Unreal Engine 5.6 C++ API: ACharacter Class Reference
ACharacter Class Reference
#include "Character.h"
Public Member Functions
void ApplyAsyncOutput (const FCharacterAsyncOutput &Output)
virtual void ApplyDamageMomentum (float DamageTaken, FDamageEvent const &DamageEvent, APawn *PawnInstigator, AActor *DamageCauser)
Apply momentum caused by damage.
virtual void BeginPlay () override
bool CanUseRootMotionRepMove (const FSimulatedRootMotionReplicatedMove &RootMotionRepMove, const FAnimMontageInstance &ClientMontageInstance) const
True if buffered move is usable to teleport client back to.
virtual void CheckJumpInput (float DeltaTime)
Trigger jump if jump button has been pressed.
virtual void ClearCrossLevelReferences () override
virtual void ClearJumpInput (float DeltaTime)
Update jump input state after having checked input.
virtual void ClientCheatFly_Implementation ()
virtual void ClientCheatGhost_Implementation ()
virtual void ClientCheatWalk_Implementation ()
void ClientMoveResponsePacked_Implementation (const FCharacterMoveResponsePackedBits &PackedBits)
bool ClientMoveResponsePacked_Validate (const FCharacterMoveResponsePackedBits &PackedBits)
DEPRECATED_CHARACTER_MOVEMENT_RPC (ClientAckGoodMove, ClientMoveResponsePacked) UFUNCTION() 1 void ClientAckGoodMove(float TimeStamp)
If no client adjustment is needed after processing received ServerMove(), ack the good move so client can remove it from SavedMoves.
DEPRECATED_CHARACTER_MOVEMENT_RPC (ClientAckGoodMove_Implementation, ClientMoveResponsePacked_Implementation) 1 void ClientAckGoodMove_Implementation(float TimeStamp)
DEPRECATED_CHARACTER_MOVEMENT_RPC (ClientAdjustPosition, ClientMoveResponsePacked) UFUNCTION() 1 void ClientAdjustPosition(float TimeStamp
Replicate position correction to client, associated with a timestamped servermove.
DEPRECATED_CHARACTER_MOVEMENT_RPC (ClientAdjustPosition_Implementation, ClientMoveResponsePacked_Implementation) 1 void ClientAdjustPosition_Implementation(float TimeStamp
DEPRECATED_CHARACTER_MOVEMENT_RPC (ClientAdjustRootMotionPosition, ClientMoveResponsePacked) UFUNCTION() 1 void ClientAdjustRootMotionPosition(float TimeStamp
Replicate position correction to client when using root motion for movement.
DEPRECATED_CHARACTER_MOVEMENT_RPC (ClientAdjustRootMotionPosition_Implementation, ClientMoveResponsePacked_Implementation) 1 void ClientAdjustRootMotionPosition_Implementation(float TimeStamp
DEPRECATED_CHARACTER_MOVEMENT_RPC (ClientAdjustRootMotionSourcePosition, ClientMoveResponsePacked) UFUNCTION() 1 void ClientAdjustRootMotionSourcePosition(float TimeStamp
Replicate root motion source correction to client when using root motion for movement.
DEPRECATED_CHARACTER_MOVEMENT_RPC (ClientAdjustRootMotionSourcePosition_Implementation, ClientMoveResponsePacked_Implementation) 1 void ClientAdjustRootMotionSourcePosition_Implementation(float TimeStamp
DEPRECATED_CHARACTER_MOVEMENT_RPC (ClientVeryShortAdjustPosition, ClientMoveResponsePacked) UFUNCTION() 1 void ClientVeryShortAdjustPosition(float TimeStamp
DEPRECATED_CHARACTER_MOVEMENT_RPC (ClientVeryShortAdjustPosition_Implementation, ClientMoveResponsePacked_Implementation) 1 void ClientVeryShortAdjustPosition_Implementation(float TimeStamp
DEPRECATED_CHARACTER_MOVEMENT_RPC (ServerMove, ServerMovePacked) UFUNCTION() 1 void ServerMove(float TimeStamp
Replicated function sent by client to server - contains client movement and view info.
DEPRECATED_CHARACTER_MOVEMENT_RPC (ServerMove_Implementation, ServerMovePacked_Implementation) 1 void ServerMove_Implementation(float TimeStamp
DEPRECATED_CHARACTER_MOVEMENT_RPC (ServerMoveDual, ServerMovePacked) UFUNCTION() 1 void ServerMoveDual(float TimeStamp0
Replicated function sent by client to server - contains client movement and view info for two moves.
DEPRECATED_CHARACTER_MOVEMENT_RPC (ServerMoveDual_Implementation, ServerMovePacked_Implementation) 1 void ServerMoveDual_Implementation(float TimeStamp0
DEPRECATED_CHARACTER_MOVEMENT_RPC (ServerMoveDualHybridRootMotion, ServerMovePacked) UFUNCTION() 1 void ServerMoveDualHybridRootMotion(float TimeStamp0
Replicated function sent by client to server - contains client movement and view info for two moves.
DEPRECATED_CHARACTER_MOVEMENT_RPC (ServerMoveDualHybridRootMotion_Implementation, ServerMovePacked_Implementation) 1 void ServerMoveDualHybridRootMotion_Implementation(float TimeStamp0
DEPRECATED_CHARACTER_MOVEMENT_RPC (ServerMoveDualNoBase, ServerMovePacked) UFUNCTION() 1 void ServerMoveDualNoBase(float TimeStamp0
Replicated function sent by client to server - contains client movement and view info for two moves.
DEPRECATED_CHARACTER_MOVEMENT_RPC (ServerMoveDualNoBase_Implementation, ServerMovePacked_Implementation) 1 void ServerMoveDualNoBase_Implementation(float TimeStamp0
DEPRECATED_CHARACTER_MOVEMENT_RPC (ServerMoveNoBase, ServerMovePacked) UFUNCTION() 1 void ServerMoveNoBase(float TimeStamp
Replicated function sent by client to server.
DEPRECATED_CHARACTER_MOVEMENT_RPC (ServerMoveNoBase_Implementation, ServerMovePacked_Implementation) 1 void ServerMoveNoBase_Implementation(float TimeStamp
DEPRECATED_CHARACTER_MOVEMENT_RPC (ServerMoveOld, ServerMovePacked) UFUNCTION() 1 void ServerMoveOld(float OldTimeStamp
DEPRECATED_CHARACTER_MOVEMENT_RPC (ServerMoveOld_Implementation, ServerMovePacked_Implementation) 1 void ServerMoveOld_Implementation(float OldTimeStamp
virtual void DisplayDebug (class UCanvas *Canvas, const FDebugDisplayInfo &DebugDisplay, float &YL, float &YPos) override
virtual void Falling ()
Called when the character's movement enters falling.
void FillAsyncInput (FCharacterAsyncInput &Input) const
Async simulation API.
template<class T>
T * FindComponentByClass () const
virtual UActorComponent * FindComponentByClass (const TSubclassOf< UActorComponent > ComponentClass) const override
int32 FindRootMotionRepMove (const FAnimMontageInstance &ClientMontageInstance) const
Find usable root motion replicated move from our buffer.
virtual void GatherCurrentMovement () override
FORCEINLINE const FBasedMovementInfo & GetBasedMovement () const
Accessor for BasedMovement.
virtual FQuat GetBaseRotationOffset () const
Get the saved rotation offset of mesh.
FORCEINLINE class UCapsuleComponent * GetCapsuleComponent () const
Returns CapsuleComponent subobject.
template<class T>
FORCEINLINE_DEBUGGABLE T * GetCharacterMovement () const
Returns CharacterMovement subobject.
FORCEINLINE UCharacterMovementComponent * GetCharacterMovement () const
virtual float GetDefaultHalfHeight () const override
Returns The half-height of the default Pawn, scaled by the component scale.
virtual FVector GetGravityDirection () const override
Returns vector direction of gravity.
virtual FQuat GetGravityTransform () const override
Returns a quaternion transforming from world space into gravity relative space.
virtual float GetJumpMaxHoldTime () const
Get the maximum jump time for the character.
FORCEINLINE class USkeletalMeshComponent * GetMesh () const
Returns Mesh subobject.
virtual UPrimitiveComponent * GetMovementBase () const override final
Return PrimitiveComponent we are based on (standing on, attached to, and moving on).
virtual UPawnMovementComponent * GetMovementComponent () const override
virtual FVector GetNavAgentLocation () const override
FORCEINLINE bool GetProxyIsJumpForceApplied () const
Indicates that this Character is currently under the force of a jump (if JumpMaxHoldTime is non-zero).
FORCEINLINE float GetReplayLastTransformUpdateTimeStamp () const
This is updated every frame to the latest timestamp, but only replicated to Replays, this is because we want to save positions to the replay replication connection each frame to ensure smooth movement.
FORCEINLINE const FBasedMovementInfo & GetReplicatedBasedMovement () const
Accessor for ReplicatedBasedMovement.
virtual FVector GetReplicatedGravityDirection () const
Returns replicated gravity direction for simulated proxies.
FORCEINLINE uint8 GetReplicatedMovementMode () const
CharacterMovement MovementMode (and custom mode) replicated for simulated proxies.
FORCEINLINE float GetReplicatedServerLastTransformUpdateTimeStamp () const
This is the value of the CharacterMovement timestamp, and is replicated down to SimulatedProxies to assist with visual smoothing of the character.
FORCEINLINE const FRepRootMotionMontage & GetRepRootMotion () const
Replicated Root Motion montage.
FRepRootMotionMontage & GetRepRootMotion_Mutable ()
Replicated Root Motion montage.
FAnimMontageInstance * GetRootMotionAnimMontageInstance () const
Get FAnimMontageInstance playing RootMotion.
virtual void GetSimpleCollisionCylinder (float &CollisionRadius, float &CollisionHalfHeight) const override
void InitializeAsyncOutput (FCharacterAsyncOutput &Output) const
bool IsCrouched () const
Set by character movement to specify that this Character is currently crouched.
virtual void Landed (const FHitResult &Hit)
Called upon landing when falling, to perform actions based on the Hit result.
virtual void MoveBlockedBy (const FHitResult &Impact)
Called when pawn's movement is blocked.
virtual void NotifyActorBeginOverlap (AActor *OtherActor)
virtual void NotifyActorEndOverlap (AActor *OtherActor)
virtual void NotifyJumpApex ()
Called when character's jump reaches Apex.
virtual void OnEndCrouch (float HalfHeightAdjust, float ScaledHalfHeightAdjust)
Called when Character stops crouching.
virtual void OnJumped_Implementation ()
virtual void OnMovementModeChanged (EMovementMode PrevMovementMode, uint8 PreviousCustomMode=0)
Called from CharacterMovementComponent to notify the character that the movement mode has changed.
virtual void OnRep_ReplicatedMovement () override
virtual void OnStartCrouch (float HalfHeightAdjust, float ScaledHalfHeightAdjust)
Called when Character crouches.
virtual void OnUpdateSimulatedPosition (const FVector &OldLocation, const FQuat &OldRotation)
Called on client after position update is received to respond to the new location and rotation.
virtual void OnWalkingOffLedge_Implementation (const FVector &PreviousFloorImpactNormal, const FVector &PreviousFloorContactNormal, const FVector &PreviousLocation, float TimeDelta)
virtual void PawnClientRestart () override
Called on the owning client of a player-controlled Pawn when it is restarted, this calls Restart()
virtual void PossessedBy (AController *NewController) override
Called when this Pawn is possessed.
virtual void PostInitializeComponents () override
virtual void PostLoad () override
virtual void PostNetReceive () override
virtual void PostNetReceiveLocationAndRotation () override
virtual void PreNetReceive () override
virtual void PreReplication (IRepChangedPropertyTracker &ChangedPropertyTracker) override
Called on the actor right before replication occurs.
virtual void PreReplicationForReplay (IRepChangedPropertyTracker &ChangedPropertyTracker) override
Called on the actor right before replication occurs.
virtual void RecalculateBaseEyeHeight () override
Set BaseEyeHeight based on current state.
void RecalculateCrouchedEyeHeight ()
Calculates the crouched eye height based on movement component settings.
virtual void ResetJumpState ()
Marks character as not trying to jump.
virtual void Restart () override
Called when the Pawn is being restarted (usually by being possessed by a Controller).
bool RestoreReplicatedMove (const FSimulatedRootMotionReplicatedMove &RootMotionRepMove)
Restore actor to an old buffered move.
virtual void RootMotionDebugClientPrintOnScreen_Implementation (const FString &InString)
void SaveRelativeBasedMovement (const FVector &NewRelativeLocation, const FRotator &NewRotation, bool bRelativeRotation)
Save a new relative location in BasedMovement and a new rotation with is either relative or absolute.
bool ServerMove_Validate (float TimeStamp, FVector_NetQuantize10 InAccel, FVector_NetQuantize100 ClientLoc, uint8 CompressedMoveFlags, uint8 ClientRoll, uint32 View, UPrimitiveComponent *ClientMovementBase, FName ClientBaseBoneName, uint8 ClientMovementMode)
bool ServerMoveDual_Validate (float TimeStamp0, FVector_NetQuantize10 InAccel0, uint8 PendingFlags, uint32 View0, float TimeStamp, FVector_NetQuantize10 InAccel, FVector_NetQuantize100 ClientLoc, uint8 NewFlags, uint8 ClientRoll, uint32 View, UPrimitiveComponent *ClientMovementBase, FName ClientBaseBoneName, uint8 ClientMovementMode)
bool ServerMoveDualHybridRootMotion_Validate (float TimeStamp0, FVector_NetQuantize10 InAccel0, uint8 PendingFlags, uint32 View0, float TimeStamp, FVector_NetQuantize10 InAccel, FVector_NetQuantize100 ClientLoc, uint8 NewFlags, uint8 ClientRoll, uint32 View, UPrimitiveComponent *ClientMovementBase, FName ClientBaseBoneName, uint8 ClientMovementMode)
bool ServerMoveDualNoBase_Validate (float TimeStamp0, FVector_NetQuantize10 InAccel0, uint8 PendingFlags, uint32 View0, float TimeStamp, FVector_NetQuantize10 InAccel, FVector_NetQuantize100 ClientLoc, uint8 NewFlags, uint8 ClientRoll, uint32 View, uint8 ClientMovementMode)
bool ServerMoveNoBase_Validate (float TimeStamp, FVector_NetQuantize10 InAccel, FVector_NetQuantize100 ClientLoc, uint8 CompressedMoveFlags, uint8 ClientRoll, uint32 View, uint8 ClientMovementMode)
bool ServerMoveOld_Validate (float OldTimeStamp, FVector_NetQuantize10 OldAccel, uint8 OldMoveFlags)
void ServerMovePacked_Implementation (const FCharacterServerMovePackedBits &PackedBits)
bool ServerMovePacked_Validate (const FCharacterServerMovePackedBits &PackedBits)
void SetAnimRootMotionTranslationScale (float InAnimRootMotionTranslationScale=1.f)
Sets scale to apply to root motion translation on this Character.
virtual void SetBase (UPrimitiveComponent *NewBase, const FName BoneName=NAME_None, bool bNotifyActor=true)
Sets the component the Character is walking on, used by CharacterMovement walking movement to be able to follow dynamic objects.
void SetIsCrouched (const bool bInIsCrouched)
Specifies whether this Character is currently crouched or not.
void SetProxyIsJumpForceApplied (const bool bInProxyIsJumpForceApplied)
Set to indicate that this Character is currently under the force of a jump (if JumpMaxHoldTime is non-zero).
virtual void SetReplicateMovement (bool bInReplicateMovement) override
Set whether this actor's movement replicates to network clients.
void SetRepRootMotion (const FRepRootMotionMontage &InRepRootMotion)
Replicated Root Motion montage.
virtual void SetupPlayerInputComponent (class UInputComponent *PlayerInputComponent) override
Allows a Pawn to set up custom input bindings.
virtual bool ShouldNotifyLanded (const struct FHitResult &Hit)
Returns true if the Landed() event should be called.
void SimulatedRootMotionPositionFixup (float DeltaSeconds)
Position fix up for Simulated Proxies playing Root Motion.
virtual void TornOff () override
virtual void TurnOff () override
Freeze pawn - stop sounds, animations, physics, weapon firing.
UFUNCTION () 1 bool CanJump() const
Check if the character can jump in the current state.
UFUNCTION () 1 bool HasAnyRootMotion() const
True if we are playing root motion from any source right now (anim root motion, root motion source)
UFUNCTION () 1 bool IsPlayingNetworkedRootMotionMontage() const
True if we are playing Root Motion right now, through a Montage with RootMotionMode == ERootMotionMode::RootMotionFromMontagesOnly.
UFUNCTION () 1 class UAnimMontage *GetCurrentMontage() const
Return current playing Montage.
UFUNCTION () 1 float GetAnimRootMotionTranslationScale() const
Scale to apply to root motion translation on this Character.
UFUNCTION () 1 virtual bool CanCrouch() const
UFUNCTION () 1 virtual bool IsJumpProvidingForce() const
True if jump is actively providing a force, such as when the jump key is held and the time it has been held is less than JumpMaxHoldTime.
UFUNCTION () 1 virtual float PlayAnimMontage(class UAnimMontage *AnimMontage
Play Animation Montage on the character mesh.
UFUNCTION () 1 virtual void CacheInitialMeshOffset(FVector MeshRelativeLocation
Cache mesh offset from capsule.
UFUNCTION () 1 virtual void Jump()
Make the character jump on the next update.
UFUNCTION () 1 virtual void LaunchCharacter(FVector LaunchVelocity
Set a pending launch velocity on the Character.
UPROPERTY() uint8 bIsCrouched UPROPERTY() uint8 bProxyIsJumpForceApplied UFUNCTION () 1 virtual void OnRep_IsCrouched()
Flag that we are receiving replication of the based movement.
UFUNCTION () 1 virtual void OnRep_ReplicatedBasedMovement()
Rep notify for ReplicatedBasedMovement.
UFUNCTION () 1 virtual void StopAnimMontage(class UAnimMontage *AnimMontage
Stop Animation Montage.
UFUNCTION () 1 virtual void StopJumping()
Stop the character from jumping on the next update.
UFUNCTION () 1 void ClientCheatFly()
UFUNCTION () 1 void ClientCheatGhost()
UFUNCTION () 1 void ClientCheatWalk()
UFUNCTION () 1 void ClientMoveResponsePacked(const FCharacterMoveResponsePackedBits &PackedBits)
UFUNCTION () 1 void OnJumped()
Event fired when the character has just started jumping.
UFUNCTION () 1 void OnLanded(const FHitResult &Hit)
Called upon landing when falling, to perform actions based on the Hit result.
UFUNCTION () 1 void OnLaunched(FVector LaunchVelocity
Let blueprint know that we were launched.
UFUNCTION () 1 void OnRep_ReplayLastTransformUpdateTimeStamp()
UFUNCTION () 1 void OnRep_RootMotion()
Handles replicated root motion properties on simulated proxies and position correction.
UFUNCTION () 1 void OnWalkingOffLedge(const FVector &PreviousFloorImpactNormal
Event fired when the Character is walking off a surface and is about to fall because CharacterMovement->CurrentFloor became unwalkable.
UFUNCTION () 1 void RootMotionDebugClientPrintOnScreen(const FString &InString)
UFUNCTION () 1 void ServerMovePacked(const FCharacterServerMovePackedBits &PackedBits)
UFUNCTION () FVector GetBaseTranslationOffset() const
Get the saved translation offset of mesh.
UFUNCTION ()) 1 bool IsPlayingRootMotion() const
True if we are playing Anim root motion right now.
UFUNCTION ()) 1 virtual void Crouch(bool bClientSimulation
Request the character to start crouching.
UFUNCTION ()) 1 virtual void UnCrouch(bool bClientSimulation
Request the character to stop crouching.
UFUNCTION ()) 1 void K2_OnEndCrouch(float HalfHeightAdjust
Event when Character stops crouching.
UFUNCTION ()) 1 void K2_OnMovementModeChanged(EMovementMode PrevMovementMode
Called from CharacterMovementComponent to notify the character that the movement mode has changed.
UFUNCTION ()) 1 void K2_OnStartCrouch(float HalfHeightAdjust
Event when Character crouches.
UFUNCTION ()) 1 void K2_UpdateCustomMovement(float DeltaTime)
Event for implementing custom character movement mode.
UFUNCTION ()) FRotator GetBaseRotationOffsetRotator() const
Get the saved rotation offset of mesh.
virtual void UnPossessed () override
Called when our Controller no longer possesses us.
virtual void UpdateNavigationRelevance () override
Update all components relevant for navigation generators to match bCanAffectNavigationGeneration flag.
UPROPERTY () FCharacterMovementUpdatedSignature OnCharacterMovementUpdated
Event triggered at the end of a CharacterMovementComponent movement update.
UPROPERTY () FCharacterReachedApexSignature OnReachedJumpApex
Broadcast when Character's jump reaches its apex.
UPROPERTY () FLandedSignature LandedDelegate
Called upon landing when falling, to perform actions based on the Hit result.
UPROPERTY () float CrouchedEyeHeight
Default crouched eye height.
UPROPERTY () float JumpForceTimeRemaining
Amount of jump force time remaining, if JumpMaxHoldTime > 0.
UPROPERTY () float JumpKeyHoldTime
Jump key Held Time.
UPROPERTY () float ProxyJumpForceStartedTime
Track last time a jump force started for a proxy.
UPROPERTY () FMovementModeChangedSignature MovementModeChangedDelegate
Multicast delegate for MovementMode changing.
UPROPERTY () FRootMotionMovementParams ClientRootMotionParams
For LocallyControlled Autonomous clients.
UPROPERTY () FRootMotionSourceGroup SavedRootMotion
For LocallyControlled Autonomous clients.
UPROPERTY () int32 JumpCurrentCount
Tracks the current number of jumps performed.
UPROPERTY () int32 JumpCurrentCountPreJump
Represents the current number of jumps performed before CheckJumpInput modifies JumpCurrentCount.
UPROPERTY () int32 JumpMaxCount
The max number of jumps the character can perform.
UPROPERTY () struct FRepRootMotionMontage RepRootMotion
Replicated Root Motion montage.
UPROPERTY () TArray< FSimulatedRootMotionReplicatedMove > RootMotionRepMoves
Array of previously received root motion moves from the server.
UPROPERTY ()) float JumpMaxHoldTime
The max time the jump key can be held.
Public Member Functions inherited from APawn
virtual void BecomeViewTarget (APlayerController *PC) override
virtual bool CanBeBaseForCharacter (APawn *APawn) const override
Overridden to defer to the RootComponent's CanCharacterStepUpOn setting if it is explicitly Yes or No.
virtual void Destroyed () override
virtual void DisableInput (APlayerController *PlayerController) override
void DispatchRestart (bool bCallClientRestart)
Wrapper function to call correct restart functions, enable bCallClientRestart if this is a locally owned player pawn or equivalent.
virtual void EditorApplyRotation (const FRotator &DeltaRotation, bool bAltDown, bool bShiftDown, bool bCtrlDown) override
virtual void EnableInput (APlayerController *PlayerController) override
virtual void EndPlay (const EEndPlayReason::Type EndPlayReason) override
virtual void EndViewTarget (APlayerController *PC) override
virtual void FaceRotation (FRotator NewControlRotation, float DeltaTime=0.f)
Updates Pawn's rotation to the given rotation, assumed to be the Controller's ControlRotation.
virtual void GetActorEyesViewPoint (FVector &Location, FRotator &Rotation) const override
template<class T>
T * GetController () const
Returns controller for this actor cast to the template type.
virtual FString GetHumanReadableName () const override
virtual void GetMoveGoalReachTest (const AActor *MovingActor, const FVector &MoveOffset, FVector &GoalOffset, float &GoalRadius, float &GoalHalfHeight) const override
Get cylinder for testing if actor has been reached.
virtual const FNavAgentProperties & GetNavAgentPropertiesRef () const override
virtual class UNetConnection * GetNetConnection () const override
virtual const AActor * GetNetOwner () const override
virtual UPlayer * GetNetOwningPlayer () override
virtual UPlayer * GetNetOwningPlayerAnyRole () override
virtual UPawnNoiseEmitterComponent * GetPawnNoiseEmitterComponent () const
Return our PawnNoiseEmitterComponent, if any.
virtual FVector GetPawnViewLocation () const
Returns Pawn's eye location.
virtual APhysicsVolume * GetPhysicsVolume () const override
Return Physics Volume for this Pawn.
APlayerState * GetPlayerState () const
If Pawn is possessed by a player, returns its Player State.
template<class T>
T * GetPlayerState () const
Templated convenience version of GetPlayerState.
template<class T>
T * GetPlayerStateChecked () const
Templated convenience version of GetPlayerState which checks the type is as presumed.
FORCEINLINE uint16 GetRemoteViewPitch () const
Replicated pitch value so we can see where remote clients are looking.
virtual FVector GetVelocity () const override
virtual FRotator GetViewRotation () const
Get the view rotation of the Pawn (direction they are looking, normally Controller->ControlRotation).
virtual bool InFreeCam () const
Returns true if player is viewing this Pawn in FreeCam.
bool InputEnabled () const
Whether this Pawn's input handling is enabled.
void Internal_AddMovementInput (FVector WorldAccel, bool bForce=false)
Internal function meant for use only within Pawn or by a PawnMovementComponent.
FVector Internal_ConsumeMovementInputVector ()
Internal function meant for use only within Pawn or by a PawnMovementComponent.
FVector Internal_GetLastMovementInputVector () const
Internal function meant for use only within Pawn or by a PawnMovementComponent.
FVector Internal_GetPendingMovementInputVector () const
Internal function meant for use only within Pawn or by a PawnMovementComponent.
virtual bool IsBasedOnActor (const AActor *Other) const override
bool IsLocalPlayerControllerViewingAPawn () const
virtual bool IsNetRelevantFor (const AActor *RealViewer, const AActor *ViewTarget, const FVector &SrcLocation) const override
void MoveIgnoreActorAdd (AActor *ActorToIgnore)
Add an Actor to ignore by Pawn's movement collision.
void MoveIgnoreActorRemove (AActor *ActorToIgnore)
Remove an Actor to ignore by Pawn's movement collision.
virtual void NotifyControllerChanged ()
Call to notify about a change in controller, on both the server and owning client.
virtual void NotifyRestarted ()
Notifies other systems that a pawn has been restarted.
virtual void OutsideWorldBounds () override
virtual void PawnStartFire (uint8 FireModeNum=0)
Handle StartFire() passed from PlayerController.
virtual void PostEditChangeProperty (struct FPropertyChangedEvent &PropertyChangedEvent) override
virtual void PostNetReceiveVelocity (const FVector &NewVelocity) override
virtual void PostRegisterAllComponents () override
virtual void PreInitializeComponents () override
virtual bool ReachedDesiredRotation ()
Return true if yaw is within AllowedYawError of desired yaw.
virtual void Reset () override
void SetController (AController *InController)
Sets controller for this actor.
virtual void SetPlayerDefaults ()
Make sure pawn properties are back to default.
void SetPlayerState (APlayerState *NewPlayerState)
Set the Pawn's Player State.
void SetRemoteViewPitch (double NewRemoteViewPitch)
Set Pawn ViewPitch, so we can see where remote clients are looking.
virtual bool ShouldTakeDamage (float Damage, FDamageEvent const &DamageEvent, AController *EventInstigator, AActor *DamageCauser) const
Return true if we are in a state to take damage (checked at the start of TakeDamage.
virtual bool ShouldTickIfViewportsOnly () const override
virtual float TakeDamage (float Damage, struct FDamageEvent const &DamageEvent, AController *EventInstigator, AActor *DamageCauser) override
virtual void TeleportSucceeded (bool bIsATest) override
UE_DEPRECATED (4.24, "IsControlled is deprecated. To check if this pawn is controlled by anything, then call IsPawnControlled. To check if this pawn is controlled only by the player then call IsPlayerControlled") UFUNCTION() 1 bool IsControlled() const
See if this actor is currently being controlled.
UE_DEPRECATED (5.0, "GetPawnPhysicsVolume is deprecated. Please use GetPhysicsVolume instead.") 1 virtual APhysicsVolume *GetPawnPhysicsVolume() const
Return Physics Volume for this Pawn.
UE_DEPRECATED (5.6, "This property is deprecated, use GetRemoteViewPitch()/RemoteViewPitch16 instead.") UPROPERTY() uint8 RemoteViewPitch
DEPRECTED, use RemoteViewPitch16 instead.
UFUNCTION () 1 APlayerController *GetLocalViewingPlayerController() const
Returns local Player Controller viewing this pawn, whether it is controlling or spectating.
UFUNCTION () 1 bool IsLocallyViewed() const
UFUNCTION () 1 FPlatformUserId GetPlatformUserId() const
Returns the Platform User ID of the PlayerController that is controlling this character.
UFUNCTION () 1 FRotator GetControlRotation() const
Get the rotation of the Controller, often the 'view' rotation of this Pawn.
UFUNCTION () 1 TSubclassOf< UInputComponent > GetOverrideInputComponentClass() const
UFUNCTION () 1 virtual bool IsBotControlled() const
Returns true if controlled by a bot.
UFUNCTION () 1 virtual bool IsLocallyControlled() const
Returns true if controlled by a local (not network) Controller.
UFUNCTION () 1 virtual bool IsMoveInputIgnored() const
Helper to see if move input is ignored.
UFUNCTION () 1 virtual bool IsPawnControlled() const
Check if this actor is currently being controlled at all (the actor has a valid Controller, which will be false for remote clients)
UFUNCTION () 1 virtual bool IsPlayerControlled() const
Returns true if controlled by a human player (possessed by a PlayerController).
UFUNCTION () 1 virtual FRotator GetBaseAimRotation() const
Return the aim rotation for the Pawn.
UFUNCTION () 1 virtual void OnRep_Controller()
Called when Controller is replicated.
UFUNCTION () 1 virtual void OnRep_PlayerState()
PlayerState Replication Notification Callback.
UFUNCTION () 1 virtual void SpawnDefaultController()
Spawn default controller for this Pawn, and get possessed by it.
UFUNCTION () 1 void PawnMakeNoise(float Loudness
Inform AIControllers that you've made a noise they might hear (they are sent a HearNoise message if they have bHearNoises==true) The instigator of this sound is the pawn which is used to call MakeNoise.
UFUNCTION () 1 void ReceiveControllerChanged(AController *OldController
Event called after a pawn's controller has changed, on the server and owning client.
UFUNCTION () 1 void ReceiveRestarted()
Event called after a pawn has been restarted, usually by a possession change.
UFUNCTION () AController *GetController() const
Returns controller for this actor.
UFUNCTION () static 1 AActor *GetMovementBaseActor(const APawn *Pawn)
Gets the owning actor of the Movement Base Component on which the pawn is standing.
UFUNCTION () virtual FVector GetNavAgentLocation() const override
Basically retrieved pawn's location on navmesh.
UFUNCTION ()) 1 FVector GetLastMovementInputVector() const
Return the last input vector in world space that was processed by ConsumeMovementInputVector(), which is usually done by the Pawn or PawnMovementComponent.
UFUNCTION ()) 1 FVector GetPendingMovementInputVector() const
Return the pending input vector in world space.
UFUNCTION ()) 1 virtual FVector ConsumeMovementInputVector()
Returns the pending input vector and resets it to zero.
UFUNCTION ()) 1 virtual void AddControllerPitchInput(float Val)
Add input (affecting Pitch) to the Controller's ControlRotation, if it is a local PlayerController.
UFUNCTION ()) 1 virtual void AddControllerRollInput(float Val)
Add input (affecting Roll) to the Controller's ControlRotation, if it is a local PlayerController.
UFUNCTION ()) 1 virtual void AddControllerYawInput(float Val)
Add input (affecting Yaw) to the Controller's ControlRotation, if it is a local PlayerController.
UFUNCTION ()) 1 virtual void AddMovementInput(FVector WorldDirection
Add movement input along the given world direction vector (usually normalized) scaled by 'ScaleValue'.
UFUNCTION ()) 1 virtual void DetachFromControllerPendingDestroy()
Call this function to detach safely pawn from its controller, knowing that we will be destroyed soon.
UFUNCTION ()) 1 void ReceivePossessed(AController *NewController)
Event called when the Pawn is possessed by a Controller.
UFUNCTION ()) 1 void ReceiveUnpossessed(AController *OldController)
Event called when the Pawn is no longer possessed by a Controller.
UFUNCTION ()) 1 void SetCanAffectNavigationGeneration(bool bNewValue
Use SetCanAffectNavigationGeneration to change this value at runtime.
void UpdateNavAgent ()
Updates MovementComponent's parameters used by navigation system.
UPROPERTY ()
Default class to use when pawn is controlled by AI.
UPROPERTY() TEnumAsByte< EAutoReceiveInput UPROPERTY () EAutoPossessAI AutoPossessAI
Determines which PlayerController, if any, should automatically possess the pawn when the level starts or when the pawn is spawned.
UPROPERTY () float BaseEyeHeight
Base eye height above collision center.
UPROPERTY () FPawnControllerChangedSignature ReceiveControllerChangedDelegate
Event called after a pawn's controller has changed, on the server and owning client.
UPROPERTY () FPawnRestartedSignature ReceiveRestartedDelegate
Event called after a pawn has been restarted, usually by a possession change.
UPROPERTY () TObjectPtr< AController > Controller
Controller currently possessing this Actor.
UPROPERTY () TObjectPtr< AController > LastHitBy
Controller of the last Actor that caused us damage.
UPROPERTY () TObjectPtr< AController > PreviousController
Previous controller that was controlling this pawn since the last controller change notification.
Data Fields
FVector FVector UPrimitiveComponent FName bool bool bBaseRelativePosition
FVector UPrimitiveComponent FName bool bool bBaseRelativePosition
float FVector FVector_NetQuantizeNormal float UPrimitiveComponent FName bool bool bBaseRelativePosition
FRootMotionSourceGroup bool float FVector FVector_NetQuantizeNormal float UPrimitiveComponent FName bool bool bBaseRelativePosition
FRootMotionSourceGroup bool bHasAnimRootMotion
FVector FVector UPrimitiveComponent FName bool bHasBase
FVector UPrimitiveComponent FName bool bHasBase
float FVector FVector_NetQuantizeNormal float UPrimitiveComponent FName bool bHasBase
FRootMotionSourceGroup bool float FVector FVector_NetQuantizeNormal float UPrimitiveComponent FName bool bHasBase
bool bXYOverride
bool bool bZOverride
FVector_NetQuantize10 FVector_NetQuantize100 uint8 uint8 uint32 UPrimitiveComponent FName ClientBaseBoneName
FVector_NetQuantize10 uint8 uint32 float FVector_NetQuantize10 FVector_NetQuantize100 uint8 uint8 uint32 UPrimitiveComponent FName ClientBaseBoneName
FVector_NetQuantize10 FVector_NetQuantize100 ClientLoc
FVector_NetQuantize10 uint8 uint32 float FVector_NetQuantize10 FVector_NetQuantize100 ClientLoc
FVector_NetQuantize10 FVector_NetQuantize100 uint8 uint8 uint32 UPrimitiveComponent * ClientMovementBase
FVector_NetQuantize10 uint8 uint32 float FVector_NetQuantize10 FVector_NetQuantize100 uint8 uint8 uint32 UPrimitiveComponent * ClientMovementBase
FVector_NetQuantize10 FVector_NetQuantize100 uint8 uint8 uint32 UPrimitiveComponent FName uint8 ClientMovementMode
FVector_NetQuantize10 FVector_NetQuantize100 uint8 uint8 uint32 uint8 ClientMovementMode
FVector_NetQuantize10 uint8 uint32 float FVector_NetQuantize10 FVector_NetQuantize100 uint8 uint8 uint32 UPrimitiveComponent FName uint8 ClientMovementMode
FVector_NetQuantize10 uint8 uint32 float FVector_NetQuantize10 FVector_NetQuantize100 uint8 uint8 uint32 uint8 ClientMovementMode
FVector_NetQuantize10 FVector_NetQuantize100 uint8 uint8 ClientRoll
FVector_NetQuantize10 uint8 uint32 float FVector_NetQuantize10 FVector_NetQuantize100 uint8 uint8 ClientRoll
FVector_NetQuantize10 FVector_NetQuantize100 uint8 CompressedMoveFlags
FVector_NetQuantize10 InAccel
FVector_NetQuantize10 uint8 uint32 float FVector_NetQuantize10 InAccel
FVector_NetQuantize10 InAccel0
float InPlayRate = 1.f
FRotator MeshRelativeRotation
FVector FVector UPrimitiveComponent * NewBase
FVector UPrimitiveComponent * NewBase
FVector FVector UPrimitiveComponent FName NewBaseBoneName
FVector UPrimitiveComponent FName NewBaseBoneName
EMovementMode uint8 uint8 NewCustomMode
FVector_NetQuantize10 uint8 uint32 float FVector_NetQuantize10 FVector_NetQuantize100 uint8 NewFlags
FVector NewLoc
EMovementMode NewMovementMode
FVector FVector NewVel
uint32 NumActorOverlapEventsCounter
Incremented every time there is an Actor overlap event (start or stop) on this actor.
FVector_NetQuantize10 OldAccel
FVector_NetQuantize10 uint8 OldMoveFlags
FVector_NetQuantize10 uint8 PendingFlags
EMovementMode uint8 PrevCustomMode
const FVector & PreviousFloorContactNormal
const FVector const FVector & PreviousLocation
float ScaledHalfHeightAdjust
float FVector FVector_NetQuantizeNormal float UPrimitiveComponent * ServerBase
FRootMotionSourceGroup bool float FVector FVector_NetQuantizeNormal float UPrimitiveComponent * ServerBase
float FVector FVector_NetQuantizeNormal float UPrimitiveComponent FName ServerBoneName
FRootMotionSourceGroup bool float FVector FVector_NetQuantizeNormal float UPrimitiveComponent FName ServerBoneName
float FVector ServerLoc
FRootMotionSourceGroup bool float FVector ServerLoc
float ServerMontageTrackPosition
FRootMotionSourceGroup bool float ServerMontageTrackPosition
FVector FVector UPrimitiveComponent FName bool bool uint8 ServerMovementMode
FVector UPrimitiveComponent FName bool bool uint8 ServerMovementMode
float FVector FVector_NetQuantizeNormal float UPrimitiveComponent FName bool bool uint8 ServerMovementMode
FRootMotionSourceGroup bool float FVector FVector_NetQuantizeNormal float UPrimitiveComponent FName bool bool uint8 ServerMovementMode
FRootMotionSourceGroup ServerRootMotion
float FVector FVector_NetQuantizeNormal ServerRotation
FRootMotionSourceGroup bool float FVector FVector_NetQuantizeNormal ServerRotation
float FVector FVector_NetQuantizeNormal float ServerVelZ
FRootMotionSourceGroup bool float FVector FVector_NetQuantizeNormal float ServerVelZ
float FName StartSectionName = NAME_None)
const FVector const FVector float TimeDelta
FVector_NetQuantize10 uint8 uint32 float TimeStamp
FVector_NetQuantize10 FVector_NetQuantize100 uint8 uint8 uint32 View
FVector_NetQuantize10 uint8 uint32 float FVector_NetQuantize10 FVector_NetQuantize100 uint8 uint8 uint32 View
FVector_NetQuantize10 uint8 uint32 View0
Data Fields inherited from APawn
float AllowedYawError
Max difference between pawn's Rotation.Yaw and GetDesiredRotation().Yaw for pawn to be considered as having reached its desired rotation.
float bool bForce = false)
bool bForceUpdate = false)
FVector bool bUseNoiseMakerLocation = true
AController * NewController
FVector NoiseLocation
FVector bool AActor * NoiseMaker = nullptr)
float ScaleValue = 1.0f
Static Public Attributes
static FName CapsuleComponentName
Name of the CapsuleComponent.
static FName CharacterMovementComponentName
Name of the CharacterMovement component.
static FName MeshComponentName
Name of the MeshComponent.
Static Public Attributes inherited from APawn
static FOnPawnBeginPlay OnPawnBeginPlay
a delegate that broadcasts a notification whenever BeginPlay() is called
Protected Member Functions
virtual void BaseChange ()
Event called after actor's base changes (if SetBase was requested to notify us with bNotifyPawn).
virtual bool CanJumpInternal_Implementation () const
FBasedMovementInfo & GetReplicatedBasedMovement_Mutable ()
This is the Replicated version of relative movement.
bool JumpIsAllowedInternal () const
void SetReplayLastTransformUpdateTimeStamp (const float InReplayLastTransformUpdateTimeStamp)
This is updated every frame to the latest timestamp, but only replicated to Replays, this is because we want to save positions to the replay replication connection each frame to ensure smooth movement.
void SetReplicatedBasedMovement (const FBasedMovementInfo &InReplicatedBasedMovement)
This is the Replicated version of relative movement.
void SetReplicatedGravityDirection (const FVector &InReplicatedGravityDirection)
CharacterMovement Custom gravity direction replicated for simulated proxies.
void SetReplicatedMovementMode (const uint8 InReplicatedMovementMode)
Sets CharacterMovement MovementMode (and custom mode) replicated for simulated proxies.
void SetReplicatedServerLastTransformUpdateTimeStamp (const float InReplicatedServerLastTransformUpdateTimeStamp)
This is the value of the CharacterMovement timestamp, and is replicated down to SimulatedProxies to assist with visual smoothing of the character.
virtual bool ShouldReplicateAcceleration () const
Whether this Character should include acceleration data in its replicated movement.
UFUNCTION ()) 1 bool CanJumpInternal() const
Customizable event to check if the character can jump in the current state.
UPROPERTY () float AnimRootMotionTranslationScale
Scale to apply to root motion translation on this Character.
UPROPERTY () float ReplayLastTransformUpdateTimeStamp
UPROPERTY () float ReplicatedServerLastTransformUpdateTimeStamp
CharacterMovement ServerLastTransformUpdateTimeStamp value, replicated to simulated proxies.
UPROPERTY () FQuat BaseRotationOffset
Saved rotation offset of mesh.
UPROPERTY () FVector BaseTranslationOffset
Saved translation offset of mesh.
UPROPERTY () FVector_NetQuantizeNormal ReplicatedGravityDirection
CharacterMovement Custom gravity direction replicated for simulated proxies.
UPROPERTY () struct FBasedMovementInfo BasedMovement
Info about our current movement base (object we are standing on).
UPROPERTY () struct FBasedMovementInfo ReplicatedBasedMovement
Replicated version of relative movement.
UPROPERTY () uint8 ReplicatedMovementMode
When true, player wants to jump.
Protected Member Functions inherited from APawn
virtual UInputComponent * CreatePlayerInputComponent ()
Creates an InputComponent that can be used for custom input bindings.
virtual void DestroyPlayerInputComponent ()
Destroys the player input component and removes any references to it.
virtual AController * GetDamageInstigator (AController *InstigatedBy, const UDamageType &DamageType) const
Get the controller instigating the damage.
virtual void OnPlayerStateChanged (APlayerState *NewPlayerState, APlayerState *OldPlayerState)
Called on both the clientand server when ever SetPlayerState is called on this pawn.
UPROPERTY () FVector ControlInputVector
Accumulated control input vector, stored in world space.
UPROPERTY () FVector LastControlInputVector
The last control input vector that was processed by ConsumeMovementInputVector().
UPROPERTY () TSubclassOf< UInputComponent > OverrideInputComponentClass
If set, then this InputComponent class will be used instead of the Input Settings' DefaultInputComponentClass.
UPROPERTY () uint16 RemoteViewPitch16
Replicated so we can see where remote clients are looking.
Protected Attributes
FVector_NetQuantizeNormal PreNetReceivedGravityDirection
Cached version of the replicated gravity direction before replication.
Private Member Functions
virtual GENERATED_BODY() public void GetLifetimeReplicatedProps (TArray< FLifetimeProperty > &OutLifetimeProps) const override
Default UObject constructor.
virtual void GetReplicatedCustomConditionState (FCustomPropertyConditionState &OutActiveState) const override
UPROPERTY ()) TObjectPtr< UCapsuleComponent > CapsuleComponent
The CapsuleComponent being used for movement collision (by CharacterMovement).
UPROPERTY ()) TObjectPtr< UCharacterMovementComponent > CharacterMovement
Movement component used for movement logic in various movement modes (walking, falling, etc), containing relevant settings and functions to control movement.
UPROPERTY ()) TObjectPtr< USkeletalMeshComponent > Mesh
The main skeletal mesh associated with this Character (optional sub-object).
Detailed Description
Definition at line 241 of file Character.h.
Member Function Documentation
ApplyAsyncOutput()
void ACharacter::ApplyAsyncOutput (const FCharacterAsyncOutput & Output)
References ApplyAsyncOutput(), and INavAgentInterface::const.
Referenced by ApplyAsyncOutput().
ApplyDamageMomentum()
virtual void ACharacter::ApplyDamageMomentum (float DamageTaken, FDamageEvent const & DamageEvent, APawn * PawnInstigator, AActor * DamageCauser) virtual
Apply momentum caused by damage.
References DamageCauser.
BaseChange()
virtual void ACharacter::BaseChange () protected virtual
Event called after actor's base changes (if SetBase was requested to notify us with bNotifyPawn).
References BaseChange().
Referenced by BaseChange().
BeginPlay()
virtual void ACharacter::BeginPlay () override virtual
Reimplemented from APawn.
References BeginPlay().
Referenced by BeginPlay().
CanJumpInternal_Implementation()
virtual bool ACharacter::CanJumpInternal_Implementation () const protected virtual
References CanJumpInternal_Implementation(), and INavAgentInterface::const.
Referenced by CanJumpInternal_Implementation().
CanUseRootMotionRepMove()
bool ACharacter::CanUseRootMotionRepMove (const FSimulatedRootMotionReplicatedMove & RootMotionRepMove, const FAnimMontageInstance & ClientMontageInstance) const
True if buffered move is usable to teleport client back to.
References CanUseRootMotionRepMove(), and INavAgentInterface::const.
Referenced by CanUseRootMotionRepMove().
CheckJumpInput()
virtual void ACharacter::CheckJumpInput (float DeltaTime) virtual
Trigger jump if jump button has been pressed.
References CheckJumpInput(), and DeltaTime.
Referenced by CheckJumpInput().
ClearCrossLevelReferences()
virtual void ACharacter::ClearCrossLevelReferences () override virtual
References ClearCrossLevelReferences().
Referenced by ClearCrossLevelReferences().
ClearJumpInput()
virtual void ACharacter::ClearJumpInput (float DeltaTime) virtual
Update jump input state after having checked input.
References ClearJumpInput(), and DeltaTime.
Referenced by ClearJumpInput().
ClientCheatFly_Implementation()
virtual void ACharacter::ClientCheatFly_Implementation () virtual
References ClientCheatFly_Implementation().
Referenced by ClientCheatFly_Implementation().
ClientCheatGhost_Implementation()
virtual void ACharacter::ClientCheatGhost_Implementation () virtual
References ClientCheatGhost_Implementation().
Referenced by ClientCheatGhost_Implementation().
ClientCheatWalk_Implementation()
virtual void ACharacter::ClientCheatWalk_Implementation () virtual
References ClientCheatWalk_Implementation().
Referenced by ClientCheatWalk_Implementation().
ClientMoveResponsePacked_Implementation()
void ACharacter::ClientMoveResponsePacked_Implementation (const FCharacterMoveResponsePackedBits & PackedBits)
Referenced by DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), and DEPRECATED_CHARACTER_MOVEMENT_RPC().
ClientMoveResponsePacked_Validate()
bool ACharacter::ClientMoveResponsePacked_Validate (const FCharacterMoveResponsePackedBits & PackedBits)
DEPRECATED_CHARACTER_MOVEMENT_RPC() [1/22]
ACharacter::DEPRECATED_CHARACTER_MOVEMENT_RPC (ClientAckGoodMove , ClientMoveResponsePacked)
If no client adjustment is needed after processing received ServerMove(), ack the good move so client can remove it from SavedMoves.
References DEPRECATED_CHARACTER_MOVEMENT_RPC(), TimeStamp, and UFUNCTION().
DEPRECATED_CHARACTER_MOVEMENT_RPC() [2/22]
ACharacter::DEPRECATED_CHARACTER_MOVEMENT_RPC (ClientAckGoodMove_Implementation , ClientMoveResponsePacked_Implementation)
References ClientMoveResponsePacked_Implementation(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), and TimeStamp.
DEPRECATED_CHARACTER_MOVEMENT_RPC() [3/22]
ACharacter::DEPRECATED_CHARACTER_MOVEMENT_RPC (ClientAdjustPosition , ClientMoveResponsePacked)
Replicate position correction to client, associated with a timestamped servermove.
Client will replay subsequent moves after applying adjustment.
References DEPRECATED_CHARACTER_MOVEMENT_RPC(), and UFUNCTION().
DEPRECATED_CHARACTER_MOVEMENT_RPC() [4/22]
ACharacter::DEPRECATED_CHARACTER_MOVEMENT_RPC (ClientAdjustPosition_Implementation , ClientMoveResponsePacked_Implementation)
References bBaseRelativePosition, bHasBase, ClientMoveResponsePacked_Implementation(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), FVector, NewBase, NewBaseBoneName, NewLoc, NewVel, ServerMovementMode, and TimeStamp.
DEPRECATED_CHARACTER_MOVEMENT_RPC() [5/22]
ACharacter::DEPRECATED_CHARACTER_MOVEMENT_RPC (ClientAdjustRootMotionPosition , ClientMoveResponsePacked)
Replicate position correction to client when using root motion for movement.
(animation root motion specific)
References DEPRECATED_CHARACTER_MOVEMENT_RPC(), and UFUNCTION().
DEPRECATED_CHARACTER_MOVEMENT_RPC() [6/22]
ACharacter::DEPRECATED_CHARACTER_MOVEMENT_RPC (ClientAdjustRootMotionPosition_Implementation , ClientMoveResponsePacked_Implementation)
References bBaseRelativePosition, bHasBase, ClientMoveResponsePacked_Implementation(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), FVector, ServerBase, ServerBoneName, ServerLoc, ServerMontageTrackPosition, ServerMovementMode, ServerRotation, ServerVelZ, and TimeStamp.
DEPRECATED_CHARACTER_MOVEMENT_RPC() [7/22]
ACharacter::DEPRECATED_CHARACTER_MOVEMENT_RPC (ClientAdjustRootMotionSourcePosition , ClientMoveResponsePacked)
Replicate root motion source correction to client when using root motion for movement.
References DEPRECATED_CHARACTER_MOVEMENT_RPC(), and UFUNCTION().
DEPRECATED_CHARACTER_MOVEMENT_RPC() [8/22]
ACharacter::DEPRECATED_CHARACTER_MOVEMENT_RPC (ClientAdjustRootMotionSourcePosition_Implementation , ClientMoveResponsePacked_Implementation)
References bBaseRelativePosition, bHasAnimRootMotion, bHasBase, ClientMoveResponsePacked_Implementation(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), FVector, ServerBase, ServerBoneName, ServerLoc, ServerMontageTrackPosition, ServerMovementMode, ServerRootMotion, ServerRotation, ServerVelZ, and TimeStamp.
DEPRECATED_CHARACTER_MOVEMENT_RPC() [9/22]
ACharacter::DEPRECATED_CHARACTER_MOVEMENT_RPC (ClientVeryShortAdjustPosition , ClientMoveResponsePacked)
References DEPRECATED_CHARACTER_MOVEMENT_RPC(), and UFUNCTION().
DEPRECATED_CHARACTER_MOVEMENT_RPC() [10/22]
ACharacter::DEPRECATED_CHARACTER_MOVEMENT_RPC (ClientVeryShortAdjustPosition_Implementation , ClientMoveResponsePacked_Implementation)
References bBaseRelativePosition, bHasBase, ClientMoveResponsePacked_Implementation(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), FVector, NewBase, NewBaseBoneName, NewLoc, ServerMovementMode, and TimeStamp.
DEPRECATED_CHARACTER_MOVEMENT_RPC() [11/22]
ACharacter::DEPRECATED_CHARACTER_MOVEMENT_RPC (ServerMove , ServerMovePacked)
Replicated function sent by client to server - contains client movement and view info.
Referenced by DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), and DEPRECATED_CHARACTER_MOVEMENT_RPC().
DEPRECATED_CHARACTER_MOVEMENT_RPC() [12/22]
ACharacter::DEPRECATED_CHARACTER_MOVEMENT_RPC (ServerMove_Implementation , ServerMovePacked_Implementation)
References ClientBaseBoneName, ClientLoc, ClientMovementBase, ClientMovementMode, ClientRoll, CompressedMoveFlags, DEPRECATED_CHARACTER_MOVEMENT_RPC(), InAccel, ServerMovePacked_Implementation(), TimeStamp, and View.
DEPRECATED_CHARACTER_MOVEMENT_RPC() [13/22]
ACharacter::DEPRECATED_CHARACTER_MOVEMENT_RPC (ServerMoveDual , ServerMovePacked)
Replicated function sent by client to server - contains client movement and view info for two moves.
References DEPRECATED_CHARACTER_MOVEMENT_RPC(), and UFUNCTION().
DEPRECATED_CHARACTER_MOVEMENT_RPC() [14/22]
ACharacter::DEPRECATED_CHARACTER_MOVEMENT_RPC (ServerMoveDual_Implementation , ServerMovePacked_Implementation)
References ClientBaseBoneName, ClientLoc, ClientMovementBase, ClientMovementMode, ClientRoll, DEPRECATED_CHARACTER_MOVEMENT_RPC(), InAccel, InAccel0, NewFlags, PendingFlags, ServerMovePacked_Implementation(), TimeStamp, View, and View0.
DEPRECATED_CHARACTER_MOVEMENT_RPC() [15/22]
ACharacter::DEPRECATED_CHARACTER_MOVEMENT_RPC (ServerMoveDualHybridRootMotion , ServerMovePacked)
Replicated function sent by client to server - contains client movement and view info for two moves.
First move is non root motion, second is root motion.
References ClientBaseBoneName, ClientLoc, ClientMovementBase, ClientMovementMode, ClientRoll, DEPRECATED_CHARACTER_MOVEMENT_RPC(), InAccel, InAccel0, NewFlags, PendingFlags, TimeStamp, UFUNCTION(), View, and View0.
DEPRECATED_CHARACTER_MOVEMENT_RPC() [16/22]
ACharacter::DEPRECATED_CHARACTER_MOVEMENT_RPC (ServerMoveDualHybridRootMotion_Implementation , ServerMovePacked_Implementation)
References ClientBaseBoneName, ClientLoc, ClientMovementBase, ClientMovementMode, ClientRoll, DEPRECATED_CHARACTER_MOVEMENT_RPC(), InAccel, InAccel0, NewFlags, PendingFlags, ServerMovePacked_Implementation(), TimeStamp, View, and View0.
DEPRECATED_CHARACTER_MOVEMENT_RPC() [17/22]
ACharacter::DEPRECATED_CHARACTER_MOVEMENT_RPC (ServerMoveDualNoBase , ServerMovePacked)
Replicated function sent by client to server - contains client movement and view info for two moves.
References DEPRECATED_CHARACTER_MOVEMENT_RPC(), and UFUNCTION().
DEPRECATED_CHARACTER_MOVEMENT_RPC() [18/22]
ACharacter::DEPRECATED_CHARACTER_MOVEMENT_RPC (ServerMoveDualNoBase_Implementation , ServerMovePacked_Implementation)
References ClientLoc, ClientMovementMode, ClientRoll, DEPRECATED_CHARACTER_MOVEMENT_RPC(), InAccel, InAccel0, NewFlags, PendingFlags, ServerMovePacked_Implementation(), TimeStamp, View, and View0.
DEPRECATED_CHARACTER_MOVEMENT_RPC() [19/22]
ACharacter::DEPRECATED_CHARACTER_MOVEMENT_RPC (ServerMoveNoBase , ServerMovePacked)
Replicated function sent by client to server.
Saves bandwidth over ServerMove() by implying that ClientMovementBase and ClientBaseBoneName are null. Passes through to CharacterMovement->ServerMove_Implementation() with null base params.
References DEPRECATED_CHARACTER_MOVEMENT_RPC(), and UFUNCTION().
DEPRECATED_CHARACTER_MOVEMENT_RPC() [20/22]
ACharacter::DEPRECATED_CHARACTER_MOVEMENT_RPC (ServerMoveNoBase_Implementation , ServerMovePacked_Implementation)
References ClientLoc, ClientMovementMode, ClientRoll, CompressedMoveFlags, DEPRECATED_CHARACTER_MOVEMENT_RPC(), InAccel, ServerMovePacked_Implementation(), TimeStamp, and View.
DEPRECATED_CHARACTER_MOVEMENT_RPC() [21/22]
ACharacter::DEPRECATED_CHARACTER_MOVEMENT_RPC (ServerMoveOld , ServerMovePacked)
References DEPRECATED_CHARACTER_MOVEMENT_RPC(), and UFUNCTION().
DEPRECATED_CHARACTER_MOVEMENT_RPC() [22/22]
ACharacter::DEPRECATED_CHARACTER_MOVEMENT_RPC (ServerMoveOld_Implementation , ServerMovePacked_Implementation)
References DEPRECATED_CHARACTER_MOVEMENT_RPC(), OldAccel, OldMoveFlags, and ServerMovePacked_Implementation().
DisplayDebug()
virtual void ACharacter::DisplayDebug (class UCanvas * Canvas, const FDebugDisplayInfo & DebugDisplay, float & YL, float & YPos) override virtual
Reimplemented from APawn.
Falling()
virtual void ACharacter::Falling () inline virtual
Called when the character's movement enters falling.
Definition at line 803 of file Character.h.
References Falling().
Referenced by Falling().
FillAsyncInput()
void ACharacter::FillAsyncInput (FCharacterAsyncInput & Input) const
Async simulation API.
References INavAgentInterface::const, FillAsyncInput(), and Input.
Referenced by FillAsyncInput().
FindComponentByClass() [1/2]
template<class T> T * ACharacter::FindComponentByClass () const inline
Definition at line 674 of file Character.h.
References FindComponentByClass().
FindComponentByClass() [2/2]
virtual UActorComponent * ACharacter::FindComponentByClass (const TSubclassOf< UActorComponent > ComponentClass) const override virtual
References INavAgentInterface::const, and FindComponentByClass().
Referenced by FindComponentByClass(), and FindComponentByClass().
FindRootMotionRepMove()
int32 ACharacter::FindRootMotionRepMove (const FAnimMontageInstance & ClientMontageInstance) const
Find usable root motion replicated move from our buffer.
Goes through the buffer back in time, to find the first move that clears 'CanUseRootMotionRepMove' below. Returns index of that move or INDEX_NONE otherwise.
References INavAgentInterface::const, and FindRootMotionRepMove().
Referenced by FindRootMotionRepMove().
GatherCurrentMovement()
virtual void ACharacter::GatherCurrentMovement () override virtual
References GatherCurrentMovement().
Referenced by GatherCurrentMovement().
GetBasedMovement()
FORCEINLINE const FBasedMovementInfo & ACharacter::GetBasedMovement () const inline
Accessor for BasedMovement.
Definition at line 502 of file Character.h.
References FORCEINLINE.
GetBaseRotationOffset()
virtual FQuat ACharacter::GetBaseRotationOffset () const inline virtual
Get the saved rotation offset of mesh.
This is how much extra rotation is applied from the capsule rotation.
Definition at line 518 of file Character.h.
Referenced by UFUNCTION().
GetCapsuleComponent()
FORCEINLINE class UCapsuleComponent * ACharacter::GetCapsuleComponent () const inline
Returns CapsuleComponent subobject.
Definition at line 407 of file Character.h.
References FORCEINLINE.
GetCharacterMovement() [1/2]
template<class T> FORCEINLINE_DEBUGGABLE T * ACharacter::GetCharacterMovement () const inline
Returns CharacterMovement subobject.
Definition at line 397 of file Character.h.
References CastChecked(), FORCEINLINE_DEBUGGABLE, and ECastCheckedType::NullAllowed.
GetCharacterMovement() [2/2]
FORCEINLINE UCharacterMovementComponent * ACharacter::GetCharacterMovement () const inline
Definition at line 401 of file Character.h.
References FORCEINLINE.
GetDefaultHalfHeight()
virtual float ACharacter::GetDefaultHalfHeight () const override virtual
Returns The half-height of the default Pawn, scaled by the component scale.
By default returns the half-height of the RootComponent, regardless of whether it is registered or collidable.
Reimplemented from APawn.
GetGravityDirection()
virtual FVector ACharacter::GetGravityDirection () const override virtual
Returns vector direction of gravity.
Reimplemented from APawn.
References FVector.
GetGravityTransform()
virtual FQuat ACharacter::GetGravityTransform () const override virtual
Returns a quaternion transforming from world space into gravity relative space.
Reimplemented from APawn.
GetJumpMaxHoldTime()
virtual float ACharacter::GetJumpMaxHoldTime () const virtual
Get the maximum jump time for the character.
Note that if StopJumping() is not called before the max jump hold time is reached, then the character will carry on receiving vertical velocity. Therefore it is usually best to call StopJumping() when jump input has ceased (such as a button up event).
Returns
Maximum jump time for the character
References INavAgentInterface::const, and GetJumpMaxHoldTime().
Referenced by GetJumpMaxHoldTime().
GetLifetimeReplicatedProps()
virtual GENERATED_BODY() public void ACharacter::GetLifetimeReplicatedProps (TArray< FLifetimeProperty > & OutLifetimeProps) const override private virtual
Default UObject constructor.
Reimplemented from APawn.
GetMesh()
FORCEINLINE class USkeletalMeshComponent * ACharacter::GetMesh () const inline
Returns Mesh subobject.
Definition at line 390 of file Character.h.
References FORCEINLINE, GetMesh(), and Mesh.
Referenced by GetMesh().
GetMovementBase()
virtual UPrimitiveComponent * ACharacter::GetMovementBase () const inline final override virtual
Return PrimitiveComponent we are based on (standing on, attached to, and moving on).
Reimplemented from APawn.
Definition at line 686 of file Character.h.
References INavAgentInterface::const.
GetMovementComponent()
virtual UPawnMovementComponent * ACharacter::GetMovementComponent () const override virtual
GetNavAgentLocation()
virtual FVector ACharacter::GetNavAgentLocation () const override virtual
References FVector.
GetProxyIsJumpForceApplied()
FORCEINLINE bool ACharacter::GetProxyIsJumpForceApplied () const inline
Indicates that this Character is currently under the force of a jump (if JumpMaxHoldTime is non-zero).
IsJumpProvidingForce() handles this as well. This function returns bProxyIsJumpForceApplied
Definition at line 733 of file Character.h.
References FORCEINLINE.
GetReplayLastTransformUpdateTimeStamp()
FORCEINLINE float ACharacter::GetReplayLastTransformUpdateTimeStamp () const inline
This is updated every frame to the latest timestamp, but only replicated to Replays, this is because we want to save positions to the replay replication connection each frame to ensure smooth movement.
This is the Accessor for ReplayLastTransformUpdateTimeStamp.
Definition at line 499 of file Character.h.
References FORCEINLINE.
GetReplicatedBasedMovement()
FORCEINLINE const FBasedMovementInfo & ACharacter::GetReplicatedBasedMovement () const inline
Accessor for ReplicatedBasedMovement.
Definition at line 505 of file Character.h.
References FORCEINLINE.
GetReplicatedBasedMovement_Mutable()
FBasedMovementInfo & ACharacter::GetReplicatedBasedMovement_Mutable () protected
This is the Replicated version of relative movement.
Do not modify on simulated proxies! Returns non-const ReplicatedBasedMovement.
References GetReplicatedBasedMovement_Mutable().
Referenced by GetReplicatedBasedMovement_Mutable().
GetReplicatedCustomConditionState()
virtual void ACharacter::GetReplicatedCustomConditionState (FCustomPropertyConditionState & OutActiveState) const override private virtual
GetReplicatedGravityDirection()
virtual FVector ACharacter::GetReplicatedGravityDirection () const virtual
Returns replicated gravity direction for simulated proxies.
References FVector.
GetReplicatedMovementMode()
FORCEINLINE uint8 ACharacter::GetReplicatedMovementMode () const inline
CharacterMovement MovementMode (and custom mode) replicated for simulated proxies.
Use CharacterMovementComponent::UnpackNetworkMovementMode() to translate it. Returns ReplicatedMovementMode
Definition at line 511 of file Character.h.
References FORCEINLINE.
GetReplicatedServerLastTransformUpdateTimeStamp()
FORCEINLINE float ACharacter::GetReplicatedServerLastTransformUpdateTimeStamp () const inline
This is the value of the CharacterMovement timestamp, and is replicated down to SimulatedProxies to assist with visual smoothing of the character.
May not be updated every frame to reduce bandwidth. This is the Accessor for ReplicatedServerLastTransformUpdateTimeStamp.
Definition at line 496 of file Character.h.
References FORCEINLINE, and GetReplicatedServerLastTransformUpdateTimeStamp().
Referenced by GetReplicatedServerLastTransformUpdateTimeStamp().
GetRepRootMotion()
FORCEINLINE const FRepRootMotionMontage & ACharacter::GetRepRootMotion () const inline
Replicated Root Motion montage.
Returns RepRootMotion
Definition at line 1040 of file Character.h.
References INavAgentInterface::const, FORCEINLINE, and GetRepRootMotion().
Referenced by GetRepRootMotion().
GetRepRootMotion_Mutable()
FRepRootMotionMontage & ACharacter::GetRepRootMotion_Mutable ()
Replicated Root Motion montage.
Returns non-const RepRootMotion
GetRootMotionAnimMontageInstance()
FAnimMontageInstance * ACharacter::GetRootMotionAnimMontageInstance () const
Get FAnimMontageInstance playing RootMotion.
References INavAgentInterface::const, and GetRootMotionAnimMontageInstance().
Referenced by GetRootMotionAnimMontageInstance().
GetSimpleCollisionCylinder()
virtual void ACharacter::GetSimpleCollisionCylinder (float & CollisionRadius, float & CollisionHalfHeight) const override virtual
References INavAgentInterface::const, and GetSimpleCollisionCylinder().
Referenced by GetSimpleCollisionCylinder().
InitializeAsyncOutput()
void ACharacter::InitializeAsyncOutput (FCharacterAsyncOutput & Output) const
References INavAgentInterface::const, and InitializeAsyncOutput().
Referenced by InitializeAsyncOutput().
IsCrouched()
bool ACharacter::IsCrouched () const
Set by character movement to specify that this Character is currently crouched.
This function returns bIsCrouched.
JumpIsAllowedInternal()
bool ACharacter::JumpIsAllowedInternal () const protected
References INavAgentInterface::const, and JumpIsAllowedInternal().
Referenced by JumpIsAllowedInternal().
Landed()
virtual void ACharacter::Landed (const FHitResult & Hit) virtual
Called upon landing when falling, to perform actions based on the Hit result.
Triggers the OnLanded event. Note that movement mode is still "Falling" during this event. Current Velocity value is the velocity at the time of landing. Consider OnMovementModeChanged() as well, as that can be used once the movement mode changes to the new mode (most likely Walking).
Parameters
Hit Result describing the landing that resulted in a valid landing spot.
See also
OnMovementModeChanged()
MoveBlockedBy()
virtual void ACharacter::MoveBlockedBy (const FHitResult & Impact) inline virtual
Called when pawn's movement is blocked.
Parameters
Impact describes the blocking hit.
Definition at line 862 of file Character.h.
References INavAgentInterface::const, and MoveBlockedBy().
Referenced by MoveBlockedBy().
NotifyActorBeginOverlap()
virtual void ACharacter::NotifyActorBeginOverlap (AActor * OtherActor) virtual
References NotifyActorBeginOverlap().
Referenced by NotifyActorBeginOverlap().
NotifyActorEndOverlap()
virtual void ACharacter::NotifyActorEndOverlap (AActor * OtherActor) virtual
References NotifyActorEndOverlap().
Referenced by NotifyActorEndOverlap().
NotifyJumpApex()
virtual void ACharacter::NotifyJumpApex () virtual
Called when character's jump reaches Apex.
Needs CharacterMovement->bNotifyApex = true
OnEndCrouch()
virtual void ACharacter::OnEndCrouch (float HalfHeightAdjust, float ScaledHalfHeightAdjust) virtual
Called when Character stops crouching.
Called on non-owned Characters through bIsCrouched replication.
Parameters
HalfHeightAdjust difference between default collision half-height, and actual crouched capsule half-height.
ScaledHalfHeightAdjust difference after component scale is taken in to account.
References OnEndCrouch(), and ScaledHalfHeightAdjust.
Referenced by OnEndCrouch().
OnJumped_Implementation()
virtual void ACharacter::OnJumped_Implementation () virtual
References OnJumped_Implementation().
Referenced by OnJumped_Implementation().
OnMovementModeChanged()
virtual void ACharacter::OnMovementModeChanged (EMovementMode PrevMovementMode, uint8 PreviousCustomMode = 0) virtual
Called from CharacterMovementComponent to notify the character that the movement mode has changed.
Parameters
PrevMovementMode Movement mode before the change
PrevCustomMode Custom mode before the change (applicable if PrevMovementMode is Custom)
References OnMovementModeChanged().
Referenced by OnMovementModeChanged().
OnRep_ReplicatedMovement()
virtual void ACharacter::OnRep_ReplicatedMovement () override virtual
References OnRep_ReplicatedMovement().
Referenced by OnRep_ReplicatedMovement().
OnStartCrouch()
virtual void ACharacter::OnStartCrouch (float HalfHeightAdjust, float ScaledHalfHeightAdjust) virtual
Called when Character crouches.
Called on non-owned Characters through bIsCrouched replication.
Parameters
HalfHeightAdjust difference between default collision half-height, and actual crouched capsule half-height.
ScaledHalfHeightAdjust difference after component scale is taken in to account.
References OnStartCrouch(), and ScaledHalfHeightAdjust.
Referenced by OnStartCrouch().
OnUpdateSimulatedPosition()
virtual void ACharacter::OnUpdateSimulatedPosition (const FVector & OldLocation, const FQuat & OldRotation) virtual
Called on client after position update is received to respond to the new location and rotation.
Actual change in location is expected to occur in CharacterMovement->SmoothCorrection(), after which this occurs. Default behavior is to check for penetration in a blocking object if bClientCheckEncroachmentOnNetUpdate is enabled, and set bSimGravityDisabled=true if so.
References INavAgentInterface::const, FVector, and OnUpdateSimulatedPosition().
Referenced by OnUpdateSimulatedPosition().
OnWalkingOffLedge_Implementation()
virtual void ACharacter::OnWalkingOffLedge_Implementation (const FVector & PreviousFloorImpactNormal, const FVector & PreviousFloorContactNormal, const FVector & PreviousLocation, float TimeDelta) virtual
References INavAgentInterface::const, FVector, OnWalkingOffLedge_Implementation(), PreviousFloorContactNormal, PreviousLocation, and TimeDelta.
Referenced by OnWalkingOffLedge_Implementation().
PawnClientRestart()
virtual void ACharacter::PawnClientRestart () override virtual
Called on the owning client of a player-controlled Pawn when it is restarted, this calls Restart()
Reimplemented from APawn.
PossessedBy()
virtual void ACharacter::PossessedBy (AController * NewController) override virtual
Called when this Pawn is possessed.
Only called on the server (or in standalone).
Parameters
NewController The controller possessing this pawn
Reimplemented from APawn.
References APawn::NewController.
PostInitializeComponents()
virtual void ACharacter::PostInitializeComponents () override virtual
Reimplemented from APawn.
PostLoad()
virtual void ACharacter::PostLoad () override virtual
Reimplemented from APawn.
Reimplemented in AEQSTestingPawn.
References PostLoad().
Referenced by PostLoad().
PostNetReceive()
virtual void ACharacter::PostNetReceive () override virtual
References PostNetReceive().
Referenced by PostNetReceive().
PostNetReceiveLocationAndRotation()
virtual void ACharacter::PostNetReceiveLocationAndRotation () override virtual
Reimplemented from APawn.
References PostNetReceiveLocationAndRotation().
Referenced by PostNetReceiveLocationAndRotation().
PreNetReceive()
virtual void ACharacter::PreNetReceive () override virtual
References PreNetReceive().
Referenced by PreNetReceive().
PreReplication()
virtual void ACharacter::PreReplication (IRepChangedPropertyTracker & ChangedPropertyTracker) override virtual
Called on the actor right before replication occurs.
Only called on Server, and for autonomous proxies if recording a Client Replay.
Reimplemented from APawn.
References PreReplication().
Referenced by PreReplication().
PreReplicationForReplay()
virtual void ACharacter::PreReplicationForReplay (IRepChangedPropertyTracker & ChangedPropertyTracker) override virtual
Called on the actor right before replication occurs.
Called for everyone when recording a Client Replay, including Simulated Proxies.
References PreReplicationForReplay().
Referenced by PreReplicationForReplay().
RecalculateBaseEyeHeight()
virtual void ACharacter::RecalculateBaseEyeHeight () override virtual
Set BaseEyeHeight based on current state.
Reimplemented from APawn.
RecalculateCrouchedEyeHeight()
void ACharacter::RecalculateCrouchedEyeHeight ()
Calculates the crouched eye height based on movement component settings.
References RecalculateCrouchedEyeHeight().
Referenced by RecalculateCrouchedEyeHeight().
ResetJumpState()
virtual void ACharacter::ResetJumpState () virtual
Marks character as not trying to jump.
References ResetJumpState().
Referenced by ResetJumpState().
Restart()
virtual void ACharacter::Restart () override virtual
Called when the Pawn is being restarted (usually by being possessed by a Controller).
This is called on the server for all pawns and the owning client for player pawns
Reimplemented from APawn.
RestoreReplicatedMove()
bool ACharacter::RestoreReplicatedMove (const FSimulatedRootMotionReplicatedMove & RootMotionRepMove)
Restore actor to an old buffered move.
References INavAgentInterface::const, and RestoreReplicatedMove().
Referenced by RestoreReplicatedMove().
RootMotionDebugClientPrintOnScreen_Implementation()
virtual void ACharacter::RootMotionDebugClientPrintOnScreen_Implementation (const FString & InString) virtual
References INavAgentInterface::const, and RootMotionDebugClientPrintOnScreen_Implementation().
Referenced by RootMotionDebugClientPrintOnScreen_Implementation().
SaveRelativeBasedMovement()
void ACharacter::SaveRelativeBasedMovement (const FVector & NewRelativeLocation, const FRotator & NewRotation, bool bRelativeRotation)
Save a new relative location in BasedMovement and a new rotation with is either relative or absolute.
References FVector.
ServerMove_Validate()
bool ACharacter::ServerMove_Validate (float TimeStamp, FVector_NetQuantize10 InAccel, FVector_NetQuantize100 ClientLoc, uint8 CompressedMoveFlags, uint8 ClientRoll, uint32 View, UPrimitiveComponent * ClientMovementBase, FName ClientBaseBoneName, uint8 ClientMovementMode)
References ClientBaseBoneName, ClientLoc, ClientMovementBase, ClientMovementMode, ClientRoll, CompressedMoveFlags, InAccel, ServerMove_Validate(), TimeStamp, and View.
Referenced by ServerMove_Validate().
ServerMoveDual_Validate()
bool ACharacter::ServerMoveDual_Validate (float TimeStamp0, FVector_NetQuantize10 InAccel0, uint8 PendingFlags, uint32 View0, float TimeStamp, FVector_NetQuantize10 InAccel, FVector_NetQuantize100 ClientLoc, uint8 NewFlags, uint8 ClientRoll, uint32 View, UPrimitiveComponent * ClientMovementBase, FName ClientBaseBoneName, uint8 ClientMovementMode)
References ClientBaseBoneName, ClientLoc, ClientMovementBase, ClientMovementMode, ClientRoll, InAccel, InAccel0, NewFlags, PendingFlags, ServerMoveDual_Validate(), TimeStamp, View, and View0.
Referenced by ServerMoveDual_Validate().
ServerMoveDualHybridRootMotion_Validate()
bool ACharacter::ServerMoveDualHybridRootMotion_Validate (float TimeStamp0, FVector_NetQuantize10 InAccel0, uint8 PendingFlags, uint32 View0, float TimeStamp, FVector_NetQuantize10 InAccel, FVector_NetQuantize100 ClientLoc, uint8 NewFlags, uint8 ClientRoll, uint32 View, UPrimitiveComponent * ClientMovementBase, FName ClientBaseBoneName, uint8 ClientMovementMode)
References ClientBaseBoneName, ClientLoc, ClientMovementBase, ClientMovementMode, ClientRoll, InAccel, InAccel0, NewFlags, PendingFlags, ServerMoveDualHybridRootMotion_Validate(), TimeStamp, View, and View0.
Referenced by ServerMoveDualHybridRootMotion_Validate().
ServerMoveDualNoBase_Validate()
bool ACharacter::ServerMoveDualNoBase_Validate (float TimeStamp0, FVector_NetQuantize10 InAccel0, uint8 PendingFlags, uint32 View0, float TimeStamp, FVector_NetQuantize10 InAccel, FVector_NetQuantize100 ClientLoc, uint8 NewFlags, uint8 ClientRoll, uint32 View, uint8 ClientMovementMode)
References ClientLoc, ClientMovementMode, ClientRoll, InAccel, InAccel0, NewFlags, PendingFlags, ServerMoveDualNoBase_Validate(), TimeStamp, View, and View0.
Referenced by ServerMoveDualNoBase_Validate().
ServerMoveNoBase_Validate()
bool ACharacter::ServerMoveNoBase_Validate (float TimeStamp, FVector_NetQuantize10 InAccel, FVector_NetQuantize100 ClientLoc, uint8 CompressedMoveFlags, uint8 ClientRoll, uint32 View, uint8 ClientMovementMode)
References ClientLoc, ClientMovementMode, ClientRoll, CompressedMoveFlags, InAccel, ServerMoveNoBase_Validate(), TimeStamp, and View.
Referenced by ServerMoveNoBase_Validate().
ServerMoveOld_Validate()
bool ACharacter::ServerMoveOld_Validate (float OldTimeStamp, FVector_NetQuantize10 OldAccel, uint8 OldMoveFlags)
References OldAccel, OldMoveFlags, and ServerMoveOld_Validate().
Referenced by ServerMoveOld_Validate().
ServerMovePacked_Implementation()
void ACharacter::ServerMovePacked_Implementation (const FCharacterServerMovePackedBits & PackedBits)
Referenced by DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), and DEPRECATED_CHARACTER_MOVEMENT_RPC().
ServerMovePacked_Validate()
bool ACharacter::ServerMovePacked_Validate (const FCharacterServerMovePackedBits & PackedBits)
SetAnimRootMotionTranslationScale()
void ACharacter::SetAnimRootMotionTranslationScale (float InAnimRootMotionTranslationScale = 1.f)
Sets scale to apply to root motion translation on this Character.
References SetAnimRootMotionTranslationScale().
Referenced by SetAnimRootMotionTranslationScale().
SetBase()
virtual void ACharacter::SetBase (UPrimitiveComponent * NewBase, const FName BoneName = NAME_None, bool bNotifyActor = true) virtual
Sets the component the Character is walking on, used by CharacterMovement walking movement to be able to follow dynamic objects.
References NewBase.
SetIsCrouched()
void ACharacter::SetIsCrouched (const bool bInIsCrouched)
Specifies whether this Character is currently crouched or not.
This function sets bIsCrouched and marks property as dirty.
SetProxyIsJumpForceApplied()
void ACharacter::SetProxyIsJumpForceApplied (const bool bInProxyIsJumpForceApplied)
Set to indicate that this Character is currently under the force of a jump (if JumpMaxHoldTime is non-zero).
IsJumpProvidingForce() handles this as well. This function sets bProxyIsJumpForceApplied
SetReplayLastTransformUpdateTimeStamp()
void ACharacter::SetReplayLastTransformUpdateTimeStamp (const float InReplayLastTransformUpdateTimeStamp) protected
This is updated every frame to the latest timestamp, but only replicated to Replays, this is because we want to save positions to the replay replication connection each frame to ensure smooth movement.
Sets ReplayLastTransformUpdateTimeStamp.
References INavAgentInterface::const, and SetReplayLastTransformUpdateTimeStamp().
Referenced by SetReplayLastTransformUpdateTimeStamp().
SetReplicatedBasedMovement()
void ACharacter::SetReplicatedBasedMovement (const FBasedMovementInfo & InReplicatedBasedMovement) protected
This is the Replicated version of relative movement.
Do not modify on simulated proxies! Sets ReplicatedBasedMovement
References INavAgentInterface::const, and SetReplicatedBasedMovement().
Referenced by SetReplicatedBasedMovement().
SetReplicatedGravityDirection()
void ACharacter::SetReplicatedGravityDirection (const FVector & InReplicatedGravityDirection) protected
CharacterMovement Custom gravity direction replicated for simulated proxies.
This function sets ReplicatedGravityDirection and also marks property as dirty.
References INavAgentInterface::const, FVector, and SetReplicatedGravityDirection().
Referenced by SetReplicatedGravityDirection().
SetReplicatedMovementMode()
void ACharacter::SetReplicatedMovementMode (const uint8 InReplicatedMovementMode) protected
Sets CharacterMovement MovementMode (and custom mode) replicated for simulated proxies.
Use CharacterMovementComponent::UnpackNetworkMovementMode() to translate it. This function sets the compressed value of ReplicatedMovementMode.
References INavAgentInterface::const, and SetReplicatedMovementMode().
Referenced by SetReplicatedMovementMode().
SetReplicatedServerLastTransformUpdateTimeStamp()
void ACharacter::SetReplicatedServerLastTransformUpdateTimeStamp (const float InReplicatedServerLastTransformUpdateTimeStamp) protected
This is the value of the CharacterMovement timestamp, and is replicated down to SimulatedProxies to assist with visual smoothing of the character.
May not be updated every frame to reduce bandwidth. This function sets ReplicatedServerLastTransformUpdateTimeStamp.
References INavAgentInterface::const, and SetReplicatedServerLastTransformUpdateTimeStamp().
Referenced by SetReplicatedServerLastTransformUpdateTimeStamp().
SetReplicateMovement()
virtual void ACharacter::SetReplicateMovement (bool bInReplicateMovement) override virtual
Set whether this actor's movement replicates to network clients.
References SetReplicateMovement().
Referenced by SetReplicateMovement().
SetRepRootMotion()
void ACharacter::SetRepRootMotion (const FRepRootMotionMontage & InRepRootMotion)
Replicated Root Motion montage.
Sets RepRootMotion
SetupPlayerInputComponent()
virtual void ACharacter::SetupPlayerInputComponent (class UInputComponent * PlayerInputComponent) override virtual
Allows a Pawn to set up custom input bindings.
Called upon possession by a PlayerController, using the InputComponent created by CreatePlayerInputComponent().
Reimplemented from APawn.
ShouldNotifyLanded()
virtual bool ACharacter::ShouldNotifyLanded (const struct FHitResult & Hit) virtual
Returns true if the Landed() event should be called.
Used by CharacterMovement to prevent notifications while playing back network moves.
References INavAgentInterface::const, and ShouldNotifyLanded().
Referenced by ShouldNotifyLanded().
ShouldReplicateAcceleration()
virtual bool ACharacter::ShouldReplicateAcceleration () const inline protected virtual
Whether this Character should include acceleration data in its replicated movement.
Definition at line 452 of file Character.h.
References CharacterCVars::EnableCharacterAccelerationReplication, and ShouldReplicateAcceleration().
Referenced by ShouldReplicateAcceleration().
SimulatedRootMotionPositionFixup()
void ACharacter::SimulatedRootMotionPositionFixup (float DeltaSeconds)
Position fix up for Simulated Proxies playing Root Motion.
References SimulatedRootMotionPositionFixup().
Referenced by SimulatedRootMotionPositionFixup().
TornOff()
virtual void ACharacter::TornOff () override virtual
References TornOff().
Referenced by TornOff().
TurnOff()
virtual void ACharacter::TurnOff () override virtual
Freeze pawn - stop sounds, animations, physics, weapon firing.
Reimplemented from APawn.
UFUNCTION() [1/37]
ACharacter::UFUNCTION () const
Check if the character can jump in the current state.
The default implementation may be overridden or extended by implementing the custom CanJump event in Blueprints.
@Return Whether the character can jump in the current state.
References APawn::Category, and Character.
UFUNCTION() [2/37]
ACharacter::UFUNCTION () const
True if we are playing root motion from any source right now (anim root motion, root motion source)
References Animation, APawn::Category, INavAgentInterface::const, and UFUNCTION().
UFUNCTION() [3/37]
ACharacter::UFUNCTION () const
True if we are playing Root Motion right now, through a Montage with RootMotionMode == ERootMotionMode::RootMotionFromMontagesOnly.
This means code path for networked root motion is enabled.
References Animation, APawn::Category, INavAgentInterface::const, and UFUNCTION().
UFUNCTION() [4/37]
ACharacter::UFUNCTION () const
Return current playing Montage.
References Animation, APawn::Category, INavAgentInterface::const, and UFUNCTION().
UFUNCTION() [5/37]
ACharacter::UFUNCTION () const
Scale to apply to root motion translation on this Character.
Returns current value of AnimRootMotionScale.
References Animation, APawn::Category, INavAgentInterface::const, and UFUNCTION().
UFUNCTION() [6/37]
ACharacter::UFUNCTION () const
Returns
true if this character is currently able to crouch (and is not currently crouched)
References APawn::Category, Character, INavAgentInterface::const, and UFUNCTION().
UFUNCTION() [7/37]
ACharacter::UFUNCTION () const
True if jump is actively providing a force, such as when the jump key is held and the time it has been held is less than JumpMaxHoldTime.
See also
CharacterMovement->IsFalling
References APawn::Category, Character, INavAgentInterface::const, and UFUNCTION().
UFUNCTION() [8/37]
ACharacter::UFUNCTION ()
Play Animation Montage on the character mesh.
Returns the length of the animation montage in seconds, or 0.f if failed to play.
References Animation, APawn::Category, and UFUNCTION().
UFUNCTION() [9/37]
ACharacter::UFUNCTION ()
Cache mesh offset from capsule.
This is used as the target for network smoothing interpolation, when the mesh is offset with lagged smoothing. This is automatically called during initialization; call this at runtime if you intend to change the default mesh offset from the capsule.
See also
GetBaseTranslationOffset(), GetBaseRotationOffset()
References APawn::Category, and Character.
UFUNCTION() [10/37]
ACharacter::UFUNCTION ()
Make the character jump on the next update.
If you want your character to jump according to the time that the jump key is held, then you can set JumpMaxHoldTime to some non-zero value. Make sure in this case to call StopJumping() when you want the jump's z-velocity to stop being applied (such as on a button up event), otherwise the character will carry on receiving the velocity until JumpKeyHoldTime reaches JumpMaxHoldTime.
References APawn::Category, and Character.
UFUNCTION() [11/37]
ACharacter::UFUNCTION ()
Set a pending launch velocity on the Character.
This velocity will be processed on the next CharacterMovementComponent tick, and will set it to the "falling" state. Triggers the OnLaunched event. @PARAM LaunchVelocity is the velocity to impart to the Character @PARAM bXYOverride if true replace the XY part of the Character's velocity instead of adding to it. @PARAM bZOverride if true replace the Z component of the Character's velocity instead of adding to it.
References APawn::Category, Character, and UFUNCTION().
UFUNCTION() [12/37]
UPROPERTY() uint8 bIsCrouched UPROPERTY() uint8 bProxyIsJumpForceApplied ACharacter::UFUNCTION ()
Flag that we are receiving replication of the based movement.
Set by character movement to specify that this Character is currently crouched. Set to indicate that this Character is currently under the force of a jump (if JumpMaxHoldTime is non-zero). IsJumpProvidingForce() handles this as well. Handle Crouching replicated from server
References APawn::Category, Character, Transient, UFUNCTION(), and UPROPERTY().
UFUNCTION() [13/37]
ACharacter::UFUNCTION ()
Rep notify for ReplicatedBasedMovement.
References UFUNCTION().
UFUNCTION() [14/37]
ACharacter::UFUNCTION ()
Stop Animation Montage.
If nullptr, it will stop what's currently active. The Blend Out Time is taken from the montage asset that is being stopped.
References Animation, APawn::Category, and UFUNCTION().
UFUNCTION() [15/37]
ACharacter::UFUNCTION ()
Stop the character from jumping on the next update.
Call this from an input event (such as a button 'up' event) to cease applying jump Z-velocity. If this is not called, then jump z-velocity will be applied until JumpMaxHoldTime is reached.
References APawn::Category, and Character.
UFUNCTION() [16/37]
ACharacter::UFUNCTION ()
References Client, and UFUNCTION().
UFUNCTION() [17/37]
ACharacter::UFUNCTION ()
References Client, and UFUNCTION().
UFUNCTION() [18/37]
ACharacter::UFUNCTION ()
References Client, and UFUNCTION().
UFUNCTION() [19/37]
ACharacter::UFUNCTION () const &
UFUNCTION() [20/37]
ACharacter::UFUNCTION ()
Event fired when the character has just started jumping.
References APawn::Category, Character, and UFUNCTION().
UFUNCTION() [21/37]
ACharacter::UFUNCTION () const &
Called upon landing when falling, to perform actions based on the Hit result.
Note that movement mode is still "Falling" during this event. Current Velocity value is the velocity at the time of landing. Consider OnMovementModeChanged() as well, as that can be used once the movement mode changes to the new mode (most likely Walking).
Parameters
Hit Result describing the landing that resulted in a valid landing spot.
See also
OnMovementModeChanged()
UFUNCTION() [22/37]
ACharacter::UFUNCTION ()
Let blueprint know that we were launched.
References bXYOverride, bZOverride, FVector, and UFUNCTION().
UFUNCTION() [23/37]
ACharacter::UFUNCTION ()
References UFUNCTION().
UFUNCTION() [24/37]
ACharacter::UFUNCTION ()
Handles replicated root motion properties on simulated proxies and position correction.
UFUNCTION() [25/37]
ACharacter::UFUNCTION () const &
Event fired when the Character is walking off a surface and is about to fall because CharacterMovement->CurrentFloor became unwalkable.
If CharacterMovement->MovementMode does not change during this event then the character will automatically start falling afterwards.
Note
Z velocity is zero during walking movement, and will be here as well. Another velocity can be computed here if desired and will be used when starting to fall.
Parameters
PreviousFloorImpactNormal Normal of the previous walkable floor.
PreviousFloorContactNormal Normal of the contact with the previous walkable floor.
PreviousLocation Previous character location before movement off the ledge.
TimeTick Time delta of movement update resulting in moving off the ledge.
References APawn::Category, and Character.
UFUNCTION() [26/37]
ACharacter::UFUNCTION () const &
References Client, INavAgentInterface::const, and UFUNCTION().
UFUNCTION() [27/37]
ACharacter::UFUNCTION () const &
Referenced by DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
UFUNCTION() [28/37]
ACharacter::UFUNCTION () const inline
Get the saved translation offset of mesh.
This is how much extra offset is applied from the center of the capsule.
Definition at line 514 of file Character.h.
References APawn::Category, Character, and FVector.
UFUNCTION() [29/37]
ACharacter::UFUNCTION () const protected
Customizable event to check if the character can jump in the current state.
Default implementation returns true if the character is on the ground and not crouching, has a valid CharacterMovementComponent and CanEverJump() returns true. Default implementation also allows for 'hold to jump higher' functionality: As well as returning true when on the ground, it also returns true when GetMaxJumpTime is more than zero and IsJumping returns true.
@Return Whether the character can jump in the current state.
References APawn::Category, Character, INavAgentInterface::const, and meta.
UFUNCTION() [30/37]
ACharacter::UFUNCTION () const
True if we are playing Anim root motion right now.
References Animation, APawn::Category, INavAgentInterface::const, meta, and UFUNCTION().
UFUNCTION() [31/37]
ACharacter::UFUNCTION ()
Request the character to start crouching.
The request is processed on the next update of the CharacterMovementComponent.
See also
OnStartCrouch
IsCrouched
CharacterMovement->WantsToCrouch
References APawn::Category, Character, and meta.
UFUNCTION() [32/37]
ACharacter::UFUNCTION ()
Request the character to stop crouching.
The request is processed on the next update of the CharacterMovementComponent.
See also
OnEndCrouch
IsCrouched
CharacterMovement->WantsToCrouch
References APawn::Category, Character, meta, and UFUNCTION().
UFUNCTION() [33/37]
ACharacter::UFUNCTION ()
Event when Character stops crouching.
Parameters
HalfHeightAdjust difference between default collision half-height, and actual crouched capsule half-height.
ScaledHalfHeightAdjust difference after component scale is taken in to account.
References meta, and UFUNCTION().
UFUNCTION() [34/37]
ACharacter::UFUNCTION ()
Called from CharacterMovementComponent to notify the character that the movement mode has changed.
Parameters
PrevMovementMode Movement mode before the change
NewMovementMode New movement mode
PrevCustomMode Custom mode before the change (applicable if PrevMovementMode is Custom)
NewCustomMode New custom mode (applicable if NewMovementMode is Custom)
References meta, and UFUNCTION().
UFUNCTION() [35/37]
ACharacter::UFUNCTION ()
Event when Character crouches.
Parameters
HalfHeightAdjust difference between default collision half-height, and actual crouched capsule half-height.
ScaledHalfHeightAdjust difference after component scale is taken in to account.
References meta, ScaledHalfHeightAdjust, and UFUNCTION().
UFUNCTION() [36/37]
ACharacter::UFUNCTION ()
Event for implementing custom character movement mode.
Called by CharacterMovement if MovementMode is set to Custom.
Note
C++ code should override UCharacterMovementComponent::PhysCustom() instead.
See also
UCharacterMovementComponent::PhysCustom()
References DeltaTime, meta, and UFUNCTION().
UFUNCTION() [37/37]
ACharacter::UFUNCTION () const inline
Get the saved rotation offset of mesh.
This is how much extra rotation is applied from the capsule rotation.
Definition at line 521 of file Character.h.
References APawn::Category, Character, GetBaseRotationOffset(), and meta.
UnPossessed()
virtual void ACharacter::UnPossessed () override virtual
Called when our Controller no longer possesses us.
Only called on the server (or in standalone).
Reimplemented from APawn.
UpdateNavigationRelevance()
virtual void ACharacter::UpdateNavigationRelevance () override virtual
Update all components relevant for navigation generators to match bCanAffectNavigationGeneration flag.
Reimplemented from APawn.
UPROPERTY() [1/28]
ACharacter::UPROPERTY ()
Event triggered at the end of a CharacterMovementComponent movement update.
This is the preferred event to use rather than the Tick event when performing custom updates to CharacterMovement properties based on the current state. This is mainly due to the nature of network updates, where client corrections in position from the server can cause multiple iterations of a movement update, which allows this event to update as well, while a Tick event would not.
Parameters
DeltaSeconds Delta time in seconds for this update
InitialLocation Location at the start of the update. May be different than the current location if movement occurred.
InitialVelocity Velocity at the start of the update. May be different than the current velocity.
References APawn::Category, Character, and UPROPERTY().
UPROPERTY() [2/28]
ACharacter::UPROPERTY ()
Broadcast when Character's jump reaches its apex.
Needs CharacterMovement->bNotifyApex = true
References APawn::Category, and Character.
UPROPERTY() [3/28]
ACharacter::UPROPERTY ()
Called upon landing when falling, to perform actions based on the Hit result.
Note that movement mode is still "Falling" during this event. Current Velocity value is the velocity at the time of landing. Consider OnMovementModeChanged() as well, as that can be used once the movement mode changes to the new mode (most likely Walking).
Parameters
Hit Result describing the landing that resulted in a valid landing spot.
See also
OnMovementModeChanged()
References APawn::Category, and Character.
UPROPERTY() [4/28]
ACharacter::UPROPERTY () protected
Scale to apply to root motion translation on this Character.
References UPROPERTY().
UPROPERTY() [5/28]
ACharacter::UPROPERTY ()
Default crouched eye height.
References Camera, APawn::Category, Character, Transient, and UPROPERTY().
UPROPERTY() [6/28]
ACharacter::UPROPERTY ()
Amount of jump force time remaining, if JumpMaxHoldTime > 0.
References APawn::Category, Character, Transient, and UPROPERTY().
UPROPERTY() [7/28]
ACharacter::UPROPERTY ()
Jump key Held Time.
This is the time that the player has held the jump key, in seconds.
References APawn::Category, Character, Transient, and UPROPERTY().
UPROPERTY() [8/28]
ACharacter::UPROPERTY ()
Track last time a jump force started for a proxy.
References APawn::Category, Character, Transient, and UPROPERTY().
UPROPERTY() [9/28]
ACharacter::UPROPERTY () protected
UPROPERTY() [10/28]
ACharacter::UPROPERTY () protected
CharacterMovement ServerLastTransformUpdateTimeStamp value, replicated to simulated proxies.
UPROPERTY() [11/28]
ACharacter::UPROPERTY ()
Multicast delegate for MovementMode changing.
References APawn::Category, Character, and UPROPERTY().
UPROPERTY() [12/28]
ACharacter::UPROPERTY () protected
Saved rotation offset of mesh.
UPROPERTY() [13/28]
ACharacter::UPROPERTY ()
For LocallyControlled Autonomous clients.
Saved root motion data to be used by SavedMoves.
References Transient, and UPROPERTY().
UPROPERTY() [14/28]
ACharacter::UPROPERTY ()
For LocallyControlled Autonomous clients.
During a PerformMovement() after root motion is prepared, we save it off into this and then record it into our SavedMoves. During SavedMove playback we use it as our "Previous Move" SavedRootMotion which includes last received root motion from the Server
References Transient, and UPROPERTY().
UPROPERTY() [15/28]
ACharacter::UPROPERTY () protected
Saved translation offset of mesh.
References FVector, and UPROPERTY().
UPROPERTY() [16/28]
ACharacter::UPROPERTY () protected
CharacterMovement Custom gravity direction replicated for simulated proxies.
References UPROPERTY().
UPROPERTY() [17/28]
ACharacter::UPROPERTY ()
Tracks the current number of jumps performed.
This is incremented in CheckJumpInput, used in CanJump_Implementation, and reset in OnMovementModeChanged. When providing overrides for these methods, it's recommended to either manually increment / reset this value, or call the Super:: method.
References APawn::Category, Character, and UPROPERTY().
UPROPERTY() [18/28]
ACharacter::UPROPERTY ()
Represents the current number of jumps performed before CheckJumpInput modifies JumpCurrentCount.
This is set in CheckJumpInput and is used in SetMoveFor and PrepMoveFor instead of JumpCurrentCount since CheckJumpInput can modify JumpCurrentCount. When providing overrides for these methods, it's recommended to either manually set this value, or call the Super:: method.
References APawn::Category, Character, and UPROPERTY().
UPROPERTY() [19/28]
ACharacter::UPROPERTY ()
The max number of jumps the character can perform.
Note that if JumpMaxHoldTime is non zero and StopJumping is not called, the player may be able to perform and unlimited number of jumps. Therefore it is usually best to call StopJumping() when jump input has ceased (such as a button up event).
References APawn::Category, Character, and UPROPERTY().
UPROPERTY() [20/28]
ACharacter::UPROPERTY () protected
Info about our current movement base (object we are standing on).
References UPROPERTY().
UPROPERTY() [21/28]
ACharacter::UPROPERTY () protected
Replicated version of relative movement.
Read-only on simulated proxies!
References UPROPERTY().
UPROPERTY() [22/28]
ACharacter::UPROPERTY ()
Replicated Root Motion montage.
References UPROPERTY().
UPROPERTY() [23/28]
ACharacter::UPROPERTY ()
Array of previously received root motion moves from the server.
References Transient, and UPROPERTY().
UPROPERTY() [24/28]
ACharacter::UPROPERTY () protected
When true, player wants to jump.
When true, applying updates to network client (replaying saved moves for a locally controlled character) True if Pawn was initially falling when started to replay network moves. If server disagrees with root motion track position, client has to resimulate root motion from last AckedMove. If server disagrees with root motion state, client has to resimulate root motion from last AckedMove. Disable simulated gravity (set when character encroaches geometry on client, to keep it from falling through floors) Disable root motion on the server. When receiving a DualServerMove, where the first move is not root motion and the second is. Tracks whether or not the character was already jumping last frame. CharacterMovement MovementMode (and custom mode) replicated for simulated proxies. Use CharacterMovementComponent::UnpackNetworkMovementMode() to translate it.
References UPROPERTY().
UPROPERTY() [25/28]
ACharacter::UPROPERTY ()
The max time the jump key can be held.
Note that if StopJumping() is not called before the max jump hold time is reached, then the character will carry on receiving vertical velocity. Therefore it is usually best to call StopJumping() when jump input has ceased (such as a button up event).
References APawn::Category, Character, Meta, and UPROPERTY().
UPROPERTY() [26/28]
ACharacter::UPROPERTY () private
The CapsuleComponent being used for movement collision (by CharacterMovement).
Always treated as being vertically aligned in simple collision check functions.
References APawn::Category, Character, meta, and UPROPERTY().
UPROPERTY() [27/28]
ACharacter::UPROPERTY () private
Movement component used for movement logic in various movement modes (walking, falling, etc), containing relevant settings and functions to control movement.
References APawn::Category, Character, meta, and UPROPERTY().
UPROPERTY() [28/28]
ACharacter::UPROPERTY () private
The main skeletal mesh associated with this Character (optional sub-object).
References APawn::Category, Character, Mesh, and meta.
Referenced by UFUNCTION(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), and UPROPERTY().
Field Documentation
bBaseRelativePosition [1/4]
FRootMotionSourceGroup bool float FVector FVector_NetQuantizeNormal float UPrimitiveComponent FName bool bool ACharacter::bBaseRelativePosition
Definition at line 359 of file Character.h.
Referenced by DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), and DEPRECATED_CHARACTER_MOVEMENT_RPC().
bBaseRelativePosition [2/4]
FVector UPrimitiveComponent FName bool bool ACharacter::bBaseRelativePosition
Definition at line 366 of file Character.h.
bBaseRelativePosition [3/4]
float FVector FVector_NetQuantizeNormal float UPrimitiveComponent FName bool bool ACharacter::bBaseRelativePosition
Definition at line 373 of file Character.h.
bBaseRelativePosition [4/4]
FRootMotionSourceGroup bool float FVector FVector_NetQuantizeNormal float UPrimitiveComponent FName bool bool ACharacter::bBaseRelativePosition
Definition at line 380 of file Character.h.
bHasAnimRootMotion
FRootMotionSourceGroup bool ACharacter::bHasAnimRootMotion
Definition at line 380 of file Character.h.
Referenced by DEPRECATED_CHARACTER_MOVEMENT_RPC().
bHasBase [1/4]
FRootMotionSourceGroup bool float FVector FVector_NetQuantizeNormal float UPrimitiveComponent FName bool ACharacter::bHasBase
Definition at line 359 of file Character.h.
Referenced by DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), and DEPRECATED_CHARACTER_MOVEMENT_RPC().
bHasBase [2/4]
FVector UPrimitiveComponent FName bool ACharacter::bHasBase
Definition at line 366 of file Character.h.
bHasBase [3/4]
float FVector FVector_NetQuantizeNormal float UPrimitiveComponent FName bool ACharacter::bHasBase
Definition at line 373 of file Character.h.
bHasBase [4/4]
FRootMotionSourceGroup bool float FVector FVector_NetQuantizeNormal float UPrimitiveComponent FName bool ACharacter::bHasBase
Definition at line 380 of file Character.h.
bXYOverride
bool ACharacter::bXYOverride
Definition at line 791 of file Character.h.
Referenced by UFUNCTION().
bZOverride
bool bool ACharacter::bZOverride
Definition at line 791 of file Character.h.
Referenced by UFUNCTION().
CapsuleComponentName
FName ACharacter::CapsuleComponentName static
Name of the CapsuleComponent.
Definition at line 410 of file Character.h.
CharacterMovementComponentName
FName ACharacter::CharacterMovementComponentName static
Name of the CharacterMovement component.
Use this name if you want to use a different class (with ObjectInitializer.SetDefaultSubobjectClass).
Definition at line 404 of file Character.h.
ClientBaseBoneName [1/2]
FVector_NetQuantize10 uint8 uint32 float FVector_NetQuantize10 FVector_NetQuantize100 uint8 uint8 uint32 UPrimitiveComponent FName ACharacter::ClientBaseBoneName
Definition at line 301 of file Character.h.
Referenced by DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), ServerMove_Validate(), ServerMoveDual_Validate(), and ServerMoveDualHybridRootMotion_Validate().
ClientBaseBoneName [2/2]
FVector_NetQuantize10 uint8 uint32 float FVector_NetQuantize10 FVector_NetQuantize100 uint8 uint8 uint32 UPrimitiveComponent FName ACharacter::ClientBaseBoneName
Definition at line 320 of file Character.h.
ClientLoc [1/2]
FVector_NetQuantize10 uint8 uint32 float FVector_NetQuantize10 FVector_NetQuantize100 ACharacter::ClientLoc
Definition at line 301 of file Character.h.
Referenced by DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), ServerMove_Validate(), ServerMoveDual_Validate(), ServerMoveDualHybridRootMotion_Validate(), ServerMoveDualNoBase_Validate(), and ServerMoveNoBase_Validate().
ClientLoc [2/2]
FVector_NetQuantize10 uint8 uint32 float FVector_NetQuantize10 FVector_NetQuantize100 ACharacter::ClientLoc
Definition at line 320 of file Character.h.
ClientMovementBase [1/2]
FVector_NetQuantize10 uint8 uint32 float FVector_NetQuantize10 FVector_NetQuantize100 uint8 uint8 uint32 UPrimitiveComponent * ACharacter::ClientMovementBase
Definition at line 301 of file Character.h.
Referenced by DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), ServerMove_Validate(), ServerMoveDual_Validate(), and ServerMoveDualHybridRootMotion_Validate().
ClientMovementBase [2/2]
FVector_NetQuantize10 uint8 uint32 float FVector_NetQuantize10 FVector_NetQuantize100 uint8 uint8 uint32 UPrimitiveComponent* ACharacter::ClientMovementBase
Definition at line 320 of file Character.h.
ClientMovementMode [1/4]
FVector_NetQuantize10 uint8 uint32 float FVector_NetQuantize10 FVector_NetQuantize100 uint8 uint8 uint32 UPrimitiveComponent FName uint8 ACharacter::ClientMovementMode
Definition at line 301 of file Character.h.
Referenced by DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), ServerMove_Validate(), ServerMoveDual_Validate(), ServerMoveDualHybridRootMotion_Validate(), ServerMoveDualNoBase_Validate(), and ServerMoveNoBase_Validate().
ClientMovementMode [2/4]
FVector_NetQuantize10 FVector_NetQuantize100 uint8 uint8 uint32 uint8 ACharacter::ClientMovementMode
Definition at line 312 of file Character.h.
ClientMovementMode [3/4]
FVector_NetQuantize10 uint8 uint32 float FVector_NetQuantize10 FVector_NetQuantize100 uint8 uint8 uint32 UPrimitiveComponent FName uint8 ACharacter::ClientMovementMode
Definition at line 320 of file Character.h.
ClientMovementMode [4/4]
FVector_NetQuantize10 uint8 uint32 float FVector_NetQuantize10 FVector_NetQuantize100 uint8 uint8 uint32 uint8 ACharacter::ClientMovementMode
Definition at line 328 of file Character.h.
ClientRoll [1/2]
FVector_NetQuantize10 uint8 uint32 float FVector_NetQuantize10 FVector_NetQuantize100 uint8 uint8 ACharacter::ClientRoll
Definition at line 301 of file Character.h.
Referenced by DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), ServerMove_Validate(), ServerMoveDual_Validate(), ServerMoveDualHybridRootMotion_Validate(), ServerMoveDualNoBase_Validate(), and ServerMoveNoBase_Validate().
ClientRoll [2/2]
FVector_NetQuantize10 uint8 uint32 float FVector_NetQuantize10 FVector_NetQuantize100 uint8 uint8 ACharacter::ClientRoll
Definition at line 320 of file Character.h.
CompressedMoveFlags
FVector_NetQuantize10 FVector_NetQuantize100 uint8 ACharacter::CompressedMoveFlags
Definition at line 301 of file Character.h.
Referenced by DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), ServerMove_Validate(), and ServerMoveNoBase_Validate().
InAccel [1/2]
FVector_NetQuantize10 uint8 uint32 float FVector_NetQuantize10 ACharacter::InAccel
Definition at line 301 of file Character.h.
Referenced by DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), ServerMove_Validate(), ServerMoveDual_Validate(), ServerMoveDualHybridRootMotion_Validate(), ServerMoveDualNoBase_Validate(), and ServerMoveNoBase_Validate().
InAccel [2/2]
FVector_NetQuantize10 uint8 uint32 float FVector_NetQuantize10 ACharacter::InAccel
Definition at line 320 of file Character.h.
InAccel0
FVector_NetQuantize10 ACharacter::InAccel0
Definition at line 320 of file Character.h.
Referenced by DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), ServerMoveDual_Validate(), ServerMoveDualHybridRootMotion_Validate(), and ServerMoveDualNoBase_Validate().
InPlayRate
float ACharacter::InPlayRate = 1.f
Definition at line 773 of file Character.h.
MeshComponentName
FName ACharacter::MeshComponentName static
Name of the MeshComponent.
Use this name if you want to prevent creation of the component (with ObjectInitializer.DoNotCreateDefaultSubobject).
Definition at line 393 of file Character.h.
MeshRelativeRotation
FRotator ACharacter::MeshRelativeRotation
Definition at line 426 of file Character.h.
NewBase [1/2]
FVector UPrimitiveComponent * ACharacter::NewBase
Definition at line 359 of file Character.h.
Referenced by DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), and SetBase().
NewBase [2/2]
FVector UPrimitiveComponent* ACharacter::NewBase
Definition at line 366 of file Character.h.
NewBaseBoneName [1/2]
FVector UPrimitiveComponent FName ACharacter::NewBaseBoneName
Definition at line 359 of file Character.h.
Referenced by DEPRECATED_CHARACTER_MOVEMENT_RPC(), and DEPRECATED_CHARACTER_MOVEMENT_RPC().
NewBaseBoneName [2/2]
FVector UPrimitiveComponent FName ACharacter::NewBaseBoneName
Definition at line 366 of file Character.h.
NewCustomMode
EMovementMode uint8 uint8 ACharacter::NewCustomMode
Definition at line 938 of file Character.h.
NewFlags
FVector_NetQuantize10 uint8 uint32 float FVector_NetQuantize10 FVector_NetQuantize100 uint8 ACharacter::NewFlags
Definition at line 320 of file Character.h.
Referenced by DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), ServerMoveDual_Validate(), ServerMoveDualHybridRootMotion_Validate(), and ServerMoveDualNoBase_Validate().
NewLoc
FVector ACharacter::NewLoc
Definition at line 359 of file Character.h.
Referenced by DEPRECATED_CHARACTER_MOVEMENT_RPC(), and DEPRECATED_CHARACTER_MOVEMENT_RPC().
NewMovementMode
EMovementMode ACharacter::NewMovementMode
Definition at line 938 of file Character.h.
NewVel
FVector FVector ACharacter::NewVel
Definition at line 359 of file Character.h.
Referenced by DEPRECATED_CHARACTER_MOVEMENT_RPC().
NumActorOverlapEventsCounter
uint32 ACharacter::NumActorOverlapEventsCounter
Incremented every time there is an Actor overlap event (start or stop) on this actor.
Definition at line 652 of file Character.h.
OldAccel
FVector_NetQuantize10 ACharacter::OldAccel
Definition at line 344 of file Character.h.
Referenced by DEPRECATED_CHARACTER_MOVEMENT_RPC(), and ServerMoveOld_Validate().
OldMoveFlags
FVector_NetQuantize10 uint8 ACharacter::OldMoveFlags
Definition at line 344 of file Character.h.
Referenced by DEPRECATED_CHARACTER_MOVEMENT_RPC(), and ServerMoveOld_Validate().
PendingFlags
FVector_NetQuantize10 uint8 ACharacter::PendingFlags
Definition at line 320 of file Character.h.
Referenced by DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), ServerMoveDual_Validate(), ServerMoveDualHybridRootMotion_Validate(), and ServerMoveDualNoBase_Validate().
PreNetReceivedGravityDirection
FVector_NetQuantizeNormal ACharacter::PreNetReceivedGravityDirection protected
Cached version of the replicated gravity direction before replication.
Used to compare if the value was changed as a result of replication.
Definition at line 477 of file Character.h.
PrevCustomMode
EMovementMode uint8 ACharacter::PrevCustomMode
Definition at line 938 of file Character.h.
PreviousFloorContactNormal
const FVector& ACharacter::PreviousFloorContactNormal
Definition at line 855 of file Character.h.
Referenced by OnWalkingOffLedge_Implementation().
PreviousLocation
const FVector const FVector& ACharacter::PreviousLocation
Definition at line 855 of file Character.h.
Referenced by OnWalkingOffLedge_Implementation().
ScaledHalfHeightAdjust
float ACharacter::ScaledHalfHeightAdjust
Definition at line 899 of file Character.h.
Referenced by OnEndCrouch(), OnStartCrouch(), and UFUNCTION().
ServerBase [1/2]
FRootMotionSourceGroup bool float FVector FVector_NetQuantizeNormal float UPrimitiveComponent * ACharacter::ServerBase
Definition at line 373 of file Character.h.
Referenced by DEPRECATED_CHARACTER_MOVEMENT_RPC(), and DEPRECATED_CHARACTER_MOVEMENT_RPC().
ServerBase [2/2]
FRootMotionSourceGroup bool float FVector FVector_NetQuantizeNormal float UPrimitiveComponent* ACharacter::ServerBase
Definition at line 380 of file Character.h.
ServerBoneName [1/2]
FRootMotionSourceGroup bool float FVector FVector_NetQuantizeNormal float UPrimitiveComponent FName ACharacter::ServerBoneName
Definition at line 373 of file Character.h.
Referenced by DEPRECATED_CHARACTER_MOVEMENT_RPC(), and DEPRECATED_CHARACTER_MOVEMENT_RPC().
ServerBoneName [2/2]
FRootMotionSourceGroup bool float FVector FVector_NetQuantizeNormal float UPrimitiveComponent FName ACharacter::ServerBoneName
Definition at line 380 of file Character.h.
ServerLoc [1/2]
FRootMotionSourceGroup bool float FVector ACharacter::ServerLoc
Definition at line 373 of file Character.h.
Referenced by DEPRECATED_CHARACTER_MOVEMENT_RPC(), and DEPRECATED_CHARACTER_MOVEMENT_RPC().
ServerLoc [2/2]
FRootMotionSourceGroup bool float FVector ACharacter::ServerLoc
Definition at line 380 of file Character.h.
ServerMontageTrackPosition [1/2]
FRootMotionSourceGroup bool float ACharacter::ServerMontageTrackPosition
Definition at line 373 of file Character.h.
Referenced by DEPRECATED_CHARACTER_MOVEMENT_RPC(), and DEPRECATED_CHARACTER_MOVEMENT_RPC().
ServerMontageTrackPosition [2/2]
FRootMotionSourceGroup bool float ACharacter::ServerMontageTrackPosition
Definition at line 380 of file Character.h.
ServerMovementMode [1/4]
FRootMotionSourceGroup bool float FVector FVector_NetQuantizeNormal float UPrimitiveComponent FName bool bool uint8 ACharacter::ServerMovementMode
Definition at line 359 of file Character.h.
Referenced by DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), and DEPRECATED_CHARACTER_MOVEMENT_RPC().
ServerMovementMode [2/4]
FVector UPrimitiveComponent FName bool bool uint8 ACharacter::ServerMovementMode
Definition at line 366 of file Character.h.
ServerMovementMode [3/4]
float FVector FVector_NetQuantizeNormal float UPrimitiveComponent FName bool bool uint8 ACharacter::ServerMovementMode
Definition at line 373 of file Character.h.
ServerMovementMode [4/4]
FRootMotionSourceGroup bool float FVector FVector_NetQuantizeNormal float UPrimitiveComponent FName bool bool uint8 ACharacter::ServerMovementMode
Definition at line 380 of file Character.h.
ServerRootMotion
FRootMotionSourceGroup ACharacter::ServerRootMotion
Definition at line 380 of file Character.h.
Referenced by DEPRECATED_CHARACTER_MOVEMENT_RPC().
ServerRotation [1/2]
FRootMotionSourceGroup bool float FVector FVector_NetQuantizeNormal ACharacter::ServerRotation
Definition at line 373 of file Character.h.
Referenced by DEPRECATED_CHARACTER_MOVEMENT_RPC(), and DEPRECATED_CHARACTER_MOVEMENT_RPC().
ServerRotation [2/2]
FRootMotionSourceGroup bool float FVector FVector_NetQuantizeNormal ACharacter::ServerRotation
Definition at line 380 of file Character.h.
ServerVelZ [1/2]
FRootMotionSourceGroup bool float FVector FVector_NetQuantizeNormal float ACharacter::ServerVelZ
Definition at line 373 of file Character.h.
Referenced by DEPRECATED_CHARACTER_MOVEMENT_RPC(), and DEPRECATED_CHARACTER_MOVEMENT_RPC().
ServerVelZ [2/2]
FRootMotionSourceGroup bool float FVector FVector_NetQuantizeNormal float ACharacter::ServerVelZ
Definition at line 380 of file Character.h.
StartSectionName
float FName ACharacter::StartSectionName = NAME_None)
Definition at line 773 of file Character.h.
TimeDelta
const FVector const FVector float ACharacter::TimeDelta
Definition at line 855 of file Character.h.
Referenced by OnWalkingOffLedge_Implementation().
TimeStamp
FVector_NetQuantize10 uint8 uint32 float ACharacter::TimeStamp
Definition at line 320 of file Character.h.
Referenced by DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), ServerMove_Validate(), ServerMoveDual_Validate(), ServerMoveDualHybridRootMotion_Validate(), ServerMoveDualNoBase_Validate(), and ServerMoveNoBase_Validate().
View [1/2]
FVector_NetQuantize10 uint8 uint32 float FVector_NetQuantize10 FVector_NetQuantize100 uint8 uint8 uint32 ACharacter::View
Definition at line 301 of file Character.h.
Referenced by DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), ServerMove_Validate(), ServerMoveDual_Validate(), ServerMoveDualHybridRootMotion_Validate(), ServerMoveDualNoBase_Validate(), and ServerMoveNoBase_Validate().
View [2/2]
FVector_NetQuantize10 uint8 uint32 float FVector_NetQuantize10 FVector_NetQuantize100 uint8 uint8 uint32 ACharacter::View
Definition at line 320 of file Character.h.
View0
FVector_NetQuantize10 uint8 uint32 ACharacter::View0
Definition at line 320 of file Character.h.
Referenced by DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), DEPRECATED_CHARACTER_MOVEMENT_RPC(), ServerMoveDual_Validate(), ServerMoveDualHybridRootMotion_Validate(), and ServerMoveDualNoBase_Validate().
The documentation for this class was generated from the following file:
Runtime/Engine/Classes/GameFramework/Character.h