Unreal Engine 5.6 C++ API: TMeshAttributeArrayBase< AttributeType > Class Template Reference
TMeshAttributeArrayBase< AttributeType > Class Template Reference
This defines the container used to hold mesh element attributes of a particular name and index.
#include "MeshAttributeArray.h"
Public Member Functions
TMeshAttributeArrayBase (uint32 InExtent=1)
FORCEINLINE AttributeType * GetElementBase (const int32 Index)
FORCEINLINE const AttributeType * GetElementBase (const int32 Index) const
FORCEINLINE uint32 GetExtent () const
uint32 GetHash (uint32 Crc) const
uint32 GetHash (uint32 Crc=0) const
FORCEINLINE void Initialize (const int32 ElementCount, const AttributeType &Default)
Initializes the array to the given size with the default value.
void Insert (const int32 Index, const AttributeType &Default)
Expands the array if necessary so that the passed element index is valid.
FORCEINLINE int32 Num () const
Return size of container.
void Remap (const TSparseArray< int32 > &IndexRemap, const AttributeType &Default)
Remaps elements according to the passed remapping table.
void SetNum (const int32 ElementCount, const AttributeType &Default)
void SetToDefault (const int32 Index, const AttributeType &Default)
Fills the index with the default value.
UE_DEPRECATED (5.0, "Please use GetElementBase() instead.") FORCEINLINE AttributeType &operator[](const int32 Index)
UE_DEPRECATED (5.0, "Please use GetElementBase() instead.") FORCEINLINE const AttributeType &operator[](const int32 Index) const
Element accessors.
UE_DEPRECATED (5.0, "This method will be removed.") FORCEINLINE const AttributeType *GetData() const
Return base of data.
Protected Attributes
TArray< AttributeType > Container
The actual container, represented by a regular array.
uint32 Extent
Number of array elements in this attribute type.
Friends
template<typename T>
TEnableIf<!TIsBulkSerializable< T >::Value, FArchive >::Type & operator<< (FArchive &Ar, TMeshAttributeArrayBase< T > &Array)
Custom serialization for TMeshAttributeArrayBase.
template<typename T>
TEnableIf< TIsBulkSerializable< T >::Value, FArchive >::Type & operator<< (FArchive &Ar, TMeshAttributeArrayBase< T > &Array)
Detailed Description
template<typename AttributeType>
class TMeshAttributeArrayBase< AttributeType >
This defines the container used to hold mesh element attributes of a particular name and index.
It is a simple TArray, so that all attributes are packed contiguously for each element ID.
Note that the container may grow arbitrarily as new elements are inserted, but it will never be shrunk as elements are removed. The only operations that will shrink the container are Initialize() and Remap().
Definition at line 82 of file MeshAttributeArray.h.
Constructor & Destructor Documentation
TMeshAttributeArrayBase()
template<typename AttributeType> TMeshAttributeArrayBase< AttributeType >::TMeshAttributeArrayBase (uint32 InExtent = 1) inline explicit
Definition at line 85 of file MeshAttributeArray.h.
References Extent.
Referenced by operator<<, and Remap().
Member Function Documentation
GetElementBase() [1/2]
template<typename AttributeType> FORCEINLINE AttributeType * TMeshAttributeArrayBase< AttributeType >::GetElementBase (const int32 Index) inline
Definition at line 152 of file MeshAttributeArray.h.
References Container, Extent, and FORCEINLINE.
GetElementBase() [2/2]
template<typename AttributeType> FORCEINLINE const AttributeType * TMeshAttributeArrayBase< AttributeType >::GetElementBase (const int32 Index) const inline
Definition at line 151 of file MeshAttributeArray.h.
References Container, Extent, and FORCEINLINE.
Referenced by TMeshAttributesRef< ElementIDType, AttributeType >::Copy(), TMeshAttributesRef< ElementIDType, TArrayView< AttributeType > >::Copy(), and Remap().
GetExtent()
template<typename AttributeType> FORCEINLINE uint32 TMeshAttributeArrayBase< AttributeType >::GetExtent () const inline
Definition at line 154 of file MeshAttributeArray.h.
References Extent, and FORCEINLINE.
GetHash() [1/2]
uint32 TMeshAttributeArrayBase< FName >::GetHash (uint32 Crc) const inline
Definition at line 167 of file MeshAttributeArray.h.
References Container, Item, and FCrc::MemCrc32().
GetHash() [2/2]
template<typename AttributeType> uint32 TMeshAttributeArrayBase< AttributeType >::GetHash (uint32 Crc = 0) const inline
Definition at line 124 of file MeshAttributeArray.h.
References Container, and FCrc::MemCrc32().
Initialize()
template<typename AttributeType> FORCEINLINE void TMeshAttributeArrayBase< AttributeType >::Initialize (const int32 ElementCount, const AttributeType & Default) inline
Initializes the array to the given size with the default value.
Definition at line 101 of file MeshAttributeArray.h.
References Container, Default, Extent, FORCEINLINE, and Insert().
Insert()
template<typename AttributeType> void TMeshAttributeArrayBase< AttributeType >::Insert (const int32 Index, const AttributeType & Default)
Expands the array if necessary so that the passed element index is valid.
Newly created elements will be assigned the default value.
Definition at line 178 of file MeshAttributeArray.h.
References Container, Default, and Extent.
Referenced by Initialize(), Remap(), and SetNum().
Num()
template<typename AttributeType> FORCEINLINE int32 TMeshAttributeArrayBase< AttributeType >::Num () const inline
Return size of container.
Definition at line 94 of file MeshAttributeArray.h.
References Container, Extent, and FORCEINLINE.
Referenced by TMeshAttributesRef< ElementIDType, AttributeType >::Copy(), and TMeshAttributesRef< ElementIDType, TArrayView< AttributeType > >::Copy().
Remap()
template<typename AttributeType> void TMeshAttributeArrayBase< AttributeType >::Remap (const TSparseArray< int32 > & IndexRemap, const AttributeType & Default)
Remaps elements according to the passed remapping table.
Definition at line 199 of file MeshAttributeArray.h.
References TMeshAttributeArrayBase(), Container, Default, Extent, GetElementBase(), Insert(), and MoveTemp().
SetNum()
template<typename AttributeType> void TMeshAttributeArrayBase< AttributeType >::SetNum (const int32 ElementCount, const AttributeType & Default) inline
Definition at line 110 of file MeshAttributeArray.h.
References Container, Default, Extent, and Insert().
SetToDefault()
template<typename AttributeType> void TMeshAttributeArrayBase< AttributeType >::SetToDefault (const int32 Index, const AttributeType & Default) inline
Fills the index with the default value.
Definition at line 133 of file MeshAttributeArray.h.
References Container, Default, and Extent.
UE_DEPRECATED() [1/3]
template<typename AttributeType> TMeshAttributeArrayBase< AttributeType >::UE_DEPRECATED (5. 0, "Please use GetElementBase() instead.") const & inline
Definition at line 148 of file MeshAttributeArray.h.
References Container, and FORCEINLINE.
UE_DEPRECATED() [2/3]
template<typename AttributeType> TMeshAttributeArrayBase< AttributeType >::UE_DEPRECATED (5. 0, "Please use GetElementBase() instead.") const & inline
Element accessors.
Definition at line 145 of file MeshAttributeArray.h.
References Container, and FORCEINLINE.
UE_DEPRECATED() [3/3]
template<typename AttributeType> TMeshAttributeArrayBase< AttributeType >::UE_DEPRECATED (5. 0, "This method will be removed.") const inline
Return base of data.
Definition at line 97 of file MeshAttributeArray.h.
References Container, FORCEINLINE, and GetData().
Friends And Related Symbol Documentation
operator<< [1/2]
template<typename AttributeType> template<typename T> TEnableIf<!TIsBulkSerializable< T >::Value, FArchive >::Type & operator<< (FArchive & Ar, TMeshAttributeArrayBase< T > & Array) friend
Custom serialization for TMeshAttributeArrayBase.
Definition at line 221 of file MeshAttributeArray.h.
References TMeshAttributeArrayBase(), Ar, Array, FFortniteMainBranchObjectVersion::GUID, FReleaseObjectVersion::GUID, FUE5MainStreamObjectVersion::GUID, FReleaseObjectVersion::MeshDescriptionNewFormat, and FCustomVersion::Version.
operator<< [2/2]
template<typename AttributeType> template<typename T> TEnableIf< TIsBulkSerializable< T >::Value, FArchive >::Type & operator<< (FArchive & Ar, TMeshAttributeArrayBase< T > & Array) friend
Definition at line 221 of file MeshAttributeArray.h.
Field Documentation
Container
template<typename AttributeType> TArray<AttributeType> TMeshAttributeArrayBase< AttributeType >::Container protected
The actual container, represented by a regular array.
Definition at line 158 of file MeshAttributeArray.h.
Referenced by GetElementBase(), GetElementBase(), GetHash(), GetHash(), Initialize(), Insert(), Num(), Remap(), SetNum(), SetToDefault(), UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
Extent
template<typename AttributeType> uint32 TMeshAttributeArrayBase< AttributeType >::Extent protected
Number of array elements in this attribute type.
Definition at line 161 of file MeshAttributeArray.h.
Referenced by TMeshAttributeArrayBase(), GetElementBase(), GetElementBase(), GetExtent(), Initialize(), Insert(), Num(), Remap(), SetNum(), and SetToDefault().
The documentation for this class was generated from the following file:
Runtime/MeshDescription/Public/MeshAttributeArray.h