Unreal Engine 5.6 C++ API: UE::Geometry::FDynamicGraphN Class Reference
UE::Geometry::FDynamicGraphN Class Reference
Implementation of DGraph that has no dimensionality, ie no data stored for vertices besides indices.
#include "DynamicGraph.h"
Public Member Functions
int AppendVertex ()
Public Member Functions inherited from UE::Geometry::FDynamicGraph
FDynamicGraph ()
virtual ~FDynamicGraph ()
int AllocateEdgeGroup ()
int AppendEdge (const FEdge &E)
int AppendEdge (const FIndex2i &ev, int GID=-1)
int AppendEdge (int v0, int v1, int GID=-1)
virtual bool CheckValidity (EValidityCheckFailMode FailMode=EValidityCheckFailMode::Check) const
This function checks that the graph is well-formed, ie all internal data structures are consistent.
EMeshResult CollapseEdge (int VKeep, int VRemove, FEdgeCollapseInfo &Collapse)
int EdgeCount () const
edge_iterator EdgeIndices () const
value_iteration< FEdge > Edges () const
Enumerate edges.
int FindEdge (int VA, int VB) const
FEdge GetEdge (int EID) const
int GetEdgeGroup (int EID) const
FIndex2i GetEdgeV (int EID) const
int GetMaxVtxEdgeCount () const
int GetVtxEdgeCount (int VID) const
bool IsBoundaryVertex (int VID) const
bool IsCompact () const
bool IsCompactV () const
bool IsEdge (int EID) const
bool IsJunctionVertex (int VID) const
bool IsRegularVertex (int VID) const
bool IsVertex (int VID) const
int MaxEdgeID () const
int MaxGroupID () const
int MaxVertexID () const
EMeshResult RemoveEdge (int EID, bool bRemoveIsolatedVertices)
EMeshResult RemoveVertex (int VID, bool bRemoveIsolatedVertices)
void SetEdgeGroup (int EID, int GroupID)
int ShapeTimestamp () const
EMeshResult SplitEdge (int EAB, FEdgeSplitInfo &Split)
EMeshResult SplitEdge (int VA, int VB, FEdgeSplitInfo &Split)
EMeshResult SplitEdgeWithExistingVertex (int EAB, int ExistingMidVert, FEdgeSplitInfo &Split)
int Timestamp () const
int VertexCount () const
vertex_iterator VertexIndices () const
FSmallListSet::ValueEnumerable VtxEdgesItr (int VID) const
Enumerate edge ids connected to vertex (i.e.
FSmallListSet::MappedValueEnumerable VtxVerticesItr (int VID) const
Enumerate "other" vertices of edges connected to vertex (i.e.
Protected Member Functions
virtual int append_new_split_vertex (int A, int B) override
Protected Member Functions inherited from UE::Geometry::FDynamicGraph
int add_edge (int A, int B, int GID)
int append_vertex_internal ()
void debug_check_is_edge (int E) const
void debug_check_is_vertex (int V) const
bool edge_has_v (int EID, int VID) const
int edge_other_v (int EID, int VID) const
bool insert_vertex_internal (int32 Vid)
int replace_edge_vertex (int EID, int VOld, int VNew)
virtual void subclass_validity_checks (TFunction< void(bool)> CheckOrFailF) const
void updateTimeStamp (bool bShapeChange)
Additional Inherited Members
Public Types inherited from UE::Geometry::FDynamicGraph
typedef FRefCountVector::IndexEnumerable edge_iterator
template<typename T>
using value_iteration = FRefCountVector::MappedEnumerable<T>
typedef FRefCountVector::IndexEnumerable vertex_iterator
Static Public Member Functions inherited from UE::Geometry::FDynamicGraph
static FEdge InvalidEdge3 ()
static FIndex2i InvalidEdgeV ()
Static Public Attributes inherited from UE::Geometry::FDynamicGraph
static constexpr int DuplicateEdgeID = -2
static constexpr int InvalidID = IndexConstants::InvalidID
Protected Attributes inherited from UE::Geometry::FDynamicGraph
TDynamicVector< FEdge > edges
FRefCountVector edges_refcount
int max_group_id = 0
int shape_timestamp = 0
int timestamp = 0
FSmallListSet vertex_edges
FRefCountVector vertices_refcount
Detailed Description
Implementation of DGraph that has no dimensionality, ie no data stored for vertices besides indices.
Definition at line 709 of file DynamicGraph.h.
Member Function Documentation
append_new_split_vertex()
virtual int UE::Geometry::FDynamicGraphN::append_new_split_vertex (int A, int B) inline override protected virtual
Reimplemented from UE::Geometry::FDynamicGraph.
Definition at line 719 of file DynamicGraph.h.
References A, AppendVertex(), and B.
AppendVertex()
int UE::Geometry::FDynamicGraphN::AppendVertex () inline
Definition at line 712 of file DynamicGraph.h.
References UE::Geometry::FDynamicGraph::append_vertex_internal().
Referenced by append_new_split_vertex().
The documentation for this class was generated from the following file:
Runtime/GeometryCore/Public/Curve/DynamicGraph.h