Unreal Engine 5.6 C++ API: USkeletalMeshComponent Class Reference
USkeletalMeshComponent Class Reference
#include "SkeletalMeshComponent.h"
Data Structures
struct FPendingRadialForces
Public Types
typedef FOnSkeletalMeshPropertyChangedMulticaster::FDelegate FOnSkeletalMeshPropertyChanged
typedef FOnSkeletalMeshUnregisterd::FDelegate FOnSkeletalMeshUnregisteredDelegate
Public Member Functions
void AddClothingBounds (FBoxSphereBounds &InOutBounds, const FTransform &LocalToWorld) const
Given bounds InOutBounds, expand them to also enclose the clothing simulation mesh.
virtual void AddRadialForce (FVector Origin, float Radius, float Strength, ERadialImpulseFalloff Falloff, bool bAccelChange=false) override
virtual void AddRadialImpulse (FVector Origin, float Radius, float Strength, ERadialImpulseFalloff Falloff, bool bVelChange=false) override
virtual bool AllocateTransformData () override
PRAGMA_ENABLE_DEPRECATION_WARNINGS void AllowQueuedAnimEventsNextDispatch ()
If true, next time that ConditionallyDispatchQueuedAnimEvents() is called it will trigger any queued anim notifies available.
void ApplyAnimationCurvesToComponent (const TMap< FName, float > *InMaterialParameterCurves, const TMap< FName, float > *InAnimationMorphCurves)
Apply animation curves to this component.
void ApplyDeltaToAllPhysicsTransforms (const FVector &DeltaLocation, const FQuat &DeltaRotation)
Set physics transforms for all bodies.
void ApplyEditedComponentSpaceTransforms ()
Called after modifying Component Space Transforms externally.
virtual void BeginPlay () override
virtual FBoxSphereBounds CalcBounds (const FTransform &LocalToWorld) const override
virtual float CalculateMass (FName BoneName=NAME_None) override
virtual bool CanEditSimulatePhysics () override
virtual const bool CanHaveStaticMobility () const override
Skeletal mesh component should not be able to have its mobility set to static.
bool CanSimulateClothing () const
virtual void CheckClothTeleport ()
Check linear and angular thresholds for clothing teleport.
virtual void ClearAnimNotifyErrors (UObject *InSourceNotify)
Clears currently stored errors.
void ClearAnimScriptInstance ()
void ClearCachedAnimProperties ()
Clear cached animation data generated for URO during evaluation.
virtual void ClearRefPoseOverride () override
virtual void CompleteParallelAnimationEvaluation (bool bDoPostAnimEvaluation)
void CompleteParallelClothSimulation ()
Callback when the parallel clothing task finishes, copies needed data back to component for gamethread.
virtual bool ComponentIsTouchingSelectionBox (const FBox &InSelBBox, const bool bConsiderOnlyBSP, const bool bMustEncompassEntireComponent) const override
virtual bool ComponentIsTouchingSelectionFrustum (const FConvexVolume &InFrustum, const bool bConsiderOnlyBSP, const bool bMustEncompassEntireComponent) const override
void ComputeRequiredBones (TArray< FBoneIndexType > &OutRequiredBones, TArray< FBoneIndexType > &OutFillComponentSpaceTransformsRequiredBones, int32 LODIndex, bool bIgnorePhysicsAsset) const
Computes the required bones in this SkeletalMeshComponent based on current SkeletalMesh, LOD and PhysicsAsset.
void ConditionallyDispatchQueuedAnimEvents ()
FRootMotionMovementParams ConsumeRootMotion ()
Consume and return pending root motion from our internal anim instances (main, sub and post)
FTransform ConvertLocalRootMotionToWorld (const FTransform &InTransform)
Take extracted RootMotion and convert it from local space to world space.
void CreateBodySetup ()
virtual void DeallocateTransformData () override
void DebugDrawClothing (FPrimitiveDrawInterface *PDI)
Draw the currently clothing state, using the editor extender interface.
void DebugDrawClothingTexts (FCanvas *Canvas, const FSceneView *SceneView)
Draw the currently clothing state, using the editor extender interface.
DECLARE_MULTICAST_DELEGATE (FOnSkeletalMeshPropertyChangedMulticaster) FOnSkeletalMeshPropertyChangedMulticaster OnSkeletalMeshPropertyChanged
DECLARE_MULTICAST_DELEGATE_OneParam (FOnSkeletalMeshUnregisterd, const USkeletalMeshComponent *) FOnSkeletalMeshUnregisterd OnSkeletalMeshUnregistered
virtual bool DoCustomNavigableGeometryExport (FNavigableGeometryExport &GeomExport) const override
void EvaluatePostProcessMeshInstance (TArray< FTransform > &OutBoneSpaceTransforms, FCompactPose &InOutPose, FBlendedHeapCurve &OutCurve, const USkeletalMesh *InSkeletalMesh, FVector &OutRootBoneTranslation, UE::Anim::FHeapAttributeContainer &OutAttributes, bool bInForceRefPose) const
Evaluates the post process instance from the skeletal mesh this component is using.
virtual void FinalizeBoneTransform () override
int32 FindConstraintIndex (FName ConstraintName)
Find Constraint Index from the name.
FConstraintInstance * FindConstraintInstance (FName ConName)
Find instance of the constraint that matches the name supplied.
int32 FindRootBodyIndex () const
Find the root body index.
void ForEachAnimInstance (TFunctionRef< void(UAnimInstance *)> InFunction)
Calls a function on each of the anim instances that this mesh component hosts, including linked and post-process instances.
int32 ForEachBodyBelow (FName BoneName, bool bIncludeSelf, bool bSkipCustomType, TFunctionRef< void(FBodyInstance *)> Func)
Iterates over all bodies below and executes Func.
virtual TArray< Chaos::FPhysicsObject * > GetAllPhysicsObjects () const override
const FBlendedHeapCurve & GetAnimationCurves () const
Access Curve Array for reading.
const FBlendedHeapCurve & GetAnimCurves () const
Get the current set of curve values.
virtual FBodyInstance * GetBodyInstance (FName BoneName=NAME_None, bool bGetWelded=true, int32 Index=INDEX_NONE) const override
virtual class UBodySetup * GetBodySetup () override
TArray< FTransform > GetBoneSpaceTransforms ()
TArrayView< const FTransform > GetBoneSpaceTransformsView ()
Get the bone space transforms as array view.
const TArray< FTransform > & GetCachedComponentSpaceTransforms () const
Access cached component space transforms.
FVector GetClosestCollidingRigidBodyLocation (const FVector &TestLocation) const
iterates through all bodies in our PhysicsAsset and returns the location of the closest bone associated with a body that has collision enabled.
bool GetClosestPointOnPhysicsAsset (const FVector &WorldPosition, FClosestPointOnPhysicsAsset &ClosestPointOnPhysicsAsset, bool bApproximate) const
Given a world position, find the closest point on the physics asset.
const TArray< FClothCollisionSource > & GetClothCollisionSources () const
IClothingSimulation * GetClothingSimulation ()
Get the current clothing simulation (read/write)
const IClothingSimulation * GetClothingSimulation () const
Get the current clothing simulation (read only)
IClothingSimulationContext * GetClothingSimulationContext ()
Get the current clothing simulation context (read/write)
const IClothingSimulationContext * GetClothingSimulationContext () const
Get the current clothing simulation context (read only)
bool GetClothSimulatedPosition_GameThread (const FGuid &AssetGuid, int32 VertexIndex, FVector &OutSimulPos) const
if the vertex index is valid for simulated vertices, returns the position in world space
virtual TStructOnScope< FActorComponentInstanceData > GetComponentInstanceData () const override
FConstraintInstance * GetConstraintInstanceByIndex (uint32 Index)
get instance of the constraint that matches the index .
bool GetConstraintProfilePropertiesOrDefault (FConstraintProfileProperties &OutProperties, FName JointName, FName ProfileName)
Gets the constraint profile properties that a joint drive would adopt if it were set to the given constraint profile.
const TMap< int32, FClothSimulData > & GetCurrentClothingData_AnyThread () const
Get the current simulation data map for the clothing on this component.
const TMap< int32, FClothSimulData > & GetCurrentClothingData_GameThread () const
Get the current simulation data map for the clothing on this component.
UE::Anim::FCurveFilterSettings GetCurveFilterSettings (int32 InLODOverride=INDEX_NONE) const
Get the curve settings that will be used for anim evaluation.
const UE::Anim::FMeshAttributeContainer & GetCustomAttributes () const
FBlendedHeapCurve & GetEditableAnimationCurves ()
Get Access to the current editable Curve Array - uses same buffer as space bases.
const FBlendedHeapCurve & GetEditableAnimationCurves () const
PRAGMA_DISABLE_DEPRECATION_WARNINGS const TArray< UAnimInstance * > & GetLinkedAnimInstances () const
Get the anim instances linked to the main AnimScriptInstance.
virtual float GetMass () const override
const TMap< FName, float > & GetMorphTargetCurves () const
const TArray< FPendingRadialForces > & GetPendingRadialForces () const
virtual Chaos::FPhysicsObject * GetPhysicsObjectById (Chaos::FPhysicsObjectId Id) const override
virtual Chaos::FPhysicsObject * GetPhysicsObjectByName (const FName &Name) const override
TSubclassOf< UAnimInstance > GetPostProcessAnimBPClassToBeUsed () const
Get the post-processing AnimBP to be used for this skeletal mesh component.
virtual void GetResourceSizeEx (FResourceSizeEx &CumulativeResourceSize) override
TSharedPtr< struct FBoneContainer > GetSharedRequiredBones ()
Gets the shared bone container used between all owned anim instances.
class UAnimSingleNodeInstance * GetSingleNodeInstance () const
virtual bool GetSquaredDistanceToCollision (const FVector &Point, float &OutSquaredDistance, FVector &OutClosestPointOnCollision) const override
float GetTotalMassBelowBone (FName InBoneName)
Utility which returns total mass of all bones below the supplied one in the hierarchy (including this one).
bool GetUpdateAnimationInEditor () const
return true if currently updating in editor is true this is non BP because this is only used for follower component to detect leader component ticking state
bool GetUpdateClothInEditor () const
virtual void GetUpdateClothSimulationData_AnyThread (TMap< int32, FClothSimulData > &OutClothSimulData, FMatrix &OutLocalToWorld, float &OutClothBlendWeight) const override
Store cloth simulation data into OutClothSimulData.
void GetWeldedBodies (TArray< FBodyInstance * > &OutWeldedBodies, TArray< FName > &OutChildrenLabels, bool bIncludingAutoWeld=false) override
bool HandleExistingParallelEvaluationTask (bool bBlockOnTask, bool bPerformPostAnimEvaluation)
virtual bool HasValidPhysicsState () const override
virtual void HideBone (int32 BoneIndex, EPhysBodyOp PhysBodyOption) override
virtual void InitAnim (bool bForceReinit)
void InitArticulated (FPhysScene *PhysScene)
Initialize PhysicsAssetInstance for the physicsAsset.
void InitCollisionRelationships ()
bool InitializeAnimScriptInstance (bool bForceReinit=true, bool bInDeferRootNodeInitialization=false)
virtual void InitializeComponent () override
void InitSkelControls ()
Initialize SkelControls.
void InstantiatePhysicsAsset (const UPhysicsAsset &PhysAsset, const FVector &Scale3D, TArray< FBodyInstance * > &OutBodies, TArray< FConstraintInstance * > &OutConstraints, FPhysScene *PhysScene=nullptr, USkeletalMeshComponent *OwningComponent=nullptr, int32 UseRootBodyIndex=INDEX_NONE, const FPhysicsAggregateHandle &UseAggregate=FPhysicsAggregateHandle()) const
Instantiates bodies given a physics asset.
void InstantiatePhysicsAssetBodies (const UPhysicsAsset &PhysAsset, TArray< FBodyInstance * > &OutBodies, FPhysScene *PhysScene=nullptr, USkeletalMeshComponent *OwningComponent=nullptr, int32 UseRootBodyIndex=INDEX_NONE, const FPhysicsAggregateHandle &UseAggregate=FPhysicsAggregateHandle()) const
Instantiates only the bodies given a physics asset, not the constraints.
void InstantiatePhysicsAssetRefPose (const UPhysicsAsset &PhysAsset, const FVector &Scale3D, TArray< FBodyInstance * > &OutBodies, TArray< FConstraintInstance * > &OutConstraints, FPhysScene *PhysScene=nullptr, USkeletalMeshComponent *OwningComponent=nullptr, int32 UseRootBodyIndex=INDEX_NONE, const FPhysicsAggregateHandle &UseAggregate=FPhysicsAggregateHandle(), bool bCreateBodiesInRefPose=false) const
Instantiates bodies given a physics asset like InstantiatePhysicsAsset but instead of reading the current component state, this reads the ref-pose from the reference skeleton of the mesh.
bool IsAnimBlueprintInstanced () const
virtual bool IsAnyRigidBodyAwake () override
virtual bool IsAnySimulatingPhysics () const override
bool IsClothBoundToLeaderComponent () const
virtual bool IsGravityEnabled () const override
virtual bool IsPlayingNetworkedRootMotionMontage () const override
virtual bool IsPlayingRootMotion () const override
virtual bool IsPlayingRootMotionFromEverything () const override
bool IsPostEvaluatingAnimation () const
bool IsRunningParallelEvaluation () const
virtual bool IsShown (const FEngineShowFlags &ShowFlags) const override
virtual bool IsSimulatingPhysics (FName BoneName=NAME_None) const override
virtual bool IsWindEnabled () const
virtual bool LineTraceComponent (FHitResult &OutHit, const FVector Start, const FVector End, const FCollisionQueryParams &Params) override
virtual void LoadedFromAnotherClass (const FName &OldClassName) override
virtual void NotifySkelControlBeyondLimit (class USkelControlLookAt *LookAt)
Notifier when look at control goes beyond of limit - candidate for delegate.
virtual void OnComponentCollisionSettingsChanged (bool bUpdateOverlaps=true) override
virtual void OnComponentDestroyed (bool bDestroyingHierarchy) override
virtual void OnPreEndOfFrameSync () override
virtual void OnUpdateTransform (EUpdateTransformFlags UpdateTransformFlags, ETeleportType Teleport=ETeleportType::None) override
virtual bool OverlapComponent (const FVector &Pos, const FQuat &Rot, const FCollisionShape &CollisionShape) const override
void ParallelAnimationEvaluation ()
void PerformAnimationEvaluation (const USkeletalMesh *InSkeletalMesh, UAnimInstance *InAnimInstance, TArray< FTransform > &OutSpaceBases, TArray< FTransform > &OutBoneSpaceTransforms, FVector &OutRootBoneTranslation, FBlendedHeapCurve &OutCurve, UE::Anim::FMeshAttributeContainer &OutAttributes)
Runs the animation evaluation for the current pose into the supplied variables PerformAnimationProcessing runs evaluation based on bInDoEvaluation.
void PerformAnimationProcessing (const USkeletalMesh *InSkeletalMesh, UAnimInstance *InAnimInstance, bool bInDoEvaluation, bool bInForceRefPose, TArray< FTransform > &OutSpaceBases, TArray< FTransform > &OutBoneSpaceTransforms, FVector &OutRootBoneTranslation, FBlendedHeapCurve &OutCurve, UE::Anim::FMeshAttributeContainer &OutAttributes)
bool PoseTickedThisFrame () const
Checked whether we have already ticked the pose this frame.
void PostAnimEvaluation (FAnimationEvaluationContext &EvaluationContext)
virtual void PostEditChangeProperty (FPropertyChangedEvent &PropertyChangedEvent) override
virtual void PostInitProperties () override
virtual void PostLoad () override
virtual void PutAllRigidBodiesToSleep () override
void RecalcRequiredBones (int32 LODIndex)
Recalculates the RequiredBones array in this SkeletalMeshComponent based on current SkeletalMesh, LOD and PhysicsAsset.
void RecalcRequiredCurves ()
Recalculates the AnimCurveUids array in RequiredBone of this SkeletalMeshComponent based on current required bone set Is called when Skeleton->IsRequiredCurvesUpToDate() = false.
virtual void RefreshBoneTransforms (FActorComponentTickFunction *TickFunction=NULL) override
void RefreshSkeletalMeshAsset ()
Sets the SkeletalMeshAsset to the current SkeletalMesh.
void RegisterClothTick (bool bRegister)
virtual void RegisterEndPhysicsTick (bool bRegister)
virtual FDelegateHandle RegisterOnBoneTransformsFinalizedDelegate (const FOnBoneTransformsFinalizedMultiCast::FDelegate &Delegate) override
Register/Unregister for OnBoneTransformsFinalized callback.
FDelegateHandle RegisterOnPhysicsCreatedDelegate (const FOnSkelMeshPhysicsCreated &Delegate)
Register/Unregister for physics state creation callback.
FDelegateHandle RegisterOnSkeletalMeshPropertyChanged (const FOnSkeletalMeshPropertyChanged &Delegate)
Register / Unregister delegates called when the skeletal mesh property is changed.
FDelegateHandle RegisterOnSkeletalMeshUnregistered (const FOnSkeletalMeshUnregisteredDelegate &Delegate)
Register / Unregister delegates called when the mesh component is unregistered.
FDelegateHandle RegisterOnTeleportDelegate (const FOnSkelMeshTeleported &Delegate)
Register/Unregister for teleport callback.
void ReleaseAllClothingResources ()
Remove all clothing actors from their simulation and clear any other necessary clothing data to leave the simulations in a clean state.
void RemoveAllClothingActors ()
Remove clothing actors from their simulation.
virtual void ReportAnimNotifyError (const FText &Error, UObject *InSourceNotify)
Subclasses such as DebugSkelMeshComponent keep track of errors in the anim notifies so they can be displayed to the user.
virtual bool RequiresPreEndOfFrameSync () const override
void ResetRootBodyIndex ()
Reset Root Body Index.
virtual void Serialize (FArchive &Ar) override
void SetAllBodiesCollisionObjectType (ECollisionChannel NewChannel)
Set the movement channel of all bodies.
void SetAllBodiesNotifyRigidBodyCollision (bool bNewNotifyRigidBodyCollision)
Set the rigid body notification state for all bodies.
virtual void SetAllMassScale (float InMassScale=1.f) override
virtual void SetAllPhysicsAngularVelocityInRadians (FVector const &NewVel, bool bAddToCurrent=false) override
virtual void SetAllPhysicsLinearVelocity (FVector NewVel, bool bAddToCurrent=false) override
virtual void SetAllPhysicsPosition (FVector NewPos) override
virtual void SetAllPhysicsRotation (const FQuat &NewRot) override
virtual void SetAllPhysicsRotation (FRotator NewRot) override
virtual void SetAllUseCCD (bool InUseCCD) override
virtual void SetCollisionObjectType (ECollisionChannel Channel) override
Set the collision object type on the skeletal mesh.
virtual void SetComponentTickEnabled (bool bEnabled) override
virtual void SetEnableGravity (bool bGravityEnabled)
void SetForceRefPose (bool bNewForceRefPose)
Change whether to force mesh into ref pose (and use cheaper vertex shader)
void SetNamedMotorsAngularPositionDrive (bool bEnableSwingDrive, bool bEnableTwistDrive, const TArray< FName > &BoneNames, bool bSetOtherBodiesToComplement=false)
Enable or Disable AngularPositionDrive based on a list of bone names.
void SetNamedMotorsAngularVelocityDrive (bool bEnableSwingDrive, bool bEnableTwistDrive, const TArray< FName > &BoneNames, bool bSetOtherBodiesToComplement=false)
Enable or Disable AngularVelocityDrive based on a list of bone names.
virtual void SetNotifyRigidBodyCollision (bool bNewNotifyRigidBodyCollision) override
Changes the value of bNotifyRigidBodyCollision.
virtual void SetPhysicsAsset (class UPhysicsAsset *NewPhysicsAsset, bool bForceReInit=false) override
virtual void SetPhysMaterialOverride (UPhysicalMaterial *NewPhysMaterial) override
virtual void SetPredictedLODLevel (int32 InPredictedLODLevel) override
virtual void SetRefPoseOverride (const TArray< FTransform > &NewRefPoseTransforms) override
void SetRootBodyIndex (int32 InBodyIndex)
Set Root Body Index.
virtual void SetSimulatePhysics (bool bEnabled) override
virtual void SetSkeletalMesh (class USkeletalMesh *NewMesh, bool bReinitPose=true) override
virtual void SetSkinnedAssetAndUpdate (class USkinnedAsset *InSkinnedAsset, bool bReinitPose=true) override
Set the new asset to render and update this component (this function is identical to SetSkeletalMesh).
bool ShouldEvaluatePostProcessAnimBP () const
bool ShouldEvaluatePostProcessInstance () const
bool ShouldOnlyTickMontages (const float DeltaTime) const
If VisibilityBasedAnimTickOption == EVisibilityBasedAnimTickOption::OnlyTickMontagesWhenNotRendered Should we tick Montages only?
bool ShouldOnlyTickMontagesAndRefreshBones (const float DeltaTime) const
bool ShouldPostUpdatePostProcessInstance () const
bool ShouldTickAnimation () const
virtual bool ShouldTickPose () const override
bool ShouldUpdatePostProcessInstance () const
virtual bool ShouldUpdateTransform (bool bLODHasChanged) const override
virtual void SkelMeshCompOnParticleSystemFinished (class UParticleSystemComponent *PSC)
We detach the Component once we are done playing it.
virtual bool SweepComponent (FHitResult &OutHit, const FVector Start, const FVector End, const FQuat &ShapRotation, const FCollisionShape &CollisionShape, bool bTraceComplex=false) override
Trace a shape against just this component.
void TermArticulated ()
Turn off all physics and remove the instance.
void TermCollisionRelationships ()
void TickAnimation (float DeltaTime, bool bNeedsValidRootMotion)
Tick Animation system.
void TickAnimInstances (float DeltaTime, bool bNeedsValidRootMotion)
Tick all of our anim instances (linked instances, main instance and post process)
void TickClothing (float DeltaTime, FTickFunction &ThisTickFunction)
Tick Clothing Animation , basically this is called inside TickComponent.
virtual void TickComponent (float DeltaTime, enum ELevelTick TickType, FActorComponentTickFunction *ThisTickFunction) override
virtual void TickPose (float DeltaTime, bool bNeedsValidRootMotion) override
UE_DEPRECATED (4.18, "This function is deprecated. Please use GetAllowedAnimCurveEvaluate instead. Note that the meaning is reversed.") UFUNCTION() bool GetDisableAnimCurves() const
UE_DEPRECATED (4.18, "This function is deprecated. Please use SetAllowAnimCurveEvaluation instead. Note that the meaning is reversed.") UFUNCTION() 1 void SetDisableAnimCurves(bool bInDisableAnimCurves)
UE_DEPRECATED (4.23, "Direct access to this property is deprecated, please use GetBoneSpaceTransforms instead. We will move to private in the future.") TArray< FTransform > BoneSpaceTransforms
Temporary array of local-space (relative to parent bone) rotation/translation for each bone.
UE_DEPRECATED (4.23, "This function is deprecated. Please use GetLinkedAnimGraphInstanceByTag") UAnimInstance *GetSubInstanceByName(FName InTag) const
UE_DEPRECATED (4.23, "This function is deprecated. Please use SetAnimInstanceClass instead. ") 1 virtual void K2_SetAnimInstanceClass(class UClass *NewClass)
UE_DEPRECATED (4.24, "Function renamed, please use GetLinkedAnimGraphInstancesByTag") void GetSubInstancesByTag(FName InTag
UE_DEPRECATED (4.24, "Function renamed, please use GetLinkedAnimLayerInstanceByClass") UAnimInstance *GetLayerSubInstanceByClass(TSubclassOf< UAnimInstance > InClass) const
UE_DEPRECATED (4.24, "Function renamed, please use GetLinkedLayerInstanceByGroup") UAnimInstance *GetLayerSubInstanceByGroup(FName InGroup) const
UE_DEPRECATED (4.24, "Function renamed, please use LinkAnimClassLayers") void SetLayerOverlay(TSubclassOf< UAnimInstance > InClass)
UE_DEPRECATED (4.24, "Function renamed, please use LinkAnimGraphByTag") void SetSubInstanceClassByTag(FName InTag
UE_DEPRECATED (4.24, "Function renamed, please use UnlinkAnimClassLayers") void ClearLayerOverlay(TSubclassOf< UAnimInstance > InClass)
UE_DEPRECATED (4.24, "This function is deprecated. Please use GetLinkedAnimGraphInstanceByTag") UAnimInstance *GetSubInstanceByTag(FName InTag) const
UE_DEPRECATED (4.26, "Please use PerformAnimationEvaluation with different signature") 1 void PerformAnimationEvaluation(const USkeletalMesh *InSkeletalMesh
UE_DEPRECATED (4.26, "Public access to this function is deprecated. Please use the mechanism provided in USkeletalMeshComponent::EndPhysicsTickComponent") void BlendInPhysics(FTickFunction &ThisTickFunction)
Take the results of the physics and blend them with the animation state (based on the PhysicsWeight parameter), and update the SpaceBases array.
UE_DEPRECATED (4.26, "This function is deprecated and should not be called directly. Please use the mechanism provided in USkeletalMeshComponent::EndPhysicsTickComponent") void BlendPhysicsBones(TArray< FBoneIndexType > &Bones)
Blend of Physics Bones with PhysicsWeight and Animated Bones with (1-PhysicsWeight)
PRAGMA_ENABLE_DEPRECATION_WARNINGS UE_DEPRECATED (5.0, "Tags are unique so this funciton is no longer supported. Please use GetLinkedAnimGraphInstanceByTag instead") UFUNCTION()) 1 void GetLinkedAnimGraphInstancesByTag(FName InTag
Returns all tagged linked instance nodes that match the tag.
UE_DEPRECATED (5.1, "This method has been deprecated. Please use BindClothToLeaderPoseComponent instead.") void BindClothToMasterPoseComponent()
UE_DEPRECATED (5.1, "This method has been deprecated. Please use SetSkeletalMesh(NewMesh, false) instead.") 1 void SetSkeletalMeshWithoutResettingAnimation(class USkeletalMesh *NewMesh)
UE_DEPRECATED (5.1, "This method has been deprecated. Please use UnbindClothFromLeaderPoseComponent instead.") void UnbindClothFromMasterPoseComponent(bool bRestoreSimulationSpace
UE_DEPRECATED (5.1, "This method has been deprecated. Please use UpdateFollowerComponent instead.") virtual void UpdateSlaveComponent() override
UE_DEPRECATED (5.1, "This method has been deprecated. Please, use IsClothBoundToLeaderComponent instead.") bool IsClothBoundToMasterComponent() const
UE_DEPRECATED (5.2, "Use GetUpdateClothSimulationData_AnyThread instead.") 1 void GetUpdateClothSimulationData(TMap< int32
Store cloth simulation data into OutClothSimData.
UE_DEPRECATED (5.3, "Please use GetCurveFilterSettings") const TArray< FName > &GetDisallowedAnimCurvesEvaluation() const
UE_DEPRECATED (5.3, "This method has been deprecated. Please use UMirrorDataTable for mirroring support.") static 1 void GetMirroringRequiredBones(const USkeletalMesh *SkeletalMesh
UE_DEPRECATED (5.5, "Please use EvaluatePostProcessMeshInstance with different signature") 1 void EvaluatePostProcessMeshInstance(TArray< FTransform > &OutBoneSpaceTransforms
UE_DEPRECATED (5.5, "Please use PerformAnimationEvaluation with different signature") 1 void PerformAnimationProcessing(const USkeletalMesh *InSkeletalMesh
UE_DEPRECATED (5.5, "This function has been renamed RemoveClothCollisionSources") void RemoveClothCollisionSource(USkeletalMeshComponent *InSourceComponent)
Remove a cloth collision source defined by a component.
UE_DEPRECATED (5.5, "This function is deprecated. Please use 'SetAnimInstanceClass' instead. ") 1 virtual void SetAnimClass(class UClass *NewClass)
Set the anim instance class.
UE_DEPRECATED (5.6, "Direct access to this property is deprecated, please use GetAnimCurves or GetCurveValue instead. We will move to private in the future.") FBlendedHeapCurve AnimCurves
UE_DEPRECATED (5.6, "These should not be used as they rely on a global delegate, ANY change in LOD from ANY skeletal mesh component triggers the callback") 1 FDelegateHandle RegisterOnLODRequiredBonesUpdate(const FOnLODRequiredBonesUpdate &Delegate)
Register/Unregister for OnLODRequiredBonesUpdate callback.
UE_DEPRECATED (5.6, "These should not be used as they rely on a global delegate, ANY change in LOD from ANY skeletal mesh component triggers the callback") 1 void UnregisterOnLODRequiredBonesUpdate(const FDelegateHandle &DelegateHandle)
UFUNCTION () 1 bool GetCurveValue(FName CurveName
Get curve value.
UFUNCTION () 1 bool GetDisablePostProcessBlueprint() const
Gets whether the post process blueprint is currently disabled for this component.
UFUNCTION () 1 bool GetFloatAttribute(const FName &BoneName
Get float type attribute value.
UFUNCTION () 1 bool GetFloatAttribute_Ref(const FName &BoneName
Get float type attribute value.
UFUNCTION () 1 bool GetIntegerAttribute(const FName &BoneName
Get integer type attribute value.
UFUNCTION () 1 bool GetIntegerAttribute_Ref(const FName &BoneName
Get integer type attribute value.
UFUNCTION () 1 bool GetStringAttribute(const FName &BoneName
Get string type attribute value.
UFUNCTION () 1 bool GetStringAttribute_Ref(const FName &BoneName
Get string type attribute value.
UFUNCTION () 1 bool GetTransformAttribute(const FName &BoneName
Get FTransform type attribute value.
UFUNCTION () 1 bool GetTransformAttribute_Ref(const FName &BoneName
Get FTransform type attribute value.
UFUNCTION () 1 bool IsBodyGravityEnabled(FName BoneName)
Checks whether or not gravity is enabled on the given bone.
UFUNCTION () 1 bool IsClothingSimulationSuspended() const
Gets whether or not the clothing simulation is currently suspended.
UFUNCTION () 1 class UClass *GetAnimClass()
Get the anim instance class via getter callable by sequencer.
UFUNCTION () 1 float GetBoneMass(FName BoneName
Returns the mass (in kg) of the given bone.
UFUNCTION () 1 float GetClothMaxDistanceScale() const
Get/Set the max distance scale of clothing mesh vertices.
UFUNCTION () 1 float GetMorphTarget(FName MorphTargetName) const
Get Morph target with given name.
UFUNCTION () 1 float GetTeleportDistanceThreshold() const
Gets the teleportation distance threshold.
UFUNCTION () 1 float GetTeleportRotationThreshold() const
Gets the teleportation rotation threshold.
UFUNCTION () 1 FName FindConstraintBoneName(int32 ConstraintIndex)
Find Constraint Name from index.
UFUNCTION () 1 FVector GetBoneLinearVelocity(const FName &InBoneName)
UFUNCTION () 1 FVector GetSkeletalCenterOfMass() const
Returns the center of mass of the skeletal mesh, instead of the root body's location.
UFUNCTION () 1 TSoftObjectPtr< UObject > GetDefaultAnimatingRig() const
UFUNCTION () 1 TSoftObjectPtr< UObject > GetDefaultAnimatingRigOverride() const
UFUNCTION () 1 UClothingSimulationInteractor *GetClothingSimulationInteractor() const
Get the current interactor for a clothing simulation, if the current simulation supports runtime interaction.
UFUNCTION () 1 USkeletalMesh *GetSkeletalMeshAsset() const
Get the SkeletalMesh rendered for this mesh.
UFUNCTION () 1 virtual void AddForceToAllBodiesBelow(FVector Force
Add a force to all rigid bodies below.
UFUNCTION () 1 virtual void AddImpulseToAllBodiesBelow(FVector Impulse
Add impulse to all single rigid bodies below.
UFUNCTION () 1 virtual void SetBodyNotifyRigidBodyCollision(bool bNewNotifyRigidBodyCollision
Changes the value of bNotifyRigidBodyCollision for a given body.
UFUNCTION () 1 virtual void SetNotifyRigidBodyCollisionBelow(bool bNewNotifyRigidBodyCollision
Changes the value of bNotifyRigidBodyCollision on all bodies below a given bone.
UFUNCTION () 1 void AccumulateAllBodiesBelowPhysicsBlendWeight(const FName &InBoneName
Accumulate AddPhysicsBlendWeight to physics blendweight for all of the bones below passed in bone to be simulated.
UFUNCTION () 1 void AddClothCollisionSource(USkeletalMeshComponent *InSourceComponent
Add a collision source for the cloth on this component.
UFUNCTION () 1 void AllowAnimCurveEvaluation(FName NameOfCurve
UFUNCTION () 1 void ClearMorphTargets()
Clear all Morph Target that are set to this mesh.
UFUNCTION () 1 void ForceClothNextUpdateTeleport()
Used to indicate we should force 'teleport' during the next call to UpdateClothState, This will transform positions and velocities and thus keep the simulation state, just translate it to a new pose.
UFUNCTION () 1 void ForceClothNextUpdateTeleportAndReset()
Used to indicate we should force 'teleport and reset' during the next call to UpdateClothState.
UFUNCTION () 1 void GetCurrentJointAngles(FName InBoneName
Gets the current Angular state for a named bone constraint.
UFUNCTION () 1 void RecreateClothingActors()
Destroys and recreates the clothing actors in the current simulation.
UFUNCTION () 1 void RemoveClothCollisionSource(USkeletalMeshComponent *InSourceComponent
Remove a cloth collision source defined by both a component and a physics asset.
UFUNCTION () 1 void RemoveClothCollisionSources(USkeletalMeshComponent *InSourceComponent)
Remove a cloth collision source defined by a component.
UFUNCTION () 1 void ResetAllBodiesSimulatePhysics()
Allows you to reset bodies Simulate state based on where bUsePhysics is set to true in the BodySetup.
UFUNCTION () 1 void ResetAllowedAnimCurveEvaluation()
By reset, it will allow all the curves to be evaluated.
UFUNCTION () 1 void ResetClothCollisionSources()
Remove all cloth collision sources.
UFUNCTION () 1 void ResetClothTeleportMode()
Reset the teleport mode of a next update to 'Continuous'.
UFUNCTION () 1 void SetAllBodiesBelowLinearVelocity(const FName &InBoneName
set the linear velocity of the child bodies to match that of the given parent bone
UFUNCTION () 1 void SetAllBodiesBelowPhysicsBlendWeight(const FName &InBoneName
Set all of the bones below passed in bone to be simulated.
UFUNCTION () 1 void SetAllBodiesBelowPhysicsDisabled(const FName &InBoneName
[WARNING: Chaos Only] Set all of the bones below passed in bone to be disabled or not for the associated physics solver Bodies will not be colliding or be part of the physics simulation.
UFUNCTION () 1 void SetAllBodiesBelowSimulatePhysics(const FName &InBoneName
Set all of the bones below passed in bone to be simulated.
UFUNCTION () 1 void SetAllBodiesPhysicsBlendWeight(float PhysicsBlendWeight
UFUNCTION () 1 void SetAllBodiesSimulatePhysics(bool bNewSimulate)
Set bSimulatePhysics to true for all bone bodies.
UFUNCTION () 1 void SetAllMotorsAngularDriveParams(float InSpring
Set Angular Drive motors params for all constraint instances.
UFUNCTION () 1 void SetAllMotorsAngularPositionDrive(bool bEnableSwingDrive
Enable or Disable AngularPositionDrive.
UFUNCTION () 1 void SetAllMotorsAngularVelocityDrive(bool bEnableSwingDrive
Enable or Disable AngularVelocityDrive.
UFUNCTION () 1 void SetAllowAnimCurveEvaluation(bool bInAllow)
UFUNCTION () 1 void SetAllowClothActors(bool bInAllow)
Sets whether cloth assets should be created/simulated in this component.
UFUNCTION () 1 void SetAllowedAnimCurvesEvaluation(const TArray< FName > &List
resets, and then only allow the following list to be allowed/disallowed
UFUNCTION () 1 void SetAngularLimits(FName InBoneName
Sets the Angular Motion Ranges for a named constraint.
UFUNCTION () 1 void SetBodySimulatePhysics(const FName &InBoneName
Set a single bone to be simulated (or not)
UFUNCTION () 1 void SetClothMaxDistanceScale(float Scale)
UFUNCTION () 1 void SetConstraintProfile(FName JointName
Sets the constraint profile properties (limits, motors, etc...) to match the constraint profile as defined in the physics asset.
UFUNCTION () 1 void SetConstraintProfileForAll(FName ProfileName
Sets the constraint profile properties (limits, motors, etc...) to match the constraint profile as defined in the physics asset for all constraints.
UFUNCTION () 1 void SetDefaultAnimatingRigOverride(TSoftObjectPtr< UObject > InAnimatingRig)
UFUNCTION () 1 void SetDisablePostProcessBlueprint(bool bInDisablePostProcess)
Sets whether the post process blueprint is currently running for this component.
UFUNCTION () 1 void SetEnableBodyGravity(bool bEnableGravity
Enables or disables gravity for the given bone.
UFUNCTION () 1 void SetEnableGravityOnAllBodiesBelow(bool bEnableGravity
Enables or disables gravity to all bodies below the given bone.
UFUNCTION () 1 void SetEnablePhysicsBlending(bool bNewBlendPhysics)
Disable physics blending of bones.
UFUNCTION () 1 void SetOverridePostProcessAnimBP(TSubclassOf< UAnimInstance > InPostProcessAnimBlueprint
Set the post-processing AnimBP to be used for this skeletal mesh component.
UFUNCTION () 1 void SetPhysicsBlendWeight(float PhysicsBlendWeight)
This is global set up for setting physics blend weight This does multiple things automatically If PhysicsBlendWeight == 1.f, it will enable Simulation, and if PhysicsBlendWeight == 0.f, it will disable Simulation.
UFUNCTION () 1 void SetTeleportDistanceThreshold(float Threshold)
Sets the teleportation distance threshold.
UFUNCTION () 1 void SetTeleportRotationThreshold(float Threshold)
Sets the teleportation rotation threshold.
UFUNCTION () 1 void SnapshotPose(UPARAM(ref) FPoseSnapshot &Snapshot)
Takes a snapshot of this skeletal mesh component's pose and saves it to the specified snapshot.
UFUNCTION () 1 void TermBodiesBelow(FName ParentBoneName)
Terminate physics on all bodies below the named bone, effectively disabling collision forever.
UFUNCTION () 1 void ToggleDisablePostProcessBlueprint()
Toggles whether the post process blueprint will run for this component.
UFUNCTION () bool GetAllowClothActors() const
UFUNCTION () bool GetAllowedAnimCurveEvaluate() const
UFUNCTION () bool GetAllowRigidBodyAnimNode() const
UFUNCTION () void SetSkeletalMeshAsset(USkeletalMesh *NewMesh)
Set the SkeletalMesh rendered for this mesh.
UFUNCTION ()) 1 bool HasValidAnimationInstance() const
Returns whether there are any valid instances to run, currently this means whether we have have an animation instance or a post process instance available to process.
UFUNCTION ()) 1 bool IsPlaying() const
UFUNCTION ()) 1 bool K2_GetClosestPointOnPhysicsAsset(const FVector &WorldPosition
Given a world position, find the closest point on the physics asset.
UFUNCTION ()) 1 class UAnimInstance *GetAnimInstance() const
Returns the animation instance that is driving the class (if available).
UFUNCTION ()) 1 FConstraintInstanceAccessor GetConstraintByName(FName ConstraintName
Gets a constraint by its name.
UFUNCTION ()) 1 float GetPlayRate() const
UFUNCTION ()) 1 float GetPosition() const
UFUNCTION ()) 1 UAnimInstance *GetLinkedAnimGraphInstanceByTag(FName InTag) const
Returns the a tagged linked instance node.
UFUNCTION ()) 1 UAnimInstance *GetLinkedAnimLayerInstanceByClass(TSubclassOf< UAnimInstance > InClass) const
Gets the first layer linked instance corresponding to the specified class.
UFUNCTION ()) 1 UAnimInstance *GetLinkedAnimLayerInstanceByGroup(FName InGroup) const
Gets the layer linked instance corresponding to the specified group.
UFUNCTION ()) 1 UAnimInstance *GetPostProcessInstance() const
Returns the active post process instance is one is available.
UFUNCTION ()) 1 virtual void SetAnimInstanceClass(class UClass *NewClass)
Set the anim instance class.
UFUNCTION ()) 1 void BindClothToLeaderPoseComponent()
If this component has a valid LeaderPoseComponent then this function makes cloth items on the follower component take the transforms of the cloth items on the leader component instead of simulating separately.
UFUNCTION ()) 1 void BreakConstraint(FVector Impulse
Break a constraint off a Gore mesh.
UFUNCTION ()) 1 void GetConstraints(bool bIncludesTerminated
Gets all the constraints.
UFUNCTION ()) 1 void GetConstraintsFromBody(FName BodyName
Gets all the constraints attached to a body.
UFUNCTION ()) 1 void LinkAnimClassLayers(TSubclassOf< UAnimInstance > InClass)
Runs through all layer nodes, attempting to find layer nodes that are implemented by the specified class, then sets up a linked instance of the class for each.
UFUNCTION ()) 1 void LinkAnimGraphByTag(FName InTag
Runs through all nodes, attempting to find linked instance by name/tag, then sets the class of each node if the tag matches.
UFUNCTION ()) 1 void OverrideAnimationData(UAnimationAsset *InAnimToPlay
This overrides current AnimationData parameter in the SkeletalMeshComponent.
UFUNCTION ()) 1 void Play(bool bLooping)
UFUNCTION()) 1 void SetAnimationMode(EAnimationMode UFUNCTION()) 1 EAnimationMode UFUNCTION ()) 1 void PlayAnimation(class UAnimationAsset *NewAnimToPlay
Below are the interface to control animation when animation mode, not blueprint mode.
UFUNCTION ()) 1 void ResetAnimInstanceDynamics(ETeleportType InTeleportType
Informs any active anim instances (main instance, linked instances, post instance) that a dynamics reset is required for example if a teleport occurs.
UFUNCTION ()) 1 void ResumeClothingSimulation()
Resumes a previously suspended clothing simulation, teleporting the clothing on the next tick.
UFUNCTION ()) 1 void SetAnimation(class UAnimationAsset *NewAnimToPlay)
UFUNCTION ()) 1 void SetEnableAnimation(bool bNewEnableAnimation)
Whether the built-in animation of this component should run when the component ticks.
UFUNCTION ()) 1 void SetMorphTarget(FName MorphTargetName
Set Morph Target with Name and Value(0-1)
UFUNCTION ()) 1 void SetPlayRate(float Rate)
UFUNCTION ()) 1 void SetPosition(float InPos
UFUNCTION ()) 1 void SetUpdateAnimationInEditor(const bool NewUpdateState)
Sets whether or not to force tick component in order to update animation and refresh transform for this component This is supported only in the editor.
UFUNCTION ()) 1 void SetUpdateClothInEditor(const bool NewUpdateState)
Sets whether or not to animate cloth in the editor.
UFUNCTION ()) 1 void Stop()
UFUNCTION ()) 1 void SuspendClothingSimulation()
Stops simulating clothing, but does not show clothing ref pose.
UFUNCTION ()) 1 void UnbindClothFromLeaderPoseComponent(bool bRestoreSimulationSpace
If this component has a valid LeaderPoseComponent and has previously had its cloth bound to the MCP, this function will unbind the cloth and resume simulation.
UFUNCTION ()) 1 void UnlinkAnimClassLayers(TSubclassOf< UAnimInstance > InClass)
Runs through all layer nodes, attempting to find layer nodes that are currently running the specified class, then resets each to its default value.
virtual void UnHideBone (int32 BoneIndex) override
virtual void UnregisterOnBoneTransformsFinalizedDelegate (const FDelegateHandle &DelegateHandle) override
void UnregisterOnPhysicsCreatedDelegate (const FDelegateHandle &DelegateHandle)
void UnregisterOnSkeletalMeshPropertyChanged (FDelegateHandle Handle)
void UnregisterOnSkeletalMeshUnregistered (FDelegateHandle Handle)
void UnregisterOnTeleportDelegate (const FDelegateHandle &DelegateHandle)
const FName UPARAM (ref) float &OutValue
const FName UPARAM (ref) FString &OutValue
const FName UPARAM (ref) FTransform &OutValue
const FName UPARAM (ref) int32 &OutValue
void UpdateBoneBodyMapping ()
Update the bone mapping on each body instance.
void UpdateClothCollision ()
Updates cloth collision inside the cloth asset (from a physics asset).
void UpdateClothStateAndSimulate (float DeltaTime, FTickFunction &ThisTickFunction)
Update the clothing simulation state and trigger the simulation task.
void UpdateClothTransform ()
Set the cloth transform update to trigger with no teleport option.
void UpdateClothTransform (ETeleportType TeleportType)
Updates cloth collision outside the cloth asset (environment collision, child collision, etc...) Should be called when scene changes or world position changes.
virtual void UpdateCollisionProfile () override
virtual void UpdateFollowerComponent () override
void UpdateHasValidBodies ()
Update bHasValidBodies flag.
void UpdateKinematicBonesToAnim (const TArray< FTransform > &InComponentSpaceTransforms, ETeleportType Teleport, bool bNeedsSkinning, EAllowKinematicDeferral DeferralAllowed=EAllowKinematicDeferral::AllowDeferral)
Iterate over each physics body in the physics for this mesh, and for each 'kinematic' (ie fixed or default if owner isn't simulating) one, update its transform based on the animated transform.
virtual bool UpdateLODStatus () override
void UpdateMeshForBrokenConstraints ()
Look up all bodies for broken constraints.
virtual bool UpdateOverlapsImpl (const TOverlapArrayView *PendingOverlaps=NULL, bool bDoNotifies=true, const TOverlapArrayView *OverlapsAtEndLocation=NULL) override
virtual void UpdatePhysicsToRBChannels () override
void UpdatePoseWatches ()
void UpdateRBJointMotors ()
Iterate over each joint in the physics for this mesh, setting its AngularPositionTarget based on the animation information.
void UpdateRigidBodyScaling (ETeleportType TeleportType)
Update rigid body scaling when the actor is set with a new uniform scale.
virtual void UpdateVisualizeLODString (FString &DebugString) override
UPROPERTY () bool bWaitForParallelClothTask
Whether we should stall the Cloth tick task until the cloth simulation is complete.
UPROPERTY() TEnumAsByte< EKinematicBonesUpdateToPhysics UPROPERTY() TEnumAsByte< EPhysicsTransformUpdateMode UPROPERTY () EClothingTeleportMode ClothTeleportMode
If we are running physics, should we update non-simulated bones based on the animation bone positions.
UPROPERTY () FConstraintBrokenSignature OnConstraintBroken
Notification when constraint is broken.
UPROPERTY () float ClothBlendWeight
weight to blend between simulated results and key-framed positions if weight is 1.0, shows only cloth simulation results and 0.0 will show only skinned results
UPROPERTY () FOnAnimInitialized OnAnimInitialized
UPROPERTY () FPlasticDeformationEventSignature OnPlasticDeformation
Notification when constraint plasticity drive target changes.
UPROPERTY () FVector LineCheckBoundsScale
If bEnableLineCheckWithBounds is true, scale the bounds by this value before doing line check.
UPROPERTY () FVector RootBoneTranslation
Offset of the root bone from the reference pose.
UPROPERTY () TObjectPtr< class UBodySetup > BodySetup
Used for per poly collision.
UPROPERTY () TObjectPtr< UAnimInstance > AnimScriptInstance
The active animation graph program instance.
UPROPERTY () TObjectPtr< UAnimInstance > PostProcessAnimInstance
An instance created from the PostPhysicsBlueprint property of the skeletal mesh we're using, Runs after (and receives pose from) the main anim instance.
UPROPERTY () TSubclassOf< class UClothingSimulationFactory > ClothingSimulationFactory
Class of the object responsible for.
UPROPERTY () TSubclassOf< UAnimInstance > OverridePostProcessAnimBP
Post-processing AnimBP to use for the given skeletal mesh component, overriding the one set in the skeletal mesh asset.
UPROPERTY () uint16 CachedAnimCurveUidVersion
Cache AnimCurveUidVersion from Skeleton and this will be used to identify if it needs to be updated.
UPROPERTY ()) class TSubclassOf< UAnimInstance > AnimClass
UPROPERTY ()) float ClothGeometryScale
This scale is applied to all cloth geometry (e.g., cloth meshes and collisions) in order to simulate in a different scale space than world.This scale is not applied to distance-based simulation parameters such as MaxDistance.
UPROPERTY ()) float ClothMaxDistanceScale
UPROPERTY() uint8 bCollideWithEnvironment UPROPERTY() uint8 bCollideWithAttachedChildren UPROPERTY() uint8 bForceCollisionUpdate UPROPERTY ()) float ClothVelocityScale
can't collide with part of environment if total collision volumes exceed 16 capsules or 32 planes per convex
UPROPERTY ()) float GlobalAnimRateScale
Used to scale speed of all animations on this skeletal mesh.
UPROPERTY ()) struct FSingleAnimationPlayData AnimationData
void ValidateAnimation ()
Validates the animation asset or blueprint, making sure it is compatible with the current skeleton.
void WaitForExistingParallelClothSimulation_GameThread ()
Stalls on any currently running clothing simulations.
virtual void WakeAllRigidBodies () override
Static Public Member Functions
static void ComputeSkinnedPositions (USkeletalMeshComponent *Component, TArray< FVector3f > &OutPositions, TArray< FMatrix44f > &CachedRefToLocals, const FSkeletalMeshLODRenderData &Model, const FSkinWeightVertexBuffer &SkinWeightBuffer)
static void ComputeSkinnedTangentBasis (USkeletalMeshComponent *Component, TArray< FVector3f > &OutTangenXYZ, TArray< FMatrix44f > &CachedRefToLocals, const FSkeletalMeshLODRenderData &Model, const FSkinWeightVertexBuffer &SkinWeightBuffer)
static void ExcludeHiddenBones (const USkeletalMeshComponent *SkeletalMeshComponent, const USkeletalMesh *SkeletalMesh, TArray< FBoneIndexType > &OutRequiredBones)
static const FName & GetAnimationModePropertyNameChecked ()
Whether to use Animation Blueprint or play Single Animation Asset.
static void GetRequiredVirtualBones (const USkeletalMesh *SkeletalMesh, TArray< FBoneIndexType > &OutRequiredBones)
static void GetShadowShapeRequiredBones (const USkeletalMeshComponent *SkeletalMeshComponent, TArray< FBoneIndexType > &OutRequiredBones)
static void GetSkinnedTangentBasis (USkeletalMeshComponent *Component, int32 VertexIndex, const FSkeletalMeshLODRenderData &Model, const FSkinWeightVertexBuffer &SkinWeightBuffer, TArray< FMatrix44f > &CachedRefToLocals, FVector3f &OutTangentX, FVector3f &OutTangentY, FVector3f &OutTangentZ)
static FVector3f GetSkinnedVertexPosition (USkeletalMeshComponent *Component, int32 VertexIndex, const FSkeletalMeshLODRenderData &Model, const FSkinWeightVertexBuffer &SkinWeightBuffer)
static FVector3f GetSkinnedVertexPosition (USkeletalMeshComponent *Component, int32 VertexIndex, const FSkeletalMeshLODRenderData &Model, const FSkinWeightVertexBuffer &SkinWeightBuffer, TArray< FMatrix44f > &CachedRefToLocals)
Data Fields
float AddPhysicsBlendWeight
FPhysicsAggregateHandle Aggregate
Physics-engine representation of aggregate which contains a physics asset instance with more than numbers of bodies.
const FName & AttributeName
FName bool bAccelChange = false
bool bAllow
bool bool bChildConstraints
FName bool bDefaultIfNotFound = false)
bool bDefaultIfNotFound = false)
bool bDisabled
bool bEnableTwistDrive
bool bFireNotifies = true)
FName bool bIncludeSelf = true)
FName bool bool bIncludeSelf = true)
bool bool bIncludeSelf = true)
const FVector bool bIncludeSelf = true)
float bool bool bIncludeSelf = true)
bool bIncludesTerminated
bool bool bool bIncludesTerminated
UAnimInstance bool bInDoEvaluation
bool bIsLooping = true
bool bool bIsPlaying = true
UPROPERTY() uint8 bUpdateOverlapsOnAnimationFinalize uint8 bLocalSpaceKinematics:1
Controls whether blending in physics bones will refresh overlaps on this component, defaults to true but can be disabled in cases where we know anim->physics blending doesn't meaningfully change overlaps.
UFUNCTION()) 1 void SetAnimationMode(EAnimationMode UFUNCTION()) 1 EAnimationMode bool bLooping
bool bNewSimulate
TArray< struct FBodyInstance * > Bodies
Array of FBodyInstance objects, storing per-instance state about about each body.
FName BoneName = NAME_None)
FVector FVector FName & BoneName
bool bParentConstraints
UPROPERTY() uint8 bResetAfterTeleport uint8 bPrevDisableClothSimulation: 1
reset the clothing after moving the clothing position (called teleport)
float bool bRemoveZeroWeight =true)
bool bScaleMass = true) const
bool bSimulate
uint8 bSimulationUpdatesChildTransforms:1
Controls whether or not this component will evaluate its post process instance.
bool bSkipCustomPhysicsType = false)
float bool bSkipCustomPhysicsType = false
bool bool bSkipCustomPhysicsType = false)
float float bool bSkipCustomPhysicsType = false)
FName bool bVelChange = false
FVector & ClosestWorldPosition
FSkeletalMeshComponentClothTickFunction ClothTickFunction
float float &Value const
TArray< UAnimInstance * > &OutSubInstances const
PRAGMA_ENABLE_DEPRECATION_WARNINGS TArray< UAnimInstance * > &OutLinkedInstances const
FVector FVector FName float &Distance const
FCompactPose FBlendedHeapCurve const USkeletalMesh FVector UE::Anim::FHeapAttributeContainer &OutAttributes const
TArray< struct FConstraintInstance * > Constraints
Array of FConstraintInstance structs, storing per-instance state about each constraint.
const FName float DefaultValue
const FName FTransform DefaultValue
const FName int32 DefaultValue
const FName FString DefaultValue
float DefaultValue
UPROPERTY() uint8 bHasValidBodies UPROPERTY() uint8 bBlendPhysics UPROPERTY() uint8 bEnablePhysicsOnDedicatedServer UPROPERTY() uint8 bUpdateMeshWhenKinematic UPROPERTY() uint8 bUpdateJointsFromAnimation UPROPERTY() uint8 bAllowClothActors UPROPERTY() uint8 bDisableClothSimulation int32 DeferredKinematicUpdateIndex
If true, there is at least one body in the current PhysicsAsset with a valid bone in the current SkeletalMesh.
TArray< FBoneIndexType > FillComponentSpaceTransformsRequiredBones
Temporary array of bone indices required to populate component space transforms.
FVector HitLocation
UAnimInstance * InAnimInstance
FVector FName InBoneName
TSubclassOf< UAnimInstance > InClass { LinkAnimGraphByTag(InTag, InClass)
float InDamping
float float InForceLimit
FCompactPose & InOutPose
FCompactPose FBlendedHeapCurve const USkeletalMesh * InSkeletalMesh
UPhysicsAsset * InSourcePhysicsAsset
const FVector & LinearVelocity
const FName ECustomBoneAttributeLookup LookupType = ECustomBoneAttributeLookup::BoneOnly)
const FName float float ECustomBoneAttributeLookup LookupType = ECustomBoneAttributeLookup::BoneOnly)
const FName FTransform FTransform ECustomBoneAttributeLookup LookupType = ECustomBoneAttributeLookup::BoneOnly)
const FName int32 int32 ECustomBoneAttributeLookup LookupType = ECustomBoneAttributeLookup::BoneOnly)
const FName FString FString ECustomBoneAttributeLookup LookupType = ECustomBoneAttributeLookup::BoneOnly)
FVector FVector & Normal
UAnimInstance bool TArray< FTransform > TArray< FTransform > FVector FBlendedHeapCurve UE::Anim::FMeshAttributeContainer & OutAttributes
UAnimInstance TArray< FTransform > TArray< FTransform > & OutBoneSpaceTransforms
UAnimInstance bool TArray< FTransform > TArray< FTransform > & OutBoneSpaceTransforms
FClothSimulData & OutClothSimData
TArray< FConstraintInstanceAccessor > & OutConstraints
bool bool bool TArray< FConstraintInstanceAccessor > & OutConstraints
UAnimInstance TArray< FTransform > TArray< FTransform > FVector FBlendedHeapCurve & OutCurve
UAnimInstance bool TArray< FTransform > TArray< FTransform > FVector FBlendedHeapCurve & OutCurve
FCompactPose FBlendedHeapCurve & OutCurve
TArray< FBoneIndexType > & OutRequiredBones
UAnimInstance TArray< FTransform > TArray< FTransform > FVector & OutRootBoneTranslation
UAnimInstance bool TArray< FTransform > TArray< FTransform > FVector & OutRootBoneTranslation
FCompactPose FBlendedHeapCurve const USkeletalMesh FVector & OutRootBoneTranslation
UAnimInstance TArray< FTransform > & OutSpaceBases
UAnimInstance bool TArray< FTransform > & OutSpaceBases
const FName float float & OutValue
const FName FTransform FTransform & OutValue
const FName int32 int32 & OutValue
const FName FString FString & OutValue
FClothSimulData USkeletalMeshComponent * OverrideLocalRootComponent = nullptr)
TArray< FPendingRadialForces > PendingRadialForces
Array of physical interactions for the frame.
float PhysicsBlendWeight
bool bool float float PlayRate = 1.f)
TArray< FAnimNodePoseWatch > PoseWatches
bool bool float Position = 0.f
FName ProfileName
int32 RagdollAggregateThreshold
Threshold for physics asset bodies above which we use an aggregate for broadphase collisions.
bool ReinitAnimInstances = true)
TArray< FBoneIndexType > RequiredBones
Temporary array of bone indices required this frame.
struct {
int32 BodyIndex
FTransform TransformToRoot
} RootBodyData
Index of the 'Root Body', or top body in the asset hierarchy.
float & Swing1Angle
float Swing1LimitAngle
float float float & Swing2Angle
float float float Swing2LimitAngle
float float & TwistAngle
float float TwistLimitAngle
float Value
Protected Member Functions
virtual bool ComponentOverlapComponentImpl (class UPrimitiveComponent *PrimComp, const FVector Pos, const FQuat &Quat, const FCollisionQueryParams &Params) override
virtual bool ComponentOverlapMultiImpl (TArray< struct FOverlapResult > &OutOverlaps, const class UWorld *InWorld, const FVector &Pos, const FQuat &Rot, ECollisionChannel TestChannel, const struct FComponentQueryParams &Params, const struct FCollisionObjectQueryParams &ObjectQueryParams=FCollisionObjectQueryParams::DefaultObjectQueryParam) const override
Test the collision of the supplied component at the supplied location/rotation, and determine the set of components that it overlaps.
FRootMotionMovementParams ConsumeRootMotion_Internal (float InAlpha)
Consume and return pending root motion from our internal anim instances (main, sub and post)
void CopyChildrenClothCollisionsToParent ()
copy children's cloth collisions to parent, where parent means this component
void CopyClothCollisionSources ()
copy cloth collision sources to this, where parent means components above it in the hierarchy
void CopyClothCollisionsToChildren ()
copy parent's cloth collisions to attached children, where parent means this component
virtual void DispatchParallelTickPose (FActorComponentTickFunction *TickFunction) override
void DoInstancePostEvaluation ()
void DoInstancePreEvaluation ()
template<typename DataType, typename CustomAttributeType>
bool FindAttributeChecked (const FName &BoneName, const FName &AttributeName, DataType DefaultValue, DataType &OutValue, ECustomBoneAttributeLookup LookupType)
Templated version to try and retrieve a typed bone attribute's value.
void FindClothCollisions (FClothCollisionData &OutCollisions)
find if this component has collisions for clothing and return the results calculated by bone transforms
virtual FTransform GetComponentTransformFromBodyInstance (FBodyInstance *UseBI) override
If PhysicsTransformUpdateMode is set to SimulationUpdatesComponentTransform, this returns the world-space transform of the body passed in (assumed to be the root body), after applying the TransformToRoot offset.
virtual bool MoveComponentImpl (const FVector &Delta, const FQuat &NewRotation, bool bSweep, FHitResult *OutHit=NULL, EMoveComponentFlags MoveFlags=MOVECOMP_NoFlags, ETeleportType Teleport=ETeleportType::None) override
bool NeedToSpawnAnimScriptInstance () const
bool NeedToSpawnPostPhysicsInstance (bool bForceReinit) const
virtual void OnCreatePhysicsState () override
virtual void OnDestroyPhysicsState () override
virtual void OnRegister () override
virtual void OnSyncComponentToRBPhysics ()
Notify called just before syncing physics update, called only if bNotifySyncComponentToRBPhysics flag is set.
virtual void OnUnregister () override
void ProcessClothCollisionWithEnvironment ()
virtual void RegisterComponentTickFunctions (bool bRegister) override
virtual void SendRenderDynamicData_Concurrent () override
virtual bool ShouldBlendPhysicsBones () const
virtual bool ShouldCreatePhysicsState () const override
virtual bool ShouldRunClothTick () const
Static Protected Member Functions
static void ExtractCollisionsForCloth (USkeletalMeshComponent *SourceComponent, UPhysicsAsset *PhysicsAsset, USkeletalMeshComponent *DestClothComponent, FClothCollisionData &OutCollisions, FClothCollisionSource &ClothCollisionSource)
Extract collisions for cloth from this component (given a component we want to apply the data to)
Protected Attributes
uint8 bClothingSimulationSuspended:1
Optimization.
uint8 bNotifySyncComponentToRBPhysics: 1
If true, OnSyncComponentToRBPhysics() notify will be called.
TMap< int32, FClothSimulData > CurrentSimulationData
Simulation data written back to the component after the simulation has taken place.
FSkeletalMeshComponentEndPhysicsTickFunction EndPhysicsTickFunction
Private Member Functions
virtual void AddFollowerPoseComponent (USkinnedMeshComponent *SkinnedMeshComponent) override
Override USkinnedMeshComponent.
bool AreRequiredCurvesUpToDate () const
void BlendInPhysicsInternal (FTickFunction &ThisTickFunction)
void CompleteParallelBlendPhysics ()
void DispatchParallelEvaluationTasks (FActorComponentTickFunction *TickFunction)
Queues up tasks for parallel update/evaluation, as well as the chained game thread completion task.
bool DoAnyPhysicsBodiesHaveWeight () const
void DoParallelEvaluationTasks_OnGameThread ()
Performs parallel eval/update work, but on the game thread.
void EndPhysicsTickComponent (FSkeletalMeshComponentEndPhysicsTickFunction &ThisTickFunction)
Update systems after physics sim is done.
void EvaluateAnimation (const USkeletalMesh *InSkeletalMesh, UAnimInstance *InAnimInstance, bool bInForceRefPose, FVector &OutRootBoneTranslation, FBlendedHeapCurve &OutCurve, FCompactPose &OutPose, UE::Anim::FHeapAttributeContainer &OutAttributes) const
Evaluate Anim System.
void FinalizeAnimationUpdate ()
void FinalizeAttributeEvaluationResults (const FBoneContainer &BoneContainer, const UE::Anim::FHeapAttributeContainer &FinalContainer, UE::Anim::FMeshAttributeContainer &OutContainer) const
void FinalizePoseEvaluationResult (const USkeletalMesh *InMesh, TArray< FTransform > &OutBoneSpaceTransforms, FVector &OutRootBoneTranslation, FCompactPose &InFinalPose) const
GENERATED_UCLASS_BODY () friend class FSkinnedMeshComponentRecreateRenderStateContext
UClothingSimulationFactory * GetClothingSimFactory () const
Gets the factory responsible for building the clothing simulation and simulation contexts.
UE::Anim::FMeshAttributeContainer & GetEditableCustomAttributes ()
PRAGMA_DISABLE_DEPRECATION_WARNINGS TArray< TObjectPtr< UAnimInstance > > & GetLinkedAnimInstances ()
void GetWindForCloth_GameThread (FVector &WindVector, float &WindAdaption) const
void HandleExistingParallelClothSimulation ()
Stalls on any currently running clothing simulations, needed when changing core sim state, or to access the clothing data.
void InstantiatePhysicsAsset_Internal (const UPhysicsAsset &PhysAsset, const FVector &Scale3D, TArray< FBodyInstance * > &OutBodies, TArray< FConstraintInstance * > &OutConstraints, TFunctionRef< FTransform(int32)> BoneTransformGetter, FPhysScene *PhysScene=nullptr, USkeletalMeshComponent *OwningComponent=nullptr, int32 UseRootBodyIndex=INDEX_NONE, const FPhysicsAggregateHandle &UseAggregate=FPhysicsAggregateHandle()) const
void InstantiatePhysicsAssetBodies_Internal (const UPhysicsAsset &PhysAsset, TArray< FBodyInstance * > &OutBodies, TFunctionRef< FTransform(int32)> BoneTransformGetter, TMap< FName, FBodyInstance * > *OutNameToBodyMap=nullptr, FPhysScene *PhysScene=nullptr, USkeletalMeshComponent *OwningComponent=nullptr, int32 UseRootBodyIndex=INDEX_NONE, const FPhysicsAggregateHandle &UseAggregate=FPhysicsAggregateHandle()) const
void MarkRequiredCurveUpToDate ()
Mark current anim UID version to up-to-date.
virtual void OnClearAnimScriptInstance ()
void OnConstraintBrokenWrapper (int32 ConstraintIndex)
Wrapper that calls our constraint broken delegate.
void OnPlasticDeformationWrapper (int32 ConstraintIndex)
Wrapper that calls our constraint plasticity delegate.
void ParallelBlendPhysics ()
void ParallelDuplicateAndInterpolate (FAnimationEvaluationContext &InAnimEvaluationContext)
Duplicates cached transforms/curves and performs interpolation.
void PerformBlendPhysicsBones (const TArray< FBoneIndexType > &InRequiredBones, TArray< FTransform > &InOutComponentSpaceTransforms, TArray< FTransform > &InOutBoneSpaceTransforms)
virtual void RefreshMorphTargets () override
FDelegateHandle RegisterOnLODRequiredBonesUpdate_Member (const FOnLODRequiredBonesUpdate &Delegate)
Register/Unregister for OnLODRequiredBonesUpdate callback.
virtual void RemoveFollowerPoseComponent (USkinnedMeshComponent *SkinnedMeshComponent) override
PRAGMA_ENABLE_DEPRECATION_WARNINGS void ResetLinkedAnimInstances ()
Clear the linked anim instances and mark them pending kill.
void ResetMorphTargetCurves ()
void ResetToRefPose ()
Internal helper - copies the mesh's reference pose to the local space transforms and regenerates component space transforms accordingly.
void SetAnimInstanceClass_Internal (const TSubclassOf< UAnimInstance > &InAnimClass)
bool ShouldRunEndPhysicsTick () const
bool ShouldWaitForClothInTickFunction () const
Whether we should stall the Cloth tick task until the cloth simulation is complete.
void SwapEvaluationContextBuffers ()
Swaps buffers into the evaluation context before and after task dispatch.
void UnregisterOnLODRequiredBonesUpdate_Member (const FDelegateHandle &DelegateHandle)
void UpdateClothSimulationContext (float InDeltaTime)
Copies the data from the external cloth simulation context.
void UpdateClothTickRegisteredState ()
void UpdateClothTransformImp ()
See UpdateClothTransform for documentation.
void UpdateDuringAnimationTickRegisteredState ()
void UpdateEndPhysicsTickRegisteredState ()
void UpdateMorphTargetOverrideCurves ()
UPROPERTY () bool bFilteredAnimCurvesIsAllowList
Whether the FilteredAnimCurves list is an allow or deny list.
UPROPERTY () float TeleportDistanceThreshold
Conduct teleportation if the character's movement is greater than this threshold in 1 frame.
UPROPERTY () float TeleportRotationThreshold
Rotation threshold in degrees, ranging from 0 to 180.
UPROPERTY () TArray< FName > FilteredAnimCurves
You can choose to disable certain curves if you prefer.
UPROPERTY () TArray< FTransform > CachedBoneSpaceTransforms
Cached BoneSpaceTransforms for Update Rate optimization.
UPROPERTY () TArray< FTransform > CachedComponentSpaceTransforms
Cached SpaceBases for Update Rate optimization.
UPROPERTY () TArray< TObjectPtr< UAnimInstance > > LinkedInstances
Any running linked anim instances.
UPROPERTY () TMap< FName
Morph Target Curves.
UPROPERTY () TObjectPtr< UClothingSimulationInteractor > ClothingInteractor
Object responsible for interacting with the clothing simulation.
UPROPERTY () uint16 CachedMeshCurveMetaDataVersion
Cache curve metadata from mesh and this will be used to identify if it needs to be updated.
UPROPERTY () uint32 LastPoseTickFrame
UPROPERTY ()) int32 PostProcessAnimBPLODThreshold
void WritebackClothingSimulationData ()
Called by the clothing completion event to perform a writeback of the simulation data to the game thread, the task is friended to gain access to this and not allow any external callers to trigger writebacks.
Private Attributes
FAnimationEvaluationContext AnimEvaluationContext
UE::Anim::FMeshAttributeContainer AttributesArray [2]
Temporary array of attributes that are active on this component - keeps same buffer index as SpaceBases - Please check SkinnedMeshComponent.
UPROPERTY() uint8 bDisableRigidBodyAnimNode UPROPERTY() uint8 bAllowAnimCurveEvaluation uint8 bBindClothToLeaderComponent:1
Disable rigid body animation nodes and play original animation without simulation.
uint8 bPendingClothCollisionUpdate:1
Flag denoting whether or not the clothing collision needs to update from its physics asset.
uint8 bPendingClothTransformUpdate:1
Flag denoting whether or not the clothing transform needs to update.
UPROPERTY() uint8 bNeedsQueuedAnimEventsDispatched uint8 bPostEvaluatingAnimation:1
UE::Anim::FMeshAttributeContainer CachedAttributes
Current and cached attribute evaluation data, used for Update Rate optimization.
FBlendedHeapCurve CachedCurve
Cached Curve result for Update Rate optimization.
TArray< FClothCollisionSource > ClothCollisionSources
Array of sources for cloth collision.
IClothingSimulation * ClothingSimulation
Clothing simulation objects.
IClothingSimulationContext * ClothingSimulationContext
float ClothTeleportCosineThresholdInRad
Used for pre-computation using TeleportRotationThreshold property.
float ClothTeleportDistThresholdSquared
Used for pre-computation using tTeleportDistanceThreshold property.
FBlendedHeapCurve CurvesArray [2]
This is required for recording animations, so save for editor only.
UE::Anim::FMeshAttributeContainer CustomAttributes
friend FSkeletalMeshComponentClothTickFunction
Let the cloth tick and completion tasks have access to private clothing data.
float MorphTargetCurves
FOnBoneTransformsFinalizedMultiCast OnBoneTransformsFinalizedMC
Multicaster fired when this component bone transforms are finalized.
FOnLODRequiredBonesUpdateMulticast OnLODRequiredBonesUpdate_Member
FOnSkelMeshPhysicsCreatedMultiCast OnSkelMeshPhysicsCreated
Multicaster fired when this component creates physics state (in case external objects rely on physics state)
FOnSkelMeshTeleportedMultiCast OnSkelMeshPhysicsTeleported
Multicaster fired when this component teleports.
FGraphEventRef ParallelAnimationEvaluationTask
FGraphEventRef ParallelBlendPhysicsCompletionTask
FGraphEventRef ParallelClothTask
Ref for the clothing parallel task, so we can detect whether or not a sim is running.
ETeleportType PendingTeleportType
Teleport type to use on the next update.
FMatrix PrevRootBoneMatrix
previous root bone matrix to compare the difference and decide to do clothing teleport
FVector3f PrevRootRigidBodyScale
previous root body scale to compare the difference when the actor scale is updated.
TSharedPtr< struct FBoneContainer > SharedRequiredBones
Shared bone container between all anim instances owned by this skeletal mesh component.
Static Private Attributes
static FOnLODRequiredBonesUpdateMulticast OnLODRequiredBonesUpdate_Static
Multicaster fired when this component finalizes the regeneration of the required bones list for the current LOD.
Friends
struct FAnimNode_LinkedAnimGraph
struct FAnimNode_LinkedAnimLayer
class FClothingSimulationContextCommon
struct FLinkedAnimLayerClassData
struct FLinkedInstancesAdapter
class FParallelAnimationCompletionTask
class FParallelBlendPhysicsCompletionTask
class FParallelBlendPhysicsTask
class FParallelClothCompletionTask
class FParallelClothTask
struct FRigUnit_AnimNextRemapPose
struct FRigUnit_AnimNextWriteSkeletalMeshComponentPose
class FSkeletalMeshComponentDetails
struct FSkeletalMeshComponentEndPhysicsTickFunction
class FTickClothingTask
class UAnimInstance
class UDebugSkelMeshComponent
Debug mesh component should be able to access for visualisation.
class UE::AnimNext::FDataRegistry
class USkeletalMesh
Detailed Description
Definition at line 314 of file SkeletalMeshComponent.h.
Member Typedef Documentation
FOnSkeletalMeshPropertyChanged
typedef FOnSkeletalMeshPropertyChangedMulticaster::FDelegate USkeletalMeshComponent::FOnSkeletalMeshPropertyChanged
Definition at line 1776 of file SkeletalMeshComponent.h.
FOnSkeletalMeshUnregisteredDelegate
typedef FOnSkeletalMeshUnregisterd::FDelegate USkeletalMeshComponent::FOnSkeletalMeshUnregisteredDelegate
Definition at line 1784 of file SkeletalMeshComponent.h.
Member Function Documentation
AddClothingBounds()
void USkeletalMeshComponent::AddClothingBounds (FBoxSphereBounds & InOutBounds, const FTransform & LocalToWorld) const
Given bounds InOutBounds, expand them to also enclose the clothing simulation mesh.
References AddClothingBounds(), and const.
Referenced by AddClothingBounds().
AddFollowerPoseComponent()
virtual void USkeletalMeshComponent::AddFollowerPoseComponent (USkinnedMeshComponent * SkinnedMeshComponent) override private virtual
Override USkinnedMeshComponent.
AddRadialForce()
virtual void USkeletalMeshComponent::AddRadialForce (FVector Origin, float Radius, float Strength, ERadialImpulseFalloff Falloff, bool bAccelChange = false) override virtual
References AddRadialForce(), bAccelChange, FVector, and Origin.
Referenced by AddRadialForce().
AddRadialImpulse()
virtual void USkeletalMeshComponent::AddRadialImpulse (FVector Origin, float Radius, float Strength, ERadialImpulseFalloff Falloff, bool bVelChange = false) override virtual
References AddRadialImpulse(), bVelChange, FVector, and Origin.
Referenced by AddRadialImpulse().
AllocateTransformData()
virtual bool USkeletalMeshComponent::AllocateTransformData () override virtual
AllowQueuedAnimEventsNextDispatch()
PRAGMA_ENABLE_DEPRECATION_WARNINGS void USkeletalMeshComponent::AllowQueuedAnimEventsNextDispatch ()
If true, next time that ConditionallyDispatchQueuedAnimEvents() is called it will trigger any queued anim notifies available.
References PRAGMA_DISABLE_DEPRECATION_WARNINGS.
ApplyAnimationCurvesToComponent()
void USkeletalMeshComponent::ApplyAnimationCurvesToComponent (const TMap< FName, float > * InMaterialParameterCurves, const TMap< FName, float > * InAnimationMorphCurves)
Apply animation curves to this component.
ApplyDeltaToAllPhysicsTransforms()
void USkeletalMeshComponent::ApplyDeltaToAllPhysicsTransforms (const FVector & DeltaLocation, const FQuat & DeltaRotation)
Set physics transforms for all bodies.
References ApplyDeltaToAllPhysicsTransforms(), const, and FVector.
Referenced by ApplyDeltaToAllPhysicsTransforms().
ApplyEditedComponentSpaceTransforms()
void USkeletalMeshComponent::ApplyEditedComponentSpaceTransforms ()
Called after modifying Component Space Transforms externally.
AreRequiredCurvesUpToDate()
bool USkeletalMeshComponent::AreRequiredCurvesUpToDate () const private
BeginPlay()
virtual void USkeletalMeshComponent::BeginPlay () override virtual
BlendInPhysicsInternal()
void USkeletalMeshComponent::BlendInPhysicsInternal (FTickFunction & ThisTickFunction) private
Referenced by UE_DEPRECATED().
CalcBounds()
virtual FBoxSphereBounds USkeletalMeshComponent::CalcBounds (const FTransform & LocalToWorld) const override virtual
CalculateMass()
virtual float USkeletalMeshComponent::CalculateMass (FName BoneName = NAME_None) override virtual
References BoneName, and CalculateMass().
Referenced by CalculateMass().
CanEditSimulatePhysics()
virtual bool USkeletalMeshComponent::CanEditSimulatePhysics () override virtual
CanHaveStaticMobility()
virtual const bool USkeletalMeshComponent::CanHaveStaticMobility () const inline override virtual
Skeletal mesh component should not be able to have its mobility set to static.
Definition at line 2701 of file SkeletalMeshComponent.h.
CanSimulateClothing()
bool USkeletalMeshComponent::CanSimulateClothing () const
CheckClothTeleport()
virtual void USkeletalMeshComponent::CheckClothTeleport () virtual
Check linear and angular thresholds for clothing teleport.
References CheckClothTeleport().
Referenced by CheckClothTeleport().
ClearAnimNotifyErrors()
virtual void USkeletalMeshComponent::ClearAnimNotifyErrors (UObject * InSourceNotify) inline virtual
Clears currently stored errors.
Call before triggering anim notifies for a particular mesh.
Definition at line 1443 of file SkeletalMeshComponent.h.
ClearAnimScriptInstance()
void USkeletalMeshComponent::ClearAnimScriptInstance ()
ClearCachedAnimProperties()
void USkeletalMeshComponent::ClearCachedAnimProperties ()
Clear cached animation data generated for URO during evaluation.
ClearRefPoseOverride()
virtual void USkeletalMeshComponent::ClearRefPoseOverride () override virtual
References ClearRefPoseOverride().
Referenced by ClearRefPoseOverride().
CompleteParallelAnimationEvaluation()
virtual void USkeletalMeshComponent::CompleteParallelAnimationEvaluation (bool bDoPostAnimEvaluation) virtual
CompleteParallelBlendPhysics()
void USkeletalMeshComponent::CompleteParallelBlendPhysics () private
CompleteParallelClothSimulation()
void USkeletalMeshComponent::CompleteParallelClothSimulation ()
Callback when the parallel clothing task finishes, copies needed data back to component for gamethread.
ComponentIsTouchingSelectionBox()
virtual bool USkeletalMeshComponent::ComponentIsTouchingSelectionBox (const FBox & InSelBBox, const bool bConsiderOnlyBSP, const bool bMustEncompassEntireComponent) const override virtual
ComponentIsTouchingSelectionFrustum()
virtual bool USkeletalMeshComponent::ComponentIsTouchingSelectionFrustum (const FConvexVolume & InFrustum, const bool bConsiderOnlyBSP, const bool bMustEncompassEntireComponent) const override virtual
ComponentOverlapComponentImpl()
virtual bool USkeletalMeshComponent::ComponentOverlapComponentImpl (class UPrimitiveComponent * PrimComp, const FVector Pos, const FQuat & Quat, const FCollisionQueryParams & Params) override protected virtual
References FVector, Params, and Quat.
ComponentOverlapMultiImpl()
virtual bool USkeletalMeshComponent::ComponentOverlapMultiImpl (TArray< struct FOverlapResult > & OutOverlaps, const class UWorld * InWorld, const FVector & Pos, const FQuat & Rot, ECollisionChannel TestChannel, const struct FComponentQueryParams & Params, const struct FCollisionObjectQueryParams & ObjectQueryParams = FCollisionObjectQueryParams::DefaultObjectQueryParam) const override protected virtual
Test the collision of the supplied component at the supplied location/rotation, and determine the set of components that it overlaps.
Parameters
OutOverlaps Array of overlaps found between this component in specified pose and the world
World World to use for overlap test
Pos Location of the component's geometry for the test against the world
Rot Rotation of the component's geometry for the test against the world
TestChannel The 'channel' that this ray is in, used to determine which components to hit
ObjectQueryParams List of object types it's looking for. When this enters, we do object query with component shape
Returns
TRUE if OutOverlaps contains any blocking results
References FCollisionObjectQueryParams::DefaultObjectQueryParam, FVector, and Params.
ComputeRequiredBones()
void USkeletalMeshComponent::ComputeRequiredBones (TArray< FBoneIndexType > & OutRequiredBones, TArray< FBoneIndexType > & OutFillComponentSpaceTransformsRequiredBones, int32 LODIndex, bool bIgnorePhysicsAsset) const
Computes the required bones in this SkeletalMeshComponent based on current SkeletalMesh, LOD and PhysicsAsset.
Parameters
LODIndex Index of LOD [0-(MaxLOD-1)]
References ComputeRequiredBones(), const, and OutRequiredBones.
Referenced by ComputeRequiredBones().
ComputeSkinnedPositions()
void USkeletalMeshComponent::ComputeSkinnedPositions (USkeletalMeshComponent * Component, TArray< FVector3f > & OutPositions, TArray< FMatrix44f > & CachedRefToLocals, const FSkeletalMeshLODRenderData & Model, const FSkinWeightVertexBuffer & SkinWeightBuffer) static
References Component.
ComputeSkinnedTangentBasis()
void USkeletalMeshComponent::ComputeSkinnedTangentBasis (USkeletalMeshComponent * Component, TArray< FVector3f > & OutTangenXYZ, TArray< FMatrix44f > & CachedRefToLocals, const FSkeletalMeshLODRenderData & Model, const FSkinWeightVertexBuffer & SkinWeightBuffer) static
References Component.
ConditionallyDispatchQueuedAnimEvents()
void USkeletalMeshComponent::ConditionallyDispatchQueuedAnimEvents ()
ConsumeRootMotion()
FRootMotionMovementParams USkeletalMeshComponent::ConsumeRootMotion ()
Consume and return pending root motion from our internal anim instances (main, sub and post)
ConsumeRootMotion_Internal()
FRootMotionMovementParams USkeletalMeshComponent::ConsumeRootMotion_Internal (float InAlpha) protected
Consume and return pending root motion from our internal anim instances (main, sub and post)
ConvertLocalRootMotionToWorld()
FTransform USkeletalMeshComponent::ConvertLocalRootMotionToWorld (const FTransform & InTransform)
Take extracted RootMotion and convert it from local space to world space.
CopyChildrenClothCollisionsToParent()
void USkeletalMeshComponent::CopyChildrenClothCollisionsToParent () protected
copy children's cloth collisions to parent, where parent means this component
CopyClothCollisionSources()
void USkeletalMeshComponent::CopyClothCollisionSources () protected
copy cloth collision sources to this, where parent means components above it in the hierarchy
CopyClothCollisionsToChildren()
void USkeletalMeshComponent::CopyClothCollisionsToChildren () protected
copy parent's cloth collisions to attached children, where parent means this component
CreateBodySetup()
void USkeletalMeshComponent::CreateBodySetup ()
DeallocateTransformData()
virtual void USkeletalMeshComponent::DeallocateTransformData () override virtual
DebugDrawClothing()
void USkeletalMeshComponent::DebugDrawClothing (FPrimitiveDrawInterface * PDI)
Draw the currently clothing state, using the editor extender interface.
Parameters
PDI The draw interface to use
References DebugDrawClothing().
Referenced by DebugDrawClothing().
DebugDrawClothingTexts()
void USkeletalMeshComponent::DebugDrawClothingTexts (FCanvas * Canvas, const FSceneView * SceneView)
Draw the currently clothing state, using the editor extender interface.
Parameters
Canvas The canvas to draw the text on
SceneView The view to project the text with
References const, and DebugDrawClothingTexts().
Referenced by DebugDrawClothingTexts().
DECLARE_MULTICAST_DELEGATE()
USkeletalMeshComponent::DECLARE_MULTICAST_DELEGATE (FOnSkeletalMeshPropertyChangedMulticaster)
DECLARE_MULTICAST_DELEGATE_OneParam()
USkeletalMeshComponent::DECLARE_MULTICAST_DELEGATE_OneParam (FOnSkeletalMeshUnregisterd , const USkeletalMeshComponent *)
DispatchParallelEvaluationTasks()
void USkeletalMeshComponent::DispatchParallelEvaluationTasks (FActorComponentTickFunction * TickFunction) private
Queues up tasks for parallel update/evaluation, as well as the chained game thread completion task.
DispatchParallelTickPose()
virtual void USkeletalMeshComponent::DispatchParallelTickPose (FActorComponentTickFunction * TickFunction) override protected virtual
DoAnyPhysicsBodiesHaveWeight()
bool USkeletalMeshComponent::DoAnyPhysicsBodiesHaveWeight () const private
DoCustomNavigableGeometryExport()
virtual bool USkeletalMeshComponent::DoCustomNavigableGeometryExport (FNavigableGeometryExport & GeomExport) const override virtual
References const, and DoCustomNavigableGeometryExport().
Referenced by DoCustomNavigableGeometryExport().
DoInstancePostEvaluation()
void USkeletalMeshComponent::DoInstancePostEvaluation () protected
DoInstancePreEvaluation()
void USkeletalMeshComponent::DoInstancePreEvaluation () protected
DoParallelEvaluationTasks_OnGameThread()
void USkeletalMeshComponent::DoParallelEvaluationTasks_OnGameThread () private
Performs parallel eval/update work, but on the game thread.
EndPhysicsTickComponent()
void USkeletalMeshComponent::EndPhysicsTickComponent (FSkeletalMeshComponentEndPhysicsTickFunction & ThisTickFunction) private
Update systems after physics sim is done.
References FSkeletalMeshComponentEndPhysicsTickFunction.
EvaluateAnimation()
void USkeletalMeshComponent::EvaluateAnimation (const USkeletalMesh * InSkeletalMesh, UAnimInstance * InAnimInstance, bool bInForceRefPose, FVector & OutRootBoneTranslation, FBlendedHeapCurve & OutCurve, FCompactPose & OutPose, UE::Anim::FHeapAttributeContainer & OutAttributes) const private
Evaluate Anim System.
References FVector, InAnimInstance, InSkeletalMesh, OutAttributes, OutCurve, OutRootBoneTranslation, UAnimInstance, and USkeletalMesh.
EvaluatePostProcessMeshInstance()
void USkeletalMeshComponent::EvaluatePostProcessMeshInstance (TArray< FTransform > & OutBoneSpaceTransforms, FCompactPose & InOutPose, FBlendedHeapCurve & OutCurve, const USkeletalMesh * InSkeletalMesh, FVector & OutRootBoneTranslation, UE::Anim::FHeapAttributeContainer & OutAttributes, bool bInForceRefPose) const
Evaluates the post process instance from the skeletal mesh this component is using.
References const, EvaluatePostProcessMeshInstance(), FVector, InOutPose, InSkeletalMesh, OutAttributes, OutBoneSpaceTransforms, OutCurve, OutRootBoneTranslation, and USkeletalMesh.
Referenced by EvaluatePostProcessMeshInstance().
ExcludeHiddenBones()
void USkeletalMeshComponent::ExcludeHiddenBones (const USkeletalMeshComponent * SkeletalMeshComponent, const USkeletalMesh * SkeletalMesh, TArray< FBoneIndexType > & OutRequiredBones) static
References const, ExcludeHiddenBones(), OutRequiredBones, SkeletalMesh, and USkeletalMesh.
Referenced by ExcludeHiddenBones().
ExtractCollisionsForCloth()
void USkeletalMeshComponent::ExtractCollisionsForCloth (USkeletalMeshComponent * SourceComponent, UPhysicsAsset * PhysicsAsset, USkeletalMeshComponent * DestClothComponent, FClothCollisionData & OutCollisions, FClothCollisionSource & ClothCollisionSource) static protected
Extract collisions for cloth from this component (given a component we want to apply the data to)
FinalizeAnimationUpdate()
void USkeletalMeshComponent::FinalizeAnimationUpdate () private
FinalizeAttributeEvaluationResults()
void USkeletalMeshComponent::FinalizeAttributeEvaluationResults (const FBoneContainer & BoneContainer, const UE::Anim::FHeapAttributeContainer & FinalContainer, UE::Anim::FMeshAttributeContainer & OutContainer) const private
FinalizeBoneTransform()
virtual void USkeletalMeshComponent::FinalizeBoneTransform () override virtual
References FinalizeBoneTransform().
Referenced by FinalizeBoneTransform().
FinalizePoseEvaluationResult()
void USkeletalMeshComponent::FinalizePoseEvaluationResult (const USkeletalMesh * InMesh, TArray< FTransform > & OutBoneSpaceTransforms, FVector & OutRootBoneTranslation, FCompactPose & InFinalPose) const private
References FVector, OutBoneSpaceTransforms, OutRootBoneTranslation, and USkeletalMesh.
FindAttributeChecked()
template<typename DataType, typename CustomAttributeType> bool USkeletalMeshComponent::FindAttributeChecked (const FName & BoneName, const FName & AttributeName, DataType DefaultValue, DataType & OutValue, ECustomBoneAttributeLookup LookupType) protected
Templated version to try and retrieve a typed bone attribute's value.
References AttributeName, BoneName, const, DefaultValue, FindAttributeChecked(), LookupType, and OutValue.
Referenced by FindAttributeChecked().
FindClothCollisions()
void USkeletalMeshComponent::FindClothCollisions (FClothCollisionData & OutCollisions) protected
find if this component has collisions for clothing and return the results calculated by bone transforms
FindConstraintIndex()
int32 USkeletalMeshComponent::FindConstraintIndex (FName ConstraintName)
Find Constraint Index from the name.
Parameters
ConstraintName Joint Name of constraint to look for
Returns
Constraint Index
References FindConstraintIndex().
Referenced by FindConstraintIndex().
FindConstraintInstance()
FConstraintInstance * USkeletalMeshComponent::FindConstraintInstance (FName ConName)
Find instance of the constraint that matches the name supplied.
References FindConstraintInstance().
Referenced by FindConstraintInstance().
FindRootBodyIndex()
int32 USkeletalMeshComponent::FindRootBodyIndex () const
Find the root body index.
ForEachAnimInstance()
void USkeletalMeshComponent::ForEachAnimInstance (TFunctionRef< void(UAnimInstance *)> InFunction)
Calls a function on each of the anim instances that this mesh component hosts, including linked and post-process instances.
References ForEachAnimInstance(), and UAnimInstance.
Referenced by ForEachAnimInstance().
ForEachBodyBelow()
int32 USkeletalMeshComponent::ForEachBodyBelow (FName BoneName, bool bIncludeSelf, bool bSkipCustomType, TFunctionRef< void(FBodyInstance *)> Func)
Iterates over all bodies below and executes Func.
Returns number of bodies found
References bIncludeSelf, BoneName, and ForEachBodyBelow().
Referenced by ForEachBodyBelow().
GENERATED_UCLASS_BODY()
USkeletalMeshComponent::GENERATED_UCLASS_BODY () private
GetAllPhysicsObjects()
virtual TArray< Chaos::FPhysicsObject * > USkeletalMeshComponent::GetAllPhysicsObjects () const override virtual
GetAnimationCurves()
const FBlendedHeapCurve & USkeletalMeshComponent::GetAnimationCurves () const inline
Access Curve Array for reading.
Definition at line 2683 of file SkeletalMeshComponent.h.
References CurvesArray.
GetAnimationModePropertyNameChecked()
const FName & USkeletalMeshComponent::GetAnimationModePropertyNameChecked () static
Whether to use Animation Blueprint or play Single Animation Asset.
References const, and GetAnimationModePropertyNameChecked().
Referenced by GetAnimationModePropertyNameChecked().
GetAnimCurves()
const FBlendedHeapCurve & USkeletalMeshComponent::GetAnimCurves () const
Get the current set of curve values.
References const, and GetAnimCurves().
Referenced by GetAnimCurves().
GetBodyInstance()
virtual FBodyInstance * USkeletalMeshComponent::GetBodyInstance (FName BoneName = NAME_None, bool bGetWelded = true, int32 Index = INDEX_NONE) const override virtual
References BoneName, and INDEX_NONE.
GetBodySetup()
virtual class UBodySetup * USkeletalMeshComponent::GetBodySetup () override virtual
GetBoneSpaceTransforms()
TArray< FTransform > USkeletalMeshComponent::GetBoneSpaceTransforms ()
References GetBoneSpaceTransforms().
Referenced by GetBoneSpaceTransforms().
GetBoneSpaceTransformsView()
TArrayView< const FTransform > USkeletalMeshComponent::GetBoneSpaceTransformsView ()
Get the bone space transforms as array view.
References const, and GetBoneSpaceTransformsView().
Referenced by GetBoneSpaceTransformsView().
GetCachedComponentSpaceTransforms()
const TArray< FTransform > & USkeletalMeshComponent::GetCachedComponentSpaceTransforms () const
Access cached component space transforms.
References const, and GetCachedComponentSpaceTransforms().
Referenced by GetCachedComponentSpaceTransforms().
GetClosestCollidingRigidBodyLocation()
FVector USkeletalMeshComponent::GetClosestCollidingRigidBodyLocation (const FVector & TestLocation) const
iterates through all bodies in our PhysicsAsset and returns the location of the closest bone associated with a body that has collision enabled.
Parameters
TestLocation - location to check against
Returns
location of closest colliding rigidbody, or TestLocation if there were no bodies to test
References const, FVector, and GetClosestCollidingRigidBodyLocation().
Referenced by GetClosestCollidingRigidBodyLocation().
GetClosestPointOnPhysicsAsset()
bool USkeletalMeshComponent::GetClosestPointOnPhysicsAsset (const FVector & WorldPosition, FClosestPointOnPhysicsAsset & ClosestPointOnPhysicsAsset, bool bApproximate) const
Given a world position, find the closest point on the physics asset.
Note that this is independent of collision and welding. This is based purely on animation position
Parameters
WorldPosition The point we want the closest point to (i.e. for all bodies in the physics asset, find the one that has a point closest to WorldPosition)
ClosestPointOnPhysicsAsset The data associated with the closest point (position, normal, etc...)
bApproximate The closest body is found using bone transform distance instead of body distance. This approximation means the final point is the closest point on a potentially not closest body. This approximation gets worse as the size of Bodies gets bigger.
Returns
true if we found a closest point
References const, FVector, and GetClosestPointOnPhysicsAsset().
Referenced by GetClosestPointOnPhysicsAsset().
GetClothCollisionSources()
const TArray< FClothCollisionSource > & USkeletalMeshComponent::GetClothCollisionSources () const inline
Definition at line 2424 of file SkeletalMeshComponent.h.
References ClothCollisionSources.
GetClothingSimFactory()
UClothingSimulationFactory * USkeletalMeshComponent::GetClothingSimFactory () const private
Gets the factory responsible for building the clothing simulation and simulation contexts.
GetClothingSimulation() [1/2]
IClothingSimulation * USkeletalMeshComponent::GetClothingSimulation ()
Get the current clothing simulation (read/write)
GetClothingSimulation() [2/2]
const IClothingSimulation * USkeletalMeshComponent::GetClothingSimulation () const
Get the current clothing simulation (read only)
GetClothingSimulationContext() [1/2]
IClothingSimulationContext * USkeletalMeshComponent::GetClothingSimulationContext ()
Get the current clothing simulation context (read/write)
GetClothingSimulationContext() [2/2]
const IClothingSimulationContext * USkeletalMeshComponent::GetClothingSimulationContext () const
Get the current clothing simulation context (read only)
GetClothSimulatedPosition_GameThread()
bool USkeletalMeshComponent::GetClothSimulatedPosition_GameThread (const FGuid & AssetGuid, int32 VertexIndex, FVector & OutSimulPos) const
if the vertex index is valid for simulated vertices, returns the position in world space
References FVector.
GetComponentInstanceData()
virtual TStructOnScope< FActorComponentInstanceData > USkeletalMeshComponent::GetComponentInstanceData () const override virtual
GetComponentTransformFromBodyInstance()
virtual FTransform USkeletalMeshComponent::GetComponentTransformFromBodyInstance (FBodyInstance * UseBI) override protected virtual
If PhysicsTransformUpdateMode is set to SimulationUpdatesComponentTransform, this returns the world-space transform of the body passed in (assumed to be the root body), after applying the TransformToRoot offset.
Otherwise, it returns the component transform.
References Ar.
GetConstraintInstanceByIndex()
FConstraintInstance * USkeletalMeshComponent::GetConstraintInstanceByIndex (uint32 Index)
get instance of the constraint that matches the index .
References GetConstraintInstanceByIndex().
Referenced by GetConstraintInstanceByIndex().
GetConstraintProfilePropertiesOrDefault()
bool USkeletalMeshComponent::GetConstraintProfilePropertiesOrDefault (FConstraintProfileProperties & OutProperties, FName JointName, FName ProfileName)
Gets the constraint profile properties that a joint drive would adopt if it were set to the given constraint profile.
The default will be returned if an empty or invalid profile name is passed in. Returns true if the successful, or false if the joint can't be found.
References GetConstraintProfilePropertiesOrDefault(), and ProfileName.
Referenced by GetConstraintProfilePropertiesOrDefault().
GetCurrentClothingData_AnyThread()
const TMap< int32, FClothSimulData > & USkeletalMeshComponent::GetCurrentClothingData_AnyThread () const
Get the current simulation data map for the clothing on this component.
This will stall until the cloth simulation is complete.
GetCurrentClothingData_GameThread()
const TMap< int32, FClothSimulData > & USkeletalMeshComponent::GetCurrentClothingData_GameThread () const
Get the current simulation data map for the clothing on this component.
For use on the game thread and only valid if bWaitForParallelClothTask is true.
GetCurveFilterSettings()
UE::Anim::FCurveFilterSettings USkeletalMeshComponent::GetCurveFilterSettings (int32 InLODOverride = INDEX_NONE) const
Get the curve settings that will be used for anim evaluation.
Parameters
InLODOverride Override the LOD that curves will be calculated for if not INDEX_NONE
Returns
the curve settings used for evaluation
References INDEX_NONE.
GetCustomAttributes()
const UE::Anim::FMeshAttributeContainer & USkeletalMeshComponent::GetCustomAttributes () const inline
Definition at line 2698 of file SkeletalMeshComponent.h.
References AttributesArray.
GetEditableAnimationCurves() [1/2]
FBlendedHeapCurve & USkeletalMeshComponent::GetEditableAnimationCurves () inline
Get Access to the current editable Curve Array - uses same buffer as space bases.
Definition at line 2686 of file SkeletalMeshComponent.h.
References CurvesArray.
GetEditableAnimationCurves() [2/2]
const FBlendedHeapCurve & USkeletalMeshComponent::GetEditableAnimationCurves () const inline
Definition at line 2687 of file SkeletalMeshComponent.h.
References CurvesArray.
GetEditableCustomAttributes()
UE::Anim::FMeshAttributeContainer & USkeletalMeshComponent::GetEditableCustomAttributes () inline private
Definition at line 2695 of file SkeletalMeshComponent.h.
References AttributesArray.
GetLinkedAnimInstances() [1/2]
PRAGMA_DISABLE_DEPRECATION_WARNINGS TArray< TObjectPtr< UAnimInstance > > & USkeletalMeshComponent::GetLinkedAnimInstances () inline private
Definition at line 1042 of file SkeletalMeshComponent.h.
GetLinkedAnimInstances() [2/2]
PRAGMA_DISABLE_DEPRECATION_WARNINGS const TArray< UAnimInstance * > & USkeletalMeshComponent::GetLinkedAnimInstances () const inline
Get the anim instances linked to the main AnimScriptInstance.
Definition at line 1034 of file SkeletalMeshComponent.h.
References const, GetLinkedAnimInstances(), and UAnimInstance.
Referenced by GetLinkedAnimInstances().
GetMass()
virtual float USkeletalMeshComponent::GetMass () const override virtual
References const, and GetMass().
Referenced by GetMass().
GetMorphTargetCurves()
const TMap< FName, float > & USkeletalMeshComponent::GetMorphTargetCurves () const inline
Definition at line 1652 of file SkeletalMeshComponent.h.
References const, GetMorphTargetCurves(), and MorphTargetCurves.
Referenced by GetMorphTargetCurves().
GetPendingRadialForces()
const TArray< FPendingRadialForces > & USkeletalMeshComponent::GetPendingRadialForces () const inline
Definition at line 982 of file SkeletalMeshComponent.h.
References PendingRadialForces.
GetPhysicsObjectById()
virtual Chaos::FPhysicsObject * USkeletalMeshComponent::GetPhysicsObjectById (Chaos::FPhysicsObjectId Id) const override virtual
GetPhysicsObjectByName()
virtual Chaos::FPhysicsObject * USkeletalMeshComponent::GetPhysicsObjectByName (const FName & Name) const override virtual
References Name.
GetPostProcessAnimBPClassToBeUsed()
TSubclassOf< UAnimInstance > USkeletalMeshComponent::GetPostProcessAnimBPClassToBeUsed () const
Get the post-processing AnimBP to be used for this skeletal mesh component.
In case an override post-processing AnimBP is set, it will always return the AnimBP class of that. Otherwise the one set in skeletal mesh asset will be returned.
GetRequiredVirtualBones()
void USkeletalMeshComponent::GetRequiredVirtualBones (const USkeletalMesh * SkeletalMesh, TArray< FBoneIndexType > & OutRequiredBones) static
References const, GetRequiredVirtualBones(), OutRequiredBones, SkeletalMesh, and USkeletalMesh.
Referenced by GetRequiredVirtualBones().
GetResourceSizeEx()
virtual void USkeletalMeshComponent::GetResourceSizeEx (FResourceSizeEx & CumulativeResourceSize) override virtual
GetShadowShapeRequiredBones()
void USkeletalMeshComponent::GetShadowShapeRequiredBones (const USkeletalMeshComponent * SkeletalMeshComponent, TArray< FBoneIndexType > & OutRequiredBones) static
References const, GetShadowShapeRequiredBones(), and OutRequiredBones.
Referenced by GetShadowShapeRequiredBones().
GetSharedRequiredBones()
TSharedPtr< struct FBoneContainer > USkeletalMeshComponent::GetSharedRequiredBones ()
Gets the shared bone container used between all owned anim instances.
Creates it on the first call.
References Animation, Category, GetSharedRequiredBones(), meta, UE_DEPRECATED(), and UPROPERTY().
Referenced by GetSharedRequiredBones().
GetSingleNodeInstance()
class UAnimSingleNodeInstance * USkeletalMeshComponent::GetSingleNodeInstance () const
GetSkinnedTangentBasis()
void USkeletalMeshComponent::GetSkinnedTangentBasis (USkeletalMeshComponent * Component, int32 VertexIndex, const FSkeletalMeshLODRenderData & Model, const FSkinWeightVertexBuffer & SkinWeightBuffer, TArray< FMatrix44f > & CachedRefToLocals, FVector3f & OutTangentX, FVector3f & OutTangentY, FVector3f & OutTangentZ) static
References Component.
GetSkinnedVertexPosition() [1/2]
FVector3f USkeletalMeshComponent::GetSkinnedVertexPosition (USkeletalMeshComponent * Component, int32 VertexIndex, const FSkeletalMeshLODRenderData & Model, const FSkinWeightVertexBuffer & SkinWeightBuffer) static
References Component.
GetSkinnedVertexPosition() [2/2]
FVector3f USkeletalMeshComponent::GetSkinnedVertexPosition (USkeletalMeshComponent * Component, int32 VertexIndex, const FSkeletalMeshLODRenderData & Model, const FSkinWeightVertexBuffer & SkinWeightBuffer, TArray< FMatrix44f > & CachedRefToLocals) static
References Component.
GetSquaredDistanceToCollision()
virtual bool USkeletalMeshComponent::GetSquaredDistanceToCollision (const FVector & Point, float & OutSquaredDistance, FVector & OutClosestPointOnCollision) const override virtual
References FVector, and Point.
GetTotalMassBelowBone()
float USkeletalMeshComponent::GetTotalMassBelowBone (FName InBoneName)
Utility which returns total mass of all bones below the supplied one in the hierarchy (including this one).
References GetTotalMassBelowBone(), and InBoneName.
Referenced by GetTotalMassBelowBone().
GetUpdateAnimationInEditor()
bool USkeletalMeshComponent::GetUpdateAnimationInEditor () const inline
return true if currently updating in editor is true this is non BP because this is only used for follower component to detect leader component ticking state
Definition at line 1375 of file SkeletalMeshComponent.h.
Referenced by FSkeletalMeshEditorParams::SaveState().
GetUpdateClothInEditor()
bool USkeletalMeshComponent::GetUpdateClothInEditor () const inline
Definition at line 1380 of file SkeletalMeshComponent.h.
Referenced by FSkeletalMeshEditorParams::SaveState().
GetUpdateClothSimulationData_AnyThread()
virtual void USkeletalMeshComponent::GetUpdateClothSimulationData_AnyThread (TMap< int32, FClothSimulData > & OutClothSimulData, FMatrix & OutLocalToWorld, float & OutClothBlendWeight) const override virtual
Store cloth simulation data into OutClothSimulData.
Override USkinnedMeshComponent.
References const, and GetUpdateClothSimulationData_AnyThread().
Referenced by GetUpdateClothSimulationData_AnyThread().
GetWeldedBodies()
void USkeletalMeshComponent::GetWeldedBodies (TArray< FBodyInstance * > & OutWeldedBodies, TArray< FName > & OutChildrenLabels, bool bIncludingAutoWeld = false) override
References GetWeldedBodies().
Referenced by GetWeldedBodies().
GetWindForCloth_GameThread()
void USkeletalMeshComponent::GetWindForCloth_GameThread (FVector & WindVector, float & WindAdaption) const private
References FVector.
HandleExistingParallelClothSimulation()
void USkeletalMeshComponent::HandleExistingParallelClothSimulation () private
Stalls on any currently running clothing simulations, needed when changing core sim state, or to access the clothing data.
HandleExistingParallelEvaluationTask()
bool USkeletalMeshComponent::HandleExistingParallelEvaluationTask (bool bBlockOnTask, bool bPerformPostAnimEvaluation)
HasValidPhysicsState()
virtual bool USkeletalMeshComponent::HasValidPhysicsState () const override virtual
HideBone()
virtual void USkeletalMeshComponent::HideBone (int32 BoneIndex, EPhysBodyOp PhysBodyOption) override virtual
InitAnim()
virtual void USkeletalMeshComponent::InitAnim (bool bForceReinit) virtual
InitArticulated()
void USkeletalMeshComponent::InitArticulated (FPhysScene * PhysScene)
Initialize PhysicsAssetInstance for the physicsAsset.
Parameters
PhysScene Physics Scene
InitCollisionRelationships()
void USkeletalMeshComponent::InitCollisionRelationships ()
References InitCollisionRelationships().
Referenced by InitCollisionRelationships().
InitializeAnimScriptInstance()
bool USkeletalMeshComponent::InitializeAnimScriptInstance (bool bForceReinit = true, bool bInDeferRootNodeInitialization = false)
InitializeComponent()
virtual void USkeletalMeshComponent::InitializeComponent () override virtual
InitSkelControls()
void USkeletalMeshComponent::InitSkelControls ()
Initialize SkelControls.
References InitSkelControls().
Referenced by InitSkelControls().
InstantiatePhysicsAsset()
void USkeletalMeshComponent::InstantiatePhysicsAsset (const UPhysicsAsset & PhysAsset, const FVector & Scale3D, TArray< FBodyInstance * > & OutBodies, TArray< FConstraintInstance * > & OutConstraints, FPhysScene * PhysScene = nullptr, USkeletalMeshComponent * OwningComponent = nullptr, int32 UseRootBodyIndex = INDEX_NONE, const FPhysicsAggregateHandle & UseAggregate = FPhysicsAggregateHandle()) const
Instantiates bodies given a physics asset.
Typically you should call InitArticulated unless you are planning to do something special with the bodies. The Created bodies and constraints are owned by the calling code and must be freed when necessary.
References FVector, INDEX_NONE, and OutConstraints.
InstantiatePhysicsAsset_Internal()
void USkeletalMeshComponent::InstantiatePhysicsAsset_Internal (const UPhysicsAsset & PhysAsset, const FVector & Scale3D, TArray< FBodyInstance * > & OutBodies, TArray< FConstraintInstance * > & OutConstraints, TFunctionRef< FTransform(int32)> BoneTransformGetter, FPhysScene * PhysScene = nullptr, USkeletalMeshComponent * OwningComponent = nullptr, int32 UseRootBodyIndex = INDEX_NONE, const FPhysicsAggregateHandle & UseAggregate = FPhysicsAggregateHandle()) const private
References FVector, INDEX_NONE, and OutConstraints.
InstantiatePhysicsAssetBodies()
void USkeletalMeshComponent::InstantiatePhysicsAssetBodies (const UPhysicsAsset & PhysAsset, TArray< FBodyInstance * > & OutBodies, FPhysScene * PhysScene = nullptr, USkeletalMeshComponent * OwningComponent = nullptr, int32 UseRootBodyIndex = INDEX_NONE, const FPhysicsAggregateHandle & UseAggregate = FPhysicsAggregateHandle()) const
Instantiates only the bodies given a physics asset, not the constraints.
The Created bodies are owned by the calling code and must be freed when necessary.
References INDEX_NONE.
InstantiatePhysicsAssetBodies_Internal()
void USkeletalMeshComponent::InstantiatePhysicsAssetBodies_Internal (const UPhysicsAsset & PhysAsset, TArray< FBodyInstance * > & OutBodies, TFunctionRef< FTransform(int32)> BoneTransformGetter, TMap< FName, FBodyInstance * > * OutNameToBodyMap = nullptr, FPhysScene * PhysScene = nullptr, USkeletalMeshComponent * OwningComponent = nullptr, int32 UseRootBodyIndex = INDEX_NONE, const FPhysicsAggregateHandle & UseAggregate = FPhysicsAggregateHandle()) const private
References INDEX_NONE.
InstantiatePhysicsAssetRefPose()
void USkeletalMeshComponent::InstantiatePhysicsAssetRefPose (const UPhysicsAsset & PhysAsset, const FVector & Scale3D, TArray< FBodyInstance * > & OutBodies, TArray< FConstraintInstance * > & OutConstraints, FPhysScene * PhysScene = nullptr, USkeletalMeshComponent * OwningComponent = nullptr, int32 UseRootBodyIndex = INDEX_NONE, const FPhysicsAggregateHandle & UseAggregate = FPhysicsAggregateHandle(), bool bCreateBodiesInRefPose = false) const
Instantiates bodies given a physics asset like InstantiatePhysicsAsset but instead of reading the current component state, this reads the ref-pose from the reference skeleton of the mesh.
Useful if trying to create bodies to be used during any evaluation work
References FVector, INDEX_NONE, and OutConstraints.
IsAnimBlueprintInstanced()
bool USkeletalMeshComponent::IsAnimBlueprintInstanced () const
IsAnyRigidBodyAwake()
virtual bool USkeletalMeshComponent::IsAnyRigidBodyAwake () override virtual
IsAnySimulatingPhysics()
virtual bool USkeletalMeshComponent::IsAnySimulatingPhysics () const override virtual
IsClothBoundToLeaderComponent()
bool USkeletalMeshComponent::IsClothBoundToLeaderComponent () const inline
Definition at line 1536 of file SkeletalMeshComponent.h.
References bBindClothToLeaderComponent.
Referenced by UE_DEPRECATED().
IsGravityEnabled()
virtual bool USkeletalMeshComponent::IsGravityEnabled () const override virtual
IsPlayingNetworkedRootMotionMontage()
virtual bool USkeletalMeshComponent::IsPlayingNetworkedRootMotionMontage () const override virtual
References const, and IsPlayingNetworkedRootMotionMontage().
Referenced by IsPlayingNetworkedRootMotionMontage().
IsPlayingRootMotion()
virtual bool USkeletalMeshComponent::IsPlayingRootMotion () const override virtual
References const, and IsPlayingRootMotion().
Referenced by IsPlayingRootMotion().
IsPlayingRootMotionFromEverything()
virtual bool USkeletalMeshComponent::IsPlayingRootMotionFromEverything () const override virtual
References const, and IsPlayingRootMotionFromEverything().
Referenced by IsPlayingRootMotionFromEverything().
IsPostEvaluatingAnimation()
bool USkeletalMeshComponent::IsPostEvaluatingAnimation () const inline
Definition at line 2793 of file SkeletalMeshComponent.h.
References bPostEvaluatingAnimation.
IsRunningParallelEvaluation()
bool USkeletalMeshComponent::IsRunningParallelEvaluation () const inline
Definition at line 2544 of file SkeletalMeshComponent.h.
References IsValidRef(), and ParallelAnimationEvaluationTask.
IsShown()
virtual bool USkeletalMeshComponent::IsShown (const FEngineShowFlags & ShowFlags) const override virtual
References const, and IsShown().
Referenced by IsShown().
IsSimulatingPhysics()
virtual bool USkeletalMeshComponent::IsSimulatingPhysics (FName BoneName = NAME_None) const override virtual
References BoneName.
IsWindEnabled()
virtual bool USkeletalMeshComponent::IsWindEnabled () const virtual
Returns
true if wind is enabled
LineTraceComponent()
virtual bool USkeletalMeshComponent::LineTraceComponent (FHitResult & OutHit, const FVector Start, const FVector End, const FCollisionQueryParams & Params) override virtual
References const, End, FVector, LineTraceComponent(), and Params.
Referenced by LineTraceComponent().
LoadedFromAnotherClass()
virtual void USkeletalMeshComponent::LoadedFromAnotherClass (const FName & OldClassName) override virtual
MarkRequiredCurveUpToDate()
void USkeletalMeshComponent::MarkRequiredCurveUpToDate () private
Mark current anim UID version to up-to-date.
Called when it's recalculated
MoveComponentImpl()
virtual bool USkeletalMeshComponent::MoveComponentImpl (const FVector & Delta, const FQuat & NewRotation, bool bSweep, FHitResult * OutHit = NULL, EMoveComponentFlags MoveFlags = MOVECOMP_NoFlags, ETeleportType Teleport = ETeleportType::None) override protected virtual
References FVector, and MOVECOMP_NoFlags.
NeedToSpawnAnimScriptInstance()
bool USkeletalMeshComponent::NeedToSpawnAnimScriptInstance () const protected
NeedToSpawnPostPhysicsInstance()
bool USkeletalMeshComponent::NeedToSpawnPostPhysicsInstance (bool bForceReinit) const protected
NotifySkelControlBeyondLimit()
virtual void USkeletalMeshComponent::NotifySkelControlBeyondLimit (class USkelControlLookAt * LookAt) virtual
Notifier when look at control goes beyond of limit - candidate for delegate.
References NotifySkelControlBeyondLimit().
Referenced by NotifySkelControlBeyondLimit().
OnClearAnimScriptInstance()
virtual void USkeletalMeshComponent::OnClearAnimScriptInstance () inline private virtual
Definition at line 2497 of file SkeletalMeshComponent.h.
OnComponentCollisionSettingsChanged()
virtual void USkeletalMeshComponent::OnComponentCollisionSettingsChanged (bool bUpdateOverlaps = true) override virtual
OnComponentDestroyed()
virtual void USkeletalMeshComponent::OnComponentDestroyed (bool bDestroyingHierarchy) override virtual
OnConstraintBrokenWrapper()
void USkeletalMeshComponent::OnConstraintBrokenWrapper (int32 ConstraintIndex) private
Wrapper that calls our constraint broken delegate.
OnCreatePhysicsState()
virtual void USkeletalMeshComponent::OnCreatePhysicsState () override protected virtual
OnDestroyPhysicsState()
virtual void USkeletalMeshComponent::OnDestroyPhysicsState () override protected virtual
OnPlasticDeformationWrapper()
void USkeletalMeshComponent::OnPlasticDeformationWrapper (int32 ConstraintIndex) private
Wrapper that calls our constraint plasticity delegate.
OnPreEndOfFrameSync()
virtual void USkeletalMeshComponent::OnPreEndOfFrameSync () override virtual
OnRegister()
virtual void USkeletalMeshComponent::OnRegister () override protected virtual
OnSyncComponentToRBPhysics()
virtual void USkeletalMeshComponent::OnSyncComponentToRBPhysics () inline protected virtual
Notify called just before syncing physics update, called only if bNotifySyncComponentToRBPhysics flag is set.
Definition at line 2491 of file SkeletalMeshComponent.h.
OnUnregister()
virtual void USkeletalMeshComponent::OnUnregister () override protected virtual
OnUpdateTransform()
virtual void USkeletalMeshComponent::OnUpdateTransform (EUpdateTransformFlags UpdateTransformFlags, ETeleportType Teleport = ETeleportType::None) override virtual
OverlapComponent()
virtual bool USkeletalMeshComponent::OverlapComponent (const FVector & Pos, const FQuat & Rot, const FCollisionShape & CollisionShape) const override virtual
References const, FVector, and OverlapComponent().
Referenced by OverlapComponent().
ParallelAnimationEvaluation()
void USkeletalMeshComponent::ParallelAnimationEvaluation ()
ParallelBlendPhysics()
void USkeletalMeshComponent::ParallelBlendPhysics () inline private
Definition at line 2600 of file SkeletalMeshComponent.h.
References AnimEvaluationContext, PerformBlendPhysicsBones(), and RequiredBones.
ParallelDuplicateAndInterpolate()
void USkeletalMeshComponent::ParallelDuplicateAndInterpolate (FAnimationEvaluationContext & InAnimEvaluationContext) private
Duplicates cached transforms/curves and performs interpolation.
PerformAnimationEvaluation()
void USkeletalMeshComponent::PerformAnimationEvaluation (const USkeletalMesh * InSkeletalMesh, UAnimInstance * InAnimInstance, TArray< FTransform > & OutSpaceBases, TArray< FTransform > & OutBoneSpaceTransforms, FVector & OutRootBoneTranslation, FBlendedHeapCurve & OutCurve, UE::Anim::FMeshAttributeContainer & OutAttributes)
Runs the animation evaluation for the current pose into the supplied variables PerformAnimationProcessing runs evaluation based on bInDoEvaluation.
PerformAnimationEvaluation always runs evaluation (and exists for backward compatibility)
Parameters
InSkeletalMesh The skeletal mesh we are animating
InAnimInstance The anim instance we are evaluating
bInDoEvaluation Whether to perform evaluation (we may just want to update)
OutSpaceBases Component space bone transforms
OutBoneSpaceTransforms Local space bone transforms
OutRootBoneTranslation Calculated root bone translation
OutCurves Blended Curve
References FVector, InAnimInstance, InSkeletalMesh, OutAttributes, OutBoneSpaceTransforms, OutCurve, OutRootBoneTranslation, OutSpaceBases, UAnimInstance, and USkeletalMesh.
PerformAnimationProcessing()
void USkeletalMeshComponent::PerformAnimationProcessing (const USkeletalMesh * InSkeletalMesh, UAnimInstance * InAnimInstance, bool bInDoEvaluation, bool bInForceRefPose, TArray< FTransform > & OutSpaceBases, TArray< FTransform > & OutBoneSpaceTransforms, FVector & OutRootBoneTranslation, FBlendedHeapCurve & OutCurve, UE::Anim::FMeshAttributeContainer & OutAttributes)
References bInDoEvaluation, FVector, InAnimInstance, InSkeletalMesh, OutAttributes, OutBoneSpaceTransforms, OutCurve, OutRootBoneTranslation, OutSpaceBases, UAnimInstance, and USkeletalMesh.
PerformBlendPhysicsBones()
void USkeletalMeshComponent::PerformBlendPhysicsBones (const TArray< FBoneIndexType > & InRequiredBones, TArray< FTransform > & InOutComponentSpaceTransforms, TArray< FTransform > & InOutBoneSpaceTransforms) private
Referenced by ParallelBlendPhysics(), and UE_DEPRECATED().
PoseTickedThisFrame()
bool USkeletalMeshComponent::PoseTickedThisFrame () const
Checked whether we have already ticked the pose this frame.
PostAnimEvaluation()
void USkeletalMeshComponent::PostAnimEvaluation (FAnimationEvaluationContext & EvaluationContext)
References PostAnimEvaluation().
Referenced by PostAnimEvaluation().
PostEditChangeProperty()
virtual void USkeletalMeshComponent::PostEditChangeProperty (FPropertyChangedEvent & PropertyChangedEvent) override virtual
PostInitProperties()
virtual void USkeletalMeshComponent::PostInitProperties () override virtual
References PostInitProperties().
Referenced by PostInitProperties().
PostLoad()
virtual void USkeletalMeshComponent::PostLoad () override virtual
References PostLoad().
Referenced by PostLoad().
ProcessClothCollisionWithEnvironment()
void USkeletalMeshComponent::ProcessClothCollisionWithEnvironment () protected
PutAllRigidBodiesToSleep()
virtual void USkeletalMeshComponent::PutAllRigidBodiesToSleep () override virtual
RecalcRequiredBones()
void USkeletalMeshComponent::RecalcRequiredBones (int32 LODIndex)
Recalculates the RequiredBones array in this SkeletalMeshComponent based on current SkeletalMesh, LOD and PhysicsAsset.
Is called when bRequiredBonesUpToDate = false
Parameters
LODIndex Index of LOD [0-(MaxLOD-1)]
References RecalcRequiredBones().
Referenced by RecalcRequiredBones().
RecalcRequiredCurves()
void USkeletalMeshComponent::RecalcRequiredCurves ()
Recalculates the AnimCurveUids array in RequiredBone of this SkeletalMeshComponent based on current required bone set Is called when Skeleton->IsRequiredCurvesUpToDate() = false.
References RecalcRequiredCurves().
Referenced by RecalcRequiredCurves().
RefreshBoneTransforms()
virtual void USkeletalMeshComponent::RefreshBoneTransforms (FActorComponentTickFunction * TickFunction = NULL) override virtual
RefreshMorphTargets()
virtual void USkeletalMeshComponent::RefreshMorphTargets () override private virtual
RefreshSkeletalMeshAsset()
void USkeletalMeshComponent::RefreshSkeletalMeshAsset ()
Sets the SkeletalMeshAsset to the current SkeletalMesh.
References RefreshSkeletalMeshAsset().
Referenced by RefreshSkeletalMeshAsset().
RegisterClothTick()
void USkeletalMeshComponent::RegisterClothTick (bool bRegister)
RegisterComponentTickFunctions()
virtual void USkeletalMeshComponent::RegisterComponentTickFunctions (bool bRegister) override protected virtual
RegisterEndPhysicsTick()
virtual void USkeletalMeshComponent::RegisterEndPhysicsTick (bool bRegister) virtual
RegisterOnBoneTransformsFinalizedDelegate()
virtual FDelegateHandle USkeletalMeshComponent::RegisterOnBoneTransformsFinalizedDelegate (const FOnBoneTransformsFinalizedMultiCast::FDelegate & Delegate) override virtual
Register/Unregister for OnBoneTransformsFinalized callback.
RegisterOnLODRequiredBonesUpdate_Member()
FDelegateHandle USkeletalMeshComponent::RegisterOnLODRequiredBonesUpdate_Member (const FOnLODRequiredBonesUpdate & Delegate) private
Register/Unregister for OnLODRequiredBonesUpdate callback.
References const, and RegisterOnLODRequiredBonesUpdate_Member().
Referenced by RegisterOnLODRequiredBonesUpdate_Member().
RegisterOnPhysicsCreatedDelegate()
FDelegateHandle USkeletalMeshComponent::RegisterOnPhysicsCreatedDelegate (const FOnSkelMeshPhysicsCreated & Delegate)
Register/Unregister for physics state creation callback.
RegisterOnSkeletalMeshPropertyChanged()
FDelegateHandle USkeletalMeshComponent::RegisterOnSkeletalMeshPropertyChanged (const FOnSkeletalMeshPropertyChanged & Delegate)
Register / Unregister delegates called when the skeletal mesh property is changed.
RegisterOnSkeletalMeshUnregistered()
FDelegateHandle USkeletalMeshComponent::RegisterOnSkeletalMeshUnregistered (const FOnSkeletalMeshUnregisteredDelegate & Delegate)
Register / Unregister delegates called when the mesh component is unregistered.
RegisterOnTeleportDelegate()
FDelegateHandle USkeletalMeshComponent::RegisterOnTeleportDelegate (const FOnSkelMeshTeleported & Delegate)
Register/Unregister for teleport callback.
ReleaseAllClothingResources()
void USkeletalMeshComponent::ReleaseAllClothingResources ()
Remove all clothing actors from their simulation and clear any other necessary clothing data to leave the simulations in a clean state.
References ReleaseAllClothingResources().
Referenced by ReleaseAllClothingResources().
RemoveAllClothingActors()
void USkeletalMeshComponent::RemoveAllClothingActors ()
Remove clothing actors from their simulation.
References RemoveAllClothingActors().
Referenced by RemoveAllClothingActors().
RemoveFollowerPoseComponent()
virtual void USkeletalMeshComponent::RemoveFollowerPoseComponent (USkinnedMeshComponent * SkinnedMeshComponent) override private virtual
ReportAnimNotifyError()
virtual void USkeletalMeshComponent::ReportAnimNotifyError (const FText & Error, UObject * InSourceNotify) inline virtual
Subclasses such as DebugSkelMeshComponent keep track of errors in the anim notifies so they can be displayed to the user.
This function adds an error. Errors are added uniquely and only removed when they're cleared by ClearAnimNotifyError.
Definition at line 1438 of file SkeletalMeshComponent.h.
References Error.
RequiresPreEndOfFrameSync()
virtual bool USkeletalMeshComponent::RequiresPreEndOfFrameSync () const override virtual
ResetLinkedAnimInstances()
PRAGMA_ENABLE_DEPRECATION_WARNINGS void USkeletalMeshComponent::ResetLinkedAnimInstances () private
Clear the linked anim instances and mark them pending kill.
ResetMorphTargetCurves()
void USkeletalMeshComponent::ResetMorphTargetCurves () private
ResetRootBodyIndex()
void USkeletalMeshComponent::ResetRootBodyIndex ()
Reset Root Body Index.
ResetToRefPose()
void USkeletalMeshComponent::ResetToRefPose () private
Internal helper - copies the mesh's reference pose to the local space transforms and regenerates component space transforms accordingly.
SendRenderDynamicData_Concurrent()
virtual void USkeletalMeshComponent::SendRenderDynamicData_Concurrent () override protected virtual
Serialize()
virtual void USkeletalMeshComponent::Serialize (FArchive & Ar) override virtual
References Ar, and Serialize().
Referenced by Serialize().
SetAllBodiesCollisionObjectType()
void USkeletalMeshComponent::SetAllBodiesCollisionObjectType (ECollisionChannel NewChannel)
Set the movement channel of all bodies.
References SetAllBodiesCollisionObjectType().
Referenced by SetAllBodiesCollisionObjectType().
SetAllBodiesNotifyRigidBodyCollision()
void USkeletalMeshComponent::SetAllBodiesNotifyRigidBodyCollision (bool bNewNotifyRigidBodyCollision)
Set the rigid body notification state for all bodies.
References SetAllBodiesNotifyRigidBodyCollision().
Referenced by SetAllBodiesNotifyRigidBodyCollision().
SetAllMassScale()
virtual void USkeletalMeshComponent::SetAllMassScale (float InMassScale = 1.f) override virtual
References SetAllMassScale().
Referenced by SetAllMassScale().
SetAllPhysicsAngularVelocityInRadians()
virtual void USkeletalMeshComponent::SetAllPhysicsAngularVelocityInRadians (FVector const & NewVel, bool bAddToCurrent = false) override virtual
References FVector.
SetAllPhysicsLinearVelocity()
virtual void USkeletalMeshComponent::SetAllPhysicsLinearVelocity (FVector NewVel, bool bAddToCurrent = false) override virtual
References FVector, and SetAllPhysicsLinearVelocity().
Referenced by SetAllPhysicsLinearVelocity().
SetAllPhysicsPosition()
virtual void USkeletalMeshComponent::SetAllPhysicsPosition (FVector NewPos) override virtual
References FVector.
SetAllPhysicsRotation() [1/2]
virtual void USkeletalMeshComponent::SetAllPhysicsRotation (const FQuat & NewRot) override virtual
SetAllPhysicsRotation() [2/2]
virtual void USkeletalMeshComponent::SetAllPhysicsRotation (FRotator NewRot) override virtual
SetAllUseCCD()
virtual void USkeletalMeshComponent::SetAllUseCCD (bool InUseCCD) override virtual
References SetAllUseCCD().
Referenced by SetAllUseCCD().
SetAnimInstanceClass_Internal()
void USkeletalMeshComponent::SetAnimInstanceClass_Internal (const TSubclassOf< UAnimInstance > & InAnimClass) private
References const, SetAnimInstanceClass_Internal(), and UAnimInstance.
Referenced by SetAnimInstanceClass_Internal(), and UPROPERTY().
SetCollisionObjectType()
virtual void USkeletalMeshComponent::SetCollisionObjectType (ECollisionChannel Channel) override virtual
Set the collision object type on the skeletal mesh.
References SetCollisionObjectType().
Referenced by SetCollisionObjectType().
SetComponentTickEnabled()
virtual void USkeletalMeshComponent::SetComponentTickEnabled (bool bEnabled) override virtual
SetEnableGravity()
virtual void USkeletalMeshComponent::SetEnableGravity (bool bGravityEnabled) virtual
SetForceRefPose()
void USkeletalMeshComponent::SetForceRefPose (bool bNewForceRefPose)
Change whether to force mesh into ref pose (and use cheaper vertex shader)
Parameters
bNewForceRefPose true if it would like to force ref pose
References SetForceRefPose().
Referenced by SetForceRefPose().
SetNamedMotorsAngularPositionDrive()
void USkeletalMeshComponent::SetNamedMotorsAngularPositionDrive (bool bEnableSwingDrive, bool bEnableTwistDrive, const TArray< FName > & BoneNames, bool bSetOtherBodiesToComplement = false)
Enable or Disable AngularPositionDrive based on a list of bone names.
References bEnableTwistDrive, const, and SetNamedMotorsAngularPositionDrive().
Referenced by SetNamedMotorsAngularPositionDrive().
SetNamedMotorsAngularVelocityDrive()
void USkeletalMeshComponent::SetNamedMotorsAngularVelocityDrive (bool bEnableSwingDrive, bool bEnableTwistDrive, const TArray< FName > & BoneNames, bool bSetOtherBodiesToComplement = false)
Enable or Disable AngularVelocityDrive based on a list of bone names.
References bEnableTwistDrive, const, and SetNamedMotorsAngularVelocityDrive().
Referenced by SetNamedMotorsAngularVelocityDrive().
SetNotifyRigidBodyCollision()
virtual void USkeletalMeshComponent::SetNotifyRigidBodyCollision (bool bNewNotifyRigidBodyCollision) override virtual
Changes the value of bNotifyRigidBodyCollision.
Parameters
bNewNotifyRigidBodyCollision - The value to assign to bNotifyRigidBodyCollision
SetPhysicsAsset()
virtual void USkeletalMeshComponent::SetPhysicsAsset (class UPhysicsAsset * NewPhysicsAsset, bool bForceReInit = false) override virtual
SetPhysMaterialOverride()
virtual void USkeletalMeshComponent::SetPhysMaterialOverride (UPhysicalMaterial * NewPhysMaterial) override virtual
SetPredictedLODLevel()
virtual void USkeletalMeshComponent::SetPredictedLODLevel (int32 InPredictedLODLevel) override virtual
SetRefPoseOverride()
virtual void USkeletalMeshComponent::SetRefPoseOverride (const TArray< FTransform > & NewRefPoseTransforms) override virtual
References const, and SetRefPoseOverride().
Referenced by SetRefPoseOverride().
SetRootBodyIndex()
void USkeletalMeshComponent::SetRootBodyIndex (int32 InBodyIndex)
Set Root Body Index.
SetSimulatePhysics()
virtual void USkeletalMeshComponent::SetSimulatePhysics (bool bEnabled) override virtual
References SetSimulatePhysics().
Referenced by SetSimulatePhysics().
SetSkeletalMesh()
virtual void USkeletalMeshComponent::SetSkeletalMesh (class USkeletalMesh * NewMesh, bool bReinitPose = true) override virtual
References USkeletalMesh.
Referenced by UFUNCTION().
SetSkinnedAssetAndUpdate()
virtual void USkeletalMeshComponent::SetSkinnedAssetAndUpdate (class USkinnedAsset * InSkinnedAsset, bool bReinitPose = true) override virtual
Set the new asset to render and update this component (this function is identical to SetSkeletalMesh).
The USkinnedAsset pointer is first cast to a USkeletalMesh, therefore this function will only set assets of type USkeletalMesh.
Parameters
InSkinnedAsset The new asset.
bReinitPose Whether to re-initialize the animation.
ShouldBlendPhysicsBones()
virtual bool USkeletalMeshComponent::ShouldBlendPhysicsBones () const protected virtual
ShouldCreatePhysicsState()
virtual bool USkeletalMeshComponent::ShouldCreatePhysicsState () const override protected virtual
ShouldEvaluatePostProcessAnimBP()
bool USkeletalMeshComponent::ShouldEvaluatePostProcessAnimBP () const
References const, and ShouldEvaluatePostProcessAnimBP().
Referenced by ShouldEvaluatePostProcessAnimBP().
ShouldEvaluatePostProcessInstance()
bool USkeletalMeshComponent::ShouldEvaluatePostProcessInstance () const
References const, and ShouldEvaluatePostProcessInstance().
Referenced by ShouldEvaluatePostProcessInstance().
ShouldOnlyTickMontages()
bool USkeletalMeshComponent::ShouldOnlyTickMontages (const float DeltaTime) const
If VisibilityBasedAnimTickOption == EVisibilityBasedAnimTickOption::OnlyTickMontagesWhenNotRendered Should we tick Montages only?
References DeltaTime.
ShouldOnlyTickMontagesAndRefreshBones()
bool USkeletalMeshComponent::ShouldOnlyTickMontagesAndRefreshBones (const float DeltaTime) const
References DeltaTime.
ShouldPostUpdatePostProcessInstance()
bool USkeletalMeshComponent::ShouldPostUpdatePostProcessInstance () const
References const, and ShouldPostUpdatePostProcessInstance().
Referenced by ShouldPostUpdatePostProcessInstance().
ShouldRunClothTick()
virtual bool USkeletalMeshComponent::ShouldRunClothTick () const protected virtual
ShouldRunEndPhysicsTick()
bool USkeletalMeshComponent::ShouldRunEndPhysicsTick () const private
ShouldTickAnimation()
bool USkeletalMeshComponent::ShouldTickAnimation () const
Returns
whether we should tick animation (we may want to skip it due to URO)
ShouldTickPose()
virtual bool USkeletalMeshComponent::ShouldTickPose () const override virtual
ShouldUpdatePostProcessInstance()
bool USkeletalMeshComponent::ShouldUpdatePostProcessInstance () const
References const, and ShouldUpdatePostProcessInstance().
Referenced by ShouldUpdatePostProcessInstance().
ShouldUpdateTransform()
virtual bool USkeletalMeshComponent::ShouldUpdateTransform (bool bLODHasChanged) const override virtual
ShouldWaitForClothInTickFunction()
bool USkeletalMeshComponent::ShouldWaitForClothInTickFunction () const private
Whether we should stall the Cloth tick task until the cloth simulation is complete.
This is required if we want up-to-date cloth data on the game thread, for example if we want to generate particles at cloth vertices. When the data is not required except for rendering, we can set this to false to eliminate a potential game thread stall while we wait for the cloth sim
SkelMeshCompOnParticleSystemFinished()
virtual void USkeletalMeshComponent::SkelMeshCompOnParticleSystemFinished (class UParticleSystemComponent * PSC) virtual
We detach the Component once we are done playing it.
Parameters
ParticleSystemComponent that finished
SwapEvaluationContextBuffers()
void USkeletalMeshComponent::SwapEvaluationContextBuffers () private
Swaps buffers into the evaluation context before and after task dispatch.
SweepComponent()
virtual bool USkeletalMeshComponent::SweepComponent (FHitResult & OutHit, const FVector Start, const FVector End, const FQuat & ShapRotation, const FCollisionShape & CollisionShape, bool bTraceComplex = false) override virtual
Trace a shape against just this component.
Will trace against each body, returning as soon as any collision is found. Note that this collision may not be the closest.
Parameters
OutHit Information about hit against this component, if true is returned
Start Start location of the trace
End End location of the trace
ShapeWorldRotation The rotation applied to the collision shape in world space
CollisionShape Collision Shape
bTraceComplex Whether or not to trace complex
Returns
true if a hit is found
References const, End, FVector, and SweepComponent().
Referenced by SweepComponent().
TermArticulated()
void USkeletalMeshComponent::TermArticulated ()
Turn off all physics and remove the instance.
TermCollisionRelationships()
void USkeletalMeshComponent::TermCollisionRelationships ()
References TermCollisionRelationships().
Referenced by TermCollisionRelationships().
TickAnimation()
void USkeletalMeshComponent::TickAnimation (float DeltaTime, bool bNeedsValidRootMotion)
Tick Animation system.
References DeltaTime.
TickAnimInstances()
void USkeletalMeshComponent::TickAnimInstances (float DeltaTime, bool bNeedsValidRootMotion)
Tick all of our anim instances (linked instances, main instance and post process)
References DeltaTime.
TickClothing()
void USkeletalMeshComponent::TickClothing (float DeltaTime, FTickFunction & ThisTickFunction)
Tick Clothing Animation , basically this is called inside TickComponent.
References DeltaTime.
TickComponent()
virtual void USkeletalMeshComponent::TickComponent (float DeltaTime, enum ELevelTick TickType, FActorComponentTickFunction * ThisTickFunction) override virtual
References DeltaTime.
TickPose()
virtual void USkeletalMeshComponent::TickPose (float DeltaTime, bool bNeedsValidRootMotion) override virtual
References DeltaTime.
UE_DEPRECATED() [1/31]
USkeletalMeshComponent::UE_DEPRECATED (4. 18, "This function is deprecated. Please use GetAllowedAnimCurveEvaluate instead. Note that the meaning is reversed.") const inline
Definition at line 1390 of file SkeletalMeshComponent.h.
References Category, UE_DEPRECATED(), and UFUNCTION().
UE_DEPRECATED() [2/31]
USkeletalMeshComponent::UE_DEPRECATED (4. 18, "This function is deprecated. Please use SetAllowAnimCurveEvaluation instead. Note that the meaning is reversed.")
References Category, and UFUNCTION().
UE_DEPRECATED() [3/31]
USkeletalMeshComponent::UE_DEPRECATED (4. 23, "Direct access to this property is deprecated, please use GetBoneSpaceTransforms instead. We will move to private in the future.")
Temporary array of local-space (relative to parent bone) rotation/translation for each bone.
This property is not safe to access during evaluation, so we created wrapper.
References UE_DEPRECATED().
Referenced by GetSharedRequiredBones(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
UE_DEPRECATED() [4/31]
USkeletalMeshComponent::UE_DEPRECATED (4. 23, "This function is deprecated. Please use GetLinkedAnimGraphInstanceByTag") const inline
Definition at line 1052 of file SkeletalMeshComponent.h.
References UAnimInstance.
UE_DEPRECATED() [5/31]
USkeletalMeshComponent::UE_DEPRECATED (4. 23, "This function is deprecated. Please use SetAnimInstanceClass instead. ")
UE_DEPRECATED() [6/31]
USkeletalMeshComponent::UE_DEPRECATED (4. 24, "Function renamed, please use GetLinkedAnimGraphInstancesByTag")
References UE_DEPRECATED().
UE_DEPRECATED() [7/31]
USkeletalMeshComponent::UE_DEPRECATED (4. 24, "Function renamed, please use GetLinkedAnimLayerInstanceByClass") const inline
Definition at line 1117 of file SkeletalMeshComponent.h.
References InClass, UAnimInstance, and UE_DEPRECATED().
UE_DEPRECATED() [8/31]
USkeletalMeshComponent::UE_DEPRECATED (4. 24, "Function renamed, please use GetLinkedLayerInstanceByGroup") const inline
Definition at line 1110 of file SkeletalMeshComponent.h.
References UAnimInstance, and UE_DEPRECATED().
UE_DEPRECATED() [9/31]
USkeletalMeshComponent::UE_DEPRECATED (4. 24, "Function renamed, please use LinkAnimClassLayers") inline
Definition at line 1087 of file SkeletalMeshComponent.h.
References InClass, UAnimInstance, and UE_DEPRECATED().
UE_DEPRECATED() [10/31]
USkeletalMeshComponent::UE_DEPRECATED (4. 24, "Function renamed, please use LinkAnimGraphByTag")
References UE_DEPRECATED().
UE_DEPRECATED() [11/31]
USkeletalMeshComponent::UE_DEPRECATED (4. 24, "Function renamed, please use UnlinkAnimClassLayers") inline
Definition at line 1099 of file SkeletalMeshComponent.h.
References InClass, UAnimInstance, and UE_DEPRECATED().
UE_DEPRECATED() [12/31]
USkeletalMeshComponent::UE_DEPRECATED (4. 24, "This function is deprecated. Please use GetLinkedAnimGraphInstanceByTag") const inline
Definition at line 1055 of file SkeletalMeshComponent.h.
References UAnimInstance.
UE_DEPRECATED() [13/31]
USkeletalMeshComponent::UE_DEPRECATED (4. 26, "Please use PerformAnimationEvaluation with different signature") const
UE_DEPRECATED() [14/31]
USkeletalMeshComponent::UE_DEPRECATED (4. 26, "Public access to this function is deprecated. Please use the mechanism provided in USkeletalMeshComponent::EndPhysicsTickComponent") & inline
Take the results of the physics and blend them with the animation state (based on the PhysicsWeight parameter), and update the SpaceBases array.
Definition at line 2130 of file SkeletalMeshComponent.h.
References BlendInPhysicsInternal().
UE_DEPRECATED() [15/31]
USkeletalMeshComponent::UE_DEPRECATED (4. 26, "This function is deprecated and should not be called directly. Please use the mechanism provided in USkeletalMeshComponent::EndPhysicsTickComponent") & inline
Blend of Physics Bones with PhysicsWeight and Animated Bones with (1-PhysicsWeight)
Parameters
RequiredBones List of bones to be blend
Definition at line 2122 of file SkeletalMeshComponent.h.
References AnimEvaluationContext, PerformBlendPhysicsBones(), and UE_DEPRECATED().
UE_DEPRECATED() [16/31]
PRAGMA_ENABLE_DEPRECATION_WARNINGS USkeletalMeshComponent::UE_DEPRECATED (5. 0, "Tags are unique so this funciton is no longer supported. Please use GetLinkedAnimGraphInstanceByTag instead")
Returns all tagged linked instance nodes that match the tag.
References Category, Keywords, meta, and UFUNCTION().
UE_DEPRECATED() [17/31]
USkeletalMeshComponent::UE_DEPRECATED (5. 1, "This method has been deprecated. Please use BindClothToLeaderPoseComponent instead.") inline
Definition at line 1331 of file SkeletalMeshComponent.h.
References UE_DEPRECATED().
UE_DEPRECATED() [18/31]
USkeletalMeshComponent::UE_DEPRECATED (5. 1, "This method has been deprecated. Please use SetSkeletalMesh(NewMesh, false) instead.")
References USkeletalMesh.
UE_DEPRECATED() [19/31]
USkeletalMeshComponent::UE_DEPRECATED (5. 1, "This method has been deprecated. Please use UnbindClothFromLeaderPoseComponent instead.")
References UE_DEPRECATED().
UE_DEPRECATED() [20/31]
USkeletalMeshComponent::UE_DEPRECATED (5. 1, "This method has been deprecated. Please use UpdateFollowerComponent instead.") inline override
Definition at line 2027 of file SkeletalMeshComponent.h.
References UpdateFollowerComponent().
UE_DEPRECATED() [21/31]
USkeletalMeshComponent::UE_DEPRECATED (5. 1, "This method has been deprecated. Please, use IsClothBoundToLeaderComponent instead.") const inline
Definition at line 1538 of file SkeletalMeshComponent.h.
References bool, and IsClothBoundToLeaderComponent().
UE_DEPRECATED() [22/31]
USkeletalMeshComponent::UE_DEPRECATED (5. 2, "Use GetUpdateClothSimulationData_AnyThread instead.")
Store cloth simulation data into OutClothSimData.
UE_DEPRECATED() [23/31]
USkeletalMeshComponent::UE_DEPRECATED (5. 3, "Please use GetCurveFilterSettings") const & inline
Definition at line 1411 of file SkeletalMeshComponent.h.
References const, and UE_DEPRECATED().
UE_DEPRECATED() [24/31]
USkeletalMeshComponent::UE_DEPRECATED (5. 3, "This method has been deprecated. Please use UMirrorDataTable for mirroring support.") const
References UE_DEPRECATED().
UE_DEPRECATED() [25/31]
USkeletalMeshComponent::UE_DEPRECATED (5. 5, "Please use EvaluatePostProcessMeshInstance with different signature") &
References UE_DEPRECATED().
UE_DEPRECATED() [26/31]
USkeletalMeshComponent::UE_DEPRECATED (5. 5, "Please use PerformAnimationEvaluation with different signature") const
UE_DEPRECATED() [27/31]
USkeletalMeshComponent::UE_DEPRECATED (5. 5, "This function has been renamed RemoveClothCollisionSources") inline
Remove a cloth collision source defined by a component.
Definition at line 2441 of file SkeletalMeshComponent.h.
References UE_DEPRECATED().
UE_DEPRECATED() [28/31]
USkeletalMeshComponent::UE_DEPRECATED (5. 5, "This function is deprecated. Please use 'SetAnimInstanceClass' instead. ")
Set the anim instance class.
Clears and re-initializes the anim instance with the new class and sets animation mode to 'AnimationBlueprint'
References UE_DEPRECATED().
UE_DEPRECATED() [29/31]
USkeletalMeshComponent::UE_DEPRECATED (5. 6, "Direct access to this property is deprecated, please use GetAnimCurves or GetCurveValue instead. We will move to private in the future.")
References UE_DEPRECATED().
UE_DEPRECATED() [30/31]
USkeletalMeshComponent::UE_DEPRECATED (5. 6, "These should not be used as they rely on a global delegate, ANY change in LOD from ANY skeletal mesh component triggers the callback") const &
Register/Unregister for OnLODRequiredBonesUpdate callback.
References const.
UE_DEPRECATED() [31/31]
USkeletalMeshComponent::UE_DEPRECATED (5. 6, "These should not be used as they rely on a global delegate, ANY change in LOD from ANY skeletal mesh component triggers the callback") const &
References const, and UE_DEPRECATED().
UFUNCTION() [1/110]
USkeletalMeshComponent::UFUNCTION ()
Get curve value.
Parameters
CurveName Name of the curve to retrieve
DefaultValue In case the curve could not be found
Value Retrieved curve value if found, otherwise is set to DefaultValue
Returns
Whether the curve was successfully retrieved
References Category, and UFUNCTION().
UFUNCTION() [2/110]
USkeletalMeshComponent::UFUNCTION () const
Gets whether the post process blueprint is currently disabled for this component.
References const, and UFUNCTION().
UFUNCTION() [3/110]
USkeletalMeshComponent::UFUNCTION () const &
Get float type attribute value.
Parameters
BoneName Name of the bone to retrieve try and retrieve the attribute from
AttributeName Name of the attribute to retrieve
DefaultValue In case the attribute could not be found
OutValue Retrieved attribute value if found, otherwise is set to DefaultValue
LookupType Determines how the attribute is retrieved from the specified BoneName (see ECustomBoneAttributeLookup)
Returns
Whether or not the atttribute was successfully retrieved
References Category, CustomAttributes, and UFUNCTION().
UFUNCTION() [4/110]
USkeletalMeshComponent::UFUNCTION () const &
Get float type attribute value.
Parameters
BoneName Name of the bone to retrieve try and retrieve the attribute from
AttributeName Name of the attribute to retrieve
OutValue (reference) Retrieved attribute value if found, otherwise is set to DefaultValue
LookupType Determines how the attribute is retrieved from the specified BoneName (see ECustomBoneAttributeLookup)
Returns
Whether or not the atttribute was successfully retrieved
References Category, CustomAttributes, and UFUNCTION().
UFUNCTION() [5/110]
USkeletalMeshComponent::UFUNCTION () const &
Get integer type attribute value.
Parameters
BoneName Name of the bone to retrieve try and retrieve the attribute from
AttributeName Name of the attribute to retrieve
DefaultValue In case the attribute could not be found
OutValue Retrieved attribute value if found, otherwise is set to DefaultValue
LookupType Determines how the attribute is retrieved from the specified BoneName (see ECustomBoneAttributeLookup)
Returns
Whether or not the atttribute was successfully retrieved
References Category, CustomAttributes, and UFUNCTION().
UFUNCTION() [6/110]
USkeletalMeshComponent::UFUNCTION () const &
Get integer type attribute value.
Parameters
BoneName Name of the bone to retrieve try and retrieve the attribute from
AttributeName Name of the attribute to retrieve
OutValue (reference) Retrieved attribute value if found, otherwise is set to DefaultValue
LookupType Determines how the attribute is retrieved from the specified BoneName (see ECustomBoneAttributeLookup)
Returns
Whether or not the atttribute was successfully retrieved
References Category, CustomAttributes, and UFUNCTION().
UFUNCTION() [7/110]
USkeletalMeshComponent::UFUNCTION () const &
Get string type attribute value.
Parameters
BoneName Name of the bone to retrieve try and retrieve the attribute from
AttributeName Name of the attribute to retrieve
DefaultValue In case the attribute could not be found
OutValue Retrieved attribute value if found, otherwise is set to DefaultValue
LookupType Determines how the attribute is retrieved from the specified BoneName (see ECustomBoneAttributeLookup)
Returns
Whether or not the atttribute was successfully retrieved
References Category, CustomAttributes, and UFUNCTION().
UFUNCTION() [8/110]
USkeletalMeshComponent::UFUNCTION () const &
Get string type attribute value.
Parameters
BoneName Name of the bone to retrieve try and retrieve the attribute from
AttributeName Name of the attribute to retrieve
OutValue (reference) Retrieved attribute value if found, otherwise is set to DefaultValue
LookupType Determines how the attribute is retrieved from the specified BoneName (see ECustomBoneAttributeLookup)
Returns
Whether or not the atttribute was successfully retrieved
References Category, CustomAttributes, and UFUNCTION().
UFUNCTION() [9/110]
USkeletalMeshComponent::UFUNCTION () const &
Get FTransform type attribute value.
Parameters
BoneName Name of the bone to retrieve try and retrieve the attribute from
AttributeName Name of the attribute to retrieve
OutValue (reference) Retrieved attribute value if found, otherwise is set to DefaultValue
LookupType Determines how the attribute is retrieved from the specified BoneName (see ECustomBoneAttributeLookup)
Returns
Whether or not the atttribute was successfully retrieved
References Category, CustomAttributes, and UFUNCTION().
UFUNCTION() [10/110]
USkeletalMeshComponent::UFUNCTION () const &
Get FTransform type attribute value.
Parameters
BoneName Name of the bone to retrieve try and retrieve the attribute from
AttributeName Name of the attribute to retrieve
OutValue (reference) Retrieved attribute value if found, otherwise is set to DefaultValue
LookupType Determines how the attribute is retrieved from the specified BoneName (see ECustomBoneAttributeLookup)
Returns
Whether or not the atttribute was successfully retrieved
References Category, CustomAttributes, and UFUNCTION().
UFUNCTION() [11/110]
USkeletalMeshComponent::UFUNCTION ()
Checks whether or not gravity is enabled on the given bone.
NAME_None indicates the root body should be queried. If the bone name given is otherwise invalid, false is returned.
Parameters
BoneName The name of the bone to check.
Returns
True if gravity is enabled on the bone.
References BoneName, Category, and UFUNCTION().
UFUNCTION() [12/110]
USkeletalMeshComponent::UFUNCTION () const
Gets whether or not the clothing simulation is currently suspended.
References Category, const, and UFUNCTION().
UFUNCTION() [13/110]
USkeletalMeshComponent::UFUNCTION ()
Get the anim instance class via getter callable by sequencer.
References UFUNCTION().
UFUNCTION() [14/110]
USkeletalMeshComponent::UFUNCTION ()
Returns the mass (in kg) of the given bone.
Parameters
BoneName Name of the body to return. 'None' indicates root body.
bScaleMass If true, the mass is scaled by the bone's MassScale.
References Category, and UFUNCTION().
UFUNCTION() [15/110]
USkeletalMeshComponent::UFUNCTION () const
Get/Set the max distance scale of clothing mesh vertices.
References Category, and const.
UFUNCTION() [16/110]
USkeletalMeshComponent::UFUNCTION () const
Get Morph target with given name.
References Category, const, and UFUNCTION().
UFUNCTION() [17/110]
USkeletalMeshComponent::UFUNCTION () const
Gets the teleportation distance threshold.
Returns
Threshold value.
References Category.
UFUNCTION() [18/110]
USkeletalMeshComponent::UFUNCTION () const
Gets the teleportation rotation threshold.
Returns
Threshold in degrees.
References Category.
UFUNCTION() [19/110]
USkeletalMeshComponent::UFUNCTION ()
Find Constraint Name from index.
Parameters
ConstraintIndex Index of constraint to look for
Returns
Constraint Joint Name
References Category, and UFUNCTION().
UFUNCTION() [20/110]
USkeletalMeshComponent::UFUNCTION () const &
References Category, const, FVector, InBoneName, and UFUNCTION().
UFUNCTION() [21/110]
USkeletalMeshComponent::UFUNCTION () const
Returns the center of mass of the skeletal mesh, instead of the root body's location.
References Category, const, FVector, and UFUNCTION().
UFUNCTION() [22/110]
USkeletalMeshComponent::UFUNCTION () const
References Category, and const.
UFUNCTION() [23/110]
USkeletalMeshComponent::UFUNCTION () const
UFUNCTION() [24/110]
USkeletalMeshComponent::UFUNCTION () const
Get the current interactor for a clothing simulation, if the current simulation supports runtime interaction.
References Category.
UFUNCTION() [25/110]
USkeletalMeshComponent::UFUNCTION () const
Get the SkeletalMesh rendered for this mesh.
References Category, const, and USkeletalMesh.
UFUNCTION() [26/110]
USkeletalMeshComponent::UFUNCTION ()
Add a force to all rigid bodies below.
This is like a 'thruster'. Good for adding a burst over some (non zero) time. Should be called every frame for the duration of the force.
Parameters
Force Force vector to apply. Magnitude indicates strength of force.
BoneName If a SkeletalMeshComponent, name of body to apply force to. 'None' indicates root body.
bAccelChange If true, Force is taken as a change in acceleration instead of a physical force (i.e. mass will have no effect).
bIncludeSelf If false, Force is only applied to bodies below but not given bone name.
References Category, and UFUNCTION().
UFUNCTION() [27/110]
USkeletalMeshComponent::UFUNCTION ()
Add impulse to all single rigid bodies below.
Good for one time instant burst.
Parameters
Impulse Magnitude and direction of impulse to apply.
BoneName If a SkeletalMeshComponent, name of body to apply impulse to. 'None' indicates root body.
bVelChange If true, the Strength is taken as a change in velocity instead of an impulse (ie. mass will have no effect).
bIncludeSelf If false, Force is only applied to bodies below but not given bone name.
References Category, and UFUNCTION().
UFUNCTION() [28/110]
USkeletalMeshComponent::UFUNCTION ()
Changes the value of bNotifyRigidBodyCollision for a given body.
Parameters
bNewNotifyRigidBodyCollision The value to assign to bNotifyRigidBodyCollision
BoneName Name of the body to turn hit notifies on/off. None implies root body
References Category.
UFUNCTION() [29/110]
USkeletalMeshComponent::UFUNCTION ()
Changes the value of bNotifyRigidBodyCollision on all bodies below a given bone.
Parameters
bNewNotifyRigidBodyCollision The value to assign to bNotifyRigidBodyCollision
BoneName Name of the body to turn hit notifies on (and below)
bIncludeSelf Whether to modify the given body (useful for roots with multiple children)
References Category, and UFUNCTION().
UFUNCTION() [30/110]
USkeletalMeshComponent::UFUNCTION () const &
Accumulate AddPhysicsBlendWeight to physics blendweight for all of the bones below passed in bone to be simulated.
References Category, and UFUNCTION().
UFUNCTION() [31/110]
USkeletalMeshComponent::UFUNCTION ()
Add a collision source for the cloth on this component.
Each cloth tick, the collision defined by the physics asset, transformed by the bones in the source component, will be applied to cloth.
Parameters
InSourceComponent The component to extract collision transforms from
InSourcePhysicsAsset The physics asset that defines the collision primitives (that will be transformed by InSourceComponent's bones)
References Category.
UFUNCTION() [32/110]
USkeletalMeshComponent::UFUNCTION ()
References Category.
UFUNCTION() [33/110]
USkeletalMeshComponent::UFUNCTION ()
Clear all Morph Target that are set to this mesh.
References Category, and UFUNCTION().
UFUNCTION() [34/110]
USkeletalMeshComponent::UFUNCTION ()
Used to indicate we should force 'teleport' during the next call to UpdateClothState, This will transform positions and velocities and thus keep the simulation state, just translate it to a new pose.
References Category, and UFUNCTION().
UFUNCTION() [35/110]
USkeletalMeshComponent::UFUNCTION ()
Used to indicate we should force 'teleport and reset' during the next call to UpdateClothState.
This can be used to reset it from a bad state or by a teleport where the old state is not important anymore.
References Category, and UFUNCTION().
UFUNCTION() [36/110]
USkeletalMeshComponent::UFUNCTION ()
Gets the current Angular state for a named bone constraint.
Parameters
InBoneName Name of bone to get constraint ranges for
Swing1Angle current angular state of the constraint
TwistAngle current angular state of the constraint
Swing2Angle current angular state of the constraint
References Category, and UFUNCTION().
UFUNCTION() [37/110]
USkeletalMeshComponent::UFUNCTION ()
Destroys and recreates the clothing actors in the current simulation.
References Category, and UFUNCTION().
UFUNCTION() [38/110]
USkeletalMeshComponent::UFUNCTION ()
Remove a cloth collision source defined by both a component and a physics asset.
References Category, and InSourcePhysicsAsset.
UFUNCTION() [39/110]
USkeletalMeshComponent::UFUNCTION ()
Remove a cloth collision source defined by a component.
References Category, and UFUNCTION().
UFUNCTION() [40/110]
USkeletalMeshComponent::UFUNCTION ()
Allows you to reset bodies Simulate state based on where bUsePhysics is set to true in the BodySetup.
References Category, and UFUNCTION().
UFUNCTION() [41/110]
USkeletalMeshComponent::UFUNCTION ()
By reset, it will allow all the curves to be evaluated.
References Category, and UFUNCTION().
UFUNCTION() [42/110]
USkeletalMeshComponent::UFUNCTION ()
Remove all cloth collision sources.
References Category, and UFUNCTION().
UFUNCTION() [43/110]
USkeletalMeshComponent::UFUNCTION ()
Reset the teleport mode of a next update to 'Continuous'.
References Category, and UFUNCTION().
UFUNCTION() [44/110]
USkeletalMeshComponent::UFUNCTION () const &
set the linear velocity of the child bodies to match that of the given parent bone
References Category, and UFUNCTION().
UFUNCTION() [45/110]
USkeletalMeshComponent::UFUNCTION () const &
Set all of the bones below passed in bone to be simulated.
References Category, and UFUNCTION().
UFUNCTION() [46/110]
USkeletalMeshComponent::UFUNCTION () const &
[WARNING: Chaos Only] Set all of the bones below passed in bone to be disabled or not for the associated physics solver Bodies will not be colliding or be part of the physics simulation.
This is different from SetAllBodiesBelowSimulatePhysics that changes bodies to Kinematic/simulated
References Category, and UFUNCTION().
UFUNCTION() [47/110]
USkeletalMeshComponent::UFUNCTION () const &
Set all of the bones below passed in bone to be simulated.
References Category, and UFUNCTION().
UFUNCTION() [48/110]
USkeletalMeshComponent::UFUNCTION ()
References Category, and UFUNCTION().
UFUNCTION() [49/110]
USkeletalMeshComponent::UFUNCTION ()
Set bSimulatePhysics to true for all bone bodies.
Does not change the component bSimulatePhysics flag.
References bNewSimulate, Category, and UFUNCTION().
UFUNCTION() [50/110]
USkeletalMeshComponent::UFUNCTION ()
Set Angular Drive motors params for all constraint instances.
References Category, and UFUNCTION().
UFUNCTION() [51/110]
USkeletalMeshComponent::UFUNCTION ()
Enable or Disable AngularPositionDrive.
If motor is in SLERP mode it will be turned on if either EnableSwingDrive OR EnableTwistDrive are enabled. In Twist and Swing mode the twist and the swing can be controlled individually.
References Category, and UFUNCTION().
UFUNCTION() [52/110]
USkeletalMeshComponent::UFUNCTION ()
Enable or Disable AngularVelocityDrive.
If motor is in SLERP mode it will be turned on if either EnableSwingDrive OR EnableTwistDrive are enabled. In Twist and Swing mode the twist and the swing can be controlled individually.
References bEnableTwistDrive, bSkipCustomPhysicsType, Category, and UFUNCTION().
UFUNCTION() [53/110]
USkeletalMeshComponent::UFUNCTION ()
References Category.
UFUNCTION() [54/110]
USkeletalMeshComponent::UFUNCTION ()
Sets whether cloth assets should be created/simulated in this component.
This will update the conditional flag and you will want to call RecreateClothingActors for it to take effect.
Parameters
bInAllow Whether to allow the creation of cloth assets and simulation.
References Category, and UFUNCTION().
UFUNCTION() [55/110]
USkeletalMeshComponent::UFUNCTION () const &
resets, and then only allow the following list to be allowed/disallowed
References bAllow, Category, const, and UFUNCTION().
UFUNCTION() [56/110]
USkeletalMeshComponent::UFUNCTION ()
Sets the Angular Motion Ranges for a named constraint.
Parameters
InBoneName Name of bone to adjust constraint ranges for
Swing1LimitAngle Size of limit in degrees, 0 means locked, 180 means free
TwistLimitAngle Size of limit in degrees, 0 means locked, 180 means free
Swing2LimitAngle Size of limit in degrees, 0 means locked, 180 means free
References Category, and UFUNCTION().
UFUNCTION() [57/110]
USkeletalMeshComponent::UFUNCTION () const &
Set a single bone to be simulated (or not)
References Category, and UFUNCTION().
UFUNCTION() [58/110]
USkeletalMeshComponent::UFUNCTION ()
References Category, Scale, and UFUNCTION().
UFUNCTION() [59/110]
USkeletalMeshComponent::UFUNCTION ()
Sets the constraint profile properties (limits, motors, etc...) to match the constraint profile as defined in the physics asset.
If profile name is not found the joint is set to use the default constraint profile.
References Category, and UFUNCTION().
UFUNCTION() [60/110]
USkeletalMeshComponent::UFUNCTION ()
Sets the constraint profile properties (limits, motors, etc...) to match the constraint profile as defined in the physics asset for all constraints.
If profile name is not found the joint is set to use the default constraint profile.
References Category, and UFUNCTION().
UFUNCTION() [61/110]
USkeletalMeshComponent::UFUNCTION ()
UFUNCTION() [62/110]
USkeletalMeshComponent::UFUNCTION ()
Sets whether the post process blueprint is currently running for this component.
If it is not currently running, and is set to run, the instance will be reinitialized
References UFUNCTION().
UFUNCTION() [63/110]
USkeletalMeshComponent::UFUNCTION ()
Enables or disables gravity for the given bone.
NAME_None indicates the root body will be edited. If the bone name given is otherwise invalid, nothing happens.
Parameters
bEnableGravity Whether gravity should be enabled or disabled.
BoneName The name of the bone to modify.
References BoneName, and Category.
UFUNCTION() [64/110]
USkeletalMeshComponent::UFUNCTION ()
Enables or disables gravity to all bodies below the given bone.
NAME_None indicates all bodies will be edited. In that case, consider using UPrimitiveComponent::EnableGravity.
Parameters
bEnableGravity Whether gravity should be enabled or disabled.
BoneName The name of the top most bone.
bIncludeSelf Whether the bone specified should be edited.
References bIncludeSelf, BoneName, Category, and UFUNCTION().
UFUNCTION() [65/110]
USkeletalMeshComponent::UFUNCTION ()
Disable physics blending of bones.
References Category, and UFUNCTION().
UFUNCTION() [66/110]
USkeletalMeshComponent::UFUNCTION ()
Set the post-processing AnimBP to be used for this skeletal mesh component.
In case an override post-processing AnimBP is set, the one set in skeletal mesh asset will be ignored and not used.
Parameters
ReinitAnimInstances Can be false when called e.g. from the construction script in a Blueprint. True when this is called while the game is running and the anim instances need to be re-initialized.
References Category.
UFUNCTION() [67/110]
USkeletalMeshComponent::UFUNCTION ()
This is global set up for setting physics blend weight This does multiple things automatically If PhysicsBlendWeight == 1.f, it will enable Simulation, and if PhysicsBlendWeight == 0.f, it will disable Simulation.
Also it will respect each body's setup, so if the body is fixed, it won't simulate. Vice versa So if you'd like all bodies to change manually, do not use this function, but SetAllBodiesPhysicsBlendWeight
References Category, PhysicsBlendWeight, and UFUNCTION().
UFUNCTION() [68/110]
USkeletalMeshComponent::UFUNCTION ()
Sets the teleportation distance threshold.
Parameters
threshold Threshold value.
References Category.
UFUNCTION() [69/110]
USkeletalMeshComponent::UFUNCTION ()
Sets the teleportation rotation threshold.
Parameters
threshold Threshold in degrees.
References Category.
UFUNCTION() [70/110]
USkeletalMeshComponent::UFUNCTION () &
Takes a snapshot of this skeletal mesh component's pose and saves it to the specified snapshot.
The snapshot is taken at the current LOD, so if for example you took the snapshot at LOD1 and then used it at LOD0 any bones not in LOD1 will use the reference pose
References Category, Snapshot, UFUNCTION(), and UPARAM().
UFUNCTION() [71/110]
USkeletalMeshComponent::UFUNCTION ()
Terminate physics on all bodies below the named bone, effectively disabling collision forever.
If you terminate, you won't be able to re-init later.
References Category.
UFUNCTION() [72/110]
USkeletalMeshComponent::UFUNCTION ()
Toggles whether the post process blueprint will run for this component.
References Category, and UFUNCTION().
UFUNCTION() [73/110]
USkeletalMeshComponent::UFUNCTION () const inline
Definition at line 1280 of file SkeletalMeshComponent.h.
References Category, and UFUNCTION().
UFUNCTION() [74/110]
USkeletalMeshComponent::UFUNCTION () const inline
Definition at line 1397 of file SkeletalMeshComponent.h.
References Category, and UFUNCTION().
UFUNCTION() [75/110]
USkeletalMeshComponent::UFUNCTION () const inline
Definition at line 1353 of file SkeletalMeshComponent.h.
References Category, and UFUNCTION().
UFUNCTION() [76/110]
USkeletalMeshComponent::UFUNCTION () inline
Set the SkeletalMesh rendered for this mesh.
Definition at line 341 of file SkeletalMeshComponent.h.
References Category, SetSkeletalMesh(), and USkeletalMesh.
Referenced by UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
UFUNCTION() [77/110]
USkeletalMeshComponent::UFUNCTION () const
Returns whether there are any valid instances to run, currently this means whether we have have an animation instance or a post process instance available to process.
References Category, const, Keywords, meta, and UFUNCTION().
UFUNCTION() [78/110]
USkeletalMeshComponent::UFUNCTION () const
References Category, const, Keywords, meta, and UFUNCTION().
UFUNCTION() [79/110]
USkeletalMeshComponent::UFUNCTION () const &
Given a world position, find the closest point on the physics asset.
Note that this is independent of collision and welding. This is based purely on animation position
Parameters
WorldPosition The point we want the closest point to (i.e. for all bodies in the physics asset, find the one that has a point closest to WorldPosition)
ClosestPointOnPhysicsAsset The data associated with the closest point (position, normal, etc...)
Returns
true if we found a closest point
References Category, Keywords, meta, and UFUNCTION().
UFUNCTION() [80/110]
USkeletalMeshComponent::UFUNCTION () const
Returns the animation instance that is driving the class (if available).
This is typically an instance of the class set as AnimBlueprintGeneratedClass (generated by an animation blueprint) Since this instance is transient, it is not safe to be used during construction script
References Category, const, Keywords, meta, UAnimInstance, and UFUNCTION().
UFUNCTION() [81/110]
USkeletalMeshComponent::UFUNCTION ()
Gets a constraint by its name.
Parameters
ConstraintName name of the constraint
IncludesTerminated whether or not to return a terminated constraint
References Category, Keywords, meta, and UFUNCTION().
UFUNCTION() [82/110]
USkeletalMeshComponent::UFUNCTION () const
References Category, const, Keywords, meta, and UFUNCTION().
UFUNCTION() [83/110]
USkeletalMeshComponent::UFUNCTION () const
References Category, const, Keywords, meta, and UFUNCTION().
UFUNCTION() [84/110]
USkeletalMeshComponent::UFUNCTION () const
Returns the a tagged linked instance node.
If no linked instances are found or none are tagged with the supplied name, this will return NULL.
References Category, const, Keywords, meta, and UAnimInstance.
UFUNCTION() [85/110]
USkeletalMeshComponent::UFUNCTION () const
Gets the first layer linked instance corresponding to the specified class.
References Category, const, InClass, Keywords, meta, and UAnimInstance.
UFUNCTION() [86/110]
USkeletalMeshComponent::UFUNCTION () const
Gets the layer linked instance corresponding to the specified group.
References Category, const, Keywords, meta, and UAnimInstance.
UFUNCTION() [87/110]
USkeletalMeshComponent::UFUNCTION () const
Returns the active post process instance is one is available.
This is set on the mesh that this component is using, and is evaluated immediately after the main instance.
References Category, const, Keywords, meta, PRAGMA_DISABLE_DEPRECATION_WARNINGS, UAnimInstance, and UFUNCTION().
UFUNCTION() [88/110]
USkeletalMeshComponent::UFUNCTION ()
Set the anim instance class.
Clears and re-initializes the anim instance with the new class and sets animation mode to 'AnimationBlueprint'
References Category, Keywords, meta, and UFUNCTION().
UFUNCTION() [89/110]
USkeletalMeshComponent::UFUNCTION ()
If this component has a valid LeaderPoseComponent then this function makes cloth items on the follower component take the transforms of the cloth items on the leader component instead of simulating separately.
@Note This will FORCE any cloth actor on the leader component to simulate in local space. Also The meshes used in the components must be identical for the cloth to bind correctly
References Category, meta, and UFUNCTION().
UFUNCTION() [90/110]
USkeletalMeshComponent::UFUNCTION ()
Break a constraint off a Gore mesh.
Parameters
Impulse vector of impulse
HitLocation location of the hit
InBoneName Name of bone to break constraint for
References Category, Keywords, meta, and UFUNCTION().
UFUNCTION() [91/110]
USkeletalMeshComponent::UFUNCTION ()
Gets all the constraints.
Parameters
IncludesTerminated whether or not to return terminated constraints
OutConstraints returned list of constraints matching the parameters
References Category, Keywords, meta, and UFUNCTION().
UFUNCTION() [92/110]
USkeletalMeshComponent::UFUNCTION ()
Gets all the constraints attached to a body.
Parameters
BodyName name of the body to get the attached constraints from
bParentConstraints return constraints where BodyName is the child of the constraint
bChildConstraints return constraints where BodyName is the parent of the constraint
bParentConstraints return constraints attached to the parent of the body
IncludesTerminated whether or not to return terminated constraints
OutConstraints returned list of constraints matching the parameters
References Category, Keywords, meta, and UFUNCTION().
UFUNCTION() [93/110]
USkeletalMeshComponent::UFUNCTION ()
Runs through all layer nodes, attempting to find layer nodes that are implemented by the specified class, then sets up a linked instance of the class for each.
Allocates one linked instance to run each of the groups specified in the class, so state is shared. If a layer is not grouped (ie. NAME_None), then state is not shared and a separate linked instance is allocated for each layer node. If InClass is null, then all layers are reset to their defaults.
References Category, InClass, Keywords, meta, and UAnimInstance.
UFUNCTION() [94/110]
USkeletalMeshComponent::UFUNCTION ()
Runs through all nodes, attempting to find linked instance by name/tag, then sets the class of each node if the tag matches.
References Category, InClass, Keywords, meta, and UAnimInstance.
UFUNCTION() [95/110]
USkeletalMeshComponent::UFUNCTION ()
This overrides current AnimationData parameter in the SkeletalMeshComponent.
This will serialize when the component serialize so it can be used during construction script. However note that this will override current existing data This can be useful if you'd like to make a blueprint with custom default animation per component This sets single player mode, which means you can't use AnimBlueprint with it
References Category, Keywords, meta, and UFUNCTION().
UFUNCTION() [96/110]
USkeletalMeshComponent::UFUNCTION ()
References bLooping, Category, Keywords, meta, and UFUNCTION().
UFUNCTION() [97/110]
UFUNCTION()) 1 void SetAnimationMode(EAnimationMode UFUNCTION()) 1 EAnimationMode USkeletalMeshComponent::UFUNCTION ()
Below are the interface to control animation when animation mode, not blueprint mode.
Set the Animation Mode
Parameters
InAnimationMode : Requested AnimationMode
bForceInitAnimScriptInstance : Init AnimScriptInstance if the AnimationMode is AnimationBlueprint even if the new animation mode is the same as current (this allows to use BP construction script to do this)
References Category, Keywords, meta, and UFUNCTION().
UFUNCTION() [98/110]
USkeletalMeshComponent::UFUNCTION ()
Informs any active anim instances (main instance, linked instances, post instance) that a dynamics reset is required for example if a teleport occurs.
References Category, const, Keywords, meta, and UFUNCTION().
UFUNCTION() [99/110]
USkeletalMeshComponent::UFUNCTION ()
Resumes a previously suspended clothing simulation, teleporting the clothing on the next tick.
References Category, meta, and UFUNCTION().
UFUNCTION() [100/110]
USkeletalMeshComponent::UFUNCTION ()
References Category, Keywords, meta, and UFUNCTION().
UFUNCTION() [101/110]
USkeletalMeshComponent::UFUNCTION ()
Whether the built-in animation of this component should run when the component ticks.
See USkeletalMeshComponent::bEnableAnimation for more details. Note that this call defers setting the flag to the end of the frame as the flag cannot change during world ticking (as other tasks may be in flight)
References Category, Keywords, meta, and UFUNCTION().
UFUNCTION() [102/110]
USkeletalMeshComponent::UFUNCTION ()
Set Morph Target with Name and Value(0-1)
Parameters
bRemoveZeroWeight : Used by editor code when it should stay in the active list with zero weight
References Category, meta, and UFUNCTION().
UFUNCTION() [103/110]
USkeletalMeshComponent::UFUNCTION ()
References Category, Keywords, meta, and UFUNCTION().
UFUNCTION() [104/110]
USkeletalMeshComponent::UFUNCTION ()
References Category, Keywords, meta, and UFUNCTION().
UFUNCTION() [105/110]
USkeletalMeshComponent::UFUNCTION () const
Sets whether or not to force tick component in order to update animation and refresh transform for this component This is supported only in the editor.
References Category, const, and meta.
UFUNCTION() [106/110]
USkeletalMeshComponent::UFUNCTION () const
Sets whether or not to animate cloth in the editor.
Requires Update Animation In Editor to also be true. This is supported only in the editor
References Category, const, meta, and UFUNCTION().
UFUNCTION() [107/110]
USkeletalMeshComponent::UFUNCTION ()
References Category, Keywords, meta, Stop, and UFUNCTION().
UFUNCTION() [108/110]
USkeletalMeshComponent::UFUNCTION ()
Stops simulating clothing, but does not show clothing ref pose.
Keeps the last known simulation state
References Category, meta, and UFUNCTION().
UFUNCTION() [109/110]
USkeletalMeshComponent::UFUNCTION ()
If this component has a valid LeaderPoseComponent and has previously had its cloth bound to the MCP, this function will unbind the cloth and resume simulation.
Parameters
bRestoreSimulationSpace if true and the leader pose cloth was originally simulating in world space, we will restore this setting. This will cause the leader component to reset which may be undesirable.
References Category, and meta.
UFUNCTION() [110/110]
USkeletalMeshComponent::UFUNCTION ()
Runs through all layer nodes, attempting to find layer nodes that are currently running the specified class, then resets each to its default value.
State sharing rules are as with SetLayerOverlay. If InClass is null, does nothing.
References Category, InClass, Keywords, meta, and UAnimInstance.
UnHideBone()
virtual void USkeletalMeshComponent::UnHideBone (int32 BoneIndex) override virtual
UnregisterOnBoneTransformsFinalizedDelegate()
virtual void USkeletalMeshComponent::UnregisterOnBoneTransformsFinalizedDelegate (const FDelegateHandle & DelegateHandle) override virtual
UnregisterOnLODRequiredBonesUpdate_Member()
void USkeletalMeshComponent::UnregisterOnLODRequiredBonesUpdate_Member (const FDelegateHandle & DelegateHandle) private
References const, and UnregisterOnLODRequiredBonesUpdate_Member().
Referenced by UnregisterOnLODRequiredBonesUpdate_Member().
UnregisterOnPhysicsCreatedDelegate()
void USkeletalMeshComponent::UnregisterOnPhysicsCreatedDelegate (const FDelegateHandle & DelegateHandle)
UnregisterOnSkeletalMeshPropertyChanged()
void USkeletalMeshComponent::UnregisterOnSkeletalMeshPropertyChanged (FDelegateHandle Handle)
References Handle.
UnregisterOnSkeletalMeshUnregistered()
void USkeletalMeshComponent::UnregisterOnSkeletalMeshUnregistered (FDelegateHandle Handle)
References Handle.
UnregisterOnTeleportDelegate()
void USkeletalMeshComponent::UnregisterOnTeleportDelegate (const FDelegateHandle & DelegateHandle)
UPARAM() [1/4]
const FName USkeletalMeshComponent::UPARAM (ref) &
Referenced by UFUNCTION(), UPARAM(), UPARAM(), and UPARAM().
UPARAM() [2/4]
const FName USkeletalMeshComponent::UPARAM (ref) &
References AttributeName, BoneName, const, LookupType, OutValue, and UPARAM().
UPARAM() [3/4]
const FName USkeletalMeshComponent::UPARAM (ref) &
References AttributeName, BoneName, const, LookupType, OutValue, and UPARAM().
UPARAM() [4/4]
const FName USkeletalMeshComponent::UPARAM (ref) &
References AttributeName, BoneName, const, LookupType, OutValue, and UPARAM().
UpdateBoneBodyMapping()
void USkeletalMeshComponent::UpdateBoneBodyMapping ()
Update the bone mapping on each body instance.
This is useful when changing skeletal mesh without recreating bodies
References UpdateBoneBodyMapping().
Referenced by UpdateBoneBodyMapping().
UpdateClothCollision()
void USkeletalMeshComponent::UpdateClothCollision ()
Updates cloth collision inside the cloth asset (from a physics asset).
Should be called when the physics asset changes and the effects are needed straight away.
UpdateClothSimulationContext()
void USkeletalMeshComponent::UpdateClothSimulationContext (float InDeltaTime) private
Copies the data from the external cloth simulation context.
We copy instead of flipping because the API has to return the full struct to make backwards compat easy
UpdateClothStateAndSimulate()
void USkeletalMeshComponent::UpdateClothStateAndSimulate (float DeltaTime, FTickFunction & ThisTickFunction)
Update the clothing simulation state and trigger the simulation task.
References DeltaTime, and UpdateClothStateAndSimulate().
Referenced by UpdateClothStateAndSimulate().
UpdateClothTickRegisteredState()
void USkeletalMeshComponent::UpdateClothTickRegisteredState () private
UpdateClothTransform() [1/2]
void USkeletalMeshComponent::UpdateClothTransform () inline
Set the cloth transform update to trigger with no teleport option.
Definition at line 2413 of file SkeletalMeshComponent.h.
References UpdateClothTransform(), and UpdateClothTransform().
Referenced by UpdateClothTransform().
UpdateClothTransform() [2/2]
void USkeletalMeshComponent::UpdateClothTransform (ETeleportType TeleportType)
Updates cloth collision outside the cloth asset (environment collision, child collision, etc...) Should be called when scene changes or world position changes.
References UpdateClothTransform().
Referenced by UpdateClothTransform(), and UpdateClothTransform().
UpdateClothTransformImp()
void USkeletalMeshComponent::UpdateClothTransformImp () private
See UpdateClothTransform for documentation.
UpdateCollisionProfile()
virtual void USkeletalMeshComponent::UpdateCollisionProfile () override virtual
UpdateDuringAnimationTickRegisteredState()
void USkeletalMeshComponent::UpdateDuringAnimationTickRegisteredState () private
UpdateEndPhysicsTickRegisteredState()
void USkeletalMeshComponent::UpdateEndPhysicsTickRegisteredState () private
UpdateFollowerComponent()
virtual void USkeletalMeshComponent::UpdateFollowerComponent () override virtual
Referenced by UE_DEPRECATED().
UpdateHasValidBodies()
void USkeletalMeshComponent::UpdateHasValidBodies ()
Update bHasValidBodies flag.
References UpdateHasValidBodies().
Referenced by UpdateHasValidBodies().
UpdateKinematicBonesToAnim()
void USkeletalMeshComponent::UpdateKinematicBonesToAnim (const TArray< FTransform > & InComponentSpaceTransforms, ETeleportType Teleport, bool bNeedsSkinning, EAllowKinematicDeferral DeferralAllowed = EAllowKinematicDeferral::AllowDeferral)
Iterate over each physics body in the physics for this mesh, and for each 'kinematic' (ie fixed or default if owner isn't simulating) one, update its transform based on the animated transform.
This update is also done for simulating bodies if a teleport is being requested.
Parameters
InComponentSpaceTransforms Array of bone transforms in component space
Teleport Whether movement is a 'teleport' (ie infers no physics velocity, but moves simulating bodies) or not
bNeedsSkinning Whether we may need to send new triangle data for per-poly skeletal mesh collision
AllowDeferral Whether we can defer actual update of bodies (if 'physics only' collision)
References AllowDeferral, const, and UpdateKinematicBonesToAnim().
Referenced by UpdateKinematicBonesToAnim().
UpdateLODStatus()
virtual bool USkeletalMeshComponent::UpdateLODStatus () override virtual
UpdateMeshForBrokenConstraints()
void USkeletalMeshComponent::UpdateMeshForBrokenConstraints ()
Look up all bodies for broken constraints.
Makes sure child bodies of a broken constraints are not fixed and using bone springs, and child joints not motorized.
References UpdateMeshForBrokenConstraints().
Referenced by UpdateMeshForBrokenConstraints().
UpdateMorphTargetOverrideCurves()
void USkeletalMeshComponent::UpdateMorphTargetOverrideCurves () private
UpdateOverlapsImpl()
virtual bool USkeletalMeshComponent::UpdateOverlapsImpl (const TOverlapArrayView * PendingOverlaps = NULL, bool bDoNotifies = true, const TOverlapArrayView * OverlapsAtEndLocation = NULL) override virtual
UpdatePhysicsToRBChannels()
virtual void USkeletalMeshComponent::UpdatePhysicsToRBChannels () override virtual
UpdatePoseWatches()
void USkeletalMeshComponent::UpdatePoseWatches ()
UpdateRBJointMotors()
void USkeletalMeshComponent::UpdateRBJointMotors ()
Iterate over each joint in the physics for this mesh, setting its AngularPositionTarget based on the animation information.
References UpdateRBJointMotors().
Referenced by UpdateRBJointMotors().
UpdateRigidBodyScaling()
void USkeletalMeshComponent::UpdateRigidBodyScaling (ETeleportType TeleportType)
Update rigid body scaling when the actor is set with a new uniform scale.
References UpdateRigidBodyScaling().
Referenced by UpdateRigidBodyScaling().
UpdateVisualizeLODString()
virtual void USkeletalMeshComponent::UpdateVisualizeLODString (FString & DebugString) override virtual
UPROPERTY() [1/32]
USkeletalMeshComponent::UPROPERTY () private
Whether the FilteredAnimCurves list is an allow or deny list.
References transient.
UPROPERTY() [2/32]
USkeletalMeshComponent::UPROPERTY ()
Whether we should stall the Cloth tick task until the cloth simulation is complete.
This is required if we want up-to-date cloth data on the game thread, for example if we want to generate particles at cloth vertices.
References Category.
UPROPERTY() [3/32]
UPROPERTY() TEnumAsByte< EKinematicBonesUpdateToPhysics UPROPERTY() TEnumAsByte< EPhysicsTransformUpdateMode USkeletalMeshComponent::UPROPERTY ()
If we are running physics, should we update non-simulated bones based on the animation bone positions.
Whether physics simulation updates component transform. whether we need to teleport cloth.
References Animation, Category, meta, Transient, and UPROPERTY().
UPROPERTY() [4/32]
USkeletalMeshComponent::UPROPERTY ()
Notification when constraint is broken.
References UPROPERTY().
UPROPERTY() [5/32]
USkeletalMeshComponent::UPROPERTY ()
weight to blend between simulated results and key-framed positions if weight is 1.0, shows only cloth simulation results and 0.0 will show only skinned results
References Category.
UPROPERTY() [6/32]
USkeletalMeshComponent::UPROPERTY () private
Conduct teleportation if the character's movement is greater than this threshold in 1 frame.
Zero or negative values will skip the check. You can also do force teleport manually using ForceNextUpdateTeleport() / ForceNextUpdateTeleportAndReset().
References Category.
UPROPERTY() [7/32]
USkeletalMeshComponent::UPROPERTY () private
Rotation threshold in degrees, ranging from 0 to 180.
Conduct teleportation if the character's rotation is greater than this threshold in 1 frame. Zero or negative values will skip the check.
References Category.
UPROPERTY() [8/32]
USkeletalMeshComponent::UPROPERTY ()
References Animation, and Category.
UPROPERTY() [9/32]
USkeletalMeshComponent::UPROPERTY ()
Notification when constraint plasticity drive target changes.
References UPROPERTY().
UPROPERTY() [10/32]
USkeletalMeshComponent::UPROPERTY ()
If bEnableLineCheckWithBounds is true, scale the bounds by this value before doing line check.
References FVector, and UPROPERTY().
UPROPERTY() [11/32]
USkeletalMeshComponent::UPROPERTY ()
Offset of the root bone from the reference pose.
Used to offset bounding box.
References FVector, transient, and UPROPERTY().
UPROPERTY() [12/32]
USkeletalMeshComponent::UPROPERTY () private
You can choose to disable certain curves if you prefer.
This is transient curves that will be ignored by animation system if you choose this
References transient.
UPROPERTY() [13/32]
USkeletalMeshComponent::UPROPERTY () private
Cached BoneSpaceTransforms for Update Rate optimization.
References Transient, and UPROPERTY().
UPROPERTY() [14/32]
USkeletalMeshComponent::UPROPERTY () private
Cached SpaceBases for Update Rate optimization.
References Transient, and UPROPERTY().
UPROPERTY() [15/32]
USkeletalMeshComponent::UPROPERTY () private
Any running linked anim instances.
References transient, UAnimInstance, and UPROPERTY().
UPROPERTY() [16/32]
USkeletalMeshComponent::UPROPERTY () private
Morph Target Curves.
This will override AnimInstance MorphTargetCurves if same curve is found
References Transient.
UPROPERTY() [17/32]
USkeletalMeshComponent::UPROPERTY ()
Used for per poly collision.
In 99% of cases you will be better off using a Physics Asset. This BodySetup is per instance because all modification of vertices is done in place
References BodySetup, and transient.
UPROPERTY() [18/32]
USkeletalMeshComponent::UPROPERTY ()
The active animation graph program instance.
References transient, UAnimInstance, and UPROPERTY().
UPROPERTY() [19/32]
USkeletalMeshComponent::UPROPERTY ()
An instance created from the PostPhysicsBlueprint property of the skeletal mesh we're using, Runs after (and receives pose from) the main anim instance.
References transient.
UPROPERTY() [20/32]
USkeletalMeshComponent::UPROPERTY () private
Object responsible for interacting with the clothing simulation.
Blueprints and code can call/set data on this from the game thread and the next time it is safe to do so the interactor will sync to the simulation context
References Transient.
UPROPERTY() [21/32]
USkeletalMeshComponent::UPROPERTY ()
Class of the object responsible for.
References Category, and UPROPERTY().
UPROPERTY() [22/32]
USkeletalMeshComponent::UPROPERTY ()
Post-processing AnimBP to use for the given skeletal mesh component, overriding the one set in the skeletal mesh asset.
References transient.
UPROPERTY() [23/32]
USkeletalMeshComponent::UPROPERTY ()
Cache AnimCurveUidVersion from Skeleton and this will be used to identify if it needs to be updated.
References transient.
UPROPERTY() [24/32]
USkeletalMeshComponent::UPROPERTY () private
Cache curve metadata from mesh and this will be used to identify if it needs to be updated.
References transient.
UPROPERTY() [25/32]
USkeletalMeshComponent::UPROPERTY () private
References Transient.
UPROPERTY() [26/32]
USkeletalMeshComponent::UPROPERTY ()
References Animation, Category, meta, SetAnimInstanceClass_Internal(), and UAnimInstance.
Referenced by FRigUnit_AnimNextRemapPose, FTickClothingTask, GetSharedRequiredBones(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), and UPROPERTY().
UPROPERTY() [27/32]
USkeletalMeshComponent::UPROPERTY ()
This scale is applied to all cloth geometry (e.g., cloth meshes and collisions) in order to simulate in a different scale space than world.This scale is not applied to distance-based simulation parameters such as MaxDistance.
This property is currently only read by the cloth solver when creating cloth actors, but may become animatable in the future.
References Category, meta, and UPROPERTY().
UPROPERTY() [28/32]
USkeletalMeshComponent::UPROPERTY ()
References Category, float, and meta.
UPROPERTY() [29/32]
UPROPERTY() uint8 bCollideWithEnvironment UPROPERTY() uint8 bCollideWithAttachedChildren UPROPERTY() uint8 bForceCollisionUpdate USkeletalMeshComponent::UPROPERTY ()
can't collide with part of environment if total collision volumes exceed 16 capsules or 32 planes per convex
can't collide with part of attached children if total collision volumes exceed 16 capsules or 32 planes per convex Forces the cloth simulation to constantly update its external collisions, at the expense of performance. This will help to prevent missed collisions if the cloth's skeletal mesh component isn't moving, and when instead, wind or other moving objects are causing new collision shapes to come into the cloth's vicinity. Scale applied to the component induced velocity of all cloth particles prior to stepping the cloth solver. Use 1.0 for fully induced velocity (default), or use 0.0 for no induced velocity, and any other values in between for a reduced induced velocity. When set to 0.0, it also provides a way to force the clothing to simulate in local space. This value multiplies to individual cloth's velocity scale settings, still allowing for differences in behavior between the various pieces of clothing within the same component.
References Category, float, Meta, and UPROPERTY().
UPROPERTY() [30/32]
USkeletalMeshComponent::UPROPERTY ()
Used to scale speed of all animations on this skeletal mesh.
References Animation, Category, meta, Physics, SkeletalMesh, and UPROPERTY().
UPROPERTY() [31/32]
USkeletalMeshComponent::UPROPERTY () private
References Animation, Category, INDEX_NONE, meta, and UPROPERTY().
UPROPERTY() [32/32]
USkeletalMeshComponent::UPROPERTY ()
References Animation, Category, meta, and UPROPERTY().
ValidateAnimation()
void USkeletalMeshComponent::ValidateAnimation ()
Validates the animation asset or blueprint, making sure it is compatible with the current skeleton.
WaitForExistingParallelClothSimulation_GameThread()
void USkeletalMeshComponent::WaitForExistingParallelClothSimulation_GameThread ()
Stalls on any currently running clothing simulations.
WakeAllRigidBodies()
virtual void USkeletalMeshComponent::WakeAllRigidBodies () override virtual
WritebackClothingSimulationData()
void USkeletalMeshComponent::WritebackClothingSimulationData () private
Called by the clothing completion event to perform a writeback of the simulation data to the game thread, the task is friended to gain access to this and not allow any external callers to trigger writebacks.
Friends And Related Symbol Documentation
FAnimNode_LinkedAnimGraph
friend struct FAnimNode_LinkedAnimGraph friend
Definition at line 322 of file SkeletalMeshComponent.h.
References FAnimNode_LinkedAnimGraph.
Referenced by FAnimNode_LinkedAnimGraph.
FAnimNode_LinkedAnimLayer
friend struct FAnimNode_LinkedAnimLayer friend
Definition at line 323 of file SkeletalMeshComponent.h.
References FAnimNode_LinkedAnimLayer.
Referenced by FAnimNode_LinkedAnimLayer.
FClothingSimulationContextCommon
friend class FClothingSimulationContextCommon friend
Definition at line 2616 of file SkeletalMeshComponent.h.
References FClothingSimulationContextCommon.
Referenced by FClothingSimulationContextCommon.
FLinkedAnimLayerClassData
friend struct FLinkedAnimLayerClassData friend
Definition at line 325 of file SkeletalMeshComponent.h.
References FLinkedAnimLayerClassData.
Referenced by FLinkedAnimLayerClassData.
FLinkedInstancesAdapter
friend struct FLinkedInstancesAdapter friend
Definition at line 324 of file SkeletalMeshComponent.h.
References FLinkedInstancesAdapter.
Referenced by FLinkedInstancesAdapter.
FParallelAnimationCompletionTask
friend class FParallelAnimationCompletionTask friend
Definition at line 319 of file SkeletalMeshComponent.h.
References FParallelAnimationCompletionTask.
Referenced by FParallelAnimationCompletionTask.
FParallelBlendPhysicsCompletionTask
friend class FParallelBlendPhysicsCompletionTask friend
Definition at line 2609 of file SkeletalMeshComponent.h.
References FParallelBlendPhysicsCompletionTask.
Referenced by FParallelBlendPhysicsCompletionTask.
FParallelBlendPhysicsTask
friend class FParallelBlendPhysicsTask friend
Definition at line 2594 of file SkeletalMeshComponent.h.
References FParallelBlendPhysicsTask.
Referenced by FParallelBlendPhysicsTask.
FParallelClothCompletionTask
friend class FParallelClothCompletionTask friend
Definition at line 1573 of file SkeletalMeshComponent.h.
References FParallelClothCompletionTask.
Referenced by FParallelClothCompletionTask.
FParallelClothTask
friend class FParallelClothTask friend
Definition at line 2605 of file SkeletalMeshComponent.h.
References FParallelClothTask.
Referenced by FParallelClothTask.
FRigUnit_AnimNextRemapPose
friend struct FRigUnit_AnimNextRemapPose friend
Definition at line 327 of file SkeletalMeshComponent.h.
References Category, FRigUnit_AnimNextRemapPose, Mesh, Transient, UPROPERTY(), and USkeletalMesh.
Referenced by FRigUnit_AnimNextRemapPose.
FRigUnit_AnimNextWriteSkeletalMeshComponentPose
friend struct FRigUnit_AnimNextWriteSkeletalMeshComponentPose friend
Definition at line 326 of file SkeletalMeshComponent.h.
References FRigUnit_AnimNextWriteSkeletalMeshComponentPose.
Referenced by FRigUnit_AnimNextWriteSkeletalMeshComponentPose.
FSkeletalMeshComponentDetails
friend class FSkeletalMeshComponentDetails friend
Definition at line 2552 of file SkeletalMeshComponent.h.
References FSkeletalMeshComponentDetails.
Referenced by FSkeletalMeshComponentDetails.
FSkeletalMeshComponentEndPhysicsTickFunction
friend struct FSkeletalMeshComponentEndPhysicsTickFunction friend
Definition at line 2499 of file SkeletalMeshComponent.h.
References FSkeletalMeshComponentEndPhysicsTickFunction.
Referenced by EndPhysicsTickComponent(), and FSkeletalMeshComponentEndPhysicsTickFunction.
FTickClothingTask
friend class FTickClothingTask friend
Definition at line 2618 of file SkeletalMeshComponent.h.
References FTickClothingTask, and UPROPERTY().
Referenced by FTickClothingTask.
UAnimInstance
friend class UAnimInstance friend
Definition at line 321 of file SkeletalMeshComponent.h.
References UAnimInstance.
Referenced by EvaluateAnimation(), ForEachAnimInstance(), GetLinkedAnimInstances(), PerformAnimationEvaluation(), PerformAnimationProcessing(), SetAnimInstanceClass_Internal(), UAnimInstance, UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UPROPERTY(), UPROPERTY(), UPROPERTY(), and USTRUCT().
UDebugSkelMeshComponent
friend class UDebugSkelMeshComponent friend
Debug mesh component should be able to access for visualisation.
Definition at line 1576 of file SkeletalMeshComponent.h.
References UDebugSkelMeshComponent.
Referenced by UDebugSkelMeshComponent.
UE::AnimNext::FDataRegistry
friend class UE::AnimNext::FDataRegistry friend
Definition at line 2728 of file SkeletalMeshComponent.h.
References Category, meta, and UE::AnimNext::FDataRegistry.
Referenced by UE::AnimNext::FDataRegistry.
USkeletalMesh
friend class USkeletalMesh friend
Definition at line 320 of file SkeletalMeshComponent.h.
References USkeletalMesh.
Referenced by EvaluateAnimation(), EvaluatePostProcessMeshInstance(), ExcludeHiddenBones(), FinalizePoseEvaluationResult(), FRigUnit_AnimNextRemapPose, GetRequiredVirtualBones(), PerformAnimationEvaluation(), PerformAnimationProcessing(), SetSkeletalMesh(), UE_DEPRECATED(), UFUNCTION(), UFUNCTION(), and USkeletalMesh.
Field Documentation
AddPhysicsBlendWeight
float USkeletalMeshComponent::AddPhysicsBlendWeight
Definition at line 2230 of file SkeletalMeshComponent.h.
Aggregate
FPhysicsAggregateHandle USkeletalMeshComponent::Aggregate
Physics-engine representation of aggregate which contains a physics asset instance with more than numbers of bodies.
Definition at line 868 of file SkeletalMeshComponent.h.
AnimEvaluationContext
FAnimationEvaluationContext USkeletalMeshComponent::AnimEvaluationContext private
Definition at line 2535 of file SkeletalMeshComponent.h.
Referenced by ParallelBlendPhysics(), and UE_DEPRECATED().
AttributeName
const FName & USkeletalMeshComponent::AttributeName
Definition at line 489 of file SkeletalMeshComponent.h.
Referenced by FindAttributeChecked(), UPARAM(), UPARAM(), and UPARAM().
AttributesArray
UE::Anim::FMeshAttributeContainer USkeletalMeshComponent::AttributesArray[2] private
Temporary array of attributes that are active on this component - keeps same buffer index as SpaceBases - Please check SkinnedMeshComponent.
Definition at line 2693 of file SkeletalMeshComponent.h.
Referenced by GetCustomAttributes(), and GetEditableCustomAttributes().
bAccelChange
FName bool USkeletalMeshComponent::bAccelChange = false
Definition at line 1983 of file SkeletalMeshComponent.h.
Referenced by AddRadialForce().
bAllow
bool USkeletalMeshComponent::bAllow
Definition at line 1401 of file SkeletalMeshComponent.h.
Referenced by UFUNCTION().
bBindClothToLeaderComponent
UPROPERTY () uint8 bDisableRigidBodyAnimNode UPROPERTY () uint8 bAllowAnimCurveEvaluation uint8 USkeletalMeshComponent::bBindClothToLeaderComponent private
Disable rigid body animation nodes and play original animation without simulation.
Disable animation curves for this component. If this is set true, no curves will be processed Whether or not we're taking cloth sim information from our leader component
Definition at line 710 of file SkeletalMeshComponent.h.
Referenced by IsClothBoundToLeaderComponent().
bChildConstraints
bool bool USkeletalMeshComponent::bChildConstraints
Definition at line 2359 of file SkeletalMeshComponent.h.
bClothingSimulationSuspended
uint8 USkeletalMeshComponent::bClothingSimulationSuspended protected
Optimization.
Whether animation and world transform updates are deferred. If this is on, the kinematic bodies (scene query data) will not update until the next time the physics simulation is run Skips Ticking and Bone Refresh. pauses this component's animations (doesn't tick them, but still refreshes bones) Whether the built-in animation of this component should run when the component ticks. It is assumed that if this is false then some external system will be animating this mesh. Note that disabling animation will also cause cloth simulation not to run and the component's tick to run on any thread. On InitAnim should we set to ref pose (if false use first tick of animation data). If enabled, takes precedence over UAnimationSettings::bTickAnimationOnSkeletalMeshInit Uses skinned data for collision data. Misc If true, force the mesh into the reference pose - is an optimization. If true TickPose() will not be called from the Component's TickComponent function. It will instead be called from Autonomous networking updates. See ACharacter. True if calling TickPose() from Autonomous networking updates. See ACharacter. If bForceRefPose was set last tick. Bool that enables debug drawing of the skeleton before it is passed to the physics. Useful for debugging animation-driven physics. If false, indicates that on the next call to UpdateSkelPose the RequiredBones array should be recalculated. If true, AnimTree has been initialised. If true, line checks will test against the bounding box of this skeletal mesh component and return a hit if there is a collision. If true, propagates calls to ApplyAnimationCurvesToComponent for follower components, only needed if follower components do not tick themselves Whether to skip UpdateKinematicBonesToAnim() when interpolating. Kinematic bones are updated to the target interpolation pose only on ticks when they are evaluated. Whether to skip bounds update when interpolating. Bounds are updated to the target interpolation pose only on ticks when they are evaluated. Whether the clothing simulation is suspended (not the same as disabled, we no longer run the sim but keep the last valid sim data around)
Definition at line 840 of file SkeletalMeshComponent.h.
bDefaultIfNotFound [1/2]
FName bool USkeletalMeshComponent::bDefaultIfNotFound = false)
Definition at line 2246 of file SkeletalMeshComponent.h.
bDefaultIfNotFound [2/2]
bool USkeletalMeshComponent::bDefaultIfNotFound = false)
Definition at line 2250 of file SkeletalMeshComponent.h.
bDisabled
bool USkeletalMeshComponent::bDisabled
Definition at line 2200 of file SkeletalMeshComponent.h.
bEnableTwistDrive
bool USkeletalMeshComponent::bEnableTwistDrive
Definition at line 2234 of file SkeletalMeshComponent.h.
Referenced by SetNamedMotorsAngularPositionDrive(), SetNamedMotorsAngularVelocityDrive(), and UFUNCTION().
bFireNotifies
bool USkeletalMeshComponent::bFireNotifies = true)
Definition at line 1206 of file SkeletalMeshComponent.h.
bIncludeSelf [1/5]
bool bool USkeletalMeshComponent::bIncludeSelf = true)
Definition at line 1731 of file SkeletalMeshComponent.h.
Referenced by ForEachBodyBelow(), and UFUNCTION().
bIncludeSelf [2/5]
FName bool bool USkeletalMeshComponent::bIncludeSelf = true)
Definition at line 1983 of file SkeletalMeshComponent.h.
bIncludeSelf [3/5]
bool bool USkeletalMeshComponent::bIncludeSelf = true)
Definition at line 2200 of file SkeletalMeshComponent.h.
bIncludeSelf [4/5]
const FVector bool USkeletalMeshComponent::bIncludeSelf = true)
Definition at line 2204 of file SkeletalMeshComponent.h.
bIncludeSelf [5/5]
float bool bool USkeletalMeshComponent::bIncludeSelf = true)
Definition at line 2226 of file SkeletalMeshComponent.h.
bIncludesTerminated [1/2]
bool USkeletalMeshComponent::bIncludesTerminated
Definition at line 2341 of file SkeletalMeshComponent.h.
bIncludesTerminated [2/2]
bool bool bool USkeletalMeshComponent::bIncludesTerminated
Definition at line 2359 of file SkeletalMeshComponent.h.
bInDoEvaluation
UAnimInstance bool USkeletalMeshComponent::bInDoEvaluation
Definition at line 2099 of file SkeletalMeshComponent.h.
Referenced by PerformAnimationProcessing().
bIsLooping
bool USkeletalMeshComponent::bIsLooping = true
Definition at line 1242 of file SkeletalMeshComponent.h.
bIsPlaying
bool bool USkeletalMeshComponent::bIsPlaying = true
Definition at line 1242 of file SkeletalMeshComponent.h.
bLocalSpaceKinematics
UPROPERTY () uint8 bUpdateOverlapsOnAnimationFinalize uint8 USkeletalMeshComponent::bLocalSpaceKinematics
Controls whether blending in physics bones will refresh overlaps on this component, defaults to true but can be disabled in cases where we know anim->physics blending doesn't meaningfully change overlaps.
Temporary fix for local space kinematics. This only works for bodies that have no constraints and is needed by vehicles. Proper support will remove this flag
Definition at line 645 of file SkeletalMeshComponent.h.
bLooping
UFUNCTION()) 1 void SetAnimationMode(EAnimationMode UFUNCTION()) 1 EAnimationMode bool USkeletalMeshComponent::bLooping
Definition at line 1161 of file SkeletalMeshComponent.h.
Referenced by UFUNCTION().
bNewSimulate
bool USkeletalMeshComponent::bNewSimulate
Definition at line 2211 of file SkeletalMeshComponent.h.
Referenced by UFUNCTION().
bNotifySyncComponentToRBPhysics
uint8 USkeletalMeshComponent::bNotifySyncComponentToRBPhysics protected
If true, OnSyncComponentToRBPhysics() notify will be called.
Definition at line 857 of file SkeletalMeshComponent.h.
Bodies
TArray<struct FBodyInstance*> USkeletalMeshComponent::Bodies
Array of FBodyInstance objects, storing per-instance state about about each body.
Definition at line 1470 of file SkeletalMeshComponent.h.
BodyIndex
int32 USkeletalMeshComponent::BodyIndex
Definition at line 1454 of file SkeletalMeshComponent.h.
Referenced by USTRUCT().
BoneName [1/2]
FName USkeletalMeshComponent::BoneName = NAME_None)
Definition at line 1723 of file SkeletalMeshComponent.h.
Referenced by CalculateMass(), FindAttributeChecked(), ForEachBodyBelow(), GetBodyInstance(), IsSimulatingPhysics(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UPARAM(), UPARAM(), and UPARAM().
BoneName [2/2]
FVector FVector FName& USkeletalMeshComponent::BoneName
Definition at line 1929 of file SkeletalMeshComponent.h.
bParentConstraints
bool USkeletalMeshComponent::bParentConstraints
Definition at line 2359 of file SkeletalMeshComponent.h.
bPendingClothCollisionUpdate
uint8 USkeletalMeshComponent::bPendingClothCollisionUpdate private
Flag denoting whether or not the clothing collision needs to update from its physics asset.
Definition at line 716 of file SkeletalMeshComponent.h.
bPendingClothTransformUpdate
uint8 USkeletalMeshComponent::bPendingClothTransformUpdate private
Flag denoting whether or not the clothing transform needs to update.
Definition at line 713 of file SkeletalMeshComponent.h.
bPostEvaluatingAnimation
UPROPERTY () uint8 bNeedsQueuedAnimEventsDispatched uint8 USkeletalMeshComponent::bPostEvaluatingAnimation private
Definition at line 864 of file SkeletalMeshComponent.h.
Referenced by IsPostEvaluatingAnimation().
bPrevDisableClothSimulation
UPROPERTY () uint8 bResetAfterTeleport uint8 USkeletalMeshComponent::bPrevDisableClothSimulation
reset the clothing after moving the clothing position (called teleport)
To save previous state
Definition at line 747 of file SkeletalMeshComponent.h.
bRemoveZeroWeight
float bool USkeletalMeshComponent::bRemoveZeroWeight =true)
Definition at line 1250 of file SkeletalMeshComponent.h.
bScaleMass
bool USkeletalMeshComponent::bScaleMass = true) const
Definition at line 1961 of file SkeletalMeshComponent.h.
bSimulate
bool USkeletalMeshComponent::bSimulate
Definition at line 2215 of file SkeletalMeshComponent.h.
bSimulationUpdatesChildTransforms
uint8 USkeletalMeshComponent::bSimulationUpdatesChildTransforms
Controls whether or not this component will evaluate its post process instance.
The post-process Instance is dictated by the skeletal mesh so this is used for per-instance control. Indicates that simulation (if it's enabled) is entirely responsible for children transforms. This is only ok if you are not animating attachment points relative to the simulation
Definition at line 638 of file SkeletalMeshComponent.h.
bSkipCustomPhysicsType [1/4]
bool bool USkeletalMeshComponent::bSkipCustomPhysicsType = false)
Definition at line 2222 of file SkeletalMeshComponent.h.
Referenced by UFUNCTION().
bSkipCustomPhysicsType [2/4]
float bool USkeletalMeshComponent::bSkipCustomPhysicsType = false
Definition at line 2226 of file SkeletalMeshComponent.h.
bSkipCustomPhysicsType [3/4]
bool bool USkeletalMeshComponent::bSkipCustomPhysicsType = false)
Definition at line 2234 of file SkeletalMeshComponent.h.
bSkipCustomPhysicsType [4/4]
float float bool USkeletalMeshComponent::bSkipCustomPhysicsType = false)
Definition at line 2242 of file SkeletalMeshComponent.h.
bVelChange
FName bool USkeletalMeshComponent::bVelChange = false
Definition at line 1994 of file SkeletalMeshComponent.h.
Referenced by AddRadialImpulse().
CachedAttributes
UE::Anim::FMeshAttributeContainer USkeletalMeshComponent::CachedAttributes private
Current and cached attribute evaluation data, used for Update Rate optimization.
Definition at line 476 of file SkeletalMeshComponent.h.
CachedCurve
FBlendedHeapCurve USkeletalMeshComponent::CachedCurve private
Cached Curve result for Update Rate optimization.
Definition at line 473 of file SkeletalMeshComponent.h.
ClosestWorldPosition
FVector& USkeletalMeshComponent::ClosestWorldPosition
Definition at line 1929 of file SkeletalMeshComponent.h.
ClothCollisionSources
TArray<FClothCollisionSource> USkeletalMeshComponent::ClothCollisionSources private
Array of sources for cloth collision.
Definition at line 1604 of file SkeletalMeshComponent.h.
Referenced by GetClothCollisionSources().
ClothingSimulation
IClothingSimulation* USkeletalMeshComponent::ClothingSimulation private
Clothing simulation objects.
ClothingSimulation is responsible for maintaining and siulating clothing actors ClothingSimulationContext is a datastore for simulation data sent to the clothing thread
Definition at line 1592 of file SkeletalMeshComponent.h.
ClothingSimulationContext
IClothingSimulationContext* USkeletalMeshComponent::ClothingSimulationContext private
Definition at line 1593 of file SkeletalMeshComponent.h.
ClothTeleportCosineThresholdInRad
float USkeletalMeshComponent::ClothTeleportCosineThresholdInRad private
Used for pre-computation using TeleportRotationThreshold property.
Definition at line 1527 of file SkeletalMeshComponent.h.
ClothTeleportDistThresholdSquared
float USkeletalMeshComponent::ClothTeleportDistThresholdSquared private
Used for pre-computation using tTeleportDistanceThreshold property.
Definition at line 1529 of file SkeletalMeshComponent.h.
ClothTickFunction
FSkeletalMeshComponentClothTickFunction USkeletalMeshComponent::ClothTickFunction
Definition at line 1475 of file SkeletalMeshComponent.h.
const [1/5]
float float& Value USkeletalMeshComponent::const
Definition at line 586 of file SkeletalMeshComponent.h.
Referenced by AddClothingBounds(), ApplyDeltaToAllPhysicsTransforms(), ComputeRequiredBones(), DebugDrawClothingTexts(), DoCustomNavigableGeometryExport(), EvaluatePostProcessMeshInstance(), ExcludeHiddenBones(), FindAttributeChecked(), GetAnimationModePropertyNameChecked(), GetAnimCurves(), GetBoneSpaceTransformsView(), GetCachedComponentSpaceTransforms(), GetClosestCollidingRigidBodyLocation(), GetClosestPointOnPhysicsAsset(), GetLinkedAnimInstances(), GetMass(), GetMorphTargetCurves(), GetRequiredVirtualBones(), GetShadowShapeRequiredBones(), GetUpdateClothSimulationData_AnyThread(), IsPlayingNetworkedRootMotionMontage(), IsPlayingRootMotion(), IsPlayingRootMotionFromEverything(), IsShown(), LineTraceComponent(), OverlapComponent(), RegisterOnLODRequiredBonesUpdate_Member(), SetAnimInstanceClass_Internal(), SetNamedMotorsAngularPositionDrive(), SetNamedMotorsAngularVelocityDrive(), SetRefPoseOverride(), ShouldEvaluatePostProcessAnimBP(), ShouldEvaluatePostProcessInstance(), ShouldPostUpdatePostProcessInstance(), ShouldUpdatePostProcessInstance(), SweepComponent(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UnregisterOnLODRequiredBonesUpdate_Member(), UPARAM(), UPARAM(), UPARAM(), and UpdateKinematicBonesToAnim().
const [2/5]
TArray<UAnimInstance*>& OutSubInstances USkeletalMeshComponent::const
Initial value:
{
        PRAGMA_DISABLE_DEPRECATION_WARNINGS
        GetLinkedAnimGraphInstancesByTag(InTag, OutSubInstances)
Definition at line 1066 of file SkeletalMeshComponent.h.
const [3/5]
PRAGMA_ENABLE_DEPRECATION_WARNINGS TArray<UAnimInstance*>& OutLinkedInstances USkeletalMeshComponent::const
Definition at line 1078 of file SkeletalMeshComponent.h.
const [4/5]
FVector FVector FName float& Distance USkeletalMeshComponent::const
Definition at line 1929 of file SkeletalMeshComponent.h.
const [5/5]
FCompactPose FBlendedHeapCurve const USkeletalMesh FVector UE::Anim::FHeapAttributeContainer& OutAttributes USkeletalMeshComponent::const
Definition at line 2107 of file SkeletalMeshComponent.h.
Constraints
TArray<struct FConstraintInstance*> USkeletalMeshComponent::Constraints
Array of FConstraintInstance structs, storing per-instance state about each constraint.
Definition at line 1473 of file SkeletalMeshComponent.h.
CurrentSimulationData
TMap<int32, FClothSimulData> USkeletalMeshComponent::CurrentSimulationData protected
Simulation data written back to the component after the simulation has taken place.
If this data is required by any system other than rendering, bWaitForParallelClothTask must be true. If bWaitForParallelClothTask is false, this data cannot be read on the game thread, and there must be a call to HandleExistingParallelClothSimulation() prior to accessing it.
Definition at line 1634 of file SkeletalMeshComponent.h.
CurvesArray
FBlendedHeapCurve USkeletalMeshComponent::CurvesArray[2] private
This is required for recording animations, so save for editor only.
Temporary array of curve arrays that are active on this component - keeps same buffer index as SpaceBases - Please check SkinnedMeshComponent
Definition at line 2680 of file SkeletalMeshComponent.h.
Referenced by GetAnimationCurves(), GetEditableAnimationCurves(), and GetEditableAnimationCurves().
CustomAttributes
UE::Anim::FMeshAttributeContainer USkeletalMeshComponent::CustomAttributes private
Definition at line 477 of file SkeletalMeshComponent.h.
Referenced by UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
DefaultValue [1/5]
const FName float USkeletalMeshComponent::DefaultValue
Definition at line 538 of file SkeletalMeshComponent.h.
Referenced by FindAttributeChecked().
DefaultValue [2/5]
const FName FTransform USkeletalMeshComponent::DefaultValue
Definition at line 550 of file SkeletalMeshComponent.h.
DefaultValue [3/5]
const FName int32 USkeletalMeshComponent::DefaultValue
Definition at line 563 of file SkeletalMeshComponent.h.
DefaultValue [4/5]
const FName FString USkeletalMeshComponent::DefaultValue
Definition at line 576 of file SkeletalMeshComponent.h.
DefaultValue [5/5]
float USkeletalMeshComponent::DefaultValue
Definition at line 586 of file SkeletalMeshComponent.h.
DeferredKinematicUpdateIndex
UPROPERTY () uint8 bHasValidBodies UPROPERTY () uint8 bBlendPhysics UPROPERTY () uint8 bEnablePhysicsOnDedicatedServer UPROPERTY () uint8 bUpdateMeshWhenKinematic UPROPERTY () uint8 bUpdateJointsFromAnimation UPROPERTY () uint8 bAllowClothActors UPROPERTY () uint8 bDisableClothSimulation int32 USkeletalMeshComponent::DeferredKinematicUpdateIndex
If true, there is at least one body in the current PhysicsAsset with a valid bone in the current SkeletalMesh.
Forces use of the physics bodies irrespective of whether they are simulated or using the physics blend weight If true, simulate physics for this component on a dedicated server. This should be set if simulating physics and replicating with a dedicated server. Note: This property cannot be changed at runtime. If true, then the physics bodies will be used to drive the skeletal mesh even when they are kinematic (not simulating), otherwise the skeletal mesh will be driven by the animation input when the bodies are kinematic If we should pass joint position to joints each frame, so that they can be used by motorized joints to drive the ragdoll based on the animation. Toggles creation of cloth simulation. Distinct from the simulation toggle below in that, if off, avoids allocating the actors entirely instead of just skipping the simulation step. Disable cloth simulation and play original animation without simulation Indicates that this SkeletalMeshComponent has deferred kinematic bone updates until next physics sim if not INDEX_NONE.
Definition at line 691 of file SkeletalMeshComponent.h.
EndPhysicsTickFunction
FSkeletalMeshComponentEndPhysicsTickFunction USkeletalMeshComponent::EndPhysicsTickFunction protected
Definition at line 2493 of file SkeletalMeshComponent.h.
FillComponentSpaceTransformsRequiredBones
TArray<FBoneIndexType> USkeletalMeshComponent::FillComponentSpaceTransformsRequiredBones
Temporary array of bone indices required to populate component space transforms.
Definition at line 1467 of file SkeletalMeshComponent.h.
FSkeletalMeshComponentClothTickFunction
friend USkeletalMeshComponent::FSkeletalMeshComponentClothTickFunction private
Let the cloth tick and completion tasks have access to private clothing data.
Definition at line 1572 of file SkeletalMeshComponent.h.
HitLocation
FVector USkeletalMeshComponent::HitLocation
Definition at line 2334 of file SkeletalMeshComponent.h.
InAnimInstance
UAnimInstance * USkeletalMeshComponent::InAnimInstance
Definition at line 2093 of file SkeletalMeshComponent.h.
Referenced by EvaluateAnimation(), PerformAnimationEvaluation(), and PerformAnimationProcessing().
InBoneName
FVector FName USkeletalMeshComponent::InBoneName
Definition at line 2334 of file SkeletalMeshComponent.h.
Referenced by GetTotalMassBelowBone(), and UFUNCTION().
InClass
TSubclassOf< UAnimInstance > USkeletalMeshComponent::InClass { LinkAnimGraphByTag(InTag, InClass)
Definition at line 1081 of file SkeletalMeshComponent.h.
Referenced by UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
InDamping
float USkeletalMeshComponent::InDamping
Definition at line 2242 of file SkeletalMeshComponent.h.
InForceLimit
float float USkeletalMeshComponent::InForceLimit
Definition at line 2242 of file SkeletalMeshComponent.h.
InOutPose
FCompactPose& USkeletalMeshComponent::InOutPose
Definition at line 2107 of file SkeletalMeshComponent.h.
Referenced by EvaluatePostProcessMeshInstance().
InSkeletalMesh
FCompactPose FBlendedHeapCurve const USkeletalMesh* USkeletalMeshComponent::InSkeletalMesh
Definition at line 2107 of file SkeletalMeshComponent.h.
Referenced by EvaluateAnimation(), EvaluatePostProcessMeshInstance(), PerformAnimationEvaluation(), and PerformAnimationProcessing().
InSourcePhysicsAsset
UPhysicsAsset * USkeletalMeshComponent::InSourcePhysicsAsset
Definition at line 2434 of file SkeletalMeshComponent.h.
Referenced by UFUNCTION().
LinearVelocity
const FVector& USkeletalMeshComponent::LinearVelocity
Definition at line 2204 of file SkeletalMeshComponent.h.
LookupType [1/5]
const FName ECustomBoneAttributeLookup USkeletalMeshComponent::LookupType = ECustomBoneAttributeLookup::BoneOnly)
Definition at line 489 of file SkeletalMeshComponent.h.
Referenced by FindAttributeChecked(), UPARAM(), UPARAM(), and UPARAM().
LookupType [2/5]
const FName float float ECustomBoneAttributeLookup USkeletalMeshComponent::LookupType = ECustomBoneAttributeLookup::BoneOnly)
Definition at line 538 of file SkeletalMeshComponent.h.
LookupType [3/5]
const FName FTransform FTransform ECustomBoneAttributeLookup USkeletalMeshComponent::LookupType = ECustomBoneAttributeLookup::BoneOnly)
Definition at line 550 of file SkeletalMeshComponent.h.
LookupType [4/5]
const FName int32 int32 ECustomBoneAttributeLookup USkeletalMeshComponent::LookupType = ECustomBoneAttributeLookup::BoneOnly)
Definition at line 563 of file SkeletalMeshComponent.h.
LookupType [5/5]
const FName FString FString ECustomBoneAttributeLookup USkeletalMeshComponent::LookupType = ECustomBoneAttributeLookup::BoneOnly)
Definition at line 576 of file SkeletalMeshComponent.h.
MorphTargetCurves
float USkeletalMeshComponent::MorphTargetCurves private
Definition at line 1649 of file SkeletalMeshComponent.h.
Referenced by GetMorphTargetCurves().
Normal
FVector FVector& USkeletalMeshComponent::Normal
Definition at line 1929 of file SkeletalMeshComponent.h.
OnBoneTransformsFinalizedMC
FOnBoneTransformsFinalizedMultiCast USkeletalMeshComponent::OnBoneTransformsFinalizedMC private
Multicaster fired when this component bone transforms are finalized.
Definition at line 2763 of file SkeletalMeshComponent.h.
OnLODRequiredBonesUpdate_Member
FOnLODRequiredBonesUpdateMulticast USkeletalMeshComponent::OnLODRequiredBonesUpdate_Member private
Definition at line 2767 of file SkeletalMeshComponent.h.
OnLODRequiredBonesUpdate_Static
FOnLODRequiredBonesUpdateMulticast USkeletalMeshComponent::OnLODRequiredBonesUpdate_Static static private
Multicaster fired when this component finalizes the regeneration of the required bones list for the current LOD.
Definition at line 2766 of file SkeletalMeshComponent.h.
OnSkelMeshPhysicsCreated
FOnSkelMeshPhysicsCreatedMultiCast USkeletalMeshComponent::OnSkelMeshPhysicsCreated private
Multicaster fired when this component creates physics state (in case external objects rely on physics state)
Definition at line 2757 of file SkeletalMeshComponent.h.
OnSkelMeshPhysicsTeleported
FOnSkelMeshTeleportedMultiCast USkeletalMeshComponent::OnSkelMeshPhysicsTeleported private
Multicaster fired when this component teleports.
Definition at line 2760 of file SkeletalMeshComponent.h.
OutAttributes
UAnimInstance bool TArray<FTransform> TArray<FTransform> FVector FBlendedHeapCurve UE::Anim::FMeshAttributeContainer& USkeletalMeshComponent::OutAttributes
Definition at line 2099 of file SkeletalMeshComponent.h.
Referenced by EvaluateAnimation(), EvaluatePostProcessMeshInstance(), PerformAnimationEvaluation(), and PerformAnimationProcessing().
OutBoneSpaceTransforms [1/2]
UAnimInstance TArray<FTransform> TArray<FTransform>& USkeletalMeshComponent::OutBoneSpaceTransforms
Definition at line 2093 of file SkeletalMeshComponent.h.
Referenced by EvaluatePostProcessMeshInstance(), FinalizePoseEvaluationResult(), PerformAnimationEvaluation(), and PerformAnimationProcessing().
OutBoneSpaceTransforms [2/2]
UAnimInstance bool TArray<FTransform> TArray<FTransform>& USkeletalMeshComponent::OutBoneSpaceTransforms
Definition at line 2099 of file SkeletalMeshComponent.h.
OutClothSimData
FClothSimulData& USkeletalMeshComponent::OutClothSimData
Definition at line 1684 of file SkeletalMeshComponent.h.
OutConstraints [1/2]
TArray<FConstraintInstanceAccessor>& USkeletalMeshComponent::OutConstraints
Definition at line 2348 of file SkeletalMeshComponent.h.
Referenced by InstantiatePhysicsAsset(), InstantiatePhysicsAsset_Internal(), and InstantiatePhysicsAssetRefPose().
OutConstraints [2/2]
bool bool bool TArray<FConstraintInstanceAccessor>& USkeletalMeshComponent::OutConstraints
Definition at line 2359 of file SkeletalMeshComponent.h.
OutCurve [1/3]
UAnimInstance TArray<FTransform> TArray<FTransform> FVector FBlendedHeapCurve& USkeletalMeshComponent::OutCurve
Definition at line 2093 of file SkeletalMeshComponent.h.
Referenced by EvaluateAnimation(), EvaluatePostProcessMeshInstance(), PerformAnimationEvaluation(), and PerformAnimationProcessing().
OutCurve [2/3]
UAnimInstance bool TArray<FTransform> TArray<FTransform> FVector FBlendedHeapCurve& USkeletalMeshComponent::OutCurve
Definition at line 2099 of file SkeletalMeshComponent.h.
OutCurve [3/3]
FCompactPose FBlendedHeapCurve& USkeletalMeshComponent::OutCurve
Definition at line 2107 of file SkeletalMeshComponent.h.
OutRequiredBones
TArray<FBoneIndexType>& USkeletalMeshComponent::OutRequiredBones
Definition at line 1754 of file SkeletalMeshComponent.h.
Referenced by ComputeRequiredBones(), ExcludeHiddenBones(), GetRequiredVirtualBones(), and GetShadowShapeRequiredBones().
OutRootBoneTranslation [1/3]
UAnimInstance TArray<FTransform> TArray<FTransform> FVector& USkeletalMeshComponent::OutRootBoneTranslation
Definition at line 2093 of file SkeletalMeshComponent.h.
Referenced by EvaluateAnimation(), EvaluatePostProcessMeshInstance(), FinalizePoseEvaluationResult(), PerformAnimationEvaluation(), and PerformAnimationProcessing().
OutRootBoneTranslation [2/3]
UAnimInstance bool TArray<FTransform> TArray<FTransform> FVector& USkeletalMeshComponent::OutRootBoneTranslation
Definition at line 2099 of file SkeletalMeshComponent.h.
OutRootBoneTranslation [3/3]
FCompactPose FBlendedHeapCurve const USkeletalMesh FVector& USkeletalMeshComponent::OutRootBoneTranslation
Definition at line 2107 of file SkeletalMeshComponent.h.
OutSpaceBases [1/2]
UAnimInstance TArray<FTransform>& USkeletalMeshComponent::OutSpaceBases
Definition at line 2093 of file SkeletalMeshComponent.h.
Referenced by PerformAnimationEvaluation(), and PerformAnimationProcessing().
OutSpaceBases [2/2]
UAnimInstance bool TArray<FTransform>& USkeletalMeshComponent::OutSpaceBases
Definition at line 2099 of file SkeletalMeshComponent.h.
OutValue [1/4]
const FName float float& USkeletalMeshComponent::OutValue
Definition at line 538 of file SkeletalMeshComponent.h.
Referenced by FindAttributeChecked(), UPARAM(), UPARAM(), and UPARAM().
OutValue [2/4]
const FName FTransform FTransform& USkeletalMeshComponent::OutValue
Definition at line 550 of file SkeletalMeshComponent.h.
OutValue [3/4]
const FName int32 int32& USkeletalMeshComponent::OutValue
Definition at line 563 of file SkeletalMeshComponent.h.
OutValue [4/4]
const FName FString FString& USkeletalMeshComponent::OutValue
Definition at line 576 of file SkeletalMeshComponent.h.
OverrideLocalRootComponent
FClothSimulData USkeletalMeshComponent* USkeletalMeshComponent::OverrideLocalRootComponent = nullptr)
Definition at line 1684 of file SkeletalMeshComponent.h.
ParallelAnimationEvaluationTask
FGraphEventRef USkeletalMeshComponent::ParallelAnimationEvaluationTask private
Definition at line 2529 of file SkeletalMeshComponent.h.
Referenced by IsRunningParallelEvaluation().
ParallelBlendPhysicsCompletionTask
FGraphEventRef USkeletalMeshComponent::ParallelBlendPhysicsCompletionTask private
Definition at line 2532 of file SkeletalMeshComponent.h.
ParallelClothTask
FGraphEventRef USkeletalMeshComponent::ParallelClothTask private
Ref for the clothing parallel task, so we can detect whether or not a sim is running.
Definition at line 1607 of file SkeletalMeshComponent.h.
PendingRadialForces
TArray<FPendingRadialForces> USkeletalMeshComponent::PendingRadialForces
Array of physical interactions for the frame.
This is a temporary solution for a more permanent force system and should not be used directly
Definition at line 987 of file SkeletalMeshComponent.h.
Referenced by GetPendingRadialForces().
PendingTeleportType
ETeleportType USkeletalMeshComponent::PendingTeleportType private
Teleport type to use on the next update.
Definition at line 628 of file SkeletalMeshComponent.h.
PhysicsBlendWeight
float USkeletalMeshComponent::PhysicsBlendWeight
Definition at line 2226 of file SkeletalMeshComponent.h.
Referenced by UFUNCTION().
PlayRate
bool bool float float USkeletalMeshComponent::PlayRate = 1.f)
Definition at line 1242 of file SkeletalMeshComponent.h.
PoseWatches
TArray<FAnimNodePoseWatch> USkeletalMeshComponent::PoseWatches
Definition at line 1710 of file SkeletalMeshComponent.h.
Position
bool bool float USkeletalMeshComponent::Position = 0.f
Definition at line 1242 of file SkeletalMeshComponent.h.
PrevRootBoneMatrix
FMatrix USkeletalMeshComponent::PrevRootBoneMatrix private
previous root bone matrix to compare the difference and decide to do clothing teleport
Definition at line 1582 of file SkeletalMeshComponent.h.
PrevRootRigidBodyScale
FVector3f USkeletalMeshComponent::PrevRootRigidBodyScale private
previous root body scale to compare the difference when the actor scale is updated.
Definition at line 1585 of file SkeletalMeshComponent.h.
ProfileName
FName USkeletalMeshComponent::ProfileName
Definition at line 2246 of file SkeletalMeshComponent.h.
Referenced by GetConstraintProfilePropertiesOrDefault().
RagdollAggregateThreshold
int32 USkeletalMeshComponent::RagdollAggregateThreshold
Threshold for physics asset bodies above which we use an aggregate for broadphase collisions.
Definition at line 921 of file SkeletalMeshComponent.h.
ReinitAnimInstances
bool USkeletalMeshComponent::ReinitAnimInstances = true)
Definition at line 406 of file SkeletalMeshComponent.h.
RequiredBones
TArray<FBoneIndexType> USkeletalMeshComponent::RequiredBones
Temporary array of bone indices required this frame.
Filled in by UpdateSkelPose.
Definition at line 1464 of file SkeletalMeshComponent.h.
Referenced by ParallelBlendPhysics().
[struct]
struct { ... } USkeletalMeshComponent::RootBodyData
Index of the 'Root Body', or top body in the asset hierarchy.
Filled in by InitInstance, so we don't need to save it. To save root body index/bone index consistently
SharedRequiredBones
TSharedPtr<struct FBoneContainer> USkeletalMeshComponent::SharedRequiredBones private
Shared bone container between all anim instances owned by this skeletal mesh component.
Definition at line 460 of file SkeletalMeshComponent.h.
Swing1Angle
float& USkeletalMeshComponent::Swing1Angle
Definition at line 2377 of file SkeletalMeshComponent.h.
Swing1LimitAngle
float USkeletalMeshComponent::Swing1LimitAngle
Definition at line 2368 of file SkeletalMeshComponent.h.
Swing2Angle
float float float& USkeletalMeshComponent::Swing2Angle
Definition at line 2377 of file SkeletalMeshComponent.h.
Swing2LimitAngle
float float float USkeletalMeshComponent::Swing2LimitAngle
Definition at line 2368 of file SkeletalMeshComponent.h.
TransformToRoot
FTransform USkeletalMeshComponent::TransformToRoot
Definition at line 1455 of file SkeletalMeshComponent.h.
TwistAngle
float float& USkeletalMeshComponent::TwistAngle
Definition at line 2377 of file SkeletalMeshComponent.h.
TwistLimitAngle
float float USkeletalMeshComponent::TwistLimitAngle
Definition at line 2368 of file SkeletalMeshComponent.h.
Value
float USkeletalMeshComponent::Value
Definition at line 1250 of file SkeletalMeshComponent.h.
The documentation for this class was generated from the following file:
Runtime/Engine/Classes/Components/SkeletalMeshComponent.h