Unreal Engine 5.6 C++ API: UE::Sequencer::FDynamicExtensionContainer Class Reference
UE::Sequencer::FDynamicExtensionContainer Class Reference
Base class for supporting dynamic extensions that participate in dynamic casting.
#include "DynamicExtensionContainer.h"
Data Structures
struct FDynamicExtensionInfo
Public Member Functions
FDynamicExtensionContainer ()=default
FDynamicExtensionContainer (const FDynamicExtensionContainer &)=delete
virtual ~FDynamicExtensionContainer ()
template<typename T>
T * CastDynamic ()
void * CastDynamic (FViewModelTypeID Type)
SEQUENCERCORE_API const void * CastDynamic (FViewModelTypeID Type) const
template<typename T>
T * CastDynamicChecked ()
template<typename T>
const T * CastDynamicChecked () const
void * CastDynamicChecked (FViewModelTypeID Type)
const void * CastDynamicChecked (FViewModelTypeID Type) const
template<typename T>
TDynamicExtensionContainerIteratorProxy< T > FilterDynamic ()
FDynamicExtensionContainer & operator= (const FDynamicExtensionContainer &)=delete
SEQUENCERCORE_API void RemoveDynamicExtension (FViewModelTypeID Type)
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID_API (SEQUENCERCORE_API, FDynamicExtensionContainer) template< typename T > const T *CastDynamic() const
Protected Member Functions
template<typename T, typename... InArgTypes>
T & AddDynamicExtension (TSharedRef< FViewModel > InOwner, InArgTypes &&... Args)
void PostInitializeExtensions ()
void ReinitializeExtensions ()
template<typename T>
void RemoveDynamicExtension ()
Private Attributes
TArray< FDynamicExtensionInfo > DynamicExtensions
Friends
struct FDynamicExtensionContainerIterator
template<typename T>
struct TDynamicExtensionContainerIteratorProxy
Detailed Description
Base class for supporting dynamic extensions that participate in dynamic casting.
Definition at line 55 of file DynamicExtensionContainer.h.
Constructor & Destructor Documentation
~FDynamicExtensionContainer()
virtual UE::Sequencer::FDynamicExtensionContainer::~FDynamicExtensionContainer () inline virtual
Definition at line 59 of file DynamicExtensionContainer.h.
FDynamicExtensionContainer() [1/2]
UE::Sequencer::FDynamicExtensionContainer::FDynamicExtensionContainer () default
Referenced by FDynamicExtensionContainer(), CastDynamic(), CastDynamic(), CastDynamicChecked(), operator=(), UE::Sequencer::FViewModel::UE_SEQUENCER_DECLARE_CASTABLE(), and UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID_API().
FDynamicExtensionContainer() [2/2]
UE::Sequencer::FDynamicExtensionContainer::FDynamicExtensionContainer (const FDynamicExtensionContainer &) delete
References FDynamicExtensionContainer().
Member Function Documentation
AddDynamicExtension()
template<typename T, typename... InArgTypes> T & UE::Sequencer::FDynamicExtensionContainer::AddDynamicExtension (TSharedRef< FViewModel > InOwner, InArgTypes &&... Args) inline protected
Definition at line 127 of file DynamicExtensionContainer.h.
References CastDynamic(), DynamicExtensions, Forward(), TSharedRef< ObjectType, InMode >::Get(), and MakeShared().
Referenced by UE::Sequencer::FViewModel::AddDynamicExtension().
CastDynamic() [1/3]
template<typename T> T * UE::Sequencer::FDynamicExtensionContainer::CastDynamic () inline
Definition at line 85 of file DynamicExtensionContainer.h.
References FDynamicExtensionContainer().
Referenced by AddDynamicExtension(), CastDynamicChecked(), CastDynamicChecked(), UE::Sequencer::FViewModel::CastThisShared(), UE::Sequencer::FViewModel::CastThisShared(), UE::Sequencer::FViewModel::CastThisSharedChecked(), and UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID_API().
CastDynamic() [2/3]
void * UE::Sequencer::FDynamicExtensionContainer::CastDynamic (FViewModelTypeID Type) inline
Definition at line 112 of file DynamicExtensionContainer.h.
References FDynamicExtensionContainer().
CastDynamic() [3/3]
SEQUENCERCORE_API const void * UE::Sequencer::FDynamicExtensionContainer::CastDynamic (FViewModelTypeID Type) const
CastDynamicChecked() [1/4]
template<typename T> T * UE::Sequencer::FDynamicExtensionContainer::CastDynamicChecked () inline
Definition at line 91 of file DynamicExtensionContainer.h.
References FDynamicExtensionContainer().
CastDynamicChecked() [2/4]
template<typename T> const T * UE::Sequencer::FDynamicExtensionContainer::CastDynamicChecked () const inline
Definition at line 78 of file DynamicExtensionContainer.h.
References CastDynamicChecked().
Referenced by CastDynamicChecked(), and UE::Sequencer::FViewModel::CastThisSharedChecked().
CastDynamicChecked() [3/4]
void * UE::Sequencer::FDynamicExtensionContainer::CastDynamicChecked (FViewModelTypeID Type) inline
Definition at line 117 of file DynamicExtensionContainer.h.
References CastDynamic(), and check.
CastDynamicChecked() [4/4]
const void * UE::Sequencer::FDynamicExtensionContainer::CastDynamicChecked (FViewModelTypeID Type) const inline
Definition at line 105 of file DynamicExtensionContainer.h.
References CastDynamic(), and check.
FilterDynamic()
template<typename T> TDynamicExtensionContainerIteratorProxy< T > UE::Sequencer::FDynamicExtensionContainer::FilterDynamic () inline
Definition at line 97 of file DynamicExtensionContainer.h.
References TDynamicExtensionContainerIteratorProxy.
operator=()
FDynamicExtensionContainer & UE::Sequencer::FDynamicExtensionContainer::operator= (const FDynamicExtensionContainer &) delete
References FDynamicExtensionContainer().
PostInitializeExtensions()
void UE::Sequencer::FDynamicExtensionContainer::PostInitializeExtensions () inline protected
Definition at line 147 of file DynamicExtensionContainer.h.
References DynamicExtensions.
ReinitializeExtensions()
void UE::Sequencer::FDynamicExtensionContainer::ReinitializeExtensions () inline protected
Definition at line 167 of file DynamicExtensionContainer.h.
References DynamicExtensions.
RemoveDynamicExtension() [1/2]
template<typename T> void UE::Sequencer::FDynamicExtensionContainer::RemoveDynamicExtension () inline protected
Definition at line 142 of file DynamicExtensionContainer.h.
References RemoveDynamicExtension().
Referenced by RemoveDynamicExtension().
RemoveDynamicExtension() [2/2]
SEQUENCERCORE_API void UE::Sequencer::FDynamicExtensionContainer::RemoveDynamicExtension (FViewModelTypeID Type)
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID_API()
UE::Sequencer::FDynamicExtensionContainer::UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID_API (SEQUENCERCORE_API , FDynamicExtensionContainer) const inline
Definition at line 68 of file DynamicExtensionContainer.h.
References FDynamicExtensionContainer(), and CastDynamic().
Friends And Related Symbol Documentation
FDynamicExtensionContainerIterator
friend struct FDynamicExtensionContainerIterator friend
Definition at line 189 of file DynamicExtensionContainer.h.
References FDynamicExtensionContainerIterator.
Referenced by FDynamicExtensionContainerIterator.
TDynamicExtensionContainerIteratorProxy
template<typename T> friend struct TDynamicExtensionContainerIteratorProxy friend
Definition at line 190 of file DynamicExtensionContainer.h.
References TDynamicExtensionContainerIteratorProxy.
Referenced by FilterDynamic(), and TDynamicExtensionContainerIteratorProxy.
Field Documentation
DynamicExtensions
TArray<FDynamicExtensionInfo> UE::Sequencer::FDynamicExtensionContainer::DynamicExtensions private
Definition at line 198 of file DynamicExtensionContainer.h.
Referenced by AddDynamicExtension(), PostInitializeExtensions(), and ReinitializeExtensions().
The documentation for this class was generated from the following file:
Editor/SequencerCore/Public/MVVM/Extensions/DynamicExtensionContainer.h