Unreal Engine 5.6 C++ API: FShaderCompileJob Class Reference
FShaderCompileJob Class Reference
Stores all of the input and output information used to compile a single shader.
#include "ShaderCompilerJobTypes.h"
Public Member Functions
FShaderCompileJob ()
FShaderCompileJob (uint32 InHash, uint32 InId, EShaderCompileJobPriority InPriroity, const FShaderCompileJobKey &InKey)
virtual RENDERCORE_API void AppendDebugName (FStringBuilderBase &OutName) const override
virtual RENDERCORE_API void AppendDiagnostics (FString &OutDiagnostics, int32 InJobIndex, int32 InNumJobs, const TCHAR *Indentation=nullptr) const override final
Generates a diagnostics string for this compile job suitable for the output log.
RENDERCORE_API FStringView GetFinalSourceView () const
virtual RENDERCORE_API FShaderCompilerInputHash GetInputHash () override
Returns hash of all inputs for this job (needed for caching).
virtual RENDERCORE_API void OnComplete () override
RENDERCORE_API void SerializeArtifact (FArchive &Ar)
virtual void SerializeOutput (FArchive &Ar) override
virtual void SerializeOutput (FShaderCacheSerializeContext &Ctx)
Serializes (and deserializes) the output for caching purposes.
RENDERCORE_API void SerializeOutput (FShaderCacheSerializeContext &Ctx, int32 CodeIndex)
RENDERCORE_API void SerializeWorkerInput (FArchive &Ar)
RENDERCORE_API void SerializeWorkerOutput (FArchive &Ar)
Public Member Functions inherited from FShaderCommonCompileJob
uint32 AddRef () const
bool Equals (const FShaderCommonCompileJob &Rhs) const
void ForEachSingleShaderJob (const TFunction< void(const FShaderCompileJob &SingleJob)> &Predicate) const
Calls the specified predicate for each single compile job, i.e.
void ForEachSingleShaderJob (const TFunction< void(FShaderCompileJob &SingleJob)> &Predicate)
uint32 GetRefCount () const
FShaderPipelineCompileJob * GetShaderPipelineJob ()
const FShaderPipelineCompileJob * GetShaderPipelineJob () const
FShaderCompileJob * GetSingleShaderJob ()
const FShaderCompileJob * GetSingleShaderJob () const
uint32 Release () const
void UpdateInputHash ()
void UpdateStatus (EShaderCompileJobStatus NewStatus)
Data Fields
FShaderCompilerInput Input
Input for the shader compile.
FShaderCompileJobKey Key
FShaderCompilerOutput Output
FShaderPreprocessOutput PreprocessOutput
TUniquePtr< FShaderCompilerOutput > SecondaryOutput {}
TUniquePtr< FShaderPreprocessOutput > SecondaryPreprocessOutput {}
TSharedPtr< const FShaderType::FParameters, ESPMode::ThreadSafe > ShaderParameters
Additional parameters that can be supplied to the compile job such that it is available from the compilation begins to when the FShader is created.
TMap< const FVertexFactoryType *, TArray< const FShaderPipelineType * > > SharingPipelines
Data Fields inherited from FShaderCommonCompileJob
uint8 bBypassCache: 1
Whether or not to bypass the job/ddc caches when executing this job.
uint8 bErrorsAreLikelyToBeCode: 1
uint8 bFinalized: 1
true if the results of the shader compile have been processed.
uint8 bInputHashSet: 1
Whether we hashed the inputs.
uint8 bIsDefaultMaterial: 1
Whether or not we are a default material.
uint8 bIsGlobalShader: 1
Whether or not we are a global shader.
uint8 bReleased: 1
true if the results of the shader compile have been released from the FShaderCompilerManager.
uint8 bSucceeded: 1
Output of the shader compile.
EShaderCompilerWorkerType CurrentWorker
uint32 Hash
uint32 Id
Id of the shader map this shader belongs to.
FShaderCompilerInputHash InputHash
Hash of all the job inputs.
FShaderJobCacheRef JobCacheRef
int32 JobIndex
TSharedPtr< FShaderCompileJobStatus > JobStatusPtr
FShaderCommonCompileJob * NextLink = nullptr
Linked list support – not using TIntrusiveLinkedList because we want lock free insertion not supported by the core class.
FThreadSafeCounter NumRefs
EShaderCompileJobPriority PendingPriority
FPendingShaderMapCompileResultsPtr PendingShaderMap
FShaderCommonCompileJob ** PrevLink = nullptr
EShaderCompileJobPriority Priority
TPimplPtr< UE::DerivedData::FRequestOwner > RequestOwner
double TimeAddedToPendingQueue = 0.0
In-engine timestamp of being added to a pending queue.
double TimeAssignedToExecution = 0.0
In-engine timestamp of being assigned to a worker.
double TimeExecutionCompleted = 0.0
In-engine timestamp of job being completed.
double TimeTaskSubmitJobs = 0.0
Time spent in tasks generated in FShaderJobCache::SubmitJobs, plus stall time on mutex locks in those tasks.
double TimeTaskSubmitJobsStall = 0.0
EShaderCompileJobType Type
Static Public Attributes
static const EShaderCompileJobType Type = EShaderCompileJobType::Single
Private Member Functions
void SerializeWorkerOutputInner (FArchive &Ar, bool bSerializeForArtifact=false)
Additional Inherited Members
Static Public Member Functions inherited from FShaderCommonCompileJob
static RENDERCORE_API uint32 GetNextJobId ()
This returns a unique id for a shader compiler job.
Protected Member Functions inherited from FShaderCommonCompileJob
FShaderCommonCompileJob (EShaderCompileJobType InType, uint32 InHash, uint32 InId, EShaderCompileJobPriority InPriority)
virtual ~FShaderCommonCompileJob ()
Detailed Description
Stores all of the input and output information used to compile a single shader.
Definition at line 322 of file ShaderCompilerJobTypes.h.
Constructor & Destructor Documentation
FShaderCompileJob() [1/2]
FShaderCompileJob::FShaderCompileJob () inline
Definition at line 375 of file ShaderCompilerJobTypes.h.
References FShaderCommonCompileJob::FShaderCommonCompileJob(), FShaderCompileJob(), Num, and Type.
Referenced by FShaderCompileJob().
FShaderCompileJob() [2/2]
FShaderCompileJob::FShaderCompileJob (uint32 InHash, uint32 InId, EShaderCompileJobPriority InPriroity, const FShaderCompileJobKey & InKey) inline
Definition at line 378 of file ShaderCompilerJobTypes.h.
References FShaderCommonCompileJob::FShaderCommonCompileJob(), Key, and Type.
Member Function Documentation
AppendDebugName()
virtual RENDERCORE_API void FShaderCompileJob::AppendDebugName (FStringBuilderBase & OutName) const override virtual
Implements FShaderCommonCompileJob.
AppendDiagnostics()
virtual RENDERCORE_API void FShaderCompileJob::AppendDiagnostics (FString & OutDiagnostics, int32 InJobIndex, int32 InNumJobs, const TCHAR * Indentation = nullptr) const final override virtual
Generates a diagnostics string for this compile job suitable for the output log.
Implements FShaderCommonCompileJob.
GetFinalSourceView()
RENDERCORE_API FStringView FShaderCompileJob::GetFinalSourceView () const
GetInputHash()
virtual RENDERCORE_API FShaderCompilerInputHash FShaderCompileJob::GetInputHash () override virtual
Returns hash of all inputs for this job (needed for caching).
Reimplemented from FShaderCommonCompileJob.
OnComplete()
virtual RENDERCORE_API void FShaderCompileJob::OnComplete () override virtual
Implements FShaderCommonCompileJob.
SerializeArtifact()
RENDERCORE_API void FShaderCompileJob::SerializeArtifact (FArchive & Ar)
References Ar.
SerializeOutput() [1/3]
virtual void FShaderCompileJob::SerializeOutput (FArchive & Ar) inline override virtual
Reimplemented from FShaderCommonCompileJob.
Definition at line 348 of file ShaderCompilerJobTypes.h.
References Ar, and SerializeOutput().
Referenced by SerializeOutput(), and SerializeOutput().
SerializeOutput() [2/3]
virtual void FShaderCompileJob::SerializeOutput (FShaderCacheSerializeContext & Ctx) inline virtual
Serializes (and deserializes) the output for caching purposes.
Reimplemented from FShaderCommonCompileJob.
Definition at line 353 of file ShaderCompilerJobTypes.h.
References SerializeOutput().
SerializeOutput() [3/3]
RENDERCORE_API void FShaderCompileJob::SerializeOutput (FShaderCacheSerializeContext & Ctx, int32 CodeIndex)
SerializeWorkerInput()
RENDERCORE_API void FShaderCompileJob::SerializeWorkerInput (FArchive & Ar)
References Ar.
SerializeWorkerOutput()
RENDERCORE_API void FShaderCompileJob::SerializeWorkerOutput (FArchive & Ar)
References Ar.
SerializeWorkerOutputInner()
void FShaderCompileJob::SerializeWorkerOutputInner (FArchive & Ar, bool bSerializeForArtifact = false) private
References Ar.
Field Documentation
Input
FShaderCompilerInput FShaderCompileJob::Input
Input for the shader compile.
Definition at line 336 of file ShaderCompilerJobTypes.h.
Key
FShaderCompileJobKey FShaderCompileJob::Key
Definition at line 327 of file ShaderCompilerJobTypes.h.
Referenced by FShaderCompileJob(), and FShaderCommonCompileJob::Equals().
Output
FShaderCompilerOutput FShaderCompileJob::Output
Definition at line 339 of file ShaderCompilerJobTypes.h.
PreprocessOutput
FShaderPreprocessOutput FShaderCompileJob::PreprocessOutput
Definition at line 337 of file ShaderCompilerJobTypes.h.
SecondaryOutput
TUniquePtr<FShaderCompilerOutput> FShaderCompileJob::SecondaryOutput {}
Definition at line 340 of file ShaderCompilerJobTypes.h.
SecondaryPreprocessOutput
TUniquePtr<FShaderPreprocessOutput> FShaderCompileJob::SecondaryPreprocessOutput {}
Definition at line 338 of file ShaderCompilerJobTypes.h.
ShaderParameters
TSharedPtr<const FShaderType::FParameters, ESPMode::ThreadSafe> FShaderCompileJob::ShaderParameters
Additional parameters that can be supplied to the compile job such that it is available from the compilation begins to when the FShader is created.
Definition at line 333 of file ShaderCompilerJobTypes.h.
SharingPipelines
TMap<const FVertexFactoryType*, TArray<const FShaderPipelineType*> > FShaderCompileJob::SharingPipelines
Definition at line 343 of file ShaderCompilerJobTypes.h.
Type
const EShaderCompileJobType FShaderCompileJob::Type = EShaderCompileJobType::Single static
Definition at line 325 of file ShaderCompilerJobTypes.h.
Referenced by FShaderCompileJob(), and FShaderCompileJob().
The documentation for this class was generated from the following file:
Runtime/RenderCore/Public/ShaderCompilerJobTypes.h