Unreal Engine 5.6 C++ API: UE::Sequencer::FTrackModel Class Reference
UE::Sequencer::FTrackModel Class Reference
#include "TrackModel.h"
Public Member Functions
FTrackModel (UMovieSceneTrack *Track)
~FTrackModel ()
void BuildContextMenu (FMenuBuilder &MenuBuilder) override
Get context menu contents.
void BuildSidebarMenu (FMenuBuilder &MenuBuilder) override
bool CanDelete (FText *OutErrorMessage) const override
bool CanDrag () const override
Returns whether the model can be dragged.
bool CanRename () const override
void CreateCurveModels (TArray< TUniquePtr< FCurveModel > > &OutCurveModels) override
Populate the specified array with curve models that are represented by this tree item.
TSharedPtr< SWidget > CreateOutlinerViewForColumn (const FCreateOutlinerViewParams &InParams, const FName &InColumnName) override
Create the visual outliner widget for the specified column.
void Delete () override
const UMovieSceneCondition * GetCondition () const override
EConditionableConditionState GetConditionState () const override
Returns condition state for this item.
bool GetDefaultExpansionState () const override
Get the default expansion state if it wasn't saved in the movie-scene data.
const FSlateBrush * GetIconBrush () const override
Gets the icon for the outliner item.
void GetIdentifierForGrouping (TStringBuilder< 128 > &OutString) const override
FText GetLabel () const override
Gets the label for the outliner item.
FSlateColor GetLabelColor () const override
Gets the color for the outliner item label.
FSlateFontInfo GetLabelFont () const override
Gets the font for the outliner item.
FText GetLabelToolTipText () const override
Gets the tooltip text for the outliner item.
ELockableLockState GetLockState () const override
Returns whether this item is locked.
FOutlinerSizing GetOutlinerSizing () const override
Return the desired size for the owning model.
int32 GetRowIndex () const override
FViewModelChildren GetSectionModels () override
FSortingKey GetSortingKey () const override
Called by the part to sort this model among its siblings.
FViewModelChildren GetTopLevelChannels ()
FViewModelVariantIterator GetTopLevelChildTrackAreaModels () const override
UMovieSceneTrack * GetTrack () const override
FViewModelVariantIterator GetTrackAreaModelList () const override
FTrackAreaParameters GetTrackAreaParameters () const override
TSharedPtr< ISequencerTrackEditor > GetTrackEditor () const override
bool HasCurves () const override
Whether this view-model has any curves and needs to have a curve editor item created.
bool IsDimmed () const override
bool IsRenameValidImpl (const FText &NewName, FText &OutErrorMessage) const override
bool IsResizable () const override
virtual void OnConstruct () override
Called once for this model when it is added to a parent that has valid shared data.
virtual void OnDeferredModifyFlush () override
void OnModifiedDirectly (UMovieSceneSignedObject *) override
void OnModifiedIndirectly (UMovieSceneSignedObject *) override
void Rename (const FText &NewName) override
void Resize (float NewSize) override
void SetConditionEditorForceTrue (bool bEditorForceTrue) override
Set this item's condition to evaluate true for editor preview purposes.
void SetCustomOrder (int32 InCustomOrder) override
Set a custom sort index for this view model.
void SetIsLocked (bool bIsLocked) override
Set whether this item is locked.
void SortChildren () override
Called when the model should sort its immediate children.
UE_SEQUENCER_DECLARE_CASTABLE (FTrackModel, FEvaluableOutlinerItemModel, IRenameableExtension, IResizableExtension, ITrackExtension, ITrackAreaExtension, ILockableExtension, IGroupableExtension, ISortableExtension, IDraggableOutlinerExtension, IDeletableExtension, IConditionableExtension)
Public Member Functions inherited from UE::Sequencer::FEvaluableOutlinerItemModel
virtual bool IsDeactivated () const override
Returns whether this item is deactivated.
bool IsMuted () const override
Returns whether this item is muted.
bool IsSolo () const override
Returns whether this item is solo.
virtual void SetIsDeactivated (const bool bInIsDeactivated) override
Set this item's deactivated state.
void SetIsMuted (bool bIsMuted) override
Set this item's mute state.
void SetIsSoloed (bool bIsSoloed) override
Enable or disable solo for this object.
UE_SEQUENCER_DECLARE_CASTABLE (FEvaluableOutlinerItemModel, FOutlinerItemModel, IMutableExtension, ISoloableExtension, IDeactivatableExtension)
Public Member Functions inherited from UE::Sequencer::FOutlinerItemModel
UE_SEQUENCER_DECLARE_CASTABLE (FOutlinerItemModel, FViewModel, FOutlinerItemModelMixin)
Public Member Functions inherited from UE::Sequencer::TOutlinerModelMixin< FViewModel >
TOutlinerModelMixin (ArgTypes &&... InArgs)
virtual FViewModel * AsViewModel ()
TOutlinerModelMixin< FViewModel > operator= (const TOutlinerModelMixin< FViewModel > &)=delete
Public Member Functions inherited from UE::Sequencer::FViewModel
FViewModel ()
Builds a new data model.
FViewModel (const FViewModel &)=delete
virtual ~FViewModel ()
template<typename T, typename... InArgTypes>
T & AddDynamicExtension (const TViewModelTypeID< T > &TypeID, InArgTypes &&... Args)
Adds a dynamic extension to this data model.
template<typename T, typename... InArgTypes>
T & AddDynamicExtension (InArgTypes &&... Args)
Adds a dynamic extension to this data model.
template<typename T>
TViewModelPtr< T > CastParent () const
Gets the parent data model.
template<typename T>
TViewModelPtr< T > CastThisShared ()
Casts this data model to an extension, or to a child class implementation.
template<typename T>
TViewModelPtr< const T > CastThisShared () const
Casts this data model to an extension, or to a child class implementation.
template<typename T>
TSharedPtr< T > CastThisSharedChecked ()
Casts this data model to an extension, or to a child class implementation.
template<typename T>
TSharedPtr< const T > CastThisSharedChecked () const
Casts this data model to an extension, or to a child class implementation.
void DiscardAllChildren ()
Unlinks the head of the children list.
template<typename T>
TViewModelPtr< T > FindAncestorOfType (bool bIncludeThis=false) const
Finds the first ancestor view model that implements the given type.
FViewModelPtr FindAncestorOfType (FViewModelTypeID Type, bool bIncludeThis=false) const
Finds a parent data model of a given type among the ancestry of this data model.
FViewModelPtr FindAncestorOfTypes (TArrayView< const FViewModelTypeID > Types, bool bIncludeThis=false) const
Finds a parent data model that supports all the given interface types among the ancestry of this data model.
TOptional< FViewModelChildren > FindChildList (EViewModelListType InType)
Retrieve the first child list that matches the specified type (if any)
FParentModelIterator GetAncestors (bool bIncludeThis=false) const
Iterates over the ancestry of this data model.
template<typename T>
TParentModelIterator< T > GetAncestorsOfType (bool bIncludeThis=false) const
Iterates over all ancestors of a given time along the ancestry of this data model.
FViewModelChildren GetChildList (EViewModelListType InType)
Retrieve the first child list that matches the specified type.
FViewModelListIterator GetChildren (EViewModelListType InFilter=EViewModelListType::Everything) const
Gets an iterator for the data model's default children list.
template<typename T>
TViewModelListIterator< T > GetChildrenOfType (EViewModelListType InFilter=EViewModelListType::Everything) const
Gets children of a given type from the view-model's children lists, or the specified list.
FParentFirstChildIterator GetDescendants (bool bIncludeThis=false, EViewModelListType InFilter=EViewModelListType::Everything) const
Gets all children and their descendants in the hierarchy below this data model.
template<typename T>
TParentFirstChildIterator< T > GetDescendantsOfType (bool bIncludeThis=false, EViewModelListType InFilter=EViewModelListType::Everything) const
Gets all children and descendants of a given type in the hierarchy below this data model.
void GetDescendantsOfType (FViewModelTypeID Type, TArray< TSharedPtr< FViewModel > > &OutChildren, EViewModelListType InFilter=EViewModelListType::Everything) const
Gets all children and descendants of a given type in the hierarchy below this data model.
int32 GetHierarchicalDepth () const
Gets the hierarchical depth of this data model, i.e.
uint32 GetModelID () const
Get this model's unique, non-persistent and non-deterministic ID.
TSharedPtr< FViewModel > GetNextSibling () const
Gets the next sibling of this data model in the children list it belongs to.
FViewModelPtr GetParent () const
Gets the parent data model.
TSharedPtr< FViewModel > GetPreviousSibling () const
Gets the next sibling of this data model in the children list it belongs to.
FViewModelPtr GetRoot () const
Returns the root model of the hierarchy, i.e.
TSharedPtr< FSharedViewModelData > GetSharedData () const
bool HasChildren () const
Returns whether this model has any children in any of its child lists.
bool IsConstructed () const
FViewModel & operator= (const FViewModel &)=delete
void RemoveFromParent ()
Remove this model from its parent.
void SetSharedData (TSharedPtr< FSharedViewModelData > InSharedData)
UE_SEQUENCER_DECLARE_CASTABLE (FViewModel, FDynamicExtensionContainer)
Public Member Functions inherited from UE::Sequencer::ICastable
template<typename RetType, typename InterfaceType, typename ... ArgTypes, typename ... ParamTypes>
RetType CastedCall (RetType(InterfaceType::*MemberFunc)(ArgTypes...), ParamTypes &&... InArgs)
template<typename RetType, typename InterfaceType, typename ... ArgTypes, typename ... ParamTypes>
RetType CastedCall (RetType(InterfaceType::*MemberFunc)(ArgTypes...), ParamTypes &&... InArgs) const
void * CastRaw (FViewModelTypeID InType)
const void * CastRaw (FViewModelTypeID InType) const
template<typename T>
T * CastThis ()
template<typename T>
const T * CastThis () const
template<typename T>
T * CastThisChecked ()
template<typename T>
const T * CastThisChecked () const
const FCastableTypeTable & GetTypeTable () const
template<typename T>
bool IsA () const
bool IsA (FViewModelTypeID InType) const
Public Member Functions inherited from TSharedFromThis< FViewModel >
TSharedRef< FViewModel, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FViewModel, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Public Member Functions inherited from UE::Sequencer::FDynamicExtensionContainer
FDynamicExtensionContainer ()=default
FDynamicExtensionContainer (const FDynamicExtensionContainer &)=delete
virtual ~FDynamicExtensionContainer ()
template<typename T>
T * CastDynamic ()
void * CastDynamic (FViewModelTypeID Type)
SEQUENCERCORE_API const void * CastDynamic (FViewModelTypeID Type) const
template<typename T>
T * CastDynamicChecked ()
template<typename T>
const T * CastDynamicChecked () const
void * CastDynamicChecked (FViewModelTypeID Type)
const void * CastDynamicChecked (FViewModelTypeID Type) const
template<typename T>
TDynamicExtensionContainerIteratorProxy< T > FilterDynamic ()
FDynamicExtensionContainer & operator= (const FDynamicExtensionContainer &)=delete
SEQUENCERCORE_API void RemoveDynamicExtension (FViewModelTypeID Type)
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID_API (SEQUENCERCORE_API, FDynamicExtensionContainer) template< typename T > const T *CastDynamic() const
Public Member Functions inherited from UE::Sequencer::FOutlinerItemModelMixin
FOutlinerItemModelMixin ()
TSharedPtr< SWidget > CreateContextMenuWidget (const FCreateOutlinerContextMenuWidgetParams &InParams) override
Build the context menu widget for this outliner item.
virtual TSharedPtr< SWidget > GenerateCurveEditorTreeWidget (const FName &InColumnName, TWeakPtr< FCurveEditor > InCurveEditor, FCurveEditorTreeItemID InTreeItemID, const TSharedRef< ITableRow > &InTableRow) override
Generate the widget content for the specified column name of the curve editor tree view.
virtual TSharedPtr< ICurveEditorTreeItem > GetCurveEditorTreeItem () const override
Gets the curve editor item for this view-model.
TSharedPtr< FSequencerEditorViewModel > GetEditor () const
FName GetIdentifier () const override
Return the identifier of the owning model.
virtual TOptional< FString > GetUniquePathName () const override
Get optional unique path name.
bool IsExpanded () const override
Gets whether this outliner item is expanded.
bool IsFilteredOut () const override
Gets whether this outliner item has been filtered out.
bool IsPinned () const override
Returns whether this item is pinned, or is in a pinned branch.
virtual bool PassesFilter (const FCurveEditorTreeFilter *InFilter) const override
Check whether this tree item passes the specified filter.
void SetExpansion (bool bInIsExpanded) override
Sets the expansion state of this outliner item.
Public Member Functions inherited from UE::Sequencer::FOutlinerExtensionShim
virtual EOutlinerSelectionState GetSelectionState () const override
Gets the outliner item's selection state.
virtual void SetFilteredOut (bool bInIsFilteredOut) override
Sets whether this outliner item is being filtered out.
virtual void SetSelectionState (EOutlinerSelectionState InState) override
Sets the outliner item's selection state.
virtual bool ShouldAnchorToTop () const override
Public Member Functions inherited from UE::Sequencer::IOutlinerExtension
virtual TSharedRef< SWidget > CreateOutlinerView (const FCreateOutlinerViewParams &InParams)
(deprecated) Create the outliner view for the label column
virtual const FSlateBrush * GetIconOverlayBrush () const
Gets the overlay icon for the outliner item.
virtual FSlateColor GetIconTint () const
Gets the icon tint color for the outliner item.
virtual FText GetIconToolTipText () const
Gets the tooltip text for the outliner item icon.
virtual bool HasBackground () const
Gets whether the outliner item has a background.
virtual void ToggleSelectionState (EOutlinerSelectionState InState, bool bInValue)
Toggles a bit in the outliner item's selection state.
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID (IOutlinerExtension) virtual ~IOutlinerExtension()
Public Member Functions inherited from UE::Sequencer::FGeometryExtensionShim
FVirtualGeometry GetVirtualGeometry () const override
void ReportVirtualGeometry (const FVirtualGeometry &InVirtualGeometry) override
Public Member Functions inherited from UE::Sequencer::IGeometryExtension
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID (IGeometryExtension) virtual ~IGeometryExtension()
Public Member Functions inherited from UE::Sequencer::FPinnableExtensionShim
virtual void ReportPinnedParent (bool bInIsInPinnedBranch) override
Lets parent items report to their children that they are in a pinned branch.
virtual void SetPinned (bool bInIsPinned) override
Sets whether this item is pinned.
Public Member Functions inherited from UE::Sequencer::IPinnableExtension
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID (IPinnableExtension) virtual ~IPinnableExtension()
Public Member Functions inherited from UE::Sequencer::FHoveredExtensionShim
virtual bool IsHovered () const
virtual void OnHovered ()
virtual void OnUnhovered ()
Public Member Functions inherited from UE::Sequencer::IHoveredExtension
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID (IHoveredExtension) virtual ~IHoveredExtension()
Public Member Functions inherited from UE::Sequencer::IDimmableExtension
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID (IDimmableExtension) virtual ~IDimmableExtension()
Public Member Functions inherited from UE::Sequencer::FCurveEditorTreeItemExtensionShim
FCurveEditorTreeItemID GetCurveEditorItemID () const override
Gets the curve editor ID for this view-model.
void OnAddedToCurveEditor (FCurveEditorTreeItemID ItemID, TSharedPtr< FCurveEditor > CurveEditor)
Called when this view-model has a curve editor item created for it.
void OnRemovedFromCurveEditor (TSharedPtr< FCurveEditor > CurveEditor)
Called when this view-model's curve editor item is removed.
Public Member Functions inherited from UE::Sequencer::ICurveEditorTreeItemExtension
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID (ICurveEditorTreeItemExtension) virtual ~ICurveEditorTreeItemExtension()
Public Member Functions inherited from ICurveEditorTreeItem
virtual ~ICurveEditorTreeItem ()
Public Member Functions inherited from UE::Sequencer::IMutableExtension
virtual bool IsInheritable () const
Returns whether this mutable can be muted by a parent, and should report its mute state to a parent.
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID (IMutableExtension) virtual ~IMutableExtension()
Public Member Functions inherited from UE::Sequencer::ISoloableExtension
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID (ISoloableExtension) virtual ~ISoloableExtension()
Public Member Functions inherited from UE::Sequencer::IDeactivatableExtension
virtual ~IDeactivatableExtension ()
virtual bool IsInheritable () const
Returns whether this deactivatable can be deactivated by a parent, and should report its deactivated state to a parent.
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID (IDeactivatableExtension)
Public Member Functions inherited from UE::Sequencer::IRenameableExtension
bool IsRenameValid (const FText &NewName, FText &OutErrorMessage) const
FSimpleMulticastDelegate & OnRenameRequested ()
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID (IRenameableExtension) virtual ~IRenameableExtension()
Public Member Functions inherited from UE::Sequencer::IResizableExtension
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID (IResizableExtension) virtual ~IResizableExtension()
Public Member Functions inherited from UE::Sequencer::ITrackExtension
TArray< UMovieSceneSection * > GetSections ()
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID (ITrackExtension) virtual ~ITrackExtension()
Public Member Functions inherited from UE::Sequencer::ITrackAreaExtension
template<typename T>
TTypedIterator< T, FViewModelVariantIterator > GetTrackAreaModelListAs () const
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID (ITrackAreaExtension) virtual ~ITrackAreaExtension()
Public Member Functions inherited from UE::Sequencer::ILockableExtension
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID (ILockableExtension) virtual ~ILockableExtension()
Public Member Functions inherited from UE::Sequencer::IGroupableExtension
FString GetIdentifierForGrouping () const
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID (IGroupableExtension) virtual ~IGroupableExtension()
Public Member Functions inherited from UE::Sequencer::ISortableExtension
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID (ISortableExtension) virtual ~ISortableExtension()
Public Member Functions inherited from UE::Sequencer::IDraggableOutlinerExtension
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID (IDraggableOutlinerExtension) virtual ~IDraggableOutlinerExtension()
Public Member Functions inherited from UE::Sequencer::IDeletableExtension
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID (IDeletableExtension) virtual ~IDeletableExtension()
Public Member Functions inherited from UE::Sequencer::IConditionableExtension
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID (IConditionableExtension) virtual ~IConditionableExtension()
Public Member Functions inherited from TIntrusiveLinkedList< TIntrusiveEventHandler< UE::MovieScene::ISignedObjectEventHandler > >
TIntrusiveLinkedList ()
Default constructor (empty list).
Public Member Functions inherited from TLinkedListBase< TIntrusiveEventHandler< UE::MovieScene::ISignedObjectEventHandler >, TIntrusiveEventHandler< UE::MovieScene::ISignedObjectEventHandler >, TIntrusiveLinkedListIterator >
TLinkedListBase ()
Default constructor (empty list)
FORCEINLINE TIntrusiveEventHandler< UE::MovieScene::ISignedObjectEventHandler > * GetNextLink () const
FORCEINLINE TIntrusiveEventHandler< UE::MovieScene::ISignedObjectEventHandler > ** GetPrevLink () const
FORCEINLINE bool IsLinked ()
Returns whether element is currently linked.
FORCEINLINE void LinkAfter (TIntrusiveEventHandler< UE::MovieScene::ISignedObjectEventHandler > *After)
Adds this element to the linked list, after the specified element.
FORCEINLINE void LinkBefore (TIntrusiveEventHandler< UE::MovieScene::ISignedObjectEventHandler > *Before)
Adds this element to a list, before the given element.
FORCEINLINE void LinkHead (TIntrusiveEventHandler< UE::MovieScene::ISignedObjectEventHandler > *&Head)
Adds this element as the head of the linked list, linking the input Head pointer to this element, so that when the element is linked/unlinked, the Head linked list pointer will be correctly updated.
FORCEINLINE void LinkReplace (TIntrusiveEventHandler< UE::MovieScene::ISignedObjectEventHandler > *Replace)
Adds this element to the linked list, replacing the specified element.
FORCEINLINE TIntrusiveEventHandler< UE::MovieScene::ISignedObjectEventHandler > * Next ()
FORCEINLINE void Unlink ()
Removes this element from the list in constant time.
Public Member Functions inherited from UE::MovieScene::ISignedObjectEventHandler
virtual void OnPostUndo ()
Public Member Functions inherited from UE::MovieScene::IDeferredSignedObjectFlushSignal
virtual ~IDeferredSignedObjectFlushSignal ()
Static Public Member Functions
static EViewModelListType GetTopLevelChannelGroupType ()
static EViewModelListType GetTopLevelChannelType ()
Static Public Member Functions inherited from UE::Sequencer::ICastable
template<typename T>
static T * CastWeakPtr (const TWeakPtr< ICastable > &InWeakPtr)
template<typename T>
static TSharedPtr< T > CastWeakPtrShared (const TWeakPtr< ICastable > &InWeakPtr)
Static Public Member Functions inherited from UE::Sequencer::IOutlinerExtension
static FString GetPathName (const FViewModel &Item)
Utility method to get the full path name of the given model.
static void GetPathName (const FViewModel &Item, FStringBuilderBase &OutString)
Utility method to get the full path name of the given model.
static FString GetPathName (const TSharedPtr< const FViewModel > Item)
Utility method to get the full path name of the given model.
static FString GetPathName (const TSharedPtr< FViewModel > Item)
Utility method to get the full path name of the given model.
static FString GetPathName (const TWeakPtr< const FViewModel > Item)
Utility method to get the full path name of the given model.
Static Public Member Functions inherited from UE::Sequencer::IGeometryExtension
static float UpdateVirtualGeometry (float InitialVirtualPosition, TSharedPtr< FViewModel > InInitialItem)
Static Public Member Functions inherited from UE::Sequencer::FPinnableExtensionShim
static void UpdateCachedPinnedState (TSharedPtr< FViewModel > RootModel)
Looks for any direct child of RootModel that is pinnable, and reports all their descendants that they are in a pinned branch, to make that lookup faster.
Static Public Member Functions inherited from UE::Sequencer::ISortableExtension
static void SortChildren (FViewModelChildren &Children, ESortingMode SortingMode)
Utility function for sorting children based on their sorting key.
static void SortChildren (TSharedPtr< FViewModel > ParentModel, ESortingMode SortingMode)
Utility function for sorting children based on their sorting key.
Private Member Functions
bool FindBoundObjects (TArray< UObject * > &OutBoundObjects) const
void ForceUpdate ()
Private Attributes
bool bNeedsUpdate
int32 PreviousLayoutNumRows = -1
FViewModelListHead SectionList
A second children list for the sections inside this track.
FViewModelListHead TopLevelChannelList
TSharedPtr< ISequencerTrackEditor > TrackEditor
TWeakObjectPtr< UMovieSceneTrack > WeakTrack
The actual track wrapped by this data model.
Additional Inherited Members
Public Types inherited from UE::Sequencer::FOutlinerItemModelMixin
using Implements = TImplements<IOutlinerExtension, IGeometryExtension, IPinnableExtension, IHoveredExtension, IDimmableExtension, ICurveEditorTreeItemExtension>
Public Types inherited from TLinkedListBase< TIntrusiveEventHandler< UE::MovieScene::ISignedObjectEventHandler >, TIntrusiveEventHandler< UE::MovieScene::ISignedObjectEventHandler >, TIntrusiveLinkedListIterator >
typedef TIntrusiveLinkedListIterator< TIntrusiveEventHandler< UE::MovieScene::ISignedObjectEventHandler >, const TIntrusiveEventHandler< UE::MovieScene::ISignedObjectEventHandler > > TConstIterator
typedef TIntrusiveLinkedListIterator< TIntrusiveEventHandler< UE::MovieScene::ISignedObjectEventHandler >, TIntrusiveEventHandler< UE::MovieScene::ISignedObjectEventHandler > > TIterator
Used to iterate over the elements of a linked list.
Static Public Attributes inherited from ICurveEditorTreeItem
static const FColumnNames ColumnNames
Protected Member Functions inherited from UE::Sequencer::FViewModel
FViewModelChildren GetChildrenForList (FViewModelListHead *ListHead)
Retrieve the children for the specified child list head.
void RegisterChildList (FViewModelListHead *InChildren)
Chain a new children list to the existing children lists.
void SetSharedDataFromConstructor (TSharedPtr< FSharedViewModelData > InSharedData)
Protected Member Functions inherited from TSharedFromThis< FViewModel >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Protected Member Functions inherited from UE::Sequencer::FDynamicExtensionContainer
template<typename T, typename... InArgTypes>
T & AddDynamicExtension (TSharedRef< FViewModel > InOwner, InArgTypes &&... Args)
void PostInitializeExtensions ()
void ReinitializeExtensions ()
template<typename T>
void RemoveDynamicExtension ()
Protected Member Functions inherited from UE::Sequencer::FOutlinerItemModelMixin
virtual void BuildDisplayOptionsMenu (FMenuBuilder &MenuBuilder)
virtual void BuildOrganizeContextMenu (FMenuBuilder &MenuBuilder)
virtual void BuildSectionColorTintsMenu (FMenuBuilder &MenuBuilder)
virtual void BuildTrackOptionsMenu (FMenuBuilder &MenuBuilder, const TArray< UMovieSceneTrack * > &InTracks)
virtual void BuildTrackRowOptionsMenu (FMenuBuilder &MenuBuilder)
void SetExpansionWithoutSaving (bool bInIsExpanded)
Set expansion state without saving it in the movie-scene data.
void SetIdentifier (FName InNewIdentifier)
Set identifier for computing node paths.
Protected Member Functions inherited from UE::MovieScene::TIntrusiveEventHandler< UE::MovieScene::ISignedObjectEventHandler >
virtual ~TIntrusiveEventHandler ()
Static Protected Member Functions inherited from TSharedFromThis< FViewModel >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Protected Attributes inherited from UE::Sequencer::ICastable
FDynamicExtensionContainer * DynamicTypes = nullptr
Protected Attributes inherited from UE::Sequencer::FOutlinerItemModelMixin
FViewModelListHead OutlinerChildList
Protected Attributes inherited from UE::Sequencer::FOutlinerExtensionShim
bool bIsExpanded = false
bool bIsFilteredOut = false
EOutlinerSelectionState SelectionState = EOutlinerSelectionState::None
Protected Attributes inherited from UE::Sequencer::FGeometryExtensionShim
FVirtualGeometry VirtualGeometry
Protected Attributes inherited from UE::Sequencer::FHoveredExtensionShim
bool bIsHovered = false
Detailed Description
Definition at line 39 of file TrackModel.h.
Constructor & Destructor Documentation
FTrackModel()
UE::Sequencer::FTrackModel::FTrackModel (UMovieSceneTrack * Track) explicit
Referenced by UE::Sequencer::FBindingLifetimeTrackModel::UE_SEQUENCER_DECLARE_CASTABLE(), UE_SEQUENCER_DECLARE_CASTABLE(), and UE::Sequencer::FTimeWarpTrackModel::UE_SEQUENCER_DECLARE_CASTABLE_API().
~FTrackModel()
UE::Sequencer::FTrackModel::~FTrackModel ()
Member Function Documentation
BuildContextMenu()
void UE::Sequencer::FTrackModel::BuildContextMenu (FMenuBuilder & MenuBuilder) override virtual
Get context menu contents.
Reimplemented from UE::Sequencer::FOutlinerItemModelMixin.
BuildSidebarMenu()
void UE::Sequencer::FTrackModel::BuildSidebarMenu (FMenuBuilder & MenuBuilder) override virtual
Reimplemented from UE::Sequencer::FOutlinerItemModelMixin.
CanDelete()
bool UE::Sequencer::FTrackModel::CanDelete (FText * OutErrorMessage) const override virtual
Implements UE::Sequencer::IDeletableExtension.
CanDrag()
bool UE::Sequencer::FTrackModel::CanDrag () const override virtual
Returns whether the model can be dragged.
Implements UE::Sequencer::IDraggableOutlinerExtension.
CanRename()
bool UE::Sequencer::FTrackModel::CanRename () const override virtual
Implements UE::Sequencer::IRenameableExtension.
CreateCurveModels()
void UE::Sequencer::FTrackModel::CreateCurveModels (TArray< TUniquePtr< FCurveModel > > & OutCurveModels) override virtual
Populate the specified array with curve models that are represented by this tree item.
Parameters
OutCurveModels Array of curve models to be populated with the curves of this tree item
Reimplemented from UE::Sequencer::FOutlinerItemModelMixin.
CreateOutlinerViewForColumn()
TSharedPtr< SWidget > UE::Sequencer::FTrackModel::CreateOutlinerViewForColumn (const FCreateOutlinerViewParams & InParams, const FName & InColumnName) override virtual
Create the visual outliner widget for the specified column.
Reimplemented from UE::Sequencer::IOutlinerExtension.
Delete()
void UE::Sequencer::FTrackModel::Delete () override virtual
Implements UE::Sequencer::IDeletableExtension.
FindBoundObjects()
bool UE::Sequencer::FTrackModel::FindBoundObjects (TArray< UObject * > & OutBoundObjects) const private
ForceUpdate()
void UE::Sequencer::FTrackModel::ForceUpdate () private
GetCondition()
const UMovieSceneCondition * UE::Sequencer::FTrackModel::GetCondition () const override virtual
Implements UE::Sequencer::IConditionableExtension.
GetConditionState()
EConditionableConditionState UE::Sequencer::FTrackModel::GetConditionState () const override virtual
Returns condition state for this item.
Implements UE::Sequencer::IConditionableExtension.
GetDefaultExpansionState()
bool UE::Sequencer::FTrackModel::GetDefaultExpansionState () const override virtual
Get the default expansion state if it wasn't saved in the movie-scene data.
Reimplemented from UE::Sequencer::FOutlinerItemModelMixin.
GetIconBrush()
const FSlateBrush * UE::Sequencer::FTrackModel::GetIconBrush () const override virtual
Gets the icon for the outliner item.
Reimplemented from UE::Sequencer::IOutlinerExtension.
GetIdentifierForGrouping()
void UE::Sequencer::FTrackModel::GetIdentifierForGrouping (TStringBuilder< 128 > & OutString) const override virtual
Implements UE::Sequencer::IGroupableExtension.
GetLabel()
FText UE::Sequencer::FTrackModel::GetLabel () const override virtual
Gets the label for the outliner item.
Reimplemented from UE::Sequencer::IOutlinerExtension.
GetLabelColor()
FSlateColor UE::Sequencer::FTrackModel::GetLabelColor () const override virtual
Gets the color for the outliner item label.
Reimplemented from UE::Sequencer::FOutlinerItemModelMixin.
GetLabelFont()
FSlateFontInfo UE::Sequencer::FTrackModel::GetLabelFont () const override virtual
Gets the font for the outliner item.
Reimplemented from UE::Sequencer::IOutlinerExtension.
GetLabelToolTipText()
FText UE::Sequencer::FTrackModel::GetLabelToolTipText () const override virtual
Gets the tooltip text for the outliner item.
Reimplemented from UE::Sequencer::IOutlinerExtension.
GetLockState()
ELockableLockState UE::Sequencer::FTrackModel::GetLockState () const override virtual
Returns whether this item is locked.
Implements UE::Sequencer::ILockableExtension.
GetOutlinerSizing()
FOutlinerSizing UE::Sequencer::FTrackModel::GetOutlinerSizing () const override virtual
Return the desired size for the owning model.
Implements UE::Sequencer::IOutlinerExtension.
GetRowIndex()
int32 UE::Sequencer::FTrackModel::GetRowIndex () const override virtual
Implements UE::Sequencer::ITrackExtension.
GetSectionModels()
FViewModelChildren UE::Sequencer::FTrackModel::GetSectionModels () override virtual
Implements UE::Sequencer::ITrackExtension.
GetSortingKey()
FSortingKey UE::Sequencer::FTrackModel::GetSortingKey () const override virtual
Called by the part to sort this model among its siblings.
Implements UE::Sequencer::ISortableExtension.
GetTopLevelChannelGroupType()
EViewModelListType UE::Sequencer::FTrackModel::GetTopLevelChannelGroupType () static
GetTopLevelChannels()
FViewModelChildren UE::Sequencer::FTrackModel::GetTopLevelChannels ()
GetTopLevelChannelType()
EViewModelListType UE::Sequencer::FTrackModel::GetTopLevelChannelType () static
GetTopLevelChildTrackAreaModels()
FViewModelVariantIterator UE::Sequencer::FTrackModel::GetTopLevelChildTrackAreaModels () const override virtual
Reimplemented from UE::Sequencer::ITrackAreaExtension.
GetTrack()
UMovieSceneTrack * UE::Sequencer::FTrackModel::GetTrack () const override virtual
Implements UE::Sequencer::ITrackExtension.
GetTrackAreaModelList()
FViewModelVariantIterator UE::Sequencer::FTrackModel::GetTrackAreaModelList () const override virtual
Implements UE::Sequencer::ITrackAreaExtension.
GetTrackAreaParameters()
FTrackAreaParameters UE::Sequencer::FTrackModel::GetTrackAreaParameters () const override virtual
Implements UE::Sequencer::ITrackAreaExtension.
GetTrackEditor()
TSharedPtr< ISequencerTrackEditor > UE::Sequencer::FTrackModel::GetTrackEditor () const override virtual
Implements UE::Sequencer::ITrackExtension.
HasCurves()
bool UE::Sequencer::FTrackModel::HasCurves () const override virtual
Whether this view-model has any curves and needs to have a curve editor item created.
Reimplemented from UE::Sequencer::FOutlinerItemModelMixin.
IsDimmed()
bool UE::Sequencer::FTrackModel::IsDimmed () const override virtual
Reimplemented from UE::Sequencer::FOutlinerItemModelMixin.
IsRenameValidImpl()
bool UE::Sequencer::FTrackModel::IsRenameValidImpl (const FText & NewName, FText & OutErrorMessage) const override virtual
Reimplemented from UE::Sequencer::IRenameableExtension.
IsResizable()
bool UE::Sequencer::FTrackModel::IsResizable () const override virtual
Implements UE::Sequencer::IResizableExtension.
OnConstruct()
virtual void UE::Sequencer::FTrackModel::OnConstruct () override virtual
Called once for this model when it is added to a parent that has valid shared data.
Reimplemented from UE::Sequencer::FViewModel.
Reimplemented in UE::Sequencer::FBindingLifetimeTrackModel, and UE::Sequencer::FTimeWarpTrackModel.
OnDeferredModifyFlush()
virtual void UE::Sequencer::FTrackModel::OnDeferredModifyFlush () override virtual
Implements UE::MovieScene::IDeferredSignedObjectFlushSignal.
Reimplemented in UE::Sequencer::FBindingLifetimeTrackModel.
OnModifiedDirectly()
void UE::Sequencer::FTrackModel::OnModifiedDirectly (UMovieSceneSignedObject *) override virtual
Reimplemented from UE::MovieScene::ISignedObjectEventHandler.
OnModifiedIndirectly()
void UE::Sequencer::FTrackModel::OnModifiedIndirectly (UMovieSceneSignedObject *) override virtual
Reimplemented from UE::MovieScene::ISignedObjectEventHandler.
Rename()
void UE::Sequencer::FTrackModel::Rename (const FText & NewName) override virtual
Implements UE::Sequencer::IRenameableExtension.
Resize()
void UE::Sequencer::FTrackModel::Resize (float NewSize) override virtual
Implements UE::Sequencer::IResizableExtension.
SetConditionEditorForceTrue()
void UE::Sequencer::FTrackModel::SetConditionEditorForceTrue (bool bEditorForceTrue) override virtual
Set this item's condition to evaluate true for editor preview purposes.
Implements UE::Sequencer::IConditionableExtension.
SetCustomOrder()
void UE::Sequencer::FTrackModel::SetCustomOrder (int32 InCustomOrder) override virtual
Set a custom sort index for this view model.
Implements UE::Sequencer::ISortableExtension.
SetIsLocked()
void UE::Sequencer::FTrackModel::SetIsLocked (bool bIsLocked) override virtual
Set whether this item is locked.
Implements UE::Sequencer::ILockableExtension.
SortChildren()
void UE::Sequencer::FTrackModel::SortChildren () override virtual
Called when the model should sort its immediate children.
Implements UE::Sequencer::ISortableExtension.
UE_SEQUENCER_DECLARE_CASTABLE()
UE::Sequencer::FTrackModel::UE_SEQUENCER_DECLARE_CASTABLE (FTrackModel , FEvaluableOutlinerItemModel , IRenameableExtension , IResizableExtension , ITrackExtension , ITrackAreaExtension , ILockableExtension , IGroupableExtension , ISortableExtension , IDraggableOutlinerExtension , IDeletableExtension , IConditionableExtension)
References FTrackModel().
Field Documentation
bNeedsUpdate
bool UE::Sequencer::FTrackModel::bNeedsUpdate private
Definition at line 171 of file TrackModel.h.
PreviousLayoutNumRows
int32 UE::Sequencer::FTrackModel::PreviousLayoutNumRows = -1 private
Definition at line 173 of file TrackModel.h.
SectionList
FViewModelListHead UE::Sequencer::FTrackModel::SectionList private
A second children list for the sections inside this track.
Definition at line 162 of file TrackModel.h.
TopLevelChannelList
FViewModelListHead UE::Sequencer::FTrackModel::TopLevelChannelList private
Definition at line 163 of file TrackModel.h.
TrackEditor
TSharedPtr<ISequencerTrackEditor> UE::Sequencer::FTrackModel::TrackEditor private
Definition at line 169 of file TrackModel.h.
WeakTrack
TWeakObjectPtr<UMovieSceneTrack> UE::Sequencer::FTrackModel::WeakTrack private
The actual track wrapped by this data model.
Definition at line 166 of file TrackModel.h.
The documentation for this class was generated from the following file:
Editor/Sequencer/Public/MVVM/ViewModels/TrackModel.h