Unreal Engine 5.6 C++ API: FTSTickerObjectBase Class Reference
FTSTickerObjectBase Class Reference abstract
Base class for thread-safe ticker objects.
#include "Ticker.h"
Public Member Functions
FTSTickerObjectBase (float InDelay=0.0f, FTSTicker &Ticker=FTSTicker::GetCoreTicker())
Constructor.
virtual ~FTSTickerObjectBase ()
Virtual destructor.
virtual bool Tick (float DeltaTime)=0
Pure virtual that must be overloaded by the inheriting class.
UE_NONCOPYABLE (FTSTickerObjectBase)
Private Attributes
FTSTicker::FDelegateHandle TickHandle
Delegate for callbacks to Tick.
Detailed Description
Base class for thread-safe ticker objects.
Definition at line 136 of file Ticker.h.
Constructor & Destructor Documentation
FTSTickerObjectBase()
FTSTickerObjectBase::FTSTickerObjectBase (float InDelay = 0.0f, FTSTicker & Ticker = FTSTicker::GetCoreTicker()) nodiscard
Constructor.
Parameters
InDelay Delay until next fire; 0 means "next frame"
Ticker the ticker to register with. Defaults to FTSTicker::GetCoreTicker().
References FTSTicker::GetCoreTicker().
Referenced by UE_NONCOPYABLE().
~FTSTickerObjectBase()
virtual FTSTickerObjectBase::~FTSTickerObjectBase () virtual
Virtual destructor.
Member Function Documentation
Tick()
virtual bool FTSTickerObjectBase::Tick (float DeltaTime) pure virtual
Pure virtual that must be overloaded by the inheriting class.
Parameters
DeltaTime time passed since the last call.
Returns
true if should continue ticking
Implemented in FODSCManager.
References DeltaTime.
UE_NONCOPYABLE()
FTSTickerObjectBase::UE_NONCOPYABLE (FTSTickerObjectBase)
References FTSTickerObjectBase().
Field Documentation
TickHandle
FTSTicker::FDelegateHandle FTSTickerObjectBase::TickHandle private
Delegate for callbacks to Tick.
Definition at line 162 of file Ticker.h.
The documentation for this class was generated from the following file:
Runtime/Core/Public/Containers/Ticker.h