Unreal Engine 5.6 C++ API: TraceServices::IEditableBookmarkProvider Class Reference
TraceServices::IEditableBookmarkProvider Class Reference abstract
#include "Bookmarks.h"
Public Member Functions
virtual ~IEditableBookmarkProvider ()=default
virtual void AppendBookmark (uint64 BookmarkPoint, double Time, uint32 CallstackId, const TCHAR *Text)=0
virtual void AppendBookmark (uint64 BookmarkPoint, double Time, uint32 CallstackId, const uint8 *FormatArgs)=0
UE_DEPRECATED (5.6, "Use AppendBookmark that has CallstackId parameter") void AppendBookmark(uint64 BookmarkPoint
UE_DEPRECATED (5.6, "Use AppendBookmark that has CallstackId parameter") void AppendBookmark(uint64 BookmarkPoint
virtual void UpdateBookmarkSpec (uint64 BookmarkPoint, const TCHAR *FormatString, const TCHAR *File, int32 Line)=0
Public Member Functions inherited from TraceServices::IEditableProvider
virtual ~IEditableProvider ()=default
virtual void BeginEdit () const
virtual void EditAccessCheck () const
virtual void EndEdit () const
Data Fields
double const uint8 * FormatArgs { AppendBookmark(BookmarkPoint, Time, 0, FormatArgs)
double const TCHAR * Text { AppendBookmark(BookmarkPoint, Time, 0, Text)
double Time
Detailed Description
Definition at line 32 of file Bookmarks.h.
Constructor & Destructor Documentation
~IEditableBookmarkProvider()
virtual TraceServices::IEditableBookmarkProvider::~IEditableBookmarkProvider () virtual default
Member Function Documentation
AppendBookmark() [1/2]
virtual void TraceServices::IEditableBookmarkProvider::AppendBookmark (uint64 BookmarkPoint, double Time, uint32 CallstackId, const TCHAR * Text) pure virtual
References Text, and Time.
AppendBookmark() [2/2]
virtual void TraceServices::IEditableBookmarkProvider::AppendBookmark (uint64 BookmarkPoint, double Time, uint32 CallstackId, const uint8 * FormatArgs) pure virtual
References FormatArgs, and Time.
UE_DEPRECATED() [1/2]
TraceServices::IEditableBookmarkProvider::UE_DEPRECATED (5. 6, "Use AppendBookmark that has CallstackId parameter")
UE_DEPRECATED() [2/2]
TraceServices::IEditableBookmarkProvider::UE_DEPRECATED (5. 6, "Use AppendBookmark that has CallstackId parameter")
UpdateBookmarkSpec()
virtual void TraceServices::IEditableBookmarkProvider::UpdateBookmarkSpec (uint64 BookmarkPoint, const TCHAR * FormatString, const TCHAR * File, int32 Line) pure virtual
References TraceServices::FormatString(), and Line.
Field Documentation
FormatArgs
double const uint8* TraceServices::IEditableBookmarkProvider::FormatArgs { AppendBookmark(BookmarkPoint, Time, 0, FormatArgs)
Definition at line 68 of file Bookmarks.h.
Referenced by AppendBookmark().
Text
double const TCHAR* TraceServices::IEditableBookmarkProvider::Text { AppendBookmark(BookmarkPoint, Time, 0, Text)
Definition at line 70 of file Bookmarks.h.
Referenced by AppendBookmark().
Time
double TraceServices::IEditableBookmarkProvider::Time
Definition at line 68 of file Bookmarks.h.
Referenced by AppendBookmark(), and AppendBookmark().
The documentation for this class was generated from the following file:
Developer/TraceServices/Public/TraceServices/Model/Bookmarks.h