Unreal Engine 5.6 C++ API: FAndroidWindowManager::FPendingWindowAccessor Class Reference
FAndroidWindowManager::FPendingWindowAccessor Class Reference
#include "AndroidWindow.h"
Public Member Functions
FPendingWindowAccessor ()
~FPendingWindowAccessor ()
ANativeWindow * GetANativeWindow () const
void SetANativeWindow (ANativeWindow *ANativeHandle)
Private Member Functions
FPendingWindowAccessor (const FPendingWindowAccessor &)=delete
FPendingWindowAccessor (FPendingWindowAccessor &&)=delete
Static Private Attributes
static UE::FMutex Lock
static ANativeWindow * PendingANativeWindow = nullptr
Detailed Description
Definition at line 212 of file AndroidWindow.h.
Constructor & Destructor Documentation
FPendingWindowAccessor() [1/3]
FAndroidWindowManager::FPendingWindowAccessor::FPendingWindowAccessor (const FPendingWindowAccessor &) private delete
References FPendingWindowAccessor().
Referenced by FPendingWindowAccessor(), and FPendingWindowAccessor().
FPendingWindowAccessor() [2/3]
FAndroidWindowManager::FPendingWindowAccessor::FPendingWindowAccessor (FPendingWindowAccessor &&) private delete
References FPendingWindowAccessor().
FPendingWindowAccessor() [3/3]
FAndroidWindowManager::FPendingWindowAccessor::FPendingWindowAccessor () inline
Definition at line 219 of file AndroidWindow.h.
References Lock.
~FPendingWindowAccessor()
FAndroidWindowManager::FPendingWindowAccessor::~FPendingWindowAccessor () inline
Definition at line 220 of file AndroidWindow.h.
References Lock.
Member Function Documentation
GetANativeWindow()
ANativeWindow * FAndroidWindowManager::FPendingWindowAccessor::GetANativeWindow () const inline
Definition at line 223 of file AndroidWindow.h.
References PendingANativeWindow.
SetANativeWindow()
void FAndroidWindowManager::FPendingWindowAccessor::SetANativeWindow (ANativeWindow * ANativeHandle) inline
Definition at line 222 of file AndroidWindow.h.
References PendingANativeWindow.
Field Documentation
Lock
UE::FMutex FAndroidWindowManager::FPendingWindowAccessor::Lock inline static private
Definition at line 215 of file AndroidWindow.h.
Referenced by FPendingWindowAccessor(), and ~FPendingWindowAccessor().
PendingANativeWindow
ANativeWindow* FAndroidWindowManager::FPendingWindowAccessor::PendingANativeWindow = nullptr inline static private
Definition at line 214 of file AndroidWindow.h.
Referenced by GetANativeWindow(), and SetANativeWindow().
The documentation for this class was generated from the following file:
Runtime/ApplicationCore/Public/Android/AndroidWindow.h