Unreal Engine 5.6 C++ API: AController Class Reference
AController Class Reference
#include "Controller.h"
Public Member Functions
virtual void ChangeState (FName NewState)
Change the current state to named state.
virtual void CleanupPlayerState ()
Called from Destroyed().
virtual void CurrentLevelUnloaded ()
Called when the level this controller is in is unloaded via streaming.
virtual void Destroyed () override
virtual void DisplayDebug (class UCanvas *Canvas, const FDebugDisplayInfo &DebugDisplay, float &YL, float &YPos) override
virtual void FailedToSpawnPawn ()
GameMode failed to spawn pawn for me.
virtual void GameHasEnded (class AActor *EndGameFocus=nullptr, bool bIsWinner=false)
Called from game mode upon end of the game, used to transition to proper state.
virtual void GetActorEyesViewPoint (FVector &out_Location, FRotator &out_Rotation) const override
FORCEINLINE ACharacter * GetCharacter () const
Getter for Character.
virtual FString GetHumanReadableName () const override
virtual void GetLifetimeReplicatedProps (TArray< FLifetimeProperty > &OutLifetimeProps) const override
virtual void GetMoveGoalReachTest (const AActor *MovingActor, const FVector &MoveOffset, FVector &GoalOffset, float &GoalRadius, float &GoalHalfHeight) const override
Get cylinder for testing if actor has been reached.
virtual FVector GetNavAgentLocation () const override
virtual const struct FNavAgentProperties & GetNavAgentPropertiesRef () const override
FPawnChangedSignature & GetOnNewPawnNotifier ()
virtual IPathFollowingAgentInterface * GetPathFollowingAgent () const override
Retrieves PathFollowingAgent for this NavAgent.
FORCEINLINE TObjectPtr< APawn > GetPawn () const
Getter for Pawn.
template<class T>
T * GetPawn () const
Templated version of GetPawn, will return nullptr if cast fails.
template<class T>
T * GetPlayerState () const
FName GetStateName () const
virtual void InitPlayerState ()
spawns and initializes the PlayerState for this Controller
virtual void InstigatedAnyDamage (float Damage, const class UDamageType *DamageType, class AActor *DamagedActor, class AActor *DamageCauser)
Called when this controller instigates ANY damage.
virtual bool IsFollowingAPath () const override
Checks if the agent is actively following a navigation path.
bool IsInState (FName InStateName) const
States (uses FNames for replication, correlated to state flags)
virtual void K2_DestroyActor () override
virtual void PawnPendingDestroy (APawn *inPawn)
Called to unpossess our pawn because it is going to be destroyed.
virtual void PostInitializeComponents () override
Overridden to create the player replication info and perform other mundane initialization tasks.
virtual void Reset () override
virtual void SetPawn (APawn *InPawn)
Setter for Pawn.
void SetPawnFromRep (APawn *InPawn)
Calls SetPawn and RepNotify locally.
virtual bool ShouldParticipateInSeamlessTravel () const
Returns whether this controller should persist through seamless travel.
virtual bool ShouldPostponePathUpdates () const override
Allows delaying repath requests.
virtual void TickActor (float DeltaTime, enum ELevelTick TickType, FActorTickFunction &ThisTickFunction) override
UFUNCTION () 1 virtual AActor *GetViewTarget() const
Get the actor the controller is looking at.
UFUNCTION () 1 virtual bool IsLocalController() const
Returns whether this Controller is a local controller.
UFUNCTION () 1 virtual bool IsLookInputIgnored() const
Returns true if look input is ignored.
UFUNCTION () 1 virtual bool IsMoveInputIgnored() const
Returns true if movement input is ignored.
UFUNCTION () 1 virtual bool LineOfSightTo(const class AActor *Other
Checks line to center and top of other actor.
UFUNCTION () 1 virtual FRotator GetControlRotation() const
Get the control rotation.
UFUNCTION () 1 virtual FRotator GetDesiredRotation() const
Get the desired pawn target rotation.
UFUNCTION () 1 virtual void GetPlayerViewPoint(FVector &Location
Returns Player's Point of View For the AI this means the Pawn's 'Eyes' ViewPoint For a Human player, this means the Camera's ViewPoint.
UFUNCTION () 1 virtual void OnRep_Pawn()
Replication Notification Callbacks.
UFUNCTION () 1 virtual void OnRep_PlayerState()
UFUNCTION () 1 virtual void ResetIgnoreInputFlags()
Reset move and look input ignore flags.
UFUNCTION () 1 virtual void SetIgnoreLookInput(bool bNewLookInput)
Locks or unlocks look input, consecutive calls stack up and require the same amount of calls to undo, or can all be undone using ResetIgnoreLookInput.
UFUNCTION () 1 virtual void SetIgnoreMoveInput(bool bNewMoveInput)
Locks or unlocks movement input, consecutive calls stack up and require the same amount of calls to undo, or can all be undone using ResetIgnoreMoveInput.
UFUNCTION () 1 virtual void SetInitialLocationAndRotation(const FVector &NewLocation
Set the initial location and rotation of the controller, as well as the control rotation.
UFUNCTION () 1 virtual void StopMovement()
Aborts the move the controller is currently performing.
UFUNCTION () 1 void ClientSetLocation(FVector NewLocation
Replicated function to set the pawn location and rotation, allowing server to force (ex.
UFUNCTION () 1 void ClientSetRotation(FRotator NewRotation
Replicated function to set the pawn rotation, allowing the server to force.
UFUNCTION () bool IsLocalPlayerController() const
Returns whether this Controller is a locally controlled PlayerController.
UFUNCTION () bool IsPlayerController() const
Returns whether this Controller is a PlayerController.
UFUNCTION ()) 1 APawn *K2_GetPawn() const
Return the Pawn that is currently 'controlled' by this PlayerController.
UFUNCTION ()) 1 virtual void Possess(APawn *InPawn) final
Handles attaching this controller to the specified pawn.
UFUNCTION ()) 1 virtual void ResetIgnoreLookInput()
Stops ignoring look input by resetting the ignore look input state.
UFUNCTION ()) 1 virtual void ResetIgnoreMoveInput()
Stops ignoring move input by resetting the ignore move input state.
UFUNCTION ()) 1 virtual void SetControlRotation(const FRotator &NewRotation)
Set the control rotation.
UFUNCTION ()) 1 virtual void UnPossess() final
Called to unpossess our pawn for any reason that is not the pawn being destroyed (destruction handled by PawnDestroyed()).
Data Fields
FVector bool bAlternateChecks = false) const
bool bResetCamera = false)
FRotator &Rotation const
const FRotator & NewRotation
FRotator NewRotation
FVector ViewPoint = FVector(ForceInit)
Protected Member Functions
virtual void AddPawnTickDependency (APawn *NewPawn)
Add dependency that makes us tick before the given Pawn.
virtual void AttachToPawn (APawn *InPawn)
Physically attach the Controller to the specified Pawn, so that our position reflects theirs.
virtual void BeginInactiveState ()
State entered when inactive (no possessed pawn, not spectating, etc).
virtual void DetachFromPawn ()
Detach the RootComponent from its parent, but only if bAttachToPawn is true and it was attached to a Pawn.
virtual void EndInactiveState ()
Called when leaving the inactive state.
class USceneComponent * GetTransformComponent () const
Returns TransformComponent subobject.
bool IsValidControlRotation (FRotator CheckRotation) const
Return false if rotation contains NaN or extremely large values (usually resulting from uninitialized values).
virtual void OnPossess (APawn *InPawn)
Overridable native function for when this controller is asked to possess a pawn.
virtual void OnUnPossess ()
Overridable native function for when this controller unpossesses its pawn.
virtual void RemovePawnTickDependency (APawn *InOldPawn)
Remove dependency that makes us tick before the given Pawn.
UFUNCTION () 1 void ReceiveInstigatedAnyDamage(float Damage
Event when this controller instigates ANY damage.
UFUNCTION ()) 1 void ReceivePossess(APawn *PossessedPawn)
Blueprint implementable event to react to the controller possessing a pawn.
UFUNCTION ()) 1 void ReceiveUnPossess(APawn *UnpossessedPawn)
Blueprint implementable event to react to the controller unpossessing a pawn.
UPROPERTY () FRotator ControlRotation
The control rotation of the Controller.
Protected Attributes
uint8 bCanPossessWithoutAuthority:1
Whether the controller must have authority to be able to call possess on a Pawn.
UPROPERTY() uint8 bAttachToPawn uint8 bIsPlayerController:1
If true, the controller location will match the possessed Pawn's location.
const class UDamageType class AActor class AActor * DamageCauser
const class UDamageType class AActor * DamagedActor
const class UDamageType * DamageType
uint8 IgnoreLookInput
Ignores look input.
uint8 IgnoreMoveInput
Ignores movement input.
FPawnChangedSignature OnNewPawn
Delegate broadcast on authorities when possessing a new pawn or unpossessing one.
Private Member Functions
HIDE_ACTOR_TRANSFORM_FUNCTIONS ()
void SetPawn_Direct (APawn *InPawn)
void SetPlayerState (APlayerState *InPlayerState)
UPROPERTY () FInstigatedAnyDamageSignature OnInstigatedAnyDamage
Called when the controller has instigated damage in any way.
UPROPERTY () FName StateName
Current gameplay state this controller is in.
UPROPERTY () FOnPossessedPawnChanged OnPossessedPawnChanged
Called on both authorities and clients when the possessed pawn changes (either OldPawn or NewPawn might be nullptr)
UPROPERTY () TObjectPtr< ACharacter > Character
Character currently being controlled by this controller.
UPROPERTY () TObjectPtr< APawn > Pawn
Pawn currently being controlled by this controller.
GENERATED_BODY() public UPROPERTY () TObjectPtr< APlayerState > PlayerState
Default Constructor.
UPROPERTY () TObjectPtr< USceneComponent > TransformComponent
Component to give controllers a transform and enable attachment if desired.
Private Attributes
TWeakObjectPtr< APawn > OldPawn
Used to track when pawn changes during OnRep_Pawn.
TWeakObjectPtr< class AActor > StartSpot
Actor marking where this controller spawned in.
Detailed Description
Definition at line 40 of file Controller.h.
Member Function Documentation
AddPawnTickDependency()
virtual void AController::AddPawnTickDependency (APawn * NewPawn) protected virtual
Add dependency that makes us tick before the given Pawn.
This minimizes latency between input processing and Pawn movement.
References AddPawnTickDependency().
Referenced by AddPawnTickDependency().
AttachToPawn()
virtual void AController::AttachToPawn (APawn * InPawn) protected virtual
Physically attach the Controller to the specified Pawn, so that our position reflects theirs.
The attachment persists during possession of the pawn. The Controller's rotation continues to match the ControlRotation. Attempting to attach to a nullptr Pawn will call DetachFromPawn() instead.
References AttachToPawn().
Referenced by AttachToPawn().
BeginInactiveState()
virtual void AController::BeginInactiveState () protected virtual
State entered when inactive (no possessed pawn, not spectating, etc).
References BeginInactiveState().
Referenced by BeginInactiveState().
ChangeState()
virtual void AController::ChangeState (FName NewState) virtual
Change the current state to named state.
CleanupPlayerState()
virtual void AController::CleanupPlayerState () virtual
Called from Destroyed().
Cleans up PlayerState.
CurrentLevelUnloaded()
virtual void AController::CurrentLevelUnloaded () virtual
Called when the level this controller is in is unloaded via streaming.
References CurrentLevelUnloaded().
Referenced by CurrentLevelUnloaded().
Destroyed()
virtual void AController::Destroyed () override virtual
DetachFromPawn()
virtual void AController::DetachFromPawn () protected virtual
Detach the RootComponent from its parent, but only if bAttachToPawn is true and it was attached to a Pawn.
References DetachFromPawn().
Referenced by DetachFromPawn().
DisplayDebug()
virtual void AController::DisplayDebug (class UCanvas * Canvas, const FDebugDisplayInfo & DebugDisplay, float & YL, float & YPos) override virtual
EndInactiveState()
virtual void AController::EndInactiveState () protected virtual
Called when leaving the inactive state.
References EndInactiveState().
Referenced by EndInactiveState().
FailedToSpawnPawn()
virtual void AController::FailedToSpawnPawn () virtual
GameMode failed to spawn pawn for me.
References FailedToSpawnPawn().
Referenced by FailedToSpawnPawn().
GameHasEnded()
virtual void AController::GameHasEnded (class AActor * EndGameFocus = nullptr, bool bIsWinner = false) virtual
Called from game mode upon end of the game, used to transition to proper state.
Parameters
EndGameFocus Actor to set as the view target on end game
bIsWinner true if this controller is on winning team
References GameHasEnded().
Referenced by GameHasEnded().
GetActorEyesViewPoint()
virtual void AController::GetActorEyesViewPoint (FVector & out_Location, FRotator & out_Rotation) const override virtual
References FVector.
GetCharacter()
FORCEINLINE ACharacter * AController::GetCharacter () const inline
Getter for Character.
Definition at line 240 of file Controller.h.
References Character, and FORCEINLINE.
GetHumanReadableName()
virtual FString AController::GetHumanReadableName () const override virtual
GetLifetimeReplicatedProps()
virtual void AController::GetLifetimeReplicatedProps (TArray< FLifetimeProperty > & OutLifetimeProps) const override virtual
GetMoveGoalReachTest()
virtual void AController::GetMoveGoalReachTest (const AActor * MovingActor, const FVector & MoveOffset, FVector & GoalOffset, float & GoalRadius, float & GoalHalfHeight) const override virtual
Get cylinder for testing if actor has been reached.
Parameters
MoveOffset - destination (relative to actor's nav location)
GoalOffset - cylinder center (relative to actor's nav location)
GoalRadius - cylinder radius
GoalHalfHeight - cylinder half height
Reimplemented from INavAgentInterface.
References const, FVector, GetMoveGoalReachTest(), INavAgentInterface::GoalOffset, INavAgentInterface::GoalRadius, and INavAgentInterface::MoveOffset.
Referenced by GetMoveGoalReachTest().
GetNavAgentLocation()
virtual FVector AController::GetNavAgentLocation () const override virtual
References const, FVector, and GetNavAgentLocation().
Referenced by GetNavAgentLocation().
GetNavAgentPropertiesRef()
virtual const struct FNavAgentProperties & AController::GetNavAgentPropertiesRef () const override virtual
References const, and GetNavAgentPropertiesRef().
Referenced by GetNavAgentPropertiesRef().
GetOnNewPawnNotifier()
FPawnChangedSignature & AController::GetOnNewPawnNotifier () inline
Definition at line 209 of file Controller.h.
References GetOnNewPawnNotifier(), and OnNewPawn.
Referenced by GetOnNewPawnNotifier().
GetPathFollowingAgent()
virtual IPathFollowingAgentInterface * AController::GetPathFollowingAgent () const override virtual
Retrieves PathFollowingAgent for this NavAgent.
Reimplemented from INavAgentInterface.
References const, and GetPathFollowingAgent().
Referenced by GetPathFollowingAgent().
GetPawn() [1/2]
FORCEINLINE TObjectPtr< APawn > AController::GetPawn () const inline
Getter for Pawn.
Definition at line 230 of file Controller.h.
References FORCEINLINE, and Pawn.
Referenced by FAISystem::IsValidControllerAndHasValidPawn().
GetPawn() [2/2]
template<class T> T * AController::GetPawn () const inline
Templated version of GetPawn, will return nullptr if cast fails.
Definition at line 234 of file Controller.h.
References Cast(), and Pawn.
GetPlayerState()
template<class T> T * AController::GetPlayerState () const inline
Returns
this controller's PlayerState cast to the template type, or NULL if there is not one. May return null if the cast fails.
Definition at line 192 of file Controller.h.
References Cast(), and GetPlayerState().
Referenced by GetPlayerState().
GetStateName()
FName AController::GetStateName () const
Returns
the name of the current state
GetTransformComponent()
class USceneComponent * AController::GetTransformComponent () const inline protected
Returns TransformComponent subobject.
Definition at line 137 of file Controller.h.
References GetTransformComponent().
Referenced by GetTransformComponent().
HIDE_ACTOR_TRANSFORM_FUNCTIONS()
AController::HIDE_ACTOR_TRANSFORM_FUNCTIONS () private
References bIsPlayerController, FORCEINLINE_DEBUGGABLE, and HIDE_ACTOR_TRANSFORM_FUNCTIONS().
Referenced by HIDE_ACTOR_TRANSFORM_FUNCTIONS().
InitPlayerState()
virtual void AController::InitPlayerState () virtual
spawns and initializes the PlayerState for this Controller
References InitPlayerState().
Referenced by InitPlayerState().
InstigatedAnyDamage()
virtual void AController::InstigatedAnyDamage (float Damage, const class UDamageType * DamageType, class AActor * DamagedActor, class AActor * DamageCauser) virtual
Called when this controller instigates ANY damage.
References const, Damage, DamageCauser, DamagedActor, DamageType, and InstigatedAnyDamage().
Referenced by InstigatedAnyDamage().
IsFollowingAPath()
virtual bool AController::IsFollowingAPath () const override virtual
Checks if the agent is actively following a navigation path.
Reimplemented from INavAgentInterface.
References const, and IsFollowingAPath().
Referenced by IsFollowingAPath().
IsInState()
bool AController::IsInState (FName InStateName) const
States (uses FNames for replication, correlated to state flags)
Parameters
StateName the name of the state to test against
Returns
true if current state is StateName
IsValidControlRotation()
bool AController::IsValidControlRotation (FRotator CheckRotation) const protected
Return false if rotation contains NaN or extremely large values (usually resulting from uninitialized values).
References Category, const, IsValidControlRotation(), and UPROPERTY().
Referenced by IsValidControlRotation().
K2_DestroyActor()
virtual void AController::K2_DestroyActor () override virtual
OnPossess()
virtual void AController::OnPossess (APawn * InPawn) protected virtual
Overridable native function for when this controller is asked to possess a pawn.
Parameters
InPawn The Pawn to be possessed
References OnPossess().
Referenced by OnPossess().
OnUnPossess()
virtual void AController::OnUnPossess () protected virtual
Overridable native function for when this controller unpossesses its pawn.
References OnUnPossess().
Referenced by OnUnPossess().
PawnPendingDestroy()
virtual void AController::PawnPendingDestroy (APawn * inPawn) virtual
Called to unpossess our pawn because it is going to be destroyed.
(other unpossession handled by UnPossess())
References PawnPendingDestroy().
Referenced by PawnPendingDestroy().
PostInitializeComponents()
virtual void AController::PostInitializeComponents () override virtual
Overridden to create the player replication info and perform other mundane initialization tasks.
RemovePawnTickDependency()
virtual void AController::RemovePawnTickDependency (APawn * InOldPawn) protected virtual
Remove dependency that makes us tick before the given Pawn.
References RemovePawnTickDependency().
Referenced by RemovePawnTickDependency().
Reset()
virtual void AController::Reset () override virtual
SetPawn()
virtual void AController::SetPawn (APawn * InPawn) virtual
Setter for Pawn.
Normally should only be used internally when possessing/unpossessing a Pawn.
SetPawn_Direct()
void AController::SetPawn_Direct (APawn * InPawn) private
References SetPawn_Direct().
Referenced by SetPawn_Direct().
SetPawnFromRep()
void AController::SetPawnFromRep (APawn * InPawn)
Calls SetPawn and RepNotify locally.
SetPlayerState()
void AController::SetPlayerState (APlayerState * InPlayerState) private
ShouldParticipateInSeamlessTravel()
virtual bool AController::ShouldParticipateInSeamlessTravel () const virtual
Returns whether this controller should persist through seamless travel.
References const, and ShouldParticipateInSeamlessTravel().
Referenced by ShouldParticipateInSeamlessTravel().
ShouldPostponePathUpdates()
virtual bool AController::ShouldPostponePathUpdates () const override virtual
Allows delaying repath requests.
Reimplemented from INavAgentInterface.
References const, and ShouldPostponePathUpdates().
Referenced by ShouldPostponePathUpdates().
TickActor()
virtual void AController::TickActor (float DeltaTime, enum ELevelTick TickType, FActorTickFunction & ThisTickFunction) override virtual
References DeltaTime.
UFUNCTION() [1/28]
AController::UFUNCTION () const
Get the actor the controller is looking at.
References Category, and Pawn.
UFUNCTION() [2/28]
AController::UFUNCTION () const
Returns whether this Controller is a local controller.
References Category, and Pawn.
UFUNCTION() [3/28]
AController::UFUNCTION () const
Returns true if look input is ignored.
References Category, const, Input, and UFUNCTION().
UFUNCTION() [4/28]
AController::UFUNCTION () const
Returns true if movement input is ignored.
References Category, const, Input, and UFUNCTION().
UFUNCTION() [5/28]
AController::UFUNCTION () const
Checks line to center and top of other actor.
Parameters
Other is the actor whose visibility is being checked.
ViewPoint is eye position visibility is being checked from. If vect(0,0,0) passed in, uses current viewtarget's eye position.
bAlternateChecks used only in AIController implementation
Returns
true if controller's pawn can see Other actor.
References Category, and UFUNCTION().
UFUNCTION() [6/28]
AController::UFUNCTION () const
Get the control rotation.
This is the full aim rotation, which may be different than a camera orientation (for example in a third person view), and may differ from the rotation of the controlled Pawn (which may choose not to visually pitch or roll, for example).
References Category, and Pawn.
Referenced by UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
UFUNCTION() [7/28]
AController::UFUNCTION () const
Get the desired pawn target rotation.
References Category, and Pawn.
UFUNCTION() [8/28]
AController::UFUNCTION () &
Returns Player's Point of View For the AI this means the Pawn's 'Eyes' ViewPoint For a Human player, this means the Camera's ViewPoint.
@output out_Location, view location of player @output out_rotation, view rotation of player
References Category, Pawn, and UFUNCTION().
UFUNCTION() [9/28]
AController::UFUNCTION ()
Replication Notification Callbacks.
References UFUNCTION().
UFUNCTION() [10/28]
AController::UFUNCTION ()
References UFUNCTION().
UFUNCTION() [11/28]
AController::UFUNCTION ()
Reset move and look input ignore flags.
References Category, Input, and UFUNCTION().
UFUNCTION() [12/28]
AController::UFUNCTION ()
Locks or unlocks look input, consecutive calls stack up and require the same amount of calls to undo, or can all be undone using ResetIgnoreLookInput.
Parameters
bNewLookInput If true, look input is ignored. If false, input is not ignored.
References Category, Input, and UFUNCTION().
UFUNCTION() [13/28]
AController::UFUNCTION ()
Locks or unlocks movement input, consecutive calls stack up and require the same amount of calls to undo, or can all be undone using ResetIgnoreMoveInput.
Parameters
bNewMoveInput If true, move input is ignored. If false, input is not ignored.
References Category, Input, and UFUNCTION().
UFUNCTION() [14/28]
AController::UFUNCTION () const &
Set the initial location and rotation of the controller, as well as the control rotation.
Typically used when the controller is first created.
References Category, Pawn, and UFUNCTION().
UFUNCTION() [15/28]
AController::UFUNCTION ()
Aborts the move the controller is currently performing.
References Category, and UFUNCTION().
UFUNCTION() [16/28]
AController::UFUNCTION ()
Replicated function to set the pawn location and rotation, allowing server to force (ex.
teleports).
References Client.
UFUNCTION() [17/28]
AController::UFUNCTION ()
Replicated function to set the pawn rotation, allowing the server to force.
References Client, and UFUNCTION().
UFUNCTION() [18/28]
AController::UFUNCTION () protected
Event when this controller instigates ANY damage.
References UFUNCTION().
UFUNCTION() [19/28]
AController::UFUNCTION () const
Returns whether this Controller is a locally controlled PlayerController.
References Category, and Pawn.
UFUNCTION() [20/28]
AController::UFUNCTION () const
Returns whether this Controller is a PlayerController.
References Category, and Pawn.
UFUNCTION() [21/28]
AController::UFUNCTION () const
Return the Pawn that is currently 'controlled' by this PlayerController.
References Category, const, meta, Pawn, and UFUNCTION().
UFUNCTION() [22/28]
AController::UFUNCTION () final
Handles attaching this controller to the specified pawn.
Only runs on the network authority (where HasAuthority() returns true). Derived native classes can override OnPossess to filter the specified pawn. When possessed pawn changed, blueprint class gets notified by ReceivePossess and OnNewPawn delegate is broadcasted.
Parameters
InPawn The Pawn to be possessed.
See also
HasAuthority, OnPossess, ReceivePossess
References Category, Keywords, meta, and Pawn.
UFUNCTION() [23/28]
AController::UFUNCTION ()
Stops ignoring look input by resetting the ignore look input state.
References Category, Input, Keywords, meta, and UFUNCTION().
UFUNCTION() [24/28]
AController::UFUNCTION ()
Stops ignoring move input by resetting the ignore move input state.
References Category, Input, Keywords, meta, and UFUNCTION().
UFUNCTION() [25/28]
AController::UFUNCTION () const &
Set the control rotation.
The RootComponent's rotation will also be updated to match it if RootComponent->bAbsoluteRotation is true.
References Category, const, meta, NewRotation, and Pawn.
UFUNCTION() [26/28]
AController::UFUNCTION () final
Called to unpossess our pawn for any reason that is not the pawn being destroyed (destruction handled by PawnDestroyed()).
References Category, Keywords, meta, Pawn, and UFUNCTION().
UFUNCTION() [27/28]
AController::UFUNCTION () protected
Blueprint implementable event to react to the controller possessing a pawn.
References meta, and UFUNCTION().
UFUNCTION() [28/28]
AController::UFUNCTION () protected
Blueprint implementable event to react to the controller unpossessing a pawn.
References meta, and UFUNCTION().
UPROPERTY() [1/8]
AController::UPROPERTY () private
Called when the controller has instigated damage in any way.
UPROPERTY() [2/8]
AController::UPROPERTY () private
Current gameplay state this controller is in.
UPROPERTY() [3/8]
AController::UPROPERTY () private
Called on both authorities and clients when the possessed pawn changes (either OldPawn or NewPawn might be nullptr)
References Category, and Pawn.
UPROPERTY() [4/8]
AController::UPROPERTY () protected
The control rotation of the Controller.
See GetControlRotation.
References UPROPERTY().
UPROPERTY() [5/8]
AController::UPROPERTY () private
Character currently being controlled by this controller.
Value is same as Pawn if the controlled pawn is a character, otherwise nullptr
References Character, and UPROPERTY().
UPROPERTY() [6/8]
AController::UPROPERTY () private
Pawn currently being controlled by this controller.
Use Pawn.Possess() to take control of a pawn
References Pawn, and UPROPERTY().
UPROPERTY() [7/8]
GENERATED_BODY() public AController::UPROPERTY () private
Default Constructor.
PlayerState containing replicated information about the player using this controller (only exists for players, not NPCs).
References Category.
Referenced by IsValidControlRotation(), UPROPERTY(), UPROPERTY(), UPROPERTY(), and UPROPERTY().
UPROPERTY() [8/8]
AController::UPROPERTY () private
Component to give controllers a transform and enable attachment if desired.
References UPROPERTY().
Field Documentation
bAlternateChecks
FVector bool AController::bAlternateChecks = false) const
Definition at line 178 of file Controller.h.
bCanPossessWithoutAuthority
uint8 AController::bCanPossessWithoutAuthority protected
Whether the controller must have authority to be able to call possess on a Pawn.
Definition at line 112 of file Controller.h.
bIsPlayerController
UPROPERTY () uint8 bAttachToPawn uint8 AController::bIsPlayerController protected
If true, the controller location will match the possessed Pawn's location.
If false, it will not be updated. Rotation will match ControlRotation in either case. Since a Controller's location is normally inaccessible, this is intended mainly for purposes of being able to attach an Actor that follows the possessed Pawn location, but that still has the full aim rotation (since a Pawn might update only some components of the rotation). Whether this controller is a PlayerController.
Definition at line 109 of file Controller.h.
Referenced by HIDE_ACTOR_TRANSFORM_FUNCTIONS().
bResetCamera
bool AController::bResetCamera = false)
Definition at line 203 of file Controller.h.
const
FRotator& Rotation AController::const
Definition at line 334 of file Controller.h.
Referenced by GetMoveGoalReachTest(), GetNavAgentLocation(), GetNavAgentPropertiesRef(), GetPathFollowingAgent(), InstigatedAnyDamage(), IsFollowingAPath(), IsValidControlRotation(), ShouldParticipateInSeamlessTravel(), ShouldPostponePathUpdates(), UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
DamageCauser
const class UDamageType class AActor class AActor* AController::DamageCauser protected
Definition at line 401 of file Controller.h.
Referenced by InstigatedAnyDamage().
DamagedActor
const class UDamageType class AActor* AController::DamagedActor protected
Definition at line 401 of file Controller.h.
Referenced by InstigatedAnyDamage().
DamageType
const class UDamageType* AController::DamageType protected
Definition at line 401 of file Controller.h.
Referenced by InstigatedAnyDamage().
IgnoreLookInput
uint8 AController::IgnoreLookInput protected
Ignores look input.
Stacked state storage, use accessor function IgnoreLookInput().
Definition at line 118 of file Controller.h.
IgnoreMoveInput
uint8 AController::IgnoreMoveInput protected
Ignores movement input.
Stacked state storage, Use accessor function IgnoreMoveInput()
Definition at line 115 of file Controller.h.
NewRotation [1/2]
const FRotator& AController::NewRotation
Definition at line 167 of file Controller.h.
Referenced by UFUNCTION().
NewRotation [2/2]
FRotator AController::NewRotation
Definition at line 199 of file Controller.h.
OldPawn
TWeakObjectPtr< APawn > AController::OldPawn private
Used to track when pawn changes during OnRep_Pawn.
It's possible to use a OnRep parameter here, but I'm not sure what happens with pointers yet so playing it safe.
Definition at line 78 of file Controller.h.
OnNewPawn
FPawnChangedSignature AController::OnNewPawn protected
Delegate broadcast on authorities when possessing a new pawn or unpossessing one.
Definition at line 90 of file Controller.h.
Referenced by GetOnNewPawnNotifier().
StartSpot
TWeakObjectPtr<class AActor> AController::StartSpot private
Actor marking where this controller spawned in.
Definition at line 54 of file Controller.h.
ViewPoint
FVector AController::ViewPoint = FVector(ForceInit)
Definition at line 178 of file Controller.h.
The documentation for this class was generated from the following file:
Runtime/Engine/Classes/GameFramework/Controller.h