Unreal Engine 5.6 C++ API: UGroomAsset Class Reference
UGroomAsset Class Reference abstract
#include "GroomAsset.h"
Public Types
enum EClassDataStripFlag : uint8 {
CDSF_ImportedStrands = 1 , CDSF_MinLodData = 2 , CDSF_StrandsStripped = 4 , CDSF_CardsStripped = 8 ,
CDSF_MeshesStripped = 16
}
Public Types inherited from UObject
enum class ENetFields_Private { NETFIELD_REP_START = 0 , NETFIELD_REP_END = -1 }
using FPostCDOCompiledContext = FObjectPostCDOCompiledContext
Public Member Functions
virtual HAIRSTRANDSCORE_API void AddAssetUserData (UAssetUserData *InUserData) override
HAIRSTRANDSCORE_API bool AreGroupsValid () const
virtual HAIRSTRANDSCORE_API void BeginDestroy () override
Called before destroying the object.
HAIRSTRANDSCORE_API bool BuildCardsData ()
HAIRSTRANDSCORE_API bool BuildMeshesData ()
HAIRSTRANDSCORE_API bool CanRebuildFromDescription () const
Returns true if the asset has the HairDescription needed to recompute its groom data.
HAIRSTRANDSCORE_API void ChangeFeatureLevel (ERHIFeatureLevel::Type PendingFeatureLevel)
HAIRSTRANDSCORE_API void ChangePlatformLevel (ERHIFeatureLevel::Type PendingFeatureLevel)
HAIRSTRANDSCORE_API void ClearNumGroup (uint32 InGroupCount)
HAIRSTRANDSCORE_API TArray< FHairVertexFactoryTypesPerMaterialData > CollectVertexFactoryTypesPerMaterialData (EShaderPlatform ShaderPlatform)
Used for PSO precaching of used materials and vertex factories.
virtual HAIRSTRANDSCORE_API TObjectPtr< UDataflowBaseContent > CreateDataflowContent () override
HAIRSTRANDSCORE_API void CreateDebugData ()
HAIRSTRANDSCORE_API uint8 GenerateClassStripFlags (FArchive &Ar)
uint32 GetAssetHash () const
HAIRSTRANDSCORE_API FName GetAssetPathName (int32 LODIndex=-1)
Helper function to return the asset path name, optionally joined with the LOD index if LODIndex > -1.
virtual HAIRSTRANDSCORE_API const TArray< UAssetUserData * > * GetAssetUserDataArray () const override
virtual HAIRSTRANDSCORE_API UAssetUserData * GetAssetUserDataOfClass (TSubclassOf< UAssetUserData > InUserDataClass) override
HAIRSTRANDSCORE_API float GetAutoLODBias () const
HAIRSTRANDSCORE_API float GetAutoLODBias (int32 InGroupIndex) const
HAIRSTRANDSCORE_API EGroomBindingType GetBindingType (int32 GroupIndex, int32 LODIndex) const
FGroomDataflowSettings & GetDataflowSettings ()
Return the Dataflow settings associated to this groom asset if any.
const FGroomDataflowSettings & GetDataflowSettings () const
Return the Dataflow settings associated to this groom asset if any, const version.
HAIRSTRANDSCORE_API const TArray< int32 > & GetDeformedGroupSections () const
HAIRSTRANDSCORE_API FPerPlatformBool GetDisableBelowMinLodStripping () const
HAIRSTRANDSCORE_API TArray< float > & GetEffectiveLODBias ()
HAIRSTRANDSCORE_API const TArray< float > & GetEffectiveLODBias () const
HAIRSTRANDSCORE_API EGroomGeometryType GetGeometryType (int32 GroupIndex, int32 LODIndex) const
EGroomGuideType GetGuideType (int32 GroupIndex) const
HAIRSTRANDSCORE_API const TArray< FHairGroupsCardsSourceDescription > & GetHairGroupsCards () const
HAIRSTRANDSCORE_API TArray< FHairGroupInfoWithVisibility > & GetHairGroupsInfo ()
HAIRSTRANDSCORE_API const TArray< FHairGroupInfoWithVisibility > & GetHairGroupsInfo () const
HAIRSTRANDSCORE_API const TArray< FHairGroupsInterpolation > & GetHairGroupsInterpolation () const
HAIRSTRANDSCORE_API const TArray< FHairGroupsLOD > & GetHairGroupsLOD () const
HAIRSTRANDSCORE_API const TArray< FHairGroupsMaterial > & GetHairGroupsMaterials () const
HAIRSTRANDSCORE_API const TArray< FHairGroupsMeshesSourceDescription > & GetHairGroupsMeshes () const
HAIRSTRANDSCORE_API const TArray< FHairGroupsPhysics > & GetHairGroupsPhysics () const
HAIRSTRANDSCORE_API TArray< FHairGroupPlatformData > & GetHairGroupsPlatformData ()
HAIRSTRANDSCORE_API const TArray< FHairGroupPlatformData > & GetHairGroupsPlatformData () const
HAIRSTRANDSCORE_API const TArray< FHairGroupsRendering > & GetHairGroupsRendering () const
HAIRSTRANDSCORE_API TArray< FHairGroupResources > & GetHairGroupsResources ()
HAIRSTRANDSCORE_API const TArray< FHairGroupResources > & GetHairGroupsResources () const
HAIRSTRANDSCORE_API int32 GetLODCount () const
HAIRSTRANDSCORE_API EGroomLODMode GetLODMode () const
HAIRSTRANDSCORE_API int32 GetMaterialIndex (FName MaterialSlotName) const
HAIRSTRANDSCORE_API TArray< FName > GetMaterialSlotNames () const
HAIRSTRANDSCORE_API FPerPlatformInt GetMinLOD () const
HAIRSTRANDSCORE_API int32 GetNumHairGroups () const
FOnGroomAssetChanged & GetOnGroomAssetChanged ()
FOnGroomAssetResourcesChanged & GetOnGroomAssetResourcesChanged ()
FOnGroomAsyncLoadFinished & GetOnGroomAsyncLoadFinished ()
virtual HAIRSTRANDSCORE_API void GetResourceSizeEx (FResourceSizeEx &CumulativeResourceSize) override
Get the size of the object/resource for use in memory tools or to display to artists/LDs in the Editor This is the extended version which separates up the used memory into different memory regions (the actual definition of which may be platform specific).
HAIRSTRANDSCORE_API bool HasDebugData () const
Debug data for derived asset generation (strands textures, ...).
HAIRSTRANDSCORE_API bool HasGeometryType (EGroomGeometryType Type) const
HAIRSTRANDSCORE_API bool HasGeometryType (uint32 GroupIndex, EGroomGeometryType Type) const
HAIRSTRANDSCORE_API void InitCardsResources ()
HAIRSTRANDSCORE_API void InitGuideResources ()
HAIRSTRANDSCORE_API void InitMeshesResources ()
HAIRSTRANDSCORE_API void InitResources ()
Initialize/Update/Release resources.
HAIRSTRANDSCORE_API void InitStrandsResources ()
HAIRSTRANDSCORE_API bool IsDeformationEnable (int32 GroupIndex) const
HAIRSTRANDSCORE_API bool IsGlobalInterpolationEnable (int32 GroupIndex, int32 LODIndex) const
HAIRSTRANDSCORE_API bool IsMaterialSlotNameValid (FName MaterialSlotName) const
HAIRSTRANDSCORE_API bool IsMaterialUsed (int32 MaterialIndex) const
HAIRSTRANDSCORE_API bool IsSimulationEnable () const
HAIRSTRANDSCORE_API bool IsSimulationEnable (int32 GroupIndex, int32 LODIndex) const
bool IsValid () const
HAIRSTRANDSCORE_API bool IsVisible (int32 GroupIndex, int32 LODIndex) const
HAIRSTRANDSCORE_API void MarkMaterialsHasChanged ()
virtual HAIRSTRANDSCORE_API bool Modify (bool bAlwaysMarkDirty=true) override
Part of Uobject interface.
HAIRSTRANDSCORE_API bool NeedsInterpolationData () const
HAIRSTRANDSCORE_API bool NeedsInterpolationData (int32 GroupIndex) const
virtual HAIRSTRANDSCORE_API void PostEditChangeProperty (FPropertyChangedEvent &PropertyChangedEvent) override
Called when a property on this object has been modified externally.
virtual HAIRSTRANDSCORE_API void PostLoad () override
Do any object-specific cleanup required immediately after loading an object.
virtual HAIRSTRANDSCORE_API void ReadDataflowContent (const TObjectPtr< UDataflowBaseContent > &DataflowContent) override
HAIRSTRANDSCORE_API void RecreateResources ()
HAIRSTRANDSCORE_API void ReleaseCardsResource (uint32 GroupIndex)
HAIRSTRANDSCORE_API void ReleaseGuidesResource (uint32 GroupIndex)
HAIRSTRANDSCORE_API void ReleaseMeshesResource (uint32 GroupIndex)
HAIRSTRANDSCORE_API void ReleaseResource ()
HAIRSTRANDSCORE_API void ReleaseStrandsResource (uint32 GroupIndex)
virtual HAIRSTRANDSCORE_API void RemoveUserDataOfClass (TSubclassOf< UAssetUserData > InUserDataClass) override
virtual HAIRSTRANDSCORE_API void Serialize (FArchive &Ar) override
Handles reading, writing, and reference collecting using FArchive.
void SetDataflowSettings (const FGroomDataflowSettings &InDataflowSettings)
Set the Dataflow settings associated to this groom asset if any.
HAIRSTRANDSCORE_API void SetDisableBelowMinLodStripping (FPerPlatformBool In)
HAIRSTRANDSCORE_API void SetEffectiveLODBias (const TArray< float > &In)
HAIRSTRANDSCORE_API void SetHairGroupsInfo (const TArray< FHairGroupInfoWithVisibility > &In)
HAIRSTRANDSCORE_API void SetHairGroupsPlatformData (const TArray< FHairGroupPlatformData > &In)
HAIRSTRANDSCORE_API void SetHairWidth (float Width)
HAIRSTRANDSCORE_API void SetMinLOD (FPerPlatformInt In)
HAIRSTRANDSCORE_API void SetNumGroup (uint32 InGroupCount, bool bResetGroupData=true, bool bResetOtherData=true)
HAIRSTRANDSCORE_API void SetScatterSceneLighting (bool Enable)
HAIRSTRANDSCORE_API void SetStableRasterization (bool bEnable)
UE_DEPRECATED (5.3, "Please do not access this member directly; use UGroomAsset accessor.") TArray< FHairGroupPlatformData > HairGroupsPlatformData
Store strands/cards/meshes data.
UE_DEPRECATED (5.3, "Please do not access this member directly; use UGroomAsset accessor.") UPROPERTY() "
Enable radial basis function interpolation to be used instead of the local skin rigid transform.
UE_DEPRECATED (5.3, "Please do not access this member directly; use UGroomAsset accessor.") UPROPERTY() ")) EGroomInterpolationType HairInterpolationType
Type of interpolation used.
UE_DEPRECATED (5.3, "Please do not access this member directly; use UGroomAsset accessor.") UPROPERTY() FPerPlatformBool DisableBelowMinLodStripping
When true all LODs below MinLod will still be cooked.
UE_DEPRECATED (5.3, "Please do not access this member directly; use UGroomAsset accessor.") UPROPERTY() TArray< float > EffectiveLODBias
The LOD bias to use after LOD stripping, regardless of MinLOD.
UE_DEPRECATED (5.3, "Please do not access this member directly; use UGroomAsset accessor.") UPROPERTY() TArray< int32 > DeformedGroupSections
Deformed skeletal mesh mapping from groups to sections.
UE_DEPRECATED (5.3, "Please do not access this member directly; use UGroomAsset accessor.") UPROPERTY() TObjectPtr< USkeletalMesh > RiggedSkeletalMesh
Deformed skeletal mesh that will drive the groom deformation/simulation.
UE_DEPRECATED (5.3, "Please do not access this member directly; use UGroomAsset accessor.") UPROPERTY()) bool EnableSimulationCache
Enable guide-cache support.
UE_DEPRECATED (5.3, "Please do not access this member directly; use UGroomAsset accessor.") UPROPERTY()) FPerPlatformInt MinLOD
Minimum LOD to cook.
UE_DEPRECATED (5.3, "Please do not access this member directly; use UGroomAsset accessor.") UPROPERTY()) TArray< FHairGroupInfoWithVisibility > HairGroupsInfo
UE_DEPRECATED (5.3, "Please do not access this member directly; use UGroomAsset accessor.") UPROPERTY()) TArray< FHairGroupsCardsSourceDescription > HairGroupsCards
Cards - Source description data.
UE_DEPRECATED (5.3, "Please do not access this member directly; use UGroomAsset accessor.") UPROPERTY()) TArray< FHairGroupsInterpolation > HairGroupsInterpolation
UE_DEPRECATED (5.3, "Please do not access this member directly; use UGroomAsset accessor.") UPROPERTY()) TArray< FHairGroupsLOD > HairGroupsLOD
UE_DEPRECATED (5.3, "Please do not access this member directly; use UGroomAsset accessor.") UPROPERTY()) TArray< FHairGroupsMaterial > HairGroupsMaterials
Meshes - Source description data.
UE_DEPRECATED (5.3, "Please do not access this member directly; use UGroomAsset accessor.") UPROPERTY()) TArray< FHairGroupsMeshesSourceDescription > HairGroupsMeshes
Meshes - Source description data.
UE_DEPRECATED (5.3, "Please do not access this member directly; use UGroomAsset accessor.") UPROPERTY()) TArray< FHairGroupsPhysics > HairGroupsPhysics
UE_DEPRECATED (5.3, "Please do not access this member directly; use UGroomAsset accessor.") UPROPERTY()) TArray< FHairGroupsRendering > HairGroupsRendering
UFUNCTION () HAIRSTRANDSCORE_API bool GetEnableGlobalInterpolation() const
UFUNCTION () HAIRSTRANDSCORE_API bool GetEnableSimulationCache() const
UFUNCTION () HAIRSTRANDSCORE_API EGroomInterpolationType GetHairInterpolationType() const
UFUNCTION () HAIRSTRANDSCORE_API TArray< FHairGroupsCardsSourceDescription > &GetHairGroupsCards()
UFUNCTION () HAIRSTRANDSCORE_API TArray< FHairGroupsInterpolation > &GetHairGroupsInterpolation()
UFUNCTION () HAIRSTRANDSCORE_API TArray< FHairGroupsLOD > &GetHairGroupsLOD()
UFUNCTION () HAIRSTRANDSCORE_API TArray< FHairGroupsMaterial > &GetHairGroupsMaterials()
UFUNCTION () HAIRSTRANDSCORE_API TArray< FHairGroupsMeshesSourceDescription > &GetHairGroupsMeshes()
UFUNCTION () HAIRSTRANDSCORE_API TArray< FHairGroupsPhysics > &GetHairGroupsPhysics()
UFUNCTION () HAIRSTRANDSCORE_API TArray< FHairGroupsRendering > &GetHairGroupsRendering()
UFUNCTION () HAIRSTRANDSCORE_API TArray< int32 > &GetDeformedGroupSections()
UFUNCTION () HAIRSTRANDSCORE_API USkeletalMesh *GetRiggedSkeletalMesh() const
UFUNCTION () HAIRSTRANDSCORE_API void SetDeformedGroupSections(const TArray< int32 > &In)
UFUNCTION () HAIRSTRANDSCORE_API void SetEnableGlobalInterpolation(bool In)
UFUNCTION () HAIRSTRANDSCORE_API void SetEnableSimulationCache(bool In)
UFUNCTION () HAIRSTRANDSCORE_API void SetHairGroupsCards(const TArray< FHairGroupsCardsSourceDescription > &In)
UFUNCTION () HAIRSTRANDSCORE_API void SetHairGroupsInterpolation(const TArray< FHairGroupsInterpolation > &In)
UFUNCTION () HAIRSTRANDSCORE_API void SetHairGroupsLOD(const TArray< FHairGroupsLOD > &In)
UFUNCTION () HAIRSTRANDSCORE_API void SetHairGroupsMaterials(const TArray< FHairGroupsMaterial > &In)
UFUNCTION () HAIRSTRANDSCORE_API void SetHairGroupsMeshes(const TArray< FHairGroupsMeshesSourceDescription > &In)
UFUNCTION () HAIRSTRANDSCORE_API void SetHairGroupsPhysics(const TArray< FHairGroupsPhysics > &In)
UFUNCTION () HAIRSTRANDSCORE_API void SetHairGroupsRendering(const TArray< FHairGroupsRendering > &In)
UFUNCTION () HAIRSTRANDSCORE_API void SetHairInterpolationType(EGroomInterpolationType In)
UFUNCTION () HAIRSTRANDSCORE_API void SetRiggedSkeletalMesh(USkeletalMesh *In)
HAIRSTRANDSCORE_API void UpdateCachedSettings ()
HAIRSTRANDSCORE_API void UpdateHairGroupsInfo ()
HAIRSTRANDSCORE_API void UpdateResource ()
UPROPERTY () TArray< TObjectPtr< UAssetUserData > > AssetUserData
Array of user data stored with the asset.
HAIRSTRANDSCORE_API void ValidateSimulationCache ()
Enable the simulation cache and recompute the cached derived data.
virtual HAIRSTRANDSCORE_API void WriteDataflowContent (const TObjectPtr< UDataflowBaseContent > &DataflowContent) const override
Public Member Functions inherited from UObject
void AbortInsideMemberFunction () const
Abort with a member function call at the top of the callstack, helping to ensure that most platforms will stuff this object's memory into the resulting minidump.
virtual bool AreNativePropertiesIdenticalTo (UObject *Other) const
Returns whether native properties are identical to the one of the passed in component.
virtual void BeginCacheForCookedPlatformData (const ITargetPlatform *TargetPlatform)
Starts caching of platform specific data for the target platform Called when cooking before serialization so that object can prepare platform specific data Not called during normal loading of objects.
virtual void BuildSubobjectMapping (UObject *OtherObject, TMap< UObject *, UObject * > &ObjectMapping) const
Given OtherObject (which will be the same type as 'this'), recursively find any matching sub-objects from 'this' that also exist within OtherObject, and add the mappings to ObjectMapping.
void CallAddReferencedObjects (FReferenceCollector &Collector)
Helper function to call AddReferencedObjects for this object's class.
void CallFunction (FFrame &Stack, RESULT_DECL, UFunction *Function)
Internal VM method for executing a function.
bool CallFunctionByNameWithArguments (const TCHAR *Cmd, FOutputDevice &Ar, UObject *Executor, bool bForceCallWithNonExec=false)
Handle calling a function by name when executed from the console or a command line.
virtual bool CallRemoteFunction (UFunction *Function, void *Parms, struct FOutParmRec *OutParms, FFrame *Stack)
Call the actor's function remotely.
virtual bool CanEditChange (const FEditPropertyChain &PropertyChain) const
Alternate version of CanEditChange that includes the full property chain leading to the property in question.
virtual bool CanEditChange (const FProperty *InProperty) const
Called by the editor to query whether a property of this object is allowed to be modified.
bool CanModify () const
Utility to allow overrides of Modify to avoid doing work if this object cannot be safely modified.
bool CheckDefaultSubobjects (bool bForceCheck=false) const
Checks default sub-object assumptions.
virtual void ClearAllCachedCookedPlatformData ()
Clear all cached cooked platform data.
virtual void ClearCachedCookedPlatformData (const ITargetPlatform *TargetPlatform)
Clears cached cooked platform data for specific platform.
virtual void CollectSaveOverrides (FObjectCollectSaveOverridesContext SaveContext)
Collect any save override state.
bool ConditionalBeginDestroy ()
Called before destroying the object.
bool ConditionalFinishDestroy ()
Called when an object is actually destroyed, memory should never be accessed again.
void ConditionalPostLoad ()
PostLoad if needed.
void ConditionalPostLoadSubobjects (struct FObjectInstancingGraph *OuterInstanceGraph=NULL)
Instances subobjects and components for objects being loaded from disk, if necessary.
virtual bool ConformSparseClassDataStruct (UScriptStruct *SourceSparseClassDataStruct, void *SourceSparseClassData) const
void CookAdditionalFiles (const TCHAR *PackageFilename, const ITargetPlatform *TargetPlatform, TFunctionRef< void(const TCHAR *Filename, void *Data, int64 Size)> WriteAdditionalFile)
Called during cook to allow objects to generate additional cooked files alongside their cooked package.
TSharedPtr< ITransactionObjectAnnotation > CreateAndRestoreTransactionAnnotation (FArchive &Ar) const
Create and restore a previously serialized annotation object with any external data required for applying a transaction.
DECLARE_DELEGATE_RetVal_OneParam (bool, FOnGetPreviewPlatform, FName &)
Delegate to return the current preview platform name, or NAME_None if no preview platform is currently active.
DECLARE_FUNCTION (execAddMulticastDelegate)
DECLARE_FUNCTION (execArrayConst)
DECLARE_FUNCTION (execArrayElement)
DECLARE_FUNCTION (execArrayGetByRef)
DECLARE_FUNCTION (execAssert)
DECLARE_FUNCTION (execAutoRtfmAbortIfNot)
DECLARE_FUNCTION (execAutoRtfmStopTransact)
DECLARE_FUNCTION (execAutoRtfmTransact)
DECLARE_FUNCTION (execBindDelegate)
DECLARE_FUNCTION (execBitFieldConst)
DECLARE_FUNCTION (execBoolVariable)
DECLARE_FUNCTION (execBreakpoint)
Breakpoint; only observed in the editor; executing it at any other time is a NOP.
DECLARE_FUNCTION (execByteConst)
DECLARE_FUNCTION (execCallMathFunction)
DECLARE_FUNCTION (execCallMulticastDelegate)
DECLARE_FUNCTION (execCast)
DECLARE_FUNCTION (execClassContext)
DECLARE_FUNCTION (execClassDefaultVariable)
DECLARE_FUNCTION (execClassSparseDataVariable)
DECLARE_FUNCTION (execClearMulticastDelegate)
DECLARE_FUNCTION (execComputedJump)
DECLARE_FUNCTION (execContext)
DECLARE_FUNCTION (execContext_FailSilent)
DECLARE_FUNCTION (execDefaultVariable)
DECLARE_FUNCTION (execDoubleConst)
DECLARE_FUNCTION (execDoubleToFloatCast)
DECLARE_FUNCTION (execDynamicCast)
DECLARE_FUNCTION (execDynArrayAdd)
DECLARE_FUNCTION (execDynArrayAddItem)
DECLARE_FUNCTION (execDynArrayFind)
DECLARE_FUNCTION (execDynArrayFindStruct)
DECLARE_FUNCTION (execDynArrayInsert)
DECLARE_FUNCTION (execDynArrayInsertItem)
DECLARE_FUNCTION (execDynArrayRemove)
DECLARE_FUNCTION (execDynArrayRemoveItem)
DECLARE_FUNCTION (execDynArraySort)
DECLARE_FUNCTION (execEatReturnValue)
DECLARE_FUNCTION (execEmptyParmValue)
DECLARE_FUNCTION (execEndFunctionParms)
DECLARE_FUNCTION (execEndOfScript)
DECLARE_FUNCTION (execEqualEqual_DelegateDelegate)
DECLARE_FUNCTION (execEqualEqual_DelegateFunction)
DECLARE_FUNCTION (execFalse)
DECLARE_FUNCTION (execFieldPathConst)
DECLARE_FUNCTION (execFinalFunction)
DECLARE_FUNCTION (execFloatConst)
DECLARE_FUNCTION (execFloatToDoubleCast)
DECLARE_FUNCTION (execGetDynArrayElement)
DECLARE_FUNCTION (execGetDynArrayLength)
DECLARE_FUNCTION (execInstanceDelegate)
DECLARE_FUNCTION (execInstanceVariable)
DECLARE_FUNCTION (execInstrumentation)
Instrumentation event for profiling; only observed in the builds with blueprint instrumentation.
DECLARE_FUNCTION (execInt64Const)
DECLARE_FUNCTION (execIntConst)
DECLARE_FUNCTION (execIntConstByte)
DECLARE_FUNCTION (execInterfaceCast)
DECLARE_FUNCTION (execInterfaceContext)
DECLARE_FUNCTION (execInterfaceToBool)
DECLARE_FUNCTION (execInterfaceToInterface)
DECLARE_FUNCTION (execInterfaceToObject)
DECLARE_FUNCTION (execInterfaceVariable)
DECLARE_FUNCTION (execIntOne)
DECLARE_FUNCTION (execIntZero)
DECLARE_FUNCTION (execJump)
DECLARE_FUNCTION (execJumpIfNot)
DECLARE_FUNCTION (execLet)
DECLARE_FUNCTION (execLetBool)
DECLARE_FUNCTION (execLetDelegate)
DECLARE_FUNCTION (execLetMulticastDelegate)
DECLARE_FUNCTION (execLetObj)
DECLARE_FUNCTION (execLetValueOnPersistentFrame)
DECLARE_FUNCTION (execLetWeakObjPtr)
DECLARE_FUNCTION (execLocalFinalFunction)
DECLARE_FUNCTION (execLocalOutVariable)
DECLARE_FUNCTION (execLocalVariable)
DECLARE_FUNCTION (execLocalVirtualFunction)
DECLARE_FUNCTION (execMapConst)
DECLARE_FUNCTION (execMetaCast)
DECLARE_FUNCTION (execNameConst)
DECLARE_FUNCTION (execNativeParm)
DECLARE_FUNCTION (execNew)
DECLARE_FUNCTION (execNoObject)
DECLARE_FUNCTION (execNotEqual_DelegateDelegate)
DECLARE_FUNCTION (execNotEqual_DelegateFunction)
DECLARE_FUNCTION (execNothing)
DECLARE_FUNCTION (execNothingInt32)
DECLARE_FUNCTION (execNothingOp4a)
DECLARE_FUNCTION (execNullInterface)
DECLARE_FUNCTION (execObjectConst)
DECLARE_FUNCTION (execObjectToBool)
DECLARE_FUNCTION (execObjectToInterface)
DECLARE_FUNCTION (execPopExecutionFlow)
Pops a code offset from the execution flow stack and starts execution there.
DECLARE_FUNCTION (execPopExecutionFlowIfNot)
Pops a code offset from the execution flow stack and starts execution there, if a condition is not true.
DECLARE_FUNCTION (execPropertyConst)
DECLARE_FUNCTION (execPushExecutionFlow)
Push a code offset onto the execution flow stack for future execution.
DECLARE_FUNCTION (execRemoveMulticastDelegate)
DECLARE_FUNCTION (execReturnNothing)
failsafe for functions that return a value - returns the zero value for a property and logs that control reached the end of a non-void function
DECLARE_FUNCTION (execRotationConst)
DECLARE_FUNCTION (execSelf)
DECLARE_FUNCTION (execSetArray)
DECLARE_FUNCTION (execSetConst)
DECLARE_FUNCTION (execSetDynArrayElement)
DECLARE_FUNCTION (execSetDynArrayLength)
DECLARE_FUNCTION (execSetMap)
DECLARE_FUNCTION (execSetSet)
DECLARE_FUNCTION (execSkipOffsetConst)
DECLARE_FUNCTION (execSoftObjectConst)
DECLARE_FUNCTION (execStringConst)
DECLARE_FUNCTION (execStructCmpEq)
DECLARE_FUNCTION (execStructCmpNe)
DECLARE_FUNCTION (execStructConst)
DECLARE_FUNCTION (execStructMember)
DECLARE_FUNCTION (execStructMemberContext)
DECLARE_FUNCTION (execSwitchValue)
DECLARE_FUNCTION (execTextConst)
DECLARE_FUNCTION (execTracepoint)
Tracepoint; only observed in the editor; executing it at any other time is a NOP.
DECLARE_FUNCTION (execTransformConst)
DECLARE_FUNCTION (execTrue)
DECLARE_FUNCTION (execUInt64Const)
DECLARE_FUNCTION (execUndefined)
DECLARE_FUNCTION (execUnicodeStringConst)
DECLARE_FUNCTION (execVector3fConst)
DECLARE_FUNCTION (execVectorConst)
DECLARE_FUNCTION (execVirtualFunction)
DECLARE_FUNCTION (execWireTracepoint)
DECLARE_FUNCTION (ProcessInternal)
Internal function call processing.
void DestroyNonNativeProperties ()
Destroy properties that won't be destroyed by the native destructor.
void ExecuteUbergraph (int32 EntryPoint)
Execute the ubergraph from a specific entry point.
virtual void ExportCustomProperties (FOutputDevice &Out, uint32 Indent)
Exports the property values for the specified object as text to the output device.
UFunction * FindFunction (FName InName) const
Returns a UFunction with the specified name, wrapper for UClass::FindFunctionByName()
UFunction * FindFunctionChecked (FName InName) const
Version of FindFunction() that will assert if the function was not found.
TSharedPtr< ITransactionObjectAnnotation > FindOrCreateTransactionAnnotation () const
Find or create and populate an annotation object with any external data required for applying a transaction.
virtual void FinishDestroy ()
Called to finish destroying the object.
virtual void GetAdditionalAssetDataObjectsForCook (FArchiveCookContext &CookContext, TArray< UObject * > &OutObjects) const
Get an additional object that should be added to the AssetDatas stored for a cooked package, to handle objects stripped from cooked packages.
UObject * GetArchetype () const
Return the template this object is based on.
void GetArchetypeInstances (TArray< UObject * > &Instances)
Builds a list of objects which have this object in their archetype chain.
virtual void GetAssetRegistryTagMetadata (TMap< FName, FAssetRegistryTagMetadata > &OutMetadata) const
Gathers a collection of asset registry tag metadata.
void GetAssetRegistryTags (FAssetData &Out) const
virtual void GetAssetRegistryTags (FAssetRegistryTagsContext Context) const
Gathers a list of asset registry searchable tags which are name/value pairs with some type information This only needs to be implemented for asset objects.
void GetAssetRegistryTags (FAssetRegistryTagsContext Context, FAssetData &Out) const
Gathers a list of asset registry tags for an FAssetData.
virtual const TCHAR * GetConfigOverridePlatform () const
Returns the override config hierarchy platform (if NDAd platforms need defaults to not be in Base*.ini but still want editor to load them)
FString GetDefaultConfigFilename () const
Get the default config filename for the specified UObject.
virtual FString GetDesc ()
Return a one line description of an object for viewing in the thumbnail view of the generic browser.
FString GetDetailedInfo () const
This will return detail info about this specific object.
virtual FName GetExporterName (void)
Returns the name of the exporter factory used to export this object Used when multiple factories have the same extension.
virtual void GetExtendedAssetRegistryTagsForSave (const ITargetPlatform *TargetPlatform, TArray< FAssetRegistryTag > &OutTags) const
Temporary interim solution to gather asset registry data at save time only.
virtual int32 GetFunctionCallspace (UFunction *Function, FFrame *Stack)
Return the space this function should be called.
FString GetGlobalUserConfigFilename () const
Get the global user override config filename for the specified UObject.
virtual void GetLifetimeReplicatedProps (TArray< class FLifetimeProperty > &OutLifetimeProps) const
Returns properties that are replicated for the lifetime of the actor channel.
virtual bool GetNativePropertyValues (TMap< FString, FString > &out_PropertyValues, uint32 ExportFlags=0) const
Callback for retrieving a textual representation of natively serialized properties.
virtual uint64 GetNetPushIdDynamic () const
Should only ever be used by internal systems.
virtual void GetPreloadDependencies (TArray< UObject * > &OutDeps)
Called during cooking.
virtual void GetPrestreamPackages (TArray< UObject * > &OutPrestream)
Called during cooking.
virtual FPrimaryAssetId GetPrimaryAssetId () const
Returns an Type:Name pair representing the PrimaryAssetId for this object.
FString GetProjectUserConfigFilename () const
Get the project user override config filename for the specified UObject.
virtual void GetReplicatedCustomConditionState (FCustomPropertyConditionState &OutActiveState) const
Called when this object begins replicating to initialize the state of custom property conditions.
SIZE_T GetResourceSizeBytes (EResourceSizeMode::Type Mode)
Get the size of the object/resource for use in memory tools or to display to artists/LDs in the Editor This is the simple version which just returns the total number of bytes used by this object.
virtual FRestoreForUObjectOverwrite * GetRestoreForUObjectOverwrite ()
Save information for StaticAllocateObject in the case of overwriting an existing object.
UScriptStruct * GetSparseClassDataStruct () const
Return the UStruct corresponding to the sidecar data structure that stores data that is constant for all instances of this class.
virtual void GetSubobjectsWithStableNamesForNetworking (TArray< UObject * > &ObjList)
Returns a list of sub-objects that have stable names for networking.
virtual bool HasNonEditorOnlyReferences () const
Called during saving to determine if the object's references are used in game even when the object itself is never loaded outside the editor (because e.g.
template<class T>
FORCEINLINE bool Implements () const
Returns true if this object implements the interface T, false otherwise.
template<class T>
bool Implements () const
Returns true if this object implements the interface T, false otherwise.
virtual void ImportCustomProperties (const TCHAR *SourceText, FFeedbackContext *Warn)
Exports the property values for the specified object as text to the output device.
void InstanceSubobjectTemplates (struct FObjectInstancingGraph *InstanceGraph=NULL)
Wrapper for calling UClass::InstanceSubobjectTemplates() for this object.
virtual bool IsAsset () const
Returns true if this object is considered an asset.
bool IsBasedOnArchetype (const UObject *const SomeObject) const
Determine if this object has SomeObject in its archetype chain.
virtual bool IsCachedCookedPlatformDataLoaded (const ITargetPlatform *TargetPlatform)
Have we finished loading all the cooked platform data for the target platforms requested in BeginCacheForCookedPlatformData.
virtual bool IsCapturingAsRootObjectForTransaction () const
Method to disable the sub object special handling in the transaction buffer for this object.
virtual EDataValidationResult IsDataValid (class FDataValidationContext &Context) const
Generic function to validate objects during changelist validations, etc.
virtual bool IsEditorOnly () const
Called during saving to determine if the object is forced to be editor only or not.
virtual bool IsFullNameStableForNetworking () const
IsFullNameStableForNetworking means an object can be referred to its full path name over the network.
bool IsInBlueprint () const
Returns whether this object is contained in or part of a blueprint object.
virtual bool IsLocalizedResource () const
Returns true if this object is considered a localized resource.
virtual bool IsNameStableForNetworking () const
IsNameStableForNetworking means an object can be referred to its path name (relative to outer) over the network.
virtual bool IsPostLoadThreadSafe () const
Called during async load to determine if PostLoad can be called on the loading thread.
virtual bool IsReadyForAsyncPostLoad () const
Called before calling PostLoad() in FAsyncPackage::PostLoadObjects().
virtual bool IsReadyForFinishDestroy ()
Called to check if the object is ready for FinishDestroy.
virtual bool IsSafeForRootSet () const
Returns true if this object is safe to add to the root set.
bool IsSelected () const
Test the selection state of a UObject.
virtual bool IsSupportedForNetworking () const
IsSupportedForNetworking means an object can be referenced over the network.
void LoadConfig (UClass *ConfigClass=nullptr, const TCHAR *Filename=nullptr, uint32 PropagationFlags=UE::LCPF_None, class FProperty *PropertyToLoad=nullptr, TArray< UE::ConfigAccessTracking::FConfigAccessData > *OutAccessedKeys=nullptr)
Imports property values from an .ini file.
virtual void LoadedFromAnotherClass (const FName &OldClassName)
Called when the object was loaded from another class via active class redirects.
virtual void MarkAsEditorOnlySubobject ()
Called during subobject creation to mark this component as editor only, which causes it to get stripped in packaged builds.
virtual void MoveDataToSparseClassDataStruct () const
virtual bool NeedsLoadForClient () const
Called during saving to determine the load flags to save with the object.
virtual bool NeedsLoadForEditorGame () const
Called during saving to include this object in client/servers running in editor builds, even if they wouldn't normally be.
virtual bool NeedsLoadForServer () const
Called during saving to determine the load flags to save with the object.
virtual bool NeedsLoadForTargetPlatform (const class ITargetPlatform *TargetPlatform) const
Called during saving to determine the load flags to save with the object.
virtual void OnCookEvent (UE::Cook::ECookEvent CookEvent, UE::Cook::FCookEventContext &Context)
Called during cooking for various events that happen on each UObject in a package during load/transform/save.
void OutputReferencers (FOutputDevice &Ar, FReferencerInformationList *Referencers=NULL)
Outputs a string to an arbitrary output device, describing the list of objects which are holding references to this one.
virtual void OverrideConfigSection (FString &SectionName)
Allows Non-PerObjectConfig classes, to override the ini section name used for loading config settings.
virtual void OverridePerObjectConfigSection (FString &SectionName)
Allows PerObjectConfig classes, to override the ini section name used for the PerObjectConfig object.
void ParseParms (const TCHAR *Parms)
Import an object from a file.
virtual void PostCDOCompiled (const FPostCDOCompiledContext &Context)
Called after the Blueprint compiler has finished generating the Class Default Object (CDO) for a class.
virtual void PostCDOContruct ()
Called after the C++ constructor has run on the Class Default Object (CDO) for a class.
virtual void PostDuplicate (bool bDuplicateForPIE)
Called after duplication & serialization and before PostLoad.
virtual void PostDuplicate (EDuplicateMode::Type DuplicateMode)
void PostEditChange ()
Intentionally non-virtual as it calls the FPropertyChangedEvent version.
virtual void PostEditChangeChainProperty (struct FPropertyChangedChainEvent &PropertyChangedEvent)
This alternate version of PostEditChange is called when properties inside structs are modified.
virtual void PostEditImport ()
Called after importing property values for this object (paste, duplicate or .t3d import) Allow the object to perform any cleanup for properties which shouldn't be duplicated or are unsupported by the script serialization.
virtual void PostEditUndo ()
Called after applying a transaction to the object.
virtual void PostEditUndo (TSharedPtr< ITransactionObjectAnnotation > TransactionAnnotation)
Called after applying a transaction to the object in cases where transaction annotation was provided.
virtual void PostInitProperties ()
Called after the C++ constructor and after the properties have been initialized, including those loaded from config.
virtual void PostLinkerChange ()
Called in response to the linker changing, this can only happen in the editor.
virtual void PostLoadSubobjects (FObjectInstancingGraph *OuterInstanceGraph)
Instances components for objects being loaded from disk, if necessary.
virtual void PostNetReceive ()
Called right after receiving a bunch.
virtual void PostReinitProperties ()
Called after properties are overwritten, including after subobjects initialization from a CDO.
virtual void PostReloadConfig (class FProperty *PropertyThatWasLoaded)
Called from ReloadConfig after the object has reloaded its configuration data.
virtual void PostRename (UObject *OldOuter, const FName OldName)
Called at the end of Rename(), but only if the rename was actually carried out.
virtual void PostRepNotifies ()
Called right after calling all OnRep notifies (called even when there are no notifies)
virtual void PostSaveRoot (FObjectPostSaveRootContext ObjectSaveContext)
Called from within SavePackage on the passed in base/root object.
virtual void PostTransacted (const FTransactionObjectEvent &TransactionEvent)
Called after the object has been transacted in some way.
virtual void PreDestroyFromReplication ()
Called right before being marked for destruction due to network replication.
virtual void PreDuplicate (FObjectDuplicationParameters &DupParams)
Called before duplication.
virtual void PreEditChange (class FEditPropertyChain &PropertyAboutToChange)
This alternate version of PreEditChange is called when properties inside structs are modified.
virtual void PreEditChange (FProperty *PropertyAboutToChange)
This is called when a property is about to be modified externally.
virtual void PreEditUndo ()
Called before applying a transaction to the object.
virtual void PreNetReceive ()
Called right before receiving a bunch.
virtual void PreSave (FObjectPreSaveContext SaveContext)
Presave function.
virtual void PreSaveRoot (FObjectPreSaveRootContext ObjectSaveContext)
Called from within SavePackage on the passed in base/root object.
virtual bool ProcessConsoleExec (const TCHAR *Cmd, FOutputDevice &Ar, UObject *Executor)
This function handles a console exec sent to the object; it is virtual so 'nexus' objects like a player controller can reroute the command to several different objects.
virtual void ProcessEvent (UFunction *Function, void *Parms)
Called by VM to execute a UFunction with a filled in UStruct of parameters.
void PropagatePostEditChange (TArray< UObject * > &AffectedObjects, FPropertyChangedChainEvent &PropertyChangedEvent)
Calls PostEditChange on all instances based on an archetype in AffectedObjects.
void PropagatePreEditChange (TArray< UObject * > &AffectedObjects, FEditPropertyChain &PropertyAboutToChange)
Calls PreEditChange on all instances based on an archetype in AffectedObjects.
virtual UClass * RegenerateClass (UClass *ClassToRegenerate, UObject *PreviousCDO)
Called on the target when a class is loaded with ClassGeneratedBy is loaded.
void ReinitializeProperties (UObject *SourceObject=NULL, struct FObjectInstancingGraph *InstanceGraph=NULL)
Wrapper function for InitProperties() which handles safely tearing down this object before re-initializing it from the specified source object.
void ReloadConfig (UClass *ConfigClass=NULL, const TCHAR *Filename=NULL, uint32 PropagationFlags=UE::LCPF_None, class FProperty *PropertyToLoad=NULL)
Wrapper method for LoadConfig that is used when reloading the config data for objects at runtime which have already loaded their config data at least once.
virtual bool Rename (const TCHAR *NewName=nullptr, UObject *NewOuter=nullptr, ERenameFlags Flags=REN_None)
Rename this object to a unique name, or change its outer.
virtual bool ResolveSubobject (const TCHAR *SubObjectPath, UObject *&OutObject, bool bLoadIfExists)
Called to defer loading a subobject to its top-level container object.
void RetrieveReferencers (TArray< FReferencerInformation > *OutInternalReferencers, TArray< FReferencerInformation > *OutExternalReferencers)
Called by OutputReferencers() to get the internal list of referencers to write.
void SaveConfig (uint64 RequiredPropertyFlags=CPF_Config, const TCHAR *Filename=nullptr, FConfigCacheIni *Config=GConfig, bool bAllowCopyToDefaultObject=true)
Save configuration out to ini files.
virtual void Serialize (FStructuredArchive::FRecord Record)
void SerializeScriptProperties (FArchive &Ar) const
Serializes the script property data located at Data.
void SerializeScriptProperties (FStructuredArchive::FSlot Slot) const
Serializes the script property data located at Data.
void SetEditChangePropagationFlags (EEditChangePropagationFlags InFlags)
Called to set the flags that control how editor change events get propagated to archetype instances.
void SetLinker (FLinkerLoad *LinkerLoad, int32 LinkerIndex, bool bShouldDetachExisting=true)
Changes the linker and linker index to the passed in one.
virtual void ShutdownAfterError ()
After a critical error, perform any mission-critical cleanup, such as restoring the video mode orreleasing hardware resources.
void SkipFunction (FFrame &Stack, RESULT_DECL, UFunction *Function)
advances Stack's code past the parameters to the given Function and if the function has a return value, copies the zero value for that property to the memory for the return value
virtual void TagSubobjects (EObjectFlags NewFlags)
Tags objects that are part of the same asset with the specified object flag, used for GC checking.
void ThreadedPostLoadAssetRegistryTags (FPostLoadAssetRegistryTagsContext &Context) const
Internal use function for the AssetRegistry.
bool TryUpdateDefaultConfigFile (const FString &SpecificFileLocation="", bool bWarnIfFail=true)
Try to Saves just the section(s) for this class into the default ini file for the class (with just the changes from base)
UE_DEPRECATED (5.0, "TryUpdateDefaultConfigFile replaces UpdateDefaultConfigFile") 1 void UpdateDefaultConfigFile(const FString &SpecificFileLocation
Saves just the section(s) for this class into the default ini file for the class (with just the changes from base)
UE_DEPRECATED (5.1, "Use version that takes FPostCDOCompiledContext instead.") virtual void PostCDOCompiled()
Called after the Blueprint compiler has finished generating the Class Default Object (CDO) for a class.
UE_DEPRECATED (5.3, "Matinee has been removed in 5.0, nothing is calling PostInterpChange anymore") virtual void PostInterpChange(FProperty *PropertyThatChanged)
UE_DEPRECATED (5.3, "Please use IsDataValid(FDataValidationContext&) const as the FDataValidationContext will allow distinguishing between Warnings and Errors.") 1 virtual EDataValidationResult IsDataValid(TArray< FText > &ValidationErrors)
Generic function to validate objects during changelist validations, etc.
UE_DEPRECATED (5.3, "Please use the the const version of IsDataValid(FDataValidationContext&)") 1 virtual EDataValidationResult IsDataValid(class FDataValidationContext &Context)
UE_DEPRECATED (5.4, "Call GetDefaultSubobjects for top level subobjects or use ForEachObjectWithOuter with a more precise check") 1 void CollectDefaultSubobjects(TArray< UObject * > &OutDefaultSubobjects
Gets all subobjects inside this object that return true for IsDefaultSubobject.
UE_DEPRECATED (5.4, "Implement the version that takes FAssetRegistryTagsContext instead.") 1 virtual void GetAssetRegistryTags(TArray< FAssetRegistryTag > &OutTags) const
UE_DEPRECATED (5.5, "Multithreaded destruction of UObjects is no longer supported.") 1 virtual bool IsDestructionThreadSafe() const
Called during garbage collection to determine if an object can have its destructor called on a worker thread.
UE_DEPRECATED (5.5, "This function is no longer called. If you require this functionality, please implement ThreadedPostLoadAssetRegistryTagsOverride. \ Note that this function MUST be safe to call on a background thread. If you have functionality that doesn't meet that requirement, \ consider using the AssetRegistry's AssetAddedEvent which fires on the game thread.") virtual void PostLoadAssetRegistryTags(const FAssetData &InAssetData
void UpdateGlobalUserConfigFile ()
Saves just the section(s) for this class into the global user ini file for the class (with just the changes from base)
void UpdateProjectUserConfigFile ()
Saves just the section(s) for this class into the project user ini file for the class (with just the changes from base)
void UpdateSinglePropertyInConfigFile (const FProperty *InProperty, const FString &InConfigIniName)
Saves just the property into the global user ini file for the class (with just the changes from base)
virtual void ValidateGeneratedRepEnums (const TArray< struct FRepRecord > &ClassReps) const
virtual void WillNeverCacheCookedPlatformDataAgain ()
All caching has finished for this object (all IsCachedCookedPlatformDataLoaded functions have finished for all platforms)
Public Member Functions inherited from UObjectBaseUtility
UObjectBaseUtility ()
UObjectBaseUtility (EObjectFlags InFlags)
void AddToCluster (UObjectBaseUtility *ClusterRootOrObjectFromCluster, bool bAddAsMutableObject=false)
Adds this objects to a GC cluster that already exists.
FORCEINLINE void AddToRoot ()
Add an object to the root set.
FORCEINLINE void AppendName (FString &ResultString) const
Optimized version of GetName that appends to an existing string.
FORCEINLINE bool AtomicallyClearInternalFlags (EInternalObjectFlags FlagsToClear) const
Atomically clears passed in internal flags.
virtual bool CanBeClusterRoot () const
Called after load to determine if the object can be a cluster root.
virtual bool CanBeInCluster () const
Called during cluster construction if the object can be added to a cluster.
FORCEINLINE void ClearFlags (EObjectFlags FlagsToClear)
Clears subset of flags for a specific object.
FORCEINLINE void ClearGarbage ()
Unmarks this object as Garbage.
FORCEINLINE void ClearInternalFlags (EInternalObjectFlags FlagsToClear) const
Clears passed in internal flags.
virtual void CreateCluster ()
Called after PostLoad to create UObject cluster.
void DetachExternalPackage ()
Utility function to temporarily detach the object external package, if any GetPackage will report the outer's package once detached.
const UClass * FindNearestCommonBaseClass (const UClass *TestClass) const
Finds the most-derived class which is a parent of both TestClass and this object's class.
FORCEINLINE EObjectMark GetAllMarks () const
Returns all of the object marks on a specific object.
FString GetFullGroupName (bool bStartWithOuter) const
Walks up the chain of packages until it reaches the top level, which it ignores.
void GetFullName (const UObject *StopOuter, FString &ResultString, EObjectFullNameFlags Flags=EObjectFullNameFlags::None) const
Version of GetFullName() that eliminates unnecessary copies.
FString GetFullName (const UObject *StopOuter=NULL, EObjectFullNameFlags Flags=EObjectFullNameFlags::None) const
Returns the fully qualified pathname for this object as well as the name of the class, in the format: 'ClassName Outermost[.Outer].Name'.
void GetFullName (FStringBuilderBase &ResultString, const UObject *StopOuter=NULL, EObjectFullNameFlags Flags=EObjectFullNameFlags::None) const
Returns the fully qualified pathname for this object as well as the name of the class, in the format: 'ClassName Outermost[.Outer].Name'.
template<typename InterfaceClassType>
InterfaceClassType * GetImplementingOuter () const
Traverses the outer chain looking for the next object that implements the specified IInterface (InterfaceClass must be an IInterface)
UObjectBaseUtility * GetImplementingOuterObject (const UClass *InInterfaceClass) const
Traverses the outer chain looking for the next object that implements the specified UInterface (InInterfaceClass must be a subclass of UInterface)
void * GetInterfaceAddress (UClass *InterfaceClass)
Returns a pointer to this object safely converted to a pointer of the specified interface class.
FORCEINLINE EInternalObjectFlags GetInternalFlags () const
Gets internal flags.
class FLinkerLoad * GetLinker () const
Returns the linker for this object.
int32 GetLinkerCustomVersion (FGuid CustomVersionKey) const
Returns the custom version of the linker for this object corresponding to the given custom version key.
int32 GetLinkerIndex () const
Returns this object's LinkerIndex.
int32 GetLinkerLicenseeUEVersion () const
Returns the licensee version of the linker for this object.
FPackageFileVersion GetLinkerUEVersion () const
Returns the UE version of the linker for this object.
FORCEINLINE EObjectFlags GetMaskedFlags (EObjectFlags Mask=RF_AllFlags) const
Returns object flags that are both in the mask and set on the object.
FORCEINLINE FString GetName () const
Returns the name of this object (with no path information)
FORCEINLINE void GetName (FString &ResultString) const
Optimized version of GetName that overwrites an existing string.
void * GetNativeInterfaceAddress (UClass *InterfaceClass)
Returns a pointer to the I* native interface object that this object implements.
const void * GetNativeInterfaceAddress (UClass *InterfaceClass) const
Returns a pointer to the const I* native interface object that this object implements.
UPackage * GetOutermost () const
Legacy function, has the same behavior as GetPackage use GetPackage instead.
UObject * GetOutermostObject () const
Walks up the list of outers until it finds the top-level one that isn't a package.
UPackage * GetPackage () const
Walks up the list of outers until it finds a package directly associated with the object.
void GetPathName (const UObject *StopOuter, FString &ResultString) const
Versions of GetPathName() that eliminates unnecessary copies and allocations.
void GetPathName (const UObject *StopOuter, FStringBuilderBase &ResultString) const
FString GetPathName (const UObject *StopOuter=NULL) const
Returns the fully qualified pathname for this object, in the format: 'Outermost[.Outer].Name'.
FORCEINLINE TStatId GetStatID (bool bForDeferredUse=false) const
Returns the stat ID of the object, used for profiling.
template<typename T>
T * GetTypedOuter () const
Traverses the outer chain searching for the next object of a certain type.
UObject * GetTypedOuter (UClass *Target) const
Traverses the outer chain searching for the next object of a certain type.
virtual UE_INTERNAL UE::Core::FVersePath GetVersePath () const
Gets the versepath of the UObject.
FORCEINLINE bool HasAllFlags (EObjectFlags FlagsToCheck) const
Used to safely check whether all of the passed in flags are set.
FORCEINLINE bool HasAllMarks (EObjectMark Marks) const
Tests an object for having ALL of a set of marks.
FORCEINLINE bool HasAnyFlags (EObjectFlags FlagsToCheck) const
Used to safely check whether any of the passed in flags are set.
FORCEINLINE bool HasAnyInternalFlags (EInternalObjectFlags FlagsToCheck) const
Used to safely check whether any of the passed in internal flags are set.
FORCEINLINE bool HasAnyMarks (EObjectMark Marks) const
Tests an object for having ANY of a set of marks.
template<class T>
bool IsA () const
Returns true if this object is of the template type.
template<typename OtherClassType>
FORCEINLINE bool IsA (OtherClassType SomeBase) const
Returns true if this object is of the specified type.
bool IsDefaultSubobject () const
Returns whether this is a subobject (template or instance) that was originally defined inside a default class object.
bool IsIn (const UObject *SomeOuter) const
Return the dispatch to IsInOuter or IsInPackage depending on SomeOuter's class.
bool IsIn (const UPackage *SomePackage) const
Overload to determine if an object is in the specified package which can now be different than its outer chain.
bool IsInA (const UClass *SomeBaseClass) const
Find out if this object is inside (has an outer) that is of the specified class.
bool IsInOuter (const UObject *SomeOuter) const
Returns true if the object is contained in the specified outer.
bool IsInPackage (const UPackage *SomePackage) const
Returns true if the object is contained in the specified package.
FORCEINLINE bool IsNative () const
Checks if the object is native.
bool IsPackageExternal () const
Get the object packaging mode.
FORCEINLINE bool IsRooted () const
Returns true if this object is explicitly rooted.
bool IsTemplate (EObjectFlags TemplateTypes=RF_ArchetypeObject|RF_ClassDefaultObject) const
Determines whether this object is a template object by checking flags on the object and the outer chain.
bool IsTemplateForSubobjects (EObjectFlags TemplateTypes=RF_ClassDefaultObject|RF_DefaultSubObject|RF_InheritableComponentTemplate) const
Returns whether this is a template that can be used to create instanced subobjects.
FORCEINLINE bool IsUnreachable () const
Checks if the object is unreachable.
FORCEINLINE void Mark (EObjectMark Marks) const
Adds marks to an object.
FORCEINLINE void MarkAsGarbage ()
Marks this object as Garbage.
bool MarkPackageDirty () const
Finds the outermost package and marks it dirty.
virtual void OnClusterMarkedAsPendingKill ()
Called during Garbage Collection to perform additional cleanup when the cluster is about to be destroyed due to PendingKill flag being set on it.
FORCEINLINE bool operator< (const UObjectBaseUtility &Other) const
Overloaded < operator.
void ReattachExternalPackage ()
Utility function to reattach the object external package, if any GetPackage will report the object external package if set after this call.
FORCEINLINE void RemoveFromRoot ()
Remove an object from the root set.
bool RootPackageHasAnyFlags (uint32 CheckFlagMask) const
Checks whether this object's top-most package has any of the specified flags.
FORCEINLINE void SetFlags (EObjectFlags NewFlags)
Modifies object flags for a specific object.
FORCEINLINE void SetInternalFlags (EInternalObjectFlags FlagsToSet) const
Clears passed in internal flags.
UE_DEPRECATED (5.0, "Use GetLinkerLicenseeUEVersion instead") inline int32 GetLinkerLicenseeUE4Version() const
UE_DEPRECATED (5.0, "Use GetLinkerUEVersion instead which returns the version as a FPackageFileVersion. See the @FPackageFileVersion documentation for further details") inline int32 GetLinkerUE4Version() const
UE_DEPRECATED (5.4, "Use IsGarbageEliminationEnabled()") static inline bool IsPendingKillEnabled()
UE_DEPRECATED (5.5, "ThisThreadAtomicallyClearedRFUnreachable() should no longer be used. Reachability flags can only be modified by the garbage collector.") bool ThisThreadAtomicallyClearedRFUnreachable()
Atomically clear the unreachable flag.
FORCEINLINE void UnMark (EObjectMark Marks) const
Removes marks from and object.
Public Member Functions inherited from UObjectBase
UObjectBase (UClass *InClass, EObjectFlags InFlags, EInternalObjectFlags InInternalFlags, UObject *InOuter, FName InName, int32 InInternalIndex=-1, int32 InSerialNumber=0, FRemoteObjectId InRemoteId=FRemoteObjectId())
Constructor used by StaticAllocateObject.
virtual ~UObjectBase ()
Final destructor, removes the object from the object array, and indirectly, from any annotations.
void AddRef () const
Increments ref-count on the object.
FORCENOINLINE void AtomicallyClearFlags (EObjectFlags FlagsToClear)
Atomically clears the specified flags.
FORCENOINLINE void AtomicallySetFlags (EObjectFlags FlagsToAdd)
Atomically adds the specified flags.
FORCEINLINE UClass * GetClass () const
Returns the UClass that defines the fields of this object.
UPackage * GetExternalPackage () const
Returns the external UPackage associated with this object, if any.
UPackage * GetExternalPackageInternal () const
Returns the external UPackage for this object, if any, NOT THREAD SAFE, used by internal gc reference collecting.
FORCEINLINE EObjectFlags GetFlags () const
Retrieve the object flags directly.
FORCEINLINE FName GetFName () const
Returns the logical name of this object.
virtual FName GetFNameForStatID () const
Overridable method to return a logical name for identification in stats.
FORCEINLINE UObject * GetOuter () const
Returns the UObject this object resides in.
FORCEINLINE uint32 GetUniqueID () const
Returns the unique ID of the object...these are reused so it is only unique while the object is alive.
bool IsValidLowLevel () const
Checks to see if the object appears to be valid.
bool IsValidLowLevelFast (bool bRecursive=true) const
Faster version of IsValidLowLevel.
void MarkAsReachable () const
Marks the object as Reachable if it's currently marked as MaybeUnreachable by incremental GC.
void ReleaseRef () const
Release ref-count on the object.
void SetExternalPackage (UPackage *InPackage)
Associate an external package directly to this object.
Static Public Member Functions
static HAIRSTRANDSCORE_API FName GetAutoLODBiasMemberName ()
static HAIRSTRANDSCORE_API FName GetDataflowSettingsMemberName ()
Static member to retrieve the member name.
static HAIRSTRANDSCORE_API FName GetDeformedGroupSectionsMemberName ()
static HAIRSTRANDSCORE_API FName GetDisableBelowMinLodStrippingMemberName ()
static HAIRSTRANDSCORE_API FName GetEffectiveLODBiasMemberName ()
static HAIRSTRANDSCORE_API FName GetEnableGlobalInterpolationMemberName ()
static HAIRSTRANDSCORE_API FName GetEnableSimulationCacheMemberName ()
static HAIRSTRANDSCORE_API FName GetHairGroupsCardsMemberName ()
static HAIRSTRANDSCORE_API FName GetHairGroupsInfoMemberName ()
static HAIRSTRANDSCORE_API FName GetHairGroupsInterpolationMemberName ()
static HAIRSTRANDSCORE_API FName GetHairGroupsLODMemberName ()
static HAIRSTRANDSCORE_API FName GetHairGroupsMaterialsMemberName ()
static HAIRSTRANDSCORE_API FName GetHairGroupsMeshesMemberName ()
static HAIRSTRANDSCORE_API FName GetHairGroupsPhysicsMemberName ()
static HAIRSTRANDSCORE_API FName GetHairGroupsPlatformDataMemberName ()
static HAIRSTRANDSCORE_API FName GetHairGroupsRenderingMemberName ()
static HAIRSTRANDSCORE_API FName GetHairInterpolationTypeMemberName ()
static HAIRSTRANDSCORE_API FName GetLODModeMemberName ()
static HAIRSTRANDSCORE_API FName GetMinLODMemberName ()
static HAIRSTRANDSCORE_API FName GetRiggedSkeletalMeshMemberName ()
Static Public Member Functions inherited from UObject
static void AddReferencedObjects (UObject *InThis, FReferenceCollector &Collector)
Callback used to allow object register its direct object references that are not already covered by the token stream.
static bool CanCreateInCurrentContext (UObject *Template)
Determines if you can create an object from the supplied template in the current context (editor, client only, dedicated server, game/listen) This calls NeedsLoadForClient & NeedsLoadForServer.
static UObject * GetArchetypeFromRequiredInfo (const UClass *Class, const UObject *Outer, FName Name, EObjectFlags ObjectFlags)
Return the template that an object with this class, outer and name would be.
static TSet< FName > & GetMetaDataTagsForAssetRegistry ()
The metadata tags to be transferred from the FMetaData to the Asset Registry.
static const FName & SourceFileTagName ()
Get the common tag name used for all asset source file import paths.
static void UpdateClassesExcludedFromDedicatedClient (const TArray< FString > &InClassNames, const TArray< FString > &InModulesNames)
Update the list of classes that we should exclude from dedicated client builds.
static void UpdateClassesExcludedFromDedicatedServer (const TArray< FString > &InClassNames, const TArray< FString > &InModulesNames)
Update the list of classes that we should exclude from dedicated server builds.
Static Public Member Functions inherited from UObjectBaseUtility
static bool IsGarbageEliminationEnabled ()
Helper function to access the private bGarbageEliminationEnabled variable.
static void ReloadObjectsFromModifiedConfigSections (const class FConfigModificationTracker *ChangeTracker)
static void SetGarbageEliminationEnabled (bool bEnabled)
Helper function to set the private bGarbageEliminationEnabled variable.
Static Public Member Functions inherited from UObjectBase
static void PrefetchClass (UObject *Object)
static void PrefetchOuter (UObject *Object)
static FString RemoveClassPrefix (const TCHAR *ClassName)
Removes the class prefix from the given string.
Data Fields
DisplayName
FOnGroomAssetChanged OnGroomAssetChanged
FOnGroomAssetResourcesChanged OnGroomAssetResourcesChanged
FOnGroomAsyncLoadFinished OnGroomAsyncLoadFinished
Data Fields inherited from UObject
bool bIncludeNestedSubobjects =false) const
TArray< FAssetRegistryTag > &OutTagsAndValuesToUpdate const final
Private Member Functions
FHairStrandsRestResource * AllocateGuidesResources (uint32 GroupIndex)
FHairStrandsInterpolationResource * AllocateInterpolationResources (uint32 GroupIndex)
void ApplyStripFlags (uint8 StripFlags, const class ITargetPlatform *CookTarget)
DECLARE_MULTICAST_DELEGATE (FOnGroomAssetResourcesChanged)
DECLARE_MULTICAST_DELEGATE (FOnGroomAsyncLoadFinished)
GENERATED_UCLASS_BODY () DECLARE_MULTICAST_DELEGATE(FOnGroomAssetChanged)
Notification when anything changed.
void SavePendingProceduralAssets ()
void UpdatePhysicsSystems ()
Update the physics system based on the solver settings enum.
UPROPERTY () FGroomDataflowSettings DataflowSettings
Dataflow settings used for any dataflow related operations.
UPROPERTY ()) EGroomLODMode LODMode
UPROPERTY ()) float AutoLODBias=0
Private Attributes
uint32 AssetNameHash = 0
TQueue< UStaticMesh * > AssetToSave_Meshes
TQueue< FHairGroupCardsTextures * > AssetToSave_Textures
bool bIsInitialized = false
TArray< FHairGroupsCardsSourceDescription > CachedHairGroupsCards
TArray< FHairGroupsInterpolation > CachedHairGroupsInterpolation
TArray< FHairGroupsLOD > CachedHairGroupsLOD
TArray< FHairGroupsMeshesSourceDescription > CachedHairGroupsMeshes
TArray< FHairGroupsPhysics > CachedHairGroupsPhysics
TArray< FHairGroupsRendering > CachedHairGroupsRendering
ERHIFeatureLevel::Type CachedResourcesFeatureLevel = ERHIFeatureLevel::Num
ERHIFeatureLevel::Type CachedResourcesPlatformLevel = ERHIFeatureLevel::Num
TArray< FHairGroupResources > HairGroupsResources
Store strands/cards/meshes resources.
Friends
class UGroomComponent
Additional Inherited Members
Static Public Attributes inherited from UObject
static FOnGetPreviewPlatform OnGetPreviewPlatform
Protected Types inherited from UObject
enum class ETransactionAnnotationCreationMode : uint8 { DefaultInstance , FindOrCreate }
Factory a new annotation object and optionally populate it with data.
Protected Member Functions inherited from UObject
bool CanCheckDefaultSubObjects (bool bForceCheck, bool &bResult) const
Checks it's ok to perform subobjects check at this time.
virtual bool CheckDefaultSubobjectsInternal () const
Checks default sub-object assumptions.
virtual TSharedPtr< ITransactionObjectAnnotation > FactoryTransactionAnnotation (const ETransactionAnnotationCreationMode InCreationMode) const
virtual FString GetDetailedInfoInternal () const
This function actually does the work for the GetDetailedInfo() and is virtual.
virtual bool IsSelectedInEditor () const
Test the selection state of a UObject.
virtual void ThreadedPostLoadAssetRegistryTagsOverride (FPostLoadAssetRegistryTagsContext &Context) const
Performs fixup on loaded asset registry data.
Protected Member Functions inherited from UObjectBase
UObjectBase ()
UObjectBase (EObjectFlags InFlags)
Constructor used for bootstrapping.
virtual void DeferredRegister (UClass *UClassStaticClass, const TCHAR *PackageName, const TCHAR *Name)
Convert a boot-strap registered class into a real one, add to uobject array, etc.
void LowLevelRename (FName NewName, UObject *NewOuter=NULL)
Just change the FName and Outer and rehash into name hash tables.
void Register (class UClass *(*StaticClassFn)(), const TCHAR *PackageName, const TCHAR *Name)
Enqueue the registration for this object.
virtual void RegisterDependencies ()
Force any base classes to be registered first.
UE_DEPRECATED (5.3, "This function is not thread-safe. Use AtomicallySetFlags or AtomicallyClearFlags instead.") FORCEINLINE void SetFlagsTo(EObjectFlags NewFlags)
Set the object flags directly.
UE_DEPRECATED (5.6, "Use the new method above and specify UClass::StaticClass as the first argument") 1 void Register(const TCHAR *PackageName
Protected Attributes inherited from UObjectBase
const TCHAR * Name
Detailed Description
Definition at line 458 of file GroomAsset.h.
Member Enumeration Documentation
EClassDataStripFlag
enum UGroomAsset::EClassDataStripFlag : uint8
Enumerator
CDSF_ImportedStrands
CDSF_MinLodData
CDSF_StrandsStripped
CDSF_CardsStripped
CDSF_MeshesStripped
Definition at line 809 of file GroomAsset.h.
Member Function Documentation
AddAssetUserData()
virtual HAIRSTRANDSCORE_API void UGroomAsset::AddAssetUserData (UAssetUserData * InUserData) override virtual
References UE_API.
AllocateGuidesResources()
FHairStrandsRestResource * UGroomAsset::AllocateGuidesResources (uint32 GroupIndex) private
AllocateInterpolationResources()
FHairStrandsInterpolationResource * UGroomAsset::AllocateInterpolationResources (uint32 GroupIndex) private
ApplyStripFlags()
void UGroomAsset::ApplyStripFlags (uint8 StripFlags, const class ITargetPlatform * CookTarget) private
AreGroupsValid()
HAIRSTRANDSCORE_API bool UGroomAsset::AreGroupsValid () const
References UE_API.
BeginDestroy()
virtual HAIRSTRANDSCORE_API void UGroomAsset::BeginDestroy () override virtual
Called before destroying the object.
This is called immediately upon deciding to destroy the object, to allow the object to begin an asynchronous cleanup process.
Reimplemented from UObject.
References UE_API.
BuildCardsData()
HAIRSTRANDSCORE_API bool UGroomAsset::BuildCardsData ()
References UE_API.
BuildMeshesData()
HAIRSTRANDSCORE_API bool UGroomAsset::BuildMeshesData ()
References UE_API.
CanRebuildFromDescription()
HAIRSTRANDSCORE_API bool UGroomAsset::CanRebuildFromDescription () const
Returns true if the asset has the HairDescription needed to recompute its groom data.
References UE_API.
ChangeFeatureLevel()
HAIRSTRANDSCORE_API void UGroomAsset::ChangeFeatureLevel (ERHIFeatureLevel::Type PendingFeatureLevel)
References UE_API.
ChangePlatformLevel()
HAIRSTRANDSCORE_API void UGroomAsset::ChangePlatformLevel (ERHIFeatureLevel::Type PendingFeatureLevel)
References UE_API.
ClearNumGroup()
HAIRSTRANDSCORE_API void UGroomAsset::ClearNumGroup (uint32 InGroupCount)
References UE_API.
CollectVertexFactoryTypesPerMaterialData()
HAIRSTRANDSCORE_API TArray< FHairVertexFactoryTypesPerMaterialData > UGroomAsset::CollectVertexFactoryTypesPerMaterialData (EShaderPlatform ShaderPlatform)
Used for PSO precaching of used materials and vertex factories.
References ShaderPlatform, and UE_API.
CreateDataflowContent()
virtual HAIRSTRANDSCORE_API TObjectPtr< UDataflowBaseContent > UGroomAsset::CreateDataflowContent () override virtual
References UE_API.
CreateDebugData()
HAIRSTRANDSCORE_API void UGroomAsset::CreateDebugData ()
References UE_API.
DECLARE_MULTICAST_DELEGATE() [1/2]
UGroomAsset::DECLARE_MULTICAST_DELEGATE (FOnGroomAssetResourcesChanged) private
DECLARE_MULTICAST_DELEGATE() [2/2]
UGroomAsset::DECLARE_MULTICAST_DELEGATE (FOnGroomAsyncLoadFinished) private
GenerateClassStripFlags()
HAIRSTRANDSCORE_API uint8 UGroomAsset::GenerateClassStripFlags (FArchive & Ar)
References Ar, and UE_API.
GENERATED_UCLASS_BODY()
UGroomAsset::GENERATED_UCLASS_BODY () private
Notification when anything changed.
GetAssetHash()
uint32 UGroomAsset::GetAssetHash () const inline
Definition at line 781 of file GroomAsset.h.
References AssetNameHash.
GetAssetPathName()
HAIRSTRANDSCORE_API FName UGroomAsset::GetAssetPathName (int32 LODIndex = -1)
Helper function to return the asset path name, optionally joined with the LOD index if LODIndex > -1.
References UE_API.
GetAssetUserDataArray()
virtual HAIRSTRANDSCORE_API const TArray< UAssetUserData * > * UGroomAsset::GetAssetUserDataArray () const override virtual
Reimplemented from IInterface_AssetUserData.
References UE_API.
GetAssetUserDataOfClass()
virtual HAIRSTRANDSCORE_API UAssetUserData * UGroomAsset::GetAssetUserDataOfClass (TSubclassOf< UAssetUserData > InUserDataClass) override virtual
References UE_API.
GetAutoLODBias() [1/2]
HAIRSTRANDSCORE_API float UGroomAsset::GetAutoLODBias () const
References UE_API.
GetAutoLODBias() [2/2]
HAIRSTRANDSCORE_API float UGroomAsset::GetAutoLODBias (int32 InGroupIndex) const
References UE_API.
GetAutoLODBiasMemberName()
HAIRSTRANDSCORE_API FName UGroomAsset::GetAutoLODBiasMemberName () static
References UE_API.
GetBindingType()
HAIRSTRANDSCORE_API EGroomBindingType UGroomAsset::GetBindingType (int32 GroupIndex, int32 LODIndex) const
References UE_API.
GetDataflowSettings() [1/2]
FGroomDataflowSettings & UGroomAsset::GetDataflowSettings () inline
Return the Dataflow settings associated to this groom asset if any.
Definition at line 573 of file GroomAsset.h.
GetDataflowSettings() [2/2]
const FGroomDataflowSettings & UGroomAsset::GetDataflowSettings () const inline
Return the Dataflow settings associated to this groom asset if any, const version.
Definition at line 570 of file GroomAsset.h.
References GetDataflowSettings().
Referenced by GetDataflowSettings().
GetDataflowSettingsMemberName()
HAIRSTRANDSCORE_API FName UGroomAsset::GetDataflowSettingsMemberName () static
Static member to retrieve the member name.
References GetDataflowSettingsMemberName(), and UE_API.
Referenced by GetDataflowSettingsMemberName().
GetDeformedGroupSections()
HAIRSTRANDSCORE_API const TArray< int32 > & UGroomAsset::GetDeformedGroupSections () const
References UE_API.
Referenced by UFUNCTION().
GetDeformedGroupSectionsMemberName()
HAIRSTRANDSCORE_API FName UGroomAsset::GetDeformedGroupSectionsMemberName () static
References UE_API.
GetDisableBelowMinLodStripping()
HAIRSTRANDSCORE_API FPerPlatformBool UGroomAsset::GetDisableBelowMinLodStripping () const
References UE_API.
GetDisableBelowMinLodStrippingMemberName()
HAIRSTRANDSCORE_API FName UGroomAsset::GetDisableBelowMinLodStrippingMemberName () static
References UE_API.
GetEffectiveLODBias() [1/2]
HAIRSTRANDSCORE_API TArray< float > & UGroomAsset::GetEffectiveLODBias ()
References UE_API.
GetEffectiveLODBias() [2/2]
HAIRSTRANDSCORE_API const TArray< float > & UGroomAsset::GetEffectiveLODBias () const
References UE_API.
GetEffectiveLODBiasMemberName()
HAIRSTRANDSCORE_API FName UGroomAsset::GetEffectiveLODBiasMemberName () static
References UE_API.
GetEnableGlobalInterpolationMemberName()
HAIRSTRANDSCORE_API FName UGroomAsset::GetEnableGlobalInterpolationMemberName () static
References UE_API.
GetEnableSimulationCacheMemberName()
HAIRSTRANDSCORE_API FName UGroomAsset::GetEnableSimulationCacheMemberName () static
References UE_API.
GetGeometryType()
HAIRSTRANDSCORE_API EGroomGeometryType UGroomAsset::GetGeometryType (int32 GroupIndex, int32 LODIndex) const
References UE_API.
GetGuideType()
EGroomGuideType UGroomAsset::GetGuideType (int32 GroupIndex) const
GetHairGroupsCards()
HAIRSTRANDSCORE_API const TArray< FHairGroupsCardsSourceDescription > & UGroomAsset::GetHairGroupsCards () const
References UE_API.
Referenced by UE_DEPRECATED(), and UFUNCTION().
GetHairGroupsCardsMemberName()
HAIRSTRANDSCORE_API FName UGroomAsset::GetHairGroupsCardsMemberName () static
References UE_API.
GetHairGroupsInfo() [1/2]
HAIRSTRANDSCORE_API TArray< FHairGroupInfoWithVisibility > & UGroomAsset::GetHairGroupsInfo ()
References UE_API.
GetHairGroupsInfo() [2/2]
HAIRSTRANDSCORE_API const TArray< FHairGroupInfoWithVisibility > & UGroomAsset::GetHairGroupsInfo () const
References UE_API.
GetHairGroupsInfoMemberName()
HAIRSTRANDSCORE_API FName UGroomAsset::GetHairGroupsInfoMemberName () static
References UE_API.
GetHairGroupsInterpolation()
HAIRSTRANDSCORE_API const TArray< FHairGroupsInterpolation > & UGroomAsset::GetHairGroupsInterpolation () const
References UE_API.
Referenced by UE_DEPRECATED(), and UFUNCTION().
GetHairGroupsInterpolationMemberName()
HAIRSTRANDSCORE_API FName UGroomAsset::GetHairGroupsInterpolationMemberName () static
References UE_API.
GetHairGroupsLOD()
HAIRSTRANDSCORE_API const TArray< FHairGroupsLOD > & UGroomAsset::GetHairGroupsLOD () const
References UE_API.
Referenced by UE_DEPRECATED(), and UFUNCTION().
GetHairGroupsLODMemberName()
HAIRSTRANDSCORE_API FName UGroomAsset::GetHairGroupsLODMemberName () static
References UE_API.
GetHairGroupsMaterials()
HAIRSTRANDSCORE_API const TArray< FHairGroupsMaterial > & UGroomAsset::GetHairGroupsMaterials () const
References UE_API.
Referenced by UE_DEPRECATED(), and UFUNCTION().
GetHairGroupsMaterialsMemberName()
HAIRSTRANDSCORE_API FName UGroomAsset::GetHairGroupsMaterialsMemberName () static
References UE_API.
GetHairGroupsMeshes()
HAIRSTRANDSCORE_API const TArray< FHairGroupsMeshesSourceDescription > & UGroomAsset::GetHairGroupsMeshes () const
References UE_API.
Referenced by UE_DEPRECATED(), and UFUNCTION().
GetHairGroupsMeshesMemberName()
HAIRSTRANDSCORE_API FName UGroomAsset::GetHairGroupsMeshesMemberName () static
References UE_API.
GetHairGroupsPhysics()
HAIRSTRANDSCORE_API const TArray< FHairGroupsPhysics > & UGroomAsset::GetHairGroupsPhysics () const
References UE_API.
Referenced by UE_DEPRECATED(), and UFUNCTION().
GetHairGroupsPhysicsMemberName()
HAIRSTRANDSCORE_API FName UGroomAsset::GetHairGroupsPhysicsMemberName () static
References UE_API.
GetHairGroupsPlatformData() [1/2]
HAIRSTRANDSCORE_API TArray< FHairGroupPlatformData > & UGroomAsset::GetHairGroupsPlatformData ()
References UE_API.
GetHairGroupsPlatformData() [2/2]
HAIRSTRANDSCORE_API const TArray< FHairGroupPlatformData > & UGroomAsset::GetHairGroupsPlatformData () const
References UE_API.
GetHairGroupsPlatformDataMemberName()
HAIRSTRANDSCORE_API FName UGroomAsset::GetHairGroupsPlatformDataMemberName () static
References UE_API.
GetHairGroupsRendering()
HAIRSTRANDSCORE_API const TArray< FHairGroupsRendering > & UGroomAsset::GetHairGroupsRendering () const
References UE_API.
Referenced by UE_DEPRECATED(), and UFUNCTION().
GetHairGroupsRenderingMemberName()
HAIRSTRANDSCORE_API FName UGroomAsset::GetHairGroupsRenderingMemberName () static
References UE_API.
GetHairGroupsResources() [1/2]
HAIRSTRANDSCORE_API TArray< FHairGroupResources > & UGroomAsset::GetHairGroupsResources ()
References UE_API.
GetHairGroupsResources() [2/2]
HAIRSTRANDSCORE_API const TArray< FHairGroupResources > & UGroomAsset::GetHairGroupsResources () const
References UE_API.
GetHairInterpolationTypeMemberName()
HAIRSTRANDSCORE_API FName UGroomAsset::GetHairInterpolationTypeMemberName () static
References UE_API.
GetLODCount()
HAIRSTRANDSCORE_API int32 UGroomAsset::GetLODCount () const
References UE_API.
GetLODMode()
HAIRSTRANDSCORE_API EGroomLODMode UGroomAsset::GetLODMode () const
References UE_API.
GetLODModeMemberName()
HAIRSTRANDSCORE_API FName UGroomAsset::GetLODModeMemberName () static
References UE_API.
GetMaterialIndex()
HAIRSTRANDSCORE_API int32 UGroomAsset::GetMaterialIndex (FName MaterialSlotName) const
References UE_API.
GetMaterialSlotNames()
HAIRSTRANDSCORE_API TArray< FName > UGroomAsset::GetMaterialSlotNames () const
References UE_API.
GetMinLOD()
HAIRSTRANDSCORE_API FPerPlatformInt UGroomAsset::GetMinLOD () const
References UE_API.
GetMinLODMemberName()
HAIRSTRANDSCORE_API FName UGroomAsset::GetMinLODMemberName () static
References UE_API.
GetNumHairGroups()
HAIRSTRANDSCORE_API int32 UGroomAsset::GetNumHairGroups () const
References UE_API.
GetOnGroomAssetChanged()
FOnGroomAssetChanged & UGroomAsset::GetOnGroomAssetChanged () inline
Definition at line 685 of file GroomAsset.h.
References OnGroomAssetChanged.
GetOnGroomAssetResourcesChanged()
FOnGroomAssetResourcesChanged & UGroomAsset::GetOnGroomAssetResourcesChanged () inline
Definition at line 686 of file GroomAsset.h.
References OnGroomAssetResourcesChanged.
GetOnGroomAsyncLoadFinished()
FOnGroomAsyncLoadFinished & UGroomAsset::GetOnGroomAsyncLoadFinished () inline
Definition at line 687 of file GroomAsset.h.
References OnGroomAsyncLoadFinished.
GetResourceSizeEx()
virtual HAIRSTRANDSCORE_API void UGroomAsset::GetResourceSizeEx (FResourceSizeEx & CumulativeResourceSize) override virtual
Get the size of the object/resource for use in memory tools or to display to artists/LDs in the Editor This is the extended version which separates up the used memory into different memory regions (the actual definition of which may be platform specific).
Parameters
CumulativeResourceSize Struct used to count up the cumulative size of the resource as to be displayed to artists/LDs in the Editor.
Reimplemented from UObject.
References UE_API.
GetRiggedSkeletalMeshMemberName()
HAIRSTRANDSCORE_API FName UGroomAsset::GetRiggedSkeletalMeshMemberName () static
References UE_API.
HasDebugData()
HAIRSTRANDSCORE_API bool UGroomAsset::HasDebugData () const
Debug data for derived asset generation (strands textures, ...).
References UE_API.
HasGeometryType() [1/2]
HAIRSTRANDSCORE_API bool UGroomAsset::HasGeometryType (EGroomGeometryType Type) const
References UE_API.
HasGeometryType() [2/2]
HAIRSTRANDSCORE_API bool UGroomAsset::HasGeometryType (uint32 GroupIndex, EGroomGeometryType Type) const
References UE_API.
InitCardsResources()
HAIRSTRANDSCORE_API void UGroomAsset::InitCardsResources ()
References UE_API.
InitGuideResources()
HAIRSTRANDSCORE_API void UGroomAsset::InitGuideResources ()
References UE_API.
InitMeshesResources()
HAIRSTRANDSCORE_API void UGroomAsset::InitMeshesResources ()
References UE_API.
InitResources()
HAIRSTRANDSCORE_API void UGroomAsset::InitResources ()
Initialize/Update/Release resources.
References UE_API.
InitStrandsResources()
HAIRSTRANDSCORE_API void UGroomAsset::InitStrandsResources ()
References UE_API.
IsDeformationEnable()
HAIRSTRANDSCORE_API bool UGroomAsset::IsDeformationEnable (int32 GroupIndex) const
References UE_API.
IsGlobalInterpolationEnable()
HAIRSTRANDSCORE_API bool UGroomAsset::IsGlobalInterpolationEnable (int32 GroupIndex, int32 LODIndex) const
References UE_API.
IsMaterialSlotNameValid()
HAIRSTRANDSCORE_API bool UGroomAsset::IsMaterialSlotNameValid (FName MaterialSlotName) const
References UE_API.
IsMaterialUsed()
HAIRSTRANDSCORE_API bool UGroomAsset::IsMaterialUsed (int32 MaterialIndex) const
References UE_API.
IsSimulationEnable() [1/2]
HAIRSTRANDSCORE_API bool UGroomAsset::IsSimulationEnable () const
References UE_API.
IsSimulationEnable() [2/2]
HAIRSTRANDSCORE_API bool UGroomAsset::IsSimulationEnable (int32 GroupIndex, int32 LODIndex) const
References UE_API.
IsValid()
bool UGroomAsset::IsValid () const inline
Definition at line 714 of file GroomAsset.h.
References bIsInitialized.
IsVisible()
HAIRSTRANDSCORE_API bool UGroomAsset::IsVisible (int32 GroupIndex, int32 LODIndex) const
References UE_API.
MarkMaterialsHasChanged()
HAIRSTRANDSCORE_API void UGroomAsset::MarkMaterialsHasChanged ()
References UE_API.
Modify()
virtual HAIRSTRANDSCORE_API bool UGroomAsset::Modify (bool bAlwaysMarkDirty = true) override virtual
Part of Uobject interface.
Reimplemented from UObject.
References UE_API.
NeedsInterpolationData() [1/2]
HAIRSTRANDSCORE_API bool UGroomAsset::NeedsInterpolationData () const
References UE_API.
NeedsInterpolationData() [2/2]
HAIRSTRANDSCORE_API bool UGroomAsset::NeedsInterpolationData (int32 GroupIndex) const
References UE_API.
PostEditChangeProperty()
virtual HAIRSTRANDSCORE_API void UGroomAsset::PostEditChangeProperty (FPropertyChangedEvent & PropertyChangedEvent) override virtual
Called when a property on this object has been modified externally.
Parameters
PropertyThatChanged the property that was modified
Reimplemented from UObject.
References Category, UObject::GetAssetRegistryTags(), UObject::PostInitProperties(), and UE_API.
PostLoad()
virtual HAIRSTRANDSCORE_API void UGroomAsset::PostLoad () override virtual
Do any object-specific cleanup required immediately after loading an object.
This is not called for newly-created objects, and by default will always execute on the game thread.
Reimplemented from UObject.
References UE_API.
ReadDataflowContent()
virtual HAIRSTRANDSCORE_API void UGroomAsset::ReadDataflowContent (const TObjectPtr< UDataflowBaseContent > & DataflowContent) override virtual
References UE_API.
RecreateResources()
HAIRSTRANDSCORE_API void UGroomAsset::RecreateResources ()
References UE_API.
ReleaseCardsResource()
HAIRSTRANDSCORE_API void UGroomAsset::ReleaseCardsResource (uint32 GroupIndex)
References UE_API.
ReleaseGuidesResource()
HAIRSTRANDSCORE_API void UGroomAsset::ReleaseGuidesResource (uint32 GroupIndex)
References UE_API.
ReleaseMeshesResource()
HAIRSTRANDSCORE_API void UGroomAsset::ReleaseMeshesResource (uint32 GroupIndex)
References UE_API.
ReleaseResource()
HAIRSTRANDSCORE_API void UGroomAsset::ReleaseResource ()
References UE_API.
ReleaseStrandsResource()
HAIRSTRANDSCORE_API void UGroomAsset::ReleaseStrandsResource (uint32 GroupIndex)
References UE_API.
RemoveUserDataOfClass()
virtual HAIRSTRANDSCORE_API void UGroomAsset::RemoveUserDataOfClass (TSubclassOf< UAssetUserData > InUserDataClass) override virtual
Reimplemented from IInterface_AssetUserData.
References UE_API.
SavePendingProceduralAssets()
void UGroomAsset::SavePendingProceduralAssets () private
Serialize()
virtual HAIRSTRANDSCORE_API void UGroomAsset::Serialize (FArchive & Ar) override virtual
Handles reading, writing, and reference collecting using FArchive.
This implementation handles all FProperty serialization, but can be overridden for native variables.
Reimplemented from UObject.
References Ar, and UE_API.
SetDataflowSettings()
void UGroomAsset::SetDataflowSettings (const FGroomDataflowSettings & InDataflowSettings) inline
Set the Dataflow settings associated to this groom asset if any.
Definition at line 576 of file GroomAsset.h.
SetDisableBelowMinLodStripping()
HAIRSTRANDSCORE_API void UGroomAsset::SetDisableBelowMinLodStripping (FPerPlatformBool In)
References UE_API.
SetEffectiveLODBias()
HAIRSTRANDSCORE_API void UGroomAsset::SetEffectiveLODBias (const TArray< float > & In)
References UE_API.
SetHairGroupsInfo()
HAIRSTRANDSCORE_API void UGroomAsset::SetHairGroupsInfo (const TArray< FHairGroupInfoWithVisibility > & In)
References UE_API.
SetHairGroupsPlatformData()
HAIRSTRANDSCORE_API void UGroomAsset::SetHairGroupsPlatformData (const TArray< FHairGroupPlatformData > & In)
References UE_API.
SetHairWidth()
HAIRSTRANDSCORE_API void UGroomAsset::SetHairWidth (float Width)
References UE_API, and Width.
SetMinLOD()
HAIRSTRANDSCORE_API void UGroomAsset::SetMinLOD (FPerPlatformInt In)
References UE_API.
SetNumGroup()
HAIRSTRANDSCORE_API void UGroomAsset::SetNumGroup (uint32 InGroupCount, bool bResetGroupData = true, bool bResetOtherData = true)
References UE_API.
SetScatterSceneLighting()
HAIRSTRANDSCORE_API void UGroomAsset::SetScatterSceneLighting (bool Enable)
References Enable, and UE_API.
SetStableRasterization()
HAIRSTRANDSCORE_API void UGroomAsset::SetStableRasterization (bool bEnable)
References UE_API.
UE_DEPRECATED() [1/17]
UGroomAsset::UE_DEPRECATED (5. 3, "Please do not access this member directly; use UGroomAsset accessor.")
Store strands/cards/meshes data.
References UE_DEPRECATED().
UE_DEPRECATED() [2/17]
UGroomAsset::UE_DEPRECATED (5. 3, "Please do not access this member directly; use UGroomAsset accessor.")
Enable radial basis function interpolation to be used instead of the local skin rigid transform.
References UE_DEPRECATED().
UE_DEPRECATED() [3/17]
UGroomAsset::UE_DEPRECATED (5. 3, "Please do not access this member directly; use UGroomAsset accessor.")
Type of interpolation used.
References Category, meta, ToolTip, UE_DEPRECATED(), and UPROPERTY().
UE_DEPRECATED() [4/17]
UGroomAsset::UE_DEPRECATED (5. 3, "Please do not access this member directly; use UGroomAsset accessor.")
When true all LODs below MinLod will still be cooked.
References Category, UE_DEPRECATED(), and UPROPERTY().
UE_DEPRECATED() [5/17]
UGroomAsset::UE_DEPRECATED (5. 3, "Please do not access this member directly; use UGroomAsset accessor.")
The LOD bias to use after LOD stripping, regardless of MinLOD.
Computed at cook time
References UE_DEPRECATED(), and UPROPERTY().
UE_DEPRECATED() [6/17]
UGroomAsset::UE_DEPRECATED (5. 3, "Please do not access this member directly; use UGroomAsset accessor.")
Deformed skeletal mesh mapping from groups to sections.
References UE_DEPRECATED(), and UPROPERTY().
UE_DEPRECATED() [7/17]
UGroomAsset::UE_DEPRECATED (5. 3, "Please do not access this member directly; use UGroomAsset accessor.")
Deformed skeletal mesh that will drive the groom deformation/simulation.
For creating this skeletal mesh, enable EnableDeformation within the interpolation settings
References Category, UE_DEPRECATED(), and UPROPERTY().
UE_DEPRECATED() [8/17]
UGroomAsset::UE_DEPRECATED (5. 3, "Please do not access this member directly; use UGroomAsset accessor.")
Enable guide-cache support.
This allows to attach a guide-cache dynamically at runtime
References Category, DisplayName, meta, ToolTip, UE_DEPRECATED(), and UPROPERTY().
UE_DEPRECATED() [9/17]
UGroomAsset::UE_DEPRECATED (5. 3, "Please do not access this member directly; use UGroomAsset accessor.")
Minimum LOD to cook.
References Category, DisplayName, meta, MinLOD, UE_DEPRECATED(), and UPROPERTY().
UE_DEPRECATED() [10/17]
UGroomAsset::UE_DEPRECATED (5. 3, "Please do not access this member directly; use UGroomAsset accessor.")
References Category, DisplayName, meta, UE_DEPRECATED(), and UPROPERTY().
Referenced by UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
UE_DEPRECATED() [11/17]
UGroomAsset::UE_DEPRECATED (5. 3, "Please do not access this member directly; use UGroomAsset accessor.")
Cards - Source description data.
References Category, DisplayName, GetHairGroupsCards(), meta, UE_DEPRECATED(), and UPROPERTY().
UE_DEPRECATED() [12/17]
UGroomAsset::UE_DEPRECATED (5. 3, "Please do not access this member directly; use UGroomAsset accessor.")
References Category, DisplayName, GetHairGroupsInterpolation(), meta, UE_DEPRECATED(), and UPROPERTY().
UE_DEPRECATED() [13/17]
UGroomAsset::UE_DEPRECATED (5. 3, "Please do not access this member directly; use UGroomAsset accessor.")
References Category, DisplayName, GetHairGroupsLOD(), meta, UE_DEPRECATED(), and UPROPERTY().
UE_DEPRECATED() [14/17]
UGroomAsset::UE_DEPRECATED (5. 3, "Please do not access this member directly; use UGroomAsset accessor.")
Meshes - Source description data.
References Category, DisplayName, GetHairGroupsMaterials(), meta, UE_DEPRECATED(), and UPROPERTY().
UE_DEPRECATED() [15/17]
UGroomAsset::UE_DEPRECATED (5. 3, "Please do not access this member directly; use UGroomAsset accessor.")
Meshes - Source description data.
References Category, DisplayName, GetHairGroupsMeshes(), meta, UE_DEPRECATED(), and UPROPERTY().
UE_DEPRECATED() [16/17]
UGroomAsset::UE_DEPRECATED (5. 3, "Please do not access this member directly; use UGroomAsset accessor.")
References Category, DisplayName, GetHairGroupsPhysics(), meta, UE_DEPRECATED(), and UPROPERTY().
UE_DEPRECATED() [17/17]
UGroomAsset::UE_DEPRECATED (5. 3, "Please do not access this member directly; use UGroomAsset accessor.")
References Category, DisplayName, GetHairGroupsRendering(), meta, UE_DEPRECATED(), and UPROPERTY().
UFUNCTION() [1/24]
UGroomAsset::UFUNCTION () const
References UE_API.
UFUNCTION() [2/24]
UGroomAsset::UFUNCTION () const
References UE_API.
UFUNCTION() [3/24]
UGroomAsset::UFUNCTION () const
References UE_API.
UFUNCTION() [4/24]
UGroomAsset::UFUNCTION () &
References GetHairGroupsCards(), and UE_API.
UFUNCTION() [5/24]
UGroomAsset::UFUNCTION () &
References GetHairGroupsInterpolation(), and UE_API.
UFUNCTION() [6/24]
UGroomAsset::UFUNCTION () &
References GetHairGroupsLOD(), and UE_API.
UFUNCTION() [7/24]
UGroomAsset::UFUNCTION () &
References GetHairGroupsMaterials(), and UE_API.
UFUNCTION() [8/24]
UGroomAsset::UFUNCTION () &
References GetHairGroupsMeshes(), and UE_API.
UFUNCTION() [9/24]
UGroomAsset::UFUNCTION () &
References GetHairGroupsPhysics(), and UE_API.
UFUNCTION() [10/24]
UGroomAsset::UFUNCTION () &
References GetHairGroupsRendering(), and UE_API.
UFUNCTION() [11/24]
UGroomAsset::UFUNCTION () &
References GetDeformedGroupSections(), and UE_API.
UFUNCTION() [12/24]
UGroomAsset::UFUNCTION () const
References UE_API.
UFUNCTION() [13/24]
UGroomAsset::UFUNCTION () const &
References UE_API.
UFUNCTION() [14/24]
UGroomAsset::UFUNCTION ()
References UE_API.
UFUNCTION() [15/24]
UGroomAsset::UFUNCTION ()
References UE_API.
UFUNCTION() [16/24]
UGroomAsset::UFUNCTION () const &
References UE_API.
UFUNCTION() [17/24]
UGroomAsset::UFUNCTION () const &
References UE_API.
UFUNCTION() [18/24]
UGroomAsset::UFUNCTION () const &
References UE_API.
UFUNCTION() [19/24]
UGroomAsset::UFUNCTION () const &
References UE_API.
UFUNCTION() [20/24]
UGroomAsset::UFUNCTION () const &
References UE_API.
UFUNCTION() [21/24]
UGroomAsset::UFUNCTION () const &
References UE_API.
UFUNCTION() [22/24]
UGroomAsset::UFUNCTION () const &
References UE_API.
UFUNCTION() [23/24]
UGroomAsset::UFUNCTION ()
References UE_API.
UFUNCTION() [24/24]
UGroomAsset::UFUNCTION ()
References UE_API.
UpdateCachedSettings()
HAIRSTRANDSCORE_API void UGroomAsset::UpdateCachedSettings ()
References UE_API.
UpdateHairGroupsInfo()
HAIRSTRANDSCORE_API void UGroomAsset::UpdateHairGroupsInfo ()
References UE_API.
UpdatePhysicsSystems()
void UGroomAsset::UpdatePhysicsSystems () private
Update the physics system based on the solver settings enum.
UpdateResource()
HAIRSTRANDSCORE_API void UGroomAsset::UpdateResource ()
References UE_API.
UPROPERTY() [1/4]
UGroomAsset::UPROPERTY () private
Dataflow settings used for any dataflow related operations.
References Category, and UPROPERTY().
UPROPERTY() [2/4]
UGroomAsset::UPROPERTY ()
Array of user data stored with the asset.
References Category, and Hidden.
UPROPERTY() [3/4]
UGroomAsset::UPROPERTY () private
References Category, Default, DisplayName, meta, and ToolTip.
Referenced by UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UPROPERTY(), and UPROPERTY().
UPROPERTY() [4/4]
UGroomAsset::UPROPERTY () private pure virtual
References Category, DisplayName, meta, ToolTip, and UPROPERTY().
ValidateSimulationCache()
HAIRSTRANDSCORE_API void UGroomAsset::ValidateSimulationCache ()
Enable the simulation cache and recompute the cached derived data.
References UE_API.
WriteDataflowContent()
virtual HAIRSTRANDSCORE_API void UGroomAsset::WriteDataflowContent (const TObjectPtr< UDataflowBaseContent > & DataflowContent) const override virtual
References UE_API.
Friends And Related Symbol Documentation
UGroomComponent
friend class UGroomComponent friend
Definition at line 837 of file GroomAsset.h.
References Count, Source, and UGroomComponent.
Referenced by UGroomComponent.
Field Documentation
AssetNameHash
uint32 UGroomAsset::AssetNameHash = 0 private
Definition at line 902 of file GroomAsset.h.
Referenced by GetAssetHash().
AssetToSave_Meshes
TQueue<UStaticMesh*> UGroomAsset::AssetToSave_Meshes private
Definition at line 922 of file GroomAsset.h.
AssetToSave_Textures
TQueue<FHairGroupCardsTextures*> UGroomAsset::AssetToSave_Textures private
Definition at line 923 of file GroomAsset.h.
bIsInitialized
bool UGroomAsset::bIsInitialized = false private
Definition at line 901 of file GroomAsset.h.
Referenced by IsValid().
CachedHairGroupsCards
TArray<FHairGroupsCardsSourceDescription> UGroomAsset::CachedHairGroupsCards private
Definition at line 916 of file GroomAsset.h.
CachedHairGroupsInterpolation
TArray<FHairGroupsInterpolation> UGroomAsset::CachedHairGroupsInterpolation private
Definition at line 914 of file GroomAsset.h.
CachedHairGroupsLOD
TArray<FHairGroupsLOD> UGroomAsset::CachedHairGroupsLOD private
Definition at line 915 of file GroomAsset.h.
CachedHairGroupsMeshes
TArray<FHairGroupsMeshesSourceDescription> UGroomAsset::CachedHairGroupsMeshes private
Definition at line 917 of file GroomAsset.h.
CachedHairGroupsPhysics
TArray<FHairGroupsPhysics> UGroomAsset::CachedHairGroupsPhysics private
Definition at line 913 of file GroomAsset.h.
CachedHairGroupsRendering
TArray<FHairGroupsRendering> UGroomAsset::CachedHairGroupsRendering private
Definition at line 912 of file GroomAsset.h.
CachedResourcesFeatureLevel
ERHIFeatureLevel::Type UGroomAsset::CachedResourcesFeatureLevel = ERHIFeatureLevel::Num private
Definition at line 919 of file GroomAsset.h.
CachedResourcesPlatformLevel
ERHIFeatureLevel::Type UGroomAsset::CachedResourcesPlatformLevel = ERHIFeatureLevel::Num private
Definition at line 918 of file GroomAsset.h.
DisplayName
UGroomAsset::DisplayName
Initial value:
= "RBF Interpolation"))
    bool EnableGlobalInterpolation = false
Definition at line 518 of file GroomAsset.h.
Referenced by UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UPROPERTY(), and UPROPERTY().
HairGroupsResources
TArray<FHairGroupResources> UGroomAsset::HairGroupsResources private
Store strands/cards/meshes resources.
Definition at line 562 of file GroomAsset.h.
OnGroomAssetChanged
FOnGroomAssetChanged UGroomAsset::OnGroomAssetChanged
Definition at line 785 of file GroomAsset.h.
Referenced by GetOnGroomAssetChanged().
OnGroomAssetResourcesChanged
FOnGroomAssetResourcesChanged UGroomAsset::OnGroomAssetResourcesChanged
Definition at line 786 of file GroomAsset.h.
Referenced by GetOnGroomAssetResourcesChanged().
OnGroomAsyncLoadFinished
FOnGroomAsyncLoadFinished UGroomAsset::OnGroomAsyncLoadFinished
Definition at line 787 of file GroomAsset.h.
Referenced by GetOnGroomAsyncLoadFinished().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/HairStrands/Source/HairStrandsCore/Public/GroomAsset.h