Unreal Engine 5.6 C++ API: FBlueprintEditor Class Reference
FBlueprintEditor Class Reference
Main Kismet asset editor.
#include "BlueprintEditor.h"
Data Structures
struct FAnalyticsStatistics
Structure to contain editor usage analytics.
struct FDisallowedPinConnection
A record of a warning generated by a disallowed pin connection attempt.
struct FImportNamespaceExParameters
Parameters for the extended ImportNamespaceEx() method.
Public Types
enum ECreatedDocumentType {
CGT_NewVariable , CGT_NewFunctionGraph , CGT_NewMacroGraph , CGT_NewAnimationLayer ,
CGT_NewEventGraph , CGT_NewLocalVariable
}
Public Types inherited from FGCObject
enum class EFlags : uint32 { None = 0 , RegisterLater = 1 << 0 , AddStableNativeReferencesOnly = 1 << 1 }
Public Member Functions
FBlueprintEditor ()
virtual ~FBlueprintEditor ()
FBPEditorBookmarkNode * AddBookmark (const FText &DisplayName, const FEditedDocumentInfo &BookmarkInfo, bool bSharedBookmark=false)
Adds a new bookmark node to the Blueprint that's being edited.
bool AddNewDelegateIsVisible () const
virtual void AddNewFunctionVariant (const UEdGraph *InOriginalFunction)
Create a variant for a function.
virtual void AddReferencedObjects (FReferenceCollector &Collector) override
Pure virtual that must be overloaded by the inheriting class.
virtual void AddToSelection (UEdGraphNode *InNode) override
void AnalyticsTrackCompileEvent (UBlueprint *Blueprint, int32 NumErrors, int32 NumWarnings) const
virtual void AnalyticsTrackNodeEvent (UBlueprint *Blueprint, UEdGraphNode *GraphNode, bool bNodeDelete=false) const override
Used to track node create/delete events for Analytics.
virtual bool AreDelegatesAllowed () const
Whether delegates are allowed to be displayed/created in a blueprint.
virtual bool AreEventGraphsAllowed () const
Whether event graphs are allowed to be displayed/created in a blueprint.
virtual bool AreMacrosAllowed () const
Whether macros are allowed to be displayed/created in a blueprint.
bool CanAccessComponentsMode () const
Returns whether the edited blueprint has components.
virtual bool CanAddNewLocalVariable () const
Checks if adding a local variable is allowed in the focused graph.
virtual void ClearSelectionStateFor (FName SelectionOwner)
void CloseDocumentTab (const UObject *DocumentID)
Finds the tab associated with the specified asset, and closes if it is open.
void CloseMergeTool ()
Closes the merge tool, rather than simply hiding it.
void CommonInitialization (const TArray< UBlueprint * > &InitBlueprints, bool bShouldOpenInDefaultsMode)
virtual void Compile ()
Called when Compile button is clicked.
virtual FReply Compile_OnClickWithReply ()
Calls the above function, but returns an FReply::Handled().
bool ConvertEventIfValid (UK2Node_Event *EventToConv)
Converts the given event node to a function graph on this blueprint if it passes validation.
bool ConvertFunctionIfValid (UK2Node_FunctionEntry *FuncEntryNode)
Converts the given function entry node to an event if it passes validation.
void CreateMergeToolTab ()
Forces the merge tool to be shown.
void CreateMergeToolTab (const UBlueprint *BaseBlueprint, const UBlueprint *RemoteBlueprint, const FOnMergeResolved &ResolutionCallback)
TSharedPtr< class ISCSEditorCustomization > CustomizeSubobjectEditor (const USceneComponent *InComponentToCustomize) const
Check to see if we can customize the subobject editor for the passed-in scene component.
DECLARE_EVENT (FBlueprintEditor, FOnRefreshEvent)
Broadcasts a notification whenever the editor needs associated controls to refresh.
DECLARE_MULTICAST_DELEGATE_OneParam (FOnModeSet, FName)
void DestroyPreview ()
Destroy the Blueprint preview.
void DoPromoteToVariable2f (UBlueprint *InBlueprint, UEdGraphPin *InTargetPin, bool bInToMemberVariable, TOptional< FVector2f > InOptionalLocation=TOptional< FVector2f >())
void DumpMessagesToCompilerLog (const TArray< TSharedRef< class FTokenizedMessage > > &Messages, bool bForceMessageDisplay)
Dumps messages to the compiler log, with an option to force it to display/come to front.
void EnableSubobjectPreview (bool bEnable)
Enable/disable the subobject editor preview viewport.
void EnsureBlueprintIsUpToDate (UBlueprint *BlueprintObj)
virtual TSharedPtr< FSubobjectEditorTreeNode > FindAndSelectSubobjectEditorTreeNode (const UActorComponent *InComponent, bool IsCntrlDown) override
bool FindOpenTabsContainingDocument (const UObject *DocumentID, TArray< TSharedPtr< SDockTab > > &Results)
virtual void FocusInspectorOnGraphSelection (const TSet< class UObject * > &NewSelection, bool bForceRefresh=false)
virtual FText GetBaseToolkitName () const override
virtual UBlueprint * GetBlueprintObj () const
Returns a pointer to the Blueprint object we are currently editing, as long as we are editing exactly one.
TSharedRef< SBlueprintBookmarks > GetBookmarksWidget () const
void GetBoundsForNode (const UEdGraphNode *InNode, class FSlateRect &OutRect, float InPadding) const
Get the visible bounds of the given graph node.
TSharedRef< SWidget > GetCompilerResults () const
virtual FString GetCustomDebugObjectLabel (UObject *ObjectBeingDebugged) const
Can be overloaded to customize the labels in the debug filter.
virtual void GetCustomDebugObjects (TArray< FCustomDebugObject > &DebugList) const
Adds to a list of custom objects for debugging beyond what will automatically be found/used.
TSharedRef< SKismetInspector > GetDefaultEditor () const
TSubclassOf< UEdGraphSchema > GetDefaultSchema () const
Gets the default schema for this editor.
virtual FString GetDocumentationLink () const override
TSharedRef< SFindInBlueprints > GetFindResults () const
virtual UEdGraph * GetFocusedGraph () const override
Returns the currently focused graph context, or NULL if no graph is available.
virtual FText GetGraphDecorationString (UEdGraph *InGraph) const
Called by a graph title bar to get any extra information the editor would like to display.
virtual TSharedPtr< class IClassViewerFilter > GetImportedClassViewerFilter () const override
Return the class viewer filter associated with the current set of imported namespaces within this editor context.
TSharedRef< SKismetInspector > GetInspector () const
Getters for the various Kismet2 widgets.
float GetInstructionTextOpacity (UEdGraph *InGraph) const
Used to determine the visibility of the graph's instruction text.
bool & GetIsContextSensitive ()
Gets or sets the flag for context sensitivity in the graph action menu.
TSharedPtr< SMyBlueprint > GetMyBlueprintWidget () const
EVisibility GetNativeParentClassButtonsVisibility () const
Determines visibility of the native parent class manipulation buttons on the menu bar overlay.
virtual int32 GetNumberOfSelectedNodes () const override
Get number of currently selected nodes in the SCS editor tree.
TSharedRef< SBlueprintPalette > GetPalette ()
EVisibility GetParentClassNameVisibility () const
Determines visibility of the standard parent class label on the menu bar overlay.
FText GetPIEStatus () const
Returns our PIE Status - SIMULATING / SERVER / CLIENT.
virtual void GetPinTypeSelectorFilters (TArray< TSharedPtr< class IPinTypeSelectorFilter > > &OutFilters) const override
Get all the the pin type selector filters within this editor context.
bool GetPinVisibility (SGraphEditor::EPinVisibility Visibility) const
AActor * GetPreviewActor () const
Provides access to the preview actor.
FPreviewScene * GetPreviewScene ()
Provides access to the preview scene.
virtual FString GetReferencerName () const override
Overload this method to report a name for your referencer.
TSharedPtr< SReplaceNodeReferences > GetReplaceReferencesWidget () const
FGraphPanelSelectionSet GetSelectedNodes () const
Get the currently selected set of nodes.
virtual TArray< TSharedPtr< FSubobjectEditorTreeNode > > GetSelectedSubobjectEditorTreeNodes () const override
Util to get the currently selected Subobject editor tree Nodes.
UEdGraphNode * GetSingleSelectedNode () const
Returns the currently selected node if there is a single node selected (if there are multiple nodes selected or none selected, it will return nullptr)
virtual TStatId GetStatId () const override
Return the stat id used to track the performance of this object.
TSharedPtr< SSubobjectEditor > GetSubobjectEditor () const
UObject * GetSubobjectEditorObjectContext () const
Delegate invoked when the Subobject editor needs to obtain the object context for editing.
TSharedPtr< SSCSEditorViewport > GetSubobjectViewport () const
FText GetTextForNativeParentClassHeaderLink () const
Returns: "(<NativeParentClass>.h)".
virtual ETickableTickType GetTickableTickType () const override
Virtual that can be overloaded by the inheriting class and is called before first tick.
TSharedPtr< class FBlueprintEditorToolbar > GetToolbarBuilder ()
virtual FName GetToolkitContextFName () const override
virtual FName GetToolkitFName () const override
virtual FText GetToolkitName () const override
virtual FText GetToolkitToolTipText () const override
FName GetUISelectionState () const
Gets the UI selection state of this editor.
void GetViewBookmark (FGuid &BookmarkId)
Gets the focused graph current view bookmark ID.
void GetViewLocation (FVector2D &Location, float &ZoomAmount)
Gets the focused graph view location/zoom amount.
FEditorViewportSelectabilityBridge * GetViewportSelectabilityBridge ()
virtual FLinearColor GetWorldCentricTabColorScale () const override
virtual FString GetWorldCentricTabPrefix () const override
virtual void HandleSetObjectBeingDebugged (UObject *InObject)
Handle when the debug object is changed in the UI.
void HandleUnrelatedNodesOpacityBoxChanged (float NewOpacity)
TOptional< float > HandleUnrelatedNodesOpacityBoxValue () const
void ImportNamespace (const FString &InNamespace)
Imports the given namespace into the editor.
void ImportNamespaceEx (const FImportNamespaceExParameters &InParams)
Imports a set of namespace(s) into the editor.
virtual bool InEditingMode () const
Returns true if in editing mode.
void InitBlueprintEditor (const EToolkitMode::Type Mode, const TSharedPtr< class IToolkitHost > &InitToolkitHost, const TArray< class UBlueprint * > &InBlueprints, bool bShouldOpenInDefaultsMode)
Edits the specified blueprint.
virtual void InitToolMenuContext (FToolMenuContext &MenuContext) override
Add context objects for menus and toolbars.
virtual bool IsBlueprintEditor () const override
virtual bool IsCompilingEnabled () const
Returns true if able to compile.
EVisibility IsDebuggerVisible () const
virtual bool IsEditable (UEdGraph *InGraph) const
Returns whether a graph is editable or not.
bool IsEditingSingleBlueprint () const
Returns whether the editor is currently editing a single blueprint object.
bool IsEditorClosing () const
Returns if we are currently closing the editor.
bool IsGraphInCurrentBlueprint (const UEdGraph *InGraph) const
Checks to see if the provided graph is contained within the current blueprint.
bool IsGraphReadOnly (UEdGraph *InGraph) const
Determines if the graph is ReadOnly, this differs from editable in that it is never expected to be edited and is in a read-only state.
virtual bool IsInAScriptingMode () const
Overridable function for determining if the current mode can script.
virtual bool IsNativeParentClassCodeLinkEnabled () const
Returns true if the parent class is native and the link to it's header can be shown.
bool IsNodeTitleVisible (const UEdGraphNode *Node, bool bRequestRename)
Check the Node Title is visible.
virtual bool IsNonImportedObject (const FSoftObjectPath &InObject) const
Return whether the given object (referenced by path) falls outside the scope of the current set of imported namespaces within this editor context.
virtual bool IsNonImportedObject (const UObject *InObject) const
Return whether the given object falls outside the scope of the current set of imported namespaces within this editor context.
bool IsParentClassABlueprint () const
Returns true if the parent class of the Blueprint being edited is also a Blueprint.
bool IsParentClassAnEditableBlueprint () const
Returns true if the parent class of the Blueprint being edited is an editable Blueprint.
bool IsParentClassNative () const
Returns true if the parent class of the Blueprint being edited is native.
bool IsPlayInEditorActive () const
Returns true if PIE is active.
bool IsSaveOnCompileEnabled () const
Helper functions used to construct/operate-on the "Save on Compile" command.
virtual bool IsSectionVisible (NodeSectionID::Type InSectionID) const
bool IsToggleHideUnrelatedNodesChecked () const
virtual void JumpToHyperlink (const UObject *ObjectReference, bool bRequestRename=false) override
void JumpToNode (const class UEdGraphNode *Node, bool bRequestRename=false)
Pan the view to center on a particular node.
virtual void JumpToPin (const class UEdGraphPin *Pin) override
void LogSimpleMessage (const FText &MessageText)
Throw a simple message into the log.
void LogToken_OnClicked (const class IMessageToken &Token)
Called when a token in a log message is clicked.
TSharedRef< SWidget > MakeHideUnrelatedNodesOptionsMenu ()
Make a drop down menu to control the opacity of unrelated nodes.
EVisibility NewDocument_GetVisibilityForType (ECreatedDocumentType GraphType) const
virtual bool NewDocument_IsVisibleForType (ECreatedDocumentType GraphType) const
FReply NewDocument_OnClick (ECreatedDocumentType GraphType)
virtual void NewDocument_OnClicked (ECreatedDocumentType GraphType)
Called when New Function button is clicked.
virtual bool OnActionMatchesName (FEdGraphSchemaAction *InAction, const FName &InName) const
function used by the SMyBlueprint to determine if an action matches a name.
virtual void OnActiveTabChanged (TSharedPtr< SDockTab > PreviouslyActive, TSharedPtr< SDockTab > NewlyActivated)
void OnAddNewDelegate ()
Called when New Delegate button is clicked.
virtual void OnAddNewLocalVariable ()
Adds a new local variable to the focused function graph.
void OnAddNewVariable ()
Adds a new variable to this blueprint.
FReply OnAddNewVariable_OnClick ()
virtual void OnClose () override
Called when this toolkit is being closed.
virtual void OnComponentAddedToBlueprint (const FSubobjectData &NewSubobjectData)
Delegate invoked when a new subobject is added in the subobject editor widget.
virtual void OnComponentDoubleClicked (TSharedPtr< class FSubobjectEditorTreeNode > Node)
Delegate invoked when an item is double clicked in the subobject editor widget.
void OnDumpCachedIndexDataForBlueprint ()
Dumps the currently-cached index data for the blueprint to a file for debugging.
void OnEditParentClassNativeCodeClicked ()
Handles opening the header file of native parent class.
void OnGenerateSearchIndexForDebugging ()
Dumps the current blueprint search index to a JSON file for debugging purposes.
virtual void OnGraphEditorBackgrounded (const TSharedRef< SGraphEditor > &InGraphEditor)
Called when the graph editor tab is backgrounded.
virtual void OnGraphEditorFocused (const TSharedRef< class SGraphEditor > &InGraphEditor)
Called when graph editor focus is changed.
void OnLockNodeStateCheckStateChanged (ECheckBoxState NewCheckedState)
virtual bool OnlyShowCustomDebugObjects () const
If returns true only the custom debug list will be used.
FOnModeSet & OnModeSet ()
void OnNodeSpawnedByKeymap ()
Called when node is spawned by keymap.
void OnNodeTitleCommitted (const FText &NewText, ETextCommit::Type CommitInfo, UEdGraphNode *NodeBeingChanged)
Called when a node's title is committed for a rename.
virtual void OnPasteNewLocalVariable (const FBPVariableDescription &VariableDescription)
Pastes a new local variable to the focused function graph.
FOnRefreshEvent & OnRefresh ()
virtual bool OnRequestClose (EAssetEditorCloseReason InCloseReason) override
Called when this toolkit is requested to close.
virtual void OnSelectionUpdated (const TArray< TSharedPtr< class FSubobjectEditorTreeNode > > &SelectedNodes)
Delegate invoked when the selection is changed in the subobject editor widget.
virtual FReply OnSpawnGraphNodeByShortcut (FInputChord InChord, const FVector2f &InPosition, UEdGraph *InGraph)
TSharedPtr< SDockTab > OpenDocument (const UObject *DocumentID, FDocumentTracker::EOpenDocumentCause Cause)
virtual TSharedPtr< SGraphEditor > OpenGraphAndBringToFront (UEdGraph *Graph, bool bSetFocus=true) override
Tries to open the specified graph and bring it's document to the front (note: this can return NULL)
void PostLayoutBlueprintEditorInitialization ()
void RefreshAllNodes_OnClicked ()
Called when the refresh all nodes button is clicked.
virtual void RefreshEditors (ERefreshBlueprintEditorReason::Type Reason=ERefreshBlueprintEditorReason::UnknownReason) override
virtual void RefreshInspector ()
virtual void RefreshMyBlueprint ()
void RegisterSCSEditorCustomization (const FName &InComponentName, TSharedPtr< class ISCSEditorCustomization > InCustomization)
Register a customization for interacting with the subobject editor.
virtual void RegisterTabSpawners (const TSharedRef< class FTabManager > &TabManager) override
IToolkit interface.
void RegisterToolbarTab (const TSharedRef< class FTabManager > &TabManager)
void RemoveBookmark (const FGuid &BookmarkNodeId, bool bRefreshUI=true)
Removes the bookmark node with the given ID.
void RemoveNamespace (const FString &InNamespace)
Removes the given namespace from the editor's current import context.
void RenameBookmark (const FGuid &BookmarkNodeId, const FText &NewName)
Renames the bookmark node with the given ID.
void RenameNewlyAddedAction (FName InActionName)
Utility function to handle all steps required to rename a newly added action.
void ReparentBlueprint_Clicked ()
Reparent the current blueprint.
virtual bool ReparentBlueprint_IsVisible () const
void ReparentBlueprint_NewParentChosen (UClass *ChosenClass)
void RequestSaveEditedObjectState ()
void RestoreEditedObjectState ()
Create new tab for each element of LastEditedObjects array.
void SaveEditedObjectState ()
Save the current set of edited objects in the LastEditedObjects array so it will be opened next time we open K2.
void SelectAndDuplicateNode (UEdGraphNode *InNode)
Duplicates an EdGraphNode using selection and copy / paste functionality.
void SelectGraphActionItemByName (const FName &ItemName, ESelectInfo::Type SelectInfo=ESelectInfo::Direct, int32 SectionId=INDEX_NONE, bool bIsCategory=false)
virtual bool SelectLocalVariable (const UEdGraph *Graph, const FName &VariableName)
Selects a local variable to load in the details panel.
virtual void SetCurrentMode (FName NewMode) override
void SetDetailsCustomization (TSharedPtr< class FDetailsViewObjectFilter > DetailsObjectFilter, TSharedPtr< class IDetailRootObjectCustomization > DetailsRootCustomization)
Sets customizations for the BP editor details panel.
void SetKeyboardFocus ()
Ensures the blueprint has keyboard focus.
void SetPinVisibility (SGraphEditor::EPinVisibility Visibility)
Pin visibility accessors.
void SetSubobjectEditorUICustomization (TSharedPtr< class ISCSEditorUICustomization > SCSEditorUICustomization)
Sets subobject editor UI customization.
void SetUISelectionState (FName SelectionOwner)
void SetupViewForBlueprintEditingMode ()
void SetViewLocation (const FVector2D &Location, float ZoomAmount, const FGuid &BookmarkId=FGuid())
Sets the focused graph view location/zoom amount.
virtual bool ShouldLoadBPLibrariesFromAssetRegistry ()
virtual void StartEditingDefaults (bool bAutoFocus=true, bool bForceRefresh=false)
Virtual override point for editing defaults; allowing more derived editors to edit something else.
virtual void SummonFindAndReplaceUI () override
Invokes the Find and Replace UI.
virtual void SummonSearchUI (bool bSetFindWithinBlueprint, FString NewSearchTerms=FString(), bool bSelectFirstResult=false) override
Invokes the search UI and sets the mode and search terms optionally.
virtual void Tick (float DeltaTime) override
Pure virtual that must be overloaded by the inheriting class.
void ToggleHideUnrelatedNodes ()
Make nodes which are unrelated to the selected nodes fade out.
virtual bool TransactionObjectAffectsBlueprint (UObject *InTransactedObject)
UE_DEPRECATED (5.0, "CustomizeSCSEditor has been deprecated. Use CustomizeSubobjectEditor instead.") TSharedPtr< class ISCSEditorCustomization > CustomizeSCSEditor(USceneComponent *InComponentToCustomize) const
UE_DEPRECATED (5.0, "FindAndSelectSCSEditorTreeNode has been deprecated. Use FindAndSelectSubobjectEditorTreeNode instead.") virtual TSharedPtr< class FSCSEditorTreeNode > FindAndSelectSCSEditorTreeNode(const UActorComponent *InComponent
UE_DEPRECATED (5.0, "GetSCSEditor has been deprecated. Use GetSubobjectEditor instead.") TSharedPtr< SSCSEditor > GetSCSEditor() const
Getters for the various optional Kismet2 widgets.
UE_DEPRECATED (5.0, "GetSelectedSCSEditorTreeNodes has been deprecated. Use GetSelectedSubobjectEditorTreeNodes instead.") virtual TArray< TSharedPtr< class FSCSEditorTreeNode > > GetSelectedSCSEditorTreeNodes() const override
UE_DEPRECATED (5.0, "OnComponentDoubleClicked(TSharedPtr<class FSCSEditorTreeNode>) has been deprecated. Use OnComponentDoubleClicked(TSharedPtr<class FSubobjectEditorTreeNode>) instead.") virtual void OnComponentDoubleClicked(TSharedPtr< class FSCSEditorTreeNode > Node)
Delegate invoked when an item is double clicked in the subobject editor widget.
UE_DEPRECATED (5.0, "OnSelectionUpdated(const TArray<TSharedPtr<class FSCSEditorTreeNode>>&) has been deprecated. Use OnSelectionUpdated(const TArray<TSharedPtr<class FSubobjectEditorTreeNode>>&) instead.") virtual void OnSelectionUpdated(const TArray< TSharedPtr< class FSCSEditorTreeNode > > &SelectedNodes)
Delegate invoked when the selection is changed in the subobject editor widget.
UE_DEPRECATED (5.0, "SetSCSEditorUICustomization has been deprecated. Use SetSubobjectEditorUICustomization instead.") void SetSCSEditorUICustomization(TSharedPtr< class ISCSEditorUICustomization > SCSEditorUICustomization)
UE_DEPRECATED (5.0, "The Toggle Hide Unrelated Nodes button is always shown now") bool ShouldShowToggleHideUnrelatedNodes(bool bIsToolbar) const
UE_DEPRECATED (5.1, "Please use GetPinTypeSelectorFilters") virtual TSharedPtr< class IPinTypeSelectorFilter > GetImportedPinTypeSelectorFilter() const override
UE_DEPRECATED (5.6, "Please use the version of the function accepting FVector2f.") virtual FReply OnSpawnGraphNodeByShortcut(FInputChord InChord
Handles spawning a graph node in the current graph using the passed in chord.
UE_DEPRECATED (5.6, "Use the version of this function accepting a TOptional") void DoPromoteToVariable(UBlueprint *InBlueprint
Perform the actual promote to variable action on the given pin in the given blueprint.
void UnregisterSCSEditorCustomization (const FName &InComponentName)
Unregister a previously registered customization for interacting with the subobject editor.
void UpdateNodeCreationStats (const ENodeCreateAction::Type CreateAction)
Update Node Creation mechanisms for analytics.
void UpdateNodesUnrelatedStatesAfterGraphChange ()
Update all nodes' unrelated states when the graph has changed.
void UpdatePreviewActor (UBlueprint *InBlueprint, bool bInForceFullUpdate=false)
Creates/updates the preview actor for the given blueprint.
void UpdateSubobjectPreview (bool bUpdateNow=false)
Refresh the preview viewport to reflect changes in the subobject.
void VariableListWasUpdated ()
Variable list window calls this after it is updated.
Public Member Functions inherited from IBlueprintEditor
virtual TSharedPtr< FSubobjectEditorTreeNode > FindAndSelectSubobjectEditorTreeNode (const class UActorComponent *InComponent, bool IsCntrlDown)=0
Find and select a specific SCS editor tree node associated with the given component.
virtual void JumpToPin (const UEdGraphPin *PinToFocusOn)=0
UE_DEPRECATED (5.0, "FindAndSelectSCSEditorTreeNode has been deprecated. Use FindAndSelectSubobjectEditorTreeNode instead.") virtual TSharedPtr< class FSCSEditorTreeNode > FindAndSelectSCSEditorTreeNode(const class UActorComponent *InComponent
UE_DEPRECATED (5.1, "Please use GetPinTypeSelectorFilters") virtual TSharedPtr< class IPinTypeSelectorFilter > GetImportedPinTypeSelectorFilter() const
Return the pin type selector filter associated with the current set of imported namespaces within this editor context.
UE_DEPRECATED (5.6, "Slate positions are represented in FVector2f. Please update to use the function acceping FVector2f.") virtual void PasteNodesHere(class UEdGraph *Graph
Public Member Functions inherited from FWorkflowCentricApplication
UNREALED_API FName GetCurrentMode () const
TSharedPtr< FApplicationMode > GetCurrentModePtr () const
virtual UNREALED_API FName GetToolMenuToolbarName (FName &OutParentName) const override
Get name used by tool menu.
UNREALED_API FName GetToolMenuToolbarNameForMode (const FName InModeName, FName &OutParentName) const
bool IsModeCurrent (FName ModeToCheck) const
UNREALED_API void PushTabFactories (FWorkflowAllowedTabSet &FactorySetToPush) const
virtual UNREALED_API UToolMenu * RegisterModeToolbarIfUnregistered (const FName InModeName)
Registers toolbar for a mode if not already registered.
virtual UNREALED_API void UnregisterTabSpawners (const TSharedRef< class FTabManager > &TabManager) override
Public Member Functions inherited from FAssetEditorToolkit
UNREALED_API FAssetEditorToolkit ()
Default constructor.
FAssetEditorToolkit (const FAssetEditorToolkit &)=delete
virtual UNREALED_API ~FAssetEditorToolkit ()
Virtual destructor, so that we can clean up our app when destroyed.
virtual void AddGraphEditorPinActionsToContextMenu (FToolMenuSection &InSection) const
UNREALED_API void AddMenuExtender (TSharedPtr< FExtender > Extender)
Adds or removes extenders to the default menu or the toolbar menu this asset editor.
UNREALED_API void AddToolbarExtender (TSharedPtr< FExtender > Extender)
UNREALED_API void AddToolbarWidget (TSharedRef< SWidget > Widget)
Adds or removes widgets from the default toolbar in this asset editor.
virtual void AddViewportOverlayWidget (TSharedRef< SWidget > InViewportOverlayWidget, int32 ZOrder=INDEX_NONE)
virtual UNREALED_API bool CloseWindow (EAssetEditorCloseReason InCloseReason) override
virtual UNREALED_API TSharedPtr< SWidget > CreateMenuBar (const TSharedPtr< FTabManager > &InTabManager, const FName InMenuName, FToolMenuContext &InToolMenuContext)
Method that can be overriden by derived classes to provide a custom MenuBar to the Standalone Toolkit Host.
UNREALED_API void FillDefaultAssetMenuCommands (FToolMenuSection &InSection)
Fills in the supplied menu with commands for modifying this asset that are generally common to most asset editors.
UNREALED_API void FillDefaultFileMenuCommands (FToolMenuSection &InSection)
Fills in the supplied menu with commands for working with this asset file.
UNREALED_API void FillDefaultFileMenuOpenCommands (FToolMenuSection &InSection)
Fills in the supplied menu with commands for working with this asset file.
UNREALED_API void FillDefaultHelpMenuCommands (FToolMenuSection &InSection)
Fills in the supplied menu with commands for the help menu.
virtual UNREALED_API void FocusWindow (UObject *ObjectToFocusOn=nullptr) override
UNREALED_API void GenerateToolbar ()
Makes a default asset editing toolbar.
virtual UNREALED_API TSharedPtr< FTabManager > GetAssociatedTabManager () override
virtual UNREALED_API FName GetEditingAssetTypeName () const override
virtual UNREALED_API FEditorModeTools & GetEditorModeManager () const final
virtual UNREALED_API FName GetEditorName () const override
IAssetEditorInstance interface.
virtual UNREALED_API double GetLastActivationTime () override
virtual UNREALED_API const TArray< UObject * > * GetObjectsCurrentlyBeingEdited () const override
virtual UNREALED_API EAssetOpenMethod GetOpenMethod () const override
UNREALED_API TSharedPtr< IToolkitHost > GetPreviousWorldCentricToolkitHost ()
virtual UNREALED_API UE::Editor::Toolbars::ECreateStatusBarOptions GetStatusBarCreationOptions () const
Called by StandaloneAssetEditorToolkitHost to determine what sections of the StatusBar should be created.
TSharedPtr< FTabManager > GetTabManager ()
virtual UNREALED_API FText GetTabSuffix () const override
UNREALED_API FName GetToolMenuAppName () const
UNREALED_API FName GetToolMenuName () const
UNREALED_API FName GetToolMenuToolbarName () const
UNREALED_API void InitAssetEditor (const EToolkitMode::Type Mode, const TSharedPtr< IToolkitHost > &InitToolkitHost, const FName AppIdentifier, const TSharedRef< FTabManager::FLayout > &StandaloneDefaultLayout, const bool bCreateDefaultStandaloneMenu, const bool bCreateDefaultToolbar, const TArray< UObject * > &ObjectsToEdit, const bool bInIsToolbarFocusable=false, const bool bInUseSmallToolbarIcons=false, const TOptional< EAssetOpenMethod > &InOpenMethod=TOptional< EAssetOpenMethod >())
Initializes this asset editor.
UNREALED_API void InitAssetEditor (const EToolkitMode::Type Mode, const TSharedPtr< IToolkitHost > &InitToolkitHost, const FName AppIdentifier, const TSharedRef< FTabManager::FLayout > &StandaloneDefaultLayout, const bool bCreateDefaultStandaloneMenu, const bool bCreateDefaultToolbar, UObject *ObjectToEdit, const bool bInIsToolbarFocusable=false, const bool bInUseSmallToolbarIcons=false, const TOptional< EAssetOpenMethod > &InOpenMethod=TOptional< EAssetOpenMethod >())
virtual UNREALED_API void InvokeTab (const FTabId &TabId) override
UNREALED_API bool IsActuallyAnAsset () const
True if this actually is editing an asset.
virtual UNREALED_API bool IsAssetEditor () const override
virtual bool IsPrimaryEditor () const override
virtual void OnToolkitHostingFinished (const TSharedRef< IToolkit > &Toolkit)
virtual void OnToolkitHostingStarted (const TSharedRef< IToolkit > &Toolkit)
virtual void OnViewportDragEnter (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
React to a Drag&Drop events from the viewport.
virtual void OnViewportDragLeave (const FDragDropEvent &DragDropEvent)
virtual FReply OnViewportDrop (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
FAssetEditorToolkit & operator= (const FAssetEditorToolkit &)=delete
UNREALED_API void RegenerateMenusAndToolbars ()
Regenerates the menubar and toolbar widgets.
UNREALED_API void RegisterDrawer (struct FWidgetDrawerConfig &&Drawer, int32 SlotIndex=INDEX_NONE)
Registers a drawer for the asset editor status bar.
UNREALED_API void RemoveAllToolbarWidgets ()
virtual UNREALED_API void RemoveEditingAsset (UObject *Asset) override
UNREALED_API void RemoveMenuExtender (TSharedPtr< FExtender > Extender)
UNREALED_API void RemoveToolbarExtender (TSharedPtr< FExtender > Extender)
virtual void RemoveViewportOverlayWidget (TSharedRef< SWidget > InViewportOverlayWidget)
Called when a toolkit requests the overlay widget to be removed.
UNREALED_API void RestoreFromLayout (const TSharedRef< FTabManager::FLayout > &NewLayout)
Applies the passed in layout (or the saved user-modified version if available).
UNREALED_API void SetMenuOverlay (TSharedRef< SWidget > Widget)
Allows the caller to set a menu overlay, displayed to the far right of the editor's menu bar.
UE_DEPRECATED (4.26, "Override CreateEditorModeManager on the toolkit class instead.") UNREALED_API void SetAssetEditorModeManager(class FAssetEditorModeManager *InModeManager)
Set the asset editor mode manager we are using.
UE_DEPRECATED (4.26, "Use GetEditorModeManager instead.") UNREALED_API class FAssetEditorModeManager *GetAssetEditorModeManager() const
Get the asset editor mode manager we are using.
UE_DEPRECATED (5.3, "Use CloseWindow that takes in an EAssetEditorCloseReason instead") UNREALED_API virtual bool CloseWindow() override
Public Member Functions inherited from IAssetEditorInstance
virtual bool IncludeAssetInRestoreOpenAssetsPrompt (UObject *Asset) const
virtual void InvokeTab (const struct FTabId &TabId)=0
UE_DEPRECATED (5.0, "Toolbar tab no longer exists and tab ID will return None; do not add it to layouts") virtual FName GetToolbarTabId() const
UE_DEPRECATED (5.3, "Use CloseWindow that takes in an EAssetEditorCloseReason instead") virtual bool CloseWindow()
UE_DEPRECATED (5.4, "Use the override that takes in an UObject instead") virtual bool IncludeAssetInRestoreOpenAssetsPrompt() const
If false, the asset being edited will not be included in reopen assets prompt on restart.
Public Member Functions inherited from FBaseToolkit
UNREALED_API FBaseToolkit ()
FBaseToolkit constructor.
virtual UNREALED_API ~FBaseToolkit ()
Virtual destructor.
virtual UNREALED_API void BringToolkitToFront () override
virtual UNREALED_API TSharedPtr< SWidget > GetInlineContent () const override
const TSharedRef< FUICommandList > GetToolkitCommands () const
virtual UNREALED_API const TSharedRef< IToolkitHost > GetToolkitHost () const override
virtual TSharedRef< FWorkspaceItem > GetWorkspaceMenuCategory () const override
virtual UNREALED_API bool IsHosted () const override
UNREALED_API bool IsWorldCentricAssetEditor () const
virtual UNREALED_API bool ProcessCommandBindings (const FKeyEvent &InKeyEvent) const override
Public Member Functions inherited from TSharedFromThis< FAssetEditorToolkit >
TSharedRef< FAssetEditorToolkit, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FAssetEditorToolkit, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Public Member Functions inherited from FGCObject
FGCObject ()
Tells the global object that forwards AddReferencedObjects calls on to objects that a new object is requiring AddReferencedObjects call.
FGCObject (const FGCObject &Other)
FGCObject (EFlags Flags)
FGCObject (FGCObject &&Other)
virtual ~FGCObject ()
virtual bool GetReferencerPropertyName (UObject *Object, FString &OutPropertyName) const
Overload this method to report how the specified object is referenced, if necessary.
FGCObject & operator= (const FGCObject &)
FGCObject & operator= (FGCObject &&)
void RegisterGCObject ()
Register with GC, only needed if constructed with EFlags::RegisterLater or after unregistering.
void UnregisterGCObject ()
Unregister ahead of destruction.
Public Member Functions inherited from FNotifyHook
virtual void NotifyPostChange (const FPropertyChangedEvent &PropertyChangedEvent, class FEditPropertyChain *PropertyThatChanged)
virtual void NotifyPreChange (class FEditPropertyChain *PropertyAboutToChange)
Public Member Functions inherited from FTickableEditorObject
FTickableEditorObject ()
Registers this instance with the static array of tickable objects.
virtual ~FTickableEditorObject ()
Removes this instance from the static array of tickable objects.
UE_NONCOPYABLE (FTickableEditorObject)
Public Member Functions inherited from FTickableObjectBase
virtual bool IsTickable () const
Virtual that can be overloaded by the inheriting class.
UE_DEPRECATED (5.5, "Use IsTickable for conditional ticks and SetTickableTickType to change the tick type after initial registration") virtual bool IsAllowedToTick() const
Function called before IsTickable, used to change rules without breaking existing API.
Public Member Functions inherited from FEditorUndoClient
virtual UNREALED_API ~FEditorUndoClient ()
Always unregister for undo on destruction, just in case.
virtual FString GetTransactionContext () const
Return the transaction context for this client.
virtual bool MatchesContext (const FTransactionContext &InContext, const TArray< TPair< UObject *, FTransactionObjectEvent > > &TransactionObjectContexts) const
Called to see if the context of the current undo/redo operation is a match for the client Default state matching old context-less undo is Context="" and PrimaryObject=NULL.
Static Public Member Functions
static FName GetContextFromBlueprintType (EBlueprintType InType)
Get the context to use from the Blueprint type.
static const FSlateBrush * GetGlyphForGraph (const UEdGraph *Graph, bool bInLargeIcon=false)
Util for finding a glyph for a graph.
static FText GetGraphDisplayName (const UEdGraph *Graph)
Gets the display name of a graph.
static FSlateBrush const * GetVarIconAndColor (const UStruct *VarScope, FName VarName, FSlateColor &IconColorOut, FSlateBrush const *&SecondaryBrushOut, FSlateColor &SecondaryColorOut)
Util for finding a glyph and color for a variable.
static FSlateBrush const * GetVarIconAndColorFromPinType (const FEdGraphPinType &PinType, FSlateColor &IconColorOut, FSlateBrush const *&SecondaryBrushOut, FSlateColor &SecondaryColorOut)
Util for finding a glyph and color for a variable.
static FSlateBrush const * GetVarIconAndColorFromProperty (const FProperty *Property, FSlateColor &IconColorOut, FSlateBrush const *&SecondaryBrushOut, FSlateColor &SecondaryColorOut)
Util for finding a glyph and color for a variable.
Static Public Member Functions inherited from FWorkflowCentricApplication
static TArray< FWorkflowApplicationModeExtender > & GetModeExtenderList ()
Static Public Member Functions inherited from FAssetEditorToolkit
static UNREALED_API FText GetLabelForObject (const UObject *InObject)
Gets the text to display in a toolkit titlebar for an object.
static UNREALED_API TSharedPtr< FExtensibilityManager > GetSharedMenuExtensibilityManager ()
Returns the default extensibility managers, these are applied for all asset types.
static UNREALED_API TSharedPtr< FExtensibilityManager > GetSharedToolBarExtensibilityManager ()
static UNREALED_API FText GetToolTipTextForObject (const UObject *InObject)
Gets the text to display in a toolkit tooltip for an object.
static UNREALED_API void RegisterDefaultToolBar ()
Registers default tool bar.
static UNREALED_API void SetPreviousWorldCentricToolkitHostForNewAssetEditor (TSharedRef< IToolkitHost > ToolkitHost)
Static: Used internally to set the world-centric toolkit host for a newly-created standalone asset editing toolkit.
Static Public Member Functions inherited from FGCObject
static void StaticInit ()
Initializes the global object referencer and adds it to the root set.
Static Public Member Functions inherited from FTickableEditorObject
static void TickObjects (const float DeltaSeconds)
Calls Tick on every tickable editor object with tick enabled.
Data Fields
UEdGraphPin bool bInToMemberVariable
TSharedPtr< FDocumentTracker > DocumentManager
UEdGraphPin bool const FVector2D * InOptionalLocation = nullptr)
const FVector2D & InPosition
UEdGraphPin * InTargetPin
bool IsCntrlDown override { return nullptr
const FVector2D UEdGraph *InGraph UE_SLATE_DEPRECATED_VECTOR_VIRTUAL_FUNCTION
Data Fields inherited from IBlueprintEditor
bool IsCntrlDown = 0
const FVector2D &Location UE_SLATE_DEPRECATED_VECTOR_VIRTUAL_FUNCTION { PasteNodesHere(Graph, UE::Slate::CastToVector2f(Location))
Static Public Attributes
static FName SelectionState_ClassDefaults
static FName SelectionState_ClassSettings
static FName SelectionState_Components
static FName SelectionState_Graph
static FName SelectionState_MyBlueprint
Static Public Attributes inherited from FGCObject
static UGCObjectReferencer * GGCObjectReferencer
The static object referencer object that is shared across all garbage collectible non-UObject objects.
Protected Member Functions
bool CanAddBreakpoint () const
bool CanAddExecutionPin () const
bool CanAddOptionPin () const
bool CanAddParentNode () const
bool CanAssignReferencedActor () const
bool CanChangePinType () const
bool CanCollapseNodes () const
bool CanCollapseSelectionToFunction () const
bool CanCollapseSelectionToFunction (TSet< class UEdGraphNode * > &InSelection) const
Called when a selection of nodes is being collapsed into a function.
bool CanCollapseSelectionToMacro () const
bool CanCollapseSelectionToMacro (TSet< class UEdGraphNode * > &InSelection) const
Called when a selection of nodes is being collapsed into a macro.
bool CanConvertEventToFunction () const
bool CanConvertFunctionToEvent () const
Callback function for the context menu on a node to determine if a function could possibly be converted to an event.
virtual bool CanCopyNodes () const
bool CanCreateMatchingFunction () const
virtual bool CanCutNodes () const
virtual bool CanDeleteNodes () const
bool CanDisableBreakpoint () const
bool CanDuplicateNodes () const
bool CanEnableBreakpoint () const
bool CanExpandNodes () const
bool CanInsertExecutionPin () const
bool CanNavigateToChildGraph () const
bool CanNavigateToParentGraph () const
bool CanOpenBlueprintDebugger () const
virtual bool CanPasteGeneric () const
virtual bool CanPasteNodes () const override
bool CanPromoteSelectionToFunction () const
bool CanPromoteSelectionToMacro () const
bool CanPromoteToVariable (bool bInToMemberVariable) const
bool CanRecombineStructPin () const
bool CanRedoGraphAction () const
Whether or not we can redo an undone action.
bool CanRemoveBreakpoint () const
bool CanRemoveExecutionPin () const
bool CanRemoveOptionPin () const
bool CanRemoveOtherStructVarPins () const
bool CanRemoveThisStructVarPin () const
bool CanRenameNodes () const
bool CanResetPinToDefaultValue () const
bool CanRestoreAllStructVarPins () const
bool CanSelectAllNodes () const
bool CanSelectReferenceInLevel () const
bool CanSplitStructPin () const
virtual bool CanStartWatchingPin () const
virtual bool CanStopWatchingPin () const
bool CanToggleBreakpoint () const
bool CanUndoGraphAction () const
Whether or not we can perform an undo of the last transacted action.
bool CanZoomToSelection () const
bool CanZoomToWindow () const
void ClearAllBreakpoints ()
Deletes all breakpoints for the blueprint being edited.
void ClearAllGraphEditorQuickJumps ()
Unbinds all graph editor "quick jump" commands.
void ClearAllWatches ()
Clears all watches associated with the blueprint being edited.
void ClearGraphEditorQuickJump (int32 BookmarkIndex)
Unbinds a graph editor "quick jump" from the command at the given index.
void CollapseNodes (TSet< class UEdGraphNode * > &InCollapsableNodes)
Called when a selection of nodes are being collapsed into a sub-graph.
void CollapseNodesIntoGraph (UEdGraphNode *InGatewayNode, class UK2Node_EditablePinBase *InEntryNode, class UK2Node_EditablePinBase *InResultNode, UEdGraph *InSourceGraph, UEdGraph *InDestinationGraph, TSet< UEdGraphNode * > &InCollapsableNodes, bool bCanDiscardEmptyReturnNode, bool bCanHaveWeakObjPtrParam)
Collapses a selection of nodes into a graph for composite, function, or macro nodes.
UEdGraph * CollapseSelectionToFunction (TSharedPtr< SGraphEditor > InRootGraph, TSet< class UEdGraphNode * > &InCollapsableNodes, UEdGraphNode *&OutFunctionNode)
Called when a selection of nodes are being collapsed into a function.
UEdGraph * CollapseSelectionToMacro (TSharedPtr< SGraphEditor > InRootGraph, TSet< class UEdGraphNode * > &InCollapsableNodes, UEdGraphNode *&OutMacroNode)
Called when a selection of nodes are being collapsed into a macro.
void CollectExecDownstreamNodes (UEdGraphNode *CurrentNode, TArray< UEdGraphNode * > &CollectedNodes)
void CollectExecUpstreamNodes (UEdGraphNode *CurrentNode, TArray< UEdGraphNode * > &CollectedNodes)
void CollectPureDownstreamNodes (UEdGraphNode *CurrentNode, TArray< UEdGraphNode * > &CollectedNodes)
void CollectPureUpstreamNodes (UEdGraphNode *CurrentNode, TArray< UEdGraphNode * > &CollectedNodes)
void ConvertEventToFunction (UK2Node_Event *SelectedEventNode)
void ConvertFunctionToEvent (UK2Node_FunctionEntry *SelectedCallFunctionNode)
virtual void CopySelectedNodes ()
virtual void CreateDefaultCommands ()
Create Default Commands.
virtual void CreateDefaultTabContents (const TArray< UBlueprint * > &InBlueprints)
Creates the widgets that go into the tabs (note: does not create the tabs themselves)
virtual TSharedRef< SGraphEditor > CreateGraphEditorWidget (TSharedRef< class FTabInfo > InTabInfo, class UEdGraph *InGraph)
TSharedRef< SWidget > CreateGraphTitleBarWidget (TSharedRef< FTabInfo > InTabInfo, UEdGraph *InGraph)
Create a graph title bar widget.
virtual void CutSelectedNodes ()
void DeleteSelectedDuplicatableNodes ()
virtual void DeleteSelectedNodes ()
void DeleteUnusedVariables_OnClicked ()
Called when DeleteUnusedVariables button is clicked.
void DisableAllBreakpoints ()
Disables all breakpoints for the blueprint being edited.
void DuplicateNodes ()
void EditClassDefaults_Clicked ()
Edit the class defaults.
void EditGlobalOptions_Clicked ()
Edit the class settings aka Blueprint global options.
void EnableAllBreakpoints ()
Enables all breakpoints for the blueprint being edited.
void ExtractEventTemplateForFunction (class UK2Node_CustomEvent *InCustomEvent, UEdGraphNode *InGatewayNode, class UK2Node_EditablePinBase *InEntryNode, class UK2Node_EditablePinBase *InResultNode, TSet< UEdGraphNode * > &InCollapsableNodes)
Pulls out the pins to use as a template when collapsing a selection to a function with a custom event involved.
void FindInBlueprint_Clicked ()
Called to start a quick find (focus the search box in the explorer tab)
void FindInBlueprints_OnClicked ()
Called when Find In Blueprints menu is opened is clicked.
TArray< UEdGraphNode * > GetAllConnectedNodes (UEdGraphNode *const Node) const
Get all connected nodes and add them to a set of out nodes.
virtual bool GetBoundsForSelectedNodes (class FSlateRect &Rect, float Padding) override
FGraphAppearanceInfo GetCurrentGraphAppearance () const
Get the graph appearance of the currently focused graph.
UEdGraphPin * GetCurrentlySelectedPin () const
virtual TSubclassOf< UEdGraphSchema > GetDefaultSchemaClass () const
Whenever new graphs need to be created it will use this schema by default.
EVisibility GetEditParentClassVisibility () const
Determines visibility of the edit parent class button on the menu bar overlay.
EVisibility GetFindParentClassVisibility () const
Determines visibility of the find parent class in content browser button on the menu bar overlay.
virtual FGraphAppearanceInfo GetGraphAppearance (class UEdGraph *InGraph) const
Get the graph appearance of a specific graph, GetCurrentGraphAppearance() uses the currently focused graph.
FText GetParentClassNameText () const
Returns the name of the Blueprint's parent class.
bool GetSaveIntermediateBuildProducts () const
bool HasAnyBreakpoints () const
bool HasAnyDisabledBreakpoints () const
bool HasAnyEnabledBreakpoints () const
bool HasAnyWatches () const
void HideUnrelatedNodes ()
virtual void InitalizeExtenders ()
Called during initialization of the blueprint editor to register commands and extenders.
bool IsDetailsPanelEditingClassDefaults () const
bool IsDetailsPanelEditingGlobalOptions () const
void LoadLibrariesFromAssetRegistry ()
Load macro & function blueprint libraries from asset registry.
void MoveNodesToAveragePos (TSet< UEdGraphNode * > &AverageNodes, FVector2D SourcePos, bool bExpandedNodesNeedUniqueGuid=false) const
Move the given set of nodes to an average spot near the Source position.
void NavigateToChildGraph ()
void NavigateToParentGraph ()
void NavigateToParentGraphByDoubleClick ()
virtual void NotifyPostChange (const FPropertyChangedEvent &PropertyChangedEvent, FProperty *PropertyThatChanged) override
virtual void NotifyPreChange (FProperty *PropertyAboutToChange) override
void OnAddBreakpoint ()
void OnAddExecutionPin ()
void OnAddOptionPin ()
void OnAddParentNode ()
void OnAlignBottom ()
void OnAlignCenter ()
void OnAlignLeft ()
void OnAlignMiddle ()
void OnAlignRight ()
void OnAlignTop ()
void OnAssignReferencedActor ()
void OnBlueprintChanged (UBlueprint *InBlueprint)
Called when the Blueprint we are editing has changed, forwards to impl.
virtual void OnBlueprintChangedImpl (UBlueprint *InBlueprint, bool bIsJustBeingCompiled=false)
Called when the Blueprint we are editing has changed.
void OnBlueprintCompiled (UBlueprint *InBlueprint)
void OnBlueprintUnloaded (UBlueprint *InBlueprint)
Handles the unloading of Blueprints (by closing the editor, if it operating on the Blueprint being unloaded)
void OnChangePinType ()
void OnChangePinTypeFinished (const FEdGraphPinType &PinType, UEdGraphPin *SelectedPin)
void OnCollapseNodes ()
void OnCollapseSelectionToFunction ()
void OnCollapseSelectionToMacro ()
void OnConvertEventToFunction ()
void OnConvertFunctionToEvent ()
virtual void OnCreateComment ()
virtual void OnCreateCustomEvent ()
Create custom event node on graph.
FActionMenuContent OnCreateGraphActionMenu (UEdGraph *InGraph, const FVector2f &InNodePosition, const TArray< UEdGraphPin * > &InDraggedPins, bool bAutoExpand, SGraphEditor::FActionMenuClosed InOnMenuClosed)
void OnCreateMatchingFunction ()
void OnDisableBreakpoint ()
void OnDistributeNodesH ()
void OnDistributeNodesV ()
FReply OnEditParentClassClicked ()
Handler for "Edit parent class" button.
virtual void OnEditTabClosed (TSharedRef< SDockTab > Tab)
void OnEnableBreakpoint ()
void OnExpandNodes ()
FReply OnFindParentClassInContentBrowserClicked ()
Handler for "Find parent class in CB" button.
virtual void OnFinishedChangingProperties (const FPropertyChangedEvent &PropertyChangedEvent)
Callback when properties have finished being handled.
FEdGraphPinType OnGetPinType (UEdGraphPin *SelectedPin) const
Functions for handling the changing of the pin's type (PinCategory, PinSubCategory, etc)
void OnGraphActionMenuClosed (bool bActionExecuted, bool bContextSensitiveChecked, bool bGraphPinContext)
Called from graph context menus when they close to tell the editor why they closed.
void OnGraphEditorDropActor (const TArray< TWeakObjectPtr< AActor > > &Actors, UEdGraph *Graph, const FVector2f &DropLocation)
Called when an actor is dropped onto the graph editor.
void OnGraphEditorDropStreamingLevel (const TArray< TWeakObjectPtr< ULevelStreaming > > &Levels, UEdGraph *Graph, const FVector2f &DropLocation)
Called when a streaming level is dropped onto the graph editor.
void OnGraphEditorQuickJump (int32 BookmarkIndex)
Handles activation of a graph editor "quick jump" command.
void OnInsertExecutionPin (EPinInsertPosition Position)
void OnInsertExecutionPinAfter ()
void OnInsertExecutionPinBefore ()
void OnListObjectsReferencedByBlueprint ()
void OnListObjectsReferencedByClass ()
void OnNodeDoubleClicked (UEdGraphNode *Node)
bool OnNodeVerifyTitleCommit (const FText &NewText, UEdGraphNode *NodeBeingChanged, FText &OutErrorMessage)
Called when a node's title is being committed for a rename so it can be verified.
void OnPostObjectPropertyChanged (UObject *InObject, FPropertyChangedEvent &PropertyChangedEvent)
Called after a property change has been propagated to instances of the Blueprint.
void OnPreObjectPropertyChanged (UObject *InObject, const FEditPropertyChain &EditPropertyChain)
Called when a property change is about to be propagated to instances of the Blueprint.
void OnPromoteSelectionToFunction ()
void OnPromoteSelectionToMacro ()
void OnPromoteToVariable (bool bInToMemberVariable)
void OnRecombineStructPin ()
void OnRemoveBreakpoint ()
void OnRemoveExecutionPin ()
void OnRemoveOptionPin ()
void OnRemoveOtherStructVarPins ()
void OnRemoveThisStructVarPin ()
void OnRenameNode ()
On starting to rename node.
void OnRepairCorruptedBlueprint ()
void OnResetPinToDefaultValue ()
void OnRestoreAllStructVarPins ()
void OnSelectedNodesChanged (const TSet< class UObject * > &NewSelection)
Called when the selection changes in the GraphEditor.
virtual void OnSelectedNodesChangedImpl (const TSet< class UObject * > &NewSelection)
Called when the selection changes in the GraphEditor.
void OnSelectReferenceInLevel ()
void OnSplitStructPin ()
void OnStackNodesH ()
void OnStackNodesV ()
void OnStartEditingDefaultsClicked ()
Start editing the defaults for this blueprint.
virtual void OnStartWatchingPin ()
virtual void OnStopWatchingPin ()
void OnStraightenConnections ()
void OnToggleBreakpoint ()
void OpenBlueprintDebugger ()
Spawns a new blueprint debugger tab.
virtual void PasteGeneric ()
Paste Variable Definition or Nodes.
virtual void PasteNodes ()
virtual void PasteNodesHere (class UEdGraph *DestinationGraph, const FVector2f &GraphLocation) override
Paste on graph at specific location.
virtual void PostRedo (bool bSuccess) override
Signal that client should run any PostRedo code.
virtual void PostRegenerateMenusAndToolbars () override
Recreates the overlay on the menu bar.
virtual void PostUndo (bool bSuccess) override
Signal that client should run any PostUndo code.
void ReconnectExecPins (class UK2Node *Node)
Given a node, make connections from anything connected to it's input pin to anything connected to it's "then" pins.
void RedoGraphAction ()
Called to redo the last undone action.
void RefreshStandAloneDefaultsEditor ()
virtual void RegisterApplicationModes (const TArray< UBlueprint * > &InBlueprints, bool bShouldOpenInDefaultsMode, bool bNewlyCreated=false)
Called during initialization of the blueprint editor to register any application modes.
void RegisterMenus ()
Register Menus.
void ResetAllNodesUnrelatedStates ()
Focus nodes which are related to the selected nodes.
void SelectAllNodes ()
void SetGraphEditorQuickJump (int32 BookmarkIndex)
Binds a graph editor "quick jump" to the command at the given index.
virtual void SetupGraphEditorEvents (UEdGraph *InGraph, SGraphEditor::FGraphEditorEvents &InEvents)
Setup all the events that the graph editor can handle.
bool ShouldShowPublicViewControl () const
Callback to determine visibility of the public view checkbox in the Defaults editor.
void ToggleSaveIntermediateBuildProducts ()
void TryInvokingDetailsTab (bool bFlash=true)
Attempts to invoke the details tab if it's currently possible to.
UE_DEPRECATED (5.6, "Please use the version of the function taking FVector2f.") FActionMenuContent OnCreateGraphActionMenu(UEdGraph *InGraph
Called to create context menu when right-clicking on graph.
void UndoGraphAction ()
Called to undo the last action.
void ZoomToSelection_Clicked ()
void ZoomToWindow_Clicked ()
Protected Member Functions inherited from FWorkflowCentricApplication
virtual UNREALED_API void AddApplicationMode (FName ModeName, TSharedRef< FApplicationMode > Mode)
virtual UNREALED_API const TMap< FName, TSharedPtr< FApplicationMode > > & GetApplicationModeList () const
virtual UNREALED_API void RemoveAllApplicationModes ()
virtual UNREALED_API bool RemoveApplicationMode (FName ModeName)
Protected Member Functions inherited from FAssetEditorToolkit
virtual UNREALED_API void AddEditingObject (UObject *Object)
Adds an item to the Editing Objects list.
virtual UNREALED_API void BrowseDocumentation_Execute () const
Called when "Browse Documentation" is clicked for this asset.
virtual bool CanFindInContentBrowser () const
Called to test if "Find in Content Browser" should be enabled for this asset.
virtual UNREALED_API bool CanReimport () const
Called to check to see if there's an asset capable of being reimported.
virtual UNREALED_API bool CanReimport (UObject *EditingObject) const
bool CanReimport_Internal () const
Internal function to check if the asset can be reimported that calls CanReimport.
virtual bool CanSaveAsset () const
Called to test if "Save" should be enabled for this asset.
bool CanSaveAsset_Internal () const
Internal function to check if the asset can be saved that calls CanSaveAsset.
virtual bool CanSaveAssetAs () const
Called to test if "Save As" should be enabled for this asset.
bool CanSaveAssetAs_Internal () const
Internal function to check if the asset can be saved that calls CanSaveAssetAs.
virtual UNREALED_API void CreateEditorModeManager () override
virtual UNREALED_API void FindInContentBrowser_Execute ()
Called when "Find in Content Browser" is clicked for this asset.
virtual UNREALED_API UToolMenu * GenerateCommonActionsToolbar (FToolMenuContext &MenuContext)
Generate the toolbar for common asset actions like Save.
UToolMenu * GenerateReadOnlyToolbar (FToolMenuContext &MenuContext)
Generate the toolbar for read only mode specific content.
virtual UNREALED_API FLinearColor GetDefaultTabColor () const
virtual UNREALED_API const FSlateBrush * GetDefaultTabIcon () const
UNREALED_API UObject * GetEditingObject () const
Returns the single object currently being edited.
UNREALED_API TArray< TObjectPtr< UObject > > & GetEditingObjectPtrs ()
UNREALED_API const TArray< UObject * > & GetEditingObjects () const
Returns an array of all the objects currently being edited.
virtual UNREALED_API FName GetReadOnlyMenuProfileName ()
Get the name of the profile registered with UToolMenus for read only menu customizations.
virtual UNREALED_API void GetSaveableObjects (TArray< UObject * > &OutObjects) const
Get the collection of edited objects that can be saved.
virtual UNREALED_API EVisibility GetVisibilityWhileAssetCompiling () const
Called to get the desired visibility when the asset is compiling.
bool HasEditingObject () const
Returns true if this toolkit has any objects being edited.
virtual bool IsFindInContentBrowserButtonVisible () const
Called to test if "Find in Content Browser" should be visible for this asset.
virtual UNREALED_API bool IsSaveAssetAsVisible () const
Called to test if "Save As" should be visible for this asset.
virtual UNREALED_API bool IsSaveAssetVisible () const
Called to test if "Save" should be visible for this asset.
virtual UNREALED_API void MapToolkitCommands ()
Can be overriden to prevent registering the default commands.
virtual void OnAssetsSaved (const TArray< UObject * > &SavedObjects)
Called from SaveAsset_Execute when assets have been saved.
virtual void OnAssetsSavedAs (const TArray< UObject * > &SavedObjects)
Called from SaveAssetAs_Execute when assets have been saved.
virtual void PostInitAssetEditor ()
Perform any initialization that should happen after the basic toolkit needs are created for the asset editor.
virtual UNREALED_API void Reimport_Execute ()
Called when "Reimport" is clicked for this asset.
virtual UNREALED_API void Reimport_Execute (UObject *EditingObject)
virtual UNREALED_API void RemoveEditingObject (UObject *Object)
Removes an item from the Editing Objects list.
UNREALED_API void RestoreFromLayout (const TSharedRef< FTabManager::FLayout > &NewLayout, bool bLoadUserLayout)
Applies the passed in layout.
virtual UNREALED_API void SaveAsset_Execute ()
Called when "Save" is clicked for this asset.
virtual UNREALED_API void SaveAssetAs_Execute ()
Called when "Save As" is clicked for this asset.
virtual UNREALED_API void SetupReadOnlyMenuProfiles (FReadOnlyAssetEditorCustomization &OutReadOnlyCustomization)
Specify the permission lists to use in read only mode.
virtual UNREALED_API bool ShouldPromptForNewFilesOnReload (const UObject &object) const
Called to determine if the user should be prompted for a new file if one is missing during an asset reload.
virtual bool ShouldReopenEditorForSavedAsset (const UObject *Asset) const
Whether to open a new asset editor for the newly-saved Asset.
UE_DEPRECATED (4.26, "Use EditorModeManager instead.") FAssetEditorModeManager *AssetEditorModeManager
UE_DEPRECATED (5.3, "Use OnRequestClose that takes in an EAssetEditorCloseReason instead") virtual bool OnRequestClose()
Called when this toolkit is requested to close.
Protected Member Functions inherited from FBaseToolkit
UNREALED_API FLinearColor GetTabColorScale () const
UNREALED_API FString GetTabPrefix () const
Protected Member Functions inherited from TSharedFromThis< FAssetEditorToolkit >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Protected Member Functions inherited from FNoncopyable
FNoncopyable ()
~FNoncopyable ()
Static Protected Member Functions
static void ExpandNode (UEdGraphNode *InNodeToExpand, UEdGraph *InSourceGraph, TSet< UEdGraphNode * > &OutExpandedNodes)
Expands passed in node.
static void MoveNodesToGraph (TArray< UEdGraphNode * > &SourceNodes, UEdGraph *DestinationGraph, TSet< UEdGraphNode * > &OutExpandedNodes, UEdGraphNode **OutEntry, UEdGraphNode **OutResult, const bool bIsCollapsedGraph=false)
Move every node from the source graph to the destination graph.
Static Protected Member Functions inherited from FAssetEditorToolkit
static UNREALED_API void SwitchToStandaloneEditor_Execute (TWeakPtr< FAssetEditorToolkit > ThisToolkitWeakRef)
Static: Called when "Switch to Standalone Editor" is clicked for the asset editor.
static UNREALED_API void SwitchToWorldCentricEditor_Execute (TWeakPtr< FAssetEditorToolkit > ThisToolkitWeakRef)
Static: Called when "Switch to World-Centric Editor" is clicked for the asset editor.
Static Protected Member Functions inherited from TSharedFromThis< FAssetEditorToolkit >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Static Protected Member Functions inherited from FTickableObjectBase
static void SimpleTickObjects (FTickableStatics &Statics, TFunctionRef< void(FTickableObjectBase *)> TickFunc)
Perform a simple tick using a class-specific statics struct and a function ref.
Protected Attributes
const FVector2D const TArray< UEdGraphPin * > bool bAutoExpand
bool bBlueprintModifiedOnOpen
Did we update the blueprint when it opened.
bool bEditorMarkedAsClosed
Whether we are already in the process of closing this editor.
bool bHideUnrelatedNodes
If true, fade out nodes which are unrelated to the selected nodes automatically.
bool bIsActionMenuContextSensitive
Whether the graph action menu should be sensitive to the pins dragged off of.
bool bIsReparentingBlueprint
True if the current blueprint is in the process of being reparented.
bool bLockNodeFadeState
Lock the current fade state of each node.
TSharedPtr< class SBlueprintBookmarks > BookmarksWidget
Blueprint bookmark editing widget.
bool bPendingDeferredClose
Flags if this blueprint editor should close on its next tick.
bool bRequestedSavingOpenDocumentState
Has someone requested a deferred update of the saved document state?
bool bSaveIntermediateBuildProducts
Should intermediate build products be saved when recompiling?
bool bSelectRegularNode
If a regular node (not a comment node) has been selected.
bool bWasOpenedInDefaultsMode
True if the editor was opened in defaults mode.
int32 CachedNumErrors
int32 CachedNumWarnings
Limited cache of last compile results.
TSharedPtr< class SWidget > CompilerResults
Compiler results log, with the log listing that it reflects.
TSharedPtr< class IMessageLogListing > CompilerResultsListing
TSharedPtr< class IPinTypeSelectorFilter > CompositePinTypeSelectorFilter
Filter used to compose multiple pin type filters together.
FName CurrentUISelection
The current UI selection state of this editor.
TSharedPtr< class SKismetInspector > DefaultEditor
defaults inspector widget
TSet< FString > DeferredNamespaceImports
Pending set of namespaces to be auto-imported on the next tick.
TSharedPtr< class SFindInBlueprints > FindResults
Find results log as well as the search filter.
TWeakPtr< class SGraphEditor > FocusedGraphEdPtr
Currently focused graph editor.
TWeakPtr< FDocumentTabFactory > GraphEditorTabFactoryPtr
Factory that spawns graph editors; used to look up all tabs spawned by it.
TSharedPtr< class IClassViewerFilter > ImportedClassViewerFilter
Filter used to restrict class viewer widgets in the editor context to imported namespaces only.
TSharedPtr< FBlueprintNamespaceHelper > ImportedNamespaceHelper
Imported namespace helper utility object.
TSharedPtr< class IPinTypeSelectorFilter > ImportedPinTypeSelectorFilter
Filter used to restrict pin type selector widgets in the editor context to imported namespaces only.
const FVector2D const TArray< UEdGraphPin * > & InDraggedPins
const FVector2D & InNodePosition
const FVector2D const TArray< UEdGraphPin * > bool SGraphEditor::FActionMenuClosed InOnMenuClosed
TSharedPtr< class SKismetInspector > Inspector
Node inspector widget.
TWeakPtr< class SDockTab > MergeTool
Merge tool - WeakPtr because it's owned by the GlobalTabManager.
TSharedPtr< class SMyBlueprint > MyBlueprintWidget
All of this blueprints' functions and variables.
TWeakPtr< class SWindow > NameEntryPopupWindow
Reference to owner of the current popup.
TSharedPtr< class INameValidatorInterface > NameEntryValidator
Reference to helper object to validate names in popup.
FOnMergeResolved OnMergeResolved
Merge tool - Delegate to call when the merge tool is closed.
FOnSetPinVisibility OnSetPinVisibility
TSharedPtr< class SBlueprintPalette > Palette
Palette of all classes with funcs/vars.
TSharedPtr< class IPinTypeSelectorFilter > PermissionsPinTypeSelectorFilter
Filter used to restrict pin type selector widgets to those which permissions allow.
TWeakPtr< class IMenu > PinTypeChangeMenu
Reference to owner of the pin type change popup.
SGraphEditor::EPinVisibility PinVisibility
Whether to hide unused pins or not.
TWeakObjectPtr< AActor > PreviewActorPtr
The preview actor representing the current preview.
FPreviewScene PreviewScene
Blueprint preview scene.
TSharedPtr< class SReplaceNodeReferences > ReplaceReferencesWidget
Widget for replacing node references.
TArray< TObjectPtr< UBlueprint > > StandardLibraries
Macro/function libraries to keep loaded.
TSharedPtr< SSubobjectEditor > SubobjectEditor
Subobject Editor.
TSharedPtr< SSCSEditorViewport > SubobjectViewport
Viewport widget.
TSharedPtr< class FBlueprintEditorToolbar > Toolbar
The toolbar builder class.
TSet< TWeakObjectPtr< UUserDefinedEnum > > UserDefinedEnumerators
User-defined enumerators to keep loaded.
TSet< TWeakObjectPtr< UUserDefinedStruct > > UserDefinedStructures
User-defined structures to keep loaded.
Protected Attributes inherited from FWorkflowCentricApplication
TSharedPtr< FApplicationMode > CurrentAppModePtr
Protected Attributes inherited from FAssetEditorToolkit
TSharedPtr< FWorkspaceItem > AssetEditorTabsCategory
The base category that tabs are registered to, allows for child classes to register to the same point.
bool bCheckDirtyOnAssetSave
Whether only dirty assets should be prompted about on save - otherwise all edited assets will be prompted to the user for save/check-out.
TSharedPtr< FEditorModeTools > EditorModeManager
The editor mode manager.
TArray< TSharedPtr< FLayoutExtender > > LayoutExtenders
Array of layout extenders.
FString LayoutIni = GEditorLayoutIni
What ini file should be used to persist and restore the user's layout.
TWeakPtr< IToolkitHost > PreviousWorldCentricToolkitHost
For standalone asset editing tool-kits that were switched from world-centric mode on the fly, this stores the toolkit host (level editor) that hosted this toolkit last.
TSharedPtr< FTabManager > TabManager
Controls our internal layout.
Protected Attributes inherited from FBaseToolkit
TSharedRef< FUICommandList > ToolkitCommands
List of UI commands for this toolkit.
TWeakPtr< IToolkitHost > ToolkitHost
The host application for this editor.
EToolkitMode::Type ToolkitMode
Asset editing mode, set at creation-time and never changes.
TSharedPtr< FWorkspaceItem > WorkspaceMenuCategory
The workspace menu category of this toolkit.
Private Types
enum class ESafeToModifyDuringPIEStatus { Unknown , Safe , NotSafe }
Private Member Functions
void BroadcastRefresh ()
Broadcast notification for associated controls to update.
bool CanFindReferences ()
Checks if we can currently find all references of the node selection.
bool CanGoToDefinition () const
Checks to see if it is possible to jump to the selected node's definition.
bool CanGoToDocumentation ()
Can we open documentation for the selected node.
ECheckBoxState CheckEnabledStateForSelectedNodes (ENodeEnabledState CheckState)
Attempt to match the given enabled state for currently-selected nodes.
void CreateSubobjectEditors ()
Creates the Subobject Editor tree component view and the Subobject Viewport.
DECLARE_MULTICAST_DELEGATE_OneParam (FOnSetPinVisibility, SGraphEditor::EPinVisibility)
FString GetDocLinkBaseUrlForSelectedNode ()
Util to try and get the base URL for the doc link for the currently selected node.
FString GetDocLinkForSelectedNode ()
Util to try and get doc link for the currently selected node.
ECheckBoxState GetEnabledCheckBoxStateForSelectedNodes ()
Returns the appropriate check box state representing whether or not the selected nodes are enabled.
void HandleUndoTransaction (const class FTransaction *Transaction)
Handle undo/redo.
bool IsEditingAnimGraph () const
Checks to see if the focused Graph-Editor is focused on a animation graph or not.
bool IsFocusedGraphEditable () const
Returns whether the currently focused graph is editable or not.
virtual void LoadEditorSettings ()
Load editor settings from disk (docking state, window pos/size, option state, etc).
void NavigateTab (FDocumentTracker::EOpenDocumentCause InCause)
Helper function to navigate the current tab.
virtual void OnBlueprintEditorPreferencesChanged (UObject *, struct FPropertyChangedEvent &)
virtual void OnBlueprintProjectSettingsChanged (UObject *, struct FPropertyChangedEvent &)
void OnChangeBreadCrumbGraph (class UEdGraph *InGraph)
Helper to move focused graph when clicking on graph breadcrumb.
virtual void OnCreateGraphEditorCommands (TSharedPtr< FUICommandList > GraphEditorCommandsList)
void OnDisallowedPinConnection (const class UEdGraphPin *PinA, const class UEdGraphPin *PinB)
Called when the user generates a warning tooltip because a connection was invalid.
void OnEditTunnel ()
void OnFindReferences (bool bSearchAllBlueprints, const EGetFindReferenceSearchStringFlags Flags)
Find all references of the selected node.
void OnGoToDefinition ()
Called when the user wants to jump to a node's definition.
void OnGoToDocumentation ()
Open documentation for the selected node class.
void OnLogTokenClicked (const TSharedRef< class IMessageToken > &Token)
Callback when a token is clicked on in the compiler results log.
void OnSetEnabledStateForSelectedNodes (ENodeEnabledState NewState)
Set the enabled state for currently-selected nodes.
virtual void SaveEditorSettings ()
Saves editor settings to disk (docking state, window pos/size, option state, etc).
Static Private Member Functions
static bool CanRecompileModules ()
Returns true if modules can be recompiled.
static bool IsASubGraph (const class UEdGraph *GraphPtr)
Function to check whether the give graph is a subgraph.
Private Attributes
FAnalyticsStatistics AnalyticsStats
analytics statistics for the Editor
bool bCodeBasedProject
Whether the current project is C++ or blueprint based.
FDelegateHandle BlueprintEditorSettingsChangedHandle
Delegate handle registered for when settings change.
FDelegateHandle BlueprintProjectSettingsChangedHandle
TSharedPtr< FUICommandList > GraphEditorCommands
Command list for the graph editor.
UEdGraph * HasOpenActionMenu
When set, flags which graph has a action menu currently open (if null, no graphs do).
float InstructionsFadeCountdown
Used to nicely fade instruction text, when the context menu is opened.
ESafeToModifyDuringPIEStatus ModifyDuringPIEStatus = ESafeToModifyDuringPIEStatus::Unknown
FDelegateHandle OnActiveTabChangedDelegateHandle
Handle to the registered OnActiveTabChanged delegate.
FOnModeSet OnModeSetData
Delegates that are fired when the blueprint editor changes modes.
FOnRefreshEvent RefreshEvent
Notification used whenever the editor wants associated controls to refresh.
TMap< FName, TSharedPtr< ISCSEditorCustomization > > SubobjectEditorCustomizations
Customizations for the Subobject editor.
TUniquePtr< FEditorViewportSelectabilityBridge > ViewportSelectabilityBridge
Detailed Description
Main Kismet asset editor.
Definition at line 210 of file BlueprintEditor.h.
Member Enumeration Documentation
ECreatedDocumentType
enum FBlueprintEditor::ECreatedDocumentType
Enumerator
CGT_NewVariable
CGT_NewFunctionGraph
CGT_NewMacroGraph
CGT_NewAnimationLayer
CGT_NewEventGraph
CGT_NewLocalVariable
Definition at line 617 of file BlueprintEditor.h.
ESafeToModifyDuringPIEStatus
enum class FBlueprintEditor::ESafeToModifyDuringPIEStatus strong private
Enumerator
Unknown
Safe
NotSafe
Definition at line 1641 of file BlueprintEditor.h.
Constructor & Destructor Documentation
FBlueprintEditor()
FBlueprintEditor::FBlueprintEditor ()
Referenced by DECLARE_EVENT().
~FBlueprintEditor()
virtual FBlueprintEditor::~FBlueprintEditor () virtual
Member Function Documentation
AddBookmark()
FBPEditorBookmarkNode * FBlueprintEditor::AddBookmark (const FText & DisplayName, const FEditedDocumentInfo & BookmarkInfo, bool bSharedBookmark = false)
Adds a new bookmark node to the Blueprint that's being edited.
AddNewDelegateIsVisible()
bool FBlueprintEditor::AddNewDelegateIsVisible () const
AddNewFunctionVariant()
virtual void FBlueprintEditor::AddNewFunctionVariant (const UEdGraph * InOriginalFunction) inline virtual
Create a variant for a function.
Definition at line 614 of file BlueprintEditor.h.
AddReferencedObjects()
virtual void FBlueprintEditor::AddReferencedObjects (FReferenceCollector & Collector) override virtual
Pure virtual that must be overloaded by the inheriting class.
Use this method to serialize any UObjects contained that you wish to keep around.
Parameters
Collector The collector of referenced objects.
Implements FGCObject.
Reimplemented in FWidgetBlueprintEditor.
AddToSelection()
virtual void FBlueprintEditor::AddToSelection (UEdGraphNode * InNode) override virtual
Implements IBlueprintEditor.
AnalyticsTrackCompileEvent()
void FBlueprintEditor::AnalyticsTrackCompileEvent (UBlueprint * Blueprint, int32 NumErrors, int32 NumWarnings) const
AnalyticsTrackNodeEvent()
virtual void FBlueprintEditor::AnalyticsTrackNodeEvent (UBlueprint * Blueprint, UEdGraphNode * GraphNode, bool bNodeDelete = false) const override virtual
Used to track node create/delete events for Analytics.
Implements IBlueprintEditor.
AreDelegatesAllowed()
virtual bool FBlueprintEditor::AreDelegatesAllowed () const virtual
Whether delegates are allowed to be displayed/created in a blueprint.
AreEventGraphsAllowed()
virtual bool FBlueprintEditor::AreEventGraphsAllowed () const virtual
Whether event graphs are allowed to be displayed/created in a blueprint.
AreMacrosAllowed()
virtual bool FBlueprintEditor::AreMacrosAllowed () const virtual
Whether macros are allowed to be displayed/created in a blueprint.
BroadcastRefresh()
void FBlueprintEditor::BroadcastRefresh () inline private
Broadcast notification for associated controls to update.
Definition at line 1585 of file BlueprintEditor.h.
References RefreshEvent.
CanAccessComponentsMode()
bool FBlueprintEditor::CanAccessComponentsMode () const
Returns whether the edited blueprint has components.
CanAddBreakpoint()
bool FBlueprintEditor::CanAddBreakpoint () const protected
CanAddExecutionPin()
bool FBlueprintEditor::CanAddExecutionPin () const protected
CanAddNewLocalVariable()
virtual bool FBlueprintEditor::CanAddNewLocalVariable () const virtual
Checks if adding a local variable is allowed in the focused graph.
CanAddOptionPin()
bool FBlueprintEditor::CanAddOptionPin () const protected
CanAddParentNode()
bool FBlueprintEditor::CanAddParentNode () const protected
CanAssignReferencedActor()
bool FBlueprintEditor::CanAssignReferencedActor () const protected
CanChangePinType()
bool FBlueprintEditor::CanChangePinType () const protected
CanCollapseNodes()
bool FBlueprintEditor::CanCollapseNodes () const protected
CanCollapseSelectionToFunction() [1/2]
bool FBlueprintEditor::CanCollapseSelectionToFunction () const protected
CanCollapseSelectionToFunction() [2/2]
bool FBlueprintEditor::CanCollapseSelectionToFunction (TSet< class UEdGraphNode * > & InSelection) const protected
Called when a selection of nodes is being collapsed into a function.
Parameters
InSelection The selection to check
Returns
Returns TRUE if the selection can be promoted to a function
CanCollapseSelectionToMacro() [1/2]
bool FBlueprintEditor::CanCollapseSelectionToMacro () const protected
CanCollapseSelectionToMacro() [2/2]
bool FBlueprintEditor::CanCollapseSelectionToMacro (TSet< class UEdGraphNode * > & InSelection) const protected
Called when a selection of nodes is being collapsed into a macro.
Parameters
InSelection The selection to check
Returns
Returns TRUE if the selection can be promoted to a macro
CanConvertEventToFunction()
bool FBlueprintEditor::CanConvertEventToFunction () const protected
CanConvertFunctionToEvent()
bool FBlueprintEditor::CanConvertFunctionToEvent () const protected
Callback function for the context menu on a node to determine if a function could possibly be converted to an event.
CanCopyNodes()
virtual bool FBlueprintEditor::CanCopyNodes () const protected virtual
CanCreateMatchingFunction()
bool FBlueprintEditor::CanCreateMatchingFunction () const protected
CanCutNodes()
virtual bool FBlueprintEditor::CanCutNodes () const protected virtual
CanDeleteNodes()
virtual bool FBlueprintEditor::CanDeleteNodes () const protected virtual
CanDisableBreakpoint()
bool FBlueprintEditor::CanDisableBreakpoint () const protected
CanDuplicateNodes()
bool FBlueprintEditor::CanDuplicateNodes () const protected
CanEnableBreakpoint()
bool FBlueprintEditor::CanEnableBreakpoint () const protected
CanExpandNodes()
bool FBlueprintEditor::CanExpandNodes () const protected
CanFindReferences()
bool FBlueprintEditor::CanFindReferences () private
Checks if we can currently find all references of the node selection.
CanGoToDefinition()
bool FBlueprintEditor::CanGoToDefinition () const private
Checks to see if it is possible to jump to the selected node's definition.
CanGoToDocumentation()
bool FBlueprintEditor::CanGoToDocumentation () private
Can we open documentation for the selected node.
CanInsertExecutionPin()
bool FBlueprintEditor::CanInsertExecutionPin () const protected
CanNavigateToChildGraph()
bool FBlueprintEditor::CanNavigateToChildGraph () const protected
CanNavigateToParentGraph()
bool FBlueprintEditor::CanNavigateToParentGraph () const protected
CanOpenBlueprintDebugger()
bool FBlueprintEditor::CanOpenBlueprintDebugger () const protected
CanPasteGeneric()
virtual bool FBlueprintEditor::CanPasteGeneric () const protected virtual
CanPasteNodes()
virtual bool FBlueprintEditor::CanPasteNodes () const override protected virtual
Implements IBlueprintEditor.
CanPromoteSelectionToFunction()
bool FBlueprintEditor::CanPromoteSelectionToFunction () const protected
CanPromoteSelectionToMacro()
bool FBlueprintEditor::CanPromoteSelectionToMacro () const protected
CanPromoteToVariable()
bool FBlueprintEditor::CanPromoteToVariable (bool bInToMemberVariable) const protected
References bInToMemberVariable.
CanRecombineStructPin()
bool FBlueprintEditor::CanRecombineStructPin () const protected
CanRecompileModules()
bool FBlueprintEditor::CanRecompileModules () static private
Returns true if modules can be recompiled.
CanRedoGraphAction()
bool FBlueprintEditor::CanRedoGraphAction () const protected
Whether or not we can redo an undone action.
CanRemoveBreakpoint()
bool FBlueprintEditor::CanRemoveBreakpoint () const protected
CanRemoveExecutionPin()
bool FBlueprintEditor::CanRemoveExecutionPin () const protected
CanRemoveOptionPin()
bool FBlueprintEditor::CanRemoveOptionPin () const protected
CanRemoveOtherStructVarPins()
bool FBlueprintEditor::CanRemoveOtherStructVarPins () const protected
CanRemoveThisStructVarPin()
bool FBlueprintEditor::CanRemoveThisStructVarPin () const protected
CanRenameNodes()
bool FBlueprintEditor::CanRenameNodes () const protected
CanResetPinToDefaultValue()
bool FBlueprintEditor::CanResetPinToDefaultValue () const protected
CanRestoreAllStructVarPins()
bool FBlueprintEditor::CanRestoreAllStructVarPins () const protected
CanSelectAllNodes()
bool FBlueprintEditor::CanSelectAllNodes () const protected
CanSelectReferenceInLevel()
bool FBlueprintEditor::CanSelectReferenceInLevel () const protected
CanSplitStructPin()
bool FBlueprintEditor::CanSplitStructPin () const protected
CanStartWatchingPin()
virtual bool FBlueprintEditor::CanStartWatchingPin () const protected virtual
CanStopWatchingPin()
virtual bool FBlueprintEditor::CanStopWatchingPin () const protected virtual
CanToggleBreakpoint()
bool FBlueprintEditor::CanToggleBreakpoint () const protected
CanUndoGraphAction()
bool FBlueprintEditor::CanUndoGraphAction () const protected
Whether or not we can perform an undo of the last transacted action.
CanZoomToSelection()
bool FBlueprintEditor::CanZoomToSelection () const protected
CanZoomToWindow()
bool FBlueprintEditor::CanZoomToWindow () const protected
CheckEnabledStateForSelectedNodes()
ECheckBoxState FBlueprintEditor::CheckEnabledStateForSelectedNodes (ENodeEnabledState CheckState) private
Attempt to match the given enabled state for currently-selected nodes.
ClearAllBreakpoints()
void FBlueprintEditor::ClearAllBreakpoints () protected
Deletes all breakpoints for the blueprint being edited.
ClearAllGraphEditorQuickJumps()
void FBlueprintEditor::ClearAllGraphEditorQuickJumps () protected
Unbinds all graph editor "quick jump" commands.
ClearAllWatches()
void FBlueprintEditor::ClearAllWatches () protected
Clears all watches associated with the blueprint being edited.
ClearGraphEditorQuickJump()
void FBlueprintEditor::ClearGraphEditorQuickJump (int32 BookmarkIndex) protected
Unbinds a graph editor "quick jump" from the command at the given index.
ClearSelectionStateFor()
virtual void FBlueprintEditor::ClearSelectionStateFor (FName SelectionOwner) virtual
CloseDocumentTab()
void FBlueprintEditor::CloseDocumentTab (const UObject * DocumentID)
Finds the tab associated with the specified asset, and closes if it is open.
References CloseDocumentTab().
Referenced by CloseDocumentTab().
CloseMergeTool()
void FBlueprintEditor::CloseMergeTool ()
Closes the merge tool, rather than simply hiding it.
CollapseNodes()
void FBlueprintEditor::CollapseNodes (TSet< class UEdGraphNode * > & InCollapsableNodes) protected
Called when a selection of nodes are being collapsed into a sub-graph.
CollapseNodesIntoGraph()
void FBlueprintEditor::CollapseNodesIntoGraph (UEdGraphNode * InGatewayNode, class UK2Node_EditablePinBase * InEntryNode, class UK2Node_EditablePinBase * InResultNode, UEdGraph * InSourceGraph, UEdGraph * InDestinationGraph, TSet< UEdGraphNode * > & InCollapsableNodes, bool bCanDiscardEmptyReturnNode, bool bCanHaveWeakObjPtrParam) protected
Collapses a selection of nodes into a graph for composite, function, or macro nodes.
Parameters
InGatewayNode The node replacing the selection of nodes
InEntryNode The entry node in the graph
InResultNode The result node in the graph
InSourceGraph The graph the selection is from
InDestinationGraph The destination graph to move the selected nodes to
InCollapsableNodes The selection of nodes being collapsed
CollapseSelectionToFunction()
UEdGraph * FBlueprintEditor::CollapseSelectionToFunction (TSharedPtr< SGraphEditor > InRootGraph, TSet< class UEdGraphNode * > & InCollapsableNodes, UEdGraphNode *& OutFunctionNode) protected
Called when a selection of nodes are being collapsed into a function.
CollapseSelectionToMacro()
UEdGraph * FBlueprintEditor::CollapseSelectionToMacro (TSharedPtr< SGraphEditor > InRootGraph, TSet< class UEdGraphNode * > & InCollapsableNodes, UEdGraphNode *& OutMacroNode) protected
Called when a selection of nodes are being collapsed into a macro.
CollectExecDownstreamNodes()
void FBlueprintEditor::CollectExecDownstreamNodes (UEdGraphNode * CurrentNode, TArray< UEdGraphNode * > & CollectedNodes) protected
CollectExecUpstreamNodes()
void FBlueprintEditor::CollectExecUpstreamNodes (UEdGraphNode * CurrentNode, TArray< UEdGraphNode * > & CollectedNodes) protected
CollectPureDownstreamNodes()
void FBlueprintEditor::CollectPureDownstreamNodes (UEdGraphNode * CurrentNode, TArray< UEdGraphNode * > & CollectedNodes) protected
CollectPureUpstreamNodes()
void FBlueprintEditor::CollectPureUpstreamNodes (UEdGraphNode * CurrentNode, TArray< UEdGraphNode * > & CollectedNodes) protected
CommonInitialization()
void FBlueprintEditor::CommonInitialization (const TArray< UBlueprint * > & InitBlueprints, bool bShouldOpenInDefaultsMode)
Compile()
virtual void FBlueprintEditor::Compile () virtual
Called when Compile button is clicked.
Reimplemented in FWidgetBlueprintEditor.
Compile_OnClickWithReply()
virtual FReply FBlueprintEditor::Compile_OnClickWithReply () virtual
Calls the above function, but returns an FReply::Handled().
Used in SButtons
ConvertEventIfValid()
bool FBlueprintEditor::ConvertEventIfValid (UK2Node_Event * EventToConv)
Converts the given event node to a function graph on this blueprint if it passes validation.
ConvertEventToFunction()
void FBlueprintEditor::ConvertEventToFunction (UK2Node_Event * SelectedEventNode) protected
ConvertFunctionIfValid()
bool FBlueprintEditor::ConvertFunctionIfValid (UK2Node_FunctionEntry * FuncEntryNode)
Converts the given function entry node to an event if it passes validation.
ConvertFunctionToEvent()
void FBlueprintEditor::ConvertFunctionToEvent (UK2Node_FunctionEntry * SelectedCallFunctionNode) protected
CopySelectedNodes()
virtual void FBlueprintEditor::CopySelectedNodes () protected virtual
CreateDefaultCommands()
virtual void FBlueprintEditor::CreateDefaultCommands () protected virtual
Create Default Commands.
CreateDefaultTabContents()
virtual void FBlueprintEditor::CreateDefaultTabContents (const TArray< UBlueprint * > & InBlueprints) protected virtual
Creates the widgets that go into the tabs (note: does not create the tabs themselves)
CreateGraphEditorWidget()
virtual TSharedRef< SGraphEditor > FBlueprintEditor::CreateGraphEditorWidget (TSharedRef< class FTabInfo > InTabInfo, class UEdGraph * InGraph) protected virtual
CreateGraphTitleBarWidget()
TSharedRef< SWidget > FBlueprintEditor::CreateGraphTitleBarWidget (TSharedRef< FTabInfo > InTabInfo, UEdGraph * InGraph) protected
Create a graph title bar widget.
CreateMergeToolTab() [1/2]
void FBlueprintEditor::CreateMergeToolTab ()
Forces the merge tool to be shown.
CreateMergeToolTab() [2/2]
void FBlueprintEditor::CreateMergeToolTab (const UBlueprint * BaseBlueprint, const UBlueprint * RemoteBlueprint, const FOnMergeResolved & ResolutionCallback)
CreateSubobjectEditors()
void FBlueprintEditor::CreateSubobjectEditors () private
Creates the Subobject Editor tree component view and the Subobject Viewport.
CustomizeSubobjectEditor()
TSharedPtr< class ISCSEditorCustomization > FBlueprintEditor::CustomizeSubobjectEditor (const USceneComponent * InComponentToCustomize) const
Check to see if we can customize the subobject editor for the passed-in scene component.
Parameters
InComponentToCustomize The component to check to see if a customization exists
Returns
an subobject editor customization instance, if one exists.
Referenced by UE_DEPRECATED().
CutSelectedNodes()
virtual void FBlueprintEditor::CutSelectedNodes () protected virtual
DECLARE_EVENT()
FBlueprintEditor::DECLARE_EVENT (FBlueprintEditor , FOnRefreshEvent)
Broadcasts a notification whenever the editor needs associated controls to refresh.
References FBlueprintEditor(), and DECLARE_EVENT().
Referenced by DECLARE_EVENT().
DECLARE_MULTICAST_DELEGATE_OneParam() [1/2]
FBlueprintEditor::DECLARE_MULTICAST_DELEGATE_OneParam (FOnModeSet , FName)
DECLARE_MULTICAST_DELEGATE_OneParam() [2/2]
FBlueprintEditor::DECLARE_MULTICAST_DELEGATE_OneParam (FOnSetPinVisibility , SGraphEditor::EPinVisibility) private
DeleteSelectedDuplicatableNodes()
void FBlueprintEditor::DeleteSelectedDuplicatableNodes () protected
DeleteSelectedNodes()
virtual void FBlueprintEditor::DeleteSelectedNodes () protected virtual
DeleteUnusedVariables_OnClicked()
void FBlueprintEditor::DeleteUnusedVariables_OnClicked () protected
Called when DeleteUnusedVariables button is clicked.
DestroyPreview()
void FBlueprintEditor::DestroyPreview ()
Destroy the Blueprint preview.
DisableAllBreakpoints()
void FBlueprintEditor::DisableAllBreakpoints () protected
Disables all breakpoints for the blueprint being edited.
DoPromoteToVariable2f()
void FBlueprintEditor::DoPromoteToVariable2f (UBlueprint * InBlueprint, UEdGraphPin * InTargetPin, bool bInToMemberVariable, TOptional< FVector2f > InOptionalLocation = TOptional< FVector2f >())
References bInToMemberVariable, DoPromoteToVariable2f(), InOptionalLocation, and InTargetPin.
Referenced by DoPromoteToVariable2f().
DumpMessagesToCompilerLog()
void FBlueprintEditor::DumpMessagesToCompilerLog (const TArray< TSharedRef< class FTokenizedMessage > > & Messages, bool bForceMessageDisplay)
Dumps messages to the compiler log, with an option to force it to display/come to front.
DuplicateNodes()
void FBlueprintEditor::DuplicateNodes () protected
EditClassDefaults_Clicked()
void FBlueprintEditor::EditClassDefaults_Clicked () protected
Edit the class defaults.
EditGlobalOptions_Clicked()
void FBlueprintEditor::EditGlobalOptions_Clicked () protected
Edit the class settings aka Blueprint global options.
EnableAllBreakpoints()
void FBlueprintEditor::EnableAllBreakpoints () protected
Enables all breakpoints for the blueprint being edited.
EnableSubobjectPreview()
void FBlueprintEditor::EnableSubobjectPreview (bool bEnable)
Enable/disable the subobject editor preview viewport.
EnsureBlueprintIsUpToDate()
void FBlueprintEditor::EnsureBlueprintIsUpToDate (UBlueprint * BlueprintObj)
ExpandNode()
void FBlueprintEditor::ExpandNode (UEdGraphNode * InNodeToExpand, UEdGraph * InSourceGraph, TSet< UEdGraphNode * > & OutExpandedNodes) static protected
Expands passed in node.
ExtractEventTemplateForFunction()
void FBlueprintEditor::ExtractEventTemplateForFunction (class UK2Node_CustomEvent * InCustomEvent, UEdGraphNode * InGatewayNode, class UK2Node_EditablePinBase * InEntryNode, class UK2Node_EditablePinBase * InResultNode, TSet< UEdGraphNode * > & InCollapsableNodes) protected
Pulls out the pins to use as a template when collapsing a selection to a function with a custom event involved.
Parameters
InCustomEvent The custom event used as a template
InGatewayNode The node replacing the selection of nodes
InEntryNode The entry node in the graph
InResultNode The result node in the graph
InCollapsableNodes The selection of nodes being collapsed
FindAndSelectSubobjectEditorTreeNode()
virtual TSharedPtr< FSubobjectEditorTreeNode > FBlueprintEditor::FindAndSelectSubobjectEditorTreeNode (const UActorComponent * InComponent, bool IsCntrlDown) override virtual
References IBlueprintEditor::IsCntrlDown.
FindInBlueprint_Clicked()
void FBlueprintEditor::FindInBlueprint_Clicked () protected
Called to start a quick find (focus the search box in the explorer tab)
FindInBlueprints_OnClicked()
void FBlueprintEditor::FindInBlueprints_OnClicked () protected
Called when Find In Blueprints menu is opened is clicked.
FindOpenTabsContainingDocument()
bool FBlueprintEditor::FindOpenTabsContainingDocument (const UObject * DocumentID, TArray< TSharedPtr< SDockTab > > & Results)
References FindOpenTabsContainingDocument().
Referenced by FindOpenTabsContainingDocument().
FocusInspectorOnGraphSelection()
virtual void FBlueprintEditor::FocusInspectorOnGraphSelection (const TSet< class UObject * > & NewSelection, bool bForceRefresh = false) virtual
GetAllConnectedNodes()
TArray< UEdGraphNode * > FBlueprintEditor::GetAllConnectedNodes (UEdGraphNode *const Node) const protected
Get all connected nodes and add them to a set of out nodes.
Parameters
Node The node to get all connects to
Returns
TArray of all connected nodes
GetBaseToolkitName()
virtual FText FBlueprintEditor::GetBaseToolkitName () const override virtual
Implements FAssetEditorToolkit.
Reimplemented in FWidgetBlueprintEditor.
GetBlueprintObj()
virtual UBlueprint * FBlueprintEditor::GetBlueprintObj () const virtual
Returns a pointer to the Blueprint object we are currently editing, as long as we are editing exactly one.
GetBookmarksWidget()
TSharedRef< SBlueprintBookmarks > FBlueprintEditor::GetBookmarksWidget () const inline
Definition at line 336 of file BlueprintEditor.h.
References BookmarksWidget.
GetBoundsForNode()
void FBlueprintEditor::GetBoundsForNode (const UEdGraphNode * InNode, class FSlateRect & OutRect, float InPadding) const
Get the visible bounds of the given graph node.
GetBoundsForSelectedNodes()
virtual bool FBlueprintEditor::GetBoundsForSelectedNodes (class FSlateRect & Rect, float Padding) override protected virtual
Implements IBlueprintEditor.
References Padding.
GetCompilerResults()
TSharedRef< SWidget > FBlueprintEditor::GetCompilerResults () const inline
Definition at line 337 of file BlueprintEditor.h.
References CompilerResults.
GetContextFromBlueprintType()
FName FBlueprintEditor::GetContextFromBlueprintType (EBlueprintType InType) static
Get the context to use from the Blueprint type.
GetCurrentGraphAppearance()
FGraphAppearanceInfo FBlueprintEditor::GetCurrentGraphAppearance () const protected
Get the graph appearance of the currently focused graph.
GetCurrentlySelectedPin()
UEdGraphPin * FBlueprintEditor::GetCurrentlySelectedPin () const protected
GetCustomDebugObjectLabel()
virtual FString FBlueprintEditor::GetCustomDebugObjectLabel (UObject * ObjectBeingDebugged) const inline virtual
Can be overloaded to customize the labels in the debug filter.
Definition at line 739 of file BlueprintEditor.h.
GetCustomDebugObjects()
virtual void FBlueprintEditor::GetCustomDebugObjects (TArray< FCustomDebugObject > & DebugList) const inline virtual
Adds to a list of custom objects for debugging beyond what will automatically be found/used.
Definition at line 733 of file BlueprintEditor.h.
GetDefaultEditor()
TSharedRef< SKismetInspector > FBlueprintEditor::GetDefaultEditor () const inline
Definition at line 334 of file BlueprintEditor.h.
References DefaultEditor.
GetDefaultSchema()
TSubclassOf< UEdGraphSchema > FBlueprintEditor::GetDefaultSchema () const inline
Gets the default schema for this editor.
Definition at line 772 of file BlueprintEditor.h.
References GetDefaultSchemaClass().
GetDefaultSchemaClass()
virtual TSubclassOf< UEdGraphSchema > FBlueprintEditor::GetDefaultSchemaClass () const protected virtual
Whenever new graphs need to be created it will use this schema by default.
Reimplemented in FWidgetBlueprintEditor.
Referenced by GetDefaultSchema().
GetDocLinkBaseUrlForSelectedNode()
FString FBlueprintEditor::GetDocLinkBaseUrlForSelectedNode () private
Util to try and get the base URL for the doc link for the currently selected node.
GetDocLinkForSelectedNode()
FString FBlueprintEditor::GetDocLinkForSelectedNode () private
Util to try and get doc link for the currently selected node.
GetDocumentationLink()
virtual FString FBlueprintEditor::GetDocumentationLink () const override virtual
Returns
the documentation location for this editor
Reimplemented from FAssetEditorToolkit.
GetEditParentClassVisibility()
EVisibility FBlueprintEditor::GetEditParentClassVisibility () const protected
Determines visibility of the edit parent class button on the menu bar overlay.
GetEnabledCheckBoxStateForSelectedNodes()
ECheckBoxState FBlueprintEditor::GetEnabledCheckBoxStateForSelectedNodes () private
Returns the appropriate check box state representing whether or not the selected nodes are enabled.
GetFindParentClassVisibility()
EVisibility FBlueprintEditor::GetFindParentClassVisibility () const protected
Determines visibility of the find parent class in content browser button on the menu bar overlay.
GetFindResults()
TSharedRef< SFindInBlueprints > FBlueprintEditor::GetFindResults () const inline
Definition at line 338 of file BlueprintEditor.h.
References FindResults.
GetFocusedGraph()
virtual UEdGraph * FBlueprintEditor::GetFocusedGraph () const override virtual
Returns the currently focused graph context, or NULL if no graph is available.
Implements IBlueprintEditor.
GetGlyphForGraph()
const FSlateBrush * FBlueprintEditor::GetGlyphForGraph (const UEdGraph * Graph, bool bInLargeIcon = false) static
Util for finding a glyph for a graph.
Parameters
Graph - The graph to evaluate
bInLargeIcon - if true the icon returned is 22x22 pixels, else it is 16x16
Returns
An appropriate brush to use to represent the graph, if the graph is an unknown type the function will return the default "function" glyph
GetGraphAppearance()
virtual FGraphAppearanceInfo FBlueprintEditor::GetGraphAppearance (class UEdGraph * InGraph) const protected virtual
Get the graph appearance of a specific graph, GetCurrentGraphAppearance() uses the currently focused graph.
Reimplemented in FWidgetBlueprintEditor.
GetGraphDecorationString()
virtual FText FBlueprintEditor::GetGraphDecorationString (UEdGraph * InGraph) const virtual
Called by a graph title bar to get any extra information the editor would like to display.
GetGraphDisplayName()
FText FBlueprintEditor::GetGraphDisplayName (const UEdGraph * Graph) static
Gets the display name of a graph.
GetImportedClassViewerFilter()
virtual TSharedPtr< class IClassViewerFilter > FBlueprintEditor::GetImportedClassViewerFilter () const inline override virtual
Return the class viewer filter associated with the current set of imported namespaces within this editor context.
Default is NULL (no filter).
Reimplemented from IBlueprintEditor.
Definition at line 295 of file BlueprintEditor.h.
References ImportedClassViewerFilter.
GetInspector()
TSharedRef< SKismetInspector > FBlueprintEditor::GetInspector () const inline
Getters for the various Kismet2 widgets.
Definition at line 333 of file BlueprintEditor.h.
References Inspector.
GetInstructionTextOpacity()
float FBlueprintEditor::GetInstructionTextOpacity (UEdGraph * InGraph) const
Used to determine the visibility of the graph's instruction text.
GetIsContextSensitive()
bool & FBlueprintEditor::GetIsContextSensitive () inline
Gets or sets the flag for context sensitivity in the graph action menu.
Definition at line 650 of file BlueprintEditor.h.
References bIsActionMenuContextSensitive.
GetMyBlueprintWidget()
TSharedPtr< SMyBlueprint > FBlueprintEditor::GetMyBlueprintWidget () const inline
Definition at line 346 of file BlueprintEditor.h.
References MyBlueprintWidget.
GetNativeParentClassButtonsVisibility()
EVisibility FBlueprintEditor::GetNativeParentClassButtonsVisibility () const
Determines visibility of the native parent class manipulation buttons on the menu bar overlay.
GetNumberOfSelectedNodes()
virtual int32 FBlueprintEditor::GetNumberOfSelectedNodes () const override virtual
Get number of currently selected nodes in the SCS editor tree.
Implements IBlueprintEditor.
GetPalette()
TSharedRef< SBlueprintPalette > FBlueprintEditor::GetPalette ()
GetParentClassNameText()
FText FBlueprintEditor::GetParentClassNameText () const protected
Returns the name of the Blueprint's parent class.
GetParentClassNameVisibility()
EVisibility FBlueprintEditor::GetParentClassNameVisibility () const
Determines visibility of the standard parent class label on the menu bar overlay.
GetPIEStatus()
FText FBlueprintEditor::GetPIEStatus () const
Returns our PIE Status - SIMULATING / SERVER / CLIENT.
GetPinTypeSelectorFilters()
virtual void FBlueprintEditor::GetPinTypeSelectorFilters (TArray< TSharedPtr< class IPinTypeSelectorFilter > > & OutFilters) const override virtual
Get all the the pin type selector filters within this editor context.
Reimplemented from IBlueprintEditor.
GetPinVisibility()
bool FBlueprintEditor::GetPinVisibility (SGraphEditor::EPinVisibility Visibility) const inline
Definition at line 590 of file BlueprintEditor.h.
References PinVisibility, and Visibility.
GetPreviewActor()
AActor * FBlueprintEditor::GetPreviewActor () const
Provides access to the preview actor.
GetPreviewScene()
FPreviewScene * FBlueprintEditor::GetPreviewScene () inline
Provides access to the preview scene.
Definition at line 357 of file BlueprintEditor.h.
References PreviewScene.
GetReferencerName()
virtual FString FBlueprintEditor::GetReferencerName () const override virtual
Overload this method to report a name for your referencer.
Implements FGCObject.
GetReplaceReferencesWidget()
TSharedPtr< SReplaceNodeReferences > FBlueprintEditor::GetReplaceReferencesWidget () const inline
Definition at line 347 of file BlueprintEditor.h.
References ReplaceReferencesWidget.
GetSaveIntermediateBuildProducts()
bool FBlueprintEditor::GetSaveIntermediateBuildProducts () const protected
GetSelectedNodes()
FGraphPanelSelectionSet FBlueprintEditor::GetSelectedNodes () const
Get the currently selected set of nodes.
GetSelectedSubobjectEditorTreeNodes()
virtual TArray< TSharedPtr< FSubobjectEditorTreeNode > > FBlueprintEditor::GetSelectedSubobjectEditorTreeNodes () const override virtual
Util to get the currently selected Subobject editor tree Nodes.
Implements IBlueprintEditor.
GetSingleSelectedNode()
UEdGraphNode * FBlueprintEditor::GetSingleSelectedNode () const
Returns the currently selected node if there is a single node selected (if there are multiple nodes selected or none selected, it will return nullptr)
GetStatId()
virtual TStatId FBlueprintEditor::GetStatId () const override virtual
Return the stat id used to track the performance of this object.
Implements FTickableObjectBase.
GetSubobjectEditor()
TSharedPtr< SSubobjectEditor > FBlueprintEditor::GetSubobjectEditor () const inline
Definition at line 344 of file BlueprintEditor.h.
References SubobjectEditor.
GetSubobjectEditorObjectContext()
UObject * FBlueprintEditor::GetSubobjectEditorObjectContext () const
Delegate invoked when the Subobject editor needs to obtain the object context for editing.
GetSubobjectViewport()
TSharedPtr< SSCSEditorViewport > FBlueprintEditor::GetSubobjectViewport () const inline
Definition at line 345 of file BlueprintEditor.h.
References SubobjectViewport.
GetTextForNativeParentClassHeaderLink()
FText FBlueprintEditor::GetTextForNativeParentClassHeaderLink () const
Returns: "(<NativeParentClass>.h)".
GetTickableTickType()
virtual ETickableTickType FBlueprintEditor::GetTickableTickType () const inline override virtual
Virtual that can be overloaded by the inheriting class and is called before first tick.
It is used to determine whether an object can possibly tick, and if not, it will not get added to the tickable objects array. If the tickable tick type is Conditional then the virtual IsTickable will be called to determine whether to tick the object on each given frame.
Returns
an enum defining the rules for ticking this object.
Reimplemented from FTickableObjectBase.
Definition at line 305 of file BlueprintEditor.h.
References Always.
GetToolbarBuilder()
TSharedPtr< class FBlueprintEditorToolbar > FBlueprintEditor::GetToolbarBuilder () inline
Definition at line 375 of file BlueprintEditor.h.
References Toolbar.
GetToolkitContextFName()
virtual FName FBlueprintEditor::GetToolkitContextFName () const override virtual
Reimplemented from FBaseToolkit.
Reimplemented in FWidgetBlueprintEditor.
GetToolkitFName()
virtual FName FBlueprintEditor::GetToolkitFName () const override virtual
Implements FAssetEditorToolkit.
Reimplemented in FWidgetBlueprintEditor.
GetToolkitName()
virtual FText FBlueprintEditor::GetToolkitName () const override virtual
Reimplemented from FAssetEditorToolkit.
GetToolkitToolTipText()
virtual FText FBlueprintEditor::GetToolkitToolTipText () const override virtual
Reimplemented from FAssetEditorToolkit.
GetUISelectionState()
FName FBlueprintEditor::GetUISelectionState () const inline
Gets the UI selection state of this editor.
Definition at line 653 of file BlueprintEditor.h.
References CurrentUISelection.
GetVarIconAndColor()
FSlateBrush const * FBlueprintEditor::GetVarIconAndColor (const UStruct * VarScope, FName VarName, FSlateColor & IconColorOut, FSlateBrush const *& SecondaryBrushOut, FSlateColor & SecondaryColorOut) static
Util for finding a glyph and color for a variable.
Parameters
VarScope Scope to find the variable in
VarName Name of variable
IconColorOut The resulting color for the glyph
SecondaryBrushOut The resulting secondary glyph brush (used for Map types)
SecondaryColorOut The resulting secondary color for the glyph (used for Map types)
Returns
The resulting glyph brush
GetVarIconAndColorFromPinType()
FSlateBrush const * FBlueprintEditor::GetVarIconAndColorFromPinType (const FEdGraphPinType & PinType, FSlateColor & IconColorOut, FSlateBrush const *& SecondaryBrushOut, FSlateColor & SecondaryColorOut) static
Util for finding a glyph and color for a variable.
Parameters
PinType The variable's pin type
IconColorOut The resulting color for the glyph
SecondaryBrushOut The resulting secondary glyph brush (used for Map types)
SecondaryColorOut The resulting secondary color for the glyph (used for Map types)
Returns
The resulting glyph brush
GetVarIconAndColorFromProperty()
FSlateBrush const * FBlueprintEditor::GetVarIconAndColorFromProperty (const FProperty * Property, FSlateColor & IconColorOut, FSlateBrush const *& SecondaryBrushOut, FSlateColor & SecondaryColorOut) static
Util for finding a glyph and color for a variable.
Parameters
Property The variable's property
IconColorOut The resulting color for the glyph
SecondaryBrushOut The resulting secondary glyph brush (used for Map types)
SecondaryColorOut The resulting secondary color for the glyph (used for Map types)
Returns
The resulting glyph brush
References Property.
GetViewBookmark()
void FBlueprintEditor::GetViewBookmark (FGuid & BookmarkId)
Gets the focused graph current view bookmark ID.
GetViewLocation()
void FBlueprintEditor::GetViewLocation (FVector2D & Location, float & ZoomAmount)
Gets the focused graph view location/zoom amount.
References Location.
GetViewportSelectabilityBridge()
FEditorViewportSelectabilityBridge * FBlueprintEditor::GetViewportSelectabilityBridge ()
GetWorldCentricTabColorScale()
virtual FLinearColor FBlueprintEditor::GetWorldCentricTabColorScale () const override virtual
Reimplemented in FWidgetBlueprintEditor.
GetWorldCentricTabPrefix()
virtual FString FBlueprintEditor::GetWorldCentricTabPrefix () const override virtual
Implements FAssetEditorToolkit.
Reimplemented in FWidgetBlueprintEditor.
HandleSetObjectBeingDebugged()
virtual void FBlueprintEditor::HandleSetObjectBeingDebugged (UObject * InObject) inline virtual
Handle when the debug object is changed in the UI.
Definition at line 760 of file BlueprintEditor.h.
HandleUndoTransaction()
void FBlueprintEditor::HandleUndoTransaction (const class FTransaction * Transaction) private
Handle undo/redo.
HandleUnrelatedNodesOpacityBoxChanged()
void FBlueprintEditor::HandleUnrelatedNodesOpacityBoxChanged (float NewOpacity)
References HandleUnrelatedNodesOpacityBoxChanged().
Referenced by HandleUnrelatedNodesOpacityBoxChanged().
HandleUnrelatedNodesOpacityBoxValue()
TOptional< float > FBlueprintEditor::HandleUnrelatedNodesOpacityBoxValue () const
References HandleUnrelatedNodesOpacityBoxValue().
Referenced by HandleUnrelatedNodesOpacityBoxValue().
HasAnyBreakpoints()
bool FBlueprintEditor::HasAnyBreakpoints () const protected
HasAnyDisabledBreakpoints()
bool FBlueprintEditor::HasAnyDisabledBreakpoints () const protected
HasAnyEnabledBreakpoints()
bool FBlueprintEditor::HasAnyEnabledBreakpoints () const protected
HasAnyWatches()
bool FBlueprintEditor::HasAnyWatches () const protected
HideUnrelatedNodes()
void FBlueprintEditor::HideUnrelatedNodes () protected
ImportNamespace()
void FBlueprintEditor::ImportNamespace (const FString & InNamespace)
Imports the given namespace into the editor.
This may trigger a load event for additional macro and/or function library assets if not already loaded.
ImportNamespaceEx()
void FBlueprintEditor::ImportNamespaceEx (const FImportNamespaceExParameters & InParams)
Imports a set of namespace(s) into the editor.
This may trigger a load event for additional macro and/or function library assets if not already loaded.
InEditingMode()
virtual bool FBlueprintEditor::InEditingMode () const virtual
Returns true if in editing mode.
InitalizeExtenders()
virtual void FBlueprintEditor::InitalizeExtenders () protected virtual
Called during initialization of the blueprint editor to register commands and extenders.
Reimplemented in FWidgetBlueprintEditor.
InitBlueprintEditor()
void FBlueprintEditor::InitBlueprintEditor (const EToolkitMode::Type Mode, const TSharedPtr< class IToolkitHost > & InitToolkitHost, const TArray< class UBlueprint * > & InBlueprints, bool bShouldOpenInDefaultsMode)
Edits the specified blueprint.
Parameters
Mode Asset editing mode for this editor (standalone or world-centric)
InitToolkitHost When Mode is WorldCentric, this is the level editor instance to spawn this editor within
InBlueprints The blueprints to edit
bShouldOpenInDefaultsMode If true, the editor will open in defaults editing mode
InitToolMenuContext()
virtual void FBlueprintEditor::InitToolMenuContext (FToolMenuContext & MenuContext) override virtual
Add context objects for menus and toolbars.
Reimplemented from FAssetEditorToolkit.
Reimplemented in FWidgetBlueprintEditor.
IsASubGraph()
bool FBlueprintEditor::IsASubGraph (const class UEdGraph * GraphPtr) static private
Function to check whether the give graph is a subgraph.
IsBlueprintEditor()
virtual bool FBlueprintEditor::IsBlueprintEditor () const override virtual
Reimplemented from FBaseToolkit.
IsCompilingEnabled()
virtual bool FBlueprintEditor::IsCompilingEnabled () const virtual
Returns true if able to compile.
IsDebuggerVisible()
EVisibility FBlueprintEditor::IsDebuggerVisible () const
IsDetailsPanelEditingClassDefaults()
bool FBlueprintEditor::IsDetailsPanelEditingClassDefaults () const protected
IsDetailsPanelEditingGlobalOptions()
bool FBlueprintEditor::IsDetailsPanelEditingGlobalOptions () const protected
IsEditable()
virtual bool FBlueprintEditor::IsEditable (UEdGraph * InGraph) const virtual
Returns whether a graph is editable or not.
IsEditingAnimGraph()
bool FBlueprintEditor::IsEditingAnimGraph () const private
Checks to see if the focused Graph-Editor is focused on a animation graph or not.
Returns
True if GraphEdPtr's current graph is an animation graph, false if not.
IsEditingSingleBlueprint()
bool FBlueprintEditor::IsEditingSingleBlueprint () const
Returns whether the editor is currently editing a single blueprint object.
IsEditorClosing()
bool FBlueprintEditor::IsEditorClosing () const
Returns if we are currently closing the editor.
IsFocusedGraphEditable()
bool FBlueprintEditor::IsFocusedGraphEditable () const private
Returns whether the currently focused graph is editable or not.
IsGraphInCurrentBlueprint()
bool FBlueprintEditor::IsGraphInCurrentBlueprint (const UEdGraph * InGraph) const
Checks to see if the provided graph is contained within the current blueprint.
IsGraphReadOnly()
bool FBlueprintEditor::IsGraphReadOnly (UEdGraph * InGraph) const
Determines if the graph is ReadOnly, this differs from editable in that it is never expected to be edited and is in a read-only state.
IsInAScriptingMode()
virtual bool FBlueprintEditor::IsInAScriptingMode () const virtual
Overridable function for determining if the current mode can script.
IsNativeParentClassCodeLinkEnabled()
virtual bool FBlueprintEditor::IsNativeParentClassCodeLinkEnabled () const virtual
Returns true if the parent class is native and the link to it's header can be shown.
IsNodeTitleVisible()
bool FBlueprintEditor::IsNodeTitleVisible (const UEdGraphNode * Node, bool bRequestRename)
Check the Node Title is visible.
IsNonImportedObject() [1/2]
virtual bool FBlueprintEditor::IsNonImportedObject (const FSoftObjectPath & InObject) const virtual
Return whether the given object (referenced by path) falls outside the scope of the current set of imported namespaces within this editor context.
Default is FALSE (imported).
Reimplemented from IBlueprintEditor.
IsNonImportedObject() [2/2]
virtual bool FBlueprintEditor::IsNonImportedObject (const UObject * InObject) const virtual
Return whether the given object falls outside the scope of the current set of imported namespaces within this editor context.
Default is FALSE (imported).
Reimplemented from IBlueprintEditor.
IsParentClassABlueprint()
bool FBlueprintEditor::IsParentClassABlueprint () const
Returns true if the parent class of the Blueprint being edited is also a Blueprint.
IsParentClassAnEditableBlueprint()
bool FBlueprintEditor::IsParentClassAnEditableBlueprint () const
Returns true if the parent class of the Blueprint being edited is an editable Blueprint.
IsParentClassNative()
bool FBlueprintEditor::IsParentClassNative () const
Returns true if the parent class of the Blueprint being edited is native.
IsPlayInEditorActive()
bool FBlueprintEditor::IsPlayInEditorActive () const
Returns true if PIE is active.
IsSaveOnCompileEnabled()
bool FBlueprintEditor::IsSaveOnCompileEnabled () const
Helper functions used to construct/operate-on the "Save on Compile" command.
IsSectionVisible()
virtual bool FBlueprintEditor::IsSectionVisible (NodeSectionID::Type InSectionID) const inline virtual
Definition at line 636 of file BlueprintEditor.h.
IsToggleHideUnrelatedNodesChecked()
bool FBlueprintEditor::IsToggleHideUnrelatedNodesChecked () const
JumpToHyperlink()
virtual void FBlueprintEditor::JumpToHyperlink (const UObject * ObjectReference, bool bRequestRename = false) override virtual
Implements IBlueprintEditor.
References ObjectReference.
JumpToNode()
void FBlueprintEditor::JumpToNode (const class UEdGraphNode * Node, bool bRequestRename = false)
Pan the view to center on a particular node.
JumpToPin()
virtual void FBlueprintEditor::JumpToPin (const class UEdGraphPin * Pin) override virtual
LoadEditorSettings()
virtual void FBlueprintEditor::LoadEditorSettings () private virtual
Load editor settings from disk (docking state, window pos/size, option state, etc).
LoadLibrariesFromAssetRegistry()
void FBlueprintEditor::LoadLibrariesFromAssetRegistry () protected
Load macro & function blueprint libraries from asset registry.
LogSimpleMessage()
void FBlueprintEditor::LogSimpleMessage (const FText & MessageText)
Throw a simple message into the log.
LogToken_OnClicked()
void FBlueprintEditor::LogToken_OnClicked (const class IMessageToken & Token)
Called when a token in a log message is clicked.
MakeHideUnrelatedNodesOptionsMenu()
TSharedRef< SWidget > FBlueprintEditor::MakeHideUnrelatedNodesOptionsMenu ()
Make a drop down menu to control the opacity of unrelated nodes.
References MakeHideUnrelatedNodesOptionsMenu().
Referenced by MakeHideUnrelatedNodesOptionsMenu().
MoveNodesToAveragePos()
void FBlueprintEditor::MoveNodesToAveragePos (TSet< UEdGraphNode * > & AverageNodes, FVector2D SourcePos, bool bExpandedNodesNeedUniqueGuid = false) const protected
Move the given set of nodes to an average spot near the Source position.
Parameters
AverageNodes The nodes to move
SourcePos The source position used to average the nodes around
bExpandedNodesNeedUniqueGuid If true then a new Guid will be generated for each node in the set
MoveNodesToGraph()
void FBlueprintEditor::MoveNodesToGraph (TArray< UEdGraphNode * > & SourceNodes, UEdGraph * DestinationGraph, TSet< UEdGraphNode * > & OutExpandedNodes, UEdGraphNode ** OutEntry, UEdGraphNode ** OutResult, const bool bIsCollapsedGraph = false) static protected
Move every node from the source graph to the destination graph.
Add Each node that is moved to the OutExpandedNodes set. If the source graph is a function graph, keep track of the entry and result nodes in the given Out Parameters.
Parameters
SourceNodes Nodes to move
DestinationGraph Graph to move nodes to
OutExpandedNodes Set of each node that was moved from the source to destination graph
OutEntry Pointer to the function entry node
OutResult Pointer to the function result node
bIsCollapsedGraph Whether or not the source graph is collapsed
NavigateTab()
void FBlueprintEditor::NavigateTab (FDocumentTracker::EOpenDocumentCause InCause) private
Helper function to navigate the current tab.
NavigateToChildGraph()
void FBlueprintEditor::NavigateToChildGraph () protected
NavigateToParentGraph()
void FBlueprintEditor::NavigateToParentGraph () protected
NavigateToParentGraphByDoubleClick()
void FBlueprintEditor::NavigateToParentGraphByDoubleClick () protected
NewDocument_GetVisibilityForType()
EVisibility FBlueprintEditor::NewDocument_GetVisibilityForType (ECreatedDocumentType GraphType) const inline
Definition at line 638 of file BlueprintEditor.h.
References EVisibility::Collapsed, NewDocument_IsVisibleForType(), and EVisibility::Visible.
NewDocument_IsVisibleForType()
virtual bool FBlueprintEditor::NewDocument_IsVisibleForType (ECreatedDocumentType GraphType) const virtual
Referenced by NewDocument_GetVisibilityForType().
NewDocument_OnClick()
FReply FBlueprintEditor::NewDocument_OnClick (ECreatedDocumentType GraphType) inline
Definition at line 629 of file BlueprintEditor.h.
References FReply::Handled(), and NewDocument_OnClicked().
NewDocument_OnClicked()
virtual void FBlueprintEditor::NewDocument_OnClicked (ECreatedDocumentType GraphType) virtual
Called when New Function button is clicked.
Referenced by NewDocument_OnClick().
NotifyPostChange()
virtual void FBlueprintEditor::NotifyPostChange (const FPropertyChangedEvent & PropertyChangedEvent, FProperty * PropertyThatChanged) override protected virtual
Reimplemented from FNotifyHook.
NotifyPreChange()
virtual void FBlueprintEditor::NotifyPreChange (FProperty * PropertyAboutToChange) override protected virtual
Reimplemented from FNotifyHook.
OnActionMatchesName()
virtual bool FBlueprintEditor::OnActionMatchesName (FEdGraphSchemaAction * InAction, const FName & InName) const inline virtual
function used by the SMyBlueprint to determine if an action matches a name.
This happens during selection of a custom action (a graph, a variable etc)
Definition at line 1578 of file BlueprintEditor.h.
References InName.
OnActiveTabChanged()
virtual void FBlueprintEditor::OnActiveTabChanged (TSharedPtr< SDockTab > PreviouslyActive, TSharedPtr< SDockTab > NewlyActivated) virtual
OnAddBreakpoint()
void FBlueprintEditor::OnAddBreakpoint () protected
OnAddExecutionPin()
void FBlueprintEditor::OnAddExecutionPin () protected
OnAddNewDelegate()
void FBlueprintEditor::OnAddNewDelegate ()
Called when New Delegate button is clicked.
OnAddNewLocalVariable()
virtual void FBlueprintEditor::OnAddNewLocalVariable () virtual
Adds a new local variable to the focused function graph.
OnAddNewVariable()
void FBlueprintEditor::OnAddNewVariable ()
Adds a new variable to this blueprint.
Referenced by OnAddNewVariable_OnClick().
OnAddNewVariable_OnClick()
FReply FBlueprintEditor::OnAddNewVariable_OnClick () inline
Definition at line 602 of file BlueprintEditor.h.
References FReply::Handled(), and OnAddNewVariable().
OnAddOptionPin()
void FBlueprintEditor::OnAddOptionPin () protected
OnAddParentNode()
void FBlueprintEditor::OnAddParentNode () protected
OnAlignBottom()
void FBlueprintEditor::OnAlignBottom () protected
OnAlignCenter()
void FBlueprintEditor::OnAlignCenter () protected
OnAlignLeft()
void FBlueprintEditor::OnAlignLeft () protected
OnAlignMiddle()
void FBlueprintEditor::OnAlignMiddle () protected
OnAlignRight()
void FBlueprintEditor::OnAlignRight () protected
OnAlignTop()
void FBlueprintEditor::OnAlignTop () protected
OnAssignReferencedActor()
void FBlueprintEditor::OnAssignReferencedActor () protected
OnBlueprintChanged()
void FBlueprintEditor::OnBlueprintChanged (UBlueprint * InBlueprint) inline protected
Called when the Blueprint we are editing has changed, forwards to impl.
Definition at line 904 of file BlueprintEditor.h.
References OnBlueprintChanged(), and OnBlueprintChangedImpl().
Referenced by OnBlueprintChanged().
OnBlueprintChangedImpl()
virtual void FBlueprintEditor::OnBlueprintChangedImpl (UBlueprint * InBlueprint, bool bIsJustBeingCompiled = false) protected virtual
Called when the Blueprint we are editing has changed.
Reimplemented in FWidgetBlueprintEditor.
References OnBlueprintChangedImpl().
Referenced by OnBlueprintChanged(), and OnBlueprintChangedImpl().
OnBlueprintCompiled()
void FBlueprintEditor::OnBlueprintCompiled (UBlueprint * InBlueprint) protected
OnBlueprintEditorPreferencesChanged()
virtual void FBlueprintEditor::OnBlueprintEditorPreferencesChanged (UObject * , struct FPropertyChangedEvent &) private virtual
OnBlueprintProjectSettingsChanged()
virtual void FBlueprintEditor::OnBlueprintProjectSettingsChanged (UObject * , struct FPropertyChangedEvent &) private virtual
OnBlueprintUnloaded()
void FBlueprintEditor::OnBlueprintUnloaded (UBlueprint * InBlueprint) protected
Handles the unloading of Blueprints (by closing the editor, if it operating on the Blueprint being unloaded)
OnChangeBreadCrumbGraph()
void FBlueprintEditor::OnChangeBreadCrumbGraph (class UEdGraph * InGraph) private
Helper to move focused graph when clicking on graph breadcrumb.
OnChangePinType()
void FBlueprintEditor::OnChangePinType () protected
OnChangePinTypeFinished()
void FBlueprintEditor::OnChangePinTypeFinished (const FEdGraphPinType & PinType, UEdGraphPin * SelectedPin) protected
OnClose()
virtual void FBlueprintEditor::OnClose () override virtual
Called when this toolkit is being closed.
Reimplemented from FWorkflowCentricApplication.
OnCollapseNodes()
void FBlueprintEditor::OnCollapseNodes () protected
OnCollapseSelectionToFunction()
void FBlueprintEditor::OnCollapseSelectionToFunction () protected
OnCollapseSelectionToMacro()
void FBlueprintEditor::OnCollapseSelectionToMacro () protected
OnComponentAddedToBlueprint()
virtual void FBlueprintEditor::OnComponentAddedToBlueprint (const FSubobjectData & NewSubobjectData) virtual
Delegate invoked when a new subobject is added in the subobject editor widget.
OnComponentDoubleClicked()
virtual void FBlueprintEditor::OnComponentDoubleClicked (TSharedPtr< class FSubobjectEditorTreeNode > Node) virtual
Delegate invoked when an item is double clicked in the subobject editor widget.
Referenced by UE_DEPRECATED().
OnConvertEventToFunction()
void FBlueprintEditor::OnConvertEventToFunction () protected
OnConvertFunctionToEvent()
void FBlueprintEditor::OnConvertFunctionToEvent () protected
OnCreateComment()
virtual void FBlueprintEditor::OnCreateComment () protected virtual
OnCreateCustomEvent()
virtual void FBlueprintEditor::OnCreateCustomEvent () protected virtual
Create custom event node on graph.
OnCreateGraphActionMenu()
FActionMenuContent FBlueprintEditor::OnCreateGraphActionMenu (UEdGraph * InGraph, const FVector2f & InNodePosition, const TArray< UEdGraphPin * > & InDraggedPins, bool bAutoExpand, SGraphEditor::FActionMenuClosed InOnMenuClosed) protected
References bAutoExpand, InDraggedPins, InNodePosition, InOnMenuClosed, and OnCreateGraphActionMenu().
Referenced by OnCreateGraphActionMenu().
OnCreateGraphEditorCommands()
virtual void FBlueprintEditor::OnCreateGraphEditorCommands (TSharedPtr< FUICommandList > GraphEditorCommandsList) inline private virtual
Definition at line 1651 of file BlueprintEditor.h.
OnCreateMatchingFunction()
void FBlueprintEditor::OnCreateMatchingFunction () protected
OnDisableBreakpoint()
void FBlueprintEditor::OnDisableBreakpoint () protected
OnDisallowedPinConnection()
void FBlueprintEditor::OnDisallowedPinConnection (const class UEdGraphPin * PinA, const class UEdGraphPin * PinB) private
Called when the user generates a warning tooltip because a connection was invalid.
OnDistributeNodesH()
void FBlueprintEditor::OnDistributeNodesH () protected
OnDistributeNodesV()
void FBlueprintEditor::OnDistributeNodesV () protected
OnDumpCachedIndexDataForBlueprint()
void FBlueprintEditor::OnDumpCachedIndexDataForBlueprint ()
Dumps the currently-cached index data for the blueprint to a file for debugging.
OnEditParentClassClicked()
FReply FBlueprintEditor::OnEditParentClassClicked () protected
Handler for "Edit parent class" button.
OnEditParentClassNativeCodeClicked()
void FBlueprintEditor::OnEditParentClassNativeCodeClicked ()
Handles opening the header file of native parent class.
OnEditTabClosed()
virtual void FBlueprintEditor::OnEditTabClosed (TSharedRef< SDockTab > Tab) protected virtual
OnEditTunnel()
void FBlueprintEditor::OnEditTunnel () private
OnEnableBreakpoint()
void FBlueprintEditor::OnEnableBreakpoint () protected
OnExpandNodes()
void FBlueprintEditor::OnExpandNodes () protected
OnFindParentClassInContentBrowserClicked()
FReply FBlueprintEditor::OnFindParentClassInContentBrowserClicked () protected
Handler for "Find parent class in CB" button.
OnFindReferences()
void FBlueprintEditor::OnFindReferences (bool bSearchAllBlueprints, const EGetFindReferenceSearchStringFlags Flags) private
Find all references of the selected node.
References Flags.
OnFinishedChangingProperties()
virtual void FBlueprintEditor::OnFinishedChangingProperties (const FPropertyChangedEvent & PropertyChangedEvent) protected virtual
Callback when properties have finished being handled.
OnGenerateSearchIndexForDebugging()
void FBlueprintEditor::OnGenerateSearchIndexForDebugging ()
Dumps the current blueprint search index to a JSON file for debugging purposes.
OnGetPinType()
FEdGraphPinType FBlueprintEditor::OnGetPinType (UEdGraphPin * SelectedPin) const protected
Functions for handling the changing of the pin's type (PinCategory, PinSubCategory, etc)
OnGoToDefinition()
void FBlueprintEditor::OnGoToDefinition () private
Called when the user wants to jump to a node's definition.
OnGoToDocumentation()
void FBlueprintEditor::OnGoToDocumentation () private
Open documentation for the selected node class.
OnGraphActionMenuClosed()
void FBlueprintEditor::OnGraphActionMenuClosed (bool bActionExecuted, bool bContextSensitiveChecked, bool bGraphPinContext) protected
Called from graph context menus when they close to tell the editor why they closed.
References OnGraphActionMenuClosed().
Referenced by OnGraphActionMenuClosed().
OnGraphEditorBackgrounded()
virtual void FBlueprintEditor::OnGraphEditorBackgrounded (const TSharedRef< SGraphEditor > & InGraphEditor) virtual
Called when the graph editor tab is backgrounded.
OnGraphEditorDropActor()
void FBlueprintEditor::OnGraphEditorDropActor (const TArray< TWeakObjectPtr< AActor > > & Actors, UEdGraph * Graph, const FVector2f & DropLocation) protected
Called when an actor is dropped onto the graph editor.
References Actors.
OnGraphEditorDropStreamingLevel()
void FBlueprintEditor::OnGraphEditorDropStreamingLevel (const TArray< TWeakObjectPtr< ULevelStreaming > > & Levels, UEdGraph * Graph, const FVector2f & DropLocation) protected
Called when a streaming level is dropped onto the graph editor.
OnGraphEditorFocused()
virtual void FBlueprintEditor::OnGraphEditorFocused (const TSharedRef< class SGraphEditor > & InGraphEditor) virtual
Called when graph editor focus is changed.
OnGraphEditorQuickJump()
void FBlueprintEditor::OnGraphEditorQuickJump (int32 BookmarkIndex) protected
Handles activation of a graph editor "quick jump" command.
OnInsertExecutionPin()
void FBlueprintEditor::OnInsertExecutionPin (EPinInsertPosition Position) protected
References Position.
OnInsertExecutionPinAfter()
void FBlueprintEditor::OnInsertExecutionPinAfter () protected
OnInsertExecutionPinBefore()
void FBlueprintEditor::OnInsertExecutionPinBefore () protected
OnListObjectsReferencedByBlueprint()
void FBlueprintEditor::OnListObjectsReferencedByBlueprint () protected
OnListObjectsReferencedByClass()
void FBlueprintEditor::OnListObjectsReferencedByClass () protected
OnLockNodeStateCheckStateChanged()
void FBlueprintEditor::OnLockNodeStateCheckStateChanged (ECheckBoxState NewCheckedState)
References OnLockNodeStateCheckStateChanged().
Referenced by OnLockNodeStateCheckStateChanged().
OnLogTokenClicked()
void FBlueprintEditor::OnLogTokenClicked (const TSharedRef< class IMessageToken > & Token) private
Callback when a token is clicked on in the compiler results log.
OnlyShowCustomDebugObjects()
virtual bool FBlueprintEditor::OnlyShowCustomDebugObjects () const inline virtual
If returns true only the custom debug list will be used.
Definition at line 736 of file BlueprintEditor.h.
OnModeSet()
FOnModeSet & FBlueprintEditor::OnModeSet () inline
Definition at line 236 of file BlueprintEditor.h.
References OnModeSetData.
OnNodeDoubleClicked()
void FBlueprintEditor::OnNodeDoubleClicked (UEdGraphNode * Node) protected
OnNodeSpawnedByKeymap()
void FBlueprintEditor::OnNodeSpawnedByKeymap ()
Called when node is spawned by keymap.
References OnNodeSpawnedByKeymap().
Referenced by OnNodeSpawnedByKeymap().
OnNodeTitleCommitted()
void FBlueprintEditor::OnNodeTitleCommitted (const FText & NewText, ETextCommit::Type CommitInfo, UEdGraphNode * NodeBeingChanged)
Called when a node's title is committed for a rename.
OnNodeVerifyTitleCommit()
bool FBlueprintEditor::OnNodeVerifyTitleCommit (const FText & NewText, UEdGraphNode * NodeBeingChanged, FText & OutErrorMessage) protected
Called when a node's title is being committed for a rename so it can be verified.
OnPasteNewLocalVariable()
virtual void FBlueprintEditor::OnPasteNewLocalVariable (const FBPVariableDescription & VariableDescription) virtual
Pastes a new local variable to the focused function graph.
OnPostObjectPropertyChanged()
void FBlueprintEditor::OnPostObjectPropertyChanged (UObject * InObject, FPropertyChangedEvent & PropertyChangedEvent) protected
Called after a property change has been propagated to instances of the Blueprint.
OnPreObjectPropertyChanged()
void FBlueprintEditor::OnPreObjectPropertyChanged (UObject * InObject, const FEditPropertyChain & EditPropertyChain) protected
Called when a property change is about to be propagated to instances of the Blueprint.
OnPromoteSelectionToFunction()
void FBlueprintEditor::OnPromoteSelectionToFunction () protected
OnPromoteSelectionToMacro()
void FBlueprintEditor::OnPromoteSelectionToMacro () protected
OnPromoteToVariable()
void FBlueprintEditor::OnPromoteToVariable (bool bInToMemberVariable) protected
References bInToMemberVariable.
OnRecombineStructPin()
void FBlueprintEditor::OnRecombineStructPin () protected
OnRefresh()
FOnRefreshEvent & FBlueprintEditor::OnRefresh () inline
Definition at line 1573 of file BlueprintEditor.h.
References OnRefresh(), and RefreshEvent.
Referenced by OnRefresh().
OnRemoveBreakpoint()
void FBlueprintEditor::OnRemoveBreakpoint () protected
OnRemoveExecutionPin()
void FBlueprintEditor::OnRemoveExecutionPin () protected
OnRemoveOptionPin()
void FBlueprintEditor::OnRemoveOptionPin () protected
OnRemoveOtherStructVarPins()
void FBlueprintEditor::OnRemoveOtherStructVarPins () protected
OnRemoveThisStructVarPin()
void FBlueprintEditor::OnRemoveThisStructVarPin () protected
OnRenameNode()
void FBlueprintEditor::OnRenameNode () protected
On starting to rename node.
OnRepairCorruptedBlueprint()
void FBlueprintEditor::OnRepairCorruptedBlueprint () protected
OnRequestClose()
virtual bool FBlueprintEditor::OnRequestClose (EAssetEditorCloseReason InCloseReason) override virtual
Called when this toolkit is requested to close.
Returns false if closing should be prevented.
Reimplemented from FWorkflowCentricApplication.
Reimplemented in FWidgetBlueprintEditor.
OnResetPinToDefaultValue()
void FBlueprintEditor::OnResetPinToDefaultValue () protected
OnRestoreAllStructVarPins()
void FBlueprintEditor::OnRestoreAllStructVarPins () protected
OnSelectedNodesChanged()
void FBlueprintEditor::OnSelectedNodesChanged (const TSet< class UObject * > & NewSelection) inline protected
Called when the selection changes in the GraphEditor.
Definition at line 884 of file BlueprintEditor.h.
References OnSelectedNodesChangedImpl().
OnSelectedNodesChangedImpl()
virtual void FBlueprintEditor::OnSelectedNodesChangedImpl (const TSet< class UObject * > & NewSelection) protected virtual
Called when the selection changes in the GraphEditor.
Referenced by OnSelectedNodesChanged().
OnSelectionUpdated()
virtual void FBlueprintEditor::OnSelectionUpdated (const TArray< TSharedPtr< class FSubobjectEditorTreeNode > > & SelectedNodes) virtual
Delegate invoked when the selection is changed in the subobject editor widget.
Referenced by UE_DEPRECATED().
OnSelectReferenceInLevel()
void FBlueprintEditor::OnSelectReferenceInLevel () protected
OnSetEnabledStateForSelectedNodes()
void FBlueprintEditor::OnSetEnabledStateForSelectedNodes (ENodeEnabledState NewState) private
Set the enabled state for currently-selected nodes.
OnSpawnGraphNodeByShortcut()
virtual FReply FBlueprintEditor::OnSpawnGraphNodeByShortcut (FInputChord InChord, const FVector2f & InPosition, UEdGraph * InGraph) virtual
References InPosition, and OnSpawnGraphNodeByShortcut().
Referenced by OnSpawnGraphNodeByShortcut().
OnSplitStructPin()
void FBlueprintEditor::OnSplitStructPin () protected
OnStackNodesH()
void FBlueprintEditor::OnStackNodesH () protected
OnStackNodesV()
void FBlueprintEditor::OnStackNodesV () protected
OnStartEditingDefaultsClicked()
void FBlueprintEditor::OnStartEditingDefaultsClicked () protected
Start editing the defaults for this blueprint.
OnStartWatchingPin()
virtual void FBlueprintEditor::OnStartWatchingPin () protected virtual
OnStopWatchingPin()
virtual void FBlueprintEditor::OnStopWatchingPin () protected virtual
OnStraightenConnections()
void FBlueprintEditor::OnStraightenConnections () protected
OnToggleBreakpoint()
void FBlueprintEditor::OnToggleBreakpoint () protected
OpenBlueprintDebugger()
void FBlueprintEditor::OpenBlueprintDebugger () protected
Spawns a new blueprint debugger tab.
OpenDocument()
TSharedPtr< SDockTab > FBlueprintEditor::OpenDocument (const UObject * DocumentID, FDocumentTracker::EOpenDocumentCause Cause)
References OpenDocument().
Referenced by OpenDocument().
OpenGraphAndBringToFront()
virtual TSharedPtr< SGraphEditor > FBlueprintEditor::OpenGraphAndBringToFront (UEdGraph * Graph, bool bSetFocus = true) override virtual
Tries to open the specified graph and bring it's document to the front (note: this can return NULL)
Implements IBlueprintEditor.
PasteGeneric()
virtual void FBlueprintEditor::PasteGeneric () protected virtual
Paste Variable Definition or Nodes.
PasteNodes()
virtual void FBlueprintEditor::PasteNodes () protected virtual
PasteNodesHere()
virtual void FBlueprintEditor::PasteNodesHere (class UEdGraph * DestinationGraph, const FVector2f & GraphLocation) override protected virtual
Paste on graph at specific location.
Implements IBlueprintEditor.
PostLayoutBlueprintEditorInitialization()
void FBlueprintEditor::PostLayoutBlueprintEditorInitialization ()
PostRedo()
virtual void FBlueprintEditor::PostRedo (bool bSuccess) override protected virtual
Signal that client should run any PostRedo code.
Parameters
bSuccess If true than redo succeeded, false if redo failed
Reimplemented from FEditorUndoClient.
Reimplemented in FWidgetBlueprintEditor.
PostRegenerateMenusAndToolbars()
virtual void FBlueprintEditor::PostRegenerateMenusAndToolbars () override protected virtual
Recreates the overlay on the menu bar.
Reimplemented from FAssetEditorToolkit.
PostUndo()
virtual void FBlueprintEditor::PostUndo (bool bSuccess) override protected virtual
Signal that client should run any PostUndo code.
Parameters
bSuccess If true than undo succeeded, false if undo failed
Reimplemented from FEditorUndoClient.
Reimplemented in FWidgetBlueprintEditor.
ReconnectExecPins()
void FBlueprintEditor::ReconnectExecPins (class UK2Node * Node) protected
Given a node, make connections from anything connected to it's input pin to anything connected to it's "then" pins.
Only works on impure nodes with single exec/then pins.
Parameters
Node The node to reconnect
RedoGraphAction()
void FBlueprintEditor::RedoGraphAction () protected
Called to redo the last undone action.
RefreshAllNodes_OnClicked()
void FBlueprintEditor::RefreshAllNodes_OnClicked ()
Called when the refresh all nodes button is clicked.
RefreshEditors()
virtual void FBlueprintEditor::RefreshEditors (ERefreshBlueprintEditorReason::Type Reason = ERefreshBlueprintEditorReason::UnknownReason) override virtual
Implements IBlueprintEditor.
References ERefreshBlueprintEditorReason::UnknownReason.
RefreshInspector()
virtual void FBlueprintEditor::RefreshInspector () virtual
Implements IBlueprintEditor.
RefreshMyBlueprint()
virtual void FBlueprintEditor::RefreshMyBlueprint () virtual
Implements IBlueprintEditor.
RefreshStandAloneDefaultsEditor()
void FBlueprintEditor::RefreshStandAloneDefaultsEditor () protected
RegisterApplicationModes()
virtual void FBlueprintEditor::RegisterApplicationModes (const TArray< UBlueprint * > & InBlueprints, bool bShouldOpenInDefaultsMode, bool bNewlyCreated = false) protected virtual
Called during initialization of the blueprint editor to register any application modes.
Reimplemented in FWidgetBlueprintEditor.
RegisterMenus()
void FBlueprintEditor::RegisterMenus () protected
Register Menus.
RegisterSCSEditorCustomization()
void FBlueprintEditor::RegisterSCSEditorCustomization (const FName & InComponentName, TSharedPtr< class ISCSEditorCustomization > InCustomization)
Register a customization for interacting with the subobject editor.
Parameters
InComponentName The name of the component to customize behavior for
InCustomization The customization instance to use
RegisterTabSpawners()
virtual void FBlueprintEditor::RegisterTabSpawners (const TSharedRef< class FTabManager > & TabManager) override virtual
IToolkit interface.
Reimplemented from FWorkflowCentricApplication.
References FAssetEditorToolkit::TabManager.
RegisterToolbarTab()
void FBlueprintEditor::RegisterToolbarTab (const TSharedRef< class FTabManager > & TabManager)
References FAssetEditorToolkit::TabManager.
RemoveBookmark()
void FBlueprintEditor::RemoveBookmark (const FGuid & BookmarkNodeId, bool bRefreshUI = true)
Removes the bookmark node with the given ID.
RemoveNamespace()
void FBlueprintEditor::RemoveNamespace (const FString & InNamespace)
Removes the given namespace from the editor's current import context.
However, this will NOT unload any associated macro and/or function library assets.
RenameBookmark()
void FBlueprintEditor::RenameBookmark (const FGuid & BookmarkNodeId, const FText & NewName)
Renames the bookmark node with the given ID.
RenameNewlyAddedAction()
void FBlueprintEditor::RenameNewlyAddedAction (FName InActionName)
Utility function to handle all steps required to rename a newly added action.
ReparentBlueprint_Clicked()
void FBlueprintEditor::ReparentBlueprint_Clicked ()
Reparent the current blueprint.
ReparentBlueprint_IsVisible()
virtual bool FBlueprintEditor::ReparentBlueprint_IsVisible () const virtual
ReparentBlueprint_NewParentChosen()
void FBlueprintEditor::ReparentBlueprint_NewParentChosen (UClass * ChosenClass)
RequestSaveEditedObjectState()
void FBlueprintEditor::RequestSaveEditedObjectState ()
ResetAllNodesUnrelatedStates()
void FBlueprintEditor::ResetAllNodesUnrelatedStates () protected
Focus nodes which are related to the selected nodes.
RestoreEditedObjectState()
void FBlueprintEditor::RestoreEditedObjectState ()
Create new tab for each element of LastEditedObjects array.
SaveEditedObjectState()
void FBlueprintEditor::SaveEditedObjectState ()
Save the current set of edited objects in the LastEditedObjects array so it will be opened next time we open K2.
SaveEditorSettings()
virtual void FBlueprintEditor::SaveEditorSettings () private virtual
Saves editor settings to disk (docking state, window pos/size, option state, etc).
SelectAllNodes()
void FBlueprintEditor::SelectAllNodes () protected
SelectAndDuplicateNode()
void FBlueprintEditor::SelectAndDuplicateNode (UEdGraphNode * InNode)
Duplicates an EdGraphNode using selection and copy / paste functionality.
SelectGraphActionItemByName()
void FBlueprintEditor::SelectGraphActionItemByName (const FName & ItemName, ESelectInfo::Type SelectInfo = ESelectInfo::Direct, int32 SectionId = INDEX_NONE, bool bIsCategory = false)
References INDEX_NONE.
SelectLocalVariable()
virtual bool FBlueprintEditor::SelectLocalVariable (const UEdGraph * Graph, const FName & VariableName) inline virtual
Selects a local variable to load in the details panel.
Definition at line 804 of file BlueprintEditor.h.
SetCurrentMode()
virtual void FBlueprintEditor::SetCurrentMode (FName NewMode) override virtual
Reimplemented from FWorkflowCentricApplication.
SetDetailsCustomization()
void FBlueprintEditor::SetDetailsCustomization (TSharedPtr< class FDetailsViewObjectFilter > DetailsObjectFilter, TSharedPtr< class IDetailRootObjectCustomization > DetailsRootCustomization)
Sets customizations for the BP editor details panel.
References SetDetailsCustomization().
Referenced by SetDetailsCustomization().
SetGraphEditorQuickJump()
void FBlueprintEditor::SetGraphEditorQuickJump (int32 BookmarkIndex) protected
Binds a graph editor "quick jump" to the command at the given index.
SetKeyboardFocus()
void FBlueprintEditor::SetKeyboardFocus ()
Ensures the blueprint has keyboard focus.
SetPinVisibility()
void FBlueprintEditor::SetPinVisibility (SGraphEditor::EPinVisibility Visibility)
Pin visibility accessors.
References Visibility.
SetSubobjectEditorUICustomization()
void FBlueprintEditor::SetSubobjectEditorUICustomization (TSharedPtr< class ISCSEditorUICustomization > SCSEditorUICustomization)
Sets subobject editor UI customization.
References SetSubobjectEditorUICustomization().
Referenced by SetSubobjectEditorUICustomization(), and UE_DEPRECATED().
SetUISelectionState()
void FBlueprintEditor::SetUISelectionState (FName SelectionOwner)
SetupGraphEditorEvents()
virtual void FBlueprintEditor::SetupGraphEditorEvents (UEdGraph * InGraph, SGraphEditor::FGraphEditorEvents & InEvents) protected virtual
Setup all the events that the graph editor can handle.
SetupViewForBlueprintEditingMode()
void FBlueprintEditor::SetupViewForBlueprintEditingMode ()
SetViewLocation()
void FBlueprintEditor::SetViewLocation (const FVector2D & Location, float ZoomAmount, const FGuid & BookmarkId = FGuid())
Sets the focused graph view location/zoom amount.
References Location.
ShouldLoadBPLibrariesFromAssetRegistry()
virtual bool FBlueprintEditor::ShouldLoadBPLibrariesFromAssetRegistry () inline virtual
Definition at line 549 of file BlueprintEditor.h.
ShouldShowPublicViewControl()
bool FBlueprintEditor::ShouldShowPublicViewControl () const protected
Callback to determine visibility of the public view checkbox in the Defaults editor.
StartEditingDefaults()
virtual void FBlueprintEditor::StartEditingDefaults (bool bAutoFocus = true, bool bForceRefresh = false) virtual
Virtual override point for editing defaults; allowing more derived editors to edit something else.
SummonFindAndReplaceUI()
virtual void FBlueprintEditor::SummonFindAndReplaceUI () override virtual
Invokes the Find and Replace UI.
Implements IBlueprintEditor.
SummonSearchUI()
virtual void FBlueprintEditor::SummonSearchUI (bool bSetFindWithinBlueprint, FString NewSearchTerms = FString(), bool bSelectFirstResult = false) override virtual
Invokes the search UI and sets the mode and search terms optionally.
Implements IBlueprintEditor.
Tick()
virtual void FBlueprintEditor::Tick (float DeltaTime) override virtual
Pure virtual that must be overloaded by the inheriting class.
It will be called at different times in the frame depending on the subclass.
Parameters
DeltaTime Game time passed since the last call.
Implements FTickableObjectBase.
Reimplemented in FWidgetBlueprintEditor.
References DeltaTime.
ToggleHideUnrelatedNodes()
void FBlueprintEditor::ToggleHideUnrelatedNodes ()
Make nodes which are unrelated to the selected nodes fade out.
ToggleSaveIntermediateBuildProducts()
void FBlueprintEditor::ToggleSaveIntermediateBuildProducts () protected
TransactionObjectAffectsBlueprint()
virtual bool FBlueprintEditor::TransactionObjectAffectsBlueprint (UObject * InTransactedObject) virtual
TryInvokingDetailsTab()
void FBlueprintEditor::TryInvokingDetailsTab (bool bFlash = true) protected
Attempts to invoke the details tab if it's currently possible to.
UE_DEPRECATED() [1/12]
FBlueprintEditor::UE_DEPRECATED (5. 0, "CustomizeSCSEditor has been deprecated. Use CustomizeSubobjectEditor instead.") const inline
Definition at line 726 of file BlueprintEditor.h.
References CustomizeSubobjectEditor().
UE_DEPRECATED() [2/12]
FBlueprintEditor::UE_DEPRECATED (5. 0, "FindAndSelectSCSEditorTreeNode has been deprecated. Use FindAndSelectSubobjectEditorTreeNode instead.") const
References UE_DEPRECATED().
UE_DEPRECATED() [3/12]
FBlueprintEditor::UE_DEPRECATED (5. 0, "GetSCSEditor has been deprecated. Use GetSubobjectEditor instead.") const inline
Getters for the various optional Kismet2 widgets.
Definition at line 341 of file BlueprintEditor.h.
UE_DEPRECATED() [4/12]
FBlueprintEditor::UE_DEPRECATED (5. 0, "GetSelectedSCSEditorTreeNodes has been deprecated. Use GetSelectedSubobjectEditorTreeNodes instead.") const override virtual
Implements IBlueprintEditor.
References override.
Referenced by UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
UE_DEPRECATED() [5/12]
FBlueprintEditor::UE_DEPRECATED (5. 0, "OnComponentDoubleClicked(TSharedPtr<class FSCSEditorTreeNode>) has been deprecated. Use OnComponentDoubleClicked(TSharedPtr<class FSubobjectEditorTreeNode>) instead.") inline
Delegate invoked when an item is double clicked in the subobject editor widget.
Definition at line 585 of file BlueprintEditor.h.
References OnComponentDoubleClicked().
UE_DEPRECATED() [6/12]
FBlueprintEditor::UE_DEPRECATED (5. 0, "OnSelectionUpdated(const TArray<TSharedPtr<class FSCSEditorTreeNode>>&) has been deprecated. Use OnSelectionUpdated(const TArray<TSharedPtr<class FSubobjectEditorTreeNode>>&) instead.") const & inline
Delegate invoked when the selection is changed in the subobject editor widget.
Definition at line 581 of file BlueprintEditor.h.
References OnSelectionUpdated().
UE_DEPRECATED() [7/12]
FBlueprintEditor::UE_DEPRECATED (5. 0, "SetSCSEditorUICustomization has been deprecated. Use SetSubobjectEditorUICustomization instead.") inline
Definition at line 687 of file BlueprintEditor.h.
References SetSubobjectEditorUICustomization(), and UE_DEPRECATED().
UE_DEPRECATED() [8/12]
FBlueprintEditor::UE_DEPRECATED (5. 0, "The Toggle Hide Unrelated Nodes button is always shown now") const
References bool.
UE_DEPRECATED() [9/12]
FBlueprintEditor::UE_DEPRECATED (5. 1, "Please use GetPinTypeSelectorFilters") const inline override
Definition at line 296 of file BlueprintEditor.h.
References ImportedPinTypeSelectorFilter.
UE_DEPRECATED() [10/12]
FBlueprintEditor::UE_DEPRECATED (5. 6, "Please use the version of the function accepting FVector2f.")
Handles spawning a graph node in the current graph using the passed in chord.
UE_DEPRECATED() [11/12]
FBlueprintEditor::UE_DEPRECATED (5. 6, "Please use the version of the function taking FVector2f.") protected
Called to create context menu when right-clicking on graph.
UE_DEPRECATED() [12/12]
FBlueprintEditor::UE_DEPRECATED (5. 6, "Use the version of this function accepting a TOptional")
Perform the actual promote to variable action on the given pin in the given blueprint.
Parameters
InBlueprint The blueprint in which to create the variable.
InTargetPin The pin on which to base the variable.
bInToMemberVariable TRUE if attempting to create a member variable, FALSE if the variable should be local
InOptionalLocation Where the new node should be placed. If null, a fixed offset from the parent node will be used.
References UE_DEPRECATED().
UndoGraphAction()
void FBlueprintEditor::UndoGraphAction () protected
Called to undo the last action.
UnregisterSCSEditorCustomization()
void FBlueprintEditor::UnregisterSCSEditorCustomization (const FName & InComponentName)
Unregister a previously registered customization for interacting with the subobject editor.
Parameters
InComponentName The name of the component to customize behavior for
UpdateNodeCreationStats()
void FBlueprintEditor::UpdateNodeCreationStats (const ENodeCreateAction::Type CreateAction)
Update Node Creation mechanisms for analytics.
References UpdateNodeCreationStats().
Referenced by UpdateNodeCreationStats().
UpdateNodesUnrelatedStatesAfterGraphChange()
void FBlueprintEditor::UpdateNodesUnrelatedStatesAfterGraphChange ()
Update all nodes' unrelated states when the graph has changed.
UpdatePreviewActor()
void FBlueprintEditor::UpdatePreviewActor (UBlueprint * InBlueprint, bool bInForceFullUpdate = false)
Creates/updates the preview actor for the given blueprint.
Parameters
InBlueprint The Blueprint to create or update the preview for.
bInForceFullUpdate Force a full update to respawn actors.
UpdateSubobjectPreview()
void FBlueprintEditor::UpdateSubobjectPreview (bool bUpdateNow = false)
Refresh the preview viewport to reflect changes in the subobject.
VariableListWasUpdated()
void FBlueprintEditor::VariableListWasUpdated ()
Variable list window calls this after it is updated.
ZoomToSelection_Clicked()
void FBlueprintEditor::ZoomToSelection_Clicked () protected
ZoomToWindow_Clicked()
void FBlueprintEditor::ZoomToWindow_Clicked () protected
Field Documentation
AnalyticsStats
FAnalyticsStatistics FBlueprintEditor::AnalyticsStats private
analytics statistics for the Editor
Definition at line 1618 of file BlueprintEditor.h.
bAutoExpand
const FVector2D const TArray<UEdGraphPin*> bool FBlueprintEditor::bAutoExpand protected
Definition at line 894 of file BlueprintEditor.h.
Referenced by OnCreateGraphActionMenu().
bBlueprintModifiedOnOpen
bool FBlueprintEditor::bBlueprintModifiedOnOpen protected
Did we update the blueprint when it opened.
Definition at line 1502 of file BlueprintEditor.h.
bCodeBasedProject
bool FBlueprintEditor::bCodeBasedProject private
Whether the current project is C++ or blueprint based.
Definition at line 1624 of file BlueprintEditor.h.
bEditorMarkedAsClosed
bool FBlueprintEditor::bEditorMarkedAsClosed protected
Whether we are already in the process of closing this editor.
Definition at line 1514 of file BlueprintEditor.h.
bHideUnrelatedNodes
bool FBlueprintEditor::bHideUnrelatedNodes protected
If true, fade out nodes which are unrelated to the selected nodes automatically.
Definition at line 1523 of file BlueprintEditor.h.
bInToMemberVariable
UEdGraphPin bool FBlueprintEditor::bInToMemberVariable
Definition at line 672 of file BlueprintEditor.h.
Referenced by CanPromoteToVariable(), DoPromoteToVariable2f(), and OnPromoteToVariable().
bIsActionMenuContextSensitive
bool FBlueprintEditor::bIsActionMenuContextSensitive protected
Whether the graph action menu should be sensitive to the pins dragged off of.
Definition at line 1508 of file BlueprintEditor.h.
Referenced by GetIsContextSensitive().
bIsReparentingBlueprint
bool FBlueprintEditor::bIsReparentingBlueprint protected
True if the current blueprint is in the process of being reparented.
Definition at line 1406 of file BlueprintEditor.h.
bLockNodeFadeState
bool FBlueprintEditor::bLockNodeFadeState protected
Lock the current fade state of each node.
Definition at line 1526 of file BlueprintEditor.h.
BlueprintEditorSettingsChangedHandle
FDelegateHandle FBlueprintEditor::BlueprintEditorSettingsChangedHandle private
Delegate handle registered for when settings change.
Definition at line 1638 of file BlueprintEditor.h.
BlueprintProjectSettingsChangedHandle
FDelegateHandle FBlueprintEditor::BlueprintProjectSettingsChangedHandle private
Definition at line 1639 of file BlueprintEditor.h.
BookmarksWidget
TSharedPtr<class SBlueprintBookmarks> FBlueprintEditor::BookmarksWidget protected
Blueprint bookmark editing widget.
Definition at line 1442 of file BlueprintEditor.h.
Referenced by GetBookmarksWidget().
bPendingDeferredClose
bool FBlueprintEditor::bPendingDeferredClose protected
Flags if this blueprint editor should close on its next tick.
Definition at line 1409 of file BlueprintEditor.h.
bRequestedSavingOpenDocumentState
bool FBlueprintEditor::bRequestedSavingOpenDocumentState protected
Has someone requested a deferred update of the saved document state?
Definition at line 1499 of file BlueprintEditor.h.
bSaveIntermediateBuildProducts
bool FBlueprintEditor::bSaveIntermediateBuildProducts protected
Should intermediate build products be saved when recompiling?
Definition at line 1403 of file BlueprintEditor.h.
bSelectRegularNode
bool FBlueprintEditor::bSelectRegularNode protected
If a regular node (not a comment node) has been selected.
Definition at line 1529 of file BlueprintEditor.h.
bWasOpenedInDefaultsMode
bool FBlueprintEditor::bWasOpenedInDefaultsMode protected
True if the editor was opened in defaults mode.
Definition at line 1532 of file BlueprintEditor.h.
CachedNumErrors
int32 FBlueprintEditor::CachedNumErrors protected
Definition at line 1456 of file BlueprintEditor.h.
CachedNumWarnings
int32 FBlueprintEditor::CachedNumWarnings protected
Limited cache of last compile results.
Definition at line 1455 of file BlueprintEditor.h.
CompilerResults
TSharedPtr<class SWidget> FBlueprintEditor::CompilerResults protected
Compiler results log, with the log listing that it reflects.
Definition at line 1451 of file BlueprintEditor.h.
Referenced by GetCompilerResults().
CompilerResultsListing
TSharedPtr<class IMessageLogListing> FBlueprintEditor::CompilerResultsListing protected
Definition at line 1452 of file BlueprintEditor.h.
CompositePinTypeSelectorFilter
TSharedPtr<class IPinTypeSelectorFilter> FBlueprintEditor::CompositePinTypeSelectorFilter protected
Filter used to compose multiple pin type filters together.
Definition at line 1491 of file BlueprintEditor.h.
CurrentUISelection
FName FBlueprintEditor::CurrentUISelection protected
The current UI selection state of this editor.
Definition at line 1511 of file BlueprintEditor.h.
Referenced by GetUISelectionState().
DefaultEditor
TSharedPtr<class SKismetInspector> FBlueprintEditor::DefaultEditor protected
defaults inspector widget
Definition at line 1436 of file BlueprintEditor.h.
Referenced by GetDefaultEditor().
DeferredNamespaceImports
TSet<FString> FBlueprintEditor::DeferredNamespaceImports protected
Pending set of namespaces to be auto-imported on the next tick.
Definition at line 1494 of file BlueprintEditor.h.
DocumentManager
TSharedPtr<FDocumentTracker> FBlueprintEditor::DocumentManager
Definition at line 1384 of file BlueprintEditor.h.
FindResults
TSharedPtr<class SFindInBlueprints> FBlueprintEditor::FindResults protected
Find results log as well as the search filter.
Definition at line 1459 of file BlueprintEditor.h.
Referenced by GetFindResults().
FocusedGraphEdPtr
TWeakPtr<class SGraphEditor> FBlueprintEditor::FocusedGraphEdPtr protected
Currently focused graph editor.
Definition at line 1412 of file BlueprintEditor.h.
GraphEditorCommands
TSharedPtr<FUICommandList> FBlueprintEditor::GraphEditorCommands private
Command list for the graph editor.
Definition at line 1588 of file BlueprintEditor.h.
GraphEditorTabFactoryPtr
TWeakPtr<FDocumentTabFactory> FBlueprintEditor::GraphEditorTabFactoryPtr protected
Factory that spawns graph editors; used to look up all tabs spawned by it.
Definition at line 1415 of file BlueprintEditor.h.
HasOpenActionMenu
UEdGraph* FBlueprintEditor::HasOpenActionMenu private
When set, flags which graph has a action menu currently open (if null, no graphs do).
Definition at line 1630 of file BlueprintEditor.h.
ImportedClassViewerFilter
TSharedPtr<class IClassViewerFilter> FBlueprintEditor::ImportedClassViewerFilter protected
Filter used to restrict class viewer widgets in the editor context to imported namespaces only.
Definition at line 1482 of file BlueprintEditor.h.
Referenced by GetImportedClassViewerFilter().
ImportedNamespaceHelper
TSharedPtr<FBlueprintNamespaceHelper> FBlueprintEditor::ImportedNamespaceHelper protected
Imported namespace helper utility object.
Definition at line 1479 of file BlueprintEditor.h.
ImportedPinTypeSelectorFilter
TSharedPtr<class IPinTypeSelectorFilter> FBlueprintEditor::ImportedPinTypeSelectorFilter protected
Filter used to restrict pin type selector widgets in the editor context to imported namespaces only.
Definition at line 1485 of file BlueprintEditor.h.
Referenced by UE_DEPRECATED().
InDraggedPins
const FVector2D const TArray<UEdGraphPin*>& FBlueprintEditor::InDraggedPins protected
Definition at line 894 of file BlueprintEditor.h.
Referenced by OnCreateGraphActionMenu().
InNodePosition
const FVector2D& FBlueprintEditor::InNodePosition protected
Definition at line 894 of file BlueprintEditor.h.
Referenced by OnCreateGraphActionMenu().
InOnMenuClosed
const FVector2D const TArray<UEdGraphPin*> bool SGraphEditor::FActionMenuClosed FBlueprintEditor::InOnMenuClosed protected
Definition at line 894 of file BlueprintEditor.h.
Referenced by OnCreateGraphActionMenu().
InOptionalLocation
UEdGraphPin bool const FVector2D* FBlueprintEditor::InOptionalLocation = nullptr)
Definition at line 672 of file BlueprintEditor.h.
Referenced by DoPromoteToVariable2f().
InPosition
const FVector2D& FBlueprintEditor::InPosition
Definition at line 660 of file BlueprintEditor.h.
Referenced by OnSpawnGraphNodeByShortcut().
Inspector
TSharedPtr<class SKismetInspector> FBlueprintEditor::Inspector protected
Node inspector widget.
Definition at line 1433 of file BlueprintEditor.h.
Referenced by GetInspector().
InstructionsFadeCountdown
float FBlueprintEditor::InstructionsFadeCountdown private
Used to nicely fade instruction text, when the context menu is opened.
Definition at line 1632 of file BlueprintEditor.h.
InTargetPin
UEdGraphPin* FBlueprintEditor::InTargetPin
Definition at line 672 of file BlueprintEditor.h.
Referenced by DoPromoteToVariable2f().
MergeTool
TWeakPtr<class SDockTab> FBlueprintEditor::MergeTool protected
Merge tool - WeakPtr because it's owned by the GlobalTabManager.
Definition at line 1462 of file BlueprintEditor.h.
ModifyDuringPIEStatus
ESafeToModifyDuringPIEStatus FBlueprintEditor::ModifyDuringPIEStatus = ESafeToModifyDuringPIEStatus::Unknown mutable private
Definition at line 1648 of file BlueprintEditor.h.
MyBlueprintWidget
TSharedPtr<class SMyBlueprint> FBlueprintEditor::MyBlueprintWidget protected
All of this blueprints' functions and variables.
Definition at line 1445 of file BlueprintEditor.h.
Referenced by GetMyBlueprintWidget().
NameEntryPopupWindow
TWeakPtr<class SWindow> FBlueprintEditor::NameEntryPopupWindow protected
Reference to owner of the current popup.
Definition at line 1467 of file BlueprintEditor.h.
NameEntryValidator
TSharedPtr<class INameValidatorInterface> FBlueprintEditor::NameEntryValidator protected
Reference to helper object to validate names in popup.
Definition at line 1470 of file BlueprintEditor.h.
OnActiveTabChangedDelegateHandle
FDelegateHandle FBlueprintEditor::OnActiveTabChangedDelegateHandle private
Handle to the registered OnActiveTabChanged delegate.
Definition at line 1635 of file BlueprintEditor.h.
OnMergeResolved
FOnMergeResolved FBlueprintEditor::OnMergeResolved protected
Merge tool - Delegate to call when the merge tool is closed.
Definition at line 1464 of file BlueprintEditor.h.
OnModeSetData
FOnModeSet FBlueprintEditor::OnModeSetData private
Delegates that are fired when the blueprint editor changes modes.
Definition at line 1627 of file BlueprintEditor.h.
Referenced by OnModeSet().
OnSetPinVisibility
FOnSetPinVisibility FBlueprintEditor::OnSetPinVisibility protected
Definition at line 1496 of file BlueprintEditor.h.
override
bool IsCntrlDown FBlueprintEditor::override { return nullptr
Definition at line 288 of file BlueprintEditor.h.
Referenced by UE_DEPRECATED().
Palette
TSharedPtr<class SBlueprintPalette> FBlueprintEditor::Palette protected
Palette of all classes with funcs/vars.
Definition at line 1439 of file BlueprintEditor.h.
PermissionsPinTypeSelectorFilter
TSharedPtr<class IPinTypeSelectorFilter> FBlueprintEditor::PermissionsPinTypeSelectorFilter protected
Filter used to restrict pin type selector widgets to those which permissions allow.
Definition at line 1488 of file BlueprintEditor.h.
PinTypeChangeMenu
TWeakPtr<class IMenu> FBlueprintEditor::PinTypeChangeMenu protected
Reference to owner of the pin type change popup.
Definition at line 1473 of file BlueprintEditor.h.
PinVisibility
SGraphEditor::EPinVisibility FBlueprintEditor::PinVisibility protected
Whether to hide unused pins or not.
Definition at line 1505 of file BlueprintEditor.h.
Referenced by GetPinVisibility().
PreviewActorPtr
TWeakObjectPtr<AActor> FBlueprintEditor::PreviewActorPtr mutable protected
The preview actor representing the current preview.
Definition at line 1520 of file BlueprintEditor.h.
PreviewScene
FPreviewScene FBlueprintEditor::PreviewScene protected
Blueprint preview scene.
Definition at line 1517 of file BlueprintEditor.h.
Referenced by GetPreviewScene().
RefreshEvent
FOnRefreshEvent FBlueprintEditor::RefreshEvent private
Notification used whenever the editor wants associated controls to refresh.
Definition at line 1582 of file BlueprintEditor.h.
Referenced by BroadcastRefresh(), and OnRefresh().
ReplaceReferencesWidget
TSharedPtr<class SReplaceNodeReferences> FBlueprintEditor::ReplaceReferencesWidget protected
Widget for replacing node references.
Definition at line 1448 of file BlueprintEditor.h.
Referenced by GetReplaceReferencesWidget().
SelectionState_ClassDefaults
FName FBlueprintEditor::SelectionState_ClassDefaults static
Definition at line 647 of file BlueprintEditor.h.
SelectionState_ClassSettings
FName FBlueprintEditor::SelectionState_ClassSettings static
Definition at line 646 of file BlueprintEditor.h.
SelectionState_Components
FName FBlueprintEditor::SelectionState_Components static
Definition at line 644 of file BlueprintEditor.h.
SelectionState_Graph
FName FBlueprintEditor::SelectionState_Graph static
Definition at line 645 of file BlueprintEditor.h.
SelectionState_MyBlueprint
FName FBlueprintEditor::SelectionState_MyBlueprint static
Definition at line 643 of file BlueprintEditor.h.
StandardLibraries
TArray<TObjectPtr<UBlueprint> > FBlueprintEditor::StandardLibraries protected
Macro/function libraries to keep loaded.
Definition at line 1424 of file BlueprintEditor.h.
SubobjectEditor
TSharedPtr<SSubobjectEditor> FBlueprintEditor::SubobjectEditor protected
Subobject Editor.
Definition at line 1427 of file BlueprintEditor.h.
Referenced by GetSubobjectEditor().
SubobjectEditorCustomizations
TMap<FName, TSharedPtr<ISCSEditorCustomization> > FBlueprintEditor::SubobjectEditorCustomizations private
Customizations for the Subobject editor.
Definition at line 1621 of file BlueprintEditor.h.
SubobjectViewport
TSharedPtr<SSCSEditorViewport> FBlueprintEditor::SubobjectViewport protected
Viewport widget.
Definition at line 1430 of file BlueprintEditor.h.
Referenced by GetSubobjectViewport().
Toolbar
TSharedPtr<class FBlueprintEditorToolbar> FBlueprintEditor::Toolbar protected
The toolbar builder class.
Definition at line 1476 of file BlueprintEditor.h.
Referenced by GetToolbarBuilder().
UE_SLATE_DEPRECATED_VECTOR_VIRTUAL_FUNCTION
const FVector2D UEdGraph* InGraph FBlueprintEditor::UE_SLATE_DEPRECATED_VECTOR_VIRTUAL_FUNCTION
Definition at line 660 of file BlueprintEditor.h.
UserDefinedEnumerators
TSet<TWeakObjectPtr<UUserDefinedEnum> > FBlueprintEditor::UserDefinedEnumerators protected
User-defined enumerators to keep loaded.
Definition at line 1418 of file BlueprintEditor.h.
UserDefinedStructures
TSet<TWeakObjectPtr<UUserDefinedStruct> > FBlueprintEditor::UserDefinedStructures protected
User-defined structures to keep loaded.
Definition at line 1421 of file BlueprintEditor.h.
ViewportSelectabilityBridge
TUniquePtr<FEditorViewportSelectabilityBridge> FBlueprintEditor::ViewportSelectabilityBridge private
Definition at line 1656 of file BlueprintEditor.h.
The documentation for this class was generated from the following file:
Editor/Kismet/Public/BlueprintEditor.h