Unreal Engine 5.6 C++ API: FGraphEditorCommandsImpl Class Reference
FGraphEditorCommandsImpl Class Reference
#include "GraphEditorActions.h"
Data Structures
struct FQuickJumpCommandInfo
Public Member Functions
FGraphEditorCommandsImpl ()
virtual ~FGraphEditorCommandsImpl ()
GRAPHEDITOR_API TSharedPtr< FUICommandInfo > GetFindReferences () const
virtual GRAPHEDITOR_API void RegisterCommands () override
Pure virtual to override; describe and instantiate the commands in here by using the UI COMMAND macro.
Public Member Functions inherited from FBindingContext
FBindingContext (const FBindingContext &)=default
FBindingContext (const FName InContextName, const FText &InContextDesc, const FName InContextParent, const FName InStyleSetName)
Constructor.
FBindingContext (FBindingContext &&)=default
void AddBundle (const FName Name, const FText &Desc)
Adds a new command bundle to this context that can be referenced by name from commands within the context.
const FText & GetBundleLabel (const FName Name)
Gets a localized label of a command bundle.
const FText & GetContextDesc () const
FName GetContextName () const
FName GetContextParent () const
FName GetStyleSetName () const
FUICommandInfoDecl NewCommand (const FName InCommandName, const FText &InCommandLabel, const FText &InCommandDesc)
Creates a new command declaration used to populate commands with data.
FBindingContext & operator= (const FBindingContext &)=default
FBindingContext & operator= (FBindingContext &&)=default
bool operator== (const FBindingContext &Other) const
Public Member Functions inherited from TSharedFromThis< FBindingContext >
TSharedRef< FBindingContext, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FBindingContext, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Data Fields
TSharedPtr< FUICommandInfo > AddBreakpoint
TSharedPtr< FUICommandInfo > AddExecutionPin
TSharedPtr< FUICommandInfo > AddOptionPin
TSharedPtr< FUICommandInfo > AddParentNode
TSharedPtr< FUICommandInfo > AlignNodesBottom
TSharedPtr< FUICommandInfo > AlignNodesCenter
TSharedPtr< FUICommandInfo > AlignNodesLeft
TSharedPtr< FUICommandInfo > AlignNodesMiddle
TSharedPtr< FUICommandInfo > AlignNodesRight
TSharedPtr< FUICommandInfo > AlignNodesTop
TSharedPtr< FUICommandInfo > AssignReferencedActor
TSharedPtr< FUICommandInfo > BreakNodeLinks
TSharedPtr< FUICommandInfo > BreakPinLinks
TSharedPtr< FUICommandInfo > BreakThisLink
TSharedPtr< FUICommandInfo > ChangePinType
TSharedPtr< FUICommandInfo > ClearAllQuickJumps
TSharedPtr< FUICommandInfo > CollapseNodes
TSharedPtr< FUICommandInfo > CollapseSelectionToFunction
TSharedPtr< FUICommandInfo > CollapseSelectionToMacro
TSharedPtr< FUICommandInfo > ConvertEventToFunction
TSharedPtr< FUICommandInfo > ConvertFunctionToEvent
TSharedPtr< FUICommandInfo > CreateComment
TSharedPtr< FUICommandInfo > CreateCustomEvent
TSharedPtr< FUICommandInfo > CreateMatchingFunction
TSharedPtr< FUICommandInfo > DeleteAndReconnectNodes
TSharedPtr< FUICommandInfo > DisableBreakpoint
TSharedPtr< FUICommandInfo > DisableNodes
TSharedPtr< FUICommandInfo > DistributeNodesHorizontally
TSharedPtr< FUICommandInfo > DistributeNodesVertically
TSharedPtr< FUICommandInfo > EnableBreakpoint
TSharedPtr< FUICommandInfo > EnableNodes
TSharedPtr< FUICommandInfo > EnableNodes_Always
TSharedPtr< FUICommandInfo > EnableNodes_DevelopmentOnly
TSharedPtr< FUICommandInfo > ExpandNodes
TSharedPtr< FUICommandInfo > FindAndReplaceReferences
TSharedPtr< FUICommandInfo > FindReferences
TSharedPtr< FUICommandInfo > FindReferencesByClassMemberGlobal
TSharedPtr< FUICommandInfo > FindReferencesByClassMemberLocal
TSharedPtr< FUICommandInfo > FindReferencesByNameGlobal
TSharedPtr< FUICommandInfo > FindReferencesByNameLocal
TSharedPtr< FUICommandInfo > GoToDefinition
TSharedPtr< FUICommandInfo > GoToDocumentation
TSharedPtr< FUICommandInfo > HideNoConnectionNoDefaultPins
TSharedPtr< FUICommandInfo > HideNoConnectionPins
TSharedPtr< FUICommandInfo > InsertExecutionPinAfter
TSharedPtr< FUICommandInfo > InsertExecutionPinBefore
TSharedPtr< FUICommandInfo > PromoteSelectionToFunction
TSharedPtr< FUICommandInfo > PromoteSelectionToMacro
TSharedPtr< FUICommandInfo > PromoteToLocalVariable
TSharedPtr< FUICommandInfo > PromoteToVariable
TArray< FQuickJumpCommandInfo > QuickJumpCommands
TSharedPtr< FUICommandInfo > RecombineStructPin
TSharedPtr< FUICommandInfo > ReconstructNodes
TSharedPtr< FUICommandInfo > RemoveBreakpoint
TSharedPtr< FUICommandInfo > RemoveExecutionPin
TSharedPtr< FUICommandInfo > RemoveOptionPin
TSharedPtr< FUICommandInfo > RemoveOtherStructVarPins
TSharedPtr< FUICommandInfo > RemoveThisStructVarPin
TSharedPtr< FUICommandInfo > ResetPinToDefaultValue
TSharedPtr< FUICommandInfo > RestoreAllStructVarPins
TSharedPtr< FUICommandInfo > SelectAllInputNodes
TSharedPtr< FUICommandInfo > SelectAllOutputNodes
TSharedPtr< FUICommandInfo > SelectReferenceInLevel
TSharedPtr< FUICommandInfo > ShowAllPins
TSharedPtr< FUICommandInfo > SplitStructPin
TSharedPtr< FUICommandInfo > StackNodesHorizontally
TSharedPtr< FUICommandInfo > StackNodesVertically
TSharedPtr< FUICommandInfo > StartWatchingPin
TSharedPtr< FUICommandInfo > StopWatchingPin
TSharedPtr< FUICommandInfo > StraightenConnections
TSharedPtr< FUICommandInfo > SummonCreateNodeMenu
TSharedPtr< FUICommandInfo > ToggleBreakpoint
TSharedPtr< FUICommandInfo > ZoomIn
TSharedPtr< FUICommandInfo > ZoomOut
Additional Inherited Members
Static Public Member Functions inherited from TCommands< FGraphEditorCommandsImpl >
static FGraphEditorCommandsImpl & Get ()
Get the singleton instance of this set of commands.
static const FBindingContext & GetContext ()
Get the BindingContext for this set of commands.
static bool IsRegistered ()
static void Register ()
Use this method to register commands.
static void Unregister ()
Use this method to clean up any resources used by the command set.
Static Public Attributes inherited from FBindingContext
static FOnBindingContextChanged CommandsChanged
A delegate that is called when commands are registered or unregistered with a binding context.
Protected Member Functions inherited from TCommands< FGraphEditorCommandsImpl >
TCommands (const FName InContextName, const FText &InContextDesc, const FName InContextParent, const FName InStyleSetName)
Construct a set of commands; call this from your custom commands class.
virtual ~TCommands ()
Protected Member Functions inherited from TSharedFromThis< FBindingContext >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions inherited from TCommands< FGraphEditorCommandsImpl >
static TWeakPtr< FGraphEditorCommandsImpl > & GetInstance ()
A static instance of the command set.
Static Protected Member Functions inherited from TSharedFromThis< FBindingContext >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
Definition at line 18 of file GraphEditorActions.h.
Constructor & Destructor Documentation
FGraphEditorCommandsImpl()
FGraphEditorCommandsImpl::FGraphEditorCommandsImpl () inline
Definition at line 22 of file GraphEditorActions.h.
References FGraphEditorCommandsImpl(), TCommands< FGraphEditorCommandsImpl >::TCommands(), NSLOCTEXT, and TEXT.
Referenced by FGraphEditorCommandsImpl().
~FGraphEditorCommandsImpl()
virtual FGraphEditorCommandsImpl::~FGraphEditorCommandsImpl () inline virtual
Definition at line 27 of file GraphEditorActions.h.
Member Function Documentation
GetFindReferences()
GRAPHEDITOR_API TSharedPtr< FUICommandInfo > FGraphEditorCommandsImpl::GetFindReferences () const inline
Definition at line 110 of file GraphEditorActions.h.
References FindReferences.
RegisterCommands()
virtual GRAPHEDITOR_API void FGraphEditorCommandsImpl::RegisterCommands () override virtual
Pure virtual to override; describe and instantiate the commands in here by using the UI COMMAND macro.
Implements TCommands< FGraphEditorCommandsImpl >.
Field Documentation
AddBreakpoint
TSharedPtr< FUICommandInfo > FGraphEditorCommandsImpl::AddBreakpoint
Definition at line 66 of file GraphEditorActions.h.
AddExecutionPin
TSharedPtr< FUICommandInfo > FGraphEditorCommandsImpl::AddExecutionPin
Definition at line 37 of file GraphEditorActions.h.
AddOptionPin
TSharedPtr< FUICommandInfo > FGraphEditorCommandsImpl::AddOptionPin
Definition at line 48 of file GraphEditorActions.h.
AddParentNode
TSharedPtr< FUICommandInfo > FGraphEditorCommandsImpl::AddParentNode
Definition at line 59 of file GraphEditorActions.h.
AlignNodesBottom
TSharedPtr< FUICommandInfo > FGraphEditorCommandsImpl::AlignNodesBottom
Definition at line 84 of file GraphEditorActions.h.
AlignNodesCenter
TSharedPtr< FUICommandInfo > FGraphEditorCommandsImpl::AlignNodesCenter
Definition at line 87 of file GraphEditorActions.h.
AlignNodesLeft
TSharedPtr< FUICommandInfo > FGraphEditorCommandsImpl::AlignNodesLeft
Definition at line 86 of file GraphEditorActions.h.
AlignNodesMiddle
TSharedPtr< FUICommandInfo > FGraphEditorCommandsImpl::AlignNodesMiddle
Definition at line 83 of file GraphEditorActions.h.
AlignNodesRight
TSharedPtr< FUICommandInfo > FGraphEditorCommandsImpl::AlignNodesRight
Definition at line 88 of file GraphEditorActions.h.
AlignNodesTop
TSharedPtr< FUICommandInfo > FGraphEditorCommandsImpl::AlignNodesTop
Definition at line 82 of file GraphEditorActions.h.
AssignReferencedActor
TSharedPtr< FUICommandInfo > FGraphEditorCommandsImpl::AssignReferencedActor
Definition at line 106 of file GraphEditorActions.h.
BreakNodeLinks
TSharedPtr< FUICommandInfo > FGraphEditorCommandsImpl::BreakNodeLinks
Definition at line 34 of file GraphEditorActions.h.
BreakPinLinks
TSharedPtr< FUICommandInfo > FGraphEditorCommandsImpl::BreakPinLinks
Definition at line 125 of file GraphEditorActions.h.
BreakThisLink
TSharedPtr< FUICommandInfo > FGraphEditorCommandsImpl::BreakThisLink
Definition at line 124 of file GraphEditorActions.h.
ChangePinType
TSharedPtr< FUICommandInfo > FGraphEditorCommandsImpl::ChangePinType
Definition at line 50 of file GraphEditorActions.h.
ClearAllQuickJumps
TSharedPtr< FUICommandInfo > FGraphEditorCommandsImpl::ClearAllQuickJumps
Definition at line 160 of file GraphEditorActions.h.
CollapseNodes
TSharedPtr< FUICommandInfo > FGraphEditorCommandsImpl::CollapseNodes
Definition at line 72 of file GraphEditorActions.h.
CollapseSelectionToFunction
TSharedPtr< FUICommandInfo > FGraphEditorCommandsImpl::CollapseSelectionToFunction
Definition at line 76 of file GraphEditorActions.h.
CollapseSelectionToMacro
TSharedPtr< FUICommandInfo > FGraphEditorCommandsImpl::CollapseSelectionToMacro
Definition at line 77 of file GraphEditorActions.h.
ConvertEventToFunction
TSharedPtr< FUICommandInfo > FGraphEditorCommandsImpl::ConvertEventToFunction
Definition at line 79 of file GraphEditorActions.h.
ConvertFunctionToEvent
TSharedPtr< FUICommandInfo > FGraphEditorCommandsImpl::ConvertFunctionToEvent
Definition at line 78 of file GraphEditorActions.h.
CreateComment
TSharedPtr< FUICommandInfo > FGraphEditorCommandsImpl::CreateComment
Definition at line 137 of file GraphEditorActions.h.
CreateCustomEvent
TSharedPtr< FUICommandInfo > FGraphEditorCommandsImpl::CreateCustomEvent
Definition at line 140 of file GraphEditorActions.h.
CreateMatchingFunction
TSharedPtr< FUICommandInfo > FGraphEditorCommandsImpl::CreateMatchingFunction
Definition at line 62 of file GraphEditorActions.h.
DeleteAndReconnectNodes
TSharedPtr< FUICommandInfo > FGraphEditorCommandsImpl::DeleteAndReconnectNodes
Definition at line 51 of file GraphEditorActions.h.
DisableBreakpoint
TSharedPtr< FUICommandInfo > FGraphEditorCommandsImpl::DisableBreakpoint
Definition at line 68 of file GraphEditorActions.h.
DisableNodes
TSharedPtr< FUICommandInfo > FGraphEditorCommandsImpl::DisableNodes
Definition at line 100 of file GraphEditorActions.h.
DistributeNodesHorizontally
TSharedPtr< FUICommandInfo > FGraphEditorCommandsImpl::DistributeNodesHorizontally
Definition at line 92 of file GraphEditorActions.h.
DistributeNodesVertically
TSharedPtr< FUICommandInfo > FGraphEditorCommandsImpl::DistributeNodesVertically
Definition at line 93 of file GraphEditorActions.h.
EnableBreakpoint
TSharedPtr< FUICommandInfo > FGraphEditorCommandsImpl::EnableBreakpoint
Definition at line 67 of file GraphEditorActions.h.
EnableNodes
TSharedPtr< FUICommandInfo > FGraphEditorCommandsImpl::EnableNodes
Definition at line 99 of file GraphEditorActions.h.
EnableNodes_Always
TSharedPtr< FUICommandInfo > FGraphEditorCommandsImpl::EnableNodes_Always
Definition at line 101 of file GraphEditorActions.h.
EnableNodes_DevelopmentOnly
TSharedPtr< FUICommandInfo > FGraphEditorCommandsImpl::EnableNodes_DevelopmentOnly
Definition at line 102 of file GraphEditorActions.h.
ExpandNodes
TSharedPtr< FUICommandInfo > FGraphEditorCommandsImpl::ExpandNodes
Definition at line 75 of file GraphEditorActions.h.
FindAndReplaceReferences
TSharedPtr< FUICommandInfo > FGraphEditorCommandsImpl::FindAndReplaceReferences
Definition at line 118 of file GraphEditorActions.h.
FindReferences
TSharedPtr< FUICommandInfo > FGraphEditorCommandsImpl::FindReferences
Definition at line 109 of file GraphEditorActions.h.
Referenced by GetFindReferences().
FindReferencesByClassMemberGlobal
TSharedPtr< FUICommandInfo > FGraphEditorCommandsImpl::FindReferencesByClassMemberGlobal
Definition at line 116 of file GraphEditorActions.h.
FindReferencesByClassMemberLocal
TSharedPtr< FUICommandInfo > FGraphEditorCommandsImpl::FindReferencesByClassMemberLocal
Definition at line 115 of file GraphEditorActions.h.
FindReferencesByNameGlobal
TSharedPtr< FUICommandInfo > FGraphEditorCommandsImpl::FindReferencesByNameGlobal
Definition at line 114 of file GraphEditorActions.h.
FindReferencesByNameLocal
TSharedPtr< FUICommandInfo > FGraphEditorCommandsImpl::FindReferencesByNameLocal
Definition at line 113 of file GraphEditorActions.h.
GoToDefinition
TSharedPtr< FUICommandInfo > FGraphEditorCommandsImpl::GoToDefinition
Definition at line 121 of file GraphEditorActions.h.
GoToDocumentation
TSharedPtr< FUICommandInfo > FGraphEditorCommandsImpl::GoToDocumentation
Definition at line 147 of file GraphEditorActions.h.
HideNoConnectionNoDefaultPins
TSharedPtr< FUICommandInfo > FGraphEditorCommandsImpl::HideNoConnectionNoDefaultPins
Definition at line 56 of file GraphEditorActions.h.
HideNoConnectionPins
TSharedPtr< FUICommandInfo > FGraphEditorCommandsImpl::HideNoConnectionPins
Definition at line 55 of file GraphEditorActions.h.
InsertExecutionPinAfter
TSharedPtr< FUICommandInfo > FGraphEditorCommandsImpl::InsertExecutionPinAfter
Definition at line 39 of file GraphEditorActions.h.
InsertExecutionPinBefore
TSharedPtr< FUICommandInfo > FGraphEditorCommandsImpl::InsertExecutionPinBefore
Definition at line 38 of file GraphEditorActions.h.
PromoteSelectionToFunction
TSharedPtr< FUICommandInfo > FGraphEditorCommandsImpl::PromoteSelectionToFunction
Definition at line 73 of file GraphEditorActions.h.
PromoteSelectionToMacro
TSharedPtr< FUICommandInfo > FGraphEditorCommandsImpl::PromoteSelectionToMacro
Definition at line 74 of file GraphEditorActions.h.
PromoteToLocalVariable
TSharedPtr< FUICommandInfo > FGraphEditorCommandsImpl::PromoteToLocalVariable
Definition at line 127 of file GraphEditorActions.h.
PromoteToVariable
TSharedPtr< FUICommandInfo > FGraphEditorCommandsImpl::PromoteToVariable
Definition at line 126 of file GraphEditorActions.h.
QuickJumpCommands
TArray< FQuickJumpCommandInfo > FGraphEditorCommandsImpl::QuickJumpCommands
Definition at line 159 of file GraphEditorActions.h.
RecombineStructPin
TSharedPtr< FUICommandInfo > FGraphEditorCommandsImpl::RecombineStructPin
Definition at line 129 of file GraphEditorActions.h.
ReconstructNodes
TSharedPtr< FUICommandInfo > FGraphEditorCommandsImpl::ReconstructNodes
Definition at line 33 of file GraphEditorActions.h.
RemoveBreakpoint
TSharedPtr< FUICommandInfo > FGraphEditorCommandsImpl::RemoveBreakpoint
Definition at line 65 of file GraphEditorActions.h.
RemoveExecutionPin
TSharedPtr< FUICommandInfo > FGraphEditorCommandsImpl::RemoveExecutionPin
Definition at line 40 of file GraphEditorActions.h.
RemoveOptionPin
TSharedPtr< FUICommandInfo > FGraphEditorCommandsImpl::RemoveOptionPin
Definition at line 49 of file GraphEditorActions.h.
RemoveOtherStructVarPins
TSharedPtr< FUICommandInfo > FGraphEditorCommandsImpl::RemoveOtherStructVarPins
Definition at line 44 of file GraphEditorActions.h.
RemoveThisStructVarPin
TSharedPtr< FUICommandInfo > FGraphEditorCommandsImpl::RemoveThisStructVarPin
Definition at line 43 of file GraphEditorActions.h.
ResetPinToDefaultValue
TSharedPtr< FUICommandInfo > FGraphEditorCommandsImpl::ResetPinToDefaultValue
Definition at line 132 of file GraphEditorActions.h.
RestoreAllStructVarPins
TSharedPtr< FUICommandInfo > FGraphEditorCommandsImpl::RestoreAllStructVarPins
Definition at line 45 of file GraphEditorActions.h.
SelectAllInputNodes
TSharedPtr< FUICommandInfo > FGraphEditorCommandsImpl::SelectAllInputNodes
Definition at line 133 of file GraphEditorActions.h.
SelectAllOutputNodes
TSharedPtr< FUICommandInfo > FGraphEditorCommandsImpl::SelectAllOutputNodes
Definition at line 134 of file GraphEditorActions.h.
SelectReferenceInLevel
TSharedPtr< FUICommandInfo > FGraphEditorCommandsImpl::SelectReferenceInLevel
Definition at line 105 of file GraphEditorActions.h.
ShowAllPins
TSharedPtr< FUICommandInfo > FGraphEditorCommandsImpl::ShowAllPins
Definition at line 54 of file GraphEditorActions.h.
SplitStructPin
TSharedPtr< FUICommandInfo > FGraphEditorCommandsImpl::SplitStructPin
Definition at line 128 of file GraphEditorActions.h.
StackNodesHorizontally
TSharedPtr< FUICommandInfo > FGraphEditorCommandsImpl::StackNodesHorizontally
Definition at line 95 of file GraphEditorActions.h.
StackNodesVertically
TSharedPtr< FUICommandInfo > FGraphEditorCommandsImpl::StackNodesVertically
Definition at line 96 of file GraphEditorActions.h.
StartWatchingPin
TSharedPtr< FUICommandInfo > FGraphEditorCommandsImpl::StartWatchingPin
Definition at line 130 of file GraphEditorActions.h.
StopWatchingPin
TSharedPtr< FUICommandInfo > FGraphEditorCommandsImpl::StopWatchingPin
Definition at line 131 of file GraphEditorActions.h.
StraightenConnections
TSharedPtr< FUICommandInfo > FGraphEditorCommandsImpl::StraightenConnections
Definition at line 90 of file GraphEditorActions.h.
SummonCreateNodeMenu
TSharedPtr< FUICommandInfo > FGraphEditorCommandsImpl::SummonCreateNodeMenu
Definition at line 150 of file GraphEditorActions.h.
ToggleBreakpoint
TSharedPtr< FUICommandInfo > FGraphEditorCommandsImpl::ToggleBreakpoint
Definition at line 69 of file GraphEditorActions.h.
ZoomIn
TSharedPtr< FUICommandInfo > FGraphEditorCommandsImpl::ZoomIn
Definition at line 143 of file GraphEditorActions.h.
ZoomOut
TSharedPtr< FUICommandInfo > FGraphEditorCommandsImpl::ZoomOut
Definition at line 144 of file GraphEditorActions.h.
The documentation for this class was generated from the following file:
Editor/GraphEditor/Public/GraphEditorActions.h