Unreal Engine 5.6 C++ API: FGameThreadHitchHeartBeatThreaded Class Reference
FGameThreadHitchHeartBeatThreaded Class Reference
#include "ThreadHeartBeat.h"
Public Types
enum EConstants { InvalidThreadId = (uint32)-1 }
Public Member Functions
void FrameStart (bool bSkipThisFrame=false)
Called at the start of a frame to register the time we are looking to detect a hitch.
double GetCurrentTime ()
double GetFrameStartTime ()
virtual bool Init ()
Initializes the runnable object.
bool IsStartedSuspended ()
Check if started suspended.
void PostFork ()
void Restart ()
void ResumeHeartBeat ()
Resume heartbeat hitch detection.
virtual uint32 Run ()
Runs the runnable object.
virtual void Stop ()
Stops the runnable object.
void SuspendHeartBeat ()
Suspend heartbeat hitch detection.
Public Member Functions inherited from FRunnable
virtual ~FRunnable ()
Virtual destructor.
virtual void Exit ()
Exits the runnable object.
virtual class FSingleThreadRunnable * GetSingleThreadInterface ()
Gets single thread interface pointer used for ticking this runnable when multi-threading is disabled.
Static Public Member Functions
static FGameThreadHitchHeartBeatThreaded & Get ()
Gets the heartbeat singleton.
static FGameThreadHitchHeartBeatThreaded * GetNoInit ()
Private Member Functions
FGameThreadHitchHeartBeatThreaded ()
virtual ~FGameThreadHitchHeartBeatThreaded ()
void InitSettings ()
Private Attributes
FThreadHeartBeatClock Clock
FCriticalSection HeartBeatCritical
Synch object for the heartbeat.
FThreadSafeCounter StopTaskCounter
Stops this thread.
FRunnableThread * Thread
Thread to run the worker FRunnable on.
Static Private Attributes
static FGameThreadHitchHeartBeatThreaded * Singleton
Detailed Description
Definition at line 326 of file ThreadHeartBeat.h.
Member Enumeration Documentation
EConstants
enum FGameThreadHitchHeartBeatThreaded::EConstants
Enumerator
InvalidThreadId
Invalid thread Id used by CheckHeartBeat.
Definition at line 365 of file ThreadHeartBeat.h.
Constructor & Destructor Documentation
FGameThreadHitchHeartBeatThreaded()
FGameThreadHitchHeartBeatThreaded::FGameThreadHitchHeartBeatThreaded () private
Referenced by Get(), and GetNoInit().
~FGameThreadHitchHeartBeatThreaded()
virtual FGameThreadHitchHeartBeatThreaded::~FGameThreadHitchHeartBeatThreaded () private virtual
Member Function Documentation
FrameStart()
void FGameThreadHitchHeartBeatThreaded::FrameStart (bool bSkipThisFrame = false)
Called at the start of a frame to register the time we are looking to detect a hitch.
Get()
FGameThreadHitchHeartBeatThreaded & FGameThreadHitchHeartBeatThreaded::Get () static
Gets the heartbeat singleton.
References FGameThreadHitchHeartBeatThreaded().
Referenced by FDisableHitchDetectorScope::FDisableHitchDetectorScope(), and FDisableHitchDetectorScope::~FDisableHitchDetectorScope().
GetCurrentTime()
double FGameThreadHitchHeartBeatThreaded::GetCurrentTime ()
GetFrameStartTime()
double FGameThreadHitchHeartBeatThreaded::GetFrameStartTime ()
GetNoInit()
FGameThreadHitchHeartBeatThreaded * FGameThreadHitchHeartBeatThreaded::GetNoInit () static
References FGameThreadHitchHeartBeatThreaded().
Init()
virtual bool FGameThreadHitchHeartBeatThreaded::Init () virtual
Initializes the runnable object.
This method is called in the context of the thread object that aggregates this, not the thread that passes this runnable to a new thread.
Returns
True if initialization was successful, false otherwise
See also
Run, Stop, Exit
Reimplemented from FRunnable.
InitSettings()
void FGameThreadHitchHeartBeatThreaded::InitSettings () private
IsStartedSuspended()
bool FGameThreadHitchHeartBeatThreaded::IsStartedSuspended ()
Check if started suspended.
PostFork()
void FGameThreadHitchHeartBeatThreaded::PostFork () inline
Definition at line 400 of file ThreadHeartBeat.h.
Restart()
void FGameThreadHitchHeartBeatThreaded::Restart () inline
Definition at line 399 of file ThreadHeartBeat.h.
ResumeHeartBeat()
void FGameThreadHitchHeartBeatThreaded::ResumeHeartBeat ()
Resume heartbeat hitch detection.
Call only after first calling SuspendHeartBeat.
Referenced by FDisableHitchDetectorScope::~FDisableHitchDetectorScope().
Run()
virtual uint32 FGameThreadHitchHeartBeatThreaded::Run () virtual
Runs the runnable object.
This is where all per object thread work is done. This is only called if the initialization was successful.
Returns
The exit code of the runnable object
See also
Init, Stop, Exit
Implements FRunnable.
Stop()
virtual void FGameThreadHitchHeartBeatThreaded::Stop () virtual
Stops the runnable object.
This is called if a thread is requested to terminate early.
See also
Init, Run, Exit
Reimplemented from FRunnable.
SuspendHeartBeat()
void FGameThreadHitchHeartBeatThreaded::SuspendHeartBeat ()
Suspend heartbeat hitch detection.
Must call ResumeHeartBeat later to resume.
Referenced by FDisableHitchDetectorScope::FDisableHitchDetectorScope().
Field Documentation
Clock
FThreadHeartBeatClock FGameThreadHitchHeartBeatThreaded::Clock private
Definition at line 356 of file ThreadHeartBeat.h.
HeartBeatCritical
FCriticalSection FGameThreadHitchHeartBeatThreaded::HeartBeatCritical private
Synch object for the heartbeat.
Definition at line 335 of file ThreadHeartBeat.h.
Singleton
FGameThreadHitchHeartBeatThreaded* FGameThreadHitchHeartBeatThreaded::Singleton static private
Definition at line 328 of file ThreadHeartBeat.h.
StopTaskCounter
FThreadSafeCounter FGameThreadHitchHeartBeatThreaded::StopTaskCounter private
Stops this thread.
Definition at line 333 of file ThreadHeartBeat.h.
Thread
FRunnableThread* FGameThreadHitchHeartBeatThreaded::Thread private
Thread to run the worker FRunnable on.
Definition at line 331 of file ThreadHeartBeat.h.
The documentation for this class was generated from the following file:
Runtime/Core/Public/HAL/ThreadHeartBeat.h