Unreal Engine 5.6 C++ API: TAsyncTreeDifferences< InNodeType > Class Template Reference
TAsyncTreeDifferences< InNodeType > Class Template Reference
#include "AsyncTreeDifferences.h"
Public Types
using DiffNodeType = TDiffNode<ValueType>
using ValueType = InNodeType
Public Member Functions
TAsyncTreeDifferences (const TAttribute< TArray< ValueType > > &InRootValuesA, const TAttribute< TArray< ValueType > > &InRootValuesB)
DECLARE_MULTICAST_DELEGATE_OneParam (FOnQueueFlushed, const TAsyncTreeDifferences &)
void FlushQueue ()
void ForEach (ETreeTraverseOrder TraversalOrder, const TFunction< ETreeTraverseControl(const TUniquePtr< DiffNodeType > &)> &Method) const
template<typename SpecificationType, typename... TArgs>
void SetDiffSpecification (TArgs... Args)
void Tick (float MaxAllottedTimeMs=1.f)
Data Fields
TUniquePtr< DiffNodeType > Head
FOnQueueFlushed OnQueueFlushed
Private Member Functions
bool AreMatching (const ValueType &ValueA, const ValueType &ValueB)
TArray< TArray< int32 > > CalculateLCSTableForMatchingValues (const TArray< ValueType > &ValuesA, const TArray< ValueType > &ValuesB)
void ProcessTopOfQueue ()
void QueueParallelNodeLists (const TArray< ValueType > &ValuesA, const TArray< ValueType > &ValuesB, DiffNodeType *ParentNode)
Static Private Member Functions
static TArray< TArray< int32 > > CalculateLCSTableForDiffNodes (const TArray< DiffNodeType > &FoundNodes, const TArray< TUniquePtr< DiffNodeType > > &ExpectedNodes)
static bool PostOrderRecursive (const TUniquePtr< DiffNodeType > &Node, const TFunction< ETreeTraverseControl(const TUniquePtr< DiffNodeType > &)> &Method)
static bool PreOrderRecursive (const TUniquePtr< DiffNodeType > &Node, const TFunction< ETreeTraverseControl(const TUniquePtr< DiffNodeType > &)> &Method)
static bool ReversePostOrderRecursive (const TUniquePtr< DiffNodeType > &Node, const TFunction< ETreeTraverseControl(const TUniquePtr< DiffNodeType > &)> &Method)
static bool ReversePreOrderRecursive (const TUniquePtr< DiffNodeType > &Node, const TFunction< ETreeTraverseControl(const TUniquePtr< DiffNodeType > &)> &Method)
Private Attributes
TAttribute< TArray< ValueType > > RootValuesA
TAttribute< TArray< ValueType > > RootValuesB
TUniquePtr< TTreeDiffSpecification< ValueType > > Specification
TArray< DiffNodeType * > UpdateQueue
Detailed Description
template<typename InNodeType>
class TAsyncTreeDifferences< InNodeType >
Definition at line 180 of file AsyncTreeDifferences.h.
Member Typedef Documentation
DiffNodeType
template<typename InNodeType> using TAsyncTreeDifferences< InNodeType >::DiffNodeType = TDiffNode<ValueType>
Definition at line 184 of file AsyncTreeDifferences.h.
ValueType
template<typename InNodeType> using TAsyncTreeDifferences< InNodeType >::ValueType = InNodeType
Definition at line 183 of file AsyncTreeDifferences.h.
Constructor & Destructor Documentation
TAsyncTreeDifferences()
template<typename InNodeType> TAsyncTreeDifferences< InNodeType >::TAsyncTreeDifferences (const TAttribute< TArray< ValueType > > & InRootValuesA, const TAttribute< TArray< ValueType > > & InRootValuesB)
Definition at line 281 of file AsyncTreeDifferences.h.
References Head, MakeUnique(), QueueParallelNodeLists(), RootValuesA, RootValuesB, and Specification.
Referenced by DECLARE_MULTICAST_DELEGATE_OneParam().
Member Function Documentation
AreMatching()
template<typename InNodeType> bool TAsyncTreeDifferences< InNodeType >::AreMatching (const ValueType & ValueA, const ValueType & ValueB) private
Definition at line 655 of file AsyncTreeDifferences.h.
References Specification.
Referenced by CalculateLCSTableForMatchingValues(), and QueueParallelNodeLists().
CalculateLCSTableForDiffNodes()
template<typename InNodeType> TArray< TArray< int32 > > TAsyncTreeDifferences< InNodeType >::CalculateLCSTableForDiffNodes (const TArray< DiffNodeType > & FoundNodes, const TArray< TUniquePtr< DiffNodeType > > & ExpectedNodes) static private
Definition at line 626 of file AsyncTreeDifferences.h.
References FMath::Max, TArray< InElementType, InAllocatorType >::Num(), and TArray< InElementType, InAllocatorType >::SetNum().
Referenced by QueueParallelNodeLists().
CalculateLCSTableForMatchingValues()
template<typename InNodeType> TArray< TArray< int32 > > TAsyncTreeDifferences< InNodeType >::CalculateLCSTableForMatchingValues (const TArray< ValueType > & ValuesA, const TArray< ValueType > & ValuesB) private
Definition at line 597 of file AsyncTreeDifferences.h.
References AreMatching(), FMath::Max, TArray< InElementType, InAllocatorType >::Num(), and TArray< InElementType, InAllocatorType >::SetNum().
Referenced by QueueParallelNodeLists().
DECLARE_MULTICAST_DELEGATE_OneParam()
template<typename InNodeType> TAsyncTreeDifferences< InNodeType >::DECLARE_MULTICAST_DELEGATE_OneParam (FOnQueueFlushed , const TAsyncTreeDifferences< InNodeType > &)
References TAsyncTreeDifferences().
FlushQueue()
template<typename InNodeType> void TAsyncTreeDifferences< InNodeType >::FlushQueue ()
Definition at line 311 of file AsyncTreeDifferences.h.
References OnQueueFlushed, ProcessTopOfQueue(), and UpdateQueue.
ForEach()
template<typename InNodeType> void TAsyncTreeDifferences< InNodeType >::ForEach (ETreeTraverseOrder TraversalOrder, const TFunction< ETreeTraverseControl(const TUniquePtr< DiffNodeType > &)> & Method) const
Definition at line 321 of file AsyncTreeDifferences.h.
References check, Head, PostOrder, PostOrderRecursive(), PreOrder, PreOrderRecursive(), ReversePostOrder, ReversePostOrderRecursive(), ReversePreOrder, and ReversePreOrderRecursive().
PostOrderRecursive()
template<typename InNodeType> bool TAsyncTreeDifferences< InNodeType >::PostOrderRecursive (const TUniquePtr< DiffNodeType > & Node, const TFunction< ETreeTraverseControl(const TUniquePtr< DiffNodeType > &)> & Method) static private
Definition at line 372 of file AsyncTreeDifferences.h.
References Break, Child, Invalid, and PostOrderRecursive().
Referenced by ForEach(), and PostOrderRecursive().
PreOrderRecursive()
template<typename InNodeType> bool TAsyncTreeDifferences< InNodeType >::PreOrderRecursive (const TUniquePtr< DiffNodeType > & Node, const TFunction< ETreeTraverseControl(const TUniquePtr< DiffNodeType > &)> & Method) static private
Definition at line 349 of file AsyncTreeDifferences.h.
References Break, Child, Invalid, PreOrderRecursive(), and SkipChildren.
Referenced by ForEach(), and PreOrderRecursive().
ProcessTopOfQueue()
template<typename InNodeType> void TAsyncTreeDifferences< InNodeType >::ProcessTopOfQueue () private
Definition at line 441 of file AsyncTreeDifferences.h.
References TArray< InElementType, InAllocatorType >::IsEmpty(), TDiffNode< ValueType >::NullValue, QueueParallelNodeLists(), Specification, UpdateQueue, TDiffNode< InNodeType >::ValueA, and TDiffNode< InNodeType >::ValueB.
Referenced by FlushQueue(), and Tick().
QueueParallelNodeLists()
template<typename InNodeType> void TAsyncTreeDifferences< InNodeType >::QueueParallelNodeLists (const TArray< ValueType > & ValuesA, const TArray< ValueType > & ValuesB, DiffNodeType * ParentNode) private
Definition at line 465 of file AsyncTreeDifferences.h.
References TArray< InElementType, InAllocatorType >::Add(), AreMatching(), CalculateLCSTableForDiffNodes(), CalculateLCSTableForMatchingValues(), Child, TDiffNode< InNodeType >::Children, INDEX_NONE, MakeUnique(), MoveTemp(), TDiffNode< ValueType >::NullValue, TArray< InElementType, InAllocatorType >::Num(), Algo::Reverse(), Specification, and UpdateQueue.
Referenced by TAsyncTreeDifferences(), ProcessTopOfQueue(), and Tick().
ReversePostOrderRecursive()
template<typename InNodeType> bool TAsyncTreeDifferences< InNodeType >::ReversePostOrderRecursive (const TUniquePtr< DiffNodeType > & Node, const TFunction< ETreeTraverseControl(const TUniquePtr< DiffNodeType > &)> & Method) static private
Definition at line 418 of file AsyncTreeDifferences.h.
References Break, Child, Invalid, and ReversePostOrderRecursive().
Referenced by ForEach(), and ReversePostOrderRecursive().
ReversePreOrderRecursive()
template<typename InNodeType> bool TAsyncTreeDifferences< InNodeType >::ReversePreOrderRecursive (const TUniquePtr< DiffNodeType > & Node, const TFunction< ETreeTraverseControl(const TUniquePtr< DiffNodeType > &)> & Method) static private
Definition at line 394 of file AsyncTreeDifferences.h.
References Break, Child, Invalid, ReversePreOrderRecursive(), and SkipChildren.
Referenced by ForEach(), and ReversePreOrderRecursive().
SetDiffSpecification()
template<typename InNodeType> template<typename SpecificationType, typename... TArgs> void TAsyncTreeDifferences< InNodeType >::SetDiffSpecification (TArgs... Args)
Definition at line 343 of file AsyncTreeDifferences.h.
References MakeUnique(), and Specification.
Tick()
template<typename InNodeType> void TAsyncTreeDifferences< InNodeType >::Tick (float MaxAllottedTimeMs = 1.f)
Definition at line 291 of file AsyncTreeDifferences.h.
References Head, OnQueueFlushed, ProcessTopOfQueue(), QueueParallelNodeLists(), RootValuesA, RootValuesB, FAndroidTime::Seconds(), and UpdateQueue.
Field Documentation
Head
template<typename InNodeType> TUniquePtr<DiffNodeType> TAsyncTreeDifferences< InNodeType >::Head
Definition at line 201 of file AsyncTreeDifferences.h.
Referenced by TAsyncTreeDifferences(), ForEach(), and Tick().
OnQueueFlushed
template<typename InNodeType> FOnQueueFlushed TAsyncTreeDifferences< InNodeType >::OnQueueFlushed
Definition at line 205 of file AsyncTreeDifferences.h.
Referenced by FlushQueue(), and Tick().
RootValuesA
template<typename InNodeType> TAttribute<TArray<ValueType> > TAsyncTreeDifferences< InNodeType >::RootValuesA private
Definition at line 224 of file AsyncTreeDifferences.h.
Referenced by TAsyncTreeDifferences(), and Tick().
RootValuesB
template<typename InNodeType> TAttribute<TArray<ValueType> > TAsyncTreeDifferences< InNodeType >::RootValuesB private
Definition at line 225 of file AsyncTreeDifferences.h.
Referenced by TAsyncTreeDifferences(), and Tick().
Specification
template<typename InNodeType> TUniquePtr<TTreeDiffSpecification<ValueType> > TAsyncTreeDifferences< InNodeType >::Specification private
Definition at line 226 of file AsyncTreeDifferences.h.
Referenced by TAsyncTreeDifferences(), AreMatching(), ProcessTopOfQueue(), QueueParallelNodeLists(), and SetDiffSpecification().
UpdateQueue
template<typename InNodeType> TArray<DiffNodeType*> TAsyncTreeDifferences< InNodeType >::UpdateQueue private
Definition at line 223 of file AsyncTreeDifferences.h.
Referenced by FlushQueue(), ProcessTopOfQueue(), QueueParallelNodeLists(), and Tick().
The documentation for this class was generated from the following file:
Editor/UnrealEd/Public/AsyncTreeDifferences.h