Unreal Engine 5.6 C++ API: IInterface_AssetUserData Class Reference
IInterface_AssetUserData Class Reference
Interface for assets/objects that can own UserData.
#include "Interface_AssetUserData.h"
Private Member Functions
GENERATED_IINTERFACE_BODY () virtual void AddAssetUserData(UAssetUserData *InUserData)
template<typename T>
T * GetAssetUserData ()
virtual const TArray< UAssetUserData * > * GetAssetUserDataArray () const
template<typename T>
T * GetAssetUserDataChecked ()
virtual void RemoveUserDataOfClass (TSubclassOf< UAssetUserData > InUserDataClass)
UFUNCTION () virtual bool AddAssetUserDataOfClass(TSubclassOf< UAssetUserData > InUserDataClass)
Creates and adds an instance of the provided AssetUserData class to the target asset.
UFUNCTION () virtual bool HasAssetUserDataOfClass(TSubclassOf< UAssetUserData > InUserDataClass)
Checks whether or not an instance of the provided AssetUserData class is contained.
UFUNCTION ()) virtual UAssetUserData *GetAssetUserDataOfClass(TSubclassOf< UAssetUserData > InUserDataClass)
Returns an instance of the provided AssetUserData class if it's contained in the target asset.
Detailed Description
Interface for assets/objects that can own UserData.
Definition at line 19 of file Interface_AssetUserData.h.
Member Function Documentation
GENERATED_IINTERFACE_BODY()
IInterface_AssetUserData::GENERATED_IINTERFACE_BODY () inline private
Definition at line 21 of file Interface_AssetUserData.h.
GetAssetUserData()
template<typename T> T * IInterface_AssetUserData::GetAssetUserData () inline private
Definition at line 72 of file Interface_AssetUserData.h.
References Cast().
GetAssetUserDataArray()
virtual const TArray< UAssetUserData * > * IInterface_AssetUserData::GetAssetUserDataArray () const inline private virtual
Reimplemented in AWorldSettings, UActorComponent, and UGroomAsset.
Definition at line 66 of file Interface_AssetUserData.h.
GetAssetUserDataChecked()
template<typename T> T * IInterface_AssetUserData::GetAssetUserDataChecked () inline private
Definition at line 78 of file Interface_AssetUserData.h.
References CastChecked().
RemoveUserDataOfClass()
virtual void IInterface_AssetUserData::RemoveUserDataOfClass (TSubclassOf< UAssetUserData > InUserDataClass) inline private virtual
Reimplemented in AWorldSettings, UActorComponent, and UGroomAsset.
Definition at line 83 of file Interface_AssetUserData.h.
UFUNCTION() [1/3]
IInterface_AssetUserData::UFUNCTION () inline private
Creates and adds an instance of the provided AssetUserData class to the target asset.
Parameters
InUserDataClass UAssetUserData sub class to create
Returns
Whether or not an instance of InUserDataClass was succesfully added
Definition at line 58 of file Interface_AssetUserData.h.
References Category, check, TSubclassOf< T >::Get(), and NewObject().
UFUNCTION() [2/3]
IInterface_AssetUserData::UFUNCTION () inline private
Checks whether or not an instance of the provided AssetUserData class is contained.
Parameters
InUserDataClass UAssetUserData sub class to check for
Returns
Whether or not an instance of InUserDataClass was found
Definition at line 45 of file Interface_AssetUserData.h.
References Category.
UFUNCTION() [3/3]
IInterface_AssetUserData::UFUNCTION () inline private
Returns an instance of the provided AssetUserData class if it's contained in the target asset.
Parameters
InUserDataClass UAssetUserData sub class to get
Returns
The instance of the UAssetUserData class contained, or null if it doesn't exist
Definition at line 32 of file Interface_AssetUserData.h.
References Category, and meta.
The documentation for this class was generated from the following file:
Runtime/Engine/Classes/Interfaces/Interface_AssetUserData.h