Unreal Engine 5.6 C++ API: FCookStatsManager Class Reference
FCookStatsManager Class Reference
Centralizes the system to gather stats from a cook that need to be collected at the core/engine level.
#include "CookStats.h"
Data Structures
struct FAutoRegisterCallback
Helper struct to auto-register your STATIC FUNCTION with CookStatsCallbacks.
struct TKeyValuePair
Copy of TKeyValuePair<> from Core, but with a default initializer for each member.
Public Types
typedef TFunctionRef< void(const FString &StatName, const TArray< StringKeyValue > &StatAttributes)> AddStatFuncRef
When you register a callback for reporting your stats, you will be given a TFunctionRef to call to add stats.
typedef TKeyValuePair< FString, FString > StringKeyValue
Every stat is essentially a name followed by an array of key/value "attributes" associated with the stat.
Public Member Functions
DECLARE_MULTICAST_DELEGATE_OneParam (FGatherCookStatsDelegate, AddStatFuncRef)
To register a callback for reporting stats, create an instance of this delegate type and add it to the delegate variable below.
Static Public Member Functions
template<typename... ArgTypes>
static TArray< FCookStatsManager::StringKeyValue > CreateKeyValueArray (ArgTypes &&...Args)
Helper to create an array of KeyValues using a single expression.
static void LogCookStats (AddStatFuncRef AddStat)
Called after the cook is finished to gather the stats.
template<typename KeyType, typename ValueType>
static TKeyValuePair< typename TDecay< KeyType >::Type, typename TDecay< ValueType >::Type > MakePair (KeyType &&InKey, ValueType &&InValue)
Helper to construct a TKeyValuePair.
Static Public Attributes
static FGatherCookStatsDelegate CookStatsCallbacks
Use this to register a callback to gather cook stats for a translation unit.
Static Private Member Functions
template<typename KeyType>
static void ImplCreateKeyValueArray (TArray< FCookStatsManager::StringKeyValue > &Attrs, KeyType &&Key)
template<typename KeyType, typename ValueType>
static void ImplCreateKeyValueArray (TArray< FCookStatsManager::StringKeyValue > &Attrs, KeyType &&Key, ValueType &&Value)
template<typename KeyType, typename ValueType, typename... ArgTypes>
static void ImplCreateKeyValueArray (TArray< FCookStatsManager::StringKeyValue > &Attrs, KeyType &&Key, ValueType &&Value, ArgTypes &&...Args)
Detailed Description
Centralizes the system to gather stats from a cook that need to be collected at the core/engine level.
Essentially, add a delegate to the CookStatsCallbacks member. When a cook a complete that is configured to use stats (ENABLE_COOK_STATS), it will broadcast this delegate, which, when called, gives you a TFunction to call to report each of your stats.
For simplicity, FAutoRegisterCallback is provided to auto-register your callback on startup. Usage is like:
static void ReportCookStats(AddStatFuncRef AddStat) { AddStat("MySubsystem.Event1", CreateKeyValueArray("Attr1", "Value1", "Attr2", "Value2" ...); AddStat("MySubsystem.Event2", CreateKeyValueArray("Attr1", "Value1", "Attr2", "Value2" ...); }
FAutoRegisterCallback GMySubsystemCookRegistration(&ReportCookStats);
When a cook is complete, your callback will be called, and the stats will be either logged, sent to an analytics provider, logged to an external file, etc. You don't care how they are added, you just call AddStat for each stat you want to add.
Definition at line 56 of file CookStats.h.
Member Typedef Documentation
AddStatFuncRef
typedef TFunctionRef<void(const FString& StatName, const TArray<StringKeyValue>& StatAttributes)> FCookStatsManager::AddStatFuncRef
When you register a callback for reporting your stats, you will be given a TFunctionRef to call to add stats.
This is the signature of the function you will call.
Definition at line 105 of file CookStats.h.
StringKeyValue
typedef TKeyValuePair<FString, FString> FCookStatsManager::StringKeyValue
Every stat is essentially a name followed by an array of key/value "attributes" associated with the stat.
Definition at line 103 of file CookStats.h.
Member Function Documentation
CreateKeyValueArray()
template<typename... ArgTypes> TArray< FCookStatsManager::StringKeyValue > FCookStatsManager::CreateKeyValueArray (ArgTypes &&... Args) inline static
Helper to create an array of KeyValues using a single expression.
If there is an odd number of arguments, the last value is considered to be an empty string.
Definition at line 132 of file CookStats.h.
References TArray< InElementType, InAllocatorType >::Empty(), Forward(), and ImplCreateKeyValueArray().
Referenced by FCookStats::CallStats::LogStats().
DECLARE_MULTICAST_DELEGATE_OneParam()
FCookStatsManager::DECLARE_MULTICAST_DELEGATE_OneParam (FGatherCookStatsDelegate , AddStatFuncRef)
To register a callback for reporting stats, create an instance of this delegate type and add it to the delegate variable below.
ImplCreateKeyValueArray() [1/3]
template<typename KeyType> void FCookStatsManager::ImplCreateKeyValueArray (TArray< FCookStatsManager::StringKeyValue > & Attrs, KeyType && Key) inline static private
Definition at line 142 of file CookStats.h.
References TArray< InElementType, InAllocatorType >::Emplace(), Forward(), Key, LexToString(), and TEXT.
Referenced by CreateKeyValueArray(), and ImplCreateKeyValueArray().
ImplCreateKeyValueArray() [2/3]
template<typename KeyType, typename ValueType> void FCookStatsManager::ImplCreateKeyValueArray (TArray< FCookStatsManager::StringKeyValue > & Attrs, KeyType && Key, ValueType && Value) inline static private
Definition at line 148 of file CookStats.h.
References TArray< InElementType, InAllocatorType >::Emplace(), Forward(), Key, LexToString(), and Value.
ImplCreateKeyValueArray() [3/3]
template<typename KeyType, typename ValueType, typename... ArgTypes> void FCookStatsManager::ImplCreateKeyValueArray (TArray< FCookStatsManager::StringKeyValue > & Attrs, KeyType && Key, ValueType && Value, ArgTypes &&... Args) inline static private
Definition at line 154 of file CookStats.h.
References TArray< InElementType, InAllocatorType >::Emplace(), Forward(), ImplCreateKeyValueArray(), Key, LexToString(), and Value.
LogCookStats()
void FCookStatsManager::LogCookStats (AddStatFuncRef AddStat) static
Called after the cook is finished to gather the stats.
MakePair()
template<typename KeyType, typename ValueType> TKeyValuePair< typename TDecay< KeyType >::Type, typename TDecay< ValueType >::Type > FCookStatsManager::MakePair (KeyType && InKey, ValueType && InValue) inline static
Helper to construct a TKeyValuePair.
Definition at line 96 of file CookStats.h.
References Forward().
Field Documentation
CookStatsCallbacks
FGatherCookStatsDelegate FCookStatsManager::CookStatsCallbacks static
Use this to register a callback to gather cook stats for a translation unit.
When a cook is finished, this delegate will be fired.
Definition at line 111 of file CookStats.h.
Referenced by FCookStatsManager::FAutoRegisterCallback::FAutoRegisterCallback().
The documentation for this class was generated from the following file:
Runtime/Core/Public/ProfilingDebugging/CookStats.h