Unreal Engine 5.6 C++ API: IDisplayClusterWarp Class Reference
IDisplayClusterWarp Class Reference abstract
#include "IDisplayClusterWarp.h"
Public Member Functions
virtual ~IDisplayClusterWarp ()=default
virtual TSharedPtr< IDisplayClusterWarpBlend, ESPMode::ThreadSafe > Create (const FDisplayClusterWarpInitializer_MPCDIFile &InConstructParameters) const =0
Create new WarpBlend interface from MPCDI File.
virtual TSharedPtr< IDisplayClusterWarpBlend, ESPMode::ThreadSafe > Create (const FDisplayClusterWarpInitializer_MPCDIFile_Profile2DScreen &InConstructParameters) const =0
Create WarpBlend interface from MPCDI file and DisplayClusterScreen component.
virtual TSharedPtr< IDisplayClusterWarpBlend, ESPMode::ThreadSafe > Create (const FDisplayClusterWarpInitializer_PFMFile &InConstructParameters) const =0
Create new WarpBlend interface from PFM File.
virtual TSharedPtr< IDisplayClusterWarpBlend, ESPMode::ThreadSafe > Create (const FDisplayClusterWarpInitializer_ProceduralMesh &InConstructParameters) const =0
Create new WarpBlend interface from procedural mesh.
virtual TSharedPtr< IDisplayClusterWarpBlend, ESPMode::ThreadSafe > Create (const FDisplayClusterWarpInitializer_StaticMesh &InConstructParameters) const =0
Create new WarpBlend interface from static mesh.
virtual bool ReadMPCDFileStructure (const FString &InMPCDIFileName, TMap< FString, TMap< FString, FDisplayClusterWarpMPCDIAttributes > > &OutMPCDIFileStructure) const =0
Read MPCDI file structure (This function uses MPCDICachedLoader's internal implementation, which greatly reduces the load time of huge MPCDI files.)
Public Member Functions inherited from IModuleInterface
virtual ~IModuleInterface ()
Note: Even though this is an interface class we need a virtual destructor here because modules are deleted via a pointer to this interface.
virtual bool IsGameModule () const
Returns true if this module hosts gameplay code.
virtual void PostLoadCallback ()
Called after the module has been reloaded.
virtual void PreUnloadCallback ()
Called before the module has been unloaded.
virtual void ShutdownModule ()
Called before the module is unloaded, right before the module object is destroyed.
virtual void StartupModule ()
Called right after the module DLL has been loaded and the module object has been created Load dependent modules here, and they will be guaranteed to be available during ShutdownModule.
virtual bool SupportsAutomaticShutdown ()
Override this to set whether your module would like cleanup on application shutdown.
virtual bool SupportsDynamicReloading ()
Override this to set whether your module is allowed to be unloaded on the fly.
Static Public Member Functions
static IDisplayClusterWarp & Get ()
Singleton-like access to this module's interface.
static bool IsAvailable ()
Checks to see if this module is loaded and ready.
Static Public Attributes
static constexpr const TCHAR * ModuleName = TEXT("DisplayClusterWarp")
Detailed Description
Definition at line 11 of file IDisplayClusterWarp.h.
Constructor & Destructor Documentation
~IDisplayClusterWarp()
virtual IDisplayClusterWarp::~IDisplayClusterWarp () virtual default
Member Function Documentation
Create() [1/5]
virtual TSharedPtr< IDisplayClusterWarpBlend, ESPMode::ThreadSafe > IDisplayClusterWarp::Create (const FDisplayClusterWarpInitializer_MPCDIFile & InConstructParameters) const pure virtual
Create new WarpBlend interface from MPCDI File.
Create() [2/5]
virtual TSharedPtr< IDisplayClusterWarpBlend, ESPMode::ThreadSafe > IDisplayClusterWarp::Create (const FDisplayClusterWarpInitializer_MPCDIFile_Profile2DScreen & InConstructParameters) const pure virtual
Create WarpBlend interface from MPCDI file and DisplayClusterScreen component.
Create() [3/5]
virtual TSharedPtr< IDisplayClusterWarpBlend, ESPMode::ThreadSafe > IDisplayClusterWarp::Create (const FDisplayClusterWarpInitializer_PFMFile & InConstructParameters) const pure virtual
Create new WarpBlend interface from PFM File.
Create() [4/5]
virtual TSharedPtr< IDisplayClusterWarpBlend, ESPMode::ThreadSafe > IDisplayClusterWarp::Create (const FDisplayClusterWarpInitializer_ProceduralMesh & InConstructParameters) const pure virtual
Create new WarpBlend interface from procedural mesh.
Create() [5/5]
virtual TSharedPtr< IDisplayClusterWarpBlend, ESPMode::ThreadSafe > IDisplayClusterWarp::Create (const FDisplayClusterWarpInitializer_StaticMesh & InConstructParameters) const pure virtual
Create new WarpBlend interface from static mesh.
Get()
IDisplayClusterWarp & IDisplayClusterWarp::Get () inline static
Singleton-like access to this module's interface.
This is just for convenience! Beware of calling this during the shutdown phase, though. Your module might have been unloaded already.
Returns
Returns singleton instance, loading the module on demand if needed
Definition at line 26 of file IDisplayClusterWarp.h.
References FModuleManager::LoadModuleChecked(), and ModuleName.
IsAvailable()
bool IDisplayClusterWarp::IsAvailable () inline static
Checks to see if this module is loaded and ready.
It is only valid to call Get() if IsAvailable() returns true.
Returns
True if the module is loaded and ready to use
Definition at line 36 of file IDisplayClusterWarp.h.
References FModuleManager::Get(), FModuleManager::IsModuleLoaded(), and ModuleName.
ReadMPCDFileStructure()
virtual bool IDisplayClusterWarp::ReadMPCDFileStructure (const FString & InMPCDIFileName, TMap< FString, TMap< FString, FDisplayClusterWarpMPCDIAttributes > > & OutMPCDIFileStructure) const pure virtual
Read MPCDI file structure (This function uses MPCDICachedLoader's internal implementation, which greatly reduces the load time of huge MPCDI files.)
Parameters
InMPCDIFileName - (in) filename of the MPCDI file
OutMPCDIFileStructure - (out) readed mpcdi structure in format: TMap<BufferId, TMap<RegionId, MPCDIAttributes>>
Returns
true if success
Field Documentation
ModuleName
const TCHAR* IDisplayClusterWarp::ModuleName = TEXT("DisplayClusterWarp") static constexpr
Definition at line 14 of file IDisplayClusterWarp.h.
Referenced by Get(), and IsAvailable().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/nDisplay/Source/DisplayClusterWarp/Public/IDisplayClusterWarp.h