Unreal Engine 5.6 C++ API: Metasound::Frontend::FMetasoundGraphAnalyzerView Class Reference
Metasound::Frontend::FMetasoundGraphAnalyzerView Class Reference
#include "MetasoundFrontendGraphAnalyzerView.h"
Public Member Functions
FMetasoundGraphAnalyzerView ()=default
METASOUNDFRONTEND_API FMetasoundGraphAnalyzerView (const FMetasoundAssetBase &InAssetBase, uint64 InInstanceID, const FOperatorSettings &InOperatorSettings)
METASOUNDFRONTEND_API ~FMetasoundGraphAnalyzerView ()
METASOUNDFRONTEND_API void AddAnalyzerForAllSupportedOutputs (FName InAnalyzerName, bool bInRequiresConnection=true)
METASOUNDFRONTEND_API FGuid AddAnalyzerForSpecifiedOutput (const FGuid &InNodeID, FVertexName InOutputName, FName InAnalyzerName, FName InAnalyzerMemberName)
METASOUNDFRONTEND_API TArray< FMetasoundAnalyzerView * > GetAnalyzerViews (FName InAnalyzerName)
METASOUNDFRONTEND_API TArray< const FMetasoundAnalyzerView * > GetAnalyzerViews (FName InAnalyzerName) const
METASOUNDFRONTEND_API TArray< FMetasoundAnalyzerView * > GetAnalyzerViewsForOutput (const FGuid &InNodeID, FName InOutputName, FName InAnalyzerName)
METASOUNDFRONTEND_API TArray< const FMetasoundAnalyzerView * > GetAnalyzerViewsForOutput (const FGuid &InNodeID, FName InOutputName, FName InAnalyzerName) const
METASOUNDFRONTEND_API bool HasAnalyzerInstance (FName InAnalyzerName, const FGuid &InAnalyzerInstanceID) const
METASOUNDFRONTEND_API void RemoveAnalyzerForAllSupportedOutputs (FName InAnalyzerName)
METASOUNDFRONTEND_API void RemoveAnalyzerInstance (FName InAnalyzerName, const FGuid &InAnalyzerInstanceID)
Private Types
using FMetasoundGraphAnalyzerOutputKey = TTuple<FGuid , FName >
Private Member Functions
FMetasoundGraphAnalyzerView (const FMetasoundGraphAnalyzerView &)=delete
FMetasoundGraphAnalyzerView (FMetasoundGraphAnalyzerView &&)=delete
METASOUNDFRONTEND_API const FMetasoundAssetBase & GetMetaSoundAssetChecked () const
FMetasoundGraphAnalyzerView & operator= (const FMetasoundGraphAnalyzerView &)=delete
FMetasoundGraphAnalyzerView & operator= (FMetasoundGraphAnalyzerView &&)=delete
METASOUNDFRONTEND_API void SendActiveAnalyzers ()
Private Attributes
TSet< FAnalyzerAddress > ActiveAnalyzers
TUniquePtr< ISender > ActiveAnalyzerSender
TMap< FMetasoundGraphAnalyzerOutputKey, TArray< FMetasoundAnalyzerView > > AnalyzerViews
uint64 InstanceID = INDEX_NONE
const FMetasoundAssetBase * MetaSoundAsset = nullptr
FOperatorSettings OperatorSettings = { 48000, 100 }
Detailed Description
Definition at line 23 of file MetasoundFrontendGraphAnalyzerView.h.
Member Typedef Documentation
FMetasoundGraphAnalyzerOutputKey
using Metasound::Frontend::FMetasoundGraphAnalyzerView::FMetasoundGraphAnalyzerOutputKey = TTuple<FGuid , FName > private
Definition at line 39 of file MetasoundFrontendGraphAnalyzerView.h.
Constructor & Destructor Documentation
FMetasoundGraphAnalyzerView() [1/4]
Metasound::Frontend::FMetasoundGraphAnalyzerView::FMetasoundGraphAnalyzerView (const FMetasoundGraphAnalyzerView &) private delete
References FMetasoundGraphAnalyzerView().
Referenced by FMetasoundGraphAnalyzerView(), FMetasoundGraphAnalyzerView(), operator=(), and operator=().
FMetasoundGraphAnalyzerView() [2/4]
Metasound::Frontend::FMetasoundGraphAnalyzerView::FMetasoundGraphAnalyzerView (FMetasoundGraphAnalyzerView &&) private delete
References FMetasoundGraphAnalyzerView().
FMetasoundGraphAnalyzerView() [3/4]
Metasound::Frontend::FMetasoundGraphAnalyzerView::FMetasoundGraphAnalyzerView () default
FMetasoundGraphAnalyzerView() [4/4]
METASOUNDFRONTEND_API Metasound::Frontend::FMetasoundGraphAnalyzerView::FMetasoundGraphAnalyzerView (const FMetasoundAssetBase & InAssetBase, uint64 InInstanceID, const FOperatorSettings & InOperatorSettings)
References UE_API.
~FMetasoundGraphAnalyzerView()
METASOUNDFRONTEND_API Metasound::Frontend::FMetasoundGraphAnalyzerView::~FMetasoundGraphAnalyzerView ()
References UE_API.
Member Function Documentation
AddAnalyzerForAllSupportedOutputs()
METASOUNDFRONTEND_API void Metasound::Frontend::FMetasoundGraphAnalyzerView::AddAnalyzerForAllSupportedOutputs (FName InAnalyzerName, bool bInRequiresConnection = true)
References UE_API.
AddAnalyzerForSpecifiedOutput()
METASOUNDFRONTEND_API FGuid Metasound::Frontend::FMetasoundGraphAnalyzerView::AddAnalyzerForSpecifiedOutput (const FGuid & InNodeID, FVertexName InOutputName, FName InAnalyzerName, FName InAnalyzerMemberName)
References UE_API.
GetAnalyzerViews() [1/2]
METASOUNDFRONTEND_API TArray< FMetasoundAnalyzerView * > Metasound::Frontend::FMetasoundGraphAnalyzerView::GetAnalyzerViews (FName InAnalyzerName)
References UE_API.
GetAnalyzerViews() [2/2]
METASOUNDFRONTEND_API TArray< const FMetasoundAnalyzerView * > Metasound::Frontend::FMetasoundGraphAnalyzerView::GetAnalyzerViews (FName InAnalyzerName) const
References UE_API.
GetAnalyzerViewsForOutput() [1/2]
METASOUNDFRONTEND_API TArray< FMetasoundAnalyzerView * > Metasound::Frontend::FMetasoundGraphAnalyzerView::GetAnalyzerViewsForOutput (const FGuid & InNodeID, FName InOutputName, FName InAnalyzerName)
References UE_API.
GetAnalyzerViewsForOutput() [2/2]
METASOUNDFRONTEND_API TArray< const FMetasoundAnalyzerView * > Metasound::Frontend::FMetasoundGraphAnalyzerView::GetAnalyzerViewsForOutput (const FGuid & InNodeID, FName InOutputName, FName InAnalyzerName) const
References UE_API.
GetMetaSoundAssetChecked()
METASOUNDFRONTEND_API const FMetasoundAssetBase & Metasound::Frontend::FMetasoundGraphAnalyzerView::GetMetaSoundAssetChecked () const private
References UE_API.
HasAnalyzerInstance()
METASOUNDFRONTEND_API bool Metasound::Frontend::FMetasoundGraphAnalyzerView::HasAnalyzerInstance (FName InAnalyzerName, const FGuid & InAnalyzerInstanceID) const
References UE_API.
operator=() [1/2]
FMetasoundGraphAnalyzerView & Metasound::Frontend::FMetasoundGraphAnalyzerView::operator= (const FMetasoundGraphAnalyzerView &) private delete
References FMetasoundGraphAnalyzerView().
operator=() [2/2]
FMetasoundGraphAnalyzerView & Metasound::Frontend::FMetasoundGraphAnalyzerView::operator= (FMetasoundGraphAnalyzerView &&) private delete
References FMetasoundGraphAnalyzerView().
RemoveAnalyzerForAllSupportedOutputs()
METASOUNDFRONTEND_API void Metasound::Frontend::FMetasoundGraphAnalyzerView::RemoveAnalyzerForAllSupportedOutputs (FName InAnalyzerName)
References UE_API.
RemoveAnalyzerInstance()
METASOUNDFRONTEND_API void Metasound::Frontend::FMetasoundGraphAnalyzerView::RemoveAnalyzerInstance (FName InAnalyzerName, const FGuid & InAnalyzerInstanceID)
References UE_API.
SendActiveAnalyzers()
METASOUNDFRONTEND_API void Metasound::Frontend::FMetasoundGraphAnalyzerView::SendActiveAnalyzers () private
References UE_API.
Field Documentation
ActiveAnalyzers
TSet<FAnalyzerAddress> Metasound::Frontend::FMetasoundGraphAnalyzerView::ActiveAnalyzers private
Definition at line 29 of file MetasoundFrontendGraphAnalyzerView.h.
ActiveAnalyzerSender
TUniquePtr<ISender> Metasound::Frontend::FMetasoundGraphAnalyzerView::ActiveAnalyzerSender private
Definition at line 26 of file MetasoundFrontendGraphAnalyzerView.h.
AnalyzerViews
TMap<FMetasoundGraphAnalyzerOutputKey, TArray<FMetasoundAnalyzerView> > Metasound::Frontend::FMetasoundGraphAnalyzerView::AnalyzerViews private
Definition at line 40 of file MetasoundFrontendGraphAnalyzerView.h.
InstanceID
uint64 Metasound::Frontend::FMetasoundGraphAnalyzerView::InstanceID = INDEX_NONE private
Definition at line 34 of file MetasoundFrontendGraphAnalyzerView.h.
MetaSoundAsset
const FMetasoundAssetBase* Metasound::Frontend::FMetasoundGraphAnalyzerView::MetaSoundAsset = nullptr private
Definition at line 35 of file MetasoundFrontendGraphAnalyzerView.h.
OperatorSettings
FOperatorSettings Metasound::Frontend::FMetasoundGraphAnalyzerView::OperatorSettings = { 48000, 100 } private
Definition at line 37 of file MetasoundFrontendGraphAnalyzerView.h.
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/Metasound/Source/MetasoundFrontend/Public/Analysis/MetasoundFrontendGraphAnalyzerView.h