Unreal Engine 5.6 C++ API: IBlueprintNodeBinder Class Reference
IBlueprintNodeBinder Class Reference abstract
#include "BlueprintNodeBinder.h"
Public Types
typedef TSet< FBindingObject > FBindingSet
Public Member Functions
bool ApplyBindings (UEdGraphNode *Node, FBindingSet const &Bindings) const
Attempts to bind all bindings to the supplied node.
virtual bool CanBindMultipleObjects () const =0
Determines if this will accept more than one binding (used to block multiple bindings from being applied to nodes that can only have one).
virtual bool IsBindingCompatible (FBindingObject BindingCandidate) const =0
Checks to see if the specified object can be bound by this.
Protected Member Functions
virtual bool BindToNode (UEdGraphNode *Node, FBindingObject Binding) const =0
Attempts to apply the specified binding to the supplied node.
Detailed Description
Definition at line 221 of file BlueprintNodeBinder.h.
Member Typedef Documentation
FBindingSet
typedef TSet< FBindingObject > IBlueprintNodeBinder::FBindingSet
Definition at line 225 of file BlueprintNodeBinder.h.
Member Function Documentation
ApplyBindings()
bool IBlueprintNodeBinder::ApplyBindings (UEdGraphNode * Node, FBindingSet const & Bindings) const inline
Attempts to bind all bindings to the supplied node.
Parameters
Node The node you want bound to.
Returns
True if all bindings were successfully applied, false if any failed.
Definition at line 250 of file BlueprintNodeBinder.h.
References BindToNode(), CanBindMultipleObjects(), and TSet< InElementType, KeyFuncs, Allocator >::Num().
BindToNode()
virtual bool IBlueprintNodeBinder::BindToNode (UEdGraphNode * Node, FBindingObject Binding) const protected pure virtual
Attempts to apply the specified binding to the supplied node.
Parameters
Node The node you want bound.
Binding The binding you want applied to Node.
Returns
True if the binding was successful, false if not.
Referenced by ApplyBindings().
CanBindMultipleObjects()
virtual bool IBlueprintNodeBinder::CanBindMultipleObjects () const pure virtual
Determines if this will accept more than one binding (used to block multiple bindings from being applied to nodes that can only have one).
Returns
True if this will accept multiple bindings, otherwise false.
Referenced by ApplyBindings().
IsBindingCompatible()
virtual bool IBlueprintNodeBinder::IsBindingCompatible (FBindingObject BindingCandidate) const pure virtual
Checks to see if the specified object can be bound by this.
Parameters
BindingCandidate The object you want to check for.
Returns
True if BindingCandidate can be bound by this controller, false if not.
The documentation for this class was generated from the following file:
Editor/BlueprintGraph/Classes/BlueprintNodeBinder.h