Unreal Engine 5.6 C++ API: UE::Geometry::FDynamicMeshAttributeSet Class Reference
UE::Geometry::FDynamicMeshAttributeSet Class Reference
FDynamicMeshAttributeSet manages a set of extended attributes for a FDynamicMesh3.
#include "DynamicMeshAttributeSet.h"
Public Member Functions
GEOMETRYCORE_API FDynamicMeshAttributeSet (FDynamicMesh3 *Mesh)
GEOMETRYCORE_API FDynamicMeshAttributeSet (FDynamicMesh3 *Mesh, int32 NumUVLayers, int32 NumNormalLayers)
virtual GEOMETRYCORE_API ~FDynamicMeshAttributeSet () override
GEOMETRYCORE_API bool AppendBonesUnique (const FDynamicMeshAttributeSet &Other)
Append bone attributes from another set.
void AttachAttribute (FName AttribName, FDynamicMeshAttributeBase *Attribute)
GEOMETRYCORE_API void AttachSkinWeightsAttribute (FName InProfileName, FDynamicMeshVertexSkinWeightsAttribute *InAttribute)
Skin weights.
GEOMETRYCORE_API bool CheckBoneValidity (EValidityCheckFailMode FailMode) const
The attribute is valid if either all attributes are empty or if the bone name attribute is not empty then all the other attributes must be either empty or their size is equal to the bone name attribute size.
GEOMETRYCORE_API void CompactCopy (const FCompactMaps &CompactMaps, const FDynamicMeshAttributeSet &Copy)
Performs a CompactCopy of the attached overlays/attributes.
GEOMETRYCORE_API void CompactInPlace (const FCompactMaps &CompactMaps)
Compacts the attribute set in place Called by the parent mesh CompactInPlace function.
GEOMETRYCORE_API void Copy (const FDynamicMeshAttributeSet &Copy)
GEOMETRYCORE_API void CopyBoneAttributes (const FDynamicMeshAttributeSet &Copy)
Copy all bone attributes from the given attribute set to this attribute set, removing any values that were there before.
GEOMETRYCORE_API void CopyBoneAttributesWithRemapping (const FDynamicMeshAttributeSet &Copy, const TMap< FName, FName > &BoneHierarchy)
Copy bone attributes from the given attribute set to this attribute set, removing any values that were there before, using the given bone hierarchy map to control which bones are copied, and how parent bone indices should be remapped.
GEOMETRYCORE_API void DisableBones ()
Disable all bone attributes.
GEOMETRYCORE_API void DisableMaterialID ()
GEOMETRYCORE_API void DisablePrimaryColors ()
GEOMETRYCORE_API void DisableTangents ()
Disable Tangents overlays.
GEOMETRYCORE_API void DiscardSculptLayers ()
GEOMETRYCORE_API void EnableBones (const int InBonesNum)
Enable all bone attributes and intialize their size to the given bone number.
GEOMETRYCORE_API void EnableMatchingAttributes (const FDynamicMeshAttributeSet &ToMatch, bool bClearExisting=true, bool bDiscardExtraAttributes=false)
Enable the matching attributes and overlay layers as the ToMatch set, but do not copy any data across.
GEOMETRYCORE_API void EnableMatchingBoneAttributes (const FDynamicMeshAttributeSet &ToMatch, bool bClearExisting, bool bDiscardExtraAttributes)
GEOMETRYCORE_API void EnableMaterialID ()
GEOMETRYCORE_API void EnablePrimaryColors ()
GEOMETRYCORE_API void EnableSculptLayers (int32 MinLayers)
GEOMETRYCORE_API void EnableTangents ()
Enable Tangents overlays (Tangent = Normal layer 1, Bitangent = Normal layer 2)
FDynamicMeshAttributeBase * GetAttachedAttribute (FName AttribName)
const FDynamicMeshAttributeBase * GetAttachedAttribute (FName AttribName) const
const TMap< FName, TUniquePtr< FDynamicMeshAttributeBase > > & GetAttachedAttributes () const
FDynamicMeshBoneColorAttribute * GetBoneColors ()
const FDynamicMeshBoneColorAttribute * GetBoneColors () const
FDynamicMeshBoneNameAttribute * GetBoneNames ()
const FDynamicMeshBoneNameAttribute * GetBoneNames () const
FDynamicMeshBoneParentIndexAttribute * GetBoneParentIndices ()
const FDynamicMeshBoneParentIndexAttribute * GetBoneParentIndices () const
FDynamicMeshBonePoseAttribute * GetBonePoses ()
const FDynamicMeshBonePoseAttribute * GetBonePoses () const
GEOMETRYCORE_API SIZE_T GetByteCount () const
FDynamicMeshMaterialAttribute * GetMaterialID ()
const FDynamicMeshMaterialAttribute * GetMaterialID () const
FDynamicMeshNormalOverlay * GetNormalLayer (int Index)
const FDynamicMeshNormalOverlay * GetNormalLayer (int Index) const
GEOMETRYCORE_API int32 GetNumBones () const
Get number of bones.
FDynamicMesh3 * GetParentMesh ()
const FDynamicMesh3 * GetParentMesh () const
GEOMETRYCORE_API FDynamicMeshPolygroupAttribute * GetPolygroupLayer (int Index)
GEOMETRYCORE_API const FDynamicMeshPolygroupAttribute * GetPolygroupLayer (int Index) const
FDynamicMeshSculptLayers * GetSculptLayers ()
const FDynamicMeshSculptLayers * GetSculptLayers () const
FDynamicMeshVertexSkinWeightsAttribute * GetSkinWeightsAttribute (FName InProfileName) const
Returns a pointer to a skin weight attribute of the given profile name.
const TMap< FName, TUniquePtr< FDynamicMeshVertexSkinWeightsAttribute > > & GetSkinWeightsAttributes () const
Returns a map of all skin weight attributes.
FDynamicMeshUVOverlay * GetUVLayer (int Index)
const FDynamicMeshUVOverlay * GetUVLayer (int Index) const
GEOMETRYCORE_API FDynamicMeshWeightAttribute * GetWeightLayer (int Index)
GEOMETRYCORE_API const FDynamicMeshWeightAttribute * GetWeightLayer (int Index) const
bool HasAttachedAttribute (FName AttribName) const
bool HasBones () const
bool HasMaterialID () const
bool HasPrimaryColors () const
bool HasSkinWeightsAttribute (FName InProfileName) const
Returns true if the list of skin weight attributes includes the given profile name.
bool HasTangentSpace () const
GEOMETRYCORE_API bool IsCompact ()
returns true if the attached overlays/attributes are compact
virtual GEOMETRYCORE_API bool IsMaterialBoundaryEdge (int EdgeID) const
GEOMETRYCORE_API bool IsSameAs (const FDynamicMeshAttributeSet &Other, bool bIgnoreDataLayout) const
Returns true if this AttributeSet is the same as Other.
GEOMETRYCORE_API bool IsSameBoneAttributesAs (const FDynamicMeshAttributeSet &Other) const
virtual GEOMETRYCORE_API bool IsSeamEdge (int EdgeID) const
virtual GEOMETRYCORE_API bool IsSeamEdge (int EdgeID, bool &bIsUVSeamOut, bool &bIsNormalSeamOut, bool &bIsColorSeamOut, bool &bIsTangentSeamOut) const
virtual GEOMETRYCORE_API bool IsSeamEndEdge (int EdgeID) const
virtual GEOMETRYCORE_API bool IsSeamIntersectionVertex (int32 VertexID) const
virtual GEOMETRYCORE_API bool IsSeamVertex (int VertexID, bool bBoundaryIsSeam=true) const
int NumAttachedAttributes () const
virtual int NumNormalLayers () const
virtual GEOMETRYCORE_API int32 NumPolygroupLayers () const
int32 NumSculptLayers () const
virtual int NumUVLayers () const
virtual GEOMETRYCORE_API int32 NumWeightLayers () const
FDynamicMeshNormalOverlay * PrimaryBiTangents ()
const FDynamicMeshNormalOverlay * PrimaryBiTangents () const
FDynamicMeshColorOverlay * PrimaryColors ()
const FDynamicMeshColorOverlay * PrimaryColors () const
FDynamicMeshNormalOverlay * PrimaryNormals ()
const FDynamicMeshNormalOverlay * PrimaryNormals () const
FDynamicMeshNormalOverlay * PrimaryTangents ()
const FDynamicMeshNormalOverlay * PrimaryTangents () const
FDynamicMeshUVOverlay * PrimaryUV ()
const FDynamicMeshUVOverlay * PrimaryUV () const
void RemoveAttribute (FName AttribName)
GEOMETRYCORE_API void RemoveSkinWeightsAttribute (FName InProfileName)
Remove a skin weights attribute matching the given profile name.
virtual GEOMETRYCORE_API void RemoveWeightLayer (int32 Index)
Remove a weight layer at the specified index.
GEOMETRYCORE_API void Serialize (FArchive &Ar, const FCompactMaps *CompactMaps, bool bUseCompression)
Serialize to and from an archive.
virtual GEOMETRYCORE_API void SetNumNormalLayers (int Num)
Set number of Normals (3-vector float overlay) layers.
virtual GEOMETRYCORE_API void SetNumPolygroupLayers (int32 Num)
Set the number of Polygroup layers.
virtual GEOMETRYCORE_API void SetNumUVLayers (int Num)
Set number of UV (2-vector float overlay) layers.
virtual GEOMETRYCORE_API void SetNumWeightLayers (int32 Num)
Set the number of weight layers.
GEOMETRYCORE_API void SplitAllBowties (bool bParallel=true)
Split all bowtie vertices in all layers.
UE_DEPRECATED (5.3, "Please instead call the 4 argument version of IsSeamEdge, which distinguishes between tangent and normal seam edges.") GEOMETRYCORE_API virtual bool IsSeamEdge(int EdgeID
Public Member Functions inherited from UE::Geometry::TDynamicAttributeSetBase< FDynamicMesh3 >
virtual ~TDynamicAttributeSetBase ()
TDynamicAttributeBase< FDynamicMesh3 > * GetRegisteredAttribute (int Idx) const
int NumRegisteredAttributes () const
Data Fields
bool bool & bIsNormalSeamOut
bool & bIsUVSeamOut
bool bool bool &bIsColorSeamOut const
Protected Types
using GenericAttributesMap = TMap<FName, TUniquePtr<FDynamicMeshAttributeBase>>
using SkinWeightAttributesMap = TMap<FName, TUniquePtr<FDynamicMeshVertexSkinWeightsAttribute>>
Protected Member Functions
virtual GEOMETRYCORE_API bool CheckValidity (bool bAllowNonmanifold, EValidityCheckFailMode FailMode) const
Check validity of attributes.
void Initialize (int MaxVertexID, int MaxTriangleID)
Initialize the existing attribute layers with the given vertex and triangle sizes.
virtual GEOMETRYCORE_API void OnCollapseEdge (const DynamicMeshInfo::FEdgeCollapseInfo &collapseInfo)
virtual GEOMETRYCORE_API void OnFlipEdge (const DynamicMeshInfo::FEdgeFlipInfo &flipInfo)
virtual GEOMETRYCORE_API void OnMergeEdges (const DynamicMeshInfo::FMergeEdgesInfo &mergeInfo)
virtual GEOMETRYCORE_API void OnMergeVertices (const DynamicMeshInfo::FMergeVerticesInfo &mergeInfo)
virtual GEOMETRYCORE_API void OnNewTriangle (int TriangleID, bool bInserted)
virtual GEOMETRYCORE_API void OnNewVertex (int VertexID, bool bInserted)
virtual GEOMETRYCORE_API void OnPokeTriangle (const DynamicMeshInfo::FPokeTriangleInfo &pokeInfo)
virtual GEOMETRYCORE_API void OnRemoveTriangle (int TriangleID)
virtual GEOMETRYCORE_API void OnRemoveVertex (int VertexID)
virtual GEOMETRYCORE_API void OnReverseTriOrientation (int TriangleID)
virtual GEOMETRYCORE_API void OnSplitEdge (const DynamicMeshInfo::FEdgeSplitInfo &splitInfo)
virtual GEOMETRYCORE_API void OnSplitVertex (const DynamicMeshInfo::FVertexSplitInfo &SplitInfo, const TArrayView< const int > &TrianglesToUpdate)
Protected Member Functions inherited from UE::Geometry::TDynamicAttributeSetBase< FDynamicMesh3 >
void RegisterExternalAttribute (TDynamicAttributeBase< FDynamicMesh3 > *Attribute)
Stores the given attribute pointer in the attribute register, so that it will be updated with mesh changes, but does not take ownership of the attribute memory.
void ResetRegisteredAttributes ()
void UnregisterExternalAttribute (TDynamicAttributeBase< FDynamicMesh3 > *Attribute)
Protected Attributes
TUniquePtr< FDynamicMeshBoneColorAttribute > BoneColorAttrib
TUniquePtr< FDynamicMeshBoneNameAttribute > BoneNameAttrib
TUniquePtr< FDynamicMeshBoneParentIndexAttribute > BoneParentIndexAttrib
TUniquePtr< FDynamicMeshBonePoseAttribute > BonePoseAttrib
TUniquePtr< FDynamicMeshColorOverlay > ColorLayer
GenericAttributesMap GenericAttributes
TUniquePtr< FDynamicMeshMaterialAttribute > MaterialIDAttrib
TIndirectArray< FDynamicMeshNormalOverlay > NormalLayers
FDynamicMesh3 * ParentMesh
Parent mesh of this attribute set.
TIndirectArray< FDynamicMeshPolygroupAttribute > PolygroupLayers
SkinWeightAttributesMap SkinWeightAttributes
TIndirectArray< FDynamicMeshUVOverlay > UVLayers
TIndirectArray< FDynamicMeshWeightAttribute > WeightLayers
Protected Attributes inherited from UE::Geometry::TDynamicAttributeSetBase< FDynamicMesh3 >
TArray< TDynamicAttributeBase< FDynamicMesh3 > * > RegisteredAttributes
Private Member Functions
void Append (const FDynamicMeshAttributeSet &ToAppend, const FDynamicMesh3::FAppendInfo &AppendInfo)
void AppendDefaulted (const FDynamicMesh3::FAppendInfo &AppendInfo)
GEOMETRYCORE_API void Reparent (FDynamicMesh3 *NewParent)
@set the parent mesh for this overlay.
Private Attributes
FDynamicMeshSculptLayers SculptLayers
Friends
class FDynamicMesh3
class FDynamicMeshSculptLayers
GEOMETRYCORE_API FArchive & operator<< (FArchive &Ar, FDynamicMeshAttributeSet &Set)
Serialization operator for FDynamicMeshAttributeSet.
Detailed Description
FDynamicMeshAttributeSet manages a set of extended attributes for a FDynamicMesh3.
This includes UV and Normal overlays, etc.
Currently the default is to always have one UV layer and one Normal layer, but the number of layers can be requested on construction.
Todo
current internal structure is a work-in-progress
Definition at line 80 of file DynamicMeshAttributeSet.h.
Member Typedef Documentation
GenericAttributesMap
using UE::Geometry::FDynamicMeshAttributeSet::GenericAttributesMap = TMap<FName, TUniquePtr<FDynamicMeshAttributeBase>> protected
Definition at line 614 of file DynamicMeshAttributeSet.h.
SkinWeightAttributesMap
using UE::Geometry::FDynamicMeshAttributeSet::SkinWeightAttributesMap = TMap<FName, TUniquePtr<FDynamicMeshVertexSkinWeightsAttribute>> protected
Definition at line 605 of file DynamicMeshAttributeSet.h.
Constructor & Destructor Documentation
FDynamicMeshAttributeSet() [1/2]
GEOMETRYCORE_API UE::Geometry::FDynamicMeshAttributeSet::FDynamicMeshAttributeSet (FDynamicMesh3 * Mesh)
References FDynamicMesh3, and UE::Geometry::Mesh.
Referenced by Append(), AppendBonesUnique(), CompactCopy(), Copy(), CopyBoneAttributes(), CopyBoneAttributesWithRemapping(), EnableMatchingAttributes(), EnableMatchingBoneAttributes(), IsSameAs(), IsSameBoneAttributesAs(), and operator<<.
FDynamicMeshAttributeSet() [2/2]
GEOMETRYCORE_API UE::Geometry::FDynamicMeshAttributeSet::FDynamicMeshAttributeSet (FDynamicMesh3 * Mesh, int32 NumUVLayers, int32 NumNormalLayers)
References FDynamicMesh3, UE::Geometry::Mesh, NumNormalLayers(), and NumUVLayers().
~FDynamicMeshAttributeSet()
virtual GEOMETRYCORE_API UE::Geometry::FDynamicMeshAttributeSet::~FDynamicMeshAttributeSet () override virtual
Member Function Documentation
Append()
void UE::Geometry::FDynamicMeshAttributeSet::Append (const FDynamicMeshAttributeSet & ToAppend, const FDynamicMesh3::FAppendInfo & AppendInfo) private
References FDynamicMeshAttributeSet().
AppendBonesUnique()
GEOMETRYCORE_API bool UE::Geometry::FDynamicMeshAttributeSet::AppendBonesUnique (const FDynamicMeshAttributeSet & Other)
Append bone attributes from another set.
When appending, the bone attributes in the Other set will only be appended if a bone with the same name does not exist in the current bone name attribute. Hence, the order of the bones in this set is preserved.
Returns
true, if append was successful
References FDynamicMeshAttributeSet(), and Other.
AppendDefaulted()
void UE::Geometry::FDynamicMeshAttributeSet::AppendDefaulted (const FDynamicMesh3::FAppendInfo & AppendInfo) private
AttachAttribute()
void UE::Geometry::FDynamicMeshAttributeSet::AttachAttribute (FName AttribName, FDynamicMeshAttributeBase * Attribute) inline
Definition at line 519 of file DynamicMeshAttributeSet.h.
References Attribute, GenericAttributes, UE::Geometry::TDynamicAttributeSetBase< FDynamicMesh3 >::RegisterExternalAttribute(), and UE::Geometry::TDynamicAttributeSetBase< FDynamicMesh3 >::UnregisterExternalAttribute().
AttachSkinWeightsAttribute()
GEOMETRYCORE_API void UE::Geometry::FDynamicMeshAttributeSet::AttachSkinWeightsAttribute (FName InProfileName, FDynamicMeshVertexSkinWeightsAttribute * InAttribute)
Skin weights.
Create a new skin weights attribute with a given skin weights profile name. If an attribute already exists with that name, that existing attribute will be deleted.
CheckBoneValidity()
GEOMETRYCORE_API bool UE::Geometry::FDynamicMeshAttributeSet::CheckBoneValidity (EValidityCheckFailMode FailMode) const
The attribute is valid if either all attributes are empty or if the bone name attribute is not empty then all the other attributes must be either empty or their size is equal to the bone name attribute size.
CheckValidity()
virtual GEOMETRYCORE_API bool UE::Geometry::FDynamicMeshAttributeSet::CheckValidity (bool bAllowNonmanifold, EValidityCheckFailMode FailMode) const protected virtual
Check validity of attributes.
Parameters
bAllowNonmanifold Accept non-manifold topology as valid. Note that this should almost always be true for attributes; non-manifold overlays are generally valid.
FailMode Desired behavior if mesh is found invalid
Reimplemented from UE::Geometry::TDynamicAttributeSetBase< FDynamicMesh3 >.
CompactCopy()
GEOMETRYCORE_API void UE::Geometry::FDynamicMeshAttributeSet::CompactCopy (const FCompactMaps & CompactMaps, const FDynamicMeshAttributeSet & Copy)
Performs a CompactCopy of the attached overlays/attributes.
Called by the parent mesh CompactCopy function.
Parameters
CompactMaps Maps indicating how vertices and triangles were changes in the parent
Copy The attribute set to be copied
References FDynamicMeshAttributeSet(), and Copy().
CompactInPlace()
GEOMETRYCORE_API void UE::Geometry::FDynamicMeshAttributeSet::CompactInPlace (const FCompactMaps & CompactMaps)
Compacts the attribute set in place Called by the parent mesh CompactInPlace function.
Parameters
CompactMaps Maps of how the vertices and triangles were compacted in the parent
Copy()
GEOMETRYCORE_API void UE::Geometry::FDynamicMeshAttributeSet::Copy (const FDynamicMeshAttributeSet & Copy)
References FDynamicMeshAttributeSet(), and Copy().
Referenced by CompactCopy(), Copy(), CopyBoneAttributes(), and CopyBoneAttributesWithRemapping().
CopyBoneAttributes()
GEOMETRYCORE_API void UE::Geometry::FDynamicMeshAttributeSet::CopyBoneAttributes (const FDynamicMeshAttributeSet & Copy)
Copy all bone attributes from the given attribute set to this attribute set, removing any values that were there before.
Parameters
Copy The attribute set to copy from.
References FDynamicMeshAttributeSet(), and Copy().
CopyBoneAttributesWithRemapping()
GEOMETRYCORE_API void UE::Geometry::FDynamicMeshAttributeSet::CopyBoneAttributesWithRemapping (const FDynamicMeshAttributeSet & Copy, const TMap< FName, FName > & BoneHierarchy)
Copy bone attributes from the given attribute set to this attribute set, removing any values that were there before, using the given bone hierarchy map to control which bones are copied, and how parent bone indices should be remapped.
Parameters
Copy The attribute set to copy from.
BoneHierarchy The hierarchy to use to copy. The key is the bone name to copy and value is the new parent name to assign to it upon copy. The order of the resulting values is the same as in the Copy. A parent name of NAME_None indicates that the bone is a root bone and will have a parent index of INDEX_NONE. If a parent name is not in the list of bones to copy, then that bone's parent index will also be set to INDEX_NONE.
References FDynamicMeshAttributeSet(), and Copy().
DisableBones()
GEOMETRYCORE_API void UE::Geometry::FDynamicMeshAttributeSet::DisableBones ()
Disable all bone attributes.
DisableMaterialID()
GEOMETRYCORE_API void UE::Geometry::FDynamicMeshAttributeSet::DisableMaterialID ()
DisablePrimaryColors()
GEOMETRYCORE_API void UE::Geometry::FDynamicMeshAttributeSet::DisablePrimaryColors ()
DisableTangents()
GEOMETRYCORE_API void UE::Geometry::FDynamicMeshAttributeSet::DisableTangents ()
Disable Tangents overlays.
DiscardSculptLayers()
GEOMETRYCORE_API void UE::Geometry::FDynamicMeshAttributeSet::DiscardSculptLayers ()
EnableBones()
GEOMETRYCORE_API void UE::Geometry::FDynamicMeshAttributeSet::EnableBones (const int InBonesNum)
Enable all bone attributes and intialize their size to the given bone number.
EnableMatchingAttributes()
GEOMETRYCORE_API void UE::Geometry::FDynamicMeshAttributeSet::EnableMatchingAttributes (const FDynamicMeshAttributeSet & ToMatch, bool bClearExisting = true, bool bDiscardExtraAttributes = false)
Enable the matching attributes and overlay layers as the ToMatch set, but do not copy any data across.
If bClearExisting=true, all existing attributes are cleared, so after the function there is an exact match but any existing attribute data is lost (!) If bClearExisting=false, new attributes are added, but existing attributes and data are preserved If bDiscardExtraAttributes=true and bClearExisting=false, then attributes in the current set but not in ToMatch are discarded, but existing attributes are not cleared/reset
References FDynamicMeshAttributeSet().
EnableMatchingBoneAttributes()
GEOMETRYCORE_API void UE::Geometry::FDynamicMeshAttributeSet::EnableMatchingBoneAttributes (const FDynamicMeshAttributeSet & ToMatch, bool bClearExisting, bool bDiscardExtraAttributes)
References FDynamicMeshAttributeSet().
EnableMaterialID()
GEOMETRYCORE_API void UE::Geometry::FDynamicMeshAttributeSet::EnableMaterialID ()
EnablePrimaryColors()
GEOMETRYCORE_API void UE::Geometry::FDynamicMeshAttributeSet::EnablePrimaryColors ()
EnableSculptLayers()
GEOMETRYCORE_API void UE::Geometry::FDynamicMeshAttributeSet::EnableSculptLayers (int32 MinLayers)
EnableTangents()
GEOMETRYCORE_API void UE::Geometry::FDynamicMeshAttributeSet::EnableTangents ()
Enable Tangents overlays (Tangent = Normal layer 1, Bitangent = Normal layer 2)
GetAttachedAttribute() [1/2]
FDynamicMeshAttributeBase * UE::Geometry::FDynamicMeshAttributeSet::GetAttachedAttribute (FName AttribName) inline
Definition at line 538 of file DynamicMeshAttributeSet.h.
References GenericAttributes.
GetAttachedAttribute() [2/2]
const FDynamicMeshAttributeBase * UE::Geometry::FDynamicMeshAttributeSet::GetAttachedAttribute (FName AttribName) const inline
Definition at line 543 of file DynamicMeshAttributeSet.h.
References GenericAttributes.
GetAttachedAttributes()
const TMap< FName, TUniquePtr< FDynamicMeshAttributeBase > > & UE::Geometry::FDynamicMeshAttributeSet::GetAttachedAttributes () const inline
Definition at line 557 of file DynamicMeshAttributeSet.h.
References GenericAttributes.
GetBoneColors() [1/2]
FDynamicMeshBoneColorAttribute * UE::Geometry::FDynamicMeshAttributeSet::GetBoneColors () inline
Definition at line 484 of file DynamicMeshAttributeSet.h.
References BoneColorAttrib.
GetBoneColors() [2/2]
const FDynamicMeshBoneColorAttribute * UE::Geometry::FDynamicMeshAttributeSet::GetBoneColors () const inline
Definition at line 489 of file DynamicMeshAttributeSet.h.
References BoneColorAttrib.
GetBoneNames() [1/2]
FDynamicMeshBoneNameAttribute * UE::Geometry::FDynamicMeshAttributeSet::GetBoneNames () inline
Definition at line 454 of file DynamicMeshAttributeSet.h.
References BoneNameAttrib.
GetBoneNames() [2/2]
const FDynamicMeshBoneNameAttribute * UE::Geometry::FDynamicMeshAttributeSet::GetBoneNames () const inline
Definition at line 459 of file DynamicMeshAttributeSet.h.
References BoneNameAttrib.
GetBoneParentIndices() [1/2]
FDynamicMeshBoneParentIndexAttribute * UE::Geometry::FDynamicMeshAttributeSet::GetBoneParentIndices () inline
Definition at line 464 of file DynamicMeshAttributeSet.h.
References BoneParentIndexAttrib.
GetBoneParentIndices() [2/2]
const FDynamicMeshBoneParentIndexAttribute * UE::Geometry::FDynamicMeshAttributeSet::GetBoneParentIndices () const inline
Definition at line 469 of file DynamicMeshAttributeSet.h.
References BoneParentIndexAttrib.
GetBonePoses() [1/2]
FDynamicMeshBonePoseAttribute * UE::Geometry::FDynamicMeshAttributeSet::GetBonePoses () inline
Definition at line 474 of file DynamicMeshAttributeSet.h.
References BonePoseAttrib.
GetBonePoses() [2/2]
const FDynamicMeshBonePoseAttribute * UE::Geometry::FDynamicMeshAttributeSet::GetBonePoses () const inline
Definition at line 479 of file DynamicMeshAttributeSet.h.
References BonePoseAttrib.
GetByteCount()
GEOMETRYCORE_API SIZE_T UE::Geometry::FDynamicMeshAttributeSet::GetByteCount () const
GetMaterialID() [1/2]
FDynamicMeshMaterialAttribute * UE::Geometry::FDynamicMeshAttributeSet::GetMaterialID () inline
Definition at line 353 of file DynamicMeshAttributeSet.h.
References MaterialIDAttrib.
GetMaterialID() [2/2]
const FDynamicMeshMaterialAttribute * UE::Geometry::FDynamicMeshAttributeSet::GetMaterialID () const inline
Definition at line 358 of file DynamicMeshAttributeSet.h.
References MaterialIDAttrib.
GetNormalLayer() [1/2]
FDynamicMeshNormalOverlay * UE::Geometry::FDynamicMeshAttributeSet::GetNormalLayer (int Index) inline
Returns
the Normal layer at the given Index if exists, else nullptr
Definition at line 226 of file DynamicMeshAttributeSet.h.
References NormalLayers.
Referenced by PrimaryBiTangents(), PrimaryBiTangents(), PrimaryNormals(), PrimaryNormals(), PrimaryTangents(), and PrimaryTangents().
GetNormalLayer() [2/2]
const FDynamicMeshNormalOverlay * UE::Geometry::FDynamicMeshAttributeSet::GetNormalLayer (int Index) const inline
Returns
the Normal layer at the given Index if exists, else nullptr
Definition at line 236 of file DynamicMeshAttributeSet.h.
References NormalLayers.
GetNumBones()
GEOMETRYCORE_API int32 UE::Geometry::FDynamicMeshAttributeSet::GetNumBones () const
Get number of bones.
GetParentMesh() [1/2]
FDynamicMesh3 * UE::Geometry::FDynamicMeshAttributeSet::GetParentMesh () inline
Returns
the parent mesh for this overlay
Definition at line 131 of file DynamicMeshAttributeSet.h.
References FDynamicMesh3, and ParentMesh.
GetParentMesh() [2/2]
const FDynamicMesh3 * UE::Geometry::FDynamicMeshAttributeSet::GetParentMesh () const inline
Returns
the parent mesh for this overlay
Definition at line 129 of file DynamicMeshAttributeSet.h.
References FDynamicMesh3, and ParentMesh.
GetPolygroupLayer() [1/2]
GEOMETRYCORE_API FDynamicMeshPolygroupAttribute * UE::Geometry::FDynamicMeshAttributeSet::GetPolygroupLayer (int Index)
Returns
the Polygroup layer at the given Index
Referenced by UE::Geometry::FPolygroupSet::SetGroup().
GetPolygroupLayer() [2/2]
GEOMETRYCORE_API const FDynamicMeshPolygroupAttribute * UE::Geometry::FDynamicMeshAttributeSet::GetPolygroupLayer (int Index) const
Returns
the Polygroup layer at the given Index
GetSculptLayers() [1/2]
FDynamicMeshSculptLayers * UE::Geometry::FDynamicMeshAttributeSet::GetSculptLayers () inline
Definition at line 499 of file DynamicMeshAttributeSet.h.
References FDynamicMeshSculptLayers, and SculptLayers.
GetSculptLayers() [2/2]
const FDynamicMeshSculptLayers * UE::Geometry::FDynamicMeshAttributeSet::GetSculptLayers () const inline
Definition at line 494 of file DynamicMeshAttributeSet.h.
References FDynamicMeshSculptLayers, and SculptLayers.
GetSkinWeightsAttribute()
FDynamicMeshVertexSkinWeightsAttribute * UE::Geometry::FDynamicMeshAttributeSet::GetSkinWeightsAttribute (FName InProfileName) const inline
Returns a pointer to a skin weight attribute of the given profile name.
If the attribute does not exist, a nullptr is returned.
Definition at line 380 of file DynamicMeshAttributeSet.h.
References SkinWeightAttributes.
GetSkinWeightsAttributes()
const TMap< FName, TUniquePtr< FDynamicMeshVertexSkinWeightsAttribute > > & UE::Geometry::FDynamicMeshAttributeSet::GetSkinWeightsAttributes () const inline
Returns a map of all skin weight attributes.
Definition at line 393 of file DynamicMeshAttributeSet.h.
References SkinWeightAttributes.
GetUVLayer() [1/2]
FDynamicMeshUVOverlay * UE::Geometry::FDynamicMeshAttributeSet::GetUVLayer (int Index) inline
Returns
the UV layer at the given Index if exists, else nullptr
Definition at line 175 of file DynamicMeshAttributeSet.h.
References UVLayers.
Referenced by PrimaryUV(), and PrimaryUV().
GetUVLayer() [2/2]
const FDynamicMeshUVOverlay * UE::Geometry::FDynamicMeshAttributeSet::GetUVLayer (int Index) const inline
Returns
the UV layer at the given Index if exists, else nullptr
Definition at line 185 of file DynamicMeshAttributeSet.h.
References UVLayers.
GetWeightLayer() [1/2]
GEOMETRYCORE_API FDynamicMeshWeightAttribute * UE::Geometry::FDynamicMeshAttributeSet::GetWeightLayer (int Index)
Returns
the weight layer at the given Index
GetWeightLayer() [2/2]
GEOMETRYCORE_API const FDynamicMeshWeightAttribute * UE::Geometry::FDynamicMeshAttributeSet::GetWeightLayer (int Index) const
Returns
the weight layer at the given Index
HasAttachedAttribute()
bool UE::Geometry::FDynamicMeshAttributeSet::HasAttachedAttribute (FName AttribName) const inline
Definition at line 552 of file DynamicMeshAttributeSet.h.
References GenericAttributes.
HasBones()
bool UE::Geometry::FDynamicMeshAttributeSet::HasBones () const inline
Definition at line 449 of file DynamicMeshAttributeSet.h.
References BoneNameAttrib.
HasMaterialID()
bool UE::Geometry::FDynamicMeshAttributeSet::HasMaterialID () const inline
Definition at line 343 of file DynamicMeshAttributeSet.h.
References MaterialIDAttrib.
HasPrimaryColors()
bool UE::Geometry::FDynamicMeshAttributeSet::HasPrimaryColors () const inline
Definition at line 283 of file DynamicMeshAttributeSet.h.
References ColorLayer.
HasSkinWeightsAttribute()
bool UE::Geometry::FDynamicMeshAttributeSet::HasSkinWeightsAttribute (FName InProfileName) const inline
Returns true if the list of skin weight attributes includes the given profile name.
Definition at line 373 of file DynamicMeshAttributeSet.h.
References SkinWeightAttributes.
HasTangentSpace()
bool UE::Geometry::FDynamicMeshAttributeSet::HasTangentSpace () const inline
Returns
true if normal layers exist for the normal, tangent, and bitangent
Definition at line 278 of file DynamicMeshAttributeSet.h.
References PrimaryBiTangents(), PrimaryNormals(), and PrimaryTangents().
Initialize()
void UE::Geometry::FDynamicMeshAttributeSet::Initialize (int MaxVertexID, int MaxTriangleID) inline protected
Initialize the existing attribute layers with the given vertex and triangle sizes.
Definition at line 630 of file DynamicMeshAttributeSet.h.
References NormalLayers, and UVLayers.
IsCompact()
GEOMETRYCORE_API bool UE::Geometry::FDynamicMeshAttributeSet::IsCompact ()
returns true if the attached overlays/attributes are compact
IsMaterialBoundaryEdge()
virtual GEOMETRYCORE_API bool UE::Geometry::FDynamicMeshAttributeSet::IsMaterialBoundaryEdge (int EdgeID) const virtual
Returns
true if the given edge is a material ID boundary
References const, and IsMaterialBoundaryEdge().
Referenced by IsMaterialBoundaryEdge().
IsSameAs()
GEOMETRYCORE_API bool UE::Geometry::FDynamicMeshAttributeSet::IsSameAs (const FDynamicMeshAttributeSet & Other, bool bIgnoreDataLayout) const
Returns true if this AttributeSet is the same as Other.
References FDynamicMeshAttributeSet(), and Other.
IsSameBoneAttributesAs()
GEOMETRYCORE_API bool UE::Geometry::FDynamicMeshAttributeSet::IsSameBoneAttributesAs (const FDynamicMeshAttributeSet & Other) const
Note
Only compares bone names and parent indices.
References FDynamicMeshAttributeSet(), and Other.
IsSeamEdge() [1/2]
virtual GEOMETRYCORE_API bool UE::Geometry::FDynamicMeshAttributeSet::IsSeamEdge (int EdgeID) const virtual
Returns
true if the given edge is a seam edge in any overlay
Referenced by IsSeamEdge().
IsSeamEdge() [2/2]
virtual GEOMETRYCORE_API bool UE::Geometry::FDynamicMeshAttributeSet::IsSeamEdge (int EdgeID, bool & bIsUVSeamOut, bool & bIsNormalSeamOut, bool & bIsColorSeamOut, bool & bIsTangentSeamOut) const virtual
Returns
true if the given edge is a seam edge in any overlay
References bIsNormalSeamOut, bIsUVSeamOut, const, and IsSeamEdge().
IsSeamEndEdge()
virtual GEOMETRYCORE_API bool UE::Geometry::FDynamicMeshAttributeSet::IsSeamEndEdge (int EdgeID) const virtual
Returns
true if the given edge is the termination of a seam in any overlay
IsSeamIntersectionVertex()
virtual GEOMETRYCORE_API bool UE::Geometry::FDynamicMeshAttributeSet::IsSeamIntersectionVertex (int32 VertexID) const virtual
Returns
true if the given vertex is a seam intersection vertex in any overlay
References const, and IsSeamIntersectionVertex().
Referenced by IsSeamIntersectionVertex().
IsSeamVertex()
virtual GEOMETRYCORE_API bool UE::Geometry::FDynamicMeshAttributeSet::IsSeamVertex (int VertexID, bool bBoundaryIsSeam = true) const virtual
Returns
true if the given vertex is a seam vertex in any overlay
References const, and IsSeamVertex().
Referenced by IsSeamVertex().
NumAttachedAttributes()
int UE::Geometry::FDynamicMeshAttributeSet::NumAttachedAttributes () const inline
Definition at line 547 of file DynamicMeshAttributeSet.h.
References GenericAttributes.
NumNormalLayers()
virtual int UE::Geometry::FDynamicMeshAttributeSet::NumNormalLayers () const inline virtual
Returns
number of Normals layers
Definition at line 211 of file DynamicMeshAttributeSet.h.
References NormalLayers.
Referenced by FDynamicMeshAttributeSet().
NumPolygroupLayers()
virtual GEOMETRYCORE_API int32 UE::Geometry::FDynamicMeshAttributeSet::NumPolygroupLayers () const virtual
Returns
number of Polygroup layers
NumSculptLayers()
int32 UE::Geometry::FDynamicMeshAttributeSet::NumSculptLayers () const inline
Definition at line 505 of file DynamicMeshAttributeSet.h.
References SculptLayers.
NumUVLayers()
virtual int UE::Geometry::FDynamicMeshAttributeSet::NumUVLayers () const inline virtual
Returns
number of UV layers
Definition at line 166 of file DynamicMeshAttributeSet.h.
References NumUVLayers(), and UVLayers.
Referenced by FDynamicMeshAttributeSet(), and NumUVLayers().
NumWeightLayers()
virtual GEOMETRYCORE_API int32 UE::Geometry::FDynamicMeshAttributeSet::NumWeightLayers () const virtual
Returns
number of weight layers
OnCollapseEdge()
virtual GEOMETRYCORE_API void UE::Geometry::FDynamicMeshAttributeSet::OnCollapseEdge (const DynamicMeshInfo::FEdgeCollapseInfo & collapseInfo) protected virtual
Reimplemented from UE::Geometry::TDynamicAttributeSetBase< FDynamicMesh3 >.
OnFlipEdge()
virtual GEOMETRYCORE_API void UE::Geometry::FDynamicMeshAttributeSet::OnFlipEdge (const DynamicMeshInfo::FEdgeFlipInfo & flipInfo) protected virtual
Reimplemented from UE::Geometry::TDynamicAttributeSetBase< FDynamicMesh3 >.
OnMergeEdges()
virtual GEOMETRYCORE_API void UE::Geometry::FDynamicMeshAttributeSet::OnMergeEdges (const DynamicMeshInfo::FMergeEdgesInfo & mergeInfo) protected virtual
Reimplemented from UE::Geometry::TDynamicAttributeSetBase< FDynamicMesh3 >.
OnMergeVertices()
virtual GEOMETRYCORE_API void UE::Geometry::FDynamicMeshAttributeSet::OnMergeVertices (const DynamicMeshInfo::FMergeVerticesInfo & mergeInfo) protected virtual
Reimplemented from UE::Geometry::TDynamicAttributeSetBase< FDynamicMesh3 >.
OnNewTriangle()
virtual GEOMETRYCORE_API void UE::Geometry::FDynamicMeshAttributeSet::OnNewTriangle (int TriangleID, bool bInserted) protected virtual
Reimplemented from UE::Geometry::TDynamicAttributeSetBase< FDynamicMesh3 >.
OnNewVertex()
virtual GEOMETRYCORE_API void UE::Geometry::FDynamicMeshAttributeSet::OnNewVertex (int VertexID, bool bInserted) protected virtual
Reimplemented from UE::Geometry::TDynamicAttributeSetBase< FDynamicMesh3 >.
OnPokeTriangle()
virtual GEOMETRYCORE_API void UE::Geometry::FDynamicMeshAttributeSet::OnPokeTriangle (const DynamicMeshInfo::FPokeTriangleInfo & pokeInfo) protected virtual
Reimplemented from UE::Geometry::TDynamicAttributeSetBase< FDynamicMesh3 >.
OnRemoveTriangle()
virtual GEOMETRYCORE_API void UE::Geometry::FDynamicMeshAttributeSet::OnRemoveTriangle (int TriangleID) protected virtual
Reimplemented from UE::Geometry::TDynamicAttributeSetBase< FDynamicMesh3 >.
OnRemoveVertex()
virtual GEOMETRYCORE_API void UE::Geometry::FDynamicMeshAttributeSet::OnRemoveVertex (int VertexID) protected virtual
Reimplemented from UE::Geometry::TDynamicAttributeSetBase< FDynamicMesh3 >.
OnReverseTriOrientation()
virtual GEOMETRYCORE_API void UE::Geometry::FDynamicMeshAttributeSet::OnReverseTriOrientation (int TriangleID) protected virtual
Reimplemented from UE::Geometry::TDynamicAttributeSetBase< FDynamicMesh3 >.
OnSplitEdge()
virtual GEOMETRYCORE_API void UE::Geometry::FDynamicMeshAttributeSet::OnSplitEdge (const DynamicMeshInfo::FEdgeSplitInfo & splitInfo) protected virtual
Reimplemented from UE::Geometry::TDynamicAttributeSetBase< FDynamicMesh3 >.
OnSplitVertex()
virtual GEOMETRYCORE_API void UE::Geometry::FDynamicMeshAttributeSet::OnSplitVertex (const DynamicMeshInfo::FVertexSplitInfo & SplitInfo, const TArrayView< const int > & TrianglesToUpdate) protected virtual
Reimplemented from UE::Geometry::TDynamicAttributeSetBase< FDynamicMesh3 >.
PrimaryBiTangents() [1/2]
FDynamicMeshNormalOverlay * UE::Geometry::FDynamicMeshAttributeSet::PrimaryBiTangents () inline
Returns
the primary biTangent layer (normal layer 2) if exists, else nullptr
Definition at line 267 of file DynamicMeshAttributeSet.h.
References GetNormalLayer().
Referenced by HasTangentSpace().
PrimaryBiTangents() [2/2]
const FDynamicMeshNormalOverlay * UE::Geometry::FDynamicMeshAttributeSet::PrimaryBiTangents () const inline
Returns
the primary biTangent layer (normal layer 2) if exists, else nullptr
Definition at line 272 of file DynamicMeshAttributeSet.h.
References GetNormalLayer().
PrimaryColors() [1/2]
FDynamicMeshColorOverlay * UE::Geometry::FDynamicMeshAttributeSet::PrimaryColors () inline
Definition at line 288 of file DynamicMeshAttributeSet.h.
References ColorLayer.
PrimaryColors() [2/2]
const FDynamicMeshColorOverlay * UE::Geometry::FDynamicMeshAttributeSet::PrimaryColors () const inline
Definition at line 293 of file DynamicMeshAttributeSet.h.
References ColorLayer.
PrimaryNormals() [1/2]
FDynamicMeshNormalOverlay * UE::Geometry::FDynamicMeshAttributeSet::PrimaryNormals () inline
Returns
the primary Normal layer (normal layer 0) if exists, else nullptr
Definition at line 247 of file DynamicMeshAttributeSet.h.
References GetNormalLayer().
Referenced by HasTangentSpace().
PrimaryNormals() [2/2]
const FDynamicMeshNormalOverlay * UE::Geometry::FDynamicMeshAttributeSet::PrimaryNormals () const inline
Returns
the primary Normal layer (normal layer 0) if exists, else nullptr
Definition at line 252 of file DynamicMeshAttributeSet.h.
References GetNormalLayer().
PrimaryTangents() [1/2]
FDynamicMeshNormalOverlay * UE::Geometry::FDynamicMeshAttributeSet::PrimaryTangents () inline
Returns
the primary tangent layer (normal layer 1) if exists, else nullptr
Definition at line 257 of file DynamicMeshAttributeSet.h.
References GetNormalLayer().
Referenced by HasTangentSpace().
PrimaryTangents() [2/2]
const FDynamicMeshNormalOverlay * UE::Geometry::FDynamicMeshAttributeSet::PrimaryTangents () const inline
Returns
the primary tangent layer (normal layer 1) if exists, else nullptr
Definition at line 262 of file DynamicMeshAttributeSet.h.
References GetNormalLayer().
PrimaryUV() [1/2]
FDynamicMeshUVOverlay * UE::Geometry::FDynamicMeshAttributeSet::PrimaryUV () inline
Returns
the primary UV layer (layer 0)
Definition at line 195 of file DynamicMeshAttributeSet.h.
References GetUVLayer().
PrimaryUV() [2/2]
const FDynamicMeshUVOverlay * UE::Geometry::FDynamicMeshAttributeSet::PrimaryUV () const inline
Returns
the primary UV layer (layer 0)
Definition at line 200 of file DynamicMeshAttributeSet.h.
References GetUVLayer().
RemoveAttribute()
void UE::Geometry::FDynamicMeshAttributeSet::RemoveAttribute (FName AttribName) inline
Definition at line 529 of file DynamicMeshAttributeSet.h.
References GenericAttributes, and UE::Geometry::TDynamicAttributeSetBase< FDynamicMesh3 >::UnregisterExternalAttribute().
RemoveSkinWeightsAttribute()
GEOMETRYCORE_API void UE::Geometry::FDynamicMeshAttributeSet::RemoveSkinWeightsAttribute (FName InProfileName)
Remove a skin weights attribute matching the given profile name.
RemoveWeightLayer()
virtual GEOMETRYCORE_API void UE::Geometry::FDynamicMeshAttributeSet::RemoveWeightLayer (int32 Index) virtual
Remove a weight layer at the specified index.
Reparent()
GEOMETRYCORE_API void UE::Geometry::FDynamicMeshAttributeSet::Reparent (FDynamicMesh3 * NewParent) private
@set the parent mesh for this overlay.
Only safe for use during FDynamicMesh move
References FDynamicMesh3.
Serialize()
GEOMETRYCORE_API void UE::Geometry::FDynamicMeshAttributeSet::Serialize (FArchive & Ar, const FCompactMaps * CompactMaps, bool bUseCompression)
Serialize to and from an archive.
Parameters
Ar Archive to serialize with.
CompactMaps If this is not a null pointer, the mesh serialization compacted the vertex and/or triangle data using the provided mapping.
bUseCompression Use compression for serializing bulk data.
References Ar.
SetNumNormalLayers()
virtual GEOMETRYCORE_API void UE::Geometry::FDynamicMeshAttributeSet::SetNumNormalLayers (int Num) virtual
Set number of Normals (3-vector float overlay) layers.
References Num.
SetNumPolygroupLayers()
virtual GEOMETRYCORE_API void UE::Geometry::FDynamicMeshAttributeSet::SetNumPolygroupLayers (int32 Num) virtual
Set the number of Polygroup layers.
References Num.
SetNumUVLayers()
virtual GEOMETRYCORE_API void UE::Geometry::FDynamicMeshAttributeSet::SetNumUVLayers (int Num) virtual
Set number of UV (2-vector float overlay) layers.
References Num.
SetNumWeightLayers()
virtual GEOMETRYCORE_API void UE::Geometry::FDynamicMeshAttributeSet::SetNumWeightLayers (int32 Num) virtual
Set the number of weight layers.
References Num.
SplitAllBowties()
GEOMETRYCORE_API void UE::Geometry::FDynamicMeshAttributeSet::SplitAllBowties (bool bParallel = true)
Split all bowtie vertices in all layers.
Parameters
bParallel if true, layers are processed in parallel
UE_DEPRECATED()
UE::Geometry::FDynamicMeshAttributeSet::UE_DEPRECATED (5. 3, "Please instead call the 4 argument version of IsSeamEdge, which distinguishes between tangent and normal seam edges.")
Returns
true if the given edge is a seam edge in any overlay. This version considers tangent seams as a type of normal seam; to consider tangent seams separately, call the 4-argument IsSeamEdge instead.
Friends And Related Symbol Documentation
FDynamicMesh3
friend class FDynamicMesh3 friend
Definition at line 625 of file DynamicMeshAttributeSet.h.
References FDynamicMesh3.
Referenced by FDynamicMeshAttributeSet(), FDynamicMeshAttributeSet(), FDynamicMesh3, GetParentMesh(), GetParentMesh(), and Reparent().
FDynamicMeshSculptLayers
friend class FDynamicMeshSculptLayers friend
Definition at line 621 of file DynamicMeshAttributeSet.h.
References FDynamicMeshSculptLayers.
Referenced by FDynamicMeshSculptLayers, GetSculptLayers(), and GetSculptLayers().
operator<<
GEOMETRYCORE_API FArchive & operator<< (FArchive & Ar, FDynamicMeshAttributeSet & Set) friend
Serialization operator for FDynamicMeshAttributeSet.
Parameters
Ar Archive to serialize with.
Set Attribute set to serialize.
Returns
Passing down serializing archive.
Definition at line 574 of file DynamicMeshAttributeSet.h.
References FDynamicMeshAttributeSet(), and Ar.
Field Documentation
bIsNormalSeamOut
bool bool& UE::Geometry::FDynamicMeshAttributeSet::bIsNormalSeamOut
Definition at line 147 of file DynamicMeshAttributeSet.h.
Referenced by IsSeamEdge().
bIsUVSeamOut
bool& UE::Geometry::FDynamicMeshAttributeSet::bIsUVSeamOut
Definition at line 147 of file DynamicMeshAttributeSet.h.
Referenced by IsSeamEdge().
BoneColorAttrib
TUniquePtr<FDynamicMeshBoneColorAttribute> UE::Geometry::FDynamicMeshAttributeSet::BoneColorAttrib protected
Definition at line 612 of file DynamicMeshAttributeSet.h.
Referenced by GetBoneColors(), and GetBoneColors().
BoneNameAttrib
TUniquePtr<FDynamicMeshBoneNameAttribute> UE::Geometry::FDynamicMeshAttributeSet::BoneNameAttrib protected
Definition at line 609 of file DynamicMeshAttributeSet.h.
Referenced by GetBoneNames(), GetBoneNames(), and HasBones().
BoneParentIndexAttrib
TUniquePtr<FDynamicMeshBoneParentIndexAttribute> UE::Geometry::FDynamicMeshAttributeSet::BoneParentIndexAttrib protected
Definition at line 610 of file DynamicMeshAttributeSet.h.
Referenced by GetBoneParentIndices(), and GetBoneParentIndices().
BonePoseAttrib
TUniquePtr<FDynamicMeshBonePoseAttribute> UE::Geometry::FDynamicMeshAttributeSet::BonePoseAttrib protected
Definition at line 611 of file DynamicMeshAttributeSet.h.
Referenced by GetBonePoses(), and GetBonePoses().
ColorLayer
TUniquePtr<FDynamicMeshColorOverlay> UE::Geometry::FDynamicMeshAttributeSet::ColorLayer protected
Definition at line 598 of file DynamicMeshAttributeSet.h.
Referenced by HasPrimaryColors(), PrimaryColors(), and PrimaryColors().
const
bool bool bool& bIsColorSeamOut UE::Geometry::FDynamicMeshAttributeSet::const
Definition at line 147 of file DynamicMeshAttributeSet.h.
Referenced by IsMaterialBoundaryEdge(), IsSeamEdge(), IsSeamIntersectionVertex(), and IsSeamVertex().
GenericAttributes
GenericAttributesMap UE::Geometry::FDynamicMeshAttributeSet::GenericAttributes protected
Definition at line 615 of file DynamicMeshAttributeSet.h.
Referenced by AttachAttribute(), GetAttachedAttribute(), GetAttachedAttribute(), GetAttachedAttributes(), HasAttachedAttribute(), NumAttachedAttributes(), and RemoveAttribute().
MaterialIDAttrib
TUniquePtr<FDynamicMeshMaterialAttribute> UE::Geometry::FDynamicMeshAttributeSet::MaterialIDAttrib protected
Definition at line 600 of file DynamicMeshAttributeSet.h.
Referenced by GetMaterialID(), GetMaterialID(), and HasMaterialID().
NormalLayers
TIndirectArray<FDynamicMeshNormalOverlay> UE::Geometry::FDynamicMeshAttributeSet::NormalLayers protected
Definition at line 597 of file DynamicMeshAttributeSet.h.
Referenced by GetNormalLayer(), GetNormalLayer(), Initialize(), and NumNormalLayers().
ParentMesh
FDynamicMesh3* UE::Geometry::FDynamicMeshAttributeSet::ParentMesh protected
Parent mesh of this attribute set.
Definition at line 593 of file DynamicMeshAttributeSet.h.
Referenced by GetParentMesh(), and GetParentMesh().
PolygroupLayers
TIndirectArray<FDynamicMeshPolygroupAttribute> UE::Geometry::FDynamicMeshAttributeSet::PolygroupLayers protected
Definition at line 603 of file DynamicMeshAttributeSet.h.
SculptLayers
FDynamicMeshSculptLayers UE::Geometry::FDynamicMeshAttributeSet::SculptLayers private
Definition at line 620 of file DynamicMeshAttributeSet.h.
Referenced by GetSculptLayers(), GetSculptLayers(), and NumSculptLayers().
SkinWeightAttributes
SkinWeightAttributesMap UE::Geometry::FDynamicMeshAttributeSet::SkinWeightAttributes protected
Definition at line 606 of file DynamicMeshAttributeSet.h.
Referenced by GetSkinWeightsAttribute(), GetSkinWeightsAttributes(), and HasSkinWeightsAttribute().
UVLayers
TIndirectArray<FDynamicMeshUVOverlay> UE::Geometry::FDynamicMeshAttributeSet::UVLayers protected
Definition at line 596 of file DynamicMeshAttributeSet.h.
Referenced by GetUVLayer(), GetUVLayer(), Initialize(), and NumUVLayers().
WeightLayers
TIndirectArray<FDynamicMeshWeightAttribute> UE::Geometry::FDynamicMeshAttributeSet::WeightLayers protected
Definition at line 602 of file DynamicMeshAttributeSet.h.
The documentation for this class was generated from the following file:
Runtime/GeometryCore/Public/DynamicMesh/DynamicMeshAttributeSet.h