Unreal Engine 5.6 C++ API: AsyncCompilationHelpers::TCompilableAsyncTask< AsyncTaskType > Class Template Reference
AsyncCompilationHelpers::TCompilableAsyncTask< AsyncTaskType > Class Template Reference abstract
#include "AsyncCompilationHelpers.h"
Private Member Functions
virtual AsyncTaskType * GetAsyncTask ()=0
void Reschedule (FQueuedThreadPool *InThreadPool, EQueuedWorkPriority InPriority) override
bool WaitCompletionWithTimeout (float TimeLimitSeconds) override
Additional Inherited Members
Public Member Functions inherited from AsyncCompilationHelpers::ICompilable
virtual ~ICompilable ()
virtual FName GetName ()=0
Detailed Description
template<typename AsyncTaskType>
class AsyncCompilationHelpers::TCompilableAsyncTask< AsyncTaskType >
Definition at line 53 of file AsyncCompilationHelpers.h.
Member Function Documentation
GetAsyncTask()
template<typename AsyncTaskType> virtual AsyncTaskType * AsyncCompilationHelpers::TCompilableAsyncTask< AsyncTaskType >::GetAsyncTask () private pure virtual
Referenced by Reschedule(), and WaitCompletionWithTimeout().
Reschedule()
template<typename AsyncTaskType> void AsyncCompilationHelpers::TCompilableAsyncTask< AsyncTaskType >::Reschedule (FQueuedThreadPool * InThreadPool, EQueuedWorkPriority InPriority) inline override private virtual
Implements AsyncCompilationHelpers::ICompilable.
Definition at line 57 of file AsyncCompilationHelpers.h.
References AsyncTask(), and GetAsyncTask().
WaitCompletionWithTimeout()
template<typename AsyncTaskType> bool AsyncCompilationHelpers::TCompilableAsyncTask< AsyncTaskType >::WaitCompletionWithTimeout (float TimeLimitSeconds) inline override private virtual
Implements AsyncCompilationHelpers::ICompilable.
Definition at line 65 of file AsyncCompilationHelpers.h.
References AsyncTask(), and GetAsyncTask().
The documentation for this class was generated from the following file:
Runtime/Engine/Public/AsyncCompilationHelpers.h