Unreal Engine 5.6 C++ API: UE::TSharedLock< FSharedRecursiveMutex > Class Reference
UE::TSharedLock< FSharedRecursiveMutex > Class Reference final
#include "SharedRecursiveMutex.h"
Public Member Functions
TSharedLock (const TSharedLock &)=delete
TSharedLock (FSharedRecursiveMutex &Lock)
~TSharedLock ()
TSharedLock & operator= (const TSharedLock &)=delete
Private Attributes
Core::Private::FSharedRecursiveMutexLink Link
FSharedRecursiveMutex & Mutex
Detailed Description
Definition at line 76 of file SharedRecursiveMutex.h.
Constructor & Destructor Documentation
TSharedLock() [1/2]
UE::TSharedLock< FSharedRecursiveMutex >::TSharedLock (const TSharedLock< FSharedRecursiveMutex > &) delete
References TSharedLock().
Referenced by TSharedLock(), and operator=().
TSharedLock() [2/2]
UE::TSharedLock< FSharedRecursiveMutex >::TSharedLock (FSharedRecursiveMutex & Lock) inline explicit nodiscard
Definition at line 82 of file SharedRecursiveMutex.h.
References Link, and Mutex.
~TSharedLock()
UE::TSharedLock< FSharedRecursiveMutex >::~TSharedLock () inline
Definition at line 88 of file SharedRecursiveMutex.h.
References Link, and Mutex.
Member Function Documentation
operator=()
TSharedLock & UE::TSharedLock< FSharedRecursiveMutex >::operator= (const TSharedLock< FSharedRecursiveMutex > &) delete
References TSharedLock().
Field Documentation
Link
Core::Private::FSharedRecursiveMutexLink UE::TSharedLock< FSharedRecursiveMutex >::Link private
Definition at line 95 of file SharedRecursiveMutex.h.
Referenced by TSharedLock(), and ~TSharedLock().
Mutex
FSharedRecursiveMutex& UE::TSharedLock< FSharedRecursiveMutex >::Mutex private
Definition at line 94 of file SharedRecursiveMutex.h.
Referenced by TSharedLock(), and ~TSharedLock().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Async/SharedRecursiveMutex.h