Unreal Engine 5.6 C++ API: TMeshAttributesRef< ElementIDType, AttributeType > Class Template Reference
TMeshAttributesRef< ElementIDType, AttributeType > Class Template Reference
This is the class used to access attribute values.
#include "MeshAttributeArray.h"
Public Types
using ArrayType = TCopyQualifiersFromTo_T<AttributeType, TMeshAttributeArraySet<std::remove_cv_t<AttributeType>>>
using BaseArrayType = TCopyQualifiersFromTo_T<AttributeType, FMeshAttributeArraySetBase>
Public Member Functions
TMeshAttributesRef (BaseArrayType *InArrayPtr=nullptr, uint32 InExtent=1)
Constructor taking a pointer to a FMeshAttributeArraySetBase.
template<typename SrcAttributeType, typename DestAttributeType = AttributeType, typename TEnableIf< std::is_const_v< DestAttributeType >, int >::Type = 0, typename TEnableIf<!std::is_const_v< SrcAttributeType >, int >::Type = 0>
TMeshAttributesRef (const TMeshAttributesRef< ElementIDType, SrcAttributeType > &InRef)
Implicitly construct a TMeshAttributesRef-to-const from a regular one.
template<typename IDType = ElementIDType, typename TEnableIf<!std::is_same_v< IDType, int32 >, int >::Type = 0>
TMeshAttributesRef (const TMeshAttributesRef< int32, AttributeType > &InRef)
Implicitly construct a TMeshAttributesRef from a TMeshAttributesArray.
template<typename SrcAttributeType, typename DestAttributeType = AttributeType, typename IDType = ElementIDType, typename TEnableIf<!std::is_same_v< IDType, int32 >, int >::Type = 0, typename TEnableIf< std::is_const_v< DestAttributeType >, int >::Type = 0, typename TEnableIf<!std::is_const_v< SrcAttributeType >, int >::Type = 0>
TMeshAttributesRef (const TMeshAttributesRef< int32, SrcAttributeType > &InRef)
Implicitly construct a TMeshAttributesRef-to-const from a TMeshAttributesArray.
void Copy (TMeshAttributesRef< ElementIDType, const AttributeType > Src, const int32 DestChannel=0, const int32 SrcChannel=0)
Copies the given attribute array and channel to this channel.
template<typename T = ElementIDType, typename TEnableIf< TIsDerivedFrom< T, FElementID >::Value, int >::Type = 0>
AttributeType Get (const ElementIDType ElementID, const int32 Channel=0) const
Get the element with the given ID and channel.
AttributeType Get (int32 ElementIndex, const int32 Channel=0) const
TArrayView< AttributeType > GetArrayView (int32 ElementIndex, const int32 Channel=0) const
AttributeType GetDefaultValue () const
Return default value for this attribute type.
uint32 GetExtent () const
Get the extent for this attribute type.
EMeshAttributeFlags GetFlags () const
Get the flags for this attribute array set.
int32 GetNumChannels () const
Return number of indices this attribute has.
int32 GetNumElements () const
Get the number of elements in this attribute array.
TArrayView< AttributeType > GetRawArray (const int32 AttributeChannel=0) const
void InsertChannel (const int32 Channel) const
Inserts an attribute channel.
bool IsValid () const
Return whether the reference is valid or not.
template<typename T = ElementIDType, typename TEnableIf< TIsDerivedFrom< T, FElementID >::Value, int >::Type = 0>
AttributeType & operator[] (const ElementIDType ElementID) const
Access elements from attribute channel 0.
AttributeType & operator[] (int32 ElementIndex) const
void RemoveChannel (const int32 Channel) const
Removes an attribute channel.
template<typename T = ElementIDType, typename TEnableIf< TIsDerivedFrom< T, FElementID >::Value, int >::Type = 0>
void Set (const ElementIDType ElementID, const AttributeType &Value) const
Set the element with the given ID and index 0 to the provided value.
template<typename T = ElementIDType, typename TEnableIf< TIsDerivedFrom< T, FElementID >::Value, int >::Type = 0>
void Set (const ElementIDType ElementID, const int32 Channel, const AttributeType &Value) const
Set the element with the given ID and channel to the provided value.
void Set (int32 ElementIndex, const AttributeType &Value) const
void Set (int32 ElementIndex, const int32 Channel, const AttributeType &Value) const
void SetArrayView (int32 ElementIndex, const int32 Channel, TArrayView< const AttributeType > Value) const
void SetArrayView (int32 ElementIndex, TArrayView< const AttributeType > Value) const
void SetNumChannels (const int32 NumChannels) const
Sets number of channels this attribute has.
UE_DEPRECATED (5.0, "Please use GetNumChannels().") int32 GetNumIndices() const
UE_DEPRECATED (5.0, "Please use InsertChannel().") void InsertIndex(const int32 Index) const
UE_DEPRECATED (5.0, "Please use RemoveChannel().") void RemoveIndex(const int32 Index) const
UE_DEPRECATED (5.0, "Please use SetNumChannels().") void SetNumIndices(const int32 NumChannels) const
Private Attributes
BaseArrayType * ArrayPtr
Friends
template<typename T, typename U>
class TMeshAttributesRef
Detailed Description
template<typename ElementIDType, typename AttributeType>
class TMeshAttributesRef< ElementIDType, AttributeType >
This is the class used to access attribute values.
It is a proxy object to a TMeshAttributeArraySet<> and should be passed by value. It is valid for as long as the owning FMeshDescription exists.
Definition at line 834 of file MeshAttributeArray.h.
Member Typedef Documentation
ArrayType
template<typename ElementIDType, typename AttributeType> using TMeshAttributesRef< ElementIDType, AttributeType >::ArrayType = TCopyQualifiersFromTo_T<AttributeType, TMeshAttributeArraySet<std::remove_cv_t<AttributeType>>>
Definition at line 840 of file MeshAttributeArray.h.
BaseArrayType
template<typename ElementIDType, typename AttributeType> using TMeshAttributesRef< ElementIDType, AttributeType >::BaseArrayType = TCopyQualifiersFromTo_T<AttributeType, FMeshAttributeArraySetBase>
Definition at line 839 of file MeshAttributeArray.h.
Constructor & Destructor Documentation
TMeshAttributesRef() [1/4]
template<typename ElementIDType, typename AttributeType> TMeshAttributesRef< ElementIDType, AttributeType >::TMeshAttributesRef (BaseArrayType * InArrayPtr = nullptr, uint32 InExtent = 1) inline explicit
Constructor taking a pointer to a FMeshAttributeArraySetBase.
Definition at line 843 of file MeshAttributeArray.h.
TMeshAttributesRef() [2/4]
template<typename ElementIDType, typename AttributeType> template<typename SrcAttributeType, typename DestAttributeType = AttributeType, typename TEnableIf< std::is_const_v< DestAttributeType >, int >::Type = 0, typename TEnableIf<!std::is_const_v< SrcAttributeType >, int >::Type = 0> TMeshAttributesRef< ElementIDType, AttributeType >::TMeshAttributesRef (const TMeshAttributesRef< ElementIDType, SrcAttributeType > & InRef) inline
Implicitly construct a TMeshAttributesRef-to-const from a regular one.
Definition at line 852 of file MeshAttributeArray.h.
TMeshAttributesRef() [3/4]
template<typename ElementIDType, typename AttributeType> template<typename IDType = ElementIDType, typename TEnableIf<!std::is_same_v< IDType, int32 >, int >::Type = 0> TMeshAttributesRef< ElementIDType, AttributeType >::TMeshAttributesRef (const TMeshAttributesRef< int32, AttributeType > & InRef) inline
Implicitly construct a TMeshAttributesRef from a TMeshAttributesArray.
Definition at line 859 of file MeshAttributeArray.h.
TMeshAttributesRef() [4/4]
template<typename ElementIDType, typename AttributeType> template<typename SrcAttributeType, typename DestAttributeType = AttributeType, typename IDType = ElementIDType, typename TEnableIf<!std::is_same_v< IDType, int32 >, int >::Type = 0, typename TEnableIf< std::is_const_v< DestAttributeType >, int >::Type = 0, typename TEnableIf<!std::is_const_v< SrcAttributeType >, int >::Type = 0> TMeshAttributesRef< ElementIDType, AttributeType >::TMeshAttributesRef (const TMeshAttributesRef< int32, SrcAttributeType > & InRef) inline
Implicitly construct a TMeshAttributesRef-to-const from a TMeshAttributesArray.
Definition at line 870 of file MeshAttributeArray.h.
Member Function Documentation
Copy()
template<typename ElementIDType, typename AttributeType> void TMeshAttributesRef< ElementIDType, AttributeType >::Copy (TMeshAttributesRef< ElementIDType, const AttributeType > Src, const int32 DestChannel = 0, const int32 SrcChannel = 0)
Copies the given attribute array and channel to this channel.
Definition at line 1024 of file MeshAttributeArray.h.
References TMeshAttributesRef, ArrayPtr, check, TMeshAttributeArrayBase< AttributeType >::GetElementBase(), IsValid(), FMath::Min, Num, and TMeshAttributeArrayBase< AttributeType >::Num().
Get() [1/2]
template<typename ElementIDType, typename AttributeType> template<typename T = ElementIDType, typename TEnableIf< TIsDerivedFrom< T, FElementID >::Value, int >::Type = 0> AttributeType TMeshAttributesRef< ElementIDType, AttributeType >::Get (const ElementIDType ElementID, const int32 Channel = 0) const inline
Get the element with the given ID and channel.
Definition at line 883 of file MeshAttributeArray.h.
Referenced by TMeshAttributesRef< ElementIDType, TArrayAttribute< AttributeType > >::GetArrayView(), TMeshAttributesRef< ElementIDType, TArrayView< AttributeType > >::Set(), TMeshAttributesRef< ElementIDType, TArrayView< AttributeType > >::Set(), TMeshAttributesRef< ElementIDType, TArrayView< AttributeType > >::Set(), and TMeshAttributesRef< ElementIDType, TArrayView< AttributeType > >::Set().
Get() [2/2]
template<typename ElementIDType, typename AttributeType> AttributeType TMeshAttributesRef< ElementIDType, AttributeType >::Get (int32 ElementIndex, const int32 Channel = 0) const inline
Definition at line 893 of file MeshAttributeArray.h.
GetArrayView()
template<typename ElementIDType, typename AttributeType> TArrayView< AttributeType > TMeshAttributesRef< ElementIDType, AttributeType >::GetArrayView (int32 ElementIndex, const int32 Channel = 0) const inline
Definition at line 898 of file MeshAttributeArray.h.
GetDefaultValue()
template<typename ElementIDType, typename AttributeType> AttributeType TMeshAttributesRef< ElementIDType, AttributeType >::GetDefaultValue () const inline
Return default value for this attribute type.
Definition at line 918 of file MeshAttributeArray.h.
Referenced by TMeshAttributesRef< FStrandID, AttributeType >::GetDefaultValue().
GetExtent()
template<typename ElementIDType, typename AttributeType> uint32 TMeshAttributesRef< ElementIDType, AttributeType >::GetExtent () const inline
Get the extent for this attribute type.
Definition at line 942 of file MeshAttributeArray.h.
GetFlags()
template<typename ElementIDType, typename AttributeType> EMeshAttributeFlags TMeshAttributesRef< ElementIDType, AttributeType >::GetFlags () const inline
Get the flags for this attribute array set.
Definition at line 939 of file MeshAttributeArray.h.
GetNumChannels()
template<typename ElementIDType, typename AttributeType> int32 TMeshAttributesRef< ElementIDType, AttributeType >::GetNumChannels () const inline
Return number of indices this attribute has.
Definition at line 927 of file MeshAttributeArray.h.
GetNumElements()
template<typename ElementIDType, typename AttributeType> int32 TMeshAttributesRef< ElementIDType, AttributeType >::GetNumElements () const inline
Get the number of elements in this attribute array.
Definition at line 933 of file MeshAttributeArray.h.
Referenced by TMeshAttributesRef< ElementIDType, TArrayAttribute< AttributeType > >::GetRawArray(), TMeshAttributesRef< ElementIDType, TArrayView< AttributeType > >::GetRawArray(), and TMeshAttributesRef< FStrandID, AttributeType >::GetRawArray().
GetRawArray()
template<typename ElementIDType, typename AttributeType> TArrayView< AttributeType > TMeshAttributesRef< ElementIDType, AttributeType >::GetRawArray (const int32 AttributeChannel = 0) const inline
Definition at line 903 of file MeshAttributeArray.h.
InsertChannel()
template<typename ElementIDType, typename AttributeType> void TMeshAttributesRef< ElementIDType, AttributeType >::InsertChannel (const int32 Channel) const inline
Inserts an attribute channel.
Definition at line 1002 of file MeshAttributeArray.h.
IsValid()
template<typename ElementIDType, typename AttributeType> bool TMeshAttributesRef< ElementIDType, AttributeType >::IsValid () const inline
Return whether the reference is valid or not.
Definition at line 915 of file MeshAttributeArray.h.
Referenced by Copy(), SetGroomAttribute(), SetHairStrandAttribute(), and SetHairVertexAttribute().
operator[]() [1/2]
template<typename ElementIDType, typename AttributeType> template<typename T = ElementIDType, typename TEnableIf< TIsDerivedFrom< T, FElementID >::Value, int >::Type = 0> AttributeType & TMeshAttributesRef< ElementIDType, AttributeType >::operator[] (const ElementIDType ElementID) const inline
Access elements from attribute channel 0.
Definition at line 876 of file MeshAttributeArray.h.
operator[]() [2/2]
template<typename ElementIDType, typename AttributeType> AttributeType & TMeshAttributesRef< ElementIDType, AttributeType >::operator[] (int32 ElementIndex) const inline
Definition at line 888 of file MeshAttributeArray.h.
RemoveChannel()
template<typename ElementIDType, typename AttributeType> void TMeshAttributesRef< ElementIDType, AttributeType >::RemoveChannel (const int32 Channel) const inline
Removes an attribute channel.
Definition at line 1014 of file MeshAttributeArray.h.
Set() [1/4]
template<typename ElementIDType, typename AttributeType> template<typename T = ElementIDType, typename TEnableIf< TIsDerivedFrom< T, FElementID >::Value, int >::Type = 0> void TMeshAttributesRef< ElementIDType, AttributeType >::Set (const ElementIDType ElementID, const AttributeType & Value) const inline
Set the element with the given ID and index 0 to the provided value.
Definition at line 946 of file MeshAttributeArray.h.
Referenced by TMeshAttributesRef< ElementIDType, TArrayView< AttributeType > >::SetArrayView(), and TMeshAttributesRef< ElementIDType, TArrayView< AttributeType > >::SetArrayView().
Set() [2/4]
template<typename ElementIDType, typename AttributeType> template<typename T = ElementIDType, typename TEnableIf< TIsDerivedFrom< T, FElementID >::Value, int >::Type = 0> void TMeshAttributesRef< ElementIDType, AttributeType >::Set (const ElementIDType ElementID, const int32 Channel, const AttributeType & Value) const inline
Set the element with the given ID and channel to the provided value.
Definition at line 953 of file MeshAttributeArray.h.
Set() [3/4]
template<typename ElementIDType, typename AttributeType> void TMeshAttributesRef< ElementIDType, AttributeType >::Set (int32 ElementIndex, const AttributeType & Value) const inline
Definition at line 958 of file MeshAttributeArray.h.
Set() [4/4]
template<typename ElementIDType, typename AttributeType> void TMeshAttributesRef< ElementIDType, AttributeType >::Set (int32 ElementIndex, const int32 Channel, const AttributeType & Value) const inline
Definition at line 963 of file MeshAttributeArray.h.
SetArrayView() [1/2]
template<typename ElementIDType, typename AttributeType> void TMeshAttributesRef< ElementIDType, AttributeType >::SetArrayView (int32 ElementIndex, const int32 Channel, TArrayView< const AttributeType > Value) const inline
Definition at line 974 of file MeshAttributeArray.h.
SetArrayView() [2/2]
template<typename ElementIDType, typename AttributeType> void TMeshAttributesRef< ElementIDType, AttributeType >::SetArrayView (int32 ElementIndex, TArrayView< const AttributeType > Value) const inline
Definition at line 968 of file MeshAttributeArray.h.
SetNumChannels()
template<typename ElementIDType, typename AttributeType> void TMeshAttributesRef< ElementIDType, AttributeType >::SetNumChannels (const int32 NumChannels) const inline
Sets number of channels this attribute has.
Definition at line 990 of file MeshAttributeArray.h.
UE_DEPRECATED() [1/4]
template<typename ElementIDType, typename AttributeType> TMeshAttributesRef< ElementIDType, AttributeType >::UE_DEPRECATED (5. 0, "Please use GetNumChannels().") const inline
Definition at line 920 of file MeshAttributeArray.h.
UE_DEPRECATED() [2/4]
template<typename ElementIDType, typename AttributeType> TMeshAttributesRef< ElementIDType, AttributeType >::UE_DEPRECATED (5. 0, "Please use InsertChannel().") const inline
Definition at line 995 of file MeshAttributeArray.h.
UE_DEPRECATED() [3/4]
template<typename ElementIDType, typename AttributeType> TMeshAttributesRef< ElementIDType, AttributeType >::UE_DEPRECATED (5. 0, "Please use RemoveChannel().") const inline
Definition at line 1007 of file MeshAttributeArray.h.
UE_DEPRECATED() [4/4]
template<typename ElementIDType, typename AttributeType> TMeshAttributesRef< ElementIDType, AttributeType >::UE_DEPRECATED (5. 0, "Please use SetNumChannels().") const inline
Definition at line 983 of file MeshAttributeArray.h.
Friends And Related Symbol Documentation
TMeshAttributesRef
template<typename ElementIDType, typename AttributeType> template<typename T, typename U> friend class TMeshAttributesRef friend
Definition at line 836 of file MeshAttributeArray.h.
Referenced by Copy().
Field Documentation
ArrayPtr
template<typename ElementIDType, typename AttributeType> BaseArrayType* TMeshAttributesRef< ElementIDType, AttributeType >::ArrayPtr private
Definition at line 1020 of file MeshAttributeArray.h.
Referenced by Copy().
The documentation for this class was generated from the following file:
Runtime/MeshDescription/Public/MeshAttributeArray.h