Unreal Engine 5.6 C++ API: UE::Geometry::TBlockedDenseGrid3< ElemType > Class Template Reference
UE::Geometry::TBlockedDenseGrid3< ElemType > Class Template Reference
TBlockedDenseGrid adds thread-safe access functions to the 3D blocked uniform grid, TBasicBlockedDenseGrid3.
#include "BlockedDenseGrid3.h"
Public Types
typedef TBlockData3< ElemType, BlockSize > BlockData3Type
typedef TBasicBlockedDenseGrid3< ElemType, BlockSize > BlockedDenseGridType
typedef TBlockedGrid3Layout< BlockSize > BlockedGrid3LayoutType
Public Types inherited from UE::Geometry::TBasicBlockedDenseGrid3< ElemType, 32 >
typedef TBlockData3< ElemType, BlockSize_ > BlockData3Type
typedef TBlockedGrid3Layout< BlockSize_ > BlockedGrid3LayoutType
Public Types inherited from UE::Geometry::TBlockedGrid3Layout< BlockSize_ >
typedef TBlockData3Layout< BlockSize_ > FBlockData3Layout
Public Member Functions
TBlockedDenseGrid3 ()
Create empty grid.
TBlockedDenseGrid3 (int32 DimI, int32 DimJ, int32 DimK, ElemType InitialValue)
Create grid with specified domain.
ElemType GetValueThreadSafe (const FVector3i &CellIJK)
ElemType GetValueThreadSafe (int32 I, int32 J, int32 K)
bool IsValidIndex (FVector3i CellIJK) const
template<typename ProcessFunc>
void ProcessValueThreadSafe (const FVector3i &CellIJK, ProcessFunc Func)
Call an external lambda with a reference to the grid value at CellIJK.
template<typename ProcessFunc>
void ProcessValueThreadSafe (int32 I, int32 J, int32 K, ProcessFunc Func)
Call an external lambda with a reference to the grid value at (I,J,K).
void Reset ()
Discard all allocated blocks but retain grid dimensions.
void Reset (int32 DimI, int32 DimJ, int32 DimK, ElemType InitialValue)
Reconfigure the grid to have the target dimensions and default value.
void Resize (int32 DimI, int32 DimJ, int32 DimK)
Reconfigure the grid to have the target dimensions.
void SetValueThreadSafe (const FVector3i &CellIJK, ElemType NewValue)
Set the grid value at CellIJK, with internal locking, so it is safe to call this from multiple read & write threads.
void SetValueThreadSafe (int32 I, int32 J, int32 K, ElemType NewValue)
Set the grid value at (I,J,K), with internal locking, so it is safe to call this from multiple read & write threads.
FVector3i ToIndex (int64 LinearIndex) const
Convert a grid cell id to CellIJK coordinates.
int64 ToLinear (const FVector3i &IJK) const
Convert grid CellIJK coordinates to a linear ID, note this id is independent of the actual internal data storage.
int64 ToLinear (int32 X, int32 Y, int32 Z) const
Convert grid CellIJK coordinates to a linear ID, note this id is independent of the actual internal data storage.
Public Member Functions inherited from UE::Geometry::TBasicBlockedDenseGrid3< ElemType, 32 >
int32 GetNumBlocks () const
ElemType GetValue (int32 I, int32 J, int32 K) const
bool PreAllocateFromSourceGrid (const TBasicBlockedDenseGrid3< OtherElemType, BlockSize > &SourceGrid)
Pre-allocate the grid blocks that also exist in SourceGrid of the same dimensions.
void ProcessValue (int32 I, int32 J, int32 K, ProcessFunc Func)
Call an external lambda with a reference to the grid value at (I,J,K).
void Reset ()
Discard all allocated blocks but retain grid dimensions.
void Resize (int32 DimI, int32 DimJ, int32 DimK)
Reconfigure the grid to have the target dimensions.
void SetValue (int32 I, int32 J, int32 K, ElemType NewValue)
Set the grid value at (I,J,K)
Public Member Functions inherited from UE::Geometry::TBlockedGrid3Layout< BlockSize_ >
TBlockedGrid3Layout ()
TBlockedGrid3Layout (FVector3i Dims)
TBlockedGrid3Layout (int32 DimI, int32 DimJ, int32 DimK)
int32 BlockIJKToBlockIndex (const FVector3i &BlockIJK) const
FVector3i BlockIndexToBlockIJK (const int32 BlockIndex) const
FAxisAlignedBox3i Bounds () const
FAxisAlignedBox3i BoundsInclusive () const
void GetBlockAndLocalIndex (const FVector3i &IJK, int32 &BlockIndexOut, int32 &LocalIndexOut) const
return the block index and local index of the cell at (I,J,K).
void GetBlockAndLocalIndex (int32 I, int32 J, int32 K, int32 &BlockIndexOut, int32 &LocalIndexOut) const
const FVector3i & GetBlockDimensions () const
const FVector3i & GetDimensions () const
int32 IJKtoBlockIndex (const FVector3i &IJK) const
bool IsValidBlockIJK (const FVector3i &BlockIJK)
bool IsValidIJK (const FVector3i &IJK) const
void Resize (int32 DimI, int32 DimJ, int32 DimK)
Recompute the block dimensions required to cover the requested cell dimensions.
int64 Size () const
Static Public Attributes
static constexpr int32 BlockElemCount = BlockSize * BlockSize * BlockSize
static constexpr int32 BlockSize = 32
Static Public Attributes inherited from UE::Geometry::TBasicBlockedDenseGrid3< ElemType, 32 >
static constexpr int32 BlockElemCount
static constexpr int32 BlockSize
Static Public Attributes inherited from UE::Geometry::TBlockedGrid3Layout< BlockSize_ >
static constexpr int32 BlockElemCount = BlockSize * BlockSize * BlockSize
static constexpr int32 BlockSize = BlockSize_
Protected Member Functions
FCriticalSection * GetBlockLock (int32 Index)
ElemType ReadValueThreadSafe (int32 I, int32 J, int32 K)
template<typename FuncType>
void WriteValueThreadSafe (int32 I, int32 J, int32 K, FuncType Func)
Protected Member Functions inherited from UE::Geometry::TBasicBlockedDenseGrid3< ElemType, 32 >
bool AllocateTopologyUnionImpl (const OtherGridType &OtherGrid)
FBlock3 & GetBlock (int32 Index)
bool IsBlockAllocated (const FBlock3 &Block) const
ElemType ReadValue (const int32 &BlockIndex, const int32 &LocalIndex) const
ElemType ReadValueWithLock (const int32 &BlockIndex, const int32 &LocalIndex, FCriticalSection *CriticalSection)
BlockData3Type & TouchBlockData (const int32 BlockIndex)
return a reference to the block data buffer associated with the specified block, allocating if needed
void WriteValue (const int32 &BlockIndex, const int32 &LocalIndex, FuncType Func)
void WriteValueWithLock (const int32 &BlockIndex, const int32 &LocalIndex, FuncType Func, FCriticalSection *CriticalSection)
Protected Attributes
TArray< FCriticalSection > BlockLocks
Protected Attributes inherited from UE::Geometry::TBasicBlockedDenseGrid3< ElemType, 32 >
TArray< FBlock3 > Blocks
ElemType DefaultValue
The value to use to initialize new blocks.
Protected Attributes inherited from UE::Geometry::TBlockedGrid3Layout< BlockSize_ >
FVector3i BlockDimensions
FVector3i Dimensions
Detailed Description
template<typename ElemType>
class UE::Geometry::TBlockedDenseGrid3< ElemType >
TBlockedDenseGrid adds thread-safe access functions to the 3D blocked uniform grid, TBasicBlockedDenseGrid3.
Blocked grid is extended by adding internally owned locks for each data block.
The grid is allocated in BlockSize^3 blocks on-demand (BlockSize is a compile-time constant) allowing very large grids to be used without having to pre-allocate all the memory, eg for sparse/narrow-band use cases.
For multi-threaded applications where memory is a premium, consider using TBlockedGrid3 (above) as it gives better control over the individual blocks and allows the caller to manage the lifetime of any locks used.
Definition at line 731 of file BlockedDenseGrid3.h.
Member Typedef Documentation
BlockData3Type
template<typename ElemType> typedef TBlockData3<ElemType, BlockSize> UE::Geometry::TBlockedDenseGrid3< ElemType >::BlockData3Type
Definition at line 740 of file BlockedDenseGrid3.h.
BlockedDenseGridType
template<typename ElemType> typedef TBasicBlockedDenseGrid3<ElemType, BlockSize> UE::Geometry::TBlockedDenseGrid3< ElemType >::BlockedDenseGridType
Definition at line 738 of file BlockedDenseGrid3.h.
BlockedGrid3LayoutType
template<typename ElemType> typedef TBlockedGrid3Layout<BlockSize> UE::Geometry::TBlockedDenseGrid3< ElemType >::BlockedGrid3LayoutType
Definition at line 739 of file BlockedDenseGrid3.h.
Constructor & Destructor Documentation
TBlockedDenseGrid3() [1/2]
template<typename ElemType> UE::Geometry::TBlockedDenseGrid3< ElemType >::TBlockedDenseGrid3 () inline
Create empty grid.
Definition at line 778 of file BlockedDenseGrid3.h.
TBlockedDenseGrid3() [2/2]
template<typename ElemType> UE::Geometry::TBlockedDenseGrid3< ElemType >::TBlockedDenseGrid3 (int32 DimI, int32 DimJ, int32 DimK, ElemType InitialValue) inline
Create grid with specified domain.
Definition at line 785 of file BlockedDenseGrid3.h.
Member Function Documentation
GetBlockLock()
template<typename ElemType> FCriticalSection * UE::Geometry::TBlockedDenseGrid3< ElemType >::GetBlockLock (int32 Index) inline protected
Definition at line 754 of file BlockedDenseGrid3.h.
Referenced by UE::Geometry::TBlockedDenseGrid3< float >::ReadValueThreadSafe(), and UE::Geometry::TBlockedDenseGrid3< float >::WriteValueThreadSafe().
GetValueThreadSafe() [1/2]
template<typename ElemType> ElemType UE::Geometry::TBlockedDenseGrid3< ElemType >::GetValueThreadSafe (const FVector3i & CellIJK) inline
Returns
the grid value at CellIJK, with internal locking, so it is safe to call this from multiple read & write threads
Definition at line 840 of file BlockedDenseGrid3.h.
GetValueThreadSafe() [2/2]
template<typename ElemType> ElemType UE::Geometry::TBlockedDenseGrid3< ElemType >::GetValueThreadSafe (int32 I, int32 J, int32 K) inline
Returns
the grid value at (I,J,K), with internal locking, so it is safe to call this from multiple read & write threads
Definition at line 832 of file BlockedDenseGrid3.h.
IsValidIndex()
template<typename ElemType> bool UE::Geometry::TBlockedDenseGrid3< ElemType >::IsValidIndex (FVector3i CellIJK) const inline
Returns
true if the specified cell IJK is contained within the grid bounds.
Definition at line 825 of file BlockedDenseGrid3.h.
ProcessValueThreadSafe() [1/2]
template<typename ElemType> template<typename ProcessFunc> void UE::Geometry::TBlockedDenseGrid3< ElemType >::ProcessValueThreadSafe (const FVector3i & CellIJK, ProcessFunc Func) inline
Call an external lambda with a reference to the grid value at CellIJK.
Called as Func(ElemType&), so the caller can both read and write the grid cell
Definition at line 879 of file BlockedDenseGrid3.h.
ProcessValueThreadSafe() [2/2]
template<typename ElemType> template<typename ProcessFunc> void UE::Geometry::TBlockedDenseGrid3< ElemType >::ProcessValueThreadSafe (int32 I, int32 J, int32 K, ProcessFunc Func) inline
Call an external lambda with a reference to the grid value at (I,J,K).
Called as Func(ElemType&), so the caller can both read and write the grid cell
note: if doing pure reads prefer the GetValue() methods because the ProcessValueThreadSafe method will allocate the underlying data block.
Definition at line 869 of file BlockedDenseGrid3.h.
ReadValueThreadSafe()
template<typename ElemType> ElemType UE::Geometry::TBlockedDenseGrid3< ElemType >::ReadValueThreadSafe (int32 I, int32 J, int32 K) inline protected
Definition at line 766 of file BlockedDenseGrid3.h.
Referenced by UE::Geometry::TBlockedDenseGrid3< float >::GetValueThreadSafe(), and UE::Geometry::TBlockedDenseGrid3< float >::GetValueThreadSafe().
Reset() [1/2]
template<typename ElemType> void UE::Geometry::TBlockedDenseGrid3< ElemType >::Reset () inline
Discard all allocated blocks but retain grid dimensions.
Definition at line 807 of file BlockedDenseGrid3.h.
Referenced by UE::Geometry::TBlockedDenseGrid3< float >::Reset().
Reset() [2/2]
template<typename ElemType> void UE::Geometry::TBlockedDenseGrid3< ElemType >::Reset (int32 DimI, int32 DimJ, int32 DimK, ElemType InitialValue) inline
Reconfigure the grid to have the target dimensions and default value.
This clears all the existing grid memory.
Definition at line 816 of file BlockedDenseGrid3.h.
Resize()
template<typename ElemType> void UE::Geometry::TBlockedDenseGrid3< ElemType >::Resize (int32 DimI, int32 DimJ, int32 DimK) inline
Reconfigure the grid to have the target dimensions.
This clears all the existing grid memory and resets the block-level default value.
Definition at line 795 of file BlockedDenseGrid3.h.
Referenced by UE::Geometry::TBlockedDenseGrid3< float >::TBlockedDenseGrid3(), and UE::Geometry::TBlockedDenseGrid3< float >::Reset().
SetValueThreadSafe() [1/2]
template<typename ElemType> void UE::Geometry::TBlockedDenseGrid3< ElemType >::SetValueThreadSafe (const FVector3i & CellIJK, ElemType NewValue) inline
Set the grid value at CellIJK, with internal locking, so it is safe to call this from multiple read & write threads.
Definition at line 856 of file BlockedDenseGrid3.h.
SetValueThreadSafe() [2/2]
template<typename ElemType> void UE::Geometry::TBlockedDenseGrid3< ElemType >::SetValueThreadSafe (int32 I, int32 J, int32 K, ElemType NewValue) inline
Set the grid value at (I,J,K), with internal locking, so it is safe to call this from multiple read & write threads.
Definition at line 848 of file BlockedDenseGrid3.h.
ToIndex()
template<typename ElemType> FVector3i UE::Geometry::TBlockedDenseGrid3< ElemType >::ToIndex (int64 LinearIndex) const inline
Convert a grid cell id to CellIJK coordinates.
Definition at line 885 of file BlockedDenseGrid3.h.
ToLinear() [1/2]
template<typename ElemType> int64 UE::Geometry::TBlockedDenseGrid3< ElemType >::ToLinear (const FVector3i & IJK) const inline
Convert grid CellIJK coordinates to a linear ID, note this id is independent of the actual internal data storage.
Definition at line 898 of file BlockedDenseGrid3.h.
ToLinear() [2/2]
template<typename ElemType> int64 UE::Geometry::TBlockedDenseGrid3< ElemType >::ToLinear (int32 X, int32 Y, int32 Z) const inline
Convert grid CellIJK coordinates to a linear ID, note this id is independent of the actual internal data storage.
Definition at line 893 of file BlockedDenseGrid3.h.
WriteValueThreadSafe()
template<typename ElemType> template<typename FuncType> void UE::Geometry::TBlockedDenseGrid3< ElemType >::WriteValueThreadSafe (int32 I, int32 J, int32 K, FuncType Func) inline protected
Definition at line 758 of file BlockedDenseGrid3.h.
Referenced by UE::Geometry::TBlockedDenseGrid3< float >::ProcessValueThreadSafe(), UE::Geometry::TBlockedDenseGrid3< float >::ProcessValueThreadSafe(), UE::Geometry::TBlockedDenseGrid3< float >::SetValueThreadSafe(), and UE::Geometry::TBlockedDenseGrid3< float >::SetValueThreadSafe().
Field Documentation
BlockElemCount
template<typename ElemType> int32 UE::Geometry::TBlockedDenseGrid3< ElemType >::BlockElemCount = BlockSize * BlockSize * BlockSize static constexpr
Definition at line 736 of file BlockedDenseGrid3.h.
BlockLocks
template<typename ElemType> TArray<FCriticalSection> UE::Geometry::TBlockedDenseGrid3< ElemType >::BlockLocks protected
Definition at line 747 of file BlockedDenseGrid3.h.
BlockSize
template<typename ElemType> int32 UE::Geometry::TBlockedDenseGrid3< ElemType >::BlockSize = 32 static constexpr
Definition at line 735 of file BlockedDenseGrid3.h.
The documentation for this class was generated from the following file:
Runtime/GeometryCore/Public/Spatial/BlockedDenseGrid3.h