Unreal Engine 5.6 C++ API: UAnimNotifyStateMachineInspectionLibrary Class Reference
UAnimNotifyStateMachineInspectionLibrary Class Reference
#include "AnimNotifyStateMachineInspectionLibrary.h"
Private Member Functions
UFUNCTION () static 1 bool IsTriggeredByState(const FAnimNotifyEventReference &EventReference
Get whether a state with the given name in any state machine triggered the notify.
GENERATED_BODY() public UFUNCTION () static 1 bool IsTriggeredByStateInStateMachine(const FAnimNotifyEventReference &EventReference
Get whether the notify was triggered from the specified state machine.
Static Private Member Functions
static bool IsStateInStateMachineInEventContext (const FAnimNotifyEventReference &Reference, int32 StateMachineIndex, int32 StateIndex)
Get whether the Reference ContextData has the given state and machine index in a UAnimNotifyStateMachineContext.
static bool IsStateMachineInEventContext (const FAnimNotifyEventReference &Reference, int32 StateMachineIndex)
Get whether the Reference ContextData has the given machine index in a UAnimNotifyStateMachineContext.
Private Attributes
GENERATED_BODY() public UAnimInstance * AnimInstance
UAnimInstance * AnimInstance
GENERATED_BODY() public UAnimInstance FName StateMachineName
GENERATED_BODY() public UAnimInstance FName FName StateName
UAnimInstance FName StateName
Detailed Description
Definition at line 16 of file AnimNotifyStateMachineInspectionLibrary.h.
Member Function Documentation
IsStateInStateMachineInEventContext()
bool UAnimNotifyStateMachineInspectionLibrary::IsStateInStateMachineInEventContext (const FAnimNotifyEventReference & Reference, int32 StateMachineIndex, int32 StateIndex) static private
Get whether the Reference ContextData has the given state and machine index in a UAnimNotifyStateMachineContext.
Parameters
Reference The event to inspect
StateIndex Index of a state inside a state machine as defined in UAnimInstance
StateMachineIndex The MachineIndex as defined in UAnimInstance
References IsStateInStateMachineInEventContext().
Referenced by IsStateInStateMachineInEventContext().
IsStateMachineInEventContext()
bool UAnimNotifyStateMachineInspectionLibrary::IsStateMachineInEventContext (const FAnimNotifyEventReference & Reference, int32 StateMachineIndex) static private
Get whether the Reference ContextData has the given machine index in a UAnimNotifyStateMachineContext.
This function should not be exposed to blueprint
Parameters
Reference The event to inspect
StateMachineIndex The MachineIndex as defined in UAnimInstance
References IsStateMachineInEventContext().
Referenced by IsStateMachineInEventContext().
UFUNCTION() [1/2]
UAnimNotifyStateMachineInspectionLibrary::UFUNCTION () const & private
Get whether a state with the given name in any state machine triggered the notify.
Parameters
EventReference The event to inspect
MeshComp The skeletal mesh that contains the animation instance that produced the event
StateName The name of a state to test
References Category, and UFUNCTION().
UFUNCTION() [2/2]
GENERATED_BODY() public UAnimNotifyStateMachineInspectionLibrary::UFUNCTION () const & private
Get whether the notify was triggered from the specified state machine.
Parameters
EventReference The event to inspect
MeshComp The skeletal mesh that contains the animation instance that produced the event
StateMachineName The Name of a state machine to test Get whether a particular state in a specific state machine triggered the notify
EventReference The event to inspect
MeshComp The skeletal mesh that contains the animation instance that produced the event
StateMachineName The name of a state machine to test
StateName The name of a state to test
References Category.
Referenced by UFUNCTION().
Field Documentation
AnimInstance [1/2]
GENERATED_BODY() public UAnimInstance* UAnimNotifyStateMachineInspectionLibrary::AnimInstance private
Definition at line 37 of file AnimNotifyStateMachineInspectionLibrary.h.
AnimInstance [2/2]
UAnimInstance* UAnimNotifyStateMachineInspectionLibrary::AnimInstance private
Definition at line 46 of file AnimNotifyStateMachineInspectionLibrary.h.
StateMachineName
GENERATED_BODY() public UAnimInstance FName UAnimNotifyStateMachineInspectionLibrary::StateMachineName private
Definition at line 37 of file AnimNotifyStateMachineInspectionLibrary.h.
StateName [1/2]
GENERATED_BODY() public UAnimInstance FName FName UAnimNotifyStateMachineInspectionLibrary::StateName private
Definition at line 37 of file AnimNotifyStateMachineInspectionLibrary.h.
StateName [2/2]
UAnimInstance FName UAnimNotifyStateMachineInspectionLibrary::StateName private
Definition at line 46 of file AnimNotifyStateMachineInspectionLibrary.h.
The documentation for this class was generated from the following file:
Runtime/Engine/Public/Animation/AnimNotifyStateMachineInspectionLibrary.h