Unreal Engine 5.6 C++ API: TSkeletalMeshVertexData< VertexDataType > Class Template Reference
TSkeletalMeshVertexData< VertexDataType > Class Template Reference
The implementation of the skeletal mesh vertex data storage type.
#include "SkeletalMeshVertexBuffer.h"
Public Types
typedef TResourceArray< VertexDataType, VERTEXBUFFER_ALIGNMENT > ArrayType
Public Types inherited from TResourceArray< VertexDataType, VERTEXBUFFER_ALIGNMENT >
using Super
Public Types inherited from TArray< InElementType, InAllocatorType >
using AllocatorType = InAllocatorType
using ElementAllocatorType
using ElementType = InElementType
using IntrusiveUnsetOptionalStateType = TArray
using RangedForConstIteratorType = TCheckedPointerIterator<const ElementType, SizeType, false>
using RangedForConstReverseIteratorType = TCheckedPointerIterator<const ElementType, SizeType, true>
using RangedForIteratorType = TCheckedPointerIterator< ElementType, SizeType, false>
using RangedForReverseIteratorType = TCheckedPointerIterator< ElementType, SizeType, true>
using SizeType = typename InAllocatorType::SizeType
using TConstIterator = TIndexedContainerIterator<const TArray, const ElementType, SizeType>
using TIterator = TIndexedContainerIterator< TArray, ElementType, SizeType>
Public Member Functions
TSkeletalMeshVertexData (bool InNeedsCPUAccess=false)
Constructor.
virtual uint8 * GetDataPointer ()
virtual uint32 GetNumVertices ()
virtual FResourceArrayInterface * GetResourceArray ()
virtual uint32 GetStride () const
TSkeletalMeshVertexData< VertexDataType > & operator= (const TArray< VertexDataType > &Other)
Assignment operator.
virtual void ResizeBuffer (uint32 NumVertices)
Resizes the vertex data buffer, discarding any data which no longer fits.
virtual void Serialize (FArchive &Ar)
Serializer for this class.
Public Member Functions inherited from FSkeletalMeshVertexDataInterface
virtual ~FSkeletalMeshVertexDataInterface ()
Virtual destructor.
Public Member Functions inherited from TResourceArray< VertexDataType, VERTEXBUFFER_ALIGNMENT >
TResourceArray (bool InNeedsCPUAccess=false)
Constructor.
TResourceArray (const TResourceArray &)=default
TResourceArray (TResourceArray &&)=default
virtual ~TResourceArray ()=default
void BulkSerialize (FArchive &Ar, bool bForcePerElementSerialization=false)
Serialize data as a single block.
virtual void Discard () override
Called on non-UMA systems after the RHI has copied the resource data, and no longer needs the CPU's copy.
virtual bool GetAllowCPUAccess () const override
virtual const void * GetResourceData () const override
virtual uint32 GetResourceDataSize () const override
virtual bool IsStatic () const override
TResourceArray & operator= (const Super &Other)
TResourceArray & operator= (const TResourceArray &)=default
TResourceArray & operator= (TResourceArray &&)=default
virtual void SetAllowCPUAccess (bool bInNeedsCPUAccess) override
Sets whether the resource array will be accessed by CPU.
Public Member Functions inherited from FResourceArrayUploadInterface
virtual ~FResourceArrayUploadInterface ()
template<typename TElement>
TConstArrayView< TElement > GetResourceDataView () const
Public Member Functions inherited from TArray< InElementType, InAllocatorType >
FORCEINLINE TArray ()
Constructor, initializes element number counters.
FORCEINLINE TArray (const ElementType *Ptr, SizeType Count)
Constructor from a raw array of elements.
FORCEINLINE TArray (const TArray &Other)
Copy constructor.
FORCEINLINE TArray (const TArray &Other, SizeType ExtraSlack)
Copy constructor.
template<typename OtherElementType, typename OtherAllocator UE_REQUIRES>
FORCEINLINE TArray (const TArray< OtherElementType, OtherAllocator > &Other)
Copy constructor with changed allocator.
template<typename OtherElementType, typename OtherSizeType>
TArray (const TArrayView< OtherElementType, OtherSizeType > &Other)
template<typename OtherElementType, typename OtherSizeType>
FORCEINLINE TArray (const TArrayView< OtherElementType, OtherSizeType > &Other)
UE_NODEBUG TArray (FIntrusiveUnsetOptionalState Tag)
TArray (std::initializer_list< InElementType > InitList)
Initializer list constructor.
FORCEINLINE TArray (TArray &&Other)
Move constructor.
template<typename OtherElementType UE_REQUIRES>
TArray (TArray< OtherElementType, AllocatorType > &&Other, SizeType ExtraSlack)
Move constructor.
template<typename OtherElementType, typename OtherAllocator UE_REQUIRES>
FORCEINLINE TArray (TArray< OtherElementType, OtherAllocator > &&Other)
Move constructor.
~TArray ()
Destructor.
UE_NODEBUG FORCEINLINE SizeType Add (const ElementType &Item)
Adds a new item to the end of the array, possibly reallocating the whole array to fit.
UE_NODEBUG FORCEINLINE SizeType Add (ElementType &&Item)
Adds a new item to the end of the array, possibly reallocating the whole array to fit.
UE_NODEBUG FORCEINLINE ElementType & Add_GetRef (const ElementType &Item) UE_LIFETIMEBOUND
Adds a new item to the end of the array, possibly reallocating the whole array to fit.
UE_NODEBUG FORCEINLINE ElementType & Add_GetRef (ElementType &&Item) UE_LIFETIMEBOUND
Adds a new item to the end of the array, possibly reallocating the whole array to fit.
SizeType AddDefaulted ()
Adds new items to the end of the array, possibly reallocating the whole array to fit.
SizeType AddDefaulted (SizeType Count)
ElementType & AddDefaulted_GetRef () UE_LIFETIMEBOUND
Add a new item to the end of the array, possibly reallocating the whole array to fit.
FORCEINLINE SizeType AddUninitialized ()
Adds a given number of uninitialized elements into the array.
FORCEINLINE SizeType AddUninitialized (SizeType Count)
FORCEINLINE SizeType AddUnique (const ElementType &Item)
Adds unique element to array if it doesn't exist.
FORCEINLINE SizeType AddUnique (ElementType &&Item)
Adds unique element to array if it doesn't exist.
SizeType AddZeroed ()
Adds new items to the end of the array, possibly reallocating the whole array to fit.
SizeType AddZeroed (SizeType Count)
ElementType & AddZeroed_GetRef () UE_LIFETIMEBOUND
Adds a new item to the end of the array, possibly reallocating the whole array to fit.
void Append (const ElementType *Ptr, SizeType Count)
Adds a raw array of elements to the end of the TArray.
template<typename OtherElementType, typename OtherAllocatorType>
void Append (const TArray< OtherElementType, OtherAllocatorType > &Source)
Appends the specified array to this array.
template<typename AliasElementType = ElementType UE_REQUIRES(TIsContainerElementTypeCopyable_V<AliasElementType>)>
void Append (const typename TContainerElementTypeCompatibility< ElementType >::CopyFromOtherType *Ptr, SizeType Count)
Adds a raw array of elements to the end of the TArray.
template<typename RangeType UE_REQUIRES>
void Append (RangeType &&Source)
Appends the elements from a contiguous range to this array.
FORCEINLINE void Append (std::initializer_list< ElementType > InitList)
Adds an initializer list of elements to the end of the TArray.
template<typename OtherElementType, typename OtherAllocator>
void Append (TArray< OtherElementType, OtherAllocator > &&Source)
Appends the specified array to this array.
UE_NODEBUG FORCEINLINE RangedForIteratorType begin ()
DO NOT USE DIRECTLY STL-like iterators to enable range-based for loop support.
UE_NODEBUG FORCEINLINE RangedForConstIteratorType begin () const
void BulkSerialize (FArchive &Ar, bool bForcePerElementSerialization=false)
Bulk serialize array as a single memory blob when loading.
FORCEINLINE void CheckAddress (const ElementType *Addr) const
Checks that the specified address is not part of an element within the container.
UE_NODEBUG FORCEINLINE void CheckInvariants () const
Checks array invariants: if array size is greater than or equal to zero and less than or equal to the maximum.
template<typename ComparisonType>
bool Contains (const ComparisonType &Item) const
Checks if this array contains the element.
template<typename Predicate>
UE_NODEBUG FORCEINLINE bool ContainsByPredicate (Predicate Pred) const
Checks if this array contains an element for which the predicate is true.
void CopyUnfrozen (const FMemoryUnfreezeContent &Context, void *Dst) const
UE_NODEBUG void CountBytes (FArchive &Ar) const
Count bytes needed to serialize this array.
UE_NODEBUG TConstIterator CreateConstIterator () const
Creates a const iterator for the contents of this array.
UE_NODEBUG TIterator CreateIterator ()
Creates an iterator for the contents of this array.
template<typename... ArgsType>
FORCEINLINE SizeType Emplace (ArgsType &&... Args)
Constructs a new item at the end of the array, possibly reallocating the whole array to fit.
template<typename... ArgsType>
FORCEINLINE ElementType & Emplace_GetRef (ArgsType &&... Args) UE_LIFETIMEBOUND
Constructs a new item at the end of the array, possibly reallocating the whole array to fit.
template<typename... ArgsType>
FORCEINLINE void EmplaceAt (SizeType Index, ArgsType &&... Args)
Constructs a new item at a specified index, possibly reallocating the whole array to fit.
template<typename... ArgsType>
FORCEINLINE ElementType & EmplaceAt_GetRef (SizeType Index, ArgsType &&... Args) UE_LIFETIMEBOUND
Constructs a new item at a specified index, possibly reallocating the whole array to fit.
void Empty (SizeType Slack=0)
Empties the array.
UE_NODEBUG FORCEINLINE RangedForIteratorType end ()
UE_NODEBUG FORCEINLINE RangedForConstIteratorType end () const
template<typename Predicate>
TArray< ElementType > FilterByPredicate (Predicate Pred) const
Filters the elements in the array based on a predicate functor.
SizeType Find (const ElementType &Item) const
Finds element within the array.
UE_NODEBUG FORCEINLINE bool Find (const ElementType &Item, SizeType &Index) const
Finds element within the array.
template<typename KeyType>
ElementType * FindByKey (const KeyType &Key)
Finds an item by key (assuming the ElementType overloads operator== for the comparison).
template<typename KeyType>
UE_NODEBUG FORCEINLINE const ElementType * FindByKey (const KeyType &Key) const
Finds an item by key (assuming the ElementType overloads operator== for the comparison).
template<typename Predicate>
ElementType * FindByPredicate (Predicate Pred)
Finds an element which matches a predicate functor.
template<typename Predicate>
UE_NODEBUG FORCEINLINE const ElementType * FindByPredicate (Predicate Pred) const
Finds an element which matches a predicate functor.
template<typename SearchType>
bool FindItemByClass (SearchType **Item=nullptr, SizeType *ItemIndex=nullptr, SizeType StartIndex=0) const
Searches for the first entry of the specified type, will only work with TArray<UObject*>.
SizeType FindLast (const ElementType &Item) const
Finds element within the array starting from the end.
UE_NODEBUG FORCEINLINE bool FindLast (const ElementType &Item, SizeType &Index) const
Finds element within the array starting from the end.
template<typename Predicate>
UE_NODEBUG FORCEINLINE SizeType FindLastByPredicate (Predicate Pred) const
Searches the array for the last occurrence of an element which matches the specified predicate.
template<typename Predicate>
SizeType FindLastByPredicate (Predicate Pred, SizeType Count) const
Searches an initial subrange of the array for the last occurrence of an element which matches the specified predicate.
UE_NODEBUG FORCEINLINE SIZE_T GetAllocatedSize (void) const
Helper function to return the amount of memory allocated by this container.
UE_NODEBUG ElementAllocatorType & GetAllocatorInstance ()
UE_NODEBUG const ElementAllocatorType & GetAllocatorInstance () const
UE_NODEBUG FORCEINLINE const ElementType * GetData () const UE_LIFETIMEBOUND
Helper function for returning a typed pointer to the first array entry.
UE_NODEBUG FORCEINLINE ElementType * GetData () UE_LIFETIMEBOUND
Helper function for returning a typed pointer to the first array entry.
UE_NODEBUG FORCEINLINE SizeType GetSlack () const
Returns the amount of slack in this array in elements.
UE_NODEBUG void Heapify ()
Builds an implicit heap from the array.
template<class PREDICATE_CLASS>
UE_NODEBUG FORCEINLINE void Heapify (const PREDICATE_CLASS &Predicate)
Implicit heaps.
template<class PREDICATE_CLASS>
void HeapPop (ElementType &OutItem, const PREDICATE_CLASS &Predicate, EAllowShrinking AllowShrinking=EAllowShrinking::Default)
Removes the top element from the heap.
UE_NODEBUG void HeapPop (ElementType &OutItem, EAllowShrinking AllowShrinking=EAllowShrinking::Default)
Removes the top element from the heap.
template<class PREDICATE_CLASS>
void HeapPopDiscard (const PREDICATE_CLASS &Predicate, EAllowShrinking AllowShrinking=EAllowShrinking::Default)
Removes the top element from the heap.
UE_NODEBUG void HeapPopDiscard (EAllowShrinking AllowShrinking=EAllowShrinking::Default)
Removes the top element from the heap.
UE_NODEBUG SizeType HeapPush (const ElementType &InItem)
Adds a new element to the heap.
template<class PREDICATE_CLASS>
SizeType HeapPush (const ElementType &InItem, const PREDICATE_CLASS &Predicate)
Adds a new element to the heap.
UE_NODEBUG SizeType HeapPush (ElementType &&InItem)
Adds a new element to the heap.
template<class PREDICATE_CLASS>
SizeType HeapPush (ElementType &&InItem, const PREDICATE_CLASS &Predicate)
Adds a new element to the heap.
template<class PREDICATE_CLASS>
void HeapRemoveAt (SizeType Index, const PREDICATE_CLASS &Predicate, EAllowShrinking AllowShrinking=EAllowShrinking::Default)
Removes an element from the heap.
UE_NODEBUG void HeapRemoveAt (SizeType Index, EAllowShrinking AllowShrinking=EAllowShrinking::Default)
Removes an element from the heap.
UE_NODEBUG void HeapSort ()
Performs heap sort on the array.
template<class PREDICATE_CLASS>
UE_NODEBUG void HeapSort (const PREDICATE_CLASS &Predicate)
Performs heap sort on the array.
UE_NODEBUG const ElementType & HeapTop () const UE_LIFETIMEBOUND
Returns the top element from the heap (does not remove the element).
UE_NODEBUG ElementType & HeapTop () UE_LIFETIMEBOUND
Returns the top element from the heap (does not remove the element).
template<typename KeyType>
SizeType IndexOfByKey (const KeyType &Key) const
Finds an item by key (assuming the ElementType overloads operator== for the comparison).
template<typename Predicate>
SizeType IndexOfByPredicate (Predicate Pred) const
Finds an item by predicate.
void Init (const ElementType &Element, SizeType Number)
Sets the size of the array, filling it with the given element.
SizeType Insert (const ElementType &Item, SizeType Index)
Inserts a given element into the array at given location.
SizeType Insert (const ElementType *Ptr, SizeType Count, SizeType Index)
Inserts a raw array of elements at a particular index in the TArray.
template<typename OtherAllocator>
SizeType Insert (const TArray< ElementType, OtherAllocator > &Items, const SizeType InIndex)
Inserts given elements into the array at given location.
template<typename OtherAllocator, typename AliasElementType = ElementType UE_REQUIRES(TIsContainerElementTypeCopyable_V<AliasElementType>)>
SizeType Insert (const TArray< typename TContainerElementTypeCompatibility< ElementType >::CopyFromOtherType, OtherAllocator > &Items, const SizeType InIndex)
Inserts given elements into the array at given location.
SizeType Insert (ElementType &&Item, SizeType Index)
Inserts a given element into the array at given location.
SizeType Insert (std::initializer_list< ElementType > InitList, const SizeType InIndex)
Inserts given elements into the array at given location.
template<typename OtherAllocator>
SizeType Insert (TArray< ElementType, OtherAllocator > &&Items, const SizeType InIndex)
Inserts given elements into the array at given location.
template<typename OtherAllocator, typename AliasElementType = ElementType UE_REQUIRES(TIsContainerElementTypeCopyable_V<AliasElementType>)>
SizeType Insert (TArray< typename TContainerElementTypeCompatibility< ElementType >::CopyFromOtherType, OtherAllocator > &&Items, const SizeType InIndex)
Inserts given elements into the array at given location.
ElementType & Insert_GetRef (const ElementType &Item, SizeType Index) UE_LIFETIMEBOUND
Inserts a given element into the array at given location.
ElementType & Insert_GetRef (ElementType &&Item, SizeType Index) UE_LIFETIMEBOUND
Inserts a given element into the array at given location.
void InsertDefaulted (SizeType Index)
Inserts a given number of default-constructed elements into the array at a given location.
void InsertDefaulted (SizeType Index, SizeType Count)
ElementType & InsertDefaulted_GetRef (SizeType Index) UE_LIFETIMEBOUND
Inserts a default-constructed element into the array at a given location.
UE_NODEBUG FORCEINLINE void InsertUninitialized (SizeType Index)
Inserts a given number of uninitialized elements into the array at given location.
UE_NODEBUG FORCEINLINE void InsertUninitialized (SizeType Index, SizeType Count)
void InsertZeroed (SizeType Index)
Inserts a given number of zeroed elements into the array at given location.
void InsertZeroed (SizeType Index, SizeType Count)
ElementType & InsertZeroed_GetRef (SizeType Index) UE_LIFETIMEBOUND
Inserts a zeroed element into the array at given location.
bool IsEmpty () const
Returns true if the array is empty and contains no elements.
UE_NODEBUG FORCEINLINE bool IsValidIndex (SizeType Index) const
Tests if index is valid, i.e.
UE_NODEBUG FORCEINLINE const ElementType & Last (SizeType IndexFromTheEnd=0) const UE_LIFETIMEBOUND
Returns n-th last element from the array.
UE_NODEBUG FORCEINLINE ElementType & Last (SizeType IndexFromTheEnd=0) UE_LIFETIMEBOUND
Returns n-th last element from the array.
UE_NODEBUG FORCEINLINE SizeType Max () const
Returns maximum number of elements in array.
UE_NODEBUG FORCEINLINE SizeType Num () const
Returns number of elements in array.
UE_NODEBUG FORCEINLINE SIZE_T NumBytes () const
template<typename AliasElementType = ElementType UE_REQUIRES(TIsContainerElementTypeReinterpretable_V<AliasElementType>)>
operator const TArray< typename TContainerElementTypeCompatibility< AliasElementType >::ReinterpretType, AllocatorType > & () const
Immutable implicit conversion operator to constant container of compatible element type.
template<typename AliasElementType = ElementType UE_REQUIRES(TIsContainerElementTypeReinterpretable_V<AliasElementType>)>
operator TArray< typename TContainerElementTypeCompatibility< AliasElementType >::ReinterpretType, AllocatorType > & ()
Mutable implicit conversion operator to container of compatible element type.
UE_NODEBUG FORCEINLINE bool operator!= (const TArray &OtherArray) const
Inequality operator.
UE_NODEBUG TArray & operator+= (const TArray &Other)
Appends the specified array to this array.
UE_NODEBUG TArray & operator+= (std::initializer_list< ElementType > InitList)
Appends the specified initializer list to this array.
UE_NODEBUG TArray & operator+= (TArray &&Other)
Appends the specified array to this array.
TArray & operator= (const TArray &Other)
Assignment operator.
template<typename OtherAllocatorType>
TArray & operator= (const TArray< ElementType, OtherAllocatorType > &Other)
Assignment operator.
template<typename OtherAllocator, typename AliasElementType = ElementType UE_REQUIRES(TIsContainerElementTypeCopyable_V<AliasElementType>)>
TArray & operator= (const TArray< typename TContainerElementTypeCompatibility< ElementType >::CopyFromOtherType, OtherAllocator > &Other)
Assignment operator.
template<typename OtherElementType, typename OtherSizeType>
TArray & operator= (const TArrayView< OtherElementType, OtherSizeType > &Other)
template<typename OtherElementType, typename OtherSizeType>
FORCEINLINE TArray< InElementType, InAllocatorType > & operator= (const TArrayView< OtherElementType, OtherSizeType > &Other)
TArray & operator= (std::initializer_list< InElementType > InitList)
Initializer list assignment operator.
TArray & operator= (TArray &&Other)
Move assignment operator.
template<typename AliasElementType = ElementType UE_REQUIRES(TIsContainerElementTypeCopyable_V<AliasElementType>)>
TArray & operator= (TArray< typename TContainerElementTypeCompatibility< ElementType >::CopyFromOtherType, AllocatorType > &&Other)
Move assignment operator.
UE_NODEBUG bool operator== (const TArray &OtherArray) const
Equality operator.
UE_NODEBUG bool operator== (FIntrusiveUnsetOptionalState Tag) const
UE_NODEBUG FORCEINLINE const ElementType & operator[] (SizeType Index) const UE_LIFETIMEBOUND
Array bracket operator.
UE_NODEBUG FORCEINLINE ElementType & operator[] (SizeType Index) UE_LIFETIMEBOUND
Array bracket operator.
ElementType Pop (EAllowShrinking AllowShrinking=EAllowShrinking::Default)
Pops element from the array.
UE_NODEBUG FORCEINLINE void Push (const ElementType &Item)
Pushes element into the array.
UE_NODEBUG FORCEINLINE void Push (ElementType &&Item)
Pushes element into the array.
FORCEINLINE void RangeCheck (SizeType Index) const
Checks if index is in array range.
FORCEINLINE void RangeCheck (SizeType Index, SizeType Count) const
Checks if a range of indices are in the array range.
UE_NODEBUG FORCEINLINE RangedForReverseIteratorType rbegin ()
UE_NODEBUG FORCEINLINE RangedForConstReverseIteratorType rbegin () const
SizeType Remove (const ElementType &Item)
Removes as many instances of Item as there are in the array, maintaining order but not indices.
template<class PREDICATE_CLASS>
SizeType RemoveAll (const PREDICATE_CLASS &Predicate)
Remove all instances that match the predicate, maintaining order but not indices Optimized to work with runs of matches/non-matches.
template<class PREDICATE_CLASS>
SizeType RemoveAllSwap (const PREDICATE_CLASS &Predicate, EAllowShrinking AllowShrinking=EAllowShrinking::Default)
Remove all instances that match the predicate.
template<typename CountType UE_REQUIRES>
FORCEINLINE void RemoveAt (SizeType Index, CountType Count, EAllowShrinking AllowShrinking=EAllowShrinking::Default)
Removes an element (or elements) at given location, optionally shrinking the array.
void RemoveAt (SizeType Index, EAllowShrinking AllowShrinking=EAllowShrinking::Default)
Removes an element (or elements) at given location, then shrinks the array.
template<typename CountType UE_REQUIRES>
FORCEINLINE void RemoveAtSwap (SizeType Index, CountType Count, EAllowShrinking AllowShrinking=EAllowShrinking::Default)
Removes an element (or elements) at given location, optionally shrinking the array.
FORCEINLINE void RemoveAtSwap (SizeType Index, EAllowShrinking AllowShrinking=EAllowShrinking::Default)
Removes an element (or elements) at given location, then shrinks the array.
SizeType RemoveSingle (const ElementType &Item)
Removes the first occurrence of the specified item in the array, maintaining order but not indices.
SizeType RemoveSingleSwap (const ElementType &Item, EAllowShrinking AllowShrinking=EAllowShrinking::Default)
Removes the first occurrence of the specified item in the array.
SizeType RemoveSwap (const ElementType &Item, EAllowShrinking AllowShrinking=EAllowShrinking::Default)
Removes all instances of a given item from the array.
UE_NODEBUG FORCEINLINE RangedForReverseIteratorType rend ()
UE_NODEBUG FORCEINLINE RangedForConstReverseIteratorType rend () const
FORCEINLINE void Reserve (SizeType Number)
Reserves memory such that the array can contain at least Number elements.
void Reset (SizeType NewSize=0)
Same as empty, but doesn't change memory allocations, unless the new size is larger than the current array.
void SetNum (SizeType NewNum, EAllowShrinking AllowShrinking=EAllowShrinking::Default)
Resizes array to given number of elements.
void SetNumUninitialized (SizeType NewNum, EAllowShrinking AllowShrinking=EAllowShrinking::Default)
Resizes array to given number of elements.
void SetNumUnsafeInternal (SizeType NewNum)
Does nothing except setting the new number of elements in the array.
void SetNumZeroed (SizeType NewNum, EAllowShrinking AllowShrinking=EAllowShrinking::Default)
Resizes array to given number of elements, optionally shrinking it.
FORCEINLINE void Shrink ()
Shrinks the array's used memory to smallest possible to store elements currently in it.
UE_NODEBUG void Sort ()
Sorts the array assuming < operator is defined for the item type.
template<class PREDICATE_CLASS>
UE_NODEBUG void Sort (const PREDICATE_CLASS &Predicate)
Sorts the array using user define predicate class.
UE_NODEBUG void StableSort ()
Stable sorts the array assuming < operator is defined for the item type.
template<class PREDICATE_CLASS>
UE_NODEBUG void StableSort (const PREDICATE_CLASS &Predicate)
Stable sorts the array using user defined predicate class.
FORCEINLINE void Swap (SizeType FirstIndexToSwap, SizeType SecondIndexToSwap)
Element-wise array element swap.
FORCEINLINE void SwapMemory (SizeType FirstIndexToSwap, SizeType SecondIndexToSwap)
Element-wise array memory swap.
UE_NODEBUG FORCEINLINE const ElementType & Top () const UE_LIFETIMEBOUND
Returns the top element, i.e.
UE_NODEBUG FORCEINLINE ElementType & Top () UE_LIFETIMEBOUND
Returns the top element, i.e.
void ToString (const FPlatformTypeLayoutParameters &LayoutParams, FMemoryToStringContext &OutContext) const
template<class PREDICATE_CLASS>
UE_ALLOWSHRINKING_BOOL_DEPRECATED ("HeapPop") UE_NODEBUG FORCEINLINE void HeapPop(ElementType &OutItem
UE_ALLOWSHRINKING_BOOL_DEPRECATED ("HeapPop") UE_NODEBUG FORCEINLINE void HeapPop(ElementType &OutItem
UE_ALLOWSHRINKING_BOOL_DEPRECATED ("HeapPopDiscard") UE_NODEBUG FORCEINLINE void HeapPopDiscard(bool bAllowShrinking)
template<class PREDICATE_CLASS>
UE_ALLOWSHRINKING_BOOL_DEPRECATED ("HeapPopDiscard") UE_NODEBUG FORCEINLINE void HeapPopDiscard(const PREDICATE_CLASS &Predicate
UE_ALLOWSHRINKING_BOOL_DEPRECATED ("HeapRemoveAt") UE_NODEBUG FORCEINLINE void HeapRemoveAt(SizeType Index
template<class PREDICATE_CLASS>
UE_ALLOWSHRINKING_BOOL_DEPRECATED ("HeapRemoveAt") UE_NODEBUG void HeapRemoveAt(SizeType Index
UE_ALLOWSHRINKING_BOOL_DEPRECATED ("Pop") UE_NODEBUG FORCEINLINE ElementType Pop(bool bAllowShrinking)
template<class PREDICATE_CLASS>
UE_ALLOWSHRINKING_BOOL_DEPRECATED ("RemoveAllSwap") UE_NODEBUG FORCEINLINE SizeType RemoveAllSwap(const PREDICATE_CLASS &Predicate
template<typename CountType>
UE_ALLOWSHRINKING_BOOL_DEPRECATED ("RemoveAt") FORCEINLINE void RemoveAt(SizeType Index
template<typename CountType>
UE_ALLOWSHRINKING_BOOL_DEPRECATED ("RemoveAtSwap") UE_NODEBUG FORCEINLINE void RemoveAtSwap(SizeType Index
UE_ALLOWSHRINKING_BOOL_DEPRECATED ("RemoveSingleSwap") UE_NODEBUG FORCEINLINE SizeType RemoveSingleSwap(const ElementType &Item
UE_ALLOWSHRINKING_BOOL_DEPRECATED ("RemoveSwap") UE_NODEBUG FORCEINLINE SizeType RemoveSwap(const ElementType &Item
UE_ALLOWSHRINKING_BOOL_DEPRECATED ("SetNum") UE_NODEBUG FORCEINLINE void SetNum(SizeType NewNum
UE_ALLOWSHRINKING_BOOL_DEPRECATED ("SetNumUninitialized") UE_NODEBUG FORCEINLINE void SetNumUninitialized(SizeType NewNum
UE_ALLOWSHRINKING_BOOL_DEPRECATED ("SetNumZeroed") UE_NODEBUG FORCEINLINE void SetNumZeroed(SizeType NewNum
template<class PREDICATE_CLASS>
UE_NODEBUG void VerifyHeap (const PREDICATE_CLASS &Predicate)
Verifies the heap.
void WriteMemoryImage (FMemoryImageWriter &Writer) const
Additional Inherited Members
Static Public Member Functions inherited from TArray< InElementType, InAllocatorType >
static void AppendHash (const FPlatformTypeLayoutParameters &LayoutParams, FSHA1 &Hasher)
UE_NODEBUG static FORCEINLINE constexpr uint32 GetTypeSize ()
Helper function returning the size of the inner type.
Data Fields inherited from TArray< InElementType, InAllocatorType >
CountType bool bAllowShrinking
bool bAllowShrinking
const PREDICATE_CLASS bool bAllowShrinking
CountType Count
const PREDICATE_CLASS & Predicate
Static Public Attributes inherited from TArray< InElementType, InAllocatorType >
static constexpr bool bHasIntrusiveUnsetOptionalState = true
Protected Attributes inherited from TArray< InElementType, InAllocatorType >
ElementAllocatorType AllocatorInstance
SizeType ArrayMax
SizeType ArrayNum
Detailed Description
template<typename VertexDataType>
class TSkeletalMeshVertexData< VertexDataType >
The implementation of the skeletal mesh vertex data storage type.
Definition at line 137 of file SkeletalMeshVertexBuffer.h.
Member Typedef Documentation
ArrayType
template<typename VertexDataType> typedef TResourceArray<VertexDataType, VERTEXBUFFER_ALIGNMENT> TSkeletalMeshVertexData< VertexDataType >::ArrayType
Definition at line 142 of file SkeletalMeshVertexBuffer.h.
Constructor & Destructor Documentation
TSkeletalMeshVertexData()
template<typename VertexDataType> TSkeletalMeshVertexData< VertexDataType >::TSkeletalMeshVertexData (bool InNeedsCPUAccess = false) inline
Constructor.
Parameters
InNeedsCPUAccess - true if resource array data should be CPU accessible
Definition at line 148 of file SkeletalMeshVertexBuffer.h.
References TResourceArray< VertexDataType, VERTEXBUFFER_ALIGNMENT >::TResourceArray(), and VERTEXBUFFER_ALIGNMENT.
Referenced by operator=().
Member Function Documentation
GetDataPointer()
template<typename VertexDataType> virtual uint8 * TSkeletalMeshVertexData< VertexDataType >::GetDataPointer () inline virtual
Returns
uint8 pointer to the resource data array
Implements FSkeletalMeshVertexDataInterface.
Definition at line 182 of file SkeletalMeshVertexBuffer.h.
GetNumVertices()
template<typename VertexDataType> virtual uint32 TSkeletalMeshVertexData< VertexDataType >::GetNumVertices () inline virtual
Returns
number of vertices stored in the resource data array
Implements FSkeletalMeshVertexDataInterface.
Definition at line 189 of file SkeletalMeshVertexBuffer.h.
References TArray< InElementType, InAllocatorType >::Num().
GetResourceArray()
template<typename VertexDataType> virtual FResourceArrayInterface * TSkeletalMeshVertexData< VertexDataType >::GetResourceArray () inline virtual
Returns
resource array interface access
Implements FSkeletalMeshVertexDataInterface.
Definition at line 196 of file SkeletalMeshVertexBuffer.h.
GetStride()
template<typename VertexDataType> virtual uint32 TSkeletalMeshVertexData< VertexDataType >::GetStride () const inline virtual
Returns
stride of the vertex type stored in the resource data array
Implements FSkeletalMeshVertexDataInterface.
Definition at line 175 of file SkeletalMeshVertexBuffer.h.
operator=()
template<typename VertexDataType> TSkeletalMeshVertexData< VertexDataType > & TSkeletalMeshVertexData< VertexDataType >::operator= (const TArray< VertexDataType > & Other) inline
Assignment operator.
This is currently the only method which allows for modifying an existing resource array
Definition at line 214 of file SkeletalMeshVertexBuffer.h.
References TArray< InElementType, InAllocatorType >::TArray, TSkeletalMeshVertexData(), TResourceArray< VertexDataType, VERTEXBUFFER_ALIGNMENT >::operator=(), and Other.
ResizeBuffer()
template<typename VertexDataType> virtual void TSkeletalMeshVertexData< VertexDataType >::ResizeBuffer (uint32 NumVertices) inline virtual
Resizes the vertex data buffer, discarding any data which no longer fits.
Parameters
NumVertices - The number of vertices to allocate the buffer for.
Implements FSkeletalMeshVertexDataInterface.
Definition at line 158 of file SkeletalMeshVertexBuffer.h.
References TArray< InElementType, InAllocatorType >::AddUninitialized(), TArray< InElementType, InAllocatorType >::Num(), TArray< InElementType, InAllocatorType >::RemoveAt(), and TArray< InElementType, InAllocatorType >::Reserve().
Serialize()
template<typename VertexDataType> virtual void TSkeletalMeshVertexData< VertexDataType >::Serialize (FArchive & Ar) inline virtual
Serializer for this class.
Parameters
Ar - archive to serialize to
B - data to serialize
Implements FSkeletalMeshVertexDataInterface.
Definition at line 206 of file SkeletalMeshVertexBuffer.h.
References Ar, and TResourceArray< VertexDataType, VERTEXBUFFER_ALIGNMENT >::BulkSerialize().
The documentation for this class was generated from the following file:
Runtime/Engine/Public/Rendering/SkeletalMeshVertexBuffer.h