Unreal Engine 5.6 C++ API: AVRTool Class Reference
AVRTool Class Reference
#include "VRTool.h"
Private Member Functions
void CreateEditorInput ()
Creates the EditorOnlyInputComponent if it does not already exist and registers all subobject callbacks to it.
GENERATED_BODY () AVRTool(const FObjectInitializer &ObjectInitializer)
virtual void OnConstruction (const FTransform &Transform) override
virtual void PostEditChangeProperty (FPropertyChangedEvent &PropertyChangedEvent) override
void RemoveEditorInput ()
Removes the EditorOnlyInputComponent from this utility actor.
UFUNCTION () bool GetReceivesEditorInput() const
UFUNCTION () UInputComponent *GetInputComponent() const
Returns the current InputComponent on this utility actor.
UFUNCTION () void SetReceivesEditorInput(bool bInValue)
UPROPERTY ()) bool bReceivesEditorInput
If set to true, then this actor will be able to recieve input delegate callbacks when in the editor.
UPROPERTY ()) TObjectPtr< UInputComponent > EditorOnlyInputComponent
Detailed Description
Definition at line 14 of file VRTool.h.
Member Function Documentation
CreateEditorInput()
void AVRTool::CreateEditorInput () private
Creates the EditorOnlyInputComponent if it does not already exist and registers all subobject callbacks to it.
GENERATED_BODY()
AVRTool::GENERATED_BODY () const & private
OnConstruction()
virtual void AVRTool::OnConstruction (const FTransform & Transform) override private virtual
References OnConstruction(), and Transform.
Referenced by OnConstruction().
PostEditChangeProperty()
virtual void AVRTool::PostEditChangeProperty (FPropertyChangedEvent & PropertyChangedEvent) override private virtual
RemoveEditorInput()
void AVRTool::RemoveEditorInput () private
Removes the EditorOnlyInputComponent from this utility actor.
UFUNCTION() [1/3]
AVRTool::UFUNCTION () const inline private
Definition at line 35 of file VRTool.h.
References Category, and UFUNCTION().
UFUNCTION() [2/3]
AVRTool::UFUNCTION () const inline private
Returns the current InputComponent on this utility actor.
This will be NULL unless bReceivesEditorInput is set to true.
Definition at line 26 of file VRTool.h.
References Category.
Referenced by UFUNCTION().
UFUNCTION() [3/3]
AVRTool::UFUNCTION () private
References Category.
UPROPERTY() [1/2]
AVRTool::UPROPERTY () private
If set to true, then this actor will be able to recieve input delegate callbacks when in the editor.
References Category, meta, and UPROPERTY().
UPROPERTY() [2/2]
AVRTool::UPROPERTY () private
References meta, and Transient.
Referenced by UPROPERTY().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Experimental/VirtualProductionUtilities/Source/VPUtilitiesEditor/Public/VRTool.h