Unreal Engine 5.6 C++ API: TEnumAsByte< InEnumType > Class Template Reference
TEnumAsByte< InEnumType > Class Template Reference
Template to store enumeration values as bytes in a type-safe way.
#include "EnumAsByte.h"
Public Types
using EnumType = InEnumType
Public Member Functions
TEnumAsByte ()=default
TEnumAsByte (const TEnumAsByte &)=default
FORCEINLINE TEnumAsByte (EnumType InValue)
Constructor, initialize to the enum value.
FORCEINLINE TEnumAsByte (int32 InValue)
Constructor, initialize to the int32 value.
FORCEINLINE TEnumAsByte (uint8 InValue)
Constructor, initialize to the int32 value.
uint8 GetIntValue () const
Gets the integer enumeration value.
EnumType GetValue () const
Gets the enumeration value.
operator EnumType () const
Implicit conversion to EnumType.
TEnumAsByte & operator= (const TEnumAsByte &)=default
bool operator== (EnumType InValue) const
Compares two enumeration values for equality.
bool operator== (TEnumAsByte InValue) const
Compares two enumeration values for equality.
Private Attributes
uint8 Value
Holds the value as a byte.
Detailed Description
template<class InEnumType>
class TEnumAsByte< InEnumType >
Template to store enumeration values as bytes in a type-safe way.
Traits classes and constants which test if a type is a TEnumAsByte.
Blueprint enums should either be enum classes (preferred): enum class EMyEnum : uint8 { One, Two }, which doesn't require wrapping in this template or a namespaced enum namespace EMyEnum { enum Type // <- literally Type, not a placeholder { One, Two }; }
Definition at line 21 of file EnumAsByte.h.
Member Typedef Documentation
EnumType
template<class InEnumType> using TEnumAsByte< InEnumType >::EnumType = InEnumType
Definition at line 26 of file EnumAsByte.h.
Constructor & Destructor Documentation
TEnumAsByte() [1/5]
template<class InEnumType> TEnumAsByte< InEnumType >::TEnumAsByte () nodiscard default
Referenced by TEnumAsByte(), operator=(), and operator==().
TEnumAsByte() [2/5]
template<class InEnumType> TEnumAsByte< InEnumType >::TEnumAsByte (const TEnumAsByte< InEnumType > &) nodiscard default
References TEnumAsByte().
TEnumAsByte() [3/5]
template<class InEnumType> FORCEINLINE TEnumAsByte< InEnumType >::TEnumAsByte (EnumType InValue) inline nodiscard
Constructor, initialize to the enum value.
Parameters
InValue value to construct with.
Definition at line 37 of file EnumAsByte.h.
References FORCEINLINE, and Value.
TEnumAsByte() [4/5]
template<class InEnumType> FORCEINLINE TEnumAsByte< InEnumType >::TEnumAsByte (int32 InValue) inline explicit nodiscard
Constructor, initialize to the int32 value.
Parameters
InValue value to construct with.
Definition at line 47 of file EnumAsByte.h.
References FORCEINLINE, and Value.
TEnumAsByte() [5/5]
template<class InEnumType> FORCEINLINE TEnumAsByte< InEnumType >::TEnumAsByte (uint8 InValue) inline explicit nodiscard
Constructor, initialize to the int32 value.
Parameters
InValue value to construct with.
Definition at line 57 of file EnumAsByte.h.
References FORCEINLINE, and Value.
Member Function Documentation
GetIntValue()
template<class InEnumType> uint8 TEnumAsByte< InEnumType >::GetIntValue () const inline nodiscard
Gets the integer enumeration value.
Returns
The enumeration value.
Definition at line 108 of file EnumAsByte.h.
References Value.
GetValue()
template<class InEnumType> EnumType TEnumAsByte< InEnumType >::GetValue () const inline nodiscard
Gets the enumeration value.
Returns
The enumeration value.
Definition at line 98 of file EnumAsByte.h.
References Value.
Referenced by FEdGraphPinHandle::FEdGraphPinHandle().
operator EnumType()
template<class InEnumType> TEnumAsByte< InEnumType >::operator EnumType () const inline nodiscard
Implicit conversion to EnumType.
Definition at line 86 of file EnumAsByte.h.
References Value.
operator=()
template<class InEnumType> TEnumAsByte & TEnumAsByte< InEnumType >::operator= (const TEnumAsByte< InEnumType > &) default
References TEnumAsByte().
operator==() [1/2]
template<class InEnumType> bool TEnumAsByte< InEnumType >::operator== (EnumType InValue) const inline nodiscard
Compares two enumeration values for equality.
Parameters
InValue The value to compare with.
Returns
true if the two values are equal, false otherwise.
Definition at line 69 of file EnumAsByte.h.
References Value.
operator==() [2/2]
template<class InEnumType> bool TEnumAsByte< InEnumType >::operator== (TEnumAsByte< InEnumType > InValue) const inline nodiscard
Compares two enumeration values for equality.
Parameters
InValue The value to compare with.
Returns
true if the two values are equal, false otherwise.
Definition at line 80 of file EnumAsByte.h.
References TEnumAsByte(), and Value.
Field Documentation
Value
template<class InEnumType> uint8 TEnumAsByte< InEnumType >::Value private
Holds the value as a byte.
Definition at line 116 of file EnumAsByte.h.
Referenced by TEnumAsByte(), TEnumAsByte(), TEnumAsByte(), GetIntValue(), GetValue(), operator EnumType(), operator==(), and operator==().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Containers/EnumAsByte.h