Unreal Engine 5.6 C++ API: FWorldPartitionLoadingContext Class Reference
FWorldPartitionLoadingContext Class Reference
#include "WorldPartitionHandle.h"
Data Structures
class FDeferred
Deferred loading context, which will gather actor registrations and unregistrations and execute them at the end of scope.
class FImmediate
Immediate loading context, which will register and unregister actors on demand.
class FNull
Null loading context, which will ignore all loading/unloading commands.
class IContext
Base class for loading contexts.
Public Member Functions
UE_DEPRECATED (5.4, "Use FWorldPartitionActorDescInstance version instead") static void LoadAndRegisterActor(FWorldPartitionActorDesc *ActorDesc)
UE_DEPRECATED (5.4, "Use FWorldPartitionActorDescInstance version instead") static void UnloadAndUnregisterActor(FWorldPartitionActorDesc *ActorDesc)
Static Private Member Functions
static void LoadAndRegisterActor (FWorldPartitionActorDescInstance *ActorDescInstance)
static void UnloadAndUnregisterActor (FWorldPartitionActorDescInstance *ActorDescInstance)
Static Private Attributes
static IContext * ActiveContext
static FImmediate DefaultContext
Friends
struct FWorldPartitionReferenceImpl
Detailed Description
Definition at line 25 of file WorldPartitionHandle.h.
Member Function Documentation
LoadAndRegisterActor()
void FWorldPartitionLoadingContext::LoadAndRegisterActor (FWorldPartitionActorDescInstance * ActorDescInstance) static private
Referenced by UE_DEPRECATED().
UE_DEPRECATED() [1/2]
FWorldPartitionLoadingContext::UE_DEPRECATED (5. 4, "Use FWorldPartitionActorDescInstance version instead") inline
Definition at line 97 of file WorldPartitionHandle.h.
References LoadAndRegisterActor().
UE_DEPRECATED() [2/2]
FWorldPartitionLoadingContext::UE_DEPRECATED (5. 4, "Use FWorldPartitionActorDescInstance version instead") inline
Definition at line 99 of file WorldPartitionHandle.h.
References UnloadAndUnregisterActor().
UnloadAndUnregisterActor()
void FWorldPartitionLoadingContext::UnloadAndUnregisterActor (FWorldPartitionActorDescInstance * ActorDescInstance) static private
Referenced by UE_DEPRECATED().
Friends And Related Symbol Documentation
FWorldPartitionReferenceImpl
friend struct FWorldPartitionReferenceImpl friend
Definition at line 27 of file WorldPartitionHandle.h.
References FWorldPartitionReferenceImpl.
Referenced by FWorldPartitionReferenceImpl.
Field Documentation
ActiveContext
IContext* FWorldPartitionLoadingContext::ActiveContext static private
Definition at line 107 of file WorldPartitionHandle.h.
DefaultContext
FImmediate FWorldPartitionLoadingContext::DefaultContext static private
Definition at line 106 of file WorldPartitionHandle.h.
The documentation for this class was generated from the following file:
Runtime/Engine/Public/WorldPartition/WorldPartitionHandle.h