Unreal Engine 5.6 C++ API: UParticleModuleLocationSkelVertSurface Class Reference
UParticleModuleLocationSkelVertSurface Class Reference
#include "ParticleModuleLocationSkelVertSurface.h"
Private Member Functions
virtual void AutoPopulateInstanceProperties (UParticleSystemComponent *PSysComp) override
virtual bool CanTickInAnyThread () override
virtual void FinalUpdate (const FUpdateContext &Context) override
GENERATED_UCLASS_BODY () UPROPERTY() TEnumAsByte< enum ELocationSkelVertSurfaceSource > SourceType
Whether the module uses Verts or Surfaces for locations.
virtual bool GetCustomMenuEntryDisplayString (int32 InEntryIndex, FString &OutDisplayString) const override
virtual int32 GetNumberOfCustomMenuOptions () const override
bool GetParticleLocation (const FContext &Context, FModuleLocationVertSurfaceInstancePayload *InstPayload, USkeletalMeshComponent *InSkelMeshComponent, int32 InPrimaryVertexIndex, FVector &OutPosition, FQuat &OutRotation, bool bSpawning=false)
Retrieve the position for the given socket index.
void GetSkeletalMeshComponentSource (const FContext &Context, FModuleLocationVertSurfaceInstancePayload *InstancePayload)
Retrieve the skeletal mesh component source to use for the current emitter instance.
virtual bool IsValidForLODLevel (UParticleLODLevel *LODLevel, FString &OutErrorString) override
virtual bool PerformCustomMenuEntry (int32 InEntryIndex) override
virtual void PostEditChangeProperty (FPropertyChangedEvent &PropertyChangedEvent) override
virtual void PostLoad () override
virtual uint32 PrepPerInstanceBlock (FParticleEmitterInstance *Owner, void *InstData) override
virtual uint32 RequiredBytes (UParticleModuleTypeDataBase *TypeData) override
virtual uint32 RequiredBytesPerInstance () override
virtual void Spawn (const FSpawnContext &Context) override
virtual bool TouchesMeshRotation () const override
virtual void Update (const FUpdateContext &Context) override
void UpdateBoneIndicesList (FParticleEmitterInstance *Owner)
Updates the indices list with the bone index for each named bone in the editor exposed values.
UPROPERTY() uint32 bUpdatePositionEachFrame UPROPERTY() uint32 bOrientMeshEmitters UPROPERTY() uint32 bInheritBoneVelocity UPROPERTY () float InheritVelocityScale
If true, update the particle locations each frame with that of the vert/surface.
UPROPERTY () float NormalCheckTolerance
Normal tolerance.
UPROPERTY () float NormalCheckToleranceDegrees
Normal tolerance.
UPROPERTY () FName SkelMeshActorParamName
The parameter name of the skeletal mesh actor that supplies the SkelMeshComponent for in-game.
UPROPERTY() uint32 bEnforceNormalCheck UPROPERTY () FVector NormalToCompare
When true use the RestrictToNormal and NormalTolerance values to check surface normals.
UPROPERTY () FVector UniversalOffset
An offset to apply to each vert/surface.
UPROPERTY () TArray< FName > ValidAssociatedBones
This module will only spawn from verts or surfaces associated with the bones in this list.
UPROPERTY () TArray< int32 > ValidMaterialIndices
Array of material indices that are valid materials to spawn from.
UPROPERTY() uint32 bInheritVertexColor UPROPERTY() uint32 bInheritUV UPROPERTY () uint32 InheritUVChannel
If true, particles inherit the associated vertex color on spawn.
bool VertInfluencedByActiveBone (FParticleEmitterInstance *Owner, FModuleLocationVertSurfaceInstancePayload *InstPayload, USkeletalMeshComponent *InSkelMeshComponent, int32 InVertexIndex, int32 *OutBoneIndex=NULL)
Check to see if the vert is influenced by a bone on our approved list.
bool VertInfluencedByActiveBoneTyped (FSkeletalMeshLODRenderData &LODData, int32 LODIndex, const FSkelMeshRenderSection &Section, int32 VertIndex, USkeletalMeshComponent *InSkelMeshComponent, FModuleLocationVertSurfaceInstancePayload *InstancePayload, int32 *OutBoneIndex)
Helper function for concrete types.
Detailed Description
Definition at line 75 of file ParticleModuleLocationSkelVertSurface.h.
Member Function Documentation
AutoPopulateInstanceProperties()
virtual void UParticleModuleLocationSkelVertSurface::AutoPopulateInstanceProperties (UParticleSystemComponent * PSysComp) override private virtual
CanTickInAnyThread()
virtual bool UParticleModuleLocationSkelVertSurface::CanTickInAnyThread () inline override private virtual
Definition at line 176 of file ParticleModuleLocationSkelVertSurface.h.
FinalUpdate()
virtual void UParticleModuleLocationSkelVertSurface::FinalUpdate (const FUpdateContext & Context) override private virtual
GENERATED_UCLASS_BODY()
UParticleModuleLocationSkelVertSurface::GENERATED_UCLASS_BODY () private
Whether the module uses Verts or Surfaces for locations.
VERTSURFACESOURCE_Vert - Use Verts as the source locations. VERTSURFACESOURCE_Surface - Use Surfaces as the source locations.
References Category, and UPROPERTY().
GetCustomMenuEntryDisplayString()
virtual bool UParticleModuleLocationSkelVertSurface::GetCustomMenuEntryDisplayString (int32 InEntryIndex, FString & OutDisplayString) const override private virtual
GetNumberOfCustomMenuOptions()
virtual int32 UParticleModuleLocationSkelVertSurface::GetNumberOfCustomMenuOptions () const override private virtual
GetParticleLocation()
bool UParticleModuleLocationSkelVertSurface::GetParticleLocation (const FContext & Context, FModuleLocationVertSurfaceInstancePayload * InstPayload, USkeletalMeshComponent * InSkelMeshComponent, int32 InPrimaryVertexIndex, FVector & OutPosition, FQuat & OutRotation, bool bSpawning = false) private
Retrieve the position for the given socket index.
Parameters
Owner The particle emitter instance that is being setup
InSkelMeshComponent The skeletal mesh component to use as the source
InPrimaryVertexIndex The index of the only vertex (vert mode) or the first vertex (surface mode)
OutPosition The position for the particle location
OutRotation Optional orientation for the particle (mesh emitters)
bSpawning When true and when using normal check on surfaces, will return false if the check fails.
Returns
bool true if successful, false if not
References FVector.
GetSkeletalMeshComponentSource()
void UParticleModuleLocationSkelVertSurface::GetSkeletalMeshComponentSource (const FContext & Context, FModuleLocationVertSurfaceInstancePayload * InstancePayload) private
Retrieve the skeletal mesh component source to use for the current emitter instance.
Parameters
Owner The particle emitter instance that is being setup
Owner The payload data that is being setup.
IsValidForLODLevel()
virtual bool UParticleModuleLocationSkelVertSurface::IsValidForLODLevel (UParticleLODLevel * LODLevel, FString & OutErrorString) override private virtual
PerformCustomMenuEntry()
virtual bool UParticleModuleLocationSkelVertSurface::PerformCustomMenuEntry (int32 InEntryIndex) override private virtual
PostEditChangeProperty()
virtual void UParticleModuleLocationSkelVertSurface::PostEditChangeProperty (FPropertyChangedEvent & PropertyChangedEvent) override private virtual
PostLoad()
virtual void UParticleModuleLocationSkelVertSurface::PostLoad () override private virtual
References PostLoad().
Referenced by PostLoad().
PrepPerInstanceBlock()
virtual uint32 UParticleModuleLocationSkelVertSurface::PrepPerInstanceBlock (FParticleEmitterInstance * Owner, void * InstData) override private virtual
References Owner.
RequiredBytes()
virtual uint32 UParticleModuleLocationSkelVertSurface::RequiredBytes (UParticleModuleTypeDataBase * TypeData) override private virtual
RequiredBytesPerInstance()
virtual uint32 UParticleModuleLocationSkelVertSurface::RequiredBytesPerInstance () override private virtual
Spawn()
virtual void UParticleModuleLocationSkelVertSurface::Spawn (const FSpawnContext & Context) override private virtual
TouchesMeshRotation()
virtual bool UParticleModuleLocationSkelVertSurface::TouchesMeshRotation () const inline override private virtual
Definition at line 174 of file ParticleModuleLocationSkelVertSurface.h.
Update()
virtual void UParticleModuleLocationSkelVertSurface::Update (const FUpdateContext & Context) override private virtual
UpdateBoneIndicesList()
void UParticleModuleLocationSkelVertSurface::UpdateBoneIndicesList (FParticleEmitterInstance * Owner) private
Updates the indices list with the bone index for each named bone in the editor exposed values.
Parameters
Owner The FParticleEmitterInstance that 'owns' the particle.
References Owner.
UPROPERTY() [1/9]
UPROPERTY() uint32 bUpdatePositionEachFrame UPROPERTY() uint32 bOrientMeshEmitters UPROPERTY() uint32 bInheritBoneVelocity UParticleModuleLocationSkelVertSurface::UPROPERTY () private
If true, update the particle locations each frame with that of the vert/surface.
If true, rotate mesh emitter meshes to orient w/ the vert/surface If true, particles inherit the associated bone velocity when spawned A scale on how much of the bone's velocity a particle will inherit.
References Category, and UPROPERTY().
UPROPERTY() [2/9]
UParticleModuleLocationSkelVertSurface::UPROPERTY () private
Normal tolerance.
Value between 1.0 and -1.0 with 1.0 being exact match, 0.0 being everything up to perpendicular and -1.0 being any direction or don't restrict at all.
References float.
UPROPERTY() [3/9]
UParticleModuleLocationSkelVertSurface::UPROPERTY () private
Normal tolerance.
0 degrees means it must be an exact match, 180 degrees means it can be any angle.
References Category.
UPROPERTY() [4/9]
UParticleModuleLocationSkelVertSurface::UPROPERTY () private
The parameter name of the skeletal mesh actor that supplies the SkelMeshComponent for in-game.
References Category, and UPROPERTY().
UPROPERTY() [5/9]
UPROPERTY() uint32 bEnforceNormalCheck UParticleModuleLocationSkelVertSurface::UPROPERTY () private
When true use the RestrictToNormal and NormalTolerance values to check surface normals.
Use this normal to restrict spawning locations
References Category, and FVector.
UPROPERTY() [6/9]
UParticleModuleLocationSkelVertSurface::UPROPERTY () private
An offset to apply to each vert/surface.
References Category, FVector, and UPROPERTY().
Referenced by GENERATED_UCLASS_BODY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), and UPROPERTY().
UPROPERTY() [7/9]
UParticleModuleLocationSkelVertSurface::UPROPERTY () private
This module will only spawn from verts or surfaces associated with the bones in this list.
References Category.
UPROPERTY() [8/9]
UParticleModuleLocationSkelVertSurface::UPROPERTY () private
Array of material indices that are valid materials to spawn from.
If empty, any material will be considered valid
References Category, and UPROPERTY().
UPROPERTY() [9/9]
UPROPERTY() uint32 bInheritVertexColor UPROPERTY() uint32 bInheritUV UParticleModuleLocationSkelVertSurface::UPROPERTY () private
If true, particles inherit the associated vertex color on spawn.
This feature is not supported for GPU particles. If true, particles inherit the associated UV data on spawn. Accessed through dynamic parameter module X and Y, must be a "Spawn Time Only" parameter on "AutoSet" mode. This feature is not supported for GPU particles. UV channel to inherit from the spawn mesh, internally clamped to those available.
References Category, and UPROPERTY().
VertInfluencedByActiveBone()
bool UParticleModuleLocationSkelVertSurface::VertInfluencedByActiveBone (FParticleEmitterInstance * Owner, FModuleLocationVertSurfaceInstancePayload * InstPayload, USkeletalMeshComponent * InSkelMeshComponent, int32 InVertexIndex, int32 * OutBoneIndex = NULL) private
Check to see if the vert is influenced by a bone on our approved list.
Parameters
Owner The particle emitter instance that is being setup
InSkelMeshComponent The skeletal mesh component to use as the source
InVertexIndex The vertex index of the vert to check.
OutBoneIndex Optional return of matching bone index
Returns
bool true if it is influenced by an approved bone, false otherwise.
References Owner.
VertInfluencedByActiveBoneTyped()
bool UParticleModuleLocationSkelVertSurface::VertInfluencedByActiveBoneTyped (FSkeletalMeshLODRenderData & LODData, int32 LODIndex, const FSkelMeshRenderSection & Section, int32 VertIndex, USkeletalMeshComponent * InSkelMeshComponent, FModuleLocationVertSurfaceInstancePayload * InstancePayload, int32 * OutBoneIndex) private
Helper function for concrete types.
The documentation for this class was generated from the following file:
Runtime/Engine/Classes/Particles/Location/ParticleModuleLocationSkelVertSurface.h