Unreal Engine 5.6 C++ API: IMovieSceneTimeWarpSource Class Reference
IMovieSceneTimeWarpSource Class Reference abstract
#include "MovieSceneTimeWarpDecoration.h"
Public Member Functions
GENERATED_BODY () virtual FMovieSceneNestedSequenceTransform GenerateTimeWarpTransform()=0
virtual int32 GetTimeWarpSortOrder () const =0
virtual bool IsTimeWarpActive () const =0
virtual void SetIsTimeWarpActive (bool bInActive)=0
Detailed Description
Definition at line 22 of file MovieSceneTimeWarpDecoration.h.
Member Function Documentation
GENERATED_BODY()
IMovieSceneTimeWarpSource::GENERATED_BODY () pure virtual
Referenced by GetTimeWarpSortOrder().
GetTimeWarpSortOrder()
virtual int32 IMovieSceneTimeWarpSource::GetTimeWarpSortOrder () const pure virtual
References GENERATED_BODY(), GetTimeWarpSortOrder(), MinimalAPI, Params, UCLASS, and UPROPERTY.
Referenced by GetTimeWarpSortOrder().
IsTimeWarpActive()
virtual bool IMovieSceneTimeWarpSource::IsTimeWarpActive () const pure virtual
References IsTimeWarpActive().
Referenced by IsTimeWarpActive().
SetIsTimeWarpActive()
virtual void IMovieSceneTimeWarpSource::SetIsTimeWarpActive (bool bInActive) pure virtual
References SetIsTimeWarpActive().
Referenced by SetIsTimeWarpActive().
The documentation for this class was generated from the following file:
Runtime/MovieScene/Public/Decorations/MovieSceneTimeWarpDecoration.h