Unreal Engine 5.6 C++ API: FRDGBuffer Class Reference
FRDGBuffer Class Reference final
A render graph tracked buffer.
#include "RenderGraphResources.h"
Public Member Functions
FRDGBufferHandle GetHandle () const
FORCEINLINE FRHIBuffer * GetIndirectRHICallBuffer () const
Returns the buffer to use for indirect RHI calls.
FRHIBuffer * GetRHI () const
The following methods may only be called during pass execution.
FORCEINLINE uint32 GetSize () const
FORCEINLINE uint32 GetStride () const
bool IsCulled () const
Public Member Functions inherited from FRDGViewableResource
bool HasBeenProduced () const
Whether a prior pass added to the graph produced contents for this resource.
bool IsDebugNameHeapAllocated () const
bool IsExternal () const
Whether this resource is externally registered with the graph (i.e.
bool IsExtracted () const
Whether this resource is has been queued for extraction at the end of graph execution.
void SetOwnerName (const FName &InOwnerName)
Public Member Functions inherited from FRDGResource
FRDGResource (const FRDGResource &)=delete
virtual ~FRDGResource ()=default
FRHIResource * GetRHI () const
virtual RENDERCORE_API void MarkResourceAsUsed ()
The following methods may only be called during pass execution.
Data Fields
FRDGBufferDesc Desc
const ERDGBufferFlags Flags
Data Fields inherited from FRDGViewableResource
const ERDGViewableResourceType Type
The type of this resource; useful for casting between types.
Data Fields inherited from FRDGResource
const TCHAR *const Name = nullptr
Static Public Attributes
static const ERDGViewableResourceType StaticType = ERDGViewableResourceType::Buffer
Private Member Functions
RENDERCORE_API FRDGBuffer (const TCHAR *InName, const FRDGBufferDesc &InDesc, ERDGBufferFlags InFlags)
RENDERCORE_API FRDGBuffer (const TCHAR *InName, const FRDGBufferDesc &InDesc, ERDGBufferFlags InFlags, FRDGBufferNumElementsCallback *InNumElementsCallback)
RENDERCORE_API void FinalizeDesc ()
Finalizes any pending field of the buffer descriptor.
FRHIBuffer * GetRHIUnchecked () const
Private Attributes
TRefCountPtr< FRDGPooledBuffer > Allocation
Valid strictly when holding a strong reference; use PooledBuffer instead.
FRDGSubresourceState * FirstState = nullptr
Tracks the first state in the graph for this buffer.
friend FRDGAllocator
friend FRDGBarrierValidation
friend FRDGBufferRegistry
friend FRDGBuilder
friend FRDGTrace
friend FRDGUserValidation
FRDGBufferHandle Handle
Registered handle set by the builder.
FRDGProducerStatesByPipeline LastProducer
Tracks the last pass that produced this resource as the graph is built.
FRDGSubresourceState * MergeState = nullptr
Tracks the merged subresource state as the graph is built.
FRDGBufferHandle NextOwner
FRDGBufferNumElementsCallback * NumElementsCallback = nullptr
Optional callback to supply NumElements after the creation of this FRDGBuffer.
uint64 PendingCommitSize = 0
Optional reserved resource commit size to apply on the first resource transition.
FRDGPooledBuffer * PooledBuffer = nullptr
Assigned pooled buffer pointer.
FRDGBufferHandle PreviousOwner
The previous / next buffer to own the PooledBuffer allocation during execution.
FRDGSubresourceState * State = nullptr
Cached state pointer from the pooled / transient buffer.
FRHITransientBuffer * TransientBuffer = nullptr
Assigned transient buffer pointer.
FRHIBufferViewCache * ViewCache = nullptr
The assigned buffer view cache (sourced from the pooled / transient buffer.
Additional Inherited Members
Protected Types inherited from FRDGViewableResource
enum class EAccessMode : uint8 { Internal , External }
enum class ETransientExtractionHint : uint8 { None , Disable , Enable }
Protected Member Functions inherited from FRDGViewableResource
RENDERCORE_API FRDGViewableResource (const TCHAR *InName, ERDGViewableResourceType InType, bool bSkipTracking, bool bImmediateFirstBarrier)
bool IsCullRoot () const
Protected Member Functions inherited from FRDGResource
FRDGResource (const TCHAR *InName)
FRHIResource * GetRHIUnchecked () const
bool HasRHI () const
RENDERCORE_API void ValidateRHIAccess () const
Protected Attributes inherited from FRDGViewableResource
struct FRDGViewableResource::FAccessModeState AccessModeState
FRDGPassHandle AcquirePass
TArrayView< const FRHITransientAliasingOverlap > AliasingOverlaps
Set of aliasing overlaps to apply to the acquire transition if transient.
uint8 bClobbered: 1
uint8 bCollectForAllocate: 1
If false, the resource needs to be collected.
uint8 bExternal: 1
Whether this is an externally registered resource.
uint8 bExtracted: 1
Whether this is an extracted resource.
uint8 bForceNonTransient: 1
Whether this resource cannot be made transient.
uint8 bProduced: 1
Whether any sub-resource has been used for write by a pass.
uint8 bQueuedForUpload: 1
If true, the resource has been queued for an upload operation.
uint8 bSkipLastTransition: 1
If true, the graph will skip the last graph transition.
uint8 bSplitFirstTransition: 1
If true, this resource should skip the first split barrier and perform transition right away.
uint8 bTransient: 1
Whether this resource is allocated through the transient resource allocator.
FRDGPassHandle DiscardPass
ERHIAccess EpilogueAccess = DefaultEpilogueAccess
The state of the resource at the graph epilogue.
FRDGPassHandle FirstPass
FRDGPassHandlesByPipeline LastPasses
uint32 PassStateIndex = 0
Scratch index allocated for the resource in the pass being setup.
uint32 ReferenceCount
Number of references in passes and deferred queries.
ETransientExtractionHint TransientExtractionHint
Whether this resource is allowed to be both transient and extracted.
Protected Attributes inherited from FRDGResource
FRHIResource * ResourceRHI = nullptr
Static Protected Attributes inherited from FRDGViewableResource
static const ERHIAccess DefaultEpilogueAccess = ERHIAccess::SRVMask
Detailed Description
A render graph tracked buffer.
Definition at line 1319 of file RenderGraphResources.h.
Constructor & Destructor Documentation
FRDGBuffer() [1/2]
RENDERCORE_API FRDGBuffer::FRDGBuffer (const TCHAR * InName, const FRDGBufferDesc & InDesc, ERDGBufferFlags InFlags) private
References InName.
FRDGBuffer() [2/2]
RENDERCORE_API FRDGBuffer::FRDGBuffer (const TCHAR * InName, const FRDGBufferDesc & InDesc, ERDGBufferFlags InFlags, FRDGBufferNumElementsCallback * InNumElementsCallback) private
References InName.
Member Function Documentation
FinalizeDesc()
RENDERCORE_API void FRDGBuffer::FinalizeDesc () private
Finalizes any pending field of the buffer descriptor.
GetHandle()
FRDGBufferHandle FRDGBuffer::GetHandle () const inline
Definition at line 1346 of file RenderGraphResources.h.
References Handle.
GetIndirectRHICallBuffer()
FORCEINLINE FRHIBuffer * FRDGBuffer::GetIndirectRHICallBuffer () const inline
Returns the buffer to use for indirect RHI calls.
Definition at line 1338 of file RenderGraphResources.h.
References checkf, Desc, FORCEINLINE, GetRHI(), FRDGResource::Name, and TEXT.
Referenced by FComputeShaderUtils::AddPass(), and FComputeShaderUtils::DispatchIndirect().
GetRHI()
FRHIBuffer * FRDGBuffer::GetRHI () const inline
The following methods may only be called during pass execution.
Returns the underlying RHI buffer resource
Definition at line 1332 of file RenderGraphResources.h.
References FRDGResource::GetRHI().
Referenced by GetIndirectRHICallBuffer().
GetRHIUnchecked()
FRHIBuffer * FRDGBuffer::GetRHIUnchecked () const inline private
Definition at line 1373 of file RenderGraphResources.h.
References FRDGResource::GetRHIUnchecked().
GetSize()
FORCEINLINE uint32 FRDGBuffer::GetSize () const inline
Definition at line 1351 of file RenderGraphResources.h.
References Desc, and FORCEINLINE.
Referenced by FComputeShaderUtils::ValidateIndirectArgsBuffer().
GetStride()
FORCEINLINE uint32 FRDGBuffer::GetStride () const inline
Definition at line 1356 of file RenderGraphResources.h.
References Desc, and FORCEINLINE.
IsCulled()
bool FRDGBuffer::IsCulled () const inline
Definition at line 1361 of file RenderGraphResources.h.
References PendingCommitSize, and FRDGViewableResource::ReferenceCount.
Field Documentation
Allocation
TRefCountPtr<FRDGPooledBuffer> FRDGBuffer::Allocation private
Valid strictly when holding a strong reference; use PooledBuffer instead.
Definition at line 1395 of file RenderGraphResources.h.
Desc
FRDGBufferDesc FRDGBuffer::Desc
Definition at line 1325 of file RenderGraphResources.h.
Referenced by FComputeShaderUtils::AddPass(), GetIndirectRHICallBuffer(), GetSize(), GetStride(), and FComputeShaderUtils::ValidateIndirectArgsBuffer().
FirstState
FRDGSubresourceState* FRDGBuffer::FirstState = nullptr private
Tracks the first state in the graph for this buffer.
Definition at line 1410 of file RenderGraphResources.h.
Flags
const ERDGBufferFlags FRDGBuffer::Flags
Definition at line 1326 of file RenderGraphResources.h.
FRDGAllocator
friend FRDGBuffer::FRDGAllocator private
Definition at line 1419 of file RenderGraphResources.h.
FRDGBarrierValidation
friend FRDGBuffer::FRDGBarrierValidation private
Definition at line 1416 of file RenderGraphResources.h.
FRDGBufferRegistry
friend FRDGBuffer::FRDGBufferRegistry private
Definition at line 1418 of file RenderGraphResources.h.
FRDGBuilder
friend FRDGBuffer::FRDGBuilder private
Definition at line 1415 of file RenderGraphResources.h.
FRDGTrace
friend FRDGBuffer::FRDGTrace private
Definition at line 1420 of file RenderGraphResources.h.
FRDGUserValidation
friend FRDGBuffer::FRDGUserValidation private
Definition at line 1417 of file RenderGraphResources.h.
Handle
FRDGBufferHandle FRDGBuffer::Handle private
Registered handle set by the builder.
Definition at line 1379 of file RenderGraphResources.h.
Referenced by GetHandle().
LastProducer
FRDGProducerStatesByPipeline FRDGBuffer::LastProducer private
Tracks the last pass that produced this resource as the graph is built.
Definition at line 1398 of file RenderGraphResources.h.
MergeState
FRDGSubresourceState* FRDGBuffer::MergeState = nullptr private
Tracks the merged subresource state as the graph is built.
Definition at line 1413 of file RenderGraphResources.h.
NextOwner
FRDGBufferHandle FRDGBuffer::NextOwner private
Definition at line 1383 of file RenderGraphResources.h.
NumElementsCallback
FRDGBufferNumElementsCallback* FRDGBuffer::NumElementsCallback = nullptr private
Optional callback to supply NumElements after the creation of this FRDGBuffer.
Definition at line 1401 of file RenderGraphResources.h.
PendingCommitSize
uint64 FRDGBuffer::PendingCommitSize = 0 private
Optional reserved resource commit size to apply on the first resource transition.
Definition at line 1404 of file RenderGraphResources.h.
Referenced by IsCulled().
PooledBuffer
FRDGPooledBuffer* FRDGBuffer::PooledBuffer = nullptr private
Assigned pooled buffer pointer.
Never reset once assigned.
Definition at line 1386 of file RenderGraphResources.h.
PreviousOwner
FRDGBufferHandle FRDGBuffer::PreviousOwner private
The previous / next buffer to own the PooledBuffer allocation during execution.
Definition at line 1382 of file RenderGraphResources.h.
State
FRDGSubresourceState* FRDGBuffer::State = nullptr private
Cached state pointer from the pooled / transient buffer.
Definition at line 1407 of file RenderGraphResources.h.
StaticType
const ERDGViewableResourceType FRDGBuffer::StaticType = ERDGViewableResourceType::Buffer static
Definition at line 1323 of file RenderGraphResources.h.
TransientBuffer
FRHITransientBuffer* FRDGBuffer::TransientBuffer = nullptr private
Assigned transient buffer pointer.
Never reset once assigned.
Definition at line 1389 of file RenderGraphResources.h.
ViewCache
FRHIBufferViewCache* FRDGBuffer::ViewCache = nullptr private
The assigned buffer view cache (sourced from the pooled / transient buffer.
Never reset.
Definition at line 1392 of file RenderGraphResources.h.
The documentation for this class was generated from the following file:
Runtime/RenderCore/Public/RenderGraphResources.h