Unreal Engine 5.6 C++ API: UE::Geometry::TImageBuilder< PixelType > Class Template Reference
UE::Geometry::TImageBuilder< PixelType > Class Template Reference
TImageBuilder is used to create and populate a 2D image with a templated "pixel" type.
#include "ImageBuilder.h"
Public Member Functions
template<typename ScalarType, EImageTilingMethod TilingMethod = EImageTilingMethod::Clamp>
PixelType BilinearSample (const FVector2d &PixelCoords, const PixelType &InvalidValue) const
Sample the image value at floating-point pixel coords with Bilinear interpolation The pixel coords are expected to be in the [0,Width]x[0,Height] image pixel rectangle.
template<typename ScalarType, EImageTilingMethod TilingMethod = EImageTilingMethod::Clamp>
PixelType BilinearSampleUV (const FVector2d &UVCoords, const PixelType &InvalidValue) const
Sample the image value at floating-point UV coords with Bilinear interpolation.
void Clear (const PixelType &ClearValue)
Clear all Pixels in the current Mip to the clear/default color for the texture build type.
bool ContainsPixel (const FVector2i &ImageCoords) const
bool ContainsPixel (int32 X, int32 Y) const
template<typename OtherType>
void Convert (TFunctionRef< OtherType(const PixelType &)> ConvertFunc, TImageBuilder< OtherType > &ConvertedImageOut) const
Convert to a different data type of same Dimensions using ConvertFunc.
void CopyPixel (int64 FromLinearIndex, int64 ToLinearIndex)
Copy Pixel value from one linear index to another.
TImageBuilder< PixelType > FastDownsample (int32 SubSteps, const PixelType &ZeroValue, TFunctionRef< PixelType(PixelType, int)> AverageFunc) const
Very basic downsampling technqiue that just averages NxN pixel blocks.
const FImageDimensions & GetDimensions () const
TArrayView64< PixelType > GetImageBuffer ()
TConstArrayView64< PixelType > GetImageBuffer () const
PixelType & GetPixel (const FVector2i &ImageCoords)
Get the Pixel at the given X/Y coordinates.
const PixelType & GetPixel (const FVector2i &ImageCoords) const
Get the Pixel at the given X/Y coordinates.
PixelType & GetPixel (int32 X, int32 Y)
Get the Pixel at the given X/Y coordinates.
const PixelType & GetPixel (int32 X, int32 Y) const
Get the Pixel at the given X/Y coordinates.
PixelType & GetPixel (int64 LinearIndex)
Get the Pixel at the given linear index.
const PixelType & GetPixel (int64 LinearIndex) const
Get the Pixel at the given linear index.
bool IsConstantValue () const
template<EImageTilingMethod TilingMethod = EImageTilingMethod::Clamp>
PixelType NearestSampleUV (const FVector2d &UVCoords) const
Sample the image value at floating-point UV coords with Nearest sampling.
void SetDimensions (FImageDimensions DimensionsIn)
void SetPixel (const FVector2i &ImageCoords, const PixelType &NewValue)
Set the Pixel at the given X/Y coordinates to the given PixelType.
void SetPixel (int32 X, int32 Y, const PixelType &NewValue)
Set the Pixel at the given X/Y coordinates to the given PixelType.
void SetPixel (int64 LinearIndex, const PixelType &NewValue)
Set the Pixel at the given linear index to the given PixelType.
Static Protected Member Functions
template<EImageTilingMethod TilingMethod>
static FVector2d GetTiledUV (const FVector2d &UVCoords)
Protected Attributes
FImageDimensions Dimensions
TDenseGrid2< PixelType > Image
Detailed Description
template<typename PixelType>
class UE::Geometry::TImageBuilder< PixelType >
TImageBuilder is used to create and populate a 2D image with a templated "pixel" type.
Definition at line 25 of file ImageBuilder.h.
Member Function Documentation
BilinearSample()
template<typename PixelType> template<typename ScalarType, EImageTilingMethod TilingMethod = EImageTilingMethod::Clamp> PixelType UE::Geometry::TImageBuilder< PixelType >::BilinearSample (const FVector2d & PixelCoords, const PixelType & InvalidValue) const inline
Sample the image value at floating-point pixel coords with Bilinear interpolation The pixel coords are expected to be in the [0,Width]x[0,Height] image pixel rectangle.
Definition at line 191 of file ImageBuilder.h.
References A, Dimensions, TMathUtil< double >::Floor(), GetPixel(), FMath::Max, UE::Geometry::Max(), FMath::Min, UE::Math::TVector2< double >::One(), UE::Geometry::Wrap, UE::Geometry::FVector2i::X, UE::Math::TVector2< T >::X, UE::Geometry::FVector2i::Y, and UE::Math::TVector2< T >::Y.
Referenced by BilinearSampleUV().
BilinearSampleUV()
template<typename PixelType> template<typename ScalarType, EImageTilingMethod TilingMethod = EImageTilingMethod::Clamp> PixelType UE::Geometry::TImageBuilder< PixelType >::BilinearSampleUV (const FVector2d & UVCoords, const PixelType & InvalidValue) const inline
Sample the image value at floating-point UV coords with Bilinear interpolation.
Definition at line 243 of file ImageBuilder.h.
References BilinearSample(), Dimensions, GetTiledUV(), and UV.
Clear()
template<typename PixelType> void UE::Geometry::TImageBuilder< PixelType >::Clear (const PixelType & ClearValue) inline
Clear all Pixels in the current Mip to the clear/default color for the texture build type.
Definition at line 47 of file ImageBuilder.h.
References Image.
ContainsPixel() [1/2]
template<typename PixelType> bool UE::Geometry::TImageBuilder< PixelType >::ContainsPixel (const FVector2i & ImageCoords) const inline
Returns
true if the given X/Y coordinates are inside the image pixel bounds, ie can be used to index a pixel
Definition at line 63 of file ImageBuilder.h.
References Dimensions, UE::Geometry::FVector2i::X, and UE::Geometry::FVector2i::Y.
ContainsPixel() [2/2]
template<typename PixelType> bool UE::Geometry::TImageBuilder< PixelType >::ContainsPixel (int32 X, int32 Y) const inline
Returns
true if the given X/Y coordinates are inside the image pixel bounds, ie can be used to index a pixel
Definition at line 55 of file ImageBuilder.h.
References Dimensions, X, and Y.
Convert()
template<typename PixelType> template<typename OtherType> void UE::Geometry::TImageBuilder< PixelType >::Convert (TFunctionRef< OtherType(const PixelType &)> ConvertFunc, TImageBuilder< OtherType > & ConvertedImageOut) const inline
Convert to a different data type of same Dimensions using ConvertFunc.
Definition at line 174 of file ImageBuilder.h.
References Dimensions, Image, SetDimensions(), and SetPixel().
CopyPixel()
template<typename PixelType> void UE::Geometry::TImageBuilder< PixelType >::CopyPixel (int64 FromLinearIndex, int64 ToLinearIndex) inline
Copy Pixel value from one linear index to another.
Definition at line 164 of file ImageBuilder.h.
References Image.
FastDownsample()
template<typename PixelType> TImageBuilder< PixelType > UE::Geometry::TImageBuilder< PixelType >::FastDownsample (int32 SubSteps, const PixelType & ZeroValue, TFunctionRef< PixelType(PixelType, int)> AverageFunc) const inline
Very basic downsampling technqiue that just averages NxN pixel blocks.
Multi-threaded.
Parameters
SubSteps each NxN pixel block of this size is averaged into 1 pixel in the output image
Zero value to use with template PixelType must be provided, pixel values will be added to this value
AverageFunc Called with Sum(Pixels) and PixelCount, return value is used as new pixel value (eg should be average)
Definition at line 294 of file ImageBuilder.h.
References Dimensions, ensure, GetPixel(), UE::Geometry::Height, ParallelFor(), SetDimensions(), SetPixel(), and Width.
GetDimensions()
template<typename PixelType> const FImageDimensions & UE::Geometry::TImageBuilder< PixelType >::GetDimensions () const inline
Definition at line 39 of file ImageBuilder.h.
References Dimensions.
Referenced by UE::Geometry::FTexture2DBuilder::BuildTextureFromImage().
GetImageBuffer() [1/2]
template<typename PixelType> TArrayView64< PixelType > UE::Geometry::TImageBuilder< PixelType >::GetImageBuffer () inline
Definition at line 121 of file ImageBuilder.h.
References Buffer, and Image.
GetImageBuffer() [2/2]
template<typename PixelType> TConstArrayView64< PixelType > UE::Geometry::TImageBuilder< PixelType >::GetImageBuffer () const inline
Definition at line 127 of file ImageBuilder.h.
References Buffer, and Image.
GetPixel() [1/6]
template<typename PixelType> PixelType & UE::Geometry::TImageBuilder< PixelType >::GetPixel (const FVector2i & ImageCoords) inline
Get the Pixel at the given X/Y coordinates.
Definition at line 81 of file ImageBuilder.h.
References Dimensions, and Image.
GetPixel() [2/6]
template<typename PixelType> const PixelType & UE::Geometry::TImageBuilder< PixelType >::GetPixel (const FVector2i & ImageCoords) const inline
Get the Pixel at the given X/Y coordinates.
Definition at line 107 of file ImageBuilder.h.
References Dimensions, and Image.
GetPixel() [3/6]
template<typename PixelType> PixelType & UE::Geometry::TImageBuilder< PixelType >::GetPixel (int32 X, int32 Y) inline
Get the Pixel at the given X/Y coordinates.
Definition at line 72 of file ImageBuilder.h.
References Dimensions, Image, X, and Y.
Referenced by BilinearSample(), FastDownsample(), and NearestSampleUV().
GetPixel() [4/6]
template<typename PixelType> const PixelType & UE::Geometry::TImageBuilder< PixelType >::GetPixel (int32 X, int32 Y) const inline
Get the Pixel at the given X/Y coordinates.
Definition at line 98 of file ImageBuilder.h.
References Dimensions, Image, X, and Y.
GetPixel() [5/6]
template<typename PixelType> PixelType & UE::Geometry::TImageBuilder< PixelType >::GetPixel (int64 LinearIndex) inline
Get the Pixel at the given linear index.
Definition at line 90 of file ImageBuilder.h.
References Image.
GetPixel() [6/6]
template<typename PixelType> const PixelType & UE::Geometry::TImageBuilder< PixelType >::GetPixel (int64 LinearIndex) const inline
Get the Pixel at the given linear index.
Definition at line 116 of file ImageBuilder.h.
References Image.
GetTiledUV()
template<typename PixelType> template<EImageTilingMethod TilingMethod> FVector2d UE::Geometry::TImageBuilder< PixelType >::GetTiledUV (const FVector2d & UVCoords) inline static protected
Definition at line 341 of file ImageBuilder.h.
References TMathUtil< double >::Clamp(), TMathUtil< double >::Floor(), UV, and UE::Geometry::Wrap.
Referenced by BilinearSampleUV(), and NearestSampleUV().
IsConstantValue()
template<typename PixelType> bool UE::Geometry::TImageBuilder< PixelType >::IsConstantValue () const inline
Returns
true if all pixels have the same value
Definition at line 270 of file ImageBuilder.h.
References Dimensions, Image, and Num.
NearestSampleUV()
template<typename PixelType> template<EImageTilingMethod TilingMethod = EImageTilingMethod::Clamp> PixelType UE::Geometry::TImageBuilder< PixelType >::NearestSampleUV (const FVector2d & UVCoords) const inline
Sample the image value at floating-point UV coords with Nearest sampling.
Definition at line 258 of file ImageBuilder.h.
References Dimensions, GetPixel(), GetTiledUV(), UV, X, and Y.
SetDimensions()
template<typename PixelType> void UE::Geometry::TImageBuilder< PixelType >::SetDimensions (FImageDimensions DimensionsIn) inline
Definition at line 33 of file ImageBuilder.h.
References Dimensions, Image, and Yes.
Referenced by Convert(), and FastDownsample().
SetPixel() [1/3]
template<typename PixelType> void UE::Geometry::TImageBuilder< PixelType >::SetPixel (const FVector2i & ImageCoords, const PixelType & NewValue) inline
Set the Pixel at the given X/Y coordinates to the given PixelType.
Definition at line 145 of file ImageBuilder.h.
References Dimensions, and Image.
SetPixel() [2/3]
template<typename PixelType> void UE::Geometry::TImageBuilder< PixelType >::SetPixel (int32 X, int32 Y, const PixelType & NewValue) inline
Set the Pixel at the given X/Y coordinates to the given PixelType.
Definition at line 136 of file ImageBuilder.h.
References Dimensions, Image, X, and Y.
Referenced by Convert(), and FastDownsample().
SetPixel() [3/3]
template<typename PixelType> void UE::Geometry::TImageBuilder< PixelType >::SetPixel (int64 LinearIndex, const PixelType & NewValue) inline
Set the Pixel at the given linear index to the given PixelType.
Definition at line 155 of file ImageBuilder.h.
References Image.
Field Documentation
Dimensions
template<typename PixelType> FImageDimensions UE::Geometry::TImageBuilder< PixelType >::Dimensions protected
Definition at line 28 of file ImageBuilder.h.
Referenced by BilinearSample(), BilinearSampleUV(), ContainsPixel(), ContainsPixel(), Convert(), FastDownsample(), GetDimensions(), GetPixel(), GetPixel(), GetPixel(), GetPixel(), IsConstantValue(), NearestSampleUV(), SetDimensions(), SetPixel(), and SetPixel().
Image
template<typename PixelType> TDenseGrid2<PixelType> UE::Geometry::TImageBuilder< PixelType >::Image protected
Definition at line 29 of file ImageBuilder.h.
Referenced by Clear(), Convert(), CopyPixel(), GetImageBuffer(), GetImageBuffer(), GetPixel(), GetPixel(), GetPixel(), GetPixel(), GetPixel(), GetPixel(), IsConstantValue(), SetDimensions(), SetPixel(), SetPixel(), and SetPixel().
The documentation for this class was generated from the following file:
Runtime/GeometryCore/Public/Image/ImageBuilder.h