Unreal Engine 5.6 C++ API: FCoroSpinLock::FScope Class Reference
FCoroSpinLock::FScope Class Reference
Public Member Functions
FScope ()=default
FScope (FRWLock *InLockObject, bool InWriteLock)
FScope (FScope &&Other)
~FScope ()
FScope & operator= (FScope &&Other)
void Release ()
Private Attributes
FRWLock * LockObject = nullptr
bool WriteLock = true
Detailed Description
Definition at line 179 of file CoroSpinLock.h.
Constructor & Destructor Documentation
FScope() [1/3]
FCoroSpinLock::FScope::FScope () default
Referenced by FScope(), and operator=().
FScope() [2/3]
FCoroSpinLock::FScope::FScope (FRWLock * InLockObject, bool InWriteLock) inline
Definition at line 187 of file CoroSpinLock.h.
References LockObject, and WriteLock.
FScope() [3/3]
FCoroSpinLock::FScope::FScope (FScope && Other) inline
Definition at line 191 of file CoroSpinLock.h.
References FScope(), LockObject, Other, and WriteLock.
~FScope()
FCoroSpinLock::FScope::~FScope () inline
Definition at line 214 of file CoroSpinLock.h.
References Release().
Member Function Documentation
operator=()
FScope & FCoroSpinLock::FScope::operator= (FScope && Other) inline
Definition at line 219 of file CoroSpinLock.h.
References FScope(), MoveTemp(), and Other.
Release()
void FCoroSpinLock::FScope::Release () inline
Definition at line 198 of file CoroSpinLock.h.
References LockObject, and WriteLock.
Referenced by ~FScope().
Field Documentation
LockObject
FRWLock* FCoroSpinLock::FScope::LockObject = nullptr private
Definition at line 181 of file CoroSpinLock.h.
Referenced by FScope(), FScope(), and Release().
WriteLock
bool FCoroSpinLock::FScope::WriteLock = true private
Definition at line 182 of file CoroSpinLock.h.
Referenced by FScope(), FScope(), and Release().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Experimental/Coroutine/CoroSpinLock.h