Unreal Engine 5.6 C++ API: STableViewBase Class Reference
STableViewBase Class Reference abstract
Contains ListView functionality that does not depend on the type of data being observed by the ListView.
#include "STableViewBase.h"
Data Structures
struct FReGenerateResults
Information about the outcome of the WidgetRegeneratePass.
Public Member Functions
void AddScrollOffset (const float InScrollOffsetDelta, bool RefreshList=false)
Add the scroll offset of this view (in items)
virtual bool ComputeVolatility () const override
Recomputes the volatility of the widget.
void ConstructChildren (const TAttribute< float > &InItemWidth, const TAttribute< float > &InItemHeight, const TAttribute< EListItemAlignment > &InItemAlignment, const TSharedPtr< SHeaderRow > &InHeaderRow, const TSharedPtr< SScrollBar > &InScrollBar, EOrientation InScrollOrientation, const FOnTableViewScrolled &InOnTableViewScrolled, const FScrollBarStyle *InScrollBarStyle=nullptr, const bool bInPreventThrottling=false)
Create the child widgets that comprise the list.
void EndInertialScrolling (const bool bInShouldStopScrollNow=false)
Reset the inertial scroll velocity accumulated in the InertialScrollManager.
TSharedPtr< SWidget > GetGeneratedChildAt (int32 Index) const
TSharedPtr< SHeaderRow > GetHeaderRow () const
int32 GetNumGeneratedChildren () const
EVisibility GetScrollbarVisibility () const
virtual FVector2D GetScrollDistance () override
Gets the distance that user has scrolled into the control in normalized coordinates (0 - 1)
virtual FVector2D GetScrollDistanceRemaining () override
Gets the distance that user has left to scroll in the control before reaching the end in normalized coordinates (0 - 1)
float GetScrollOffset () const
Gets the scroll offset of this view (in items)
virtual TSharedRef< class SWidget > GetScrollWidget () override
Returns the typed SWidget that implements this interface.
bool IsPendingRefresh () const
Return true if there is currently a refresh pending, false otherwise.
bool IsRightClickScrolling () const
bool IsScrollbarNeeded () const
Returns true if scrolling is possible; false if the view is big enough to fit all the content.
bool IsScrolling () const
Returns whether the attached scrollbar is scrolling.
bool IsUserScrolling () const
virtual FCursorReply OnCursorQuery (const FGeometry &MyGeometry, const FPointerEvent &CursorEvent) const override
The system asks each widget under the mouse to provide a cursor.
virtual void OnFocusLost (const FFocusEvent &InFocusEvent) override
Called when this widget loses focus.
virtual FReply OnKeyDown (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent) override
Called after a key is pressed when this widget has focus (this event bubbles if not handled)
virtual FReply OnMouseButtonDoubleClick (const FGeometry &InMyGeometry, const FPointerEvent &InMouseEvent) override
Called when a mouse button is double clicked.
virtual FReply OnMouseButtonDown (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent) override
The system calls this method to notify the widget that a mouse button was pressed within it.
virtual FReply OnMouseButtonUp (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent) override
The system calls this method to notify the widget that a mouse button was release within it.
virtual void OnMouseCaptureLost (const FCaptureLostEvent &CaptureLostEvent) override
Called when this widget had captured the mouse, but that capture has been revoked for some reason.
virtual void OnMouseEnter (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent) override
The system will use this event to notify a widget that the cursor has entered it.
virtual void OnMouseLeave (const FPointerEvent &MouseEvent) override
The system will use this event to notify a widget that the cursor has left it.
virtual FReply OnMouseMove (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent) override
The system calls this method to notify the widget that a mouse moved within it.
virtual FReply OnMouseWheel (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent) override
Called when the mouse wheel is spun.
virtual int32 OnPaint (const FPaintArgs &Args, const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, FSlateWindowElementList &OutDrawElements, int32 LayerId, const FWidgetStyle &InWidgetStyle, bool bParentEnabled) const override
The widget should respond by populating the OutDrawElements array with FDrawElements that represent it and any of its children.
virtual FReply OnPreviewMouseButtonDown (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent) override
Just like OnMouseButtonDown, but tunnels instead of bubbling.
virtual FReply OnTouchEnded (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent) override
Called when a touchpad touch is ended (finger lifted)
virtual FReply OnTouchMoved (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent) override
Called when a touchpad touch is moved (finger moved)
virtual FReply OnTouchStarted (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent) override
Called when a touchpad touch is started (finger down)
virtual void RebuildList ()=0
Completely wipe existing widgets and fully regenerate them on next tick.
virtual void RequestListRefresh ()
Mark the list as dirty so that it will refresh its widgets on next tick.
void ScrollBar_OnUserScrolled (float InScrollOffsetFraction)
Invoked by the scrollbar when the user scrolls.
void ScrollToBottom ()
Scrolls the view to the bottom.
void ScrollToTop ()
Scrolls the view to the top.
void SetAllowOverscroll (EAllowOverscroll InAllowOverscroll)
Sets whether to permit overscroll on this list view.
void SetBackgroundBrush (const TAttribute< const FSlateBrush * > &InBackgroundBrush)
Sets the Background Brush.
void SetEnableTouchAnimatedScrolling (bool bInEnableTouchAnimatedScrolling)
Sets whether the list should lerp between scroll offsets or jump instantly between them with touch.
void SetFixedLineScrollOffset (TOptional< double > InFixedLineScrollOffset)
Sets the fixed offset in items to always apply to the top/left (depending on orientation) of the list.
void SetIsGamepadScrollingEnabled (bool bInIsGamepadScrollingEnabled)
Enables/disables being able to scroll via gamepad.
void SetIsPointerScrollingEnabled (bool bInIsPointerScrollingEnabled)
Enables/disables being able to scroll via pointer.
void SetIsRightClickScrollingEnabled (const bool bInEnableRightClickScrolling)
Enables/disables being able to scroll with the right mouse button.
void SetIsScrollAnimationEnabled (bool bInEnableScrollAnimation)
Sets whether the list should lerp between scroll offsets or jump instantly between them.
void SetIsTouchScrollingEnabled (const bool bInEnableTouchScrolling)
Enables/disables being able to scroll using touch input.
void SetItemHeight (TAttribute< float > Height)
Sets the item height.
void SetItemWidth (TAttribute< float > Width)
Sets the item width.
void SetScrollbarPadding (const FMargin &InScrollbarPadding)
void SetScrollbarVisibility (const EVisibility InVisibility)
void SetScrollingAnimationInterpolationSpeed (float InScrollingAnimationInterpolationSpeed)
Sets the speed of lerp between scroll offsets.
void SetScrollOffset (const float InScrollOffset)
Set the scroll offset of this view (in items)
void SetSelectItemOnNavigation (const bool bInSelectItemOnNavigation)
Sets whether items will be selected and focused or only focused when navigating to them.
void SetWheelScrollMultiplier (float NewWheelScrollMultiplier)
Sets the multiplier applied when wheel scrolling.
virtual bool SupportsKeyboardFocus () const override
Checks to see if this widget supports keyboard focus.
virtual void Tick (const FGeometry &AllottedGeometry, const double InCurrentTime, const float InDeltaTime) override
Ticks this widget with Geometry.
Public Member Functions inherited from SCompoundWidget
virtual FChildren * GetChildren () override
Returns the useful children (if any) of this widget.
virtual FSlateColor GetForegroundColor () const override
virtual void OnArrangeChildren (const FGeometry &AllottedGeometry, FArrangedChildren &ArrangedChildren) const override
Compute the Geometry of all the children and add populate the ArrangedChildren list with their values.
virtual void SetVisibility (TAttribute< EVisibility > InVisibility) override final
Public Member Functions inherited from SWidget
template<typename MetaDataType>
void AddMetadata (const TSharedRef< MetaDataType > &AddMe)
Add metadata to this widget.
virtual const FSlateInvalidationRoot * Advanced_AsInvalidationRoot () const
FORCEINLINE TSharedPtr< SWidget > Advanced_GetPaintParentWidget () const
virtual bool Advanced_IsInvalidationRoot () const
virtual bool Advanced_IsWindow () const
Is this widget derivative of SWindow.
void ArrangeChildren (const FGeometry &AllottedGeometry, FArrangedChildren &ArrangedChildren, bool bUpdateAttributes=false) const
Non-virtual entry point for arrange children.
void AssignParentWidget (TSharedPtr< SWidget > InParent)
FORCEINLINE void CacheVolatility ()
Recalculates volatility of the widget and caches the result.
FSlateRect CalculateCullingAndClippingRules (const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, bool &bClipToBounds, bool &bAlwaysClip, bool &bIntersectClipBounds) const
Calculates what if any clipping state changes need to happen when drawing this widget.
bool ConditionallyDetatchParentWidget (SWidget *InExpectedParent)
void EnableToolTipForceField (const bool bEnableForceField)
Sets whether this widget is a "tool tip force field".
FORCEINLINE void ForceVolatile (bool bForce)
Should this widget always appear as volatile for any layout caching host widget.
virtual FChildren * GetAllChildren ()
Returns the children (if any) of this widget that are used by the invalidation system.
template<typename MetaDataType>
TArray< TSharedRef< MetaDataType > > GetAllMetaData () const
Get all metadata of the type provided.
const FGeometry & GetCachedGeometry () const
bool GetCanTick () const
FORCEINLINE EWidgetClipping GetClipping () const
FName GetCreatedInLocation () const
FORCEINLINE FMargin GetCullingBoundsExtension () const
const TOptional< FSlateClippingState > & GetCurrentClippingState () const
Returns the clipping state to clip this widget against its parent.
UE::Slate::FDeprecateVector2DResult GetDesiredSize () const
virtual FSlateColor GetDisabledForegroundColor () const
EFlowDirectionPreference GetFlowDirectionPreference () const
Gets the desired flow direction for the layout.
template<typename MetaDataType>
TSharedPtr< MetaDataType > GetMetaData () const
Get the metadata of the type provided.
const FGeometry & GetPaintSpaceGeometry () const
Gets the last geometry used to Tick the widget.
FORCEINLINE TSharedPtr< SWidget > GetParentWidget () const
const FSlateWidgetPersistentState & GetPersistentState () const
FORCEINLINE EWidgetPixelSnapping GetPixelSnapping () const
const FWidgetProxyHandle GetProxyHandle () const
virtual FString GetReadableLocation () const
virtual float GetRelativeLayoutScale (const int32 ChildIndex, float LayoutScaleMultiplier) const
What is the Child's scale relative to this widget.
FORCEINLINE float GetRenderOpacity () const
FORCEINLINE const TOptional< FSlateRenderTransform > & GetRenderTransform () const
FORCEINLINE UE::Slate::FDeprecateVector2DResult GetRenderTransformPivot () const
FORCEINLINE UE::Slate::FDeprecateVector2DResult GetRenderTransformPivotWithRespectToFlowDirection () const
FORCEINLINE TOptional< FSlateRenderTransform > GetRenderTransformWithRespectToFlowDirection () const
FORCEINLINE TStatId GetStatID (bool bForDeferredUse=false) const
virtual FName GetTag () const
const FGeometry & GetTickSpaceGeometry () const
Gets the last geometry used to Tick the widget.
virtual TSharedPtr< IToolTip > GetToolTip ()
FName GetType () const
FString GetTypeAsString () const
FORCEINLINE EVisibility GetVisibility () const
virtual EWindowZone::Type GetWindowZoneOverride () const
Called when the mouse is moved over the widget's window, to determine if we should report whether OS-specific features should be active at this location (such as a title bar grip, system menu, etc.) Usually you should not need to override this function.
bool HasActiveTimers () const
Does this widget have any active timers?
bool HasAnyUpdateFlags (EWidgetUpdateFlags FlagsToCheck) const
TOptional< EFocusCause > HasAnyUserFocus () const
Gets whether or not any users have this widget focused, and if so the type of focus (first one found).
bool HasAnyUserFocusOrFocusedDescendants () const
bool HasFocusedDescendants () const
virtual bool HasKeyboardFocus () const
Checks to see if this widget currently has the keyboard focus.
bool HasMouseCapture () const
Checks to see if this widget is the current mouse captor.
bool HasMouseCaptureByUser (int32 UserIndex, TOptional< int32 > PointerIndex=TOptional< int32 >()) const
Checks to see if this widget has mouse capture from the provided user.
bool HasRegisteredSlateAttribute () const
bool HasToolTipForceField () const
TOptional< EFocusCause > HasUserFocus (int32 UserIndex) const
Gets whether or not the specified users has this widget focused, and if so the type of focus.
bool HasUserFocusedDescendants (int32 UserIndex) const
Gets whether or not the specified users has this widget or any descendant focused.
void Invalidate (EInvalidateWidgetReason InvalidateReason)
Invalidates the widget from the view of a layout caching widget that may own this widget.
bool IsAttributesUpdatesEnabled () const
bool IsDirectlyHovered () const
FORCEINLINE bool IsEnabled () const
bool IsHovered () const
virtual bool IsInteractable () const
FORCEINLINE bool IsParentValid () const
FORCEINLINE bool IsVolatile () const
Whether or not a widget is volatile and will update every frame without being invalidated.
FORCEINLINE bool IsVolatileIndirectly () const
This widget is volatile because its parent or some ancestor is volatile.
void MarkPrepassAsDirty ()
In fast path, if the widget is mark, do a full Prepass on its next update to calculate it's desired size.
bool NeedsPrepass () const
virtual FReply OnAnalogValueChanged (const FGeometry &MyGeometry, const FAnalogInputEvent &InAnalogInputEvent)
Called when an analog value changes on a button that supports analog.
virtual FReply OnDragDetected (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Called when Slate detects that a widget started to be dragged.
virtual void OnDragEnter (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called during drag and drop when the drag enters a widget.
virtual void OnDragLeave (const FDragDropEvent &DragDropEvent)
Called during drag and drop when the drag leaves a widget.
virtual FReply OnDragOver (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called during drag and drop when the the mouse is being dragged over a widget.
virtual FReply OnDrop (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called when the user is dropping something onto a widget; terminates drag and drop.
virtual void OnFinishedKeyInput ()
All the key (keyboard, gamepay, joystick, etc.) input from this frame has been routed.
virtual void OnFinishedPointerInput ()
All the pointer (mouse, touch, stylus, etc.) events from this frame have been routed.
virtual void OnFocusChanging (const FWeakWidgetPath &PreviousFocusPath, const FWidgetPath &NewWidgetPath, const FFocusEvent &InFocusEvent)
Called whenever a focus path is changing on all the widgets within the old and new focus paths.
virtual FReply OnFocusReceived (const FGeometry &MyGeometry, const FFocusEvent &InFocusEvent)
Called when focus is given to this widget.
virtual FReply OnKeyChar (const FGeometry &MyGeometry, const FCharacterEvent &InCharacterEvent)
Called after a character is entered while this widget has keyboard focus.
virtual FReply OnKeyUp (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
Called after a key is released when this widget has focus.
virtual TOptional< TSharedRef< SWidget > > OnMapCursor (const FCursorReply &CursorReply) const
After OnCursorQuery has specified a cursor type the system asks each widget under the mouse to map that cursor to a widget.
virtual FReply OnMotionDetected (const FGeometry &MyGeometry, const FMotionEvent &InMotionEvent)
Called when motion is detected (controller or device) e.g.
virtual FNavigationReply OnNavigation (const FGeometry &MyGeometry, const FNavigationEvent &InNavigationEvent)
Called when navigation is requested e.g.
virtual FReply OnPreviewKeyDown (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
Called after a key is pressed when this widget or a child of this widget has focus If a widget handles this event, OnKeyDown will not be passed to the focused widget.
virtual FPopupMethodReply OnQueryPopupMethod () const
Popups can manifest in a NEW OS WINDOW or via an OVERLAY in an existing window.
virtual TOptional< bool > OnQueryShowFocus (const EFocusCause InFocusCause) const
Called to determine if we should render the focus brush.
virtual void OnToolTipClosing ()
Called when a tooltip displayed from this widget is being closed.
virtual FReply OnTouchFirstMove (const FGeometry &MyGeometry, const FPointerEvent &TouchEvent)
Called when a touchpad touch first moves after TouchStarted.
virtual FReply OnTouchForceChanged (const FGeometry &MyGeometry, const FPointerEvent &TouchEvent)
Called when a touchpad touch force changes.
virtual FReply OnTouchGesture (const FGeometry &MyGeometry, const FPointerEvent &GestureEvent)
Called when the user performs a gesture on trackpad.
virtual TSharedPtr< FPopupLayer > OnVisualizePopup (const TSharedRef< SWidget > &PopupContent)
Visualize a new pop-up if possible.
virtual bool OnVisualizeTooltip (const TSharedPtr< SWidget > &TooltipContent)
Called when Slate wants to visualize tooltip.
int32 Paint (const FPaintArgs &Args, const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, FSlateWindowElementList &OutDrawElements, int32 LayerId, const FWidgetStyle &InWidgetStyle, bool bParentEnabled) const
Called to tell a widget to paint itself (and it's children).
TSharedRef< FActiveTimerHandle > RegisterActiveTimer (float TickPeriod, FWidgetActiveTimerDelegate TickFunction)
Registers an "active timer" delegate that will execute at some regular interval.
template<typename MetaDataType>
int32 RemoveMetaData (const TSharedRef< MetaDataType > &RemoveMe)
Remove metadata to this widget.
void SetCanTick (bool bInCanTick)
void SetClipping (EWidgetClipping InClipping)
Sets the clipping to bounds rules for this widget.
FORCEINLINE void SetCullingBoundsExtension (const FMargin &InCullingBoundsExtension)
Sets an additional culling padding that is added to a widget to give more leeway when culling widgets.
void SetCursor (const TAttribute< TOptional< EMouseCursor::Type > > &InCursor)
Set the cursor that should appear when this widget is hovered.
void SetEnabled (TAttribute< bool > InEnabledState)
Sets the enabled state of this widget.
void SetFlowDirectionPreference (EFlowDirectionPreference InFlowDirectionPreference)
Sets how content should flow in this panel, based on the current culture.
void SetOnMouseButtonDown (FPointerEventHandler EventHandler)
See OnMouseButtonDown event.
void SetOnMouseButtonUp (FPointerEventHandler EventHandler)
See OnMouseButtonUp event.
void SetOnMouseDoubleClick (FPointerEventHandler EventHandler)
See OnMouseDoubleClick event.
void SetOnMouseEnter (FNoReplyPointerEventHandler EventHandler)
See OnMouseEnter event.
void SetOnMouseLeave (FSimpleNoReplyPointerEventHandler EventHandler)
See OnMouseLeave event.
void SetOnMouseMove (FPointerEventHandler EventHandler)
See OnMouseMove event.
void SetPixelSnapping (EWidgetPixelSnapping InPixelSnappingMethod)
Sets the pixel snapping method for this widget.
FORCEINLINE void SetRenderOpacity (float InRenderOpacity)
FORCEINLINE void SetRenderTransform (TAttribute< TOptional< FSlateRenderTransform > > InTransform)
FORCEINLINE void SetRenderTransformPivot (TAttribute< FVector2D > InTransformPivot)
FORCEINLINE void SetTag (FName InTag)
void SetToolTip (const TAttribute< TSharedPtr< IToolTip > > &InToolTip)
Set the tool tip that should appear when this widget is hovered.
void SetToolTipText (const FText &InToolTipText)
Set the tool tip that should appear when this widget is hovered.
void SetToolTipText (const TAttribute< FText > &ToolTipText)
Set the tool tip that should appear when this widget is hovered.
FORCEINLINE bool ShouldInvalidatePrepassDueToVolatility ()
void SlatePrepass ()
DEPRECATED version of SlatePrepass that assumes no scaling beyond AppScale.
void SlatePrepass (float InLayoutScaleMultiplier)
Descends to leaf-most widgets in the hierarchy and gathers desired sizes on the way up.
virtual FString ToString () const
virtual TOptional< FVirtualPointerPosition > TranslateMouseCoordinateForCustomHitTestChild (const SWidget &ChildWidget, const FGeometry &MyGeometry, const FVector2D ScreenSpaceMouseCoordinate, const FVector2D LastScreenSpaceMouseCoordinate) const
void UnRegisterActiveTimer (const TSharedRef< FActiveTimerHandle > &ActiveTimerHandle)
Unregisters an active timer handle.
virtual bool ValidatePathToChild (SWidget *InChild)
Public Member Functions inherited from FSlateControlledConstruction
FSlateControlledConstruction ()=default
virtual ~FSlateControlledConstruction ()=default
virtual const FSlateWidgetClassData & GetWidgetClass () const =0
void operator delete (void *mem)
Public Member Functions inherited from TSharedFromThis< SWidget >
TSharedRef< SWidget, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< SWidget, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Public Member Functions inherited from IScrollableWidget
virtual ~IScrollableWidget ()
Data Fields
const ETableViewMode::Type TableViewMode
Is this list backing a tree or just a standalone list.
Protected Types
enum class EScrollIntoViewResult { Success , Deferred , Failure }
Protected Member Functions
STableViewBase (ETableViewMode::Type InTableViewMode)
virtual ~STableViewBase ()
void AppendPinnedWidget (const TSharedRef< SWidget > &WidgetToAppend)
Add a WidgetToAppend to the bottom of the pinned view.
void AppendWidget (const TSharedRef< ITableRow > &WidgetToAppend)
Add a WidgetToAppend to the bottom of the view.
bool CanUseInertialScroll (float ScrollAmount) const
Check whether the current state of the table warrants inertial scroll by the specified amount.
void ClearPinnedWidgets ()
Remove all the pinned widgets from the view.
void ClearWidgets ()
Remove all the widgets from the view.
EActiveTimerReturnType EnsureTickToRefresh (double InCurrentTime, float InDeltaTime)
One-off active timer to refresh the contents of the table as needed.
int32 FindChildUnderPosition (FArrangedChildren &ArrangedChildren, const FVector2D &ArrangedSpacePosition) const
Util function to find the child index under the given position.
const FChildren * GetConstructedTableItems () const
virtual float GetFirstLineScrollOffset () const
Get the offset of the first list item.
float GetItemHeight () const
Get the uniform item height that is enforced by ListViews.
UE::Slate::FDeprecateVector2DResult GetItemSize () const
Get the uniform item.
float GetItemWidth () const
Get the uniform item width.
virtual int32 GetNumItemsBeingObserved () const =0
virtual int32 GetNumItemsPerLine () const
Get the number of items that can fit in the view along the line axis (orthogonal to the scroll axis) before creating a new line.
virtual float GetNumLiveWidgets () const
int32 GetNumPinnedItems () const
float GetScrollRateInItems () const
Get the scroll rate in items that best approximates a constant physical scroll rate.
double GetTargetScrollOffset () const
Returns the "true" scroll offset where the list will ultimately settle (and may already be).
void InsertPinnedWidget (const TSharedRef< SWidget > &WidgetToInset)
Insert WidgetToInsert at the top of the pinned view.
void InsertWidget (const TSharedRef< ITableRow > &WidgetToInset)
Insert WidgetToInsert at the top of the view.
void NavigateToWidget (const uint32 UserIndex, const TSharedPtr< SWidget > &NavigationDestination, ENavigationSource NavigationSource=ENavigationSource::FocusedWidget) const
Util Function so templates classes don't need to include SlateApplication.
virtual void NotifyFinishedScrolling ()=0
Called at the end of a Tick when.
virtual void NotifyItemScrolledIntoView ()=0
Called when an item has entered the visible geometry to check to see if the ItemScrolledIntoView delegate should be fired.
virtual void OnClippingChanged () override
Passing over the clipping to SListPanel.
virtual void OnRightMouseButtonDown (const FPointerEvent &MouseEvent)
virtual void OnRightMouseButtonUp (const FPointerEvent &MouseEvent)
Opens a context menu as the result of a right click if OnContextMenuOpening is bound and we are not right click scrolling.
virtual FReGenerateResults ReGenerateItems (const FGeometry &MyGeometry)=0
Update generate Widgets for Items as needed and clean up any Widgets that are no longer needed.
void RequestLayoutRefresh ()
Internal request for a layout update on the next tick (i.e.
virtual float ScrollBy (const FGeometry &MyGeometry, float ScrollByAmount, EAllowOverscroll InAllowOverscroll)
Scroll the list view by some number of screen units.
virtual EScrollIntoViewResult ScrollIntoView (const FGeometry &ListViewGeometry)=0
If there is a pending request to scroll an item into view, do so.
virtual float ScrollTo (float InScrollOffset)
Scroll the view to an offset and resets the inertial scroll velocity.
UE_DEPRECATED (5.5, "The Pinned items visibility is no more an attribute.") 1 EVisibility GetPinnedItemsVisiblity() const
EActiveTimerReturnType UpdateInertialScroll (double InCurrentTime, float InDeltaTime)
Active timer to update the inertial scroll.
virtual void UpdateSelectionSet ()=0
Remove any items that are no longer in the list from the selection set.
Protected Member Functions inherited from SCompoundWidget
SCompoundWidget ()
Disallow public construction.
virtual ~SCompoundWidget ()
virtual FVector2D ComputeDesiredSize (float) const override
Compute the ideal size necessary to display this widget.
TSlateAttributeRef< FLinearColor > GetColorAndOpacityAttribute () const
TSlateAttributeRef< FVector2D > GetContentScaleAttribute () const
TSlateAttributeRef< FSlateColor > GetForegroundColorAttribute () const
Protected Member Functions inherited from SWidget
SWidget ()
Hidden default constructor.
virtual ~SWidget ()
Dtor ensures that active timer handles are UnRegistered with the SlateApplication.
FORCEINLINE bool Advanced_InvalidateVolatility ()
Recalculates and caches volatility and returns 'true' if the volatility changed.
virtual void CacheDesiredSize (float InLayoutScaleMultiplier)
The system calls this method.
EFlowDirection ComputeFlowDirection () const
Establishes a new flow direction potentially, if this widget has a particular preference for it and all its children.
virtual bool CustomPrepass (float LayoutScaleMultiplier)
bool FindChildGeometries (const FGeometry &MyGeometry, const TSet< TSharedRef< SWidget > > &WidgetsToFind, TMap< TSharedRef< SWidget >, FArrangedWidget > &OutResult) const
Find the geometry of a descendant widget.
void FindChildGeometries_Helper (const FGeometry &MyGeometry, const TSet< TSharedRef< SWidget > > &WidgetsToFind, TMap< TSharedRef< SWidget >, FArrangedWidget > &OutResult) const
Actual implementation of FindChildGeometries.
FGeometry FindChildGeometry (const FGeometry &MyGeometry, TSharedRef< SWidget > WidgetToFind) const
Find the geometry of a descendant widget.
virtual TOptional< EMouseCursor::Type > GetCursor () const
The cursor to show when the mouse is hovering over this widget.
TSlateAttributeRef< bool > GetEnabledStateAttribute () const
virtual const FSlateBrush * GetFocusBrush () const
TSlateAttributeRef< bool > GetHoveredAttribute () const
float GetPrepassLayoutScaleMultiplier () const
TSlateAttributeRef< TOptional< FSlateRenderTransform > > GetRenderTransformAttribute () const
TSlateAttributeRef< FVector2D > GetRenderTransformPivotAttribute () const
TSlateAttributeRef< EVisibility > GetVisibilityAttribute () const
void InvalidateChildRemovedFromTree (SWidget &Child)
Called when a child is removed from the tree parent's widget tree either by removing it from a slot.
FORCEINLINE bool IsChildWidgetCulled (const FSlateRect &, const FArrangedWidget &) const
bool IsConstructed () const
Is the widget construction completed (did we called and returned from the Construct() function)
void Prepass_ChildLoop (float InLayoutScaleMultiplier, FChildren *MyChildren)
template<typename TargetValueType, typename SourceValueType>
bool SetAttribute (TAttribute< TargetValueType > &TargetValue, const TAttribute< SourceValueType > &SourceValue, EInvalidateWidgetReason BaseInvalidationReason)
Performs the attribute assignment and invalidates the widget minimally based on what actually changed.
void SetDebugInfo (const ANSICHAR *InType, const ANSICHAR *InFile, int32 OnLine, size_t InAllocSize)
Used by Slate to set the runtime debug info about this widget.
void SetHover (TAttribute< bool > InHovered)
Set the hover state.
void SetVolatilePrepass (bool bVolatile)
bool ShouldBeEnabled (bool InParentEnabled) const
Determines if this widget should be enabled.
void SWidgetConstruct (const FSlateBaseNamedArgs &Args)
Construct a SWidget based on initial parameters.
Protected Member Functions inherited from TSharedFromThis< SWidget >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Protected Attributes
EAllowOverscroll AllowOverscroll
Whether to permit overscroll on this list view.
float AmountScrolledWhileRightMouseDown
How much we scrolled while the rmb has been held.
FInvalidatableBrushAttribute BackgroundBrush
Brush resource representing the background area of the view.
bool bEnableAnimatedScrolling = false
True to lerp smoothly between offsets when the desired scroll offset changes.
bool bEnableRightClickScrolling = true
True to allow right click drag scrolling.
bool bEnableTouchAnimatedScrolling = false
True to lerp smoothly between offsets when the desired scroll offset changes with touch.
bool bEnableTouchScrolling = true
True to allow scrolling by using touch input.
bool bIsGamepadScrollingEnabled = true
Whether the list is allowed to scroll via gamepad.
bool bIsPointerScrollingEnabled = true
Whether the list is allowed to scroll via cursor.
bool bIsScrollingActiveTimerRegistered
Whether the active timer to update the inertial scrolling is currently registered.
bool bSelectItemOnNavigation = true
If true, items will be "selected" (in addition to focused) when navigating to them.
bool bShowSoftwareCursor
Whether the software cursor should be drawn in the viewport.
bool bStartedTouchInteraction
Did the user start an interaction in this list?
bool bWasAtEndOfList
Last time we scrolled, did we end up at the end of the list.
EConsumeMouseWheel ConsumeMouseWheel
How we should handle scrolling with the mouse wheel.
double CurrentScrollOffset = 0.
The currently displayed scroll offset from the beginning of the list in items.
double DesiredScrollOffset = 0.
The raw desired scroll offset from the beginning of the list in items.
TOptional< double > FixedLineScrollOffset
The fixed offset in lines to always apply to the top/left (depending on orientation) of the list.
TSharedPtr< SHeaderRow > HeaderRow
Column headers that describe which columns this list shows.
FInertialScrollManager InertialScrollManager
Helper object to manage inertial scrolling.
TSharedPtr< SListPanel > ItemsPanel
The panel which holds the visible widgets in this list.
FReGenerateResults LastGenerateResults
Information about the widgets we generated during the last regenerate pass.
FOnContextMenuOpening OnContextMenuOpening
Delegate to invoke when the context menu should be opening.
FSimpleDelegate OnItemsRebuilt
Delegate to invoke after the children have been regenerated.
FOnTableViewScrolled OnTableViewScrolled
Delegate to call when the table view is scrolled.
EOrientation Orientation = Orient_Vertical
The layout and scroll orientation of the list.
FOverscroll Overscroll
FGeometry PanelGeometryLastTick
What the list's geometry was the last time a refresh occurred.
TSharedPtr< SListPanel > PinnedItemsPanel
The panel which holds the pinned widgets in this list.
FVector2f PressedScreenSpacePosition
The location in screenspace the view was pressed.
TSharedPtr< SScrollBar > ScrollBar
The scroll bar widget.
FMargin ScrollBarSlotPadding
Padding to the scrollbox.
float ScrollingAnimationInterpolationSpeed = 12.f
The speed of interpolation for the scrolling animation.
TAttribute< ESelectionMode::Type > SelectionMode
The selection mode that this tree/list is in.
FVector2f SoftwareCursorPosition
The current position of the software cursor.
float TickScrollDelta
The amount we have scrolled this tick cycle.
float WheelScrollMultiplier
How much to scroll when using mouse wheel.
Protected Attributes inherited from SCompoundWidget
FCompoundWidgetOneChildSlot ChildSlot
The slot that contains this widget's descendants.
Protected Attributes inherited from SWidget
uint8 bCanHaveChildren: 1
Can the widget ever support children?
uint8 bCanSupportFocus: 1
Can the widget ever support keyboard focus.
uint8 bClippingProxy: 1
Some widgets might be a complex hierarchy of child widgets you never see.
uint8 bHasCustomPrepass: 1
uint8 bHasRelativeLayoutScale: 1
uint8 bVolatilityAlwaysInvalidatesPrepass: 1
if this widget should always invalidate the prepass step when volatile
EWidgetClipping Clipping
Set to true if all content of the widget should clip to the bounds of this widget.
FMargin CullingBoundsExtension
Can be used to enlarge the culling bounds of this widget (pre-intersection), this can be useful if you've got children that you know are using rendering transforms to render outside their standard bounds, if that happens it's possible the parent might be culled before the descendant widget is entirely off screen.
EWidgetPixelSnapping PixelSnappingMethod
When set to EPixelSnappingMethod::SnapToPixel, the widget is drawn at the nearest pixel.
float RenderOpacity
The opacity of the widget.
Private Member Functions
bool ShouldScrollToFixedLineOffsetAtZeroVelocity () const
Whether or not the view should scroll to a fixed line offset if the scroll velocity is 0.
Private Attributes
union {
SVerticalBox::FSlot * HorizontalScrollBarSlot
SHorizontalBox::FSlot * VerticalScrollBarSlot
};
bool bIsInertialScroll = false
Whether or not the current scroll is inertial.
bool bItemsNeedRefresh = false
When true, a refresh should occur the next tick.
Additional Inherited Members
Static Public Member Functions inherited from FSlateControlledConstruction
static const FSlateWidgetClassData & StaticWidgetClass ()
Static Protected Member Functions inherited from SWidget
static TAttribute< EVisibility > AccessWidgetVisibilityAttribute (const TSharedRef< SWidget > &Widget)
Protected static helper to allow widgets to access the visibility attribute of other widgets directly.
static int32 FindChildUnderMouse (const FArrangedChildren &Children, const FPointerEvent &MouseEvent)
static int32 FindChildUnderPosition (const FArrangedChildren &Children, const UE::Slate::FDeprecateVector2DParameter &ArrangedSpacePosition)
Static Protected Member Functions inherited from TSharedFromThis< SWidget >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
Contains ListView functionality that does not depend on the type of data being observed by the ListView.
Definition at line 107 of file STableViewBase.h.
Member Enumeration Documentation
EScrollIntoViewResult
enum class STableViewBase::EScrollIntoViewResult strong protected
Enumerator
Success
The function scrolled an item (if set) into view (or the item was already in view)
Deferred
The function did not have enough data to scroll the given item into view, so it should be deferred until the next Tick.
Failure
The function failed to scroll to the specified item.
Definition at line 400 of file STableViewBase.h.
Constructor & Destructor Documentation
STableViewBase()
STableViewBase::STableViewBase (ETableViewMode::Type InTableViewMode) protected
Referenced by SListView< TSharedPtr< FString > >::SListView().
~STableViewBase()
virtual STableViewBase::~STableViewBase () protected virtual
Member Function Documentation
AddScrollOffset()
void STableViewBase::AddScrollOffset (const float InScrollOffsetDelta, bool RefreshList = false)
Add the scroll offset of this view (in items)
AppendPinnedWidget()
void STableViewBase::AppendPinnedWidget (const TSharedRef< SWidget > & WidgetToAppend) protected
Add a WidgetToAppend to the bottom of the pinned view.
Referenced by SListView< TSharedPtr< FString > >::GeneratePinnedWidgetForItem().
AppendWidget()
void STableViewBase::AppendWidget (const TSharedRef< ITableRow > & WidgetToAppend) protected
Add a WidgetToAppend to the bottom of the view.
Referenced by SListView< TSharedPtr< FString > >::GenerateWidgetForItem().
CanUseInertialScroll()
bool STableViewBase::CanUseInertialScroll (float ScrollAmount) const protected
Check whether the current state of the table warrants inertial scroll by the specified amount.
ClearPinnedWidgets()
void STableViewBase::ClearPinnedWidgets () protected
Remove all the pinned widgets from the view.
Referenced by STreeView< FRigVMSearchResult >::ReGenerateItems(), and SListView< TSharedPtr< FString > >::ReGeneratePinnedItems().
ClearWidgets()
void STableViewBase::ClearWidgets () protected
Remove all the widgets from the view.
Referenced by SListView< TSharedPtr< FString > >::ReGenerateItems(), STileView< ItemType >::ReGenerateItems(), and SListView< TSharedPtr< FString > >::SetItemsSource().
ComputeVolatility()
virtual bool STableViewBase::ComputeVolatility () const override virtual
Recomputes the volatility of the widget.
If you have additional state you automatically want to make the widget volatile, you should sample that information here.
Reimplemented from SWidget.
ConstructChildren()
void STableViewBase::ConstructChildren (const TAttribute< float > & InItemWidth, const TAttribute< float > & InItemHeight, const TAttribute< EListItemAlignment > & InItemAlignment, const TSharedPtr< SHeaderRow > & InHeaderRow, const TSharedPtr< SScrollBar > & InScrollBar, EOrientation InScrollOrientation, const FOnTableViewScrolled & InOnTableViewScrolled, const FScrollBarStyle * InScrollBarStyle = nullptr, const bool bInPreventThrottling = false)
Create the child widgets that comprise the list.
Referenced by STileView< ItemType >::SLATE_END_ARGS(), SListView< TSharedPtr< FString > >::SLATE_EVENT(), and STreeView< FRigVMSearchResult >::SLATE_EVENT().
EndInertialScrolling()
void STableViewBase::EndInertialScrolling (const bool bInShouldStopScrollNow = false)
Reset the inertial scroll velocity accumulated in the InertialScrollManager.
Parameters
bInShouldStopScrollNow true implies the scroll will stop instantly, else the list will scroll until any accumulated scroll offset is cleared.
Referenced by STileView< ItemType >::ScrollIntoView().
EnsureTickToRefresh()
EActiveTimerReturnType STableViewBase::EnsureTickToRefresh (double InCurrentTime, float InDeltaTime) protected
One-off active timer to refresh the contents of the table as needed.
FindChildUnderPosition()
int32 STableViewBase::FindChildUnderPosition (FArrangedChildren & ArrangedChildren, const FVector2D & ArrangedSpacePosition) const protected
Util function to find the child index under the given position.
GetConstructedTableItems()
const FChildren * STableViewBase::GetConstructedTableItems () const protected
GetFirstLineScrollOffset()
virtual float STableViewBase::GetFirstLineScrollOffset () const protected virtual
Get the offset of the first list item.
GetGeneratedChildAt()
TSharedPtr< SWidget > STableViewBase::GetGeneratedChildAt (int32 Index) const
Returns
The generated row widget at the specified index if it exists (NULL otherwise).
GetHeaderRow()
TSharedPtr< SHeaderRow > STableViewBase::GetHeaderRow () const
GetItemHeight()
float STableViewBase::GetItemHeight () const protected
Get the uniform item height that is enforced by ListViews.
Referenced by STileView< ItemType >::GetTileDimensions().
GetItemSize()
UE::Slate::FDeprecateVector2DResult STableViewBase::GetItemSize () const protected
Get the uniform item.
GetItemWidth()
float STableViewBase::GetItemWidth () const protected
Get the uniform item width.
Referenced by STileView< ItemType >::GetTileDimensions().
GetNumGeneratedChildren()
int32 STableViewBase::GetNumGeneratedChildren () const
Returns
The number of Widgets we currently have generated.
GetNumItemsBeingObserved()
virtual int32 STableViewBase::GetNumItemsBeingObserved () const protected pure virtual
Returns
how many items there are in the TArray being observed
Implemented in SListView< ItemType >, SListView< FCurveEditorTreeItemID >, SListView< FName >, SListView< FSCSEditorTreeNodePtrType >, SListView< ListType >, SListView< OptionType >, SListView< TSharedPtr< class FComponentClassComboEntry > >, SListView< TSharedPtr< class FDebugLineItem > >, SListView< TSharedPtr< class FFilterConfiguratorNode > >, SListView< TSharedPtr< class FTableTreeNode > >, SListView< TSharedPtr< const FCollectionSpreadSheetItem > >, SListView< TSharedPtr< const FSelectionViewItem > >, SListView< TSharedPtr< EAudioOscilloscopeTriggerMode > >, SListView< TSharedPtr< ECSVImportType > >, SListView< TSharedPtr< ERichCurveInterpMode > >, SListView< TSharedPtr< FAnimAttributeEntry > >, SListView< TSharedPtr< FBlueprintDebugObjectInstance > >, SListView< TSharedPtr< FBlueprintDifferenceTreeEntry > >, SListView< TSharedPtr< FDataflowOutlinerTreeItem > >, SListView< TSharedPtr< FDisplayedBoneMappingInfo > >, SListView< TSharedPtr< FGeometryCollectionFacesTreeItem > >, SListView< TSharedPtr< FGeometryCollectionVerticesTreeItem > >, SListView< TSharedPtr< FGraphActionNode > >, SListView< TSharedPtr< FName > >, SListView< TSharedPtr< FPendingDelete > >, SListView< TSharedPtr< FPendingPrivateAsset > >, SListView< TSharedPtr< FRigStackEntry > >, SListView< TSharedPtr< FRigVMDebugObjectInstance > >, SListView< TSharedPtr< FRigVMEditorGraphExplorerTreeElement > >, SListView< TSharedPtr< FRigVMStringWithTag > >, SListView< TSharedPtr< FSequencerFilterSuggestionListEntryBase > >, SListView< TSharedPtr< FString > >, SListView< TSharedPtr< FText > >, SListView< TSharedPtr< int32 > >, SListView< TSharedPtr< SBlueprintNamespaceEntry::FPathTreeNodeItem > >, SListView< TSharedPtr< SBoneTreeMenu::FBoneNameInfo > >, SListView< TSharedPtr< SReadOnlyHierarchyView::FItem > >, SListView< TSharedPtr< SRigVMNodeLayoutWidget::FNodeLayoutRow > >, SListView< TSharedPtr< SRigVMVariantWidget::FVariantTreeRowInfo > >, SListView< TSharedPtr< UE::Insights::FFilter > >, SListView< TSharedPtr< UE::Insights::FFilterGroupOperator > >, SListView< TSharedPtr< UE::Insights::IFilterOperator > >, SListView< TSharedRef< FRigVMTreeNode > >, SListView< TSharedRef< UE::Insights::ITableTreeViewPreset > >, SListView< TWeakPtr< FViewModel > >, SListView< TWeakViewModelPtr< IOutlinerExtension > >, SListView< UObject * >, and STileView< ItemType >.
GetNumItemsPerLine()
virtual int32 STableViewBase::GetNumItemsPerLine () const protected virtual
Get the number of items that can fit in the view along the line axis (orthogonal to the scroll axis) before creating a new line.
Default is 1, but may be more in subclasses (like STileView)
Reimplemented in STileView< ItemType >.
Referenced by SListView< TSharedPtr< FString > >::OnKeyDown_Internal(), and SListView< TSharedPtr< FString > >::OnNavigation().
GetNumLiveWidgets()
virtual float STableViewBase::GetNumLiveWidgets () const protected virtual
Returns
the number of items that can fit on the screen
Referenced by SListView< TSharedPtr< FString > >::OnKeyDown_Internal(), and STileView< ItemType >::ScrollIntoView().
GetNumPinnedItems()
int32 STableViewBase::GetNumPinnedItems () const protected
Returns
how many pinned items are in the table
Referenced by STreeView< FRigVMSearchResult >::PopulatePinnedItems().
GetScrollbarVisibility()
EVisibility STableViewBase::GetScrollbarVisibility () const
GetScrollDistance()
virtual FVector2D STableViewBase::GetScrollDistance () override virtual
Gets the distance that user has scrolled into the control in normalized coordinates (0 - 1)
Implements IScrollableWidget.
GetScrollDistanceRemaining()
virtual FVector2D STableViewBase::GetScrollDistanceRemaining () override virtual
Gets the distance that user has left to scroll in the control before reaching the end in normalized coordinates (0 - 1)
Implements IScrollableWidget.
GetScrollOffset()
float STableViewBase::GetScrollOffset () const
Gets the scroll offset of this view (in items)
GetScrollRateInItems()
float STableViewBase::GetScrollRateInItems () const protected
Get the scroll rate in items that best approximates a constant physical scroll rate.
GetScrollWidget()
virtual TSharedRef< class SWidget > STableViewBase::GetScrollWidget () override virtual
Returns the typed SWidget that implements this interface.
Implements IScrollableWidget.
GetTargetScrollOffset()
double STableViewBase::GetTargetScrollOffset () const protected
Returns the "true" scroll offset where the list will ultimately settle (and may already be).
Referenced by STileView< ItemType >::ScrollIntoView().
InsertPinnedWidget()
void STableViewBase::InsertPinnedWidget (const TSharedRef< SWidget > & WidgetToInset) protected
Insert WidgetToInsert at the top of the pinned view.
InsertWidget()
void STableViewBase::InsertWidget (const TSharedRef< ITableRow > & WidgetToInset) protected
Insert WidgetToInsert at the top of the view.
Referenced by SListView< TSharedPtr< FString > >::GenerateWidgetForItem().
IsPendingRefresh()
bool STableViewBase::IsPendingRefresh () const
Return true if there is currently a refresh pending, false otherwise.
Referenced by SListView< TSharedPtr< FString > >::Private_IsPendingRefresh(), and STileView< ItemType >::ScrollIntoView().
IsRightClickScrolling()
bool STableViewBase::IsRightClickScrolling () const
Returns
Returns true if the user is currently interactively scrolling the view by holding the right mouse button and dragging.
Referenced by FArguments< ItemType >::OnMouseButtonUp().
IsScrollbarNeeded()
bool STableViewBase::IsScrollbarNeeded () const
Returns true if scrolling is possible; false if the view is big enough to fit all the content.
IsScrolling()
bool STableViewBase::IsScrolling () const
Returns whether the attached scrollbar is scrolling.
IsUserScrolling()
bool STableViewBase::IsUserScrolling () const
Returns
Returns true if the user is currently interactively scrolling the view by holding either mouse button and dragging.
NavigateToWidget()
void STableViewBase::NavigateToWidget (const uint32 UserIndex, const TSharedPtr< SWidget > & NavigationDestination, ENavigationSource NavigationSource = ENavigationSource::FocusedWidget) const protected
Util Function so templates classes don't need to include SlateApplication.
NotifyFinishedScrolling()
virtual void STableViewBase::NotifyFinishedScrolling () protected pure virtual
Called at the end of a Tick when.
CurrentScrollOffset == TargetScrollOffset
the user is not scrolling
the table view is not scrolling from an overscroll position
NotifyItemScrolledIntoView()
virtual void STableViewBase::NotifyItemScrolledIntoView () protected pure virtual
Called when an item has entered the visible geometry to check to see if the ItemScrolledIntoView delegate should be fired.
OnClippingChanged()
virtual void STableViewBase::OnClippingChanged () override protected virtual
Passing over the clipping to SListPanel.
Reimplemented from SWidget.
OnCursorQuery()
virtual FCursorReply STableViewBase::OnCursorQuery (const FGeometry & MyGeometry, const FPointerEvent & CursorEvent) const override virtual
The system asks each widget under the mouse to provide a cursor.
This event is bubbled.
Returns
FCursorReply::Unhandled() if the event is not handled; return FCursorReply::Cursor() otherwise.
Reimplemented from SWidget.
OnFocusLost()
virtual void STableViewBase::OnFocusLost (const FFocusEvent & InFocusEvent) override virtual
Called when this widget loses focus.
This event does not bubble.
Parameters
InFocusEvent The FocusEvent
Reimplemented from SWidget.
Reimplemented in SCommonTileView< ItemType >.
Referenced by SCommonTileView< ItemType >::OnFocusLost().
OnKeyDown()
virtual FReply STableViewBase::OnKeyDown (const FGeometry & MyGeometry, const FKeyEvent & InKeyEvent) override virtual
Called after a key is pressed when this widget has focus (this event bubbles if not handled)
Parameters
MyGeometry The Geometry of the widget receiving the event
InKeyEvent Key event
Returns
Returns whether the event was handled, along with other possible actions
Reimplemented from SWidget.
Reimplemented in FOnSelectionChanged<>, SCurveEditorTree, SListView< ItemType >, SListView< FCurveEditorTreeItemID >, SListView< FName >, SListView< FSCSEditorTreeNodePtrType >, SListView< ListType >, SListView< OptionType >, SListView< TSharedPtr< class FComponentClassComboEntry > >, SListView< TSharedPtr< class FDebugLineItem > >, SListView< TSharedPtr< class FFilterConfiguratorNode > >, SListView< TSharedPtr< class FTableTreeNode > >, SListView< TSharedPtr< const FCollectionSpreadSheetItem > >, SListView< TSharedPtr< const FSelectionViewItem > >, SListView< TSharedPtr< EAudioOscilloscopeTriggerMode > >, SListView< TSharedPtr< ECSVImportType > >, SListView< TSharedPtr< ERichCurveInterpMode > >, SListView< TSharedPtr< FAnimAttributeEntry > >, SListView< TSharedPtr< FBlueprintDebugObjectInstance > >, SListView< TSharedPtr< FBlueprintDifferenceTreeEntry > >, SListView< TSharedPtr< FDataflowOutlinerTreeItem > >, SListView< TSharedPtr< FDisplayedBoneMappingInfo > >, SListView< TSharedPtr< FGeometryCollectionFacesTreeItem > >, SListView< TSharedPtr< FGeometryCollectionVerticesTreeItem > >, SListView< TSharedPtr< FGraphActionNode > >, SListView< TSharedPtr< FName > >, SListView< TSharedPtr< FPendingDelete > >, SListView< TSharedPtr< FPendingPrivateAsset > >, SListView< TSharedPtr< FRigStackEntry > >, SListView< TSharedPtr< FRigVMDebugObjectInstance > >, SListView< TSharedPtr< FRigVMEditorGraphExplorerTreeElement > >, SListView< TSharedPtr< FRigVMStringWithTag > >, SListView< TSharedPtr< FSequencerFilterSuggestionListEntryBase > >, SListView< TSharedPtr< FString > >, SListView< TSharedPtr< FText > >, SListView< TSharedPtr< int32 > >, SListView< TSharedPtr< SBlueprintNamespaceEntry::FPathTreeNodeItem > >, SListView< TSharedPtr< SBoneTreeMenu::FBoneNameInfo > >, SListView< TSharedPtr< SReadOnlyHierarchyView::FItem > >, SListView< TSharedPtr< SRigVMNodeLayoutWidget::FNodeLayoutRow > >, SListView< TSharedPtr< SRigVMVariantWidget::FVariantTreeRowInfo > >, SListView< TSharedPtr< UE::Insights::FFilter > >, SListView< TSharedPtr< UE::Insights::FFilterGroupOperator > >, SListView< TSharedPtr< UE::Insights::IFilterOperator > >, SListView< TSharedRef< FRigVMTreeNode > >, SListView< TSharedRef< UE::Insights::ITableTreeViewPreset > >, SListView< TWeakPtr< FViewModel > >, SListView< TWeakViewModelPtr< IOutlinerExtension > >, SListView< UObject * >, STreeView< ItemType >, STreeView< FCurveEditorTreeItemID >, STreeView< FKeyTreeItem >, STreeView< FReferenceTreeItemPtr >, STreeView< FRigVMSearchResult >, STreeView< FSCSEditorTreeNodePtrType >, STreeView< FSearchResult >, STreeView< TSharedPtr< class FDebugLineItem > >, STreeView< TSharedPtr< class FFilterConfiguratorNode > >, STreeView< TSharedPtr< class FTableTreeNode > >, STreeView< TSharedPtr< FBlueprintDifferenceTreeEntry > >, STreeView< TSharedPtr< FDataflowOutlinerTreeItem > >, STreeView< TSharedPtr< FGeometryCollectionFacesTreeItem > >, STreeView< TSharedPtr< FGeometryCollectionVerticesTreeItem > >, STreeView< TSharedPtr< FGraphActionNode > >, STreeView< TSharedPtr< FRigStackEntry > >, STreeView< TSharedPtr< FRigVMEditorGraphExplorerTreeElement > >, STreeView< TSharedPtr< FRigVMVariableMappingInfo > >, STreeView< TSharedPtr< SBlueprintNamespaceEntry::FPathTreeNodeItem > >, STreeView< TSharedPtr< SBoneTreeMenu::FBoneNameInfo > >, STreeView< TSharedPtr< SReadOnlyHierarchyView::FItem > >, STreeView< TSharedPtr< SRigVMNodeLayoutWidget::FNodeLayoutRow > >, STreeView< TSharedPtr< SRigVMVariantWidget::FVariantTreeRowInfo > >, STreeView< TSharedRef< FRigVMTreeNode > >, STreeView< TWeakPtr< FViewModel > >, STreeView< TWeakViewModelPtr< IOutlinerExtension > >, and UE::Sequencer::SOutlinerView.
Referenced by SListView< TSharedPtr< FString > >::OnKeyDown_Internal().
OnMouseButtonDoubleClick()
virtual FReply STableViewBase::OnMouseButtonDoubleClick (const FGeometry & InMyGeometry, const FPointerEvent & InMouseEvent) override virtual
Called when a mouse button is double clicked.
Override this in derived classes.
Parameters
InMyGeometry Widget geometry
InMouseEvent Mouse button event
Returns
Returns whether the event was handled, along with other possible actions
Reimplemented from SWidget.
Referenced by SCurveEditorTree::SLATE_ARGUMENT(), SListView< TSharedPtr< FString > >::SLATE_EVENT(), SSCSEditorDragDropTree::SLATE_EVENT(), STileView< ItemType >::SLATE_EVENT(), and STreeView< FRigVMSearchResult >::SLATE_EVENT().
OnMouseButtonDown()
virtual FReply STableViewBase::OnMouseButtonDown (const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) override virtual
The system calls this method to notify the widget that a mouse button was pressed within it.
This event is bubbled.
Parameters
MyGeometry The Geometry of the widget receiving the event
MouseEvent Information about the input event
Returns
Whether the event was handled along with possible requests for the system to take action.
Reimplemented from SWidget.
Reimplemented in SListView< ItemType >, SListView< FCurveEditorTreeItemID >, SListView< FName >, SListView< FSCSEditorTreeNodePtrType >, SListView< ListType >, SListView< OptionType >, SListView< TSharedPtr< class FComponentClassComboEntry > >, SListView< TSharedPtr< class FDebugLineItem > >, SListView< TSharedPtr< class FFilterConfiguratorNode > >, SListView< TSharedPtr< class FTableTreeNode > >, SListView< TSharedPtr< const FCollectionSpreadSheetItem > >, SListView< TSharedPtr< const FSelectionViewItem > >, SListView< TSharedPtr< EAudioOscilloscopeTriggerMode > >, SListView< TSharedPtr< ECSVImportType > >, SListView< TSharedPtr< ERichCurveInterpMode > >, SListView< TSharedPtr< FAnimAttributeEntry > >, SListView< TSharedPtr< FBlueprintDebugObjectInstance > >, SListView< TSharedPtr< FBlueprintDifferenceTreeEntry > >, SListView< TSharedPtr< FDataflowOutlinerTreeItem > >, SListView< TSharedPtr< FDisplayedBoneMappingInfo > >, SListView< TSharedPtr< FGeometryCollectionFacesTreeItem > >, SListView< TSharedPtr< FGeometryCollectionVerticesTreeItem > >, SListView< TSharedPtr< FGraphActionNode > >, SListView< TSharedPtr< FName > >, SListView< TSharedPtr< FPendingDelete > >, SListView< TSharedPtr< FPendingPrivateAsset > >, SListView< TSharedPtr< FRigStackEntry > >, SListView< TSharedPtr< FRigVMDebugObjectInstance > >, SListView< TSharedPtr< FRigVMEditorGraphExplorerTreeElement > >, SListView< TSharedPtr< FRigVMStringWithTag > >, SListView< TSharedPtr< FSequencerFilterSuggestionListEntryBase > >, SListView< TSharedPtr< FString > >, SListView< TSharedPtr< FText > >, SListView< TSharedPtr< int32 > >, SListView< TSharedPtr< SBlueprintNamespaceEntry::FPathTreeNodeItem > >, SListView< TSharedPtr< SBoneTreeMenu::FBoneNameInfo > >, SListView< TSharedPtr< SReadOnlyHierarchyView::FItem > >, SListView< TSharedPtr< SRigVMNodeLayoutWidget::FNodeLayoutRow > >, SListView< TSharedPtr< SRigVMVariantWidget::FVariantTreeRowInfo > >, SListView< TSharedPtr< UE::Insights::FFilter > >, SListView< TSharedPtr< UE::Insights::FFilterGroupOperator > >, SListView< TSharedPtr< UE::Insights::IFilterOperator > >, SListView< TSharedRef< FRigVMTreeNode > >, SListView< TSharedRef< UE::Insights::ITableTreeViewPreset > >, SListView< TWeakPtr< FViewModel > >, SListView< TWeakViewModelPtr< IOutlinerExtension > >, and SListView< UObject * >.
References MouseEvent.
Referenced by SListView< TSharedPtr< FString > >::OnMouseButtonDown().
OnMouseButtonUp()
virtual FReply STableViewBase::OnMouseButtonUp (const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) override virtual
The system calls this method to notify the widget that a mouse button was release within it.
This event is bubbled.
Parameters
MyGeometry The Geometry of the widget receiving the event
MouseEvent Information about the input event
Returns
Whether the event was handled along with possible requests for the system to take action.
Reimplemented from SWidget.
Reimplemented in SListView< ItemType >, SListView< FCurveEditorTreeItemID >, SListView< FName >, SListView< FSCSEditorTreeNodePtrType >, SListView< ListType >, SListView< OptionType >, SListView< TSharedPtr< class FComponentClassComboEntry > >, SListView< TSharedPtr< class FDebugLineItem > >, SListView< TSharedPtr< class FFilterConfiguratorNode > >, SListView< TSharedPtr< class FTableTreeNode > >, SListView< TSharedPtr< const FCollectionSpreadSheetItem > >, SListView< TSharedPtr< const FSelectionViewItem > >, SListView< TSharedPtr< EAudioOscilloscopeTriggerMode > >, SListView< TSharedPtr< ECSVImportType > >, SListView< TSharedPtr< ERichCurveInterpMode > >, SListView< TSharedPtr< FAnimAttributeEntry > >, SListView< TSharedPtr< FBlueprintDebugObjectInstance > >, SListView< TSharedPtr< FBlueprintDifferenceTreeEntry > >, SListView< TSharedPtr< FDataflowOutlinerTreeItem > >, SListView< TSharedPtr< FDisplayedBoneMappingInfo > >, SListView< TSharedPtr< FGeometryCollectionFacesTreeItem > >, SListView< TSharedPtr< FGeometryCollectionVerticesTreeItem > >, SListView< TSharedPtr< FGraphActionNode > >, SListView< TSharedPtr< FName > >, SListView< TSharedPtr< FPendingDelete > >, SListView< TSharedPtr< FPendingPrivateAsset > >, SListView< TSharedPtr< FRigStackEntry > >, SListView< TSharedPtr< FRigVMDebugObjectInstance > >, SListView< TSharedPtr< FRigVMEditorGraphExplorerTreeElement > >, SListView< TSharedPtr< FRigVMStringWithTag > >, SListView< TSharedPtr< FSequencerFilterSuggestionListEntryBase > >, SListView< TSharedPtr< FString > >, SListView< TSharedPtr< FText > >, SListView< TSharedPtr< int32 > >, SListView< TSharedPtr< SBlueprintNamespaceEntry::FPathTreeNodeItem > >, SListView< TSharedPtr< SBoneTreeMenu::FBoneNameInfo > >, SListView< TSharedPtr< SReadOnlyHierarchyView::FItem > >, SListView< TSharedPtr< SRigVMNodeLayoutWidget::FNodeLayoutRow > >, SListView< TSharedPtr< SRigVMVariantWidget::FVariantTreeRowInfo > >, SListView< TSharedPtr< UE::Insights::FFilter > >, SListView< TSharedPtr< UE::Insights::FFilterGroupOperator > >, SListView< TSharedPtr< UE::Insights::IFilterOperator > >, SListView< TSharedRef< FRigVMTreeNode > >, SListView< TSharedRef< UE::Insights::ITableTreeViewPreset > >, SListView< TWeakPtr< FViewModel > >, SListView< TWeakViewModelPtr< IOutlinerExtension > >, and SListView< UObject * >.
References MouseEvent.
Referenced by SListView< TSharedPtr< FString > >::OnMouseButtonUp().
OnMouseCaptureLost()
virtual void STableViewBase::OnMouseCaptureLost (const FCaptureLostEvent & CaptureLostEvent) override virtual
Called when this widget had captured the mouse, but that capture has been revoked for some reason.
Reimplemented from SWidget.
OnMouseEnter()
virtual void STableViewBase::OnMouseEnter (const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) override virtual
The system will use this event to notify a widget that the cursor has entered it.
This event is uses a custom bubble strategy.
Parameters
MyGeometry The Geometry of the widget receiving the event
MouseEvent Information about the input event
Reimplemented from SWidget.
References MouseEvent.
OnMouseLeave()
virtual void STableViewBase::OnMouseLeave (const FPointerEvent & MouseEvent) override virtual
The system will use this event to notify a widget that the cursor has left it.
This event is uses a custom bubble strategy.
Parameters
MouseEvent Information about the input event
Reimplemented from SWidget.
Reimplemented in SCommonListView< ItemType >, SCommonTileView< ItemType >, and SCommonTreeView< ItemType >.
References MouseEvent.
Referenced by SCommonListView< ItemType >::OnMouseLeave(), SCommonTileView< ItemType >::OnMouseLeave(), and SCommonTreeView< ItemType >::OnMouseLeave().
OnMouseMove()
virtual FReply STableViewBase::OnMouseMove (const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) override virtual
The system calls this method to notify the widget that a mouse moved within it.
This event is bubbled.
Parameters
MyGeometry The Geometry of the widget receiving the event
MouseEvent Information about the input event
Returns
Whether the event was handled along with possible requests for the system to take action.
Reimplemented from SWidget.
References MouseEvent.
OnMouseWheel()
virtual FReply STableViewBase::OnMouseWheel (const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) override virtual
Called when the mouse wheel is spun.
This event is bubbled.
Parameters
MouseEvent Mouse event
Returns
Returns whether the event was handled, along with other possible actions
Reimplemented from SWidget.
References MouseEvent.
OnPaint()
virtual int32 STableViewBase::OnPaint (const FPaintArgs & Args, const FGeometry & AllottedGeometry, const FSlateRect & MyCullingRect, FSlateWindowElementList & OutDrawElements, int32 LayerId, const FWidgetStyle & InWidgetStyle, bool bParentEnabled) const override virtual
The widget should respond by populating the OutDrawElements array with FDrawElements that represent it and any of its children.
Called by the non-virtual OnPaint to enforce pre/post conditions during OnPaint.
Parameters
Args All the arguments necessary to paint this widget (
Todo
umg: move all params into this struct)
Parameters
AllottedGeometry The FGeometry that describes an area in which the widget should appear.
MyCullingRect The rectangle representing the bounds currently being used to completely cull widgets. Unless IsChildWidgetCulled(...) returns true, you should paint the widget.
OutDrawElements A list of FDrawElements to populate with the output.
LayerId The Layer onto which this widget should be rendered.
InColorAndOpacity Color and Opacity to be applied to all the descendants of the widget being painted
bParentEnabled True if the parent of this widget is enabled.
Returns
The maximum layer ID attained by this widget or any of its children.
Reimplemented from SCompoundWidget.
Reimplemented in UE::Sequencer::SOutlinerView.
References SWidget::FSlateWindowElementList.
OnPreviewMouseButtonDown()
virtual FReply STableViewBase::OnPreviewMouseButtonDown (const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) override virtual
Just like OnMouseButtonDown, but tunnels instead of bubbling.
If this event is handled, OnMouseButtonDown will not be sent.
Use this event sparingly as preview events generally make UIs more difficult to reason about.
Reimplemented from SWidget.
References MouseEvent.
OnRightMouseButtonDown()
virtual void STableViewBase::OnRightMouseButtonDown (const FPointerEvent & MouseEvent) inline protected virtual
Reimplemented in UE::Sequencer::SOutlinerView.
Definition at line 343 of file STableViewBase.h.
References MouseEvent.
OnRightMouseButtonUp()
virtual void STableViewBase::OnRightMouseButtonUp (const FPointerEvent & MouseEvent) protected virtual
Opens a context menu as the result of a right click if OnContextMenuOpening is bound and we are not right click scrolling.
Reimplemented in UE::Sequencer::SOutlinerView.
References MouseEvent.
Referenced by SListView< TSharedPtr< FString > >::Private_OnItemRightClicked().
OnTouchEnded()
virtual FReply STableViewBase::OnTouchEnded (const FGeometry & MyGeometry, const FPointerEvent & InTouchEvent) override virtual
Called when a touchpad touch is ended (finger lifted)
Parameters
InTouchEvent The touch event generated
Reimplemented from SWidget.
Reimplemented in SCommonListView< ItemType >, and SCommonTreeView< ItemType >.
Referenced by SCommonListView< ItemType >::OnTouchEnded(), and SCommonTreeView< ItemType >::OnTouchEnded().
OnTouchMoved()
virtual FReply STableViewBase::OnTouchMoved (const FGeometry & MyGeometry, const FPointerEvent & InTouchEvent) override virtual
Called when a touchpad touch is moved (finger moved)
Parameters
InTouchEvent The touch event generated
Reimplemented from SWidget.
Reimplemented in SCommonListView< ItemType >, SCommonTileView< ItemType >, and SCommonTreeView< ItemType >.
Referenced by SCommonListView< ItemType >::OnTouchMoved(), SCommonTileView< ItemType >::OnTouchMoved(), and SCommonTreeView< ItemType >::OnTouchMoved().
OnTouchStarted()
virtual FReply STableViewBase::OnTouchStarted (const FGeometry & MyGeometry, const FPointerEvent & InTouchEvent) override virtual
Called when a touchpad touch is started (finger down)
Parameters
InTouchEvent The touch event generated
Reimplemented from SWidget.
RebuildList()
virtual void STableViewBase::RebuildList () pure virtual
Completely wipe existing widgets and fully regenerate them on next tick.
Implemented in FOnSelectionChanged<>, SListView< ItemType >, SListView< FCurveEditorTreeItemID >, SListView< FName >, SListView< FSCSEditorTreeNodePtrType >, SListView< ListType >, SListView< OptionType >, SListView< TSharedPtr< class FComponentClassComboEntry > >, SListView< TSharedPtr< class FDebugLineItem > >, SListView< TSharedPtr< class FFilterConfiguratorNode > >, SListView< TSharedPtr< class FTableTreeNode > >, SListView< TSharedPtr< const FCollectionSpreadSheetItem > >, SListView< TSharedPtr< const FSelectionViewItem > >, SListView< TSharedPtr< EAudioOscilloscopeTriggerMode > >, SListView< TSharedPtr< ECSVImportType > >, SListView< TSharedPtr< ERichCurveInterpMode > >, SListView< TSharedPtr< FAnimAttributeEntry > >, SListView< TSharedPtr< FBlueprintDebugObjectInstance > >, SListView< TSharedPtr< FBlueprintDifferenceTreeEntry > >, SListView< TSharedPtr< FDataflowOutlinerTreeItem > >, SListView< TSharedPtr< FDisplayedBoneMappingInfo > >, SListView< TSharedPtr< FGeometryCollectionFacesTreeItem > >, SListView< TSharedPtr< FGeometryCollectionVerticesTreeItem > >, SListView< TSharedPtr< FGraphActionNode > >, SListView< TSharedPtr< FName > >, SListView< TSharedPtr< FPendingDelete > >, SListView< TSharedPtr< FPendingPrivateAsset > >, SListView< TSharedPtr< FRigStackEntry > >, SListView< TSharedPtr< FRigVMDebugObjectInstance > >, SListView< TSharedPtr< FRigVMEditorGraphExplorerTreeElement > >, SListView< TSharedPtr< FRigVMStringWithTag > >, SListView< TSharedPtr< FSequencerFilterSuggestionListEntryBase > >, SListView< TSharedPtr< FString > >, SListView< TSharedPtr< FText > >, SListView< TSharedPtr< int32 > >, SListView< TSharedPtr< SBlueprintNamespaceEntry::FPathTreeNodeItem > >, SListView< TSharedPtr< SBoneTreeMenu::FBoneNameInfo > >, SListView< TSharedPtr< SReadOnlyHierarchyView::FItem > >, SListView< TSharedPtr< SRigVMNodeLayoutWidget::FNodeLayoutRow > >, SListView< TSharedPtr< SRigVMVariantWidget::FVariantTreeRowInfo > >, SListView< TSharedPtr< UE::Insights::FFilter > >, SListView< TSharedPtr< UE::Insights::FFilterGroupOperator > >, SListView< TSharedPtr< UE::Insights::IFilterOperator > >, SListView< TSharedRef< FRigVMTreeNode > >, SListView< TSharedRef< UE::Insights::ITableTreeViewPreset > >, SListView< TWeakPtr< FViewModel > >, SListView< TWeakViewModelPtr< IOutlinerExtension > >, SListView< UObject * >, STreeView< ItemType >, STreeView< FCurveEditorTreeItemID >, STreeView< FKeyTreeItem >, STreeView< FReferenceTreeItemPtr >, STreeView< FRigVMSearchResult >, STreeView< FSCSEditorTreeNodePtrType >, STreeView< FSearchResult >, STreeView< TSharedPtr< class FDebugLineItem > >, STreeView< TSharedPtr< class FFilterConfiguratorNode > >, STreeView< TSharedPtr< class FTableTreeNode > >, STreeView< TSharedPtr< FBlueprintDifferenceTreeEntry > >, STreeView< TSharedPtr< FDataflowOutlinerTreeItem > >, STreeView< TSharedPtr< FGeometryCollectionFacesTreeItem > >, STreeView< TSharedPtr< FGeometryCollectionVerticesTreeItem > >, STreeView< TSharedPtr< FGraphActionNode > >, STreeView< TSharedPtr< FRigStackEntry > >, STreeView< TSharedPtr< FRigVMEditorGraphExplorerTreeElement > >, STreeView< TSharedPtr< FRigVMVariableMappingInfo > >, STreeView< TSharedPtr< SBlueprintNamespaceEntry::FPathTreeNodeItem > >, STreeView< TSharedPtr< SBoneTreeMenu::FBoneNameInfo > >, STreeView< TSharedPtr< SReadOnlyHierarchyView::FItem > >, STreeView< TSharedPtr< SRigVMNodeLayoutWidget::FNodeLayoutRow > >, STreeView< TSharedPtr< SRigVMVariantWidget::FVariantTreeRowInfo > >, STreeView< TSharedRef< FRigVMTreeNode > >, STreeView< TWeakPtr< FViewModel > >, and STreeView< TWeakViewModelPtr< IOutlinerExtension > >.
ReGenerateItems()
virtual FReGenerateResults STableViewBase::ReGenerateItems (const FGeometry & MyGeometry) protected pure virtual
Update generate Widgets for Items as needed and clean up any Widgets that are no longer needed.
Re-arrange the visible widget order as necessary.
Implemented in FOnSelectionChanged<>, SListView< ItemType >, SListView< FCurveEditorTreeItemID >, SListView< FName >, SListView< FSCSEditorTreeNodePtrType >, SListView< ListType >, SListView< OptionType >, SListView< TSharedPtr< class FComponentClassComboEntry > >, SListView< TSharedPtr< class FDebugLineItem > >, SListView< TSharedPtr< class FFilterConfiguratorNode > >, SListView< TSharedPtr< class FTableTreeNode > >, SListView< TSharedPtr< const FCollectionSpreadSheetItem > >, SListView< TSharedPtr< const FSelectionViewItem > >, SListView< TSharedPtr< EAudioOscilloscopeTriggerMode > >, SListView< TSharedPtr< ECSVImportType > >, SListView< TSharedPtr< ERichCurveInterpMode > >, SListView< TSharedPtr< FAnimAttributeEntry > >, SListView< TSharedPtr< FBlueprintDebugObjectInstance > >, SListView< TSharedPtr< FBlueprintDifferenceTreeEntry > >, SListView< TSharedPtr< FDataflowOutlinerTreeItem > >, SListView< TSharedPtr< FDisplayedBoneMappingInfo > >, SListView< TSharedPtr< FGeometryCollectionFacesTreeItem > >, SListView< TSharedPtr< FGeometryCollectionVerticesTreeItem > >, SListView< TSharedPtr< FGraphActionNode > >, SListView< TSharedPtr< FName > >, SListView< TSharedPtr< FPendingDelete > >, SListView< TSharedPtr< FPendingPrivateAsset > >, SListView< TSharedPtr< FRigStackEntry > >, SListView< TSharedPtr< FRigVMDebugObjectInstance > >, SListView< TSharedPtr< FRigVMEditorGraphExplorerTreeElement > >, SListView< TSharedPtr< FRigVMStringWithTag > >, SListView< TSharedPtr< FSequencerFilterSuggestionListEntryBase > >, SListView< TSharedPtr< FString > >, SListView< TSharedPtr< FText > >, SListView< TSharedPtr< int32 > >, SListView< TSharedPtr< SBlueprintNamespaceEntry::FPathTreeNodeItem > >, SListView< TSharedPtr< SBoneTreeMenu::FBoneNameInfo > >, SListView< TSharedPtr< SReadOnlyHierarchyView::FItem > >, SListView< TSharedPtr< SRigVMNodeLayoutWidget::FNodeLayoutRow > >, SListView< TSharedPtr< SRigVMVariantWidget::FVariantTreeRowInfo > >, SListView< TSharedPtr< UE::Insights::FFilter > >, SListView< TSharedPtr< UE::Insights::FFilterGroupOperator > >, SListView< TSharedPtr< UE::Insights::IFilterOperator > >, SListView< TSharedRef< FRigVMTreeNode > >, SListView< TSharedRef< UE::Insights::ITableTreeViewPreset > >, SListView< TWeakPtr< FViewModel > >, SListView< TWeakViewModelPtr< IOutlinerExtension > >, SListView< UObject * >, STileView< ItemType >, STreeView< ItemType >, STreeView< FCurveEditorTreeItemID >, STreeView< FKeyTreeItem >, STreeView< FReferenceTreeItemPtr >, STreeView< FRigVMSearchResult >, STreeView< FSCSEditorTreeNodePtrType >, STreeView< FSearchResult >, STreeView< TSharedPtr< class FDebugLineItem > >, STreeView< TSharedPtr< class FFilterConfiguratorNode > >, STreeView< TSharedPtr< class FTableTreeNode > >, STreeView< TSharedPtr< FBlueprintDifferenceTreeEntry > >, STreeView< TSharedPtr< FDataflowOutlinerTreeItem > >, STreeView< TSharedPtr< FGeometryCollectionFacesTreeItem > >, STreeView< TSharedPtr< FGeometryCollectionVerticesTreeItem > >, STreeView< TSharedPtr< FGraphActionNode > >, STreeView< TSharedPtr< FRigStackEntry > >, STreeView< TSharedPtr< FRigVMEditorGraphExplorerTreeElement > >, STreeView< TSharedPtr< FRigVMVariableMappingInfo > >, STreeView< TSharedPtr< SBlueprintNamespaceEntry::FPathTreeNodeItem > >, STreeView< TSharedPtr< SBoneTreeMenu::FBoneNameInfo > >, STreeView< TSharedPtr< SReadOnlyHierarchyView::FItem > >, STreeView< TSharedPtr< SRigVMNodeLayoutWidget::FNodeLayoutRow > >, STreeView< TSharedPtr< SRigVMVariantWidget::FVariantTreeRowInfo > >, STreeView< TSharedRef< FRigVMTreeNode > >, STreeView< TWeakPtr< FViewModel > >, and STreeView< TWeakViewModelPtr< IOutlinerExtension > >.
RequestLayoutRefresh()
void STableViewBase::RequestLayoutRefresh () protected
Internal request for a layout update on the next tick (i.e.
a refresh without implication that the source items have changed)
Referenced by SListView< TSharedPtr< FString > >::RequestScrollIntoView().
RequestListRefresh()
virtual void STableViewBase::RequestListRefresh () virtual
Mark the list as dirty so that it will refresh its widgets on next tick.
Note that refreshing will only generate/release widgets as needed from any deltas in the list items source.
Reimplemented in FOnSelectionChanged<>, STreeView< ItemType >, STreeView< FCurveEditorTreeItemID >, STreeView< FKeyTreeItem >, STreeView< FReferenceTreeItemPtr >, STreeView< FRigVMSearchResult >, STreeView< FSCSEditorTreeNodePtrType >, STreeView< FSearchResult >, STreeView< TSharedPtr< class FDebugLineItem > >, STreeView< TSharedPtr< class FFilterConfiguratorNode > >, STreeView< TSharedPtr< class FTableTreeNode > >, STreeView< TSharedPtr< FBlueprintDifferenceTreeEntry > >, STreeView< TSharedPtr< FDataflowOutlinerTreeItem > >, STreeView< TSharedPtr< FGeometryCollectionFacesTreeItem > >, STreeView< TSharedPtr< FGeometryCollectionVerticesTreeItem > >, STreeView< TSharedPtr< FGraphActionNode > >, STreeView< TSharedPtr< FRigStackEntry > >, STreeView< TSharedPtr< FRigVMEditorGraphExplorerTreeElement > >, STreeView< TSharedPtr< FRigVMVariableMappingInfo > >, STreeView< TSharedPtr< SBlueprintNamespaceEntry::FPathTreeNodeItem > >, STreeView< TSharedPtr< SBoneTreeMenu::FBoneNameInfo > >, STreeView< TSharedPtr< SReadOnlyHierarchyView::FItem > >, STreeView< TSharedPtr< SRigVMNodeLayoutWidget::FNodeLayoutRow > >, STreeView< TSharedPtr< SRigVMVariantWidget::FVariantTreeRowInfo > >, STreeView< TSharedRef< FRigVMTreeNode > >, STreeView< TWeakPtr< FViewModel > >, and STreeView< TWeakViewModelPtr< IOutlinerExtension > >.
Referenced by SListView< TSharedPtr< FString > >::RebuildList(), STreeView< FRigVMSearchResult >::RequestListRefresh(), STileView< ItemType >::ScrollBy(), and STileView< ItemType >::ScrollIntoView().
ScrollBar_OnUserScrolled()
void STableViewBase::ScrollBar_OnUserScrolled (float InScrollOffsetFraction)
Invoked by the scrollbar when the user scrolls.
Parameters
InScrollOffsetFraction The location to which the user scrolled as a fraction (between 0 and 1) of total height of the content.
ScrollBy()
virtual float STableViewBase::ScrollBy (const FGeometry & MyGeometry, float ScrollByAmount, EAllowOverscroll InAllowOverscroll) protected virtual
Scroll the list view by some number of screen units.
Parameters
MyGeometry The geometry of the ListView at the time
ScrollByAmount The amount to scroll by in Slate Screen Units.
AllowOverscroll Should we allow scrolling past the beginning/end of the list?
Returns
The amount actually scrolled in items
Reimplemented in STileView< ItemType >.
ScrollIntoView()
virtual EScrollIntoViewResult STableViewBase::ScrollIntoView (const FGeometry & ListViewGeometry) protected pure virtual
If there is a pending request to scroll an item into view, do so.
Parameters
ListViewGeometry The geometry of the listView; can be useful for centering the item.
Implemented in STileView< ItemType >.
ScrollTo()
virtual float STableViewBase::ScrollTo (float InScrollOffset) protected virtual
Scroll the view to an offset and resets the inertial scroll velocity.
Parameters
InScrollOffset Offset into the total list length to scroll down.
Returns
The amount actually scrolled
Referenced by STileView< ItemType >::ScrollBy().
ScrollToBottom()
void STableViewBase::ScrollToBottom ()
Scrolls the view to the bottom.
ScrollToTop()
void STableViewBase::ScrollToTop ()
Scrolls the view to the top.
SetAllowOverscroll()
void STableViewBase::SetAllowOverscroll (EAllowOverscroll InAllowOverscroll)
Sets whether to permit overscroll on this list view.
SetBackgroundBrush()
void STableViewBase::SetBackgroundBrush (const TAttribute< const FSlateBrush * > & InBackgroundBrush)
Sets the Background Brush.
Referenced by SListView< TSharedPtr< FString > >::SetStyle(), and STreeView< FRigVMSearchResult >::SetStyle().
SetEnableTouchAnimatedScrolling()
void STableViewBase::SetEnableTouchAnimatedScrolling (bool bInEnableTouchAnimatedScrolling)
Sets whether the list should lerp between scroll offsets or jump instantly between them with touch.
SetFixedLineScrollOffset()
void STableViewBase::SetFixedLineScrollOffset (TOptional< double > InFixedLineScrollOffset)
Sets the fixed offset in items to always apply to the top/left (depending on orientation) of the list.
SetIsGamepadScrollingEnabled()
void STableViewBase::SetIsGamepadScrollingEnabled (bool bInIsGamepadScrollingEnabled)
Enables/disables being able to scroll via gamepad.
SetIsPointerScrollingEnabled()
void STableViewBase::SetIsPointerScrollingEnabled (bool bInIsPointerScrollingEnabled)
Enables/disables being able to scroll via pointer.
This should be use as a temporary mean to disable scrolling.
SetIsRightClickScrollingEnabled()
void STableViewBase::SetIsRightClickScrollingEnabled (const bool bInEnableRightClickScrolling)
Enables/disables being able to scroll with the right mouse button.
SetIsScrollAnimationEnabled()
void STableViewBase::SetIsScrollAnimationEnabled (bool bInEnableScrollAnimation)
Sets whether the list should lerp between scroll offsets or jump instantly between them.
SetIsTouchScrollingEnabled()
void STableViewBase::SetIsTouchScrollingEnabled (const bool bInEnableTouchScrolling)
Enables/disables being able to scroll using touch input.
SetItemHeight()
void STableViewBase::SetItemHeight (TAttribute< float > Height)
Sets the item height.
SetItemWidth()
void STableViewBase::SetItemWidth (TAttribute< float > Width)
Sets the item width.
References Width.
SetScrollbarPadding()
void STableViewBase::SetScrollbarPadding (const FMargin & InScrollbarPadding)
SetScrollbarVisibility()
void STableViewBase::SetScrollbarVisibility (const EVisibility InVisibility)
SetScrollingAnimationInterpolationSpeed()
void STableViewBase::SetScrollingAnimationInterpolationSpeed (float InScrollingAnimationInterpolationSpeed)
Sets the speed of lerp between scroll offsets.
SetScrollOffset()
void STableViewBase::SetScrollOffset (const float InScrollOffset)
Set the scroll offset of this view (in items)
Referenced by STileView< ItemType >::ScrollIntoView().
SetSelectItemOnNavigation()
void STableViewBase::SetSelectItemOnNavigation (const bool bInSelectItemOnNavigation)
Sets whether items will be selected and focused or only focused when navigating to them.
SetWheelScrollMultiplier()
void STableViewBase::SetWheelScrollMultiplier (float NewWheelScrollMultiplier)
Sets the multiplier applied when wheel scrolling.
Higher numbers will cover more distance per click of the wheel.
ShouldScrollToFixedLineOffsetAtZeroVelocity()
bool STableViewBase::ShouldScrollToFixedLineOffsetAtZeroVelocity () const private
Whether or not the view should scroll to a fixed line offset if the scroll velocity is 0.
SupportsKeyboardFocus()
virtual bool STableViewBase::SupportsKeyboardFocus () const override virtual
Checks to see if this widget supports keyboard focus.
Override this in derived classes.
Returns
True if this widget can take keyboard focus
Reimplemented from SWidget.
Reimplemented in SListView< ItemType >, SListView< FCurveEditorTreeItemID >, SListView< FName >, SListView< FSCSEditorTreeNodePtrType >, SListView< ListType >, SListView< OptionType >, SListView< TSharedPtr< class FComponentClassComboEntry > >, SListView< TSharedPtr< class FDebugLineItem > >, SListView< TSharedPtr< class FFilterConfiguratorNode > >, SListView< TSharedPtr< class FTableTreeNode > >, SListView< TSharedPtr< const FCollectionSpreadSheetItem > >, SListView< TSharedPtr< const FSelectionViewItem > >, SListView< TSharedPtr< EAudioOscilloscopeTriggerMode > >, SListView< TSharedPtr< ECSVImportType > >, SListView< TSharedPtr< ERichCurveInterpMode > >, SListView< TSharedPtr< FAnimAttributeEntry > >, SListView< TSharedPtr< FBlueprintDebugObjectInstance > >, SListView< TSharedPtr< FBlueprintDifferenceTreeEntry > >, SListView< TSharedPtr< FDataflowOutlinerTreeItem > >, SListView< TSharedPtr< FDisplayedBoneMappingInfo > >, SListView< TSharedPtr< FGeometryCollectionFacesTreeItem > >, SListView< TSharedPtr< FGeometryCollectionVerticesTreeItem > >, SListView< TSharedPtr< FGraphActionNode > >, SListView< TSharedPtr< FName > >, SListView< TSharedPtr< FPendingDelete > >, SListView< TSharedPtr< FPendingPrivateAsset > >, SListView< TSharedPtr< FRigStackEntry > >, SListView< TSharedPtr< FRigVMDebugObjectInstance > >, SListView< TSharedPtr< FRigVMEditorGraphExplorerTreeElement > >, SListView< TSharedPtr< FRigVMStringWithTag > >, SListView< TSharedPtr< FSequencerFilterSuggestionListEntryBase > >, SListView< TSharedPtr< FString > >, SListView< TSharedPtr< FText > >, SListView< TSharedPtr< int32 > >, SListView< TSharedPtr< SBlueprintNamespaceEntry::FPathTreeNodeItem > >, SListView< TSharedPtr< SBoneTreeMenu::FBoneNameInfo > >, SListView< TSharedPtr< SReadOnlyHierarchyView::FItem > >, SListView< TSharedPtr< SRigVMNodeLayoutWidget::FNodeLayoutRow > >, SListView< TSharedPtr< SRigVMVariantWidget::FVariantTreeRowInfo > >, SListView< TSharedPtr< UE::Insights::FFilter > >, SListView< TSharedPtr< UE::Insights::FFilterGroupOperator > >, SListView< TSharedPtr< UE::Insights::IFilterOperator > >, SListView< TSharedRef< FRigVMTreeNode > >, SListView< TSharedRef< UE::Insights::ITableTreeViewPreset > >, SListView< TWeakPtr< FViewModel > >, SListView< TWeakViewModelPtr< IOutlinerExtension > >, and SListView< UObject * >.
Tick()
virtual void STableViewBase::Tick (const FGeometry & AllottedGeometry, const double InCurrentTime, const float InDeltaTime) override virtual
Ticks this widget with Geometry.
Override in derived classes, but always call the parent implementation.
Parameters
AllottedGeometry The space allotted for this widget
InCurrentTime Current absolute real time
InDeltaTime Real time passed since last tick
Reimplemented from SWidget.
Reimplemented in FOnSelectionChanged<>, STreeView< ItemType >, STreeView< FCurveEditorTreeItemID >, STreeView< FKeyTreeItem >, STreeView< FReferenceTreeItemPtr >, STreeView< FRigVMSearchResult >, STreeView< FSCSEditorTreeNodePtrType >, STreeView< FSearchResult >, STreeView< TSharedPtr< class FDebugLineItem > >, STreeView< TSharedPtr< class FFilterConfiguratorNode > >, STreeView< TSharedPtr< class FTableTreeNode > >, STreeView< TSharedPtr< FBlueprintDifferenceTreeEntry > >, STreeView< TSharedPtr< FDataflowOutlinerTreeItem > >, STreeView< TSharedPtr< FGeometryCollectionFacesTreeItem > >, STreeView< TSharedPtr< FGeometryCollectionVerticesTreeItem > >, STreeView< TSharedPtr< FGraphActionNode > >, STreeView< TSharedPtr< FRigStackEntry > >, STreeView< TSharedPtr< FRigVMEditorGraphExplorerTreeElement > >, STreeView< TSharedPtr< FRigVMVariableMappingInfo > >, STreeView< TSharedPtr< SBlueprintNamespaceEntry::FPathTreeNodeItem > >, STreeView< TSharedPtr< SBoneTreeMenu::FBoneNameInfo > >, STreeView< TSharedPtr< SReadOnlyHierarchyView::FItem > >, STreeView< TSharedPtr< SRigVMNodeLayoutWidget::FNodeLayoutRow > >, STreeView< TSharedPtr< SRigVMVariantWidget::FVariantTreeRowInfo > >, STreeView< TSharedRef< FRigVMTreeNode > >, STreeView< TWeakPtr< FViewModel > >, STreeView< TWeakViewModelPtr< IOutlinerExtension > >, and UE::Sequencer::SOutlinerView.
Referenced by STreeView< FRigVMSearchResult >::Tick().
UE_DEPRECATED()
STableViewBase::UE_DEPRECATED (5. 5, "The Pinned items visibility is no more an attribute.") const protected
UpdateInertialScroll()
EActiveTimerReturnType STableViewBase::UpdateInertialScroll (double InCurrentTime, float InDeltaTime) protected
Active timer to update the inertial scroll.
UpdateSelectionSet()
virtual void STableViewBase::UpdateSelectionSet () protected pure virtual
Remove any items that are no longer in the list from the selection set.
Implemented in SListView< ItemType >, SListView< FCurveEditorTreeItemID >, SListView< FName >, SListView< FSCSEditorTreeNodePtrType >, SListView< ListType >, SListView< OptionType >, SListView< TSharedPtr< class FComponentClassComboEntry > >, SListView< TSharedPtr< class FDebugLineItem > >, SListView< TSharedPtr< class FFilterConfiguratorNode > >, SListView< TSharedPtr< class FTableTreeNode > >, SListView< TSharedPtr< const FCollectionSpreadSheetItem > >, SListView< TSharedPtr< const FSelectionViewItem > >, SListView< TSharedPtr< EAudioOscilloscopeTriggerMode > >, SListView< TSharedPtr< ECSVImportType > >, SListView< TSharedPtr< ERichCurveInterpMode > >, SListView< TSharedPtr< FAnimAttributeEntry > >, SListView< TSharedPtr< FBlueprintDebugObjectInstance > >, SListView< TSharedPtr< FBlueprintDifferenceTreeEntry > >, SListView< TSharedPtr< FDataflowOutlinerTreeItem > >, SListView< TSharedPtr< FDisplayedBoneMappingInfo > >, SListView< TSharedPtr< FGeometryCollectionFacesTreeItem > >, SListView< TSharedPtr< FGeometryCollectionVerticesTreeItem > >, SListView< TSharedPtr< FGraphActionNode > >, SListView< TSharedPtr< FName > >, SListView< TSharedPtr< FPendingDelete > >, SListView< TSharedPtr< FPendingPrivateAsset > >, SListView< TSharedPtr< FRigStackEntry > >, SListView< TSharedPtr< FRigVMDebugObjectInstance > >, SListView< TSharedPtr< FRigVMEditorGraphExplorerTreeElement > >, SListView< TSharedPtr< FRigVMStringWithTag > >, SListView< TSharedPtr< FSequencerFilterSuggestionListEntryBase > >, SListView< TSharedPtr< FString > >, SListView< TSharedPtr< FText > >, SListView< TSharedPtr< int32 > >, SListView< TSharedPtr< SBlueprintNamespaceEntry::FPathTreeNodeItem > >, SListView< TSharedPtr< SBoneTreeMenu::FBoneNameInfo > >, SListView< TSharedPtr< SReadOnlyHierarchyView::FItem > >, SListView< TSharedPtr< SRigVMNodeLayoutWidget::FNodeLayoutRow > >, SListView< TSharedPtr< SRigVMVariantWidget::FVariantTreeRowInfo > >, SListView< TSharedPtr< UE::Insights::FFilter > >, SListView< TSharedPtr< UE::Insights::FFilterGroupOperator > >, SListView< TSharedPtr< UE::Insights::IFilterOperator > >, SListView< TSharedRef< FRigVMTreeNode > >, SListView< TSharedRef< UE::Insights::ITableTreeViewPreset > >, SListView< TWeakPtr< FViewModel > >, SListView< TWeakViewModelPtr< IOutlinerExtension > >, and SListView< UObject * >.
Field Documentation
[union]
union { ... } STableViewBase
AllowOverscroll
EAllowOverscroll STableViewBase::AllowOverscroll protected
Whether to permit overscroll on this list view.
Definition at line 571 of file STableViewBase.h.
Referenced by SListView< TSharedPtr< FString > >::SLATE_ARGUMENT(), STileView< ItemType >::SLATE_ARGUMENT(), and STreeView< FRigVMSearchResult >::SLATE_ARGUMENT().
AmountScrolledWhileRightMouseDown
float STableViewBase::AmountScrolledWhileRightMouseDown protected
How much we scrolled while the rmb has been held.
Definition at line 496 of file STableViewBase.h.
BackgroundBrush
FInvalidatableBrushAttribute STableViewBase::BackgroundBrush protected
Brush resource representing the background area of the view.
Definition at line 550 of file STableViewBase.h.
bEnableAnimatedScrolling
bool STableViewBase::bEnableAnimatedScrolling = false protected
True to lerp smoothly between offsets when the desired scroll offset changes.
Definition at line 465 of file STableViewBase.h.
Referenced by STileView< ItemType >::ScrollIntoView(), STileView< ItemType >::SLATE_END_ARGS(), SListView< TSharedPtr< FString > >::SLATE_EVENT(), and STreeView< FRigVMSearchResult >::SLATE_EVENT().
bEnableRightClickScrolling
bool STableViewBase::bEnableRightClickScrolling = true protected
True to allow right click drag scrolling.
Definition at line 474 of file STableViewBase.h.
bEnableTouchAnimatedScrolling
bool STableViewBase::bEnableTouchAnimatedScrolling = false protected
True to lerp smoothly between offsets when the desired scroll offset changes with touch.
Definition at line 471 of file STableViewBase.h.
bEnableTouchScrolling
bool STableViewBase::bEnableTouchScrolling = true protected
True to allow scrolling by using touch input.
Definition at line 477 of file STableViewBase.h.
bIsGamepadScrollingEnabled
bool STableViewBase::bIsGamepadScrollingEnabled = true protected
Whether the list is allowed to scroll via gamepad.
Definition at line 541 of file STableViewBase.h.
bIsInertialScroll
bool STableViewBase::bIsInertialScroll = false private
Whether or not the current scroll is inertial.
Definition at line 584 of file STableViewBase.h.
bIsPointerScrollingEnabled
bool STableViewBase::bIsPointerScrollingEnabled = true protected
Whether the list is allowed to scroll via cursor.
Definition at line 538 of file STableViewBase.h.
bIsScrollingActiveTimerRegistered
bool STableViewBase::bIsScrollingActiveTimerRegistered protected
Whether the active timer to update the inertial scrolling is currently registered.
Definition at line 564 of file STableViewBase.h.
bItemsNeedRefresh
bool STableViewBase::bItemsNeedRefresh = false private
When true, a refresh should occur the next tick.
Definition at line 578 of file STableViewBase.h.
bSelectItemOnNavigation
bool STableViewBase::bSelectItemOnNavigation = true protected
If true, items will be "selected" (in addition to focused) when navigating to them.
If false, they will only be focused.
Definition at line 480 of file STableViewBase.h.
Referenced by SCommonListView< ItemType >::OnFocusReceived().
bShowSoftwareCursor
bool STableViewBase::bShowSoftwareCursor protected
Whether the software cursor should be drawn in the viewport.
Definition at line 532 of file STableViewBase.h.
bStartedTouchInteraction
bool STableViewBase::bStartedTouchInteraction protected
Did the user start an interaction in this list?
Definition at line 493 of file STableViewBase.h.
Referenced by SCommonListView< ItemType >::OnMouseLeave(), SCommonTileView< ItemType >::OnMouseLeave(), and SCommonTreeView< ItemType >::OnMouseLeave().
bWasAtEndOfList
bool STableViewBase::bWasAtEndOfList protected
Last time we scrolled, did we end up at the end of the list.
Definition at line 508 of file STableViewBase.h.
Referenced by STileView< ItemType >::ScrollBy().
ConsumeMouseWheel
EConsumeMouseWheel STableViewBase::ConsumeMouseWheel protected
How we should handle scrolling with the mouse wheel.
Definition at line 574 of file STableViewBase.h.
Referenced by SListView< TSharedPtr< FString > >::SLATE_ARGUMENT(), STileView< ItemType >::SLATE_ARGUMENT(), and STreeView< FRigVMSearchResult >::SLATE_EVENT().
CurrentScrollOffset
double STableViewBase::CurrentScrollOffset = 0. protected
The currently displayed scroll offset from the beginning of the list in items.
Definition at line 483 of file STableViewBase.h.
Referenced by SListView< TSharedPtr< FString > >::ReGenerateItems(), and STileView< ItemType >::ReGenerateItems().
DesiredScrollOffset
double STableViewBase::DesiredScrollOffset = 0. protected
The raw desired scroll offset from the beginning of the list in items.
Does not incorporate the FixedLineScrollOffset. Use GetTargetScrollOffset() to know the final target offset to display. Note: If scroll animation is disabled and there is no FixedLineScrollOffset, this is identical to both the CurrentScrollOffset and the target offset.
Definition at line 490 of file STableViewBase.h.
Referenced by STileView< ItemType >::ScrollBy().
FixedLineScrollOffset
TOptional<double> STableViewBase::FixedLineScrollOffset protected
The fixed offset in lines to always apply to the top/left (depending on orientation) of the list.
If provided:
all non-inertial means of scrolling will settle with exactly this offset of the topmost entry. Ex: A value of 0.25 would cause the topmost full entry to be offset down by a quarter length of the preceding entry.
all inertial means of scrolling will, at the end of the scroll, settle with exactly this offset of the entry most in view. Ex: if at the end of the scroll we see 0.25% of a line and 0.75% of next line at the top/left, the list will scroll to show the second line minus the offset.
Definition at line 462 of file STableViewBase.h.
Referenced by STileView< ItemType >::ScrollIntoView(), SListView< TSharedPtr< FString > >::SLATE_ARGUMENT(), STileView< ItemType >::SLATE_ARGUMENT(), STileView< ItemType >::SLATE_END_ARGS(), SListView< TSharedPtr< FString > >::SLATE_EVENT(), STreeView< FRigVMSearchResult >::SLATE_EVENT(), and STreeView< FRigVMSearchResult >::SLATE_EVENT().
HeaderRow
TSharedPtr< SHeaderRow > STableViewBase::HeaderRow protected
Column headers that describe which columns this list shows.
Definition at line 523 of file STableViewBase.h.
Referenced by SListView< TSharedPtr< FString > >::SLATE_ATTRIBUTE(), SSCSEditorDragDropTree::SLATE_EVENT(), and STreeView< FRigVMSearchResult >::SLATE_EVENT().
HorizontalScrollBarSlot
SVerticalBox::FSlot* STableViewBase::HorizontalScrollBarSlot
Definition at line 590 of file STableViewBase.h.
InertialScrollManager
FInertialScrollManager STableViewBase::InertialScrollManager protected
Helper object to manage inertial scrolling.
Definition at line 526 of file STableViewBase.h.
Referenced by SListView< TSharedPtr< FString > >::Private_ClearSelection(), SListView< TSharedPtr< FString > >::Private_SelectRangeFromCurrentTo(), and SListView< TSharedPtr< FString > >::Private_SetItemSelection().
ItemsPanel
TSharedPtr< SListPanel > STableViewBase::ItemsPanel protected
The panel which holds the visible widgets in this list.
Definition at line 437 of file STableViewBase.h.
Referenced by STreeView< FRigVMSearchResult >::Tick().
LastGenerateResults
FReGenerateResults STableViewBase::LastGenerateResults protected
Information about the widgets we generated during the last regenerate pass.
Definition at line 505 of file STableViewBase.h.
Referenced by STileView< ItemType >::ScrollIntoView().
OnContextMenuOpening
FOnContextMenuOpening STableViewBase::OnContextMenuOpening protected
Delegate to invoke when the context menu should be opening.
If it is nullptr, a context menu will not be summoned.
Definition at line 514 of file STableViewBase.h.
Referenced by SSCSEditorDragDropTree::SLATE_ATTRIBUTE(), STileView< ItemType >::SLATE_END_ARGS(), SCurveEditorTree::SLATE_EVENT(), SListView< TSharedPtr< FString > >::SLATE_EVENT(), SListView< TSharedPtr< FString > >::SLATE_EVENT(), STileView< ItemType >::SLATE_EVENT(), STreeView< FRigVMSearchResult >::SLATE_EVENT(), and STreeView< FRigVMSearchResult >::SLATE_EVENT().
OnItemsRebuilt
FSimpleDelegate STableViewBase::OnItemsRebuilt protected
Delegate to invoke after the children have been regenerated.
Definition at line 517 of file STableViewBase.h.
Referenced by STileView< ItemType >::SLATE_END_ARGS(), SListView< TSharedPtr< FString > >::SLATE_EVENT(), SListView< TSharedPtr< FString > >::SLATE_EVENT(), STileView< ItemType >::SLATE_EVENT(), STreeView< FRigVMSearchResult >::SLATE_EVENT(), and STreeView< FRigVMSearchResult >::SLATE_EVENT().
OnTableViewScrolled
FOnTableViewScrolled STableViewBase::OnTableViewScrolled protected
Delegate to call when the table view is scrolled.
Definition at line 449 of file STableViewBase.h.
Orientation
EOrientation STableViewBase::Orientation = Orient_Vertical protected
The layout and scroll orientation of the list.
Definition at line 544 of file STableViewBase.h.
Referenced by SListView< TSharedPtr< FString > >::GenerateWidgetForItem(), STileView< ItemType >::GetNumItemsPerLine(), STileView< ItemType >::GetTileDimensions(), SListView< TSharedPtr< FString > >::OnNavigation(), STileView< ItemType >::OnNavigation(), SListView< TSharedPtr< FString > >::Private_GetOrientation(), SListView< TSharedPtr< FString > >::ReGenerateItems(), STileView< ItemType >::ReGenerateItems(), STileView< ItemType >::ScrollIntoView(), SListView< TSharedPtr< FString > >::SLATE_ARGUMENT(), and STileView< ItemType >::SLATE_ARGUMENT().
Overscroll
FOverscroll STableViewBase::Overscroll protected
Definition at line 568 of file STableViewBase.h.
Referenced by STileView< ItemType >::ScrollBy().
PanelGeometryLastTick
FGeometry STableViewBase::PanelGeometryLastTick protected
What the list's geometry was the last time a refresh occurred.
Definition at line 511 of file STableViewBase.h.
Referenced by STileView< ItemType >::GetNumItemsPerLine().
PinnedItemsPanel
TSharedPtr< SListPanel > STableViewBase::PinnedItemsPanel protected
The panel which holds the pinned widgets in this list.
Definition at line 440 of file STableViewBase.h.
PressedScreenSpacePosition
FVector2f STableViewBase::PressedScreenSpacePosition protected
The location in screenspace the view was pressed.
Definition at line 499 of file STableViewBase.h.
ScrollBar
TSharedPtr< SScrollBar > STableViewBase::ScrollBar protected
The scroll bar widget.
Definition at line 443 of file STableViewBase.h.
Referenced by STileView< ItemType >::SLATE_END_ARGS(), SListView< TSharedPtr< FString > >::SLATE_EVENT(), and STreeView< FRigVMSearchResult >::SLATE_EVENT().
ScrollBarSlotPadding
FMargin STableViewBase::ScrollBarSlotPadding protected
Padding to the scrollbox.
Definition at line 446 of file STableViewBase.h.
Referenced by SListView< TSharedPtr< FString > >::SLATE_EVENT().
ScrollingAnimationInterpolationSpeed
float STableViewBase::ScrollingAnimationInterpolationSpeed = 12.f protected
The speed of interpolation for the scrolling animation.
Definition at line 468 of file STableViewBase.h.
SelectionMode
TAttribute<ESelectionMode::Type> STableViewBase::SelectionMode protected
The selection mode that this tree/list is in.
Note that it is up to the generated ITableRows to respect this setting.
Definition at line 520 of file STableViewBase.h.
Referenced by SListView< TSharedPtr< FString > >::ClearSelection(), SListView< TSharedPtr< FString > >::IsItemSelected(), SListView< TSharedPtr< FString > >::OnKeyDown_Internal(), SListView< TSharedPtr< FString > >::OnMouseButtonDown(), SListView< TSharedPtr< FString > >::OnMouseButtonUp(), SListView< TSharedPtr< FString > >::Private_GetSelectionMode(), SListView< TSharedPtr< FString > >::Private_SelectRangeFromCurrentTo(), SListView< TSharedPtr< FString > >::Private_SetItemSelection(), SListView< TSharedPtr< FString > >::Private_SignalSelectionChanged(), SListView< TSharedPtr< FString > >::SetItemSelection(), SListView< TSharedPtr< FString > >::SetItemSelection(), SListView< TSharedPtr< FString > >::SLATE_ATTRIBUTE(), STileView< ItemType >::SLATE_ATTRIBUTE(), STileView< ItemType >::SLATE_END_ARGS(), SListView< TSharedPtr< FString > >::SLATE_EVENT(), SSCSEditorDragDropTree::SLATE_EVENT(), STreeView< FRigVMSearchResult >::SLATE_EVENT(), and STreeView< FRigVMSearchResult >::SLATE_EVENT().
SoftwareCursorPosition
FVector2f STableViewBase::SoftwareCursorPosition protected
The current position of the software cursor.
Definition at line 529 of file STableViewBase.h.
TableViewMode
const ETableViewMode::Type STableViewBase::TableViewMode
Is this list backing a tree or just a standalone list.
Definition at line 158 of file STableViewBase.h.
Referenced by SListView< TSharedPtr< FString > >::GetTableViewMode(), and SListView< TSharedPtr< FString > >::UpdateSelectionSet().
TickScrollDelta
float STableViewBase::TickScrollDelta protected
The amount we have scrolled this tick cycle.
Definition at line 502 of file STableViewBase.h.
VerticalScrollBarSlot
SHorizontalBox::FSlot* STableViewBase::VerticalScrollBarSlot
Definition at line 589 of file STableViewBase.h.
WheelScrollMultiplier
float STableViewBase::WheelScrollMultiplier protected
How much to scroll when using mouse wheel.
Definition at line 535 of file STableViewBase.h.
Referenced by SListView< TSharedPtr< FString > >::SLATE_ARGUMENT(), and STileView< ItemType >::SLATE_ARGUMENT().
The documentation for this class was generated from the following file:
Runtime/Slate/Public/Widgets/Views/STableViewBase.h