Unreal Engine 5.6 C++ API: SButton Class Reference
SButton Class Reference
Slate's Buttons are clickable Widgets that can contain arbitrary widgets as its Content().
#include "SButton.h"
Public Member Functions
void Construct (const FArguments &InArgs)
Construct this widget.
virtual FSlateColor GetDisabledForegroundColor () const final
virtual FSlateColor GetForegroundColor () const final
virtual bool IsInteractable () const override
bool IsPressed () const
Returns true if this button is currently pressed.
virtual void OnFocusLost (const FFocusEvent &InFocusEvent) override
Called when this widget loses focus.
virtual FReply OnKeyDown (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent) override
Called after a key is pressed when this widget has focus (this event bubbles if not handled)
virtual FReply OnKeyUp (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent) override
Called after a key is released when this widget has focus.
virtual FReply OnMouseButtonDoubleClick (const FGeometry &InMyGeometry, const FPointerEvent &InMouseEvent) override
Called when a mouse button is double clicked.
virtual FReply OnMouseButtonDown (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent) override
The system calls this method to notify the widget that a mouse button was pressed within it.
virtual FReply OnMouseButtonUp (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent) override
The system calls this method to notify the widget that a mouse button was release within it.
virtual void OnMouseCaptureLost (const FCaptureLostEvent &CaptureLostEvent) override
Called when this widget had captured the mouse, but that capture has been revoked for some reason.
virtual void OnMouseEnter (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent) override
The system will use this event to notify a widget that the cursor has entered it.
virtual void OnMouseLeave (const FPointerEvent &MouseEvent) override
The system will use this event to notify a widget that the cursor has left it.
virtual FReply OnMouseMove (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent) override
The system calls this method to notify the widget that a mouse moved within it.
virtual int32 OnPaint (const FPaintArgs &Args, const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, FSlateWindowElementList &OutDrawElements, int32 LayerId, const FWidgetStyle &InWidgetStyle, bool bParentEnabled) const override
The widget should respond by populating the OutDrawElements array with FDrawElements that represent it and any of its children.
void SetButtonStyle (const FButtonStyle *ButtonStyle)
See ButtonStyle attribute.
void SetClickedSound (TOptional< FSlateSound > InClickedSound)
See ClickedSound attribute.
void SetClickMethod (EButtonClickMethod::Type InClickMethod)
void SetContentPadding (TAttribute< FMargin > InContentPadding)
See ContentPadding attribute.
void SetHoveredSound (TOptional< FSlateSound > InHoveredSound)
See HoveredSound attribute.
void SetOnClicked (FOnClicked InOnClicked)
See OnClicked event.
void SetOnHovered (FSimpleDelegate InOnHovered)
Set OnHovered event.
void SetOnUnhovered (FSimpleDelegate InOnUnhovered)
Set OnUnhovered event.
void SetPressedSound (TOptional< FSlateSound > InPressedSound)
See PressedSound attribute.
void SetPressMethod (EButtonPressMethod::Type InPressMethod)
void SetTouchMethod (EButtonTouchMethod::Type InTouchMethod)
void SimulateClick ()
virtual bool SupportsKeyboardFocus () const override
Checks to see if this widget supports keyboard focus.
Public Member Functions inherited from SCompoundWidget
virtual FChildren * GetChildren () override
Returns the useful children (if any) of this widget.
virtual void OnArrangeChildren (const FGeometry &AllottedGeometry, FArrangedChildren &ArrangedChildren) const override
Compute the Geometry of all the children and add populate the ArrangedChildren list with their values.
virtual void SetVisibility (TAttribute< EVisibility > InVisibility) override final
Public Member Functions inherited from SWidget
template<typename MetaDataType>
void AddMetadata (const TSharedRef< MetaDataType > &AddMe)
Add metadata to this widget.
virtual const FSlateInvalidationRoot * Advanced_AsInvalidationRoot () const
FORCEINLINE TSharedPtr< SWidget > Advanced_GetPaintParentWidget () const
virtual bool Advanced_IsInvalidationRoot () const
virtual bool Advanced_IsWindow () const
Is this widget derivative of SWindow.
void ArrangeChildren (const FGeometry &AllottedGeometry, FArrangedChildren &ArrangedChildren, bool bUpdateAttributes=false) const
Non-virtual entry point for arrange children.
void AssignParentWidget (TSharedPtr< SWidget > InParent)
FORCEINLINE void CacheVolatility ()
Recalculates volatility of the widget and caches the result.
FSlateRect CalculateCullingAndClippingRules (const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, bool &bClipToBounds, bool &bAlwaysClip, bool &bIntersectClipBounds) const
Calculates what if any clipping state changes need to happen when drawing this widget.
bool ConditionallyDetatchParentWidget (SWidget *InExpectedParent)
void EnableToolTipForceField (const bool bEnableForceField)
Sets whether this widget is a "tool tip force field".
FORCEINLINE void ForceVolatile (bool bForce)
Should this widget always appear as volatile for any layout caching host widget.
virtual FChildren * GetAllChildren ()
Returns the children (if any) of this widget that are used by the invalidation system.
template<typename MetaDataType>
TArray< TSharedRef< MetaDataType > > GetAllMetaData () const
Get all metadata of the type provided.
const FGeometry & GetCachedGeometry () const
bool GetCanTick () const
FORCEINLINE EWidgetClipping GetClipping () const
FName GetCreatedInLocation () const
FORCEINLINE FMargin GetCullingBoundsExtension () const
const TOptional< FSlateClippingState > & GetCurrentClippingState () const
Returns the clipping state to clip this widget against its parent.
UE::Slate::FDeprecateVector2DResult GetDesiredSize () const
EFlowDirectionPreference GetFlowDirectionPreference () const
Gets the desired flow direction for the layout.
template<typename MetaDataType>
TSharedPtr< MetaDataType > GetMetaData () const
Get the metadata of the type provided.
const FGeometry & GetPaintSpaceGeometry () const
Gets the last geometry used to Tick the widget.
FORCEINLINE TSharedPtr< SWidget > GetParentWidget () const
const FSlateWidgetPersistentState & GetPersistentState () const
FORCEINLINE EWidgetPixelSnapping GetPixelSnapping () const
const FWidgetProxyHandle GetProxyHandle () const
virtual FString GetReadableLocation () const
virtual float GetRelativeLayoutScale (const int32 ChildIndex, float LayoutScaleMultiplier) const
What is the Child's scale relative to this widget.
FORCEINLINE float GetRenderOpacity () const
FORCEINLINE const TOptional< FSlateRenderTransform > & GetRenderTransform () const
FORCEINLINE UE::Slate::FDeprecateVector2DResult GetRenderTransformPivot () const
FORCEINLINE UE::Slate::FDeprecateVector2DResult GetRenderTransformPivotWithRespectToFlowDirection () const
FORCEINLINE TOptional< FSlateRenderTransform > GetRenderTransformWithRespectToFlowDirection () const
FORCEINLINE TStatId GetStatID (bool bForDeferredUse=false) const
virtual FName GetTag () const
const FGeometry & GetTickSpaceGeometry () const
Gets the last geometry used to Tick the widget.
virtual TSharedPtr< IToolTip > GetToolTip ()
FName GetType () const
FString GetTypeAsString () const
FORCEINLINE EVisibility GetVisibility () const
virtual EWindowZone::Type GetWindowZoneOverride () const
Called when the mouse is moved over the widget's window, to determine if we should report whether OS-specific features should be active at this location (such as a title bar grip, system menu, etc.) Usually you should not need to override this function.
bool HasActiveTimers () const
Does this widget have any active timers?
bool HasAnyUpdateFlags (EWidgetUpdateFlags FlagsToCheck) const
TOptional< EFocusCause > HasAnyUserFocus () const
Gets whether or not any users have this widget focused, and if so the type of focus (first one found).
bool HasAnyUserFocusOrFocusedDescendants () const
bool HasFocusedDescendants () const
virtual bool HasKeyboardFocus () const
Checks to see if this widget currently has the keyboard focus.
bool HasMouseCapture () const
Checks to see if this widget is the current mouse captor.
bool HasMouseCaptureByUser (int32 UserIndex, TOptional< int32 > PointerIndex=TOptional< int32 >()) const
Checks to see if this widget has mouse capture from the provided user.
bool HasRegisteredSlateAttribute () const
bool HasToolTipForceField () const
TOptional< EFocusCause > HasUserFocus (int32 UserIndex) const
Gets whether or not the specified users has this widget focused, and if so the type of focus.
bool HasUserFocusedDescendants (int32 UserIndex) const
Gets whether or not the specified users has this widget or any descendant focused.
void Invalidate (EInvalidateWidgetReason InvalidateReason)
Invalidates the widget from the view of a layout caching widget that may own this widget.
bool IsAttributesUpdatesEnabled () const
bool IsDirectlyHovered () const
FORCEINLINE bool IsEnabled () const
bool IsHovered () const
FORCEINLINE bool IsParentValid () const
FORCEINLINE bool IsVolatile () const
Whether or not a widget is volatile and will update every frame without being invalidated.
FORCEINLINE bool IsVolatileIndirectly () const
This widget is volatile because its parent or some ancestor is volatile.
void MarkPrepassAsDirty ()
In fast path, if the widget is mark, do a full Prepass on its next update to calculate it's desired size.
bool NeedsPrepass () const
virtual FReply OnAnalogValueChanged (const FGeometry &MyGeometry, const FAnalogInputEvent &InAnalogInputEvent)
Called when an analog value changes on a button that supports analog.
virtual FCursorReply OnCursorQuery (const FGeometry &MyGeometry, const FPointerEvent &CursorEvent) const
The system asks each widget under the mouse to provide a cursor.
virtual FReply OnDragDetected (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Called when Slate detects that a widget started to be dragged.
virtual void OnDragEnter (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called during drag and drop when the drag enters a widget.
virtual void OnDragLeave (const FDragDropEvent &DragDropEvent)
Called during drag and drop when the drag leaves a widget.
virtual FReply OnDragOver (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called during drag and drop when the the mouse is being dragged over a widget.
virtual FReply OnDrop (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called when the user is dropping something onto a widget; terminates drag and drop.
virtual void OnFinishedKeyInput ()
All the key (keyboard, gamepay, joystick, etc.) input from this frame has been routed.
virtual void OnFinishedPointerInput ()
All the pointer (mouse, touch, stylus, etc.) events from this frame have been routed.
virtual void OnFocusChanging (const FWeakWidgetPath &PreviousFocusPath, const FWidgetPath &NewWidgetPath, const FFocusEvent &InFocusEvent)
Called whenever a focus path is changing on all the widgets within the old and new focus paths.
virtual FReply OnFocusReceived (const FGeometry &MyGeometry, const FFocusEvent &InFocusEvent)
Called when focus is given to this widget.
virtual FReply OnKeyChar (const FGeometry &MyGeometry, const FCharacterEvent &InCharacterEvent)
Called after a character is entered while this widget has keyboard focus.
virtual TOptional< TSharedRef< SWidget > > OnMapCursor (const FCursorReply &CursorReply) const
After OnCursorQuery has specified a cursor type the system asks each widget under the mouse to map that cursor to a widget.
virtual FReply OnMotionDetected (const FGeometry &MyGeometry, const FMotionEvent &InMotionEvent)
Called when motion is detected (controller or device) e.g.
virtual FReply OnMouseWheel (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Called when the mouse wheel is spun.
virtual FNavigationReply OnNavigation (const FGeometry &MyGeometry, const FNavigationEvent &InNavigationEvent)
Called when navigation is requested e.g.
virtual FReply OnPreviewKeyDown (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
Called after a key is pressed when this widget or a child of this widget has focus If a widget handles this event, OnKeyDown will not be passed to the focused widget.
virtual FReply OnPreviewMouseButtonDown (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Just like OnMouseButtonDown, but tunnels instead of bubbling.
virtual FPopupMethodReply OnQueryPopupMethod () const
Popups can manifest in a NEW OS WINDOW or via an OVERLAY in an existing window.
virtual TOptional< bool > OnQueryShowFocus (const EFocusCause InFocusCause) const
Called to determine if we should render the focus brush.
virtual void OnToolTipClosing ()
Called when a tooltip displayed from this widget is being closed.
virtual FReply OnTouchEnded (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is ended (finger lifted)
virtual FReply OnTouchFirstMove (const FGeometry &MyGeometry, const FPointerEvent &TouchEvent)
Called when a touchpad touch first moves after TouchStarted.
virtual FReply OnTouchForceChanged (const FGeometry &MyGeometry, const FPointerEvent &TouchEvent)
Called when a touchpad touch force changes.
virtual FReply OnTouchGesture (const FGeometry &MyGeometry, const FPointerEvent &GestureEvent)
Called when the user performs a gesture on trackpad.
virtual FReply OnTouchMoved (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is moved (finger moved)
virtual FReply OnTouchStarted (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is started (finger down)
virtual TSharedPtr< FPopupLayer > OnVisualizePopup (const TSharedRef< SWidget > &PopupContent)
Visualize a new pop-up if possible.
virtual bool OnVisualizeTooltip (const TSharedPtr< SWidget > &TooltipContent)
Called when Slate wants to visualize tooltip.
int32 Paint (const FPaintArgs &Args, const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, FSlateWindowElementList &OutDrawElements, int32 LayerId, const FWidgetStyle &InWidgetStyle, bool bParentEnabled) const
Called to tell a widget to paint itself (and it's children).
TSharedRef< FActiveTimerHandle > RegisterActiveTimer (float TickPeriod, FWidgetActiveTimerDelegate TickFunction)
Registers an "active timer" delegate that will execute at some regular interval.
template<typename MetaDataType>
int32 RemoveMetaData (const TSharedRef< MetaDataType > &RemoveMe)
Remove metadata to this widget.
void SetCanTick (bool bInCanTick)
void SetClipping (EWidgetClipping InClipping)
Sets the clipping to bounds rules for this widget.
FORCEINLINE void SetCullingBoundsExtension (const FMargin &InCullingBoundsExtension)
Sets an additional culling padding that is added to a widget to give more leeway when culling widgets.
void SetCursor (const TAttribute< TOptional< EMouseCursor::Type > > &InCursor)
Set the cursor that should appear when this widget is hovered.
void SetEnabled (TAttribute< bool > InEnabledState)
Sets the enabled state of this widget.
void SetFlowDirectionPreference (EFlowDirectionPreference InFlowDirectionPreference)
Sets how content should flow in this panel, based on the current culture.
void SetOnMouseButtonDown (FPointerEventHandler EventHandler)
See OnMouseButtonDown event.
void SetOnMouseButtonUp (FPointerEventHandler EventHandler)
See OnMouseButtonUp event.
void SetOnMouseDoubleClick (FPointerEventHandler EventHandler)
See OnMouseDoubleClick event.
void SetOnMouseEnter (FNoReplyPointerEventHandler EventHandler)
See OnMouseEnter event.
void SetOnMouseLeave (FSimpleNoReplyPointerEventHandler EventHandler)
See OnMouseLeave event.
void SetOnMouseMove (FPointerEventHandler EventHandler)
See OnMouseMove event.
void SetPixelSnapping (EWidgetPixelSnapping InPixelSnappingMethod)
Sets the pixel snapping method for this widget.
FORCEINLINE void SetRenderOpacity (float InRenderOpacity)
FORCEINLINE void SetRenderTransform (TAttribute< TOptional< FSlateRenderTransform > > InTransform)
FORCEINLINE void SetRenderTransformPivot (TAttribute< FVector2D > InTransformPivot)
FORCEINLINE void SetTag (FName InTag)
void SetToolTip (const TAttribute< TSharedPtr< IToolTip > > &InToolTip)
Set the tool tip that should appear when this widget is hovered.
void SetToolTipText (const FText &InToolTipText)
Set the tool tip that should appear when this widget is hovered.
void SetToolTipText (const TAttribute< FText > &ToolTipText)
Set the tool tip that should appear when this widget is hovered.
FORCEINLINE bool ShouldInvalidatePrepassDueToVolatility ()
void SlatePrepass ()
DEPRECATED version of SlatePrepass that assumes no scaling beyond AppScale.
void SlatePrepass (float InLayoutScaleMultiplier)
Descends to leaf-most widgets in the hierarchy and gathers desired sizes on the way up.
virtual void Tick (const FGeometry &AllottedGeometry, const double InCurrentTime, const float InDeltaTime)
Ticks this widget with Geometry.
virtual FString ToString () const
virtual TOptional< FVirtualPointerPosition > TranslateMouseCoordinateForCustomHitTestChild (const SWidget &ChildWidget, const FGeometry &MyGeometry, const FVector2D ScreenSpaceMouseCoordinate, const FVector2D LastScreenSpaceMouseCoordinate) const
void UnRegisterActiveTimer (const TSharedRef< FActiveTimerHandle > &ActiveTimerHandle)
Unregisters an active timer handle.
virtual bool ValidatePathToChild (SWidget *InChild)
Public Member Functions inherited from FSlateControlledConstruction
FSlateControlledConstruction ()=default
virtual ~FSlateControlledConstruction ()=default
virtual const FSlateWidgetClassData & GetWidgetClass () const =0
void operator delete (void *mem)
Public Member Functions inherited from TSharedFromThis< SWidget >
TSharedRef< SWidget, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< SWidget, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Protected Member Functions
SButton ()
Sets the rules to use for determining whether the button was clicked.
virtual FVector2D ComputeDesiredSize (float) const override
Compute the ideal size necessary to display this widget.
void ExecuteHoverStateChanged (bool bPlaySound)
FReply ExecuteOnClick ()
Execute the "OnClicked" delegate, and get the reply.
TSlateAttributeRef< bool > GetAppearPressedAttribute () const
TSlateAttributeRef< FSlateColor > GetBorderForegroundColorAttribute () const
TEnumAsByte< EButtonClickMethod::Type > GetClickMethodFromInputType (const FPointerEvent &MouseEvent) const
Utility function to translate other input click methods to regular ones.
FMargin GetCombinedPadding () const
TSlateAttributeRef< FMargin > GetContentPaddingAttribute () const
bool GetShowDisabledEffect () const
bool IsPreciseTapOrClick (const FPointerEvent &MouseEvent) const
Utility function to determine if the incoming mouse event is for a precise tap or click.
void PlayClickedSound () const
Play the clicked sound.
void PlayHoverSound () const
Play the hovered sound.
void PlayPressedSound () const
Play the pressed sound.
virtual void Press ()
Press the button.
virtual void Release ()
Release the button.
void SetAppearPressed (TAttribute< bool > InValue)
Set the AppearPressed look.
void SetIsFocusable (bool bInIsFocusable)
Set if this button can be focused.
Protected Member Functions inherited from SBorder
TSlateAttributeRef< FSlateColor > GetBorderBackgroundColorAttribute () const
TSlateAttributeRef< const FSlateBrush * > GetBorderImageAttribute () const
FVector2D GetDesiredSizeScale () const
Get the desired size scale multiplier.
TSlateAttributeRef< FVector2D > GetDesiredSizeScaleAttribute () const
bool GetShowDisabledEffect () const
Get whether or not to show the disabled effect when this border is disabled.
TSlateAttributeRef< bool > GetShowDisabledEffectAttribute () const
Protected Member Functions inherited from SCompoundWidget
SCompoundWidget ()
Disallow public construction.
virtual ~SCompoundWidget ()
TSlateAttributeRef< FLinearColor > GetColorAndOpacityAttribute () const
TSlateAttributeRef< FVector2D > GetContentScaleAttribute () const
TSlateAttributeRef< FSlateColor > GetForegroundColorAttribute () const
Protected Member Functions inherited from SWidget
SWidget ()
Hidden default constructor.
virtual ~SWidget ()
Dtor ensures that active timer handles are UnRegistered with the SlateApplication.
FORCEINLINE bool Advanced_InvalidateVolatility ()
Recalculates and caches volatility and returns 'true' if the volatility changed.
virtual void CacheDesiredSize (float InLayoutScaleMultiplier)
The system calls this method.
EFlowDirection ComputeFlowDirection () const
Establishes a new flow direction potentially, if this widget has a particular preference for it and all its children.
virtual bool ComputeVolatility () const
Recomputes the volatility of the widget.
virtual bool CustomPrepass (float LayoutScaleMultiplier)
bool FindChildGeometries (const FGeometry &MyGeometry, const TSet< TSharedRef< SWidget > > &WidgetsToFind, TMap< TSharedRef< SWidget >, FArrangedWidget > &OutResult) const
Find the geometry of a descendant widget.
void FindChildGeometries_Helper (const FGeometry &MyGeometry, const TSet< TSharedRef< SWidget > > &WidgetsToFind, TMap< TSharedRef< SWidget >, FArrangedWidget > &OutResult) const
Actual implementation of FindChildGeometries.
FGeometry FindChildGeometry (const FGeometry &MyGeometry, TSharedRef< SWidget > WidgetToFind) const
Find the geometry of a descendant widget.
virtual TOptional< EMouseCursor::Type > GetCursor () const
The cursor to show when the mouse is hovering over this widget.
TSlateAttributeRef< bool > GetEnabledStateAttribute () const
virtual const FSlateBrush * GetFocusBrush () const
TSlateAttributeRef< bool > GetHoveredAttribute () const
float GetPrepassLayoutScaleMultiplier () const
TSlateAttributeRef< TOptional< FSlateRenderTransform > > GetRenderTransformAttribute () const
TSlateAttributeRef< FVector2D > GetRenderTransformPivotAttribute () const
TSlateAttributeRef< EVisibility > GetVisibilityAttribute () const
void InvalidateChildRemovedFromTree (SWidget &Child)
Called when a child is removed from the tree parent's widget tree either by removing it from a slot.
FORCEINLINE bool IsChildWidgetCulled (const FSlateRect &, const FArrangedWidget &) const
bool IsConstructed () const
Is the widget construction completed (did we called and returned from the Construct() function)
virtual void OnClippingChanged ()
Called when clipping is changed.
void Prepass_ChildLoop (float InLayoutScaleMultiplier, FChildren *MyChildren)
template<typename TargetValueType, typename SourceValueType>
bool SetAttribute (TAttribute< TargetValueType > &TargetValue, const TAttribute< SourceValueType > &SourceValue, EInvalidateWidgetReason BaseInvalidationReason)
Performs the attribute assignment and invalidates the widget minimally based on what actually changed.
void SetDebugInfo (const ANSICHAR *InType, const ANSICHAR *InFile, int32 OnLine, size_t InAllocSize)
Used by Slate to set the runtime debug info about this widget.
void SetHover (TAttribute< bool > InHovered)
Set the hover state.
void SetVolatilePrepass (bool bVolatile)
bool ShouldBeEnabled (bool InParentEnabled) const
Determines if this widget should be enabled.
void SWidgetConstruct (const FSlateBaseNamedArgs &Args)
Construct a SWidget based on initial parameters.
Protected Member Functions inherited from TSharedFromThis< SWidget >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Private Member Functions
ButtonStyle HAlign SLATE_ARGUMENT (EVerticalAlignment, VAlign) SLATE_ATTRIBUTE(FMargin
Vertical alignment.
ButtonStyle HAlign ContentPadding SLATE_ATTRIBUTE (FMargin, NormalPaddingOverride) SLATE_ATTRIBUTE(FMargin
If set, overrides the button style's additional spacing between the button's border and the content when not pressed.
ButtonStyle HAlign ContentPadding PressedPaddingOverride SLATE_ATTRIBUTE (FText, Text) SLATE_EVENT(FOnClicked
The text to display in this button, if no custom content is specified.
SLATE_DECLARE_WIDGET_API (SButton, SBorder, 1) public
SLATE_DEFAULT_SLOT (FArguments, Content) SLATE_STYLE_ARGUMENT(FButtonStyle
Slot for this button's content (optional)
ButtonStyle HAlign ContentPadding PressedPaddingOverride OnClicked OnReleased SLATE_EVENT (FSimpleDelegate, OnHovered) SLATE_EVENT(FSimpleDelegate
ButtonStyle HAlign ContentPadding PressedPaddingOverride OnClicked SLATE_EVENT (FSimpleDelegate, OnPressed) SLATE_EVENT(FSimpleDelegate
Called when the button is pressed.
ButtonStyle SLATE_STYLE_ARGUMENT (FTextBlockStyle, TextStyle) SLATE_ARGUMENT(EHorizontalAlignment
The text style of the button.
void UpdateBorderImage ()
void UpdateDisabledForegroundColor ()
void UpdateForegroundColor ()
void UpdatePadding ()
void UpdatePressStateChanged ()
void UpdateShowDisabledEffect ()
Private Attributes
TSlateAttribute< bool > AppearPressedAttribute
Optional foreground color that will be inherited by all of this widget's contents.
uint8 bIsFocusable:1
Can this button be focused?
uint8 bIsPressed:1
True if this button is currently in a pressed state.
uint8 bIsStyleNormalPaddingOverridden:1
True if NormalPaddingAttribute is overriding the button style's normal padding.
uint8 bIsStylePressedPaddingOverridden:1
True if PressedPaddingAttribute is overriding the button style's pressed padding.
TSlateAttribute< FSlateColor > BorderForegroundColorAttribute
Optional foreground color that will be inherited by all of this widget's contents.
FSlateSound ClickedSound
The Sound to play when the button is clicked.
TEnumAsByte< EButtonClickMethod::Type > ClickMethod
Sets whether a click should be triggered on mouse down, mouse up, or that both a mouse down and up are required.
TSlateAttribute< FMargin > ContentPaddingAttribute
Padding specified by the user; it will be combind with the button's internal padding.
FSlateSound HoveredSound
The Sound to play when the button is hovered.
TSlateAttribute< FMargin > NormalPaddingAttribute
Normal padding override specified by the user, or the button style's normal padding if not being overridden.
FOnClicked OnClicked
The delegate to execute when the button is clicked.
FSimpleDelegate OnHovered
The delegate to execute when the button is hovered.
FSimpleDelegate OnPressed
The delegate to execute when the button is pressed.
FSimpleDelegate OnReleased
The delegate to execute when the button is released.
FSimpleDelegate OnUnhovered
The delegate to execute when the button exit the hovered state.
TSlateAttribute< FMargin > PressedPaddingAttribute
Pressed padding override specified by the user, or the button style's pressed padding if not being overridden.
FVector2D PressedScreenSpacePosition
The location in screenspace the button was pressed.
FSlateSound PressedSound
The Sound to play when the button is pressed.
TEnumAsByte< EButtonPressMethod::Type > PressMethod
How should the button be clicked with keyboard/controller button events?
const FButtonStyle * Style
Style resource for the button.
TEnumAsByte< EButtonTouchMethod::Type > TouchMethod
How should the button be clicked with touch events?
Additional Inherited Members
Static Public Member Functions inherited from FSlateControlledConstruction
static const FSlateWidgetClassData & StaticWidgetClass ()
Static Protected Member Functions inherited from SWidget
static TAttribute< EVisibility > AccessWidgetVisibilityAttribute (const TSharedRef< SWidget > &Widget)
Protected static helper to allow widgets to access the visibility attribute of other widgets directly.
static int32 FindChildUnderMouse (const FArrangedChildren &Children, const FPointerEvent &MouseEvent)
static int32 FindChildUnderPosition (const FArrangedChildren &Children, const UE::Slate::FDeprecateVector2DParameter &ArrangedSpacePosition)
Static Protected Member Functions inherited from TSharedFromThis< SWidget >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Protected Attributes inherited from SCompoundWidget
FCompoundWidgetOneChildSlot ChildSlot
The slot that contains this widget's descendants.
Protected Attributes inherited from SWidget
uint8 bCanHaveChildren: 1
Can the widget ever support children?
uint8 bCanSupportFocus: 1
Can the widget ever support keyboard focus.
uint8 bClippingProxy: 1
Some widgets might be a complex hierarchy of child widgets you never see.
uint8 bHasCustomPrepass: 1
uint8 bHasRelativeLayoutScale: 1
uint8 bVolatilityAlwaysInvalidatesPrepass: 1
if this widget should always invalidate the prepass step when volatile
EWidgetClipping Clipping
Set to true if all content of the widget should clip to the bounds of this widget.
FMargin CullingBoundsExtension
Can be used to enlarge the culling bounds of this widget (pre-intersection), this can be useful if you've got children that you know are using rendering transforms to render outside their standard bounds, if that happens it's possible the parent might be culled before the descendant widget is entirely off screen.
EWidgetPixelSnapping PixelSnappingMethod
When set to EPixelSnappingMethod::SnapToPixel, the widget is drawn at the nearest pixel.
float RenderOpacity
The opacity of the widget.
Detailed Description
Slate's Buttons are clickable Widgets that can contain arbitrary widgets as its Content().
Definition at line 26 of file SButton.h.
Constructor & Destructor Documentation
SButton()
SButton::SButton () protected
Sets the rules to use for determining whether the button was clicked.
This is an advanced setting and generally should be left as the default. How should the button be clicked with touch events? How should the button be clicked with keyboard/controller button events? Sometimes a button should only be mouse-clickable and never keyboard focusable. The sound to play when the button is pressed The sound to play when the button is clicked The sound to play when the button is hovered Which text shaping method should we use? (unset to use the default returned by GetDefaultTextShapingMethod) Which text flow direction should we use? (unset to use the default returned by GetDefaultTextFlowDirection)
References SButton().
Referenced by SButton(), SLATE_DECLARE_WIDGET_API(), and SLATE_EVENT().
Member Function Documentation
ComputeDesiredSize()
virtual FVector2D SButton::ComputeDesiredSize (float LayoutScaleMultiplier) const override protected virtual
Compute the ideal size necessary to display this widget.
For aggregate widgets (e.g. panels) this size should include the size necessary to show all of its children. CacheDesiredSize() guarantees that the size of descendants is computed and cached before that of the parents, so it is safe to call GetDesiredSize() for any children while implementing this method.
Note that ComputeDesiredSize() is meant as an aide to the developer. It is NOT meant to be very robust in many cases. If your widget is simulating a bouncing ball, you should just return a reasonable size; e.g. 160x160. Let the programmer set up a reasonable rule of resizing the bouncy ball simulation.
Parameters
LayoutScaleMultiplier This parameter is safe to ignore for almost all widgets; only really affects text measuring.
Returns
The desired size.
Reimplemented from SBorder.
Construct()
void SButton::Construct (const FArguments & InArgs)
Construct this widget.
Parameters
InArgs The declaration data for this widget
Referenced by SHyperlink::SLATE_ATTRIBUTE().
ExecuteHoverStateChanged()
void SButton::ExecuteHoverStateChanged (bool bPlaySound) protected
ExecuteOnClick()
FReply SButton::ExecuteOnClick () protected
Execute the "OnClicked" delegate, and get the reply.
GetAppearPressedAttribute()
TSlateAttributeRef< bool > SButton::GetAppearPressedAttribute () const inline protected
Returns
the AppearPressed attribute.
Definition at line 273 of file SButton.h.
References AppearPressedAttribute, and TSharedFromThis< SWidget >::SharedThis().
GetBorderForegroundColorAttribute()
TSlateAttributeRef< FSlateColor > SButton::GetBorderForegroundColorAttribute () const inline protected
Returns
the BorderForegroundColor attribute.
Definition at line 261 of file SButton.h.
References BorderForegroundColorAttribute, and TSharedFromThis< SWidget >::SharedThis().
GetClickMethodFromInputType()
TEnumAsByte< EButtonClickMethod::Type > SButton::GetClickMethodFromInputType (const FPointerEvent & MouseEvent) const protected
Utility function to translate other input click methods to regular ones.
References MouseEvent.
GetCombinedPadding()
FMargin SButton::GetCombinedPadding () const protected
Returns
combines the user-specified margin and the button's internal margin.
GetContentPaddingAttribute()
TSlateAttributeRef< FMargin > SButton::GetContentPaddingAttribute () const inline protected
Returns
the ContentPadding attribute.
Definition at line 264 of file SButton.h.
References ContentPaddingAttribute, and TSharedFromThis< SWidget >::SharedThis().
GetDisabledForegroundColor()
virtual FSlateColor SButton::GetDisabledForegroundColor () const final virtual
Returns
the Foreground color that this widget sets when this widget or any of its ancestors are disabled; unset options if the widget does not set a foreground color
Reimplemented from SWidget.
GetForegroundColor()
virtual FSlateColor SButton::GetForegroundColor () const inline final virtual
Returns
the Foreground color that this widget sets; unset options if the widget does not set a foreground color
Reimplemented from SCompoundWidget.
Definition at line 139 of file SButton.h.
References GetForegroundColor().
Referenced by GetForegroundColor().
GetShowDisabledEffect()
bool SButton::GetShowDisabledEffect () const protected
Returns
True if the disabled effect should be shown.
IsInteractable()
virtual bool SButton::IsInteractable () const override virtual
Returns
Is this widget interactive or not? Defaults to false
Reimplemented from SWidget.
IsPreciseTapOrClick()
bool SButton::IsPreciseTapOrClick (const FPointerEvent & MouseEvent) const protected
Utility function to determine if the incoming mouse event is for a precise tap or click.
References MouseEvent.
IsPressed()
bool SButton::IsPressed () const inline
Returns true if this button is currently pressed.
Returns
True if pressed, otherwise false
Note
IsPressed used to be virtual. Use SetAppearPressed to assign an attribute if you need to override the default behavior.
Definition at line 153 of file SButton.h.
References AppearPressedAttribute, bIsPressed, and IsPressed().
Referenced by IsPressed().
OnFocusLost()
virtual void SButton::OnFocusLost (const FFocusEvent & InFocusEvent) override virtual
Called when this widget loses focus.
This event does not bubble.
Parameters
InFocusEvent The FocusEvent
Reimplemented from SWidget.
OnKeyDown()
virtual FReply SButton::OnKeyDown (const FGeometry & MyGeometry, const FKeyEvent & InKeyEvent) override virtual
Called after a key is pressed when this widget has focus (this event bubbles if not handled)
Parameters
MyGeometry The Geometry of the widget receiving the event
InKeyEvent Key event
Returns
Returns whether the event was handled, along with other possible actions
Reimplemented from SWidget.
OnKeyUp()
virtual FReply SButton::OnKeyUp (const FGeometry & MyGeometry, const FKeyEvent & InKeyEvent) override virtual
Called after a key is released when this widget has focus.
Parameters
MyGeometry The Geometry of the widget receiving the event
InKeyEvent Key event
Returns
Returns whether the event was handled, along with other possible actions
Reimplemented from SWidget.
OnMouseButtonDoubleClick()
virtual FReply SButton::OnMouseButtonDoubleClick (const FGeometry & InMyGeometry, const FPointerEvent & InMouseEvent) override virtual
Called when a mouse button is double clicked.
Override this in derived classes.
Parameters
InMyGeometry Widget geometry
InMouseEvent Mouse button event
Returns
Returns whether the event was handled, along with other possible actions
Reimplemented from SWidget.
OnMouseButtonDown()
virtual FReply SButton::OnMouseButtonDown (const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) override virtual
The system calls this method to notify the widget that a mouse button was pressed within it.
This event is bubbled.
Parameters
MyGeometry The Geometry of the widget receiving the event
MouseEvent Information about the input event
Returns
Whether the event was handled along with possible requests for the system to take action.
Reimplemented from SWidget.
Reimplemented in SRigVMVariantCapsule.
References MouseEvent.
OnMouseButtonUp()
virtual FReply SButton::OnMouseButtonUp (const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) override virtual
The system calls this method to notify the widget that a mouse button was release within it.
This event is bubbled.
Parameters
MyGeometry The Geometry of the widget receiving the event
MouseEvent Information about the input event
Returns
Whether the event was handled along with possible requests for the system to take action.
Reimplemented from SWidget.
References MouseEvent.
OnMouseCaptureLost()
virtual void SButton::OnMouseCaptureLost (const FCaptureLostEvent & CaptureLostEvent) override virtual
Called when this widget had captured the mouse, but that capture has been revoked for some reason.
Reimplemented from SWidget.
OnMouseEnter()
virtual void SButton::OnMouseEnter (const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) override virtual
The system will use this event to notify a widget that the cursor has entered it.
This event is uses a custom bubble strategy.
Parameters
MyGeometry The Geometry of the widget receiving the event
MouseEvent Information about the input event
Reimplemented from SWidget.
References MouseEvent.
OnMouseLeave()
virtual void SButton::OnMouseLeave (const FPointerEvent & MouseEvent) override virtual
The system will use this event to notify a widget that the cursor has left it.
This event is uses a custom bubble strategy.
Parameters
MouseEvent Information about the input event
Reimplemented from SWidget.
References MouseEvent.
OnMouseMove()
virtual FReply SButton::OnMouseMove (const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) override virtual
The system calls this method to notify the widget that a mouse moved within it.
This event is bubbled.
Parameters
MyGeometry The Geometry of the widget receiving the event
MouseEvent Information about the input event
Returns
Whether the event was handled along with possible requests for the system to take action.
Reimplemented from SWidget.
References MouseEvent.
OnPaint()
virtual int32 SButton::OnPaint (const FPaintArgs & Args, const FGeometry & AllottedGeometry, const FSlateRect & MyCullingRect, FSlateWindowElementList & OutDrawElements, int32 LayerId, const FWidgetStyle & InWidgetStyle, bool bParentEnabled) const override virtual
The widget should respond by populating the OutDrawElements array with FDrawElements that represent it and any of its children.
Called by the non-virtual OnPaint to enforce pre/post conditions during OnPaint.
Parameters
Args All the arguments necessary to paint this widget (
Todo
umg: move all params into this struct)
Parameters
AllottedGeometry The FGeometry that describes an area in which the widget should appear.
MyCullingRect The rectangle representing the bounds currently being used to completely cull widgets. Unless IsChildWidgetCulled(...) returns true, you should paint the widget.
OutDrawElements A list of FDrawElements to populate with the output.
LayerId The Layer onto which this widget should be rendered.
InColorAndOpacity Color and Opacity to be applied to all the descendants of the widget being painted
bParentEnabled True if the parent of this widget is enabled.
Returns
The maximum layer ID attained by this widget or any of its children.
Reimplemented from SBorder.
References SWidget::FSlateWindowElementList.
PlayClickedSound()
void SButton::PlayClickedSound () const protected
Play the clicked sound.
PlayHoverSound()
void SButton::PlayHoverSound () const protected
Play the hovered sound.
PlayPressedSound()
void SButton::PlayPressedSound () const protected
Play the pressed sound.
Press()
virtual void SButton::Press () protected virtual
Press the button.
Release()
virtual void SButton::Release () protected virtual
Release the button.
SetAppearPressed()
void SButton::SetAppearPressed (TAttribute< bool > InValue) inline protected
Set the AppearPressed look.
Definition at line 267 of file SButton.h.
References AppearPressedAttribute, and MoveTemp().
SetButtonStyle()
void SButton::SetButtonStyle (const FButtonStyle * ButtonStyle)
See ButtonStyle attribute.
SetClickedSound()
void SButton::SetClickedSound (TOptional< FSlateSound > InClickedSound)
See ClickedSound attribute.
SetClickMethod()
void SButton::SetClickMethod (EButtonClickMethod::Type InClickMethod)
SetContentPadding()
void SButton::SetContentPadding (TAttribute< FMargin > InContentPadding)
See ContentPadding attribute.
SetHoveredSound()
void SButton::SetHoveredSound (TOptional< FSlateSound > InHoveredSound)
See HoveredSound attribute.
SetIsFocusable()
void SButton::SetIsFocusable (bool bInIsFocusable) inline protected
Set if this button can be focused.
Definition at line 252 of file SButton.h.
References bIsFocusable.
SetOnClicked()
void SButton::SetOnClicked (FOnClicked InOnClicked)
See OnClicked event.
SetOnHovered()
void SButton::SetOnHovered (FSimpleDelegate InOnHovered)
Set OnHovered event.
SetOnUnhovered()
void SButton::SetOnUnhovered (FSimpleDelegate InOnUnhovered)
Set OnUnhovered event.
SetPressedSound()
void SButton::SetPressedSound (TOptional< FSlateSound > InPressedSound)
See PressedSound attribute.
SetPressMethod()
void SButton::SetPressMethod (EButtonPressMethod::Type InPressMethod)
SetTouchMethod()
void SButton::SetTouchMethod (EButtonTouchMethod::Type InTouchMethod)
SimulateClick()
void SButton::SimulateClick ()
SLATE_ARGUMENT()
ButtonStyle HAlign SButton::SLATE_ARGUMENT (EVerticalAlignment , VAlign) private
Vertical alignment.
Spacing between button's border and the content.
References SLATE_ARGUMENT(), and SLATE_ATTRIBUTE().
Referenced by SLATE_ARGUMENT(), SLATE_EVENT(), and SLATE_STYLE_ARGUMENT().
SLATE_ATTRIBUTE() [1/2]
ButtonStyle HAlign ContentPadding SButton::SLATE_ATTRIBUTE (FMargin , NormalPaddingOverride) private
If set, overrides the button style's additional spacing between the button's border and the content when not pressed.
If set, overrides the button style's additional spacing between the button's border and the content when pressed.
References SLATE_ATTRIBUTE().
Referenced by SLATE_ARGUMENT(), SLATE_ATTRIBUTE(), SLATE_ATTRIBUTE(), and SLATE_EVENT().
SLATE_ATTRIBUTE() [2/2]
ButtonStyle HAlign ContentPadding PressedPaddingOverride SButton::SLATE_ATTRIBUTE (FText , Text) private
The text to display in this button, if no custom content is specified.
Called when the button is clicked
References OnClicked, SLATE_ATTRIBUTE(), SLATE_EVENT(), and Text.
SLATE_DECLARE_WIDGET_API()
SButton::SLATE_DECLARE_WIDGET_API (SButton , SBorder , 1) inline private
Definition at line 28 of file SButton.h.
References SButton().
SLATE_DEFAULT_SLOT()
SButton::SLATE_DEFAULT_SLOT (FArguments , Content) private
Slot for this button's content (optional)
The visual style of the button
SLATE_EVENT() [1/2]
ButtonStyle HAlign ContentPadding PressedPaddingOverride OnClicked OnReleased SButton::SLATE_EVENT (FSimpleDelegate , OnHovered) private
References SButton(), ClickMethod, OnHovered, OnUnhovered, PressMethod, SLATE_ARGUMENT(), SLATE_ATTRIBUTE(), SBorder::SLATE_END_ARGS(), SLATE_EVENT(), and TouchMethod.
SLATE_EVENT() [2/2]
ButtonStyle HAlign ContentPadding PressedPaddingOverride OnClicked SButton::SLATE_EVENT (FSimpleDelegate , OnPressed) private
Called when the button is pressed.
Called when the button is released
References OnPressed, OnReleased, and SLATE_EVENT().
Referenced by SLATE_ATTRIBUTE(), SHyperlink::SLATE_ATTRIBUTE(), SLATE_EVENT(), and SLATE_EVENT().
SLATE_STYLE_ARGUMENT()
ButtonStyle SButton::SLATE_STYLE_ARGUMENT (FTextBlockStyle , TextStyle) private
The text style of the button.
Horizontal alignment
References SLATE_ARGUMENT(), and SLATE_STYLE_ARGUMENT().
Referenced by SLATE_STYLE_ARGUMENT().
SupportsKeyboardFocus()
virtual bool SButton::SupportsKeyboardFocus () const override virtual
Checks to see if this widget supports keyboard focus.
Override this in derived classes.
Returns
True if this widget can take keyboard focus
Reimplemented from SWidget.
UpdateBorderImage()
void SButton::UpdateBorderImage () private
UpdateDisabledForegroundColor()
void SButton::UpdateDisabledForegroundColor () private
UpdateForegroundColor()
void SButton::UpdateForegroundColor () private
UpdatePadding()
void SButton::UpdatePadding () private
UpdatePressStateChanged()
void SButton::UpdatePressStateChanged () private
UpdateShowDisabledEffect()
void SButton::UpdateShowDisabledEffect () private
Field Documentation
AppearPressedAttribute
TSlateAttribute<bool> SButton::AppearPressedAttribute private
Optional foreground color that will be inherited by all of this widget's contents.
Definition at line 345 of file SButton.h.
Referenced by GetAppearPressedAttribute(), IsPressed(), and SetAppearPressed().
bIsFocusable
uint8 SButton::bIsFocusable private
Can this button be focused?
Definition at line 324 of file SButton.h.
Referenced by SetIsFocusable().
bIsPressed
uint8 SButton::bIsPressed private
True if this button is currently in a pressed state.
Definition at line 327 of file SButton.h.
Referenced by IsPressed().
bIsStyleNormalPaddingOverridden
uint8 SButton::bIsStyleNormalPaddingOverridden private
True if NormalPaddingAttribute is overriding the button style's normal padding.
Definition at line 330 of file SButton.h.
bIsStylePressedPaddingOverridden
uint8 SButton::bIsStylePressedPaddingOverridden private
True if PressedPaddingAttribute is overriding the button style's pressed padding.
Definition at line 333 of file SButton.h.
BorderForegroundColorAttribute
TSlateAttribute<FSlateColor> SButton::BorderForegroundColorAttribute private
Optional foreground color that will be inherited by all of this widget's contents.
Definition at line 337 of file SButton.h.
Referenced by GetBorderForegroundColorAttribute().
ClickedSound
FSlateSound SButton::ClickedSound private
The Sound to play when the button is clicked.
Definition at line 312 of file SButton.h.
ClickMethod
TEnumAsByte<EButtonClickMethod::Type> SButton::ClickMethod private
Sets whether a click should be triggered on mouse down, mouse up, or that both a mouse down and up are required.
Definition at line 315 of file SButton.h.
Referenced by SLATE_EVENT().
ContentPaddingAttribute
TSlateAttribute<FMargin> SButton::ContentPaddingAttribute private
Padding specified by the user; it will be combind with the button's internal padding.
Definition at line 339 of file SButton.h.
Referenced by GetContentPaddingAttribute().
HoveredSound
FSlateSound SButton::HoveredSound private
The Sound to play when the button is hovered.
Definition at line 306 of file SButton.h.
NormalPaddingAttribute
TSlateAttribute<FMargin> SButton::NormalPaddingAttribute private
Normal padding override specified by the user, or the button style's normal padding if not being overridden.
Definition at line 341 of file SButton.h.
OnClicked
FOnClicked SButton::OnClicked private
The delegate to execute when the button is clicked.
Definition at line 291 of file SButton.h.
Referenced by SLATE_ATTRIBUTE(), SHyperlink::SLATE_ATTRIBUTE(), and SRigVMVariantCapsule::SLATE_EVENT().
OnHovered
FSimpleDelegate SButton::OnHovered private
The delegate to execute when the button is hovered.
Definition at line 300 of file SButton.h.
Referenced by SLATE_EVENT().
OnPressed
FSimpleDelegate SButton::OnPressed private
The delegate to execute when the button is pressed.
Definition at line 294 of file SButton.h.
Referenced by SLATE_EVENT().
OnReleased
FSimpleDelegate SButton::OnReleased private
The delegate to execute when the button is released.
Definition at line 297 of file SButton.h.
Referenced by SLATE_EVENT().
OnUnhovered
FSimpleDelegate SButton::OnUnhovered private
The delegate to execute when the button exit the hovered state.
Definition at line 303 of file SButton.h.
Referenced by SLATE_EVENT().
PressedPaddingAttribute
TSlateAttribute<FMargin> SButton::PressedPaddingAttribute private
Pressed padding override specified by the user, or the button style's pressed padding if not being overridden.
Definition at line 343 of file SButton.h.
PressedScreenSpacePosition
FVector2D SButton::PressedScreenSpacePosition private
The location in screenspace the button was pressed.
Definition at line 286 of file SButton.h.
PressedSound
FSlateSound SButton::PressedSound private
The Sound to play when the button is pressed.
Definition at line 309 of file SButton.h.
PressMethod
TEnumAsByte<EButtonPressMethod::Type> SButton::PressMethod private
How should the button be clicked with keyboard/controller button events?
Definition at line 321 of file SButton.h.
Referenced by SLATE_EVENT().
Style
const FButtonStyle* SButton::Style private
Style resource for the button.
Definition at line 289 of file SButton.h.
Referenced by SHyperlink::SLATE_ATTRIBUTE().
TouchMethod
TEnumAsByte<EButtonTouchMethod::Type> SButton::TouchMethod private
How should the button be clicked with touch events?
Definition at line 318 of file SButton.h.
Referenced by SLATE_EVENT().
The documentation for this class was generated from the following file:
Runtime/Slate/Public/Widgets/Input/SButton.h