Unreal Engine 5.6 C++ API: FAssetTagValueRef Class Reference
FAssetTagValueRef Class Reference
Reference to a tagged value in a FAssetDataTagMapSharedView.
#include "AssetDataTagMap.h"
Data Structures
class FFixedTagValue
Public Member Functions
FAssetTagValueRef ()=default
FAssetTagValueRef (const FAssetTagValueRef &)=default
FAssetTagValueRef (const FString *Str)
FAssetTagValueRef (FAssetTagValueRef &&)=default
FAssetTagValueRef (uint32 StoreIndex, FixedTagPrivate::FValueId ValueId)
FAssetRegistryExportPath AsExportPath () const
FName AsName () const
FString AsString () const
FText AsText () const
bool Equals (FStringView Str) const
int64 GetResourceSize () const
Measure how much memory is used by the value.
FString GetStorageString () const
Coerce the type to a Complex String capable of representing the type.
FString GetValue () const
bool IsSet () const
FAssetTagValueRef & operator= (const FAssetTagValueRef &)=default
FAssetTagValueRef & operator= (FAssetTagValueRef &&)=default
bool TryGetAsText (FText &Out) const
Private Types
using FStringPointer = const FString*
Private Member Functions
FixedTagPrivate::FValueHandle AsFixed () const
const FString & AsLoose () const
uint64 IsFixed () const
FString ToLoose () const
Copy this's value (whether loose or fixed) into the loose format.
bool TryGetAsMarshalledText (FixedTagPrivate::FMarshalledText &Out) const
Return whether this's value is a MarshalledFText, and copy it into out parameter if so.
Private Attributes
union {
uint64 Bits = 0
FFixedTagValue Fixed
FStringPointer Loose
};
friend FAssetRegistryState
Friends
class FAssetDataTagMapSharedView
class FixedTagPrivate::FStoreBuilder
bool operator!= (const FString &A, FAssetTagValueRef B)
bool operator!= (FAssetTagValueRef A, const FString &B)
bool operator!= (FAssetTagValueRef A, FStringView B)
bool operator!= (FStringView A, FAssetTagValueRef B)
bool operator== (const FString &A, FAssetTagValueRef B)
bool operator== (FAssetTagValueRef A, const FString &B)
bool operator== (FAssetTagValueRef A, FStringView B)
bool operator== (FStringView A, FAssetTagValueRef B)
Detailed Description
Reference to a tagged value in a FAssetDataTagMapSharedView.
Helps avoid needless FString conversions when using fixed / cooked tag values that are stored as FName, FText or FAssetRegistryExportPath.
Definition at line 181 of file AssetDataTagMap.h.
Member Typedef Documentation
FStringPointer
using FAssetTagValueRef::FStringPointer = const FString* private
Definition at line 218 of file AssetDataTagMap.h.
Constructor & Destructor Documentation
FAssetTagValueRef() [1/5]
FAssetTagValueRef::FAssetTagValueRef () default
Referenced by FAssetTagValueRef(), FAssetTagValueRef(), operator!=, operator!=, operator!=, operator!=, operator=(), operator=(), operator==, operator==, operator==, and operator==.
FAssetTagValueRef() [2/5]
FAssetTagValueRef::FAssetTagValueRef (const FAssetTagValueRef &) default
References FAssetTagValueRef().
FAssetTagValueRef() [3/5]
FAssetTagValueRef::FAssetTagValueRef (FAssetTagValueRef &&) default
References FAssetTagValueRef().
FAssetTagValueRef() [4/5]
FAssetTagValueRef::FAssetTagValueRef (const FString * Str) inline explicit
Definition at line 236 of file AssetDataTagMap.h.
References Loose.
FAssetTagValueRef() [5/5]
FAssetTagValueRef::FAssetTagValueRef (uint32 StoreIndex, FixedTagPrivate::FValueId ValueId) inline
Definition at line 237 of file AssetDataTagMap.h.
References Fixed.
Member Function Documentation
AsExportPath()
FAssetRegistryExportPath FAssetTagValueRef::AsExportPath () const
Referenced by FAssetData::GetTagValueRef().
AsFixed()
FixedTagPrivate::FValueHandle FAssetTagValueRef::AsFixed () const private
AsLoose()
const FString & FAssetTagValueRef::AsLoose () const private
AsName()
FName FAssetTagValueRef::AsName () const
Referenced by FAssetData::GetTagValue(), and FAssetData::GetTagValueRef().
AsString()
FString FAssetTagValueRef::AsString () const
Referenced by FAssetData::GetTagValue(), FAssetData::GetTagValueRef(), and GetValue().
AsText()
FText FAssetTagValueRef::AsText () const
Referenced by FAssetData::GetTagValue().
Equals()
bool FAssetTagValueRef::Equals (FStringView Str) const
Referenced by FAssetDataTagMapSharedView::ContainsKeyValue().
GetResourceSize()
int64 FAssetTagValueRef::GetResourceSize () const
Measure how much memory is used by the value.
Does not account for deduplication, adding the results for keys sharing a duplicated value will overreport how much memory is used.
GetStorageString()
FString FAssetTagValueRef::GetStorageString () const inline
Coerce the type to a Complex String capable of representing the type.
Definition at line 252 of file AssetDataTagMap.h.
References ToLoose().
GetValue()
FString FAssetTagValueRef::GetValue () const inline
Definition at line 250 of file AssetDataTagMap.h.
References AsString().
Referenced by FAssetData::GetTagValue(), and FAssetData::GetTagValueRef().
IsFixed()
uint64 FAssetTagValueRef::IsFixed () const inline private
Definition at line 228 of file AssetDataTagMap.h.
References Fixed.
IsSet()
bool FAssetTagValueRef::IsSet () const inline
Definition at line 242 of file AssetDataTagMap.h.
References Bits.
Referenced by FAssetDataTagMapSharedView::Contains(), FAssetData::GetTagValue(), FAssetData::GetTagValue(), FAssetData::GetTagValue(), FAssetData::GetTagValue(), FAssetData::GetTagValueRef(), and FAssetData::GetTagValueRef().
operator=() [1/2]
FAssetTagValueRef & FAssetTagValueRef::operator= (const FAssetTagValueRef &) default
References FAssetTagValueRef().
operator=() [2/2]
FAssetTagValueRef & FAssetTagValueRef::operator= (FAssetTagValueRef &&) default
References FAssetTagValueRef().
ToLoose()
FString FAssetTagValueRef::ToLoose () const private
Copy this's value (whether loose or fixed) into the loose format.
The returned loose value is in StorageFormat (e.g. complex strings) rather than display format.
Referenced by GetStorageString().
TryGetAsMarshalledText()
bool FAssetTagValueRef::TryGetAsMarshalledText (FixedTagPrivate::FMarshalledText & Out) const private
Return whether this's value is a MarshalledFText, and copy it into out parameter if so.
TryGetAsText()
bool FAssetTagValueRef::TryGetAsText (FText & Out) const
Friends And Related Symbol Documentation
FAssetDataTagMapSharedView
friend class FAssetDataTagMapSharedView friend
Definition at line 183 of file AssetDataTagMap.h.
References FAssetDataTagMapSharedView.
Referenced by FAssetDataTagMapSharedView.
FixedTagPrivate::FStoreBuilder
friend class FixedTagPrivate::FStoreBuilder friend
Definition at line 270 of file AssetDataTagMap.h.
operator!= [1/4]
bool operator!= (const FString & A, FAssetTagValueRef B) friend
Definition at line 282 of file AssetDataTagMap.h.
References FAssetTagValueRef(), A, and B.
operator!= [2/4]
bool operator!= (FAssetTagValueRef A, const FString & B) friend
Definition at line 280 of file AssetDataTagMap.h.
References FAssetTagValueRef(), A, and B.
operator!= [3/4]
bool operator!= (FAssetTagValueRef A, FStringView B) friend
Definition at line 274 of file AssetDataTagMap.h.
References FAssetTagValueRef(), A, and B.
operator!= [4/4]
bool operator!= (FStringView A, FAssetTagValueRef B) friend
Definition at line 276 of file AssetDataTagMap.h.
References FAssetTagValueRef(), A, and B.
operator== [1/4]
bool operator== (const FString & A, FAssetTagValueRef B) friend
Definition at line 281 of file AssetDataTagMap.h.
References FAssetTagValueRef(), A, and B.
operator== [2/4]
bool operator== (FAssetTagValueRef A, const FString & B) friend
Definition at line 279 of file AssetDataTagMap.h.
References FAssetTagValueRef(), A, and B.
operator== [3/4]
bool operator== (FAssetTagValueRef A, FStringView B) friend
Definition at line 273 of file AssetDataTagMap.h.
References FAssetTagValueRef(), A, and B.
operator== [4/4]
bool operator== (FStringView A, FAssetTagValueRef B) friend
Definition at line 275 of file AssetDataTagMap.h.
References FAssetTagValueRef(), A, and B.
Field Documentation
[union]
union { ... } FAssetTagValueRef
Bits
uint64 FAssetTagValueRef::Bits = 0
Definition at line 225 of file AssetDataTagMap.h.
Referenced by IsSet().
FAssetRegistryState
friend FAssetTagValueRef::FAssetRegistryState private
Definition at line 271 of file AssetDataTagMap.h.
Fixed
FFixedTagValue FAssetTagValueRef::Fixed
Definition at line 224 of file AssetDataTagMap.h.
Referenced by FAssetTagValueRef(), and IsFixed().
Loose
FStringPointer FAssetTagValueRef::Loose
Definition at line 223 of file AssetDataTagMap.h.
Referenced by FAssetTagValueRef().
The documentation for this class was generated from the following file:
Runtime/CoreUObject/Public/AssetRegistry/AssetDataTagMap.h