Unreal Engine 5.6 C++ API: FArrayProperty Class Reference
FArrayProperty Class Reference
#include "UnrealType.h"
Public Types
enum { CPPSize = sizeof(FScriptArray) , CPPAlignment = alignof(FScriptArray) }
Type of the CPP property.
using TCppType = TTypeFundamentals::TCppType
using TTypeFundamentals = Super::TTypeFundamentals
Public Types inherited from TProperty< FScriptArray, FProperty >
typedef FProperty Super
typedef FScriptArray TCppType
typedef TPropertyTypeFundamentals< FScriptArray > TTypeFundamentals
Public Types inherited from FField
typedef FField BaseFieldClass
typedef FFieldClass FieldTypeClass
using FLinkedListBuilder = TLinkedListBuilder<FField>
typedef FField Super
typedef FField ThisClass
Public Types inherited from TPropertyTypeFundamentals< FScriptArray >
enum
typedef FScriptArray TCppType
Type of the CPP property.
Public Member Functions
FArrayProperty (FFieldVariant InOwner, const FName &InName, EObjectFlags InObjectFlags, EArrayPropertyFlags InArrayPropertyFlags=EArrayPropertyFlags::None)
FArrayProperty (FFieldVariant InOwner, const UECodeGen_Private::FArrayPropertyParams &Prop)
Constructor used for constructing compiled in properties.
virtual ~FArrayProperty ()
virtual void AddCppProperty (FProperty *Property) override
virtual void AddReferencedObjects (FReferenceCollector &Collector) override
virtual bool CanSerializeFromTypeName (UE::FPropertyTypeName Type) const override
Returns true if the type of this property matches the type name.
virtual void ClearIntrusiveOptionalValue (void *Data) const override
Set the value to it's special unset state.
virtual void ClearValueInternal (void *Data) const override
virtual bool ContainsObjectReference (TArray< const FStructProperty * > &EncounteredStructProps, EPropertyObjectReferenceType InReferenceType=EPropertyObjectReferenceType::Strong) const override
Returns true if this property, or in the case of e.g.
virtual EConvertFromTypeResult ConvertFromType (const FPropertyTag &Tag, FStructuredArchive::FSlot Slot, uint8 *Data, UStruct *DefaultsStruct, const uint8 *Defaults) override
Allows a property to implement backwards compatibility handling for tagged properties.
virtual void CopyValuesInternal (void *Dest, void const *Src, int32 Count) const override
virtual void DestroyValueInternal (void *Dest) const override
virtual void EmitIntrusiveOptionalReferenceInfo (UE::GC::FSchemaBuilder &Schema, int32 BaseOffset, TArray< const FStructProperty * > &EncounteredStructProps, UE::GC::FPropertyStack &DebugPath) override
For properties returning true from HasIntrusiveUnsetOptionalState which also contain object references, emit information for the garbage collector to safely gather the references from the value whether the optional value is set or unset.
virtual void EmitReferenceInfo (UE::GC::FSchemaBuilder &Schema, int32 BaseOffset, TArray< const FStructProperty * > &EncounteredStructProps, UE::GC::FPropertyStack &DebugPath) override
Emits tokens used by realtime garbage collection code to passed in ReferenceTokenStream.
virtual FString GetCPPMacroType (FString &ExtendedTypeText) const override
virtual FString GetCPPType (FString *ExtendedTypeText, uint32 CPPExportFlags) const override
FString GetCPPTypeCustom (FString *ExtendedTypeText, uint32 CPPExportFlags, const FString &InnerTypeText, const FString &InInnerExtendedTypeText) const
virtual FField * GetInnerFieldByName (const FName &InName) override
Returns an inner field by name if the field has any.
virtual void GetInnerFields (TArray< FField * > &OutFields) override
Fills the provided array with all inner fields this field owns (recursively)
virtual int32 GetMinAlignment () const override
virtual void GetPreloadDependencies (TArray< UObject * > &OutDeps) override
virtual void * GetValueAddressAtIndex_Direct (const FProperty *Inner, void *InValueAddress, int32 Index) const override
Gets value address at given index inside of a static array or container.
virtual bool HasIntrusiveUnsetOptionalState () const override
virtual bool Identical (const void *A, const void *B, uint32 PortFlags) const override
virtual void InitializeIntrusiveUnsetOptionalValue (void *Data) const override
Returns whether this type has a special state for an unset TOptional meaning the size TOptional<T> and T are the same.
virtual void InitializeValueInternal (void *Dest) const override
virtual void InstanceSubobjects (void *Data, void const *DefaultData, TNotNull< UObject * > Owner, struct FObjectInstancingGraph *InstanceGraph) override
Creates new copies of components.
virtual bool IsIntrusiveOptionalValueSet (const void *Data) const override
Returns whether an optional value of this inner type is unset.
virtual void LinkInternal (FArchive &Ar) override
virtual bool LoadTypeName (UE::FPropertyTypeName Type, const FPropertyTag *Tag=nullptr) override
Restores this property and its owned properties from the type name.
virtual bool NetSerializeItem (FArchive &Ar, UPackageMap *Map, void *Data, TArray< uint8 > *MetaData=NULL) const override
virtual void PostDuplicate (const FField &InField) override
Fixups after duplicating a Field.
virtual void * ResolveVisitedPathInfo (void *Data, const FPropertyVisitorInfo &Info) const override
Attempt to resolve the given inner path info against this outer property to get the inner property value.
virtual bool SameType (const FProperty *Other) const override
returns true, if Other is property of exactly the same type
virtual void SaveTypeName (UE::FPropertyTypeNameBuilder &Type) const override
Saves the type name of this property and its owned properties.
virtual void Serialize (FArchive &Ar) override
virtual void SerializeItem (FStructuredArchive::FSlot Slot, void *Value, void const *Defaults) const override
virtual bool UseBinaryOrNativeSerialization (const FArchive &Ar) const override
virtual EPropertyVisitorControlFlow Visit (FPropertyVisitorContext &Context, const TFunctionRef< EPropertyVisitorControlFlow(const FPropertyVisitorContext &)> InFunc) const override
Visits this property and allows recursion into the inner properties This method allows callers to visit inner properties without knowing about its container type as opposed to TPropertyIterator.
Public Member Functions inherited from TProperty< FScriptArray, FProperty >
TProperty (EInternal InInernal, FFieldClass *InClass)
FORCEINLINE TCppType GetOptionalPropertyValue_InContainer (void const *B, int32 ArrayIndex=0) const
Get the value of the property from a container address, unless it is NULL, then return the default value.
FORCEINLINE TCppType const & GetPropertyValue_InContainer (void const *A, int32 ArrayIndex=0) const
Get the value of the property from a container address.
FORCEINLINE TCppType const * GetPropertyValuePtr_InContainer (void const *A, int32 ArrayIndex=0) const
Convert the address of a container to the address of the property value, in the proper type.
FORCEINLINE void GetValue_InContainer (void const *InContainer, TCppType *OutValue) const
FORCEINLINE void SetPropertyValue_InContainer (void *A, TCppType const &Value, int32 ArrayIndex=0) const
Set the value of a property in a container.
FORCEINLINE void SetValue_InContainer (void *OutContainer, const TCppType &InValue) const
Public Member Functions inherited from FProperty
FProperty (FFieldVariant InOwner, const FName &InName, EObjectFlags InObjectFlags)
FProperty (FFieldVariant InOwner, const UECodeGen_Private::FPropertyParamsBaseWithOffset &Prop, EPropertyFlags AdditionalPropertyFlags=CPF_None)
Constructor used for constructing compiled-in properties.
FProperty (FFieldVariant InOwner, const UECodeGen_Private::FPropertyParamsBaseWithoutOffset &Prop, EPropertyFlags AdditionalPropertyFlags=CPF_None)
Constructor used for constructing compiled-in properties.
void * AllocateAndInitializeValue () const
Allocates and initializes memory to hold a value this property represents.
virtual void CallGetter (const void *Container, void *OutValue) const
Calls the native getter function for this property.
virtual void CallSetter (void *Container, const void *InValue) const
Calls the native setter function for this property.
FORCEINLINE void ClearPropertyFlags (EPropertyFlags NewFlags)
FORCEINLINE void ClearValue (void *Data) const
Zeros the value for this property.
FORCEINLINE void ClearValue_InContainer (void *Data, int32 ArrayIndex=0) const
Zeros the value for this property.
template<typename ValueType>
FORCEINLINE ValueType * ContainerPtrToValuePtr (UObject *ContainerPtr, int32 ArrayIndex=0) const
Get the pointer to property value in a supplied 'container'.
template<typename ValueType>
FORCEINLINE ValueType const * ContainerPtrToValuePtr (UObject const *ContainerPtr, int32 ArrayIndex=0) const
template<typename ValueType>
FORCEINLINE ValueType * ContainerPtrToValuePtr (void *ContainerPtr, int32 ArrayIndex=0) const
template<typename ValueType>
FORCEINLINE ValueType const * ContainerPtrToValuePtr (void const *ContainerPtr, int32 ArrayIndex=0) const
template<typename ValueType>
FORCEINLINE ValueType * ContainerPtrToValuePtrForDefaults (UStruct *ContainerClass, UObject *ContainerPtr, int32 ArrayIndex=0) const
template<typename ValueType>
FORCEINLINE ValueType const * ContainerPtrToValuePtrForDefaults (UStruct *ContainerClass, UObject const *ContainerPtr, int32 ArrayIndex=0) const
template<typename ValueType>
FORCEINLINE ValueType * ContainerPtrToValuePtrForDefaults (UStruct *ContainerClass, void *ContainerPtr, int32 ArrayIndex=0) const
template<typename ValueType>
FORCEINLINE ValueType const * ContainerPtrToValuePtrForDefaults (UStruct *ContainerClass, void const *ContainerPtr, int32 ArrayIndex=0) const
bool ContainsFinishDestroy (TArray< const FStructProperty * > &EncounteredStructProps) const
Returns true if the property or any of the child properties should be cleared on FinishDestroy.
FORCEINLINE bool ContainsInstancedObjectProperty () const
Returns true if this property, or in the case of e.g.
bool ContainsWeakObjectReference () const
Returns true if this property, or in the case of e.g.
FORCEINLINE void CopyCompleteValue (void *Dest, void const *Src) const
Copy the value for all elements of this property.
FORCEINLINE void CopyCompleteValue_InContainer (void *Dest, void const *Src) const
virtual void CopyCompleteValueFromScriptVM (void *Dest, void const *Src) const
Copy the value for all elements of this property.
virtual void CopyCompleteValueFromScriptVM_InContainer (void *OutContainer, void const *InValue) const
virtual void CopyCompleteValueToScriptVM (void *Dest, void const *Src) const
Copy the value for all elements of this property.
virtual void CopyCompleteValueToScriptVM_InContainer (void *OutValue, void const *InContainer) const
Equivalent to the above functions, but using the container and aware of getters/setters when the container has them.
FORCEINLINE void CopySingleValue (void *Dest, void const *Src) const
Copy the value for a single element of this property.
virtual void CopySingleValueFromScriptVM (void *Dest, void const *Src) const
Copy the value for a single element of this property.
virtual void CopySingleValueToScriptVM (void *Dest, void const *Src) const
Copy the value for a single element of this property.
void DestroyAndFreeValue (void *InMemory) const
Destroys and frees memory with a value this property represents.
FORCEINLINE void DestroyValue (void *Dest) const
Destroys the value for this property.
FORCEINLINE void DestroyValue_InContainer (void *Dest) const
Destroys the value for this property.
bool ExportText_Direct (FString &ValueStr, const void *Data, const void *Delta, UObject *Parent, int32 PortFlags, UObject *ExportRootScope=nullptr) const
FORCEINLINE bool ExportText_InContainer (int32 Index, FString &ValueStr, const void *Data, const void *Delta, UObject *Parent, int32 PortFlags, UObject *ExportRootScope=nullptr) const
void ExportTextItem_Direct (FString &ValueStr, const void *PropertyValue, const void *DefaultValue, UObject *Parent, int32 PortFlags, UObject *ExportRootScope=nullptr) const
void ExportTextItem_InContainer (FString &ValueStr, const void *Container, const void *DefaultValue, UObject *Parent, int32 PortFlags, UObject *ExportRootScope=nullptr) const
void FinishDestroy (void *Data) const
Applies appropriate finish destroy actions for the property if needed.
void FinishDestroy_InContainer (void *Data) const
Applies appropriate finish destroy actions for the property if needed.
ELifetimeCondition GetBlueprintReplicationCondition () const
int32 GetElementSize () const
virtual FName GetID () const
FString GetNameCPP () const
Returns the C++ name of the property, including the _DEPRECATED suffix if the property is deprecated.
FORCEINLINE int32 GetOffset_ForDebug () const
Return offset of property from container base.
FORCEINLINE int32 GetOffset_ForGC () const
Return offset of property from container base.
FORCEINLINE int32 GetOffset_ForInternal () const
Return offset of property from container base.
FORCEINLINE int32 GetOffset_ForUFunction () const
Return offset of property from container base.
FORCEINLINE int32 GetOffset_ReplaceWith_ContainerPtrToValuePtr () const
Return offset of property from container base.
FProperty * GetOwnerProperty ()
Returns the first FProperty in this property's Outer chain that does not have a FProperty for an Outer.
const FProperty * GetOwnerProperty () const
FORCEINLINE EPropertyFlags GetPropertyFlags () const
Returns this property's propertyflags.
FORCEINLINE FProperty * GetRepOwner ()
Returns the replication owner, which is the property itself, or NULL if this isn't important for replication.
void GetSingleValue_InContainer (const void *InContainer, void *OutValue, int32 ArrayIndex) const
Copies a single value to OutValue even if the property represents a static array of values.
FORCEINLINE int32 GetSize () const
FORCEINLINE void GetValue_InContainer (void const *InContainer, void *OutValue) const
uint32 GetValueTypeHash (const void *Src) const
Returns the hash value for an element of this property.
FORCEINLINE bool HasAllPropertyFlags (uint64 FlagsToCheck) const
Used to safely check whether all of the passed in flags are set.
FORCEINLINE bool HasAnyPropertyFlags (uint64 FlagsToCheck) const
Used to safely check whether any of the passed in flags are set.
virtual bool HasGetter () const
Checks if this property as a native getter function.
virtual bool HasSetter () const
Checks if this property as a native setter function.
virtual bool HasSetterOrGetter () const
Checks if this property as a native setter or getter function.
bool Identical_InContainer (const void *A, const void *B, int32 ArrayIndex=0, uint32 PortFlags=0) const
Determines whether the property values are identical.
const TCHAR * ImportText_Direct (const TCHAR *Buffer, void *PropertyPtr, UObject *OwnerObject, int32 PortFlags, FOutputDevice *ErrorText=(FOutputDevice *) GWarn) const
Import a text value.
const TCHAR * ImportText_InContainer (const TCHAR *Buffer, void *Container, UObject *OwnerObject, int32 PortFlags, FOutputDevice *ErrorText=(FOutputDevice *) GWarn) const
Import a text value.
FORCEINLINE void InitializeValue (void *Dest) const
Zeros, copies from the default, or calls the constructor for on the value for this property.
FORCEINLINE void InitializeValue_InContainer (void *Dest) const
Zeros, copies from the default, or calls the constructor for on the value for this property.
FORCEINLINE bool IsEditorOnlyProperty () const
Editor-only properties are those that only are used with the editor is present or cannot be removed from serialisation.
FORCEINLINE bool IsInContainer (const UStruct *ContainerClass) const
See if the offset of this property is below the supplied container size.
FORCEINLINE bool IsInContainer (int32 ContainerSize) const
See if the offset of this property is below the supplied container size.
int32 Link (FArchive &Ar)
void LinkWithoutChangingOffset (FArchive &Ar)
void PerformOperationWithGetter (void *OutContainer, const void *DirectPropertyAddress, TFunctionRef< void(const void *)> DirectValueAccessFunc) const
Helper function for getting container / struct property value and performing operation directly on the value memory.
void PerformOperationWithSetter (void *OutContainer, void *DirectPropertyAddress, TFunctionRef< void(void *)> DirectValueAccessFunc) const
Helper function for setting container / struct property value and performing operation directly on the value memory.
void SerializeBinProperty (FStructuredArchive::FSlot Slot, void *Data, int32 ArrayIdx=-1)
Serializes the property with the struct's data residing in Data.
void SerializeNonMatchingBinProperty (FStructuredArchive::FSlot Slot, void *Data, void const *DefaultData, UStruct *DefaultStruct)
Serializes the property with the struct's data residing in Data, unless it matches the default.
void SetBlueprintReplicationCondition (ELifetimeCondition InBlueprintReplicationCondition)
void SetElementSize (int32 NewSize)
FORCEINLINE void SetPropertyFlags (EPropertyFlags NewFlags)
void SetSingleValue_InContainer (void *OutContainer, const void *InValue, int32 ArrayIndex) const
Copies a single value to the property even if the property represents a static array of values.
FORCEINLINE void SetValue_InContainer (void *OutContainer, const void *InValue) const
bool ShouldDuplicateValue () const
Determines whether this property value is eligible for copying when duplicating an object.
bool ShouldPort (uint32 PortFlags=0) const
bool ShouldSerializeValue (FArchive &Ar) const
virtual bool SupportsNetSharedSerialization () const
UE_DEPRECATED (5.7, "Visit is deprecated, please use Visit with context instead.") 1 EPropertyVisitorControlFlow Visit(const FPropertyVisitorData &Data
bool ValidateImportFlags (uint32 PortFlags, FOutputDevice *ErrorText=NULL) const
Verify that modifying this property's value via ImportText is allowed.
EPropertyVisitorControlFlow Visit (const FPropertyVisitorData &Data, const TFunctionRef< EPropertyVisitorControlFlow(const FPropertyVisitorContext &)> InFunc) const
Visits this property and allows recursion into the inner properties This method allows callers to visit inner properties without knowing about its container type as opposed to TPropertyIterator.
Public Member Functions inherited from FField
FField (EInternal InInernal, FFieldClass *InClass)
FField (FFieldVariant InOwner, const FName &InName, EObjectFlags InObjectFlags)
virtual ~FField ()
void AppendName (FString &ResultString) const
virtual void BeginDestroy ()
virtual void Bind ()
void ClearFlags (EObjectFlags NewFlags)
FString GetAuthoredName () const
Returns a human readable string that was assigned to this field at creation.
uint64 GetCastFlags () const
FFieldClass * GetClass () const
virtual SIZE_T GetFieldSize () const
EObjectFlags GetFlags () const
Retrieve the object flags directly.
FORCEINLINE FName GetFName () const
FString GetFullName () const
FLinkerLoad * GetLinker () const
FORCEINLINE FString GetName () const
FORCEINLINE void GetName (FString &OutName) const
UPackage * GetOutermost () const
Goes up the outer chain to look for the outermost package.
template<typename T>
T * GetOwner () const
template<typename T>
FUNCTION_NON_NULL_RETURN_START T * GetOwnerChecked () const FUNCTION_NON_NULL_RETURN_END
UClass * GetOwnerClass () const
Goes up the outer chain to look for a UClass.
UStruct * GetOwnerStruct () const
Goes up the outer chain to look for a UStruct.
UField * GetOwnerUField () const
Goes up the outer chain to look for a UField.
FORCEINLINE UObject * GetOwnerUObject () const
Goes up the outer chain to look for a UObject.
FFieldVariant GetOwnerVariant () const
Gets the owner container for this field.
void GetPathName (const UObject *StopOuter, FStringBuilderBase &ResultString) const
FString GetPathName (const UObject *StopOuter=nullptr) const
template<typename T>
T * GetTypedOwner () const
FField * GetTypedOwner (FFieldClass *Target) const
Goes up the outer chain to look for the outer of the specified type.
UObject * GetTypedOwner (UClass *Target) const
Goes up the outer chain to look for the outer of the specified type.
bool HasAllFlags (EObjectFlags FlagsToCheck) const
Used to safely check whether all of the passed in flags are set.
bool HasAnyFlags (EObjectFlags FlagsToCheck) const
Used to safely check whether any of the passed in flags are set.
FORCEINLINE UObject * InternalGetOwnerAsUObjectUnsafe () const
Internal function for quickly getting the owner of this object as UObject.
template<typename T>
bool IsA () const
bool IsA (const FFieldClass *FieldType) const
bool IsIn (const FField *InOwner) const
bool IsIn (const UObject *InOwner) const
bool IsNative () const
bool IsRooted () const
bool IsValidLowLevel () const
virtual void PostLoad ()
void Rename (const FName &NewName)
void SetFlags (EObjectFlags NewFlags)
UE_DEPRECATED (5.0, "HasAllCastFlags is deprecated. Not all FField has CastFlag. Use IsA instead.") inline bool HasAllCastFlags(const uint64 InCastFlags) const
UE_DEPRECATED (5.0, "HasAnyCastFlags is deprecated. Not all FField has CastFlag. Use IsA instead.") inline bool HasAnyCastFlags(const uint64 InCastFlags) const
Static Public Member Functions
static void ExportTextInnerItem (FString &ValueStr, const FProperty *Inner, const void *PropertyValue, int32 PropertySize, const void *DefaultValue, int32 DefaultSize, UObject *Parent=nullptr, int32 PortFlags=0, UObject *ExportRootScope=nullptr)
Called by ExportText_Internal, but can also be used by a non-ArrayProperty whose ArrayDim is > 1.
static const TCHAR * ImportTextInnerItem (const TCHAR *Buffer, const FProperty *Inner, void *Data, int32 PortFlags, UObject *OwnerObject, FScriptArrayHelper *ArrayHelper=nullptr, FOutputDevice *ErrorText=(FOutputDevice *) GWarn)
Called by ImportTextItem, but can also be used by a non-ArrayProperty whose ArrayDim is > 1.
Static Public Member Functions inherited from FProperty
static FName FindRedirectedPropertyName (const UStruct *ObjectStruct, FName OldName)
Gets a redirected property name, will return NAME_None if no redirection was found.
static const TCHAR * ImportSingleProperty (const TCHAR *Str, void *DestData, const UStruct *ObjectStruct, UObject *SubobjectOuter, int32 PortFlags, FOutputDevice *Warn, TArray< struct FDefinedProperty > &DefinedProperties)
parses and imports a text definition of a single property's value (if array, may be an individual element) also includes parsing of special operations for array properties (Add/Remove/RemoveIndex/Empty)
Static Public Member Functions inherited from FField
static FField * Construct (const FFieldVariant &InOwner, const FName &InName, EObjectFlags InFlags)
Constructs a new field given its class.
static FField * Construct (const FName &FieldTypeName, const FFieldVariant &InOwner, const FName &InName, EObjectFlags InFlags)
Constructs a new field given the name of its class.
static FField * Duplicate (const FField *InField, FFieldVariant DestOwner, const FName DestName=NAME_None, EObjectFlags FlagMask=RF_AllFlags, EInternalObjectFlags InternalFlagsMask=EInternalObjectFlags_AllFlags)
Duplicates an FField.
static FName GenerateFFieldName (FFieldVariant InOwner, FFieldClass *InClass)
Generates a name for a Field of a given type.
static FFieldClass * StaticClass ()
static constexpr uint64 StaticClassCastFlags ()
static constexpr uint64 StaticClassCastFlagsPrivate ()
static FField * TryConstruct (const FName &FieldTypeName, const FFieldVariant &InOwner, const FName &InName, EObjectFlags InFlags)
Tries to construct a new field given the name of its class.
Static Public Member Functions inherited from TPropertyTypeFundamentals< FScriptArray >
static FORCEINLINE void ClearIntrusiveOptionalValue (void *A)
static FORCEINLINE void DestroyPropertyValue (void *A)
Destroy the value of a property at an address.
static FORCEINLINE TCppType GetDefaultPropertyValue ()
Get the default value of the cpp type, just the default constructor, which works even for things like in32.
static FORCEINLINE TCppType GetOptionalPropertyValue (void const *B)
Get the value of the property from an address, unless it is NULL, then return the default value.
static FORCEINLINE TCppType const & GetPropertyValue (void const *A)
Get the value of the property from an address.
static FORCEINLINE TCppType const * GetPropertyValuePtr (void const *A)
Convert the address of a value of the property to the proper type.
static FORCEINLINE TCHAR const * GetTypeName ()
static FORCEINLINE bool HasIntrusiveUnsetOptionalState ()
static FORCEINLINE void InitializeIntrusiveUnsetOptionalValue (void *Data)
static FORCEINLINE TCppType * InitializePropertyValue (void *A)
Initialize the value of a property at an address, this assumes over uninitialized memory.
static FORCEINLINE bool IsIntrusiveOptionalValueSet (const void *A)
static FORCEINLINE void SetPropertyValue (void *A, TCppType const &Value)
Set the value of a property at an address.
Protected Member Functions
virtual bool ContainsClearOnFinishDestroyInternal (TArray< const FStructProperty * > &EncounteredStructProps) const override
virtual void ExportText_Internal (FString &ValueStr, const void *PropertyValueOrContainer, EPropertyPointerType PropertyPointerType, const void *DefaultValue, UObject *Parent, int32 PortFlags, UObject *ExportRootScope) const override
virtual void FinishDestroyInternal (void *Data) const override
virtual const TCHAR * ImportText_Internal (const TCHAR *Buffer, void *ContainerOrPropertyPtr, EPropertyPointerType PropertyPointerType, UObject *OwnerObject, int32 PortFlags, FOutputDevice *ErrorText) const override
Protected Member Functions inherited from FProperty
virtual uint32 GetValueTypeHashInternal (const void *Src) const
void Init ()
Initializes internal state.
FORCEINLINE void * PointerToValuePtr (void const *ContainerOrPropertyPtr, EPropertyPointerType PropertyPointerType, int32 ArrayIndex=0) const
void SetOffset_Internal (int32 NewOffset)
Set the alignment offset for this property - added for FMapProperty.
Protected Member Functions inherited from FField
void SetFlagsTo (EObjectFlags NewFlags)
Set the object flags directly.
Private Member Functions
DECLARE_FIELD_API (FArrayProperty,(TProperty< FScriptArray, FProperty >), CASTCLASS_FArrayProperty, 1) EArrayPropertyFlags ArrayFlags
Private Attributes
FProperty * Inner
Additional Inherited Members
Data Fields inherited from FProperty
const TFunctionRef< EPropertyVisitorControlFlow(const FPropertyVisitorPath &, const FPropertyVisitorData &)> InFunc const
FProperty * DestructorLinkNext
In memory only: Linked list of properties requiring destruction.
virtual FString GetCPPType (FString *ExtendedTypeText=NULL, uint32 CPPExportFlags=0) const PURE_VIRTUAL(FProperty
Returns the text to use for exporting this property to header file.
virtual bool Identical (const void *A, const void *B, uint32 PortFlags=0) const PURE_VIRTUAL(FProperty
Determines whether the property values are identical.
virtual void virtual SerializeItem(FStructuredArchive::FSlot Slot, void *Value, void const *Defaults=NULL) const PURE_VIRTUAL(FProperty boo NetSerializeItem)(FArchive &Ar, UPackageMap *Map, void *Data, TArray< uint8 > *MetaData=NULL) const
FProperty * NextRef
In memory only: Linked list of object reference properties from most-derived to base.
FProperty * PostConstructLinkNext
In memory only: Linked list of properties requiring post constructor initialization.
EPropertyFlags PropertyFlags
FProperty * PropertyLinkNext
In memory only: Linked list of properties from most-derived to base.
uint16 RepIndex
FName RepNotifyFunc
Data Fields inherited from FField
EObjectFlags FlagsPrivate
Object flags.
FName NamePrivate
Name of this field.
FField * Next
Next Field in the linked list.
FFieldVariant Owner
Owner of this field.
Static Protected Member Functions inherited from TPropertyTypeFundamentals< FScriptArray >
static FORCEINLINE EPropertyFlags GetComputedFlagsPropertyFlags ()
Get the property flags corresponding to this C++ type, from the C++ type traits system.
Protected Attributes inherited from FProperty
virtual void virtual ExportText_Internal(FString &ValueStr, const void *PropertyValueOrContainer, EPropertyPointerType PointerType, const void *DefaultValue, UObject *Parent, int32 PortFlags, UObject *ExportRootScope=nullptr) const PURE_VIRTUAL(FProperty const TCHAR ImportText_Internal)(const TCHAR *Buffer, void *ContainerOrPropertyPtr, EPropertyPointerType PointerType, UObject *OwnerObject, int32 PortFlags, FOutputDevice *ErrorText) const PURE_VIRTUAL(FProperty
Detailed Description
Definition at line 3423 of file UnrealType.h.
Member Typedef Documentation
TCppType
using FArrayProperty::TCppType = TTypeFundamentals::TCppType
Definition at line 3441 of file UnrealType.h.
TTypeFundamentals
using FArrayProperty::TTypeFundamentals = Super::TTypeFundamentals
Definition at line 3440 of file UnrealType.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Type of the CPP property.
Enumerator
CPPSize
CPPAlignment
Definition at line 3433 of file UnrealType.h.
Constructor & Destructor Documentation
FArrayProperty() [1/2]
FArrayProperty::FArrayProperty (FFieldVariant InOwner, const FName & InName, EObjectFlags InObjectFlags, EArrayPropertyFlags InArrayPropertyFlags = EArrayPropertyFlags::None)
References InName, and UE_API.
Referenced by ~FArrayProperty(), and DECLARE_FIELD_API().
FArrayProperty() [2/2]
FArrayProperty::FArrayProperty (FFieldVariant InOwner, const UECodeGen_Private::FArrayPropertyParams & Prop)
Constructor used for constructing compiled in properties.
Parameters
InOwner Owner of the property
PropBase Pointer to the compiled in structure describing the property
References UE_API.
~FArrayProperty()
virtual FArrayProperty::~FArrayProperty () virtual
References FArrayProperty(), and UE_API.
Member Function Documentation
AddCppProperty()
virtual void FArrayProperty::AddCppProperty (FProperty * Property) override virtual
Reimplemented from FField.
References Property, and UE_API.
AddReferencedObjects()
virtual void FArrayProperty::AddReferencedObjects (FReferenceCollector & Collector) override virtual
Reimplemented from FField.
References UE_API.
CanSerializeFromTypeName()
virtual bool FArrayProperty::CanSerializeFromTypeName (UE::FPropertyTypeName Type) const override virtual
Returns true if the type of this property matches the type name.
Reimplemented from FProperty.
References UE_API.
ClearIntrusiveOptionalValue()
virtual void FArrayProperty::ClearIntrusiveOptionalValue (void * Data) const override virtual
Set the value to it's special unset state.
Equivalent to TOptional<T>::Reset. Only valid to call if HasIntrusiveUnsetOptionalState returns true.
See also
operator=(FIntrusiveUnsetOptionalState)
Parameters
Data Address of the alue, already offset.
Reimplemented from TProperty< FScriptArray, FProperty >.
References UE_API.
ClearValueInternal()
virtual void FArrayProperty::ClearValueInternal (void * Data) const override virtual
Reimplemented from TProperty< FScriptArray, FProperty >.
References UE_API.
ContainsClearOnFinishDestroyInternal()
virtual bool FArrayProperty::ContainsClearOnFinishDestroyInternal (TArray< const FStructProperty * > & EncounteredStructProps) const override protected virtual
Reimplemented from FProperty.
References UE_API.
ContainsObjectReference()
virtual bool FArrayProperty::ContainsObjectReference (TArray< const FStructProperty * > & EncounteredStructProps, EPropertyObjectReferenceType InReferenceType = EPropertyObjectReferenceType::Strong) const override virtual
Returns true if this property, or in the case of e.g.
array or struct properties any sub- property, contains a UObject reference.
Parameters
EncounteredStructProps used to check for recursion in arrays
InReferenceType type of object reference (strong / weak)
Returns
true if property (or sub- properties) contains the specified type of UObject reference, false otherwise
Reimplemented from FProperty.
References UE_API.
ConvertFromType()
virtual EConvertFromTypeResult FArrayProperty::ConvertFromType (const FPropertyTag & Tag, FStructuredArchive::FSlot Slot, uint8 * Data, UStruct * DefaultsStruct, const uint8 * Defaults) override virtual
Allows a property to implement backwards compatibility handling for tagged properties.
Parameters
Tag property tag of the loading data
Ar the archive the data is being loaded from
Data a pointer to the container to write the loaded data to
DefaultsStruct
Defaults if available, a pointer to the container containing the default value for this property, or null
Returns
A state which tells the tagged property system how the property dealt with the data. Converted: the function handled conversion. CannotConvert: the tag is not something that the property can convert. Serialized: the function handled serialization without conversion. UseSerializeItem: no conversion was done on the property - this can mean that the tag is correct and normal serialization applies or that the tag is incompatible.
Reimplemented from FProperty.
References UE_API.
CopyValuesInternal()
virtual void FArrayProperty::CopyValuesInternal (void * Dest, void const * Src, int32 Count) const override virtual
Reimplemented from TProperty< FScriptArray, FProperty >.
References Count, and UE_API.
DECLARE_FIELD_API()
FArrayProperty::DECLARE_FIELD_API (FArrayProperty , (TProperty< FScriptArray, FProperty >) , CASTCLASS_FArrayProperty , 1) private
References FArrayProperty(), TProperty< FScriptArray, FProperty >::TProperty(), CASTCLASS_FArrayProperty, and UE_API.
DestroyValueInternal()
virtual void FArrayProperty::DestroyValueInternal (void * Dest) const override virtual
Reimplemented from TProperty< FScriptArray, FProperty >.
References UE_API.
EmitIntrusiveOptionalReferenceInfo()
virtual void FArrayProperty::EmitIntrusiveOptionalReferenceInfo (UE::GC::FSchemaBuilder & Schema, int32 BaseOffset, TArray< const FStructProperty * > & EncounteredStructProps, UE::GC::FPropertyStack & DebugPath) override virtual
For properties returning true from HasIntrusiveUnsetOptionalState which also contain object references, emit information for the garbage collector to safely gather the references from the value whether the optional value is set or unset.
Reimplemented from FProperty.
References UE_API.
EmitReferenceInfo()
virtual void FArrayProperty::EmitReferenceInfo (UE::GC::FSchemaBuilder & Schema, int32 BaseOffset, TArray< const FStructProperty * > & EncounteredStructProps, UE::GC::FPropertyStack & DebugPath) override virtual
Emits tokens used by realtime garbage collection code to passed in ReferenceTokenStream.
The offset emitted is relative to the passed in BaseOffset which is used by e.g. arrays of structs.
Reimplemented from FProperty.
References UE_API.
ExportText_Internal()
virtual void FArrayProperty::ExportText_Internal (FString & ValueStr, const void * PropertyValueOrContainer, EPropertyPointerType PropertyPointerType, const void * DefaultValue, UObject * Parent, int32 PortFlags, UObject * ExportRootScope) const override protected virtual
References Parent, and UE_API.
ExportTextInnerItem()
void FArrayProperty::ExportTextInnerItem (FString & ValueStr, const FProperty * Inner, const void * PropertyValue, int32 PropertySize, const void * DefaultValue, int32 DefaultSize, UObject * Parent = nullptr, int32 PortFlags = 0, UObject * ExportRootScope = nullptr) static
Called by ExportText_Internal, but can also be used by a non-ArrayProperty whose ArrayDim is > 1.
References Inner, Parent, and UE_API.
FinishDestroyInternal()
virtual void FArrayProperty::FinishDestroyInternal (void * Data) const override protected virtual
Reimplemented from FProperty.
References UE_API.
GetCPPMacroType()
virtual FString FArrayProperty::GetCPPMacroType (FString & ExtendedTypeText) const override virtual
Reimplemented from FProperty.
References UE_API.
GetCPPType()
virtual FString FArrayProperty::GetCPPType (FString * ExtendedTypeText, uint32 CPPExportFlags) const override virtual
Reimplemented from TProperty< FScriptArray, FProperty >.
References UE_API.
GetCPPTypeCustom()
FString FArrayProperty::GetCPPTypeCustom (FString * ExtendedTypeText, uint32 CPPExportFlags, const FString & InnerTypeText, const FString & InInnerExtendedTypeText) const
References UE_API.
GetInnerFieldByName()
virtual FField * FArrayProperty::GetInnerFieldByName (const FName & InName) override virtual
Returns an inner field by name if the field has any.
Reimplemented from FField.
References FField::FField(), InName, and UE_API.
GetInnerFields()
virtual void FArrayProperty::GetInnerFields (TArray< FField * > & OutFields) override virtual
Fills the provided array with all inner fields this field owns (recursively)
Reimplemented from FField.
References UE_API.
GetMinAlignment()
virtual int32 FArrayProperty::GetMinAlignment () const inline override virtual
Reimplemented from TProperty< FScriptArray, FProperty >.
Definition at line 3515 of file UnrealType.h.
GetPreloadDependencies()
virtual void FArrayProperty::GetPreloadDependencies (TArray< UObject * > & OutDeps) override virtual
Reimplemented from FField.
References UE_API.
GetValueAddressAtIndex_Direct()
virtual void * FArrayProperty::GetValueAddressAtIndex_Direct (const FProperty * Inner, void * InValueAddress, int32 Index) const override virtual
Gets value address at given index inside of a static array or container.
Parameters
InValueAddress address of the value represented by this property
Index into the static array or container
Returns
address of the value at given index
Reimplemented from FProperty.
References Inner, and UE_API.
HasIntrusiveUnsetOptionalState()
virtual bool FArrayProperty::HasIntrusiveUnsetOptionalState () const override virtual
Reimplemented from TProperty< FScriptArray, FProperty >.
References UE_API.
Identical()
virtual bool FArrayProperty::Identical (const void * A, const void * B, uint32 PortFlags) const override virtual
References A, B, and UE_API.
ImportText_Internal()
virtual const TCHAR * FArrayProperty::ImportText_Internal (const TCHAR * Buffer, void * ContainerOrPropertyPtr, EPropertyPointerType PropertyPointerType, UObject * OwnerObject, int32 PortFlags, FOutputDevice * ErrorText) const override protected virtual
References Buffer, and UE_API.
ImportTextInnerItem()
const TCHAR * FArrayProperty::ImportTextInnerItem (const TCHAR * Buffer, const FProperty * Inner, void * Data, int32 PortFlags, UObject * OwnerObject, FScriptArrayHelper * ArrayHelper = nullptr, FOutputDevice * ErrorText = (FOutputDevice *) GWarn) static
Called by ImportTextItem, but can also be used by a non-ArrayProperty whose ArrayDim is > 1.
ArrayHelper should be supplied by ArrayProperties and nullptr for fixed-size arrays.
References Buffer, GWarn, Inner, and UE_API.
InitializeIntrusiveUnsetOptionalValue()
virtual void FArrayProperty::InitializeIntrusiveUnsetOptionalValue (void * Data) const override virtual
Returns whether this type has a special state for an unset TOptional meaning the size TOptional<T> and T are the same.
Properties must implement this function explicitly even if they do not have such a state.
See also
Optional.h - HasIntrusiveUnsetOptionalState
FOptionalProperty Initialize the value at the given address to an unset TOptional using an intrusive state rather than a trailing boolean.
TOptional::TOptional
Constructor taking FIntrusiveUnsetOptionalState
Reimplemented from TProperty< FScriptArray, FProperty >.
References UE_API.
InitializeValueInternal()
virtual void FArrayProperty::InitializeValueInternal (void * Dest) const inline override virtual
Reimplemented from TProperty< FScriptArray, FProperty >.
Definition at line 3487 of file UnrealType.h.
References checkf, EnumHasAnyFlags(), FProperty::GetElementSize(), PLATFORM_32BITS, PLATFORM_ANDROID, and TEXT.
InstanceSubobjects()
virtual void FArrayProperty::InstanceSubobjects (void * Data, void const * DefaultData, TNotNull< UObject * > Owner, struct FObjectInstancingGraph * InstanceGraph) override virtual
Creates new copies of components.
Parameters
Data pointer to the address of the instanced object referenced by this UComponentProperty
DefaultData pointer to the address of the default value of the instanced object referenced by this UComponentProperty
Owner the object that contains this property's data
InstanceGraph contains the mappings of instanced objects and components to their templates
Reimplemented from FProperty.
References FField::Owner, and UE_API.
IsIntrusiveOptionalValueSet()
virtual bool FArrayProperty::IsIntrusiveOptionalValueSet (const void * Data) const override virtual
Returns whether an optional value of this inner type is unset.
Only valid to call if HasIntrusiveUnsetOptionalState returns true. Equivalent to TOptional<T>::IsSet()
See also
operator==(FIntrusiveUnsetOptionalState)
Parameters
Data Address of value to inspect, already offset.
Returns
true if the value is unset
Reimplemented from TProperty< FScriptArray, FProperty >.
References UE_API.
LinkInternal()
virtual void FArrayProperty::LinkInternal (FArchive & Ar) override virtual
Reimplemented from TProperty< FScriptArray, FProperty >.
References Ar, and UE_API.
LoadTypeName()
virtual bool FArrayProperty::LoadTypeName (UE::FPropertyTypeName Type, const FPropertyTag * Tag = nullptr) override virtual
Restores this property and its owned properties from the type name.
Returns
true if this property loaded from the type name and is in a valid and usable state.
Reimplemented from FProperty.
References UE_API.
NetSerializeItem()
virtual bool FArrayProperty::NetSerializeItem (FArchive & Ar, UPackageMap * Map, void * Data, TArray< uint8 > * MetaData = NULL) const override virtual
References Ar, Map, MetaData, and UE_API.
PostDuplicate()
virtual void FArrayProperty::PostDuplicate (const FField & InField) override virtual
Fixups after duplicating a Field.
Reimplemented from FProperty.
References FField::FField(), and UE_API.
ResolveVisitedPathInfo()
virtual void * FArrayProperty::ResolveVisitedPathInfo (void * Data, const FPropertyVisitorInfo & Info) const override virtual
Attempt to resolve the given inner path info against this outer property to get the inner property value.
Returns
The inner property value, or null if the path info is incompatible/missing on this property.
Reimplemented from FProperty.
References Info, and UE_API.
SameType()
virtual bool FArrayProperty::SameType (const FProperty * Other) const override virtual
returns true, if Other is property of exactly the same type
Reimplemented from FProperty.
References Other, and UE_API.
SaveTypeName()
virtual void FArrayProperty::SaveTypeName (UE::FPropertyTypeNameBuilder & Type) const override virtual
Saves the type name of this property and its owned properties.
Reimplemented from FProperty.
References UE_API.
Serialize()
virtual void FArrayProperty::Serialize (FArchive & Ar) override virtual
Reimplemented from FProperty.
References Ar, and UE_API.
SerializeItem()
virtual void FArrayProperty::SerializeItem (FStructuredArchive::FSlot Slot, void * Value, void const * Defaults) const override virtual
References UE_API, and Value.
UseBinaryOrNativeSerialization()
virtual bool FArrayProperty::UseBinaryOrNativeSerialization (const FArchive & Ar) const override virtual
Reimplemented from FProperty.
References Ar, and UE_API.
Visit()
virtual EPropertyVisitorControlFlow FArrayProperty::Visit (FPropertyVisitorContext & Context, const TFunctionRef< EPropertyVisitorControlFlow(const FPropertyVisitorContext &)> InFunc) const override virtual
Visits this property and allows recursion into the inner properties This method allows callers to visit inner properties without knowing about its container type as opposed to TPropertyIterator.
This visit property pattern facilitates the recursion into user defined properties and allows users to add specific visit logic on UStruct via traits.
Parameters
Context which containes the path that was computed until we reached this property and the sata to the property to visit
InFunc to call on each visited property, the return value controls what is the next behavior once this property has been visited
Returns
the new action to take one visited this property
Reimplemented from FProperty.
References UE_API.
Field Documentation
Inner
FProperty* FArrayProperty::Inner private
Definition at line 3429 of file UnrealType.h.
Referenced by ExportTextInnerItem(), GetValueAddressAtIndex_Direct(), and ImportTextInnerItem().
The documentation for this class was generated from the following file:
Runtime/CoreUObject/Public/UObject/UnrealType.h