Unreal Engine 5.6 C++ API: FStringTableRegistry Class Reference
FStringTableRegistry Class Reference
Singleton registry of known string table instances.
#include "StringTableRegistry.h"
Public Member Functions
void EnumerateStringTables (const TFunctionRef< bool(const FName &, const FStringTableConstRef &)> &InEnumerator) const
Enumerate all registered string tables.
FStringTablePtr FindMutableStringTable (const FName InTableId) const
Try and find a string table with the given ID.
FStringTableConstPtr FindStringTable (const FName InTableId) const
Try and find a string table with the given ID.
UStringTable * FindStringTableAsset (const FName InTableId) const
Try and find a string table asset with the given ID.
FText Internal_FindLocTableEntry (const FName InTableId, const FTextKey &InKey, const EStringTableLoadingPolicy InLoadingPolicy) const
Internal function called by LOCTABLE to find the entry with by the given key within the given string table (redirects, will load assets if needed, and returns a dummy FText if not found)
void Internal_LocTableFromFile (const FName InTableId, const FTextKey &InNamespace, const FString &InFilePath, const FString &InRootPath)
Internal function called by LOCTABLE_FROMFILE_X to create and register a FStringTable instance that has been populated from a file.
void Internal_NewLocTable (const FName InTableId, const FTextKey &InNamespace)
Internal function called by LOCTABLE_NEW to create and register a new FStringTable instance.
void Internal_SetLocTableEntry (const FName InTableId, const FTextKey &InKey, const FString &InSourceString)
Internal function called by LOCTABLE_SETSTRING to set the entry denoted by the given key to the given source string, within the given string table (table must have been registered already)
void Internal_SetLocTableEntryMetaData (const FName InTableId, const FTextKey &InKey, const FName InMetaDataId, const FString &InMetaData)
Internal function called by LOCTABLE_SETMETA to set meta-data for the entry denoted by the given key, within the given string table (table must have been registered already)
void LogMissingStringTableEntry (const FName InTableId, const FTextKey &InKey)
Log a missing string table entry (will only log each missing entry once to avoid spam)
void RegisterStringTable (const FName InTableId, FStringTableRef InTable)
Register a string table with the given ID.
UE_DEPRECATED (5.0, "FindTableIdAndKey is deprecated. Use FTextInspector::GetTableIdAndKey instead.") 1 bool FindTableIdAndKey(const FText &InText
Given an FText, try and find the table ID and key for it.
void UnregisterStringTable (const FName InTableId)
Unregister a string table with the given ID.
Static Public Member Functions
static FStringTableRegistry & Get ()
Singleton accessor.
Data Fields
FName FString &OutKey const
FName & OutTableId
Private Types
typedef TSet< FTextKey > FLocKeySet
Mapping from a table ID to a set of keys that we've logged warnings for.
Private Member Functions
FStringTableRegistry ()
Private constructor - use singleton accessor.
~FStringTableRegistry ()
void OnDirectoryChanged (const TArray< struct FFileChangeData > &InFileChanges)
Callback handler for a directory change notification.
Private Attributes
TMap< FString, FName > CSVFilesToWatch
Mapping of absolute CSV file paths to the table ID that imported them using Internal_LocTableFromFile.
FCriticalSection CSVFilesToWatchCS
Critical section preventing concurrent modification of CSVFilesToWatch.
FDelegateHandle EngineDirectoryWatcherHandle
Delegate handle watching the Engine directory.
FDelegateHandle GameDirectoryWatcherHandle
Delegate handle watching the Game directory.
TMap< FName, FLocKeySet > LoggedMissingEntries
FTransactionallySafeCriticalSection LoggedMissingEntriesCS
Critical section preventing concurrent modification of LoggedMissingEntries.
TMap< FName, FStringTablePtr > RegisteredStringTables
Mapping from a table ID to a string table instance.
FTransactionallySafeCriticalSection RegisteredStringTablesCS
Critical section preventing concurrent modification of RegisteredStringTables.
Detailed Description
Singleton registry of known string table instances.
Definition at line 24 of file StringTableRegistry.h.
Member Typedef Documentation
FLocKeySet
typedef TSet<FTextKey> FStringTableRegistry::FLocKeySet private
Mapping from a table ID to a set of keys that we've logged warnings for.
Definition at line 82 of file StringTableRegistry.h.
Constructor & Destructor Documentation
FStringTableRegistry()
FStringTableRegistry::FStringTableRegistry () private
Private constructor - use singleton accessor.
References FStringTableRegistry().
Referenced by FStringTableRegistry(), ~FStringTableRegistry(), and Get().
~FStringTableRegistry()
FStringTableRegistry::~FStringTableRegistry () private
References FStringTableRegistry().
Member Function Documentation
EnumerateStringTables()
void FStringTableRegistry::EnumerateStringTables (const TFunctionRef< bool(const FName &, const FStringTableConstRef &)> & InEnumerator) const
Enumerate all registered string tables.
FindMutableStringTable()
FStringTablePtr FStringTableRegistry::FindMutableStringTable (const FName InTableId) const
Try and find a string table with the given ID.
FindStringTable()
FStringTableConstPtr FStringTableRegistry::FindStringTable (const FName InTableId) const
Try and find a string table with the given ID.
FindStringTableAsset()
UStringTable * FStringTableRegistry::FindStringTableAsset (const FName InTableId) const
Try and find a string table asset with the given ID.
Get()
FStringTableRegistry & FStringTableRegistry::Get () static
Singleton accessor.
References FStringTableRegistry().
Internal_FindLocTableEntry()
FText FStringTableRegistry::Internal_FindLocTableEntry (const FName InTableId, const FTextKey & InKey, const EStringTableLoadingPolicy InLoadingPolicy) const
Internal function called by LOCTABLE to find the entry with by the given key within the given string table (redirects, will load assets if needed, and returns a dummy FText if not found)
References const, and Internal_FindLocTableEntry().
Referenced by Internal_FindLocTableEntry().
Internal_LocTableFromFile()
void FStringTableRegistry::Internal_LocTableFromFile (const FName InTableId, const FTextKey & InNamespace, const FString & InFilePath, const FString & InRootPath)
Internal function called by LOCTABLE_FROMFILE_X to create and register a FStringTable instance that has been populated from a file.
References const, and Internal_LocTableFromFile().
Referenced by Internal_LocTableFromFile().
Internal_NewLocTable()
void FStringTableRegistry::Internal_NewLocTable (const FName InTableId, const FTextKey & InNamespace)
Internal function called by LOCTABLE_NEW to create and register a new FStringTable instance.
References const, and Internal_NewLocTable().
Referenced by Internal_NewLocTable().
Internal_SetLocTableEntry()
void FStringTableRegistry::Internal_SetLocTableEntry (const FName InTableId, const FTextKey & InKey, const FString & InSourceString)
Internal function called by LOCTABLE_SETSTRING to set the entry denoted by the given key to the given source string, within the given string table (table must have been registered already)
References const, and Internal_SetLocTableEntry().
Referenced by Internal_SetLocTableEntry().
Internal_SetLocTableEntryMetaData()
void FStringTableRegistry::Internal_SetLocTableEntryMetaData (const FName InTableId, const FTextKey & InKey, const FName InMetaDataId, const FString & InMetaData)
Internal function called by LOCTABLE_SETMETA to set meta-data for the entry denoted by the given key, within the given string table (table must have been registered already)
References const, and Internal_SetLocTableEntryMetaData().
Referenced by Internal_SetLocTableEntryMetaData().
LogMissingStringTableEntry()
void FStringTableRegistry::LogMissingStringTableEntry (const FName InTableId, const FTextKey & InKey)
Log a missing string table entry (will only log each missing entry once to avoid spam)
References const, and LogMissingStringTableEntry().
Referenced by LogMissingStringTableEntry().
OnDirectoryChanged()
void FStringTableRegistry::OnDirectoryChanged (const TArray< struct FFileChangeData > & InFileChanges) private
Callback handler for a directory change notification.
RegisterStringTable()
void FStringTableRegistry::RegisterStringTable (const FName InTableId, FStringTableRef InTable)
Register a string table with the given ID.
UE_DEPRECATED()
FStringTableRegistry::UE_DEPRECATED (5. 0, "FindTableIdAndKey is deprecated. Use FTextInspector::GetTableIdAndKey instead.") const &
Given an FText, try and find the table ID and key for it.
UnregisterStringTable()
void FStringTableRegistry::UnregisterStringTable (const FName InTableId)
Unregister a string table with the given ID.
Field Documentation
const
FName FString& OutKey FStringTableRegistry::const
Definition at line 50 of file StringTableRegistry.h.
Referenced by Internal_FindLocTableEntry(), Internal_LocTableFromFile(), Internal_NewLocTable(), Internal_SetLocTableEntry(), Internal_SetLocTableEntryMetaData(), and LogMissingStringTableEntry().
CSVFilesToWatch
TMap<FString, FName> FStringTableRegistry::CSVFilesToWatch private
Mapping of absolute CSV file paths to the table ID that imported them using Internal_LocTableFromFile.
Definition at line 93 of file StringTableRegistry.h.
CSVFilesToWatchCS
FCriticalSection FStringTableRegistry::CSVFilesToWatchCS mutable private
Critical section preventing concurrent modification of CSVFilesToWatch.
Definition at line 96 of file StringTableRegistry.h.
EngineDirectoryWatcherHandle
FDelegateHandle FStringTableRegistry::EngineDirectoryWatcherHandle private
Delegate handle watching the Engine directory.
Definition at line 99 of file StringTableRegistry.h.
GameDirectoryWatcherHandle
FDelegateHandle FStringTableRegistry::GameDirectoryWatcherHandle private
Delegate handle watching the Game directory.
Definition at line 102 of file StringTableRegistry.h.
LoggedMissingEntries
TMap<FName, FLocKeySet> FStringTableRegistry::LoggedMissingEntries private
Definition at line 83 of file StringTableRegistry.h.
LoggedMissingEntriesCS
FTransactionallySafeCriticalSection FStringTableRegistry::LoggedMissingEntriesCS mutable private
Critical section preventing concurrent modification of LoggedMissingEntries.
Definition at line 86 of file StringTableRegistry.h.
OutTableId
FName& FStringTableRegistry::OutTableId
Definition at line 50 of file StringTableRegistry.h.
RegisteredStringTables
TMap<FName, FStringTablePtr> FStringTableRegistry::RegisteredStringTables private
Mapping from a table ID to a string table instance.
Definition at line 76 of file StringTableRegistry.h.
RegisteredStringTablesCS
FTransactionallySafeCriticalSection FStringTableRegistry::RegisteredStringTablesCS mutable private
Critical section preventing concurrent modification of RegisteredStringTables.
Definition at line 79 of file StringTableRegistry.h.
The documentation for this class was generated from the following file:
Runtime/Core/Public/Internationalization/StringTableRegistry.h