Unreal Engine 5.6 C++ API: Metasound::FSendAddress Class Reference
Metasound::FSendAddress Class Reference
FSendAddress is used as a addressing system for MetaSound Send nodes, Recieve nodes and MetaSound script communication.
#include "MetasoundRouter.h"
Public Member Functions
FSendAddress ()=default
METASOUNDFRONTEND_API FSendAddress (const FName &InChannelName, const FName &InDataType, uint64 InInstanceID=INDEX_NONE)
METASOUNDFRONTEND_API FSendAddress (const FString &InChannelName)
virtual METASOUNDFRONTEND_API TUniquePtr< FTransmissionAddress > Clone () const override
Clone the address.
virtual METASOUNDFRONTEND_API FName GetAddressType () const override
Return the type of address.
METASOUNDFRONTEND_API const FName & GetChannelName () const
virtual METASOUNDFRONTEND_API FName GetDataType () const override
Return the data type.
METASOUNDFRONTEND_API uint64 GetInstanceID () const
virtual METASOUNDFRONTEND_API FString ToString () const override
Return a string representation of the address for debugging.
Public Member Functions inherited from Metasound::FTransmissionAddress
FTransmissionAddress ()=default
virtual ~FTransmissionAddress ()=default
METASOUNDFRONTEND_API bool operator!= (const FTransmissionAddress &InOther) const
METASOUNDFRONTEND_API bool operator== (const FTransmissionAddress &InOther) const
Static Public Attributes
static METASOUNDFRONTEND_API const FLazyName AddressType
Private Member Functions
virtual METASOUNDFRONTEND_API uint32 GetHash () const override
Create a hash of the address.
virtual METASOUNDFRONTEND_API bool IsEqual (const FTransmissionAddress &InOther) const override
Determine if the given address is equal to this address.
Private Attributes
FName ChannelName
FName DataType
uint64 InstanceID = INDEX_NONE
Detailed Description
FSendAddress is used as a addressing system for MetaSound Send nodes, Recieve nodes and MetaSound script communication.
Definition at line 145 of file MetasoundRouter.h.
Constructor & Destructor Documentation
FSendAddress() [1/3]
Metasound::FSendAddress::FSendAddress () default
FSendAddress() [2/3]
METASOUNDFRONTEND_API Metasound::FSendAddress::FSendAddress (const FString & InChannelName)
References UE_API.
FSendAddress() [3/3]
METASOUNDFRONTEND_API Metasound::FSendAddress::FSendAddress (const FName & InChannelName, const FName & InDataType, uint64 InInstanceID = INDEX_NONE)
References INDEX_NONE, and UE_API.
Member Function Documentation
Clone()
virtual METASOUNDFRONTEND_API TUniquePtr< FTransmissionAddress > Metasound::FSendAddress::Clone () const override virtual
Clone the address.
Implements Metasound::FTransmissionAddress.
References UE_API.
GetAddressType()
virtual METASOUNDFRONTEND_API FName Metasound::FSendAddress::GetAddressType () const override virtual
Return the type of address.
The AddressType must be unique per a subclass of FTransmissionAddress as it is used to determine the validity of a static_cast from FTransmissionAddress to the derived address type.
Implements Metasound::FTransmissionAddress.
References UE_API.
GetChannelName()
METASOUNDFRONTEND_API const FName & Metasound::FSendAddress::GetChannelName () const
References UE_API.
Referenced by Metasound::ReceiveNodePrivate::TReceiverOperator< TDataType >::GetSendAddressWithDataType(), and Metasound::SendNodePrivate::TSendOperator< TDataType >::GetSendAddressWithDataType().
GetDataType()
virtual METASOUNDFRONTEND_API FName Metasound::FSendAddress::GetDataType () const override virtual
Return the data type.
Implements Metasound::FTransmissionAddress.
References UE_API.
GetHash()
virtual METASOUNDFRONTEND_API uint32 Metasound::FSendAddress::GetHash () const override private virtual
Create a hash of the address.
Implements Metasound::FTransmissionAddress.
References UE_API.
GetInstanceID()
METASOUNDFRONTEND_API uint64 Metasound::FSendAddress::GetInstanceID () const
References UE_API.
Referenced by Metasound::ReceiveNodePrivate::TReceiverOperator< TDataType >::GetSendAddressWithDataType(), and Metasound::SendNodePrivate::TSendOperator< TDataType >::GetSendAddressWithDataType().
IsEqual()
virtual METASOUNDFRONTEND_API bool Metasound::FSendAddress::IsEqual (const FTransmissionAddress & InOther) const override private virtual
Determine if the given address is equal to this address.
Implements Metasound::FTransmissionAddress.
References Metasound::FTransmissionAddress::FTransmissionAddress(), and UE_API.
ToString()
virtual METASOUNDFRONTEND_API FString Metasound::FSendAddress::ToString () const override virtual
Return a string representation of the address for debugging.
Implements Metasound::FTransmissionAddress.
References UE_API.
Field Documentation
AddressType
METASOUNDFRONTEND_API const FLazyName Metasound::FSendAddress::AddressType static
Definition at line 148 of file MetasoundRouter.h.
ChannelName
FName Metasound::FSendAddress::ChannelName private
Definition at line 171 of file MetasoundRouter.h.
DataType
FName Metasound::FSendAddress::DataType private
Definition at line 172 of file MetasoundRouter.h.
InstanceID
uint64 Metasound::FSendAddress::InstanceID = INDEX_NONE private
Definition at line 175 of file MetasoundRouter.h.
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/Metasound/Source/MetasoundFrontend/Public/MetasoundRouter.h