Unreal Engine 5.6 C++ API: FStringOutputDevice Class Reference
FStringOutputDevice Class Reference
#include "UnrealString.h"
Public Member Functions
FStringOutputDevice (const FStringOutputDevice &)=default
FStringOutputDevice (const TCHAR *OutputDeviceName=TEXT(""))
FStringOutputDevice (FStringOutputDevice &&)=default
virtual FString & operator+= (const FString &Other)
FStringOutputDevice & operator= (const FStringOutputDevice &)=default
FStringOutputDevice & operator= (FStringOutputDevice &&)=default
virtual void Serialize (const TCHAR *InData, ELogVerbosity::Type Verbosity, const class FName &Category) override
Public Member Functions inherited from FOutputDevice
FOutputDevice ()
FOutputDevice (const FOutputDevice &)
FOutputDevice (FOutputDevice &&)
virtual ~FOutputDevice ()
virtual bool CanBeUsedOnAnyThread () const
virtual bool CanBeUsedOnMultipleThreads () const
virtual bool CanBeUsedOnPanicThread () const
template<typename FmtType, typename... Types>
FORCEINLINE void CategorizedLogf (const FName &Category, ELogVerbosity::Type Verbosity, const FmtType &Fmt, Types... Args)
virtual void Dump (class FArchive &Ar)
Dumps the contents of this output device's buffer to an archive (supported by output device that have a memory buffer)
virtual void Flush ()
FORCEINLINE bool GetAutoEmitLineTerminator () const
FORCEINLINE bool GetSuppressEventTag () const
virtual bool IsMemoryOnly () const
void Log (const FName &Category, ELogVerbosity::Type Verbosity, const FString &S)
void Log (const FName &Category, ELogVerbosity::Type Verbosity, const TCHAR *Str)
void Log (const FString &S)
void Log (const FText &S)
void Log (const TCHAR *S)
void Log (ELogVerbosity::Type Verbosity, const FString &S)
void Log (ELogVerbosity::Type Verbosity, const TCHAR *S)
template<typename FmtType>
void Logf (const FmtType &Fmt)
template<typename FmtType, typename... Types>
FORCEINLINE void Logf (const FmtType &Fmt, Types... Args)
template<typename FmtType, typename... Types>
FORCEINLINE void Logf (ELogVerbosity::Type Verbosity, const FmtType &Fmt, Types... Args)
FOutputDevice & operator= (const FOutputDevice &)
FOutputDevice & operator= (FOutputDevice &&)
virtual void Serialize (const TCHAR *V, ELogVerbosity::Type Verbosity, const FName &Category)=0
virtual void Serialize (const TCHAR *V, ELogVerbosity::Type Verbosity, const FName &Category, const double Time)
virtual void SerializeRecord (const UE::FLogRecord &Record)
void SetAutoEmitLineTerminator (bool bInAutoEmitLineTerminator)
void SetSuppressEventTag (bool bInSuppressEventTag)
virtual void TearDown ()
Closes output device and cleans up.
Additional Inherited Members
Protected Attributes inherited from FOutputDevice
bool bAutoEmitLineTerminator
Whether to output a line-terminator after each log call...
bool bSuppressEventTag
Whether to output the 'Log: ' type front...
Detailed Description
Definition at line 288 of file UnrealString.h.
Constructor & Destructor Documentation
FStringOutputDevice() [1/3]
FStringOutputDevice::FStringOutputDevice (const TCHAR * OutputDeviceName = TEXT("")) inline
Definition at line 291 of file UnrealString.h.
References FOutputDevice::bAutoEmitLineTerminator.
Referenced by FStringOutputDevice(), FStringOutputDevice(), operator=(), and operator=().
FStringOutputDevice() [2/3]
FStringOutputDevice::FStringOutputDevice (FStringOutputDevice &&) default
References FStringOutputDevice().
FStringOutputDevice() [3/3]
FStringOutputDevice::FStringOutputDevice (const FStringOutputDevice &) default
References FStringOutputDevice().
Member Function Documentation
operator+=()
virtual FString & FStringOutputDevice::operator+= (const FString & Other) inline virtual
Reimplemented in FStringOutputDeviceCountLines.
Definition at line 311 of file UnrealString.h.
References Other.
operator=() [1/2]
FStringOutputDevice & FStringOutputDevice::operator= (const FStringOutputDevice &) default
References FStringOutputDevice().
operator=() [2/2]
FStringOutputDevice & FStringOutputDevice::operator= (FStringOutputDevice &&) default
References FStringOutputDevice().
Serialize()
virtual void FStringOutputDevice::Serialize (const TCHAR * InData, ELogVerbosity::Type Verbosity, const class FName & Category) inline override virtual
Reimplemented in FConsoleOutputDevice, and FStringOutputDeviceCountLines.
Definition at line 296 of file UnrealString.h.
References FOutputDevice::bAutoEmitLineTerminator, Category, and LINE_TERMINATOR.
Referenced by FStringOutputDeviceCountLines::Serialize().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Containers/UnrealString.h