Unreal Engine 5.6 C++ API: TBitArray< Allocator > Class Template Reference
TBitArray< Allocator > Class Template Reference
A dynamically sized bit array.
#include "BitArray.h"
Data Structures
class FConstIterator
Const BitArray iterator.
class FConstReverseIterator
Const reverse iterator.
struct FConstWordIterator
class FIterator
BitArray iterator.
class FReverseIterator
Reverse iterator.
struct FWordIterator
struct TSupportsFreezeMemoryImageHelper
struct TSupportsFreezeMemoryImageHelper< true, Dummy >
struct TWordIteratorBase
Public Types
typedef Allocator::template ForElementType< uint32 > AllocatorType
Public Member Functions
TBitArray ()
FORCEINLINE TBitArray (bool bValue, int32 InNumBits)
Minimal initialization constructor.
FORCEINLINE TBitArray (const TBitArray &Copy)
Copy constructor.
template<typename OtherAllocator>
FORCEINLINE TBitArray (const TBitArray< OtherAllocator > &Copy)
FORCEINLINE TBitArray (TBitArray &&Other)
Move constructor.
FORCEINLINE FBitReference AccessCorrespondingBit (const FRelativeBitReference &RelativeReference)
FORCEINLINE const FConstBitReference AccessCorrespondingBit (const FRelativeBitReference &RelativeReference) const
int32 Add (const bool Value)
Adds a bit to the array with the given value.
int32 Add (const bool Value, int32 NumBitsToAdd)
Adds multiple bits to the array with the given value.
template<typename InWordType>
int32 AddRange (const InWordType *ReadBits, int32 NumBitsToAdd, int32 ReadOffsetBits=0)
Adds multiple bits read from the given pointer.
template<typename OtherAllocator>
int32 AddRange (const TBitArray< OtherAllocator > &ReadBits, int32 NumBitsToAdd, int32 ReadOffsetBits=0)
Adds multiple bits read from the given BitArray.
int32 AddUninitialized (int32 NumBitsToAdd)
Inserts space for multiple bits at the end of the array.
FORCEINLINE FIterator begin ()
Enables range-based for loops, DO NOT USE DIRECTLY.
FORCEINLINE FConstIterator begin () const
void BitwiseNOT ()
Perform a bitwise NOT on all the bits in this array.
void CheckInvariants () const
Checks the invariants of this class.
template<typename OtherAllocator, typename BinaryOpType>
TBitArray & CombineWithBinaryOp (const TBitArray< OtherAllocator > &InOther, EBitwiseOperatorFlags InFlags, BinaryOpType &&InBinaryOp)
Perform a custom bitwise operation on this bit array with another.
template<typename OtherAllocator>
TBitArray & CombineWithBitwiseAND (const TBitArray< OtherAllocator > &InOther, EBitwiseOperatorFlags InFlags)
Perform a bitwise AND on this bit array with another.
template<typename OtherAllocator>
TBitArray & CombineWithBitwiseOR (const TBitArray< OtherAllocator > &InOther, EBitwiseOperatorFlags InFlags)
Return the bitwise OR of two bit arrays.
template<typename OtherAllocator>
TBitArray & CombineWithBitwiseXOR (const TBitArray< OtherAllocator > &InOther, EBitwiseOperatorFlags InFlags)
Return the bitwise XOR of two bit arrays.
template<typename OtherAllocator>
bool CompareSetBits (const TBitArray< OtherAllocator > &Other, const bool bMissingBitValue) const
Returns true if Other contains all the same set bits as this, accounting for differences in length.
FORCEINLINE bool Contains (bool bValue) const
Checks if the array contains the specified value (true/false).
void CountBytes (FArchive &Ar) const
Tracks the container's memory use through an archive.
int32 CountSetBits (int32 FromIndex=0, int32 ToIndex=INDEX_NONE) const
Count the number of set bits in this array FromIndex <= bit < ToIndex.
void Empty (int32 ExpectedNumBits=0)
Removes all bits from the array, potentially leaving space allocated for an expected number of bits about to be added.
FORCEINLINE FIterator end ()
FORCEINLINE FConstIterator end () const
int32 Find (bool bValue) const
Finds the first occurrence of the specified value (true/false) in the array, and returns the bit index.
int32 FindAndSetFirstZeroBit (int32 StartIndex=0)
Finds the first occurrence of a zero bit in the array and sets it to one, returning the bit index.
int32 FindAndSetLastZeroBit ()
Finds the last occurrence of a zero bit in the array and sets it to one, returning the bit index.
template<typename IndexType>
FORCEINLINE int32 FindFrom (bool bValue, IndexType StartIndex) const
Finds the first occurrence of the specified value (true/false) in the array, starting from the given bit index, and returns the bit index.
int32 FindLast (bool bValue) const
Finds the last occurrence of the specified value (true/false) in the array, and returns the bit index.
template<typename IndexType>
int32 FindLastFrom (bool bValue, IndexType EndIndexInclusive) const
Finds the last occurrence of the specified value (true/false) in the array starting the (reverse) search from the given bit index, and returns the bit index.
uint32 GetAllocatedSize (void) const
Helper function to return the amount of memory allocated by this container.
FORCEINLINE uint32 * GetData ()
FORCEINLINE const uint32 * GetData () const
template<typename InWordType>
FORCEINLINE void GetRange (int32 Index, int32 NumBitsToGet, InWordType *WriteBits, int32 WriteOffsetBits=0) const
Reads a range of bits within the array and writes them to the given pointer.
FORCEINLINE void Init (bool bValue, int32 InNumBits)
Resets the array's contents.
void Insert (bool Value, int32 Index)
Adds a bit with the given value at the given index in the array.
void Insert (bool Value, int32 Index, int32 NumBitsToAdd)
Inserts multiple bits with the given value into the array, starting at the given Index.
template<typename InWordType>
void InsertRange (const InWordType *ReadBits, int32 Index, int32 NumBitsToAdd, int32 ReadOffsetBits=0)
Inserts multiple bits read from the given pointer, starting at the given index.
template<typename OtherAllocator>
void InsertRange (const TBitArray< OtherAllocator > &ReadBits, int32 Index, int32 NumBitsToAdd, int32 ReadOffsetBits=0)
Inserts multiple bits read from the given BitArray into the array, starting at the given index.
void InsertUninitialized (int32 Index, int32 NumBitsToAdd)
Inserts space for multiple bits into the array, starting at the given index.
bool IsEmpty () const
Returns true if the bit array is empty and contains no elements.
FORCEINLINE bool IsValidIndex (int32 InIndex) const
FORCEINLINE int32 Max () const
FORCEINLINE int32 Num () const
FORCEINLINE bool operator!= (const TBitArray< Allocator > &Other) const
FORCEINLINE bool operator< (const TBitArray< Allocator > &Other) const
FORCEINLINE TBitArray & operator= (const TBitArray &Copy)
Assignment operator.
template<typename OtherAllocator>
FORCEINLINE TBitArray & operator= (const TBitArray< OtherAllocator > &Copy)
FORCEINLINE TBitArray & operator= (TBitArray &&Other)
Move assignment.
FORCEINLINE bool operator== (const TBitArray< Allocator > &Other) const
FORCEINLINE FBitReference operator[] (int32 Index)
FORCEINLINE const FConstBitReference operator[] (int32 Index) const
int32 PadToNum (int32 DesiredNum, bool bPadValue)
Pad this bit array with the specified value to ensure that it is at least the specified length.
FORCEINLINE FReverseIterator rbegin ()
FORCEINLINE FConstReverseIterator rbegin () const
void RemoveAt (int32 BaseIndex, int32 NumBitsToRemove=1)
Removes bits from the array.
void RemoveAtSwap (int32 BaseIndex, int32 NumBitsToRemove=1)
FORCEINLINE FReverseIterator rend ()
FORCEINLINE FConstReverseIterator rend () const
void Reserve (int32 Number)
Reserves memory such that the array can contain at least Number bits.
void Reset ()
Removes all bits from the array retaining any space already allocated.
void Serialize (FArchive &Ar)
Serializer.
template<typename ValueType>
FORCENOINLINE void SetNum (int32 InNumBits, ValueType bValue)
Sets the number of bits, initializing any potentially added bits to the given value.
void SetNumUninitialized (int32 InNumBits)
Sets number of bits without initializing new bits.
FORCENOINLINE void SetRange (int32 Index, int32 NumBitsToSet, bool Value)
Sets or unsets a range of bits within the array.
template<typename InWordType>
void SetRangeFromRange (int32 Index, int32 NumBitsToSet, const InWordType *ReadBits, int32 ReadOffsetBits=0)
Sets range of bits within the TBitArray to the values read out of a pointer.
template<typename OtherAllocator>
FORCEINLINE void SetRangeFromRange (int32 Index, int32 NumBitsToSet, const TBitArray< OtherAllocator > &ReadBits, int32 ReadOffsetBits=0)
Sets range of bits within this TBitArray to the values read out another TBitArray.
void WriteMemoryImage (FMemoryImageWriter &Writer) const
Static Public Member Functions
template<typename AllocatorA, typename AllocatorB>
static TBitArray BitwiseAND (const TBitArray< AllocatorA > &A, const TBitArray< AllocatorB > &B, EBitwiseOperatorFlags InFlags)
Return the bitwise AND of two bit arrays.
template<typename AllocatorA, typename AllocatorB>
static TBitArray BitwiseOR (const TBitArray< AllocatorA > &A, const TBitArray< AllocatorB > &B, EBitwiseOperatorFlags InFlags)
Return the bitwise OR of two bit arrays.
template<typename AllocatorA, typename AllocatorB>
static TBitArray BitwiseXOR (const TBitArray< AllocatorA > &A, const TBitArray< AllocatorB > &B, EBitwiseOperatorFlags InFlags)
Return the bitwise XOR of two bit arrays.
Private Types
typedef uint32 WordType
Private Member Functions
template<typename OtherAllocator>
void Assign (const TBitArray< OtherAllocator > &Other)
void ClearPartialSlackBits ()
Clears the slack bits within the final partially relevant Word.
int32 FindFromImpl (bool bValue, int32 StartIndex) const
int32 FindLastFromImpl (bool bValue, int32 EndIndexExclusive) const
FORCEINLINE uint32 GetLastWordMask (int32 EndIndexExclusive) const
FORCEINLINE uint32 GetMaxWords () const
FORCEINLINE uint32 GetNumWords () const
FORCENOINLINE void Realloc (int32 PreviousNumBits)
void SetBitNoCheck (int32 Index, bool Value)
Static Private Member Functions
template<typename BitArrayType>
static FORCEINLINE void Move (BitArrayType &ToArray, BitArrayType &FromArray)
static FORCEINLINE void SetWords (uint32 *Words, int32 NumWords, bool bValue)
Private Attributes
AllocatorType AllocatorInstance
int32 MaxBits
int32 NumBits
Static Private Attributes
static constexpr WordType FullWordMask = (WordType)-1
Friends
template<typename, typename, bool>
class TConstDualSetBitIterator
template<typename>
class TConstSetBitIterator
template<typename, typename>
class TScriptBitArray
template<typename AllocatorA, typename AllocatorB, typename OutAllocator, typename ProjectionType>
void UE::Core::Private::BitwiseBinaryOperatorImpl (const TBitArray< AllocatorA > &, const TBitArray< AllocatorB > &, TBitArray< OutAllocator > &, EBitwiseOperatorFlags, ProjectionType &&)
template<typename OtherAllocator, typename OutAllocator, typename ProjectionType>
void UE::Core::Private::BitwiseOperatorImpl (const TBitArray< OtherAllocator > &, TBitArray< OutAllocator > &, EBitwiseOperatorFlags, ProjectionType &&)
Detailed Description
template<typename Allocator>
class TBitArray< Allocator >
A dynamically sized bit array.
An array of Booleans. They stored in one bit/Boolean. There are iterators that efficiently iterate over only set bits.
Definition at line 349 of file BitArray.h.
Member Typedef Documentation
AllocatorType
template<typename Allocator> typedef Allocator::template ForElementType<uint32> TBitArray< Allocator >::AllocatorType
Definition at line 365 of file BitArray.h.
WordType
template<typename Allocator> typedef uint32 TBitArray< Allocator >::WordType private
Definition at line 360 of file BitArray.h.
Constructor & Destructor Documentation
TBitArray() [1/5]
template<typename Allocator> TBitArray< Allocator >::TBitArray () inline nodiscard
Definition at line 373 of file BitArray.h.
Referenced by TBitArray< Allocator >::FConstIterator::FConstIterator(), TBitArray< Allocator >::FConstReverseIterator::FConstReverseIterator(), TBitArray< Allocator >::FConstReverseIterator::FConstReverseIterator(), TBitArray< Allocator >::FConstWordIterator::FConstWordIterator(), TBitArray< Allocator >::FConstWordIterator::FConstWordIterator(), TBitArray< Allocator >::FIterator::FIterator(), TBitArray< Allocator >::FReverseIterator::FReverseIterator(), TBitArray< Allocator >::FReverseIterator::FReverseIterator(), TBitArray< Allocator >::FWordIterator::FWordIterator(), TBitArray< Allocator >::TSupportsFreezeMemoryImageHelper< bFreezeMemoryImage, Dummy >::WriteMemoryImage(), and TBitArray< Allocator >::TSupportsFreezeMemoryImageHelper< true, Dummy >::WriteMemoryImage().
TBitArray() [2/5]
template<typename Allocator> FORCEINLINE TBitArray< Allocator >::TBitArray (bool bValue, int32 InNumBits) inline explicit nodiscard
Minimal initialization constructor.
Parameters
Value - The value to initial the bits to.
InNumBits - The initial number of bits in the array.
Definition at line 385 of file BitArray.h.
TBitArray() [3/5]
template<typename Allocator> FORCEINLINE TBitArray< Allocator >::TBitArray (TBitArray< Allocator > && Other) inline nodiscard
Move constructor.
Definition at line 394 of file BitArray.h.
TBitArray() [4/5]
template<typename Allocator> FORCEINLINE TBitArray< Allocator >::TBitArray (const TBitArray< Allocator > & Copy) inline nodiscard
Copy constructor.
Definition at line 402 of file BitArray.h.
TBitArray() [5/5]
template<typename Allocator> template<typename OtherAllocator> FORCEINLINE TBitArray< Allocator >::TBitArray (const TBitArray< OtherAllocator > & Copy) inline explicit nodiscard
Definition at line 410 of file BitArray.h.
Member Function Documentation
AccessCorrespondingBit() [1/2]
template<typename Allocator> FORCEINLINE FBitReference TBitArray< Allocator >::AccessCorrespondingBit (const FRelativeBitReference & RelativeReference) inline nodiscard
Definition at line 1456 of file BitArray.h.
AccessCorrespondingBit() [2/2]
template<typename Allocator> FORCEINLINE const FConstBitReference TBitArray< Allocator >::AccessCorrespondingBit (const FRelativeBitReference & RelativeReference) const inline nodiscard
Definition at line 1466 of file BitArray.h.
Add() [1/2]
template<typename Allocator> int32 TBitArray< Allocator >::Add (const bool Value) inline
Adds a bit to the array with the given value.
Returns
The index of the added bit.
Definition at line 608 of file BitArray.h.
Referenced by STreeView< FRigVMSearchResult >::PopulateLinearizedItems().
Add() [2/2]
template<typename Allocator> int32 TBitArray< Allocator >::Add (const bool Value, int32 NumBitsToAdd) inline
Adds multiple bits to the array with the given value.
Returns
The index of the first added bit.
Definition at line 619 of file BitArray.h.
AddRange() [1/2]
template<typename Allocator> template<typename InWordType> int32 TBitArray< Allocator >::AddRange (const InWordType * ReadBits, int32 NumBitsToAdd, int32 ReadOffsetBits = 0) inline
Adds multiple bits read from the given pointer.
Parameters
ReadBits The address of sized integers to read the bits from. Bits are read from ReadBits in the current platform's mathematical bitorder (ReadBits[0] & 0x1, ReadBits[0] & 0x2, ... ReadBits[0] & 0x100, ... ReadBits[0] & 0x80000000, ReadBits[1] & 0x1 ...
NumBitsToAdd The number of bits to add. Must be >= 0.
ReadOffsetBits Number of bits into ReadBits at which to start reading. Must be >= 0.
Returns
The index of the first added bit.
Definition at line 640 of file BitArray.h.
AddRange() [2/2]
template<typename Allocator> template<typename OtherAllocator> int32 TBitArray< Allocator >::AddRange (const TBitArray< OtherAllocator > & ReadBits, int32 NumBitsToAdd, int32 ReadOffsetBits = 0) inline
Adds multiple bits read from the given BitArray.
Parameters
ReadBits The value to set the bits to.
NumBitsToAdd The number of bits to add. Must be >= 0.
ReadOffsetBits Number of bits into ReadBits at which to start reading. Must be >= 0.
Returns
The index of the first added bit.
Definition at line 655 of file BitArray.h.
AddUninitialized()
template<typename Allocator> int32 TBitArray< Allocator >::AddUninitialized (int32 NumBitsToAdd) inline
Inserts space for multiple bits at the end of the array.
The inserted bits are set to arbitrary values and should be written using SetRange or otherwise before being read.
Parameters
NumBitsToAdd The number of bits to add. Must be >= 0.
Definition at line 668 of file BitArray.h.
Referenced by TBitArray< typename Allocator::BitArrayAllocator >::Add(), TBitArray< typename Allocator::BitArrayAllocator >::Add(), TBitArray< typename Allocator::BitArrayAllocator >::AddRange(), TBitArray< typename Allocator::BitArrayAllocator >::AddRange(), and TBitArray< typename Allocator::BitArrayAllocator >::InsertUninitialized().
Assign()
template<typename Allocator> template<typename OtherAllocator> void TBitArray< Allocator >::Assign (const TBitArray< OtherAllocator > & Other) inline private
Definition at line 540 of file BitArray.h.
Referenced by TBitArray< typename Allocator::BitArrayAllocator >::TBitArray(), TBitArray< typename Allocator::BitArrayAllocator >::TBitArray(), TBitArray< typename Allocator::BitArrayAllocator >::operator=(), and TBitArray< typename Allocator::BitArrayAllocator >::operator=().
begin() [1/2]
template<typename Allocator> FORCEINLINE FIterator TBitArray< Allocator >::begin () inline nodiscard
Enables range-based for loops, DO NOT USE DIRECTLY.
Definition at line 1811 of file BitArray.h.
begin() [2/2]
template<typename Allocator> FORCEINLINE FConstIterator TBitArray< Allocator >::begin () const inline nodiscard
Definition at line 1812 of file BitArray.h.
BitwiseAND()
template<typename Allocator> template<typename AllocatorA, typename AllocatorB> TBitArray TBitArray< Allocator >::BitwiseAND (const TBitArray< AllocatorA > & A, const TBitArray< AllocatorB > & B, EBitwiseOperatorFlags InFlags) inline static nodiscard
Return the bitwise AND of two bit arrays.
The resulting bit array will be sized according to InFlags.
Definition at line 1262 of file BitArray.h.
Referenced by UE::MovieScene::FComponentMask::BitwiseAND(), and TTypeBitSetBase< TStructTypeBitSet, TBaseStruct, TUStructType, FStructTypeBitSet::FBitSetContainer >::operator&().
BitwiseNOT()
template<typename Allocator> void TBitArray< Allocator >::BitwiseNOT () inline
Perform a bitwise NOT on all the bits in this array.
Definition at line 1339 of file BitArray.h.
BitwiseOR()
template<typename Allocator> template<typename AllocatorA, typename AllocatorB> TBitArray TBitArray< Allocator >::BitwiseOR (const TBitArray< AllocatorA > & A, const TBitArray< AllocatorB > & B, EBitwiseOperatorFlags InFlags) inline static nodiscard
Return the bitwise OR of two bit arrays.
The resulting bit array will be sized according to InFlags.
Definition at line 1293 of file BitArray.h.
Referenced by UE::MovieScene::FComponentMask::BitwiseOR(), TStructTypeBitSet< TBaseStruct, TStructTrackerWrapper, TUStructType >::operator+(), TTypeBitSetBase< TStructTypeBitSet, TBaseStruct, TUStructType, FStructTypeBitSet::FBitSetContainer >::operator+=(), and TTypeBitSetBase< TStructTypeBitSet, TBaseStruct, TUStructType, FStructTypeBitSet::FBitSetContainer >::operator|().
BitwiseXOR()
template<typename Allocator> template<typename AllocatorA, typename AllocatorB> TBitArray TBitArray< Allocator >::BitwiseXOR (const TBitArray< AllocatorA > & A, const TBitArray< AllocatorB > & B, EBitwiseOperatorFlags InFlags) inline static nodiscard
Return the bitwise XOR of two bit arrays.
The resulting bit array will be sized according to InFlags.
Definition at line 1319 of file BitArray.h.
Referenced by UE::MovieScene::FComponentMask::BitwiseXOR().
CheckInvariants()
template<typename Allocator> void TBitArray< Allocator >::CheckInvariants () const inline
Checks the invariants of this class.
Definition at line 558 of file BitArray.h.
Referenced by TBitArray< typename Allocator::BitArrayAllocator >::FindAndSetFirstZeroBit(), TBitArray< typename Allocator::BitArrayAllocator >::FindAndSetLastZeroBit(), TBitArray< typename Allocator::BitArrayAllocator >::RemoveAt(), TBitArray< typename Allocator::BitArrayAllocator >::RemoveAtSwap(), and TBitArray< typename Allocator::BitArrayAllocator >::SetRange().
ClearPartialSlackBits()
template<typename Allocator> void TBitArray< Allocator >::ClearPartialSlackBits () inline private
Clears the slack bits within the final partially relevant Word.
Definition at line 1845 of file BitArray.h.
Referenced by TBitArray< typename Allocator::BitArrayAllocator >::AddUninitialized(), TBitArray< typename Allocator::BitArrayAllocator >::Init(), TBitArray< typename Allocator::BitArrayAllocator >::Realloc(), TBitArray< typename Allocator::BitArrayAllocator >::RemoveAt(), TBitArray< typename Allocator::BitArrayAllocator >::RemoveAtSwap(), TBitArray< typename Allocator::BitArrayAllocator >::Serialize(), and TBitArray< typename Allocator::BitArrayAllocator >::SetNumUninitialized().
CombineWithBinaryOp()
template<typename Allocator> template<typename OtherAllocator, typename BinaryOpType> TBitArray & TBitArray< Allocator >::CombineWithBinaryOp (const TBitArray< OtherAllocator > & InOther, EBitwiseOperatorFlags InFlags, BinaryOpType && InBinaryOp) inline
Perform a custom bitwise operation on this bit array with another.
This array receives the result and will be sized max(A.Num(), B.Num()).
Definition at line 1273 of file BitArray.h.
CombineWithBitwiseAND()
template<typename Allocator> template<typename OtherAllocator> TBitArray & TBitArray< Allocator >::CombineWithBitwiseAND (const TBitArray< OtherAllocator > & InOther, EBitwiseOperatorFlags InFlags) inline
Perform a bitwise AND on this bit array with another.
This array receives the result and will be sized max(A.Num(), B.Num()).
Definition at line 1283 of file BitArray.h.
CombineWithBitwiseOR()
template<typename Allocator> template<typename OtherAllocator> TBitArray & TBitArray< Allocator >::CombineWithBitwiseOR (const TBitArray< OtherAllocator > & InOther, EBitwiseOperatorFlags InFlags) inline
Return the bitwise OR of two bit arrays.
The resulting bit array will be sized according to InFlags.
Definition at line 1309 of file BitArray.h.
CombineWithBitwiseXOR()
template<typename Allocator> template<typename OtherAllocator> TBitArray & TBitArray< Allocator >::CombineWithBitwiseXOR (const TBitArray< OtherAllocator > & InOther, EBitwiseOperatorFlags InFlags) inline
Return the bitwise XOR of two bit arrays.
The resulting bit array will be sized according to InFlags.
Definition at line 1330 of file BitArray.h.
CompareSetBits()
template<typename Allocator> template<typename OtherAllocator> bool TBitArray< Allocator >::CompareSetBits (const TBitArray< OtherAllocator > & Other, const bool bMissingBitValue) const inline nodiscard
Returns true if Other contains all the same set bits as this, accounting for differences in length.
Similar to operator== but can handle different length arrays by zero or one-filling missing bits.
Parameters
Other The array to compare against
bMissingBitValue The value to use for missing bits when considering bits that are outside the range of either array
Returns
true if this array matches Other, including any missing bits, false otherwise
Definition at line 1377 of file BitArray.h.
Contains()
template<typename Allocator> FORCEINLINE bool TBitArray< Allocator >::Contains (bool bValue) const inline nodiscard
Checks if the array contains the specified value (true/false).
Parameters
bValue The value (true/false) to check for.
Returns
true if the array contains the specified value, false otherwise.
Definition at line 1217 of file BitArray.h.
CountBytes()
template<typename Allocator> void TBitArray< Allocator >::CountBytes (FArchive & Ar) const inline
Tracks the container's memory use through an archive.
Definition at line 1061 of file BitArray.h.
CountSetBits()
template<typename Allocator> int32 TBitArray< Allocator >::CountSetBits (int32 FromIndex = 0, int32 ToIndex = INDEX_NONE) const inline nodiscard
Count the number of set bits in this array FromIndex <= bit < ToIndex.
Definition at line 1350 of file BitArray.h.
Empty()
template<typename Allocator> void TBitArray< Allocator >::Empty (int32 ExpectedNumBits = 0) inline
Removes all bits from the array, potentially leaving space allocated for an expected number of bits about to be added.
Parameters
ExpectedNumBits - The expected number of bits about to be added.
Definition at line 772 of file BitArray.h.
end() [1/2]
template<typename Allocator> FORCEINLINE FIterator TBitArray< Allocator >::end () inline nodiscard
Definition at line 1813 of file BitArray.h.
end() [2/2]
template<typename Allocator> FORCEINLINE FConstIterator TBitArray< Allocator >::end () const inline nodiscard
Definition at line 1814 of file BitArray.h.
Find()
template<typename Allocator> int32 TBitArray< Allocator >::Find (bool bValue) const inline nodiscard
Finds the first occurrence of the specified value (true/false) in the array, and returns the bit index.
If the specified value is not found, INDEX_NONE is returned.
Parameters
bValue The value (true/false) to search for.
Returns
The index of the first occurrence of the specified value (true/false), or INDEX_NONE if not found.
Definition at line 1077 of file BitArray.h.
FindAndSetFirstZeroBit()
template<typename Allocator> int32 TBitArray< Allocator >::FindAndSetFirstZeroBit (int32 StartIndex = 0) inline
Finds the first occurrence of a zero bit in the array and sets it to one, returning the bit index.
If there are no zero bits in the array, INDEX_NONE is returned.
Parameters
StartIndex The index to start the search from. Defaults to 0.
Returns
The index of the first occurrence of a zero bit that was successfully set to one, or INDEX_NONE if not found.
Definition at line 1230 of file BitArray.h.
FindAndSetLastZeroBit()
template<typename Allocator> int32 TBitArray< Allocator >::FindAndSetLastZeroBit () inline
Finds the last occurrence of a zero bit in the array and sets it to one, returning the bit index.
If there are no zero bits in the array, INDEX_NONE is returned.
Returns
The index of the last occurrence of a zero bit that was successfully set to one, or INDEX_NONE if not found.
Definition at line 1247 of file BitArray.h.
FindFrom()
template<typename Allocator> template<typename IndexType> FORCEINLINE int32 TBitArray< Allocator >::FindFrom (bool bValue, IndexType StartIndex) const inline nodiscard
Finds the first occurrence of the specified value (true/false) in the array, starting from the given bit index, and returns the bit index.
If the specified value is not found from the given index, INDEX_NONE is returned.
Parameters
bValue The value (true/false) to search for.
StartIndex The index to start the search from.
Precondition
StartIndex is expected to be in the inclusive range [0, Num()].
Returns
The index of the first occurrence of the specified value (true/false) from StartIndex, or INDEX_NONE if not found.
Definition at line 1170 of file BitArray.h.
FindFromImpl()
template<typename Allocator> int32 TBitArray< Allocator >::FindFromImpl (bool bValue, int32 StartIndex) const inline private
Definition at line 1084 of file BitArray.h.
Referenced by TBitArray< typename Allocator::BitArrayAllocator >::Find(), TBitArray< typename Allocator::BitArrayAllocator >::FindAndSetFirstZeroBit(), and TBitArray< typename Allocator::BitArrayAllocator >::FindFrom().
FindLast()
template<typename Allocator> int32 TBitArray< Allocator >::FindLast (bool bValue) const inline nodiscard
Finds the last occurrence of the specified value (true/false) in the array, and returns the bit index.
If the specified value is not found, INDEX_NONE is returned.
Parameters
bValue The value (true/false) to search for.
Returns
The index of the last occurrence of the specified value (true/false), or INDEX_NONE if not found.
Definition at line 1185 of file BitArray.h.
Referenced by TBitArray< typename Allocator::BitArrayAllocator >::FindAndSetLastZeroBit().
FindLastFrom()
template<typename Allocator> template<typename IndexType> int32 TBitArray< Allocator >::FindLastFrom (bool bValue, IndexType EndIndexInclusive) const inline nodiscard
Finds the last occurrence of the specified value (true/false) in the array starting the (reverse) search from the given bit index, and returns the bit index.
If the specified value is not found, INDEX_NONE is returned.
Parameters
bValue The value (true/false) to search for.
EndIndexInclusive The index to start the (reverse) search from.
Returns
The index of the last occurrence of the specified value (true/false) from EndIndexInclusive, or INDEX_NONE if not found.
Definition at line 1200 of file BitArray.h.
FindLastFromImpl()
template<typename Allocator> int32 TBitArray< Allocator >::FindLastFromImpl (bool bValue, int32 EndIndexExclusive) const inline private
Definition at line 1117 of file BitArray.h.
Referenced by TBitArray< typename Allocator::BitArrayAllocator >::FindLast(), and TBitArray< typename Allocator::BitArrayAllocator >::FindLastFrom().
GetAllocatedSize()
template<typename Allocator> uint32 TBitArray< Allocator >::GetAllocatedSize (void) const inline nodiscard
Helper function to return the amount of memory allocated by this container.
Returns
number of bytes allocated by this container
Definition at line 1055 of file BitArray.h.
GetData() [1/2]
template<typename Allocator> FORCEINLINE uint32 * TBitArray< Allocator >::GetData () inline nodiscard
Definition at line 1682 of file BitArray.h.
GetData() [2/2]
template<typename Allocator> FORCEINLINE const uint32 * TBitArray< Allocator >::GetData () const inline nodiscard
Definition at line 1677 of file BitArray.h.
Referenced by TBitArray< Allocator >::FConstWordIterator::FConstWordIterator(), TBitArray< Allocator >::FConstWordIterator::FConstWordIterator(), TBitArray< Allocator >::FWordIterator::FWordIterator(), TBitArray< typename Allocator::BitArrayAllocator >::AccessCorrespondingBit(), TBitArray< typename Allocator::BitArrayAllocator >::AccessCorrespondingBit(), TBitArray< typename Allocator::BitArrayAllocator >::Assign(), TBitArray< typename Allocator::BitArrayAllocator >::CheckInvariants(), TBitArray< typename Allocator::BitArrayAllocator >::ClearPartialSlackBits(), TBitArray< typename Allocator::BitArrayAllocator >::FindFromImpl(), TBitArray< typename Allocator::BitArrayAllocator >::FindLastFromImpl(), TBitArray< typename Allocator::BitArrayAllocator >::GetRange(), GetTypeHash(), TBitArray< typename Allocator::BitArrayAllocator >::Init(), TBitArray< typename Allocator::BitArrayAllocator >::InsertUninitialized(), TBitArray< typename Allocator::BitArrayAllocator >::operator<(), TBitArray< typename Allocator::BitArrayAllocator >::operator==(), TBitArray< typename Allocator::BitArrayAllocator >::operator[](), TBitArray< typename Allocator::BitArrayAllocator >::operator[](), TBitArray< typename Allocator::BitArrayAllocator >::RemoveAt(), TBitArray< typename Allocator::BitArrayAllocator >::RemoveAtSwap(), TBitArray< typename Allocator::BitArrayAllocator >::Serialize(), TBitArray< typename Allocator::BitArrayAllocator >::SetBitNoCheck(), TBitArray< typename Allocator::BitArrayAllocator >::SetRange(), TBitArray< typename Allocator::BitArrayAllocator >::SetRangeFromRange(), and TBitArray< typename Allocator::BitArrayAllocator >::SetRangeFromRange().
GetLastWordMask()
template<typename Allocator> FORCEINLINE uint32 TBitArray< Allocator >::GetLastWordMask (int32 EndIndexExclusive) const inline nodiscard private
Definition at line 504 of file BitArray.h.
Referenced by TBitArray< typename Allocator::BitArrayAllocator >::FindLastFromImpl().
GetMaxWords()
template<typename Allocator> FORCEINLINE uint32 TBitArray< Allocator >::GetMaxWords () const inline nodiscard private
Definition at line 499 of file BitArray.h.
Referenced by TBitArray< typename Allocator::BitArrayAllocator >::CountBytes(), TBitArray< typename Allocator::BitArrayAllocator >::Init(), and TBitArray< typename Allocator::BitArrayAllocator >::Reserve().
GetNumWords()
template<typename Allocator> FORCEINLINE uint32 TBitArray< Allocator >::GetNumWords () const inline nodiscard private
Definition at line 494 of file BitArray.h.
Referenced by TBitArray< typename Allocator::BitArrayAllocator >::CountBytes(), TBitArray< typename Allocator::BitArrayAllocator >::Init(), TBitArray< typename Allocator::BitArrayAllocator >::operator<(), and TBitArray< typename Allocator::BitArrayAllocator >::Serialize().
GetRange()
template<typename Allocator> template<typename InWordType> FORCEINLINE void TBitArray< Allocator >::GetRange (int32 Index, int32 NumBitsToGet, InWordType * WriteBits, int32 WriteOffsetBits = 0) const inline
Reads a range of bits within the array and writes them to the given pointer.
Parameters
Index The index of the first bit to read; must be 0 <= Index <= Num().
NumBitsToGet The number of bits to read, must satisify 0 <= NumBitsToGet && Index + NumBitsToGet <= Num().
WriteBits The address of sized integers to write the bits to. Bits are written into WriteBits in the current platform's mathematical bitorder (WriteBits[0] & 0x1, WriteBits[0] & 0x2, ... WriteBits[0] & 0x100, ... WriteBits[0] & 0x80000000, WriteBits[1] & 0x1 ...
WriteOffsetBits Number of bits into WriteBits at which to start writing.
Definition at line 982 of file BitArray.h.
Init()
template<typename Allocator> FORCEINLINE void TBitArray< Allocator >::Init (bool bValue, int32 InNumBits) inline
Resets the array's contents.
Use TBitArray(bool bValue, int32 InNumBits) instead of default constructor and Init().
Parameters
Value - The value to initial the bits to.
NumBits - The number of bits in the array.
Definition at line 821 of file BitArray.h.
Insert() [1/2]
template<typename Allocator> void TBitArray< Allocator >::Insert (bool Value, int32 Index) inline
Adds a bit with the given value at the given index in the array.
Parameters
Value The value of the bit to add
Index - The index at which to add; must be 0 <= Index <= Num().
Definition at line 696 of file BitArray.h.
Insert() [2/2]
template<typename Allocator> void TBitArray< Allocator >::Insert (bool Value, int32 Index, int32 NumBitsToAdd) inline
Inserts multiple bits with the given value into the array, starting at the given Index.
Parameters
Value The value of the bits to add
Index The index at which to add; must be 0 <= Index <= Num().
NumBitsToAdd The number of bits to add. Must be >= 0.
Definition at line 708 of file BitArray.h.
InsertRange() [1/2]
template<typename Allocator> template<typename InWordType> void TBitArray< Allocator >::InsertRange (const InWordType * ReadBits, int32 Index, int32 NumBitsToAdd, int32 ReadOffsetBits = 0) inline
Inserts multiple bits read from the given pointer, starting at the given index.
Parameters
ReadBits The address of sized integers to read the bits from. Bits are read from ReadBits in the current platform's mathematical bitorder (ReadBits[0] & 0x1, ReadBits[0] & 0x2, ... ReadBits[0] & 0x100, ... ReadBits[0] & 0x80000000, ReadBits[1] & 0x1 ...
Index The index at which to add; must be 0 <= Index <= Num().
NumBitsToAdd The number of bits to add. Must be >= 0.
ReadOffsetBits Number of bits into ReadBits at which to start reading.
Definition at line 723 of file BitArray.h.
InsertRange() [2/2]
template<typename Allocator> template<typename OtherAllocator> void TBitArray< Allocator >::InsertRange (const TBitArray< OtherAllocator > & ReadBits, int32 Index, int32 NumBitsToAdd, int32 ReadOffsetBits = 0) inline
Inserts multiple bits read from the given BitArray into the array, starting at the given index.
Parameters
ReadBits The value to set the bits to.
Index The index at which to add; must be 0 <= Index <= Num().
NumBitsToAdd The number of bits to add. Must be >= 0.
ReadOffsetBits Number of bits into ReadBits at which to start reading.
Definition at line 737 of file BitArray.h.
InsertUninitialized()
template<typename Allocator> void TBitArray< Allocator >::InsertUninitialized (int32 Index, int32 NumBitsToAdd) inline
Inserts space for multiple bits into the array, starting at the given index.
The inserted bits are set to arbitrary values and should be written using SetRange or otherwise before being read.
Parameters
Index The index at which to add; must be 0 <= Index <= Num().
NumBitsToAdd The number of bits to add. Must be >= 0.
Definition at line 750 of file BitArray.h.
Referenced by TBitArray< typename Allocator::BitArrayAllocator >::Insert(), TBitArray< typename Allocator::BitArrayAllocator >::Insert(), TBitArray< typename Allocator::BitArrayAllocator >::InsertRange(), and TBitArray< typename Allocator::BitArrayAllocator >::InsertRange().
IsEmpty()
template<typename Allocator> bool TBitArray< Allocator >::IsEmpty () const inline nodiscard
Returns true if the bit array is empty and contains no elements.
Returns
True if the bit array is empty.
See also
Num
Definition at line 1433 of file BitArray.h.
IsValidIndex()
template<typename Allocator> FORCEINLINE bool TBitArray< Allocator >::IsValidIndex (int32 InIndex) const inline nodiscard
Definition at line 1422 of file BitArray.h.
Max()
template<typename Allocator> FORCEINLINE int32 TBitArray< Allocator >::Max () const inline nodiscard
Definition at line 1439 of file BitArray.h.
Move()
template<typename Allocator> template<typename BitArrayType> FORCEINLINE void TBitArray< Allocator >::Move (BitArrayType & ToArray, BitArrayType & FromArray) inline static private
Definition at line 527 of file BitArray.h.
Num()
template<typename Allocator> FORCEINLINE int32 TBitArray< Allocator >::Num () const inline nodiscard
Definition at line 1438 of file BitArray.h.
Referenced by TBitArray< Allocator >::FConstReverseIterator::FConstReverseIterator(), TBitArray< Allocator >::FConstWordIterator::FConstWordIterator(), TBitArray< Allocator >::FReverseIterator::FReverseIterator(), TBitArray< Allocator >::FWordIterator::FWordIterator(), GetTypeHash(), TBitArray< typename Allocator::BitArrayAllocator >::operator<(), TMeshElementArrayBase< ElementType >::operator<<, TBitArray< typename Allocator::BitArrayAllocator >::operator==(), TBitArray< typename Allocator::BitArrayAllocator >::PadToNum(), STreeView< FRigVMSearchResult >::PopulateLinearizedItems(), UE::MovieScene::TSimpleBlenderSystemImpl< PropertyType, ResultTraits >::Run(), and UE::MovieScene::TSimpleBlenderSystemImpl< PropertyType, ResultTraits >::Schedule().
operator!=()
template<typename Allocator> FORCEINLINE bool TBitArray< Allocator >::operator!= (const TBitArray< Allocator > & Other) const inline nodiscard
Definition at line 487 of file BitArray.h.
operator<()
template<typename Allocator> FORCEINLINE bool TBitArray< Allocator >::operator< (const TBitArray< Allocator > & Other) const inline nodiscard
Definition at line 463 of file BitArray.h.
operator=() [1/3]
template<typename Allocator> FORCEINLINE TBitArray & TBitArray< Allocator >::operator= (const TBitArray< Allocator > & Copy) inline
Assignment operator.
Definition at line 433 of file BitArray.h.
operator=() [2/3]
template<typename Allocator> template<typename OtherAllocator> FORCEINLINE TBitArray & TBitArray< Allocator >::operator= (const TBitArray< OtherAllocator > & Copy) inline
Definition at line 445 of file BitArray.h.
operator=() [3/3]
template<typename Allocator> FORCEINLINE TBitArray & TBitArray< Allocator >::operator= (TBitArray< Allocator > && Other) inline
Move assignment.
Definition at line 420 of file BitArray.h.
operator==()
template<typename Allocator> FORCEINLINE bool TBitArray< Allocator >::operator== (const TBitArray< Allocator > & Other) const inline nodiscard
Definition at line 453 of file BitArray.h.
operator[]() [1/2]
template<typename Allocator> FORCEINLINE FBitReference TBitArray< Allocator >::operator[] (int32 Index) inline nodiscard
Definition at line 1440 of file BitArray.h.
operator[]() [2/2]
template<typename Allocator> FORCEINLINE const FConstBitReference TBitArray< Allocator >::operator[] (int32 Index) const inline nodiscard
Definition at line 1448 of file BitArray.h.
PadToNum()
template<typename Allocator> int32 TBitArray< Allocator >::PadToNum (int32 DesiredNum, bool bPadValue) inline
Pad this bit array with the specified value to ensure that it is at least the specified length.
Does nothing if Num() >= DesiredNum.
Parameters
DesiredNum The desired number of elements that should exist in the array.
bPadValue The value to pad with (0 or 1)
Returns
The number of bits that were added to the array, or 0 if Num() >= DesiredNum.
Definition at line 1410 of file BitArray.h.
rbegin() [1/2]
template<typename Allocator> FORCEINLINE FReverseIterator TBitArray< Allocator >::rbegin () inline nodiscard
Definition at line 1816 of file BitArray.h.
rbegin() [2/2]
template<typename Allocator> FORCEINLINE FConstReverseIterator TBitArray< Allocator >::rbegin () const inline nodiscard
Definition at line 1817 of file BitArray.h.
Realloc()
template<typename Allocator> FORCENOINLINE void TBitArray< Allocator >::Realloc (int32 PreviousNumBits) inline private
Definition at line 1826 of file BitArray.h.
Referenced by TBitArray< typename Allocator::BitArrayAllocator >::Empty(), TBitArray< typename Allocator::BitArrayAllocator >::Reserve(), and TBitArray< typename Allocator::BitArrayAllocator >::Serialize().
RemoveAt()
template<typename Allocator> void TBitArray< Allocator >::RemoveAt (int32 BaseIndex, int32 NumBitsToRemove = 1) inline
Removes bits from the array.
Parameters
BaseIndex - The index of the first bit to remove.
NumBitsToRemove - The number of consecutive bits to remove.
Definition at line 997 of file BitArray.h.
RemoveAtSwap()
template<typename Allocator> void TBitArray< Allocator >::RemoveAtSwap (int32 BaseIndex, int32 NumBitsToRemove = 1) inline
Definition at line 1020 of file BitArray.h.
rend() [1/2]
template<typename Allocator> FORCEINLINE FReverseIterator TBitArray< Allocator >::rend () inline nodiscard
Definition at line 1818 of file BitArray.h.
rend() [2/2]
template<typename Allocator> FORCEINLINE FConstReverseIterator TBitArray< Allocator >::rend () const inline nodiscard
Definition at line 1819 of file BitArray.h.
Reserve()
template<typename Allocator> void TBitArray< Allocator >::Reserve (int32 Number) inline
Reserves memory such that the array can contain at least Number bits.
@Number The number of bits to reserve space for.
Definition at line 793 of file BitArray.h.
Referenced by TBitArray< typename Allocator::BitArrayAllocator >::AddUninitialized().
Reset()
template<typename Allocator> void TBitArray< Allocator >::Reset () inline
Removes all bits from the array retaining any space already allocated.
Definition at line 810 of file BitArray.h.
Serialize()
template<typename Allocator> void TBitArray< Allocator >::Serialize (FArchive & Ar) inline
Serializer.
Definition at line 580 of file BitArray.h.
Referenced by operator<<().
SetBitNoCheck()
template<typename Allocator> void TBitArray< Allocator >::SetBitNoCheck (int32 Index, bool Value) inline private
Definition at line 1835 of file BitArray.h.
Referenced by TBitArray< typename Allocator::BitArrayAllocator >::Add(), and TBitArray< typename Allocator::BitArrayAllocator >::Insert().
SetNum()
template<typename Allocator> template<typename ValueType> FORCENOINLINE void TBitArray< Allocator >::SetNum (int32 InNumBits, ValueType bValue) inline
Sets the number of bits, initializing any potentially added bits to the given value.
Definition at line 863 of file BitArray.h.
SetNumUninitialized()
template<typename Allocator> void TBitArray< Allocator >::SetNumUninitialized (int32 InNumBits) inline
Sets number of bits without initializing new bits.
Definition at line 842 of file BitArray.h.
Referenced by TMeshElementArrayBase< ElementType >::operator<<, and TBitArray< typename Allocator::BitArrayAllocator >::SetNum().
SetRange()
template<typename Allocator> FORCENOINLINE void TBitArray< Allocator >::SetRange (int32 Index, int32 NumBitsToSet, bool Value) inline
Sets or unsets a range of bits within the array.
Parameters
Index The index of the first bit to set; must be 0 <= Index <= Num().
NumBitsToSet The number of bits to set, must satisify Index + NumBitsToSet <= Num().
Value The value to set the bits to.
Definition at line 880 of file BitArray.h.
Referenced by TBitArray< typename Allocator::BitArrayAllocator >::Add(), TBitArray< typename Allocator::BitArrayAllocator >::Insert(), and TBitArray< typename Allocator::BitArrayAllocator >::SetNum().
SetRangeFromRange() [1/2]
template<typename Allocator> template<typename InWordType> void TBitArray< Allocator >::SetRangeFromRange (int32 Index, int32 NumBitsToSet, const InWordType * ReadBits, int32 ReadOffsetBits = 0) inline
Sets range of bits within the TBitArray to the values read out of a pointer.
Parameters
Index The index of the first bit to set; must be 0 <= Index <= Num().
NumBitsToSet The number of bits to set, must satisify 0 <= NumBitsToSet && Index + NumBitsToSet <= Num().
ReadBits The address of sized integers to read the bits from. Bits are read from ReadBits in the current platform's mathematical bitorder (ReadBits[0] & 0x1, ReadBits[0] & 0x2, ... ReadBits[0] & 0x100, ... ReadBits[0] & 0x80000000, ReadBits[1] & 0x1 ...
ReadOffsetBits Number of bits into ReadBits at which to start reading.
Definition at line 947 of file BitArray.h.
Referenced by TBitArray< typename Allocator::BitArrayAllocator >::AddRange(), TBitArray< typename Allocator::BitArrayAllocator >::AddRange(), TBitArray< typename Allocator::BitArrayAllocator >::InsertRange(), and TBitArray< typename Allocator::BitArrayAllocator >::InsertRange().
SetRangeFromRange() [2/2]
template<typename Allocator> template<typename OtherAllocator> FORCEINLINE void TBitArray< Allocator >::SetRangeFromRange (int32 Index, int32 NumBitsToSet, const TBitArray< OtherAllocator > & ReadBits, int32 ReadOffsetBits = 0) inline
Sets range of bits within this TBitArray to the values read out another TBitArray.
Parameters
Index The index of the first bit to set; must be 0 <= Index <= Num().
NumBitsToSet The number of bits to set, must satisify 0 <= NumBitsToSet && Index + NumBitsToSet <= Num().
ReadBits The value to set the bits to.
ReadOffsetBits Number of bits into ReadBits at which to start reading.
Definition at line 966 of file BitArray.h.
SetWords()
template<typename Allocator> FORCEINLINE void TBitArray< Allocator >::SetWords (uint32 * Words, int32 NumWords, bool bValue) inline static private
Definition at line 510 of file BitArray.h.
Referenced by TBitArray< typename Allocator::BitArrayAllocator >::Init().
WriteMemoryImage()
template<typename Allocator> void TBitArray< Allocator >::WriteMemoryImage (FMemoryImageWriter & Writer) const inline
Definition at line 1880 of file BitArray.h.
Referenced by TSparseArray< SetElementType, typename Allocator::SparseArrayAllocator >::WriteMemoryImage().
Friends And Related Symbol Documentation
TConstDualSetBitIterator
template<typename Allocator> template<typename, typename, bool> friend class TConstDualSetBitIterator friend
Definition at line 371 of file BitArray.h.
TConstSetBitIterator
template<typename Allocator> template<typename> friend class TConstSetBitIterator friend
Definition at line 368 of file BitArray.h.
TScriptBitArray
template<typename Allocator> template<typename, typename> friend class TScriptBitArray friend
Definition at line 352 of file BitArray.h.
UE::Core::Private::BitwiseBinaryOperatorImpl
template<typename Allocator> template<typename AllocatorA, typename AllocatorB, typename OutAllocator, typename ProjectionType> void UE::Core::Private::BitwiseBinaryOperatorImpl (const TBitArray< AllocatorA > & , const TBitArray< AllocatorB > & , TBitArray< OutAllocator > & , EBitwiseOperatorFlags , ProjectionType &&) friend
UE::Core::Private::BitwiseOperatorImpl
template<typename Allocator> template<typename OtherAllocator, typename OutAllocator, typename ProjectionType> void UE::Core::Private::BitwiseOperatorImpl (const TBitArray< OtherAllocator > & , TBitArray< OutAllocator > & , EBitwiseOperatorFlags , ProjectionType &&) friend
Field Documentation
AllocatorInstance
template<typename Allocator> AllocatorType TBitArray< Allocator >::AllocatorInstance private
Definition at line 1822 of file BitArray.h.
FullWordMask
template<typename Allocator> WordType TBitArray< Allocator >::FullWordMask = (WordType)-1 static constexpr private
Definition at line 361 of file BitArray.h.
MaxBits
template<typename Allocator> int32 TBitArray< Allocator >::MaxBits private
Definition at line 1824 of file BitArray.h.
NumBits
template<typename Allocator> int32 TBitArray< Allocator >::NumBits private
Definition at line 1823 of file BitArray.h.
Referenced by TBitArray< typename Allocator::BitArrayAllocator >::AddRange(), TBitArray< typename Allocator::BitArrayAllocator >::InsertRange(), and TBitArray< typename Allocator::BitArrayAllocator >::SetRangeFromRange().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Containers/BitArray.h