Unreal Engine 5.6 C++ API: AWorldPartitionMiniMap Class Reference
AWorldPartitionMiniMap Class Reference abstract
#include "WorldPartitionMiniMap.h"
Private Member Functions
virtual void CheckForErrors () override
void GetMiniMapResolution (int32 &OutMinimapImageSizeX, int32 &OutMinimapImageSizeY, int32 &OutWorldUnitsPerPixel) const
FBox GetMiniMapWorldBounds () const
virtual GENERATED_BODY() private bool IsEditorOnly () const final
virtual bool IsLockLocation () const
virtual bool IsUserManaged () const final
virtual void PostLoad () override
UPROPERTY ()
Target world units per pixel for the minimap texture.
UPROPERTY ()
Size of the loading region that will be used when iterating over the whole map during the minimap build process.
UPROPERTY ()
UPROPERTY () FBox MiniMapWorldBounds
UPROPERTY () FBox2D UVOffset
UPROPERTY () int32 MiniMapTileSize_DEPRECATED=0
UPROPERTY () TEnumAsByte< ESceneCaptureSource > CaptureSource
UPROPERTY () TObjectPtr< UTexture2D > MiniMapTexture
UPROPERTY () TSet< TObjectPtr< UDataLayerAsset > > ExcludedDataLayers
Private Attributes
AdvancedDisplay int32 BuilderCellSize
AdvancedDisplay uint32 CaptureWarmupFrames
AdvancedDisplay int32 WorldUnitsPerPixel
Detailed Description
Definition at line 15 of file WorldPartitionMiniMap.h.
Member Function Documentation
CheckForErrors()
virtual void AWorldPartitionMiniMap::CheckForErrors () override private virtual
GetMiniMapResolution()
void AWorldPartitionMiniMap::GetMiniMapResolution (int32 & OutMinimapImageSizeX, int32 & OutMinimapImageSizeY, int32 & OutWorldUnitsPerPixel) const private
GetMiniMapWorldBounds()
FBox AWorldPartitionMiniMap::GetMiniMapWorldBounds () const private
IsEditorOnly()
virtual GENERATED_BODY() private bool AWorldPartitionMiniMap::IsEditorOnly () const inline final private virtual
Definition at line 30 of file WorldPartitionMiniMap.h.
IsLockLocation()
virtual bool AWorldPartitionMiniMap::IsLockLocation () const inline private virtual
Definition at line 34 of file WorldPartitionMiniMap.h.
IsUserManaged()
virtual bool AWorldPartitionMiniMap::IsUserManaged () const inline final private virtual
Definition at line 35 of file WorldPartitionMiniMap.h.
PostLoad()
virtual void AWorldPartitionMiniMap::PostLoad () override private virtual
Reimplemented from AInfo.
UPROPERTY() [1/9]
AWorldPartitionMiniMap::UPROPERTY () private
Target world units per pixel for the minimap texture.
May not end up being the final minimap accuracy if the resulting texture resolution is unsupported.
References Category, and meta.
UPROPERTY() [2/9]
AWorldPartitionMiniMap::UPROPERTY () private
Size of the loading region that will be used when iterating over the whole map during the minimap build process.
A smaller size may help reduce blurriness as it will put less pressure on various graphics pools, at the expanse of an increase in processing time.
References Category, meta, and UPROPERTY().
UPROPERTY() [3/9]
AWorldPartitionMiniMap::UPROPERTY () private
References Category, meta, and UPROPERTY().
UPROPERTY() [4/9]
AWorldPartitionMiniMap::UPROPERTY () private
References Category.
Referenced by UPROPERTY(), UPROPERTY(), and UPROPERTY().
UPROPERTY() [5/9]
AWorldPartitionMiniMap::UPROPERTY () private
References Category.
UPROPERTY() [6/9]
AWorldPartitionMiniMap::UPROPERTY () private pure virtual
References UPROPERTY().
UPROPERTY() [7/9]
AWorldPartitionMiniMap::UPROPERTY () private
References Category, and UPROPERTY().
UPROPERTY() [8/9]
AWorldPartitionMiniMap::UPROPERTY () private
References Category.
UPROPERTY() [9/9]
AWorldPartitionMiniMap::UPROPERTY () private
References Category.
Field Documentation
BuilderCellSize
AdvancedDisplay int32 AWorldPartitionMiniMap::BuilderCellSize private
Definition at line 69 of file WorldPartitionMiniMap.h.
CaptureWarmupFrames
AdvancedDisplay uint32 AWorldPartitionMiniMap::CaptureWarmupFrames private
Definition at line 77 of file WorldPartitionMiniMap.h.
WorldUnitsPerPixel
AdvancedDisplay int32 AWorldPartitionMiniMap::WorldUnitsPerPixel private
Definition at line 62 of file WorldPartitionMiniMap.h.
The documentation for this class was generated from the following file:
Runtime/Engine/Public/WorldPartition/WorldPartitionMiniMap.h