Unreal Engine 5.6 C++ API: FSlateControlledConstruction Class Reference
FSlateControlledConstruction Class Reference abstract
#include "SlateControlledConstruction.h"
Public Member Functions
FSlateControlledConstruction ()=default
virtual ~FSlateControlledConstruction ()=default
virtual const FSlateWidgetClassData & GetWidgetClass () const =0
void operator delete (void *mem)
Static Public Member Functions
static const FSlateWidgetClassData & StaticWidgetClass ()
Private Member Functions
FSlateControlledConstruction (const FSlateControlledConstruction &Other)=delete
UI objects cannot be copy-constructed.
void * operator new (const size_t InSize)
Widgets should only ever be constructed via SNew or SAssignNew.
void * operator new (const size_t InSize, void *Addr)
Widgets should only ever be constructed via SNew or SAssignNew.
void operator= (const FSlateControlledConstruction &Other)=delete
UI objects cannot be copied.
Friends
template<typename ObjectType, ESPMode Mode>
class SharedPointerInternals::TIntrusiveReferenceController
template<class WidgetType, bool bIsUserWidget>
struct TWidgetAllocator
Detailed Description
Definition at line 84 of file SlateControlledConstruction.h.
Constructor & Destructor Documentation
FSlateControlledConstruction() [1/2]
FSlateControlledConstruction::FSlateControlledConstruction () default
Referenced by FSlateControlledConstruction(), operator=(), and SWidget::SLATE_DECLARE_WIDGET_API().
~FSlateControlledConstruction()
virtual FSlateControlledConstruction::~FSlateControlledConstruction () virtual default
FSlateControlledConstruction() [2/2]
FSlateControlledConstruction::FSlateControlledConstruction (const FSlateControlledConstruction & Other) private delete
UI objects cannot be copy-constructed.
References FSlateControlledConstruction(), and Other.
Member Function Documentation
GetWidgetClass()
virtual const FSlateWidgetClassData & FSlateControlledConstruction::GetWidgetClass () const pure virtual
operator delete()
void FSlateControlledConstruction::operator delete (void * mem) inline
Definition at line 125 of file SlateControlledConstruction.h.
References FMemory::Free().
operator new() [1/2]
void * FSlateControlledConstruction::operator new (const size_t InSize) inline private
Widgets should only ever be constructed via SNew or SAssignNew.
Definition at line 106 of file SlateControlledConstruction.h.
operator new() [2/2]
void * FSlateControlledConstruction::operator new (const size_t InSize, void * Addr) inline private
Widgets should only ever be constructed via SNew or SAssignNew.
Definition at line 112 of file SlateControlledConstruction.h.
operator=()
void FSlateControlledConstruction::operator= (const FSlateControlledConstruction & Other) private delete
UI objects cannot be copied.
References FSlateControlledConstruction(), and Other.
StaticWidgetClass()
const FSlateWidgetClassData & FSlateControlledConstruction::StaticWidgetClass () inline static
Definition at line 91 of file SlateControlledConstruction.h.
References Instance, and TEXT.
Friends And Related Symbol Documentation
SharedPointerInternals::TIntrusiveReferenceController
template<typename ObjectType, ESPMode Mode> friend class SharedPointerInternals::TIntrusiveReferenceController friend
Definition at line 122 of file SlateControlledConstruction.h.
TWidgetAllocator
template<class WidgetType, bool bIsUserWidget> friend struct TWidgetAllocator friend
Definition at line 118 of file SlateControlledConstruction.h.
References TWidgetAllocator.
Referenced by TWidgetAllocator.
The documentation for this class was generated from the following file:
Runtime/SlateCore/Public/Widgets/SlateControlledConstruction.h