Unreal Engine 5.6 C++ API: FOctreeChildNodeSubset Class Reference
FOctreeChildNodeSubset Class Reference
A subset of an octree node's children that intersect a bounding box.
#include "GenericOctree.h"
Public Member Functions
FOctreeChildNodeSubset ()
Initializes the subset to be empty.
FOctreeChildNodeSubset (FOctreeChildNodeRef ChildRef)
Initializes the subset to contain a single node.
bool Contains (FOctreeChildNodeRef ChildRef) const
Determines whether the subset contains a specific node.
Data Fields
union {
struct {
uint32 bNegativeX: 1
uint32 bNegativeY: 1
uint32 bNegativeZ: 1
uint32 bPositiveX: 1
uint32 bPositiveY: 1
uint32 bPositiveZ: 1
}
struct {
uint32 NegativeChildBits: 3
Only the bits for the children on the negative side of the splits.
uint32 PositiveChildBits: 3
Only the bits for the children on the positive side of the splits.
}
uint32 AllBits
All the bits used to store the subset.
uint32 ChildBits: 6
All the bits corresponding to the child bits.
};
Detailed Description
A subset of an octree node's children that intersect a bounding box.
Definition at line 200 of file GenericOctree.h.
Constructor & Destructor Documentation
FOctreeChildNodeSubset() [1/2]
FOctreeChildNodeSubset::FOctreeChildNodeSubset () inline
Initializes the subset to be empty.
Definition at line 233 of file GenericOctree.h.
References AllBits.
FOctreeChildNodeSubset() [2/2]
FOctreeChildNodeSubset::FOctreeChildNodeSubset (FOctreeChildNodeRef ChildRef) inline
Initializes the subset to contain a single node.
Definition at line 238 of file GenericOctree.h.
References AllBits, FOctreeChildNodeRef::Index, NegativeChildBits, and PositiveChildBits.
Member Function Documentation
Contains()
bool FOctreeChildNodeSubset::Contains (FOctreeChildNodeRef ChildRef) const nodiscard
Determines whether the subset contains a specific node.
Referenced by TOctree2< FVolumeLightingSample, FLightVolumeOctreeSemantics >::FindElementsWithBoundsTestInternal(), TOctree2< FVolumeLightingSample, FLightVolumeOctreeSemantics >::FindFirstElementWithBoundsTestInternal(), and TOctree_DEPRECATED< ElementType, OctreeSemantics >::TConstElementBoxIterator< StackAllocator >::ProcessChildren().
Field Documentation
[union]
union { ... } FOctreeChildNodeSubset
AllBits
uint32 FOctreeChildNodeSubset::AllBits
All the bits used to store the subset.
Definition at line 229 of file GenericOctree.h.
Referenced by FOctreeChildNodeSubset(), and FOctreeChildNodeSubset().
bNegativeX
uint32 FOctreeChildNodeSubset::bNegativeX
Definition at line 211 of file GenericOctree.h.
bNegativeY
uint32 FOctreeChildNodeSubset::bNegativeY
Definition at line 212 of file GenericOctree.h.
bNegativeZ
uint32 FOctreeChildNodeSubset::bNegativeZ
Definition at line 213 of file GenericOctree.h.
bPositiveX
uint32 FOctreeChildNodeSubset::bPositiveX
Definition at line 208 of file GenericOctree.h.
bPositiveY
uint32 FOctreeChildNodeSubset::bPositiveY
Definition at line 209 of file GenericOctree.h.
bPositiveZ
uint32 FOctreeChildNodeSubset::bPositiveZ
Definition at line 210 of file GenericOctree.h.
ChildBits
uint32 FOctreeChildNodeSubset::ChildBits
All the bits corresponding to the child bits.
Definition at line 226 of file GenericOctree.h.
NegativeChildBits
uint32 FOctreeChildNodeSubset::NegativeChildBits
Only the bits for the children on the negative side of the splits.
Definition at line 222 of file GenericOctree.h.
Referenced by FOctreeChildNodeSubset().
PositiveChildBits
uint32 FOctreeChildNodeSubset::PositiveChildBits
Only the bits for the children on the positive side of the splits.
Definition at line 219 of file GenericOctree.h.
Referenced by FOctreeChildNodeSubset().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Math/GenericOctree.h