Unreal Engine 5.6 C++ API: UNiagaraDataInterfaceGeometryCollection Class Reference
UNiagaraDataInterfaceGeometryCollection Class Reference
#include "NiagaraDataInterfaceGeometryCollection.h"
Protected Member Functions
virtual bool CopyToInternal (UNiagaraDataInterface *Destination) const override
Copy one niagara DI to this.
Private Member Functions
virtual void BuildShaderParameters (FNiagaraShaderParametersBuilder &ShaderParametersBuilder) const override
GPU simulation functionality.
virtual ETickingGroup CalculateTickGroup (const void *PerInstanceData) const override
virtual bool CanExecuteOnTarget (ENiagaraSimTarget Target) const override
virtual void DestroyPerInstanceData (void *PerInstanceData, FNiagaraSystemInstance *SystemInstance) override
BoundsMax RootTransform_Translation RootTransform_Scale PrevWorldTransformBuffer PrevWorldInverseTransformBuffer ElementTransforms END_SHADER_PARAMETER_STRUCT () UPROPERTY() ENDIGeometryCollection_SourceMode SourceMode
Controls how to retrieve the Skeletal Mesh Component to attach to.
virtual bool Equals (const UNiagaraDataInterface *Other) const override
GENERATED_UCLASS_BODY () BEGIN_SHADER_PARAMETER_STRUCT(FShaderParameters
void GetActorTransform (FVectorVMExternalFunctionContext &Context)
void GetElementBounds (FVectorVMExternalFunctionContext &Context)
void GetElementTransformCS (FVectorVMExternalFunctionContext &Context)
void GetNumGeometryElements (FVectorVMExternalFunctionContext &Context)
virtual void GetVMExternalFunction (const FVMExternalFunctionBindingInfo &BindingInfo, void *InstanceData, FVMExternalFunction &OutFunc) override
UNiagaraDataInterface Interface.
virtual bool HasPostSimulateTick () const override
virtual bool HasPreSimulateTick () const override
virtual bool HasTickGroupPrereqs () const override
virtual bool InitPerInstanceData (void *PerInstanceData, FNiagaraSystemInstance *SystemInstance) override
virtual int32 PerInstanceDataSize () const override
virtual bool PerInstanceTick (void *PerInstanceData, FNiagaraSystemInstance *SystemInstance, float DeltaSeconds) override
virtual bool PerInstanceTickPostSimulate (void *PerInstanceData, FNiagaraSystemInstance *InSystemInstance, float DeltaSeconds) override
virtual void PostInitProperties () override
UObject Interface.
virtual bool PostSimulateCanOverlapFrames () const override
virtual void ProvidePerInstanceDataForRenderThread (void *DataForRenderThread, void *PerInstanceData, const FNiagaraSystemInstanceID &SystemInstance) override
void ResolveGeometryCollection (FNiagaraSystemInstance *SystemInstance, FNDIGeometryCollectionData *InstanceData)
bool ResolveGeometryCollectionFromActor (AActor *Actor, FResolvedNiagaraGeometryCollection &ResolvedSource)
bool ResolveGeometryCollectionFromAttachParent (FNiagaraSystemInstance *SystemInstance, FResolvedNiagaraGeometryCollection &ResolvedSource)
bool ResolveGeometryCollectionFromDefaultCollection (FResolvedNiagaraGeometryCollection &ResolvedSource)
bool ResolveGeometryCollectionFromDirectSource (FResolvedNiagaraGeometryCollection &ResolvedSource)
bool ResolveGeometryCollectionFromParameterBinding (UObject *UserParameter, FResolvedNiagaraGeometryCollection &ResolvedSource)
void SetElementTransformCS (FVectorVMExternalFunctionContext &Context)
void SetElementTransformWS (FVectorVMExternalFunctionContext &Context)
virtual void SetShaderParameters (const FNiagaraDataInterfaceSetShaderParametersContext &Context) const override
BoundsMax RootTransform_Translation SHADER_PARAMETER (FQuat4f, RootTransform_Rotation) SHADER_PARAMETER(FVector3f
SHADER_PARAMETER (FVector3f, BoundsMin) SHADER_PARAMETER(FVector3f
BoundsMax SHADER_PARAMETER (int32, NumPieces) SHADER_PARAMETER(FVector3f
BoundsMax RootTransform_Translation RootTransform_Scale PrevWorldTransformBuffer PrevWorldInverseTransformBuffer SHADER_PARAMETER_SRV (Buffer< float4 >, BoundsBuffer) SHADER_PARAMETER_RDG_BUFFER_SRV(ByteAddressBuffer
BoundsMax RootTransform_Translation RootTransform_Scale PrevWorldTransformBuffer SHADER_PARAMETER_SRV (Buffer< float4 >, WorldInverseTransformBuffer) SHADER_PARAMETER_SRV(Buffer< float4 >
BoundsMax RootTransform_Translation RootTransform_Scale SHADER_PARAMETER_SRV (Buffer< float4 >, WorldTransformBuffer) SHADER_PARAMETER_SRV(Buffer< float4 >
UPROPERTY () bool bIncludeIntermediateBones
UPROPERTY () TObjectPtr< UGeometryCollectionComponent > SourceComponent
The source component from which to sample.
UPROPERTY ()) FNiagaraUserParameterBinding GeometryCollectionUserParameter
Reference to a user parameter if we're reading one.
UPROPERTY ()) TObjectPtr< UGeometryCollection > DefaultGeometryCollection
GeometryCollection used to sample from when not overridden by a source actor from the scene.
UPROPERTY ()) TSoftObjectPtr< AGeometryCollectionActor > GeometryCollectionActor
The source actor from which to sample.
Detailed Description
Definition at line 185 of file NiagaraDataInterfaceGeometryCollection.h.
Member Function Documentation
BuildShaderParameters()
virtual void UNiagaraDataInterfaceGeometryCollection::BuildShaderParameters (FNiagaraShaderParametersBuilder & ShaderParametersBuilder) const override private virtual
GPU simulation functionality.
CalculateTickGroup()
virtual ETickingGroup UNiagaraDataInterfaceGeometryCollection::CalculateTickGroup (const void * PerInstanceData) const override private virtual
CanExecuteOnTarget()
virtual bool UNiagaraDataInterfaceGeometryCollection::CanExecuteOnTarget (ENiagaraSimTarget Target) const inline override private virtual
Definition at line 239 of file NiagaraDataInterfaceGeometryCollection.h.
References CanExecuteOnTarget(), and Target.
Referenced by CanExecuteOnTarget().
CopyToInternal()
virtual bool UNiagaraDataInterfaceGeometryCollection::CopyToInternal (UNiagaraDataInterface * Destination) const override protected virtual
Copy one niagara DI to this.
DestroyPerInstanceData()
virtual void UNiagaraDataInterfaceGeometryCollection::DestroyPerInstanceData (void * PerInstanceData, FNiagaraSystemInstance * SystemInstance) override private virtual
END_SHADER_PARAMETER_STRUCT()
BoundsMax RootTransform_Translation RootTransform_Scale PrevWorldTransformBuffer PrevWorldInverseTransformBuffer ElementTransforms UNiagaraDataInterfaceGeometryCollection::END_SHADER_PARAMETER_STRUCT () private
Controls how to retrieve the Skeletal Mesh Component to attach to.
References Category, Default, END_SHADER_PARAMETER_STRUCT(), and UPROPERTY().
Referenced by END_SHADER_PARAMETER_STRUCT().
Equals()
virtual bool UNiagaraDataInterfaceGeometryCollection::Equals (const UNiagaraDataInterface * Other) const override private virtual
References Other.
GENERATED_UCLASS_BODY()
UNiagaraDataInterfaceGeometryCollection::GENERATED_UCLASS_BODY () private
References BEGIN_SHADER_PARAMETER_STRUCT.
GetActorTransform()
void UNiagaraDataInterfaceGeometryCollection::GetActorTransform (FVectorVMExternalFunctionContext & Context) private
GetElementBounds()
void UNiagaraDataInterfaceGeometryCollection::GetElementBounds (FVectorVMExternalFunctionContext & Context) private
GetElementTransformCS()
void UNiagaraDataInterfaceGeometryCollection::GetElementTransformCS (FVectorVMExternalFunctionContext & Context) private
GetNumGeometryElements()
void UNiagaraDataInterfaceGeometryCollection::GetNumGeometryElements (FVectorVMExternalFunctionContext & Context) private
GetVMExternalFunction()
virtual void UNiagaraDataInterfaceGeometryCollection::GetVMExternalFunction (const FVMExternalFunctionBindingInfo & BindingInfo, void * InstanceData, FVMExternalFunction & OutFunc) override private virtual
UNiagaraDataInterface Interface.
References GetVMExternalFunction().
Referenced by GetVMExternalFunction().
HasPostSimulateTick()
virtual bool UNiagaraDataInterfaceGeometryCollection::HasPostSimulateTick () const inline override private virtual
Definition at line 247 of file NiagaraDataInterfaceGeometryCollection.h.
HasPreSimulateTick()
virtual bool UNiagaraDataInterfaceGeometryCollection::HasPreSimulateTick () const inline override private virtual
Definition at line 246 of file NiagaraDataInterfaceGeometryCollection.h.
HasTickGroupPrereqs()
virtual bool UNiagaraDataInterfaceGeometryCollection::HasTickGroupPrereqs () const inline override private virtual
Definition at line 249 of file NiagaraDataInterfaceGeometryCollection.h.
InitPerInstanceData()
virtual bool UNiagaraDataInterfaceGeometryCollection::InitPerInstanceData (void * PerInstanceData, FNiagaraSystemInstance * SystemInstance) override private virtual
PerInstanceDataSize()
virtual int32 UNiagaraDataInterfaceGeometryCollection::PerInstanceDataSize () const inline override private virtual
Definition at line 243 of file NiagaraDataInterfaceGeometryCollection.h.
PerInstanceTick()
virtual bool UNiagaraDataInterfaceGeometryCollection::PerInstanceTick (void * PerInstanceData, FNiagaraSystemInstance * SystemInstance, float DeltaSeconds) override private virtual
PerInstanceTickPostSimulate()
virtual bool UNiagaraDataInterfaceGeometryCollection::PerInstanceTickPostSimulate (void * PerInstanceData, FNiagaraSystemInstance * InSystemInstance, float DeltaSeconds) override private virtual
PostInitProperties()
virtual void UNiagaraDataInterfaceGeometryCollection::PostInitProperties () override private virtual
UObject Interface.
References PostInitProperties().
Referenced by PostInitProperties().
PostSimulateCanOverlapFrames()
virtual bool UNiagaraDataInterfaceGeometryCollection::PostSimulateCanOverlapFrames () const inline override private virtual
Definition at line 248 of file NiagaraDataInterfaceGeometryCollection.h.
ProvidePerInstanceDataForRenderThread()
virtual void UNiagaraDataInterfaceGeometryCollection::ProvidePerInstanceDataForRenderThread (void * DataForRenderThread, void * PerInstanceData, const FNiagaraSystemInstanceID & SystemInstance) override private virtual
ResolveGeometryCollection()
void UNiagaraDataInterfaceGeometryCollection::ResolveGeometryCollection (FNiagaraSystemInstance * SystemInstance, FNDIGeometryCollectionData * InstanceData) private
ResolveGeometryCollectionFromActor()
bool UNiagaraDataInterfaceGeometryCollection::ResolveGeometryCollectionFromActor (AActor * Actor, FResolvedNiagaraGeometryCollection & ResolvedSource) private
References Actor.
ResolveGeometryCollectionFromAttachParent()
bool UNiagaraDataInterfaceGeometryCollection::ResolveGeometryCollectionFromAttachParent (FNiagaraSystemInstance * SystemInstance, FResolvedNiagaraGeometryCollection & ResolvedSource) private
ResolveGeometryCollectionFromDefaultCollection()
bool UNiagaraDataInterfaceGeometryCollection::ResolveGeometryCollectionFromDefaultCollection (FResolvedNiagaraGeometryCollection & ResolvedSource) private
ResolveGeometryCollectionFromDirectSource()
bool UNiagaraDataInterfaceGeometryCollection::ResolveGeometryCollectionFromDirectSource (FResolvedNiagaraGeometryCollection & ResolvedSource) private
ResolveGeometryCollectionFromParameterBinding()
bool UNiagaraDataInterfaceGeometryCollection::ResolveGeometryCollectionFromParameterBinding (UObject * UserParameter, FResolvedNiagaraGeometryCollection & ResolvedSource) private
SetElementTransformCS()
void UNiagaraDataInterfaceGeometryCollection::SetElementTransformCS (FVectorVMExternalFunctionContext & Context) private
SetElementTransformWS()
void UNiagaraDataInterfaceGeometryCollection::SetElementTransformWS (FVectorVMExternalFunctionContext & Context) private
SetShaderParameters()
virtual void UNiagaraDataInterfaceGeometryCollection::SetShaderParameters (const FNiagaraDataInterfaceSetShaderParametersContext & Context) const override private virtual
SHADER_PARAMETER() [1/3]
BoundsMax RootTransform_Translation UNiagaraDataInterfaceGeometryCollection::SHADER_PARAMETER (FQuat4f , RootTransform_Rotation) private
References SHADER_PARAMETER().
SHADER_PARAMETER() [2/3]
UNiagaraDataInterfaceGeometryCollection::SHADER_PARAMETER (FVector3f , BoundsMin) private
References SHADER_PARAMETER().
Referenced by SHADER_PARAMETER(), SHADER_PARAMETER(), and SHADER_PARAMETER().
SHADER_PARAMETER() [3/3]
BoundsMax UNiagaraDataInterfaceGeometryCollection::SHADER_PARAMETER (int32 , NumPieces) private
References SHADER_PARAMETER().
SHADER_PARAMETER_SRV() [1/3]
BoundsMax RootTransform_Translation RootTransform_Scale PrevWorldTransformBuffer PrevWorldInverseTransformBuffer UNiagaraDataInterfaceGeometryCollection::SHADER_PARAMETER_SRV (Buffer< float4 > , BoundsBuffer) private
References Buffer, SHADER_PARAMETER_RDG_BUFFER_SRV, and SHADER_PARAMETER_SRV().
SHADER_PARAMETER_SRV() [2/3]
BoundsMax RootTransform_Translation RootTransform_Scale PrevWorldTransformBuffer UNiagaraDataInterfaceGeometryCollection::SHADER_PARAMETER_SRV (Buffer< float4 > , WorldInverseTransformBuffer) private
References Buffer, and SHADER_PARAMETER_SRV().
SHADER_PARAMETER_SRV() [3/3]
BoundsMax RootTransform_Translation RootTransform_Scale UNiagaraDataInterfaceGeometryCollection::SHADER_PARAMETER_SRV (Buffer< float4 > , WorldTransformBuffer) private
References Buffer, and SHADER_PARAMETER_SRV().
Referenced by SHADER_PARAMETER_SRV(), SHADER_PARAMETER_SRV(), and SHADER_PARAMETER_SRV().
UPROPERTY() [1/5]
UNiagaraDataInterfaceGeometryCollection::UPROPERTY () private
References Category, and UPROPERTY().
UPROPERTY() [2/5]
UNiagaraDataInterfaceGeometryCollection::UPROPERTY () private
The source component from which to sample.
Takes precedence over the direct mesh. Not exposed to the user, only indirectly accessible from blueprints.
References Transient, and UPROPERTY().
UPROPERTY() [3/5]
UNiagaraDataInterfaceGeometryCollection::UPROPERTY () private
Reference to a user parameter if we're reading one.
References Category, meta, and UPROPERTY().
UPROPERTY() [4/5]
UNiagaraDataInterfaceGeometryCollection::UPROPERTY () private
GeometryCollection used to sample from when not overridden by a source actor from the scene.
This reference is NOT removed from cooked builds.
References Category, and meta.
Referenced by END_SHADER_PARAMETER_STRUCT(), UPROPERTY(), UPROPERTY(), UPROPERTY(), and UPROPERTY().
UPROPERTY() [5/5]
UNiagaraDataInterfaceGeometryCollection::UPROPERTY () private
The source actor from which to sample.
Takes precedence over the direct geometry collection. Note that this can only be set when used as a user variable on a niagara component in the world.
References Category, meta, and UPROPERTY().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Experimental/ChaosNiagara/Source/ChaosNiagara/Public/NiagaraDataInterfaceGeometryCollection.h