Unreal Engine 5.6 C++ API: TMathUtil< RealType > Class Template Reference
TMathUtil< RealType > Class Template Reference
#include "MathUtil.h"
Static Public Member Functions
static RealType Abs (const RealType Value)
static RealType ACos (const RealType Value)
static RealType Atan2 (const RealType ValueY, const RealType ValueX)
static RealType Atan2Positive (const RealType Y, const RealType X)
static RealType Cbrt (const RealType Value)
Compute cube root.
static RealType Ceil (const RealType Value)
static RealType Clamp (const RealType Value, const RealType ClampMin, const RealType ClampMax)
static RealType Cos (const RealType Value)
static RealType Exp (const RealType Power)
static RealType Floor (const RealType Value)
static bool IsFinite (const RealType Value)
static bool IsNaN (const RealType Value)
static RealType Lerp (const RealType A, const RealType B, RealType Alpha)
static RealType Log (const RealType Value)
static RealType Max (const RealType A, const RealType B)
static RealType Max3 (const RealType A, const RealType B, const RealType C)
static int32 Max3Index (const RealType A, const RealType B, const RealType C)
static RealType Min (const RealType A, const RealType B)
static RealType Min3 (const RealType A, const RealType B, const RealType C)
static int32 Min3Index (const RealType A, const RealType B, const RealType C)
static void MinMax (RealType A, RealType B, RealType C, RealType &MinOut, RealType &MaxOut)
compute min and max of a,b,c with max 3 comparisons (sometimes 2)
static RealType Pow (const RealType Value, const RealType Power)
static RealType Round (const RealType Value)
static RealType Sign (const RealType Value)
static int32 SignAsInt (const RealType Value)
static RealType SignNonZero (const RealType Value)
static RealType Sin (const RealType Value)
static RealType SmoothMax (RealType A, RealType B, RealType BlendExtent)
Uses a quadratic blend to smooth the max transition when A and B are less than BlendExtent apart.
static RealType SmoothMin (RealType A, RealType B, RealType BlendExtent)
Uses a quadratic blend to smooth the min transition when A and B are less than BlendExtent apart.
static RealType Sqrt (const RealType Value)
static RealType Tan (const RealType Value)
Private Member Functions
TMathUtil ()=delete
Detailed Description
template<typename RealType>
class TMathUtil< RealType >
Definition at line 149 of file MathUtil.h.
Constructor & Destructor Documentation
TMathUtil()
template<typename RealType> TMathUtil< RealType >::TMathUtil () private delete
Referenced by Atan2Positive().
Member Function Documentation
Abs()
template<typename RealType> RealType TMathUtil< RealType >::Abs (const RealType Value) inline static
Definition at line 215 of file MathUtil.h.
References Value.
Referenced by UE::Geometry::TPolygon2< double >::Area(), UE::Geometry::TTriangle2< float >::Area(), UE::Geometry::VectorUtil::Area(), UE::Geometry::TTransformSRT3< float >::ClampMinimumScale(), UE::Geometry::TPlane3< FVector::FReal >::ClipSegment(), UE::Geometry::TDistLine3Segment3< float >::ComputeResult(), UE::Geometry::TDistLine3Triangle3< float >::ComputeResult(), UE::Geometry::TDistRay3Segment3< float >::ComputeResult(), UE::Geometry::TFrame3< float >::ConstrainedAlignPerpAxes(), UE::Geometry::TOrientedBox2< float >::Contains(), UE::Geometry::TOrientedBox3< float >::Contains(), UE::Geometry::TCircle2< float >::Distance(), UE::Geometry::TAxisAlignedBox3< float >::DistanceSquared(), UE::Geometry::VectorUtil::EpsilonEqual(), UE::Geometry::TPlane3< FVector::FReal >::FindLineIntersection(), UE::Geometry::TTransformSRT3< float >::GetSafeScaleReciprocal(), UE::Geometry::TTransformSRT3< float >::HasNonUniformScale(), UE::Geometry::TLine2< double >::IntersectionPoint(), UE::Geometry::TMatrix2< float >::Inverse(), UE::Geometry::TMatrix3< float >::Inverse(), UE::Geometry::IsNormalized(), UE::Geometry::IsNormalized(), UE::Geometry::MaxAbsElement(), UE::Geometry::MaxAbsElementIndex(), UE::Geometry::TInterval1< float >::MaxAbsExtrema(), UE::Geometry::MinAbsElement(), UE::Geometry::MinAbsElementIndex(), UE::Geometry::TQuaternion< RealType >::SetToSlerp(), and UE::Geometry::TDistRay3Segment3< float >::SquaredDistance().
ACos()
template<typename RealType> RealType TMathUtil< RealType >::ACos (const RealType Value) inline static
Definition at line 378 of file MathUtil.h.
References Value.
Referenced by UE::Geometry::AngleD(), UE::Geometry::AngleD(), UE::Geometry::AngleR(), UE::Geometry::AngleR(), UE::Geometry::TSphericalFibonacci< RealType >::Point(), UE::Geometry::TQuaternion< RealType >::SetToSlerp(), and UE::Geometry::SignedAngleR().
Atan2()
template<typename RealType> RealType TMathUtil< RealType >::Atan2 (const RealType ValueY, const RealType ValueX) inline static
Definition at line 360 of file MathUtil.h.
Referenced by Atan2Positive(), UE::Geometry::TSphericalFibonacci< RealType >::FindIndex(), UE::Geometry::TMatrix2< float >::GetAngleRad(), and UE::Geometry::CurveUtil::WindingIntegral2().
Atan2Positive()
template<typename RealType> RealType TMathUtil< RealType >::Atan2Positive (const RealType Y, const RealType X) inline static
Returns
result of Atan2 shifted to [0,2pi] (normal ATan2 returns in range [-pi,pi])
Definition at line 429 of file MathUtil.h.
References TMathUtil(), Atan2(), X, and Y.
Referenced by UE::Geometry::FDynamicGraph2< double >::SortedVtxEdges().
Cbrt()
template<typename RealType> RealType TMathUtil< RealType >::Cbrt (const RealType Value) inline static
Compute cube root.
Definition at line 348 of file MathUtil.h.
References Value.
Ceil()
template<typename RealType> RealType TMathUtil< RealType >::Ceil (const RealType Value) inline static
Definition at line 390 of file MathUtil.h.
References Value.
Referenced by UE::Geometry::TBoundsGridIndexer3< float >::CeilInt(), UE::Geometry::TGaussian2< float >::MakeKernelFromRadius(), and UE::Geometry::TGaussian2< float >::MakeKernelFromRadius().
Clamp()
template<typename RealType> RealType TMathUtil< RealType >::Clamp (const RealType Value, const RealType ClampMin, const RealType ClampMax) inline static
Definition at line 222 of file MathUtil.h.
References Value.
Referenced by UELocal::BlendColors_Lerp(), UE::Geometry::TPolygon2< double >::DistanceSquared(), UE::Geometry::TPolyline< T, 2 >< double >::DistanceSquared(), UE::Geometry::TSphericalFibonacci< RealType >::FindIndex(), Lerp(), UE::Geometry::TSegment2< FVector::FReal >::ProjectUnitRange(), UE::Geometry::TSegment3< float >::ProjectUnitRange(), SmoothMax(), and SmoothMin().
Cos()
template<typename RealType> RealType TMathUtil< RealType >::Cos (const RealType Value) inline static
Definition at line 372 of file MathUtil.h.
References Value.
Referenced by UE::Geometry::TMatrix3< float >::AxisAngleR(), UE::Geometry::TSphericalFibonacci< RealType >::FindIndex(), UE::Geometry::GenerateArcSegments(), UE::Geometry::GenerateCircleSegments(), UE::Geometry::TCircle2< float >::GetBoundingPolygonRadius(), UE::Geometry::TCircle2< float >::GetPointFromAngleR(), UE::Geometry::TCircle3< float >::GetPointFromAngleR(), UE::Geometry::TVectorSetAnalysis3< float >::GreedyClusterVectors(), UE::Geometry::TPolygon2< double >::MakeCircle(), UE::Geometry::TPolygon2< double >::MakeRoundedRectangle(), UE::Geometry::TFibonacciLattice< RealType >::Point(), UE::Geometry::TSphericalFibonacci< RealType >::Point(), and UE::Geometry::TMatrix2< float >::RotationRad().
Exp()
template<typename RealType> RealType TMathUtil< RealType >::Exp (const RealType Power) inline static
Definition at line 408 of file MathUtil.h.
Referenced by UE::Geometry::TGaussian1< float >::Evaluate(), UE::Geometry::TGaussian2< float >::Evaluate(), UE::Geometry::TGaussian3< float >::Evaluate(), UE::Geometry::TGaussian1< float >::EvaluateSqr(), UE::Geometry::TGaussian1< float >::EvaluateSqrUnscaled(), UE::Geometry::TGaussian2< float >::EvaluateSqrUnscaled(), UE::Geometry::TGaussian3< float >::EvaluateSqrUnscaled(), UE::Geometry::TGaussian1< float >::EvaluateUnscaled(), and UE::Geometry::TGaussian2< float >::MakeKernelFromWidth().
Floor()
template<typename RealType> RealType TMathUtil< RealType >::Floor (const RealType Value) inline static
Definition at line 384 of file MathUtil.h.
References Value.
Referenced by UE::Geometry::TSphericalFibonacci< RealType >::FindIndex(), UE::Geometry::TSphericalFibonacci< RealType >::MultiplyAddFrac(), UE::Geometry::TFibonacciLattice< RealType >::Point(), UE::Geometry::TSphericalFibonacci< RealType >::Point(), UE::Geometry::TScaleGridIndexer2< float >::ToGrid(), UE::Geometry::TScaleGridIndexer3< float >::ToGrid(), UE::Geometry::TShiftGridIndexer2< float >::ToGrid(), and UE::Geometry::TShiftGridIndexer3< float >::ToGrid().
IsFinite()
template<typename RealType> bool TMathUtil< RealType >::IsFinite (const RealType Value) inline static
Definition at line 208 of file MathUtil.h.
References Value.
Referenced by UE::Geometry::VectorUtil::IsFinite(), and UE::Geometry::VectorUtil::IsFinite().
IsNaN()
template<typename RealType> bool TMathUtil< RealType >::IsNaN (const RealType Value) inline static
Definition at line 201 of file MathUtil.h.
References Value.
Lerp()
template<typename RealType> RealType TMathUtil< RealType >::Lerp (const RealType A, const RealType B, RealType Alpha) inline static
Definition at line 422 of file MathUtil.h.
References A, Alpha, B, and Clamp().
Log()
template<typename RealType> RealType TMathUtil< RealType >::Log (const RealType Value) inline static
Definition at line 414 of file MathUtil.h.
Referenced by UE::Geometry::TSphericalFibonacci< RealType >::FindIndex().
Max()
template<typename RealType> RealType TMathUtil< RealType >::Max (const RealType A, const RealType B) inline static
Definition at line 246 of file MathUtil.h.
References A, and B.
Referenced by UE::Geometry::FAxisAlignedBox2i::Area(), UE::Geometry::TMeshDijkstra< PointSetType >::ComputeToMaxDistance(), UE::Geometry::TMeshDijkstra< PointSetType >::ComputeToTargetPoint(), UE::Geometry::FAxisAlignedBox3i::Depth(), UE::Geometry::TAxisAlignedBox3< float >::Depth(), UE::Geometry::TAxisAlignedBox3< float >::Dimension(), UE::Geometry::TCapsule3< float >::DistanceSquared(), UE::Geometry::TSphere3< float >::DistanceSquared(), UE::Geometry::TSphericalFibonacci< RealType >::FindIndex(), UE::Geometry::TSegment3< float >::GetBounds(), UE::Geometry::FAxisAlignedBox3i::Height(), UE::Geometry::TAxisAlignedBox2< FVector::FReal >::Height(), UE::Geometry::TAxisAlignedBox3< float >::Height(), UE::Geometry::TAxisAlignedBox2< FVector::FReal >::Intersect(), UE::Geometry::TAxisAlignedBox3< float >::Intersect(), UE::Geometry::TInterval1< float >::IntersectionWith(), UE::Geometry::Max(), UE::Geometry::Max(), UE::Geometry::TInterval1< float >::MaxAbsExtrema(), UE::Geometry::TAxisAlignedBox2< FVector::FReal >::MaxDim(), UE::Geometry::TAxisAlignedBox3< float >::MaxDim(), MinMax(), UE::Geometry::IntrinsicCorrespondenceUtils::FNormalCoordinates::NumCornerCrossingRefEdges(), UE::Geometry::IntrinsicCorrespondenceUtils::FNormalCoordinates::NumCornerEmanatingRefEdges(), UE::Geometry::IntrinsicCorrespondenceUtils::FNormalCoordinates::NumEdgeCrossing(), UE::Geometry::THemisphericalFibonacci< RealType >::Point(), UE::Geometry::TMeshLocalParam< PointSetType >::ProcessQueueUntilTermination(), UE::Geometry::TSkeletalRicciNaryBlend3< InputBoundedImplicitType, RealType >::Value(), UE::Geometry::FAxisAlignedBox3i::Width(), UE::Geometry::TAxisAlignedBox2< FVector::FReal >::Width(), and UE::Geometry::TAxisAlignedBox3< float >::Width().
Max3()
template<typename RealType> RealType TMathUtil< RealType >::Max3 (const RealType A, const RealType B, const RealType C) inline static
Definition at line 252 of file MathUtil.h.
References A, B, and Max.
Referenced by UE::Geometry::TAxisAlignedBox3< float >::TAxisAlignedBox3(), UE::Geometry::MaxAbsElement(), and UE::Geometry::MaxElement().
Max3Index()
template<typename RealType> int32 TMathUtil< RealType >::Max3Index (const RealType A, const RealType B, const RealType C) inline static
Definition at line 258 of file MathUtil.h.
References A, and B.
Referenced by UE::Geometry::MaxAbsElementIndex(), and UE::Geometry::MaxElementIndex().
Min()
template<typename RealType> RealType TMathUtil< RealType >::Min (const RealType A, const RealType B) inline static
Definition at line 271 of file MathUtil.h.
References A, and B.
Referenced by UE::Geometry::TPolygon2< double >::Chamfer(), UE::Geometry::TSphericalFibonacci< RealType >::FindIndex(), UE::Geometry::TSegment3< float >::GetBounds(), UE::Geometry::TAxisAlignedBox2< FVector::FReal >::Intersect(), UE::Geometry::TAxisAlignedBox3< float >::Intersect(), UE::Geometry::TInterval1< float >::IntersectionWith(), UE::Geometry::Min(), UE::Geometry::Min(), Min3(), UE::Geometry::TAxisAlignedBox2< FVector::FReal >::MinDim(), UE::Geometry::TAxisAlignedBox3< float >::MinDim(), MinMax(), and SmoothMin().
Min3()
template<typename RealType> RealType TMathUtil< RealType >::Min3 (const RealType A, const RealType B, const RealType C) inline static
Definition at line 277 of file MathUtil.h.
References A, B, and Min().
Referenced by UE::Geometry::TAxisAlignedBox3< float >::TAxisAlignedBox3(), UE::Geometry::MinAbsElement(), and UE::Geometry::MinElement().
Min3Index()
template<typename RealType> int32 TMathUtil< RealType >::Min3Index (const RealType A, const RealType B, const RealType C) inline static
Definition at line 283 of file MathUtil.h.
References A, and B.
Referenced by UE::Geometry::MinAbsElementIndex(), and UE::Geometry::MinElementIndex().
MinMax()
template<typename RealType> void TMathUtil< RealType >::MinMax (RealType A, RealType B, RealType C, RealType & MinOut, RealType & MaxOut) inline static
compute min and max of a,b,c with max 3 comparisons (sometimes 2)
Definition at line 297 of file MathUtil.h.
References A, B, Max(), and Min().
Pow()
template<typename RealType> RealType TMathUtil< RealType >::Pow (const RealType Value, const RealType Power) inline static
Definition at line 402 of file MathUtil.h.
References Value.
Referenced by UE::Geometry::TSphericalFibonacci< RealType >::FindIndex(), and UE::Geometry::TSkeletalRicciNaryBlend3< InputBoundedImplicitType, RealType >::Value().
Round()
template<typename RealType> RealType TMathUtil< RealType >::Round (const RealType Value) inline static
Definition at line 396 of file MathUtil.h.
References Value.
Referenced by UE::Geometry::TSphericalFibonacci< RealType >::FindIndex(), and UE::Geometry::CurveUtil::IsConvex2().
Sign()
template<typename RealType> RealType TMathUtil< RealType >::Sign (const RealType Value) inline static
Definition at line 234 of file MathUtil.h.
References SignAsInt(), and Value.
SignAsInt()
template<typename RealType> int32 TMathUtil< RealType >::SignAsInt (const RealType Value) inline static
Definition at line 228 of file MathUtil.h.
References Value.
Referenced by UE::Geometry::TExactIntrTriangle3Triangle3< float >::FindOrTestWithoutCoplanar(), UE::Geometry::TetUtil::IsInsideExact(), and Sign().
SignNonZero()
template<typename RealType> RealType TMathUtil< RealType >::SignNonZero (const RealType Value) inline static
Definition at line 240 of file MathUtil.h.
References Value.
Referenced by UE::Geometry::TTransformSRT3< float >::ClampMinimumScale().
Sin()
template<typename RealType> RealType TMathUtil< RealType >::Sin (const RealType Value) inline static
Definition at line 366 of file MathUtil.h.
References Value.
Referenced by UE::Geometry::TMatrix3< float >::AxisAngleR(), UE::Geometry::TSphericalFibonacci< RealType >::FindIndex(), UE::Geometry::GenerateArcSegments(), UE::Geometry::GenerateCircleSegments(), UE::Geometry::TCircle2< float >::GetPointFromAngleR(), UE::Geometry::TCircle3< float >::GetPointFromAngleR(), UE::Geometry::TPolygon2< double >::MakeCircle(), UE::Geometry::TPolygon2< double >::MakeRoundedRectangle(), UE::Geometry::TFibonacciLattice< RealType >::Point(), UE::Geometry::TSphericalFibonacci< RealType >::Point(), UE::Geometry::TMatrix2< float >::RotationRad(), and UE::Geometry::TQuaternion< RealType >::SetToSlerp().
SmoothMax()
template<typename RealType> RealType TMathUtil< RealType >::SmoothMax (RealType A, RealType B, RealType BlendExtent) inline static
Uses a quadratic blend to smooth the max transition when A and B are less than BlendExtent apart.
Definition at line 330 of file MathUtil.h.
References A, B, Clamp(), and Max.
SmoothMin()
template<typename RealType> RealType TMathUtil< RealType >::SmoothMin (RealType A, RealType B, RealType BlendExtent) inline static
Uses a quadratic blend to smooth the min transition when A and B are less than BlendExtent apart.
Definition at line 318 of file MathUtil.h.
References A, B, Clamp(), and Min().
Sqrt()
template<typename RealType> RealType TMathUtil< RealType >::Sqrt (const RealType Value) inline static
Definition at line 342 of file MathUtil.h.
References Value.
Referenced by UE::Geometry::TSampleSetStatistics< float >::CompleteSecondPass_FixedCount(), UE::MeshDeformation::ConstructValenceWeightedLaplacian(), UE::Geometry::TAxisAlignedBox2< FVector::FReal >::DiagonalLength(), UE::Geometry::TAxisAlignedBox3< float >::DiagonalLength(), UE::Geometry::Distance(), UE::Geometry::Distance(), UE::Geometry::TCircle3< float >::Distance(), UE::Geometry::TriangleUtil::EquilateralEdgeLengthForArea(), UE::Geometry::TSphericalFibonacci< RealType >::FindIndex(), UE::Geometry::TDistLine3Circle3< float >::Get(), UE::Geometry::TDistLine3Segment3< float >::Get(), UE::Geometry::TDistLine3Triangle3< float >::Get(), UE::Geometry::TDistSegment2AxisAlignedBox2< float >::Get(), UE::Geometry::TDistSegment3Triangle3< float >::Get(), UE::Geometry::TDistTriangle3Triangle3< float >::Get(), UE::Geometry::Length(), UE::Geometry::TFibonacciLattice< RealType >::Point(), UE::Geometry::THemisphericalFibonacci< RealType >::Point(), UE::Geometry::TSphericalFibonacci< RealType >::Point(), UE::Geometry::TMeshLocalParam< PointSetType >::ProcessQueueUntilTermination(), UE::Geometry::TMeshLocalParam< PointSetType >::PropagateUV(), UE::Geometry::TCircle2< float >::SetArea(), UE::Geometry::TCircle3< float >::SetArea(), UE::Geometry::TCapsule3< float >::SignedDistance(), UE::Geometry::TImplicitLine3< float >::Value(), UE::Geometry::TSkeletalRicciNaryBlend3< InputBoundedImplicitType, RealType >::Value(), UE::Geometry::VectorUtil::VectorCot(), UE::Geometry::VectorUtil::VectorTanHalfAngle(), and UE::Geometry::VectorUtil::VectorTanHalfAngle().
Tan()
template<typename RealType> RealType TMathUtil< RealType >::Tan (const RealType Value) inline static
Definition at line 354 of file MathUtil.h.
References Value.
The documentation for this class was generated from the following file:
Runtime/GeometryCore/Public/MathUtil.h