Unreal Engine 5.6 C++ API: FHashBuilder Class Reference
FHashBuilder Class Reference
Class for computing a hash of multiple types, going through GetTypeHash when the type implements it, and fallbacks to raw data hashing when the type doesn't.
#include "HashBuilder.h"
Public Member Functions
FHashBuilder (uint32 InHash=0)
template<typename T>
FORCEINLINE FHashBuilder & Append (const T &InData)
template<typename T>
FORCEINLINE FHashBuilder & Append (const TArray< T > &InArray)
template<typename T, typename U>
FORCEINLINE FHashBuilder & Append (const TMap< T, U > &InMap)
template<typename T>
FORCEINLINE FHashBuilder & Append (const TSet< T > &InSet)
template<typename T>
FORCEINLINE TEnableIf< TIsPODType< T >::Value, FHashBuilder & >::Type AppendRaw (const T &InData)
FORCEINLINE FHashBuilder & AppendRaw (const void *Data, int64 Num)
FORCEINLINE uint32 GetHash () const
template<typename T>
FORCEINLINE FHashBuilder & operator<< (const T &InData)
Private Attributes
uint32 Hash
Detailed Description
Class for computing a hash of multiple types, going through GetTypeHash when the type implements it, and fallbacks to raw data hashing when the type doesn't.
Note: this hash builder should be used for transient hashes, as some types implements run-dependent hash computations, such as GetTypeHash(FName).
Definition at line 17 of file HashBuilder.h.
Constructor & Destructor Documentation
FHashBuilder()
FHashBuilder::FHashBuilder (uint32 InHash = 0) inline explicit
Definition at line 20 of file HashBuilder.h.
References Hash.
Referenced by Append(), Append(), Append(), Append(), AppendRaw(), AppendRaw(), and operator<<().
Member Function Documentation
Append() [1/4]
template<typename T> FORCEINLINE FHashBuilder & FHashBuilder::Append (const T & InData) inline
Definition at line 37 of file HashBuilder.h.
References FHashBuilder(), AppendRaw(), FORCEINLINE, GetTypeHash(), Hash, HashCombineFast(), and TModels_V.
Referenced by Append(), Append(), Append(), and operator<<().
Append() [2/4]
template<typename T> FORCEINLINE FHashBuilder & FHashBuilder::Append (const TArray< T > & InArray) inline
Definition at line 51 of file HashBuilder.h.
References FHashBuilder(), Append(), FORCEINLINE, and Value.
Append() [3/4]
template<typename T, typename U> FORCEINLINE FHashBuilder & FHashBuilder::Append (const TMap< T, U > & InMap) inline
Definition at line 71 of file HashBuilder.h.
References FHashBuilder(), Append(), FORCEINLINE, and Value.
Append() [4/4]
template<typename T> FORCEINLINE FHashBuilder & FHashBuilder::Append (const TSet< T > & InSet) inline
Definition at line 61 of file HashBuilder.h.
References FHashBuilder(), Append(), FORCEINLINE, and Value.
AppendRaw() [1/2]
template<typename T> FORCEINLINE TEnableIf< TIsPODType< T >::Value, FHashBuilder & >::Type FHashBuilder::AppendRaw (const T & InData) inline
Definition at line 31 of file HashBuilder.h.
References FHashBuilder(), AppendRaw(), and FORCEINLINE.
AppendRaw() [2/2]
FORCEINLINE FHashBuilder & FHashBuilder::AppendRaw (const void * Data, int64 Num) inline
Definition at line 24 of file HashBuilder.h.
References FHashBuilder(), CityHash64(), FORCEINLINE, GetTypeHash(), Hash, HashCombineFast(), and Num.
Referenced by Append(), and AppendRaw().
GetHash()
FORCEINLINE uint32 FHashBuilder::GetHash () const inline
Definition at line 87 of file HashBuilder.h.
References FORCEINLINE, and Hash.
operator<<()
template<typename T> FORCEINLINE FHashBuilder & FHashBuilder::operator<< (const T & InData) inline
Definition at line 82 of file HashBuilder.h.
References FHashBuilder(), Append(), and FORCEINLINE.
Field Documentation
Hash
uint32 FHashBuilder::Hash private
Definition at line 93 of file HashBuilder.h.
Referenced by FHashBuilder(), Append(), AppendRaw(), and GetHash().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Misc/HashBuilder.h