Unreal Engine 5.6 C++ API: ICookPackageSplitter Class Reference
ICookPackageSplitter Class Reference abstract
This class is used for packages that need to be split into multiple runtime packages.
#include "CookPackageSplitter.h"
Data Structures
struct FGeneratedPackage
Data sent to the cooker to describe each desired generated package.
struct FGeneratedPackageForPopulate
Representation of generated packages prepared by the cooker.
struct FPopulateContext
Context passed into Populate, PreSave, and PostSave functions, on the Generator package and on the Generated packages.
Public Types
enum class EGeneratedRequiresGenerator : uint8 { None , Populate , Save , Count }
Return value for the DoesGeneratedRequireGenerator function.
enum class ETeardown { Complete , Canceled }
Public Member Functions
virtual ~ICookPackageSplitter ()
virtual EGeneratedRequiresGenerator DoesGeneratedRequireGenerator ()
Return capability setting which indicates which splitter functions acting on the parent generator package must be called on the splitter before splitter functions acting on the generated packages can be called.
virtual TArray< FGeneratedPackage > GetGenerateList (const UPackage *OwnerPackage, const UObject *OwnerObject)=0
Return the list of packages to generate.
virtual void OnOwnerReloaded (UPackage *OwnerPackage, UObject *OwnerObject)
Called when the Owner package needs to be reloaded after a garbage collect in order to populate a generated package.
virtual bool PopulateGeneratedPackage (FPopulateContext &PopulateContext)
Try to populate a generated package.
virtual bool PopulateGeneratorPackage (FPopulateContext &PopulateContext)
Called before presaving the parent generator package, to give the generator a chance to inform the cooker which objects will be moved into the generator package that are not already present in it.
virtual void PostSaveGeneratedPackage (FPopulateContext &PopulateContext)
Called after saving a generated package.
virtual void PostSaveGeneratorPackage (FPopulateContext &PopulateContext)
Called after saving the parent generator package.
virtual bool PreSaveGeneratedPackage (FPopulateContext &PopulateContext)
Called before saving a generated package, after PopulateGeneratedPackage.
virtual bool PreSaveGeneratorPackage (FPopulateContext &PopulateContext)
Called before saving the parent generator package, after PopulateGeneratorPackage but before PopulateGeneratedPackage for any generated packages.
virtual bool RequiresGeneratorPackageDestructBeforeResplit ()
An ICookPackageSplitter for a single generator package normally is constructed only once and handles all generated packages for that generator, but during MPCook in cases of load balancing between CookWorkers, it is possible that the original splitter is destructed but then recreated later.
virtual void Teardown (ETeardown Status)
Do teardown actions after all packages have saved, or when the cook is cancelled.
UE_DEPRECATED (5.6, "Deprecation support, do not call outside of cooker code.") UNREALED_API void WarnIfDeprecatedVirtualNotCalled(const TCHAR *FunctionName)
UE_DEPRECATED (5.6, "Implement version that takes an FPopulateContext instead.") UNREALED_API virtual bool PopulateGeneratedPackage(UPackage *OwnerPackage
UE_DEPRECATED (5.6, "Implement version that takes an FPopulateContext instead.") UNREALED_API virtual bool PopulateGeneratorPackage(UPackage *OwnerPackage
UE_DEPRECATED (5.6, "Implement version that takes an FPopulateContext instead.") UNREALED_API virtual bool PreSaveGeneratedPackage(UPackage *OwnerPackage
UE_DEPRECATED (5.6, "Implement version that takes an FPopulateContext instead.") UNREALED_API virtual bool PreSaveGeneratorPackage(UPackage *OwnerPackage
UE_DEPRECATED (5.6, "Implement version that takes an FPopulateContext instead.") UNREALED_API virtual void PostSaveGeneratedPackage(UPackage *OwnerPackage
UE_DEPRECATED (5.6, "Implement version that takes an FPopulateContext instead.") UNREALED_API virtual void PostSaveGeneratorPackage(UPackage *OwnerPackage
UE_DEPRECATED (5.6, "Use FGeneratedPackageForPopulate instead.") typedef FGeneratedPackageForPopulate FGeneratedPackageForPreSave
virtual bool UseInternalReferenceToAvoidGarbageCollect ()
If true, this splitter forces the Generator package objects it needs to remain referenced, and the cooker should expect them to still be in memory after a garbage collect so long as the splitter is alive.
Static Public Member Functions
static UNREALED_API FString ConstructGeneratedPackageName (FName OwnerPackageName, FStringView RelPath, FStringView GeneratedRootOverride=FStringView())
Return the full packagename that will be used for a GeneratedPackage, based on the GeneratorPackage's name and on the RelPath and optional GeneratedRootPath that the splitter provides in the FGeneratedPackage it returns from GetGenerateList.
static UNREALED_API const TCHAR * GetGeneratedPackageSubPath ()
The name of the Generated subdirectory that is the parent directory of a splitter's generated packages.
static FString GetSplitterDebugName ()
Return DebugName for this SplitterClass in cook log messages.
static UNREALED_API bool IsUnderGeneratedPackageSubPath (FStringView FileOrLongPackagePath)
Return true if the given path is a Generated directory, or a subpath under it.
static bool RequiresCachedCookedPlatformDataBeforeSplit ()
Return whether IsCachedCookedPlatformDataLoaded needs to return true for all UObjects in the generator package before ShouldSplit or GetGenerateList can be called.
static bool ShouldSplit (UObject *SplitData)
Return whether the CookPackageSplitter subclass should handle the given SplitDataClass instance.
Data Fields
UObject const FGeneratedPackageForPopulate & GeneratedPackage
UObject const TArray< ICookPackageSplitter::FGeneratedPackageForPopulate > & GeneratedPackages
UObject const TArray< ICookPackageSplitter::FGeneratedPackageForPopulate > TArray< UObject * > TArray< UPackage * > & OutKeepReferencedPackages
UObject const TArray< FGeneratedPackageForPopulate > TArray< UPackage * > & OutKeepReferencedPackages
UObject const FGeneratedPackageForPopulate TArray< UObject * > TArray< UPackage * > & OutKeepReferencedPackages
UObject const FGeneratedPackageForPopulate TArray< UPackage * > & OutKeepReferencedPackages
UObject const TArray< ICookPackageSplitter::FGeneratedPackageForPopulate > TArray< UObject * > & OutObjectsToMove
UObject const FGeneratedPackageForPopulate TArray< UObject * > & OutObjectsToMove
UObject * OwnerObject
UObject const TArray< FGeneratedPackageForPopulate > & PlaceholderPackages
Private Member Functions
UE_DEPRECATED (5.6, "Deprecation support, do not read/write outside of cooker code.") bool bDeprecatedVirtualCalledAsExpected
Detailed Description
This class is used for packages that need to be split into multiple runtime packages.
It provides the instructions to the cooker for how to split the package.
Definition at line 37 of file CookPackageSplitter.h.
Member Enumeration Documentation
EGeneratedRequiresGenerator
enum class ICookPackageSplitter::EGeneratedRequiresGenerator : uint8 strong
Return value for the DoesGeneratedRequireGenerator function.
All levels behave correctly, but provide different tradeoffs of guarantees to the splitter versus performance.
Enumerator
None
GetGenerateList will be called before PopulateGeneratedPackage.
PopulateGenerator and PreSaveGenerator might or might not be called before. OutKeepReferencedPackages from PopulateGenerator will not be kept referenced after PostSaveGenerator. Best for performance.
Populate
GetGenerateList and PopulateGenerator will be called before PopulateGeneratedPackage.
OutKeepReferencedPackages from PopulateGenerator will be kept referenced until all generated and generator packages call PostSave or until the splitter is destroyed. Performance cost: Possible extra calls to PopulateGeneratedPackage, possible unnecessary memory increase due to OutKeepReferencedPackages.
Save
GetGenerateList PopulateGenerator, PreSaveGenerator, and PostSaveGenerator will be called before PopulateGeneratedPackage.
Performance cost: Progress on generated packages will be delayed until generator finishes saving. Possible unnecessary memory increase due to OutKeepReferencedPackages. Retraction is not possible in MPCook for the generated packages; they must all be saved on the same CookWorker that saves the generator.
Count
Definition at line 97 of file CookPackageSplitter.h.
ETeardown
enum class ICookPackageSplitter::ETeardown strong
Enumerator
Complete
Canceled
Definition at line 59 of file CookPackageSplitter.h.
Constructor & Destructor Documentation
~ICookPackageSplitter()
virtual ICookPackageSplitter::~ICookPackageSplitter () inline virtual
Definition at line 55 of file CookPackageSplitter.h.
Member Function Documentation
ConstructGeneratedPackageName()
UNREALED_API FString ICookPackageSplitter::ConstructGeneratedPackageName (FName OwnerPackageName, FStringView RelPath, FStringView GeneratedRootOverride = FStringView()) static
Return the full packagename that will be used for a GeneratedPackage, based on the GeneratorPackage's name and on the RelPath and optional GeneratedRootPath that the splitter provides in the FGeneratedPackage it returns from GetGenerateList.
DoesGeneratedRequireGenerator()
virtual EGeneratedRequiresGenerator ICookPackageSplitter::DoesGeneratedRequireGenerator () inline virtual
Return capability setting which indicates which splitter functions acting on the parent generator package must be called on the splitter before splitter functions acting on the generated packages can be called.
Also impacts the lifetime of memory guarantees for the generator functions.
See also
EGeneratedRequiresGenerator. Default is EGeneratedRequiresGenerator::None, which provides the best performance but the fewest guarantees.
Examples of dependencies and what capability level should be used: ShouldSplit call reads data that is written by BeginCacheForCookedPlatformData: EGeneratedRequiresGenerator::Save PopulateGeneratedPackage or PreSaveGeneratedPackage read data that is written by PopulateGeneratorPackage: EGeneratedRequiresGenerator::Populate
Definition at line 134 of file CookPackageSplitter.h.
References None.
GetGeneratedPackageSubPath()
UNREALED_API const TCHAR * ICookPackageSplitter::GetGeneratedPackageSubPath () static
The name of the Generated subdirectory that is the parent directory of a splitter's generated packages.
GetGenerateList()
virtual TArray< FGeneratedPackage > ICookPackageSplitter::GetGenerateList (const UPackage * OwnerPackage, const UObject * OwnerObject) pure virtual
Return the list of packages to generate.
References OwnerObject.
GetSplitterDebugName()
FString ICookPackageSplitter::GetSplitterDebugName () inline static
Return DebugName for this SplitterClass in cook log messages.
Definition at line 51 of file CookPackageSplitter.h.
References TEXT.
IsUnderGeneratedPackageSubPath()
UNREALED_API bool ICookPackageSplitter::IsUnderGeneratedPackageSubPath (FStringView FileOrLongPackagePath) static
Return true if the given path is a Generated directory, or a subpath under it.
OnOwnerReloaded()
virtual void ICookPackageSplitter::OnOwnerReloaded (UPackage * OwnerPackage, UObject * OwnerObject) inline virtual
Called when the Owner package needs to be reloaded after a garbage collect in order to populate a generated package.
Definition at line 344 of file CookPackageSplitter.h.
References OwnerObject.
PopulateGeneratedPackage()
virtual bool ICookPackageSplitter::PopulateGeneratedPackage (FPopulateContext & PopulateContext) inline virtual
Try to populate a generated package.
Receive an empty UPackage generated from an element in GetGenerateList and populate it. Return a list of all the objects that will be moved into the Generated package during its save, so the cooker can call BeginCacheForCookedPlatformData on them before the move After returning, the given package will be queued for saving into the TargetDomain
PopulateGeneratedPackage is guaranteed to not be called again on the same generated package until the splitter has been destroyed and the generator package has been garbage collected.
Returns
True if successfully populated, false on error (this will cause a cook error).
Definition at line 318 of file CookPackageSplitter.h.
Referenced by UE_DEPRECATED().
PopulateGeneratorPackage()
virtual bool ICookPackageSplitter::PopulateGeneratorPackage (FPopulateContext & PopulateContext) inline virtual
Called before presaving the parent generator package, to give the generator a chance to inform the cooker which objects will be moved into the generator package that are not already present in it.
PopulateGeneratorPackage is guaranteed to not be called again until the splitter has been destroyed and the generator package has been garbage collected.
Returns
True if successfully populated, false on error (this will cause a cook error).
Definition at line 281 of file CookPackageSplitter.h.
PostSaveGeneratedPackage()
virtual void ICookPackageSplitter::PostSaveGeneratedPackage (FPopulateContext & PopulateContext) inline virtual
Called after saving a generated package.
Undo any required adjustments to the parent package that were made in PreSaveGeneratedPackage, so that the parent package is once again ready for use in the editor or in future PreSaveGeneratedPackage calls.
Definition at line 339 of file CookPackageSplitter.h.
Referenced by UE_DEPRECATED().
PostSaveGeneratorPackage()
virtual void ICookPackageSplitter::PostSaveGeneratorPackage (FPopulateContext & PopulateContext) inline virtual
Called after saving the parent generator package.
Undo any required adjustments to the parent package that were made in PreSaveGeneratorPackage, so that the package is once again ready for use in the editor or in future GetGenerateList or PreSaveGeneratedPackage calls
Definition at line 301 of file CookPackageSplitter.h.
Referenced by UE_DEPRECATED().
PreSaveGeneratedPackage()
virtual bool ICookPackageSplitter::PreSaveGeneratedPackage (FPopulateContext & PopulateContext) inline virtual
Called before saving a generated package, after PopulateGeneratedPackage.
Make any required adjustments to the generated package before it is saved into the target domain.
Returns
True if successfully presaved, false on error (this will cause a cook error).
Definition at line 329 of file CookPackageSplitter.h.
Referenced by UE_DEPRECATED().
PreSaveGeneratorPackage()
virtual bool ICookPackageSplitter::PreSaveGeneratorPackage (FPopulateContext & PopulateContext) inline virtual
Called before saving the parent generator package, after PopulateGeneratorPackage but before PopulateGeneratedPackage for any generated packages.
Make any required adjustments to the parent package before it is saved into the target domain.
Returns
True if successfully presaved, false on error (this will cause a cook error).
Definition at line 291 of file CookPackageSplitter.h.
Referenced by UE_DEPRECATED().
RequiresCachedCookedPlatformDataBeforeSplit()
bool ICookPackageSplitter::RequiresCachedCookedPlatformDataBeforeSplit () inline static
Return whether IsCachedCookedPlatformDataLoaded needs to return true for all UObjects in the generator package before ShouldSplit or GetGenerateList can be called.
If true this slows down our ability to parallelize the cook of the generated packages.
Definition at line 47 of file CookPackageSplitter.h.
RequiresGeneratorPackageDestructBeforeResplit()
virtual bool ICookPackageSplitter::RequiresGeneratorPackageDestructBeforeResplit () inline virtual
An ICookPackageSplitter for a single generator package normally is constructed only once and handles all generated packages for that generator, but during MPCook in cases of load balancing between CookWorkers, it is possible that the original splitter is destructed but then recreated later.
This is guaranteed not to happen without a GarbageCollection pass in between, but that GarbageCollection may fail to destruct the generator package if it is still referenced from other packages or systems. Depending on the ICookPackageSplitter's implemenation, this failure to GC might cause an error, because changes made from the previous splitter are not handled in the next splitter. If RequiresGeneratorPackageDestructBeforeResplit is true, the cooker will log this failure to GC the generator package as an error.
Definition at line 88 of file CookPackageSplitter.h.
ShouldSplit()
bool ICookPackageSplitter::ShouldSplit (UObject * SplitData) inline static
Return whether the CookPackageSplitter subclass should handle the given SplitDataClass instance.
Definition at line 49 of file CookPackageSplitter.h.
Teardown()
virtual void ICookPackageSplitter::Teardown (ETeardown Status) inline virtual
Do teardown actions after all packages have saved, or when the cook is cancelled.
Always called before destruction.
Definition at line 65 of file CookPackageSplitter.h.
UE_DEPRECATED() [1/9]
ICookPackageSplitter::UE_DEPRECATED (5. 6, "Deprecation support, do not call outside of cooker code.") const
References UE_DEPRECATED().
UE_DEPRECATED() [2/9]
ICookPackageSplitter::UE_DEPRECATED (5. 6, "Deprecation support, do not read/write outside of cooker code.") private
References Private, and UE_DEPRECATED().
UE_DEPRECATED() [3/9]
ICookPackageSplitter::UE_DEPRECATED (5. 6, "Implement version that takes an FPopulateContext instead.")
References OwnerObject, PopulateGeneratedPackage(), and UE_DEPRECATED().
UE_DEPRECATED() [4/9]
ICookPackageSplitter::UE_DEPRECATED (5. 6, "Implement version that takes an FPopulateContext instead.")
References UE_DEPRECATED().
UE_DEPRECATED() [5/9]
ICookPackageSplitter::UE_DEPRECATED (5. 6, "Implement version that takes an FPopulateContext instead.")
References OwnerObject, PreSaveGeneratedPackage(), and UE_DEPRECATED().
UE_DEPRECATED() [6/9]
ICookPackageSplitter::UE_DEPRECATED (5. 6, "Implement version that takes an FPopulateContext instead.")
References OwnerObject, PreSaveGeneratorPackage(), and UE_DEPRECATED().
UE_DEPRECATED() [7/9]
ICookPackageSplitter::UE_DEPRECATED (5. 6, "Implement version that takes an FPopulateContext instead.")
References GeneratedPackage, OwnerObject, PostSaveGeneratedPackage(), and UE_DEPRECATED().
UE_DEPRECATED() [8/9]
ICookPackageSplitter::UE_DEPRECATED (5. 6, "Implement version that takes an FPopulateContext instead.")
References OwnerObject, PostSaveGeneratorPackage(), and UE_DEPRECATED().
UE_DEPRECATED() [9/9]
ICookPackageSplitter::UE_DEPRECATED (5. 6, "Use FGeneratedPackageForPopulate instead.")
Referenced by UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
UseInternalReferenceToAvoidGarbageCollect()
virtual bool ICookPackageSplitter::UseInternalReferenceToAvoidGarbageCollect () inline virtual
If true, this splitter forces the Generator package objects it needs to remain referenced, and the cooker should expect them to still be in memory after a garbage collect so long as the splitter is alive.
Definition at line 73 of file CookPackageSplitter.h.
Field Documentation
GeneratedPackage
UObject const FGeneratedPackageForPopulate & ICookPackageSplitter::GeneratedPackage
Definition at line 378 of file CookPackageSplitter.h.
Referenced by UE_DEPRECATED().
GeneratedPackages
UObject const TArray<ICookPackageSplitter::FGeneratedPackageForPopulate>& ICookPackageSplitter::GeneratedPackages
Definition at line 369 of file CookPackageSplitter.h.
OutKeepReferencedPackages [1/4]
UObject const TArray<ICookPackageSplitter::FGeneratedPackageForPopulate> TArray<UObject*> TArray<UPackage*>& ICookPackageSplitter::OutKeepReferencedPackages
Definition at line 370 of file CookPackageSplitter.h.
OutKeepReferencedPackages [2/4]
UObject const TArray<FGeneratedPackageForPopulate> TArray<UPackage*>& ICookPackageSplitter::OutKeepReferencedPackages
Definition at line 373 of file CookPackageSplitter.h.
OutKeepReferencedPackages [3/4]
UObject const FGeneratedPackageForPopulate TArray<UObject*> TArray<UPackage*>& ICookPackageSplitter::OutKeepReferencedPackages
Definition at line 379 of file CookPackageSplitter.h.
OutKeepReferencedPackages [4/4]
UObject const FGeneratedPackageForPopulate TArray<UPackage*>& ICookPackageSplitter::OutKeepReferencedPackages
Definition at line 382 of file CookPackageSplitter.h.
OutObjectsToMove [1/2]
UObject const TArray<ICookPackageSplitter::FGeneratedPackageForPopulate> TArray<UObject*>& ICookPackageSplitter::OutObjectsToMove
Definition at line 370 of file CookPackageSplitter.h.
OutObjectsToMove [2/2]
UObject const FGeneratedPackageForPopulate TArray<UObject*>& ICookPackageSplitter::OutObjectsToMove
Definition at line 378 of file CookPackageSplitter.h.
OwnerObject
UObject * ICookPackageSplitter::OwnerObject
Definition at line 368 of file CookPackageSplitter.h.
Referenced by GetGenerateList(), OnOwnerReloaded(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
PlaceholderPackages
UObject const TArray<FGeneratedPackageForPopulate>& ICookPackageSplitter::PlaceholderPackages
Definition at line 373 of file CookPackageSplitter.h.
The documentation for this class was generated from the following file:
Editor/UnrealEd/Public/CookPackageSplitter.h