Unreal Engine 5.6 C++ API: Metasound::TVertexInterfaceImpl< VertexType > Class Template Reference
Metasound::TVertexInterfaceImpl< VertexType > Class Template Reference
TVertexInterfaceImpls encapsulates multiple related data vertices.
#include "MetasoundVertex.h"
Public Types
using RangedForConstIteratorType = typename TArray<VertexType>::RangedForConstIteratorType
Public Member Functions
TVertexInterfaceImpl ()=default
TVertexInterfaceImpl (TArray< VertexType > InVertices)
Construct with prebuilt array of vertices.
void Add (const VertexType &InVertex)
Add a vertex to the group.
void Add (VertexType &&InVertex)
void Append (TArrayView< const VertexType > InVertices)
VertexType & At (int32 InIndex)
Return a vertex at an index.
const VertexType & At (int32 InIndex) const
Return a vertex at an index.
RangedForConstIteratorType begin () const
Iterator for ranged for loops.
bool Contains (const FVertexName &InKey) const
Returns true if the group contains a vertex with a matching key.
RangedForConstIteratorType end () const
Iterator for ranged for loops.
VertexType * Find (const FVertexName &InKey)
Find a vertex with a given VertexName.
const VertexType * Find (const FVertexName &InKey) const
Find a vertex with a given VertexName.
int32 GetSortOrderIndex (const FVertexName &InKey) const
Return the sort order index of a vertex with the given name.
int32 Num () const
Returns the number of vertices in the group.
const VertexType & operator[] (const FVertexName &InName) const
Return the vertex for a given vertex key.
bool Remove (const FVertexName &InKey)
Remove a vertex by key.
template<typename... VertexTypes>
UE_DEPRECATED (5.6, "Use the constructors of derived classes instead (FInputVertexInterface, FOutputVertexInterface, etc).") explicit TVertexInterfaceImpl(VertexTypes &&... InVertices)
TVertexInterfaceImpl constructor with variadic list of vertex models.
Protected Attributes
TArray< VertexType > Vertices
Private Types
using FEqualVertexName = VertexPrivate::TEqualVertexName<VertexType>
Private Member Functions
void AddOrUpdateVertex (VertexType &&InVertex)
Friends
bool operator!= (const TVertexInterfaceImpl< VertexType > &InLHS, const TVertexInterfaceImpl< VertexType > &InRHS)
Compare whether two vertex groups are unequal.
bool operator== (const TVertexInterfaceImpl< VertexType > &InLHS, const TVertexInterfaceImpl< VertexType > &InRHS)
Compare whether two vertex groups are equal.
Detailed Description
template<typename VertexType>
class Metasound::TVertexInterfaceImpl< VertexType >
TVertexInterfaceImpls encapsulates multiple related data vertices.
It requires that each vertex in the group have a unique FVertexName.
Definition at line 298 of file MetasoundVertex.h.
Member Typedef Documentation
FEqualVertexName
template<typename VertexType> using Metasound::TVertexInterfaceImpl< VertexType >::FEqualVertexName = VertexPrivate::TEqualVertexName<VertexType> private
Definition at line 300 of file MetasoundVertex.h.
RangedForConstIteratorType
template<typename VertexType> using Metasound::TVertexInterfaceImpl< VertexType >::RangedForConstIteratorType = typename TArray<VertexType>::RangedForConstIteratorType
Definition at line 315 of file MetasoundVertex.h.
Constructor & Destructor Documentation
TVertexInterfaceImpl() [1/2]
template<typename VertexType> Metasound::TVertexInterfaceImpl< VertexType >::TVertexInterfaceImpl () default
Referenced by operator!=, operator==, and UE_DEPRECATED().
TVertexInterfaceImpl() [2/2]
template<typename VertexType> Metasound::TVertexInterfaceImpl< VertexType >::TVertexInterfaceImpl (TArray< VertexType > InVertices) inline explicit
Construct with prebuilt array of vertices.
Definition at line 320 of file MetasoundVertex.h.
References MoveTemp(), and Vertices.
Member Function Documentation
Add() [1/2]
template<typename VertexType> void Metasound::TVertexInterfaceImpl< VertexType >::Add (const VertexType & InVertex) inline
Add a vertex to the group.
Definition at line 345 of file MetasoundVertex.h.
References AddOrUpdateVertex().
Add() [2/2]
template<typename VertexType> void Metasound::TVertexInterfaceImpl< VertexType >::Add (VertexType && InVertex) inline
Definition at line 350 of file MetasoundVertex.h.
References AddOrUpdateVertex(), and MoveTemp().
AddOrUpdateVertex()
template<typename VertexType> void Metasound::TVertexInterfaceImpl< VertexType >::AddOrUpdateVertex (VertexType && InVertex) inline private
Definition at line 302 of file MetasoundVertex.h.
References Find, MoveTemp(), Vertex, and Vertices.
Referenced by Add(), Add(), and UE_DEPRECATED().
Append()
template<typename VertexType> void Metasound::TVertexInterfaceImpl< VertexType >::Append (TArrayView< const VertexType > InVertices) inline
Definition at line 355 of file MetasoundVertex.h.
References Add, and Vertex.
At() [1/2]
template<typename VertexType> VertexType & Metasound::TVertexInterfaceImpl< VertexType >::At (int32 InIndex) inline
Return a vertex at an index.
Definition at line 432 of file MetasoundVertex.h.
References Vertices.
At() [2/2]
template<typename VertexType> const VertexType & Metasound::TVertexInterfaceImpl< VertexType >::At (int32 InIndex) const inline
Return a vertex at an index.
Definition at line 426 of file MetasoundVertex.h.
References Vertices.
begin()
template<typename VertexType> RangedForConstIteratorType Metasound::TVertexInterfaceImpl< VertexType >::begin () const inline
Iterator for ranged for loops.
Definition at line 408 of file MetasoundVertex.h.
References Vertices.
Contains()
template<typename VertexType> bool Metasound::TVertexInterfaceImpl< VertexType >::Contains (const FVertexName & InKey) const inline
Returns true if the group contains a vertex with a matching key.
Definition at line 371 of file MetasoundVertex.h.
References Vertices.
Referenced by Metasound::FDataReferenceCollection::GetDataReadReferenceOrConstructWithVertexDefault().
end()
template<typename VertexType> RangedForConstIteratorType Metasound::TVertexInterfaceImpl< VertexType >::end () const inline
Iterator for ranged for loops.
Definition at line 414 of file MetasoundVertex.h.
References Vertices.
Find() [1/2]
template<typename VertexType> VertexType * Metasound::TVertexInterfaceImpl< VertexType >::Find (const FVertexName & InKey) inline
Find a vertex with a given VertexName.
Definition at line 377 of file MetasoundVertex.h.
References Vertices.
Find() [2/2]
template<typename VertexType> const VertexType * Metasound::TVertexInterfaceImpl< VertexType >::Find (const FVertexName & InKey) const inline
Find a vertex with a given VertexName.
Definition at line 383 of file MetasoundVertex.h.
References Vertices.
GetSortOrderIndex()
template<typename VertexType> int32 Metasound::TVertexInterfaceImpl< VertexType >::GetSortOrderIndex (const FVertexName & InKey) const inline
Return the sort order index of a vertex with the given name.
Parameters
InKey - FVertexName of vertex of interest.
Returns
The index of the vertex. INDEX_NONE if the vertex does not exist.
Definition at line 394 of file MetasoundVertex.h.
References Vertices.
Num()
template<typename VertexType> int32 Metasound::TVertexInterfaceImpl< VertexType >::Num () const inline
Returns the number of vertices in the group.
Definition at line 420 of file MetasoundVertex.h.
References Vertices.
operator[]()
template<typename VertexType> const VertexType & Metasound::TVertexInterfaceImpl< VertexType >::operator[] (const FVertexName & InName) const inline
Return the vertex for a given vertex key.
Definition at line 400 of file MetasoundVertex.h.
References checkf, Find, InName, TEXT, and Vertex.
Remove()
template<typename VertexType> bool Metasound::TVertexInterfaceImpl< VertexType >::Remove (const FVertexName & InKey) inline
Remove a vertex by key.
Definition at line 364 of file MetasoundVertex.h.
References Vertices.
UE_DEPRECATED()
template<typename VertexType> template<typename... VertexTypes> Metasound::TVertexInterfaceImpl< VertexType >::UE_DEPRECATED (5. 6, "Use the constructors of derived classes instead (FInputVertexInterface, FOutputVertexInterface, etc).") && inline
TVertexInterfaceImpl constructor with variadic list of vertex models.
Definition at line 329 of file MetasoundVertex.h.
References TVertexInterfaceImpl(), AddOrUpdateVertex(), Forward(), and Vertices.
Friends And Related Symbol Documentation
operator!=
template<typename VertexType> bool operator!= (const TVertexInterfaceImpl< VertexType > & InLHS, const TVertexInterfaceImpl< VertexType > & InRHS) friend
Compare whether two vertex groups are unequal.
Definition at line 444 of file MetasoundVertex.h.
References TVertexInterfaceImpl().
operator==
template<typename VertexType> bool operator== (const TVertexInterfaceImpl< VertexType > & InLHS, const TVertexInterfaceImpl< VertexType > & InRHS) friend
Compare whether two vertex groups are equal.
Definition at line 438 of file MetasoundVertex.h.
References TVertexInterfaceImpl(), and Vertices.
Field Documentation
Vertices
template<typename VertexType> TArray<VertexType> Metasound::TVertexInterfaceImpl< VertexType >::Vertices protected
Definition at line 451 of file MetasoundVertex.h.
Referenced by TVertexInterfaceImpl(), AddOrUpdateVertex(), At(), At(), begin(), Contains(), end(), Find(), Find(), GetSortOrderIndex(), Num(), operator==, Remove(), and UE_DEPRECATED().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/Metasound/Source/MetasoundGraphCore/Public/MetasoundVertex.h