Unreal Engine 5.6 C++ API: FCanvasTriangleRendererItem Class Reference
FCanvasTriangleRendererItem Class Reference
Info needed to render a single FTriangleRenderer.
#include "CanvasRendererItem.h"
Data Structures
class FRenderData
class FTriangleVertexFactory
Public Member Functions
FCanvasTriangleRendererItem (ERHIFeatureLevel::Type InFeatureLevel, const FMaterialRenderProxy *InMaterialRenderProxy=NULL, const FCanvas::FTransformEntry &InTransform=FCanvas::FTransformEntry(FMatrix::Identity), bool bInFreezeTime=false)
Init constructor.
void AddReserveTriangles (int32 NumTriangles)
Reserves space in array for NumTriangles new triangles.
int32 AddTriangle (const FCanvasUVTri &Tri, FHitProxyId HitProxyId)
Add a new triangle to the render data.
virtual class FCanvasTriangleRendererItem * GetCanvasTriangleRendererItem () override
FCanvasTriangleRendererItem instance accessor.
bool IsMatch (const FMaterialRenderProxy *InMaterialRenderProxy, const FCanvas::FTransformEntry &InTransform)
Determine if this is a matching set by comparing material,transform.
virtual bool Render_GameThread (const FCanvas *Canvas, FCanvasRenderThreadScope &RenderScope) override
Renders the canvas item.
virtual bool Render_RenderThread (FCanvasRenderContext &RenderContext, FMeshPassProcessorRenderState &DrawRenderState, const FCanvas *Canvas) override
Renders the canvas item.
void ReserveTriangles (int32 NumTriangles)
Reserves space in array for at least NumTriangles total triangles.
Public Member Functions inherited from FCanvasBaseRenderItem
virtual ~FCanvasBaseRenderItem ()
virtual class FCanvasBatchedElementRenderItem * GetCanvasBatchedElementRenderItem ()
FCanvasBatchedElementRenderItem instance accessor.
virtual class FCanvasTileRendererItem * GetCanvasTileRendererItem ()
FCanvasTileRendererItem instance accessor.
Private Attributes
const bool bFreezeTime
TSharedPtr< FRenderData > Data
Render data which is allocated when a new FCanvasTriangleRendererItem is added for rendering.
Detailed Description
Info needed to render a single FTriangleRenderer.
Definition at line 160 of file CanvasRendererItem.h.
Constructor & Destructor Documentation
FCanvasTriangleRendererItem()
FCanvasTriangleRendererItem::FCanvasTriangleRendererItem (ERHIFeatureLevel::Type InFeatureLevel, const FMaterialRenderProxy * InMaterialRenderProxy = NULL, const FCanvas::FTransformEntry & InTransform = FCanvas::FTransformEntry(FMatrix::Identity), bool bInFreezeTime = false) inline
Init constructor.
Definition at line 166 of file CanvasRendererItem.h.
References bFreezeTime, Data, UE::Math::TMatrix< double >::Identity, and MakeShared().
Referenced by GetCanvasTriangleRendererItem().
Member Function Documentation
AddReserveTriangles()
void FCanvasTriangleRendererItem::AddReserveTriangles (int32 NumTriangles) inline
Reserves space in array for NumTriangles new triangles.
Parameters
NumTriangles Additional number of triangles to reserve space for.
Definition at line 232 of file CanvasRendererItem.h.
References Data, and FORCEINLINE.
AddTriangle()
int32 FCanvasTriangleRendererItem::AddTriangle (const FCanvasUVTri & Tri, FHitProxyId HitProxyId) inline
Add a new triangle to the render data.
These triangles all use the same transform and material proxy
Parameters
return number of triangles added
Definition at line 222 of file CanvasRendererItem.h.
References Data, and FORCEINLINE.
GetCanvasTriangleRendererItem()
virtual class FCanvasTriangleRendererItem * FCanvasTriangleRendererItem::GetCanvasTriangleRendererItem () inline override virtual
FCanvasTriangleRendererItem instance accessor.
Returns
this instance
Reimplemented from FCanvasBaseRenderItem.
Definition at line 180 of file CanvasRendererItem.h.
References FCanvasTriangleRendererItem().
IsMatch()
bool FCanvasTriangleRendererItem::IsMatch (const FMaterialRenderProxy * InMaterialRenderProxy, const FCanvas::FTransformEntry & InTransform) inline
Determine if this is a matching set by comparing material,transform.
All must match
Parameters
IInMaterialRenderProxy - material proxy resource for the item being rendered
InTransform - the transform for the item being rendered
Returns
true if the parameters match this render item
Definition at line 211 of file CanvasRendererItem.h.
References Data, and FCanvas::FTransformEntry::GetMatrixCRC().
Render_GameThread()
virtual bool FCanvasTriangleRendererItem::Render_GameThread (const FCanvas * Canvas, FCanvasRenderThreadScope & RenderScope) override virtual
Renders the canvas item.
Iterates over each triangle to be rendered and draws it with its own transforms
Parameters
Canvas - canvas currently being rendered
Returns
true if anything rendered
Implements FCanvasBaseRenderItem.
Render_RenderThread()
virtual bool FCanvasTriangleRendererItem::Render_RenderThread (FCanvasRenderContext & RenderContext, FMeshPassProcessorRenderState & DrawRenderState, const FCanvas * Canvas) override virtual
Renders the canvas item.
Iterates over each triangle to be rendered and draws it with its own transforms
Parameters
Canvas - canvas currently being rendered
RHICmdList - command list to use
Returns
true if anything rendered
Implements FCanvasBaseRenderItem.
ReserveTriangles()
void FCanvasTriangleRendererItem::ReserveTriangles (int32 NumTriangles) inline
Reserves space in array for at least NumTriangles total triangles.
Parameters
NumTriangles Additional number of triangles to reserve space for.
Definition at line 242 of file CanvasRendererItem.h.
References Data, and FORCEINLINE.
Field Documentation
bFreezeTime
const bool FCanvasTriangleRendererItem::bFreezeTime private
Definition at line 322 of file CanvasRendererItem.h.
Referenced by FCanvasTriangleRendererItem().
Data
TSharedPtr<FRenderData> FCanvasTriangleRendererItem::Data private
Render data which is allocated when a new FCanvasTriangleRendererItem is added for rendering.
This data is only freed on the rendering thread once the item has finished rendering
Definition at line 320 of file CanvasRendererItem.h.
Referenced by FCanvasTriangleRendererItem(), AddReserveTriangles(), AddTriangle(), IsMatch(), and ReserveTriangles().
The documentation for this class was generated from the following file:
Runtime/Engine/Public/CanvasRendererItem.h