Unreal Engine 5.6 C++ API: Metasound::DynamicGraph::FDynamicOperatorTransactor Class Reference
Metasound::DynamicGraph::FDynamicOperatorTransactor Class Reference
The FDynamicOperatorTransactor is used for communicating with a dynamic MetaSound operator.
#include "MetasoundDynamicOperatorTransactor.h"
Data Structures
struct FDynamicOperatorInfo
struct FLiteralNodeID
Public Member Functions
METASOUNDGRAPHCORE_API FDynamicOperatorTransactor ()
FDynamicOperatorTransactor (const FDynamicOperatorTransactor &)=delete
METASOUNDGRAPHCORE_API FDynamicOperatorTransactor (const FGraph &InGraph)
METASOUNDGRAPHCORE_API void AddDataEdge (const FGuid &InFromNodeID, const FVertexName &InFromVertex, const FGuid &InToNodeID, const FVertexName &InToVertex)
Add an edge to the graph, connecting two vertices from two nodes.
METASOUNDGRAPHCORE_API void AddInputDataDestination (const FGuid &InNode, const FVertexName &InVertexName, const FLiteral &InDefaultLiteral, FReferenceCreationFunction InFunc)
Add an input data destination to describe how data provided outside this graph should be routed internally.
METASOUNDGRAPHCORE_API void AddNode (const FGuid &InNodeID, TUniquePtr< INode > InNode)
Add a node to the graph.
METASOUNDGRAPHCORE_API void AddOutputDataSource (const FGuid &InNode, const FVertexName &InVertexName)
Add an output data source which describes routing of data which is owned this graph and exposed externally.
METASOUNDGRAPHCORE_API TSharedRef< TSpscQueue< TUniquePtr< IDynamicOperatorTransform > > > CreateTransformQueue (const FOperatorSettings &InOperatorSettings, const FMetasoundEnvironment &InEnvironment, const TSharedPtr< FGraphRenderCost > &InRenderCost)
METASOUNDGRAPHCORE_API const FGraph & GetGraph () const
Return internal version of graph.
FDynamicOperatorTransactor & operator= (const FDynamicOperatorTransactor &)=delete
METASOUNDGRAPHCORE_API void RemoveDataEdge (const FGuid &InFromNode, const FVertexName &InFromVertexName, const FGuid &InToNode, const FVertexName &InToVertexName, FLiteral InReplacementLiteral, const FReferenceCreationFunction InReferenceCreateFunc)
Remove the given data edge.
METASOUNDGRAPHCORE_API void RemoveInputDataDestination (const FVertexName &InVertexName)
Remove an exposed input from the graph.
METASOUNDGRAPHCORE_API void RemoveNode (const FGuid &InNodeID)
Remove a node from the graph.
METASOUNDGRAPHCORE_API void RemoveOutputDataSource (const FVertexName &InVertexName)
Remove an exposed output from the graph.
METASOUNDGRAPHCORE_API void SetValue (const FGuid &InNodeID, const FVertexName &InVertexName, const FLiteral &InLiteral, const FReferenceCreationFunction InReferenceCreateFunc)
Set the value on a unconnected node input vertex.
UE_DEPRECATED (5.5, "Replace with CreateTransformQueue overload including FGraphRenderCost") METASOUNDGRAPHCORE_API TSharedRef< TSpscQueue< TUniquePtr< IDynamicOperatorTransform > > > CreateTransformQueue(const FOperatorSettings &InOperatorSettings
Create a queue for communication with a dynamic operator.
UE_DEPRECATED (5.6, "Literal nodes will no longer be supported. Use RemoveDataEdge with an FLiteral instead.") METASOUNDGRAPHCORE_API void RemoveDataEdge(const FGuid &InFromNode
UE_DEPRECATED (5.6, "Setting values using a literal node will no longer be supported. Set literal on the vertex interface instead.") METASOUNDGRAPHCORE_API void SetValue(const FGuid &InNodeID
Data Fields
const FMetasoundEnvironment & InEnvironment
const FVertexName & InFromVertexName
const FVertexName TUniquePtr< INode > InLiteralNode
const FVertexName const FGuid const FVertexName TUniquePtr< INode > InReplacementLiteralNode
const FVertexName const FGuid & InToNode
const FVertexName const FGuid const FVertexName & InToVertexName
const FVertexName & InVertexName
Private Types
using FCreateTransformFunctionRef = TFunctionRef<TUniquePtr<IDynamicOperatorTransform>(const FDynamicOperatorInfo& InOperatorInfo)>
Private Member Functions
METASOUNDGRAPHCORE_API void AddDataEdgeInternal (const INode &InFromNode, const FVertexName &InFromVertex, const FGuid &InToNodeID, const INode &InToNode, const FVertexName &InToVertex)
METASOUNDGRAPHCORE_API TUniquePtr< IDynamicOperatorTransform > CreateInsertOperatorTransform (const INode &InNode, int32 InOrdinal, const FOperatorSettings &InOperatorSettings, const FMetasoundEnvironment &InEnvironment, FGraphRenderCost *InGraphRenderCost) const
METASOUNDGRAPHCORE_API void EnqueueAddEdgeOperatorTransform (const INode &InFromNode, const FVertexName &InFromVertex, const INode &InToNode, const FVertexName &InToVertex, const TArray< FOrdinalSwap > &InOrdinalUpdates)
METASOUNDGRAPHCORE_API void EnqueueBeginFadeOperatorTransform (const INode &InNode, EAudioFadeType InFadeType, TArrayView< const FVertexName > InInputsToFade, TArrayView< const FVertexName > InOutputsToFade)
METASOUNDGRAPHCORE_API void EnqueueEndFadeOperatorTransform (const INode &InNode)
METASOUNDGRAPHCORE_API void EnqueueFadeAndAddEdgeOperatorTransform (const INode &InFromNode, const FVertexName &InFromVertex, const INode &InToNode, const FVertexName &InToVertex, const TArray< FOrdinalSwap > &InOrdinalUpdates)
METASOUNDGRAPHCORE_API void EnqueueFadeAndRemoveEdgeOperatorTransform (const INode &InFromNode, const FVertexName &InFromVertexName, const INode &InToNode, const FVertexName &InToVertexName, const FLiteral &InReplacementLiteral, const FReferenceCreationFunction InReferenceCreateFunc)
METASOUNDGRAPHCORE_API void EnqueueFadeAndRemoveEdgeOperatorTransform_Deprecated (const INode &InFromNode, const FVertexName &InFromVertexName, const INode &InToNode, const FVertexName &InToVertexName, const INode &InReplacementLiteralNode, int32 InLiteralOrdinal)
METASOUNDGRAPHCORE_API void EnqueueInsertOperatorTransform (const INode &InNode, int32 InOrdinal)
METASOUNDGRAPHCORE_API void EnqueueRemoveEdgeOperatorTransform (const INode &InFromNode, const FVertexName &InFromVertexName, const INode &InToNode, const FVertexName &InToVertexName, const FLiteral &InReplacementLiteral, const FReferenceCreationFunction InReferenceCreateFunc)
METASOUNDGRAPHCORE_API void EnqueueRemoveEdgeOperatorTransform_Deprecated (const INode &InFromNode, const FVertexName &InFromVertexName, const INode &InToNode, const FVertexName &InToVertexName, const INode &InReplacementLiteralNode, int32 InLiteralOrdinal)
METASOUNDGRAPHCORE_API void EnqueueRemoveOperatorTransform (const INode &InNode, const TArray< FOperatorID > &InOperatorsConnectedToInput)
METASOUNDGRAPHCORE_API void EnqueueTransformOnOperatorQueues (FCreateTransformFunctionRef InFunc)
METASOUNDGRAPHCORE_API void FadeAndRemoveNodeInternal (const INode &InNode, TArrayView< const FVertexName > InOutputsToFade, bool bInRemoveDataEdgesWithNode)
METASOUNDGRAPHCORE_API void RemoveNodeInternal (const INode &InNode, bool bInRemoveDataEdgesWithNode)
Private Attributes
FGraph Graph
FDynamicGraphIncrementalSorter GraphSorter
TSortedMap< FLiteralNodeID, TUniquePtr< INode > > LiteralNodeMap
FOperatorBuilder OperatorBuilder
TArray< FDynamicOperatorInfo > OperatorInfos
Friends
class Debug::FDynamicOperatorDebugger
bool operator< (const FLiteralNodeID &InLHS, const FLiteralNodeID &InRHS)
Detailed Description
The FDynamicOperatorTransactor is used for communicating with a dynamic MetaSound operator.
Graph manipulations performed on the transactor are forwarded to dynamic operators using the transform queue. Each modification is converted into IDynamicOperatorTransforms which are consumed by dynamic operators during their execution.
Definition at line 183 of file MetasoundDynamicOperatorTransactor.h.
Member Typedef Documentation
FCreateTransformFunctionRef
using Metasound::DynamicGraph::FDynamicOperatorTransactor::FCreateTransformFunctionRef = TFunctionRef<TUniquePtr<IDynamicOperatorTransform>(const FDynamicOperatorInfo& InOperatorInfo)> private
Definition at line 281 of file MetasoundDynamicOperatorTransactor.h.
Constructor & Destructor Documentation
FDynamicOperatorTransactor() [1/3]
Metasound::DynamicGraph::FDynamicOperatorTransactor::FDynamicOperatorTransactor (const FDynamicOperatorTransactor &) delete
References FDynamicOperatorTransactor().
Referenced by FDynamicOperatorTransactor(), and operator=().
FDynamicOperatorTransactor() [2/3]
METASOUNDGRAPHCORE_API Metasound::DynamicGraph::FDynamicOperatorTransactor::FDynamicOperatorTransactor ()
References UE_API.
FDynamicOperatorTransactor() [3/3]
METASOUNDGRAPHCORE_API Metasound::DynamicGraph::FDynamicOperatorTransactor::FDynamicOperatorTransactor (const FGraph & InGraph)
References UE_API.
Member Function Documentation
AddDataEdge()
METASOUNDGRAPHCORE_API void Metasound::DynamicGraph::FDynamicOperatorTransactor::AddDataEdge (const FGuid & InFromNodeID, const FVertexName & InFromVertex, const FGuid & InToNodeID, const FVertexName & InToVertex)
Add an edge to the graph, connecting two vertices from two nodes.
Parameters
FromNode - Node which contains the output vertex.
FromVertex - Key of the vertex in the FromNode.
ToNode - Node which contains the input vertex.
ToVertex - Key of the vertex in the ToNode.
References AddDataEdge(), and UE_API.
Referenced by AddDataEdge().
AddDataEdgeInternal()
METASOUNDGRAPHCORE_API void Metasound::DynamicGraph::FDynamicOperatorTransactor::AddDataEdgeInternal (const INode & InFromNode, const FVertexName & InFromVertex, const FGuid & InToNodeID, const INode & InToNode, const FVertexName & InToVertex) private
References AddDataEdgeInternal(), InToNode, and UE_API.
Referenced by AddDataEdgeInternal().
AddInputDataDestination()
METASOUNDGRAPHCORE_API void Metasound::DynamicGraph::FDynamicOperatorTransactor::AddInputDataDestination (const FGuid & InNode, const FVertexName & InVertexName, const FLiteral & InDefaultLiteral, FReferenceCreationFunction InFunc)
Add an input data destination to describe how data provided outside this graph should be routed internally.
Parameters
InNode - Node which receives the data.
InVertexName - Key for input vertex on InNode.
References AddInputDataDestination(), InVertexName, and UE_API.
Referenced by AddInputDataDestination().
AddNode()
METASOUNDGRAPHCORE_API void Metasound::DynamicGraph::FDynamicOperatorTransactor::AddNode (const FGuid & InNodeID, TUniquePtr< INode > InNode)
Add a node to the graph.
References AddNode(), and UE_API.
Referenced by AddNode().
AddOutputDataSource()
METASOUNDGRAPHCORE_API void Metasound::DynamicGraph::FDynamicOperatorTransactor::AddOutputDataSource (const FGuid & InNode, const FVertexName & InVertexName)
Add an output data source which describes routing of data which is owned this graph and exposed externally.
Parameters
InNode - Node which produces the data.
InVertexName - Key for output vertex on InNode.
References AddOutputDataSource(), InVertexName, and UE_API.
Referenced by AddOutputDataSource().
CreateInsertOperatorTransform()
METASOUNDGRAPHCORE_API TUniquePtr< IDynamicOperatorTransform > Metasound::DynamicGraph::FDynamicOperatorTransactor::CreateInsertOperatorTransform (const INode & InNode, int32 InOrdinal, const FOperatorSettings & InOperatorSettings, const FMetasoundEnvironment & InEnvironment, FGraphRenderCost * InGraphRenderCost) const private
References InEnvironment, and UE_API.
CreateTransformQueue()
METASOUNDGRAPHCORE_API TSharedRef< TSpscQueue< TUniquePtr< IDynamicOperatorTransform > > > Metasound::DynamicGraph::FDynamicOperatorTransactor::CreateTransformQueue (const FOperatorSettings & InOperatorSettings, const FMetasoundEnvironment & InEnvironment, const TSharedPtr< FGraphRenderCost > & InRenderCost)
References CreateTransformQueue(), InEnvironment, and UE_API.
Referenced by CreateTransformQueue().
EnqueueAddEdgeOperatorTransform()
METASOUNDGRAPHCORE_API void Metasound::DynamicGraph::FDynamicOperatorTransactor::EnqueueAddEdgeOperatorTransform (const INode & InFromNode, const FVertexName & InFromVertex, const INode & InToNode, const FVertexName & InToVertex, const TArray< FOrdinalSwap > & InOrdinalUpdates) private
References EnqueueAddEdgeOperatorTransform(), InToNode, and UE_API.
Referenced by EnqueueAddEdgeOperatorTransform().
EnqueueBeginFadeOperatorTransform()
METASOUNDGRAPHCORE_API void Metasound::DynamicGraph::FDynamicOperatorTransactor::EnqueueBeginFadeOperatorTransform (const INode & InNode, EAudioFadeType InFadeType, TArrayView< const FVertexName > InInputsToFade, TArrayView< const FVertexName > InOutputsToFade) private
References EnqueueBeginFadeOperatorTransform(), and UE_API.
Referenced by EnqueueBeginFadeOperatorTransform().
EnqueueEndFadeOperatorTransform()
METASOUNDGRAPHCORE_API void Metasound::DynamicGraph::FDynamicOperatorTransactor::EnqueueEndFadeOperatorTransform (const INode & InNode) private
References EnqueueEndFadeOperatorTransform(), and UE_API.
Referenced by EnqueueEndFadeOperatorTransform().
EnqueueFadeAndAddEdgeOperatorTransform()
METASOUNDGRAPHCORE_API void Metasound::DynamicGraph::FDynamicOperatorTransactor::EnqueueFadeAndAddEdgeOperatorTransform (const INode & InFromNode, const FVertexName & InFromVertex, const INode & InToNode, const FVertexName & InToVertex, const TArray< FOrdinalSwap > & InOrdinalUpdates) private
References EnqueueFadeAndAddEdgeOperatorTransform(), InToNode, and UE_API.
Referenced by EnqueueFadeAndAddEdgeOperatorTransform().
EnqueueFadeAndRemoveEdgeOperatorTransform()
METASOUNDGRAPHCORE_API void Metasound::DynamicGraph::FDynamicOperatorTransactor::EnqueueFadeAndRemoveEdgeOperatorTransform (const INode & InFromNode, const FVertexName & InFromVertexName, const INode & InToNode, const FVertexName & InToVertexName, const FLiteral & InReplacementLiteral, const FReferenceCreationFunction InReferenceCreateFunc) private
References EnqueueFadeAndRemoveEdgeOperatorTransform(), InFromVertexName, InToNode, InToVertexName, and UE_API.
Referenced by EnqueueFadeAndRemoveEdgeOperatorTransform().
EnqueueFadeAndRemoveEdgeOperatorTransform_Deprecated()
METASOUNDGRAPHCORE_API void Metasound::DynamicGraph::FDynamicOperatorTransactor::EnqueueFadeAndRemoveEdgeOperatorTransform_Deprecated (const INode & InFromNode, const FVertexName & InFromVertexName, const INode & InToNode, const FVertexName & InToVertexName, const INode & InReplacementLiteralNode, int32 InLiteralOrdinal) private
References EnqueueFadeAndRemoveEdgeOperatorTransform_Deprecated(), InFromVertexName, InReplacementLiteralNode, InToNode, InToVertexName, and UE_API.
Referenced by EnqueueFadeAndRemoveEdgeOperatorTransform_Deprecated().
EnqueueInsertOperatorTransform()
METASOUNDGRAPHCORE_API void Metasound::DynamicGraph::FDynamicOperatorTransactor::EnqueueInsertOperatorTransform (const INode & InNode, int32 InOrdinal) private
References EnqueueInsertOperatorTransform(), and UE_API.
Referenced by EnqueueInsertOperatorTransform().
EnqueueRemoveEdgeOperatorTransform()
METASOUNDGRAPHCORE_API void Metasound::DynamicGraph::FDynamicOperatorTransactor::EnqueueRemoveEdgeOperatorTransform (const INode & InFromNode, const FVertexName & InFromVertexName, const INode & InToNode, const FVertexName & InToVertexName, const FLiteral & InReplacementLiteral, const FReferenceCreationFunction InReferenceCreateFunc) private
References EnqueueRemoveEdgeOperatorTransform(), InFromVertexName, InToNode, InToVertexName, and UE_API.
Referenced by EnqueueRemoveEdgeOperatorTransform().
EnqueueRemoveEdgeOperatorTransform_Deprecated()
METASOUNDGRAPHCORE_API void Metasound::DynamicGraph::FDynamicOperatorTransactor::EnqueueRemoveEdgeOperatorTransform_Deprecated (const INode & InFromNode, const FVertexName & InFromVertexName, const INode & InToNode, const FVertexName & InToVertexName, const INode & InReplacementLiteralNode, int32 InLiteralOrdinal) private
References EnqueueRemoveEdgeOperatorTransform_Deprecated(), InFromVertexName, InReplacementLiteralNode, InToNode, InToVertexName, and UE_API.
Referenced by EnqueueRemoveEdgeOperatorTransform_Deprecated().
EnqueueRemoveOperatorTransform()
METASOUNDGRAPHCORE_API void Metasound::DynamicGraph::FDynamicOperatorTransactor::EnqueueRemoveOperatorTransform (const INode & InNode, const TArray< FOperatorID > & InOperatorsConnectedToInput) private
References EnqueueRemoveOperatorTransform(), and UE_API.
Referenced by EnqueueRemoveOperatorTransform().
EnqueueTransformOnOperatorQueues()
METASOUNDGRAPHCORE_API void Metasound::DynamicGraph::FDynamicOperatorTransactor::EnqueueTransformOnOperatorQueues (FCreateTransformFunctionRef InFunc) private
References UE_API.
FadeAndRemoveNodeInternal()
METASOUNDGRAPHCORE_API void Metasound::DynamicGraph::FDynamicOperatorTransactor::FadeAndRemoveNodeInternal (const INode & InNode, TArrayView< const FVertexName > InOutputsToFade, bool bInRemoveDataEdgesWithNode) private
References FadeAndRemoveNodeInternal(), and UE_API.
Referenced by FadeAndRemoveNodeInternal().
GetGraph()
METASOUNDGRAPHCORE_API const FGraph & Metasound::DynamicGraph::FDynamicOperatorTransactor::GetGraph () const
Return internal version of graph.
References GetGraph(), and UE_API.
Referenced by GetGraph().
operator=()
FDynamicOperatorTransactor & Metasound::DynamicGraph::FDynamicOperatorTransactor::operator= (const FDynamicOperatorTransactor &) delete
References FDynamicOperatorTransactor().
RemoveDataEdge()
METASOUNDGRAPHCORE_API void Metasound::DynamicGraph::FDynamicOperatorTransactor::RemoveDataEdge (const FGuid & InFromNode, const FVertexName & InFromVertexName, const FGuid & InToNode, const FVertexName & InToVertexName, FLiteral InReplacementLiteral, const FReferenceCreationFunction InReferenceCreateFunc)
Remove the given data edge.
References InFromVertexName, InToNode, InToVertexName, RemoveDataEdge(), and UE_API.
Referenced by RemoveDataEdge().
RemoveInputDataDestination()
METASOUNDGRAPHCORE_API void Metasound::DynamicGraph::FDynamicOperatorTransactor::RemoveInputDataDestination (const FVertexName & InVertexName)
Remove an exposed input from the graph.
References InVertexName, RemoveInputDataDestination(), and UE_API.
Referenced by RemoveInputDataDestination().
RemoveNode()
METASOUNDGRAPHCORE_API void Metasound::DynamicGraph::FDynamicOperatorTransactor::RemoveNode (const FGuid & InNodeID)
Remove a node from the graph.
References RemoveNode(), and UE_API.
Referenced by RemoveNode().
RemoveNodeInternal()
METASOUNDGRAPHCORE_API void Metasound::DynamicGraph::FDynamicOperatorTransactor::RemoveNodeInternal (const INode & InNode, bool bInRemoveDataEdgesWithNode) private
References RemoveNodeInternal(), and UE_API.
Referenced by RemoveNodeInternal().
RemoveOutputDataSource()
METASOUNDGRAPHCORE_API void Metasound::DynamicGraph::FDynamicOperatorTransactor::RemoveOutputDataSource (const FVertexName & InVertexName)
Remove an exposed output from the graph.
References InVertexName, RemoveOutputDataSource(), and UE_API.
Referenced by RemoveOutputDataSource().
SetValue()
METASOUNDGRAPHCORE_API void Metasound::DynamicGraph::FDynamicOperatorTransactor::SetValue (const FGuid & InNodeID, const FVertexName & InVertexName, const FLiteral & InLiteral, const FReferenceCreationFunction InReferenceCreateFunc)
Set the value on a unconnected node input vertex.
References InVertexName, SetValue(), and UE_API.
Referenced by SetValue().
UE_DEPRECATED() [1/3]
Metasound::DynamicGraph::FDynamicOperatorTransactor::UE_DEPRECATED (5. 5, "Replace with CreateTransformQueue overload including FGraphRenderCost") const &
Create a queue for communication with a dynamic operator.
Referenced by UE_DEPRECATED(), and UE_DEPRECATED().
UE_DEPRECATED() [2/3]
Metasound::DynamicGraph::FDynamicOperatorTransactor::UE_DEPRECATED (5. 6, "Literal nodes will no longer be supported. Use RemoveDataEdge with an FLiteral instead.") const &
References UE_DEPRECATED().
UE_DEPRECATED() [3/3]
Metasound::DynamicGraph::FDynamicOperatorTransactor::UE_DEPRECATED (5. 6, "Setting values using a literal node will no longer be supported. Set literal on the vertex interface instead.") const &
References UE_DEPRECATED().
Friends And Related Symbol Documentation
Debug::FDynamicOperatorDebugger
friend class Debug::FDynamicOperatorDebugger friend
Definition at line 304 of file MetasoundDynamicOperatorTransactor.h.
References Debug::FDynamicOperatorDebugger.
Referenced by Debug::FDynamicOperatorDebugger.
operator<
bool operator< (const FLiteralNodeID & InLHS, const FLiteralNodeID & InRHS) friend
Field Documentation
Graph
FGraph Metasound::DynamicGraph::FDynamicOperatorTransactor::Graph private
Definition at line 288 of file MetasoundDynamicOperatorTransactor.h.
GraphSorter
FDynamicGraphIncrementalSorter Metasound::DynamicGraph::FDynamicOperatorTransactor::GraphSorter private
Definition at line 289 of file MetasoundDynamicOperatorTransactor.h.
InEnvironment
const FMetasoundEnvironment& Metasound::DynamicGraph::FDynamicOperatorTransactor::InEnvironment
Definition at line 194 of file MetasoundDynamicOperatorTransactor.h.
Referenced by CreateInsertOperatorTransform(), and CreateTransformQueue().
InFromVertexName
const FVertexName& Metasound::DynamicGraph::FDynamicOperatorTransactor::InFromVertexName
Definition at line 214 of file MetasoundDynamicOperatorTransactor.h.
Referenced by EnqueueFadeAndRemoveEdgeOperatorTransform(), EnqueueFadeAndRemoveEdgeOperatorTransform_Deprecated(), EnqueueRemoveEdgeOperatorTransform(), EnqueueRemoveEdgeOperatorTransform_Deprecated(), and RemoveDataEdge().
InLiteralNode
const FVertexName TUniquePtr<INode> Metasound::DynamicGraph::FDynamicOperatorTransactor::InLiteralNode
Definition at line 220 of file MetasoundDynamicOperatorTransactor.h.
InReplacementLiteralNode
const FVertexName const FGuid const FVertexName TUniquePtr<INode> Metasound::DynamicGraph::FDynamicOperatorTransactor::InReplacementLiteralNode
Definition at line 214 of file MetasoundDynamicOperatorTransactor.h.
Referenced by EnqueueFadeAndRemoveEdgeOperatorTransform_Deprecated(), and EnqueueRemoveEdgeOperatorTransform_Deprecated().
InToNode
const FVertexName const FGuid& Metasound::DynamicGraph::FDynamicOperatorTransactor::InToNode
Definition at line 214 of file MetasoundDynamicOperatorTransactor.h.
Referenced by AddDataEdgeInternal(), EnqueueAddEdgeOperatorTransform(), EnqueueFadeAndAddEdgeOperatorTransform(), EnqueueFadeAndRemoveEdgeOperatorTransform(), EnqueueFadeAndRemoveEdgeOperatorTransform_Deprecated(), EnqueueRemoveEdgeOperatorTransform(), EnqueueRemoveEdgeOperatorTransform_Deprecated(), and RemoveDataEdge().
InToVertexName
const FVertexName const FGuid const FVertexName& Metasound::DynamicGraph::FDynamicOperatorTransactor::InToVertexName
Definition at line 214 of file MetasoundDynamicOperatorTransactor.h.
Referenced by EnqueueFadeAndRemoveEdgeOperatorTransform(), EnqueueFadeAndRemoveEdgeOperatorTransform_Deprecated(), EnqueueRemoveEdgeOperatorTransform(), EnqueueRemoveEdgeOperatorTransform_Deprecated(), and RemoveDataEdge().
InVertexName
const FVertexName& Metasound::DynamicGraph::FDynamicOperatorTransactor::InVertexName
Definition at line 220 of file MetasoundDynamicOperatorTransactor.h.
Referenced by AddInputDataDestination(), AddOutputDataSource(), RemoveInputDataDestination(), RemoveOutputDataSource(), and SetValue().
LiteralNodeMap
TSortedMap<FLiteralNodeID, TUniquePtr<INode> > Metasound::DynamicGraph::FDynamicOperatorTransactor::LiteralNodeMap private
Definition at line 301 of file MetasoundDynamicOperatorTransactor.h.
OperatorBuilder
FOperatorBuilder Metasound::DynamicGraph::FDynamicOperatorTransactor::OperatorBuilder private
Definition at line 287 of file MetasoundDynamicOperatorTransactor.h.
OperatorInfos
TArray<FDynamicOperatorInfo> Metasound::DynamicGraph::FDynamicOperatorTransactor::OperatorInfos private
Definition at line 292 of file MetasoundDynamicOperatorTransactor.h.
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/Metasound/Source/MetasoundGraphCore/Public/MetasoundDynamicOperatorTransactor.h