Unreal Engine 5.6 C++ API: IPreviewCollectionInterface Class Reference
IPreviewCollectionInterface Class Reference abstract
Preview Collection options.
#include "PreviewCollectionInterface.h"
Private Member Functions
GENERATED_IINTERFACE_BODY () UE_DEPRECATED(4.21
Returns nodes that needs for them to map.
virtual USkeletalMesh * GetPreviewBaseMesh () const
If you want this to set base mesh also, please use this interface.
virtual void GetPreviewSkeletalMeshes (TArray< USkeletalMesh * > &OutList, TArray< TSubclassOf< UAnimInstance > > &OutAnimBP) const =0
Returns nodes that needs for them to map.
This interface no longer used Use GetPreviewSkeletalMeshes (TArray< USkeletalMesh * > &OutList, TArray< TSubclassOf< UAnimInstance > > &OutAnimBP).") 1 virtual void GetPreviewSkeletalMeshes(TArray<USkeletalMesh*> & OutList) const
Detailed Description
Preview Collection options.
If you have native UDataAsset class that implements this, you can preview all in the animation editor using Additional Mesh section
Definition at line 21 of file PreviewCollectionInterface.h.
Member Function Documentation
GENERATED_IINTERFACE_BODY()
IPreviewCollectionInterface::GENERATED_IINTERFACE_BODY () private
Returns nodes that needs for them to map.
GetPreviewBaseMesh()
virtual USkeletalMesh * IPreviewCollectionInterface::GetPreviewBaseMesh () const inline private virtual
If you want this to set base mesh also, please use this interface.
If this returns nullptr, it will just use whatever set up right now
Definition at line 30 of file PreviewCollectionInterface.h.
References GetPreviewBaseMesh().
Referenced by GetPreviewBaseMesh().
GetPreviewSkeletalMeshes() [1/2]
virtual void IPreviewCollectionInterface::GetPreviewSkeletalMeshes (TArray< USkeletalMesh * > & OutList, TArray< TSubclassOf< UAnimInstance > > & OutAnimBP) const private pure virtual
Returns nodes that needs for them to map.
GetPreviewSkeletalMeshes() [2/2]
This interface no longer used Use IPreviewCollectionInterface::GetPreviewSkeletalMeshes (TArray< USkeletalMesh * > & OutList, TArray< TSubclassOf< UAnimInstance > > & OutAnimBP) const & private
References GetPreviewSkeletalMeshes(), and UE_DEPRECATED.
Referenced by GetPreviewSkeletalMeshes().
The documentation for this class was generated from the following file:
Runtime/Engine/Public/Animation/PreviewCollectionInterface.h