Unreal Engine 5.6 C++ API: Metasound::Frontend::NodeRegistrationPrivate::TDeprecatedNodeAPIAdapter< TNodeType > Class Template Reference
Metasound::Frontend::NodeRegistrationPrivate::TDeprecatedNodeAPIAdapter< TNodeType > Class Template Reference
#include "MetasoundNodeRegistrationMacro.h"
Public Member Functions
TDeprecatedNodeAPIAdapter (FNodeData InNodeData, TSharedRef< const FNodeClassMetadata > InClassMetadata)
Public Member Functions inherited from Metasound::Frontend::NodeRegistrationPrivate::FDeprecatedNodeAPIAdapterBase
virtual ~FDeprecatedNodeAPIAdapterBase ()=default
virtual METASOUNDFRONTEND_API FOperatorFactorySharedRef GetDefaultOperatorFactory () const override
Return a reference to the default operator factory.
Public Member Functions inherited from Metasound::FBasicNode
METASOUNDGRAPHCORE_API FBasicNode (FNodeData InNodeData, TSharedRef< const FNodeClassMetadata > InClassMetadata)
Construct a basic node.
virtual ~FBasicNode ()=default
virtual METASOUNDGRAPHCORE_API const FGuid & GetInstanceID () const override
Return the ID of this specific instance of the node class.
virtual METASOUNDGRAPHCORE_API const FName & GetInstanceName () const override
Return the name of this specific instance of the node class.
virtual METASOUNDGRAPHCORE_API const FNodeClassMetadata & GetMetadata () const override
Return metadata associated with this node.
virtual METASOUNDGRAPHCORE_API TSharedPtr< const IOperatorData > GetOperatorData () const override
Return the configuration for this node.
virtual METASOUNDGRAPHCORE_API const FVertexInterface & GetVertexInterface () const override
Return the interface associated with this node instance.
virtual METASOUNDGRAPHCORE_API void SetDefaultInput (const FVertexName &InVertexName, const FLiteral &InLiteral) override
Set the default literal for an input vertex.
Public Member Functions inherited from Metasound::INode
virtual ~INode ()
Public Member Functions inherited from Metasound::INodeBase
virtual ~INodeBase ()=default
UE_DEPRECATED (5.6, "INodeBase will not expose dynamic FVertexInterface operations") virtual bool IsVertexInterfaceSupported(const FVertexInterface &InInterface) const
Expresses whether a specific vertex interface is supported.
UE_DEPRECATED (5.6, "INodeBase will not expose dynamic FVertexInterface operations") virtual bool SetVertexInterface(const FVertexInterface &InInterface)
Set the vertex interface.
UE_EXPERIMENTAL (5.6, "Node operator data is still under development") virtual METASOUNDGRAPHCORE_API TSharedPtr< const IOperatorData > GetOperatorData() const
Returns the configuration for the node.
Additional Inherited Members
Protected Member Functions inherited from Metasound::Frontend::NodeRegistrationPrivate::FDeprecatedNodeAPIAdapterBase
METASOUNDFRONTEND_API FDeprecatedNodeAPIAdapterBase (FNodeData InNodeData, TSharedRef< const FNodeClassMetadata > InClassMetadata, TUniquePtr< INode > InNode)
Detailed Description
template<typename TNodeType>
class Metasound::Frontend::NodeRegistrationPrivate::TDeprecatedNodeAPIAdapter< TNodeType >
Definition at line 162 of file MetasoundNodeRegistrationMacro.h.
Constructor & Destructor Documentation
TDeprecatedNodeAPIAdapter()
template<typename TNodeType> Metasound::Frontend::NodeRegistrationPrivate::TDeprecatedNodeAPIAdapter< TNodeType >::TDeprecatedNodeAPIAdapter (FNodeData InNodeData, TSharedRef< const FNodeClassMetadata > InClassMetadata) inline
Definition at line 165 of file MetasoundNodeRegistrationMacro.h.
References Metasound::Frontend::NodeRegistrationPrivate::FDeprecatedNodeAPIAdapterBase::FDeprecatedNodeAPIAdapterBase(), ID, MakeUnique(), MoveTemp(), Name, and Metasound::TIsOnlyDeprecatedNodeConstructorProvided< T >::Value.
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/Metasound/Source/MetasoundFrontend/Public/MetasoundNodeRegistrationMacro.h