Unreal Engine 5.6 C++ API: FSceneViewFamily Class Reference
FSceneViewFamily Class Reference
A set of views into a scene which only have different view transforms and owner actors.
#include "SceneView.h"
Data Structures
struct ConstructionValues
Helper struct for creating FSceneViewFamily instances If created with specifying a time it will retrieve them from the world in the given scene.
Public Member Functions
FSceneViewFamily (const ConstructionValues &CVS)
Initialization constructor.
FSceneViewFamily (const FSceneViewFamily &)
FSceneViewFamily (FSceneViewFamily &&InViewFamily)
virtual ~FSceneViewFamily ()
FORCEINLINE bool AllowStandardTranslucencySeparated () const
FORCEINLINE bool AllowTranslucencyAfterDOF () const
EDebugViewShaderMode ChooseDebugViewShaderMode () const
FORCEINLINE EDebugViewShaderMode GetDebugViewShaderMode () const
template<typename TExtensionData>
TExtensionData * GetExtentionData ()
template<typename TExtensionData>
const TExtensionData * GetExtentionData () const
ERHIFeatureLevel::Type GetFeatureLevel () const
bool GetIsInFocus () const
template<typename TExtensionData>
TExtensionData * GetOrCreateExtentionData ()
FORCEINLINE const ISpatialUpscaler * GetPrimarySpatialUpscalerInterface () const
ISceneRenderer * GetSceneRenderer () const
FORCEINLINE const ISceneViewFamilyScreenPercentage * GetScreenPercentageInterface () const
FORCEINLINE const ISpatialUpscaler * GetSecondarySpatialUpscalerInterface () const
EShaderPlatform GetShaderPlatform () const
FORCEINLINE const UE::Renderer::Private::ITemporalUpscaler * GetTemporalUpscalerInterface () const
FORCEINLINE int32 GetViewModeParam () const
FORCEINLINE const FName & GetViewModeParamName () const
void operator= (const FSceneViewFamily &)=delete
void SetIsInFocus (bool bInIsInFocus)
FORCEINLINE void SetPrimarySpatialUpscalerInterface (ISpatialUpscaler *InSpatialUpscalerInterface)
void SetSceneRenderer (ISceneRenderer *NewSceneRenderer)
FORCEINLINE void SetScreenPercentageInterface (ISceneViewFamilyScreenPercentage *InScreenPercentageInterface)
Safely sets the view family's screen percentage interface.
FORCEINLINE void SetScreenPercentageInterface_Unchecked (ISceneViewFamilyScreenPercentage *InScreenPercentageInterface)
FORCEINLINE void SetSecondarySpatialUpscalerInterface (ISpatialUpscaler *InSpatialUpscalerInterface)
FORCEINLINE void SetTemporalUpscalerInterface (UE::Renderer::Private::ITemporalUpscaler *InTemporalUpscalerInterface)
bool SupportsScreenPercentage () const
Returns whether the screen percentage show flag is supported or not for this view family.
UE_DEPRECATED (5.6, "bIsMultipleViewFamily is no longer used") bool bIsMultipleViewFamily
UE_DEPRECATED (5.6, "This member is no longer used") float *ProfileSceneRenderTime
FORCEINLINE bool UseDebugViewPS () const
Data Fields
TArray< const FSceneView * > AllViews
All views include main camera views and scene capture views.
bool bAdditionalViewFamily
Indicates this view family is an additional one.
bool bCurrentlyBeingEdited
Whether the scene is currently being edited, which can be used to speed up lighting propagation.
bool bDeferClear
Used to defer the back buffer clearing to just before the back buffer is drawn to.
bool bDrawBaseInfo
Indicates whether, or not, the base attachment volume should be drawn.
bool bIsFirstViewInMultipleViewFamily = true
Whether this view is the first of multiple view families rendered in a single frame.
bool bIsHDR
When enabled, the post processing will output in HDR space.
bool bIsMainViewFamily = false
Whether this is the "main" view family.
bool bIsViewFamilyInfo = false
bool bMultiGPUForkAndJoin
if true then each view is not rendered using the same GPUMask.
bool bNullifyWorldSpacePosition
Indicates whether the shader world space position should be forced to 0.
bool bOverrideVirtualTextureThrottle
Whether to disable virtual texture update throttling.
bool bRealtimeUpdate
Indicates whether the view family is updated in realtime.
bool bRequireMultiView
True if scenecolor and depth should be multiview-allocated.
bool bResolveScene
if true then results of scene rendering are copied/resolved to the RenderTarget.
bool bSplitScreenDebugAllowed = false
Whether this view allows split screen debug – we only want it for editor and game viewports, not other random scene renders.
bool bThumbnailRendering = false
Whether this view is for thumbnail rendering.
bool bWorldIsPaused
GetWorld->IsPaused() && !Simulate Simulate is excluded as the camera can move which invalidates motionblur.
float DebugDPIScale = 1.0f
DPI scale to be used for debugging font.
EDebugViewShaderMode DebugViewShaderMode
FDisplayInternalsData DisplayInternalsData
FEngineShowFlags EngineShowFlags
The new show flags for the views (meant to replace the old system).
FExposureSettings ExposureSettings
Editor setting to allow designers to override the automatic expose.
uint64 FrameCounter = 0
Copy from main thread GFrameCounter to be accessible on render thread side.
uint32 FrameNumber
Copy from main thread GFrameNumber to be accessible on render thread side.
int8 LandscapeLODOverride
FString ProfileDescription
const FRenderTarget * RenderTarget
The render target which the views are being rendered to.
const FRenderTarget * RenderTargetDepth
FSceneInterface * Scene
The scene being viewed.
ESceneCaptureCompositeMode SceneCaptureCompositeMode
When enabled, the scene capture will composite into the render target instead of overwriting its contents.
ESceneCaptureSource SceneCaptureSource
Which component of the scene rendering should be output to the final render target.
ESecondaryScreenPercentageMethod SecondaryScreenPercentageMethod
float SecondaryViewFraction
Secondary view fraction to support High DPI monitor still with same primary screen percentage range for temporal upscale to test content consistently in editor no mater of the HighDPI scale.
TArray< FVector, TInlineAllocator< 2 > > StreamingViewOrigins
Views' origin of the (optional) streaming views.
FGameTime Time
The current time.
TArray< TSharedRef< class ISceneViewExtension, ESPMode::ThreadSafe > > ViewExtensions
Extensions that can modify view parameters on the render thread.
EViewModeIndex ViewMode
View mode of the family.
int32 ViewModeParam
FName ViewModeParamName
TArray< const FSceneView * > Views
The views which make up the family.
int32 VirtualTextureFeedbackFactor
Size in pixels of a virtual texture feedback tile.
Private Attributes
bool bAllowStandardTranslucencySeparated = false
whether the pre DOF translucency are allowed to be rendered in separated target from scene to allow for better composition with distortion.
bool bAllowTranslucencyAfterDOF = false
whether the translucency are allowed to render after DOF, if not they will be rendered in standard translucency.
bool bIsInFocus = true
True if this view is the current editing view or the active game view.
ISpatialUpscaler * PrimarySpatialUpscalerInterface
ISceneRenderer * SceneRenderer
The scene renderer that is rendering this view family.
ISceneViewFamilyScreenPercentage * ScreenPercentageInterface
Interface to handle screen percentage of the views of the family.
ISpatialUpscaler * SecondarySpatialUpscalerInterface
UE::Renderer::Private::ITemporalUpscaler * TemporalUpscalerInterface
Renderer private interfaces, automatically have same lifetime as FSceneViewFamily.
TArray< TSharedRef< class ISceneViewFamilyExtentionData, ESPMode::ThreadSafe > > ViewExtentionDatas
Arrays of standalone data that have safe lifetime as FSceneViewFamily.
Friends
class FSceneRenderer
class FViewFamilyInfo
Detailed Description
A set of views into a scene which only have different view transforms and owner actors.
Definition at line 2161 of file SceneView.h.
Constructor & Destructor Documentation
FSceneViewFamily() [1/3]
FSceneViewFamily::FSceneViewFamily (const ConstructionValues & CVS)
Initialization constructor.
References FSceneViewFamily().
Referenced by FSceneViewFamily(), FSceneViewFamily(), FSceneViewFamily(), ~FSceneViewFamily(), and operator=().
FSceneViewFamily() [2/3]
FSceneViewFamily::FSceneViewFamily (const FSceneViewFamily &)
References FSceneViewFamily().
~FSceneViewFamily()
virtual FSceneViewFamily::~FSceneViewFamily () virtual
References FSceneViewFamily().
FSceneViewFamily() [3/3]
FSceneViewFamily::FSceneViewFamily (FSceneViewFamily && InViewFamily)
References FSceneViewFamily().
Member Function Documentation
AllowStandardTranslucencySeparated()
FORCEINLINE bool FSceneViewFamily::AllowStandardTranslucencySeparated () const inline
Definition at line 2435 of file SceneView.h.
References bAllowStandardTranslucencySeparated, and FORCEINLINE.
AllowTranslucencyAfterDOF()
FORCEINLINE bool FSceneViewFamily::AllowTranslucencyAfterDOF () const inline
Definition at line 2433 of file SceneView.h.
References bAllowTranslucencyAfterDOF, and FORCEINLINE.
ChooseDebugViewShaderMode()
EDebugViewShaderMode FSceneViewFamily::ChooseDebugViewShaderMode () const
GetDebugViewShaderMode()
FORCEINLINE EDebugViewShaderMode FSceneViewFamily::GetDebugViewShaderMode () const inline
Definition at line 2418 of file SceneView.h.
References DebugViewShaderMode, and FORCEINLINE.
Referenced by FSetupViewUniformParametersInputs::Create().
GetExtentionData() [1/2]
template<typename TExtensionData> TExtensionData * FSceneViewFamily::GetExtentionData () inline
Definition at line 2483 of file SceneView.h.
References AsConst().
GetExtentionData() [2/2]
template<typename TExtensionData> const TExtensionData * FSceneViewFamily::GetExtentionData () const inline
Definition at line 2469 of file SceneView.h.
References TIsDerivedFrom< DerivedType, BaseType >::Value, and ViewExtentionDatas.
Referenced by GetOrCreateExtentionData().
GetFeatureLevel()
ERHIFeatureLevel::Type FSceneViewFamily::GetFeatureLevel () const
References GetFeatureLevel().
Referenced by GetFeatureLevel(), and GetShaderPlatform().
GetIsInFocus()
bool FSceneViewFamily::GetIsInFocus () const inline
Definition at line 2536 of file SceneView.h.
References bIsInFocus.
GetOrCreateExtentionData()
template<typename TExtensionData> TExtensionData * FSceneViewFamily::GetOrCreateExtentionData () inline
Definition at line 2488 of file SceneView.h.
References check, GetExtentionData(), MakeShared(), and ViewExtentionDatas.
GetPrimarySpatialUpscalerInterface()
FORCEINLINE const ISpatialUpscaler * FSceneViewFamily::GetPrimarySpatialUpscalerInterface () const inline
Definition at line 2519 of file SceneView.h.
References FORCEINLINE, and PrimarySpatialUpscalerInterface.
GetSceneRenderer()
ISceneRenderer * FSceneViewFamily::GetSceneRenderer () const inline
Definition at line 2540 of file SceneView.h.
References check, and SceneRenderer.
GetScreenPercentageInterface()
FORCEINLINE const ISceneViewFamilyScreenPercentage * FSceneViewFamily::GetScreenPercentageInterface () const inline
Definition at line 2437 of file SceneView.h.
References FORCEINLINE, and ScreenPercentageInterface.
GetSecondarySpatialUpscalerInterface()
FORCEINLINE const ISpatialUpscaler * FSceneViewFamily::GetSecondarySpatialUpscalerInterface () const inline
Definition at line 2531 of file SceneView.h.
References FORCEINLINE, and SecondarySpatialUpscalerInterface.
GetShaderPlatform()
EShaderPlatform FSceneViewFamily::GetShaderPlatform () const inline
Definition at line 2411 of file SceneView.h.
References GetFeatureLevel(), and GetShaderPlatform().
Referenced by GetShaderPlatform().
GetTemporalUpscalerInterface()
FORCEINLINE const UE::Renderer::Private::ITemporalUpscaler * FSceneViewFamily::GetTemporalUpscalerInterface () const inline
Definition at line 2507 of file SceneView.h.
References FORCEINLINE, and TemporalUpscalerInterface.
GetViewModeParam()
FORCEINLINE int32 FSceneViewFamily::GetViewModeParam () const inline
Definition at line 2419 of file SceneView.h.
References FORCEINLINE, and ViewModeParam.
GetViewModeParamName()
FORCEINLINE const FName & FSceneViewFamily::GetViewModeParamName () const inline
Definition at line 2420 of file SceneView.h.
References FORCEINLINE, and ViewModeParamName.
operator=()
void FSceneViewFamily::operator= (const FSceneViewFamily &) delete
References FSceneViewFamily().
SetIsInFocus()
void FSceneViewFamily::SetIsInFocus (bool bInIsInFocus) inline
Definition at line 2537 of file SceneView.h.
References bIsInFocus.
SetPrimarySpatialUpscalerInterface()
FORCEINLINE void FSceneViewFamily::SetPrimarySpatialUpscalerInterface (ISpatialUpscaler * InSpatialUpscalerInterface) inline
Definition at line 2512 of file SceneView.h.
References check, checkf, FORCEINLINE, PrimarySpatialUpscalerInterface, and TEXT.
SetSceneRenderer()
void FSceneViewFamily::SetSceneRenderer (ISceneRenderer * NewSceneRenderer) inline
Definition at line 2539 of file SceneView.h.
References SceneRenderer.
SetScreenPercentageInterface()
FORCEINLINE void FSceneViewFamily::SetScreenPercentageInterface (ISceneViewFamilyScreenPercentage * InScreenPercentageInterface) inline
Safely sets the view family's screen percentage interface.
This is meant to be set by one of the ISceneViewExtension::BeginRenderViewFamily(). And collision will automatically be detected. If no extension sets it, that is fine since the renderer is going to use an internal default one.
The renderer reserves the right to delete and replace the view family's screen percentage interface for testing purposes with the r.Test.OverrideScreenPercentageInterface CVar.
Definition at line 2451 of file SceneView.h.
References check, checkf, FORCEINLINE, ScreenPercentageInterface, and TEXT.
SetScreenPercentageInterface_Unchecked()
FORCEINLINE void FSceneViewFamily::SetScreenPercentageInterface_Unchecked (ISceneViewFamilyScreenPercentage * InScreenPercentageInterface) inline
Definition at line 2458 of file SceneView.h.
References FORCEINLINE, and ScreenPercentageInterface.
SetSecondarySpatialUpscalerInterface()
FORCEINLINE void FSceneViewFamily::SetSecondarySpatialUpscalerInterface (ISpatialUpscaler * InSpatialUpscalerInterface) inline
Definition at line 2524 of file SceneView.h.
References check, checkf, FORCEINLINE, SecondarySpatialUpscalerInterface, and TEXT.
SetTemporalUpscalerInterface()
FORCEINLINE void FSceneViewFamily::SetTemporalUpscalerInterface (UE::Renderer::Private::ITemporalUpscaler * InTemporalUpscalerInterface) inline
Definition at line 2500 of file SceneView.h.
References check, checkf, FORCEINLINE, TemporalUpscalerInterface, and TEXT.
SupportsScreenPercentage()
bool FSceneViewFamily::SupportsScreenPercentage () const
Returns whether the screen percentage show flag is supported or not for this view family.
UE_DEPRECATED() [1/2]
FSceneViewFamily::UE_DEPRECATED (5. 6, "bIsMultipleViewFamily is no longer used")
References bool.
UE_DEPRECATED() [2/2]
FSceneViewFamily::UE_DEPRECATED (5. 6, "This member is no longer used")
References float.
UseDebugViewPS()
FORCEINLINE bool FSceneViewFamily::UseDebugViewPS () const inline
Definition at line 2422 of file SceneView.h.
References DebugViewShaderMode, DVSM_None, and FORCEINLINE.
Friends And Related Symbol Documentation
FSceneRenderer
friend class FSceneRenderer friend
Definition at line 2566 of file SceneView.h.
References FSceneRenderer.
Referenced by FSceneRenderer.
FViewFamilyInfo
friend class FViewFamilyInfo friend
Definition at line 2567 of file SceneView.h.
References FViewFamilyInfo, and PRAGMA_DISABLE_DEPRECATION_WARNINGS.
Referenced by FViewFamilyInfo.
Field Documentation
AllViews
TArray<const FSceneView*> FSceneViewFamily::AllViews
All views include main camera views and scene capture views.
Definition at line 2261 of file SceneView.h.
bAdditionalViewFamily
bool FSceneViewFamily::bAdditionalViewFamily
Indicates this view family is an additional one.
Definition at line 2286 of file SceneView.h.
bAllowStandardTranslucencySeparated
bool FSceneViewFamily::bAllowStandardTranslucencySeparated = false private
whether the pre DOF translucency are allowed to be rendered in separated target from scene to allow for better composition with distortion.
Definition at line 2561 of file SceneView.h.
Referenced by AllowStandardTranslucencySeparated().
bAllowTranslucencyAfterDOF
bool FSceneViewFamily::bAllowTranslucencyAfterDOF = false private
whether the translucency are allowed to render after DOF, if not they will be rendered in standard translucency.
Definition at line 2558 of file SceneView.h.
Referenced by AllowTranslucencyAfterDOF().
bCurrentlyBeingEdited
bool FSceneViewFamily::bCurrentlyBeingEdited
Whether the scene is currently being edited, which can be used to speed up lighting propagation.
Definition at line 2374 of file SceneView.h.
bDeferClear
bool FSceneViewFamily::bDeferClear
Used to defer the back buffer clearing to just before the back buffer is drawn to.
Definition at line 2292 of file SceneView.h.
bDrawBaseInfo
bool FSceneViewFamily::bDrawBaseInfo
Indicates whether, or not, the base attachment volume should be drawn.
Definition at line 2384 of file SceneView.h.
bIsFirstViewInMultipleViewFamily
bool FSceneViewFamily::bIsFirstViewInMultipleViewFamily = true
Whether this view is the first of multiple view families rendered in a single frame.
Setting this correctly helps make better and more consistent streaming decisions. This should be a temporary workaround until we have an API for executing code before/after all view rendering.
Definition at line 2313 of file SceneView.h.
bIsHDR
bool FSceneViewFamily::bIsHDR
When enabled, the post processing will output in HDR space.
Definition at line 2346 of file SceneView.h.
bIsInFocus
bool FSceneViewFamily::bIsInFocus = true private
True if this view is the current editing view or the active game view.
Definition at line 2564 of file SceneView.h.
Referenced by GetIsInFocus(), and SetIsInFocus().
bIsMainViewFamily
bool FSceneViewFamily::bIsMainViewFamily = false
Whether this is the "main" view family.
Should be set to true for the view family of the main editor or game viewport. Affects where rendering occurs for Scene Captures with the "bMainViewFamily" flag set.
Definition at line 2324 of file SceneView.h.
bIsViewFamilyInfo
bool FSceneViewFamily::bIsViewFamilyInfo = false
Definition at line 2315 of file SceneView.h.
bMultiGPUForkAndJoin
bool FSceneViewFamily::bMultiGPUForkAndJoin
if true then each view is not rendered using the same GPUMask.
Definition at line 2298 of file SceneView.h.
bNullifyWorldSpacePosition
bool FSceneViewFamily::bNullifyWorldSpacePosition
Indicates whether the shader world space position should be forced to 0.
Also sets the view vector to (0,0,1) for all pixels. This is used in the texture streaming build when computing material tex coords scale. Because the material are rendered in tiles, there is no actual valid mapping for world space position. World space mapping would require to render mesh with the level transforms to be valid.
Definition at line 2392 of file SceneView.h.
Referenced by FSetupViewUniformParametersInputs::Create().
bOverrideVirtualTextureThrottle
bool FSceneViewFamily::bOverrideVirtualTextureThrottle
Whether to disable virtual texture update throttling.
Definition at line 2377 of file SceneView.h.
bRealtimeUpdate
bool FSceneViewFamily::bRealtimeUpdate
Indicates whether the view family is updated in realtime.
Definition at line 2289 of file SceneView.h.
bRequireMultiView
bool FSceneViewFamily::bRequireMultiView
True if scenecolor and depth should be multiview-allocated.
Definition at line 2349 of file SceneView.h.
bResolveScene
bool FSceneViewFamily::bResolveScene
if true then results of scene rendering are copied/resolved to the RenderTarget.
Definition at line 2295 of file SceneView.h.
bSplitScreenDebugAllowed
bool FSceneViewFamily::bSplitScreenDebugAllowed = false
Whether this view allows split screen debug – we only want it for editor and game viewports, not other random scene renders.
Definition at line 2318 of file SceneView.h.
bThumbnailRendering
bool FSceneViewFamily::bThumbnailRendering = false
Whether this view is for thumbnail rendering.
Definition at line 2337 of file SceneView.h.
bWorldIsPaused
bool FSceneViewFamily::bWorldIsPaused
GetWorld->IsPaused() && !Simulate Simulate is excluded as the camera can move which invalidates motionblur.
Definition at line 2343 of file SceneView.h.
Referenced by FSetupViewUniformParametersInputs::Create().
DebugDPIScale
float FSceneViewFamily::DebugDPIScale = 1.0f
DPI scale to be used for debugging font.
Definition at line 2352 of file SceneView.h.
DebugViewShaderMode
EDebugViewShaderMode FSceneViewFamily::DebugViewShaderMode
Definition at line 2414 of file SceneView.h.
Referenced by GetDebugViewShaderMode(), and UseDebugViewPS().
DisplayInternalsData
FDisplayInternalsData FSceneViewFamily::DisplayInternalsData
Definition at line 2361 of file SceneView.h.
EngineShowFlags
FEngineShowFlags FSceneViewFamily::EngineShowFlags
The new show flags for the views (meant to replace the old system).
Definition at line 2274 of file SceneView.h.
Referenced by FSetupViewUniformParametersInputs::Create(), and FInstancedStaticMeshSceneProxy::GetViewRelevance().
ExposureSettings
FExposureSettings FSceneViewFamily::ExposureSettings
Editor setting to allow designers to override the automatic expose.
0:Automatic, following indices: -4 .. +4
Definition at line 2355 of file SceneView.h.
FrameCounter
uint64 FSceneViewFamily::FrameCounter = 0
Copy from main thread GFrameCounter to be accessible on render thread side.
GFrameCounter is incremented once per engine tick, so multi views of the same frame have the same value.
Definition at line 2283 of file SceneView.h.
Referenced by FSetupViewUniformParametersInputs::Create().
FrameNumber
uint32 FSceneViewFamily::FrameNumber
Copy from main thread GFrameNumber to be accessible on render thread side.
UINT_MAX before CreateSceneRenderer() or BeginRenderingViewFamily() was called
Definition at line 2280 of file SceneView.h.
Referenced by FSetupViewUniformParametersInputs::Create().
LandscapeLODOverride
int8 FSceneViewFamily::LandscapeLODOverride
Definition at line 2371 of file SceneView.h.
PrimarySpatialUpscalerInterface
ISpatialUpscaler* FSceneViewFamily::PrimarySpatialUpscalerInterface private
Definition at line 2551 of file SceneView.h.
Referenced by GetPrimarySpatialUpscalerInterface(), and SetPrimarySpatialUpscalerInterface().
ProfileDescription
FString FSceneViewFamily::ProfileDescription
Definition at line 2396 of file SceneView.h.
RenderTarget
const FRenderTarget* FSceneViewFamily::RenderTarget
The render target which the views are being rendered to.
Definition at line 2267 of file SceneView.h.
RenderTargetDepth
const FRenderTarget* FSceneViewFamily::RenderTargetDepth
Definition at line 2268 of file SceneView.h.
Scene
FSceneInterface* FSceneViewFamily::Scene
The scene being viewed.
Definition at line 2271 of file SceneView.h.
SceneCaptureCompositeMode
ESceneCaptureCompositeMode FSceneViewFamily::SceneCaptureCompositeMode
When enabled, the scene capture will composite into the render target instead of overwriting its contents.
Definition at line 2334 of file SceneView.h.
SceneCaptureSource
ESceneCaptureSource FSceneViewFamily::SceneCaptureSource
Which component of the scene rendering should be output to the final render target.
If SCS_FinalColorLDR this indicates do nothing.
Definition at line 2330 of file SceneView.h.
SceneRenderer
ISceneRenderer* FSceneViewFamily::SceneRenderer private
The scene renderer that is rendering this view family.
This is only initialized in the rendering thread's copies of the FSceneViewFamily.
Definition at line 2544 of file SceneView.h.
Referenced by GetSceneRenderer(), and SetSceneRenderer().
ScreenPercentageInterface
ISceneViewFamilyScreenPercentage* FSceneViewFamily::ScreenPercentageInterface private
Interface to handle screen percentage of the views of the family.
Definition at line 2547 of file SceneView.h.
Referenced by GetScreenPercentageInterface(), SetScreenPercentageInterface(), and SetScreenPercentageInterface_Unchecked().
SecondaryScreenPercentageMethod
ESecondaryScreenPercentageMethod FSceneViewFamily::SecondaryScreenPercentageMethod
Definition at line 2368 of file SceneView.h.
SecondarySpatialUpscalerInterface
ISpatialUpscaler* FSceneViewFamily::SecondarySpatialUpscalerInterface private
Definition at line 2552 of file SceneView.h.
Referenced by GetSecondarySpatialUpscalerInterface(), and SetSecondarySpatialUpscalerInterface().
SecondaryViewFraction
float FSceneViewFamily::SecondaryViewFraction
Secondary view fraction to support High DPI monitor still with same primary screen percentage range for temporal upscale to test content consistently in editor no mater of the HighDPI scale.
Definition at line 2367 of file SceneView.h.
StreamingViewOrigins
TArray<FVector, TInlineAllocator<2> > FSceneViewFamily::StreamingViewOrigins
Views' origin of the (optional) streaming views.
Used for prefetching rendering data ahead of time.
Definition at line 2402 of file SceneView.h.
TemporalUpscalerInterface
UE::Renderer::Private::ITemporalUpscaler* FSceneViewFamily::TemporalUpscalerInterface private
Renderer private interfaces, automatically have same lifetime as FSceneViewFamily.
Definition at line 2550 of file SceneView.h.
Referenced by GetTemporalUpscalerInterface(), and SetTemporalUpscalerInterface().
Time
FGameTime FSceneViewFamily::Time
The current time.
Definition at line 2277 of file SceneView.h.
Referenced by FSetupViewUniformParametersInputs::Create().
ViewExtensions
TArray<TSharedRef<class ISceneViewExtension, ESPMode::ThreadSafe> > FSceneViewFamily::ViewExtensions
Extensions that can modify view parameters on the render thread.
Definition at line 2358 of file SceneView.h.
ViewExtentionDatas
TArray<TSharedRef<class ISceneViewFamilyExtentionData, ESPMode::ThreadSafe> > FSceneViewFamily::ViewExtentionDatas private
Arrays of standalone data that have safe lifetime as FSceneViewFamily.
Definition at line 2555 of file SceneView.h.
Referenced by GetExtentionData(), and GetOrCreateExtentionData().
ViewMode
EViewModeIndex FSceneViewFamily::ViewMode
View mode of the family.
Definition at line 2264 of file SceneView.h.
ViewModeParam
int32 FSceneViewFamily::ViewModeParam
Definition at line 2415 of file SceneView.h.
Referenced by GetViewModeParam().
ViewModeParamName
FName FSceneViewFamily::ViewModeParamName
Definition at line 2416 of file SceneView.h.
Referenced by GetViewModeParamName().
Views
TArray<const FSceneView*> FSceneViewFamily::Views
The views which make up the family.
Definition at line 2258 of file SceneView.h.
VirtualTextureFeedbackFactor
int32 FSceneViewFamily::VirtualTextureFeedbackFactor
Size in pixels of a virtual texture feedback tile.
Definition at line 2380 of file SceneView.h.
The documentation for this class was generated from the following file:
Runtime/Engine/Public/SceneView.h