Unreal Engine 5.6 C++ API: UE::Geometry::FMeshFaceSelection Class Reference
UE::Geometry::FMeshFaceSelection Class Reference
#include "MeshFaceSelection.h"
Public Member Functions
FMeshFaceSelection (const FDynamicMesh3 *mesh)
GEOMETRYCORE_API FMeshFaceSelection (const FDynamicMesh3 *mesh, const FMeshVertexSelection &convertV, int minCount=3)
FMeshFaceSelection (const FDynamicMesh3 *mesh, int group_id)
TArray< int > AsArray () const
TBitArray< FDefaultBitArrayAllocator > AsBitArray () const
const TSet< int > & AsSet () const
TSet< int >::TRangedForIterator begin ()
DO NOT USE DIRECTLY STL-like iterators to enable range-based for loop support.
TSet< int >::TRangedForConstIterator begin () const
bool ClipFins (bool bClipLoners)
bool Contains (int tid) const
GEOMETRYCORE_API void ContractBorderByOneRingNeighbours (int NumRings=1, bool bContractFromMeshBoundary=false, const TUniqueFunction< bool(int)> &FilterF=nullptr)
remove all triangles in vertex one-rings of current selection to set.
template<typename EnumerableType>
void Deselect (const EnumerableType &Enumerable)
void Deselect (int tid)
void Deselect (TArrayView< const int > Triangles)
void DeselectAll ()
void DeselectGroup (int gid)
TSet< int >::TRangedForIterator end ()
TSet< int >::TRangedForConstIterator end () const
void ExpandToFaceNeighbours (const TUniqueFunction< bool(int)> &FilterF=nullptr)
void ExpandToFaceNeighbours (int rounds, const TUniqueFunction< bool(int)> &FilterF=nullptr)
GEOMETRYCORE_API void ExpandToOneRingNeighbours (const TUniqueFunction< bool(int)> &FilterF=nullptr)
Add all triangles in vertex one-rings of current selection to set.
GEOMETRYCORE_API void ExpandToOneRingNeighbours (int nRings, const TUniqueFunction< bool(int)> &FilterF=nullptr)
Expand selection by N vertex one-rings.
bool FillEars (bool bFillTinyHoles)
TArray< int > FindBorderTris () const
find set of tris just inside border of selection
TArray< int > FindNeighbourTris () const
find set of tris just outside border of selection
void FloodFill (const TArray< int > &Seeds, const TUniqueFunction< bool(int)> &TriFilterF=nullptr, const TUniqueFunction< bool(int)> &EdgeFilterF=nullptr)
Grow selection outwards from seed triangles, until it hits boundaries defined by triangle and edge filters.
void FloodFill (int tSeed, const TUniqueFunction< bool(int)> &TriFilterF=nullptr, const TUniqueFunction< bool(int)> &EdgeFilterF=nullptr)
Grow selection outwards from seed triangle, until it hits boundaries defined by triangle and edge filters.
bool IsSelected (int tid) const
TPair< bool, bool > IsSelectionBoundaryEdge (int32 eid) const
bool LocalOptimize (bool bClipFins, bool bFillEars, bool bFillTinyHoles=true, bool bClipLoners=true, bool bRemoveBowties=false)
bool LocalOptimize (bool bRemoveBowties=true)
int Num () const
bool remove_bowties ()
bool RemoveBowties ()
Find any "bowtie" vertices - ie vertex v such taht there is multiple spans of triangles selected in v's triangle one-ring - and deselect those one-rings.
template<typename EnumerableType, typename E = decltype(DeclVal<EnumerableType>().begin())>
void Select (const EnumerableType &Enumerable)
void Select (int tid)
void Select (TFunctionRef< bool(int)> SelectF)
void SelectEdgeTris (int eid)
void SelectGroup (int gid)
void SelectGroupInverse (int gid)
void SelectVertexOneRing (int vid)
void SelectVertexOneRings (TArrayView< const int > Vertices)
template<typename EnumerableType, typename StorageType>
void SetDifference (const EnumerableType &SubtractSet, StorageType &DifferenceStorage) const
Find the elements in current selection that are not in SubtractSet, and store in DifferenceStorage.
template<typename EnumerableType, typename StorageType>
void SetIntersection (const EnumerableType &IntersectSet, StorageType &IntersectionStorage) const
Find the elements in current selection that are also in IntersectSet, and store in IntersectionStorage.
Private Member Functions
void add (int tid)
void count_nbrs (int tid, int &nbr_in, int &nbr_out, int &bdry_e) const
bool is_bowtie_vtx (int vid) const
bool is_ear (int tid, bool include_tiny_holes) const
bool is_fin (int tid, bool include_loners) const
void remove (int tid)
Private Attributes
const FDynamicMesh3 * Mesh
TSet< int > Selected
Detailed Description
Definition at line 20 of file MeshFaceSelection.h.
Constructor & Destructor Documentation
FMeshFaceSelection() [1/3]
UE::Geometry::FMeshFaceSelection::FMeshFaceSelection (const FDynamicMesh3 * mesh) inline
Definition at line 29 of file MeshFaceSelection.h.
References Mesh.
FMeshFaceSelection() [2/3]
GEOMETRYCORE_API UE::Geometry::FMeshFaceSelection::FMeshFaceSelection (const FDynamicMesh3 * mesh, const FMeshVertexSelection & convertV, int minCount = 3)
FMeshFaceSelection() [3/3]
UE::Geometry::FMeshFaceSelection::FMeshFaceSelection (const FDynamicMesh3 * mesh, int group_id) inline
Definition at line 39 of file MeshFaceSelection.h.
References Mesh, and SelectGroup().
Member Function Documentation
add()
void UE::Geometry::FMeshFaceSelection::add (int tid) inline private
Definition at line 56 of file MeshFaceSelection.h.
References Selected.
Referenced by ExpandToFaceNeighbours(), FillEars(), FloodFill(), Select(), Select(), Select(), SelectEdgeTris(), SelectGroup(), SelectGroupInverse(), and SelectVertexOneRing().
AsArray()
TArray< int > UE::Geometry::FMeshFaceSelection::AsArray () const inline
Definition at line 241 of file MeshFaceSelection.h.
References Selected.
AsBitArray()
TBitArray< FDefaultBitArrayAllocator > UE::Geometry::FMeshFaceSelection::AsBitArray () const inline
Definition at line 245 of file MeshFaceSelection.h.
References Mesh, and Selected.
AsSet()
const TSet< int > & UE::Geometry::FMeshFaceSelection::AsSet () const inline
Definition at line 237 of file MeshFaceSelection.h.
References Selected.
begin() [1/2]
TSet< int >::TRangedForIterator UE::Geometry::FMeshFaceSelection::begin () inline
DO NOT USE DIRECTLY STL-like iterators to enable range-based for loop support.
Definition at line 48 of file MeshFaceSelection.h.
References Selected.
begin() [2/2]
TSet< int >::TRangedForConstIterator UE::Geometry::FMeshFaceSelection::begin () const inline
Definition at line 49 of file MeshFaceSelection.h.
References Selected.
ClipFins()
bool UE::Geometry::FMeshFaceSelection::ClipFins (bool bClipLoners) inline
Definition at line 428 of file MeshFaceSelection.h.
References TArray< InElementType, InAllocatorType >::Add(), is_fin(), TArray< InElementType, InAllocatorType >::Num(), remove(), and Selected.
Referenced by LocalOptimize().
Contains()
bool UE::Geometry::FMeshFaceSelection::Contains (int tid) const inline
Definition at line 80 of file MeshFaceSelection.h.
References Selected.
ContractBorderByOneRingNeighbours()
GEOMETRYCORE_API void UE::Geometry::FMeshFaceSelection::ContractBorderByOneRingNeighbours (int NumRings = 1, bool bContractFromMeshBoundary = false, const TUniqueFunction< bool(int)> & FilterF = nullptr)
remove all triangles in vertex one-rings of current selection to set.
On a large selection this is quite expensive as we don't know the boundary, so we have to iterate over all selected triangles.
Return false from FilterF to prevent triangles from being deselected.
count_nbrs()
void UE::Geometry::FMeshFaceSelection::count_nbrs (int tid, int & nbr_in, int & nbr_out, int & bdry_e) const inline private
Definition at line 573 of file MeshFaceSelection.h.
References UE::Geometry::FDynamicMesh3::InvalidID, IsSelected(), and Mesh.
Referenced by is_ear(), and is_fin().
Deselect() [1/3]
template<typename EnumerableType> void UE::Geometry::FMeshFaceSelection::Deselect (const EnumerableType & Enumerable) inline
Definition at line 158 of file MeshFaceSelection.h.
References remove().
Deselect() [2/3]
void UE::Geometry::FMeshFaceSelection::Deselect (int tid) inline
Definition at line 145 of file MeshFaceSelection.h.
References remove().
Referenced by remove_bowties().
Deselect() [3/3]
void UE::Geometry::FMeshFaceSelection::Deselect (TArrayView< const int > Triangles) inline
Definition at line 149 of file MeshFaceSelection.h.
References remove().
DeselectAll()
void UE::Geometry::FMeshFaceSelection::DeselectAll () inline
Definition at line 166 of file MeshFaceSelection.h.
References Selected.
DeselectGroup()
void UE::Geometry::FMeshFaceSelection::DeselectGroup (int gid) inline
Definition at line 194 of file MeshFaceSelection.h.
References Mesh, and remove().
end() [1/2]
TSet< int >::TRangedForIterator UE::Geometry::FMeshFaceSelection::end () inline
Definition at line 50 of file MeshFaceSelection.h.
References Selected.
end() [2/2]
TSet< int >::TRangedForConstIterator UE::Geometry::FMeshFaceSelection::end () const inline
Definition at line 51 of file MeshFaceSelection.h.
References Selected.
ExpandToFaceNeighbours() [1/2]
void UE::Geometry::FMeshFaceSelection::ExpandToFaceNeighbours (const TUniqueFunction< bool(int)> & FilterF = nullptr) inline
Definition at line 316 of file MeshFaceSelection.h.
References TArray< InElementType, InAllocatorType >::Add(), add(), ID, UE::Geometry::FDynamicMesh3::InvalidID, IsSelected(), Mesh, and Selected.
Referenced by ExpandToFaceNeighbours().
ExpandToFaceNeighbours() [2/2]
void UE::Geometry::FMeshFaceSelection::ExpandToFaceNeighbours (int rounds, const TUniqueFunction< bool(int)> & FilterF = nullptr) inline
Definition at line 340 of file MeshFaceSelection.h.
References ExpandToFaceNeighbours().
ExpandToOneRingNeighbours() [1/2]
GEOMETRYCORE_API void UE::Geometry::FMeshFaceSelection::ExpandToOneRingNeighbours (const TUniqueFunction< bool(int)> & FilterF = nullptr)
Add all triangles in vertex one-rings of current selection to set.
On a large selection this is quite expensive as we don't know the boundary, so we have to iterate over all selected triangles.
Return false from FilterF to prevent triangles from being included.
ExpandToOneRingNeighbours() [2/2]
GEOMETRYCORE_API void UE::Geometry::FMeshFaceSelection::ExpandToOneRingNeighbours (int nRings, const TUniqueFunction< bool(int)> & FilterF = nullptr)
Expand selection by N vertex one-rings.
This is significantly faster than calling ExpandToOnering() multiple times, because we can track the growing front and only check the new triangles.
Return false from FilterF to prevent triangles from being included.
FillEars()
bool UE::Geometry::FMeshFaceSelection::FillEars (bool bFillTinyHoles) inline
Definition at line 447 of file MeshFaceSelection.h.
References TArray< InElementType, InAllocatorType >::Add(), add(), is_ear(), IsSelected(), Mesh, TArray< InElementType, InAllocatorType >::Num(), and Selected.
Referenced by LocalOptimize().
FindBorderTris()
TArray< int > UE::Geometry::FMeshFaceSelection::FindBorderTris () const inline
find set of tris just inside border of selection
Definition at line 301 of file MeshFaceSelection.h.
References UE::Geometry::FIndex3i::A, TArray< InElementType, InAllocatorType >::Add(), UE::Geometry::FIndex3i::B, UE::Geometry::FIndex3i::C, IsSelected(), Mesh, and Selected.
FindNeighbourTris()
TArray< int > UE::Geometry::FMeshFaceSelection::FindNeighbourTris () const inline
find set of tris just outside border of selection
Definition at line 280 of file MeshFaceSelection.h.
References TArray< InElementType, InAllocatorType >::Add(), UE::Geometry::FDynamicMesh3::InvalidID, IsSelected(), Mesh, and Selected.
FloodFill() [1/2]
void UE::Geometry::FMeshFaceSelection::FloodFill (const TArray< int > & Seeds, const TUniqueFunction< bool(int)> & TriFilterF = nullptr, const TUniqueFunction< bool(int)> & EdgeFilterF = nullptr) inline
Grow selection outwards from seed triangles, until it hits boundaries defined by triangle and edge filters.
Edge filter is not effective unless it (possibly combined w/ triangle filter) defines closed loops.
Definition at line 389 of file MeshFaceSelection.h.
References UE::Geometry::TDynamicVector< Type, BlockSize >::Add(), add(), UE::Geometry::TDynamicVector< Type, BlockSize >::Back(), UE::Geometry::FDynamicMesh3::InvalidID, IsSelected(), Mesh, UE::Geometry::TDynamicVector< Type, BlockSize >::Num(), UE::Geometry::TDynamicVector< Type, BlockSize >::PopBack(), and Seed.
FloodFill() [2/2]
void UE::Geometry::FMeshFaceSelection::FloodFill (int tSeed, const TUniqueFunction< bool(int)> & TriFilterF = nullptr, const TUniqueFunction< bool(int)> & EdgeFilterF = nullptr) inline
Grow selection outwards from seed triangle, until it hits boundaries defined by triangle and edge filters.
Edge filter is not effective unless it (possibly combined w/ triangle filter) defines closed loops.
Definition at line 380 of file MeshFaceSelection.h.
References FloodFill().
Referenced by FloodFill().
is_bowtie_vtx()
bool UE::Geometry::FMeshFaceSelection::is_bowtie_vtx (int vid) const inline private
Definition at line 547 of file MeshFaceSelection.h.
References UE::Geometry::FIndex2i::A, UE::Geometry::FIndex2i::B, UE::Geometry::FDynamicMesh3::InvalidID, IsSelected(), and Mesh.
Referenced by remove_bowties().
is_ear()
bool UE::Geometry::FMeshFaceSelection::is_ear (int tid, bool include_tiny_holes) const inline private
Definition at line 594 of file MeshFaceSelection.h.
References count_nbrs(), and IsSelected().
Referenced by FillEars().
is_fin()
bool UE::Geometry::FMeshFaceSelection::is_fin (int tid, bool include_loners) const inline private
Definition at line 619 of file MeshFaceSelection.h.
References count_nbrs(), and IsSelected().
Referenced by ClipFins().
IsSelected()
bool UE::Geometry::FMeshFaceSelection::IsSelected (int tid) const inline
Definition at line 75 of file MeshFaceSelection.h.
References Selected.
Referenced by count_nbrs(), ExpandToFaceNeighbours(), FillEars(), FindBorderTris(), FindNeighbourTris(), FloodFill(), is_bowtie_vtx(), is_ear(), and is_fin().
IsSelectionBoundaryEdge()
TPair< bool, bool > UE::Geometry::FMeshFaceSelection::IsSelectionBoundaryEdge (int32 eid) const inline
Returns
pair (bIsSelectionBoundaryEdge, bIsMeshBoundaryEdge) for a given edge
Definition at line 258 of file MeshFaceSelection.h.
References UE::Geometry::FIndex2i::A, UE::Geometry::FIndex2i::B, IndexConstants::InvalidID, Mesh, and Selected.
LocalOptimize() [1/2]
bool UE::Geometry::FMeshFaceSelection::LocalOptimize (bool bClipFins, bool bFillEars, bool bFillTinyHoles = true, bool bClipLoners = true, bool bRemoveBowties = false) inline
Definition at line 475 of file MeshFaceSelection.h.
References ClipFins(), FillEars(), and remove_bowties().
Referenced by LocalOptimize().
LocalOptimize() [2/2]
bool UE::Geometry::FMeshFaceSelection::LocalOptimize (bool bRemoveBowties = true) inline
Definition at line 495 of file MeshFaceSelection.h.
References LocalOptimize().
Num()
int UE::Geometry::FMeshFaceSelection::Num () const inline
Definition at line 68 of file MeshFaceSelection.h.
References Selected.
remove()
void UE::Geometry::FMeshFaceSelection::remove (int tid) inline private
Definition at line 60 of file MeshFaceSelection.h.
References Selected.
Referenced by ClipFins(), Deselect(), Deselect(), Deselect(), and DeselectGroup().
remove_bowties()
bool UE::Geometry::FMeshFaceSelection::remove_bowties () inline
Definition at line 511 of file MeshFaceSelection.h.
References UE::Geometry::FIndex3i::A, TSet< InElementType, KeyFuncs, Allocator >::Add(), UE::Geometry::FIndex3i::B, UE::Geometry::FIndex3i::C, Deselect(), TSet< InElementType, KeyFuncs, Allocator >::Empty(), is_bowtie_vtx(), Mesh, and Selected.
Referenced by LocalOptimize(), and RemoveBowties().
RemoveBowties()
bool UE::Geometry::FMeshFaceSelection::RemoveBowties () inline
Find any "bowtie" vertices - ie vertex v such taht there is multiple spans of triangles selected in v's triangle one-ring - and deselect those one-rings.
Returns true if selection was modified.
Definition at line 508 of file MeshFaceSelection.h.
References remove_bowties().
Select() [1/3]
template<typename EnumerableType, typename E = decltype(DeclVal<EnumerableType>().begin())> void UE::Geometry::FMeshFaceSelection::Select (const EnumerableType & Enumerable) inline
Definition at line 95 of file MeshFaceSelection.h.
References add(), and Mesh.
Select() [2/3]
void UE::Geometry::FMeshFaceSelection::Select (int tid) inline
Definition at line 85 of file MeshFaceSelection.h.
References add(), ensure, and Mesh.
Select() [3/3]
void UE::Geometry::FMeshFaceSelection::Select (TFunctionRef< bool(int)> SelectF) inline
Definition at line 106 of file MeshFaceSelection.h.
References add(), and Mesh.
SelectEdgeTris()
void UE::Geometry::FMeshFaceSelection::SelectEdgeTris (int eid) inline
Definition at line 134 of file MeshFaceSelection.h.
References UE::Geometry::FIndex2i::A, add(), UE::Geometry::FIndex2i::B, UE::Geometry::FDynamicMesh3::InvalidID, and Mesh.
SelectGroup()
void UE::Geometry::FMeshFaceSelection::SelectGroup (int gid) inline
Definition at line 172 of file MeshFaceSelection.h.
References add(), and Mesh.
Referenced by FMeshFaceSelection().
SelectGroupInverse()
void UE::Geometry::FMeshFaceSelection::SelectGroupInverse (int gid) inline
Definition at line 183 of file MeshFaceSelection.h.
References add(), and Mesh.
SelectVertexOneRing()
void UE::Geometry::FMeshFaceSelection::SelectVertexOneRing (int vid) inline
Definition at line 119 of file MeshFaceSelection.h.
References add(), and Mesh.
Referenced by SelectVertexOneRings().
SelectVertexOneRings()
void UE::Geometry::FMeshFaceSelection::SelectVertexOneRings (TArrayView< const int > Vertices) inline
Definition at line 126 of file MeshFaceSelection.h.
References SelectVertexOneRing(), and UE::Geometry::Vertices.
SetDifference()
template<typename EnumerableType, typename StorageType> void UE::Geometry::FMeshFaceSelection::SetDifference (const EnumerableType & SubtractSet, StorageType & DifferenceStorage) const inline
Find the elements in current selection that are not in SubtractSet, and store in DifferenceStorage.
Definition at line 211 of file MeshFaceSelection.h.
References Selected.
SetIntersection()
template<typename EnumerableType, typename StorageType> void UE::Geometry::FMeshFaceSelection::SetIntersection (const EnumerableType & IntersectSet, StorageType & IntersectionStorage) const inline
Find the elements in current selection that are also in IntersectSet, and store in IntersectionStorage.
Definition at line 226 of file MeshFaceSelection.h.
References Selected.
Field Documentation
Mesh
const FDynamicMesh3* UE::Geometry::FMeshFaceSelection::Mesh private
Definition at line 23 of file MeshFaceSelection.h.
Referenced by FMeshFaceSelection(), FMeshFaceSelection(), AsBitArray(), count_nbrs(), DeselectGroup(), ExpandToFaceNeighbours(), FillEars(), FindBorderTris(), FindNeighbourTris(), FloodFill(), is_bowtie_vtx(), IsSelectionBoundaryEdge(), remove_bowties(), Select(), Select(), Select(), SelectEdgeTris(), SelectGroup(), SelectGroupInverse(), and SelectVertexOneRing().
Selected
TSet<int> UE::Geometry::FMeshFaceSelection::Selected private
Definition at line 25 of file MeshFaceSelection.h.
Referenced by add(), AsArray(), AsBitArray(), AsSet(), begin(), begin(), ClipFins(), Contains(), DeselectAll(), end(), end(), ExpandToFaceNeighbours(), FillEars(), FindBorderTris(), FindNeighbourTris(), IsSelected(), IsSelectionBoundaryEdge(), Num(), remove(), remove_bowties(), SetDifference(), and SetIntersection().
The documentation for this class was generated from the following file:
Runtime/GeometryCore/Public/Selections/MeshFaceSelection.h