Unreal Engine 5.6 C++ API: IReload Class Reference
IReload Class Reference abstract
Systems that implement a reload capability implement this interface and register it with the module manager while a reload is in progress.
#include "Reload.h"
Public Member Functions
virtual ~IReload ()=default
virtual bool GetEnableReinstancing (bool bHasChanged) const =0
Return if re-instancing is to be allowed.
virtual const TArray< UClass * > & GetNewClasses ()=0
Return an array of the new classes.
virtual const TCHAR * GetPrefix () const =0
When classes, structures, and enumerations are renamed, the given prefix is applied.
virtual const UObject * GetReinstancedCDO (const UObject *CDO)=0
virtual UObject * GetReinstancedCDO (UObject *CDO)=0
For a given CDO, return the new CDO if it has been re-instanced.
virtual const TMap< UClass *, UClass * > & GetReinstancedClasses ()=0
Return a map of the reinstanced classes where the old class is the key and the new class is the value.
virtual EActiveReloadType GetType () const =0
Returns the type of reload currently in progress.
virtual void NotifyChange (UClass *New, UClass *Old)=0
Invoke to register a new or changed class, enumeration, or structure for re-instancing.
virtual void NotifyChange (UEnum *New, UEnum *Old)=0
virtual void NotifyChange (UPackage *New, UPackage *Old)=0
virtual void NotifyChange (UScriptStruct *New, UScriptStruct *Old)=0
virtual void NotifyFunctionRemap (FNativeFuncPtr NewFunctionPointer, FNativeFuncPtr OldFunctionPointer)=0
Invoke when a duplicate function has been detected.
virtual void Reinstance ()=0
Perform the re-instancing.
Detailed Description
Systems that implement a reload capability implement this interface and register it with the module manager while a reload is in progress.
Definition at line 18 of file Reload.h.
Constructor & Destructor Documentation
~IReload()
virtual IReload::~IReload () virtual default
Member Function Documentation
GetEnableReinstancing()
virtual bool IReload::GetEnableReinstancing (bool bHasChanged) const pure virtual
Return if re-instancing is to be allowed.
Implemented in FReload.
GetNewClasses()
virtual const TArray< UClass * > & IReload::GetNewClasses () pure virtual
Return an array of the new classes.
Implemented in FReload.
GetPrefix()
virtual const TCHAR * IReload::GetPrefix () const pure virtual
When classes, structures, and enumerations are renamed, the given prefix is applied.
Implemented in FReload.
GetReinstancedCDO() [1/2]
virtual const UObject * IReload::GetReinstancedCDO (const UObject * CDO) pure virtual
Implemented in FReload.
GetReinstancedCDO() [2/2]
virtual UObject * IReload::GetReinstancedCDO (UObject * CDO) pure virtual
For a given CDO, return the new CDO if it has been re-instanced.
If it hasn't been re-instanced, then the supplied CDO will be returned. If a non-CDO object is passed in, it will be returned as is.
Implemented in FReload.
GetReinstancedClasses()
virtual const TMap< UClass *, UClass * > & IReload::GetReinstancedClasses () pure virtual
Return a map of the reinstanced classes where the old class is the key and the new class is the value.
Implemented in FReload.
GetType()
virtual EActiveReloadType IReload::GetType () const pure virtual
Returns the type of reload currently in progress.
Implemented in FReload.
NotifyChange() [1/4]
virtual void IReload::NotifyChange (UClass * New, UClass * Old) pure virtual
Invoke to register a new or changed class, enumeration, or structure for re-instancing.
Implemented in FReload.
References New().
NotifyChange() [2/4]
virtual void IReload::NotifyChange (UEnum * New, UEnum * Old) pure virtual
Implemented in FReload.
References New().
NotifyChange() [3/4]
virtual void IReload::NotifyChange (UPackage * New, UPackage * Old) pure virtual
Implemented in FReload.
References New().
NotifyChange() [4/4]
virtual void IReload::NotifyChange (UScriptStruct * New, UScriptStruct * Old) pure virtual
Implemented in FReload.
References New().
NotifyFunctionRemap()
virtual void IReload::NotifyFunctionRemap (FNativeFuncPtr NewFunctionPointer, FNativeFuncPtr OldFunctionPointer) pure virtual
Invoke when a duplicate function has been detected.
Implemented in FReload.
Reinstance()
virtual void IReload::Reinstance () pure virtual
Perform the re-instancing.
Implemented in FReload.
The documentation for this class was generated from the following file:
Runtime/CoreUObject/Public/UObject/Reload.h