Unreal Engine 5.6 C++ API: UE::UnifiedError::FRefCountedErrorDetails Class Reference
UE::UnifiedError::FRefCountedErrorDetails Class Reference
FRefCountedErrorDetails; base implementation of refcounting for IErrorDetails, this is used for heap allocated IErrorDetails implementations.
#include "UnifiedError.h"
Public Member Functions
virtual ~FRefCountedErrorDetails ()
virtual FReturnedRefCountValue AddRef () const final
virtual uint32 GetErrorDetailsTypeId () const
GetErrorDetialsTypeId; Simple type information for error details, generated using hash of details name See also: #define FERROR_DETAILS.
virtual const FAnsiStringView GetErrorDetailsTypeName () const override
virtual uint32 GetRefCount () const final
virtual uint32 Release () const final
Public Member Functions inherited from UE::UnifiedError::IErrorDetails
virtual ~IErrorDetails ()=default
virtual const FText GetErrorFormatString (const FError &Error) const =0
GetErrorFormatString; specifies the default error format string to be used when generating FError::GetErrorMessage.
virtual void GetErrorProperties (const FError &Error, IErrorPropertyExtractor &OutProperties) const =0
GetErrorProperties; used to expose error properties in name:value format, Error properties can be used for string formating functions, searching, exposing context to higher level stacks See also: FError::GetErrorMessage, IErrorDetails::GetErrorFormatString, FError::GetDetailByKey.
virtual TRefCountPtr< const IErrorDetails > GetInnerErrorDetails () const
GetInnerErrorDetails; Exposes inner error details to FError, if this ErrorDetails allows inner details.
virtual void SerializeForLog (FCbWriter &Writer) const
virtual void SetInnerErrorDetails (TRefCountPtr< const IErrorDetails > ErrorDetails)
SetInnerErrorDetails; Exposes inner error details to FError, if this ErrorDetails allows inner details.
Public Member Functions inherited from IRefCountedObject
virtual ~IRefCountedObject ()
Public Member Functions inherited from FRefCountBase
FRefCountBase ()=default
FRefCountBase (const FRefCountBase &Rhs)=delete
virtual ~FRefCountBase ()=default
FReturnedRefCountValue AddRef () const
uint32 GetRefCount () const
FRefCountBase & operator= (const FRefCountBase &Rhs)=delete
uint32 Release () const
Static Public Member Functions
static uint32 StaticGetErrorDetailsTypeId ()
Static Public Attributes
static const uint32 StaticDetailsTypeId = UE::UnifiedError::FErrorDetailsRegistry::Get().RegisterDetails(ANSITEXTVIEW("UnifiedError" "::" "FRefCountedErrorDetails"), nullptr)
Detailed Description
FRefCountedErrorDetails; base implementation of refcounting for IErrorDetails, this is used for heap allocated IErrorDetails implementations.
Definition at line 185 of file UnifiedError.h.
Constructor & Destructor Documentation
~FRefCountedErrorDetails()
virtual UE::UnifiedError::FRefCountedErrorDetails::~FRefCountedErrorDetails () virtual
Member Function Documentation
AddRef()
virtual FReturnedRefCountValue UE::UnifiedError::FRefCountedErrorDetails::AddRef () const inline final virtual
Implements IRefCountedObject.
Definition at line 192 of file UnifiedError.h.
References FRefCountBase::AddRef().
GetErrorDetailsTypeId()
virtual uint32 UE::UnifiedError::FRefCountedErrorDetails::GetErrorDetailsTypeId () const inline virtual
GetErrorDetialsTypeId; Simple type information for error details, generated using hash of details name See also: #define FERROR_DETAILS.
Returns
Implements UE::UnifiedError::IErrorDetails.
Reimplemented in UE::UnifiedError::FDynamicErrorDetails, and UE::UnifiedError::TErrorDetails< T >.
Definition at line 187 of file UnifiedError.h.
GetErrorDetailsTypeName()
virtual const FAnsiStringView UE::UnifiedError::FRefCountedErrorDetails::GetErrorDetailsTypeName () const inline override virtual
Implements UE::UnifiedError::IErrorDetails.
Reimplemented in UE::UnifiedError::FDynamicErrorDetails.
Definition at line 187 of file UnifiedError.h.
GetRefCount()
virtual uint32 UE::UnifiedError::FRefCountedErrorDetails::GetRefCount () const inline final virtual
Implements IRefCountedObject.
Definition at line 194 of file UnifiedError.h.
References FRefCountBase::GetRefCount().
Release()
virtual uint32 UE::UnifiedError::FRefCountedErrorDetails::Release () const inline final virtual
Implements IRefCountedObject.
Definition at line 193 of file UnifiedError.h.
References FRefCountBase::Release().
StaticGetErrorDetailsTypeId()
uint32 UE::UnifiedError::FRefCountedErrorDetails::StaticGetErrorDetailsTypeId () inline static
Definition at line 187 of file UnifiedError.h.
Field Documentation
StaticDetailsTypeId
const uint32 UE::UnifiedError::FRefCountedErrorDetails::StaticDetailsTypeId = UE::UnifiedError::FErrorDetailsRegistry::Get().RegisterDetails(ANSITEXTVIEW("UnifiedError" "::" "FRefCountedErrorDetails"), nullptr) inline static
Definition at line 187 of file UnifiedError.h.
The documentation for this class was generated from the following file:
Runtime/Core/Public/Experimental/UnifiedError/UnifiedError.h