Unreal Engine 5.6 C++ API: Metasound::TOutputNode< DataType, VertexAccess > Class Template Reference
Metasound::TOutputNode< DataType, VertexAccess > Class Template Reference
Output nodes are used to expose graph data to external entities.
#include "MetasoundOutputNode.h"
Public Member Functions
TOutputNode (const FVertexName &InInstanceName, const FGuid &InInstanceID, const FVertexName &InVertexName)
TOutputNode (const FVertexName &InVertexName, FNodeData InNodeData, TSharedRef< const FNodeClassMetadata > InClassMetadata)
Public Member Functions inherited from Metasound::FOutputNode
METASOUNDFRONTEND_API FOutputNode (const FVertexName &InVertexName, FNodeData InNodeData, TSharedRef< const FNodeClassMetadata > InClassMetadata)
virtual METASOUNDFRONTEND_API TSharedRef< IOperatorFactory, ESPMode::ThreadSafe > GetDefaultOperatorFactory () const override
Return a reference to the default operator factory.
Public Member Functions inherited from Metasound::FBasicNode
METASOUNDGRAPHCORE_API FBasicNode (FNodeData InNodeData, TSharedRef< const FNodeClassMetadata > InClassMetadata)
Construct a basic node.
virtual ~FBasicNode ()=default
virtual METASOUNDGRAPHCORE_API const FGuid & GetInstanceID () const override
Return the ID of this specific instance of the node class.
virtual METASOUNDGRAPHCORE_API const FName & GetInstanceName () const override
Return the name of this specific instance of the node class.
virtual METASOUNDGRAPHCORE_API const FNodeClassMetadata & GetMetadata () const override
Return metadata associated with this node.
virtual METASOUNDGRAPHCORE_API TSharedPtr< const IOperatorData > GetOperatorData () const override
Return the configuration for this node.
virtual METASOUNDGRAPHCORE_API const FVertexInterface & GetVertexInterface () const override
Return the interface associated with this node instance.
virtual METASOUNDGRAPHCORE_API void SetDefaultInput (const FVertexName &InVertexName, const FLiteral &InLiteral) override
Set the default literal for an input vertex.
Public Member Functions inherited from Metasound::INode
virtual ~INode ()
Public Member Functions inherited from Metasound::INodeBase
virtual ~INodeBase ()=default
UE_DEPRECATED (5.6, "INodeBase will not expose dynamic FVertexInterface operations") virtual bool IsVertexInterfaceSupported(const FVertexInterface &InInterface) const
Expresses whether a specific vertex interface is supported.
UE_DEPRECATED (5.6, "INodeBase will not expose dynamic FVertexInterface operations") virtual bool SetVertexInterface(const FVertexInterface &InInterface)
Set the vertex interface.
UE_EXPERIMENTAL (5.6, "Node operator data is still under development") virtual METASOUNDGRAPHCORE_API TSharedPtr< const IOperatorData > GetOperatorData() const
Returns the configuration for the node.
Additional Inherited Members
Static Public Member Functions inherited from Metasound::FOutputNode
static METASOUNDFRONTEND_API FNodeClassMetadata CreateNodeClassMetadata (const FVertexName &InVertexName, const FName &InDataTypeName, EVertexAccessType InVertexAccessType)
static METASOUNDFRONTEND_API FVertexInterface CreateVertexInterface (const FVertexName &InVertexName, const FName &InDataTypeName, EVertexAccessType InVertexAccessType)
static METASOUNDFRONTEND_API FName GetVariantName (EVertexAccessType InVertexAccessType)
Detailed Description
template<typename DataType, EVertexAccessType VertexAccess = EVertexAccessType::Reference>
class Metasound::TOutputNode< DataType, VertexAccess >
Output nodes are used to expose graph data to external entities.
Definition at line 73 of file MetasoundOutputNode.h.
Constructor & Destructor Documentation
TOutputNode() [1/2]
template<typename DataType, EVertexAccessType VertexAccess = EVertexAccessType::Reference> Metasound::TOutputNode< DataType, VertexAccess >::TOutputNode (const FVertexName & InInstanceName, const FGuid & InInstanceID, const FVertexName & InVertexName) inline
Definition at line 76 of file MetasoundOutputNode.h.
References Metasound::FOutputNode::FOutputNode(), TOutputNode(), Metasound::FOutputNode::CreateNodeClassMetadata(), Metasound::FOutputNode::CreateVertexInterface(), Metasound::GetMetasoundDataTypeName(), and MakeShared().
Referenced by TOutputNode().
TOutputNode() [2/2]
template<typename DataType, EVertexAccessType VertexAccess = EVertexAccessType::Reference> Metasound::TOutputNode< DataType, VertexAccess >::TOutputNode (const FVertexName & InVertexName, FNodeData InNodeData, TSharedRef< const FNodeClassMetadata > InClassMetadata) inline
Definition at line 81 of file MetasoundOutputNode.h.
References Metasound::FOutputNode::FOutputNode(), and MoveTemp().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/Metasound/Source/MetasoundFrontend/Public/MetasoundOutputNode.h