Unreal Engine 5.6 C++ API: UE::TLogTemplate< StorageType > Class Template Reference
UE::TLogTemplate< StorageType > Class Template Reference
A log template that is templated on its storage.
#include "StructuredLogFormat.h"
Public Member Functions
TLogTemplate (const FText &Format, const FLogTemplateOptions &Options={}, const Logging::Private::FLogField *Fields=nullptr, int32 FieldCount=0)
TLogTemplate (const TCHAR *Format, const FLogTemplateOptions &Options={}, const Logging::Private::FLogField *Fields=nullptr, int32 FieldCount=0)
TLogTemplate (const TCHAR *TextNamespace, const TCHAR *TextKey, const TCHAR *Format, const FLogTemplateOptions &Options={}, const Logging::Private::FLogField *Fields=nullptr, int32 FieldCount=0)
~TLogTemplate ()
FLogTemplate * Detach ()
void FormatTo (FUtf8StringBuilderBase &Out, const FCbFieldViewIterator &Fields)
void FormatTo (FWideStringBuilderBase &Out, const FCbFieldViewIterator &Fields)
FText FormatToText (const FCbFieldViewIterator &Fields)
FLogTemplate * Get () const
Private Member Functions
TLogTemplate ()=default
Private Attributes
StorageType Storage
Detailed Description
template<typename StorageType>
class UE::TLogTemplate< StorageType >
A log template that is templated on its storage.
Use FInlineLogTemplate or FSharedLogTemplate.
Definition at line 134 of file StructuredLogFormat.h.
Constructor & Destructor Documentation
TLogTemplate() [1/4]
template<typename StorageType> UE::TLogTemplate< StorageType >::TLogTemplate (const TCHAR * Format, const FLogTemplateOptions & Options = {}, const Logging::Private::FLogField * Fields = nullptr, int32 FieldCount = 0) inline explicit
Definition at line 137 of file StructuredLogFormat.h.
TLogTemplate() [2/4]
template<typename StorageType> UE::TLogTemplate< StorageType >::TLogTemplate (const FText & Format, const FLogTemplateOptions & Options = {}, const Logging::Private::FLogField * Fields = nullptr, int32 FieldCount = 0) inline explicit
Definition at line 142 of file StructuredLogFormat.h.
TLogTemplate() [3/4]
template<typename StorageType> UE::TLogTemplate< StorageType >::TLogTemplate (const TCHAR * TextNamespace, const TCHAR * TextKey, const TCHAR * Format, const FLogTemplateOptions & Options = {}, const Logging::Private::FLogField * Fields = nullptr, int32 FieldCount = 0) inline explicit
Definition at line 147 of file StructuredLogFormat.h.
~TLogTemplate()
template<typename StorageType> UE::TLogTemplate< StorageType >::~TLogTemplate () inline
Definition at line 167 of file StructuredLogFormat.h.
TLogTemplate() [4/4]
template<typename StorageType> UE::TLogTemplate< StorageType >::TLogTemplate () private default
Member Function Documentation
Detach()
template<typename StorageType> FLogTemplate * UE::TLogTemplate< StorageType >::Detach () inline
Definition at line 177 of file StructuredLogFormat.h.
FormatTo() [1/2]
template<typename StorageType> void UE::TLogTemplate< StorageType >::FormatTo (FUtf8StringBuilderBase & Out, const FCbFieldViewIterator & Fields) inline
Definition at line 152 of file StructuredLogFormat.h.
FormatTo() [2/2]
template<typename StorageType> void UE::TLogTemplate< StorageType >::FormatTo (FWideStringBuilderBase & Out, const FCbFieldViewIterator & Fields) inline
Definition at line 157 of file StructuredLogFormat.h.
FormatToText()
template<typename StorageType> FText UE::TLogTemplate< StorageType >::FormatToText (const FCbFieldViewIterator & Fields) inline
Definition at line 162 of file StructuredLogFormat.h.
Get()
template<typename StorageType> FLogTemplate * UE::TLogTemplate< StorageType >::Get () const inline
Definition at line 172 of file StructuredLogFormat.h.
Referenced by UE::TLogTemplate< Logging::Private::FInlineLogTemplateStorage >::~TLogTemplate(), UE::TLogTemplate< Logging::Private::FInlineLogTemplateStorage >::FormatTo(), UE::TLogTemplate< Logging::Private::FInlineLogTemplateStorage >::FormatTo(), and UE::TLogTemplate< Logging::Private::FInlineLogTemplateStorage >::FormatToText().
Field Documentation
Storage
template<typename StorageType> StorageType UE::TLogTemplate< StorageType >::Storage private
Definition at line 186 of file StructuredLogFormat.h.
The documentation for this class was generated from the following file:
Runtime/Core/Public/Logging/StructuredLogFormat.h