Unreal Engine 5.6 C++ API: FAssetThumbnailPool Class Reference
FAssetThumbnailPool Class Reference
Utility class for keeping track of, rendering, and recycling thumbnails rendered in Slate.
#include "AssetThumbnail.h"
Data Structures
struct FThumbId
Key for looking up thumbnails in a map.
struct FThumbnailInfo
Information about a thumbnail.
struct FThumbnailInfo_RenderThread
Public Member Functions
UNREALED_API FAssetThumbnailPool (uint32 InNumInPool, double InMaxFrameTimeAllowance=0.005, uint32 InMaxRealTimeThumbnailsPerFrame=3)
Constructor.
UNREALED_API ~FAssetThumbnailPool ()
Destructor to free all remaining resources.
FSlateTexture2DRHIRef * AccessTexture (const FAssetData &AssetData, uint32 Width, uint32 Height)
Accesses the texture for an object.
void AddReferencer (const FAssetThumbnail &AssetThumbnail)
Adds a referencer to keep textures around as long as they are needed.
DECLARE_EVENT_OneParam (FAssetThumbnailPool, FThumbnailRendered, const FAssetData &)
Register/Unregister a callback for when thumbnails are rendered.
DECLARE_EVENT_OneParam (FAssetThumbnailPool, FThumbnailRenderFailed, const FAssetData &)
Register/Unregister a callback for when thumbnails fail to render.
virtual UNREALED_API TStatId GetStatId () const override
Return the stat id used to track the performance of this object.
bool IsInRenderStack (const TSharedPtr< FAssetThumbnail > &Thumbnail) const
Returns true if the thumbnail for the specified asset in the specified size is in the stack of thumbnails to render.
bool IsRendered (const TSharedPtr< FAssetThumbnail > &Thumbnail) const
Returns true if the thumbnail for the specified asset in the specified size has been rendered.
virtual UNREALED_API bool IsTickable () const override
Checks if any new thumbnails are queued.
FThumbnailRendered & OnThumbnailRendered ()
FThumbnailRenderFailed & OnThumbnailRenderFailed ()
UNREALED_API void PrioritizeThumbnails (const TArray< TSharedPtr< FAssetThumbnail > > &ThumbnailsToPrioritize, uint32 Width, uint32 Height)
Brings all items in ThumbnailsToPrioritize to the front of the render stack if they are actually in the stack.
UNREALED_API void RefreshThumbnail (const TSharedPtr< FAssetThumbnail > &ThumbnailToRefresh)
Re-renders the specified thumbnail.
void RemoveReferencer (const FAssetThumbnail &AssetThumbnail)
Removes a referencer to clean up textures that are no longer needed.
UNREALED_API void SetRealTimeThumbnail (const TSharedPtr< FAssetThumbnail > &Thumbnail, bool bRealTimeThumbnail)
Enables/disables realtime thumbnail behavior.
virtual UNREALED_API void Tick (float DeltaTime) override
Ticks the pool, rendering new thumbnails as needed.
Public Member Functions inherited from FTickableEditorObject
FTickableEditorObject ()
Registers this instance with the static array of tickable objects.
virtual ~FTickableEditorObject ()
Removes this instance from the static array of tickable objects.
UE_NONCOPYABLE (FTickableEditorObject)
Public Member Functions inherited from FTickableObjectBase
virtual ETickableTickType GetTickableTickType () const
Virtual that can be overloaded by the inheriting class and is called before first tick.
UE_DEPRECATED (5.5, "Use IsTickable for conditional ticks and SetTickableTickType to change the tick type after initial registration") virtual bool IsAllowedToTick() const
Function called before IsTickable, used to change rules without breaking existing API.
Static Public Attributes
static UNREALED_API FName CustomThumbnailTagName
Private Member Functions
void FreeThumbnail (const FSoftObjectPath &ObjectPath, uint32 Width, uint32 Height)
Frees the rendering resources and clears a slot in the pool for an asset thumbnail at the specified width and height.
bool LoadThumbnail (TSharedRef< FThumbnailInfo > ThumbnailInfo, bool &bIsAssetStillCompiling, const FAssetData &CustomAssetToRender=FAssetData())
Assign a thumbnail from its render target and re-render it if necessary.
void OnAssetLoaded (UObject *Asset)
Handler for when an asset is loaded.
void OnThumbnailDirtied (const FSoftObjectPath &ObjectPath)
Handler for when a thumbnail gets flagged as dirty.
void RefreshThumbnailsFor (const FSoftObjectPath &ObjectPath)
Adds the thumbnails associated with the object found at ObjectPath to the render stack.
void ReleaseResources ()
Releases all rendering resources held by the pool.
Private Attributes
TAttribute< bool > AreRealTimeThumbnailsAllowed
Attribute that determines if real-time thumbnails are allowed.
bool bWereShadersCompilingLastFrame = false
Shaders are still building.
TArray< TSharedRef< FThumbnailInfo > > FreeThumbnails
List of free thumbnails that can be reused.
double MaxFrameTimeAllowance
Max number of seconds per tick to spend rendering thumbnails.
uint32 MaxRealTimeThumbnailsPerFrame
Max number of dynamic thumbnails to update per frame.
uint32 NumInPool
Max number of thumbnails in the pool.
TArray< TSharedRef< FThumbnailInfo > > RealTimeThumbnails
List of thumbnails that can be rendered in real-time.
TArray< TSharedRef< FThumbnailInfo > > RealTimeThumbnailsToRender
List of real-time thumbnails that are queued to be rendered.
TArray< FSoftObjectPath > RecentlyLoadedAssets
A list of object paths for recently loaded assets whose thumbnails need to be refreshed.
TMap< FThumbId, int32 > RefCountMap
A mapping of objects to the number of referencers.
FThumbnailRendered ThumbnailRenderedEvent
The delegate to execute when a thumbnail is rendered.
FThumbnailRenderFailed ThumbnailRenderFailedEvent
The delegate to execute when a thumbnail failed to render.
TArray< TSharedRef< FThumbnailInfo > > ThumbnailsToRenderStack
List of thumbnails to render when possible.
TMap< FThumbId, TSharedRef< FThumbnailInfo > > ThumbnailToTextureMap
A mapping of objects to their thumbnails.
Additional Inherited Members
Static Public Member Functions inherited from FTickableEditorObject
static void TickObjects (const float DeltaSeconds)
Calls Tick on every tickable editor object with tick enabled.
Static Protected Member Functions inherited from FTickableObjectBase
static void SimpleTickObjects (FTickableStatics &Statics, TFunctionRef< void(FTickableObjectBase *)> TickFunc)
Perform a simple tick using a class-specific statics struct and a function ref.
Detailed Description
Utility class for keeping track of, rendering, and recycling thumbnails rendered in Slate.
Definition at line 221 of file AssetThumbnail.h.
Constructor & Destructor Documentation
FAssetThumbnailPool()
UNREALED_API FAssetThumbnailPool::FAssetThumbnailPool (uint32 InNumInPool, double InMaxFrameTimeAllowance = 0.005, uint32 InMaxRealTimeThumbnailsPerFrame = 3)
Constructor.
Parameters
InNumInPool The number of thumbnails allowed in the pool
InAreRealTimeThumbnailsAllowed Attribute that determines if thumbnails should be rendered in real-time
InMaxFrameTimeAllowance The maximum number of seconds per tick to spend rendering thumbnails
InMaxRealTimeThumbnailsPerFrame The maximum number of real-time thumbnails to render per tick
Referenced by DECLARE_EVENT_OneParam(), and DECLARE_EVENT_OneParam().
~FAssetThumbnailPool()
UNREALED_API FAssetThumbnailPool::~FAssetThumbnailPool ()
Destructor to free all remaining resources.
Member Function Documentation
AccessTexture()
FSlateTexture2DRHIRef * FAssetThumbnailPool::AccessTexture (const FAssetData & AssetData, uint32 Width, uint32 Height)
Accesses the texture for an object.
If a thumbnail was recently rendered this function simply returns the thumbnail. If it was not, it requests a new one be generated No assumptions should be made about whether or not it was rendered
Parameters
Asset The asset to get the thumbnail for
Width The width of the thumbnail
Height The height of the thumbnail
Returns
The thumbnail for the asset or NULL if one could not be produced
References Width.
AddReferencer()
void FAssetThumbnailPool::AddReferencer (const FAssetThumbnail & AssetThumbnail)
Adds a referencer to keep textures around as long as they are needed.
DECLARE_EVENT_OneParam() [1/2]
FAssetThumbnailPool::DECLARE_EVENT_OneParam (FAssetThumbnailPool , FThumbnailRendered , const FAssetData &)
Register/Unregister a callback for when thumbnails are rendered.
References FAssetThumbnailPool().
DECLARE_EVENT_OneParam() [2/2]
FAssetThumbnailPool::DECLARE_EVENT_OneParam (FAssetThumbnailPool , FThumbnailRenderFailed , const FAssetData &)
Register/Unregister a callback for when thumbnails fail to render.
References FAssetThumbnailPool().
FreeThumbnail()
void FAssetThumbnailPool::FreeThumbnail (const FSoftObjectPath & ObjectPath, uint32 Width, uint32 Height) private
Frees the rendering resources and clears a slot in the pool for an asset thumbnail at the specified width and height.
Parameters
ObjectPath The path to the asset whose thumbnail should be free
Width The width of the thumbnail to free
Height The height of the thumbnail to free
References Width.
GetStatId()
virtual UNREALED_API TStatId FAssetThumbnailPool::GetStatId () const override virtual
Return the stat id used to track the performance of this object.
Implements FTickableObjectBase.
IsInRenderStack()
bool FAssetThumbnailPool::IsInRenderStack (const TSharedPtr< FAssetThumbnail > & Thumbnail) const
Returns true if the thumbnail for the specified asset in the specified size is in the stack of thumbnails to render.
IsRendered()
bool FAssetThumbnailPool::IsRendered (const TSharedPtr< FAssetThumbnail > & Thumbnail) const
Returns true if the thumbnail for the specified asset in the specified size has been rendered.
IsTickable()
virtual UNREALED_API bool FAssetThumbnailPool::IsTickable () const override virtual
Checks if any new thumbnails are queued.
Reimplemented from FTickableObjectBase.
LoadThumbnail()
bool FAssetThumbnailPool::LoadThumbnail (TSharedRef< FThumbnailInfo > ThumbnailInfo, bool & bIsAssetStillCompiling, const FAssetData & CustomAssetToRender = FAssetData()) private
Assign a thumbnail from its render target and re-render it if necessary.
Parameters
ThumbnailInfo The thumbnail info to assign a texture to
bIsAssetStillCompiling If the asset we want to load the thumbnail is compiling, this flag will be set to true, it wont be touch in other cases.
CustomAssetToRender The asset to render when generating the texture
Returns
true if the thumbnail was assigned to a valid texture
OnAssetLoaded()
void FAssetThumbnailPool::OnAssetLoaded (UObject * Asset) private
Handler for when an asset is loaded.
References Asset.
OnThumbnailDirtied()
void FAssetThumbnailPool::OnThumbnailDirtied (const FSoftObjectPath & ObjectPath) private
Handler for when a thumbnail gets flagged as dirty.
Used to refresh the thumbnail.
OnThumbnailRendered()
FThumbnailRendered & FAssetThumbnailPool::OnThumbnailRendered () inline
Definition at line 282 of file AssetThumbnail.h.
References ThumbnailRenderedEvent.
OnThumbnailRenderFailed()
FThumbnailRenderFailed & FAssetThumbnailPool::OnThumbnailRenderFailed () inline
Definition at line 286 of file AssetThumbnail.h.
References ThumbnailRenderFailedEvent.
PrioritizeThumbnails()
UNREALED_API void FAssetThumbnailPool::PrioritizeThumbnails (const TArray< TSharedPtr< FAssetThumbnail > > & ThumbnailsToPrioritize, uint32 Width, uint32 Height)
Brings all items in ThumbnailsToPrioritize to the front of the render stack if they are actually in the stack.
References Width.
RefreshThumbnail()
UNREALED_API void FAssetThumbnailPool::RefreshThumbnail (const TSharedPtr< FAssetThumbnail > & ThumbnailToRefresh)
Re-renders the specified thumbnail.
RefreshThumbnailsFor()
void FAssetThumbnailPool::RefreshThumbnailsFor (const FSoftObjectPath & ObjectPath) private
Adds the thumbnails associated with the object found at ObjectPath to the render stack.
ReleaseResources()
void FAssetThumbnailPool::ReleaseResources () private
Releases all rendering resources held by the pool.
RemoveReferencer()
void FAssetThumbnailPool::RemoveReferencer (const FAssetThumbnail & AssetThumbnail)
Removes a referencer to clean up textures that are no longer needed.
SetRealTimeThumbnail()
UNREALED_API void FAssetThumbnailPool::SetRealTimeThumbnail (const TSharedPtr< FAssetThumbnail > & Thumbnail, bool bRealTimeThumbnail)
Enables/disables realtime thumbnail behavior.
Tick()
virtual UNREALED_API void FAssetThumbnailPool::Tick (float DeltaTime) override virtual
Ticks the pool, rendering new thumbnails as needed.
Implements FTickableObjectBase.
References DeltaTime.
Field Documentation
AreRealTimeThumbnailsAllowed
TAttribute<bool> FAssetThumbnailPool::AreRealTimeThumbnailsAllowed private
Attribute that determines if real-time thumbnails are allowed.
Called every frame.
Definition at line 420 of file AssetThumbnail.h.
bWereShadersCompilingLastFrame
bool FAssetThumbnailPool::bWereShadersCompilingLastFrame = false private
Shaders are still building.
Definition at line 426 of file AssetThumbnail.h.
CustomThumbnailTagName
UNREALED_API FName FAssetThumbnailPool::CustomThumbnailTagName static
Definition at line 224 of file AssetThumbnail.h.
FreeThumbnails
TArray< TSharedRef<FThumbnailInfo> > FAssetThumbnailPool::FreeThumbnails private
List of free thumbnails that can be reused.
Definition at line 411 of file AssetThumbnail.h.
MaxFrameTimeAllowance
double FAssetThumbnailPool::MaxFrameTimeAllowance private
Max number of seconds per tick to spend rendering thumbnails.
Definition at line 432 of file AssetThumbnail.h.
MaxRealTimeThumbnailsPerFrame
uint32 FAssetThumbnailPool::MaxRealTimeThumbnailsPerFrame private
Max number of dynamic thumbnails to update per frame.
Definition at line 429 of file AssetThumbnail.h.
NumInPool
uint32 FAssetThumbnailPool::NumInPool private
Max number of thumbnails in the pool.
Definition at line 423 of file AssetThumbnail.h.
RealTimeThumbnails
TArray< TSharedRef<FThumbnailInfo> > FAssetThumbnailPool::RealTimeThumbnails private
List of thumbnails that can be rendered in real-time.
Definition at line 405 of file AssetThumbnail.h.
RealTimeThumbnailsToRender
TArray< TSharedRef<FThumbnailInfo> > FAssetThumbnailPool::RealTimeThumbnailsToRender private
List of real-time thumbnails that are queued to be rendered.
Definition at line 408 of file AssetThumbnail.h.
RecentlyLoadedAssets
TArray<FSoftObjectPath> FAssetThumbnailPool::RecentlyLoadedAssets private
A list of object paths for recently loaded assets whose thumbnails need to be refreshed.
Definition at line 417 of file AssetThumbnail.h.
RefCountMap
TMap< FThumbId, int32 > FAssetThumbnailPool::RefCountMap private
A mapping of objects to the number of referencers.
Definition at line 414 of file AssetThumbnail.h.
ThumbnailRenderedEvent
FThumbnailRendered FAssetThumbnailPool::ThumbnailRenderedEvent private
The delegate to execute when a thumbnail is rendered.
Definition at line 393 of file AssetThumbnail.h.
Referenced by OnThumbnailRendered().
ThumbnailRenderFailedEvent
FThumbnailRenderFailed FAssetThumbnailPool::ThumbnailRenderFailedEvent private
The delegate to execute when a thumbnail failed to render.
Definition at line 396 of file AssetThumbnail.h.
Referenced by OnThumbnailRenderFailed().
ThumbnailsToRenderStack
TArray< TSharedRef<FThumbnailInfo> > FAssetThumbnailPool::ThumbnailsToRenderStack private
List of thumbnails to render when possible.
Definition at line 402 of file AssetThumbnail.h.
ThumbnailToTextureMap
TMap< FThumbId, TSharedRef<FThumbnailInfo> > FAssetThumbnailPool::ThumbnailToTextureMap private
A mapping of objects to their thumbnails.
Definition at line 399 of file AssetThumbnail.h.
The documentation for this class was generated from the following file:
Editor/UnrealEd/Public/AssetThumbnail.h