Unreal Engine 5.6 C++ API: UE::Tasks::TaskConcurrencyLimiter_Private::FPimpl Class Reference
UE::Tasks::TaskConcurrencyLimiter_Private::FPimpl Class Reference
#include "TaskConcurrencyLimiter.h"
Public Member Functions
FPimpl (uint32 InMaxConcurrency, ETaskPriority InTaskPriority)
~FPimpl ()
template<typename TaskFunctionType>
void Push (const TCHAR *DebugName, TaskFunctionType &&TaskFunction)
bool Wait (FTimespan Timeout)
Public Member Functions inherited from TSharedFromThis< FPimpl >
TSharedRef< FPimpl, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FPimpl, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Private Member Functions
void AddWorkItem (LowLevelTasks::FTask *Task)
void CompleteWorkItem (uint32 ConcurrencySlot)
void ProcessQueue (uint32 ConcurrencySlot, bool bSkipFirstWakeUp)
void ProcessQueueFromPush (uint32 ConcurrencySlot)
void ProcessQueueFromWorker (uint32 ConcurrencySlot)
Private Attributes
std::atomic< FEvent * > CompletionEvent { nullptr }
FConcurrencySlots ConcurrencySlots
std::atomic< uint32 > NumWorkItems { 0 }
ETaskPriority TaskPriority
TLockFreePointerListFIFO< LowLevelTasks::FTask, PLATFORM_CACHE_LINE_SIZE > WorkQueue
Additional Inherited Members
Protected Member Functions inherited from TSharedFromThis< FPimpl >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions inherited from TSharedFromThis< FPimpl >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
Definition at line 54 of file TaskConcurrencyLimiter.h.
Constructor & Destructor Documentation
FPimpl()
UE::Tasks::TaskConcurrencyLimiter_Private::FPimpl::FPimpl (uint32 InMaxConcurrency, ETaskPriority InTaskPriority) inline explicit
Definition at line 57 of file TaskConcurrencyLimiter.h.
References ConcurrencySlots, and TaskPriority.
~FPimpl()
UE::Tasks::TaskConcurrencyLimiter_Private::FPimpl::~FPimpl ()
Member Function Documentation
AddWorkItem()
void UE::Tasks::TaskConcurrencyLimiter_Private::FPimpl::AddWorkItem (LowLevelTasks::FTask * Task) private
Referenced by Push().
CompleteWorkItem()
void UE::Tasks::TaskConcurrencyLimiter_Private::FPimpl::CompleteWorkItem (uint32 ConcurrencySlot) private
Referenced by Push().
ProcessQueue()
void UE::Tasks::TaskConcurrencyLimiter_Private::FPimpl::ProcessQueue (uint32 ConcurrencySlot, bool bSkipFirstWakeUp) private
ProcessQueueFromPush()
void UE::Tasks::TaskConcurrencyLimiter_Private::FPimpl::ProcessQueueFromPush (uint32 ConcurrencySlot) private
ProcessQueueFromWorker()
void UE::Tasks::TaskConcurrencyLimiter_Private::FPimpl::ProcessQueueFromWorker (uint32 ConcurrencySlot) private
Push()
template<typename TaskFunctionType> void UE::Tasks::TaskConcurrencyLimiter_Private::FPimpl::Push (const TCHAR * DebugName, TaskFunctionType && TaskFunction) inline
Definition at line 66 of file TaskConcurrencyLimiter.h.
References AddWorkItem(), TSharedFromThis< ObjectType, Mode >::AsShared(), CompleteWorkItem(), TSharedPtr< ObjectType, InMode >::Get(), MakeShared(), MoveTemp(), and TaskPriority.
Wait()
bool UE::Tasks::TaskConcurrencyLimiter_Private::FPimpl::Wait (FTimespan Timeout)
References UE::Tasks::Timeout.
Field Documentation
CompletionEvent
std::atomic<FEvent*> UE::Tasks::TaskConcurrencyLimiter_Private::FPimpl::CompletionEvent { nullptr } private
Definition at line 106 of file TaskConcurrencyLimiter.h.
ConcurrencySlots
FConcurrencySlots UE::Tasks::TaskConcurrencyLimiter_Private::FPimpl::ConcurrencySlots private
Definition at line 102 of file TaskConcurrencyLimiter.h.
Referenced by FPimpl().
NumWorkItems
std::atomic<uint32> UE::Tasks::TaskConcurrencyLimiter_Private::FPimpl::NumWorkItems { 0 } private
Definition at line 105 of file TaskConcurrencyLimiter.h.
TaskPriority
ETaskPriority UE::Tasks::TaskConcurrencyLimiter_Private::FPimpl::TaskPriority private
Definition at line 103 of file TaskConcurrencyLimiter.h.
Referenced by FPimpl(), and Push().
WorkQueue
TLockFreePointerListFIFO<LowLevelTasks::FTask, PLATFORM_CACHE_LINE_SIZE> UE::Tasks::TaskConcurrencyLimiter_Private::FPimpl::WorkQueue private
Definition at line 104 of file TaskConcurrencyLimiter.h.
The documentation for this class was generated from the following file:
Runtime/Core/Public/Tasks/TaskConcurrencyLimiter.h