Unreal Engine 5.6 C++ API: FStreamingGenerationActorDescView Class Reference
FStreamingGenerationActorDescView Class Reference
#include "WorldPartitionStreamingGeneration.h"
Data Structures
struct FInvalidReference
Public Member Functions
FStreamingGenerationActorDescView (const FStreamingGenerationActorDescViewMap &InActorDescViewMap, const FWorldPartitionActorDescInstance *InActorDescInstance, bool bInUnsaved=false)
virtual ~FStreamingGenerationActorDescView ()
void AddForcedInvalidReference (const FStreamingGenerationActorDescView *ReferenceView)
const FStreamingGenerationActorDescViewMap & GetActorDescViewMap () const
virtual bool GetActorIsHLODRelevant () const override
virtual const FDataLayerInstanceNames & GetDataLayerInstanceNames () const override
FTransform GetEditorOnlyParentTransform () const
const TArray< FGuid > & GetEditorReferences () const
virtual FSoftObjectPath GetHLODLayer () const override
const FInvalidReference * GetInvalidReference (const FGuid &InGuid) const
virtual bool GetIsSpatiallyLoaded () const override
virtual const TArray< FGuid > & GetReferences () const override
const FDataLayerInstanceNames & GetRuntimeDataLayerInstanceNames () const
virtual FName GetRuntimeGrid () const override
virtual bool IsEditorOnlyReference (const FGuid &ReferenceGuid) const override
bool IsUnsaved () const
bool operator== (const FStreamingGenerationActorDescView &Other) const
void SetDataLayerInstanceNames (const FDataLayerInstanceNames &InDataLayerInstanceNames)
void SetEditorOnlyParentTransform (const FTransform &InEditorOnlyParentTransform)
void SetEditorReferences (const TArray< FGuid > &InEditorReferences)
void SetForcedHLODIrrelevant ()
void SetForcedNoDataLayers ()
void SetForcedNoHLODLayer ()
void SetForcedNonSpatiallyLoaded ()
void SetForcedNoRuntimeGrid ()
void SetParentView (const FStreamingGenerationActorDescView *InParentView)
void SetRuntimeDataLayerInstanceNames (const FDataLayerInstanceNames &InRuntimeDataLayerInstanceNames)
void SetRuntimeGrid (FName InRuntimeGrid)
void SetRuntimeHLODLayer (const FSoftObjectPath &InHLODLayer)
void SetRuntimeReferences (const TArray< FGuid > &InRuntimeReferences)
virtual FString ToString (FWorldPartitionActorDesc::EToStringMode Mode) const override
Public Member Functions inherited from FWorldPartitionActorDescInstanceView
FWorldPartitionActorDescInstanceView (const FWorldPartitionActorDescInstance *InActorDescInstance)
virtual void CheckForErrors (IStreamingGenerationErrorHandler *ErrorHandler) const override
virtual AActor * GetActor (bool bEvenIfPendingKill=true, bool bEvenIfUnreachable=false) const override
virtual const FWorldPartitionActorDesc * GetActorDesc () const override
virtual bool GetActorIsEditorOnly () const override
virtual bool GetActorIsEditorOnlyLoadedInPIE () const override
virtual bool GetActorIsRuntimeOnly () const override
virtual FName GetActorLabel () const override
virtual FName GetActorName () const override
virtual UClass * GetActorNativeClass () const override
virtual FName GetActorPackage () const override
virtual FSoftObjectPath GetActorSoftPath () const override
virtual FTopLevelAssetPath GetBaseClass () const override
virtual const FWorldPartitionActorFilter * GetChildContainerFilter () const override
virtual EWorldPartitionActorFilterType GetChildContainerFilterType () const override
virtual bool GetChildContainerInstance (FWorldPartitionActorDesc::FContainerInstance &OutContainerInstance) const override
virtual FName GetChildContainerPackage () const override
virtual UActorDescContainerInstance * GetContainerInstance () const override
virtual FGuid GetContentBundleGuid () const override
const FDataLayerInstanceNames & GetDataLayerInstanceNames () const override
virtual TArray< FName > GetDataLayers () const override
virtual FBox GetEditorBounds () const override
virtual const TArray< FGuid > & GetEditorOnlyReferences () const override
virtual const FSoftObjectPath & GetExternalDataLayerAsset () const override
virtual const FGuid & GetFolderGuid () const override
virtual FName GetFolderPath () const override
virtual const FGuid & GetGuid () const override
virtual FTopLevelAssetPath GetNativeClass () const override
virtual const FGuid & GetParentActor () const override
virtual bool GetProperty (FName PropertyName, FName *PropertyValue) const override
virtual FBox GetRuntimeBounds () const override
virtual const FGuid & GetSceneOutlinerParent () const override
virtual const TArray< FName > & GetTags () const override
virtual bool HasProperty (FName PropertyName) const override
virtual bool HasResolvedDataLayerInstanceNames () const override
virtual bool IsChildContainerInstance () const override
virtual bool IsEditorRelevant () const override
virtual bool IsListedInSceneOutliner () const override
virtual bool IsLoaded (bool bEvenIfPendingKill=false) const override
virtual bool IsMainWorldOnly () const override
virtual bool IsRuntimeRelevant () const override
virtual bool IsUsingDataLayerAsset () const override
Public Member Functions inherited from IWorldPartitionActorDescInstanceView
virtual ~IWorldPartitionActorDescInstanceView ()
virtual FName GetActorLabelOrName () const
Protected Member Functions
FStreamingGenerationActorDescView (const FWorldPartitionActorDescInstance *InActorDescInstance)
Private Types
typedef FWorldPartitionActorDescInstanceView Super
Private Attributes
const FStreamingGenerationActorDescViewMap * ActorDescViewMap
bool bIsForcedHLODIrrelevant
bool bIsForcedNoDataLayers
bool bIsForcedNonSpatiallyLoaded
bool bIsForcedNoRuntimeGrid
bool bIsForceNoHLODLayer
bool bIsUnsaved
TOptional< FTransform > EditorOnlyParentTransform
TArray< FGuid > EditorReferences
TMap< FGuid, FInvalidReference > ForcedInvalidReference
FDataLayerInstanceNames LastReturnedDataLayerInstanceNames
const FStreamingGenerationActorDescView * ParentView
TOptional< FDataLayerInstanceNames > ResolvedDataLayerInstanceNames
TOptional< FName > ResolvedRuntimeGrid
TOptional< FDataLayerInstanceNames > RuntimeDataLayerInstanceNames
TOptional< FSoftObjectPath > RuntimeHLODLayer
TOptional< TArray< FGuid > > RuntimeReferences
Friends
class FStreamingGenerationActorDescViewMap
class FWorldPartitionStreamingGenerator
uint32 GetTypeHash (const FStreamingGenerationActorDescView &Key)
Detailed Description
Definition at line 17 of file WorldPartitionStreamingGeneration.h.
Member Typedef Documentation
Super
typedef FWorldPartitionActorDescInstanceView FStreamingGenerationActorDescView::Super private
Definition at line 19 of file WorldPartitionStreamingGeneration.h.
Constructor & Destructor Documentation
FStreamingGenerationActorDescView() [1/2]
FStreamingGenerationActorDescView::FStreamingGenerationActorDescView (const FWorldPartitionActorDescInstance * InActorDescInstance) inline protected
Definition at line 26 of file WorldPartitionStreamingGeneration.h.
References FWorldPartitionActorDescInstanceView::FWorldPartitionActorDescInstanceView(), ActorDescViewMap, bIsForcedHLODIrrelevant, bIsForcedNoDataLayers, bIsForcedNonSpatiallyLoaded, bIsForcedNoRuntimeGrid, bIsForceNoHLODLayer, bIsUnsaved, and ParentView.
Referenced by FStreamingGenerationActorDescView(), AddForcedInvalidReference(), GetTypeHash, operator==(), and SetParentView().
FStreamingGenerationActorDescView() [2/2]
FStreamingGenerationActorDescView::FStreamingGenerationActorDescView (const FStreamingGenerationActorDescViewMap & InActorDescViewMap, const FWorldPartitionActorDescInstance * InActorDescInstance, bool bInUnsaved = false) inline
Definition at line 47 of file WorldPartitionStreamingGeneration.h.
References FStreamingGenerationActorDescView(), ActorDescViewMap, bIsUnsaved, and FStreamingGenerationActorDescViewMap.
~FStreamingGenerationActorDescView()
virtual FStreamingGenerationActorDescView::~FStreamingGenerationActorDescView () inline virtual
Definition at line 54 of file WorldPartitionStreamingGeneration.h.
Member Function Documentation
AddForcedInvalidReference()
void FStreamingGenerationActorDescView::AddForcedInvalidReference (const FStreamingGenerationActorDescView * ReferenceView)
References FStreamingGenerationActorDescView().
GetActorDescViewMap()
const FStreamingGenerationActorDescViewMap & FStreamingGenerationActorDescView::GetActorDescViewMap () const inline
Definition at line 68 of file WorldPartitionStreamingGeneration.h.
References ActorDescViewMap, and FStreamingGenerationActorDescViewMap.
GetActorIsHLODRelevant()
virtual bool FStreamingGenerationActorDescView::GetActorIsHLODRelevant () const override virtual
Reimplemented from FWorldPartitionActorDescInstanceView.
GetDataLayerInstanceNames()
virtual const FDataLayerInstanceNames & FStreamingGenerationActorDescView::GetDataLayerInstanceNames () const override virtual
Implements IWorldPartitionActorDescInstanceView.
GetEditorOnlyParentTransform()
FTransform FStreamingGenerationActorDescView::GetEditorOnlyParentTransform () const inline
Definition at line 85 of file WorldPartitionStreamingGeneration.h.
References EditorOnlyParentTransform, and UE::Math::TTransform< double >::Identity.
GetEditorReferences()
const TArray< FGuid > & FStreamingGenerationActorDescView::GetEditorReferences () const
GetHLODLayer()
virtual FSoftObjectPath FStreamingGenerationActorDescView::GetHLODLayer () const override virtual
Reimplemented from FWorldPartitionActorDescInstanceView.
GetInvalidReference()
const FInvalidReference * FStreamingGenerationActorDescView::GetInvalidReference (const FGuid & InGuid) const
GetIsSpatiallyLoaded()
virtual bool FStreamingGenerationActorDescView::GetIsSpatiallyLoaded () const override virtual
Reimplemented from FWorldPartitionActorDescInstanceView.
GetReferences()
virtual const TArray< FGuid > & FStreamingGenerationActorDescView::GetReferences () const override virtual
Reimplemented from FWorldPartitionActorDescInstanceView.
GetRuntimeDataLayerInstanceNames()
const FDataLayerInstanceNames & FStreamingGenerationActorDescView::GetRuntimeDataLayerInstanceNames () const
GetRuntimeGrid()
virtual FName FStreamingGenerationActorDescView::GetRuntimeGrid () const override virtual
Reimplemented from FWorldPartitionActorDescInstanceView.
IsEditorOnlyReference()
virtual bool FStreamingGenerationActorDescView::IsEditorOnlyReference (const FGuid & ReferenceGuid) const override virtual
Reimplemented from FWorldPartitionActorDescInstanceView.
IsUnsaved()
bool FStreamingGenerationActorDescView::IsUnsaved () const inline
Definition at line 67 of file WorldPartitionStreamingGeneration.h.
References bIsUnsaved.
operator==()
bool FStreamingGenerationActorDescView::operator== (const FStreamingGenerationActorDescView & Other) const inline
Definition at line 91 of file WorldPartitionStreamingGeneration.h.
References FStreamingGenerationActorDescView(), FWorldPartitionActorDescInstanceView::GetGuid(), and Other.
SetDataLayerInstanceNames()
void FStreamingGenerationActorDescView::SetDataLayerInstanceNames (const FDataLayerInstanceNames & InDataLayerInstanceNames)
SetEditorOnlyParentTransform()
void FStreamingGenerationActorDescView::SetEditorOnlyParentTransform (const FTransform & InEditorOnlyParentTransform)
SetEditorReferences()
void FStreamingGenerationActorDescView::SetEditorReferences (const TArray< FGuid > & InEditorReferences)
SetForcedHLODIrrelevant()
void FStreamingGenerationActorDescView::SetForcedHLODIrrelevant ()
SetForcedNoDataLayers()
void FStreamingGenerationActorDescView::SetForcedNoDataLayers ()
SetForcedNoHLODLayer()
void FStreamingGenerationActorDescView::SetForcedNoHLODLayer ()
SetForcedNonSpatiallyLoaded()
void FStreamingGenerationActorDescView::SetForcedNonSpatiallyLoaded ()
SetForcedNoRuntimeGrid()
void FStreamingGenerationActorDescView::SetForcedNoRuntimeGrid ()
SetParentView()
void FStreamingGenerationActorDescView::SetParentView (const FStreamingGenerationActorDescView * InParentView)
References FStreamingGenerationActorDescView().
SetRuntimeDataLayerInstanceNames()
void FStreamingGenerationActorDescView::SetRuntimeDataLayerInstanceNames (const FDataLayerInstanceNames & InRuntimeDataLayerInstanceNames)
SetRuntimeGrid()
void FStreamingGenerationActorDescView::SetRuntimeGrid (FName InRuntimeGrid)
SetRuntimeHLODLayer()
void FStreamingGenerationActorDescView::SetRuntimeHLODLayer (const FSoftObjectPath & InHLODLayer)
SetRuntimeReferences()
void FStreamingGenerationActorDescView::SetRuntimeReferences (const TArray< FGuid > & InRuntimeReferences)
ToString()
virtual FString FStreamingGenerationActorDescView::ToString (FWorldPartitionActorDesc::EToStringMode Mode) const override virtual
Reimplemented from FWorldPartitionActorDescInstanceView.
Friends And Related Symbol Documentation
FStreamingGenerationActorDescViewMap
friend class FStreamingGenerationActorDescViewMap friend
Definition at line 21 of file WorldPartitionStreamingGeneration.h.
References FStreamingGenerationActorDescViewMap.
Referenced by FStreamingGenerationActorDescView(), FStreamingGenerationActorDescViewMap, and GetActorDescViewMap().
FWorldPartitionStreamingGenerator
friend class FWorldPartitionStreamingGenerator friend
Definition at line 22 of file WorldPartitionStreamingGeneration.h.
References FWorldPartitionStreamingGenerator.
Referenced by FWorldPartitionStreamingGenerator.
GetTypeHash
uint32 GetTypeHash (const FStreamingGenerationActorDescView & Key) friend
Definition at line 96 of file WorldPartitionStreamingGeneration.h.
References FStreamingGenerationActorDescView(), GetTypeHash, and Key.
Referenced by GetTypeHash.
Field Documentation
ActorDescViewMap
const FStreamingGenerationActorDescViewMap* FStreamingGenerationActorDescView::ActorDescViewMap private
Definition at line 102 of file WorldPartitionStreamingGeneration.h.
Referenced by FStreamingGenerationActorDescView(), FStreamingGenerationActorDescView(), and GetActorDescViewMap().
bIsForcedHLODIrrelevant
bool FStreamingGenerationActorDescView::bIsForcedHLODIrrelevant private
Definition at line 109 of file WorldPartitionStreamingGeneration.h.
Referenced by FStreamingGenerationActorDescView().
bIsForcedNoDataLayers
bool FStreamingGenerationActorDescView::bIsForcedNoDataLayers private
Definition at line 107 of file WorldPartitionStreamingGeneration.h.
Referenced by FStreamingGenerationActorDescView().
bIsForcedNonSpatiallyLoaded
bool FStreamingGenerationActorDescView::bIsForcedNonSpatiallyLoaded private
Definition at line 105 of file WorldPartitionStreamingGeneration.h.
Referenced by FStreamingGenerationActorDescView().
bIsForcedNoRuntimeGrid
bool FStreamingGenerationActorDescView::bIsForcedNoRuntimeGrid private
Definition at line 106 of file WorldPartitionStreamingGeneration.h.
Referenced by FStreamingGenerationActorDescView().
bIsForceNoHLODLayer
bool FStreamingGenerationActorDescView::bIsForceNoHLODLayer private
Definition at line 108 of file WorldPartitionStreamingGeneration.h.
Referenced by FStreamingGenerationActorDescView().
bIsUnsaved
bool FStreamingGenerationActorDescView::bIsUnsaved private
Definition at line 110 of file WorldPartitionStreamingGeneration.h.
Referenced by FStreamingGenerationActorDescView(), FStreamingGenerationActorDescView(), and IsUnsaved().
EditorOnlyParentTransform
TOptional<FTransform> FStreamingGenerationActorDescView::EditorOnlyParentTransform private
Definition at line 124 of file WorldPartitionStreamingGeneration.h.
Referenced by GetEditorOnlyParentTransform().
EditorReferences
TArray<FGuid> FStreamingGenerationActorDescView::EditorReferences private
Definition at line 123 of file WorldPartitionStreamingGeneration.h.
ForcedInvalidReference
TMap<FGuid, FInvalidReference> FStreamingGenerationActorDescView::ForcedInvalidReference private
Definition at line 113 of file WorldPartitionStreamingGeneration.h.
LastReturnedDataLayerInstanceNames
FDataLayerInstanceNames FStreamingGenerationActorDescView::LastReturnedDataLayerInstanceNames mutable private
Definition at line 116 of file WorldPartitionStreamingGeneration.h.
ParentView
const FStreamingGenerationActorDescView* FStreamingGenerationActorDescView::ParentView private
Definition at line 103 of file WorldPartitionStreamingGeneration.h.
Referenced by FStreamingGenerationActorDescView().
ResolvedDataLayerInstanceNames
TOptional<FDataLayerInstanceNames> FStreamingGenerationActorDescView::ResolvedDataLayerInstanceNames private
Definition at line 119 of file WorldPartitionStreamingGeneration.h.
ResolvedRuntimeGrid
TOptional<FName> FStreamingGenerationActorDescView::ResolvedRuntimeGrid private
Definition at line 118 of file WorldPartitionStreamingGeneration.h.
RuntimeDataLayerInstanceNames
TOptional<FDataLayerInstanceNames> FStreamingGenerationActorDescView::RuntimeDataLayerInstanceNames private
Definition at line 120 of file WorldPartitionStreamingGeneration.h.
RuntimeHLODLayer
TOptional<FSoftObjectPath> FStreamingGenerationActorDescView::RuntimeHLODLayer private
Definition at line 122 of file WorldPartitionStreamingGeneration.h.
RuntimeReferences
TOptional<TArray<FGuid> > FStreamingGenerationActorDescView::RuntimeReferences private
Definition at line 121 of file WorldPartitionStreamingGeneration.h.
The documentation for this class was generated from the following file:
Runtime/Engine/Public/WorldPartition/WorldPartitionStreamingGeneration.h