Unreal Engine 5.6 C++ API: TOctree2< ElementType, OctreeSemantics > Class Template Reference
TOctree2< ElementType, OctreeSemantics > Class Template Reference
An octree.
#include "GenericOctree.h"
Data Structures
struct COctreeSemanticsV2
class FFreeList
struct FNode
Public Types
using FNodeIndex = uint32
using FReal = FVector::FReal
Public Member Functions
TOctree2 ()
DO NOT USE.
TOctree2 (const FVector &InOrigin, FVector::FReal InExtent)
Initialization constructor.
void AddElement (typename TCallTraits< ElementType >::ConstReference Element)
Adds an element to the octree.
void ApplyOffset (const FVector &InOffset, bool bGlobalOctree=false)
Apply an arbitrary offset to all elements in the tree InOffset - offset to apply bGlobalOctree - hint that this octree is used as a boundless global volume, so only content will be shifted but not origin of the octree.
void Destroy ()
this function resets the octree to empty.
void DumpStats () const
Writes stats for the octree to the log.
template<typename IterateAllElementsFunc>
void FindAllElements (const IterateAllElementsFunc &Func) const
this function will call the passed in function for all elements in the Octree in node by node in no specified order.
template<typename IterateBoundsFunc>
void FindElementsWithBoundsTest (const FBoxCenterAndExtent &BoxBounds, const IterateBoundsFunc &Func) const
this function will traverse the Octree using a fast box-box intersection this should be the preferred way of traversing the tree.
template<typename PredicateFunc, typename IterateFunc>
void FindElementsWithPredicate (const PredicateFunc &Predicate, const IterateFunc &Func) const
this function will traverse the Octree starting from the root in depth first order and the predicate can be used to implement custom culling for each node.
template<typename IterateBoundsFunc>
FOctreeElementId2 FindFirstElementWithBoundsTest (const FBoxCenterAndExtent &BoxBounds, const IterateBoundsFunc &Func) const
this function will traverse the Octree using a fast box-box intersection and aborts traversal as soon as the Element function returns false.
template<typename IterateBoundsFunc>
void FindNearbyElements (const FVector &Position, const IterateBoundsFunc &Func) const
this function will traverse the Octree using a tryint to find nearby nodes that contain any elements.
template<typename PredicateFunc, typename IterateFunc>
void FindNodesWithPredicate (const PredicateFunc &Predicate, const IterateFunc &Func) const
this function will traverse the Octree starting from the root in depth first order and the predicate can be used to implement custom culling for each node.
ElementType & GetElementById (FOctreeElementId2 ElementId)
Accesses an octree element by ID.
const ElementType & GetElementById (FOctreeElementId2 ElementId) const
Accesses an octree element by ID.
TArrayView< const ElementType > GetElementsForNode (FNodeIndex NodeIndex) const
return all elements for a given node.
FReal GetNodeLevelExtent (int32 Level) const
int32 GetNumNodes () const
FBoxCenterAndExtent GetRootBounds () const
SIZE_T GetSizeBytes () const
bool IsValidElementId (FOctreeElementId2 ElementId) const
check if a FOctreeElementId2 is valid.
void RemoveElement (FOctreeElementId2 ElementId)
Removes an element from the octree.
void ShrinkElements ()
Protected Member Functions
void SetElementId (const ElementType &Element, FOctreeElementId2 Id)
Private Types
using ElementArrayType = TArray<ElementType, typename OctreeSemantics::ElementAllocator>
Private Member Functions
void AddElementInternal (FNodeIndex CurrentNodeIndex, const FOctreeNodeContext &NodeContext, const FBoxCenterAndExtent &ElementBounds, typename TCallTraits< ElementType >::ConstReference Element, ElementArrayType &TempElementStorage)
FNodeIndex AllocateEightNodes ()
void CollapseNodesInternal (FNodeIndex CurrentNodeIndex, ElementArrayType &CollapsedNodeElements)
template<typename IterateFunc>
void FindElementsWithBoundsTestInternal (FNodeIndex CurrentNodeIndex, const FOctreeNodeContext &NodeContext, const FBoxCenterAndExtent &BoxBounds, const IterateFunc &Func) const
template<typename IterateFunc>
FOctreeElementId2 FindFirstElementWithBoundsTestInternal (FNodeIndex CurrentNodeIndex, const FOctreeNodeContext &NodeContext, const FBoxCenterAndExtent &BoxBounds, const IterateFunc &Func) const
template<typename IterateFunc>
void FindNearbyElementsInternal (FNodeIndex CurrentNodeIndex, const FOctreeNodeContext &NodeContext, const FBoxCenterAndExtent &BoxBounds, const IterateFunc &Func) const
template<typename PredicateFunc, typename IterateFunc>
void FindNodesWithPredicateInternal (FNodeIndex ParentNodeIndex, FNodeIndex CurrentNodeIndex, const FOctreeNodeContext &NodeContext, const PredicateFunc &Predicate, const IterateFunc &Func) const
void FreeEightNodes (FNodeIndex Index)
template<typename Semantics>
void SetOctreeSemanticsElementId (const ElementType &Element, FOctreeElementId2 Id)
Private Attributes
TArray< FNodeIndex > FreeList
FVector::FReal MinLeafExtent
The extent of a leaf at the maximum allowed depth of the tree.
TArray< FNodeIndex > ParentLinks
FOctreeNodeContext RootNodeContext
TArray< ElementArrayType, TAlignedHeapAllocator< alignof(ElementArrayType)> > TreeElements
TArray< FNode > TreeNodes
Detailed Description
template<typename ElementType, typename OctreeSemantics>
class TOctree2< ElementType, OctreeSemantics >
An octree.
Definition at line 377 of file GenericOctree.h.
Member Typedef Documentation
ElementArrayType
template<typename ElementType, typename OctreeSemantics> using TOctree2< ElementType, OctreeSemantics >::ElementArrayType = TArray<ElementType, typename OctreeSemantics::ElementAllocator> private
Definition at line 379 of file GenericOctree.h.
FNodeIndex
template<typename ElementType, typename OctreeSemantics> using TOctree2< ElementType, OctreeSemantics >::FNodeIndex = uint32
Definition at line 381 of file GenericOctree.h.
FReal
template<typename ElementType, typename OctreeSemantics> using TOctree2< ElementType, OctreeSemantics >::FReal = FVector::FReal
Definition at line 382 of file GenericOctree.h.
Constructor & Destructor Documentation
TOctree2() [1/2]
template<typename ElementType, typename OctreeSemantics> TOctree2< ElementType, OctreeSemantics >::TOctree2 (const FVector & InOrigin, FVector::FReal InExtent) inline
Initialization constructor.
Definition at line 1031 of file GenericOctree.h.
TOctree2() [2/2]
template<typename ElementType, typename OctreeSemantics> TOctree2< ElementType, OctreeSemantics >::TOctree2 () inline
DO NOT USE.
This constructor is for internal usage only for hot-reload purposes.
Definition at line 1040 of file GenericOctree.h.
Member Function Documentation
AddElement()
template<typename ElementType, typename OctreeSemantics> void TOctree2< ElementType, OctreeSemantics >::AddElement (typename TCallTraits< ElementType >::ConstReference Element) inline
Adds an element to the octree.
Parameters
Element - The element to add.
Definition at line 821 of file GenericOctree.h.
Referenced by TOctree2< FVolumeLightingSample, FLightVolumeOctreeSemantics >::ApplyOffset().
AddElementInternal()
template<typename ElementType, typename OctreeSemantics> void TOctree2< ElementType, OctreeSemantics >::AddElementInternal (FNodeIndex CurrentNodeIndex, const FOctreeNodeContext & NodeContext, const FBoxCenterAndExtent & ElementBounds, typename TCallTraits< ElementType >::ConstReference Element, ElementArrayType & TempElementStorage) inline private
Definition at line 536 of file GenericOctree.h.
Referenced by TOctree2< FVolumeLightingSample, FLightVolumeOctreeSemantics >::AddElement(), and TOctree2< FVolumeLightingSample, FLightVolumeOctreeSemantics >::AddElementInternal().
AllocateEightNodes()
template<typename ElementType, typename OctreeSemantics> FNodeIndex TOctree2< ElementType, OctreeSemantics >::AllocateEightNodes () inline private
Definition at line 506 of file GenericOctree.h.
Referenced by TOctree2< FVolumeLightingSample, FLightVolumeOctreeSemantics >::AddElementInternal().
ApplyOffset()
template<typename ElementType, typename OctreeSemantics> void TOctree2< ElementType, OctreeSemantics >::ApplyOffset (const FVector & InOffset, bool bGlobalOctree = false) inline
Apply an arbitrary offset to all elements in the tree InOffset - offset to apply bGlobalOctree - hint that this octree is used as a boundless global volume, so only content will be shifted but not origin of the octree.
Definition at line 1007 of file GenericOctree.h.
CollapseNodesInternal()
template<typename ElementType, typename OctreeSemantics> void TOctree2< ElementType, OctreeSemantics >::CollapseNodesInternal (FNodeIndex CurrentNodeIndex, ElementArrayType & CollapsedNodeElements) inline private
Definition at line 588 of file GenericOctree.h.
Referenced by TOctree2< FVolumeLightingSample, FLightVolumeOctreeSemantics >::ApplyOffset(), TOctree2< FVolumeLightingSample, FLightVolumeOctreeSemantics >::CollapseNodesInternal(), and TOctree2< FVolumeLightingSample, FLightVolumeOctreeSemantics >::RemoveElement().
Destroy()
template<typename ElementType, typename OctreeSemantics> void TOctree2< ElementType, OctreeSemantics >::Destroy () inline
this function resets the octree to empty.
Definition at line 890 of file GenericOctree.h.
Referenced by TOctree2< FVolumeLightingSample, FLightVolumeOctreeSemantics >::ApplyOffset().
DumpStats()
template<typename ElementType, typename OctreeSemantics> void TOctree2< ElementType, OctreeSemantics >::DumpStats () const inline
Writes stats for the octree to the log.
Definition at line 931 of file GenericOctree.h.
FindAllElements()
template<typename ElementType, typename OctreeSemantics> template<typename IterateAllElementsFunc> void TOctree2< ElementType, OctreeSemantics >::FindAllElements (const IterateAllElementsFunc & Func) const inline
this function will call the passed in function for all elements in the Octree in node by node in no specified order.
Parameters
Func - Function to call with each Element.
Definition at line 743 of file GenericOctree.h.
FindElementsWithBoundsTest()
template<typename ElementType, typename OctreeSemantics> template<typename IterateBoundsFunc> void TOctree2< ElementType, OctreeSemantics >::FindElementsWithBoundsTest (const FBoxCenterAndExtent & BoxBounds, const IterateBoundsFunc & Func) const inline
this function will traverse the Octree using a fast box-box intersection this should be the preferred way of traversing the tree.
Parameters
BoxBounds - the bounds to test if a node is traversed or skipped.
Func - Function to call with each Element for nodes that passed bounds test.
Definition at line 788 of file GenericOctree.h.
FindElementsWithBoundsTestInternal()
template<typename ElementType, typename OctreeSemantics> template<typename IterateFunc> void TOctree2< ElementType, OctreeSemantics >::FindElementsWithBoundsTestInternal (FNodeIndex CurrentNodeIndex, const FOctreeNodeContext & NodeContext, const FBoxCenterAndExtent & BoxBounds, const IterateFunc & Func) const inline private
Definition at line 630 of file GenericOctree.h.
Referenced by TOctree2< FVolumeLightingSample, FLightVolumeOctreeSemantics >::FindElementsWithBoundsTest(), and TOctree2< FVolumeLightingSample, FLightVolumeOctreeSemantics >::FindElementsWithBoundsTestInternal().
FindElementsWithPredicate()
template<typename ElementType, typename OctreeSemantics> template<typename PredicateFunc, typename IterateFunc> void TOctree2< ElementType, OctreeSemantics >::FindElementsWithPredicate (const PredicateFunc & Predicate, const IterateFunc & Func) const inline
this function will traverse the Octree starting from the root in depth first order and the predicate can be used to implement custom culling for each node.
Parameters
Predicate - a Function when given the bounds of the currently traversed node that returns true if traversal should continue or false to skip that branch.
Func - Function to call with each Element for nodes that passed the predicate.
Definition at line 771 of file GenericOctree.h.
FindFirstElementWithBoundsTest()
template<typename ElementType, typename OctreeSemantics> template<typename IterateBoundsFunc> FOctreeElementId2 TOctree2< ElementType, OctreeSemantics >::FindFirstElementWithBoundsTest (const FBoxCenterAndExtent & BoxBounds, const IterateBoundsFunc & Func) const inline
this function will traverse the Octree using a fast box-box intersection and aborts traversal as soon as the Element function returns false.
Parameters
BoxBounds - the bounds to test if a node is traversed or skipped.
Func - Function to call with each Element for nodes that passed bounds test.
Returns
The ID of the found element. It's only valid until the next time the tree changes.
Definition at line 800 of file GenericOctree.h.
FindFirstElementWithBoundsTestInternal()
template<typename ElementType, typename OctreeSemantics> template<typename IterateFunc> FOctreeElementId2 TOctree2< ElementType, OctreeSemantics >::FindFirstElementWithBoundsTestInternal (FNodeIndex CurrentNodeIndex, const FOctreeNodeContext & NodeContext, const FBoxCenterAndExtent & BoxBounds, const IterateFunc & Func) const inline private
Definition at line 658 of file GenericOctree.h.
Referenced by TOctree2< FVolumeLightingSample, FLightVolumeOctreeSemantics >::FindFirstElementWithBoundsTest(), and TOctree2< FVolumeLightingSample, FLightVolumeOctreeSemantics >::FindFirstElementWithBoundsTestInternal().
FindNearbyElements()
template<typename ElementType, typename OctreeSemantics> template<typename IterateBoundsFunc> void TOctree2< ElementType, OctreeSemantics >::FindNearbyElements (const FVector & Position, const IterateBoundsFunc & Func) const inline
this function will traverse the Octree using a tryint to find nearby nodes that contain any elements.
Parameters
Position - the position to look nearby.
Func - Function to call with each Element for nodes that passed bounds test.
Definition at line 811 of file GenericOctree.h.
FindNearbyElementsInternal()
template<typename ElementType, typename OctreeSemantics> template<typename IterateFunc> void TOctree2< ElementType, OctreeSemantics >::FindNearbyElementsInternal (FNodeIndex CurrentNodeIndex, const FOctreeNodeContext & NodeContext, const FBoxCenterAndExtent & BoxBounds, const IterateFunc & Func) const inline private
Definition at line 697 of file GenericOctree.h.
Referenced by TOctree2< FVolumeLightingSample, FLightVolumeOctreeSemantics >::FindNearbyElements(), and TOctree2< FVolumeLightingSample, FLightVolumeOctreeSemantics >::FindNearbyElementsInternal().
FindNodesWithPredicate()
template<typename ElementType, typename OctreeSemantics> template<typename PredicateFunc, typename IterateFunc> void TOctree2< ElementType, OctreeSemantics >::FindNodesWithPredicate (const PredicateFunc & Predicate, const IterateFunc & Func) const inline
this function will traverse the Octree starting from the root in depth first order and the predicate can be used to implement custom culling for each node.
Parameters
Predicate - a Function when given the bounds of the currently traversed node that returns true if traversal should continue or false to skip that branch.
Func - Function that will receive the node ID which can be stored and later used to get the elements using GetElementsForNode for all nodes that passed the predicate.
Definition at line 760 of file GenericOctree.h.
FindNodesWithPredicateInternal()
template<typename ElementType, typename OctreeSemantics> template<typename PredicateFunc, typename IterateFunc> void TOctree2< ElementType, OctreeSemantics >::FindNodesWithPredicateInternal (FNodeIndex ParentNodeIndex, FNodeIndex CurrentNodeIndex, const FOctreeNodeContext & NodeContext, const PredicateFunc & Predicate, const IterateFunc & Func) const inline private
Definition at line 609 of file GenericOctree.h.
Referenced by TOctree2< FVolumeLightingSample, FLightVolumeOctreeSemantics >::DumpStats(), TOctree2< FVolumeLightingSample, FLightVolumeOctreeSemantics >::FindElementsWithPredicate(), TOctree2< FVolumeLightingSample, FLightVolumeOctreeSemantics >::FindNodesWithPredicate(), and TOctree2< FVolumeLightingSample, FLightVolumeOctreeSemantics >::FindNodesWithPredicateInternal().
FreeEightNodes()
template<typename ElementType, typename OctreeSemantics> void TOctree2< ElementType, OctreeSemantics >::FreeEightNodes (FNodeIndex Index) inline private
Definition at line 523 of file GenericOctree.h.
Referenced by TOctree2< FVolumeLightingSample, FLightVolumeOctreeSemantics >::CollapseNodesInternal().
GetElementById() [1/2]
template<typename ElementType, typename OctreeSemantics> ElementType & TOctree2< ElementType, OctreeSemantics >::GetElementById (FOctreeElementId2 ElementId) inline nodiscard
Accesses an octree element by ID.
Definition at line 901 of file GenericOctree.h.
GetElementById() [2/2]
template<typename ElementType, typename OctreeSemantics> const ElementType & TOctree2< ElementType, OctreeSemantics >::GetElementById (FOctreeElementId2 ElementId) const inline nodiscard
Accesses an octree element by ID.
Definition at line 907 of file GenericOctree.h.
GetElementsForNode()
template<typename ElementType, typename OctreeSemantics> TArrayView< const ElementType > TOctree2< ElementType, OctreeSemantics >::GetElementsForNode (FNodeIndex NodeIndex) const inline nodiscard
return all elements for a given node.
Parameters
NodeIndex - The the index of the node can be obtained using FindNodesWithPredicate.
Definition at line 925 of file GenericOctree.h.
Referenced by TOctree2< FVolumeLightingSample, FLightVolumeOctreeSemantics >::DumpStats().
GetNodeLevelExtent()
template<typename ElementType, typename OctreeSemantics> FReal TOctree2< ElementType, OctreeSemantics >::GetNodeLevelExtent (int32 Level) const inline nodiscard
Definition at line 982 of file GenericOctree.h.
GetNumNodes()
template<typename ElementType, typename OctreeSemantics> int32 TOctree2< ElementType, OctreeSemantics >::GetNumNodes () const inline nodiscard
Definition at line 733 of file GenericOctree.h.
GetRootBounds()
template<typename ElementType, typename OctreeSemantics> FBoxCenterAndExtent TOctree2< ElementType, OctreeSemantics >::GetRootBounds () const inline nodiscard
Definition at line 988 of file GenericOctree.h.
GetSizeBytes()
template<typename ElementType, typename OctreeSemantics> SIZE_T TOctree2< ElementType, OctreeSemantics >::GetSizeBytes () const inline nodiscard
Definition at line 974 of file GenericOctree.h.
IsValidElementId()
template<typename ElementType, typename OctreeSemantics> bool TOctree2< ElementType, OctreeSemantics >::IsValidElementId (FOctreeElementId2 ElementId) const inline nodiscard
check if a FOctreeElementId2 is valid.
Parameters
ElementId - The ElementId to check.
Definition at line 916 of file GenericOctree.h.
RemoveElement()
template<typename ElementType, typename OctreeSemantics> void TOctree2< ElementType, OctreeSemantics >::RemoveElement (FOctreeElementId2 ElementId) inline
Removes an element from the octree.
Parameters
ElementId - The element to remove from the octree.
Definition at line 832 of file GenericOctree.h.
SetElementId()
template<typename ElementType, typename OctreeSemantics> void TOctree2< ElementType, OctreeSemantics >::SetElementId (const ElementType & Element, FOctreeElementId2 Id) inline protected
Definition at line 1073 of file GenericOctree.h.
Referenced by TOctree2< FVolumeLightingSample, FLightVolumeOctreeSemantics >::AddElementInternal(), and TOctree2< FVolumeLightingSample, FLightVolumeOctreeSemantics >::RemoveElement().
SetOctreeSemanticsElementId()
template<typename ElementType, typename OctreeSemantics> template<typename Semantics> void TOctree2< ElementType, OctreeSemantics >::SetOctreeSemanticsElementId (const ElementType & Element, FOctreeElementId2 Id) inline private
Definition at line 1059 of file GenericOctree.h.
Referenced by TOctree2< FVolumeLightingSample, FLightVolumeOctreeSemantics >::SetElementId().
ShrinkElements()
template<typename ElementType, typename OctreeSemantics> void TOctree2< ElementType, OctreeSemantics >::ShrinkElements () inline
Definition at line 993 of file GenericOctree.h.
Field Documentation
FreeList
template<typename ElementType, typename OctreeSemantics> TArray<FNodeIndex> TOctree2< ElementType, OctreeSemantics >::FreeList private
Definition at line 502 of file GenericOctree.h.
MinLeafExtent
template<typename ElementType, typename OctreeSemantics> FVector::FReal TOctree2< ElementType, OctreeSemantics >::MinLeafExtent private
The extent of a leaf at the maximum allowed depth of the tree.
Definition at line 504 of file GenericOctree.h.
ParentLinks
template<typename ElementType, typename OctreeSemantics> TArray<FNodeIndex> TOctree2< ElementType, OctreeSemantics >::ParentLinks private
Definition at line 398 of file GenericOctree.h.
RootNodeContext
template<typename ElementType, typename OctreeSemantics> FOctreeNodeContext TOctree2< ElementType, OctreeSemantics >::RootNodeContext private
Definition at line 396 of file GenericOctree.h.
TreeElements
template<typename ElementType, typename OctreeSemantics> TArray<ElementArrayType, TAlignedHeapAllocator<alignof(ElementArrayType)> > TOctree2< ElementType, OctreeSemantics >::TreeElements private
Definition at line 399 of file GenericOctree.h.
TreeNodes
template<typename ElementType, typename OctreeSemantics> TArray<FNode> TOctree2< ElementType, OctreeSemantics >::TreeNodes private
Definition at line 397 of file GenericOctree.h.
The documentation for this class was generated from the following file:
Runtime/Core/Public/Math/GenericOctree.h