Unreal Engine 5.6 C++ API: UE::Geometry::TMarchingPixelInfill< PixelType > Class Template Reference
UE::Geometry::TMarchingPixelInfill< PixelType > Class Template Reference
TMarchingPixelInfill implements a very basic infilling strategy where the missing pixel with the most "known" neighbours is set to the average value of those neighbours, and this is iterated until all missing pixels are known.
#include "ImageInfilling.h"
Public Member Functions
template<typename OtherPixelType>
void ApplyInfill (TImageBuilder< OtherPixelType > &Image, TFunctionRef< OtherPixelType(OtherPixelType SumOfNbrValues, int NbrCount)> NormalizeFunc) const
Fill the missing values in Image by replaying the infill sequence computed by ComputeInfill()
void ApplyInfill (TImageBuilder< PixelType > &Image, TFunctionRef< PixelType(PixelType SumOfNbrValues, int NbrCount)> NormalizeFunc) const
Fill the missing values in Image by replaying the infill sequence computed by ComputeInfill()
void ComputeInfill (TImageBuilder< PixelType > &Image, const TArray< FVector2i > &MissingPixels, PixelType MissingValue, TFunctionRef< PixelType(PixelType SumOfNbrValues, int NbrCount)> NormalizeFunc)
Fill the values of MissingPixels in Image by propagating from known values.
Data Fields
TArray< int32 > InfillSequence
Detailed Description
template<typename PixelType>
class UE::Geometry::TMarchingPixelInfill< PixelType >
TMarchingPixelInfill implements a very basic infilling strategy where the missing pixel with the most "known" neighbours is set to the average value of those neighbours, and this is iterated until all missing pixels are known.
A Priority Queue is used to track the active front.
The infill sequence is tracked, which allows it to be "replayed" on multiple images. This is useful in cases where we have separate images with the same holes, which arises when baking textures from world sampling.
Definition at line 28 of file ImageInfilling.h.
Member Function Documentation
ApplyInfill() [1/2]
template<typename PixelType> template<typename OtherPixelType> void UE::Geometry::TMarchingPixelInfill< PixelType >::ApplyInfill (TImageBuilder< OtherPixelType > & Image, TFunctionRef< OtherPixelType(OtherPixelType SumOfNbrValues, int NbrCount)> NormalizeFunc) const inline
Fill the missing values in Image by replaying the infill sequence computed by ComputeInfill()
Parameters
NormalizeFunc Implements an "average" operation for the template OtherPixelType, normally (SumOfNbrValues / NbrCount)
Definition at line 139 of file ImageInfilling.h.
References InfillSequence, UE::Geometry::FVector2i::X, and UE::Geometry::FVector2i::Y.
Referenced by ApplyInfill().
ApplyInfill() [2/2]
template<typename PixelType> void UE::Geometry::TMarchingPixelInfill< PixelType >::ApplyInfill (TImageBuilder< PixelType > & Image, TFunctionRef< PixelType(PixelType SumOfNbrValues, int NbrCount)> NormalizeFunc) const inline
Fill the missing values in Image by replaying the infill sequence computed by ComputeInfill()
Parameters
NormalizeFunc Implements an "average" operation for the template PixelType, normally (SumOfNbrValues / NbrCount)
Definition at line 174 of file ImageInfilling.h.
References ApplyInfill().
ComputeInfill()
template<typename PixelType> void UE::Geometry::TMarchingPixelInfill< PixelType >::ComputeInfill (TImageBuilder< PixelType > & Image, const TArray< FVector2i > & MissingPixels, PixelType MissingValue, TFunctionRef< PixelType(PixelType SumOfNbrValues, int NbrCount)> NormalizeFunc) inline
Fill the values of MissingPixels in Image by propagating from known values.
Parameters
MissingValue this value is used to indicate 'missing' in the image. Input pixels do not have to be set to this value, they are set internally to avoid map lookups
NormalizeFunc Implements an "average" operation for the template PixelType, normally (SumOfNbrValues / Count)
Definition at line 41 of file ImageInfilling.h.
References TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Add(), UE::Geometry::FIndexPriorityQueue::Contains(), UE::Count, UE::Geometry::FIndexPriorityQueue::Dequeue(), TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Find(), UE::Geometry::FIndexPriorityQueue::GetCount(), UE::Geometry::FIndexPriorityQueue::GetPriority(), IndexUtil::GridOffsets8, InfillSequence, UE::Geometry::FIndexPriorityQueue::Insert(), TArray< InElementType, InAllocatorType >::Num(), UE::Geometry::FIndexPriorityQueue::Update(), UE::Geometry::FVector2i::X, and UE::Geometry::FVector2i::Y.
Field Documentation
InfillSequence
template<typename PixelType> TArray<int32> UE::Geometry::TMarchingPixelInfill< PixelType >::InfillSequence
Definition at line 33 of file ImageInfilling.h.
Referenced by ApplyInfill(), and ComputeInfill().
The documentation for this class was generated from the following file:
Runtime/GeometryCore/Public/Image/ImageInfilling.h