Unreal Engine 5.6 C++ API: FShadowMap2D Class Reference
FShadowMap2D Class Reference
#include "ShadowMap.h"
Public Member Functions
FShadowMap2D ()
FShadowMap2D (const TMap< ULightComponent *, FShadowMapData2D * > &ShadowMapData)
FShadowMap2D (TArray< FGuid > LightGuids)
virtual void AddReferencedObjects (FReferenceCollector &Collector)
const FVector2D & GetCoordinateBias () const
const FVector2D & GetCoordinateScale () const
virtual FShadowMapInteraction GetInteraction () const
virtual FShadowMap2D * GetShadowMap2D ()
virtual const FShadowMap2D * GetShadowMap2D () const
UTexture2D * GetTexture ()
const UTexture2D * GetTexture () const
bool IsShadowFactorTexture () const
bool IsValid () const
virtual void Serialize (FArchive &Ar)
Public Member Functions inherited from FShadowMap
FShadowMap ()
Default constructor.
FShadowMap (TArray< FGuid > InLightGuids)
virtual ~FShadowMap ()
Destructor.
void AddRef ()
bool ContainsLight (const FGuid &LightGuid) const
Checks if a light is stored in this shadow-map.
void Release ()
Static Public Member Functions
static TRefCountPtr< FShadowMap2D > AllocateInstancedShadowMap (UObject *LightMapOuter, UInstancedStaticMeshComponent *Component, TArray< TMap< ULightComponent *, TUniquePtr< FShadowMapData2D > > > &&InstancedShadowMapData, UMapBuildDataRegistry *Registry, FGuid MapBuildDataId, const FBoxSphereBounds &Bounds, ELightMapPaddingType PaddingType, EShadowMapFlags ShadowmapFlags)
Allocates texture space for the shadow-map and stores the shadow-map's raw data for deferred encoding.
static TRefCountPtr< FShadowMap2D > AllocateShadowMap (UObject *LightMapOuter, const TMap< ULightComponent *, FShadowMapData2D * > &ShadowMapData, const FBoxSphereBounds &Bounds, ELightMapPaddingType InPaddingType, EShadowMapFlags InShadowmapFlags)
static int32 EncodeSingleTexture (const FStaticLightingBuildContext *LightingContext, struct FShadowMapPendingTexture &PendingTexture, UShadowMapTexture2D *Texture, TArray< TArray< FFourDistanceFieldSamples > > &MipData)
Constructs mip maps for a single shadowmap texture.
static void EncodeTextures (const FStaticLightingBuildContext *LightingContext, bool bLightingSuccessful, bool bMultithreadedEncode=false)
Executes all pending shadow-map encoding requests.
static bool GetStatusUpdate ()
static void SetStatusUpdate (bool bInEnable)
Call to enable/disable status update of LightMap encoding.
Protected Attributes
bool bChannelValid [4]
Tracks which of the 4 channels has valid texture data.
FVector2D CoordinateBias
The bias which is applied to the shadow-map coordinates before sampling the shadow-map textures.
FVector2D CoordinateScale
The scale which is applied to the shadow-map coordinates before sampling the shadow-map textures.
FVector4f InvUniformPenumbraSize
Stores the inverse of the penumbra size, normalized.
TObjectPtr< UShadowMapTexture2D > Texture
The texture which contains the shadow-map data.
Static Protected Attributes
static bool bUpdateStatus
If true, update the status when encoding light maps.
Additional Inherited Members
Public Types inherited from FShadowMap
enum { SMT_None = 0 , SMT_2D = 2 }
Data Fields inherited from FShadowMap
TArray< FGuid > LightGuids
The GUIDs of lights which this shadow-map stores.
Protected Member Functions inherited from FShadowMap
virtual void Cleanup ()
Called when the light-map is no longer referenced.
Detailed Description
Definition at line 299 of file ShadowMap.h.
Constructor & Destructor Documentation
FShadowMap2D() [1/3]
FShadowMap2D::FShadowMap2D ()
Referenced by GetShadowMap2D(), and GetShadowMap2D().
FShadowMap2D() [2/3]
FShadowMap2D::FShadowMap2D (const TMap< ULightComponent *, FShadowMapData2D * > & ShadowMapData)
FShadowMap2D() [3/3]
FShadowMap2D::FShadowMap2D (TArray< FGuid > LightGuids)
References FShadowMap::LightGuids.
Member Function Documentation
AddReferencedObjects()
virtual void FShadowMap2D::AddReferencedObjects (FReferenceCollector & Collector) virtual
Reimplemented from FShadowMap.
AllocateInstancedShadowMap()
TRefCountPtr< FShadowMap2D > FShadowMap2D::AllocateInstancedShadowMap (UObject * LightMapOuter, UInstancedStaticMeshComponent * Component, TArray< TMap< ULightComponent *, TUniquePtr< FShadowMapData2D > > > && InstancedShadowMapData, UMapBuildDataRegistry * Registry, FGuid MapBuildDataId, const FBoxSphereBounds & Bounds, ELightMapPaddingType PaddingType, EShadowMapFlags ShadowmapFlags) static
Allocates texture space for the shadow-map and stores the shadow-map's raw data for deferred encoding.
If the shadow-map has no shadows in it, it will return NULL.
Parameters
Component - The component that owns this shadowmap
InstancedShadowMapData - The raw shadow-map data to fill the texture with.
Bounds - The bounds of the primitive the shadow-map will be rendered on. Used as a hint to pack shadow-maps on nearby primitives in the same texture.
InPaddingType - the method for padding the shadowmap.
ShadowmapFlags - flags that determine how the shadowmap is stored (e.g. streamed or not)
References Component, and Registry.
AllocateShadowMap()
TRefCountPtr< FShadowMap2D > FShadowMap2D::AllocateShadowMap (UObject * LightMapOuter, const TMap< ULightComponent *, FShadowMapData2D * > & ShadowMapData, const FBoxSphereBounds & Bounds, ELightMapPaddingType InPaddingType, EShadowMapFlags InShadowmapFlags) static
EncodeSingleTexture()
int32 FShadowMap2D::EncodeSingleTexture (const FStaticLightingBuildContext * LightingContext, struct FShadowMapPendingTexture & PendingTexture, UShadowMapTexture2D * Texture, TArray< TArray< FFourDistanceFieldSamples > > & MipData) static
Constructs mip maps for a single shadowmap texture.
References Texture.
EncodeTextures()
void FShadowMap2D::EncodeTextures (const FStaticLightingBuildContext * LightingContext, bool bLightingSuccessful, bool bMultithreadedEncode = false) static
Executes all pending shadow-map encoding requests.
Parameters
LightingContext Context in which the textures exist
bLightingSuccessful Whether the lighting build was successful or not.
GetCoordinateBias()
const FVector2D & FShadowMap2D::GetCoordinateBias () const inline
Definition at line 343 of file ShadowMap.h.
References check, CoordinateBias, and IsValid().
GetCoordinateScale()
const FVector2D & FShadowMap2D::GetCoordinateScale () const inline
Definition at line 342 of file ShadowMap.h.
References check, CoordinateScale, and IsValid().
GetInteraction()
virtual FShadowMapInteraction FShadowMap2D::GetInteraction () const virtual
Implements FShadowMap.
GetShadowMap2D() [1/2]
virtual FShadowMap2D * FShadowMap2D::GetShadowMap2D () inline virtual
Reimplemented from FShadowMap.
Definition at line 353 of file ShadowMap.h.
References FShadowMap2D().
GetShadowMap2D() [2/2]
virtual const FShadowMap2D * FShadowMap2D::GetShadowMap2D () const inline virtual
Reimplemented from FShadowMap.
Definition at line 354 of file ShadowMap.h.
References FShadowMap2D().
GetStatusUpdate()
bool FShadowMap2D::GetStatusUpdate () inline static
Definition at line 363 of file ShadowMap.h.
References bUpdateStatus.
GetTexture() [1/2]
UTexture2D * FShadowMap2D::GetTexture ()
GetTexture() [2/2]
const UTexture2D * FShadowMap2D::GetTexture () const
IsShadowFactorTexture()
bool FShadowMap2D::IsShadowFactorTexture () const inline
Definition at line 345 of file ShadowMap.h.
IsValid()
bool FShadowMap2D::IsValid () const inline
Definition at line 344 of file ShadowMap.h.
References Texture.
Referenced by GetCoordinateBias(), and GetCoordinateScale().
Serialize()
virtual void FShadowMap2D::Serialize (FArchive & Ar) virtual
Reimplemented from FShadowMap.
References Ar.
SetStatusUpdate()
void FShadowMap2D::SetStatusUpdate (bool bInEnable) inline static
Call to enable/disable status update of LightMap encoding.
Definition at line 358 of file ShadowMap.h.
References bUpdateStatus.
Field Documentation
bChannelValid
bool FShadowMap2D::bChannelValid[4] protected
Tracks which of the 4 channels has valid texture data.
Definition at line 381 of file ShadowMap.h.
bUpdateStatus
bool FShadowMap2D::bUpdateStatus static protected
If true, update the status when encoding light maps.
Definition at line 388 of file ShadowMap.h.
Referenced by GetStatusUpdate(), and SetStatusUpdate().
CoordinateBias
FVector2D FShadowMap2D::CoordinateBias protected
The bias which is applied to the shadow-map coordinates before sampling the shadow-map textures.
Definition at line 378 of file ShadowMap.h.
Referenced by GetCoordinateBias().
CoordinateScale
FVector2D FShadowMap2D::CoordinateScale protected
The scale which is applied to the shadow-map coordinates before sampling the shadow-map textures.
Definition at line 375 of file ShadowMap.h.
Referenced by GetCoordinateScale().
InvUniformPenumbraSize
FVector4f FShadowMap2D::InvUniformPenumbraSize protected
Stores the inverse of the penumbra size, normalized.
Stores 1 to interpret the shadowmap as a shadow factor directly, instead of as a distance field.
Definition at line 384 of file ShadowMap.h.
Texture
TObjectPtr<UShadowMapTexture2D> FShadowMap2D::Texture protected
The texture which contains the shadow-map data.
Definition at line 372 of file ShadowMap.h.
Referenced by EncodeSingleTexture(), and IsValid().
The documentation for this class was generated from the following file:
Runtime/Engine/Public/ShadowMap.h