Unreal Engine 5.6 C++ API: FLazyPrintf Class Reference
FLazyPrintf Class Reference
#include "LazyPrintf.h"
Public Member Functions
FLazyPrintf (const TCHAR *InputWithPercentS)
FString GetResultString ()
void PushParam (const TCHAR *Data)
Private Member Functions
bool ProcessUntilPercentS ()
Private Attributes
const TCHAR * CurrentInputPos
FString CurrentState
Detailed Description
Definition at line 10 of file LazyPrintf.h.
Constructor & Destructor Documentation
FLazyPrintf()
FLazyPrintf::FLazyPrintf (const TCHAR * InputWithPercentS) inline
Definition at line 14 of file LazyPrintf.h.
References CurrentInputPos, and CurrentState.
Member Function Documentation
GetResultString()
FString FLazyPrintf::GetResultString () inline nodiscard
Definition at line 21 of file LazyPrintf.h.
References check, CurrentInputPos, CurrentState, and ProcessUntilPercentS().
ProcessUntilPercentS()
bool FLazyPrintf::ProcessUntilPercentS () inline private
Definition at line 49 of file LazyPrintf.h.
References CurrentInputPos, CurrentState, Found, TCString< TCHAR >::Strstr(), and TEXT.
Referenced by GetResultString(), and PushParam().
PushParam()
void FLazyPrintf::PushParam (const TCHAR * Data) inline
Definition at line 33 of file LazyPrintf.h.
References check, CurrentState, and ProcessUntilPercentS().
Field Documentation
CurrentInputPos
const TCHAR* FLazyPrintf::CurrentInputPos private
Definition at line 71 of file LazyPrintf.h.
Referenced by FLazyPrintf(), GetResultString(), and ProcessUntilPercentS().
CurrentState
FString FLazyPrintf::CurrentState private
Definition at line 72 of file LazyPrintf.h.
Referenced by FLazyPrintf(), GetResultString(), ProcessUntilPercentS(), and PushParam().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Containers/LazyPrintf.h