Unreal Engine 5.6 C++ API: FBaseGraphTask Class Reference
FBaseGraphTask Class Reference
Base class for all graph tasks, used for both TGraphTask and simple graph events.
#include "TaskGraphInterfaces.h"
Public Member Functions
FBaseGraphTask (const FGraphEventArray *InPrerequisites)
void DispatchSubsequents (ENamedThreads::Type CurrentThreadIfKnown=ENamedThreads::AnyThread)
Backward compatibility wrapper for Unlock.
void DontCompleteUntil (FGraphEventRef NestedTask)
Call on a currently active task to add a nested task, which will delay any subsequent tasks until the nested task completes.
FORCEINLINE void Execute (TArray< FBaseGraphTask * > &NewTasks, ENamedThreads::Type CurrentThread, bool bDeleteOnCompletion)
FGraphEventRef GetCompletionEvent ()
Returns a reference to this task that can be used as a prerequisite for new tasks or passed to DontCompleteUntil.
void Init (const TCHAR *InDebugName, UE::Tasks::ETaskPriority InPriority, UE::Tasks::EExtendedTaskPriority InExtendedPriority, UE::Tasks::ETaskFlags InTaskFlags=UE::Tasks::ETaskFlags::None)
bool IsComplete () const
Return true if this task has finished executing, this wrapper exists for backward compatibility.
bool IsTaskEvent () const
Returns true if this is a simple task event, which cannot execute code and must be manually dispatched.
UE_DEPRECATED (5.6, "Call AddPrerequisites separately if you need to add new tasks before dispatch") void DispatchSubsequents(TArray< FBaseGraphTask * > &NewTasks
void Unlock (ENamedThreads::Type CurrentThreadIfKnown=ENamedThreads::AnyThread)
Unlocks a task that was returned from ConstructAndHold or CreateGraphEvent, which may execute immediately if prerequisites are already completed.
Public Member Functions inherited from UE::Tasks::Private::FTaskBase
void AddNested (FTaskBase &Nested)
template<typename HigherLevelTaskType, decltype(std::declval< HigherLevelTaskType >().Pimpl) * = nullptr>
bool AddPrerequisites (const HigherLevelTaskType &Prerequisite)
template<typename HigherLevelTaskType, std::enable_if_t< std::is_same_v< HigherLevelTaskType, FGraphEventRef > > * = nullptr>
bool AddPrerequisites (const HigherLevelTaskType &Prerequisite)
template<typename PrerequisiteCollectionType, decltype(std::declval< PrerequisiteCollectionType >().begin()) * = nullptr>
void AddPrerequisites (const PrerequisiteCollectionType &InPrerequisites)
bool AddPrerequisites (FTaskBase &Prerequisite)
void AddRef ()
bool AddSubsequent (FTaskBase &Subsequent)
EExtendedTaskPriority GetExtendedPriority () const
FPipe * GetPipe () const
ETaskPriority GetPriority () const
uint32 GetRefCount (std::memory_order MemoryOrder=std::memory_order_relaxed) const
TaskTrace::FId GetTraceId () const
bool IsAwaitable () const
bool IsCompleted () const
bool IsNamedThreadTask () const
void Release ()
void ReleaseInternalReference ()
void SetPipe (FPipe &InPipe)
bool TryLaunch (uint64 TaskSize)
bool TryRetractAndExecute (FTimeout Timeout, uint32 RecursionDepth=0)
template<typename ConditionType>
UE_DEPRECATED (5.5, "This method will be removed.") bool BusyWait(ConditionType &&Condition)
UE_DEPRECATED (5.5, "Use Wait instead") bool BusyWait(FTimeout Timeout)
void Wait ()
bool Wait (FTimeout Timeout)
void WaitWithNamedThreadsSupport ()
Static Public Member Functions
static FGraphEventRef CreateGraphEvent ()
Create a simple task event that can be used as a prerequisite for other tasks, and then manually triggered with DispatchSubsequents.
Additional Inherited Members
Protected Member Functions inherited from UE::Tasks::Private::FTaskBase
FTaskBase (uint32 InitRefCount, bool bUnlockPrerequisites=true)
virtual ~FTaskBase ()
template<typename PrerequisiteCollectionType, decltype(std::declval< PrerequisiteCollectionType >().begin()) * = nullptr>
void AddPrerequisites (const PrerequisiteCollectionType &InPrerequisites, bool bLockPrerequisite)
void ClearPipe ()
void Close ()
virtual void ExecuteTask ()=0
void Init (const TCHAR *InDebugName, ETaskPriority InPriority, EExtendedTaskPriority InExtendedPriority, ETaskFlags Flags)
bool TryExecuteTask ()
void UnlockPrerequisites ()
Detailed Description
Base class for all graph tasks, used for both TGraphTask and simple graph events.
This is a wrapper around the Tasks::Private::FTaskBase functionality
Definition at line 480 of file TaskGraphInterfaces.h.
Constructor & Destructor Documentation
FBaseGraphTask()
FBaseGraphTask::FBaseGraphTask (const FGraphEventArray * InPrerequisites) inline explicit
Definition at line 484 of file TaskGraphInterfaces.h.
References UE::Tasks::Private::FTaskBase::FTaskBase(), UE::Tasks::Private::FTaskBase::AddPrerequisites(), and UE::Tasks::Private::FTaskBase::UnlockPrerequisites().
Referenced by FGraphEventImpl::FGraphEventImpl(), TGraphTask< TTask >::TGraphTask(), and UE_DEPRECATED().
Member Function Documentation
CreateGraphEvent()
FGraphEventRef FBaseGraphTask::CreateGraphEvent () inline static
Create a simple task event that can be used as a prerequisite for other tasks, and then manually triggered with DispatchSubsequents.
Definition at line 753 of file TaskGraphInterfaces.h.
DispatchSubsequents()
void FBaseGraphTask::DispatchSubsequents (ENamedThreads::Type CurrentThreadIfKnown = ENamedThreads::AnyThread) inline
Backward compatibility wrapper for Unlock.
Definition at line 569 of file TaskGraphInterfaces.h.
References ENamedThreads::AnyThread, and Unlock().
Referenced by UE_DEPRECATED().
DontCompleteUntil()
void FBaseGraphTask::DontCompleteUntil (FGraphEventRef NestedTask) inline
Call on a currently active task to add a nested task, which will delay any subsequent tasks until the nested task completes.
AddPrerequisites should be used instead if the task has not yet been launched.
Definition at line 520 of file TaskGraphInterfaces.h.
References UE::Tasks::Private::FTaskBase::AddNested(), UE::Tasks::Private::FTaskBase::AddPrerequisites(), checkSlow, UE::Tasks::Private::GetCurrentTask(), and IsTaskEvent().
Execute()
FORCEINLINE void FBaseGraphTask::Execute (TArray< FBaseGraphTask * > & NewTasks, ENamedThreads::Type CurrentThread, bool bDeleteOnCompletion) inline
Definition at line 500 of file TaskGraphInterfaces.h.
References checkSlow, FORCEINLINE, UE::Tasks::Private::FTaskBase::IsNamedThreadTask(), TArray< InElementType, InAllocatorType >::Num(), UE::Tasks::Private::FTaskBase::ReleaseInternalReference(), UE::Tasks::Private::FTaskBase::TryExecuteTask(), and verify.
GetCompletionEvent()
FGraphEventRef FBaseGraphTask::GetCompletionEvent () inline
Returns a reference to this task that can be used as a prerequisite for new tasks or passed to DontCompleteUntil.
Definition at line 511 of file TaskGraphInterfaces.h.
Init()
void FBaseGraphTask::Init (const TCHAR * InDebugName, UE::Tasks::ETaskPriority InPriority, UE::Tasks::EExtendedTaskPriority InExtendedPriority, UE::Tasks::ETaskFlags InTaskFlags = UE::Tasks::ETaskFlags::None) inline
Definition at line 495 of file TaskGraphInterfaces.h.
References UE::Tasks::None.
Referenced by TGraphTask< TTask >::Init().
IsComplete()
bool FBaseGraphTask::IsComplete () const inline
Return true if this task has finished executing, this wrapper exists for backward compatibility.
Definition at line 539 of file TaskGraphInterfaces.h.
References UE::Tasks::Private::FTaskBase::IsCompleted().
IsTaskEvent()
bool FBaseGraphTask::IsTaskEvent () const inline
Returns true if this is a simple task event, which cannot execute code and must be manually dispatched.
Definition at line 548 of file TaskGraphInterfaces.h.
References UE::Tasks::Private::FTaskBase::GetExtendedPriority(), and UE::Tasks::TaskEvent.
Referenced by DontCompleteUntil(), and Unlock().
UE_DEPRECATED()
FBaseGraphTask::UE_DEPRECATED (5. 6, "Call AddPrerequisites separately if you need to add new tasks before dispatch") &
References FBaseGraphTask(), check, and DispatchSubsequents().
Unlock()
void FBaseGraphTask::Unlock (ENamedThreads::Type CurrentThreadIfKnown = ENamedThreads::AnyThread) inline
Unlocks a task that was returned from ConstructAndHold or CreateGraphEvent, which may execute immediately if prerequisites are already completed.
This can only be safely called exactly once and the caller is responsible for tracking that.
Definition at line 557 of file TaskGraphInterfaces.h.
References UE::Tasks::Private::FTaskBase::AddRef(), ENamedThreads::AnyThread, IsTaskEvent(), and UE::Tasks::Private::FTaskBase::TryLaunch().
Referenced by DispatchSubsequents().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Async/TaskGraphInterfaces.h