Unreal Engine 5.6 C++ API: UBasicLineSetComponentBase Class Reference
UBasicLineSetComponentBase Class Reference
UBasic2DLineSetComponent and UBasic3DLineSetComponent are components that draw a set of lines as small squares.
#include "BasicLineSetComponent.h"
Public Member Functions
UBasicLineSetComponentBase ()
void ClearComponent ()
Clears the component state and marks component as dirty.
void SetColor (FColor InColor)
Set per line material Line Color parameter that is uniform for all lines.
void SetLineMaterial (UMaterialInterface *InLineMaterial)
Specify material that handles lines.
void SetLineSetParameters (FColor InColor, float InSize, float InDepthBias)
Set per line material parameters that are uniform for all lines.
void SetLineThickness (float InSize)
Set per line material Line Size/Thickness parameter that is uniform for all lines.
Public Member Functions inherited from UMeshComponent
const TArray< TObjectPtr< UMaterialInterface > > & GetComponentMaterialSlotsOverlayMaterial () const
Retrieve the material slots overly materials assigned to this component.
virtual void GetDefaultMaterialSlotsOverlayMaterial (TArray< TObjectPtr< UMaterialInterface > > &OutMaterialSlotOverlayMaterials) const
Get all default material slots overlay materials from the mesh.
float GetScalarParameterDefaultValue (const FName ParameterName)
Returns default value for the parameter input.
UFUNCTION () 1 void SetColorParameterValueOnMaterials(const FName ParameterName
Set all occurrences of Vector Material Parameters with ParameterName in the set of materials of the SkeletalMesh to ParameterValue.
UFUNCTION () 1 void SetScalarParameterValueOnMaterials(const FName ParameterName
Set all occurrences of Scalar Material Parameters with ParameterName in the set of materials of the SkeletalMesh to ParameterValue.
UFUNCTION () 1 void SetVectorParameterValueOnMaterials(const FName ParameterName
Set all occurrences of Vector Material Parameters with ParameterName in the set of materials of the SkeletalMesh to ParameterValue.
Protected Member Functions
virtual int32 GetNumMaterials () const override
template<typename CalcLineBoxFn>
FBoxSphereBounds UpdateComponentBounds (const FTransform &LocalToWorld, bool bLinesDirty, CalcLineBoxFn &&CalcLineBox) const
Update component bounds using a provided function that determines the box around all line positions.
Protected Member Functions inherited from UMeshComponent
virtual void BeginDestroy () override
void CacheMaterialParameterNameIndices ()
Retrieves all the (scalar/vector-)parameters from within the used materials on the SkeletalMesh, and stores material index vs parameter names.
virtual UMaterialInterface * GetDefaultOverlayMaterial () const
Get the default overlay material used by a mesh.
virtual float GetDefaultOverlayMaterialMaxDrawDistance () const
Get the default overlay material max draw distance.
void MarkCachedMaterialParameterNameIndicesDirty ()
Mark cache parameters map as dirty, cache will be rebuild once SetScalar/SetVector functions are called.
Protected Attributes
bool bBoundsDirty = true
FBoxSphereBounds Bounds
FColor Color
float DepthBias = 0.0f
TObjectPtr< const UMaterialInterface > LineMaterial
float Size = 1.0f
Protected Attributes inherited from UMeshComponent
uint8 bCachedMaterialParameterIndicesAreDirty: 1
Whether or not to cache material parameter to speed up setting scalar or vector value on materials.
TSortedMap< FName, FMaterialParameterCache, FDefaultAllocator, FNameFastLess > MaterialParameterCache
Private Attributes
CURRENT_FILE_ID___LINE___GENERATED_BODY
Additional Inherited Members
Data Fields inherited from UMeshComponent
const float ParameterValue
const FVector ParameterValue
const FLinearColor ParameterValue
Detailed Description
UBasic2DLineSetComponent and UBasic3DLineSetComponent are components that draw a set of lines as small squares.
The 2D version stores XY coordinates with Z set to 0 whereas the 3D version stores XYZ coordinates. All lines have the same color, size, and depth bias based on what is set via SetLineSetParameters(). The lines are drawn as two triangles, i.e. a square, orthogonal to the view direction. The actual line size is calculated in the shader using a custom material.
Before inserting any lines via AddElement(), the maximum number of lines that will be added needs to be declared via ReserveElements(). The actual number of lines that were added is available via NumElements().
To support both 2D and 3D with minimal code duplication, the line set components are composed from the UBasicLineSetComponentBase class for the component specific functionality, and an instantiation of the TBasicElementSet template class for either FVector2f or FVector3f that encapsulates all line specific functionality. The final derived classes UBasic2DLineSetComponent and UBasic3DLineSetComponent contain identical boilerplate code to facilitate calls that need to go both to the component base class and the line base class, e.g. Clear() will both mark the component as dirty and delete all lines. Base class for component specific functionality independent of the type of line stored in the component.
Definition at line 30 of file BasicLineSetComponent.h.
Constructor & Destructor Documentation
UBasicLineSetComponentBase()
UBasicLineSetComponentBase::UBasicLineSetComponentBase ()
References UBasicLineSetComponentBase().
Referenced by UBasicLineSetComponentBase().
Member Function Documentation
ClearComponent()
void UBasicLineSetComponentBase::ClearComponent ()
Clears the component state and marks component as dirty.
References ClearComponent().
Referenced by UBasic2DLineSetComponent::Clear(), UBasic3DLineSetComponent::Clear(), and ClearComponent().
GetNumMaterials()
virtual int32 UBasicLineSetComponentBase::GetNumMaterials () const inline override protected virtual
Reimplemented from UMeshComponent.
Definition at line 56 of file BasicLineSetComponent.h.
References GetNumMaterials().
Referenced by GetNumMaterials().
SetColor()
void UBasicLineSetComponentBase::SetColor (FColor InColor)
Set per line material Line Color parameter that is uniform for all lines.
References SetColor().
Referenced by SetColor().
SetLineMaterial()
void UBasicLineSetComponentBase::SetLineMaterial (UMaterialInterface * InLineMaterial)
Specify material that handles lines.
References SetLineMaterial().
Referenced by SetLineMaterial().
SetLineSetParameters()
void UBasicLineSetComponentBase::SetLineSetParameters (FColor InColor, float InSize, float InDepthBias)
Set per line material parameters that are uniform for all lines.
References SetLineSetParameters().
Referenced by SetLineSetParameters().
SetLineThickness()
void UBasicLineSetComponentBase::SetLineThickness (float InSize)
Set per line material Line Size/Thickness parameter that is uniform for all lines.
References SetLineThickness().
Referenced by SetLineThickness().
UpdateComponentBounds()
template<typename CalcLineBoxFn> FBoxSphereBounds UBasicLineSetComponentBase::UpdateComponentBounds (const FTransform & LocalToWorld, bool bLinesDirty, CalcLineBoxFn && CalcLineBox) const inline protected
Update component bounds using a provided function that determines the box around all line positions.
This unifies how the bounds are calculated while keeping the calculation of the box around all line positions generic.
Definition at line 61 of file BasicLineSetComponent.h.
References bBoundsDirty, Bounds, Box, and Size.
Referenced by UBasic2DLineSetComponent::CalcBounds(), and UBasic3DLineSetComponent::CalcBounds().
Field Documentation
bBoundsDirty
bool UBasicLineSetComponentBase::bBoundsDirty = true mutable protected
Definition at line 95 of file BasicLineSetComponent.h.
Referenced by UpdateComponentBounds().
Bounds
FBoxSphereBounds UBasicLineSetComponentBase::Bounds mutable protected
Definition at line 92 of file BasicLineSetComponent.h.
Referenced by UpdateComponentBounds().
Color
FColor UBasicLineSetComponentBase::Color protected
Definition at line 98 of file BasicLineSetComponent.h.
CURRENT_FILE_ID___LINE___GENERATED_BODY
UBasicLineSetComponentBase::CURRENT_FILE_ID___LINE___GENERATED_BODY private
Definition at line 32 of file BasicLineSetComponent.h.
DepthBias
float UBasicLineSetComponentBase::DepthBias = 0.0f protected
Definition at line 104 of file BasicLineSetComponent.h.
LineMaterial
TObjectPtr<const UMaterialInterface> UBasicLineSetComponentBase::LineMaterial protected
Definition at line 89 of file BasicLineSetComponent.h.
Size
float UBasicLineSetComponentBase::Size = 1.0f protected
Definition at line 101 of file BasicLineSetComponent.h.
Referenced by UpdateComponentBounds().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Editor/UVEditor/Source/UVEditorTools/Public/Drawing/BasicLineSetComponent.h