Unreal Engine 5.6 C++ API: UE::Serialization::FEditorBulkData Class Reference
UE::Serialization::FEditorBulkData Class Reference final
The goal of this class is to provide an editor time version of BulkData that will work with the asset virtualization system.
#include "EditorBulkData.h"
Data Structures
struct FSharedBufferWithID
Utility struct used to compute the Payload ID before calling UpdatePayload.
Public Member Functions
FEditorBulkData ()=default
FEditorBulkData (const FEditorBulkData &Other)
FEditorBulkData (FEditorBulkData &&Other)
~FEditorBulkData ()
bool CanSaveForRegistry () const
Return true if the bulkdata has a source location that persists between editor processes (package file or virtualization).
FEditorBulkData CopyTornOff () const
Make a torn-off copy of this bulk data.
void CreateFromBulkData (FBulkData &BulkData, const FGuid &Guid, UObject *Owner)
Convenience method to make it easier to convert from FBulkData to FEditorBulkData and sets the Guid.
void CreateLegacyUniqueIdentifier (UObject *Owner)
Fix legacy content that created the Id from non-unique Guids.
void DetachFromDisk (FArchive *Ar, bool bEnsurePayloadIsLoaded)
Removes the ability for the bulkdata object to load it's payload from disk (if it was doing so)
bool DoesPayloadNeedLoading () const
Returns if the payload would require loading in order to be accessed.
void GetBulkDataVersions (FArchive &InlineArchive, FPackageFileVersion &OutUEVersion, int32 &OutLicenseeUEVersion, FCustomVersionContainer &OutCustomVersions) const
Get the versions used in the file containing the payload.
TFuture< FCompressedBuffer > GetCompressedPayload () const
Returns an immutable FCompressedBuffer reference to the payload data.
FGuid GetIdentifier () const
Returns a unique identifier for the object itself.
TFuture< FSharedBuffer > GetPayload () const
Returns an immutable FCompressedBuffer reference to the payload data.
const FIoHash & GetPayloadId () const
Returns an unique identifier for the content of the payload.
int64 GetPayloadSize () const
Returns the size of the payload in bytes.
bool HasPayloadData () const
Returns true if the bulkdata object contains a valid payload greater than zero bytes in size.
bool HasPlaceholderPayloadId () const
Return whether the BulkData has legacy payload id that needs to be updated from loaded payload before it can be used in DDC.
bool IsMemoryOnlyPayload () const
Return whether the BulkData is an in-memory payload without a persistent source location.
bool LocationMatches (const FEditorBulkData &Other) const
Return whether *this has the same source for the bulkdata (e.g.
FEditorBulkData & operator= (const FEditorBulkData &Other)
FEditorBulkData & operator= (FEditorBulkData &&Other)
void Reset ()
Reset to a truly empty state.
void Serialize (FArchive &Ar, UObject *Owner, bool bAllowRegister=true)
Used to serialize the bulkdata to/from a FArchive.
void SerializeForRegistry (FArchive &Ar)
Used to serialize the bulkdata to/from a limited cache system used by the BulkDataRegistry.
void SetCompressionOptions (ECompressedBufferCompressor Compressor, ECompressedBufferCompressionLevel CompressionLevel)
Sets the compression options to be applied to the payload during serialization.
void SetCompressionOptions (ECompressionOptions Option)
Sets the compression options to be applied to the payload during serialization.
void TearOff ()
Set this BulkData into Torn-Off mode.
UE_DEPRECATED (5.0, "SetVirtualizationOptOut is an internal feature for development and will be removed without warning!") 1 void SetVirtualizationOptOut(bool bOptOut)
UE_DEPRECATED (5.1, "Call GetBulkDataVersions instead.") 1 FCustomVersionContainer GetCustomVersions(FArchive &InlineArchive)
void UnloadData ()
Unloads the data (if possible) but leaves it in a state where the data can be reloaded.
void UpdatePayload (FCompressedBuffer InPayload, UObject *Owner=nullptr)
Replaces the existing payload (if any) with a new one.
void UpdatePayload (FSharedBuffer InPayload, UObject *Owner=nullptr)
Replaces the existing payload (if any) with a new one.
void UpdatePayload (FSharedBufferWithID InPayload, UObject *Owner=nullptr)
Allows the existing payload to be replaced with a new one.
void UpdatePayloadId ()
Load the payload and set the correct payload id, if the bulkdata has a PlaceholderPayloadId.
void UpdateRegistrationOwner (UObject *Owner)
Update the Owner of this BulkData in the BulkDataRegistry to include the Owner information.
Protected Types
enum class ETornOff
Protected Member Functions
FEditorBulkData (const FEditorBulkData &Other, ETornOff)
Private Types
enum class EFlags : uint32 {
None = 0 , IsVirtualized = 1 << 0 , HasPayloadSidecarFile = 1 << 1 , ReferencesLegacyFile = 1 << 2 ,
LegacyFileIsCompressed = 1 << 3 , DisablePayloadCompression = 1 << 4 , LegacyKeyWasGuidDerived = 1 << 5 , HasRegistered = 1 << 6 ,
IsTornOff = 1 << 7 , ReferencesWorkspaceDomain = 1 << 8 , StoredInPackageTrailer = 1 << 9 , IsCooked = 1 << 10 ,
WasDetached = 1 << 11
}
Flags used to store additional meta information about the bulk data.
enum ErrorVerbosity { None = 0 , All }
Used to control what level of error reporting we return from some methods.
Private Member Functions
EFlags BuildFlagsForSerialization (FArchive &Ar, bool bKeepFileDataByReference) const
bool CanLoadDataFromDisk () const
bool CanUnloadData () const
FRIEND_ENUM_CLASS_FLAGS (EFlags)
FText GetCorruptedPayloadErrorMsgForSave (FLinkerSave *Linker) const
Utility to return an apt error message if the payload is invalid when trying to save the bulkdata.
FCompressedBuffer GetDataInternal () const
bool HasAttachedArchive () const
Returns true when the bulkdata has an attachment to it's package file on disk, if the bulkdata later becomes detached then EFlag::WasDetached will be set.
bool HasPayloadSidecarFile () const
bool IsDataVirtualized () const
bool IsReferencingByPackagePath () const
bool IsReferencingOldBulkData () const
bool IsReferencingWorkspaceDomain () const
bool IsStoredInPackageTrailer () const
FCompressedBuffer LoadFromDisk () const
FCompressedBuffer LoadFromPackageFile () const
FCompressedBuffer LoadFromPackageTrailer () const
FCompressedBuffer LoadFromSidecarFile () const
FCompressedBuffer LoadFromSidecarFileInternal (ErrorVerbosity Verbosity) const
void LogRegisterError (UE::BulkDataRegistry::ERegisterResult Value, UObject *Owner, const FGuid &FailedBulkDataId, const TCHAR *CallerName, bool bHandledbyCreateUniqueGuid) const
void OnExitMemory ()
Used when we want to keep registration of our BulkDataId tied to our Payload location, but this BulkData is exiting memory and the registry needs to know so it can drop its copy of the payload and allow us to reregister later if reloaded.
FCompressedBuffer PullData () const
void PushData (const FPackagePath &InPackagePath)
void RecompressForSerialization (FCompressedBuffer &InOutPayload, EFlags PayloadFlags) const
void Register (UObject *Owner, const TCHAR *LogCallerName, bool bAllowUpdateId)
bool SerializeData (FArchive &Ar, FCompressedBuffer &Payload, const EFlags PayloadFlags) const
void SerializeToLegacyPath (FLinkerSave &LinkerSave, FCompressedBuffer PayloadToSerialize, EFlags UpdatedFlags, UObject *Owner)
Old legacy path that saved the payload to the end of the package.
void SerializeToPackageTrailer (FLinkerSave &LinkerSave, FCompressedBuffer PayloadToSerialize, EFlags UpdatedFlags, UObject *Owner)
The new path that saves payloads to the FPackageTrailer which is then appended to the end of the package file.
bool ShouldUseLegacySerialization (const FLinkerSave *LinkerSave) const
Returns true if we should use legacy serialization instead of the FPackageTrailer system.
bool TryPayloadValidationForSaving (const FCompressedBuffer &PayloadForSaving, FLinkerSave *LinkerSave) const
Checks to make sure that the payload we are saving is what we expect it to be.
void Unregister ()
Used when we need to clear the registration for our bulkdataId because its ownership is transferring elsewhere.
void UpdateKeyIfNeeded ()
void UpdateKeyIfNeeded (FCompressedBuffer InPayload) const
void UpdatePayloadImpl (FSharedBuffer &&InPayload, const FIoHash &InPayloadID, UObject *Owner)
void UpdateRegistrationData (UObject *Owner, const TCHAR *LogCallerName, bool bAllowUpdateId)
Check whether we should be registered, and register/unregister/update as necessary to match.
Static Private Member Functions
static bool IsDataVirtualized (EFlags InFlags)
static bool IsReferencingByPackagePath (EFlags InFlags)
static bool IsReferencingOldBulkData (EFlags InFlags)
static bool IsReferencingWorkspaceDomain (EFlags InFlags)
static bool IsStoredInPackageTrailer (EFlags InFlags)
static void ValidatePackageTrailerBuilder (const FLinkerSave *LinkerSave, const FIoHash &Id, EFlags PayloadFlags)
A utility for validating that a package trailer builder was created correctly.
Private Attributes
FArchive * AttachedAr = nullptr
The archive representing the file on disk containing the payload (if there is one), we keep the pointer so that the bulkdata object can be detached if needed.
bool bSkipVirtualization = false
FGuid BulkDataId
Unique identifier for the bulkdata object itself.
Private::FCompressionSettings CompressionSettings
Compression settings to be applied to the payload when the package is next saved.
EFlags Flags = EFlags::None
A 32bit bitfield of flags.
FRecursiveMutex Mutex
int64 OffsetInFile = INDEX_NONE
Offset of the payload in the file that contains it (INDEX_NONE if the payload does not come from a file)
FPackagePath PackagePath
PackagePath containing the payload (this will be empty if the payload does not come from PackageResourceManager)
FSharedBuffer Payload
Pointer to the payload if it is held in memory (it has been updated but not yet saved to disk for example)
FIoHash PayloadContentId
Unique identifier for the contents of the payload.
int64 PayloadSize = 0
Length of the payload in bytes.
Static Private Attributes
static constexpr EFlags TransientFlags = EFlags((uint32)EFlags::HasRegistered | (uint32)EFlags::IsTornOff | (uint32)EFlags::WasDetached)
A common grouping of EFlags.
Friends
struct FTocEntry
Detailed Description
The goal of this class is to provide an editor time version of BulkData that will work with the asset virtualization system.
Assuming that the DDC is hot, the virtualized payloads are accessed relatively infrequently, usually when the package is being edited in the editor in some manner. So the payload access is designed around this. If the data is frequently accessed when running the editor then the user would not gain from having it virtualized as they would end up pulling it immediately anyway.
The biggest difference with normal bulkdata is that the access times might be significantly longer if the payload is not readily available which is why the only way to access the payload is by a TFuture or a callback so that the caller is forced to consider how to handle the potential stall and hopefully organize their code in such a way that the time lag is not noticeable to the user.
The second biggest difference is that the caller will own the payload memory once it is returned to them, unlike the old bulkdata class which would retain ownership. Which forces the calling code to be in control of when the memory is actually allocated and for how long. With the old bulkdata class a single access would leave that memory allocated in a non-obvious way and would lead to memory bloats within the editor.
The method ::GetGuid can be used to access a unique identifier for the payload, currently it is based on the payload itself, so that two objects with the same payload would both have the same Guid. The intent is that we would be able to share local copies of the payload between branches to reduce the cost of having multiple branches with similar data on the same machine.
Updating the bulkdata: Unlike the older bulkdata system, EditorBulkData does not support any lock/unlock mechanism, instead the internal data is updated via a single call to UpdatePayload and the data is retrieved via a single call to GetPayload.
For examples see the "System.CoreUObject.Serialization.EditorBulkData.UpdatePayload" test found in Engine\Source\Runtime\CoreUObject\Private\Tests\Serialization\EditorBulkDataTests.cpp.
Thread Safety:
The class should be thread safe in that you can call the public methods on multiple threads at once and expect things to work. However if you were to call GetPayloadSize() before calling GetPayload() on one thread it would be possible for a call to UpdatePayload() to occur on another thread in between those two calls, meaning that the size you got might not be the correct size as the payload returned. If you need that level of thread safety it would be up to you to manage it at a higher level. It would however be safe to pass a copy of your FEditorBulkData to a background task rather than a reference. The copy would either be able to load the payload from disk, pull it from virtualized storage or if the source bulkdata is holding the payload in memory it will just take a reference to that payload rather than making a copy. In this way you can be sure of the state of the FEditorBulkData on the background task as future edits to the original bulkdata will not affect it. The base class with no type
Definition at line 131 of file EditorBulkData.h.
Member Enumeration Documentation
EFlags
enum class UE::Serialization::FEditorBulkData::EFlags : uint32 strong private
Flags used to store additional meta information about the bulk data.
Enumerator
None
No flags are set.
IsVirtualized
Is the data actually virtualized or not?
HasPayloadSidecarFile
Does the package have access to a .upayload file?
ReferencesLegacyFile
The bulkdata object is currently referencing a payload saved under old bulkdata formats.
LegacyFileIsCompressed
The legacy file being referenced is stored with Zlib compression format.
DisablePayloadCompression
The payload should not have compression applied to it.
It is assumed that the payload is already in some sort of compressed format, see the compression documentation above for more details.
LegacyKeyWasGuidDerived
The legacy file being referenced derived its key from guid and it should be replaced with a key-from-hash when saved.
HasRegistered
(Transient) The Guid has been registered with the BulkDataRegistry
IsTornOff
(Transient) The BulkData object is a copy used only to represent the id and payload; it does not communicate with the BulkDataRegistry, and will point DDC jobs toward the original BulkData
ReferencesWorkspaceDomain
The bulkdata object references a payload stored in a WorkspaceDomain file.
StoredInPackageTrailer
The payload is stored in a package trailer, so the bulkdata object will have to poll the trailer to find the payload offset.
IsCooked
The bulkdata object was cooked.
WasDetached
(Transient) The package owning the bulkdata has been detached from disk and we can no longer load from it
Definition at line 377 of file EditorBulkData.h.
ErrorVerbosity
enum UE::Serialization::FEditorBulkData::ErrorVerbosity private
Used to control what level of error reporting we return from some methods.
Enumerator
None
No errors should be logged.
All
Everything should be logged.
Definition at line 414 of file EditorBulkData.h.
ETornOff
enum class UE::Serialization::FEditorBulkData::ETornOff strong protected
Definition at line 370 of file EditorBulkData.h.
Constructor & Destructor Documentation
FEditorBulkData() [1/4]
UE::Serialization::FEditorBulkData::FEditorBulkData () default
Referenced by FEditorBulkData(), FEditorBulkData(), FEditorBulkData(), CopyTornOff(), LocationMatches(), operator=(), and operator=().
~FEditorBulkData()
UE::Serialization::FEditorBulkData::~FEditorBulkData ()
FEditorBulkData() [2/4]
UE::Serialization::FEditorBulkData::FEditorBulkData (FEditorBulkData && Other)
References FEditorBulkData(), and Other.
FEditorBulkData() [3/4]
UE::Serialization::FEditorBulkData::FEditorBulkData (const FEditorBulkData & Other)
References FEditorBulkData(), and Other.
FEditorBulkData() [4/4]
UE::Serialization::FEditorBulkData::FEditorBulkData (const FEditorBulkData & Other, ETornOff) protected
References FEditorBulkData(), and Other.
Member Function Documentation
BuildFlagsForSerialization()
EFlags UE::Serialization::FEditorBulkData::BuildFlagsForSerialization (FArchive & Ar, bool bKeepFileDataByReference) const private
References Ar.
CanLoadDataFromDisk()
bool UE::Serialization::FEditorBulkData::CanLoadDataFromDisk () const private
CanSaveForRegistry()
bool UE::Serialization::FEditorBulkData::CanSaveForRegistry () const
Return true if the bulkdata has a source location that persists between editor processes (package file or virtualization).
CanUnloadData()
bool UE::Serialization::FEditorBulkData::CanUnloadData () const private
CopyTornOff()
FEditorBulkData UE::Serialization::FEditorBulkData::CopyTornOff () const inline
Make a torn-off copy of this bulk data.
Definition at line 329 of file EditorBulkData.h.
References FEditorBulkData(), and CopyTornOff().
Referenced by CopyTornOff().
CreateFromBulkData()
void UE::Serialization::FEditorBulkData::CreateFromBulkData (FBulkData & BulkData, const FGuid & Guid, UObject * Owner)
Convenience method to make it easier to convert from FBulkData to FEditorBulkData and sets the Guid.
Parameters
BulkData The bulkdata object to create from.
Guid A guid associated with the bulkdata object which will be used to identify the payload. This MUST remain the same between sessions so that the payloads key remains consistent!
References Guid, and Owner.
CreateLegacyUniqueIdentifier()
void UE::Serialization::FEditorBulkData::CreateLegacyUniqueIdentifier (UObject * Owner)
Fix legacy content that created the Id from non-unique Guids.
Run on objects created before FUE5MainStreamObjectVersion::VirtualizedBulkDataHaveUniqueGuids
References Owner.
DetachFromDisk()
void UE::Serialization::FEditorBulkData::DetachFromDisk (FArchive * Ar, bool bEnsurePayloadIsLoaded)
Removes the ability for the bulkdata object to load it's payload from disk (if it was doing so)
Parameters
Ar The archive that the bulkdata is being detached from. This should match AttachedAr.
bEnsurePayloadIsLoaded If true and the bulkdata currently is storing it's payload as a package on disk then the payload should be loaded into memory so that it can be accessed in the future. If false then the payload is not important and does not need to be loaded.
References Ar.
DoesPayloadNeedLoading()
bool UE::Serialization::FEditorBulkData::DoesPayloadNeedLoading () const
Returns if the payload would require loading in order to be accessed.
Returns false if the payload is already in memory or of zero length
FRIEND_ENUM_CLASS_FLAGS()
UE::Serialization::FEditorBulkData::FRIEND_ENUM_CLASS_FLAGS (EFlags) private
GetBulkDataVersions()
void UE::Serialization::FEditorBulkData::GetBulkDataVersions (FArchive & InlineArchive, FPackageFileVersion & OutUEVersion, int32 & OutLicenseeUEVersion, FCustomVersionContainer & OutCustomVersions) const
Get the versions used in the file containing the payload.
Parameters
InlineArchive The archive that was used to load this object
References GetBulkDataVersions().
Referenced by GetBulkDataVersions().
GetCompressedPayload()
TFuture< FCompressedBuffer > UE::Serialization::FEditorBulkData::GetCompressedPayload () const
Returns an immutable FCompressedBuffer reference to the payload data.
Note that depending on the internal storage formats, the payload might not actually be compressed, but that will be handled by the FCompressedBuffer interface. Call FCompressedBuffer::Decompress() to get access to the payload in FSharedBuffer format.
GetCorruptedPayloadErrorMsgForSave()
FText UE::Serialization::FEditorBulkData::GetCorruptedPayloadErrorMsgForSave (FLinkerSave * Linker) const private
Utility to return an apt error message if the payload is invalid when trying to save the bulkdata.
It will try to provide the best info from the given options.
Parameters
Linker The FLinkerSave being used to save the bulkdata at the point of error. This can be nullptr if the bulkdata is not being saved to a package on disk.
Returns
The formatted error message.
GetDataInternal()
FCompressedBuffer UE::Serialization::FEditorBulkData::GetDataInternal () const private
GetIdentifier()
FGuid UE::Serialization::FEditorBulkData::GetIdentifier () const
Returns a unique identifier for the object itself.
GetPayload()
TFuture< FSharedBuffer > UE::Serialization::FEditorBulkData::GetPayload () const
Returns an immutable FCompressedBuffer reference to the payload data.
GetPayloadId()
const FIoHash & UE::Serialization::FEditorBulkData::GetPayloadId () const
Returns an unique identifier for the content of the payload.
GetPayloadSize()
int64 UE::Serialization::FEditorBulkData::GetPayloadSize () const inline
Returns the size of the payload in bytes.
Definition at line 196 of file EditorBulkData.h.
References PayloadSize.
HasAttachedArchive()
bool UE::Serialization::FEditorBulkData::HasAttachedArchive () const inline private
Returns true when the bulkdata has an attachment to it's package file on disk, if the bulkdata later becomes detached then EFlag::WasDetached will be set.
Definition at line 506 of file EditorBulkData.h.
References AttachedAr.
HasPayloadData()
bool UE::Serialization::FEditorBulkData::HasPayloadData () const inline
Returns true if the bulkdata object contains a valid payload greater than zero bytes in size.
Definition at line 202 of file EditorBulkData.h.
References PayloadSize.
HasPayloadSidecarFile()
bool UE::Serialization::FEditorBulkData::HasPayloadSidecarFile () const inline private
Definition at line 461 of file EditorBulkData.h.
References EnumHasAnyFlags(), Flags, and HasPayloadSidecarFile.
HasPlaceholderPayloadId()
bool UE::Serialization::FEditorBulkData::HasPlaceholderPayloadId () const inline
Return whether the BulkData has legacy payload id that needs to be updated from loaded payload before it can be used in DDC.
Definition at line 343 of file EditorBulkData.h.
References EnumHasAnyFlags(), Flags, and LegacyKeyWasGuidDerived.
IsDataVirtualized() [1/2]
bool UE::Serialization::FEditorBulkData::IsDataVirtualized () const inline private
Definition at line 451 of file EditorBulkData.h.
References Flags, and IsDataVirtualized().
Referenced by IsDataVirtualized().
IsDataVirtualized() [2/2]
bool UE::Serialization::FEditorBulkData::IsDataVirtualized (EFlags InFlags) inline static private
Definition at line 456 of file EditorBulkData.h.
References EnumHasAnyFlags(), and IsVirtualized.
IsMemoryOnlyPayload()
bool UE::Serialization::FEditorBulkData::IsMemoryOnlyPayload () const
Return whether the BulkData is an in-memory payload without a persistent source location.
IsReferencingByPackagePath() [1/2]
bool UE::Serialization::FEditorBulkData::IsReferencingByPackagePath () const inline private
Definition at line 484 of file EditorBulkData.h.
References Flags, and IsReferencingByPackagePath().
Referenced by IsReferencingByPackagePath().
IsReferencingByPackagePath() [2/2]
bool UE::Serialization::FEditorBulkData::IsReferencingByPackagePath (EFlags InFlags) inline static private
Definition at line 488 of file EditorBulkData.h.
References EnumHasAnyFlags(), ReferencesLegacyFile, and ReferencesWorkspaceDomain.
IsReferencingOldBulkData() [1/2]
bool UE::Serialization::FEditorBulkData::IsReferencingOldBulkData () const inline private
Definition at line 466 of file EditorBulkData.h.
References Flags, and IsReferencingOldBulkData().
Referenced by IsReferencingOldBulkData().
IsReferencingOldBulkData() [2/2]
bool UE::Serialization::FEditorBulkData::IsReferencingOldBulkData (EFlags InFlags) inline static private
Definition at line 470 of file EditorBulkData.h.
References EnumHasAnyFlags(), and ReferencesLegacyFile.
IsReferencingWorkspaceDomain() [1/2]
bool UE::Serialization::FEditorBulkData::IsReferencingWorkspaceDomain () const inline private
Definition at line 475 of file EditorBulkData.h.
References Flags, and IsReferencingWorkspaceDomain().
Referenced by IsReferencingWorkspaceDomain().
IsReferencingWorkspaceDomain() [2/2]
bool UE::Serialization::FEditorBulkData::IsReferencingWorkspaceDomain (EFlags InFlags) inline static private
Definition at line 479 of file EditorBulkData.h.
References EnumHasAnyFlags(), and ReferencesWorkspaceDomain.
IsStoredInPackageTrailer() [1/2]
bool UE::Serialization::FEditorBulkData::IsStoredInPackageTrailer () const inline private
Definition at line 493 of file EditorBulkData.h.
References Flags, and IsStoredInPackageTrailer().
Referenced by IsStoredInPackageTrailer().
IsStoredInPackageTrailer() [2/2]
bool UE::Serialization::FEditorBulkData::IsStoredInPackageTrailer (EFlags InFlags) inline static private
Definition at line 497 of file EditorBulkData.h.
References EnumHasAnyFlags(), and StoredInPackageTrailer.
LoadFromDisk()
FCompressedBuffer UE::Serialization::FEditorBulkData::LoadFromDisk () const private
LoadFromPackageFile()
FCompressedBuffer UE::Serialization::FEditorBulkData::LoadFromPackageFile () const private
LoadFromPackageTrailer()
FCompressedBuffer UE::Serialization::FEditorBulkData::LoadFromPackageTrailer () const private
LoadFromSidecarFile()
FCompressedBuffer UE::Serialization::FEditorBulkData::LoadFromSidecarFile () const private
LoadFromSidecarFileInternal()
FCompressedBuffer UE::Serialization::FEditorBulkData::LoadFromSidecarFileInternal (ErrorVerbosity Verbosity) const private
LocationMatches()
bool UE::Serialization::FEditorBulkData::LocationMatches (const FEditorBulkData & Other) const
Return whether *this has the same source for the bulkdata (e.g.
identical file locations if from file) as Other
References FEditorBulkData(), and Other.
LogRegisterError()
void UE::Serialization::FEditorBulkData::LogRegisterError (UE::BulkDataRegistry::ERegisterResult Value, UObject * Owner, const FGuid & FailedBulkDataId, const TCHAR * CallerName, bool bHandledbyCreateUniqueGuid) const private
References Owner, and Value.
OnExitMemory()
void UE::Serialization::FEditorBulkData::OnExitMemory () private
Used when we want to keep registration of our BulkDataId tied to our Payload location, but this BulkData is exiting memory and the registry needs to know so it can drop its copy of the payload and allow us to reregister later if reloaded.
operator=() [1/2]
FEditorBulkData & UE::Serialization::FEditorBulkData::operator= (const FEditorBulkData & Other)
References FEditorBulkData(), and Other.
operator=() [2/2]
FEditorBulkData & UE::Serialization::FEditorBulkData::operator= (FEditorBulkData && Other)
References FEditorBulkData(), and Other.
PullData()
FCompressedBuffer UE::Serialization::FEditorBulkData::PullData () const private
PushData()
void UE::Serialization::FEditorBulkData::PushData (const FPackagePath & InPackagePath) private
RecompressForSerialization()
void UE::Serialization::FEditorBulkData::RecompressForSerialization (FCompressedBuffer & InOutPayload, EFlags PayloadFlags) const private
Register()
void UE::Serialization::FEditorBulkData::Register (UObject * Owner, const TCHAR * LogCallerName, bool bAllowUpdateId) private
References Owner.
Reset()
void UE::Serialization::FEditorBulkData::Reset ()
Reset to a truly empty state.
Serialize()
void UE::Serialization::FEditorBulkData::Serialize (FArchive & Ar, UObject * Owner, bool bAllowRegister = true)
Used to serialize the bulkdata to/from a FArchive.
Parameters
Ar The archive to serialize the bulkdata.
Owner The UObject that contains the bulkdata object, if this is a nullptr then the bulkdata will assume that it must serialize the payload immediately to memory as it will not be able to identify it's package path.
bAllowRegistry Legacy parameter to skip registration when loading BulkData we know we will need to modify the identifier of. Should always be true for non-legacy serialization.
References Ar, and Owner.
SerializeData()
bool UE::Serialization::FEditorBulkData::SerializeData (FArchive & Ar, FCompressedBuffer & Payload, const EFlags PayloadFlags) const private
References Ar, and Payload.
SerializeForRegistry()
void UE::Serialization::FEditorBulkData::SerializeForRegistry (FArchive & Ar)
Used to serialize the bulkdata to/from a limited cache system used by the BulkDataRegistry.
References Ar.
SerializeToLegacyPath()
void UE::Serialization::FEditorBulkData::SerializeToLegacyPath (FLinkerSave & LinkerSave, FCompressedBuffer PayloadToSerialize, EFlags UpdatedFlags, UObject * Owner) private
Old legacy path that saved the payload to the end of the package.
References Owner.
SerializeToPackageTrailer()
void UE::Serialization::FEditorBulkData::SerializeToPackageTrailer (FLinkerSave & LinkerSave, FCompressedBuffer PayloadToSerialize, EFlags UpdatedFlags, UObject * Owner) private
The new path that saves payloads to the FPackageTrailer which is then appended to the end of the package file.
References Owner.
SetCompressionOptions() [1/2]
void UE::Serialization::FEditorBulkData::SetCompressionOptions (ECompressedBufferCompressor Compressor, ECompressedBufferCompressionLevel CompressionLevel)
Sets the compression options to be applied to the payload during serialization.
These settings will continue to be used until the bulkdata object is reset, a subsequent call to SetCompressionOptions is made or the owning package is serialized to disk.
Parameters
Compressor The Oodle compressor to use.
See also
ECompressedBufferCompressor
Parameters
CompressionLevel The Oodle compression level to use.
See also
ECompressedBufferCompressionLevel
SetCompressionOptions() [2/2]
void UE::Serialization::FEditorBulkData::SetCompressionOptions (ECompressionOptions Option)
Sets the compression options to be applied to the payload during serialization.
These settings will continue to be used until the bulkdata object is reset, a subsequent call to SetCompressionOptions is made or the owning package is serialized to disk.
Parameters
Option The high level option to use.
See also
UE::Serialization::ECompressionOptions
ShouldUseLegacySerialization()
bool UE::Serialization::FEditorBulkData::ShouldUseLegacySerialization (const FLinkerSave * LinkerSave) const private
Returns true if we should use legacy serialization instead of the FPackageTrailer system.
This can be removed when UE_ENABLE_VIRTUALIZATION_TOGGLE is removed.
TearOff()
void UE::Serialization::FEditorBulkData::TearOff ()
Set this BulkData into Torn-Off mode.
It will no longer register with the BulkDataRegistry, even if copied from another BulkData, and it will pass on this flag to any BulkData copied/moved from it. Use Reset() to remove this state. Torn-off BulkDatas share the guid with the BulkData they copy from.
References TearOff().
Referenced by TearOff().
TryPayloadValidationForSaving()
bool UE::Serialization::FEditorBulkData::TryPayloadValidationForSaving (const FCompressedBuffer & PayloadForSaving, FLinkerSave * LinkerSave) const private
Checks to make sure that the payload we are saving is what we expect it to be.
If not then we need to log an error to the user, mark the archive as having an error and return. This error is not reasonable to expect, if it occurs then it means something has gone very wrong, which is why there is also an ensure to make sure that any instances of it occurring as properly recorded and can be investigated.
UE_DEPRECATED() [1/2]
UE::Serialization::FEditorBulkData::UE_DEPRECATED (5. 0, "SetVirtualizationOptOut is an internal feature for development and will be removed without warning!")
UE_DEPRECATED() [2/2]
UE::Serialization::FEditorBulkData::UE_DEPRECATED (5. 1, "Call GetBulkDataVersions instead.") &
UnloadData()
void UE::Serialization::FEditorBulkData::UnloadData ()
Unloads the data (if possible) but leaves it in a state where the data can be reloaded.
Unregister()
void UE::Serialization::FEditorBulkData::Unregister () private
Used when we need to clear the registration for our bulkdataId because its ownership is transferring elsewhere.
UpdateKeyIfNeeded() [1/2]
void UE::Serialization::FEditorBulkData::UpdateKeyIfNeeded () private
UpdateKeyIfNeeded() [2/2]
void UE::Serialization::FEditorBulkData::UpdateKeyIfNeeded (FCompressedBuffer InPayload) const private
UpdatePayload() [1/3]
void UE::Serialization::FEditorBulkData::UpdatePayload (FCompressedBuffer InPayload, UObject * Owner = nullptr)
Replaces the existing payload (if any) with a new one.
Note that FCompressedBuffers already know the FIoHash of the raw payload and so we do not recalculate it, making this method much faster for larger payloads than the other overloads.
Parameters
InPayload The payload that this bulkdata object should reference.
See also
FCompressedBuffer
Parameters
Owner The object that owns the bulkdata, or null to not associate with a UObject.
References Owner.
UpdatePayload() [2/3]
void UE::Serialization::FEditorBulkData::UpdatePayload (FSharedBuffer InPayload, UObject * Owner = nullptr)
Replaces the existing payload (if any) with a new one.
It is important to consider the ownership model of the payload being passed in to the method.
To pass in a raw pointer use 'FSharedBuffer::...(Data, Size)' to create a valid FSharedBuffer. Use 'FSharedBuffer::MakeView' if you want to retain ownership on the data being passed in, and use 'FSharedBuffer::TakeOwnership' if you are okay with the bulkdata object taking over ownership of it. The bulkdata object must own its internal buffer, so if you pass in a non-owned FSharedBuffer (ie by using 'FSharedBuffer::MakeView') then a clone of the data will be created internally and assigned to the bulkdata object.
Parameters
InPayload The payload that this bulkdata object should reference.
See also
FSharedBuffer
Parameters
Owner The object that owns the bulkdata, or null to not associate with a UObject.
References Owner.
UpdatePayload() [3/3]
void UE::Serialization::FEditorBulkData::UpdatePayload (FSharedBufferWithID InPayload, UObject * Owner = nullptr)
Allows the existing payload to be replaced with a new one.
To pass in a raw pointer use 'FSharedBuffer::...(Data, Size)' to create a valid FSharedBuffer. Use 'FSharedBuffer::MakeView' if you want to retain ownership on the data being passed in, and use 'FSharedBuffer::TakeOwnership' if you are okay with the bulkdata object taking over ownership of it. The bulkdata object must own its internal buffer, so if you pass in a non-owned FSharedBuffer (ie by using 'FSharedBuffer::MakeView') then a clone of the data will be created internally and assigned to the bulkdata object.
Use this override if you want compute PayloadId before updating the bulkdata
Parameters
InPayload The payload to update the bulkdata with
Owner The object that owns the bulkdata, or null to not associate with a UObject.
References Owner.
UpdatePayloadId()
void UE::Serialization::FEditorBulkData::UpdatePayloadId ()
Load the payload and set the correct payload id, if the bulkdata has a PlaceholderPayloadId.
UpdatePayloadImpl()
void UE::Serialization::FEditorBulkData::UpdatePayloadImpl (FSharedBuffer && InPayload, const FIoHash & InPayloadID, UObject * Owner) private
References Owner.
UpdateRegistrationData()
void UE::Serialization::FEditorBulkData::UpdateRegistrationData (UObject * Owner, const TCHAR * LogCallerName, bool bAllowUpdateId) private
Check whether we should be registered, and register/unregister/update as necessary to match.
References Owner.
UpdateRegistrationOwner()
void UE::Serialization::FEditorBulkData::UpdateRegistrationOwner (UObject * Owner)
Update the Owner of this BulkData in the BulkDataRegistry to include the Owner information.
Has no effect if the BulkData is not valid for registration. The Owner information is lost and this function must be called again if the BulkData's payload information is modified.
References Owner.
ValidatePackageTrailerBuilder()
void UE::Serialization::FEditorBulkData::ValidatePackageTrailerBuilder (const FLinkerSave * LinkerSave, const FIoHash & Id, EFlags PayloadFlags) static private
A utility for validating that a package trailer builder was created correctly.
If a problem is encountered we will assert to prevent a corrupted package from being saved. The main thing we check is that the payload was added to the correct list for the correct payload storage type based on the flags we have for the payload. Note that it is not expected that we will ever encounter these problems (so asserting is acceptable) and the checks could be considered a little over cautious. We should consider just removing this check in 5.2 onwards.
Parameters
LinkerSave The linker containing the package trailer builder
Id The hash of the payload we want to verify
PayloadFlags The flags for the payload.
Friends And Related Symbol Documentation
FTocEntry
friend struct FTocEntry friend
Definition at line 374 of file EditorBulkData.h.
References FTocEntry.
Referenced by FTocEntry.
Field Documentation
AttachedAr
FArchive* UE::Serialization::FEditorBulkData::AttachedAr = nullptr private
The archive representing the file on disk containing the payload (if there is one), we keep the pointer so that the bulkdata object can be detached if needed.
Definition at line 572 of file EditorBulkData.h.
Referenced by HasAttachedArchive().
bSkipVirtualization
bool UE::Serialization::FEditorBulkData::bSkipVirtualization = false private
Definition at line 587 of file EditorBulkData.h.
BulkDataId
FGuid UE::Serialization::FEditorBulkData::BulkDataId private
Unique identifier for the bulkdata object itself.
Definition at line 558 of file EditorBulkData.h.
CompressionSettings
Private::FCompressionSettings UE::Serialization::FEditorBulkData::CompressionSettings private
Compression settings to be applied to the payload when the package is next saved.
The settings will be reset if the payload is unloaded from memory during serialization (i.e. the payload was virtualized or the package was saved to disk.&
Definition at line 595 of file EditorBulkData.h.
Flags
EFlags UE::Serialization::FEditorBulkData::Flags = EFlags::None private
A 32bit bitfield of flags.
Definition at line 581 of file EditorBulkData.h.
Referenced by HasPayloadSidecarFile(), HasPlaceholderPayloadId(), IsDataVirtualized(), IsReferencingByPackagePath(), IsReferencingOldBulkData(), IsReferencingWorkspaceDomain(), and IsStoredInPackageTrailer().
Mutex
FRecursiveMutex UE::Serialization::FEditorBulkData::Mutex mutable private
Definition at line 584 of file EditorBulkData.h.
OffsetInFile
int64 UE::Serialization::FEditorBulkData::OffsetInFile = INDEX_NONE private
Offset of the payload in the file that contains it (INDEX_NONE if the payload does not come from a file)
Definition at line 575 of file EditorBulkData.h.
PackagePath
FPackagePath UE::Serialization::FEditorBulkData::PackagePath private
PackagePath containing the payload (this will be empty if the payload does not come from PackageResourceManager)
Definition at line 578 of file EditorBulkData.h.
Payload
FSharedBuffer UE::Serialization::FEditorBulkData::Payload private
Pointer to the payload if it is held in memory (it has been updated but not yet saved to disk for example)
Definition at line 564 of file EditorBulkData.h.
Referenced by SerializeData().
PayloadContentId
FIoHash UE::Serialization::FEditorBulkData::PayloadContentId private
Unique identifier for the contents of the payload.
Definition at line 561 of file EditorBulkData.h.
PayloadSize
int64 UE::Serialization::FEditorBulkData::PayloadSize = 0 private
Length of the payload in bytes.
Definition at line 567 of file EditorBulkData.h.
Referenced by GetPayloadSize(), and HasPayloadData().
TransientFlags
EFlags UE::Serialization::FEditorBulkData::TransientFlags = EFlags((uint32)EFlags::HasRegistered | (uint32)EFlags::IsTornOff | (uint32)EFlags::WasDetached) static constexpr private
A common grouping of EFlags.
Definition at line 411 of file EditorBulkData.h.
The documentation for this class was generated from the following file:
Runtime/CoreUObject/Public/Serialization/EditorBulkData.h