Unreal Engine 5.6 C++ API: FShaderCode Class Reference
FShaderCode Class Reference
#include "ShaderCore.h"
Public Member Functions
FShaderCode ()
template<class T>
void AddOptionalData (const T &In)
void AddOptionalData (EShaderOptionalDataKey Key, const ANSICHAR *InString)
void AddOptionalData (EShaderOptionalDataKey Key, const uint8 *ValuePtr, uint32 ValueSize)
void Compress (FName ShaderCompressionFormat, FOodleDataCompression::ECompressor InOodleCompressor, FOodleDataCompression::ECompressionLevel InOodleLevel)
void FinalizeShaderCode (FCompressedBuffer OverrideSymbolsBuffer=FCompressedBuffer()) const
FName GetCompressionFormat () const
const FShaderCodeResource & GetFinalizedResource (EShaderFrequency Frequency, FSHAHash OutputHash) const
FOodleDataCompression::ECompressor GetOodleCompressor () const
FOodleDataCompression::ECompressionLevel GetOodleLevel () const
TConstArrayView< uint8 > GetReadView () const
int32 GetShaderCodeSize () const
TConstArrayView< uint8 > GetSymbolReadView () const
TArray< uint8 > & GetSymbolWriteAccess ()
int32 GetUncompressedSize () const
TArray< uint8 > & GetWriteAccess ()
bool IsCompressed () const
void SetFromResource (FShaderCodeResource &&Resource)
UE_DEPRECATED (5.5, "Use GetReadView") const TArray< uint8 > &GetReadAccess() const
Private Attributes
FName CompressionFormat
Compression algo.
FOodleDataCompression::ECompressor OodleCompressor
Oodle-specific compression algorithm - used if CompressionFormat is set to NAME_Oodle.
FOodleDataCompression::ECompressionLevel OodleLevel
Oodle-specific compression level - used if CompressionFormat is set to NAME_Oodle.
int32 OptionalDataSize
FShaderCodeResource ShaderCodeResource
int32 ShaderCodeSize
We cannot get the code size after the compression, so store it here.
TArray< uint8 > ShaderCodeWithOptionalData
TArray< uint8 > SymbolData
int32 UncompressedSize
ShaderCode may be compressed in SCWs on demand.
Friends
RENDERCORE_API FArchive & operator<< (FArchive &Ar, FShaderCode &Output)
Detailed Description
Definition at line 1238 of file ShaderCore.h.
Constructor & Destructor Documentation
FShaderCode()
FShaderCode::FShaderCode () inline
Definition at line 1266 of file ShaderCore.h.
References CompressionFormat, None, OodleCompressor, OodleLevel, OptionalDataSize, ShaderCodeSize, and UncompressedSize.
Referenced by operator<<.
Member Function Documentation
AddOptionalData() [1/3]
template<class T> void FShaderCode::AddOptionalData (const T & In) inline
Definition at line 1382 of file ShaderCore.h.
References AddOptionalData().
Referenced by AddOptionalData(), and AddOptionalData().
AddOptionalData() [2/3]
void FShaderCode::AddOptionalData (EShaderOptionalDataKey Key, const ANSICHAR * InString) inline
Definition at line 1407 of file ShaderCore.h.
References AddOptionalData(), Key, TCString< ANSICHAR >::Strlen(), and TSequenceHistory< HistorySize >::Size.
AddOptionalData() [3/3]
void FShaderCode::AddOptionalData (EShaderOptionalDataKey Key, const uint8 * ValuePtr, uint32 ValueSize) inline
Definition at line 1391 of file ShaderCore.h.
References check, Key, OptionalDataSize, and ShaderCodeWithOptionalData.
Compress()
void FShaderCode::Compress (FName ShaderCompressionFormat, FOodleDataCompression::ECompressor InOodleCompressor, FOodleDataCompression::ECompressionLevel InOodleLevel)
FinalizeShaderCode()
void FShaderCode::FinalizeShaderCode (FCompressedBuffer OverrideSymbolsBuffer = FCompressedBuffer()) const inline
Definition at line 1277 of file ShaderCore.h.
References check, checkf, FCompressedBuffer::Compress(), MakeSharedBufferFromArray(), MoveTemp(), OptionalDataSize, ShaderCodeResource, ShaderCodeWithOptionalData, SymbolData, TEXT, and UncompressedSize.
Referenced by GetReadView(), and GetShaderCodeSize().
GetCompressionFormat()
FName FShaderCode::GetCompressionFormat () const inline
Definition at line 1360 of file ShaderCore.h.
References CompressionFormat.
Referenced by GetFinalizedResource().
GetFinalizedResource()
const FShaderCodeResource & FShaderCode::GetFinalizedResource (EShaderFrequency Frequency, FSHAHash OutputHash) const inline
Definition at line 1414 of file ShaderCore.h.
References check, Fatal, Frequency, GetCompressionFormat(), GetOodleCompressor(), GetOodleLevel(), GetShaderCodeSize(), GetShaderCompressionFormat(), GetShaderCompressionOodleSettings(), OptionalDataSize, ShaderCodeResource, ShaderCodeWithOptionalData, TEXT, FName::ToString(), FSHAHash::ToString(), ToString(), UE_LOG, UncompressedSize, and Verbose.
GetOodleCompressor()
FOodleDataCompression::ECompressor FShaderCode::GetOodleCompressor () const inline
Definition at line 1365 of file ShaderCore.h.
References OodleCompressor.
Referenced by GetFinalizedResource().
GetOodleLevel()
FOodleDataCompression::ECompressionLevel FShaderCode::GetOodleLevel () const inline
Definition at line 1370 of file ShaderCore.h.
References OodleLevel.
Referenced by GetFinalizedResource().
GetReadView()
TConstArrayView< uint8 > FShaderCode::GetReadView () const inline
Definition at line 1348 of file ShaderCore.h.
References FinalizeShaderCode(), and ShaderCodeResource.
GetShaderCodeSize()
int32 FShaderCode::GetShaderCodeSize () const inline
Definition at line 1316 of file ShaderCore.h.
References FinalizeShaderCode(), FShaderCodeReader::GetShaderCodeSize(), ShaderCodeResource, ShaderCodeSize, and UncompressedSize.
Referenced by GetFinalizedResource().
GetSymbolReadView()
TConstArrayView< uint8 > FShaderCode::GetSymbolReadView () const inline
Definition at line 1310 of file ShaderCore.h.
References checkf, OptionalDataSize, SymbolData, and TEXT.
GetSymbolWriteAccess()
TArray< uint8 > & FShaderCode::GetSymbolWriteAccess () inline
Definition at line 1304 of file ShaderCore.h.
References checkf, OptionalDataSize, SymbolData, and TEXT.
GetUncompressedSize()
int32 FShaderCode::GetUncompressedSize () const inline
Definition at line 1375 of file ShaderCore.h.
References UncompressedSize.
GetWriteAccess()
TArray< uint8 > & FShaderCode::GetWriteAccess () inline
Definition at line 1297 of file ShaderCore.h.
References checkf, OptionalDataSize, ShaderCodeWithOptionalData, and TEXT.
IsCompressed()
bool FShaderCode::IsCompressed () const inline
Definition at line 1355 of file ShaderCore.h.
References UncompressedSize.
SetFromResource()
void FShaderCode::SetFromResource (FShaderCodeResource && Resource) inline
Definition at line 1483 of file ShaderCore.h.
References CompressionFormat, GetShaderCompressionFormat(), GetShaderCompressionOodleSettings(), MoveTemp(), OodleCompressor, OodleLevel, OptionalDataSize, ShaderCodeResource, ShaderCodeSize, and UncompressedSize.
UE_DEPRECATED()
FShaderCode::UE_DEPRECATED (5. 5, "Use GetReadView") const & inline
Definition at line 1340 of file ShaderCore.h.
Friends And Related Symbol Documentation
operator<<
RENDERCORE_API FArchive & operator<< (FArchive & Ar, FShaderCode & Output) friend
References FShaderCode(), and Ar.
Field Documentation
CompressionFormat
FName FShaderCode::CompressionFormat mutable private
Compression algo.
Definition at line 1253 of file ShaderCore.h.
Referenced by FShaderCode(), GetCompressionFormat(), and SetFromResource().
OodleCompressor
FOodleDataCompression::ECompressor FShaderCode::OodleCompressor private
Oodle-specific compression algorithm - used if CompressionFormat is set to NAME_Oodle.
Definition at line 1256 of file ShaderCore.h.
Referenced by FShaderCode(), GetOodleCompressor(), and SetFromResource().
OodleLevel
FOodleDataCompression::ECompressionLevel FShaderCode::OodleLevel private
Oodle-specific compression level - used if CompressionFormat is set to NAME_Oodle.
Definition at line 1259 of file ShaderCore.h.
Referenced by FShaderCode(), GetOodleLevel(), and SetFromResource().
OptionalDataSize
int32 FShaderCode::OptionalDataSize mutable private
Definition at line 1241 of file ShaderCore.h.
Referenced by FShaderCode(), AddOptionalData(), FinalizeShaderCode(), GetFinalizedResource(), GetSymbolReadView(), GetSymbolWriteAccess(), GetWriteAccess(), and SetFromResource().
ShaderCodeResource
FShaderCodeResource FShaderCode::ShaderCodeResource mutable private
Definition at line 1247 of file ShaderCore.h.
Referenced by FinalizeShaderCode(), GetFinalizedResource(), GetReadView(), GetShaderCodeSize(), and SetFromResource().
ShaderCodeSize
int32 FShaderCode::ShaderCodeSize mutable private
We cannot get the code size after the compression, so store it here.
Definition at line 1262 of file ShaderCore.h.
Referenced by FShaderCode(), GetShaderCodeSize(), and SetFromResource().
ShaderCodeWithOptionalData
TArray<uint8> FShaderCode::ShaderCodeWithOptionalData mutable private
Definition at line 1243 of file ShaderCore.h.
Referenced by AddOptionalData(), FinalizeShaderCode(), GetFinalizedResource(), and GetWriteAccess().
SymbolData
TArray<uint8> FShaderCode::SymbolData mutable private
Definition at line 1245 of file ShaderCore.h.
Referenced by FinalizeShaderCode(), GetSymbolReadView(), and GetSymbolWriteAccess().
UncompressedSize
int32 FShaderCode::UncompressedSize mutable private
ShaderCode may be compressed in SCWs on demand.
If this value isn't null, the shader code is compressed.
Definition at line 1250 of file ShaderCore.h.
Referenced by FShaderCode(), FinalizeShaderCode(), GetFinalizedResource(), GetShaderCodeSize(), GetUncompressedSize(), IsCompressed(), and SetFromResource().
The documentation for this class was generated from the following file:
Runtime/RenderCore/Public/ShaderCore.h