Unreal Engine 5.6 C++ API: UE::Geometry::TSpatialPhotoSet< PixelType, RealType > Class Template Reference
UE::Geometry::TSpatialPhotoSet< PixelType, RealType > Class Template Reference
TSpatialPhotoSet is a set of TSpatialPhotos.
#include "SpatialPhotoSet.h"
Public Member Functions
void Add (TSpatialPhoto< PixelType > &&Photo)
Add a photo to the photo set via move operation.
PixelType ComputeSample (const FVector3d &Position, const FVector3d &Normal, TFunctionRef< bool(const FVector3d &, const FVector3d &)> VisibilityFunction, const PixelType &DefaultValue) const
Estimate a pixel value at the given 3D Position/Normal using the PhotoSet.
PixelType ComputeSample (const int &PhotoIndex, const FVector2d &PhotoCoords, const PixelType &DefaultValue) const
bool ComputeSampleLocation (const FVector3d &Position, const FVector3d &Normal, TFunctionRef< bool(const FVector3d &, const FVector3d &)> VisibilityFunction, int &PhotoIndex, FVector2d &PhotoCoords) const
PixelType ComputeSampleNearest (const int &PhotoIndex, const FVector2d &PhotoCoords, const PixelType &DefaultValue) const
void Empty ()
const TSpatialPhoto< PixelType > & Get (int32 Index) const
int32 Num () const
Protected Attributes
TArray< TSharedPtr< TSpatialPhoto< PixelType >, ESPMode::ThreadSafe > > Photos
Detailed Description
template<typename PixelType, typename RealType>
class UE::Geometry::TSpatialPhotoSet< PixelType, RealType >
TSpatialPhotoSet is a set of TSpatialPhotos.
The ComputeSample() function can be used to determine the value "seen" by the photo set at a given 3D position/normal, if possible.
Definition at line 79 of file SpatialPhotoSet.h.
Member Function Documentation
Add()
template<typename PixelType, typename RealType> void UE::Geometry::TSpatialPhotoSet< PixelType, RealType >::Add (TSpatialPhoto< PixelType > && Photo) inline
Add a photo to the photo set via move operation.
Definition at line 84 of file SpatialPhotoSet.h.
ComputeSample() [1/2]
template<typename PixelType, typename RealType> PixelType UE::Geometry::TSpatialPhotoSet< PixelType, RealType >::ComputeSample (const FVector3d & Position, const FVector3d & Normal, TFunctionRef< bool(const FVector3d &, const FVector3d &)> VisibilityFunction, const PixelType & DefaultValue) const
Estimate a pixel value at the given 3D Position/Normal using the PhotoSet.
This is effectively a reprojection process, that tries to find the "best" pixel value in the photo set that projects onto the given Position/Normal.
A position may be visible from multiple photos, in this case the dot-product between the view vector and normal is used to decide which photo pixel to use.
VisibilityFunction is used to determine if a 3D point is visible from the given photo point. Generally the caller would implement some kind of raycast to do this.
Returns
the best valid sample if found, or DefaultValue if no suitable sample is available
Definition at line 210 of file SpatialPhotoSet.h.
References ComputeSampleLocation(), UE::Geometry::TSpatialPhoto< PixelType >::Image, UE::Geometry::Normal, Photos, and UE::Geometry::Position.
ComputeSample() [2/2]
template<typename PixelType, typename RealType> PixelType UE::Geometry::TSpatialPhotoSet< PixelType, RealType >::ComputeSample (const int & PhotoIndex, const FVector2d & PhotoCoords, const PixelType & DefaultValue) const
Definition at line 232 of file SpatialPhotoSet.h.
References UE::Geometry::TSpatialPhoto< PixelType >::Image, and Photos.
ComputeSampleLocation()
template<typename PixelType, typename RealType> bool UE::Geometry::TSpatialPhotoSet< PixelType, RealType >::ComputeSampleLocation (const FVector3d & Position, const FVector3d & Normal, TFunctionRef< bool(const FVector3d &, const FVector3d &)> VisibilityFunction, int & PhotoIndex, FVector2d & PhotoCoords) const
Definition at line 147 of file SpatialPhotoSet.h.
References TMathUtil< double >::Abs(), check, TMathUtilConstants< double >::DegToRad, UE::Geometry::TSpatialPhoto< PixelType >::Dimensions, UE::Geometry::Dot(), UE::Math::TVector< T >::Dot(), UE::Geometry::TSpatialPhoto< PixelType >::Frame, UE::Geometry::FImageDimensions::GetHeight(), UE::Geometry::FImageDimensions::GetWidth(), UE::Geometry::TSpatialPhoto< PixelType >::HorzFOVDegrees, IndexConstants::InvalidID, UE::Geometry::FImageDimensions::IsSquare(), UE::Geometry::TSpatialPhoto< PixelType >::NearPlaneDist, UE::Geometry::Normal, Normalized, Num, UE::Geometry::TFrame3< RealType >::Origin, Photos, UE::Geometry::Position, UE::Geometry::TFrame3< RealType >::RayPlaneIntersection(), TMathUtil< double >::Tan(), UE::Geometry::TFrame3< RealType >::X(), UE::Math::TVector2< T >::X, UE::Geometry::TFrame3< RealType >::Y(), UE::Math::TVector2< T >::Y, and UE::Geometry::TFrame3< RealType >::Z().
Referenced by ComputeSample().
ComputeSampleNearest()
template<typename PixelType, typename RealType> PixelType UE::Geometry::TSpatialPhotoSet< PixelType, RealType >::ComputeSampleNearest (const int & PhotoIndex, const FVector2d & PhotoCoords, const PixelType & DefaultValue) const
Definition at line 244 of file SpatialPhotoSet.h.
References UE::Geometry::TSpatialPhoto< PixelType >::Image, Photos, UE::Math::TVector2< T >::X, and UE::Math::TVector2< T >::Y.
Empty()
template<typename PixelType, typename RealType> void UE::Geometry::TSpatialPhotoSet< PixelType, RealType >::Empty () inline
Returns
removes all photos from the photo set
Definition at line 94 of file SpatialPhotoSet.h.
Get()
template<typename PixelType, typename RealType> const TSpatialPhoto< PixelType > & UE::Geometry::TSpatialPhotoSet< PixelType, RealType >::Get (int32 Index) const inline
Returns
the photo at the given index
Definition at line 97 of file SpatialPhotoSet.h.
Num()
template<typename PixelType, typename RealType> int32 UE::Geometry::TSpatialPhotoSet< PixelType, RealType >::Num () const inline
Returns
the number of photos in the photo set
Definition at line 91 of file SpatialPhotoSet.h.
Field Documentation
Photos
template<typename PixelType, typename RealType> TArray<TSharedPtr<TSpatialPhoto<PixelType>, ESPMode::ThreadSafe> > UE::Geometry::TSpatialPhotoSet< PixelType, RealType >::Photos protected
Definition at line 140 of file SpatialPhotoSet.h.
Referenced by ComputeSample(), ComputeSample(), ComputeSampleLocation(), and ComputeSampleNearest().
The documentation for this class was generated from the following file:
Runtime/GeometryCore/Public/Image/SpatialPhotoSet.h