Unreal Engine 5.6 C++ API: IDisplayClusterConfiguratorTreeItem Class Reference
IDisplayClusterConfiguratorTreeItem Class Reference abstract
#include "IDisplayClusterConfiguratorTreeItem.h"
Public Member Functions
virtual ~IDisplayClusterConfiguratorTreeItem ()=default
virtual EDisplayClusterConfiguratorTreeFilterResult ApplyFilter (const TSharedPtr< FTextFilterExpressionEvaluator > &TextFilter)=0
Applies the specified text filter to the tree item and returns the results.
virtual bool CanDeleteItem () const =0
virtual bool CanDuplicateItem () const =0
virtual bool CanHideItem () const =0
virtual bool CanRenameItem () const =0
virtual void DeleteItem () const =0
Deletes the tree row item and its backing object.
virtual TSharedRef< SWidget > GenerateInlineEditWidget (const TAttribute< FText > &FilterText, FIsSelected InIsSelected)=0
Builds the slate widget for any inline data editing.
virtual TSharedRef< SWidget > GenerateWidgetForColumn (const FName &ColumnName, TSharedPtr< ITableRow > TableRow, const TAttribute< FText > &FilterText, FIsSelected InIsSelected)=0
Builds a widget for the specified column.
virtual FName GetAttachName () const =0
Return the name used to attach to this item.
virtual TArray< TSharedPtr< IDisplayClusterConfiguratorTreeItem > > & GetChildren ()=0
The array of children for this item.
virtual const TArray< TSharedPtr< IDisplayClusterConfiguratorTreeItem > > & GetChildrenConst () const =0
The const array of children for this item.
virtual void GetChildrenObjectsRecursive (TArray< UObject * > &OutObjects) const =0
Get all Children object.
virtual TSharedRef< IDisplayClusterConfiguratorViewTree > GetConfiguratorTree () const =0
The owning view tree.
virtual TArray< TSharedPtr< IDisplayClusterConfiguratorTreeItem > > & GetFilteredChildren ()=0
The filtered array of children for this item.
virtual EDisplayClusterConfiguratorTreeFilterResult GetFilterResult () const =0
Get the current filter result.
virtual FString GetIconStyle () const =0
Get the style for image icon.
virtual TSharedPtr< IDisplayClusterConfiguratorTreeItem > GetParent () const =0
Get this item's parent.
virtual void GetParentObjectsRecursive (TArray< UObject * > &OutObjects) const =0
Get the objects of all parents of this item.
virtual FName GetRowItemName () const =0
Get the name of the item that this row represents.
virtual FName GetTypeName () const
virtual FReply HandleAcceptDrop (const FDragDropEvent &DragDropEvent, TSharedPtr< IDisplayClusterConfiguratorTreeItem > TargetItem)=0
Handle Accep drag and drop drop event.
virtual TOptional< EItemDropZone > HandleCanAcceptDrop (const FDragDropEvent &DragDropEvent, EItemDropZone DropZone, TSharedPtr< IDisplayClusterConfiguratorTreeItem > TargetItem)=0
Handles the CanAcceptDrop callback for the tree item.
virtual FReply HandleDragDetected (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)=0
Handle a drag and drop detected event.
virtual void HandleDragEnter (const FDragDropEvent &DragDropEvent)=0
Handle a drag and drop enter event.
virtual void HandleDragLeave (const FDragDropEvent &DragDropEvent)=0
Handle a drag and drop leave event.
virtual FReply HandleDrop (FDragDropEvent const &DragDropEvent)=0
Handle a drag and drop drop event.
virtual bool HasInlineEditor () const =0
virtual void Initialize ()=0
Initializes the tree item.
virtual bool IsChildOfRecursive (const TSharedRef< IDisplayClusterConfiguratorTreeItem > &InParentTreeItem) const =0
Return true if this item is a child of the given parent tree item.
virtual bool IsHovered () const =0
Return true if tree item is hovered.
virtual bool IsInitiallyExpanded () const =0
Get whether this item begins expanded or not.
virtual bool IsInlineEditorExpanded () const =0
Get the expansion state of the inline editor.
virtual bool IsOfTypeByName (const FName &Type) const
virtual bool IsRoot () const =0
Return true if that is root tree item.
virtual TSharedRef< ITableRow > MakeTreeRowWidget (const TSharedRef< STableViewBase > &InOwnerTable, const TAttribute< FText > &InFilterText)=0
Builds the table row widget to display this info.
virtual void OnItemDoubleClicked ()=0
Handler for when the user double clicks on this item in the tree.
virtual void OnMouseEnter ()=0
Handler for when the user enter the mouse on this item in the tree.
virtual void OnMouseLeave ()=0
Handler for when the user leave the mouse on this item in the tree.
virtual void RequestRename ()=0
Requests a rename on the the tree row item.
virtual void SetFilterResult (EDisplayClusterConfiguratorTreeFilterResult InResult)=0
Set the current filter result.
virtual void SetItemHidden (bool bIsHidden)=0
Sets the item's visibility.
virtual void SetParent (TSharedPtr< IDisplayClusterConfiguratorTreeItem > InParent)=0
Set this item's parent.
virtual void ToggleInlineEditorExpansion ()=0
Toggle the expansion state of the inline editor.
Public Member Functions inherited from IDisplayClusterConfiguratorItem
virtual ~IDisplayClusterConfiguratorItem ()=default
virtual UObject * GetObject () const =0
Get the object represented by this item, if any.
virtual bool IsSelected ()=0
virtual void OnSelection ()=0
Public Member Functions inherited from TSharedFromThis< IDisplayClusterConfiguratorItem >
TSharedRef< IDisplayClusterConfiguratorItem, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< IDisplayClusterConfiguratorItem, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Static Public Member Functions
static const FName & GetTypeId ()
Additional Inherited Members
Protected Member Functions inherited from TSharedFromThis< IDisplayClusterConfiguratorItem >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions inherited from TSharedFromThis< IDisplayClusterConfiguratorItem >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
Definition at line 44 of file IDisplayClusterConfiguratorTreeItem.h.
Constructor & Destructor Documentation
~IDisplayClusterConfiguratorTreeItem()
virtual IDisplayClusterConfiguratorTreeItem::~IDisplayClusterConfiguratorTreeItem () virtual default
Member Function Documentation
ApplyFilter()
virtual EDisplayClusterConfiguratorTreeFilterResult IDisplayClusterConfiguratorTreeItem::ApplyFilter (const TSharedPtr< FTextFilterExpressionEvaluator > & TextFilter) pure virtual
Applies the specified text filter to the tree item and returns the results.
Parameters
TextFilter - The filter to apply
Returns
The results of applying the filter to this tree item
References ApplyFilter().
Referenced by ApplyFilter().
CanDeleteItem()
virtual bool IDisplayClusterConfiguratorTreeItem::CanDeleteItem () const pure virtual
Returns
true if this item can be deleted
References CanDeleteItem().
Referenced by CanDeleteItem().
CanDuplicateItem()
virtual bool IDisplayClusterConfiguratorTreeItem::CanDuplicateItem () const pure virtual
Returns
true if this item can be duplicated
References CanDuplicateItem().
Referenced by CanDuplicateItem().
CanHideItem()
virtual bool IDisplayClusterConfiguratorTreeItem::CanHideItem () const pure virtual
Returns
true if this item can be hidden
References CanHideItem().
Referenced by CanHideItem().
CanRenameItem()
virtual bool IDisplayClusterConfiguratorTreeItem::CanRenameItem () const pure virtual
Returns
true if this item can be renamed
References CanRenameItem().
Referenced by CanRenameItem().
DeleteItem()
virtual void IDisplayClusterConfiguratorTreeItem::DeleteItem () const pure virtual
Deletes the tree row item and its backing object.
References DeleteItem().
Referenced by DeleteItem().
GenerateInlineEditWidget()
virtual TSharedRef< SWidget > IDisplayClusterConfiguratorTreeItem::GenerateInlineEditWidget (const TAttribute< FText > & FilterText, FIsSelected InIsSelected) pure virtual
Builds the slate widget for any inline data editing.
References FIsSelected, and GenerateInlineEditWidget().
Referenced by GenerateInlineEditWidget().
GenerateWidgetForColumn()
virtual TSharedRef< SWidget > IDisplayClusterConfiguratorTreeItem::GenerateWidgetForColumn (const FName & ColumnName, TSharedPtr< ITableRow > TableRow, const TAttribute< FText > & FilterText, FIsSelected InIsSelected) pure virtual
Builds a widget for the specified column.
Parameters
ColumnName - The name of the column to build the widget for.
TableRow - The table row the widget is being generated for.
FilterText - The current filter being applied to the tree view.
InIsSelected - The FIsSelected delegate for the current table row.
References FIsSelected, and GenerateWidgetForColumn().
Referenced by GenerateWidgetForColumn().
GetAttachName()
virtual FName IDisplayClusterConfiguratorTreeItem::GetAttachName () const pure virtual
Return the name used to attach to this item.
References GetAttachName().
Referenced by GetAttachName().
GetChildren()
virtual TArray< TSharedPtr< IDisplayClusterConfiguratorTreeItem > > & IDisplayClusterConfiguratorTreeItem::GetChildren () pure virtual
The array of children for this item.
References GetChildren().
Referenced by GetChildren().
GetChildrenConst()
virtual const TArray< TSharedPtr< IDisplayClusterConfiguratorTreeItem > > & IDisplayClusterConfiguratorTreeItem::GetChildrenConst () const pure virtual
The const array of children for this item.
References GetChildrenConst().
Referenced by GetChildrenConst().
GetChildrenObjectsRecursive()
virtual void IDisplayClusterConfiguratorTreeItem::GetChildrenObjectsRecursive (TArray< UObject * > & OutObjects) const pure virtual
Get all Children object.
References GetChildrenObjectsRecursive().
Referenced by GetChildrenObjectsRecursive().
GetConfiguratorTree()
virtual TSharedRef< IDisplayClusterConfiguratorViewTree > IDisplayClusterConfiguratorTreeItem::GetConfiguratorTree () const pure virtual
The owning view tree.
References GetConfiguratorTree().
Referenced by GetConfiguratorTree().
GetFilteredChildren()
virtual TArray< TSharedPtr< IDisplayClusterConfiguratorTreeItem > > & IDisplayClusterConfiguratorTreeItem::GetFilteredChildren () pure virtual
The filtered array of children for this item.
References GetFilteredChildren().
Referenced by GetFilteredChildren().
GetFilterResult()
virtual EDisplayClusterConfiguratorTreeFilterResult IDisplayClusterConfiguratorTreeItem::GetFilterResult () const pure virtual
Get the current filter result.
References GetFilterResult().
Referenced by GetFilterResult().
GetIconStyle()
virtual FString IDisplayClusterConfiguratorTreeItem::GetIconStyle () const pure virtual
Get the style for image icon.
References GetIconStyle().
Referenced by GetIconStyle().
GetParent()
virtual TSharedPtr< IDisplayClusterConfiguratorTreeItem > IDisplayClusterConfiguratorTreeItem::GetParent () const pure virtual
Get this item's parent.
References GetParent().
Referenced by GetParent().
GetParentObjectsRecursive()
virtual void IDisplayClusterConfiguratorTreeItem::GetParentObjectsRecursive (TArray< UObject * > & OutObjects) const pure virtual
Get the objects of all parents of this item.
References GetParentObjectsRecursive().
Referenced by GetParentObjectsRecursive().
GetRowItemName()
virtual FName IDisplayClusterConfiguratorTreeItem::GetRowItemName () const pure virtual
Get the name of the item that this row represents.
References GetRowItemName().
Referenced by GetRowItemName().
GetTypeId()
const FName & IDisplayClusterConfiguratorTreeItem::GetTypeId () inline static
Definition at line 51 of file IDisplayClusterConfiguratorTreeItem.h.
GetTypeName()
virtual FName IDisplayClusterConfiguratorTreeItem::GetTypeName () const inline virtual
Definition at line 51 of file IDisplayClusterConfiguratorTreeItem.h.
HandleAcceptDrop()
virtual FReply IDisplayClusterConfiguratorTreeItem::HandleAcceptDrop (const FDragDropEvent & DragDropEvent, TSharedPtr< IDisplayClusterConfiguratorTreeItem > TargetItem) pure virtual
Handle Accep drag and drop drop event.
References HandleAcceptDrop().
Referenced by HandleAcceptDrop().
HandleCanAcceptDrop()
virtual TOptional< EItemDropZone > IDisplayClusterConfiguratorTreeItem::HandleCanAcceptDrop (const FDragDropEvent & DragDropEvent, EItemDropZone DropZone, TSharedPtr< IDisplayClusterConfiguratorTreeItem > TargetItem) pure virtual
Handles the CanAcceptDrop callback for the tree item.
References HandleCanAcceptDrop().
Referenced by HandleCanAcceptDrop().
HandleDragDetected()
virtual FReply IDisplayClusterConfiguratorTreeItem::HandleDragDetected (const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) pure virtual
Handle a drag and drop detected event.
References HandleDragDetected(), and MouseEvent.
Referenced by HandleDragDetected().
HandleDragEnter()
virtual void IDisplayClusterConfiguratorTreeItem::HandleDragEnter (const FDragDropEvent & DragDropEvent) pure virtual
Handle a drag and drop enter event.
References HandleDragEnter().
Referenced by HandleDragEnter().
HandleDragLeave()
virtual void IDisplayClusterConfiguratorTreeItem::HandleDragLeave (const FDragDropEvent & DragDropEvent) pure virtual
Handle a drag and drop leave event.
References HandleDragLeave().
Referenced by HandleDragLeave().
HandleDrop()
virtual FReply IDisplayClusterConfiguratorTreeItem::HandleDrop (FDragDropEvent const & DragDropEvent) pure virtual
Handle a drag and drop drop event.
References HandleDrop().
Referenced by HandleDrop().
HasInlineEditor()
virtual bool IDisplayClusterConfiguratorTreeItem::HasInlineEditor () const pure virtual
Returns
true if the item has an in-line editor widget
References HasInlineEditor().
Referenced by HasInlineEditor().
Initialize()
virtual void IDisplayClusterConfiguratorTreeItem::Initialize () pure virtual
Initializes the tree item.
References Initialize().
Referenced by Initialize().
IsChildOfRecursive()
virtual bool IDisplayClusterConfiguratorTreeItem::IsChildOfRecursive (const TSharedRef< IDisplayClusterConfiguratorTreeItem > & InParentTreeItem) const pure virtual
Return true if this item is a child of the given parent tree item.
References IsChildOfRecursive().
Referenced by IsChildOfRecursive().
IsHovered()
virtual bool IDisplayClusterConfiguratorTreeItem::IsHovered () const pure virtual
Return true if tree item is hovered.
References IsHovered().
Referenced by IsHovered().
IsInitiallyExpanded()
virtual bool IDisplayClusterConfiguratorTreeItem::IsInitiallyExpanded () const pure virtual
Get whether this item begins expanded or not.
References IsInitiallyExpanded().
Referenced by IsInitiallyExpanded().
IsInlineEditorExpanded()
virtual bool IDisplayClusterConfiguratorTreeItem::IsInlineEditorExpanded () const pure virtual
Get the expansion state of the inline editor.
References IsInlineEditorExpanded().
Referenced by IsInlineEditorExpanded().
IsOfTypeByName()
virtual bool IDisplayClusterConfiguratorTreeItem::IsOfTypeByName (const FName & Type) const inline virtual
Definition at line 51 of file IDisplayClusterConfiguratorTreeItem.h.
IsRoot()
virtual bool IDisplayClusterConfiguratorTreeItem::IsRoot () const pure virtual
Return true if that is root tree item.
References IsRoot().
Referenced by IsRoot().
MakeTreeRowWidget()
virtual TSharedRef< ITableRow > IDisplayClusterConfiguratorTreeItem::MakeTreeRowWidget (const TSharedRef< STableViewBase > & InOwnerTable, const TAttribute< FText > & InFilterText) pure virtual
Builds the table row widget to display this info.
References MakeTreeRowWidget().
Referenced by MakeTreeRowWidget().
OnItemDoubleClicked()
virtual void IDisplayClusterConfiguratorTreeItem::OnItemDoubleClicked () pure virtual
Handler for when the user double clicks on this item in the tree.
References OnItemDoubleClicked().
Referenced by OnItemDoubleClicked().
OnMouseEnter()
virtual void IDisplayClusterConfiguratorTreeItem::OnMouseEnter () pure virtual
Handler for when the user enter the mouse on this item in the tree.
References OnMouseEnter().
Referenced by OnMouseEnter().
OnMouseLeave()
virtual void IDisplayClusterConfiguratorTreeItem::OnMouseLeave () pure virtual
Handler for when the user leave the mouse on this item in the tree.
References OnMouseLeave().
Referenced by OnMouseLeave().
RequestRename()
virtual void IDisplayClusterConfiguratorTreeItem::RequestRename () pure virtual
Requests a rename on the the tree row item.
References RequestRename().
Referenced by RequestRename().
SetFilterResult()
virtual void IDisplayClusterConfiguratorTreeItem::SetFilterResult (EDisplayClusterConfiguratorTreeFilterResult InResult) pure virtual
Set the current filter result.
References SetFilterResult().
Referenced by SetFilterResult().
SetItemHidden()
virtual void IDisplayClusterConfiguratorTreeItem::SetItemHidden (bool bIsHidden) pure virtual
Sets the item's visibility.
References SetItemHidden().
Referenced by SetItemHidden().
SetParent()
virtual void IDisplayClusterConfiguratorTreeItem::SetParent (TSharedPtr< IDisplayClusterConfiguratorTreeItem > InParent) pure virtual
Set this item's parent.
References SetParent().
Referenced by SetParent().
ToggleInlineEditorExpansion()
virtual void IDisplayClusterConfiguratorTreeItem::ToggleInlineEditorExpansion () pure virtual
Toggle the expansion state of the inline editor.
References ToggleInlineEditorExpansion().
Referenced by ToggleInlineEditorExpansion().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/nDisplay/Source/DisplayClusterConfigurator/Public/Views/TreeViews/IDisplayClusterConfiguratorTreeItem.h