Unreal Engine 5.6 C++ API: UE::Anim::DataModel::FHasherBase< SubClassType > Class Template Reference
UE::Anim::DataModel::FHasherBase< SubClassType > Class Template Reference
Base class of Hasher classes used by IAnimationDataModel classes to share code between GenerateGuid and GenerateDebugStateString.
#include "AnimDataModelHasher.h"
Public Member Functions
void BeginObject (const TCHAR *Name=nullptr)
void EndObject ()
void UpdateAnimatedBoneAttributes (TConstArrayView< FAnimatedBoneAttribute > AnimatedBoneAttributes, const TCHAR *Name)
template<typename T>
void UpdateArray (const TArray< T > &Array, const TCHAR *Name)
template<typename T>
void UpdateArray (TConstArrayView< T > Array, const TCHAR *Name)
void UpdateBytes (const uint8 *Data, int32 Size, const TCHAR *Name)
template<typename T>
void UpdateData (const T &Data, const TCHAR *Name)
void UpdateLegacyString (const FString &Data, const TCHAR *Name)
Previously, some code was serializing strings as GetCharArray, which includes the null terminator, and we did not want to change behavior because it would change the key.
void UpdateRichCurve (const FRichCurve &Curve, const TCHAR *Name)
void UpdateString (const FString &Data, const TCHAR *Name)
void UpdateTransformCurves (TConstArrayView< FTransformCurve > TransformCurves, const TCHAR *Name)
void UpdateVectorCurve (const FVectorCurve &VectorCurve, const TCHAR *Name)
Private Member Functions
SubClassType * TypedThis ()
Detailed Description
template<typename SubClassType>
class UE::Anim::DataModel::FHasherBase< SubClassType >
Base class of Hasher classes used by IAnimationDataModel classes to share code between GenerateGuid and GenerateDebugStateString.
This class uses no virtuals for performance; the function that takes a Hasher should be templated on the type of the Hasher.
This base class shows the required interface and some convenience functions. It uses the Curiously Recurring Template Pattern to call the Subclass's version of internal function calls.
Definition at line 31 of file AnimDataModelHasher.h.
Member Function Documentation
BeginObject()
template<typename SubClassType> void UE::Anim::DataModel::FHasherBase< SubClassType >::BeginObject (const TCHAR * Name = nullptr) inline
Definition at line 40 of file AnimDataModelHasher.h.
References checkf, Name, and TEXT.
EndObject()
template<typename SubClassType> void UE::Anim::DataModel::FHasherBase< SubClassType >::EndObject () inline
Definition at line 44 of file AnimDataModelHasher.h.
References checkf, and TEXT.
TypedThis()
template<typename SubClassType> SubClassType * UE::Anim::DataModel::FHasherBase< SubClassType >::TypedThis () inline private
Definition at line 160 of file AnimDataModelHasher.h.
Referenced by UpdateAnimatedBoneAttributes(), UpdateArray(), UpdateArray(), UpdateData(), UpdateLegacyString(), UpdateRichCurve(), UpdateString(), UpdateTransformCurves(), and UpdateVectorCurve().
UpdateAnimatedBoneAttributes()
template<typename SubClassType> void UE::Anim::DataModel::FHasherBase< SubClassType >::UpdateAnimatedBoneAttributes (TConstArrayView< FAnimatedBoneAttribute > AnimatedBoneAttributes, const TCHAR * Name) inline
Definition at line 104 of file AnimDataModelHasher.h.
References Attribute, UScriptStruct::GetCppStructOps(), UObjectBase::GetFName(), UStruct::GetPropertiesSize(), UScriptStruct::GetStructTypeHash(), UScriptStruct::ICppStructOps::HasGetTypeHash(), Key, Name, TEXT, FName::ToString(), and TypedThis().
UpdateArray() [1/2]
template<typename SubClassType> template<typename T> void UE::Anim::DataModel::FHasherBase< SubClassType >::UpdateArray (const TArray< T > & Array, const TCHAR * Name) inline
Definition at line 57 of file AnimDataModelHasher.h.
References Array, Name, and TypedThis().
UpdateArray() [2/2]
template<typename SubClassType> template<typename T> void UE::Anim::DataModel::FHasherBase< SubClassType >::UpdateArray (TConstArrayView< T > Array, const TCHAR * Name) inline
Definition at line 62 of file AnimDataModelHasher.h.
References Array, Name, and TypedThis().
UpdateBytes()
template<typename SubClassType> void UE::Anim::DataModel::FHasherBase< SubClassType >::UpdateBytes (const uint8 * Data, int32 Size, const TCHAR * Name) inline
Definition at line 36 of file AnimDataModelHasher.h.
References checkf, Name, TEXT, and TSequenceHistory< HistorySize >::Size.
UpdateData()
template<typename SubClassType> template<typename T> void UE::Anim::DataModel::FHasherBase< SubClassType >::UpdateData (const T & Data, const TCHAR * Name) inline
Definition at line 52 of file AnimDataModelHasher.h.
References Name, and TypedThis().
UpdateLegacyString()
template<typename SubClassType> void UE::Anim::DataModel::FHasherBase< SubClassType >::UpdateLegacyString (const FString & Data, const TCHAR * Name) inline
Previously, some code was serializing strings as GetCharArray, which includes the null terminator, and we did not want to change behavior because it would change the key.
Those sites call UpdateLegacyString instead, and the subclasses that want to preserve the key override it.
Definition at line 75 of file AnimDataModelHasher.h.
References Name, and TypedThis().
UpdateRichCurve()
template<typename SubClassType> void UE::Anim::DataModel::FHasherBase< SubClassType >::UpdateRichCurve (const FRichCurve & Curve, const TCHAR * Name) inline
Definition at line 80 of file AnimDataModelHasher.h.
References Name, TEXT, and TypedThis().
UpdateString()
template<typename SubClassType> void UE::Anim::DataModel::FHasherBase< SubClassType >::UpdateString (const FString & Data, const TCHAR * Name) inline
Definition at line 66 of file AnimDataModelHasher.h.
References Name, and TypedThis().
UpdateTransformCurves()
template<typename SubClassType> void UE::Anim::DataModel::FHasherBase< SubClassType >::UpdateTransformCurves (TConstArrayView< FTransformCurve > TransformCurves, const TCHAR * Name) inline
Definition at line 142 of file AnimDataModelHasher.h.
References Name, TEXT, and TypedThis().
UpdateVectorCurve()
template<typename SubClassType> void UE::Anim::DataModel::FHasherBase< SubClassType >::UpdateVectorCurve (const FVectorCurve & VectorCurve, const TCHAR * Name) inline
Definition at line 92 of file AnimDataModelHasher.h.
References Name, TEXT, and TypedThis().
The documentation for this class was generated from the following file:
Runtime/Engine/Public/Animation/AnimDataModelHasher.h