Unreal Engine 5.6 C++ API: FSceneView Class Reference
FSceneView Class Reference
A projection from scene space into a 2D screen region.
#include "SceneView.h"
Data Structures
struct FWaterInfoTextureRenderingParams
Public Member Functions
PRAGMA_DISABLE_DEPRECATION_WARNINGS FSceneView (const FSceneView &Other)=default
These are only needed because of deprecated members being accessed in them.
FSceneView (const FSceneViewInitOptions &InitOptions)
Initialization constructor.
FSceneView (FSceneView &&Other)=default
virtual PRAGMA_ENABLE_DEPRECATION_WARNINGS ~FSceneView ()
Default destructor.
FORCEINLINE bool AllowGPUParticleUpdate () const
void ConfigureBufferVisualizationSettings ()
Configure post process settings for the buffer visualization system.
void ConfigureVisualizeCalibrationSettings ()
Configure post process settings for calibration material.
FVector4 CursorToScreen (float X, float Y, float Z) const
Transforms a cursor location in render target pixel coordinates into the view's screen-space, taking into account the viewport rectangle.
FVector Deproject (const FPlane &ScreenPoint) const
Transforms a point from the view's screen-space into world coordinates multiplies X, Y, Z by W before transforming.
void DeprojectFVector2D (const FVector2D &ScreenPos, FVector &out_WorldOrigin, FVector &out_WorldDirection) const
Transforms 2D screen coordinates into a 3D world-space origin and direction.
void EndFinalPostprocessSettings (const FSceneViewInitOptions &ViewInitOptions)
applied global restrictions from show flags
const FConvexVolume & GetCullingFrustum () const
uint32 GetDistanceFieldTemporalSampleIndex () const
returns the distance field temporal sample index or 0 if there is no view state
const FConvexVolume * GetDynamicMeshElementsShadowCullFrustum () const
FRDGPooledBuffer * GetEyeAdaptationBuffer () const
Returns the eye adaptation buffer or null if it doesn't exist.
ERHIFeatureLevel::Type GetFeatureLevel () const
Get the feature level for this view (cached from the scene so this is not different per view)
const FSceneView * GetInstancedSceneView () const
Get the first secondary view associated with the primary view.
const TUniformBufferRef< FInstancedViewUniformShaderParameters > & GetInstancedViewUniformBuffer () const
Returns uniform buffer that is used to access (first) instanced view's properties.
float GetLastEyeAdaptationExposure () const
Returns the eye adaptation exposure or 0.0f if it doesn't exist.
uint32 GetOcclusionFrameCounter () const
returns a the occlusion frame counter or MAX_uint32 if there is no view state
ERenderTargetLoadAction GetOverwriteLoadAction () const
Returns the load action to use when overwriting all pixels of a target that you intend to read from.
const FVector & GetPreShadowTranslation () const
const FSceneView * GetPrimarySceneView () const
Get the primary view associated with the secondary view.
TArray< const FSceneView * > GetSecondaryViews () const
Get all secondary views associated with the primary view.
EShaderPlatform GetShaderPlatform () const
Get the feature level for this view.
const FViewMatrices & GetShadowViewMatrices () const
const FSceneView * GetSnapshotOriginView () const
int32 GetStereoPassInstanceFactor () const
Instance factor for a stereo pass (normally 2 for ISR views, but see IStereoRendering::GetDesiredNumberOfViews()).
FVector GetTemporalLODOrigin (int32 Index, bool bUseLaggedLODTransition=true) const
Returns the location used as the origin for LOD computations.
float GetTemporalLODTransition () const
Returns the blend factor between the last two LOD samples.
FVector GetViewDirection () const
uint32 GetViewKey () const
returns a unique key for the view state if one exists, otherwise returns zero
FVector GetViewRight () const
FVector GetViewUp () const
bool HasEyeAdaptationViewState () const
bool HasValidEyeAdaptationBuffer () const
Tells if the eye adaptation buffer exists without attempting to allocate it.
bool IsInstancedSceneView () const
Checks whether this is the instanced view of a stereo pair.
bool IsInstancedStereoPass () const
True if the view should render as an instanced stereo pass.
bool IsPerspectiveProjection () const
bool IsPrimarySceneView () const
Checks whether this is the primary view of a stereo pair (important in instanced stereo rendering).
bool IsRayTracingAllowedForView () const
bool IsUnderwater () const
void OverridePostProcessSettings (const FPostProcessSettings &Src, float Weight)
custom layers can be combined with the existing settings
FVector4 PixelToScreen (float X, float Y, float Z) const
Transforms a point from pixel coordinates relative to the view's X,Y (left, top) into the view's screen-space.
FVector4 PixelToWorld (float X, float Y, float Z) const
Transforms a point from pixel coordinates relative to the view's X,Y (left, top) into the view's world-space.
FPlane Project (const FVector &WorldPoint) const
Transforms a point from the view's world-space into the view's screen-space.
bool ScreenToPixel (const FVector4 &ScreenPoint, FVector2D &OutPixelLocation) const
Transforms a point from the view's screen-space into pixel coordinates relative to the view's X,Y.
FVector ScreenToWorld (const FVector4 &ScreenPoint) const
Transforms a point from the view's screen-space to world-space.
void SetDynamicMeshElementsShadowCullFrustum (const FConvexVolume *InDynamicMeshElementsShadowCullFrustum)
void SetPreShadowTranslation (const FVector &InPreShadowTranslation)
void SetupAntiAliasingMethod ()
void SetupCommonViewUniformBufferParameters (FViewUniformShaderParameters &ViewUniformShaderParameters, const FIntPoint &InBufferSize, int32 NumMSAASamples, const FIntRect &InEffectiveViewRect, const FViewMatrices &InViewMatrices, const FViewMatrices &InPrevViewMatrices) const
Populates the uniform buffer prameters common to all scene view use cases View parameters should be set up in this method if they are required for the view to render properly.
void SetupViewRectUniformBufferParameters (FViewUniformShaderParameters &ViewUniformShaderParameters, const FIntPoint &InBufferSize, const FIntRect &InEffectiveViewRect, const FViewMatrices &InViewMatrices, const FViewMatrices &InPrevViewMatrice) const
Sets up the view rect parameters in the view's uniform shader parameters.
void StartFinalPostprocessSettings (FVector InViewLocation)
Setup defaults and depending on view position (postprocess volumes)
UE_DEPRECATED (5.2, "Use GetEyeAdaptationBuffer() instead.") 1 IPooledRenderTarget *GetEyeAdaptationTexture() const
UE_DEPRECATED (5.2, "Use HasValidEyeAdaptationBuffer() instead.") 1 bool HasValidEyeAdaptationTexture() const
UE_DEPRECATED (5.6, "Use GetCullingFrustum() instead.") uint8 CullingFrustum
UE_DEPRECATED (5.6, "Use GetShadowViewMatrices instead") uint8 ShadowViewMatrices
void UpdatePlanarReflectionViewMatrix (const FSceneView &SourceView, const FMirrorMatrix &MirrorMatrix)
If we late update a view, we need to also late update any planar reflection views derived from it.
void UpdateProjectionMatrix (const FMatrix &NewProjectionMatrix)
void UpdateViewMatrix ()
Allow things like HMD displays to update the view matrix at the last minute, to minimize perceived latency.
bool WorldToPixel (const FVector &WorldPoint, FVector2D &OutPixelLocation) const
Transforms a point from the view's world-space into pixel coordinates relative to the view's X,Y (left, top).
FVector4 WorldToScreen (const FVector &WorldPoint) const
Transforms a point from world-space to the view's screen-space.
Public Member Functions inherited from FSceneViewFixLayout
virtual ~FSceneViewFixLayout ()=default
Static Public Member Functions
static void DeprojectScreenToWorld (const FVector2D &ScreenPos, const FIntRect &ViewRect, const FMatrix &InvViewMatrix, const FMatrix &InvProjMatrix, FVector &out_WorldOrigin, FVector &out_WorldDirection)
Transforms 2D screen coordinates into a 3D world-space origin and direction.
static void DeprojectScreenToWorld (const FVector2D &ScreenPos, const FIntRect &ViewRect, const FMatrix &InvViewProjMatrix, FVector &out_WorldOrigin, FVector &out_WorldDirection)
Overload to take a single combined view projection matrix.
static FVector4f GetScreenPositionScaleBias (const FIntPoint &BufferSize, const FIntRect &ViewRect)
static bool ProjectWorldToScreen (const FVector &WorldPosition, const FIntRect &ViewRect, const FMatrix &ViewProjectionMatrix, FVector2D &out_ScreenPos, bool bShouldCalcOutsideViewPosition=false)
Transforms 3D world-space origin into 2D screen coordinates.
Data Fields
TStaticArray< FLinearColor, 6 > AdditionalSelectionOutlineColors
Additional selection colors for the editor (used by post processing)
FVector2f AmbientOcclusionOverrideParameter
EAntiAliasingMethod AntiAliasingMethod
UE::StereoRenderUtils::FStereoShaderAspects Aspects
Stereo aspects of the shader pipeline based on this view's shader platform.
FTextureRHIRef AtmosphereInscatterTexture
FTextureRHIRef AtmosphereIrradianceTexture
FTextureRHIRef AtmosphereTransmittanceTexture
Parameters for atmospheric fog.
FLinearColor BackgroundColor
bool bAllowCrossGPUTransfer
Allow cross GPU transfer for this view.
bool bAllowRayTracing = true
Set to false to disable ray tracing on this view.
bool bAllowTemporalJitter
bool bAllowTranslucentPrimitivesInHitProxy
True if we should draw translucent objects when rendering hit proxies.
FVector BaseHmdLocation
FQuat BaseHmdOrientation
bool bCameraCut
Whether we did a camera cut for this view this frame.
TOptional< bool > bCameraMotionBlur
Whether to enable motion blur caused by camera movements.
bool bDisableDistanceBasedFadeTransitions
Whether we should disable distance-based fade transitions for this frame (usually after a large camera movement.)
bool bEnableDynamicCocOffset = false
Enables a CoC offset whose offset value changes with pixel's scene depth.
bool bExcludeFromSceneTextureExtents = false
Whether this view should be excluded from extent history tracking.
bool bEyeAdaptationAllViewPixels
Whether to generate histogram eye adaptation from all view pixels, useful with a shared EyeAdaptationViewState.
bool bForceCameraVisibilityReset
True if we need to force the camera to discard previous frames occlusion.
bool bForcePathTracerReset
True if we should force the path tracer to reset its internal accumulation state.
bool bHasNearClippingPlane
bool bHasSelectedComponents
True if any components are selected in isolation (independent of actor selection)
bool bHMDHiddenAreaMaskActive = false
bool bIsGameView
True if this scene was created from a game world.
bool bIsInstancedStereoEnabled
True if instanced stereo is enabled.
bool bIsLocked
Whether this view was created from a locked viewpoint.
bool bIsMobileMultiViewEnabled
True if mobile multi-view is enabled.
bool bIsMultiViewportEnabled
True if multi-viewport instanced stereo rendering is enabled.
bool bIsOfflineRender
Whether this view is being used to render a high quality offline render.
bool bIsPlanarReflection
Whether this view is being used to render a planar reflection.
bool bIsReflectionCapture
Whether this view is being used to render a reflection capture.
bool bIsSceneCapture
Whether this view is being used to render a scene capture.
bool bIsSceneCaptureCube
Whether the scene capture is a cube map (bIsSceneCapture will also be set).
bool bIsSinglePassStereo
True if any single-pass stereo mechanism is enabled (mobile multi view, instanced stereo multi-layer, or instanced stereo multi-viewport).
bool bIsViewInfo
For sanity checking casts that are assumed to be safe.
bool bIsVirtualTexture
Whether this view is being used to render a runtime virtual texture.
bool bOverrideGPUMask
Use custom GPUmask.
bool bRenderFirstInstanceOnly
Whether this view should render the first instance only of any meshes using instancing.
bool bRenderSceneTwoSided
Whether to force two sided rendering for this view.
bool bReverseCulling
true if ViewMatrix.Determinant() is negative.
bool bSceneCaptureUsesRayTracing
Whether this view may use ray tracing, for views that are used to render a scene capture.
bool bShouldBindInstancedViewUB
True if we need to bind the instanced view uniform buffer parameters.
bool bStaticSceneOnly
Whether to only render static lights and objects.
bool bUseFieldOfViewForLOD
bool bUsePixelInspector
FIntRect CameraConstrainedViewRect
Aspect ratio constrained view rect.
TOptional< FMatrix > ClipToPrevClipOverride
Matrix overrides PrevViewToClip in the view uniform buffer.
FLinearColor ColorScale
Color scale multiplier used during post processing.
FVector CullingOrigin
Monoscopic culling origin, same as the view matrix origin in case of non-stereo.
FName CurrentBufferVisualizationMode
Current buffer visualization mode.
FName CurrentGPUSkinCacheVisualizationMode
Current GPU Skin Cache visualization mode.
FName CurrentGroomVisualizationMode
Current Groom visualization mode.
FName CurrentLumenVisualizationMode
Current Lumen visualization mode.
FName CurrentNaniteVisualizationMode
Current Nanite visualization mode.
FName CurrentRayTracingDebugVisualizationMode
Current ray tracing debug visualization mode.
FName CurrentSubstrateVisualizationMode
Current Substrate visualization mode.
FName CurrentVirtualShadowMapVisualizationMode
Current Virtual Shadow Map visualization mode.
FName CurrentVirtualTextureVisualizationMode
Current Virtual Texture visualization mode.
FName CurrentVisualizeCalibrationColorMaterialName
Current visualize calibration color material name.
FName CurrentVisualizeCalibrationCustomMaterialName
Current visualize calibration custom material name.
FName CurrentVisualizeCalibrationGrayscaleMaterialName
Current visualize calibration grayscale material name.
FIntPoint CursorPos
class FCustomRenderPassBase * CustomRenderPass = nullptr
float DesiredFOV
FVector4f DiffuseOverrideParameter
These can be used to override material parameters across the scene without recompiling shaders.
EDrawDynamicFlags::Type DrawDynamicFlags
FViewElementDrawer * Drawer
An interaction which draws the view's interaction elements.
FTextureRHIRef DynamicCocOffsetLUT
Lookup table for the dynamic CoC offset.
uint64 EditorViewBitflag
The set of (the first 64) groups' visibility info for this view.
const FSceneViewFamily * Family
const ERHIFeatureLevel::Type FeatureLevel
Feature level for this scene.
FFinalPostProcessSettings FinalPostProcessSettings
The final settings for the current viewer position (blended together from many volumes).
float FOV
Actual field of view and that desired by the camera originally.
FPlane GlobalClippingPlane
Global clipping plane being applied to the scene, or all 0's if disabled.
FRHIGPUMask GPUMask
The GPU nodes on which to render this view.
TSet< FPrimitiveComponentId > HiddenPrimitives
The primitives which are hidden for this view.
float InFocusDistance = 0.0
When dynamic CoC offset is enabled, this is the distance from camera at which objects will be in perfect focus (when the CoC offset is maximum so that the final CoC is 0)
uint32 InstanceFactor = 1
When using mobile multi view fallback path we need to instance draw calls ourselves to cover both eyes instead of letting the drivers do it for us.
FVector4f InvDeviceZToWorldZTransform
FShaderResourceViewRHIRef LandscapeIndirectionBuffer
Landscape rendering related data.
FShaderResourceViewRHIRef LandscapePerComponentDataBuffer
FVector4f LensPrincipalPointOffsetScale
In some cases, the principal point of the lens is not at the center of the screen, especially for overlapped tile rendering.
float LODDistanceFactor
Multiplier for cull distance on objects.
float MaterialTextureMipBias
Mip bias to apply in material's samplers.
int32 MaxShadowCascades
Maximum number of shadow cascades to render with.
float NearClippingDistance
FPlane NearClippingPlane
FVector4f NormalOverrideParameter
FVector OriginOffsetThisFrame
World origin offset value.
FLinearColor OverlayColor
TOptional< uint32 > OverrideFrameIndexValue
The frame index to override, useful for keeping determinism when rendering sequences.
TOptional< uint32 > OverrideOutputFrameIndexValue
If set, overrides the Output Frame Index.
int32 PathTracerSeedOffset
Sets an offset to the seed the path tracer is using.
int32 PlayerIndex
Player index this view is associated with or INDEX_NONE.
TOptional< FTransform > PreviousViewTransform
EPrimaryScreenPercentageMethod PrimaryScreenPercentageMethod
int32 PrimaryViewIndex
For stereoscopic rendering, view family index of the primary view associated with this view.
FMatrix ProjectionMatrixUnadjustedForRHI
FVector2f RoughnessOverrideParameter
FSceneViewInitOptions SceneViewInitOptions
FLinearColor SelectionOutlineColor
Selection color for the editor (used by post processing)
TOptional< TSet< FPrimitiveComponentId > > ShowOnlyPrimitives
The primitives which are visible for this view.
FVector4f SpecularOverrideParameter
TBitArray SpriteCategoryVisibility
BitArray representing the visibility state of the various sprite categories in the editor for this view.
FSceneViewStateInterface * State
can be 0 (thumbnail rendering)
EStereoscopicPass StereoPass
For stereoscopic rendering, whether or not this is a full pass, or a left / right eye pass.
int32 StereoViewIndex
For stereoscopic rendering, unique index identifying the view across view families.
FLinearColor SubduedSelectionOutlineColor
Selection color for use in the editor with inactive primitives.
FVector TranslucentSortAxis
Sort axis for when TranslucentSortPolicy is SortAlongAxis.
TEnumAsByte< ETranslucentSortPolicy::Type > TranslucentSortPolicy
Translucent sort mode.
FIntRect UnconstrainedViewRect
float UnderwaterDepth
How far below the water surface this view is.
const FIntRect UnscaledViewRect
FSceneViewOwner ViewActor
The actor which is being viewed from.
FConvexVolume ViewFrustum
uint8 ViewLightingChannelMask = FViewLightingChannels::GetMaskDefault()
View light masking support.
FVector ViewLocation
Variables used to determine the view matrix.
FViewMatrices ViewMatrices
FRotator ViewRotation
TUniformBufferRef< FViewUniformShaderParameters > ViewUniformBuffer
The uniform buffer for the view's parameters.
FShaderResourceViewRHIRef WaterDataBuffer
FShaderResourceViewRHIRef WaterIndirectionBuffer
Water rendering related data.
TArray< FWaterInfoTextureRenderingParams > WaterInfoTextureRenderingParams
int32 WaterInfoTextureViewIndex = INDEX_NONE
Index of the water info texture slice corresponding to this view.
EViewWaterIntersection WaterIntersection = EViewWaterIntersection::OutsideWater
Whether the view intersects water.
float WorldToMetersScale
Protected Attributes
FSceneViewStateInterface * EyeAdaptationViewState = nullptr
TUniformBufferRef< FInstancedViewUniformShaderParameters > InstancedViewUniformBuffer
Instanced view uniform buffer held on the primary view.
const FSceneView * SnapshotOriginView = nullptr
Some views get cloned for certain renders, like shadows (see FViewInfo::CreateSnapshot()).
Private Member Functions
void SetupViewFrustum ()
Private Attributes
const FConvexVolume * DynamicMeshElementsShadowCullFrustum
During GetDynamicMeshElements this will be the correct cull volume for shadow stuff.
FVector PreShadowTranslation
If the above is non-null, a translation that is applied to world-space before transforming by one of the shadow matrices.
TSharedPtr< FConvexVolume > StereoCullingFrustum
Friends
class FSceneRenderer
class FViewSnapshotCache
Detailed Description
A projection from scene space into a 2D screen region.
Definition at line 1374 of file SceneView.h.
Constructor & Destructor Documentation
FSceneView() [1/3]
FSceneView::FSceneView (const FSceneViewInitOptions & InitOptions)
Initialization constructor.
References PRAGMA_DISABLE_DEPRECATION_WARNINGS.
Referenced by FSceneView(), FSceneView(), GetInstancedSceneView(), GetPrimarySceneView(), GetSnapshotOriginView(), and UpdatePlanarReflectionViewMatrix().
FSceneView() [2/3]
PRAGMA_DISABLE_DEPRECATION_WARNINGS FSceneView::FSceneView (const FSceneView & Other) default
These are only needed because of deprecated members being accessed in them.
References FSceneView(), and Other.
FSceneView() [3/3]
FSceneView::FSceneView (FSceneView && Other) default
References FSceneView(), Other, and PRAGMA_ENABLE_DEPRECATION_WARNINGS.
~FSceneView()
virtual PRAGMA_ENABLE_DEPRECATION_WARNINGS FSceneView::~FSceneView () virtual
Default destructor.
Member Function Documentation
AllowGPUParticleUpdate()
FORCEINLINE bool FSceneView::AllowGPUParticleUpdate () const inline
Definition at line 1812 of file SceneView.h.
References bIsPlanarReflection, bIsReflectionCapture, bIsSceneCapture, and FORCEINLINE.
ConfigureBufferVisualizationSettings()
void FSceneView::ConfigureBufferVisualizationSettings ()
Configure post process settings for the buffer visualization system.
ConfigureVisualizeCalibrationSettings()
void FSceneView::ConfigureVisualizeCalibrationSettings ()
Configure post process settings for calibration material.
CursorToScreen()
FVector4 FSceneView::CursorToScreen (float X, float Y, float Z) const
Transforms a cursor location in render target pixel coordinates into the view's screen-space, taking into account the viewport rectangle.
References X, Y, and Z.
Deproject()
FVector FSceneView::Deproject (const FPlane & ScreenPoint) const
Transforms a point from the view's screen-space into world coordinates multiplies X, Y, Z by W before transforming.
References FVector.
DeprojectFVector2D()
void FSceneView::DeprojectFVector2D (const FVector2D & ScreenPos, FVector & out_WorldOrigin, FVector & out_WorldDirection) const
Transforms 2D screen coordinates into a 3D world-space origin and direction.
Parameters
ScreenPos - screen coordinates in pixels
out_WorldOrigin (out) - world-space origin vector
out_WorldDirection (out) - world-space direction vector
References FVector.
DeprojectScreenToWorld() [1/2]
void FSceneView::DeprojectScreenToWorld (const FVector2D & ScreenPos, const FIntRect & ViewRect, const FMatrix & InvViewMatrix, const FMatrix & InvProjMatrix, FVector & out_WorldOrigin, FVector & out_WorldDirection) static
Transforms 2D screen coordinates into a 3D world-space origin and direction.
Parameters
ScreenPos - screen coordinates in pixels
ViewRect - view rectangle
InvViewMatrix - inverse view matrix
InvProjMatrix - inverse projection matrix
out_WorldOrigin (out) - world-space origin vector
out_WorldDirection (out) - world-space direction vector
References FVector.
DeprojectScreenToWorld() [2/2]
void FSceneView::DeprojectScreenToWorld (const FVector2D & ScreenPos, const FIntRect & ViewRect, const FMatrix & InvViewProjMatrix, FVector & out_WorldOrigin, FVector & out_WorldDirection) static
Overload to take a single combined view projection matrix.
References FVector.
EndFinalPostprocessSettings()
void FSceneView::EndFinalPostprocessSettings (const FSceneViewInitOptions & ViewInitOptions)
applied global restrictions from show flags
GetCullingFrustum()
const FConvexVolume & FSceneView::GetCullingFrustum () const inline
Definition at line 1540 of file SceneView.h.
References GetCullingFrustum(), StereoCullingFrustum, and ViewFrustum.
Referenced by GetCullingFrustum().
GetDistanceFieldTemporalSampleIndex()
uint32 FSceneView::GetDistanceFieldTemporalSampleIndex () const
returns the distance field temporal sample index or 0 if there is no view state
GetDynamicMeshElementsShadowCullFrustum()
const FConvexVolume * FSceneView::GetDynamicMeshElementsShadowCullFrustum () const inline
Definition at line 1883 of file SceneView.h.
References DynamicMeshElementsShadowCullFrustum.
GetEyeAdaptationBuffer()
FRDGPooledBuffer * FSceneView::GetEyeAdaptationBuffer () const
Returns the eye adaptation buffer or null if it doesn't exist.
References GetEyeAdaptationBuffer().
Referenced by GetEyeAdaptationBuffer().
GetFeatureLevel()
ERHIFeatureLevel::Type FSceneView::GetFeatureLevel () const inline
Get the feature level for this view (cached from the scene so this is not different per view)
Definition at line 1951 of file SceneView.h.
References FeatureLevel.
GetInstancedSceneView()
const FSceneView * FSceneView::GetInstancedSceneView () const
Get the first secondary view associated with the primary view.
References FSceneView().
Referenced by IsInstancedSceneView().
GetInstancedViewUniformBuffer()
const TUniformBufferRef< FInstancedViewUniformShaderParameters > & FSceneView::GetInstancedViewUniformBuffer () const inline
Returns uniform buffer that is used to access (first) instanced view's properties.
Note: it is not the same as that view's ViewUniformBuffer, albeit it contains all relevant data from it.
Definition at line 2023 of file SceneView.h.
References InstancedViewUniformBuffer.
GetLastEyeAdaptationExposure()
float FSceneView::GetLastEyeAdaptationExposure () const
Returns the eye adaptation exposure or 0.0f if it doesn't exist.
References GetLastEyeAdaptationExposure().
Referenced by GetLastEyeAdaptationExposure().
GetOcclusionFrameCounter()
uint32 FSceneView::GetOcclusionFrameCounter () const
returns a the occlusion frame counter or MAX_uint32 if there is no view state
GetOverwriteLoadAction()
ERenderTargetLoadAction FSceneView::GetOverwriteLoadAction () const inline
Returns the load action to use when overwriting all pixels of a target that you intend to read from.
Takes into account the HMD hidden area mesh.
Definition at line 2029 of file SceneView.h.
References bHMDHiddenAreaMaskActive.
GetPreShadowTranslation()
const FVector & FSceneView::GetPreShadowTranslation () const inline
Definition at line 1886 of file SceneView.h.
References FVector, and PreShadowTranslation.
GetPrimarySceneView()
const FSceneView * FSceneView::GetPrimarySceneView () const
Get the primary view associated with the secondary view.
References FSceneView(), and GetPrimarySceneView().
Referenced by GetPrimarySceneView(), and IsPrimarySceneView().
GetScreenPositionScaleBias()
FVector4f FSceneView::GetScreenPositionScaleBias (const FIntPoint & BufferSize, const FIntRect & ViewRect) static
GetSecondaryViews()
TArray< const FSceneView * > FSceneView::GetSecondaryViews () const
Get all secondary views associated with the primary view.
GetShaderPlatform()
EShaderPlatform FSceneView::GetShaderPlatform () const
Get the feature level for this view.
GetShadowViewMatrices()
const FViewMatrices & FSceneView::GetShadowViewMatrices () const
References ViewMatrices.
GetSnapshotOriginView()
const FSceneView * FSceneView::GetSnapshotOriginView () const inline
Definition at line 2034 of file SceneView.h.
References FSceneView(), and SnapshotOriginView.
GetStereoPassInstanceFactor()
int32 FSceneView::GetStereoPassInstanceFactor () const inline
Instance factor for a stereo pass (normally 2 for ISR views, but see IStereoRendering::GetDesiredNumberOfViews()).
Returns 1 for non-instanced stereo views or regular (split screen etc) views.
Definition at line 1960 of file SceneView.h.
References InstanceFactor.
GetTemporalLODOrigin()
FVector FSceneView::GetTemporalLODOrigin (int32 Index, bool bUseLaggedLODTransition = true) const
Returns the location used as the origin for LOD computations.
Parameters
Index,0 or 1, which LOD origin to return
Returns
LOD origin
References FVector.
GetTemporalLODTransition()
float FSceneView::GetTemporalLODTransition () const
Returns the blend factor between the last two LOD samples.
GetViewDirection()
FVector FSceneView::GetViewDirection () const inline
Definition at line 1881 of file SceneView.h.
References FVector, and ViewMatrices.
GetViewKey()
uint32 FSceneView::GetViewKey () const
returns a unique key for the view state if one exists, otherwise returns zero
GetViewRight()
FVector FSceneView::GetViewRight () const inline
Definition at line 1879 of file SceneView.h.
References FVector, and ViewMatrices.
GetViewUp()
FVector FSceneView::GetViewUp () const inline
Definition at line 1880 of file SceneView.h.
References FVector, and ViewMatrices.
HasEyeAdaptationViewState()
bool FSceneView::HasEyeAdaptationViewState () const inline
Definition at line 2041 of file SceneView.h.
References EyeAdaptationViewState.
HasValidEyeAdaptationBuffer()
bool FSceneView::HasValidEyeAdaptationBuffer () const
Tells if the eye adaptation buffer exists without attempting to allocate it.
References HasValidEyeAdaptationBuffer().
Referenced by HasValidEyeAdaptationBuffer().
IsInstancedSceneView()
bool FSceneView::IsInstancedSceneView () const inline
Checks whether this is the instanced view of a stereo pair.
If the technique supports instanced rendering stereo and ISR is enabled, such views can be skipped.
Definition at line 2014 of file SceneView.h.
References GetInstancedSceneView().
IsInstancedStereoPass()
bool FSceneView::IsInstancedStereoPass () const
True if the view should render as an instanced stereo pass.
IsPerspectiveProjection()
bool FSceneView::IsPerspectiveProjection () const inline
Returns
true:perspective, false:orthographic
Definition at line 1890 of file SceneView.h.
References ViewMatrices.
IsPrimarySceneView()
bool FSceneView::IsPrimarySceneView () const inline
Checks whether this is the primary view of a stereo pair (important in instanced stereo rendering).
Will also be true for any view that isn't stereo.
Definition at line 2005 of file SceneView.h.
References GetPrimarySceneView(), and IsPrimarySceneView().
Referenced by IsPrimarySceneView().
IsRayTracingAllowedForView()
bool FSceneView::IsRayTracingAllowedForView () const inline
Definition at line 2036 of file SceneView.h.
References bAllowRayTracing, bIsSceneCapture, and bSceneCaptureUsesRayTracing.
IsUnderwater()
bool FSceneView::IsUnderwater () const inline
Definition at line 1892 of file SceneView.h.
References UnderwaterDepth.
OverridePostProcessSettings()
void FSceneView::OverridePostProcessSettings (const FPostProcessSettings & Src, float Weight)
custom layers can be combined with the existing settings
Parameters
Weight usually 0..1 but outside range is clamped
References Weight.
PixelToScreen()
FVector4 FSceneView::PixelToScreen (float X, float Y, float Z) const
Transforms a point from pixel coordinates relative to the view's X,Y (left, top) into the view's screen-space.
References X, Y, and Z.
PixelToWorld()
FVector4 FSceneView::PixelToWorld (float X, float Y, float Z) const
Transforms a point from pixel coordinates relative to the view's X,Y (left, top) into the view's world-space.
References X, Y, and Z.
Project()
FPlane FSceneView::Project (const FVector & WorldPoint) const
Transforms a point from the view's world-space into the view's screen-space.
Divides the resulting X, Y, Z by W before returning.
References FVector.
ProjectWorldToScreen()
bool FSceneView::ProjectWorldToScreen (const FVector & WorldPosition, const FIntRect & ViewRect, const FMatrix & ViewProjectionMatrix, FVector2D & out_ScreenPos, bool bShouldCalcOutsideViewPosition = false) static
Transforms 3D world-space origin into 2D screen coordinates.
Parameters
WorldPosition - the 3d world point to transform
ViewRect - view rectangle
ViewProjectionMatrix - combined view projection matrix
out_ScreenPos (out) - screen coordinates in pixels
bShouldCalcOutsideViewPosition - if enabled, calculates the out_ScreenPos if the WorldPosition is outside of ViewProjectionMatrix
References FVector.
ScreenToPixel()
bool FSceneView::ScreenToPixel (const FVector4 & ScreenPoint, FVector2D & OutPixelLocation) const
Transforms a point from the view's screen-space into pixel coordinates relative to the view's X,Y.
ScreenToWorld()
FVector FSceneView::ScreenToWorld (const FVector4 & ScreenPoint) const
Transforms a point from the view's screen-space to world-space.
References FVector.
SetDynamicMeshElementsShadowCullFrustum()
void FSceneView::SetDynamicMeshElementsShadowCullFrustum (const FConvexVolume * InDynamicMeshElementsShadowCullFrustum) inline
Definition at line 1884 of file SceneView.h.
References DynamicMeshElementsShadowCullFrustum.
SetPreShadowTranslation()
void FSceneView::SetPreShadowTranslation (const FVector & InPreShadowTranslation) inline
Definition at line 1887 of file SceneView.h.
References FVector, and PreShadowTranslation.
SetupAntiAliasingMethod()
void FSceneView::SetupAntiAliasingMethod ()
SetupCommonViewUniformBufferParameters()
void FSceneView::SetupCommonViewUniformBufferParameters (FViewUniformShaderParameters & ViewUniformShaderParameters, const FIntPoint & InBufferSize, int32 NumMSAASamples, const FIntRect & InEffectiveViewRect, const FViewMatrices & InViewMatrices, const FViewMatrices & InPrevViewMatrices) const
Populates the uniform buffer prameters common to all scene view use cases View parameters should be set up in this method if they are required for the view to render properly.
This is to avoid code duplication and uninitialized parameters in other places that create view uniform parameters (e.g Slate)
SetupViewFrustum()
void FSceneView::SetupViewFrustum () private
SetupViewRectUniformBufferParameters()
void FSceneView::SetupViewRectUniformBufferParameters (FViewUniformShaderParameters & ViewUniformShaderParameters, const FIntPoint & InBufferSize, const FIntRect & InEffectiveViewRect, const FViewMatrices & InViewMatrices, const FViewMatrices & InPrevViewMatrice) const
Sets up the view rect parameters in the view's uniform shader parameters.
StartFinalPostprocessSettings()
void FSceneView::StartFinalPostprocessSettings (FVector InViewLocation)
Setup defaults and depending on view position (postprocess volumes)
References FVector.
UE_DEPRECATED() [1/4]
FSceneView::UE_DEPRECATED (5. 2, "Use GetEyeAdaptationBuffer() instead.") const
References UE_DEPRECATED().
UE_DEPRECATED() [2/4]
FSceneView::UE_DEPRECATED (5. 2, "Use HasValidEyeAdaptationBuffer() instead.") const
UE_DEPRECATED() [3/4]
FSceneView::UE_DEPRECATED (5. 6, "Use GetCullingFrustum() instead.")
UE_DEPRECATED() [4/4]
FSceneView::UE_DEPRECATED (5. 6, "Use GetShadowViewMatrices instead")
Referenced by UE_DEPRECATED().
UpdatePlanarReflectionViewMatrix()
void FSceneView::UpdatePlanarReflectionViewMatrix (const FSceneView & SourceView, const FMirrorMatrix & MirrorMatrix)
If we late update a view, we need to also late update any planar reflection views derived from it.
References FSceneView().
UpdateProjectionMatrix()
void FSceneView::UpdateProjectionMatrix (const FMatrix & NewProjectionMatrix)
UpdateViewMatrix()
void FSceneView::UpdateViewMatrix ()
Allow things like HMD displays to update the view matrix at the last minute, to minimize perceived latency.
WorldToPixel()
bool FSceneView::WorldToPixel (const FVector & WorldPoint, FVector2D & OutPixelLocation) const
Transforms a point from the view's world-space into pixel coordinates relative to the view's X,Y (left, top).
References FVector.
WorldToScreen()
FVector4 FSceneView::WorldToScreen (const FVector & WorldPoint) const
Transforms a point from world-space to the view's screen-space.
References FVector.
Friends And Related Symbol Documentation
FSceneRenderer
friend class FSceneRenderer friend
Definition at line 1788 of file SceneView.h.
References FSceneRenderer.
Referenced by FSceneRenderer.
FViewSnapshotCache
friend class FViewSnapshotCache friend
Definition at line 2047 of file SceneView.h.
References FViewSnapshotCache.
Referenced by FViewSnapshotCache.
Field Documentation
AdditionalSelectionOutlineColors
TStaticArray<FLinearColor, 6> FSceneView::AdditionalSelectionOutlineColors
Additional selection colors for the editor (used by post processing)
Definition at line 1710 of file SceneView.h.
AmbientOcclusionOverrideParameter
FVector2f FSceneView::AmbientOcclusionOverrideParameter
Definition at line 1520 of file SceneView.h.
Referenced by FSetupViewUniformParametersInputs::Create().
AntiAliasingMethod
EAntiAliasingMethod FSceneView::AntiAliasingMethod
Definition at line 1725 of file SceneView.h.
Aspects
UE::StereoRenderUtils::FStereoShaderAspects FSceneView::Aspects
Stereo aspects of the shader pipeline based on this view's shader platform.
Definition at line 1785 of file SceneView.h.
AtmosphereInscatterTexture
FTextureRHIRef FSceneView::AtmosphereInscatterTexture
Definition at line 1733 of file SceneView.h.
AtmosphereIrradianceTexture
FTextureRHIRef FSceneView::AtmosphereIrradianceTexture
Definition at line 1732 of file SceneView.h.
AtmosphereTransmittanceTexture
FTextureRHIRef FSceneView::AtmosphereTransmittanceTexture
Parameters for atmospheric fog.
Definition at line 1731 of file SceneView.h.
BackgroundColor
FLinearColor FSceneView::BackgroundColor
Definition at line 1435 of file SceneView.h.
bAllowCrossGPUTransfer
bool FSceneView::bAllowCrossGPUTransfer
Allow cross GPU transfer for this view.
Definition at line 1451 of file SceneView.h.
bAllowRayTracing
bool FSceneView::bAllowRayTracing = true
Set to false to disable ray tracing on this view.
Use IsRayTracingAllowedForView() function to test for ray tracing, not this bool.
Definition at line 1779 of file SceneView.h.
Referenced by IsRayTracingAllowedForView().
bAllowTemporalJitter
bool FSceneView::bAllowTemporalJitter
Definition at line 1533 of file SceneView.h.
bAllowTranslucentPrimitivesInHitProxy
bool FSceneView::bAllowTranslucentPrimitivesInHitProxy
True if we should draw translucent objects when rendering hit proxies.
Definition at line 1701 of file SceneView.h.
BaseHmdLocation
FVector FSceneView::BaseHmdLocation
Definition at line 1420 of file SceneView.h.
BaseHmdOrientation
FQuat FSceneView::BaseHmdOrientation
Definition at line 1419 of file SceneView.h.
bCameraCut
bool FSceneView::bCameraCut
Whether we did a camera cut for this view this frame.
Definition at line 1567 of file SceneView.h.
Referenced by FSetupViewUniformParametersInputs::Create().
bCameraMotionBlur
TOptional<bool> FSceneView::bCameraMotionBlur
Whether to enable motion blur caused by camera movements.
Definition at line 1690 of file SceneView.h.
bDisableDistanceBasedFadeTransitions
bool FSceneView::bDisableDistanceBasedFadeTransitions
Whether we should disable distance-based fade transitions for this frame (usually after a large camera movement.)
Definition at line 1642 of file SceneView.h.
bEnableDynamicCocOffset
bool FSceneView::bEnableDynamicCocOffset = false
Enables a CoC offset whose offset value changes with pixel's scene depth.
Definition at line 1764 of file SceneView.h.
bExcludeFromSceneTextureExtents
bool FSceneView::bExcludeFromSceneTextureExtents = false
Whether this view should be excluded from extent history tracking.
Definition at line 1645 of file SceneView.h.
bEyeAdaptationAllViewPixels
bool FSceneView::bEyeAdaptationAllViewPixels
Whether to generate histogram eye adaptation from all view pixels, useful with a shared EyeAdaptationViewState.
Pixels for views must form a contiguous rect.
Definition at line 1587 of file SceneView.h.
bForceCameraVisibilityReset
bool FSceneView::bForceCameraVisibilityReset
True if we need to force the camera to discard previous frames occlusion.
Necessary for overlapped tile rendering where we discard previous frame occlusion because the projection matrix changes.
Definition at line 1639 of file SceneView.h.
bForcePathTracerReset
bool FSceneView::bForcePathTracerReset
True if we should force the path tracer to reset its internal accumulation state.
Definition at line 1648 of file SceneView.h.
bHasNearClippingPlane
bool FSceneView::bHasNearClippingPlane
Definition at line 1545 of file SceneView.h.
bHasSelectedComponents
bool FSceneView::bHasSelectedComponents
True if any components are selected in isolation (independent of actor selection)
Definition at line 1712 of file SceneView.h.
bHMDHiddenAreaMaskActive
bool FSceneView::bHMDHiddenAreaMaskActive = false
Definition at line 1466 of file SceneView.h.
Referenced by GetOverwriteLoadAction().
bIsGameView
bool FSceneView::bIsGameView
True if this scene was created from a game world.
Definition at line 1573 of file SceneView.h.
bIsInstancedStereoEnabled
bool FSceneView::bIsInstancedStereoEnabled
True if instanced stereo is enabled.
Definition at line 1621 of file SceneView.h.
bIsLocked
bool FSceneView::bIsLocked
Whether this view was created from a locked viewpoint.
Definition at line 1612 of file SceneView.h.
bIsMobileMultiViewEnabled
bool FSceneView::bIsMobileMultiViewEnabled
True if mobile multi-view is enabled.
Definition at line 1627 of file SceneView.h.
bIsMultiViewportEnabled
bool FSceneView::bIsMultiViewportEnabled
True if multi-viewport instanced stereo rendering is enabled.
Definition at line 1624 of file SceneView.h.
bIsOfflineRender
bool FSceneView::bIsOfflineRender
Whether this view is being used to render a high quality offline render.
Definition at line 1606 of file SceneView.h.
bIsPlanarReflection
bool FSceneView::bIsPlanarReflection
Whether this view is being used to render a planar reflection.
Definition at line 1600 of file SceneView.h.
Referenced by AllowGPUParticleUpdate().
bIsReflectionCapture
bool FSceneView::bIsReflectionCapture
Whether this view is being used to render a reflection capture.
Definition at line 1597 of file SceneView.h.
Referenced by AllowGPUParticleUpdate().
bIsSceneCapture
bool FSceneView::bIsSceneCapture
Whether this view is being used to render a scene capture.
Definition at line 1581 of file SceneView.h.
Referenced by AllowGPUParticleUpdate(), and IsRayTracingAllowedForView().
bIsSceneCaptureCube
bool FSceneView::bIsSceneCaptureCube
Whether the scene capture is a cube map (bIsSceneCapture will also be set).
Definition at line 1584 of file SceneView.h.
bIsSinglePassStereo
bool FSceneView::bIsSinglePassStereo
True if any single-pass stereo mechanism is enabled (mobile multi view, instanced stereo multi-layer, or instanced stereo multi-viewport).
Not related to the deprecated NVidia feature known as Single-Pass Stereo.
Definition at line 1634 of file SceneView.h.
bIsViewInfo
bool FSceneView::bIsViewInfo
For sanity checking casts that are assumed to be safe.
Definition at line 1576 of file SceneView.h.
bIsVirtualTexture
bool FSceneView::bIsVirtualTexture
Whether this view is being used to render a runtime virtual texture.
Definition at line 1603 of file SceneView.h.
bOverrideGPUMask
bool FSceneView::bOverrideGPUMask
Use custom GPUmask.
Definition at line 1454 of file SceneView.h.
bRenderFirstInstanceOnly
bool FSceneView::bRenderFirstInstanceOnly
Whether this view should render the first instance only of any meshes using instancing.
Definition at line 1460 of file SceneView.h.
bRenderSceneTwoSided
bool FSceneView::bRenderSceneTwoSided
Whether to force two sided rendering for this view.
Definition at line 1609 of file SceneView.h.
bReverseCulling
bool FSceneView::bReverseCulling
true if ViewMatrix.Determinant() is negative.
Definition at line 1555 of file SceneView.h.
Referenced by FSetupViewUniformParametersInputs::Create().
bSceneCaptureUsesRayTracing
bool FSceneView::bSceneCaptureUsesRayTracing
Whether this view may use ray tracing, for views that are used to render a scene capture.
Use IsRayTracingAllowedForView() to test for ray tracing, not this bool. Filled in based on the bUseRayTracingIfEnabled field in the scene capture component and r.RayTracing.SceneCaptures CVar (-1 == use value from component, 0 == disable globally, 1 == enable globally).
Definition at line 1594 of file SceneView.h.
Referenced by IsRayTracingAllowedForView().
bShouldBindInstancedViewUB
bool FSceneView::bShouldBindInstancedViewUB
True if we need to bind the instanced view uniform buffer parameters.
Definition at line 1630 of file SceneView.h.
bStaticSceneOnly
bool FSceneView::bStaticSceneOnly
Whether to only render static lights and objects.
This is used when capturing the scene for reflection captures, which aren't updated at runtime.
Definition at line 1618 of file SceneView.h.
bUseFieldOfViewForLOD
bool FSceneView::bUseFieldOfViewForLOD
Definition at line 1463 of file SceneView.h.
bUsePixelInspector
bool FSceneView::bUsePixelInspector
Definition at line 1509 of file SceneView.h.
CameraConstrainedViewRect
FIntRect FSceneView::CameraConstrainedViewRect
Aspect ratio constrained view rect.
In the editor, when attached to a camera actor and the camera black bar showflag is enabled, the normal viewrect remains as the full viewport, and the black bars are just simulated by drawing black bars. This member stores the effective constrained area within the bars.
Definition at line 1666 of file SceneView.h.
ClipToPrevClipOverride
TOptional<FMatrix> FSceneView::ClipToPrevClipOverride
Matrix overrides PrevViewToClip in the view uniform buffer.
Used for replacing motion blur caused by the current camera movements with a custom transform.
Definition at line 1694 of file SceneView.h.
ColorScale
FLinearColor FSceneView::ColorScale
Color scale multiplier used during post processing.
Definition at line 1439 of file SceneView.h.
CullingOrigin
FVector FSceneView::CullingOrigin
Monoscopic culling origin, same as the view matrix origin in case of non-stereo.
Definition at line 1552 of file SceneView.h.
CurrentBufferVisualizationMode
FName FSceneView::CurrentBufferVisualizationMode
Current buffer visualization mode.
Definition at line 1475 of file SceneView.h.
CurrentGPUSkinCacheVisualizationMode
FName FSceneView::CurrentGPUSkinCacheVisualizationMode
Current GPU Skin Cache visualization mode.
Definition at line 1505 of file SceneView.h.
CurrentGroomVisualizationMode
FName FSceneView::CurrentGroomVisualizationMode
Current Groom visualization mode.
Definition at line 1487 of file SceneView.h.
CurrentLumenVisualizationMode
FName FSceneView::CurrentLumenVisualizationMode
Current Lumen visualization mode.
Definition at line 1481 of file SceneView.h.
CurrentNaniteVisualizationMode
FName FSceneView::CurrentNaniteVisualizationMode
Current Nanite visualization mode.
Definition at line 1478 of file SceneView.h.
CurrentRayTracingDebugVisualizationMode
FName FSceneView::CurrentRayTracingDebugVisualizationMode
Current ray tracing debug visualization mode.
Definition at line 1984 of file SceneView.h.
CurrentSubstrateVisualizationMode
FName FSceneView::CurrentSubstrateVisualizationMode
Current Substrate visualization mode.
Definition at line 1484 of file SceneView.h.
CurrentVirtualShadowMapVisualizationMode
FName FSceneView::CurrentVirtualShadowMapVisualizationMode
Current Virtual Shadow Map visualization mode.
Definition at line 1490 of file SceneView.h.
CurrentVirtualTextureVisualizationMode
FName FSceneView::CurrentVirtualTextureVisualizationMode
Current Virtual Texture visualization mode.
Definition at line 1493 of file SceneView.h.
CurrentVisualizeCalibrationColorMaterialName
FName FSceneView::CurrentVisualizeCalibrationColorMaterialName
Current visualize calibration color material name.
Definition at line 1496 of file SceneView.h.
CurrentVisualizeCalibrationCustomMaterialName
FName FSceneView::CurrentVisualizeCalibrationCustomMaterialName
Current visualize calibration custom material name.
Definition at line 1502 of file SceneView.h.
CurrentVisualizeCalibrationGrayscaleMaterialName
FName FSceneView::CurrentVisualizeCalibrationGrayscaleMaterialName
Current visualize calibration grayscale material name.
Definition at line 1499 of file SceneView.h.
CursorPos
FIntPoint FSceneView::CursorPos
Definition at line 1570 of file SceneView.h.
Referenced by FSetupViewUniformParametersInputs::Create().
CustomRenderPass
class FCustomRenderPassBase* FSceneView::CustomRenderPass = nullptr
Definition at line 1578 of file SceneView.h.
DesiredFOV
float FSceneView::DesiredFOV
Definition at line 1470 of file SceneView.h.
DiffuseOverrideParameter
FVector4f FSceneView::DiffuseOverrideParameter
These can be used to override material parameters across the scene without recompiling shaders.
The last component is how much to include of the material's value for that parameter, so 0 will completely remove the material's value.
Definition at line 1516 of file SceneView.h.
Referenced by FSetupViewUniformParametersInputs::Create().
DrawDynamicFlags
EDrawDynamicFlags::Type FSceneView::DrawDynamicFlags
Definition at line 1472 of file SceneView.h.
Drawer
FViewElementDrawer* FSceneView::Drawer
An interaction which draws the view's interaction elements.
Definition at line 1403 of file SceneView.h.
DynamicCocOffsetLUT
FTextureRHIRef FSceneView::DynamicCocOffsetLUT
Lookup table for the dynamic CoC offset.
Definition at line 1770 of file SceneView.h.
DynamicMeshElementsShadowCullFrustum
const FConvexVolume* FSceneView::DynamicMeshElementsShadowCullFrustum private
During GetDynamicMeshElements this will be the correct cull volume for shadow stuff.
Definition at line 1386 of file SceneView.h.
Referenced by GetDynamicMeshElementsShadowCullFrustum(), and SetDynamicMeshElementsShadowCullFrustum().
EditorViewBitflag
uint64 FSceneView::EditorViewBitflag
The set of (the first 64) groups' visibility info for this view.
Definition at line 1698 of file SceneView.h.
EyeAdaptationViewState
FSceneViewStateInterface* FSceneView::EyeAdaptationViewState = nullptr protected
Definition at line 2049 of file SceneView.h.
Referenced by HasEyeAdaptationViewState().
Family
const FSceneViewFamily* FSceneView::Family
Definition at line 1377 of file SceneView.h.
Referenced by FSetupViewUniformParametersInputs::Create(), and FInstancedStaticMeshSceneProxy::GetViewRelevance().
FeatureLevel
const ERHIFeatureLevel::Type FSceneView::FeatureLevel
Feature level for this scene.
Definition at line 1773 of file SceneView.h.
Referenced by GetFeatureLevel().
FinalPostProcessSettings
FFinalPostProcessSettings FSceneView::FinalPostProcessSettings
The final settings for the current viewer position (blended together from many volumes).
Setup by the main thread, passed to the render thread and never touched again by the main thread.
Definition at line 1719 of file SceneView.h.
Referenced by FSetupViewUniformParametersInputs::Create().
FOV
float FSceneView::FOV
Actual field of view and that desired by the camera originally.
Definition at line 1469 of file SceneView.h.
Referenced by FSetupViewUniformParametersInputs::Create().
GlobalClippingPlane
FPlane FSceneView::GlobalClippingPlane
Global clipping plane being applied to the scene, or all 0's if disabled.
This is used when rendering the planar reflection pass.
Definition at line 1660 of file SceneView.h.
Referenced by FSetupViewUniformParametersInputs::Create().
GPUMask
FRHIGPUMask FSceneView::GPUMask
The GPU nodes on which to render this view.
Definition at line 1457 of file SceneView.h.
HiddenPrimitives
TSet<FPrimitiveComponentId> FSceneView::HiddenPrimitives
The primitives which are hidden for this view.
Definition at line 1526 of file SceneView.h.
InFocusDistance
float FSceneView::InFocusDistance = 0.0
When dynamic CoC offset is enabled, this is the distance from camera at which objects will be in perfect focus (when the CoC offset is maximum so that the final CoC is 0)
Definition at line 1767 of file SceneView.h.
InstancedViewUniformBuffer
TUniformBufferRef<FInstancedViewUniformShaderParameters> FSceneView::InstancedViewUniformBuffer protected
Instanced view uniform buffer held on the primary view.
Definition at line 2052 of file SceneView.h.
Referenced by GetInstancedViewUniformBuffer().
InstanceFactor
uint32 FSceneView::InstanceFactor = 1
When using mobile multi view fallback path we need to instance draw calls ourselves to cover both eyes instead of letting the drivers do it for us.
Definition at line 1776 of file SceneView.h.
Referenced by GetStereoPassInstanceFactor().
InvDeviceZToWorldZTransform
FVector4f FSceneView::InvDeviceZToWorldZTransform
Definition at line 1558 of file SceneView.h.
Referenced by FSetupViewUniformParametersInputs::Create().
LandscapeIndirectionBuffer
FShaderResourceViewRHIRef FSceneView::LandscapeIndirectionBuffer
Landscape rendering related data.
Definition at line 1760 of file SceneView.h.
LandscapePerComponentDataBuffer
FShaderResourceViewRHIRef FSceneView::LandscapePerComponentDataBuffer
Definition at line 1761 of file SceneView.h.
LensPrincipalPointOffsetScale
FVector4f FSceneView::LensPrincipalPointOffsetScale
In some cases, the principal point of the lens is not at the center of the screen, especially for overlapped tile rendering.
So given a UV in [-1,1] viewport space, convert it to the [-1,1] viewport space of the lens using LensUV = LensPrincipalPointOffsetScale.xy ScreenUV * LensPrincipalPointOffsetScale.zw; This value is FVector4(0,0,1,1) unless overridden.
Definition at line 1687 of file SceneView.h.
LODDistanceFactor
float FSceneView::LODDistanceFactor
Multiplier for cull distance on objects.
Definition at line 1564 of file SceneView.h.
MaterialTextureMipBias
float FSceneView::MaterialTextureMipBias
Mip bias to apply in material's samplers.
Definition at line 1523 of file SceneView.h.
MaxShadowCascades
int32 FSceneView::MaxShadowCascades
Maximum number of shadow cascades to render with.
Definition at line 1412 of file SceneView.h.
NearClippingDistance
float FSceneView::NearClippingDistance
Definition at line 1549 of file SceneView.h.
NearClippingPlane
FPlane FSceneView::NearClippingPlane
Definition at line 1547 of file SceneView.h.
NormalOverrideParameter
FVector4f FSceneView::NormalOverrideParameter
Definition at line 1518 of file SceneView.h.
Referenced by FSetupViewUniformParametersInputs::Create().
OriginOffsetThisFrame
FVector FSceneView::OriginOffsetThisFrame
World origin offset value.
Non-zero only for a single frame when origin is rebased
Definition at line 1561 of file SceneView.h.
OverlayColor
FLinearColor FSceneView::OverlayColor
Definition at line 1436 of file SceneView.h.
OverrideFrameIndexValue
TOptional<uint32> FSceneView::OverrideFrameIndexValue
The frame index to override, useful for keeping determinism when rendering sequences.
Definition at line 1675 of file SceneView.h.
OverrideOutputFrameIndexValue
TOptional<uint32> FSceneView::OverrideOutputFrameIndexValue
If set, overrides the Output Frame Index.
Useful for Halton-like offsets that should produce the same results in multi-sample accumulation when rendering sequences. If unset, renderer defaults to FrameIndex.
Definition at line 1680 of file SceneView.h.
PathTracerSeedOffset
int32 FSceneView::PathTracerSeedOffset
Sets an offset to the seed the path tracer is using.
Definition at line 1651 of file SceneView.h.
PlayerIndex
int32 FSceneView::PlayerIndex
Player index this view is associated with or INDEX_NONE.
Definition at line 1400 of file SceneView.h.
PreShadowTranslation
FVector FSceneView::PreShadowTranslation private
If the above is non-null, a translation that is applied to world-space before transforming by one of the shadow matrices.
Definition at line 1388 of file SceneView.h.
Referenced by GetPreShadowTranslation(), and SetPreShadowTranslation().
PreviousViewTransform
TOptional<FTransform> FSceneView::PreviousViewTransform
Definition at line 1422 of file SceneView.h.
PrimaryScreenPercentageMethod
EPrimaryScreenPercentageMethod FSceneView::PrimaryScreenPercentageMethod
Definition at line 1728 of file SceneView.h.
PrimaryViewIndex
int32 FSceneView::PrimaryViewIndex
For stereoscopic rendering, view family index of the primary view associated with this view.
Definition at line 1448 of file SceneView.h.
ProjectionMatrixUnadjustedForRHI
FMatrix FSceneView::ProjectionMatrixUnadjustedForRHI
Definition at line 1433 of file SceneView.h.
RoughnessOverrideParameter
FVector2f FSceneView::RoughnessOverrideParameter
Definition at line 1519 of file SceneView.h.
Referenced by FSetupViewUniformParametersInputs::Create().
SceneViewInitOptions
FSceneViewInitOptions FSceneView::SceneViewInitOptions
Definition at line 1394 of file SceneView.h.
SelectionOutlineColor
FLinearColor FSceneView::SelectionOutlineColor
Selection color for the editor (used by post processing)
Definition at line 1706 of file SceneView.h.
ShowOnlyPrimitives
TOptional<TSet<FPrimitiveComponentId> > FSceneView::ShowOnlyPrimitives
The primitives which are visible for this view.
If the array is not empty, all other primitives will be hidden.
Definition at line 1529 of file SceneView.h.
SnapshotOriginView
const FSceneView* FSceneView::SnapshotOriginView = nullptr protected
Some views get cloned for certain renders, like shadows (see FViewInfo::CreateSnapshot()).
If that's the case, this will point to the view this one originates from
Definition at line 1791 of file SceneView.h.
Referenced by GetSnapshotOriginView().
SpecularOverrideParameter
FVector4f FSceneView::SpecularOverrideParameter
Definition at line 1517 of file SceneView.h.
Referenced by FSetupViewUniformParametersInputs::Create().
SpriteCategoryVisibility
TBitArray FSceneView::SpriteCategoryVisibility
BitArray representing the visibility state of the various sprite categories in the editor for this view.
Definition at line 1704 of file SceneView.h.
State
FSceneViewStateInterface* FSceneView::State
can be 0 (thumbnail rendering)
Definition at line 1379 of file SceneView.h.
StereoCullingFrustum
TSharedPtr<FConvexVolume> FSceneView::StereoCullingFrustum private
Definition at line 1390 of file SceneView.h.
Referenced by GetCullingFrustum().
StereoPass
EStereoscopicPass FSceneView::StereoPass
For stereoscopic rendering, whether or not this is a full pass, or a left / right eye pass.
Definition at line 1442 of file SceneView.h.
StereoViewIndex
int32 FSceneView::StereoViewIndex
For stereoscopic rendering, unique index identifying the view across view families.
Definition at line 1445 of file SceneView.h.
SubduedSelectionOutlineColor
FLinearColor FSceneView::SubduedSelectionOutlineColor
Selection color for use in the editor with inactive primitives.
Definition at line 1708 of file SceneView.h.
TranslucentSortAxis
FVector FSceneView::TranslucentSortAxis
Sort axis for when TranslucentSortPolicy is SortAlongAxis.
Definition at line 1669 of file SceneView.h.
TranslucentSortPolicy
TEnumAsByte<ETranslucentSortPolicy::Type> FSceneView::TranslucentSortPolicy
Translucent sort mode.
Definition at line 1672 of file SceneView.h.
UnconstrainedViewRect
FIntRect FSceneView::UnconstrainedViewRect
Definition at line 1409 of file SceneView.h.
UnderwaterDepth
float FSceneView::UnderwaterDepth
How far below the water surface this view is.
-1 means the view is out of water.
Definition at line 1654 of file SceneView.h.
Referenced by IsUnderwater().
UnscaledViewRect
const FIntRect FSceneView::UnscaledViewRect
Definition at line 1406 of file SceneView.h.
Referenced by FSetupViewUniformParametersInputs::Create().
ViewActor
FSceneViewOwner FSceneView::ViewActor
The actor which is being viewed from.
Definition at line 1397 of file SceneView.h.
ViewFrustum
FConvexVolume FSceneView::ViewFrustum
Definition at line 1535 of file SceneView.h.
Referenced by FDebugRenderSceneProxy::BoxInView(), GetCullingFrustum(), FDebugRenderSceneProxy::PointInView(), FDebugRenderSceneProxy::SegmentInView(), and FDebugRenderSceneProxy::SphereInView().
ViewLightingChannelMask
uint8 FSceneView::ViewLightingChannelMask = FViewLightingChannels::GetMaskDefault()
View light masking support.
Some systems assume the same mask setting for all views within a family, with potential artifacts if views use different masks.
Definition at line 1782 of file SceneView.h.
ViewLocation
FVector FSceneView::ViewLocation
Variables used to determine the view matrix.
Definition at line 1417 of file SceneView.h.
ViewMatrices
FViewMatrices FSceneView::ViewMatrices
Definition at line 1414 of file SceneView.h.
Referenced by GetShadowViewMatrices(), GetViewDirection(), GetViewRight(), GetViewUp(), IsPerspectiveProjection(), and FDebugRenderSceneProxy::PointInRange().
ViewRotation
FRotator FSceneView::ViewRotation
Definition at line 1418 of file SceneView.h.
ViewUniformBuffer
TUniformBufferRef<FViewUniformShaderParameters> FSceneView::ViewUniformBuffer
The uniform buffer for the view's parameters.
This is only initialized in the rendering thread's copies of the FSceneView.
Definition at line 1382 of file SceneView.h.
WaterDataBuffer
FShaderResourceViewRHIRef FSceneView::WaterDataBuffer
Definition at line 1737 of file SceneView.h.
WaterIndirectionBuffer
FShaderResourceViewRHIRef FSceneView::WaterIndirectionBuffer
Water rendering related data.
Definition at line 1736 of file SceneView.h.
WaterInfoTextureRenderingParams
TArray<FWaterInfoTextureRenderingParams> FSceneView::WaterInfoTextureRenderingParams
Definition at line 1757 of file SceneView.h.
WaterInfoTextureViewIndex
int32 FSceneView::WaterInfoTextureViewIndex = INDEX_NONE
Index of the water info texture slice corresponding to this view.
Definition at line 1739 of file SceneView.h.
WaterIntersection
EViewWaterIntersection FSceneView::WaterIntersection = EViewWaterIntersection::OutsideWater
Whether the view intersects water.
Definition at line 1657 of file SceneView.h.
WorldToMetersScale
float FSceneView::WorldToMetersScale
Definition at line 1421 of file SceneView.h.
The documentation for this class was generated from the following file:
Runtime/Engine/Public/SceneView.h