Unreal Engine 5.6 C++ API: TFixedTickReplicator_Server< InModelDef > Class Template Reference
TFixedTickReplicator_Server< InModelDef > Class Template Reference
#include "NetworkPredictionSerialization.h"
Public Types
using InputType = typename StateTypes::InputType
using ModelDef = InModelDef
using StateTypes = typename ModelDef::StateTypes
Static Public Member Functions
static void EatCmd (const FNetSerializeParams &P)
static void NetRecv (const FNetSerializeParams &P, TServerRecvData_Fixed< ModelDef > &ServerRecvData, TModelDataStore< ModelDef > *DataStore, FFixedTickState *TickState)
static void NetSend (const FNetSerializeParams &P, FNetworkPredictionID ID, TModelDataStore< ModelDef > *DataStore, FFixedTickState *TickState)
static void SetNumInputsPerSend (int32 NumToSend)
Static Private Attributes
static int32 NumInputsPerSend = 6
Detailed Description
template<typename InModelDef>
class TFixedTickReplicator_Server< InModelDef >
Definition at line 100 of file NetworkPredictionSerialization.h.
Member Typedef Documentation
InputType
template<typename InModelDef> using TFixedTickReplicator_Server< InModelDef >::InputType = typename StateTypes::InputType
Definition at line 106 of file NetworkPredictionSerialization.h.
ModelDef
template<typename InModelDef> using TFixedTickReplicator_Server< InModelDef >::ModelDef = InModelDef
Definition at line 104 of file NetworkPredictionSerialization.h.
StateTypes
template<typename InModelDef> using TFixedTickReplicator_Server< InModelDef >::StateTypes = typename ModelDef::StateTypes
Definition at line 105 of file NetworkPredictionSerialization.h.
Member Function Documentation
EatCmd()
template<typename InModelDef> void TFixedTickReplicator_Server< InModelDef >::EatCmd (const FNetSerializeParams & P) inline static
Definition at line 204 of file NetworkPredictionSerialization.h.
References Empty, and FNetworkPredictionDriverBase< ModelDef >::NetSerialize().
Referenced by NetRecv(), and NetSend().
NetRecv()
template<typename InModelDef> void TFixedTickReplicator_Server< InModelDef >::NetRecv (const FNetSerializeParams & P, TServerRecvData_Fixed< ModelDef > & ServerRecvData, TModelDataStore< ModelDef > * DataStore, FFixedTickState * TickState) inline static
Definition at line 116 of file NetworkPredictionSerialization.h.
References Ar, FNetSerializeParams::Ar, EatCmd(), EndFrame, FFixedTickState::FixedStepMS, TServerRecvData_Fixed< ModelDef >::InputBuffer, TServerRecvData_Fixed< ModelDef >::LastConsumedFrame, TServerRecvData_Fixed< ModelDef >::LastRecvFrame, FNetworkPredictionDriverBase< ModelDef >::NetSerialize(), NETSIM_CHECKSUM, npEnsure, NumInputsPerSend, FFixedTickState::PendingFrame, FNetworkPredictionSerialization::ReadCompressedFrame(), UE_NP_TRACE_NET_RECV, UE_NP_TRACE_SYSTEM_FAULT, and UE_NP_TRACE_USER_STATE_INPUT.
NetSend()
template<typename InModelDef> void TFixedTickReplicator_Server< InModelDef >::NetSend (const FNetSerializeParams & P, FNetworkPredictionID ID, TModelDataStore< ModelDef > * DataStore, FFixedTickState * TickState) inline static
Definition at line 169 of file NetworkPredictionSerialization.h.
References Ar, FNetSerializeParams::Ar, TInstanceFrameState< ModelDef >::Buffer, EatCmd(), EndFrame, NetworkPredictionCVars::ForceSendDefaultInputCommands(), TModelDataStore< ModelDef >::Frames, ID, FNetworkPredictionDriverBase< ModelDef >::NetSerialize(), NETSIM_CHECKSUM, npCheckSlow, NumInputsPerSend, FFixedTickState::PendingFrame, and FNetworkPredictionSerialization::WriteCompressedFrame().
SetNumInputsPerSend()
template<typename InModelDef> void TFixedTickReplicator_Server< InModelDef >::SetNumInputsPerSend (int32 NumToSend) inline static
Definition at line 108 of file NetworkPredictionSerialization.h.
References NumInputsPerSend.
Field Documentation
NumInputsPerSend
template<typename InModelDef> int32 TFixedTickReplicator_Server< InModelDef >::NumInputsPerSend = 6 inline static private
Definition at line 211 of file NetworkPredictionSerialization.h.
Referenced by NetRecv(), NetSend(), and SetNumInputsPerSend().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/NetworkPrediction/Source/NetworkPrediction/Public/NetworkPredictionSerialization.h