Unreal Engine 5.6 C++ API: FThreadManager Class Reference
FThreadManager Class Reference
Manages runnables and runnable threads.
#include "ThreadManager.h"
Data Structures
struct FThreadStackBackTrace
Public Member Functions
FThreadManager ()
~FThreadManager ()
void AddThread (uint32 ThreadId, FRunnableThread *Thread)
Used internally to add a new thread object.
void ForEachThread (TFunction< void(uint32 ThreadId, FRunnableThread *Thread)> Func)
Enumerate each thread.
void ForEachThreadStackBackTrace (TFunctionRef< bool(uint32 ThreadId, const TCHAR *ThreadName, const TConstArrayView< uint64 > &StackTrace)> Func)
void GetAllThreadStackBackTraces (TArray< FThreadStackBackTrace > &StackTraces)
int32 NumThreads () const
Get the number of registered threads.
void RemoveThread (FRunnableThread *Thread)
Used internally to remove thread object.
void Tick ()
Ticks all fake threads and their runnable objects.
Static Public Member Functions
static FThreadManager & Get ()
Access to the singleton object.
static const FString & GetThreadName (uint32 ThreadId)
Returns the name of a thread given its TLS id.
Private Types
using FThreads = TMap<uint32, FRunnableThread*, TInlineSetAllocator<256>>
Private Member Functions
bool CheckThreadListSafeToContinueIteration ()
TArray< FRunnableThread * > GetForkableThreads ()
Returns a list of registered forkable threads.
const FString & GetThreadNameInternal (uint32 ThreadId)
Returns internal name of a the thread given its TLS id.
void HandleOnParentPreFork ()
Notification that the parent is about to fork.
void OnThreadListModified ()
Private Attributes
bool bIsThreadListDirty = false
FThreads Threads
List of thread objects to be ticked.
FCriticalSection ThreadsCritical
Critical section for ThreadList.
Friends
class FForkProcessHelper
Detailed Description
Manages runnables and runnable threads.
Definition at line 19 of file ThreadManager.h.
Member Typedef Documentation
FThreads
using FThreadManager::FThreads = TMap<uint32, FRunnableThread*, TInlineSetAllocator<256>> private
Definition at line 24 of file ThreadManager.h.
Constructor & Destructor Documentation
FThreadManager()
FThreadManager::FThreadManager ()
Referenced by Get().
~FThreadManager()
FThreadManager::~FThreadManager ()
Member Function Documentation
AddThread()
void FThreadManager::AddThread (uint32 ThreadId, FRunnableThread * Thread)
Used internally to add a new thread object.
Parameters
Thread thread object.
See also
RemoveThread
References Thread.
CheckThreadListSafeToContinueIteration()
bool FThreadManager::CheckThreadListSafeToContinueIteration () private
ForEachThread()
void FThreadManager::ForEachThread (TFunction< void(uint32 ThreadId, FRunnableThread *Thread)> Func)
Enumerate each thread.
References Thread.
ForEachThreadStackBackTrace()
void FThreadManager::ForEachThreadStackBackTrace (TFunctionRef< bool(uint32 ThreadId, const TCHAR *ThreadName, const TConstArrayView< uint64 > &StackTrace)> Func)
Get()
FThreadManager & FThreadManager::Get () static
Access to the singleton object.
Returns
Thread manager object.
References FThreadManager().
Referenced by GetThreadName().
GetAllThreadStackBackTraces()
void FThreadManager::GetAllThreadStackBackTraces (TArray< FThreadStackBackTrace > & StackTraces)
GetForkableThreads()
TArray< FRunnableThread * > FThreadManager::GetForkableThreads () private
Returns a list of registered forkable threads.
GetThreadName()
const FString & FThreadManager::GetThreadName (uint32 ThreadId) inline static
Returns the name of a thread given its TLS id.
Definition at line 62 of file ThreadManager.h.
References Get(), GetThreadNameInternal(), GGameThreadId, GRenderThreadId, PRAGMA_DISABLE_DEPRECATION_WARNINGS, PRAGMA_ENABLE_DEPRECATION_WARNINGS, and TEXT.
GetThreadNameInternal()
const FString & FThreadManager::GetThreadNameInternal (uint32 ThreadId) private
Returns internal name of a the thread given its TLS id.
Referenced by GetThreadName().
HandleOnParentPreFork()
void FThreadManager::HandleOnParentPreFork () private
Notification that the parent is about to fork.
NumThreads()
int32 FThreadManager::NumThreads () const inline
Get the number of registered threads.
Definition at line 56 of file ThreadManager.h.
References Threads.
OnThreadListModified()
void FThreadManager::OnThreadListModified () private
RemoveThread()
void FThreadManager::RemoveThread (FRunnableThread * Thread)
Used internally to remove thread object.
Parameters
Thread thread object to be removed.
See also
AddThread
References Thread.
Tick()
void FThreadManager::Tick ()
Ticks all fake threads and their runnable objects.
Friends And Related Symbol Documentation
FForkProcessHelper
friend class FForkProcessHelper friend
Definition at line 122 of file ThreadManager.h.
References FForkProcessHelper.
Referenced by FForkProcessHelper.
Field Documentation
bIsThreadListDirty
bool FThreadManager::bIsThreadListDirty = false private
Definition at line 29 of file ThreadManager.h.
Threads
FThreads FThreadManager::Threads private
List of thread objects to be ticked.
Definition at line 26 of file ThreadManager.h.
Referenced by NumThreads().
ThreadsCritical
FCriticalSection FThreadManager::ThreadsCritical private
Critical section for ThreadList.
Definition at line 22 of file ThreadManager.h.
The documentation for this class was generated from the following file:
Runtime/Core/Public/HAL/ThreadManager.h