Unreal Engine 5.6 C++ API: TMemoryView< DataType > Class Template Reference
TMemoryView< DataType > Class Template Reference
A non-owning view of a contiguous region of memory.
#include "MemoryView.h"
Public Member Functions
constexpr TMemoryView ()=default
Construct an empty view.
template<typename OtherDataType UE_REQUIRES>
constexpr TMemoryView (const TMemoryView< OtherDataType > &InView)
Construct a view of by copying a view with compatible const/volatile qualifiers.
template<typename DataEndType UE_REQUIRES>
TMemoryView (DataType *InData, DataEndType *InDataEnd)
Construct a view starting at InData and ending at InDataEnd.
constexpr TMemoryView (DataType *InData, uint64 InSize)
Construct a view of InSize bytes starting at InData.
template<typename OtherDataType>
int32 CompareBytes (const TMemoryView< OtherDataType > &InView) const
Returns whether the bytes of this view are equal or less/greater than the bytes of the other view.
template<typename OtherDataType>
bool Contains (const TMemoryView< OtherDataType > &InView) const
Returns whether this view fully contains the other view.
TMemoryView CopyFrom (FMemoryView InView) const
Copies bytes from the input view into this view, and returns the remainder of this view.
template<typename OtherDataType>
bool EqualBytes (const TMemoryView< OtherDataType > &InView) const
Returns whether the bytes of this views are equal to the bytes of the other view.
template<typename OtherDataType>
constexpr bool Equals (const TMemoryView< OtherDataType > &InView) const
Returns whether the data pointers and sizes of this view and the other view are equal.
constexpr DataType * GetData () const
Returns a pointer to the start of the view.
DataType * GetDataEnd () const
Returns a pointer to the end of the view.
constexpr uint64 GetSize () const
Returns the number of bytes in the view.
template<typename OtherDataType>
bool Intersects (const TMemoryView< OtherDataType > &InView) const
Returns whether this view intersects the other view.
constexpr bool IsEmpty () const
Returns whether the view has a size of 0 regardless of its data pointer.
constexpr TMemoryView Left (uint64 InSize) const
Returns the left-most part of the view by taking the given number of bytes from the left.
constexpr TMemoryView LeftChop (uint64 InSize) const
Returns the left-most part of the view by chopping the given number of bytes from the right.
constexpr void LeftChopInline (uint64 InSize)
Modifies the view by chopping the given number of bytes from the right.
constexpr void LeftInline (uint64 InSize)
Modifies the view to be the given number of bytes from the left.
TMemoryView Mid (uint64 InOffset, uint64 InSize=TNumericLimits< uint64 >::Max()) const
Returns the middle part of the view by taking up to the given number of bytes from the given position.
void MidInline (uint64 InOffset, uint64 InSize=TNumericLimits< uint64 >::Max())
Modifies the view to be the middle part by taking up to the given number of bytes from the given offset.
template<typename OtherDataType>
constexpr bool operator!= (const TMemoryView< OtherDataType > &InView) const
Returns whether the data pointers and sizes of this view and the other view are not equal.
constexpr TMemoryView & operator+= (uint64 InOffset)
Advances the start of the view by an offset, which is clamped to stay within the view.
template<typename OtherDataType>
constexpr bool operator== (const TMemoryView< OtherDataType > &InView) const
Returns whether the data pointers and sizes of this view and the other view are equal.
constexpr void Reset ()
Resets to an empty view.
TMemoryView Right (uint64 InSize) const
Returns the right-most part of the view by taking the given number of bytes from the right.
TMemoryView RightChop (uint64 InSize) const
Returns the right-most part of the view by chopping the given number of bytes from the left.
void RightChopInline (uint64 InSize)
Modifies the view by chopping the given number of bytes from the left.
void RightInline (uint64 InSize)
Modifies the view to be the given number of bytes from the right.
Private Types
using ByteType = std::conditional_t<TIsConst<DataType>::Value, const uint8, uint8>
Private Member Functions
DataType * GetDataAtOffsetNoCheck (uint64 InOffset) const
Returns the data pointer advanced by an offset in bytes.
Private Attributes
DataType * Data = nullptr
uint64 Size = 0
Friends
template<typename OtherDataType>
class TMemoryView
Detailed Description
template<typename DataType>
class TMemoryView< DataType >
A non-owning view of a contiguous region of memory.
Prefer to use the aliases FMemoryView or FMutableMemoryView over this type.
Functions that modify a view clamp sizes and offsets to always return a sub-view of the input.
Definition at line 28 of file MemoryView.h.
Member Typedef Documentation
ByteType
template<typename DataType> using TMemoryView< DataType >::ByteType = std::conditional_t<TIsConst<DataType>::Value, const uint8, uint8> private
Definition at line 32 of file MemoryView.h.
Constructor & Destructor Documentation
TMemoryView() [1/4]
template<typename DataType> TMemoryView< DataType >::TMemoryView () constexpr default
Construct an empty view.
TMemoryView() [2/4]
template<typename DataType> template<typename OtherDataType UE_REQUIRES> TMemoryView< DataType >::TMemoryView (const TMemoryView< OtherDataType > & InView) inline constexpr
Construct a view of by copying a view with compatible const/volatile qualifiers.
Definition at line 43 of file MemoryView.h.
TMemoryView() [3/4]
template<typename DataType> TMemoryView< DataType >::TMemoryView (DataType * InData, uint64 InSize) inline constexpr
Construct a view of InSize bytes starting at InData.
Definition at line 50 of file MemoryView.h.
TMemoryView() [4/4]
template<typename DataType> template<typename DataEndType UE_REQUIRES> TMemoryView< DataType >::TMemoryView (DataType * InData, DataEndType * InDataEnd) inline
Construct a view starting at InData and ending at InDataEnd.
Definition at line 61 of file MemoryView.h.
Member Function Documentation
CompareBytes()
template<typename DataType> template<typename OtherDataType> int32 TMemoryView< DataType >::CompareBytes (const TMemoryView< OtherDataType > & InView) const inline nodiscard
Returns whether the bytes of this view are equal or less/greater than the bytes of the other view.
Definition at line 174 of file MemoryView.h.
Referenced by UE::Cook::FCookDependency::operator<(), and UE::Cook::FCookDependency::operator==().
Contains()
template<typename DataType> template<typename OtherDataType> bool TMemoryView< DataType >::Contains (const TMemoryView< OtherDataType > & InView) const inline nodiscard
Returns whether this view fully contains the other view.
Definition at line 160 of file MemoryView.h.
Referenced by TCbBuffer< ViewType >::TCbBuffer(), and TCbBuffer< ViewType >::TCbBuffer().
CopyFrom()
template<typename DataType> TMemoryView TMemoryView< DataType >::CopyFrom (FMemoryView InView) const inline
Copies bytes from the input view into this view, and returns the remainder of this view.
Definition at line 216 of file MemoryView.h.
Referenced by UE::FPlatformIoDispatcherBase::ProcessCompletedFileBlock(), UE::FPlatformIoDispatcherBase::ScatterDecodedBlock(), and FMemoryReaderView::Serialize().
EqualBytes()
template<typename DataType> template<typename OtherDataType> bool TMemoryView< DataType >::EqualBytes (const TMemoryView< OtherDataType > & InView) const inline nodiscard
Returns whether the bytes of this views are equal to the bytes of the other view.
Definition at line 182 of file MemoryView.h.
Equals()
template<typename DataType> template<typename OtherDataType> bool TMemoryView< DataType >::Equals (const TMemoryView< OtherDataType > & InView) const inline nodiscard constexpr
Returns whether the data pointers and sizes of this view and the other view are equal.
Definition at line 189 of file MemoryView.h.
Referenced by TMemoryView< const void >::operator!=(), and TMemoryView< const void >::operator==().
GetData()
template<typename DataType> DataType * TMemoryView< DataType >::GetData () const inline nodiscard constexpr
Returns a pointer to the start of the view.
Definition at line 68 of file MemoryView.h.
Referenced by TraceServices::TCachedPagedArray< InItemType, PageSize >::TCachedPagedArray(), TraceServices::TCachedStringStore< WIDECHAR >::TCachedStringStore(), FBuzHash::Add(), FBlake3Hash::FromView(), FIoHash::FromView(), FCbFieldViewIterator::MakeRange(), UE::FPlatformIoDispatcherBase::ProcessCompletedFileBlock(), FIoChunkId::Set(), and TCbFieldIterator< FieldType >::TryGetRangeView().
GetDataAtOffsetNoCheck()
template<typename DataType> DataType * TMemoryView< DataType >::GetDataAtOffsetNoCheck (uint64 InOffset) const inline nodiscard private
Returns the data pointer advanced by an offset in bytes.
Definition at line 229 of file MemoryView.h.
Referenced by TMemoryView< const void >::Contains(), TMemoryView< const void >::GetDataEnd(), TMemoryView< const void >::Intersects(), TMemoryView< const void >::RightChopInline(), and TMemoryView< const void >::RightInline().
GetDataEnd()
template<typename DataType> DataType * TMemoryView< DataType >::GetDataEnd () const inline nodiscard
Returns a pointer to the end of the view.
Definition at line 71 of file MemoryView.h.
Referenced by FCbFieldViewIterator::MakeRange().
GetSize()
template<typename DataType> uint64 TMemoryView< DataType >::GetSize () const inline nodiscard constexpr
Returns the number of bytes in the view.
Definition at line 74 of file MemoryView.h.
Referenced by TraceServices::TCachedPagedArray< InItemType, PageSize >::TCachedPagedArray(), TraceServices::TCachedStringStore< WIDECHAR >::TCachedStringStore(), FBuzHash::Add(), FBlake3Hash::FromView(), FIoHash::FromView(), UE::FPlatformIoDispatcherBase::ProcessCompletedFileBlock(), and FIoChunkId::Set().
Intersects()
template<typename DataType> template<typename OtherDataType> bool TMemoryView< DataType >::Intersects (const TMemoryView< OtherDataType > & InView) const inline nodiscard
Returns whether this view intersects the other view.
Definition at line 167 of file MemoryView.h.
IsEmpty()
template<typename DataType> bool TMemoryView< DataType >::IsEmpty () const inline nodiscard constexpr
Returns whether the view has a size of 0 regardless of its data pointer.
Definition at line 77 of file MemoryView.h.
Referenced by FCbFieldViewIterator::MakeRange().
Left()
template<typename DataType> TMemoryView TMemoryView< DataType >::Left (uint64 InSize) const inline nodiscard constexpr
Returns the left-most part of the view by taking the given number of bytes from the left.
Definition at line 83 of file MemoryView.h.
Referenced by FShaderCodeResource::Unpack().
LeftChop()
template<typename DataType> TMemoryView TMemoryView< DataType >::LeftChop (uint64 InSize) const inline nodiscard constexpr
Returns the left-most part of the view by chopping the given number of bytes from the right.
Definition at line 91 of file MemoryView.h.
LeftChopInline()
template<typename DataType> void TMemoryView< DataType >::LeftChopInline (uint64 InSize) inline constexpr
Modifies the view by chopping the given number of bytes from the right.
Definition at line 129 of file MemoryView.h.
Referenced by TMemoryView< const void >::LeftChop().
LeftInline()
template<typename DataType> void TMemoryView< DataType >::LeftInline (uint64 InSize) inline constexpr
Modifies the view to be the given number of bytes from the left.
Definition at line 123 of file MemoryView.h.
Referenced by TMemoryView< const void >::Left(), TMemoryView< const void >::MidInline(), and UE::FPlatformIoDispatcherBase::ProcessCompletedFileBlock().
Mid()
template<typename DataType> TMemoryView TMemoryView< DataType >::Mid (uint64 InOffset, uint64 InSize = TNumericLimits<uint64>::Max()) const inline nodiscard
Returns the middle part of the view by taking up to the given number of bytes from the given position.
Definition at line 115 of file MemoryView.h.
Referenced by UE::FPlatformIoDispatcherBase::ProcessCompletedFileBlock(), and UE::FPlatformIoDispatcherBase::ScatterDecodedBlock().
MidInline()
template<typename DataType> void TMemoryView< DataType >::MidInline (uint64 InOffset, uint64 InSize = TNumericLimits<uint64>::Max()) inline
Modifies the view to be the middle part by taking up to the given number of bytes from the given offset.
Definition at line 152 of file MemoryView.h.
Referenced by TMemoryView< const void >::Mid(), and UE::FPlatformIoDispatcherBase::ProcessCompletedFileBlock().
operator!=()
template<typename DataType> template<typename OtherDataType> bool TMemoryView< DataType >::operator!= (const TMemoryView< OtherDataType > & InView) const inline nodiscard constexpr
Returns whether the data pointers and sizes of this view and the other view are not equal.
Definition at line 203 of file MemoryView.h.
operator+=()
template<typename DataType> TMemoryView & TMemoryView< DataType >::operator+= (uint64 InOffset) inline constexpr
Advances the start of the view by an offset, which is clamped to stay within the view.
Definition at line 209 of file MemoryView.h.
operator==()
template<typename DataType> template<typename OtherDataType> bool TMemoryView< DataType >::operator== (const TMemoryView< OtherDataType > & InView) const inline nodiscard constexpr
Returns whether the data pointers and sizes of this view and the other view are equal.
Definition at line 196 of file MemoryView.h.
Reset()
template<typename DataType> void TMemoryView< DataType >::Reset () inline constexpr
Resets to an empty view.
Definition at line 80 of file MemoryView.h.
Right()
template<typename DataType> TMemoryView TMemoryView< DataType >::Right (uint64 InSize) const inline nodiscard
Returns the right-most part of the view by taking the given number of bytes from the right.
Definition at line 99 of file MemoryView.h.
RightChop()
template<typename DataType> TMemoryView TMemoryView< DataType >::RightChop (uint64 InSize) const inline nodiscard
Returns the right-most part of the view by chopping the given number of bytes from the left.
Definition at line 107 of file MemoryView.h.
Referenced by UE::FPlatformIoDispatcherBase::ScatterDecodedBlock(), and FShaderCodeResource::Unpack().
RightChopInline()
template<typename DataType> void TMemoryView< DataType >::RightChopInline (uint64 InSize) inline
Modifies the view by chopping the given number of bytes from the left.
Definition at line 144 of file MemoryView.h.
Referenced by TMemoryView< const void >::MidInline(), TMemoryView< const void >::operator+=(), UE::FPlatformIoDispatcherBase::ProcessCompletedFileBlock(), and TMemoryView< const void >::RightChop().
RightInline()
template<typename DataType> void TMemoryView< DataType >::RightInline (uint64 InSize) inline
Modifies the view to be the given number of bytes from the right.
Definition at line 135 of file MemoryView.h.
Referenced by TMemoryView< const void >::Right().
Friends And Related Symbol Documentation
TMemoryView
template<typename DataType> template<typename OtherDataType> friend class TMemoryView friend
Definition at line 235 of file MemoryView.h.
Referenced by MakeMemoryView(), MakeMemoryView(), operator+(), operator+(), and TMemoryView< const void >::Reset().
Field Documentation
Data
template<typename DataType> DataType* TMemoryView< DataType >::Data = nullptr private
Definition at line 238 of file MemoryView.h.
Referenced by TMemoryView< const void >::CompareBytes(), TMemoryView< const void >::Contains(), TMemoryView< const void >::CopyFrom(), TMemoryView< const void >::EqualBytes(), TMemoryView< const void >::Equals(), TMemoryView< const void >::Intersects(), MakeMemoryView(), MakeMemoryView(), and MakeMemoryView().
Size
template<typename DataType> uint64 TMemoryView< DataType >::Size = 0 private
Definition at line 239 of file MemoryView.h.
Referenced by TMemoryView< const void >::CompareBytes(), TMemoryView< const void >::Contains(), TMemoryView< const void >::CopyFrom(), TMemoryView< const void >::EqualBytes(), TMemoryView< const void >::Equals(), and TMemoryView< const void >::Intersects().
The documentation for this class was generated from the following files:
Runtime/Core/Public/Memory/MemoryFwd.h
Runtime/Core/Public/Memory/MemoryView.h