Unreal Engine 5.6 C++ API: IPrimitiveComponent Class Reference
IPrimitiveComponent Class Reference abstract
#include "ComponentInterfaces.h"
Public Member Functions
virtual HHitProxy * CreateMeshHitProxy (int32 SectionIndex, int32 MaterialIndex)=0
virtual HHitProxy * CreatePrimitiveHitProxies (TArray< TRefCountPtr< HHitProxy > > &OutHitProxies)=0
virtual void CreateRenderState (FRegisterComponentContext *Context)=0
virtual FPrimitiveSceneProxy * CreateSceneProxy ()=0
virtual void DestroyRenderState ()=0
virtual FBoxSphereBounds GetBounds () const =0
virtual FString GetFullName () const =0
virtual float GetLastRenderTimeOnScreen () const =0
virtual FString GetName () const =0
template<class T>
T * GetOwner ()
virtual UObject * GetOwner () const =0
virtual FString GetOwnerName () const =0
virtual void GetPrimitiveStats (FPrimitiveStats &PrimitiveStats) const =0
virtual FSceneInterface * GetScene () const =0
virtual FPrimitiveSceneProxy * GetSceneProxy () const =0
virtual void GetStreamableRenderAssetInfo (TArray< struct FStreamingRenderAssetPrimitiveInfo > &StreamableRenderAssets) const =0
virtual FTransform GetTransform () const =0
template<class T>
T * GetUObject ()
template<class T>
const T * GetUObject () const
virtual const UObject * GetUObject () const =0
virtual UObject * GetUObject ()=0
virtual void GetUsedMaterials (TArray< UMaterialInterface * > &OutMaterials, bool bGetDebugMaterials=false) const =0
virtual UWorld * GetWorld () const =0
virtual bool IsRegistered () const =0
virtual bool IsRenderStateCreated () const =0
virtual bool IsRenderStateDirty () const =0
virtual bool IsUnreachable () const =0
virtual void MarkRenderStateDirty ()=0
virtual void PrecachePSOs ()=0
virtual bool ShouldCreateRenderState () const =0
Static Public Member Functions
static void AddImplementer (const FComponentInterfaceImplementation &Implementer)
static void RemoveImplementer (const UClass *ImplementerClass)
Static Protected Attributes
static TArray< FComponentInterfaceImplementation > Implementers
Friends
template<class T>
class TComponentInterfaceIterator
Detailed Description
Definition at line 58 of file ComponentInterfaces.h.
Member Function Documentation
AddImplementer()
void IPrimitiveComponent::AddImplementer (const FComponentInterfaceImplementation & Implementer) static
CreateMeshHitProxy()
virtual HHitProxy * IPrimitiveComponent::CreateMeshHitProxy (int32 SectionIndex, int32 MaterialIndex) pure virtual
Implemented in FActorPrimitiveComponentInterface.
CreatePrimitiveHitProxies()
virtual HHitProxy * IPrimitiveComponent::CreatePrimitiveHitProxies (TArray< TRefCountPtr< HHitProxy > > & OutHitProxies) pure virtual
Implemented in FActorPrimitiveComponentInterface.
CreateRenderState()
virtual void IPrimitiveComponent::CreateRenderState (FRegisterComponentContext * Context) pure virtual
Implemented in FActorPrimitiveComponentInterface.
CreateSceneProxy()
virtual FPrimitiveSceneProxy * IPrimitiveComponent::CreateSceneProxy () pure virtual
Implemented in FActorPrimitiveComponentInterface.
DestroyRenderState()
virtual void IPrimitiveComponent::DestroyRenderState () pure virtual
Implemented in FActorPrimitiveComponentInterface.
Referenced by FComponentRecreateRenderStateContext::FComponentRecreateRenderStateContext().
GetBounds()
virtual FBoxSphereBounds IPrimitiveComponent::GetBounds () const pure virtual
Implemented in FActorPrimitiveComponentInterface.
GetFullName()
virtual FString IPrimitiveComponent::GetFullName () const pure virtual
Implemented in FActorPrimitiveComponentInterface.
Referenced by FComponentRecreateRenderStateContext::FComponentRecreateRenderStateContext().
GetLastRenderTimeOnScreen()
virtual float IPrimitiveComponent::GetLastRenderTimeOnScreen () const pure virtual
Implemented in FActorPrimitiveComponentInterface.
GetName()
virtual FString IPrimitiveComponent::GetName () const pure virtual
Implemented in FActorPrimitiveComponentInterface.
GetOwner() [1/2]
template<class T> T * IPrimitiveComponent::GetOwner () inline
Definition at line 94 of file ComponentInterfaces.h.
References Cast(), and GetOwner().
Referenced by GetOwner().
GetOwner() [2/2]
virtual UObject * IPrimitiveComponent::GetOwner () const pure virtual
Implemented in FActorPrimitiveComponentInterface.
GetOwnerName()
virtual FString IPrimitiveComponent::GetOwnerName () const pure virtual
Implemented in FActorPrimitiveComponentInterface.
GetPrimitiveStats()
virtual void IPrimitiveComponent::GetPrimitiveStats (FPrimitiveStats & PrimitiveStats) const pure virtual
Implemented in FActorPrimitiveComponentInterface.
GetScene()
virtual FSceneInterface * IPrimitiveComponent::GetScene () const pure virtual
Implemented in FActorPrimitiveComponentInterface.
GetSceneProxy()
virtual FPrimitiveSceneProxy * IPrimitiveComponent::GetSceneProxy () const pure virtual
Implemented in FActorPrimitiveComponentInterface.
GetStreamableRenderAssetInfo()
virtual void IPrimitiveComponent::GetStreamableRenderAssetInfo (TArray< struct FStreamingRenderAssetPrimitiveInfo > & StreamableRenderAssets) const pure virtual
Implemented in FActorPrimitiveComponentInterface.
GetTransform()
virtual FTransform IPrimitiveComponent::GetTransform () const pure virtual
Implemented in FActorPrimitiveComponentInterface.
GetUObject() [1/4]
template<class T> T * IPrimitiveComponent::GetUObject () inline
Definition at line 88 of file ComponentInterfaces.h.
References Cast(), and GetUObject().
Referenced by GetUObject().
GetUObject() [2/4]
template<class T> const T * IPrimitiveComponent::GetUObject () const inline
Definition at line 85 of file ComponentInterfaces.h.
References Cast(), and GetUObject().
Referenced by GetUObject().
GetUObject() [3/4]
virtual const UObject * IPrimitiveComponent::GetUObject () const pure virtual
Implemented in FActorPrimitiveComponentInterface.
GetUObject() [4/4]
virtual UObject * IPrimitiveComponent::GetUObject () pure virtual
Implemented in FActorPrimitiveComponentInterface.
GetUsedMaterials()
virtual void IPrimitiveComponent::GetUsedMaterials (TArray< UMaterialInterface * > & OutMaterials, bool bGetDebugMaterials = false) const pure virtual
Implemented in FActorPrimitiveComponentInterface.
GetWorld()
virtual UWorld * IPrimitiveComponent::GetWorld () const pure virtual
Implemented in FActorPrimitiveComponentInterface.
IsRegistered()
virtual bool IPrimitiveComponent::IsRegistered () const pure virtual
Implemented in FActorPrimitiveComponentInterface.
Referenced by FComponentRecreateRenderStateContext::FComponentRecreateRenderStateContext().
IsRenderStateCreated()
virtual bool IPrimitiveComponent::IsRenderStateCreated () const pure virtual
Implemented in FActorPrimitiveComponentInterface.
Referenced by FComponentRecreateRenderStateContext::FComponentRecreateRenderStateContext().
IsRenderStateDirty()
virtual bool IPrimitiveComponent::IsRenderStateDirty () const pure virtual
Implemented in FActorPrimitiveComponentInterface.
IsUnreachable()
virtual bool IPrimitiveComponent::IsUnreachable () const pure virtual
Implemented in FActorPrimitiveComponentInterface.
Referenced by FComponentRecreateRenderStateContext::FComponentRecreateRenderStateContext().
MarkRenderStateDirty()
virtual void IPrimitiveComponent::MarkRenderStateDirty () pure virtual
Implemented in FActorPrimitiveComponentInterface.
PrecachePSOs()
virtual void IPrimitiveComponent::PrecachePSOs () pure virtual
Implemented in FActorPrimitiveComponentInterface.
RemoveImplementer()
void IPrimitiveComponent::RemoveImplementer (const UClass * ImplementerClass) static
ShouldCreateRenderState()
virtual bool IPrimitiveComponent::ShouldCreateRenderState () const pure virtual
Implemented in FActorPrimitiveComponentInterface.
Friends And Related Symbol Documentation
TComponentInterfaceIterator
template<class T> friend class TComponentInterfaceIterator friend
Definition at line 109 of file ComponentInterfaces.h.
References TComponentInterfaceIterator.
Referenced by TComponentInterfaceIterator.
Field Documentation
Implementers
TArray<FComponentInterfaceImplementation> IPrimitiveComponent::Implementers static protected
Definition at line 111 of file ComponentInterfaces.h.
The documentation for this class was generated from the following file:
Runtime/Engine/Classes/Components/ComponentInterfaces.h