Unreal Engine 5.6 C++ API: TEasingAttributeInterpolator< NumericType > Class Template Reference
TEasingAttributeInterpolator< NumericType > Class Template Reference
An easing attribute interpolator.
#include "AttributeInterpolator.h"
Data Structures
struct FSettings
Public Member Functions
TEasingAttributeInterpolator (const FSettings &InSettings)
virtual bool IdenticalTo (const TAttributeInterpolator< NumericType > *InOther) const override
Compares this interpolator to another one.
virtual bool IsTypeOf (EAttributeInterpolatorType InType) const override
Returns true if the interpolator is of a given type.
Public Member Functions inherited from TAttributeInterpolator< NumericType >
TAttributeInterpolator ()
virtual ~TAttributeInterpolator ()
DECLARE_MULTICAST_DELEGATE_OneParam (FInterpolatorEvent, TOptional< NumericType >)
bool Equals (const double &InA, const double &InB, double InTolerance)
bool Equals (const float &InA, const float &InB, double InTolerance)
const NumericType & Get () const
Returns the interpolated value.
double GetOverAllDeltaTime () const
Returns the delta time between the start of the animation and now.
bool IsEnabled () const
bool IsSet () const
Returns true if this interpolator's value has even been set.
FInterpolatorEvent & OnInterpolationStarted ()
FInterpolatorEvent & OnInterpolationStopped ()
void Reset () const
Resets the interpolator.
void SetDelayOneShot (float InDelay) const
Sets the delay for the next shot - delays are consumed and only used once.
void SetEnabled (bool InEnabled=true)
void SetTolerance (float InTolerance)
Sets the tolerance on this interpolator.
void SetValue (const NumericType &InValue) const
Set the internal state of the interpolator.
void SetValueAndStop (const NumericType &InValue) const
Set the internal state of the interpolator and disables animation.
void Tick (float InDeltaTime)
Updates the interpolator.
Protected Member Functions
virtual void Interpolate () const override
Protected Member Functions inherited from TAttributeInterpolator< NumericType >
bool IsPlaying () const
virtual bool PlayIfStopped () const
virtual bool Restart () const
virtual bool Start () const
virtual bool Stop () const
Protected Attributes
FSettings Settings
Protected Attributes inherited from TAttributeInterpolator< NumericType >
bool bEnabled
TOptional< float > Delay
TOptional< NumericType > DesiredValue
TOptional< NumericType > InterpolatedValue
FInterpolatorEvent InterpolationStarted
FInterpolatorEvent InterpolationStopped
TOptional< NumericType > LastValue
TOptional< float > OverallDeltaTime
float Tolerance
Private Types
typedef TAttributeInterpolator< NumericType > Super
Additional Inherited Members
Static Public Member Functions inherited from TAttributeInterpolator< NumericType >
static bool Equals (const NumericType &InA, const NumericType &InB, double InTolerance=0.001)
Helper function to compare to values - to allow to specialize per type as needed.
Detailed Description
template<typename NumericType>
class TEasingAttributeInterpolator< NumericType >
An easing attribute interpolator.
This interpolator is to implement default easing functions such as Cubic etc probably to rely on FCurveSequence.
Definition at line 382 of file AttributeInterpolator.h.
Member Typedef Documentation
Super
template<typename NumericType> typedef TAttributeInterpolator<NumericType> TEasingAttributeInterpolator< NumericType >::Super private
Definition at line 386 of file AttributeInterpolator.h.
Constructor & Destructor Documentation
TEasingAttributeInterpolator()
template<typename NumericType> TEasingAttributeInterpolator< NumericType >::TEasingAttributeInterpolator (const FSettings & InSettings) inline explicit
Definition at line 404 of file AttributeInterpolator.h.
References Settings.
Referenced by IdenticalTo().
Member Function Documentation
IdenticalTo()
template<typename NumericType> virtual bool TEasingAttributeInterpolator< NumericType >::IdenticalTo (const TAttributeInterpolator< NumericType > * InOther) const inline override virtual
Compares this interpolator to another one.
Parameters
InOther The interpolator to compare this one to
Returns
True if the this interpolator is considered identical to the passed one
Implements TAttributeInterpolator< NumericType >.
Definition at line 418 of file AttributeInterpolator.h.
References TAttributeInterpolator< NumericType >::TAttributeInterpolator(), TEasingAttributeInterpolator(), TEasingAttributeInterpolator< NumericType >::FSettings::Duration, Easing, FMath::IsNearlyEqual(), TAttributeInterpolator< NumericType >::IsTypeOf(), and Settings.
Interpolate()
template<typename NumericType> virtual void TEasingAttributeInterpolator< NumericType >::Interpolate () const inline override protected virtual
Implements TAttributeInterpolator< NumericType >.
Definition at line 434 of file AttributeInterpolator.h.
References check, FMath::Clamp(), DeltaTime, TAttributeInterpolator< NumericType >::DesiredValue, EaseInterpolatorRatio(), float, TAttributeInterpolator< NumericType >::GetOverAllDeltaTime(), TAttributeInterpolator< NumericType >::InterpolatedValue, TAttributeInterpolator< NumericType >::IsSet(), TAttributeInterpolator< NumericType >::LastValue, FMath::Lerp(), Settings, and TAttributeInterpolator< NumericType >::SetValueAndStop().
IsTypeOf()
template<typename NumericType> virtual bool TEasingAttributeInterpolator< NumericType >::IsTypeOf (EAttributeInterpolatorType InType) const inline override virtual
Returns true if the interpolator is of a given type.
Parameters
InType The type to compare agains
Returns
True if the interpolator matches the type
Implements TAttributeInterpolator< NumericType >.
Definition at line 413 of file AttributeInterpolator.h.
References Easing.
Field Documentation
Settings
template<typename NumericType> FSettings TEasingAttributeInterpolator< NumericType >::Settings protected
Definition at line 451 of file AttributeInterpolator.h.
Referenced by TEasingAttributeInterpolator(), IdenticalTo(), and Interpolate().
The documentation for this class was generated from the following file:
Runtime/Slate/Public/Framework/Animation/AttributeInterpolator.h