Unreal Engine 5.6 C++ API: FLandscapePhysicalMaterialRenderTask Class Reference
FLandscapePhysicalMaterialRenderTask Class Reference
A single task for calculating the landscape physical material.
#include "LandscapePhysicalMaterial.h"
Public Member Functions
FLandscapePhysicalMaterialRenderTask ()
~FLandscapePhysicalMaterialRenderTask ()
void Flush ()
Flush a task to completion.
uint32 GetHash () const
TArray< uint8 > const & GetResultIds () const
Get the result data.
TArray< class UPhysicalMaterial * > const & GetResultMaterials () const
Get the result data.
bool Init (class ULandscapeComponent const *LandscapeComponent, uint32 InHash)
Initialize the task for a component.
bool IsComplete () const
Returns true if the task is complete and the result is available.
bool IsInProgress () const
Is this Task in progress (valid and incomplete)
bool IsValid () const
Returns true if Init() has been called without a Release().
void Release ()
Release the task.
void Tick ()
Update a task.
Private Member Functions
FLandscapePhysicalMaterialRenderTask (FLandscapePhysicalMaterialRenderTask const &)
void UpdateInternal (bool bInFlush)
Private Attributes
uint32 Hash = 0
int32 PoolHandle = -1
Friends
class FLandscapePhysicalMaterialRenderTaskPool
Detailed Description
A single task for calculating the landscape physical material.
The work uses the GPU so this object handles reading back the data without stalling. We need to call Tick() until IsComplete() returns true. We need to call Release() after use to prevent leaking of internal objects. All calls are expected to be made on the game thread only.
Definition at line 16 of file LandscapePhysicalMaterial.h.
Constructor & Destructor Documentation
FLandscapePhysicalMaterialRenderTask() [1/2]
FLandscapePhysicalMaterialRenderTask::FLandscapePhysicalMaterialRenderTask () inline
Definition at line 19 of file LandscapePhysicalMaterial.h.
Referenced by FLandscapePhysicalMaterialRenderTask().
~FLandscapePhysicalMaterialRenderTask()
FLandscapePhysicalMaterialRenderTask::~FLandscapePhysicalMaterialRenderTask () inline
Definition at line 22 of file LandscapePhysicalMaterial.h.
References Release().
FLandscapePhysicalMaterialRenderTask() [2/2]
FLandscapePhysicalMaterialRenderTask::FLandscapePhysicalMaterialRenderTask (FLandscapePhysicalMaterialRenderTask const &) private
References FLandscapePhysicalMaterialRenderTask().
Member Function Documentation
Flush()
void FLandscapePhysicalMaterialRenderTask::Flush ()
Flush a task to completion.
This may stall waiting for completion.
GetHash()
uint32 FLandscapePhysicalMaterialRenderTask::GetHash () const inline
Definition at line 50 of file LandscapePhysicalMaterial.h.
References Hash.
GetResultIds()
TArray< uint8 > const & FLandscapePhysicalMaterialRenderTask::GetResultIds () const
Get the result data.
Assumes that IsComplete() is true. This doesn't Release() the data.
GetResultMaterials()
TArray< class UPhysicalMaterial * > const & FLandscapePhysicalMaterialRenderTask::GetResultMaterials () const
Get the result data.
Assumes that IsComplete() is true. This doesn't Release() the data.
Init()
bool FLandscapePhysicalMaterialRenderTask::Init (class ULandscapeComponent const * LandscapeComponent, uint32 InHash)
Initialize the task for a component.
A task in progress can safely call Init() again to rekick the task. Returns false if no physical material needs to be rendered.
IsComplete()
bool FLandscapePhysicalMaterialRenderTask::IsComplete () const
Returns true if the task is complete and the result is available.
IsInProgress()
bool FLandscapePhysicalMaterialRenderTask::IsInProgress () const
Is this Task in progress (valid and incomplete)
IsValid()
bool FLandscapePhysicalMaterialRenderTask::IsValid () const
Returns true if Init() has been called without a Release().
Release()
void FLandscapePhysicalMaterialRenderTask::Release ()
Release the task.
After calling this IsValid() will return false until we call Init() again.
Referenced by ~FLandscapePhysicalMaterialRenderTask().
Tick()
void FLandscapePhysicalMaterialRenderTask::Tick ()
Update a task.
Does nothing if the task is complete.
UpdateInternal()
void FLandscapePhysicalMaterialRenderTask::UpdateInternal (bool bInFlush) private
Friends And Related Symbol Documentation
FLandscapePhysicalMaterialRenderTaskPool
friend class FLandscapePhysicalMaterialRenderTaskPool friend
Definition at line 57 of file LandscapePhysicalMaterial.h.
References FLandscapePhysicalMaterialRenderTaskPool.
Referenced by FLandscapePhysicalMaterialRenderTaskPool.
Field Documentation
Hash
uint32 FLandscapePhysicalMaterialRenderTask::Hash = 0 private
Definition at line 60 of file LandscapePhysicalMaterial.h.
Referenced by GetHash().
PoolHandle
int32 FLandscapePhysicalMaterialRenderTask::PoolHandle = -1 private
Definition at line 55 of file LandscapePhysicalMaterial.h.
The documentation for this class was generated from the following file:
Runtime/Landscape/Classes/LandscapePhysicalMaterial.h