Unreal Engine 5.6 C++ API: TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize > Class Template Reference
TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize > Class Template Reference
#include "MallocBinnedCommon.h"
Data Structures
struct FPerThreadFreeBlockLists
struct FPoolHashBucket
Hash table struct for retrieving allocation book keeping information.
struct Internal
Public Member Functions
virtual void GetAllocatorStats (FGenericMemoryStats &OutStats) override
Writes allocator stats from the last update into the specified destination.
Public Member Functions inherited from FMalloc
virtual void DumpAllocatorStats (class FOutputDevice &Ar)
Dumps current allocator stats to the log.
virtual void Free (void *Original)=0
Free.
virtual bool GetAllocationSize (void *Original, SIZE_T &SizeOut)
If possible determine the size of the memory allocated at the given address.
virtual const TCHAR * GetDescriptiveName ()
Gets descriptive name for logging purposes.
virtual uint64 GetImmediatelyFreeableCachedMemorySize () const
Returns the amount of free memory cached by the allocator that can be returned to the system in case of a memory shortage.
virtual uint64 GetTotalFreeCachedMemorySize () const
Returns the amount of total free memory cached by the allocator.
virtual void InitializeStatsMetadata ()
Initializes stats metadata.
virtual bool IsInternallyThreadSafe () const
Returns if the allocator is guaranteed to be thread-safe and therefore doesn't need a unnecessary thread-safety wrapper around it.
virtual void * Malloc (SIZE_T Count, uint32 Alignment=DEFAULT_ALIGNMENT)=0
Malloc.
virtual void * MallocZeroed (SIZE_T Count, uint32 Alignment=DEFAULT_ALIGNMENT)
Malloc zeroed memory.
virtual void OnMallocInitialized ()
Notifies the malloc implementation that initialization of all allocators in GMalloc is complete, so it's safe to initialize any extra features that require "regular" allocations.
virtual void OnPostFork ()
Notifies the malloc implementation that the process has forked so we can try and avoid dirtying pre-fork pages.
virtual void OnPreFork ()
Notifies the malloc implementation that the process is about to fork.
virtual SIZE_T QuantizeSize (SIZE_T Count, uint32 Alignment)
For some allocators this will return the actual size that should be requested to eliminate internal fragmentation.
virtual void * Realloc (void *Original, SIZE_T Count, uint32 Alignment=DEFAULT_ALIGNMENT)=0
Realloc.
virtual void Trim (bool bTrimThreadCaches)
Releases as much memory as possible.
virtual void * TryMalloc (SIZE_T Count, uint32 Alignment=DEFAULT_ALIGNMENT)
TryMalloc - like Malloc(), but may return a nullptr result if the allocation request cannot be satisfied.
virtual void * TryMallocZeroed (SIZE_T Count, uint32 Alignment=DEFAULT_ALIGNMENT)
TryMalloc - like MallocZeroed(), but may return a nullptr result if the allocation request cannot be satisfied.
virtual void * TryRealloc (void *Original, SIZE_T Count, uint32 Alignment=DEFAULT_ALIGNMENT)
TryRealloc - like Realloc(), but may return a nullptr if the allocation request cannot be satisfied.
virtual void UpdateStats ()
Called once per frame, gathers and sets all memory allocator statistics into the corresponding stats.
virtual bool ValidateHeap ()
Validates the allocator's heap.
Public Member Functions inherited from FUseSystemMallocForNew
void operator delete (void *Ptr)
Overloaded delete operator using the system allocator.
void operator delete[] (void *Ptr)
Overloaded array delete operator using the system allocator.
void * operator new (size_t Size)
Overloaded new operator using the system allocator.
void * operator new[] (size_t Size)
Overloaded array new operator using the system allocator.
Public Member Functions inherited from FExec
virtual ~FExec ()
virtual bool Exec (UWorld *InWorld, const TCHAR *Cmd, FOutputDevice &Ar)
Exec handler.
Protected Member Functions
void AllocateHashBuckets ()
FORCEINLINE uint32 BoundSizeToPoolIndex (SIZE_T Size, const uint8(&MemSizeToPoolIndex)[1+(MAX_SMALL_POOL_SIZE > > 4)]) const
virtual void ClearAndDisableTLSCachesOnCurrentThread () override
Clears the TLS caches on the current thread and disables any future caching.
bool GetAllocationSizeExternal (void *Ptr, SIZE_T &SizeOut)
int64 GetTotalAllocatedSmallPoolMemory () const
virtual void MarkTLSCachesAsUnusedOnCurrentThread () override
Mark TLS caches for current thread as unused.
virtual void MarkTLSCachesAsUsedOnCurrentThread () override
Mark TLS caches for the current thread as used.
bool PromoteToLargerBin (SIZE_T &Size, uint32 &Alignment, const AllocType &Alloc) const
FORCEINLINE SIZE_T QuantizeSizeCommon (SIZE_T Count, uint32 Alignment, const AllocType &Alloc) const
virtual void SetupTLSCachesOnCurrentThread () override
Set up TLS caches on the current thread.
void UpdateStatsCommon (const AllocType &Alloc)
Protected Member Functions inherited from FMallocBinnedCommonBase
void GetAllocatorStatsInternal (FGenericMemoryStats &OutStats, int64 TotalAllocatedSmallPoolMemory)
Protected Member Functions inherited from FExec
virtual bool Exec_Dev (UWorld *InWorld, const TCHAR *Cmd, FOutputDevice &Ar)
Implementation of Exec that is only called in non-shipping targets.
virtual bool Exec_Editor (UWorld *InWorld, const TCHAR *Cmd, FOutputDevice &Ar)
Implementation of Exec that is only called in editor.
virtual bool Exec_Runtime (UWorld *InWorld, const TCHAR *Cmd, FOutputDevice &Ar)
Implementation of Exec that is called on all targets where UE_ALLOW_EXEC_COMMANDS is true.
Static Protected Member Functions
static UE::FPlatformRecursiveMutex & GetFreeBlockListsRegistrationMutex ()
static TArray< FPerThreadFreeBlockLists * > & GetRegisteredFreeBlockLists ()
Static Protected Member Functions inherited from FMallocBinnedCommonBase
static CA_NO_RETURN void OutOfMemory (uint64 Size, uint32 Alignment=0)
Static Private Member Functions
static void RegisterThreadFreeBlockLists (FPerThreadFreeBlockLists *FreeBlockLists)
static void UnregisterThreadFreeBlockLists (FPerThreadFreeBlockLists *FreeBlockLists)
Private Attributes
FPoolHashBucket * HashBucketFreeList = nullptr
FPoolHashBucket * HashBuckets = nullptr
Static Private Attributes
static constexpr int MAX_SMALL_POOL_SIZE = MaxSmallPoolSize
static constexpr int NUM_SMALL_POOLS = NumSmallPools
Friends
class FMallocBinnedCommonUtils
Additional Inherited Members
Static Public Attributes inherited from FMalloc
static TAtomic< uint64 > MaxSingleAlloc
Limits the maximum single allocation, to this many bytes, for debugging.
Protected Attributes inherited from FMallocBinnedCommonBase
UE::FPlatformRecursiveMutex ExternalAllocMutex
std::atomic< uint64 > MemoryTrimEpoch { 0 }
uint64 NumPoolsPerPage
FPtrToPoolMapping PtrToPoolMapping
Static Protected Attributes inherited from FMallocBinnedCommonBase
static std::atomic< int64 > AllocatedLargePoolMemory
static std::atomic< int64 > AllocatedLargePoolMemoryWAlignment
static std::atomic< int64 > AllocatedOSSmallPoolMemory
static std::atomic< int64 > AllocatedSmallPoolMemory
static uint32 BinnedTlsSlot
static std::atomic< int64 > ConsolidatedMemory
static int64 HashMemory
static uint32 OsAllocationGranularity
static int64 PoolInfoMemory
static std::atomic< int64 > TLSMemory
Detailed Description
template<class AllocType, int NumSmallPools, int MaxSmallPoolSize>
class TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >
Definition at line 418 of file MallocBinnedCommon.h.
Member Function Documentation
AllocateHashBuckets()
template<class AllocType, int NumSmallPools, int MaxSmallPoolSize> void TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::AllocateHashBuckets () inline protected
Definition at line 974 of file MallocBinnedCommon.h.
References Align, DefaultConstructItems(), HashBuckets, FMallocBinnedCommonBase::HashMemory, FMallocBinnedCommonBase::OsAllocationGranularity, FMallocBinnedCommonBase::PtrToPoolMapping, UE_MBC_UPDATE_STATS, and verify.
BoundSizeToPoolIndex()
template<class AllocType, int NumSmallPools, int MaxSmallPoolSize> FORCEINLINE uint32 TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::BoundSizeToPoolIndex (SIZE_T Size, const uint8(&) MemSizeToPoolIndex[1+(MAX_SMALL_POOL_SIZE > > 4)]) const inline protected
Definition at line 837 of file MallocBinnedCommon.h.
References checkSlow, FORCEINLINE, MAX_SMALL_POOL_SIZE, NUM_SMALL_POOLS, TSequenceHistory< HistorySize >::Size, UE_MBC_MIN_SMALL_POOL_ALIGNMENT, and UE_MBC_MIN_SMALL_POOL_ALIGNMENT_SHIFT.
Referenced by PromoteToLargerBin(), and QuantizeSizeCommon().
ClearAndDisableTLSCachesOnCurrentThread()
template<class AllocType, int NumSmallPools, int MaxSmallPoolSize> virtual void TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::ClearAndDisableTLSCachesOnCurrentThread () inline override protected virtual
Clears the TLS caches on the current thread and disables any future caching.
Reimplemented from FMalloc.
Definition at line 761 of file MallocBinnedCommon.h.
References TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::FPerThreadFreeBlockLists::ClearTLS(), GMallocBinnedPerThreadCaches, and UE_MBC_ALLOW_RUNTIME_TWEAKING.
GetAllocationSizeExternal()
template<class AllocType, int NumSmallPools, int MaxSmallPoolSize> bool TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::GetAllocationSizeExternal (void * Ptr, SIZE_T & SizeOut) inline protected
Definition at line 874 of file MallocBinnedCommon.h.
References checkf, FMallocBinnedCommonBase::ExternalAllocMutex, Fatal, TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::Internal::FindPoolInfo(), LogMemory, TEXT, and UE_LOG.
GetAllocatorStats()
template<class AllocType, int NumSmallPools, int MaxSmallPoolSize> virtual void TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::GetAllocatorStats (FGenericMemoryStats & out_Stats) inline override virtual
Writes allocator stats from the last update into the specified destination.
Reimplemented from FMalloc.
Definition at line 459 of file MallocBinnedCommon.h.
References FMallocBinnedCommonBase::GetAllocatorStatsInternal(), and GetTotalAllocatedSmallPoolMemory().
GetFreeBlockListsRegistrationMutex()
template<class AllocType, int NumSmallPools, int MaxSmallPoolSize> UE::FPlatformRecursiveMutex & TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::GetFreeBlockListsRegistrationMutex () inline static protected
Definition at line 733 of file MallocBinnedCommon.h.
Referenced by GetTotalAllocatedSmallPoolMemory(), RegisterThreadFreeBlockLists(), and UnregisterThreadFreeBlockLists().
GetRegisteredFreeBlockLists()
template<class AllocType, int NumSmallPools, int MaxSmallPoolSize> TArray< FPerThreadFreeBlockLists * > & TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::GetRegisteredFreeBlockLists () inline static protected
Definition at line 739 of file MallocBinnedCommon.h.
Referenced by GetTotalAllocatedSmallPoolMemory(), RegisterThreadFreeBlockLists(), and UnregisterThreadFreeBlockLists().
GetTotalAllocatedSmallPoolMemory()
template<class AllocType, int NumSmallPools, int MaxSmallPoolSize> int64 TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::GetTotalAllocatedSmallPoolMemory () const inline protected
Definition at line 904 of file MallocBinnedCommon.h.
References FMallocBinnedCommonBase::AllocatedSmallPoolMemory, FMallocBinnedCommonBase::ConsolidatedMemory, GetFreeBlockListsRegistrationMutex(), and GetRegisteredFreeBlockLists().
Referenced by GetAllocatorStats(), and UpdateStatsCommon().
MarkTLSCachesAsUnusedOnCurrentThread()
template<class AllocType, int NumSmallPools, int MaxSmallPoolSize> virtual void TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::MarkTLSCachesAsUnusedOnCurrentThread () inline override protected virtual
Mark TLS caches for current thread as unused.
Typically before going to sleep. These are the threads that we can trim without waking them up.
Reimplemented from FMalloc.
Definition at line 786 of file MallocBinnedCommon.h.
References GMallocBinnedPerThreadCaches, UE_MBC_ALLOW_RUNTIME_TWEAKING, and TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::FPerThreadFreeBlockLists::UnlockTLS().
MarkTLSCachesAsUsedOnCurrentThread()
template<class AllocType, int NumSmallPools, int MaxSmallPoolSize> virtual void TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::MarkTLSCachesAsUsedOnCurrentThread () inline override protected virtual
Mark TLS caches for the current thread as used.
Thread has woken up to do some processing and needs its TLS caches back.
Reimplemented from FMalloc.
Definition at line 774 of file MallocBinnedCommon.h.
References GMallocBinnedPerThreadCaches, TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::FPerThreadFreeBlockLists::LockTLS(), and UE_MBC_ALLOW_RUNTIME_TWEAKING.
PromoteToLargerBin()
template<class AllocType, int NumSmallPools, int MaxSmallPoolSize> bool TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::PromoteToLargerBin (SIZE_T & Size, uint32 & Alignment, const AllocType & Alloc) const inline protected
Definition at line 846 of file MallocBinnedCommon.h.
References Align, BoundSizeToPoolIndex(), IsAligned(), FMath::Max, MAX_SMALL_POOL_SIZE, NUM_SMALL_POOLS, TSequenceHistory< HistorySize >::Size, UE_MBC_MAX_SMALL_POOL_ALIGNMENT, UE_MBC_MIN_SMALL_POOL_ALIGNMENT, and UNLIKELY.
QuantizeSizeCommon()
template<class AllocType, int NumSmallPools, int MaxSmallPoolSize> FORCEINLINE SIZE_T TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::QuantizeSizeCommon (SIZE_T Count, uint32 Alignment, const AllocType & Alloc) const inline protected
Definition at line 801 of file MallocBinnedCommon.h.
References Align, BoundSizeToPoolIndex(), check, checkSlow, Count, DEFAULT_ALIGNMENT, FORCEINLINE, IsAligned(), FMath::IsPowerOfTwo(), FMath::Max, MAX_SMALL_POOL_SIZE, NUM_SMALL_POOLS, UE_MBC_MAX_SMALL_POOL_ALIGNMENT, and UE_MBC_MIN_SMALL_POOL_ALIGNMENT.
RegisterThreadFreeBlockLists()
template<class AllocType, int NumSmallPools, int MaxSmallPoolSize> void TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::RegisterThreadFreeBlockLists (FPerThreadFreeBlockLists * FreeBlockLists) inline static private
Definition at line 989 of file MallocBinnedCommon.h.
References GetFreeBlockListsRegistrationMutex(), and GetRegisteredFreeBlockLists().
Referenced by TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::FPerThreadFreeBlockLists::SetTLS().
SetupTLSCachesOnCurrentThread()
template<class AllocType, int NumSmallPools, int MaxSmallPoolSize> virtual void TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::SetupTLSCachesOnCurrentThread () inline override protected virtual
Set up TLS caches on the current thread.
These are the threads that we can trim.
Reimplemented from FMalloc.
Definition at line 745 of file MallocBinnedCommon.h.
References FAndroidTLS::AllocTlsSlot(), FMallocBinnedCommonBase::BinnedTlsSlot, check, GMallocBinnedPerThreadCaches, FGenericPlatformTLS::IsValidTlsSlot(), TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::FPerThreadFreeBlockLists::SetTLS(), and UE_MBC_ALLOW_RUNTIME_TWEAKING.
UnregisterThreadFreeBlockLists()
template<class AllocType, int NumSmallPools, int MaxSmallPoolSize> void TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::UnregisterThreadFreeBlockLists (FPerThreadFreeBlockLists * FreeBlockLists) inline static private
Definition at line 996 of file MallocBinnedCommon.h.
References TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::FPerThreadFreeBlockLists::AllocatedMemory, FMallocBinnedCommonBase::ConsolidatedMemory, GetFreeBlockListsRegistrationMutex(), GetRegisteredFreeBlockLists(), and UE_MBC_UPDATE_STATS.
Referenced by TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::FPerThreadFreeBlockLists::ClearTLS().
UpdateStatsCommon()
template<class AllocType, int NumSmallPools, int MaxSmallPoolSize> void TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::UpdateStatsCommon (const AllocType & Alloc) inline protected
Definition at line 921 of file MallocBinnedCommon.h.
References FMallocBinnedCommonBase::AllocatedLargePoolMemory, FMallocBinnedCommonBase::AllocatedLargePoolMemoryWAlignment, FMallocBinnedCommonBase::AllocatedOSSmallPoolMemory, CSV_CATEGORY_INDEX, CSV_CUSTOM_STAT, float, FName, GetTotalAllocatedSmallPoolMemory(), GMallocBinnedEnableCSVStats, Name, TCString< TCHAR >::Sprintf(), and TEXT.
Friends And Related Symbol Documentation
FMallocBinnedCommonUtils
template<class AllocType, int NumSmallPools, int MaxSmallPoolSize> friend class FMallocBinnedCommonUtils friend
Definition at line 420 of file MallocBinnedCommon.h.
References FMallocBinnedCommonUtils.
Referenced by FMallocBinnedCommonUtils.
Field Documentation
HashBucketFreeList
template<class AllocType, int NumSmallPools, int MaxSmallPoolSize> FPoolHashBucket* TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::HashBucketFreeList = nullptr private
Definition at line 987 of file MallocBinnedCommon.h.
HashBuckets
template<class AllocType, int NumSmallPools, int MaxSmallPoolSize> FPoolHashBucket* TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::HashBuckets = nullptr private
Definition at line 986 of file MallocBinnedCommon.h.
Referenced by AllocateHashBuckets().
MAX_SMALL_POOL_SIZE
template<class AllocType, int NumSmallPools, int MaxSmallPoolSize> int TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::MAX_SMALL_POOL_SIZE = MaxSmallPoolSize static constexpr private
Definition at line 423 of file MallocBinnedCommon.h.
Referenced by BoundSizeToPoolIndex(), PromoteToLargerBin(), and QuantizeSizeCommon().
NUM_SMALL_POOLS
template<class AllocType, int NumSmallPools, int MaxSmallPoolSize> int TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::NUM_SMALL_POOLS = NumSmallPools static constexpr private
Definition at line 422 of file MallocBinnedCommon.h.
Referenced by BoundSizeToPoolIndex(), PromoteToLargerBin(), and QuantizeSizeCommon().
The documentation for this class was generated from the following file:
Runtime/Core/Public/HAL/MallocBinnedCommon.h