Unreal Engine 5.6 C++ API: FReplyBase Class Reference
FReplyBase Class Reference
Base class for all the ways that a Slate Widget can reply to events.
#include "ReplyBase.h"
Public Member Functions
const TSharedPtr< SWidget > GetHandler () const
The widget that ultimately handled the event.
bool IsEventHandled () const
Protected Member Functions
FReplyBase (bool InIsHandled)
A reply can be handled or unhandled.
Protected Attributes
bool bIsHandled
Has a widget handled an event.
TSharedPtr< SWidget > EventHandler
Widget that handled the event that generated this reply.
Detailed Description
Base class for all the ways that a Slate Widget can reply to events.
Typical replies include requests to set focus, capture or release the pointer, signify a cursor preference, etc.
Definition at line 14 of file ReplyBase.h.
Constructor & Destructor Documentation
FReplyBase()
FReplyBase::FReplyBase (bool InIsHandled) inline protected
A reply can be handled or unhandled.
Any widget handling events decides whether it has handled the event.
Definition at line 27 of file ReplyBase.h.
References bIsHandled.
Referenced by TReplyBase< ReplyType >::TReplyBase().
Member Function Documentation
GetHandler()
const TSharedPtr< SWidget > FReplyBase::GetHandler () const inline
The widget that ultimately handled the event.
Definition at line 22 of file ReplyBase.h.
References EventHandler.
IsEventHandled()
bool FReplyBase::IsEventHandled () const inline
Returns
true if this this reply is a result of the event being handled; false otherwise.
Definition at line 19 of file ReplyBase.h.
References bIsHandled.
Referenced by FPopupMethodReply::IsSet(), FArguments< ItemType >::OnDrop(), SListView< TSharedPtr< FString > >::OnKeyDown(), STreeView< FRigVMSearchResult >::OnKeyDown(), SCommonListView< ItemType >::OnTouchMoved(), SCommonTileView< ItemType >::OnTouchMoved(), SCommonTreeView< ItemType >::OnTouchMoved(), UE::Sequencer::FInputHandlerStack::ProcessEvent(), and UE::Sequencer::FInputHandlerStack::ProcessKeyEvent().
Field Documentation
bIsHandled
bool FReplyBase::bIsHandled protected
Has a widget handled an event.
Definition at line 33 of file ReplyBase.h.
Referenced by FPopupMethodReply::FPopupMethodReply(), FReply::FReply(), FReplyBase(), TReplyBase< ReplyType >::TReplyBase(), and IsEventHandled().
EventHandler
TSharedPtr<SWidget> FReplyBase::EventHandler protected
Widget that handled the event that generated this reply.
Definition at line 36 of file ReplyBase.h.
Referenced by GetHandler(), and TReplyBase< ReplyType >::SetHandler().
The documentation for this class was generated from the following file:
Runtime/SlateCore/Public/Input/ReplyBase.h