Unreal Engine 5.6 C++ API: AExponentialHeightFog Class Reference
AExponentialHeightFog Class Reference
#include "ExponentialHeightFog.h"
Public Member Functions
class UExponentialHeightFogComponent * GetComponent () const
Returns Component subobject.
virtual void PostInitializeComponents () override
UPROPERTY() uint32 bEnabled UFUNCTION () virtual void OnRep_bEnabled()
replicated copy of ExponentialHeightFogComponent's bEnabled property
Private Member Functions
virtual bool ActorTypeSupportsDataLayer () const override
GENERATED_UCLASS_BODY () virtual void GetLifetimeReplicatedProps(TArray< FLifetimeProperty > &OutLifetimeProps) const override
UPROPERTY ()) TObjectPtr< class UExponentialHeightFogComponent > Component
Detailed Description
Definition at line 14 of file ExponentialHeightFog.h.
Member Function Documentation
ActorTypeSupportsDataLayer()
virtual bool AExponentialHeightFog::ActorTypeSupportsDataLayer () const inline override private virtual
Reimplemented from AInfo.
Definition at line 23 of file ExponentialHeightFog.h.
GENERATED_UCLASS_BODY()
AExponentialHeightFog::GENERATED_UCLASS_BODY () const & override private
GetComponent()
class UExponentialHeightFogComponent * AExponentialHeightFog::GetComponent () const inline
Returns Component subobject.
Definition at line 46 of file ExponentialHeightFog.h.
References Component, and GetComponent().
Referenced by GetComponent().
PostInitializeComponents()
virtual void AExponentialHeightFog::PostInitializeComponents () override virtual
References PostInitializeComponents().
Referenced by PostInitializeComponents().
UFUNCTION()
UPROPERTY() uint32 bEnabled AExponentialHeightFog::UFUNCTION ()
replicated copy of ExponentialHeightFogComponent's bEnabled property
Replication Notification Callbacks
References UFUNCTION().
Referenced by UFUNCTION().
UPROPERTY()
AExponentialHeightFog::UPROPERTY () private
Todo
document
References Category, Component, meta, and UPROPERTY().
Referenced by UPROPERTY().
The documentation for this class was generated from the following file:
Runtime/Engine/Classes/Engine/ExponentialHeightFog.h