Unreal Engine 5.6 C++ API: ALevelStreamingVolume Class Reference
ALevelStreamingVolume Class Reference
#include "LevelStreamingVolume.h"
Private Member Functions
virtual void CheckForErrors () override
Function that gets called from within Map_Check to allow this actor to check itself for any potential errors and register them with map check dialog.
GENERATED_UCLASS_BODY () UPROPERTY()) TArray< FName > StreamingLevelNames
Levels names affected by this level streaming volume.
virtual void PostLoad () override
void UpdateStreamingLevelsRefs ()
Updates list of streaming levels that are referenced by this streaming volume.
UPROPERTY() uint32 bEditorPreVisOnly UPROPERTY() uint32 bDisabled UPROPERTY () TEnumAsByte< enum EStreamingVolumeUsage > StreamingUsage
If true, this streaming volume should only be used for editor streaming level previs.
Additional Inherited Members
Public Member Functions inherited from AVolume
bool EncompassesPoint (FVector Point, float SphereRadius=0.f, float *OutDistanceToPoint=0) const
FBoxSphereBounds GetBounds () const
virtual FName GetCustomIconName () const override
virtual bool IsLevelBoundsRelevant () const override
virtual bool IsStaticBrush () const override
virtual bool IsVolumeBrush () const override
virtual void PostEditChangeProperty (FPropertyChangedEvent &PropertyChangedEvent) override
virtual void PostEditImport () override
virtual bool ShouldCheckCollisionComponentForErrors () const
Public Member Functions inherited from ABrush
virtual bool CanDeleteSelectedActor (FText &OutReason) const override
bool CanEverAffectBSP () const
virtual bool CanReplaceSelectedActor (FText &OutReason) const override
FORCEINLINE void ClearNotForClientOrServer ()
Indicate that brush need should be loaded on client or servers.
virtual void CopyPosRotScaleFrom (ABrush *Other)
DECLARE_MULTICAST_DELEGATE_OneParam (FOnBrushRegistered, ABrush *)
Delegate used for notifications when PostRegisterAllComponents is called for a Brush.
virtual void Destroyed () override
class UBrushComponent * GetBrushComponent () const
Returns BrushComponent subobject.
virtual FColor GetWireColor () const
Figures out the best color to use for this brushes wireframe drawing.
virtual void InitPosRotScale ()
virtual bool IsActorLabelEditable () const override
virtual bool IsBrushShape () const
virtual bool IsComponentRelevantForNavigation (UActorComponent *Component) const override
FORCEINLINE bool IsNotForClientOrServer () const
Return if true if this brush is not used for gameplay (i.e.
virtual bool Modify (bool bAlwaysMarkDirty=true) override
virtual bool NeedsLoadForClient () const override
virtual bool NeedsLoadForServer () const override
virtual void PostEditChangeChainProperty (FPropertyChangedChainEvent &PropertyChangedEvent) override
virtual void PostEditMove (bool bFinished) override
virtual void PostRegisterAllComponents () override
virtual void RebuildNavigationData ()
virtual bool SetIsHiddenEdLayer (bool bIsHiddenEdLayer) override
virtual void SetIsTemporarilyHiddenInEditor (bool bIsHidden) override
FORCEINLINE void SetNotForClientOrServer ()
Indicate that this brush need not be loaded on client or servers.
bool ShouldExportStaticNavigableGeometry () const
virtual bool SupportsExternalPackaging () const override
virtual bool SupportsLayers () const override
UPROPERTY() uint32 bInManipulation UPROPERTY () TArray< struct FGeomSelection > SavedSelections
Flag set when we are in a manipulation (scaling, translation, brush builder param change etc.)
Static Public Member Functions inherited from ABrush
static FOnBrushRegistered & GetOnBrushRegisteredDelegate ()
Function to get the 'brush registered' delegate.
static bool GetSuppressBSPRegeneration ()
static bool NeedsRebuild (TArray< TWeakObjectPtr< ULevel > > *OutLevels=nullptr)
Called to see if any of the levels need rebuilding.
static void OnRebuildDone ()
Called upon finishing the csg rebuild to clear the rebuild bool.
static void SetNeedRebuild (ULevel *InLevel)
Called to make not of the level that needs rebuilding.
static void SetSuppressBSPRegeneration (bool bSuppress)
Static Public Attributes inherited from ABrush
static const TCHAR * GGeometryRebuildCause
Debug purposes only; an attempt to catch the cause of UE-36265.
Detailed Description
Definition at line 29 of file LevelStreamingVolume.h.
Member Function Documentation
CheckForErrors()
virtual void ALevelStreamingVolume::CheckForErrors () override private virtual
Function that gets called from within Map_Check to allow this actor to check itself for any potential errors and register them with map check dialog.
Reimplemented from AVolume.
GENERATED_UCLASS_BODY()
ALevelStreamingVolume::GENERATED_UCLASS_BODY () private
Levels names affected by this level streaming volume.
References Category, meta, and UPROPERTY().
PostLoad()
virtual void ALevelStreamingVolume::PostLoad () override private virtual
Reimplemented from ABrush.
References PostLoad().
Referenced by PostLoad().
UpdateStreamingLevelsRefs()
void ALevelStreamingVolume::UpdateStreamingLevelsRefs () private
Updates list of streaming levels that are referenced by this streaming volume.
UPROPERTY()
UPROPERTY() uint32 bEditorPreVisOnly UPROPERTY() uint32 bDisabled ALevelStreamingVolume::UPROPERTY () private
If true, this streaming volume should only be used for editor streaming level previs.
If true, this streaming volume is ignored by the streaming volume code. Used to either disable a level streaming volume without disassociating it from the level, or to toggle the control of a level's streaming between Kismet and volume streaming. Determines what this volume is used for, e.g. whether to control loading, loading and visibility or just visibilty (blocking on load)
References Category, and UPROPERTY().
Referenced by GENERATED_UCLASS_BODY(), and UPROPERTY().
The documentation for this class was generated from the following file:
Runtime/Engine/Classes/Engine/LevelStreamingVolume.h