Unreal Engine 5.6 C++ API: FRigVMLocalVariableDetailCustomization Class Reference
FRigVMLocalVariableDetailCustomization Class Reference
#include "RigVMLocalVariableDetailCustomization.h"
Public Member Functions
virtual void CustomizeDetails (IDetailLayoutBuilder &DetailBuilder) override
IDetailCustomization interface.
Public Member Functions inherited from IDetailCustomization
virtual ~IDetailCustomization ()
virtual void CustomizeDetails (const TSharedPtr< IDetailLayoutBuilder > &DetailBuilder)
Called when details should be customized, this version allows the customization to store a weak ptr to the layout builder.
virtual void PendingDelete ()
Called when no longer used and will be deleted.
Public Member Functions inherited from TSharedFromThis< IDetailCustomization >
TSharedRef< IDetailCustomization, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< IDetailCustomization, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Static Public Member Functions
static TSharedRef< IDetailCustomization > MakeInstance ()
Private Member Functions
FRigVMLocalVariableDetailCustomization ()
FText GetName () const
ECheckBoxState HandleBoolDefaultValueIsChecked () const
void HandlePinInfoChanged (const FEdGraphPinType &PinType)
void OnBoolDefaultValueChanged (ECheckBoxState InCheckBoxState)
FEdGraphPinType OnGetPinInfo () const
bool OnVerifyNameChanged (const FText &InText, FText &OutErrorMessage)
void SetName (const FText &InNewText, ETextCommit::Type InCommitType)
Private Attributes
URigVMBlueprint * BlueprintBeingCustomized
TSharedPtr< IPropertyHandle > DefaultValueHandle
TArray< TSharedPtr< FString > > EnumOptions
URigVMGraph * GraphBeingCustomized
TSharedPtr< IPropertyHandle > NameHandle
FRigVMLocalVariableNameValidator NameValidator
TArray< TWeakObjectPtr< URigVMDetailsViewWrapperObject > > ObjectsBeingCustomized
TSharedPtr< IPropertyHandle > TypeHandle
TSharedPtr< IPropertyHandle > TypeObjectHandle
FRigVMGraphVariableDescription VariableDescription
Additional Inherited Members
Protected Member Functions inherited from TSharedFromThis< IDetailCustomization >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions inherited from TSharedFromThis< IDetailCustomization >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
Definition at line 19 of file RigVMLocalVariableDetailCustomization.h.
Constructor & Destructor Documentation
FRigVMLocalVariableDetailCustomization()
FRigVMLocalVariableDetailCustomization::FRigVMLocalVariableDetailCustomization () inline private
Definition at line 21 of file RigVMLocalVariableDetailCustomization.h.
References BlueprintBeingCustomized, GraphBeingCustomized, and NameValidator.
Referenced by MakeInstance().
Member Function Documentation
CustomizeDetails()
virtual void FRigVMLocalVariableDetailCustomization::CustomizeDetails (IDetailLayoutBuilder & DetailBuilder) override virtual
IDetailCustomization interface.
Implements IDetailCustomization.
GetName()
FText FRigVMLocalVariableDetailCustomization::GetName () const private
HandleBoolDefaultValueIsChecked()
ECheckBoxState FRigVMLocalVariableDetailCustomization::HandleBoolDefaultValueIsChecked () const private
HandlePinInfoChanged()
void FRigVMLocalVariableDetailCustomization::HandlePinInfoChanged (const FEdGraphPinType & PinType) private
MakeInstance()
TSharedRef< IDetailCustomization > FRigVMLocalVariableDetailCustomization::MakeInstance () inline static
Definition at line 31 of file RigVMLocalVariableDetailCustomization.h.
References FRigVMLocalVariableDetailCustomization(), and MakeShareable().
OnBoolDefaultValueChanged()
void FRigVMLocalVariableDetailCustomization::OnBoolDefaultValueChanged (ECheckBoxState InCheckBoxState) private
OnGetPinInfo()
FEdGraphPinType FRigVMLocalVariableDetailCustomization::OnGetPinInfo () const private
OnVerifyNameChanged()
bool FRigVMLocalVariableDetailCustomization::OnVerifyNameChanged (const FText & InText, FText & OutErrorMessage) private
SetName()
void FRigVMLocalVariableDetailCustomization::SetName (const FText & InNewText, ETextCommit::Type InCommitType) private
Field Documentation
BlueprintBeingCustomized
URigVMBlueprint* FRigVMLocalVariableDetailCustomization::BlueprintBeingCustomized private
Definition at line 42 of file RigVMLocalVariableDetailCustomization.h.
Referenced by FRigVMLocalVariableDetailCustomization().
DefaultValueHandle
TSharedPtr<IPropertyHandle> FRigVMLocalVariableDetailCustomization::DefaultValueHandle private
Definition at line 49 of file RigVMLocalVariableDetailCustomization.h.
EnumOptions
TArray<TSharedPtr<FString> > FRigVMLocalVariableDetailCustomization::EnumOptions private
Definition at line 52 of file RigVMLocalVariableDetailCustomization.h.
GraphBeingCustomized
URigVMGraph* FRigVMLocalVariableDetailCustomization::GraphBeingCustomized private
Definition at line 41 of file RigVMLocalVariableDetailCustomization.h.
Referenced by FRigVMLocalVariableDetailCustomization().
NameHandle
TSharedPtr<IPropertyHandle> FRigVMLocalVariableDetailCustomization::NameHandle private
Definition at line 46 of file RigVMLocalVariableDetailCustomization.h.
NameValidator
FRigVMLocalVariableNameValidator FRigVMLocalVariableDetailCustomization::NameValidator private
Definition at line 51 of file RigVMLocalVariableDetailCustomization.h.
Referenced by FRigVMLocalVariableDetailCustomization().
ObjectsBeingCustomized
TArray<TWeakObjectPtr<URigVMDetailsViewWrapperObject> > FRigVMLocalVariableDetailCustomization::ObjectsBeingCustomized private
Definition at line 44 of file RigVMLocalVariableDetailCustomization.h.
TypeHandle
TSharedPtr<IPropertyHandle> FRigVMLocalVariableDetailCustomization::TypeHandle private
Definition at line 47 of file RigVMLocalVariableDetailCustomization.h.
TypeObjectHandle
TSharedPtr<IPropertyHandle> FRigVMLocalVariableDetailCustomization::TypeObjectHandle private
Definition at line 48 of file RigVMLocalVariableDetailCustomization.h.
VariableDescription
FRigVMGraphVariableDescription FRigVMLocalVariableDetailCustomization::VariableDescription private
Definition at line 43 of file RigVMLocalVariableDetailCustomization.h.
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/RigVM/Source/RigVMEditor/Public/Editor/RigVMLocalVariableDetailCustomization.h