Unreal Engine 5.6 C++ API: Metasound::TDataReference< DataType > Class Template Reference
Metasound::TDataReference< DataType > Class Template Reference
Template class for a paramter reference.
#include "MetasoundDataReference.h"
Public Types
typedef TDataReferenceTypeInfo< DataType > FInfoType
Public Member Functions
TDataReference (const TDataReference< DataType > &Other)=default
Enable copy constructor.
TDataReference (TDataReference< DataType > &&Other)=default
Enable move constructor.
virtual const void *const GetDataTypeId () const override
Return the ID of the underlying type.
virtual const FName & GetDataTypeName () const override
Return the name of the underlying type.
virtual void * GetRaw () const override
Return a raw pointer to the data.
TDataReference< DataType > & operator= (const TDataReference< DataType > &Other)=default
Enable copy operator.
TDataReference< DataType > & operator= (TDataReference< DataType > &&Other)=default
Enable move operator.
Public Member Functions inherited from Metasound::IDataReference
virtual ~IDataReference ()=default
virtual TUniquePtr< IDataReference > Clone () const =0
Creates a copy of the parameter type.
Static Public Member Functions
template<typename... ArgTypes>
static TDataReference< DataType > CreateNew (ArgTypes &&... Args)
This should be used to construct a new DataType object and return this TDataReference as a wrapper around it.
Protected Types
typedef TSharedRef< DataType, ESPMode::NotThreadSafe > FRefType
Protected Member Functions
template<typename... ArgTypes>
TDataReference (EDataRefShouldConstruct InToken, ArgTypes &&... Args)
This constructor forwards arguments to an underlying constructor.
Protected Attributes
FRefType ObjectReference
Additional Inherited Members
Static Public Attributes inherited from Metasound::IDataReference
static METASOUNDGRAPHCORE_API const FName RouterName
Detailed Description
template<typename DataType>
class Metasound::TDataReference< DataType >
Template class for a paramter reference.
This fulfills the IParamterRef interface, utilizing TDataReferenceTypeInfo to define the the TypeName and TypeId of the parameter.
Definition at line 172 of file MetasoundDataReference.h.
Member Typedef Documentation
FInfoType
template<typename DataType> typedef TDataReferenceTypeInfo<DataType> Metasound::TDataReference< DataType >::FInfoType
Definition at line 189 of file MetasoundDataReference.h.
FRefType
template<typename DataType> typedef TSharedRef<DataType, ESPMode::NotThreadSafe> Metasound::TDataReference< DataType >::FRefType protected
Definition at line 185 of file MetasoundDataReference.h.
Constructor & Destructor Documentation
TDataReference() [1/3]
template<typename DataType> template<typename... ArgTypes> Metasound::TDataReference< DataType >::TDataReference (EDataRefShouldConstruct InToken, ArgTypes &&... Args) inline protected
This constructor forwards arguments to an underlying constructor.
Definition at line 180 of file MetasoundDataReference.h.
References Forward(), MakeShared(), NotThreadSafe, and ObjectReference.
Referenced by Metasound::TDataReadReference< FMidiClockSongPosition >::TDataReadReference(), Metasound::TDataReadReference< FMidiClockSongPosition >::TDataReadReference(), Metasound::TDataReadReference< FMidiClockSongPosition >::TDataReadReference(), TDataReference(), TDataReference(), Metasound::TDataValueReference< DataType >::TDataValueReference(), Metasound::TDataValueReference< DataType >::TDataValueReference(), Metasound::TDataWriteReference< FMidiClockSongPosition >::TDataWriteReference(), CreateNew(), operator=(), and operator=().
TDataReference() [2/3]
template<typename DataType> Metasound::TDataReference< DataType >::TDataReference (const TDataReference< DataType > & Other) default
Enable copy constructor.
References TDataReference(), and Other.
TDataReference() [3/3]
template<typename DataType> Metasound::TDataReference< DataType >::TDataReference (TDataReference< DataType > && Other) default
Enable move constructor.
References TDataReference(), and Other.
Member Function Documentation
CreateNew()
template<typename DataType> template<typename... ArgTypes> TDataReference< DataType > Metasound::TDataReference< DataType >::CreateNew (ArgTypes &&... Args) inline static
This should be used to construct a new DataType object and return this TDataReference as a wrapper around it.
Definition at line 194 of file MetasoundDataReference.h.
References TDataReference(), Forward(), and Metasound::NewObject.
GetDataTypeId()
template<typename DataType> virtual const void *const Metasound::TDataReference< DataType >::GetDataTypeId () const inline override virtual
Return the ID of the underlying type.
Implements Metasound::IDataReference.
Definition at line 220 of file MetasoundDataReference.h.
References Metasound::GetMetasoundDataTypeId().
GetDataTypeName()
template<typename DataType> virtual const FName & Metasound::TDataReference< DataType >::GetDataTypeName () const inline override virtual
Return the name of the underlying type.
Implements Metasound::IDataReference.
Definition at line 213 of file MetasoundDataReference.h.
References Metasound::GetMetasoundDataTypeName(), and Name.
GetRaw()
template<typename DataType> virtual void * Metasound::TDataReference< DataType >::GetRaw () const inline override virtual
Return a raw pointer to the data.
Implements Metasound::IDataReference.
Definition at line 226 of file MetasoundDataReference.h.
References ObjectReference.
operator=() [1/2]
template<typename DataType> TDataReference< DataType > & Metasound::TDataReference< DataType >::operator= (const TDataReference< DataType > & Other) default
Enable copy operator.
References TDataReference(), and Other.
operator=() [2/2]
template<typename DataType> TDataReference< DataType > & Metasound::TDataReference< DataType >::operator= (TDataReference< DataType > && Other) default
Enable move operator.
References TDataReference(), and Other.
Field Documentation
ObjectReference
template<typename DataType> FRefType Metasound::TDataReference< DataType >::ObjectReference protected
Definition at line 235 of file MetasoundDataReference.h.
Referenced by TDataReference(), Metasound::TDataReadReference< FMidiClockSongPosition >::Get(), Metasound::TDataValueReference< DataType >::Get(), Metasound::TDataWriteReference< FMidiClockSongPosition >::Get(), GetRaw(), Metasound::TDataReadReference< FMidiClockSongPosition >::operator*(), Metasound::TDataValueReference< DataType >::operator*(), Metasound::TDataWriteReference< FMidiClockSongPosition >::operator*(), Metasound::TDataReadReference< FMidiClockSongPosition >::operator->(), Metasound::TDataValueReference< DataType >::operator->(), Metasound::TDataWriteReference< FMidiClockSongPosition >::operator->(), and Metasound::TDataReadReference< FMidiClockSongPosition >::operator=().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/Metasound/Source/MetasoundGraphCore/Public/MetasoundDataReference.h