Unreal Engine 5.6 C++ API: FRDGScope::TStorage< TTypes > Class Template Reference
FRDGScope::TStorage< TTypes > Class Template Reference
#include "RenderGraphEvent.h"
Public Member Functions
template<typename TCallback>
void Dispatch (TCallback &&Callback)
template<typename TScopeType, typename... TArgs>
void Emplace (TArgs &&... Args)
template<typename TScopeType>
TScopeType * Get ()
template<typename TScopeType>
TScopeType const * Get () const
Static Public Member Functions
template<typename TScopeType>
static constexpr SIZE_T GetTypeIndex ()
Private Types
typedef TVariant< FEmptyVariantState, TTypes... > TImpl
Private Attributes
TImpl Impl
Detailed Description
template<typename... TTypes>
class FRDGScope::TStorage< TTypes >
Definition at line 244 of file RenderGraphEvent.h.
Member Typedef Documentation
TImpl
template<typename... TTypes> typedef TVariant<FEmptyVariantState, TTypes...> FRDGScope::TStorage< TTypes >::TImpl private
Definition at line 246 of file RenderGraphEvent.h.
Member Function Documentation
Dispatch()
template<typename... TTypes> template<typename TCallback> void FRDGScope::TStorage< TTypes >::Dispatch (TCallback && Callback) inline
Definition at line 251 of file RenderGraphEvent.h.
Emplace()
template<typename... TTypes> template<typename TScopeType, typename... TArgs> void FRDGScope::TStorage< TTypes >::Emplace (TArgs &&... Args) inline
Definition at line 259 of file RenderGraphEvent.h.
Referenced by FRDGScope::TStorage< FRDGScope_Budget >::Emplace().
Get() [1/2]
template<typename... TTypes> template<typename TScopeType> TScopeType * FRDGScope::TStorage< TTypes >::Get () inline
Definition at line 271 of file RenderGraphEvent.h.
Referenced by FRDGScope::TStorage< FRDGScope_Budget >::Get(), and FRDGScope::TStorage< FRDGScope_Budget >::Get().
Get() [2/2]
template<typename... TTypes> template<typename TScopeType> TScopeType const * FRDGScope::TStorage< TTypes >::Get () const inline
Definition at line 279 of file RenderGraphEvent.h.
GetTypeIndex()
template<typename... TTypes> template<typename TScopeType> constexpr SIZE_T FRDGScope::TStorage< TTypes >::GetTypeIndex () inline static constexpr
Definition at line 265 of file RenderGraphEvent.h.
Field Documentation
Impl
template<typename... TTypes> TImpl FRDGScope::TStorage< TTypes >::Impl private
Definition at line 247 of file RenderGraphEvent.h.
The documentation for this class was generated from the following file:
Runtime/RenderCore/Public/RenderGraphEvent.h