Unreal Engine 5.6 C++ API: TPropertyIterator< T > Class Template Reference
TPropertyIterator< T > Class Template Reference
Iterates over all structs and their properties.
#include "PropertyIterator.h"
Public Member Functions
TPropertyIterator ()
const UStruct * GetStruct ()
FORCEINLINE operator bool () const
conversion to "bool" returning true if the iterator is valid.
FORCEINLINE bool operator! () const
inverse of the "bool" operator
T * operator* ()
void operator++ ()
T * operator-> ()
Protected Member Functions
void IterateToNext ()
Private Attributes
TObjectIterator< UStruct > ClassIterator
FField * Field
The current location in the list of fields being iterated.
const UStruct * Struct
The object being searched for the specified field.
Friends
bool operator!= (const TPropertyIterator< T > &Lhs, const TPropertyIterator< T > &Rhs)
bool operator== (const TPropertyIterator< T > &Lhs, const TPropertyIterator< T > &Rhs)
Detailed Description
template<class T>
class TPropertyIterator< T >
Iterates over all structs and their properties.
Definition at line 15 of file PropertyIterator.h.
Constructor & Destructor Documentation
TPropertyIterator()
template<class T> TPropertyIterator< T >::TPropertyIterator () inline
Definition at line 25 of file PropertyIterator.h.
References ClassIterator, Field, IterateToNext(), and Struct.
Referenced by operator!=, and operator==.
Member Function Documentation
GetStruct()
template<class T> const UStruct * TPropertyIterator< T >::GetStruct () inline
Definition at line 70 of file PropertyIterator.h.
References Struct.
IterateToNext()
template<class T> void TPropertyIterator< T >::IterateToNext () inline protected
Definition at line 75 of file PropertyIterator.h.
References ClassIterator, Field, FField::IsA(), FField::Next, and Struct.
Referenced by TPropertyIterator(), and operator++().
operator bool()
template<class T> FORCEINLINE TPropertyIterator< T >::operator bool () const inline explicit
conversion to "bool" returning true if the iterator is valid.
Definition at line 42 of file PropertyIterator.h.
References Field, and FORCEINLINE.
operator!()
template<class T> FORCEINLINE bool TPropertyIterator< T >::operator! () const inline
inverse of the "bool" operator
Definition at line 47 of file PropertyIterator.h.
References bool, and FORCEINLINE.
operator*()
template<class T> T * TPropertyIterator< T >::operator* () inline
Definition at line 60 of file PropertyIterator.h.
References checkSlow, and Field.
operator++()
template<class T> void TPropertyIterator< T >::operator++ () inline
Definition at line 55 of file PropertyIterator.h.
References checkSlow, Field, and IterateToNext().
operator->()
template<class T> T * TPropertyIterator< T >::operator-> () inline
Definition at line 65 of file PropertyIterator.h.
References checkSlow, and Field.
Friends And Related Symbol Documentation
operator!=
template<class T> bool operator!= (const TPropertyIterator< T > & Lhs, const TPropertyIterator< T > & Rhs) friend
Definition at line 53 of file PropertyIterator.h.
References TPropertyIterator(), and Field.
operator==
template<class T> bool operator== (const TPropertyIterator< T > & Lhs, const TPropertyIterator< T > & Rhs) friend
Definition at line 52 of file PropertyIterator.h.
References TPropertyIterator(), and Field.
Field Documentation
ClassIterator
template<class T> TObjectIterator<UStruct> TPropertyIterator< T >::ClassIterator private
Definition at line 22 of file PropertyIterator.h.
Referenced by TPropertyIterator(), and IterateToNext().
Field
template<class T> FField* TPropertyIterator< T >::Field private
The current location in the list of fields being iterated.
Definition at line 21 of file PropertyIterator.h.
Referenced by TPropertyIterator(), IterateToNext(), operator bool(), operator!=, operator*(), operator++(), operator->(), and operator==.
Struct
template<class T> const UStruct* TPropertyIterator< T >::Struct private
The object being searched for the specified field.
Definition at line 19 of file PropertyIterator.h.
Referenced by TPropertyIterator(), GetStruct(), and IterateToNext().
The documentation for this class was generated from the following file:
Runtime/CoreUObject/Public/UObject/PropertyIterator.h