Unreal Engine 5.6 C++ API: FActorPrimitiveColorHandler Class Reference
FActorPrimitiveColorHandler Class Reference
FActorPrimitiveColorHandler is a simple mechanism for custom actor coloration registration.
#include "ActorPrimitiveColorHandler.h"
Data Structures
struct FPrimitiveColorHandler
Public Member Functions
FActorPrimitiveColorHandler ()
FName GetActivePrimitiveColorHandler () const
FText GetActivePrimitiveColorHandlerDisplayName () const
FLinearColor GetPrimitiveColor (const UPrimitiveComponent *InPrimitiveComponent) const
void GetRegisteredPrimitiveColorHandlers (TArray< FPrimitiveColorHandler > &OutPrimitiveColorHandlers) const
void RefreshPrimitiveColorHandler (FName InHandlerName, const TArray< AActor * > &InActors)
void RefreshPrimitiveColorHandler (FName InHandlerName, const TArray< UPrimitiveComponent * > &InPrimitiveComponents)
void RefreshPrimitiveColorHandler (FName InHandlerName, UWorld *InWorld)
void RegisterPrimitiveColorHandler (FName InHandlerName, const FText &InHandlerText, bool bInAvailalbleInEditor, const FGetColorFunc &InHandlerFunc, const FActivateFunc &InActivateFunc=DefaultFunc, const FText &InHandlerToolTipText=FText())
void RegisterPrimitiveColorHandler (FName InHandlerName, const FText &InHandlerText, const FGetColorFunc &InHandlerFunc, const FActivateFunc &InActivateFunc=DefaultFunc, const FText &InHandlerToolTipText=FText())
void RegisterPrimitiveColorHandler (FPrimitiveColorHandler &PrimitiveColorHandler)
bool SetActivePrimitiveColorHandler (FName InHandlerName, UWorld *InWorld)
void UnregisterPrimitiveColorHandler (FName InHandlerName)
Static Public Member Functions
static FActorPrimitiveColorHandler & Get ()
Private Types
using FActivateFunc = TFunction<void(void)>
using FDeactivateFunc = TFunction<void(void)>
using FGetColorFunc = TFunction<FLinearColor(const UPrimitiveComponent*)>
Private Member Functions
void InitActivePrimitiveColorHandler ()
Private Attributes
FPrimitiveColorHandler * ActivePrimitiveColorHandler
FName ActivePrimitiveColorHandlerName
TMap< FName, FPrimitiveColorHandler > Handlers
Static Private Attributes
static constexpr auto DefaultFunc = []() {}
Detailed Description
FActorPrimitiveColorHandler is a simple mechanism for custom actor coloration registration.
Once an actor color handler is registered, it can automatically be activated with the SHOW ACTORCOLORATION <HANDLERNAME> command.
Definition at line 19 of file ActorPrimitiveColorHandler.h.
Member Typedef Documentation
FActivateFunc
using FActorPrimitiveColorHandler::FActivateFunc = TFunction<void(void)> private
Definition at line 22 of file ActorPrimitiveColorHandler.h.
FDeactivateFunc
using FActorPrimitiveColorHandler::FDeactivateFunc = TFunction<void(void)> private
Definition at line 23 of file ActorPrimitiveColorHandler.h.
FGetColorFunc
using FActorPrimitiveColorHandler::FGetColorFunc = TFunction<FLinearColor(const UPrimitiveComponent*)> private
Definition at line 21 of file ActorPrimitiveColorHandler.h.
Constructor & Destructor Documentation
FActorPrimitiveColorHandler()
FActorPrimitiveColorHandler::FActorPrimitiveColorHandler ()
References UE_API.
Referenced by Get().
Member Function Documentation
Get()
FActorPrimitiveColorHandler & FActorPrimitiveColorHandler::Get () static
References FActorPrimitiveColorHandler(), and UE_API.
GetActivePrimitiveColorHandler()
FName FActorPrimitiveColorHandler::GetActivePrimitiveColorHandler () const
References UE_API.
GetActivePrimitiveColorHandlerDisplayName()
FText FActorPrimitiveColorHandler::GetActivePrimitiveColorHandlerDisplayName () const
References UE_API.
GetPrimitiveColor()
FLinearColor FActorPrimitiveColorHandler::GetPrimitiveColor (const UPrimitiveComponent * InPrimitiveComponent) const
References UE_API.
GetRegisteredPrimitiveColorHandlers()
void FActorPrimitiveColorHandler::GetRegisteredPrimitiveColorHandlers (TArray< FPrimitiveColorHandler > & OutPrimitiveColorHandlers) const
References UE_API.
InitActivePrimitiveColorHandler()
void FActorPrimitiveColorHandler::InitActivePrimitiveColorHandler () private
RefreshPrimitiveColorHandler() [1/3]
void FActorPrimitiveColorHandler::RefreshPrimitiveColorHandler (FName InHandlerName, const TArray< AActor * > & InActors)
References UE_API.
RefreshPrimitiveColorHandler() [2/3]
void FActorPrimitiveColorHandler::RefreshPrimitiveColorHandler (FName InHandlerName, const TArray< UPrimitiveComponent * > & InPrimitiveComponents)
References UE_API.
RefreshPrimitiveColorHandler() [3/3]
void FActorPrimitiveColorHandler::RefreshPrimitiveColorHandler (FName InHandlerName, UWorld * InWorld)
References UE_API.
RegisterPrimitiveColorHandler() [1/3]
void FActorPrimitiveColorHandler::RegisterPrimitiveColorHandler (FName InHandlerName, const FText & InHandlerText, bool bInAvailalbleInEditor, const FGetColorFunc & InHandlerFunc, const FActivateFunc & InActivateFunc = DefaultFunc, const FText & InHandlerToolTipText = FText())
References DefaultFunc, and UE_API.
RegisterPrimitiveColorHandler() [2/3]
void FActorPrimitiveColorHandler::RegisterPrimitiveColorHandler (FName InHandlerName, const FText & InHandlerText, const FGetColorFunc & InHandlerFunc, const FActivateFunc & InActivateFunc = DefaultFunc, const FText & InHandlerToolTipText = FText())
References DefaultFunc, and UE_API.
RegisterPrimitiveColorHandler() [3/3]
void FActorPrimitiveColorHandler::RegisterPrimitiveColorHandler (FPrimitiveColorHandler & PrimitiveColorHandler)
References UE_API.
SetActivePrimitiveColorHandler()
bool FActorPrimitiveColorHandler::SetActivePrimitiveColorHandler (FName InHandlerName, UWorld * InWorld)
References UE_API.
UnregisterPrimitiveColorHandler()
void FActorPrimitiveColorHandler::UnregisterPrimitiveColorHandler (FName InHandlerName)
References UE_API.
Field Documentation
ActivePrimitiveColorHandler
FPrimitiveColorHandler* FActorPrimitiveColorHandler::ActivePrimitiveColorHandler private
Definition at line 63 of file ActorPrimitiveColorHandler.h.
ActivePrimitiveColorHandlerName
FName FActorPrimitiveColorHandler::ActivePrimitiveColorHandlerName private
Definition at line 62 of file ActorPrimitiveColorHandler.h.
DefaultFunc
auto FActorPrimitiveColorHandler::DefaultFunc = []() {} static constexpr private
Definition at line 24 of file ActorPrimitiveColorHandler.h.
Referenced by RegisterPrimitiveColorHandler(), and RegisterPrimitiveColorHandler().
Handlers
TMap<FName, FPrimitiveColorHandler> FActorPrimitiveColorHandler::Handlers private
Definition at line 64 of file ActorPrimitiveColorHandler.h.
The documentation for this class was generated from the following file:
Runtime/Engine/Classes/GameFramework/ActorPrimitiveColorHandler.h