Unreal Engine 5.6 C++ API: TLruCache< KeyType, ValueType, KeyComp >::TIterator Class Reference
TLruCache< KeyType, ValueType, KeyComp >::TIterator Class Reference
Cache iterator.
#include "LruCache.h"
Public Member Functions
FORCEINLINE TIterator ()
FORCEINLINE TIterator (TLruCache &InCache)
FORCEINLINE void RemoveCurrentAndIncrement ()
Removes the current element from the cache and increments the iterator.
Public Member Functions inherited from TLruCache< KeyType, ValueType, KeyComp >::TBaseIterator< false >
FORCEINLINE TBaseIterator ()
FORCEINLINE KeyType & Key () const
FORCEINLINE operator bool () const
FORCEINLINE bool operator! () const
FORCEINLINE bool operator!= (const TBaseIterator &Rhs) const
ValueType & operator* () const
FORCEINLINE TBaseIterator & operator++ ()
ValueType & operator-> () const
FORCEINLINE bool operator== (const TBaseIterator &Rhs) const
FORCEINLINE ValueType & Value () const
Private Attributes
TLruCache * Cache
Additional Inherited Members
Protected Member Functions inherited from TLruCache< KeyType, ValueType, KeyComp >::TBaseIterator< false >
FCacheEntry * GetCurrentEntry ()
void Increment ()
Detailed Description
template<typename KeyType, typename ValueType, typename KeyComp = DefaultKeyComparer<KeyType>>
class TLruCache< KeyType, ValueType, KeyComp >::TIterator
Cache iterator.
Definition at line 743 of file LruCache.h.
Constructor & Destructor Documentation
TIterator() [1/2]
template<typename KeyType, typename ValueType, typename KeyComp = DefaultKeyComparer<KeyType>> FORCEINLINE TLruCache< KeyType, ValueType, KeyComp >::TIterator::TIterator () inline nodiscard
Definition at line 748 of file LruCache.h.
References TLruCache< KeyType, ValueType, KeyComp >::TBaseIterator< false >::TBaseIterator(), Cache, and FORCEINLINE.
TIterator() [2/2]
template<typename KeyType, typename ValueType, typename KeyComp = DefaultKeyComparer<KeyType>> FORCEINLINE TLruCache< KeyType, ValueType, KeyComp >::TIterator::TIterator (TLruCache & InCache) inline nodiscard
Definition at line 754 of file LruCache.h.
References TLruCache< KeyType, ValueType, KeyComp >::TBaseIterator< false >::TBaseIterator(), TLruCache< KeyType, ValueType, KeyComp >::TLruCache(), Cache, and FORCEINLINE.
Member Function Documentation
RemoveCurrentAndIncrement()
template<typename KeyType, typename ValueType, typename KeyComp = DefaultKeyComparer<KeyType>> FORCEINLINE void TLruCache< KeyType, ValueType, KeyComp >::TIterator::RemoveCurrentAndIncrement () inline
Removes the current element from the cache and increments the iterator.
Definition at line 761 of file LruCache.h.
References Cache, check, FORCEINLINE, TLruCache< KeyType, ValueType, KeyComp >::TBaseIterator< false >::GetCurrentEntry(), and TLruCache< KeyType, ValueType, KeyComp >::TBaseIterator< false >::Increment().
Field Documentation
Cache
template<typename KeyType, typename ValueType, typename KeyComp = DefaultKeyComparer<KeyType>> TLruCache* TLruCache< KeyType, ValueType, KeyComp >::TIterator::Cache private
Definition at line 772 of file LruCache.h.
Referenced by TIterator(), TIterator(), and RemoveCurrentAndIncrement().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Containers/LruCache.h