Unreal Engine 5.6 C++ API: TLockFreeClassAllocator_TLSCache< T, TPaddingForCacheContention > Class Template Reference
TLockFreeClassAllocator_TLSCache< T, TPaddingForCacheContention > Class Template Reference
Thread safe, lock free pooling allocator of memory for instances of T.
#include "LockFreeFixedSizeAllocator.h"
Public Member Functions
void * Allocate ()
Returns a memory block of size sizeof(T).
void Free (T *Item)
Calls a destructor on Item and returns the memory to the free list for recycling.
T * New ()
Returns a new T using the default constructor.
Additional Inherited Members
Private Member Functions inherited from TLockFreeFixedSizeAllocator_TLSCacheBase< SIZE, TLockFreePointerListUnordered< void *, TPaddingForCacheContention >, FNoopCounter >
TLockFreeFixedSizeAllocator_TLSCacheBase ()
~TLockFreeFixedSizeAllocator_TLSCacheBase ()
Destructor, leaks all of the memory.
FORCEINLINE void * Allocate ()
Allocates a memory block of size SIZE.
FORCEINLINE void Free (void *Item)
Puts a memory block previously obtained from Allocate() back on the free list for future use.
const FNoopCounter & GetNumFree () const
Gets the number of allocated memory blocks that are currently unused.
const FNoopCounter & GetNumUsed () const
Gets the number of allocated memory blocks that are currently in use.
Private Member Functions inherited from FNoncopyable
FNoncopyable ()
~FNoncopyable ()
Detailed Description
template<class T, int TPaddingForCacheContention>
class TLockFreeClassAllocator_TLSCache< T, TPaddingForCacheContention >
Thread safe, lock free pooling allocator of memory for instances of T.
Never returns free space until program shutdown.
Definition at line 387 of file LockFreeFixedSizeAllocator.h.
Member Function Documentation
Allocate()
template<class T, int TPaddingForCacheContention> void * TLockFreeClassAllocator_TLSCache< T, TPaddingForCacheContention >::Allocate () inline
Returns a memory block of size sizeof(T).
Returns
Pointer to the allocated memory.
See also
Free, New
Definition at line 396 of file LockFreeFixedSizeAllocator.h.
References Allocate().
Referenced by Allocate(), and New().
Free()
template<class T, int TPaddingForCacheContention> void TLockFreeClassAllocator_TLSCache< T, TPaddingForCacheContention >::Free (T * Item) inline
Calls a destructor on Item and returns the memory to the free list for recycling.
Parameters
Item The item whose memory to free.
See also
Allocate, New
Definition at line 418 of file LockFreeFixedSizeAllocator.h.
References Free(), and Item.
Referenced by Free().
New()
template<class T, int TPaddingForCacheContention> T * TLockFreeClassAllocator_TLSCache< T, TPaddingForCacheContention >::New () inline
Returns a new T using the default constructor.
Returns
Pointer to the new object.
See also
Allocate, Free
Definition at line 407 of file LockFreeFixedSizeAllocator.h.
References Allocate().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Containers/LockFreeFixedSizeAllocator.h