Unreal Engine 5.6 C++ API: TCopyResourceCS< SrcType, DstType, ValueType, NumChannels > Class Template Reference
TCopyResourceCS< SrcType, DstType, ValueType, NumChannels > Class Template Reference
#include "CopyTextureShaders.h"
Public Types
using ShaderMapType = FGlobalShaderMap
using ShaderMetaType = FGlobalShaderType
Public Types inherited from FGlobalShader
using FPermutationParameters = FGlobalShaderPermutationParameters
using ShaderMetaType = FGlobalShaderType
Public Types inherited from FShader
using CompiledShaderInitializerType = FShaderCompiledShaderInitializerType
using FPermutationDomain = FShaderPermutationNone
using FPermutationParameters = FShaderPermutationParameters
using FShaderStatisticMap = TMemoryImageMap<ShaderStatKeyType, FShaderStatVariant>
using ShaderMetaType = FShaderType
using ShaderStatKeyType = FMemoryImageName
Public Member Functions
TCopyResourceCS ()
TCopyResourceCS (const ShaderMetaType::CompiledShaderInitializerType &Initializer)
DECLARE_EXPORTED_TYPE_LAYOUT (TCopyResourceCS, RENDERCORE_API, NonVirtual)
void GetDispatchContext (CopyTextureCS::DispatchContext &OutContext)
Public Member Functions inherited from FCopyTextureCS
void Dispatch (FRHIComputeCommandList &RHICmdList, const CopyTextureCS::DispatchContext &Context, FIntVector const &SrcOffset, FIntVector const &DstOffset, FIntVector const &Dimensions)
const FShaderResourceParameter & GetDstResourceParam ()
const FShaderResourceParameter & GetSrcResourceParam ()
Public Member Functions inherited from FGlobalShader
FGlobalShader ()=default
RENDERCORE_API FGlobalShader (const ShaderMetaType::CompiledShaderInitializerType &Initializer)
template<typename TViewUniformShaderParameters>
void SetParameters (FRHIBatchedShaderParameters &BatchedParameters, FRHIUniformBuffer *ViewUniformBuffer)
Public Member Functions inherited from FShader
RENDERCORE_API FShader ()
Used to construct a shader for deserialization.
RENDERCORE_API FShader (const CompiledShaderInitializerType &Initializer)
Construct a shader from shader compiler output.
RENDERCORE_API ~FShader ()
RENDERCORE_API void DumpDebugInfo (const FShaderMapPointerTable &InPtrTable)
RENDERCORE_API void Finalize (const FShaderMapResourceCode *Code)
RENDERCORE_API const FShaderParametersMetadata * FindAutomaticallyBoundUniformBufferStruct (int32 BaseIndex) const
uint32 GetCodeSize () const
EShaderFrequency GetFrequency () const
RENDERCORE_API const FSHAHash & GetHash () const
Returns the hash of the shader file that this shader was compiled with.
uint32 GetNumInstructions () const
uint32 GetNumTextureSamplers () const
RENDERCORE_API const FSHAHash & GetOutputHash () const
int32 GetResourceIndex () const
EShaderPlatform GetShaderPlatform () const
uint32 GetSortKey () const
Returns an identifier suitable for deterministic sorting of shaders between sessions.
const FShaderTarget GetTarget () const
FShaderType * GetType (const FPointerTableBase *InPointerTable) const
FShaderType * GetType (const FShaderMapPointerTable &InPointerTable) const
FShaderType * GetTypeUnfrozen () const
template<typename UniformBufferStructType>
const TShaderUniformBufferParameter< UniformBufferStructType > & GetUniformBufferParameter () const
Finds an automatically bound uniform buffer matching the given uniform buffer type if one exists, or returns an unbound parameter.
const FShaderUniformBufferParameter & GetUniformBufferParameter (const FHashedName SearchName) const
Finds an automatically bound uniform buffer matching the HashedName if one exists, or returns an unbound parameter.
const FShaderUniformBufferParameter & GetUniformBufferParameter (const FShaderParametersMetadata *SearchStruct) const
Finds an automatically bound uniform buffer matching the given uniform buffer struct if one exists, or returns an unbound parameter.
RENDERCORE_API const FSHAHash & GetVertexFactoryHash () const
FVertexFactoryType * GetVertexFactoryType (const FPointerTableBase *InPointerTable) const
FVertexFactoryType * GetVertexFactoryType (const FShaderMapPointerTable &InPointerTable) const
bool IsFrozen () const
LAYOUT_FIELD (FShaderParameterBindings, Bindings)
LAYOUT_FIELD (FShaderParameterMapInfo, ParameterMapInfo)
RENDERCORE_API void SaveShaderStableKeys (const FShaderMapPointerTable &InPtrTable, EShaderPlatform TargetShaderPlatform, int32 PermutationId, const struct FStableShaderKeyAndValue &SaveKeyVal)
void SetNumInstructions (uint32 Value)
Static Public Member Functions
static FShader * ConstructCompiledInstance (const typename FShader::CompiledShaderInitializerType &Initializer)
static FShader * ConstructSerializedInstance ()
static const TCHAR * GetFunctionName ()
static void GetPermutationIdStringImpl (int32 PermutationId, FString &OutString, bool bFullNames)
static const TCHAR * GetSourceFilename ()
static RENDERCORE_API ShaderMetaType & GetStaticType ()
static void ModifyCompilationEnvironment (const FGlobalShaderPermutationParameters &Parameters, FShaderCompilerEnvironment &OutEnvironment)
static void ModifyCompilationEnvironmentImpl (const FShaderPermutationParameters &Parameters, FShaderCompilerEnvironment &OutEnvironment)
static bool ShouldCompilePermutation (const FGlobalShaderPermutationParameters &Parameters)
static bool ShouldCompilePermutationImpl (const FShaderPermutationParameters &Parameters)
static EShaderPermutationPrecacheRequest ShouldPrecachePermutationImpl (const FShaderPermutationParameters &Parameters)
Static Public Member Functions inherited from FCopyTextureCS
static void ModifyCompilationEnvironment (const FGlobalShaderPermutationParameters &Parameters, FShaderCompilerEnvironment &OutEnvironment)
static TShaderRef< FCopyTextureCS > SelectShader (FGlobalShaderMap *GlobalShaderMap, ECopyTextureResourceType SrcType, ECopyTextureResourceType DstType, ECopyTextureValueType ValueType, CopyTextureCS::DispatchContext &OutContext)
Static Public Member Functions inherited from FGlobalShader
static void ModifyCompilationEnvironment (const FGlobalShaderPermutationParameters &Parameters, FShaderCompilerEnvironment &Environment)
static bool ShouldCompilePermutation (const FShaderPermutationParameters &)
Can be overridden by FShader subclasses to determine whether a specific permutation should be compiled.
static EShaderPermutationPrecacheRequest ShouldPrecachePermutation (const FShaderPermutationParameters &Parameters)
Can be overridden by FShader subclasses to determine whether a specific permutation should be precached.
Static Public Member Functions inherited from FShader
static EShaderCompileJobPriority GetOverrideJobPriority ()
Can be overridden by FShader subclasses to set a custom job priority (EShaderCompileJobPriority) or EShaderCompileJobPriority::None to ignore custom priority.
static ERayTracingPayloadType GetRayTracingPayloadType (const int32 PermutationId)
Can be overriden by FShader subclasses to specify which raytracing payload should be used.
static const FShaderParametersMetadata * GetRootParametersMetadata ()
Returns the meta data for the root shader parameter struct.
static const FShaderBindingLayout * GetShaderBindingLayout (const FShaderPermutationParameters &)
Get shader binding layout used by the shader.
static void ModifyCompilationEnvironment (const FShaderPermutationParameters &, FShaderCompilerEnvironment &)
Can be overridden by FShader subclasses to modify their compile environment just before compilation occurs.
static bool ShouldCompilePermutation (const FShaderPermutationParameters &)
Can be overridden by FShader subclasses to determine whether a specific permutation should be compiled.
static EShaderPermutationPrecacheRequest ShouldPrecachePermutation (const FShaderPermutationParameters &Parameters)
Can be overridden by FShader subclasses to determine whether a specific permutation should be precached.
static bool ValidateCompiledResult (EShaderPlatform InPlatform, const FShaderParameterMap &InParameterMap, TArray< FString > &OutError)
Can be overridden by FShader subclasses to determine whether compilation is valid.
Static Public Attributes
static constexpr uint32 ThreadGroupSizeX = CopyTextureCS::TThreadGroupSize<DstType>::X
static constexpr uint32 ThreadGroupSizeY = CopyTextureCS::TThreadGroupSize<DstType>::Y
static constexpr uint32 ThreadGroupSizeZ = CopyTextureCS::TThreadGroupSize<DstType>::Z
Static Private Attributes
static FShaderTypeRegistration ShaderTypeRegistration
Additional Inherited Members
Protected Member Functions inherited from FCopyTextureCS
FCopyTextureCS ()
FCopyTextureCS (const ShaderMetaType::CompiledShaderInitializerType &Initializer)
LAYOUT_FIELD (FShaderParameter, DimensionsParam)
LAYOUT_FIELD (FShaderParameter, DstOffsetParam)
LAYOUT_FIELD (FShaderParameter, SrcOffsetParam)
LAYOUT_FIELD (FShaderResourceParameter, DstResourceParam)
LAYOUT_FIELD (FShaderResourceParameter, SrcResourceParam)
Protected Member Functions inherited from FShader
LAYOUT_FIELD (TMemoryImageArray< FHashedName >, UniformBufferParameterStructs)
LAYOUT_FIELD (TMemoryImageArray< FShaderUniformBufferParameter >, UniformBufferParameters)
LAYOUT_FIELD_EDITORONLY (FSHAHash, OutputHash)
Hash of the compiled output from this shader and the resulting parameter map.
LAYOUT_FIELD_EDITORONLY (FSHAHash, SourceHash)
Hash of this shader's source files generated at compile time, and stored to allow creating an FShaderId.
LAYOUT_FIELD_EDITORONLY (FSHAHash, VFSourceHash)
Vertex factory source hash, stored so that an FShaderId can be constructed from this shader.
Static Protected Member Functions inherited from FCopyTextureCS
template<typename ShaderType>
static TShaderRef< FCopyTextureCS > SelectShader (FGlobalShaderMap *GlobalShaderMap, CopyTextureCS::DispatchContext &OutContext)
template<ECopyTextureResourceType SrcType>
static TShaderRef< FCopyTextureCS > SelectShader (FGlobalShaderMap *GlobalShaderMap, ECopyTextureResourceType DstType, ECopyTextureValueType ValueType, CopyTextureCS::DispatchContext &OutContext)
template<ECopyTextureResourceType SrcType, ECopyTextureResourceType DstType>
static TShaderRef< FCopyTextureCS > SelectShader (FGlobalShaderMap *GlobalShaderMap, ECopyTextureValueType ValueType, CopyTextureCS::DispatchContext &OutContext)
Detailed Description
template<ECopyTextureResourceType SrcType, ECopyTextureResourceType DstType, ECopyTextureValueType ValueType, uint32 NumChannels>
class TCopyResourceCS< SrcType, DstType, ValueType, NumChannels >
Definition at line 128 of file CopyTextureShaders.h.
Member Typedef Documentation
ShaderMapType
template<ECopyTextureResourceType SrcType, ECopyTextureResourceType DstType, ECopyTextureValueType ValueType, uint32 NumChannels> using TCopyResourceCS< SrcType, DstType, ValueType, NumChannels >::ShaderMapType = FGlobalShaderMap
Definition at line 132 of file CopyTextureShaders.h.
ShaderMetaType
template<ECopyTextureResourceType SrcType, ECopyTextureResourceType DstType, ECopyTextureValueType ValueType, uint32 NumChannels> using TCopyResourceCS< SrcType, DstType, ValueType, NumChannels >::ShaderMetaType = FGlobalShaderType
Definition at line 132 of file CopyTextureShaders.h.
Constructor & Destructor Documentation
TCopyResourceCS() [1/2]
template<ECopyTextureResourceType SrcType, ECopyTextureResourceType DstType, ECopyTextureValueType ValueType, uint32 NumChannels> TCopyResourceCS< SrcType, DstType, ValueType, NumChannels >::TCopyResourceCS () inline
Definition at line 135 of file CopyTextureShaders.h.
Referenced by ConstructCompiledInstance().
TCopyResourceCS() [2/2]
template<ECopyTextureResourceType SrcType, ECopyTextureResourceType DstType, ECopyTextureValueType ValueType, uint32 NumChannels> TCopyResourceCS< SrcType, DstType, ValueType, NumChannels >::TCopyResourceCS (const ShaderMetaType::CompiledShaderInitializerType & Initializer) inline
Definition at line 136 of file CopyTextureShaders.h.
References FCopyTextureCS::FCopyTextureCS().
Member Function Documentation
ConstructCompiledInstance()
template<ECopyTextureResourceType SrcType, ECopyTextureResourceType DstType, ECopyTextureValueType ValueType, uint32 NumChannels> FShader * TCopyResourceCS< SrcType, DstType, ValueType, NumChannels >::ConstructCompiledInstance (const typename FShader::CompiledShaderInitializerType & Initializer) inline static
Definition at line 132 of file CopyTextureShaders.h.
References TCopyResourceCS(), and Global.
ConstructSerializedInstance()
template<ECopyTextureResourceType SrcType, ECopyTextureResourceType DstType, ECopyTextureValueType ValueType, uint32 NumChannels> FShader * TCopyResourceCS< SrcType, DstType, ValueType, NumChannels >::ConstructSerializedInstance () inline static
Definition at line 132 of file CopyTextureShaders.h.
DECLARE_EXPORTED_TYPE_LAYOUT()
template<ECopyTextureResourceType SrcType, ECopyTextureResourceType DstType, ECopyTextureValueType ValueType, uint32 NumChannels> TCopyResourceCS< SrcType, DstType, ValueType, NumChannels >::DECLARE_EXPORTED_TYPE_LAYOUT (TCopyResourceCS< SrcType, DstType, ValueType, NumChannels > , RENDERCORE_API , NonVirtual)
GetDispatchContext()
template<ECopyTextureResourceType SrcType, ECopyTextureResourceType DstType, ECopyTextureValueType ValueType, uint32 NumChannels> void TCopyResourceCS< SrcType, DstType, ValueType, NumChannels >::GetDispatchContext (CopyTextureCS::DispatchContext & OutContext) inline
Definition at line 196 of file CopyTextureShaders.h.
References CopyTextureCS::DispatchContext::DstType, CopyTextureCS::DispatchContext::NumChannels, CopyTextureCS::DispatchContext::SrcType, CopyTextureCS::DispatchContext::ThreadGroupSizeX, ThreadGroupSizeX, CopyTextureCS::DispatchContext::ThreadGroupSizeY, ThreadGroupSizeY, CopyTextureCS::DispatchContext::ThreadGroupSizeZ, ThreadGroupSizeZ, and CopyTextureCS::DispatchContext::ValueType.
GetFunctionName()
template<ECopyTextureResourceType SrcType, ECopyTextureResourceType DstType, ECopyTextureValueType ValueType, uint32 NumChannels> const TCHAR * TCopyResourceCS< SrcType, DstType, ValueType, NumChannels >::GetFunctionName () inline static
Definition at line 145 of file CopyTextureShaders.h.
References TEXT.
GetPermutationIdStringImpl()
template<ECopyTextureResourceType SrcType, ECopyTextureResourceType DstType, ECopyTextureValueType ValueType, uint32 NumChannels> void TCopyResourceCS< SrcType, DstType, ValueType, NumChannels >::GetPermutationIdStringImpl (int32 PermutationId, FString & OutString, bool bFullNames) inline static
Definition at line 132 of file CopyTextureShaders.h.
GetSourceFilename()
template<ECopyTextureResourceType SrcType, ECopyTextureResourceType DstType, ECopyTextureValueType ValueType, uint32 NumChannels> const TCHAR * TCopyResourceCS< SrcType, DstType, ValueType, NumChannels >::GetSourceFilename () inline static
Definition at line 144 of file CopyTextureShaders.h.
References TEXT.
GetStaticType()
template<ECopyTextureResourceType SrcType, ECopyTextureResourceType DstType, ECopyTextureValueType ValueType, uint32 NumChannels> RENDERCORE_API ShaderMetaType & TCopyResourceCS< SrcType, DstType, ValueType, NumChannels >::GetStaticType () static
ModifyCompilationEnvironment()
template<ECopyTextureResourceType SrcType, ECopyTextureResourceType DstType, ECopyTextureValueType ValueType, uint32 NumChannels> void TCopyResourceCS< SrcType, DstType, ValueType, NumChannels >::ModifyCompilationEnvironment (const FGlobalShaderPermutationParameters & Parameters, FShaderCompilerEnvironment & OutEnvironment) inline static
Definition at line 152 of file CopyTextureShaders.h.
References Float, Int32, FCopyTextureCS::ModifyCompilationEnvironment(), FShaderCompilerEnvironment::SetDefine(), TEXT, ThreadGroupSizeX, ThreadGroupSizeY, ThreadGroupSizeZ, and Uint32.
ModifyCompilationEnvironmentImpl()
template<ECopyTextureResourceType SrcType, ECopyTextureResourceType DstType, ECopyTextureValueType ValueType, uint32 NumChannels> void TCopyResourceCS< SrcType, DstType, ValueType, NumChannels >::ModifyCompilationEnvironmentImpl (const FShaderPermutationParameters & Parameters, FShaderCompilerEnvironment & OutEnvironment) inline static
Definition at line 132 of file CopyTextureShaders.h.
ShouldCompilePermutation()
template<ECopyTextureResourceType SrcType, ECopyTextureResourceType DstType, ECopyTextureValueType ValueType, uint32 NumChannels> bool TCopyResourceCS< SrcType, DstType, ValueType, NumChannels >::ShouldCompilePermutation (const FGlobalShaderPermutationParameters & Parameters) inline static
Definition at line 147 of file CopyTextureShaders.h.
References FShaderPermutationParameters::Platform.
ShouldCompilePermutationImpl()
template<ECopyTextureResourceType SrcType, ECopyTextureResourceType DstType, ECopyTextureValueType ValueType, uint32 NumChannels> bool TCopyResourceCS< SrcType, DstType, ValueType, NumChannels >::ShouldCompilePermutationImpl (const FShaderPermutationParameters & Parameters) inline static
Definition at line 132 of file CopyTextureShaders.h.
ShouldPrecachePermutationImpl()
template<ECopyTextureResourceType SrcType, ECopyTextureResourceType DstType, ECopyTextureValueType ValueType, uint32 NumChannels> EShaderPermutationPrecacheRequest TCopyResourceCS< SrcType, DstType, ValueType, NumChannels >::ShouldPrecachePermutationImpl (const FShaderPermutationParameters & Parameters) inline static
Definition at line 132 of file CopyTextureShaders.h.
Field Documentation
ShaderTypeRegistration
template<ECopyTextureResourceType SrcType, ECopyTextureResourceType DstType, ECopyTextureValueType ValueType, uint32 NumChannels> FShaderTypeRegistration TCopyResourceCS< SrcType, DstType, ValueType, NumChannels >::ShaderTypeRegistration static private
Definition at line 132 of file CopyTextureShaders.h.
ThreadGroupSizeX
template<ECopyTextureResourceType SrcType, ECopyTextureResourceType DstType, ECopyTextureValueType ValueType, uint32 NumChannels> uint32 TCopyResourceCS< SrcType, DstType, ValueType, NumChannels >::ThreadGroupSizeX = CopyTextureCS::TThreadGroupSize<DstType>::X static constexpr
Definition at line 140 of file CopyTextureShaders.h.
Referenced by GetDispatchContext(), and ModifyCompilationEnvironment().
ThreadGroupSizeY
template<ECopyTextureResourceType SrcType, ECopyTextureResourceType DstType, ECopyTextureValueType ValueType, uint32 NumChannels> uint32 TCopyResourceCS< SrcType, DstType, ValueType, NumChannels >::ThreadGroupSizeY = CopyTextureCS::TThreadGroupSize<DstType>::Y static constexpr
Definition at line 141 of file CopyTextureShaders.h.
Referenced by GetDispatchContext(), and ModifyCompilationEnvironment().
ThreadGroupSizeZ
template<ECopyTextureResourceType SrcType, ECopyTextureResourceType DstType, ECopyTextureValueType ValueType, uint32 NumChannels> uint32 TCopyResourceCS< SrcType, DstType, ValueType, NumChannels >::ThreadGroupSizeZ = CopyTextureCS::TThreadGroupSize<DstType>::Z static constexpr
Definition at line 142 of file CopyTextureShaders.h.
Referenced by GetDispatchContext(), and ModifyCompilationEnvironment().
The documentation for this class was generated from the following file:
Runtime/RenderCore/Public/CopyTextureShaders.h