Unreal Engine 5.6 C++ API: UE::Geometry::FMeshNormalMapEvaluator Class Reference
UE::Geometry::FMeshNormalMapEvaluator Class Reference
A mesh evaluator for tangent space normals.
#include "MeshNormalMapEvaluator.h"
Public Member Functions
PRAGMA_DISABLE_DEPRECATION_WARNINGS FMeshNormalMapEvaluator ()=default
FMeshNormalMapEvaluator (const FMeshNormalMapEvaluator &)=default
virtual DYNAMICMESH_API const TArray< EComponents > & DataLayout () const override
FMeshNormalMapEvaluator & operator= (const FMeshNormalMapEvaluator &)=default
DYNAMICMESH_API virtual PRAGMA_ENABLE_DEPRECATION_WARNINGS void Setup (const FMeshBaseBaker &Baker, FEvaluationContext &Context) override
Invoked at start of bake to setup this evaluator and return an evaluation context to the baker.
virtual EMeshMapEvaluatorType Type () const override
Public Member Functions inherited from UE::Geometry::FMeshMapEvaluator
virtual ~FMeshMapEvaluator ()=default
Static Public Member Functions
static DYNAMICMESH_API void EvaluateChannel (const int DataIdx, float *&In, float &Out, void *EvalData)
static DYNAMICMESH_API void EvaluateColor (const int DataIdx, float *&In, FVector4f &Out, void *EvalData)
static DYNAMICMESH_API void EvaluateDefault (float *&Out, void *EvalData)
template<bool bUseDetailNormalMap>
static void EvaluateSample (float *&Out, const FCorrespondenceSample &Sample, void *EvalData)
Protected Types
using FNormalTexture = IMeshBakerDetailSampler::FBakeDetailNormalTexture
using FNormalTextureMap = TMap<const void*, FNormalTexture>
Protected Attributes
const TMeshTangents< double > * BaseMeshTangents = nullptr
bool bHasDetailNormalTextures = false
FVector3f DefaultNormal = FVector3f::UnitZ()
FNormalTextureMap DetailNormalMaps
const IMeshBakerDetailSampler * DetailSampler = nullptr
Private Member Functions
template<bool bUseDetailNormalMap>
FVector3f SampleFunction (const FCorrespondenceSample &SampleData) const
Additional Inherited Members
Public Types inherited from UE::Geometry::FMeshMapEvaluator
enum class EAccumulateMode { Add , Overwrite , Last }
Accumulate mode informs the baker how samples should be accumulated into the buffer.
enum class EComponents { Float1 = 1 , Float2 = 2 , Float3 = 3 , Float4 = 4 }
The number of float components of an evaluator result/target.
Static Protected Member Functions inherited from UE::Geometry::FMeshMapEvaluator
static void WriteToBuffer (float *&Out, const float Data)
Write float data to a float buffer and increment.
static void WriteToBuffer (float *&Out, const FVector2f &Data)
Write FVector2f data to a float buffer and increment.
static void WriteToBuffer (float *&Out, const FVector3f &Data)
Write FVector3f data to a float buffer and increment.
static void WriteToBuffer (float *&Out, const FVector4f &Data)
Write FVector4f data to a float buffer and increment.
Detailed Description
A mesh evaluator for tangent space normals.
Definition at line 21 of file MeshNormalMapEvaluator.h.
Member Typedef Documentation
FNormalTexture
using UE::Geometry::FMeshNormalMapEvaluator::FNormalTexture = IMeshBakerDetailSampler::FBakeDetailNormalTexture protected
Definition at line 50 of file MeshNormalMapEvaluator.h.
FNormalTextureMap
using UE::Geometry::FMeshNormalMapEvaluator::FNormalTextureMap = TMap<const void*, FNormalTexture> protected
Definition at line 51 of file MeshNormalMapEvaluator.h.
Constructor & Destructor Documentation
FMeshNormalMapEvaluator() [1/2]
PRAGMA_DISABLE_DEPRECATION_WARNINGS UE::Geometry::FMeshNormalMapEvaluator::FMeshNormalMapEvaluator () default
Referenced by FMeshNormalMapEvaluator(), and operator=().
FMeshNormalMapEvaluator() [2/2]
UE::Geometry::FMeshNormalMapEvaluator::FMeshNormalMapEvaluator (const FMeshNormalMapEvaluator &) default
References FMeshNormalMapEvaluator().
Member Function Documentation
DataLayout()
virtual DYNAMICMESH_API const TArray< EComponents > & UE::Geometry::FMeshNormalMapEvaluator::DataLayout () const override virtual
Returns
the data layout of the evaluator
Implements UE::Geometry::FMeshMapEvaluator.
References UE_API.
EvaluateChannel()
DYNAMICMESH_API void UE::Geometry::FMeshNormalMapEvaluator::EvaluateChannel (const int DataIdx, float *& In, float & Out, void * EvalData) static
References UE_API.
EvaluateColor()
DYNAMICMESH_API void UE::Geometry::FMeshNormalMapEvaluator::EvaluateColor (const int DataIdx, float *& In, FVector4f & Out, void * EvalData) static
References UE_API.
EvaluateDefault()
DYNAMICMESH_API void UE::Geometry::FMeshNormalMapEvaluator::EvaluateDefault (float *& Out, void * EvalData) static
References UE_API.
EvaluateSample()
template<bool bUseDetailNormalMap> void UE::Geometry::FMeshNormalMapEvaluator::EvaluateSample (float *& Out, const FCorrespondenceSample & Sample, void * EvalData) static
operator=()
FMeshNormalMapEvaluator & UE::Geometry::FMeshNormalMapEvaluator::operator= (const FMeshNormalMapEvaluator &) default
References FMeshNormalMapEvaluator(), PRAGMA_ENABLE_DEPRECATION_WARNINGS, and UE_API.
SampleFunction()
template<bool bUseDetailNormalMap> FVector3f UE::Geometry::FMeshNormalMapEvaluator::SampleFunction (const FCorrespondenceSample & SampleData) const private
Setup()
DYNAMICMESH_API virtual PRAGMA_ENABLE_DEPRECATION_WARNINGS void UE::Geometry::FMeshNormalMapEvaluator::Setup (const FMeshBaseBaker & Baker, FEvaluationContext & Context) override virtual
Invoked at start of bake to setup this evaluator and return an evaluation context to the baker.
The evaluation context indicates to the baker how the evaluator should be invoked. See FEvaluationContext for more details.
Parameters
Baker the baker that owns this evaluator.
Context [out] the evaluation context.
Implements UE::Geometry::FMeshMapEvaluator.
Type()
virtual EMeshMapEvaluatorType UE::Geometry::FMeshNormalMapEvaluator::Type () const inline override virtual
Returns
the type of evaluator.
Implements UE::Geometry::FMeshMapEvaluator.
Definition at line 35 of file MeshNormalMapEvaluator.h.
References UE::Geometry::Normal.
Field Documentation
BaseMeshTangents
const TMeshTangents<double>* UE::Geometry::FMeshNormalMapEvaluator::BaseMeshTangents = nullptr protected
Definition at line 55 of file MeshNormalMapEvaluator.h.
bHasDetailNormalTextures
bool UE::Geometry::FMeshNormalMapEvaluator::bHasDetailNormalTextures = false protected
Definition at line 54 of file MeshNormalMapEvaluator.h.
DefaultNormal
FVector3f UE::Geometry::FMeshNormalMapEvaluator::DefaultNormal = FVector3f::UnitZ() protected
Definition at line 57 of file MeshNormalMapEvaluator.h.
DetailNormalMaps
FNormalTextureMap UE::Geometry::FMeshNormalMapEvaluator::DetailNormalMaps protected
Definition at line 52 of file MeshNormalMapEvaluator.h.
DetailSampler
const IMeshBakerDetailSampler* UE::Geometry::FMeshNormalMapEvaluator::DetailSampler = nullptr protected
Definition at line 48 of file MeshNormalMapEvaluator.h.
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/GeometryProcessing/Source/DynamicMesh/Public/Sampling/MeshNormalMapEvaluator.h