Unreal Engine 5.6 C++ API: FObjectPostSaveRootContext Class Reference
FObjectPostSaveRootContext Class Reference
Interface used by PostSaveRoot to access the save parameters.
#include "ObjectSaveContext.h"
Public Member Functions
FObjectPostSaveRootContext (const FObjectPostSaveRootContext &Other)
FObjectPostSaveRootContext (FObjectSaveContextData &InData)
bool IsCleanupRequired () const
Return whether PreSaveRoot indicated PostSaveRoot needs to take extra cleanup steps.
Public Member Functions inherited from FObjectPostSaveContext
FObjectPostSaveContext (const FObjectPostSaveContext &Other)
FObjectPostSaveContext (FObjectSaveContextData &InData)
UE::Cook::ECookingDLC GetCookingDLC () const
UE::Cook::ECookType GetCookType () const
uint32 GetOriginalPackageFlags () const
Package->GetPackageFlags before the save, or 0 if no package.
EObjectSaveContextPhase GetPhase () const
Return which phase of SavePackage callbacks are active.
uint32 GetSaveFlags () const
Return the save flags (ESaveFlags) of the save.
const TCHAR * GetTargetFilename () const
The target Filename being saved into (not the temporary file for saving).
const ITargetPlatform * GetTargetPlatform () const
Return the targetplatform of the save, if cooking.
bool IsCookByTheBook () const
bool IsCooking () const
Report whether this is a save into a target-specific cooked format.
bool IsCookOnTheFly () const
bool IsCookTypeUnknown () const
bool IsLastConcurrentSave () const
Always true normally.
bool IsProceduralSave () const
Return whether the package is being saved due to a procedural save.
bool IsUpdatingLoadedPath () const
Return whether LoadedPath of the package being saved is being updated.
bool SaveSucceeded () const
Return whether the Save was successful.
Additional Inherited Members
Protected Attributes inherited from FObjectPostSaveContext
FObjectSaveContextData & Data
Detailed Description
Interface used by PostSaveRoot to access the save parameters.
Definition at line 538 of file ObjectSaveContext.h.
Constructor & Destructor Documentation
FObjectPostSaveRootContext() [1/2]
FObjectPostSaveRootContext::FObjectPostSaveRootContext (FObjectSaveContextData & InData) inline explicit
Definition at line 541 of file ObjectSaveContext.h.
References FObjectPostSaveContext::FObjectPostSaveContext().
Referenced by FObjectPostSaveRootContext().
FObjectPostSaveRootContext() [2/2]
FObjectPostSaveRootContext::FObjectPostSaveRootContext (const FObjectPostSaveRootContext & Other) inline
Definition at line 546 of file ObjectSaveContext.h.
References FObjectPostSaveContext::FObjectPostSaveContext(), FObjectPostSaveRootContext(), FObjectPostSaveContext::Data, and Other.
Member Function Documentation
IsCleanupRequired()
bool FObjectPostSaveRootContext::IsCleanupRequired () const inline
Return whether PreSaveRoot indicated PostSaveRoot needs to take extra cleanup steps.
Definition at line 552 of file ObjectSaveContext.h.
References FObjectPostSaveContext::Data.
The documentation for this class was generated from the following file:
Runtime/CoreUObject/Public/UObject/ObjectSaveContext.h