Unreal Engine 5.6 C++ API: FArenaPointer Class Reference
FArenaPointer Class Reference
Tagged Arena Pointer.
#include "MemoryArena.h"
Public Types
enum { NoTag = 0 }
Public Member Functions
FArenaPointer ()=default
FArenaPointer (void *Ptr, uint16 ArenaIndex)
FMemoryArena & Arena () const
void Free () const
FORCEINLINE const uint16 GetArenaIndex () const
FORCEINLINE void * GetPointer ()
FORCEINLINE const void * GetPointer () const
operator bool () const
FORCEINLINE void SetPointerAndArena (void *InPtr, uint16 InArenaTag)
Private Attributes
void * TaggedPointer = nullptr
Static Private Attributes
static constexpr uint64 ArenaMask = 0xffff000000000000
static constexpr int ArenaShift = 48
static constexpr uint64 PointerMask = 0x0000ffffFFFFffff
Detailed Description
Tagged Arena Pointer.
Stores an arena ID alongside a pointer. On 64-bit architectures the arena ID can be encoded in the otherwise unused MSB part of the pointer for zero memory overhead vs a regular pointer. For 32-bit architectures the arena ID is stored in a separate member.
A null pointer can still have an arena ID, which is useful for cases where you have a container that starts out empty but still want to track which arena should be used for subsequent allocations.
Definition at line 41 of file MemoryArena.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
NoTag
Definition at line 46 of file MemoryArena.h.
Constructor & Destructor Documentation
FArenaPointer() [1/2]
FArenaPointer::FArenaPointer () default
Referenced by TArenaPointer< T >::TArenaPointer().
FArenaPointer() [2/2]
FArenaPointer::FArenaPointer (void * Ptr, uint16 ArenaIndex) inline
Definition at line 76 of file MemoryArena.h.
References ArenaShift, and TaggedPointer.
Member Function Documentation
Arena()
FMemoryArena & FArenaPointer::Arena () const
Referenced by Free().
Free()
void FArenaPointer::Free () const inline
Definition at line 133 of file MemoryArena.h.
References Arena(), FMemoryArena::Free(), and GetPointer().
GetArenaIndex()
FORCEINLINE const uint16 FArenaPointer::GetArenaIndex () const inline
Definition at line 71 of file MemoryArena.h.
References ArenaShift, FORCEINLINE, and TaggedPointer.
GetPointer() [1/2]
FORCEINLINE void * FArenaPointer::GetPointer () inline
Definition at line 72 of file MemoryArena.h.
References FORCEINLINE, PointerMask, and TaggedPointer.
Referenced by Free(), operator bool(), TArenaPointer< T >::operator const T *(), TArenaPointer< T >::operator T*(), TArenaPointer< T >::operator->(), and TArenaPointer< T >::operator->().
GetPointer() [2/2]
FORCEINLINE const void * FArenaPointer::GetPointer () const inline
Definition at line 73 of file MemoryArena.h.
References FORCEINLINE, PointerMask, and TaggedPointer.
operator bool()
FArenaPointer::operator bool () const inline
Definition at line 79 of file MemoryArena.h.
References GetPointer().
SetPointerAndArena()
FORCEINLINE void FArenaPointer::SetPointerAndArena (void * InPtr, uint16 InArenaTag) inline
Definition at line 74 of file MemoryArena.h.
References ArenaShift, FORCEINLINE, and TaggedPointer.
Referenced by TArenaPointer< T >::operator=().
Field Documentation
ArenaMask
uint64 FArenaPointer::ArenaMask = 0xffff000000000000 static constexpr private
Definition at line 65 of file MemoryArena.h.
ArenaShift
int FArenaPointer::ArenaShift = 48 static constexpr private
Definition at line 64 of file MemoryArena.h.
Referenced by FArenaPointer(), GetArenaIndex(), and SetPointerAndArena().
PointerMask
uint64 FArenaPointer::PointerMask = 0x0000ffffFFFFffff static constexpr private
Definition at line 66 of file MemoryArena.h.
Referenced by GetPointer(), and GetPointer().
TaggedPointer
void* FArenaPointer::TaggedPointer = nullptr private
Definition at line 68 of file MemoryArena.h.
Referenced by FArenaPointer(), GetArenaIndex(), GetPointer(), GetPointer(), and SetPointerAndArena().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Memory/MemoryArena.h