Unreal Engine 5.6 C++ API: FArchiveProxy Class Reference
FArchiveProxy Class Reference
Base class for archive proxies.
#include "ArchiveProxy.h"
Public Member Functions
FArchiveProxy (const FArchiveProxy &)=delete
FArchiveProxy (FArchive &InInnerArchive)
Creates and initializes a new instance of the archive proxy.
FArchiveProxy (FArchiveProxy &&)=delete
~FArchiveProxy ()
virtual bool AtEnd () override
Returns true if the current location within the backing data storage is at the end, always returns false if there is no storage.
virtual void AttachBulkData (UObject *Owner, FBulkData *BulkData) override
Attaches/ associates the passed in bulk data object with the linker.
virtual bool AttachExternalReadDependency (FExternalReadCallback &ReadCallback) override
Adds external read dependency.
virtual bool Close () override
Attempts to close and finalize any handles used for backing data storage, returns true if it succeeded.
virtual void CountBytes (SIZE_T InNum, SIZE_T InMax) override
Called to get the computed size from a size-detecting archive after it has finished serializing.
virtual void DetachBulkData (FBulkData *BulkData, bool bEnsureBulkDataIsLoaded) override
Detaches the passed in bulk data object from the linker.
virtual void Flush () override
Attempts to finish writing any buffered data to disk/permanent storage.
virtual void FlushCache () override
Flushes cache and frees internal data.
virtual void ForceBlueprintFinalization () override
Inform the archive that a blueprint would like to force finalization, normally this is triggered by CDO load, but if there's no CDO we force finalization.
virtual UObject * GetArchetypeFromLoader (const UObject *Obj) override
Called to retrieve the archetype from the event driven loader.
virtual FString GetArchiveName () const override
Returns the name of the Archive.
virtual FArchive * GetCacheableArchive () override
Returns a pointer to an archive that represents the same data that the current archive covers, but that can be cached and reused later In the case of standard archives, this function will just return a pointer to itself.
virtual const FCustomVersionContainer & GetCustomVersions () const override
Gets the custom version numbers for this archive.
virtual::FArchiveState & GetInnermostState () override
Returns lowest level archive state, proxy archives will override this.
virtual FLinker * GetLinker () override
If this archive is a FLinkerLoad or FLinkerSave, returns a pointer to the ULinker portion.
virtual FORCEINLINE bool IsProxyOf (FArchive *InOther) const
Determine if the given archive is a valid "child" of this archive.
virtual void MarkScriptSerializationEnd (const UObject *Obj) override
Called when an object stops serializing property data using script serialization.
virtual void MarkScriptSerializationStart (const UObject *Obj) override
Called when an object begins serializing property data using script serialization.
virtual void MarkSearchableName (const TObjectPtr< const UObject > &TypeObject, const FName &ValueName) const override
Called to register a reference to a specific name value, of type TypeObject (UEnum or UStruct normally).
virtual FArchive & operator<< (FField *&Value) override
Serializes a Field value from or into this archive.
virtual FArchive & operator<< (FLazyObjectPtr &Value) override
Serializes a lazy object pointer value from or into this archive.
virtual FArchive & operator<< (FName &Value) override
Serializes an FName value from or into this archive.
virtual FArchive & operator<< (FObjectPtr &Value) override
Serializes a wrapped object pointer value from or into this archive.
virtual FArchive & operator<< (FSoftObjectPath &Value) override
Serializes soft object paths from or into this archive.
virtual FArchive & operator<< (FSoftObjectPtr &Value) override
Serializes asset pointer from or into this archive.
virtual FArchive & operator<< (FText &Value) override
Serializes an FText value from or into an archive.
virtual FArchive & operator<< (FWeakObjectPtr &Value) override
Serializes FWeakObjectPtr value from or into this archive.
virtual FArchive & operator<< (UObject *&Value) override
Serializes an UObject value from or into this archive.
FArchiveProxy & operator= (const FArchiveProxy &)=delete
FArchiveProxy & operator= (FArchiveProxy &&)=delete
virtual void PopDebugDataString () override
virtual FORCEINLINE void PopSerializedProperty (class FProperty *InProperty, const bool bIsEditorOnlyProperty)
Pops editor-only marker from the stack of currently serialized properties.
virtual bool Precache (int64 PrecacheOffset, int64 PrecacheSize) override
Hint the archive that the region starting at passed in offset and spanning the passed in size is going to be read soon and should be precached.
virtual void Preload (UObject *Object) override
Tells the archive to attempt to preload the specified object so data can be loaded out of it.
virtual void PushDebugDataString (const FName &DebugData) override
Debug stack storage if you want to add data to the archive for usage further down the serialization stack this should be used in conjunction with the FScopeAddDebugData struct.
virtual FORCEINLINE void PushSerializedProperty (class FProperty *InProperty, const bool bIsEditorOnlyProperty)
Pushes editor-only marker to the stack of currently serialized properties.
virtual void ResetCustomVersions () override
Resets the custom version numbers for this archive.
virtual void Seek (int64 InPos) override
Attempts to set the current offset into backing data storage, this will do nothing if there is no storage.
virtual void Serialize (void *V, int64 Length) override
virtual void SerializeBits (void *Bits, int64 LengthBits) override
virtual bool SerializeBulkData (FBulkData &BulkData, const FBulkDataSerializationParams &Params) override
Serialize bulk data.
virtual void SerializeInt (uint32 &Value, uint32 Max) override
virtual void SerializeIntPacked (uint32 &Value) override
Packs int value into bytes of 7 bits with 8th bit for 'more'.
virtual bool SetCompressionMap (TArray< FCompressedChunk > *CompressedChunks, ECompressionFlags CompressionFlags) override
Sets mapping from offsets/ sizes that are going to be used for seeking and serialization to what is actually stored on disk.
virtual void SetCustomVersions (const FCustomVersionContainer &NewVersions) override
Sets the custom version numbers for this archive.
virtual void SetDebugSerializationFlags (uint32 InCustomFlags) override
Sets the archives custom serialization modifier flags (nothing to do with PortFlags or Custom versions)
virtual void SetFilterEditorOnly (bool InFilterEditorOnly) override
Sets a flag indicating that this archive needs to filter editor-only content.
FORCEINLINE void SetSerializedProperty (FProperty *InProperty) override
Overrides the property that is currently being serialized.
void SetSerializedPropertyChain (const FArchiveSerializedPropertyChain *InSerializedPropertyChain, class FProperty *InSerializedPropertyOverride=nullptr) override
Set the raw serialized property chain for this archive, optionally overriding the serialized property too (or null to use the head of the property chain)
virtual bool ShouldSkipProperty (const FProperty *InProperty) const override
Checks whether the archive wants to skip the property independent of the other flags.
virtual int64 Tell () override
Returns the current location within the backing data storage, which can possibly be passed to Seek later to restore a read/write location.
virtual int64 TotalSize () override
Returns total size of the backing data storage.
virtual bool UseToResolveEnumerators () const override
Checks whether the archive is used to resolve out-of-date enum indexes If function returns true, the archive should be called only for objects containing user defined enum.
Public Member Functions inherited from FArchive
FArchive ()=default
FArchive (const FArchive &)=default
virtual ~FArchive ()
virtual void AttachBulkData (UE::Serialization::FEditorBulkData *BulkData)
FORCEINLINE FArchive & ByteOrderSerialize (void *V, int32 Length)
Serialize data of Length bytes, taking into account byte swapping if needed.
void ByteSwap (void *V, int32 Length)
Used to do byte swapping on small items.
void ClearError ()
Sets ArIsError to false, this does not clear any CriticalErrors.
FORCEINLINE bool ContainsCode () const
Returns true if this archive contains native or generated code.
FORCEINLINE bool ContainsMap () const
Returns true if this archive contains a ULevel or UWorld object.
FORCEINLINE const ITargetPlatform * CookingTarget () const
Returns the cooking target platform.
int32 CustomVer (const struct FGuid &Key) const
Queries a custom version from the archive.
virtual void DetachBulkData (UE::Serialization::FEditorBulkData *BulkData, bool bEnsureBulkDataIsLoaded)
FORCEINLINE bool DoDelta () const
Returns true if this archive should handle delta serialization for properties.
FORCEINLINE bool DoIntraPropertyDelta () const
Returns true if this archive should perform delta serialization within properties (e.g.
virtual uint32 EngineNetVer () const
Returns the engine-global network protocol version for this archive.
FORCEINLINE FEngineVersionBase EngineVer () const
Returns the compiled engine version used for this archive.
template<SIZE_T Size>
FORCEINLINE bool FastPathLoad (void *InDest)
FORCEINLINE bool ForceByteSwapping () const
Returns true if this archive should always swap bytes, ignoring endian rules.
virtual uint32 GameNetVer () const
Returns the game-specific network protocol version for this archive.
FArchiveState & GetArchiveState ()
Returns the low level archive state for this archive.
const FArchiveState & GetArchiveState () const
FORCEINLINE FArchiveCookContext * GetCookContext ()
FORCEINLINE uint32 GetDebugSerializationFlags () const
Returns the editor-only debug serialization flags.
FORCEINLINE bool GetError () const
FORCEINLINE int64 GetMaxSerializeSize () const
Returns the maximum size of data that this archive is allowed to serialize.
virtual const FUObjectMigrationContext * GetMigrationContext () const
When migrating objects, we may need some context as to the intent of the migration during serialization.
FORCEINLINE uint32 GetPortFlags () const
Returns this archive's property serialization modifier flags.
FArchiveSavePackageData * GetSavePackageData ()
FORCEINLINE class FProperty * GetSerializedProperty () const
Gets the property that is currently being serialized.
FORCEINLINE const FArchiveSerializedPropertyChain * GetSerializedPropertyChain () const
Get the raw serialized property chain for this archive.
void GetSerializedPropertyChain (TArray< class FProperty * > &OutProperties) const
Gets the chain of properties that are currently being serialized.
FORCEINLINE bool HasAllPortFlags (uint32 Flags) const
Checks to see if all of the passed in property serialization modifier flags are set.
FORCEINLINE bool HasAnyPortFlags (uint32 Flags) const
Checks to see if any of the passed in property serialization modifier flags are set.
FORCEINLINE bool IsAllowingLazyLoading () const
Returns true if this archive sould allow lazy loading of bulk / secondary data.
FORCEINLINE bool IsByteSwapping ()
Returns true if data larger than 1 byte should be swapped to deal with endian mismatches.
FORCEINLINE bool IsCooking () const
Checks whether the archive is used for cooking.
FORCEINLINE bool IsCountingMemory () const
Returns true if this archive is counting memory, normally CountBytes is called to get the size.
FORCEINLINE bool IsCriticalError () const
Returns true if this archive contains critical errors that cannot be recovered from.
FORCEINLINE bool IsError () const
Returns true if this archive contains errors, which means that further serialization is generally not safe.
bool IsFilterEditorOnly () const
Indicates whether this archive is filtering editor-only on save or contains data that had editor-only content stripped.
FORCEINLINE bool IsForcingUnicode () const
Returns true if this archive wants to always save strings in UTF16 format even if they are ANSI characters.
FORCEINLINE bool IsIgnoringArchetypeRef () const
Returns true if this archive should ignore archetype references for structs and classes.
FORCEINLINE bool IsIgnoringClassGeneratedByRef () const
Returns true if this archive should ignore the ClassGeneratedBy reference in UClass.
FORCEINLINE bool IsIgnoringClassRef () const
Returns true if this archive should ignore the Class reference in UObject.
FORCEINLINE bool IsIgnoringOuterRef () const
Returns true if this archive should ignore the Outer reference in UObject.
FORCEINLINE bool IsLoading () const
Returns true if this archive is for loading data.
FORCEINLINE bool IsLoadingFromCookedPackage () const
Returns true if this archive is loading from a cooked package.
FORCEINLINE constexpr bool IsMigratingRemoteObjects () const
Returns true if this Archive is migrating remote object.
FORCEINLINE bool IsModifyingWeakAndStrongReferences () const
Returns true if this archive should modify/search weak object references as well as strong ones.
FORCEINLINE bool IsNetArchive () const
Whether or not this archive is serializing data being sent/received by the netcode.
FORCEINLINE bool IsObjectReferenceCollector () const
Returns true if this archive is only looking for UObject references.
FORCEINLINE bool IsPersistent () const
Returns true if this archive is saving or loading data destined for persistent storage and should skip transient data.
bool IsSaveGame () const
Indicates whether this archive is saving or loading game state.
FORCEINLINE bool IsSaving () const
Returns true if this archive is for saving data, this can also be a pre-save preparation archive.
FORCEINLINE bool IsSerializingDefaults () const
Returns true if this archive is currently serializing class/struct default values.
FORCEINLINE bool IsTextFormat () const
Returns true if this archive serializes to a structured text format.
FORCEINLINE bool IsTransacting () const
Returns true if this archive is transacting, which is used to keep track of changes to objects for things like the editor undo system.
FORCEINLINE int32 LicenseeUEVer () const
Returns the licensee-specific version used for this archive, will be 0 by default.
template<typename FmtType, typename... Types>
void Logf (const FmtType &Fmt, Types... Args)
template<class T>
FORCEINLINE FArchive & operator<< (TCheckedObjPtr< T > &Value)
Serializes a UObject wrapped in a TCheckedObjPtr container, using the above operator, and verifies the serialized object is derived from the correct base class, to prevent illegal casting.
FArchive & operator= (const FArchive &ArchiveToCopy)=default
virtual void PopFileRegionType ()
virtual void PushFileRegionType (EFileRegionType Type)
Called whilst cooking to provide file region hints to the cooker.
FORCEINLINE bool RequiresLocalizationGather () const
Returns true if this archive contains data required to be gathered for localization.
virtual void Reset ()
Resets all of the base archive members.
void SerializeCompressed (void *V, int64 Length, FName CompressionFormatCannotChange, ECompressionFlags Flags=COMPRESS_NoFlags, bool bTreatBufferAsFileReader=false)
Serializes and compresses/ uncompresses data.
void SerializeCompressedNew (void *V, int64 Length)
Serializes and compresses/ uncompresses data with default compressor choices.
void SerializeCompressedNew (void *V, int64 Length, FName CompressionFormatToEncode, FName CompressionFormatToDecodeOldV1Files, ECompressionFlags Flags=COMPRESS_NoFlags, bool bTreatBufferAsFileReader=false, int64 *OutPartialReadLength=nullptr)
Serializes and compresses/ uncompresses data.
virtual void SerializeIntPacked64 (uint64 &Value)
void SetArchiveState (const FArchiveState &InState)
Modifies current archive state, can be used to override flags.
void SetByteSwapping (bool Enabled)
Toggle byte order swapping.
void SetCriticalError ()
Sets the archiver IsCriticalError and IsError to true.
void SetCustomVersion (const struct FGuid &Key, int32 Version, FName FriendlyName)
Sets a specific custom version.
virtual void SetEngineNetVer (const uint32 InEngineNetVer)
Sets the archive engine network version.
virtual void SetEngineVer (const FEngineVersionBase &InVer)
Sets the archive engine version.
void SetError ()
Sets ArIsError to true.
virtual void SetForceUnicode (bool bInForceUnicode)
Sets whether this archive wants to force saving as Unicode.
virtual void SetGameNetVer (const uint32 InGameNetVer)
Sets the archive game network version.
virtual void SetIsLoading (bool bInIsLoading)
Sets whether this archive is for loading data.
virtual void SetIsLoadingFromCookedPackage (bool bInIsLoadingFromCookedPackage)
Sets whether the archive is loading from a cooked package.
virtual void SetIsPersistent (bool bInIsPersistent)
Sets whether this archive is to persistent storage.
virtual void SetIsSaving (bool bInIsSaving)
Sets whether this archive is for saving data.
virtual void SetIsTextFormat (bool bInIsTextFormat)
Sets whether this archive is in text format.
virtual void SetIsTransacting (bool bInIsTransacting)
Sets whether this archive is for transacting.
virtual void SetLicenseeUEVer (int32 InVer)
Sets the archive licensee version number.
void SetMigratingRemoteObjects (bool bMigrating)
If set true, this archive is migrating remote objects.
void SetPortFlags (uint32 InPortFlags)
Sets the archive's property serialization modifier flags.
void SetSavePackageData (FArchiveSavePackageData *InSavePackageData)
Marks that this archive is one of the archives used by SavePackage, and provides access to data and functions used only during savepackage, such as the cook data bundle for information about the cook being conducted (if applicable) and writing build dependencies for assetregistry.
void SetShouldSkipUpdateCustomVersion (bool bShouldSkip)
If set true, UsingCurrentVersion will not query the version registry to get the latest version data for the key if the version key is already set in the local container.
virtual void SetUEVer (FPackageFileVersion InVer)
Sets the archive version number.
virtual void SetUseUnversionedPropertySerialization (bool bInUseUnversioned)
Sets whether tagged property serialization should be replaced by faster unversioned serialization.
virtual void SetWantBinaryPropertySerialization (bool bInWantBinaryPropertySerialization)
Sets whether this archive wants binary property serialization.
FORCEINLINE bool ShouldSkipBulkData () const
Returns true if this archive should ignore bulk data.
FORCEINLINE bool ShouldSkipCompilingAssets () const
Returns true if it is allowed to skip serialization on assets still being compiled to avoid waiting unless strictly necessary.
FORCEINLINE bool ShouldSkipUpdateCustomVersion () const
Returns true if this Archive does not update the custom version data for a given key if has already been set previously in the local custom versions container.
void StartSerializingDefaults ()
Sets a flag indicating that this archive is currently serializing class/struct defaults.
void StopSerializingDefaults ()
Indicate that this archive is no longer serializing class/struct defaults.
void ThisContainsCode ()
Sets a flag indicating that this archive contains native or generated code.
void ThisContainsMap ()
Sets a flag indicating that this archive contains a ULevel or UWorld object.
void ThisRequiresLocalizationGather ()
Sets a flag indicating that this archive contains data required to be gathered for localization.
UE_DEPRECATED (5.5, "Use GetCookContext or CookingTarget or GetSavePackageData") FArchiveCookData *GetCookData()
UE_DEPRECATED (5.5, "Use SetSavePackageData.") void SetCookData(FArchiveCookData *InCookData)
FORCEINLINE FPackageFileVersion UEVer () const
Returns the global engine serialization version used for this archive.
FORCEINLINE bool UseUnversionedPropertySerialization () const
Returns true if tagged property serialization should be replaced by faster unversioned serialization.
virtual void UsingCustomVersion (const struct FGuid &Guid)
Registers the custom version to the archive.
FORCEINLINE bool WantBinaryPropertySerialization () const
Returns true if this archive wants properties to be serialized in binary form instead of safer but slower tagged form.
Protected Attributes
FArchive & InnerArchive
Holds the archive that this archive is a proxy to.
Additional Inherited Members
Data Fields inherited from FArchive
FFastPathLoadBuffer * ActiveFPLB
uint8 ArAllowLazyLoading: 1
Whether to allow lazy loading of bulk/secondary data.
uint8 ArContainsCode: 1
Quickly tell if an archive contains script code.
uint8 ArContainsMap: 1
Used to determine whether FArchive contains a level or world.
const struct FCustomPropertyListNode * ArCustomPropertyList
Custom property list attribute.
uint32 ArDebugSerializationFlags
Custom serialization modifier flags can be used for anything.
UE_DEPRECATED(5.6, "Public access to ArRequiresLocalizationGather has been deprecated - please use Ar.RequiresLocalizationGather() and Ar.ThisRequiresLocalizationGather() for getting and setting respectively.") uint8 ArRequiresLocalizationGather uint8 ArForceByteSwapping: 1
Used to determine whether FArchive contains data required to be gathered for localization.
uint8 ArIgnoreArchetypeRef: 1
If true, we will not serialize archetype references for structs and classes.
uint8 ArIgnoreClassGeneratedByRef: 1
If true, we will not serialize ClassGeneratedBy reference in UClass.
uint8 ArIgnoreClassRef: 1
If true, UObject::Serialize will skip serialization of the Class property.
uint8 ArIgnoreOuterRef: 1
If true, we will not serialize the Outer reference in UObject.
uint8 ArIsCountingMemory: 1
Whether this archive is counting memory.
uint8 ArIsFilterEditorOnly: 1
Whether editor only properties are being filtered from the archive (or has been filtered).
uint8 ArIsModifyingWeakAndStrongReferences: 1
Whether a reference collector is modifying the references and wants both weak and strong ones.
uint8 ArIsNetArchive: 1
Whether or not this archive is sending/receiving network data.
uint8 ArIsObjectReferenceCollector: 1
Whether this archive only cares about serializing object references.
uint8 ArIsSaveGame: 1
Whether this archive is saving/loading game state.
int64 ArMaxSerializeSize
Max size of data that this archive is allowed to serialize.
uint8 ArMergeOverrides: 1
Set to false if OverriddenProperties should be cleared at the beginning of SerializeVersionedTaggedProperties.
uint8 ArNoDelta: 1
If true, do not perform delta serialization of properties.
uint8 ArNoIntraPropertyDelta: 1
If true, do not perform delta serialization within properties (e.g.
uint32 ArPortFlags
Modifier flags that be used when serializing UProperties.
uint8 ArPreserveArrayElements: 1
Set TRUE to stop arrays from being cleared before they're loaded.
int32 ArSerializingDefaults
Whether we are currently serializing defaults.
uint8 ArShouldSkipBulkData: 1
Whether bulk data serialization should be skipped or not.
uint8 ArUseCustomPropertyList: 1
Set TRUE to use the custom property list attribute for serialization.
FFastPathLoadBuffer InlineFPLB
Protected Member Functions inherited from FArchive
virtual void SerializeBool (bool &D)
Serializes a Boolean value from or into an archive.
void SetShouldSkipCompilingAssets (bool Enabled)
Set whether or not it is allowed to skip serialization on assets still being compiled to avoid waiting unless strictly necessary.
Static Protected Member Functions inherited from FArchive
static void LinkProxy (FArchiveState &Inner, FArchiveState &Proxy)
static void UnlinkProxy (FArchiveState &Inner, FArchiveState &Proxy)
Detailed Description
Base class for archive proxies.
Archive proxies are archive types that modify the behavior of another archive type.
Definition at line 18 of file ArchiveProxy.h.
Constructor & Destructor Documentation
FArchiveProxy() [1/3]
FArchiveProxy::FArchiveProxy (FArchive & InInnerArchive)
Creates and initializes a new instance of the archive proxy.
Parameters
InInnerArchive The inner archive to proxy.
References FArchive::FArchive().
Referenced by FArchiveProxy(), FArchiveProxy(), FNameAsStringIndexProxyArchive::FNameAsStringIndexProxyArchive(), FNameAsStringProxyArchive::FNameAsStringProxyArchive(), FPropertyProxyArchive::FPropertyProxyArchive(), TVersionedReader< T >::TVersionedReader(), TVersionedWriter< T >::TVersionedWriter(), operator=(), and operator=().
~FArchiveProxy()
FArchiveProxy::~FArchiveProxy ()
FArchiveProxy() [2/3]
FArchiveProxy::FArchiveProxy (FArchiveProxy &&) delete
References FArchiveProxy().
FArchiveProxy() [3/3]
FArchiveProxy::FArchiveProxy (const FArchiveProxy &) delete
References FArchiveProxy().
Member Function Documentation
AtEnd()
virtual bool FArchiveProxy::AtEnd () inline override virtual
Returns true if the current location within the backing data storage is at the end, always returns false if there is no storage.
Reimplemented from FArchive.
Definition at line 149 of file ArchiveProxy.h.
References InnerArchive.
AttachBulkData()
virtual void FArchiveProxy::AttachBulkData (UObject * Owner, FBulkData * BulkData) inline override virtual
Attaches/ associates the passed in bulk data object with the linker.
Parameters
Owner UObject owning the bulk data
BulkData Bulk data object to associate
Reimplemented from FArchive.
Definition at line 159 of file ArchiveProxy.h.
References BulkData, InnerArchive, and Owner.
AttachExternalReadDependency()
virtual bool FArchiveProxy::AttachExternalReadDependency (FExternalReadCallback & ReadCallback) inline override virtual
Adds external read dependency.
Returns
true if dependency has been added, false if Archive does not support them
Reimplemented from FArchive.
Definition at line 229 of file ArchiveProxy.h.
References InnerArchive.
Close()
virtual bool FArchiveProxy::Close () inline override virtual
Attempts to close and finalize any handles used for backing data storage, returns true if it succeeded.
Reimplemented from FArchive.
Definition at line 189 of file ArchiveProxy.h.
References InnerArchive.
CountBytes()
virtual void FArchiveProxy::CountBytes (SIZE_T InNum, SIZE_T InMax) inline override virtual
Called to get the computed size from a size-detecting archive after it has finished serializing.
Reimplemented from FArchive.
Definition at line 122 of file ArchiveProxy.h.
References InnerArchive.
DetachBulkData()
virtual void FArchiveProxy::DetachBulkData (FBulkData * BulkData, bool bEnsureBulkDataIsLoaded) inline override virtual
Detaches the passed in bulk data object from the linker.
Parameters
BulkData Bulk data object to detach
bEnsureBulkDataIsLoaded Whether to ensure that the bulk data is loaded before detaching
Reimplemented from FArchive.
Definition at line 164 of file ArchiveProxy.h.
References BulkData, and InnerArchive.
Flush()
virtual void FArchiveProxy::Flush () inline override virtual
Attempts to finish writing any buffered data to disk/permanent storage.
Reimplemented from FArchive.
Definition at line 184 of file ArchiveProxy.h.
References InnerArchive.
FlushCache()
virtual void FArchiveProxy::FlushCache () inline override virtual
Flushes cache and frees internal data.
Reimplemented from FArchive.
Definition at line 244 of file ArchiveProxy.h.
References InnerArchive.
ForceBlueprintFinalization()
virtual void FArchiveProxy::ForceBlueprintFinalization () inline override virtual
Inform the archive that a blueprint would like to force finalization, normally this is triggered by CDO load, but if there's no CDO we force finalization.
Reimplemented from FArchive.
Definition at line 249 of file ArchiveProxy.h.
References InnerArchive.
GetArchetypeFromLoader()
virtual UObject * FArchiveProxy::GetArchetypeFromLoader (const UObject * Obj) inline override virtual
Called to retrieve the archetype from the event driven loader.
If this returns null, then call GetArchetype yourself.
Reimplemented from FArchive.
Definition at line 224 of file ArchiveProxy.h.
References InnerArchive.
GetArchiveName()
virtual FString FArchiveProxy::GetArchiveName () const override virtual
Returns the name of the Archive.
Useful for getting the name of the package a struct or object is in when a loading error occurs.
This is overridden for the specific Archive Types
Reimplemented from FArchive.
Reimplemented in FMaterialResourceProxyReader.
GetCacheableArchive()
virtual FArchive * FArchiveProxy::GetCacheableArchive () inline override virtual
Returns a pointer to an archive that represents the same data that the current archive covers, but that can be cached and reused later In the case of standard archives, this function will just return a pointer to itself.
If the archive is actually a temporary proxy to another archive, and has a shorter lifecycle than the source archive, it should return either a pointer to the underlying archive, or if the data becomes inaccessible when the proxy object disappears (as is the case with text format archives) then nullptr
Reimplemented from FArchive.
Definition at line 314 of file ArchiveProxy.h.
References FArchive::FArchive(), and InnerArchive.
GetCustomVersions()
virtual const FCustomVersionContainer & FArchiveProxy::GetCustomVersions () const inline override virtual
Gets the custom version numbers for this archive.
These are used to check for system or game-specific version numbers.
Returns
The container of custom versions in the archive.
Reimplemented from FArchive.
Definition at line 204 of file ArchiveProxy.h.
References InnerArchive.
Referenced by TVersionedWriter< T >::~TVersionedWriter().
GetInnermostState()
virtual::FArchiveState & FArchiveProxy::GetInnermostState () inline override virtual
Returns lowest level archive state, proxy archives will override this.
Reimplemented from FArchive.
Definition at line 319 of file ArchiveProxy.h.
References InnerArchive.
GetLinker()
virtual FLinker * FArchiveProxy::GetLinker () inline override virtual
If this archive is a FLinkerLoad or FLinkerSave, returns a pointer to the ULinker portion.
Returns
The linker, or nullptr if the archive is not a linker.
Reimplemented from FArchive.
Definition at line 129 of file ArchiveProxy.h.
References InnerArchive.
IsProxyOf()
virtual FORCEINLINE bool FArchiveProxy::IsProxyOf (FArchive * InOther) const inline virtual
Determine if the given archive is a valid "child" of this archive.
In general, this means "is exactly the same" but this function allows a derived archive to support "child" or "internal" archives which are different objects that proxy the original one in some way.
Parameters
BulkData Bulk data object to detach
bEnsureBulkDataIsLoaded Whether to ensure that the bulk data is loaded before detaching
Reimplemented from FArchive.
Definition at line 309 of file ArchiveProxy.h.
References FArchive::FArchive(), FORCEINLINE, and InnerArchive.
MarkScriptSerializationEnd()
virtual void FArchiveProxy::MarkScriptSerializationEnd (const UObject * Obj) inline override virtual
Called when an object stops serializing property data using script serialization.
Reimplemented from FArchive.
Definition at line 199 of file ArchiveProxy.h.
References InnerArchive.
MarkScriptSerializationStart()
virtual void FArchiveProxy::MarkScriptSerializationStart (const UObject * Obj) inline override virtual
Called when an object begins serializing property data using script serialization.
Reimplemented from FArchive.
Definition at line 194 of file ArchiveProxy.h.
References InnerArchive.
MarkSearchableName()
virtual void FArchiveProxy::MarkSearchableName (const TObjectPtr< const UObject > & TypeObject, const FName & ValueName) const inline override virtual
Called to register a reference to a specific name value, of type TypeObject (UEnum or UStruct normally).
Const so it can be called from PostSerialize
Reimplemented from FArchive.
Definition at line 219 of file ArchiveProxy.h.
References InnerArchive.
operator<<() [1/9]
virtual FArchive & FArchiveProxy::operator<< (FField *& Value) inline override virtual
Serializes a Field value from or into this archive.
This operator can be implemented by sub-classes that wish to serialize UObject instances.
Parameters
Value The value to serialize.
Returns
This instance.
Reimplemented from FArchive.
Reimplemented in FActorDescArchive, and FPropertyProxyArchive.
Definition at line 83 of file ArchiveProxy.h.
References FArchive::FArchive(), InnerArchive, and Value.
operator<<() [2/9]
virtual FArchive & FArchiveProxy::operator<< (FLazyObjectPtr & Value) inline override virtual
Serializes a lazy object pointer value from or into this archive.
Most of the time, FLazyObjectPtrs are serialized as UObject*, but some archives need to override this.
Parameters
Value The value to serialize.
Returns
This instance.
Reimplemented from FArchive.
Reimplemented in FActorDescArchive.
Definition at line 59 of file ArchiveProxy.h.
References FArchive::FArchive(), InnerArchive, and Value.
operator<<() [3/9]
virtual FArchive & FArchiveProxy::operator<< (FName & Value) inline override virtual
Serializes an FName value from or into this archive.
This operator can be implemented by sub-classes that wish to serialize FName instances.
Parameters
Value The value to serialize.
Returns
This instance.
Reimplemented from FArchive.
Reimplemented in FActorDescArchive, FActorDescArchivePatcher, FMaterialResourceProxyReader, FNameAsStringIndexProxyArchive, and FNameAsStringProxyArchive.
Definition at line 35 of file ArchiveProxy.h.
References FArchive::FArchive(), InnerArchive, and Value.
Referenced by FActorDescArchive::operator<<().
operator<<() [4/9]
virtual FArchive & FArchiveProxy::operator<< (FObjectPtr & Value) inline override virtual
Serializes a wrapped object pointer value from or into this archive.
Most of the time, FObjectPtrs are serialized as UObject*, but some archives need to override this.
Parameters
Value The value to serialize.
Returns
This instance.
Reimplemented from FArchive.
Reimplemented in FActorDescArchive, FObjectAndNameAsStringProxyArchive, and UE::AnimNext::FTraitReader.
Definition at line 53 of file ArchiveProxy.h.
References FArchive::FArchive(), InnerArchive, and Value.
operator<<() [5/9]
virtual FArchive & FArchiveProxy::operator<< (FSoftObjectPath & Value) inline override virtual
Serializes soft object paths from or into this archive.
Parameters
Value Soft object path to serialize.
Returns
This instance.
Reimplemented from FArchive.
Reimplemented in FActorDescArchive, FActorDescArchivePatcher, FObjectAndNameAsStringProxyArchive, and UE::AnimNext::FTraitReader.
Definition at line 65 of file ArchiveProxy.h.
References FArchive::FArchive(), InnerArchive, and Value.
operator<<() [6/9]
virtual FArchive & FArchiveProxy::operator<< (FSoftObjectPtr & Value) inline override virtual
Serializes asset pointer from or into this archive.
Most of the time, FSoftObjectPtr are serialized as UObject *, but some archives need to override this.
Parameters
Value The asset pointer to serialize.
Returns
This instance.
Reimplemented from FArchive.
Reimplemented in FActorDescArchive, FObjectAndNameAsStringProxyArchive, and UE::AnimNext::FTraitReader.
Definition at line 71 of file ArchiveProxy.h.
References FArchive::FArchive(), InnerArchive, and Value.
operator<<() [7/9]
virtual FArchive & FArchiveProxy::operator<< (FText & Value) inline override virtual
Serializes an FText value from or into an archive.
Parameters
Ar The archive to serialize from or to.
Value The value to serialize.
Reimplemented from FArchive.
Reimplemented in FActorDescArchive.
Definition at line 41 of file ArchiveProxy.h.
References FArchive::FArchive(), InnerArchive, and Value.
operator<<() [8/9]
virtual FArchive & FArchiveProxy::operator<< (FWeakObjectPtr & Value) inline override virtual
Serializes FWeakObjectPtr value from or into this archive.
This operator can be implemented by sub-classes that wish to serialize FWeakObjectPtr instances.
Parameters
Value The value to serialize.
Returns
This instance.
Reimplemented from FArchive.
Reimplemented in FActorDescArchive, FObjectAndNameAsStringProxyArchive, and UE::AnimNext::FTraitReader.
Definition at line 77 of file ArchiveProxy.h.
References FArchive::FArchive(), InnerArchive, and Value.
operator<<() [9/9]
virtual FArchive & FArchiveProxy::operator<< (UObject *& Value) inline override virtual
Serializes an UObject value from or into this archive.
This operator can be implemented by sub-classes that wish to serialize UObject instances.
Parameters
Value The value to serialize.
Returns
This instance.
Reimplemented from FArchive.
Reimplemented in FActorDescArchive, FObjectAndNameAsStringProxyArchive, and UE::AnimNext::FTraitReader.
Definition at line 47 of file ArchiveProxy.h.
References FArchive::FArchive(), InnerArchive, and Value.
operator=() [1/2]
FArchiveProxy & FArchiveProxy::operator= (const FArchiveProxy &) delete
References FArchiveProxy().
operator=() [2/2]
FArchiveProxy & FArchiveProxy::operator= (FArchiveProxy &&) delete
References FArchiveProxy().
PopDebugDataString()
virtual void FArchiveProxy::PopDebugDataString () inline override virtual
Reimplemented from FArchive.
Definition at line 271 of file ArchiveProxy.h.
References InnerArchive.
PopSerializedProperty()
virtual FORCEINLINE void FArchiveProxy::PopSerializedProperty (class FProperty * InProperty, const bool bIsEditorOnlyProperty) inline virtual
Pops editor-only marker from the stack of currently serialized properties.
Reimplemented from FArchive.
Definition at line 296 of file ArchiveProxy.h.
References FORCEINLINE, InnerArchive, and FArchive::PopSerializedProperty().
Precache()
virtual bool FArchiveProxy::Precache (int64 PrecacheOffset, int64 PrecacheSize) inline override virtual
Hint the archive that the region starting at passed in offset and spanning the passed in size is going to be read soon and should be precached.
The function returns whether the precache operation has completed or not which is an important hint for code knowing that it deals with potential async I/O. The archive is free to either not implement this function or only partially precache so it is required that given sufficient time the function will return true. Archives not based on async I/O should always return true.
This function will not change the current archive position.
Parameters
PrecacheOffset Offset at which to begin precaching.
PrecacheSize Number of bytes to precache
Returns
false if precache operation is still pending, true otherwise
Reimplemented from FArchive.
Definition at line 174 of file ArchiveProxy.h.
References InnerArchive.
Preload()
virtual void FArchiveProxy::Preload (UObject * Object) inline override virtual
Tells the archive to attempt to preload the specified object so data can be loaded out of it.
Reimplemented from FArchive.
Definition at line 117 of file ArchiveProxy.h.
References InnerArchive, and Object.
PushDebugDataString()
virtual void FArchiveProxy::PushDebugDataString (const FName & DebugData) inline override virtual
Debug stack storage if you want to add data to the archive for usage further down the serialization stack this should be used in conjunction with the FScopeAddDebugData struct.
Reimplemented from FArchive.
Definition at line 267 of file ArchiveProxy.h.
References InnerArchive.
PushSerializedProperty()
virtual FORCEINLINE void FArchiveProxy::PushSerializedProperty (class FProperty * InProperty, const bool bIsEditorOnlyProperty) inline virtual
Pushes editor-only marker to the stack of currently serialized properties.
Reimplemented from FArchive.
Definition at line 290 of file ArchiveProxy.h.
References FORCEINLINE, InnerArchive, and FArchive::PushSerializedProperty().
ResetCustomVersions()
virtual void FArchiveProxy::ResetCustomVersions () inline override virtual
Resets the custom version numbers for this archive.
Reimplemented from FArchive.
Definition at line 214 of file ArchiveProxy.h.
References InnerArchive.
Seek()
virtual void FArchiveProxy::Seek (int64 InPos) inline override virtual
Attempts to set the current offset into backing data storage, this will do nothing if there is no storage.
Reimplemented from FArchive.
Reimplemented in FMaterialResourceProxyReader.
Definition at line 154 of file ArchiveProxy.h.
References InnerArchive.
Referenced by TVersionedReader< T >::TVersionedReader(), and TVersionedWriter< T >::~TVersionedWriter().
Serialize()
virtual void FArchiveProxy::Serialize (void * V, int64 Length) inline override virtual
Reimplemented from FArchive.
Reimplemented in FActorDescArchivePatcher.
Definition at line 97 of file ArchiveProxy.h.
References InnerArchive.
SerializeBits()
virtual void FArchiveProxy::SerializeBits (void * Bits, int64 LengthBits) inline override virtual
Reimplemented from FArchive.
Definition at line 102 of file ArchiveProxy.h.
References InnerArchive.
SerializeBulkData()
virtual bool FArchiveProxy::SerializeBulkData (FBulkData & BulkData, const FBulkDataSerializationParams & Params) inline override virtual
Serialize bulk data.
Parameters
BulkData Bulk data object to serialize
Params Serialization parameters
Returns
true if the bulk data was serialized, false to fallback to default serialization (inline)
Reimplemented from FArchive.
Definition at line 169 of file ArchiveProxy.h.
References BulkData, InnerArchive, and Params.
SerializeInt()
virtual void FArchiveProxy::SerializeInt (uint32 & Value, uint32 Max) inline override virtual
Reimplemented from FArchive.
Definition at line 107 of file ArchiveProxy.h.
References InnerArchive, Max, and Value.
SerializeIntPacked()
virtual void FArchiveProxy::SerializeIntPacked (uint32 & Value) inline override virtual
Packs int value into bytes of 7 bits with 8th bit for 'more'.
Reimplemented from FArchive.
Definition at line 112 of file ArchiveProxy.h.
References InnerArchive, and Value.
SetCompressionMap()
virtual bool FArchiveProxy::SetCompressionMap (TArray< FCompressedChunk > * CompressedChunks, ECompressionFlags CompressionFlags) inline override virtual
Sets mapping from offsets/ sizes that are going to be used for seeking and serialization to what is actually stored on disk.
If the archive supports dealing with compression in this way it is going to return true.
Parameters
CompressedChunks Pointer to array containing information about [un]compressed chunks
CompressionFlags Flags determining compression format associated with mapping
Returns
true if archive supports translating offsets & uncompressing on read, false otherwise
Reimplemented from FArchive.
Definition at line 179 of file ArchiveProxy.h.
References InnerArchive.
SetCustomVersions()
virtual void FArchiveProxy::SetCustomVersions (const FCustomVersionContainer & CustomVersionContainer) inline override virtual
Sets the custom version numbers for this archive.
Parameters
CustomVersionContainer - The container of custom versions to copy into the archive.
Reimplemented from FArchive.
Definition at line 209 of file ArchiveProxy.h.
References InnerArchive.
Referenced by TVersionedReader< T >::TVersionedReader().
SetDebugSerializationFlags()
virtual void FArchiveProxy::SetDebugSerializationFlags (uint32 InCustomFlags) inline override virtual
Sets the archives custom serialization modifier flags (nothing to do with PortFlags or Custom versions)
Parameters
InCustomFlags the new flags to use for custom serialization
Reimplemented from FArchive.
Definition at line 254 of file ArchiveProxy.h.
References InnerArchive, and FArchive::SetDebugSerializationFlags().
SetFilterEditorOnly()
virtual void FArchiveProxy::SetFilterEditorOnly (bool InFilterEditorOnly) inline override virtual
Sets a flag indicating that this archive needs to filter editor-only content.
Parameters
InFilterEditorOnly Whether to filter editor-only content.
Reimplemented from FArchive.
Definition at line 260 of file ArchiveProxy.h.
References InnerArchive, and FArchive::SetFilterEditorOnly().
SetSerializedProperty()
FORCEINLINE void FArchiveProxy::SetSerializedProperty (FProperty * InProperty) inline override virtual
Overrides the property that is currently being serialized.
Note
: You likely want to call PushSerializedProperty/PopSerializedProperty instead
Parameters
InProperty Pointer to the property that is currently being serialized
Reimplemented from FArchive.
Definition at line 277 of file ArchiveProxy.h.
References FORCEINLINE, InnerArchive, and FArchive::SetSerializedProperty().
SetSerializedPropertyChain()
void FArchiveProxy::SetSerializedPropertyChain (const FArchiveSerializedPropertyChain * InSerializedPropertyChain, class FProperty * InSerializedPropertyOverride = nullptr) inline override virtual
Set the raw serialized property chain for this archive, optionally overriding the serialized property too (or null to use the head of the property chain)
Reimplemented from FArchive.
Definition at line 283 of file ArchiveProxy.h.
References InnerArchive, and FArchive::SetSerializedPropertyChain().
ShouldSkipProperty()
virtual bool FArchiveProxy::ShouldSkipProperty (const FProperty * InProperty) const inline override virtual
Checks whether the archive wants to skip the property independent of the other flags.
Reimplemented from FArchive.
Definition at line 234 of file ArchiveProxy.h.
References InnerArchive.
Tell()
virtual int64 FArchiveProxy::Tell () inline override virtual
Returns the current location within the backing data storage, which can possibly be passed to Seek later to restore a read/write location.
If this returns -1, there is no backing data storage and Seek will not function.
Reimplemented from FArchive.
Reimplemented in FMaterialResourceProxyReader.
Definition at line 139 of file ArchiveProxy.h.
References InnerArchive.
Referenced by TVersionedReader< T >::TVersionedReader(), TVersionedWriter< T >::TVersionedWriter(), and TVersionedWriter< T >::~TVersionedWriter().
TotalSize()
virtual int64 FArchiveProxy::TotalSize () inline override virtual
Returns total size of the backing data storage.
Reimplemented from FArchive.
Definition at line 144 of file ArchiveProxy.h.
References InnerArchive.
UseToResolveEnumerators()
virtual bool FArchiveProxy::UseToResolveEnumerators () const inline override virtual
Checks whether the archive is used to resolve out-of-date enum indexes If function returns true, the archive should be called only for objects containing user defined enum.
Returns
true if the archive is used to resolve out-of-date enum indexes
Reimplemented from FArchive.
Definition at line 239 of file ArchiveProxy.h.
References InnerArchive.
Field Documentation
InnerArchive
FArchive& FArchiveProxy::InnerArchive protected
Holds the archive that this archive is a proxy to.
Definition at line 327 of file ArchiveProxy.h.
Referenced by FPropertyProxyArchive::FPropertyProxyArchive(), AtEnd(), AttachBulkData(), AttachExternalReadDependency(), Close(), CountBytes(), DetachBulkData(), Flush(), FlushCache(), ForceBlueprintFinalization(), GetArchetypeFromLoader(), GetCacheableArchive(), GetCustomVersions(), GetInnermostState(), GetLinker(), IsProxyOf(), MarkScriptSerializationEnd(), MarkScriptSerializationStart(), MarkSearchableName(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), FPropertyProxyArchive::operator<<(), PopDebugDataString(), PopSerializedProperty(), Precache(), Preload(), PushDebugDataString(), PushSerializedProperty(), ResetCustomVersions(), Seek(), FMaterialResourceProxyReader::Seek(), Serialize(), SerializeBits(), SerializeBulkData(), SerializeInt(), SerializeIntPacked(), SetCompressionMap(), SetCustomVersions(), SetDebugSerializationFlags(), SetFilterEditorOnly(), SetSerializedProperty(), SetSerializedPropertyChain(), ShouldSkipProperty(), Tell(), FMaterialResourceProxyReader::Tell(), TotalSize(), and UseToResolveEnumerators().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Serialization/ArchiveProxy.h