Unreal Engine 5.6 C++ API: FDisplayClusterMeshProjectionTransform Class Reference
FDisplayClusterMeshProjectionTransform Class Reference
A transform that can be passed around to project and unprojection positions for a specific projection type.
#include "DisplayClusterMeshProjectionRenderer.h"
Public Member Functions
FDisplayClusterMeshProjectionTransform ()
FDisplayClusterMeshProjectionTransform (EDisplayClusterMeshProjectionType InProjection, const FMatrix &InViewMatrix)
DISPLAYCLUSTERLIGHTCARDEDITORSHADERS_API FVector ProjectPosition (const FVector &WorldPosition) const
DISPLAYCLUSTERLIGHTCARDEDITORSHADERS_API FVector UnprojectPosition (const FVector &ProjectedPosition) const
Private Attributes
FMatrix InvViewMatrix
EDisplayClusterMeshProjectionType Projection
FMatrix ViewMatrix
Detailed Description
A transform that can be passed around to project and unprojection positions for a specific projection type.
Definition at line 115 of file DisplayClusterMeshProjectionRenderer.h.
Constructor & Destructor Documentation
FDisplayClusterMeshProjectionTransform() [1/2]
FDisplayClusterMeshProjectionTransform::FDisplayClusterMeshProjectionTransform () inline
Definition at line 118 of file DisplayClusterMeshProjectionRenderer.h.
References FDisplayClusterMeshProjectionTransform(), and Linear.
Referenced by FDisplayClusterMeshProjectionTransform().
FDisplayClusterMeshProjectionTransform() [2/2]
FDisplayClusterMeshProjectionTransform::FDisplayClusterMeshProjectionTransform (EDisplayClusterMeshProjectionType InProjection, const FMatrix & InViewMatrix) inline
Definition at line 122 of file DisplayClusterMeshProjectionRenderer.h.
References Inverse(), InvViewMatrix, Projection, and ViewMatrix.
Member Function Documentation
ProjectPosition()
DISPLAYCLUSTERLIGHTCARDEDITORSHADERS_API FVector FDisplayClusterMeshProjectionTransform::ProjectPosition (const FVector & WorldPosition) const
References FVector.
UnprojectPosition()
DISPLAYCLUSTERLIGHTCARDEDITORSHADERS_API FVector FDisplayClusterMeshProjectionTransform::UnprojectPosition (const FVector & ProjectedPosition) const
References FVector.
Field Documentation
InvViewMatrix
FMatrix FDisplayClusterMeshProjectionTransform::InvViewMatrix private
Definition at line 134 of file DisplayClusterMeshProjectionRenderer.h.
Referenced by FDisplayClusterMeshProjectionTransform().
Projection
EDisplayClusterMeshProjectionType FDisplayClusterMeshProjectionTransform::Projection private
Definition at line 132 of file DisplayClusterMeshProjectionRenderer.h.
Referenced by FDisplayClusterMeshProjectionTransform().
ViewMatrix
FMatrix FDisplayClusterMeshProjectionTransform::ViewMatrix private
Definition at line 133 of file DisplayClusterMeshProjectionRenderer.h.
Referenced by FDisplayClusterMeshProjectionTransform().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/nDisplay/Source/DisplayClusterLightCardEditorShaders/Public/DisplayClusterMeshProjectionRenderer.h