Unreal Engine 5.6 C++ API: FQueuedThreadPoolTaskGraphWrapper Class Reference
FQueuedThreadPoolTaskGraphWrapper Class Reference final
ThreadPool wrapper implementation allowing to schedule thread-pool tasks on the task graph.
#include "QueuedThreadPoolWrapper.h"
Public Member Functions
FQueuedThreadPoolTaskGraphWrapper (ENamedThreads::Type InDesiredThread)
InDesiredThread The task-graph desired thread and priority.
FQueuedThreadPoolTaskGraphWrapper (TFunction< ENamedThreads::Type(EQueuedWorkPriority)> InPriorityMapper=nullptr)
InPriorityMapper Thread-safe function used to map any priority from this Queue to the priority that should be used when scheduling the task on the task graph.
~FQueuedThreadPoolTaskGraphWrapper ()
Public Member Functions inherited from FQueuedThreadPool
FQueuedThreadPool ()
virtual ~FQueuedThreadPool ()
virtual bool CreateForkable (uint32 InNumQueuedThreads, uint32 StackSize=(32 *1024), EThreadPriority ThreadPriority=TPri_Normal, const TCHAR *Name=TEXT("UnknownThreadPool"))
Creates the thread pool with the specified number of forkable threads (see FForkProcessHelper)
Protected Member Functions
bool Create (uint32 InNumQueuedThreads, uint32 StackSize, EThreadPriority ThreadPriority, const TCHAR *Name) override
Creates the thread pool with the specified number of threads.
void Destroy () override
Tells the pool to clean up all background threads.
Private Member Functions
void AddQueuedWork (IQueuedWork *InQueuedWork, EQueuedWorkPriority InPriority=EQueuedWorkPriority::Normal) override
Checks to see if there is a thread available to perform the task.
ENamedThreads::Type GetDefaultPriorityMapping (EQueuedWorkPriority InQueuedWorkPriority)
int32 GetNumThreads () const override
Get the number of queued threads.
void OnTaskCompleted (IQueuedWork *InQueuedWork)
bool RetractQueuedWork (IQueuedWork *InQueuedWork) override
Attempts to retract a previously queued task.
Private Attributes
TAtomic< bool > bIsExiting
UE::FManualResetEvent Finished
TFunction< ENamedThreads::Type(EQueuedWorkPriority)> PriorityMapper
TAtomic< uint32 > TaskCount
Additional Inherited Members
Static Public Member Functions inherited from FQueuedThreadPool
static FQueuedThreadPool * Allocate ()
Allocates a thread pool.
Static Public Attributes inherited from FQueuedThreadPool
static uint32 OverrideStackSize
Stack size for threads created for the thread pool.
Detailed Description
ThreadPool wrapper implementation allowing to schedule thread-pool tasks on the task graph.
Definition at line 261 of file QueuedThreadPoolWrapper.h.
Constructor & Destructor Documentation
FQueuedThreadPoolTaskGraphWrapper() [1/2]
FQueuedThreadPoolTaskGraphWrapper::FQueuedThreadPoolTaskGraphWrapper (TFunction< ENamedThreads::Type(EQueuedWorkPriority)> InPriorityMapper = nullptr) inline
InPriorityMapper Thread-safe function used to map any priority from this Queue to the priority that should be used when scheduling the task on the task graph.
Definition at line 267 of file QueuedThreadPoolWrapper.h.
References bIsExiting, GetDefaultPriorityMapping(), PriorityMapper, and TaskCount.
Referenced by AddQueuedWork().
FQueuedThreadPoolTaskGraphWrapper() [2/2]
FQueuedThreadPoolTaskGraphWrapper::FQueuedThreadPoolTaskGraphWrapper (ENamedThreads::Type InDesiredThread) inline
InDesiredThread The task-graph desired thread and priority.
Definition at line 284 of file QueuedThreadPoolWrapper.h.
References bIsExiting, PriorityMapper, and TaskCount.
~FQueuedThreadPoolTaskGraphWrapper()
FQueuedThreadPoolTaskGraphWrapper::~FQueuedThreadPoolTaskGraphWrapper () inline
Definition at line 291 of file QueuedThreadPoolWrapper.h.
References Destroy().
Member Function Documentation
AddQueuedWork()
void FQueuedThreadPoolTaskGraphWrapper::AddQueuedWork (IQueuedWork * InQueuedWork, EQueuedWorkPriority InQueuedWorkPriority = EQueuedWorkPriority::Normal) inline override private virtual
Checks to see if there is a thread available to perform the task.
If not, it queues the work for later. Otherwise it is immediately dispatched.
Parameters
InQueuedWork The work that needs to be done asynchronously
InQueuedWorkPriority The priority at which to process this task
See also
RetractQueuedWork
Implements FQueuedThreadPool.
Definition at line 296 of file QueuedThreadPoolWrapper.h.
References FQueuedThreadPoolTaskGraphWrapper(), bIsExiting, check, FFunctionGraphTask::CreateAndDispatchWhenReady(), IQueuedWork::DoThreadedWork(), Normal, OnTaskCompleted(), PriorityMapper, QUICK_USE_CYCLE_STAT, and TaskCount.
Create()
bool FQueuedThreadPoolTaskGraphWrapper::Create (uint32 InNumQueuedThreads, uint32 StackSize, EThreadPriority ThreadPriority, const TCHAR * Name) inline override protected virtual
Creates the thread pool with the specified number of threads.
Parameters
InNumQueuedThreads Specifies the number of threads to use in the pool
StackSize The size of stack the threads in the pool need (32K default)
ThreadPriority priority of new pool thread
Name optional name for the pool to be used for instrumentation
Returns
Whether the pool creation was successful or not
Implements FQueuedThreadPool.
Definition at line 346 of file QueuedThreadPoolWrapper.h.
References Name.
Destroy()
void FQueuedThreadPoolTaskGraphWrapper::Destroy () inline override protected virtual
Tells the pool to clean up all background threads.
Implements FQueuedThreadPool.
Definition at line 351 of file QueuedThreadPoolWrapper.h.
References bIsExiting, Finished, and TaskCount.
Referenced by ~FQueuedThreadPoolTaskGraphWrapper().
GetDefaultPriorityMapping()
ENamedThreads::Type FQueuedThreadPoolTaskGraphWrapper::GetDefaultPriorityMapping (EQueuedWorkPriority InQueuedWorkPriority) inline private
Definition at line 332 of file QueuedThreadPoolWrapper.h.
References ENamedThreads::AnyBackgroundThreadNormalTask, ENamedThreads::AnyHiPriThreadNormalTask, ENamedThreads::AnyNormalThreadNormalTask, and Normal.
Referenced by FQueuedThreadPoolTaskGraphWrapper().
GetNumThreads()
int32 FQueuedThreadPoolTaskGraphWrapper::GetNumThreads () const inline override private virtual
Get the number of queued threads.
Implements FQueuedThreadPool.
Definition at line 327 of file QueuedThreadPoolWrapper.h.
References FTaskGraphInterface::Get(), and FTaskGraphInterface::GetNumWorkerThreads().
OnTaskCompleted()
void FQueuedThreadPoolTaskGraphWrapper::OnTaskCompleted (IQueuedWork * InQueuedWork) inline private
Definition at line 319 of file QueuedThreadPoolWrapper.h.
References bIsExiting, Finished, and TaskCount.
Referenced by AddQueuedWork().
RetractQueuedWork()
bool FQueuedThreadPoolTaskGraphWrapper::RetractQueuedWork (IQueuedWork * InQueuedWork) inline override private virtual
Attempts to retract a previously queued task.
Parameters
InQueuedWork The work to try to retract
Returns
true if the work was retracted
See also
AddQueuedWork
Implements FQueuedThreadPool.
Definition at line 313 of file QueuedThreadPoolWrapper.h.
Field Documentation
bIsExiting
TAtomic<bool> FQueuedThreadPoolTaskGraphWrapper::bIsExiting private
Definition at line 363 of file QueuedThreadPoolWrapper.h.
Referenced by FQueuedThreadPoolTaskGraphWrapper(), FQueuedThreadPoolTaskGraphWrapper(), AddQueuedWork(), Destroy(), and OnTaskCompleted().
Finished
UE::FManualResetEvent FQueuedThreadPoolTaskGraphWrapper::Finished private
Definition at line 364 of file QueuedThreadPoolWrapper.h.
Referenced by Destroy(), and OnTaskCompleted().
PriorityMapper
TFunction<ENamedThreads::Type (EQueuedWorkPriority)> FQueuedThreadPoolTaskGraphWrapper::PriorityMapper private
Definition at line 361 of file QueuedThreadPoolWrapper.h.
Referenced by FQueuedThreadPoolTaskGraphWrapper(), FQueuedThreadPoolTaskGraphWrapper(), and AddQueuedWork().
TaskCount
TAtomic<uint32> FQueuedThreadPoolTaskGraphWrapper::TaskCount private
Definition at line 362 of file QueuedThreadPoolWrapper.h.
Referenced by FQueuedThreadPoolTaskGraphWrapper(), FQueuedThreadPoolTaskGraphWrapper(), AddQueuedWork(), Destroy(), and OnTaskCompleted().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Misc/QueuedThreadPoolWrapper.h