Unreal Engine 5.6 C++ API: UE::Geometry::FPinchKelvinlet Class Reference
UE::Geometry::FPinchKelvinlet Class Reference
#include "Kelvinlets.h"
Public Types
typedef TBaseKelvinlet< FPinchKelvinlet > MyBase
Public Member Functions
FPinchKelvinlet (const FMatrix3d &ForceMatrix, const double Size, const double ShearModulus, const double PoissonRatio)
FVector3d Evaluate (const FVector3d &Pos) const
Public Member Functions inherited from UE::Geometry::TBaseKelvinlet< FPinchKelvinlet >
TBaseKelvinlet (const double Size, const double ShearModulus, const double PoissonRatio)
void SetMaterialParameters (const double ShearModulus, const double PoissonRatio)
void UpdateRegularization (const double R)
Public Member Functions inherited from UE::Geometry::TKelvinletIntegrator< KelvinletModelType >
FVector3d Evaluate (const FVector3d &Pos) const
FVector3d IntegrateRK3 (const FVector3d &Pos, double dt) const
Private Member Functions
void Normalize ()
FMatrix3d PinchMatrix (const FMatrix3d &Mat)
Private Attributes
double c
FMatrix3d F
Additional Inherited Members
Protected Attributes inherited from UE::Geometry::TBaseKelvinlet< FPinchKelvinlet >
double a
double bhat
double E
Detailed Description
Definition at line 512 of file Kelvinlets.h.
Member Typedef Documentation
MyBase
typedef TBaseKelvinlet<FPinchKelvinlet> UE::Geometry::FPinchKelvinlet::MyBase
Definition at line 515 of file Kelvinlets.h.
Constructor & Destructor Documentation
FPinchKelvinlet()
UE::Geometry::FPinchKelvinlet::FPinchKelvinlet (const FMatrix3d & ForceMatrix, const double Size, const double ShearModulus, const double PoissonRatio) inline
Definition at line 517 of file Kelvinlets.h.
References F, Normalize(), PinchMatrix(), and TSequenceHistory< HistorySize >::Size.
Member Function Documentation
Evaluate()
FVector3d UE::Geometry::FPinchKelvinlet::Evaluate (const FVector3d & Pos) const inline
Definition at line 527 of file Kelvinlets.h.
References UE::Geometry::TBaseKelvinlet< FPinchKelvinlet >::bhat, c, UE::Math::TVector< T >::Dot(), UE::Geometry::TBaseKelvinlet< FPinchKelvinlet >::E, F, and UE::Math::TVector< T >::SquaredLength().
Normalize()
void UE::Geometry::FPinchKelvinlet::Normalize () inline private
Definition at line 564 of file Kelvinlets.h.
References UE::Geometry::TBaseKelvinlet< FPinchKelvinlet >::bhat, and c.
Referenced by FPinchKelvinlet().
PinchMatrix()
FMatrix3d UE::Geometry::FPinchKelvinlet::PinchMatrix (const FMatrix3d & Mat) inline private
Definition at line 556 of file Kelvinlets.h.
References UE::Geometry::TMatrix3< double >::Identity(), UE::Geometry::TMatrix3< RealType >::Trace(), and UE::Geometry::TMatrix3< RealType >::Transpose().
Referenced by FPinchKelvinlet().
Field Documentation
c
double UE::Geometry::FPinchKelvinlet::c private
Definition at line 573 of file Kelvinlets.h.
Referenced by Evaluate(), and Normalize().
F
FMatrix3d UE::Geometry::FPinchKelvinlet::F private
Definition at line 575 of file Kelvinlets.h.
Referenced by FPinchKelvinlet(), and Evaluate().
The documentation for this class was generated from the following file:
Runtime/GeometryCore/Public/Deformers/Kelvinlets.h