Unreal Engine 5.6 C++ API: FMeshDescriptionOperations Class Reference
FMeshDescriptionOperations Class Reference
#include "MeshDescriptionOperations.h"
Public Types
enum ETangentOptions {
None = 0 , BlendOverlappingNormals = 0x00000001 , IgnoreDegenerateTriangles = 0x00000002 , UseMikkTSpace = 0x00000004 ,
UseWeightedAreaAndAngle = 0x00000008
}
typedef FStaticMeshOperations::FAppendSettings FAppendSettings
Public Member Functions
UE_DEPRECATED (4.25, "Use FMeshDescription::RemapPolygonGroups() instead.") static void RemapPolygonGroups(FMeshDescription &MeshDescription
UE_DEPRECATED (4.25, "Use FStaticMeshOperations::AddUVChannel() instead.") static bool AddUVChannel(FMeshDescription &MeshDescription)
Add a UV channel to the MeshDescription.
UE_DEPRECATED (4.25, "Use FStaticMeshOperations::AppendMeshDescription() instead.") static void AppendMeshDescription(const FMeshDescription &SourceMesh
UE_DEPRECATED (4.25, "Use FStaticMeshOperations::BuildWeldedVertexIDRemap() instead.") static void BuildWeldedVertexIDRemap(const FMeshDescription &MeshDescription
UE_DEPRECATED (4.25, "Use FStaticMeshOperations::ComputeSHAHash() instead.") static FSHAHash ComputeSHAHash(const FMeshDescription &MeshDescription)
Computes the SHA hash of all the attributes values in the MeshDescription.
UE_DEPRECATED (4.25, "Use FStaticMeshOperations::ConvertFromRawMesh() instead.") static void ConvertFromRawMesh(const FRawMesh &SourceRawMesh
Convert old FRawMesh format to MeshDescription.
UE_DEPRECATED (4.25, "Use FStaticMeshOperations::ConvertHardEdgesToSmoothGroup() instead.") static void ConvertHardEdgesToSmoothGroup(const FMeshDescription &SourceMeshDescription
UE_DEPRECATED (4.25, "Use FStaticMeshOperations::ConvertSmoothGroupToHardEdges() instead.") static void ConvertSmoothGroupToHardEdges(const TArray< uint32 > &FaceSmoothingMasks
UE_DEPRECATED (4.25, "Use FStaticMeshOperations::ConvertToRawMesh() instead.") static void ConvertToRawMesh(const FMeshDescription &SourceMeshDescription
Convert this mesh description into the old FRawMesh format.
UE_DEPRECATED (4.25, "Use FStaticMeshOperations::CreatComputePolygonTangentsAndNormals() instead.") static void CreatePolygonNTB(FMeshDescription &MeshDescription
Compute normal, tangent and Bi-Normal for every polygon in the mesh description.
UE_DEPRECATED (4.25, "Use FStaticMeshOperations::CreateLightMapUVLayout() instead.") static bool CreateLightMapUVLayout(FMeshDescription &MeshDescription
Find and pack UV charts for lightmap.
UE_DEPRECATED (4.25, "Use FStaticMeshOperations::CreateMikktTangents() instead.") static void CreateMikktTangents(FMeshDescription &MeshDescription
Compute tangent and Bi-Normal using mikkt space for every vertex in the mesh description.
UE_DEPRECATED (4.25, "Use FStaticMeshOperations::CreateNormals() instead.") static void CreateNormals(FMeshDescription &MeshDescription
Compute normal, tangent and Bi-Normal(only if bComputeTangent is true) for every vertex in the mesh description.
UE_DEPRECATED (4.25, "Use FStaticMeshOperations::FindOverlappingCorners() instead.") static void FindOverlappingCorners(FOverlappingCorners &OverlappingCorners
Find all overlapping vertex using the threshold in the mesh description.
UE_DEPRECATED (4.25, "Use FStaticMeshOperations::GenerateBoxUV() instead.") static void GenerateBoxUV(const FMeshDescription &MeshDescription
Generate box UV mapping for the MeshDescription.
UE_DEPRECATED (4.25, "Use FStaticMeshOperations::GenerateCylindricalUV() instead.") static void GenerateCylindricalUV(FMeshDescription &MeshDescription
Generate cylindrical UV mapping for the MeshDescription.
UE_DEPRECATED (4.25, "Use FStaticMeshOperations::GeneratePlanarUV() instead.") static void GeneratePlanarUV(const FMeshDescription &MeshDescription
Generate planar UV mapping for the MeshDescription.
UE_DEPRECATED (4.25, "Use FStaticMeshOperations::GenerateUniqueUVsForStaticMesh() instead.") static bool GenerateUniqueUVsForStaticMesh(const FMeshDescription &MeshDescription
Create some UVs from the specified mesh description data.
UE_DEPRECATED (4.25, "Use FStaticMeshOperations::GetUVChartCount() instead.") static int32 GetUVChartCount(FMeshDescription &MeshDescription
Find all charts in the mesh description.
UE_DEPRECATED (4.25, "Use FStaticMeshOperations::HasVertexColor() instead.") static bool HasVertexColor(const FMeshDescription &MeshDescription)
UE_DEPRECATED (4.25, "Use FStaticMeshOperations::InsertUVChannel() instead.") static bool InsertUVChannel(FMeshDescription &MeshDescription
Insert a UV channel at the given index to the MeshDescription.
UE_DEPRECATED (4.25, "Use FStaticMeshOperations::RecomputeNormalsAndTangentsIfNeeded() instead.") static void RecomputeNormalsAndTangentsIfNeeded(FMeshDescription &MeshDescription
UE_DEPRECATED (4.25, "Use FStaticMeshOperations::RemoveUVChannel() instead.") static bool RemoveUVChannel(FMeshDescription &MeshDescription
Remove the UV channel at the given index from the MeshDescription.
UE_DEPRECATED (4.25, "Use FStaticMeshOperations::SwapPolygonPolygonGroup() instead.") static void SwapPolygonPolygonGroup(FMeshDescription &MeshDescription
Data Fields
FMeshDescription FAppendSettings & AppendSettings
ETangentOptions bool bComputeTangent
ETangentOptions bool bForceRecomputeNormals = false
ETangentOptions bool bool bForceRecomputeTangents = false)
int32 bool bMergeIdenticalMaterials
int32 int32 int32 bool bRemoveEmptyPolygonGroup
float ComparisonThreshold
const FMeshDescription float ComparisonThreshold
FMeshDescription & DestinationMeshDescription
FRawMesh & DestinationRawMesh
int32 int32 DstLightmapIndex
TArray< uint32 > & FaceSmoothingMasks
int32 ELightmapUVVersion LightmapUVVersion
int32 int32 int32 ELightmapUVVersion LightmapUVVersion
FRawMesh const TMap< FName, int32 > & MaterialMap
FMeshDescription const TMap< int32, FName > & MaterialMap
const FMeshDescription & MeshDescription
int32 int32 int32 MinLightmapResolution
int32 bool TArray< FVector2D > & OutTexCoords
const FUVMapParameters TMap< FVertexInstanceID, FVector2D > & OutTexCoords
const float TMap< FVertexID, FVertexID > & OutVertexIDRemap
int32 ELightmapUVVersion const FOverlappingCorners & OverlappingCorners
int32 int32 int32 ELightmapUVVersion const FOverlappingCorners & OverlappingCorners
const FUVMapParameters & Params
TMap< FPolygonGroupID, FPolygonGroupID > & Remap
int32 SectionIndex
int32 SrcLightmapIndex
ETangentOptions TangentOptions
FMeshDescription & TargetMesh
int32 TextureResolution
int32 int32 int32 TriangleIndexEnd
int32 int32 TriangleIndexStart
int32 UVChannelIndex
const float WeldingThreshold
Detailed Description
Definition at line 27 of file MeshDescriptionOperations.h.
Member Typedef Documentation
FAppendSettings
typedef FStaticMeshOperations::FAppendSettings FMeshDescriptionOperations::FAppendSettings
Definition at line 39 of file MeshDescriptionOperations.h.
Member Enumeration Documentation
ETangentOptions
enum FMeshDescriptionOperations::ETangentOptions
Enumerator
None
BlendOverlappingNormals
IgnoreDegenerateTriangles
UseMikkTSpace
UseWeightedAreaAndAngle
Definition at line 30 of file MeshDescriptionOperations.h.
Member Function Documentation
UE_DEPRECATED() [1/24]
FMeshDescriptionOperations::UE_DEPRECATED (4. 25, "Use FMeshDescription::RemapPolygonGroups() instead.") &
References UE_DEPRECATED().
UE_DEPRECATED() [2/24]
FMeshDescriptionOperations::UE_DEPRECATED (4. 25, "Use FStaticMeshOperations::AddUVChannel() instead.") &
Add a UV channel to the MeshDescription.
References MeshDescription, and UE_DEPRECATED().
UE_DEPRECATED() [3/24]
FMeshDescriptionOperations::UE_DEPRECATED (4. 25, "Use FStaticMeshOperations::AppendMeshDescription() instead.") const &
References UE_DEPRECATED().
UE_DEPRECATED() [4/24]
FMeshDescriptionOperations::UE_DEPRECATED (4. 25, "Use FStaticMeshOperations::BuildWeldedVertexIDRemap() instead.") const &
References UE_DEPRECATED().
UE_DEPRECATED() [5/24]
FMeshDescriptionOperations::UE_DEPRECATED (4. 25, "Use FStaticMeshOperations::ComputeSHAHash() instead.") const &
Computes the SHA hash of all the attributes values in the MeshDescription.
References MeshDescription, and UE_DEPRECATED().
UE_DEPRECATED() [6/24]
FMeshDescriptionOperations::UE_DEPRECATED (4. 25, "Use FStaticMeshOperations::ConvertFromRawMesh() instead.") const &
Convert old FRawMesh format to MeshDescription.
References UE_DEPRECATED().
UE_DEPRECATED() [7/24]
FMeshDescriptionOperations::UE_DEPRECATED (4. 25, "Use FStaticMeshOperations::ConvertHardEdgesToSmoothGroup() instead.") const &
References UE_DEPRECATED().
UE_DEPRECATED() [8/24]
FMeshDescriptionOperations::UE_DEPRECATED (4. 25, "Use FStaticMeshOperations::ConvertSmoothGroupToHardEdges() instead.") const &
References DestinationMeshDescription, FaceSmoothingMasks, and UE_DEPRECATED().
UE_DEPRECATED() [9/24]
FMeshDescriptionOperations::UE_DEPRECATED (4. 25, "Use FStaticMeshOperations::ConvertToRawMesh() instead.") const &
Convert this mesh description into the old FRawMesh format.
Referenced by UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
UE_DEPRECATED() [10/24]
FMeshDescriptionOperations::UE_DEPRECATED (4. 25, "Use FStaticMeshOperations::CreatComputePolygonTangentsAndNormals() instead.") &
Compute normal, tangent and Bi-Normal for every polygon in the mesh description.
(this do not compute Vertex NTBs) It also remove the degenerated polygon from the mesh description
References UE_DEPRECATED().
UE_DEPRECATED() [11/24]
FMeshDescriptionOperations::UE_DEPRECATED (4. 25, "Use FStaticMeshOperations::CreateLightMapUVLayout() instead.") &
Find and pack UV charts for lightmap.
The packing algorithm uses a rasterization method, hence the resolution parameter.
If the given minimum resolution is not enough to handle all the charts, generation will fail.
Parameters
MeshDescription Edited mesh
SrcLightmapIndex index of the source UV channel
DstLightmapIndex index of the destination UV channel
MinLightmapResolution Minimum resolution used for the packing
LightmapUVVersion Algorithm version
OverlappingCorners Overlapping corners of the given mesh
Returns
UV layout correctly generated
References MeshDescription, SrcLightmapIndex, and UE_DEPRECATED().
UE_DEPRECATED() [12/24]
FMeshDescriptionOperations::UE_DEPRECATED (4. 25, "Use FStaticMeshOperations::CreateMikktTangents() instead.") &
Compute tangent and Bi-Normal using mikkt space for every vertex in the mesh description.
References MeshDescription, TangentOptions, and UE_DEPRECATED().
UE_DEPRECATED() [13/24]
FMeshDescriptionOperations::UE_DEPRECATED (4. 25, "Use FStaticMeshOperations::CreateNormals() instead.") &
Compute normal, tangent and Bi-Normal(only if bComputeTangent is true) for every vertex in the mesh description.
References UE_DEPRECATED().
UE_DEPRECATED() [14/24]
FMeshDescriptionOperations::UE_DEPRECATED (4. 25, "Use FStaticMeshOperations::FindOverlappingCorners() instead.") &
Find all overlapping vertex using the threshold in the mesh description.
References UE_DEPRECATED().
UE_DEPRECATED() [15/24]
FMeshDescriptionOperations::UE_DEPRECATED (4. 25, "Use FStaticMeshOperations::GenerateBoxUV() instead.") const &
Generate box UV mapping for the MeshDescription.
References MeshDescription, OutTexCoords, Params, and UE_DEPRECATED().
UE_DEPRECATED() [16/24]
FMeshDescriptionOperations::UE_DEPRECATED (4. 25, "Use FStaticMeshOperations::GenerateCylindricalUV() instead.") &
Generate cylindrical UV mapping for the MeshDescription.
References MeshDescription, OutTexCoords, Params, and UE_DEPRECATED().
UE_DEPRECATED() [17/24]
FMeshDescriptionOperations::UE_DEPRECATED (4. 25, "Use FStaticMeshOperations::GeneratePlanarUV() instead.") const &
Generate planar UV mapping for the MeshDescription.
References UE_DEPRECATED().
UE_DEPRECATED() [18/24]
FMeshDescriptionOperations::UE_DEPRECATED (4. 25, "Use FStaticMeshOperations::GenerateUniqueUVsForStaticMesh() instead.") const &
Create some UVs from the specified mesh description data.
References UE_DEPRECATED().
UE_DEPRECATED() [19/24]
FMeshDescriptionOperations::UE_DEPRECATED (4. 25, "Use FStaticMeshOperations::GetUVChartCount() instead.") &
Find all charts in the mesh description.
References UE_DEPRECATED().
UE_DEPRECATED() [20/24]
FMeshDescriptionOperations::UE_DEPRECATED (4. 25, "Use FStaticMeshOperations::HasVertexColor() instead.") const &
References MeshDescription, and UE_DEPRECATED().
UE_DEPRECATED() [21/24]
FMeshDescriptionOperations::UE_DEPRECATED (4. 25, "Use FStaticMeshOperations::InsertUVChannel() instead.") &
Insert a UV channel at the given index to the MeshDescription.
References UE_DEPRECATED().
UE_DEPRECATED() [22/24]
FMeshDescriptionOperations::UE_DEPRECATED (4. 25, "Use FStaticMeshOperations::RecomputeNormalsAndTangentsIfNeeded() instead.") &
References UE_DEPRECATED().
UE_DEPRECATED() [23/24]
FMeshDescriptionOperations::UE_DEPRECATED (4. 25, "Use FStaticMeshOperations::RemoveUVChannel() instead.") &
Remove the UV channel at the given index from the MeshDescription.
References MeshDescription, UE_DEPRECATED(), and UVChannelIndex.
UE_DEPRECATED() [24/24]
FMeshDescriptionOperations::UE_DEPRECATED (4. 25, "Use FStaticMeshOperations::SwapPolygonPolygonGroup() instead.") &
References UE_DEPRECATED().
Field Documentation
AppendSettings
FMeshDescription FAppendSettings& FMeshDescriptionOperations::AppendSettings
Definition at line 50 of file MeshDescriptionOperations.h.
bComputeTangent
ETangentOptions bool FMeshDescriptionOperations::bComputeTangent
Definition at line 67 of file MeshDescriptionOperations.h.
bForceRecomputeNormals
ETangentOptions bool FMeshDescriptionOperations::bForceRecomputeNormals = false
Definition at line 56 of file MeshDescriptionOperations.h.
bForceRecomputeTangents
ETangentOptions bool bool FMeshDescriptionOperations::bForceRecomputeTangents = false)
Definition at line 56 of file MeshDescriptionOperations.h.
bMergeIdenticalMaterials
int32 bool FMeshDescriptionOperations::bMergeIdenticalMaterials
Definition at line 105 of file MeshDescriptionOperations.h.
bRemoveEmptyPolygonGroup
int32 int32 int32 bool FMeshDescriptionOperations::bRemoveEmptyPolygonGroup
Definition at line 145 of file MeshDescriptionOperations.h.
ComparisonThreshold [1/2]
float FMeshDescriptionOperations::ComparisonThreshold
Definition at line 63 of file MeshDescriptionOperations.h.
ComparisonThreshold [2/2]
const FMeshDescription float FMeshDescriptionOperations::ComparisonThreshold
Definition at line 75 of file MeshDescriptionOperations.h.
DestinationMeshDescription
FMeshDescription & FMeshDescriptionOperations::DestinationMeshDescription
Definition at line 47 of file MeshDescriptionOperations.h.
Referenced by UE_DEPRECATED().
DestinationRawMesh
FRawMesh& FMeshDescriptionOperations::DestinationRawMesh
Definition at line 43 of file MeshDescriptionOperations.h.
DstLightmapIndex
int32 int32 FMeshDescriptionOperations::DstLightmapIndex
Definition at line 98 of file MeshDescriptionOperations.h.
FaceSmoothingMasks
TArray<uint32>& FMeshDescriptionOperations::FaceSmoothingMasks
Definition at line 148 of file MeshDescriptionOperations.h.
Referenced by UE_DEPRECATED().
LightmapUVVersion [1/2]
int32 ELightmapUVVersion FMeshDescriptionOperations::LightmapUVVersion
Definition at line 79 of file MeshDescriptionOperations.h.
LightmapUVVersion [2/2]
int32 int32 int32 ELightmapUVVersion FMeshDescriptionOperations::LightmapUVVersion
Definition at line 100 of file MeshDescriptionOperations.h.
MaterialMap [1/2]
FRawMesh const TMap<FName, int32>& FMeshDescriptionOperations::MaterialMap
Definition at line 43 of file MeshDescriptionOperations.h.
MaterialMap [2/2]
FMeshDescription const TMap<int32, FName>& FMeshDescriptionOperations::MaterialMap
Definition at line 47 of file MeshDescriptionOperations.h.
MeshDescription
const FMeshDescription& FMeshDescriptionOperations::MeshDescription
Definition at line 75 of file MeshDescriptionOperations.h.
Referenced by UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
MinLightmapResolution
int32 int32 int32 FMeshDescriptionOperations::MinLightmapResolution
Definition at line 99 of file MeshDescriptionOperations.h.
OutTexCoords [1/2]
const FUVMapParameters TMap< FVertexInstanceID, FVector2D > & FMeshDescriptionOperations::OutTexCoords
Definition at line 105 of file MeshDescriptionOperations.h.
Referenced by UE_DEPRECATED(), and UE_DEPRECATED().
OutTexCoords [2/2]
const FUVMapParameters TMap<FVertexInstanceID, FVector2D>& FMeshDescriptionOperations::OutTexCoords
Definition at line 121 of file MeshDescriptionOperations.h.
OutVertexIDRemap
const float TMap<FVertexID, FVertexID>& FMeshDescriptionOperations::OutVertexIDRemap
Definition at line 157 of file MeshDescriptionOperations.h.
OverlappingCorners [1/2]
int32 ELightmapUVVersion const FOverlappingCorners& FMeshDescriptionOperations::OverlappingCorners
Definition at line 79 of file MeshDescriptionOperations.h.
OverlappingCorners [2/2]
int32 int32 int32 ELightmapUVVersion const FOverlappingCorners& FMeshDescriptionOperations::OverlappingCorners
Definition at line 101 of file MeshDescriptionOperations.h.
Params
const FUVMapParameters & FMeshDescriptionOperations::Params
Definition at line 121 of file MeshDescriptionOperations.h.
Referenced by UE_DEPRECATED(), and UE_DEPRECATED().
Remap
TMap<FPolygonGroupID, FPolygonGroupID>& FMeshDescriptionOperations::Remap
Definition at line 132 of file MeshDescriptionOperations.h.
SectionIndex
int32 FMeshDescriptionOperations::SectionIndex
Definition at line 145 of file MeshDescriptionOperations.h.
SrcLightmapIndex
int32 FMeshDescriptionOperations::SrcLightmapIndex
Definition at line 79 of file MeshDescriptionOperations.h.
Referenced by UE_DEPRECATED().
TangentOptions
ETangentOptions FMeshDescriptionOperations::TangentOptions
Definition at line 56 of file MeshDescriptionOperations.h.
Referenced by UE_DEPRECATED().
TargetMesh
FMeshDescription& FMeshDescriptionOperations::TargetMesh
Definition at line 50 of file MeshDescriptionOperations.h.
TextureResolution
int32 FMeshDescriptionOperations::TextureResolution
Definition at line 105 of file MeshDescriptionOperations.h.
TriangleIndexEnd
int32 int32 int32 FMeshDescriptionOperations::TriangleIndexEnd
Definition at line 145 of file MeshDescriptionOperations.h.
TriangleIndexStart
int32 int32 FMeshDescriptionOperations::TriangleIndexStart
Definition at line 145 of file MeshDescriptionOperations.h.
UVChannelIndex
int32 FMeshDescriptionOperations::UVChannelIndex
Definition at line 113 of file MeshDescriptionOperations.h.
Referenced by UE_DEPRECATED().
WeldingThreshold
const float FMeshDescriptionOperations::WeldingThreshold
Definition at line 157 of file MeshDescriptionOperations.h.
The documentation for this class was generated from the following file:
Developer/MeshDescriptionOperations/Public/MeshDescriptionOperations.h