Unreal Engine 5.6 C++ API: FSharpPullKelvinletBrushOp Class Reference
FSharpPullKelvinletBrushOp Class Reference
#include "KelvinletBrushOp.h"
Public Member Functions
virtual void ApplyStamp (const FDynamicMesh3 *SrcMesh, const FSculptBrushStamp &Stamp, const TArray< int32 > &Vertices, TArray< FVector3d > &NewPositionsOut) override
virtual ESculptBrushOpTargetType GetBrushTargetType () const override
virtual bool IgnoreZeroMovements () const override
Public Member Functions inherited from FBaseKelvinletBrushOp
template<typename KelvinletType>
void ApplyKelvinlet (const KelvinletType &Kelvinlet, const FFrame3d &LocalFrame, const TArray< int32 > &Vertices, TArray< FVector3d > &NewPositionsOut) const
void SetBaseProperties (const FDynamicMesh3 *SrcMesh, const FSculptBrushStamp &Stamp)
Public Member Functions inherited from FMeshSculptBrushOp
virtual ~FMeshSculptBrushOp ()
virtual void ApplyStamp (const FDynamicMesh3 *Mesh, const FSculptBrushStamp &Stamp, const TArray< int32 > &Vertices, TArray< FVector3d > &NewValuesOut)=0
virtual void BeginStroke (const FDynamicMesh3 *Mesh, const FSculptBrushStamp &Stamp, const TArray< int32 > &InitialVertices)
virtual void CancelStroke ()
virtual void ConfigureOptions (const FSculptBrushOptions &Options)
virtual void EndStroke (const FDynamicMesh3 *Mesh, const FSculptBrushStamp &Stamp, const TArray< int32 > &FinalVertices)
virtual bool GetAlignStampToView () const
virtual EBrushRegionType GetBrushRegionType () const
const FMeshSculptFallofFunc & GetFalloff () const
template<typename PropType>
PropType * GetPropertySetAs ()
template<typename PropType>
const PropType * GetPropertySetAs () const
virtual EReferencePlaneType GetReferencePlaneType () const
virtual EStampAlignmentType GetStampAlignmentType () const
virtual bool SupportsVariableSpacing () const
virtual bool UseLastStampFrameOnZeroMovement () const
virtual bool UsesAlpha () const
virtual bool WantsStampRegionPlane () const
Additional Inherited Members
Public Types inherited from FMeshSculptBrushOp
enum class EBrushRegionType { LocalSphere , InfiniteCylinder , CylinderOnSphere }
enum class EReferencePlaneType { None , InitialROI , InitialROI_ViewAligned , WorkPlane }
enum class EStampAlignmentType { HitNormal , Camera , ReferencePlane , ReferenceSphere }
Data Fields inherited from FMeshSculptBrushOp
FSculptBrushOptions CurrentOptions
TSharedPtr< FMeshSculptFallofFunc > Falloff
TWeakObjectPtr< UMeshSculptBrushOpProps > PropertySet
Protected Member Functions inherited from FBaseKelvinletBrushOp
void ApplyFalloff (const FSculptBrushStamp &Stamp, const TArray< int32 > &Vertices, TArray< FVector3d > &NewPositionsOut) const
template<typename KelvinletType>
void DisplaceKelvinlet (const KelvinletType &Kelvinlet, const FFrame3d &LocalFrame, const TArray< int32 > &Vertices, TArray< FVector3d > &NewPositionsOut) const
template<typename KelvinletType>
void IntegrateKelvinlet (const KelvinletType &Kelvinlet, const FFrame3d &LocalFrame, const TArray< int32 > &Vertices, TArray< FVector3d > &NewPositionsOut, const double Dt, const int32 Steps) const
Protected Attributes inherited from FBaseKelvinletBrushOp
double IntegrationTime = 1.
const FDynamicMesh3 * Mesh
float Mu
float Nu
int32 NumSteps
float Size
Detailed Description
Definition at line 304 of file KelvinletBrushOp.h.
Member Function Documentation
ApplyStamp()
virtual void FSharpPullKelvinletBrushOp::ApplyStamp (const FDynamicMesh3 * SrcMesh, const FSculptBrushStamp & Stamp, const TArray< int32 > & Vertices, TArray< FVector3d > & NewPositionsOut) inline override virtual
Reimplemented from FBaseKelvinletBrushOp.
Definition at line 309 of file KelvinletBrushOp.h.
References Alpha, FBaseKelvinletBrushOp::ApplyFalloff(), FBaseKelvinletBrushOp::ApplyKelvinlet(), FSculptBrushStamp::Falloff, Force, FSculptBrushStamp::LocalFrame, FBaseKelvinletBrushOp::Mu, FBaseKelvinletBrushOp::Nu, UE::Geometry::TFrame3< RealType >::Origin, FSculptBrushStamp::PrevLocalFrame, FBaseKelvinletBrushOp::SetBaseProperties(), FBaseKelvinletBrushOp::Size, and UE::Geometry::TFrame3< RealType >::ToFrameVector().
GetBrushTargetType()
virtual ESculptBrushOpTargetType FSharpPullKelvinletBrushOp::GetBrushTargetType () const inline override virtual
Reimplemented from FMeshSculptBrushOp.
Definition at line 328 of file KelvinletBrushOp.h.
References ActivePlane.
IgnoreZeroMovements()
virtual bool FSharpPullKelvinletBrushOp::IgnoreZeroMovements () const inline override virtual
Reimplemented from FMeshSculptBrushOp.
Definition at line 333 of file KelvinletBrushOp.h.
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/MeshModelingToolset/Source/MeshModelingTools/Public/Sculpting/KelvinletBrushOp.h