Unreal Engine 5.6 C++ API: FLegacyEdModeWidgetHelper Class Reference
FLegacyEdModeWidgetHelper Class Reference
#include "LegacyEdModeWidgetHelpers.h"
Data Structures
struct FPropertyWidgetInfo
Structure that holds info about our optional property widget.
Public Member Functions
UNREALED_API FLegacyEdModeWidgetHelper ()
virtual ~FLegacyEdModeWidgetHelper ()=default
virtual UNREALED_API void ActorSelectionChangeNotify ()
virtual UNREALED_API bool AllowsViewportDragTool () const
virtual UNREALED_API bool AllowWidgetMove ()
virtual UNREALED_API bool CanCycleWidgetMode () const
virtual UNREALED_API void DrawHUD (FEditorViewportClient *ViewportClient, FViewport *Viewport, const FSceneView *View, FCanvas *Canvas)
virtual UNREALED_API EAxisList::Type GetCurrentWidgetAxis () const final
virtual UNREALED_API bool GetCustomDrawingCoordinateSystem (FMatrix &InMatrix, void *InData)
virtual UNREALED_API bool GetCustomInputCoordinateSystem (FMatrix &InMatrix, void *InData)
virtual UNREALED_API EAxisList::Type GetWidgetAxisToDraw (UE::Widget::EWidgetMode InWidgetMode) const
virtual UNREALED_API FVector GetWidgetLocation () const
virtual UNREALED_API FVector GetWidgetNormalFromCurrentAxis (void *InData)
virtual UNREALED_API bool HandleClick (FEditorViewportClient *InViewportClient, HHitProxy *HitProxy, const FViewportClick &Click)
virtual UNREALED_API bool InputDelta (FEditorViewportClient *InViewportClient, FViewport *InViewport, FVector &InDrag, FRotator &InRot, FVector &InScale)
virtual UNREALED_API void Render (const FSceneView *View, FViewport *Viewport, FPrimitiveDrawInterface *PDI)
virtual UNREALED_API void SetCurrentWidgetAxis (EAxisList::Type InAxis) final
virtual UNREALED_API bool ShouldDrawWidget () const
virtual UNREALED_API bool ShowModeWidgets () const
virtual UNREALED_API bool UsesPropertyWidgets () const
virtual UNREALED_API bool UsesTransformWidget () const
virtual UNREALED_API bool UsesTransformWidget (UE::Widget::EWidgetMode CheckMode) const
Static Public Member Functions
static UNREALED_API bool CanCreateWidgetForProperty (FProperty *InProp)
Returns true if this property can support creating a widget in the editor.
static UNREALED_API bool CanCreateWidgetForStructure (const UStruct *InPropStruct)
Returns true if this structure can support creating a widget in the editor.
static UNREALED_API bool ShouldCreateWidgetForProperty (FProperty *InProp)
See if we should create a widget for the supplied property when selecting an actor instance.
Static Public Attributes
static UNREALED_API const FName MD_MakeEditWidget
Value of UPROPERTY can be edited with a widget in the editor (translation, rotation)
static UNREALED_API const FName MD_ValidateWidgetUsing
Specifies a function used for validation of the current value of a property.
Protected Member Functions
UNREALED_API AActor * GetFirstSelectedActorInstance () const
Returns the first selected Actor, or NULL if there is no selection.
virtual UNREALED_API UObject * GetItemToTryDisplayingWidgetsFor (FTransform &OutWidgetToWorld) const
Finds the best item to display widgets for (preferring selected components over selected actors)
UNREALED_API void GetPropertyWidgetInfos (const UStruct *InStruct, const void *InContainer, TArray< FPropertyWidgetInfo > &OutInfos) const
Gets an array of property widget info structures for the given struct/class type for the given container.
Protected Attributes
bool bEditedPropertyIsTransform
Indicates.
EAxisList::Type CurrentWidgetAxis
The current axis that is being dragged on the widget.
int32 EditedPropertyIndex
If the property being edited is an array property, this is the index of the element we're currently dealing with.
FString EditedPropertyName
Name of the property currently being edited.
FEditorModeTools * Owner
Pointer back to the mode tools that we are registered with.
TScriptInterface< ILegacyEdModeWidgetInterface > ParentModeInterface
Friends
class FEditorModeRegistry
class UBaseLegacyWidgetEdMode
Detailed Description
Definition at line 26 of file LegacyEdModeWidgetHelpers.h.
Constructor & Destructor Documentation
FLegacyEdModeWidgetHelper()
UNREALED_API FLegacyEdModeWidgetHelper::FLegacyEdModeWidgetHelper ()
~FLegacyEdModeWidgetHelper()
virtual FLegacyEdModeWidgetHelper::~FLegacyEdModeWidgetHelper () virtual default
Member Function Documentation
ActorSelectionChangeNotify()
virtual UNREALED_API void FLegacyEdModeWidgetHelper::ActorSelectionChangeNotify () virtual
References ActorSelectionChangeNotify().
Referenced by ActorSelectionChangeNotify().
AllowsViewportDragTool()
virtual UNREALED_API bool FLegacyEdModeWidgetHelper::AllowsViewportDragTool () const virtual
References AllowsViewportDragTool().
Referenced by AllowsViewportDragTool().
AllowWidgetMove()
virtual UNREALED_API bool FLegacyEdModeWidgetHelper::AllowWidgetMove () virtual
CanCreateWidgetForProperty()
UNREALED_API bool FLegacyEdModeWidgetHelper::CanCreateWidgetForProperty (FProperty * InProp) static
Returns true if this property can support creating a widget in the editor.
CanCreateWidgetForStructure()
UNREALED_API bool FLegacyEdModeWidgetHelper::CanCreateWidgetForStructure (const UStruct * InPropStruct) static
Returns true if this structure can support creating a widget in the editor.
CanCycleWidgetMode()
virtual UNREALED_API bool FLegacyEdModeWidgetHelper::CanCycleWidgetMode () const virtual
DrawHUD()
virtual UNREALED_API void FLegacyEdModeWidgetHelper::DrawHUD (FEditorViewportClient * ViewportClient, FViewport * Viewport, const FSceneView * View, FCanvas * Canvas) virtual
Reimplemented in FEdMode.
GetCurrentWidgetAxis()
virtual UNREALED_API EAxisList::Type FLegacyEdModeWidgetHelper::GetCurrentWidgetAxis () const final virtual
GetCustomDrawingCoordinateSystem()
virtual UNREALED_API bool FLegacyEdModeWidgetHelper::GetCustomDrawingCoordinateSystem (FMatrix & InMatrix, void * InData) virtual
References GetCustomDrawingCoordinateSystem().
Referenced by GetCustomDrawingCoordinateSystem().
GetCustomInputCoordinateSystem()
virtual UNREALED_API bool FLegacyEdModeWidgetHelper::GetCustomInputCoordinateSystem (FMatrix & InMatrix, void * InData) virtual
References GetCustomInputCoordinateSystem().
Referenced by GetCustomInputCoordinateSystem().
GetFirstSelectedActorInstance()
UNREALED_API AActor * FLegacyEdModeWidgetHelper::GetFirstSelectedActorInstance () const protected
Returns the first selected Actor, or NULL if there is no selection.
GetItemToTryDisplayingWidgetsFor()
virtual UNREALED_API UObject * FLegacyEdModeWidgetHelper::GetItemToTryDisplayingWidgetsFor (FTransform & OutWidgetToWorld) const protected virtual
Finds the best item to display widgets for (preferring selected components over selected actors)
GetPropertyWidgetInfos()
UNREALED_API void FLegacyEdModeWidgetHelper::GetPropertyWidgetInfos (const UStruct * InStruct, const void * InContainer, TArray< FPropertyWidgetInfo > & OutInfos) const protected
Gets an array of property widget info structures for the given struct/class type for the given container.
Parameters
InStruct The type of structure/class to access widget info structures for.
InContainer The container of the given type.
OutInfos An array of widget info structures (output).
References InContainer.
GetWidgetAxisToDraw()
virtual UNREALED_API EAxisList::Type FLegacyEdModeWidgetHelper::GetWidgetAxisToDraw (UE::Widget::EWidgetMode InWidgetMode) const virtual
GetWidgetLocation()
virtual UNREALED_API FVector FLegacyEdModeWidgetHelper::GetWidgetLocation () const virtual
References FVector.
GetWidgetNormalFromCurrentAxis()
virtual UNREALED_API FVector FLegacyEdModeWidgetHelper::GetWidgetNormalFromCurrentAxis (void * InData) virtual
References FVector.
HandleClick()
virtual UNREALED_API bool FLegacyEdModeWidgetHelper::HandleClick (FEditorViewportClient * InViewportClient, HHitProxy * HitProxy, const FViewportClick & Click) virtual
Reimplemented in FEdMode.
References Click.
InputDelta()
virtual UNREALED_API bool FLegacyEdModeWidgetHelper::InputDelta (FEditorViewportClient * InViewportClient, FViewport * InViewport, FVector & InDrag, FRotator & InRot, FVector & InScale) virtual
Reimplemented in FEdMode, FPhysicsDebugMode, and FPhysicsManipulationEdMode.
References FVector.
Render()
virtual UNREALED_API void FLegacyEdModeWidgetHelper::Render (const FSceneView * View, FViewport * Viewport, FPrimitiveDrawInterface * PDI) virtual
Reimplemented in FEdMode, and FPhysicsDebugMode.
SetCurrentWidgetAxis()
virtual UNREALED_API void FLegacyEdModeWidgetHelper::SetCurrentWidgetAxis (EAxisList::Type InAxis) final virtual
ShouldCreateWidgetForProperty()
UNREALED_API bool FLegacyEdModeWidgetHelper::ShouldCreateWidgetForProperty (FProperty * InProp) static
See if we should create a widget for the supplied property when selecting an actor instance.
ShouldDrawWidget()
virtual UNREALED_API bool FLegacyEdModeWidgetHelper::ShouldDrawWidget () const virtual
Reimplemented in FPhysicsDebugMode, and FPhysicsManipulationEdMode.
ShowModeWidgets()
virtual UNREALED_API bool FLegacyEdModeWidgetHelper::ShowModeWidgets () const virtual
UsesPropertyWidgets()
virtual UNREALED_API bool FLegacyEdModeWidgetHelper::UsesPropertyWidgets () const virtual
Reimplemented in FEdMode.
References UsesPropertyWidgets().
Referenced by UsesPropertyWidgets().
UsesTransformWidget() [1/2]
virtual UNREALED_API bool FLegacyEdModeWidgetHelper::UsesTransformWidget () const virtual
Reimplemented in FEdMode, and FPhysicsManipulationEdMode.
UsesTransformWidget() [2/2]
virtual UNREALED_API bool FLegacyEdModeWidgetHelper::UsesTransformWidget (UE::Widget::EWidgetMode CheckMode) const virtual
Reimplemented in FEdMode.
Friends And Related Symbol Documentation
FEditorModeRegistry
friend class FEditorModeRegistry friend
Definition at line 28 of file LegacyEdModeWidgetHelpers.h.
References FEditorModeRegistry.
Referenced by FEditorModeRegistry.
UBaseLegacyWidgetEdMode
friend class UBaseLegacyWidgetEdMode friend
Definition at line 29 of file LegacyEdModeWidgetHelpers.h.
References UBaseLegacyWidgetEdMode.
Referenced by UBaseLegacyWidgetEdMode.
Field Documentation
bEditedPropertyIsTransform
bool FLegacyEdModeWidgetHelper::bEditedPropertyIsTransform protected
Indicates.
Definition at line 114 of file LegacyEdModeWidgetHelpers.h.
CurrentWidgetAxis
EAxisList::Type FLegacyEdModeWidgetHelper::CurrentWidgetAxis protected
The current axis that is being dragged on the widget.
Definition at line 117 of file LegacyEdModeWidgetHelpers.h.
EditedPropertyIndex
int32 FLegacyEdModeWidgetHelper::EditedPropertyIndex protected
If the property being edited is an array property, this is the index of the element we're currently dealing with.
Definition at line 111 of file LegacyEdModeWidgetHelpers.h.
EditedPropertyName
FString FLegacyEdModeWidgetHelper::EditedPropertyName protected
Name of the property currently being edited.
Definition at line 108 of file LegacyEdModeWidgetHelpers.h.
MD_MakeEditWidget
UNREALED_API const FName FLegacyEdModeWidgetHelper::MD_MakeEditWidget static
Value of UPROPERTY can be edited with a widget in the editor (translation, rotation)
Definition at line 79 of file LegacyEdModeWidgetHelpers.h.
MD_ValidateWidgetUsing
UNREALED_API const FName FLegacyEdModeWidgetHelper::MD_ValidateWidgetUsing static
Specifies a function used for validation of the current value of a property.
The function returns a string that is empty if the value is valid, or contains an error description if the value is invalid
Definition at line 81 of file LegacyEdModeWidgetHelpers.h.
Owner
FEditorModeTools* FLegacyEdModeWidgetHelper::Owner protected
Pointer back to the mode tools that we are registered with.
Definition at line 120 of file LegacyEdModeWidgetHelpers.h.
ParentModeInterface
TScriptInterface<ILegacyEdModeWidgetInterface> FLegacyEdModeWidgetHelper::ParentModeInterface protected
Definition at line 122 of file LegacyEdModeWidgetHelpers.h.
The documentation for this class was generated from the following file:
Editor/UnrealEd/Public/Tools/LegacyEdModeWidgetHelpers.h