Unreal Engine 5.6 C++ API: UE::FPropertyPathNameTree::FConstIterator Class Reference
UE::FPropertyPathNameTree::FConstIterator Class Reference
#include "PropertyPathNameTree.h"
Public Member Functions
FConstIterator (const TMap< FKey, FValue >::TConstIterator &InNodeIt)
FName GetName () const
FConstNode GetNode () const
FPropertyTypeName GetType () const
operator bool () const
bool operator!= (const FConstIterator &Rhs) const
FConstIterator & operator++ ()
bool operator== (const FConstIterator &Rhs) const
Private Attributes
TMap< FKey, FValue >::TConstIterator NodeIt
Detailed Description
Definition at line 111 of file PropertyPathNameTree.h.
Constructor & Destructor Documentation
FConstIterator()
UE::FPropertyPathNameTree::FConstIterator::FConstIterator (const TMap< FKey, FValue >::TConstIterator & InNodeIt) inline explicit
Definition at line 114 of file PropertyPathNameTree.h.
References NodeIt.
Referenced by operator!=(), operator++(), and operator==().
Member Function Documentation
GetName()
FName UE::FPropertyPathNameTree::FConstIterator::GetName () const inline
Definition at line 126 of file PropertyPathNameTree.h.
References NodeIt.
GetNode()
FConstNode UE::FPropertyPathNameTree::FConstIterator::GetNode () const inline
Definition at line 128 of file PropertyPathNameTree.h.
References NodeIt.
GetType()
FPropertyTypeName UE::FPropertyPathNameTree::FConstIterator::GetType () const inline
Definition at line 127 of file PropertyPathNameTree.h.
References NodeIt.
operator bool()
UE::FPropertyPathNameTree::FConstIterator::operator bool () const inline explicit
Definition at line 121 of file PropertyPathNameTree.h.
References NodeIt.
operator!=()
bool UE::FPropertyPathNameTree::FConstIterator::operator!= (const FConstIterator & Rhs) const inline
Definition at line 124 of file PropertyPathNameTree.h.
References FConstIterator(), and NodeIt.
operator++()
FConstIterator & UE::FPropertyPathNameTree::FConstIterator::operator++ () inline
Definition at line 119 of file PropertyPathNameTree.h.
References FConstIterator(), and NodeIt.
operator==()
bool UE::FPropertyPathNameTree::FConstIterator::operator== (const FConstIterator & Rhs) const inline
Definition at line 123 of file PropertyPathNameTree.h.
References FConstIterator(), and NodeIt.
Field Documentation
NodeIt
TMap<FKey,FValue>::TConstIterator UE::FPropertyPathNameTree::FConstIterator::NodeIt private
Definition at line 131 of file PropertyPathNameTree.h.
Referenced by FConstIterator(), GetName(), GetNode(), GetType(), operator bool(), operator!=(), operator++(), and operator==().
The documentation for this class was generated from the following file:
Runtime/CoreUObject/Internal/UObject/PropertyPathNameTree.h