Unreal Engine 5.6 C++ API: UHierarchicalInstancedStaticMeshComponent Class Reference
UHierarchicalInstancedStaticMeshComponent Class Reference
#include "HierarchicalInstancedStaticMeshComponent.h"
Data Structures
class FClusterBuilder
struct FClusterTree
Public Member Functions
virtual int32 AddInstance (const FTransform &InstanceTransform, bool bWorldSpace=false) override
virtual TArray< int32 > AddInstances (const TArray< FTransform > &InstanceTransforms, bool bShouldReturnIndices, bool bWorldSpace=false, bool bUpdateNavigation=true) override
void ApplyBuildTreeAsync (ENamedThreads::Type CurrentThread, const FGraphEventRef &MyCompletionGraphEvent, TSharedRef< FClusterBuilder, ESPMode::ThreadSafe > Builder, double StartTime)
virtual void ApplyComponentInstanceData (struct FInstancedStaticMeshComponentInstanceData *InstancedMeshData) override
Applies the cached component instance data to a newly blueprint constructed component.
virtual bool BatchUpdateInstancesData (int32 StartInstanceIndex, int32 NumInstances, FInstancedStaticMeshInstanceData *StartInstanceData, bool bMarkRenderStateDirty=false, bool bTeleport=false) override
virtual bool BatchUpdateInstancesTransform (int32 StartInstanceIndex, int32 NumInstances, const FTransform &NewInstancesTransform, bool bWorldSpace=false, bool bMarkRenderStateDirty=false, bool bTeleport=false) override
virtual bool BatchUpdateInstancesTransforms (int32 StartInstanceIndex, const TArray< FTransform > &NewInstancesTransforms, bool bWorldSpace=false, bool bMarkRenderStateDirty=false, bool bTeleport=false) override
virtual bool BatchUpdateInstancesTransforms (int32 StartInstanceIndex, TArrayView< const FTransform > NewInstancesTransforms, bool bWorldSpace, bool bMarkRenderStateDirty, bool bTeleport) override
this is array view version of the UFUNCTION, blueprints do not support ArrayViews at the time of adding this one
bool BuildTreeIfOutdated (bool Async, bool ForceUpdate)
virtual FBoxSphereBounds CalcBounds (const FTransform &BoundTransform) const override
virtual void ClearInstances () override
virtual FPrimitiveSceneProxy * CreateSceneProxy () override
int32 DesiredInstancesPerLeaf ()
Heuristic for the number of leaves in the tree.
FVector GetAverageScale () const
virtual TArray< int32 > GetInstancesOverlappingBox (const FBox &Box, bool bBoxInWorldSpace=true) const override
virtual TArray< int32 > GetInstancesOverlappingSphere (const FVector &Center, float Radius, bool bSphereInWorldSpace=true) const override
virtual int32 GetNumRenderInstances () const
int32 GetOverlappingBoxCount (const FBox &Box) const
Get the number of instances that overlap a given box.
void GetOverlappingBoxTransforms (const FBox &Box, TArray< FTransform > &OutTransforms) const
Get the transforms of instances inside the provided box.
int32 GetOverlappingSphereCount (const FSphere &Sphere) const
Get the number of instances that overlap a given sphere.
virtual void GetResourceSizeEx (FResourceSizeEx &CumulativeResourceSize) override
void GetTree (TArray< FClusterNode > &OutClusterTree) const
EHISMViewRelevanceType GetViewRelevanceType () const
bool IsAsyncBuilding () const
bool IsTreeFullyBuilt () const
virtual void PostEditChangeChainProperty (FPropertyChangedChainEvent &PropertyChangedEvent) override
virtual void PostEditImport () override
virtual void PostEditUndo () override
virtual void PostLoad () override
virtual void PostStaticMeshCompilation () override
virtual void PreAllocateInstancesMemory (int32 AddedInstanceCount) override
Preallocated memory to include the new added instances count, to prevent reallloc during the add operation.
virtual void PropagateLightingScenarioChange () override
virtual bool RemoveInstance (int32 InstanceIndex) override
virtual bool RemoveInstances (const TArray< int32 > &InstancesToRemove) override
virtual bool RemoveInstances (const TArray< int32 > &InstancesToRemove, bool bInstanceArrayAlreadySortedInReverseOrder) override
Remove the instances specified.
virtual void Serialize (FArchive &Ar) override
virtual bool SetCustomData (int32 InstanceIndex, TArrayView< const float > InCustomData, bool bMarkRenderStateDirty=false) override
Per Instance Custom Data.
virtual bool SetCustomDataValue (int32 InstanceIndex, int32 CustomDataIndex, float CustomDataValue, bool bMarkRenderStateDirty=false) override
virtual bool SupportsRemoveSwap () const override
Returns true if RemoveAtSwap is enabled.
void UpdateDensityScaling ()
Will apply current density scaling, if enabled.
virtual bool UpdateInstanceTransform (int32 InstanceIndex, const FTransform &NewInstanceTransform, bool bWorldSpace, bool bMarkRenderStateDirty=false, bool bTeleport=false) override
Public Member Functions inherited from UInstancedStaticMeshComponent
FPrimitiveInstanceId AddInstanceById (const FTransform &InstanceTransforms, bool bWorldSpace=false)
TArray< FPrimitiveInstanceId > AddInstancesById (const TArrayView< const FTransform > &InstanceTransforms, bool bWorldSpace=false, bool bUpdateNavigation=true)
Preliminary ID-based interface.
virtual bool BatchUpdateInstancesTransforms (int32 StartInstanceIndex, const TArray< FTransform > &NewInstancesTransforms, const TArray< FTransform > &NewInstancesPrevTransforms, bool bWorldSpace=false, bool bMarkRenderStateDirty=false, bool bTeleport=false)
Update the transform for an array of instances.
virtual void BeginCacheForCookedPlatformData (const ITargetPlatform *TargetPlatform) override
See: UObject::BeginCacheForCookedPlatformData.
virtual void BeginDestroy () override
virtual bool BuildTextureStreamingDataImpl (ETextureStreamingBuildType BuildType, EMaterialQualityLevel::Type QualityLevel, ERHIFeatureLevel::Type FeatureLevel, TSet< FGuid > &DependentResources, bool &bOutSupportsBuildTextureStreamingData) override
Build the data to compute accuracte StreaminTexture data.
virtual bool CanEditChange (const FProperty *InProperty) const override
virtual bool CanEditSimulatePhysics () override
void ClearInstanceSelection ()
Deselect all instances.
virtual void CollectPSOPrecacheData (const FPSOPrecacheParams &BasePrecachePSOParams, FMaterialInterfacePSOPrecacheParamsList &OutParams) override
Precache all PSOs which can be used by the component.
virtual bool ComponentIsTouchingSelectionBox (const FBox &InSelBBox, const bool bConsiderOnlyBSP, const bool bMustEncompassEntireComponent) const override
virtual bool ComponentIsTouchingSelectionFrustum (const FConvexVolume &InFrustum, const bool bConsiderOnlyBSP, const bool bMustEncompassEntireComponent) const override
virtual void ComputeHLODHash (class FHLODHashBuilder &HashBuilder) const override
virtual bool DoCustomNavigableGeometryExport (FNavigableGeometryExport &GeomExport) const override
virtual TArray< Chaos::FPhysicsObject * > GetAllPhysicsObjects () const override
virtual FBodyInstance * GetBodyInstance (FName BoneName=NAME_None, bool bGetWelded=true, int32 Index=INDEX_NONE) const override
virtual void GetComponentChildElements (TArray< FTypedElementHandle > &OutElementHandles, const bool bAllowCreate=true) override
virtual TStructOnScope< FActorComponentInstanceData > GetComponentInstanceData () const override
const TSharedPtr< FISMCInstanceDataSceneProxy, ESPMode::ThreadSafe > & GetInstanceDataSceneProxy () const
FORCEINLINE int32 GetInstanceIndexForId (FPrimitiveInstanceId InstanceId) const
Fetches current instance index for a given InstanceId.
bool GetInstancePrevTransform (int32 InstanceIndex, FTransform &OutInstanceTransform, bool bWorldSpace=false) const
Get the prev transform for the instance specified.
void GetInstancesMinMaxScale (FVector &MinScale, FVector &MaxScale) const
virtual void GetLightAndShadowMapMemoryUsage (int32 &LightMapMemoryUsage, int32 &ShadowMapMemoryUsage) const override
virtual bool GetMaterialStreamingData (int32 MaterialIndex, FPrimitiveMaterialInfo &MaterialData) const override
Get material, UV density and bounds for a given material index.
virtual FBox GetNavigationBounds () const override
virtual void GetNavigationData (FNavigationRelevantData &Data) const override
int32 GetNumInstances () const
TSharedPtr< FISMCInstanceDataSceneProxy, ESPMode::ThreadSafe > GetOrCreateInstanceDataSceneProxy ()
virtual Chaos::FPhysicsObject * GetPhysicsObjectById (Chaos::FPhysicsObjectId Id) const override
FORCEINLINE int32 GetRenderIndex (int32 InInstanceIndex) const
Returns the render instance buffer index.
virtual FMatrix GetRenderMatrix () const override
virtual void GetStaticLightingInfo (FStaticLightingPrimitiveInfo &OutPrimitiveInfo, const TArray< ULightComponent * > &InRelevantLights, const FLightingBuildOptions &Options) override
virtual FBox GetStreamingBounds () const override
virtual void GetStreamingRenderAssetInfo (FStreamingTextureLevelContext &LevelContext, TArray< FStreamingRenderAssetPrimitiveInfo > &OutStreamingRenderAssets) const override
Get the StreaminTexture data.
virtual float GetTextureStreamingTransformScale () const override
Get the scale comming form the component, when computing StreamingTexture data.
FPrimitiveMaterialPropertyDescriptor GetUsedMaterialPropertyDesc (ERHIFeatureLevel::Type FeatureLevel) const
wrapper which is public so we can implement the LIST ISM command
void InvalidateInstanceDataTracking ()
Clears all the updated instance tracking data AND instance ID association, also forcing a full update of the instance data the next time it is flushed.
virtual bool IsCachedCookedPlatformDataLoaded (const ITargetPlatform *TargetPlatform) override
See: UObject::IsCachedCookedPlatformDataLoaded.
virtual bool IsHLODRelevant () const override
bool IsInstanceSelected (int32 InInstanceIndex) const
Check to see if an instance is selected.
virtual bool IsInstanceTouchingSelectionBox (int32 InstanceIndex, const FBox &InBox, const bool bMustEncompassEntireInstance) const
virtual bool IsInstanceTouchingSelectionFrustum (int32 InstanceIndex, const FConvexVolume &InFrustum, const bool bMustEncompassEntireInstance) const
virtual bool IsNavigationRelevant () const override
bool IsValidId (FPrimitiveInstanceId InstanceId)
virtual bool LineTraceComponent (FHitResult &OutHit, const FVector Start, const FVector End, const FCollisionQueryParams &Params) override
FInstanceDataFlags MakeInstanceDataFlags (bool bAnyMaterialHasPerInstanceRandom, bool bAnyMaterialHasPerInstanceCustomData) const
virtual void OnRegister () override
virtual void OnUnregister () override
virtual void OnUpdateTransform (EUpdateTransformFlags UpdateTransformFlags, ETeleportType Teleport) override
virtual bool OverlapComponent (const FVector &Pos, const FQuat &Rot, const FCollisionShape &CollisionShape) const override
virtual void PartialNavigationUpdate (int32 InstanceIdx)
Request to navigation system to update only part of navmesh occupied by specified instance.
virtual void PartialNavigationUpdates (TConstArrayView< FTransform > InstanceTransforms)
Request to navigation system to update only part of navmesh occupied specified instances transforms.
void PreApplyComponentInstanceData (struct FInstancedStaticMeshComponentInstanceData *ComponentInstanceData)
Handle changes that must happen before the proxy is recreated.
virtual void PreSave (FObjectPreSaveContext ObjectSaveContext) override
void RemoveInstanceById (FPrimitiveInstanceId InstanceId)
virtual void RemoveInstancesById (const TArrayView< const FPrimitiveInstanceId > &InstanceIds, bool bUpdateNavigation=true)
void SelectInstance (bool bInSelected, int32 InInstanceIndex, int32 InInstanceCount=1)
Select/deselect an instance or group of instances.
virtual void SendRenderInstanceData_Concurrent () override
void SetBakedLightingDataChanged (int32 InInstanceIndex)
Mark the "shadowmap" or lightmap uv as modified for the instance since this is stored in external data.
void SetBakedLightingDataChangedAll ()
Mark the "shadowmap" or lightmap uv as modified for all the instances since this is stored in external data.
virtual bool SetCustomData (int32 InstanceIndexStart, int32 InstanceIndexEnd, TConstArrayView< float > CustomDataFloats, bool bMarkRenderStateDirty=false)
void SetCustomDataById (const TArrayView< const FPrimitiveInstanceId > &InstanceIds, TArrayView< const float > CustomDataFloats)
void SetCustomDataById (FPrimitiveInstanceId InstanceId, TArrayView< const float > CustomDataFloats)
void SetCustomDataValueById (FPrimitiveInstanceId InstanceId, int32 CustomDataIndex, float CustomDataValue)
void SetHasPerInstancePrevTransforms (bool bInHasPreviousTransforms)
void SetPreviousTransformById (FPrimitiveInstanceId InstanceId, const FTransform &NewPrevInstanceTransform, bool bWorldSpace=false)
void SetRemoveSwap ()
Sets to use RemoveAtSwap on instance removal.
void SetUseConservativeBounds (bool bValue)
Sets whether to use conservative bounds.
virtual bool ShouldCreatePhysicsState () const override
virtual bool ShouldSkipDirtyAreaOnAddOrRemove () const override
virtual bool SupportsStaticLighting () const override
Whether the component type supports static lighting.
virtual bool SweepComponent (FHitResult &OutHit, const FVector Start, const FVector End, const FQuat &ShapRotation, const FCollisionShape &CollisionShape, bool bTraceComplex=false) override
UE_DEPRECATED (5.0, "Use AddInstance or AddInstances with bWorldSpace set to true.") UFUNCTION()) int32 AddInstanceWorldSpace(const FTransform &WorldTransform)
Add an instance to this component.
UE_DEPRECATED (5.4, "This function has been added only for the purposes of moving LWI code outside of the engine. Don't use it, it will be removed soon.") void OnPostPopulatePerInstanceData()
UFUNCTION () 1 bool GetInstanceTransform(int32 InstanceIndex
Get the transform for the instance specified.
UFUNCTION () 1 bool IsValidInstance(int32 InstanceIndex) const
Does the given index map to a valid instance in this component?
UFUNCTION () 1 int32 GetInstanceCount() const
Get the number of instances in this component.
UFUNCTION () 1 virtual bool BatchUpdateInstancesTransform(int32 StartInstanceIndex
Update the transform for a number of instances.
UFUNCTION () 1 virtual bool BatchUpdateInstancesTransforms(int32 StartInstanceIndex
Update the transform for an array of instances.
UFUNCTION () 1 virtual bool RemoveInstance(int32 InstanceIndex)
Remove the instance specified.
UFUNCTION () 1 virtual bool RemoveInstances(const TArray< int32 > &InstancesToRemove)
Remove the instances specified.
UFUNCTION () 1 virtual bool SetCustomDataValue(int32 InstanceIndex
Update custom data for specific instance.
UFUNCTION () 1 virtual bool UpdateInstanceTransform(int32 InstanceIndex
Update the transform for the instance specified.
UFUNCTION () 1 virtual int32 AddInstance(const FTransform &InstanceTransform
Add an instance to this component.
UFUNCTION () 1 virtual TArray< int32 > AddInstances(const TArray< FTransform > &InstanceTransforms
Add multiple instances to this component.
UFUNCTION () 1 virtual TArray< int32 > GetInstancesOverlappingBox(const FBox &Box
Returns the instances with instance bounds overlapping the specified box.
UFUNCTION () 1 virtual TArray< int32 > GetInstancesOverlappingSphere(const FVector &Center
Returns the instances with instance bounds overlapping the specified sphere.
UFUNCTION () 1 virtual void ClearInstances()
Clear all instances being rendered by this component.
UFUNCTION () 1 virtual void SetNumCustomDataFloats(int32 InNumCustomDataFloats)
Update number of custom data entries per instance.
UFUNCTION () 1 void SetCullDistances(int32 StartCullDistance
Sets the fading start and culling end distances for this component.
UFUNCTION () 1 void SetLODDistanceScale(float InLODDistanceScale)
Sets the LOD scale.
UFUNCTION () float GetLODDistanceScale() const
Gets the current LOD scale.
UFUNCTION () void GetCullDistances(int32 &OutStartCullDistance
Gets the fading start and culling end distances for this component.
virtual void UpdateBounds () override
void UpdateComponentTransform (EUpdateTransformFlags UpdateTransformFlags, ETeleportType Teleport)
void UpdateInstanceTransformById (FPrimitiveInstanceId InstanceId, const FTransform &NewInstanceTransform, bool bWorldSpace=false, bool bTeleport=false)
UPROPERTY () TArray< int32 > InstanceReorderTable
Mapping from PerInstanceSMData order to instance render buffer order.
Public Member Functions inherited from UStaticMeshComponent
virtual ~UStaticMeshComponent ()
virtual UObject const * AdditionalStatObject () const override
virtual void AddMapBuildDataGUIDs (TSet< FGuid > &InGUIDs) const override
virtual FStaticMeshStaticLightingMesh * AllocateStaticLightingMesh (int32 LODIndex, const TArray< ULightComponent * > &InRelevantLights)
Allocates an implementation of FStaticLightingMesh that will handle static lighting for this component.
virtual bool AllowsAsyncPhysicsStateCreation () const override
virtual bool AllowsAsyncPhysicsStateDestruction () const override
void ApplyComponentInstanceData (struct FStaticMeshComponentInstanceData *ComponentInstanceData)
virtual bool AreNativePropertiesIdenticalTo (UObject *Other) const override
virtual void BeginPlay () override
bool CanMeshPaintTextureColors () const
bool CanMeshPaintVertexColors () const
virtual void CheckForErrors () override
virtual uint32 ComputeHashTextureStreamingBuiltData () const override
virtual HHitProxy * CreateMeshHitProxy (int32 SectionIndex, int32 MaterialIndex) const override
virtual void CreateRenderState_Concurrent (FRegisterComponentContext *Context) override
DECLARE_DELEGATE_RetVal (const Nanite::FResources *, FOnGetNaniteResources)
Called during scene proxy creation to get the Nanite resource data.
DECLARE_EVENT_OneParam (UStaticMeshComponent, FOnStaticMeshChanged, UStaticMeshComponent *)
Called when the static mesh changes.
virtual bool DoesSocketExist (FName InSocketName) const override
virtual void ExportCustomProperties (FOutputDevice &Out, uint32 Indent) override
int32 GetBlueprintCreatedComponentIndex () const
Get this components index in its parents blueprint created components array (used for matching instance data)
virtual class UBodySetup * GetBodySetup () override
virtual void GetDefaultMaterialSlotsOverlayMaterial (TArray< TObjectPtr< UMaterialInterface > > &OutMaterialSlotOverlayMaterials) const override
Get all default LOD sections overlay materials used by a mesh.
virtual FString GetDetailedInfoInternal () const override
virtual float GetDiffuseBoost (int32 ElementIndex) const override
virtual UMaterialInterface * GetEditorMaterial (int32 MaterialIndex) const override
virtual float GetEmissiveBoost (int32 ElementIndex) const override
virtual bool GetEstimatedLightAndShadowMapMemoryUsage (int32 &TextureLightMapMemoryUsage, int32 &TextureShadowMapMemoryUsage, int32 &VertexLightMapMemoryUsage, int32 &VertexShadowMapMemoryUsage, int32 &StaticLightingResolution, bool &bIsUsingTextureMapping, bool &bHasLightmapTexCoords) const
Returns the light and shadow map memory for this primite in its out variables.
virtual void GetEstimatedLightMapResolution (int32 &Width, int32 &Height) const
Returns the lightmap resolution used for this primitive instance in the case of it supporting texture light/ shadow maps.
FORCEINLINE int32 GetForcedLodModel () const
FORCEINLINE bool GetForceNaniteForMasked () const
virtual bool GetLightMapResolution (int32 &Width, int32 &Height) const override
virtual UMaterialInterface * GetMaterial (int32 MaterialIndex) const final
virtual UMaterialInterface * GetMaterialFromCollisionFaceIndex (int32 FaceIndex, int32 &SectionIndex) const override
virtual int32 GetMaterialIndex (FName MaterialSlotName) const override
virtual bool GetMaterialPropertyPath (int32 ElementIndex, UObject *&OutOwner, FString &OutPropertyPath, FProperty *&OutProperty) override
virtual TArray< FName > GetMaterialSlotNames () const override
const FMeshMapBuildData * GetMeshMapBuildData (const FStaticMeshComponentLODInfo &LODInfo, bool bCheckForResourceCluster=true) const
virtual UTexture * GetMeshPaintTexture () const override
Get the mesh paint texture set on this component.
virtual int32 GetMeshPaintTextureCoordinateIndex () const override
Get the default coordinate index for painting to the mesh paint texture on this component.
int32 GetMeshPaintTextureResolution () const
Returns the size to use when creating a mesh paint texture on this component.
FORCEINLINE int32 GetMinLOD () const
UMaterialInterface * GetNaniteAuditMaterial (int32 MaterialIndex) const
virtual const Nanite::FResources * GetNaniteResources () const
virtual int32 GetNumMaterials () const override
FORCEINLINE bool GetOverrideMinLOD () const
virtual void GetPrimitiveStats (FPrimitiveStats &PrimitiveStats) const override
virtual bool GetShadowIndirectOnly () const override
class UStaticMeshSocket const * GetSocketByName (FName InSocketName) const
Returns the named socket on the static mesh component.
virtual FTransform GetSocketTransform (FName InSocketName, ERelativeTransformSpace TransformSpace=RTS_World) const override
virtual ELightMapInteractionType GetStaticLightingType () const override
virtual int32 GetStaticLightMapResolution () const override
TObjectPtr< UStaticMesh > GetStaticMesh () const
Get the StaticMesh used by this instance.
virtual float GetStreamingScale () const override
virtual void GetTextureLightAndShadowMapMemoryUsage (int32 InWidth, int32 InHeight, int32 &OutLightMapMemoryUsage, int32 &OutShadowMapMemoryUsage) const
Get the memory used for texture-based light and shadow maps of the given width and height.
virtual void GetUsedMaterials (TArray< UMaterialInterface * > &OutMaterials, bool bGetDebugMaterials=false) const final
virtual void GetUsedTextures (TArray< UTexture * > &OutTextures, EMaterialQualityLevel::Type QualityLevel) override
FColor GetWireframeColor () const
Returns the wireframe color to use for this component.
virtual bool HasAnySockets () const override
virtual bool HasLightmapTextureCoordinates () const
Returns true if the static mesh the component uses has valid lightmap texture coordinates.
virtual bool HasValidNaniteData () const
Returns true if the component has valid Nanite render data.
virtual bool HasValidSettingsForStaticLighting (bool bOverlookInvalidComponents) const override
Returns true if the component is static AND has the right static mesh setup to support lightmaps.
virtual void ImportCustomProperties (const TCHAR *SourceText, FFeedbackContext *Warn) override
virtual void InitializeComponent () override
virtual void InvalidateLightingCacheDetailed (bool bInvalidateBuildEnqueuedLighting, bool bTranslationOnly) override
virtual bool IsCompiling () const override
FORCEINLINE bool IsDisallowNanite () const
FORCEINLINE bool IsForceDisableNanite () const
FORCEINLINE bool IsForceNaniteForMasked () const
virtual bool IsMaterialSlotNameValid (FName MaterialSlotName) const override
virtual bool IsPostLoadThreadSafe () const override
virtual bool IsPrecomputedLightingValid () const override
FORCEINLINE bool IsReverseCulling () const
virtual bool IsShown (const FEngineShowFlags &ShowFlags) const override
virtual void OnAsyncDestroyPhysicsStateEnd_GameThread () override
virtual FOnGetNaniteResources & OnGetNaniteResources ()
virtual const FOnGetNaniteResources & OnGetNaniteResources () const
void OnMeshRebuild (bool bRenderDataChanged)
virtual FOnStaticMeshChanged & OnStaticMeshChanged ()
virtual void PostApplyToComponent () override
virtual void PostDuplicate (bool bDuplicateForPIE) override
virtual void PostEditChangeProperty (FPropertyChangedEvent &PropertyChangedEvent) override
virtual void PostInitProperties () override
virtual void PostReinitProperties () override
virtual void PrecachePSOs () override
virtual void PreEditUndo () override
virtual void PreStaticMeshCompilation ()
virtual bool PrestreamMeshLODs (float Seconds) override
virtual void QuerySupportedSockets (TArray< FComponentSocketDescription > &OutSockets) const override
virtual void RegisterLODStreamingCallback (FLODStreamingCallback &&Callback, int32 LODIdx, float TimeoutSecs, bool bOnStreamIn) override
Register a one-time callback that will be called when criteria met.
virtual void RegisterLODStreamingCallback (FLODStreamingCallback &&CallbackStreamingStart, FLODStreamingCallback &&CallbackStreamingDone, float TimeoutStartSecs, float TimeoutDoneSecs) override
Register a one-time callback that will be called when streaming starts or ends.
void ReleaseResources ()
virtual bool RemapActorTextureStreamingBuiltDataToLevel (const class UActorTextureStreamingBuildDataComponent *InActorTextureBuildData) override
void RemoveInstanceVertexColorsFromLOD (int32 LODToRemoveColorsFrom)
Removes instance vertex colors from the specified LOD.
virtual bool RequiresGameThreadEndOfFrameRecreate () const override
virtual void SetCollisionProfileName (FName InCollisionProfileName, bool bUpdateOverlaps=true) override
bool SetLODDataCount (const uint32 MinSize, const uint32 MaxSize)
Add or remove elements to have the size in the specified range.
virtual void SetMeshPaintTexture (UTexture *Texture) override
Set the mesh paint texture on this component.
virtual void SetMeshPaintTextureOverride (UTexture *OverrideTexture) override
Set a transient override mesh paint texture on this component.
virtual bool SetStaticLightingMapping (bool bTextureMapping, int32 ResolutionToUse)
Switches the static mesh component to use either Texture or Vertex static lighting.
virtual bool ShouldCollideWhenPlacing () const override
virtual bool ShouldCreateRenderState () const override
virtual bool ShouldIncrementalPreRegister (UWorld *WorldContext) const override
virtual bool ShouldRecreateProxyOnUpdateTransform () const override
virtual bool ShouldRenderSelected () const override
virtual bool SupportsDefaultCollision ()
Whether or not the component supports default collision from its static mesh asset.
virtual bool SupportsDitheredLODTransitions (ERHIFeatureLevel::Type FeatureLevel)
Whether we can support dithered LOD transitions (default behavior checks all materials).
virtual bool SupportsWorldPositionOffsetVelocity () const override
UE_DEPRECATED (5.6, "Use UPrimitiveComponent::IsFirstPersonRelevant() instead.") bool IsStaticMeshFirstPersonRelevant() const
UFUNCTION () 1 virtual bool SetStaticMesh(class UStaticMesh *NewMesh)
Change the StaticMesh used by this instance.
UFUNCTION () 1 void GetLocalBounds(FVector &Min
Get Local bounds.
UFUNCTION () 1 void OnRep_StaticMesh(class UStaticMesh *OldStaticMesh)
UFUNCTION () 1 void SetDistanceFieldSelfShadowBias(float NewValue)
Sets the component's DistanceFieldSelfShadowBias.
UFUNCTION () 1 void SetEvaluateWorldPositionOffset(bool NewValue)
UFUNCTION () 1 void SetEvaluateWorldPositionOffsetInRayTracing(bool NewValue)
UFUNCTION () 1 void SetForceDisableNanite(bool bInForceDisableNanite)
Force disabling of Nanite rendering.
UFUNCTION () 1 void SetForcedLodModel(int32 NewForcedLodModel)
UFUNCTION () 1 void SetReverseCulling(bool ReverseCulling)
Set forced reverse culling.
UFUNCTION () 1 void SetWorldPositionOffsetDisableDistance(int32 NewValue)
UFUNCTION () bool GetInitialEvaluateWorldPositionOffset()
Get the initial value of bEvaluateWorldPositionOffset.
UFUNCTION () void UpdateInitialEvaluateWorldPositionOffset()
This manually updates the initial value of bEvaluateWorldPositionOffset to be the current value.
void UpdateCollisionFromStaticMesh ()
Sets the BodyInstance to use the mesh's body setup for external collision information.
void UpdateMapBuildDataId ()
void UpdateStaticLightingData ()
UPROPERTY () float DistanceFieldSelfShadowBias
Useful for reducing self shadowing from distance field methods when using world position offset to animate the mesh's vertices.
UPROPERTY () float NanitePixelProgrammableDistance
Used to forcefully disable pixel programmable rasterization of Nanite when the mesh is further than a given distance from the camera.
UPROPERTY () struct FLightmassPrimitiveSettings LightmassSettings
The Lightmass settings for this object.
UPROPERTY () TArray< FStreamingTextureBuildInfo > StreamingTextureData
The list of texture, bounds and scales.
UPROPERTY () TArray< struct FStaticMeshComponentLODInfo > LODData
Static mesh LOD data.
UPROPERTY () TObjectPtr< UTexture > MaterialCacheTexture
UPROPERTY () TObjectPtr< UTexture > MeshPaintTextureCooked
Cooked pointer to texture containing mesh painting for this mesh component.
UPROPERTY () TObjectPtr< UTexture > MeshPaintTextureOverride
Set this to override the locally stored mesh paint texture.
UPROPERTY ()) float DistanceFieldIndirectShadowMinVisibility
Controls how dark the dynamic indirect shadow can be.
UPROPERTY ()) float StreamingDistanceMultiplier
Allows adjusting the desired streaming distance of streaming textures that uses UV 0.
UPROPERTY ()) int32 OverriddenLightMapRes
Light map resolution to use on this component, used if bOverrideLightMapRes is true and there is a valid StaticMesh.
UPROPERTY()) uint8 bOverrideWireframeColor UPROPERTY() uint8 bOverrideMinLOD UPROPERTY() uint8 bOverrideNavigationExport UPROPERTY() uint8 bForceNavigationObstacle UPROPERTY() uint8 bDisallowMeshPaintPerInstance_DEPRECATED UPROPERTY() uint8 bIgnoreInstanceForTextureStreaming UPROPERTY()) uint8 bOverrideLightMapRes UPROPERTY()) uint8 bCastDistanceFieldIndirectShadow UPROPERTY() uint8 bOverrideDistanceFieldSelfShadowBias UPROPERTY() uint8 bUseSubDivisions UPROPERTY() uint8 bUseDefaultCollision UPROPERTY()) uint8 bSortTriangles UPROPERTY() uint8 bReverseCulling UPROPERTY() uint8 bEnableVertexColorMeshPainting UPROPERTY() uint8 bEnableTextureColorMeshPainting UPROPERTY()) uint8 bOverrideMeshPaintTextureCoordinateIndex UPROPERTY()) uint8 bOverrideMeshPaintTextureResolution UPROPERTY ()) int32 OverriddenMeshPaintTextureCoordinateIndex
If true, WireframeColorOverride will be used.
UPROPERTY ()) int32 OverriddenMeshPaintTextureResolution
The overriden resolution of texture color mesh paint textures on this component.
virtual bool UseNaniteOverrideMaterials () const override
Determines if we use the nanite overrides from any materials.
virtual bool UsesOnlyUnlitMaterials () const override
virtual bool UsesTextureLightmaps (int32 InWidth, int32 InHeight) const
Returns true if the component uses texture lightmaps.
Public Member Functions inherited from UMeshComponent
const TArray< TObjectPtr< UMaterialInterface > > & GetComponentMaterialSlotsOverlayMaterial () const
Retrieve the material slots overly materials assigned to this component.
float GetScalarParameterDefaultValue (const FName ParameterName)
Returns default value for the parameter input.
UFUNCTION () 1 void SetColorParameterValueOnMaterials(const FName ParameterName
Set all occurrences of Vector Material Parameters with ParameterName in the set of materials of the SkeletalMesh to ParameterValue.
UFUNCTION () 1 void SetScalarParameterValueOnMaterials(const FName ParameterName
Set all occurrences of Scalar Material Parameters with ParameterName in the set of materials of the SkeletalMesh to ParameterValue.
UFUNCTION () 1 void SetVectorParameterValueOnMaterials(const FName ParameterName
Set all occurrences of Vector Material Parameters with ParameterName in the set of materials of the SkeletalMesh to ParameterValue.
Protected Member Functions
float ActualInstancesPerLeaf ()
Average number of instances per leaf.
void ApplyBuildTree (FClusterBuilder &Builder, const bool bWasAsyncBuild)
void ApplyEmpty ()
virtual void BuildComponentInstanceData (ERHIFeatureLevel::Type FeatureLevel, FInstanceUpdateComponentDesc &OutData) override
virtual void BuildTree ()
virtual void BuildTreeAsync ()
FVector CalcTranslatedInstanceSpaceOrigin () const
virtual FPrimitiveSceneProxy * CreateStaticMeshSceneProxy (Nanite::FMaterialAudit &NaniteMaterials, bool bCreateNanite) override
void GetInstanceTransforms (TArray< FMatrix > &InstanceTransforms, FVector const &Offset) const
virtual FVector GetTranslatedInstanceSpaceOrigin () const override
Get the translated space for instance transforms to be passed to the renderer.
int32 GetVertsForLOD (int32 LODIndex)
Gets and approximate number of verts for each LOD to generate heuristics.
virtual void OnPostLoadPerInstanceData () override
Creates rendering buffer from serialized data, if any.
void PostBuildStats ()
For testing, prints some stats after any kind of build.
void RemoveInstancesInternal (TConstArrayView< int32 > InstanceIndices)
Removes specified instances.
void SetPerInstanceLightMapAndEditorData (FStaticMeshInstanceData &PerInstanceData, const TArray< TRefCountPtr< HHitProxy > > &HitProxies)
UE_DEPRECATED (5.4, "AccumulatedNavigationDirtyArea has been deprecated.") mutable FBox AccumulatedNavigationDirtyArea
UE_DEPRECATED (5.4, "AccumulatedNavigationDirtyAreas has been deprecated.") mutable TArray< FBox > AccumulatedNavigationDirtyAreas
UE_DEPRECATED (5.4, "FlushAccumulatedNavigationUpdates has been deprecated. Use UInstancedStaticMeshComponent::PartialNavigationUpdates if you want to manually update the navigation data.") 1 void FlushAccumulatedNavigationUpdates()
UE_DEPRECATED (5.4, "UHierarchicalInstancedStaticMeshComponent is no longer overriding UInstancedStaticMeshComponent::GetNavigationPerInstanceTransforms.") 1 virtual void GetNavigationPerInstanceTransforms(const FBox &AreaBox
UE_DEPRECATED (5.4, "UHierarchicalInstancedStaticMeshComponent is no longer overriding UInstancedStaticMeshComponent::PartialNavigationUpdate.") 1 virtual void PartialNavigationUpdate(int32 InstanceIdx) override
UE_DEPRECATED (5.4, "UHierarchicalInstancedStaticMeshComponent is no longer overriding UInstancedStaticMeshComponent::SupportsPartialNavigationUpdate.") virtual bool SupportsPartialNavigationUpdate() const override
Protected Member Functions inherited from UInstancedStaticMeshComponent
int32 AddInstanceInternal (int32 InstanceIndex, FInstancedStaticMeshInstanceData *InNewInstanceData, const FTransform &InstanceTransform, bool bWorldSpace)
Internal version of AddInstance.
TArray< int32 > AddInstancesInternal (TConstArrayView< FTransform > InstanceTransforms, bool bShouldReturnIndices, bool bWorldSpace, bool bUpdateNavigation=true)
Internal implementation of AddInstances.
void ApplyLightMapping (FStaticLightingTextureMapping_InstancedStaticMesh *InMapping, const FStaticLightingBuildContext *LightingContext)
void BuildInstanceDataDeltaChangeSetCommon (FISMInstanceUpdateChangeSet &ChangeSet)
void BuildLegacyRenderData (FStaticMeshInstanceData &OutData)
Build instance buffer for rendering from current component data.
void CalcAndCacheNavigationBounds ()
FBoxSphereBounds CalcBoundsImpl (const FTransform &BoundTransform, const FBox &InstanceBounds) const
Calculates bounds from all instances.
virtual bool CanEditSMInstance (const FSMInstanceId &InstanceId) const override
virtual bool CanMoveSMInstance (const FSMInstanceId &InstanceId, const ETypedElementWorldType InWorldType) const override
Get the display name of the given static mesh instance.
void ClearAllInstanceBodies ()
Terminate all body instances owned by this component.
virtual bool ComponentOverlapComponentImpl (class UPrimitiveComponent *PrimComp, const FVector Pos, const FQuat &Quat, const FCollisionQueryParams &Params) override
virtual bool ComponentOverlapMultiImpl (TArray< struct FOverlapResult > &OutOverlaps, const class UWorld *InWorld, const FVector &Pos, const FQuat &Rot, ECollisionChannel TestChannel, const struct FComponentQueryParams &Params, const struct FCollisionObjectQueryParams &ObjectQueryParams=FCollisionObjectQueryParams::DefaultObjectQueryParam) const override
void CreateAllInstanceBodies ()
Creates body instances for all instances owned by this component.
void CreateHitProxyData (TArray< TRefCountPtr< HHitProxy > > &HitProxies)
virtual bool DeleteSMInstances (TArrayView< const FSMInstanceId > InstanceIds) override
Attempt to delete the given static mesh instances.
virtual bool DuplicateSMInstances (TArrayView< const FSMInstanceId > InstanceIds, TArray< FSMInstanceId > &OutNewInstanceIds) override
Attempt to duplicate the given static mesh instances, retrieving the IDs of any new instances.
virtual void FullNavigationUpdate ()
Request to navigation system to update for the bounds of the ISM.
FBox GetInstanceNavigationBounds () const
Returns the bounds of a single instance in local space.
virtual void GetNavigationPerInstanceTransforms (const FBox &AreaBox, TArray< FTransform > &InstanceData) const
Handles request from navigation system to gather instance transforms in a specific area box.
virtual bool GetSMInstanceTransform (const FSMInstanceId &InstanceId, FTransform &OutInstanceTransform, bool bWorldSpace=false) const override
Attempt to get the transform of the given static mesh instance.
void InitializeInstancingRandomSeed ()
void InitInstanceBody (int32 InstanceIdx, FBodyInstance *InBodyInstance)
Initializes the body instance for the specified instance of the static mesh.
void InvalidateCachedBounds ()
virtual void NotifySMInstanceMovementEnded (const FSMInstanceId &InstanceId) override
Notify that the given static mesh instance is done being moved.
virtual void NotifySMInstanceMovementOngoing (const FSMInstanceId &InstanceId) override
Notify that the given static mesh instance is currently being moved.
virtual void NotifySMInstanceMovementStarted (const FSMInstanceId &InstanceId) override
Notify that the given static mesh instance is about to be moved.
virtual void NotifySMInstanceSelectionChanged (const FSMInstanceId &InstanceId, const bool bIsSelected) override
Notify that the given static mesh instance selection state has changed.
virtual bool OnAsyncDestroyPhysicsState (const UE::FTimeout &Timeout) override
virtual void OnAsyncDestroyPhysicsStateBegin_GameThread () override
virtual void OnCreatePhysicsState () override
virtual void OnDestroyPhysicsState () override
bool RemoveInstanceInternal (int32 InstanceIndex, bool InstanceAlreadyRemoved, bool bForceRemoveAtSwap=false, bool bUpdateNavigation=true)
Internal version of RemoveInstance.
void SerializeRenderData (FArchive &Ar)
Serialize instance buffer that is used for rendering.
virtual bool SetSMInstanceTransform (const FSMInstanceId &InstanceId, const FTransform &InstanceTransform, bool bWorldSpace=false, bool bMarkRenderStateDirty=false, bool bTeleport=false) override
Attempt to set the transform of the given static mesh instance.
virtual bool SupportsPartialNavigationUpdate () const
Does this component support partial navigation updates.
UE_DEPRECATED (5.5, "Use version with FBox") FBoxSphereBounds CalcBoundsImpl(const FTransform &BoundTransform
UPROPERTY () int32 NumPendingLightmaps
Number of pending lightmaps still to be calculated (Apply()'d).
UPROPERTY () TArray< FInstancedStaticMeshMappingInfo > CachedMappings
The mappings for all the instances of this component.
Protected Member Functions inherited from UStaticMeshComponent
void CollectPSOPrecacheDataImpl (const FVertexFactoryType *VFType, const FPSOPrecacheParams &BasePrecachePSOParams, GetPSOVertexElementsFn GetVertexElements, FMaterialInterfacePSOPrecacheParamsList &OutParams) const
bool ShouldCreateNaniteProxy (Nanite::FMaterialAudit *OutNaniteMaterials=nullptr) const
bool ShouldExportAsObstacle (const UNavCollisionBase &InNavCollision) const
Protected Member Functions inherited from UMeshComponent
void CacheMaterialParameterNameIndices ()
Retrieves all the (scalar/vector-)parameters from within the used materials on the SkeletalMesh, and stores material index vs parameter names.
virtual UMaterialInterface * GetDefaultOverlayMaterial () const
Get the default overlay material used by a mesh.
virtual float GetDefaultOverlayMaterialMaxDrawDistance () const
Get the default overlay material max draw distance.
void MarkCachedMaterialParameterNameIndicesDirty ()
Mark cache parameters map as dirty, cache will be rebuild once SetScalar/SetVector functions are called.
Static Protected Member Functions
static FBox GetClusterTreeBounds (TArray< FClusterNode > const &InClusterTree, const FVector &InOffset)
Protected Attributes
FGraphEventArray BuildTreeAsyncTasks
friend FClusterBuilder
friend FInstancedLightMap2D
friend FInstancedShadowMap2D
friend FStaticLightingTextureMapping_InstancedStaticMesh
TArray< FTransform > &InstanceData const override
EHISMViewRelevanceType ViewRelevanceType = EHISMViewRelevanceType::HISM
Protected Attributes inherited from UInstancedStaticMeshComponent
uint8 bIsInstanceDataApplyCompleted: 1
bool bForNavigation const
friend FInstancedLightMap2D
friend FInstancedShadowMap2D
friend FStaticLightingTextureMapping_InstancedStaticMesh
FPrimitiveInstanceDataManager PrimitiveInstanceDataManager
Protected Attributes inherited from UStaticMeshComponent
uint8 bInitialEvaluateWorldPositionOffset: 1
Forces this component to always use Nanite for masked materials, even if FNaniteSettings::bAllowMaskedMaterials=false.
uint8 bMipLevelCallbackRegistered: 1
Whether mip callbacks have been registered and need to be removed on destroy.
uint8 bPrecachedPSOs: 1
Whether PrecachedPSOs was called.
uint8 bSupportMeshPainting: 1
Whether mesh painting is supported.
Protected Attributes inherited from UMeshComponent
uint8 bCachedMaterialParameterIndicesAreDirty: 1
Whether or not to cache material parameter to speed up setting scalar or vector value on materials.
TSortedMap< FName, FMaterialParameterCache, FDefaultAllocator, FNameFastLess > MaterialParameterCache
Private Member Functions
~UHierarchicalInstancedStaticMeshComponent ()
bool BatchUpdateInstancesTransformsInternal (int32 StartInstanceIndex, TArrayView< const FTransform > NewInstancesTransforms, bool bWorldSpace, bool bMarkRenderStateDirty, bool bTeleport)
hidden Implementation of BatchUpdateInstancesTransforms - it is shared by the TArray and TArrayView version of public API
GENERATED_UCLASS_BODY () friend class ALightWeightInstanceStaticMeshManager
UPROPERTY () FBox BuiltInstanceBounds
Value used to seed the random number stream that generates random numbers for each of this mesh's instances.
UPROPERTY () FBox UnbuiltInstanceBounds
Value used to seed the random number stream that generates random numbers for each of this mesh's instances.
UPROPERTY () FBoxSphereBounds CacheMeshExtendedBounds
Value used to seed the random number stream that generates random numbers for each of this mesh's instances.
UPROPERTY() uint32 bUseTranslatedInstanceSpace UPROPERTY () FVector TranslatedInstanceSpaceOrigin
Value used to seed the random number stream that generates random numbers for each of this mesh's instances.
UPROPERTY () int32 InstanceCountToRender
Value used to seed the random number stream that generates random numbers for each of this mesh's instances.
UPROPERTY () int32 NumBuiltInstances
Value used to seed the random number stream that generates random numbers for each of this mesh's instances.
UPROPERTY () int32 OcclusionLayerNumNodes
Value used to seed the random number stream that generates random numbers for each of this mesh's instances.
UPROPERTY () TArray< FBox > UnbuiltInstanceBoundsList
Value used to seed the random number stream that generates random numbers for each of this mesh's instances.
UPROPERTY () TArray< int32 > SortedInstances
Value used to seed the random number stream that generates random numbers for each of this mesh's instances.
Private Attributes
bool bAutoRebuildTreeOnInstanceChanges: 1
bool bCanEnableDensityScaling: 1
bool bConcurrentChanges: 1
bool bIsAsyncBuilding: 1
bool bIsOutOfDate: 1
TSharedPtr< TArray< FClusterNode >, ESPMode::ThreadSafe > ClusterTreePtr
UPROPERTY() uint32 bEnableDensityScaling float CurrentDensityScaling
int32 NumBuiltRenderInstances
Additional Inherited Members
Public Types inherited from UInstancedStaticMeshComponent
enum class EInstanceDeletionReason : uint8 { NotDeleting , EntryAlreadyRemoved , EntryRemoval , Clearing }
The reason why a deletion operation is currently happening.
Static Public Member Functions inherited from UStaticMeshComponent
static void AddReferencedObjects (UObject *InThis, FReferenceCollector &Collector)
static const FName GetMemberNameChecked_StaticMesh ()
Helper function to get the FName of the private static mesh member.
Data Fields inherited from UInstancedStaticMeshComponent
bool bBoxInWorldSpace =true) const
bool bForceShowAllInstancesDetails = false
Indicates that the user has purposedly chosen to show the instance list in the details panel, despite the performance warning.
int32 float bool bMarkRenderStateDirty = false)
const FTransform bool bool bMarkRenderStateDirty =false
const TArray< FTransform > bool bool bMarkRenderStateDirty =false
int32 const FTransform bool bool bMarkRenderStateDirty =false
bool bShouldReturnIndices
float bool bSphereInWorldSpace =true) const
const FTransform bool bool bool bTeleport =false)
const TArray< FTransform > bool bool bool bTeleport =false)
int32 const FTransform bool bool bool bTeleport =false)
bool bool bool bUpdateNavigation = true)
bool bWorldSpace = false)
bool bool bWorldSpace = false
FTransform bool bWorldSpace = false) const
const FTransform bool bWorldSpace =false
const TArray< FTransform > bool bWorldSpace =false
int32 const FTransform bool bWorldSpace =false
int32 &OutEndCullDistance const { OutStartCullDistance = InstanceStartCullDistance
int32 CustomDataIndex
int32 float CustomDataValue
EInstanceDeletionReason DeletionState = EInstanceDeletionReason::NotDeleting
This will be set to the appropriate state when one or more instances are in the process of being deleted.
int32 EndCullDistance
TArray< FBodyInstance * > InstanceBodies
Physics representation of the instance bodies.
int32 const FTransform & NewInstancesTransform
const TArray< FTransform > & NewInstancesTransforms
const FTransform & NewInstanceTransform
int32 NumInstances
OutEndCullDistance = InstanceEndCullDistance
FTransform & OutInstanceTransform
SIZE_T ProxySize
Tracks outstanding proxysize, as this is a bit hard to do with the fire-and-forget grass.
float Radius
TBitArray SelectedInstances
One bit per instance if the instance is selected.
Data Fields inherited from UStaticMeshComponent
FVector &Max const
Data Fields inherited from UMeshComponent
const float ParameterValue
const FVector ParameterValue
const FLinearColor ParameterValue
Protected Types inherited from UInstancedStaticMeshComponent
enum class EBoundsCacheType : uint8 {
Component , Navigation , Local , Count ,
Other
}
Protected Types inherited from UStaticMeshComponent
using GetPSOVertexElementsFn = TFunctionRef<void(const FStaticMeshLODResources& LODRenderData, int32 LODIndex, bool bSupportsManualVertexFetch, FVertexDeclarationElementList& Elements)>
Shared implementation for all StaticMesh derived components.
Detailed Description
Definition at line 135 of file HierarchicalInstancedStaticMeshComponent.h.
Constructor & Destructor Documentation
~UHierarchicalInstancedStaticMeshComponent()
UHierarchicalInstancedStaticMeshComponent::~UHierarchicalInstancedStaticMeshComponent () private
Member Function Documentation
ActualInstancesPerLeaf()
float UHierarchicalInstancedStaticMeshComponent::ActualInstancesPerLeaf () protected
Average number of instances per leaf.
AddInstance()
virtual int32 UHierarchicalInstancedStaticMeshComponent::AddInstance (const FTransform & InstanceTransform, bool bWorldSpace = false) override virtual
References UInstancedStaticMeshComponent::bWorldSpace.
AddInstances()
virtual TArray< int32 > UHierarchicalInstancedStaticMeshComponent::AddInstances (const TArray< FTransform > & InstanceTransforms, bool bShouldReturnIndices, bool bWorldSpace = false, bool bUpdateNavigation = true) override virtual
References UInstancedStaticMeshComponent::bShouldReturnIndices, UInstancedStaticMeshComponent::bUpdateNavigation, and UInstancedStaticMeshComponent::bWorldSpace.
ApplyBuildTree()
void UHierarchicalInstancedStaticMeshComponent::ApplyBuildTree (FClusterBuilder & Builder, const bool bWasAsyncBuild) protected
ApplyBuildTreeAsync()
void UHierarchicalInstancedStaticMeshComponent::ApplyBuildTreeAsync (ENamedThreads::Type CurrentThread, const FGraphEventRef & MyCompletionGraphEvent, TSharedRef< FClusterBuilder, ESPMode::ThreadSafe > Builder, double StartTime)
ApplyComponentInstanceData()
virtual void UHierarchicalInstancedStaticMeshComponent::ApplyComponentInstanceData (struct FInstancedStaticMeshComponentInstanceData * ComponentInstanceData) override virtual
Applies the cached component instance data to a newly blueprint constructed component.
Reimplemented from UInstancedStaticMeshComponent.
ApplyEmpty()
void UHierarchicalInstancedStaticMeshComponent::ApplyEmpty () protected
BatchUpdateInstancesData()
virtual bool UHierarchicalInstancedStaticMeshComponent::BatchUpdateInstancesData (int32 StartInstanceIndex, int32 NumInstances, FInstancedStaticMeshInstanceData * StartInstanceData, bool bMarkRenderStateDirty = false, bool bTeleport = false) override virtual
Reimplemented from UInstancedStaticMeshComponent.
References UInstancedStaticMeshComponent::bMarkRenderStateDirty, UInstancedStaticMeshComponent::bTeleport, and UInstancedStaticMeshComponent::NumInstances.
BatchUpdateInstancesTransform()
virtual bool UHierarchicalInstancedStaticMeshComponent::BatchUpdateInstancesTransform (int32 StartInstanceIndex, int32 NumInstances, const FTransform & NewInstancesTransform, bool bWorldSpace = false, bool bMarkRenderStateDirty = false, bool bTeleport = false) override virtual
References UInstancedStaticMeshComponent::bMarkRenderStateDirty, UInstancedStaticMeshComponent::bTeleport, UInstancedStaticMeshComponent::bWorldSpace, UInstancedStaticMeshComponent::NewInstancesTransform, and UInstancedStaticMeshComponent::NumInstances.
BatchUpdateInstancesTransforms() [1/2]
virtual bool UHierarchicalInstancedStaticMeshComponent::BatchUpdateInstancesTransforms (int32 StartInstanceIndex, const TArray< FTransform > & NewInstancesTransforms, bool bWorldSpace = false, bool bMarkRenderStateDirty = false, bool bTeleport = false) override virtual
References UInstancedStaticMeshComponent::bMarkRenderStateDirty, UInstancedStaticMeshComponent::bTeleport, UInstancedStaticMeshComponent::bWorldSpace, and UInstancedStaticMeshComponent::NewInstancesTransforms.
BatchUpdateInstancesTransforms() [2/2]
virtual bool UHierarchicalInstancedStaticMeshComponent::BatchUpdateInstancesTransforms (int32 StartInstanceIndex, TArrayView< const FTransform > NewInstancesTransforms, bool bWorldSpace, bool bMarkRenderStateDirty, bool bTeleport) override virtual
this is array view version of the UFUNCTION, blueprints do not support ArrayViews at the time of adding this one
Reimplemented from UInstancedStaticMeshComponent.
References UInstancedStaticMeshComponent::bMarkRenderStateDirty, UInstancedStaticMeshComponent::bTeleport, UInstancedStaticMeshComponent::bWorldSpace, and UInstancedStaticMeshComponent::NewInstancesTransforms.
BatchUpdateInstancesTransformsInternal()
bool UHierarchicalInstancedStaticMeshComponent::BatchUpdateInstancesTransformsInternal (int32 StartInstanceIndex, TArrayView< const FTransform > NewInstancesTransforms, bool bWorldSpace, bool bMarkRenderStateDirty, bool bTeleport) private
hidden Implementation of BatchUpdateInstancesTransforms - it is shared by the TArray and TArrayView version of public API
References BatchUpdateInstancesTransformsInternal(), UInstancedStaticMeshComponent::bMarkRenderStateDirty, UInstancedStaticMeshComponent::bTeleport, UInstancedStaticMeshComponent::bWorldSpace, UInstancedStaticMeshComponent::const, and UInstancedStaticMeshComponent::NewInstancesTransforms.
Referenced by BatchUpdateInstancesTransformsInternal().
BuildComponentInstanceData()
virtual void UHierarchicalInstancedStaticMeshComponent::BuildComponentInstanceData (ERHIFeatureLevel::Type FeatureLevel, FInstanceUpdateComponentDesc & OutData) override protected virtual
Reimplemented from UInstancedStaticMeshComponent.
BuildTree()
virtual void UHierarchicalInstancedStaticMeshComponent::BuildTree () protected virtual
BuildTreeAsync()
virtual void UHierarchicalInstancedStaticMeshComponent::BuildTreeAsync () protected virtual
BuildTreeIfOutdated()
bool UHierarchicalInstancedStaticMeshComponent::BuildTreeIfOutdated (bool Async, bool ForceUpdate)
References Async().
CalcBounds()
virtual FBoxSphereBounds UHierarchicalInstancedStaticMeshComponent::CalcBounds (const FTransform & BoundTransform) const override virtual
Reimplemented from UInstancedStaticMeshComponent.
CalcTranslatedInstanceSpaceOrigin()
FVector UHierarchicalInstancedStaticMeshComponent::CalcTranslatedInstanceSpaceOrigin () const protected
References FVector.
ClearInstances()
virtual void UHierarchicalInstancedStaticMeshComponent::ClearInstances () override virtual
CreateSceneProxy()
virtual FPrimitiveSceneProxy * UHierarchicalInstancedStaticMeshComponent::CreateSceneProxy () override virtual
Reimplemented from UInstancedStaticMeshComponent.
CreateStaticMeshSceneProxy()
virtual FPrimitiveSceneProxy * UHierarchicalInstancedStaticMeshComponent::CreateStaticMeshSceneProxy (Nanite::FMaterialAudit & NaniteMaterials, bool bCreateNanite) override protected virtual
Reimplemented from UInstancedStaticMeshComponent.
DesiredInstancesPerLeaf()
int32 UHierarchicalInstancedStaticMeshComponent::DesiredInstancesPerLeaf ()
Heuristic for the number of leaves in the tree.
GENERATED_UCLASS_BODY()
UHierarchicalInstancedStaticMeshComponent::GENERATED_UCLASS_BODY () private
GetAverageScale()
FVector UHierarchicalInstancedStaticMeshComponent::GetAverageScale () const
References FVector.
GetClusterTreeBounds()
FBox UHierarchicalInstancedStaticMeshComponent::GetClusterTreeBounds (TArray< FClusterNode > const & InClusterTree, const FVector & InOffset) static protected
References FVector.
GetInstancesOverlappingBox()
virtual TArray< int32 > UHierarchicalInstancedStaticMeshComponent::GetInstancesOverlappingBox (const FBox & Box, bool bBoxInWorldSpace = true) const override virtual
References UInstancedStaticMeshComponent::bBoxInWorldSpace, and Box.
GetInstancesOverlappingSphere()
virtual TArray< int32 > UHierarchicalInstancedStaticMeshComponent::GetInstancesOverlappingSphere (const FVector & Center, float Radius, bool bSphereInWorldSpace = true) const override virtual
References UInstancedStaticMeshComponent::bSphereInWorldSpace, FVector, and UInstancedStaticMeshComponent::Radius.
GetInstanceTransforms()
void UHierarchicalInstancedStaticMeshComponent::GetInstanceTransforms (TArray< FMatrix > & InstanceTransforms, FVector const & Offset) const protected
References FVector.
GetNumRenderInstances()
virtual int32 UHierarchicalInstancedStaticMeshComponent::GetNumRenderInstances () const inline virtual
Reimplemented from UInstancedStaticMeshComponent.
Definition at line 344 of file HierarchicalInstancedStaticMeshComponent.h.
GetOverlappingBoxCount()
int32 UHierarchicalInstancedStaticMeshComponent::GetOverlappingBoxCount (const FBox & Box) const
Get the number of instances that overlap a given box.
References Box.
GetOverlappingBoxTransforms()
void UHierarchicalInstancedStaticMeshComponent::GetOverlappingBoxTransforms (const FBox & Box, TArray< FTransform > & OutTransforms) const
Get the transforms of instances inside the provided box.
References Box.
GetOverlappingSphereCount()
int32 UHierarchicalInstancedStaticMeshComponent::GetOverlappingSphereCount (const FSphere & Sphere) const
Get the number of instances that overlap a given sphere.
References Sphere.
GetResourceSizeEx()
virtual void UHierarchicalInstancedStaticMeshComponent::GetResourceSizeEx (FResourceSizeEx & CumulativeResourceSize) override virtual
Reimplemented from UInstancedStaticMeshComponent.
GetTranslatedInstanceSpaceOrigin()
virtual FVector UHierarchicalInstancedStaticMeshComponent::GetTranslatedInstanceSpaceOrigin () const inline override protected virtual
Get the translated space for instance transforms to be passed to the renderer.
In the renderer data structures we only have floating point precision for instance transforms relative to their owning primitive. The primitive transform itself has double precision. Some ISM that are authored in world space need to adjust the local space to keep instance transforms within precision limits.
Reimplemented from UInstancedStaticMeshComponent.
Definition at line 380 of file HierarchicalInstancedStaticMeshComponent.h.
References FVector.
GetTree()
void UHierarchicalInstancedStaticMeshComponent::GetTree (TArray< FClusterNode > & OutClusterTree) const
GetVertsForLOD()
int32 UHierarchicalInstancedStaticMeshComponent::GetVertsForLOD (int32 LODIndex) protected
Gets and approximate number of verts for each LOD to generate heuristics.
GetViewRelevanceType()
EHISMViewRelevanceType UHierarchicalInstancedStaticMeshComponent::GetViewRelevanceType () const inline
Definition at line 351 of file HierarchicalInstancedStaticMeshComponent.h.
References ViewRelevanceType.
IsAsyncBuilding()
bool UHierarchicalInstancedStaticMeshComponent::IsAsyncBuilding () const inline
Definition at line 333 of file HierarchicalInstancedStaticMeshComponent.h.
References bIsAsyncBuilding.
IsTreeFullyBuilt()
bool UHierarchicalInstancedStaticMeshComponent::IsTreeFullyBuilt () const inline
Definition at line 334 of file HierarchicalInstancedStaticMeshComponent.h.
References bIsOutOfDate.
OnPostLoadPerInstanceData()
virtual void UHierarchicalInstancedStaticMeshComponent::OnPostLoadPerInstanceData () override protected virtual
Creates rendering buffer from serialized data, if any.
Reimplemented from UInstancedStaticMeshComponent.
PostBuildStats()
void UHierarchicalInstancedStaticMeshComponent::PostBuildStats () protected
For testing, prints some stats after any kind of build.
PostEditChangeChainProperty()
virtual void UHierarchicalInstancedStaticMeshComponent::PostEditChangeChainProperty (FPropertyChangedChainEvent & PropertyChangedEvent) override virtual
Reimplemented from UInstancedStaticMeshComponent.
PostEditImport()
virtual void UHierarchicalInstancedStaticMeshComponent::PostEditImport () override virtual
Reimplemented from UStaticMeshComponent.
PostEditUndo()
virtual void UHierarchicalInstancedStaticMeshComponent::PostEditUndo () override virtual
Reimplemented from UInstancedStaticMeshComponent.
PostLoad()
virtual void UHierarchicalInstancedStaticMeshComponent::PostLoad () override virtual
Reimplemented from UInstancedStaticMeshComponent.
PostStaticMeshCompilation()
virtual void UHierarchicalInstancedStaticMeshComponent::PostStaticMeshCompilation () override virtual
Reimplemented from UInstancedStaticMeshComponent.
PreAllocateInstancesMemory()
virtual void UHierarchicalInstancedStaticMeshComponent::PreAllocateInstancesMemory (int32 AddedInstanceCount) override virtual
Preallocated memory to include the new added instances count, to prevent reallloc during the add operation.
Reimplemented from UInstancedStaticMeshComponent.
PropagateLightingScenarioChange()
virtual void UHierarchicalInstancedStaticMeshComponent::PropagateLightingScenarioChange () override virtual
Reimplemented from UInstancedStaticMeshComponent.
RemoveInstance()
virtual bool UHierarchicalInstancedStaticMeshComponent::RemoveInstance (int32 InstanceIndex) override virtual
RemoveInstances() [1/2]
virtual bool UHierarchicalInstancedStaticMeshComponent::RemoveInstances (const TArray< int32 > & InstancesToRemove) override virtual
RemoveInstances() [2/2]
virtual bool UHierarchicalInstancedStaticMeshComponent::RemoveInstances (const TArray< int32 > & InstancesToRemove, bool bInstanceArrayAlreadySortedInReverseOrder) override virtual
Remove the instances specified.
Returns True on success.
Parameters
InstancesToRemove array of the instance indices to remove (can be sorted
See also
bInstanceArrayAlreadySortedInReverseOrder)
Parameters
bInstanceArrayAlreadySortedInReverseOrder true is the array is already sorted in reverse order
Reimplemented from UInstancedStaticMeshComponent.
RemoveInstancesInternal()
void UHierarchicalInstancedStaticMeshComponent::RemoveInstancesInternal (TConstArrayView< int32 > InstanceIndices) protected
Removes specified instances.
Serialize()
virtual void UHierarchicalInstancedStaticMeshComponent::Serialize (FArchive & Ar) override virtual
Reimplemented from UInstancedStaticMeshComponent.
References Ar.
SetCustomData()
virtual bool UHierarchicalInstancedStaticMeshComponent::SetCustomData (int32 InstanceIndex, TArrayView< const float > CustomDataFloats, bool bMarkRenderStateDirty = false) override virtual
Per Instance Custom Data.
Reimplemented from UInstancedStaticMeshComponent.
References UInstancedStaticMeshComponent::bMarkRenderStateDirty.
SetCustomDataValue()
virtual bool UHierarchicalInstancedStaticMeshComponent::SetCustomDataValue (int32 InstanceIndex, int32 CustomDataIndex, float CustomDataValue, bool bMarkRenderStateDirty = false) override virtual
References UInstancedStaticMeshComponent::bMarkRenderStateDirty, UInstancedStaticMeshComponent::CustomDataIndex, and UInstancedStaticMeshComponent::CustomDataValue.
SetPerInstanceLightMapAndEditorData()
void UHierarchicalInstancedStaticMeshComponent::SetPerInstanceLightMapAndEditorData (FStaticMeshInstanceData & PerInstanceData, const TArray< TRefCountPtr< HHitProxy > > & HitProxies) protected
SupportsRemoveSwap()
virtual bool UHierarchicalInstancedStaticMeshComponent::SupportsRemoveSwap () const inline override virtual
Returns true if RemoveAtSwap is enabled.
Derived classes may always return true regardless of whether SetRemoveSwapEnabled() was called.
Reimplemented from UInstancedStaticMeshComponent.
Definition at line 323 of file HierarchicalInstancedStaticMeshComponent.h.
UE_DEPRECATED() [1/6]
UHierarchicalInstancedStaticMeshComponent::UE_DEPRECATED (5. 4, "AccumulatedNavigationDirtyArea has been deprecated.") protected
References UE_DEPRECATED().
UE_DEPRECATED() [2/6]
UHierarchicalInstancedStaticMeshComponent::UE_DEPRECATED (5. 4, "AccumulatedNavigationDirtyAreas has been deprecated.") protected
References UE_DEPRECATED().
UE_DEPRECATED() [3/6]
UHierarchicalInstancedStaticMeshComponent::UE_DEPRECATED (5. 4, "FlushAccumulatedNavigationUpdates has been deprecated. Use UInstancedStaticMeshComponent::PartialNavigationUpdates if you want to manually update the navigation data.") protected
UE_DEPRECATED() [4/6]
UHierarchicalInstancedStaticMeshComponent::UE_DEPRECATED (5. 4, "UHierarchicalInstancedStaticMeshComponent is no longer overriding UInstancedStaticMeshComponent::GetNavigationPerInstanceTransforms.") const & protected
Referenced by UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
UE_DEPRECATED() [5/6]
UHierarchicalInstancedStaticMeshComponent::UE_DEPRECATED (5. 4, "UHierarchicalInstancedStaticMeshComponent is no longer overriding UInstancedStaticMeshComponent::PartialNavigationUpdate.") override protected
References override, UInstancedStaticMeshComponent::PartialNavigationUpdate(), and UE_DEPRECATED().
UE_DEPRECATED() [6/6]
UHierarchicalInstancedStaticMeshComponent::UE_DEPRECATED (5. 4, "UHierarchicalInstancedStaticMeshComponent is no longer overriding UInstancedStaticMeshComponent::SupportsPartialNavigationUpdate.") const inline override protected
Definition at line 388 of file HierarchicalInstancedStaticMeshComponent.h.
References UInstancedStaticMeshComponent::SupportsPartialNavigationUpdate(), and UE_DEPRECATED().
UpdateDensityScaling()
void UHierarchicalInstancedStaticMeshComponent::UpdateDensityScaling ()
Will apply current density scaling, if enabled.
UpdateInstanceTransform()
virtual bool UHierarchicalInstancedStaticMeshComponent::UpdateInstanceTransform (int32 InstanceIndex, const FTransform & NewInstanceTransform, bool bWorldSpace, bool bMarkRenderStateDirty = false, bool bTeleport = false) override virtual
References UInstancedStaticMeshComponent::bMarkRenderStateDirty, UInstancedStaticMeshComponent::bTeleport, UInstancedStaticMeshComponent::bWorldSpace, and UInstancedStaticMeshComponent::NewInstanceTransform.
UPROPERTY() [1/9]
UHierarchicalInstancedStaticMeshComponent::UPROPERTY () private virtual
Value used to seed the random number stream that generates random numbers for each of this mesh's instances.
The random number is stored in a buffer accessible to materials through the PerInstanceRandom expression. If this is set to zero (default), it will be populated automatically by the editor.
Implements UInstancedStaticMeshComponent.
References UPROPERTY().
UPROPERTY() [2/9]
UHierarchicalInstancedStaticMeshComponent::UPROPERTY () private virtual
Value used to seed the random number stream that generates random numbers for each of this mesh's instances.
The random number is stored in a buffer accessible to materials through the PerInstanceRandom expression. If this is set to zero (default), it will be populated automatically by the editor.
Implements UInstancedStaticMeshComponent.
References UPROPERTY().
UPROPERTY() [3/9]
UHierarchicalInstancedStaticMeshComponent::UPROPERTY () private virtual
Value used to seed the random number stream that generates random numbers for each of this mesh's instances.
The random number is stored in a buffer accessible to materials through the PerInstanceRandom expression. If this is set to zero (default), it will be populated automatically by the editor.
Implements UInstancedStaticMeshComponent.
References UPROPERTY().
UPROPERTY() [4/9]
UPROPERTY() uint32 bUseTranslatedInstanceSpace UHierarchicalInstancedStaticMeshComponent::UPROPERTY () private virtual
Value used to seed the random number stream that generates random numbers for each of this mesh's instances.
The random number is stored in a buffer accessible to materials through the PerInstanceRandom expression. If this is set to zero (default), it will be populated automatically by the editor.
Implements UInstancedStaticMeshComponent.
References FVector, and UPROPERTY().
Referenced by UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), and UPROPERTY().
UPROPERTY() [5/9]
UHierarchicalInstancedStaticMeshComponent::UPROPERTY () private virtual
Value used to seed the random number stream that generates random numbers for each of this mesh's instances.
The random number is stored in a buffer accessible to materials through the PerInstanceRandom expression. If this is set to zero (default), it will be populated automatically by the editor.
Implements UInstancedStaticMeshComponent.
References UPROPERTY().
UPROPERTY() [6/9]
UHierarchicalInstancedStaticMeshComponent::UPROPERTY () private virtual
Value used to seed the random number stream that generates random numbers for each of this mesh's instances.
The random number is stored in a buffer accessible to materials through the PerInstanceRandom expression. If this is set to zero (default), it will be populated automatically by the editor.
Implements UInstancedStaticMeshComponent.
References UPROPERTY().
UPROPERTY() [7/9]
UHierarchicalInstancedStaticMeshComponent::UPROPERTY () private virtual
Value used to seed the random number stream that generates random numbers for each of this mesh's instances.
The random number is stored in a buffer accessible to materials through the PerInstanceRandom expression. If this is set to zero (default), it will be populated automatically by the editor.
Implements UInstancedStaticMeshComponent.
References UPROPERTY().
UPROPERTY() [8/9]
UHierarchicalInstancedStaticMeshComponent::UPROPERTY () private virtual
Value used to seed the random number stream that generates random numbers for each of this mesh's instances.
The random number is stored in a buffer accessible to materials through the PerInstanceRandom expression. If this is set to zero (default), it will be populated automatically by the editor.
Implements UInstancedStaticMeshComponent.
References UPROPERTY().
UPROPERTY() [9/9]
UHierarchicalInstancedStaticMeshComponent::UPROPERTY () private virtual
Value used to seed the random number stream that generates random numbers for each of this mesh's instances.
The random number is stored in a buffer accessible to materials through the PerInstanceRandom expression. If this is set to zero (default), it will be populated automatically by the editor.
Implements UInstancedStaticMeshComponent.
References UPROPERTY().
Field Documentation
bAutoRebuildTreeOnInstanceChanges
bool UHierarchicalInstancedStaticMeshComponent::bAutoRebuildTreeOnInstanceChanges private
Definition at line 200 of file HierarchicalInstancedStaticMeshComponent.h.
bCanEnableDensityScaling
bool UHierarchicalInstancedStaticMeshComponent::bCanEnableDensityScaling private
Definition at line 204 of file HierarchicalInstancedStaticMeshComponent.h.
bConcurrentChanges
bool UHierarchicalInstancedStaticMeshComponent::bConcurrentChanges private
Definition at line 199 of file HierarchicalInstancedStaticMeshComponent.h.
bIsAsyncBuilding
bool UHierarchicalInstancedStaticMeshComponent::bIsAsyncBuilding private
Definition at line 197 of file HierarchicalInstancedStaticMeshComponent.h.
Referenced by IsAsyncBuilding().
bIsOutOfDate
bool UHierarchicalInstancedStaticMeshComponent::bIsOutOfDate private
Definition at line 198 of file HierarchicalInstancedStaticMeshComponent.h.
Referenced by IsTreeFullyBuilt().
BuildTreeAsyncTasks
FGraphEventArray UHierarchicalInstancedStaticMeshComponent::BuildTreeAsyncTasks protected
Definition at line 398 of file HierarchicalInstancedStaticMeshComponent.h.
ClusterTreePtr
TSharedPtr<TArray<FClusterNode>, ESPMode::ThreadSafe> UHierarchicalInstancedStaticMeshComponent::ClusterTreePtr private
Definition at line 143 of file HierarchicalInstancedStaticMeshComponent.h.
CurrentDensityScaling
UPROPERTY () uint32 bEnableDensityScaling float UHierarchicalInstancedStaticMeshComponent::CurrentDensityScaling private
Definition at line 183 of file HierarchicalInstancedStaticMeshComponent.h.
FClusterBuilder
friend UHierarchicalInstancedStaticMeshComponent::FClusterBuilder protected
Definition at line 409 of file HierarchicalInstancedStaticMeshComponent.h.
FInstancedLightMap2D
friend UHierarchicalInstancedStaticMeshComponent::FInstancedLightMap2D protected
Definition at line 407 of file HierarchicalInstancedStaticMeshComponent.h.
FInstancedShadowMap2D
friend UHierarchicalInstancedStaticMeshComponent::FInstancedShadowMap2D protected
Definition at line 408 of file HierarchicalInstancedStaticMeshComponent.h.
FStaticLightingTextureMapping_InstancedStaticMesh
friend UHierarchicalInstancedStaticMeshComponent::FStaticLightingTextureMapping_InstancedStaticMesh protected
Definition at line 406 of file HierarchicalInstancedStaticMeshComponent.h.
NumBuiltRenderInstances
int32 UHierarchicalInstancedStaticMeshComponent::NumBuiltRenderInstances private
Definition at line 163 of file HierarchicalInstancedStaticMeshComponent.h.
override
TArray<FTransform>& InstanceData const UHierarchicalInstancedStaticMeshComponent::override protected
Definition at line 385 of file HierarchicalInstancedStaticMeshComponent.h.
Referenced by UE_DEPRECATED().
ViewRelevanceType
EHISMViewRelevanceType UHierarchicalInstancedStaticMeshComponent::ViewRelevanceType = EHISMViewRelevanceType::HISM protected
Definition at line 399 of file HierarchicalInstancedStaticMeshComponent.h.
Referenced by GetViewRelevanceType().
The documentation for this class was generated from the following file:
Runtime/Engine/Classes/Components/HierarchicalInstancedStaticMeshComponent.h