Unreal Engine 5.6 C++ API: TBasicLayoutWidgetSlot< SlotType > Class Template Reference
TBasicLayoutWidgetSlot< SlotType > Class Template Reference
A templated basic slot that can be used by layout.
#include "BasicLayoutWidgetSlot.h"
Public Member Functions
TBasicLayoutWidgetSlot ()
TBasicLayoutWidgetSlot (const EHorizontalAlignment InHAlign, const EVerticalAlignment InVAlign)
TBasicLayoutWidgetSlot (FChildren &InOwner)
TBasicLayoutWidgetSlot (FChildren &InOwner, const EHorizontalAlignment InHAlign, const EVerticalAlignment InVAlign)
SLATE_SLOT_BEGIN_ARGS_TwoMixins (TBasicLayoutWidgetSlot, TSlotBase< SlotType >, TPaddingWidgetSlotMixin< SlotType >, TAlignmentWidgetSlotMixin< SlotType >) SLATE_SLOT_END_ARGS() void Construct(const FChildren &SlotOwner
TAlignmentWidgetSlotMixin (SlotOwner, MoveTemp(InArgs))
TPaddingWidgetSlotMixin (SlotOwner, MoveTemp(InArgs))
Public Member Functions inherited from TWidgetSlotWithAttributeSupport< SlotType >
virtual ~TWidgetSlotWithAttributeSupport ()
void Construct (const FChildren &SlotOwner, typename Super::FSlotArguments &&InArgs)
virtual FName GetContainerName () const override
virtual uint32 GetContainerSortOrder () const override
virtual SWidget & GetContainerWidget () const override
void RequestSortAttribute ()
Public Member Functions inherited from TSlotBase< SlotType >
void Construct (const FChildren &SlotOwner, FSlotArguments &&InArgs)
SlotType & Expose (SlotType *&OutVarToInit)
FSlotBase ()
FSlotBase (const FChildren &InParent)
FSlotBase (const FSlotBase &)=delete
FSlotBase (const TSharedRef< SWidget > &InWidget)
SlotType & operator[] (const TSharedRef< SWidget > &InChildWidget)
SlotType & operator[] (TSharedRef< SWidget > &&InChildWidget)
Public Member Functions inherited from FSlotBase
FSlotBase ()
FSlotBase (const FChildren &InParent)
FSlotBase (const FSlotBase &)=delete
FSlotBase (const TSharedRef< SWidget > &InWidget)
virtual ~FSlotBase ()
FORCEINLINE_DEBUGGABLE void AttachWidget (const TSharedRef< SWidget > &InWidget)
FORCEINLINE_DEBUGGABLE void AttachWidget (TSharedRef< SWidget > &&InWidget)
Attach the child widget the slot now owns.
const TSharedPtr< SWidget > DetachWidget ()
Remove the widget from its current slot.
const FChildren * GetOwner () const
Access the FChildren that own the slot.
SWidget * GetOwnerWidget () const
Access the widget that own the slot.
FORCEINLINE_DEBUGGABLE const TSharedRef< SWidget > & GetWidget () const
Access the widget in the current slot.
void Invalidate (EInvalidateWidgetReason InvalidateReason)
Invalidate the widget's owner.
FSlotBase & operator= (const FSlotBase &)=delete
void SetOwner (const FChildren &Children)
Set the owner of the slot.
Public Member Functions inherited from TPaddingWidgetSlotMixin< SlotType >
TPaddingWidgetSlotMixin ()
FMargin GetPadding () const
void SetPadding (TAttribute< FMargin > InPadding)
Public Member Functions inherited from TAlignmentWidgetSlotMixin< SlotType >
TAlignmentWidgetSlotMixin ()
EHorizontalAlignment GetHorizontalAlignment () const
EVerticalAlignment GetVerticalAlignment () const
void SetHorizontalAlignment (EHorizontalAlignment Alignment)
void SetVerticalAlignment (EVerticalAlignment Alignment)
Static Public Member Functions
static void RegisterAttributes (FSlateWidgetSlotAttributeInitializer &AttributeInitializer)
Static Public Member Functions inherited from TWidgetSlotWithAttributeSupport< SlotType >
static void RegisterAttributes (FSlateWidgetSlotAttributeInitializer &AttributeInitializer)
Data Fields
FSlotArguments && InArgs
Additional Inherited Members
Public Types inherited from TSlotBase< SlotType >
enum EConstructSlotIsFChildren { ConstructSlotIsFChildren }
Argument to indicate the Slot is also its owner.
Protected Member Functions inherited from FSlotBase
template<typename TargetValueType, typename SourceValueType>
bool SetAttribute (TAttribute< TargetValueType > &TargetValue, const TAttribute< SourceValueType > &SourceValue, EInvalidateWidgetReason BaseInvalidationReason)
Performs the attribute assignment and invalidates the widget minimally based on what actually changed.
Protected Member Functions inherited from TPaddingWidgetSlotMixin< SlotType >
void ConstructMixin (const FChildren &SlotOwner, FSlotArgumentsMixin &&InArgs)
Protected Member Functions inherited from TAlignmentWidgetSlotMixin< SlotType >
void ConstructMixin (const FChildren &SlotOwner, FSlotArgumentsMixin &&InArgs)
Static Protected Member Functions inherited from TPaddingWidgetSlotMixin< SlotType >
static void RegisterAttributesMixin (FSlateWidgetSlotAttributeInitializer &AttributeInitializer)
Detailed Description
template<typename SlotType>
class TBasicLayoutWidgetSlot< SlotType >
A templated basic slot that can be used by layout.
Definition at line 596 of file BasicLayoutWidgetSlot.h.
Constructor & Destructor Documentation
TBasicLayoutWidgetSlot() [1/4]
template<typename SlotType> TBasicLayoutWidgetSlot< SlotType >::TBasicLayoutWidgetSlot () inline
Definition at line 601 of file BasicLayoutWidgetSlot.h.
References TAlignmentWidgetSlotMixin(), and TPaddingWidgetSlotMixin().
Referenced by SLATE_SLOT_BEGIN_ARGS_TwoMixins().
TBasicLayoutWidgetSlot() [2/4]
template<typename SlotType> TBasicLayoutWidgetSlot< SlotType >::TBasicLayoutWidgetSlot (FChildren & InOwner) inline
Definition at line 607 of file BasicLayoutWidgetSlot.h.
References TAlignmentWidgetSlotMixin(), and TPaddingWidgetSlotMixin().
TBasicLayoutWidgetSlot() [3/4]
template<typename SlotType> TBasicLayoutWidgetSlot< SlotType >::TBasicLayoutWidgetSlot (const EHorizontalAlignment InHAlign, const EVerticalAlignment InVAlign) inline
Definition at line 613 of file BasicLayoutWidgetSlot.h.
References TAlignmentWidgetSlotMixin(), and TPaddingWidgetSlotMixin().
TBasicLayoutWidgetSlot() [4/4]
template<typename SlotType> TBasicLayoutWidgetSlot< SlotType >::TBasicLayoutWidgetSlot (FChildren & InOwner, const EHorizontalAlignment InHAlign, const EVerticalAlignment InVAlign) inline
Definition at line 619 of file BasicLayoutWidgetSlot.h.
References TAlignmentWidgetSlotMixin(), and TPaddingWidgetSlotMixin().
Member Function Documentation
RegisterAttributes()
template<typename SlotType> void TBasicLayoutWidgetSlot< SlotType >::RegisterAttributes (FSlateWidgetSlotAttributeInitializer & AttributeInitializer) inline static
Definition at line 636 of file BasicLayoutWidgetSlot.h.
References TWidgetSlotWithAttributeSupport< SlotType >::RegisterAttributes(), and TPaddingWidgetSlotMixin< MixedIntoType >::RegisterAttributesMixin().
SLATE_SLOT_BEGIN_ARGS_TwoMixins()
template<typename SlotType> TBasicLayoutWidgetSlot< SlotType >::SLATE_SLOT_BEGIN_ARGS_TwoMixins (TBasicLayoutWidgetSlot< SlotType > , TSlotBase< SlotType > , TPaddingWidgetSlotMixin< SlotType > , TAlignmentWidgetSlotMixin< SlotType >) const &
References TBasicLayoutWidgetSlot(), TAlignmentWidgetSlotMixin(), and TPaddingWidgetSlotMixin().
TAlignmentWidgetSlotMixin()
template<typename SlotType> TBasicLayoutWidgetSlot< SlotType >::TAlignmentWidgetSlotMixin (SlotOwner , MoveTemp(InArgs))
References InArgs.
Referenced by TBasicLayoutWidgetSlot(), TBasicLayoutWidgetSlot(), TBasicLayoutWidgetSlot(), TBasicLayoutWidgetSlot(), and SLATE_SLOT_BEGIN_ARGS_TwoMixins().
TPaddingWidgetSlotMixin()
template<typename SlotType> TBasicLayoutWidgetSlot< SlotType >::TPaddingWidgetSlotMixin (SlotOwner , MoveTemp(InArgs))
References InArgs.
Referenced by TBasicLayoutWidgetSlot(), TBasicLayoutWidgetSlot(), TBasicLayoutWidgetSlot(), TBasicLayoutWidgetSlot(), and SLATE_SLOT_BEGIN_ARGS_TwoMixins().
Field Documentation
InArgs
template<typename SlotType> FSlotArguments&& TBasicLayoutWidgetSlot< SlotType >::InArgs
Initial value:
{
        TWidgetSlotWithAttributeSupport<SlotType>::Construct(SlotOwner, MoveTemp(InArgs))
Definition at line 629 of file BasicLayoutWidgetSlot.h.
Referenced by TAlignmentWidgetSlotMixin(), and TPaddingWidgetSlotMixin().
The documentation for this class was generated from the following file:
Runtime/SlateCore/Public/Layout/BasicLayoutWidgetSlot.h