Unreal Engine 5.6 C++ API: TLazySingleton< T > Class Template Reference
TLazySingleton< T > Class Template Reference final
Lazy singleton that can be torn down explicitly.
#include "LazySingleton.h"
Static Public Member Functions
static T & Get ()
Creates singleton once on first call.
static void TearDown ()
Destroys singleton.
static T * TryGet ()
Get or create singleton unless it's torn down.
Private Member Functions
TLazySingleton (void(*Constructor)(void *))
~TLazySingleton ()
T & GetValue ()
void Reset ()
T * TryGetValue ()
Static Private Member Functions
static TLazySingleton & GetLazy (void(*Constructor)(void *))
Private Attributes
unsigned char Data [sizeof(T)]
T * Ptr
Additional Inherited Members
Static Protected Member Functions inherited from FLazySingleton
template<class T>
static void Construct (void *Place)
template<class T>
static void Destruct (T *Instance)
Detailed Description
template<class T>
class TLazySingleton< T >
Lazy singleton that can be torn down explicitly.
Defining DISABLE_LAZY_SINGLETON_DESTRUCTION stops automatic static destruction and will instead leak singletons that have not been explicitly torn down. This helps prevent shutdown crashes and deadlocks in quick exit scenarios such as ExitProcess() on Windows.
T must be default constructible.
Example use case:
struct FOo { static FOo& Get(); static void TearDown();
// If default constructor is private friend class FLazySingleton; };
// Only include in .cpp and do not inline Get() and TearDown() #include "Misc/LazySingleton.h"
FOo& FOo::Get() { return TLazySingleton<FOo>::Get(); }
void FOo::TearDown() { TLazySingleton<FOo>::TearDown(); }
Definition at line 50 of file LazySingleton.h.
Constructor & Destructor Documentation
TLazySingleton()
template<class T> TLazySingleton< T >::TLazySingleton (void(* Constructor)(void *)) inline private
Definition at line 85 of file LazySingleton.h.
References Data, and Ptr.
Referenced by GetLazy().
~TLazySingleton()
template<class T> TLazySingleton< T >::~TLazySingleton () inline private
Definition at line 96 of file LazySingleton.h.
References Reset().
Member Function Documentation
Get()
template<class T> T & TLazySingleton< T >::Get () inline static
Creates singleton once on first call.
Thread-safe w.r.t. other Get() calls. Do not call after TearDown().
Definition at line 58 of file LazySingleton.h.
References FLazySingleton::Construct(), GetLazy(), and GetValue().
GetLazy()
template<class T> TLazySingleton & TLazySingleton< T >::GetLazy (void(* Constructor)(void *)) inline static private
Definition at line 76 of file LazySingleton.h.
References TLazySingleton(), and TCueDispatchTable< TCueHandler >::Singleton.
Referenced by Get(), TearDown(), and TryGet().
GetValue()
template<class T> T & TLazySingleton< T >::GetValue () inline private
Definition at line 107 of file LazySingleton.h.
References check, and Ptr.
Referenced by Get().
Reset()
template<class T> void TLazySingleton< T >::Reset () inline private
Definition at line 113 of file LazySingleton.h.
References FLazySingleton::Destruct(), and Ptr.
Referenced by ~TLazySingleton(), and TearDown().
TearDown()
template<class T> void TLazySingleton< T >::TearDown () inline static
Destroys singleton.
No thread must access the singleton during or after this call.
Definition at line 64 of file LazySingleton.h.
References GetLazy(), and Reset().
TryGet()
template<class T> T * TLazySingleton< T >::TryGet () inline static
Get or create singleton unless it's torn down.
Definition at line 70 of file LazySingleton.h.
References FLazySingleton::Construct(), GetLazy(), and TryGetValue().
TryGetValue()
template<class T> T * TLazySingleton< T >::TryGetValue () inline private
Definition at line 102 of file LazySingleton.h.
References Ptr.
Referenced by TryGet().
Field Documentation
Data
template<class T> unsigned char TLazySingleton< T >::Data[sizeof(T)] private
Definition at line 82 of file LazySingleton.h.
Referenced by TLazySingleton().
Ptr
template<class T> T* TLazySingleton< T >::Ptr private
Definition at line 83 of file LazySingleton.h.
Referenced by TLazySingleton(), GetValue(), Reset(), and TryGetValue().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Misc/LazySingleton.h