Unreal Engine 5.6 C++ API: FSlateDebugging Class Reference
FSlateDebugging Class Reference
#include "SlateDebugging.h"
Data Structures
struct FLastCursorQuery
struct FScopeProcessInputEvent
struct FScopeRouteInputEvent
struct IWidgetInputRoutingEvent
Public Member Functions
DECLARE_MULTICAST_DELEGATE_FourParams (FPaintDebugElements, const FPaintArgs &, const FGeometry &, FSlateWindowElementList &, int32 &)
Called once the window is drawn (including PaintDeferred).
DECLARE_MULTICAST_DELEGATE_OneParam (FBeginWindow, const FSlateWindowElementList &)
Called when a widget begins painting.
PRAGMA_ENABLE_DEPRECATION_WARNINGS DECLARE_MULTICAST_DELEGATE_OneParam (FDrawElementType, const FSlateDebuggingElementTypeAddedEventArgs &)
Called as soon as the element is added to the element list.
DECLARE_MULTICAST_DELEGATE_OneParam (FEndWindow, const FSlateWindowElementList &)
Called when a window finishes painting.
DECLARE_MULTICAST_DELEGATE_OneParam (FWidgetAttemptNavigationEvent, const FSlateDebuggingNavigationEventArgs &)
DECLARE_MULTICAST_DELEGATE_OneParam (FWidgetCursorQuery, const FSlateDebuggingCursorQueryEventArgs &)
DECLARE_MULTICAST_DELEGATE_OneParam (FWidgetExecuteNavigationEvent, const FSlateDebuggingExecuteNavigationEventArgs &)
DECLARE_MULTICAST_DELEGATE_OneParam (FWidgetFocusEvent, const FSlateDebuggingFocusEventArgs &)
DECLARE_MULTICAST_DELEGATE_OneParam (FWidgetInputEvent, const FSlateDebuggingInputEventArgs &)
DECLARE_MULTICAST_DELEGATE_OneParam (FWidgetInvalidate, const FSlateDebuggingInvalidateArgs &)
DECLARE_MULTICAST_DELEGATE_OneParam (FWidgetMouseCaptureEvent, const FSlateDebuggingMouseCaptureEventArgs &)
DECLARE_MULTICAST_DELEGATE_OneParam (FWidgetUpdatedEvent, const FSlateDebuggingWidgetUpdatedEventArgs &)
DECLARE_MULTICAST_DELEGATE_OneParam (FWidgetWarningEvent, const FSlateDebuggingWarningEventArgs &)
DECLARE_MULTICAST_DELEGATE_SixParams (FBeginWidgetPaint, const SWidget *, const FPaintArgs &, const FGeometry &, const FSlateRect &, const FSlateWindowElementList &, int32)
Called just before a widget paints.
DECLARE_MULTICAST_DELEGATE_ThreeParams (FEndWidgetPaint, const SWidget *, const FSlateWindowElementList &, int32)
Called after a widget finishes painting.
DECLARE_MULTICAST_DELEGATE_TwoParams (FUICommandRun, const FName &, const FText &)
UE_DEPRECATED (5.2, "FSlateDebugging::ElementAdded is deprecated, use FSlateDebugging::ElementTypeAdded instead") DECLARE_MULTICAST_DELEGATE_TwoParams(FDrawElement
Called as soon as the element is added to the element list.
Static Public Member Functions
static void BroadcastAttemptNavigation (const FNavigationEvent &InNavigationEvent, const FNavigationReply &InNavigationReply, const FWidgetPath &InNavigationSource, const TSharedPtr< SWidget > &InDestinationWidget, ESlateDebuggingNavigationMethod InNavigationMethod)
static void BroadcastCursorQuery (TSharedPtr< const SWidget > InWidgetOverridingCursor, const FCursorReply &InReply)
static void BroadcastExecuteNavigation ()
static void BroadcastFocusChanging (const FFocusEvent &InFocusEvent, const FWeakWidgetPath &InOldFocusedWidgetPath, const TSharedPtr< SWidget > &InOldFocusedWidget, const FWidgetPath &InNewFocusedWidgetPath, const TSharedPtr< SWidget > &InNewFocusedWidget)
static void BroadcastFocusLost (const FFocusEvent &InFocusEvent, const FWeakWidgetPath &InOldFocusedWidgetPath, const TSharedPtr< SWidget > &InOldFocusedWidget, const FWidgetPath &InNewFocusedWidgetPath, const TSharedPtr< SWidget > &InNewFocusedWidget)
static void BroadcastFocusReceived (const FFocusEvent &InFocusEvent, const FWeakWidgetPath &InOldFocusedWidgetPath, const TSharedPtr< SWidget > &InOldFocusedWidget, const FWidgetPath &InNewFocusedWidgetPath, const TSharedPtr< SWidget > &InNewFocusedWidget)
static void BroadcastInputEvent (ESlateDebuggingInputEvent InputEventType, const FInputEvent *InInputEvent, const FReply &InReply)
static void BroadcastInputEvent (ESlateDebuggingInputEvent InputEventType, const FInputEvent *InInputEvent, const FReply &InReply, const TSharedPtr< SWidget > &HandlerWidget)
static void BroadcastInputEvent (ESlateDebuggingInputEvent InputEventType, const FInputEvent *InInputEvent, const FReply &InReply, const TSharedPtr< SWidget > &HandlerWidget, const FName &AdditionalContent)
static void BroadcastInputEvent (ESlateDebuggingInputEvent InputEventType, const FInputEvent *InInputEvent, const FReply &InReply, const TSharedPtr< SWidget > &HandlerWidget, const FString &AdditionalContent)
static void BroadcastInputEvent (ESlateDebuggingInputEvent InputEventType, const FInputEvent *InInputEvent, const FReply &InReply, const TSharedPtr< SWidget > &HandlerWidget, const TCHAR AdditionalContent)
static void BroadcastInputEvent (ESlateDebuggingInputEvent InputEventType, const FInputEvent *InInputEvent, const TSharedPtr< SWidget > &HandlerWidget)
static void BroadcastInvalidationRootInvalidate (const SWidget *WidgetInvalidated, const SWidget *WidgetInvalidateInvestigator, ESlateDebuggingInvalidateRootReason InvalidateReason)
static void BroadcastMouseCapture (uint32 UserIndex, uint32 PointerIndex, TSharedPtr< const SWidget > InCapturingWidget)
static void BroadcastMouseCaptureLost (uint32 UserIndex, uint32 PointerIndex, TSharedPtr< const SWidget > InWidgetLostCapture)
static void BroadcastNoReplyInputEvent (ESlateDebuggingInputEvent InputEventType, const FInputEvent *InInputEvent, const TSharedPtr< SWidget > &HandlerWidget)
static void BroadcastPreProcessInputEvent (ESlateDebuggingInputEvent InputEventType, const TCHAR *InputPrecessorName, bool bHandled)
static void BroadcastWarning (const FText &WarningText, const TSharedPtr< SWidget > &OptionalContextWidget)
static void BroadcastWidgetInvalidate (const SWidget *WidgetInvalidated, const SWidget *WidgetInvalidateInvestigator, EInvalidateWidgetReason InvalidateReason)
static void BroadcastWidgetUpdated (const SWidget *Invalidated, EWidgetUpdateFlags UpdateFlags)
static void BroadcastWidgetUpdatedByPaint (const SWidget *Invalidated, EWidgetUpdateFlags UpdateFlags)
static void ExportWidgetList (FStringView Filename)
static const TArray< const SWidget * > & GetAllWidgets ()
static void RegisterWidgetInputRoutingEvent (IWidgetInputRoutingEvent *Event)
static void UnregisterWidgetInputRoutingEvent (IWidgetInputRoutingEvent *Event)
Data Fields
const FSlateWindowElementList int32
Static Public Attributes
static FWidgetAttemptNavigationEvent AttemptNavigationEvent
static FBeginWidgetPaint BeginWidgetPaint
static FBeginWindow BeginWindow
static FUICommandRun CommandRun
static FWidgetCursorQuery CursorChangedEvent
static PRAGMA_DISABLE_DEPRECATION_WARNINGS FDrawElement ElementAdded
static FDrawElementType ElementTypeAdded
static FEndWidgetPaint EndWidgetPaint
static FEndWindow EndWindow
static FWidgetExecuteNavigationEvent ExecuteNavigationEvent
static FWidgetFocusEvent FocusEvent
static FWidgetInputEvent InputEvent
static FWidgetMouseCaptureEvent MouseCaptureEvent
static FPaintDebugElements PaintDebugElements
static FWidgetWarningEvent Warning
static FWidgetInvalidate WidgetInvalidateEvent
static FWidgetUpdatedEvent WidgetUpdatedEvent
Private Member Functions
FSlateDebugging ()=delete
Static Private Attributes
static FLastCursorQuery LastCursorQuery
static TArray< IWidgetInputRoutingEvent * > RoutingEvents
Detailed Description
Definition at line 280 of file SlateDebugging.h.
Constructor & Destructor Documentation
FSlateDebugging()
FSlateDebugging::FSlateDebugging () private delete
Member Function Documentation
BroadcastAttemptNavigation()
void FSlateDebugging::BroadcastAttemptNavigation (const FNavigationEvent & InNavigationEvent, const FNavigationReply & InNavigationReply, const FWidgetPath & InNavigationSource, const TSharedPtr< SWidget > & InDestinationWidget, ESlateDebuggingNavigationMethod InNavigationMethod) static
BroadcastCursorQuery()
void FSlateDebugging::BroadcastCursorQuery (TSharedPtr< const SWidget > InWidgetOverridingCursor, const FCursorReply & InReply) static
BroadcastExecuteNavigation()
void FSlateDebugging::BroadcastExecuteNavigation () static
BroadcastFocusChanging()
void FSlateDebugging::BroadcastFocusChanging (const FFocusEvent & InFocusEvent, const FWeakWidgetPath & InOldFocusedWidgetPath, const TSharedPtr< SWidget > & InOldFocusedWidget, const FWidgetPath & InNewFocusedWidgetPath, const TSharedPtr< SWidget > & InNewFocusedWidget) static
BroadcastFocusLost()
void FSlateDebugging::BroadcastFocusLost (const FFocusEvent & InFocusEvent, const FWeakWidgetPath & InOldFocusedWidgetPath, const TSharedPtr< SWidget > & InOldFocusedWidget, const FWidgetPath & InNewFocusedWidgetPath, const TSharedPtr< SWidget > & InNewFocusedWidget) static
BroadcastFocusReceived()
void FSlateDebugging::BroadcastFocusReceived (const FFocusEvent & InFocusEvent, const FWeakWidgetPath & InOldFocusedWidgetPath, const TSharedPtr< SWidget > & InOldFocusedWidget, const FWidgetPath & InNewFocusedWidgetPath, const TSharedPtr< SWidget > & InNewFocusedWidget) static
BroadcastInputEvent() [1/6]
void FSlateDebugging::BroadcastInputEvent (ESlateDebuggingInputEvent InputEventType, const FInputEvent * InInputEvent, const FReply & InReply) static
References BroadcastInputEvent().
Referenced by BroadcastInputEvent(), BroadcastInputEvent(), BroadcastInputEvent(), BroadcastInputEvent(), BroadcastInputEvent(), and BroadcastInputEvent().
BroadcastInputEvent() [2/6]
void FSlateDebugging::BroadcastInputEvent (ESlateDebuggingInputEvent InputEventType, const FInputEvent * InInputEvent, const FReply & InReply, const TSharedPtr< SWidget > & HandlerWidget) static
References BroadcastInputEvent().
BroadcastInputEvent() [3/6]
void FSlateDebugging::BroadcastInputEvent (ESlateDebuggingInputEvent InputEventType, const FInputEvent * InInputEvent, const FReply & InReply, const TSharedPtr< SWidget > & HandlerWidget, const FName & AdditionalContent) static
References BroadcastInputEvent().
BroadcastInputEvent() [4/6]
void FSlateDebugging::BroadcastInputEvent (ESlateDebuggingInputEvent InputEventType, const FInputEvent * InInputEvent, const FReply & InReply, const TSharedPtr< SWidget > & HandlerWidget, const FString & AdditionalContent) static
References BroadcastInputEvent().
BroadcastInputEvent() [5/6]
void FSlateDebugging::BroadcastInputEvent (ESlateDebuggingInputEvent InputEventType, const FInputEvent * InInputEvent, const FReply & InReply, const TSharedPtr< SWidget > & HandlerWidget, const TCHAR AdditionalContent) static
References BroadcastInputEvent().
BroadcastInputEvent() [6/6]
void FSlateDebugging::BroadcastInputEvent (ESlateDebuggingInputEvent InputEventType, const FInputEvent * InInputEvent, const TSharedPtr< SWidget > & HandlerWidget) static
References BroadcastInputEvent().
BroadcastInvalidationRootInvalidate()
void FSlateDebugging::BroadcastInvalidationRootInvalidate (const SWidget * WidgetInvalidated, const SWidget * WidgetInvalidateInvestigator, ESlateDebuggingInvalidateRootReason InvalidateReason) static
BroadcastMouseCapture()
void FSlateDebugging::BroadcastMouseCapture (uint32 UserIndex, uint32 PointerIndex, TSharedPtr< const SWidget > InCapturingWidget) static
BroadcastMouseCaptureLost()
void FSlateDebugging::BroadcastMouseCaptureLost (uint32 UserIndex, uint32 PointerIndex, TSharedPtr< const SWidget > InWidgetLostCapture) static
BroadcastNoReplyInputEvent()
void FSlateDebugging::BroadcastNoReplyInputEvent (ESlateDebuggingInputEvent InputEventType, const FInputEvent * InInputEvent, const TSharedPtr< SWidget > & HandlerWidget) static
References BroadcastNoReplyInputEvent().
Referenced by BroadcastNoReplyInputEvent().
BroadcastPreProcessInputEvent()
void FSlateDebugging::BroadcastPreProcessInputEvent (ESlateDebuggingInputEvent InputEventType, const TCHAR * InputPrecessorName, bool bHandled) static
BroadcastWarning()
void FSlateDebugging::BroadcastWarning (const FText & WarningText, const TSharedPtr< SWidget > & OptionalContextWidget) static
References BroadcastWarning().
Referenced by BroadcastWarning().
BroadcastWidgetInvalidate()
void FSlateDebugging::BroadcastWidgetInvalidate (const SWidget * WidgetInvalidated, const SWidget * WidgetInvalidateInvestigator, EInvalidateWidgetReason InvalidateReason) static
BroadcastWidgetUpdated()
void FSlateDebugging::BroadcastWidgetUpdated (const SWidget * Invalidated, EWidgetUpdateFlags UpdateFlags) static
BroadcastWidgetUpdatedByPaint()
void FSlateDebugging::BroadcastWidgetUpdatedByPaint (const SWidget * Invalidated, EWidgetUpdateFlags UpdateFlags) static
DECLARE_MULTICAST_DELEGATE_FourParams()
FSlateDebugging::DECLARE_MULTICAST_DELEGATE_FourParams (FPaintDebugElements , const FPaintArgs & , const FGeometry & , FSlateWindowElementList & , int32 &)
Called once the window is drawn (including PaintDeferred).
It can be used to draw additional debug info on top of the window.
References int32.
DECLARE_MULTICAST_DELEGATE_OneParam() [1/12]
FSlateDebugging::DECLARE_MULTICAST_DELEGATE_OneParam (FBeginWindow , const FSlateWindowElementList &)
Called when a widget begins painting.
Referenced by DECLARE_MULTICAST_DELEGATE_OneParam(), DECLARE_MULTICAST_DELEGATE_OneParam(), and DECLARE_MULTICAST_DELEGATE_OneParam().
DECLARE_MULTICAST_DELEGATE_OneParam() [2/12]
PRAGMA_ENABLE_DEPRECATION_WARNINGS FSlateDebugging::DECLARE_MULTICAST_DELEGATE_OneParam (FDrawElementType , const FSlateDebuggingElementTypeAddedEventArgs &)
Called as soon as the element is added to the element list.
NOTE: These elements are not valid until the widget finishes painting, or you can resolve them all after the window finishes painting.
References DECLARE_MULTICAST_DELEGATE_OneParam().
DECLARE_MULTICAST_DELEGATE_OneParam() [3/12]
FSlateDebugging::DECLARE_MULTICAST_DELEGATE_OneParam (FEndWindow , const FSlateWindowElementList &)
Called when a window finishes painting.
DECLARE_MULTICAST_DELEGATE_OneParam() [4/12]
FSlateDebugging::DECLARE_MULTICAST_DELEGATE_OneParam (FWidgetAttemptNavigationEvent , const FSlateDebuggingNavigationEventArgs &)
DECLARE_MULTICAST_DELEGATE_OneParam() [5/12]
FSlateDebugging::DECLARE_MULTICAST_DELEGATE_OneParam (FWidgetCursorQuery , const FSlateDebuggingCursorQueryEventArgs &)
DECLARE_MULTICAST_DELEGATE_OneParam() [6/12]
FSlateDebugging::DECLARE_MULTICAST_DELEGATE_OneParam (FWidgetExecuteNavigationEvent , const FSlateDebuggingExecuteNavigationEventArgs &)
DECLARE_MULTICAST_DELEGATE_OneParam() [7/12]
FSlateDebugging::DECLARE_MULTICAST_DELEGATE_OneParam (FWidgetFocusEvent , const FSlateDebuggingFocusEventArgs &)
DECLARE_MULTICAST_DELEGATE_OneParam() [8/12]
FSlateDebugging::DECLARE_MULTICAST_DELEGATE_OneParam (FWidgetInputEvent , const FSlateDebuggingInputEventArgs &)
References DECLARE_MULTICAST_DELEGATE_OneParam().
DECLARE_MULTICAST_DELEGATE_OneParam() [9/12]
FSlateDebugging::DECLARE_MULTICAST_DELEGATE_OneParam (FWidgetInvalidate , const FSlateDebuggingInvalidateArgs &)
DECLARE_MULTICAST_DELEGATE_OneParam() [10/12]
FSlateDebugging::DECLARE_MULTICAST_DELEGATE_OneParam (FWidgetMouseCaptureEvent , const FSlateDebuggingMouseCaptureEventArgs &)
DECLARE_MULTICAST_DELEGATE_OneParam() [11/12]
FSlateDebugging::DECLARE_MULTICAST_DELEGATE_OneParam (FWidgetUpdatedEvent , const FSlateDebuggingWidgetUpdatedEventArgs &)
DECLARE_MULTICAST_DELEGATE_OneParam() [12/12]
FSlateDebugging::DECLARE_MULTICAST_DELEGATE_OneParam (FWidgetWarningEvent , const FSlateDebuggingWarningEventArgs &)
References DECLARE_MULTICAST_DELEGATE_OneParam().
DECLARE_MULTICAST_DELEGATE_SixParams()
FSlateDebugging::DECLARE_MULTICAST_DELEGATE_SixParams (FBeginWidgetPaint , const SWidget * , const FPaintArgs & , const FGeometry & , const FSlateRect & , const FSlateWindowElementList & , int32)
Called just before a widget paints.
References int32.
DECLARE_MULTICAST_DELEGATE_ThreeParams()
FSlateDebugging::DECLARE_MULTICAST_DELEGATE_ThreeParams (FEndWidgetPaint , const SWidget * , const FSlateWindowElementList & , int32)
Called after a widget finishes painting.
References int32.
DECLARE_MULTICAST_DELEGATE_TwoParams()
FSlateDebugging::DECLARE_MULTICAST_DELEGATE_TwoParams (FUICommandRun , const FName & , const FText &)
ExportWidgetList()
void FSlateDebugging::ExportWidgetList (FStringView Filename) static
References Filename.
GetAllWidgets()
const TArray< const SWidget * > & FSlateDebugging::GetAllWidgets () static
RegisterWidgetInputRoutingEvent()
void FSlateDebugging::RegisterWidgetInputRoutingEvent (IWidgetInputRoutingEvent * Event) static
References Event.
UE_DEPRECATED()
FSlateDebugging::UE_DEPRECATED (5. 2, "FSlateDebugging::ElementAdded is deprecated, use FSlateDebugging::ElementTypeAdded instead")
Called as soon as the element is added to the element list.
NOTE: These elements are not valid until the widget finishes painting, or you can resolve them all after the window finishes painting.
UnregisterWidgetInputRoutingEvent()
void FSlateDebugging::UnregisterWidgetInputRoutingEvent (IWidgetInputRoutingEvent * Event) static
References Event.
Field Documentation
AttemptNavigationEvent
FWidgetAttemptNavigationEvent FSlateDebugging::AttemptNavigationEvent static
Definition at line 385 of file SlateDebugging.h.
BeginWidgetPaint
FBeginWidgetPaint FSlateDebugging::BeginWidgetPaint static
Definition at line 293 of file SlateDebugging.h.
BeginWindow
FBeginWindow FSlateDebugging::BeginWindow static
Definition at line 285 of file SlateDebugging.h.
CommandRun
FUICommandRun FSlateDebugging::CommandRun static
Definition at line 426 of file SlateDebugging.h.
CursorChangedEvent
FWidgetCursorQuery FSlateDebugging::CursorChangedEvent static
Definition at line 405 of file SlateDebugging.h.
ElementAdded
PRAGMA_DISABLE_DEPRECATION_WARNINGS FDrawElement FSlateDebugging::ElementAdded static
Definition at line 310 of file SlateDebugging.h.
ElementTypeAdded
FDrawElementType FSlateDebugging::ElementTypeAdded static
Definition at line 318 of file SlateDebugging.h.
Referenced by FSlateWindowElementList::AddUninitialized().
EndWidgetPaint
FEndWidgetPaint FSlateDebugging::EndWidgetPaint static
Definition at line 297 of file SlateDebugging.h.
EndWindow
FEndWindow FSlateDebugging::EndWindow static
Definition at line 289 of file SlateDebugging.h.
ExecuteNavigationEvent
FWidgetExecuteNavigationEvent FSlateDebugging::ExecuteNavigationEvent static
Definition at line 391 of file SlateDebugging.h.
FocusEvent
FWidgetFocusEvent FSlateDebugging::FocusEvent static
Definition at line 376 of file SlateDebugging.h.
InputEvent
FWidgetInputEvent FSlateDebugging::InputEvent static
Definition at line 329 of file SlateDebugging.h.
int32
const FSlateWindowElementList FSlateDebugging::int32
Definition at line 308 of file SlateDebugging.h.
Referenced by DECLARE_MULTICAST_DELEGATE_FourParams(), DECLARE_MULTICAST_DELEGATE_SixParams(), and DECLARE_MULTICAST_DELEGATE_ThreeParams().
LastCursorQuery
FLastCursorQuery FSlateDebugging::LastCursorQuery static private
Definition at line 442 of file SlateDebugging.h.
MouseCaptureEvent
FWidgetMouseCaptureEvent FSlateDebugging::MouseCaptureEvent static
Definition at line 398 of file SlateDebugging.h.
PaintDebugElements
FPaintDebugElements FSlateDebugging::PaintDebugElements static
Definition at line 301 of file SlateDebugging.h.
RoutingEvents
TArray<IWidgetInputRoutingEvent*> FSlateDebugging::RoutingEvents static private
Definition at line 444 of file SlateDebugging.h.
Warning
FWidgetWarningEvent FSlateDebugging::Warning static
Definition at line 323 of file SlateDebugging.h.
WidgetInvalidateEvent
FWidgetInvalidate FSlateDebugging::WidgetInvalidateEvent static
Definition at line 411 of file SlateDebugging.h.
WidgetUpdatedEvent
FWidgetUpdatedEvent FSlateDebugging::WidgetUpdatedEvent static
Definition at line 418 of file SlateDebugging.h.
The documentation for this class was generated from the following file:
Runtime/SlateCore/Public/Debugging/SlateDebugging.h