Unreal Engine 5.6 C++ API: Metasound::FInputVertexInterfaceData Class Reference
Metasound::FInputVertexInterfaceData Class Reference
An input vertex interface with optionally bound data references.
#include "MetasoundVertexData.h"
Public Types
using FRangedForConstIteratorType = typename TArray<FInputBinding>::RangedForConstIteratorType
using FRangedForIteratorType = typename TArray<FInputBinding>::RangedForIteratorType
Public Member Functions
METASOUNDGRAPHCORE_API FInputVertexInterfaceData ()
Construct with an FInputVertexInterface.
METASOUNDGRAPHCORE_API FInputVertexInterfaceData (const FInputVertexInterface &InVertexInterface)
Construct with an FInputVertexInterface.
METASOUNDGRAPHCORE_API void AddVertex (const FInputDataVertex &InVertex)
Add a vertex.
METASOUNDGRAPHCORE_API bool AreAllVerticesBound () const
Returns true if all vertices in the FInputVertexInterface are bound to data references.
FRangedForIteratorType begin ()
FRangedForConstIteratorType begin () const
METASOUNDGRAPHCORE_API void Bind (FInputVertexInterfaceData &InOutInputVertexData)
Bind vertex data using other vertex data.
template<typename DataType>
void BindReadVertex (const FVertexName &InVertexName, TDataReadReference< DataType > &InOutDataReference)
Bind a read vertex from a read reference.
template<typename DataType>
void BindReadVertex (const FVertexName &InVertexName, TDataWriteReference< DataType > &InOutDataReference)
Bind a read vertex from a write reference.
template<typename DataReferenceType>
void BindVertex (const FVertexName &InVertexName, DataReferenceType &InOutDataReference)
Bind a vertex with a a data reference.
METASOUNDGRAPHCORE_API void BindVertex (const FVertexName &InVertexName, FAnyDataReference &InOutDataReference)
Bind a vertex with a any data reference.
template<typename DataType>
void BindWriteVertex (const FVertexName &InVertexName, TDataWriteReference< DataType > &InOutDataReference)
Bind a write vertex from a write reference.
METASOUNDGRAPHCORE_API bool Contains (const FVertexName &InVertexName) const
Returns true if a vertex exists with the provided name.
FRangedForIteratorType end ()
FRangedForConstIteratorType end () const
METASOUNDGRAPHCORE_API const FAnyDataReference * FindDataReference (const FVertexName &InVertexName) const
Find data reference bound to vertex.
ForEachSubInterfaceBinding (InSubInterfaceName, InVertexName, INDEX_NONE, GetOrCreateDefault)
ForEachSubInterfaceBinding (InSubInterfaceName, InVertexName, InOutDataReferences.Num(), BindData)
ForEachSubInterfaceBinding (InSubInterfaceName, InVertexName, InOutDataReferences.Num(), BindData)
ForEachSubInterfaceBinding (InSubInterfaceName, InVertexName, InOutDataReferences.Num(), BindData)
ForEachSubInterfaceBinding (InSubInterfaceName, InVertexName, InValues.Num(), BindData)
template<typename DataType>
TDataReadReference< DataType > GetDataReadReference (const FVertexName &InVertexName) const
Get data read reference assuming data is bound and read or write accessible.
template<typename DataType>
TDataWriteReference< DataType > GetDataWriteReference (const FVertexName &InVertexName) const
Get data write reference assuming data is bound and write accessible.
template<typename DataType>
TDataReadReference< DataType > GetOrCreateDefaultDataReadReference (const FVertexName &InVertexName, const FOperatorSettings &InSettings) const
Get the bound data read reference if it exists.
template<typename DataType>
TDataValueReference< DataType > GetOrCreateDefaultDataValueReference (const FVertexName &InVertexName, const FOperatorSettings &InSettings) const
Gets the value of the bound data reference if it exists.
template<typename DataType>
TDataWriteReference< DataType > GetOrCreateDefaultDataWriteReference (const FVertexName &InVertexName, const FOperatorSettings &InSettings) const
Get the bound data write reference if it exists.
template<typename DataType>
DataType GetOrCreateDefaultValue (const FVertexName &InVertexName, const FOperatorSettings &InSettings) const
Gets the value of the bound data reference if it exists.
template<typename DataType>
const DataType * GetValue (const FVertexName &InVertexName) const
Returns the current value of a vertex.
METASOUNDGRAPHCORE_API const FInputDataVertex & GetVertex (const FVertexName &InVertexName) const
Return the vertex associated with the vertex name.
METASOUNDGRAPHCORE_API EDataReferenceAccessType GetVertexDataAccessType (const FVertexName &InVertexName) const
Returns the access type of a bound vertex.
METASOUNDGRAPHCORE_API bool IsVertexBound (const FVertexName &InVertexName) const
Returns true if a vertex with the given vertex name exists and is bound to a data reference.
METASOUNDGRAPHCORE_API bool IsVertexInterfaceFrozen () const
Returns true if the vertex interface is frozen.
METASOUNDGRAPHCORE_API void RemoveVertex (const FVertexName &InVertexName)
Remove a vertex.
METASOUNDGRAPHCORE_API void SetDefaultLiteral (const FVertexName &InVertexName, const FLiteral &InLiteral)
Set the default literal used to create default values.
METASOUNDGRAPHCORE_API void SetIsVertexInterfaceFrozen (bool bInIsVertexInterfaceFrozen)
Set whether the vertex interface is frozen or not.
template<typename DataType>
void SetValue (const FVertexName &InVertexName, const DataType &InValue)
Set the value of a vertex.
METASOUNDGRAPHCORE_API void SetVertex (const FVertexName &InVertexName, const FAnyDataReference &InDataReference)
Sets a vertex to use a data reference, ignoring any existing data bound to the vertex.
METASOUNDGRAPHCORE_API void SetVertex (const FVertexName &InVertexName, FAnyDataReference &&InDataReference)
Sets a vertex to use a data reference, ignoring any existing data bound to the vertex.
UE_DEPRECATED (5.6, "Do not use FDataReferenceCollection.") METASOUNDGRAPHCORE_API FDataReferenceCollection ToDataReferenceCollection() const
Convert vertex data to a data reference collection.
UE_DEPRECATED (5.6, "Do not use FDataReferenceCollection.") METASOUNDGRAPHCORE_API void Set(const FDataReferenceCollection &InCollection)
Set a data references to vertices with matching vertex names.
template<typename DataType, typename ... ConstructorArgTypes>
UE_DEPRECATED (5.6, "Please GetOrCreateDefaultDataReadReference instead.") TDataReadReference< DataType > GetOrConstructDataReadReference(const FVertexName &InVertexName
Get the bound data read reference if it exists.
template<typename DataType, typename ... ConstructorArgTypes>
UE_DEPRECATED (5.6, "Please GetOrCreateDefaultDataWriteReference instead.") TDataWriteReference< DataType > GetOrConstructDataWriteReference(const FVertexName &InVertexName
Get the bound data write reference if it exists.
UE_DEPRECATED (5.6, "Please use a non-const lvalue reference for data references passed to this function. Const data references can sometimes be created by passing in temporary objects and/or triggering implicit conversion.") METASOUNDGRAPHCORE_API void Bind(const FInputVertexInterfaceData &InOutInputVertexData)
Bind vertex data using other vertex data.
UE_DEPRECATED (5.6, "Please use a non-const lvalue reference for data references passed to this function. Const data references can sometimes be created by passing in temporary objects and/or triggering implicit conversion.") METASOUNDGRAPHCORE_API void BindVertex(const FVertexName &InVertexName
Bind a vertex with a any data reference.
template<typename DataType>
UE_DEPRECATED (5.6, "Please use a non-const lvalue reference for data references passed to this function. Const data references can sometimes be created by passing in temporary objects and/or triggering implicit conversion.") void BindReadVertex(const FVertexName &InVertexName
Bind a read vertex from a read reference.
template<typename DataType>
UE_DEPRECATED (5.6, "Please use a non-const lvalue reference for data references passed to this function. Const data references can sometimes be created by passing in temporary objects and/or triggering implicit conversion.") void BindWriteVertex(const FVertexName &InVertexName
Bind a write vertex from a write reference.
UE_EXPERIMENTAL (5.6, "Sub interfaces are still under development") METASOUNDGRAPHCORE_API TArray< const FAnyDataReference * > FindSubInterfaceReferences(const FName &InSubInterfaceName
Find data references bound to the sub interface vertices.
UE_EXPERIMENTAL (5.6, "Sub interfaces are still under development") METASOUNDGRAPHCORE_API uint32 GetNumSubInterfaceInstances(const FName &InSubInterfaceName) const
Return the number of instances of a particular sub interface.
template<typename DataReferenceType>
UE_EXPERIMENTAL (5.6, "Sub interfaces are still under development") TArray< DataReferenceType > GetOrCreateDefaultSubInterfaceAs(const FName &InSubInterfaceName
Get or create an array of data references for all instances of a sub interface vertex.
template<typename DataType>
UE_EXPERIMENTAL (5.6, "Sub interfaces are still under development") TArray< DataType > GetOrCreateDefaultSubInterfaceValues(const FName &InSubInterfaceName
Get or create an array of values for all instances of a sub interface vertex.
template<typename DataType>
UE_EXPERIMENTAL (5.6, "Sub interfaces are still under development") TArray< TDataReadReference< DataType > > GetOrCreateDefaultSubInterfaceDataReadReferences(const FName &InSubInterfaceName
Get or create an array of data read references for all instances of a sub interface vertex.
template<typename DataType>
UE_EXPERIMENTAL (5.6, "Sub interfaces are still under development") TArray< TDataWriteReference< DataType > > GetOrCreateDefaultSubInterfaceDataWriteReferences(const FName &InSubInterfaceName
Get or create an array of data write references for all instances of a sub interface vertex.
template<typename RangeType>
UE_EXPERIMENTAL (5.6, "Sub interfaces are still under development") void BindSubInterfaceReadVertices(const FName &InSubInterfaceName
Bind the vertices of a sub interface vertex as read references.
template<typename RangeType>
UE_EXPERIMENTAL (5.6, "Sub interfaces are still under development") void BindSubInterfaceVertices(const FName &InSubInterfaceName
Bind the vertices of a sub interface vertex.
template<typename RangeType>
UE_EXPERIMENTAL (5.6, "Sub interfaces are still under development") void BindSubInterfaceWriteVertices(const FName &InSubInterfaceName
Bind the vertices of a sub interface vertex as write references.
template<typename RangeType>
UE_EXPERIMENTAL (5.6, "Sub interfaces are still under development") void SetSubInterfaceValues(const FName &InSubInterfaceName
Bind the vertices of a sub interface vertex as value references.
Data Fields
ConstructorArgTypes &&ConstructorArgs const
const FVertexName const FOperatorSettings &InSettings const
const FVertexName &InVertexName const
auto GetOrCreateDefault
const TDataReadReference< DataType > & InOutDataReference
const TDataWriteReference< DataType > & InOutDataReference
const FAnyDataReference & InOutDataReference
const FName RangeType & InOutDataReferences
const FName const RangeType & InValues
const FName & InVertexName
const FVertexName & InVertexName
return References
Private Types
using FInputBinding = VertexDataPrivate::FInputBinding
Private Member Functions
METASOUNDGRAPHCORE_API void Apply (const FVertexName &InVertexName, TFunctionRef< FInputBinding()> InCreateFunc, TFunctionRef< void(FInputBinding &)> InApplyFunc)
METASOUNDGRAPHCORE_API FInputBinding * Find (const FVertexName &InVertexName)
METASOUNDGRAPHCORE_API const FInputBinding * Find (const FVertexName &InVertexName) const
METASOUNDGRAPHCORE_API FInputBinding * FindChecked (const FVertexName &InVertexName)
METASOUNDGRAPHCORE_API const FInputBinding * FindChecked (const FVertexName &InVertexName) const
METASOUNDGRAPHCORE_API const VertexPrivate::FSubInterfaceLayout * FindSubInterface (const FName &InSubInterfaceName) const
METASOUNDGRAPHCORE_API void ForEachSubInterfaceBinding (const FName &InSubInterfaceName, const FVertexName &InVertexName, uint32 InExpectedNumSubInterfaceInstances, TFunctionRef< void(uint32, const FInputBinding &)> InApplyFunc) const
METASOUNDGRAPHCORE_API void ForEachSubInterfaceBinding (const FName &InSubInterfaceName, const FVertexName &InVertexName, uint32 InExpectedNumSubInterfaceInstances, TFunctionRef< void(uint32, FInputBinding &)> InApplyFunc)
Private Attributes
TArray< FInputBinding > Bindings
bool bIsVertexInterfaceFrozen = false
TArray< VertexPrivate::FSubInterfaceLayout > SubInterfaces
Friends
METASOUNDGRAPHCORE_API void CompareVertexInterfaceDataToPriorState (const FInputVertexInterfaceData &InCurrentInterface, const TArray< FVertexDataState > &InPriorState, TSortedVertexNameMap< FAnyDataReference > &OutUpdates)
Compares the current data bound to the vertex interface with a prior cached state.
METASOUNDGRAPHCORE_API void GetVertexInterfaceDataState (const FInputVertexInterfaceData &InVertexInterface, TArray< FVertexDataState > &OutState)
Caches a representation of the current data references bound to the vertex interface.
Detailed Description
An input vertex interface with optionally bound data references.
Definition at line 543 of file MetasoundVertexData.h.
Member Typedef Documentation
FInputBinding
using Metasound::FInputVertexInterfaceData::FInputBinding = VertexDataPrivate::FInputBinding private
Definition at line 545 of file MetasoundVertexData.h.
FRangedForConstIteratorType
using Metasound::FInputVertexInterfaceData::FRangedForConstIteratorType = typename TArray<FInputBinding>::RangedForConstIteratorType
Definition at line 550 of file MetasoundVertexData.h.
FRangedForIteratorType
using Metasound::FInputVertexInterfaceData::FRangedForIteratorType = typename TArray<FInputBinding>::RangedForIteratorType
Definition at line 549 of file MetasoundVertexData.h.
Constructor & Destructor Documentation
FInputVertexInterfaceData() [1/2]
METASOUNDGRAPHCORE_API Metasound::FInputVertexInterfaceData::FInputVertexInterfaceData ()
Construct with an FInputVertexInterface.
This will default to a unfrozen vertex interface.
References UE_API.
Referenced by Bind(), CompareVertexInterfaceDataToPriorState, GetVertexInterfaceDataState, and UE_DEPRECATED().
FInputVertexInterfaceData() [2/2]
METASOUNDGRAPHCORE_API Metasound::FInputVertexInterfaceData::FInputVertexInterfaceData (const FInputVertexInterface & InVertexInterface)
Construct with an FInputVertexInterface.
This will default to a frozen vertex interface.
References UE_API.
Member Function Documentation
AddVertex()
METASOUNDGRAPHCORE_API void Metasound::FInputVertexInterfaceData::AddVertex (const FInputDataVertex & InVertex)
Add a vertex.
VertexInterfaceData must be unfrozen.
References AddVertex(), const, and UE_API.
Referenced by AddVertex().
Apply()
METASOUNDGRAPHCORE_API void Metasound::FInputVertexInterfaceData::Apply (const FVertexName & InVertexName, TFunctionRef< FInputBinding()> InCreateFunc, TFunctionRef< void(FInputBinding &)> InApplyFunc) private
References Apply(), const, InVertexName, and UE_API.
Referenced by Apply(), BindReadVertex(), BindReadVertex(), Metasound::FOutputVertexInterfaceData::BindReadVertex(), Metasound::FOutputVertexInterfaceData::BindReadVertex(), BindVertex(), Metasound::FOutputVertexInterfaceData::BindVertex(), BindWriteVertex(), Metasound::FOutputVertexInterfaceData::BindWriteVertex(), SetValue(), and Metasound::FOutputVertexInterfaceData::SetValue().
AreAllVerticesBound()
METASOUNDGRAPHCORE_API bool Metasound::FInputVertexInterfaceData::AreAllVerticesBound () const
Returns true if all vertices in the FInputVertexInterface are bound to data references.
References AreAllVerticesBound(), const, and UE_API.
Referenced by AreAllVerticesBound().
begin() [1/2]
FRangedForIteratorType Metasound::FInputVertexInterfaceData::begin () inline
Definition at line 763 of file MetasoundVertexData.h.
References begin(), and Bindings.
Referenced by begin().
begin() [2/2]
FRangedForConstIteratorType Metasound::FInputVertexInterfaceData::begin () const inline
Definition at line 773 of file MetasoundVertexData.h.
References Bindings.
Bind()
METASOUNDGRAPHCORE_API void Metasound::FInputVertexInterfaceData::Bind (FInputVertexInterfaceData & InOutInputVertexData)
Bind vertex data using other vertex data.
References FInputVertexInterfaceData(), Bind(), and UE_API.
Referenced by Bind(), and UE_DEPRECATED().
BindReadVertex() [1/2]
template<typename DataType> void Metasound::FInputVertexInterfaceData::BindReadVertex (const FVertexName & InVertexName, TDataReadReference< DataType > & InOutDataReference) inline
Bind a read vertex from a read reference.
Definition at line 599 of file MetasoundVertexData.h.
References Apply(), InOutDataReference, and InVertexName.
Referenced by Metasound::MetasoundVariableNodesPrivate::TVariableMutatorOperator< DataType >::BindInputs(), Metasound::ReceiveNodePrivate::TReceiverOperator< TDataType >::BindInputs(), Metasound::SendNodePrivate::TSendOperator< TDataType >::BindInputs(), Metasound::TArrayConcatOperator< ArrayType >::BindInputs(), Metasound::TArrayGetOperator< ArrayType >::BindInputs(), Metasound::TArrayLastIndexOperator< ArrayType >::BindInputs(), Metasound::TArrayNumOperator< ArrayType >::BindInputs(), Metasound::TArrayRandomGetOperator< ArrayType >::BindInputs(), Metasound::TArraySetOperator< ArrayType >::BindInputs(), Metasound::TArrayShuffleOperator< ArrayType >::BindInputs(), Metasound::TArraySubsetOperator< ArrayType >::BindInputs(), Metasound::TAutoConverterNode< FromDataType, ToDataType >::FConverterOperator::BindInputs(), and Metasound::FOutputVertexInterfaceData::UE_DEPRECATED().
BindReadVertex() [2/2]
template<typename DataType> void Metasound::FInputVertexInterfaceData::BindReadVertex (const FVertexName & InVertexName, TDataWriteReference< DataType > & InOutDataReference) inline
Bind a read vertex from a write reference.
Definition at line 609 of file MetasoundVertexData.h.
References Apply(), InOutDataReference, and InVertexName.
BindVertex() [1/2]
template<typename DataReferenceType> void Metasound::FInputVertexInterfaceData::BindVertex (const FVertexName & InVertexName, DataReferenceType & InOutDataReference) inline
Bind a vertex with a a data reference.
Definition at line 640 of file MetasoundVertexData.h.
References Apply(), BindVertex(), const, InOutDataReference, and InVertexName.
Referenced by Metasound::MetasoundInputNodePrivate::TPostExecutableInputOperator< DataType >::BindInputs(), and BindVertex().
BindVertex() [2/2]
METASOUNDGRAPHCORE_API void Metasound::FInputVertexInterfaceData::BindVertex (const FVertexName & InVertexName, FAnyDataReference & InOutDataReference)
Bind a vertex with a any data reference.
References InOutDataReference, InVertexName, and UE_API.
BindWriteVertex()
template<typename DataType> void Metasound::FInputVertexInterfaceData::BindWriteVertex (const FVertexName & InVertexName, TDataWriteReference< DataType > & InOutDataReference) inline
Bind a write vertex from a write reference.
Definition at line 627 of file MetasoundVertexData.h.
References Apply(), InOutDataReference, and InVertexName.
Referenced by Metasound::MetasoundVariableNodesPrivate::TVariableAccessorOperator< DataType >::BindInputs(), Metasound::MetasoundVariableNodesPrivate::TVariableDeferredAccessorOperator< DataType >::BindInputs(), Metasound::MetasoundVariableNodesPrivate::TVariableMutatorOperator< DataType >::BindInputs(), and Metasound::FOutputVertexInterfaceData::UE_DEPRECATED().
Contains()
METASOUNDGRAPHCORE_API bool Metasound::FInputVertexInterfaceData::Contains (const FVertexName & InVertexName) const
Returns true if a vertex exists with the provided name.
This does not reflect whether the vertex is bound or not.
References InVertexName, and UE_API.
end() [1/2]
FRangedForIteratorType Metasound::FInputVertexInterfaceData::end () inline
Definition at line 768 of file MetasoundVertexData.h.
References Bindings.
end() [2/2]
FRangedForConstIteratorType Metasound::FInputVertexInterfaceData::end () const inline
Definition at line 778 of file MetasoundVertexData.h.
References Bindings.
Find() [1/2]
METASOUNDGRAPHCORE_API FInputBinding * Metasound::FInputVertexInterfaceData::Find (const FVertexName & InVertexName) private
References const, Find(), InVertexName, and UE_API.
Referenced by Find(), and Find().
Find() [2/2]
METASOUNDGRAPHCORE_API const FInputBinding * Metasound::FInputVertexInterfaceData::Find (const FVertexName & InVertexName) const private
References const, Find(), InVertexName, and UE_API.
FindChecked() [1/2]
METASOUNDGRAPHCORE_API FInputBinding * Metasound::FInputVertexInterfaceData::FindChecked (const FVertexName & InVertexName) private
References const, FindChecked(), InVertexName, and UE_API.
Referenced by FindChecked(), FindChecked(), GetDataReadReference(), Metasound::FOutputVertexInterfaceData::GetDataReadReference(), GetDataWriteReference(), Metasound::FOutputVertexInterfaceData::GetDataWriteReference(), GetOrCreateDefaultDataValueReference(), GetOrCreateDefaultValue(), GetValue(), and Metasound::FOutputVertexInterfaceData::GetValue().
FindChecked() [2/2]
METASOUNDGRAPHCORE_API const FInputBinding * Metasound::FInputVertexInterfaceData::FindChecked (const FVertexName & InVertexName) const private
References const, FindChecked(), InVertexName, and UE_API.
FindDataReference()
METASOUNDGRAPHCORE_API const FAnyDataReference * Metasound::FInputVertexInterfaceData::FindDataReference (const FVertexName & InVertexName) const
Find data reference bound to vertex.
Returns a nullptr if no data reference is bound.
References InVertexName, and UE_API.
Referenced by Metasound::MetasoundInputNodePrivate::TInputNodeOperatorFactory< DataType, VertexAccess >::CreateOperator(), Metasound::MetasoundVariableNodesPrivate::TVariableAccessorOperator< DataType >::CreateOperator(), Metasound::MetasoundVariableNodesPrivate::TVariableDeferredAccessorOperator< DataType >::CreateOperator(), and Metasound::MetasoundVariableNodesPrivate::TVariableMutatorOperator< DataType >::CreateOperator().
FindSubInterface()
METASOUNDGRAPHCORE_API const VertexPrivate::FSubInterfaceLayout * Metasound::FInputVertexInterfaceData::FindSubInterface (const FName & InSubInterfaceName) const private
References const, FindSubInterface(), and UE_API.
Referenced by FindSubInterface().
ForEachSubInterfaceBinding() [1/7]
METASOUNDGRAPHCORE_API void Metasound::FInputVertexInterfaceData::ForEachSubInterfaceBinding (const FName & InSubInterfaceName, const FVertexName & InVertexName, uint32 InExpectedNumSubInterfaceInstances, TFunctionRef< void(uint32, const FInputBinding &)> InApplyFunc) const private
References const, ForEachSubInterfaceBinding(), InVertexName, and UE_API.
ForEachSubInterfaceBinding() [2/7]
METASOUNDGRAPHCORE_API void Metasound::FInputVertexInterfaceData::ForEachSubInterfaceBinding (const FName & InSubInterfaceName, const FVertexName & InVertexName, uint32 InExpectedNumSubInterfaceInstances, TFunctionRef< void(uint32, FInputBinding &)> InApplyFunc) private
References const, ForEachSubInterfaceBinding(), InVertexName, and UE_API.
ForEachSubInterfaceBinding() [3/7]
Metasound::FInputVertexInterfaceData::ForEachSubInterfaceBinding (InSubInterfaceName , InVertexName , INDEX_NONE , GetOrCreateDefault)
References GetOrCreateDefault, INDEX_NONE, and InVertexName.
ForEachSubInterfaceBinding() [4/7]
Metasound::FInputVertexInterfaceData::ForEachSubInterfaceBinding (InSubInterfaceName , InVertexName , InOutDataReferences. Num(), BindData)
References InOutDataReferences, and InVertexName.
Referenced by ForEachSubInterfaceBinding(), and ForEachSubInterfaceBinding().
ForEachSubInterfaceBinding() [5/7]
Metasound::FInputVertexInterfaceData::ForEachSubInterfaceBinding (InSubInterfaceName , InVertexName , InOutDataReferences. Num(), BindData)
References InOutDataReferences, and InVertexName.
ForEachSubInterfaceBinding() [6/7]
Metasound::FInputVertexInterfaceData::ForEachSubInterfaceBinding (InSubInterfaceName , InVertexName , InOutDataReferences. Num(), BindData)
References InOutDataReferences, and InVertexName.
ForEachSubInterfaceBinding() [7/7]
Metasound::FInputVertexInterfaceData::ForEachSubInterfaceBinding (InSubInterfaceName , InVertexName , InValues. Num(), BindData)
References InValues, and InVertexName.
GetDataReadReference()
template<typename DataType> TDataReadReference< DataType > Metasound::FInputVertexInterfaceData::GetDataReadReference (const FVertexName & InVertexName) const inline
Get data read reference assuming data is bound and read or write accessible.
Definition at line 820 of file MetasoundVertexData.h.
References FindChecked(), Metasound::VertexDataPrivate::FInputBinding::GetDataReferenceAs(), and InVertexName.
Referenced by Metasound::ReceiveNodePrivate::TReceiverOperator< TDataType >::CreateOperator().
GetDataWriteReference()
template<typename DataType> TDataWriteReference< DataType > Metasound::FInputVertexInterfaceData::GetDataWriteReference (const FVertexName & InVertexName) const inline
Get data write reference assuming data is bound and write accessible.
Definition at line 868 of file MetasoundVertexData.h.
References FindChecked(), Metasound::VertexDataPrivate::FInputBinding::GetDataReferenceAs(), and InVertexName.
GetOrCreateDefaultDataReadReference()
template<typename DataType> TDataReadReference< DataType > Metasound::FInputVertexInterfaceData::GetOrCreateDefaultDataReadReference (const FVertexName & InVertexName, const FOperatorSettings & InSettings) const inline
Get the bound data read reference if it exists.
Otherwise create and return a data read reference by constructing one using the Vertex's default literal.
Definition at line 831 of file MetasoundVertexData.h.
References Metasound::TDataLiteralFactory< DataType, TDataReadReference< DataType > >::CreateExplicitArgs(), Metasound::FLiteral::CreateInvalid(), Find, InVertexName, TEXT, UE_LOG, and Warning.
Referenced by Metasound::MetasoundVariableNodesPrivate::TVariableMutatorOperator< DataType >::CreateOperator(), Metasound::ReceiveNodePrivate::TReceiverOperator< TDataType >::CreateOperator(), Metasound::SendNodePrivate::TSendOperator< TDataType >::CreateOperator(), Metasound::TArrayConcatOperator< ArrayType >::CreateOperator(), Metasound::TArrayGetOperator< ArrayType >::CreateOperator(), Metasound::TArrayLastIndexOperator< ArrayType >::CreateOperator(), Metasound::TArrayNumOperator< ArrayType >::CreateOperator(), Metasound::TArrayRandomGetOperator< ArrayType >::CreateOperator(), Metasound::TArraySetOperator< ArrayType >::CreateOperator(), Metasound::TArrayShuffleOperator< ArrayType >::CreateOperator(), Metasound::TArraySubsetOperator< ArrayType >::CreateOperator(), and Metasound::TAutoConverterNode< FromDataType, ToDataType >::FCoverterOperatorFactory::CreateOperator().
GetOrCreateDefaultDataValueReference()
template<typename DataType> TDataValueReference< DataType > Metasound::FInputVertexInterfaceData::GetOrCreateDefaultDataValueReference (const FVertexName & InVertexName, const FOperatorSettings & InSettings) const inline
Gets the value of the bound data reference if it exists.
Otherwise create and return a value by constructing one using the Vertex's default literal.
Definition at line 812 of file MetasoundVertexData.h.
References FindChecked(), Metasound::VertexDataPrivate::FInputBinding::GetOrCreateDefaultAs(), and InVertexName.
GetOrCreateDefaultDataWriteReference()
template<typename DataType> TDataWriteReference< DataType > Metasound::FInputVertexInterfaceData::GetOrCreateDefaultDataWriteReference (const FVertexName & InVertexName, const FOperatorSettings & InSettings) const inline
Get the bound data write reference if it exists.
Otherwise create and return a data write reference by constructing one using the Vertex's default literal.
Definition at line 879 of file MetasoundVertexData.h.
References Metasound::TDataLiteralFactory< DataType, TDataWriteReference< DataType > >::CreateExplicitArgs(), Metasound::FLiteral::CreateInvalid(), Find, InVertexName, TEXT, UE_LOG, and Warning.
GetOrCreateDefaultValue()
template<typename DataType> DataType Metasound::FInputVertexInterfaceData::GetOrCreateDefaultValue (const FVertexName & InVertexName, const FOperatorSettings & InSettings) const inline
Gets the value of the bound data reference if it exists.
Otherwise create and return a value by constructing one using the Vertex's default literal.
Definition at line 802 of file MetasoundVertexData.h.
References FindChecked(), Metasound::VertexDataPrivate::FInputBinding::GetOrCreateDefaultAs(), and InVertexName.
Referenced by Metasound::TArrayRandomGetOperator< ArrayType >::CreateOperator().
GetValue()
template<typename DataType> const DataType * Metasound::FInputVertexInterfaceData::GetValue (const FVertexName & InVertexName) const inline
Returns the current value of a vertex.
Definition at line 788 of file MetasoundVertexData.h.
References FindChecked(), Metasound::VertexDataPrivate::FInputBinding::GetDataReferenceAs(), InVertexName, and Metasound::VertexDataPrivate::FInputBinding::IsBound().
GetVertex()
METASOUNDGRAPHCORE_API const FInputDataVertex & Metasound::FInputVertexInterfaceData::GetVertex (const FVertexName & InVertexName) const
Return the vertex associated with the vertex name.
References const, GetVertex(), InVertexName, and UE_API.
Referenced by GetVertex().
GetVertexDataAccessType()
METASOUNDGRAPHCORE_API EDataReferenceAccessType Metasound::FInputVertexInterfaceData::GetVertexDataAccessType (const FVertexName & InVertexName) const
Returns the access type of a bound vertex.
If the vertex does not exist or if it is unbound, this will return EDataReferenceAccessType::None
References const, GetVertexDataAccessType(), InVertexName, and UE_API.
Referenced by GetVertexDataAccessType().
IsVertexBound()
METASOUNDGRAPHCORE_API bool Metasound::FInputVertexInterfaceData::IsVertexBound (const FVertexName & InVertexName) const
Returns true if a vertex with the given vertex name exists and is bound to a data reference.
References const, InVertexName, IsVertexBound(), and UE_API.
Referenced by Metasound::ReceiveNodePrivate::TReceiverOperator< TDataType >::CreateOperator(), Metasound::SendNodePrivate::TSendOperator< TDataType >::CreateOperator(), and IsVertexBound().
IsVertexInterfaceFrozen()
METASOUNDGRAPHCORE_API bool Metasound::FInputVertexInterfaceData::IsVertexInterfaceFrozen () const
Returns true if the vertex interface is frozen.
References UE_API.
RemoveVertex()
METASOUNDGRAPHCORE_API void Metasound::FInputVertexInterfaceData::RemoveVertex (const FVertexName & InVertexName)
Remove a vertex.
VertexInterfaceData must be unfrozen.
References const, InVertexName, RemoveVertex(), and UE_API.
Referenced by RemoveVertex().
SetDefaultLiteral()
METASOUNDGRAPHCORE_API void Metasound::FInputVertexInterfaceData::SetDefaultLiteral (const FVertexName & InVertexName, const FLiteral & InLiteral)
Set the default literal used to create default values.
References const, InVertexName, SetDefaultLiteral(), and UE_API.
Referenced by SetDefaultLiteral().
SetIsVertexInterfaceFrozen()
METASOUNDGRAPHCORE_API void Metasound::FInputVertexInterfaceData::SetIsVertexInterfaceFrozen (bool bInIsVertexInterfaceFrozen)
Set whether the vertex interface is frozen or not.
If frozen, attempts to access vertices which do not already exist will result in an error.
If not frozen, attempts to bind to a missing vertex will automatically add the missing vertex.
References UE_API.
SetValue()
template<typename DataType> void Metasound::FInputVertexInterfaceData::SetValue (const FVertexName & InVertexName, const DataType & InValue) inline
Set the value of a vertex.
Definition at line 576 of file MetasoundVertexData.h.
References Apply(), Metasound::GetMetasoundDataTypeName(), InVertexName, Metasound::Value, and Vertex.
Referenced by Metasound::TArrayRandomGetOperator< ArrayType >::BindInputs().
SetVertex() [1/2]
METASOUNDGRAPHCORE_API void Metasound::FInputVertexInterfaceData::SetVertex (const FVertexName & InVertexName, const FAnyDataReference & InDataReference)
Sets a vertex to use a data reference, ignoring any existing data bound to the vertex.
References const, InVertexName, SetVertex(), and UE_API.
Referenced by SetVertex(), and SetVertex().
SetVertex() [2/2]
METASOUNDGRAPHCORE_API void Metasound::FInputVertexInterfaceData::SetVertex (const FVertexName & InVertexName, FAnyDataReference && InDataReference)
Sets a vertex to use a data reference, ignoring any existing data bound to the vertex.
References const, InVertexName, SetVertex(), and UE_API.
UE_DEPRECATED() [1/8]
Metasound::FInputVertexInterfaceData::UE_DEPRECATED (5. 6, "Do not use FDataReferenceCollection.") const
Convert vertex data to a data reference collection.
References const, UE_API, and UE_DEPRECATED().
UE_DEPRECATED() [2/8]
Metasound::FInputVertexInterfaceData::UE_DEPRECATED (5. 6, "Do not use FDataReferenceCollection.") const &
Set a data references to vertices with matching vertex names.
Ignores any existing data bound to the vertex.
References const, UE_API, and UE_DEPRECATED().
UE_DEPRECATED() [3/8]
template<typename DataType, typename ... ConstructorArgTypes> Metasound::FInputVertexInterfaceData::UE_DEPRECATED (5. 6, "Please GetOrCreateDefaultDataReadReference instead.") const &
Get the bound data read reference if it exists.
Otherwise create and return a data read reference by constructing one the supplied constructor arguments.
UE_DEPRECATED() [4/8]
template<typename DataType, typename ... ConstructorArgTypes> Metasound::FInputVertexInterfaceData::UE_DEPRECATED (5. 6, "Please GetOrCreateDefaultDataWriteReference instead.") const &
Get the bound data write reference if it exists.
Otherwise create and return a data write reference by constructing one the supplied constructor arguments.
References const, Metasound::TDataWriteReference< DataType >::CreateNew(), Find, Forward(), InVertexName, TEXT, UE_LOG, and Warning.
UE_DEPRECATED() [5/8]
Metasound::FInputVertexInterfaceData::UE_DEPRECATED (5. 6, "Please use a non-const lvalue reference for data references passed to this function. Const data references can sometimes be created by passing in temporary objects and/or triggering implicit conversion.") const &
Bind vertex data using other vertex data.
References FInputVertexInterfaceData(), Bind(), const, and UE_API.
UE_DEPRECATED() [6/8]
Metasound::FInputVertexInterfaceData::UE_DEPRECATED (5. 6, "Please use a non-const lvalue reference for data references passed to this function. Const data references can sometimes be created by passing in temporary objects and/or triggering implicit conversion.") const &
Bind a vertex with a any data reference.
UE_DEPRECATED() [7/8]
template<typename DataType> Metasound::FInputVertexInterfaceData::UE_DEPRECATED (5. 6, "Please use a non-const lvalue reference for data references passed to this function. Const data references can sometimes be created by passing in temporary objects and/or triggering implicit conversion.") const &
Bind a read vertex from a read reference.
Referenced by UE_DEPRECATED(), and UE_DEPRECATED().
UE_DEPRECATED() [8/8]
template<typename DataType> Metasound::FInputVertexInterfaceData::UE_DEPRECATED (5. 6, "Please use a non-const lvalue reference for data references passed to this function. Const data references can sometimes be created by passing in temporary objects and/or triggering implicit conversion.") const &
Bind a write vertex from a write reference.
UE_EXPERIMENTAL() [1/10]
Metasound::FInputVertexInterfaceData::UE_EXPERIMENTAL (5. 6, "Sub interfaces are still under development") const &
Find data references bound to the sub interface vertices.
If there is no bound data for a sub interface instance, the array element will be a nullptr.
Parameters
InSubInterfaceName - Name of the sub interface
InVertexName - Name of the prototype vertex in the sub interface.
UE_EXPERIMENTAL() [2/10]
Metasound::FInputVertexInterfaceData::UE_EXPERIMENTAL (5. 6, "Sub interfaces are still under development") const &
Return the number of instances of a particular sub interface.
References const, and UE_API.
Referenced by UE_EXPERIMENTAL().
UE_EXPERIMENTAL() [3/10]
template<typename DataReferenceType> Metasound::FInputVertexInterfaceData::UE_EXPERIMENTAL (5. 6, "Sub interfaces are still under development") const &
Get or create an array of data references for all instances of a sub interface vertex.
Parameters
InSubInterfaceName - Name of the sub interface
InVertexName - Name of the prototype vertex in the sub interface.
InSettings - Operator settings to use if creating a data reference.
UE_EXPERIMENTAL() [4/10]
template<typename DataType> Metasound::FInputVertexInterfaceData::UE_EXPERIMENTAL (5. 6, "Sub interfaces are still under development") const &
Get or create an array of values for all instances of a sub interface vertex.
Parameters
InSubInterfaceName - Name of the sub interface
InVertexName - Name of the prototype vertex in the sub interface.
InSettings - Operator settings to use if creating a data reference.
References const, and InVertexName.
UE_EXPERIMENTAL() [5/10]
template<typename DataType> Metasound::FInputVertexInterfaceData::UE_EXPERIMENTAL (5. 6, "Sub interfaces are still under development") const &
Get or create an array of data read references for all instances of a sub interface vertex.
Parameters
InSubInterfaceName - Name of the sub interface
InVertexName - Name of the prototype vertex in the sub interface.
InSettings - Operator settings to use if creating a data reference.
References const, and InVertexName.
UE_EXPERIMENTAL() [6/10]
template<typename DataType> Metasound::FInputVertexInterfaceData::UE_EXPERIMENTAL (5. 6, "Sub interfaces are still under development") const &
Get or create an array of data write references for all instances of a sub interface vertex.
Parameters
InSubInterfaceName - Name of the sub interface
InVertexName - Name of the prototype vertex in the sub interface.
InSettings - Operator settings to use if creating a data reference.
References const, and InVertexName.
UE_EXPERIMENTAL() [7/10]
template<typename RangeType> Metasound::FInputVertexInterfaceData::UE_EXPERIMENTAL (5. 6, "Sub interfaces are still under development") const &
Bind the vertices of a sub interface vertex as read references.
Parameters
InSubInterfaceName - Name of sub interface.
InVertexName - Name of prototype vertex on sub interface.
InOutDataReferences - An indexable sequence container of data references.
References const, InOutDataReferences, and InVertexName.
UE_EXPERIMENTAL() [8/10]
template<typename RangeType> Metasound::FInputVertexInterfaceData::UE_EXPERIMENTAL (5. 6, "Sub interfaces are still under development") const &
Bind the vertices of a sub interface vertex.
Parameters
InSubInterfaceName - Name of sub interface.
InVertexName - Name of prototype vertex on sub interface.
InOutDataReferences - An indexable sequence container of data references.
References UE_EXPERIMENTAL().
UE_EXPERIMENTAL() [9/10]
template<typename RangeType> Metasound::FInputVertexInterfaceData::UE_EXPERIMENTAL (5. 6, "Sub interfaces are still under development") const &
Bind the vertices of a sub interface vertex as write references.
Parameters
InSubInterfaceName - Name of sub interface.
InVertexName - Name of prototype vertex on sub interface.
InOutDataReferences - An indexable sequence container of data references.
References const, InOutDataReferences, and InVertexName.
UE_EXPERIMENTAL() [10/10]
template<typename RangeType> Metasound::FInputVertexInterfaceData::UE_EXPERIMENTAL (5. 6, "Sub interfaces are still under development") const &
Bind the vertices of a sub interface vertex as value references.
Parameters
InSubInterfaceName - Name of sub interface.
InVertexName - Name of prototype vertex on sub interface.
InOutDataReferences - An indexable sequence container of data references.
Friends And Related Symbol Documentation
CompareVertexInterfaceDataToPriorState
METASOUNDGRAPHCORE_API void CompareVertexInterfaceDataToPriorState (const FInputVertexInterfaceData & InCurrentInterface, const TArray< FVertexDataState > & InPriorState, TSortedVertexNameMap< FAnyDataReference > & OutUpdates) friend
Compares the current data bound to the vertex interface with a prior cached state.
References FInputVertexInterfaceData(), CompareVertexInterfaceDataToPriorState, and const.
Referenced by CompareVertexInterfaceDataToPriorState.
GetVertexInterfaceDataState
METASOUNDGRAPHCORE_API void GetVertexInterfaceDataState (const FInputVertexInterfaceData & InVertexInterface, TArray< FVertexDataState > & OutState) friend
Caches a representation of the current data references bound to the vertex interface.
References FInputVertexInterfaceData(), const, and GetVertexInterfaceDataState.
Referenced by GetVertexInterfaceDataState.
Field Documentation
Bindings
TArray<FInputBinding> Metasound::FInputVertexInterfaceData::Bindings private
Definition at line 996 of file MetasoundVertexData.h.
Referenced by begin(), begin(), end(), and end().
bIsVertexInterfaceFrozen
bool Metasound::FInputVertexInterfaceData::bIsVertexInterfaceFrozen = false private
Definition at line 995 of file MetasoundVertexData.h.
const [1/3]
const FVertexName const FOperatorSettings &InSettings Metasound::FInputVertexInterfaceData::const
Initial value:
{
            if (const FInputBinding* Binding = Find(InVertexName))
            {
                return Binding->GetOrConstructAs<TDataReadReference<DataType>>(Forward<ConstructorArgTypes>(ConstructorArgs)...);
            }
            else
            {
                UE_LOG(LogMetaSound, Warning, TEXT("Failed find vertex with name '%s'. Cannot check for existing bound data."), *InVertexName.ToString());
            }
            return TDataReadReference<DataType>::CreateNew(Forward<ConstructorArgTypes>(ConstructorArgs)...)
Definition at line 851 of file MetasoundVertexData.h.
Referenced by AddVertex(), Apply(), AreAllVerticesBound(), BindVertex(), CompareVertexInterfaceDataToPriorState, Find(), Find(), FindChecked(), FindChecked(), FindSubInterface(), ForEachSubInterfaceBinding(), ForEachSubInterfaceBinding(), GetVertex(), GetVertexDataAccessType(), GetVertexInterfaceDataState, IsVertexBound(), RemoveVertex(), SetDefaultLiteral(), SetVertex(), SetVertex(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_EXPERIMENTAL(), UE_EXPERIMENTAL(), UE_EXPERIMENTAL(), UE_EXPERIMENTAL(), UE_EXPERIMENTAL(), and UE_EXPERIMENTAL().
const [2/3]
const FVertexName const FOperatorSettings& InSettings Metasound::FInputVertexInterfaceData::const
Initial value:
{
            TArray<DataReferenceType> References
Definition at line 920 of file MetasoundVertexData.h.
const [3/3]
const FVertexName& InVertexName Metasound::FInputVertexInterfaceData::const
Definition at line 977 of file MetasoundVertexData.h.
GetOrCreateDefault
auto Metasound::FInputVertexInterfaceData::GetOrCreateDefault
Initial value:
= [&References, &InSettings](uint32 InIndex, const FInputBinding& InBinding)
            {
                check(References.Num() == InIndex);
                References.Add(InBinding.GetOrCreateDefaultAs<DataReferenceType>(InSettings));
            }
Definition at line 923 of file MetasoundVertexData.h.
Referenced by ForEachSubInterfaceBinding().
InOutDataReference [1/3]
const TDataReadReference<DataType>& Metasound::FInputVertexInterfaceData::InOutDataReference
Initial value:
{
            BindReadVertex(InVertexName, const_cast<TDataReadReference<DataType>&>(InOutDataReference))
Definition at line 592 of file MetasoundVertexData.h.
Referenced by BindReadVertex(), BindReadVertex(), BindVertex(), BindVertex(), and BindWriteVertex().
InOutDataReference [2/3]
const TDataWriteReference<DataType>& Metasound::FInputVertexInterfaceData::InOutDataReference
Initial value:
{
            BindWriteVertex(InVertexName, const_cast<TDataWriteReference<DataType>&>(InOutDataReference))
Definition at line 620 of file MetasoundVertexData.h.
InOutDataReference [3/3]
const FAnyDataReference& Metasound::FInputVertexInterfaceData::InOutDataReference
Definition at line 636 of file MetasoundVertexData.h.
InOutDataReferences
const FName RangeType & Metasound::FInputVertexInterfaceData::InOutDataReferences
Initial value:
{
            auto BindData = [&InOutDataReferences](uint32 Index, FInputBinding& Binding)
            {
                Binding.Bind(InOutDataReferences[Index]);
            }
Definition at line 661 of file MetasoundVertexData.h.
Referenced by ForEachSubInterfaceBinding(), UE_EXPERIMENTAL(), and UE_EXPERIMENTAL().
InValues
const FName const RangeType& Metasound::FInputVertexInterfaceData::InValues
Initial value:
{
            auto BindData = [&InValues](uint32 Index, FInputBinding& Binding)
            {
                Binding.SetValue<TElementType_T<RangeType>>(InValues[Index]);
            }
Definition at line 709 of file MetasoundVertexData.h.
Referenced by ForEachSubInterfaceBinding().
InVertexName [1/2]
const FVertexName & Metasound::FInputVertexInterfaceData::InVertexName
Definition at line 661 of file MetasoundVertexData.h.
Referenced by Apply(), BindReadVertex(), BindReadVertex(), BindVertex(), BindVertex(), BindWriteVertex(), Contains(), Find(), Find(), FindChecked(), FindChecked(), FindDataReference(), ForEachSubInterfaceBinding(), ForEachSubInterfaceBinding(), ForEachSubInterfaceBinding(), ForEachSubInterfaceBinding(), ForEachSubInterfaceBinding(), GetDataReadReference(), GetDataWriteReference(), GetOrCreateDefaultDataReadReference(), GetOrCreateDefaultDataValueReference(), GetOrCreateDefaultDataWriteReference(), GetOrCreateDefaultValue(), GetValue(), GetVertex(), GetVertexDataAccessType(), IsVertexBound(), RemoveVertex(), SetDefaultLiteral(), SetValue(), SetVertex(), SetVertex(), UE_DEPRECATED(), UE_EXPERIMENTAL(), UE_EXPERIMENTAL(), UE_EXPERIMENTAL(), UE_EXPERIMENTAL(), and UE_EXPERIMENTAL().
InVertexName [2/2]
const FVertexName& Metasound::FInputVertexInterfaceData::InVertexName
Definition at line 920 of file MetasoundVertexData.h.
References
return Metasound::FInputVertexInterfaceData::References
Definition at line 930 of file MetasoundVertexData.h.
SubInterfaces
TArray<VertexPrivate::FSubInterfaceLayout> Metasound::FInputVertexInterfaceData::SubInterfaces private
Definition at line 997 of file MetasoundVertexData.h.
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/Metasound/Source/MetasoundGraphCore/Public/MetasoundVertexData.h