Unreal Engine 5.6 C++ API: TSetElementBase< InElementType, true > Class Template Reference
TSetElementBase< InElementType, true > Class Template Reference
#include "Set.h"
Public Types
typedef InElementType ElementType
Public Member Functions
TSetElementBase ()=default
TSetElementBase (const TSetElementBase &)=default
template<typename InitType UE_REQUIRES>
FORCEINLINE TSetElementBase (InitType &&InValue)
Initialization constructor.
TSetElementBase (TSetElementBase &&)=default
LAYOUT_FIELD (ElementType, Value)
The element's value.
LAYOUT_MUTABLE_FIELD (FSetElementId, HashNextId)
The id of the next element in the same hash bucket.
LAYOUT_MUTABLE_FIELD (int32, HashIndex)
The hash bucket that the element is currently linked to.
TSetElementBase & operator= (const TSetElementBase &)=default
TSetElementBase & operator= (TSetElementBase &&)=default
Data Fields
int32 HashIndex
The hash bucket that the element is currently linked to.
FSetElementId HashNextId
The id of the next element in the same hash bucket.
ElementType Value
The element's value.
Private Member Functions
DECLARE_INLINE_TYPE_LAYOUT (TSetElementBase, NonVirtual)
Detailed Description
template<typename InElementType>
class TSetElementBase< InElementType, true >
Definition at line 60 of file Set.h.
Member Typedef Documentation
ElementType
template<typename InElementType> typedef InElementType TSetElementBase< InElementType, true >::ElementType
Definition at line 64 of file Set.h.
Constructor & Destructor Documentation
TSetElementBase() [1/4]
template<typename InElementType> TSetElementBase< InElementType, true >::TSetElementBase () nodiscard default
References TSetElementBase().
Referenced by TSetElementBase(), TSetElementBase(), TSetElementBase(), DECLARE_INLINE_TYPE_LAYOUT(), operator=(), and operator=().
TSetElementBase() [2/4]
template<typename InElementType> template<typename InitType UE_REQUIRES> FORCEINLINE TSetElementBase< InElementType, true >::TSetElementBase (InitType && InValue) inline explicit nodiscard
Initialization constructor.
Definition at line 73 of file Set.h.
References FORCEINLINE, Forward(), and Value.
TSetElementBase() [3/4]
template<typename InElementType> TSetElementBase< InElementType, true >::TSetElementBase (TSetElementBase< InElementType, true > &&) nodiscard default
References TSetElementBase().
TSetElementBase() [4/4]
template<typename InElementType> TSetElementBase< InElementType, true >::TSetElementBase (const TSetElementBase< InElementType, true > &) nodiscard default
References TSetElementBase().
Member Function Documentation
DECLARE_INLINE_TYPE_LAYOUT()
template<typename InElementType> TSetElementBase< InElementType, true >::DECLARE_INLINE_TYPE_LAYOUT (TSetElementBase< InElementType, true > , NonVirtual) private
References TSetElementBase().
LAYOUT_FIELD()
template<typename InElementType> TSetElementBase< InElementType, true >::LAYOUT_FIELD (ElementType , Value)
The element's value.
References Value.
LAYOUT_MUTABLE_FIELD() [1/2]
template<typename InElementType> TSetElementBase< InElementType, true >::LAYOUT_MUTABLE_FIELD (FSetElementId , HashNextId)
The id of the next element in the same hash bucket.
References HashNextId.
LAYOUT_MUTABLE_FIELD() [2/2]
template<typename InElementType> TSetElementBase< InElementType, true >::LAYOUT_MUTABLE_FIELD (int32 , HashIndex)
The hash bucket that the element is currently linked to.
References HashIndex.
operator=() [1/2]
template<typename InElementType> TSetElementBase & TSetElementBase< InElementType, true >::operator= (const TSetElementBase< InElementType, true > &) default
References TSetElementBase().
operator=() [2/2]
template<typename InElementType> TSetElementBase & TSetElementBase< InElementType, true >::operator= (TSetElementBase< InElementType, true > &&) default
References TSetElementBase().
Field Documentation
HashIndex
int32 TSetElementBase< InElementType, bTypeLayout >::HashIndex mutable
The hash bucket that the element is currently linked to.
Definition at line 56 of file Set.h.
Referenced by LAYOUT_MUTABLE_FIELD().
HashNextId
FSetElementId TSetElementBase< InElementType, bTypeLayout >::HashNextId mutable
The id of the next element in the same hash bucket.
Definition at line 53 of file Set.h.
Referenced by LAYOUT_MUTABLE_FIELD().
Value
ElementType TSetElementBase< InElementType, bTypeLayout >::Value
The element's value.
Definition at line 50 of file Set.h.
Referenced by TSetElementBase(), and LAYOUT_FIELD().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Containers/Set.h