Unreal Engine 5.6 C++ API: TAllocRecordingLog< FModifier, FAllocOp > Class Template Reference
TAllocRecordingLog< FModifier, FAllocOp > Class Template Reference
#include "AllocLogRecordingPlayback.h"
Public Member Functions
template<typename... ArgTypes>
TAllocRecordingLog (const FString &Filename, ArgTypes &&... Args)
template<typename... ArgTypes>
int64 RecordAlloc (ArgTypes &&... Args)
void RecordFree (int64 AllocIndex)
Protected Member Functions
void WriteLineBuffer (int32 NumCharacters)
Protected Attributes
FCriticalSection CS
int64 CurrentAllocationIndex
ANSICHAR LineBuffer [MAX_SPRINTF]
TSharedPtr< FArchive > OutputFile
Detailed Description
template<typename FModifier, typename FAllocOp>
class TAllocRecordingLog< FModifier, FAllocOp >
Definition at line 78 of file AllocLogRecordingPlayback.h.
Constructor & Destructor Documentation
TAllocRecordingLog()
template<typename FModifier, typename FAllocOp> template<typename... ArgTypes> TAllocRecordingLog< FModifier, FAllocOp >::TAllocRecordingLog (const FString & Filename, ArgTypes &&... Args) inline
Definition at line 101 of file AllocLogRecordingPlayback.h.
References CurrentAllocationIndex, Filename, Forward(), IFileManager::Get(), LineBuffer, MakeShareable(), OutputFile, TEXT, and WriteLineBuffer().
Member Function Documentation
RecordAlloc()
template<typename FModifier, typename FAllocOp> template<typename... ArgTypes> int64 TAllocRecordingLog< FModifier, FAllocOp >::RecordAlloc (ArgTypes &&... Args) inline
Definition at line 115 of file AllocLogRecordingPlayback.h.
References CS, CurrentAllocationIndex, Forward(), GFrameNumberRenderThread, INDEX_NONE, LineBuffer, and WriteLineBuffer().
RecordFree()
template<typename FModifier, typename FAllocOp> void TAllocRecordingLog< FModifier, FAllocOp >::RecordFree (int64 AllocIndex) inline
Definition at line 130 of file AllocLogRecordingPlayback.h.
References CS, GFrameNumberRenderThread, INDEX_NONE, LineBuffer, and WriteLineBuffer().
WriteLineBuffer()
template<typename FModifier, typename FAllocOp> void TAllocRecordingLog< FModifier, FAllocOp >::WriteLineBuffer (int32 NumCharacters) inline protected
Definition at line 85 of file AllocLogRecordingPlayback.h.
References LineBuffer, MAX_SPRINTF, and OutputFile.
Referenced by TAllocRecordingLog(), RecordAlloc(), and RecordFree().
Field Documentation
CS
template<typename FModifier, typename FAllocOp> FCriticalSection TAllocRecordingLog< FModifier, FAllocOp >::CS protected
Definition at line 94 of file AllocLogRecordingPlayback.h.
Referenced by RecordAlloc(), and RecordFree().
CurrentAllocationIndex
template<typename FModifier, typename FAllocOp> int64 TAllocRecordingLog< FModifier, FAllocOp >::CurrentAllocationIndex protected
Definition at line 93 of file AllocLogRecordingPlayback.h.
Referenced by TAllocRecordingLog(), and RecordAlloc().
LineBuffer
template<typename FModifier, typename FAllocOp> ANSICHAR TAllocRecordingLog< FModifier, FAllocOp >::LineBuffer[MAX_SPRINTF] protected
Definition at line 97 of file AllocLogRecordingPlayback.h.
Referenced by TAllocRecordingLog(), RecordAlloc(), RecordFree(), and WriteLineBuffer().
OutputFile
template<typename FModifier, typename FAllocOp> TSharedPtr<FArchive> TAllocRecordingLog< FModifier, FAllocOp >::OutputFile protected
Definition at line 95 of file AllocLogRecordingPlayback.h.
Referenced by TAllocRecordingLog(), and WriteLineBuffer().
The documentation for this class was generated from the following file:
Runtime/Core/Public/ProfilingDebugging/AllocLogRecordingPlayback.h