Unreal Engine 5.6 C++ API: Metasound::TExecutableOperator< DerivedOperatorType > Class Template Reference
Metasound::TExecutableOperator< DerivedOperatorType > Class Template Reference
Convenience class for supporting the IOperator interface's GetExecuteFunction virtual member function.
#include "MetasoundExecutableOperator.h"
Public Member Functions
virtual ~TExecutableOperator ()
virtual FExecuteFunction GetExecuteFunction () override
Return the execution function to call during graph execution.
virtual FPostExecuteFunction GetPostExecuteFunction () override
Return the FPostExecute function to call during graph post execution.
virtual FResetFunction GetResetFunction () override
Return the reset function to call during graph execution.
Public Member Functions inherited from Metasound::IOperator
virtual ~IOperator ()
virtual void METASOUNDGRAPHCORE_API BindInputs (FInputVertexInterfaceData &InVertexData)
BindInputs binds data references in the IOperator with the FInputVertexInterfaceData.
virtual void METASOUNDGRAPHCORE_API BindOutputs (FOutputVertexInterfaceData &InVertexData)
BindOutputs binds data references in the IOperator with the FOutputVertexInterfaceData.
UE_DEPRECATED (5.3, "Bind(FVertexInterfaceData&) has been replaced by BindInputs(FInputVertexInterfaceDAta&) and BindOutputs(FOutputVertexInterfaceData&)") virtual void METASOUNDGRAPHCORE_API Bind(FVertexInterfaceData &InVertexData) const
Bind(...) has been deprecated in favor of BindInputs(...) and BindOutputs(...).
UE_DEPRECATED (5.3, "GetInputs() has been replaced by BindInputs(FInputVertexInterfaceData&).") virtual FDataReferenceCollection METASOUNDGRAPHCORE_API GetInputs() const
GetInputs() has been deprecated in favor of BindInputs(...).
UE_DEPRECATED (5.3, "GetOutputs() has been replaced by BindOutputs(FOutputVertexInterfaceData&)") virtual FDataReferenceCollection METASOUNDGRAPHCORE_API GetOutputs() const
GetOutputs() has been deprecated in favor of BindOutputs(...).
Static Private Member Functions
static void ExecuteFunction (IOperator *InOperator)
Additional Inherited Members
Public Types inherited from Metasound::IOperator
using FExecuteFunction = void(*)(IOperator*)
Pointer to execute function for an operator.
using FPostExecuteFunction = void(*)(IOperator*)
Pointer to post execute function for an operator.
using FResetFunction = void(*)(IOperator*, const FResetParams& InParams)
Pointer to initialize function for an operator.
Detailed Description
template<class DerivedOperatorType>
class Metasound::TExecutableOperator< DerivedOperatorType >
Convenience class for supporting the IOperator interface's GetExecuteFunction virtual member function.
Derived classes should inherit from this template class as well as implement a void Execute() member function.
class MyOperator : public TExecutableOperator<MyOperator>
{
  public:
  ...
  void Execute()
  {
  ...
  }
};
Definition at line 186 of file MetasoundExecutableOperator.h.
Constructor & Destructor Documentation
~TExecutableOperator()
template<class DerivedOperatorType> virtual Metasound::TExecutableOperator< DerivedOperatorType >::~TExecutableOperator () inline virtual
Definition at line 190 of file MetasoundExecutableOperator.h.
Member Function Documentation
ExecuteFunction()
template<class DerivedOperatorType> void Metasound::TExecutableOperator< DerivedOperatorType >::ExecuteFunction (IOperator * InOperator) inline static private
Definition at line 209 of file MetasoundExecutableOperator.h.
References check.
Referenced by GetExecuteFunction().
GetExecuteFunction()
template<class DerivedOperatorType> virtual FExecuteFunction Metasound::TExecutableOperator< DerivedOperatorType >::GetExecuteFunction () inline override virtual
Return the execution function to call during graph execution.
The IOperator* argument to the FExecutionFunction will be the same IOperator instance which returned the execution function.
nullptr return values are valid and signal an IOperator which does not need to be executed.
Implements Metasound::IOperator.
Definition at line 197 of file MetasoundExecutableOperator.h.
References ExecuteFunction().
GetPostExecuteFunction()
template<class DerivedOperatorType> virtual FPostExecuteFunction Metasound::TExecutableOperator< DerivedOperatorType >::GetPostExecuteFunction () inline override virtual
Return the FPostExecute function to call during graph post execution.
The IOperator* argument to the FPostExecutionFunction will be the same IOperator instance which returned the execution function.
nullptr return values are valid and signal an IOperator which does not need to be post executed.
Implements Metasound::IOperator.
Reimplemented in Metasound::FGraphOperator.
Definition at line 202 of file MetasoundExecutableOperator.h.
References Metasound::MetasoundExecutableOperatorPrivate::TPostExecuteFunctionAdapter< OperatorType >::GetPostExecuteFunction().
GetResetFunction()
template<class DerivedOperatorType> virtual FResetFunction Metasound::TExecutableOperator< DerivedOperatorType >::GetResetFunction () inline override virtual
Return the reset function to call during graph execution.
The IOperator* argument to the FExecutionFunction will be the same IOperator instance which returned the execution function.
nullptr return values are valid and signal an IOperator which does not need to be reset.
Implements Metasound::IOperator.
Definition at line 192 of file MetasoundExecutableOperator.h.
References Metasound::MetasoundExecutableOperatorPrivate::TResetFunctionAdapter< OperatorType >::GetResetFunction().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/Metasound/Source/MetasoundGraphCore/Public/MetasoundExecutableOperator.h