Unreal Engine 5.6 C++ API: FDataLayerInstanceDesc Class Reference
FDataLayerInstanceDesc Class Reference
#include "WorldDataLayersActorDesc.h"
Public Member Functions
FDataLayerInstanceDesc ()
FName GetAssetPath () const
EDataLayerType GetDataLayerType () const
FName GetName () const
FName GetParentName () const
FString GetShortName () const
void Init (class UDataLayerInstance *DataLayerInstance)
bool IsIncludedInActorFilterDefault () const
bool IsUsingAsset () const
bool SupportsActorFilters () const
Private Member Functions
class UDataLayerAsset * GetAsset () const
Private Attributes
FName AssetPath
bool bDeprecatedIsRuntime
bool bIsIncludedInActorFilterDefault
bool bIsPrivate
bool bIsUsingAsset
bool bPrivateDataLayerSupportsActorFilter
FName Name
FName ParentName
FString PrivateShortName
Friends
bool operator< (const FDataLayerInstanceDesc &Lhs, const FDataLayerInstanceDesc &Rhs)
FArchive & operator<< (FArchive &Ar, FDataLayerInstanceDesc &DataLayerInstanceDesc)
bool operator== (const FDataLayerInstanceDesc &Lhs, const FDataLayerInstanceDesc &Rhs)
class UDataLayerInstance
Detailed Description
Definition at line 11 of file WorldDataLayersActorDesc.h.
Constructor & Destructor Documentation
FDataLayerInstanceDesc()
FDataLayerInstanceDesc::FDataLayerInstanceDesc ()
Referenced by operator<, operator<<, and operator==.
Member Function Documentation
GetAsset()
class UDataLayerAsset * FDataLayerInstanceDesc::GetAsset () const private
GetAssetPath()
FName FDataLayerInstanceDesc::GetAssetPath () const inline
Definition at line 23 of file WorldDataLayersActorDesc.h.
References AssetPath.
GetDataLayerType()
EDataLayerType FDataLayerInstanceDesc::GetDataLayerType () const
GetName()
FName FDataLayerInstanceDesc::GetName () const inline
Definition at line 20 of file WorldDataLayersActorDesc.h.
References Name.
GetParentName()
FName FDataLayerInstanceDesc::GetParentName () const inline
Definition at line 21 of file WorldDataLayersActorDesc.h.
References ParentName.
GetShortName()
FString FDataLayerInstanceDesc::GetShortName () const
Init()
void FDataLayerInstanceDesc::Init (class UDataLayerInstance * DataLayerInstance)
References UDataLayerInstance.
IsIncludedInActorFilterDefault()
bool FDataLayerInstanceDesc::IsIncludedInActorFilterDefault () const inline
Definition at line 26 of file WorldDataLayersActorDesc.h.
References bIsIncludedInActorFilterDefault.
IsUsingAsset()
bool FDataLayerInstanceDesc::IsUsingAsset () const inline
Definition at line 22 of file WorldDataLayersActorDesc.h.
References bIsUsingAsset.
SupportsActorFilters()
bool FDataLayerInstanceDesc::SupportsActorFilters () const
Friends And Related Symbol Documentation
operator<
bool operator< (const FDataLayerInstanceDesc & Lhs, const FDataLayerInstanceDesc & Rhs) friend
References FDataLayerInstanceDesc().
operator<<
FArchive & operator<< (FArchive & Ar, FDataLayerInstanceDesc & DataLayerInstanceDesc) friend
References FDataLayerInstanceDesc(), and Ar.
operator==
bool operator== (const FDataLayerInstanceDesc & Lhs, const FDataLayerInstanceDesc & Rhs) friend
References FDataLayerInstanceDesc().
UDataLayerInstance
friend class UDataLayerInstance friend
Definition at line 57 of file WorldDataLayersActorDesc.h.
References UDataLayerInstance.
Referenced by Init(), and UDataLayerInstance.
Field Documentation
AssetPath
FName FDataLayerInstanceDesc::AssetPath private
Definition at line 41 of file WorldDataLayersActorDesc.h.
Referenced by GetAssetPath().
bDeprecatedIsRuntime
bool FDataLayerInstanceDesc::bDeprecatedIsRuntime private
Definition at line 54 of file WorldDataLayersActorDesc.h.
bIsIncludedInActorFilterDefault
bool FDataLayerInstanceDesc::bIsIncludedInActorFilterDefault private
Definition at line 43 of file WorldDataLayersActorDesc.h.
Referenced by IsIncludedInActorFilterDefault().
bIsPrivate
bool FDataLayerInstanceDesc::bIsPrivate private
Definition at line 45 of file WorldDataLayersActorDesc.h.
bIsUsingAsset
bool FDataLayerInstanceDesc::bIsUsingAsset private
Definition at line 37 of file WorldDataLayersActorDesc.h.
Referenced by IsUsingAsset().
bPrivateDataLayerSupportsActorFilter
bool FDataLayerInstanceDesc::bPrivateDataLayerSupportsActorFilter private
Definition at line 49 of file WorldDataLayersActorDesc.h.
Name
FName FDataLayerInstanceDesc::Name private
Definition at line 33 of file WorldDataLayersActorDesc.h.
Referenced by GetName().
ParentName
FName FDataLayerInstanceDesc::ParentName private
Definition at line 35 of file WorldDataLayersActorDesc.h.
Referenced by GetParentName().
PrivateShortName
FString FDataLayerInstanceDesc::PrivateShortName private
Definition at line 51 of file WorldDataLayersActorDesc.h.
The documentation for this class was generated from the following file:
Runtime/Engine/Public/WorldPartition/DataLayer/WorldDataLayersActorDesc.h