Unreal Engine 5.6 C++ API: FRedirectionSummary Class Reference
FRedirectionSummary Class Reference
Container for FCoreRedirects that can affect a package.
#include "RedirectionSummary.h"
Data Structures
struct FCompareRedirect
struct FRedirectContainer
Public Member Functions
FRedirectionSummary ()=default
FRedirectionSummary (FRedirectionSummary &&Other)
void Add (const FCoreRedirect &CoreRedirect, bool bIsWildcardMatch)
void AppendHashGlobal (FBlake3 &Hasher)
void GetHashAffectingPackages (const TConstArrayView< FName > &PackageNames, TArray< FBlake3Hash > &HashArray)
FRedirectionSummary & operator= (FRedirectionSummary &&Other)
void Remove (const FCoreRedirect &CoreRedirect, bool bIsWildcardMatch)
UE_DEPRECATED (5.6, "Use GetHashAffectingPackages instead.") void AppendHashAffectingPackages(FBlake3 &Hasher
Data Fields
TConstArrayView< FName > PackageNames
Static Private Member Functions
static TArray< FName, TInlineAllocator< 2 > > GetAffectedPackages (const FCoreRedirect &Redirect)
Private Attributes
FRedirectContainer GlobalRedirects
FRWLock Lock
CoreRedirects are written when the engine is single threaded, but we do not write the hashes for the global and per-package containers until they are requested on demand.
TMap< FName, FRedirectContainer > RedirectsForPackage
Detailed Description
Container for FCoreRedirects that can affect a package.
Used by class FCoreRedirects to implement AppendHashOfRedirectsAffectingPackages.
Definition at line 20 of file RedirectionSummary.h.
Constructor & Destructor Documentation
FRedirectionSummary() [1/2]
FRedirectionSummary::FRedirectionSummary () default
Referenced by FRedirectionSummary(), and operator=().
FRedirectionSummary() [2/2]
FRedirectionSummary::FRedirectionSummary (FRedirectionSummary && Other)
References FRedirectionSummary(), and Other.
Member Function Documentation
Add()
void FRedirectionSummary::Add (const FCoreRedirect & CoreRedirect, bool bIsWildcardMatch)
AppendHashGlobal()
void FRedirectionSummary::AppendHashGlobal (FBlake3 & Hasher)
References AppendHashGlobal().
Referenced by AppendHashGlobal().
GetAffectedPackages()
TArray< FName, TInlineAllocator< 2 > > FRedirectionSummary::GetAffectedPackages (const FCoreRedirect & Redirect) static private
GetHashAffectingPackages()
void FRedirectionSummary::GetHashAffectingPackages (const TConstArrayView< FName > & PackageNames, TArray< FBlake3Hash > & HashArray)
References GetHashAffectingPackages(), and PackageNames.
Referenced by GetHashAffectingPackages().
operator=()
FRedirectionSummary & FRedirectionSummary::operator= (FRedirectionSummary && Other)
References FRedirectionSummary(), and Other.
Remove()
void FRedirectionSummary::Remove (const FCoreRedirect & CoreRedirect, bool bIsWildcardMatch)
UE_DEPRECATED()
FRedirectionSummary::UE_DEPRECATED (5. 6, "Use GetHashAffectingPackages instead.") &
Field Documentation
GlobalRedirects
FRedirectContainer FRedirectionSummary::GlobalRedirects private
Definition at line 64 of file RedirectionSummary.h.
Lock
FRWLock FRedirectionSummary::Lock private
CoreRedirects are written when the engine is single threaded, but we do not write the hashes for the global and per-package containers until they are requested on demand.
The requests on demand can occur on multiple threads, so we need a lock to ensure that the first thread that requests them and finds them dirty does not cause a data race with the second thread requests them.
Definition at line 71 of file RedirectionSummary.h.
PackageNames
TConstArrayView<FName> FRedirectionSummary::PackageNames
Definition at line 31 of file RedirectionSummary.h.
Referenced by GetHashAffectingPackages().
RedirectsForPackage
TMap<FName, FRedirectContainer> FRedirectionSummary::RedirectsForPackage private
Definition at line 63 of file RedirectionSummary.h.
The documentation for this class was generated from the following file:
Runtime/CoreUObject/Internal/UObject/CoreRedirects/RedirectionSummary.h