Unreal Engine 5.6 C++ API: FBindingContext Class Reference
FBindingContext Class Reference
Represents a context in which input bindings are valid.
#include "UICommandInfo.h"
Public Member Functions
FBindingContext (const FBindingContext &)=default
FBindingContext (const FName InContextName, const FText &InContextDesc, const FName InContextParent, const FName InStyleSetName)
Constructor.
FBindingContext (FBindingContext &&)=default
void AddBundle (const FName Name, const FText &Desc)
Adds a new command bundle to this context that can be referenced by name from commands within the context.
const FText & GetBundleLabel (const FName Name)
Gets a localized label of a command bundle.
const FText & GetContextDesc () const
FName GetContextName () const
FName GetContextParent () const
FName GetStyleSetName () const
FUICommandInfoDecl NewCommand (const FName InCommandName, const FText &InCommandLabel, const FText &InCommandDesc)
Creates a new command declaration used to populate commands with data.
FBindingContext & operator= (const FBindingContext &)=default
FBindingContext & operator= (FBindingContext &&)=default
bool operator== (const FBindingContext &Other) const
Public Member Functions inherited from TSharedFromThis< FBindingContext >
TSharedRef< FBindingContext, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FBindingContext, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Static Public Attributes
static FOnBindingContextChanged CommandsChanged
A delegate that is called when commands are registered or unregistered with a binding context.
Private Attributes
TMap< FName, FText > Bundles
A list of command bundles and their friendly names that can be referenced in this context.
FText ContextDesc
The description of the context.
FName ContextName
The name of the context.
FName ContextParent
The name of the parent context.
FName StyleSetName
The style set to find the icons in.
Friends
uint32 GetTypeHash (const FBindingContext &Context)
Additional Inherited Members
Protected Member Functions inherited from TSharedFromThis< FBindingContext >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions inherited from TSharedFromThis< FBindingContext >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
Represents a context in which input bindings are valid.
Definition at line 83 of file UICommandInfo.h.
Constructor & Destructor Documentation
FBindingContext() [1/3]
FBindingContext::FBindingContext (const FName InContextName, const FText & InContextDesc, const FName InContextParent, const FName InStyleSetName) inline
Constructor.
Parameters
InContextName The name of the context
InContextDesc The localized description of the context
InContextParent Optional parent context. Bindings are not allowed to be the same between parent and child contexts
InStyleSetName The style set to find the icons in, eg) FCoreStyle::Get().GetStyleSetName()
Definition at line 95 of file UICommandInfo.h.
References check, ContextDesc, ContextName, ContextParent, FName::IsNone(), and StyleSetName.
Referenced by FBindingContext(), FBindingContext(), TCommands< CommandContextType >::TCommands(), TCommands< CommandContextType >::GetContext(), GetTypeHash, operator=(), operator=(), and operator==().
FBindingContext() [2/3]
FBindingContext::FBindingContext (const FBindingContext &) default
References FBindingContext().
FBindingContext() [3/3]
FBindingContext::FBindingContext (FBindingContext &&) default
References FBindingContext().
Member Function Documentation
AddBundle()
void FBindingContext::AddBundle (const FName Name, const FText & Desc)
Adds a new command bundle to this context that can be referenced by name from commands within the context.
Parameters
Name A unique identifier for the bundle in this context
Desc A localized description of the bundle
References Name.
GetBundleLabel()
const FText & FBindingContext::GetBundleLabel (const FName Name)
Gets a localized label of a command bundle.
Parameters
Name The name of the bundle to get a label for
Returns
The localized label of the bundle
References Name.
GetContextDesc()
const FText & FBindingContext::GetContextDesc () const inline
Returns
The localized description of this context
Definition at line 132 of file UICommandInfo.h.
References ContextDesc.
GetContextName()
FName FBindingContext::GetContextName () const inline
Returns
The name of the context
Definition at line 117 of file UICommandInfo.h.
References ContextName.
Referenced by TInteractiveToolCommands< CommandContextType >::RegisterUIToolCommand().
GetContextParent()
FName FBindingContext::GetContextParent () const inline
Returns
The name of the parent context (or NAME_None if there isnt one)
Definition at line 122 of file UICommandInfo.h.
References ContextParent.
GetStyleSetName()
FName FBindingContext::GetStyleSetName () const inline
Returns
The name of the style set to find the icons in
Definition at line 127 of file UICommandInfo.h.
References StyleSetName.
Referenced by FTabCommands::FTabCommands(), and TInteractiveToolCommands< CommandContextType >::RegisterUIToolCommand().
NewCommand()
FUICommandInfoDecl FBindingContext::NewCommand (const FName InCommandName, const FText & InCommandLabel, const FText & InCommandDesc)
Creates a new command declaration used to populate commands with data.
operator=() [1/2]
FBindingContext & FBindingContext::operator= (const FBindingContext &) default
References FBindingContext().
operator=() [2/2]
FBindingContext & FBindingContext::operator= (FBindingContext &&) default
References FBindingContext().
operator==()
bool FBindingContext::operator== (const FBindingContext & Other) const inline
Definition at line 156 of file UICommandInfo.h.
References FBindingContext(), ContextName, and Other.
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FBindingContext & Context) friend
Definition at line 151 of file UICommandInfo.h.
References FBindingContext(), and GetTypeHash.
Referenced by GetTypeHash.
Field Documentation
Bundles
TMap<FName, FText> FBindingContext::Bundles private
A list of command bundles and their friendly names that can be referenced in this context.
Definition at line 179 of file UICommandInfo.h.
CommandsChanged
FOnBindingContextChanged FBindingContext::CommandsChanged static
A delegate that is called when commands are registered or unregistered with a binding context.
Definition at line 162 of file UICommandInfo.h.
Referenced by TCommands< CommandContextType >::Register(), and TCommands< CommandContextType >::Unregister().
ContextDesc
FText FBindingContext::ContextDesc private
The description of the context.
Definition at line 173 of file UICommandInfo.h.
Referenced by FBindingContext(), and GetContextDesc().
ContextName
FName FBindingContext::ContextName private
The name of the context.
Definition at line 167 of file UICommandInfo.h.
Referenced by FBindingContext(), GetContextName(), and operator==().
ContextParent
FName FBindingContext::ContextParent private
The name of the parent context.
Definition at line 170 of file UICommandInfo.h.
Referenced by FBindingContext(), and GetContextParent().
StyleSetName
FName FBindingContext::StyleSetName private
The style set to find the icons in.
Definition at line 176 of file UICommandInfo.h.
Referenced by FBindingContext(), and GetStyleSetName().
The documentation for this class was generated from the following file:
Runtime/Slate/Public/Framework/Commands/UICommandInfo.h