Unreal Engine 5.6 C++ API: FLocalPlayerIterator Class Reference
FLocalPlayerIterator Class Reference
#include "UnrealEngine.h"
Public Member Functions
FLocalPlayerIterator (UEngine *InEngine, class UWorld *InWorld)
operator bool () const
ULocalPlayer * operator* () const
void operator++ ()
ULocalPlayer * operator-> () const
Protected Member Functions
void GetCurrent ()
Protected Attributes
TArray< classULocalPlayer * >::TConstIterator Iter
Detailed Description
Definition at line 35 of file UnrealEngine.h.
Constructor & Destructor Documentation
FLocalPlayerIterator()
FLocalPlayerIterator::FLocalPlayerIterator (UEngine * InEngine, class UWorld * InWorld) inline
Definition at line 48 of file UnrealEngine.h.
References GetCurrent(), and Iter.
Member Function Documentation
GetCurrent()
void FLocalPlayerIterator::GetCurrent () inline protected
Definition at line 40 of file UnrealEngine.h.
References Iter.
Referenced by FLocalPlayerIterator(), and operator++().
operator bool()
FLocalPlayerIterator::operator bool () const inline explicit
Definition at line 67 of file UnrealEngine.h.
References Iter.
operator*()
ULocalPlayer * FLocalPlayerIterator::operator* () const inline
Definition at line 59 of file UnrealEngine.h.
References Iter.
operator++()
void FLocalPlayerIterator::operator++ () inline
Definition at line 54 of file UnrealEngine.h.
References GetCurrent(), and Iter.
operator->()
ULocalPlayer * FLocalPlayerIterator::operator-> () const inline
Definition at line 63 of file UnrealEngine.h.
References Iter.
Field Documentation
Iter
TArray<classULocalPlayer*>::TConstIterator FLocalPlayerIterator::Iter protected
Definition at line 38 of file UnrealEngine.h.
Referenced by FLocalPlayerIterator(), GetCurrent(), operator bool(), operator*(), operator++(), and operator->().
The documentation for this class was generated from the following file:
Runtime/Engine/Public/UnrealEngine.h