Unreal Engine 5.6 C++ API: FChildren Class Reference
FChildren Class Reference abstract
FChildren is an interface that must be implemented by all child containers.
#include "ChildrenBase.h"
Data Structures
struct FConstWidgetRef
struct FWidgetRef
Public Member Functions
FChildren (std::nullptr_t)=delete
FChildren (SWidget *InOwner)
FChildren (SWidget *InOwner, FName InName)
template<typename Predicate>
FORCEINLINE void ForEachWidget (Predicate &&Pred)
Applies the predicate to all the widgets contained by the FChildren.
template<typename Predicate>
FORCEINLINE void ForEachWidget (Predicate &&Pred) const
Applies the predicate to all the widgets contained by the FChildren.
virtual TSharedRef< const SWidget > GetChildAt (int32 Index) const =0
virtual TSharedRef< SWidget > GetChildAt (int32 Index)=0
FName GetName () const
Option to give a name to Children to SlotAttribute purposes or for debugging.
SWidget & GetOwner () const
virtual const FSlotBase & GetSlotAt (int32 ChildIndex) const =0
virtual int32 Num () const =0
virtual int32 NumSlot () const
void * operator new (size_t)=delete
void * operator new[] (size_t)=delete
virtual bool SupportSlotWithSlateAttribute () const
Protected Types
enum ECopyConstruct { CopyConstruct }
enum ERefConstruct { ReferenceConstruct }
Protected Member Functions
virtual ~FChildren ()
void Debug_TestDestroyTag () const
virtual FConstWidgetRef GetChildRefAt (int32 Index) const =0
virtual FWidgetRef GetChildRefAt (int32 Index)=0
Private Attributes
bool Debug_bIsIteratingChildren = false
uint8 Debug_DestroyedTag = 0xDC
FName Name
SWidget * Owner
Friends
class FCombinedChildren
template<typename T>
class TOneDynamicChild
Detailed Description
FChildren is an interface that must be implemented by all child containers.
It allows iteration over a list of any Widget's children regardless of how the underlying Widget happens to store its children.
FChildren is intended to be returned by the GetChildren() method.
Definition at line 26 of file ChildrenBase.h.
Member Enumeration Documentation
ECopyConstruct
enum FChildren::ECopyConstruct protected
Enumerator
CopyConstruct
Definition at line 124 of file ChildrenBase.h.
ERefConstruct
enum FChildren::ERefConstruct protected
Enumerator
ReferenceConstruct
Definition at line 125 of file ChildrenBase.h.
Constructor & Destructor Documentation
FChildren() [1/3]
FChildren::FChildren (SWidget * InOwner) inline
Definition at line 29 of file ChildrenBase.h.
References check, Name, and Owner.
Referenced by FNoChildren::FNoChildren(), FNoChildren::FNoChildren(), TOneDynamicChild< SlotType >::TOneDynamicChild(), TSingleWidgetChildrenWithSlot< TSingleWidgetChildrenWithBasicLayoutSlot< InPaddingInvalidationReason > >::TSingleWidgetChildrenWithSlot(), TSingleWidgetChildrenWithSlot< TSingleWidgetChildrenWithBasicLayoutSlot< InPaddingInvalidationReason > >::TSingleWidgetChildrenWithSlot(), TSlotlessChildren< ChildType >::TSlotlessChildren(), TOneDynamicChild< SlotType >::GetChildRefAt(), and TOneDynamicChild< SlotType >::GetChildRefAt().
FChildren() [2/3]
FChildren::FChildren (SWidget * InOwner, FName InName) inline
Definition at line 35 of file ChildrenBase.h.
References check, InName, Name, and Owner.
FChildren() [3/3]
FChildren::FChildren (std::nullptr_t) delete
~FChildren()
virtual FChildren::~FChildren () inline protected virtual
Definition at line 196 of file ChildrenBase.h.
References Debug_bIsIteratingChildren, Debug_DestroyedTag, Debug_TestDestroyTag(), Fatal, FReflectionMetaData::GetWidgetDebugInfo(), Name, Owner, TEXT, and UE_CLOG.
Member Function Documentation
Debug_TestDestroyTag()
void FChildren::Debug_TestDestroyTag () const inline protected
There is no guarantee that it will work. The memory could have been reused and the new data can luckily matches what we are looking for.
Definition at line 206 of file ChildrenBase.h.
References Debug_DestroyedTag, Fatal, TEXT, and UE_CLOG.
Referenced by ~FChildren(), ForEachWidget(), ForEachWidget(), GetName(), and GetOwner().
ForEachWidget() [1/2]
template<typename Predicate> FORCEINLINE void FChildren::ForEachWidget (Predicate && Pred) inline
Applies the predicate to all the widgets contained by the FChildren.
Definition at line 65 of file ChildrenBase.h.
References Debug_bIsIteratingChildren, Debug_TestDestroyTag(), FORCEINLINE, GetChildRefAt(), FChildren::FWidgetRef::GetWidget(), Num(), and Predicate.
ForEachWidget() [2/2]
template<typename Predicate> FORCEINLINE void FChildren::ForEachWidget (Predicate && Pred) const inline
Applies the predicate to all the widgets contained by the FChildren.
Definition at line 82 of file ChildrenBase.h.
References Debug_bIsIteratingChildren, Debug_TestDestroyTag(), FORCEINLINE, GetChildRefAt(), FChildren::FConstWidgetRef::GetWidget(), Num(), and Predicate.
GetChildAt() [1/2]
virtual TSharedRef< const SWidget > FChildren::GetChildAt (int32 Index) const pure virtual
Returns
const pointer to the Widget at the specified Index.
Implemented in FCombinedChildren, FNoChildren, FScopedWidgetSlotArguments< FNodeSlot >, FScopedWidgetSlotArguments< FPopupLayerSlot >, TOneDynamicChild< SlotType >, TPanelChildren< SlotType >, TPanelChildren< FOverlaySlot >::FScopedWidgetSlotArguments< FOverlaySlot >, TPanelChildren< FSlot >::FScopedWidgetSlotArguments< FSlot >, TSingleWidgetChildrenWithSlot< SlotType >, TSingleWidgetChildrenWithSlot< TSingleWidgetChildrenWithBasicLayoutSlot< InPaddingInvalidationReason > >, TSlotlessChildren< ChildType >, and TWeakChild< ChildType >.
GetChildAt() [2/2]
virtual TSharedRef< SWidget > FChildren::GetChildAt (int32 Index) pure virtual
Returns
pointer to the Widget at the specified Index.
Implemented in FCombinedChildren, FNoChildren, FScopedWidgetSlotArguments< FNodeSlot >, FScopedWidgetSlotArguments< FPopupLayerSlot >, TOneDynamicChild< SlotType >, TOneDynamicChild< FBasicLayoutWidgetSlot >, TPanelChildren< SlotType >, TPanelChildren< FBasicLayoutWidgetSlot >, TPanelChildren< FOverlaySlot >::FScopedWidgetSlotArguments< FOverlaySlot >, TPanelChildren< FOverlaySlot >, TPanelChildren< FSlot >::FScopedWidgetSlotArguments< FSlot >, TPanelChildren< FSlot >, TPanelChildren< SBoxPanel::FSlot >, TPanelChildren< SConstraintCanvas::FSlot >, TPanelChildren< SGridPanel::FSlot >, TPanelChildren< SNodePanel::SNode::FNodeSlot >, TPanelChildren< SRadialBox::FSlot >, TPanelChildren< SScrollBarTrack::FSlot >, TPanelChildren< SScrollBox::FSlot >, TPanelChildren< SSegmentedControl::FSlot >, TPanelChildren< SSplitter2x2::FSlot >, TPanelChildren< SSplitter::FSlot >, TPanelChildren< SUniformGridPanel::FSlot >, TPanelChildren< UE::Sequencer::FTrackAreaSlot >, TPanelChildren< UE::Sequencer::SCompoundTrackLaneView::FSlot >, TPanelChildren< UE::Sequencer::STrackLane::FSlot >, TSingleWidgetChildrenWithSlot< SlotType >, TSingleWidgetChildrenWithSlot< FSingleWidgetChildrenWithSlot >, TSingleWidgetChildrenWithSlot< TSingleWidgetChildrenWithBasicLayoutSlot< EInvalidateWidgetReason::Layout > >, TSingleWidgetChildrenWithSlot< TSingleWidgetChildrenWithBasicLayoutSlot< InPaddingInvalidationReason > >, TSlotlessChildren< ChildType >, TSlotlessChildren< SNodePanel::SNode >, TSlotlessChildren< SWidget >, TWeakChild< ChildType >, and TWeakChild< SWidget >.
GetChildRefAt() [1/2]
virtual FConstWidgetRef FChildren::GetChildRefAt (int32 Index) const protected pure virtual
Returns
ref to the Widget at the specified Index.
Implemented in FCombinedChildren, FNoChildren, FScopedWidgetSlotArguments< FNodeSlot >, FScopedWidgetSlotArguments< FPopupLayerSlot >, TOneDynamicChild< SlotType >, TPanelChildren< SlotType >, TPanelChildren< FOverlaySlot >::FScopedWidgetSlotArguments< FOverlaySlot >, TPanelChildren< FSlot >::FScopedWidgetSlotArguments< FSlot >, TSingleWidgetChildrenWithSlot< SlotType >, TSingleWidgetChildrenWithSlot< TSingleWidgetChildrenWithBasicLayoutSlot< InPaddingInvalidationReason > >, TSlotlessChildren< ChildType >, and TWeakChild< ChildType >.
GetChildRefAt() [2/2]
virtual FWidgetRef FChildren::GetChildRefAt (int32 Index) protected pure virtual
Returns
ref to the Widget at the specified Index.
Implemented in FCombinedChildren, FNoChildren, FScopedWidgetSlotArguments< FNodeSlot >, FScopedWidgetSlotArguments< FPopupLayerSlot >, TOneDynamicChild< SlotType >, TOneDynamicChild< FBasicLayoutWidgetSlot >, TPanelChildren< SlotType >, TPanelChildren< FBasicLayoutWidgetSlot >, TPanelChildren< FOverlaySlot >::FScopedWidgetSlotArguments< FOverlaySlot >, TPanelChildren< FOverlaySlot >, TPanelChildren< FSlot >::FScopedWidgetSlotArguments< FSlot >, TPanelChildren< FSlot >, TPanelChildren< SBoxPanel::FSlot >, TPanelChildren< SConstraintCanvas::FSlot >, TPanelChildren< SGridPanel::FSlot >, TPanelChildren< SNodePanel::SNode::FNodeSlot >, TPanelChildren< SRadialBox::FSlot >, TPanelChildren< SScrollBarTrack::FSlot >, TPanelChildren< SScrollBox::FSlot >, TPanelChildren< SSegmentedControl::FSlot >, TPanelChildren< SSplitter2x2::FSlot >, TPanelChildren< SSplitter::FSlot >, TPanelChildren< SUniformGridPanel::FSlot >, TPanelChildren< UE::Sequencer::FTrackAreaSlot >, TPanelChildren< UE::Sequencer::SCompoundTrackLaneView::FSlot >, TPanelChildren< UE::Sequencer::STrackLane::FSlot >, TSingleWidgetChildrenWithSlot< SlotType >, TSingleWidgetChildrenWithSlot< FSingleWidgetChildrenWithSlot >, TSingleWidgetChildrenWithSlot< TSingleWidgetChildrenWithBasicLayoutSlot< EInvalidateWidgetReason::Layout > >, TSingleWidgetChildrenWithSlot< TSingleWidgetChildrenWithBasicLayoutSlot< InPaddingInvalidationReason > >, TSlotlessChildren< ChildType >, TSlotlessChildren< SNodePanel::SNode >, TSlotlessChildren< SWidget >, TWeakChild< ChildType >, and TWeakChild< SWidget >.
Referenced by ForEachWidget(), and ForEachWidget().
GetName()
FName FChildren::GetName () const inline
Option to give a name to Children to SlotAttribute purposes or for debugging.
Definition at line 113 of file ChildrenBase.h.
References Debug_TestDestroyTag(), and Name.
Referenced by TWidgetSlotWithAttributeSupport< SlotType >::Construct(), and TWidgetSlotWithAttributeSupport< SlotType >::GetContainerName().
GetOwner()
SWidget & FChildren::GetOwner () const inline
Returns
the SWidget that own the FChildren
Definition at line 57 of file ChildrenBase.h.
References Debug_TestDestroyTag(), and Owner.
Referenced by TSlotlessChildren< ChildType >::Add(), TWeakChild< ChildType >::AttachWidget(), TWeakChild< ChildType >::DetachWidget(), TSlotlessChildren< ChildType >::Empty(), TSlotlessChildren< ChildType >::Insert(), FScopedWidgetSlotArguments< FNodeSlot >::Move(), TSlotlessChildren< ChildType >::Remove(), TSlotlessChildren< ChildType >::RemoveAt(), TSlotlessChildren< ChildType >::Reset(), FScopedWidgetSlotArguments< FNodeSlot >::Sort(), TSlotlessChildren< ChildType >::Sort(), FScopedWidgetSlotArguments< FNodeSlot >::StableSort(), FScopedWidgetSlotArguments< FNodeSlot >::Swap(), and TSlotlessChildren< ChildType >::Swap().
GetSlotAt()
virtual const FSlotBase & FChildren::GetSlotAt (int32 ChildIndex) const pure virtual
Returns
the const reference to the slot at the specified Index
Implemented in FCombinedChildren, FNoChildren, FScopedWidgetSlotArguments< FNodeSlot >, FScopedWidgetSlotArguments< FPopupLayerSlot >, TOneDynamicChild< SlotType >, TOneDynamicChild< FBasicLayoutWidgetSlot >, TPanelChildren< SlotType >, TPanelChildren< FBasicLayoutWidgetSlot >, TPanelChildren< FOverlaySlot >::FScopedWidgetSlotArguments< FOverlaySlot >, TPanelChildren< FOverlaySlot >, TPanelChildren< FSlot >::FScopedWidgetSlotArguments< FSlot >, TPanelChildren< FSlot >, TPanelChildren< SBoxPanel::FSlot >, TPanelChildren< SConstraintCanvas::FSlot >, TPanelChildren< SGridPanel::FSlot >, TPanelChildren< SNodePanel::SNode::FNodeSlot >, TPanelChildren< SRadialBox::FSlot >, TPanelChildren< SScrollBarTrack::FSlot >, TPanelChildren< SScrollBox::FSlot >, TPanelChildren< SSegmentedControl::FSlot >, TPanelChildren< SSplitter2x2::FSlot >, TPanelChildren< SSplitter::FSlot >, TPanelChildren< SUniformGridPanel::FSlot >, TPanelChildren< UE::Sequencer::FTrackAreaSlot >, TPanelChildren< UE::Sequencer::SCompoundTrackLaneView::FSlot >, TPanelChildren< UE::Sequencer::STrackLane::FSlot >, TSingleWidgetChildrenWithSlot< SlotType >, TSingleWidgetChildrenWithSlot< FSingleWidgetChildrenWithSlot >, TSingleWidgetChildrenWithSlot< TSingleWidgetChildrenWithBasicLayoutSlot< EInvalidateWidgetReason::Layout > >, TSingleWidgetChildrenWithSlot< TSingleWidgetChildrenWithBasicLayoutSlot< InPaddingInvalidationReason > >, TSlotlessChildren< ChildType >, TSlotlessChildren< SNodePanel::SNode >, TSlotlessChildren< SWidget >, TWeakChild< ChildType >, and TWeakChild< SWidget >.
Num()
virtual int32 FChildren::Num () const pure virtual
Returns
the number of children
Implemented in FCombinedChildren, FNoChildren, FScopedWidgetSlotArguments< FNodeSlot >, FScopedWidgetSlotArguments< FPopupLayerSlot >, TOneDynamicChild< SlotType >, TOneDynamicChild< FBasicLayoutWidgetSlot >, TPanelChildren< SlotType >, TPanelChildren< FBasicLayoutWidgetSlot >, TPanelChildren< FOverlaySlot >::FScopedWidgetSlotArguments< FOverlaySlot >, TPanelChildren< FOverlaySlot >, TPanelChildren< FSlot >::FScopedWidgetSlotArguments< FSlot >, TPanelChildren< FSlot >, TPanelChildren< SBoxPanel::FSlot >, TPanelChildren< SConstraintCanvas::FSlot >, TPanelChildren< SGridPanel::FSlot >, TPanelChildren< SNodePanel::SNode::FNodeSlot >, TPanelChildren< SRadialBox::FSlot >, TPanelChildren< SScrollBarTrack::FSlot >, TPanelChildren< SScrollBox::FSlot >, TPanelChildren< SSegmentedControl::FSlot >, TPanelChildren< SSplitter2x2::FSlot >, TPanelChildren< SSplitter::FSlot >, TPanelChildren< SUniformGridPanel::FSlot >, TPanelChildren< UE::Sequencer::FTrackAreaSlot >, TPanelChildren< UE::Sequencer::SCompoundTrackLaneView::FSlot >, TPanelChildren< UE::Sequencer::STrackLane::FSlot >, TSingleWidgetChildrenWithSlot< SlotType >, TSingleWidgetChildrenWithSlot< FSingleWidgetChildrenWithSlot >, TSingleWidgetChildrenWithSlot< TSingleWidgetChildrenWithBasicLayoutSlot< EInvalidateWidgetReason::Layout > >, TSingleWidgetChildrenWithSlot< TSingleWidgetChildrenWithBasicLayoutSlot< InPaddingInvalidationReason > >, TSlotlessChildren< ChildType >, TSlotlessChildren< SNodePanel::SNode >, TSlotlessChildren< SWidget >, TWeakChild< ChildType >, and TWeakChild< SWidget >.
Referenced by ForEachWidget(), ForEachWidget(), and NumSlot().
NumSlot()
virtual int32 FChildren::NumSlot () const inline virtual
Returns
the number of slot the children has.
Reimplemented in FCombinedChildren, TSlotlessChildren< ChildType >, TSlotlessChildren< SNodePanel::SNode >, TSlotlessChildren< SWidget >, TWeakChild< ChildType >, and TWeakChild< SWidget >.
Definition at line 98 of file ChildrenBase.h.
References Num().
Referenced by TWidgetSlotWithAttributeSupport< SlotType >::GetContainerSortOrder().
operator new()
void * FChildren::operator new (size_t) delete
operator new[]()
void * FChildren::operator new[] (size_t) delete
SupportSlotWithSlateAttribute()
virtual bool FChildren::SupportSlotWithSlateAttribute () const inline virtual
Returns
if the Children can support slot with SlateSlotAttribute.
Reimplemented in FScopedWidgetSlotArguments< FNodeSlot >, FScopedWidgetSlotArguments< FPopupLayerSlot >, TPanelChildren< SlotType >, TPanelChildren< FBasicLayoutWidgetSlot >, TPanelChildren< FOverlaySlot >::FScopedWidgetSlotArguments< FOverlaySlot >, TPanelChildren< FOverlaySlot >, TPanelChildren< FSlot >::FScopedWidgetSlotArguments< FSlot >, TPanelChildren< FSlot >, TPanelChildren< SBoxPanel::FSlot >, TPanelChildren< SConstraintCanvas::FSlot >, TPanelChildren< SGridPanel::FSlot >, TPanelChildren< SNodePanel::SNode::FNodeSlot >, TPanelChildren< SRadialBox::FSlot >, TPanelChildren< SScrollBarTrack::FSlot >, TPanelChildren< SScrollBox::FSlot >, TPanelChildren< SSegmentedControl::FSlot >, TPanelChildren< SSplitter2x2::FSlot >, TPanelChildren< SSplitter::FSlot >, TPanelChildren< SUniformGridPanel::FSlot >, TPanelChildren< UE::Sequencer::FTrackAreaSlot >, TPanelChildren< UE::Sequencer::SCompoundTrackLaneView::FSlot >, and TPanelChildren< UE::Sequencer::STrackLane::FSlot >.
Definition at line 107 of file ChildrenBase.h.
Referenced by TWidgetSlotWithAttributeSupport< SlotType >::Construct().
Friends And Related Symbol Documentation
FCombinedChildren
friend class FCombinedChildren friend
Definition at line 120 of file ChildrenBase.h.
References FCombinedChildren.
Referenced by FCombinedChildren.
TOneDynamicChild
template<typename T> friend class TOneDynamicChild friend
Definition at line 122 of file ChildrenBase.h.
References TOneDynamicChild.
Referenced by TOneDynamicChild.
Field Documentation
Debug_bIsIteratingChildren
bool FChildren::Debug_bIsIteratingChildren = false mutable private
Definition at line 227 of file ChildrenBase.h.
Referenced by ~FChildren(), ForEachWidget(), and ForEachWidget().
Debug_DestroyedTag
uint8 FChildren::Debug_DestroyedTag = 0xDC mutable private
Definition at line 228 of file ChildrenBase.h.
Referenced by ~FChildren(), and Debug_TestDestroyTag().
Name
FName FChildren::Name private
Definition at line 224 of file ChildrenBase.h.
Referenced by FChildren(), FChildren(), ~FChildren(), and GetName().
Owner
SWidget* FChildren::Owner private
Definition at line 223 of file ChildrenBase.h.
Referenced by FChildren(), FChildren(), ~FChildren(), and GetOwner().
The documentation for this class was generated from the following file:
Runtime/SlateCore/Public/Layout/ChildrenBase.h