Unreal Engine 5.6 C++ API: TLockFreeFixedSizeAllocator< SIZE, TPaddingForCacheContention, TTrackingCounter > Class Template Reference
TLockFreeFixedSizeAllocator< SIZE, TPaddingForCacheContention, TTrackingCounter > Class Template Reference
Thread safe, lock free pooling allocator of fixed size blocks that only returns free space when the allocator is destroyed.
#include "LockFreeFixedSizeAllocator.h"
Public Member Functions
TLockFreeFixedSizeAllocator ()
~TLockFreeFixedSizeAllocator ()
Destructor, returns all memory via FMemory::Free.
void * Allocate (int32 Alignment=MIN_ALIGNMENT)
Allocates a memory block of size SIZE.
void Free (void *Item)
Puts a memory block previously obtained from Allocate() back on the free list for future use.
TTrackingCounter::IntegerType GetNumFree () const
Gets the number of allocated memory blocks that are currently unused.
TTrackingCounter::IntegerType GetNumUsed () const
Gets the number of allocated memory blocks that are currently in use.
void Trim ()
Returns all free memory to the heap.
Private Member Functions
UE_NONCOPYABLE (TLockFreeFixedSizeAllocator) TLockFreePointerListUnordered< void
Lock free list of free memory blocks.
Private Attributes
TPaddingForCacheContention FreeList
TTrackingCounter NumFree
Total number of blocks in the free list.
TTrackingCounter NumUsed
Total number of blocks outstanding and not in the free list.
Detailed Description
template<int32 SIZE, int TPaddingForCacheContention, typename TTrackingCounter = FNoopCounter>
class TLockFreeFixedSizeAllocator< SIZE, TPaddingForCacheContention, TTrackingCounter >
Thread safe, lock free pooling allocator of fixed size blocks that only returns free space when the allocator is destroyed.
Alignment isn't handled; assumes FMemory::Malloc will work.
Definition at line 195 of file LockFreeFixedSizeAllocator.h.
Constructor & Destructor Documentation
TLockFreeFixedSizeAllocator()
template<int32 SIZE, int TPaddingForCacheContention, typename TTrackingCounter = FNoopCounter> TLockFreeFixedSizeAllocator< SIZE, TPaddingForCacheContention, TTrackingCounter >::TLockFreeFixedSizeAllocator () inline
Definition at line 198 of file LockFreeFixedSizeAllocator.h.
~TLockFreeFixedSizeAllocator()
template<int32 SIZE, int TPaddingForCacheContention, typename TTrackingCounter = FNoopCounter> TLockFreeFixedSizeAllocator< SIZE, TPaddingForCacheContention, TTrackingCounter >::~TLockFreeFixedSizeAllocator () inline
Destructor, returns all memory via FMemory::Free.
Definition at line 204 of file LockFreeFixedSizeAllocator.h.
Member Function Documentation
Allocate()
template<int32 SIZE, int TPaddingForCacheContention, typename TTrackingCounter = FNoopCounter> void * TLockFreeFixedSizeAllocator< SIZE, TPaddingForCacheContention, TTrackingCounter >::Allocate (int32 Alignment = MIN_ALIGNMENT) inline
Allocates a memory block of size SIZE.
Returns
Pointer to the allocated memory.
See also
Free
Definition at line 220 of file LockFreeFixedSizeAllocator.h.
Free()
template<int32 SIZE, int TPaddingForCacheContention, typename TTrackingCounter = FNoopCounter> void TLockFreeFixedSizeAllocator< SIZE, TPaddingForCacheContention, TTrackingCounter >::Free (void * Item) inline
Puts a memory block previously obtained from Allocate() back on the free list for future use.
Parameters
Item The item to free.
See also
Allocate
Definition at line 261 of file LockFreeFixedSizeAllocator.h.
Referenced by TLockFreeFixedSizeAllocator< PageSize, PLATFORM_CACHE_LINE_SIZE, FThreadSafeCounter >::Allocate().
GetNumFree()
template<int32 SIZE, int TPaddingForCacheContention, typename TTrackingCounter = FNoopCounter> TTrackingCounter::IntegerType TLockFreeFixedSizeAllocator< SIZE, TPaddingForCacheContention, TTrackingCounter >::GetNumFree () const inline
Gets the number of allocated memory blocks that are currently unused.
Returns
Number of unused memory blocks.
See also
GetNumUsed
Definition at line 309 of file LockFreeFixedSizeAllocator.h.
GetNumUsed()
template<int32 SIZE, int TPaddingForCacheContention, typename TTrackingCounter = FNoopCounter> TTrackingCounter::IntegerType TLockFreeFixedSizeAllocator< SIZE, TPaddingForCacheContention, TTrackingCounter >::GetNumUsed () const inline
Gets the number of allocated memory blocks that are currently in use.
Returns
Number of used memory blocks.
See also
GetNumFree
Definition at line 298 of file LockFreeFixedSizeAllocator.h.
Referenced by TLockFreeFixedSizeAllocator< PageSize, PLATFORM_CACHE_LINE_SIZE, FThreadSafeCounter >::~TLockFreeFixedSizeAllocator().
Trim()
template<int32 SIZE, int TPaddingForCacheContention, typename TTrackingCounter = FNoopCounter> void TLockFreeFixedSizeAllocator< SIZE, TPaddingForCacheContention, TTrackingCounter >::Trim () inline
Returns all free memory to the heap.
Definition at line 277 of file LockFreeFixedSizeAllocator.h.
Referenced by TLockFreeFixedSizeAllocator< PageSize, PLATFORM_CACHE_LINE_SIZE, FThreadSafeCounter >::~TLockFreeFixedSizeAllocator().
UE_NONCOPYABLE()
template<int32 SIZE, int TPaddingForCacheContention, typename TTrackingCounter = FNoopCounter> TLockFreeFixedSizeAllocator< SIZE, TPaddingForCacheContention, TTrackingCounter >::UE_NONCOPYABLE (TLockFreeFixedSizeAllocator< SIZE, TPaddingForCacheContention, TTrackingCounter >) private
Lock free list of free memory blocks.
Field Documentation
FreeList
template<int32 SIZE, int TPaddingForCacheContention, typename TTrackingCounter = FNoopCounter> TPaddingForCacheContention TLockFreeFixedSizeAllocator< SIZE, TPaddingForCacheContention, TTrackingCounter >::FreeList private
Definition at line 318 of file LockFreeFixedSizeAllocator.h.
NumFree
template<int32 SIZE, int TPaddingForCacheContention, typename TTrackingCounter = FNoopCounter> TTrackingCounter TLockFreeFixedSizeAllocator< SIZE, TPaddingForCacheContention, TTrackingCounter >::NumFree private
Total number of blocks in the free list.
Definition at line 324 of file LockFreeFixedSizeAllocator.h.
NumUsed
template<int32 SIZE, int TPaddingForCacheContention, typename TTrackingCounter = FNoopCounter> TTrackingCounter TLockFreeFixedSizeAllocator< SIZE, TPaddingForCacheContention, TTrackingCounter >::NumUsed private
Total number of blocks outstanding and not in the free list.
Definition at line 321 of file LockFreeFixedSizeAllocator.h.
The documentation for this class was generated from the following file:
Runtime/Core/Public/Containers/LockFreeFixedSizeAllocator.h