Unreal Engine 5.6 C++ API: FMaterialCompilationOutput Class Reference
FMaterialCompilationOutput Class Reference
Stores outputs from the material compile that need to be saved.
#include "MaterialShared.h"
Public Member Functions
FMaterialCompilationOutput ()
int32 FindOrAddUserSceneTexture (FName UserSceneTexture)
int32 GetNumPostProcessInputsUsed () const
bool IsSceneTextureUsed (ESceneTextureId TexId) const
int ELWCFunctionKind::Max LAYOUT_ARRAY_EDITORONLY (uint16, EstimatedLWCFuncUsagesCS,(int) ELWCFunctionKind::Max) LAYOUT_FIELD_EDITORONLY(uint16
Number of virtual texture lookups performed, excludes direct invocation in shaders (for example VT lightmaps)
LAYOUT_ARRAY_EDITORONLY (uint16, EstimatedLWCFuncUsagesVS,(int) ELWCFunctionKind::Max) LAYOUT_ARRAY_EDITORONLY(uint16
Estimate of the number of times each LWC operator occurs in the material shader code.
LAYOUT_BITFIELD (uint8, bHasRuntimeVirtualTextureOutputNode, 1)
true if the material writes to a runtime virtual texture custom output node.
LAYOUT_BITFIELD (uint8, bIsLightFunctionAtlasCompatible, 1)
true if the material is compatible with the light function atlas
LAYOUT_BITFIELD (uint8, bModifiesMeshPosition, 1)
true if the material modifies the the mesh position.
LAYOUT_BITFIELD (uint8, bNeedsSceneTextures, 1)
true if the material needs the scene texture lookups.
LAYOUT_BITFIELD (uint8, bUsedWithNeuralNetworks, 1)
Whether the material uses NNE.
LAYOUT_BITFIELD (uint8, bUsesAnisotropy, 1)
true if the material uses non 0 anisotropy value
LAYOUT_BITFIELD (uint8, bUsesCustomizedUVs, 1)
Whether the material uses customized UVs.
LAYOUT_BITFIELD (uint8, bUsesDBufferTextureLookup, 1)
true if the material uses DBuffer texture lookups.
LAYOUT_BITFIELD (uint8, bUsesDisplacement, 1)
Whether the material uses scalar displacement.
LAYOUT_BITFIELD (uint8, bUsesDistanceCullFade, 1)
true if the material uses distance cull fade
LAYOUT_BITFIELD (uint8, bUsesEyeAdaptation, 1)
true if the material uses the EyeAdaptationLookup
LAYOUT_BITFIELD (uint8, bUsesGlobalDistanceField, 1)
true if material uses the global distance field
LAYOUT_BITFIELD (uint8, bUsesPerInstanceCustomData, 1)
true if the material uses per-instance custom data
LAYOUT_BITFIELD (uint8, bUsesPixelDepthOffset, 1)
true if the material writes a pixel depth offset
LAYOUT_BITFIELD (uint8, bUsesVertexInterpolator, 1)
true if the material uses vertex interpolator
LAYOUT_BITFIELD (uint8, bUsesWorldPositionOffset, 1)
Whether the material uses world position offset.
LAYOUT_FIELD (FSubstrateMaterialCompilationOutput, SubstrateMaterialCompilationOutput)
The Substrate material layout.
LAYOUT_FIELD (FUniformExpressionSet, UniformExpressionSet)
LAYOUT_FIELD (TMemoryImageArray< FScriptName >, UserSceneTextureInputs)
User scene texture inputs to this material, these will use slots not taken up by the UsedSceneTextures bitfield below.
LAYOUT_FIELD (uint32, UsedSceneTextures)
Bitfield of the ESceneTextures used.
LAYOUT_FIELD (uint8, RuntimeVirtualTextureOutputAttributeMask)
Bitfield of runtime virtual texture output attributes.
LAYOUT_FIELD (uint8, UsedDBufferTextures)
Bitfield of used DBuffer textures .
LAYOUT_FIELD (uint8, UsedPathTracingBufferTextures)
Bitfield of the EPathTracingBufferTextureId used.
LAYOUT_FIELD_EDITORONLY (uint16, EstimatedNumTextureSamplesPS)
LAYOUT_FIELD_EDITORONLY (uint16, EstimatedNumTextureSamplesVS)
Number of times SampleTexture is called, excludes custom nodes.
LAYOUT_FIELD_EDITORONLY (uint8, NumUsedCustomInterpolatorScalars)
Number of used custom vertex interpolation scalars.
LAYOUT_FIELD_EDITORONLY (uint8, NumUsedUVScalars)
Number of used custom UV scalars.
bool NeedsGBuffer () const
true if the material uses any GBuffer textures
bool RequiresSceneColorCopy () const
Indicates whether the material uses scene color.
void SetIsDBufferTextureLookupUsed (bool bValue)
void SetIsDBufferTextureUsed (int32 TextureIndex)
void SetIsPathTracingBufferTextureUsed (int32 TexId)
void SetIsSceneTextureUsed (ESceneTextureId TexId)
bool UsesSceneDepthLookup () const
true if the material uses the SceneDepth lookup
bool UsesVelocitySceneTexture () const
true if the material uses the Velocity SceneTexture lookup
Data Fields
EstimatedLWCFuncUsagesPS
int ELWCFunctionKind::Max EstimatedNumVirtualTextureLookups
Private Member Functions
DECLARE_TYPE_LAYOUT (FMaterialCompilationOutput, NonVirtual)
Detailed Description
Stores outputs from the material compile that need to be saved.
Definition at line 760 of file MaterialShared.h.
Constructor & Destructor Documentation
FMaterialCompilationOutput()
FMaterialCompilationOutput::FMaterialCompilationOutput () inline
Definition at line 764 of file MaterialShared.h.
References EstimatedLWCFuncUsagesPS, EstimatedNumVirtualTextureLookups, and FMemory::Memzero().
Referenced by DECLARE_TYPE_LAYOUT().
Member Function Documentation
DECLARE_TYPE_LAYOUT()
FMaterialCompilationOutput::DECLARE_TYPE_LAYOUT (FMaterialCompilationOutput , NonVirtual) private
References FMaterialCompilationOutput().
FindOrAddUserSceneTexture()
int32 FMaterialCompilationOutput::FindOrAddUserSceneTexture (FName UserSceneTexture)
GetNumPostProcessInputsUsed()
int32 FMaterialCompilationOutput::GetNumPostProcessInputsUsed () const
IsSceneTextureUsed()
bool FMaterialCompilationOutput::IsSceneTextureUsed (ESceneTextureId TexId) const inline
Definition at line 801 of file MaterialShared.h.
Referenced by NeedsGBuffer(), RequiresSceneColorCopy(), UsesSceneDepthLookup(), and UsesVelocitySceneTexture().
LAYOUT_ARRAY_EDITORONLY() [1/2]
int ELWCFunctionKind::Max FMaterialCompilationOutput::LAYOUT_ARRAY_EDITORONLY (uint16 , EstimatedLWCFuncUsagesCS , (int) ELWCFunctionKind::Max)
Number of virtual texture lookups performed, excludes direct invocation in shaders (for example VT lightmaps)
References LAYOUT_ARRAY_EDITORONLY(), and Max.
LAYOUT_ARRAY_EDITORONLY() [2/2]
FMaterialCompilationOutput::LAYOUT_ARRAY_EDITORONLY (uint16 , EstimatedLWCFuncUsagesVS , (int) ELWCFunctionKind::Max)
Estimate of the number of times each LWC operator occurs in the material shader code.
Referenced by LAYOUT_ARRAY_EDITORONLY().
LAYOUT_BITFIELD() [1/16]
FMaterialCompilationOutput::LAYOUT_BITFIELD (uint8 , bHasRuntimeVirtualTextureOutputNode , 1)
true if the material writes to a runtime virtual texture custom output node.
References LAYOUT_BITFIELD().
LAYOUT_BITFIELD() [2/16]
FMaterialCompilationOutput::LAYOUT_BITFIELD (uint8 , bIsLightFunctionAtlasCompatible , 1)
true if the material is compatible with the light function atlas
References LAYOUT_BITFIELD().
LAYOUT_BITFIELD() [3/16]
FMaterialCompilationOutput::LAYOUT_BITFIELD (uint8 , bModifiesMeshPosition , 1)
true if the material modifies the the mesh position.
References LAYOUT_BITFIELD().
LAYOUT_BITFIELD() [4/16]
FMaterialCompilationOutput::LAYOUT_BITFIELD (uint8 , bNeedsSceneTextures , 1)
true if the material needs the scene texture lookups.
References LAYOUT_BITFIELD().
Referenced by LAYOUT_BITFIELD(), LAYOUT_BITFIELD(), LAYOUT_BITFIELD(), LAYOUT_BITFIELD(), LAYOUT_BITFIELD(), LAYOUT_BITFIELD(), LAYOUT_BITFIELD(), LAYOUT_BITFIELD(), LAYOUT_BITFIELD(), LAYOUT_BITFIELD(), LAYOUT_BITFIELD(), LAYOUT_BITFIELD(), LAYOUT_BITFIELD(), LAYOUT_BITFIELD(), LAYOUT_BITFIELD(), and LAYOUT_BITFIELD().
LAYOUT_BITFIELD() [5/16]
FMaterialCompilationOutput::LAYOUT_BITFIELD (uint8 , bUsedWithNeuralNetworks , 1)
Whether the material uses NNE.
References LAYOUT_BITFIELD().
LAYOUT_BITFIELD() [6/16]
FMaterialCompilationOutput::LAYOUT_BITFIELD (uint8 , bUsesAnisotropy , 1)
true if the material uses non 0 anisotropy value
References LAYOUT_BITFIELD().
LAYOUT_BITFIELD() [7/16]
FMaterialCompilationOutput::LAYOUT_BITFIELD (uint8 , bUsesCustomizedUVs , 1)
Whether the material uses customized UVs.
References LAYOUT_BITFIELD().
LAYOUT_BITFIELD() [8/16]
FMaterialCompilationOutput::LAYOUT_BITFIELD (uint8 , bUsesDBufferTextureLookup , 1)
true if the material uses DBuffer texture lookups.
References LAYOUT_BITFIELD().
LAYOUT_BITFIELD() [9/16]
FMaterialCompilationOutput::LAYOUT_BITFIELD (uint8 , bUsesDisplacement , 1)
Whether the material uses scalar displacement.
References LAYOUT_BITFIELD().
LAYOUT_BITFIELD() [10/16]
FMaterialCompilationOutput::LAYOUT_BITFIELD (uint8 , bUsesDistanceCullFade , 1)
true if the material uses distance cull fade
References LAYOUT_BITFIELD().
LAYOUT_BITFIELD() [11/16]
FMaterialCompilationOutput::LAYOUT_BITFIELD (uint8 , bUsesEyeAdaptation , 1)
true if the material uses the EyeAdaptationLookup
References LAYOUT_BITFIELD().
LAYOUT_BITFIELD() [12/16]
FMaterialCompilationOutput::LAYOUT_BITFIELD (uint8 , bUsesGlobalDistanceField , 1)
true if material uses the global distance field
References LAYOUT_BITFIELD().
LAYOUT_BITFIELD() [13/16]
FMaterialCompilationOutput::LAYOUT_BITFIELD (uint8 , bUsesPerInstanceCustomData , 1)
true if the material uses per-instance custom data
References LAYOUT_BITFIELD().
LAYOUT_BITFIELD() [14/16]
FMaterialCompilationOutput::LAYOUT_BITFIELD (uint8 , bUsesPixelDepthOffset , 1)
true if the material writes a pixel depth offset
References LAYOUT_BITFIELD().
LAYOUT_BITFIELD() [15/16]
FMaterialCompilationOutput::LAYOUT_BITFIELD (uint8 , bUsesVertexInterpolator , 1)
true if the material uses vertex interpolator
References LAYOUT_BITFIELD().
LAYOUT_BITFIELD() [16/16]
FMaterialCompilationOutput::LAYOUT_BITFIELD (uint8 , bUsesWorldPositionOffset , 1)
Whether the material uses world position offset.
References LAYOUT_BITFIELD().
LAYOUT_FIELD() [1/7]
FMaterialCompilationOutput::LAYOUT_FIELD (FSubstrateMaterialCompilationOutput , SubstrateMaterialCompilationOutput)
The Substrate material layout.
References LAYOUT_FIELD().
LAYOUT_FIELD() [2/7]
FMaterialCompilationOutput::LAYOUT_FIELD (FUniformExpressionSet , UniformExpressionSet)
Referenced by LAYOUT_FIELD(), LAYOUT_FIELD(), and LAYOUT_FIELD().
LAYOUT_FIELD() [3/7]
FMaterialCompilationOutput::LAYOUT_FIELD (TMemoryImageArray< FScriptName > , UserSceneTextureInputs)
User scene texture inputs to this material, these will use slots not taken up by the UsedSceneTextures bitfield below.
LAYOUT_FIELD() [4/7]
FMaterialCompilationOutput::LAYOUT_FIELD (uint32 , UsedSceneTextures)
Bitfield of the ESceneTextures used.
LAYOUT_FIELD() [5/7]
FMaterialCompilationOutput::LAYOUT_FIELD (uint8 , RuntimeVirtualTextureOutputAttributeMask)
Bitfield of runtime virtual texture output attributes.
References LAYOUT_FIELD().
LAYOUT_FIELD() [6/7]
FMaterialCompilationOutput::LAYOUT_FIELD (uint8 , UsedDBufferTextures)
Bitfield of used DBuffer textures .
References LAYOUT_FIELD().
LAYOUT_FIELD() [7/7]
FMaterialCompilationOutput::LAYOUT_FIELD (uint8 , UsedPathTracingBufferTextures)
Bitfield of the EPathTracingBufferTextureId used.
LAYOUT_FIELD_EDITORONLY() [1/4]
FMaterialCompilationOutput::LAYOUT_FIELD_EDITORONLY (uint16 , EstimatedNumTextureSamplesPS)
LAYOUT_FIELD_EDITORONLY() [2/4]
FMaterialCompilationOutput::LAYOUT_FIELD_EDITORONLY (uint16 , EstimatedNumTextureSamplesVS)
Number of times SampleTexture is called, excludes custom nodes.
Referenced by LAYOUT_FIELD_EDITORONLY(), and LAYOUT_FIELD_EDITORONLY().
LAYOUT_FIELD_EDITORONLY() [3/4]
FMaterialCompilationOutput::LAYOUT_FIELD_EDITORONLY (uint8 , NumUsedCustomInterpolatorScalars)
Number of used custom vertex interpolation scalars.
References LAYOUT_FIELD_EDITORONLY().
LAYOUT_FIELD_EDITORONLY() [4/4]
FMaterialCompilationOutput::LAYOUT_FIELD_EDITORONLY (uint8 , NumUsedUVScalars)
Number of used custom UV scalars.
References LAYOUT_FIELD_EDITORONLY().
NeedsGBuffer()
bool FMaterialCompilationOutput::NeedsGBuffer () const inline
true if the material uses any GBuffer textures
Definition at line 830 of file MaterialShared.h.
References IsSceneTextureUsed().
RequiresSceneColorCopy()
bool FMaterialCompilationOutput::RequiresSceneColorCopy () const inline
Indicates whether the material uses scene color.
Definition at line 827 of file MaterialShared.h.
References IsSceneTextureUsed().
SetIsDBufferTextureLookupUsed()
void FMaterialCompilationOutput::SetIsDBufferTextureLookupUsed (bool bValue) inline
Definition at line 822 of file MaterialShared.h.
SetIsDBufferTextureUsed()
void FMaterialCompilationOutput::SetIsDBufferTextureUsed (int32 TextureIndex) inline
Definition at line 821 of file MaterialShared.h.
SetIsPathTracingBufferTextureUsed()
void FMaterialCompilationOutput::SetIsPathTracingBufferTextureUsed (int32 TexId) inline
Definition at line 824 of file MaterialShared.h.
SetIsSceneTextureUsed()
void FMaterialCompilationOutput::SetIsSceneTextureUsed (ESceneTextureId TexId) inline
Definition at line 803 of file MaterialShared.h.
UsesSceneDepthLookup()
bool FMaterialCompilationOutput::UsesSceneDepthLookup () const inline
true if the material uses the SceneDepth lookup
Definition at line 855 of file MaterialShared.h.
References IsSceneTextureUsed().
UsesVelocitySceneTexture()
bool FMaterialCompilationOutput::UsesVelocitySceneTexture () const inline
true if the material uses the Velocity SceneTexture lookup
Definition at line 858 of file MaterialShared.h.
References IsSceneTextureUsed().
Field Documentation
EstimatedLWCFuncUsagesPS
FMaterialCompilationOutput::EstimatedLWCFuncUsagesPS
Definition at line 877 of file MaterialShared.h.
Referenced by FMaterialCompilationOutput().
EstimatedNumVirtualTextureLookups
int ELWCFunctionKind::Max FMaterialCompilationOutput::EstimatedNumVirtualTextureLookups
Definition at line 881 of file MaterialShared.h.
Referenced by FMaterialCompilationOutput().
The documentation for this class was generated from the following file:
Runtime/Engine/Public/MaterialShared.h