Unreal Engine 5.6 C++ API: TUniqueObj< T > Class Template Reference
TUniqueObj< T > Class Template Reference
#include "UniqueObj.h"
Public Types
using ElementType = T
Public Member Functions
template<typename... Args>
TUniqueObj (Args &&... args)
TUniqueObj (const TUniqueObj &other)
TUniqueObj (TUniqueObj &&other)
T & Get ()
const T & Get () const
T & operator* ()
const T & operator* () const
T * operator-> ()
const T * operator-> () const
template<typename Arg>
TUniqueObj & operator= (Arg &&other)
TUniqueObj & operator= (const TUniqueObj &)=delete
TUniqueObj & operator= (TUniqueObj &&other)
void Serialize (FArchive &Ar)
Private Attributes
TUniquePtr< T > Obj
Detailed Description
template<typename T>
class TUniqueObj< T >
Definition at line 12 of file UniqueObj.h.
Member Typedef Documentation
ElementType
template<typename T> using TUniqueObj< T >::ElementType = T
Definition at line 15 of file UniqueObj.h.
Constructor & Destructor Documentation
TUniqueObj() [1/3]
template<typename T> TUniqueObj< T >::TUniqueObj (const TUniqueObj< T > & other) inline
Definition at line 17 of file UniqueObj.h.
References TUniqueObj(), MakeUnique(), and Obj.
Referenced by TUniqueObj(), TUniqueObj(), operator=(), operator=(), and operator=().
TUniqueObj() [2/3]
template<typename T> TUniqueObj< T >::TUniqueObj (TUniqueObj< T > && other) inline
Definition at line 24 of file UniqueObj.h.
References TUniqueObj(), MakeUnique(), MoveTemp(), and Obj.
TUniqueObj() [3/3]
template<typename T> template<typename... Args> TUniqueObj< T >::TUniqueObj (Args &&... args) inline explicit
Definition at line 30 of file UniqueObj.h.
References Forward(), MakeUnique(), and Obj.
Member Function Documentation
Get() [1/2]
template<typename T> T & TUniqueObj< T >::Get () inline
Definition at line 52 of file UniqueObj.h.
References Obj.
Get() [2/2]
template<typename T> const T & TUniqueObj< T >::Get () const inline
Definition at line 53 of file UniqueObj.h.
References Obj.
operator*() [1/2]
template<typename T> T & TUniqueObj< T >::operator* () inline
Definition at line 58 of file UniqueObj.h.
References Obj.
operator*() [2/2]
template<typename T> const T & TUniqueObj< T >::operator* () const inline
Definition at line 59 of file UniqueObj.h.
References Obj.
operator->() [1/2]
template<typename T> T * TUniqueObj< T >::operator-> () inline
Definition at line 55 of file UniqueObj.h.
References Obj.
operator->() [2/2]
template<typename T> const T * TUniqueObj< T >::operator-> () const inline
Definition at line 56 of file UniqueObj.h.
References Obj.
operator=() [1/3]
template<typename T> template<typename Arg> TUniqueObj & TUniqueObj< T >::operator= (Arg && other) inline
Definition at line 46 of file UniqueObj.h.
References TUniqueObj(), Forward(), and Obj.
operator=() [2/3]
template<typename T> TUniqueObj & TUniqueObj< T >::operator= (const TUniqueObj< T > &) delete
References TUniqueObj().
operator=() [3/3]
template<typename T> TUniqueObj & TUniqueObj< T >::operator= (TUniqueObj< T > && other) inline
Definition at line 39 of file UniqueObj.h.
References TUniqueObj(), Obj, and Swap.
Serialize()
template<typename T> void TUniqueObj< T >::Serialize (FArchive & Ar) inline
Definition at line 61 of file UniqueObj.h.
References Ar, and Obj.
Referenced by operator<<().
Field Documentation
Obj
template<typename T> TUniquePtr<T> TUniqueObj< T >::Obj private
Definition at line 67 of file UniqueObj.h.
Referenced by TUniqueObj(), TUniqueObj(), TUniqueObj(), Get(), Get(), operator*(), operator*(), operator->(), operator->(), operator=(), operator=(), and Serialize().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Templates/UniqueObj.h