Unreal Engine 5.6 C++ API: FProperty Class Reference
FProperty Class Reference
#include "UnrealType.h"
Public Member Functions
FProperty (FFieldVariant InOwner, const FName &InName, EObjectFlags InObjectFlags)
FProperty (FFieldVariant InOwner, const UECodeGen_Private::FPropertyParamsBaseWithOffset &Prop, EPropertyFlags AdditionalPropertyFlags=CPF_None)
Constructor used for constructing compiled-in properties.
FProperty (FFieldVariant InOwner, const UECodeGen_Private::FPropertyParamsBaseWithoutOffset &Prop, EPropertyFlags AdditionalPropertyFlags=CPF_None)
Constructor used for constructing compiled-in properties.
void * AllocateAndInitializeValue () const
Allocates and initializes memory to hold a value this property represents.
virtual void CallGetter (const void *Container, void *OutValue) const
Calls the native getter function for this property.
virtual void CallSetter (void *Container, const void *InValue) const
Calls the native setter function for this property.
virtual bool CanSerializeFromTypeName (UE::FPropertyTypeName Type) const
Returns true if the type of this property matches the type name.
virtual void ClearIntrusiveOptionalValue (void *Data) const
Set the value to it's special unset state.
FORCEINLINE void ClearPropertyFlags (EPropertyFlags NewFlags)
FORCEINLINE void ClearValue (void *Data) const
Zeros the value for this property.
FORCEINLINE void ClearValue_InContainer (void *Data, int32 ArrayIndex=0) const
Zeros the value for this property.
template<typename ValueType>
FORCEINLINE ValueType * ContainerPtrToValuePtr (UObject *ContainerPtr, int32 ArrayIndex=0) const
Get the pointer to property value in a supplied 'container'.
template<typename ValueType>
FORCEINLINE ValueType const * ContainerPtrToValuePtr (UObject const *ContainerPtr, int32 ArrayIndex=0) const
template<typename ValueType>
FORCEINLINE ValueType * ContainerPtrToValuePtr (void *ContainerPtr, int32 ArrayIndex=0) const
template<typename ValueType>
FORCEINLINE ValueType const * ContainerPtrToValuePtr (void const *ContainerPtr, int32 ArrayIndex=0) const
template<typename ValueType>
FORCEINLINE ValueType * ContainerPtrToValuePtrForDefaults (UStruct *ContainerClass, UObject *ContainerPtr, int32 ArrayIndex=0) const
template<typename ValueType>
FORCEINLINE ValueType const * ContainerPtrToValuePtrForDefaults (UStruct *ContainerClass, UObject const *ContainerPtr, int32 ArrayIndex=0) const
template<typename ValueType>
FORCEINLINE ValueType * ContainerPtrToValuePtrForDefaults (UStruct *ContainerClass, void *ContainerPtr, int32 ArrayIndex=0) const
template<typename ValueType>
FORCEINLINE ValueType const * ContainerPtrToValuePtrForDefaults (UStruct *ContainerClass, void const *ContainerPtr, int32 ArrayIndex=0) const
bool ContainsFinishDestroy (TArray< const FStructProperty * > &EncounteredStructProps) const
Returns true if the property or any of the child properties should be cleared on FinishDestroy.
FORCEINLINE bool ContainsInstancedObjectProperty () const
Returns true if this property, or in the case of e.g.
virtual bool ContainsObjectReference (TArray< const FStructProperty * > &EncounteredStructProps, EPropertyObjectReferenceType InReferenceType=EPropertyObjectReferenceType::Strong) const
Returns true if this property, or in the case of e.g.
bool ContainsWeakObjectReference () const
Returns true if this property, or in the case of e.g.
virtual EConvertFromTypeResult ConvertFromType (const FPropertyTag &Tag, FStructuredArchive::FSlot Slot, uint8 *Data, UStruct *DefaultsStruct, const uint8 *Defaults)
Allows a property to implement backwards compatibility handling for tagged properties.
FORCEINLINE void CopyCompleteValue (void *Dest, void const *Src) const
Copy the value for all elements of this property.
FORCEINLINE void CopyCompleteValue_InContainer (void *Dest, void const *Src) const
virtual void CopyCompleteValueFromScriptVM (void *Dest, void const *Src) const
Copy the value for all elements of this property.
virtual void CopyCompleteValueFromScriptVM_InContainer (void *OutContainer, void const *InValue) const
virtual void CopyCompleteValueToScriptVM (void *Dest, void const *Src) const
Copy the value for all elements of this property.
virtual void CopyCompleteValueToScriptVM_InContainer (void *OutValue, void const *InContainer) const
Equivalent to the above functions, but using the container and aware of getters/setters when the container has them.
FORCEINLINE void CopySingleValue (void *Dest, void const *Src) const
Copy the value for a single element of this property.
virtual void CopySingleValueFromScriptVM (void *Dest, void const *Src) const
Copy the value for a single element of this property.
virtual void CopySingleValueToScriptVM (void *Dest, void const *Src) const
Copy the value for a single element of this property.
void DestroyAndFreeValue (void *InMemory) const
Destroys and frees memory with a value this property represents.
FORCEINLINE void DestroyValue (void *Dest) const
Destroys the value for this property.
FORCEINLINE void DestroyValue_InContainer (void *Dest) const
Destroys the value for this property.
virtual void EmitIntrusiveOptionalReferenceInfo (UE::GC::FSchemaBuilder &Schema, int32 BaseOffset, TArray< const FStructProperty * > &EncounteredStructProps, UE::GC::FPropertyStack &DebugPath)
For properties returning true from HasIntrusiveUnsetOptionalState which also contain object references, emit information for the garbage collector to safely gather the references from the value whether the optional value is set or unset.
virtual void EmitReferenceInfo (UE::GC::FSchemaBuilder &Schema, int32 BaseOffset, TArray< const FStructProperty * > &EncounteredStructProps, UE::GC::FPropertyStack &DebugPath)
Emits tokens used by realtime garbage collection code to passed in ReferenceTokenStream.
bool ExportText_Direct (FString &ValueStr, const void *Data, const void *Delta, UObject *Parent, int32 PortFlags, UObject *ExportRootScope=nullptr) const
FORCEINLINE bool ExportText_InContainer (int32 Index, FString &ValueStr, const void *Data, const void *Delta, UObject *Parent, int32 PortFlags, UObject *ExportRootScope=nullptr) const
void ExportTextItem_Direct (FString &ValueStr, const void *PropertyValue, const void *DefaultValue, UObject *Parent, int32 PortFlags, UObject *ExportRootScope=nullptr) const
void ExportTextItem_InContainer (FString &ValueStr, const void *Container, const void *DefaultValue, UObject *Parent, int32 PortFlags, UObject *ExportRootScope=nullptr) const
void FinishDestroy (void *Data) const
Applies appropriate finish destroy actions for the property if needed.
void FinishDestroy_InContainer (void *Data) const
Applies appropriate finish destroy actions for the property if needed.
ELifetimeCondition GetBlueprintReplicationCondition () const
virtual FString GetCPPMacroType (FString &ExtendedTypeText) const
int32 GetElementSize () const
virtual FName GetID () const
virtual int32 GetMinAlignment () const
FString GetNameCPP () const
Returns the C++ name of the property, including the _DEPRECATED suffix if the property is deprecated.
FORCEINLINE int32 GetOffset_ForDebug () const
Return offset of property from container base.
FORCEINLINE int32 GetOffset_ForGC () const
Return offset of property from container base.
FORCEINLINE int32 GetOffset_ForInternal () const
Return offset of property from container base.
FORCEINLINE int32 GetOffset_ForUFunction () const
Return offset of property from container base.
FORCEINLINE int32 GetOffset_ReplaceWith_ContainerPtrToValuePtr () const
Return offset of property from container base.
FProperty * GetOwnerProperty ()
Returns the first FProperty in this property's Outer chain that does not have a FProperty for an Outer.
const FProperty * GetOwnerProperty () const
FORCEINLINE EPropertyFlags GetPropertyFlags () const
Returns this property's propertyflags.
FORCEINLINE FProperty * GetRepOwner ()
Returns the replication owner, which is the property itself, or NULL if this isn't important for replication.
void GetSingleValue_InContainer (const void *InContainer, void *OutValue, int32 ArrayIndex) const
Copies a single value to OutValue even if the property represents a static array of values.
FORCEINLINE int32 GetSize () const
FORCEINLINE void GetValue_InContainer (void const *InContainer, void *OutValue) const
virtual void * GetValueAddressAtIndex_Direct (const FProperty *Inner, void *InValueAddress, int32 Index) const
Gets value address at given index inside of a static array or container.
uint32 GetValueTypeHash (const void *Src) const
Returns the hash value for an element of this property.
FORCEINLINE bool HasAllPropertyFlags (uint64 FlagsToCheck) const
Used to safely check whether all of the passed in flags are set.
FORCEINLINE bool HasAnyPropertyFlags (uint64 FlagsToCheck) const
Used to safely check whether any of the passed in flags are set.
virtual bool HasGetter () const
Checks if this property as a native getter function.
virtual bool HasSetter () const
Checks if this property as a native setter function.
virtual bool HasSetterOrGetter () const
Checks if this property as a native setter or getter function.
bool Identical_InContainer (const void *A, const void *B, int32 ArrayIndex=0, uint32 PortFlags=0) const
Determines whether the property values are identical.
const TCHAR * ImportText_Direct (const TCHAR *Buffer, void *PropertyPtr, UObject *OwnerObject, int32 PortFlags, FOutputDevice *ErrorText=(FOutputDevice *) GWarn) const
Import a text value.
const TCHAR * ImportText_InContainer (const TCHAR *Buffer, void *Container, UObject *OwnerObject, int32 PortFlags, FOutputDevice *ErrorText=(FOutputDevice *) GWarn) const
Import a text value.
virtual bool virtual HasIntrusiveUnsetOptionalState() const PURE_VIRTUAL(FProperty void InitializeIntrusiveUnsetOptionalValue (void *Data) const
Returns whether this type has a special state for an unset TOptional meaning the size TOptional<T> and T are the same.
FORCEINLINE void InitializeValue (void *Dest) const
Zeros, copies from the default, or calls the constructor for on the value for this property.
FORCEINLINE void InitializeValue_InContainer (void *Dest) const
Zeros, copies from the default, or calls the constructor for on the value for this property.
virtual void InstanceSubobjects (void *Data, void const *DefaultData, TNotNull< UObject * > Owner, struct FObjectInstancingGraph *InstanceGraph)
Creates new copies of components.
FORCEINLINE bool IsEditorOnlyProperty () const
Editor-only properties are those that only are used with the editor is present or cannot be removed from serialisation.
FORCEINLINE bool IsInContainer (const UStruct *ContainerClass) const
See if the offset of this property is below the supplied container size.
FORCEINLINE bool IsInContainer (int32 ContainerSize) const
See if the offset of this property is below the supplied container size.
virtual bool IsIntrusiveOptionalValueSet (const void *Data) const
Returns whether an optional value of this inner type is unset.
int32 Link (FArchive &Ar)
void LinkWithoutChangingOffset (FArchive &Ar)
virtual bool LoadTypeName (UE::FPropertyTypeName Type, const FPropertyTag *Tag=nullptr)
Restores this property and its owned properties from the type name.
void PerformOperationWithGetter (void *OutContainer, const void *DirectPropertyAddress, TFunctionRef< void(const void *)> DirectValueAccessFunc) const
Helper function for getting container / struct property value and performing operation directly on the value memory.
void PerformOperationWithSetter (void *OutContainer, void *DirectPropertyAddress, TFunctionRef< void(void *)> DirectValueAccessFunc) const
Helper function for setting container / struct property value and performing operation directly on the value memory.
virtual void PostDuplicate (const FField &InField) override
Fixups after duplicating a Field.
virtual void * ResolveVisitedPathInfo (void *Data, const FPropertyVisitorInfo &Info) const
Attempt to resolve the given inner path info against this outer property to get the inner property value.
virtual bool SameType (const FProperty *Other) const
returns true, if Other is property of exactly the same type
virtual void SaveTypeName (UE::FPropertyTypeNameBuilder &Type) const
Saves the type name of this property and its owned properties.
virtual void Serialize (FArchive &Ar) override
void SerializeBinProperty (FStructuredArchive::FSlot Slot, void *Data, int32 ArrayIdx=-1)
Serializes the property with the struct's data residing in Data.
void SerializeNonMatchingBinProperty (FStructuredArchive::FSlot Slot, void *Data, void const *DefaultData, UStruct *DefaultStruct)
Serializes the property with the struct's data residing in Data, unless it matches the default.
void SetBlueprintReplicationCondition (ELifetimeCondition InBlueprintReplicationCondition)
void SetElementSize (int32 NewSize)
FORCEINLINE void SetPropertyFlags (EPropertyFlags NewFlags)
void SetSingleValue_InContainer (void *OutContainer, const void *InValue, int32 ArrayIndex) const
Copies a single value to the property even if the property represents a static array of values.
FORCEINLINE void SetValue_InContainer (void *OutContainer, const void *InValue) const
bool ShouldDuplicateValue () const
Determines whether this property value is eligible for copying when duplicating an object.
bool ShouldPort (uint32 PortFlags=0) const
bool ShouldSerializeValue (FArchive &Ar) const
virtual bool SupportsNetSharedSerialization () const
UE_DEPRECATED (5.7, "Visit is deprecated, please use Visit with context instead.") 1 EPropertyVisitorControlFlow Visit(const FPropertyVisitorData &Data
virtual bool UseBinaryOrNativeSerialization (const FArchive &Ar) const
bool ValidateImportFlags (uint32 PortFlags, FOutputDevice *ErrorText=NULL) const
Verify that modifying this property's value via ImportText is allowed.
EPropertyVisitorControlFlow Visit (const FPropertyVisitorData &Data, const TFunctionRef< EPropertyVisitorControlFlow(const FPropertyVisitorContext &)> InFunc) const
Visits this property and allows recursion into the inner properties This method allows callers to visit inner properties without knowing about its container type as opposed to TPropertyIterator.
virtual EPropertyVisitorControlFlow Visit (FPropertyVisitorContext &Context, const TFunctionRef< EPropertyVisitorControlFlow(const FPropertyVisitorContext &)> InFunc) const
Visits this property and allows recursion into the inner properties This method allows callers to visit inner properties without knowing about its container type as opposed to TPropertyIterator.
Public Member Functions inherited from FField
FField (EInternal InInernal, FFieldClass *InClass)
FField (FFieldVariant InOwner, const FName &InName, EObjectFlags InObjectFlags)
virtual ~FField ()
virtual void AddCppProperty (FProperty *Property)
virtual void AddReferencedObjects (FReferenceCollector &Collector)
void AppendName (FString &ResultString) const
virtual void BeginDestroy ()
virtual void Bind ()
void ClearFlags (EObjectFlags NewFlags)
FString GetAuthoredName () const
Returns a human readable string that was assigned to this field at creation.
uint64 GetCastFlags () const
FFieldClass * GetClass () const
virtual SIZE_T GetFieldSize () const
EObjectFlags GetFlags () const
Retrieve the object flags directly.
FORCEINLINE FName GetFName () const
FString GetFullName () const
virtual FField * GetInnerFieldByName (const FName &InName)
Returns an inner field by name if the field has any.
virtual void GetInnerFields (TArray< FField * > &OutFields)
Fills the provided array with all inner fields this field owns (recursively)
FLinkerLoad * GetLinker () const
FORCEINLINE FString GetName () const
FORCEINLINE void GetName (FString &OutName) const
UPackage * GetOutermost () const
Goes up the outer chain to look for the outermost package.
template<typename T>
T * GetOwner () const
template<typename T>
FUNCTION_NON_NULL_RETURN_START T * GetOwnerChecked () const FUNCTION_NON_NULL_RETURN_END
UClass * GetOwnerClass () const
Goes up the outer chain to look for a UClass.
UStruct * GetOwnerStruct () const
Goes up the outer chain to look for a UStruct.
UField * GetOwnerUField () const
Goes up the outer chain to look for a UField.
FORCEINLINE UObject * GetOwnerUObject () const
Goes up the outer chain to look for a UObject.
FFieldVariant GetOwnerVariant () const
Gets the owner container for this field.
void GetPathName (const UObject *StopOuter, FStringBuilderBase &ResultString) const
FString GetPathName (const UObject *StopOuter=nullptr) const
virtual void GetPreloadDependencies (TArray< UObject * > &OutDeps)
template<typename T>
T * GetTypedOwner () const
FField * GetTypedOwner (FFieldClass *Target) const
Goes up the outer chain to look for the outer of the specified type.
UObject * GetTypedOwner (UClass *Target) const
Goes up the outer chain to look for the outer of the specified type.
bool HasAllFlags (EObjectFlags FlagsToCheck) const
Used to safely check whether all of the passed in flags are set.
bool HasAnyFlags (EObjectFlags FlagsToCheck) const
Used to safely check whether any of the passed in flags are set.
FORCEINLINE UObject * InternalGetOwnerAsUObjectUnsafe () const
Internal function for quickly getting the owner of this object as UObject.
template<typename T>
bool IsA () const
bool IsA (const FFieldClass *FieldType) const
bool IsIn (const FField *InOwner) const
bool IsIn (const UObject *InOwner) const
bool IsNative () const
bool IsRooted () const
bool IsValidLowLevel () const
virtual void PostLoad ()
void Rename (const FName &NewName)
void SetFlags (EObjectFlags NewFlags)
UE_DEPRECATED (5.0, "HasAllCastFlags is deprecated. Not all FField has CastFlag. Use IsA instead.") inline bool HasAllCastFlags(const uint64 InCastFlags) const
UE_DEPRECATED (5.0, "HasAnyCastFlags is deprecated. Not all FField has CastFlag. Use IsA instead.") inline bool HasAnyCastFlags(const uint64 InCastFlags) const
Static Public Member Functions
static FName FindRedirectedPropertyName (const UStruct *ObjectStruct, FName OldName)
Gets a redirected property name, will return NAME_None if no redirection was found.
static const TCHAR * ImportSingleProperty (const TCHAR *Str, void *DestData, const UStruct *ObjectStruct, UObject *SubobjectOuter, int32 PortFlags, FOutputDevice *Warn, TArray< struct FDefinedProperty > &DefinedProperties)
parses and imports a text definition of a single property's value (if array, may be an individual element) also includes parsing of special operations for array properties (Add/Remove/RemoveIndex/Empty)
Static Public Member Functions inherited from FField
static FField * Construct (const FFieldVariant &InOwner, const FName &InName, EObjectFlags InFlags)
Constructs a new field given its class.
static FField * Construct (const FName &FieldTypeName, const FFieldVariant &InOwner, const FName &InName, EObjectFlags InFlags)
Constructs a new field given the name of its class.
static FField * Duplicate (const FField *InField, FFieldVariant DestOwner, const FName DestName=NAME_None, EObjectFlags FlagMask=RF_AllFlags, EInternalObjectFlags InternalFlagsMask=EInternalObjectFlags_AllFlags)
Duplicates an FField.
static FName GenerateFFieldName (FFieldVariant InOwner, FFieldClass *InClass)
Generates a name for a Field of a given type.
static FFieldClass * StaticClass ()
static constexpr uint64 StaticClassCastFlags ()
static constexpr uint64 StaticClassCastFlagsPrivate ()
static FField * TryConstruct (const FName &FieldTypeName, const FFieldVariant &InOwner, const FName &InName, EObjectFlags InFlags)
Tries to construct a new field given the name of its class.
Data Fields
const TFunctionRef< EPropertyVisitorControlFlow(const FPropertyVisitorPath &, const FPropertyVisitorData &)> InFunc const
FProperty * DestructorLinkNext
In memory only: Linked list of properties requiring destruction.
virtual FString GetCPPType (FString *ExtendedTypeText=NULL, uint32 CPPExportFlags=0) const PURE_VIRTUAL(FProperty
Returns the text to use for exporting this property to header file.
virtual bool Identical (const void *A, const void *B, uint32 PortFlags=0) const PURE_VIRTUAL(FProperty
Determines whether the property values are identical.
virtual void virtual SerializeItem(FStructuredArchive::FSlot Slot, void *Value, void const *Defaults=NULL) const PURE_VIRTUAL(FProperty boo NetSerializeItem)(FArchive &Ar, UPackageMap *Map, void *Data, TArray< uint8 > *MetaData=NULL) const
FProperty * NextRef
In memory only: Linked list of object reference properties from most-derived to base.
FProperty * PostConstructLinkNext
In memory only: Linked list of properties requiring post constructor initialization.
EPropertyFlags PropertyFlags
FProperty * PropertyLinkNext
In memory only: Linked list of properties from most-derived to base.
uint16 RepIndex
FName RepNotifyFunc
Data Fields inherited from FField
EObjectFlags FlagsPrivate
Object flags.
FName NamePrivate
Name of this field.
FField * Next
Next Field in the linked list.
FFieldVariant Owner
Owner of this field.
Protected Member Functions
virtual void ClearValueInternal (void *Data) const
virtual bool ContainsClearOnFinishDestroyInternal (TArray< const FStructProperty * > &EncounteredStructProps) const
virtual void CopyValuesInternal (void *Dest, void const *Src, int32 Count) const
virtual void DestroyValueInternal (void *Dest) const
virtual void FinishDestroyInternal (void *Data) const
virtual uint32 GetValueTypeHashInternal (const void *Src) const
void Init ()
Initializes internal state.
virtual void InitializeValueInternal (void *Dest) const
virtual void LinkInternal (FArchive &Ar)
FORCEINLINE void * PointerToValuePtr (void const *ContainerOrPropertyPtr, EPropertyPointerType PropertyPointerType, int32 ArrayIndex=0) const
void SetOffset_Internal (int32 NewOffset)
Set the alignment offset for this property - added for FMapProperty.
Protected Member Functions inherited from FField
void SetFlagsTo (EObjectFlags NewFlags)
Set the object flags directly.
Protected Attributes
virtual void virtual ExportText_Internal(FString &ValueStr, const void *PropertyValueOrContainer, EPropertyPointerType PointerType, const void *DefaultValue, UObject *Parent, int32 PortFlags, UObject *ExportRootScope=nullptr) const PURE_VIRTUAL(FProperty const TCHAR ImportText_Internal)(const TCHAR *Buffer, void *ContainerOrPropertyPtr, EPropertyPointerType PointerType, UObject *OwnerObject, int32 PortFlags, FOutputDevice *ErrorText) const PURE_VIRTUAL(FProperty
Private Member Functions
FORCEINLINE void * ContainerUObjectPtrToValuePtrInternal (UObject *ContainerPtr, int32 ArrayIndex) const
FORCEINLINE void * ContainerVoidPtrToValuePtrInternal (void *ContainerPtr, int32 ArrayIndex) const
DECLARE_FIELD_API (FProperty, FField, CASTCLASS_FProperty, 1) int32 ArrayDim
int32 SetupOffset ()
Set the alignment offset for this property.
UE_DEPRECATED (5.5, "Use GetElementSize/SetElementSize instead.") int32 ElementSize
Private Attributes
TEnumAsByte< ELifetimeCondition > BlueprintReplicationCondition
int32 Offset_Internal
Friends
class FMapProperty
void UE::CoreUObject::Private::ExportEnumToBuffer (const UEnum *Enum, const FProperty *Prop, const FNumericProperty *NumericProp, FString &ValueStr, const void *PropertyValueOrContainer, EPropertyPointerType PropertyPointerType, const void *DefaultValue, UObject *Parent, int32 PortFlags, UObject *ExportRootScope)
const TCHAR * UE::CoreUObject::Private::ImportEnumFromBuffer (UEnum *Enum, const FProperty *PropertyToSet, const FNumericProperty *UnderlyingProp, const TCHAR *PropertyClassName, const TCHAR *Buffer, void *ContainerOrPropertyPtr, EPropertyPointerType PropertyPointerType, FOutputDevice *ErrorText)
class UEProperty_Private::FProperty_DoNotUse
Additional Inherited Members
Public Types inherited from FField
typedef FField BaseFieldClass
typedef FFieldClass FieldTypeClass
using FLinkedListBuilder = TLinkedListBuilder<FField>
typedef FField Super
typedef FField ThisClass
Detailed Description
Definition at line 180 of file UnrealType.h.
Constructor & Destructor Documentation
FProperty() [1/3]
FProperty::FProperty (FFieldVariant InOwner, const FName & InName, EObjectFlags InObjectFlags)
References InName.
Referenced by FEnumProperty::AddCppProperty(), FOptionalProperty::AddCppProperty(), FNumericProperty::DECLARE_FIELD_API(), DECLARE_FIELD_API(), FStructProperty::DECLARE_FIELD_API(), FObjectPropertyBase::FindImportedObject(), FStructProperty::FindInnerPropertyInstance(), GetOwnerProperty(), GetOwnerProperty(), GetRepOwner(), GetValueAddressAtIndex_Direct(), FObjectPropertyBase::ParseObjectPropertyValue(), FEnumProperty::SameType(), FObjectPropertyBase::SameType(), FOptionalProperty::SameType(), SameType(), FStructProperty::SameType(), FOptionalProperty::SetValueProperty(), UE::CoreUObject::Private::ExportEnumToBuffer, and UE::CoreUObject::Private::ImportEnumFromBuffer.
FProperty() [2/3]
FProperty::FProperty (FFieldVariant InOwner, const UECodeGen_Private::FPropertyParamsBaseWithOffset & Prop, EPropertyFlags AdditionalPropertyFlags = CPF_None)
Constructor used for constructing compiled-in properties.
Parameters
InOwner Owner of the property
PropBase Pointer to the compiled in structure describing the property
FProperty() [3/3]
FProperty::FProperty (FFieldVariant InOwner, const UECodeGen_Private::FPropertyParamsBaseWithoutOffset & Prop, EPropertyFlags AdditionalPropertyFlags = CPF_None)
Constructor used for constructing compiled-in properties.
Parameters
InOwner Owner of the property
PropBase Pointer to the compiled in structure describing the property
Member Function Documentation
AllocateAndInitializeValue()
void * FProperty::AllocateAndInitializeValue () const
Allocates and initializes memory to hold a value this property represents.
Referenced by FObjectPropertyBase::GetWrappedUObjectPtrValues(), and FObjectPropertyBase::SetWrappedUObjectPtrValues().
CallGetter()
virtual void FProperty::CallGetter (const void * Container, void * OutValue) const inline virtual
Calls the native getter function for this property.
Parameters
Container Pointer to the owner of this property (either UObject or struct)
OutValue Pointer to the value where the existing property value will be copied to
Definition at line 324 of file UnrealType.h.
References checkf, Container, FField::GetFullName(), HasGetter(), and TEXT.
Referenced by GetValue_InContainer().
CallSetter()
virtual void FProperty::CallSetter (void * Container, const void * InValue) const inline virtual
Calls the native setter function for this property.
Parameters
Container Pointer to the owner of this property (either UObject or struct)
InValue Pointer to the new value
Definition at line 315 of file UnrealType.h.
References checkf, Container, FField::GetFullName(), HasSetter(), and TEXT.
Referenced by SetValue_InContainer().
CanSerializeFromTypeName()
virtual bool FProperty::CanSerializeFromTypeName (UE::FPropertyTypeName Type) const virtual
Returns true if the type of this property matches the type name.
Reimplemented in FArrayProperty, FByteProperty, FEnumProperty, FMapProperty, FOptionalProperty, FSetProperty, and FStructProperty.
ClearIntrusiveOptionalValue()
virtual void FProperty::ClearIntrusiveOptionalValue (void * Data) const virtual
Set the value to it's special unset state.
Equivalent to TOptional<T>::Reset. Only valid to call if HasIntrusiveUnsetOptionalState returns true.
See also
operator=(FIntrusiveUnsetOptionalState)
Parameters
Data Address of the alue, already offset.
Reimplemented in FArrayProperty, FMapProperty, FObjectProperty, FSetProperty, FStructProperty, TProperty< double, FNumericProperty >, TProperty< FFieldPath, FProperty >, TProperty< FLazyObjectPtr, FObjectPropertyBase >, TProperty< float, FNumericProperty >, TProperty< FMulticastScriptDelegate, FMulticastDelegateProperty >, TProperty< FName, FProperty >, TProperty< FScriptArray, FProperty >, TProperty< FScriptDelegate, FProperty >, TProperty< FScriptInterface, FProperty >, TProperty< FScriptMap, FProperty >, TProperty< FScriptSet, FProperty >, TProperty< FSoftObjectPtr, FObjectPropertyBase >, TProperty< FSparseDelegate, FMulticastDelegateProperty >, TProperty< FText, FProperty >, TProperty< FWeakObjectPtr, FObjectPropertyBase >, TProperty< int16, FNumericProperty >, TProperty< int32, FNumericProperty >, TProperty< int64, FNumericProperty >, TProperty< int8, FNumericProperty >, TProperty< InTCppType, FMulticastDelegateProperty >, TProperty< InTCppType, FObjectPropertyBase >, TProperty< TObjectPtr< UObject >, FObjectPropertyBase >, TProperty< uint16, FNumericProperty >, TProperty< uint32, FNumericProperty >, TProperty< uint64, FNumericProperty >, and TProperty< uint8, FNumericProperty >.
References ClearIntrusiveOptionalValue(), and const.
Referenced by ClearIntrusiveOptionalValue().
ClearPropertyFlags()
FORCEINLINE void FProperty::ClearPropertyFlags (EPropertyFlags NewFlags) inline
Definition at line 1218 of file UnrealType.h.
References FORCEINLINE, and PropertyFlags.
ClearValue()
FORCEINLINE void FProperty::ClearValue (void * Data) const inline
Zeros the value for this property.
The existing data is assumed valid (so for example this calls FString::Empty) This only does one item and not the entire fixed size array.
Parameters
Data the address of the value for this property that should be cleared.
Definition at line 931 of file UnrealType.h.
References ClearValueInternal(), FORCEINLINE, GetElementSize(), HasAllPropertyFlags(), and FMemory::Memzero().
Referenced by FObjectProperty::ClearIntrusiveOptionalValue(), and FObjectProperty::InitializeIntrusiveUnsetOptionalValue().
ClearValue_InContainer()
FORCEINLINE void FProperty::ClearValue_InContainer (void * Data, int32 ArrayIndex = 0) const inline
Zeros the value for this property.
The existing data is assumed valid (so for example this calls FString::Empty) This only does one item and not the entire fixed size array.
Parameters
Data the address of the container of the value for this property that should be cleared.
Definition at line 948 of file UnrealType.h.
References ClearValueInternal(), ContainerPtrToValuePtr(), FORCEINLINE, GetElementSize(), HasAllPropertyFlags(), and FMemory::Memzero().
ClearValueInternal()
virtual void FProperty::ClearValueInternal (void * Data) const protected virtual
Reimplemented in FArrayProperty, FBoolProperty, FMapProperty, FOptionalProperty, FSetProperty, FStructProperty, TProperty< double, FNumericProperty >, TProperty< FFieldPath, FProperty >, TProperty< FLazyObjectPtr, FObjectPropertyBase >, TProperty< float, FNumericProperty >, TProperty< FMulticastScriptDelegate, FMulticastDelegateProperty >, TProperty< FName, FProperty >, TProperty< FScriptArray, FProperty >, TProperty< FScriptDelegate, FProperty >, TProperty< FScriptInterface, FProperty >, TProperty< FScriptMap, FProperty >, TProperty< FScriptSet, FProperty >, TProperty< FSoftObjectPtr, FObjectPropertyBase >, TProperty< FSparseDelegate, FMulticastDelegateProperty >, TProperty< FText, FProperty >, TProperty< FWeakObjectPtr, FObjectPropertyBase >, TProperty< int16, FNumericProperty >, TProperty< int32, FNumericProperty >, TProperty< int64, FNumericProperty >, TProperty< int8, FNumericProperty >, TProperty< InTCppType, FMulticastDelegateProperty >, TProperty< InTCppType, FObjectPropertyBase >, TProperty< TObjectPtr< UObject >, FObjectPropertyBase >, TProperty< uint16, FNumericProperty >, TProperty< uint32, FNumericProperty >, TProperty< uint64, FNumericProperty >, and TProperty< uint8, FNumericProperty >.
Referenced by ClearValue(), and ClearValue_InContainer().
ContainerPtrToValuePtr() [1/4]
template<typename ValueType> FORCEINLINE ValueType * FProperty::ContainerPtrToValuePtr (UObject * ContainerPtr, int32 ArrayIndex = 0) const inline
Get the pointer to property value in a supplied 'container'.
You can only call this function on a UObject* or a uint8*. If the property you want is a 'top level' UObject property, you must call the function passing in a UObject* and not a uint8*. There are checks inside the function to vertify this.
Parameters
ContainerPtr UObject* or uint8* to container of property value
ArrayIndex In array case, index of array element we want
Definition at line 742 of file UnrealType.h.
References ContainerUObjectPtrToValuePtrInternal(), and FORCEINLINE.
Referenced by FComponentEditorUtils::ApplyDefaultValueChange(), FComponentEditorUtils::ApplyDefaultValueChange(), ClearValue_InContainer(), ContainerPtrToValuePtr(), ContainerPtrToValuePtr(), ContainerPtrToValuePtrForDefaults(), ContainerPtrToValuePtrForDefaults(), ContainerPtrToValuePtrForDefaults(), ContainerPtrToValuePtrForDefaults(), CopyCompleteValue_InContainer(), DestroyValue_InContainer(), ExportText_InContainer(), FinishDestroy_InContainer(), GetNodeFromPropertyIndex(), FBoolProperty::GetPropertyValue_InContainer(), TProperty< InTCppType, FObjectPropertyBase >::GetPropertyValuePtr_InContainer(), TProperty< InTCppType, FObjectPropertyBase >::GetPropertyValuePtr_InContainer(), FObjectPropertyBase::GetWrappedUObjectPtrValues(), Identical_InContainer(), InitializeValue_InContainer(), FObjectPropertyBase::LoadObjectPropertyValue_InContainer(), FGameModeInfoCustomizer::OnGetDefaultClass(), FGameModeInfoCustomizer::OnSetDefaultClass(), SerializeBinProperty(), SerializeNonMatchingBinProperty(), FBoolProperty::SetPropertyValue_InContainer(), FObjectPropertyBase::SetWrappedUObjectPtrValues(), and USTRUCT().
ContainerPtrToValuePtr() [2/4]
template<typename ValueType> FORCEINLINE ValueType const * FProperty::ContainerPtrToValuePtr (UObject const * ContainerPtr, int32 ArrayIndex = 0) const inline
Definition at line 752 of file UnrealType.h.
References ContainerPtrToValuePtr(), and FORCEINLINE.
ContainerPtrToValuePtr() [3/4]
template<typename ValueType> FORCEINLINE ValueType * FProperty::ContainerPtrToValuePtr (void * ContainerPtr, int32 ArrayIndex = 0) const inline
Definition at line 747 of file UnrealType.h.
References ContainerVoidPtrToValuePtrInternal(), and FORCEINLINE.
ContainerPtrToValuePtr() [4/4]
template<typename ValueType> FORCEINLINE ValueType const * FProperty::ContainerPtrToValuePtr (void const * ContainerPtr, int32 ArrayIndex = 0) const inline
Definition at line 757 of file UnrealType.h.
References ContainerPtrToValuePtr(), and FORCEINLINE.
ContainerPtrToValuePtrForDefaults() [1/4]
template<typename ValueType> FORCEINLINE ValueType * FProperty::ContainerPtrToValuePtrForDefaults (UStruct * ContainerClass, UObject * ContainerPtr, int32 ArrayIndex = 0) const inline
Definition at line 765 of file UnrealType.h.
References ContainerPtrToValuePtr(), FORCEINLINE, and IsInContainer().
Referenced by ExportText_InContainer(), and SerializeNonMatchingBinProperty().
ContainerPtrToValuePtrForDefaults() [2/4]
template<typename ValueType> FORCEINLINE ValueType const * FProperty::ContainerPtrToValuePtrForDefaults (UStruct * ContainerClass, UObject const * ContainerPtr, int32 ArrayIndex = 0) const inline
Definition at line 783 of file UnrealType.h.
References ContainerPtrToValuePtr(), FORCEINLINE, and IsInContainer().
ContainerPtrToValuePtrForDefaults() [3/4]
template<typename ValueType> FORCEINLINE ValueType * FProperty::ContainerPtrToValuePtrForDefaults (UStruct * ContainerClass, void * ContainerPtr, int32 ArrayIndex = 0) const inline
Definition at line 774 of file UnrealType.h.
References ContainerPtrToValuePtr(), FORCEINLINE, and IsInContainer().
ContainerPtrToValuePtrForDefaults() [4/4]
template<typename ValueType> FORCEINLINE ValueType const * FProperty::ContainerPtrToValuePtrForDefaults (UStruct * ContainerClass, void const * ContainerPtr, int32 ArrayIndex = 0) const inline
Definition at line 792 of file UnrealType.h.
References ContainerPtrToValuePtr(), FORCEINLINE, and IsInContainer().
ContainerUObjectPtrToValuePtrInternal()
FORCEINLINE void * FProperty::ContainerUObjectPtrToValuePtrInternal (UObject * ContainerPtr, int32 ArrayIndex) const inline private
Definition at line 688 of file UnrealType.h.
References check, checkf, FORCEINLINE, FField::GetClass(), GetElementSize(), FField::GetName(), FField::GetOwner(), FField::IsA(), FField::IsValidLowLevel(), Offset_Internal, and TEXT.
Referenced by ContainerPtrToValuePtr().
ContainerVoidPtrToValuePtrInternal()
FORCEINLINE void * FProperty::ContainerVoidPtrToValuePtrInternal (void * ContainerPtr, int32 ArrayIndex) const inline private
Definition at line 674 of file UnrealType.h.
References check, checkf, FORCEINLINE, GetElementSize(), FField::GetOwner(), Offset_Internal, and TEXT.
Referenced by ContainerPtrToValuePtr(), GetValue_InContainer(), and SetValue_InContainer().
ContainsClearOnFinishDestroyInternal()
virtual bool FProperty::ContainsClearOnFinishDestroyInternal (TArray< const FStructProperty * > & EncounteredStructProps) const protected virtual
Reimplemented in FArrayProperty, FMapProperty, FOptionalProperty, FSetProperty, and FStructProperty.
Referenced by ContainsFinishDestroy().
ContainsFinishDestroy()
bool FProperty::ContainsFinishDestroy (TArray< const FStructProperty * > & EncounteredStructProps) const inline
Returns true if the property or any of the child properties should be cleared on FinishDestroy.
Definition at line 996 of file UnrealType.h.
References ContainsClearOnFinishDestroyInternal(), and PropertyFlags.
ContainsInstancedObjectProperty()
FORCEINLINE bool FProperty::ContainsInstancedObjectProperty () const inline
Returns true if this property, or in the case of e.g.
array or struct properties any sub- property, contains a UObject reference that is marked CPF_NeedCtorLink (i.e. instanced keyword).
Returns
true if property (or sub- properties) contain a FObjectProperty that is marked CPF_NeedCtorLink, false otherwise
Definition at line 1136 of file UnrealType.h.
References FORCEINLINE, and PropertyFlags.
ContainsObjectReference()
virtual bool FProperty::ContainsObjectReference (TArray< const FStructProperty * > & EncounteredStructProps, EPropertyObjectReferenceType InReferenceType = EPropertyObjectReferenceType::Strong) const virtual
Returns true if this property, or in the case of e.g.
array or struct properties any sub- property, contains a UObject reference.
Parameters
EncounteredStructProps used to check for recursion in arrays
InReferenceType type of object reference (strong / weak)
Returns
true if property (or sub- properties) contains the specified type of UObject reference, false otherwise
Reimplemented in FArrayProperty, FDelegateProperty, FFieldPathProperty, FInterfaceProperty, FMapProperty, FMulticastDelegateProperty, FOptionalProperty, FSetProperty, FStructProperty, TFObjectPropertyBase< InTCppType >, TFObjectPropertyBase< FLazyObjectPtr >, TFObjectPropertyBase< FSoftObjectPtr >, TFObjectPropertyBase< FWeakObjectPtr >, and TFObjectPropertyBase< TObjectPtr< UObject > >.
Referenced by ContainsWeakObjectReference().
ContainsWeakObjectReference()
bool FProperty::ContainsWeakObjectReference () const inline
Returns true if this property, or in the case of e.g.
array or struct properties any sub- property, contains a weak UObject reference.
Returns
true if property (or sub- properties) contain a weak UObject reference, false otherwise
Definition at line 1124 of file UnrealType.h.
References ContainsObjectReference().
ConvertFromType()
virtual EConvertFromTypeResult FProperty::ConvertFromType (const FPropertyTag & Tag, FStructuredArchive::FSlot Slot, uint8 * Data, UStruct * DefaultsStruct, const uint8 * Defaults) virtual
Allows a property to implement backwards compatibility handling for tagged properties.
Parameters
Tag property tag of the loading data
Ar the archive the data is being loaded from
Data a pointer to the container to write the loaded data to
DefaultsStruct
Defaults if available, a pointer to the container containing the default value for this property, or null
Returns
A state which tells the tagged property system how the property dealt with the data. Converted: the function handled conversion. CannotConvert: the tag is not something that the property can convert. Serialized: the function handled serialization without conversion. UseSerializeItem: no conversion was done on the property - this can mean that the tag is correct and normal serialization applies or that the tag is incompatible.
Reimplemented in FArrayProperty, FBoolProperty, FByteProperty, FEnumProperty, FFieldPathProperty, FMapProperty, FMulticastDelegateProperty, FNameProperty, FObjectProperty, FOptionalProperty, FSetProperty, FSoftObjectProperty, FStructProperty, FTextProperty, TProperty_Numeric< double >, TProperty_Numeric< float >, TProperty_Numeric< int16 >, TProperty_Numeric< int32 >, TProperty_Numeric< int64 >, TProperty_Numeric< int8 >, TProperty_Numeric< uint16 >, TProperty_Numeric< uint32 >, TProperty_Numeric< uint64 >, and TProperty_Numeric< uint8 >.
CopyCompleteValue()
FORCEINLINE void FProperty::CopyCompleteValue (void * Dest, void const * Src) const inline
Copy the value for all elements of this property.
Parameters
Dest the address where the value should be copied to. This should always correspond to the BASE + OFFSET, where BASE = (for member properties) the address of the UObject which contains this data, (for locals/parameters) the address of the space allocated for the function's locals OFFSET = the Offset of this FProperty
Src the address of the value to copy from. should be evaluated the same way as Dest
InstancingParams contains information about instancing (if any) to perform
Definition at line 856 of file UnrealType.h.
References CopyValuesInternal(), FORCEINLINE, GetElementSize(), FMemory::Memcpy(), and PropertyFlags.
Referenced by CopyCompleteValue_InContainer(), FRigVMMemoryHandle::GetData_Internal(), GetValue_InContainer(), and SetValue_InContainer().
CopyCompleteValue_InContainer()
FORCEINLINE void FProperty::CopyCompleteValue_InContainer (void * Dest, void const * Src) const inline
Definition at line 870 of file UnrealType.h.
References ContainerPtrToValuePtr(), CopyCompleteValue(), and FORCEINLINE.
CopyCompleteValueFromScriptVM()
virtual void FProperty::CopyCompleteValueFromScriptVM (void * Dest, void const * Src) const virtual
Copy the value for all elements of this property.
From the script VM.
Parameters
Dest the address where the value should be copied to. This should always correspond to the BASE + OFFSET, where BASE = (for member properties) the address of the UObject which contains this data, (for locals/parameters) the address of the space allocated for the function's locals OFFSET = the Offset of this FProperty
Src the address of the value to copy from. should be evaluated the same way as Dest
Reimplemented in FLazyObjectProperty, FObjectProperty, and FWeakObjectProperty.
CopyCompleteValueFromScriptVM_InContainer()
virtual void FProperty::CopyCompleteValueFromScriptVM_InContainer (void * OutContainer, void const * InValue) const virtual
Reimplemented in FLazyObjectProperty, FObjectProperty, and FWeakObjectProperty.
CopyCompleteValueToScriptVM()
virtual void FProperty::CopyCompleteValueToScriptVM (void * Dest, void const * Src) const virtual
Copy the value for all elements of this property.
To the script VM.
Parameters
Dest the address where the value should be copied to. This should always correspond to the BASE + OFFSET, where BASE = (for member properties) the address of the UObject which contains this data, (for locals/parameters) the address of the space allocated for the function's locals OFFSET = the Offset of this FProperty
Src the address of the value to copy from. should be evaluated the same way as Dest
Reimplemented in FLazyObjectProperty, FObjectProperty, and FWeakObjectProperty.
CopyCompleteValueToScriptVM_InContainer()
virtual void FProperty::CopyCompleteValueToScriptVM_InContainer (void * OutValue, void const * InContainer) const virtual
Equivalent to the above functions, but using the container and aware of getters/setters when the container has them.
Reimplemented in FLazyObjectProperty, FObjectProperty, and FWeakObjectProperty.
References InContainer.
CopySingleValue()
FORCEINLINE void FProperty::CopySingleValue (void * Dest, void const * Src) const inline
Copy the value for a single element of this property.
Parameters
Dest the address where the value should be copied to. This should always correspond to the BASE + OFFSET + INDEX * SIZE, where BASE = (for member properties) the address of the UObject which contains this data, (for locals/parameters) the address of the space allocated for the function's locals OFFSET = the Offset of this FProperty INDEX = the index that you want to copy. for properties which are not arrays, this should always be 0 SIZE = the ElementSize of this FProperty
Src the address of the value to copy from. should be evaluated the same way as Dest
InstancingParams contains information about instancing (if any) to perform
Definition at line 822 of file UnrealType.h.
References CopyValuesInternal(), FORCEINLINE, GetElementSize(), FMemory::Memcpy(), and PropertyFlags.
CopySingleValueFromScriptVM()
virtual void FProperty::CopySingleValueFromScriptVM (void * Dest, void const * Src) const virtual
Copy the value for a single element of this property.
From the script VM.
Parameters
Dest the address where the value should be copied to. This should always correspond to the BASE + OFFSET + INDEX * SIZE, where BASE = (for member properties) the address of the UObject which contains this data, (for locals/parameters) the address of the space allocated for the function's locals OFFSET = the Offset of this FProperty INDEX = the index that you want to copy. for properties which are not arrays, this should always be 0 SIZE = the ElementSize of this FProperty
Src the address of the value to copy from. should be evaluated the same way as Dest
Reimplemented in FLazyObjectProperty, FObjectProperty, and FWeakObjectProperty.
CopySingleValueToScriptVM()
virtual void FProperty::CopySingleValueToScriptVM (void * Dest, void const * Src) const virtual
Copy the value for a single element of this property.
To the script VM.
Parameters
Dest the address where the value should be copied to. This should always correspond to the BASE + OFFSET + INDEX * SIZE, where BASE = (for member properties) the address of the UObject which contains this data, (for locals/parameters) the address of the space allocated for the function's locals OFFSET = the Offset of this FProperty INDEX = the index that you want to copy. for properties which are not arrays, this should always be 0 SIZE = the ElementSize of this FProperty
Src the address of the value to copy from. should be evaluated the same way as Dest
Reimplemented in FLazyObjectProperty, FObjectProperty, and FWeakObjectProperty.
Referenced by FScriptSetHelper::AddElement().
CopyValuesInternal()
virtual void FProperty::CopyValuesInternal (void * Dest, void const * Src, int32 Count) const protected virtual
Reimplemented in FArrayProperty, FBoolProperty, FMapProperty, FObjectProperty, FOptionalProperty, FSetProperty, FStructProperty, TProperty< double, FNumericProperty >, TProperty< FFieldPath, FProperty >, TProperty< FLazyObjectPtr, FObjectPropertyBase >, TProperty< float, FNumericProperty >, TProperty< FMulticastScriptDelegate, FMulticastDelegateProperty >, TProperty< FName, FProperty >, TProperty< FScriptArray, FProperty >, TProperty< FScriptDelegate, FProperty >, TProperty< FScriptInterface, FProperty >, TProperty< FScriptMap, FProperty >, TProperty< FScriptSet, FProperty >, TProperty< FSoftObjectPtr, FObjectPropertyBase >, TProperty< FSparseDelegate, FMulticastDelegateProperty >, TProperty< FText, FProperty >, TProperty< FWeakObjectPtr, FObjectPropertyBase >, TProperty< int16, FNumericProperty >, TProperty< int32, FNumericProperty >, TProperty< int64, FNumericProperty >, TProperty< int8, FNumericProperty >, TProperty< InTCppType, FMulticastDelegateProperty >, TProperty< InTCppType, FObjectPropertyBase >, TProperty< TObjectPtr< UObject >, FObjectPropertyBase >, TProperty< uint16, FNumericProperty >, TProperty< uint32, FNumericProperty >, TProperty< uint64, FNumericProperty >, and TProperty< uint8, FNumericProperty >.
References Count.
Referenced by CopyCompleteValue(), and CopySingleValue().
DECLARE_FIELD_API()
FProperty::DECLARE_FIELD_API (FProperty , FField , CASTCLASS_FProperty , 1) private
References FField::FField(), FProperty(), CASTCLASS_FProperty, and UE_API.
DestroyAndFreeValue()
void FProperty::DestroyAndFreeValue (void * InMemory) const
Destroys and frees memory with a value this property represents.
Referenced by FObjectPropertyBase::GetWrappedUObjectPtrValues(), and FObjectPropertyBase::SetWrappedUObjectPtrValues().
DestroyValue()
FORCEINLINE void FProperty::DestroyValue (void * Dest) const inline
Destroys the value for this property.
The existing data is assumed valid (so for example this calls FString::Empty) This does the entire fixed size array.
Parameters
Dest the address of the value for this property that should be destroyed.
Definition at line 968 of file UnrealType.h.
References DestroyValueInternal(), FORCEINLINE, and PropertyFlags.
Referenced by FDefaultConstructedPropertyElement::FDefaultConstructedPropertyElement(), FScriptSetHelper::AddElement(), UBlueprintMapLibrary::DECLARE_FUNCTION(), UBlueprintMapLibrary::DECLARE_FUNCTION(), UBlueprintMapLibrary::DECLARE_FUNCTION(), UBlueprintMapLibrary::DECLARE_FUNCTION(), UBlueprintMapLibrary::DECLARE_FUNCTION(), UBlueprintSetLibrary::DECLARE_FUNCTION(), UBlueprintSetLibrary::DECLARE_FUNCTION(), UBlueprintSetLibrary::DECLARE_FUNCTION(), UBlueprintSetLibrary::DECLARE_FUNCTION(), UKismetArrayLibrary::DECLARE_FUNCTION(), UKismetArrayLibrary::DECLARE_FUNCTION(), UKismetArrayLibrary::DECLARE_FUNCTION(), UKismetArrayLibrary::DECLARE_FUNCTION(), UKismetArrayLibrary::DECLARE_FUNCTION(), UKismetArrayLibrary::DECLARE_FUNCTION(), UKismetArrayLibrary::DECLARE_FUNCTION(), and UKismetArrayLibrary::DECLARE_FUNCTION().
DestroyValue_InContainer()
FORCEINLINE void FProperty::DestroyValue_InContainer (void * Dest) const inline
Destroys the value for this property.
The existing data is assumed valid (so for example this calls FString::Empty) This does the entire fixed size array.
Parameters
Dest the address of the container containing the value that should be destroyed.
Definition at line 981 of file UnrealType.h.
References ContainerPtrToValuePtr(), DestroyValueInternal(), FORCEINLINE, and PropertyFlags.
DestroyValueInternal()
virtual void FProperty::DestroyValueInternal (void * Dest) const protected virtual
Reimplemented in FArrayProperty, FMapProperty, FOptionalProperty, FSetProperty, FStructProperty, TProperty< double, FNumericProperty >, TProperty< FFieldPath, FProperty >, TProperty< FLazyObjectPtr, FObjectPropertyBase >, TProperty< float, FNumericProperty >, TProperty< FMulticastScriptDelegate, FMulticastDelegateProperty >, TProperty< FName, FProperty >, TProperty< FScriptArray, FProperty >, TProperty< FScriptDelegate, FProperty >, TProperty< FScriptInterface, FProperty >, TProperty< FScriptMap, FProperty >, TProperty< FScriptSet, FProperty >, TProperty< FSoftObjectPtr, FObjectPropertyBase >, TProperty< FSparseDelegate, FMulticastDelegateProperty >, TProperty< FText, FProperty >, TProperty< FWeakObjectPtr, FObjectPropertyBase >, TProperty< int16, FNumericProperty >, TProperty< int32, FNumericProperty >, TProperty< int64, FNumericProperty >, TProperty< int8, FNumericProperty >, TProperty< InTCppType, FMulticastDelegateProperty >, TProperty< InTCppType, FObjectPropertyBase >, TProperty< TObjectPtr< UObject >, FObjectPropertyBase >, TProperty< uint16, FNumericProperty >, TProperty< uint32, FNumericProperty >, TProperty< uint64, FNumericProperty >, and TProperty< uint8, FNumericProperty >.
Referenced by DestroyValue(), and DestroyValue_InContainer().
EmitIntrusiveOptionalReferenceInfo()
virtual void FProperty::EmitIntrusiveOptionalReferenceInfo (UE::GC::FSchemaBuilder & Schema, int32 BaseOffset, TArray< const FStructProperty * > & EncounteredStructProps, UE::GC::FPropertyStack & DebugPath) virtual
For properties returning true from HasIntrusiveUnsetOptionalState which also contain object references, emit information for the garbage collector to safely gather the references from the value whether the optional value is set or unset.
Reimplemented in FArrayProperty, FMapProperty, FObjectProperty, FSetProperty, and FStructProperty.
References const, and EmitIntrusiveOptionalReferenceInfo().
Referenced by EmitIntrusiveOptionalReferenceInfo().
EmitReferenceInfo()
virtual void FProperty::EmitReferenceInfo (UE::GC::FSchemaBuilder & Schema, int32 BaseOffset, TArray< const FStructProperty * > & EncounteredStructProps, UE::GC::FPropertyStack & DebugPath) virtual
Emits tokens used by realtime garbage collection code to passed in ReferenceTokenStream.
The offset emitted is relative to the passed in BaseOffset which is used by e.g. arrays of structs.
Reimplemented in FArrayProperty, FFieldPathProperty, FInterfaceProperty, FMapProperty, FObjectProperty, FOptionalProperty, FSetProperty, and FStructProperty.
ExportText_Direct()
bool FProperty::ExportText_Direct (FString & ValueStr, const void * Data, const void * Delta, UObject * Parent, int32 PortFlags, UObject * ExportRootScope = nullptr) const
References const, ExportText_Direct(), and Parent.
Referenced by ExportText_Direct(), ExportText_InContainer(), and FRigVMMemoryHandle::GetData_Internal().
ExportText_InContainer()
FORCEINLINE bool FProperty::ExportText_InContainer (int32 Index, FString & ValueStr, const void * Data, const void * Delta, UObject * Parent, int32 PortFlags, UObject * ExportRootScope = nullptr) const inline
Definition at line 667 of file UnrealType.h.
References const, ContainerPtrToValuePtr(), ContainerPtrToValuePtrForDefaults(), ExportText_Direct(), ExportText_InContainer(), FORCEINLINE, and Parent.
Referenced by ExportText_InContainer().
ExportTextItem_Direct()
void FProperty::ExportTextItem_Direct (FString & ValueStr, const void * PropertyValue, const void * DefaultValue, UObject * Parent, int32 PortFlags, UObject * ExportRootScope = nullptr) const inline
Definition at line 528 of file UnrealType.h.
References Direct, and Parent.
ExportTextItem_InContainer()
void FProperty::ExportTextItem_InContainer (FString & ValueStr, const void * Container, const void * DefaultValue, UObject * Parent, int32 PortFlags, UObject * ExportRootScope = nullptr) const inline
Definition at line 533 of file UnrealType.h.
References Container, and Parent.
FindRedirectedPropertyName()
FName FProperty::FindRedirectedPropertyName (const UStruct * ObjectStruct, FName OldName) static
Gets a redirected property name, will return NAME_None if no redirection was found.
FinishDestroy()
void FProperty::FinishDestroy (void * Data) const inline
Applies appropriate finish destroy actions for the property if needed.
This is used during UObject destruction to e.g. safely clear values which rely on UScriptStructs. This does the entire fixed size array.
Parameters
Data the address of the value for this property that should be handled for finish destroy.
Definition at line 1013 of file UnrealType.h.
References FinishDestroyInternal(), and PropertyFlags.
FinishDestroy_InContainer()
void FProperty::FinishDestroy_InContainer (void * Data) const inline
Applies appropriate finish destroy actions for the property if needed.
This is used during UObject destruction to e.g. safely clear values which rely on UScriptStructs. This does the entire fixed size array.
Parameters
Data the address of the container containing the value that should be handled for finish destroy.
Definition at line 1030 of file UnrealType.h.
References ContainerPtrToValuePtr(), FinishDestroyInternal(), and PropertyFlags.
FinishDestroyInternal()
virtual void FProperty::FinishDestroyInternal (void * Data) const protected virtual
Reimplemented in FArrayProperty, FMapProperty, FOptionalProperty, FSetProperty, and FStructProperty.
Referenced by FinishDestroy(), and FinishDestroy_InContainer().
GetBlueprintReplicationCondition()
ELifetimeCondition FProperty::GetBlueprintReplicationCondition () const inline
Definition at line 1269 of file UnrealType.h.
References BlueprintReplicationCondition.
GetCPPMacroType()
virtual FString FProperty::GetCPPMacroType (FString & ExtendedTypeText) const virtual
Reimplemented in FArrayProperty, FBoolProperty, FClassProperty, FEnumProperty, FFieldPathProperty, FInterfaceProperty, FLazyObjectProperty, FMapProperty, FObjectProperty, FOptionalProperty, FSetProperty, FSoftClassProperty, FSoftObjectProperty, FStructProperty, and FWeakObjectProperty.
GetElementSize()
int32 FProperty::GetElementSize () const inline
Definition at line 239 of file UnrealType.h.
References PRAGMA_DISABLE_DEPRECATION_WARNINGS, and PRAGMA_ENABLE_DEPRECATION_WARNINGS.
Referenced by ClearValue(), ClearValue_InContainer(), ContainerUObjectPtrToValuePtrInternal(), ContainerVoidPtrToValuePtrInternal(), CopyCompleteValue(), CopySingleValue(), FScriptArrayHelper::CreateHelperFormInnerProperty(), UBlueprintMapLibrary::DECLARE_FUNCTION(), UBlueprintMapLibrary::DECLARE_FUNCTION(), UBlueprintMapLibrary::DECLARE_FUNCTION(), UBlueprintMapLibrary::DECLARE_FUNCTION(), UBlueprintMapLibrary::DECLARE_FUNCTION(), UBlueprintSetLibrary::DECLARE_FUNCTION(), UBlueprintSetLibrary::DECLARE_FUNCTION(), UBlueprintSetLibrary::DECLARE_FUNCTION(), UBlueprintSetLibrary::DECLARE_FUNCTION(), UKismetArrayLibrary::DECLARE_FUNCTION(), UKismetArrayLibrary::DECLARE_FUNCTION(), UKismetArrayLibrary::DECLARE_FUNCTION(), UKismetArrayLibrary::DECLARE_FUNCTION(), UKismetArrayLibrary::DECLARE_FUNCTION(), UKismetArrayLibrary::DECLARE_FUNCTION(), UKismetArrayLibrary::DECLARE_FUNCTION(), UKismetArrayLibrary::DECLARE_FUNCTION(), TProperty< InTCppType, FObjectPropertyBase >::DestroyValueInternal(), GetSize(), FObjectPropertyBase::GetWrappedUObjectPtrValues(), InitializeValue(), InitializeValue_InContainer(), FArrayProperty::InitializeValueInternal(), FMapProperty::InitializeValueInternal(), TProperty< InTCppType, FObjectPropertyBase >::InitializeValueInternal(), PointerToValuePtr(), and FObjectPropertyBase::SetWrappedUObjectPtrValues().
GetID()
virtual FName FProperty::GetID () const virtual
Reimplemented in FLazyObjectProperty, FObjectPropertyBase, and FSoftObjectProperty.
GetMinAlignment()
virtual int32 FProperty::GetMinAlignment () const virtual
Reimplemented in FArrayProperty, FBoolProperty, FEnumProperty, FOptionalProperty, FStructProperty, TProperty< double, FNumericProperty >, TProperty< FFieldPath, FProperty >, TProperty< FLazyObjectPtr, FObjectPropertyBase >, TProperty< float, FNumericProperty >, TProperty< FMulticastScriptDelegate, FMulticastDelegateProperty >, TProperty< FName, FProperty >, TProperty< FScriptArray, FProperty >, TProperty< FScriptDelegate, FProperty >, TProperty< FScriptInterface, FProperty >, TProperty< FScriptMap, FProperty >, TProperty< FScriptSet, FProperty >, TProperty< FSoftObjectPtr, FObjectPropertyBase >, TProperty< FSparseDelegate, FMulticastDelegateProperty >, TProperty< FText, FProperty >, TProperty< FWeakObjectPtr, FObjectPropertyBase >, TProperty< int16, FNumericProperty >, TProperty< int32, FNumericProperty >, TProperty< int64, FNumericProperty >, TProperty< int8, FNumericProperty >, TProperty< InTCppType, FMulticastDelegateProperty >, TProperty< InTCppType, FObjectPropertyBase >, TProperty< TObjectPtr< UObject >, FObjectPropertyBase >, TProperty< uint16, FNumericProperty >, TProperty< uint32, FNumericProperty >, TProperty< uint64, FNumericProperty >, and TProperty< uint8, FNumericProperty >.
Referenced by FScriptSetHelper::CreateHelperFormElementProperty(), FScriptMapHelper::CreateHelperFormInnerProperties(), and FScriptArrayHelper::CreateHelperFormInnerProperty().
GetNameCPP()
FString FProperty::GetNameCPP () const
Returns the C++ name of the property, including the _DEPRECATED suffix if the property is deprecated.
Returns
C++ name of property
GetOffset_ForDebug()
FORCEINLINE int32 FProperty::GetOffset_ForDebug () const inline
Return offset of property from container base.
Definition at line 392 of file UnrealType.h.
References FORCEINLINE, and Offset_Internal.
GetOffset_ForGC()
FORCEINLINE int32 FProperty::GetOffset_ForGC () const inline
Return offset of property from container base.
Definition at line 402 of file UnrealType.h.
References FORCEINLINE, and Offset_Internal.
GetOffset_ForInternal()
FORCEINLINE int32 FProperty::GetOffset_ForInternal () const inline
Return offset of property from container base.
Definition at line 407 of file UnrealType.h.
References FORCEINLINE, and Offset_Internal.
GetOffset_ForUFunction()
FORCEINLINE int32 FProperty::GetOffset_ForUFunction () const inline
Return offset of property from container base.
Definition at line 397 of file UnrealType.h.
References FORCEINLINE, and Offset_Internal.
GetOffset_ReplaceWith_ContainerPtrToValuePtr()
FORCEINLINE int32 FProperty::GetOffset_ReplaceWith_ContainerPtrToValuePtr () const inline
Return offset of property from container base.
Definition at line 412 of file UnrealType.h.
References FORCEINLINE, and Offset_Internal.
GetOwnerProperty() [1/2]
FProperty * FProperty::GetOwnerProperty () inline
Returns the first FProperty in this property's Outer chain that does not have a FProperty for an Outer.
Definition at line 1187 of file UnrealType.h.
References FProperty(), and FField::GetOwner().
GetOwnerProperty() [2/2]
const FProperty * FProperty::GetOwnerProperty () const inline
Definition at line 1197 of file UnrealType.h.
References FProperty(), and FField::GetOwner().
GetPropertyFlags()
FORCEINLINE EPropertyFlags FProperty::GetPropertyFlags () const inline
Returns this property's propertyflags.
Definition at line 1210 of file UnrealType.h.
References FORCEINLINE, and PropertyFlags.
GetRepOwner()
FORCEINLINE FProperty * FProperty::GetRepOwner () inline
Returns the replication owner, which is the property itself, or NULL if this isn't important for replication.
It is relevant if the property is a net relevant and not being run in the editor
Definition at line 1249 of file UnrealType.h.
References FProperty(), FORCEINLINE, GIsEditor, and PropertyFlags.
GetSingleValue_InContainer()
void FProperty::GetSingleValue_InContainer (const void * InContainer, void * OutValue, int32 ArrayIndex) const
Copies a single value to OutValue even if the property represents a static array of values.
Parameters
InContainer Instance owner of the property
OutValue Pointer to the memory that the value will be copied to. Must be at least ElementSize big
ArrayIndex Index into the static array to copy the value from. If the property is not a static array it should be 0
References InContainer.
GetSize()
FORCEINLINE int32 FProperty::GetSize () const inline
Definition at line 1149 of file UnrealType.h.
References FORCEINLINE, and GetElementSize().
Referenced by FScriptSetHelper::AddElement(), FScriptSetHelper::CreateHelperFormElementProperty(), FScriptMapHelper::CreateHelperFormInnerProperties(), IsInContainer(), and IsInContainer().
GetValue_InContainer()
FORCEINLINE void FProperty::GetValue_InContainer (void const * InContainer, void * OutValue) const inline
Definition at line 587 of file UnrealType.h.
References CallGetter(), ContainerVoidPtrToValuePtrInternal(), CopyCompleteValue(), FORCEINLINE, HasGetter(), and InContainer.
Referenced by TProperty_Numeric< InTCppType >::GetNumericPropertyValueToString_InContainer(), TProperty_Numeric< InTCppType >::GetSignedIntPropertyValue_InContainer(), TProperty_Numeric< InTCppType >::GetUnsignedIntPropertyValue_InContainer(), FObjectPropertyBase::GetWrappedUObjectPtrValues(), and FObjectPropertyBase::SetWrappedUObjectPtrValues().
GetValueAddressAtIndex_Direct()
virtual void * FProperty::GetValueAddressAtIndex_Direct (const FProperty * Inner, void * InValueAddress, int32 Index) const virtual
Gets value address at given index inside of a static array or container.
Parameters
InValueAddress address of the value represented by this property
Index into the static array or container
Returns
address of the value at given index
Reimplemented in FArrayProperty, FMapProperty, and FSetProperty.
References FProperty(), const, Parent, and PURE_VIRTUAL.
GetValueTypeHash()
uint32 FProperty::GetValueTypeHash (const void * Src) const
Returns the hash value for an element of this property.
Referenced by FScriptSetHelper::AddElement(), FScriptSetHelper::FindElementIndexFromHash(), and FScriptSetHelper::RemoveElement().
GetValueTypeHashInternal()
virtual uint32 FProperty::GetValueTypeHashInternal (const void * Src) const protected virtual
Reimplemented in FBoolProperty, FDoubleProperty, FEnumProperty, FFloatProperty, FLazyObjectProperty, FNameProperty, FObjectProperty, FOptionalProperty, FSoftObjectProperty, FStructProperty, FWeakObjectProperty, TProperty_Numeric< double >, TProperty_Numeric< float >, TProperty_Numeric< int16 >, TProperty_Numeric< int32 >, TProperty_Numeric< int64 >, TProperty_Numeric< int8 >, TProperty_Numeric< uint16 >, TProperty_Numeric< uint32 >, TProperty_Numeric< uint64 >, and TProperty_Numeric< uint8 >.
HasAllPropertyFlags()
FORCEINLINE bool FProperty::HasAllPropertyFlags (uint64 FlagsToCheck) const inline
Used to safely check whether all of the passed in flags are set.
Parameters
FlagsToCheck Object flags to check for
Returns
true if all of the passed in flags are set (including no flags passed in), false otherwise
Definition at line 1240 of file UnrealType.h.
References FORCEINLINE, and PropertyFlags.
Referenced by ClearValue(), ClearValue_InContainer(), and TFieldIterator< T >::IterateToNext().
HasAnyPropertyFlags()
FORCEINLINE bool FProperty::HasAnyPropertyFlags (uint64 FlagsToCheck) const inline
Used to safely check whether any of the passed in flags are set.
Parameters
FlagsToCheck Object flags to check for.
Returns
true if any of the passed in flags are set, false otherwise (including no flags passed in).
Definition at line 1229 of file UnrealType.h.
References CPF_AllFlags, FORCEINLINE, and PropertyFlags.
Referenced by UE::Private::DoesParamMatch(), FRigVMGraphEnumDetailCustomization::GetPropertyChain(), and FRigVMGraphMathTypeDetailCustomization::GetPropertyChain().
HasGetter()
virtual bool FProperty::HasGetter () const inline virtual
Checks if this property as a native getter function.
Definition at line 301 of file UnrealType.h.
Referenced by CallGetter(), GetValue_InContainer(), and FObjectPropertyBase::GetWrappedUObjectPtrValues().
HasSetter()
virtual bool FProperty::HasSetter () const inline virtual
Checks if this property as a native setter function.
Definition at line 296 of file UnrealType.h.
Referenced by CallSetter(), SetValue_InContainer(), and FObjectPropertyBase::SetWrappedUObjectPtrValues().
HasSetterOrGetter()
virtual bool FProperty::HasSetterOrGetter () const inline virtual
Checks if this property as a native setter or getter function.
Definition at line 306 of file UnrealType.h.
Identical_InContainer()
bool FProperty::Identical_InContainer (const void * A, const void * B, int32 ArrayIndex = 0, uint32 PortFlags = 0) const inline
Determines whether the property values are identical.
Parameters
A property container of data to be compared, NOT offset
B property container of data to be compared, NOT offset
PortFlags allows caller more control over how the property values are compared
Returns
true if the property values are identical
Definition at line 469 of file UnrealType.h.
References A, B, const, ContainerPtrToValuePtr(), Identical, and Identical_InContainer().
Referenced by Identical_InContainer().
ImportSingleProperty()
const TCHAR * FProperty::ImportSingleProperty (const TCHAR * Str, void * DestData, const UStruct * ObjectStruct, UObject * SubobjectOuter, int32 PortFlags, FOutputDevice * Warn, TArray< struct FDefinedProperty > & DefinedProperties) static
parses and imports a text definition of a single property's value (if array, may be an individual element) also includes parsing of special operations for array properties (Add/Remove/RemoveIndex/Empty)
Parameters
Str the string to parse
DestData base location the parsed property should place its data (DestData + ParsedProperty->Offset)
ObjectStruct the struct containing the valid fields
SubobjectOuter owner of DestData and any subobjects within it
PortFlags property import flags
Warn output device for any error messages
DefinedProperties (out) list of properties/indices that have been parsed by previous calls, so duplicate definitions cause an error
Returns
pointer to remaining text in the stream (even on failure, but on failure it may not be advanced past the entire key/value pair)
References Warn.
ImportText_Direct()
const TCHAR * FProperty::ImportText_Direct (const TCHAR * Buffer, void * PropertyPtr, UObject * OwnerObject, int32 PortFlags, FOutputDevice * ErrorText = (FOutputDevice*)GWarn) const inline
Import a text value.
Parameters
Buffer Text representing the property value
PropertyPtr Pointer to property value
OwnerObject Object that owns the property
PortFlags Flags controlling the behavior when importing the value
ErrorText Output device for throwing warnings or errors on import
Returns
Buffer pointer advanced by the number of characters consumed when reading the text value
Definition at line 566 of file UnrealType.h.
References Buffer, Direct, GWarn, ImportText_Internal, PPF_UseDeprecatedProperties, and ValidateImportFlags().
ImportText_InContainer()
const TCHAR * FProperty::ImportText_InContainer (const TCHAR * Buffer, void * Container, UObject * OwnerObject, int32 PortFlags, FOutputDevice * ErrorText = (FOutputDevice*)GWarn) const inline
Import a text value.
Parameters
Buffer Text representing the property value
Container Pointer to the container that owns this property (either UObject pointer or a struct pointer)
OwnerObject Object that owns the property container (if the container is an UObject then Container is also OwnerObject)
PortFlags Flags controlling the behavior when importing the value
ErrorText Output device for throwing warnings or errors on import
Returns
Buffer pointer advanced by the number of characters consumed when reading the text value
Definition at line 547 of file UnrealType.h.
References Buffer, Container, GWarn, ImportText_Internal, PPF_UseDeprecatedProperties, and ValidateImportFlags().
Init()
void FProperty::Init () protected
Initializes internal state.
References FORCEINLINE, Init(), and UE_INTERNAL.
Referenced by Init().
InitializeIntrusiveUnsetOptionalValue()
virtual bool virtual HasIntrusiveUnsetOptionalState() const PURE_VIRTUAL(FProperty void FProperty::InitializeIntrusiveUnsetOptionalValue (void * Data) const virtual
Returns whether this type has a special state for an unset TOptional meaning the size TOptional<T> and T are the same.
Properties must implement this function explicitly even if they do not have such a state.
See also
Optional.h - HasIntrusiveUnsetOptionalState
FOptionalProperty Initialize the value at the given address to an unset TOptional using an intrusive state rather than a trailing boolean.
TOptional::TOptional
Constructor taking FIntrusiveUnsetOptionalState
Reimplemented in FArrayProperty, FMapProperty, FObjectProperty, FSetProperty, FStructProperty, TProperty< double, FNumericProperty >, TProperty< FFieldPath, FProperty >, TProperty< FLazyObjectPtr, FObjectPropertyBase >, TProperty< float, FNumericProperty >, TProperty< FMulticastScriptDelegate, FMulticastDelegateProperty >, TProperty< FName, FProperty >, TProperty< FScriptArray, FProperty >, TProperty< FScriptDelegate, FProperty >, TProperty< FScriptInterface, FProperty >, TProperty< FScriptMap, FProperty >, TProperty< FScriptSet, FProperty >, TProperty< FSoftObjectPtr, FObjectPropertyBase >, TProperty< FSparseDelegate, FMulticastDelegateProperty >, TProperty< FText, FProperty >, TProperty< FWeakObjectPtr, FObjectPropertyBase >, TProperty< int16, FNumericProperty >, TProperty< int32, FNumericProperty >, TProperty< int64, FNumericProperty >, TProperty< int8, FNumericProperty >, TProperty< InTCppType, FMulticastDelegateProperty >, TProperty< InTCppType, FObjectPropertyBase >, TProperty< TObjectPtr< UObject >, FObjectPropertyBase >, TProperty< uint16, FNumericProperty >, TProperty< uint32, FNumericProperty >, TProperty< uint64, FNumericProperty >, and TProperty< uint8, FNumericProperty >.
References const, and InitializeIntrusiveUnsetOptionalValue().
Referenced by InitializeIntrusiveUnsetOptionalValue().
InitializeValue()
FORCEINLINE void FProperty::InitializeValue (void * Dest) const inline
Zeros, copies from the default, or calls the constructor for on the value for this property.
The existing data is assumed invalid (so for example this might indirectly call FString::FString, This will do the entire fixed size array.
Parameters
Dest the address of the value for this property that should be cleared.
Definition at line 1051 of file UnrealType.h.
References FORCEINLINE, GetElementSize(), InitializeValueInternal(), FMemory::Memzero(), and PropertyFlags.
Referenced by FScriptSetHelper::AddElement(), UBlueprintMapLibrary::DECLARE_FUNCTION(), UBlueprintMapLibrary::DECLARE_FUNCTION(), UBlueprintMapLibrary::DECLARE_FUNCTION(), UBlueprintMapLibrary::DECLARE_FUNCTION(), UBlueprintMapLibrary::DECLARE_FUNCTION(), UBlueprintSetLibrary::DECLARE_FUNCTION(), UBlueprintSetLibrary::DECLARE_FUNCTION(), UBlueprintSetLibrary::DECLARE_FUNCTION(), UBlueprintSetLibrary::DECLARE_FUNCTION(), UKismetArrayLibrary::DECLARE_FUNCTION(), UKismetArrayLibrary::DECLARE_FUNCTION(), UKismetArrayLibrary::DECLARE_FUNCTION(), UKismetArrayLibrary::DECLARE_FUNCTION(), UKismetArrayLibrary::DECLARE_FUNCTION(), UKismetArrayLibrary::DECLARE_FUNCTION(), UKismetArrayLibrary::DECLARE_FUNCTION(), and UKismetArrayLibrary::DECLARE_FUNCTION().
InitializeValue_InContainer()
FORCEINLINE void FProperty::InitializeValue_InContainer (void * Dest) const inline
Zeros, copies from the default, or calls the constructor for on the value for this property.
The existing data is assumed invalid (so for example this might indirectly call FString::FString, This will do the entire fixed size array.
Parameters
Dest the address of the container of value for this property that should be cleared.
Definition at line 1069 of file UnrealType.h.
References ContainerPtrToValuePtr(), FORCEINLINE, GetElementSize(), InitializeValueInternal(), FMemory::Memzero(), and PropertyFlags.
InitializeValueInternal()
virtual void FProperty::InitializeValueInternal (void * Dest) const protected virtual
Reimplemented in FArrayProperty, FBoolProperty, FMapProperty, FOptionalProperty, FStructProperty, TProperty< double, FNumericProperty >, TProperty< FFieldPath, FProperty >, TProperty< FLazyObjectPtr, FObjectPropertyBase >, TProperty< float, FNumericProperty >, TProperty< FMulticastScriptDelegate, FMulticastDelegateProperty >, TProperty< FName, FProperty >, TProperty< FScriptArray, FProperty >, TProperty< FScriptDelegate, FProperty >, TProperty< FScriptInterface, FProperty >, TProperty< FScriptMap, FProperty >, TProperty< FScriptSet, FProperty >, TProperty< FSoftObjectPtr, FObjectPropertyBase >, TProperty< FSparseDelegate, FMulticastDelegateProperty >, TProperty< FText, FProperty >, TProperty< FWeakObjectPtr, FObjectPropertyBase >, TProperty< int16, FNumericProperty >, TProperty< int32, FNumericProperty >, TProperty< int64, FNumericProperty >, TProperty< int8, FNumericProperty >, TProperty< InTCppType, FMulticastDelegateProperty >, TProperty< InTCppType, FObjectPropertyBase >, TProperty< TObjectPtr< UObject >, FObjectPropertyBase >, TProperty< uint16, FNumericProperty >, TProperty< uint32, FNumericProperty >, TProperty< uint64, FNumericProperty >, and TProperty< uint8, FNumericProperty >.
Referenced by InitializeValue(), and InitializeValue_InContainer().
InstanceSubobjects()
virtual void FProperty::InstanceSubobjects (void * Data, void const * DefaultData, TNotNull< UObject * > Owner, struct FObjectInstancingGraph * InstanceGraph) virtual
Creates new copies of components.
Parameters
Data pointer to the address of the instanced object referenced by this UComponentProperty
DefaultData pointer to the address of the default value of the instanced object referenced by this UComponentProperty
Owner the object that contains this property's data
InstanceGraph contains the mappings of instanced objects and components to their templates
Reimplemented in FArrayProperty, FDelegateProperty, FMapProperty, FMulticastDelegateProperty, FObjectPropertyBase, FOptionalProperty, FSetProperty, and FStructProperty.
References FField::Owner.
IsEditorOnlyProperty()
FORCEINLINE bool FProperty::IsEditorOnlyProperty () const inline
Editor-only properties are those that only are used with the editor is present or cannot be removed from serialisation.
Editor-only properties include: EditorOnly properties Properties that cannot be removed from serialisation are: Boolean properties (may affect GCC_BITFIELD_MAGIC computation) Native properties (native serialisation)
Definition at line 1261 of file UnrealType.h.
References CPF_DevelopmentAssets, FORCEINLINE, and PropertyFlags.
IsInContainer() [1/2]
FORCEINLINE bool FProperty::IsInContainer (const UStruct * ContainerClass) const inline
See if the offset of this property is below the supplied container size.
Definition at line 806 of file UnrealType.h.
References FORCEINLINE, UStruct::GetPropertiesSize(), GetSize(), MAX_int32, and Offset_Internal.
IsInContainer() [2/2]
FORCEINLINE bool FProperty::IsInContainer (int32 ContainerSize) const inline
See if the offset of this property is below the supplied container size.
Definition at line 801 of file UnrealType.h.
References FORCEINLINE, GetSize(), and Offset_Internal.
Referenced by ContainerPtrToValuePtrForDefaults(), ContainerPtrToValuePtrForDefaults(), ContainerPtrToValuePtrForDefaults(), and ContainerPtrToValuePtrForDefaults().
IsIntrusiveOptionalValueSet()
virtual bool FProperty::IsIntrusiveOptionalValueSet (const void * Data) const virtual
Returns whether an optional value of this inner type is unset.
Only valid to call if HasIntrusiveUnsetOptionalState returns true. Equivalent to TOptional<T>::IsSet()
See also
operator==(FIntrusiveUnsetOptionalState)
Parameters
Data Address of value to inspect, already offset.
Returns
true if the value is unset
Reimplemented in FArrayProperty, FMapProperty, FObjectProperty, FSetProperty, FStructProperty, TProperty< double, FNumericProperty >, TProperty< FFieldPath, FProperty >, TProperty< FLazyObjectPtr, FObjectPropertyBase >, TProperty< float, FNumericProperty >, TProperty< FMulticastScriptDelegate, FMulticastDelegateProperty >, TProperty< FName, FProperty >, TProperty< FScriptArray, FProperty >, TProperty< FScriptDelegate, FProperty >, TProperty< FScriptInterface, FProperty >, TProperty< FScriptMap, FProperty >, TProperty< FScriptSet, FProperty >, TProperty< FSoftObjectPtr, FObjectPropertyBase >, TProperty< FSparseDelegate, FMulticastDelegateProperty >, TProperty< FText, FProperty >, TProperty< FWeakObjectPtr, FObjectPropertyBase >, TProperty< int16, FNumericProperty >, TProperty< int32, FNumericProperty >, TProperty< int64, FNumericProperty >, TProperty< int8, FNumericProperty >, TProperty< InTCppType, FMulticastDelegateProperty >, TProperty< InTCppType, FObjectPropertyBase >, TProperty< TObjectPtr< UObject >, FObjectPropertyBase >, TProperty< uint16, FNumericProperty >, TProperty< uint32, FNumericProperty >, TProperty< uint64, FNumericProperty >, and TProperty< uint8, FNumericProperty >.
References const, and IsIntrusiveOptionalValueSet().
Referenced by IsIntrusiveOptionalValueSet().
Link()
int32 FProperty::Link (FArchive & Ar) inline
Definition at line 422 of file UnrealType.h.
References Ar, LinkInternal(), and SetupOffset().
LinkInternal()
virtual void FProperty::LinkInternal (FArchive & Ar) protected virtual
Reimplemented in FArrayProperty, FBoolProperty, FEnumProperty, FInterfaceProperty, FMapProperty, FOptionalProperty, FSetProperty, FSoftObjectProperty, FStructProperty, FWeakObjectProperty, TProperty< double, FNumericProperty >, TProperty< FFieldPath, FProperty >, TProperty< FLazyObjectPtr, FObjectPropertyBase >, TProperty< float, FNumericProperty >, TProperty< FMulticastScriptDelegate, FMulticastDelegateProperty >, TProperty< FName, FProperty >, TProperty< FScriptArray, FProperty >, TProperty< FScriptDelegate, FProperty >, TProperty< FScriptInterface, FProperty >, TProperty< FScriptMap, FProperty >, TProperty< FScriptSet, FProperty >, TProperty< FSoftObjectPtr, FObjectPropertyBase >, TProperty< FSparseDelegate, FMulticastDelegateProperty >, TProperty< FText, FProperty >, TProperty< FWeakObjectPtr, FObjectPropertyBase >, TProperty< int16, FNumericProperty >, TProperty< int32, FNumericProperty >, TProperty< int64, FNumericProperty >, TProperty< int8, FNumericProperty >, TProperty< InTCppType, FMulticastDelegateProperty >, TProperty< InTCppType, FObjectPropertyBase >, TProperty< TObjectPtr< UObject >, FObjectPropertyBase >, TProperty< uint16, FNumericProperty >, TProperty< uint32, FNumericProperty >, TProperty< uint64, FNumericProperty >, and TProperty< uint8, FNumericProperty >.
References Ar.
Referenced by Link(), and LinkWithoutChangingOffset().
LinkWithoutChangingOffset()
void FProperty::LinkWithoutChangingOffset (FArchive & Ar) inline
Definition at line 417 of file UnrealType.h.
References Ar, and LinkInternal().
LoadTypeName()
virtual bool FProperty::LoadTypeName (UE::FPropertyTypeName Type, const FPropertyTag * Tag = nullptr) virtual
Restores this property and its owned properties from the type name.
Returns
true if this property loaded from the type name and is in a valid and usable state.
Reimplemented in FArrayProperty, FByteProperty, FEnumProperty, FMapProperty, FMulticastSparseDelegateProperty, FOptionalProperty, FSetProperty, and FStructProperty.
PerformOperationWithGetter()
void FProperty::PerformOperationWithGetter (void * OutContainer, const void * DirectPropertyAddress, TFunctionRef< void(const void *)> DirectValueAccessFunc) const
Helper function for getting container / struct property value and performing operation directly on the value memory.
Parameters
OutContainer Pointer to the container that owns the property. Can be null but then setters and getters will not be used.
DirectPropertyAddress Direct property value address. Can be null only if OutContainer is a valid pointer.
DirectValueAccessFunc Function that manipulates directly on property value address. The value address can be different than the passed in DirectPropertyAddress if setters and getters are present and OutContainer pointer is valid.
PerformOperationWithSetter()
void FProperty::PerformOperationWithSetter (void * OutContainer, void * DirectPropertyAddress, TFunctionRef< void(void *)> DirectValueAccessFunc) const
Helper function for setting container / struct property value and performing operation directly on the value memory.
Parameters
OutContainer Pointer to the container that owns the property. Can be null but then setters and getters will not be used.
DirectPropertyAddress Direct property value address. Can be null only if OutContainer is a valid pointer.
DirectValueAccessFunc Function that manipulates directly on property value address. The value address can be different than the passed in DirectPropertyAddress if setters and getters are present and OutContainer pointer is valid.
PointerToValuePtr()
FORCEINLINE void * FProperty::PointerToValuePtr (void const * ContainerOrPropertyPtr, EPropertyPointerType PropertyPointerType, int32 ArrayIndex = 0) const inline protected
Definition at line 720 of file UnrealType.h.
References Container, FORCEINLINE, GetElementSize(), and Offset_Internal.
PostDuplicate()
virtual void FProperty::PostDuplicate (const FField & InField) override virtual
Fixups after duplicating a Field.
Reimplemented from FField.
Reimplemented in FArrayProperty, FBoolProperty, FByteProperty, FClassProperty, FDelegateProperty, FEnumProperty, FInterfaceProperty, FMapProperty, FMulticastDelegateProperty, FObjectPropertyBase, FOptionalProperty, FSetProperty, FSoftClassProperty, and FStructProperty.
References FField::FField().
ResolveVisitedPathInfo()
virtual void * FProperty::ResolveVisitedPathInfo (void * Data, const FPropertyVisitorInfo & Info) const virtual
Attempt to resolve the given inner path info against this outer property to get the inner property value.
Returns
The inner property value, or null if the path info is incompatible/missing on this property.
Reimplemented in FArrayProperty, FMapProperty, FObjectPropertyBase, FOptionalProperty, FSetProperty, and FStructProperty.
References const, Info, and ResolveVisitedPathInfo().
Referenced by ResolveVisitedPathInfo().
SameType()
virtual bool FProperty::SameType (const FProperty * Other) const virtual
returns true, if Other is property of exactly the same type
Reimplemented in FArrayProperty, FClassProperty, FDelegateProperty, FEnumProperty, FInterfaceProperty, FMapProperty, FMulticastDelegateProperty, FObjectPropertyBase, FOptionalProperty, FSetProperty, FSoftClassProperty, and FStructProperty.
References FProperty(), and Other.
Referenced by RigVMTypeUtils::AreCompatible().
SaveTypeName()
virtual void FProperty::SaveTypeName (UE::FPropertyTypeNameBuilder & Type) const virtual
Saves the type name of this property and its owned properties.
Reimplemented in FArrayProperty, FByteProperty, FEnumProperty, FMapProperty, FOptionalProperty, FSetProperty, and FStructProperty.
Serialize()
virtual void FProperty::Serialize (FArchive & Ar) override virtual
Reimplemented from FField.
Reimplemented in FArrayProperty, FBoolProperty, FByteProperty, FClassProperty, FDelegateProperty, FEnumProperty, FFieldPathProperty, FInterfaceProperty, FMapProperty, FMulticastDelegateProperty, FObjectPropertyBase, FOptionalProperty, FSetProperty, FSoftClassProperty, and FStructProperty.
References Ar.
SerializeBinProperty()
void FProperty::SerializeBinProperty (FStructuredArchive::FSlot Slot, void * Data, int32 ArrayIdx = -1) inline
Serializes the property with the struct's data residing in Data.
Parameters
Ar the archive to use for serialization
Data pointer to the location of the beginning of the struct's property data
ArrayIdx if not -1 (default), only this array slot will be serialized
Definition at line 481 of file UnrealType.h.
References ContainerPtrToValuePtr(), FStructuredArchiveSlot::EnterStream(), UE::StructuredArchive::Private::FSlotBase::GetUnderlyingArchive(), ShouldSerializeValue(), and Stream.
SerializeNonMatchingBinProperty()
void FProperty::SerializeNonMatchingBinProperty (FStructuredArchive::FSlot Slot, void * Data, void const * DefaultData, UStruct * DefaultStruct) inline
Serializes the property with the struct's data residing in Data, unless it matches the default.
Parameters
Ar the archive to use for serialization
Data pointer to the location of the beginning of the struct's property data
DefaultData pointer to the location of the beginning of the data that should be compared against
DefaultStruct struct corresponding to the block of memory located at DefaultData
Definition at line 504 of file UnrealType.h.
References ContainerPtrToValuePtr(), ContainerPtrToValuePtrForDefaults(), Default, FStructuredArchiveSlot::EnterStream(), FArchive::GetPortFlags(), UE::StructuredArchive::Private::FSlotBase::GetUnderlyingArchive(), Identical, ShouldSerializeValue(), Stream, and Target.
SetBlueprintReplicationCondition()
void FProperty::SetBlueprintReplicationCondition (ELifetimeCondition InBlueprintReplicationCondition) inline
Definition at line 1270 of file UnrealType.h.
References BlueprintReplicationCondition.
SetElementSize()
void FProperty::SetElementSize (int32 NewSize)
Referenced by TProperty< InTCppType, FObjectPropertyBase >::TProperty(), TProperty< InTCppType, FObjectPropertyBase >::TProperty(), and TProperty< InTCppType, FObjectPropertyBase >::LinkInternal().
SetOffset_Internal()
void FProperty::SetOffset_Internal (int32 NewOffset) protected
Set the alignment offset for this property - added for FMapProperty.
References SetOffset_Internal().
Referenced by SetOffset_Internal().
SetPropertyFlags()
FORCEINLINE void FProperty::SetPropertyFlags (EPropertyFlags NewFlags) inline
Definition at line 1214 of file UnrealType.h.
References FORCEINLINE, and PropertyFlags.
SetSingleValue_InContainer()
void FProperty::SetSingleValue_InContainer (void * OutContainer, const void * InValue, int32 ArrayIndex) const
Copies a single value to the property even if the property represents a static array of values.
Parameters
OutContainer Instance owner of the property
InValue Pointer to the memory that the value will be copied from. Must be at least ElementSize big
ArrayIndex Index into the static array to copy the value from. If the property is not a static array it should be 0
SetupOffset()
int32 FProperty::SetupOffset () private
Set the alignment offset for this property.
Returns
the size of the structure including this newly added property
References SetupOffset().
Referenced by Link(), and SetupOffset().
SetValue_InContainer()
FORCEINLINE void FProperty::SetValue_InContainer (void * OutContainer, const void * InValue) const inline
Definition at line 576 of file UnrealType.h.
References CallSetter(), ContainerVoidPtrToValuePtrInternal(), CopyCompleteValue(), FORCEINLINE, and HasSetter().
Referenced by TProperty_Numeric< InTCppType >::SetNumericPropertyValueFromString_InContainer(), and FObjectPropertyBase::SetWrappedUObjectPtrValues().
ShouldDuplicateValue()
bool FProperty::ShouldDuplicateValue () const inline
Determines whether this property value is eligible for copying when duplicating an object.
Returns
true if this property value should be copied into the duplicate object
Definition at line 1162 of file UnrealType.h.
References FField::GetOwnerClass(), and ShouldPort().
ShouldPort()
bool FProperty::ShouldPort (uint32 PortFlags = 0) const
Referenced by ShouldDuplicateValue().
ShouldSerializeValue()
bool FProperty::ShouldSerializeValue (FArchive & Ar) const
References Ar.
Referenced by SerializeBinProperty(), and SerializeNonMatchingBinProperty().
SupportsNetSharedSerialization()
virtual bool FProperty::SupportsNetSharedSerialization () const virtual
Reimplemented in FFieldPathProperty, FInterfaceProperty, FObjectPropertyBase, FOptionalProperty, and FStructProperty.
UE_DEPRECATED() [1/2]
FProperty::UE_DEPRECATED (5. 5, "Use GetElementSize/SetElementSize instead.") private
UE_DEPRECATED() [2/2]
FProperty::UE_DEPRECATED (5. 7, "Visit is deprecated, please use Visit with context instead.") const &
UseBinaryOrNativeSerialization()
virtual bool FProperty::UseBinaryOrNativeSerialization (const FArchive & Ar) const virtual
Reimplemented in FArrayProperty, FMapProperty, FOptionalProperty, FSetProperty, and FStructProperty.
References Ar.
ValidateImportFlags()
bool FProperty::ValidateImportFlags (uint32 PortFlags, FOutputDevice * ErrorText = NULL) const
Verify that modifying this property's value via ImportText is allowed.
Parameters
PortFlags the flags specified in the call to ImportText
ErrorText [out] set to the error message that should be displayed if returns false
Returns
true if ImportText should be allowed
Referenced by ImportText_Direct(), and ImportText_InContainer().
Visit() [1/2]
EPropertyVisitorControlFlow FProperty::Visit (const FPropertyVisitorData & Data, const TFunctionRef< EPropertyVisitorControlFlow(const FPropertyVisitorContext &)> InFunc) const
Visits this property and allows recursion into the inner properties This method allows callers to visit inner properties without knowing about its container type as opposed to TPropertyIterator.
This visit property pattern facilitates the recursion into user defined properties and allows users to add specific visit logic on UStruct via traits.
Parameters
Data to the property to visit
InFunc to call on each visited property, the return value controls what is the next behavior once this property has been visited
Returns
the new action to take one visited this property
References const, and Visit().
Referenced by Visit(), and Visit().
Visit() [2/2]
virtual EPropertyVisitorControlFlow FProperty::Visit (FPropertyVisitorContext & Context, const TFunctionRef< EPropertyVisitorControlFlow(const FPropertyVisitorContext &)> InFunc) const virtual
Visits this property and allows recursion into the inner properties This method allows callers to visit inner properties without knowing about its container type as opposed to TPropertyIterator.
This visit property pattern facilitates the recursion into user defined properties and allows users to add specific visit logic on UStruct via traits.
Parameters
Context which containes the path that was computed until we reached this property and the sata to the property to visit
InFunc to call on each visited property, the return value controls what is the next behavior once this property has been visited
Returns
the new action to take one visited this property
Reimplemented in FArrayProperty, FMapProperty, FObjectPropertyBase, FOptionalProperty, FSetProperty, and FStructProperty.
References const, and Visit().
Friends And Related Symbol Documentation
FMapProperty
friend class FMapProperty friend
Definition at line 365 of file UnrealType.h.
References FMapProperty.
Referenced by FMapProperty.
UE::CoreUObject::Private::ExportEnumToBuffer
void UE::CoreUObject::Private::ExportEnumToBuffer (const UEnum * Enum, const FProperty * Prop, const FNumericProperty * NumericProp, FString & ValueStr, const void * PropertyValueOrContainer, EPropertyPointerType PropertyPointerType, const void * DefaultValue, UObject * Parent, int32 PortFlags, UObject * ExportRootScope) friend
References FProperty(), Enum, and Parent.
UE::CoreUObject::Private::ImportEnumFromBuffer
const TCHAR * UE::CoreUObject::Private::ImportEnumFromBuffer (UEnum * Enum, const FProperty * PropertyToSet, const FNumericProperty * UnderlyingProp, const TCHAR * PropertyClassName, const TCHAR * Buffer, void * ContainerOrPropertyPtr, EPropertyPointerType PropertyPointerType, FOutputDevice * ErrorText) friend
References FProperty(), Buffer, and Enum.
UEProperty_Private::FProperty_DoNotUse
friend class UEProperty_Private::FProperty_DoNotUse friend
Definition at line 366 of file UnrealType.h.
References UEProperty_Private::FProperty_DoNotUse.
Referenced by UEProperty_Private::FProperty_DoNotUse.
Field Documentation
BlueprintReplicationCondition
TEnumAsByte<ELifetimeCondition> FProperty::BlueprintReplicationCondition private
Definition at line 193 of file UnrealType.h.
Referenced by GetBlueprintReplicationCondition(), and SetBlueprintReplicationCondition().
const
const TFunctionRef<EPropertyVisitorControlFlow(const FPropertyVisitorPath& , const FPropertyVisitorData&)> InFunc FProperty::const
Definition at line 330 of file UnrealType.h.
Referenced by FDoubleProperty::FDoubleProperty(), FFloatProperty::FFloatProperty(), FInt16Property::FInt16Property(), FInt64Property::FInt64Property(), FInt8Property::FInt8Property(), FIntProperty::FIntProperty(), FLazyObjectProperty::FLazyObjectProperty(), FNumericProperty::FNumericProperty(), FObjectProperty::FObjectProperty(), FSoftObjectProperty::FSoftObjectProperty(), FSoftObjectProperty::FSoftObjectProperty(), FUInt16Property::FUInt16Property(), FUInt32Property::FUInt32Property(), FUInt64Property::FUInt64Property(), FWeakObjectProperty::FWeakObjectProperty(), ClearIntrusiveOptionalValue(), EmitIntrusiveOptionalReferenceInfo(), ExportText_Direct(), ExportText_InContainer(), GetValueAddressAtIndex_Direct(), Identical_InContainer(), FMulticastDelegateProperty::ImportDelegateFromText(), FMulticastDelegateProperty::ImportText_Add(), FMulticastDelegateProperty::ImportText_Remove(), InitializeIntrusiveUnsetOptionalValue(), IsIntrusiveOptionalValueSet(), ResolveVisitedPathInfo(), Visit(), and Visit().
DestructorLinkNext
FProperty* FProperty::DestructorLinkNext
In memory only: Linked list of properties requiring destruction.
Note this does not include things that will be destroyed by the native destructor
Definition at line 209 of file UnrealType.h.
GetCPPType
virtual FString FProperty::GetCPPType(FString *ExtendedTypeText=NULL, uint32 CPPExportFlags=0) const PURE_VIRTUAL(FProperty
Returns the text to use for exporting this property to header file.
Parameters
ExtendedTypeText for property types which use templates, will be filled in with the type
CPPExportFlags flags for modifying the behavior of the export
Definition at line 287 of file UnrealType.h.
Referenced by TProperty_MulticastDelegate< InTCppType >::GetCPPType().
Identical
virtual bool FProperty::Identical(const void *A, const void *B, uint32 PortFlags=0) const PURE_VIRTUAL(FProperty
Determines whether the property values are identical.
Parameters
A property data to be compared, already offset
B property data to be compared, already offset
PortFlags allows caller more control over how the property values are compared
Returns
true if the property values are identical
Definition at line 458 of file UnrealType.h.
Referenced by FScriptSetHelper::AddElement(), FScriptSetHelper::FindElementIndex(), FScriptSetHelper::FindElementIndexFromHash(), FScriptMapHelper::FindMapIndexWithKey(), Identical_InContainer(), FScriptSetHelper::RemoveElement(), and SerializeNonMatchingBinProperty().
ImportText_Internal
virtual void virtual ExportText_Internal (FString& ValueStr, const void* PropertyValueOrContainer, EPropertyPointerType PointerType, const void* DefaultValue, UObject* Parent, int32 PortFlags, UObject* ExportRootScope = nullptr) const PURE_VIRTUAL(FProperty const TCHAR FProperty::ImportText_Internal) (const TCHAR *Buffer, void *ContainerOrPropertyPtr, EPropertyPointerType PointerType, UObject *OwnerObject, int32 PortFlags, FOutputDevice *ErrorText) const PURE_VIRTUAL(FProperty protected
Definition at line 662 of file UnrealType.h.
Referenced by ImportText_Direct(), and ImportText_InContainer().
NetSerializeItem
virtual void virtual SerializeItem(FStructuredArchive::FSlot Slot, void *Value, void const *Defaults=NULL) const PURE_VIRTUAL(FProperty boo FProperty::NetSerializeItem) (FArchive &Ar, UPackageMap *Map, void *Data, TArray< uint8 > *MetaData=NULL) const
Definition at line 525 of file UnrealType.h.
NextRef
FProperty* FProperty::NextRef
In memory only: Linked list of object reference properties from most-derived to base.
Definition at line 207 of file UnrealType.h.
Offset_Internal
int32 FProperty::Offset_Internal private
Definition at line 201 of file UnrealType.h.
Referenced by ContainerUObjectPtrToValuePtrInternal(), ContainerVoidPtrToValuePtrInternal(), GetOffset_ForDebug(), GetOffset_ForGC(), GetOffset_ForInternal(), GetOffset_ForUFunction(), GetOffset_ReplaceWith_ContainerPtrToValuePtr(), IsInContainer(), IsInContainer(), and PointerToValuePtr().
PostConstructLinkNext
FProperty* FProperty::PostConstructLinkNext
In memory only: Linked list of properties requiring post constructor initialization.
Definition at line 211 of file UnrealType.h.
PropertyFlags
EPropertyFlags FProperty::PropertyFlags
Definition at line 189 of file UnrealType.h.
Referenced by FScriptSetHelper::AddElement(), ClearPropertyFlags(), ContainsFinishDestroy(), ContainsInstancedObjectProperty(), CopyCompleteValue(), CopySingleValue(), FGameModeInfoCustomizer::CustomizeGameModeDefaultClass(), DestroyValue(), DestroyValue_InContainer(), FinishDestroy(), FinishDestroy_InContainer(), GetPropertyFlags(), GetReplicatedProperty(), GetRepOwner(), HasAllPropertyFlags(), HasAnyPropertyFlags(), FObjectProperty::HasIntrusiveUnsetOptionalState(), InitializeValue(), InitializeValue_InContainer(), IsEditorOnlyProperty(), and SetPropertyFlags().
PropertyLinkNext
FProperty* FProperty::PropertyLinkNext
In memory only: Linked list of properties from most-derived to base.
Definition at line 205 of file UnrealType.h.
RepIndex
uint16 FProperty::RepIndex
Definition at line 190 of file UnrealType.h.
RepNotifyFunc
FName FProperty::RepNotifyFunc
Definition at line 213 of file UnrealType.h.
The documentation for this class was generated from the following file:
Runtime/CoreUObject/Public/UObject/UnrealType.h