Unreal Engine 5.6 C++ API: UKismetStringLibrary Class Reference
UKismetStringLibrary Class Reference
#include "KismetStringLibrary.h"
Private Member Functions
This method has been deprecated and will be removed Please use FString::SanitizeFloat () or LexToSanitzedString instead.") static 1 FString Conv_FloatToString(float InFloat)
GENERATED_UCLASS_BODY () UE_DEPRECATED(5.0
Converts a float value to a string.
UE_DEPRECATED (5.0, "This method has been deprecated and will be removed. Please use FString::Printf instead.") static 1 FString BuildString_Float(const FString &AppendTo
Converts a float->string, create a new string in the form AppendTo+Prefix+InFloat+Suffix.
UE_DEPRECATED (5.0, "This method has been deprecated and will be removed. Please use LexFromString instead.") static 1 float Conv_StringToFloat(const FString &InString)
Converts a string to a float value.
UFUNCTION ()
Converts a string to a name value.
UFUNCTION ()
Converts a string to a int value.
UFUNCTION ()
Converts a string to a int value.
UFUNCTION ()
Converts a string to a double value.
UFUNCTION ()
Convert String Back To Vector.
UFUNCTION ()
Convert String Back To Float Vector.
UFUNCTION ()
Convert String Back To Vector2D.
UFUNCTION ()
Convert String Back To Rotator.
UFUNCTION ()
Convert String Back To Color.
UFUNCTION ()
Concatenates two strings together to make a new string.
UFUNCTION () "
Converts a double value to a string.
UFUNCTION () "
Converts an integer value to a string.
UFUNCTION () "
Converts an 64-bit integer value to a string.
UFUNCTION () "
Converts a byte value to a string.
UFUNCTION () "
Converts a boolean value to a string, either 'true' or 'false'.
UFUNCTION () "
Converts a vector value to a string, in the form 'X= Y= Z='.
UFUNCTION () "
Converts a float vector value to a string, in the form 'X= Y= Z='.
UFUNCTION () "
Converts an IntVector value to a string, in the form 'X= Y= Z='.
UFUNCTION () "
Converts an IntVector2 value to a string, in the form 'X= Y='.
UFUNCTION () "
Converts an IntPoint value to a string, in the form 'X= Y='.
UFUNCTION () "
Converts a vector2d value to a string, in the form 'X= Y='.
UFUNCTION () "
Converts a rotator value to a string, in the form 'P= Y= R='.
UFUNCTION () "
Converts a transform value to a string, in the form 'Translation: X= Y= Z= Rotation: P= Y= R= Scale: X= Y= Z='.
UFUNCTION () "
Converts a UObject value to a string by calling the object's GetName method.
UFUNCTION () "
Converts a FBox value to a string.
UFUNCTION () "
Converts a FBox value to a string of its Center and Extents values.
UFUNCTION () "
Converts a InputDeviceId value to a string.
UFUNCTION () "
Converts a PlatformUserId value to a string.
UFUNCTION () "
Converts a linear color value to a string, in the form '(R=,G=,B=,A=)'.
UFUNCTION () "
Converts a name value to a string.
UFUNCTION () "
Converts a name value to a string.
UFUNCTION () "
Test if the input strings are equal (A == B)
UFUNCTION () "
Test if the input strings are equal (A == B), ignoring case.
UFUNCTION () "
Test if the input string are not equal (A != B)
UFUNCTION () "
Test if the input string are not equal (A != B), ignoring case differences.
UFUNCTION () ")
Converts a double->string, create a new string in the form AppendTo+Prefix+InDouble+Suffix.
UFUNCTION () ")
Converts a int->string, creating a new string in the form AppendTo+Prefix+InInt+Suffix.
UFUNCTION () ")
Converts a boolean->string, creating a new string in the form AppendTo+Prefix+InBool+Suffix.
UFUNCTION () ")
Converts a vector->string, creating a new string in the form AppendTo+Prefix+InVector+Suffix.
UFUNCTION () ")
Converts an IntVector->string, creating a new string in the form AppendTo+Prefix+InIntVector+Suffix.
UFUNCTION () ")
Converts an IntVector2->string, creating a new string in the form AppendTo+Prefix+InIntVector+Suffix.
UFUNCTION () ")
Converts a vector2d->string, creating a new string in the form AppendTo+Prefix+InVector2d+Suffix.
UFUNCTION () ")
Converts a rotator->string, creating a new string in the form AppendTo+Prefix+InRot+Suffix.
UFUNCTION () ")
Converts a object->string, creating a new string in the form AppendTo+Prefix+object name+Suffix.
UFUNCTION () ")
Converts a color->string, creating a new string in the form AppendTo+Prefix+InColor+Suffix.
UFUNCTION () ")
Converts a color->string, creating a new string in the form AppendTo+Prefix+InName+Suffix.
UFUNCTION () static 1 bool Contains(const FString &SearchIn
Returns whether this string contains the specified substring.
UFUNCTION () static 1 bool EndsWith(const FString &SourceString
Test whether this string ends with given string.
UFUNCTION () static 1 bool IsNumeric(const FString &SourceString)
UFUNCTION () static 1 bool MatchesWildcard(const FString &SourceString
Searches this string for a given wild card.
UFUNCTION () static 1 bool Split(const FString &SourceString
Splits this string at given string position case sensitive.
UFUNCTION () static 1 bool StartsWith(const FString &SourceString
Test whether this string starts with given string.
UFUNCTION () static 1 FString DiffString(const FString &First
Returns a string describing the LCS difference between two strings, First and Second.
UFUNCTION () static 1 FString GetSubstring(const FString &SourceString
Returns a substring from the string starting at the specified position.
UFUNCTION () static 1 FString JoinStringArray(const TArray< FString > &SourceArray
Concatenates an array of strings into a single string.
UFUNCTION () static 1 FString Left(const FString &SourceString
Returns the left most given number of characters.
UFUNCTION () static 1 FString LeftChop(const FString &SourceString
Returns the left most characters from the string chopping the given number of characters from the end.
UFUNCTION () static 1 FString LeftPad(const FString &SourceString
UFUNCTION () static 1 FString Mid(const FString &SourceString
Returns the substring from Start position for Count characters.
UFUNCTION () static 1 FString Replace(const FString &SourceString
Replace all occurrences of a substring in this string.
UFUNCTION () static 1 FString Reverse(const FString &SourceString)
Returns a copy of this string, with the characters in reverse order.
UFUNCTION () static 1 FString Right(const FString &SourceString
Returns the string to the right of the specified location, counting back from the right (end of the word).
UFUNCTION () static 1 FString RightChop(const FString &SourceString
Returns the string to the right of the specified location, counting forward from the left (from the beginning of the word).
UFUNCTION () static 1 FString RightPad(const FString &SourceString
UFUNCTION () static 1 FString TimeSecondsToString(float InSeconds)
Convert a number of seconds into minutes:seconds.milliseconds format string (including leading zeroes)
UFUNCTION () static 1 FString ToLower(const FString &SourceString)
Returns a string converted to Lower case.
UFUNCTION () static 1 FString ToUpper(const FString &SourceString)
Returns a string converted to Upper case.
UFUNCTION () static 1 FString Trim(const FString &SourceString)
Removes whitespace characters from the front of this string.
UFUNCTION () static 1 FString TrimTrailing(const FString &SourceString)
Removes trailing whitespace characters.
UFUNCTION () static 1 int32 CullArray(const FString &SourceString
Takes an array of strings and removes any zero length entries.
UFUNCTION () static 1 int32 FindSubstring(const FString &SearchIn
Finds the starting index of a substring in the a specified string.
UFUNCTION () static 1 int32 GetCharacterAsNumber(const FString &SourceString
Gets a single character from the string (as an integer)
UFUNCTION () static 1 int32 ReplaceInline(UPARAM(ref) FString &SourceString
Replace all occurrences of SearchText with ReplacementText in this string.
UFUNCTION () static 1 TArray< FString > GetCharacterArrayFromString(const FString &SourceString)
Returns an array that contains one entry for each character in SourceString.
UFUNCTION () static 1 TArray< FString > ParseIntoArray(const FString &SourceString
Gets an array of strings from a source string divided up by a separator and empty strings can optionally be culled.
UFUNCTION ()) static 1 bool IsEmpty(const FString &InString)
Returns true if the string is empty.
UFUNCTION ()) static 1 int32 Len(const FString &S)
Returns the number of characters in the string.
Private Attributes
BlueprintAutocast
const FString bool bool bSearchFromEnd = false
const FString bool bUseCase = false
Category
int32 ChCount
CompactNodeTitle = "->"
int32 Count
int32 int32 Count
const FString const bool CullEmptyStrings = true)
const FString & Delimiter = FString(TEXT(" "))
const FString & From
TArray< FString > & InArray
int32 Index = 0)
const FString float InFloat
const FString & InPrefix
const FString & InStr
const FString & InSuffix
const FString FString & LeftS
int32 int32 Length = 1)
const FString & Prefix
const FString const FString & ReplacementText
const FString FString FString & RightS
const FString ESearchCase::Type SearchCase = ESearchCase::IgnoreCase)
const FString const FString ESearchCase::Type SearchCase = ESearchCase::IgnoreCase)
const FString FString FString ESearchCase::Type SearchCase = ESearchCase::IgnoreCase
const FString FString FString ESearchCase::Type ESearchDir::Type SearchDir = ESearchDir::FromStart)
const FString & SearchText
const FString & Second
const FString & Separator = FString(TEXT(" ")))
int32 Start
int32 StartIndex = 0
const FString bool bool int32 StartPosition = -1)
const FString & Substring
const FString float const FString & Suffix
const FString const FString & To
const FString & Wildcard
Detailed Description
Definition at line 11 of file KismetStringLibrary.h.
Member Function Documentation
FString::SanitizeFloat()
This method has been deprecated and will be removed Please use UKismetStringLibrary::FString::SanitizeFloat () private
References InFloat, and UE_DEPRECATED().
GENERATED_UCLASS_BODY()
UKismetStringLibrary::GENERATED_UCLASS_BODY () private
Converts a float value to a string.
UE_DEPRECATED() [1/2]
UKismetStringLibrary::UE_DEPRECATED (5. 0, "This method has been deprecated and will be removed. Please use FString::Printf instead.") const & private
Converts a float->string, create a new string in the form AppendTo+Prefix+InFloat+Suffix.
Parameters
AppendTo - An existing string to use as the start of the conversion string
Prefix - A string to use as a prefix, after the AppendTo string
InFloat - The float value to convert
Suffix - A suffix to append to the end of the conversion string
Returns
A new string built from the passed parameters
References UE_DEPRECATED().
UE_DEPRECATED() [2/2]
UKismetStringLibrary::UE_DEPRECATED (5. 0, "This method has been deprecated and will be removed. Please use LexFromString instead.") const & private
Converts a string to a float value.
References UE_DEPRECATED().
Referenced by FString::SanitizeFloat(), UE_DEPRECATED(), and UE_DEPRECATED().
UFUNCTION() [1/77]
UKismetStringLibrary::UFUNCTION () private
Converts a string to a name value.
References BlueprintAutocast, Category, CompactNodeTitle, meta, and UFUNCTION().
UFUNCTION() [2/77]
UKismetStringLibrary::UFUNCTION () private
Converts a string to a int value.
References BlueprintAutocast, Category, CompactNodeTitle, meta, and UFUNCTION().
UFUNCTION() [3/77]
UKismetStringLibrary::UFUNCTION () private
Converts a string to a int value.
References BlueprintAutocast, Category, CompactNodeTitle, meta, and UFUNCTION().
UFUNCTION() [4/77]
UKismetStringLibrary::UFUNCTION () private
Converts a string to a double value.
References BlueprintAutocast, Category, CompactNodeTitle, meta, and UFUNCTION().
UFUNCTION() [5/77]
UKismetStringLibrary::UFUNCTION () private
Convert String Back To Vector.
IsValid indicates whether or not the string could be successfully converted.
References Category, CompactNodeTitle, FVector, meta, and UFUNCTION().
UFUNCTION() [6/77]
UKismetStringLibrary::UFUNCTION () private
Convert String Back To Float Vector.
IsValid indicates whether or not the string could be successfully converted.
References Category, CompactNodeTitle, meta, and UFUNCTION().
UFUNCTION() [7/77]
UKismetStringLibrary::UFUNCTION () private
Convert String Back To Vector2D.
IsValid indicates whether or not the string could be successfully converted.
References Category, CompactNodeTitle, meta, and UFUNCTION().
UFUNCTION() [8/77]
UKismetStringLibrary::UFUNCTION () private
Convert String Back To Rotator.
IsValid indicates whether or not the string could be successfully converted.
References Category, CompactNodeTitle, meta, and UFUNCTION().
UFUNCTION() [9/77]
UKismetStringLibrary::UFUNCTION () private
Convert String Back To Color.
IsValid indicates whether or not the string could be successfully converted.
References Category, CompactNodeTitle, meta, and UFUNCTION().
UFUNCTION() [10/77]
UKismetStringLibrary::UFUNCTION () private
Concatenates two strings together to make a new string.
Parameters
A - The original string
B - The string to append to A
Returns
A new string which is the concatenation of A+B
References A, B, Category, meta, and UFUNCTION().
UFUNCTION() [11/77]
UKismetStringLibrary::UFUNCTION () private
Converts a double value to a string.
Referenced by UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
UFUNCTION() [12/77]
UKismetStringLibrary::UFUNCTION () private
Converts an integer value to a string.
References BlueprintAutocast, Category, CompactNodeTitle, meta, and UFUNCTION().
UFUNCTION() [13/77]
UKismetStringLibrary::UFUNCTION () private
Converts an 64-bit integer value to a string.
References BlueprintAutocast, Category, CompactNodeTitle, meta, and UFUNCTION().
UFUNCTION() [14/77]
UKismetStringLibrary::UFUNCTION () private
Converts a byte value to a string.
References BlueprintAutocast, Category, CompactNodeTitle, meta, and UFUNCTION().
UFUNCTION() [15/77]
UKismetStringLibrary::UFUNCTION () private
Converts a boolean value to a string, either 'true' or 'false'.
References BlueprintAutocast, Category, CompactNodeTitle, meta, and UFUNCTION().
UFUNCTION() [16/77]
UKismetStringLibrary::UFUNCTION () private
Converts a vector value to a string, in the form 'X= Y= Z='.
References BlueprintAutocast, Category, CompactNodeTitle, FVector, meta, and UFUNCTION().
UFUNCTION() [17/77]
UKismetStringLibrary::UFUNCTION () private
Converts a float vector value to a string, in the form 'X= Y= Z='.
References BlueprintAutocast, Category, CompactNodeTitle, meta, and UFUNCTION().
UFUNCTION() [18/77]
UKismetStringLibrary::UFUNCTION () private
Converts an IntVector value to a string, in the form 'X= Y= Z='.
References BlueprintAutocast, Category, CompactNodeTitle, meta, and UFUNCTION().
UFUNCTION() [19/77]
UKismetStringLibrary::UFUNCTION () private
Converts an IntVector2 value to a string, in the form 'X= Y='.
References BlueprintAutocast, Category, CompactNodeTitle, meta, and UFUNCTION().
UFUNCTION() [20/77]
UKismetStringLibrary::UFUNCTION () private
Converts an IntPoint value to a string, in the form 'X= Y='.
References BlueprintAutocast, Category, CompactNodeTitle, meta, and UFUNCTION().
UFUNCTION() [21/77]
UKismetStringLibrary::UFUNCTION () private
Converts a vector2d value to a string, in the form 'X= Y='.
References BlueprintAutocast, Category, CompactNodeTitle, meta, and UFUNCTION().
UFUNCTION() [22/77]
UKismetStringLibrary::UFUNCTION () private
Converts a rotator value to a string, in the form 'P= Y= R='.
References BlueprintAutocast, Category, CompactNodeTitle, meta, and UFUNCTION().
UFUNCTION() [23/77]
UKismetStringLibrary::UFUNCTION () private
Converts a transform value to a string, in the form 'Translation: X= Y= Z= Rotation: P= Y= R= Scale: X= Y= Z='.
References BlueprintAutocast, Category, CompactNodeTitle, meta, and UFUNCTION().
UFUNCTION() [24/77]
UKismetStringLibrary::UFUNCTION () private
Converts a UObject value to a string by calling the object's GetName method.
References BlueprintAutocast, Category, CompactNodeTitle, meta, and UFUNCTION().
UFUNCTION() [25/77]
UKismetStringLibrary::UFUNCTION () private
Converts a FBox value to a string.
References BlueprintAutocast, Box, Category, CompactNodeTitle, meta, and UFUNCTION().
UFUNCTION() [26/77]
UKismetStringLibrary::UFUNCTION () private
Converts a FBox value to a string of its Center and Extents values.
References BlueprintAutocast, Box, Category, CompactNodeTitle, meta, and UFUNCTION().
UFUNCTION() [27/77]
UKismetStringLibrary::UFUNCTION () private
Converts a InputDeviceId value to a string.
References BlueprintAutocast, Category, CompactNodeTitle, meta, and UFUNCTION().
UFUNCTION() [28/77]
UKismetStringLibrary::UFUNCTION () private
Converts a PlatformUserId value to a string.
References BlueprintAutocast, Category, CompactNodeTitle, meta, and UFUNCTION().
UFUNCTION() [29/77]
UKismetStringLibrary::UFUNCTION () private
Converts a linear color value to a string, in the form '(R=,G=,B=,A=)'.
References BlueprintAutocast, Category, CompactNodeTitle, meta, and UFUNCTION().
UFUNCTION() [30/77]
UKismetStringLibrary::UFUNCTION () private
Converts a name value to a string.
References BlueprintAutocast, Category, CompactNodeTitle, InName, meta, and UFUNCTION().
UFUNCTION() [31/77]
UKismetStringLibrary::UFUNCTION () private
Converts a name value to a string.
References BlueprintAutocast, Category, CompactNodeTitle, meta, and UFUNCTION().
UFUNCTION() [32/77]
UKismetStringLibrary::UFUNCTION () private
Test if the input strings are equal (A == B)
Parameters
A - The string to compare against
B - The string to compare
Returns
True if the strings are equal, false otherwise
References A, B, Category, CompactNodeTitle, meta, and UFUNCTION().
UFUNCTION() [33/77]
UKismetStringLibrary::UFUNCTION () private
Test if the input strings are equal (A == B), ignoring case.
Parameters
A - The string to compare against
B - The string to compare
Returns
True if the strings are equal, false otherwise
References A, B, Category, CompactNodeTitle, meta, and UFUNCTION().
UFUNCTION() [34/77]
UKismetStringLibrary::UFUNCTION () private
Test if the input string are not equal (A != B)
Parameters
A - The string to compare against
B - The string to compare
Returns
Returns true if the input strings are not equal, false if they are equal
References A, B, Category, CompactNodeTitle, meta, and UFUNCTION().
UFUNCTION() [35/77]
UKismetStringLibrary::UFUNCTION () private
Test if the input string are not equal (A != B), ignoring case differences.
Parameters
A - The string to compare against
B - The string to compare
Returns
Returns true if the input strings are not equal, false if they are equal
References A, B, Category, CompactNodeTitle, meta, and UFUNCTION().
UFUNCTION() [36/77]
UKismetStringLibrary::UFUNCTION () private
Converts a double->string, create a new string in the form AppendTo+Prefix+InDouble+Suffix.
Parameters
AppendTo - An existing string to use as the start of the conversion string
Prefix - A string to use as a prefix, after the AppendTo string
InDouble - The double value to convert
Suffix - A suffix to append to the end of the conversion string
Returns
A new string built from the passed parameters
References Category, meta, Prefix, Suffix, and UFUNCTION().
UFUNCTION() [37/77]
UKismetStringLibrary::UFUNCTION () private
Converts a int->string, creating a new string in the form AppendTo+Prefix+InInt+Suffix.
Parameters
AppendTo - An existing string to use as the start of the conversion string
Prefix - A string to use as a prefix, after the AppendTo string
InInt - The int value to convert
Suffix - A suffix to append to the end of the conversion string
Returns
A new string built from the passed parameters
References Category, meta, Prefix, Suffix, and UFUNCTION().
UFUNCTION() [38/77]
UKismetStringLibrary::UFUNCTION () private
Converts a boolean->string, creating a new string in the form AppendTo+Prefix+InBool+Suffix.
Parameters
AppendTo - An existing string to use as the start of the conversion string
Prefix - A string to use as a prefix, after the AppendTo string
InBool - The bool value to convert. Will add "true" or "false" to the conversion string
Suffix - A suffix to append to the end of the conversion string
Returns
A new string built from the passed parameters
References Category, meta, Prefix, Suffix, and UFUNCTION().
UFUNCTION() [39/77]
UKismetStringLibrary::UFUNCTION () private
Converts a vector->string, creating a new string in the form AppendTo+Prefix+InVector+Suffix.
Parameters
AppendTo - An existing string to use as the start of the conversion string
Prefix - A string to use as a prefix, after the AppendTo string
InVector - The vector value to convert. Uses the standard FVector::ToString conversion
Suffix - A suffix to append to the end of the conversion string
Returns
A new string built from the passed parameters
References Category, FVector, meta, Prefix, Suffix, and UFUNCTION().
UFUNCTION() [40/77]
UKismetStringLibrary::UFUNCTION () private
Converts an IntVector->string, creating a new string in the form AppendTo+Prefix+InIntVector+Suffix.
Parameters
AppendTo - An existing string to use as the start of the conversion string
Prefix - A string to use as a prefix, after the AppendTo string
InIntVector - The intVector value to convert. Uses the standard FVector::ToString conversion
Suffix - A suffix to append to the end of the conversion string
Returns
A new string built from the passed parameters
References Category, meta, Prefix, Suffix, and UFUNCTION().
UFUNCTION() [41/77]
UKismetStringLibrary::UFUNCTION () private
Converts an IntVector2->string, creating a new string in the form AppendTo+Prefix+InIntVector+Suffix.
Parameters
AppendTo - An existing string to use as the start of the conversion string
Prefix - A string to use as a prefix, after the AppendTo string
InIntVector - The intVector2 value to convert. Uses the standard FVector::ToString conversion
Suffix - A suffix to append to the end of the conversion string
Returns
A new string built from the passed parameters
References Category, meta, Prefix, Suffix, and UFUNCTION().
UFUNCTION() [42/77]
UKismetStringLibrary::UFUNCTION () private
Converts a vector2d->string, creating a new string in the form AppendTo+Prefix+InVector2d+Suffix.
Parameters
AppendTo - An existing string to use as the start of the conversion string
Prefix - A string to use as a prefix, after the AppendTo string
InVector2d - The vector2d value to convert. Uses the standard FVector2D::ToString conversion
Suffix - A suffix to append to the end of the conversion string
Returns
A new string built from the passed parameters
References Category, meta, Prefix, Suffix, and UFUNCTION().
UFUNCTION() [43/77]
UKismetStringLibrary::UFUNCTION () private
Converts a rotator->string, creating a new string in the form AppendTo+Prefix+InRot+Suffix.
Parameters
AppendTo - An existing string to use as the start of the conversion string
Prefix - A string to use as a prefix, after the AppendTo string
InRot - The rotator value to convert. Uses the standard ToString conversion
Suffix - A suffix to append to the end of the conversion string
Returns
A new string built from the passed parameters
References Category, meta, Prefix, Suffix, and UFUNCTION().
UFUNCTION() [44/77]
UKismetStringLibrary::UFUNCTION () private
Converts a object->string, creating a new string in the form AppendTo+Prefix+object name+Suffix.
Parameters
AppendTo - An existing string to use as the start of the conversion string
Prefix - A string to use as a prefix, after the AppendTo string
InObj - The object to convert. Will insert the name of the object into the conversion string
Suffix - A suffix to append to the end of the conversion string
Returns
A new string built from the passed parameters
References Category, meta, Prefix, Suffix, and UFUNCTION().
UFUNCTION() [45/77]
UKismetStringLibrary::UFUNCTION () private
Converts a color->string, creating a new string in the form AppendTo+Prefix+InColor+Suffix.
Parameters
AppendTo - An existing string to use as the start of the conversion string
Prefix - A string to use as a prefix, after the AppendTo string
InColor - The linear color value to convert. Uses the standard ToString conversion
Suffix - A suffix to append to the end of the conversion string
Returns
A new string built from the passed parameters
References Category, meta, Prefix, Suffix, and UFUNCTION().
UFUNCTION() [46/77]
UKismetStringLibrary::UFUNCTION () private
Converts a color->string, creating a new string in the form AppendTo+Prefix+InName+Suffix.
Parameters
AppendTo - An existing string to use as the start of the conversion string
Prefix - A string to use as a prefix, after the AppendTo string
InName - The name value to convert
Suffix - A suffix to append to the end of the conversion string
Returns
A new string built from the passed parameters
References Category, InName, meta, Prefix, Suffix, and UFUNCTION().
UFUNCTION() [47/77]
UKismetStringLibrary::UFUNCTION () const & private
Returns whether this string contains the specified substring.
Parameters
SubStr Find to search for
SearchCase Indicates whether the search is case sensitive or not (defaults to ESearchCase::IgnoreCase)
SearchDir Indicates whether the search starts at the begining or at the end (defaults to ESearchDir::FromStart)
Returns
Returns whether the string contains the substring
References bSearchFromEnd, bUseCase, Category, Substring, and UFUNCTION().
UFUNCTION() [48/77]
UKismetStringLibrary::UFUNCTION () const & private
Test whether this string ends with given string.
Parameters
SearchCase Indicates whether the search is case sensitive or not (defaults to ESearchCase::IgnoreCase)
Returns
true if this string ends with specified text, false otherwise
References Category, and UFUNCTION().
UFUNCTION() [49/77]
UKismetStringLibrary::UFUNCTION () const & private
References Category, and UFUNCTION().
UFUNCTION() [50/77]
UKismetStringLibrary::UFUNCTION () const & private
Searches this string for a given wild card.
Parameters
Wildcard *?-type wildcard
SearchCase Indicates whether the search is case sensitive or not (defaults to ESearchCase::IgnoreCase)
Returns
true if this string matches the *?-type wildcard given.
Warning
This is a simple, SLOW routine. Use with caution
References Category, and UFUNCTION().
UFUNCTION() [51/77]
UKismetStringLibrary::UFUNCTION () const & private
Splits this string at given string position case sensitive.
Parameters
InStr The string to search and split at
LeftS out the string to the left of InStr, not updated if return is false
RightS out the string to the right of InStr, not updated if return is false
SearchCase Indicates whether the search is case sensitive or not (defaults to ESearchCase::IgnoreCase)
SearchDir Indicates whether the search starts at the begining or at the end (defaults to ESearchDir::FromStart)
Returns
true if string is split, otherwise false
References Category, and UFUNCTION().
UFUNCTION() [52/77]
UKismetStringLibrary::UFUNCTION () const & private
Test whether this string starts with given string.
Parameters
SearchCase Indicates whether the search is case sensitive or not (defaults to ESearchCase::IgnoreCase)
Returns
true if this string begins with specified text, false otherwise
References Category, and UFUNCTION().
UFUNCTION() [53/77]
UKismetStringLibrary::UFUNCTION () const & private
Returns a string describing the LCS difference between two strings, First and Second.
This function is editor only because it is expensive for large strings. Examples:
("A", "") -> "- [ 0001 | ] A" ("", "") -> "" ("The quick brown fox", "The quick red fox") -> "~ [ 0001 | 0001 ] The quick brown fox ~~~~~
The quick red fox"
The numbers between the [], separated by |, are the line numbers in the First and Second string at which the difference occurs. Preceding the line number information is a symbol identifying the type of difference: A tilde (~) indicates a modification, a minus (-) indicates a removal from First, and a plus (+) indicates an addition to second.
Parameters
First - The string to treat as basis
Second - The string to treat as change
Returns
the LCS difference between the First and Second string
References Category.
UFUNCTION() [54/77]
UKismetStringLibrary::UFUNCTION () const & private
Returns a substring from the string starting at the specified position.
Parameters
SourceString - The string to get the substring from
StartIndex - The location in SourceString to use as the start of the substring
Length The length of the requested substring
Returns
The requested substring
References Category, and UFUNCTION().
UFUNCTION() [55/77]
UKismetStringLibrary::UFUNCTION () const & private
Concatenates an array of strings into a single string.
Parameters
SourceArray - The array of strings to concatenate.
Separator - The string used to separate each element.
Returns
The final, joined, separated string.
References Category, and UFUNCTION().
UFUNCTION() [56/77]
UKismetStringLibrary::UFUNCTION () const & private
Returns the left most given number of characters.
References Category, and UFUNCTION().
UFUNCTION() [57/77]
UKismetStringLibrary::UFUNCTION () const & private
Returns the left most characters from the string chopping the given number of characters from the end.
References Category, Count, LeftChop, and UFUNCTION().
UFUNCTION() [58/77]
UKismetStringLibrary::UFUNCTION () const & private
References Category, and UFUNCTION().
UFUNCTION() [59/77]
UKismetStringLibrary::UFUNCTION () const & private
Returns the substring from Start position for Count characters.
References Category, and UFUNCTION().
UFUNCTION() [60/77]
UKismetStringLibrary::UFUNCTION () const & private
Replace all occurrences of a substring in this string.
Parameters
From substring to replace
To substring to replace From with
SearchCase Indicates whether the search is case sensitive or not (defaults to ESearchCase::IgnoreCase)
Returns
a copy of this string with the replacement made
References Category, and UFUNCTION().
UFUNCTION() [61/77]
UKismetStringLibrary::UFUNCTION () const & private
Returns a copy of this string, with the characters in reverse order.
References Category, and UFUNCTION().
UFUNCTION() [62/77]
UKismetStringLibrary::UFUNCTION () const & private
Returns the string to the right of the specified location, counting back from the right (end of the word).
References Category, Count, Right, and UFUNCTION().
UFUNCTION() [63/77]
UKismetStringLibrary::UFUNCTION () const & private
Returns the string to the right of the specified location, counting forward from the left (from the beginning of the word).
References Category, Count, RightChop, and UFUNCTION().
UFUNCTION() [64/77]
UKismetStringLibrary::UFUNCTION () const & private
References Category, ChCount, and UFUNCTION().
UFUNCTION() [65/77]
UKismetStringLibrary::UFUNCTION () private
Convert a number of seconds into minutes:seconds.milliseconds format string (including leading zeroes)
Returns
A new string built from the seconds parameter
References Category.
UFUNCTION() [66/77]
UKismetStringLibrary::UFUNCTION () const & private
Returns a string converted to Lower case.
Parameters
SourceString The string to convert
Returns
The string in lower case
References Category, and UFUNCTION().
UFUNCTION() [67/77]
UKismetStringLibrary::UFUNCTION () const & private
Returns a string converted to Upper case.
Parameters
SourceString The string to convert
Returns
The string in upper case
References Category, and UFUNCTION().
UFUNCTION() [68/77]
UKismetStringLibrary::UFUNCTION () const & private
Removes whitespace characters from the front of this string.
References Category, and UFUNCTION().
UFUNCTION() [69/77]
UKismetStringLibrary::UFUNCTION () const & private
Removes trailing whitespace characters.
References Category, and UFUNCTION().
UFUNCTION() [70/77]
UKismetStringLibrary::UFUNCTION () const & private
Takes an array of strings and removes any zero length entries.
Parameters
InArray The array to cull
Returns
The number of elements left in InArray
References Category, and UFUNCTION().
UFUNCTION() [71/77]
UKismetStringLibrary::UFUNCTION () const & private
Finds the starting index of a substring in the a specified string.
Parameters
SearchIn The string to search within
Substring The string to look for in the SearchIn string
bUseCase Whether or not to be case-sensitive
bSearchFromEnd Whether or not to start the search from the end of the string instead of the beginning
StartPosition The position to start the search from
Returns
The index (starting from 0 if bSearchFromEnd is false) of the first occurence of the substring
References Category, and UFUNCTION().
UFUNCTION() [72/77]
UKismetStringLibrary::UFUNCTION () const & private
Gets a single character from the string (as an integer)
Parameters
SourceString - The string to convert
Index - Location of the character whose value is required
Returns
The integer value of the character or 0 if index is out of range
References Category, and UFUNCTION().
UFUNCTION() [73/77]
UKismetStringLibrary::UFUNCTION () & private
Replace all occurrences of SearchText with ReplacementText in this string.
Parameters
SearchText the text that should be removed from this string
ReplacementText the text to insert in its place
SearchCase Indicates whether the search is case sensitive or not (defaults to ESearchCase::IgnoreCase)
Returns
the number of occurrences of SearchText that were replaced.
References Category, and UFUNCTION().
UFUNCTION() [74/77]
UKismetStringLibrary::UFUNCTION () const & private
Returns an array that contains one entry for each character in SourceString.
Parameters
SourceString The string to break apart into characters
Returns
An array containing one entry for each character in SourceString
References Category, and UFUNCTION().
UFUNCTION() [75/77]
UKismetStringLibrary::UFUNCTION () const & private
Gets an array of strings from a source string divided up by a separator and empty strings can optionally be culled.
Parameters
SourceString - The string to chop up
Delimiter - The string to delimit on
CullEmptyStrings = true - Cull (true) empty strings or add them to the array (false)
Returns
The array of string that have been separated
References Category, and UFUNCTION().
UFUNCTION() [76/77]
UKismetStringLibrary::UFUNCTION () const & private
Returns true if the string is empty.
Parameters
InString - The string to check
Returns
Whether or not the string is empty
References Category, Keywords, meta, and UFUNCTION().
UFUNCTION() [77/77]
UKismetStringLibrary::UFUNCTION () const & private
Returns the number of characters in the string.
Parameters
SourceString - The string to measure
Returns
The number of chars in the string
References Category, CompactNodeTitle, Keywords, meta, and UFUNCTION().
Field Documentation
BlueprintAutocast
UKismetStringLibrary::BlueprintAutocast private
Definition at line 20 of file KismetStringLibrary.h.
Referenced by UFUNCTION(), and UFUNCTION().
bSearchFromEnd
const FString bool bool UKismetStringLibrary::bSearchFromEnd = false private
Definition at line 361 of file KismetStringLibrary.h.
Referenced by UFUNCTION().
bUseCase
const FString bool UKismetStringLibrary::bUseCase = false private
Definition at line 361 of file KismetStringLibrary.h.
Referenced by UFUNCTION().
Category
UKismetStringLibrary::Category private
Initial value:
= "Utilities|String")
    static 1 FString Conv_DoubleToString(double InDouble)
Definition at line 20 of file KismetStringLibrary.h.
Referenced by UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
ChCount
int32 UKismetStringLibrary::ChCount private
Definition at line 433 of file KismetStringLibrary.h.
Referenced by UFUNCTION().
CompactNodeTitle
UKismetStringLibrary::CompactNodeTitle = "->" private
Definition at line 20 of file KismetStringLibrary.h.
Referenced by UFUNCTION(), UFUNCTION(), and UFUNCTION().
Count [1/2]
int32 UKismetStringLibrary::Count private
Definition at line 547 of file KismetStringLibrary.h.
Referenced by UFUNCTION(), UFUNCTION(), and UFUNCTION().
Count [2/2]
int32 int32 UKismetStringLibrary::Count private
Definition at line 563 of file KismetStringLibrary.h.
CullEmptyStrings
const FString const bool UKismetStringLibrary::CullEmptyStrings = true) private
Definition at line 391 of file KismetStringLibrary.h.
Delimiter
const FString& UKismetStringLibrary::Delimiter = FString(TEXT(" ")) private
Definition at line 391 of file KismetStringLibrary.h.
From
const FString& UKismetStringLibrary::From private
Definition at line 518 of file KismetStringLibrary.h.
InArray
TArray<FString>& UKismetStringLibrary::InArray private
Definition at line 501 of file KismetStringLibrary.h.
Index
int32 UKismetStringLibrary::Index = 0) private
Definition at line 381 of file KismetStringLibrary.h.
InFloat
const FString float UKismetStringLibrary::InFloat private
Definition at line 152 of file KismetStringLibrary.h.
Referenced by FString::SanitizeFloat().
InPrefix
const FString& UKismetStringLibrary::InPrefix private
Definition at line 459 of file KismetStringLibrary.h.
InStr
const FString& UKismetStringLibrary::InStr private
Definition at line 543 of file KismetStringLibrary.h.
InSuffix
const FString& UKismetStringLibrary::InSuffix private
Definition at line 468 of file KismetStringLibrary.h.
LeftS
const FString FString& UKismetStringLibrary::LeftS private
Definition at line 543 of file KismetStringLibrary.h.
Length
int32 int32 UKismetStringLibrary::Length = 1) private
Definition at line 349 of file KismetStringLibrary.h.
Prefix
const FString& UKismetStringLibrary::Prefix private
Definition at line 152 of file KismetStringLibrary.h.
Referenced by UFUNCTION().
ReplacementText
const FString const FString& UKismetStringLibrary::ReplacementText private
Definition at line 530 of file KismetStringLibrary.h.
RightS
const FString FString FString& UKismetStringLibrary::RightS private
Definition at line 543 of file KismetStringLibrary.h.
SearchCase [1/3]
const FString const FString ESearchCase::Type UKismetStringLibrary::SearchCase = ESearchCase::IgnoreCase) private
Definition at line 459 of file KismetStringLibrary.h.
SearchCase [2/3]
const FString const FString ESearchCase::Type UKismetStringLibrary::SearchCase = ESearchCase::IgnoreCase) private
Definition at line 518 of file KismetStringLibrary.h.
SearchCase [3/3]
const FString FString FString ESearchCase::Type UKismetStringLibrary::SearchCase = ESearchCase::IgnoreCase private
Definition at line 543 of file KismetStringLibrary.h.
SearchDir
const FString FString FString ESearchCase::Type ESearchDir::Type UKismetStringLibrary::SearchDir = ESearchDir::FromStart) private
Definition at line 543 of file KismetStringLibrary.h.
SearchText
const FString& UKismetStringLibrary::SearchText private
Definition at line 530 of file KismetStringLibrary.h.
Second
const FString& UKismetStringLibrary::Second private
Definition at line 587 of file KismetStringLibrary.h.
Separator
const FString& UKismetStringLibrary::Separator = FString(TEXT(" "))) private
Definition at line 400 of file KismetStringLibrary.h.
Start
int32 UKismetStringLibrary::Start private
Definition at line 563 of file KismetStringLibrary.h.
StartIndex
int32 UKismetStringLibrary::StartIndex = 0 private
Definition at line 349 of file KismetStringLibrary.h.
StartPosition
const FString bool bool int32 UKismetStringLibrary::StartPosition = -1) private
Definition at line 361 of file KismetStringLibrary.h.
Substring
const FString & UKismetStringLibrary::Substring private
Definition at line 361 of file KismetStringLibrary.h.
Referenced by UFUNCTION().
Suffix
const FString float const FString& UKismetStringLibrary::Suffix private
Definition at line 152 of file KismetStringLibrary.h.
Referenced by UFUNCTION().
To
const FString const FString& UKismetStringLibrary::To private
Definition at line 518 of file KismetStringLibrary.h.
Wildcard
const FString& UKismetStringLibrary::Wildcard private
Definition at line 479 of file KismetStringLibrary.h.
The documentation for this class was generated from the following file:
Runtime/Engine/Classes/Kismet/KismetStringLibrary.h