Unreal Engine 5.6 C++ API: FSkeletalMeshStreamIn_IO Class Reference
FSkeletalMeshStreamIn_IO Class Reference
#include "SkeletalMeshUpdate.h"
Data Structures
class FCancelIORequestsTask
Public Member Functions
FSkeletalMeshStreamIn_IO (const USkeletalMesh *InMesh, bool bHighPrio, EThreadType CreateResourcesThread)
virtual ~FSkeletalMeshStreamIn_IO ()
virtual void Abort () override
Cancel the current update.
Public Member Functions inherited from FSkeletalMeshStreamIn
FSkeletalMeshStreamIn (const USkeletalMesh *InMesh, EThreadType CreateResourcesThread)
virtual ~FSkeletalMeshStreamIn ()
Public Member Functions inherited from FSkeletalMeshUpdate
FSkeletalMeshUpdate (const USkeletalMesh *InMesh)
virtual ~FSkeletalMeshUpdate ()
Public Member Functions inherited from TRenderAssetUpdate< FSkelMeshUpdateContext >
TRenderAssetUpdate (const UStreamableRenderAsset *InAsset)
EThreadType GetRelevantThread () const final override
Return the thread relevant to the next step of execution.
void PushTask (const FContext &Context, EThreadType InTaskThread, const FCallback &InTaskCallback, EThreadType InCancelationThread, const FCallback &InCancelationCallback)
Defines the next step to be executed.
Public Member Functions inherited from FRenderAssetUpdate
FRenderAssetUpdate (const UStreamableRenderAsset *InAsset)
FReturnedRefCountValue AddRef () const final override
ETaskState DoLock ()
Perform a lock on the object, preventing any other thread from processing a pending task in Tick().
void DoUnlock (ETaskState PreviousTaskState)
Release any lock on the object, allowing other thread to modify it.
uint32 GetRefCount () const final override
bool IsCancelled () const
Returns whether the task was aborted through Abort() or cancelled.
bool IsCompleted () const
Returns whether the task has finished executing and there is no other thread possibly accessing it.
bool IsLocked () const
bool IsSuccessfullyFinished () const
Returns whether this update has finished successfully.
uint32 Release () const final override
void Tick (EThreadType InCurrentThread)
Do or schedule any pending work for a given texture.
Public Member Functions inherited from IRefCountedObject
virtual ~IRefCountedObject ()
Protected Types
typedef FAutoDeleteAsyncTask< FCancelIORequestsTask > FAsyncCancelIORequestsTask
Protected Types inherited from FRenderAssetUpdate
typedef FAutoDeleteAsyncTask< FMipUpdateTask > FAsyncMipUpdateTask
The async task to update this object, only one can be active at anytime.
Protected Member Functions
void Cancel (const FContext &Context)
Cancel and report IO error.
void CancelIORequest ()
Called by FAsyncCancelIORequestsTask to cancel inflight IO request if any.
void ClearIORequest (const FContext &Context)
Release IORequest and IOFileHandle.
void DoCancelIO (const FContext &Context)
void DoCreateBuffers (const FContext &Context)
void DoInitiateIO (const FContext &Context)
void DoSerializeLODData (const FContext &Context)
void ReportIOError (const FContext &Context)
Report IO errors if any.
void SerializeLODData (const FContext &Context)
Serialize data of new LODs to corresponding FStaticMeshLODResources.
void SetIORequest (const FContext &Context)
Create a new async IO request to read in LOD data.
Protected Member Functions inherited from FSkeletalMeshStreamIn
void CreateBuffers (const FContext &Context)
Create buffers with new LOD data.
void DiscardNewLODs (const FContext &Context)
Discard newly streamed-in CPU data.
void DoCancel (const FContext &Context)
Discard streamed-in CPU data and intermediate RHI buffers.
void DoFinishUpdate (const FContext &Context)
Apply the new buffers (if not cancelled) and finish the update process.
Protected Member Functions inherited from TRenderAssetUpdate< FSkelMeshUpdateContext >
void ClearCallbacks ()
ETaskState TickInternal (EThreadType InCurrentThread, bool bCheckForSuspension) final override
Protected Member Functions inherited from FRenderAssetUpdate
virtual ~FRenderAssetUpdate ()
void MarkAsCancelled ()
Set the task state as cancelled.
void MarkAsSuccessfullyFinished ()
void ScheduleAsyncTask ()
void ScheduleGTTask ()
void ScheduleRenderTask ()
Protected Attributes
bool bFailedOnIOError = false
bool bHighPrioIORequest
FIoBuffer BulkData
Bulk data I/O buffer.
FBulkDataBatchRequest BulkDataRequest
Handle to bulk data I/O request.
Protected Attributes inherited from FSkeletalMeshStreamIn
const EThreadType CreateResourcesThread
The thread to use for recording the above command list.
FIntermediateBuffers IntermediateBuffersArray [MAX_MESH_LOD_COUNT]
The intermediate buffers created in the update process.
FRHICommandList * StreamingRHICmdList = nullptr
RHI command list used for creating buffers and replacing the streaming placeholders.
Protected Attributes inherited from TRenderAssetUpdate< FSkelMeshUpdateContext >
FCallback CancelationCallback
The callback handling the cancellation of the update (only if the update gets cancelled).
EThreadType CancelationThread
The thread on which to call the cancellation of the update (only if the update gets cancelled).
FCallback TaskCallback
The callback that will perform the next step of the update.
EThreadType TaskThread
The thread on which to call the next step of the update, being TaskCallback.
Protected Attributes inherited from FRenderAssetUpdate
bool bDeferExecution
Defer execution even if a task pushes a new task on the same thread.
bool bIsCancelled
Whether the task has been cancelled because the update could not proceed or because the user called Abort().
bool bSuccess
Whether this update finished successfully.
FCriticalSection CS
Critical Section.
const int32 CurrentFirstLODIdx = INDEX_NONE
const int32 PendingFirstLODIdx = INDEX_NONE
const FStreamableRenderResourceState ResourceState
The streamable state requested.
int32 ScheduledAsyncTasks
Number of Ticks scheduled on async tasks.
int32 ScheduledGTTasks
Number of Ticks scheduled on the game thread.
int32 ScheduledRenderTasks
Number of Ticks scheduled on the render thread.
const UStreamableRenderAsset * StreamableAsset = nullptr
The asset updated.
volatile ETaskState TaskState
The state of the work yet to be performed to complete the update or cancelation.
FThreadSafeCounter TaskSynchronization
Synchronization used for trigger the task next step execution.
Friends
class FCancelIORequestsTask
Additional Inherited Members
Public Types inherited from TRenderAssetUpdate< FSkelMeshUpdateContext >
typedef TFunction< void(const FContext &Context)> FCallback
A callback used to perform a task in the update process.
typedef FSkelMeshUpdateContext FContext
Public Types inherited from FRenderAssetUpdate
enum ETaskState {
TS_Done , TS_Suspended , TS_InProgress , TS_Locked ,
TS_Init
}
The state of scheduled work for the update process.
enum EThreadType {
TT_None , TT_Render , TT_Async , TT_GameThread ,
TT_GameRunningAsync
}
A thread type used for doing a part of the update process.
Detailed Description
Definition at line 170 of file SkeletalMeshUpdate.h.
Member Typedef Documentation
FAsyncCancelIORequestsTask
typedef FAutoDeleteAsyncTask<FCancelIORequestsTask> FSkeletalMeshStreamIn_IO::FAsyncCancelIORequestsTask protected
Definition at line 198 of file SkeletalMeshUpdate.h.
Constructor & Destructor Documentation
FSkeletalMeshStreamIn_IO()
FSkeletalMeshStreamIn_IO::FSkeletalMeshStreamIn_IO (const USkeletalMesh * InMesh, bool bHighPrio, EThreadType CreateResourcesThread)
Definition at line 608 of file SkeletalMeshUpdate.cpp.
References FSkeletalMeshStreamIn::FSkeletalMeshStreamIn(), bHighPrioIORequest, FSkeletalMeshStreamIn::CreateResourcesThread, DoInitiateIO(), TRenderAssetUpdate< FSkelMeshUpdateContext >::PushTask(), SRA_UPDATE_CALLBACK, FRenderAssetUpdate::TT_Async, and FRenderAssetUpdate::TT_None.
Referenced by FSkeletalMeshStreamIn_IO::FCancelIORequestsTask::FCancelIORequestsTask().
~FSkeletalMeshStreamIn_IO()
virtual FSkeletalMeshStreamIn_IO::~FSkeletalMeshStreamIn_IO () inline virtual
Definition at line 175 of file SkeletalMeshUpdate.h.
Member Function Documentation
Abort()
void FSkeletalMeshStreamIn_IO::Abort () override virtual
Cancel the current update.
Will also attempt to cancel pending IO requests, see FTexture2DStreamIn_IO::Abort(). This is called outside of the update loop when a cancelation is required for external events.
Reimplemented from FSkeletalMeshUpdate.
Definition at line 423 of file SkeletalMeshUpdate.cpp.
References FSkeletalMeshUpdate::Abort(), BulkDataRequest, FRenderAssetUpdate::IsCancelled(), and FRenderAssetUpdate::IsCompleted().
Cancel()
void FSkeletalMeshStreamIn_IO::Cancel (const FContext & Context) protected
Cancel and report IO error.
Definition at line 594 of file SkeletalMeshUpdate.cpp.
References FSkeletalMeshStreamIn::DoCancel(), and ReportIOError().
Referenced by DoCancelIO(), and DoSerializeLODData().
CancelIORequest()
void FSkeletalMeshStreamIn_IO::CancelIORequest () protected
Called by FAsyncCancelIORequestsTask to cancel inflight IO request if any.
Definition at line 600 of file SkeletalMeshUpdate.cpp.
References BulkDataRequest.
ClearIORequest()
void FSkeletalMeshStreamIn_IO::ClearIORequest (const FContext & Context) protected
Release IORequest and IOFileHandle.
IORequest will be cancelled if still inflight
Definition at line 515 of file SkeletalMeshUpdate.cpp.
References BulkData, and BulkDataRequest.
Referenced by DoCancelIO(), and DoSerializeLODData().
DoCancelIO()
void FSkeletalMeshStreamIn_IO::DoCancelIO (const FContext & Context) protected
Definition at line 649 of file SkeletalMeshUpdate.cpp.
References Cancel(), ClearIORequest(), TRenderAssetUpdate< FSkelMeshUpdateContext >::PushTask(), SRA_UPDATE_CALLBACK, and FRenderAssetUpdate::TT_None.
Referenced by DoInitiateIO().
DoCreateBuffers()
void FSkeletalMeshStreamIn_IO::DoCreateBuffers (const FContext & Context) protected
Definition at line 635 of file SkeletalMeshUpdate.cpp.
References check, FSkeletalMeshStreamIn::CreateBuffers(), FSkeletalMeshStreamIn::DoFinishUpdate(), TRenderAssetUpdate< FSkelMeshUpdateContext >::PushTask(), SRA_UPDATE_CALLBACK, FRenderAssetUpdate::TaskSynchronization, and FRenderAssetUpdate::TT_Render.
Referenced by DoSerializeLODData().
DoInitiateIO()
void FSkeletalMeshStreamIn_IO::DoInitiateIO (const FContext & Context) protected
Definition at line 615 of file SkeletalMeshUpdate.cpp.
References check, DoCancelIO(), DoSerializeLODData(), TRenderAssetUpdate< FSkelMeshUpdateContext >::PushTask(), SetIORequest(), SRA_UPDATE_CALLBACK, and FRenderAssetUpdate::TT_Async.
Referenced by FSkeletalMeshStreamIn_IO().
DoSerializeLODData()
void FSkeletalMeshStreamIn_IO::DoSerializeLODData (const FContext & Context) protected
Definition at line 624 of file SkeletalMeshUpdate.cpp.
References Cancel(), check, ClearIORequest(), FSkeletalMeshStreamIn::CreateResourcesThread, DoCreateBuffers(), TRenderAssetUpdate< FSkelMeshUpdateContext >::PushTask(), SerializeLODData(), SRA_UPDATE_CALLBACK, and FRenderAssetUpdate::TT_Async.
Referenced by DoInitiateIO().
ReportIOError()
void FSkeletalMeshStreamIn_IO::ReportIOError (const FContext & Context) protected
Report IO errors if any.
Definition at line 527 of file SkeletalMeshUpdate.cpp.
References bFailedOnIOError, FRenderAssetUpdate::CurrentFirstLODIdx, IStreamingManager::Get(), FStreamingManagerCollection::GetRenderAssetStreamingManager(), IRenderAssetStreamingManager::MarkMountedStateDirty(), FRenderAssetUpdate::PendingFirstLODIdx, TEXT, UE_LOG, and Warning.
Referenced by Cancel().
SerializeLODData()
void FSkeletalMeshStreamIn_IO::SerializeLODData (const FContext & Context) protected
Serialize data of new LODs to corresponding FStaticMeshLODResources.
Definition at line 542 of file SkeletalMeshUpdate.cpp.
References Ar, bFailedOnIOError, BulkData, check, FRenderAssetUpdate::CurrentFirstLODIdx, Error, Fatal, FBulkData::GetBulkDataFlags(), FBulkData::GetBulkDataOffsetInFile(), FBulkData::GetBulkDataSize(), FBulkData::GetIoFilenameHash(), GLog, FRenderAssetUpdate::IsCancelled(), LLM_SCOPE_BYNAME, FRenderAssetUpdate::MarkAsCancelled(), Mesh, FRenderAssetUpdate::PendingFirstLODIdx, RenderData, FSkeletalMeshLODRenderData::SerializeStreamedData(), FSkeletalMeshLODRenderData::ShouldForceKeepCPUResources(), FSkeletalMeshLODRenderData::ShouldKeepCPUResources(), FSkeletalMeshLODRenderData::StreamingBulkData, FRenderAssetUpdate::TaskSynchronization, TEXT, and UE_LOG.
Referenced by DoSerializeLODData().
SetIORequest()
void FSkeletalMeshStreamIn_IO::SetIORequest (const FContext & Context) protected
Create a new async IO request to read in LOD data.
Definition at line 438 of file SkeletalMeshUpdate.cpp.
References AIOP_BelowNormal, AIOP_Low, AIOP_MAX, bFailedOnIOError, bHighPrioIORequest, FRenderAssetUpdate::bIsCancelled, BulkData, BulkDataRequest, check, FMath::Clamp(), FRenderAssetUpdate::CurrentFirstLODIdx, IConsoleManager::FindConsoleVariable(), IConsoleManager::Get(), IConsoleVariable::GetInt(), FRenderAssetUpdate::IsCancelled(), FBulkDataBatchRequest::FScatterGatherBuilder::Issue(), FRenderAssetUpdate::MarkAsCancelled(), Mesh, FBulkDataRequest::Ok, FRenderAssetUpdate::PendingFirstLODIdx, FBulkDataBatchRequest::FScatterGatherBuilder::Read(), RenderData, FBulkDataBatchRequest::ScatterGather(), FRenderAssetUpdate::TaskSynchronization, TEXT, FRenderAssetUpdate::Tick(), TRACE_IOSTORE_METADATA_SCOPE_TAG, and FRenderAssetUpdate::TT_None.
Referenced by DoInitiateIO().
Friends And Related Symbol Documentation
FCancelIORequestsTask
friend class FCancelIORequestsTask friend
Definition at line 199 of file SkeletalMeshUpdate.h.
Field Documentation
bFailedOnIOError
bool FSkeletalMeshStreamIn_IO::bFailedOnIOError = false protected
Definition at line 228 of file SkeletalMeshUpdate.h.
Referenced by ReportIOError(), SerializeLODData(), and SetIORequest().
bHighPrioIORequest
bool FSkeletalMeshStreamIn_IO::bHighPrioIORequest protected
Definition at line 225 of file SkeletalMeshUpdate.h.
Referenced by FSkeletalMeshStreamIn_IO(), and SetIORequest().
BulkData
FIoBuffer FSkeletalMeshStreamIn_IO::BulkData protected
Bulk data I/O buffer.
Definition at line 223 of file SkeletalMeshUpdate.h.
Referenced by ClearIORequest(), SerializeLODData(), and SetIORequest().
BulkDataRequest
FBulkDataBatchRequest FSkeletalMeshStreamIn_IO::BulkDataRequest protected
Handle to bulk data I/O request.
Definition at line 220 of file SkeletalMeshUpdate.h.
Referenced by Abort(), CancelIORequest(), ClearIORequest(), and SetIORequest().
The documentation for this class was generated from the following files:
Runtime/Engine/Internal/Streaming/SkeletalMeshUpdate.h
Runtime/Engine/Internal/Streaming/SkeletalMeshUpdate.cpp