Unreal Engine 5.6 C++ API: UE::Geometry::TDynamicMeshVectorOverlay< RealType, ElementSize, VectorType > Class Template Reference
UE::Geometry::TDynamicMeshVectorOverlay< RealType, ElementSize, VectorType > Class Template Reference
TDynamicMeshVectorOverlay is an convenient extension of TDynamicMeshOverlay that adds a specific N-element Vector type to the template, and adds accessor functions that convert between that N-element vector type and the N-element arrays used by TDynamicMeshOverlay.
#include "DynamicMeshOverlay.h"
Public Types
using BaseType = TDynamicMeshOverlay<RealType, ElementSize>
Public Types inherited from UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >
typedef FRefCountVector::IndexEnumerable element_iterator
Public Member Functions
TDynamicMeshVectorOverlay ()
TDynamicMeshVectorOverlay (FDynamicMesh3 *parentMesh)
int AppendElement (const RealType *Value)
Append a new Element to the overlay.
int AppendElement (const VectorType &Value)
Append a new Element to the overlay.
bool EnumerateVertexElements (int VertexID, TFunctionRef< bool(int TriangleID, int ElementID, const VectorType &Value)> ProcessFunc, bool bFindUniqueElements=true) const
Iterate through triangles connected to VertexID and call ProcessFunc for each per-triangle-vertex Element with its Value.
VectorType GetElement (int ElementID) const
Get Element at a specific ID.
void GetElement (int ElementID, VectorType &V) const
Get Element at a specific ID.
VectorType GetElementAtVertex (int TriangleID, int VertexID) const
Get the Element value associated with a vertex of a triangle.
void GetElementAtVertex (int TriangleID, int VertexID, VectorType &V) const
Get the Element value associated with a vertex of a triangle.
void GetTriElement (int TriangleID, int32 TriVertexIndex, VectorType &Value) const
Get the Element associated with a vertex of a triangle.
void GetTriElements (int TriangleID, VectorType &A, VectorType &B, VectorType &C) const
Get the three Elements associated with a triangle.
void SetElement (int ElementID, const VectorType &Value)
Set Element at a specific ID.
Public Member Functions inherited from UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >
TDynamicMeshOverlay ()
Create an empty overlay.
TDynamicMeshOverlay (FDynamicMesh3 *ParentMeshIn)
Create an overlay for the given parent mesh.
void Append (const TDynamicMeshOverlay &ToAppend, const FDynamicMesh3::FAppendInfo &AppendInfo)
void AppendDefaulted (const FDynamicMesh3::FAppendInfo &AppendInfo)
int AppendElement (const RealType *Value)
Allocate a new element with the given value.
int AppendElement (RealType ConstantValue)
Allocate a new element with the given constant value.
bool AreTrianglesConnected (int TriangleID0, int TriangleID1) const
void BeginUnsafeElementsInsert ()
Call this before a set of unsafe InsertVertex() calls.
bool CheckValidity (bool bAllowNonManifoldVertices=true, EValidityCheckFailMode FailMode=EValidityCheckFailMode::Check) const
Checks that the overlay mesh is well-formed, ie all internal data structures are consistent.
void ClearElements ()
Discard all elements.
template<typename EnumerableIntType>
void ClearElements (const EnumerableIntType &Triangles)
Discard elements for given triangles.
void CompactCopy (const FCompactMaps &CompactMaps, const TDynamicMeshOverlay< RealType, ElementSize > &Copy)
Copy the Copy overlay to a compact rep, also updating parent references based on the CompactMaps.
void CompactInPlace (const FCompactMaps &CompactMaps)
Compact overlay and update links to parent based on CompactMaps.
void Copy (const TDynamicMeshOverlay< RealType, ElementSize > &Copy)
Set this overlay to contain the same arrays as the copy overlay.
int CountVertexElements (int VertexID, bool bBruteForce=false) const
Count the number of unique elements for a given parent-mesh vertex.
void CreateFromPredicate (TFunctionRef< bool(int ParentVertexIdx, int TriIDA, int TriIDB)> TrisCanShareVertexPredicate, RealType InitElementValue)
Build overlay topology from a predicate function, e.g.
int ElementCount () const
element_iterator ElementIndicesItr () const
void EndUnsafeElementsInsert ()
Call after a set of unsafe InsertVertex() calls to rebuild free list.
void FreeUnusedElements (const TSet< int > *ElementsToCheck=nullptr)
Goes through elements and frees any whose reference counts indicate that they are not being used.
SIZE_T GetByteCount () const
template<typename AsType>
void GetElement (int ElementID, AsType &Data) const
Get the element at a given index.
void GetElement (int ElementID, RealType *Data) const
Get the element at a given index.
template<typename AsType>
void GetElementAtVertex (int TriangleID, int VertexID, AsType &Data) const
Get the Element value associated with a vertex of a triangle.
int GetElementIDAtVertex (int TriangleID, int VertexID) const
Find the element ID at a vertex of a triangle.
void GetElementTriangles (int ElementID, TArray< int > &OutTriangles) const
find the triangles connected to an element
FDynamicMesh3 * GetParentMesh ()
const FDynamicMesh3 * GetParentMesh () const
int GetParentVertex (int ElementID) const
Get the parent vertex id for the element at a given index.
FIndex3i GetTriangle (int TriangleID) const
Get the element index tuple for a triangle.
bool GetTriangleIfValid (int TriangleID, FIndex3i &TriangleOut) const
If the triangle is set to valid element indices, return the indices in TriangleOut and return true, otherwise return false.
template<typename AsType>
void GetTriBaryInterpolate (int32 TriangleID, const AsType *BaryCoords, AsType *DataOut) const
Compute interpolated parameter value inside triangle using barycentric coordinates.
void GetVertexElements (int VertexID, TArray< int > &OutElements) const
find the elements associated with a given parent-mesh vertex
bool HasInteriorSeamEdges () const
void InitializeNewTriangle (int TriangleID)
Set a triangle's element indices to InvalidID.
void InitializeTriangles (int MaxTriangleID)
Initialize the triangle list to the given size, and set all triangles to InvalidID.
EMeshResult InsertElement (int ElementID, const RealType *Value, bool bUnsafe=false)
Insert element at given index, assuming it is unused.
bool IsBowtieInOverlay (int32 VertexID) const
Determines whether the base-mesh vertex has "bowtie" topology in the Overlay.
bool IsCompact () const
bool IsElement (int vID) const
bool IsSameAs (const TDynamicMeshOverlay< RealType, ElementSize > &Other, bool bIgnoreDataLayout) const
Returns true if this overlay is the same as Other.
bool IsSeamEdge (int EdgeID, bool *bIsNonIntersectingOut=nullptr) const
Returns true if the parent-mesh edge is a "Seam" in this overlay.
bool IsSeamEndEdge (int EdgeID) const
Returns true if the parent-mesh edge is a "Seam End" in this overlay, meaning the adjacent element triangles share one element, not two.
bool IsSeamIntersectionVertex (int32 VertexID) const
Returns true if the parent-mesh vertex is at a seam 'intersection' – i.e., the end of a seam, or the intersection w/ another seam.
bool IsSeamVertex (int VertexID, bool bBoundaryIsSeam=true) const
Returns true if the parent-mesh vertex is connected to any seam edges.
bool IsSetTriangle (int TID) const
int MaxElementID () const
bool MergeElement (int SourceElementID, int TargetElementID)
Collapse SourceElementID into TargetElementID, resulting in connecting any containing triangles and reducing the total elements in the overlay.
void OnCollapseEdge (const DynamicMeshInfo::FEdgeCollapseInfo &CollapseInfo)
Update the overlay to reflect an edge collapse in the parent mesh.
void OnFlipEdge (const DynamicMeshInfo::FEdgeFlipInfo &FlipInfo)
Update the overlay to reflect an edge flip in the parent mesh.
void OnMergeEdges (const DynamicMeshInfo::FMergeEdgesInfo &MergeInfo)
Update the overlay to reflect an edge merge in the parent mesh.
void OnMergeVertices (const DynamicMeshInfo::FMergeVerticesInfo &MergeInfo)
Update the overlay to reflect a vertex merge in the parent mesh.
void OnPokeTriangle (const DynamicMeshInfo::FPokeTriangleInfo &PokeInfo)
Update the overlay to reflect a face poke in the parent mesh.
void OnRemoveTriangle (int TriangleID)
Remove a triangle from the overlay.
void OnReverseTriOrientation (int TriangleID)
Reverse the orientation of a triangle's elements.
void OnSplitEdge (const DynamicMeshInfo::FEdgeSplitInfo &SplitInfo)
Update the overlay to reflect an edge split in the parent mesh.
void OnSplitVertex (const DynamicMeshInfo::FVertexSplitInfo &SplitInfo, const TArrayView< const int > &TrianglesToUpdate)
Update the overlay to reflect a vertex split in the parent mesh.
void Serialize (FArchive &Ar, const FCompactMaps *CompactMaps, bool bUseCompression)
Serialize to and from an archive.
template<typename AsType>
void SetElement (int ElementID, const AsType &Data)
Set the element at a given index.
void SetElement (int ElementID, const RealType *Data)
Set the element at a given index.
void SetParentVertex (int ElementIndex, int ParentVertexIndex)
EMeshResult SetTriangle (int TriangleID, const FIndex3i &TriElements, bool bAllowElementFreeing=true)
Set the triangle to the given Element index tuple, and increment element reference counts.
void SplitBowties ()
Refine an existing overlay topology by splitting any bow ties.
void SplitBowtiesAtVertex (int32 Vid, TArray< int32 > *NewElementIDs=nullptr)
Split any bowties at given vertex.
int SplitElement (int ElementID, const TArrayView< const int > &TrianglesToUpdate)
Create a new copy of ElementID, and update connected triangles in the TrianglesToUpdate array to reference the copy of ElementID where they used to reference ElementID (Note: This just calls "SplitElementWithNewParent" with the existing element's parent id.)
int SplitElementWithNewParent (int ElementID, int SplitParentVertexID, const TArrayView< const int > &TrianglesToUpdate)
Create a new copy of ElementID, and update connected triangles in the TrianglesToUpdate array to reference the copy of ElementID where they used to reference ElementID.
void SplitVerticesWithPredicate (TFunctionRef< bool(int ElementIdx, int TriID)> ShouldSplitOutVertex, TFunctionRef< void(int ElementIdx, int TriID, RealType *FillVect)> GetNewElementValue)
Refine an existing overlay topology.
bool TriangleHasElement (int TriangleID, int ElementID) const
void UnsetTriangle (int TriangleID, bool bAllowElementFreeing=true)
Set the triangle to have InvalidID element IDs, decrementing element reference counts if needed.
Additional Inherited Members
Protected Member Functions inherited from UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >
void InternalSetTriangle (int TriangleID, const FIndex3i &TriElements, bool bUpdateRefCounts, bool bAllowElementFreeing=true)
updates the triangles array and optionally the element reference counts
void SetElementFromBary (int SetElement, int ElementA, int ElementB, int ElementC, const FVector3d &BaryCoords)
Set the value at an Element to be a barycentric interpolation of three other Elements.
void SetElementFromLerp (int SetElement, int ElementA, int ElementB, double Alpha)
Set the value at an Element to be a linear interpolation of two other Elements.
Protected Attributes inherited from UE::Geometry::TDynamicMeshOverlay< RealType, ElementSize >
TDynamicVector< RealType > Elements
List of element values.
FRefCountVector ElementsRefCounts
Reference counts of element indices.
TDynamicVector< int > ElementTriangles
List of triangle element-index triplets [Elem0 Elem1 Elem2].
FDynamicMesh3 * ParentMesh
The parent mesh this overlay belongs to.
TDynamicVector< int > ParentVertices
List of parent vertex indices, one per element.
Detailed Description
template<typename RealType, int ElementSize, typename VectorType>
class UE::Geometry::TDynamicMeshVectorOverlay< RealType, ElementSize, VectorType >
TDynamicMeshVectorOverlay is an convenient extension of TDynamicMeshOverlay that adds a specific N-element Vector type to the template, and adds accessor functions that convert between that N-element vector type and the N-element arrays used by TDynamicMeshOverlay.
Definition at line 706 of file DynamicMeshOverlay.h.
Member Typedef Documentation
BaseType
template<typename RealType, int ElementSize, typename VectorType> using UE::Geometry::TDynamicMeshVectorOverlay< RealType, ElementSize, VectorType >::BaseType = TDynamicMeshOverlay<RealType, ElementSize>
Definition at line 709 of file DynamicMeshOverlay.h.
Constructor & Destructor Documentation
TDynamicMeshVectorOverlay() [1/2]
template<typename RealType, int ElementSize, typename VectorType> UE::Geometry::TDynamicMeshVectorOverlay< RealType, ElementSize, VectorType >::TDynamicMeshVectorOverlay () inline
Definition at line 711 of file DynamicMeshOverlay.h.
TDynamicMeshVectorOverlay() [2/2]
template<typename RealType, int ElementSize, typename VectorType> UE::Geometry::TDynamicMeshVectorOverlay< RealType, ElementSize, VectorType >::TDynamicMeshVectorOverlay (FDynamicMesh3 * parentMesh) inline
Definition at line 716 of file DynamicMeshOverlay.h.
Member Function Documentation
AppendElement() [1/2]
template<typename RealType, int ElementSize, typename VectorType> int UE::Geometry::TDynamicMeshVectorOverlay< RealType, ElementSize, VectorType >::AppendElement (const RealType * Value) inline
Append a new Element to the overlay.
Definition at line 735 of file DynamicMeshOverlay.h.
AppendElement() [2/2]
template<typename RealType, int ElementSize, typename VectorType> int UE::Geometry::TDynamicMeshVectorOverlay< RealType, ElementSize, VectorType >::AppendElement (const VectorType & Value) inline
Append a new Element to the overlay.
Definition at line 724 of file DynamicMeshOverlay.h.
EnumerateVertexElements()
template<typename RealType, int ElementSize, typename VectorType> bool UE::Geometry::TDynamicMeshVectorOverlay< RealType, ElementSize, VectorType >::EnumerateVertexElements (int VertexID, TFunctionRef< bool(int TriangleID, int ElementID, const VectorType &Value)> ProcessFunc, bool bFindUniqueElements = true) const
Iterate through triangles connected to VertexID and call ProcessFunc for each per-triangle-vertex Element with its Value.
ProcessFunc must return true to continue the enumeration, or false to early-terminate it
Parameters
bFindUniqueElements if true, ProcessFunc is only called once for each ElementID, otherwise it is called once for each Triangle
Returns
true if at least one valid Element was found, ie if ProcessFunc was called at least one time
GetElement() [1/2]
template<typename RealType, int ElementSize, typename VectorType> VectorType UE::Geometry::TDynamicMeshVectorOverlay< RealType, ElementSize, VectorType >::GetElement (int ElementID) const inline
Get Element at a specific ID.
Definition at line 743 of file DynamicMeshOverlay.h.
Referenced by FMeshRenderBufferSetConversionUtil::GetOverlayColorAsFColor(), UE::Geometry::TDynamicMeshVectorOverlay< float, 2, FVector2f >::GetTriElement(), UE::Geometry::TDynamicMeshVectorOverlay< float, 2, FVector2f >::GetTriElements(), FMeshRenderBufferSetConversionUtil::InitializeBuffersFromOverlays(), and FMeshRenderBufferSetConversionUtil::UpdateVertexBuffersFromOverlays().
GetElement() [2/2]
template<typename RealType, int ElementSize, typename VectorType> void UE::Geometry::TDynamicMeshVectorOverlay< RealType, ElementSize, VectorType >::GetElement (int ElementID, VectorType & V) const inline
Get Element at a specific ID.
Definition at line 753 of file DynamicMeshOverlay.h.
GetElementAtVertex() [1/2]
template<typename RealType, int ElementSize, typename VectorType> VectorType UE::Geometry::TDynamicMeshVectorOverlay< RealType, ElementSize, VectorType >::GetElementAtVertex (int TriangleID, int VertexID) const inline
Get the Element value associated with a vertex of a triangle.
Definition at line 761 of file DynamicMeshOverlay.h.
GetElementAtVertex() [2/2]
template<typename RealType, int ElementSize, typename VectorType> void UE::Geometry::TDynamicMeshVectorOverlay< RealType, ElementSize, VectorType >::GetElementAtVertex (int TriangleID, int VertexID, VectorType & V) const inline
Get the Element value associated with a vertex of a triangle.
Definition at line 771 of file DynamicMeshOverlay.h.
GetTriElement()
template<typename RealType, int ElementSize, typename VectorType> void UE::Geometry::TDynamicMeshVectorOverlay< RealType, ElementSize, VectorType >::GetTriElement (int TriangleID, int32 TriVertexIndex, VectorType & Value) const inline
Get the Element associated with a vertex of a triangle.
Parameters
TriVertexIndex index of vertex in triangle, valid values are 0,1,2
Definition at line 780 of file DynamicMeshOverlay.h.
GetTriElements()
template<typename RealType, int ElementSize, typename VectorType> void UE::Geometry::TDynamicMeshVectorOverlay< RealType, ElementSize, VectorType >::GetTriElements (int TriangleID, VectorType & A, VectorType & B, VectorType & C) const inline
Get the three Elements associated with a triangle.
Definition at line 789 of file DynamicMeshOverlay.h.
SetElement()
template<typename RealType, int ElementSize, typename VectorType> void UE::Geometry::TDynamicMeshVectorOverlay< RealType, ElementSize, VectorType >::SetElement (int ElementID, const VectorType & Value) inline
Set Element at a specific ID.
Definition at line 801 of file DynamicMeshOverlay.h.
The documentation for this class was generated from the following file:
Runtime/GeometryCore/Public/DynamicMesh/DynamicMeshOverlay.h