Unreal Engine 5.6 C++ API: FInstanceIdIndexMap Class Reference
FInstanceIdIndexMap Class Reference
#include "InstanceDataSceneProxy.h"
Public Member Functions
FInstanceIdIndexMap ()=default
void CreateExplicitIdentityMapping ()
Convert an implicit identity mapping to an explicit one, by filling in the mapping arrays.
FORCEINLINE int32 GetMaxInstanceId () const
Returms the upper bound on the instance ID represented as an integer, may be larger than the number of instances but is never larger than the max that has ever been allocated.
FORCEINLINE int32 GetMaxInstanceIndex () const
Returns the maximum instance index (or rather the maximum valid number plus one), AKA the number of instances represented.
FORCEINLINE int32 IdToIndex (FPrimitiveInstanceId InstanceId) const
Translate from FPrimitiveInstanceId to Index.
FORCEINLINE FPrimitiveInstanceId IndexToId (int32 InstanceIndex) const
Translate from Index to FPrimitiveInstanceId.
FORCEINLINE bool IsIdentity () const
Returns true if the mapping is an identity mapping.
FORCEINLINE bool IsValidId (FPrimitiveInstanceId InstanceId) const
Returns true if InstanceId is in the mapped range AND .
void RebuildFromIndexToIdMap (TArray< FPrimitiveInstanceId > &&InIndexToIdMap, int32 MaxInstanceId)
void Reset (int32 InNumInstances)
Reset the mapping to an identity map of size InNumInstances.
void ResizeExplicit (int32 InNumInstances, int32 MaxInstanceId)
Make sure the mapping is explicit and add enough space to accommodate the InNumInstances & MaxInstanceId.
void Serialize (FArchive &Ar)
FORCEINLINE void SetInvalid (FPrimitiveInstanceId InstanceId)
Set the index mapping for the given InstanceId to INDEX_NONE.
FORCEINLINE void Update (FPrimitiveInstanceId InstanceId, int32 InstanceIndex)
Update the mapping from ID to index (and vice versa).
Protected Member Functions
void RebuildFromIndexToIdMap (int32 MaxInstanceId)
Protected Attributes
TArray< int32 > IdToIndexMap
TArray< FPrimitiveInstanceId > IndexToIdMap
int32 NumInstances = 0
Detailed Description
Definition at line 14 of file InstanceDataSceneProxy.h.
Constructor & Destructor Documentation
FInstanceIdIndexMap()
FInstanceIdIndexMap::FInstanceIdIndexMap () default
Member Function Documentation
CreateExplicitIdentityMapping()
void FInstanceIdIndexMap::CreateExplicitIdentityMapping ()
Convert an implicit identity mapping to an explicit one, by filling in the mapping arrays.
Not allowed to be called if the mapping is already explicit.
GetMaxInstanceId()
FORCEINLINE int32 FInstanceIdIndexMap::GetMaxInstanceId () const inline
Returms the upper bound on the instance ID represented as an integer, may be larger than the number of instances but is never larger than the max that has ever been allocated.
Definition at line 27 of file InstanceDataSceneProxy.h.
References FORCEINLINE, IdToIndexMap, IsIdentity(), and NumInstances.
Referenced by IsValidId().
GetMaxInstanceIndex()
FORCEINLINE int32 FInstanceIdIndexMap::GetMaxInstanceIndex () const inline
Returns the maximum instance index (or rather the maximum valid number plus one), AKA the number of instances represented.
Definition at line 32 of file InstanceDataSceneProxy.h.
References FORCEINLINE, IndexToIdMap, IsIdentity(), and NumInstances.
Referenced by IndexToId().
IdToIndex()
FORCEINLINE int32 FInstanceIdIndexMap::IdToIndex (FPrimitiveInstanceId InstanceId) const inline
Translate from FPrimitiveInstanceId to Index.
Definition at line 41 of file InstanceDataSceneProxy.h.
References FORCEINLINE, IdToIndexMap, and IsIdentity().
IndexToId()
FORCEINLINE FPrimitiveInstanceId FInstanceIdIndexMap::IndexToId (int32 InstanceIndex) const inline
Translate from Index to FPrimitiveInstanceId.
Definition at line 49 of file InstanceDataSceneProxy.h.
References check, FORCEINLINE, GetMaxInstanceIndex(), IndexToIdMap, and IsIdentity().
IsIdentity()
FORCEINLINE bool FInstanceIdIndexMap::IsIdentity () const inline
Returns true if the mapping is an identity mapping.
I.e., each instance ID corresponds to the same index.
Definition at line 22 of file InstanceDataSceneProxy.h.
References FORCEINLINE, and IndexToIdMap.
Referenced by GetMaxInstanceId(), GetMaxInstanceIndex(), IdToIndex(), IndexToId(), and IsValidId().
IsValidId()
FORCEINLINE bool FInstanceIdIndexMap::IsValidId (FPrimitiveInstanceId InstanceId) const inline
Returns true if InstanceId is in the mapped range AND .
Definition at line 37 of file InstanceDataSceneProxy.h.
References FORCEINLINE, GetMaxInstanceId(), IdToIndexMap, INDEX_NONE, and IsIdentity().
RebuildFromIndexToIdMap() [1/2]
void FInstanceIdIndexMap::RebuildFromIndexToIdMap (int32 MaxInstanceId) protected
RebuildFromIndexToIdMap() [2/2]
void FInstanceIdIndexMap::RebuildFromIndexToIdMap (TArray< FPrimitiveInstanceId > && InIndexToIdMap, int32 MaxInstanceId)
Reset()
void FInstanceIdIndexMap::Reset (int32 InNumInstances)
Reset the mapping to an identity map of size InNumInstances.
ResizeExplicit()
void FInstanceIdIndexMap::ResizeExplicit (int32 InNumInstances, int32 MaxInstanceId)
Make sure the mapping is explicit and add enough space to accommodate the InNumInstances & MaxInstanceId.
Serialize()
void FInstanceIdIndexMap::Serialize (FArchive & Ar)
References Ar.
SetInvalid()
FORCEINLINE void FInstanceIdIndexMap::SetInvalid (FPrimitiveInstanceId InstanceId) inline
Set the index mapping for the given InstanceId to INDEX_NONE.
Definition at line 58 of file InstanceDataSceneProxy.h.
References FORCEINLINE, IdToIndexMap, and INDEX_NONE.
Update()
FORCEINLINE void FInstanceIdIndexMap::Update (FPrimitiveInstanceId InstanceId, int32 InstanceIndex) inline
Update the mapping from ID to index (and vice versa).
Does not reset any previous mapping for the given ID.
Definition at line 67 of file InstanceDataSceneProxy.h.
References FORCEINLINE, IdToIndexMap, and IndexToIdMap.
Field Documentation
IdToIndexMap
TArray<int32> FInstanceIdIndexMap::IdToIndexMap protected
Definition at line 105 of file InstanceDataSceneProxy.h.
Referenced by GetMaxInstanceId(), IdToIndex(), IsValidId(), SetInvalid(), and Update().
IndexToIdMap
TArray<FPrimitiveInstanceId> FInstanceIdIndexMap::IndexToIdMap protected
Definition at line 104 of file InstanceDataSceneProxy.h.
Referenced by GetMaxInstanceIndex(), IndexToId(), IsIdentity(), and Update().
NumInstances
int32 FInstanceIdIndexMap::NumInstances = 0 protected
Definition at line 107 of file InstanceDataSceneProxy.h.
Referenced by GetMaxInstanceId(), and GetMaxInstanceIndex().
The documentation for this class was generated from the following file:
Runtime/Engine/Public/InstanceDataSceneProxy.h