Unreal Engine 5.6 C++ API: FRigVMExprAST Class Reference
FRigVMExprAST Class Reference abstract
#include "RigVMAST.h"
Public Types
enum EType {
Block , Entry , InvokeEntry , CallExtern ,
InlineFunction , NoOp , Var , Literal ,
ExternalVar , Assign , Copy , CachedValue ,
Exit , Invalid
}
typedef TArray< const FRigVMBlockExprAST *, TInlineAllocator< 5 > > FRigVMBlockArray
returns all of the block this expression is in
Public Member Functions
FRigVMExprAST (const FRigVMExprAST &)=delete
virtual ~FRigVMExprAST ()
TArray< FRigVMExprAST * >::RangedForConstIteratorType begin () const
template<class ObjectType>
const ObjectType * ChildAt (int32 InIndex) const
templated getter to retrieve a child with a given index type checking will occur within the To method and raise
const FRigVMExprAST * ChildAt (int32 InIndex) const
getter to retrieve a child with a given index
TArray< FRigVMExprAST * >::RangedForConstIteratorType end () const
const FRigVMBlockExprAST * GetBlock () const
returns the block of this expression
TOptional< uint32 > GetBlockCombinationHash () const
returns the unique block combination hash for this expression (or INDEX_NONE)
const FString & GetBlockCombinationName () const
returns the unique block combination name for this expression (or an empty string)
FRigVMBlockArray GetBlocks (bool bSortByDepth) const
virtual const FRigVMExprAST * GetFirstChildOfType (EType InExprType) const
returns the first parent in the tree of a given type
virtual const FRigVMExprAST * GetFirstParentOfType (EType InExprType) const
returns the first parent in the tree of a given type
int32 GetIndex () const
returns the index of this expression within the parser's storage
int32 GetMaximumDepth () const
returns the maximum depth of the expression in tree (number of recursive parents)
int32 GetMinChildIndexWithinParent (const FRigVMExprAST *InParentExpr) const
returns the lowest child index found for this expression within a parent (or INDEX_NONE)
FName GetName () const
returns the name of the expression (can be NAME_None)
const FRigVMExprAST * GetParent () const
returns the parent of this expression
const FRigVMParserAST * GetParser () const
returns the parser this expression is owned by
virtual const FRigVMASTProxy & GetProxy () const
returns the model proxy this expression relates to
const FRigVMBlockExprAST * GetRootBlock () const
returns the root / top level block of this expression
EType GetType () const
returns the exact type of the expression
FName GetTypeName () const
returns the name of the expression's type
virtual bool IsA (EType InType) const =0
provides type checking for inherited types
virtual bool IsConstant () const
returns true if this expressions is constant (non varying)
virtual bool IsNode () const
returns true if the expression is a node expression
bool IsParentedTo (const FRigVMExprAST *InParentExpr) const
returns true if a given expression is parented to another expression
bool IsParentOf (const FRigVMExprAST *InChildExpr) const
returns true if a given expression is a parent of another expression
bool IsValid () const
returns true if the expressoin is valid
virtual bool IsVar () const
returns true if the expression is a var expression
bool IsVarying () const
returns true if this expressions is varying (non constant)
int32 NumChildren () const
returns the number of children of this expression
int32 NumParents () const
returns the number of parents of this expression
const FRigVMExprAST * operator[] (int32 InIndex) const
accessor operator for a given child
template<class ObjectType>
const ObjectType * ParentAt (int32 InIndex) const
templated getter to retrieve a parent with a given index type checking will occur within the To method and raise
const FRigVMExprAST * ParentAt (int32 InIndex) const
getter to retrieve a parent with a given index
template<class ObjectType>
ObjectType * To ()
templated cast for casting between different expression types.
template<class ObjectType>
const ObjectType * To () const
const templated cast for casting between different expression types.
template<>
const FRigVMBlockExprAST * To () const
template<>
const FRigVMNodeExprAST * To () const
template<>
const FRigVMEntryExprAST * To () const
template<>
const FRigVMInvokeEntryExprAST * To () const
template<>
const FRigVMCallExternExprAST * To () const
template<>
const FRigVMInlineFunctionExprAST * To () const
template<>
const FRigVMNoOpExprAST * To () const
template<>
const FRigVMVarExprAST * To () const
template<>
const FRigVMLiteralExprAST * To () const
template<>
const FRigVMExternalVarExprAST * To () const
template<>
const FRigVMAssignExprAST * To () const
template<>
const FRigVMCopyExprAST * To () const
template<>
const FRigVMCachedValueExprAST * To () const
template<>
const FRigVMExitExprAST * To () const
Protected Member Functions
FRigVMExprAST (EType InType=EType::Invalid, const FRigVMASTProxy &InProxy=FRigVMASTProxy())
void AddParent (FRigVMExprAST *InParent)
virtual FString DumpText (const FString &InPrefix=FString()) const
void GetBlocksImpl (FRigVMBlockArray &InOutBlocks) const
void InvalidateCaches ()
void InvalidateCachesImpl (TArray< bool > &OutProcessed)
void RemoveChild (FRigVMExprAST *InChild)
void RemoveParent (FRigVMExprAST *InParent)
void ReplaceBy (FRigVMExprAST *InReplacement)
void ReplaceChild (FRigVMExprAST *InCurrentChild, FRigVMExprAST *InNewChild)
void ReplaceParent (FRigVMExprAST *InCurrentParent, FRigVMExprAST *InNewParent)
Protected Attributes
TOptional< TOptional< uint32 > > BlockCombinationHash
TOptional< int32 > BlocksCacheVersion
FRigVMBlockArray CachedBlocks
TMap< int32, const FRigVMExprAST * > CachedFirstChildOfType
TMap< int32, const FRigVMExprAST * > CachedFirstParentOfType
TArray< FRigVMExprAST * > Children
TOptional< int32 > FirstChildOfTypeCacheVersion
TOptional< int32 > FirstParentOfTypeCacheVersion
int32 Index
TOptional< int32 > MaximumDepth
FName Name
TArray< FRigVMExprAST * > Parents
const FRigVMParserAST * ParserPtr
TMap< FName, int32 > PinNameToChildIndex
EType Type
Friends
class FRigVMParserAST
class URigVMCompiler
Detailed Description
Definition at line 76 of file RigVMAST.h.
Member Typedef Documentation
FRigVMBlockArray
typedef TArray<const FRigVMBlockExprAST*, TInlineAllocator<5> > FRigVMExprAST::FRigVMBlockArray
returns all of the block this expression is in
Parameters
bSortByDepth If true the blocks will be returned sorted (head to tail)
Returns
all of the block this expression is in
Definition at line 182 of file RigVMAST.h.
Member Enumeration Documentation
EType
enum FRigVMExprAST::EType
Enumerator
Block
Entry
InvokeEntry
CallExtern
InlineFunction
NoOp
Var
Literal
ExternalVar
Assign
Copy
CachedValue
Exit
Invalid
Definition at line 81 of file RigVMAST.h.
Constructor & Destructor Documentation
~FRigVMExprAST()
virtual FRigVMExprAST::~FRigVMExprAST () inline virtual
Definition at line 100 of file RigVMAST.h.
FRigVMExprAST() [1/2]
FRigVMExprAST::FRigVMExprAST (const FRigVMExprAST &) delete
References FRigVMExprAST().
Referenced by FRigVMAssignExprAST::FRigVMAssignExprAST(), FRigVMBlockExprAST::FRigVMBlockExprAST(), FRigVMCachedValueExprAST::FRigVMCachedValueExprAST(), FRigVMExitExprAST::FRigVMExitExprAST(), FRigVMExprAST(), FRigVMVarExprAST::FRigVMVarExprAST(), AddParent(), ChildAt(), FRigVMBlockExprAST::Contains(), GetFirstChildOfType(), GetFirstParentOfType(), GetMinChildIndexWithinParent(), GetParent(), IsParentedTo(), IsParentOf(), operator[](), ParentAt(), RemoveChild(), RemoveParent(), ReplaceBy(), ReplaceChild(), and ReplaceParent().
FRigVMExprAST() [2/2]
FRigVMExprAST::FRigVMExprAST (EType InType = EType::Invalid, const FRigVMASTProxy & InProxy = FRigVMASTProxy()) protected
References Invalid.
Member Function Documentation
AddParent()
void FRigVMExprAST::AddParent (FRigVMExprAST * InParent) protected
References FRigVMExprAST().
begin()
TArray< FRigVMExprAST * >::RangedForConstIteratorType FRigVMExprAST::begin () const inline
Definition at line 219 of file RigVMAST.h.
References Children.
ChildAt() [1/2]
template<class ObjectType> const ObjectType * FRigVMExprAST::ChildAt (int32 InIndex) const inline
templated getter to retrieve a child with a given index type checking will occur within the To method and raise
Parameters
InIndex the index of the child to retrieve
Returns
the child at a given index cast to the provided class
Definition at line 228 of file RigVMAST.h.
References Children.
Referenced by FRigVMCachedValueExprAST::GetCallExternExpr(), and FRigVMCachedValueExprAST::GetVarExpr().
ChildAt() [2/2]
const FRigVMExprAST * FRigVMExprAST::ChildAt (int32 InIndex) const inline
getter to retrieve a child with a given index
Parameters
InIndex the index of the child to retrieve
Returns
the child at a given index
Definition at line 236 of file RigVMAST.h.
References FRigVMExprAST(), and Children.
DumpText()
virtual FString FRigVMExprAST::DumpText (const FString & InPrefix = FString()) const protected virtual
end()
TArray< FRigVMExprAST * >::RangedForConstIteratorType FRigVMExprAST::end () const inline
Definition at line 221 of file RigVMAST.h.
References Children.
GetBlock()
const FRigVMBlockExprAST * FRigVMExprAST::GetBlock () const
returns the block of this expression
Returns
the block of this expression
GetBlockCombinationHash()
TOptional< uint32 > FRigVMExprAST::GetBlockCombinationHash () const
returns the unique block combination hash for this expression (or INDEX_NONE)
Returns
the unique block combination name for this expression (or INDEX_NONE)
GetBlockCombinationName()
const FString & FRigVMExprAST::GetBlockCombinationName () const
returns the unique block combination name for this expression (or an empty string)
Returns
the unique block combination name for this expression (or an empty string)
GetBlocks()
FRigVMBlockArray FRigVMExprAST::GetBlocks (bool bSortByDepth) const
GetBlocksImpl()
void FRigVMExprAST::GetBlocksImpl (FRigVMBlockArray & InOutBlocks) const protected
GetFirstChildOfType()
virtual const FRigVMExprAST * FRigVMExprAST::GetFirstChildOfType (EType InExprType) const virtual
returns the first parent in the tree of a given type
Parameters
InExprType The type of expression to look for in the parent tree
Returns
the first parent in the tree of a given type
References FRigVMExprAST().
GetFirstParentOfType()
virtual const FRigVMExprAST * FRigVMExprAST::GetFirstParentOfType (EType InExprType) const virtual
returns the first parent in the tree of a given type
Parameters
InExprType The type of expression to look for in the parent tree
Returns
the first parent in the tree of a given type
References FRigVMExprAST().
GetIndex()
int32 FRigVMExprAST::GetIndex () const inline
returns the index of this expression within the parser's storage
Returns
the index of this expression within the parser's storage
Definition at line 140 of file RigVMAST.h.
References Index.
Referenced by IsValid().
GetMaximumDepth()
int32 FRigVMExprAST::GetMaximumDepth () const
returns the maximum depth of the expression in tree (number of recursive parents)
Returns
the maximum depth of the expression in tree (number of recursive parents)
GetMinChildIndexWithinParent()
int32 FRigVMExprAST::GetMinChildIndexWithinParent (const FRigVMExprAST * InParentExpr) const
returns the lowest child index found for this expression within a parent (or INDEX_NONE)
Returns
the lowest child index found for this expression within a parent (or INDEX_NONE)
References FRigVMExprAST().
GetName()
FName FRigVMExprAST::GetName () const inline
returns the name of the expression (can be NAME_None)
Returns
the name of the expression
Definition at line 111 of file RigVMAST.h.
References Name.
GetParent()
const FRigVMExprAST * FRigVMExprAST::GetParent () const
returns the parent of this expression
Returns
the parent of this expression
References FRigVMExprAST().
GetParser()
const FRigVMParserAST * FRigVMExprAST::GetParser () const inline
returns the parser this expression is owned by
Returns
the parser this expression is owned by
Definition at line 107 of file RigVMAST.h.
References FRigVMParserAST, and ParserPtr.
GetProxy()
virtual const FRigVMASTProxy & FRigVMExprAST::GetProxy () const inline virtual
returns the model proxy this expression relates to
Reimplemented in FRigVMAssignExprAST, FRigVMNodeExprAST, and FRigVMVarExprAST.
Definition at line 146 of file RigVMAST.h.
GetRootBlock()
const FRigVMBlockExprAST * FRigVMExprAST::GetRootBlock () const
returns the root / top level block of this expression
Returns
the root / top level block of this expression
GetType()
EType FRigVMExprAST::GetType () const inline
returns the exact type of the expression
Returns
the exact type of the expression
Definition at line 115 of file RigVMAST.h.
References Type.
GetTypeName()
FName FRigVMExprAST::GetTypeName () const
returns the name of the expression's type
Returns
the name of the expression's type
InvalidateCaches()
void FRigVMExprAST::InvalidateCaches () protected
InvalidateCachesImpl()
void FRigVMExprAST::InvalidateCachesImpl (TArray< bool > & OutProcessed) protected
IsA()
virtual bool FRigVMExprAST::IsA (EType InType) const pure virtual
provides type checking for inherited types
Parameters
InType the type to check against
Returns
true if this expression is of a given type
Implemented in FRigVMAssignExprAST, FRigVMBlockExprAST, FRigVMCachedValueExprAST, FRigVMCallExternExprAST, FRigVMCopyExprAST, FRigVMEntryExprAST, FRigVMExitExprAST, FRigVMExternalVarExprAST, FRigVMInlineFunctionExprAST, FRigVMInvokeEntryExprAST, FRigVMLiteralExprAST, FRigVMNodeExprAST, FRigVMNoOpExprAST, and FRigVMVarExprAST.
Referenced by To().
IsConstant()
virtual bool FRigVMExprAST::IsConstant () const virtual
returns true if this expressions is constant (non varying)
Returns
true if this expressions is constant (non varying)
Reimplemented in FRigVMExitExprAST, FRigVMInlineFunctionExprAST, FRigVMLiteralExprAST, FRigVMNodeExprAST, and FRigVMVarExprAST.
Referenced by IsVarying().
IsNode()
virtual bool FRigVMExprAST::IsNode () const inline virtual
returns true if the expression is a node expression
Reimplemented in FRigVMNodeExprAST.
Definition at line 127 of file RigVMAST.h.
IsParentedTo()
bool FRigVMExprAST::IsParentedTo (const FRigVMExprAST * InParentExpr) const
returns true if a given expression is parented to another expression
Parameters
InParentExpr The potential parent to check
Returns
True if this expression is parented to the InParentExpr
References FRigVMExprAST().
IsParentOf()
bool FRigVMExprAST::IsParentOf (const FRigVMExprAST * InChildExpr) const
returns true if a given expression is a parent of another expression
Parameters
InChildExpr The potential child to check
Returns
True if this expression is a parent of the InChildExpr
References FRigVMExprAST().
IsValid()
bool FRigVMExprAST::IsValid () const inline
returns true if the expressoin is valid
Definition at line 143 of file RigVMAST.h.
References GetIndex(), and INDEX_NONE.
IsVar()
virtual bool FRigVMExprAST::IsVar () const inline virtual
returns true if the expression is a var expression
Reimplemented in FRigVMVarExprAST.
Definition at line 133 of file RigVMAST.h.
IsVarying()
bool FRigVMExprAST::IsVarying () const inline
returns true if this expressions is varying (non constant)
Returns
true if this expressions is varying (non constant)
Definition at line 207 of file RigVMAST.h.
References IsConstant().
NumChildren()
int32 FRigVMExprAST::NumChildren () const inline
returns the number of children of this expression
Returns
the number of children of this expression
Definition at line 199 of file RigVMAST.h.
References Children.
NumParents()
int32 FRigVMExprAST::NumParents () const inline
returns the number of parents of this expression
Returns
the number of parents of this expression
Definition at line 248 of file RigVMAST.h.
References Parents.
operator[]()
const FRigVMExprAST * FRigVMExprAST::operator[] (int32 InIndex) const inline
accessor operator for a given child
Parameters
InIndex the index of the child to retrieve (bound = NumChildren() - 1)
Returns
the child at the given index
Definition at line 216 of file RigVMAST.h.
References FRigVMExprAST(), and Children.
ParentAt() [1/2]
template<class ObjectType> const ObjectType * FRigVMExprAST::ParentAt (int32 InIndex) const inline
templated getter to retrieve a parent with a given index type checking will occur within the To method and raise
Parameters
InIndex the index of the parent to retrieve
Returns
the parent at a given index cast to the provided class
Definition at line 255 of file RigVMAST.h.
References Parents.
ParentAt() [2/2]
const FRigVMExprAST * FRigVMExprAST::ParentAt (int32 InIndex) const inline
getter to retrieve a parent with a given index
Parameters
InIndex the index of the parent to retrieve
Returns
the parent at a given index
Definition at line 263 of file RigVMAST.h.
References FRigVMExprAST(), and Parents.
RemoveChild()
void FRigVMExprAST::RemoveChild (FRigVMExprAST * InChild) protected
References FRigVMExprAST().
RemoveParent()
void FRigVMExprAST::RemoveParent (FRigVMExprAST * InParent) protected
References FRigVMExprAST().
ReplaceBy()
void FRigVMExprAST::ReplaceBy (FRigVMExprAST * InReplacement) protected
References FRigVMExprAST().
ReplaceChild()
void FRigVMExprAST::ReplaceChild (FRigVMExprAST * InCurrentChild, FRigVMExprAST * InNewChild) protected
References FRigVMExprAST().
ReplaceParent()
void FRigVMExprAST::ReplaceParent (FRigVMExprAST * InCurrentParent, FRigVMExprAST * InNewParent) protected
References FRigVMExprAST().
To() [1/16]
template<class ObjectType> ObjectType * FRigVMExprAST::To () inline
templated cast for casting between different expression types.
specializations below are used for type checking
Returns
this object cast to the provided class
Definition at line 284 of file RigVMAST.h.
To() [2/16]
template<class ObjectType> const ObjectType * FRigVMExprAST::To () const inline
const templated cast for casting between different expression types.
specializations below are used for type checking
Returns
this object cast to the provided class
Definition at line 273 of file RigVMAST.h.
References checkNoEntry.
To() [3/16]
template<> const FRigVMBlockExprAST * FRigVMExprAST::To () const inline
Definition at line 361 of file RigVMAST.h.
References Block, ensure, and IsA().
To() [4/16]
template<> const FRigVMNodeExprAST * FRigVMExprAST::To () const inline
Definition at line 372 of file RigVMAST.h.
References CallExtern, ensure, Entry, InlineFunction, InvokeEntry, IsA(), and NoOp.
To() [5/16]
template<> const FRigVMEntryExprAST * FRigVMExprAST::To () const inline
Definition at line 389 of file RigVMAST.h.
References ensure, Entry, and IsA().
To() [6/16]
template<> const FRigVMInvokeEntryExprAST * FRigVMExprAST::To () const inline
Definition at line 400 of file RigVMAST.h.
References ensure, InvokeEntry, and IsA().
To() [7/16]
template<> const FRigVMCallExternExprAST * FRigVMExprAST::To () const inline
Definition at line 411 of file RigVMAST.h.
References CallExtern, ensure, and IsA().
To() [8/16]
template<> const FRigVMInlineFunctionExprAST * FRigVMExprAST::To () const inline
Definition at line 422 of file RigVMAST.h.
References ensure, InlineFunction, and IsA().
To() [9/16]
template<> const FRigVMNoOpExprAST * FRigVMExprAST::To () const inline
Definition at line 433 of file RigVMAST.h.
References ensure, IsA(), and NoOp.
To() [10/16]
template<> const FRigVMVarExprAST * FRigVMExprAST::To () const inline
Definition at line 444 of file RigVMAST.h.
References ensure, IsA(), and Var.
To() [11/16]
template<> const FRigVMLiteralExprAST * FRigVMExprAST::To () const inline
Definition at line 455 of file RigVMAST.h.
References ensure, IsA(), and Literal.
To() [12/16]
template<> const FRigVMExternalVarExprAST * FRigVMExprAST::To () const inline
Definition at line 466 of file RigVMAST.h.
References ensure, ExternalVar, and IsA().
To() [13/16]
template<> const FRigVMAssignExprAST * FRigVMExprAST::To () const inline
Definition at line 477 of file RigVMAST.h.
References Assign, ensure, and IsA().
To() [14/16]
template<> const FRigVMCopyExprAST * FRigVMExprAST::To () const inline
Definition at line 488 of file RigVMAST.h.
References Copy, ensure, and IsA().
To() [15/16]
template<> const FRigVMCachedValueExprAST * FRigVMExprAST::To () const inline
Definition at line 499 of file RigVMAST.h.
References CachedValue, ensure, and IsA().
To() [16/16]
template<> const FRigVMExitExprAST * FRigVMExprAST::To () const inline
Definition at line 510 of file RigVMAST.h.
References ensure, Exit, and IsA().
Friends And Related Symbol Documentation
FRigVMParserAST
friend class FRigVMParserAST friend
Definition at line 352 of file RigVMAST.h.
References FRigVMParserAST.
Referenced by FRigVMParserAST, and GetParser().
URigVMCompiler
friend class URigVMCompiler friend
Definition at line 353 of file RigVMAST.h.
References URigVMCompiler.
Referenced by URigVMCompiler.
Field Documentation
BlockCombinationHash
TOptional<TOptional<uint32> > FRigVMExprAST::BlockCombinationHash mutable protected
Definition at line 343 of file RigVMAST.h.
BlocksCacheVersion
TOptional<int32> FRigVMExprAST::BlocksCacheVersion mutable protected
Definition at line 345 of file RigVMAST.h.
CachedBlocks
FRigVMBlockArray FRigVMExprAST::CachedBlocks mutable protected
Definition at line 346 of file RigVMAST.h.
CachedFirstChildOfType
TMap<int32, const FRigVMExprAST*> FRigVMExprAST::CachedFirstChildOfType mutable protected
Definition at line 348 of file RigVMAST.h.
CachedFirstParentOfType
TMap<int32, const FRigVMExprAST*> FRigVMExprAST::CachedFirstParentOfType mutable protected
Definition at line 350 of file RigVMAST.h.
Children
TArray<FRigVMExprAST*> FRigVMExprAST::Children protected
Definition at line 341 of file RigVMAST.h.
Referenced by begin(), ChildAt(), end(), NumChildren(), and operator[]().
FirstChildOfTypeCacheVersion
TOptional<int32> FRigVMExprAST::FirstChildOfTypeCacheVersion mutable protected
Definition at line 347 of file RigVMAST.h.
FirstParentOfTypeCacheVersion
TOptional<int32> FRigVMExprAST::FirstParentOfTypeCacheVersion mutable protected
Definition at line 349 of file RigVMAST.h.
Index
int32 FRigVMExprAST::Index protected
Definition at line 338 of file RigVMAST.h.
Referenced by GetIndex().
MaximumDepth
TOptional<int32> FRigVMExprAST::MaximumDepth mutable protected
Definition at line 344 of file RigVMAST.h.
Name
FName FRigVMExprAST::Name protected
Definition at line 336 of file RigVMAST.h.
Referenced by GetName().
Parents
TArray<FRigVMExprAST*> FRigVMExprAST::Parents protected
Definition at line 340 of file RigVMAST.h.
Referenced by NumParents(), and ParentAt().
ParserPtr
const FRigVMParserAST* FRigVMExprAST::ParserPtr protected
Definition at line 339 of file RigVMAST.h.
Referenced by GetParser().
PinNameToChildIndex
TMap<FName, int32> FRigVMExprAST::PinNameToChildIndex protected
Definition at line 342 of file RigVMAST.h.
Type
EType FRigVMExprAST::Type protected
Definition at line 337 of file RigVMAST.h.
Referenced by GetType().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/RigVM/Source/RigVMDeveloper/Public/RigVMCompiler/RigVMAST.h