Unreal Engine 5.6 C++ API: UE::Sequencer::TSharedListItem< T > Class Template Reference
UE::Sequencer::TSharedListItem< T > Class Template Reference
#include "SharedList.h"
Public Member Functions
virtual ~TSharedListItem ()
void Link (TSharedPtr< T > &Head)
TSharedPtr< T > Next () const
void Unlink ()
Public Member Functions inherited from TSharedFromThis< T >
TSharedRef< T, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< T, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Private Attributes
TSharedPtr< T > NextLink
TSharedPtr< T > * PrevLink = nullptr
Additional Inherited Members
Protected Member Functions inherited from TSharedFromThis< T >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions inherited from TSharedFromThis< T >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
template<typename T>
class UE::Sequencer::TSharedListItem< T >
Definition at line 13 of file SharedList.h.
Constructor & Destructor Documentation
~TSharedListItem()
template<typename T> virtual UE::Sequencer::TSharedListItem< T >::~TSharedListItem () inline virtual
Definition at line 16 of file SharedList.h.
References Unlink().
Member Function Documentation
Link()
template<typename T> void UE::Sequencer::TSharedListItem< T >::Link (TSharedPtr< T > & Head) inline
Definition at line 26 of file SharedList.h.
References TSharedFromThis< T >::AsShared(), NextLink, and PrevLink.
Next()
template<typename T> TSharedPtr< T > UE::Sequencer::TSharedListItem< T >::Next () const inline
Definition at line 21 of file SharedList.h.
References NextLink.
Unlink()
template<typename T> void UE::Sequencer::TSharedListItem< T >::Unlink () inline
Definition at line 38 of file SharedList.h.
References NextLink, and PrevLink.
Referenced by ~TSharedListItem().
Field Documentation
NextLink
template<typename T> TSharedPtr<T> UE::Sequencer::TSharedListItem< T >::NextLink private
Definition at line 55 of file SharedList.h.
Referenced by Link(), Next(), and Unlink().
PrevLink
template<typename T> TSharedPtr<T>* UE::Sequencer::TSharedListItem< T >::PrevLink = nullptr private
Definition at line 56 of file SharedList.h.
Referenced by Link(), and Unlink().
The documentation for this class was generated from the following file:
Editor/SequencerCore/Public/MVVM/SharedList.h