Unreal Engine 5.6 C++ API: IContentBundleEditorSubsystemInterface Class Reference
IContentBundleEditorSubsystemInterface Class Reference abstract
#include "ContentBundleEditorSubsystemInterface.h"
Public Member Functions
virtual ~IContentBundleEditorSubsystemInterface ()
virtual bool ActivateContentBundleEditing (TSharedPtr< FContentBundleEditor > &ContentBundleEditor) const =0
virtual bool DeactivateContentBundleEditing (TSharedPtr< FContentBundleEditor > &ContentBundleEditor) const =0
virtual bool DeactivateCurrentContentBundleEditing () const =0
DECLARE_EVENT_OneParam (UContentBundleEditorSubsystem, FOnContentBundleAdded, const FContentBundleEditor *)
DECLARE_EVENT_OneParam (UContentBundleEditorSubsystem, FOnContentBundleChanged, const FContentBundleEditor *)
DECLARE_EVENT_OneParam (UContentBundleEditorSubsystem, FOnContentBundleRemoved, const FContentBundleEditor *)
DECLARE_EVENT_OneParam (UContentBundleEditorSubsystem, FOnContentBundleRemovedContent, const FContentBundleEditor *)
virtual TSharedPtr< FContentBundleEditor > GetEditorContentBundle (const FGuid &ContentBundleGuid) const =0
virtual bool IsEditingContentBundle () const =0
virtual void NotifyContentBundleAdded (const FContentBundleEditor *ContentBundle)=0
virtual void NotifyContentBundleChanged (const FContentBundleEditor *ContentBundle)=0
virtual void NotifyContentBundleInjectedContent (const FContentBundleEditor *ContentBundle)=0
virtual void NotifyContentBundleRemoved (const FContentBundleEditor *ContentBundle)=0
virtual void NotifyContentBundleRemovedContent (const FContentBundleEditor *ContentBundle)=0
FOnContentBundleAdded & OnContentBundleAdded ()
FOnContentBundleChanged & OnContentBundleChanged ()
FOnContentBundleRemoved & OnContentBundleRemoved ()
FOnContentBundleRemovedContent & OnContentBundleRemovedContent ()
virtual void PopContentBundleEditing ()=0
virtual void PushContentBundleEditing ()
virtual void PushContentBundleEditing (bool bDuplicateContext)=0
Static Public Member Functions
static IContentBundleEditorSubsystemInterface * Get ()
Static Protected Member Functions
static void SetInstance (IContentBundleEditorSubsystemInterface *InInstance)
Static Protected Attributes
static IContentBundleEditorSubsystemInterface * Instance
Private Attributes
FOnContentBundleAdded ContentBundleAdded
FOnContentBundleChanged ContentBundleChanged
FOnContentBundleRemoved ContentBundleRemoved
FOnContentBundleRemovedContent ContentBundleRemovedContent
Detailed Description
Definition at line 9 of file ContentBundleEditorSubsystemInterface.h.
Constructor & Destructor Documentation
~IContentBundleEditorSubsystemInterface()
virtual IContentBundleEditorSubsystemInterface::~IContentBundleEditorSubsystemInterface () inline virtual
Definition at line 14 of file ContentBundleEditorSubsystemInterface.h.
Member Function Documentation
ActivateContentBundleEditing()
virtual bool IContentBundleEditorSubsystemInterface::ActivateContentBundleEditing (TSharedPtr< FContentBundleEditor > & ContentBundleEditor) const pure virtual
Referenced by FContentBundleActivationScope::FContentBundleActivationScope().
DeactivateContentBundleEditing()
virtual bool IContentBundleEditorSubsystemInterface::DeactivateContentBundleEditing (TSharedPtr< FContentBundleEditor > & ContentBundleEditor) const pure virtual
Referenced by FContentBundleActivationScope::~FContentBundleActivationScope().
DeactivateCurrentContentBundleEditing()
virtual bool IContentBundleEditorSubsystemInterface::DeactivateCurrentContentBundleEditing () const pure virtual
DECLARE_EVENT_OneParam() [1/4]
IContentBundleEditorSubsystemInterface::DECLARE_EVENT_OneParam (UContentBundleEditorSubsystem , FOnContentBundleAdded , const FContentBundleEditor *)
DECLARE_EVENT_OneParam() [2/4]
IContentBundleEditorSubsystemInterface::DECLARE_EVENT_OneParam (UContentBundleEditorSubsystem , FOnContentBundleChanged , const FContentBundleEditor *)
DECLARE_EVENT_OneParam() [3/4]
IContentBundleEditorSubsystemInterface::DECLARE_EVENT_OneParam (UContentBundleEditorSubsystem , FOnContentBundleRemoved , const FContentBundleEditor *)
DECLARE_EVENT_OneParam() [4/4]
IContentBundleEditorSubsystemInterface::DECLARE_EVENT_OneParam (UContentBundleEditorSubsystem , FOnContentBundleRemovedContent , const FContentBundleEditor *)
Get()
IContentBundleEditorSubsystemInterface * IContentBundleEditorSubsystemInterface::Get () inline static
Definition at line 12 of file ContentBundleEditorSubsystemInterface.h.
References Instance.
Referenced by FContentBundleActivationScope::FContentBundleActivationScope(), and FContentBundleActivationScope::~FContentBundleActivationScope().
GetEditorContentBundle()
virtual TSharedPtr< FContentBundleEditor > IContentBundleEditorSubsystemInterface::GetEditorContentBundle (const FGuid & ContentBundleGuid) const pure virtual
Referenced by FContentBundleActivationScope::FContentBundleActivationScope(), and FContentBundleActivationScope::~FContentBundleActivationScope().
IsEditingContentBundle()
virtual bool IContentBundleEditorSubsystemInterface::IsEditingContentBundle () const pure virtual
NotifyContentBundleAdded()
virtual void IContentBundleEditorSubsystemInterface::NotifyContentBundleAdded (const FContentBundleEditor * ContentBundle) pure virtual
NotifyContentBundleChanged()
virtual void IContentBundleEditorSubsystemInterface::NotifyContentBundleChanged (const FContentBundleEditor * ContentBundle) pure virtual
NotifyContentBundleInjectedContent()
virtual void IContentBundleEditorSubsystemInterface::NotifyContentBundleInjectedContent (const FContentBundleEditor * ContentBundle) pure virtual
NotifyContentBundleRemoved()
virtual void IContentBundleEditorSubsystemInterface::NotifyContentBundleRemoved (const FContentBundleEditor * ContentBundle) pure virtual
NotifyContentBundleRemovedContent()
virtual void IContentBundleEditorSubsystemInterface::NotifyContentBundleRemovedContent (const FContentBundleEditor * ContentBundle) pure virtual
OnContentBundleAdded()
FOnContentBundleAdded & IContentBundleEditorSubsystemInterface::OnContentBundleAdded () inline
Definition at line 33 of file ContentBundleEditorSubsystemInterface.h.
References ContentBundleAdded.
OnContentBundleChanged()
FOnContentBundleChanged & IContentBundleEditorSubsystemInterface::OnContentBundleChanged () inline
Definition at line 42 of file ContentBundleEditorSubsystemInterface.h.
References ContentBundleChanged.
OnContentBundleRemoved()
FOnContentBundleRemoved & IContentBundleEditorSubsystemInterface::OnContentBundleRemoved () inline
Definition at line 36 of file ContentBundleEditorSubsystemInterface.h.
References ContentBundleRemoved.
OnContentBundleRemovedContent()
FOnContentBundleRemovedContent & IContentBundleEditorSubsystemInterface::OnContentBundleRemovedContent () inline
Definition at line 39 of file ContentBundleEditorSubsystemInterface.h.
References ContentBundleRemovedContent.
PopContentBundleEditing()
virtual void IContentBundleEditorSubsystemInterface::PopContentBundleEditing () pure virtual
Referenced by FContentBundleActivationScope::~FContentBundleActivationScope().
PushContentBundleEditing() [1/2]
virtual void IContentBundleEditorSubsystemInterface::PushContentBundleEditing () inline virtual
Definition at line 28 of file ContentBundleEditorSubsystemInterface.h.
References PushContentBundleEditing().
Referenced by FContentBundleActivationScope::FContentBundleActivationScope(), and PushContentBundleEditing().
PushContentBundleEditing() [2/2]
virtual void IContentBundleEditorSubsystemInterface::PushContentBundleEditing (bool bDuplicateContext) pure virtual
SetInstance()
void IContentBundleEditorSubsystemInterface::SetInstance (IContentBundleEditorSubsystemInterface * InInstance) static protected
Field Documentation
ContentBundleAdded
FOnContentBundleAdded IContentBundleEditorSubsystemInterface::ContentBundleAdded private
Definition at line 49 of file ContentBundleEditorSubsystemInterface.h.
Referenced by OnContentBundleAdded().
ContentBundleChanged
FOnContentBundleChanged IContentBundleEditorSubsystemInterface::ContentBundleChanged private
Definition at line 52 of file ContentBundleEditorSubsystemInterface.h.
Referenced by OnContentBundleChanged().
ContentBundleRemoved
FOnContentBundleRemoved IContentBundleEditorSubsystemInterface::ContentBundleRemoved private
Definition at line 50 of file ContentBundleEditorSubsystemInterface.h.
Referenced by OnContentBundleRemoved().
ContentBundleRemovedContent
FOnContentBundleRemovedContent IContentBundleEditorSubsystemInterface::ContentBundleRemovedContent private
Definition at line 51 of file ContentBundleEditorSubsystemInterface.h.
Referenced by OnContentBundleRemovedContent().
Instance
IContentBundleEditorSubsystemInterface* IContentBundleEditorSubsystemInterface::Instance static protected
Definition at line 46 of file ContentBundleEditorSubsystemInterface.h.
Referenced by Get().
The documentation for this class was generated from the following file:
Runtime/Engine/Public/WorldPartition/ContentBundle/ContentBundleEditorSubsystemInterface.h