Unreal Engine 5.6 C++ API: FTextBuilder Class Reference
FTextBuilder Class Reference
#include "Text.h"
Public Member Functions
void AppendLine ()
Append an empty line to the builder, indented by the running indentation of the builder.
void AppendLine (const FName &Name)
Append the given name line to the builder, indented by the running indentation of the builder.
void AppendLine (const FString &String)
Append the given string line to the builder, indented by the running indentation of the builder.
void AppendLine (const FText &Text)
Append the given text line to the builder, indented by the running indentation of the builder.
void AppendLineFormat (const FTextFormat &Pattern, const FFormatNamedArguments &Arguments)
Append the given formatted text line to the builder, indented by the running indentation of the builder.
void AppendLineFormat (const FTextFormat &Pattern, const FFormatOrderedArguments &Arguments)
Append the given formatted text line to the builder, indented by the running indentation of the builder.
template<typename... ArgTypes>
FORCEINLINE void AppendLineFormat (FTextFormat Pattern, ArgTypes... Args)
Append the given formatted text line to the builder, indented by the running indentation of the builder.
void Clear ()
Clear the builder and reset it to its default state.
int32 GetNumLines () const
Returns the number of lines.
void Indent ()
Increase the running indentation of the builder.
bool IsEmpty () const
Check to see if the builder has any data.
FText ToText () const
Build the current set of input into a FText.
void Unindent ()
Decrease the running indentation of the builder.
Private Member Functions
void BuildAndAppendLine (FString &&Data)
void BuildAndAppendLine (FText &&Data)
Private Attributes
int32 IndentCount = 0
TArray< FText > Lines
Detailed Description
Definition at line 1313 of file Text.h.
Member Function Documentation
AppendLine() [1/4]
void FTextBuilder::AppendLine ()
Append an empty line to the builder, indented by the running indentation of the builder.
AppendLine() [2/4]
void FTextBuilder::AppendLine (const FName & Name)
Append the given name line to the builder, indented by the running indentation of the builder.
References Name.
AppendLine() [3/4]
void FTextBuilder::AppendLine (const FString & String)
Append the given string line to the builder, indented by the running indentation of the builder.
References String.
AppendLine() [4/4]
void FTextBuilder::AppendLine (const FText & Text)
Append the given text line to the builder, indented by the running indentation of the builder.
References Text.
AppendLineFormat() [1/3]
void FTextBuilder::AppendLineFormat (const FTextFormat & Pattern, const FFormatNamedArguments & Arguments)
Append the given formatted text line to the builder, indented by the running indentation of the builder.
AppendLineFormat() [2/3]
void FTextBuilder::AppendLineFormat (const FTextFormat & Pattern, const FFormatOrderedArguments & Arguments)
Append the given formatted text line to the builder, indented by the running indentation of the builder.
AppendLineFormat() [3/3]
template<typename... ArgTypes> FORCEINLINE void FTextBuilder::AppendLineFormat (FTextFormat Pattern, ArgTypes... Args) inline
Append the given formatted text line to the builder, indented by the running indentation of the builder.
Definition at line 1360 of file Text.h.
References BuildAndAppendLine(), FORCEINLINE, FText::Format(), MoveTemp(), and TIsConstructible< T, Args >::Value.
BuildAndAppendLine() [1/2]
void FTextBuilder::BuildAndAppendLine (FString && Data) private
Referenced by AppendLineFormat().
BuildAndAppendLine() [2/2]
void FTextBuilder::BuildAndAppendLine (FText && Data) private
Clear()
void FTextBuilder::Clear ()
Clear the builder and reset it to its default state.
GetNumLines()
int32 FTextBuilder::GetNumLines () const
Returns the number of lines.
Indent()
void FTextBuilder::Indent ()
Increase the running indentation of the builder.
IsEmpty()
bool FTextBuilder::IsEmpty () const
Check to see if the builder has any data.
ToText()
FText FTextBuilder::ToText () const
Build the current set of input into a FText.
Unindent()
void FTextBuilder::Unindent ()
Decrease the running indentation of the builder.
Field Documentation
IndentCount
int32 FTextBuilder::IndentCount = 0 private
Definition at line 1393 of file Text.h.
Lines
TArray<FText> FTextBuilder::Lines private
Definition at line 1392 of file Text.h.
The documentation for this class was generated from the following file:
Runtime/Core/Public/Internationalization/Text.h