Unreal Engine 5.6 C++ API: FEngineVersionBase Class Reference
FEngineVersionBase Class Reference
Base class for the EngineVersion class.
#include "EngineVersionBase.h"
Public Member Functions
FEngineVersionBase ()=default
Empty constructor.
FEngineVersionBase (uint16 InMajor, uint16 InMinor, uint16 InPatch=0, uint32 InChangelist=0)
Constructs a version from the given components.
uint32 GetChangelist () const
Returns the changelist number corresponding to this version.
FORCEINLINE uint16 GetMajor () const
Returns the Major version number corresponding to this version.
FORCEINLINE uint16 GetMinor () const
Returns the Minor version number corresponding to this version.
FORCEINLINE uint16 GetPatch () const
Returns the Patch version number corresponding to this version.
bool HasChangelist () const
Returns whether the engine version has a changelist component.
bool IsEmpty () const
Returns whether the current version is empty.
bool IsLicenseeVersion () const
Checks if the changelist number represents licensee changelist number.
Static Public Member Functions
static uint32 EncodeLicenseeChangelist (uint32 Changelist)
Encodes a licensee changelist number (by setting the top bit)
static EVersionComparison GetNewest (const FEngineVersionBase &First, const FEngineVersionBase &Second, EVersionComponent *OutComponent)
Returns the newest of two versions, and the component at which they differ.
Protected Attributes
uint32 Changelist = 0
Changelist number.
uint16 Major = 0
Major version number.
uint16 Minor = 0
Minor version number.
uint16 Patch = 0
Patch version number.
Detailed Description
Base class for the EngineVersion class.
Holds basic version numbers.
Definition at line 28 of file EngineVersionBase.h.
Constructor & Destructor Documentation
FEngineVersionBase() [1/2]
FEngineVersionBase::FEngineVersionBase () default
Empty constructor.
Initializes the version to 0.0.0-0.
Referenced by GetNewest(), and FEngineVersion::IsCompatibleWith().
FEngineVersionBase() [2/2]
FEngineVersionBase::FEngineVersionBase (uint16 InMajor, uint16 InMinor, uint16 InPatch = 0, uint32 InChangelist = 0)
Constructs a version from the given components.
Member Function Documentation
EncodeLicenseeChangelist()
uint32 FEngineVersionBase::EncodeLicenseeChangelist (uint32 Changelist) static
Encodes a licensee changelist number (by setting the top bit)
References Changelist.
GetChangelist()
uint32 FEngineVersionBase::GetChangelist () const
Returns the changelist number corresponding to this version.
GetMajor()
FORCEINLINE uint16 FEngineVersionBase::GetMajor () const inline
Returns the Major version number corresponding to this version.
Definition at line 42 of file EngineVersionBase.h.
References FORCEINLINE, and Major.
GetMinor()
FORCEINLINE uint16 FEngineVersionBase::GetMinor () const inline
Returns the Minor version number corresponding to this version.
Definition at line 48 of file EngineVersionBase.h.
References FORCEINLINE, and Minor.
GetNewest()
EVersionComparison FEngineVersionBase::GetNewest (const FEngineVersionBase & First, const FEngineVersionBase & Second, EVersionComponent * OutComponent) static
Returns the newest of two versions, and the component at which they differ.
References FEngineVersionBase(), First, and Second.
GetPatch()
FORCEINLINE uint16 FEngineVersionBase::GetPatch () const inline
Returns the Patch version number corresponding to this version.
Definition at line 54 of file EngineVersionBase.h.
References FORCEINLINE, and Patch.
HasChangelist()
bool FEngineVersionBase::HasChangelist () const
Returns whether the engine version has a changelist component.
IsEmpty()
bool FEngineVersionBase::IsEmpty () const
Returns whether the current version is empty.
IsLicenseeVersion()
bool FEngineVersionBase::IsLicenseeVersion () const
Checks if the changelist number represents licensee changelist number.
Field Documentation
Changelist
uint32 FEngineVersionBase::Changelist = 0 protected
Changelist number.
This is used to arbitrate when Major/Minor/Patch version numbers match. Use GetChangelist() instead of using this member directly.
Definition at line 86 of file EngineVersionBase.h.
Referenced by EncodeLicenseeChangelist().
Major
uint16 FEngineVersionBase::Major = 0 protected
Major version number.
Definition at line 77 of file EngineVersionBase.h.
Referenced by GetMajor().
Minor
uint16 FEngineVersionBase::Minor = 0 protected
Minor version number.
Definition at line 80 of file EngineVersionBase.h.
Referenced by GetMinor().
Patch
uint16 FEngineVersionBase::Patch = 0 protected
Patch version number.
Definition at line 83 of file EngineVersionBase.h.
Referenced by GetPatch().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Misc/EngineVersionBase.h