Unreal Engine 5.6 C++ API: IMovieScenePlayer Class Reference
IMovieScenePlayer Class Reference abstract
Interface for movie scene players Provides information for playback of a movie scene.
#include "IMovieScenePlayer.h"
Public Member Functions
MOVIESCENE_API IMovieScenePlayer ()
virtual MOVIESCENE_API ~IMovieScenePlayer ()
void AddBindingOverride (const FMovieSceneEvaluationOperand &InOperand, const FMovieSceneEvaluationOperand &InOverrideOperand)
Adds an override for the given operand.
virtual UObject * AsUObject ()
Cast this player instance as a UObject if possible.
virtual UMovieSceneEntitySystemLinker * ConstructEntitySystemLinker ()
Called to retrieve or construct an entity linker for the specified playback context.
virtual MOVIESCENE_API FGuid CreateBinding (UMovieSceneSequence *InSequence, UObject *InObject)
void DiscardPreAnimatedState ()
Discard all pre-animated state without restoring it.
MOVIESCENE_API TArrayView< TWeakObjectPtr<> > FindBoundObjects (const FGuid &ObjectBindingID, FMovieSceneSequenceIDRef SequenceID)
Locate objects bound to the specified object guid, in the specified sequence.
TArrayView< TWeakObjectPtr<> > FindBoundObjects (const FMovieSceneEvaluationOperand &Operand)
Locate objects bound to the specified sequence operand.
FGuid FindCachedObjectId (UObject &InObject, FMovieSceneSequenceIDRef SequenceID)
Attempt to find the object binding ID for the specified object, in the specified sequence.
FGuid FindObjectId (UObject &InObject, FMovieSceneSequenceIDRef SequenceID)
Attempt to find the object binding ID for the specified object, in the specified sequence.
MOVIESCENE_API TSharedPtr< UE::MovieScene::FSharedPlaybackState > FindSharedPlaybackState ()
Returns the evaluated sequence instance's shared playback state, if any.
MOVIESCENE_API TSharedPtr< const UE::MovieScene::FSharedPlaybackState > FindSharedPlaybackState () const
FMovieSceneEvaluationOperand * GetBindingOverride (const FMovieSceneEvaluationOperand &InOperand)
Retrieves any override for the given operand.
MOVIESCENE_API FMovieSceneEvaluationState * GetEvaluationState ()
Gets the evaluation state that stores global state to do with the playback operation.
virtual FMovieSceneRootEvaluationTemplateInstance & GetEvaluationTemplate ()=0
Access the evaluation template that we are playing back.
virtual MOVIESCENE_API TArray< UObject * > GetEventContexts () const
Access the event contexts for this movie scene player.
virtual TScriptInterface< IMovieSceneSequencePlayerObserver > GetObserver ()
virtual IMovieScenePlaybackClient * GetPlaybackClient ()
Access the client in charge of playback.
const IMovieScenePlaybackClient * GetPlaybackClient () const
virtual UObject * GetPlaybackContext () const
Access the playback context for this movie scene player.
MOVIESCENE_API TSharedRef< UE::MovieScene::FSharedPlaybackState > GetSharedPlaybackState ()
Returns the evaluated sequence instance's shared playback state, asserts if there is none.
MOVIESCENE_API TSharedRef< const UE::MovieScene::FSharedPlaybackState > GetSharedPlaybackState () const
virtual FMovieSceneSpawnRegister & GetSpawnRegister ()
Obtain an object responsible for managing movie scene spawnables.
MOVIESCENE_API UE::MovieScene::IStaticBindingOverridesPlaybackCapability * GetStaticBindingOverrides ()
Gets the list of binding overrides to use for the sequence.
uint16 GetUniqueIndex () const
virtual bool HasDynamicWeighting () const
Whether this player utilizes dynamic weighting.
virtual MOVIESCENE_API void InitializeRootInstance (TSharedRef< UE::MovieScene::FSharedPlaybackState > NewSharedPlaybackState)
Initializes a new root sequence instance and its shared playback state.
MOVIESCENE_API void InvalidateCachedData ()
Invalidate any cached state contained within this player causing all entities to be forcibly re-linked and evaluated.
virtual MOVIESCENE_API bool IsDisablingEventTriggers (FFrameTime &DisabledUntilTime) const
Returns whether event triggers are disabled and if so, until what time.
MOVIESCENE_API bool IsEvaluating () const
virtual bool IsPreview () const
Test whether this is a preview player or not.
virtual void NotifyBindingsChanged () override
Called whenever any object bindings have changed.
virtual void NotifyBindingUpdate (const FGuid &InGuid, FMovieSceneSequenceIDRef InSequenceID, TArrayView< TWeakObjectPtr<> > Objects) override
Called whenever an object binding has been resolved to give the player a chance to interact with the objects before they are animated.
virtual void OnObjectSpawned (UObject *InObject, const FMovieSceneEvaluationOperand &Operand)
UE_DEPRECATED(5.4, "Director instances are now automanaged via FSequenceDirectorPlaybackCapability") UObject *GetOrCreateDirectorInstance(TSharedRef< const UE virtual MOVIESCENE_API void PopulateUpdateFlags (UE::MovieScene::ESequenceInstanceUpdateFlags &OutFlags)
Gets a new or existing director blueprint instance for the given root or sub sequence.
virtual void PostEvaluation (const FMovieSceneContext &Context)
Called by the evaluation system after evaluation has occured.
virtual void PreEvaluation (const FMovieSceneContext &Context)
Called by the evaluation system when evaluation has just started.
void RemoveBindingOverride (const FMovieSceneEvaluationOperand &InOperand)
Removes any override set for the given operand.
virtual MOVIESCENE_API void ResolveBoundObjects (UE::UniversalObjectLocator::FResolveParams &ResolveParams, const FGuid &InBindingId, FMovieSceneSequenceID SequenceID, UMovieSceneSequence &Sequence, TArray< UObject *, TInlineAllocator< 1 > > &OutObjects) const
Resolve objects bound to the specified binding ID.
void RestorePreAnimatedState ()
Restore all pre-animated state.
FORCEINLINE void SavePreAnimatedState (FMovieSceneAnimTypeID InTokenType, const IMovieScenePreAnimatedGlobalTokenProducer &InProducer)
Attempt to save specific state for the specified token state before it mutates state.
FORCEINLINE void SavePreAnimatedState (UObject &InObject, FMovieSceneAnimTypeID InTokenType, const IMovieScenePreAnimatedTokenProducer &InProducer)
Attempt to save specific state for the specified token state before it animates an object.
virtual void SetPlaybackStatus (EMovieScenePlayerStatus::Type InPlaybackStatus)=0
UE_DEPRECATED (5.4, "Camera cut management has moved to UMovieSceneCameraCutTrackInstance") virtual bool CanUpdateCameraCut() const
UE_DEPRECATED (5.4, "Camera cut management has moved to UMovieSceneCameraCutTrackInstance") virtual void UpdateCameraCut(UObject *CameraObject
UE_DEPRECATED (5.4, "Director instances are now automanaged via FSequenceDirectorPlaybackCapability") void ResetDirectorInstances()
Remove all director blueprint instances.
UE_DEPRECATED (5.4, "Please either call IMovieScenePlayer::FindBoundObjects, FMovieSceneObjectBindingID::ResolveBoundObjects, or FMovieSceneEvaluationState::FindBoundObjects") MOVIESCENE_API virtual void ResolveBoundObjects(const FGuid &InBindingId
Resolve objects bound to the specified binding ID.
UE_DEPRECATED (5.5, "Viewport settings management has moved to FViewportSettingsPlaybackCapability") virtual void SetViewportSettings(const TMap< FViewportClient *
UE_DEPRECATED (5.6, "Please use GetEvaluationState().") FMovieSceneEvaluationState State
Evaluation state that stores global state to do with the playback operation.
UE_DEPRECATED (5.6, "Please use GetStaticBindingOverrides().") TMap< FMovieSceneEvaluationOperand
List of binding overrides to use for the sequence.
Public Member Functions inherited from UE::MovieScene::IObjectBindingNotifyPlaybackCapability
UE_DECLARE_MOVIESCENE_PLAYBACK_CAPABILITY_API (MOVIESCENE_API, IObjectBindingNotifyPlaybackCapability) virtual void NotifyBindingsChanged()
Called when multiple object bindings have changed.
Static Public Member Functions
static MOVIESCENE_API void Get (TArray< IMovieScenePlayer * > &OutPlayers, bool bOnlyUnstoppedPlayers)
static MOVIESCENE_API IMovieScenePlayer * Get (uint16 InUniqueIndex)
static MOVIESCENE_API void SetIsEvaluatingFlag (uint16 InUniqueIndex, bool bIsUpdating)
Data Fields
FMovieSceneEvaluationOperand & BindingOverrides
UObject bool bJumpCut
FMovieSceneSequenceID UMovieSceneSequence UObject TArray< UObject *, TInlineAllocator< 1 > > &OutObjects const
FMovieScenePreAnimatedState PreAnimatedState
Container that stores any per-animated state tokens.
FMovieSceneSequenceID UMovieSceneSequence UObject * ResolutionContext
FMovieSceneSequenceID UMovieSceneSequence & Sequence
FMovieSceneSequenceID SequenceID
UObject * UnlockIfCameraObject = nullptr
EMovieSceneViewportParams & ViewportParamsMap
Private Attributes
FNullMovieSceneSpawnRegister NullRegister
Null register that asserts on use.
UE::MovieScene::FStaticBindingOverrides StaticBindingOverrides
Static binding overrides.
uint16 UniqueIndex
This player's unique Index.
Detailed Description
Interface for movie scene players Provides information for playback of a movie scene.
Definition at line 88 of file IMovieScenePlayer.h.
Constructor & Destructor Documentation
IMovieScenePlayer()
MOVIESCENE_API IMovieScenePlayer::IMovieScenePlayer ()
Referenced by Get(), and GetPlaybackClient().
~IMovieScenePlayer()
virtual MOVIESCENE_API IMovieScenePlayer::~IMovieScenePlayer () virtual
Member Function Documentation
AddBindingOverride()
void IMovieScenePlayer::AddBindingOverride (const FMovieSceneEvaluationOperand & InOperand, const FMovieSceneEvaluationOperand & InOverrideOperand)
Adds an override for the given operand.
AsUObject()
virtual UObject * IMovieScenePlayer::AsUObject () inline virtual
Cast this player instance as a UObject if possible.
Reimplemented in FMovieSceneLegacyPlayer.
Definition at line 109 of file IMovieScenePlayer.h.
ConstructEntitySystemLinker()
virtual UMovieSceneEntitySystemLinker * IMovieScenePlayer::ConstructEntitySystemLinker () inline virtual
Called to retrieve or construct an entity linker for the specified playback context.
Reimplemented in FMovieSceneLegacyPlayer.
Definition at line 104 of file IMovieScenePlayer.h.
CreateBinding()
virtual MOVIESCENE_API FGuid IMovieScenePlayer::CreateBinding (UMovieSceneSequence * InSequence, UObject * InObject) virtual
Reimplemented in ISequencer.
DiscardPreAnimatedState()
void IMovieScenePlayer::DiscardPreAnimatedState () inline
Discard all pre-animated state without restoring it.
Definition at line 352 of file IMovieScenePlayer.h.
References GetSharedPlaybackState(), PRAGMA_DISABLE_DEPRECATION_WARNINGS, PRAGMA_ENABLE_DEPRECATION_WARNINGS, PreAnimatedState, and State.
FindBoundObjects() [1/2]
MOVIESCENE_API TArrayView< TWeakObjectPtr<> > IMovieScenePlayer::FindBoundObjects (const FGuid & ObjectBindingID, FMovieSceneSequenceIDRef SequenceID)
Locate objects bound to the specified object guid, in the specified sequence.
Note
: Objects lists are cached internally until they are invalidate.
Parameters
ObjectBindingID The object to resolve
SequenceID ID of the sequence to resolve for
Returns
Iterable list of weak object pointers pertaining to the specified GUID
References SequenceID.
Referenced by Sequencer::AddKeyForExternalValue(), TPropertyTrackExecutionToken< PropertyValueType, IntermediateType >::Execute(), FindBoundObjects(), and ISequencer::FindObjectsInCurrentSequence().
FindBoundObjects() [2/2]
TArrayView< TWeakObjectPtr<> > IMovieScenePlayer::FindBoundObjects (const FMovieSceneEvaluationOperand & Operand) inline
Locate objects bound to the specified sequence operand.
Note
: Objects lists are cached internally until they are invalidate.
Parameters
Operand The movie scene operand to resolve
Returns
Iterable list of weak object pointers pertaining to the specified GUID
Definition at line 276 of file IMovieScenePlayer.h.
References FindBoundObjects().
FindCachedObjectId()
FGuid IMovieScenePlayer::FindCachedObjectId (UObject & InObject, FMovieSceneSequenceIDRef SequenceID) inline
Attempt to find the object binding ID for the specified object, in the specified sequence.
Note
: Does not clear the existing cache
Parameters
InObject The object to find a GUID for
SequenceID The sequence ID to search within
Returns
The guid of the object's binding, or zero guid if it was not found
Definition at line 306 of file IMovieScenePlayer.h.
References GetSharedPlaybackState(), PRAGMA_DISABLE_DEPRECATION_WARNINGS, PRAGMA_ENABLE_DEPRECATION_WARNINGS, SequenceID, and State.
FindObjectId()
FGuid IMovieScenePlayer::FindObjectId (UObject & InObject, FMovieSceneSequenceIDRef SequenceID) inline
Attempt to find the object binding ID for the specified object, in the specified sequence.
Note
: Will forcably resolve all out-of-date object mappings in the sequence
Parameters
InObject The object to find a GUID for
SequenceID The sequence ID to search within
Returns
The guid of the object's binding, or zero guid if it was not found
Definition at line 290 of file IMovieScenePlayer.h.
References GetSharedPlaybackState(), PRAGMA_DISABLE_DEPRECATION_WARNINGS, PRAGMA_ENABLE_DEPRECATION_WARNINGS, SequenceID, and State.
FindSharedPlaybackState() [1/2]
MOVIESCENE_API TSharedPtr< UE::MovieScene::FSharedPlaybackState > IMovieScenePlayer::FindSharedPlaybackState ()
Returns the evaluated sequence instance's shared playback state, if any.
FindSharedPlaybackState() [2/2]
MOVIESCENE_API TSharedPtr< const UE::MovieScene::FSharedPlaybackState > IMovieScenePlayer::FindSharedPlaybackState () const
Get() [1/2]
MOVIESCENE_API void IMovieScenePlayer::Get (TArray< IMovieScenePlayer * > & OutPlayers, bool bOnlyUnstoppedPlayers) static
Get() [2/2]
MOVIESCENE_API IMovieScenePlayer * IMovieScenePlayer::Get (uint16 InUniqueIndex) static
References IMovieScenePlayer().
GetBindingOverride()
FMovieSceneEvaluationOperand * IMovieScenePlayer::GetBindingOverride (const FMovieSceneEvaluationOperand & InOperand)
Retrieves any override for the given operand.
GetEvaluationState()
MOVIESCENE_API FMovieSceneEvaluationState * IMovieScenePlayer::GetEvaluationState ()
Gets the evaluation state that stores global state to do with the playback operation.
GetEvaluationTemplate()
virtual FMovieSceneRootEvaluationTemplateInstance & IMovieScenePlayer::GetEvaluationTemplate () pure virtual
Access the evaluation template that we are playing back.
Implemented in FMovieSceneLegacyPlayer.
GetEventContexts()
virtual MOVIESCENE_API TArray< UObject * > IMovieScenePlayer::GetEventContexts () const virtual
Access the event contexts for this movie scene player.
GetObserver()
virtual TScriptInterface< IMovieSceneSequencePlayerObserver > IMovieScenePlayer::GetObserver () inline virtual
Definition at line 248 of file IMovieScenePlayer.h.
GetPlaybackClient() [1/2]
virtual IMovieScenePlaybackClient * IMovieScenePlayer::GetPlaybackClient () inline virtual
Access the client in charge of playback.
Returns
A pointer to the playback client, or nullptr if one is not available
Reimplemented in FMovieSceneLegacyPlayer.
Definition at line 149 of file IMovieScenePlayer.h.
References GetPlaybackClient().
Referenced by GetPlaybackClient().
GetPlaybackClient() [2/2]
const IMovieScenePlaybackClient * IMovieScenePlayer::GetPlaybackClient () const inline
Definition at line 151 of file IMovieScenePlayer.h.
References IMovieScenePlayer(), and GetPlaybackClient().
Referenced by GetPlaybackClient().
GetPlaybackContext()
virtual UObject * IMovieScenePlayer::GetPlaybackContext () const inline virtual
Access the playback context for this movie scene player.
Reimplemented in FMovieSceneLegacyPlayer.
Definition at line 213 of file IMovieScenePlayer.h.
References GetPlaybackContext().
Referenced by GetPlaybackContext().
GetSharedPlaybackState() [1/2]
MOVIESCENE_API TSharedRef< UE::MovieScene::FSharedPlaybackState > IMovieScenePlayer::GetSharedPlaybackState ()
Returns the evaluated sequence instance's shared playback state, asserts if there is none.
Referenced by DiscardPreAnimatedState(), FindCachedObjectId(), FindObjectId(), and RestorePreAnimatedState().
GetSharedPlaybackState() [2/2]
MOVIESCENE_API TSharedRef< const UE::MovieScene::FSharedPlaybackState > IMovieScenePlayer::GetSharedPlaybackState () const
GetSpawnRegister()
virtual FMovieSceneSpawnRegister & IMovieScenePlayer::GetSpawnRegister () inline virtual
Obtain an object responsible for managing movie scene spawnables.
Reimplemented in FMovieSceneLegacyPlayer.
Definition at line 156 of file IMovieScenePlayer.h.
References NullRegister.
GetStaticBindingOverrides()
MOVIESCENE_API UE::MovieScene::IStaticBindingOverridesPlaybackCapability * IMovieScenePlayer::GetStaticBindingOverrides ()
Gets the list of binding overrides to use for the sequence.
GetUniqueIndex()
uint16 IMovieScenePlayer::GetUniqueIndex () const inline
Definition at line 384 of file IMovieScenePlayer.h.
References UniqueIndex.
HasDynamicWeighting()
virtual bool IMovieScenePlayer::HasDynamicWeighting () const inline virtual
Whether this player utilizes dynamic weighting.
Definition at line 233 of file IMovieScenePlayer.h.
InitializeRootInstance()
virtual MOVIESCENE_API void IMovieScenePlayer::InitializeRootInstance (TSharedRef< UE::MovieScene::FSharedPlaybackState > NewSharedPlaybackState) virtual
Initializes a new root sequence instance and its shared playback state.
This adds all the player's playback capabilities to the given state.
Reimplemented in FMovieSceneLegacyPlayer.
InvalidateCachedData()
MOVIESCENE_API void IMovieScenePlayer::InvalidateCachedData ()
Invalidate any cached state contained within this player causing all entities to be forcibly re-linked and evaluated.
IsDisablingEventTriggers()
virtual MOVIESCENE_API bool IMovieScenePlayer::IsDisablingEventTriggers (FFrameTime & DisabledUntilTime) const virtual
Returns whether event triggers are disabled and if so, until what time.
IsEvaluating()
MOVIESCENE_API bool IMovieScenePlayer::IsEvaluating () const
IsPreview()
virtual bool IMovieScenePlayer::IsPreview () const inline virtual
Test whether this is a preview player or not.
As such, playback range becomes insignificant for things like spawnables
Definition at line 228 of file IMovieScenePlayer.h.
NotifyBindingsChanged()
virtual void IMovieScenePlayer::NotifyBindingsChanged () inline override virtual
Called whenever any object bindings have changed.
Definition at line 176 of file IMovieScenePlayer.h.
Referenced by NotifyBindingUpdate().
NotifyBindingUpdate()
virtual void IMovieScenePlayer::NotifyBindingUpdate (const FGuid & InGuid, FMovieSceneSequenceIDRef InSequenceID, TArrayView< TWeakObjectPtr<> > Objects) inline override virtual
Called whenever an object binding has been resolved to give the player a chance to interact with the objects before they are animated.
Parameters
InGuid The guid of the object binding that has been resolved
InSequenceID The ID of the sequence in which the object binding resides
Objects The array of objects that were resolved
Reimplemented from UE::MovieScene::IObjectBindingNotifyPlaybackCapability.
Definition at line 171 of file IMovieScenePlayer.h.
References NotifyBindingsChanged().
OnObjectSpawned()
virtual void IMovieScenePlayer::OnObjectSpawned (UObject * InObject, const FMovieSceneEvaluationOperand & Operand) inline virtual
Definition at line 162 of file IMovieScenePlayer.h.
PopulateUpdateFlags()
UE_DEPRECATED(5.4, "Director instances are now automanaged via FSequenceDirectorPlaybackCapability") UObject *GetOrCreateDirectorInstance(TSharedRef< const UE virtual MOVIESCENE_API void IMovieScenePlayer::PopulateUpdateFlags (UE::MovieScene::ESequenceInstanceUpdateFlags & OutFlags) virtual
Gets a new or existing director blueprint instance for the given root or sub sequence.
Called to initialize the flag structure that denotes what functions need to be called on this updater
References PopulateUpdateFlags().
Referenced by PopulateUpdateFlags().
PostEvaluation()
virtual void IMovieScenePlayer::PostEvaluation (const FMovieSceneContext & Context) inline virtual
Called by the evaluation system after evaluation has occured.
Definition at line 243 of file IMovieScenePlayer.h.
PreEvaluation()
virtual void IMovieScenePlayer::PreEvaluation (const FMovieSceneContext & Context) inline virtual
Called by the evaluation system when evaluation has just started.
Definition at line 238 of file IMovieScenePlayer.h.
RemoveBindingOverride()
void IMovieScenePlayer::RemoveBindingOverride (const FMovieSceneEvaluationOperand & InOperand)
Removes any override set for the given operand.
ResolveBoundObjects()
virtual MOVIESCENE_API void IMovieScenePlayer::ResolveBoundObjects (UE::UniversalObjectLocator::FResolveParams & ResolveParams, const FGuid & InBindingId, FMovieSceneSequenceID SequenceID, UMovieSceneSequence & Sequence, TArray< UObject *, TInlineAllocator< 1 > > & OutObjects) const virtual
Resolve objects bound to the specified binding ID.
Parameters
InBindingId The ID relating to the object(s) to resolve
OutObjects Container to populate with the bound objects
References Sequence, and SequenceID.
RestorePreAnimatedState()
void IMovieScenePlayer::RestorePreAnimatedState () inline
Restore all pre-animated state.
Definition at line 341 of file IMovieScenePlayer.h.
References GetSharedPlaybackState(), PRAGMA_DISABLE_DEPRECATION_WARNINGS, PRAGMA_ENABLE_DEPRECATION_WARNINGS, PreAnimatedState, and State.
SavePreAnimatedState() [1/2]
FORCEINLINE void IMovieScenePlayer::SavePreAnimatedState (FMovieSceneAnimTypeID InTokenType, const IMovieScenePreAnimatedGlobalTokenProducer & InProducer) inline
Attempt to save specific state for the specified token state before it mutates state.
Note
: Will only call IMovieSceneExecutionToken::CacheExistingState if no state has been previously cached for the specified token type
Parameters
InTokenType Unique marker that identifies the originating token type
InProducer Producer implementation that defines how to create the preanimated token, if it doesn't already exist
Definition at line 333 of file IMovieScenePlayer.h.
References FORCEINLINE, and PreAnimatedState.
SavePreAnimatedState() [2/2]
FORCEINLINE void IMovieScenePlayer::SavePreAnimatedState (UObject & InObject, FMovieSceneAnimTypeID InTokenType, const IMovieScenePreAnimatedTokenProducer & InProducer) inline
Attempt to save specific state for the specified token state before it animates an object.
Note
: Will only call IMovieSceneExecutionToken::CacheExistingState if no state has been previously cached for the specified token type
Parameters
InObject The object to cache state for
InTokenType Unique marker that identifies the originating token type
InProducer Producer implementation that defines how to create the preanimated token, if it doesn't already exist
Definition at line 321 of file IMovieScenePlayer.h.
References FORCEINLINE, and PreAnimatedState.
Referenced by TPropertyTrackExecutionToken< PropertyValueType, IntermediateType >::Execute(), and TBlendableTokenStack< DataType >::SavePreAnimatedStateImpl().
SetIsEvaluatingFlag()
MOVIESCENE_API void IMovieScenePlayer::SetIsEvaluatingFlag (uint16 InUniqueIndex, bool bIsUpdating) static
SetPlaybackStatus()
virtual void IMovieScenePlayer::SetPlaybackStatus (EMovieScenePlayerStatus::Type InPlaybackStatus) pure virtual
Parameters
PlaybackStatus The playback status to set
Implemented in FMovieSceneLegacyPlayer.
UE_DEPRECATED() [1/7]
IMovieScenePlayer::UE_DEPRECATED (5. 4, "Camera cut management has moved to UMovieSceneCameraCutTrackInstance") const inline
Definition at line 399 of file IMovieScenePlayer.h.
UE_DEPRECATED() [2/7]
IMovieScenePlayer::UE_DEPRECATED (5. 4, "Camera cut management has moved to UMovieSceneCameraCutTrackInstance")
UE_DEPRECATED() [3/7]
IMovieScenePlayer::UE_DEPRECATED (5. 4, "Director instances are now automanaged via FSequenceDirectorPlaybackCapability")
Remove all director blueprint instances.
References const, SequenceID, and UE_DEPRECATED().
UE_DEPRECATED() [4/7]
IMovieScenePlayer::UE_DEPRECATED (5. 4, "Please either call IMovieScenePlayer::FindBoundObjects , FMovieSceneObjectBindingID::ResolveBoundObjects , or FMovieSceneEvaluationState::FindBoundObjects") const &
Resolve objects bound to the specified binding ID.
Parameters
InBindingId The ID relating to the object(s) to resolve
OutObjects Container to populate with the bound objects
UE_DEPRECATED() [5/7]
IMovieScenePlayer::UE_DEPRECATED (5. 5, "Viewport settings management has moved to FViewportSettingsPlaybackCapability") const
Referenced by UE_DEPRECATED(), and UE_DEPRECATED().
UE_DEPRECATED() [6/7]
IMovieScenePlayer::UE_DEPRECATED (5. 6, "Please use GetEvaluationState().")
Evaluation state that stores global state to do with the playback operation.
References State.
UE_DEPRECATED() [7/7]
IMovieScenePlayer::UE_DEPRECATED (5. 6, "Please use GetStaticBindingOverrides().")
List of binding overrides to use for the sequence.
References UE_DEPRECATED().
Field Documentation
BindingOverrides
FMovieSceneEvaluationOperand& IMovieScenePlayer::BindingOverrides
Definition at line 446 of file IMovieScenePlayer.h.
bJumpCut
UObject bool IMovieScenePlayer::bJumpCut
Initial value:
= false)
    {
        EMovieSceneCameraCutParams CameraCutParams;
        CameraCutParams.UnlockIfCameraObject = UnlockIfCameraObject;
        CameraCutParams.bJumpCut = bJumpCut;
        PRAGMA_DISABLE_DEPRECATION_WARNINGS
        UpdateCameraCut(CameraObject, CameraCutParams);
        PRAGMA_ENABLE_DEPRECATION_WARNINGS
    }
    UE_DEPRECATED(5.4, "Camera cut management has moved to UMovieSceneCameraCutTrackInstance")
    virtual void UpdateCameraCut(UObject* CameraObject, const EMovieSceneCameraCutParams& CameraCutParams) {}
protected:
    friend struct FMovieSceneObjectCache
Definition at line 403 of file IMovieScenePlayer.h.
const
FMovieSceneSequenceID UMovieSceneSequence UObject TArray<UObject*, TInlineAllocator<1> >& OutObjects IMovieScenePlayer::const
Definition at line 142 of file IMovieScenePlayer.h.
Referenced by ISequencer::CreateBinding(), ISequencer::GetFilterInterface(), ISequencer::GetFocusedDisplayRate(), ISequencer::GetFocusedTickResolution(), ISequencer::GetRootDisplayRate(), ISequencer::GetRootTickResolution(), ISequencer::GetSupportedCustomBindingTypes(), ISequencer::SetDisplayName(), UE_DEPRECATED(), ISequencer::UE_DEPRECATED(), and ISequencer::UE_DEPRECATED().
NullRegister
FNullMovieSceneSpawnRegister IMovieScenePlayer::NullRegister private
Null register that asserts on use.
Definition at line 451 of file IMovieScenePlayer.h.
Referenced by GetSpawnRegister().
PreAnimatedState
FMovieScenePreAnimatedState IMovieScenePlayer::PreAnimatedState
Container that stores any per-animated state tokens.
Definition at line 442 of file IMovieScenePlayer.h.
Referenced by DiscardPreAnimatedState(), RestorePreAnimatedState(), SavePreAnimatedState(), SavePreAnimatedState(), and TBlendableTokenStack< DataType >::SavePreAnimatedStateImpl().
ResolutionContext
FMovieSceneSequenceID UMovieSceneSequence UObject* IMovieScenePlayer::ResolutionContext
Definition at line 142 of file IMovieScenePlayer.h.
Sequence
FMovieSceneSequenceID UMovieSceneSequence& IMovieScenePlayer::Sequence
Definition at line 142 of file IMovieScenePlayer.h.
Referenced by ISequencer::AddSubSequence(), ResolveBoundObjects(), and ISequencer::SuppressAutoEvaluation().
SequenceID
FMovieSceneSequenceID IMovieScenePlayer::SequenceID
Definition at line 142 of file IMovieScenePlayer.h.
Referenced by FindBoundObjects(), FindCachedObjectId(), FindObjectId(), ISequencer::FindSubSection(), ISequencer::PopToSequenceInstance(), ResolveBoundObjects(), and UE_DEPRECATED().
StaticBindingOverrides
UE::MovieScene::FStaticBindingOverrides IMovieScenePlayer::StaticBindingOverrides private
Static binding overrides.
Definition at line 454 of file IMovieScenePlayer.h.
UniqueIndex
uint16 IMovieScenePlayer::UniqueIndex private
This player's unique Index.
Definition at line 457 of file IMovieScenePlayer.h.
Referenced by GetUniqueIndex().
UnlockIfCameraObject
UObject* IMovieScenePlayer::UnlockIfCameraObject = nullptr
Definition at line 403 of file IMovieScenePlayer.h.
ViewportParamsMap
EMovieSceneViewportParams& IMovieScenePlayer::ViewportParamsMap
Initial value:
{}
    UE_DEPRECATED(5.5, "Viewport settings management has moved to FViewportSettingsPlaybackCapability")
    virtual void GetViewportSettings(TMap<FViewportClient*, EMovieSceneViewportParams>& ViewportParamsMap) const {}
    virtual EMovieScenePlayerStatus::Type GetPlaybackStatus() const = 0
Definition at line 117 of file IMovieScenePlayer.h.
The documentation for this class was generated from the following file:
Runtime/MovieScene/Public/IMovieScenePlayer.h