Unreal Engine 5.6 C++ API: TBaseFunctorDelegateInstance< RetValType(ParamTypes...), UserPolicy, FunctorType, VarTypes... > Class Template Reference
TBaseFunctorDelegateInstance< RetValType(ParamTypes...), UserPolicy, FunctorType, VarTypes... > Class Template Reference
#include "DelegateInstancesImpl.h"
Public Member Functions
template<typename InFunctorType, typename... InVarTypes>
TBaseFunctorDelegateInstance (InFunctorType &&InFunctor, InVarTypes &&... Vars)
void CreateCopy (TDelegateBase< FNotThreadSafeDelegateMode > &Base) const final
void CreateCopy (TDelegateBase< FNotThreadSafeNotCheckedDelegateMode > &Base) const final
void CreateCopy (TDelegateBase< FThreadSafeDelegateMode > &Base) const final
RetValType Execute (ParamTypes... Params) const final
bool ExecuteIfSafe (ParamTypes... Params) const final
uint64 GetBoundProgramCounterForTimerManager () const final
const void * GetObjectForTimerManager () const final
UObject * GetUObject () const final
bool HasSameObject (FDelegateUserObjectConst UserObject) const final
bool IsSafeToExecute () const final
Public Member Functions inherited from TCommonDelegateInstanceState< RetValType(ParamTypes...), UserPolicy, VarTypes... >
TCommonDelegateInstanceState (InVarTypes &&... Vars)
FDelegateHandle GetHandle () const final
Private Types
using DelegateBaseType = typename UserPolicy::FDelegateExtras
using Super = TCommonDelegateInstanceState<RetValType(ParamTypes...), UserPolicy, VarTypes...>
Private Attributes
std::remove_const_t< FunctorType > Functor
Additional Inherited Members
Protected Attributes inherited from TCommonDelegateInstanceState< RetValType(ParamTypes...), UserPolicy, VarTypes... >
FDelegateHandle Handle
TTuple< VarTypes... > Payload
Detailed Description
template<typename RetValType, typename... ParamTypes, typename UserPolicy, typename FunctorType, typename... VarTypes>
class TBaseFunctorDelegateInstance< RetValType(ParamTypes...), UserPolicy, FunctorType, VarTypes... >
Definition at line 812 of file DelegateInstancesImpl.h.
Member Typedef Documentation
DelegateBaseType
template<typename RetValType, typename... ParamTypes, typename UserPolicy, typename FunctorType, typename... VarTypes> using TBaseFunctorDelegateInstance< RetValType(ParamTypes...), UserPolicy, FunctorType, VarTypes... >::DelegateBaseType = typename UserPolicy::FDelegateExtras private
Definition at line 818 of file DelegateInstancesImpl.h.
Super
template<typename RetValType, typename... ParamTypes, typename UserPolicy, typename FunctorType, typename... VarTypes> using TBaseFunctorDelegateInstance< RetValType(ParamTypes...), UserPolicy, FunctorType, VarTypes... >::Super = TCommonDelegateInstanceState<RetValType(ParamTypes...), UserPolicy, VarTypes...> private
Definition at line 817 of file DelegateInstancesImpl.h.
Constructor & Destructor Documentation
TBaseFunctorDelegateInstance()
template<typename RetValType, typename... ParamTypes, typename UserPolicy, typename FunctorType, typename... VarTypes> template<typename InFunctorType, typename... InVarTypes> TBaseFunctorDelegateInstance< RetValType(ParamTypes...), UserPolicy, FunctorType, VarTypes... >::TBaseFunctorDelegateInstance (InFunctorType && InFunctor, InVarTypes &&... Vars) inline explicit
Definition at line 822 of file DelegateInstancesImpl.h.
References Forward(), and Functor.
Referenced by CreateCopy(), CreateCopy(), and CreateCopy().
Member Function Documentation
CreateCopy() [1/3]
template<typename RetValType, typename... ParamTypes, typename UserPolicy, typename FunctorType, typename... VarTypes> void TBaseFunctorDelegateInstance< RetValType(ParamTypes...), UserPolicy, FunctorType, VarTypes... >::CreateCopy (TDelegateBase< FNotThreadSafeDelegateMode > & Base) const inline final
Definition at line 874 of file DelegateInstancesImpl.h.
References TBaseFunctorDelegateInstance().
CreateCopy() [2/3]
template<typename RetValType, typename... ParamTypes, typename UserPolicy, typename FunctorType, typename... VarTypes> void TBaseFunctorDelegateInstance< RetValType(ParamTypes...), UserPolicy, FunctorType, VarTypes... >::CreateCopy (TDelegateBase< FNotThreadSafeNotCheckedDelegateMode > & Base) const inline final
Definition at line 879 of file DelegateInstancesImpl.h.
References TBaseFunctorDelegateInstance().
CreateCopy() [3/3]
template<typename RetValType, typename... ParamTypes, typename UserPolicy, typename FunctorType, typename... VarTypes> void TBaseFunctorDelegateInstance< RetValType(ParamTypes...), UserPolicy, FunctorType, VarTypes... >::CreateCopy (TDelegateBase< FThreadSafeDelegateMode > & Base) const inline final
Definition at line 869 of file DelegateInstancesImpl.h.
References TBaseFunctorDelegateInstance().
Execute()
template<typename RetValType, typename... ParamTypes, typename UserPolicy, typename FunctorType, typename... VarTypes> RetValType TBaseFunctorDelegateInstance< RetValType(ParamTypes...), UserPolicy, FunctorType, VarTypes... >::Execute (ParamTypes... Params) const inline final
Definition at line 884 of file DelegateInstancesImpl.h.
References Forward(), Functor, Params, and TCommonDelegateInstanceState< RetValType(ParamTypes...), UserPolicy, VarTypes... >::Payload.
ExecuteIfSafe()
template<typename RetValType, typename... ParamTypes, typename UserPolicy, typename FunctorType, typename... VarTypes> bool TBaseFunctorDelegateInstance< RetValType(ParamTypes...), UserPolicy, FunctorType, VarTypes... >::ExecuteIfSafe (ParamTypes... Params) const inline final
Definition at line 889 of file DelegateInstancesImpl.h.
References Forward(), Functor, Params, and TCommonDelegateInstanceState< RetValType(ParamTypes...), UserPolicy, VarTypes... >::Payload.
GetBoundProgramCounterForTimerManager()
template<typename RetValType, typename... ParamTypes, typename UserPolicy, typename FunctorType, typename... VarTypes> uint64 TBaseFunctorDelegateInstance< RetValType(ParamTypes...), UserPolicy, FunctorType, VarTypes... >::GetBoundProgramCounterForTimerManager () const inline final
Definition at line 849 of file DelegateInstancesImpl.h.
GetObjectForTimerManager()
template<typename RetValType, typename... ParamTypes, typename UserPolicy, typename FunctorType, typename... VarTypes> const void * TBaseFunctorDelegateInstance< RetValType(ParamTypes...), UserPolicy, FunctorType, VarTypes... >::GetObjectForTimerManager () const inline final
Definition at line 844 of file DelegateInstancesImpl.h.
GetUObject()
template<typename RetValType, typename... ParamTypes, typename UserPolicy, typename FunctorType, typename... VarTypes> UObject * TBaseFunctorDelegateInstance< RetValType(ParamTypes...), UserPolicy, FunctorType, VarTypes... >::GetUObject () const inline final
Definition at line 839 of file DelegateInstancesImpl.h.
HasSameObject()
template<typename RetValType, typename... ParamTypes, typename UserPolicy, typename FunctorType, typename... VarTypes> bool TBaseFunctorDelegateInstance< RetValType(ParamTypes...), UserPolicy, FunctorType, VarTypes... >::HasSameObject (FDelegateUserObjectConst UserObject) const inline final
Definition at line 855 of file DelegateInstancesImpl.h.
IsSafeToExecute()
template<typename RetValType, typename... ParamTypes, typename UserPolicy, typename FunctorType, typename... VarTypes> bool TBaseFunctorDelegateInstance< RetValType(ParamTypes...), UserPolicy, FunctorType, VarTypes... >::IsSafeToExecute () const inline final
Definition at line 861 of file DelegateInstancesImpl.h.
Field Documentation
Functor
template<typename RetValType, typename... ParamTypes, typename UserPolicy, typename FunctorType, typename... VarTypes> std::remove_const_t<FunctorType> TBaseFunctorDelegateInstance< RetValType(ParamTypes...), UserPolicy, FunctorType, VarTypes... >::Functor mutable private
Definition at line 902 of file DelegateInstancesImpl.h.
Referenced by TBaseFunctorDelegateInstance(), Execute(), and ExecuteIfSafe().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Delegates/DelegateInstancesImpl.h