Unreal Engine 5.6 C++ API: FSkinnedMeshComponentHelper Class Reference
FSkinnedMeshComponentHelper Class Reference
Helper class used to share implementation for different SkinnedMeshComponent types.
#include "SkinnedMeshComponentHelper.h"
Static Public Member Functions
template<typename T>
static int32 ComputeMinLOD (const T &InComponent)
template<typename T>
static void GetDefaultMaterialSlotsOverlayMaterial (const T &InComponent, TArray< TObjectPtr< UMaterialInterface > > &OutMaterials)
template<typename T>
static UMaterialInterface * GetMaterial (const T &InComponent, int32 InMaterialIndex)
template<typename T>
static const Nanite::FResources * GetNaniteResources (const T &InComponent)
template<typename T>
static int32 GetNumLODs (const T &InComponent)
template<typename T>
static FSkeletalMeshRenderData * GetSkeletalMeshRenderData (const T &InComponent)
template<typename T>
static void GetUsedMaterials (const T &InComponent, TArray< UMaterialInterface * > &OutMaterials, bool bInGetDebugMaterials)
template<typename T>
static int32 GetValidMinLOD (const T &InComponent, const int32 InMinLODIndex)
template<typename T>
static bool HasValidNaniteData (const T &InComponent)
template<typename T>
static bool ShouldNaniteSkin (const T &InComponent)
Detailed Description
Helper class used to share implementation for different SkinnedMeshComponent types.
Definition at line 19 of file SkinnedMeshComponentHelper.h.
Member Function Documentation
ComputeMinLOD()
template<class T> int32 FSkinnedMeshComponentHelper::ComputeMinLOD (const T & InComponent) static
Definition at line 83 of file SkinnedMeshComponentHelper.h.
References GetValidMinLOD(), and FMath::Max.
Referenced by FInstancedSkinnedMeshComponentHelper::CreateSceneProxy().
GetDefaultMaterialSlotsOverlayMaterial()
template<class T> void FSkinnedMeshComponentHelper::GetDefaultMaterialSlotsOverlayMaterial (const T & InComponent, TArray< TObjectPtr< UMaterialInterface > > & OutMaterials) static
Definition at line 165 of file SkinnedMeshComponentHelper.h.
GetMaterial()
template<class T> UMaterialInterface * FSkinnedMeshComponentHelper::GetMaterial (const T & InComponent, int32 InMaterialIndex) static
Definition at line 108 of file SkinnedMeshComponentHelper.h.
GetNaniteResources()
template<typename T> const Nanite::FResources * FSkinnedMeshComponentHelper::GetNaniteResources (const T & InComponent) static
Definition at line 179 of file SkinnedMeshComponentHelper.h.
Referenced by HasValidNaniteData().
GetNumLODs()
template<class T> int32 FSkinnedMeshComponentHelper::GetNumLODs (const T & InComponent) static
Definition at line 71 of file SkinnedMeshComponentHelper.h.
References GetSkeletalMeshRenderData(), and RenderData.
Referenced by GetValidMinLOD().
GetSkeletalMeshRenderData()
template<class T> FSkeletalMeshRenderData * FSkinnedMeshComponentHelper::GetSkeletalMeshRenderData (const T & InComponent) static
Definition at line 54 of file SkinnedMeshComponentHelper.h.
Referenced by FInstancedSkinnedMeshComponentHelper::CreateMeshObject(), GetNumLODs(), and GetValidMinLOD().
GetUsedMaterials()
template<class T> void FSkinnedMeshComponentHelper::GetUsedMaterials (const T & InComponent, TArray< UMaterialInterface * > & OutMaterials, bool bInGetDebugMaterials) static
Definition at line 126 of file SkinnedMeshComponentHelper.h.
References TArray< InElementType, InAllocatorType >::Add(), FMaterialOverlayHelper::AppendAllOverlayMaterial(), and FMath::Max.
GetValidMinLOD()
template<class T> int32 FSkinnedMeshComponentHelper::GetValidMinLOD (const T & InComponent, const int32 InMinLODIndex) static
NOTE: We're logging if the index is not valid in the render data but we still want to return a valid value from 0 to max. Render data could be invalid if we're still loading/streaming in the asset.
Definition at line 93 of file SkinnedMeshComponentHelper.h.
References FMath::Clamp(), GetNumLODs(), GetSkeletalMeshRenderData(), INDEX_NONE, and RenderData.
Referenced by ComputeMinLOD().
HasValidNaniteData()
template<typename T> bool FSkinnedMeshComponentHelper::HasValidNaniteData (const T & InComponent) static
Definition at line 190 of file SkinnedMeshComponentHelper.h.
References GetNaniteResources(), and Nanite::FResources::PageStreamingStates.
Referenced by ShouldNaniteSkin().
ShouldNaniteSkin()
template<typename T> bool FSkinnedMeshComponentHelper::ShouldNaniteSkin (const T & InComponent) static
Definition at line 197 of file SkinnedMeshComponentHelper.h.
References HasValidNaniteData(), ShaderPlatform, and UseNanite().
Referenced by FInstancedSkinnedMeshComponentHelper::CreateSceneProxy().
The documentation for this class was generated from the following file:
Runtime/Engine/Public/SkinnedMeshComponentHelper.h