Unreal Engine 5.6 C++ API: UE::MeshDeformation::CotanTriangleData Class Reference
UE::MeshDeformation::CotanTriangleData Class Reference
The per-triangle data used in constructing the cotangent weighted laplacian.
#include "PrecomputedMeshWeightData.h"
Public Types
typedef FVector3d TriangleVertices[3]
Public Member Functions
CotanTriangleData ()=default
CotanTriangleData (const FDynamicMesh3 &DynamicMesh, int32 TriId)
bool bIsObtuse () const
int32 GetLocalEdgeIdx (const int32 DynamicsMeshEdgeId) const
double GetOpposingCotangent (const int32 DynamicsMeshEdgeId) const
double GetOpposingCotangent (const int32 DynamicsMeshEdgeId, bool &bValid) const
helper to return the cotangent of the angle opposite the given edge
DYNAMICMESH_API void Initialize (const FDynamicMesh3 &DynamicMesh, int32 SrcTriId)
Data Fields
double Area = -1
double Cotangent [3] = { 0. }
Total byte count: 6 double + 3 int32 = 60 bytes.
int32 OppositeEdge [3] = { -1 }
int32 TriId = -1
double VoronoiArea [3] = { 0. }
Static Public Attributes
static constexpr double SmallTriangleArea = SMALL_NUMBER
Detailed Description
The per-triangle data used in constructing the cotangent weighted laplacian.
Definition at line 52 of file PrecomputedMeshWeightData.h.
Member Typedef Documentation
TriangleVertices
typedef FVector3d UE::MeshDeformation::CotanTriangleData::TriangleVertices[3]
Definition at line 56 of file PrecomputedMeshWeightData.h.
Constructor & Destructor Documentation
CotanTriangleData() [1/2]
UE::MeshDeformation::CotanTriangleData::CotanTriangleData () default
CotanTriangleData() [2/2]
UE::MeshDeformation::CotanTriangleData::CotanTriangleData (const FDynamicMesh3 & DynamicMesh, int32 TriId) inline
Definition at line 60 of file PrecomputedMeshWeightData.h.
References Initialize, and TriId.
Member Function Documentation
bIsObtuse()
bool UE::MeshDeformation::CotanTriangleData::bIsObtuse () const inline
Definition at line 114 of file PrecomputedMeshWeightData.h.
References Cotangent.
GetLocalEdgeIdx()
int32 UE::MeshDeformation::CotanTriangleData::GetLocalEdgeIdx (const int32 DynamicsMeshEdgeId) const inline
Definition at line 67 of file PrecomputedMeshWeightData.h.
References OppositeEdge.
Referenced by GetOpposingCotangent().
GetOpposingCotangent() [1/2]
double UE::MeshDeformation::CotanTriangleData::GetOpposingCotangent (const int32 DynamicsMeshEdgeId) const inline
Definition at line 106 of file PrecomputedMeshWeightData.h.
References checkSlow, and GetOpposingCotangent().
GetOpposingCotangent() [2/2]
double UE::MeshDeformation::CotanTriangleData::GetOpposingCotangent (const int32 DynamicsMeshEdgeId, bool & bValid) const inline
helper to return the cotangent of the angle opposite the given edge
Parameters
DynamicsMeshEdgeId is the id used by FDynamicMesh3 for this edge.
bValid will false on return if the requested edge is not part of this triangle
Returns
Cotangent of the opposite angle.
Definition at line 91 of file PrecomputedMeshWeightData.h.
References Cotangent, and GetLocalEdgeIdx().
Referenced by UE::MeshDeformation::ConstructCotangentLaplacian(), UE::MeshDeformation::ConstructCotangentLaplacian(), UE::MeshDeformation::ConstructFullCotangentLaplacian(), and GetOpposingCotangent().
Initialize()
DYNAMICMESH_API void UE::MeshDeformation::CotanTriangleData::Initialize (const FDynamicMesh3 & DynamicMesh, int32 SrcTriId)
References UE_API.
Field Documentation
Area
double UE::MeshDeformation::CotanTriangleData::Area = -1
Definition at line 141 of file PrecomputedMeshWeightData.h.
Referenced by UE::MeshDeformation::ConstructFullCotangentLaplacian().
Cotangent
double UE::MeshDeformation::CotanTriangleData::Cotangent[3] = { 0. }
Total byte count: 6 double + 3 int32 = 60 bytes.
Definition at line 133 of file PrecomputedMeshWeightData.h.
Referenced by bIsObtuse(), and GetOpposingCotangent().
OppositeEdge
int32 UE::MeshDeformation::CotanTriangleData::OppositeEdge[3] = { -1 }
Definition at line 146 of file PrecomputedMeshWeightData.h.
Referenced by GetLocalEdgeIdx().
SmallTriangleArea
double UE::MeshDeformation::CotanTriangleData::SmallTriangleArea = SMALL_NUMBER static constexpr
Definition at line 124 of file PrecomputedMeshWeightData.h.
TriId
int32 UE::MeshDeformation::CotanTriangleData::TriId = -1
Definition at line 127 of file PrecomputedMeshWeightData.h.
Referenced by CotanTriangleData().
VoronoiArea
double UE::MeshDeformation::CotanTriangleData::VoronoiArea[3] = { 0. }
Definition at line 137 of file PrecomputedMeshWeightData.h.
Referenced by UE::MeshDeformation::ConstructCotangentLaplacian(), UE::MeshDeformation::ConstructCotangentLaplacian(), and UE::MeshDeformation::ConstructFullCotangentLaplacian().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/GeometryProcessing/Source/DynamicMesh/Public/Solvers/PrecomputedMeshWeightData.h