Unreal Engine 5.6 C++ API: FRigVMTreePhase Class Reference
FRigVMTreePhase Class Reference
The Phase describes a phase of performing a UI wizard, like picking a set of inputs, or performing tasks.
#include "RigVMTreeToolkitContext.h"
Public Types
typedef FRigVMTreeElement Super
Public Member Functions
const TArray< TSharedRef< FRigVMTreeTask > > & FRigVMTreePhase (int32 InID, const FString &InName, const TSharedRef< FRigVMTreeContext > &InContext)
void AddNode (const TSharedRef< FRigVMTreeNode > &InNode)
virtual bool AllowsMultiSelection () const
FReply Cancel () const
DECLARE_DELEGATE_RetVal (FReply, FReplyDelegate) DECLARE_DELEGATE_OneParam(FQueueTasksDelegate
TSharedPtr< FRigVMTreeNode > FindVisibleNode (const FString &InPath) const
TArray< TSharedRef< FRigVMTreeNode > > GetAllNodes () const
TSharedRef< FRigVMTreeContext > GetContext () const
int32 GetID () const
const FString & GetName () const
virtual FName GetType () const override
const TArray< TSharedRef< FRigVMTreeNode > > & GetVisibleNodes () const
void IncrementContextHash ()
bool IsActive () const
TAttribute< bool > & IsCancelButtonEnabled ()
TAttribute< bool > & IsCancelButtonVisible ()
virtual bool IsOfType (const FName &InType) const override
TAttribute< bool > & IsPrimaryButtonEnabled ()
TAttribute< bool > & IsPrimaryButtonVisible ()
FReplyDelegate & OnCancel ()
FReplyDelegate & OnPrimaryAction ()
FQueueTasksDelegate & OnQueueTasks ()
FReply PrimaryAction () const
TAttribute< FText > & PrimaryButtonText ()
void QueueTasks (const TArray< TSharedRef< FRigVMTreeTask > > &InTasks) const
void RemoveNode (const TSharedRef< FRigVMTreeNode > &InNode)
void SetAllowsMultiSelection (bool InAllowsMultiSelection)
void SetNodes (const TArray< TSharedRef< FRigVMTreeNode > > &InNodes)
TSharedPtr< FRigVMTreePhase > ToSharedPtr () const
TSharedRef< FRigVMTreePhase > ToSharedRef () const
Public Member Functions inherited from FRigVMTreeElement
virtual ~FRigVMTreeElement ()
virtual void Initialize ()
template<typename T>
bool IsA () const
Public Member Functions inherited from TSharedFromThis< FRigVMTreeElement >
TSharedRef< FRigVMTreeElement, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FRigVMTreeElement, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Static Public Member Functions
template<typename... Types>
static TSharedRef< FRigVMTreePhase > Create (Types... Args)
Static Public Attributes
static const FLazyName Type = FLazyName(TEXT("FRigVMTreePhase"))
Static Public Attributes inherited from FRigVMTreeElement
static const FLazyName Type = FLazyName(TEXT("FRigVMTreeElement"))
Private Attributes
bool bAllowsMultiSelection
bool bIsActive
TSharedRef< FRigVMTreeContext > Context
int32 ID
TAttribute< bool > IsCancelButtonEnabledAttribute
TAttribute< bool > IsCancelButtonVisibleAttribute
TAttribute< bool > IsPrimaryButtonEnabledAttribute
TAttribute< bool > IsPrimaryButtonVisibleAttribute
FString Name
FReplyDelegate OnCancelDelegate
FReplyDelegate OnPrimaryActionDelegate
TAttribute< FText > PrimaryButtonTextAttribute
FQueueTasksDelegate QueueTasksDelegate
TSharedRef< FRigVMTreeRootNode > RootNode
Friends
template<typename T>
TSharedPtr< T > Cast (const TSharedRef< FRigVMTreePhase > &InElement)
template<typename T>
const TSharedRef< T > & CastChecked (const TSharedRef< FRigVMTreePhase > &InElement)
class SRigVMBulkEditWidget
Additional Inherited Members
Protected Member Functions inherited from FRigVMTreeElement
FRigVMTreeElement ()
Protected Member Functions inherited from TSharedFromThis< FRigVMTreeElement >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions inherited from TSharedFromThis< FRigVMTreeElement >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
The Phase describes a phase of performing a UI wizard, like picking a set of inputs, or performing tasks.
This can be also seen as the steps a wizard goes through when performing a UI process.
Definition at line 53 of file RigVMTreeToolkitContext.h.
Member Typedef Documentation
Super
typedef FRigVMTreeElement FRigVMTreePhase::Super
Definition at line 56 of file RigVMTreeToolkitContext.h.
Constructor & Destructor Documentation
FRigVMTreePhase()
const TArray< TSharedRef< FRigVMTreeTask > > & FRigVMTreePhase::FRigVMTreePhase (int32 InID, const FString & InName, const TSharedRef< FRigVMTreeContext > & InContext)
References FRigVMTreePhase(), and InName.
Referenced by FRigVMTreePhase(), and Cast.
Member Function Documentation
AddNode()
void FRigVMTreePhase::AddNode (const TSharedRef< FRigVMTreeNode > & InNode)
AllowsMultiSelection()
virtual bool FRigVMTreePhase::AllowsMultiSelection () const inline virtual
Definition at line 78 of file RigVMTreeToolkitContext.h.
References bAllowsMultiSelection.
Cancel()
FReply FRigVMTreePhase::Cancel () const inline
Definition at line 103 of file RigVMTreeToolkitContext.h.
References OnCancelDelegate, and FReply::Unhandled().
Create()
template<typename... Types> TSharedRef< FRigVMTreePhase > FRigVMTreePhase::Create (Types... Args) inline static
Definition at line 56 of file RigVMTreeToolkitContext.h.
DECLARE_DELEGATE_RetVal()
FRigVMTreePhase::DECLARE_DELEGATE_RetVal (FReply , FReplyDelegate)
References DECLARE_DELEGATE_OneParam, and DECLARE_DELEGATE_RetVal().
Referenced by DECLARE_DELEGATE_RetVal().
FindVisibleNode()
TSharedPtr< FRigVMTreeNode > FRigVMTreePhase::FindVisibleNode (const FString & InPath) const
GetAllNodes()
TArray< TSharedRef< FRigVMTreeNode > > FRigVMTreePhase::GetAllNodes () const
GetContext()
TSharedRef< FRigVMTreeContext > FRigVMTreePhase::GetContext () const inline
Definition at line 141 of file RigVMTreeToolkitContext.h.
References Context.
GetID()
int32 FRigVMTreePhase::GetID () const inline
Definition at line 63 of file RigVMTreeToolkitContext.h.
References GetID(), and ID.
Referenced by GetID().
GetName()
const FString & FRigVMTreePhase::GetName () const inline
Definition at line 68 of file RigVMTreeToolkitContext.h.
References Name.
GetType()
virtual FName FRigVMTreePhase::GetType () const inline override virtual
Reimplemented from FRigVMTreeElement.
Definition at line 56 of file RigVMTreeToolkitContext.h.
GetVisibleNodes()
const TArray< TSharedRef< FRigVMTreeNode > > & FRigVMTreePhase::GetVisibleNodes () const
IncrementContextHash()
void FRigVMTreePhase::IncrementContextHash ()
IsActive()
bool FRigVMTreePhase::IsActive () const inline
Definition at line 73 of file RigVMTreeToolkitContext.h.
References bIsActive.
IsCancelButtonEnabled()
TAttribute< bool > & FRigVMTreePhase::IsCancelButtonEnabled () inline
Definition at line 93 of file RigVMTreeToolkitContext.h.
References IsCancelButtonEnabledAttribute.
IsCancelButtonVisible()
TAttribute< bool > & FRigVMTreePhase::IsCancelButtonVisible () inline
Definition at line 88 of file RigVMTreeToolkitContext.h.
References IsCancelButtonVisibleAttribute.
IsOfType()
virtual bool FRigVMTreePhase::IsOfType (const FName & InType) const inline override virtual
Reimplemented from FRigVMTreeElement.
Definition at line 56 of file RigVMTreeToolkitContext.h.
IsPrimaryButtonEnabled()
TAttribute< bool > & FRigVMTreePhase::IsPrimaryButtonEnabled () inline
Definition at line 117 of file RigVMTreeToolkitContext.h.
References IsPrimaryButtonEnabledAttribute.
IsPrimaryButtonVisible()
TAttribute< bool > & FRigVMTreePhase::IsPrimaryButtonVisible () inline
Definition at line 112 of file RigVMTreeToolkitContext.h.
References IsPrimaryButtonVisibleAttribute.
OnCancel()
FReplyDelegate & FRigVMTreePhase::OnCancel () inline
Definition at line 98 of file RigVMTreeToolkitContext.h.
References OnCancelDelegate.
OnPrimaryAction()
FReplyDelegate & FRigVMTreePhase::OnPrimaryAction () inline
Definition at line 127 of file RigVMTreeToolkitContext.h.
References OnPrimaryActionDelegate.
OnQueueTasks()
FQueueTasksDelegate & FRigVMTreePhase::OnQueueTasks () inline
Definition at line 158 of file RigVMTreeToolkitContext.h.
References QueueTasksDelegate.
PrimaryAction()
FReply FRigVMTreePhase::PrimaryAction () const inline
Definition at line 132 of file RigVMTreeToolkitContext.h.
References OnPrimaryActionDelegate, and FReply::Unhandled().
PrimaryButtonText()
TAttribute< FText > & FRigVMTreePhase::PrimaryButtonText () inline
Definition at line 122 of file RigVMTreeToolkitContext.h.
References PrimaryButtonTextAttribute.
QueueTasks()
void FRigVMTreePhase::QueueTasks (const TArray< TSharedRef< FRigVMTreeTask > > & InTasks) const inline
Definition at line 163 of file RigVMTreeToolkitContext.h.
References QueueTasksDelegate.
RemoveNode()
void FRigVMTreePhase::RemoveNode (const TSharedRef< FRigVMTreeNode > & InNode)
SetAllowsMultiSelection()
void FRigVMTreePhase::SetAllowsMultiSelection (bool InAllowsMultiSelection) inline
Definition at line 83 of file RigVMTreeToolkitContext.h.
References bAllowsMultiSelection.
SetNodes()
void FRigVMTreePhase::SetNodes (const TArray< TSharedRef< FRigVMTreeNode > > & InNodes)
ToSharedPtr()
TSharedPtr< FRigVMTreePhase > FRigVMTreePhase::ToSharedPtr () const inline
Definition at line 56 of file RigVMTreeToolkitContext.h.
ToSharedRef()
TSharedRef< FRigVMTreePhase > FRigVMTreePhase::ToSharedRef () const inline
Definition at line 56 of file RigVMTreeToolkitContext.h.
Friends And Related Symbol Documentation
Cast
template<typename T> TSharedPtr< T > Cast (const TSharedRef< FRigVMTreePhase > & InElement) friend
Definition at line 56 of file RigVMTreeToolkitContext.h.
References FRigVMTreeElement::FRigVMTreeElement(), and FRigVMTreePhase().
CastChecked
template<typename T> const TSharedRef< T > & CastChecked (const TSharedRef< FRigVMTreePhase > & InElement) friend
Definition at line 56 of file RigVMTreeToolkitContext.h.
SRigVMBulkEditWidget
friend class SRigVMBulkEditWidget friend
Definition at line 185 of file RigVMTreeToolkitContext.h.
References SRigVMBulkEditWidget.
Referenced by SRigVMBulkEditWidget.
Field Documentation
bAllowsMultiSelection
bool FRigVMTreePhase::bAllowsMultiSelection private
Definition at line 173 of file RigVMTreeToolkitContext.h.
Referenced by AllowsMultiSelection(), and SetAllowsMultiSelection().
bIsActive
bool FRigVMTreePhase::bIsActive private
Definition at line 172 of file RigVMTreeToolkitContext.h.
Referenced by IsActive().
Context
TSharedRef<FRigVMTreeContext> FRigVMTreePhase::Context private
Definition at line 174 of file RigVMTreeToolkitContext.h.
Referenced by GetContext().
ID
int32 FRigVMTreePhase::ID private
Definition at line 170 of file RigVMTreeToolkitContext.h.
Referenced by GetID().
IsCancelButtonEnabledAttribute
TAttribute<bool> FRigVMTreePhase::IsCancelButtonEnabledAttribute private
Definition at line 177 of file RigVMTreeToolkitContext.h.
Referenced by IsCancelButtonEnabled().
IsCancelButtonVisibleAttribute
TAttribute<bool> FRigVMTreePhase::IsCancelButtonVisibleAttribute private
Definition at line 176 of file RigVMTreeToolkitContext.h.
Referenced by IsCancelButtonVisible().
IsPrimaryButtonEnabledAttribute
TAttribute<bool> FRigVMTreePhase::IsPrimaryButtonEnabledAttribute private
Definition at line 180 of file RigVMTreeToolkitContext.h.
Referenced by IsPrimaryButtonEnabled().
IsPrimaryButtonVisibleAttribute
TAttribute<bool> FRigVMTreePhase::IsPrimaryButtonVisibleAttribute private
Definition at line 179 of file RigVMTreeToolkitContext.h.
Referenced by IsPrimaryButtonVisible().
Name
FString FRigVMTreePhase::Name private
Definition at line 171 of file RigVMTreeToolkitContext.h.
Referenced by GetName().
OnCancelDelegate
FReplyDelegate FRigVMTreePhase::OnCancelDelegate private
Definition at line 178 of file RigVMTreeToolkitContext.h.
Referenced by Cancel(), and OnCancel().
OnPrimaryActionDelegate
FReplyDelegate FRigVMTreePhase::OnPrimaryActionDelegate private
Definition at line 182 of file RigVMTreeToolkitContext.h.
Referenced by OnPrimaryAction(), and PrimaryAction().
PrimaryButtonTextAttribute
TAttribute<FText> FRigVMTreePhase::PrimaryButtonTextAttribute private
Definition at line 181 of file RigVMTreeToolkitContext.h.
Referenced by PrimaryButtonText().
QueueTasksDelegate
FQueueTasksDelegate FRigVMTreePhase::QueueTasksDelegate private
Definition at line 183 of file RigVMTreeToolkitContext.h.
Referenced by OnQueueTasks(), and QueueTasks().
RootNode
TSharedRef<FRigVMTreeRootNode> FRigVMTreePhase::RootNode private
Definition at line 175 of file RigVMTreeToolkitContext.h.
Type
const FLazyName FRigVMTreePhase::Type = FLazyName(TEXT("FRigVMTreePhase")) inline static
Definition at line 56 of file RigVMTreeToolkitContext.h.
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/RigVM/Source/RigVMEditor/Public/Widgets/RigVMTreeToolkitContext.h