Unreal Engine 5.6 C++ API: FRigVMASTProxy Class Reference
FRigVMASTProxy Class Reference
#include "RigVMASTProxy.h"
Public Member Functions
FRigVMASTProxy ()
FRigVMASTProxy (const FRigVMASTProxy &InOther)
const FRigVMCallstack & GetCallstack () const
FRigVMASTProxy GetChild (UObject *InSubject) const
FRigVMASTProxy GetParent () const
FRigVMASTProxy GetSibling (UObject *InSubject) const
UObject * GetSubject () const
template<class T>
T * GetSubject () const
template<class T>
T * GetSubjectChecked () const
template<class T>
bool IsA () const
bool IsValid () const
bool operator!= (const FRigVMASTProxy &Other) const
bool operator< (const FRigVMASTProxy &Other) const
FRigVMASTProxy & operator= (const FRigVMASTProxy &InOther)
bool operator== (const FRigVMASTProxy &Other) const
bool operator> (const FRigVMASTProxy &Other) const
Static Public Member Functions
static FRigVMASTProxy MakeFromCallPath (const FString &InCallPath, UObject *InRootObject)
static FRigVMASTProxy MakeFromCallstack (const FRigVMCallstack &InCallstack)
static FRigVMASTProxy MakeFromCallstack (const TArray< TWeakObjectPtr< UObject > > *InCallstack)
static FRigVMASTProxy MakeFromUObject (UObject *InSubject)
Private Attributes
FRigVMCallstack Callstack
Friends
uint32 GetTypeHash (const FRigVMASTProxy &Proxy)
Detailed Description
Definition at line 130 of file RigVMASTProxy.h.
Constructor & Destructor Documentation
FRigVMASTProxy() [1/2]
FRigVMASTProxy::FRigVMASTProxy () inline
Definition at line 134 of file RigVMASTProxy.h.
References Callstack.
Referenced by FRigVMASTProxy(), GetChild(), GetParent(), GetSibling(), GetTypeHash, MakeFromCallPath(), MakeFromCallstack(), MakeFromCallstack(), MakeFromUObject(), operator!=(), operator<(), operator=(), operator==(), and operator>().
FRigVMASTProxy() [2/2]
FRigVMASTProxy::FRigVMASTProxy (const FRigVMASTProxy & InOther) inline
Definition at line 142 of file RigVMASTProxy.h.
References FRigVMASTProxy(), Callstack, and FRigVMCallstack::Stack.
Member Function Documentation
GetCallstack()
const FRigVMCallstack & FRigVMASTProxy::GetCallstack () const inline
Definition at line 205 of file RigVMASTProxy.h.
References Callstack.
Referenced by GetTypeHash, operator!=(), operator<(), operator==(), and operator>().
GetChild()
FRigVMASTProxy FRigVMASTProxy::GetChild (UObject * InSubject) const inline
Definition at line 189 of file RigVMASTProxy.h.
References FRigVMASTProxy(), and Child.
GetParent()
FRigVMASTProxy FRigVMASTProxy::GetParent () const inline
Definition at line 177 of file RigVMASTProxy.h.
References FRigVMASTProxy(), Callstack, ensure, and Parent.
GetSibling()
FRigVMASTProxy FRigVMASTProxy::GetSibling (UObject * InSubject) const inline
Definition at line 167 of file RigVMASTProxy.h.
References FRigVMASTProxy(), Callstack, FRigVMCallstack::GetCallPath(), TArray< InElementType, InAllocatorType >::Last(), and FRigVMCallstack::Stack.
GetSubject() [1/2]
UObject * FRigVMASTProxy::GetSubject () const inline
Definition at line 207 of file RigVMASTProxy.h.
References Callstack.
Referenced by GetSubjectChecked(), IsA(), and IsValid().
GetSubject() [2/2]
template<class T> T * FRigVMASTProxy::GetSubject () const inline
Definition at line 210 of file RigVMASTProxy.h.
References Cast(), and GetSubject().
Referenced by GetSubject().
GetSubjectChecked()
template<class T> T * FRigVMASTProxy::GetSubjectChecked () const inline
Definition at line 213 of file RigVMASTProxy.h.
References CastChecked(), and GetSubject().
IsA()
template<class T> bool FRigVMASTProxy::IsA () const inline
Definition at line 218 of file RigVMASTProxy.h.
References GetSubject().
IsValid()
bool FRigVMASTProxy::IsValid () const inline
Definition at line 215 of file RigVMASTProxy.h.
References Callstack, and GetSubject().
MakeFromCallPath()
FRigVMASTProxy FRigVMASTProxy::MakeFromCallPath (const FString & InCallPath, UObject * InRootObject) static
References FRigVMASTProxy().
MakeFromCallstack() [1/2]
FRigVMASTProxy FRigVMASTProxy::MakeFromCallstack (const FRigVMCallstack & InCallstack) static
References FRigVMASTProxy().
MakeFromCallstack() [2/2]
FRigVMASTProxy FRigVMASTProxy::MakeFromCallstack (const TArray< TWeakObjectPtr< UObject > > * InCallstack) static
References FRigVMASTProxy().
MakeFromUObject()
FRigVMASTProxy FRigVMASTProxy::MakeFromUObject (UObject * InSubject) static
References FRigVMASTProxy().
operator!=()
bool FRigVMASTProxy::operator!= (const FRigVMASTProxy & Other) const inline
Definition at line 230 of file RigVMASTProxy.h.
References FRigVMASTProxy(), GetCallstack(), and Other.
operator<()
bool FRigVMASTProxy::operator< (const FRigVMASTProxy & Other) const inline
Definition at line 235 of file RigVMASTProxy.h.
References FRigVMASTProxy(), GetCallstack(), and Other.
operator=()
FRigVMASTProxy & FRigVMASTProxy::operator= (const FRigVMASTProxy & InOther) inline
Definition at line 150 of file RigVMASTProxy.h.
References FRigVMASTProxy(), Callstack, and FRigVMCallstack::Stack.
operator==()
bool FRigVMASTProxy::operator== (const FRigVMASTProxy & Other) const inline
Definition at line 225 of file RigVMASTProxy.h.
References FRigVMASTProxy(), GetCallstack(), and Other.
operator>()
bool FRigVMASTProxy::operator> (const FRigVMASTProxy & Other) const inline
Definition at line 240 of file RigVMASTProxy.h.
References FRigVMASTProxy(), GetCallstack(), and Other.
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FRigVMASTProxy & Proxy) friend
Definition at line 220 of file RigVMASTProxy.h.
References FRigVMASTProxy(), GetCallstack(), and GetTypeHash().
Field Documentation
Callstack
FRigVMCallstack FRigVMASTProxy::Callstack private
Definition at line 251 of file RigVMASTProxy.h.
Referenced by FRigVMASTProxy(), FRigVMASTProxy(), GetCallstack(), GetParent(), GetSibling(), GetSubject(), IsValid(), and operator=().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/RigVM/Source/RigVMDeveloper/Public/RigVMCompiler/RigVMASTProxy.h