Unreal Engine 5.6 C++ API: FRDGUniformBufferBinding Class Reference
FRDGUniformBufferBinding Class Reference
#include "ShaderParameterMacros.h"
Public Member Functions
FRDGUniformBufferBinding ()=default
FORCEINLINE EUniformBufferBindingFlags GetBindingFlags () const
FORCEINLINE FRDGUniformBuffer * GetUniformBuffer () const
FORCEINLINE bool IsShader () const
FORCEINLINE bool IsStatic () const
FORCEINLINE operator bool () const
FORCEINLINE FRDGUniformBuffer * operator-> () const
Protected Member Functions
FRDGUniformBufferBinding (FRDGUniformBuffer *InUniformBuffer, EUniformBufferBindingFlags InBindingFlags)
Private Attributes
EUniformBufferBindingFlags BindingFlags = EUniformBufferBindingFlags::Shader
FRDGUniformBuffer * UniformBuffer = nullptr
Detailed Description
Definition at line 271 of file ShaderParameterMacros.h.
Constructor & Destructor Documentation
FRDGUniformBufferBinding() [1/2]
FRDGUniformBufferBinding::FRDGUniformBufferBinding () default
Referenced by TRDGUniformBufferBinding< UniformBufferStructType >::TRDGUniformBufferBinding(), and TRDGUniformBufferBinding< UniformBufferStructType >::TRDGUniformBufferBinding().
FRDGUniformBufferBinding() [2/2]
FRDGUniformBufferBinding::FRDGUniformBufferBinding (FRDGUniformBuffer * InUniformBuffer, EUniformBufferBindingFlags InBindingFlags) inline protected
Definition at line 307 of file ShaderParameterMacros.h.
References BindingFlags, and UniformBuffer.
Member Function Documentation
GetBindingFlags()
FORCEINLINE EUniformBufferBindingFlags FRDGUniformBufferBinding::GetBindingFlags () const inline
Definition at line 281 of file ShaderParameterMacros.h.
References BindingFlags, and FORCEINLINE.
Referenced by TRDGUniformBufferBinding< UniformBufferStructType >::TRDGUniformBufferBinding().
GetUniformBuffer()
FORCEINLINE FRDGUniformBuffer * FRDGUniformBufferBinding::GetUniformBuffer () const inline
Definition at line 276 of file ShaderParameterMacros.h.
References FORCEINLINE, and UniformBuffer.
Referenced by TRDGUniformBufferBinding< UniformBufferStructType >::GetUniformBuffer().
IsShader()
FORCEINLINE bool FRDGUniformBufferBinding::IsShader () const inline
Definition at line 291 of file ShaderParameterMacros.h.
References BindingFlags, EnumHasAnyFlags(), and FORCEINLINE.
IsStatic()
FORCEINLINE bool FRDGUniformBufferBinding::IsStatic () const inline
Definition at line 286 of file ShaderParameterMacros.h.
References BindingFlags, EnumHasAnyFlags(), and FORCEINLINE.
operator bool()
FORCEINLINE FRDGUniformBufferBinding::operator bool () const inline
Definition at line 296 of file ShaderParameterMacros.h.
References FORCEINLINE, and UniformBuffer.
operator->()
FORCEINLINE FRDGUniformBuffer * FRDGUniformBufferBinding::operator-> () const inline
Definition at line 301 of file ShaderParameterMacros.h.
References FORCEINLINE, and UniformBuffer.
Field Documentation
BindingFlags
EUniformBufferBindingFlags FRDGUniformBufferBinding::BindingFlags = EUniformBufferBindingFlags::Shader private
Definition at line 314 of file ShaderParameterMacros.h.
Referenced by FRDGUniformBufferBinding(), GetBindingFlags(), IsShader(), and IsStatic().
UniformBuffer
FRDGUniformBuffer* FRDGUniformBufferBinding::UniformBuffer = nullptr private
Definition at line 313 of file ShaderParameterMacros.h.
Referenced by FRDGUniformBufferBinding(), GetUniformBuffer(), operator bool(), and operator->().
The documentation for this class was generated from the following file:
Runtime/RenderCore/Public/ShaderParameterMacros.h