Unreal Engine 5.6 C++ API: IMultiBlockBaseWidget Class Reference
IMultiBlockBaseWidget Class Reference abstract
MultiBlock Slate widget interface.
#include "MultiBox.h"
Public Member Functions
virtual TSharedRef< const SWidget > AsWidget () const =0
Interprets this object as a SWidget.
virtual TSharedRef< SWidget > AsWidget ()=0
Interprets this object as a SWidget.
virtual void BuildMultiBlockWidget (const ISlateStyle *StyleSet, const FName &StyleName)=0
Builds this MultiBlock widget up from the MultiBlock associated with it.
virtual UE_DEPRECATED(5.6, "Use the const version of GetMultiBlockLocation") virtual EMultiBlockLocation EMultiBlockLocation::Type GetMultiBlockLocation () const =0
Returns this MultiBlocks location.
virtual bool IsInEditMode () const =0
Returns true if editing this widget.
virtual void SetMultiBlock (TSharedRef< const FMultiBlock > InMultiBlock)=0
Associates this widget with a MultiBlock.
virtual void SetMultiBlockLocation (EMultiBlockLocation::Type InLocation, bool bSectionContainsIcons)=0
Sets the blocks location relative to the other blocks.
virtual void SetOptionsBlockWidget (TSharedPtr< SWidget > InOptionsBlockWidget)=0
Adds a dropdown widget for options associated with this widget.
virtual void SetOwnerMultiBoxWidget (TSharedRef< SMultiBoxWidget > InOwnerMultiBoxWidget)=0
Associates the owner MultiBox widget with this widget.
Detailed Description
MultiBlock Slate widget interface.
Definition at line 536 of file MultiBox.h.
Member Function Documentation
AsWidget() [1/2]
virtual TSharedRef< const SWidget > IMultiBlockBaseWidget::AsWidget () const pure virtual
Interprets this object as a SWidget.
Returns
Widget reference
Implemented in SMultiBlockBaseWidget.
AsWidget() [2/2]
virtual TSharedRef< SWidget > IMultiBlockBaseWidget::AsWidget () pure virtual
Interprets this object as a SWidget.
Returns
Widget reference
Implemented in SMultiBlockBaseWidget.
BuildMultiBlockWidget()
virtual void IMultiBlockBaseWidget::BuildMultiBlockWidget (const ISlateStyle * StyleSet, const FName & StyleName) pure virtual
Builds this MultiBlock widget up from the MultiBlock associated with it.
Parameters
StyleSet The Slate style to use to build the widget
StyleName The style name to use from the StyleSet
GetMultiBlockLocation()
virtual UE_DEPRECATED(5.6, "Use the const version of GetMultiBlockLocation") virtual EMultiBlockLocation EMultiBlockLocation::Type IMultiBlockBaseWidget::GetMultiBlockLocation () const pure virtual
Returns this MultiBlocks location.
Returns this MultiBlocks location
Implemented in SMultiBlockBaseWidget.
References GetMultiBlockLocation().
Referenced by GetMultiBlockLocation(), and SetMultiBlockLocation().
IsInEditMode()
virtual bool IMultiBlockBaseWidget::IsInEditMode () const pure virtual
Returns true if editing this widget.
Implemented in SMultiBlockBaseWidget.
References IsInEditMode().
Referenced by IsInEditMode().
SetMultiBlock()
virtual void IMultiBlockBaseWidget::SetMultiBlock (TSharedRef< const FMultiBlock > InMultiBlock) pure virtual
Associates this widget with a MultiBlock.
Parameters
InMultiBlock The MultiBlock we'll be associated with
Implemented in SMultiBlockBaseWidget.
SetMultiBlockLocation()
virtual void IMultiBlockBaseWidget::SetMultiBlockLocation (EMultiBlockLocation::Type InLocation, bool bSectionContainsIcons) pure virtual
Sets the blocks location relative to the other blocks.
Parameters
InLocation The MultiBlocks location
bSectionContainsIcons Does the section contain icons?
Implemented in SMultiBlockBaseWidget.
References GetMultiBlockLocation().
SetOptionsBlockWidget()
virtual void IMultiBlockBaseWidget::SetOptionsBlockWidget (TSharedPtr< SWidget > InOptionsBlockWidget) pure virtual
Adds a dropdown widget for options associated with this widget.
The usage of this is block specific
Parameters
InOptionsBlockWidget The options block to associate with this widget
Implemented in SMultiBlockBaseWidget.
SetOwnerMultiBoxWidget()
virtual void IMultiBlockBaseWidget::SetOwnerMultiBoxWidget (TSharedRef< SMultiBoxWidget > InOwnerMultiBoxWidget) pure virtual
Associates the owner MultiBox widget with this widget.
Parameters
InOwnerMultiBoxWidget The MultiBox widget that owns us
Implemented in SMultiBlockBaseWidget.
The documentation for this class was generated from the following file:
Runtime/Slate/Public/Framework/MultiBox/MultiBox.h