Unreal Engine 5.6 C++ API: FGlobalShaderType Class Reference
FGlobalShaderType Class Reference
A shader meta type for the simplest shaders; shaders which are not material or vertex factory linked.
#include "GlobalShader.h"
Public Types
typedef FShader::CompiledShaderInitializerType CompiledShaderInitializerType
Public Types inherited from FShaderType
typedef FShader *(* ConstructCompiledType) (const FShader::CompiledShaderInitializerType &Initializer)
typedef class FShader *(* ConstructSerializedType) ()
enum class EShaderTypeForDynamicCast : uint32 {
Global , Material , MeshMaterial , Niagara ,
OCIO , ComputeKernel , NNERuntimeIREE , NumShaderTypes
}
typedef EShaderCompileJobPriority(* GetOverrideJobPriorityType) ()
typedef void(* GetPermutationIdStringType) (int32 PermutationId, FString &, bool)
typedef ERayTracingPayloadType(* GetRayTracingPayloadTypeType) (const int32 PermutationId)
typedef const FShaderBindingLayout *(* GetShaderBindingLayoutType) (const FShaderPermutationParameters &)
typedef void(* ModifyCompilationEnvironmentType) (const FShaderPermutationParameters &, FShaderCompilerEnvironment &)
typedef bool(* ShouldCompilePermutationType) (const FShaderPermutationParameters &)
typedef EShaderPermutationPrecacheRequest(* ShouldPrecachePermutationType) (const FShaderPermutationParameters &)
typedef bool(* ValidateCompiledResultType) (EShaderPlatform, const FShaderParameterMap &, TArray< FString > &)
Public Member Functions
FGlobalShaderType (FTypeLayoutDesc &InTypeLayout, const TCHAR *InName, const TCHAR *InSourceFilename, const TCHAR *InFunctionName, uint32 InFrequency, int32 InTotalPermutationCount, ConstructSerializedType InConstructSerializedRef, ConstructCompiledType InConstructCompiledRef, ShouldCompilePermutationType InShouldCompilePermutationRef, ShouldPrecachePermutationType InShouldPrecachePermutationRef, GetRayTracingPayloadTypeType InGetRayTracingPayloadTypeRef, GetShaderBindingLayoutType InGetShaderBindingLayoutTypeRef, ModifyCompilationEnvironmentType InModifyCompilationEnvironmentRef, ValidateCompiledResultType InValidateCompiledResultRef, GetOverrideJobPriorityType InGetOverrideJobPriorityRef, uint32 InTypeSize, const FShaderParametersMetadata *InRootParametersMetadata=nullptr, GetPermutationIdStringType InGetPermutationIdStringRef=nullptr)
RENDERCORE_API void SetupCompileEnvironment (EShaderPlatform Platform, int32 PermutationId, EShaderPermutationFlags Flags, FShaderCompilerEnvironment &Environment) const
Sets up the environment used to compile an instance of this shader type.
bool ShouldCompilePermutation (EShaderPlatform Platform, int32 PermutationId, EShaderPermutationFlags Flags) const
Checks if the shader type should be cached for a particular platform.
EShaderPermutationPrecacheRequest ShouldPrecachePermutation (EShaderPlatform Platform, int32 PermutationId, EShaderPermutationFlags Flags) const
Public Member Functions inherited from FShaderType
RENDERCORE_API FShaderType (EShaderTypeForDynamicCast InShaderTypeForDynamicCast, FTypeLayoutDesc &InTypeLayout, const TCHAR *InName, const TCHAR *InSourceFilename, const TCHAR *InFunctionName, uint32 InFrequency, int32 TotalPermutationCount, ConstructSerializedType InConstructSerializedRef, ConstructCompiledType InConstructCompiledRef, ShouldCompilePermutationType InShouldCompilePermutationRef, ShouldPrecachePermutationType InShouldPrecachePermutationRef, GetRayTracingPayloadTypeType InGetRayTracingPayloadTypeRef, GetShaderBindingLayoutType InGetShaderBindingLayoutTypeRef, ModifyCompilationEnvironmentType InModifyCompilationEnvironmentRef, ValidateCompiledResultType InValidateCompiledResultRef, GetOverrideJobPriorityType InGetOverrideJobPriorityRef, uint32 InTypeSize, const FShaderParametersMetadata *InRootParametersMetadata, GetPermutationIdStringType InGetPermutationIdStringRef=nullptr)
Minimal initialization constructor.
virtual RENDERCORE_API ~FShaderType ()
RENDERCORE_API void AddUniformBufferIncludesToEnvironment (FShaderCompilerEnvironment &OutEnvironment, EShaderPlatform Platform) const
Adds include statements for uniform buffers that this shader type references.
const FGlobalShaderType * AsGlobalShaderType () const
const FMaterialShaderType * AsMaterialShaderType () const
const FMeshMaterialShaderType * AsMeshMaterialShaderType () const
const FNiagaraShaderType * AsNiagaraShaderType () const
const FOpenColorIOShaderType * AsOpenColorIOShaderType () const
RENDERCORE_API FShader * ConstructCompiled (const FShader::CompiledShaderInitializerType &Initializer) const
RENDERCORE_API FShader * ConstructForDeserialization () const
Constructs a new instance of the shader type for deserialization.
RENDERCORE_API void DumpDebugInfo ()
FComputeKernelShaderType * GetComputeKernelShaderType ()
const FComputeKernelShaderType * GetComputeKernelShaderType () const
const FName & GetFName () const
EShaderFrequency GetFrequency () const
const TCHAR * GetFunctionName () const
FGlobalShaderType * GetGlobalShaderType ()
const FGlobalShaderType * GetGlobalShaderType () const
const FHashedName & GetHashedName () const
const FHashedName & GetHashedShaderFilename () const
const FTypeLayoutDesc & GetLayout () const
FMaterialShaderType * GetMaterialShaderType ()
const FMaterialShaderType * GetMaterialShaderType () const
FMeshMaterialShaderType * GetMeshMaterialShaderType ()
const FMeshMaterialShaderType * GetMeshMaterialShaderType () const
const TCHAR * GetName () const
FNiagaraShaderType * GetNiagaraShaderType ()
const FNiagaraShaderType * GetNiagaraShaderType () const
FNNERuntimeIREEShaderType * GetNNERuntimeIREEShaderType ()
const FNNERuntimeIREEShaderType * GetNNERuntimeIREEShaderType () const
int32 GetNumShaders () const
FOpenColorIOShaderType * GetOpenColorIOShaderType ()
const FOpenColorIOShaderType * GetOpenColorIOShaderType () const
RENDERCORE_API EShaderCompileJobPriority GetOverrideJobPriority () const
Returns a custom compile job priority or EShaderCompileJobPriority::None to ignore the customization.
int32 GetPermutationCount () const
RENDERCORE_API FString GetPermutationIdString (int32 PermutationId, bool bFullNames) const
Returns a string representation for the specified permutation Id.
RENDERCORE_API ERayTracingPayloadType GetRayTracingPayloadType (const int32 PermutationId) const
const TSet< const TCHAR *, TStringPointerSetKeyFuncs_DEPRECATED< const TCHAR * > > & GetReferencedUniformBufferNames () const
const TSet< const FShaderParametersMetadata * > & GetReferencedUniformBuffers () const
const FShaderParametersMetadata * GetRootParametersMetadata () const
Returns the meta data for the root shader parameter struct.
RENDERCORE_API const FShaderBindingLayout * GetShaderBindingLayout (const FShaderPermutationParameters &Parameters) const
const TCHAR * GetShaderFilename () const
RENDERCORE_API void GetShaderStableKeyParts (struct FStableShaderKeyAndValue &SaveKeyVal)
RENDERCORE_API const FSHAHash & GetSourceHash (EShaderPlatform ShaderPlatform) const
Calculates a Hash based on this shader type's source code and includes.
EShaderTypeForDynamicCast GetTypeForDynamicCast () const
uint32 GetTypeSize () const
RENDERCORE_API void ModifyCompilationEnvironment (const FShaderPermutationParameters &Parameters, FShaderCompilerEnvironment &OutEnvironment) const
RENDERCORE_API bool ShouldCompilePermutation (const FShaderPermutationParameters &Parameters) const
RENDERCORE_API EShaderPermutationPrecacheRequest ShouldPrecachePermutation (const FShaderPermutationParameters &Parameters) const
RENDERCORE_API void UpdateReferencedUniformBufferNames (const TMap< FString, TArray< const TCHAR * > > &ShaderFileToUniformBufferVariables)
RENDERCORE_API bool ValidateCompiledResult (EShaderPlatform Platform, const FShaderParameterMap &ParameterMap, TArray< FString > &OutError) const
Checks if the shader type should pass compilation for a particular set of parameters.
Static Public Member Functions
static RENDERCORE_API bool ShouldCompilePipeline (const FShaderPipelineType *ShaderPipelineType, EShaderPlatform Platform, EShaderPermutationFlags Flags)
Static Public Member Functions inherited from FShaderType
static RENDERCORE_API TMap< FHashedName, FShaderType * > & GetNameToTypeMap ()
static RENDERCORE_API FShaderType * GetShaderTypeByName (const TCHAR *Name)
static RENDERCORE_API TArray< const FShaderType * > GetShaderTypesByFilename (const TCHAR *Filename, bool bSearchAsRegexFilter=false)
static RENDERCORE_API TArray< const FShaderType * > GetShaderTypesByFilenameFilter (const TFunction< bool(const TCHAR *)> &InFilenameFilter)
static RENDERCORE_API const TArray< FShaderType * > & GetSortedTypes (EShaderTypeForDynamicCast Type)
static RENDERCORE_API TLinkedList< FShaderType * > *& GetTypeList ()
static RENDERCORE_API void Initialize (const TMap< FString, TArray< const TCHAR * > > &ShaderFileToUniformBufferVariables)
Initialize FShaderType static members, this must be called before any shader types are created.
static RENDERCORE_API void Uninitialize ()
Uninitializes FShaderType cached data.
Friends
class FGlobalShaderTypeCompiler
Additional Inherited Members
Protected Attributes inherited from FShaderType
TSet< const FShaderParametersMetadata * > ReferencedUniformBuffers
Cache of referenced uniform buffer structs.
Detailed Description
A shader meta type for the simplest shaders; shaders which are not material or vertex factory linked.
There should only a single instance of each simple shader type.
Definition at line 86 of file GlobalShader.h.
Member Typedef Documentation
CompiledShaderInitializerType
typedef FShader::CompiledShaderInitializerType FGlobalShaderType::CompiledShaderInitializerType
Definition at line 91 of file GlobalShader.h.
Constructor & Destructor Documentation
FGlobalShaderType()
FGlobalShaderType::FGlobalShaderType (FTypeLayoutDesc & InTypeLayout, const TCHAR * InName, const TCHAR * InSourceFilename, const TCHAR * InFunctionName, uint32 InFrequency, int32 InTotalPermutationCount, ConstructSerializedType InConstructSerializedRef, ConstructCompiledType InConstructCompiledRef, ShouldCompilePermutationType InShouldCompilePermutationRef, ShouldPrecachePermutationType InShouldPrecachePermutationRef, GetRayTracingPayloadTypeType InGetRayTracingPayloadTypeRef, GetShaderBindingLayoutType InGetShaderBindingLayoutTypeRef, ModifyCompilationEnvironmentType InModifyCompilationEnvironmentRef, ValidateCompiledResultType InValidateCompiledResultRef, GetOverrideJobPriorityType InGetOverrideJobPriorityRef, uint32 InTypeSize, const FShaderParametersMetadata * InRootParametersMetadata = nullptr, GetPermutationIdStringType InGetPermutationIdStringRef = nullptr) inline
Definition at line 93 of file GlobalShader.h.
References FGlobalShaderType(), and FShaderType::Global.
Referenced by FGlobalShaderType().
Member Function Documentation
SetupCompileEnvironment()
RENDERCORE_API void FGlobalShaderType::SetupCompileEnvironment (EShaderPlatform Platform, int32 PermutationId, EShaderPermutationFlags Flags, FShaderCompilerEnvironment & Environment) const
Sets up the environment used to compile an instance of this shader type.
Parameters
Platform - Platform to compile for.
Environment - The shader compile environment that the function modifies.
References Flags, and Platform.
ShouldCompilePermutation()
bool FGlobalShaderType::ShouldCompilePermutation (EShaderPlatform Platform, int32 PermutationId, EShaderPermutationFlags Flags) const inline
Checks if the shader type should be cached for a particular platform.
Parameters
Platform - The platform to check.
Returns
True if this shader type should be cached.
Definition at line 100 of file GlobalShader.h.
References Flags, FShaderType::GetFName(), Platform, and FShaderType::ShouldCompilePermutation().
ShouldCompilePipeline()
RENDERCORE_API bool FGlobalShaderType::ShouldCompilePipeline (const FShaderPipelineType * ShaderPipelineType, EShaderPlatform Platform, EShaderPermutationFlags Flags) static
References Flags, and Platform.
ShouldPrecachePermutation()
EShaderPermutationPrecacheRequest FGlobalShaderType::ShouldPrecachePermutation (EShaderPlatform Platform, int32 PermutationId, EShaderPermutationFlags Flags) const inline
Definition at line 105 of file GlobalShader.h.
References Flags, FShaderType::GetFName(), Platform, and FShaderType::ShouldPrecachePermutation().
Friends And Related Symbol Documentation
FGlobalShaderTypeCompiler
friend class FGlobalShaderTypeCompiler friend
Definition at line 88 of file GlobalShader.h.
References FGlobalShaderTypeCompiler.
Referenced by FGlobalShaderTypeCompiler.
The documentation for this class was generated from the following file:
Runtime/RenderCore/Public/GlobalShader.h