Unreal Engine 5.6 C++ API: FEditorFileUtils Class Reference
FEditorFileUtils Class Reference
This class is a wrapper for editor loading and saving functionality It is meant to contain only functions that can be executed in script (but are also allowed in C++).
#include "FileHelpers.h"
Data Structures
struct FPromptForCheckoutAndSaveParams
struct FShouldIgnorePackage
Public Types
enum EGarbageCollectionOption { GCO_SkipGarbageCollection = 0 , GCO_CollectGarbage = 1 }
Used to decide how to handle garbage collection.
enum EPromptReturnCode { PR_Success , PR_Failure , PR_Declined , PR_Cancelled }
Enum used for prompt returns.
using FShouldIgnorePackageFunctionRef = TFunctionRef<bool(UPackage*)>
Dirty Package Ignore.
Public Member Functions
DECLARE_DELEGATE (FOnLevelPickingCancelled)
DECLARE_DELEGATE_OneParam (FOnLevelsChosen, const TArray< FAssetData > &)
DECLARE_MULTICAST_DELEGATE (FOnLoadMapStart)
DECLARE_MULTICAST_DELEGATE_OneParam (FOnLoadMapEnd, const FString &Filename)
DECLARE_MULTICAST_DELEGATE_OneParam (FOnPrepareWorldsForExplicitSave, TArray< UWorld * > Worlds)
Static Public Member Functions
static UNREALED_API bool AttemptUnloadInactiveWorldPackage (UPackage *PackageToUnload, FText &OutErrorMessage)
Unloads the specified package potentially containing an inactive world.
static bool AutosaveContentPackages (const FString &AbsoluteAutosaveDir, const int32 AutosaveIndex, const bool bForceIfNotInList, const TSet< TWeakObjectPtr< UPackage >, TWeakObjectPtrSetKeyFuncs< TWeakObjectPtr< UPackage > > > &DirtyPackagesForAutoSave)
Saves all asset packages to the specified directory.
static EAutosaveContentPackagesResult::Type AutosaveContentPackagesEx (const FString &AbsoluteAutosaveDir, const int32 AutosaveIndex, const bool bForceIfNotInList, const TSet< TWeakObjectPtr< UPackage >, TWeakObjectPtrSetKeyFuncs< TWeakObjectPtr< UPackage > > > &DirtyPackagesForAutoSave)
Saves all asset packages to the specified directory.
static bool AutosaveMap (const FString &AbsoluteAutosaveDir, const int32 AutosaveIndex, const bool bForceIfNotInList, const TSet< TWeakObjectPtr< UPackage >, TWeakObjectPtrSetKeyFuncs< TWeakObjectPtr< UPackage > > > &DirtyPackagesForAutoSave)
Saves all levels to the specified directory.
static EAutosaveContentPackagesResult::Type AutosaveMapEx (const FString &AbsoluteAutosaveDir, const int32 AutosaveIndex, const bool bForceIfNotInList, const TSet< TWeakObjectPtr< UPackage >, TWeakObjectPtrSetKeyFuncs< TWeakObjectPtr< UPackage > > > &DirtyPackagesForAutoSave)
Saves all levels to the specified directory.
static UNREALED_API ECommandResult::Type CheckoutPackages (const TArray< FString > &PkgsToCheckOut, TArray< FString > *OutPackagesCheckedOut=NULL, const bool bErrorIfAlreadyCheckedOut=true)
Check out the specified packages from source control and report any errors while checking out.
static UNREALED_API ECommandResult::Type CheckoutPackages (const TArray< UPackage * > &PkgsToCheckOut, TArray< UPackage * > *OutPackagesCheckedOut=NULL, const bool bErrorIfAlreadyCheckedOut=true, const bool bConfirmPackageBranchCheckOutStatus=true)
Check out the specified packages from source control and report any errors while checking out.
static UNREALED_API void Export (bool bExportSelectedActorsOnly)
static UNREALED_API FString ExtractPackageName (const FString &ObjectPath)
Helper function used to extract the package name from the object path.
static UNREALED_API void FindAllConfigFiles (TArray< FString > &OutConfigFiles)
Looks for config files for the current project.
static UNREALED_API void FindAllPackageFiles (TArray< FString > &OutPackages)
Looks for package files in the known content paths on disk.
static UNREALED_API void FindAllSubmittableConfigFiles (TMap< FString, FSourceControlStatePtr > &OutConfigFiles)
Looks for source control submittable non-package config files for the current project.
static UNREALED_API void FindAllSubmittablePackageFiles (TMap< FString, FSourceControlStatePtr > &OutPackages, const bool bIncludeMaps)
Looks for source control submittable files in the known content paths on disk.
static UNREALED_API void FindAllSubmittableProjectFiles (TMap< FString, FSourceControlStatePtr > &OutProjectFiles)
Looks for source control submittable non-package project files for the current project.
static FString GetAutoSaveFilename (UPackage *const Package, const FString &AbsoluteAutosaveDir, const int32 AutoSaveIndex, const FString &PackageExt)
Get the autosave filename for the given package.
static UNREALED_API void GetDirtyContentPackages (TArray< UPackage * > &OutDirtyPackages, const FShouldIgnorePackageFunctionRef &ShouldIgnorePackageFunction=FShouldIgnorePackage::Default)
Appends array with all currently dirty content packages.
static UNREALED_API void GetDirtyPackages (TArray< UPackage * > &OutDirtyPackages, const FShouldIgnorePackageFunctionRef &ShouldIgnorePackageFunction=FShouldIgnorePackage::Default)
Appends array with all currently dirty packages.
static UNREALED_API void GetDirtyWorldPackages (TArray< UPackage * > &OutDirtyPackages, const FShouldIgnorePackageFunctionRef &ShouldIgnorePackageFunction=FShouldIgnorePackage::Default)
Appends array with all currently dirty world packages.
static UNREALED_API FString GetFilename (const FName &PackageName)
static UNREALED_API FString GetFilename (UObject *LevelObject)
static UNREALED_API FString GetFilterString (EFileInteraction Interaction)
Returns a file filter string appropriate for a specific file interaction.
static UNREALED_API FOnLoadMapEnd & GetOnLoadMapEndDelegate ()
static UNREALED_API FOnLoadMapStart & GetOnLoadMapStartDelegate ()
static UNREALED_API void Import ()
Presents the user with a file dialog for importing.
static UNREALED_API void Import (const FString &InFilename)
static bool IsLoadingStartupMap ()
Whether or not we're in the middle of loading the simple startup map.
static UNREALED_API bool IsMapPackageAsset (const FString &ObjectPath)
Helper function used to decide whether a package name is a map package or not.
static UNREALED_API bool IsMapPackageAsset (const FString &ObjectPath, FString &MapFilePath)
Helper function used to decide whether a package name is a map package or not.
static UNREALED_API bool IsValidMapFilename (const FString &MapFilename, FText &OutErrorMessage)
Returns true if the specified map filename is valid for loading or saving.
static UNREALED_API void LoadDefaultMapAtStartup ()
Loads a simple example map.
static UNREALED_API bool LoadMap ()
Prompts the user to save the current map if necessary, the presents a load dialog and loads a new map if selected by the user.
static UNREALED_API bool LoadMap (const FString &Filename, bool LoadAsTemplate=false, const bool bShowProgress=true)
Loads the specified map.
static UNREALED_API void OpenLevelPickingDialog (const FOnLevelsChosen &OnLevelsChosen, const FOnLevelPickingCancelled &OnLevelPickingCancelled, bool bAllowMultipleSelection)
Opens a non-modal dialog to allow the user to choose a level.
static UNREALED_API void PrepareWorldsForExplicitSave (TArray< UWorld * > Worlds)
Broadcasts the OnPrepareWorldsForExplicitSave event to allow validation and changes to worlds before they're saved.
static UNREALED_API EPromptReturnCode PromptForCheckoutAndSave (const TArray< UPackage * > &PackagesToSave, bool bCheckDirty, bool bPromptToSave, const FText &Title, const FText &Message, TArray< UPackage * > *OutFailedPackages=NULL, bool bAlreadyCheckedOut=false, bool bCanBeDeclined=true)
static UNREALED_API EPromptReturnCode PromptForCheckoutAndSave (const TArray< UPackage * > &PackagesToSave, bool bCheckDirty, bool bPromptToSave, TArray< UPackage * > *OutFailedPackages=NULL, bool bAlreadyCheckedOut=false, bool bCanBeDeclined=true)
static UNREALED_API EPromptReturnCode PromptForCheckoutAndSave (const TArray< UPackage * > &PackagesToSave, FPromptForCheckoutAndSaveParams &InOutParams)
Optionally prompts the user for which of the provided packages should be saved, and then additionally prompts the user to check-out any of the provided packages which are under source control.
static UNREALED_API bool PromptToCheckoutLevels (bool bCheckDirty, const TArray< ULevel * > &SpecificLevelsToCheckOut, TArray< UPackage * > *OutPackagesNotNeedingCheckout=NULL)
Prompt the user with a check-box dialog allowing them to check out relevant level packages from source control.
static UNREALED_API bool PromptToCheckoutLevels (bool bCheckDirty, ULevel *SpecificLevelToCheckOut)
Overloaded version of PromptToCheckOutLevels which prompts the user with a check-box dialog allowing them to check out the relevant level package if necessary.
static UNREALED_API bool PromptToCheckoutPackages (bool bCheckDirty, const TArray< UPackage * > &PackagesToCheckOut, TArray< UPackage * > *OutPackagesCheckedOutOrMadeWritable=NULL, TArray< UPackage * > *OutPackagesNotNeedingCheckout=NULL, const bool bPromptingAfterModify=false, const bool bAllowSkip=false)
Prompt the user with a check-box dialog allowing them to check out the provided packages from source control, if desired.
static void RegisterLevelFilename (UObject *Object, const FString &NewLevelFilename)
Sets the active level filename so that "Save" operates on this file and "SaveAs" must be used on others.
static void ResetLevelFilenames ()
Clears current level filename so that the user must SaveAs on next Save.
static UNREALED_API void SaveAssetsAs (const TArray< UObject * > &Assets, TArray< UObject * > &OutSavedAssets)
Does a SaveAs for the specified assets.
static UNREALED_API bool SaveCurrentLevel ()
Saves the active level, prompting the use for checkout if necessary.
static UNREALED_API bool SaveDirtyContentPackages (TArray< UClass * > &SaveContentClasses, const bool bPromptUserToSave, const bool bFastSave=false, const bool bNotifyNoPackagesSaved=false, const bool bCanBeDeclined=true)
Looks at all currently loaded packages and saves them if their "bDirty" flag is set and they include specified clasees, optionally prompting the user to select which packages to save)
static UNREALED_API bool SaveDirtyPackages (const bool bPromptUserToSave, const bool bSaveMapPackages, const bool bSaveContentPackages, const bool bFastSave=false, const bool bNotifyNoPackagesSaved=false, const bool bCanBeDeclined=true, bool *bOutPackagesNeededSaving=NULL, const FShouldIgnorePackageFunctionRef &ShouldIgnorePackageFunction=FShouldIgnorePackage::Default, bool bSkipExternalObjectSave=false)
Looks at all currently loaded packages and saves them if their "bDirty" flag is set, optionally prompting the user to select which packages to save)
static UNREALED_API bool SaveLevel (ULevel *Level, const FString &DefaultFilename=TEXT(""), FString *OutSavedFilename=nullptr)
Saves the specified level.
static UNREALED_API bool SaveLevelAs (ULevel *Level, FString *OutSavedFilename=nullptr)
Does a saveAs for the specified level.
static UNREALED_API bool SaveMap (UWorld *World, const FString &Filename)
Saves the specified map package, returning true on success.
static UNREALED_API bool SaveMapDataPackages (UWorld *World, bool bCheckDirty)
Saves packages which contain map data but are not map packages themselves.
static bool SaveWorlds (UWorld *InWorld, const FString &RootPath, const TCHAR *Prefix, TArray< FString > &OutFilenames)
Save all packages corresponding to the specified world, with the option to override their path and also apply a prefix.
static bool ShouldSkipExternalObjectSave ()
Whether or not saving the map package should save the external objects packages.
Static Public Attributes
static UNREALED_API FOnPrepareWorldsForExplicitSave OnPrepareWorldsForExplicitSave
Static Private Member Functions
static bool AddCheckoutPackageItems (bool bCheckDirty, const TArray< UPackage * > &PackagesToCheckOut, const TSet< FName > &ReadOnlyPackages, TArray< UPackage * > *OutPackagesNotNeedingCheckout, bool *bOutHavePackageToCheckOut)
Private method used to build a list of items requiring checkout.
static bool AutomaticCheckoutOrPromptToRevertPackages (const TArray< UPackage * > &PackagesToCheckOut, TArray< UPackage * > *OutPackagesCheckedOutOrMadeWritable, TArray< UPackage * > *OutPackagesNotNeedingCheckout, TArray< UPackage * > *OutPackagesToRevert)
Tries to checkout packages without prompting and only prompts (for revert) if that fails.
static void MakePackagesWritable (const TArray< UPackage * > &PackagesToMakeWritable, TArray< UPackage * > *OutPackagesMadeWritable, TArray< UPackage * > *OutPackagesMadeWritableFailed)
Tries to make the given packages writable.
static bool PromptToCheckoutPackagesInternal (bool bCheckDirty, const TArray< UPackage * > &PackagesToCheckOut, TArray< UPackage * > *OutPackagesCheckedOutOrMadeWritable, TArray< UPackage * > *OutPackagesNotNeedingCheckout, const bool bPromptingAfterModify, const bool bAllowSkip)
Prompts for package checkout without reentrance check.
static void UpdateCheckoutPackageItems (bool bCheckDirty, TArray< UPackage * > PackagesToCheckOut, TSet< FName > ReadOnlyPackages, TArray< UPackage * > *OutPackagesNotNeedingCheckout)
Callback from PackagesDialog used to update the list of items when the source control state changes.
Static Private Attributes
static bool bIsLoadingDefaultStartupMap
static bool bIsPromptingForCheckoutAndSave
Flag used to determine if the checkout and save prompt is already open to prevent re-entrance.
static bool bSkipExternalObjectSave
Flag used in SaveMap to skip saving external objects and only save the map.
static FOnLoadMapEnd OnLoadMapEnd
static FOnLoadMapStart OnLoadMapStart
static TSet< FString > PackagesNotSavedDuringSaveAll
static TSet< FString > PackagesNotToPromptAnyMore
Detailed Description
This class is a wrapper for editor loading and saving functionality It is meant to contain only functions that can be executed in script (but are also allowed in C++).
It is separated from FEditorFileUtils to ensure new easier to use methods can be created without breaking FEditorFileUtils backwards compatibility However this should be used in place of FEditorFileUtils wherever possible as the goal is to deprecate FEditorFileUtils eventually For saving map files through the main editor frame.
Definition at line 183 of file FileHelpers.h.
Member Typedef Documentation
FShouldIgnorePackageFunctionRef
using FEditorFileUtils::FShouldIgnorePackageFunctionRef = TFunctionRef<bool(UPackage*)>
Dirty Package Ignore.
Definition at line 187 of file FileHelpers.h.
Member Enumeration Documentation
EGarbageCollectionOption
enum FEditorFileUtils::EGarbageCollectionOption
Used to decide how to handle garbage collection.
Enumerator
GCO_SkipGarbageCollection
GCO_CollectGarbage
Definition at line 195 of file FileHelpers.h.
EPromptReturnCode
enum FEditorFileUtils::EPromptReturnCode
Enum used for prompt returns.
Enumerator
PR_Success
PR_Failure
The user has answered in the affirmative to all prompts, and execution succeeded.
PR_Declined
The user has answered in the affirmative to prompts, but an operation(s) has failed during execution.
PR_Cancelled
The user has declined out of the prompt; the caller should continue whatever it was doing.
The user has cancelled out of a prompt; the caller should abort whatever it was doing
Definition at line 443 of file FileHelpers.h.
Member Function Documentation
AddCheckoutPackageItems()
bool FEditorFileUtils::AddCheckoutPackageItems (bool bCheckDirty, const TArray< UPackage * > & PackagesToCheckOut, const TSet< FName > & ReadOnlyPackages, TArray< UPackage * > * OutPackagesNotNeedingCheckout, bool * bOutHavePackageToCheckOut) static private
Private method used to build a list of items requiring checkout.
AttemptUnloadInactiveWorldPackage()
UNREALED_API bool FEditorFileUtils::AttemptUnloadInactiveWorldPackage (UPackage * PackageToUnload, FText & OutErrorMessage) static
Unloads the specified package potentially containing an inactive world.
When returning false, OutErrorMessage is supplied with a display string describing the reason why the world could not be unloaded.
AutomaticCheckoutOrPromptToRevertPackages()
bool FEditorFileUtils::AutomaticCheckoutOrPromptToRevertPackages (const TArray< UPackage * > & PackagesToCheckOut, TArray< UPackage * > * OutPackagesCheckedOutOrMadeWritable, TArray< UPackage * > * OutPackagesNotNeedingCheckout, TArray< UPackage * > * OutPackagesToRevert) static private
Tries to checkout packages without prompting and only prompts (for revert) if that fails.
AutosaveContentPackages()
bool FEditorFileUtils::AutosaveContentPackages (const FString & AbsoluteAutosaveDir, const int32 AutosaveIndex, const bool bForceIfNotInList, const TSet< TWeakObjectPtr< UPackage >, TWeakObjectPtrSetKeyFuncs< TWeakObjectPtr< UPackage > > > & DirtyPackagesForAutoSave) static
Saves all asset packages to the specified directory.
Parameters
AbsoluteAutosaveDir Autosave directory.
AutosaveIndex Integer prepended to autosave filenames.
bForceIfNotInList Should the save be forced if the package is dirty, but not in DirtyPackagesForAutoSave?
DirtyPackagesForAutoSave A set of packages that are considered by the auto-save system to be dirty, you should check this to see if a package needs saving
Returns
true if one or more packages were autosaved; false otherwise
AutosaveContentPackagesEx()
EAutosaveContentPackagesResult::Type FEditorFileUtils::AutosaveContentPackagesEx (const FString & AbsoluteAutosaveDir, const int32 AutosaveIndex, const bool bForceIfNotInList, const TSet< TWeakObjectPtr< UPackage >, TWeakObjectPtrSetKeyFuncs< TWeakObjectPtr< UPackage > > > & DirtyPackagesForAutoSave) static
Saves all asset packages to the specified directory.
Parameters
AbsoluteAutosaveDir Autosave directory.
AutosaveIndex Integer prepended to autosave filenames.
bForceIfNotInList Should the save be forced if the package is dirty, but not in DirtyPackagesForAutoSave?
DirtyPackagesForAutoSave A set of packages that are considered by the auto-save system to be dirty, you should check this to see if a package needs saving
Returns
Success if saved at least one faile. NothingToDo if there was nothing to save. Failure on at least one auto-save failure.
AutosaveMap()
bool FEditorFileUtils::AutosaveMap (const FString & AbsoluteAutosaveDir, const int32 AutosaveIndex, const bool bForceIfNotInList, const TSet< TWeakObjectPtr< UPackage >, TWeakObjectPtrSetKeyFuncs< TWeakObjectPtr< UPackage > > > & DirtyPackagesForAutoSave) static
Saves all levels to the specified directory.
Parameters
AbsoluteAutosaveDir Autosave directory.
AutosaveIndex Integer prepended to autosave filenames..
bForceIfNotInList Should the save be forced if the package is dirty, but not in DirtyPackagesForAutoSave?
DirtyPackagesForAutoSave A set of packages that are considered by the auto-save system to be dirty, you should check this to see if a package needs saving
AutosaveMapEx()
EAutosaveContentPackagesResult::Type FEditorFileUtils::AutosaveMapEx (const FString & AbsoluteAutosaveDir, const int32 AutosaveIndex, const bool bForceIfNotInList, const TSet< TWeakObjectPtr< UPackage >, TWeakObjectPtrSetKeyFuncs< TWeakObjectPtr< UPackage > > > & DirtyPackagesForAutoSave) static
Saves all levels to the specified directory.
Parameters
AbsoluteAutosaveDir Autosave directory.
AutosaveIndex Integer prepended to autosave filenames..
bForceIfNotInList Should the save be forced if the package is dirty, but not in DirtyPackagesForAutoSave?
DirtyPackagesForAutoSave A set of packages that are considered by the auto-save system to be dirty, you should check this to see if a package needs saving
CheckoutPackages() [1/2]
UNREALED_API ECommandResult::Type FEditorFileUtils::CheckoutPackages (const TArray< FString > & PkgsToCheckOut, TArray< FString > * OutPackagesCheckedOut = NULL, const bool bErrorIfAlreadyCheckedOut = true) static
Check out the specified packages from source control and report any errors while checking out.
Parameters
PkgsToCheckOut Reference to array of package names to check out
OutPackagesCheckedOut If not NULL, this array will be populated with packages that were checked out.
bErrorIfAlreadyCheckedOut true to consider being unable to checkout a package because it is already checked out an error, false to allow this without error
Returns
the result of the check out operation
CheckoutPackages() [2/2]
UNREALED_API ECommandResult::Type FEditorFileUtils::CheckoutPackages (const TArray< UPackage * > & PkgsToCheckOut, TArray< UPackage * > * OutPackagesCheckedOut = NULL, const bool bErrorIfAlreadyCheckedOut = true, const bool bConfirmPackageBranchCheckOutStatus = true) static
Check out the specified packages from source control and report any errors while checking out.
Parameters
PkgsToCheckOut Reference to array of packages to check out
OutPackagesCheckedOut If not NULL, this array will be populated with packages that were checked out.
bErrorIfAlreadyCheckedOut true to consider being unable to checkout a package because it is already checked out an error, false to allow this without error
bConfirmPackageBranchCheckOutStatus true to prompt user on whether a package that is checked out or modified in another branch should be checked out, false to silently attempt check out.
Returns
true if all the packages were checked out successfully
DECLARE_DELEGATE()
FEditorFileUtils::DECLARE_DELEGATE (FOnLevelPickingCancelled)
DECLARE_DELEGATE_OneParam()
FEditorFileUtils::DECLARE_DELEGATE_OneParam (FOnLevelsChosen , const TArray< FAssetData > &)
DECLARE_MULTICAST_DELEGATE()
FEditorFileUtils::DECLARE_MULTICAST_DELEGATE (FOnLoadMapStart)
DECLARE_MULTICAST_DELEGATE_OneParam() [1/2]
FEditorFileUtils::DECLARE_MULTICAST_DELEGATE_OneParam (FOnLoadMapEnd , const FString & Filename)
References Filename.
DECLARE_MULTICAST_DELEGATE_OneParam() [2/2]
FEditorFileUtils::DECLARE_MULTICAST_DELEGATE_OneParam (FOnPrepareWorldsForExplicitSave , TArray< UWorld * > Worlds)
Export()
UNREALED_API void FEditorFileUtils::Export (bool bExportSelectedActorsOnly) static
ExtractPackageName()
UNREALED_API FString FEditorFileUtils::ExtractPackageName (const FString & ObjectPath) static
Helper function used to extract the package name from the object path.
Parameters
ObjectPath The path to the package to test
Returns
The package name from the string
FindAllConfigFiles()
UNREALED_API void FEditorFileUtils::FindAllConfigFiles (TArray< FString > & OutConfigFiles) static
Looks for config files for the current project.
Parameters
OutConfigFiles All found config filenames.
FindAllPackageFiles()
UNREALED_API void FEditorFileUtils::FindAllPackageFiles (TArray< FString > & OutPackages) static
Looks for package files in the known content paths on disk.
Parameters
OutPackages All found package filenames.
Referenced by DoActionToAllPackages().
FindAllSubmittableConfigFiles()
UNREALED_API void FEditorFileUtils::FindAllSubmittableConfigFiles (TMap< FString, FSourceControlStatePtr > & OutConfigFiles) static
Looks for source control submittable non-package config files for the current project.
Parameters
OutConfigFiles All found config filenames and their source control state.
FindAllSubmittablePackageFiles()
UNREALED_API void FEditorFileUtils::FindAllSubmittablePackageFiles (TMap< FString, FSourceControlStatePtr > & OutPackages, const bool bIncludeMaps) static
Looks for source control submittable files in the known content paths on disk.
Parameters
OutPackages All found package filenames and their source control state
bIncludeMaps If true, also adds maps to the list
FindAllSubmittableProjectFiles()
UNREALED_API void FEditorFileUtils::FindAllSubmittableProjectFiles (TMap< FString, FSourceControlStatePtr > & OutProjectFiles) static
Looks for source control submittable non-package project files for the current project.
Parameters
OutProjectFiles All found project filenames and their source control state.
GetAutoSaveFilename()
FString FEditorFileUtils::GetAutoSaveFilename (UPackage *const Package, const FString & AbsoluteAutosaveDir, const int32 AutoSaveIndex, const FString & PackageExt) static
Get the autosave filename for the given package.
Parameters
Package Package to get the autosave filename for.
AbsoluteAutosaveDir Autosave directory.
AutosaveIndex Integer prepended to autosave filenames.
PackageExt Extension to use for the given package. Note: This must include the dot.
References Package.
GetDirtyContentPackages()
UNREALED_API void FEditorFileUtils::GetDirtyContentPackages (TArray< UPackage * > & OutDirtyPackages, const FShouldIgnorePackageFunctionRef & ShouldIgnorePackageFunction = FShouldIgnorePackage::Default) static
Appends array with all currently dirty content packages.
Parameters
OutDirtyPackages Array to append dirty packages to.
References FEditorFileUtils::FShouldIgnorePackage::Default().
GetDirtyPackages()
UNREALED_API void FEditorFileUtils::GetDirtyPackages (TArray< UPackage * > & OutDirtyPackages, const FShouldIgnorePackageFunctionRef & ShouldIgnorePackageFunction = FShouldIgnorePackage::Default) static
Appends array with all currently dirty packages.
Parameters
OutDirtyPackages Array to append dirty packages to.
FilterFunction Allows filtering out some dirty packages.
References FEditorFileUtils::FShouldIgnorePackage::Default().
GetDirtyWorldPackages()
UNREALED_API void FEditorFileUtils::GetDirtyWorldPackages (TArray< UPackage * > & OutDirtyPackages, const FShouldIgnorePackageFunctionRef & ShouldIgnorePackageFunction = FShouldIgnorePackage::Default) static
Appends array with all currently dirty world packages.
Parameters
OutDirtyPackages Array to append dirty packages to.
References FEditorFileUtils::FShouldIgnorePackage::Default().
GetFilename() [1/2]
UNREALED_API FString FEditorFileUtils::GetFilename (const FName & PackageName) static
References PackageName.
GetFilename() [2/2]
UNREALED_API FString FEditorFileUtils::GetFilename (UObject * LevelObject) static
GetFilterString()
UNREALED_API FString FEditorFileUtils::GetFilterString (EFileInteraction Interaction) static
Returns a file filter string appropriate for a specific file interaction.
Parameters
Interaction A file interaction to get a filter string for.
Returns
A filter string.
GetOnLoadMapEndDelegate()
UNREALED_API FOnLoadMapEnd & FEditorFileUtils::GetOnLoadMapEndDelegate () static
GetOnLoadMapStartDelegate()
UNREALED_API FOnLoadMapStart & FEditorFileUtils::GetOnLoadMapStartDelegate () static
Import() [1/2]
UNREALED_API void FEditorFileUtils::Import () static
Presents the user with a file dialog for importing.
If the import is not a merge (bMerging is false), AskSaveChanges() is called first.
Import() [2/2]
UNREALED_API void FEditorFileUtils::Import (const FString & InFilename) static
IsLoadingStartupMap()
bool FEditorFileUtils::IsLoadingStartupMap () inline static
Whether or not we're in the middle of loading the simple startup map.
Definition at line 593 of file FileHelpers.h.
References bIsLoadingDefaultStartupMap.
IsMapPackageAsset() [1/2]
UNREALED_API bool FEditorFileUtils::IsMapPackageAsset (const FString & ObjectPath) static
Helper function used to decide whether a package name is a map package or not.
Map packages aren't added to the additional package list.
Parameters
ObjectPath The path to the package to test
Returns
True if package is a map
IsMapPackageAsset() [2/2]
UNREALED_API bool FEditorFileUtils::IsMapPackageAsset (const FString & ObjectPath, FString & MapFilePath) static
Helper function used to decide whether a package name is a map package or not.
Map packages aren't added to the additional package list.
Parameters
ObjectPath The path to the package to test
MapFilePath OUT parameter that returns the map file path if it exists.
Returns
True if package is a map
IsValidMapFilename()
UNREALED_API bool FEditorFileUtils::IsValidMapFilename (const FString & MapFilename, FText & OutErrorMessage) static
Returns true if the specified map filename is valid for loading or saving.
When returning false, OutErrorMessage is supplied with a display string describing the reason why the map name is invalid.
LoadDefaultMapAtStartup()
UNREALED_API void FEditorFileUtils::LoadDefaultMapAtStartup () static
Loads a simple example map.
LoadMap() [1/2]
UNREALED_API bool FEditorFileUtils::LoadMap () static
Prompts the user to save the current map if necessary, the presents a load dialog and loads a new map if selected by the user.
LoadMap() [2/2]
UNREALED_API bool FEditorFileUtils::LoadMap (const FString & Filename, bool LoadAsTemplate = false, const bool bShowProgress = true) static
Loads the specified map.
Does not prompt the user to save the current map.
Parameters
Filename Map package filename, including path.
LoadAsTemplate Forces the map to load into an untitled outermost package preventing the map saving over the original file.
bShowProgress Whether to show a progress dialog as the map loads\
Returns
true on success, false otherwise
References Filename.
MakePackagesWritable()
void FEditorFileUtils::MakePackagesWritable (const TArray< UPackage * > & PackagesToMakeWritable, TArray< UPackage * > * OutPackagesMadeWritable, TArray< UPackage * > * OutPackagesMadeWritableFailed) static private
Tries to make the given packages writable.
OpenLevelPickingDialog()
UNREALED_API void FEditorFileUtils::OpenLevelPickingDialog (const FOnLevelsChosen & OnLevelsChosen, const FOnLevelPickingCancelled & OnLevelPickingCancelled, bool bAllowMultipleSelection) static
Opens a non-modal dialog to allow the user to choose a level.
Parameters
OnLevelsChosen Delegate executed when one more more levels have been selected
OnLevelPickingDialogClosed Delegate executed when the level picking dialog is closed
bAllowMultipleSelection If true, more than one level can be chosen
PrepareWorldsForExplicitSave()
UNREALED_API void FEditorFileUtils::PrepareWorldsForExplicitSave (TArray< UWorld * > Worlds) static
Broadcasts the OnPrepareWorldsForExplicitSave event to allow validation and changes to worlds before they're saved.
Used for Editor triggered explicit saves caused by user input such as ctrl+s, or clicking the save button. Changes to worlds include dirtying the world itself or affecting its ExternalActors through Adds/Removes/Edits.
Parameters
Worlds A list of the worlds that will be broadcasted.
PromptForCheckoutAndSave() [1/3]
UNREALED_API EPromptReturnCode FEditorFileUtils::PromptForCheckoutAndSave (const TArray< UPackage * > & PackagesToSave, bool bCheckDirty, bool bPromptToSave, const FText & Title, const FText & Message, TArray< UPackage * > * OutFailedPackages = NULL, bool bAlreadyCheckedOut = false, bool bCanBeDeclined = true) static
References Title.
PromptForCheckoutAndSave() [2/3]
UNREALED_API EPromptReturnCode FEditorFileUtils::PromptForCheckoutAndSave (const TArray< UPackage * > & PackagesToSave, bool bCheckDirty, bool bPromptToSave, TArray< UPackage * > * OutFailedPackages = NULL, bool bAlreadyCheckedOut = false, bool bCanBeDeclined = true) static
PromptForCheckoutAndSave() [3/3]
UNREALED_API EPromptReturnCode FEditorFileUtils::PromptForCheckoutAndSave (const TArray< UPackage * > & PackagesToSave, FPromptForCheckoutAndSaveParams & InOutParams) static
Optionally prompts the user for which of the provided packages should be saved, and then additionally prompts the user to check-out any of the provided packages which are under source control.
If the user cancels their way out of either dialog, no packages are saved. It is possible the user will be prompted again, if the saving process fails for any reason. In that case, the user will be prompted on a package-by-package basis, allowing them to retry saving, skip trying to save the current package, or to again cancel out of the entire dialog. If the user skips saving a package that failed to save, the package will be added to the optional OutFailedPackages array, and execution will continue. After all packages are saved (or not), the user is provided with a warning about any packages that were writable on disk but not in source control, as well as a warning about which packages failed to save.
Parameters
PackagesToSave The list of packages to save. Both map and content packages are supported
bCheckDirty If true, only packages that are dirty in PackagesToSave will be saved
bPromptToSave If true the user will be prompted with a list of packages to save, otherwise all passed in packages are saved
Title If bPromptToSave true provides a dialog title
Message If bPromptToSave true provides a dialog message
OutFailedPackages [out] If specified, will be filled in with all of the packages that failed to save successfully
bAlreadyCheckedOut If true, the user will not be prompted with the source control dialog
bCanBeDeclined If true, offer a "Don't Save" option in addition to "Cancel", which will not result in a cancellation return code.
Returns
An enum value signifying success, failure, user declined, or cancellation. If any packages at all failed to save during execution, the return code will be failure, even if other packages successfully saved. If the user cancels at any point during any prompt, the return code will be cancellation, even though it is possible some packages have been successfully saved (if the cancel comes on a later package that can't be saved for some reason). If the user opts the "Don't Save" option on the dialog, the return code will indicate the user has declined out of the prompt. This way calling code can distinguish between a decline and a cancel and then proceed as planned, or abort its operation accordingly.
PromptToCheckoutLevels() [1/2]
UNREALED_API bool FEditorFileUtils::PromptToCheckoutLevels (bool bCheckDirty, const TArray< ULevel * > & SpecificLevelsToCheckOut, TArray< UPackage * > * OutPackagesNotNeedingCheckout = NULL) static
Prompt the user with a check-box dialog allowing them to check out relevant level packages from source control.
Parameters
bCheckDirty If true, non-dirty packages won't be added to the dialog
SpecificLevelsToCheckOut If specified, only the provided levels' packages will display in the dialog if they are under source control; If nothing is specified, all levels referenced by GWorld whose packages are under source control will be displayed
OutPackagesNotNeedingCheckout If not null, this array will be populated with packages that the user was not prompted about and do not need to be checked out to save. Useful for saving packages even if the user canceled the checkout dialog.
Returns
true if the user did not cancel out of the dialog and has potentially checked out some files (or if there is no source control integration); false if the user cancelled the dialog
PromptToCheckoutLevels() [2/2]
UNREALED_API bool FEditorFileUtils::PromptToCheckoutLevels (bool bCheckDirty, ULevel * SpecificLevelToCheckOut) static
Overloaded version of PromptToCheckOutLevels which prompts the user with a check-box dialog allowing them to check out the relevant level package if necessary.
Parameters
bCheckDirty If true, non-dirty packages won't be added to the dialog
SpecificLevelToCheckOut The level whose package will display in the dialog if it is under source control
Returns
true if the user did not cancel out of the dialog and has potentially checked out some files (or if there is no source control integration); false if the user cancelled the dialog
PromptToCheckoutPackages()
UNREALED_API bool FEditorFileUtils::PromptToCheckoutPackages (bool bCheckDirty, const TArray< UPackage * > & PackagesToCheckOut, TArray< UPackage * > * OutPackagesCheckedOutOrMadeWritable = NULL, TArray< UPackage * > * OutPackagesNotNeedingCheckout = NULL, const bool bPromptingAfterModify = false, const bool bAllowSkip = false) static
Prompt the user with a check-box dialog allowing them to check out the provided packages from source control, if desired.
Parameters
bCheckDirty If true, non-dirty packages won't be added to the dialog
PackagesToCheckOut Reference to array of packages to prompt the user with for possible check out
OutPackagesCheckedOutOrMadeWritable If not NULL, this array will be populated with packages that the user selected to check out or make writable.
OutPackagesNotNeedingCheckout If not NULL, this array will be populated with packages that the user was not prompted about and do not need to be checked out to save. Useful for saving packages even if the user canceled the checkout dialog.
bPromptingAfterModify If true, we are prompting the user after an object has been modified, which changes the cancel button to "Ask me later".
bAllowSkip If true, user can skip the checkout / make writable.
Returns
true if the user did not cancel out of the dialog and has potentially checked out some files (or if there is no source control integration); false if the user cancelled the dialog
PromptToCheckoutPackagesInternal()
bool FEditorFileUtils::PromptToCheckoutPackagesInternal (bool bCheckDirty, const TArray< UPackage * > & PackagesToCheckOut, TArray< UPackage * > * OutPackagesCheckedOutOrMadeWritable, TArray< UPackage * > * OutPackagesNotNeedingCheckout, const bool bPromptingAfterModify, const bool bAllowSkip) static private
Prompts for package checkout without reentrance check.
RegisterLevelFilename()
void FEditorFileUtils::RegisterLevelFilename (UObject * Object, const FString & NewLevelFilename) static
Sets the active level filename so that "Save" operates on this file and "SaveAs" must be used on others.
References Object.
ResetLevelFilenames()
void FEditorFileUtils::ResetLevelFilenames () static
Clears current level filename so that the user must SaveAs on next Save.
Called by NewMap() after the contents of the map are cleared. Also called after loading a map template so that the template isn't overwritten.
SaveAssetsAs()
UNREALED_API void FEditorFileUtils::SaveAssetsAs (const TArray< UObject * > & Assets, TArray< UObject * > & OutSavedAssets) static
Does a SaveAs for the specified assets.
Parameters
Assets The collection of assets to save.
SavedAssets The collection of corresponding saved assets (contains original asset if not resaved).
SaveCurrentLevel()
UNREALED_API bool FEditorFileUtils::SaveCurrentLevel () static
Saves the active level, prompting the use for checkout if necessary.
Returns
true on success, False on fail
SaveDirtyContentPackages()
UNREALED_API bool FEditorFileUtils::SaveDirtyContentPackages (TArray< UClass * > & SaveContentClasses, const bool bPromptUserToSave, const bool bFastSave = false, const bool bNotifyNoPackagesSaved = false, const bool bCanBeDeclined = true) static
Looks at all currently loaded packages and saves them if their "bDirty" flag is set and they include specified clasees, optionally prompting the user to select which packages to save)
Parameters
SaveContentClasses save only specified classes or children classes
bPromptUserToSave true if we should prompt the user to save dirty packages we found. false to assume all dirty packages should be saved. Regardless of this setting the user will be prompted for checkout(if needed) unless bFastSave is set
bFastSave true if we should do a fast save. (I.E dont prompt the user to save, dont prompt for checkout, and only save packages that are currently writable). Note: Still prompts for SaveAs if a package needs a filename
bNotifyNoPackagesSaved true if a notification should be displayed when no packages need to be saved.
bCanBeDeclined true if the user prompt should contain a "Don't Save" button in addition to "Cancel", which won't result in a failure return code.
Returns
true on success, false on fail.
SaveDirtyPackages()
UNREALED_API bool FEditorFileUtils::SaveDirtyPackages (const bool bPromptUserToSave, const bool bSaveMapPackages, const bool bSaveContentPackages, const bool bFastSave = false, const bool bNotifyNoPackagesSaved = false, const bool bCanBeDeclined = true, bool * bOutPackagesNeededSaving = NULL, const FShouldIgnorePackageFunctionRef & ShouldIgnorePackageFunction = FShouldIgnorePackage::Default, bool bSkipExternalObjectSave = false) static
Looks at all currently loaded packages and saves them if their "bDirty" flag is set, optionally prompting the user to select which packages to save)
Parameters
bPromptUserToSave true if we should prompt the user to save dirty packages we found. false to assume all dirty packages should be saved. Regardless of this setting the user will be prompted for checkout(if needed) unless bFastSave is set
bSaveMapPackages true if map packages should be saved
bSaveContentPackages true if we should save content packages.
bFastSave true if we should do a fast save. (I.E dont prompt the user to save, dont prompt for checkout, and only save packages that are currently writable). Note: Still prompts for SaveAs if a package needs a filename
bNotifyNoPackagesSaved true if a notification should be displayed when no packages need to be saved.
bCanBeDeclined true if the user prompt should contain a "Don't Save" button in addition to "Cancel", which won't result in a failure return code.
bOutPackagesNeededSaving when not NULL, will be set to true if there was any work to be done, and false otherwise.
ShouldIgnorePackageFunction callback that allows filtering if package should be saved or not.
bSkipExternalObjectSave true if saved package should skip saving their own external packages.
Returns
true on success, false on fail.
References bSkipExternalObjectSave, and FEditorFileUtils::FShouldIgnorePackage::Default().
SaveLevel()
UNREALED_API bool FEditorFileUtils::SaveLevel (ULevel * Level, const FString & DefaultFilename = TEXT(""), FString * OutSavedFilename = nullptr) static
Saves the specified level.
SaveAs is performed as necessary.
Parameters
Level The level to be saved.
DefaultFilename File name to use for this level if it doesn't have one yet (or empty string to prompt)
OutSavedFilename When returning true, this string will be set to the filename of the saved level.
Returns
true if the level was saved.
SaveLevelAs()
UNREALED_API bool FEditorFileUtils::SaveLevelAs (ULevel * Level, FString * OutSavedFilename = nullptr) static
Does a saveAs for the specified level.
Parameters
Level The Level to be SaveAs'd.
OutSavedFilename When returning true, this string will be set to the filename of the saved level.
Returns
true if the world was saved.
SaveMap()
UNREALED_API bool FEditorFileUtils::SaveMap (UWorld * World, const FString & Filename) static
Saves the specified map package, returning true on success.
Parameters
World The world to save.
Filename Map package filename, including path.
Returns
true if the map was saved successfully.
References Filename.
SaveMapDataPackages()
UNREALED_API bool FEditorFileUtils::SaveMapDataPackages (UWorld * World, bool bCheckDirty) static
Saves packages which contain map data but are not map packages themselves.
Parameters
World The world map data packages to be saved.
bCheckDirty If true, only packages that are dirty will be saved.
Returns
true if the data packages were saved.
SaveWorlds()
bool FEditorFileUtils::SaveWorlds (UWorld * InWorld, const FString & RootPath, const TCHAR * Prefix, TArray< FString > & OutFilenames) static
Save all packages corresponding to the specified world, with the option to override their path and also apply a prefix.
Parameters
InWorld The world to save (including its children)
RootPath Root Path override, replaces /Game/ in original name
Prefix Optional prefix for base filename, can be NULL
OutFilenames The file names of all successfully saved worlds will be added to this
Returns
true if at least one level was saved. If bPIESaving, will be true is ALL worlds were saved.
ShouldSkipExternalObjectSave()
bool FEditorFileUtils::ShouldSkipExternalObjectSave () inline static
Whether or not saving the map package should save the external objects packages.
Definition at line 596 of file FileHelpers.h.
References bSkipExternalObjectSave.
UpdateCheckoutPackageItems()
void FEditorFileUtils::UpdateCheckoutPackageItems (bool bCheckDirty, TArray< UPackage * > PackagesToCheckOut, TSet< FName > ReadOnlyPackages, TArray< UPackage * > * OutPackagesNotNeedingCheckout) static private
Callback from PackagesDialog used to update the list of items when the source control state changes.
Field Documentation
bIsLoadingDefaultStartupMap
bool FEditorFileUtils::bIsLoadingDefaultStartupMap static private
Definition at line 691 of file FileHelpers.h.
Referenced by IsLoadingStartupMap().
bIsPromptingForCheckoutAndSave
bool FEditorFileUtils::bIsPromptingForCheckoutAndSave static private
Flag used to determine if the checkout and save prompt is already open to prevent re-entrance.
Definition at line 694 of file FileHelpers.h.
bSkipExternalObjectSave
bool FEditorFileUtils::bSkipExternalObjectSave static private
Flag used in SaveMap to skip saving external objects and only save the map.
Definition at line 697 of file FileHelpers.h.
Referenced by SaveDirtyPackages(), and ShouldSkipExternalObjectSave().
OnLoadMapEnd
FOnLoadMapEnd FEditorFileUtils::OnLoadMapEnd static private
Definition at line 706 of file FileHelpers.h.
OnLoadMapStart
FOnLoadMapStart FEditorFileUtils::OnLoadMapStart static private
Definition at line 705 of file FileHelpers.h.
OnPrepareWorldsForExplicitSave
UNREALED_API FOnPrepareWorldsForExplicitSave FEditorFileUtils::OnPrepareWorldsForExplicitSave static
Definition at line 422 of file FileHelpers.h.
PackagesNotSavedDuringSaveAll
TSet<FString> FEditorFileUtils::PackagesNotSavedDuringSaveAll static private
Definition at line 700 of file FileHelpers.h.
PackagesNotToPromptAnyMore
TSet<FString> FEditorFileUtils::PackagesNotToPromptAnyMore static private
Definition at line 703 of file FileHelpers.h.
The documentation for this class was generated from the following file:
Editor/UnrealEd/Public/FileHelpers.h