Unreal Engine 5.6 C++ API: UE::GC::FPropertyStack Class Reference
UE::GC::FPropertyStack Class Reference
Helps generate debug property paths for GC schemas and to resolve them back to FProperties.
#include "GarbageCollectionSchema.h"
Public Member Functions
FPropertyStack ()=default
~FPropertyStack ()
FString GetPropertyPath () const
Get string representing property stack, e.g.
UE_NONCOPYABLE (FPropertyStack)
Static Public Member Functions
static bool ConvertPathToProperties (UClass *ObjectClass, FName InPropertyPath, TArray< FProperty * > &OutProperties)
Converts a property path constructed with GetPropertyPath() to an array of properties (from the outermost to the innermost) *.
Private Attributes
TArray< const FProperty * > Props
Friends
class FPropertyStackScope
Detailed Description
Helps generate debug property paths for GC schemas and to resolve them back to FProperties.
Definition at line 61 of file GarbageCollectionSchema.h.
Constructor & Destructor Documentation
FPropertyStack()
UE::GC::FPropertyStack::FPropertyStack () default
Referenced by UE_NONCOPYABLE().
~FPropertyStack()
UE::GC::FPropertyStack::~FPropertyStack () inline
Definition at line 66 of file GarbageCollectionSchema.h.
References check, and Props.
Member Function Documentation
ConvertPathToProperties()
bool UE::GC::FPropertyStack::ConvertPathToProperties (UClass * ObjectClass, FName InPropertyPath, TArray< FProperty * > & OutProperties) static
Converts a property path constructed with GetPropertyPath() to an array of properties (from the outermost to the innermost) *.
Parameters
ObjectClass Class that defines the outermost property
InPropertyPath Property path
OutProperties resulting array
Returns
true if the conversion was successful, false otherwise
GetPropertyPath()
FString UE::GC::FPropertyStack::GetPropertyPath () const
Get string representing property stack, e.g.
"Member.StructMember.InnerStructMember"
Referenced by UE::GC::ToName().
UE_NONCOPYABLE()
UE::GC::FPropertyStack::UE_NONCOPYABLE (FPropertyStack)
References FPropertyStack().
Friends And Related Symbol Documentation
FPropertyStackScope
friend class FPropertyStackScope friend
Definition at line 80 of file GarbageCollectionSchema.h.
References FPropertyStackScope.
Referenced by FPropertyStackScope.
Field Documentation
Props
TArray<const FProperty*> UE::GC::FPropertyStack::Props private
Definition at line 81 of file GarbageCollectionSchema.h.
Referenced by ~FPropertyStack().
The documentation for this class was generated from the following file:
Runtime/CoreUObject/Public/UObject/GarbageCollectionSchema.h