Unreal Engine 5.6 C++ API: TAsyncResult< ResultType > Class Template Reference
TAsyncResult< ResultType > Class Template Reference
Template for asynchronous return values.
#include "AsyncResult.h"
Public Member Functions
TAsyncResult ()
Default constructor.
template<typename ArgType, typename = std::enable_if_t<std::is_same_v<ArgType, ResultType> && std::is_reference_v<const ArgType&>>>
TAsyncResult (const ArgType &Result)
Creates and initializes a new instance with the given synchronous result value.
TAsyncResult (TAsyncResult &&Other)
Move constructor.
TAsyncResult (TFuture< ResultType > &&InFuture, const TSharedPtr< IAsyncProgress > &InProgress, const TSharedPtr< IAsyncTask > &InTask)
Creates and initializes a new instance.
const TFuture< ResultType > & GetFuture () const
Gets the future that will hold the result.
TSharedPtr< IAsyncProgress > GetProgess () const
Get an object that indicates the progress of the task that is computing the result.
TSharedPtr< IAsyncTask > GetTask () const
Get the asynchronous task that is computing the result.
TAsyncResult & operator= (TAsyncResult &&Other)
Move assignment operator.
Private Member Functions
TAsyncResult (const TAsyncResult &)
Hidden copy constructor (async results cannot be copied).
TAsyncResult & operator= (const TAsyncResult &)
Hidden copy assignment (async results cannot be copied).
Private Attributes
TFuture< ResultType > Future
The future.
TSharedPtr< IAsyncProgress > Progress
The progress object.
TSharedPtr< IAsyncTask > Task
The task object.
Detailed Description
template<typename ResultType>
class TAsyncResult< ResultType >
Template for asynchronous return values.
Parameters
ResultType The return value's type.
Definition at line 17 of file AsyncResult.h.
Constructor & Destructor Documentation
TAsyncResult() [1/5]
template<typename ResultType> TAsyncResult< ResultType >::TAsyncResult () inline
Default constructor.
Definition at line 22 of file AsyncResult.h.
Referenced by TAsyncResult(), TAsyncResult(), operator=(), and operator=().
TAsyncResult() [2/5]
template<typename ResultType> template<typename ArgType, typename = std::enable_if_t<std::is_same_v<ArgType, ResultType> && std::is_reference_v<const ArgType&>>> TAsyncResult< ResultType >::TAsyncResult (const ArgType & Result) inline
Creates and initializes a new instance with the given synchronous result value.
This constructor is only available for referenceable result types, to make 'void' a feasible result type for this template class.
Parameters
Result The result value to set.
Definition at line 33 of file AsyncResult.h.
References Future, TPromise< ResultType >::GetFuture(), and TPromise< ResultType >::SetValue().
TAsyncResult() [3/5]
template<typename ResultType> TAsyncResult< ResultType >::TAsyncResult (TFuture< ResultType > && InFuture, const TSharedPtr< IAsyncProgress > & InProgress, const TSharedPtr< IAsyncTask > & InTask) inline
Creates and initializes a new instance.
Parameters
InFuture The future to set.
InProgress The progress object (optional).
InTask The task object object (optional).
Definition at line 47 of file AsyncResult.h.
References Future, InProgress, MoveTemp(), Progress, and Task.
TAsyncResult() [4/5]
template<typename ResultType> TAsyncResult< ResultType >::TAsyncResult (TAsyncResult< ResultType > && Other) inline
Move constructor.
Definition at line 54 of file AsyncResult.h.
References TAsyncResult(), Future, MoveTemp(), Other, Progress, and Task.
TAsyncResult() [5/5]
template<typename ResultType> TAsyncResult< ResultType >::TAsyncResult (const TAsyncResult< ResultType > &) private
Hidden copy constructor (async results cannot be copied).
References TAsyncResult().
Member Function Documentation
GetFuture()
template<typename ResultType> const TFuture< ResultType > & TAsyncResult< ResultType >::GetFuture () const inline
Gets the future that will hold the result.
Returns
The future.
Definition at line 85 of file AsyncResult.h.
References Future.
GetProgess()
template<typename ResultType> TSharedPtr< IAsyncProgress > TAsyncResult< ResultType >::GetProgess () const inline
Get an object that indicates the progress of the task that is computing the result.
Returns
Task progress object, or nullptr if not available.
Definition at line 95 of file AsyncResult.h.
References Progress.
GetTask()
template<typename ResultType> TSharedPtr< IAsyncTask > TAsyncResult< ResultType >::GetTask () const inline
Get the asynchronous task that is computing the result.
Returns
Task object, or nullptr if not available.
Definition at line 105 of file AsyncResult.h.
References Task.
operator=() [1/2]
template<typename ResultType> TAsyncResult & TAsyncResult< ResultType >::operator= (const TAsyncResult< ResultType > &) private
Hidden copy assignment (async results cannot be copied).
References TAsyncResult().
operator=() [2/2]
template<typename ResultType> TAsyncResult & TAsyncResult< ResultType >::operator= (TAsyncResult< ResultType > && Other) inline
Move assignment operator.
Definition at line 66 of file AsyncResult.h.
References TAsyncResult(), Future, MoveTemp(), Other, Progress, and Task.
Field Documentation
Future
template<typename ResultType> TFuture<ResultType> TAsyncResult< ResultType >::Future private
The future.
Definition at line 121 of file AsyncResult.h.
Referenced by TAsyncResult(), TAsyncResult(), TAsyncResult(), GetFuture(), and operator=().
Progress
template<typename ResultType> TSharedPtr<IAsyncProgress> TAsyncResult< ResultType >::Progress private
The progress object.
Definition at line 124 of file AsyncResult.h.
Referenced by TAsyncResult(), TAsyncResult(), GetProgess(), and operator=().
Task
template<typename ResultType> TSharedPtr<IAsyncTask> TAsyncResult< ResultType >::Task private
The task object.
Definition at line 127 of file AsyncResult.h.
Referenced by TAsyncResult(), TAsyncResult(), GetTask(), and operator=().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Async/AsyncResult.h