Unreal Engine 5.6 C++ API: FLinkerSave Class Reference
FLinkerSave Class Reference
Handles saving Unreal package files.
#include "LinkerSave.h"
Data Structures
struct FSidecarStorageInfo
Public Types
using AdditionalDataCallback = TUniqueFunction<void(FLinkerSave& ExportsArchive, FArchive& DataArchive, int64 DataStartOffset)>
Callback for arbitrary serializers to append data to the end of the ExportsArchive.
Public Member Functions
FLinkerSave (UPackage *InParent)
Partially construct the FLinkerSave.
virtual ~FLinkerSave ()
void AssignMemorySaver (bool bForceByteSwapping, bool bInSaveUnversioned=false)
Construct a FMemoryWriter archive and call AssignSaver with it.
void AssignSaver (FArchive *InSaver, bool bForceByteSwapping, bool bInSaveUnversioned=false)
Assign the Saver that will receive the binary data for the package and write it to disk/memory/unspecified.
bool CloseAndDestroySaver ()
Closes and deletes the Saver (file, memory or custom writer) which will close any associated file handle.
void ForEachBulkDataCookedIndex (TUniqueFunction< void(FBulkDataCookedIndex, FFileRegionMemoryWriter &)> &&Func, EBulkDataPayloadType Type) const
virtual FString GetArchiveName () const override
Returns the name of the Archive.
FFileRegionMemoryWriter & GetBulkDataArchive (FBulkDataCookedIndex CookedIndex)
virtual FString GetDebugName () const override
Returns a descriptor of the PackagePath this Linker is reading from or writing to, usable for an identifier in warning and log messages.
const FString & GetFilename () const
Get the filename being saved to.
virtual FLinker * GetLinker ()
If this archive is a FLinkerLoad or FLinkerSave, returns a pointer to the FLinker portion.
FFileRegionMemoryWriter & GetMemoryMappedBulkDataArchive (FBulkDataCookedIndex CookedIndex)
FFileRegionMemoryWriter & GetOptionalBulkDataArchive (FBulkDataCookedIndex CookedIndex)
FOutputDevice * GetOutputDevice () const
bool HasCookedIndexBulkData () const
int32 MapName (FNameEntryId Name) const
Returns the appropriate name index for the source name, or INDEX_NONE if not found in NameIndices.
FPackageIndex MapObject (TObjectPtr< const UObject > Object) const
Returns the appropriate package index for the source object, or default value if not found in ObjectIndicesMap.
int32 MapSoftObjectPath (const FSoftObjectPath &SoftObjectPath) const
Returns the appropriate soft object path index for the source soft object path, or INDEX_NONE if not found.
virtual void MarkScriptSerializationEnd (const UObject *Obj) override
Called when an object stops serializing property data using script serialization.
virtual void MarkScriptSerializationStart (const UObject *Obj) override
Called when an object begins serializing property data using script serialization.
void OnPostSave (const FPackagePath &PackagePath, FObjectPostSaveContext ObjectSaveContext)
Invoke all of the callbacks in PostSaveCallbacks and then empty it.
void OnPostSaveBulkData ()
Triggered after bulk data payloads has been serialized to disk/package writer.
virtual FArchive & operator<< (FField *&Value)
Serializes a Field value from or into this archive.
virtual FArchive & operator<< (FLazyObjectPtr &LazyObjectPtr) override
Serializes a lazy object pointer value from or into this archive.
virtual FArchive & operator<< (FName &InName) override
Serializes an FName value from or into this archive.
virtual FArchive & operator<< (FObjectPtr &Value) override
Serializes a wrapped object pointer value from or into this archive.
virtual FArchive & operator<< (FSoftObjectPath &SoftObjectPath) override
Serializes soft object paths from or into this archive.
virtual FArchive & operator<< (FSoftObjectPtr &Value) override
Serializes asset pointer from or into this archive.
virtual FArchive & operator<< (FText &Value)
Serializes an FText value from or into an archive.
virtual FArchive & operator<< (FWeakObjectPtr &Value) override
Serializes FWeakObjectPtr value from or into this archive.
template<class T>
FORCEINLINE FArchive & operator<< (TCheckedObjPtr< T > &Value)
Serializes a UObject wrapped in a TCheckedObjPtr container, using the above operator, and verifies the serialized object is derived from the correct base class, to prevent illegal casting.
virtual FArchive & operator<< (UObject *&Obj) override
Serializes an UObject value from or into this archive.
virtual void PopDebugDataString () override
virtual void PopSerializedProperty (class FProperty *InProperty, const bool bIsEditorOnlyProperty) override
Pop a property that was previously being serialized off the property stack.
virtual void PushDebugDataString (const FName &DebugData) override
Debug stack storage if you want to add data to the archive for usage further down the serialization stack this should be used in conjunction with the FScopeAddDebugData struct.
virtual void PushSerializedProperty (class FProperty *InProperty, const bool bIsEditorOnlyProperty) override
Push a property that is currently being serialized onto the property stack.
void Seek (int64 InPos)
Attempts to set the current offset into backing data storage, this will do nothing if there is no storage.
void Serialize (FArchive &Ar)
I/O function.
void Serialize (void *V, int64 Length)
virtual bool SerializeBulkData (FBulkData &BulkData, const FBulkDataSerializationParams &Params) override
Serialize bulk data.
virtual void SetDebugSerializationFlags (uint32 InCustomFlags) override
Sets the archives custom serialization modifier flags (nothing to do with PortFlags or Custom versions)
void SetDeclareRegionForEachAdditionalFile (bool bValue)
Sets whether a separate file regions should be declared for each bulkdata.
void SetFileRegionsEnabled (bool bEnabled)
Sets whether file regions will be written or not.
virtual void SetFilterEditorOnly (bool bInFilterEditorOnly) override
Sets a flag indicating that this archive needs to filter editor-only content.
void SetMemoryMapAlignment (int64 InAlignment)
Set target platform memory map alignment.
void SetOutputDevice (FOutputDevice *InOutputDevice)
void SetSaveBulkDataByReference (bool bValue)
Sets whether saving bulk data by reference, i.e.
void SetSaveBulkDataToSeparateFiles (bool bValue)
Sets whether bulk data will be stored in the Linker archive (.uasset) or in sepearate files (.ubulk, .m.ubulk, .opt.ubulk) .
virtual void SetSerializedProperty (FProperty *InProperty) override
Overrides the property that is currently being serialized.
virtual void SetSerializedPropertyChain (const FArchiveSerializedPropertyChain *InSerializedPropertyChain, class FProperty *InSerializedPropertyOverride=nullptr) override
Set the raw serialized property chain for this archive, optionally overriding the serialized property too (or null to use the head of the property chain)
void SetTransientPropertyOverrides (const TMap< UObject *, TSet< FProperty * > > &InTransientPropertyOverrides)
Sets the map of overrided properties for each export that should be treated as transient, and nulled out when serializing.
virtual void SetUseUnversionedPropertySerialization (bool bInUseUnversioned) override
Sets whether tagged property serialization should be replaced by faster unversioned serialization.
virtual bool ShouldSkipProperty (const FProperty *InProperty) const override
Checks whether the archive wants to skip the property independent of the other flags.
int64 Tell ()
Returns the current location within the backing data storage, which can possibly be passed to Seek later to restore a read/write location.
bool TryAssignFileSaver (FStringView InFilename, bool bForceByteSwapping, bool bInSaveUnversioned=false)
Construct a file saver from IPlatformFile and call AssignSaver with it.
UE_DEPRECATED (5.5, "GetSerializeContext is not supported. Use FUObjectThreadContext::Get().GetSerializeContext().") FUObjectSerializeContext *GetSerializeContext() override
UE_DEPRECATED (5.5, "Use the overload that takes a FBulkDataCookedIndex") FFileRegionMemoryWriter &GetBulkDataArchive()
UE_DEPRECATED (5.5, "Use the overload that takes a FBulkDataCookedIndex") FFileRegionMemoryWriter &GetMemoryMappedBulkDataArchive()
UE_DEPRECATED (5.5, "Use the overload that takes a FBulkDataCookedIndex") FFileRegionMemoryWriter &GetOptionalBulkDataArchive()
UE_DEPRECATED (5.6, "No longer supported, contact Epic if you need this functionality.") 1 static TMap< FString
A mapping of package name to generated script SHA keys.
UE_DEPRECATED (5.6, "Use constructor that takes only Parent and then call AssignFileSaver.") FLinkerSave(UPackage *InParent
Constructor for file writer.
UE_DEPRECATED (5.6, "Use constructor that takes only Parent and then call AssignMemorySaver.") FLinkerSave(UPackage *InParent
Constructor for memory writer.
UE_DEPRECATED (5.6, "Use constructor that takes only Parent and then call AssignSaver.") FLinkerSave(UPackage *InParent
Constructor for custom savers.
virtual void UsingCustomVersion (const struct FGuid &Guid) override
Registers the custom version to the archive.
Public Member Functions inherited from FLinker
FLinker (ELinkerType::Type InType, UPackage *InRoot)
Constructor.
virtual ~FLinker ()
bool FilterExport (const FObjectExport &Export)
Test and object against the load flag filters.
FString GetExportFullName (FPackageIndex PackageIndex, const TCHAR *FakeRoot=nullptr, bool bResolveForcedExports=false)
Return the full name of the UObject represented by the specified package index.
FString GetExportFullName (int32 ExportIndex, const TCHAR *FakeRoot=nullptr, bool bResolveForcedExports=false)
Return the full name of the UObject represented by the specified export.
FString GetExportPathName (FPackageIndex PackageIndex, const TCHAR *FakeRoot=nullptr, bool bResolveForcedExports=false)
Return the path name of the UObject represented by the specified export.
FString GetExportPathName (int32 ExportIndex, const TCHAR *FakeRoot=nullptr, bool bResolveForcedExports=false)
Return the path name of the UObject represented by the specified export.
FString GetFullImpExpName (FPackageIndex PackageIndex)
Return the full name of the UObject represented by the specified export.
FString GetPathName (FPackageIndex PackageIndex)
Return the path name of the UObject represented by the specified import.
FORCEINLINE ELinkerType::Type GetType () const
void Serialize (FArchive &Ar)
I/O function.
UE_DEPRECATED (5.6, "No longer supported. Contact Epic if you need this functionality.") class FSHA1 *ScriptSHA
UE_DEPRECATED (5.6, "No longer supported. Contact Epic if you need this functionality.") void GetScriptSHAKey(uint8 *OutKey)
UE_DEPRECATED (5.6, "No longer supported. Contact Epic if you need this functionality.") void StartScriptSHAGeneration()
UE_DEPRECATED (5.6, "No longer supported. Contact Epic if you need this functionality.") void UpdateScriptSHAKey(const TArray< uint8 > &ScriptCode)
Public Member Functions inherited from FLinkerTables
bool AnyExportIsInImport (int32 ImportIndex) const
Return if any export is in the import.
bool AnyExportShareOuterWithImport (int32 ImportIndex) const
Return if any export share an outer with the import.
bool DoResourcesShareOutermost (FPackageIndex LinkerIndexLHS, FPackageIndex LinkerIndexRHS) const
Return if two resources share the same outermost.
FORCEINLINE FObjectExport & Exp (FPackageIndex Index)
Check that this Index is non-null and an export and return an import.
FORCEINLINE FObjectExport const & Exp (FPackageIndex Index) const
FORCEINLINE FObjectExport * ExpPtr (FPackageIndex Index)
Return an export for this index.
SIZE_T GetAllocatedSize () const
Returns the amount of memory allocated by this container, not including sizeof(*this).
FName GetClassName (FPackageIndex PackageIndex)
Gets the class name for the specified PackageIndex.
FName GetExportClassName (FPackageIndex PackageIndex)
Gets the class name for the specified index in the export map.
FName GetExportClassName (int32 ExportIdx)
Gets the class name for the specified index in the export map.
FString GetExportFullName (const FString &RootPackagePath, int32 ExportIndex, bool bResolveForcedExports=false)
Return the full name of the UObject represented by the specified export.
FString GetExportPathName (const FString &RootPackagePath, int32 ExportIndex, bool bResolveForcedExports=false)
Return the path name of the UObject represented by the specified export.
FName GetImportClassName (FPackageIndex PackageIndex)
Gets the class name for the specified index in the import map.
FName GetImportClassName (int32 ImportIdx)
Gets the class name for the specified index in the import map.
FString GetImportFullName (FPackageIndex PackageIndex)
Return the full name of the UObject represented by the specified package index.
FString GetImportFullName (int32 ImportIndex)
Return the full name of the UObject represented by the specified import.
FString GetImportPathName (FPackageIndex PackageIndex)
Return the path name of the UObject represented by the specified import.
FString GetImportPathName (int32 ImportIndex)
Return the path name of the UObject represented by the specified import.
FORCEINLINE FObjectImport & Imp (FPackageIndex Index)
Check that this Index is non-null and an import and return an import.
FORCEINLINE FObjectImport const & Imp (FPackageIndex Index) const
FORCEINLINE FObjectResource & ImpExp (FPackageIndex Index)
Check that this Index is non-null and return an import or export.
FORCEINLINE FObjectResource const & ImpExp (FPackageIndex Index) const
Check that this Index is non-null and return an import or export.
FORCEINLINE FObjectResource * ImpExpPtr (FPackageIndex Index)
Return an import or export for this index.
bool ImportIsInAnyExport (int32 ImportIndex) const
Return if the import is in any export.
FORCEINLINE FObjectImport * ImpPtr (FPackageIndex Index)
Return an import for this index.
FPackageIndex ResourceGetOutermost (FPackageIndex LinkerIndex) const
Return the outermost resource package index of the resource pointed by LinkerIndex.
bool ResourceIsIn (FPackageIndex LinkerIndex, FPackageIndex OuterIndex) const
Return if a resource has the specified other resource in its outer chain.
void SerializeSearchableNamesMap (FArchive &Ar)
Serializes the searchable name map.
void SerializeSearchableNamesMap (FStructuredArchive::FSlot Slot)
Public Member Functions inherited from FArchiveUObject
template<class T>
FORCEINLINE FArchive & operator<< (TCheckedObjPtr< T > &Value)
Serializes a UObject wrapped in a TCheckedObjPtr container, using the above operator, and verifies the serialized object is derived from the correct base class, to prevent illegal casting.
Public Member Functions inherited from FArchive
FArchive ()=default
FArchive (const FArchive &)=default
virtual ~FArchive ()
virtual bool AtEnd ()
Returns true if the current location within the backing data storage is at the end, always returns false if there is no storage.
virtual void AttachBulkData (UE::Serialization::FEditorBulkData *BulkData)
virtual void AttachBulkData (UObject *Owner, FBulkData *BulkData)
Attaches/ associates the passed in bulk data object with the linker.
virtual bool AttachExternalReadDependency (FExternalReadCallback &ReadCallback)
Adds external read dependency.
FORCEINLINE FArchive & ByteOrderSerialize (void *V, int32 Length)
Serialize data of Length bytes, taking into account byte swapping if needed.
void ByteSwap (void *V, int32 Length)
Used to do byte swapping on small items.
void ClearError ()
Sets ArIsError to false, this does not clear any CriticalErrors.
virtual bool Close ()
Attempts to close and finalize any handles used for backing data storage, returns true if it succeeded.
FORCEINLINE bool ContainsCode () const
Returns true if this archive contains native or generated code.
FORCEINLINE bool ContainsMap () const
Returns true if this archive contains a ULevel or UWorld object.
FORCEINLINE const ITargetPlatform * CookingTarget () const
Returns the cooking target platform.
virtual void CountBytes (SIZE_T InNum, SIZE_T InMax)
Called to get the computed size from a size-detecting archive after it has finished serializing.
int32 CustomVer (const struct FGuid &Key) const
Queries a custom version from the archive.
virtual void DetachBulkData (FBulkData *BulkData, bool bEnsureBulkDataIsLoaded)
Detaches the passed in bulk data object from the linker.
virtual void DetachBulkData (UE::Serialization::FEditorBulkData *BulkData, bool bEnsureBulkDataIsLoaded)
FORCEINLINE bool DoDelta () const
Returns true if this archive should handle delta serialization for properties.
FORCEINLINE bool DoIntraPropertyDelta () const
Returns true if this archive should perform delta serialization within properties (e.g.
virtual uint32 EngineNetVer () const
Returns the engine-global network protocol version for this archive.
FORCEINLINE FEngineVersionBase EngineVer () const
Returns the compiled engine version used for this archive.
template<SIZE_T Size>
FORCEINLINE bool FastPathLoad (void *InDest)
virtual void Flush ()
Attempts to finish writing any buffered data to disk/permanent storage.
virtual void FlushCache ()
Flushes cache and frees internal data.
virtual void ForceBlueprintFinalization ()
Inform the archive that a blueprint would like to force finalization, normally this is triggered by CDO load, but if there's no CDO we force finalization.
FORCEINLINE bool ForceByteSwapping () const
Returns true if this archive should always swap bytes, ignoring endian rules.
virtual uint32 GameNetVer () const
Returns the game-specific network protocol version for this archive.
virtual UObject * GetArchetypeFromLoader (const UObject *Obj)
Called to retrieve the archetype from the event driven loader.
FArchiveState & GetArchiveState ()
Returns the low level archive state for this archive.
const FArchiveState & GetArchiveState () const
virtual FArchive * GetCacheableArchive ()
Returns a pointer to an archive that represents the same data that the current archive covers, but that can be cached and reused later In the case of standard archives, this function will just return a pointer to itself.
FORCEINLINE FArchiveCookContext * GetCookContext ()
virtual const FCustomVersionContainer & GetCustomVersions () const
Gets the custom version numbers for this archive.
FORCEINLINE uint32 GetDebugSerializationFlags () const
Returns the editor-only debug serialization flags.
FORCEINLINE bool GetError () const
virtual FArchiveState & GetInnermostState ()
Returns lowest level archive state, proxy archives will override this.
FORCEINLINE int64 GetMaxSerializeSize () const
Returns the maximum size of data that this archive is allowed to serialize.
virtual const FUObjectMigrationContext * GetMigrationContext () const
When migrating objects, we may need some context as to the intent of the migration during serialization.
FORCEINLINE uint32 GetPortFlags () const
Returns this archive's property serialization modifier flags.
FArchiveSavePackageData * GetSavePackageData ()
FORCEINLINE class FProperty * GetSerializedProperty () const
Gets the property that is currently being serialized.
FORCEINLINE const FArchiveSerializedPropertyChain * GetSerializedPropertyChain () const
Get the raw serialized property chain for this archive.
void GetSerializedPropertyChain (TArray< class FProperty * > &OutProperties) const
Gets the chain of properties that are currently being serialized.
FORCEINLINE bool HasAllPortFlags (uint32 Flags) const
Checks to see if all of the passed in property serialization modifier flags are set.
FORCEINLINE bool HasAnyPortFlags (uint32 Flags) const
Checks to see if any of the passed in property serialization modifier flags are set.
FORCEINLINE bool IsAllowingLazyLoading () const
Returns true if this archive sould allow lazy loading of bulk / secondary data.
FORCEINLINE bool IsByteSwapping ()
Returns true if data larger than 1 byte should be swapped to deal with endian mismatches.
FORCEINLINE bool IsCooking () const
Checks whether the archive is used for cooking.
FORCEINLINE bool IsCountingMemory () const
Returns true if this archive is counting memory, normally CountBytes is called to get the size.
FORCEINLINE bool IsCriticalError () const
Returns true if this archive contains critical errors that cannot be recovered from.
FORCEINLINE bool IsError () const
Returns true if this archive contains errors, which means that further serialization is generally not safe.
bool IsFilterEditorOnly () const
Indicates whether this archive is filtering editor-only on save or contains data that had editor-only content stripped.
FORCEINLINE bool IsForcingUnicode () const
Returns true if this archive wants to always save strings in UTF16 format even if they are ANSI characters.
FORCEINLINE bool IsIgnoringArchetypeRef () const
Returns true if this archive should ignore archetype references for structs and classes.
FORCEINLINE bool IsIgnoringClassGeneratedByRef () const
Returns true if this archive should ignore the ClassGeneratedBy reference in UClass.
FORCEINLINE bool IsIgnoringClassRef () const
Returns true if this archive should ignore the Class reference in UObject.
FORCEINLINE bool IsIgnoringOuterRef () const
Returns true if this archive should ignore the Outer reference in UObject.
FORCEINLINE bool IsLoading () const
Returns true if this archive is for loading data.
FORCEINLINE bool IsLoadingFromCookedPackage () const
Returns true if this archive is loading from a cooked package.
FORCEINLINE constexpr bool IsMigratingRemoteObjects () const
Returns true if this Archive is migrating remote object.
FORCEINLINE bool IsModifyingWeakAndStrongReferences () const
Returns true if this archive should modify/search weak object references as well as strong ones.
FORCEINLINE bool IsNetArchive () const
Whether or not this archive is serializing data being sent/received by the netcode.
FORCEINLINE bool IsObjectReferenceCollector () const
Returns true if this archive is only looking for UObject references.
FORCEINLINE bool IsPersistent () const
Returns true if this archive is saving or loading data destined for persistent storage and should skip transient data.
virtual bool IsProxyOf (FArchive *InOther) const
Determine if the given archive is a valid "child" of this archive.
bool IsSaveGame () const
Indicates whether this archive is saving or loading game state.
FORCEINLINE bool IsSaving () const
Returns true if this archive is for saving data, this can also be a pre-save preparation archive.
FORCEINLINE bool IsSerializingDefaults () const
Returns true if this archive is currently serializing class/struct default values.
FORCEINLINE bool IsTextFormat () const
Returns true if this archive serializes to a structured text format.
FORCEINLINE bool IsTransacting () const
Returns true if this archive is transacting, which is used to keep track of changes to objects for things like the editor undo system.
FORCEINLINE int32 LicenseeUEVer () const
Returns the licensee-specific version used for this archive, will be 0 by default.
template<typename FmtType, typename... Types>
void Logf (const FmtType &Fmt, Types... Args)
virtual void MarkSearchableName (const TObjectPtr< const UObject > &TypeObject, const FName &ValueName) const
Called to register a reference to a specific name value, of type TypeObject (UEnum or UStruct normally).
template<class T>
FORCEINLINE FArchive & operator<< (TCheckedObjPtr< T > &Value)
Serializes a UObject wrapped in a TCheckedObjPtr container, using the above operator, and verifies the serialized object is derived from the correct base class, to prevent illegal casting.
FArchive & operator= (const FArchive &ArchiveToCopy)=default
virtual void PopFileRegionType ()
virtual bool Precache (int64 PrecacheOffset, int64 PrecacheSize)
Hint the archive that the region starting at passed in offset and spanning the passed in size is going to be read soon and should be precached.
virtual void Preload (UObject *Object)
Tells the archive to attempt to preload the specified object so data can be loaded out of it.
virtual void PushFileRegionType (EFileRegionType Type)
Called whilst cooking to provide file region hints to the cooker.
FORCEINLINE bool RequiresLocalizationGather () const
Returns true if this archive contains data required to be gathered for localization.
virtual void Reset ()
Resets all of the base archive members.
virtual void ResetCustomVersions ()
Resets the custom version numbers for this archive.
virtual void SerializeBits (void *V, int64 LengthBits)
void SerializeCompressed (void *V, int64 Length, FName CompressionFormatCannotChange, ECompressionFlags Flags=COMPRESS_NoFlags, bool bTreatBufferAsFileReader=false)
Serializes and compresses/ uncompresses data.
void SerializeCompressedNew (void *V, int64 Length)
Serializes and compresses/ uncompresses data with default compressor choices.
void SerializeCompressedNew (void *V, int64 Length, FName CompressionFormatToEncode, FName CompressionFormatToDecodeOldV1Files, ECompressionFlags Flags=COMPRESS_NoFlags, bool bTreatBufferAsFileReader=false, int64 *OutPartialReadLength=nullptr)
Serializes and compresses/ uncompresses data.
virtual void SerializeInt (uint32 &Value, uint32 Max)
virtual void SerializeIntPacked (uint32 &Value)
Packs int value into bytes of 7 bits with 8th bit for 'more'.
virtual void SerializeIntPacked64 (uint64 &Value)
void SetArchiveState (const FArchiveState &InState)
Modifies current archive state, can be used to override flags.
void SetByteSwapping (bool Enabled)
Toggle byte order swapping.
virtual bool SetCompressionMap (TArray< FCompressedChunk > *CompressedChunks, ECompressionFlags CompressionFlags)
Sets mapping from offsets/ sizes that are going to be used for seeking and serialization to what is actually stored on disk.
void SetCriticalError ()
Sets the archiver IsCriticalError and IsError to true.
void SetCustomVersion (const struct FGuid &Key, int32 Version, FName FriendlyName)
Sets a specific custom version.
virtual void SetCustomVersions (const FCustomVersionContainer &CustomVersionContainer)
Sets the custom version numbers for this archive.
virtual void SetEngineNetVer (const uint32 InEngineNetVer)
Sets the archive engine network version.
virtual void SetEngineVer (const FEngineVersionBase &InVer)
Sets the archive engine version.
void SetError ()
Sets ArIsError to true.
virtual void SetForceUnicode (bool bInForceUnicode)
Sets whether this archive wants to force saving as Unicode.
virtual void SetGameNetVer (const uint32 InGameNetVer)
Sets the archive game network version.
virtual void SetIsLoading (bool bInIsLoading)
Sets whether this archive is for loading data.
virtual void SetIsLoadingFromCookedPackage (bool bInIsLoadingFromCookedPackage)
Sets whether the archive is loading from a cooked package.
virtual void SetIsPersistent (bool bInIsPersistent)
Sets whether this archive is to persistent storage.
virtual void SetIsSaving (bool bInIsSaving)
Sets whether this archive is for saving data.
virtual void SetIsTextFormat (bool bInIsTextFormat)
Sets whether this archive is in text format.
virtual void SetIsTransacting (bool bInIsTransacting)
Sets whether this archive is for transacting.
virtual void SetLicenseeUEVer (int32 InVer)
Sets the archive licensee version number.
void SetMigratingRemoteObjects (bool bMigrating)
If set true, this archive is migrating remote objects.
void SetPortFlags (uint32 InPortFlags)
Sets the archive's property serialization modifier flags.
void SetSavePackageData (FArchiveSavePackageData *InSavePackageData)
Marks that this archive is one of the archives used by SavePackage, and provides access to data and functions used only during savepackage, such as the cook data bundle for information about the cook being conducted (if applicable) and writing build dependencies for assetregistry.
void SetShouldSkipUpdateCustomVersion (bool bShouldSkip)
If set true, UsingCurrentVersion will not query the version registry to get the latest version data for the key if the version key is already set in the local container.
virtual void SetUEVer (FPackageFileVersion InVer)
Sets the archive version number.
virtual void SetWantBinaryPropertySerialization (bool bInWantBinaryPropertySerialization)
Sets whether this archive wants binary property serialization.
FORCEINLINE bool ShouldSkipBulkData () const
Returns true if this archive should ignore bulk data.
FORCEINLINE bool ShouldSkipCompilingAssets () const
Returns true if it is allowed to skip serialization on assets still being compiled to avoid waiting unless strictly necessary.
FORCEINLINE bool ShouldSkipUpdateCustomVersion () const
Returns true if this Archive does not update the custom version data for a given key if has already been set previously in the local custom versions container.
void StartSerializingDefaults ()
Sets a flag indicating that this archive is currently serializing class/struct defaults.
void StopSerializingDefaults ()
Indicate that this archive is no longer serializing class/struct defaults.
void ThisContainsCode ()
Sets a flag indicating that this archive contains native or generated code.
void ThisContainsMap ()
Sets a flag indicating that this archive contains a ULevel or UWorld object.
void ThisRequiresLocalizationGather ()
Sets a flag indicating that this archive contains data required to be gathered for localization.
virtual int64 TotalSize ()
Returns total size of the backing data storage.
UE_DEPRECATED (5.5, "Use GetCookContext or CookingTarget or GetSavePackageData") FArchiveCookData *GetCookData()
UE_DEPRECATED (5.5, "Use SetSavePackageData.") void SetCookData(FArchiveCookData *InCookData)
FORCEINLINE FPackageFileVersion UEVer () const
Returns the global engine serialization version used for this archive.
virtual bool UseToResolveEnumerators () const
Checks whether the archive is used to resolve out-of-date enum indexes If function returns true, the archive should be called only for objects containing user defined enum.
FORCEINLINE bool UseUnversionedPropertySerialization () const
Returns true if tagged property serialization should be replaced by faster unversioned serialization.
FORCEINLINE bool WantBinaryPropertySerialization () const
Returns true if this archive wants properties to be serialized in binary form instead of safer but slower tagged form.
Static Public Member Functions
static FORCEINLINE ELinkerType::Type StaticType ()
Static Public Member Functions inherited from FArchiveUObject
static FArchive & SerializeLazyObjectPtr (FArchive &Ar, FLazyObjectPtr &Value)
static FArchive & SerializeObjectPtr (FArchive &Ar, FObjectPtr &Value)
static FArchive & SerializeSoftObjectPath (FArchive &Ar, FSoftObjectPath &Value)
static FArchive & SerializeSoftObjectPtr (FArchive &Ar, FSoftObjectPtr &Value)
static FArchive & SerializeWeakObjectPtr (FArchive &Ar, FWeakObjectPtr &Value)
Data Fields
TArray< AdditionalDataCallback > AdditionalDataToAppend
Array of callbacks that will be invoked when it is possible to serialize out data to the end of the output file.
const TCHAR bool bForceByteSwapping
bool bForceByteSwapping
FArchive bool bForceByteSwapping
const TCHAR bool bool bInSaveUnversioned = false)
bool bool bInSaveUnversioned = false)
FArchive bool bool bInSaveUnversioned = false)
bool bIsWritingHeaderSoftObjectPaths = false
Flag that indicate if we are currently serializing the package header soft object paths.
bool bProceduralSave = false
Set to true when the package is being saved due to a procedural save.
bool bRehydratePayloads = false
When set to true, payloads that are currently virtualized should be downloaded and stored locally with the package.
bool bUpdatingLoadedPath = false
Set to true when the LoadedPath of the package being saved is being updated.
TMap< Verse::VCell *, FPackageIndex > CellIndicesMap
FPackageIndex CurrentlySavingExport
UObject * CurrentlySavingExportObject = nullptr
TArray< FPackageIndex > DepListForErrorChecking
TArray< FFileRegion > FileRegions
const TCHAR * InFilename
FArchive * InSaver
TMap< FNameEntryId, int32 > NameIndices
TMap< TObjectPtr< UObject >, FPackageIndex > ObjectIndicesMap
Index array - location of the resource for a UObject is stored in the ObjectIndices array using the UObject's Index.
TArray< uint8 > PackagesToScriptSHAMap
TUniquePtr< UE::FPackageTrailerBuilder > PackageTrailerBuilder
Gathers all payloads while save the package, so that they can be stored in a single data structure.
TArray< TUniqueFunction< void(const FPackagePath &PackagePath, FObjectPostSaveContext ObjectSaveContext)> > PostSaveCallbacks
Array of callbacks that will be invoked when the package has successfully saved to disk.
TRefCountPtr< FUObjectSerializeContext > SaveContext
Save context associated with this linker.
FArchive * Saver = nullptr
The archive that actually writes the data to disk.
TMap< const UObject *, TArray< FName > > SearchableNamesObjectMap
List of Searchable Names, by object containing them.
TArray< FSidecarStorageInfo > SidecarDataToAppend
Used by FEditorBulkData to add payloads to be added to the payload sidecar file (currently an experimental feature)
TMap< FSoftObjectPath, int32 > SoftObjectPathIndices
Data Fields inherited from FLinker
TArray< FObjectDataResource > DataResourceMap
Raw/bulk data references.
bool FilterClientButNotServer
If true, filter out exports that are for clients but not servers.
bool FilterServerButNotClient
If true, filter out exports that are for servers but not clients.
TArray< FGatherableTextData > GatherableTextDataMap
Gatherable text data contained within this package.
UPackage * LinkerRoot
The top-level UPackage object for the package associated with this linker.
TArray< FNameEntryId > NameMap
Names used by objects contained within this package.
TArray< FSoftObjectPath > SoftObjectPathList
List of SoftObjectPath contained in this package,.
FPackageFileSummary Summary
Table of contents for this package's file.
Data Fields inherited from FLinkerTables
TArray< FCellExport > CellExportMap
The list of FCellExports found in the package.
TArray< FCellImport > CellImportMap
The list of FCellImports found in the package.
TArray< TArray< FPackageIndex > > DependsMap
List of dependency lists for each export.
TArray< FObjectExport > ExportMap
The list of FObjectExports found in the package.
TArray< FObjectImport > ImportMap
The list of FObjectImports found in the package.
TMap< FPackageIndex, TArray< FName > > SearchableNamesMap
List of Searchable Names, by object containing them.
TArray< FName > SoftPackageReferenceList
List of packages that are soft referenced by this package.
Data Fields inherited from FArchive
FFastPathLoadBuffer * ActiveFPLB
uint8 ArAllowLazyLoading: 1
Whether to allow lazy loading of bulk/secondary data.
uint8 ArContainsCode: 1
Quickly tell if an archive contains script code.
uint8 ArContainsMap: 1
Used to determine whether FArchive contains a level or world.
const struct FCustomPropertyListNode * ArCustomPropertyList
Custom property list attribute.
uint32 ArDebugSerializationFlags
Custom serialization modifier flags can be used for anything.
UE_DEPRECATED(5.6, "Public access to ArRequiresLocalizationGather has been deprecated - please use Ar.RequiresLocalizationGather() and Ar.ThisRequiresLocalizationGather() for getting and setting respectively.") uint8 ArRequiresLocalizationGather uint8 ArForceByteSwapping: 1
Used to determine whether FArchive contains data required to be gathered for localization.
uint8 ArIgnoreArchetypeRef: 1
If true, we will not serialize archetype references for structs and classes.
uint8 ArIgnoreClassGeneratedByRef: 1
If true, we will not serialize ClassGeneratedBy reference in UClass.
uint8 ArIgnoreClassRef: 1
If true, UObject::Serialize will skip serialization of the Class property.
uint8 ArIgnoreOuterRef: 1
If true, we will not serialize the Outer reference in UObject.
uint8 ArIsCountingMemory: 1
Whether this archive is counting memory.
uint8 ArIsFilterEditorOnly: 1
Whether editor only properties are being filtered from the archive (or has been filtered).
uint8 ArIsModifyingWeakAndStrongReferences: 1
Whether a reference collector is modifying the references and wants both weak and strong ones.
uint8 ArIsNetArchive: 1
Whether or not this archive is sending/receiving network data.
uint8 ArIsObjectReferenceCollector: 1
Whether this archive only cares about serializing object references.
uint8 ArIsSaveGame: 1
Whether this archive is saving/loading game state.
int64 ArMaxSerializeSize
Max size of data that this archive is allowed to serialize.
uint8 ArMergeOverrides: 1
Set to false if OverriddenProperties should be cleared at the beginning of SerializeVersionedTaggedProperties.
uint8 ArNoDelta: 1
If true, do not perform delta serialization of properties.
uint8 ArNoIntraPropertyDelta: 1
If true, do not perform delta serialization within properties (e.g.
uint32 ArPortFlags
Modifier flags that be used when serializing UProperties.
uint8 ArPreserveArrayElements: 1
Set TRUE to stop arrays from being cleared before they're loaded.
int32 ArSerializingDefaults
Whether we are currently serializing defaults.
uint8 ArShouldSkipBulkData: 1
Whether bulk data serialization should be skipped or not.
uint8 ArUseCustomPropertyList: 1
Set TRUE to use the custom property list attribute for serialization.
FFastPathLoadBuffer InlineFPLB
Protected Member Functions
void AssignSaverInternal (FArchive *InSaver, bool bForceByteSwapping, bool bInSaveUnversioned)
const TMap< FBulkDataCookedIndex, TUniquePtr< FFileRegionMemoryWriter > > & GetArchives (EBulkDataPayloadType Type) const
void SerializeObjectPointer (const FObjectPtr &Value)
void SetFilename (FStringView InFilename)
Set the filename being saved to.
Protected Member Functions inherited from FArchive
virtual void SerializeBool (bool &D)
Serializes a Boolean value from or into an archive.
void SetShouldSkipCompilingAssets (bool Enabled)
Set whether or not it is allowed to skip serialization on assets still being compiled to avoid waiting unless strictly necessary.
Private Attributes
bool bDeclareRegionForEachAdditionalFile = false
Whether a separate file region should be declared for each bulkdata.
bool bFileRegionsEnabled = false
Whether file regions are enabled.
bool bSaveBulkDataByReference = false
Whether saving bulk data by reference.
bool bSaveBulkDataToSeparateFiles = false
Whether saving bulk data to separate files.
TMap< FBulkDataCookedIndex, TUniquePtr< FFileRegionMemoryWriter > > BulkDataAr
Default bulk data archive.
FString Filename
The name of the file for this package.
FOutputDevice * LogOutput = nullptr
Optional log output to bubble errors back up.
TMap< FBulkDataCookedIndex, TUniquePtr< FFileRegionMemoryWriter > > MemoryMappedBulkDataAr
Memory mapped bulk data archive.
int64 MemoryMappingAlignment = -1
Alignment for memory mapped data .
TMap< FBulkDataCookedIndex, TUniquePtr< FFileRegionMemoryWriter > > OptionalBulkDataAr
Optional bulk data archive.
TMap< FBulkData *, int32 > SerializedBulkData
Map from bulk data object to resource index.
const TMap< UObject *, TSet< FProperty * > > * TransientPropertyOverrides = nullptr
Friends
FORCEINLINE friend FArchive & operator<< (FArchive &Ar, ANSICHAR &Value)
Serializes an ANSICHAR value from or into an archive.
FORCEINLINE friend FArchive & operator<< (FArchive &Ar, bool &D)
FORCEINLINE friend FArchive & operator<< (FArchive &Ar, double &Value)
Serializes a double precision floating point value from or into an archive.
FORCEINLINE friend FArchive & operator<< (FArchive &Ar, float &Value)
Serializes a single precision floating point value from or into an archive.
FArchive & operator<< (FArchive &Ar, FString &Value)
Serializes an FString value from or into an archive.
FORCEINLINE friend FArchive & operator<< (FArchive &Ar, int16 &Value)
Serializes a signed 16-bit integer value from or into an archive.
FORCEINLINE friend FArchive & operator<< (FArchive &Ar, int32 &Value)
Serializes a signed 32-bit integer value from or into an archive.
FArchive & operator<< (FArchive &Ar, int64 &Value)
Serializes a signed 64-bit integer value from or into an archive.
FORCEINLINE friend FArchive & operator<< (FArchive &Ar, int8 &Value)
Serializes a signed 8-bit integer value from or into an archive.
FORCEINLINE friend FArchive & operator<< (FArchive &Ar, uint16 &Value)
Serializes an unsigned 16-bit integer value from or into an archive.
FORCEINLINE friend FArchive & operator<< (FArchive &Ar, uint32 &Value)
Serializes an unsigned 32-bit integer value from or into an archive.
FORCEINLINE friend FArchive & operator<< (FArchive &Ar, uint64 &Value)
Serializes a unsigned 64-bit integer value from or into an archive.
FORCEINLINE friend FArchive & operator<< (FArchive &Ar, uint8 &Value)
Serializes an unsigned 8-bit integer value from or into an archive.
FORCEINLINE friend FArchive & operator<< (FArchive &Ar, UTF32CHAR &Value)
Serializes a UTF32CHAR value from or into an archive.
FORCEINLINE friend FArchive & operator<< (FArchive &Ar, WIDECHAR &Value)
Serializes a WIDECHAR value from or into an archive.
Additional Inherited Members
Static Protected Member Functions inherited from FArchive
static void LinkProxy (FArchiveState &Inner, FArchiveState &Proxy)
static void UnlinkProxy (FArchiveState &Inner, FArchiveState &Proxy)
Detailed Description
Handles saving Unreal package files.
Definition at line 46 of file LinkerSave.h.
Member Typedef Documentation
AdditionalDataCallback
using FLinkerSave::AdditionalDataCallback = TUniqueFunction<void(FLinkerSave& ExportsArchive, FArchive& DataArchive, int64 DataStartOffset)>
Callback for arbitrary serializers to append data to the end of the ExportsArchive.
Some PackageWriters used by SavePackage will write this data to a separate archive.
Parameters
ExportsArchive The archive containing the UObjects and structs, this is always this LinkerSave.
DataArchive The archive to which the data should be written. Might be this LinkerSave, or might be a separate archive.
DataStartOffset The offset to the beginning of the range in DataArchive that should be stored in the UObject or struct's export data. Reading at DataStartOffset from the FArchive passed into Serialize during a load will return the data that the callback wrote to DataArchive.
Definition at line 96 of file LinkerSave.h.
Constructor & Destructor Documentation
~FLinkerSave()
virtual FLinkerSave::~FLinkerSave () virtual
FLinkerSave()
FLinkerSave::FLinkerSave (UPackage * InParent) explicit
Partially construct the FLinkerSave.
No FArchive functions may be called on *this until AssignSaver has been called with a non-null FArchive.
References FLinkerSave().
Referenced by FLinkerSave().
Member Function Documentation
AssignMemorySaver()
void FLinkerSave::AssignMemorySaver (bool bForceByteSwapping, bool bInSaveUnversioned = false)
Construct a FMemoryWriter archive and call AssignSaver with it.
See also
AssignSaver.
References AssignMemorySaver(), bForceByteSwapping, and bInSaveUnversioned.
Referenced by AssignMemorySaver().
AssignSaver()
void FLinkerSave::AssignSaver (FArchive * InSaver, bool bForceByteSwapping, bool bInSaveUnversioned = false)
Assign the Saver that will receive the binary data for the package and write it to disk/memory/unspecified.
Must be called only once, after construction and before any calls to FArchive functions on this. Takes ownership of the given archive, and deletes it in CloseAndDestroySaver or destructor.
Parameters
bForceByteSwapping Passed to FArchive::IsByteSwapping
bInSaveUnversioned Passed to FPackageFileSummary::bUnversioned, which if true removes native versioning and custom versions from the saved package. Used for cooked packages, which exactly match native runtime version.
References FArchive::FArchive(), AssignSaver(), bForceByteSwapping, bInSaveUnversioned, and InSaver.
Referenced by AssignSaver().
AssignSaverInternal()
void FLinkerSave::AssignSaverInternal (FArchive * InSaver, bool bForceByteSwapping, bool bInSaveUnversioned) protected
References FArchive::FArchive(), bForceByteSwapping, bInSaveUnversioned, and InSaver.
CloseAndDestroySaver()
bool FLinkerSave::CloseAndDestroySaver ()
Closes and deletes the Saver (file, memory or custom writer) which will close any associated file handle.
Returns false if the owned saver contains errors after closing it, true otherwise.
ForEachBulkDataCookedIndex()
void FLinkerSave::ForEachBulkDataCookedIndex (TUniqueFunction< void(FBulkDataCookedIndex, FFileRegionMemoryWriter &)> && Func, EBulkDataPayloadType Type) const
GetArchiveName()
virtual FString FLinkerSave::GetArchiveName () const override virtual
Returns the name of the Archive.
Useful for getting the name of the package a struct or object is in when a loading error occurs.
This is overridden for the specific Archive Types
Reimplemented from FArchive.
GetArchives()
const TMap< FBulkDataCookedIndex, TUniquePtr< FFileRegionMemoryWriter > > & FLinkerSave::GetArchives (EBulkDataPayloadType Type) const protected
GetBulkDataArchive()
FFileRegionMemoryWriter & FLinkerSave::GetBulkDataArchive (FBulkDataCookedIndex CookedIndex)
Referenced by UE_DEPRECATED().
GetDebugName()
virtual FString FLinkerSave::GetDebugName () const override virtual
Returns a descriptor of the PackagePath this Linker is reading from or writing to, usable for an identifier in warning and log messages.
Reimplemented from FLinker.
GetFilename()
const FString & FLinkerSave::GetFilename () const
Get the filename being saved to.
GetLinker()
virtual FLinker * FLinkerSave::GetLinker () inline virtual
If this archive is a FLinkerLoad or FLinkerSave, returns a pointer to the FLinker portion.
Reimplemented from FArchive.
Definition at line 267 of file LinkerSave.h.
References FLinker::FLinker().
GetMemoryMappedBulkDataArchive()
FFileRegionMemoryWriter & FLinkerSave::GetMemoryMappedBulkDataArchive (FBulkDataCookedIndex CookedIndex)
Referenced by UE_DEPRECATED().
GetOptionalBulkDataArchive()
FFileRegionMemoryWriter & FLinkerSave::GetOptionalBulkDataArchive (FBulkDataCookedIndex CookedIndex)
Referenced by UE_DEPRECATED().
GetOutputDevice()
FOutputDevice * FLinkerSave::GetOutputDevice () const inline
Definition at line 310 of file LinkerSave.h.
References LogOutput.
HasCookedIndexBulkData()
bool FLinkerSave::HasCookedIndexBulkData () const
MapName()
int32 FLinkerSave::MapName (FNameEntryId Name) const
Returns the appropriate name index for the source name, or INDEX_NONE if not found in NameIndices.
References MapName(), and Name.
Referenced by MapName().
MapObject()
FPackageIndex FLinkerSave::MapObject (TObjectPtr< const UObject > Object) const
Returns the appropriate package index for the source object, or default value if not found in ObjectIndicesMap.
References MapObject(), and Object.
Referenced by MapObject().
MapSoftObjectPath()
int32 FLinkerSave::MapSoftObjectPath (const FSoftObjectPath & SoftObjectPath) const
Returns the appropriate soft object path index for the source soft object path, or INDEX_NONE if not found.
References MapSoftObjectPath(), and SoftObjectPath.
Referenced by MapSoftObjectPath().
MarkScriptSerializationEnd()
virtual void FLinkerSave::MarkScriptSerializationEnd (const UObject * Obj) override virtual
Called when an object stops serializing property data using script serialization.
Reimplemented from FArchive.
References MarkScriptSerializationEnd().
Referenced by MarkScriptSerializationEnd().
MarkScriptSerializationStart()
virtual void FLinkerSave::MarkScriptSerializationStart (const UObject * Obj) override virtual
Called when an object begins serializing property data using script serialization.
Reimplemented from FArchive.
References MarkScriptSerializationStart().
Referenced by MarkScriptSerializationStart().
OnPostSave()
void FLinkerSave::OnPostSave (const FPackagePath & PackagePath, FObjectPostSaveContext ObjectSaveContext)
Invoke all of the callbacks in PostSaveCallbacks and then empty it.
References PackagePath.
OnPostSaveBulkData()
void FLinkerSave::OnPostSaveBulkData ()
Triggered after bulk data payloads has been serialized to disk/package writer.
operator<<() [1/10]
virtual FArchive & FArchive::operator<< (FField *& Value) inline virtual
Serializes a Field value from or into this archive.
This operator can be implemented by sub-classes that wish to serialize UObject instances.
Parameters
Value The value to serialize.
Returns
This instance.
Reimplemented from FArchiveUObject.
Definition at line 26 of file Archive.h.
operator<<() [2/10]
virtual FArchive & FLinkerSave::operator<< (FLazyObjectPtr & Value) override virtual
Serializes a lazy object pointer value from or into this archive.
Most of the time, FLazyObjectPtrs are serialized as UObject*, but some archives need to override this.
Parameters
Value The value to serialize.
Returns
This instance.
Reimplemented from FArchiveUObject.
References FArchive::FArchive(), and LazyObjectPtr.
operator<<() [3/10]
virtual FArchive & FLinkerSave::operator<< (FName & Value) override virtual
Serializes an FName value from or into this archive.
This operator can be implemented by sub-classes that wish to serialize FName instances.
Parameters
Value The value to serialize.
Returns
This instance.
Reimplemented from FArchiveUObject.
References FArchive::FArchive(), and InName.
operator<<() [4/10]
virtual FArchive & FLinkerSave::operator<< (FObjectPtr & Value) override virtual
Serializes a wrapped object pointer value from or into this archive.
Most of the time, FObjectPtrs are serialized as UObject*, but some archives need to override this.
Parameters
Value The value to serialize.
Returns
This instance.
Reimplemented from FArchiveUObject.
References FArchive::FArchive(), Cell, and Value.
operator<<() [5/10]
virtual FArchive & FLinkerSave::operator<< (FSoftObjectPath & Value) override virtual
Serializes soft object paths from or into this archive.
Parameters
Value Soft object path to serialize.
Returns
This instance.
Reimplemented from FArchiveUObject.
References FArchive::FArchive(), and SoftObjectPath.
operator<<() [6/10]
virtual FArchive & FArchiveUObject::operator<< (FSoftObjectPtr & Value) inline override virtual
Serializes asset pointer from or into this archive.
Most of the time, FSoftObjectPtr are serialized as UObject *, but some archives need to override this.
Parameters
Value The asset pointer to serialize.
Returns
This instance.
Reimplemented from FArchiveUObject.
Definition at line 31 of file ArchiveUObject.h.
operator<<() [7/10]
virtual FArchive & FArchive::operator<< (FText & Value) virtual
Serializes an FText value from or into an archive.
Parameters
Ar The archive to serialize from or to.
Value The value to serialize.
Reimplemented from FArchiveUObject.
operator<<() [8/10]
virtual FArchive & FArchiveUObject::operator<< (FWeakObjectPtr & Value) inline override virtual
Serializes FWeakObjectPtr value from or into this archive.
This operator can be implemented by sub-classes that wish to serialize FWeakObjectPtr instances.
Parameters
Value The value to serialize.
Returns
This instance.
Reimplemented from FArchiveUObject.
Definition at line 33 of file ArchiveUObject.h.
operator<<() [9/10]
template<class T> FORCEINLINE FArchive & FArchive::operator<< (TCheckedObjPtr< T > & Value) inline
Serializes a UObject wrapped in a TCheckedObjPtr container, using the above operator, and verifies the serialized object is derived from the correct base class, to prevent illegal casting.
Parameters
Value The value to serialize.
Returns
This instance.
Definition at line 26 of file Archive.h.
operator<<() [10/10]
virtual FArchive & FLinkerSave::operator<< (UObject *& Value) override virtual
Serializes an UObject value from or into this archive.
This operator can be implemented by sub-classes that wish to serialize UObject instances.
Parameters
Value The value to serialize.
Returns
This instance.
Reimplemented from FArchiveUObject.
References FArchive::FArchive().
PopDebugDataString()
virtual void FLinkerSave::PopDebugDataString () inline override virtual
Reimplemented from FArchive.
Definition at line 259 of file LinkerSave.h.
References Saver.
PopSerializedProperty()
virtual void FLinkerSave::PopSerializedProperty (class FProperty * InProperty, const bool bIsEditorOnlyProperty) override virtual
Pop a property that was previously being serialized off the property stack.
Parameters
InProperty Pointer to the property that was previously being serialized
bIsEditorOnlyProperty True if the property is editor only (call FProperty::IsEditorOnlyProperty to work this out, as the archive can't since it can't access CoreUObject types)
Reimplemented from FArchive.
PushDebugDataString()
virtual void FLinkerSave::PushDebugDataString (const FName & DebugData) inline override virtual
Debug stack storage if you want to add data to the archive for usage further down the serialization stack this should be used in conjunction with the FScopeAddDebugData struct.
Reimplemented from FArchive.
Definition at line 258 of file LinkerSave.h.
References Saver.
PushSerializedProperty()
virtual void FLinkerSave::PushSerializedProperty (class FProperty * InProperty, const bool bIsEditorOnlyProperty) override virtual
Push a property that is currently being serialized onto the property stack.
Parameters
InProperty Pointer to the property that is currently being serialized
bIsEditorOnlyProperty True if the property is editor only (call FProperty::IsEditorOnlyProperty to work this out, as the archive can't since it can't access CoreUObject types)
Reimplemented from FArchive.
Seek()
void FLinkerSave::Seek (int64 InPos) virtual
Attempts to set the current offset into backing data storage, this will do nothing if there is no storage.
Reimplemented from FArchive.
Serialize() [1/2]
void FLinker::Serialize (FArchive & Ar)
I/O function.
Parameters
Ar the archive to read/write into
Serialize() [2/2]
void FLinkerSave::Serialize (void * V, int64 Length) virtual
Reimplemented from FArchive.
SerializeBulkData()
virtual bool FLinkerSave::SerializeBulkData (FBulkData & BulkData, const FBulkDataSerializationParams & Params) override virtual
Serialize bulk data.
Parameters
BulkData Bulk data object to serialize
Params Serialization parameters
Returns
true if the bulk data was serialized, false to fallback to default serialization (inline)
Reimplemented from FArchive.
References BulkData, and Params.
SerializeObjectPointer()
void FLinkerSave::SerializeObjectPointer (const FObjectPtr & Value) protected
References Value.
SetDebugSerializationFlags()
virtual void FLinkerSave::SetDebugSerializationFlags (uint32 InCustomFlags) override virtual
Sets the archives custom serialization modifier flags (nothing to do with PortFlags or Custom versions)
Parameters
InCustomFlags the new flags to use for custom serialization
Reimplemented from FArchive.
References SetDebugSerializationFlags().
Referenced by SetDebugSerializationFlags().
SetDeclareRegionForEachAdditionalFile()
void FLinkerSave::SetDeclareRegionForEachAdditionalFile (bool bValue) inline
Sets whether a separate file regions should be declared for each bulkdata.
Definition at line 239 of file LinkerSave.h.
References bDeclareRegionForEachAdditionalFile.
SetFilename()
void FLinkerSave::SetFilename (FStringView InFilename) protected
Set the filename being saved to.
References InFilename.
SetFileRegionsEnabled()
void FLinkerSave::SetFileRegionsEnabled (bool bEnabled) inline
Sets whether file regions will be written or not.
Definition at line 233 of file LinkerSave.h.
References bFileRegionsEnabled.
SetFilterEditorOnly()
virtual void FLinkerSave::SetFilterEditorOnly (bool InFilterEditorOnly) override virtual
Sets a flag indicating that this archive needs to filter editor-only content.
Parameters
InFilterEditorOnly Whether to filter editor-only content.
Reimplemented from FArchive.
References SetFilterEditorOnly().
Referenced by SetFilterEditorOnly().
SetMemoryMapAlignment()
void FLinkerSave::SetMemoryMapAlignment (int64 InAlignment) inline
Set target platform memory map alignment.
A negative value disables memory mapped bulk data.
Definition at line 227 of file LinkerSave.h.
References MemoryMappingAlignment.
SetOutputDevice()
void FLinkerSave::SetOutputDevice (FOutputDevice * InOutputDevice) inline
Definition at line 304 of file LinkerSave.h.
References LogOutput.
SetSaveBulkDataByReference()
void FLinkerSave::SetSaveBulkDataByReference (bool bValue) inline
Sets whether saving bulk data by reference, i.e.
leaving the bulk data payload in the original .uasset file when using EditorDomain.
Definition at line 245 of file LinkerSave.h.
References bSaveBulkDataByReference.
SetSaveBulkDataToSeparateFiles()
void FLinkerSave::SetSaveBulkDataToSeparateFiles (bool bValue) inline
Sets whether bulk data will be stored in the Linker archive (.uasset) or in sepearate files (.ubulk, .m.ubulk, .opt.ubulk) .
Definition at line 251 of file LinkerSave.h.
References bSaveBulkDataToSeparateFiles.
SetSerializedProperty()
virtual void FLinkerSave::SetSerializedProperty (FProperty * InProperty) override virtual
Overrides the property that is currently being serialized.
Note
: You likely want to call PushSerializedProperty/PopSerializedProperty instead
Parameters
InProperty Pointer to the property that is currently being serialized
Reimplemented from FArchive.
SetSerializedPropertyChain()
virtual void FLinkerSave::SetSerializedPropertyChain (const FArchiveSerializedPropertyChain * InSerializedPropertyChain, class FProperty * InSerializedPropertyOverride = nullptr) override virtual
Set the raw serialized property chain for this archive, optionally overriding the serialized property too (or null to use the head of the property chain)
Reimplemented from FArchive.
SetTransientPropertyOverrides()
void FLinkerSave::SetTransientPropertyOverrides (const TMap< UObject *, TSet< FProperty * > > & InTransientPropertyOverrides) inline
Sets the map of overrided properties for each export that should be treated as transient, and nulled out when serializing.
Definition at line 221 of file LinkerSave.h.
References SetTransientPropertyOverrides(), and TransientPropertyOverrides.
Referenced by SetTransientPropertyOverrides().
SetUseUnversionedPropertySerialization()
virtual void FLinkerSave::SetUseUnversionedPropertySerialization (bool bInUseUnversioned) override virtual
Sets whether tagged property serialization should be replaced by faster unversioned serialization.
This assumes writer and reader share the same property definitions.
Reimplemented from FArchive.
References SetUseUnversionedPropertySerialization().
Referenced by SetUseUnversionedPropertySerialization().
ShouldSkipProperty()
virtual bool FLinkerSave::ShouldSkipProperty (const FProperty * InProperty) const override virtual
Checks whether the archive wants to skip the property independent of the other flags.
Reimplemented from FArchive.
StaticType()
FORCEINLINE ELinkerType::Type FLinkerSave::StaticType () inline static
Definition at line 50 of file LinkerSave.h.
References FORCEINLINE, and ELinkerType::Save.
Tell()
int64 FLinkerSave::Tell () virtual
Returns the current location within the backing data storage, which can possibly be passed to Seek later to restore a read/write location.
If this returns -1, there is no backing data storage and Seek will not function.
Reimplemented from FArchive.
References FLinker::Serialize().
TryAssignFileSaver()
bool FLinkerSave::TryAssignFileSaver (FStringView InFilename, bool bForceByteSwapping, bool bInSaveUnversioned = false)
Construct a file saver from IPlatformFile and call AssignSaver with it.
See also
AssignSaver. If the file write fails, the Saver will be set to nullptr and it is a fatal error to call FArchive functions on *this. Caller must handle returnvalue == false and if so destroy *this without calling FArchive functions.
Returns
Whether the creation of the Saver archive succeeded.
References bForceByteSwapping, bInSaveUnversioned, InFilename, and TryAssignFileSaver().
Referenced by TryAssignFileSaver().
UE_DEPRECATED() [1/8]
FLinkerSave::UE_DEPRECATED (5. 5, "GetSerializeContext is not supported. Use FUObjectThreadContext::Get().GetSerializeContext().") override
UE_DEPRECATED() [2/8]
FLinkerSave::UE_DEPRECATED (5. 5, "Use the overload that takes a FBulkDataCookedIndex") & inline
Definition at line 334 of file LinkerSave.h.
References FBulkDataCookedIndex::Default, and GetBulkDataArchive().
UE_DEPRECATED() [3/8]
FLinkerSave::UE_DEPRECATED (5. 5, "Use the overload that takes a FBulkDataCookedIndex") & inline
Definition at line 346 of file LinkerSave.h.
References FBulkDataCookedIndex::Default, and GetMemoryMappedBulkDataArchive().
UE_DEPRECATED() [4/8]
FLinkerSave::UE_DEPRECATED (5. 5, "Use the overload that takes a FBulkDataCookedIndex") & inline
Definition at line 340 of file LinkerSave.h.
References FBulkDataCookedIndex::Default, and GetOptionalBulkDataArchive().
UE_DEPRECATED() [5/8]
FLinkerSave::UE_DEPRECATED (5. 6, "No longer supported, contact Epic if you need this functionality.")
A mapping of package name to generated script SHA keys.
Referenced by UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
UE_DEPRECATED() [6/8]
FLinkerSave::UE_DEPRECATED (5. 6, "Use constructor that takes only Parent and then call AssignFileSaver.")
Constructor for file writer.
References UE_DEPRECATED().
UE_DEPRECATED() [7/8]
FLinkerSave::UE_DEPRECATED (5. 6, "Use constructor that takes only Parent and then call AssignMemorySaver.")
Constructor for memory writer.
References UE_DEPRECATED().
UE_DEPRECATED() [8/8]
FLinkerSave::UE_DEPRECATED (5. 6, "Use constructor that takes only Parent and then call AssignSaver.")
Constructor for custom savers.
The linker assumes ownership of the custom saver.
References UE_DEPRECATED().
UsingCustomVersion()
virtual void FLinkerSave::UsingCustomVersion (const struct FGuid & Guid) override virtual
Registers the custom version to the archive.
This is used to inform the archive that custom version information is about to be stored. There is no effect when the archive is being loaded from.
Parameters
Guid The guid of the custom version. This must have previously been registered with FCustomVersionRegistration.
Reimplemented from FArchive.
References Guid, and UsingCustomVersion().
Referenced by UsingCustomVersion().
Friends And Related Symbol Documentation
operator<< [1/15]
FORCEINLINE friend FArchive & operator<< (FArchive & Ar, ANSICHAR & Value) friend
Serializes an ANSICHAR value from or into an archive.
Parameters
Ar The archive to serialize from or to.
Value The value to serialize.
Definition at line 26 of file Archive.h.
operator<< [2/15]
FORCEINLINE friend FArchive & operator<< (FArchive & Ar, bool & D) friend
Definition at line 26 of file Archive.h.
operator<< [3/15]
FORCEINLINE friend FArchive & operator<< (FArchive & Ar, double & Value) friend
Serializes a double precision floating point value from or into an archive.
Parameters
Ar The archive to serialize from or to.
Value The value to serialize.
Definition at line 26 of file Archive.h.
operator<< [4/15]
FORCEINLINE friend FArchive & operator<< (FArchive & Ar, float & Value) friend
Serializes a single precision floating point value from or into an archive.
Parameters
Ar The archive to serialize from or to.
Value The value to serialize.
Definition at line 26 of file Archive.h.
operator<< [5/15]
FArchive & operator<< (FArchive & Ar, FString & Value) friend
Serializes an FString value from or into an archive.
Parameters
Ar The archive to serialize from or to.
Value The value to serialize.
operator<< [6/15]
FORCEINLINE friend FArchive & operator<< (FArchive & Ar, int16 & Value) friend
Serializes a signed 16-bit integer value from or into an archive.
Parameters
Ar The archive to serialize from or to.
Value The value to serialize.
Definition at line 26 of file Archive.h.
operator<< [7/15]
FORCEINLINE friend FArchive & operator<< (FArchive & Ar, int32 & Value) friend
Serializes a signed 32-bit integer value from or into an archive.
Parameters
Ar The archive to serialize from or to.
Value The value to serialize.
Definition at line 26 of file Archive.h.
operator<< [8/15]
FArchive & operator<< (FArchive & Ar, int64 & Value) friend
Serializes a signed 64-bit integer value from or into an archive.
Parameters
Ar The archive to serialize from or to.
Value The value to serialize.
Definition at line 26 of file Archive.h.
operator<< [9/15]
FORCEINLINE friend FArchive & operator<< (FArchive & Ar, int8 & Value) friend
Serializes a signed 8-bit integer value from or into an archive.
Parameters
Ar The archive to serialize from or to.
Value The value to serialize.
Definition at line 26 of file Archive.h.
operator<< [10/15]
FORCEINLINE friend FArchive & operator<< (FArchive & Ar, uint16 & Value) friend
Serializes an unsigned 16-bit integer value from or into an archive.
Parameters
Ar The archive to serialize from or to.
Value The value to serialize.
Definition at line 26 of file Archive.h.
operator<< [11/15]
FORCEINLINE friend FArchive & operator<< (FArchive & Ar, uint32 & Value) friend
Serializes an unsigned 32-bit integer value from or into an archive.
Parameters
Ar The archive to serialize from or to.
Value The value to serialize.
Definition at line 26 of file Archive.h.
operator<< [12/15]
FORCEINLINE friend FArchive & operator<< (FArchive & Ar, uint64 & Value) friend
Serializes a unsigned 64-bit integer value from or into an archive.
Parameters
Ar The archive to serialize from or to.
Value The value to serialize.
Definition at line 26 of file Archive.h.
operator<< [13/15]
FORCEINLINE friend FArchive & operator<< (FArchive & Ar, uint8 & Value) friend
Serializes an unsigned 8-bit integer value from or into an archive.
Parameters
Ar The archive to serialize from or to.
Value The value to serialize.
Definition at line 26 of file Archive.h.
operator<< [14/15]
FORCEINLINE friend FArchive & operator<< (FArchive & Ar, UTF32CHAR & Value) friend
Serializes a UTF32CHAR value from or into an archive.
Parameters
Ar The archive to serialize from or to.
Value The value to serialize.
Definition at line 26 of file Archive.h.
operator<< [15/15]
FORCEINLINE friend FArchive & operator<< (FArchive & Ar, WIDECHAR & Value) friend
Serializes a WIDECHAR value from or into an archive.
Parameters
Ar The archive to serialize from or to.
Value The value to serialize.
Definition at line 26 of file Archive.h.
Field Documentation
AdditionalDataToAppend
TArray<AdditionalDataCallback> FLinkerSave::AdditionalDataToAppend
Array of callbacks that will be invoked when it is possible to serialize out data to the end of the output file.
Definition at line 101 of file LinkerSave.h.
bDeclareRegionForEachAdditionalFile
bool FLinkerSave::bDeclareRegionForEachAdditionalFile = false private
Whether a separate file region should be declared for each bulkdata.
Definition at line 392 of file LinkerSave.h.
Referenced by SetDeclareRegionForEachAdditionalFile().
bFileRegionsEnabled
bool FLinkerSave::bFileRegionsEnabled = false private
Whether file regions are enabled.
Definition at line 390 of file LinkerSave.h.
Referenced by SetFileRegionsEnabled().
bForceByteSwapping [1/3]
const TCHAR bool FLinkerSave::bForceByteSwapping
Definition at line 147 of file LinkerSave.h.
Referenced by AssignMemorySaver(), AssignSaver(), AssignSaverInternal(), and TryAssignFileSaver().
bForceByteSwapping [2/3]
bool FLinkerSave::bForceByteSwapping
Definition at line 150 of file LinkerSave.h.
bForceByteSwapping [3/3]
FArchive bool FLinkerSave::bForceByteSwapping
Definition at line 153 of file LinkerSave.h.
bInSaveUnversioned [1/3]
const TCHAR bool bool FLinkerSave::bInSaveUnversioned = false)
Definition at line 147 of file LinkerSave.h.
Referenced by AssignMemorySaver(), AssignSaver(), AssignSaverInternal(), and TryAssignFileSaver().
bInSaveUnversioned [2/3]
bool bool FLinkerSave::bInSaveUnversioned = false)
Definition at line 150 of file LinkerSave.h.
bInSaveUnversioned [3/3]
FArchive bool bool FLinkerSave::bInSaveUnversioned = false)
Definition at line 153 of file LinkerSave.h.
bIsWritingHeaderSoftObjectPaths
bool FLinkerSave::bIsWritingHeaderSoftObjectPaths = false
Flag that indicate if we are currently serializing the package header soft object paths.
Used to disable mapping while serializing the header itself.
Definition at line 79 of file LinkerSave.h.
bProceduralSave
bool FLinkerSave::bProceduralSave = false
Set to true when the package is being saved due to a procedural save.
Any save without the the possibility of user-generated edits to the package is a procedural save (Cooking, EditorDomain). This allows us to execute transforms that only need to be executed in response to new user data.
Definition at line 108 of file LinkerSave.h.
bRehydratePayloads
bool FLinkerSave::bRehydratePayloads = false
When set to true, payloads that are currently virtualized should be downloaded and stored locally with the package.
Definition at line 118 of file LinkerSave.h.
bSaveBulkDataByReference
bool FLinkerSave::bSaveBulkDataByReference = false private
Whether saving bulk data by reference.
Definition at line 394 of file LinkerSave.h.
Referenced by SetSaveBulkDataByReference().
bSaveBulkDataToSeparateFiles
bool FLinkerSave::bSaveBulkDataToSeparateFiles = false private
Whether saving bulk data to separate files.
Definition at line 396 of file LinkerSave.h.
Referenced by SetSaveBulkDataToSeparateFiles().
BulkDataAr
TMap<FBulkDataCookedIndex, TUniquePtr<FFileRegionMemoryWriter> > FLinkerSave::BulkDataAr private
Default bulk data archive.
Definition at line 377 of file LinkerSave.h.
bUpdatingLoadedPath
bool FLinkerSave::bUpdatingLoadedPath = false
Set to true when the LoadedPath of the package being saved is being updated.
This allows us to update the in-memory package when it is saved in editor to match its new save file. This is used e.g. to decide whether to update the in-memory file offsets for BulkData.
Definition at line 115 of file LinkerSave.h.
CellIndicesMap
TMap<Verse::VCell*, FPackageIndex> FLinkerSave::CellIndicesMap
Definition at line 67 of file LinkerSave.h.
CurrentlySavingExport
FPackageIndex FLinkerSave::CurrentlySavingExport
Definition at line 61 of file LinkerSave.h.
CurrentlySavingExportObject
UObject* FLinkerSave::CurrentlySavingExportObject = nullptr
Definition at line 62 of file LinkerSave.h.
DepListForErrorChecking
TArray<FPackageIndex> FLinkerSave::DepListForErrorChecking
Definition at line 63 of file LinkerSave.h.
Filename
FString FLinkerSave::Filename private
The name of the file for this package.
Definition at line 384 of file LinkerSave.h.
FileRegions
TArray<FFileRegion> FLinkerSave::FileRegions
Definition at line 84 of file LinkerSave.h.
InFilename
const TCHAR* FLinkerSave::InFilename
Definition at line 147 of file LinkerSave.h.
Referenced by SetFilename(), and TryAssignFileSaver().
InSaver
FArchive* FLinkerSave::InSaver
Definition at line 153 of file LinkerSave.h.
Referenced by AssignSaver(), and AssignSaverInternal().
LogOutput
FOutputDevice* FLinkerSave::LogOutput = nullptr private
Optional log output to bubble errors back up.
Definition at line 364 of file LinkerSave.h.
Referenced by GetOutputDevice(), and SetOutputDevice().
MemoryMappedBulkDataAr
TMap<FBulkDataCookedIndex, TUniquePtr<FFileRegionMemoryWriter> > FLinkerSave::MemoryMappedBulkDataAr private
Memory mapped bulk data archive.
Definition at line 381 of file LinkerSave.h.
MemoryMappingAlignment
int64 FLinkerSave::MemoryMappingAlignment = -1 private
Alignment for memory mapped data .
Definition at line 388 of file LinkerSave.h.
Referenced by SetMemoryMapAlignment().
NameIndices
TMap<FNameEntryId, int32> FLinkerSave::NameIndices
Definition at line 73 of file LinkerSave.h.
ObjectIndicesMap
TMap<TObjectPtr<UObject>, FPackageIndex> FLinkerSave::ObjectIndicesMap
Index array - location of the resource for a UObject is stored in the ObjectIndices array using the UObject's Index.
Definition at line 66 of file LinkerSave.h.
OptionalBulkDataAr
TMap<FBulkDataCookedIndex, TUniquePtr<FFileRegionMemoryWriter> > FLinkerSave::OptionalBulkDataAr private
Optional bulk data archive.
Definition at line 379 of file LinkerSave.h.
PackagesToScriptSHAMap
TArray<uint8> FLinkerSave::PackagesToScriptSHAMap
Definition at line 143 of file LinkerSave.h.
PackageTrailerBuilder
TUniquePtr<UE::FPackageTrailerBuilder> FLinkerSave::PackageTrailerBuilder
Gathers all payloads while save the package, so that they can be stored in a single data structure.
See also
FPackageTrailer
Definition at line 130 of file LinkerSave.h.
PostSaveCallbacks
TArray<TUniqueFunction<void(const FPackagePath& PackagePath, FObjectPostSaveContext ObjectSaveContext)> > FLinkerSave::PostSaveCallbacks
Array of callbacks that will be invoked when the package has successfully saved to disk.
The callbacks will not be invoked if the package fails to save for some reason. Unlike subscribing to the UPackage::PackageSavedEvent this callback allows custom data via lambda capture.
Parameters
PackagePath The path of the package
Definition at line 139 of file LinkerSave.h.
SaveContext
TRefCountPtr<FUObjectSerializeContext> FLinkerSave::SaveContext
Save context associated with this linker.
Definition at line 82 of file LinkerSave.h.
Saver
FArchive* FLinkerSave::Saver = nullptr
The archive that actually writes the data to disk.
Definition at line 59 of file LinkerSave.h.
Referenced by PopDebugDataString(), and PushDebugDataString().
SearchableNamesObjectMap
TMap<const UObject *, TArray<FName> > FLinkerSave::SearchableNamesObjectMap
List of Searchable Names, by object containing them.
This gets turned into package indices later
Definition at line 70 of file LinkerSave.h.
SerializedBulkData
TMap<FBulkData*, int32> FLinkerSave::SerializedBulkData private
Map from bulk data object to resource index.
Definition at line 373 of file LinkerSave.h.
SidecarDataToAppend
TArray<FSidecarStorageInfo> FLinkerSave::SidecarDataToAppend
Used by FEditorBulkData to add payloads to be added to the payload sidecar file (currently an experimental feature)
Definition at line 127 of file LinkerSave.h.
SoftObjectPathIndices
TMap<FSoftObjectPath, int32> FLinkerSave::SoftObjectPathIndices
Definition at line 76 of file LinkerSave.h.
TransientPropertyOverrides
const TMap<UObject*, TSet<FProperty*> >* FLinkerSave::TransientPropertyOverrides = nullptr private
Definition at line 386 of file LinkerSave.h.
Referenced by SetTransientPropertyOverrides().
The documentation for this class was generated from the following file:
Runtime/CoreUObject/Public/UObject/LinkerSave.h