Unreal Engine 5.6 C++ API: UBlueprintMapLibrary Class Reference
UBlueprintMapLibrary Class Reference
#include "BlueprintMapLibrary.h"
Private Member Functions
DECLARE_FUNCTION (execMap_Add)
DECLARE_FUNCTION (execMap_Clear)
DECLARE_FUNCTION (execMap_Contains)
DECLARE_FUNCTION (execMap_Find)
DECLARE_FUNCTION (execMap_GetKeyValueByIndex)
DECLARE_FUNCTION (execMap_GetLastIndex)
DECLARE_FUNCTION (execMap_IsEmpty)
DECLARE_FUNCTION (execMap_IsNotEmpty)
DECLARE_FUNCTION (execMap_Keys)
DECLARE_FUNCTION (execMap_Length)
DECLARE_FUNCTION (execMap_Remove)
DECLARE_FUNCTION (execMap_Values)
DECLARE_FUNCTION (execSetMapPropertyByName)
GENERATED_BODY() public UFUNCTION ()
Adds a key and value to the map.
UFUNCTION ()
Finds the value associated with the provided Key.
UFUNCTION ()
Checks whether key is in a provided Map.
UFUNCTION ()
Outputs an array of all keys present in the map.
UFUNCTION ()
Outputs an array of all values present in the map.
UFUNCTION ()
Determines the number of entries in a provided Map.
UFUNCTION ()
Check if the map does not have any entires.
UFUNCTION ()
Check if the map has any entries.
UFUNCTION ()
Clears a map of all entries, resetting it to empty.
UFUNCTION ()
Given a map and an index, returns a copy of the key and value found at that index.
UFUNCTION ()
Determines the last valid index for a map.
UFUNCTION ()) static 1 void SetMapPropertyByName(UObject *Object
Not exposed to users.
Static Private Member Functions
static void GenericMap_Add (const void *TargetMap, const FMapProperty *MapProperty, const void *KeyPtr, const void *ValuePtr)
static void GenericMap_Clear (const void *TargetMap, const FMapProperty *MapProperty)
static bool GenericMap_Find (const void *TargetMap, const FMapProperty *MapProperty, const void *KeyPtr, void *ValuePtr)
static void GenericMap_GetKeyValueByIndex (const void *TargetMap, const FMapProperty *MapProperty, int32 Index, void *KeyPtr, void *ValuePtr)
static int32 GenericMap_GetLastIndex (const void *TargetMap, const FMapProperty *MapProperty)
static bool GenericMap_IsEmpty (const void *TargetMap, const FMapProperty *MapProperty)
static bool GenericMap_IsNotEmpty (const void *TargetMap, const FMapProperty *MapProperty)
static void GenericMap_Keys (const void *MapAddr, const FMapProperty *MapProperty, const void *ArrayAddr, const FArrayProperty *ArrayProperty)
static int32 GenericMap_Length (const void *TargetMap, const FMapProperty *MapProperty)
static bool GenericMap_Remove (const void *TargetMap, const FMapProperty *MapProperty, const void *KeyPtr)
static void GenericMap_SetMapPropertyByName (UObject *OwnerObject, FName MapPropertyName, const void *SrcMapAddr)
static void GenericMap_Values (const void *MapAddr, const FMapProperty *MapProperty, const void *ArrayAddr, const FArrayProperty *ArrayProperty)
Private Attributes
GENERATED_BODY() public Category
Category
FName PropertyName
FName const TMap< int32, int32 > & Value
Static Private Attributes
static constexpr int32 MaxSupportedMapSize = TNumericLimits<int32>::Max()
Detailed Description
Definition at line 14 of file BlueprintMapLibrary.h.
Member Function Documentation
DECLARE_FUNCTION() [1/13]
UBlueprintMapLibrary::DECLARE_FUNCTION (execMap_Add) inline private
Definition at line 142 of file BlueprintMapLibrary.h.
References CastField(), DECLARE_FUNCTION(), FProperty::DestroyValue(), FMemory_Alloca, GenericMap_Add(), FProperty::GetElementSize(), FProperty::InitializeValue(), MapProperty, P_FINISH, P_NATIVE_BEGIN, and P_NATIVE_END.
Referenced by DECLARE_FUNCTION().
DECLARE_FUNCTION() [2/13]
UBlueprintMapLibrary::DECLARE_FUNCTION (execMap_Clear) inline private
Definition at line 407 of file BlueprintMapLibrary.h.
References CastField(), GenericMap_Clear(), MapProperty, P_FINISH, P_NATIVE_BEGIN, and P_NATIVE_END.
DECLARE_FUNCTION() [3/13]
UBlueprintMapLibrary::DECLARE_FUNCTION (execMap_Contains) inline private
Definition at line 323 of file BlueprintMapLibrary.h.
References CastField(), FProperty::DestroyValue(), FMemory_Alloca, GenericMap_Find(), FProperty::GetElementSize(), FProperty::InitializeValue(), MapProperty, P_FINISH, P_NATIVE_BEGIN, P_NATIVE_END, and RESULT_PARAM.
DECLARE_FUNCTION() [4/13]
UBlueprintMapLibrary::DECLARE_FUNCTION (execMap_Find) inline private
Definition at line 213 of file BlueprintMapLibrary.h.
References CastField(), FProperty::DestroyValue(), FMemory_Alloca, GenericMap_Find(), FProperty::GetElementSize(), FProperty::InitializeValue(), FFieldClass::IsChildOf(), MapProperty, P_FINISH, P_NATIVE_BEGIN, P_NATIVE_END, and RESULT_PARAM.
DECLARE_FUNCTION() [5/13]
UBlueprintMapLibrary::DECLARE_FUNCTION (execMap_GetKeyValueByIndex) inline private
Definition at line 440 of file BlueprintMapLibrary.h.
References CastField(), FProperty::DestroyValue(), FMemory_Alloca, GenericMap_GetKeyValueByIndex(), FField::GetClass(), FProperty::GetElementSize(), FProperty::InitializeValue(), FFieldClass::IsChildOf(), MapProperty, P_FINISH, P_GET_PROPERTY, P_NATIVE_BEGIN, and P_NATIVE_END.
DECLARE_FUNCTION() [6/13]
UBlueprintMapLibrary::DECLARE_FUNCTION (execMap_GetLastIndex) inline private
Definition at line 502 of file BlueprintMapLibrary.h.
References CastField(), GenericMap_GetLastIndex(), MapProperty, P_FINISH, P_NATIVE_BEGIN, P_NATIVE_END, and RESULT_PARAM.
DECLARE_FUNCTION() [7/13]
UBlueprintMapLibrary::DECLARE_FUNCTION (execMap_IsEmpty) inline private
Definition at line 371 of file BlueprintMapLibrary.h.
References CastField(), GenericMap_IsEmpty(), MapProperty, P_FINISH, P_NATIVE_BEGIN, P_NATIVE_END, and RESULT_PARAM.
DECLARE_FUNCTION() [8/13]
UBlueprintMapLibrary::DECLARE_FUNCTION (execMap_IsNotEmpty) inline private
Definition at line 389 of file BlueprintMapLibrary.h.
References CastField(), GenericMap_IsNotEmpty(), MapProperty, P_FINISH, P_NATIVE_BEGIN, P_NATIVE_END, and RESULT_PARAM.
DECLARE_FUNCTION() [9/13]
UBlueprintMapLibrary::DECLARE_FUNCTION (execMap_Keys) inline private
Definition at line 266 of file BlueprintMapLibrary.h.
References ArrayProperty, CastField(), GenericMap_Keys(), MapProperty, P_FINISH, P_NATIVE_BEGIN, and P_NATIVE_END.
DECLARE_FUNCTION() [10/13]
UBlueprintMapLibrary::DECLARE_FUNCTION (execMap_Length) inline private
Definition at line 353 of file BlueprintMapLibrary.h.
References CastField(), GenericMap_Length(), MapProperty, P_FINISH, P_NATIVE_BEGIN, P_NATIVE_END, and RESULT_PARAM.
DECLARE_FUNCTION() [11/13]
UBlueprintMapLibrary::DECLARE_FUNCTION (execMap_Remove) inline private
Definition at line 183 of file BlueprintMapLibrary.h.
References CastField(), FProperty::DestroyValue(), FMemory_Alloca, GenericMap_Remove(), FProperty::GetElementSize(), FProperty::InitializeValue(), MapProperty, P_FINISH, P_NATIVE_BEGIN, P_NATIVE_END, and RESULT_PARAM.
DECLARE_FUNCTION() [12/13]
UBlueprintMapLibrary::DECLARE_FUNCTION (execMap_Values) inline private
Definition at line 295 of file BlueprintMapLibrary.h.
References ArrayProperty, CastField(), GenericMap_Values(), MapProperty, P_FINISH, P_NATIVE_BEGIN, and P_NATIVE_END.
DECLARE_FUNCTION() [13/13]
UBlueprintMapLibrary::DECLARE_FUNCTION (execSetMapPropertyByName) inline private
Definition at line 425 of file BlueprintMapLibrary.h.
References GenericMap_SetMapPropertyByName(), P_FINISH, P_GET_OBJECT, P_GET_PROPERTY, P_NATIVE_BEGIN, and P_NATIVE_END.
GenericMap_Add()
void UBlueprintMapLibrary::GenericMap_Add (const void * TargetMap, const FMapProperty * MapProperty, const void * KeyPtr, const void * ValuePtr) static private
References MapProperty.
Referenced by DECLARE_FUNCTION().
GenericMap_Clear()
void UBlueprintMapLibrary::GenericMap_Clear (const void * TargetMap, const FMapProperty * MapProperty) static private
References MapProperty.
Referenced by DECLARE_FUNCTION().
GenericMap_Find()
bool UBlueprintMapLibrary::GenericMap_Find (const void * TargetMap, const FMapProperty * MapProperty, const void * KeyPtr, void * ValuePtr) static private
References MapProperty.
Referenced by DECLARE_FUNCTION(), and DECLARE_FUNCTION().
GenericMap_GetKeyValueByIndex()
void UBlueprintMapLibrary::GenericMap_GetKeyValueByIndex (const void * TargetMap, const FMapProperty * MapProperty, int32 Index, void * KeyPtr, void * ValuePtr) static private
References MapProperty.
Referenced by DECLARE_FUNCTION().
GenericMap_GetLastIndex()
int32 UBlueprintMapLibrary::GenericMap_GetLastIndex (const void * TargetMap, const FMapProperty * MapProperty) static private
References MapProperty.
Referenced by DECLARE_FUNCTION().
GenericMap_IsEmpty()
bool UBlueprintMapLibrary::GenericMap_IsEmpty (const void * TargetMap, const FMapProperty * MapProperty) static private
References MapProperty.
Referenced by DECLARE_FUNCTION().
GenericMap_IsNotEmpty()
bool UBlueprintMapLibrary::GenericMap_IsNotEmpty (const void * TargetMap, const FMapProperty * MapProperty) static private
References MapProperty.
Referenced by DECLARE_FUNCTION().
GenericMap_Keys()
void UBlueprintMapLibrary::GenericMap_Keys (const void * MapAddr, const FMapProperty * MapProperty, const void * ArrayAddr, const FArrayProperty * ArrayProperty) static private
References ArrayProperty, and MapProperty.
Referenced by DECLARE_FUNCTION().
GenericMap_Length()
int32 UBlueprintMapLibrary::GenericMap_Length (const void * TargetMap, const FMapProperty * MapProperty) static private
References MapProperty.
Referenced by DECLARE_FUNCTION().
GenericMap_Remove()
bool UBlueprintMapLibrary::GenericMap_Remove (const void * TargetMap, const FMapProperty * MapProperty, const void * KeyPtr) static private
References MapProperty.
Referenced by DECLARE_FUNCTION().
GenericMap_SetMapPropertyByName()
void UBlueprintMapLibrary::GenericMap_SetMapPropertyByName (UObject * OwnerObject, FName MapPropertyName, const void * SrcMapAddr) static private
Referenced by DECLARE_FUNCTION().
GenericMap_Values()
void UBlueprintMapLibrary::GenericMap_Values (const void * MapAddr, const FMapProperty * MapProperty, const void * ArrayAddr, const FArrayProperty * ArrayProperty) static private
References ArrayProperty, and MapProperty.
Referenced by DECLARE_FUNCTION().
UFUNCTION() [1/12]
GENERATED_BODY() public UBlueprintMapLibrary::UFUNCTION () private
Adds a key and value to the map.
If something already uses the provided key it will be overwritten with the new value. After calling Key is guaranteed to be associated with Value until a subsequent mutation of the Map.
Parameters
TargetMap The map to add the key and value to
Key The key that will be used to look the value up
Value The value to be retrieved later Removes a key and its associated value from the map.
TargetMap The map to remove the key and its associated value from
Key The key that will be used to look the value up
Returns
True if an item was removed (False indicates nothing in the map uses the provided key)
Referenced by UFUNCTION(), and UFUNCTION().
UFUNCTION() [2/12]
UBlueprintMapLibrary::UFUNCTION () private
Finds the value associated with the provided Key.
Parameters
TargetMap The map to perform the lookup on
Key The key that will be used to look the value up
Value The value associated with the key, default constructed if key was not found
Returns
True if an item was found (False indicates nothing in the map uses the provided key)
UFUNCTION() [3/12]
UBlueprintMapLibrary::UFUNCTION () private
Checks whether key is in a provided Map.
Parameters
TargetMap The map to perform the lookup on
Key The key that will be used to lookup
Returns
True if an item was found (False indicates nothing in the map uses the provided key)
References Category, Key, meta, and UFUNCTION().
UFUNCTION() [4/12]
UBlueprintMapLibrary::UFUNCTION () private
Outputs an array of all keys present in the map.
Parameters
TargetMap The map to get the list of keys from
Keys All keys present in the map
References Category, meta, and UFUNCTION().
UFUNCTION() [5/12]
UBlueprintMapLibrary::UFUNCTION () private
Outputs an array of all values present in the map.
Parameters
TargetMap The map to get the list of values from
Values All values present in the map
References Category, meta, and UFUNCTION().
UFUNCTION() [6/12]
UBlueprintMapLibrary::UFUNCTION () private
Determines the number of entries in a provided Map.
Parameters
TargetMap The map in question
Returns
The number of entries in the map
References Category, Keywords, meta, and UFUNCTION().
UFUNCTION() [7/12]
UBlueprintMapLibrary::UFUNCTION () private
Check if the map does not have any entires.
Parameters
TargetMap The map to check
Returns
A boolean indicating if the map has any entires
References Category, meta, and UFUNCTION().
UFUNCTION() [8/12]
UBlueprintMapLibrary::UFUNCTION () private
Check if the map has any entries.
Parameters
TargetMap The map to check
Returns
A boolean indicating if the map has any entires
References Category, meta, and UFUNCTION().
UFUNCTION() [9/12]
UBlueprintMapLibrary::UFUNCTION () private
Clears a map of all entries, resetting it to empty.
Parameters
TargetMap The map to clear
References Category, meta, and UFUNCTION().
UFUNCTION() [10/12]
UBlueprintMapLibrary::UFUNCTION () private
Given a map and an index, returns a copy of the key and value found at that index.
Index may differ from the order in which they were added. This function is implemented for the purpose of iterating maps by index.
Parameters
TargetMap The map to get a key & value from
Index The index in the map to get the key & value
Key A copy of the key stored in the map at the index
Value A copy of the value stored in the map at the index
References Category, Key, meta, UFUNCTION(), and Value.
UFUNCTION() [11/12]
UBlueprintMapLibrary::UFUNCTION () private
Determines the last valid index for a map.
Parameters
TargetMap The map in question
Returns
The number of entries in the map
References Category, meta, and UFUNCTION().
UFUNCTION() [12/12]
UBlueprintMapLibrary::UFUNCTION () private
Not exposed to users.
Supports setting a map property on an object by name.
References meta, and UFUNCTION().
Field Documentation
Category [1/2]
GENERATED_BODY() public UBlueprintMapLibrary::Category private
Initial value:
= "Utilities|Map")
    static 1 bool Map_Remove(const TMap<int32, int32>& TargetMap, const int32& Key)
Definition at line 37 of file BlueprintMapLibrary.h.
Referenced by UFUNCTION().
Category [2/2]
UBlueprintMapLibrary::Category private
Initial value:
= "Utilities|Map")
    static 1 bool Map_Find(const TMap<int32, int32>& TargetMap, const int32& Key, int32& Value)
Definition at line 48 of file BlueprintMapLibrary.h.
MaxSupportedMapSize
int32 UBlueprintMapLibrary::MaxSupportedMapSize = TNumericLimits<int32>::Max() static constexpr private
Definition at line 534 of file BlueprintMapLibrary.h.
PropertyName
FName UBlueprintMapLibrary::PropertyName private
Definition at line 118 of file BlueprintMapLibrary.h.
Value
FName const TMap<int32, int32>& UBlueprintMapLibrary::Value private
Definition at line 118 of file BlueprintMapLibrary.h.
Referenced by UFUNCTION().
The documentation for this class was generated from the following file:
Runtime/Engine/Classes/Kismet/BlueprintMapLibrary.h