Unreal Engine 5.6 C++ API: TCbBuffer< ViewType > Class Template Reference
TCbBuffer< ViewType > Class Template Reference
A wrapper that holds a reference to the buffer that contains its compact binary value.
#include "CompactBinary.h"
Public Member Functions
TCbBuffer ()=default
Construct a default value.
TCbBuffer (const ViewType &Value, FSharedBuffer OuterBuffer)
Construct a value that holds a reference to the buffer that contains it.
template<typename OtherViewType>
TCbBuffer (const ViewType &Value, TCbBuffer< OtherViewType > OuterBuffer)
Construct a value that holds a reference to the buffer of the outer that contains it.
TCbBuffer (FSharedBuffer ValueBuffer, ECbFieldType Type=ECbFieldType::HasFieldType)
Construct a value from a pointer to its data and an optional externally-provided type.
const ViewType & AsView () const
Returns the value as a view.
FCbFieldIterator begin () const
DO NOT USE DIRECTLY.
FCbFieldIterator CreateIterator () const
Create an iterator for the fields of an array or object, otherwise an empty iterator.
constexpr FCbIteratorSentinel end () const
FSharedBuffer GetOuterBuffer () &&
const FSharedBuffer & GetOuterBuffer () const &
Returns the outer buffer (if any) that contains this value.
bool IsOwned () const
Whether this reference has ownership of the memory in its buffer.
void MakeOwned ()
Clone the value, if necessary, to a buffer that this reference has ownership of.
FCbField operator[] (FUtf8StringView Name) const
Find a field of an object by case-sensitive name comparison, otherwise a field with no value.
void Reset ()
Reset this to a default value and null buffer.
Private Attributes
FSharedBuffer Buffer
Friends
template<typename OtherType>
class TCbBuffer
Detailed Description
template<typename ViewType>
class TCbBuffer< ViewType >
A wrapper that holds a reference to the buffer that contains its compact binary value.
Definition at line 1112 of file CompactBinary.h.
Constructor & Destructor Documentation
TCbBuffer() [1/4]
template<typename ViewType> TCbBuffer< ViewType >::TCbBuffer () default
Construct a default value.
TCbBuffer() [2/4]
template<typename ViewType> TCbBuffer< ViewType >::TCbBuffer (FSharedBuffer ValueBuffer, ECbFieldType Type = ECbFieldType::HasFieldType) inline explicit
Construct a value from a pointer to its data and an optional externally-provided type.
Parameters
ValueBuffer A buffer that exactly contains the value.
Type HasFieldType means that ValueBuffer contains the type. Otherwise, use the given type.
Definition at line 1124 of file CompactBinary.h.
References Buffer, check, TMemoryView< DataType >::Contains(), FSharedBuffer::GetData(), FSharedBuffer::GetView(), HasFieldType, and MoveTemp().
TCbBuffer() [3/4]
template<typename ViewType> TCbBuffer< ViewType >::TCbBuffer (const ViewType & Value, FSharedBuffer OuterBuffer) inline
Construct a value that holds a reference to the buffer that contains it.
Definition at line 1135 of file CompactBinary.h.
References Buffer, check, TMemoryView< DataType >::Contains(), FSharedBuffer::GetView(), MoveTemp(), and Value.
TCbBuffer() [4/4]
template<typename ViewType> template<typename OtherViewType> TCbBuffer< ViewType >::TCbBuffer (const ViewType & Value, TCbBuffer< OtherViewType > OuterBuffer) inline
Construct a value that holds a reference to the buffer of the outer that contains it.
Definition at line 1147 of file CompactBinary.h.
References TCbBuffer, Buffer, MoveTemp(), and Value.
Member Function Documentation
AsView()
template<typename ViewType> const ViewType & TCbBuffer< ViewType >::AsView () const inline nodiscard
Returns the value as a view.
Definition at line 1171 of file CompactBinary.h.
begin()
template<typename ViewType> FCbFieldIterator TCbBuffer< ViewType >::begin () const inline
DO NOT USE DIRECTLY.
These functions enable range-based for loop support.
Definition at line 1357 of file CompactBinary.h.
References CreateIterator().
CreateIterator()
template<typename ViewType> FCbFieldIterator TCbBuffer< ViewType >::CreateIterator () const inline nodiscard
Create an iterator for the fields of an array or object, otherwise an empty iterator.
Definition at line 1347 of file CompactBinary.h.
References GetOuterBuffer(), and FCbFieldIterator::MakeRangeView().
Referenced by begin().
end()
template<typename ViewType> FCbIteratorSentinel TCbBuffer< ViewType >::end () const inline constexpr
Definition at line 1190 of file CompactBinary.h.
GetOuterBuffer() [1/2]
template<typename ViewType> FSharedBuffer TCbBuffer< ViewType >::GetOuterBuffer () && inline nodiscard
Definition at line 1180 of file CompactBinary.h.
References Buffer, and MoveTemp().
GetOuterBuffer() [2/2]
template<typename ViewType> const FSharedBuffer & TCbBuffer< ViewType >::GetOuterBuffer () const & inline nodiscard
Returns the outer buffer (if any) that contains this value.
The outer buffer might contain other data before and/or after this value. Use GetBuffer to request a buffer that exactly contains this value, or TryGetView for a contiguous view.
Definition at line 1179 of file CompactBinary.h.
References Buffer.
Referenced by CreateIterator(), and operator[]().
IsOwned()
template<typename ViewType> bool TCbBuffer< ViewType >::IsOwned () const inline
Whether this reference has ownership of the memory in its buffer.
Definition at line 1156 of file CompactBinary.h.
References Buffer.
Referenced by MakeOwned().
MakeOwned()
template<typename ViewType> void TCbBuffer< ViewType >::MakeOwned () inline
Clone the value, if necessary, to a buffer that this reference has ownership of.
Definition at line 1159 of file CompactBinary.h.
References FUniqueBuffer::Alloc(), Buffer, FUniqueBuffer::GetData(), IsOwned(), and FUniqueBuffer::MoveToShared().
operator[]()
template<typename ViewType> FCbField TCbBuffer< ViewType >::operator[] (FUtf8StringView Name) const inline nodiscard
Find a field of an object by case-sensitive name comparison, otherwise a field with no value.
Definition at line 1273 of file CompactBinary.h.
References GetOuterBuffer(), TCbBufferFactory< FCbField, FCbFieldView >::MakeView(), and Name.
Reset()
template<typename ViewType> void TCbBuffer< ViewType >::Reset () inline
Reset this to a default value and null buffer.
Definition at line 1153 of file CompactBinary.h.
References TCbBuffer.
Friends And Related Symbol Documentation
TCbBuffer
template<typename ViewType> template<typename OtherType> friend class TCbBuffer friend
Definition at line 1194 of file CompactBinary.h.
References TCbBuffer.
Referenced by TCbBuffer(), TCbBuffer, and Reset().
Field Documentation
Buffer
template<typename ViewType> FSharedBuffer TCbBuffer< ViewType >::Buffer private
Definition at line 1196 of file CompactBinary.h.
Referenced by TCbBuffer(), TCbBuffer(), TCbBuffer(), GetOuterBuffer(), GetOuterBuffer(), IsOwned(), and MakeOwned().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Serialization/CompactBinary.h