Unreal Engine 5.6 C++ API: UPhysicsConstraintComponent Class Reference
UPhysicsConstraintComponent Class Reference
#include "PhysicsConstraintComponent.h"
Public Member Functions
virtual void BeginDestroy () override
Called before destroying the object.
virtual void CheckForErrors () override
Function that gets called from within Map_Check to allow this actor component to check itself for any potential errors and register them with map check dialog.
virtual void EndPlay (const EEndPlayReason::Type EndPlayReason) override
Ends gameplay for this component.
FBox GetBodyBox (EConstraintFrame::Type Frame) const
Get body bounding box.
FTransform GetBodyTransform (EConstraintFrame::Type Frame) const
Get the body frame.
void InitComponentConstraint ()
Initialize the frames and creates constraint.
virtual void InitializeComponent () override
Initializes the component.
virtual void OnRegister () override
Called when a component is registered, after Scene is set, but before CreateRenderState_Concurrent or OnCreatePhysicsState are called.
virtual void OnUnregister () override
Called when a component is unregistered.
virtual void PostEditChangeChainProperty (FPropertyChangedChainEvent &PropertyChangedEvent) override
This alternate version of PostEditChange is called when properties inside structs are modified.
virtual void PostEditChangeProperty (FPropertyChangedEvent &PropertyChangedEvent) override
Called when a property on this object has been modified externally.
virtual void PostEditComponentMove (bool bFinished) override
Called when this component is moved in the editor.
virtual void PostLoad () override
Do any object-specific cleanup required immediately after loading an object.
void TermComponentConstraint ()
Break the constraint.
UFUNCTION () 1 bool IsBroken()
UFUNCTION () 1 FConstraintInstanceAccessor GetConstraint()
Gets the constraint object.
UFUNCTION () 1 float GetCurrentSwing1() const
Gets the current Swing1 of the constraint.
UFUNCTION () 1 float GetCurrentSwing2() const
Gets the current Swing2 of the constraint.
UFUNCTION () 1 float GetCurrentTwist() const
Gets the current Angular Twist of the constraint.
UFUNCTION () 1 void BreakConstraint()
Break this constraint.
UFUNCTION () 1 void GetConstrainedComponents(UPrimitiveComponent *&OutComponent1
Get connected components and potential related attachement bones.
UFUNCTION () 1 void GetConstraintForce(FVector &OutLinearForce
UFUNCTION () 1 void SetAngularBreakable(bool bAngularBreakable
Sets the Angular Breakable properties.
UFUNCTION() 1 void SetAngularDriveMode(EAngularDriveMode UFUNCTION () 1 void SetAngularDriveAccelerationMode(bool bAccelerationMode)
Switches the angular drive mode between SLERP and Twist And Swing.
UFUNCTION () 1 void SetAngularDriveParams(float PositionStrength
Sets the drive params for the angular drive.
UFUNCTION () 1 void SetAngularOrientationTarget(const FRotator &InPosTarget)
Sets the target orientation for the angular drive.
UFUNCTION () 1 void SetAngularPlasticity(bool bAngularPlasticity
Sets the Angular Plasticity properties.
UFUNCTION () 1 void SetAngularSwing1Limit(EAngularConstraintMotion MotionType
Sets the Angular Swing1 Motion Type.
UFUNCTION () 1 void SetAngularSwing2Limit(EAngularConstraintMotion MotionType
Sets the Angular Swing2 Motion Type.
UFUNCTION () 1 void SetAngularTwistLimit(EAngularConstraintMotion ConstraintType
Sets the Angular Twist Motion Type.
UFUNCTION () 1 void SetAngularVelocityDriveSLERP(bool bEnableSLERP)
Enables/Disables the angular velocity slerp drive.
UFUNCTION () 1 void SetAngularVelocityDriveTwistAndSwing(bool bEnableTwistDrive
Enables/Disables angular velocity twist and swing drive.
UFUNCTION () 1 void SetAngularVelocityTarget(const FVector &InVelTarget)
Sets the target velocity for the angular drive.
UFUNCTION () 1 void SetConstrainedComponents(UPrimitiveComponent *Component1
Directly specify component to connect.
UFUNCTION () 1 void SetContactTransferScale(float ContactTransferScale)
Sets the contact transfer scale properties.
UFUNCTION() 1 void SetConstraintReferenceFrame(EConstraintFrame UFUNCTION() 1 void SetConstraintReferencePosition(EConstraintFrame UFUNCTION() 1 void SetConstraintReferenceOrientation(EConstraintFrame UFUNCTION () 1 void SetDisableCollision(bool bDisableCollision)
UFUNCTION () 1 void SetLinearBreakable(bool bLinearBreakable
Sets the Linear Breakable properties.
UFUNCTION () 1 void SetLinearDriveAccelerationMode(bool bAccelerationMode)
Toggles the linear drive acceleration mode.
UFUNCTION () 1 void SetLinearDriveParams(float PositionStrength
Sets the drive params for the linear drive.
UFUNCTION () 1 void SetLinearPlasticity(bool bLinearPlasticity
Sets the Linear Plasticity properties.
UFUNCTION () 1 void SetLinearPositionDrive(bool bEnableDriveX
Enables/Disables linear position drive.
UFUNCTION () 1 void SetLinearPositionTarget(const FVector &InPosTarget)
Sets the target position for the linear drive.
UFUNCTION () 1 void SetLinearVelocityDrive(bool bEnableDriveX
Enables/Disables linear position drive.
UFUNCTION () 1 void SetLinearVelocityTarget(const FVector &InVelTarget)
Sets the target velocity for the linear drive.
UFUNCTION () 1 void SetLinearXLimit(ELinearConstraintMotion ConstraintType
Sets the LinearX Motion Type.
UFUNCTION () 1 void SetLinearYLimit(ELinearConstraintMotion ConstraintType
Sets the LinearY Motion Type.
UFUNCTION () 1 void SetLinearZLimit(ELinearConstraintMotion ConstraintType
Sets the LinearZ Motion Type.
UFUNCTION () 1 void SetOrientationDriveSLERP(bool bEnableSLERP)
Enables/Disables the angular orientation slerp drive.
UFUNCTION () 1 void SetOrientationDriveTwistAndSwing(bool bEnableTwistDrive
Enables/Disables angular orientation drive.
UFUNCTION () 1 void SetProjectionEnabled(bool bProjectionEnabled)
UFUNCTION () 1 void SetProjectionParams(float ProjectionLinearAlpha
Set the projection settings for use when projection is enabled.
UFUNCTION () bool IsProjectionEnabled() const
UFUNCTION ()) void SetAngularOrientationDrive(bool bEnableSwingDrive
Enables/Disables angular orientation drive.
UFUNCTION ()) void SetAngularVelocityDrive(bool bEnableSwingDrive
void UpdateConstraintFrames ()
Update the reference frames held inside the constraint that indicate the joint location in the reference frame of the two connected bodies.
void UpdateSpriteTexture ()
UPROPERTY ()) FConstraintInstance ConstraintInstance
All constraint settings.
Public Member Functions inherited from USceneComponent
void AddLocalOffset (FVector DeltaLocation, bool bSweep=false, FHitResult *OutSweepHitResult=nullptr, ETeleportType Teleport=ETeleportType::None)
void AddLocalRotation (const FQuat &DeltaRotation, bool bSweep=false, FHitResult *OutSweepHitResult=nullptr, ETeleportType Teleport=ETeleportType::None)
void AddLocalRotation (FRotator DeltaRotation, bool bSweep=false, FHitResult *OutSweepHitResult=nullptr, ETeleportType Teleport=ETeleportType::None)
void AddLocalTransform (const FTransform &DeltaTransform, bool bSweep=false, FHitResult *OutSweepHitResult=nullptr, ETeleportType Teleport=ETeleportType::None)
void AddRelativeLocation (FVector DeltaLocation, bool bSweep=false, FHitResult *OutSweepHitResult=nullptr, ETeleportType Teleport=ETeleportType::None)
void AddRelativeRotation (const FQuat &DeltaRotation, bool bSweep=false, FHitResult *OutSweepHitResult=nullptr, ETeleportType Teleport=ETeleportType::None)
void AddRelativeRotation (FRotator DeltaRotation, bool bSweep=false, FHitResult *OutSweepHitResult=nullptr, ETeleportType Teleport=ETeleportType::None)
void AddWorldOffset (FVector DeltaLocation, bool bSweep=false, FHitResult *OutSweepHitResult=nullptr, ETeleportType Teleport=ETeleportType::None)
void AddWorldRotation (const FQuat &DeltaRotation, bool bSweep=false, FHitResult *OutSweepHitResult=nullptr, ETeleportType Teleport=ETeleportType::None)
void AddWorldRotation (FRotator DeltaRotation, bool bSweep=false, FHitResult *OutSweepHitResult=nullptr, ETeleportType Teleport=ETeleportType::None)
void AddWorldTransform (const FTransform &DeltaTransform, bool bSweep=false, FHitResult *OutSweepHitResult=nullptr, ETeleportType Teleport=ETeleportType::None)
void AddWorldTransformKeepScale (const FTransform &DeltaTransform, bool bSweep=false, FHitResult *OutSweepHitResult=nullptr, ETeleportType Teleport=ETeleportType::None)
virtual void ApplyWorldOffset (const FVector &InOffset, bool bWorldShift) override
Called by owner actor on position shifting Component should update all relevant data structures to reflect new actor location.
virtual bool AttachToComponent (USceneComponent *InParent, const FAttachmentTransformRules &AttachmentRules, FName InSocketName=NAME_None)
Attach this component to another scene component, optionally at a named socket.
virtual void CalcBoundingCylinder (float &CylinderRadius, float &CylinderHalfHeight) const
Calculate the axis-aligned bounding cylinder of the component (radius in X-Y, half-height along Z axis).
virtual FBoxSphereBounds CalcBounds (const FTransform &LocalToWorld) const
Calculate the bounds of the component.
virtual FBoxSphereBounds CalcLocalBounds () const
Calculate the local bounds of the component.
virtual bool CanAttachAsChild (const USceneComponent *ChildComponent, FName SocketName) const
Called to see if it's possible to attach another scene component as a child.
virtual bool CanEditChange (const FProperty *Property) const override
Called by the editor to query whether a property of this object is allowed to be modified.
bool CanEverRender () const
return true if it can ever render
virtual const bool CanHaveStaticMobility () const
Determines whether or not the component can have its mobility set to static.
void ClearSkipUpdateOverlaps ()
Clears the skip update overlaps flag.
void ConditionalUpdateComponentToWorld ()
Call UpdateComponentToWorld if bComponentToWorldUpdated is false.
virtual void DestroyComponent (bool bPromoteChildren=false) override
Unregister the component, remove it from its outer Actor's Components array and mark for pending kill.
virtual void DetachFromComponent (const FDetachmentTransformRules &DetachmentRules)
Detach this component from whatever it is attached to.
FVector GetActorPositionForRenderer () const
Returns the ActorPosition for use by rendering.
const TArray< TObjectPtr< USceneComponent > > & GetAttachChildren () const
Get the SceneComponents that are attached to this component.
UFUNCTION() 1 virtual void SetMobility(EComponentMobility USceneComponent * GetAttachmentRoot () const
Set how often this component is allowed to move during runtime.
AActor * GetAttachmentRootActor () const
Walks up the attachment chain from this SceneComponent and returns the top-level actor it's attached to.
AActor * GetAttachParentActor () const
Gets the owner of the attach parent.
virtual ECollisionEnabled::Type GetCollisionEnabled () const
Returns the form of collision for this component.
virtual ECollisionChannel GetCollisionObjectType () const
Returns the channel that this component belongs to when it moves.
virtual ECollisionResponse GetCollisionResponseToChannel (ECollisionChannel Channel) const
Returns the response that this component has to a specific collision channel.
virtual const FCollisionResponseContainer & GetCollisionResponseToChannels () const
Return const reference to CollsionResponseContainer.
ECollisionResponse GetCollisionResponseToComponent (USceneComponent *OtherComponent) const
Compares the CollisionObjectType of each component against the Response of the other, to see what kind of response we should generate.
virtual TStructOnScope< FActorComponentInstanceData > GetComponentInstanceData () const override
Called before we throw away components during RerunConstructionScripts, to cache any data we wish to persist across that operation.
FORCEINLINE FVector GetComponentLocation () const
Return location of the component, in world space.
FORCEINLINE FQuat GetComponentQuat () const
Return rotation quaternion of the component, in world space.
FORCEINLINE FRotator GetComponentRotation () const
Return rotation of the component, in world space.
FORCEINLINE FVector GetComponentScale () const
Return scale of the component, in world space.
FORCEINLINE const FTransform & GetComponentToWorld () const
Get the current component-to-world transform for this component TODO: probably deprecate this in favor of GetComponentTransform.
FORCEINLINE const FTransform & GetComponentTransform () const
Get the current component-to-world transform for this component.
FScopedMovementUpdate * GetCurrentScopedMovement () const
Returns the current scoped movement update, or NULL if there is none.
UPROPERTY()) uint8 bHiddenInGame UPROPERTY() uint8 bBoundsChangeTriggersStreamingDataRebuild UPROPERTY() uint8 bUseAttachParentBound UPROPERTY() uint8 bComputeFastLocalBounds UPROPERTY() uint8 bComputeBoundsOnceForGame UPROPERTY() uint8 bComputedBoundsOnceForGame FBoxSphereBounds GetLocalBounds () const
Whether or not the cached PhysicsVolume this component overlaps should be updated when the component is moved.
virtual bool GetMaterialPropertyPath (int32 ElementIndex, UObject *&OutOwner, FString &OutPropertyPath, FProperty *&OutProperty)
Returns full material property path and UObject owner property object Path examples: Material property path with array element and inner struct Materials[0].InnerStruct.Material Material property path with array element Materials[0] Simple material property path Materials.
EComponentMobility::Type GetMobility () const
Return the Mobility of this component.
virtual const int32 GetNumUncachedStaticLightingInteractions () const
Returns number of lighting interactions that need to be recalculated.
virtual FBoxSphereBounds GetPlacementExtent () const
Get the extent used when placing this component in the editor, used for 'pulling back' hit.
FVector GetRelativeLocation () const
Gets the literal value of RelativeLocation.
FVector & GetRelativeLocation_DirectMutable ()
Gets a refence to RelativeLocation with the expectation that it will be modified.
FRotator GetRelativeRotation () const
Gets the literal value of RelativeRotation.
FRotator & GetRelativeRotation_DirectMutable ()
Gets a refence to RelativeRotation with the expectation that it will be modified.
FORCEINLINE const FRotationConversionCache & GetRelativeRotationCache () const
Get the RelativeRotationCache.
FQuat GetRelativeRotationFromWorld (const FQuat &WorldRotation)
Convenience function to get the relative rotation from the passed in world rotation.
FVector GetRelativeScale3D () const
Gets the literal value of RelativeScale3D.
FVector & GetRelativeScale3D_DirectMutable ()
Gets a refence to RelativeRotation with the expectation that it will be modified.
void GetSocketWorldLocationAndRotation (FName InSocketName, FVector &OutLocation, FQuat &OutRotation) const
void GetSocketWorldLocationAndRotation (FName InSocketName, FVector &OutLocation, FRotator &OutRotation) const
Find the world-space location and rotation of the given named socket.
virtual FBox GetStreamingBounds () const override
bool GetVisibleFlag () const
Gets the literal value of bVisible.
virtual bool HasAnySockets () const
Returns true if this component has any sockets.
bool HasGroupedMovementUpdates () const
Returns true if this component is part of a grouped movement update that will apply later.
bool IsAttachedTo (const USceneComponent *TestComp) const
Walks up the attachment chain to see if this component is attached to the supplied component.
FORCEINLINE_DEBUGGABLE bool IsCollisionEnabled () const
Utility to see if there is any form of collision (query or physics) enabled on this component.
virtual EDataValidationResult IsDataValid (FDataValidationContext &Context) const override
Generic function to validate objects during changelist validations, etc.
bool IsDeferringMovementUpdates () const
Returns true if movement is currently within the scope of an FScopedMovementUpdate.
FORCEINLINE_DEBUGGABLE bool IsPhysicsCollisionEnabled () const
Utility to see if there is any physics collision enabled on this component.
virtual bool IsPostLoadThreadSafe () const override
Called during async load to determine if PostLoad can be called on the loading thread.
virtual bool IsPrecomputedLightingValid () const
True if our precomputed lighting is up to date.
FORCEINLINE_DEBUGGABLE bool IsQueryCollisionEnabled () const
Utility to see if there is any query collision enabled on this component.
bool IsUsingAbsoluteLocation () const
Gets the literal value of bAbsoluteLocation.
bool IsUsingAbsoluteRotation () const
Gets the literal value of bAbsoluteRotation.
bool IsUsingAbsoluteScale () const
Gets the literal value of bAbsoluteScale.
virtual bool IsVisibleInEditor () const
Return true if visible in editor.
virtual bool IsWorldGeometry () const
Is this component considered 'world' geometry, by default checks if this uses the WorldStatic collision channel.
bool MoveComponent (const FVector &Delta, const FQuat &NewRotation, bool bSweep, FHitResult *Hit=NULL, EMoveComponentFlags MoveFlags=MOVECOMP_NoFlags, ETeleportType Teleport=ETeleportType::None)
Tries to move the component by a movement vector (Delta) and sets rotation to NewRotation.
bool MoveComponent (const FVector &Delta, const FRotator &NewRotation, bool bSweep, FHitResult *Hit=NULL, EMoveComponentFlags MoveFlags=MOVECOMP_NoFlags, ETeleportType Teleport=ETeleportType::None)
virtual bool NeedsLoadForTargetPlatform (const ITargetPlatform *TargetPlatform) const
virtual void OnAttachmentChanged ()
Called when AttachParent changes, to allow the scene to update its attachment state.
virtual void OnComponentDestroyed (bool bDestroyingHierarchy) override
Called when a component is destroyed.
virtual void OnPreRegister () override
Called by PreRegisterComponentWithWorld when the component is being pre-registered.
virtual void OnReceiveReplicatedState (const FVector X, const FQuat R, const FVector V, const FVector W)
Called when client receive replication data, before replication is performed.
virtual void PostNetReceive () override
Called right after receiving a bunch.
virtual void PostRepNotifies () override
Called right after calling all OnRep notifies (called even when there are no notifies)
virtual void PreFeatureLevelChange (ERHIFeatureLevel::Type PendingFeatureLevel)
Called to update any visuals needed for a feature level change.
virtual void PreNetReceive () override
Called right before receiving a bunch.
void ProcessDeferredMovementGroup (const struct FDeferredComponentMoveData &MoveData)
Process a single instance of a scoped movement.
virtual void PropagateLightingScenarioChange ()
Updates any visuals after the lighting has changed.
virtual void QuerySupportedSockets (TArray< FComponentSocketDescription > &OutSockets) const
Get a list of sockets this component contains.
virtual void Serialize (FArchive &Ar) override
Handles reading, writing, and reference collecting using FArchive.
FORCEINLINE void SetComponentToWorld (const FTransform &NewComponentToWorld)
Sets the cached component to world directly.
void SetPhysicsVolume (APhysicsVolume *NewVolume, bool bTriggerNotifiers)
Replace current PhysicsVolume to input NewVolume.
void SetRelativeLocation (FVector NewLocation, bool bSweep=false, FHitResult *OutSweepHitResult=nullptr, ETeleportType Teleport=ETeleportType::None)
void SetRelativeLocation_Direct (const FVector NewRelativeLocation)
Sets the value of RelativeLocation without causing other side effects to this instance.
void SetRelativeLocationAndRotation (FVector NewLocation, const FQuat &NewRotation, bool bSweep=false, FHitResult *OutSweepHitResult=nullptr, ETeleportType Teleport=ETeleportType::None)
void SetRelativeLocationAndRotation (FVector NewLocation, FRotator NewRotation, bool bSweep=false, FHitResult *OutSweepHitResult=nullptr, ETeleportType Teleport=ETeleportType::None)
void SetRelativeRotation (const FQuat &NewRotation, bool bSweep=false, FHitResult *OutSweepHitResult=nullptr, ETeleportType Teleport=ETeleportType::None)
void SetRelativeRotation (FRotator NewRotation, bool bSweep=false, FHitResult *OutSweepHitResult=nullptr, ETeleportType Teleport=ETeleportType::None)
void SetRelativeRotation_Direct (const FRotator NewRelativeRotation)
Sets the value of RelativeRotation without causing other side effects to this instance.
void SetRelativeRotationCache (const FRotationConversionCache &InCache)
Sets the RelativeRotationCache.
void SetRelativeRotationExact (FRotator NewRotation, bool bSweep=false, FHitResult *OutSweepHitResult=nullptr, ETeleportType Teleport=ETeleportType::None)
Set the rotation of the component relative to its parent and force RelativeRotation to be equal to new rotation.
void SetRelativeScale3D_Direct (const FVector NewRelativeScale3D)
Sets the value of RelativeScale3D without causing other side effects to this instance.
void SetRelativeTransform (const FTransform &NewTransform, bool bSweep=false, FHitResult *OutSweepHitResult=nullptr, ETeleportType Teleport=ETeleportType::None)
void SetRelativeTransform_Direct (const FTransform &NewRelativeTransform)
Helper function to set the location, rotation, and scale without causing other side effects to this instance.
void SetupAttachment (USceneComponent *InParent, FName InSocketName=NAME_None)
Initializes desired Attach Parent and SocketName to be attached to when the component is registered.
void SetUsingAbsoluteLocation (const bool bInAbsoluteLocation)
Sets the value of bAbsoluteLocation without causing other side effects to this instance.
void SetUsingAbsoluteRotation (const bool bInAbsoluteRotation)
Sets the value of bAbsoluteRotation without causing other side effects to this instance.
void SetUsingAbsoluteScale (const bool bInAbsoluteRotation)
Sets the value of bAbsoluteScale without causing other side effects to this instance.
void SetVisibleFlag (const bool bInVisible)
Sets the value of bVisible without causing other side effects to this instance.
void SetWorldLocation (FVector NewLocation, bool bSweep=false, FHitResult *OutSweepHitResult=nullptr, ETeleportType Teleport=ETeleportType::None)
void SetWorldLocationAndRotation (FVector NewLocation, const FQuat &NewRotation, bool bSweep=false, FHitResult *OutSweepHitResult=nullptr, ETeleportType Teleport=ETeleportType::None)
Set the relative location and FQuat rotation of the component to put it at the supplied pose in world space.
void SetWorldLocationAndRotation (FVector NewLocation, FRotator NewRotation, bool bSweep=false, FHitResult *OutSweepHitResult=nullptr, ETeleportType Teleport=ETeleportType::None)
void SetWorldLocationAndRotationNoPhysics (const FVector &NewLocation, const FRotator &NewRotation)
Special version of SetWorldLocationAndRotation that does not affect physics.
void SetWorldRotation (const FQuat &NewRotation, bool bSweep=false, FHitResult *OutSweepHitResult=nullptr, ETeleportType Teleport=ETeleportType::None)
void SetWorldRotation (FRotator NewRotation, bool bSweep=false, FHitResult *OutSweepHitResult=nullptr, ETeleportType Teleport=ETeleportType::None)
void SetWorldTransform (const FTransform &NewTransform, bool bSweep=false, FHitResult *OutSweepHitResult=nullptr, ETeleportType Teleport=ETeleportType::None)
virtual bool ShouldCollideWhenPlacing () const
If true, bounds should be used when placing component/actor in level.
bool ShouldComponentAddToScene () const
Looking at various values of the component, determines if this component should be added to the scene.
virtual bool ShouldCreateRenderState () const override
Return true if CreateRenderState() should be called.
bool ShouldRender () const
return true if it should render
bool ShouldSkipUpdateOverlaps () const
If true, we can use the old computed overlaps.
UE_DEPRECATED (4.12, "This function is deprecated, please use DetachFromComponent() instead.") UFUNCTION() ")) 1 virtual void DetachFromParent(bool bMaintainWorldPosition
DEPRECATED - Use DetachFromComponent() instead.
UE_DEPRECATED (4.17, "This function is deprecated, please use AttachToComponent() instead.") UFUNCTION() "
DEPRECATED - Use AttachToComponent() instead.
UFUNCTION ()
Return location of the component, in world space.
UFUNCTION ()
Returns rotation of the component, in world space.
UFUNCTION ()
Returns scale of the component, in world space.
UFUNCTION ()
Get the current component-to-world transform for this component.
UFUNCTION ()
Detach this component from whatever it is attached to.
UFUNCTION () 1 FTransform GetRelativeTransform() const
Returns the transform of the component relative to its parent.
UFUNCTION () 1 FVector GetForwardVector() const
Get the forward (X) unit direction vector from this component, in world space.
UFUNCTION () 1 FVector GetRightVector() const
Get the right (Y) unit direction vector from this component, in world space.
UFUNCTION () 1 FVector GetUpVector() const
Get the up (Z) unit direction vector from this component, in world space.
UFUNCTION () 1 int32 GetNumChildrenComponents() const
Gets the number of attached children components.
UFUNCTION () 1 USceneComponent *GetChildComponent(int32 ChildIndex) const
Gets the attached child component at the specified location.
UFUNCTION () 1 virtual bool IsAnySimulatingPhysics() const
Returns whether the specified body is currently using physics simulation.
UFUNCTION () 1 virtual bool IsSimulatingPhysics(FName BoneName
Returns whether the specified body is currently using physics simulation.
UFUNCTION () 1 virtual bool IsVisible() const
Returns true if this component is visible in the current context.
UFUNCTION () 1 virtual FVector GetComponentVelocity() const
Get velocity of the component: either ComponentVelocity, or the velocity of the physics body if simulating physics.
UFUNCTION () 1 void GetChildrenComponents(bool bIncludeAllDescendants
Gets all components that are attached to this component, possibly recursively.
UFUNCTION () 1 void GetParentComponents(TArray< USceneComponent * > &Parents) const
Gets all attachment parent components up to and including the root component.
UFUNCTION () 1 void ResetRelativeTransform()
Reset the transform of the component relative to its parent.
UFUNCTION () 1 void SetAbsolute(bool bNewAbsoluteLocation
Set which parts of the relative transform should be relative to parent, and which should be relative to world.
UFUNCTION () 1 void SetRelativeScale3D(FVector NewScale3D)
Set the non-uniform scale of the component relative to its parent.
UFUNCTION () 1 void SetShouldUpdatePhysicsVolume(bool bInShouldUpdatePhysicsVolume)
Sets whether or not the cached PhysicsVolume this component overlaps should be updated when the component is moved.
UFUNCTION () 1 void SetWorldScale3D(FVector NewScale)
Set the relative scale of the component to put it at the supplied scale in world space.
UFUNCTION () bool GetShouldUpdatePhysicsVolume() const
Gets whether or not the cached PhysicsVolume this component overlaps should be updated when the component is moved.
UFUNCTION () FName GetAttachSocketName() const
Get the socket we are attached to.
UFUNCTION () static 1 bool IsGroupedComponentMovementEnabled()
UFUNCTION () USceneComponent *GetAttachParent() const
Get the SceneComponent we are attached to.
UFUNCTION () void SetVisibility(bool bNewVisibility
Set visibility of the component, if during game use this to turn on/off.
UFUNCTION ()) 1 APhysicsVolume *GetPhysicsVolume() const
Get the PhysicsVolume overlapping this component.
UFUNCTION ()) 1 bool K2_AttachToComponent(USceneComponent *Parent
Attach this component to another scene component, optionally at a named socket.
UFUNCTION ()) 1 TArray< FName > GetAllSocketNames() const
Gets the names of all the sockets on the component.
UFUNCTION ()) 1 virtual bool DoesSocketExist(FName InSocketName) const
Return true if socket with the given name exists.
UFUNCTION ()) 1 virtual FQuat GetSocketQuaternion(FName InSocketName) const
Get world-space socket or bone FQuat rotation.
UFUNCTION ()) 1 virtual FRotator GetSocketRotation(FName InSocketName) const
Get world-space socket or bone FRotator rotation.
UFUNCTION ()) 1 virtual FTransform GetSocketTransform(FName InSocketName
Get world-space socket transform.
UFUNCTION ()) 1 virtual FVector GetSocketLocation(FName InSocketName) const
Get world-space socket or bone location.
UFUNCTION ()) 1 void K2_AddLocalOffset(FVector DeltaLocation
Adds a delta to the location of the component in its local reference frame.
UFUNCTION ()) 1 void K2_AddLocalRotation(FRotator DeltaRotation
Adds a delta to the rotation of the component in its local reference frame.
UFUNCTION ()) 1 void K2_AddLocalTransform(const FTransform &DeltaTransform
Adds a delta to the transform of the component in its local reference frame.
UFUNCTION ()) 1 void K2_AddRelativeLocation(FVector DeltaLocation
Adds a delta to the translation of the component relative to its parent.
UFUNCTION ()) 1 void K2_AddRelativeRotation(FRotator DeltaRotation
Adds a delta the rotation of the component relative to its parent.
UFUNCTION ()) 1 void K2_AddWorldOffset(FVector DeltaLocation
Adds a delta to the location of the component in world space.
UFUNCTION ()) 1 void K2_AddWorldRotation(FRotator DeltaRotation
Adds a delta to the rotation of the component in world space.
UFUNCTION ()) 1 void K2_AddWorldTransform(const FTransform &DeltaTransform
Adds a delta to the transform of the component in world space.
UFUNCTION ()) 1 void K2_AddWorldTransformKeepScale(const FTransform &DeltaTransform
Adds a delta to the transform of the component in world space.
UFUNCTION ()) 1 void K2_SetRelativeLocation(FVector NewLocation
Set the location of the component relative to its parent.
UFUNCTION ()) 1 void K2_SetRelativeLocationAndRotation(FVector NewLocation
Set the location and rotation of the component relative to its parent.
UFUNCTION ()) 1 void K2_SetRelativeRotation(FRotator NewRotation
Set the rotation of the component relative to its parent.
UFUNCTION ()) 1 void K2_SetRelativeTransform(const FTransform &NewTransform
Set the transform of the component relative to its parent.
UFUNCTION ()) 1 void K2_SetWorldLocation(FVector NewLocation
Put this component at the specified location in world space.
UFUNCTION ()) 1 void K2_SetWorldLocationAndRotation(FVector NewLocation
Set the relative location and rotation of the component to put it at the supplied pose in world space.
UFUNCTION ()) 1 void K2_SetWorldRotation(FRotator NewRotation
UFUNCTION ()) 1 void K2_SetWorldTransform(const FTransform &NewTransform
Set the transform of the component in world space.
virtual void UpdateBounds ()
Update the Bounds of the component.
void UpdateChildTransforms (EUpdateTransformFlags UpdateTransformFlags=EUpdateTransformFlags::None, ETeleportType Teleport=ETeleportType::None)
Update transforms of any components attached to this one.
virtual void UpdateComponentToWorld (EUpdateTransformFlags UpdateTransformFlags=EUpdateTransformFlags::None, ETeleportType Teleport=ETeleportType::None) override final
Recalculate the value of our component to world transform.
bool UpdateOverlaps (const TOverlapArrayView *PendingOverlaps=nullptr, bool bDoNotifies=true, const TOverlapArrayView *OverlapsAtEndLocation=nullptr)
Queries world and updates overlap tracking state for this component.
virtual void UpdatePhysicsVolume (bool bTriggerNotifiers)
Updates the PhysicsVolume of this SceneComponent, if bShouldUpdatePhysicsVolume is true.
UPROPERTY () FVector ComponentVelocity
Velocity of the component.
UPROPERTY() TEnumAsByte< EComponentMobility UPROPERTY () TEnumAsByte< enum EDetailMode > DetailMode
How often this component is allowed to move, used to make various optimizations.
UPROPERTY ()) FPhysicsVolumeChanged PhysicsVolumeChangedDelegate
Delegate that will be called when PhysicsVolume has been changed.
Public Member Functions inherited from UActorComponent
virtual void AddAssetUserData (UAssetUserData *InUserData) override
virtual UObject const * AdditionalStatObject () const
Give a readable name for this component, including asset name if applicable.
void AddReplicatedSubObject (UObject *SubObject, ELifetimeCondition NetCondition=COND_None)
Register a SubObject that will get replicated along with the actor component.
FORCEINLINE bool AllowReregistration () const
Check whether the component class allows reregistration during ReregisterAllComponents.
virtual bool AllowsAsyncPhysicsStateCreation () const
Returns whether this component allows having its physics state being created asynchronously (outside of the GameThread).
virtual bool AllowsAsyncPhysicsStateDestruction () const
Returns whether this component allows having its physics state being destroyed asynchronously (outside of the GameThread).
virtual void AsyncPhysicsTickComponent (float DeltaTime, float SimTime)
Override this function to implement custom logic to be executed every physics step.
virtual void BeginPlay ()
Begins Play for the component.
virtual bool CallRemoteFunction (UFunction *Function, void *Parameters, FOutParmRec *OutParms, FFrame *Stack) override
Call the actor's function remotely.
bool CanEverAffectNavigation () const
Can this component potentially influence navigation.
void ClearNeedEndOfFrameUpdate ()
If we belong to a world, clear the request to do a deferred update.
void ClearUCSModifiedProperties ()
Clears the component's UCS modified properties.
bool ComponentIsInLevel (const class ULevel *TestLevel) const
Returns true if this actor is contained by TestLevel.
bool ComponentIsInPersistentLevel (bool bIncludeLevelStreamingPersistent) const
See if this component is in the persistent level.
virtual void ComputeHLODHash (class FHLODHashBuilder &HashBuilder) const
Override to allow a component subclass to compute an hash for the purpose of HLOD generation.
void CreatePhysicsState (bool bAllowDeferral=false)
Create any physics engine information for this component.
DECLARE_MULTICAST_DELEGATE_OneParam (FOnMarkRenderStateDirty, UActorComponent &)
void DestroyPhysicsState ()
Shut down any physics engine structure for this component.
void DestroyReplicatedSubObjectOnRemotePeers (UObject *SubObject)
Stop replicating a subobject and tell actor channels to delete the replica of this subobject next time the Actor gets replicated Note it is up to the caller to delete the local object on the authority.
void DetermineUCSModifiedProperties ()
Initializes the list of properties that are modified by the UserConstructionScript.
void DoDeferredRenderUpdates_Concurrent ()
Uses the bRenderStateDirty/bRenderTransformDirty/bRenderInstancesDirty to perform any necessary work on this component.
virtual bool ForceActorNoDataLayers () const
virtual bool ForceActorNonSpatiallyLoaded () const
virtual void GetActorDescProperties (FPropertyPairsMap &PropertyPairsMap) const
Add properties to the component owner's actor desc.
virtual const TArray< UAssetUserData * > * GetAssetUserDataArray () const override
virtual UAssetUserData * GetAssetUserDataOfClass (TSubclassOf< UAssetUserData > InUserDataClass) override
virtual UObject * GetAsyncPhysicsStateObject () const override final
Returns the associated UObject for this processor.
virtual void GetComponentChildElements (TArray< FTypedElementHandle > &OutElementHandles, const bool bAllowCreate=true)
Get the logical child elements of this component, if any.
virtual bool GetComponentClassCanReplicate () const
Returns true if this type of component can ever replicate, override to disable the default behavior.
ULevel * GetComponentLevel () const
Return the ULevel that this Component is part of.
virtual TSharedPtr< SWidget > GetCustomEditorPreviewWidget ()
If this component is set up to provide a preview window in editor (see GetEditorPreviewInfo), you can use this to customize the preview (to be something other than a world viewport).
virtual TSubclassOf< class UHLODBuilder > GetCustomHLODBuilderClass () const
Return the custom HLODBuilder class that should be used to generate HLODs for components of this type.
virtual bool GetEditorPreviewInfo (float DeltaTime, FMinimalViewInfo &ViewOut)
Supplies the editor with a view specific to this component (think a view from a camera components POV, a render, etc.).
virtual int32 GetFunctionCallspace (UFunction *Function, FFrame *Stack) override
Return the space this function should be called.
virtual TArray< UActorComponent * > GetHLODProxyComponents () const
Override to provide a custom set of components to be used in place of the current component for the HLOD generation.
FORCEINLINE bool GetIsReplicated () const
Returns whether replication is enabled or not.
virtual void GetLifetimeReplicatedProps (TArray< FLifetimeProperty > &OutLifetimeProps) const override
Returns properties that are replicated for the lifetime of the actor channel.
uint32 GetMarkedForEndOfFrameUpdateState () const
Tracks whether the component has been added to one of the world's end of frame update lists.
uint32 GetMarkedForPreEndOfFrameSync () const
Tracks whether the component has been added to one of the world's end of frame update lists.
ENetMode GetNetMode () const
Get the network mode (dedicated server, client, standalone, etc) for this component.
template<class T>
T * GetOwner () const
Templated version of GetOwner(), will return nullptr if cast fails.
ENetRole GetOwnerRole () const
Get the network role of the Owner, or ROLE_None if there is no owner.
virtual FString GetReadableName () const
Returns a readable name for this component, including the asset name if applicable By default this appends a space plus AdditionalStatObject()
virtual ELifetimeCondition GetReplicationCondition () const
Returns the replication condition for the component.
class FSceneInterface * GetScene () const
Returns the rendering scene associated with this component.
virtual FBox GetStreamingBoundsEditor () const
void GetUCSModifiedProperties (TSet< const FProperty * > &ModifiedProperties) const
Returns the list of properties that are modified by the UserConstructionScript.
int32 GetUCSSerializationIndex () const
Returns the UCS serialization index.
virtual UWorld * GetWorld () const override final
Getter for the cached world pointer, will return null if the component is not actually spawned in a level.
bool HasBeenCreated () const
Indicates that OnCreatedComponent has been called, but OnDestroyedComponent has not yet.
bool HasBeenInitialized () const
Indicates that InitializeComponent has been called, but UninitializeComponent has not yet.
bool HasBegunPlay () const
Indicates that BeginPlay has been called, but EndPlay has not yet.
void InvalidateLightingCache ()
Invalidate lighting cache with default options.
virtual void InvalidateLightingCacheDetailed (bool bInvalidateBuildEnqueuedLighting, bool bTranslationOnly)
Called when this actor component has moved, allowing it to discard statically cached lighting information.
bool IsAsyncCreatePhysicsStateRunning () const
Whether asynchronous physics state creation is running or not.
bool IsAsyncDestroyPhysicsStateRunning () const
Whether asynchronous physics state destruction is running or not.
virtual bool IsAsyncPhysicsStateCreated () const override final
Returns whether the physics state is created.
bool IsCreatedByConstructionScript () const
Returns true if instances of this component are created by either the user or simple construction script.
bool IsEditableWhenInherited () const
True if this component can be modified when it was inherited from a parent actor class.
virtual bool IsHLODRelevant () const
Override to specify that a component is relevant to the HLOD generation.
virtual bool IsNameStableForNetworking () const override
IsNameStableForNetworking means an object can be referred to its path name (relative to outer) over the network.
virtual bool IsNavigationRelevant () const
Override to specify that a component is relevant to the navigation system.
bool IsNetMode (ENetMode Mode) const
Test whether net mode is the given mode.
bool IsNetSimulating () const
Returns true if we are replicating and this client is not authoritative.
bool IsNetStartupComponent () const
Returns true if this component was owned by a net startup actor during level load.
bool IsOwnerRunningUserConstructionScript () const
See if the owning Actor is currently running the UCS.
bool IsOwnerSelected () const
Returns whether the component's owner is selected in the editor.
bool IsPhysicsStateCreated () const
Returns true if the physics 'state' (e.g.
FORCEINLINE bool IsPreRegistered () const
See if this component is currently pre-registered.
FORCEINLINE bool IsPreRegistering () const
See if this component is currently pre-registering.
FORCEINLINE bool IsPreUnregistered () const
See if this component is currently pre-unregistered.
FORCEINLINE bool IsPreUnregistering () const
See if this component is currently pre-unregistering.
virtual bool IsReadyForOwnerToAutoDestroy () const
Overridable check for a component to indicate to its Owner that it should prevent the Actor from auto destroying when finished.
bool IsReadyForReplication () const
Indicates that ReadyForReplication has been called.
FORCEINLINE bool IsRegistered () const
See if this component is currently registered.
bool IsRenderInstancesDirty () const
Is this component's instance data in need of sending to the renderer?
bool IsRenderStateCreated () const
Returns true if the render 'state' (e.g.
bool IsRenderStateDirty () const
Is this component in need of its whole state being sent to the renderer?
bool IsRenderStateRecreating () const
Returns true if the render 'state' is being recreated for this component (see additional comments on variable above)
bool IsRenderTransformDirty () const
Is this component's transform in need of sending to the renderer?
bool IsReplicatedSubObjectRegistered (const UObject *SubObject) const
Tells if the object is registered to be replicated by this actor component.
virtual bool IsSelectedInEditor () const override
Test the selection state of a UObject.
virtual bool IsSupportedForNetworking () const override
IsSupportedForNetworking means an object can be referenced over the network.
bool IsUsingRegisteredSubObjectList () const
Returns if this component is replicating subobjects via the registration list or via the virtual ReplicateSubObjects method.
void MarkForNeededEndOfFrameRecreate ()
If we belong to a world, mark this for a deferred update, otherwise do it now.
void MarkForNeededEndOfFrameUpdate ()
If we belong to a world, mark this for a deferred update, otherwise do it now.
void MarkRenderDynamicDataDirty ()
Indicate that dynamic data for this component needs to be sent at the end of the frame.
void MarkRenderInstancesDirty ()
Marks the instances as dirty - changes to instance transforms/custom data will be sent to the render thread at the end of the frame.
void MarkRenderStateDirty ()
Mark the render state as dirty - will be sent to the render thread at the end of the frame.
void MarkRenderTransformDirty ()
Marks the transform as dirty - will be sent to the render thread at the end of the frame.
virtual bool Modify (bool bAlwaysMarkDirty=true) override
Note that the object will be modified.
virtual bool NeedsLoadForClient () const override
Called during saving to determine the load flags to save with the object.
virtual bool NeedsLoadForEditorGame () const override
Called during saving to include this object in client/servers running in editor builds, even if they wouldn't normally be.
virtual bool NeedsLoadForServer () const override
Called during saving to determine the load flags to save with the object.
virtual void OnActorEnableCollisionChanged ()
Called on each component when the Actor's bEnableCollisionChanged flag changes.
virtual void OnActorVisibilityChanged ()
Called on each component when the Actor's visibility state changes.
virtual bool OnAsyncCreatePhysicsState (const UE::FTimeout &Timeout) override
Used to create any physics engine information for this component outside of the GameThread.
virtual void OnAsyncCreatePhysicsStateEnd_GameThread () override
Called on the GameThread once the component's physic engine information is created.
virtual bool OnAsyncDestroyPhysicsState (const UE::FTimeout &Timeout) override
Used to destroy any physics engine information for this component outside of the GameThread.
virtual void OnAsyncDestroyPhysicsStateBegin_GameThread () override
Called on the GameThread before the component's physic engine information is destroyed.
virtual void OnAsyncDestroyPhysicsStateEnd_GameThread () override
Called on the GameThread once the component's physic engine information is destroyed.
virtual void OnComponentCreated ()
Called when a component is created (not loaded).
void OnCreatedFromReplication ()
void OnDestroyedFromReplication ()
virtual void OnEndOfFrameUpdateDuringTick ()
Allows components to handle an EOF update happening mid tick.
virtual void OnPreEndOfFrameSync ()
Allows components to wait on outstanding tasks prior to sending EOF update data.
virtual void PostApplyToComponent ()
Called after ApplyToComponent has run.
virtual void PostEditUndo () override
Called after applying a transaction to the object.
virtual void PostInitProperties () override
Called after the C++ constructor and after the properties have been initialized, including those loaded from config.
virtual void PostRename (UObject *OldOuter, const FName OldName) override
Called at the end of Rename(), but only if the rename was actually carried out.
virtual void PreEditChange (FProperty *PropertyThatWillChange) override
This is called when a property is about to be modified externally.
virtual void PreEditUndo () override
Called before applying a transaction to the object.
void PreRegisterComponentWithWorld (UWorld *InWorld)
Pre-registers a component with a specific world.
virtual void PreReplication (IRepChangedPropertyTracker &ChangedPropertyTracker)
Called on the component right before replication occurs.
void PreUnregisterComponentFromWorld ()
Pre-unregisters a component from a specific world.
virtual void ReadyForReplication ()
ReadyForReplication gets called on replicated components when their owning actor is officially ready for replication.
void RecreatePhysicsState ()
Recreate the physics state right way.
void RecreateRenderState_Concurrent ()
Recreate the render state right away.
UFUNCTION()) 1 void ReceiveEndPlay(EEndPlayReason void RegisterAllComponentTickFunctions (bool bRegister)
Blueprint implementable event for when the component ends play, generally via destruction or its Actor's EndPlay.
void RegisterComponent ()
Register this component, creating any rendering/physics state.
void RegisterComponentWithWorld (UWorld *InWorld, FRegisterComponentContext *Context=nullptr)
Registers a component with a specific world, which creates any visual/physical state.
void RemoveReplicatedSubObject (UObject *SubObject)
Unregister a SubObject to stop replicating it's properties to clients.
void RemoveUCSModifiedProperties (const TArray< FProperty * > &Properties)
Removes specified properties from the list of UCS-modified properties.
virtual void RemoveUserDataOfClass (TSubclassOf< UAssetUserData > InUserDataClass) override
virtual bool Rename (const TCHAR *NewName=NULL, UObject *NewOuter=NULL, ERenameFlags Flags=REN_None) override
Rename this object to a unique name, or change its outer.
virtual bool ReplicateSubobjects (class UActorChannel *Channel, class FOutBunch *Bunch, FReplicationFlags *RepFlags)
Allows a component to replicate other subobject on the actor.
virtual bool RequiresGameThreadEndOfFrameRecreate () const
return true if this component requires end of frame recreates to happen from the game thread.
virtual bool RequiresGameThreadEndOfFrameUpdates () const
return true if this component requires end of frame updates to happen from the game thread.
virtual bool RequiresPreEndOfFrameSync () const
return true if this component needs to sync to tasks before end of frame updates are executed
void ReregisterComponent ()
Unregisters and immediately re-registers component.
void SetActiveFlag (const bool bNewIsActive)
Sets the value of bIsActive without causing other side effects to this instance.
void SetCanEverAffectNavigation (bool bRelevant)
Sets value of bCanEverAffectNavigation flag and update navigation octree if needed.
virtual void SetComponentTickEnabledAsync (bool bEnabled)
Spawns a task on GameThread that will call SetComponentTickEnabled.
void SetIsNetStartupComponent (const bool bInIsNetStartupComponent)
This should only be called by the engine in ULevel::InitializeNetworkActors to initialize bIsNetStartupComponent.
void SetNetAddressable ()
This signifies the component can be ID'd by name over the network.
virtual void SetPackageExternal (bool bExternal, bool bShouldDirty)
bool SetupActorComponentTickFunction (struct FTickFunction *TickFunction)
Set up a tick function for a component in the standard way.
virtual bool ShouldIncrementalPreRegister (UWorld *WorldContext) const
Returns whether PreRegisterComponentWithWorld should be called for this component when its Level is being added to the world.
virtual bool ShouldIncrementalPreUnregister () const
Returns whether PreUnregisterComponentFromWorld should be called for this component when its Level is being removed from the world.
void TearOffReplicatedSubObjectOnRemotePeers (UObject *SubObject)
Stop replicating a subobject and tell actor channels who spawned a replica of this subobject to release ownership over it.
virtual void TickComponent (float DeltaTime, enum ELevelTick TickType, FActorComponentTickFunction *ThisTickFunction)
Function called every frame on this ActorComponent.
UFUNCTION () 1 bool ComponentHasTag(FName Tag) const
See if this component contains the supplied tag.
UFUNCTION () 1 float GetComponentTickInterval() const
Returns the tick interval for this component's primary tick function, which is the frequency in seconds at which it will be executed.
UFUNCTION () 1 virtual bool IsComponentTickEnabled() const
Returns whether this component has tick enabled or not.
UFUNCTION () 1 virtual void OnRep_IsActive()
Handles replication of active state, handles ticking by default but should be overridden as needed.
UFUNCTION () 1 virtual void SetAutoActivate(bool bNewAutoActivate)
Sets whether the component should be auto activate or not.
UFUNCTION () 1 virtual void SetComponentTickEnabled(bool bEnabled)
Set this component's tick functions to be enabled or disabled.
UFUNCTION () 1 void SetComponentTickInterval(float TickInterval)
Sets the tick interval for this component's primary tick function.
UFUNCTION () 1 void SetComponentTickIntervalAndCooldown(float TickInterval)
Sets the tick interval for this component's primary tick function.
UFUNCTION () 1 void SetIsReplicated(bool ShouldReplicate)
Enable or disable replication.
UFUNCTION () 1 void SetTickableWhenPaused(bool bTickableWhenPaused)
Sets whether this component can tick when paused.
UFUNCTION ()) 1 virtual void Activate(bool bReset
Activates the SceneComponent, should be overridden by native child classes.
UFUNCTION ()) 1 virtual void AddTickPrerequisiteActor(AActor *PrerequisiteActor)
Make this component tick after PrerequisiteActor.
UFUNCTION ()) 1 virtual void AddTickPrerequisiteComponent(UActorComponent *PrerequisiteComponent)
Make this component tick after PrerequisiteComponent.
UFUNCTION ()) 1 virtual void Deactivate()
Deactivates the SceneComponent.
UFUNCTION ()) 1 virtual void RemoveTickPrerequisiteActor(AActor *PrerequisiteActor)
Remove tick dependency on PrerequisiteActor.
UFUNCTION ()) 1 virtual void RemoveTickPrerequisiteComponent(UActorComponent *PrerequisiteComponent)
Remove tick dependency on PrerequisiteComponent.
UFUNCTION ()) 1 virtual void SetActive(bool bNewActive
Sets whether the component is active or not.
UFUNCTION ()) 1 virtual void ToggleActive()
Toggles the active state of the component.
UFUNCTION ()) 1 void K2_DestroyComponent(UObject *Object)
Unregister and mark for pending kill a component.
UFUNCTION ()) 1 void ReceiveAsyncPhysicsTick(float DeltaSeconds
Event called every async physics tick if bAsyncPhysicsTickEnabled is true.
UFUNCTION ()) 1 void ReceiveBeginPlay()
Blueprint implementable event for when the component is beginning play, called before its owning actor's BeginPlay or when the component is dynamically created if the Actor has already BegunPlay.
UFUNCTION ()) 1 void ReceiveTick(float DeltaSeconds)
Event called every frame if tick is enabled.
UFUNCTION ()) 1 void SetTickGroup(ETickingGroup NewTickGroup)
Changes the ticking group for this component.
UFUNCTION ()) AActor *GetOwner() const
Follow the Outer chain to get the AActor that 'Owns' this component.
UFUNCTION ()) bool IsActive() const
Returns whether the component is active or not.
UFUNCTION ()) bool IsBeingDestroyed() const
Returns whether the component is in the process of being destroyed.
virtual void UninitializeComponent ()
Handle this component being Uninitialized.
void UnregisterComponent ()
Unregister this component, destroying any rendering/physics state.
UPROPERTY () EComponentCreationMethod CreationMethod
Describes how a component instance will be created.
UPROPERTY () FActorComponentActivatedSignature OnComponentActivated
Called when the component has been activated, with parameter indicating if it was from a reset.
UPROPERTY () FActorComponentDeactivateSignature OnComponentDeactivated
Called when the component has been deactivated.
Public Member Functions inherited from UObject
void AbortInsideMemberFunction () const
Abort with a member function call at the top of the callstack, helping to ensure that most platforms will stuff this object's memory into the resulting minidump.
virtual bool AreNativePropertiesIdenticalTo (UObject *Other) const
Returns whether native properties are identical to the one of the passed in component.
virtual void BeginCacheForCookedPlatformData (const ITargetPlatform *TargetPlatform)
Starts caching of platform specific data for the target platform Called when cooking before serialization so that object can prepare platform specific data Not called during normal loading of objects.
virtual void BuildSubobjectMapping (UObject *OtherObject, TMap< UObject *, UObject * > &ObjectMapping) const
Given OtherObject (which will be the same type as 'this'), recursively find any matching sub-objects from 'this' that also exist within OtherObject, and add the mappings to ObjectMapping.
void CallAddReferencedObjects (FReferenceCollector &Collector)
Helper function to call AddReferencedObjects for this object's class.
void CallFunction (FFrame &Stack, RESULT_DECL, UFunction *Function)
Internal VM method for executing a function.
bool CallFunctionByNameWithArguments (const TCHAR *Cmd, FOutputDevice &Ar, UObject *Executor, bool bForceCallWithNonExec=false)
Handle calling a function by name when executed from the console or a command line.
virtual bool CanEditChange (const FEditPropertyChain &PropertyChain) const
Alternate version of CanEditChange that includes the full property chain leading to the property in question.
bool CanModify () const
Utility to allow overrides of Modify to avoid doing work if this object cannot be safely modified.
bool CheckDefaultSubobjects (bool bForceCheck=false) const
Checks default sub-object assumptions.
virtual void ClearAllCachedCookedPlatformData ()
Clear all cached cooked platform data.
virtual void ClearCachedCookedPlatformData (const ITargetPlatform *TargetPlatform)
Clears cached cooked platform data for specific platform.
virtual void CollectSaveOverrides (FObjectCollectSaveOverridesContext SaveContext)
Collect any save override state.
bool ConditionalBeginDestroy ()
Called before destroying the object.
bool ConditionalFinishDestroy ()
Called when an object is actually destroyed, memory should never be accessed again.
void ConditionalPostLoad ()
PostLoad if needed.
void ConditionalPostLoadSubobjects (struct FObjectInstancingGraph *OuterInstanceGraph=NULL)
Instances subobjects and components for objects being loaded from disk, if necessary.
virtual bool ConformSparseClassDataStruct (UScriptStruct *SourceSparseClassDataStruct, void *SourceSparseClassData) const
void CookAdditionalFiles (const TCHAR *PackageFilename, const ITargetPlatform *TargetPlatform, TFunctionRef< void(const TCHAR *Filename, void *Data, int64 Size)> WriteAdditionalFile)
Called during cook to allow objects to generate additional cooked files alongside their cooked package.
TSharedPtr< ITransactionObjectAnnotation > CreateAndRestoreTransactionAnnotation (FArchive &Ar) const
Create and restore a previously serialized annotation object with any external data required for applying a transaction.
DECLARE_DELEGATE_RetVal_OneParam (bool, FOnGetPreviewPlatform, FName &)
Delegate to return the current preview platform name, or NAME_None if no preview platform is currently active.
DECLARE_FUNCTION (execAddMulticastDelegate)
DECLARE_FUNCTION (execArrayConst)
DECLARE_FUNCTION (execArrayElement)
DECLARE_FUNCTION (execArrayGetByRef)
DECLARE_FUNCTION (execAssert)
DECLARE_FUNCTION (execAutoRtfmAbortIfNot)
DECLARE_FUNCTION (execAutoRtfmStopTransact)
DECLARE_FUNCTION (execAutoRtfmTransact)
DECLARE_FUNCTION (execBindDelegate)
DECLARE_FUNCTION (execBitFieldConst)
DECLARE_FUNCTION (execBoolVariable)
DECLARE_FUNCTION (execBreakpoint)
Breakpoint; only observed in the editor; executing it at any other time is a NOP.
DECLARE_FUNCTION (execByteConst)
DECLARE_FUNCTION (execCallMathFunction)
DECLARE_FUNCTION (execCallMulticastDelegate)
DECLARE_FUNCTION (execCast)
DECLARE_FUNCTION (execClassContext)
DECLARE_FUNCTION (execClassDefaultVariable)
DECLARE_FUNCTION (execClassSparseDataVariable)
DECLARE_FUNCTION (execClearMulticastDelegate)
DECLARE_FUNCTION (execComputedJump)
DECLARE_FUNCTION (execContext)
DECLARE_FUNCTION (execContext_FailSilent)
DECLARE_FUNCTION (execDefaultVariable)
DECLARE_FUNCTION (execDoubleConst)
DECLARE_FUNCTION (execDoubleToFloatCast)
DECLARE_FUNCTION (execDynamicCast)
DECLARE_FUNCTION (execDynArrayAdd)
DECLARE_FUNCTION (execDynArrayAddItem)
DECLARE_FUNCTION (execDynArrayFind)
DECLARE_FUNCTION (execDynArrayFindStruct)
DECLARE_FUNCTION (execDynArrayInsert)
DECLARE_FUNCTION (execDynArrayInsertItem)
DECLARE_FUNCTION (execDynArrayRemove)
DECLARE_FUNCTION (execDynArrayRemoveItem)
DECLARE_FUNCTION (execDynArraySort)
DECLARE_FUNCTION (execEatReturnValue)
DECLARE_FUNCTION (execEmptyParmValue)
DECLARE_FUNCTION (execEndFunctionParms)
DECLARE_FUNCTION (execEndOfScript)
DECLARE_FUNCTION (execEqualEqual_DelegateDelegate)
DECLARE_FUNCTION (execEqualEqual_DelegateFunction)
DECLARE_FUNCTION (execFalse)
DECLARE_FUNCTION (execFieldPathConst)
DECLARE_FUNCTION (execFinalFunction)
DECLARE_FUNCTION (execFloatConst)
DECLARE_FUNCTION (execFloatToDoubleCast)
DECLARE_FUNCTION (execGetDynArrayElement)
DECLARE_FUNCTION (execGetDynArrayLength)
DECLARE_FUNCTION (execInstanceDelegate)
DECLARE_FUNCTION (execInstanceVariable)
DECLARE_FUNCTION (execInstrumentation)
Instrumentation event for profiling; only observed in the builds with blueprint instrumentation.
DECLARE_FUNCTION (execInt64Const)
DECLARE_FUNCTION (execIntConst)
DECLARE_FUNCTION (execIntConstByte)
DECLARE_FUNCTION (execInterfaceCast)
DECLARE_FUNCTION (execInterfaceContext)
DECLARE_FUNCTION (execInterfaceToBool)
DECLARE_FUNCTION (execInterfaceToInterface)
DECLARE_FUNCTION (execInterfaceToObject)
DECLARE_FUNCTION (execInterfaceVariable)
DECLARE_FUNCTION (execIntOne)
DECLARE_FUNCTION (execIntZero)
DECLARE_FUNCTION (execJump)
DECLARE_FUNCTION (execJumpIfNot)
DECLARE_FUNCTION (execLet)
DECLARE_FUNCTION (execLetBool)
DECLARE_FUNCTION (execLetDelegate)
DECLARE_FUNCTION (execLetMulticastDelegate)
DECLARE_FUNCTION (execLetObj)
DECLARE_FUNCTION (execLetValueOnPersistentFrame)
DECLARE_FUNCTION (execLetWeakObjPtr)
DECLARE_FUNCTION (execLocalFinalFunction)
DECLARE_FUNCTION (execLocalOutVariable)
DECLARE_FUNCTION (execLocalVariable)
DECLARE_FUNCTION (execLocalVirtualFunction)
DECLARE_FUNCTION (execMapConst)
DECLARE_FUNCTION (execMetaCast)
DECLARE_FUNCTION (execNameConst)
DECLARE_FUNCTION (execNativeParm)
DECLARE_FUNCTION (execNew)
DECLARE_FUNCTION (execNoObject)
DECLARE_FUNCTION (execNotEqual_DelegateDelegate)
DECLARE_FUNCTION (execNotEqual_DelegateFunction)
DECLARE_FUNCTION (execNothing)
DECLARE_FUNCTION (execNothingInt32)
DECLARE_FUNCTION (execNothingOp4a)
DECLARE_FUNCTION (execNullInterface)
DECLARE_FUNCTION (execObjectConst)
DECLARE_FUNCTION (execObjectToBool)
DECLARE_FUNCTION (execObjectToInterface)
DECLARE_FUNCTION (execPopExecutionFlow)
Pops a code offset from the execution flow stack and starts execution there.
DECLARE_FUNCTION (execPopExecutionFlowIfNot)
Pops a code offset from the execution flow stack and starts execution there, if a condition is not true.
DECLARE_FUNCTION (execPropertyConst)
DECLARE_FUNCTION (execPushExecutionFlow)
Push a code offset onto the execution flow stack for future execution.
DECLARE_FUNCTION (execRemoveMulticastDelegate)
DECLARE_FUNCTION (execReturnNothing)
failsafe for functions that return a value - returns the zero value for a property and logs that control reached the end of a non-void function
DECLARE_FUNCTION (execRotationConst)
DECLARE_FUNCTION (execSelf)
DECLARE_FUNCTION (execSetArray)
DECLARE_FUNCTION (execSetConst)
DECLARE_FUNCTION (execSetDynArrayElement)
DECLARE_FUNCTION (execSetDynArrayLength)
DECLARE_FUNCTION (execSetMap)
DECLARE_FUNCTION (execSetSet)
DECLARE_FUNCTION (execSkipOffsetConst)
DECLARE_FUNCTION (execSoftObjectConst)
DECLARE_FUNCTION (execStringConst)
DECLARE_FUNCTION (execStructCmpEq)
DECLARE_FUNCTION (execStructCmpNe)
DECLARE_FUNCTION (execStructConst)
DECLARE_FUNCTION (execStructMember)
DECLARE_FUNCTION (execStructMemberContext)
DECLARE_FUNCTION (execSwitchValue)
DECLARE_FUNCTION (execTextConst)
DECLARE_FUNCTION (execTracepoint)
Tracepoint; only observed in the editor; executing it at any other time is a NOP.
DECLARE_FUNCTION (execTransformConst)
DECLARE_FUNCTION (execTrue)
DECLARE_FUNCTION (execUInt64Const)
DECLARE_FUNCTION (execUndefined)
DECLARE_FUNCTION (execUnicodeStringConst)
DECLARE_FUNCTION (execVector3fConst)
DECLARE_FUNCTION (execVectorConst)
DECLARE_FUNCTION (execVirtualFunction)
DECLARE_FUNCTION (execWireTracepoint)
DECLARE_FUNCTION (ProcessInternal)
Internal function call processing.
void DestroyNonNativeProperties ()
Destroy properties that won't be destroyed by the native destructor.
void ExecuteUbergraph (int32 EntryPoint)
Execute the ubergraph from a specific entry point.
virtual void ExportCustomProperties (FOutputDevice &Out, uint32 Indent)
Exports the property values for the specified object as text to the output device.
UFunction * FindFunction (FName InName) const
Returns a UFunction with the specified name, wrapper for UClass::FindFunctionByName()
UFunction * FindFunctionChecked (FName InName) const
Version of FindFunction() that will assert if the function was not found.
TSharedPtr< ITransactionObjectAnnotation > FindOrCreateTransactionAnnotation () const
Find or create and populate an annotation object with any external data required for applying a transaction.
virtual void FinishDestroy ()
Called to finish destroying the object.
virtual void GetAdditionalAssetDataObjectsForCook (FArchiveCookContext &CookContext, TArray< UObject * > &OutObjects) const
Get an additional object that should be added to the AssetDatas stored for a cooked package, to handle objects stripped from cooked packages.
UObject * GetArchetype () const
Return the template this object is based on.
void GetArchetypeInstances (TArray< UObject * > &Instances)
Builds a list of objects which have this object in their archetype chain.
virtual void GetAssetRegistryTagMetadata (TMap< FName, FAssetRegistryTagMetadata > &OutMetadata) const
Gathers a collection of asset registry tag metadata.
void GetAssetRegistryTags (FAssetData &Out) const
virtual void GetAssetRegistryTags (FAssetRegistryTagsContext Context) const
Gathers a list of asset registry searchable tags which are name/value pairs with some type information This only needs to be implemented for asset objects.
void GetAssetRegistryTags (FAssetRegistryTagsContext Context, FAssetData &Out) const
Gathers a list of asset registry tags for an FAssetData.
virtual const TCHAR * GetConfigOverridePlatform () const
Returns the override config hierarchy platform (if NDAd platforms need defaults to not be in Base*.ini but still want editor to load them)
FString GetDefaultConfigFilename () const
Get the default config filename for the specified UObject.
virtual FString GetDesc ()
Return a one line description of an object for viewing in the thumbnail view of the generic browser.
FString GetDetailedInfo () const
This will return detail info about this specific object.
virtual FName GetExporterName (void)
Returns the name of the exporter factory used to export this object Used when multiple factories have the same extension.
virtual void GetExtendedAssetRegistryTagsForSave (const ITargetPlatform *TargetPlatform, TArray< FAssetRegistryTag > &OutTags) const
Temporary interim solution to gather asset registry data at save time only.
FString GetGlobalUserConfigFilename () const
Get the global user override config filename for the specified UObject.
virtual bool GetNativePropertyValues (TMap< FString, FString > &out_PropertyValues, uint32 ExportFlags=0) const
Callback for retrieving a textual representation of natively serialized properties.
virtual uint64 GetNetPushIdDynamic () const
Should only ever be used by internal systems.
virtual void GetPreloadDependencies (TArray< UObject * > &OutDeps)
Called during cooking.
virtual void GetPrestreamPackages (TArray< UObject * > &OutPrestream)
Called during cooking.
virtual FPrimaryAssetId GetPrimaryAssetId () const
Returns an Type:Name pair representing the PrimaryAssetId for this object.
FString GetProjectUserConfigFilename () const
Get the project user override config filename for the specified UObject.
virtual void GetReplicatedCustomConditionState (FCustomPropertyConditionState &OutActiveState) const
Called when this object begins replicating to initialize the state of custom property conditions.
SIZE_T GetResourceSizeBytes (EResourceSizeMode::Type Mode)
Get the size of the object/resource for use in memory tools or to display to artists/LDs in the Editor This is the simple version which just returns the total number of bytes used by this object.
virtual void GetResourceSizeEx (FResourceSizeEx &CumulativeResourceSize)
Get the size of the object/resource for use in memory tools or to display to artists/LDs in the Editor This is the extended version which separates up the used memory into different memory regions (the actual definition of which may be platform specific).
virtual FRestoreForUObjectOverwrite * GetRestoreForUObjectOverwrite ()
Save information for StaticAllocateObject in the case of overwriting an existing object.
UScriptStruct * GetSparseClassDataStruct () const
Return the UStruct corresponding to the sidecar data structure that stores data that is constant for all instances of this class.
virtual void GetSubobjectsWithStableNamesForNetworking (TArray< UObject * > &ObjList)
Returns a list of sub-objects that have stable names for networking.
virtual bool HasNonEditorOnlyReferences () const
Called during saving to determine if the object's references are used in game even when the object itself is never loaded outside the editor (because e.g.
template<class T>
FORCEINLINE bool Implements () const
Returns true if this object implements the interface T, false otherwise.
template<class T>
bool Implements () const
Returns true if this object implements the interface T, false otherwise.
virtual void ImportCustomProperties (const TCHAR *SourceText, FFeedbackContext *Warn)
Exports the property values for the specified object as text to the output device.
void InstanceSubobjectTemplates (struct FObjectInstancingGraph *InstanceGraph=NULL)
Wrapper for calling UClass::InstanceSubobjectTemplates() for this object.
virtual bool IsAsset () const
Returns true if this object is considered an asset.
bool IsBasedOnArchetype (const UObject *const SomeObject) const
Determine if this object has SomeObject in its archetype chain.
virtual bool IsCachedCookedPlatformDataLoaded (const ITargetPlatform *TargetPlatform)
Have we finished loading all the cooked platform data for the target platforms requested in BeginCacheForCookedPlatformData.
virtual bool IsCapturingAsRootObjectForTransaction () const
Method to disable the sub object special handling in the transaction buffer for this object.
virtual bool IsEditorOnly () const
Called during saving to determine if the object is forced to be editor only or not.
virtual bool IsFullNameStableForNetworking () const
IsFullNameStableForNetworking means an object can be referred to its full path name over the network.
bool IsInBlueprint () const
Returns whether this object is contained in or part of a blueprint object.
virtual bool IsLocalizedResource () const
Returns true if this object is considered a localized resource.
virtual bool IsReadyForAsyncPostLoad () const
Called before calling PostLoad() in FAsyncPackage::PostLoadObjects().
virtual bool IsReadyForFinishDestroy ()
Called to check if the object is ready for FinishDestroy.
virtual bool IsSafeForRootSet () const
Returns true if this object is safe to add to the root set.
bool IsSelected () const
Test the selection state of a UObject.
void LoadConfig (UClass *ConfigClass=nullptr, const TCHAR *Filename=nullptr, uint32 PropagationFlags=UE::LCPF_None, class FProperty *PropertyToLoad=nullptr, TArray< UE::ConfigAccessTracking::FConfigAccessData > *OutAccessedKeys=nullptr)
Imports property values from an .ini file.
virtual void LoadedFromAnotherClass (const FName &OldClassName)
Called when the object was loaded from another class via active class redirects.
virtual void MarkAsEditorOnlySubobject ()
Called during subobject creation to mark this component as editor only, which causes it to get stripped in packaged builds.
virtual void MoveDataToSparseClassDataStruct () const
virtual bool NeedsLoadForTargetPlatform (const class ITargetPlatform *TargetPlatform) const
Called during saving to determine the load flags to save with the object.
virtual void OnCookEvent (UE::Cook::ECookEvent CookEvent, UE::Cook::FCookEventContext &Context)
Called during cooking for various events that happen on each UObject in a package during load/transform/save.
void OutputReferencers (FOutputDevice &Ar, FReferencerInformationList *Referencers=NULL)
Outputs a string to an arbitrary output device, describing the list of objects which are holding references to this one.
virtual void OverrideConfigSection (FString &SectionName)
Allows Non-PerObjectConfig classes, to override the ini section name used for loading config settings.
virtual void OverridePerObjectConfigSection (FString &SectionName)
Allows PerObjectConfig classes, to override the ini section name used for the PerObjectConfig object.
void ParseParms (const TCHAR *Parms)
Import an object from a file.
virtual void PostCDOCompiled (const FPostCDOCompiledContext &Context)
Called after the Blueprint compiler has finished generating the Class Default Object (CDO) for a class.
virtual void PostCDOContruct ()
Called after the C++ constructor has run on the Class Default Object (CDO) for a class.
virtual void PostDuplicate (bool bDuplicateForPIE)
Called after duplication & serialization and before PostLoad.
virtual void PostDuplicate (EDuplicateMode::Type DuplicateMode)
void PostEditChange ()
Intentionally non-virtual as it calls the FPropertyChangedEvent version.
virtual void PostEditImport ()
Called after importing property values for this object (paste, duplicate or .t3d import) Allow the object to perform any cleanup for properties which shouldn't be duplicated or are unsupported by the script serialization.
virtual void PostEditUndo (TSharedPtr< ITransactionObjectAnnotation > TransactionAnnotation)
Called after applying a transaction to the object in cases where transaction annotation was provided.
virtual void PostLinkerChange ()
Called in response to the linker changing, this can only happen in the editor.
virtual void PostLoadSubobjects (FObjectInstancingGraph *OuterInstanceGraph)
Instances components for objects being loaded from disk, if necessary.
virtual void PostReinitProperties ()
Called after properties are overwritten, including after subobjects initialization from a CDO.
virtual void PostReloadConfig (class FProperty *PropertyThatWasLoaded)
Called from ReloadConfig after the object has reloaded its configuration data.
virtual void PostSaveRoot (FObjectPostSaveRootContext ObjectSaveContext)
Called from within SavePackage on the passed in base/root object.
virtual void PostTransacted (const FTransactionObjectEvent &TransactionEvent)
Called after the object has been transacted in some way.
virtual void PreDestroyFromReplication ()
Called right before being marked for destruction due to network replication.
virtual void PreDuplicate (FObjectDuplicationParameters &DupParams)
Called before duplication.
virtual void PreEditChange (class FEditPropertyChain &PropertyAboutToChange)
This alternate version of PreEditChange is called when properties inside structs are modified.
virtual void PreSave (FObjectPreSaveContext SaveContext)
Presave function.
virtual void PreSaveRoot (FObjectPreSaveRootContext ObjectSaveContext)
Called from within SavePackage on the passed in base/root object.
virtual bool ProcessConsoleExec (const TCHAR *Cmd, FOutputDevice &Ar, UObject *Executor)
This function handles a console exec sent to the object; it is virtual so 'nexus' objects like a player controller can reroute the command to several different objects.
virtual void ProcessEvent (UFunction *Function, void *Parms)
Called by VM to execute a UFunction with a filled in UStruct of parameters.
void PropagatePostEditChange (TArray< UObject * > &AffectedObjects, FPropertyChangedChainEvent &PropertyChangedEvent)
Calls PostEditChange on all instances based on an archetype in AffectedObjects.
void PropagatePreEditChange (TArray< UObject * > &AffectedObjects, FEditPropertyChain &PropertyAboutToChange)
Calls PreEditChange on all instances based on an archetype in AffectedObjects.
virtual UClass * RegenerateClass (UClass *ClassToRegenerate, UObject *PreviousCDO)
Called on the target when a class is loaded with ClassGeneratedBy is loaded.
void ReinitializeProperties (UObject *SourceObject=NULL, struct FObjectInstancingGraph *InstanceGraph=NULL)
Wrapper function for InitProperties() which handles safely tearing down this object before re-initializing it from the specified source object.
void ReloadConfig (UClass *ConfigClass=NULL, const TCHAR *Filename=NULL, uint32 PropagationFlags=UE::LCPF_None, class FProperty *PropertyToLoad=NULL)
Wrapper method for LoadConfig that is used when reloading the config data for objects at runtime which have already loaded their config data at least once.
virtual bool ResolveSubobject (const TCHAR *SubObjectPath, UObject *&OutObject, bool bLoadIfExists)
Called to defer loading a subobject to its top-level container object.
void RetrieveReferencers (TArray< FReferencerInformation > *OutInternalReferencers, TArray< FReferencerInformation > *OutExternalReferencers)
Called by OutputReferencers() to get the internal list of referencers to write.
void SaveConfig (uint64 RequiredPropertyFlags=CPF_Config, const TCHAR *Filename=nullptr, FConfigCacheIni *Config=GConfig, bool bAllowCopyToDefaultObject=true)
Save configuration out to ini files.
virtual void Serialize (FStructuredArchive::FRecord Record)
void SerializeScriptProperties (FArchive &Ar) const
Serializes the script property data located at Data.
void SerializeScriptProperties (FStructuredArchive::FSlot Slot) const
Serializes the script property data located at Data.
void SetEditChangePropagationFlags (EEditChangePropagationFlags InFlags)
Called to set the flags that control how editor change events get propagated to archetype instances.
void SetLinker (FLinkerLoad *LinkerLoad, int32 LinkerIndex, bool bShouldDetachExisting=true)
Changes the linker and linker index to the passed in one.
virtual void ShutdownAfterError ()
After a critical error, perform any mission-critical cleanup, such as restoring the video mode orreleasing hardware resources.
void SkipFunction (FFrame &Stack, RESULT_DECL, UFunction *Function)
advances Stack's code past the parameters to the given Function and if the function has a return value, copies the zero value for that property to the memory for the return value
virtual void TagSubobjects (EObjectFlags NewFlags)
Tags objects that are part of the same asset with the specified object flag, used for GC checking.
void ThreadedPostLoadAssetRegistryTags (FPostLoadAssetRegistryTagsContext &Context) const
Internal use function for the AssetRegistry.
bool TryUpdateDefaultConfigFile (const FString &SpecificFileLocation="", bool bWarnIfFail=true)
Try to Saves just the section(s) for this class into the default ini file for the class (with just the changes from base)
UE_DEPRECATED (5.0, "TryUpdateDefaultConfigFile replaces UpdateDefaultConfigFile") 1 void UpdateDefaultConfigFile(const FString &SpecificFileLocation
Saves just the section(s) for this class into the default ini file for the class (with just the changes from base)
UE_DEPRECATED (5.1, "Use version that takes FPostCDOCompiledContext instead.") virtual void PostCDOCompiled()
Called after the Blueprint compiler has finished generating the Class Default Object (CDO) for a class.
UE_DEPRECATED (5.3, "Matinee has been removed in 5.0, nothing is calling PostInterpChange anymore") virtual void PostInterpChange(FProperty *PropertyThatChanged)
UE_DEPRECATED (5.3, "Please use IsDataValid(FDataValidationContext&) const as the FDataValidationContext will allow distinguishing between Warnings and Errors.") 1 virtual EDataValidationResult IsDataValid(TArray< FText > &ValidationErrors)
Generic function to validate objects during changelist validations, etc.
UE_DEPRECATED (5.3, "Please use the the const version of IsDataValid(FDataValidationContext&)") 1 virtual EDataValidationResult IsDataValid(class FDataValidationContext &Context)
UE_DEPRECATED (5.4, "Call GetDefaultSubobjects for top level subobjects or use ForEachObjectWithOuter with a more precise check") 1 void CollectDefaultSubobjects(TArray< UObject * > &OutDefaultSubobjects
Gets all subobjects inside this object that return true for IsDefaultSubobject.
UE_DEPRECATED (5.4, "Implement the version that takes FAssetRegistryTagsContext instead.") 1 virtual void GetAssetRegistryTags(TArray< FAssetRegistryTag > &OutTags) const
UE_DEPRECATED (5.5, "Multithreaded destruction of UObjects is no longer supported.") 1 virtual bool IsDestructionThreadSafe() const
Called during garbage collection to determine if an object can have its destructor called on a worker thread.
UE_DEPRECATED (5.5, "This function is no longer called. If you require this functionality, please implement ThreadedPostLoadAssetRegistryTagsOverride. \ Note that this function MUST be safe to call on a background thread. If you have functionality that doesn't meet that requirement, \ consider using the AssetRegistry's AssetAddedEvent which fires on the game thread.") virtual void PostLoadAssetRegistryTags(const FAssetData &InAssetData
void UpdateGlobalUserConfigFile ()
Saves just the section(s) for this class into the global user ini file for the class (with just the changes from base)
void UpdateProjectUserConfigFile ()
Saves just the section(s) for this class into the project user ini file for the class (with just the changes from base)
void UpdateSinglePropertyInConfigFile (const FProperty *InProperty, const FString &InConfigIniName)
Saves just the property into the global user ini file for the class (with just the changes from base)
virtual void ValidateGeneratedRepEnums (const TArray< struct FRepRecord > &ClassReps) const
virtual void WillNeverCacheCookedPlatformDataAgain ()
All caching has finished for this object (all IsCachedCookedPlatformDataLoaded functions have finished for all platforms)
Public Member Functions inherited from UObjectBaseUtility
UObjectBaseUtility ()
UObjectBaseUtility (EObjectFlags InFlags)
void AddToCluster (UObjectBaseUtility *ClusterRootOrObjectFromCluster, bool bAddAsMutableObject=false)
Adds this objects to a GC cluster that already exists.
FORCEINLINE void AddToRoot ()
Add an object to the root set.
FORCEINLINE void AppendName (FString &ResultString) const
Optimized version of GetName that appends to an existing string.
FORCEINLINE bool AtomicallyClearInternalFlags (EInternalObjectFlags FlagsToClear) const
Atomically clears passed in internal flags.
virtual bool CanBeClusterRoot () const
Called after load to determine if the object can be a cluster root.
virtual bool CanBeInCluster () const
Called during cluster construction if the object can be added to a cluster.
FORCEINLINE void ClearFlags (EObjectFlags FlagsToClear)
Clears subset of flags for a specific object.
FORCEINLINE void ClearGarbage ()
Unmarks this object as Garbage.
FORCEINLINE void ClearInternalFlags (EInternalObjectFlags FlagsToClear) const
Clears passed in internal flags.
virtual void CreateCluster ()
Called after PostLoad to create UObject cluster.
void DetachExternalPackage ()
Utility function to temporarily detach the object external package, if any GetPackage will report the outer's package once detached.
const UClass * FindNearestCommonBaseClass (const UClass *TestClass) const
Finds the most-derived class which is a parent of both TestClass and this object's class.
FORCEINLINE EObjectMark GetAllMarks () const
Returns all of the object marks on a specific object.
FString GetFullGroupName (bool bStartWithOuter) const
Walks up the chain of packages until it reaches the top level, which it ignores.
void GetFullName (const UObject *StopOuter, FString &ResultString, EObjectFullNameFlags Flags=EObjectFullNameFlags::None) const
Version of GetFullName() that eliminates unnecessary copies.
FString GetFullName (const UObject *StopOuter=NULL, EObjectFullNameFlags Flags=EObjectFullNameFlags::None) const
Returns the fully qualified pathname for this object as well as the name of the class, in the format: 'ClassName Outermost[.Outer].Name'.
void GetFullName (FStringBuilderBase &ResultString, const UObject *StopOuter=NULL, EObjectFullNameFlags Flags=EObjectFullNameFlags::None) const
Returns the fully qualified pathname for this object as well as the name of the class, in the format: 'ClassName Outermost[.Outer].Name'.
template<typename InterfaceClassType>
InterfaceClassType * GetImplementingOuter () const
Traverses the outer chain looking for the next object that implements the specified IInterface (InterfaceClass must be an IInterface)
UObjectBaseUtility * GetImplementingOuterObject (const UClass *InInterfaceClass) const
Traverses the outer chain looking for the next object that implements the specified UInterface (InInterfaceClass must be a subclass of UInterface)
void * GetInterfaceAddress (UClass *InterfaceClass)
Returns a pointer to this object safely converted to a pointer of the specified interface class.
FORCEINLINE EInternalObjectFlags GetInternalFlags () const
Gets internal flags.
class FLinkerLoad * GetLinker () const
Returns the linker for this object.
int32 GetLinkerCustomVersion (FGuid CustomVersionKey) const
Returns the custom version of the linker for this object corresponding to the given custom version key.
int32 GetLinkerIndex () const
Returns this object's LinkerIndex.
int32 GetLinkerLicenseeUEVersion () const
Returns the licensee version of the linker for this object.
FPackageFileVersion GetLinkerUEVersion () const
Returns the UE version of the linker for this object.
FORCEINLINE EObjectFlags GetMaskedFlags (EObjectFlags Mask=RF_AllFlags) const
Returns object flags that are both in the mask and set on the object.
FORCEINLINE FString GetName () const
Returns the name of this object (with no path information)
FORCEINLINE void GetName (FString &ResultString) const
Optimized version of GetName that overwrites an existing string.
void * GetNativeInterfaceAddress (UClass *InterfaceClass)
Returns a pointer to the I* native interface object that this object implements.
const void * GetNativeInterfaceAddress (UClass *InterfaceClass) const
Returns a pointer to the const I* native interface object that this object implements.
UPackage * GetOutermost () const
Legacy function, has the same behavior as GetPackage use GetPackage instead.
UObject * GetOutermostObject () const
Walks up the list of outers until it finds the top-level one that isn't a package.
UPackage * GetPackage () const
Walks up the list of outers until it finds a package directly associated with the object.
void GetPathName (const UObject *StopOuter, FString &ResultString) const
Versions of GetPathName() that eliminates unnecessary copies and allocations.
void GetPathName (const UObject *StopOuter, FStringBuilderBase &ResultString) const
FString GetPathName (const UObject *StopOuter=NULL) const
Returns the fully qualified pathname for this object, in the format: 'Outermost[.Outer].Name'.
FORCEINLINE TStatId GetStatID (bool bForDeferredUse=false) const
Returns the stat ID of the object, used for profiling.
template<typename T>
T * GetTypedOuter () const
Traverses the outer chain searching for the next object of a certain type.
UObject * GetTypedOuter (UClass *Target) const
Traverses the outer chain searching for the next object of a certain type.
virtual UE_INTERNAL UE::Core::FVersePath GetVersePath () const
Gets the versepath of the UObject.
FORCEINLINE bool HasAllFlags (EObjectFlags FlagsToCheck) const
Used to safely check whether all of the passed in flags are set.
FORCEINLINE bool HasAllMarks (EObjectMark Marks) const
Tests an object for having ALL of a set of marks.
FORCEINLINE bool HasAnyFlags (EObjectFlags FlagsToCheck) const
Used to safely check whether any of the passed in flags are set.
FORCEINLINE bool HasAnyInternalFlags (EInternalObjectFlags FlagsToCheck) const
Used to safely check whether any of the passed in internal flags are set.
FORCEINLINE bool HasAnyMarks (EObjectMark Marks) const
Tests an object for having ANY of a set of marks.
template<class T>
bool IsA () const
Returns true if this object is of the template type.
template<typename OtherClassType>
FORCEINLINE bool IsA (OtherClassType SomeBase) const
Returns true if this object is of the specified type.
bool IsDefaultSubobject () const
Returns whether this is a subobject (template or instance) that was originally defined inside a default class object.
bool IsIn (const UObject *SomeOuter) const
Return the dispatch to IsInOuter or IsInPackage depending on SomeOuter's class.
bool IsIn (const UPackage *SomePackage) const
Overload to determine if an object is in the specified package which can now be different than its outer chain.
bool IsInA (const UClass *SomeBaseClass) const
Find out if this object is inside (has an outer) that is of the specified class.
bool IsInOuter (const UObject *SomeOuter) const
Returns true if the object is contained in the specified outer.
bool IsInPackage (const UPackage *SomePackage) const
Returns true if the object is contained in the specified package.
FORCEINLINE bool IsNative () const
Checks if the object is native.
bool IsPackageExternal () const
Get the object packaging mode.
FORCEINLINE bool IsRooted () const
Returns true if this object is explicitly rooted.
bool IsTemplate (EObjectFlags TemplateTypes=RF_ArchetypeObject|RF_ClassDefaultObject) const
Determines whether this object is a template object by checking flags on the object and the outer chain.
bool IsTemplateForSubobjects (EObjectFlags TemplateTypes=RF_ClassDefaultObject|RF_DefaultSubObject|RF_InheritableComponentTemplate) const
Returns whether this is a template that can be used to create instanced subobjects.
FORCEINLINE bool IsUnreachable () const
Checks if the object is unreachable.
FORCEINLINE void Mark (EObjectMark Marks) const
Adds marks to an object.
FORCEINLINE void MarkAsGarbage ()
Marks this object as Garbage.
bool MarkPackageDirty () const
Finds the outermost package and marks it dirty.
virtual void OnClusterMarkedAsPendingKill ()
Called during Garbage Collection to perform additional cleanup when the cluster is about to be destroyed due to PendingKill flag being set on it.
FORCEINLINE bool operator< (const UObjectBaseUtility &Other) const
Overloaded < operator.
void ReattachExternalPackage ()
Utility function to reattach the object external package, if any GetPackage will report the object external package if set after this call.
FORCEINLINE void RemoveFromRoot ()
Remove an object from the root set.
bool RootPackageHasAnyFlags (uint32 CheckFlagMask) const
Checks whether this object's top-most package has any of the specified flags.
FORCEINLINE void SetFlags (EObjectFlags NewFlags)
Modifies object flags for a specific object.
FORCEINLINE void SetInternalFlags (EInternalObjectFlags FlagsToSet) const
Clears passed in internal flags.
UE_DEPRECATED (5.0, "Use GetLinkerLicenseeUEVersion instead") inline int32 GetLinkerLicenseeUE4Version() const
UE_DEPRECATED (5.0, "Use GetLinkerUEVersion instead which returns the version as a FPackageFileVersion. See the @FPackageFileVersion documentation for further details") inline int32 GetLinkerUE4Version() const
UE_DEPRECATED (5.4, "Use IsGarbageEliminationEnabled()") static inline bool IsPendingKillEnabled()
UE_DEPRECATED (5.5, "ThisThreadAtomicallyClearedRFUnreachable() should no longer be used. Reachability flags can only be modified by the garbage collector.") bool ThisThreadAtomicallyClearedRFUnreachable()
Atomically clear the unreachable flag.
FORCEINLINE void UnMark (EObjectMark Marks) const
Removes marks from and object.
Public Member Functions inherited from UObjectBase
UObjectBase (UClass *InClass, EObjectFlags InFlags, EInternalObjectFlags InInternalFlags, UObject *InOuter, FName InName, int32 InInternalIndex=-1, int32 InSerialNumber=0, FRemoteObjectId InRemoteId=FRemoteObjectId())
Constructor used by StaticAllocateObject.
virtual ~UObjectBase ()
Final destructor, removes the object from the object array, and indirectly, from any annotations.
void AddRef () const
Increments ref-count on the object.
FORCENOINLINE void AtomicallyClearFlags (EObjectFlags FlagsToClear)
Atomically clears the specified flags.
FORCENOINLINE void AtomicallySetFlags (EObjectFlags FlagsToAdd)
Atomically adds the specified flags.
FORCEINLINE UClass * GetClass () const
Returns the UClass that defines the fields of this object.
UPackage * GetExternalPackage () const
Returns the external UPackage associated with this object, if any.
UPackage * GetExternalPackageInternal () const
Returns the external UPackage for this object, if any, NOT THREAD SAFE, used by internal gc reference collecting.
FORCEINLINE EObjectFlags GetFlags () const
Retrieve the object flags directly.
FORCEINLINE FName GetFName () const
Returns the logical name of this object.
virtual FName GetFNameForStatID () const
Overridable method to return a logical name for identification in stats.
FORCEINLINE UObject * GetOuter () const
Returns the UObject this object resides in.
FORCEINLINE uint32 GetUniqueID () const
Returns the unique ID of the object...these are reused so it is only unique while the object is alive.
bool IsValidLowLevel () const
Checks to see if the object appears to be valid.
bool IsValidLowLevelFast (bool bRecursive=true) const
Faster version of IsValidLowLevel.
void MarkAsReachable () const
Marks the object as Reachable if it's currently marked as MaybeUnreachable by incremental GC.
void ReleaseRef () const
Release ref-count on the object.
void SetExternalPackage (UPackage *InPackage)
Associate an external package directly to this object.
Public Member Functions inherited from IAsyncPhysicsStateProcessor
virtual void CollectBodySetupsWithPhysicsMeshesToCreate (TSet< UBodySetup * > &OutBodySetups) const
Returns body setups that needs to create their physics meshes before physics state asynchronous creation.
Data Fields
float AngularBreakThreshold
float AngularPlasticityThreshold
bool bEnableDriveY
bool bool bEnableDriveZ
bool bEnableSwingDrive
bool bEnableTwistDrive
FName BoneName1
FName UPrimitiveComponent FName BoneName2
FName UPrimitiveComponent * Component2
float float InForceLimit
float LimitSize
float LinearBreakThreshold
float LinearPlasticityThreshold
FVector & OutAngularForce
FName & OutBoneName1
FName UPrimitiveComponent FName & OutBoneName2
FName UPrimitiveComponent *& OutComponent2
float EConstraintPlasticityType PlasticityType
float ProjectionAngularAlpha
float float float ProjectionAngularTolerance
float float ProjectionLinearTolerance
float Swing1LimitAngle
float Swing2LimitAngle
float TwistLimitAngle
float VelocityStrength
Data Fields inherited from USceneComponent
AttachType
bool bCallModify = true)
bool bNewAbsoluteRotation = false
bool bool bNewAbsoluteScale = false)
FBoxSphereBounds Bounds
Current bounds of the component.
bool bPropagateToChildren
bool bSweep
FRotator bool bSweep
bool FHitResult bool bTeleport
FRotator bool FHitResult bool bTeleport
FName EAttachmentRule EAttachmentRule EAttachmentRule bool bWeldSimulatedBodies
Category
TArray< USceneComponent * > &Children const
FIsRootComponentChanged IsRootComponentChanged
Delegate invoked when this scene component becomes the actor's root component or when it no longer is.
FName EAttachmentRule LocationRule
FRotator NewRotation
FName EAttachmentRule EAttachmentRule RotationRule
FName EAttachmentRule EAttachmentRule EAttachmentRule ScaleRule
FName SocketName
bool FHitResult & SweepHitResult
FRotator bool FHitResult & SweepHitResult
ERelativeTransformSpace TransformSpace = RTS_World) const
FTransformUpdated TransformUpdated
Delegate called when this component is moved.
Data Fields inherited from UActorComponent
uint8 bAllowAnyoneToDestroyMe:1
Can this component be destroyed (via K2_DestroyComponent) by any parent.
uint8 bAllowConcurrentTick:1
Can we tick this concurrently on other threads?
uint8 bAutoRegister:1
Does this component automatically register with its owner.
UPROPERTY() uint8 bEditableWhenInherited uint8 bNavigationRelevant: 1
Whether the component is activated at creation or must be explicitly activated.
uint8 bNeverNeedsRenderUpdate:1
If true, this component never needs a render update.
bool bReset =false)
uint8 bTickInEditor:1
Should this component be ticked in the editor.
uint8 bWantsInitializeComponent:1
Whether this component can potentially influence navigation.
float SimSeconds
Data Fields inherited from UObject
bool bIncludeNestedSubobjects =false) const
TArray< FAssetRegistryTag > &OutTagsAndValuesToUpdate const final
Protected Member Functions
FBox GetBodyBoxInternal (EConstraintFrame::Type Frame, FName InBoneName) const
Internal util to get body box from actor/component name/bone name information.
FBodyInstance * GetBodyInstance (EConstraintFrame::Type Frame) const
Get the body instance that we want to constrain to.
FTransform GetBodyTransformInternal (EConstraintFrame::Type Frame, FName InBoneName) const
Internal util to get body transform from actor/component name/bone name information.
UPrimitiveComponent * GetComponentInternal (EConstraintFrame::Type Frame) const
Internal util to get component from actor/component name.
float GetConstraintScale () const
Returns the scale of the constraint as it will be passed into the ConstraintInstance.
Chaos::FPhysicsObject * GetPhysicsObject (EConstraintFrame::Type Frame) const
Get the physics object that we want to constrain to.
void OnConstraintBrokenHandler (FConstraintInstance *BrokenConstraint)
Routes the FConstraint callback to the dynamic delegate.
void OnPlasticDeformationHandler (FConstraintInstance *Constraint)
Routes the FConstraint callback to the dynamic delegate.
Protected Member Functions inherited from USceneComponent
FORCEINLINE bool AreDynamicDataChangesAllowed (bool bIgnoreStationary=true) const
Determine if dynamic data is allowed to be changed.
FORCEINLINE FTransform CalcNewComponentToWorld (const FTransform &NewRelativeTransform, const USceneComponent *Parent=nullptr, FName SocketName=NAME_None) const
Calculate the new ComponentToWorld transform for this component.
FTransform CalcNewComponentToWorld_GeneralCase (const FTransform &NewRelativeTransform, const USceneComponent *Parent, FName SocketName) const
Utility function to handle calculating transform with a parent.
bool CheckStaticMobilityAndWarn (const FText &ActionText) const
Check if mobility is set to non-static.
bool HasGroupedMovementUpdate (const FScopedMovementUpdate &ScopedUpdate) const
bool InternalSetWorldLocationAndRotation (FVector NewLocation, const FQuat &NewQuat, bool bNoPhysics=false, ETeleportType Teleport=ETeleportType::None)
Internal helper, for use from MoveComponent().
bool IsDeferringMovementUpdates (const FScopedMovementUpdate &ScopedUpdate) const
virtual bool MoveComponentImpl (const FVector &Delta, const FQuat &NewRotation, bool bSweep, FHitResult *Hit=NULL, EMoveComponentFlags MoveFlags=MOVECOMP_NoFlags, ETeleportType Teleport=ETeleportType::None)
Override this method for custom behavior for MoveComponent.
virtual void OnChildAttached (USceneComponent *ChildComponent)
Called after a child scene component is attached to this component.
virtual void OnChildDetached (USceneComponent *ChildComponent)
Called after a child scene component is detached from this component.
virtual void OnHiddenInGameChanged ()
Overridable internal function to respond to changes in the hidden in game value of the component.
virtual void OnUpdateTransform (EUpdateTransformFlags UpdateTransformFlags, ETeleportType Teleport=ETeleportType::None)
Native callback when this component is moved.
virtual void OnVisibilityChanged ()
Overridable internal function to respond to changes in the visibility of the component.
void PostUpdateNavigationData ()
Called after changing transform, tries to update navigation octree for owner.
void UpdateNavigationData ()
Called after changing transform, tries to update navigation octree for this component.
virtual bool UpdateOverlapsImpl (const TOverlapArrayView *PendingOverlaps=nullptr, bool bDoNotifies=true, const TOverlapArrayView *OverlapsAtEndLocation=nullptr)
Internal helper for UpdateOverlaps.
Protected Member Functions inherited from UActorComponent
virtual void CreateRenderState_Concurrent (FRegisterComponentContext *Context)
Used to create any rendering thread information for this component.
void DeferRemoveAsyncPhysicsTick ()
Defers the call to SetAsyncPhysicsTickEnabled(false) to the next async tick.
virtual void DestroyRenderState_Concurrent ()
Used to shut down any rendering thread structure for this component.
void HandleCanEverAffectNavigationChange (bool bForceUpdate=false)
Makes sure navigation system has up to date information regarding component's navigation relevancy and if it can affect navigation at all.
virtual bool HasValidPhysicsState () const
Used to check that DestroyPhysicsState() is working correctly.
bool NeedsInitialization () const
Convenience method for testing whether or not we are still be constructed / initialized.
virtual void OnCreatePhysicsState ()
Used to create any physics engine information for this component.
virtual void OnDestroyPhysicsState ()
Used to shut down and physics engine structure for this component.
virtual void OnPreRegistered ()
Called once the component is pre-registered.
virtual void OnPreUnregister ()
Called by PreUnregisterComponentFromWorld when the component is being pre-unregistered.
virtual void OnPreUnregistered ()
Called once the component is pre-unregistered.
bool OwnerNeedsInitialization () const
Convenience method for testing whether or not our owner is still being constructed / initialized.
virtual void PrecachePSOs ()
Precache all PSOs which can be used by the actor component.
virtual void RegisterComponentTickFunctions (bool bRegister)
Virtual call chain to register all tick functions.
virtual void SendRenderDynamicData_Concurrent ()
Called to send dynamic data for this component to the rendering thread.
virtual void SendRenderInstanceData_Concurrent ()
Called to send instance data for this component to the rendering thread.
virtual void SendRenderTransform_Concurrent ()
Called to send a transform update for this component to the rendering thread.
void SetAsyncPhysicsTickEnabled (bool bEnabled)
Sets bAsyncPhysicsTickEnabled which determines whether to use use the async physics tick with this component.
void SetIsReplicatedByDefault (const bool bNewReplicates)
Sets the value of bReplicates without causing other side effects to this instance.
virtual bool ShouldActivate () const
Return true if this component is in a state where it can be activated normally.
virtual bool ShouldAsyncCreatePhysicsState (UWorld *WorldContext) const
Returns whether this component should create its physics state asynchronously.
virtual bool ShouldAsyncDestroyPhysicsState () const
Returns whether this component should destroy its physics state asynchronously.
virtual bool ShouldCreatePhysicsState () const
Return true if CreatePhysicsState() should be called.
UPROPERTY () TArray< TObjectPtr< UAssetUserData > > AssetUserData
Array of user data stored with the component.
Protected Member Functions inherited from UObject
bool CanCheckDefaultSubObjects (bool bForceCheck, bool &bResult) const
Checks it's ok to perform subobjects check at this time.
virtual bool CheckDefaultSubobjectsInternal () const
Checks default sub-object assumptions.
virtual TSharedPtr< ITransactionObjectAnnotation > FactoryTransactionAnnotation (const ETransactionAnnotationCreationMode InCreationMode) const
virtual FString GetDetailedInfoInternal () const
This function actually does the work for the GetDetailedInfo() and is virtual.
virtual void ThreadedPostLoadAssetRegistryTagsOverride (FPostLoadAssetRegistryTagsContext &Context) const
Performs fixup on loaded asset registry data.
Protected Member Functions inherited from UObjectBase
UObjectBase ()
UObjectBase (EObjectFlags InFlags)
Constructor used for bootstrapping.
virtual void DeferredRegister (UClass *UClassStaticClass, const TCHAR *PackageName, const TCHAR *Name)
Convert a boot-strap registered class into a real one, add to uobject array, etc.
void LowLevelRename (FName NewName, UObject *NewOuter=NULL)
Just change the FName and Outer and rehash into name hash tables.
void Register (class UClass *(*StaticClassFn)(), const TCHAR *PackageName, const TCHAR *Name)
Enqueue the registration for this object.
virtual void RegisterDependencies ()
Force any base classes to be registered first.
UE_DEPRECATED (5.3, "This function is not thread-safe. Use AtomicallySetFlags or AtomicallyClearFlags instead.") FORCEINLINE void SetFlagsTo(EObjectFlags NewFlags)
Set the object flags directly.
UE_DEPRECATED (5.6, "Use the new method above and specify UClass::StaticClass as the first argument") 1 void Register(const TCHAR *PackageName
Private Member Functions
GENERATED_UCLASS_BODY () UPROPERTY() TObjectPtr< AActor > ConstraintActor1
Pointer to first Actor to constrain.
void OnConstraintBrokenWrapper (int32 ConstraintIndex)
Wrapper that calls our constraint broken delegate.
void OnPlasticDeformationWrapper (int32 ConstraintIndex)
Wrapper that calls our constraint plasticity delegate.
UPROPERTY () FConstrainComponentPropName ComponentName1
Name of first component property to constrain.
UPROPERTY () FConstrainComponentPropName ComponentName2
Name of second component property to constrain.
UPROPERTY () FConstraintBrokenSignature OnConstraintBroken
Notification when constraint is broken.
UPROPERTY () FPlasticDeformationEventSignature OnPlasticDeformation
Notification when constraint plasticity drive target changes.
UPROPERTY () TObjectPtr< AActor > ConstraintActor2
Pointer to second Actor to constrain.
UPROPERTY () TObjectPtr< class UPhysicsConstraintTemplate > ConstraintSetup_DEPRECATED
Private Attributes
bool bIsBrokenLocal
TWeakObjectPtr< UPrimitiveComponent > OverrideComponent1
Allows direct setting of first component to constraint.
TWeakObjectPtr< UPrimitiveComponent > OverrideComponent2
Allows direct setting of second component to constraint.
Friends
class FConstraintComponentVisualizer
Additional Inherited Members
Public Types inherited from UObject
enum class ENetFields_Private { NETFIELD_REP_START = 0 , NETFIELD_REP_END = -1 }
using FPostCDOCompiledContext = FObjectPostCDOCompiledContext
Static Public Member Functions inherited from USceneComponent
static void ConvertAttachLocation (EAttachLocation::Type InAttachLocation, EAttachmentRule &InOutLocationRule, EAttachmentRule &InOutRotationRule, EAttachmentRule &InOutScaleRule)
Backwards compatibility: Used to convert old-style EAttachLocation to new-style EAttachmentRules.
static const FName GetAbsoluteLocationPropertyName ()
Gets the property name for bAbsoluteLocation.
static const FName GetAbsoluteRotationPropertyName ()
Gets the property name for bAbsoluteRotation.
static const FName GetAbsoluteScalePropertyName ()
Gets the property name for bAbsoluteScale.
static const FName GetRelativeLocationPropertyName ()
Gets the property name for RelativeLocation.
static const FName GetRelativeRotationPropertyName ()
Gets the property name for RelativeRotation.
static const FName GetRelativeScale3DPropertyName ()
Gets the property name for RelativeScale3D.
static const FName GetVisiblePropertyName ()
Gets the property name for bVisible.
Static Public Member Functions inherited from UActorComponent
static void AddReferencedObjects (UObject *InThis, FReferenceCollector &Collector)
Static Public Member Functions inherited from UObject
static void AddReferencedObjects (UObject *InThis, FReferenceCollector &Collector)
Callback used to allow object register its direct object references that are not already covered by the token stream.
static bool CanCreateInCurrentContext (UObject *Template)
Determines if you can create an object from the supplied template in the current context (editor, client only, dedicated server, game/listen) This calls NeedsLoadForClient & NeedsLoadForServer.
static UObject * GetArchetypeFromRequiredInfo (const UClass *Class, const UObject *Outer, FName Name, EObjectFlags ObjectFlags)
Return the template that an object with this class, outer and name would be.
static TSet< FName > & GetMetaDataTagsForAssetRegistry ()
The metadata tags to be transferred from the FMetaData to the Asset Registry.
static const FName & SourceFileTagName ()
Get the common tag name used for all asset source file import paths.
static void UpdateClassesExcludedFromDedicatedClient (const TArray< FString > &InClassNames, const TArray< FString > &InModulesNames)
Update the list of classes that we should exclude from dedicated client builds.
static void UpdateClassesExcludedFromDedicatedServer (const TArray< FString > &InClassNames, const TArray< FString > &InModulesNames)
Update the list of classes that we should exclude from dedicated server builds.
Static Public Member Functions inherited from UObjectBaseUtility
static bool IsGarbageEliminationEnabled ()
Helper function to access the private bGarbageEliminationEnabled variable.
static void ReloadObjectsFromModifiedConfigSections (const class FConfigModificationTracker *ChangeTracker)
static void SetGarbageEliminationEnabled (bool bEnabled)
Helper function to set the private bGarbageEliminationEnabled variable.
Static Public Member Functions inherited from UObjectBase
static void PrefetchClass (UObject *Object)
static void PrefetchOuter (UObject *Object)
static FString RemoveClassPrefix (const TCHAR *ClassName)
Removes the class prefix from the given string.
Static Public Attributes inherited from USceneComponent
static int32 SkipUpdateOverlapsOptimEnabled
Global flag to enable/disable overlap optimizations, settable with p.SkipUpdateOverlapsOptimEnabled cvar.
Static Public Attributes inherited from UActorComponent
static TMap< UActorComponent *, TArray< FSimpleMemberReference > > AllUCSModifiedProperties
static FTransactionallySafeRWLock AllUCSModifiedPropertiesLock
static const FString ComponentTemplateNameSuffix
Suffix used to identify template component instances.
static FOnMarkRenderStateDirty MarkRenderStateDirtyEvent
Called When render state is marked dirty.
Static Public Attributes inherited from UObject
static FOnGetPreviewPlatform OnGetPreviewPlatform
Protected Types inherited from UActorComponent
enum class EComponentRegistrationState {
None , PreRegistering , PreRegistered , PreUnregistering ,
PreUnregistered
}
Protected Types inherited from UObject
enum class ETransactionAnnotationCreationMode : uint8 { DefaultInstance , FindOrCreate }
Factory a new annotation object and optionally populate it with data.
Static Protected Member Functions inherited from UActorComponent
static bool CanBeHLODRelevant (const UActorComponent *ActorComponent)
Utility method used by subclasses to test basic conditions a component must fulfill to be considered HLOD relevant.
static const FName GetReplicatesPropertyName ()
Gets the property name for bReplicates.
Protected Attributes inherited from USceneComponent
uint8 bDisableDetachmentUpdateOverlaps:1
If true, this component stops the walk up the attachment chain in GetActorPositionForRenderer().
uint8 bHasGroupedMoveThisFrame: 1 = false
If true, then this scene component has requested to have some movement applied as part of a deferred group.
uint8 bWantsOnUpdateTransform:1
If true, OnUpdateTransform virtual will be called each time this component is moved.
Protected Attributes inherited from UActorComponent
uint8 bAllowReregistration:1
Check whether the component class allows reregistration during ReregisterAllComponents.
uint8 bCallAsyncPhysicsStateCreatedDelegate:1
If the physics state was created while component was pre-registering, notification to GameThread is deferred next time CreatePhysicsState is called.
uint8 bPhysicsStateCreated:1
If the physics state is currently created for this component.
uint8 bRegistered:1
Indicates if this ActorComponent is currently registered with a scene.
uint8 bRenderStateCreated:1
If the render state is currently created for this component.
uint8 bRenderStateRecreating:1
Render state is being recreated for this component.
EComponentRegistrationState RegistrationState
Indicates if this ActorComponent is currently pre-registering or pre-registered with a scene.
Protected Attributes inherited from UObjectBase
const TCHAR * Name
Detailed Description
Definition at line 19 of file PhysicsConstraintComponent.h.
Member Function Documentation
BeginDestroy()
virtual void UPhysicsConstraintComponent::BeginDestroy () override virtual
Called before destroying the object.
This is called immediately upon deciding to destroy the object, to allow the object to begin an asynchronous cleanup process.
Reimplemented from USceneComponent.
References BeginDestroy().
Referenced by BeginDestroy().
CheckForErrors()
virtual void UPhysicsConstraintComponent::CheckForErrors () override virtual
Function that gets called from within Map_Check to allow this actor component to check itself for any potential errors and register them with map check dialog.
Note
Derived class implementations should call up to their parents.
Reimplemented from UActorComponent.
EndPlay()
virtual void UPhysicsConstraintComponent::EndPlay (const EEndPlayReason::Type EndPlayReason) override virtual
Ends gameplay for this component.
Called from AActor::EndPlay only if bHasBegunPlay is true
Reimplemented from USceneComponent.
GENERATED_UCLASS_BODY()
UPhysicsConstraintComponent::GENERATED_UCLASS_BODY () private
Pointer to first Actor to constrain.
References USceneComponent::AActor, USceneComponent::Category, and UPROPERTY().
GetBodyBox()
FBox UPhysicsConstraintComponent::GetBodyBox (EConstraintFrame::Type Frame) const
Get body bounding box.
Works without constraint being created
GetBodyBoxInternal()
FBox UPhysicsConstraintComponent::GetBodyBoxInternal (EConstraintFrame::Type Frame, FName InBoneName) const protected
Internal util to get body box from actor/component name/bone name information.
GetBodyInstance()
FBodyInstance * UPhysicsConstraintComponent::GetBodyInstance (EConstraintFrame::Type Frame) const protected
Get the body instance that we want to constrain to.
GetBodyTransform()
FTransform UPhysicsConstraintComponent::GetBodyTransform (EConstraintFrame::Type Frame) const
Get the body frame.
Works without constraint being created
GetBodyTransformInternal()
FTransform UPhysicsConstraintComponent::GetBodyTransformInternal (EConstraintFrame::Type Frame, FName InBoneName) const protected
Internal util to get body transform from actor/component name/bone name information.
GetComponentInternal()
UPrimitiveComponent * UPhysicsConstraintComponent::GetComponentInternal (EConstraintFrame::Type Frame) const protected
Internal util to get component from actor/component name.
GetConstraintScale()
float UPhysicsConstraintComponent::GetConstraintScale () const protected
Returns the scale of the constraint as it will be passed into the ConstraintInstance.
GetPhysicsObject()
Chaos::FPhysicsObject * UPhysicsConstraintComponent::GetPhysicsObject (EConstraintFrame::Type Frame) const protected
Get the physics object that we want to constrain to.
InitComponentConstraint()
void UPhysicsConstraintComponent::InitComponentConstraint ()
Initialize the frames and creates constraint.
InitializeComponent()
virtual void UPhysicsConstraintComponent::InitializeComponent () override virtual
Initializes the component.
Occurs at level startup or actor spawn. This is before BeginPlay (Actor or Component).
All Components in the level will be Initialized on load before any Actor/Component gets BeginPlay Requires component to be registered, and bWantsInitializeComponent to be true.
Reimplemented from UActorComponent.
OnConstraintBrokenHandler()
void UPhysicsConstraintComponent::OnConstraintBrokenHandler (FConstraintInstance * BrokenConstraint) protected
Routes the FConstraint callback to the dynamic delegate.
OnConstraintBrokenWrapper()
void UPhysicsConstraintComponent::OnConstraintBrokenWrapper (int32 ConstraintIndex) private
Wrapper that calls our constraint broken delegate.
OnPlasticDeformationHandler()
void UPhysicsConstraintComponent::OnPlasticDeformationHandler (FConstraintInstance * Constraint) protected
Routes the FConstraint callback to the dynamic delegate.
OnPlasticDeformationWrapper()
void UPhysicsConstraintComponent::OnPlasticDeformationWrapper (int32 ConstraintIndex) private
Wrapper that calls our constraint plasticity delegate.
OnRegister()
virtual void UPhysicsConstraintComponent::OnRegister () override virtual
Called when a component is registered, after Scene is set, but before CreateRenderState_Concurrent or OnCreatePhysicsState are called.
Reimplemented from USceneComponent.
OnUnregister()
virtual void UPhysicsConstraintComponent::OnUnregister () override virtual
Called when a component is unregistered.
Called after DestroyRenderState_Concurrent and OnDestroyPhysicsState are called.
Reimplemented from USceneComponent.
PostEditChangeChainProperty()
virtual void UPhysicsConstraintComponent::PostEditChangeChainProperty (FPropertyChangedChainEvent & PropertyChangedEvent) override virtual
This alternate version of PostEditChange is called when properties inside structs are modified.
The property that was actually modified is located at the tail of the list. The head of the list of the FStructProperty member variable that contains the property that was modified.
Reimplemented from USceneComponent.
PostEditChangeProperty()
virtual void UPhysicsConstraintComponent::PostEditChangeProperty (FPropertyChangedEvent & PropertyChangedEvent) override virtual
Called when a property on this object has been modified externally.
Parameters
PropertyThatChanged the property that was modified
Reimplemented from USceneComponent.
References Ar, and USceneComponent::Serialize().
PostEditComponentMove()
virtual void UPhysicsConstraintComponent::PostEditComponentMove (bool bFinished) override virtual
Called when this component is moved in the editor.
Reimplemented from USceneComponent.
PostLoad()
virtual void UPhysicsConstraintComponent::PostLoad () override virtual
Do any object-specific cleanup required immediately after loading an object.
This is not called for newly-created objects, and by default will always execute on the game thread.
Reimplemented from UActorComponent.
References PostLoad().
Referenced by PostLoad().
TermComponentConstraint()
void UPhysicsConstraintComponent::TermComponentConstraint ()
Break the constraint.
UFUNCTION() [1/40]
UPhysicsConstraintComponent::UFUNCTION ()
References USceneComponent::Category, and UFUNCTION().
UFUNCTION() [2/40]
UPhysicsConstraintComponent::UFUNCTION ()
Gets the constraint object.
References USceneComponent::Category, and UFUNCTION().
UFUNCTION() [3/40]
UPhysicsConstraintComponent::UFUNCTION () const
Gets the current Swing1 of the constraint.
References USceneComponent::Category, USceneComponent::const, and UFUNCTION().
UFUNCTION() [4/40]
UPhysicsConstraintComponent::UFUNCTION () const
Gets the current Swing2 of the constraint.
References USceneComponent::Category, USceneComponent::const, and UFUNCTION().
UFUNCTION() [5/40]
UPhysicsConstraintComponent::UFUNCTION () const
Gets the current Angular Twist of the constraint.
References USceneComponent::Category, USceneComponent::const, and UFUNCTION().
UFUNCTION() [6/40]
UPhysicsConstraintComponent::UFUNCTION ()
Break this constraint.
References USceneComponent::Category, and UFUNCTION().
UFUNCTION() [7/40]
UPhysicsConstraintComponent::UFUNCTION () &
Get connected components and potential related attachement bones.
References USceneComponent::Category, and UFUNCTION().
UFUNCTION() [8/40]
UPhysicsConstraintComponent::UFUNCTION () &
References USceneComponent::Category, and UFUNCTION().
UFUNCTION() [9/40]
UPhysicsConstraintComponent::UFUNCTION ()
Sets the Angular Breakable properties.
Parameters
bAngularBreakable Whether it is possible to break the joint with angular force
AngularBreakThreshold Torque needed to break the joint
References USceneComponent::Category, and UFUNCTION().
UFUNCTION() [10/40]
UFUNCTION() 1 void SetAngularDriveMode(EAngularDriveMode UPhysicsConstraintComponent::UFUNCTION ()
Switches the angular drive mode between SLERP and Twist And Swing.
Parameters
DriveMode The angular drive mode to use. SLERP uses shortest spherical path, but will not work if any angular constraints are locked. Twist and Swing decomposes the path into the different angular degrees of freedom but may experience gimbal lock Toggles the angular drive acceleration mode. When enabled, the acceleration of the angular drive is not affected by the inertia of the constrained objects around the drive axis.
References USceneComponent::Category, and UFUNCTION().
UFUNCTION() [11/40]
UPhysicsConstraintComponent::UFUNCTION ()
Sets the drive params for the angular drive.
Parameters
PositionStrength Positional strength for the drive (stiffness)
VelocityStrength Velocity strength of the drive (damping)
InForceLimit Max force applied by the drive
References USceneComponent::Category, InForceLimit, UFUNCTION(), and VelocityStrength.
UFUNCTION() [12/40]
UPhysicsConstraintComponent::UFUNCTION () const &
Sets the target orientation for the angular drive.
Parameters
InPosTarget Target orientation
References USceneComponent::Category, USceneComponent::const, and UFUNCTION().
UFUNCTION() [13/40]
UPhysicsConstraintComponent::UFUNCTION ()
Sets the Angular Plasticity properties.
Parameters
bAngularPlasticity Whether it is possible to reset the target angle from the angular displacement
AngularPlasticityThreshold Degrees needed to reset the rest state of the joint
References USceneComponent::Category, and UFUNCTION().
UFUNCTION() [14/40]
UPhysicsConstraintComponent::UFUNCTION ()
Sets the Angular Swing1 Motion Type.
Parameters
ConstraintType New Constraint Type
Swing1LimitAngle Size of limit in degrees
References USceneComponent::Category, and UFUNCTION().
UFUNCTION() [15/40]
UPhysicsConstraintComponent::UFUNCTION ()
Sets the Angular Swing2 Motion Type.
Parameters
ConstraintType New Constraint Type
Swing2LimitAngle Size of limit in degrees
References USceneComponent::Category, and UFUNCTION().
UFUNCTION() [16/40]
UPhysicsConstraintComponent::UFUNCTION ()
Sets the Angular Twist Motion Type.
Parameters
ConstraintType New Constraint Type
TwistLimitAngle Size of limit in degrees
References USceneComponent::Category, and UFUNCTION().
UFUNCTION() [17/40]
UPhysicsConstraintComponent::UFUNCTION ()
Enables/Disables the angular velocity slerp drive.
Only relevant if the AngularDriveMode is set to SLERP
Parameters
bEnableSLERP Indicates whether the SLERP drive should be enabled. Only relevant if the AngularDriveMode is set to SLERP
References USceneComponent::Category, and UFUNCTION().
UFUNCTION() [18/40]
UPhysicsConstraintComponent::UFUNCTION ()
Enables/Disables angular velocity twist and swing drive.
Only relevant if the AngularDriveMode is set to Twist and Swing
Parameters
bEnableSwingDrive Indicates whether the drive for the swing axis should be enabled. Only relevant if the AngularDriveMode is set to Twist and Swing
bEnableTwistDrive Indicates whether the drive for the twist axis should be enabled. Only relevant if the AngularDriveMode is set to Twist and Swing
References bEnableSwingDrive, bEnableTwistDrive, and USceneComponent::Category.
UFUNCTION() [19/40]
UPhysicsConstraintComponent::UFUNCTION () const &
Sets the target velocity for the angular drive.
Parameters
InVelTarget Target velocity
References USceneComponent::Category, USceneComponent::const, FVector, and UFUNCTION().
UFUNCTION() [20/40]
UPhysicsConstraintComponent::UFUNCTION ()
Directly specify component to connect.
Will update frames based on current position.
References USceneComponent::Category.
Referenced by UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), and UpdateConstraintFrames().
UFUNCTION() [21/40]
UPhysicsConstraintComponent::UFUNCTION ()
Sets the contact transfer scale properties.
Parameters
ContactTransferScale Set the contact transfer scale for the parent of the joint
References USceneComponent::Category, and UFUNCTION().
UFUNCTION() [22/40]
UFUNCTION() 1 void SetConstraintReferenceFrame(EConstraintFrame UFUNCTION() 1 void SetConstraintReferencePosition(EConstraintFrame UFUNCTION() 1 void SetConstraintReferenceOrientation(EConstraintFrame UPhysicsConstraintComponent::UFUNCTION ()
References USceneComponent::Category, and UFUNCTION().
UFUNCTION() [23/40]
UPhysicsConstraintComponent::UFUNCTION ()
Sets the Linear Breakable properties.
Parameters
bLinearBreakable Whether it is possible to break the joint with linear force
LinearBreakThreshold Force needed to break the joint
References USceneComponent::Category, and UFUNCTION().
UFUNCTION() [24/40]
UPhysicsConstraintComponent::UFUNCTION ()
Toggles the linear drive acceleration mode.
When enabled, the acceleration of the angular drive is not affected by the inertia of the constrained objects along the drive axis.
References USceneComponent::Category, and UFUNCTION().
UFUNCTION() [25/40]
UPhysicsConstraintComponent::UFUNCTION ()
Sets the drive params for the linear drive.
Parameters
PositionStrength Positional strength for the drive (stiffness)
VelocityStrength Velocity strength of the drive (damping)
InForceLimit Max force applied by the drive
References USceneComponent::Category, and UFUNCTION().
UFUNCTION() [26/40]
UPhysicsConstraintComponent::UFUNCTION ()
Sets the Linear Plasticity properties.
Parameters
bLinearPlasticity Whether it is possible to reset the target angle from the Linear displacement
LinearPlasticityThreshold Percent deformation needed to reset the rest length of the joint
References USceneComponent::Category, and UFUNCTION().
UFUNCTION() [27/40]
UPhysicsConstraintComponent::UFUNCTION ()
Enables/Disables linear position drive.
Parameters
bEnableDriveX Indicates whether the drive for the X-Axis should be enabled
bEnableDriveY Indicates whether the drive for the Y-Axis should be enabled
bEnableDriveZ Indicates whether the drive for the Z-Axis should be enabled
References USceneComponent::Category, and UFUNCTION().
UFUNCTION() [28/40]
UPhysicsConstraintComponent::UFUNCTION () const &
Sets the target position for the linear drive.
Parameters
InPosTarget Target position
References USceneComponent::Category, USceneComponent::const, FVector, and UFUNCTION().
UFUNCTION() [29/40]
UPhysicsConstraintComponent::UFUNCTION ()
Enables/Disables linear position drive.
Parameters
bEnableDriveX Indicates whether the drive for the X-Axis should be enabled
bEnableDriveY Indicates whether the drive for the Y-Axis should be enabled
bEnableDriveZ Indicates whether the drive for the Z-Axis should be enabled
References bEnableDriveY, bEnableDriveZ, USceneComponent::Category, and UFUNCTION().
UFUNCTION() [30/40]
UPhysicsConstraintComponent::UFUNCTION () const &
Sets the target velocity for the linear drive.
Parameters
InVelTarget Target velocity
References USceneComponent::Category, USceneComponent::const, FVector, and UFUNCTION().
UFUNCTION() [31/40]
UPhysicsConstraintComponent::UFUNCTION ()
Sets the LinearX Motion Type.
Parameters
ConstraintType New Constraint Type
LimitSize Size of limit
References USceneComponent::Category, and UFUNCTION().
UFUNCTION() [32/40]
UPhysicsConstraintComponent::UFUNCTION ()
Sets the LinearY Motion Type.
Parameters
ConstraintType New Constraint Type
LimitSize Size of limit
References USceneComponent::Category, LimitSize, and UFUNCTION().
UFUNCTION() [33/40]
UPhysicsConstraintComponent::UFUNCTION ()
Sets the LinearZ Motion Type.
Parameters
ConstraintType New Constraint Type
LimitSize Size of limit
References USceneComponent::Category, LimitSize, and UFUNCTION().
UFUNCTION() [34/40]
UPhysicsConstraintComponent::UFUNCTION ()
Enables/Disables the angular orientation slerp drive.
Only relevant if the AngularDriveMode is set to SLERP
Parameters
bEnableSLERP Indicates whether the SLERP drive should be enabled. Only relevant if the AngularDriveMode is set to SLERP
References USceneComponent::Category, and UFUNCTION().
UFUNCTION() [35/40]
UPhysicsConstraintComponent::UFUNCTION ()
Enables/Disables angular orientation drive.
Only relevant if the AngularDriveMode is set to Twist and Swing
Parameters
bEnableSwingDrive Indicates whether the drive for the swing axis should be enabled. Only relevant if the AngularDriveMode is set to Twist and Swing
bEnableTwistDrive Indicates whether the drive for the twist axis should be enabled. Only relevant if the AngularDriveMode is set to Twist and Swing
References USceneComponent::Category.
UFUNCTION() [36/40]
UPhysicsConstraintComponent::UFUNCTION ()
References USceneComponent::Category, and UFUNCTION().
UFUNCTION() [37/40]
UPhysicsConstraintComponent::UFUNCTION ()
Set the projection settings for use when projection is enabled.
See SetProjectionEnabled. For ragdolls you usually require that ProjectionLinearAlpha and ProjectionAngularAlpha be zero. They are most useful for cosmetic chains etc. ProjectionLinearTolerance and ProjectionAngularTolerance are emergency error recovery settings and should only rarely affect the simulation. If the simulation is significantly affected by the Tolerance settings, it likely indicates a setup stability issue.
Parameters
ProjectionLinearAlpha Controls the semi-physical correction of linear error remaining after the joint solve. Will add energy into the system. Best for joint chains connected to a kinematic.
ProjectionAngularAlpha Controls the semi-physical correction of angular error remaining after the joint solve. Will add energy into the system. Best for joint chains connected to a kinematic.
ProjectionLinearTolerance Linear errors above this will be corrected with a non-physical teleport.
ProjectionAngularTolerance Angular errors above this will be corrected with a non-physical teleport.
References USceneComponent::Category, and UFUNCTION().
UFUNCTION() [38/40]
UPhysicsConstraintComponent::UFUNCTION () const
References USceneComponent::Category, USceneComponent::const, and UFUNCTION().
UFUNCTION() [39/40]
UPhysicsConstraintComponent::UFUNCTION ()
Enables/Disables angular orientation drive.
Only relevant if the AngularDriveMode is set to Twist and Swing
Parameters
bEnableSwingDrive Indicates whether the drive for the swing axis should be enabled. Only relevant if the AngularDriveMode is set to Twist and Swing
bEnableTwistDrive Indicates whether the drive for the twist axis should be enabled. Only relevant if the AngularDriveMode is set to Twist and Swing
References USceneComponent::Category, meta, and UFUNCTION().
UFUNCTION() [40/40]
UPhysicsConstraintComponent::UFUNCTION ()
References bEnableSwingDrive, bEnableTwistDrive, USceneComponent::Category, meta, and UFUNCTION().
UpdateConstraintFrames()
void UPhysicsConstraintComponent::UpdateConstraintFrames ()
Update the reference frames held inside the constraint that indicate the joint location in the reference frame of the two connected bodies.
You should call this whenever the constraint or either Component moves, or if you change the connected Components. This function does nothing though once the joint has been initialized.
References USceneComponent::Category, USceneComponent::const, FVector, UFUNCTION(), and UpdateConstraintFrames().
Referenced by UpdateConstraintFrames().
UpdateSpriteTexture()
void UPhysicsConstraintComponent::UpdateSpriteTexture ()
UPROPERTY() [1/7]
UPhysicsConstraintComponent::UPROPERTY () private
Name of first component property to constrain.
If Actor1 is NULL, will look within Owner. If this is NULL, will use RootComponent of Actor1
References USceneComponent::Category, and UPROPERTY().
Referenced by GENERATED_UCLASS_BODY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), and UPROPERTY().
UPROPERTY() [2/7]
UPhysicsConstraintComponent::UPROPERTY () private
Name of second component property to constrain.
If Actor2 is NULL, will look within Owner. If this is NULL, will use RootComponent of Actor2
References USceneComponent::Category, and UPROPERTY().
UPROPERTY() [3/7]
UPhysicsConstraintComponent::UPROPERTY () private
Notification when constraint is broken.
References UPROPERTY().
UPROPERTY() [4/7]
UPhysicsConstraintComponent::UPROPERTY () private
Notification when constraint plasticity drive target changes.
References UPROPERTY().
UPROPERTY() [5/7]
UPhysicsConstraintComponent::UPROPERTY () private
Pointer to second Actor to constrain.
References USceneComponent::AActor, USceneComponent::Category, and UPROPERTY().
UPROPERTY() [6/7]
UPhysicsConstraintComponent::UPROPERTY () private
References UPROPERTY().
UPROPERTY() [7/7]
UPhysicsConstraintComponent::UPROPERTY ()
All constraint settings.
References USceneComponent::Category, meta, and UPROPERTY().
Friends And Related Symbol Documentation
FConstraintComponentVisualizer
friend class FConstraintComponentVisualizer friend
Definition at line 393 of file PhysicsConstraintComponent.h.
References FConstraintComponentVisualizer.
Referenced by FConstraintComponentVisualizer.
Field Documentation
AngularBreakThreshold
float UPhysicsConstraintComponent::AngularBreakThreshold
Definition at line 304 of file PhysicsConstraintComponent.h.
AngularPlasticityThreshold
float UPhysicsConstraintComponent::AngularPlasticityThreshold
Definition at line 311 of file PhysicsConstraintComponent.h.
bEnableDriveY
bool UPhysicsConstraintComponent::bEnableDriveY
Definition at line 129 of file PhysicsConstraintComponent.h.
Referenced by UFUNCTION().
bEnableDriveZ
bool bool UPhysicsConstraintComponent::bEnableDriveZ
Definition at line 129 of file PhysicsConstraintComponent.h.
Referenced by UFUNCTION().
bEnableSwingDrive
bool UPhysicsConstraintComponent::bEnableSwingDrive
Definition at line 156 of file PhysicsConstraintComponent.h.
Referenced by UFUNCTION(), and UFUNCTION().
bEnableTwistDrive
bool UPhysicsConstraintComponent::bEnableTwistDrive
Initial value:
{
        SetOrientationDriveTwistAndSwing(bEnableTwistDrive, bEnableSwingDrive)
Definition at line 146 of file PhysicsConstraintComponent.h.
Referenced by UFUNCTION(), and UFUNCTION().
bIsBrokenLocal
bool UPhysicsConstraintComponent::bIsBrokenLocal private
Definition at line 419 of file PhysicsConstraintComponent.h.
BoneName1
FName UPhysicsConstraintComponent::BoneName1
Definition at line 112 of file PhysicsConstraintComponent.h.
BoneName2
FName UPrimitiveComponent FName UPhysicsConstraintComponent::BoneName2
Definition at line 112 of file PhysicsConstraintComponent.h.
Component2
FName UPrimitiveComponent* UPhysicsConstraintComponent::Component2
Definition at line 112 of file PhysicsConstraintComponent.h.
InForceLimit
float float UPhysicsConstraintComponent::InForceLimit
Definition at line 215 of file PhysicsConstraintComponent.h.
Referenced by UFUNCTION().
LimitSize
float UPhysicsConstraintComponent::LimitSize
Definition at line 248 of file PhysicsConstraintComponent.h.
Referenced by UFUNCTION(), and UFUNCTION().
LinearBreakThreshold
float UPhysicsConstraintComponent::LinearBreakThreshold
Definition at line 290 of file PhysicsConstraintComponent.h.
LinearPlasticityThreshold
float UPhysicsConstraintComponent::LinearPlasticityThreshold
Definition at line 297 of file PhysicsConstraintComponent.h.
OutAngularForce
FVector& UPhysicsConstraintComponent::OutAngularForce
Definition at line 377 of file PhysicsConstraintComponent.h.
OutBoneName1
FName& UPhysicsConstraintComponent::OutBoneName1
Definition at line 116 of file PhysicsConstraintComponent.h.
OutBoneName2
FName UPrimitiveComponent FName& UPhysicsConstraintComponent::OutBoneName2
Definition at line 116 of file PhysicsConstraintComponent.h.
OutComponent2
FName UPrimitiveComponent*& UPhysicsConstraintComponent::OutComponent2
Definition at line 116 of file PhysicsConstraintComponent.h.
OverrideComponent1
TWeakObjectPtr<UPrimitiveComponent> UPhysicsConstraintComponent::OverrideComponent1 private
Allows direct setting of first component to constraint.
Definition at line 48 of file PhysicsConstraintComponent.h.
OverrideComponent2
TWeakObjectPtr<UPrimitiveComponent> UPhysicsConstraintComponent::OverrideComponent2 private
Allows direct setting of second component to constraint.
Definition at line 51 of file PhysicsConstraintComponent.h.
PlasticityType
float EConstraintPlasticityType UPhysicsConstraintComponent::PlasticityType
Definition at line 297 of file PhysicsConstraintComponent.h.
ProjectionAngularAlpha
float UPhysicsConstraintComponent::ProjectionAngularAlpha
Definition at line 373 of file PhysicsConstraintComponent.h.
ProjectionAngularTolerance
float float float UPhysicsConstraintComponent::ProjectionAngularTolerance
Definition at line 373 of file PhysicsConstraintComponent.h.
ProjectionLinearTolerance
float float UPhysicsConstraintComponent::ProjectionLinearTolerance
Definition at line 373 of file PhysicsConstraintComponent.h.
Swing1LimitAngle
float UPhysicsConstraintComponent::Swing1LimitAngle
Definition at line 269 of file PhysicsConstraintComponent.h.
Swing2LimitAngle
float UPhysicsConstraintComponent::Swing2LimitAngle
Definition at line 276 of file PhysicsConstraintComponent.h.
TwistLimitAngle
float UPhysicsConstraintComponent::TwistLimitAngle
Definition at line 283 of file PhysicsConstraintComponent.h.
VelocityStrength
float UPhysicsConstraintComponent::VelocityStrength
Definition at line 215 of file PhysicsConstraintComponent.h.
Referenced by UFUNCTION().
The documentation for this class was generated from the following file:
Runtime/Engine/Classes/PhysicsEngine/PhysicsConstraintComponent.h