Unreal Engine 5.6 C++ API: UE::GC::FWorkBlockifier Class Reference
UE::GC::FWorkBlockifier Class Reference
Reachable objects waiting to be processed.
#include "FastReferenceCollector.h"
Public Member Functions
FWorkBlockifier ()=default
~FWorkBlockifier ()
template<EGCOptions Options>
FORCEINLINE_DEBUGGABLE void Add (UObject *Object)
void FreeOwningBlock (UObject *const *BlockObjects)
int32 GetWorkerIndex () const
bool HasWork () const
void Init ()
FORCEINLINE bool IsUnused () const
template<EGCOptions Options>
FORCEINLINE FWorkBlock * PopFullBlock ()
FORCEINLINE_DEBUGGABLE FWorkBlock * PopPartialBlock (int32 &OutNum)
void ResetAsyncQueue ()
void SetAsyncQueue (FWorkstealingQueue &Queue)
void SetWorkerIndex (int32 Idx)
FORCEINLINE FWorkBlock * StealFullBlock () const
UE_NONCOPYABLE (FWorkBlockifier)
Private Member Functions
void AllocateWipBlock ()
FORCEINLINE int32 PartialNum () const
FWorkBlock * PopFullBlockAsync ()
FWorkBlock * PopFullBlockSync ()
FWorkBlock * PopWipBlock ()
void PushFullBlockAsync ()
void PushFullBlockSync ()
FWorkBlock * StealAsyncBlock () const
Private Attributes
union {
FWorkstealingQueue * AsyncQueue
FWorkBlock * SyncQueue = nullptr
};
FWorkBlock * Wip
UObject ** WipIt
int32 WorkerIndex = INDEX_NONE
Detailed Description
Reachable objects waiting to be processed.
Type-erases parallel/serial queue.
Definition at line 142 of file FastReferenceCollector.h.
Constructor & Destructor Documentation
FWorkBlockifier()
UE::GC::FWorkBlockifier::FWorkBlockifier () default
Referenced by UE_NONCOPYABLE().
~FWorkBlockifier()
UE::GC::FWorkBlockifier::~FWorkBlockifier ()
Member Function Documentation
Add()
template<EGCOptions Options> FORCEINLINE_DEBUGGABLE void UE::GC::FWorkBlockifier::Add (UObject * Object) inline
Definition at line 154 of file FastReferenceCollector.h.
References FORCEINLINE_DEBUGGABLE, IsParallel(), UE::Options, PushFullBlockAsync(), PushFullBlockSync(), Wip, and WipIt.
AllocateWipBlock()
void UE::GC::FWorkBlockifier::AllocateWipBlock () private
Referenced by Init().
FreeOwningBlock()
void UE::GC::FWorkBlockifier::FreeOwningBlock (UObject *const * BlockObjects)
GetWorkerIndex()
int32 UE::GC::FWorkBlockifier::GetWorkerIndex () const inline
Definition at line 200 of file FastReferenceCollector.h.
References WorkerIndex.
HasWork()
bool UE::GC::FWorkBlockifier::HasWork () const inline
Definition at line 202 of file FastReferenceCollector.h.
References PartialNum().
Init()
void UE::GC::FWorkBlockifier::Init () inline
Definition at line 149 of file FastReferenceCollector.h.
References AllocateWipBlock().
IsUnused()
FORCEINLINE bool UE::GC::FWorkBlockifier::IsUnused () const inline
Definition at line 194 of file FastReferenceCollector.h.
References FORCEINLINE, PartialNum(), and SyncQueue.
PartialNum()
FORCEINLINE int32 UE::GC::FWorkBlockifier::PartialNum () const inline private
Definition at line 225 of file FastReferenceCollector.h.
References FORCEINLINE, Wip, and WipIt.
Referenced by HasWork(), IsUnused(), and PopPartialBlock().
PopFullBlock()
template<EGCOptions Options> FORCEINLINE FWorkBlock * UE::GC::FWorkBlockifier::PopFullBlock () inline
Definition at line 182 of file FastReferenceCollector.h.
References FORCEINLINE, IsParallel(), UE::Options, PopFullBlockAsync(), and PopFullBlockSync().
Referenced by UE::GC::TFastReferenceCollector< ProcessorType, CollectorType >::ProcessObjectArray().
PopFullBlockAsync()
FWorkBlock * UE::GC::FWorkBlockifier::PopFullBlockAsync () private
Referenced by PopFullBlock().
PopFullBlockSync()
FWorkBlock * UE::GC::FWorkBlockifier::PopFullBlockSync () private
Referenced by PopFullBlock().
PopPartialBlock()
FORCEINLINE_DEBUGGABLE FWorkBlock * UE::GC::FWorkBlockifier::PopPartialBlock (int32 & OutNum) inline
Definition at line 170 of file FastReferenceCollector.h.
References FORCEINLINE_DEBUGGABLE, Num, PartialNum(), and PopWipBlock().
Referenced by UE::GC::TFastReferenceCollector< ProcessorType, CollectorType >::ProcessObjectArray().
PopWipBlock()
FWorkBlock * UE::GC::FWorkBlockifier::PopWipBlock () private
Referenced by PopPartialBlock().
PushFullBlockAsync()
void UE::GC::FWorkBlockifier::PushFullBlockAsync () private
Referenced by Add().
PushFullBlockSync()
void UE::GC::FWorkBlockifier::PushFullBlockSync () private
Referenced by Add().
ResetAsyncQueue()
void UE::GC::FWorkBlockifier::ResetAsyncQueue ()
SetAsyncQueue()
void UE::GC::FWorkBlockifier::SetAsyncQueue (FWorkstealingQueue & Queue) inline
Definition at line 150 of file FastReferenceCollector.h.
References AsyncQueue.
SetWorkerIndex()
void UE::GC::FWorkBlockifier::SetWorkerIndex (int32 Idx) inline
Definition at line 199 of file FastReferenceCollector.h.
References WorkerIndex.
StealAsyncBlock()
FWorkBlock * UE::GC::FWorkBlockifier::StealAsyncBlock () const private
Referenced by StealFullBlock().
StealFullBlock()
FORCEINLINE FWorkBlock * UE::GC::FWorkBlockifier::StealFullBlock () const inline
Definition at line 187 of file FastReferenceCollector.h.
References FORCEINLINE, and StealAsyncBlock().
UE_NONCOPYABLE()
UE::GC::FWorkBlockifier::UE_NONCOPYABLE (FWorkBlockifier)
References FWorkBlockifier().
Field Documentation
[union]
union { ... } UE::GC::FWorkBlockifier
AsyncQueue
FWorkstealingQueue* UE::GC::FWorkBlockifier::AsyncQueue
Definition at line 213 of file FastReferenceCollector.h.
Referenced by SetAsyncQueue().
SyncQueue
FWorkBlock* UE::GC::FWorkBlockifier::SyncQueue = nullptr
Definition at line 212 of file FastReferenceCollector.h.
Referenced by IsUnused().
Wip
FWorkBlock* UE::GC::FWorkBlockifier::Wip private
Definition at line 209 of file FastReferenceCollector.h.
Referenced by Add(), and PartialNum().
WipIt
UObject** UE::GC::FWorkBlockifier::WipIt private
Definition at line 208 of file FastReferenceCollector.h.
Referenced by Add(), and PartialNum().
WorkerIndex
int32 UE::GC::FWorkBlockifier::WorkerIndex = INDEX_NONE private
Definition at line 215 of file FastReferenceCollector.h.
Referenced by GetWorkerIndex(), and SetWorkerIndex().
The documentation for this class was generated from the following file:
Runtime/CoreUObject/Public/UObject/FastReferenceCollector.h