Unreal Engine 5.6 C++ API: UE::Geometry::FImageTile Class Reference
UE::Geometry::FImageTile Class Reference
#include "ImageTile.h"
Public Member Functions
FImageTile ()=default
FImageTile (const FVector2i &InStart, const FVector2i &InEnd)
bool Contains (const int32 X, const int32 Y) const
FVector2i GetCoords (const int64 LinearIdx) const
FVector2i GetEnd () const
int32 GetHeight () const
int64 GetIndex (const FVector2i &LocalCoords) const
int64 GetIndex (const int32 X, const int32 Y) const
int64 GetIndexFromSourceCoords (const FVector2i &SourceCoords) const
int64 GetIndexFromSourceCoords (const int32 X, const int32 Y) const
FVector2i GetSourceCoords (const FVector2i &LocalCoords) const
FVector2i GetSourceCoords (const int32 X, const int32 Y) const
FVector2i GetSourceCoords (const int64 LinearIdx) const
FVector2i GetStart () const
int32 GetWidth () const
int64 Num () const
Private Attributes
FVector2i End = FVector2i::Zero()
int Height = 0
FVector2i Start = FVector2i::Zero()
int Width = 0
Detailed Description
Definition at line 13 of file ImageTile.h.
Constructor & Destructor Documentation
FImageTile() [1/2]
UE::Geometry::FImageTile::FImageTile () default
FImageTile() [2/2]
UE::Geometry::FImageTile::FImageTile (const FVector2i & InStart, const FVector2i & InEnd) inline
Definition at line 23 of file ImageTile.h.
References End, Height, Start, Width, X, and Y.
Member Function Documentation
Contains()
bool UE::Geometry::FImageTile::Contains (const int32 X, const int32 Y) const inline
Returns
true if the given source coordinates are contained by this tile.
Definition at line 75 of file ImageTile.h.
References End, Start, X, and Y.
Referenced by GetIndexFromSourceCoords().
GetCoords()
FVector2i UE::Geometry::FImageTile::GetCoords (const int64 LinearIdx) const inline
Returns
the coordinates into this tile given the linear index into this tile.
Definition at line 69 of file ImageTile.h.
References Width.
GetEnd()
FVector2i UE::Geometry::FImageTile::GetEnd () const inline
Definition at line 36 of file ImageTile.h.
References End.
GetHeight()
int32 UE::Geometry::FImageTile::GetHeight () const inline
Definition at line 46 of file ImageTile.h.
References Height.
GetIndex() [1/2]
int64 UE::Geometry::FImageTile::GetIndex (const FVector2i & LocalCoords) const inline
Returns
the linear index for the given local coordinates into this tile.
Definition at line 63 of file ImageTile.h.
References GetIndex(), UE::Geometry::FVector2i::X, and UE::Geometry::FVector2i::Y.
GetIndex() [2/2]
int64 UE::Geometry::FImageTile::GetIndex (const int32 X, const int32 Y) const inline
Returns
the linear index for the given local XY coordinates into this tile.
Definition at line 57 of file ImageTile.h.
References Width, X, and Y.
Referenced by GetIndex(), and GetIndexFromSourceCoords().
GetIndexFromSourceCoords() [1/2]
int64 UE::Geometry::FImageTile::GetIndexFromSourceCoords (const FVector2i & SourceCoords) const inline
Returns
the linear index for the given source coordinates.
Definition at line 88 of file ImageTile.h.
References GetIndexFromSourceCoords(), UE::Geometry::FVector2i::X, and UE::Geometry::FVector2i::Y.
GetIndexFromSourceCoords() [2/2]
int64 UE::Geometry::FImageTile::GetIndexFromSourceCoords (const int32 X, const int32 Y) const inline
Returns
the linear index for the given source coordinates.
Definition at line 81 of file ImageTile.h.
References checkSlow, Contains(), GetIndex(), Start, X, and Y.
Referenced by GetIndexFromSourceCoords().
GetSourceCoords() [1/3]
FVector2i UE::Geometry::FImageTile::GetSourceCoords (const FVector2i & LocalCoords) const inline
Returns
the source image's coordinates given local coordinates into this tile.
Definition at line 106 of file ImageTile.h.
References GetSourceCoords(), UE::Geometry::FVector2i::X, and UE::Geometry::FVector2i::Y.
GetSourceCoords() [2/3]
FVector2i UE::Geometry::FImageTile::GetSourceCoords (const int32 X, const int32 Y) const inline
Returns
the source image's coordinates given local XY coordinates into this tile.
Definition at line 100 of file ImageTile.h.
References Start, X, and Y.
GetSourceCoords() [3/3]
FVector2i UE::Geometry::FImageTile::GetSourceCoords (const int64 LinearIdx) const inline
Returns
the source image's coordinates given linear index into this tile.
Definition at line 94 of file ImageTile.h.
References Start, and Width.
Referenced by GetSourceCoords().
GetStart()
FVector2i UE::Geometry::FImageTile::GetStart () const inline
Definition at line 31 of file ImageTile.h.
References Start.
GetWidth()
int32 UE::Geometry::FImageTile::GetWidth () const inline
Definition at line 41 of file ImageTile.h.
References Width.
Num()
int64 UE::Geometry::FImageTile::Num () const inline
Definition at line 51 of file ImageTile.h.
References Height, and Width.
Field Documentation
End
FVector2i UE::Geometry::FImageTile::End = FVector2i::Zero() private
Definition at line 17 of file ImageTile.h.
Referenced by FImageTile(), Contains(), and GetEnd().
Height
int UE::Geometry::FImageTile::Height = 0 private
Definition at line 19 of file ImageTile.h.
Referenced by FImageTile(), GetHeight(), and Num().
Start
FVector2i UE::Geometry::FImageTile::Start = FVector2i::Zero() private
Definition at line 16 of file ImageTile.h.
Referenced by FImageTile(), Contains(), GetIndexFromSourceCoords(), GetSourceCoords(), GetSourceCoords(), and GetStart().
Width
int UE::Geometry::FImageTile::Width = 0 private
Definition at line 18 of file ImageTile.h.
Referenced by FImageTile(), GetCoords(), GetIndex(), GetSourceCoords(), GetWidth(), and Num().
The documentation for this class was generated from the following file:
Runtime/GeometryCore/Public/Image/ImageTile.h