Unreal Engine 5.6 C++ API: FAssetDataTagMap Class Reference
FAssetDataTagMap Class Reference
"Loose" FName -> FString that is optionally ref-counted and owned by a FAssetDataTagMapSharedView
#include "AssetDataTagMap.h"
Public Member Functions
FAssetDataTagMap ()=default
FAssetDataTagMap (const FAssetDataTagMap &O)
FAssetDataTagMap (FAssetDataTagMap &&O)
FAssetDataTagMap & operator= (const FAssetDataTagMap &O)
FAssetDataTagMap & operator= (FAssetDataTagMap &&O)
Public Member Functions inherited from TSortedMap< FName, FString, FDefaultAllocator, FNameFastLess >
TSortedMap ()=default
TSortedMap (const TSortedMap &)=default
TSortedMap (const TSortedMap< KeyType, ValueType, OtherArrayAllocator, FNameFastLess > &Other)
Constructor for copying elements from a TSortedMap with a different ArrayAllocator.
TSortedMap (FIntrusiveUnsetOptionalState Tag)
TSortedMap (std::initializer_list< TPairInitializer< const KeyType &, const ValueType & > > InitList)
Constructor which gets its elements from a native initializer list.
TSortedMap (TSortedMap &&)=default
TSortedMap (TSortedMap< KeyType, ValueType, OtherArrayAllocator, FNameFastLess > &&Other)
Constructor for moving elements from a TSortedMap with a different ArrayAllocator.
FORCEINLINE ValueType & Add (const KeyType &InKey)
Sets a default value associated with a key.
FORCEINLINE ValueType & Add (const KeyType &InKey, const ValueType &InValue)
Sets the value associated with a key.
FORCEINLINE ValueType & Add (const KeyType &InKey, ValueType &&InValue)
FORCEINLINE ValueType & Add (KeyType &&InKey)
FORCEINLINE ValueType & Add (KeyType &&InKey, const ValueType &InValue)
FORCEINLINE ValueType & Add (KeyType &&InKey, ValueType &&InValue)
void Append (const TSortedMap< KeyType, ValueType, OtherArrayAllocator, OtherSortPredicate > &OtherMap)
Add all items from another map to our map (if any keys are in both, the value from the other map wins).
void Append (TSortedMap< KeyType, ValueType, OtherArrayAllocator, OtherSortPredicate > &&OtherMap)
Move all items from another map into our map (if any keys are in both, the value from the other map wins) and empty the other map.
FORCEINLINE RangedForIteratorType begin ()
DO NOT USE DIRECTLY STL-like iterators to enable range-based for loop support.
FORCEINLINE RangedForConstIteratorType begin () const
FORCEINLINE bool Contains (KeyConstPointerType Key) const
Checks if map contains the specified key.
FORCEINLINE void CountBytes (FArchive &Ar) const
Tracks the container's memory use through an archive.
FORCEINLINE TConstIterator CreateConstIterator () const
Creates a const iterator over all the pairs in this map.
FORCEINLINE TConstKeyIterator CreateConstKeyIterator (KeyInitType InKey) const
Creates a const iterator over the values associated with a specified key in a map.
FORCEINLINE TIterator CreateIterator ()
Creates an iterator over all the pairs in this map.
FORCEINLINE TKeyIterator CreateKeyIterator (KeyInitType InKey)
Creates an iterator over the values associated with a specified key in a map.
void Dump (FOutputDevice &Ar)
Describes the map's contents through an output device.
ValueType & Emplace (InitKeyType &&InKey)
Sets a default value associated with a key.
ValueType & Emplace (InitKeyType &&InKey, InitValueType &&InValue)
Sets the value associated with a key.
FORCEINLINE void Empty (int32 ExpectedNumElements=0)
Removes all elements from the map, potentially leaving space allocated for an expected number of elements about to be added.
FORCEINLINE RangedForIteratorType end ()
FORCEINLINE RangedForConstIteratorType end () const
FORCEINLINE ValueType * Find (KeyConstPointerType Key)
Returns the value associated with a specified key.
FORCEINLINE const ValueType * Find (KeyConstPointerType Key) const
FORCEINLINE ValueType FindAndRemoveChecked (KeyConstPointerType Key)
Finds a pair with the specified key, removes it from the map, and returns the value part of the pair.
ElementType * FindArbitraryElement ()
Finds any pair in the map and returns a pointer to it.
const ElementType * FindArbitraryElement () const
FORCEINLINE ValueType & FindChecked (KeyConstPointerType Key)
Returns a reference to the value associated with a specified key.
FORCEINLINE const ValueType & FindChecked (KeyConstPointerType Key) const
const KeyType * FindKey (ValueInitType Value) const
Returns the key associated with the specified value.
FORCEINLINE ValueType & FindOrAdd (const KeyType &Key)
Returns the value associated with a specified key, or if none exists, adds a value using the default constructor.
FORCEINLINE ValueType & FindOrAdd (KeyType &&Key)
FORCEINLINE ValueType FindRef (KeyConstPointerType Key) const
Returns the value associated with a specified key.
FORCEINLINE ValueType FindRef (KeyConstPointerType Key, ValueType DefaultValue) const
Returns the value associated with a specified key.
void GenerateKeyArray (TArray< KeyType, Allocator > &OutArray) const
Generates an array from the keys in this map.
void GenerateValueArray (TArray< ValueType, Allocator > &OutArray) const
Generates an array from the values in this map.
FORCEINLINE ElementType & Get (FSetElementId Id)
Return a mapped pair by internal identifier.
FORCEINLINE const ElementType & Get (FSetElementId Id) const
Return a mapped pair by internal identifier.
FORCEINLINE SIZE_T GetAllocatedSize () const
Helper function to return the amount of memory allocated by this container.
int32 GetKeys (TArray< KeyType, Allocator > &OutKeys) const
Returns the unique keys contained within this map.
FORCEINLINE int32 GetMaxIndex () const
bool IsEmpty () const
Returns true if the map is empty and contains no elements.
FORCEINLINE bool IsValidId (FSetElementId Id) const
Checks whether an element id is valid.
FORCEINLINE int32 Num () const
FORCEINLINE bool operator!= (const TSortedMap &Other) const
Inequality operator.
TSortedMap & operator= (const TSortedMap &)=default
TSortedMap & operator= (const TSortedMap< KeyType, ValueType, OtherArrayAllocator, FNameFastLess > &Other)
Assignment operator for copying elements from a TSortedMap with a different ArrayAllocator.
TSortedMap & operator= (std::initializer_list< TPairInitializer< const KeyType &, const ValueType & > > InitList)
Assignment operator which gets its elements from a native initializer list.
TSortedMap & operator= (TSortedMap &&)=default
TSortedMap & operator= (TSortedMap< KeyType, ValueType, OtherArrayAllocator, FNameFastLess > &&Other)
Assignment operator for moving elements from a TSortedMap with a different ArrayAllocator.
FORCEINLINE bool operator== (const TSortedMap &Other) const
Equality operator.
bool operator== (FIntrusiveUnsetOptionalState Tag) const
FORCEINLINE ValueType & operator[] (KeyConstPointerType Key)
FORCEINLINE const ValueType & operator[] (KeyConstPointerType Key) const
FORCEINLINE int32 Remove (KeyConstPointerType InKey)
Removes all value associations for a key.
FORCEINLINE bool RemoveAndCopyValue (KeyInitType Key, ValueType &OutRemovedValue)
Removes the pair with the specified key and copies the value that was removed to the ref parameter.
FORCEINLINE void Reserve (int32 Number)
Preallocates enough memory to contain Number elements.
FORCEINLINE void Reset ()
Efficiently empties out the map but preserves all allocations and capacities.
FORCEINLINE void Shrink ()
Shrinks the pair set to avoid slack.
Private Attributes
FThreadSafeCounter RefCount
Friends
class FAssetDataTagMapSharedView
Additional Inherited Members
Public Types inherited from TSortedMap< FName, FString, FDefaultAllocator, FNameFastLess >
typedef TPair< KeyType, ValueType > ElementType
using IntrusiveUnsetOptionalStateType
typedef TTypeTraits< KeyType >::ConstPointerType KeyConstPointerType
typedef TTypeTraits< KeyType >::ConstInitType KeyInitType
typedef FName KeyType
typedef ElementArrayType::RangedForConstIteratorType RangedForConstIteratorType
typedef ElementArrayType::RangedForIteratorType RangedForIteratorType
Ranged For iterators.
typedef TTypeTraits< ValueType >::ConstInitType ValueInitType
typedef FString ValueType
Static Public Attributes inherited from TSortedMap< FName, FString, FDefaultAllocator, FNameFastLess >
static constexpr bool bHasIntrusiveUnsetOptionalState
Detailed Description
"Loose" FName -> FString that is optionally ref-counted and owned by a FAssetDataTagMapSharedView
Definition at line 288 of file AssetDataTagMap.h.
Constructor & Destructor Documentation
FAssetDataTagMap() [1/3]
FAssetDataTagMap::FAssetDataTagMap () default
Referenced by FAssetDataTagMap(), FAssetDataTagMap(), operator=(), and operator=().
FAssetDataTagMap() [2/3]
FAssetDataTagMap::FAssetDataTagMap (const FAssetDataTagMap & O) inline
Definition at line 295 of file AssetDataTagMap.h.
References FAssetDataTagMap().
FAssetDataTagMap() [3/3]
FAssetDataTagMap::FAssetDataTagMap (FAssetDataTagMap && O) inline
Definition at line 296 of file AssetDataTagMap.h.
References FAssetDataTagMap(), and MoveTemp().
Member Function Documentation
operator=() [1/2]
FAssetDataTagMap & FAssetDataTagMap::operator= (const FAssetDataTagMap & O) inline
Definition at line 297 of file AssetDataTagMap.h.
References FAssetDataTagMap(), and TSortedMap< FName, FString, FDefaultAllocator, FNameFastLess >::operator=().
operator=() [2/2]
FAssetDataTagMap & FAssetDataTagMap::operator= (FAssetDataTagMap && O) inline
Definition at line 298 of file AssetDataTagMap.h.
References FAssetDataTagMap(), MoveTemp(), and TSortedMap< FName, FString, FDefaultAllocator, FNameFastLess >::operator=().
Friends And Related Symbol Documentation
FAssetDataTagMapSharedView
friend class FAssetDataTagMapSharedView friend
Definition at line 291 of file AssetDataTagMap.h.
References FAssetDataTagMapSharedView.
Referenced by FAssetDataTagMapSharedView.
Field Documentation
RefCount
FThreadSafeCounter FAssetDataTagMap::RefCount mutable private
Definition at line 290 of file AssetDataTagMap.h.
The documentation for this class was generated from the following file:
Runtime/CoreUObject/Public/AssetRegistry/AssetDataTagMap.h