Unreal Engine 5.6 C++ API: FEngineVersion Class Reference
FEngineVersion Class Reference
Utility functions.
#include "EngineVersion.h"
Public Member Functions
FEngineVersion ()=default
Empty constructor.
FEngineVersion (uint16 InMajor, uint16 InMinor, uint16 InPatch, uint32 InChangelist, const FString &InBranch)
Constructs a version from the given components.
void Empty ()
Clears the object.
bool ExactMatch (const FEngineVersion &Other) const
Checks whether this engine version is an exact match for another engine version.
const FString GetBranch () const
Returns the branch name corresponding to this version.
const FString & GetBranchDescriptor () const
bool IsCompatibleWith (const FEngineVersionBase &Other) const
Checks compatibility with another version object.
void Set (uint16 InMajor, uint16 InMinor, uint16 InPatch, uint32 InChangelist, const FString &InBranch)
Sets the version to the given values.
FString ToString (EVersionComponent LastComponent=EVersionComponent::Branch) const
Generates a version string.
Public Member Functions inherited from FEngineVersionBase
FEngineVersionBase ()=default
Empty constructor.
FEngineVersionBase (uint16 InMajor, uint16 InMinor, uint16 InPatch=0, uint32 InChangelist=0)
Constructs a version from the given components.
uint32 GetChangelist () const
Returns the changelist number corresponding to this version.
FORCEINLINE uint16 GetMajor () const
Returns the Major version number corresponding to this version.
FORCEINLINE uint16 GetMinor () const
Returns the Minor version number corresponding to this version.
FORCEINLINE uint16 GetPatch () const
Returns the Patch version number corresponding to this version.
bool HasChangelist () const
Returns whether the engine version has a changelist component.
bool IsEmpty () const
Returns whether the current version is empty.
bool IsLicenseeVersion () const
Checks if the changelist number represents licensee changelist number.
Static Public Member Functions
static const FEngineVersion & CompatibleWith ()
Gets the earliest version which this engine maintains strict API and package compatibility with.
static const FEngineVersion & Current ()
Gets the current engine version.
static bool Parse (const FString &Text, FEngineVersion &OutVersion)
Parses a version object from a string.
static void TearDown ()
Clears the current and compatible-with engine versions.
Static Public Member Functions inherited from FEngineVersionBase
static uint32 EncodeLicenseeChangelist (uint32 Changelist)
Encodes a licensee changelist number (by setting the top bit)
static EVersionComparison GetNewest (const FEngineVersionBase &First, const FEngineVersionBase &Second, EVersionComponent *OutComponent)
Returns the newest of two versions, and the component at which they differ.
Private Attributes
FString Branch
Branch name.
Friends
void operator<< (class FArchive &Ar, FEngineVersion &Version)
Serialization functions.
void operator<< (FStructuredArchive::FSlot Slot, FEngineVersion &Version)
Additional Inherited Members
Protected Attributes inherited from FEngineVersionBase
uint32 Changelist = 0
Changelist number.
uint16 Major = 0
Major version number.
uint16 Minor = 0
Minor version number.
uint16 Patch = 0
Patch version number.
Detailed Description
Utility functions.
Definition at line 11 of file EngineVersion.h.
Constructor & Destructor Documentation
FEngineVersion() [1/2]
FEngineVersion::FEngineVersion () default
Empty constructor.
Initializes the version to 0.0.0-0.
Referenced by CompatibleWith(), Current(), ExactMatch(), operator<<, operator<<, and Parse().
FEngineVersion() [2/2]
FEngineVersion::FEngineVersion (uint16 InMajor, uint16 InMinor, uint16 InPatch, uint32 InChangelist, const FString & InBranch)
Constructs a version from the given components.
Member Function Documentation
CompatibleWith()
const FEngineVersion & FEngineVersion::CompatibleWith () static
Gets the earliest version which this engine maintains strict API and package compatibility with.
References FEngineVersion().
Current()
const FEngineVersion & FEngineVersion::Current () static
Gets the current engine version.
References FEngineVersion().
Empty()
void FEngineVersion::Empty ()
Clears the object.
ExactMatch()
bool FEngineVersion::ExactMatch (const FEngineVersion & Other) const
Checks whether this engine version is an exact match for another engine version.
References FEngineVersion(), and Other.
GetBranch()
const FString FEngineVersion::GetBranch () const inline
Returns the branch name corresponding to this version.
Definition at line 53 of file EngineVersion.h.
References Branch, and TEXT.
GetBranchDescriptor()
const FString & FEngineVersion::GetBranchDescriptor () const
IsCompatibleWith()
bool FEngineVersion::IsCompatibleWith (const FEngineVersionBase & Other) const
Checks compatibility with another version object.
References FEngineVersionBase::FEngineVersionBase(), and Other.
Parse()
bool FEngineVersion::Parse (const FString & Text, FEngineVersion & OutVersion) static
Parses a version object from a string.
Returns true on success.
References FEngineVersion(), and Text.
Set()
void FEngineVersion::Set (uint16 InMajor, uint16 InMinor, uint16 InPatch, uint32 InChangelist, const FString & InBranch)
Sets the version to the given values.
TearDown()
void FEngineVersion::TearDown () static
Clears the current and compatible-with engine versions.
ToString()
FString FEngineVersion::ToString (EVersionComponent LastComponent = EVersionComponent::Branch) const
Generates a version string.
References Branch.
Friends And Related Symbol Documentation
operator<< [1/2]
void operator<< (class FArchive & Ar, FEngineVersion & Version) friend
Serialization functions.
References FEngineVersion(), and Ar.
operator<< [2/2]
void operator<< (FStructuredArchive::FSlot Slot, FEngineVersion & Version) friend
References FEngineVersion().
Field Documentation
Branch
FString FEngineVersion::Branch private
Branch name.
Definition at line 64 of file EngineVersion.h.
Referenced by GetBranch().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Misc/EngineVersion.h