Unreal Engine 5.6 C++ API: UE::GC::FPrefetchingObjectIterator Class Reference
UE::GC::FPrefetchingObjectIterator Class Reference
#include "FastReferenceCollector.h"
Public Member Functions
FPrefetchingObjectIterator (TConstArrayView< UObject * > Objects)
FORCEINLINE_DEBUGGABLE void Advance ()
UObject * GetCurrentObject ()
bool HasMore () const
Private Attributes
UObject *const * End
UObject *const * It
const FSchemaView * PrefetchedSchema
Detailed Description
Definition at line 91 of file FastReferenceCollector.h.
Constructor & Destructor Documentation
FPrefetchingObjectIterator()
UE::GC::FPrefetchingObjectIterator::FPrefetchingObjectIterator (TConstArrayView< UObject * > Objects) inline explicit
Definition at line 95 of file FastReferenceCollector.h.
References begin(), End, end(), It, Num, and PrefetchedSchema.
Member Function Documentation
Advance()
FORCEINLINE_DEBUGGABLE void UE::GC::FPrefetchingObjectIterator::Advance () inline
Definition at line 101 of file FastReferenceCollector.h.
References FORCEINLINE_DEBUGGABLE, It, UE::GC::ObjectLookahead, FGenericPlatformMisc::Prefetch(), UObjectBase::PrefetchClass(), PrefetchedSchema, and UObjectBase::PrefetchOuter().
GetCurrentObject()
UObject * UE::GC::FPrefetchingObjectIterator::GetCurrentObject () inline
Definition at line 114 of file FastReferenceCollector.h.
References It.
HasMore()
bool UE::GC::FPrefetchingObjectIterator::HasMore () const inline
Definition at line 113 of file FastReferenceCollector.h.
References End, and It.
Referenced by UE::GC::TFastReferenceCollector< ProcessorType, CollectorType >::ProcessObjects().
Field Documentation
End
UObject* const* UE::GC::FPrefetchingObjectIterator::End private
Definition at line 118 of file FastReferenceCollector.h.
Referenced by FPrefetchingObjectIterator(), and HasMore().
It
UObject* const* UE::GC::FPrefetchingObjectIterator::It private
Definition at line 117 of file FastReferenceCollector.h.
Referenced by FPrefetchingObjectIterator(), Advance(), GetCurrentObject(), and HasMore().
PrefetchedSchema
const FSchemaView* UE::GC::FPrefetchingObjectIterator::PrefetchedSchema private
Definition at line 119 of file FastReferenceCollector.h.
Referenced by FPrefetchingObjectIterator(), and Advance().
The documentation for this class was generated from the following file:
Runtime/CoreUObject/Public/UObject/FastReferenceCollector.h