Unreal Engine 5.6 C++ API: FMaterialShaderMapContent Class Reference
FMaterialShaderMapContent Class Reference
#include "MaterialShared.h"
Data Structures
struct FProjectMeshShaderMapToKey
Public Types
using Super = FShaderMapContent
Public Member Functions
FMaterialShaderMapContent (EShaderPlatform InPlatform=EShaderPlatform::SP_NumPlatforms)
~FMaterialShaderMapContent ()
void Finalize (const FShaderMapResourceCode *Code)
uint32 GetNumShaderPipelines () const
uint32 GetNumShaders () const
Public Member Functions inherited from FShaderMapContent
RENDERCORE_API FShaderMapContent (EShaderPlatform InPlatform)
Default constructor.
RENDERCORE_API ~FShaderMapContent ()
Destructor ensures pipelines cleared up.
RENDERCORE_API void AddShader (const FHashedName &TypeName, int32 PermutationId, FShader *Shader)
RENDERCORE_API void AddShaderPipeline (FShaderPipeline *Pipeline)
RENDERCORE_API void DumpShaderList (const FShaderMapBase &InShaderMap, FShaderListReport &Out) const
RENDERCORE_API void Empty ()
clears out all shaders and deletes shader pipelines held in the map
RENDERCORE_API void Finalize (const FShaderMapResourceCode *Code)
RENDERCORE_API FShader * FindOrAddShader (const FHashedName &TypeName, int32 PermutationId, FShader *Shader)
RENDERCORE_API FShaderPipeline * FindOrAddShaderPipeline (FShaderPipeline *Pipeline)
RENDERCORE_API uint32 GetMaxNumInstructionsForShader (const FShaderMapBase &InShaderMap, FShaderType *ShaderType) const
RENDERCORE_API uint32 GetMaxTextureSamplersShaderMap (const FShaderMapBase &InShaderMap) const
uint32 GetNumShaderPipelines () const
RENDERCORE_API uint32 GetNumShaders () const
RENDERCORE_API void GetOutdatedTypes (const FShaderMapBase &InShaderMap, TArray< const FShaderType * > &OutdatedShaderTypes, TArray< const FShaderPipelineType * > &OutdatedShaderPipelineTypes, TArray< const FVertexFactoryType * > &OutdatedFactoryTypes) const
RENDERCORE_API FShader * GetShader (const FHashedName &TypeName, int32 PermutationId=0) const
Finds the shader with the given type name.
FShader * GetShader (const FShaderType *ShaderType, int32 PermutationId=0) const
Finds the shader with the given type.
template<typename ShaderType>
ShaderType * GetShader (const typename ShaderType::FPermutationDomain &PermutationVector) const
Finds the shader with the given type.
template<typename ShaderType>
ShaderType * GetShader (int32 PermutationId=0) const
Finds the shader with the given type.
RENDERCORE_API void GetShaderList (const FShaderMapBase &InShaderMap, const FSHAHash &InMaterialShaderMapHash, TMap< FShaderId, TShaderRef< FShader > > &OutShaders) const
Builds a list of the shaders in a shader map.
RENDERCORE_API void GetShaderList (const FShaderMapBase &InShaderMap, TMap< FHashedName, TShaderRef< FShader > > &OutShaders) const
Builds a list of the shaders in a shader map.
FShaderPipeline * GetShaderPipeline (const FHashedName &PipelineTypeName) const
FShaderPipeline * GetShaderPipeline (const FShaderPipelineType *PipelineType) const
RENDERCORE_API void GetShaderPipelineList (const FShaderMapBase &InShaderMap, TArray< FShaderPipelineRef > &OutShaderPipelines, FShaderPipeline::EFilter Filter) const
Builds a list of the shader pipelines in a shader map.
TArrayView< const TMemoryImagePtr< FShaderPipeline > > GetShaderPipelines () const
RENDERCORE_API EShaderPlatform GetShaderPlatform () const
TArrayView< const TMemoryImagePtr< FShader > > GetShaders () const
const FShader::FShaderStatisticMap GetShaderStatisticsMapForShader (const FShaderMapBase &InShaderMap, FShaderType *ShaderType) const
bool HasShader (const FHashedName &TypeName, int32 PermutationId) const
Finds the shader with the given type.
bool HasShader (const FShaderType *Type, int32 PermutationId) const
bool HasShaderPipeline (const FHashedName &PipelineTypeName) const
bool HasShaderPipeline (const FShaderPipelineType *PipelineType) const
bool IsEmpty () const
RENDERCORE_API void RemoveShaderPipelineType (const FShaderPipelineType *ShaderPipelineType)
RENDERCORE_API void RemoveShaderTypePermutaion (const FHashedName &TypeName, int32 PermutationId)
Removes the shader of the given type from the shader map.
void RemoveShaderTypePermutaion (const FShaderType *Type, int32 PermutationId)
RENDERCORE_API void SaveShaderStableKeys (const FShaderMapBase &InShaderMap, EShaderPlatform TargetShaderPlatform, const struct FStableShaderKeyAndValue &SaveKeyVal)
RENDERCORE_API void UpdateHash (FSHA1 &Hasher) const
RENDERCORE_API void Validate (const FShaderMapBase &InShaderMap) const
Private Member Functions
FMeshMaterialShaderMap * AcquireMeshShaderMap (const FHashedName &VertexFactoryTypeName)
void AddMeshShaderMap (const FHashedName &VertexFactoryTypeName, FMeshMaterialShaderMap *MeshShaderMap)
DECLARE_TYPE_LAYOUT (FMaterialShaderMapContent, NonVirtual)
const FMeshMaterialShaderMap * GetMeshShaderMap (const FHashedName &VertexFactoryTypeName) const
LAYOUT_FIELD (FMaterialCompilationOutput, MaterialCompilationOutput)
Uniform expressions generated from the material compile.
LAYOUT_FIELD (FScriptName, ResolutionRelativeToInput)
LAYOUT_FIELD (FScriptName, UserSceneTextureOutput)
LAYOUT_FIELD (FSHAHash, ShaderContentHash)
LAYOUT_FIELD (TMemoryImageArray< TMemoryImagePtr< FMeshMaterialShaderMap > >, OrderedMeshShaderMaps)
The material's mesh shader maps, indexed by VFType->GetId(), for fast lookup at runtime.
LAYOUT_FIELD_EDITORONLY (FMemoryImageString, DebugDescription)
LAYOUT_FIELD_EDITORONLY (FMemoryImageString, FriendlyName)
LAYOUT_FIELD_EDITORONLY (FMemoryImageString, MaterialPath)
LAYOUT_FIELD_EDITORONLY (TMemoryImageArray< FMaterialProcessedSource >, ShaderProcessedSource)
LAYOUT_FIELD_INITIALIZED (int32, UserTextureDivisorX, 0)
LAYOUT_FIELD_INITIALIZED (int32, UserTextureDivisorY, 0)
void RemoveMeshShaderMap (const FHashedName &VertexFactoryTypeName)
Friends
class FMaterialShaderMap
Additional Inherited Members
Protected Types inherited from FShaderMapContent
using FMemoryImageHashTable = THashTable<FMemoryImageAllocator>
Protected Member Functions inherited from FShaderMapContent
RENDERCORE_API void EmptyShaderPipelines ()
LAYOUT_FIELD (FMemoryImageHashTable, ShaderHash)
LAYOUT_FIELD (FMemoryImageName, ShaderPlatformName)
The ShaderPlatform Name this shader map was compiled with.
LAYOUT_FIELD (TMemoryImageArray< FHashedName >, ShaderTypes)
LAYOUT_FIELD (TMemoryImageArray< int32 >, ShaderPermutations)
LAYOUT_FIELD (TMemoryImageArray< TMemoryImagePtr< FShader > >, Shaders)
LAYOUT_FIELD (TMemoryImageArray< TMemoryImagePtr< FShaderPipeline > >, ShaderPipelines)
Detailed Description
Definition at line 1374 of file MaterialShared.h.
Member Typedef Documentation
Super
using FMaterialShaderMapContent::Super = FShaderMapContent
Definition at line 1379 of file MaterialShared.h.
Constructor & Destructor Documentation
FMaterialShaderMapContent()
FMaterialShaderMapContent::FMaterialShaderMapContent (EShaderPlatform InPlatform = EShaderPlatform::SP_NumPlatforms) inline explicit
Definition at line 1381 of file MaterialShared.h.
References FShaderMapContent::FShaderMapContent().
Referenced by DECLARE_TYPE_LAYOUT().
~FMaterialShaderMapContent()
FMaterialShaderMapContent::~FMaterialShaderMapContent ()
Member Function Documentation
AcquireMeshShaderMap()
FMeshMaterialShaderMap * FMaterialShaderMapContent::AcquireMeshShaderMap (const FHashedName & VertexFactoryTypeName) private
AddMeshShaderMap()
void FMaterialShaderMapContent::AddMeshShaderMap (const FHashedName & VertexFactoryTypeName, FMeshMaterialShaderMap * MeshShaderMap) private
DECLARE_TYPE_LAYOUT()
FMaterialShaderMapContent::DECLARE_TYPE_LAYOUT (FMaterialShaderMapContent , NonVirtual) private
References FMaterialShaderMapContent().
Finalize()
void FMaterialShaderMapContent::Finalize (const FShaderMapResourceCode * Code)
GetMeshShaderMap()
const FMeshMaterialShaderMap * FMaterialShaderMapContent::GetMeshShaderMap (const FHashedName & VertexFactoryTypeName) const private
GetNumShaderPipelines()
uint32 FMaterialShaderMapContent::GetNumShaderPipelines () const inline
Definition at line 1394 of file MaterialShared.h.
References FShaderMapContent::GetNumShaderPipelines().
GetNumShaders()
uint32 FMaterialShaderMapContent::GetNumShaders () const inline
Definition at line 1384 of file MaterialShared.h.
References FShaderMapContent::GetNumShaders().
LAYOUT_FIELD() [1/5]
FMaterialShaderMapContent::LAYOUT_FIELD (FMaterialCompilationOutput , MaterialCompilationOutput) private
Uniform expressions generated from the material compile.
LAYOUT_FIELD() [2/5]
FMaterialShaderMapContent::LAYOUT_FIELD (FScriptName , ResolutionRelativeToInput) private
LAYOUT_FIELD() [3/5]
FMaterialShaderMapContent::LAYOUT_FIELD (FScriptName , UserSceneTextureOutput) private
LAYOUT_FIELD() [4/5]
FMaterialShaderMapContent::LAYOUT_FIELD (FSHAHash , ShaderContentHash) private
LAYOUT_FIELD() [5/5]
FMaterialShaderMapContent::LAYOUT_FIELD (TMemoryImageArray< TMemoryImagePtr< FMeshMaterialShaderMap > > , OrderedMeshShaderMaps) private
The material's mesh shader maps, indexed by VFType->GetId(), for fast lookup at runtime.
LAYOUT_FIELD_EDITORONLY() [1/4]
FMaterialShaderMapContent::LAYOUT_FIELD_EDITORONLY (FMemoryImageString , DebugDescription) private
LAYOUT_FIELD_EDITORONLY() [2/4]
FMaterialShaderMapContent::LAYOUT_FIELD_EDITORONLY (FMemoryImageString , FriendlyName) private
LAYOUT_FIELD_EDITORONLY() [3/4]
FMaterialShaderMapContent::LAYOUT_FIELD_EDITORONLY (FMemoryImageString , MaterialPath) private
LAYOUT_FIELD_EDITORONLY() [4/4]
FMaterialShaderMapContent::LAYOUT_FIELD_EDITORONLY (TMemoryImageArray< FMaterialProcessedSource > , ShaderProcessedSource) private
LAYOUT_FIELD_INITIALIZED() [1/2]
FMaterialShaderMapContent::LAYOUT_FIELD_INITIALIZED (int32 , UserTextureDivisorX , 0) private
LAYOUT_FIELD_INITIALIZED() [2/2]
FMaterialShaderMapContent::LAYOUT_FIELD_INITIALIZED (int32 , UserTextureDivisorY , 0) private
RemoveMeshShaderMap()
void FMaterialShaderMapContent::RemoveMeshShaderMap (const FHashedName & VertexFactoryTypeName) private
Friends And Related Symbol Documentation
FMaterialShaderMap
friend class FMaterialShaderMap friend
Definition at line 1376 of file MaterialShared.h.
References FMaterialShaderMap.
Referenced by FMaterialShaderMap.
The documentation for this class was generated from the following file:
Runtime/Engine/Public/MaterialShared.h