Unreal Engine 5.6 C++ API: SRigVMGraphPinEnumPicker Class Reference
SRigVMGraphPinEnumPicker Class Reference
#include "SRigVMGraphPinEnumPicker.h"
Public Member Functions
SLATE_ARGUMENT (URigVMPin *, ModelPin) SLATE_END_ARGS() void Construct(const FArguments &InArgs
SLATE_BEGIN_ARGS (SRigVMGraphPinEnumPicker)
Public Member Functions inherited from SGraphPin
SGraphPin ()
virtual ~SGraphPin ()
bool AreConnectionsFaded () const
void EnableDragAndDrop (bool bEnable)
Enables or disables drag and drop on the pin.
bool GetDefaultValueIsEditable () const
True if the pin's default value can be edited, false if it is read only.
virtual EVisibility GetDefaultValueVisibility () const
EEdGraphPinDirection GetDirection () const
TWeakPtr< SHorizontalBox > GetFullPinHorizontalRowWidget ()
Retrieves the full horizontal box that contains the pin's row content.
bool GetIsConnectable () const
Returns whether or not this pin is currently connectable.
TSharedRef< SWrapBox > GetLabelAndValue () const
Get the label/value part of the pin widget.
UE::Slate::FDeprecateVector2DResult GetNodeOffset () const
Gets Node Offset.
TSharedPtr< SWidget > GetPinImageWidget () const
Returns the current pin image widget that is being used.
UEdGraphPin * GetPinObj () const
virtual TSharedPtr< IToolTip > GetToolTip () override
TSharedRef< SWidget > GetValueWidget () const
Get the widget created by GetDefaultValueWidget()
bool HasInteractiveTooltip () const
void InvalidateGraphData ()
Called when ed graph data is cleared, indicating this widget can no longer safely access GraphPinObj Typically an SGraphPin is destroyed before the ed graph data is actually deleted but because SWidget is reference counted we have had problems in the past with the SGraphPin (or Node) living unexpectedly long.
bool IsArray () const
bool IsByMutableRef () const
bool IsConnected () const
bool IsDelegate () const
bool IsEditingEnabled () const
True if pin can be edited.
bool IsMap () const
EVisibility IsPinVisibleAsAdvanced () const
If pin in node is visible at all.
bool IsSet () const
virtual void OnDragEnter (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent) override
Called during drag and drop when the drag enters a widget.
virtual void OnDragLeave (const FDragDropEvent &DragDropEvent) override
Called during drag and drop when the drag leaves a widget.
virtual FReply OnDragOver (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent) override
Called during drag and drop when the the mouse is being dragged over a widget.
virtual FReply OnDrop (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent) override
Called when the user is dropping something onto a widget; terminates drag and drop.
virtual FReply OnMouseButtonUp (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent) override
The system calls this method to notify the widget that a mouse button was release within it.
virtual void OnMouseEnter (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent) override
The system will use this event to notify a widget that the cursor has entered it.
virtual void OnMouseLeave (const FPointerEvent &MouseEvent) override
The system will use this event to notify a widget that the cursor has left it.
virtual FReply OnMouseMove (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent) override
The system calls this method to notify the widget that a mouse moved within it.
virtual FReply OnPinMouseDown (const FGeometry &SenderGeometry, const FPointerEvent &MouseEvent)
Handle clicking on the pin.
FReply OnPinNameMouseDown (const FGeometry &SenderGeometry, const FPointerEvent &MouseEvent)
Handle clicking on the pin name.
void RefreshLOD ()
Refresh the level of detail applied to the pin name.
void SetCustomPinIcon (const FSlateBrush *InConnectedBrush, const FSlateBrush *InDisconnectedBrush)
Override the visual look of the pin by providing two custom brushes.
void SetDiffHighlighted (bool bHighlighted)
void SetFadeConnections (bool bInFadeConnections)
Makes Pin Connection Wires transparent.
void SetIsEditable (TAttribute< bool > InIsEditable)
Set attribute for determining if pin is editable.
void SetOnlyShowDefaultValue (bool bNewOnlyShowDefaultValue)
Set this pin to only be used to display default value.
void SetOwner (const TSharedRef< SGraphNode > OwnerNode)
void SetPinColorModifier (FLinearColor InColor)
Allows the connection drawing policy to control the pin color.
void SetPinDiffColor (TOptional< FLinearColor > InColor)
Allows Diff to highlight pins.
void SetPinImageWidget (TSharedRef< SWidget > NewWidget)
Sets the pin widget for this pin.
void SetPinObj (UEdGraphPin *PinObj)
void SetShowLabel (bool bNewDrawLabel)
Control whether we draw the label on this pin.
UsePinColorForText SLATE_ARGUMENT (float, SideToSideMargin) SLATE_END_ARGS() void Construct(const FArguments &InArgs
Construct this widget.
SLATE_ARGUMENT (FName, PinLabelStyle) SLATE_ARGUMENT(bool
SLATE_BEGIN_ARGS (SGraphPin)
virtual void Tick (const FGeometry &AllottedGeometry, const double InCurrentTime, const float InDeltaTime) override
Ticks this widget with Geometry.
virtual bool TryHandlePinConnection (SGraphPin &OtherSPin)
Tries to handle making a connection to another pin, depending on the schema and the pins it may do:
Public Member Functions inherited from SBorder
virtual int32 OnPaint (const FPaintArgs &Args, const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, FSlateWindowElementList &OutDrawElements, int32 LayerId, const FWidgetStyle &InWidgetStyle, bool bParentEnabled) const override
The widget should respond by populating the OutDrawElements array with FDrawElements that represent it and any of its children.
Public Member Functions inherited from SCompoundWidget
virtual FChildren * GetChildren () override
Returns the useful children (if any) of this widget.
virtual FSlateColor GetForegroundColor () const override
virtual void OnArrangeChildren (const FGeometry &AllottedGeometry, FArrangedChildren &ArrangedChildren) const override
Compute the Geometry of all the children and add populate the ArrangedChildren list with their values.
virtual void SetVisibility (TAttribute< EVisibility > InVisibility) override final
Public Member Functions inherited from SWidget
template<typename MetaDataType>
void AddMetadata (const TSharedRef< MetaDataType > &AddMe)
Add metadata to this widget.
virtual const FSlateInvalidationRoot * Advanced_AsInvalidationRoot () const
FORCEINLINE TSharedPtr< SWidget > Advanced_GetPaintParentWidget () const
virtual bool Advanced_IsInvalidationRoot () const
virtual bool Advanced_IsWindow () const
Is this widget derivative of SWindow.
void ArrangeChildren (const FGeometry &AllottedGeometry, FArrangedChildren &ArrangedChildren, bool bUpdateAttributes=false) const
Non-virtual entry point for arrange children.
void AssignParentWidget (TSharedPtr< SWidget > InParent)
FORCEINLINE void CacheVolatility ()
Recalculates volatility of the widget and caches the result.
FSlateRect CalculateCullingAndClippingRules (const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, bool &bClipToBounds, bool &bAlwaysClip, bool &bIntersectClipBounds) const
Calculates what if any clipping state changes need to happen when drawing this widget.
bool ConditionallyDetatchParentWidget (SWidget *InExpectedParent)
void EnableToolTipForceField (const bool bEnableForceField)
Sets whether this widget is a "tool tip force field".
FORCEINLINE void ForceVolatile (bool bForce)
Should this widget always appear as volatile for any layout caching host widget.
virtual FChildren * GetAllChildren ()
Returns the children (if any) of this widget that are used by the invalidation system.
template<typename MetaDataType>
TArray< TSharedRef< MetaDataType > > GetAllMetaData () const
Get all metadata of the type provided.
const FGeometry & GetCachedGeometry () const
bool GetCanTick () const
FORCEINLINE EWidgetClipping GetClipping () const
FName GetCreatedInLocation () const
FORCEINLINE FMargin GetCullingBoundsExtension () const
const TOptional< FSlateClippingState > & GetCurrentClippingState () const
Returns the clipping state to clip this widget against its parent.
UE::Slate::FDeprecateVector2DResult GetDesiredSize () const
virtual FSlateColor GetDisabledForegroundColor () const
EFlowDirectionPreference GetFlowDirectionPreference () const
Gets the desired flow direction for the layout.
template<typename MetaDataType>
TSharedPtr< MetaDataType > GetMetaData () const
Get the metadata of the type provided.
const FGeometry & GetPaintSpaceGeometry () const
Gets the last geometry used to Tick the widget.
FORCEINLINE TSharedPtr< SWidget > GetParentWidget () const
const FSlateWidgetPersistentState & GetPersistentState () const
FORCEINLINE EWidgetPixelSnapping GetPixelSnapping () const
const FWidgetProxyHandle GetProxyHandle () const
virtual FString GetReadableLocation () const
virtual float GetRelativeLayoutScale (const int32 ChildIndex, float LayoutScaleMultiplier) const
What is the Child's scale relative to this widget.
FORCEINLINE float GetRenderOpacity () const
FORCEINLINE const TOptional< FSlateRenderTransform > & GetRenderTransform () const
FORCEINLINE UE::Slate::FDeprecateVector2DResult GetRenderTransformPivot () const
FORCEINLINE UE::Slate::FDeprecateVector2DResult GetRenderTransformPivotWithRespectToFlowDirection () const
FORCEINLINE TOptional< FSlateRenderTransform > GetRenderTransformWithRespectToFlowDirection () const
FORCEINLINE TStatId GetStatID (bool bForDeferredUse=false) const
virtual FName GetTag () const
const FGeometry & GetTickSpaceGeometry () const
Gets the last geometry used to Tick the widget.
FName GetType () const
FString GetTypeAsString () const
FORCEINLINE EVisibility GetVisibility () const
virtual EWindowZone::Type GetWindowZoneOverride () const
Called when the mouse is moved over the widget's window, to determine if we should report whether OS-specific features should be active at this location (such as a title bar grip, system menu, etc.) Usually you should not need to override this function.
bool HasActiveTimers () const
Does this widget have any active timers?
bool HasAnyUpdateFlags (EWidgetUpdateFlags FlagsToCheck) const
TOptional< EFocusCause > HasAnyUserFocus () const
Gets whether or not any users have this widget focused, and if so the type of focus (first one found).
bool HasAnyUserFocusOrFocusedDescendants () const
bool HasFocusedDescendants () const
virtual bool HasKeyboardFocus () const
Checks to see if this widget currently has the keyboard focus.
bool HasMouseCapture () const
Checks to see if this widget is the current mouse captor.
bool HasMouseCaptureByUser (int32 UserIndex, TOptional< int32 > PointerIndex=TOptional< int32 >()) const
Checks to see if this widget has mouse capture from the provided user.
bool HasRegisteredSlateAttribute () const
bool HasToolTipForceField () const
TOptional< EFocusCause > HasUserFocus (int32 UserIndex) const
Gets whether or not the specified users has this widget focused, and if so the type of focus.
bool HasUserFocusedDescendants (int32 UserIndex) const
Gets whether or not the specified users has this widget or any descendant focused.
void Invalidate (EInvalidateWidgetReason InvalidateReason)
Invalidates the widget from the view of a layout caching widget that may own this widget.
bool IsAttributesUpdatesEnabled () const
bool IsDirectlyHovered () const
FORCEINLINE bool IsEnabled () const
bool IsHovered () const
virtual bool IsInteractable () const
FORCEINLINE bool IsParentValid () const
FORCEINLINE bool IsVolatile () const
Whether or not a widget is volatile and will update every frame without being invalidated.
FORCEINLINE bool IsVolatileIndirectly () const
This widget is volatile because its parent or some ancestor is volatile.
void MarkPrepassAsDirty ()
In fast path, if the widget is mark, do a full Prepass on its next update to calculate it's desired size.
bool NeedsPrepass () const
virtual FReply OnAnalogValueChanged (const FGeometry &MyGeometry, const FAnalogInputEvent &InAnalogInputEvent)
Called when an analog value changes on a button that supports analog.
virtual FCursorReply OnCursorQuery (const FGeometry &MyGeometry, const FPointerEvent &CursorEvent) const
The system asks each widget under the mouse to provide a cursor.
virtual FReply OnDragDetected (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Called when Slate detects that a widget started to be dragged.
virtual void OnFinishedKeyInput ()
All the key (keyboard, gamepay, joystick, etc.) input from this frame has been routed.
virtual void OnFinishedPointerInput ()
All the pointer (mouse, touch, stylus, etc.) events from this frame have been routed.
virtual void OnFocusChanging (const FWeakWidgetPath &PreviousFocusPath, const FWidgetPath &NewWidgetPath, const FFocusEvent &InFocusEvent)
Called whenever a focus path is changing on all the widgets within the old and new focus paths.
virtual void OnFocusLost (const FFocusEvent &InFocusEvent)
Called when this widget loses focus.
virtual FReply OnFocusReceived (const FGeometry &MyGeometry, const FFocusEvent &InFocusEvent)
Called when focus is given to this widget.
virtual FReply OnKeyChar (const FGeometry &MyGeometry, const FCharacterEvent &InCharacterEvent)
Called after a character is entered while this widget has keyboard focus.
virtual FReply OnKeyDown (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
Called after a key is pressed when this widget has focus (this event bubbles if not handled)
virtual FReply OnKeyUp (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
Called after a key is released when this widget has focus.
virtual TOptional< TSharedRef< SWidget > > OnMapCursor (const FCursorReply &CursorReply) const
After OnCursorQuery has specified a cursor type the system asks each widget under the mouse to map that cursor to a widget.
virtual FReply OnMotionDetected (const FGeometry &MyGeometry, const FMotionEvent &InMotionEvent)
Called when motion is detected (controller or device) e.g.
virtual FReply OnMouseButtonDoubleClick (const FGeometry &InMyGeometry, const FPointerEvent &InMouseEvent)
Called when a mouse button is double clicked.
virtual FReply OnMouseButtonDown (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system calls this method to notify the widget that a mouse button was pressed within it.
virtual void OnMouseCaptureLost (const FCaptureLostEvent &CaptureLostEvent)
Called when this widget had captured the mouse, but that capture has been revoked for some reason.
virtual FReply OnMouseWheel (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Called when the mouse wheel is spun.
virtual FNavigationReply OnNavigation (const FGeometry &MyGeometry, const FNavigationEvent &InNavigationEvent)
Called when navigation is requested e.g.
virtual FReply OnPreviewKeyDown (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
Called after a key is pressed when this widget or a child of this widget has focus If a widget handles this event, OnKeyDown will not be passed to the focused widget.
virtual FReply OnPreviewMouseButtonDown (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Just like OnMouseButtonDown, but tunnels instead of bubbling.
virtual FPopupMethodReply OnQueryPopupMethod () const
Popups can manifest in a NEW OS WINDOW or via an OVERLAY in an existing window.
virtual TOptional< bool > OnQueryShowFocus (const EFocusCause InFocusCause) const
Called to determine if we should render the focus brush.
virtual void OnToolTipClosing ()
Called when a tooltip displayed from this widget is being closed.
virtual FReply OnTouchEnded (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is ended (finger lifted)
virtual FReply OnTouchFirstMove (const FGeometry &MyGeometry, const FPointerEvent &TouchEvent)
Called when a touchpad touch first moves after TouchStarted.
virtual FReply OnTouchForceChanged (const FGeometry &MyGeometry, const FPointerEvent &TouchEvent)
Called when a touchpad touch force changes.
virtual FReply OnTouchGesture (const FGeometry &MyGeometry, const FPointerEvent &GestureEvent)
Called when the user performs a gesture on trackpad.
virtual FReply OnTouchMoved (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is moved (finger moved)
virtual FReply OnTouchStarted (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is started (finger down)
virtual TSharedPtr< FPopupLayer > OnVisualizePopup (const TSharedRef< SWidget > &PopupContent)
Visualize a new pop-up if possible.
virtual bool OnVisualizeTooltip (const TSharedPtr< SWidget > &TooltipContent)
Called when Slate wants to visualize tooltip.
int32 Paint (const FPaintArgs &Args, const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, FSlateWindowElementList &OutDrawElements, int32 LayerId, const FWidgetStyle &InWidgetStyle, bool bParentEnabled) const
Called to tell a widget to paint itself (and it's children).
TSharedRef< FActiveTimerHandle > RegisterActiveTimer (float TickPeriod, FWidgetActiveTimerDelegate TickFunction)
Registers an "active timer" delegate that will execute at some regular interval.
template<typename MetaDataType>
int32 RemoveMetaData (const TSharedRef< MetaDataType > &RemoveMe)
Remove metadata to this widget.
void SetCanTick (bool bInCanTick)
void SetClipping (EWidgetClipping InClipping)
Sets the clipping to bounds rules for this widget.
FORCEINLINE void SetCullingBoundsExtension (const FMargin &InCullingBoundsExtension)
Sets an additional culling padding that is added to a widget to give more leeway when culling widgets.
void SetCursor (const TAttribute< TOptional< EMouseCursor::Type > > &InCursor)
Set the cursor that should appear when this widget is hovered.
void SetEnabled (TAttribute< bool > InEnabledState)
Sets the enabled state of this widget.
void SetFlowDirectionPreference (EFlowDirectionPreference InFlowDirectionPreference)
Sets how content should flow in this panel, based on the current culture.
void SetOnMouseButtonDown (FPointerEventHandler EventHandler)
See OnMouseButtonDown event.
void SetOnMouseButtonUp (FPointerEventHandler EventHandler)
See OnMouseButtonUp event.
void SetOnMouseDoubleClick (FPointerEventHandler EventHandler)
See OnMouseDoubleClick event.
void SetOnMouseEnter (FNoReplyPointerEventHandler EventHandler)
See OnMouseEnter event.
void SetOnMouseLeave (FSimpleNoReplyPointerEventHandler EventHandler)
See OnMouseLeave event.
void SetOnMouseMove (FPointerEventHandler EventHandler)
See OnMouseMove event.
void SetPixelSnapping (EWidgetPixelSnapping InPixelSnappingMethod)
Sets the pixel snapping method for this widget.
FORCEINLINE void SetRenderOpacity (float InRenderOpacity)
FORCEINLINE void SetRenderTransform (TAttribute< TOptional< FSlateRenderTransform > > InTransform)
FORCEINLINE void SetRenderTransformPivot (TAttribute< FVector2D > InTransformPivot)
FORCEINLINE void SetTag (FName InTag)
void SetToolTip (const TAttribute< TSharedPtr< IToolTip > > &InToolTip)
Set the tool tip that should appear when this widget is hovered.
void SetToolTipText (const FText &InToolTipText)
Set the tool tip that should appear when this widget is hovered.
void SetToolTipText (const TAttribute< FText > &ToolTipText)
Set the tool tip that should appear when this widget is hovered.
FORCEINLINE bool ShouldInvalidatePrepassDueToVolatility ()
void SlatePrepass ()
DEPRECATED version of SlatePrepass that assumes no scaling beyond AppScale.
void SlatePrepass (float InLayoutScaleMultiplier)
Descends to leaf-most widgets in the hierarchy and gathers desired sizes on the way up.
virtual bool SupportsKeyboardFocus () const
Checks to see if this widget supports keyboard focus.
virtual FString ToString () const
virtual TOptional< FVirtualPointerPosition > TranslateMouseCoordinateForCustomHitTestChild (const SWidget &ChildWidget, const FGeometry &MyGeometry, const FVector2D ScreenSpaceMouseCoordinate, const FVector2D LastScreenSpaceMouseCoordinate) const
void UnRegisterActiveTimer (const TSharedRef< FActiveTimerHandle > &ActiveTimerHandle)
Unregisters an active timer handle.
virtual bool ValidatePathToChild (SWidget *InChild)
Public Member Functions inherited from FSlateControlledConstruction
FSlateControlledConstruction ()=default
virtual ~FSlateControlledConstruction ()=default
virtual const FSlateWidgetClassData & GetWidgetClass () const =0
void operator delete (void *mem)
Public Member Functions inherited from TSharedFromThis< SWidget >
TSharedRef< SWidget, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< SWidget, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Data Fields
UEdGraphPin * InGraphPinObj
Data Fields inherited from SGraphPin
UsePinColorForText UEdGraphPin * InPin
Protected Member Functions
virtual TSharedRef< SWidget > GetDefaultValueWidget () override
Build the widget we should put into the 'default value' space, shown when nothing connected.
void HandleControlEnumChanged (TSharedPtr< FString > InItem, ESelectInfo::Type InSelectionInfo)
Protected Member Functions inherited from SGraphPin
virtual FReply ClickedOnPinStatusIcon ()
Toggle the watch pinning.
virtual bool DoesWidgetHandleSettingEditingEnabled () const
If true the graph pin subclass is responsible for setting the IsEnabled delegates for the aspects it cares about.
virtual FSlateColor GetHighlightColor () const
void GetInteractiveTooltipLocation (FVector2f &InOutDesiredLocation) const
virtual TSharedRef< SWidget > GetLabelWidget (const FName &InPinLabelStyle)
Get the widget we should put in the label space, which displays the name of the pin.
const FSlateBrush * GetPinBorder () const
virtual FSlateColor GetPinColor () const
TOptional< EMouseCursor::Type > GetPinCursor () const
virtual FSlateColor GetPinDiffColor () const
virtual const FSlateBrush * GetPinIcon () const
FText GetPinLabel () const
EVisibility GetPinLabelVisibility () const
If we should show the label on this pin.
virtual const FSlateBrush * GetPinStatusIcon () const
virtual EVisibility GetPinStatusIconVisibility () const
virtual FSlateColor GetPinTextColor () const
EVisibility GetPinVisiblity () const
Determines the pin's visibility based on the LOD factor, when it is low LOD, no hit test will occur.
FSlateColor GetSecondaryPinColor () const
const FSlateBrush * GetSecondaryPinIcon () const
FText GetTooltipText () const
virtual TSharedRef< FDragDropOperation > SpawnPinDragEvent (const TSharedRef< class SGraphPanel > &InGraphPanel, const TArray< TSharedRef< SGraphPin > > &InStartingPins)
Spawns a FDragConnection or similar class for the pin drag event.
UE_DEPRECATED (5.6, "Use the version of the function accepting FVector2f; this Slate API no longer interfaces directly with double-precision scalars and vectors.") void GetInteractiveTooltipLocation(FVector2D &InOutDesiredLocation) const
Gets the window location (in screen coords) for an interactive tooltip (e.g.
virtual bool UseLowDetailPinNames () const
Protected Member Functions inherited from SBorder
virtual FVector2D ComputeDesiredSize (float) const override
Compute the ideal size necessary to display this widget.
TSlateAttributeRef< FSlateColor > GetBorderBackgroundColorAttribute () const
TSlateAttributeRef< const FSlateBrush * > GetBorderImageAttribute () const
FVector2D GetDesiredSizeScale () const
Get the desired size scale multiplier.
TSlateAttributeRef< FVector2D > GetDesiredSizeScaleAttribute () const
bool GetShowDisabledEffect () const
Get whether or not to show the disabled effect when this border is disabled.
TSlateAttributeRef< bool > GetShowDisabledEffectAttribute () const
Protected Member Functions inherited from SCompoundWidget
SCompoundWidget ()
Disallow public construction.
virtual ~SCompoundWidget ()
TSlateAttributeRef< FLinearColor > GetColorAndOpacityAttribute () const
TSlateAttributeRef< FVector2D > GetContentScaleAttribute () const
TSlateAttributeRef< FSlateColor > GetForegroundColorAttribute () const
Protected Member Functions inherited from SWidget
SWidget ()
Hidden default constructor.
virtual ~SWidget ()
Dtor ensures that active timer handles are UnRegistered with the SlateApplication.
FORCEINLINE bool Advanced_InvalidateVolatility ()
Recalculates and caches volatility and returns 'true' if the volatility changed.
virtual void CacheDesiredSize (float InLayoutScaleMultiplier)
The system calls this method.
EFlowDirection ComputeFlowDirection () const
Establishes a new flow direction potentially, if this widget has a particular preference for it and all its children.
virtual bool ComputeVolatility () const
Recomputes the volatility of the widget.
virtual bool CustomPrepass (float LayoutScaleMultiplier)
bool FindChildGeometries (const FGeometry &MyGeometry, const TSet< TSharedRef< SWidget > > &WidgetsToFind, TMap< TSharedRef< SWidget >, FArrangedWidget > &OutResult) const
Find the geometry of a descendant widget.
void FindChildGeometries_Helper (const FGeometry &MyGeometry, const TSet< TSharedRef< SWidget > > &WidgetsToFind, TMap< TSharedRef< SWidget >, FArrangedWidget > &OutResult) const
Actual implementation of FindChildGeometries.
FGeometry FindChildGeometry (const FGeometry &MyGeometry, TSharedRef< SWidget > WidgetToFind) const
Find the geometry of a descendant widget.
virtual TOptional< EMouseCursor::Type > GetCursor () const
The cursor to show when the mouse is hovering over this widget.
TSlateAttributeRef< bool > GetEnabledStateAttribute () const
virtual const FSlateBrush * GetFocusBrush () const
TSlateAttributeRef< bool > GetHoveredAttribute () const
float GetPrepassLayoutScaleMultiplier () const
TSlateAttributeRef< TOptional< FSlateRenderTransform > > GetRenderTransformAttribute () const
TSlateAttributeRef< FVector2D > GetRenderTransformPivotAttribute () const
TSlateAttributeRef< EVisibility > GetVisibilityAttribute () const
void InvalidateChildRemovedFromTree (SWidget &Child)
Called when a child is removed from the tree parent's widget tree either by removing it from a slot.
FORCEINLINE bool IsChildWidgetCulled (const FSlateRect &, const FArrangedWidget &) const
bool IsConstructed () const
Is the widget construction completed (did we called and returned from the Construct() function)
virtual void OnClippingChanged ()
Called when clipping is changed.
void Prepass_ChildLoop (float InLayoutScaleMultiplier, FChildren *MyChildren)
template<typename TargetValueType, typename SourceValueType>
bool SetAttribute (TAttribute< TargetValueType > &TargetValue, const TAttribute< SourceValueType > &SourceValue, EInvalidateWidgetReason BaseInvalidationReason)
Performs the attribute assignment and invalidates the widget minimally based on what actually changed.
void SetDebugInfo (const ANSICHAR *InType, const ANSICHAR *InFile, int32 OnLine, size_t InAllocSize)
Used by Slate to set the runtime debug info about this widget.
void SetHover (TAttribute< bool > InHovered)
Set the hover state.
void SetVolatilePrepass (bool bVolatile)
bool ShouldBeEnabled (bool InParentEnabled) const
Determines if this widget should be enabled.
void SWidgetConstruct (const FSlateBaseNamedArgs &Args)
Construct a SWidget based on initial parameters.
Protected Member Functions inherited from TSharedFromThis< SWidget >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Protected Attributes
URigVMPin * ModelPin
Protected Attributes inherited from SGraphPin
bool bDragAndDropEnabled
TRUE if the pin should allow any drag and drop.
bool bFadeConnections
TRUE if the connections from this pin should be drawn at a lower opacity.
bool bGraphDataInvalid
flag indicating that graph data has been deleted by the user
bool bIsDiffHighlighted
True if this pin is being diffed and it's currently selected in the diff view.
bool bIsMovingLinks
true when we're moving links between pins.
bool bOnlyShowDefaultValue
If we should draw the label on this pin.
bool bShowLabel
If we should draw the label on this pin.
bool bUsePinColorForText
TRUE if the pin should use the Pin's color for the text.
const FSlateBrush * CachedImg_ArrayPin_Connected
const FSlateBrush * CachedImg_ArrayPin_Disconnected
const FSlateBrush * CachedImg_DelegatePin_Connected
const FSlateBrush * CachedImg_DelegatePin_Disconnected
const FSlateBrush * CachedImg_MapPinKey
const FSlateBrush * CachedImg_MapPinValue
const FSlateBrush * CachedImg_Pin_Background
const FSlateBrush * CachedImg_Pin_BackgroundHovered
const FSlateBrush * CachedImg_Pin_Connected
const FSlateBrush * CachedImg_Pin_DiffOutline
const FSlateBrush * CachedImg_Pin_Disconnected
const FSlateBrush * CachedImg_PosePin_Connected
const FSlateBrush * CachedImg_PosePin_Disconnected
const FSlateBrush * CachedImg_RefPin_Connected
const FSlateBrush * CachedImg_RefPin_Disconnected
const FSlateBrush * CachedImg_SetPin
FDeprecateSlateVector2D CachedNodeOffset
Cached offset from owning node to approximate position of culled pins.
const FSlateBrush * Custom_Brush_Connected
const FSlateBrush * Custom_Brush_Disconnected
TWeakPtr< SHorizontalBox > FullPinHorizontalRowWidget
Horizontal box that holds the full detail pin widget, useful for outsiders to inject widgets into the pin.
class UEdGraphPin * GraphPinObj
The GraphPin that this widget represents.
TSet< FEdGraphPinReference > HoverPinSet
Set of pins that are currently being hovered.
TAttribute< bool > IsEditable
Is this pin editable.
TSharedPtr< SWrapBox > LabelAndValue
Label and value.
TWeakPtr< SGraphNode > OwnerNodePtr
The GraphNode that owns this pin.
FLinearColor PinColorModifier
Color modifier for use by the connection drawing policy.
TOptional< FLinearColor > PinDiffColor
If set, this will change the color of the pin's background highlight.
TSharedPtr< SWidget > PinImage
Image of pin.
TWeakPtr< FPinValueInspectorTooltip > ValueInspectorTooltip
Value inspector tooltip while debugging.
TSharedPtr< SWidget > ValueWidget
Value widget for the pin, created with GetDefaultValueWidget()
Protected Attributes inherited from SCompoundWidget
FCompoundWidgetOneChildSlot ChildSlot
The slot that contains this widget's descendants.
Protected Attributes inherited from SWidget
uint8 bCanHaveChildren: 1
Can the widget ever support children?
uint8 bCanSupportFocus: 1
Can the widget ever support keyboard focus.
uint8 bClippingProxy: 1
Some widgets might be a complex hierarchy of child widgets you never see.
uint8 bHasCustomPrepass: 1
uint8 bHasRelativeLayoutScale: 1
uint8 bVolatilityAlwaysInvalidatesPrepass: 1
if this widget should always invalidate the prepass step when volatile
EWidgetClipping Clipping
Set to true if all content of the widget should clip to the bounds of this widget.
FMargin CullingBoundsExtension
Can be used to enlarge the culling bounds of this widget (pre-intersection), this can be useful if you've got children that you know are using rendering transforms to render outside their standard bounds, if that happens it's possible the parent might be culled before the descendant widget is entirely off screen.
EWidgetPixelSnapping PixelSnappingMethod
When set to EPixelSnappingMethod::SnapToPixel, the widget is drawn at the nearest pixel.
float RenderOpacity
The opacity of the widget.
Additional Inherited Members
Static Public Member Functions inherited from FSlateControlledConstruction
static const FSlateWidgetClassData & StaticWidgetClass ()
Static Protected Member Functions inherited from SWidget
static TAttribute< EVisibility > AccessWidgetVisibilityAttribute (const TSharedRef< SWidget > &Widget)
Protected static helper to allow widgets to access the visibility attribute of other widgets directly.
static int32 FindChildUnderMouse (const FArrangedChildren &Children, const FPointerEvent &MouseEvent)
static int32 FindChildUnderPosition (const FArrangedChildren &Children, const UE::Slate::FDeprecateVector2DParameter &ArrangedSpacePosition)
Static Protected Member Functions inherited from TSharedFromThis< SWidget >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
Definition at line 53 of file SRigVMGraphPinEnumPicker.h.
Member Function Documentation
GetDefaultValueWidget()
virtual TSharedRef< SWidget > SRigVMGraphPinEnumPicker::GetDefaultValueWidget () override protected virtual
Build the widget we should put into the 'default value' space, shown when nothing connected.
Reimplemented from SGraphPin.
References GetDefaultValueWidget().
Referenced by GetDefaultValueWidget().
HandleControlEnumChanged()
void SRigVMGraphPinEnumPicker::HandleControlEnumChanged (TSharedPtr< FString > InItem, ESelectInfo::Type InSelectionInfo) protected
References HandleControlEnumChanged().
Referenced by HandleControlEnumChanged().
SLATE_ARGUMENT()
SRigVMGraphPinEnumPicker::SLATE_ARGUMENT (URigVMPin * , ModelPin) const &
References ModelPin.
SLATE_BEGIN_ARGS()
SRigVMGraphPinEnumPicker::SLATE_BEGIN_ARGS (SRigVMGraphPinEnumPicker) inline
Definition at line 56 of file SRigVMGraphPinEnumPicker.h.
Field Documentation
InGraphPinObj
UEdGraphPin* SRigVMGraphPinEnumPicker::InGraphPinObj
Definition at line 61 of file SRigVMGraphPinEnumPicker.h.
ModelPin
URigVMPin* SRigVMGraphPinEnumPicker::ModelPin protected
Definition at line 70 of file SRigVMGraphPinEnumPicker.h.
Referenced by SLATE_ARGUMENT().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/RigVM/Source/RigVMEditor/Public/Widgets/SRigVMGraphPinEnumPicker.h