Unreal Engine 5.6 C++ API: UE::Geometry::FBasePositionSnapSolver3 Class Reference
UE::Geometry::FBasePositionSnapSolver3 Class Reference
FBasePositionSnapSolver3 is a base class for 3D position snapping implementations.
#include "BasePositionSnapSolver3.h"
Data Structures
struct FCustomMetric
FCustomMetric overrides/modifies the default should-snap-happen metric.
struct FSnapTargetCircle
struct FSnapTargetLine
Target line that might be snapped to.
struct FSnapTargetPoint
Target point that might be snapped to.
Public Types
enum class ECustomMetricType { ReplaceValue = 0 , Multiplier = 1 , MinValue = 2 }
ECustomMetricType defines how a FCustomMetric should be interpreted.
Public Member Functions
MODELINGCOMPONENTS_API FBasePositionSnapSolver3 ()
virtual ~FBasePositionSnapSolver3 ()
virtual MODELINGCOMPONENTS_API void AddCircleTarget (const FCircle3d &Circle, int TargetID, int Priority=100)
Add a snap target Circle.
virtual MODELINGCOMPONENTS_API void AddIgnoreTarget (int TargetID)
Add given TargetID to the ignore list, so any points/lines with that ID will not be snapped-to.
virtual MODELINGCOMPONENTS_API void AddLineTarget (const FLine3d &Line, int TargetID, int Priority=100)
Add a snap target line.
virtual MODELINGCOMPONENTS_API void AddPointTarget (const FVector3d &Position, int TargetID, const FCustomMetric &CustomMetric, int Priority=100)
Add a snap target point at the given Position.
virtual MODELINGCOMPONENTS_API void AddPointTarget (const FVector3d &Position, int TargetID, int Priority=100)
Add a snap target point at the given Position.
int GetActiveSnapDistanceID () const
FVector3d GetActiveSnapFromPoint () const
const FLine3d & GetActiveSnapLine () const
int GetActiveSnapTargetID () const
FVector3d GetActiveSnapToPoint () const
bool HaveActiveSnap () const
bool HaveActiveSnapDistance () const
bool HaveActiveSnapLine () const
virtual MODELINGCOMPONENTS_API bool IsIgnored (int TargetID) const
virtual MODELINGCOMPONENTS_API bool RemoveCircleTargetsByID (int TargetID)
Remove any line targets with this TargetID.
virtual MODELINGCOMPONENTS_API void RemoveIgnoreTarget (int TargetID)
Add given TargetID from the ignore list.
virtual MODELINGCOMPONENTS_API bool RemoveLineTargetsByID (int TargetID)
Remove any line targets with this TargetID.
virtual MODELINGCOMPONENTS_API bool RemovePointTargetsByID (int TargetID)
Remove any point targets with this TargetID.
virtual MODELINGCOMPONENTS_API void Reset ()
Discard the set of snap points and lines and clear the active snap.
virtual MODELINGCOMPONENTS_API void ResetActiveSnap ()
Clear the active snap.
Data Fields
bool bEnableStableSnap = true
If true, then we will prefer to keep current snap point over a new one.
TFunction< double(const FVector3d &, const FVector3d &)> SnapMetricFunc
This is the function we use to measure distances between snap points.
double SnapMetricTolerance
Tolerance for snapping, in unit relative to SnapMetricFunc.
double StableSnapImproveThresh = 0.5
How much we have to improve the snap metric to discard the current stable snap.
Static Public Attributes
static constexpr int BaseExternalLineID = 10000
subclasses may have internal TargetID values, so external lines should have IDs larger than this
static constexpr int BaseExternalPointID = 1000
subclasses may have internal TargetID values, so external points should have IDs larger than this
Protected Member Functions
virtual MODELINGCOMPONENTS_API void ClearActiveSnapData ()
MODELINGCOMPONENTS_API const FSnapTargetPoint * FindBestSnapInSet (const TArray< FSnapTargetPoint > &TestTargets, double &MinMetric, int &MinPriority, const TFunction< FVector3d(const FVector3d &)> &GetSnapPointFromFunc)
MODELINGCOMPONENTS_API int32 FindIndexOfBestSnapInSet (const TArray< FSnapTargetPoint > &TestTargets, double &MinMetric, int &MinPriority, const TFunction< FVector3d(const FVector3d &)> &GetSnapPointFromFunc)
virtual MODELINGCOMPONENTS_API void SetActiveSnapData (const FSnapTargetPoint &TargetPoint, const FVector3d &FromPoint, const FVector3d &ToPoint, double Metric)
MODELINGCOMPONENTS_API bool TestSnapTarget (const FSnapTargetPoint &Target, double MinMetric, int MinPriority, const TFunction< FVector3d(const FVector3d &)> &GetSnapPointFromFunc)
Protected Attributes
FVector3d ActiveSnapFromPoint
FSnapTargetPoint ActiveSnapTarget
FVector3d ActiveSnapToPoint
bool bHaveActiveSnap
TSet< int > IgnoreTargets
list of TargetID values to ignore in snap queries
double SnappedPointMetric
TArray< FSnapTargetCircle > TargetCircles
TArray< FSnapTargetLine > TargetLines
TArray< FSnapTargetPoint > TargetPoints
Detailed Description
FBasePositionSnapSolver3 is a base class for 3D position snapping implementations.
It is not usable on its own and the split between this class and the implementations is not incredibly clean. However there is lots of shared functionality that is placed here.
3D Point and Line targets are supported. Targets can also be "ignored".
The actual snap "solve" must be implemented by subclasses, depending on their input data (ray, point, line, etc)
Definition at line 30 of file BasePositionSnapSolver3.h.
Member Enumeration Documentation
ECustomMetricType
enum class UE::Geometry::FBasePositionSnapSolver3::ECustomMetricType strong
ECustomMetricType defines how a FCustomMetric should be interpreted.
Enumerator
ReplaceValue
Multiplier
Use given parameter instead of default metric value.
MinValue
Multiply default metric value by given parameter.
Definition at line 62 of file BasePositionSnapSolver3.h.
Constructor & Destructor Documentation
FBasePositionSnapSolver3()
MODELINGCOMPONENTS_API UE::Geometry::FBasePositionSnapSolver3::FBasePositionSnapSolver3 ()
References UE_API.
~FBasePositionSnapSolver3()
virtual UE::Geometry::FBasePositionSnapSolver3::~FBasePositionSnapSolver3 () inline virtual
Definition at line 55 of file BasePositionSnapSolver3.h.
Member Function Documentation
AddCircleTarget()
virtual MODELINGCOMPONENTS_API void UE::Geometry::FBasePositionSnapSolver3::AddCircleTarget (const FCircle3d & Circle, int TargetID, int Priority = 100) virtual
Add a snap target Circle.
Parameters
TargetID identifier for this target. Can be shared with other targets
Priority importance of this snap target. Lower priority is more important.
References Circle, and UE_API.
AddIgnoreTarget()
virtual MODELINGCOMPONENTS_API void UE::Geometry::FBasePositionSnapSolver3::AddIgnoreTarget (int TargetID) virtual
Add given TargetID to the ignore list, so any points/lines with that ID will not be snapped-to.
References UE_API.
AddLineTarget()
virtual MODELINGCOMPONENTS_API void UE::Geometry::FBasePositionSnapSolver3::AddLineTarget (const FLine3d & Line, int TargetID, int Priority = 100) virtual
Add a snap target line.
Parameters
TargetID identifier for this target. Can be shared with other targets
Priority importance of this snap line. Lower priority is more important.
References Line, and UE_API.
AddPointTarget() [1/2]
virtual MODELINGCOMPONENTS_API void UE::Geometry::FBasePositionSnapSolver3::AddPointTarget (const FVector3d & Position, int TargetID, const FCustomMetric & CustomMetric, int Priority = 100) virtual
Add a snap target point at the given Position.
Parameters
Position snap target point location
TargetID identifier for this target. Can be shared with other targets
CustomMetric Use the given custom metric instead of the default metric
Priority importance of this snap point. Lower priority is more important.
References UE::Geometry::Position, and UE_API.
AddPointTarget() [2/2]
virtual MODELINGCOMPONENTS_API void UE::Geometry::FBasePositionSnapSolver3::AddPointTarget (const FVector3d & Position, int TargetID, int Priority = 100) virtual
Add a snap target point at the given Position.
Parameters
Position snap target point location
TargetID identifier for this target. Can be shared with other targets
Priority importance of this snap point. Lower priority is more important.
References UE::Geometry::Position, and UE_API.
ClearActiveSnapData()
virtual MODELINGCOMPONENTS_API void UE::Geometry::FBasePositionSnapSolver3::ClearActiveSnapData () protected virtual
References UE_API.
FindBestSnapInSet()
MODELINGCOMPONENTS_API const FSnapTargetPoint * UE::Geometry::FBasePositionSnapSolver3::FindBestSnapInSet (const TArray< FSnapTargetPoint > & TestTargets, double & MinMetric, int & MinPriority, const TFunction< FVector3d(const FVector3d &)> & GetSnapPointFromFunc) protected
References UE_API.
FindIndexOfBestSnapInSet()
MODELINGCOMPONENTS_API int32 UE::Geometry::FBasePositionSnapSolver3::FindIndexOfBestSnapInSet (const TArray< FSnapTargetPoint > & TestTargets, double & MinMetric, int & MinPriority, const TFunction< FVector3d(const FVector3d &)> & GetSnapPointFromFunc) protected
References UE_API.
GetActiveSnapDistanceID()
int UE::Geometry::FBasePositionSnapSolver3::GetActiveSnapDistanceID () const inline
Returns
internal snap distance ID (interpretation defined by subclasses)
Definition at line 162 of file BasePositionSnapSolver3.h.
References ActiveSnapTarget.
GetActiveSnapFromPoint()
FVector3d UE::Geometry::FBasePositionSnapSolver3::GetActiveSnapFromPoint () const inline
Returns
the snapped-from point. This may be the original target, a point on a line, after projections, etc. Defined by subclasses.
Definition at line 150 of file BasePositionSnapSolver3.h.
References ActiveSnapFromPoint.
GetActiveSnapLine()
const FLine3d & UE::Geometry::FBasePositionSnapSolver3::GetActiveSnapLine () const inline
Returns
3D line for active snap target
Definition at line 157 of file BasePositionSnapSolver3.h.
References ActiveSnapTarget.
GetActiveSnapTargetID()
int UE::Geometry::FBasePositionSnapSolver3::GetActiveSnapTargetID () const inline
Returns
targetID of original point or line that resulted in the snap
Definition at line 152 of file BasePositionSnapSolver3.h.
References ActiveSnapTarget, and bHaveActiveSnap.
GetActiveSnapToPoint()
FVector3d UE::Geometry::FBasePositionSnapSolver3::GetActiveSnapToPoint () const inline
Returns
the snapped-to point
Definition at line 148 of file BasePositionSnapSolver3.h.
References ActiveSnapToPoint.
HaveActiveSnap()
bool UE::Geometry::FBasePositionSnapSolver3::HaveActiveSnap () const inline
Returns
true if after the last snap solve we have an active snap
Definition at line 146 of file BasePositionSnapSolver3.h.
References bHaveActiveSnap.
Referenced by HaveActiveSnapDistance(), UE::Geometry::FPointPlanarSnapSolver::HaveActiveSnapIntersection(), and HaveActiveSnapLine().
HaveActiveSnapDistance()
bool UE::Geometry::FBasePositionSnapSolver3::HaveActiveSnapDistance () const inline
Returns
true if the active snap target is based on a distance along a line
Definition at line 160 of file BasePositionSnapSolver3.h.
References ActiveSnapTarget, and HaveActiveSnap().
HaveActiveSnapLine()
bool UE::Geometry::FBasePositionSnapSolver3::HaveActiveSnapLine () const inline
Returns
true if the active snap target is a line
Definition at line 155 of file BasePositionSnapSolver3.h.
References ActiveSnapTarget, and HaveActiveSnap().
IsIgnored()
virtual MODELINGCOMPONENTS_API bool UE::Geometry::FBasePositionSnapSolver3::IsIgnored (int TargetID) const virtual
Returns
true if the given TargetID is in the ignore list
References UE_API.
RemoveCircleTargetsByID()
virtual MODELINGCOMPONENTS_API bool UE::Geometry::FBasePositionSnapSolver3::RemoveCircleTargetsByID (int TargetID) virtual
Remove any line targets with this TargetID.
References UE_API.
RemoveIgnoreTarget()
virtual MODELINGCOMPONENTS_API void UE::Geometry::FBasePositionSnapSolver3::RemoveIgnoreTarget (int TargetID) virtual
Add given TargetID from the ignore list.
References UE_API.
RemoveLineTargetsByID()
virtual MODELINGCOMPONENTS_API bool UE::Geometry::FBasePositionSnapSolver3::RemoveLineTargetsByID (int TargetID) virtual
Remove any line targets with this TargetID.
References UE_API.
RemovePointTargetsByID()
virtual MODELINGCOMPONENTS_API bool UE::Geometry::FBasePositionSnapSolver3::RemovePointTargetsByID (int TargetID) virtual
Remove any point targets with this TargetID.
References UE_API.
Reset()
virtual MODELINGCOMPONENTS_API void UE::Geometry::FBasePositionSnapSolver3::Reset () virtual
Discard the set of snap points and lines and clear the active snap.
Reimplemented in UE::Geometry::FPointPlanarSnapSolver.
References UE_API.
ResetActiveSnap()
virtual MODELINGCOMPONENTS_API void UE::Geometry::FBasePositionSnapSolver3::ResetActiveSnap () virtual
Clear the active snap.
References UE_API.
SetActiveSnapData()
virtual MODELINGCOMPONENTS_API void UE::Geometry::FBasePositionSnapSolver3::SetActiveSnapData (const FSnapTargetPoint & TargetPoint, const FVector3d & FromPoint, const FVector3d & ToPoint, double Metric) protected virtual
References UE_API.
TestSnapTarget()
MODELINGCOMPONENTS_API bool UE::Geometry::FBasePositionSnapSolver3::TestSnapTarget (const FSnapTargetPoint & Target, double MinMetric, int MinPriority, const TFunction< FVector3d(const FVector3d &)> & GetSnapPointFromFunc) protected
References Target, and UE_API.
Field Documentation
ActiveSnapFromPoint
FVector3d UE::Geometry::FBasePositionSnapSolver3::ActiveSnapFromPoint protected
Definition at line 220 of file BasePositionSnapSolver3.h.
Referenced by GetActiveSnapFromPoint().
ActiveSnapTarget
FSnapTargetPoint UE::Geometry::FBasePositionSnapSolver3::ActiveSnapTarget protected
Definition at line 219 of file BasePositionSnapSolver3.h.
Referenced by GetActiveSnapDistanceID(), GetActiveSnapLine(), GetActiveSnapTargetID(), HaveActiveSnapDistance(), and HaveActiveSnapLine().
ActiveSnapToPoint
FVector3d UE::Geometry::FBasePositionSnapSolver3::ActiveSnapToPoint protected
Definition at line 221 of file BasePositionSnapSolver3.h.
Referenced by GetActiveSnapToPoint().
BaseExternalLineID
int UE::Geometry::FBasePositionSnapSolver3::BaseExternalLineID = 10000 static constexpr
subclasses may have internal TargetID values, so external lines should have IDs larger than this
Definition at line 50 of file BasePositionSnapSolver3.h.
BaseExternalPointID
int UE::Geometry::FBasePositionSnapSolver3::BaseExternalPointID = 1000 static constexpr
subclasses may have internal TargetID values, so external points should have IDs larger than this
Definition at line 48 of file BasePositionSnapSolver3.h.
bEnableStableSnap
bool UE::Geometry::FBasePositionSnapSolver3::bEnableStableSnap = true
If true, then we will prefer to keep current snap point over a new one.
Definition at line 43 of file BasePositionSnapSolver3.h.
bHaveActiveSnap
bool UE::Geometry::FBasePositionSnapSolver3::bHaveActiveSnap protected
Definition at line 218 of file BasePositionSnapSolver3.h.
Referenced by GetActiveSnapTargetID(), and HaveActiveSnap().
IgnoreTargets
TSet<int> UE::Geometry::FBasePositionSnapSolver3::IgnoreTargets protected
list of TargetID values to ignore in snap queries
Definition at line 213 of file BasePositionSnapSolver3.h.
SnapMetricFunc
TFunction<double(const FVector3d&, const FVector3d&)> UE::Geometry::FBasePositionSnapSolver3::SnapMetricFunc
This is the function we use to measure distances between snap points.
Defaults to Euclidean distance.
Definition at line 38 of file BasePositionSnapSolver3.h.
SnapMetricTolerance
double UE::Geometry::FBasePositionSnapSolver3::SnapMetricTolerance
Tolerance for snapping, in unit relative to SnapMetricFunc.
Definition at line 40 of file BasePositionSnapSolver3.h.
SnappedPointMetric
double UE::Geometry::FBasePositionSnapSolver3::SnappedPointMetric protected
Definition at line 222 of file BasePositionSnapSolver3.h.
StableSnapImproveThresh
double UE::Geometry::FBasePositionSnapSolver3::StableSnapImproveThresh = 0.5
How much we have to improve the snap metric to discard the current stable snap.
Definition at line 45 of file BasePositionSnapSolver3.h.
TargetCircles
TArray<FSnapTargetCircle> UE::Geometry::FBasePositionSnapSolver3::TargetCircles protected
Definition at line 209 of file BasePositionSnapSolver3.h.
TargetLines
TArray<FSnapTargetLine> UE::Geometry::FBasePositionSnapSolver3::TargetLines protected
Definition at line 200 of file BasePositionSnapSolver3.h.
TargetPoints
TArray<FSnapTargetPoint> UE::Geometry::FBasePositionSnapSolver3::TargetPoints protected
Definition at line 189 of file BasePositionSnapSolver3.h.
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/MeshModelingToolset/Source/ModelingComponents/Public/Snapping/BasePositionSnapSolver3.h