Unreal Engine 5.6 C++ API: IPropertyTableColumn Class Reference
IPropertyTableColumn Class Reference abstract
#include "IPropertyTableColumn.h"
Public Member Functions
virtual bool CanSelectCells () const =0
virtual bool CanSortBy () const =0
DECLARE_EVENT_OneParam (IPropertyTableColumn, FFrozenStateChanged, const TSharedRef< IPropertyTableColumn > &)
virtual TSharedRef< class IPropertyTableCell > GetCell (const TSharedRef< class IPropertyTableRow > &Row)=0
virtual TSharedRef< class IDataSource > GetDataSource () const =0
virtual FText GetDisplayName () const =0
virtual FName GetId () const =0
virtual TSharedRef< class FPropertyPath > GetPartialPath () const =0
virtual TSharedPtr< struct FCompareRowByColumnBase > GetPropertySorter (const FProperty *Property, EColumnSortMode::Type SortMode)=0
virtual EPropertyTableColumnSizeMode::Type GetSizeMode () const =0
virtual TSharedRef< class IPropertyTable > GetTable () const =0
virtual float GetWidth () const =0
virtual bool IsFrozen () const =0
virtual bool IsHidden () const =0
virtual FFrozenStateChanged * OnFrozenStateChanged ()=0
virtual void RemoveCellsForRow (const TSharedRef< class IPropertyTableRow > &Row)=0
virtual void SetFrozen (bool IsFrozen)=0
virtual void SetHidden (bool IsHidden)=0
virtual void SetSizeMode (EPropertyTableColumnSizeMode::Type InSizeMode)=0
virtual void SetWidth (float InWidth)=0
virtual void Sort (TArray< TSharedRef< class IPropertyTableRow > > &Rows, const EColumnSortMode::Type PrimarySortMode, const TSharedPtr< IPropertyTableColumn > &SecondarySortColumn, const EColumnSortMode::Type SecondarySortMode)=0
virtual void Tick ()=0
Tick the property column each frame.
Detailed Description
Definition at line 16 of file IPropertyTableColumn.h.
Member Function Documentation
CanSelectCells()
virtual bool IPropertyTableColumn::CanSelectCells () const pure virtual
CanSortBy()
virtual bool IPropertyTableColumn::CanSortBy () const pure virtual
DECLARE_EVENT_OneParam()
IPropertyTableColumn::DECLARE_EVENT_OneParam (IPropertyTableColumn , FFrozenStateChanged , const TSharedRef< IPropertyTableColumn > &)
GetCell()
virtual TSharedRef< class IPropertyTableCell > IPropertyTableColumn::GetCell (const TSharedRef< class IPropertyTableRow > & Row) pure virtual
GetDataSource()
virtual TSharedRef< class IDataSource > IPropertyTableColumn::GetDataSource () const pure virtual
GetDisplayName()
virtual FText IPropertyTableColumn::GetDisplayName () const pure virtual
GetId()
virtual FName IPropertyTableColumn::GetId () const pure virtual
GetPartialPath()
virtual TSharedRef< class FPropertyPath > IPropertyTableColumn::GetPartialPath () const pure virtual
GetPropertySorter()
virtual TSharedPtr< struct FCompareRowByColumnBase > IPropertyTableColumn::GetPropertySorter (const FProperty * Property, EColumnSortMode::Type SortMode) pure virtual
References Property.
GetSizeMode()
virtual EPropertyTableColumnSizeMode::Type IPropertyTableColumn::GetSizeMode () const pure virtual
GetTable()
virtual TSharedRef< class IPropertyTable > IPropertyTableColumn::GetTable () const pure virtual
GetWidth()
virtual float IPropertyTableColumn::GetWidth () const pure virtual
IsFrozen()
virtual bool IPropertyTableColumn::IsFrozen () const pure virtual
Referenced by SetFrozen().
IsHidden()
virtual bool IPropertyTableColumn::IsHidden () const pure virtual
Referenced by SetHidden().
OnFrozenStateChanged()
virtual FFrozenStateChanged * IPropertyTableColumn::OnFrozenStateChanged () pure virtual
RemoveCellsForRow()
virtual void IPropertyTableColumn::RemoveCellsForRow (const TSharedRef< class IPropertyTableRow > & Row) pure virtual
SetFrozen()
virtual void IPropertyTableColumn::SetFrozen (bool IsFrozen) pure virtual
References IsFrozen().
SetHidden()
virtual void IPropertyTableColumn::SetHidden (bool IsHidden) pure virtual
References IsHidden().
SetSizeMode()
virtual void IPropertyTableColumn::SetSizeMode (EPropertyTableColumnSizeMode::Type InSizeMode) pure virtual
SetWidth()
virtual void IPropertyTableColumn::SetWidth (float InWidth) pure virtual
Sort()
virtual void IPropertyTableColumn::Sort (TArray< TSharedRef< class IPropertyTableRow > > & Rows, const EColumnSortMode::Type PrimarySortMode, const TSharedPtr< IPropertyTableColumn > & SecondarySortColumn, const EColumnSortMode::Type SecondarySortMode) pure virtual
Tick()
virtual void IPropertyTableColumn::Tick () pure virtual
Tick the property column each frame.
The documentation for this class was generated from the following file:
Editor/PropertyEditor/Public/IPropertyTableColumn.h