Unreal Engine 5.6 C++ API: Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::FIteratorType Class Reference
Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::FIteratorType Class Reference
#include "RobinHoodHashTable.h"
Public Member Functions
FHashElementId GetElementId () const
bool operator!= (const FIteratorType &Rhs) const
ElementType & operator* () const
FIteratorType & operator++ ()
bool operator== (const FIteratorType &Rhs) const
Private Member Functions
FIteratorType (FData &InData, bool bIsStartIterator)
Private Attributes
FData & Data
FData::FIteratorState State
Friends
template<typename, typename, typename, typename>
class TRobinHoodHashTable
Detailed Description
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator>
class Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::FIteratorType
Definition at line 726 of file RobinHoodHashTable.h.
Constructor & Destructor Documentation
FIteratorType()
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::FIteratorType::FIteratorType (FData & InData, bool bIsStartIterator) inline private
Definition at line 734 of file RobinHoodHashTable.h.
References Data, and State.
Referenced by operator!=(), operator++(), and operator==().
Member Function Documentation
GetElementId()
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> FHashElementId Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::FIteratorType::GetElementId () const inline
Definition at line 768 of file RobinHoodHashTable.h.
References State.
operator!=()
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> bool Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::FIteratorType::operator!= (const FIteratorType & Rhs) const inline
Definition at line 752 of file RobinHoodHashTable.h.
References FIteratorType(), Data, and State.
operator*()
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> ElementType & Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::FIteratorType::operator* () const inline
Definition at line 757 of file RobinHoodHashTable.h.
References Data, and State.
operator++()
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> FIteratorType & Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::FIteratorType::operator++ () inline
Definition at line 762 of file RobinHoodHashTable.h.
References FIteratorType(), Data, and State.
operator==()
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> bool Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::FIteratorType::operator== (const FIteratorType & Rhs) const inline
Definition at line 747 of file RobinHoodHashTable.h.
References FIteratorType(), Data, and State.
Friends And Related Symbol Documentation
TRobinHoodHashTable
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> template<typename, typename, typename, typename> friend class TRobinHoodHashTable friend
Definition at line 732 of file RobinHoodHashTable.h.
References TRobinHoodHashTable.
Referenced by TRobinHoodHashTable.
Field Documentation
Data
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> FData& Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::FIteratorType::Data private
Definition at line 729 of file RobinHoodHashTable.h.
Referenced by FIteratorType(), operator!=(), operator*(), operator++(), and operator==().
State
template<typename KeyType, typename ValueType, typename Hasher, typename HashMapAllocator> FData::FIteratorState Experimental::RobinHoodHashTable_Private::TRobinHoodHashTable< KeyType, ValueType, Hasher, HashMapAllocator >::FIteratorType::State private
Definition at line 728 of file RobinHoodHashTable.h.
Referenced by FIteratorType(), GetElementId(), operator!=(), operator*(), operator++(), and operator==().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Experimental/Containers/RobinHoodHashTable.h