Unreal Engine 5.6 C++ API: IAssetEditorInstance Class Reference
IAssetEditorInstance Class Reference abstract
This class keeps track of a currently open asset editor; allowing it to be brought into focus, closed, etc..., without concern for how the editor was implemented.
#include "AssetEditorSubsystem.h"
Public Member Functions
virtual bool CloseWindow (EAssetEditorCloseReason InCloseReason)
virtual void FocusWindow (UObject *ObjectToFocusOn=nullptr)=0
virtual TSharedPtr< class FTabManager > GetAssociatedTabManager ()=0
virtual FName GetEditingAssetTypeName () const
virtual FName GetEditorName () const =0
virtual double GetLastActivationTime ()=0
virtual EAssetOpenMethod GetOpenMethod () const
virtual bool IncludeAssetInRestoreOpenAssetsPrompt (UObject *Asset) const
virtual void InvokeTab (const struct FTabId &TabId)=0
virtual bool IsPrimaryEditor () const =0
virtual void RemoveEditingAsset (UObject *Asset)=0
UE_DEPRECATED (5.0, "Toolbar tab no longer exists and tab ID will return None; do not add it to layouts") virtual FName GetToolbarTabId() const
UE_DEPRECATED (5.3, "Use CloseWindow that takes in an EAssetEditorCloseReason instead") virtual bool CloseWindow()
UE_DEPRECATED (5.4, "Use the override that takes in an UObject instead") virtual bool IncludeAssetInRestoreOpenAssetsPrompt() const
If false, the asset being edited will not be included in reopen assets prompt on restart.
Detailed Description
This class keeps track of a currently open asset editor; allowing it to be brought into focus, closed, etc..., without concern for how the editor was implemented.
Definition at line 55 of file AssetEditorSubsystem.h.
Member Function Documentation
CloseWindow()
virtual bool IAssetEditorInstance::CloseWindow (EAssetEditorCloseReason InCloseReason) inline virtual
Reimplemented in FAssetEditorToolkit, and SMiniCurveEditor.
Definition at line 65 of file AssetEditorSubsystem.h.
References CloseWindow(), PRAGMA_DISABLE_DEPRECATION_WARNINGS, and PRAGMA_ENABLE_DEPRECATION_WARNINGS.
Referenced by CloseWindow(), and UE_DEPRECATED().
FocusWindow()
virtual void IAssetEditorInstance::FocusWindow (UObject * ObjectToFocusOn = nullptr) pure virtual
Implemented in FAssetEditorToolkit, and SMiniCurveEditor.
GetAssociatedTabManager()
virtual TSharedPtr< class FTabManager > IAssetEditorInstance::GetAssociatedTabManager () pure virtual
Implemented in FAssetEditorToolkit, and SMiniCurveEditor.
GetEditingAssetTypeName()
virtual FName IAssetEditorInstance::GetEditingAssetTypeName () const inline virtual
Reimplemented in FAssetEditorToolkit, and FSimpleAssetEditor.
Definition at line 87 of file AssetEditorSubsystem.h.
GetEditorName()
virtual FName IAssetEditorInstance::GetEditorName () const pure virtual
Implemented in FAssetEditorToolkit, and SMiniCurveEditor.
GetLastActivationTime()
virtual double IAssetEditorInstance::GetLastActivationTime () pure virtual
Implemented in FAssetEditorToolkit, and SMiniCurveEditor.
GetOpenMethod()
virtual EAssetOpenMethod IAssetEditorInstance::GetOpenMethod () const inline virtual
Reimplemented in FAssetEditorToolkit.
Definition at line 91 of file AssetEditorSubsystem.h.
IncludeAssetInRestoreOpenAssetsPrompt()
virtual bool IAssetEditorInstance::IncludeAssetInRestoreOpenAssetsPrompt (UObject * Asset) const inline virtual
Definition at line 76 of file AssetEditorSubsystem.h.
References Asset, IncludeAssetInRestoreOpenAssetsPrompt(), PRAGMA_DISABLE_DEPRECATION_WARNINGS, and PRAGMA_ENABLE_DEPRECATION_WARNINGS.
Referenced by IncludeAssetInRestoreOpenAssetsPrompt(), and UE_DEPRECATED().
InvokeTab()
virtual void IAssetEditorInstance::InvokeTab (const struct FTabId & TabId) pure virtual
Implemented in SMiniCurveEditor.
IsPrimaryEditor()
virtual bool IAssetEditorInstance::IsPrimaryEditor () const pure virtual
Implemented in FAssetEditorToolkit, FSimpleAssetEditor, and SMiniCurveEditor.
RemoveEditingAsset()
virtual void IAssetEditorInstance::RemoveEditingAsset (UObject * Asset) pure virtual
Implemented in FAssetEditorToolkit, and SMiniCurveEditor.
References Asset.
UE_DEPRECATED() [1/3]
IAssetEditorInstance::UE_DEPRECATED (5. 0, "Toolbar tab no longer exists and tab ID will return None; do not add it to layouts") const inline
Definition at line 85 of file AssetEditorSubsystem.h.
UE_DEPRECATED() [2/3]
IAssetEditorInstance::UE_DEPRECATED (5. 3, "Use CloseWindow that takes in an EAssetEditorCloseReason instead") inline
Definition at line 62 of file AssetEditorSubsystem.h.
References CloseWindow().
UE_DEPRECATED() [3/3]
IAssetEditorInstance::UE_DEPRECATED (5. 4, "Use the override that takes in an UObject instead") const inline
If false, the asset being edited will not be included in reopen assets prompt on restart.
Definition at line 73 of file AssetEditorSubsystem.h.
References IncludeAssetInRestoreOpenAssetsPrompt().
The documentation for this class was generated from the following file:
Editor/UnrealEd/Public/Subsystems/AssetEditorSubsystem.h