Unreal Engine 5.6 C++ API: FPackageReloadedEvent Class Reference
FPackageReloadedEvent Class Reference
Delegate payload for FOnPackageReloaded.
#include "PackageReload.h"
Public Member Functions
FPackageReloadedEvent (const UPackage *InOldPackage, const UPackage *InNewPackage, TMap< UObject *, UObject * > InRepointedObjects)
FORCEINLINE void AddObjectReferencer (UObject *InObject)
Add a referencing object for any of the objects that were replaced by the package reload.
void AddReferencedObjects (FReferenceCollector &Collector)
FORCEINLINE const UPackage * GetNewPackage () const
Get the new package pointer (the package that replaced the original one).
FORCEINLINE const TArray< TWeakObjectPtr< UObject > > & GetObjectReferencers () const
Get the set of objects that were referencing any of the objects that were replaced by the package reload.
FORCEINLINE const UPackage * GetOldPackage () const
Get the old package pointer (the original package that was replaced).
template<typename InObjectType, typename OutObjectType>
FORCEINLINE bool GetRepointedObject (InObjectType *InObject, OutObjectType *&OutRepointedObject) const
Given an object pointer, check to see if it needs to be repointed to an object in the new package, and populate OutRepointedObject if needed.
FORCEINLINE const TMap< UObject *, UObject * > & GetRepointedObjects () const
Get the raw map of repointed objects.
template<typename ObjectType>
FORCEINLINE bool RepointObject (ObjectType *&Object) const
Given an object pointer, check to see if it needs to be repointed to an object in the new package, and update it if needed.
Private Member Functions
bool GetRepointedObjectInternal (const UObject *InObject, const UObject *&OutRepointedObject) const
Private Attributes
const UPackage * NewPackage
TArray< TWeakObjectPtr< UObject > > ObjectReferencers
const UPackage * OldPackage
TMap< TObjectPtr< UObject >, TObjectPtr< UObject > > RepointedObjects
Detailed Description
Delegate payload for FOnPackageReloaded.
Definition at line 66 of file PackageReload.h.
Constructor & Destructor Documentation
FPackageReloadedEvent()
FPackageReloadedEvent::FPackageReloadedEvent (const UPackage * InOldPackage, const UPackage * InNewPackage, TMap< UObject *, UObject * > InRepointedObjects) inline
Definition at line 69 of file PackageReload.h.
References MoveTemp(), NewPackage, ObjectPtrWrap(), ObjectReferencers, OldPackage, and RepointedObjects.
Member Function Documentation
AddObjectReferencer()
FORCEINLINE void FPackageReloadedEvent::AddObjectReferencer (UObject * InObject) inline
Add a referencing object for any of the objects that were replaced by the package reload.
Definition at line 135 of file PackageReload.h.
References FORCEINLINE, and ObjectReferencers.
AddReferencedObjects()
void FPackageReloadedEvent::AddReferencedObjects (FReferenceCollector & Collector) inline
Definition at line 140 of file PackageReload.h.
References RepointedObjects.
GetNewPackage()
FORCEINLINE const UPackage * FPackageReloadedEvent::GetNewPackage () const inline
Get the new package pointer (the package that replaced the original one).
Definition at line 88 of file PackageReload.h.
References FORCEINLINE, and NewPackage.
GetObjectReferencers()
FORCEINLINE const TArray< TWeakObjectPtr< UObject > > & FPackageReloadedEvent::GetObjectReferencers () const inline
Get the set of objects that were referencing any of the objects that were replaced by the package reload.
Note
Beware that object referencers may become null as the result of other operations that happen during reloading (such as recompiling Blueprints).
Definition at line 127 of file PackageReload.h.
References FORCEINLINE, and ObjectReferencers.
GetOldPackage()
FORCEINLINE const UPackage * FPackageReloadedEvent::GetOldPackage () const inline
Get the old package pointer (the original package that was replaced).
Definition at line 80 of file PackageReload.h.
References FORCEINLINE, and OldPackage.
GetRepointedObject()
template<typename InObjectType, typename OutObjectType> FORCEINLINE bool FPackageReloadedEvent::GetRepointedObject (InObjectType * InObject, OutObjectType *& OutRepointedObject) const inline
Given an object pointer, check to see if it needs to be repointed to an object in the new package, and populate OutRepointedObject if needed.
Returns
true if the object can be repointed, false otherwise.
Definition at line 106 of file PackageReload.h.
References FORCEINLINE, GetRepointedObjectInternal(), and UE::Core::Private::PointerIsConvertibleFromTo::TImpl< From, To, NoCVFrom, NoCVTo >::Value.
Referenced by FCurveOwnerInterface::RepointCurveOwnerAsset().
GetRepointedObjectInternal()
bool FPackageReloadedEvent::GetRepointedObjectInternal (const UObject * InObject, const UObject *& OutRepointedObject) const inline private
Definition at line 146 of file PackageReload.h.
References RepointedObjects.
Referenced by GetRepointedObject(), and RepointObject().
GetRepointedObjects()
FORCEINLINE const TMap< UObject *, UObject * > & FPackageReloadedEvent::GetRepointedObjects () const inline
Get the raw map of repointed objects.
Definition at line 96 of file PackageReload.h.
References FORCEINLINE, ObjectPtrDecay(), and RepointedObjects.
RepointObject()
template<typename ObjectType> FORCEINLINE bool FPackageReloadedEvent::RepointObject (ObjectType *& Object) const inline
Given an object pointer, check to see if it needs to be repointed to an object in the new package, and update it if needed.
Returns
true if the object was repointed, false otherwise.
Definition at line 117 of file PackageReload.h.
References FORCEINLINE, GetRepointedObjectInternal(), Object, and UE::Core::Private::PointerIsConvertibleFromTo::TImpl< From, To, NoCVFrom, NoCVTo >::Value.
Field Documentation
NewPackage
const UPackage* FPackageReloadedEvent::NewPackage private
Definition at line 157 of file PackageReload.h.
Referenced by FPackageReloadedEvent(), and GetNewPackage().
ObjectReferencers
TArray<TWeakObjectPtr<UObject> > FPackageReloadedEvent::ObjectReferencers private
Definition at line 159 of file PackageReload.h.
Referenced by FPackageReloadedEvent(), AddObjectReferencer(), and GetObjectReferencers().
OldPackage
const UPackage* FPackageReloadedEvent::OldPackage private
Definition at line 156 of file PackageReload.h.
Referenced by FPackageReloadedEvent(), and GetOldPackage().
RepointedObjects
TMap<TObjectPtr<UObject>, TObjectPtr<UObject> > FPackageReloadedEvent::RepointedObjects private
Definition at line 158 of file PackageReload.h.
Referenced by FPackageReloadedEvent(), AddReferencedObjects(), GetRepointedObjectInternal(), and GetRepointedObjects().
The documentation for this class was generated from the following file:
Runtime/CoreUObject/Public/UObject/PackageReload.h