Unreal Engine 5.6 C++ API: TAttribute< ObjectType > Class Template Reference
TAttribute< ObjectType > Class Template Reference
Attribute object.
#include "Attribute.h"
Public Member Functions
TAttribute ()
Default constructor.
template<typename OtherType>
TAttribute (const OtherType &InInitialValue)
Construct implicitly from an initial value.
TAttribute (ObjectType &&InInitialValue)
Construct implicitly from moving an initial value.
template<class SourceType>
TAttribute (SourceType *InUserObject, typename FGetter::template TConstMethodPtr< SourceType > InMethodPtr)
Constructs by binding an arbitrary function that will be called to generate this attribute's value on demand.
template<class SourceType>
TAttribute (TSharedRef< SourceType > InUserObject, typename FGetter::template TConstMethodPtr< SourceType > InMethodPtr)
Constructs by binding an arbitrary function that will be called to generate this attribute's value on demand.
void Bind (const FGetter &InGetter)
Binds an arbitrary function that will be called to generate this attribute's value on demand.
void Bind (FGetter &&InGetter)
Binds an arbitrary function that will be called to generate this attribute's value on demand.
template<class SourceType>
void Bind (SourceType *InUserObject, typename FGetter::template TConstMethodPtr< SourceType > InMethodPtr)
Binds an arbitrary function that will be called to generate this attribute's value on demand.
template<class SourceType>
void Bind (TSharedRef< SourceType > InUserObject, typename FGetter::template TConstMethodPtr< SourceType > InMethodPtr)
Binds an arbitrary function that will be called to generate this attribute's value on demand.
template<typename LambdaType, typename... PayloadTypes>
void BindLambda (LambdaType &&InCallable, PayloadTypes &&... InputPayload)
Static: Binds a C++ lambda delegate technically this works for any functor types, but lambdas are the primary use case.
template<class SourceType>
void BindRaw (SourceType *InUserObject, typename FGetter::template TConstMethodPtr< SourceType > InMethodPtr)
Binds an arbitrary function that will be called to generate this attribute's value on demand.
template<typename UserClass, ESPMode Mode, typename LambdaType, typename... PayloadTypes>
void BindSPLambda (const TSharedRef< UserClass, Mode > &InUserObjectRef, LambdaType &&InCallable, PayloadTypes &&... InputPayload)
Static: Binds a weak shared pointer C++ lambda delegate technically this works for any functor types, but lambdas are the primary use case.
template<typename UserClass, typename LambdaType, typename... PayloadTypes>
void BindSPLambda (const UserClass *InUserObject, LambdaType &&InCallable, PayloadTypes &&... InputPayload)
template<typename... VarTypes>
void BindStatic (TIdentity_T< typename FGetter::template TFuncPtr< VarTypes... > > InFuncPtr, VarTypes... Vars)
Binds an arbitrary function that will be called to generate this attribute's value on demand.
template<class SourceType>
void BindUFunction (SourceType *InUserObject, const FName &InFunctionName)
Binds an arbitrary function that will be called to generate this attribute's value on demand.
template<class SourceType>
void BindUObject (SourceType *InUserObject, typename FGetter::template TConstMethodPtr< SourceType > InMethodPtr)
Binds an arbitrary function that will be called to generate this attribute's value on demand.
template<typename UserClass, typename LambdaType, typename... PayloadTypes>
void BindWeakLambda (UserClass *InUserObject, LambdaType &&InCallable, PayloadTypes &&... InputPayload)
Static: Binds a weak object C++ lambda delegate technically this works for any functor types, but lambdas are the primary use case.
DECLARE_DELEGATE_RetVal (ObjectType, FGetter)
Attribute 'getter' delegate.
const ObjectType & Get () const
Gets the attribute's current value.
const ObjectType & Get (const ObjectType &DefaultValue) const
Gets the attribute's current value.
const FGetter & GetBinding () const
Gets the attribute's 'getter' which can be bound or unbound.
bool IdenticalTo (const TAttribute &InOther) const
Is this attribute identical to another TAttribute.
bool IsBound () const
Checks to see if this attribute has a 'getter' function bound.
bool IsSet () const
Was this TAttribute ever assigned?
template<typename OtherType>
void Set (const OtherType &InNewValue)
Sets the attribute's value.
void Set (ObjectType &&InNewValue)
Sets the attribute's value.
TVariant< ObjectType, FGetter > Steal ()
Move the attribute's 'getter' or the attribute's Value and reset the attribute.
Static Public Member Functions
static TAttribute Create (const FGetter &InGetter)
Static: Creates an attribute that's pre-bound to the specified 'getter' delegate.
static TAttribute Create (FGetter &&InGetter)
Static: Creates an attribute that's pre-bound to the specified 'getter' delegate.
template<class SourceType>
static TAttribute< ObjectType > Create (SourceType *InUserObject, const FName &InFunctionName)
Creates an attribute by binding an arbitrary function that will be called to generate this attribute's value on demand.
static FORCEINLINE TAttribute< ObjectType > Create (TFunction< ObjectType(void)> &&InLambda)
template<typename LambdaType, typename... PayloadTypes>
static FORCEINLINE TAttribute CreateLambda (LambdaType &&InCallable, PayloadTypes &&... InputPayload)
Helper function for creating TAttributes from a lambda TAttribute<float> FloatAttribute = TAttribute<float>::CreateLambda([]{ return 10.f; });.
template<typename SourceType, typename SourceTypeOrBase, typename... PayloadTypes>
static FORCEINLINE TAttribute CreateRaw (const SourceType *InObject, ObjectType(SourceTypeOrBase::*InMethod)(PayloadTypes...) const, typename TDecay< PayloadTypes >::Type... InputPayload)
Helper function for creating TAttributes from a const member function pointer, accessed through a raw pointer.
template<typename SourceType, typename SourceTypeOrBase, typename... PayloadTypes>
static FORCEINLINE TAttribute CreateSP (const SourceType *InObject, ObjectType(SourceTypeOrBase::*InMethod)(PayloadTypes...) const, typename TDecay< PayloadTypes >::Type... InputPayload)
Helper function for creating TAttributes from a const member function pointer, accessed through a weak pointer to the shared object.
template<typename UserClass, ESPMode Mode, typename LambdaType, typename... PayloadTypes>
static FORCEINLINE TAttribute CreateSPLambda (const TSharedRef< UserClass, Mode > &InUserObjectRef, LambdaType &&InCallable, PayloadTypes &&... InputPayload)
Helper function for creating TAttributes from a weak shared pointer C++ lambda delegate.
template<typename UserClass, typename LambdaType, typename... PayloadTypes>
static FORCEINLINE TAttribute CreateSPLambda (UserClass *InUserObject, LambdaType &&InCallable, PayloadTypes &&... InputPayload)
template<typename FuncPtrType, typename... VarTypes>
static TAttribute CreateStatic (FuncPtrType &&InFuncPtr, VarTypes... Vars)
Creates an attribute by binding an arbitrary function that will be called to generate this attribute's value on demand.
template<typename UserClass, typename LambdaType, typename... PayloadTypes>
static FORCEINLINE TAttribute CreateWeakLambda (UserClass *InUserObject, LambdaType &&InCallable, PayloadTypes &&... InputPayload)
Helper function for creating TAttributes from a weak object pointer C++ lambda delegate.
Private Member Functions
TAttribute (const FGetter &InGetter, bool bExplicitConstructor)
Special explicit constructor for TAttribute::Create()
TAttribute (FGetter &&InGetter, bool bExplicitConstructor)
Special explicit constructor for TAttribute::Create()
Private Attributes
bool bIsSet
true when this attribute was explicitly set by a consumer, false when the attribute's value is set to the default
FGetter Getter
Bound member function for this attribute (may be NULL if no function is bound.) When set, all attempts to read the attribute's value will instead call this delegate to generate the value.
ObjectType Value
Current value.
Friends
template<class OtherType>
class TAttribute
Detailed Description
template<typename ObjectType>
class TAttribute< ObjectType >
Attribute object.
Definition at line 16 of file Attribute.h.
Constructor & Destructor Documentation
TAttribute() [1/7]
template<typename ObjectType> TAttribute< ObjectType >::TAttribute () inline
Default constructor.
Definition at line 32 of file Attribute.h.
References bIsSet, Getter, and Value.
TAttribute() [2/7]
template<typename ObjectType> template<typename OtherType> TAttribute< ObjectType >::TAttribute (const OtherType & InInitialValue) inline
Construct implicitly from an initial value.
Parameters
InInitialValue The value for this attribute
Definition at line 45 of file Attribute.h.
References bIsSet, Getter, and Value.
TAttribute() [3/7]
template<typename ObjectType> TAttribute< ObjectType >::TAttribute (ObjectType && InInitialValue) inline
Construct implicitly from moving an initial value.
Parameters
InInitialValue
Definition at line 57 of file Attribute.h.
References bIsSet, Getter, MoveTemp(), and Value.
TAttribute() [4/7]
template<typename ObjectType> template<class SourceType> TAttribute< ObjectType >::TAttribute (TSharedRef< SourceType > InUserObject, typename FGetter::template TConstMethodPtr< SourceType > InMethodPtr) inline
Constructs by binding an arbitrary function that will be called to generate this attribute's value on demand.
After binding, the attribute will no longer have a value that can be accessed directly, and instead the bound function will always be called to generate the value.
Parameters
InUserObject Shared Pointer to the instance of the class that contains the member function you want to bind. The attribute will only retain a weak pointer to this class.
InMethodPtr Member function to bind. The function's structure (return value, arguments, etc) must match IBoundAttributeDelegate's definition.
Definition at line 73 of file Attribute.h.
References bIsSet, CreateSP(), Getter, and Value.
TAttribute() [5/7]
template<typename ObjectType> template<class SourceType> TAttribute< ObjectType >::TAttribute (SourceType * InUserObject, typename FGetter::template TConstMethodPtr< SourceType > InMethodPtr) inline
Constructs by binding an arbitrary function that will be called to generate this attribute's value on demand.
After binding, the attribute will no longer have a value that can be accessed directly, and instead the bound function will always be called to generate the value.
Parameters
InUserObject Shared Pointer to the instance of the class that contains the member function you want to bind. The attribute will only retain a weak pointer to this class.
InMethodPtr Member function to bind. The function's structure (return value, arguments, etc) must match IBoundAttributeDelegate's definition.
Definition at line 89 of file Attribute.h.
References bIsSet, CreateSP(), Getter, and Value.
TAttribute() [6/7]
template<typename ObjectType> TAttribute< ObjectType >::TAttribute (const FGetter & InGetter, bool bExplicitConstructor) inline private
Special explicit constructor for TAttribute::Create()
Definition at line 482 of file Attribute.h.
References bIsSet, Getter, and Value.
TAttribute() [7/7]
template<typename ObjectType> TAttribute< ObjectType >::TAttribute (FGetter && InGetter, bool bExplicitConstructor) inline private
Special explicit constructor for TAttribute::Create()
Definition at line 489 of file Attribute.h.
References bIsSet, Getter, MoveTemp(), and Value.
Member Function Documentation
Bind() [1/4]
template<typename ObjectType> void TAttribute< ObjectType >::Bind (const FGetter & InGetter) inline
Binds an arbitrary function that will be called to generate this attribute's value on demand.
After binding, the attribute will no longer have a value that can be accessed directly, and instead the bound function will always be called to generate the value.
Parameters
InGetter The delegate object with your function binding
Definition at line 274 of file Attribute.h.
References bIsSet, and Getter.
Referenced by SMultiColumnTableRow< ItemType >::GenerateColumns().
Bind() [2/4]
template<typename ObjectType> void TAttribute< ObjectType >::Bind (FGetter && InGetter) inline
Binds an arbitrary function that will be called to generate this attribute's value on demand.
After binding, the attribute will no longer have a value that can be accessed directly, and instead the bound function will always be called to generate the value.
Parameters
InGetter The delegate object with your function binding
Definition at line 288 of file Attribute.h.
References bIsSet, Getter, and MoveTemp().
Bind() [3/4]
template<typename ObjectType> template<class SourceType> void TAttribute< ObjectType >::Bind (SourceType * InUserObject, typename FGetter::template TConstMethodPtr< SourceType > InMethodPtr) inline
Binds an arbitrary function that will be called to generate this attribute's value on demand.
After binding, the attribute will no longer have a value that can be accessed directly, and instead the bound function will always be called to generate the value.
Parameters
InUserObject Shared Pointer to the instance of the class that contains the member function you want to bind. The attribute will only retain a weak pointer to this class.
InMethodPtr Member function to bind. The function's structure (return value, arguments, etc) must match IBoundAttributeDelegate's definition.
Definition at line 347 of file Attribute.h.
References bIsSet, and Getter.
Bind() [4/4]
template<typename ObjectType> template<class SourceType> void TAttribute< ObjectType >::Bind (TSharedRef< SourceType > InUserObject, typename FGetter::template TConstMethodPtr< SourceType > InMethodPtr) inline
Binds an arbitrary function that will be called to generate this attribute's value on demand.
After binding, the attribute will no longer have a value that can be accessed directly, and instead the bound function will always be called to generate the value.
Parameters
InUserObject Shared Pointer to the instance of the class that contains the member function you want to bind. The attribute will only retain a weak pointer to this class.
InMethodPtr Member function to bind. The function's structure (return value, arguments, etc) must match IBoundAttributeDelegate's definition.
Definition at line 332 of file Attribute.h.
References bIsSet, and Getter.
BindLambda()
template<typename ObjectType> template<typename LambdaType, typename... PayloadTypes> void TAttribute< ObjectType >::BindLambda (LambdaType && InCallable, PayloadTypes &&... InputPayload) inline
Static: Binds a C++ lambda delegate technically this works for any functor types, but lambdas are the primary use case.
Definition at line 388 of file Attribute.h.
References bIsSet, Forward(), and Getter.
BindRaw()
template<typename ObjectType> template<class SourceType> void TAttribute< ObjectType >::BindRaw (SourceType * InUserObject, typename FGetter::template TConstMethodPtr< SourceType > InMethodPtr) inline
Binds an arbitrary function that will be called to generate this attribute's value on demand.
After binding, the attribute will no longer have a value that can be accessed directly, and instead the bound function will always be called to generate the value.
Parameters
InUserObject Instance of the class that contains the member function you want to bind.
InMethodPtr Member function to bind. The function's structure (return value, arguments, etc) must match IBoundAttributeDelegate's definition.
Definition at line 317 of file Attribute.h.
References bIsSet, and Getter.
Referenced by SMultiColumnTableRow< ItemType >::GenerateColumns().
BindSPLambda() [1/2]
template<typename ObjectType> template<typename UserClass, ESPMode Mode, typename LambdaType, typename... PayloadTypes> void TAttribute< ObjectType >::BindSPLambda (const TSharedRef< UserClass, Mode > & InUserObjectRef, LambdaType && InCallable, PayloadTypes &&... InputPayload) inline
Static: Binds a weak shared pointer C++ lambda delegate technically this works for any functor types, but lambdas are the primary use case.
Definition at line 399 of file Attribute.h.
References bIsSet, Forward(), and Getter.
BindSPLambda() [2/2]
template<typename ObjectType> template<typename UserClass, typename LambdaType, typename... PayloadTypes> void TAttribute< ObjectType >::BindSPLambda (const UserClass * InUserObject, LambdaType && InCallable, PayloadTypes &&... InputPayload) inline
Definition at line 405 of file Attribute.h.
References bIsSet, Forward(), and Getter.
BindStatic()
template<typename ObjectType> template<typename... VarTypes> void TAttribute< ObjectType >::BindStatic (TIdentity_T< typename FGetter::template TFuncPtr< VarTypes... > > InFuncPtr, VarTypes... Vars) inline
Binds an arbitrary function that will be called to generate this attribute's value on demand.
After binding, the attribute will no longer have a value that can be accessed directly, and instead the bound function will always be called to generate the value.
Parameters
InFuncPtr Function to bind. The function's structure (return value, arguments, etc) must match IBoundAttributeDelegate's definition.
Definition at line 302 of file Attribute.h.
References bIsSet, and Getter.
BindUFunction()
template<typename ObjectType> template<class SourceType> void TAttribute< ObjectType >::BindUFunction (SourceType * InUserObject, const FName & InFunctionName) inline
Binds an arbitrary function that will be called to generate this attribute's value on demand.
After binding, the attribute will no longer have a value that can be accessed directly, and instead the bound function will always be called to generate the value.
Parameters
InUserObject Instance of the class that contains the member function you want to bind.
InFunctionName Member function name to bind.
Definition at line 377 of file Attribute.h.
References bIsSet, and Getter.
Referenced by Create().
BindUObject()
template<typename ObjectType> template<class SourceType> void TAttribute< ObjectType >::BindUObject (SourceType * InUserObject, typename FGetter::template TConstMethodPtr< SourceType > InMethodPtr) inline
Binds an arbitrary function that will be called to generate this attribute's value on demand.
After binding, the attribute will no longer have a value that can be accessed directly, and instead the bound function will always be called to generate the value.
Parameters
InUserObject Instance of the class that contains the member function you want to bind.
InMethodPtr Member function to bind. The function's structure (return value, arguments, etc) must match IBoundAttributeDelegate's definition.
Definition at line 362 of file Attribute.h.
References bIsSet, and Getter.
BindWeakLambda()
template<typename ObjectType> template<typename UserClass, typename LambdaType, typename... PayloadTypes> void TAttribute< ObjectType >::BindWeakLambda (UserClass * InUserObject, LambdaType && InCallable, PayloadTypes &&... InputPayload) inline
Static: Binds a weak object C++ lambda delegate technically this works for any functor types, but lambdas are the primary use case.
Definition at line 416 of file Attribute.h.
References bIsSet, Forward(), and Getter.
Create() [1/4]
template<typename ObjectType> TAttribute TAttribute< ObjectType >::Create (const FGetter & InGetter) inline static nodiscard
Static: Creates an attribute that's pre-bound to the specified 'getter' delegate.
Parameters
InGetter Delegate to bind
Definition at line 101 of file Attribute.h.
References TAttribute.
Referenced by FRigVMGraphEditorSummoner::ConstructTabNameForObject(), MakeAttributeLambda(), MakeAttributeRaw(), MakeAttributeSP(), MakeAttributeSP(), MakeAttributeSPLambda(), MakeAttributeSPLambda(), MakeAttributeUObject(), and MakeAttributeWeakLambda().
Create() [2/4]
template<typename ObjectType> TAttribute TAttribute< ObjectType >::Create (FGetter && InGetter) inline static nodiscard
Static: Creates an attribute that's pre-bound to the specified 'getter' delegate.
Parameters
InGetter Delegate to bind
Definition at line 112 of file Attribute.h.
References TAttribute, and MoveTemp().
Create() [3/4]
template<typename ObjectType> template<class SourceType> TAttribute< ObjectType > TAttribute< ObjectType >::Create (SourceType * InUserObject, const FName & InFunctionName) inline static nodiscard
Creates an attribute by binding an arbitrary function that will be called to generate this attribute's value on demand.
After binding, the attribute will no longer have a value that can be accessed directly, and instead the bound function will always be called to generate the value.
Parameters
InUserObject Instance of the class that contains the member function you want to bind.
InFunctionName Member function name to bind.
Definition at line 192 of file Attribute.h.
References TAttribute, and BindUFunction().
Create() [4/4]
template<typename ObjectType> FORCEINLINE TAttribute< ObjectType > TAttribute< ObjectType >::Create (TFunction< ObjectType(void)> && InLambda) inline static nodiscard
Definition at line 199 of file Attribute.h.
References TAttribute, Create, FORCEINLINE, and MoveTemp().
CreateLambda()
template<typename ObjectType> template<typename LambdaType, typename... PayloadTypes> FORCEINLINE TAttribute TAttribute< ObjectType >::CreateLambda (LambdaType && InCallable, PayloadTypes &&... InputPayload) inline static nodiscard
Helper function for creating TAttributes from a lambda TAttribute<float> FloatAttribute = TAttribute<float>::CreateLambda([]{ return 10.f; });.
Definition at line 155 of file Attribute.h.
References TAttribute, Create, FORCEINLINE, and Forward().
CreateRaw()
template<typename ObjectType> template<typename SourceType, typename SourceTypeOrBase, typename... PayloadTypes> FORCEINLINE TAttribute TAttribute< ObjectType >::CreateRaw (const SourceType * InObject, ObjectType(SourceTypeOrBase::* InMethod)(PayloadTypes...) const, typename TDecay< PayloadTypes >::Type... InputPayload) inline static nodiscard
Helper function for creating TAttributes from a const member function pointer, accessed through a raw pointer.
Definition at line 136 of file Attribute.h.
References TAttribute, Create, FORCEINLINE, and MoveTemp().
CreateSP()
template<typename ObjectType> template<typename SourceType, typename SourceTypeOrBase, typename... PayloadTypes> FORCEINLINE TAttribute TAttribute< ObjectType >::CreateSP (const SourceType * InObject, ObjectType(SourceTypeOrBase::* InMethod)(PayloadTypes...) const, typename TDecay< PayloadTypes >::Type... InputPayload) inline static nodiscard
Helper function for creating TAttributes from a const member function pointer, accessed through a weak pointer to the shared object.
Definition at line 145 of file Attribute.h.
References TAttribute, Create, FORCEINLINE, and MoveTemp().
Referenced by TAttribute(), and TAttribute().
CreateSPLambda() [1/2]
template<typename ObjectType> template<typename UserClass, ESPMode Mode, typename LambdaType, typename... PayloadTypes> FORCEINLINE TAttribute TAttribute< ObjectType >::CreateSPLambda (const TSharedRef< UserClass, Mode > & InUserObjectRef, LambdaType && InCallable, PayloadTypes &&... InputPayload) inline static nodiscard
Helper function for creating TAttributes from a weak shared pointer C++ lambda delegate.
Definition at line 164 of file Attribute.h.
References TAttribute, Create, FORCEINLINE, and Forward().
CreateSPLambda() [2/2]
template<typename ObjectType> template<typename UserClass, typename LambdaType, typename... PayloadTypes> FORCEINLINE TAttribute TAttribute< ObjectType >::CreateSPLambda (UserClass * InUserObject, LambdaType && InCallable, PayloadTypes &&... InputPayload) inline static nodiscard
Definition at line 169 of file Attribute.h.
References TAttribute, Create, FORCEINLINE, and Forward().
CreateStatic()
template<typename ObjectType> template<typename FuncPtrType, typename... VarTypes> TAttribute TAttribute< ObjectType >::CreateStatic (FuncPtrType && InFuncPtr, VarTypes... Vars) inline static nodiscard
Creates an attribute by binding an arbitrary function that will be called to generate this attribute's value on demand.
After binding, the attribute will no longer have a value that can be accessed directly, and instead the bound function will always be called to generate the value.
Parameters
InFuncPtr Member function to bind. The function's structure (return value, arguments, etc) must match IBoundAttributeDelegate's definition.
Definition at line 126 of file Attribute.h.
References TAttribute, and MoveTemp().
CreateWeakLambda()
template<typename ObjectType> template<typename UserClass, typename LambdaType, typename... PayloadTypes> FORCEINLINE TAttribute TAttribute< ObjectType >::CreateWeakLambda (UserClass * InUserObject, LambdaType && InCallable, PayloadTypes &&... InputPayload) inline static nodiscard
Helper function for creating TAttributes from a weak object pointer C++ lambda delegate.
Definition at line 178 of file Attribute.h.
References TAttribute, Create, FORCEINLINE, and Forward().
DECLARE_DELEGATE_RetVal()
template<typename ObjectType> TAttribute< ObjectType >::DECLARE_DELEGATE_RetVal (ObjectType , FGetter)
Attribute 'getter' delegate.
ObjectType GetValue() const
Returns
The attribute's value
Get() [1/2]
template<typename ObjectType> const ObjectType & TAttribute< ObjectType >::Get () const inline
Gets the attribute's current value.
Assumes that the attribute is set.
Returns
The attribute's value
Definition at line 241 of file Attribute.h.
References Getter, and Value.
Referenced by FDynamicTextToken::FDynamicTextToken(), ArrangeSingleChild(), SNodePanel::SNode::ComputeDesiredSize(), SMultiColumnTableRow< ItemType >::GenerateColumns(), Get(), SNodePanel::SNode::GetRelativeLayoutScale(), UE::Slate::TSlotAccessor< SlotType, std::enable_if_t< std::is_base_of_v< FSlotProxy, std::decay_t< SlotType > > > >::GetShrinkSizeValue(), UE::Slate::TSlotAccessor< SlotType, std::enable_if_t< std::is_base_of_v< FSlotProxy, std::decay_t< SlotType > > > >::GetSizeValue(), SNodePanel::SNode::OnArrangeChildren(), SSegmentedControl< OptionType >::RebuildChildren(), and SSegmentedControl< OptionType >::SetValue().
Get() [2/2]
template<typename ObjectType> const ObjectType & TAttribute< ObjectType >::Get (const ObjectType & DefaultValue) const inline
Gets the attribute's current value.
The attribute may not be set, in which case use the default value provided. Shorthand for the boilerplate code: MyAttribute.IsSet() ? MyAttribute.Get() : DefaultValue
Definition at line 262 of file Attribute.h.
References bIsSet, and Get().
GetBinding()
template<typename ObjectType> const FGetter & TAttribute< ObjectType >::GetBinding () const inline nodiscard
Gets the attribute's 'getter' which can be bound or unbound.
Returns
The attribute's FGetter.
Definition at line 437 of file Attribute.h.
References Getter.
IdenticalTo()
template<typename ObjectType> bool TAttribute< ObjectType >::IdenticalTo (const TAttribute< ObjectType > & InOther) const inline
Is this attribute identical to another TAttribute.
Parameters
InOther The other attribute to compare with.
Returns
true if the attributes are identical, false otherwise.
Definition at line 460 of file Attribute.h.
References TAttribute, Getter, IsBound(), IsSet(), and Value.
Referenced by FSlotBase::SetAttribute(), and SetWidgetAttribute().
IsBound()
template<typename ObjectType> bool TAttribute< ObjectType >::IsBound () const inline
Checks to see if this attribute has a 'getter' function bound.
Returns
True if attribute is bound to a getter function
Definition at line 427 of file Attribute.h.
References Getter.
Referenced by IdenticalTo(), SSegmentedControl< OptionType >::RebuildChildren(), FSlotBase::SetAttribute(), SSpacer::SetSize(), SSegmentedControl< OptionType >::SetValue(), SetWidgetAttribute(), and Steal().
IsSet()
template<typename ObjectType> bool TAttribute< ObjectType >::IsSet () const inline
Was this TAttribute ever assigned?
Definition at line 230 of file Attribute.h.
References bIsSet.
Referenced by IdenticalTo(), SWidget::SetHover(), TResizingWidgetSlotMixin< MixedIntoType >::SetSizeParam(), SSegmentedControl< OptionType >::SetValue(), and Steal().
Set() [1/2]
template<typename ObjectType> template<typename OtherType> void TAttribute< ObjectType >::Set (const OtherType & InNewValue) inline
Sets the attribute's value.
Parameters
InNewValue The value to set the attribute to
Definition at line 210 of file Attribute.h.
References bIsSet, Getter, and Value.
Set() [2/2]
template<typename ObjectType> void TAttribute< ObjectType >::Set (ObjectType && InNewValue) inline
Sets the attribute's value.
Parameters
InNewValue The value to set the attribute to
Definition at line 222 of file Attribute.h.
References bIsSet, Getter, MoveTemp(), and Value.
Steal()
template<typename ObjectType> TVariant< ObjectType, FGetter > TAttribute< ObjectType >::Steal () inline nodiscard
Move the attribute's 'getter' or the attribute's Value and reset the attribute.
The attribute needs to be set.
Returns
The attribute's FGetter or Value
Definition at line 447 of file Attribute.h.
References bIsSet, checkf, Getter, IsBound(), IsSet(), MoveTemp(), TEXT, and Value.
Friends And Related Symbol Documentation
TAttribute
template<typename ObjectType> template<class OtherType> friend class TAttribute friend
Definition at line 496 of file Attribute.h.
References TAttribute.
Referenced by TAttribute, Create(), Create(), Create(), Create(), CreateLambda(), CreateRaw(), CreateSP(), CreateSPLambda(), CreateSPLambda(), CreateStatic(), CreateWeakLambda(), and IdenticalTo().
Field Documentation
bIsSet
template<typename ObjectType> bool TAttribute< ObjectType >::bIsSet private
true when this attribute was explicitly set by a consumer, false when the attribute's value is set to the default
Definition at line 502 of file Attribute.h.
Referenced by TAttribute(), TAttribute(), TAttribute(), TAttribute(), TAttribute(), TAttribute(), TAttribute(), Bind(), Bind(), Bind(), Bind(), BindLambda(), BindRaw(), BindSPLambda(), BindSPLambda(), BindStatic(), BindUFunction(), BindUObject(), BindWeakLambda(), Get(), IsSet(), Set(), Set(), and Steal().
Getter
template<typename ObjectType> FGetter TAttribute< ObjectType >::Getter private
Bound member function for this attribute (may be NULL if no function is bound.) When set, all attempts to read the attribute's value will instead call this delegate to generate the value.
Our attribute's 'getter' delegate
Definition at line 507 of file Attribute.h.
Referenced by TAttribute(), TAttribute(), TAttribute(), TAttribute(), TAttribute(), TAttribute(), TAttribute(), Bind(), Bind(), Bind(), Bind(), BindLambda(), BindRaw(), BindSPLambda(), BindSPLambda(), BindStatic(), BindUFunction(), BindUObject(), BindWeakLambda(), Get(), GetBinding(), IdenticalTo(), IsBound(), Set(), Set(), and Steal().
Value
template<typename ObjectType> ObjectType TAttribute< ObjectType >::Value mutable private
Current value.
Mutable so that we can cache the value locally when using a bound Getter (allows const ref return value.)
Definition at line 499 of file Attribute.h.
Referenced by TAttribute(), TAttribute(), TAttribute(), TAttribute(), TAttribute(), TAttribute(), TAttribute(), Get(), IdenticalTo(), Set(), Set(), and Steal().
The documentation for this class was generated from the following files:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/nDisplay/Source/DisplayClusterConfigurator/Public/Views/TreeViews/IDisplayClusterConfiguratorTreeItem.h
Runtime/Core/Public/Misc/Attribute.h