Unreal Engine 5.6 C++ API: FRigVMGraphEnumDetailCustomization Class Reference
FRigVMGraphEnumDetailCustomization Class Reference
Customization for editing a rig vm integer control enum class.
#include "RigVMGraphDetailCustomization.h"
Public Member Functions
FRigVMGraphEnumDetailCustomization ()
virtual void CustomizeChildren (TSharedRef< class IPropertyHandle > InPropertyHandle, class IDetailChildrenBuilder &StructBuilder, IPropertyTypeCustomizationUtils &StructCustomizationUtils) override
Called when the children of the property should be customized or extra rows added.
virtual void CustomizeHeader (TSharedRef< class IPropertyHandle > InPropertyHandle, class FDetailWidgetRow &HeaderRow, IPropertyTypeCustomizationUtils &StructCustomizationUtils) override
IPropertyTypeCustomization interface.
Public Member Functions inherited from IPropertyTypeCustomization
virtual ~IPropertyTypeCustomization ()
virtual bool ShouldInlineKey () const
Public Member Functions inherited from TSharedFromThis< IPropertyTypeCustomization >
TSharedRef< IPropertyTypeCustomization, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< IPropertyTypeCustomization, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Static Public Member Functions
static TSharedRef< IPropertyTypeCustomization > MakeInstance ()
Protected Member Functions
TArray< uint8 * > GetMemoryBeingCustomized ()
bool GetPropertyChain (TSharedRef< class IPropertyHandle > InPropertyHandle, FEditPropertyChain &OutPropertyChain, TArray< int32 > &OutPropertyArrayIndices, bool &bOutEnabled)
void HandleControlEnumChanged (TSharedPtr< FString > InEnumPath, ESelectInfo::Type InSelectType, TSharedRef< IPropertyHandle > InPropertyHandle)
Protected Member Functions inherited from TSharedFromThis< IPropertyTypeCustomization >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions
static UEnum ** ContainerMemoryBlockToEnumPtr (uint8 *InMemoryBlock, FEditPropertyChain &InPropertyChain, TArray< int32 > &InPropertyArrayIndices)
Static Protected Member Functions inherited from TSharedFromThis< IPropertyTypeCustomization >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Protected Attributes
URigVMBlueprint * BlueprintBeingCustomized
URigVMGraph * GraphBeingCustomized
TArray< TWeakObjectPtr< UObject > > ObjectsBeingCustomized
TArray< TSharedPtr< FStructOnScope > > StructsBeingCustomized
Detailed Description
Customization for editing a rig vm integer control enum class.
Definition at line 305 of file RigVMGraphDetailCustomization.h.
Constructor & Destructor Documentation
FRigVMGraphEnumDetailCustomization()
FRigVMGraphEnumDetailCustomization::FRigVMGraphEnumDetailCustomization ()
Referenced by MakeInstance().
Member Function Documentation
ContainerMemoryBlockToEnumPtr()
UEnum ** FRigVMGraphEnumDetailCustomization::ContainerMemoryBlockToEnumPtr (uint8 * InMemoryBlock, FEditPropertyChain & InPropertyChain, TArray< int32 > & InPropertyArrayIndices) inline static protected
Definition at line 381 of file RigVMGraphDetailCustomization.h.
References ArrayProperty, CastField(), check, TDoubleLinkedList< ElementType >::GetHead(), FScriptArrayHelper::GetRawPtr(), INDEX_NONE, FScriptArrayHelper::IsValidIndex(), TArray< InElementType, InAllocatorType >::IsValidIndex(), and Property.
CustomizeChildren()
virtual void FRigVMGraphEnumDetailCustomization::CustomizeChildren (TSharedRef< class IPropertyHandle > PropertyHandle, class IDetailChildrenBuilder & ChildBuilder, IPropertyTypeCustomizationUtils & CustomizationUtils) override virtual
Called when the children of the property should be customized or extra rows added.
Parameters
PropertyHandle Handle to the property being customized
StructBuilder A builder for adding children
StructCustomizationUtils Utilities for customization
Implements IPropertyTypeCustomization.
CustomizeHeader()
virtual void FRigVMGraphEnumDetailCustomization::CustomizeHeader (TSharedRef< class IPropertyHandle > InPropertyHandle, class FDetailWidgetRow & HeaderRow, IPropertyTypeCustomizationUtils & StructCustomizationUtils) override virtual
IPropertyTypeCustomization interface.
Implements IPropertyTypeCustomization.
GetMemoryBeingCustomized()
TArray< uint8 * > FRigVMGraphEnumDetailCustomization::GetMemoryBeingCustomized () inline protected
Definition at line 322 of file RigVMGraphDetailCustomization.h.
References TArray< InElementType, InAllocatorType >::Add(), Object, ObjectsBeingCustomized, TArray< InElementType, InAllocatorType >::Reserve(), and StructsBeingCustomized.
GetPropertyChain()
bool FRigVMGraphEnumDetailCustomization::GetPropertyChain (TSharedRef< class IPropertyHandle > InPropertyHandle, FEditPropertyChain & OutPropertyChain, TArray< int32 > & OutPropertyArrayIndices, bool & bOutEnabled) inline protected
Definition at line 346 of file RigVMGraphDetailCustomization.h.
References TDoubleLinkedList< ElementType >::AddHead(), TDoubleLinkedList< ElementType >::Empty(), TDoubleLinkedList< ElementType >::GetHead(), TDoubleLinkedList< ElementType >::GetTail(), FProperty::HasAnyPropertyFlags(), TArray< InElementType, InAllocatorType >::Insert(), TSharedPtr< ObjectType, InMode >::IsValid(), ObjectsBeingCustomized, TArray< InElementType, InAllocatorType >::Reset(), FEditPropertyChain::SetActiveMemberPropertyNode(), and StructsBeingCustomized.
HandleControlEnumChanged()
void FRigVMGraphEnumDetailCustomization::HandleControlEnumChanged (TSharedPtr< FString > InEnumPath, ESelectInfo::Type InSelectType, TSharedRef< IPropertyHandle > InPropertyHandle) protected
MakeInstance()
TSharedRef< IPropertyTypeCustomization > FRigVMGraphEnumDetailCustomization::MakeInstance () inline static
Definition at line 311 of file RigVMGraphDetailCustomization.h.
References FRigVMGraphEnumDetailCustomization(), and MakeShareable().
Field Documentation
BlueprintBeingCustomized
URigVMBlueprint* FRigVMGraphEnumDetailCustomization::BlueprintBeingCustomized protected
Definition at line 427 of file RigVMGraphDetailCustomization.h.
GraphBeingCustomized
URigVMGraph* FRigVMGraphEnumDetailCustomization::GraphBeingCustomized protected
Definition at line 428 of file RigVMGraphDetailCustomization.h.
ObjectsBeingCustomized
TArray<TWeakObjectPtr<UObject> > FRigVMGraphEnumDetailCustomization::ObjectsBeingCustomized protected
Definition at line 429 of file RigVMGraphDetailCustomization.h.
Referenced by GetMemoryBeingCustomized(), and GetPropertyChain().
StructsBeingCustomized
TArray<TSharedPtr<FStructOnScope> > FRigVMGraphEnumDetailCustomization::StructsBeingCustomized protected
Definition at line 430 of file RigVMGraphDetailCustomization.h.
Referenced by GetMemoryBeingCustomized(), and GetPropertyChain().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/RigVM/Source/RigVMEditor/Public/Editor/RigVMGraphDetailCustomization.h