Unreal Engine 5.6 C++ API: TWrappedToolCommandChange< ChangeType > Class Template Reference
TWrappedToolCommandChange< ChangeType > Class Template Reference
Holds another Change and forwards Apply/Revert to it, with calls to Before/After lambas, allowing client classes to respond to a change without having to intercept it explicitly.
#include "InteractiveToolChange.h"
Public Member Functions
virtual void Apply (UObject *Object) override
Makes the change to the object.
virtual void Revert (UObject *Object) override
Reverts change to the object.
virtual FString ToString () const override
Describes this change (for debugging)
Public Member Functions inherited from FCommandChange
virtual TUniquePtr< FChange > Execute (UObject *Object) final
Makes the change to the object, returning a new change that can be used to perfectly roll back this change.
virtual EChangeStyle GetChangeType () final
What style of change is this.
Public Member Functions inherited from FChange
virtual ~FChange ()
Virtual destructor.
virtual void AddReferencedObjects (FReferenceCollector &Collector)
Used by GC to collect referenced objects.
virtual bool HasExpired (UObject *Object) const
virtual void PrintToLog (FFeedbackContext &FeedbackContext, const int32 IndentLevel=0)
Prints this change to the log, including sub-changes if there are any.
Data Fields
TUniqueFunction< void(bool bRevert)> AfterModify
TUniqueFunction< void(bool bRevert)> BeforeModify
TUniquePtr< ChangeType > WrappedChange
Additional Inherited Members
Public Types inherited from FChange
enum class EChangeStyle { InPlaceSwap , CommandPattern }
Protected Member Functions inherited from FChange
FChange ()
Protected default constructor.
Detailed Description
template<typename ChangeType>
class TWrappedToolCommandChange< ChangeType >
Holds another Change and forwards Apply/Revert to it, with calls to Before/After lambas, allowing client classes to respond to a change without having to intercept it explicitly.
(Be very careful with these lambdas!)
Definition at line 93 of file InteractiveToolChange.h.
Member Function Documentation
Apply()
template<typename ChangeType> virtual void TWrappedToolCommandChange< ChangeType >::Apply (UObject * Object) inline override virtual
Makes the change to the object.
Implements FChange.
Definition at line 101 of file InteractiveToolChange.h.
References AfterModify, BeforeModify, Object, and WrappedChange.
Revert()
template<typename ChangeType> virtual void TWrappedToolCommandChange< ChangeType >::Revert (UObject * Object) inline override virtual
Reverts change to the object.
Implements FChange.
Definition at line 114 of file InteractiveToolChange.h.
References AfterModify, BeforeModify, Object, and WrappedChange.
ToString()
template<typename ChangeType> virtual FString TWrappedToolCommandChange< ChangeType >::ToString () const inline override virtual
Describes this change (for debugging)
Reimplemented from FToolCommandChange.
Definition at line 127 of file InteractiveToolChange.h.
References WrappedChange.
Field Documentation
AfterModify
template<typename ChangeType> TUniqueFunction<void(bool bRevert)> TWrappedToolCommandChange< ChangeType >::AfterModify
Definition at line 99 of file InteractiveToolChange.h.
Referenced by Apply(), and Revert().
BeforeModify
template<typename ChangeType> TUniqueFunction<void(bool bRevert)> TWrappedToolCommandChange< ChangeType >::BeforeModify
Definition at line 98 of file InteractiveToolChange.h.
Referenced by Apply(), and Revert().
WrappedChange
template<typename ChangeType> TUniquePtr<ChangeType> TWrappedToolCommandChange< ChangeType >::WrappedChange
Definition at line 96 of file InteractiveToolChange.h.
Referenced by Apply(), Revert(), and ToString().
The documentation for this class was generated from the following file:
Runtime/InteractiveToolsFramework/Public/InteractiveToolChange.h