Unreal Engine 5.6 C++ API: FRenderTargetPool Class Reference
FRenderTargetPool Class Reference
Encapsulates the render targets pools that allows easy sharing (mostly used on the render thread side)
#include "RenderTargetPool.h"
Public Member Functions
FRenderTargetPool ()=default
RENDERCORE_API void CreateUntrackedElement (const FPooledRenderTargetDesc &Desc, TRefCountPtr< IPooledRenderTarget > &Out, const FSceneRenderTargetItem &Item)
RENDERCORE_API void DumpMemoryUsage (FOutputDevice &OutputDevice)
bool FindFreeElement (const FRHITextureCreateInfo &Desc, TRefCountPtr< IPooledRenderTarget > &Out, const TCHAR *Name)
bool FindFreeElement (FRHICommandListBase &RHICmdList, const FPooledRenderTargetDesc &Desc, TRefCountPtr< IPooledRenderTarget > &Out, const TCHAR *InDebugName)
RENDERCORE_API bool FindFreeElement (FRHICommandListBase &RHICmdList, const FRHITextureCreateInfo &Desc, TRefCountPtr< IPooledRenderTarget > &Out, const TCHAR *Name)
RENDERCORE_API TRefCountPtr< IPooledRenderTarget > FindFreeElement (FRHICommandListBase &RHICmdList, FRHITextureCreateInfo Desc, const TCHAR *Name)
TRefCountPtr< IPooledRenderTarget > FindFreeElement (FRHITextureCreateInfo Desc, const TCHAR *Name)
RENDERCORE_API int32 FindIndex (IPooledRenderTarget *In) const
RENDERCORE_API void FreeUnusedResource (TRefCountPtr< IPooledRenderTarget > &In)
Allows to remove a resource so it cannot be shared and gets released immediately instead a/some frame[s] later.
RENDERCORE_API void FreeUnusedResources ()
Good to call between levels or before memory intense operations.
RENDERCORE_API FPooledRenderTarget * GetElementById (uint32 Id) const
uint32 GetElementCount () const
RENDERCORE_API void GetStats (uint32 &OutWholeCount, uint32 &OutWholePoolInKB, uint32 &OutUsedInKB) const
Only to get statistics on usage and free elements.
RENDERCORE_API void ReleaseRHI ()
Free renderer resources.
RENDERCORE_API void TickPoolElements ()
Can release RT, should be called once per frame.
Public Member Functions inherited from FRenderResource
RENDERCORE_API FRenderResource ()
Default constructor.
RENDERCORE_API FRenderResource (const FRenderResource &)
Misc copy/assignment.
RENDERCORE_API FRenderResource (ERHIFeatureLevel::Type InFeatureLevel)
Constructor when we know what feature level this resource should support.
RENDERCORE_API FRenderResource (FRenderResource &&)
virtual RENDERCORE_API ~FRenderResource ()
Destructor used to catch unreleased resources.
virtual FString GetFriendlyName () const
EInitPhase GetInitPhase () const
int32 GetListIndex () const
FName GetOwnerName () const
FName GetResourceName () const
virtual RENDERCORE_API void InitResource (FRHICommandListBase &RHICmdList)
Initializes the resource.
virtual void InitRHI (FRHICommandListBase &RHICmdList)
Initializes the RHI resources used by this resource.
FORCEINLINE bool IsInitialized () const
RENDERCORE_API FRenderResource & operator= (const FRenderResource &Other)
RENDERCORE_API FRenderResource & operator= (FRenderResource &&Other)
virtual RENDERCORE_API void ReleaseResource ()
Prepares the resource for deletion.
void SetOwnerName (FName InOwnerName)
SetOwnerName should be called before BeginInitResource for the owner name to be successfully tracked.
void SetResourceName (FName InResourceName)
RENDERCORE_API void UpdateRHI (FRHICommandListBase &RHICmdList)
If the resource's RHI resources have been initialized, then release and reinitialize it.
Private Member Functions
void CompactPool ()
FPooledRenderTarget * CreateRenderTarget (FRHICommandListBase &RHICmdList, const FRHITextureCreateInfo &Desc, uint32 DescHash, const TCHAR *Name)
void FinishSchedule (FRHICommandListBase &RHICmdList, FPooledRenderTarget *RenderTarget, const TCHAR *Name)
void FreeElementAtIndex (int32 Index)
FPooledRenderTarget * ScheduleAllocation (FRHICommandListBase &RHICmdList, FRHITextureCreateInfo Desc, const TCHAR *Name, const FRHITransientAllocationFences &Fences)
void ScheduleDeallocation (FPooledRenderTarget *RenderTarget, const FRHITransientAllocationFences &Fences)
FPooledRenderTarget * TryFindRenderTarget (const FRHITextureCreateInfo &Desc, uint32 DescHash) const
template<typename T>
FPooledRenderTarget * TryFindRenderTarget (const FRHITextureCreateInfo &Desc, uint32 DescHash, T &&Predicate) const
Private Attributes
uint32 AllocationLevelInKB = 0
bool bCurrentlyOverBudget = false
TArray< TRefCountPtr< FPooledRenderTarget > > DeferredDeleteArray
UE::FRecursiveMutex Mutex
TArray< uint32 > PooledRenderTargetHashes
Elements can be 0, we compact the buffer later.
TArray< TRefCountPtr< FPooledRenderTarget > > PooledRenderTargets
Friends
struct FPooledRenderTarget
class FRDGBuilder
class FVisualizeTexture
class FVisualizeTexturePresent
Additional Inherited Members
Public Types inherited from FRenderResource
enum class EInitPhase : uint8 { Pre , Default , MAX }
Controls initialization order of render resources.
Static Public Member Functions inherited from FRenderResource
static RENDERCORE_API void ChangeFeatureLevel (ERHIFeatureLevel::Type NewFeatureLevel)
Reinitializes render resources at a new feature level.
static RENDERCORE_API void InitPreRHIResources ()
Initialize all resources initialized before the RHI was initialized.
static RENDERCORE_API void ReleaseRHIForAllResources ()
Release all render resources that are currently initialized.
Data Fields inherited from FRenderResource
ERenderResourceState ResourceState = ERenderResourceState::Default
Protected Member Functions inherited from FRenderResource
template<typename T>
FBufferRHIRef CreateRHIBuffer (FRHICommandListBase &RHICmdList, T &InOutResourceObject, uint32 ResourceCount, EBufferUsageFlags InBufferUsageFlags, const TCHAR *InDebugName)
const FStaticFeatureLevel GetFeatureLevel () const
FORCEINLINE bool HasValidFeatureLevel () const
void SetFeatureLevel (const FStaticFeatureLevel InFeatureLevel)
void SetInitPhase (EInitPhase InInitPhase)
Static Protected Member Functions inherited from FRenderResource
static RENDERCORE_API FRHICommandListBase & GetImmediateCommandList ()
Detailed Description
Encapsulates the render targets pools that allows easy sharing (mostly used on the render thread side)
Definition at line 96 of file RenderTargetPool.h.
Constructor & Destructor Documentation
FRenderTargetPool()
FRenderTargetPool::FRenderTargetPool () default
Member Function Documentation
CompactPool()
void FRenderTargetPool::CompactPool () private
CreateRenderTarget()
FPooledRenderTarget * FRenderTargetPool::CreateRenderTarget (FRHICommandListBase & RHICmdList, const FRHITextureCreateInfo & Desc, uint32 DescHash, const TCHAR * Name) private
References FPooledRenderTarget, and Name.
CreateUntrackedElement()
RENDERCORE_API void FRenderTargetPool::CreateUntrackedElement (const FPooledRenderTargetDesc & Desc, TRefCountPtr< IPooledRenderTarget > & Out, const FSceneRenderTargetItem & Item)
References Item.
DumpMemoryUsage()
RENDERCORE_API void FRenderTargetPool::DumpMemoryUsage (FOutputDevice & OutputDevice)
FindFreeElement() [1/5]
bool FRenderTargetPool::FindFreeElement (const FRHITextureCreateInfo & Desc, TRefCountPtr< IPooledRenderTarget > & Out, const TCHAR * Name) inline
Definition at line 110 of file RenderTargetPool.h.
References FindFreeElement(), and Name.
FindFreeElement() [2/5]
bool FRenderTargetPool::FindFreeElement (FRHICommandListBase & RHICmdList, const FPooledRenderTargetDesc & Desc, TRefCountPtr< IPooledRenderTarget > & Out, const TCHAR * InDebugName) inline
Parameters
DebugName must not be 0, we only store the pointer
Out is not the return argument to avoid double allocation because of wrong reference counting call from RenderThread only
Returns
true if the old element was still valid, false if a new one was assigned
Definition at line 121 of file RenderTargetPool.h.
References FindFreeElement(), and Translate().
FindFreeElement() [3/5]
RENDERCORE_API bool FRenderTargetPool::FindFreeElement (FRHICommandListBase & RHICmdList, const FRHITextureCreateInfo & Desc, TRefCountPtr< IPooledRenderTarget > & Out, const TCHAR * Name)
References Name.
FindFreeElement() [4/5]
RENDERCORE_API TRefCountPtr< IPooledRenderTarget > FRenderTargetPool::FindFreeElement (FRHICommandListBase & RHICmdList, FRHITextureCreateInfo Desc, const TCHAR * Name)
References Name.
Referenced by FindFreeElement(), FindFreeElement(), and FindFreeElement().
FindFreeElement() [5/5]
TRefCountPtr< IPooledRenderTarget > FRenderTargetPool::FindFreeElement (FRHITextureCreateInfo Desc, const TCHAR * Name) inline
Definition at line 105 of file RenderTargetPool.h.
References FindFreeElement(), and Name.
FindIndex()
RENDERCORE_API int32 FRenderTargetPool::FindIndex (IPooledRenderTarget * In) const
FinishSchedule()
void FRenderTargetPool::FinishSchedule (FRHICommandListBase & RHICmdList, FPooledRenderTarget * RenderTarget, const TCHAR * Name) private
References FPooledRenderTarget, Name, and RenderTarget.
FreeElementAtIndex()
void FRenderTargetPool::FreeElementAtIndex (int32 Index) private
FreeUnusedResource()
RENDERCORE_API void FRenderTargetPool::FreeUnusedResource (TRefCountPtr< IPooledRenderTarget > & In)
Allows to remove a resource so it cannot be shared and gets released immediately instead a/some frame[s] later.
FreeUnusedResources()
RENDERCORE_API void FRenderTargetPool::FreeUnusedResources ()
Good to call between levels or before memory intense operations.
GetElementById()
RENDERCORE_API FPooledRenderTarget * FRenderTargetPool::GetElementById (uint32 Id) const
References FPooledRenderTarget.
GetElementCount()
uint32 FRenderTargetPool::GetElementCount () const inline
Definition at line 152 of file RenderTargetPool.h.
References PooledRenderTargets.
GetStats()
RENDERCORE_API void FRenderTargetPool::GetStats (uint32 & OutWholeCount, uint32 & OutWholePoolInKB, uint32 & OutUsedInKB) const
Only to get statistics on usage and free elements.
Normally only called in renderthread or if FlushRenderingCommands was called()
ReleaseRHI()
RENDERCORE_API void FRenderTargetPool::ReleaseRHI () virtual
Free renderer resources.
Reimplemented from FRenderResource.
ScheduleAllocation()
FPooledRenderTarget * FRenderTargetPool::ScheduleAllocation (FRHICommandListBase & RHICmdList, FRHITextureCreateInfo Desc, const TCHAR * Name, const FRHITransientAllocationFences & Fences) private
References FPooledRenderTarget, and Name.
ScheduleDeallocation()
void FRenderTargetPool::ScheduleDeallocation (FPooledRenderTarget * RenderTarget, const FRHITransientAllocationFences & Fences) private
References FPooledRenderTarget, and RenderTarget.
TickPoolElements()
RENDERCORE_API void FRenderTargetPool::TickPoolElements ()
Can release RT, should be called once per frame.
call from RenderThread only
TryFindRenderTarget() [1/2]
FPooledRenderTarget * FRenderTargetPool::TryFindRenderTarget (const FRHITextureCreateInfo & Desc, uint32 DescHash) const inline private
Definition at line 168 of file RenderTargetPool.h.
References FPooledRenderTarget, and TryFindRenderTarget().
TryFindRenderTarget() [2/2]
template<typename T> FPooledRenderTarget * FRenderTargetPool::TryFindRenderTarget (const FRHITextureCreateInfo & Desc, uint32 DescHash, T && Predicate) const private
References FPooledRenderTarget, and Predicate.
Referenced by TryFindRenderTarget().
Friends And Related Symbol Documentation
FPooledRenderTarget
friend struct FPooledRenderTarget friend
Definition at line 204 of file RenderTargetPool.h.
References FPooledRenderTarget.
Referenced by CreateRenderTarget(), FinishSchedule(), FPooledRenderTarget, GetElementById(), ScheduleAllocation(), ScheduleDeallocation(), TryFindRenderTarget(), and TryFindRenderTarget().
FRDGBuilder
friend class FRDGBuilder friend
Definition at line 207 of file RenderTargetPool.h.
References FRDGBuilder.
Referenced by FRDGBuilder.
FVisualizeTexture
friend class FVisualizeTexture friend
Definition at line 205 of file RenderTargetPool.h.
References FVisualizeTexture.
Referenced by FVisualizeTexture.
FVisualizeTexturePresent
friend class FVisualizeTexturePresent friend
Definition at line 206 of file RenderTargetPool.h.
References FVisualizeTexturePresent.
Referenced by FVisualizeTexturePresent.
Field Documentation
AllocationLevelInKB
uint32 FRenderTargetPool::AllocationLevelInKB = 0 private
Definition at line 196 of file RenderTargetPool.h.
bCurrentlyOverBudget
bool FRenderTargetPool::bCurrentlyOverBudget = false private
Definition at line 199 of file RenderTargetPool.h.
DeferredDeleteArray
TArray< TRefCountPtr<FPooledRenderTarget> > FRenderTargetPool::DeferredDeleteArray private
Definition at line 193 of file RenderTargetPool.h.
Mutex
UE::FRecursiveMutex FRenderTargetPool::Mutex mutable private
Definition at line 188 of file RenderTargetPool.h.
PooledRenderTargetHashes
TArray<uint32> FRenderTargetPool::PooledRenderTargetHashes private
Elements can be 0, we compact the buffer later.
Definition at line 191 of file RenderTargetPool.h.
PooledRenderTargets
TArray< TRefCountPtr<FPooledRenderTarget> > FRenderTargetPool::PooledRenderTargets private
Definition at line 192 of file RenderTargetPool.h.
Referenced by GetElementCount().
The documentation for this class was generated from the following file:
Runtime/RenderCore/Public/RenderTargetPool.h