Unreal Engine 5.6 C++ API: FRDGBufferAccess Class Reference
FRDGBufferAccess Class Reference
#include "ShaderParameterMacros.h"
Public Member Functions
FRDGBufferAccess ()=default
FRDGBufferAccess (FRDGBuffer *InBuffer, ERHIAccess InAccess)
FORCEINLINE ERHIAccess GetAccess () const
FORCEINLINE FRDGBuffer * GetBuffer () const
FORCEINLINE operator bool () const
FORCEINLINE operator FRDGBuffer * () const
FORCEINLINE bool operator!= (const FRDGBufferAccess &RHS) const
FORCEINLINE FRDGBuffer * operator-> () const
FORCEINLINE bool operator== (const FRDGBufferAccess &RHS) const
Private Attributes
ERHIAccess Access = ERHIAccess::Unknown
TAlignedShaderParameterPtr< FRDGBuffer * > Buffer = nullptr
Detailed Description
Definition at line 365 of file ShaderParameterMacros.h.
Constructor & Destructor Documentation
FRDGBufferAccess() [1/2]
FRDGBufferAccess::FRDGBufferAccess () default
Referenced by TRDGBufferAccess< InAccess >::TRDGBufferAccess(), TRDGBufferAccess< InAccess >::TRDGBufferAccess(), operator!=(), and operator==().
FRDGBufferAccess() [2/2]
FRDGBufferAccess::FRDGBufferAccess (FRDGBuffer * InBuffer, ERHIAccess InAccess) inline
Definition at line 369 of file ShaderParameterMacros.h.
References Access, Buffer, and check.
Member Function Documentation
GetAccess()
FORCEINLINE ERHIAccess FRDGBufferAccess::GetAccess () const inline
Definition at line 377 of file ShaderParameterMacros.h.
References Access, and FORCEINLINE.
GetBuffer()
FORCEINLINE FRDGBuffer * FRDGBufferAccess::GetBuffer () const inline
Definition at line 376 of file ShaderParameterMacros.h.
References Buffer, and FORCEINLINE.
operator bool()
FORCEINLINE FRDGBufferAccess::operator bool () const inline
Definition at line 379 of file ShaderParameterMacros.h.
References Buffer, and FORCEINLINE.
operator FRDGBuffer *()
FORCEINLINE FRDGBufferAccess::operator FRDGBuffer * () const inline
Definition at line 390 of file ShaderParameterMacros.h.
References Buffer, and FORCEINLINE.
operator!=()
FORCEINLINE bool FRDGBufferAccess::operator!= (const FRDGBufferAccess & RHS) const inline
Definition at line 400 of file ShaderParameterMacros.h.
References FRDGBufferAccess(), Access, Buffer, and FORCEINLINE.
operator->()
FORCEINLINE FRDGBuffer * FRDGBufferAccess::operator-> () const inline
Definition at line 384 of file ShaderParameterMacros.h.
References Buffer, check, and FORCEINLINE.
operator==()
FORCEINLINE bool FRDGBufferAccess::operator== (const FRDGBufferAccess & RHS) const inline
Definition at line 395 of file ShaderParameterMacros.h.
References FRDGBufferAccess(), Access, Buffer, and FORCEINLINE.
Field Documentation
Access
ERHIAccess FRDGBufferAccess::Access = ERHIAccess::Unknown private
Definition at line 407 of file ShaderParameterMacros.h.
Referenced by FRDGBufferAccess(), GetAccess(), operator!=(), and operator==().
Buffer
TAlignedShaderParameterPtr<FRDGBuffer*> FRDGBufferAccess::Buffer = nullptr private
Definition at line 406 of file ShaderParameterMacros.h.
Referenced by FRDGBufferAccess(), GetBuffer(), operator bool(), operator FRDGBuffer *(), operator!=(), operator->(), and operator==().
The documentation for this class was generated from the following file:
Runtime/RenderCore/Public/ShaderParameterMacros.h