Unreal Engine 5.6 C++ API: UNetworkSettings Class Reference
UNetworkSettings Class Reference
#include "NetworkSettings.h"
Public Member Functions
virtual void PostEditChangeProperty (FPropertyChangedEvent &PropertyChangedEvent) override
virtual void PostInitProperties () override
Private Member Functions
GENERATED_UCLASS_BODY () static const int32 DefaultMaxRepArraySize
Default MaxRepArraySize.
UPROPERTY()) uint32 bVerifyPeer UPROPERTY()) uint32 bEnableMultiplayerWorldOriginRebasing UPROPERTY () TArray< FNetworkEmulationProfileDescription > NetworkEmulationProfiles
This lists the common network emulation profiles that will be selectable in PIE settings.
Static Private Attributes
static const int32 DefaultMaxRepArrayMemory = UINT16_MAX
Default MaxRepArrayMemory.
Detailed Description
Definition at line 28 of file NetworkSettings.h.
Member Function Documentation
GENERATED_UCLASS_BODY()
UNetworkSettings::GENERATED_UCLASS_BODY () const private
Default MaxRepArraySize.
See also
MaxRepArraySize.
PostEditChangeProperty()
virtual void UNetworkSettings::PostEditChangeProperty (FPropertyChangedEvent & PropertyChangedEvent) override virtual
PostInitProperties()
virtual void UNetworkSettings::PostInitProperties () override virtual
References PostInitProperties().
Referenced by PostInitProperties().
UPROPERTY()
UPROPERTY()) uint32 bVerifyPeer UPROPERTY()) uint32 bEnableMultiplayerWorldOriginRebasing UNetworkSettings::UPROPERTY () private
This lists the common network emulation profiles that will be selectable in PIE settings.
References config, and UPROPERTY().
Referenced by UPROPERTY().
Field Documentation
DefaultMaxRepArrayMemory
const int32 UNetworkSettings::DefaultMaxRepArrayMemory = UINT16_MAX static private
Default MaxRepArrayMemory.
See also
MaxRepArrayMemory.
Definition at line 36 of file NetworkSettings.h.
The documentation for this class was generated from the following file:
Runtime/Engine/Classes/Engine/NetworkSettings.h