Unreal Engine 5.6 C++ API: UE::Geometry::FGeometrySelectionPreview Class Reference
UE::Geometry::FGeometrySelectionPreview Class Reference
FGeometrySelectionPreview is a combined FGeometrySelection and FGeometrySelectionEditor.
#include "GeometrySelection.h"
Public Member Functions
FGeometrySelectionPreview (const FGeometrySelectionEditor &ActiveEditor)
bool IsEmpty () const
Public Member Functions inherited from UE::Geometry::FGeometrySelectionEditor
DYNAMICMESH_API void ClearSelection (FGeometrySelectionDelta &DeltaOut)
Clear the Target Selection and return change information in DeltaOut.
template<typename ListType>
bool Deselect (const ListType &List, FGeometrySelectionDelta &DeltaOut)
Remove the items in the List from the Target Selection and return change information in DeltaOut.
EGeometryElementType GetElementType () const
bool GetIsTopologyIDFilteringEnabled () const
const FGeometrySelectionHitQueryConfig & GetQueryConfig () const
const FGeometrySelection & GetSelection () const
Access the Selection object this Editor is modifying.
EGeometryTopologyType GetTopologyType () const
DYNAMICMESH_API void Initialize (FGeometrySelection *TargetSelectionIn, bool bEnableTopologyIDFiltering)
Initialize the Editor with the given Selection.
DYNAMICMESH_API void Initialize (FGeometrySelection *TargetSelectionIn, const FGeometrySelectionHitQueryConfig &QueryConfigIn, bool bEnableTopologyIDFiltering)
Initialize the Editor with the given Selection.
DYNAMICMESH_API bool IsSelected (uint64 ID) const
DYNAMICMESH_API bool RemoveFromSelection (uint64 ID)
Remove ID from Selection.
DYNAMICMESH_API bool Replace (const FGeometrySelection &NewSelection, FGeometrySelectionDelta &DeltaOut)
Replace the current set of selected items with those in the NewSelection, and return change information in DeltaOut.
template<typename ListType>
bool Select (const ListType &List, FGeometrySelectionDelta &DeltaOut)
Add the items in the List to the Target Selection and return change information in DeltaOut.
bool Select (uint64 ID)
Add the items to the Target Selection.
DYNAMICMESH_API void UpdateQueryConfig (const FGeometrySelectionHitQueryConfig &NewConfig, bool bEnableTopologyIDFilteringIn)
Update the active QueryConfig for this SelectionEditor.
Data Fields
FGeometrySelection PreviewSelection
Additional Inherited Members
Protected Member Functions inherited from UE::Geometry::FGeometrySelectionEditor
DYNAMICMESH_API uint64 RemapToExistingTopologyID (uint64 ID, bool &bFoundOut) const
Protected Attributes inherited from UE::Geometry::FGeometrySelectionEditor
bool bEnableTopologyIDFiltering = false
FGeometrySelectionHitQueryConfig QueryConfig
FGeometrySelection * TargetSelection = nullptr
Detailed Description
FGeometrySelectionPreview is a combined FGeometrySelection and FGeometrySelectionEditor.
The purpose of this class is to support things like hover-highlighting, where the Selection system needs to be queried but the result is going to be discarded. FGeometrySelectionPreview can only be constructed based on a parent FGeometrySelectionEditor, from which it derives it's configuration, which is then how the rest of the system knows what geometry to provide as a preview/etc
Definition at line 444 of file GeometrySelection.h.
Constructor & Destructor Documentation
FGeometrySelectionPreview()
UE::Geometry::FGeometrySelectionPreview::FGeometrySelectionPreview (const FGeometrySelectionEditor & ActiveEditor) inline
Definition at line 449 of file GeometrySelection.h.
References UE::Geometry::FGeometrySelectionEditor::GetIsTopologyIDFilteringEnabled(), UE::Geometry::FGeometrySelectionEditor::GetQueryConfig(), UE::Geometry::FGeometrySelectionEditor::GetSelection(), Initialize, and PreviewSelection.
Member Function Documentation
IsEmpty()
bool UE::Geometry::FGeometrySelectionPreview::IsEmpty () const inline
Definition at line 455 of file GeometrySelection.h.
References PreviewSelection.
Field Documentation
PreviewSelection
FGeometrySelection UE::Geometry::FGeometrySelectionPreview::PreviewSelection
Definition at line 447 of file GeometrySelection.h.
Referenced by FGeometrySelectionPreview(), and IsEmpty().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/GeometryProcessing/Source/DynamicMesh/Public/Selections/GeometrySelection.h