Unreal Engine 5.6 C++ API: FRayTracingDebugVisualizationMenuCommands Class Reference
FRayTracingDebugVisualizationMenuCommands Class Reference
#include "RayTracingDebugVisualizationMenuCommands.h"
Data Structures
struct FVisualizationRecord
Public Types
enum class FVisualizationType : uint8 {
Overview , Standard , Performance , Timing ,
Other
}
typedef TVisualizationModeCommandMap::TConstIterator TCommandConstIterator
typedef TMultiMap< FName, FVisualizationRecord > TVisualizationModeCommandMap
Public Member Functions
FRayTracingDebugVisualizationMenuCommands ()
void BindCommands (FUICommandList &CommandList, const TSharedPtr< FEditorViewportClient > &Client) const
TCommandConstIterator CreateCommandConstIterator () const
bool IsPopulated () const
virtual void RegisterCommands () override
Pure virtual to override; describe and instantiate the commands in here by using the UI COMMAND macro.
UE_DEPRECATED (5.6, "Please use the version taking UToolMenu* as argument") static void BuildVisualisationSubMenu(FMenuBuilder &Menu)
Public Member Functions inherited from FBindingContext
FBindingContext (const FBindingContext &)=default
FBindingContext (const FName InContextName, const FText &InContextDesc, const FName InContextParent, const FName InStyleSetName)
Constructor.
FBindingContext (FBindingContext &&)=default
void AddBundle (const FName Name, const FText &Desc)
Adds a new command bundle to this context that can be referenced by name from commands within the context.
const FText & GetBundleLabel (const FName Name)
Gets a localized label of a command bundle.
const FText & GetContextDesc () const
FName GetContextName () const
FName GetContextParent () const
FName GetStyleSetName () const
FUICommandInfoDecl NewCommand (const FName InCommandName, const FText &InCommandLabel, const FText &InCommandDesc)
Creates a new command declaration used to populate commands with data.
FBindingContext & operator= (const FBindingContext &)=default
FBindingContext & operator= (FBindingContext &&)=default
bool operator== (const FBindingContext &Other) const
Public Member Functions inherited from TSharedFromThis< FBindingContext >
TSharedRef< FBindingContext, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FBindingContext, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Static Public Member Functions
static void BuildVisualisationSubMenu (UToolMenu *InMenu)
Static Public Member Functions inherited from TCommands< FRayTracingDebugVisualizationMenuCommands >
static FRayTracingDebugVisualizationMenuCommands & Get ()
Get the singleton instance of this set of commands.
static const FBindingContext & GetContext ()
Get the BindingContext for this set of commands.
static bool IsRegistered ()
static void Register ()
Use this method to register commands.
static void Unregister ()
Use this method to clean up any resources used by the command set.
Private Member Functions
bool AddCommandTypeToMenu (FMenuBuilder &Menu, const FVisualizationType Type) const
Remove this function when removing deprecated BuildVisualisationSubMenu(FMenuBuilder& Menu)
bool AddCommandTypeToSection (FToolMenuSection &InSection, const FVisualizationType Type) const
void BuildCommandMap ()
Static Private Member Functions
static void ChangeRayTracingDebugVisualizationMode (TWeakPtr< FEditorViewportClient > WeakClient, FName InName)
static bool IsRayTracingDebugVisualizationModeSelected (TWeakPtr< FEditorViewportClient > WeakClient, FName InName)
Private Attributes
TVisualizationModeCommandMap CommandMap
Additional Inherited Members
Static Public Attributes inherited from FBindingContext
static FOnBindingContextChanged CommandsChanged
A delegate that is called when commands are registered or unregistered with a binding context.
Protected Member Functions inherited from TCommands< FRayTracingDebugVisualizationMenuCommands >
TCommands (const FName InContextName, const FText &InContextDesc, const FName InContextParent, const FName InStyleSetName)
Construct a set of commands; call this from your custom commands class.
virtual ~TCommands ()
Protected Member Functions inherited from TSharedFromThis< FBindingContext >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions inherited from TCommands< FRayTracingDebugVisualizationMenuCommands >
static TWeakPtr< FRayTracingDebugVisualizationMenuCommands > & GetInstance ()
A static instance of the command set.
Static Protected Member Functions inherited from TSharedFromThis< FBindingContext >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
Definition at line 16 of file RayTracingDebugVisualizationMenuCommands.h.
Member Typedef Documentation
TCommandConstIterator
typedef TVisualizationModeCommandMap::TConstIterator FRayTracingDebugVisualizationMenuCommands::TCommandConstIterator
Definition at line 43 of file RayTracingDebugVisualizationMenuCommands.h.
TVisualizationModeCommandMap
typedef TMultiMap<FName, FVisualizationRecord> FRayTracingDebugVisualizationMenuCommands::TVisualizationModeCommandMap
Definition at line 42 of file RayTracingDebugVisualizationMenuCommands.h.
Member Enumeration Documentation
FVisualizationType
enum class FRayTracingDebugVisualizationMenuCommands::FVisualizationType : uint8 strong
Enumerator
Overview
Standard
Performance
Timing
Other
Definition at line 19 of file RayTracingDebugVisualizationMenuCommands.h.
Constructor & Destructor Documentation
FRayTracingDebugVisualizationMenuCommands()
FRayTracingDebugVisualizationMenuCommands::FRayTracingDebugVisualizationMenuCommands ()
Member Function Documentation
AddCommandTypeToMenu()
bool FRayTracingDebugVisualizationMenuCommands::AddCommandTypeToMenu (FMenuBuilder & Menu, const FVisualizationType Type) const private
Remove this function when removing deprecated BuildVisualisationSubMenu(FMenuBuilder& Menu)
References Menu.
AddCommandTypeToSection()
bool FRayTracingDebugVisualizationMenuCommands::AddCommandTypeToSection (FToolMenuSection & InSection, const FVisualizationType Type) const private
BindCommands()
void FRayTracingDebugVisualizationMenuCommands::BindCommands (FUICommandList & CommandList, const TSharedPtr< FEditorViewportClient > & Client) const
References BindCommands(), and Client.
Referenced by BindCommands().
BuildCommandMap()
void FRayTracingDebugVisualizationMenuCommands::BuildCommandMap () private
BuildVisualisationSubMenu()
void FRayTracingDebugVisualizationMenuCommands::BuildVisualisationSubMenu (UToolMenu * InMenu) static
References BuildVisualisationSubMenu().
Referenced by BuildVisualisationSubMenu(), and UE_DEPRECATED().
ChangeRayTracingDebugVisualizationMode()
void FRayTracingDebugVisualizationMenuCommands::ChangeRayTracingDebugVisualizationMode (TWeakPtr< FEditorViewportClient > WeakClient, FName InName) static private
References InName.
CreateCommandConstIterator()
TCommandConstIterator FRayTracingDebugVisualizationMenuCommands::CreateCommandConstIterator () const
IsPopulated()
bool FRayTracingDebugVisualizationMenuCommands::IsPopulated () const inline
Definition at line 58 of file RayTracingDebugVisualizationMenuCommands.h.
References CommandMap, and IsPopulated().
Referenced by IsPopulated().
IsRayTracingDebugVisualizationModeSelected()
bool FRayTracingDebugVisualizationMenuCommands::IsRayTracingDebugVisualizationModeSelected (TWeakPtr< FEditorViewportClient > WeakClient, FName InName) static private
References InName.
RegisterCommands()
virtual void FRayTracingDebugVisualizationMenuCommands::RegisterCommands () override virtual
Pure virtual to override; describe and instantiate the commands in here by using the UI COMMAND macro.
Implements TCommands< FRayTracingDebugVisualizationMenuCommands >.
References RegisterCommands().
Referenced by RegisterCommands().
UE_DEPRECATED()
FRayTracingDebugVisualizationMenuCommands::UE_DEPRECATED (5. 6, "Please use the version taking UToolMenu* as argument") &
References BuildVisualisationSubMenu(), and Menu.
Field Documentation
CommandMap
TVisualizationModeCommandMap FRayTracingDebugVisualizationMenuCommands::CommandMap private
Definition at line 74 of file RayTracingDebugVisualizationMenuCommands.h.
Referenced by IsPopulated().
The documentation for this class was generated from the following file:
Editor/UnrealEd/Public/RayTracingDebugVisualizationMenuCommands.h