Unreal Engine 5.6 C++ API: FReturnGraphTask Class Reference
FReturnGraphTask Class Reference
FReturnGraphTask is a task used to return flow control from a named thread back to the original caller of ProcessThreadUntilRequestReturn.
#include "TaskGraphInterfaces.h"
Public Member Functions
FReturnGraphTask (ENamedThreads::Type InThreadToReturnFrom)
Constructor.
void DoTask (ENamedThreads::Type CurrentThread, const FGraphEventRef &MyCompletionGraphEvent)
Actually execute the task.
ENamedThreads::Type GetDesiredThread ()
Retrieve the thread that this task wants to run on.
FORCEINLINE TStatId GetStatId () const
Static Public Member Functions
static ESubsequentsMode::Type GetSubsequentsMode ()
Private Attributes
ENamedThreads::Type ThreadToReturnFrom
Named thread that we want to cause to return to the caller of ProcessThreadUntilRequestReturn.
Detailed Description
FReturnGraphTask is a task used to return flow control from a named thread back to the original caller of ProcessThreadUntilRequestReturn.
Definition at line 770 of file TaskGraphInterfaces.h.
Constructor & Destructor Documentation
FReturnGraphTask()
FReturnGraphTask::FReturnGraphTask (ENamedThreads::Type InThreadToReturnFrom) inline
Constructor.
Parameters
InThreadToReturnFrom; named thread to cause to return
Definition at line 778 of file TaskGraphInterfaces.h.
References ENamedThreads::AnyThread, checkThreadGraph, and ThreadToReturnFrom.
Member Function Documentation
DoTask()
void FReturnGraphTask::DoTask (ENamedThreads::Type CurrentThread, const FGraphEventRef & MyCompletionGraphEvent) inline
Actually execute the task.
Parameters
CurrentThread; the thread we are running on
MyCompletionGraphEvent; my completion event. Not always useful since at the end of DoWork, you can assume you are done and hence further tasks do not need you as a prerequisite. However, MyCompletionGraphEvent can be useful for passing to other routines or when it is handy to set up subsequents before you actually do work.
Definition at line 806 of file TaskGraphInterfaces.h.
References checkThreadGraph, FTaskGraphInterface::Get(), ENamedThreads::GetThreadIndex(), FTaskGraphInterface::RequestReturn(), and ThreadToReturnFrom.
GetDesiredThread()
ENamedThreads::Type FReturnGraphTask::GetDesiredThread () inline
Retrieve the thread that this task wants to run on.
Returns
the thread that this task should run on.
Definition at line 793 of file TaskGraphInterfaces.h.
References ThreadToReturnFrom.
GetStatId()
FORCEINLINE TStatId FReturnGraphTask::GetStatId () const inline
Definition at line 784 of file TaskGraphInterfaces.h.
References FORCEINLINE, and GET_STATID.
GetSubsequentsMode()
ESubsequentsMode::Type FReturnGraphTask::GetSubsequentsMode () inline static
Definition at line 798 of file TaskGraphInterfaces.h.
References ESubsequentsMode::TrackSubsequents.
Field Documentation
ThreadToReturnFrom
ENamedThreads::Type FReturnGraphTask::ThreadToReturnFrom private
Named thread that we want to cause to return to the caller of ProcessThreadUntilRequestReturn.
Definition at line 814 of file TaskGraphInterfaces.h.
Referenced by FReturnGraphTask(), DoTask(), and GetDesiredThread().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Async/TaskGraphInterfaces.h