Unreal Engine 5.6 C++ API: FNetworkPredictionServiceRegistry Class Reference
FNetworkPredictionServiceRegistry Class Reference
#include "NetworkPredictionServiceRegistry.h"
Data Structures
struct IDataStore
struct TServiceStorage
Public Member Functions
template<typename ModelDef = FNetworkPredictionModelDef>
TModelDataStore< ModelDef > * GetDataStore ()
template<typename ModelDef>
void RegisterInstance (FNetworkPredictionID ID, TInstanceData< ModelDef > &InstanceData, ENetworkPredictionService ServiceMask)
template<typename ModelDef>
void UnregisterInstance (FNetworkPredictionID ID)
Data Fields
TServiceStorage< IFinalizeService > FixedFinalize
TServiceStorage< IInputService > FixedInputLocal
TServiceStorage< IInputService > FixedInputRemote
TServiceStorage< IFixedInterpolateService > FixedInterpolate
TServiceStorage< IPhysicsService > FixedPhysics
TServiceStorage< IFixedRollbackService > FixedRollback
TServiceStorage< IFixedSmoothingService > FixedSmoothing
TServiceStorage< ILocalTickService > FixedTick
TServiceStorage< IIndependentInterpolateService > IndependentInterpolate
TServiceStorage< IFinalizeService > IndependentLocalFinalize
TServiceStorage< IInputService > IndependentLocalInput
TServiceStorage< ILocalTickService > IndependentLocalTick
TServiceStorage< IRemoteFinalizeService > IndependentRemoteFinalize
TServiceStorage< IRemoteIndependentTickService > IndependentRemoteTick
TServiceStorage< IIndependentRollbackService > IndependentRollback
TServiceStorage< IServerRPCService > ServerRPC
Private Member Functions
template<ENetworkPredictionService ServiceMask, typename ServiceType, typename FuncRefType, typename ServiceStorageType>
void ConditionalCallFuncOnService (ServiceStorageType &ServiceStorage, const FuncRefType &Func, ENetworkPredictionService Mask)
template<typename ModelDef = FNetworkPredictionModelDef, typename FuncRefType>
void ForEachService (ENetworkPredictionService Mask, const FuncRefType &Func)
template<typename ServiceType, typename ArrayType>
ServiceType * GetService_Internal (ArrayType &Array)
template<typename ModelDef>
void UnregisterInstance_Internal (FNetworkPredictionID ID, ENetworkPredictionService ServiceMask)
Private Attributes
TArray< TUniquePtr< IDataStore > > DataStoreArray
Detailed Description
Definition at line 72 of file NetworkPredictionServiceRegistry.h.
Member Function Documentation
ConditionalCallFuncOnService()
template<ENetworkPredictionService ServiceMask, typename ServiceType, typename FuncRefType, typename ServiceStorageType> void FNetworkPredictionServiceRegistry::ConditionalCallFuncOnService (ServiceStorageType & ServiceStorage, const FuncRefType & Func, ENetworkPredictionService Mask) inline private
Definition at line 217 of file NetworkPredictionServiceRegistry.h.
References EnumHasAllFlags(), GetDataStore(), MakeUnique(), Mask, and FSparseArrayAllocationInfo::Pointer.
ForEachService()
template<typename ModelDef = FNetworkPredictionModelDef, typename FuncRefType> void FNetworkPredictionServiceRegistry::ForEachService (ENetworkPredictionService Mask, const FuncRefType & Func) inline private
Definition at line 188 of file NetworkPredictionServiceRegistry.h.
References ANY_FIXED, ANY_INDEPENDENT, EnumHasAnyFlags(), FixedFinalize, FixedInputLocal, FixedInputRemote, FixedInterpolate, FixedPhysics, FixedRollback, FixedSmoothing, FixedTick, IndependentInterpolate, IndependentLocalFinalize, IndependentLocalInput, IndependentLocalTick, IndependentRemoteFinalize, IndependentRemoteTick, IndependentRollback, Mask, NP_DEFINE_SERVICE_CALL, and ServerRPC.
Referenced by RegisterInstance(), and UnregisterInstance_Internal().
GetDataStore()
template<typename ModelDef = FNetworkPredictionModelDef> TModelDataStore< ModelDef > * FNetworkPredictionServiceRegistry::GetDataStore () inline
Definition at line 127 of file NetworkPredictionServiceRegistry.h.
References DataStoreArray, Item, MakeUnique(), npEnsureMsgf, Self, and TEXT.
Referenced by ConditionalCallFuncOnService(), GetService_Internal(), and UnregisterInstance().
GetService_Internal()
template<typename ServiceType, typename ArrayType> ServiceType * FNetworkPredictionServiceRegistry::GetService_Internal (ArrayType & Array) inline private
Definition at line 241 of file NetworkPredictionServiceRegistry.h.
References Array, GetDataStore(), Item, npCheckf, FSparseArrayAllocationInfo::Pointer, and TEXT.
RegisterInstance()
template<typename ModelDef> void FNetworkPredictionServiceRegistry::RegisterInstance (FNetworkPredictionID ID, TInstanceData< ModelDef > & InstanceData, ENetworkPredictionService ServiceMask) inline
Definition at line 82 of file NetworkPredictionServiceRegistry.h.
References ANY_FIXED, ANY_INDEPENDENT, EnumHasAnyFlags(), ForEachService(), ID, None, npEnsureSlow, TInstanceData< ModelDef >::ServiceMask, and UnregisterInstance_Internal().
UnregisterInstance()
template<typename ModelDef> void FNetworkPredictionServiceRegistry::UnregisterInstance (FNetworkPredictionID ID) inline
Definition at line 112 of file NetworkPredictionServiceRegistry.h.
References GetDataStore(), ID, TModelDataStore< ModelDef >::Instances, Mask, None, TInstanceData< ModelDef >::ServiceMask, and UnregisterInstance_Internal().
UnregisterInstance_Internal()
template<typename ModelDef> void FNetworkPredictionServiceRegistry::UnregisterInstance_Internal (FNetworkPredictionID ID, ENetworkPredictionService ServiceMask) inline private
Definition at line 256 of file NetworkPredictionServiceRegistry.h.
References ForEachService(), and ID.
Referenced by RegisterInstance(), and UnregisterInstance().
Field Documentation
DataStoreArray
TArray<TUniquePtr<IDataStore> > FNetworkPredictionServiceRegistry::DataStoreArray private
Definition at line 269 of file NetworkPredictionServiceRegistry.h.
Referenced by GetDataStore().
FixedFinalize
TServiceStorage<IFinalizeService> FNetworkPredictionServiceRegistry::FixedFinalize
Definition at line 173 of file NetworkPredictionServiceRegistry.h.
Referenced by ForEachService().
FixedInputLocal
TServiceStorage<IInputService> FNetworkPredictionServiceRegistry::FixedInputLocal
Definition at line 170 of file NetworkPredictionServiceRegistry.h.
Referenced by ForEachService().
FixedInputRemote
TServiceStorage<IInputService> FNetworkPredictionServiceRegistry::FixedInputRemote
Definition at line 171 of file NetworkPredictionServiceRegistry.h.
Referenced by ForEachService().
FixedInterpolate
TServiceStorage<IFixedInterpolateService> FNetworkPredictionServiceRegistry::FixedInterpolate
Definition at line 169 of file NetworkPredictionServiceRegistry.h.
Referenced by ForEachService().
FixedPhysics
TServiceStorage<IPhysicsService> FNetworkPredictionServiceRegistry::FixedPhysics
Definition at line 174 of file NetworkPredictionServiceRegistry.h.
Referenced by ForEachService().
FixedRollback
TServiceStorage<IFixedRollbackService> FNetworkPredictionServiceRegistry::FixedRollback
Definition at line 168 of file NetworkPredictionServiceRegistry.h.
Referenced by ForEachService().
FixedSmoothing
TServiceStorage<IFixedSmoothingService> FNetworkPredictionServiceRegistry::FixedSmoothing
Definition at line 175 of file NetworkPredictionServiceRegistry.h.
Referenced by ForEachService().
FixedTick
TServiceStorage<ILocalTickService> FNetworkPredictionServiceRegistry::FixedTick
Definition at line 172 of file NetworkPredictionServiceRegistry.h.
Referenced by ForEachService().
IndependentInterpolate
TServiceStorage<IIndependentInterpolateService> FNetworkPredictionServiceRegistry::IndependentInterpolate
Definition at line 178 of file NetworkPredictionServiceRegistry.h.
Referenced by ForEachService().
IndependentLocalFinalize
TServiceStorage<IFinalizeService> FNetworkPredictionServiceRegistry::IndependentLocalFinalize
Definition at line 182 of file NetworkPredictionServiceRegistry.h.
Referenced by ForEachService().
IndependentLocalInput
TServiceStorage<IInputService> FNetworkPredictionServiceRegistry::IndependentLocalInput
Definition at line 179 of file NetworkPredictionServiceRegistry.h.
Referenced by ForEachService().
IndependentLocalTick
TServiceStorage<ILocalTickService> FNetworkPredictionServiceRegistry::IndependentLocalTick
Definition at line 180 of file NetworkPredictionServiceRegistry.h.
Referenced by ForEachService().
IndependentRemoteFinalize
TServiceStorage<IRemoteFinalizeService> FNetworkPredictionServiceRegistry::IndependentRemoteFinalize
Definition at line 183 of file NetworkPredictionServiceRegistry.h.
Referenced by ForEachService().
IndependentRemoteTick
TServiceStorage<IRemoteIndependentTickService> FNetworkPredictionServiceRegistry::IndependentRemoteTick
Definition at line 181 of file NetworkPredictionServiceRegistry.h.
Referenced by ForEachService().
IndependentRollback
TServiceStorage<IIndependentRollbackService> FNetworkPredictionServiceRegistry::IndependentRollback
Definition at line 177 of file NetworkPredictionServiceRegistry.h.
Referenced by ForEachService().
ServerRPC
TServiceStorage<IServerRPCService> FNetworkPredictionServiceRegistry::ServerRPC
Definition at line 166 of file NetworkPredictionServiceRegistry.h.
Referenced by ForEachService().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/NetworkPrediction/Source/NetworkPrediction/Public/Services/NetworkPredictionServiceRegistry.h