Unreal Engine 5.6 C++ API: TFunction< Ret(ParamTypes...)> Class Template Reference
TFunction< Ret(ParamTypes...)> Class Template Reference final
TFunction<FuncType>
#include "Function.h"
Public Member Functions
TFunction (const TFunction &Other)=default
template<typename FunctorType UE_REQUIRES>
TFunction (FunctorType &&InFunc)
Constructor which binds a TFunction to any function object.
TFunction (TFunction &&)=default
TFunction (TYPE_OF_NULLPTR=nullptr)
Default constructor.
~TFunction ()=default
FORCEINLINE bool IsSet () const
Tests if the TFunction is callable.
FORCEINLINE operator bool () const
Tests if the TFunction is callable.
FORCEINLINE bool operator!= (TYPE_OF_NULLPTR) const
Nullptr inequality operator.
TFunction & operator= (const TFunction &Other)
Copy assignment operator.
TFunction & operator= (TFunction &&Other)
Move assignment operator.
TFunction & operator= (TYPE_OF_NULLPTR)
Assignment to null is a form of Reset.
FORCEINLINE bool operator== (TYPE_OF_NULLPTR) const
Nullptr equality operator.
Private Types
using Super = UE::Core::Private::Function::TFunctionRefBase<UE::Core::Private::Function::TFunctionStorage<false>, Ret(ParamTypes...)>
Detailed Description
template<typename Ret, typename... ParamTypes>
class TFunction< Ret(ParamTypes...)>
TFunction<FuncType>
A class which represents a copy of something callable. FuncType represents a function type and so TFunction should be defined as follows:
// A function taking a string and float and returning int32. Parameter names are optional. TFunction<int32 (const FString& Name, float Scale)>
Unlike TFunctionRef, this object is intended to be used like a UE version of std::function. That is, it takes a copy of whatever is bound to it, meaning you can return it from functions and store them in objects without caring about the lifetime of the original object being bound.
Example:
// Something.h TFunction<FString (int32)> GetTransform();
// Something.cpp TFunction<FString (int32)> GetTransform(const FString& Prefix) { // Squares number and returns it as a string with the specified prefix return [=](int32 Num) { return Prefix + TEXT(": ") + TTypeToString<int32>::ToString(Num * Num); }; }
// SomewhereElse.cpp #include "Something.h"
void Func() { TFunction<FString (int32)> Transform = GetTransform(TEXT("Hello"));
FString Result = Transform(5); // "Hello: 25" }
Definition at line 707 of file Function.h.
Member Typedef Documentation
Super
template<typename Ret, typename... ParamTypes> using TFunction< Ret(ParamTypes...)>::Super = UE::Core::Private::Function::TFunctionRefBase<UE::Core::Private::Function::TFunctionStorage<false>, Ret(ParamTypes...)> private
Definition at line 709 of file Function.h.
Constructor & Destructor Documentation
TFunction() [1/4]
template<typename Ret, typename... ParamTypes> TFunction< Ret(ParamTypes...)>::TFunction (TYPE_OF_NULLPTR = nullptr) inline
Default constructor.
Definition at line 715 of file Function.h.
Referenced by TFunction(), TFunction(), operator=(), operator=(), and operator=().
TFunction() [2/4]
template<typename Ret, typename... ParamTypes> template<typename FunctorType UE_REQUIRES> TFunction< Ret(ParamTypes...)>::TFunction (FunctorType && InFunc) inline
Constructor which binds a TFunction to any function object.
Definition at line 729 of file Function.h.
References Core, Function, Private, and Value.
TFunction() [3/4]
template<typename Ret, typename... ParamTypes> TFunction< Ret(ParamTypes...)>::TFunction (TFunction< Ret(ParamTypes...)> &&) default
References TFunction().
TFunction() [4/4]
template<typename Ret, typename... ParamTypes> TFunction< Ret(ParamTypes...)>::TFunction (const TFunction< Ret(ParamTypes...)> & Other) default
References TFunction(), and Other.
~TFunction()
template<typename Ret, typename... ParamTypes> TFunction< Ret(ParamTypes...)>::~TFunction () default
Member Function Documentation
IsSet()
template<typename Ret, typename... ParamTypes> FORCEINLINE bool TFunction< Ret(ParamTypes...)>::IsSet () const inline
Tests if the TFunction is callable.
Definition at line 788 of file Function.h.
References FORCEINLINE.
operator bool()
template<typename Ret, typename... ParamTypes> FORCEINLINE TFunction< Ret(ParamTypes...)>::operator bool () const inline explicit
Tests if the TFunction is callable.
Definition at line 780 of file Function.h.
References FORCEINLINE.
operator!=()
template<typename Ret, typename... ParamTypes> FORCEINLINE bool TFunction< Ret(ParamTypes...)>::operator!= (TYPE_OF_NULLPTR) const inline
Nullptr inequality operator.
Definition at line 804 of file Function.h.
References FORCEINLINE.
operator=() [1/3]
template<typename Ret, typename... ParamTypes> TFunction & TFunction< Ret(ParamTypes...)>::operator= (const TFunction< Ret(ParamTypes...)> & Other) inline
Copy assignment operator.
Definition at line 761 of file Function.h.
References TFunction(), Other, and Swap.
operator=() [2/3]
template<typename Ret, typename... ParamTypes> TFunction & TFunction< Ret(ParamTypes...)>::operator= (TFunction< Ret(ParamTypes...)> && Other) inline
Move assignment operator.
Definition at line 752 of file Function.h.
References TFunction(), Other, and Swap.
operator=() [3/3]
template<typename Ret, typename... ParamTypes> TFunction & TFunction< Ret(ParamTypes...)>::operator= (TYPE_OF_NULLPTR) inline
Assignment to null is a form of Reset.
Definition at line 771 of file Function.h.
References TFunction().
operator==()
template<typename Ret, typename... ParamTypes> FORCEINLINE bool TFunction< Ret(ParamTypes...)>::operator== (TYPE_OF_NULLPTR) const inline
Nullptr equality operator.
Definition at line 796 of file Function.h.
References FORCEINLINE.
The documentation for this class was generated from the following file:
Runtime/Core/Public/Templates/Function.h