Unreal Engine 5.6 C++ API: TSparseArray< InElementType, Allocator >::TConstSubsetIterator< SubsetAllocator > Class Template Reference
TSparseArray< InElementType, Allocator >::TConstSubsetIterator< SubsetAllocator > Class Template Reference
An iterator which only iterates over the elements of the array which correspond to set bits in a separate bit array.
#include "SparseArray.h"
Public Member Functions
TConstSubsetIterator (const TSparseArray &InArray, const TBitArray< SubsetAllocator > &InBitArray)
FORCEINLINE int32 GetIndex () const
FORCEINLINE const FRelativeBitReference & GetRelativeBitReference () const
FORCEINLINE operator bool () const
conversion to "bool" returning true if the iterator is valid.
FORCEINLINE bool operator! () const
inverse of the "bool" operator
FORCEINLINE const ElementType & operator* () const
FORCEINLINE TConstSubsetIterator & operator++ ()
FORCEINLINE const ElementType * operator-> () const
Private Attributes
const TSparseArray & Array
TConstDualSetBitIterator< typename Allocator::BitArrayAllocator, SubsetAllocator > BitArrayIt
Detailed Description
template<typename InElementType, typename Allocator>
template<typename SubsetAllocator = FDefaultBitArrayAllocator>
class TSparseArray< InElementType, Allocator >::TConstSubsetIterator< SubsetAllocator >
An iterator which only iterates over the elements of the array which correspond to set bits in a separate bit array.
Definition at line 1123 of file SparseArray.h.
Constructor & Destructor Documentation
TConstSubsetIterator()
template<typename InElementType, typename Allocator> template<typename SubsetAllocator = FDefaultBitArrayAllocator> TSparseArray< InElementType, Allocator >::TConstSubsetIterator< SubsetAllocator >::TConstSubsetIterator (const TSparseArray & InArray, const TBitArray< SubsetAllocator > & InBitArray) inline nodiscard
Definition at line 1126 of file SparseArray.h.
References TSparseArray< InElementType, Allocator >::TSparseArray(), TSparseArray< InElementType, Allocator >::AllocationFlags, Array, and BitArrayIt.
Referenced by operator++().
Member Function Documentation
GetIndex()
template<typename InElementType, typename Allocator> template<typename SubsetAllocator = FDefaultBitArrayAllocator> FORCEINLINE int32 TSparseArray< InElementType, Allocator >::TConstSubsetIterator< SubsetAllocator >::GetIndex () const inline nodiscard
Definition at line 1137 of file SparseArray.h.
References BitArrayIt, and FORCEINLINE.
Referenced by operator*(), and operator->().
GetRelativeBitReference()
template<typename InElementType, typename Allocator> template<typename SubsetAllocator = FDefaultBitArrayAllocator> FORCEINLINE const FRelativeBitReference & TSparseArray< InElementType, Allocator >::TConstSubsetIterator< SubsetAllocator >::GetRelativeBitReference () const inline nodiscard
Definition at line 1161 of file SparseArray.h.
References BitArrayIt, and FORCEINLINE.
operator bool()
template<typename InElementType, typename Allocator> template<typename SubsetAllocator = FDefaultBitArrayAllocator> FORCEINLINE TSparseArray< InElementType, Allocator >::TConstSubsetIterator< SubsetAllocator >::operator bool () const inline explicit nodiscard
conversion to "bool" returning true if the iterator is valid.
Definition at line 1143 of file SparseArray.h.
References BitArrayIt, and FORCEINLINE.
operator!()
template<typename InElementType, typename Allocator> template<typename SubsetAllocator = FDefaultBitArrayAllocator> FORCEINLINE bool TSparseArray< InElementType, Allocator >::TConstSubsetIterator< SubsetAllocator >::operator! () const inline nodiscard
inverse of the "bool" operator
Definition at line 1148 of file SparseArray.h.
References bool, and FORCEINLINE.
operator*()
template<typename InElementType, typename Allocator> template<typename SubsetAllocator = FDefaultBitArrayAllocator> FORCEINLINE const ElementType & TSparseArray< InElementType, Allocator >::TConstSubsetIterator< SubsetAllocator >::operator* () const inline nodiscard
Definition at line 1153 of file SparseArray.h.
References Array, FORCEINLINE, and GetIndex().
operator++()
template<typename InElementType, typename Allocator> template<typename SubsetAllocator = FDefaultBitArrayAllocator> FORCEINLINE TConstSubsetIterator & TSparseArray< InElementType, Allocator >::TConstSubsetIterator< SubsetAllocator >::operator++ () inline
Definition at line 1131 of file SparseArray.h.
References TConstSubsetIterator(), BitArrayIt, and FORCEINLINE.
operator->()
template<typename InElementType, typename Allocator> template<typename SubsetAllocator = FDefaultBitArrayAllocator> FORCEINLINE const ElementType * TSparseArray< InElementType, Allocator >::TConstSubsetIterator< SubsetAllocator >::operator-> () const inline nodiscard
Definition at line 1157 of file SparseArray.h.
References Array, FORCEINLINE, and GetIndex().
Field Documentation
Array
template<typename InElementType, typename Allocator> template<typename SubsetAllocator = FDefaultBitArrayAllocator> const TSparseArray& TSparseArray< InElementType, Allocator >::TConstSubsetIterator< SubsetAllocator >::Array private
Definition at line 1166 of file SparseArray.h.
Referenced by TConstSubsetIterator(), operator*(), and operator->().
BitArrayIt
template<typename InElementType, typename Allocator> template<typename SubsetAllocator = FDefaultBitArrayAllocator> TConstDualSetBitIterator<typename Allocator::BitArrayAllocator,SubsetAllocator> TSparseArray< InElementType, Allocator >::TConstSubsetIterator< SubsetAllocator >::BitArrayIt private
Definition at line 1167 of file SparseArray.h.
Referenced by TConstSubsetIterator(), GetIndex(), GetRelativeBitReference(), operator bool(), and operator++().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Containers/SparseArray.h