Unreal Engine 5.6 C++ API: FSubsystemCollection< TBaseType > Class Template Reference
FSubsystemCollection< TBaseType > Class Template Reference
#include "SubsystemCollection.h"
Public Member Functions
FSubsystemCollection ()
Construct a FSubsystemCollection, pass in the owning object almost certainly (this).
virtual void AddReferencedObjects (FReferenceCollector &Collector) override
Pure virtual that must be overloaded by the inheriting class.
void ForEachSubsystem (TFunctionRef< void(TBaseType *)> Operation, const TSubclassOf< TBaseType > &SubsystemClass={}) const
Perform an operation on all subsystems of a given type in the collection.
virtual FString GetReferencerName () const override
Overload this method to report a name for your referencer.
template<typename TSubsystemClass>
TSubsystemClass * GetSubsystem (const TSubclassOf< TSubsystemClass > &SubsystemClass) const
Get a Subsystem by type.
template<typename TSubsystemClass>
TArray< TSubsystemClass * > GetSubsystemArrayCopy (const TSubclassOf< TSubsystemClass > &SubsystemClass) const
Get a list of Subsystems by type.
template<typename TSubsystemClass>
UE_DEPRECATED (5.4, "This function is unsafe for re-entrancy and has been deprecated. Use ForEachSubsystem or GetSubsystemArrayCopy instead") const TArray< TSubsystemClass * > &GetSubsystemArray(const TSubclassOf< TSubsystemClass > &SubsystemClass) const
Get a list of Subsystems by type.
Public Member Functions inherited from FSubsystemCollectionBase
void AddReferencedObjects (UObject *Referencer, FReferenceCollector &Collector)
Collect references held by this collection.
void Deinitialize ()
const UClass * GetBaseType () const
Get the collection BaseType.
void Initialize (UObject *NewOuter)
Initialize the collection of systems, systems will be created and initialized.
template<typename TSubsystemClass>
TSubsystemClass * InitializeDependency ()
Only call from Initialize() of Systems to ensure initialization order Note: Dependencies only work within a collection.
USubsystem * InitializeDependency (TSubclassOf< USubsystem > SubsystemClass)
Only call from Initialize() of Systems to ensure initialization order Note: Dependencies only work within a collection.
bool IsInitialized () const
Returns true if collection was already initialized.
Public Member Functions inherited from FGCObject
FGCObject ()
Tells the global object that forwards AddReferencedObjects calls on to objects that a new object is requiring AddReferencedObjects call.
FGCObject (const FGCObject &Other)
FGCObject (EFlags Flags)
FGCObject (FGCObject &&Other)
virtual ~FGCObject ()
virtual bool GetReferencerPropertyName (UObject *Object, FString &OutPropertyName) const
Overload this method to report how the specified object is referenced, if necessary.
FGCObject & operator= (const FGCObject &)
FGCObject & operator= (FGCObject &&)
void RegisterGCObject ()
Register with GC, only needed if constructed with EFlags::RegisterLater or after unregistering.
void UnregisterGCObject ()
Unregister ahead of destruction.
Additional Inherited Members
Public Types inherited from FGCObject
enum class EFlags : uint32 { None = 0 , RegisterLater = 1 << 0 , AddStableNativeReferencesOnly = 1 << 1 }
Static Public Member Functions inherited from FSubsystemCollectionBase
static void ActivateExternalSubsystem (UClass *SubsystemClass)
Registers and adds instances of the specified Subsystem class to all existing SubsystemCollections of the correct type.
static void DeactivateExternalSubsystem (UClass *SubsystemClass)
Unregisters and removed instances of the specified Subsystem class from all existing SubsystemCollections of the correct type.
Static Public Member Functions inherited from FGCObject
static void StaticInit ()
Initializes the global object referencer and adds it to the root set.
Static Public Attributes inherited from FGCObject
static UGCObjectReferencer * GGCObjectReferencer
The static object referencer object that is shared across all garbage collectible non-UObject objects.
Protected Member Functions inherited from FSubsystemCollectionBase
FSubsystemCollectionBase ()
protected constructor - Use the FSubsystemCollection<TBaseType> class
FSubsystemCollectionBase (UClass *InBaseType)
protected constructor - for use by the template only(FSubsystemCollection<TBaseType>)
virtual ~FSubsystemCollectionBase ()
destructor will be called from virtual ~FGCObject in GC cleanup
FSubsystemArray & FindAndPopulateSubsystemArrayInternal (UClass *SubsystemClass) const
void ForEachSubsystem (TFunctionRef< void(USubsystem *)> Operation) const
Run the given operation on each registered subsystem.
void ForEachSubsystemOfClass (UClass *SubsystemClass, TFunctionRef< void(USubsystem *)> Operation) const
Perform an operation on all subsystems that derive from the given class.
TArray< USubsystem * > GetSubsystemArrayCopy (UClass *SubsystemClass) const
Get a list of Subsystems by type.
USubsystem * GetSubsystemInternal (UClass *SubsystemClass) const
Get a Subsystem by type.
UE_DEPRECATED (5.4, "This function is unsafe for re-entrancy and has been deprecated. Use ForEachSubsystemOfClass or GetSubsystemArrayCopy instead") 1 const TArray< USubsystem * > &GetSubsystemArrayInternal(UClass *SubsystemClass) const
Get a list of Subsystems by type.
Detailed Description
template<typename TBaseType>
class FSubsystemCollection< TBaseType >
Definition at line 123 of file SubsystemCollection.h.
Constructor & Destructor Documentation
FSubsystemCollection()
template<typename TBaseType> FSubsystemCollection< TBaseType >::FSubsystemCollection () inline
Construct a FSubsystemCollection, pass in the owning object almost certainly (this).
Definition at line 183 of file SubsystemCollection.h.
References FSubsystemCollectionBase::FSubsystemCollectionBase(), and StaticClass().
Member Function Documentation
AddReferencedObjects()
template<typename TBaseType> virtual void FSubsystemCollection< TBaseType >::AddReferencedObjects (FReferenceCollector & Collector) inline override virtual
Pure virtual that must be overloaded by the inheriting class.
Use this method to serialize any UObjects contained that you wish to keep around.
Parameters
Collector The collector of referenced objects.
Implements FGCObject.
Definition at line 170 of file SubsystemCollection.h.
References FSubsystemCollectionBase::AddReferencedObjects().
ForEachSubsystem()
template<typename TBaseType> void FSubsystemCollection< TBaseType >::ForEachSubsystem (TFunctionRef< void(TBaseType *)> Operation, const TSubclassOf< TBaseType > & SubsystemClass = {}) const inline
Perform an operation on all subsystems of a given type in the collection.
Definition at line 161 of file SubsystemCollection.h.
GetReferencerName()
template<typename TBaseType> virtual FString FSubsystemCollection< TBaseType >::GetReferencerName () const inline override virtual
Overload this method to report a name for your referencer.
Implements FGCObject.
Definition at line 175 of file SubsystemCollection.h.
References TEXT.
GetSubsystem()
template<typename TBaseType> template<typename TSubsystemClass> TSubsystemClass * FSubsystemCollection< TBaseType >::GetSubsystem (const TSubclassOf< TSubsystemClass > & SubsystemClass) const inline
Get a Subsystem by type.
Definition at line 128 of file SubsystemCollection.h.
References FSubsystemCollectionBase::GetSubsystemInternal(), and TIsDerivedFrom< DerivedType, BaseType >::IsDerived.
GetSubsystemArrayCopy()
template<typename TBaseType> template<typename TSubsystemClass> TArray< TSubsystemClass * > FSubsystemCollection< TBaseType >::GetSubsystemArrayCopy (const TSubclassOf< TSubsystemClass > & SubsystemClass) const inline
Get a list of Subsystems by type.
Definition at line 151 of file SubsystemCollection.h.
References Array, and FSubsystemCollectionBase::FindAndPopulateSubsystemArrayInternal().
UE_DEPRECATED()
template<typename TBaseType> template<typename TSubsystemClass> FSubsystemCollection< TBaseType >::UE_DEPRECATED (5. 4, "This function is unsafe for re-entrancy and has been deprecated. Use ForEachSubsystem or GetSubsystemArrayCopy instead") const & inline
Get a list of Subsystems by type.
Definition at line 138 of file SubsystemCollection.h.
References Array, and FSubsystemCollectionBase::FindAndPopulateSubsystemArrayInternal().
The documentation for this class was generated from the following file:
Runtime/Engine/Public/Subsystems/SubsystemCollection.h