Unreal Engine 5.6 C++ API: UE::MovieScene::TMovieSceneMaterialSystem< AccessorType, RequiredComponents > Class Template Reference
UE::MovieScene::TMovieSceneMaterialSystem< AccessorType, RequiredComponents > Class Template Reference
#include "MovieSceneMaterialSystem.h"
Data Structures
struct FMaterialGroupingPolicy
Public Types
using MaterialParameterStorageType = TPreAnimatedStateStorage<TPreAnimatedMaterialParameterTraits<AccessorType, RequiredComponents...>>
using MaterialSwitcherStorageType = TPreAnimatedStateStorage<TPreAnimatedMaterialTraits<AccessorType, RequiredComponents...>>
Public Member Functions
void OnLink (UMovieSceneEntitySystemLinker *Linker, TComponentTypeID< RequiredComponents >... InRequiredComponents)
void OnPostSpawn (UMovieSceneEntitySystemLinker *InLinker, TComponentTypeID< RequiredComponents >... InRequiredComponents)
void OnRun (UMovieSceneEntitySystemLinker *Linker, TComponentTypeID< RequiredComponents >... InRequiredComponents, FSystemTaskPrerequisites &InPrerequisites, FSystemSubsequentTasks &Subsequents)
void OnUnlink (UMovieSceneEntitySystemLinker *Linker)
void SavePreAnimatedState (UMovieSceneEntitySystemLinker *Linker, TComponentTypeID< RequiredComponents >... InRequiredComponents, const IMovieScenePreAnimatedStateSystemInterface::FPreAnimationParameters &InParameters)
Data Fields
TSharedPtr< MaterialParameterStorageType > MaterialParameterStorage
TSharedPtr< MaterialSwitcherStorageType > MaterialSwitcherStorage
Protected Attributes
UE::MovieScene::FEntityGroupingPolicyKey GroupingKey
FEntityComponentFilter MaterialParameterFilter
FEntityComponentFilter MaterialSwitcherFilter
FCachedEntityFilterResult_Allocations ReinitializeBoundMaterials
Detailed Description
template<typename AccessorType, typename... RequiredComponents>
class UE::MovieScene::TMovieSceneMaterialSystem< AccessorType, RequiredComponents >
Definition at line 88 of file MovieSceneMaterialSystem.h.
Member Typedef Documentation
MaterialParameterStorageType
template<typename AccessorType, typename... RequiredComponents> using UE::MovieScene::TMovieSceneMaterialSystem< AccessorType, RequiredComponents >::MaterialParameterStorageType = TPreAnimatedStateStorage<TPreAnimatedMaterialParameterTraits<AccessorType, RequiredComponents...>>
Definition at line 93 of file MovieSceneMaterialSystem.h.
MaterialSwitcherStorageType
template<typename AccessorType, typename... RequiredComponents> using UE::MovieScene::TMovieSceneMaterialSystem< AccessorType, RequiredComponents >::MaterialSwitcherStorageType = TPreAnimatedStateStorage<TPreAnimatedMaterialTraits<AccessorType, RequiredComponents...>>
Definition at line 92 of file MovieSceneMaterialSystem.h.
Member Function Documentation
OnLink()
template<typename AccessorType, typename... RequiredComponents> void UE::MovieScene::TMovieSceneMaterialSystem< AccessorType, RequiredComponents >::OnLink (UMovieSceneEntitySystemLinker * Linker, TComponentTypeID< RequiredComponents >... InRequiredComponents)
Definition at line 351 of file MovieSceneMaterialSystem.h.
References UE::MovieScene::FMovieSceneTracksComponentTypes::BoundMaterial, UE::MovieScene::FMovieSceneTracksComponentTypes::ColorMaterialParameterInfo, UE::MovieScene::FMovieSceneTracksComponentTypes::ColorParameterName, UE::MovieScene::FBuiltInComponentTypes::Get(), UE::MovieScene::FMovieSceneTracksComponentTypes::Get(), GroupingKey, MaterialParameterFilter, MaterialSwitcherFilter, UE::MovieScene::FBuiltInComponentTypes::NeedsUnlink, UE::MovieScene::FBuiltInComponentTypes::ObjectResult, OnPostSpawn(), ReinitializeBoundMaterials, UE::MovieScene::FMovieSceneTracksComponentTypes::ScalarMaterialParameterInfo, UE::MovieScene::FMovieSceneTracksComponentTypes::ScalarParameterName, UE::MovieScene::FBuiltInComponentTypes::Tags, UE::MovieScene::FMovieSceneTracksComponentTypes::VectorMaterialParameterInfo, and UE::MovieScene::FMovieSceneTracksComponentTypes::VectorParameterName.
OnPostSpawn()
template<typename AccessorType, typename... RequiredComponents> void UE::MovieScene::TMovieSceneMaterialSystem< AccessorType, RequiredComponents >::OnPostSpawn (UMovieSceneEntitySystemLinker * InLinker, TComponentTypeID< RequiredComponents >... InRequiredComponents)
Definition at line 392 of file MovieSceneMaterialSystem.h.
References UE::MovieScene::FMovieSceneTracksComponentTypes::BoundMaterial, UE::MovieScene::FMovieSceneTracksComponentTypes::Get(), Num, ReinitializeBoundMaterials, and SCOPE_CYCLE_COUNTER.
Referenced by OnLink().
OnRun()
template<typename AccessorType, typename... RequiredComponents> void UE::MovieScene::TMovieSceneMaterialSystem< AccessorType, RequiredComponents >::OnRun (UMovieSceneEntitySystemLinker * Linker, TComponentTypeID< RequiredComponents >... InRequiredComponents, FSystemTaskPrerequisites & InPrerequisites, FSystemSubsequentTasks & Subsequents)
Definition at line 417 of file MovieSceneMaterialSystem.h.
References UE::MovieScene::FMovieSceneTracksComponentTypes::BoundMaterial, Filter, UE::MovieScene::TEntityTaskComponents< T >::FilterAll(), UE::MovieScene::FBuiltInComponentTypes::Get(), UE::MovieScene::FMovieSceneTracksComponentTypes::Get(), UE::MovieScene::FBuiltInComponentTypes::Ignored, UE::MovieScene::FBuiltInComponentTypes::ImportedEntity, MaterialParameterFilter, UE::MovieScene::FBuiltInComponentTypes::NeedsLink, UE::MovieScene::FBuiltInComponentTypes::NeedsUnlink, UE::MovieScene::FBuiltInComponentTypes::ObjectResult, and UE::MovieScene::FBuiltInComponentTypes::Tags.
OnUnlink()
template<typename AccessorType, typename... RequiredComponents> void UE::MovieScene::TMovieSceneMaterialSystem< AccessorType, RequiredComponents >::OnUnlink (UMovieSceneEntitySystemLinker * Linker)
Definition at line 379 of file MovieSceneMaterialSystem.h.
References ensure, and GroupingKey.
SavePreAnimatedState()
template<typename AccessorType, typename... RequiredComponents> void UE::MovieScene::TMovieSceneMaterialSystem< AccessorType, RequiredComponents >::SavePreAnimatedState (UMovieSceneEntitySystemLinker * Linker, TComponentTypeID< RequiredComponents >... InRequiredComponents, const IMovieScenePreAnimatedStateSystemInterface::FPreAnimationParameters & InParameters)
Definition at line 464 of file MovieSceneMaterialSystem.h.
References MaterialParameterFilter, MaterialParameterStorage, MaterialSwitcherFilter, MaterialSwitcherStorage, and Params.
Field Documentation
GroupingKey
template<typename AccessorType, typename... RequiredComponents> UE::MovieScene::FEntityGroupingPolicyKey UE::MovieScene::TMovieSceneMaterialSystem< AccessorType, RequiredComponents >::GroupingKey protected
Definition at line 184 of file MovieSceneMaterialSystem.h.
Referenced by OnLink(), and OnUnlink().
MaterialParameterFilter
template<typename AccessorType, typename... RequiredComponents> FEntityComponentFilter UE::MovieScene::TMovieSceneMaterialSystem< AccessorType, RequiredComponents >::MaterialParameterFilter protected
Definition at line 187 of file MovieSceneMaterialSystem.h.
Referenced by OnLink(), OnRun(), and SavePreAnimatedState().
MaterialParameterStorage
template<typename AccessorType, typename... RequiredComponents> TSharedPtr<MaterialParameterStorageType> UE::MovieScene::TMovieSceneMaterialSystem< AccessorType, RequiredComponents >::MaterialParameterStorage
Definition at line 96 of file MovieSceneMaterialSystem.h.
Referenced by SavePreAnimatedState().
MaterialSwitcherFilter
template<typename AccessorType, typename... RequiredComponents> FEntityComponentFilter UE::MovieScene::TMovieSceneMaterialSystem< AccessorType, RequiredComponents >::MaterialSwitcherFilter protected
Definition at line 186 of file MovieSceneMaterialSystem.h.
Referenced by OnLink(), and SavePreAnimatedState().
MaterialSwitcherStorage
template<typename AccessorType, typename... RequiredComponents> TSharedPtr<MaterialSwitcherStorageType> UE::MovieScene::TMovieSceneMaterialSystem< AccessorType, RequiredComponents >::MaterialSwitcherStorage
Definition at line 95 of file MovieSceneMaterialSystem.h.
Referenced by SavePreAnimatedState().
ReinitializeBoundMaterials
template<typename AccessorType, typename... RequiredComponents> FCachedEntityFilterResult_Allocations UE::MovieScene::TMovieSceneMaterialSystem< AccessorType, RequiredComponents >::ReinitializeBoundMaterials protected
Definition at line 189 of file MovieSceneMaterialSystem.h.
Referenced by OnLink(), and OnPostSpawn().
The documentation for this class was generated from the following file:
Runtime/MovieSceneTracks/Public/Systems/MovieSceneMaterialSystem.h