Unreal Engine 5.6 C++ API: FGrowableMallocChunk Class Reference
FGrowableMallocChunk Class Reference abstract
#include "GenericGrowableAllocator.h"
Data Structures
class FFreeEntry
Public Member Functions
FGrowableMallocChunk (uint64 InSize, uint32 Type, FCriticalSection *InCriticalSection)
Constructor.
virtual ~FGrowableMallocChunk ()
Destructor.
bool CanFitEntry (uint32 Size, uint32 Alignment)
Check free list for an entry big enough to fit the requested Size with Alignment.
virtual FGrowableAllocationBase * CreateAllocationStruct ()=0
Creates an implementation specific subclass of FGrowableAllocationBase.
virtual uint64 CreateInternalMemory (uint64 Size)=0
Lets the implementation allocate the backing memory for the chunk.
void Destroy ()
virtual void DestroyAllocationStruct (FGrowableAllocationBase *Allocation)
Destroys the implemtnation object.
virtual void DestroyInternalMemory ()=0
Destroys the backing memory for the chunk.
virtual bool DoesChunkContainAddress (const void *Address)=0
Queries the implementation if the given address came from this chunk.
virtual bool DoesChunkContainAllocation (const FGrowableAllocationBase *Allocation)=0
Queries the implementation if the given allocation came from this chunk.
bool Free (FGrowableAllocationBase *Memory)
virtual void * GetAddressForTracking (uint32 Offset)=0
void GetAllocationInfo (uint64 &Used, uint64 &Free)
void Initialize ()
virtual void InitializeAllocationStruct (FGrowableAllocationBase *Allocation)=0
Lets the implementation fill in any specific fields of the allocation struct after the base fields are set up.
bool IsEmpty ()
FGrowableAllocationBase * Malloc (uint32 Size, uint32 Alignment, uint32 MinAllocationSize, int32 OwnerType)
void ShowFullAllocationList ()
Public Member Functions inherited from FGrowableMallocBase
FGrowableMallocBase ()
Constructor.
virtual ~FGrowableMallocBase ()
virtual uint64 GetWasteApproximation ()
Returns approximated amount of memory wasted due to allocations' alignment.
Data Fields
FCriticalSection * CriticalSection
Shared critical section.
FFreeEntry * FreeList
List of free blocks.
uint64 HeapSize
Size of the heap.
uint32 MaxFreeEntrySize
Size of the largest free entry (will be MaxFreeEntrySizeDirty if unknown)
uint32 MemoryType
uint64 UsedMemorySize
Size of used memory.
Static Public Attributes
static const uint32 MaxFreeEntrySizeDirty = 0xffffffff
Additional Inherited Members
Protected Attributes inherited from FGrowableMallocBase
uint64 CurrentAllocs
The current number of allocations.
uint64 TotalAllocated
Total amount ever allocated.
uint64 TotalAllocs
The total number of allocations.
uint64 TotalWaste
The total amount of memory wasted due to allocations' alignment.
Detailed Description
Definition at line 77 of file GenericGrowableAllocator.h.
Constructor & Destructor Documentation
FGrowableMallocChunk()
FGrowableMallocChunk::FGrowableMallocChunk (uint64 InSize, uint32 Type, FCriticalSection * InCriticalSection) inline
Constructor.
Definition at line 133 of file GenericGrowableAllocator.h.
References CriticalSection, HeapSize, MaxFreeEntrySize, MaxFreeEntrySizeDirty, MemoryType, and UsedMemorySize.
~FGrowableMallocChunk()
virtual FGrowableMallocChunk::~FGrowableMallocChunk () inline virtual
Destructor.
Definition at line 154 of file GenericGrowableAllocator.h.
Member Function Documentation
CanFitEntry()
bool FGrowableMallocChunk::CanFitEntry (uint32 Size, uint32 Alignment) inline
Check free list for an entry big enough to fit the requested Size with Alignment.
Parameters
Size - allocation size
Alignment - allocation alignment
Returns
true if available entry was found
Definition at line 170 of file GenericGrowableAllocator.h.
References FreeList, FMath::Max, MaxFreeEntrySize, MaxFreeEntrySizeDirty, and TSequenceHistory< HistorySize >::Size.
CreateAllocationStruct()
virtual FGrowableAllocationBase * FGrowableMallocChunk::CreateAllocationStruct () pure virtual
Creates an implementation specific subclass of FGrowableAllocationBase.
Does not need to be initialized (see InitializeAllocationStruct)
Referenced by Malloc().
CreateInternalMemory()
virtual uint64 FGrowableMallocChunk::CreateInternalMemory (uint64 Size) pure virtual
Lets the implementation allocate the backing memory for the chunk.
Implementation needs to pause LLM tracking for ELLMTracker::Default if it's allocating from an allocator that tracks via ELLMTracker::Default
Parameters
Size Minimum size needed for this allocation. The implementation will likely allocate more, and return that amount
Returns
The actual size of the chunk that was allocated (could be much larger than Size)
References TSequenceHistory< HistorySize >::Size.
Referenced by Initialize().
Destroy()
void FGrowableMallocChunk::Destroy () inline
Definition at line 158 of file GenericGrowableAllocator.h.
References checkf, DestroyInternalMemory(), IsEmpty(), and TEXT.
DestroyAllocationStruct()
virtual void FGrowableMallocChunk::DestroyAllocationStruct (FGrowableAllocationBase * Allocation) inline virtual
Destroys the implemtnation object.
By default, just deletes it
Definition at line 108 of file GenericGrowableAllocator.h.
Referenced by Free().
DestroyInternalMemory()
virtual void FGrowableMallocChunk::DestroyInternalMemory () pure virtual
Destroys the backing memory for the chunk.
Implementation needs to pause LLM tracking for ELLMTracker::Default if it's allocating from an allocator that tracks via ELLMTracker::Default
Referenced by Destroy().
DoesChunkContainAddress()
virtual bool FGrowableMallocChunk::DoesChunkContainAddress (const void * Address) pure virtual
Queries the implementation if the given address came from this chunk.
DoesChunkContainAllocation()
virtual bool FGrowableMallocChunk::DoesChunkContainAllocation (const FGrowableAllocationBase * Allocation) pure virtual
Queries the implementation if the given allocation came from this chunk.
Free()
bool FGrowableMallocChunk::Free (FGrowableAllocationBase * Memory) inline
Definition at line 283 of file GenericGrowableAllocator.h.
References FGrowableMallocChunk::FFreeEntry::BlockSize, CriticalSection, FGrowableMallocBase::CurrentAllocs, DestroyAllocationStruct(), FreeList, GetAddressForTracking(), LLM_IF_ENABLED, FGrowableMallocChunk::FFreeEntry::Location, FMath::Max, MaxFreeEntrySize, Memory, MemoryTrace_Free(), FGrowableMallocChunk::FFreeEntry::Next, Padding, SystemMemory, TSequenceHistory< HistorySize >::Size, and UsedMemorySize.
Referenced by GetAllocationInfo().
GetAddressForTracking()
virtual void * FGrowableMallocChunk::GetAddressForTracking (uint32 Offset) pure virtual
Referenced by Free(), and Malloc().
GetAllocationInfo()
void FGrowableMallocChunk::GetAllocationInfo (uint64 & Used, uint64 & Free) inline
Definition at line 358 of file GenericGrowableAllocator.h.
References Free(), HeapSize, and UsedMemorySize.
Initialize()
void FGrowableMallocChunk::Initialize () inline
Definition at line 142 of file GenericGrowableAllocator.h.
References CreateInternalMemory(), FreeList, HeapSize, and MaxFreeEntrySize.
InitializeAllocationStruct()
virtual void FGrowableMallocChunk::InitializeAllocationStruct (FGrowableAllocationBase * Allocation) pure virtual
Lets the implementation fill in any specific fields of the allocation struct after the base fields are set up.
Referenced by Malloc().
IsEmpty()
bool FGrowableMallocChunk::IsEmpty () inline
Returns
true if this chunk has no used memory
Definition at line 209 of file GenericGrowableAllocator.h.
References UsedMemorySize.
Referenced by Destroy().
Malloc()
FGrowableAllocationBase * FGrowableMallocChunk::Malloc (uint32 Size, uint32 Alignment, uint32 MinAllocationSize, int32 OwnerType) inline
Definition at line 214 of file GenericGrowableAllocator.h.
References Align, FGrowableMallocChunk::FFreeEntry::BlockSize, checkSlow, CreateAllocationStruct(), CriticalSection, FGrowableMallocBase::CurrentAllocs, FreeList, GetAddressForTracking(), InitializeAllocationStruct(), LLM_IF_ENABLED, FGenericPlatformMisc::LowLevelOutputDebugStringf(), MaxFreeEntrySize, MaxFreeEntrySizeDirty, MemoryTrace_Alloc(), FGrowableMallocChunk::FFreeEntry::Next, FGrowableAllocationBase::Offset, FGrowableAllocationBase::OwnerType, Padding, FGrowableAllocationBase::Padding, FGrowableAllocationBase::Size, FGrowableMallocChunk::FFreeEntry::Split(), SystemMemory, TEXT, FGrowableMallocBase::TotalAllocs, FGrowableMallocBase::TotalWaste, TSequenceHistory< HistorySize >::Size, and UsedMemorySize.
ShowFullAllocationList()
void FGrowableMallocChunk::ShowFullAllocationList () inline
Definition at line 365 of file GenericGrowableAllocator.h.
References TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Add(), FGrowableMallocChunk::FFreeEntry::BlockSize, TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Contains(), Count, TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::CreateIterator(), TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::FindChecked(), FreeList, FGrowableMallocChunk::FFreeEntry::Location, FGenericPlatformMisc::LowLevelOutputDebugStringf(), FGrowableMallocChunk::FFreeEntry::Next, and TEXT.
Field Documentation
CriticalSection
FCriticalSection* FGrowableMallocChunk::CriticalSection
Shared critical section.
Definition at line 502 of file GenericGrowableAllocator.h.
Referenced by FGrowableMallocChunk(), Free(), and Malloc().
FreeList
FFreeEntry* FGrowableMallocChunk::FreeList
List of free blocks.
Definition at line 499 of file GenericGrowableAllocator.h.
Referenced by CanFitEntry(), Free(), Initialize(), Malloc(), and ShowFullAllocationList().
HeapSize
uint64 FGrowableMallocChunk::HeapSize
Size of the heap.
Definition at line 490 of file GenericGrowableAllocator.h.
Referenced by FGrowableMallocChunk(), GetAllocationInfo(), and Initialize().
MaxFreeEntrySize
uint32 FGrowableMallocChunk::MaxFreeEntrySize
Size of the largest free entry (will be MaxFreeEntrySizeDirty if unknown)
Definition at line 496 of file GenericGrowableAllocator.h.
Referenced by FGrowableMallocChunk(), CanFitEntry(), Free(), Initialize(), and Malloc().
MaxFreeEntrySizeDirty
const uint32 FGrowableMallocChunk::MaxFreeEntrySizeDirty = 0xffffffff static
Definition at line 504 of file GenericGrowableAllocator.h.
Referenced by FGrowableMallocChunk(), CanFitEntry(), and Malloc().
MemoryType
uint32 FGrowableMallocChunk::MemoryType
Definition at line 487 of file GenericGrowableAllocator.h.
Referenced by FGrowableMallocChunk().
UsedMemorySize
uint64 FGrowableMallocChunk::UsedMemorySize
Size of used memory.
Definition at line 493 of file GenericGrowableAllocator.h.
Referenced by FGrowableMallocChunk(), Free(), GetAllocationInfo(), IsEmpty(), and Malloc().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Misc/GenericGrowableAllocator.h