Unreal Engine 5.6 C++ API: FNetControlMessageInfo Class Reference
FNetControlMessageInfo Class Reference
contains info about a message type retrievable without static binding (e.g.
#include "DataChannel.h"
Static Public Member Functions
static const TCHAR * GetName (uint8 MessageIndex)
static bool IsRegistered (uint8 MessageIndex)
Static Private Member Functions
static void CheckInitialized ()
template<typename FirstParamType, typename... ParamTypes>
static void ReceiveParams (FInBunch &Bunch, FirstParamType &FirstParam, ParamTypes &... Params)
template<typename... ParamTypes>
static void ReceiveParams (FInBunch &Bunch, ParamTypes &... Params)
template<typename FirstParamType, typename... ParamTypes>
static void SendParams (FControlChannelOutBunch &Bunch, FirstParamType &FirstParam, ParamTypes &... Params)
template<typename... ParamTypes>
static void SendParams (FControlChannelOutBunch &Bunch, ParamTypes &... Params)
static void SetName (uint8 MessageType, const TCHAR *InName)
Static Private Attributes
static bool bInitialized
static constexpr int MaxNames = TNumericLimits<uint8>::Max() + 1
static const TCHAR * Names [MaxNames]
Friends
template<int32 Index, typename... ParamTypes>
class UE::Net::TNetControlMessageImpl
Detailed Description
contains info about a message type retrievable without static binding (e.g.
whether it's a valid type, friendly name string, etc)
Definition at line 45 of file DataChannel.h.
Member Function Documentation
CheckInitialized()
void FNetControlMessageInfo::CheckInitialized () inline static private
Definition at line 60 of file DataChannel.h.
References bInitialized, Names, TEXT, and UE_ARRAY_COUNT.
Referenced by GetName(), IsRegistered(), and SetName().
GetName()
const TCHAR * FNetControlMessageInfo::GetName (uint8 MessageIndex) inline static
Definition at line 48 of file DataChannel.h.
References CheckInitialized(), and Names.
IsRegistered()
bool FNetControlMessageInfo::IsRegistered (uint8 MessageIndex) inline static
Definition at line 53 of file DataChannel.h.
References CheckInitialized(), and Names.
ReceiveParams() [1/2]
template<typename FirstParamType, typename... ParamTypes> void FNetControlMessageInfo::ReceiveParams (FInBunch & Bunch, FirstParamType & FirstParam, ParamTypes &... Params) inline static private
Definition at line 91 of file DataChannel.h.
References Params, and ReceiveParams().
ReceiveParams() [2/2]
template<typename... ParamTypes> void FNetControlMessageInfo::ReceiveParams (FInBunch & Bunch, ParamTypes &... Params) inline static private
Definition at line 88 of file DataChannel.h.
References Params.
Referenced by UE::Net::TNetControlMessageImpl< Index, ParamTypes >::Receive(), and ReceiveParams().
SendParams() [1/2]
template<typename FirstParamType, typename... ParamTypes> void FNetControlMessageInfo::SendParams (FControlChannelOutBunch & Bunch, FirstParamType & FirstParam, ParamTypes &... Params) inline static private
Definition at line 81 of file DataChannel.h.
References Params, and SendParams().
SendParams() [2/2]
template<typename... ParamTypes> void FNetControlMessageInfo::SendParams (FControlChannelOutBunch & Bunch, ParamTypes &... Params) inline static private
Definition at line 78 of file DataChannel.h.
References Params.
Referenced by UE::Net::TNetControlMessageImpl< Index, ParamTypes >::Send(), and SendParams().
SetName()
void FNetControlMessageInfo::SetName (uint8 MessageType, const TCHAR * InName) inline static private
Definition at line 71 of file DataChannel.h.
References CheckInitialized(), InName, and Names.
Referenced by UE::Net::TNetControlMessageImpl< Index, ParamTypes >::Initialize().
Friends And Related Symbol Documentation
UE::Net::TNetControlMessageImpl
template<int32 Index, typename... ParamTypes> friend class UE::Net::TNetControlMessageImpl friend
Definition at line 58 of file DataChannel.h.
Field Documentation
bInitialized
bool FNetControlMessageInfo::bInitialized static private
Definition at line 99 of file DataChannel.h.
Referenced by CheckInitialized().
MaxNames
int FNetControlMessageInfo::MaxNames = TNumericLimits<uint8>::Max() + 1 static constexpr private
Definition at line 97 of file DataChannel.h.
Referenced by UE::Net::TNetControlMessageImpl< Index, ParamTypes >::Send().
Names
const TCHAR* FNetControlMessageInfo::Names[MaxNames] static private
Definition at line 98 of file DataChannel.h.
Referenced by CheckInitialized(), GetName(), IsRegistered(), and SetName().
The documentation for this class was generated from the following file:
Runtime/Engine/Public/Net/DataChannel.h