Unreal Engine 5.6 C++ API: AEmitter Class Reference
AEmitter Class Reference
#include "Emitter.h"
Public Member Functions
void AutoPopulateInstanceProperties ()
virtual void CheckForErrors () override
virtual FString GetDetailedInfoInternal () const override
class UParticleSystemComponent * GetParticleSystemComponent ()
Returns ParticleSystemComponent subobject.
virtual bool GetReferencedContentObjects (TArray< UObject * > &Objects) const override
virtual void PostActorCreated () override
virtual void PostInitializeComponents () override
void ResetInLevel ()
Called to reset the emitter actor in the level.
UFUNCTION () 1 virtual void OnParticleSystemFinished(class UParticleSystemComponent *FinishedComponent)
UFUNCTION () 1 virtual void OnRep_bCurrentlyActive()
Replication Notification Callbacks.
UFUNCTION ()) 1 bool IsActive() const
UFUNCTION ()) 1 virtual void SetTemplate(class UParticleSystem *NewTemplate)
UFUNCTION ()) 1 void Activate()
UFUNCTION ()) 1 void Deactivate()
UFUNCTION ()) 1 void SetActorParameter(FName ParameterName
UFUNCTION ()) 1 void SetColorParameter(FName ParameterName
UFUNCTION ()) 1 void SetFloatParameter(FName ParameterName
UFUNCTION ()) 1 void SetMaterialParameter(FName ParameterName
UFUNCTION ()) 1 void SetVectorParameter(FName ParameterName
UFUNCTION ()) 1 void ToggleActive()
UPROPERTY () FParticleBurstSignature OnParticleBurst
UPROPERTY () FParticleCollisionSignature OnParticleCollide
UPROPERTY () FParticleDeathSignature OnParticleDeath
UPROPERTY() uint32 bDestroyOnSystemFinish UPROPERTY() uint32 bPostUpdateTickGroup UPROPERTY() uint32 bCurrentlyActive UPROPERTY () FParticleSpawnSignature OnParticleSpawn
used to update status of toggleable level placed emitters on clients
Data Fields
float Param
FVector Param
FLinearColor Param
class AActor * Param
class UMaterialInterface * Param
Private Member Functions
GENERATED_UCLASS_BODY () 1 virtual void GetLifetimeReplicatedProps(TArray< FLifetimeProperty > &OutLifetimeProps) const override
UPROPERTY ()) TObjectPtr< class UParticleSystemComponent > ParticleSystemComponent
Detailed Description
Definition at line 55 of file Emitter.h.
Member Function Documentation
AutoPopulateInstanceProperties()
void AEmitter::AutoPopulateInstanceProperties ()
References AutoPopulateInstanceProperties().
Referenced by AutoPopulateInstanceProperties().
CheckForErrors()
virtual void AEmitter::CheckForErrors () override virtual
GENERATED_UCLASS_BODY()
AEmitter::GENERATED_UCLASS_BODY () const & override private
GetDetailedInfoInternal()
virtual FString AEmitter::GetDetailedInfoInternal () const override virtual
References GetDetailedInfoInternal().
Referenced by GetDetailedInfoInternal().
GetParticleSystemComponent()
class UParticleSystemComponent * AEmitter::GetParticleSystemComponent () inline
Returns ParticleSystemComponent subobject.
Definition at line 155 of file Emitter.h.
GetReferencedContentObjects()
virtual bool AEmitter::GetReferencedContentObjects (TArray< UObject * > & Objects) const override virtual
PostActorCreated()
virtual void AEmitter::PostActorCreated () override virtual
References PostActorCreated().
Referenced by PostActorCreated().
PostInitializeComponents()
virtual void AEmitter::PostInitializeComponents () override virtual
References PostInitializeComponents().
Referenced by PostInitializeComponents().
ResetInLevel()
void AEmitter::ResetInLevel ()
Called to reset the emitter actor in the level.
Intended for use in editor only
UFUNCTION() [1/12]
AEmitter::UFUNCTION ()
Referenced by UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
UFUNCTION() [2/12]
AEmitter::UFUNCTION ()
Replication Notification Callbacks.
References UFUNCTION().
UFUNCTION() [3/12]
AEmitter::UFUNCTION () const
References Category, meta, and UFUNCTION().
UFUNCTION() [4/12]
AEmitter::UFUNCTION ()
References Category, meta, and UFUNCTION().
UFUNCTION() [5/12]
AEmitter::UFUNCTION ()
References Activate, Category, meta, and UFUNCTION().
UFUNCTION() [6/12]
AEmitter::UFUNCTION ()
References Category, Deactivate, meta, and UFUNCTION().
UFUNCTION() [7/12]
AEmitter::UFUNCTION ()
References Category, meta, and UFUNCTION().
UFUNCTION() [8/12]
AEmitter::UFUNCTION ()
References Category, meta, and UFUNCTION().
UFUNCTION() [9/12]
AEmitter::UFUNCTION ()
References Category, meta, and UFUNCTION().
UFUNCTION() [10/12]
AEmitter::UFUNCTION ()
References Category, meta, and UFUNCTION().
UFUNCTION() [11/12]
AEmitter::UFUNCTION ()
References Category, meta, and UFUNCTION().
UFUNCTION() [12/12]
AEmitter::UFUNCTION ()
References Category, meta, and UFUNCTION().
UPROPERTY() [1/5]
AEmitter::UPROPERTY ()
References UPROPERTY().
UPROPERTY() [2/5]
AEmitter::UPROPERTY ()
References UPROPERTY().
UPROPERTY() [3/5]
AEmitter::UPROPERTY ()
References UPROPERTY().
UPROPERTY() [4/5]
UPROPERTY() uint32 bDestroyOnSystemFinish UPROPERTY() uint32 bPostUpdateTickGroup UPROPERTY() uint32 bCurrentlyActive AEmitter::UPROPERTY ()
used to update status of toggleable level placed emitters on clients
References UPROPERTY().
UPROPERTY() [5/5]
AEmitter::UPROPERTY () private
References Category, meta, and UPROPERTY().
Referenced by UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), and UPROPERTY().
Field Documentation
Param [1/5]
float AEmitter::Param
Definition at line 119 of file Emitter.h.
Param [2/5]
FVector AEmitter::Param
Definition at line 121 of file Emitter.h.
Param [3/5]
FLinearColor AEmitter::Param
Definition at line 123 of file Emitter.h.
Param [4/5]
class AActor* AEmitter::Param
Definition at line 125 of file Emitter.h.
Param [5/5]
class UMaterialInterface* AEmitter::Param
Definition at line 127 of file Emitter.h.
The documentation for this class was generated from the following file:
Runtime/Engine/Classes/Particles/Emitter.h