Unreal Engine 5.6 C++ API: UE::Geometry::FSparseDynamicPointOctree3 Class Reference
UE::Geometry::FSparseDynamicPointOctree3 Class Reference
FSparseDynamicPointOctree3 sorts Points with axis-aligned bounding boxes into a dynamic sparse octree of axis-aligned uniform grid cells.
#include "SparseDynamicPointOctree3.h"
Data Structures
struct FStatistics
statistics about internal structure of the octree
Public Member Functions
void CheckValidity (TFunctionRef< bool(int)> IsValidPointIDFunc, TFunctionRef< FVector3d(int)> GetPointFunc, EValidityCheckFailMode FailMode=EValidityCheckFailMode::Check, bool bVerbose=false, bool bFailOnMissingPoints=false) const
Check that the octree is internally valid.
void ComputeStatistics (FStatistics &StatsOut) const
Populate given FStatistics with info about the octree.
void ConfigureFromPointCountEstimate (double MaxBoundsDimension, int CountEstimate)
Do a rough ballpark configuration of the RootDimension, MaxTreeDepth, and MaxPointsPerCell tree config values, given a bounding-box dimension and estimate of the total number of points that will be inserted.
bool ContainsPoint (int32 PointID) const
Test if an Point is stored in the tree.
GEOMETRYCORE_API int32 FindClosestPoint (FVector3d QueryPt, double DistanceThreshold, TFunctionRef< bool(int32)> PredicateFunc, TFunctionRef< double(int32)> DistSqFunc, TArray< const FSparsePointOctreeCell * > *TempBuffer=nullptr) const
Find closest point in the tree, relative to a query point, within a search distance.
void FindKClosestPoints (FVector3d QueryPt, double DistanceThreshold, int32 NumToFind, TArray< TPair< int32, double > > &FoundPoints, TFunctionRef< bool(int32)> PredicateFunc, TFunctionRef< double(int32)> DistSqFunc, TArray< const FSparsePointOctreeCell * > *TempBuffer=nullptr) const
Find the K closest point in the tree, relative to a query point, within a search distance.
int32 FindNearestHitPoint (const FRay3d &Ray, TFunctionRef< double(int, const FRay3d &)> HitPointDistFunc, double MaxDistance=TNumericLimits< double >::Max()) const
Find nearest ray-hit point with Points in tree.
void InsertPoint (int32 PointID, const FVector3d &Position)
Insert PointID into the Octree at maximum depth.
void InsertPoint_DynamicExpand (int32 PointID, TFunctionRef< FVector3d(int)> GetPositionFunc)
Insert PointID into the Octree.
void ParallelInsertDensePointSet (int32 MaxPointID, TFunctionRef< FVector3d(int)> GetPositionFunc)
Insert a set of dense points with IDs in range [0, MaxPointID-1], in parallel.
void ParallelRangeQuery (const FAxisAlignedBox3d &Bounds, TFunctionRef< bool(int)> PredicateFunc, TArray< int > &PointIDsOut, TArray< const FSparsePointOctreeCell * > *TempBuffer=nullptr) const
Collect PointIDs from all the cells with bounding boxes that intersect Bounds, where PredicateFunc passes Query is parallelized across Root cells.
void RangeQuery (const FAxisAlignedBox3d &Bounds, TFunctionRef< bool(int)> PredicateFunc, TArray< int > &PointIDsOut, TArray< const FSparsePointOctreeCell * > *TempBuffer=nullptr) const
Collect PointIDs from all the cells with bounding boxes that intersect Bounds, where PredicateFunc passes.
void ReinsertPoint (int32 PointID, const FVector3d &NewPosition)
Update the position of an Point in the octree.
bool RemovePoint (int32 PointID)
Remove a Point from the octree.
void RemovePointUnsafe (int32 PointID)
Remove a Point from the octree.
Data Fields
int MaxPointsPerCell = 1000
if using the InsertPoint_DynamicExpand() insertion path, then when a cell gets to this many points, and has depth < MaxTreeDepth, it will be expanded and its points moved down
int MaxTreeDepth = 10
Points will not be inserted more than this many levels deep from a Root cell.
double RootDimension = 1000.0
Size of the Root cells of the octree.
Protected Member Functions
bool CellContains (const FSparsePointOctreeCell &Cell, const FVector3d &Position) const
uint32 CreateNewRootCell (FSparsePointOctreeCell NewRootCell, bool bInitializeCellPointList)
FSparsePointOctreeCell FindCurrentContainingCell (const FVector3d &Position) const
double FindNearestRayCellIntersection (const FSparsePointOctreeCell &Cell, const FRay3d &Ray) const
FAxisAlignedBox3d GetCellBox (const FSparsePointOctreeCell &Cell) const
FAxisAlignedBox3d GetCellBox (uint32 Level, const FVector3i &Index) const
FVector3d GetCellCenter (const FSparsePointOctreeCell &Cell) const
FVector3d GetCellCenter (uint32 Level, const FVector3i &Index) const
uint32 GetCellForPoint (int32 PointID) const
double GetCellWidth (uint32 Level) const
void Insert_NewChildCell (int32 PointID, const FVector3d &Position, int ParentCellID, FSparsePointOctreeCell NewChildCell, int ChildIdx)
void Insert_NewRoot (int32 PointID, const FVector3d &Position, FSparsePointOctreeCell NewRootCell)
void Insert_ToCell (int32 PointID, const FVector3d &Position, const FSparsePointOctreeCell &ExistingCell)
FVector3i PointToIndex (uint32 Level, const FVector3d &Position) const
int ToChildCellIndex (const FSparsePointOctreeCell &Cell, const FVector3d &Position) const
int ToChildCellIndex (uint32 Level, const FVector3i &Index, const FVector3d &Position) const
Protected Attributes
TSparseListSet< int32 > CellPointLists
FRefCountVector CellRefCounts
TDynamicVector< FSparsePointOctreeCell > Cells
TDynamicVector< uint32 > PointIDToCellMap
TSparseGrid3< uint32 > RootCells
Static Protected Attributes
static constexpr uint32 InvalidCellID = FSparsePointOctreeCell::InvalidID
Private Member Functions
void IterateRootsInRadius (FVector3d QueryPt, double InitialRadius, TFunctionRef< double(double RadSq, const FSparsePointOctreeCell &Root)> RootFn) const
Detailed Description
FSparseDynamicPointOctree3 sorts Points with axis-aligned bounding boxes into a dynamic sparse octree of axis-aligned uniform grid cells.
At the top level we have an infinite grid of "root cells" of size RootDimension, which then contain 8 children, and so on. (So in fact each cell is a separate octree, and we have a uniform grid of octrees)
The Points and their bounding-boxes are not stored in the tree. You must have an integer identifier (PointID) for each Point, and call Insert(PointID, BoundingBox). Some query functions will require you to provide a lambda/etc that can be called to retrieve the bounding box for a given PointID.
By default Points are currently inserted at the maximum possible depth, ie smallest cell that will contain them, or MaxTreeDepth.
The octree is dynamic. Points can be removed and re-inserted.
Definition at line 106 of file SparseDynamicPointOctree3.h.
Member Function Documentation
CellContains()
bool UE::Geometry::FSparseDynamicPointOctree3::CellContains (const FSparsePointOctreeCell & Cell, const FVector3d & Position) const inline protected
Definition at line 398 of file SparseDynamicPointOctree3.h.
References Cell, UE::Geometry::TAxisAlignedBox3< RealType >::Contains(), GetCellBox(), and UE::Geometry::Position.
Referenced by FindCurrentContainingCell(), Insert_NewChildCell(), Insert_ToCell(), InsertPoint(), and ReinsertPoint().
CheckValidity()
void UE::Geometry::FSparseDynamicPointOctree3::CheckValidity (TFunctionRef< bool(int)> IsValidPointIDFunc, TFunctionRef< FVector3d(int)> GetPointFunc, EValidityCheckFailMode FailMode = EValidityCheckFailMode::Check, bool bVerbose = false, bool bFailOnMissingPoints = false) const inline
Check that the octree is internally valid.
Parameters
IsValidPointIDFunc function that returns true if given PointID is valid
GetPointFunc function that returns point position identified by PointID
FailMode how should validity checks fail
bVerbose if true, print some debug info via UE_LOG
bFailOnMissingPoints if true, assume PointIDs are dense and that all PointIDs must be in the tree
Definition at line 1151 of file SparseDynamicPointOctree3.h.
References Cell, CellPointLists, CellRefCounts, Cells, UE::Geometry::Check, checkf, CheckValidity(), UE::Geometry::TAxisAlignedBox3< RealType >::Contains(), UE::Geometry::Ensure, ensureMsgf, GetCellBox(), TArray< InElementType, InAllocatorType >::Init(), InvalidCellID, FMath::Max, PointIDToCellMap, UE::Geometry::Position, TEXT, UE_LOG, and Warning.
Referenced by CheckValidity(), and UE::Geometry::TDynamicVerticesOctree3< SourceType >::CheckValidity().
ComputeStatistics()
void UE::Geometry::FSparseDynamicPointOctree3::ComputeStatistics (FStatistics & StatsOut) const inline
Populate given FStatistics with info about the octree.
Definition at line 1249 of file SparseDynamicPointOctree3.h.
References Cell, CellPointLists, CellRefCounts, Cells, ComputeStatistics(), float, GetCellWidth(), TArray< InElementType, InAllocatorType >::Init(), UE::Geometry::FSparseDynamicPointOctree3::FStatistics::LevelBoxCounts, UE::Geometry::FSparseDynamicPointOctree3::FStatistics::LevelCellSizes, UE::Geometry::FSparseDynamicPointOctree3::FStatistics::LevelMaxObjCounts, UE::Geometry::FSparseDynamicPointOctree3::FStatistics::LevelObjCounts, UE::Geometry::FSparseDynamicPointOctree3::FStatistics::Levels, and FMath::Max.
Referenced by ComputeStatistics().
ConfigureFromPointCountEstimate()
void UE::Geometry::FSparseDynamicPointOctree3::ConfigureFromPointCountEstimate (double MaxBoundsDimension, int CountEstimate) inline
Do a rough ballpark configuration of the RootDimension, MaxTreeDepth, and MaxPointsPerCell tree config values, given a bounding-box dimension and estimate of the total number of points that will be inserted.
This is primarily intended to be used with ParallelInsertDensePointSet()
Definition at line 430 of file SparseDynamicPointOctree3.h.
ContainsPoint()
bool UE::Geometry::FSparseDynamicPointOctree3::ContainsPoint (int32 PointID) const inline
Test if an Point is stored in the tree.
Parameters
PointID ID of the Point
Returns
true if PointID is stored in this octree
Definition at line 460 of file SparseDynamicPointOctree3.h.
References InvalidCellID, and PointIDToCellMap.
Referenced by InsertPoint(), InsertPoint_DynamicExpand(), ReinsertPoint(), and RemovePoint().
CreateNewRootCell()
uint32 UE::Geometry::FSparseDynamicPointOctree3::CreateNewRootCell (FSparsePointOctreeCell NewRootCell, bool bInitializeCellPointList) inline protected
Definition at line 548 of file SparseDynamicPointOctree3.h.
References UE::Geometry::FSparsePointOctreeCell::CellID, CellPointLists, CellRefCounts, Cells, checkSlow, UE::Geometry::FSparsePointOctreeCell::Index, and RootCells.
Referenced by Insert_NewRoot(), and ParallelInsertDensePointSet().
FindClosestPoint()
GEOMETRYCORE_API int32 UE::Geometry::FSparseDynamicPointOctree3::FindClosestPoint (FVector3d QueryPt, double DistanceThreshold, TFunctionRef< bool(int32)> PredicateFunc, TFunctionRef< double(int32)> DistSqFunc, TArray< const FSparsePointOctreeCell * > * TempBuffer = nullptr) const
Find closest point in the tree, relative to a query point, within a search distance.
Parameters
QueryPt Find the point closest to this query point
DistanceThreshold Limit the search to this distance
PredicateFunc Return true if point should be included (i.e., this is a filter)
DistSqFunc User-provided squared distance between the point with the given ID and the QueryPt
TempBuffer Optional temporary buffer to store a queue of cells (to avoid memory allocations)
Returns
The ID of the closest point, or INDEX_NONE if no point was found
FindCurrentContainingCell()
FSparsePointOctreeCell UE::Geometry::FSparseDynamicPointOctree3::FindCurrentContainingCell (const FVector3d & Position) const inline protected
Definition at line 1107 of file SparseDynamicPointOctree3.h.
References CellContains(), CellRefCounts, Cells, checkSlow, FindCurrentContainingCell(), UE::Geometry::FSparsePointOctreeCell::GetChildCellID(), UE::Geometry::FSparsePointOctreeCell::HasChild(), UE::Geometry::FSparsePointOctreeCell::InvalidLevel, PointToIndex(), UE::Geometry::Position, RootCells, ToChildCellIndex(), and UE::Geometry::FVector3i::Zero().
Referenced by FindCurrentContainingCell(), InsertPoint(), and InsertPoint_DynamicExpand().
FindKClosestPoints()
void UE::Geometry::FSparseDynamicPointOctree3::FindKClosestPoints (FVector3d QueryPt, double DistanceThreshold, int32 NumToFind, TArray< TPair< int32, double > > & FoundPoints, TFunctionRef< bool(int32)> PredicateFunc, TFunctionRef< double(int32)> DistSqFunc, TArray< const FSparsePointOctreeCell * > * TempBuffer = nullptr) const
Find the K closest point in the tree, relative to a query point, within a search distance.
Parameters
QueryPt Find the points closest to this query point
DistanceThreshold Limit the search to this distance
NumToFind The maximum number of closest points to find
FoundPoints The found closest points will be added to this array
PredicateFunc Return true if point should be included (i.e., this is a filter)
DistSqFunc User-provided squared distance between the point with the given ID and the QueryPt
TempBuffer Optional temporary buffer to store a queue of cells (to avoid memory allocations)
References UE::Geometry::Check.
FindNearestHitPoint()
int32 UE::Geometry::FSparseDynamicPointOctree3::FindNearestHitPoint (const FRay3d & Ray, TFunctionRef< double(int, const FRay3d &)> HitPointDistFunc, double MaxDistance = TNumericLimits<double>::Max()) const inline
Find nearest ray-hit point with Points in tree.
Parameters
Ray the ray
HitPointDistFunc function that returns distance along ray to hit-point on Point identified by PointID (or TNumericLimits<double>::Max() on miss)
MaxDistance maximum hit distance
Returns
PointID of hit Point, or -1 on miss
Definition at line 913 of file SparseDynamicPointOctree3.h.
References TArray< InElementType, InAllocatorType >::Add(), UE::Geometry::FSparsePointOctreeCell::CellID, CellPointLists, Cells, FindNearestHitPoint(), FindNearestRayCellIntersection(), No, TArray< InElementType, InAllocatorType >::Num(), TArray< InElementType, InAllocatorType >::Pop(), Ray, TArray< InElementType, InAllocatorType >::Reserve(), and RootCells.
Referenced by FindNearestHitPoint(), and UE::Geometry::TDynamicVerticesOctree3< SourceType >::FindNearestHitVertex().
FindNearestRayCellIntersection()
double UE::Geometry::FSparseDynamicPointOctree3::FindNearestRayCellIntersection (const FSparsePointOctreeCell & Cell, const FRay3d & Ray) const inline protected
Definition at line 896 of file SparseDynamicPointOctree3.h.
References UE::Geometry::Box, Cell, UE::Geometry::TIntrRay3AxisAlignedBox3< double >::FindIntersection(), FindNearestRayCellIntersection(), GetCellBox(), and Ray.
Referenced by FindNearestHitPoint(), and FindNearestRayCellIntersection().
GetCellBox() [1/2]
FAxisAlignedBox3d UE::Geometry::FSparseDynamicPointOctree3::GetCellBox (const FSparsePointOctreeCell & Cell) const inline protected
Definition at line 344 of file SparseDynamicPointOctree3.h.
References Cell, and GetCellBox().
GetCellBox() [2/2]
FAxisAlignedBox3d UE::Geometry::FSparseDynamicPointOctree3::GetCellBox (uint32 Level, const FVector3i & Index) const inline protected
Definition at line 334 of file SparseDynamicPointOctree3.h.
References GetCellWidth().
Referenced by CellContains(), CheckValidity(), FindNearestRayCellIntersection(), GetCellBox(), and RangeQuery().
GetCellCenter() [1/2]
FVector3d UE::Geometry::FSparseDynamicPointOctree3::GetCellCenter (const FSparsePointOctreeCell & Cell) const inline protected
Definition at line 358 of file SparseDynamicPointOctree3.h.
References Cell, and GetCellCenter().
GetCellCenter() [2/2]
FVector3d UE::Geometry::FSparseDynamicPointOctree3::GetCellCenter (uint32 Level, const FVector3i & Index) const inline protected
Definition at line 349 of file SparseDynamicPointOctree3.h.
References GetCellWidth().
Referenced by GetCellCenter(), and ToChildCellIndex().
GetCellForPoint()
uint32 UE::Geometry::FSparseDynamicPointOctree3::GetCellForPoint (int32 PointID) const inline protected
Definition at line 404 of file SparseDynamicPointOctree3.h.
References InvalidCellID, and PointIDToCellMap.
Referenced by ReinsertPoint(), and RemovePoint().
GetCellWidth()
double UE::Geometry::FSparseDynamicPointOctree3::GetCellWidth (uint32 Level) const inline protected
Definition at line 326 of file SparseDynamicPointOctree3.h.
References RootDimension.
Referenced by ComputeStatistics(), GetCellBox(), GetCellCenter(), and PointToIndex().
Insert_NewChildCell()
void UE::Geometry::FSparseDynamicPointOctree3::Insert_NewChildCell (int32 PointID, const FVector3d & Position, int ParentCellID, FSparsePointOctreeCell NewChildCell, int ChildIdx) inline protected
Definition at line 504 of file SparseDynamicPointOctree3.h.
References CellContains(), UE::Geometry::FSparsePointOctreeCell::CellID, CellPointLists, CellRefCounts, Cells, checkSlow, UE::Geometry::FSparsePointOctreeCell::HasChild(), UE::Geometry::FSparsePointOctreeCell::Index, InvalidCellID, UE::Geometry::FSparsePointOctreeCell::Level, PointIDToCellMap, PointToIndex(), UE::Geometry::Position, and UE::Geometry::FSparsePointOctreeCell::SetChild().
Referenced by InsertPoint(), and InsertPoint_DynamicExpand().
Insert_NewRoot()
void UE::Geometry::FSparseDynamicPointOctree3::Insert_NewRoot (int32 PointID, const FVector3d & Position, FSparsePointOctreeCell NewRootCell) inline protected
Definition at line 540 of file SparseDynamicPointOctree3.h.
References CellPointLists, CreateNewRootCell(), InvalidCellID, PointIDToCellMap, and UE::Geometry::Position.
Referenced by InsertPoint(), and InsertPoint_DynamicExpand().
Insert_ToCell()
void UE::Geometry::FSparseDynamicPointOctree3::Insert_ToCell (int32 PointID, const FVector3d & Position, const FSparsePointOctreeCell & ExistingCell) inline protected
Definition at line 526 of file SparseDynamicPointOctree3.h.
References CellContains(), UE::Geometry::FSparsePointOctreeCell::CellID, CellPointLists, CellRefCounts, checkSlow, UE::Geometry::FSparsePointOctreeCell::Index, InvalidCellID, UE::Geometry::FSparsePointOctreeCell::Level, PointIDToCellMap, PointToIndex(), and UE::Geometry::Position.
Referenced by InsertPoint(), and InsertPoint_DynamicExpand().
InsertPoint()
void UE::Geometry::FSparseDynamicPointOctree3::InsertPoint (int32 PointID, const FVector3d & Position) inline
Insert PointID into the Octree at maximum depth.
Currently only expands at most one depth-level per insertion. This is sub-optimal.
Parameters
PointID ID of the Point to insert
Position position of the Point
Definition at line 466 of file SparseDynamicPointOctree3.h.
References CellContains(), UE::Geometry::FSparsePointOctreeCell::CellID, checkSlow, ContainsPoint(), FindCurrentContainingCell(), UE::Geometry::FSparsePointOctreeCell::HasChild(), Insert_NewChildCell(), Insert_NewRoot(), Insert_ToCell(), UE::Geometry::FSparsePointOctreeCell::InvalidLevel, UE::Geometry::FSparsePointOctreeCell::IsExistingCell(), UE::Geometry::FSparsePointOctreeCell::Level, UE::Geometry::FSparsePointOctreeCell::MakeChildCell(), MaxTreeDepth, UE::Geometry::Position, and ToChildCellIndex().
Referenced by UE::Geometry::TDynamicVerticesOctree3< SourceType >::InsertVertex(), UE::Geometry::TDynamicVerticesOctree3< SourceType >::InsertVertices(), UE::Geometry::TDynamicVerticesOctree3< SourceType >::InsertVertices(), and ReinsertPoint().
InsertPoint_DynamicExpand()
void UE::Geometry::FSparseDynamicPointOctree3::InsertPoint_DynamicExpand (int32 PointID, TFunctionRef< FVector3d(int)> GetPositionFunc) inline
Insert PointID into the Octree.
Dynamically expands cells that have more than MaxPointsPerCell
Parameters
PointID ID of the Point to insert
GetPositionFunc function that returns position of point (Required to reinsert points on expand)
Definition at line 770 of file SparseDynamicPointOctree3.h.
References UE::Geometry::FSparsePointOctreeCell::CellID, CellPointLists, Cells, checkSlow, ContainsPoint(), FindCurrentContainingCell(), UE::Geometry::FSparsePointOctreeCell::GetChildCellID(), UE::Geometry::FSparsePointOctreeCell::HasChild(), Insert_NewChildCell(), Insert_NewRoot(), Insert_ToCell(), InsertPoint_DynamicExpand(), UE::Geometry::FSparsePointOctreeCell::InvalidLevel, UE::Geometry::FSparsePointOctreeCell::IsExistingCell(), UE::Geometry::FSparsePointOctreeCell::Level, UE::Geometry::FSparsePointOctreeCell::MakeChildCell(), MaxPointsPerCell, MaxTreeDepth, UE::Geometry::Position, and ToChildCellIndex().
Referenced by UE::Geometry::TDynamicVerticesOctree3< SourceType >::Initialize(), and InsertPoint_DynamicExpand().
IterateRootsInRadius()
void UE::Geometry::FSparseDynamicPointOctree3::IterateRootsInRadius (FVector3d QueryPt, double InitialRadius, TFunctionRef< double(double RadSq, const FSparsePointOctreeCell &Root)> RootFn) const private
References Root.
ParallelInsertDensePointSet()
void UE::Geometry::FSparseDynamicPointOctree3::ParallelInsertDensePointSet (int32 MaxPointID, TFunctionRef< FVector3d(int)> GetPositionFunc) inline
Insert a set of dense points with IDs in range [0, MaxPointID-1], in parallel.
The points are only inserted in leaf nodes, at MaxTreeDepth level, so that value should be set conservatively. Parallel insertion is across root cells, so if the RootDimension is larger than the point set bounds, this will be slower than incremental construction. ConfigureFromPointCountEstimate() provides reasonable values for large point sets.
Parameters
GetPositionFunc function that returns position of point (Required to reinsert points on expand)
Definition at line 567 of file SparseDynamicPointOctree3.h.
References TArray< InElementType, InAllocatorType >::Add(), Cell, UE::Geometry::FSparsePointOctreeCell::CellID, CellPointLists, CellRefCounts, Cells, checkSlow, CreateNewRootCell(), TArray< InElementType, InAllocatorType >::Empty(), ensure, UE::Geometry::FSparsePointOctreeCell::Index, InvalidCellID, UE::Geometry::FSparsePointOctreeCell::MakeChildCell(), MakeUnique(), MaxTreeDepth, TArray< InElementType, InAllocatorType >::Num(), operator==(), ParallelFor(), PointIDToCellMap, PointToIndex(), TArray< InElementType, InAllocatorType >::Reserve(), TArray< InElementType, InAllocatorType >::SetNum(), TArray< InElementType, InAllocatorType >::SetNumUninitialized(), and Swap.
ParallelRangeQuery()
void UE::Geometry::FSparseDynamicPointOctree3::ParallelRangeQuery (const FAxisAlignedBox3d & Bounds, TFunctionRef< bool(int)> PredicateFunc, TArray< int > & PointIDsOut, TArray< const FSparsePointOctreeCell * > * TempBuffer = nullptr) const inline
Collect PointIDs from all the cells with bounding boxes that intersect Bounds, where PredicateFunc passes Query is parallelized across Root cells.
So if there is only one Root cell, it's actually slower than RangeQuery() due to internal temp buffers.
Parameters
Bounds query box
PredicateFunc return true if point should be included (ie this is a filter)
PointIDsOut collected PointIDs are stored here
TempBuffer optional temporary buffer to store a queue of cells (to avoid memory allocations)
Definition at line 1031 of file SparseDynamicPointOctree3.h.
References TArray< InElementType, InAllocatorType >::Add(), Cells, UE::Geometry::TAxisAlignedBox3< RealType >::Max, UE::Geometry::TAxisAlignedBox3< RealType >::Min, TArray< InElementType, InAllocatorType >::Num(), ParallelFor(), ParallelRangeQuery(), PointToIndex(), TArray< InElementType, InAllocatorType >::Reserve(), TArray< InElementType, InAllocatorType >::Reset(), and RootCells.
Referenced by ParallelRangeQuery().
PointToIndex()
FVector3i UE::Geometry::FSparseDynamicPointOctree3::PointToIndex (uint32 Level, const FVector3d & Position) const inline protected
Definition at line 364 of file SparseDynamicPointOctree3.h.
References FMath::Clamp(), TMathUtil< double >::Floor(), GetCellWidth(), UE::Geometry::Position, and Value.
Referenced by FindCurrentContainingCell(), Insert_NewChildCell(), Insert_ToCell(), ParallelInsertDensePointSet(), ParallelRangeQuery(), and RangeQuery().
RangeQuery()
void UE::Geometry::FSparseDynamicPointOctree3::RangeQuery (const FAxisAlignedBox3d & Bounds, TFunctionRef< bool(int)> PredicateFunc, TArray< int > & PointIDsOut, TArray< const FSparsePointOctreeCell * > * TempBuffer = nullptr) const inline
Collect PointIDs from all the cells with bounding boxes that intersect Bounds, where PredicateFunc passes.
Parameters
Bounds query box
PredicateFunc return true if point should be included (ie this is a filter)
PointIDsOut collected PointIDs are stored here
TempBuffer optional temporary buffer to store a queue of cells (to avoid memory allocations)
Definition at line 976 of file SparseDynamicPointOctree3.h.
References TArray< InElementType, InAllocatorType >::Add(), UE::Geometry::FSparsePointOctreeCell::CellID, CellPointLists, Cells, GetCellBox(), UE::Geometry::TAxisAlignedBox3< RealType >::Max, UE::Geometry::TAxisAlignedBox3< RealType >::Min, No, TArray< InElementType, InAllocatorType >::Num(), PointToIndex(), TArray< InElementType, InAllocatorType >::Pop(), RangeQuery(), TArray< InElementType, InAllocatorType >::Reserve(), TArray< InElementType, InAllocatorType >::Reset(), and RootCells.
Referenced by RangeQuery().
ReinsertPoint()
void UE::Geometry::FSparseDynamicPointOctree3::ReinsertPoint (int32 PointID, const FVector3d & NewPosition) inline
Update the position of an Point in the octree.
This is more efficient than doing a remove+insert
Parameters
PointID ID of the Point
NewBounds enw bounding box of the Point
Definition at line 871 of file SparseDynamicPointOctree3.h.
References CellContains(), Cells, ContainsPoint(), GetCellForPoint(), InsertPoint(), InvalidCellID, ReinsertPoint(), and RemovePoint().
Referenced by ReinsertPoint(), and UE::Geometry::TDynamicVerticesOctree3< SourceType >::ReinsertVertices().
RemovePoint()
bool UE::Geometry::FSparseDynamicPointOctree3::RemovePoint (int32 PointID) inline
Remove a Point from the octree.
Parameters
PointID ID of the Point
Returns
true if the Point was in the tree and removed
Definition at line 837 of file SparseDynamicPointOctree3.h.
References CellPointLists, checkSlow, ContainsPoint(), GetCellForPoint(), InvalidCellID, PointIDToCellMap, and RemovePoint().
Referenced by ReinsertPoint(), RemovePoint(), UE::Geometry::TDynamicVerticesOctree3< SourceType >::RemovePoint(), UE::Geometry::TDynamicVerticesOctree3< SourceType >::RemoveVertices(), and UE::Geometry::TDynamicVerticesOctree3< SourceType >::RemoveVertices().
RemovePointUnsafe()
void UE::Geometry::FSparseDynamicPointOctree3::RemovePointUnsafe (int32 PointID) inline
Remove a Point from the octree.
This function must only be called with PointIDs that are certain to be in the tree.
Parameters
PointID ID of the Point.
Definition at line 858 of file SparseDynamicPointOctree3.h.
References CellPointLists, InvalidCellID, PointIDToCellMap, and RemovePointUnsafe().
Referenced by RemovePointUnsafe().
ToChildCellIndex() [1/2]
int UE::Geometry::FSparseDynamicPointOctree3::ToChildCellIndex (const FSparsePointOctreeCell & Cell, const FVector3d & Position) const inline protected
Definition at line 393 of file SparseDynamicPointOctree3.h.
References Cell, UE::Geometry::Position, and ToChildCellIndex().
ToChildCellIndex() [2/2]
int UE::Geometry::FSparseDynamicPointOctree3::ToChildCellIndex (uint32 Level, const FVector3i & Index, const FVector3d & Position) const inline protected
Definition at line 384 of file SparseDynamicPointOctree3.h.
References GetCellCenter(), and UE::Geometry::Position.
Referenced by FindCurrentContainingCell(), InsertPoint(), InsertPoint_DynamicExpand(), and ToChildCellIndex().
Field Documentation
CellPointLists
TSparseListSet<int32> UE::Geometry::FSparseDynamicPointOctree3::CellPointLists protected
Definition at line 316 of file SparseDynamicPointOctree3.h.
Referenced by CheckValidity(), ComputeStatistics(), CreateNewRootCell(), FindNearestHitPoint(), Insert_NewChildCell(), Insert_NewRoot(), Insert_ToCell(), InsertPoint_DynamicExpand(), ParallelInsertDensePointSet(), RangeQuery(), RemovePoint(), and RemovePointUnsafe().
CellRefCounts
FRefCountVector UE::Geometry::FSparseDynamicPointOctree3::CellRefCounts protected
Definition at line 311 of file SparseDynamicPointOctree3.h.
Referenced by CheckValidity(), ComputeStatistics(), CreateNewRootCell(), FindCurrentContainingCell(), Insert_NewChildCell(), Insert_ToCell(), and ParallelInsertDensePointSet().
Cells
TDynamicVector<FSparsePointOctreeCell> UE::Geometry::FSparseDynamicPointOctree3::Cells protected
Definition at line 314 of file SparseDynamicPointOctree3.h.
Referenced by CheckValidity(), ComputeStatistics(), CreateNewRootCell(), FindCurrentContainingCell(), FindNearestHitPoint(), Insert_NewChildCell(), InsertPoint_DynamicExpand(), ParallelInsertDensePointSet(), ParallelRangeQuery(), RangeQuery(), and ReinsertPoint().
InvalidCellID
uint32 UE::Geometry::FSparseDynamicPointOctree3::InvalidCellID = FSparsePointOctreeCell::InvalidID static constexpr protected
Definition at line 307 of file SparseDynamicPointOctree3.h.
Referenced by CheckValidity(), ContainsPoint(), GetCellForPoint(), Insert_NewChildCell(), Insert_NewRoot(), Insert_ToCell(), ParallelInsertDensePointSet(), ReinsertPoint(), RemovePoint(), and RemovePointUnsafe().
MaxPointsPerCell
int UE::Geometry::FSparseDynamicPointOctree3::MaxPointsPerCell = 1000
if using the InsertPoint_DynamicExpand() insertion path, then when a cell gets to this many points, and has depth < MaxTreeDepth, it will be expanded and its points moved down
Definition at line 137 of file SparseDynamicPointOctree3.h.
Referenced by InsertPoint_DynamicExpand().
MaxTreeDepth
int UE::Geometry::FSparseDynamicPointOctree3::MaxTreeDepth = 10
Points will not be inserted more than this many levels deep from a Root cell.
Definition at line 131 of file SparseDynamicPointOctree3.h.
Referenced by InsertPoint(), InsertPoint_DynamicExpand(), and ParallelInsertDensePointSet().
PointIDToCellMap
TDynamicVector<uint32> UE::Geometry::FSparseDynamicPointOctree3::PointIDToCellMap protected
Definition at line 318 of file SparseDynamicPointOctree3.h.
Referenced by CheckValidity(), ContainsPoint(), GetCellForPoint(), Insert_NewChildCell(), Insert_NewRoot(), Insert_ToCell(), ParallelInsertDensePointSet(), RemovePoint(), and RemovePointUnsafe().
RootCells
TSparseGrid3<uint32> UE::Geometry::FSparseDynamicPointOctree3::RootCells protected
Definition at line 322 of file SparseDynamicPointOctree3.h.
Referenced by CreateNewRootCell(), FindCurrentContainingCell(), FindNearestHitPoint(), ParallelRangeQuery(), and RangeQuery().
RootDimension
double UE::Geometry::FSparseDynamicPointOctree3::RootDimension = 1000.0
Size of the Root cells of the octree.
Definition at line 126 of file SparseDynamicPointOctree3.h.
Referenced by GetCellWidth().
The documentation for this class was generated from the following file:
Runtime/GeometryCore/Public/Spatial/SparseDynamicPointOctree3.h