Unreal Engine 5.6 C++ API: Metasound::MetasoundInputNodePrivate::TInputNodeOperatorFactory< DataType, VertexAccess > Class Template Reference
Metasound::MetasoundInputNodePrivate::TInputNodeOperatorFactory< DataType, VertexAccess > Class Template Reference
#include "MetasoundInputNode.h"
Public Member Functions
TInputNodeOperatorFactory (const FVertexName &InVertexName)
virtual TUniquePtr< IOperator > CreateOperator (const FBuildOperatorParams &InParams, FBuildResults &OutResults) override
Public Member Functions inherited from Metasound::IOperatorFactory
virtual ~IOperatorFactory ()=default
Private Types
using FPassThroughDataReference = std::conditional_t<bIsReferenceVertexAccess, TDataReadReference<DataType>, TDataValueReference<DataType>>
Private Member Functions
FPassThroughDataReference CreatePassThroughDataReference (const FAnyDataReference &InRef)
Private Attributes
FVertexName VertexName
Static Private Attributes
static constexpr bool bIsReferenceVertexAccess = VertexAccess == EVertexAccessType::Reference
static constexpr bool bIsValueVertexAccess = VertexAccess == EVertexAccessType::Value
Detailed Description
template<typename DataType, EVertexAccessType VertexAccess = EVertexAccessType::Reference>
class Metasound::MetasoundInputNodePrivate::TInputNodeOperatorFactory< DataType, VertexAccess >
Definition at line 253 of file MetasoundInputNode.h.
Member Typedef Documentation
FPassThroughDataReference
template<typename DataType, EVertexAccessType VertexAccess = EVertexAccessType::Reference> using Metasound::MetasoundInputNodePrivate::TInputNodeOperatorFactory< DataType, VertexAccess >::FPassThroughDataReference = std::conditional_t<bIsReferenceVertexAccess, TDataReadReference<DataType>, TDataValueReference<DataType>> private
Definition at line 261 of file MetasoundInputNode.h.
Constructor & Destructor Documentation
TInputNodeOperatorFactory()
template<typename DataType, EVertexAccessType VertexAccess = EVertexAccessType::Reference> Metasound::MetasoundInputNodePrivate::TInputNodeOperatorFactory< DataType, VertexAccess >::TInputNodeOperatorFactory (const FVertexName & InVertexName) inline explicit
Definition at line 281 of file MetasoundInputNode.h.
References VertexName.
Member Function Documentation
CreateOperator()
template<typename DataType, EVertexAccessType VertexAccess = EVertexAccessType::Reference> virtual TUniquePtr< IOperator > Metasound::MetasoundInputNodePrivate::TInputNodeOperatorFactory< DataType, VertexAccess >::CreateOperator (const FBuildOperatorParams & InParams, FBuildResults & OutResults) inline override virtual
Implements Metasound::IOperatorFactory.
Definition at line 286 of file MetasoundInputNode.h.
References bIsReferenceVertexAccess, CreatePassThroughDataReference(), Metasound::FInputVertexInterfaceData::FindDataReference(), Metasound::FBuildOperatorParams::InputData, MakeUnique(), Metasound::FBuildOperatorParams::OperatorSettings, VertexName, and Metasound::Write.
CreatePassThroughDataReference()
template<typename DataType, EVertexAccessType VertexAccess = EVertexAccessType::Reference> FPassThroughDataReference Metasound::MetasoundInputNodePrivate::TInputNodeOperatorFactory< DataType, VertexAccess >::CreatePassThroughDataReference (const FAnyDataReference & InRef) inline private
Definition at line 264 of file MetasoundInputNode.h.
References bIsReferenceVertexAccess, bIsValueVertexAccess, Metasound::FAnyDataReference::GetDataReadReference(), and Metasound::FAnyDataReference::GetDataValueReference().
Referenced by CreateOperator().
Field Documentation
bIsReferenceVertexAccess
template<typename DataType, EVertexAccessType VertexAccess = EVertexAccessType::Reference> bool Metasound::MetasoundInputNodePrivate::TInputNodeOperatorFactory< DataType, VertexAccess >::bIsReferenceVertexAccess = VertexAccess == EVertexAccessType::Reference static constexpr private
Definition at line 255 of file MetasoundInputNode.h.
Referenced by CreateOperator(), and CreatePassThroughDataReference().
bIsValueVertexAccess
template<typename DataType, EVertexAccessType VertexAccess = EVertexAccessType::Reference> bool Metasound::MetasoundInputNodePrivate::TInputNodeOperatorFactory< DataType, VertexAccess >::bIsValueVertexAccess = VertexAccess == EVertexAccessType::Value static constexpr private
Definition at line 256 of file MetasoundInputNode.h.
Referenced by CreatePassThroughDataReference().
VertexName
template<typename DataType, EVertexAccessType VertexAccess = EVertexAccessType::Reference> FVertexName Metasound::MetasoundInputNodePrivate::TInputNodeOperatorFactory< DataType, VertexAccess >::VertexName private
Definition at line 310 of file MetasoundInputNode.h.
Referenced by TInputNodeOperatorFactory(), and CreateOperator().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/Metasound/Source/MetasoundFrontend/Public/MetasoundInputNode.h