Unreal Engine 5.6 C++ API: Metasound::FBuildErrorBase Class Reference
Metasound::FBuildErrorBase Class Reference
FBuildErrorBase.
#include "MetasoundBuildError.h"
Public Member Functions
METASOUNDGRAPHCORE_API FBuildErrorBase (const FName &InErrorType, const FText &InErrorDescription)
virtual ~FBuildErrorBase ()=default
virtual METASOUNDGRAPHCORE_API const TArray< FDataEdge > & GetDataEdges () const override
Returns an array of edges associated with the error.
virtual METASOUNDGRAPHCORE_API const FText & GetErrorDescription () const override
Returns a human readable error description.
virtual METASOUNDGRAPHCORE_API const FName & GetErrorType () const override
Returns the type of error.
virtual METASOUNDGRAPHCORE_API const TArray< FInputDataDestination > & GetInputDataDestinations () const override
Returns an array of destinations associated with the error.
virtual METASOUNDGRAPHCORE_API const TArray< const INode * > & GetNodes () const override
Returns an array of Nodes associated with the error.
virtual METASOUNDGRAPHCORE_API const TArray< FOutputDataSource > & GetOutputDataSources () const override
Returns an array of sources associated with the error.
Public Member Functions inherited from Metasound::IOperatorBuildError
virtual ~IOperatorBuildError ()=default
Protected Member Functions
METASOUNDGRAPHCORE_API void AddDataEdge (const FDataEdge &InEdge)
METASOUNDGRAPHCORE_API void AddDataEdges (TArrayView< const FDataEdge > InEdges)
METASOUNDGRAPHCORE_API void AddInputDataDestination (const FInputDataDestination &InInputDataDestination)
METASOUNDGRAPHCORE_API void AddInputDataDestinations (TArrayView< const FInputDataDestination > InInputDataDestinations)
METASOUNDGRAPHCORE_API void AddNode (const INode &InNode)
METASOUNDGRAPHCORE_API void AddNodes (TArrayView< INode const *const > InNodes)
METASOUNDGRAPHCORE_API void AddOutputDataSource (const FOutputDataSource &InOutputDataSource)
METASOUNDGRAPHCORE_API void AddOutputDataSources (TArrayView< const FOutputDataSource > InOutputDataSources)
Private Attributes
TArray< FInputDataDestination > Destinations
TArray< FDataEdge > Edges
FText ErrorDescription
FName ErrorType
TArray< const INode * > Nodes
TArray< FOutputDataSource > Sources
Detailed Description
FBuildErrorBase.
A general build error which contains a error type and human readable error description.
Definition at line 20 of file MetasoundBuildError.h.
Constructor & Destructor Documentation
FBuildErrorBase()
METASOUNDGRAPHCORE_API Metasound::FBuildErrorBase::FBuildErrorBase (const FName & InErrorType, const FText & InErrorDescription)
References UE_API.
Referenced by Metasound::FMissingOutputNodeInputReferenceError::FMissingOutputNodeInputReferenceError(), and Metasound::FMissingOutputNodeInputReferenceError::FMissingOutputNodeInputReferenceError().
~FBuildErrorBase()
virtual Metasound::FBuildErrorBase::~FBuildErrorBase () virtual default
Member Function Documentation
AddDataEdge()
METASOUNDGRAPHCORE_API void Metasound::FBuildErrorBase::AddDataEdge (const FDataEdge & InEdge) protected
References UE_API.
AddDataEdges()
METASOUNDGRAPHCORE_API void Metasound::FBuildErrorBase::AddDataEdges (TArrayView< const FDataEdge > InEdges) protected
References UE_API.
AddInputDataDestination()
METASOUNDGRAPHCORE_API void Metasound::FBuildErrorBase::AddInputDataDestination (const FInputDataDestination & InInputDataDestination) protected
References UE_API.
AddInputDataDestinations()
METASOUNDGRAPHCORE_API void Metasound::FBuildErrorBase::AddInputDataDestinations (TArrayView< const FInputDataDestination > InInputDataDestinations) protected
References UE_API.
AddNode()
METASOUNDGRAPHCORE_API void Metasound::FBuildErrorBase::AddNode (const INode & InNode) protected
References UE_API.
Referenced by Metasound::FMissingOutputNodeInputReferenceError::FMissingOutputNodeInputReferenceError(), and Metasound::FMissingOutputNodeInputReferenceError::FMissingOutputNodeInputReferenceError().
AddNodes()
METASOUNDGRAPHCORE_API void Metasound::FBuildErrorBase::AddNodes (TArrayView< INode const *const > InNodes) protected
References UE_API.
AddOutputDataSource()
METASOUNDGRAPHCORE_API void Metasound::FBuildErrorBase::AddOutputDataSource (const FOutputDataSource & InOutputDataSource) protected
References UE_API.
AddOutputDataSources()
METASOUNDGRAPHCORE_API void Metasound::FBuildErrorBase::AddOutputDataSources (TArrayView< const FOutputDataSource > InOutputDataSources) protected
References UE_API.
GetDataEdges()
virtual METASOUNDGRAPHCORE_API const TArray< FDataEdge > & Metasound::FBuildErrorBase::GetDataEdges () const override virtual
Returns an array of edges associated with the error.
Implements Metasound::IOperatorBuildError.
References UE_API.
GetErrorDescription()
virtual METASOUNDGRAPHCORE_API const FText & Metasound::FBuildErrorBase::GetErrorDescription () const override virtual
Returns a human readable error description.
Implements Metasound::IOperatorBuildError.
References UE_API.
GetErrorType()
virtual METASOUNDGRAPHCORE_API const FName & Metasound::FBuildErrorBase::GetErrorType () const override virtual
Returns the type of error.
Implements Metasound::IOperatorBuildError.
References UE_API.
GetInputDataDestinations()
virtual METASOUNDGRAPHCORE_API const TArray< FInputDataDestination > & Metasound::FBuildErrorBase::GetInputDataDestinations () const override virtual
Returns an array of destinations associated with the error.
Implements Metasound::IOperatorBuildError.
References UE_API.
GetNodes()
virtual METASOUNDGRAPHCORE_API const TArray< const INode * > & Metasound::FBuildErrorBase::GetNodes () const override virtual
Returns an array of Nodes associated with the error.
Implements Metasound::IOperatorBuildError.
References UE_API.
GetOutputDataSources()
virtual METASOUNDGRAPHCORE_API const TArray< FOutputDataSource > & Metasound::FBuildErrorBase::GetOutputDataSources () const override virtual
Returns an array of sources associated with the error.
Implements Metasound::IOperatorBuildError.
References UE_API.
Field Documentation
Destinations
TArray<FInputDataDestination> Metasound::FBuildErrorBase::Destinations private
Definition at line 71 of file MetasoundBuildError.h.
Edges
TArray<FDataEdge> Metasound::FBuildErrorBase::Edges private
Definition at line 70 of file MetasoundBuildError.h.
ErrorDescription
FText Metasound::FBuildErrorBase::ErrorDescription private
Definition at line 67 of file MetasoundBuildError.h.
ErrorType
FName Metasound::FBuildErrorBase::ErrorType private
Definition at line 66 of file MetasoundBuildError.h.
Nodes
TArray<const INode*> Metasound::FBuildErrorBase::Nodes private
Definition at line 69 of file MetasoundBuildError.h.
Sources
TArray<FOutputDataSource> Metasound::FBuildErrorBase::Sources private
Definition at line 72 of file MetasoundBuildError.h.
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/Metasound/Source/MetasoundGraphCore/Public/MetasoundBuildError.h