Unreal Engine 5.6 C++ API: FGenericPlatformChunkInstall Class Reference
FGenericPlatformChunkInstall Class Reference
Generic implementation of chunk based install.
#include "GenericPlatformChunkInstall.h"
Public Member Functions
virtual FDelegateHandle AddChunkInstallDelegate (FPlatformChunkInstallDelegate Delegate) override
Request a delegate callback on chunk install completion or failure.
virtual FDelegateHandle AddNamedChunkCompleteDelegate (FPlatformNamedChunkCompleteDelegate Delegate) override
Request a delegate callback on named chunk install completion or failure.
virtual FDelegateHandle AddNamedChunkInstallDelegate (FPlatformNamedChunkInstallDelegate Delegate) override
virtual void AsyncInit (TFunction< void(bool)> OnInitComplete) override
Initialize the platform chunk installer in the background.
virtual bool DebugStartNextChunk () override
For platforms that support emulation of the Chunk install.
virtual void ExternalNotifyChunkAvailable (uint32 InChunkID) override
Allow an external system to notify that a particular chunk ID has become available Initial use-case is for dynamically encrypted pak files to signal to the outside world that it has become available.
virtual float GetChunkProgress (uint32 ChunkID, EChunkProgressReportingType::Type ReportType) override
Get the current install progress of a chunk.
virtual EChunkInstallSpeed::Type GetInstallSpeed () override
Inquire about the priority of chunk installation vs.
virtual bool GetNamedChunkInstallationStatus (const FName NamedChunk, FChunkInstallationStatusDetail &OutChunkStatusDetail) const override
Get detailed installation status for the given named chunk.
virtual EChunkLocation::Type GetNamedChunkLocation (const FName NamedChunk) override
Get the current location of the given named chunk.
virtual float GetNamedChunkProgress (const FName NamedChunk, EChunkProgressReportingType::Type ReportType) override
Get the current install progress of the given named chunk.
virtual TArray< FName > GetNamedChunksByType (ENamedChunkType NamedChunkType) const override
Get a list of all the named chunks of the given type.
virtual ENamedChunkType GetNamedChunkType (const FName NamedChunk) const override
Query the type of the given named chunk.
virtual EChunkLocation::Type GetPakchunkLocation (int32 PakchunkIndex) override
Get the current location of a chunk with pakchunk index.
virtual bool GetPakFilesInNamedChunk (const FName NamedChunk, TArray< FString > &OutFilesInChunk) const override
Get the list of pak files in the given named chunk.
virtual bool GetProgressReportingTypeSupported (EChunkProgressReportingType::Type ReportType) override
Check if a given reporting type is supported.
virtual bool InstallNamedChunk (const FName NamedChunk) override
Install the given named chunk.
virtual bool InstallNamedChunks (const TArrayView< const FName > &NamedChunks) override
Install the given set of named chunks.
virtual bool IsAvailable () const
Returns whether chunk installation is available (i.e.
virtual bool IsNamedChunkForCurrentLocale (const FName NamedChunk) const
Determine if the given named chunk is suitable for the current system locale.
virtual bool IsNamedChunkInProgress (const FName NamedChunk) override
Check whether the give chunk is being installed.
virtual bool PrioritizeChunk (uint32 ChunkID, EChunkPriority::Type Priority) override
Hint to the installer that we would like to prioritize a specific chunk.
virtual bool PrioritizeNamedChunk (const FName NamedChunk, EChunkPriority::Type Priority) override
Hint to the installer that we would like to prioritize a specific chunk.
virtual bool PrioritizePakchunk (int32 PakchunkIndex, EChunkPriority::Type Priority)
Hint to the installer that we would like to prioritize a specific chunk.
virtual void RemoveChunkInstallDelegate (FDelegateHandle Delegate) override
Remove a delegate callback on chunk install completion.
virtual void RemoveNamedChunkCompleteDelegate (FDelegateHandle Delegate) override
Remove a delegate callback on named chunk install completion.
virtual void RemoveNamedChunkInstallDelegate (FDelegateHandle Delegate) override
virtual bool SetAutoPakMountingEnabled (bool bEnabled)
Set whether pak files are auto-mounted when they are installed (the default is that they are mounted)
virtual bool SetInstallSpeed (EChunkInstallSpeed::Type InstallSpeed) override
Specify the priority of chunk installation vs.
virtual bool SupportsBundleSource () const override
Returns whether this platform chunk installer implements all the API functions to support the platform chunk install bundle source.
virtual bool SupportsNamedChunkInstall () const override
Check whether current platform supports chunk installation by name.
virtual bool UninstallNamedChunk (const FName NamedChunk) override
Uninstall the given named chunk.
virtual bool UninstallNamedChunks (const TArrayView< const FName > &NamedChunks) override
Uninstall the given set of named chunks.
Public Member Functions inherited from IPlatformChunkInstall
virtual ~IPlatformChunkInstall ()
Virtual destructor.
UE_DEPRECATED (5.4, "use AddNamedChunkCompleteDelegate instead") virtual FDelegateHandle AddNamedChunkInstallDelegate(FPlatformNamedChunkInstallDelegate Delegate)=0
Request a delegate callback on named chunk install completion or failure.
UE_DEPRECATED (5.4, "use RemoveNamedChunkCompleteDelegate instead") virtual void RemoveNamedChunkInstallDelegate(FDelegateHandle Delegate)=0
Remove a delegate callback on named chunk install completion.
Protected Member Functions
void DoNamedChunkCompleteCallbacks (const FName NamedChunk, EChunkLocation::Type Location, bool bHasSucceeded) const
void DoNamedChunkCompleteCallbacks (const TArrayView< const FName > &NamedChunks, EChunkLocation::Type Location, bool bHasSucceeded) const
virtual EChunkLocation::Type GetChunkLocation (uint32 ChunkID) override
Get the current location of a chunk.
Protected Attributes
FPlatformChunkInstallMultiDelegate InstallDelegate
Delegates called when installation succeeds or fails.
FPlatformNamedChunkCompleteMultiDelegate NamedChunkCompleteDelegate
FPlatformNamedChunkInstallMultiDelegate NamedChunkInstallDelegate
Detailed Description
Generic implementation of chunk based install.
Definition at line 389 of file GenericPlatformChunkInstall.h.
Member Function Documentation
AddChunkInstallDelegate()
virtual FDelegateHandle FGenericPlatformChunkInstall::AddChunkInstallDelegate (FPlatformChunkInstallDelegate Delegate) inline override virtual
Request a delegate callback on chunk install completion or failure.
Request may not be respected.
Parameters
Delegate The delegate to call when any chunk is installed or fails to install
Returns
Handle to the bound delegate
Implements IPlatformChunkInstall.
Definition at line 453 of file GenericPlatformChunkInstall.h.
References InstallDelegate.
AddNamedChunkCompleteDelegate()
virtual FDelegateHandle FGenericPlatformChunkInstall::AddNamedChunkCompleteDelegate (FPlatformNamedChunkCompleteDelegate Delegate) inline override virtual
Request a delegate callback on named chunk install completion or failure.
Request may not be respected.
Parameters
Delegate The delegate to call when any named chunk is installed or fails to install
Returns
Handle to the bound delegate
Implements IPlatformChunkInstall.
Definition at line 533 of file GenericPlatformChunkInstall.h.
References NamedChunkCompleteDelegate.
AddNamedChunkInstallDelegate()
virtual FDelegateHandle FGenericPlatformChunkInstall::AddNamedChunkInstallDelegate (FPlatformNamedChunkInstallDelegate Delegate) inline override virtual
Definition at line 518 of file GenericPlatformChunkInstall.h.
References NamedChunkInstallDelegate.
AsyncInit()
virtual void FGenericPlatformChunkInstall::AsyncInit (TFunction< void(bool)> OnInitComplete) override virtual
Initialize the platform chunk installer in the background.
May require opt-in for the platform-specific chunk installer due to backwards compatility concerns.
Parameters
OnInitialized Callback for when asyncronous initialization is completed.
Implements IPlatformChunkInstall.
DebugStartNextChunk()
virtual bool FGenericPlatformChunkInstall::DebugStartNextChunk () inline override virtual
For platforms that support emulation of the Chunk install.
Starts transfer of the next chunk. Does nothing in a shipping build.
Returns
true if the operation succeeds.
Implements IPlatformChunkInstall.
Definition at line 443 of file GenericPlatformChunkInstall.h.
DoNamedChunkCompleteCallbacks() [1/2]
void FGenericPlatformChunkInstall::DoNamedChunkCompleteCallbacks (const FName NamedChunk, EChunkLocation::Type Location, bool bHasSucceeded) const protected
References Location.
DoNamedChunkCompleteCallbacks() [2/2]
void FGenericPlatformChunkInstall::DoNamedChunkCompleteCallbacks (const TArrayView< const FName > & NamedChunks, EChunkLocation::Type Location, bool bHasSucceeded) const protected
References Location.
ExternalNotifyChunkAvailable()
virtual void FGenericPlatformChunkInstall::ExternalNotifyChunkAvailable (uint32 InChunkID) inline override virtual
Allow an external system to notify that a particular chunk ID has become available Initial use-case is for dynamically encrypted pak files to signal to the outside world that it has become available.
Parameters
InChunkID - ID of the chunk that has just become available
Implements IPlatformChunkInstall.
Definition at line 448 of file GenericPlatformChunkInstall.h.
References InstallDelegate.
GetChunkLocation()
virtual EChunkLocation::Type FGenericPlatformChunkInstall::GetChunkLocation (uint32 ChunkID) inline override protected virtual
Get the current location of a chunk.
Pakchunk index and platform chunk id are not always the same. Call GetPakchunkLocation instead of calling from outside.
Parameters
ChunkID The id of the chunk to check.
Returns
Enum specifying whether the chunk is available to use, waiting to install, or does not exist.
Implements IPlatformChunkInstall.
Definition at line 574 of file GenericPlatformChunkInstall.h.
References EChunkLocation::LocalFast.
GetChunkProgress()
virtual float FGenericPlatformChunkInstall::GetChunkProgress (uint32 ChunkID, EChunkProgressReportingType::Type ReportType) inline override virtual
Get the current install progress of a chunk.
Let the user specify report type for platforms that support more than one.
Parameters
ChunkID The id of the chunk to check.
ReportType The type of progress report you want.
Returns
A value whose meaning is dependent on the ReportType param.
Implements IPlatformChunkInstall.
Definition at line 419 of file GenericPlatformChunkInstall.h.
References EChunkProgressReportingType::PercentageComplete.
GetInstallSpeed()
virtual EChunkInstallSpeed::Type FGenericPlatformChunkInstall::GetInstallSpeed () inline override virtual
Inquire about the priority of chunk installation vs.
game IO.
Returns
Paused, low or high priority.
Implements IPlatformChunkInstall.
Definition at line 428 of file GenericPlatformChunkInstall.h.
References EChunkInstallSpeed::Paused.
GetNamedChunkInstallationStatus()
virtual bool FGenericPlatformChunkInstall::GetNamedChunkInstallationStatus (const FName NamedChunk, FChunkInstallationStatusDetail & OutChunkStatusDetail) const inline override virtual
Get detailed installation status for the given named chunk.
Parameters
NamedChunk The named chunk to query
OutChunkStatusDetail (out) structure that will contain the status detail
Returns
true if the structure has been filled in
Implements IPlatformChunkInstall.
Definition at line 554 of file GenericPlatformChunkInstall.h.
GetNamedChunkLocation()
virtual EChunkLocation::Type FGenericPlatformChunkInstall::GetNamedChunkLocation (const FName NamedChunk) inline override virtual
Get the current location of the given named chunk.
Parameters
NamedChunk The name of the chunk
Returns
Enum specifying whether the chunk is available to use, waiting to install, or does not exist.
Implements IPlatformChunkInstall.
Definition at line 493 of file GenericPlatformChunkInstall.h.
References EChunkLocation::NotAvailable.
GetNamedChunkProgress()
virtual float FGenericPlatformChunkInstall::GetNamedChunkProgress (const FName NamedChunk, EChunkProgressReportingType::Type ReportType) inline override virtual
Get the current install progress of the given named chunk.
Let the user specify report type for platforms that support more than one.
Parameters
NamedChunk The name of the chunk
ReportType The type of progress report you want.
Returns
A value whose meaning is dependent on the ReportType param.
Implements IPlatformChunkInstall.
Definition at line 498 of file GenericPlatformChunkInstall.h.
GetNamedChunksByType()
virtual TArray< FName > FGenericPlatformChunkInstall::GetNamedChunksByType (ENamedChunkType NamedChunkType) const inline override virtual
Get a list of all the named chunks of the given type.
Parameters
Enum indicating the type of chunk
Returns
Array containing all named chunks of the given type
Implements IPlatformChunkInstall.
Definition at line 513 of file GenericPlatformChunkInstall.h.
GetNamedChunkType()
virtual ENamedChunkType FGenericPlatformChunkInstall::GetNamedChunkType (const FName NamedChunk) const inline override virtual
Query the type of the given named chunk.
Parameters
NamedChunk The name of the chunk
Returns
Enum indicating the type of chunk, if any
Implements IPlatformChunkInstall.
Definition at line 508 of file GenericPlatformChunkInstall.h.
References Invalid.
GetPakchunkLocation()
virtual EChunkLocation::Type FGenericPlatformChunkInstall::GetPakchunkLocation (int32 PakchunkIndex) inline override virtual
Get the current location of a chunk with pakchunk index.
Parameters
PakchunkIndex The id of the pak chunk.
Returns
Enum specifying whether the chunk is available to use, waiting to install, or does not exist.
Implements IPlatformChunkInstall.
Definition at line 399 of file GenericPlatformChunkInstall.h.
References IPlatformChunkInstall::GetChunkLocation().
GetPakFilesInNamedChunk()
virtual bool FGenericPlatformChunkInstall::GetPakFilesInNamedChunk (const FName NamedChunk, TArray< FString > & OutFilesInChunk) const inline override virtual
Get the list of pak files in the given named chunk.
Parameters
NamedChunk The named chunk to query
OutFilesInChunk The pak files names in the named chunk
Returns
true if the named chunk is valid and this function is supported
Implements IPlatformChunkInstall.
Definition at line 549 of file GenericPlatformChunkInstall.h.
GetProgressReportingTypeSupported()
virtual bool FGenericPlatformChunkInstall::GetProgressReportingTypeSupported (EChunkProgressReportingType::Type ReportType) inline override virtual
Check if a given reporting type is supported.
Parameters
ReportType Enum specifying how progress is reported.
Returns
true if reporting type is supported on the current platform.
Implements IPlatformChunkInstall.
Definition at line 409 of file GenericPlatformChunkInstall.h.
References EChunkProgressReportingType::PercentageComplete.
InstallNamedChunk()
virtual bool FGenericPlatformChunkInstall::InstallNamedChunk (const FName NamedChunk) inline override virtual
Install the given named chunk.
Parameters
NamedChunk The name of the chunk
Returns
whether installation task has been kicked
Implements IPlatformChunkInstall.
Definition at line 473 of file GenericPlatformChunkInstall.h.
References IPlatformChunkInstall::InstallNamedChunks(), and MakeArrayView().
InstallNamedChunks()
virtual bool FGenericPlatformChunkInstall::InstallNamedChunks (const TArrayView< const FName > & NamedChunks) inline override virtual
Install the given set of named chunks.
Parameters
NamedChunks The names of the chunks to install
Returns
whether installation task has been kicked
Implements IPlatformChunkInstall.
Definition at line 483 of file GenericPlatformChunkInstall.h.
IsAvailable()
virtual bool FGenericPlatformChunkInstall::IsAvailable () const inline virtual
Returns whether chunk installation is available (i.e.
we are an installed packaged build etc)
Implements IPlatformChunkInstall.
Definition at line 394 of file GenericPlatformChunkInstall.h.
IsNamedChunkForCurrentLocale()
virtual bool FGenericPlatformChunkInstall::IsNamedChunkForCurrentLocale (const FName NamedChunk) const inline virtual
Determine if the given named chunk is suitable for the current system locale.
Parameters
NamedChunk The named chunk to query
Returns
false if the chunk is associated with a different locale
Implements IPlatformChunkInstall.
Definition at line 559 of file GenericPlatformChunkInstall.h.
IsNamedChunkInProgress()
virtual bool FGenericPlatformChunkInstall::IsNamedChunkInProgress (const FName NamedChunk) inline override virtual
Check whether the give chunk is being installed.
Parameters
NamedChunk The name of the chunk
Returns
whether installation task has been kicked
Implements IPlatformChunkInstall.
Definition at line 468 of file GenericPlatformChunkInstall.h.
PrioritizeChunk()
virtual bool FGenericPlatformChunkInstall::PrioritizeChunk (uint32 ChunkID, EChunkPriority::Type Priority) inline override virtual
Hint to the installer that we would like to prioritize a specific chunk.
Parameters
ChunkID The id of the chunk to prioritize.
Priority The priority for the chunk.
Returns
false if the operation is not allowed or the chunk doesn't exist, otherwise true.
Implements IPlatformChunkInstall.
Definition at line 438 of file GenericPlatformChunkInstall.h.
PrioritizeNamedChunk()
virtual bool FGenericPlatformChunkInstall::PrioritizeNamedChunk (const FName NamedChunk, EChunkPriority::Type Priority) inline override virtual
Hint to the installer that we would like to prioritize a specific chunk.
Parameters
NamedChunk The name of the chunk
Priority The priority for the chunk.
Returns
false if the operation is not allowed or the chunk doesn't exist, otherwise true.
Implements IPlatformChunkInstall.
Definition at line 503 of file GenericPlatformChunkInstall.h.
PrioritizePakchunk()
virtual bool FGenericPlatformChunkInstall::PrioritizePakchunk (int32 PakchunkIndex, EChunkPriority::Type Priority) inline virtual
Hint to the installer that we would like to prioritize a specific chunk.
Parameters
PakchunkIndex The index of the pakchunk to prioritize.
Priority The priority for the chunk.
Returns
false if the operation is not allowed or the chunk doesn't exist, otherwise true.
Implements IPlatformChunkInstall.
Definition at line 404 of file GenericPlatformChunkInstall.h.
References IPlatformChunkInstall::PrioritizeChunk().
RemoveChunkInstallDelegate()
virtual void FGenericPlatformChunkInstall::RemoveChunkInstallDelegate (FDelegateHandle Delegate) inline override virtual
Remove a delegate callback on chunk install completion.
Parameters
Delegate The delegate to remove.
Implements IPlatformChunkInstall.
Definition at line 458 of file GenericPlatformChunkInstall.h.
References InstallDelegate.
RemoveNamedChunkCompleteDelegate()
virtual void FGenericPlatformChunkInstall::RemoveNamedChunkCompleteDelegate (FDelegateHandle Delegate) inline override virtual
Remove a delegate callback on named chunk install completion.
Parameters
Delegate The delegate to remove.
Implements IPlatformChunkInstall.
Definition at line 528 of file GenericPlatformChunkInstall.h.
References NamedChunkCompleteDelegate.
RemoveNamedChunkInstallDelegate()
virtual void FGenericPlatformChunkInstall::RemoveNamedChunkInstallDelegate (FDelegateHandle Delegate) inline override virtual
Definition at line 523 of file GenericPlatformChunkInstall.h.
References NamedChunkInstallDelegate.
SetAutoPakMountingEnabled()
virtual bool FGenericPlatformChunkInstall::SetAutoPakMountingEnabled (bool bEnabled) inline virtual
Set whether pak files are auto-mounted when they are installed (the default is that they are mounted)
Parameters
bEnabled Whether to auto-mount pak files
Returns
false if this function is not supported
Implements IPlatformChunkInstall.
Definition at line 544 of file GenericPlatformChunkInstall.h.
SetInstallSpeed()
virtual bool FGenericPlatformChunkInstall::SetInstallSpeed (EChunkInstallSpeed::Type InstallSpeed) inline override virtual
Specify the priority of chunk installation vs.
game IO.
Parameters
InstallSpeed Pause, low or high priority.
Returns
false if the operation is not allowed, otherwise true.
Implements IPlatformChunkInstall.
Definition at line 433 of file GenericPlatformChunkInstall.h.
SupportsBundleSource()
virtual bool FGenericPlatformChunkInstall::SupportsBundleSource () const inline override virtual
Returns whether this platform chunk installer implements all the API functions to support the platform chunk install bundle source.
Implements IPlatformChunkInstall.
Definition at line 539 of file GenericPlatformChunkInstall.h.
SupportsNamedChunkInstall()
virtual bool FGenericPlatformChunkInstall::SupportsNamedChunkInstall () const inline override virtual
Check whether current platform supports chunk installation by name.
Returns
whether Intelligent Install is supported
Implements IPlatformChunkInstall.
Definition at line 463 of file GenericPlatformChunkInstall.h.
UninstallNamedChunk()
virtual bool FGenericPlatformChunkInstall::UninstallNamedChunk (const FName NamedChunk) inline override virtual
Uninstall the given named chunk.
Parameters
NamedChunk The name of the chunk
Returns
whether uninstallation task has been kicked
Implements IPlatformChunkInstall.
Definition at line 478 of file GenericPlatformChunkInstall.h.
References MakeArrayView(), and IPlatformChunkInstall::UninstallNamedChunks().
UninstallNamedChunks()
virtual bool FGenericPlatformChunkInstall::UninstallNamedChunks (const TArrayView< const FName > & NamedChunks) inline override virtual
Uninstall the given set of named chunks.
Parameters
NamedChunk The names of the chunks to uninstall
Returns
whether uninstallation task has been kicked
Implements IPlatformChunkInstall.
Definition at line 488 of file GenericPlatformChunkInstall.h.
Field Documentation
InstallDelegate
FPlatformChunkInstallMultiDelegate FGenericPlatformChunkInstall::InstallDelegate protected
Delegates called when installation succeeds or fails.
Definition at line 570 of file GenericPlatformChunkInstall.h.
Referenced by AddChunkInstallDelegate(), ExternalNotifyChunkAvailable(), and RemoveChunkInstallDelegate().
NamedChunkCompleteDelegate
FPlatformNamedChunkCompleteMultiDelegate FGenericPlatformChunkInstall::NamedChunkCompleteDelegate protected
Definition at line 572 of file GenericPlatformChunkInstall.h.
Referenced by AddNamedChunkCompleteDelegate(), and RemoveNamedChunkCompleteDelegate().
NamedChunkInstallDelegate
FPlatformNamedChunkInstallMultiDelegate FGenericPlatformChunkInstall::NamedChunkInstallDelegate protected
Definition at line 571 of file GenericPlatformChunkInstall.h.
Referenced by AddNamedChunkInstallDelegate(), and RemoveNamedChunkInstallDelegate().
The documentation for this class was generated from the following file:
Runtime/Core/Public/GenericPlatform/GenericPlatformChunkInstall.h