Unreal Engine 5.6 C++ API: FAutoConsoleVariableRef Class Reference
FAutoConsoleVariableRef Class Reference
Autoregistering float, int, bool, FString REF variable class...this changes that value when the console variable is changed.
#include "IConsoleManager.h"
Public Member Functions
FAutoConsoleVariableRef (const TCHAR *Name, bool &RefValue, const TCHAR *Help, const FConsoleVariableDelegate &Callback, uint32 Flags=ECVF_Default)
Create a reference to a bool console variable.
FAutoConsoleVariableRef (const TCHAR *Name, bool &RefValue, const TCHAR *Help, uint32 Flags=ECVF_Default)
Create a reference to a bool console variable.
FAutoConsoleVariableRef (const TCHAR *Name, float &RefValue, const TCHAR *Help, const FConsoleVariableDelegate &Callback, uint32 Flags=ECVF_Default)
Create a reference to a float console variable.
FAutoConsoleVariableRef (const TCHAR *Name, float &RefValue, const TCHAR *Help, uint32 Flags=ECVF_Default)
Create a reference to a float console variable.
FAutoConsoleVariableRef (const TCHAR *Name, FName &RefValue, const TCHAR *Help, uint32 Flags=ECVF_Default)
Create a reference to a FName console variable.
FAutoConsoleVariableRef (const TCHAR *Name, FString &RefValue, const TCHAR *Help, const FConsoleVariableDelegate &Callback, uint32 Flags=ECVF_Default)
Create a reference to a FString console variable.
FAutoConsoleVariableRef (const TCHAR *Name, FString &RefValue, const TCHAR *Help, uint32 Flags=ECVF_Default)
Create a reference to a FString console variable.
FAutoConsoleVariableRef (const TCHAR *Name, int32 &RefValue, const TCHAR *Help, const FConsoleVariableDelegate &Callback, uint32 Flags=ECVF_Default)
Create a reference to a int console variable.
FAutoConsoleVariableRef (const TCHAR *Name, int32 &RefValue, const TCHAR *Help, uint32 Flags=ECVF_Default)
Create a reference to a int console variable.
virtual ~FAutoConsoleVariableRef ()
FORCEINLINE IConsoleVariable & operator* ()
Dereference back to a variable.
FORCEINLINE const IConsoleVariable & operator* () const
FORCEINLINE IConsoleVariable * operator-> ()
Dereference back to a variable.
FORCEINLINE const IConsoleVariable * operator-> () const
Additional Inherited Members
Private Member Functions inherited from FAutoConsoleObject
virtual ~FAutoConsoleObject ()
Destructor, removes the console object.
FORCEINLINE IConsoleVariable * AsVariable ()
returns the contained console object as an IConsoleVariable
FORCEINLINE const IConsoleVariable * AsVariable () const
returns the contained console object as an IConsoleVariable
FAutoConsoleObject (IConsoleObject *InTarget)
Constructor, saves the argument for future removal from the console variable system.
Static Private Member Functions inherited from FAutoConsoleObject
static TArray< const FAutoConsoleObject * > & AccessDesktopShaderChangeCvars ()
static TArray< const FAutoConsoleObject * > & AccessGeneralShaderChangeCvars ()
static TArray< const FAutoConsoleObject * > & AccessMobileShaderChangeCvars ()
Detailed Description
Autoregistering float, int, bool, FString REF variable class...this changes that value when the console variable is changed.
Definition at line 1510 of file IConsoleManager.h.
Constructor & Destructor Documentation
FAutoConsoleVariableRef() [1/9]
FAutoConsoleVariableRef::FAutoConsoleVariableRef (const TCHAR * Name, int32 & RefValue, const TCHAR * Help, uint32 Flags = ECVF_Default) inline
Create a reference to a int console variable.
Parameters
Name must not be 0
Help must not be 0
Flags bitmask combined from EConsoleVariableFlags
Definition at line 1519 of file IConsoleManager.h.
References FAutoConsoleObject::FAutoConsoleObject(), ECVF_Default, Flags, and Name.
FAutoConsoleVariableRef() [2/9]
FAutoConsoleVariableRef::FAutoConsoleVariableRef (const TCHAR * Name, float & RefValue, const TCHAR * Help, uint32 Flags = ECVF_Default) inline
Create a reference to a float console variable.
Parameters
Name must not be 0
Help must not be 0
Flags bitmask combined from EConsoleVariableFlags
Definition at line 1529 of file IConsoleManager.h.
References FAutoConsoleObject::FAutoConsoleObject(), ECVF_Default, Flags, and Name.
FAutoConsoleVariableRef() [3/9]
FAutoConsoleVariableRef::FAutoConsoleVariableRef (const TCHAR * Name, bool & RefValue, const TCHAR * Help, uint32 Flags = ECVF_Default) inline
Create a reference to a bool console variable.
Parameters
Name must not be 0
Help must not be 0
Flags bitmask combined from EConsoleVariableFlags
Definition at line 1539 of file IConsoleManager.h.
References FAutoConsoleObject::FAutoConsoleObject(), ECVF_Default, Flags, and Name.
FAutoConsoleVariableRef() [4/9]
FAutoConsoleVariableRef::FAutoConsoleVariableRef (const TCHAR * Name, FString & RefValue, const TCHAR * Help, uint32 Flags = ECVF_Default) inline
Create a reference to a FString console variable.
Parameters
Name must not be 0
Help must not be 0
Flags bitmask combined from EConsoleVariableFlags
Definition at line 1549 of file IConsoleManager.h.
References FAutoConsoleObject::FAutoConsoleObject(), ECVF_Default, Flags, and Name.
FAutoConsoleVariableRef() [5/9]
FAutoConsoleVariableRef::FAutoConsoleVariableRef (const TCHAR * Name, FName & RefValue, const TCHAR * Help, uint32 Flags = ECVF_Default) inline
Create a reference to a FName console variable.
Parameters
Name must not be 0
Help must not be 0
Flags bitmask combined from EConsoleVariableFlags
Definition at line 1560 of file IConsoleManager.h.
References FAutoConsoleObject::FAutoConsoleObject(), ECVF_Default, Flags, and Name.
FAutoConsoleVariableRef() [6/9]
FAutoConsoleVariableRef::FAutoConsoleVariableRef (const TCHAR * Name, int32 & RefValue, const TCHAR * Help, const FConsoleVariableDelegate & Callback, uint32 Flags = ECVF_Default) inline
Create a reference to a int console variable.
Parameters
Name must not be 0
Help must not be 0
Callback Delegate called when the variable changes.
See also
IConsoleVariable::SetOnChangedCallback
Parameters
Flags bitmask combined from EConsoleVariableFlags
Definition at line 1572 of file IConsoleManager.h.
References FAutoConsoleObject::FAutoConsoleObject(), FAutoConsoleObject::AsVariable(), ECVF_Default, Flags, Name, and IConsoleVariable::SetOnChangedCallback().
FAutoConsoleVariableRef() [7/9]
FAutoConsoleVariableRef::FAutoConsoleVariableRef (const TCHAR * Name, float & RefValue, const TCHAR * Help, const FConsoleVariableDelegate & Callback, uint32 Flags = ECVF_Default) inline
Create a reference to a float console variable.
Parameters
Name must not be 0
Help must not be 0
Callback Delegate called when the variable changes.
See also
IConsoleVariable::SetOnChangedCallback
Parameters
Flags bitmask combined from EConsoleVariableFlags
Definition at line 1585 of file IConsoleManager.h.
References FAutoConsoleObject::FAutoConsoleObject(), FAutoConsoleObject::AsVariable(), ECVF_Default, Flags, Name, and IConsoleVariable::SetOnChangedCallback().
FAutoConsoleVariableRef() [8/9]
FAutoConsoleVariableRef::FAutoConsoleVariableRef (const TCHAR * Name, bool & RefValue, const TCHAR * Help, const FConsoleVariableDelegate & Callback, uint32 Flags = ECVF_Default) inline
Create a reference to a bool console variable.
Parameters
Name must not be 0
Help must not be 0
Callback Delegate called when the variable changes.
See also
IConsoleVariable::SetOnChangedCallback
Parameters
Flags bitmask combined from EConsoleVariableFlags
Definition at line 1598 of file IConsoleManager.h.
References FAutoConsoleObject::FAutoConsoleObject(), FAutoConsoleObject::AsVariable(), ECVF_Default, Flags, Name, and IConsoleVariable::SetOnChangedCallback().
FAutoConsoleVariableRef() [9/9]
FAutoConsoleVariableRef::FAutoConsoleVariableRef (const TCHAR * Name, FString & RefValue, const TCHAR * Help, const FConsoleVariableDelegate & Callback, uint32 Flags = ECVF_Default) inline
Create a reference to a FString console variable.
Parameters
Name must not be 0
Help must not be 0
Callback Delegate called when the variable changes.
See also
IConsoleVariable::SetOnChangedCallback
Parameters
Flags bitmask combined from EConsoleVariableFlags
Definition at line 1611 of file IConsoleManager.h.
References FAutoConsoleObject::FAutoConsoleObject(), FAutoConsoleObject::AsVariable(), ECVF_Default, Flags, Name, and IConsoleVariable::SetOnChangedCallback().
~FAutoConsoleVariableRef()
virtual FAutoConsoleVariableRef::~FAutoConsoleVariableRef () inline virtual
Definition at line 1617 of file IConsoleManager.h.
Member Function Documentation
operator*() [1/2]
FORCEINLINE IConsoleVariable & FAutoConsoleVariableRef::operator* () inline
Dereference back to a variable.
Definition at line 1621 of file IConsoleManager.h.
References FAutoConsoleObject::AsVariable(), and FORCEINLINE.
operator*() [2/2]
FORCEINLINE const IConsoleVariable & FAutoConsoleVariableRef::operator* () const inline
Definition at line 1625 of file IConsoleManager.h.
References FAutoConsoleObject::AsVariable(), and FORCEINLINE.
operator->() [1/2]
FORCEINLINE IConsoleVariable * FAutoConsoleVariableRef::operator-> () inline
Dereference back to a variable.
Definition at line 1630 of file IConsoleManager.h.
References FAutoConsoleObject::AsVariable(), and FORCEINLINE.
operator->() [2/2]
FORCEINLINE const IConsoleVariable * FAutoConsoleVariableRef::operator-> () const inline
Definition at line 1634 of file IConsoleManager.h.
References FAutoConsoleObject::AsVariable(), and FORCEINLINE.
The documentation for this class was generated from the following file:
Runtime/Core/Public/HAL/IConsoleManager.h