Unreal Engine 5.6 C++ API: UParticleModuleRequired Class Reference
UParticleModuleRequired Class Reference
#include "ParticleModuleRequired.h"
Private Member Functions
virtual bool AddModuleCurvesToEditor (UInterpCurveEdSetup *EdSetup, TArray< const FCurveEdEntry * > &OutCurveEntries) override
virtual void BeginDestroy () override
void CacheDerivedData ()
FParticleRequiredModule * CreateRendererResource ()
virtual void FinishDestroy () override
GENERATED_UCLASS_BODY () UPROPERTY() TObjectPtr< class UMaterialInterface > Material
The material to utilize for the emitter at this LOD level.
virtual bool GenerateLODModuleValues (UParticleModule *SourceModule, float Percentage, UParticleLODLevel *LODLevel) override
FRHIShaderResourceView * GetBoundingGeometrySRV () const
void GetDefaultCutout ()
const FVector2f * GetFrameData (int32 FrameIndex) const
virtual EModuleType GetModuleType () const override
int32 GetNumBoundingTriangles () const
int32 GetNumBoundingVertices () const
int32 GetNumFrames () const
void InitBoundingGeometryBuffer ()
void InitializeDefaults ()
Initializes the default values for this property.
bool IsBoundingGeometryValid () const
virtual bool IsReadyForFinishDestroy () override
virtual bool IsValidForLODLevel (UParticleLODLevel *LODLevel, FString &OutErrorString) override
virtual void PostEditChangeProperty (FPropertyChangedEvent &PropertyChangedEvent) override
virtual void PostInitProperties () override
virtual void PostLoad () override
virtual void PreEditChange (FProperty *PropertyAboutToChange) override
virtual void Serialize (FStructuredArchive::FRecord Record) override
virtual void SetToSensibleDefaults (UParticleEmitter *Owner) override
bool ShouldUseVelocityForMotionBlur () const
UPROPERTY () EParticleUVFlipMode UVFlippingMode
Controls UV Flipping for this emitter.
UPROPERTY () float EmitterDelay
Indicates the time (in seconds) that this emitter should be delayed in the particle system.
UPROPERTY () float EmitterDelayLow
The low end of the emitter delay if using a range.
UPROPERTY () float MacroUVRadius
World space radius that UVs generated with the ParticleMacroUV material node will tile based on.
UPROPERTY () float RandomImageTime
The amount of time (particle-relative, 0.0 to 1.0) to 'lock' on a random sub image 0.0 = change every frame 1.0 = select a random image at spawn and hold for the life of the particle.
UPROPERTY () FRotator EmitterRotation
UPROPERTY () FVector EmitterOrigin
UPROPERTY () FVector MacroUVPosition
Local space position that UVs generated with the ParticleMacroUV material node will be centered on.
UPROPERTY () FVector NormalsCylinderDirection
When EmitterNormalsMode is ENM_Cylindrical, particle normals are created to face away from the cylinder going through NormalsSphereCenter in the direction NormalsCylinderDirection.
UPROPERTY() uint8 bDurationRecalcEachLoop UPROPERTY () FVector NormalsSphereCenter
If true, recalculate the emitter duration on each loop.
UPROPERTY () int32 EmitterLoops
The number of times to loop the emitter.
UPROPERTY () int32 MaxDrawCount
The maximum number of particles to DRAW for this emitter.
UPROPERTY () int32 RandomImageChanges
The number of times to change a random image over the life of the particle.
UPROPERTY() uint8 bOrbitModuleAffectsVelocityAlignment UPROPERTY () int32 SubImages_Horizontal
Ensures that movement generated from the orbit module is applied to velocity-aligned particles.
UPROPERTY () int32 SubImages_Vertical
The number of sub-images vertically in the texture.
UPROPERTY () struct FRawDistributionFloat SpawnRate
The rate at which to spawn particles.
UPROPERTY () TArray< FName > NamedMaterialOverrides
Named material overrides for this emitter.
UPROPERTY () TArray< FParticleBurst > BurstList
The array of burst entries.
UPROPERTY () TEnumAsByte< enum EEmitterNormalsMode > EmitterNormalsMode
Normal generation mode for this emitter LOD.
UPROPERTY() uint8 bOverrideSystemMacroUV UPROPERTY() uint8 bUseMaxDrawCount UPROPERTY () TEnumAsByte< enum EOpacitySourceMode > OpacitySourceMode
Override the system MacroUV settings.
UPROPERTY () TEnumAsByte< enum ESubUVBoundingVertexCount > BoundingMode
More bounding vertices results in reduced overdraw, but adds more triangle overhead.
UPROPERTY() uint8 bScaleUV UPROPERTY() uint8 bEmitterDelayUseRange UPROPERTY () TEnumAsByte< EParticleBurstMethod > ParticleBurstMethod
Whether to scale the UV or not - ie, the model wasn't setup with sub uvs.
UPROPERTY () TEnumAsByte< EParticleScreenAlignment > ScreenAlignment
The screen alignment to utilize for the emitter at this LOD level.
UPROPERTY()) uint8 bUseLocalSpace UPROPERTY() uint8 bKillOnDeactivate UPROPERTY() uint8 bKillOnCompleted UPROPERTY () TEnumAsByte< EParticleSortMode > SortMode
If true, update the emitter in local space.
UPROPERTY() uint8 bDelayFirstLoopOnly UPROPERTY () TEnumAsByte< EParticleSubUVInterpMethod > InterpolationMethod
If true, the emitter will be delayed only on the first loop.
UPROPERTY () TObjectPtr< UTexture2D > CutoutTexture
Texture to generate bounding geometry from.
UPROPERTY ()) float AlphaThreshold
Alpha channel values larger than the threshold are considered occupied and will be contained in the bounding geometry.
UPROPERTY() uint8 bUseLegacyEmitterTime UPROPERTY()) uint8 bRemoveHMDRoll UPROPERTY() uint8 bSupportLargeWorldCoordinates UPROPERTY() uint8 bEmitterDurationUseRange UPROPERTY() uint8 bOverrideUseVelocityForMotionBlur UPROPERTY()) uint8 bUseVelocityForMotionBlur UPROPERTY ()) float EmitterDuration
If true, the EmitterTime for the emitter will be calculated by modulating the SecondsSinceCreation by the EmitterDuration.
UPROPERTY ()) float EmitterDurationLow
The low end of the emitter duration if using a range.
UPROPERTY ()) float MaxFacingCameraBlendDistance
The distance at which PSA_FacingCameraDistanceBlend is fully PSA_FacingCameraPosition.
UPROPERTY ()) float MinFacingCameraBlendDistance
The distance at which PSA_FacingCameraDistanceBlend is fully PSA_Square.
Private Attributes
FSubUVBoundingGeometryBuffer * BoundingGeometryBuffer
Used on platforms that support instancing, the bounding geometry is fetched from a vertex shader instead of on the CPU.
FSubUVDerivedData DerivedData
Derived data for this asset, generated off of SubUVTexture.
FRenderCommandFence ReleaseFence
Tracks progress of BoundingGeometryBuffer release during destruction.
Friends
struct FParticleEmitterInstance
class FParticleModuleRequiredDetails
Detailed Description
Definition at line 122 of file ParticleModuleRequired.h.
Member Function Documentation
AddModuleCurvesToEditor()
virtual bool UParticleModuleRequired::AddModuleCurvesToEditor (UInterpCurveEdSetup * EdSetup, TArray< const FCurveEdEntry * > & OutCurveEntries) inline override private virtual
Definition at line 446 of file ParticleModuleRequired.h.
BeginDestroy()
virtual void UParticleModuleRequired::BeginDestroy () override private virtual
CacheDerivedData()
void UParticleModuleRequired::CacheDerivedData () private
CreateRendererResource()
FParticleRequiredModule * UParticleModuleRequired::CreateRendererResource () inline private
Definition at line 487 of file ParticleModuleRequired.h.
References FParticleRequiredModule::AlphaThreshold, FParticleRequiredModule::bCutoutTexureIsValid, FParticleRequiredModule::BoundingGeometryBufferSRV, FParticleRequiredModule::bUseVelocityForMotionBlur, check, DerivedData, FParticleRequiredModule::FrameData, GetBoundingGeometrySRV(), GetNumBoundingTriangles(), GetNumBoundingVertices(), GetNumFrames(), IsBoundingGeometryValid(), FParticleRequiredModule::NumBoundingTriangles, FParticleRequiredModule::NumBoundingVertices, FParticleRequiredModule::NumFrames, and ShouldUseVelocityForMotionBlur().
FinishDestroy()
virtual void UParticleModuleRequired::FinishDestroy () override private virtual
GENERATED_UCLASS_BODY()
UParticleModuleRequired::GENERATED_UCLASS_BODY () private
The material to utilize for the emitter at this LOD level.
References Category, Material, and UPROPERTY().
GenerateLODModuleValues()
virtual bool UParticleModuleRequired::GenerateLODModuleValues (UParticleModule * SourceModule, float Percentage, UParticleLODLevel * LODLevel) override private virtual
References Percentage.
GetBoundingGeometrySRV()
FRHIShaderResourceView * UParticleModuleRequired::GetBoundingGeometrySRV () const inline private
Definition at line 467 of file ParticleModuleRequired.h.
References BoundingGeometryBuffer.
Referenced by CreateRendererResource().
GetDefaultCutout()
void UParticleModuleRequired::GetDefaultCutout () private
GetFrameData()
const FVector2f * UParticleModuleRequired::GetFrameData (int32 FrameIndex) const inline private
Definition at line 482 of file ParticleModuleRequired.h.
References DerivedData, and GetNumBoundingVertices().
GetModuleType()
virtual EModuleType UParticleModuleRequired::GetModuleType () const inline override private virtual
Definition at line 451 of file ParticleModuleRequired.h.
GetNumBoundingTriangles()
int32 UParticleModuleRequired::GetNumBoundingTriangles () const inline private
Definition at line 477 of file ParticleModuleRequired.h.
Referenced by CreateRendererResource().
GetNumBoundingVertices()
int32 UParticleModuleRequired::GetNumBoundingVertices () const inline private
Definition at line 472 of file ParticleModuleRequired.h.
Referenced by CreateRendererResource(), and GetFrameData().
GetNumFrames()
int32 UParticleModuleRequired::GetNumFrames () const inline private
Definition at line 457 of file ParticleModuleRequired.h.
Referenced by CreateRendererResource().
InitBoundingGeometryBuffer()
void UParticleModuleRequired::InitBoundingGeometryBuffer () private
InitializeDefaults()
void UParticleModuleRequired::InitializeDefaults () private
Initializes the default values for this property.
References InitializeDefaults().
Referenced by InitializeDefaults().
IsBoundingGeometryValid()
bool UParticleModuleRequired::IsBoundingGeometryValid () const inline private
Definition at line 462 of file ParticleModuleRequired.h.
Referenced by CreateRendererResource().
IsReadyForFinishDestroy()
virtual bool UParticleModuleRequired::IsReadyForFinishDestroy () override private virtual
IsValidForLODLevel()
virtual bool UParticleModuleRequired::IsValidForLODLevel (UParticleLODLevel * LODLevel, FString & OutErrorString) override private virtual
PostEditChangeProperty()
virtual void UParticleModuleRequired::PostEditChangeProperty (FPropertyChangedEvent & PropertyChangedEvent) override private virtual
PostInitProperties()
virtual void UParticleModuleRequired::PostInitProperties () override private virtual
References PostInitProperties().
Referenced by PostInitProperties().
PostLoad()
virtual void UParticleModuleRequired::PostLoad () override private virtual
References PostLoad().
Referenced by PostLoad().
PreEditChange()
virtual void UParticleModuleRequired::PreEditChange (FProperty * PropertyAboutToChange) override private virtual
Serialize()
virtual void UParticleModuleRequired::Serialize (FStructuredArchive::FRecord Record) override private virtual
References Record, and Serialize().
Referenced by Serialize().
SetToSensibleDefaults()
virtual void UParticleModuleRequired::SetToSensibleDefaults (UParticleEmitter * Owner) override private virtual
References Owner.
ShouldUseVelocityForMotionBlur()
bool UParticleModuleRequired::ShouldUseVelocityForMotionBlur () const private
Referenced by CreateRendererResource().
UPROPERTY() [1/31]
UParticleModuleRequired::UPROPERTY () private
Controls UV Flipping for this emitter.
References Category, and UPROPERTY().
UPROPERTY() [2/31]
UParticleModuleRequired::UPROPERTY () private
Indicates the time (in seconds) that this emitter should be delayed in the particle system.
References Category, and UPROPERTY().
UPROPERTY() [3/31]
UParticleModuleRequired::UPROPERTY () private
The low end of the emitter delay if using a range.
References Category, and UPROPERTY().
UPROPERTY() [4/31]
UParticleModuleRequired::UPROPERTY () private
World space radius that UVs generated with the ParticleMacroUV material node will tile based on.
References Category, and UPROPERTY().
UPROPERTY() [5/31]
UParticleModuleRequired::UPROPERTY () private
The amount of time (particle-relative, 0.0 to 1.0) to 'lock' on a random sub image 0.0 = change every frame 1.0 = select a random image at spawn and hold for the life of the particle.
References UPROPERTY().
UPROPERTY() [6/31]
UParticleModuleRequired::UPROPERTY () private
References Category, and UPROPERTY().
UPROPERTY() [7/31]
UParticleModuleRequired::UPROPERTY () private
References Category, FVector, and UPROPERTY().
UPROPERTY() [8/31]
UParticleModuleRequired::UPROPERTY () private
Local space position that UVs generated with the ParticleMacroUV material node will be centered on.
References Category, FVector, and UPROPERTY().
UPROPERTY() [9/31]
UParticleModuleRequired::UPROPERTY () private
When EmitterNormalsMode is ENM_Cylindrical, particle normals are created to face away from the cylinder going through NormalsSphereCenter in the direction NormalsCylinderDirection.
NormalsCylinderDirection is in local space.
References Category, FVector, Normals, and UPROPERTY().
UPROPERTY() [10/31]
UPROPERTY() uint8 bDurationRecalcEachLoop UParticleModuleRequired::UPROPERTY () private
If true, recalculate the emitter duration on each loop.
When EmitterNormalsMode is ENM_Spherical, particle normals are created to face away from NormalsSphereCenter. NormalsSphereCenter is in local space.
References Category, FVector, Normals, and UPROPERTY().
UPROPERTY() [11/31]
UParticleModuleRequired::UPROPERTY () private
The number of times to loop the emitter.
0 indicates loop continuously
References Category, Duration, and UPROPERTY().
UPROPERTY() [12/31]
UParticleModuleRequired::UPROPERTY () private
The maximum number of particles to DRAW for this emitter.
If set to 0, it will use whatever number are present.
References Category, and UPROPERTY().
UPROPERTY() [13/31]
UParticleModuleRequired::UPROPERTY () private
The number of times to change a random image over the life of the particle.
References Category, and UPROPERTY().
UPROPERTY() [14/31]
UPROPERTY() uint8 bOrbitModuleAffectsVelocityAlignment UParticleModuleRequired::UPROPERTY () private
Ensures that movement generated from the orbit module is applied to velocity-aligned particles.
The number of sub-images horizontally in the texture
References Category, and UPROPERTY().
UPROPERTY() [15/31]
UParticleModuleRequired::UPROPERTY () private
The number of sub-images vertically in the texture.
References Category, and UPROPERTY().
UPROPERTY() [16/31]
UParticleModuleRequired::UPROPERTY () private
The rate at which to spawn particles.
References UPROPERTY().
UPROPERTY() [17/31]
UParticleModuleRequired::UPROPERTY () private
Named material overrides for this emitter.
Overrides this emitter's material(s) with those in the correspondingly named slot(s) of the owning system.
References Category, and UPROPERTY().
UPROPERTY() [18/31]
UParticleModuleRequired::UPROPERTY () private
The array of burst entries.
References UPROPERTY().
UPROPERTY() [19/31]
UParticleModuleRequired::UPROPERTY () private
Normal generation mode for this emitter LOD.
References Category, Normals, and UPROPERTY().
UPROPERTY() [20/31]
UPROPERTY() uint8 bOverrideSystemMacroUV UPROPERTY() uint8 bUseMaxDrawCount UParticleModuleRequired::UPROPERTY () private
Override the system MacroUV settings.
If true, use the MaxDrawCount to limit the number of particles rendered. NOTE: This does not limit the number spawned/updated, only what is drawn.
References Category, and UPROPERTY().
UPROPERTY() [21/31]
UParticleModuleRequired::UPROPERTY () private
More bounding vertices results in reduced overdraw, but adds more triangle overhead.
The eight vertex mode is best used when the SubUV texture has a lot of space to cut out that is not captured by the four vertex version, and when the particles using the texture will be few and large.
References Category, Duration, and UPROPERTY().
UPROPERTY() [22/31]
UPROPERTY() uint8 bScaleUV UPROPERTY() uint8 bEmitterDelayUseRange UParticleModuleRequired::UPROPERTY () private
Whether to scale the UV or not - ie, the model wasn't setup with sub uvs.
If true, select the emitter delay from the range [EmitterDelayLow..EmitterDelay] The method to utilize when burst-emitting particles
References Category, and UPROPERTY().
UPROPERTY() [23/31]
UParticleModuleRequired::UPROPERTY () private
The screen alignment to utilize for the emitter at this LOD level.
One of the following: PSA_FacingCameraPosition - Faces the camera position, but is not dependent on the camera rotation.
This method produces more stable particles under camera rotation. PSA_Square - Uniform scale (via SizeX) facing the camera PSA_Rectangle - Non-uniform scale (via SizeX and SizeY) facing the camera PSA_Velocity - Orient the particle towards both the camera and the direction the particle is moving. Non-uniform scaling is allowed. PSA_TypeSpecific - Use the alignment method indicated in the type data module. PSA_FacingCameraDistanceBlend - Blends between PSA_FacingCameraPosition and PSA_Square over specified distance.
References Category, meta, and UPROPERTY().
UPROPERTY() [24/31]
UPROPERTY()) uint8 bUseLocalSpace UPROPERTY() uint8 bKillOnDeactivate UPROPERTY() uint8 bKillOnCompleted UParticleModuleRequired::UPROPERTY () private
If true, update the emitter in local space.
If true, kill the emitter when the particle system is deactivated If true, kill the emitter when it completes The sorting mode to use for this emitter. PSORTMODE_None - No sorting required. PSORTMODE_ViewProjDepth - Sort by view projected depth of the particle. PSORTMODE_DistanceToView - Sort by distance of particle to view in world space. PSORTMODE_Age_OldestFirst - Sort by age, oldest drawn first. PSORTMODE_Age_NewestFirst - Sort by age, newest drawn first.
References Category, Duration, meta, and UPROPERTY().
UPROPERTY() [25/31]
UPROPERTY() uint8 bDelayFirstLoopOnly UParticleModuleRequired::UPROPERTY () private
If true, the emitter will be delayed only on the first loop.
The interpolation method to used for the SubUV image selection. One of the following: PSUVIM_None - Do not apply SubUV modules to this emitter. PSUVIM_Linear - Smoothly transition between sub-images in the given order, with no blending between the current and the next PSUVIM_Linear_Blend - Smoothly transition between sub-images in the given order, blending between the current and the next PSUVIM_Random - Pick the next image at random, with no blending between the current and the next PSUVIM_Random_Blend - Pick the next image at random, blending between the current and the next
References Category, and UPROPERTY().
UPROPERTY() [26/31]
UParticleModuleRequired::UPROPERTY () private
Texture to generate bounding geometry from.
References Category, and UPROPERTY().
UPROPERTY() [27/31]
UParticleModuleRequired::UPROPERTY () private
Alpha channel values larger than the threshold are considered occupied and will be contained in the bounding geometry.
Raising this threshold slightly can reduce overdraw in particles using this animation asset.
References Category, meta, and UPROPERTY().
UPROPERTY() [28/31]
UPROPERTY() uint8 bUseLegacyEmitterTime UPROPERTY()) uint8 bRemoveHMDRoll UPROPERTY() uint8 bSupportLargeWorldCoordinates UPROPERTY() uint8 bEmitterDurationUseRange UPROPERTY() uint8 bOverrideUseVelocityForMotionBlur UPROPERTY()) uint8 bUseVelocityForMotionBlur UParticleModuleRequired::UPROPERTY () private
If true, the EmitterTime for the emitter will be calculated by modulating the SecondsSinceCreation by the EmitterDuration.
As this can lead to issues w/ looping and variable duration, a new approach has been implemented. If false, this new approach is utilized, and the EmitterTime is simply incremented by DeltaTime each tick. When the emitter loops, it adjusts the EmitterTime by the current EmitterDuration resulting in proper looping/delay behavior. If true, removes the HMD view roll (e.g. in VR) If true, gpu simulation positions are offset to support double precision vectors. Cpu sims always support large world coordinates. If true, select the emitter duration from the range [EmitterDurationLow..EmitterDuration] When supported by the vertex factory will use particle velocity for motion blur approximation. This will be inaccurate in some cases, i.e. sprite rotation, but may provide a reasonable result vs having this disabled How long, in seconds, the emitter will run before looping.
References Category, Duration, meta, and UPROPERTY().
UPROPERTY() [29/31]
UParticleModuleRequired::UPROPERTY () private
The low end of the emitter duration if using a range.
References Category, Duration, meta, and UPROPERTY().
UPROPERTY() [30/31]
UParticleModuleRequired::UPROPERTY () private
The distance at which PSA_FacingCameraDistanceBlend is fully PSA_FacingCameraPosition.
References Category, meta, and UPROPERTY().
UPROPERTY() [31/31]
UParticleModuleRequired::UPROPERTY () private
The distance at which PSA_FacingCameraDistanceBlend is fully PSA_Square.
References Category, meta, and UPROPERTY().
Referenced by GENERATED_UCLASS_BODY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), and UPROPERTY().
Friends And Related Symbol Documentation
FParticleEmitterInstance
friend struct FParticleEmitterInstance friend
Definition at line 504 of file ParticleModuleRequired.h.
References FParticleEmitterInstance.
Referenced by FParticleEmitterInstance.
FParticleModuleRequiredDetails
friend class FParticleModuleRequiredDetails friend
Definition at line 503 of file ParticleModuleRequired.h.
References FParticleModuleRequiredDetails.
Referenced by FParticleModuleRequiredDetails.
Field Documentation
BoundingGeometryBuffer
FSubUVBoundingGeometryBuffer* UParticleModuleRequired::BoundingGeometryBuffer private
Used on platforms that support instancing, the bounding geometry is fetched from a vertex shader instead of on the CPU.
Definition at line 514 of file ParticleModuleRequired.h.
Referenced by GetBoundingGeometrySRV().
DerivedData
FSubUVDerivedData UParticleModuleRequired::DerivedData private
Derived data for this asset, generated off of SubUVTexture.
Definition at line 508 of file ParticleModuleRequired.h.
Referenced by CreateRendererResource(), and GetFrameData().
ReleaseFence
FRenderCommandFence UParticleModuleRequired::ReleaseFence private
Tracks progress of BoundingGeometryBuffer release during destruction.
Definition at line 511 of file ParticleModuleRequired.h.
The documentation for this class was generated from the following file:
Runtime/Engine/Classes/Particles/ParticleModuleRequired.h