Unreal Engine 5.6 C++ API: UAIBlueprintHelperLibrary Class Reference
UAIBlueprintHelperLibrary Class Reference
#include "AIBlueprintHelperLibrary.h"
Private Member Functions
GENERATED_UCLASS_BODY () UFUNCTION()) static AIMODULE_API UAIAsyncTaskBlueprintProxy *CreateMoveToProxyObject(UObject *WorldContextObject
UFUNCTION () static AIMODULE_API bool IsValidAIDirection(FVector DirectionVector)
UFUNCTION () static AIMODULE_API bool IsValidAILocation(FVector Location)
UFUNCTION () static AIMODULE_API bool IsValidAIRotation(FRotator Rotation)
UFUNCTION () static AIMODULE_API void SimpleMoveToActor(AController *Controller
UFUNCTION () static AIMODULE_API void SimpleMoveToLocation(AController *Controller
UFUNCTION ()) static AIMODULE_API AAIController *GetAIController(AActor *ControlledActor)
The way it works exactly is if the actor passed in is a pawn, then the function retrieves pawn's controller cast to AIController.
UFUNCTION ()) static AIMODULE_API APawn *SpawnAIFromClass(UObject *WorldContextObject
Spawns AI agent of a given class.
UFUNCTION ()) static AIMODULE_API const TArray< FVector > GetCurrentPathPoints(AController *Controller)
Returns an array of navigation path points given controller is currently using.
UFUNCTION ()) static AIMODULE_API int32 GetCurrentPathIndex(const AController *Controller)
Return the path index the given controller is currently at.
UFUNCTION ()) static AIMODULE_API int32 GetNextNavLinkIndex(const AController *Controller)
Return the path index of the next nav link for the current path of the given controller.
UFUNCTION ()) static AIMODULE_API UBlackboardComponent *GetBlackboard(AActor *Target)
UFUNCTION ()) static AIMODULE_API UNavigationPath *GetCurrentPath(AController *Controller)
Returns a NEW UOBJECT that is a COPY of navigation path given controller is currently using.
UFUNCTION ()) static AIMODULE_API void LockAIResourcesWithAnimation(UAnimInstance *AnimInstance
locks indicated AI resources of animated pawn
UFUNCTION ()) static AIMODULE_API void SendAIMessage(APawn *Target
UFUNCTION ()) static AIMODULE_API void UnlockAIResourcesWithAnimation(UAnimInstance *AnimInstance
unlocks indicated AI resources of animated pawn.
Static Private Member Functions
static UPathFollowingComponent * GetPathComp (const AController *Controller)
Private Attributes
APawn FVector AActor float AcceptanceRadius = 5.f
TSubclassOf< APawn > UBehaviorTree * BehaviorTree
bool bLockMovement
TSubclassOf< APawn > UBehaviorTree FVector FRotator bool bNoCollisionFail = false
APawn FVector AActor float bool bStopOnOverlap = false)
FName UObject bool bSuccess = true)
bool bUnlockMovement
APawn FVector Destination
const AActor * Goal
const FVector & Goal
TSubclassOf< APawn > UBehaviorTree FVector Location
bool bool LockAILogic
FName Message
FName UObject * MessageSource
TSubclassOf< APawn > UBehaviorTree FVector FRotator bool AActor * Owner = nullptr)
APawn * Pawn
TSubclassOf< APawn > PawnClass
TSubclassOf< APawn > UBehaviorTree FVector FRotator Rotation = FRotator::ZeroRotator
APawn FVector AActor * TargetActor = NULL
bool bool UnlockAILogic
Detailed Description
Definition at line 26 of file AIBlueprintHelperLibrary.h.
Member Function Documentation
GENERATED_UCLASS_BODY()
UAIBlueprintHelperLibrary::GENERATED_UCLASS_BODY () private
References meta, and UFUNCTION().
GetPathComp()
UPathFollowingComponent * UAIBlueprintHelperLibrary::GetPathComp (const AController * Controller) static private
References GetPathComp().
Referenced by GetPathComp().
UFUNCTION() [1/15]
UAIBlueprintHelperLibrary::UFUNCTION () private
References Category, FVector, and UFUNCTION().
UFUNCTION() [2/15]
UAIBlueprintHelperLibrary::UFUNCTION () private
References Category, FVector, Location, and UFUNCTION().
UFUNCTION() [3/15]
UAIBlueprintHelperLibrary::UFUNCTION () private
References Category, Rotation, and UFUNCTION().
UFUNCTION() [4/15]
UAIBlueprintHelperLibrary::UFUNCTION () private
References Category, and UFUNCTION().
UFUNCTION() [5/15]
UAIBlueprintHelperLibrary::UFUNCTION () private
References Category, and UFUNCTION().
UFUNCTION() [6/15]
UAIBlueprintHelperLibrary::UFUNCTION () private
The way it works exactly is if the actor passed in is a pawn, then the function retrieves pawn's controller cast to AIController.
Otherwise the function returns actor cast to AIController.
References Category, meta, and UFUNCTION().
UFUNCTION() [7/15]
UAIBlueprintHelperLibrary::UFUNCTION () private
Spawns AI agent of a given class.
The PawnClass needs to have AIController set for the function to spawn a controller as well.
Parameters
BehaviorTree if set, and the function has successfully spawned and AI controller, this BehaviorTree asset will be assigned to the AI controller, and run.
Owner lets you spawn the AI in a sublevel rather than in the persistent level (which is the default behavior).
References Category, meta, and UFUNCTION().
UFUNCTION() [8/15]
UAIBlueprintHelperLibrary::UFUNCTION () const private
Returns an array of navigation path points given controller is currently using.
References Category, FVector, meta, and UFUNCTION().
UFUNCTION() [9/15]
UAIBlueprintHelperLibrary::UFUNCTION () const private
Return the path index the given controller is currently at.
Returns INDEX_NONE if no path.
References Category, meta, and UFUNCTION().
UFUNCTION() [10/15]
UAIBlueprintHelperLibrary::UFUNCTION () const private
Return the path index of the next nav link for the current path of the given controller.
Returns INDEX_NONE if no path or no incoming nav link.
References Category, meta, and UFUNCTION().
UFUNCTION() [11/15]
UAIBlueprintHelperLibrary::UFUNCTION () private
References Category, meta, Target, and UFUNCTION().
UFUNCTION() [12/15]
UAIBlueprintHelperLibrary::UFUNCTION () private
Returns a NEW UOBJECT that is a COPY of navigation path given controller is currently using.
The result being a copy means you won't be able to influence agent's pathfollowing by manipulating received path. Please use GetCurrentPathPoints if you only need the array of path points.
References Category, meta, and UFUNCTION().
UFUNCTION() [13/15]
UAIBlueprintHelperLibrary::UFUNCTION () private
locks indicated AI resources of animated pawn
References Category, meta, and UFUNCTION().
UFUNCTION() [14/15]
UAIBlueprintHelperLibrary::UFUNCTION () private
References Category, meta, and UFUNCTION().
Referenced by GENERATED_UCLASS_BODY(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
UFUNCTION() [15/15]
UAIBlueprintHelperLibrary::UFUNCTION () private
unlocks indicated AI resources of animated pawn.
Will unlock only animation-locked resources
References Category, meta, and UFUNCTION().
Field Documentation
AcceptanceRadius
APawn FVector AActor float UAIBlueprintHelperLibrary::AcceptanceRadius = 5.f private
Definition at line 31 of file AIBlueprintHelperLibrary.h.
BehaviorTree
TSubclassOf<APawn> UBehaviorTree* UAIBlueprintHelperLibrary::BehaviorTree private
Definition at line 45 of file AIBlueprintHelperLibrary.h.
bLockMovement
bool UAIBlueprintHelperLibrary::bLockMovement private
Definition at line 57 of file AIBlueprintHelperLibrary.h.
bNoCollisionFail
TSubclassOf<APawn> UBehaviorTree FVector FRotator bool UAIBlueprintHelperLibrary::bNoCollisionFail = false private
Definition at line 45 of file AIBlueprintHelperLibrary.h.
bStopOnOverlap
APawn FVector AActor float bool UAIBlueprintHelperLibrary::bStopOnOverlap = false) private
Definition at line 31 of file AIBlueprintHelperLibrary.h.
bSuccess
FName UObject bool UAIBlueprintHelperLibrary::bSuccess = true) private
Definition at line 34 of file AIBlueprintHelperLibrary.h.
bUnlockMovement
bool UAIBlueprintHelperLibrary::bUnlockMovement private
Definition at line 61 of file AIBlueprintHelperLibrary.h.
Destination
APawn FVector UAIBlueprintHelperLibrary::Destination private
Definition at line 31 of file AIBlueprintHelperLibrary.h.
Goal [1/2]
const AActor* UAIBlueprintHelperLibrary::Goal private
Definition at line 92 of file AIBlueprintHelperLibrary.h.
Goal [2/2]
const FVector& UAIBlueprintHelperLibrary::Goal private
Definition at line 95 of file AIBlueprintHelperLibrary.h.
Location
TSubclassOf<APawn> UBehaviorTree FVector UAIBlueprintHelperLibrary::Location private
Definition at line 45 of file AIBlueprintHelperLibrary.h.
Referenced by UFUNCTION().
LockAILogic
bool bool UAIBlueprintHelperLibrary::LockAILogic private
Definition at line 57 of file AIBlueprintHelperLibrary.h.
Message
FName UAIBlueprintHelperLibrary::Message private
Definition at line 34 of file AIBlueprintHelperLibrary.h.
MessageSource
FName UObject* UAIBlueprintHelperLibrary::MessageSource private
Definition at line 34 of file AIBlueprintHelperLibrary.h.
Owner
TSubclassOf<APawn> UBehaviorTree FVector FRotator bool AActor* UAIBlueprintHelperLibrary::Owner = nullptr) private
Definition at line 45 of file AIBlueprintHelperLibrary.h.
Pawn
APawn* UAIBlueprintHelperLibrary::Pawn private
Definition at line 31 of file AIBlueprintHelperLibrary.h.
PawnClass
TSubclassOf<APawn> UAIBlueprintHelperLibrary::PawnClass private
Definition at line 45 of file AIBlueprintHelperLibrary.h.
Rotation
TSubclassOf<APawn> UBehaviorTree FVector FRotator UAIBlueprintHelperLibrary::Rotation = FRotator::ZeroRotator private
Definition at line 45 of file AIBlueprintHelperLibrary.h.
Referenced by UFUNCTION().
TargetActor
APawn FVector AActor* UAIBlueprintHelperLibrary::TargetActor = NULL private
Definition at line 31 of file AIBlueprintHelperLibrary.h.
UnlockAILogic
bool bool UAIBlueprintHelperLibrary::UnlockAILogic private
Definition at line 61 of file AIBlueprintHelperLibrary.h.
The documentation for this class was generated from the following file:
Runtime/AIModule/Classes/Blueprint/AIBlueprintHelperLibrary.h