Unreal Engine 5.6 C++ API: FObjectCollectSaveOverridesContext Class Reference
FObjectCollectSaveOverridesContext Class Reference
Interface used by CollectSaveOverrides to access the save parameters.
#include "ObjectSaveContext.h"
Public Member Functions
FObjectCollectSaveOverridesContext (const FObjectCollectSaveOverridesContext &Other)
FObjectCollectSaveOverridesContext (FObjectSaveContextData &InData)
void AddSaveOverride (UObject *Target, FObjectSaveOverride InOverride)
Add a save override to specific object.
UE::Cook::ECookingDLC GetCookingDLC () const
UE::Cook::ECookType GetCookType () const
uint32 GetSaveFlags () const
Return the save flags (ESaveFlags) of the save.
const ITargetPlatform * GetTargetPlatform () const
Return the targetplatform of the save, if cooking.
bool IsCookByTheBook () const
bool IsCooking () const
Report whether this is a save into a target-specific cooked format.
bool IsCookOnTheFly () const
bool IsCookTypeUnknown () const
bool IsProceduralSave () const
Return whether the package is being saved due to a procedural save.
Protected Attributes
FObjectSaveContextData & Data
Friends
class UObject
Detailed Description
Interface used by CollectSaveOverrides to access the save parameters.
Definition at line 192 of file ObjectSaveContext.h.
Constructor & Destructor Documentation
FObjectCollectSaveOverridesContext() [1/2]
FObjectCollectSaveOverridesContext::FObjectCollectSaveOverridesContext (FObjectSaveContextData & InData) inline explicit
Definition at line 195 of file ObjectSaveContext.h.
References Data.
Referenced by FObjectCollectSaveOverridesContext().
FObjectCollectSaveOverridesContext() [2/2]
FObjectCollectSaveOverridesContext::FObjectCollectSaveOverridesContext (const FObjectCollectSaveOverridesContext & Other) inline
Definition at line 201 of file ObjectSaveContext.h.
References FObjectCollectSaveOverridesContext(), Data, and Other.
Member Function Documentation
AddSaveOverride()
void FObjectCollectSaveOverridesContext::AddSaveOverride (UObject * Target, FObjectSaveOverride InOverride) inline
Add a save override to specific object.
(i.e. mark certain objects or properties transient for this save)
Definition at line 232 of file ObjectSaveContext.h.
References Data, MoveTemp(), Target, and UObject.
GetCookingDLC()
UE::Cook::ECookingDLC FObjectCollectSaveOverridesContext::GetCookingDLC () const inline
Definition at line 217 of file ObjectSaveContext.h.
References Data.
GetCookType()
UE::Cook::ECookType FObjectCollectSaveOverridesContext::GetCookType () const inline
Definition at line 216 of file ObjectSaveContext.h.
References Data.
Referenced by IsCookByTheBook(), IsCookOnTheFly(), and IsCookTypeUnknown().
GetSaveFlags()
uint32 FObjectCollectSaveOverridesContext::GetSaveFlags () const inline
Return the save flags (ESaveFlags) of the save.
Definition at line 227 of file ObjectSaveContext.h.
References Data.
GetTargetPlatform()
const ITargetPlatform * FObjectCollectSaveOverridesContext::GetTargetPlatform () const inline
Return the targetplatform of the save, if cooking.
Null if not cooking.
Definition at line 211 of file ObjectSaveContext.h.
References Data.
IsCookByTheBook()
bool FObjectCollectSaveOverridesContext::IsCookByTheBook () const inline
Definition at line 213 of file ObjectSaveContext.h.
References UE::Cook::ByTheBook, and GetCookType().
IsCooking()
bool FObjectCollectSaveOverridesContext::IsCooking () const inline
Report whether this is a save into a target-specific cooked format.
Definition at line 208 of file ObjectSaveContext.h.
References Data.
IsCookOnTheFly()
bool FObjectCollectSaveOverridesContext::IsCookOnTheFly () const inline
Definition at line 214 of file ObjectSaveContext.h.
References GetCookType(), and UE::Cook::OnTheFly.
IsCookTypeUnknown()
bool FObjectCollectSaveOverridesContext::IsCookTypeUnknown () const inline
Definition at line 215 of file ObjectSaveContext.h.
References GetCookType(), and UE::Cook::Unknown.
IsProceduralSave()
bool FObjectCollectSaveOverridesContext::IsProceduralSave () const inline
Return whether the package is being saved due to a procedural save.
Any save without the possibility of user-generated edits to the package is a procedural save (Cooking, EditorDomain). This allows us to execute transforms that only need to be executed in response to new user data.
Definition at line 224 of file ObjectSaveContext.h.
References Data.
Friends And Related Symbol Documentation
UObject
friend class UObject friend
Definition at line 239 of file ObjectSaveContext.h.
References UObject.
Referenced by AddSaveOverride(), and UObject.
Field Documentation
Data
FObjectSaveContextData& FObjectCollectSaveOverridesContext::Data protected
Definition at line 238 of file ObjectSaveContext.h.
Referenced by FObjectCollectSaveOverridesContext(), FObjectCollectSaveOverridesContext(), AddSaveOverride(), GetCookingDLC(), GetCookType(), GetSaveFlags(), GetTargetPlatform(), IsCooking(), and IsProceduralSave().
The documentation for this class was generated from the following file:
Runtime/CoreUObject/Public/UObject/ObjectSaveContext.h