Unreal Engine 5.6 C++ API: SCommonButtonTableRow< ItemType > Class Template Reference
SCommonButtonTableRow< ItemType > Class Template Reference
A CommonUI version of the object table row that is aware of UCommonButtonBase.
#include "SCommonButtonTableRow.h"
Public Member Functions
virtual FReply OnMouseButtonDoubleClick (const FGeometry &InMyGeometry, const FPointerEvent &InMouseEvent) override
virtual FReply OnMouseButtonDown (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent) override
virtual FReply OnMouseButtonUp (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent) override
virtual void OnMouseEnter (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent) override
virtual void OnMouseLeave (const FPointerEvent &MouseEvent) override
SLATE_ARGUMENT (bool, bAllowDragging) SLATE_EVENT(FOnRowHovered
SLATE_BEGIN_ARGS (SCommonButtonTableRow< ItemType >)
OnHovered Content SLATE_END_ARGS () public
OnHovered SLATE_EVENT (FOnRowHovered, OnUnhovered) SLATE_DEFAULT_SLOT(FArguments
Protected Member Functions
virtual void DetectItemSelectionChanged () override
virtual void InitializeObjectRow () override
virtual void OnItemSelectionChanged (bool bIsItemSelected) override
virtual void ResetObjectRow () override
Private Member Functions
void HandleButtonClicked ()
void HandleButtonDoubleClicked ()
void HandleButtonHovered ()
void HandleButtonSelectionChanged (bool bIsButtonSelected)
void HandleButtonUnhovered ()
Detailed Description
template<typename ItemType>
class SCommonButtonTableRow< ItemType >
A CommonUI version of the object table row that is aware of UCommonButtonBase.
Instead of bothering with handling mouse events directly, we rely on the entry being a button itself and respond to events from it.
Definition at line 15 of file SCommonButtonTableRow.h.
Member Function Documentation
DetectItemSelectionChanged()
template<typename ItemType> virtual void SCommonButtonTableRow< ItemType >::DetectItemSelectionChanged () inline override protected virtual
Definition at line 109 of file SCommonButtonTableRow.h.
References Cast(), and OnItemSelectionChanged().
HandleButtonClicked()
template<typename ItemType> void SCommonButtonTableRow< ItemType >::HandleButtonClicked () inline private
Definition at line 141 of file SCommonButtonTableRow.h.
Referenced by InitializeObjectRow().
HandleButtonDoubleClicked()
template<typename ItemType> void SCommonButtonTableRow< ItemType >::HandleButtonDoubleClicked () inline private
Definition at line 151 of file SCommonButtonTableRow.h.
Referenced by InitializeObjectRow().
HandleButtonHovered()
template<typename ItemType> void SCommonButtonTableRow< ItemType >::HandleButtonHovered () inline private
Definition at line 164 of file SCommonButtonTableRow.h.
Referenced by InitializeObjectRow().
HandleButtonSelectionChanged()
template<typename ItemType> void SCommonButtonTableRow< ItemType >::HandleButtonSelectionChanged (bool bIsButtonSelected) inline private
Definition at line 174 of file SCommonButtonTableRow.h.
References ensure.
Referenced by InitializeObjectRow().
HandleButtonUnhovered()
template<typename ItemType> void SCommonButtonTableRow< ItemType >::HandleButtonUnhovered () inline private
Definition at line 169 of file SCommonButtonTableRow.h.
Referenced by InitializeObjectRow().
InitializeObjectRow()
template<typename ItemType> virtual void SCommonButtonTableRow< ItemType >::InitializeObjectRow () inline override protected virtual
Definition at line 61 of file SCommonButtonTableRow.h.
References Cast(), HandleButtonClicked(), HandleButtonDoubleClicked(), HandleButtonHovered(), HandleButtonSelectionChanged(), and HandleButtonUnhovered().
OnItemSelectionChanged()
template<typename ItemType> virtual void SCommonButtonTableRow< ItemType >::OnItemSelectionChanged (bool bIsItemSelected) inline override protected virtual
Definition at line 127 of file SCommonButtonTableRow.h.
References Cast().
Referenced by DetectItemSelectionChanged().
OnMouseButtonDoubleClick()
template<typename ItemType> virtual FReply SCommonButtonTableRow< ItemType >::OnMouseButtonDoubleClick (const FGeometry & InMyGeometry, const FPointerEvent & InMouseEvent) inline override virtual
Definition at line 58 of file SCommonButtonTableRow.h.
References FReply::Handled().
OnMouseButtonDown()
template<typename ItemType> virtual FReply SCommonButtonTableRow< ItemType >::OnMouseButtonDown (const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) inline override virtual
Definition at line 56 of file SCommonButtonTableRow.h.
References MouseEvent.
OnMouseButtonUp()
template<typename ItemType> virtual FReply SCommonButtonTableRow< ItemType >::OnMouseButtonUp (const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) inline override virtual
Definition at line 57 of file SCommonButtonTableRow.h.
References MouseEvent.
OnMouseEnter()
template<typename ItemType> virtual void SCommonButtonTableRow< ItemType >::OnMouseEnter (const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) inline override virtual
Definition at line 54 of file SCommonButtonTableRow.h.
References MouseEvent.
OnMouseLeave()
template<typename ItemType> virtual void SCommonButtonTableRow< ItemType >::OnMouseLeave (const FPointerEvent & MouseEvent) inline override virtual
Definition at line 55 of file SCommonButtonTableRow.h.
References MouseEvent.
ResetObjectRow()
template<typename ItemType> virtual void SCommonButtonTableRow< ItemType >::ResetObjectRow () inline override protected virtual
Definition at line 89 of file SCommonButtonTableRow.h.
References Cast().
SLATE_ARGUMENT()
template<typename ItemType> SCommonButtonTableRow< ItemType >::SLATE_ARGUMENT (bool , bAllowDragging)
SLATE_BEGIN_ARGS()
template<typename ItemType> SCommonButtonTableRow< ItemType >::SLATE_BEGIN_ARGS (SCommonButtonTableRow< ItemType >) inline
Definition at line 18 of file SCommonButtonTableRow.h.
SLATE_END_ARGS()
template<typename ItemType> OnHovered Content SCommonButtonTableRow< ItemType >::SLATE_END_ARGS () inline
Definition at line 25 of file SCommonButtonTableRow.h.
References Cast(), ensureMsgf, SLATE_END_ARGS(), and TEXT.
Referenced by SLATE_END_ARGS().
SLATE_EVENT()
template<typename ItemType> OnHovered SCommonButtonTableRow< ItemType >::SLATE_EVENT (FOnRowHovered , OnUnhovered)
References SLATE_DEFAULT_SLOT, and SLATE_EVENT().
Referenced by SLATE_EVENT().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/CommonUI/Source/CommonUI/Public/SCommonButtonTableRow.h