Unreal Engine 5.6 C++ API: FMappedName Class Reference
FMappedName Class Reference
Index and name number into a name map.
#include "MappedName.h"
Public Types
enum class EType { Package , Container , Global }
Public Member Functions
FMappedName ()=default
uint32 GetIndex () const
uint32 GetNumber () const
EType GetType () const
bool IsGlobal () const
bool IsValid () const
bool operator!= (FMappedName Other) const
FName ResolveName (TConstArrayView< FDisplayNameEntryId > Names) const
FMinimalName ToUnresolvedMinimalName () const
Static Public Member Functions
static FMappedName Create (const uint32 InIndex, const uint32 InNumber, EType InType)
static FMappedName FromMinimalName (const FMinimalName &MinimalName)
static bool IsResolvedToMinimalName (const FMinimalName &MinimalName)
static FName SafeMinimalNameToName (const FMinimalName &MinimalName)
Private Member Functions
FMappedName (const uint32 InIndex, const uint32 InNumber)
Private Attributes
uint32 Index = InvalidIndex
uint32 Number = InvalidIndex
Static Private Attributes
static constexpr uint32 IndexBits = 30u
static constexpr uint32 IndexMask = (1u << IndexBits) - 1u
static constexpr uint32 InvalidIndex = ~uint32(0)
static constexpr uint32 TypeMask = ~IndexMask
static constexpr uint32 TypeShift = IndexBits
Friends
FArchive & operator<< (FArchive &Ar, FMappedName &MappedName)
Detailed Description
Index and name number into a name map.
Definition at line 21 of file MappedName.h.
Member Enumeration Documentation
EType
enum class FMappedName::EType strong
Enumerator
Package
Container
Global
Definition at line 30 of file MappedName.h.
Constructor & Destructor Documentation
FMappedName() [1/2]
FMappedName::FMappedName () inline default
Referenced by Create(), FromMinimalName(), IsResolvedToMinimalName(), operator!=(), and operator<<.
FMappedName() [2/2]
FMappedName::FMappedName (const uint32 InIndex, const uint32 InNumber) inline private
Definition at line 105 of file MappedName.h.
References Index, and Number.
Member Function Documentation
Create()
FMappedName FMappedName::Create (const uint32 InIndex, const uint32 InNumber, EType InType) inline static
Definition at line 39 of file MappedName.h.
References FMappedName(), check, and TypeShift.
FromMinimalName()
FMappedName FMappedName::FromMinimalName (const FMinimalName & MinimalName) inline static
Definition at line 45 of file MappedName.h.
References FMappedName().
Referenced by IsResolvedToMinimalName().
GetIndex()
uint32 FMappedName::GetIndex () const inline
Definition at line 82 of file MappedName.h.
References Index, and IndexMask.
Referenced by FNameMap::GetName(), ResolveName(), and FNameMap::TryGetName().
GetNumber()
uint32 FMappedName::GetNumber () const inline
Definition at line 87 of file MappedName.h.
References Number.
Referenced by FNameMap::GetName(), ResolveName(), and FNameMap::TryGetName().
GetType()
EType FMappedName::GetType () const inline
Definition at line 72 of file MappedName.h.
References Index, TypeMask, and TypeShift.
Referenced by FNameMap::GetName(), and FNameMap::TryGetName().
IsGlobal()
bool FMappedName::IsGlobal () const inline
Definition at line 77 of file MappedName.h.
References Index, TypeMask, and TypeShift.
IsResolvedToMinimalName()
bool FMappedName::IsResolvedToMinimalName (const FMinimalName & MinimalName) inline static
Definition at line 50 of file MappedName.h.
References FMappedName(), FromMinimalName(), and IsValid().
Referenced by SafeMinimalNameToName().
IsValid()
bool FMappedName::IsValid () const inline
Definition at line 67 of file MappedName.h.
References Index, InvalidIndex, and Number.
Referenced by IsResolvedToMinimalName().
operator!=()
bool FMappedName::operator!= (FMappedName Other) const inline
Definition at line 92 of file MappedName.h.
References FMappedName(), Index, Number, and Other.
ResolveName()
FName FMappedName::ResolveName (TConstArrayView< FDisplayNameEntryId > Names) const inline
Definition at line 97 of file MappedName.h.
References GetIndex(), GetNumber(), and Names.
SafeMinimalNameToName()
FName FMappedName::SafeMinimalNameToName (const FMinimalName & MinimalName) inline static
Definition at line 57 of file MappedName.h.
References IsResolvedToMinimalName(), and MinimalNameToName().
ToUnresolvedMinimalName()
FMinimalName FMappedName::ToUnresolvedMinimalName () const inline
Definition at line 62 of file MappedName.h.
Friends And Related Symbol Documentation
operator<<
FArchive & operator<< (FArchive & Ar, FMappedName & MappedName) friend
References FMappedName(), and Ar.
Field Documentation
Index
uint32 FMappedName::Index = InvalidIndex private
Definition at line 109 of file MappedName.h.
Referenced by FMappedName(), GetIndex(), GetType(), IsGlobal(), IsValid(), and operator!=().
IndexBits
uint32 FMappedName::IndexBits = 30u static constexpr private
Definition at line 24 of file MappedName.h.
IndexMask
uint32 FMappedName::IndexMask = (1u << IndexBits) - 1u static constexpr private
Definition at line 25 of file MappedName.h.
Referenced by GetIndex().
InvalidIndex
uint32 FMappedName::InvalidIndex = ~uint32(0) static constexpr private
Definition at line 23 of file MappedName.h.
Referenced by IsValid().
Number
uint32 FMappedName::Number = InvalidIndex private
Definition at line 110 of file MappedName.h.
Referenced by FMappedName(), GetNumber(), IsValid(), and operator!=().
TypeMask
uint32 FMappedName::TypeMask = ~IndexMask static constexpr private
Definition at line 26 of file MappedName.h.
Referenced by GetType(), and IsGlobal().
TypeShift
uint32 FMappedName::TypeShift = IndexBits static constexpr private
Definition at line 27 of file MappedName.h.
Referenced by Create(), GetType(), and IsGlobal().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Serialization/MappedName.h