Unreal Engine 5.6 C++ API: FAsyncTask< TTask > Class Template Reference
FAsyncTask< TTask > Class Template Reference
#include "AsyncWork.h"
Data Structures
struct CMarkAsCanceled
Public Member Functions
FAsyncTask ()
template<typename Arg0Type, typename... ArgTypes>
FAsyncTask (Arg0Type &&Arg0, ArgTypes &&... Args)
Forwarding constructor.
void DoTaskWork () final
Perform task's work.
TTask & GetTask ()
const TTask & GetTask () const
bool TryAbandonTask () final
Abandon task if possible, returns true on success, false otherwise.
Public Member Functions inherited from FAsyncTaskBase
virtual ~FAsyncTaskBase ()
Destructor, not legal when a task is in process.
bool Cancel ()
Cancel the task, if possible.
void EnsureCompletion (bool bDoWorkOnThisThreadIfNotStarted=true, bool bIsLatencySensitive=false)
Wait until the job is complete.
const TCHAR * GetDebugName () const final
Returns text to identify the Work, for debug/log purposes only.
EQueuedWorkPriority GetPriority () const
int64 GetRequiredMemory () const final
Returns an approximation of the peak memory (in bytes) this task could require during it's execution.
bool IsDone ()
Returns true if the work and TASK has completed, false while it's still in progress.
bool IsIdle () const
Returns true if the work has not been started or has been completed.
bool IsWorkDone () const
Returns true if the work has completed, false while it's still in progress.
bool Reschedule (FQueuedThreadPool *InQueuedPool=GThreadPool, EQueuedWorkPriority InQueuedWorkPriority=EQueuedWorkPriority::Normal)
If not already being processed, will be rescheduled on given thread pool and priority.
bool SetPriority (EQueuedWorkPriority QueuedWorkPriority)
void StartBackgroundTask (FQueuedThreadPool *InQueuedPool=GThreadPool, EQueuedWorkPriority InQueuedWorkPriority=EQueuedWorkPriority::Normal, EQueuedWorkFlags InQueuedWorkFlags=EQueuedWorkFlags::None, int64 InRequiredMemory=-1, const TCHAR *InDebugName=nullptr)
Queue this task for processing by the background thread pool.
void StartSynchronousTask (EQueuedWorkPriority InQueuedWorkPriority=EQueuedWorkPriority::Normal, EQueuedWorkFlags InQueuedWorkFlags=EQueuedWorkFlags::None, int64 InRequiredMemory=-1, const TCHAR *InDebugName=nullptr)
Run this task on this thread.
bool WaitCompletionWithTimeout (float TimeLimitSeconds)
Wait until the job is complete, up to a time limit.
Private Member Functions
void MarkAsCanceled () final
Optionally mark the task as canceled if supported.
Private Attributes
TTask Task
User job embedded in this task.
Additional Inherited Members
Protected Member Functions inherited from FAsyncTaskBase
void CheckIdle () const
Internal call to assert that we are idle.
void Init (TStatId InStatId)
Detailed Description
template<typename TTask>
class FAsyncTask< TTask >
Definition at line 583 of file AsyncWork.h.
Constructor & Destructor Documentation
FAsyncTask() [1/2]
template<typename TTask> FAsyncTask< TTask >::FAsyncTask () inline
Definition at line 608 of file AsyncWork.h.
Referenced by UE::Geometry::FAsyncTaskExecuterWithAbort< TTask >::FAsyncTaskExecuterWithAbort().
FAsyncTask() [2/2]
template<typename TTask> template<typename Arg0Type, typename... ArgTypes> FAsyncTask< TTask >::FAsyncTask (Arg0Type && Arg0, ArgTypes &&... Args) inline
Forwarding constructor.
Definition at line 617 of file AsyncWork.h.
Member Function Documentation
DoTaskWork()
template<typename TTask> void FAsyncTask< TTask >::DoTaskWork () inline final virtual
Perform task's work.
Implements FAsyncTaskBase.
Definition at line 653 of file AsyncWork.h.
GetTask() [1/2]
template<typename TTask> TTask & FAsyncTask< TTask >::GetTask () inline
Definition at line 627 of file AsyncWork.h.
Referenced by UE::Geometry::FAsyncTaskExecuterWithAbort< TTask >::FAsyncTaskExecuterWithAbort(), and UE::Geometry::FAsyncTaskExecuterWithProgressCancel< TTask >::FAsyncTaskExecuterWithProgressCancel().
GetTask() [2/2]
template<typename TTask> const TTask & FAsyncTask< TTask >::GetTask () const inline
Definition at line 636 of file AsyncWork.h.
MarkAsCanceled()
template<typename TTask> void FAsyncTask< TTask >::MarkAsCanceled () inline final private virtual
Optionally mark the task as canceled if supported.
Reimplemented from FAsyncTaskBase.
Definition at line 600 of file AsyncWork.h.
TryAbandonTask()
template<typename TTask> bool FAsyncTask< TTask >::TryAbandonTask () inline final virtual
Abandon task if possible, returns true on success, false otherwise.
Implements FAsyncTaskBase.
Definition at line 642 of file AsyncWork.h.
Field Documentation
Task
template<typename TTask> TTask FAsyncTask< TTask >::Task private
User job embedded in this task.
Definition at line 587 of file AsyncWork.h.
Referenced by FAsyncTask< TTask >::CMarkAsCanceled::Requires().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Async/AsyncWork.h