Unreal Engine 5.6 C++ API: UE::StateTree::FActiveStatePath Class Reference
UE::StateTree::FActiveStatePath Class Reference
Describe the state list used to get to a specific state.
#include "StateTreeStatePath.h"
Public Member Functions
FActiveStatePath ()=default
STATETREEMODULE_API FActiveStatePath (TNotNull< const UStateTree * > InStateTree, const TArrayView< const FActiveState > InElements)
STATETREEMODULE_API FActiveStatePath (TNotNull< const UStateTree * > InStateTree, TArray< FActiveState > InElements)
STATETREEMODULE_API bool Contains (FActiveState Other) const
STATETREEMODULE_API bool Contains (FActiveStateID Other) const
STATETREEMODULE_API TValueOrError< FString, void > Describe () const
const TArrayView< const FActiveState > GetView () const
STATETREEMODULE_API int32 IndexOf (FActiveState Other) const
STATETREEMODULE_API int32 IndexOf (FActiveStateID Other) const
STATETREEMODULE_API const TArrayView< const FActiveState > Intersect (const FActiveStatePath &Other) const
STATETREEMODULE_API bool Matches (const FActiveStatePath &Other) const
STATETREEMODULE_API bool Matches (FActiveState Other) const
STATETREEMODULE_API bool Matches (FActiveStateID Other) const
int32 Num () const
STATETREEMODULE_API bool StartsWith (const FActiveStatePath &Other) const
Static Public Member Functions
static STATETREEMODULE_API bool Contains (const TArrayView< const FActiveState > &Path, FActiveState Other)
static STATETREEMODULE_API bool Contains (const TArrayView< const FActiveState > &Path, FActiveStateID Other)
static STATETREEMODULE_API TValueOrError< FString, void > Describe (TNotNull< const UStateTree * > StateTree, const TArrayView< const FActiveState > &Path)
static STATETREEMODULE_API int32 IndexOf (const TArrayView< const FActiveState > &Path, FActiveState Other)
static STATETREEMODULE_API int32 IndexOf (const TArrayView< const FActiveState > &Path, FActiveStateID Other)
static STATETREEMODULE_API const TArrayView< const FActiveState > Intersect (const TArrayView< const FActiveState > &A, const TArrayView< const FActiveState > &B)
static STATETREEMODULE_API bool Matches (const TArrayView< const FActiveState > &A, const TArrayView< const FActiveState > &B)
static STATETREEMODULE_API bool Matches (const TArrayView< const FActiveState > &Path, FActiveState Other)
static STATETREEMODULE_API bool Matches (const TArrayView< const FActiveState > &Path, FActiveStateID Other)
static STATETREEMODULE_API bool StartsWith (const TArrayView< const FActiveState > &Path, const TArrayView< const FActiveState > &B)
Private Attributes
TArray< FActiveState > States
TWeakObjectPtr< const UStateTree > StateTree
Detailed Description
Describe the state list used to get to a specific state.
Since a state can be a subtree and can be linked to other states, the path to activate the subtree can be different. A state can enter, then exit, then reenter. It is considered the same state path but not the same unique state path. For a tree like RootA(0) StateA(1) StateB(2) LinkedStateA(3) StateC(4) LinkedStateA(5) SubTreeA(6) StateD(7) The path to get to StateD can be RootA.StateB.LinkedStateA.SubTreeA.StateD(0.2.3.6.7)
Definition at line 125 of file StateTreeStatePath.h.
Constructor & Destructor Documentation
FActiveStatePath() [1/3]
UE::StateTree::FActiveStatePath::FActiveStatePath () explicit default
Referenced by Intersect(), Matches(), and StartsWith().
FActiveStatePath() [2/3]
STATETREEMODULE_API UE::StateTree::FActiveStatePath::FActiveStatePath (TNotNull< const UStateTree * > InStateTree, const TArrayView< const FActiveState > InElements) explicit
References UE_API.
FActiveStatePath() [3/3]
STATETREEMODULE_API UE::StateTree::FActiveStatePath::FActiveStatePath (TNotNull< const UStateTree * > InStateTree, TArray< FActiveState > InElements) explicit
References UE_API.
Member Function Documentation
Contains() [1/4]
STATETREEMODULE_API bool UE::StateTree::FActiveStatePath::Contains (const TArrayView< const FActiveState > & Path, FActiveState Other) static nodiscard
Returns
true if the path contains anywhere the other element.
References Other, Path, and UE_API.
Contains() [2/4]
STATETREEMODULE_API bool UE::StateTree::FActiveStatePath::Contains (const TArrayView< const FActiveState > & Path, FActiveStateID Other) static nodiscard
Returns
true if the path contains anywhere the other element.
References Other, Path, and UE_API.
Contains() [3/4]
STATETREEMODULE_API bool UE::StateTree::FActiveStatePath::Contains (FActiveState Other) const nodiscard
Returns
true if this path contains anywhere the other element.
References Other, and UE_API.
Contains() [4/4]
STATETREEMODULE_API bool UE::StateTree::FActiveStatePath::Contains (FActiveStateID Other) const nodiscard
Returns
true if this path contains anywhere the other element.
References Other, and UE_API.
Describe() [1/2]
STATETREEMODULE_API TValueOrError< FString, void > UE::StateTree::FActiveStatePath::Describe () const nodiscard
Returns
debugging information about the path.
References UE_API.
Describe() [2/2]
STATETREEMODULE_API TValueOrError< FString, void > UE::StateTree::FActiveStatePath::Describe (TNotNull< const UStateTree * > StateTree, const TArrayView< const FActiveState > & Path) static nodiscard
Returns
debugging information about the path.
References Path, StateTree, and UE_API.
GetView()
const TArrayView< const FActiveState > UE::StateTree::FActiveStatePath::GetView () const inline nodiscard
Returns
a view of the states in the path.
Definition at line 139 of file StateTreeStatePath.h.
References States.
IndexOf() [1/4]
STATETREEMODULE_API int32 UE::StateTree::FActiveStatePath::IndexOf (const TArrayView< const FActiveState > & Path, FActiveState Other) static nodiscard
Returns
true the index of element inside the path.
References Other, Path, and UE_API.
IndexOf() [2/4]
STATETREEMODULE_API int32 UE::StateTree::FActiveStatePath::IndexOf (const TArrayView< const FActiveState > & Path, FActiveStateID Other) static nodiscard
Returns
true the index of element inside the path.
References Other, Path, and UE_API.
IndexOf() [3/4]
STATETREEMODULE_API int32 UE::StateTree::FActiveStatePath::IndexOf (FActiveState Other) const nodiscard
Returns
true the index of element inside the path.
References Other, and UE_API.
IndexOf() [4/4]
STATETREEMODULE_API int32 UE::StateTree::FActiveStatePath::IndexOf (FActiveStateID Other) const nodiscard
Returns
true the index of element inside the path.
References Other, and UE_API.
Intersect() [1/2]
STATETREEMODULE_API const TArrayView< const FActiveState > UE::StateTree::FActiveStatePath::Intersect (const FActiveStatePath & Other) const nodiscard
Returns
the path where the 2 paths intersect.
References FActiveStatePath(), Other, and UE_API.
Intersect() [2/2]
STATETREEMODULE_API const TArrayView< const FActiveState > UE::StateTree::FActiveStatePath::Intersect (const TArrayView< const FActiveState > & A, const TArrayView< const FActiveState > & B) static nodiscard
Returns
the elements that are in both paths.
References A, B, and UE_API.
Matches() [1/6]
STATETREEMODULE_API bool UE::StateTree::FActiveStatePath::Matches (const FActiveStatePath & Other) const nodiscard
Returns
true if both paths match exactly.
References FActiveStatePath(), Other, and UE_API.
Matches() [2/6]
STATETREEMODULE_API bool UE::StateTree::FActiveStatePath::Matches (const TArrayView< const FActiveState > & A, const TArrayView< const FActiveState > & B) static nodiscard
Returns
true if both paths match exactly.
References A, B, and UE_API.
Matches() [3/6]
STATETREEMODULE_API bool UE::StateTree::FActiveStatePath::Matches (const TArrayView< const FActiveState > & Path, FActiveState Other) static nodiscard
Returns
true if the last element in the path matches.
References Other, Path, and UE_API.
Matches() [4/6]
STATETREEMODULE_API bool UE::StateTree::FActiveStatePath::Matches (const TArrayView< const FActiveState > & Path, FActiveStateID Other) static nodiscard
Returns
true if the last element in the path matches.
References Other, Path, and UE_API.
Matches() [5/6]
STATETREEMODULE_API bool UE::StateTree::FActiveStatePath::Matches (FActiveState Other) const nodiscard
Returns
true if the last element in the path matches.
References Other, and UE_API.
Matches() [6/6]
STATETREEMODULE_API bool UE::StateTree::FActiveStatePath::Matches (FActiveStateID Other) const nodiscard
Returns
true if the last element in the path matches.
References Other, and UE_API.
Num()
int32 UE::StateTree::FActiveStatePath::Num () const inline nodiscard
Returns
the number of elements in the path.
Definition at line 133 of file StateTreeStatePath.h.
References States.
StartsWith() [1/2]
STATETREEMODULE_API bool UE::StateTree::FActiveStatePath::StartsWith (const FActiveStatePath & Other) const nodiscard
Returns
true if this path starts with and contains the other path.
References FActiveStatePath(), Other, and UE_API.
StartsWith() [2/2]
STATETREEMODULE_API bool UE::StateTree::FActiveStatePath::StartsWith (const TArrayView< const FActiveState > & Path, const TArrayView< const FActiveState > & B) static nodiscard
Returns
true if the path starts with and contains the other path.
References B, Path, and UE_API.
Field Documentation
States
TArray<FActiveState> UE::StateTree::FActiveStatePath::States private
Definition at line 206 of file StateTreeStatePath.h.
Referenced by GetView(), and Num().
StateTree
TWeakObjectPtr<const UStateTree> UE::StateTree::FActiveStatePath::StateTree private
Definition at line 205 of file StateTreeStatePath.h.
Referenced by Describe().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/StateTree/Source/StateTreeModule/Public/StateTreeStatePath.h