Unreal Engine 5.6 C++ API: SRigVMNodeLayoutWidget Class Reference
SRigVMNodeLayoutWidget Class Reference
#include "SRigVMNodeLayoutWidget.h"
Data Structures
struct FNodeLayoutRow
class FRigVMNodeLayoutDragDropOp
class SRigVMNowLayoutRow
Public Member Functions
virtual ~SRigVMNodeLayoutWidget () override
void Construct (const FArguments &InArgs)
virtual FReply OnKeyDown (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent) override
Called after a key is pressed when this widget has focus (this event bubbles if not handled)
void Refresh ()
OnGetCategories OnCategoryRemoved OnGetElementLabel OnGetElementCategory OnGetElementColor OnElementIndexInCategoryChanged OnGetStructuralHash OnValidateElementName SLATE_ATTRIBUTE (float, MaxScrollBoxSize) SLATE_END_ARGS() SRigVMNodeLayoutWidget()
SLATE_BEGIN_ARGS (SRigVMNodeLayoutWidget)
OnGetCategories SLATE_EVENT (FRigVMNodeLayoutWidget_OnCategoryAdded, OnCategoryAdded) SLATE_EVENT(FRigVMNodeLayoutWidget_OnCategoryRemoved
OnGetCategories OnCategoryRemoved SLATE_EVENT (FRigVMNodeLayoutWidget_OnCategoryRenamed, OnCategoryRenamed) SLATE_EVENT(FRigVMNodeLayoutWidget_OnGetElementLabel
OnGetCategories OnCategoryRemoved OnGetElementLabel OnGetElementCategory OnGetElementColor OnElementIndexInCategoryChanged SLATE_EVENT (FRigVMNodeLayoutWidget_OnElementCategoryChanged, OnElementCategoryChanged) SLATE_EVENT(FRigVMNodeLayoutWidget_OnGetStructuralHash
OnGetCategories OnCategoryRemoved OnGetElementLabel SLATE_EVENT (FRigVMNodeLayoutWidget_OnElementLabelChanged, OnElementLabelChanged) SLATE_EVENT(FRigVMNodeLayoutWidget_OnGetElementCategory
OnGetCategories OnCategoryRemoved OnGetElementLabel OnGetElementCategory OnGetElementColor SLATE_EVENT (FRigVMNodeLayoutWidget_OnGetElementIcon, OnGetElementIcon) SLATE_EVENT(FRigVMNodeLayoutWidget_OnElementIndexInCategoryChanged
OnGetCategories OnCategoryRemoved OnGetElementLabel OnGetElementCategory SLATE_EVENT (FRigVMNodeLayoutWidget_OnGetElementIndexInCategory, OnGetElementIndexInCategory) SLATE_EVENT(FRigVMNodeLayoutWidget_OnGetElementColor
SLATE_EVENT (FRigVMNodeLayoutWidget_OnGetUncategorizedPins, OnGetUncategorizedPins) SLATE_EVENT(FRigVMNodeLayoutWidget_OnGetCategories
OnGetCategories OnCategoryRemoved OnGetElementLabel OnGetElementCategory OnGetElementColor OnElementIndexInCategoryChanged OnGetStructuralHash SLATE_EVENT (FRigVMNodeLayoutWidget_ValidateName, OnValidateCategoryName) SLATE_EVENT(FRigVMNodeLayoutWidget_ValidateName
virtual void Tick (const FGeometry &AllottedGeometry, const double InCurrentTime, const float InDeltaTime) override
Ticks this widget with Geometry.
Public Member Functions inherited from SPanel
void Construct ()
Most panels do not create widgets as part of their implementation, so they do not need to implement a Construct()
virtual void SetVisibility (TAttribute< EVisibility > InVisibility) override final
Public Member Functions inherited from SWidget
template<typename MetaDataType>
void AddMetadata (const TSharedRef< MetaDataType > &AddMe)
Add metadata to this widget.
virtual const FSlateInvalidationRoot * Advanced_AsInvalidationRoot () const
FORCEINLINE TSharedPtr< SWidget > Advanced_GetPaintParentWidget () const
virtual bool Advanced_IsInvalidationRoot () const
virtual bool Advanced_IsWindow () const
Is this widget derivative of SWindow.
void ArrangeChildren (const FGeometry &AllottedGeometry, FArrangedChildren &ArrangedChildren, bool bUpdateAttributes=false) const
Non-virtual entry point for arrange children.
void AssignParentWidget (TSharedPtr< SWidget > InParent)
FORCEINLINE void CacheVolatility ()
Recalculates volatility of the widget and caches the result.
FSlateRect CalculateCullingAndClippingRules (const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, bool &bClipToBounds, bool &bAlwaysClip, bool &bIntersectClipBounds) const
Calculates what if any clipping state changes need to happen when drawing this widget.
bool ConditionallyDetatchParentWidget (SWidget *InExpectedParent)
void EnableToolTipForceField (const bool bEnableForceField)
Sets whether this widget is a "tool tip force field".
FORCEINLINE void ForceVolatile (bool bForce)
Should this widget always appear as volatile for any layout caching host widget.
virtual FChildren * GetAllChildren ()
Returns the children (if any) of this widget that are used by the invalidation system.
template<typename MetaDataType>
TArray< TSharedRef< MetaDataType > > GetAllMetaData () const
Get all metadata of the type provided.
const FGeometry & GetCachedGeometry () const
bool GetCanTick () const
FORCEINLINE EWidgetClipping GetClipping () const
FName GetCreatedInLocation () const
FORCEINLINE FMargin GetCullingBoundsExtension () const
const TOptional< FSlateClippingState > & GetCurrentClippingState () const
Returns the clipping state to clip this widget against its parent.
UE::Slate::FDeprecateVector2DResult GetDesiredSize () const
virtual FSlateColor GetDisabledForegroundColor () const
EFlowDirectionPreference GetFlowDirectionPreference () const
Gets the desired flow direction for the layout.
virtual FSlateColor GetForegroundColor () const
template<typename MetaDataType>
TSharedPtr< MetaDataType > GetMetaData () const
Get the metadata of the type provided.
const FGeometry & GetPaintSpaceGeometry () const
Gets the last geometry used to Tick the widget.
FORCEINLINE TSharedPtr< SWidget > GetParentWidget () const
const FSlateWidgetPersistentState & GetPersistentState () const
FORCEINLINE EWidgetPixelSnapping GetPixelSnapping () const
const FWidgetProxyHandle GetProxyHandle () const
virtual FString GetReadableLocation () const
virtual float GetRelativeLayoutScale (const int32 ChildIndex, float LayoutScaleMultiplier) const
What is the Child's scale relative to this widget.
FORCEINLINE float GetRenderOpacity () const
FORCEINLINE const TOptional< FSlateRenderTransform > & GetRenderTransform () const
FORCEINLINE UE::Slate::FDeprecateVector2DResult GetRenderTransformPivot () const
FORCEINLINE UE::Slate::FDeprecateVector2DResult GetRenderTransformPivotWithRespectToFlowDirection () const
FORCEINLINE TOptional< FSlateRenderTransform > GetRenderTransformWithRespectToFlowDirection () const
FORCEINLINE TStatId GetStatID (bool bForDeferredUse=false) const
virtual FName GetTag () const
const FGeometry & GetTickSpaceGeometry () const
Gets the last geometry used to Tick the widget.
virtual TSharedPtr< IToolTip > GetToolTip ()
FName GetType () const
FString GetTypeAsString () const
FORCEINLINE EVisibility GetVisibility () const
virtual EWindowZone::Type GetWindowZoneOverride () const
Called when the mouse is moved over the widget's window, to determine if we should report whether OS-specific features should be active at this location (such as a title bar grip, system menu, etc.) Usually you should not need to override this function.
bool HasActiveTimers () const
Does this widget have any active timers?
bool HasAnyUpdateFlags (EWidgetUpdateFlags FlagsToCheck) const
TOptional< EFocusCause > HasAnyUserFocus () const
Gets whether or not any users have this widget focused, and if so the type of focus (first one found).
bool HasAnyUserFocusOrFocusedDescendants () const
bool HasFocusedDescendants () const
virtual bool HasKeyboardFocus () const
Checks to see if this widget currently has the keyboard focus.
bool HasMouseCapture () const
Checks to see if this widget is the current mouse captor.
bool HasMouseCaptureByUser (int32 UserIndex, TOptional< int32 > PointerIndex=TOptional< int32 >()) const
Checks to see if this widget has mouse capture from the provided user.
bool HasRegisteredSlateAttribute () const
bool HasToolTipForceField () const
TOptional< EFocusCause > HasUserFocus (int32 UserIndex) const
Gets whether or not the specified users has this widget focused, and if so the type of focus.
bool HasUserFocusedDescendants (int32 UserIndex) const
Gets whether or not the specified users has this widget or any descendant focused.
void Invalidate (EInvalidateWidgetReason InvalidateReason)
Invalidates the widget from the view of a layout caching widget that may own this widget.
bool IsAttributesUpdatesEnabled () const
bool IsDirectlyHovered () const
FORCEINLINE bool IsEnabled () const
bool IsHovered () const
virtual bool IsInteractable () const
FORCEINLINE bool IsParentValid () const
FORCEINLINE bool IsVolatile () const
Whether or not a widget is volatile and will update every frame without being invalidated.
FORCEINLINE bool IsVolatileIndirectly () const
This widget is volatile because its parent or some ancestor is volatile.
void MarkPrepassAsDirty ()
In fast path, if the widget is mark, do a full Prepass on its next update to calculate it's desired size.
bool NeedsPrepass () const
virtual FReply OnAnalogValueChanged (const FGeometry &MyGeometry, const FAnalogInputEvent &InAnalogInputEvent)
Called when an analog value changes on a button that supports analog.
virtual FCursorReply OnCursorQuery (const FGeometry &MyGeometry, const FPointerEvent &CursorEvent) const
The system asks each widget under the mouse to provide a cursor.
virtual FReply OnDragDetected (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Called when Slate detects that a widget started to be dragged.
virtual void OnDragEnter (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called during drag and drop when the drag enters a widget.
virtual void OnDragLeave (const FDragDropEvent &DragDropEvent)
Called during drag and drop when the drag leaves a widget.
virtual FReply OnDragOver (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called during drag and drop when the the mouse is being dragged over a widget.
virtual void OnFinishedKeyInput ()
All the key (keyboard, gamepay, joystick, etc.) input from this frame has been routed.
virtual void OnFinishedPointerInput ()
All the pointer (mouse, touch, stylus, etc.) events from this frame have been routed.
virtual void OnFocusChanging (const FWeakWidgetPath &PreviousFocusPath, const FWidgetPath &NewWidgetPath, const FFocusEvent &InFocusEvent)
Called whenever a focus path is changing on all the widgets within the old and new focus paths.
virtual void OnFocusLost (const FFocusEvent &InFocusEvent)
Called when this widget loses focus.
virtual FReply OnFocusReceived (const FGeometry &MyGeometry, const FFocusEvent &InFocusEvent)
Called when focus is given to this widget.
virtual FReply OnKeyChar (const FGeometry &MyGeometry, const FCharacterEvent &InCharacterEvent)
Called after a character is entered while this widget has keyboard focus.
virtual FReply OnKeyUp (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
Called after a key is released when this widget has focus.
virtual TOptional< TSharedRef< SWidget > > OnMapCursor (const FCursorReply &CursorReply) const
After OnCursorQuery has specified a cursor type the system asks each widget under the mouse to map that cursor to a widget.
virtual FReply OnMotionDetected (const FGeometry &MyGeometry, const FMotionEvent &InMotionEvent)
Called when motion is detected (controller or device) e.g.
virtual FReply OnMouseButtonDoubleClick (const FGeometry &InMyGeometry, const FPointerEvent &InMouseEvent)
Called when a mouse button is double clicked.
virtual FReply OnMouseButtonDown (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system calls this method to notify the widget that a mouse button was pressed within it.
virtual FReply OnMouseButtonUp (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system calls this method to notify the widget that a mouse button was release within it.
virtual void OnMouseCaptureLost (const FCaptureLostEvent &CaptureLostEvent)
Called when this widget had captured the mouse, but that capture has been revoked for some reason.
virtual void OnMouseEnter (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system will use this event to notify a widget that the cursor has entered it.
virtual void OnMouseLeave (const FPointerEvent &MouseEvent)
The system will use this event to notify a widget that the cursor has left it.
virtual FReply OnMouseMove (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system calls this method to notify the widget that a mouse moved within it.
virtual FReply OnMouseWheel (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Called when the mouse wheel is spun.
virtual FNavigationReply OnNavigation (const FGeometry &MyGeometry, const FNavigationEvent &InNavigationEvent)
Called when navigation is requested e.g.
virtual FReply OnPreviewKeyDown (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
Called after a key is pressed when this widget or a child of this widget has focus If a widget handles this event, OnKeyDown will not be passed to the focused widget.
virtual FReply OnPreviewMouseButtonDown (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Just like OnMouseButtonDown, but tunnels instead of bubbling.
virtual FPopupMethodReply OnQueryPopupMethod () const
Popups can manifest in a NEW OS WINDOW or via an OVERLAY in an existing window.
virtual TOptional< bool > OnQueryShowFocus (const EFocusCause InFocusCause) const
Called to determine if we should render the focus brush.
virtual void OnToolTipClosing ()
Called when a tooltip displayed from this widget is being closed.
virtual FReply OnTouchEnded (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is ended (finger lifted)
virtual FReply OnTouchFirstMove (const FGeometry &MyGeometry, const FPointerEvent &TouchEvent)
Called when a touchpad touch first moves after TouchStarted.
virtual FReply OnTouchForceChanged (const FGeometry &MyGeometry, const FPointerEvent &TouchEvent)
Called when a touchpad touch force changes.
virtual FReply OnTouchGesture (const FGeometry &MyGeometry, const FPointerEvent &GestureEvent)
Called when the user performs a gesture on trackpad.
virtual FReply OnTouchMoved (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is moved (finger moved)
virtual FReply OnTouchStarted (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is started (finger down)
virtual TSharedPtr< FPopupLayer > OnVisualizePopup (const TSharedRef< SWidget > &PopupContent)
Visualize a new pop-up if possible.
virtual bool OnVisualizeTooltip (const TSharedPtr< SWidget > &TooltipContent)
Called when Slate wants to visualize tooltip.
int32 Paint (const FPaintArgs &Args, const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, FSlateWindowElementList &OutDrawElements, int32 LayerId, const FWidgetStyle &InWidgetStyle, bool bParentEnabled) const
Called to tell a widget to paint itself (and it's children).
TSharedRef< FActiveTimerHandle > RegisterActiveTimer (float TickPeriod, FWidgetActiveTimerDelegate TickFunction)
Registers an "active timer" delegate that will execute at some regular interval.
template<typename MetaDataType>
int32 RemoveMetaData (const TSharedRef< MetaDataType > &RemoveMe)
Remove metadata to this widget.
void SetCanTick (bool bInCanTick)
void SetClipping (EWidgetClipping InClipping)
Sets the clipping to bounds rules for this widget.
FORCEINLINE void SetCullingBoundsExtension (const FMargin &InCullingBoundsExtension)
Sets an additional culling padding that is added to a widget to give more leeway when culling widgets.
void SetCursor (const TAttribute< TOptional< EMouseCursor::Type > > &InCursor)
Set the cursor that should appear when this widget is hovered.
void SetEnabled (TAttribute< bool > InEnabledState)
Sets the enabled state of this widget.
void SetFlowDirectionPreference (EFlowDirectionPreference InFlowDirectionPreference)
Sets how content should flow in this panel, based on the current culture.
void SetOnMouseButtonDown (FPointerEventHandler EventHandler)
See OnMouseButtonDown event.
void SetOnMouseButtonUp (FPointerEventHandler EventHandler)
See OnMouseButtonUp event.
void SetOnMouseDoubleClick (FPointerEventHandler EventHandler)
See OnMouseDoubleClick event.
void SetOnMouseEnter (FNoReplyPointerEventHandler EventHandler)
See OnMouseEnter event.
void SetOnMouseLeave (FSimpleNoReplyPointerEventHandler EventHandler)
See OnMouseLeave event.
void SetOnMouseMove (FPointerEventHandler EventHandler)
See OnMouseMove event.
void SetPixelSnapping (EWidgetPixelSnapping InPixelSnappingMethod)
Sets the pixel snapping method for this widget.
FORCEINLINE void SetRenderOpacity (float InRenderOpacity)
FORCEINLINE void SetRenderTransform (TAttribute< TOptional< FSlateRenderTransform > > InTransform)
FORCEINLINE void SetRenderTransformPivot (TAttribute< FVector2D > InTransformPivot)
FORCEINLINE void SetTag (FName InTag)
void SetToolTip (const TAttribute< TSharedPtr< IToolTip > > &InToolTip)
Set the tool tip that should appear when this widget is hovered.
void SetToolTipText (const FText &InToolTipText)
Set the tool tip that should appear when this widget is hovered.
void SetToolTipText (const TAttribute< FText > &ToolTipText)
Set the tool tip that should appear when this widget is hovered.
FORCEINLINE bool ShouldInvalidatePrepassDueToVolatility ()
void SlatePrepass ()
DEPRECATED version of SlatePrepass that assumes no scaling beyond AppScale.
void SlatePrepass (float InLayoutScaleMultiplier)
Descends to leaf-most widgets in the hierarchy and gathers desired sizes on the way up.
virtual bool SupportsKeyboardFocus () const
Checks to see if this widget supports keyboard focus.
virtual FString ToString () const
virtual TOptional< FVirtualPointerPosition > TranslateMouseCoordinateForCustomHitTestChild (const SWidget &ChildWidget, const FGeometry &MyGeometry, const FVector2D ScreenSpaceMouseCoordinate, const FVector2D LastScreenSpaceMouseCoordinate) const
void UnRegisterActiveTimer (const TSharedRef< FActiveTimerHandle > &ActiveTimerHandle)
Unregisters an active timer handle.
virtual bool ValidatePathToChild (SWidget *InChild)
Public Member Functions inherited from FSlateControlledConstruction
FSlateControlledConstruction ()=default
virtual ~FSlateControlledConstruction ()=default
virtual const FSlateWidgetClassData & GetWidgetClass () const =0
void operator delete (void *mem)
Public Member Functions inherited from TSharedFromThis< SWidget >
TSharedRef< SWidget, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< SWidget, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Private Member Functions
DECLARE_DELEGATE_RetVal_ThreeParams (FReply, FRigVMNodeLayoutWidget_OnElementAcceptDrop, TSharedPtr< FNodeLayoutRow >, TSharedPtr< FNodeLayoutRow >, EItemDropZone)
DECLARE_DELEGATE_RetVal_ThreeParams (TOptional< EItemDropZone >, FRigVMNodeLayoutWidget_OnElementCanDrop, TSharedPtr< FNodeLayoutRow >, TSharedPtr< FNodeLayoutRow >, EItemDropZone)
TSharedRef< ITableRow > GenerateRow (TSharedPtr< FNodeLayoutRow > InRow, const TSharedRef< STableViewBase > &OwnerTable)
void GetChildrenForRow (TSharedPtr< FNodeLayoutRow > InRow, TArray< TSharedPtr< FNodeLayoutRow > > &OutChildren)
FReply HandleAddCategory ()
bool IsNodeLayoutEditable () const
FReply OnAcceptDrop (const FDragDropEvent &InDragDropEvent, TSharedPtr< FNodeLayoutRow > InTargetRow, EItemDropZone InDropZone)
TOptional< EItemDropZone > OnCanAcceptDrop (const FDragDropEvent &InDragDropEvent, TSharedPtr< FNodeLayoutRow > InTargetRow, EItemDropZone InDropZone)
FReply OnDragDetectedForRow (TSharedPtr< FNodeLayoutRow > InSourceRow)
virtual FReply OnDrop (const FGeometry &InGeometry, const FDragDropEvent &InDragDropEvent)
Called when the user is dropping something onto a widget; terminates drag and drop.
void OnItemExpansionChanged (TSharedPtr< FNodeLayoutRow > InRow, bool bExpanded)
void OnItemSelectionChanged (TSharedPtr< FNodeLayoutRow > InRow, ESelectInfo::Type InSelectInfo)
Private Attributes
TOptional< uint32 > LastStructuralHash
TArray< TSharedPtr< FNodeLayoutRow > > NodeLayoutRows
FRigVMNodeLayoutWidget_OnCategoryAdded OnCategoryAdded
FRigVMNodeLayoutWidget_OnCategoryRemoved OnCategoryRemoved
FRigVMNodeLayoutWidget_OnCategoryRenamed OnCategoryRenamed
FRigVMNodeLayoutWidget_OnElementCategoryChanged OnElementCategoryChanged
FRigVMNodeLayoutWidget_OnElementIndexInCategoryChanged OnElementIndexInCategoryChanged
FRigVMNodeLayoutWidget_OnElementLabelChanged OnElementLabelChanged
FRigVMNodeLayoutWidget_OnGetCategories OnGetCategories
FRigVMNodeLayoutWidget_OnGetElementCategory OnGetElementCategory
FRigVMNodeLayoutWidget_OnGetElementColor OnGetElementColor
FRigVMNodeLayoutWidget_OnGetElementIcon OnGetElementIcon
FRigVMNodeLayoutWidget_OnGetElementIndexInCategory OnGetElementIndexInCategory
FRigVMNodeLayoutWidget_OnGetElementLabel OnGetElementLabel
FRigVMNodeLayoutWidget_OnGetStructuralHash OnGetStructuralHash
FRigVMNodeLayoutWidget_OnGetUncategorizedPins OnGetUncategorizedPins
FRigVMNodeLayoutWidget_ValidateName OnValidateCategoryName
FRigVMNodeLayoutWidget_ValidateName OnValidateElementName
TSharedPtr< STreeView< TSharedPtr< FNodeLayoutRow > > > TreeView
Additional Inherited Members
Static Public Member Functions inherited from FSlateControlledConstruction
static const FSlateWidgetClassData & StaticWidgetClass ()
Protected Member Functions inherited from SBox
float ComputeDesiredHeight () const
virtual FVector2D ComputeDesiredSize (float) const override
A Panel's desired size in the space required to arrange of its children on the screen while respecting all of the children's desired sizes and any layout-related options specified by the user.
float ComputeDesiredWidth () const
Protected Member Functions inherited from SPanel
SPanel ()
Hidden default constructor.
virtual ~SPanel ()
int32 PaintArrangedChildren (const FPaintArgs &Args, const FArrangedChildren &ArrangedChildren, const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, FSlateWindowElementList &OutDrawElements, int32 LayerId, const FWidgetStyle &InWidgetStyle, bool bParentEnabled) const
Just like OnPaint, but takes already arranged children.
Protected Member Functions inherited from SWidget
SWidget ()
Hidden default constructor.
virtual ~SWidget ()
Dtor ensures that active timer handles are UnRegistered with the SlateApplication.
FORCEINLINE bool Advanced_InvalidateVolatility ()
Recalculates and caches volatility and returns 'true' if the volatility changed.
virtual void CacheDesiredSize (float InLayoutScaleMultiplier)
The system calls this method.
EFlowDirection ComputeFlowDirection () const
Establishes a new flow direction potentially, if this widget has a particular preference for it and all its children.
virtual bool ComputeVolatility () const
Recomputes the volatility of the widget.
virtual bool CustomPrepass (float LayoutScaleMultiplier)
bool FindChildGeometries (const FGeometry &MyGeometry, const TSet< TSharedRef< SWidget > > &WidgetsToFind, TMap< TSharedRef< SWidget >, FArrangedWidget > &OutResult) const
Find the geometry of a descendant widget.
void FindChildGeometries_Helper (const FGeometry &MyGeometry, const TSet< TSharedRef< SWidget > > &WidgetsToFind, TMap< TSharedRef< SWidget >, FArrangedWidget > &OutResult) const
Actual implementation of FindChildGeometries.
FGeometry FindChildGeometry (const FGeometry &MyGeometry, TSharedRef< SWidget > WidgetToFind) const
Find the geometry of a descendant widget.
virtual TOptional< EMouseCursor::Type > GetCursor () const
The cursor to show when the mouse is hovering over this widget.
TSlateAttributeRef< bool > GetEnabledStateAttribute () const
virtual const FSlateBrush * GetFocusBrush () const
TSlateAttributeRef< bool > GetHoveredAttribute () const
float GetPrepassLayoutScaleMultiplier () const
TSlateAttributeRef< TOptional< FSlateRenderTransform > > GetRenderTransformAttribute () const
TSlateAttributeRef< FVector2D > GetRenderTransformPivotAttribute () const
TSlateAttributeRef< EVisibility > GetVisibilityAttribute () const
void InvalidateChildRemovedFromTree (SWidget &Child)
Called when a child is removed from the tree parent's widget tree either by removing it from a slot.
FORCEINLINE bool IsChildWidgetCulled (const FSlateRect &, const FArrangedWidget &) const
bool IsConstructed () const
Is the widget construction completed (did we called and returned from the Construct() function)
virtual void OnClippingChanged ()
Called when clipping is changed.
void Prepass_ChildLoop (float InLayoutScaleMultiplier, FChildren *MyChildren)
template<typename TargetValueType, typename SourceValueType>
bool SetAttribute (TAttribute< TargetValueType > &TargetValue, const TAttribute< SourceValueType > &SourceValue, EInvalidateWidgetReason BaseInvalidationReason)
Performs the attribute assignment and invalidates the widget minimally based on what actually changed.
void SetDebugInfo (const ANSICHAR *InType, const ANSICHAR *InFile, int32 OnLine, size_t InAllocSize)
Used by Slate to set the runtime debug info about this widget.
void SetHover (TAttribute< bool > InHovered)
Set the hover state.
void SetVolatilePrepass (bool bVolatile)
bool ShouldBeEnabled (bool InParentEnabled) const
Determines if this widget should be enabled.
void SWidgetConstruct (const FSlateBaseNamedArgs &Args)
Construct a SWidget based on initial parameters.
Protected Member Functions inherited from TSharedFromThis< SWidget >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions inherited from SWidget
static TAttribute< EVisibility > AccessWidgetVisibilityAttribute (const TSharedRef< SWidget > &Widget)
Protected static helper to allow widgets to access the visibility attribute of other widgets directly.
static int32 FindChildUnderMouse (const FArrangedChildren &Children, const FPointerEvent &MouseEvent)
static int32 FindChildUnderPosition (const FArrangedChildren &Children, const UE::Slate::FDeprecateVector2DParameter &ArrangedSpacePosition)
Static Protected Member Functions inherited from TSharedFromThis< SWidget >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Protected Attributes inherited from SBox
FBoxOneChildSlot ChildSlot
Protected Attributes inherited from SWidget
uint8 bCanHaveChildren: 1
Can the widget ever support children?
uint8 bCanSupportFocus: 1
Can the widget ever support keyboard focus.
uint8 bClippingProxy: 1
Some widgets might be a complex hierarchy of child widgets you never see.
uint8 bHasCustomPrepass: 1
uint8 bHasRelativeLayoutScale: 1
uint8 bVolatilityAlwaysInvalidatesPrepass: 1
if this widget should always invalidate the prepass step when volatile
EWidgetClipping Clipping
Set to true if all content of the widget should clip to the bounds of this widget.
FMargin CullingBoundsExtension
Can be used to enlarge the culling bounds of this widget (pre-intersection), this can be useful if you've got children that you know are using rendering transforms to render outside their standard bounds, if that happens it's possible the parent might be culled before the descendant widget is entirely off screen.
EWidgetPixelSnapping PixelSnappingMethod
When set to EPixelSnappingMethod::SnapToPixel, the widget is drawn at the nearest pixel.
float RenderOpacity
The opacity of the widget.
Detailed Description
Definition at line 27 of file SRigVMNodeLayoutWidget.h.
Constructor & Destructor Documentation
~SRigVMNodeLayoutWidget()
virtual SRigVMNodeLayoutWidget::~SRigVMNodeLayoutWidget () override virtual
Member Function Documentation
Construct()
void SRigVMNodeLayoutWidget::Construct (const FArguments & InArgs)
References Construct().
Referenced by Construct().
DECLARE_DELEGATE_RetVal_ThreeParams() [1/2]
SRigVMNodeLayoutWidget::DECLARE_DELEGATE_RetVal_ThreeParams (FReply , FRigVMNodeLayoutWidget_OnElementAcceptDrop , TSharedPtr< FNodeLayoutRow > , TSharedPtr< FNodeLayoutRow > , EItemDropZone) private
DECLARE_DELEGATE_RetVal_ThreeParams() [2/2]
SRigVMNodeLayoutWidget::DECLARE_DELEGATE_RetVal_ThreeParams (TOptional< EItemDropZone > , FRigVMNodeLayoutWidget_OnElementCanDrop , TSharedPtr< FNodeLayoutRow > , TSharedPtr< FNodeLayoutRow > , EItemDropZone) private
GenerateRow()
TSharedRef< ITableRow > SRigVMNodeLayoutWidget::GenerateRow (TSharedPtr< FNodeLayoutRow > InRow, const TSharedRef< STableViewBase > & OwnerTable) private
GetChildrenForRow()
void SRigVMNodeLayoutWidget::GetChildrenForRow (TSharedPtr< FNodeLayoutRow > InRow, TArray< TSharedPtr< FNodeLayoutRow > > & OutChildren) private
HandleAddCategory()
FReply SRigVMNodeLayoutWidget::HandleAddCategory () private
IsNodeLayoutEditable()
bool SRigVMNodeLayoutWidget::IsNodeLayoutEditable () const private
OnAcceptDrop()
FReply SRigVMNodeLayoutWidget::OnAcceptDrop (const FDragDropEvent & InDragDropEvent, TSharedPtr< FNodeLayoutRow > InTargetRow, EItemDropZone InDropZone) private
OnCanAcceptDrop()
TOptional< EItemDropZone > SRigVMNodeLayoutWidget::OnCanAcceptDrop (const FDragDropEvent & InDragDropEvent, TSharedPtr< FNodeLayoutRow > InTargetRow, EItemDropZone InDropZone) private
OnDragDetectedForRow()
FReply SRigVMNodeLayoutWidget::OnDragDetectedForRow (TSharedPtr< FNodeLayoutRow > InSourceRow) private
OnDrop()
virtual FReply SRigVMNodeLayoutWidget::OnDrop (const FGeometry & MyGeometry, const FDragDropEvent & DragDropEvent) private virtual
Called when the user is dropping something onto a widget; terminates drag and drop.
Parameters
MyGeometry The geometry of the widget receiving the event.
DragDropEvent The drag and drop event.
Returns
A reply that indicated whether this event was handled.
Reimplemented from SWidget.
OnItemExpansionChanged()
void SRigVMNodeLayoutWidget::OnItemExpansionChanged (TSharedPtr< FNodeLayoutRow > InRow, bool bExpanded) private
OnItemSelectionChanged()
void SRigVMNodeLayoutWidget::OnItemSelectionChanged (TSharedPtr< FNodeLayoutRow > InRow, ESelectInfo::Type InSelectInfo) private
OnKeyDown()
virtual FReply SRigVMNodeLayoutWidget::OnKeyDown (const FGeometry & MyGeometry, const FKeyEvent & InKeyEvent) override virtual
Called after a key is pressed when this widget has focus (this event bubbles if not handled)
Parameters
MyGeometry The Geometry of the widget receiving the event
InKeyEvent Key event
Returns
Returns whether the event was handled, along with other possible actions
Reimplemented from SWidget.
References OnKeyDown().
Referenced by OnKeyDown().
Refresh()
void SRigVMNodeLayoutWidget::Refresh ()
References Refresh().
Referenced by Refresh().
SLATE_ATTRIBUTE()
OnGetCategories OnCategoryRemoved OnGetElementLabel OnGetElementCategory OnGetElementColor OnElementIndexInCategoryChanged OnGetStructuralHash OnValidateElementName SRigVMNodeLayoutWidget::SLATE_ATTRIBUTE (float , MaxScrollBoxSize)
References SLATE_ATTRIBUTE(), and SBox::SLATE_END_ARGS().
Referenced by SLATE_ATTRIBUTE().
SLATE_BEGIN_ARGS()
SRigVMNodeLayoutWidget::SLATE_BEGIN_ARGS (SRigVMNodeLayoutWidget) inline
Definition at line 31 of file SRigVMNodeLayoutWidget.h.
SLATE_EVENT() [1/8]
OnGetCategories SRigVMNodeLayoutWidget::SLATE_EVENT (FRigVMNodeLayoutWidget_OnCategoryAdded , OnCategoryAdded)
References OnCategoryAdded, OnCategoryRemoved, and SLATE_EVENT().
SLATE_EVENT() [2/8]
OnGetCategories OnCategoryRemoved SRigVMNodeLayoutWidget::SLATE_EVENT (FRigVMNodeLayoutWidget_OnCategoryRenamed , OnCategoryRenamed)
References OnCategoryRenamed, OnGetElementLabel, and SLATE_EVENT().
SLATE_EVENT() [3/8]
OnGetCategories OnCategoryRemoved OnGetElementLabel OnGetElementCategory OnGetElementColor OnElementIndexInCategoryChanged SRigVMNodeLayoutWidget::SLATE_EVENT (FRigVMNodeLayoutWidget_OnElementCategoryChanged , OnElementCategoryChanged)
References OnElementCategoryChanged, OnGetStructuralHash, and SLATE_EVENT().
SLATE_EVENT() [4/8]
OnGetCategories OnCategoryRemoved OnGetElementLabel SRigVMNodeLayoutWidget::SLATE_EVENT (FRigVMNodeLayoutWidget_OnElementLabelChanged , OnElementLabelChanged)
References OnElementLabelChanged, OnGetElementCategory, and SLATE_EVENT().
SLATE_EVENT() [5/8]
OnGetCategories OnCategoryRemoved OnGetElementLabel OnGetElementCategory OnGetElementColor SRigVMNodeLayoutWidget::SLATE_EVENT (FRigVMNodeLayoutWidget_OnGetElementIcon , OnGetElementIcon)
References OnElementIndexInCategoryChanged, OnGetElementIcon, and SLATE_EVENT().
SLATE_EVENT() [6/8]
OnGetCategories OnCategoryRemoved OnGetElementLabel OnGetElementCategory SRigVMNodeLayoutWidget::SLATE_EVENT (FRigVMNodeLayoutWidget_OnGetElementIndexInCategory , OnGetElementIndexInCategory)
References OnGetElementColor, OnGetElementIndexInCategory, and SLATE_EVENT().
SLATE_EVENT() [7/8]
SRigVMNodeLayoutWidget::SLATE_EVENT (FRigVMNodeLayoutWidget_OnGetUncategorizedPins , OnGetUncategorizedPins)
References OnGetCategories, and OnGetUncategorizedPins.
Referenced by SLATE_EVENT(), SLATE_EVENT(), SLATE_EVENT(), SLATE_EVENT(), SLATE_EVENT(), SLATE_EVENT(), and SLATE_EVENT().
SLATE_EVENT() [8/8]
OnGetCategories OnCategoryRemoved OnGetElementLabel OnGetElementCategory OnGetElementColor OnElementIndexInCategoryChanged OnGetStructuralHash SRigVMNodeLayoutWidget::SLATE_EVENT (FRigVMNodeLayoutWidget_ValidateName , OnValidateCategoryName)
References OnValidateCategoryName, OnValidateElementName, and SLATE_EVENT().
Tick()
virtual void SRigVMNodeLayoutWidget::Tick (const FGeometry & AllottedGeometry, const double InCurrentTime, const float InDeltaTime) override virtual
Ticks this widget with Geometry.
Override in derived classes, but always call the parent implementation.
Parameters
AllottedGeometry The space allotted for this widget
InCurrentTime Current absolute real time
InDeltaTime Real time passed since last tick
Reimplemented from SWidget.
References Tick().
Referenced by Tick().
Field Documentation
LastStructuralHash
TOptional<uint32> SRigVMNodeLayoutWidget::LastStructuralHash private
Definition at line 225 of file SRigVMNodeLayoutWidget.h.
NodeLayoutRows
TArray<TSharedPtr<FNodeLayoutRow> > SRigVMNodeLayoutWidget::NodeLayoutRows private
Definition at line 223 of file SRigVMNodeLayoutWidget.h.
OnCategoryAdded
FRigVMNodeLayoutWidget_OnCategoryAdded SRigVMNodeLayoutWidget::OnCategoryAdded private
Definition at line 66 of file SRigVMNodeLayoutWidget.h.
Referenced by SLATE_EVENT().
OnCategoryRemoved
FRigVMNodeLayoutWidget_OnCategoryRemoved SRigVMNodeLayoutWidget::OnCategoryRemoved private
Definition at line 67 of file SRigVMNodeLayoutWidget.h.
Referenced by SLATE_EVENT().
OnCategoryRenamed
FRigVMNodeLayoutWidget_OnCategoryRenamed SRigVMNodeLayoutWidget::OnCategoryRenamed private
Definition at line 68 of file SRigVMNodeLayoutWidget.h.
Referenced by SLATE_EVENT().
OnElementCategoryChanged
FRigVMNodeLayoutWidget_OnElementCategoryChanged SRigVMNodeLayoutWidget::OnElementCategoryChanged private
Definition at line 76 of file SRigVMNodeLayoutWidget.h.
Referenced by SLATE_EVENT().
OnElementIndexInCategoryChanged
FRigVMNodeLayoutWidget_OnElementIndexInCategoryChanged SRigVMNodeLayoutWidget::OnElementIndexInCategoryChanged private
Definition at line 75 of file SRigVMNodeLayoutWidget.h.
Referenced by SLATE_EVENT().
OnElementLabelChanged
FRigVMNodeLayoutWidget_OnElementLabelChanged SRigVMNodeLayoutWidget::OnElementLabelChanged private
Definition at line 70 of file SRigVMNodeLayoutWidget.h.
Referenced by SLATE_EVENT().
OnGetCategories
FRigVMNodeLayoutWidget_OnGetCategories SRigVMNodeLayoutWidget::OnGetCategories private
Definition at line 65 of file SRigVMNodeLayoutWidget.h.
Referenced by SLATE_EVENT().
OnGetElementCategory
FRigVMNodeLayoutWidget_OnGetElementCategory SRigVMNodeLayoutWidget::OnGetElementCategory private
Definition at line 71 of file SRigVMNodeLayoutWidget.h.
Referenced by SLATE_EVENT().
OnGetElementColor
FRigVMNodeLayoutWidget_OnGetElementColor SRigVMNodeLayoutWidget::OnGetElementColor private
Definition at line 73 of file SRigVMNodeLayoutWidget.h.
Referenced by SLATE_EVENT().
OnGetElementIcon
FRigVMNodeLayoutWidget_OnGetElementIcon SRigVMNodeLayoutWidget::OnGetElementIcon private
Definition at line 74 of file SRigVMNodeLayoutWidget.h.
Referenced by SLATE_EVENT().
OnGetElementIndexInCategory
FRigVMNodeLayoutWidget_OnGetElementIndexInCategory SRigVMNodeLayoutWidget::OnGetElementIndexInCategory private
Definition at line 72 of file SRigVMNodeLayoutWidget.h.
Referenced by SLATE_EVENT().
OnGetElementLabel
FRigVMNodeLayoutWidget_OnGetElementLabel SRigVMNodeLayoutWidget::OnGetElementLabel private
Definition at line 69 of file SRigVMNodeLayoutWidget.h.
Referenced by SLATE_EVENT().
OnGetStructuralHash
FRigVMNodeLayoutWidget_OnGetStructuralHash SRigVMNodeLayoutWidget::OnGetStructuralHash private
Definition at line 77 of file SRigVMNodeLayoutWidget.h.
Referenced by SLATE_EVENT().
OnGetUncategorizedPins
FRigVMNodeLayoutWidget_OnGetUncategorizedPins SRigVMNodeLayoutWidget::OnGetUncategorizedPins private
Definition at line 64 of file SRigVMNodeLayoutWidget.h.
Referenced by SLATE_EVENT().
OnValidateCategoryName
FRigVMNodeLayoutWidget_ValidateName SRigVMNodeLayoutWidget::OnValidateCategoryName private
Definition at line 78 of file SRigVMNodeLayoutWidget.h.
Referenced by SLATE_EVENT().
OnValidateElementName
FRigVMNodeLayoutWidget_ValidateName SRigVMNodeLayoutWidget::OnValidateElementName private
Definition at line 79 of file SRigVMNodeLayoutWidget.h.
Referenced by SLATE_EVENT().
TreeView
TSharedPtr<STreeView<TSharedPtr<FNodeLayoutRow> > > SRigVMNodeLayoutWidget::TreeView private
Definition at line 224 of file SRigVMNodeLayoutWidget.h.
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/RigVM/Source/RigVMEditor/Public/Widgets/SRigVMNodeLayoutWidget.h