Unreal Engine 5.6 C++ API: FCbPackage Class Reference
FCbPackage Class Reference
A package is an object with a tree of referenced attachments.
#include "CompactBinaryPackage.h"
Public Types
using FAttachmentResolver = TFunctionRef<FSharedBuffer (const FIoHash& Hash)>
A function that resolves a hash to a buffer containing the data matching that hash.
Public Member Functions
FCbPackage ()=default
Construct a null package.
FCbPackage (FCbObject InObject)
Construct a package from a root object without gathering attachments.
FCbPackage (FCbObject InObject, const FIoHash &InObjectHash)
Construct a package from a root object without gathering attachments.
FCbPackage (FCbObject InObject, const FIoHash &InObjectHash, FAttachmentResolver InResolver)
Construct a package from a root object and gather attachments using the resolver.
FCbPackage (FCbObject InObject, FAttachmentResolver InResolver)
Construct a package from a root object and gather attachments using the resolver.
void AddAttachment (const FCbAttachment &Attachment)
Add the attachment to this package.
void AddAttachment (const FCbAttachment &Attachment, FAttachmentResolver Resolver)
Add the attachment to this package, along with any references that can be resolved.
bool Equals (const FCbPackage &Package) const
Compares packages by their object and attachment hashes.
const FCbAttachment * FindAttachment (const FCbAttachment &Attachment) const
Find an attachment if it exists in the package.
const FCbAttachment * FindAttachment (const FIoHash &Hash) const
Find an attachment by its hash.
TConstArrayView< FCbAttachment > GetAttachments () const
Returns the attachments in this package.
const FCbObject & GetObject () const
Returns the object for the package.
const FIoHash & GetObjectHash () const
Returns the hash of the object for the package.
bool IsNull () const
Whether the package has an empty object and no attachments.
operator bool () const
Whether the package has a non-empty object or attachments.
bool operator!= (const FCbPackage &Package) const
bool operator== (const FCbPackage &Package) const
int32 RemoveAttachment (const FCbAttachment &Attachment)
int32 RemoveAttachment (const FIoHash &Hash)
Remove an attachment by hash.
void Reset ()
Reset this to a null package.
void Save (FArchive &Ar) const
Save the object and attachments into the archive as a stream of compact binary fields.
void Save (FCbWriter &Writer) const
Save the object and attachments into the writer as a stream of compact binary fields.
void SetObject (FCbObject InObject)
Set the root object without gathering attachments.
void SetObject (FCbObject InObject, const FIoHash &InObjectHash)
Set the root object without gathering attachments.
void SetObject (FCbObject InObject, const FIoHash &InObjectHash, FAttachmentResolver InResolver)
Set the root object and gather attachments using the resolver.
void SetObject (FCbObject InObject, FAttachmentResolver InResolver)
Set the root object and gather attachments using the resolver.
bool TryLoad (FArchive &Ar, FCbBufferAllocator Allocator=FUniqueBuffer::Alloc)
Load the object and attachments from compact binary as written by Save.
bool TryLoad (FCbFieldIterator &Fields)
Load the object and attachments from compact binary as written by Save.
Private Member Functions
void AddAttachment (const FCbAttachment &Attachment, FAttachmentResolver *Resolver)
void GatherAttachments (const FCbObject &Object, FAttachmentResolver Resolver)
void SetObject (FCbObject Object, const FIoHash *Hash, FAttachmentResolver *Resolver)
Private Attributes
TArray< FCbAttachment > Attachments
Attachments ordered by their hash.
FCbObject Object
FIoHash ObjectHash
Detailed Description
A package is an object with a tree of referenced attachments.
A package is a Merkle tree with an object as its root and non-leaf nodes, and either binary or objects as its leaf nodes. Nodes reference their children from fields of type BinaryAttachment or ObjectAttachment, which store the raw hash of the referenced attachment.
It is invalid for a package to include attachments that are not referenced by its object or by one of its referenced object attachments. This invariant needs to be maintained if attachments are added explicitly instead of being discovered by the attachment resolver. If any attachment is not referenced, it may not survive a round-trip through certain storage systems.
It is valid for a package to exclude referenced attachments, but then it is the responsibility of the package consumer to have a mechanism for resolving those references when necessary.
A package is serialized as a sequence of compact binary fields with no name. The object may be both preceded and followed by attachments. The object is only serialized when it is non-empty, starting with its hash, in a Hash field, followed by the object, in an Object field. A package ends with a Null field. The canonical order of components is the object and its hash, followed by the attachments ordered by hash, followed by a Null field. It is valid for the a package to have its attachments serialized in any order relative to each other and to the object.
Definition at line 255 of file CompactBinaryPackage.h.
Member Typedef Documentation
FAttachmentResolver
using FCbPackage::FAttachmentResolver = TFunctionRef<FSharedBuffer (const FIoHash& Hash)>
A function that resolves a hash to a buffer containing the data matching that hash.
The resolver may return a null buffer to skip resolving an attachment for the hash.
Definition at line 263 of file CompactBinaryPackage.h.
Constructor & Destructor Documentation
FCbPackage() [1/5]
FCbPackage::FCbPackage () default
Construct a null package.
Referenced by Equals(), operator!=(), operator==(), and Reset().
FCbPackage() [2/5]
FCbPackage::FCbPackage (FCbObject InObject) inline explicit
Construct a package from a root object without gathering attachments.
Parameters
InObject The root object, which will be cloned unless it is owned.
Definition at line 273 of file CompactBinaryPackage.h.
References MoveTemp(), and SetObject().
FCbPackage() [3/5]
FCbPackage::FCbPackage (FCbObject InObject, FAttachmentResolver InResolver) inline explicit
Construct a package from a root object and gather attachments using the resolver.
Parameters
InObject The root object, which will be cloned unless it is owned.
InResolver A function that is invoked for every reference and binary reference field.
Definition at line 284 of file CompactBinaryPackage.h.
References MoveTemp(), and SetObject().
FCbPackage() [4/5]
FCbPackage::FCbPackage (FCbObject InObject, const FIoHash & InObjectHash) inline explicit
Construct a package from a root object without gathering attachments.
Parameters
InObject The root object, which will be cloned unless it is owned.
InObjectHash The hash of the object, which must match to avoid validation errors.
Definition at line 295 of file CompactBinaryPackage.h.
References MoveTemp(), and SetObject().
FCbPackage() [5/5]
FCbPackage::FCbPackage (FCbObject InObject, const FIoHash & InObjectHash, FAttachmentResolver InResolver) inline explicit
Construct a package from a root object and gather attachments using the resolver.
Parameters
InObject The root object, which will be cloned unless it is owned.
InObjectHash The hash of the object, which must match to avoid validation errors.
InResolver A function that is invoked for every reference and binary reference field.
Definition at line 307 of file CompactBinaryPackage.h.
References MoveTemp(), and SetObject().
Member Function Documentation
AddAttachment() [1/3]
void FCbPackage::AddAttachment (const FCbAttachment & Attachment) inline
Add the attachment to this package.
Definition at line 389 of file CompactBinaryPackage.h.
References AddAttachment().
Referenced by AddAttachment(), and AddAttachment().
AddAttachment() [2/3]
void FCbPackage::AddAttachment (const FCbAttachment & Attachment, FAttachmentResolver * Resolver) private
AddAttachment() [3/3]
void FCbPackage::AddAttachment (const FCbAttachment & Attachment, FAttachmentResolver Resolver) inline
Add the attachment to this package, along with any references that can be resolved.
Definition at line 395 of file CompactBinaryPackage.h.
References AddAttachment().
Equals()
bool FCbPackage::Equals (const FCbPackage & Package) const
Compares packages by their object and attachment hashes.
References FCbPackage(), and Package.
Referenced by operator!=(), and operator==().
FindAttachment() [1/2]
const FCbAttachment * FCbPackage::FindAttachment (const FCbAttachment & Attachment) const inline
Find an attachment if it exists in the package.
Definition at line 383 of file CompactBinaryPackage.h.
References FindAttachment(), and FCbAttachment::GetHash().
FindAttachment() [2/2]
const FCbAttachment * FCbPackage::FindAttachment (const FIoHash & Hash) const
Find an attachment by its hash.
Returns
The attachment, or null if the attachment is not found.
Note
The returned pointer is only valid until the attachments on this package are modified.
References Hash.
Referenced by FindAttachment().
GatherAttachments()
void FCbPackage::GatherAttachments (const FCbObject & Object, FAttachmentResolver Resolver) private
References Object.
GetAttachments()
TConstArrayView< FCbAttachment > FCbPackage::GetAttachments () const inline
Returns the attachments in this package.
Definition at line 372 of file CompactBinaryPackage.h.
References Attachments.
GetObject()
const FCbObject & FCbPackage::GetObject () const inline
Returns the object for the package.
Definition at line 322 of file CompactBinaryPackage.h.
References Object.
GetObjectHash()
const FIoHash & FCbPackage::GetObjectHash () const inline
Returns the hash of the object for the package.
Definition at line 325 of file CompactBinaryPackage.h.
References ObjectHash.
IsNull()
bool FCbPackage::IsNull () const inline
Whether the package has an empty object and no attachments.
Definition at line 319 of file CompactBinaryPackage.h.
References Attachments, and Object.
Referenced by operator bool().
operator bool()
FCbPackage::operator bool () const inline explicit
Whether the package has a non-empty object or attachments.
Definition at line 316 of file CompactBinaryPackage.h.
References IsNull().
operator!=()
bool FCbPackage::operator!= (const FCbPackage & Package) const inline
Definition at line 411 of file CompactBinaryPackage.h.
References FCbPackage(), Equals(), and Package.
operator==()
bool FCbPackage::operator== (const FCbPackage & Package) const inline
Definition at line 410 of file CompactBinaryPackage.h.
References FCbPackage(), Equals(), and Package.
RemoveAttachment() [1/2]
int32 FCbPackage::RemoveAttachment (const FCbAttachment & Attachment) inline
Definition at line 406 of file CompactBinaryPackage.h.
References FCbAttachment::GetHash(), and RemoveAttachment().
Referenced by RemoveAttachment().
RemoveAttachment() [2/2]
int32 FCbPackage::RemoveAttachment (const FIoHash & Hash)
Remove an attachment by hash.
Returns
Number of attachments removed, which will be either 0 or 1.
References Hash.
Reset()
void FCbPackage::Reset () inline
Reset this to a null package.
Definition at line 313 of file CompactBinaryPackage.h.
References FCbPackage().
Save() [1/2]
void FCbPackage::Save (FArchive & Ar) const
Save the object and attachments into the archive as a stream of compact binary fields.
References Ar.
Save() [2/2]
void FCbPackage::Save (FCbWriter & Writer) const
Save the object and attachments into the writer as a stream of compact binary fields.
SetObject() [1/5]
void FCbPackage::SetObject (FCbObject InObject) inline
Set the root object without gathering attachments.
Parameters
InObject The root object, which will be cloned unless it is owned.
Definition at line 332 of file CompactBinaryPackage.h.
References MoveTemp(), and SetObject().
Referenced by FCbPackage(), FCbPackage(), FCbPackage(), FCbPackage(), SetObject(), SetObject(), SetObject(), and SetObject().
SetObject() [2/5]
void FCbPackage::SetObject (FCbObject InObject, const FIoHash & InObjectHash) inline
Set the root object without gathering attachments.
Parameters
InObject The root object, which will be cloned unless it is owned.
InObjectHash The hash of the object, which must match to avoid validation errors.
Definition at line 354 of file CompactBinaryPackage.h.
References MoveTemp(), and SetObject().
SetObject() [3/5]
void FCbPackage::SetObject (FCbObject InObject, const FIoHash & InObjectHash, FAttachmentResolver InResolver) inline
Set the root object and gather attachments using the resolver.
Parameters
InObject The root object, which will be cloned unless it is owned.
InObjectHash The hash of the object, which must match to avoid validation errors.
InResolver A function that is invoked for every reference and binary reference field.
Definition at line 366 of file CompactBinaryPackage.h.
References MoveTemp(), and SetObject().
SetObject() [4/5]
void FCbPackage::SetObject (FCbObject InObject, FAttachmentResolver InResolver) inline
Set the root object and gather attachments using the resolver.
Parameters
InObject The root object, which will be cloned unless it is owned.
InResolver A function that is invoked for every reference and binary reference field.
Definition at line 343 of file CompactBinaryPackage.h.
References MoveTemp(), and SetObject().
SetObject() [5/5]
void FCbPackage::SetObject (FCbObject Object, const FIoHash * Hash, FAttachmentResolver * Resolver) private
References Hash, and Object.
TryLoad() [1/2]
bool FCbPackage::TryLoad (FArchive & Ar, FCbBufferAllocator Allocator = FUniqueBuffer::Alloc)
Load the object and attachments from compact binary as written by Save.
The object and attachments will be individually loaded into owned buffers.
Parameters
Ar Archive to read the package from. An error state is set on failure.
Allocator Allocator for object and attachment buffers.
Note
Allocated buffers will be cloned if they are not owned.
References FUniqueBuffer::Alloc(), Allocator, and Ar.
TryLoad() [2/2]
bool FCbPackage::TryLoad (FCbFieldIterator & Fields)
Load the object and attachments from compact binary as written by Save.
The object and attachments reference the input iterator, if it is owned, and otherwise clones the object and attachments individually to make owned copies.
The iterator is advanced as object and attachment fields are consumed from it.
Field Documentation
Attachments
TArray<FCbAttachment> FCbPackage::Attachments private
Attachments ordered by their hash.
Definition at line 447 of file CompactBinaryPackage.h.
Referenced by GetAttachments(), and IsNull().
Object
FCbObject FCbPackage::Object private
Definition at line 448 of file CompactBinaryPackage.h.
Referenced by GatherAttachments(), GetObject(), IsNull(), and SetObject().
ObjectHash
FIoHash FCbPackage::ObjectHash private
Definition at line 449 of file CompactBinaryPackage.h.
Referenced by GetObjectHash().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Serialization/CompactBinaryPackage.h