Unreal Engine 5.6 C++ API: UE::SequenceNavigator::FNavigationToolItemDragDropOp Class Reference
UE::SequenceNavigator::FNavigationToolItemDragDropOp Class Reference
Drag Drop Operation for Navigation Tool Items.
#include "NavigationToolItemDragDropOp.h"
Public Member Functions
template<typename InDropHandlerType, typename = typename TEnableIf<TIsDerivedFrom<InDropHandlerType, FNavigationToolItemDropHandler>::Value>::Type, typename... InArgTypes>
void AddDropHandler (InArgTypes &&... InArgs)
TOptional< EItemDropZone > CanDrop (const EItemDropZone InDropZone, const FNavigationToolItemPtr &InTargetItem) const
DRAG_DROP_OPERATOR_TYPE (FNavigationToolItemDragDropOp, FDecoratedDragDropOp) static TSharedRef< FNavigationToolItemDragDropOp > New(const TArray< FNavigationToolItemPtr > &InItems
FReply Drop (EItemDropZone InDropZone, const FNavigationToolItemPtr &InTargetItem)
ENavigationToolDragDropActionType GetActionType () const
TConstArrayView< FNavigationToolItemPtr > GetItems () const
TSharedPtr< INavigationToolView > GetToolView () const
Public Member Functions inherited from FDecoratedDragDropOp
FDecoratedDragDropOp ()
virtual void Construct () override
Overridden to provide public access.
DRAG_DROP_OPERATOR_TYPE (FDecoratedDragDropOp, FDragDropOperation) FText CurrentHoverText
String to show as hover text.
virtual TSharedPtr< SWidget > GetDefaultDecorator () const override
The widget decorator to use.
FText GetDefaultHoverText () const
Gets the default hover text for this drag drop op.
FText GetHoverText () const
const FSlateBrush * GetIcon () const
FSlateColor GetIconColorAndOpacity () const
virtual void ResetToDefaultToolTip ()
Set the decorator back to the icon and text defined by the default.
void SetToolTip (const FText &Text, const FSlateBrush *Icon)
Set the text and icon for this tooltip.
void SetupDefaults ()
Setup some default values for the decorator.
Public Member Functions inherited from FDragDropOperation
FDragDropOperation ()
Default constructor.
virtual ~FDragDropOperation ()
Destructor.
virtual bool AffectedByPointerEvent (const FPointerEvent &PointerEvent)
Checks if this drag and drop operation is affected by a given PointerEvent.
virtual FVector2D GetDecoratorPosition () const
Gets the desired position of the decorator in absolute space.
virtual bool IsExternalOperation () const
Is this drag Drop operation going to interact with applications outside of Slate.
template<class TType>
bool IsOfType () const
Check if this drag and drop operation can cast safely to the specified template type.
virtual bool IsOfTypeImpl (const FString &Type) const
Checks whether this drag and drop operation can cast safely to the specified type.
virtual bool IsWindowlessOperation () const
virtual FCursorReply OnCursorQuery ()
Allows drag/drop operations to override the current cursor.
virtual void OnDragged (const class FDragDropEvent &DragDropEvent)
Called when the mouse was moved during a drag and drop operation.
virtual void OnDrop (bool bDropWasHandled, const FPointerEvent &MouseEvent)
Invoked when the drag and drop operation has ended.
void SetCursorOverride (TOptional< EMouseCursor::Type > CursorType)
Sets the cursor to override the drag drop operations cursor with so that a control can give temporary feedback, for example - a slashed circle telling the user 'this can't be dropped here'.
virtual void SetDecoratorVisibility (bool bVisible)
Alters the visibility of the window.
Public Member Functions inherited from TSharedFromThis< FDragDropOperation >
TSharedRef< FDragDropOperation, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FDragDropOperation, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Data Fields
const TSharedPtr< FNavigationToolView > ENavigationToolDragDropActionType InActionType
const TSharedPtr< FNavigationToolView > & InToolView
Data Fields inherited from FDecoratedDragDropOp
const FSlateBrush * CurrentIconBrush
Icon to be displayed.
FSlateColor CurrentIconColorAndOpacity
The color of the icon to be displayed.
Protected Member Functions
void Init (const TArray< FNavigationToolItemPtr > &InItems, const TSharedPtr< FNavigationToolView > &InToolView, ENavigationToolDragDropActionType InActionType)
Protected Member Functions inherited from FDragDropOperation
virtual TSharedPtr< FDragDropOperation > ConvertTo (const FString &TypeId)
void CreateCursorDecoratorWindow ()
Creates a window for the cursor decorator.
void DestroyCursorDecoratorWindow ()
Destroys the cursor decorator window.
Protected Member Functions inherited from TSharedFromThis< FDragDropOperation >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Protected Attributes
ENavigationToolDragDropActionType ActionType = ENavigationToolDragDropActionType::Move
TArray< TSharedRef< FNavigationToolItemDropHandler > > DropHandlers
TArray< FNavigationToolItemPtr > Items
TWeakPtr< INavigationToolView > WeakToolView
Protected Attributes inherited from FDecoratedDragDropOp
const FSlateBrush * DefaultHoverIcon
Default icon to be displayed.
FSlateColor DefaultHoverIconColorAndOpacity
Default color and opacity for the default icon to be displayed.
FText DefaultHoverText
Default string to show as hover text.
Protected Attributes inherited from FDragDropOperation
bool bCreateNewWindow
Create a new window for the decorator content.
TSharedPtr< SWindow > CursorDecoratorWindow
The window that owns the decorator widget.
TOptional< EMouseCursor::Type > MouseCursor
Mouse cursor used by the drag drop operation.
TOptional< EMouseCursor::Type > MouseCursorOverride
Mouse cursor used to temporarily replace the drag drops cursor.
Additional Inherited Members
Static Protected Member Functions inherited from TSharedFromThis< FDragDropOperation >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
Drag Drop Operation for Navigation Tool Items.
Customized behavior can be added in via the AddDropHandler function
Definition at line 18 of file NavigationToolItemDragDropOp.h.
Member Function Documentation
AddDropHandler()
template<typename InDropHandlerType, typename = typename TEnableIf<TIsDerivedFrom<InDropHandlerType, FNavigationToolItemDropHandler>::Value>::Type, typename... InArgTypes> void UE::SequenceNavigator::FNavigationToolItemDragDropOp::AddDropHandler (InArgTypes &&... InArgs) inline
Definition at line 45 of file NavigationToolItemDragDropOp.h.
References DropHandlers, Forward(), and MakeShared().
CanDrop()
TOptional< EItemDropZone > UE::SequenceNavigator::FNavigationToolItemDragDropOp::CanDrop (const EItemDropZone InDropZone, const FNavigationToolItemPtr & InTargetItem) const
DRAG_DROP_OPERATOR_TYPE()
UE::SequenceNavigator::FNavigationToolItemDragDropOp::DRAG_DROP_OPERATOR_TYPE (FNavigationToolItemDragDropOp , FDecoratedDragDropOp) const &
References FDecoratedDragDropOp::FDecoratedDragDropOp().
Drop()
FReply UE::SequenceNavigator::FNavigationToolItemDragDropOp::Drop (EItemDropZone InDropZone, const FNavigationToolItemPtr & InTargetItem)
GetActionType()
ENavigationToolDragDropActionType UE::SequenceNavigator::FNavigationToolItemDragDropOp::GetActionType () const inline
Definition at line 37 of file NavigationToolItemDragDropOp.h.
References ActionType.
GetItems()
TConstArrayView< FNavigationToolItemPtr > UE::SequenceNavigator::FNavigationToolItemDragDropOp::GetItems () const inline
Definition at line 32 of file NavigationToolItemDragDropOp.h.
References Items.
GetToolView()
TSharedPtr< INavigationToolView > UE::SequenceNavigator::FNavigationToolItemDragDropOp::GetToolView () const inline
Definition at line 27 of file NavigationToolItemDragDropOp.h.
References WeakToolView.
Init()
void UE::SequenceNavigator::FNavigationToolItemDragDropOp::Init (const TArray< FNavigationToolItemPtr > & InItems, const TSharedPtr< FNavigationToolView > & InToolView, ENavigationToolDragDropActionType InActionType) protected
References InActionType, and InToolView.
Field Documentation
ActionType
ENavigationToolDragDropActionType UE::SequenceNavigator::FNavigationToolItemDragDropOp::ActionType = ENavigationToolDragDropActionType::Move protected
Definition at line 67 of file NavigationToolItemDragDropOp.h.
Referenced by GetActionType().
DropHandlers
TArray<TSharedRef<FNavigationToolItemDropHandler> > UE::SequenceNavigator::FNavigationToolItemDragDropOp::DropHandlers protected
Definition at line 63 of file NavigationToolItemDragDropOp.h.
Referenced by AddDropHandler().
InActionType
const TSharedPtr<FNavigationToolView> ENavigationToolDragDropActionType UE::SequenceNavigator::FNavigationToolItemDragDropOp::InActionType
Definition at line 25 of file NavigationToolItemDragDropOp.h.
Referenced by Init().
InToolView
const TSharedPtr<FNavigationToolView>& UE::SequenceNavigator::FNavigationToolItemDragDropOp::InToolView
Definition at line 24 of file NavigationToolItemDragDropOp.h.
Referenced by Init().
Items
TArray<FNavigationToolItemPtr> UE::SequenceNavigator::FNavigationToolItemDragDropOp::Items protected
Definition at line 61 of file NavigationToolItemDragDropOp.h.
Referenced by GetItems().
WeakToolView
TWeakPtr<INavigationToolView> UE::SequenceNavigator::FNavigationToolItemDragDropOp::WeakToolView protected
Definition at line 65 of file NavigationToolItemDragDropOp.h.
Referenced by GetToolView().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Experimental/SequenceNavigator/Source/SequenceNavigator/Public/DragDropOps/NavigationToolItemDragDropOp.h