Unreal Engine 5.6 C++ API: FLevelSequenceActorSpawner Class Reference
FLevelSequenceActorSpawner Class Reference
#include "LevelSequenceActorSpawner.h"
Public Member Functions
virtual LEVELSEQUENCE_API void DestroySpawnedObject (UObject &Object) override
Destroy a specific previously spawned object.
virtual LEVELSEQUENCE_API UClass * GetSupportedTemplateType () const override
Returns the type of object we can spawn.
virtual LEVELSEQUENCE_API UObject * SpawnObject (FMovieSceneSpawnable &Spawnable, FMovieSceneSequenceIDRef TemplateID, TSharedRef< const UE::MovieScene::FSharedPlaybackState > SharedPlaybackState) override
Spawn an object for the specified GUID, from the specified sequence instance.
Public Member Functions inherited from IMovieSceneObjectSpawner
virtual ~IMovieSceneObjectSpawner ()
Virtual destructor.
virtual bool CanConvertSpawnableToPossessable (FMovieSceneSpawnable &Spawnable) const
Check whether the specified Spawnable can become a Possessable.
virtual bool CanSetupDefaultsForSpawnable (UObject *SpawnedObject) const
virtual TValueOrError< FNewSpawnable, FText > CreateNewSpawnableType (UObject &SourceObject, UMovieScene &OwnerMovieScene, UActorFactory *ActorFactory=nullptr)
Create a new spawnable type from the given source object.
virtual int32 GetSpawnerPriority () const
virtual bool IsEditor () const
virtual void SetupDefaultsForSpawnable (UObject *SpawnedObject, const FGuid &Guid, const TOptional< FTransformData > &TransformData, TSharedRef< ISequencer > Sequencer, USequencerSettings *Settings)
Setup a new spawnable object with some default tracks and keys.
Static Public Member Functions
static LEVELSEQUENCE_API TSharedRef< IMovieSceneObjectSpawner > CreateObjectSpawner ()
Detailed Description
Definition at line 7 of file LevelSequenceActorSpawner.h.
Member Function Documentation
CreateObjectSpawner()
LEVELSEQUENCE_API TSharedRef< IMovieSceneObjectSpawner > FLevelSequenceActorSpawner::CreateObjectSpawner () static
Referenced by FChaosCacheObjectSpawner::UE_DEPRECATED().
DestroySpawnedObject()
virtual LEVELSEQUENCE_API void FLevelSequenceActorSpawner::DestroySpawnedObject (UObject & Object) override virtual
Destroy a specific previously spawned object.
Parameters
Object The object to destroy
Implements IMovieSceneObjectSpawner.
References Object.
Referenced by FChaosCacheObjectSpawner::UE_DEPRECATED().
GetSupportedTemplateType()
virtual LEVELSEQUENCE_API UClass * FLevelSequenceActorSpawner::GetSupportedTemplateType () const override virtual
Returns the type of object we can spawn.
Returns
the class of the object we support for spawning
Implements IMovieSceneObjectSpawner.
Referenced by FChaosCacheObjectSpawner::UE_DEPRECATED().
SpawnObject()
virtual LEVELSEQUENCE_API UObject * FLevelSequenceActorSpawner::SpawnObject (FMovieSceneSpawnable & Spawnable, FMovieSceneSequenceIDRef TemplateID, TSharedRef< const UE::MovieScene::FSharedPlaybackState > SharedPlaybackState) override virtual
Spawn an object for the specified GUID, from the specified sequence instance.
Parameters
Object ID of the object to spawn
TemplateID Identifier for the current template we're evaluating
Player Movie scene player that is ultimately responsible for spawning the object
Returns
the spawned object, or nullptr on failure
Implements IMovieSceneObjectSpawner.
The documentation for this class was generated from the following file:
Runtime/LevelSequence/Public/LevelSequenceActorSpawner.h