Unreal Engine 5.6 C++ API: FDelegateGraphTask Class Reference
FDelegateGraphTask Class Reference
Task class for more full featured delegate based tasks.
#include "TaskGraphInterfaces.h"
Public Member Functions
FDelegateGraphTask (const FDelegate &InTaskDeletegate, const TStatId InStatId, ENamedThreads::Type InDesiredThread)
Task constructor.
DECLARE_DELEGATE_TwoParams (FDelegate, ENamedThreads::Type, const FGraphEventRef &)
void DoTask (ENamedThreads::Type CurrentThread, const FGraphEventRef &MyCompletionGraphEvent)
ENamedThreads::Type GetDesiredThread ()
Public Member Functions inherited from FCustomStatIDGraphTaskBase
FCustomStatIDGraphTaskBase (const TStatId &StatId)
Constructor.
FORCEINLINE TStatId GetStatId () const
Gets stat id for this task.
Static Public Member Functions
static FGraphEventRef CreateAndDispatchWhenReady (const FDelegate &InTaskDeletegate, const TStatId InStatId, const FGraphEventArray *InPrerequisites=NULL, ENamedThreads::Type InCurrentThreadIfKnown=ENamedThreads::AnyThread, ENamedThreads::Type InDesiredThread=ENamedThreads::AnyThread)
Create a task and dispatch it when the prerequisites are complete.
static FGraphEventRef CreateAndDispatchWhenReady (const FDelegate &InTaskDeletegate, const TStatId InStatId, const FGraphEventRef &InPrerequisite, ENamedThreads::Type InCurrentThreadIfKnown=ENamedThreads::AnyThread, ENamedThreads::Type InDesiredThread=ENamedThreads::AnyThread)
Create a task and dispatch it when the prerequisites are complete.
static ESubsequentsMode::Type GetSubsequentsMode ()
Data Fields
const ENamedThreads::Type DesiredThread
Thread to run delegate on.
FDelegate TaskDelegate
Delegate to fire when task runs.
Detailed Description
Task class for more full featured delegate based tasks.
Still less efficient than a custom task, but provides all of the args
Definition at line 1003 of file TaskGraphInterfaces.h.
Constructor & Destructor Documentation
FDelegateGraphTask()
FDelegateGraphTask::FDelegateGraphTask (const FDelegate & InTaskDeletegate, const TStatId InStatId, ENamedThreads::Type InDesiredThread) inline
Task constructor.
Parameters
InTaskDelegate - delegate to execute when the prerequisites are complete
InStatId - The stat id for this task.
InDesiredThread - Thread to run on
Definition at line 1031 of file TaskGraphInterfaces.h.
References FCustomStatIDGraphTaskBase::FCustomStatIDGraphTaskBase(), DesiredThread, and TaskDelegate.
Member Function Documentation
CreateAndDispatchWhenReady() [1/2]
FGraphEventRef FDelegateGraphTask::CreateAndDispatchWhenReady (const FDelegate & InTaskDeletegate, const TStatId InStatId, const FGraphEventArray * InPrerequisites = NULL, ENamedThreads::Type InCurrentThreadIfKnown = ENamedThreads::AnyThread, ENamedThreads::Type InDesiredThread = ENamedThreads::AnyThread) inline static
Create a task and dispatch it when the prerequisites are complete.
Parameters
InTaskDelegate - delegate to execute when the prerequisites are complete
InStatId - The stat id for this task.
InPrerequisites - Handles for prerequisites for this task, can be NULL if there are no prerequisites
InCurrentThreadIfKnown - This thread, if known
InDesiredThread - Thread to run on
Returns
completion handle for the new task
Definition at line 1047 of file TaskGraphInterfaces.h.
References ENamedThreads::AnyThread, TGraphTask< TTask >::FConstructor::ConstructAndDispatchWhenReady(), and TGraphTask< TTask >::CreateTask().
Referenced by CreateAndDispatchWhenReady().
CreateAndDispatchWhenReady() [2/2]
FGraphEventRef FDelegateGraphTask::CreateAndDispatchWhenReady (const FDelegate & InTaskDeletegate, const TStatId InStatId, const FGraphEventRef & InPrerequisite, ENamedThreads::Type InCurrentThreadIfKnown = ENamedThreads::AnyThread, ENamedThreads::Type InDesiredThread = ENamedThreads::AnyThread) inline static
Create a task and dispatch it when the prerequisites are complete.
Parameters
InTaskDelegate - delegate to execute when the prerequisites are complete
InStatId - The stat id for this task.
InPrerequisite - Handle for a single prerequisite for this task
InCurrentThreadIfKnown - This thread, if known
InDesiredThread - Thread to run on
Returns
completion handle for the new task
Definition at line 1060 of file TaskGraphInterfaces.h.
References ENamedThreads::AnyThread, check, CreateAndDispatchWhenReady(), and TRefCountPtr< ReferencedType >::GetReference().
DECLARE_DELEGATE_TwoParams()
FDelegateGraphTask::DECLARE_DELEGATE_TwoParams (FDelegate , ENamedThreads::Type , const FGraphEventRef &)
DoTask()
void FDelegateGraphTask::DoTask (ENamedThreads::Type CurrentThread, const FGraphEventRef & MyCompletionGraphEvent) inline
Definition at line 1021 of file TaskGraphInterfaces.h.
References TaskDelegate.
GetDesiredThread()
ENamedThreads::Type FDelegateGraphTask::GetDesiredThread () inline
Definition at line 1013 of file TaskGraphInterfaces.h.
References DesiredThread.
GetSubsequentsMode()
ESubsequentsMode::Type FDelegateGraphTask::GetSubsequentsMode () inline static
Definition at line 1017 of file TaskGraphInterfaces.h.
References ESubsequentsMode::TrackSubsequents.
Field Documentation
DesiredThread
const ENamedThreads::Type FDelegateGraphTask::DesiredThread
Thread to run delegate on.
Definition at line 1011 of file TaskGraphInterfaces.h.
Referenced by FDelegateGraphTask(), and GetDesiredThread().
TaskDelegate
FDelegate FDelegateGraphTask::TaskDelegate
Delegate to fire when task runs.
Definition at line 1009 of file TaskGraphInterfaces.h.
Referenced by FDelegateGraphTask(), and DoTask().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Async/TaskGraphInterfaces.h