Unreal Engine 5.6 C++ API: FSkeletalMeshLODModel Class Reference
FSkeletalMeshLODModel Class Reference
All data to define a certain LOD model for a skeletal mesh.
#include "SkeletalMeshLODModel.h"
Data Structures
struct FSkelMeshImportedMeshInfo
struct FThreadSafeBuildStringID
Public Member Functions
FSkeletalMeshLODModel ()
Constructor (default)
FSkeletalMeshLODModel (FSkeletalMeshLODModel &&InOther)
~FSkeletalMeshLODModel ()
bool DoSectionsUse16BitBoneIndex () const
void Empty ()
void GetClothMappingData (TArray< FMeshToMeshVertData > &MappingData, TArray< FClothBufferIndexMapping > &OutClothIndexMapping) const
Fill array with APEX cloth mapping data.
FString GetLODModelDeriveDataKey () const
Build a derive data key with the user section data (UserSectionsData) and the original bulk data.
int32 GetMaxBoneInfluences () const
void GetMeshDescription (const USkeletalMesh *InSkeletalMesh, const int32 InLODIndex, FMeshDescription &OutMeshDescription) const
Fills in a representation of this model into the given mesh description object.
void GetNonClothVertices (TArray< FSoftSkinVertex > &OutVertices) const
Similar to GetVertices but ignores vertices from clothing sections to avoid getting duplicate vertices from clothing sections if not needed.
int32 GetNumNonClothingVertices () const
TArray< uint32 > & GetRawPointIndices ()
Accessor for the RawPointIndice which is editor only data: array of the original point (wedge) indices for each of the vertices in a FSkeletalMeshLODModel.
const TArray< uint32 > & GetRawPointIndices () const
Accessor for the RawPointIndice which is editor only data: array of the original point (wedge) indices for each of the vertices in a FSkeletalMeshLODModel.
void GetResourceSizeEx (FResourceSizeEx &CumulativeResourceSize) const
void GetSectionFromVertexIndex (int32 InVertIndex, int32 &OutSectionIndex, int32 &OutVertIndex) const
Utility for finding the section that a particular vertex is in.
void GetVertices (TArray< FSoftSkinVertex > &Vertices) const
Fill array with vertex position and tangent data from skel mesh chunks.
bool HasClothData () const
int32 NumNonClothingSections () const
void Serialize (FArchive &Ar, UObject *Owner, int32 Idx)
Special serialize function passing the owning UObject along as required by FUnytpedBulkData serialization.
void SyncronizeUserSectionsDataArray (bool bResetNonUsedSection=false)
Make sure user section data is present for every original sections.
UE_DEPRECATED (5.0, "Please do not access this function anymore. This data is not use anymore.") FRawSkeletalMeshBulkData &GetRawSkeletalMeshBulkData_DEPRECATED()
void UpdateChunkedSectionInfo (const FString &SkeletalMeshName)
This function will update the chunked information for each section.
Static Public Member Functions
static void CopyStructure (FSkeletalMeshLODModel *Destination, const FSkeletalMeshLODModel *Source)
Copy one structure to the other, make sure all bulk data is unlock and the data can be read before copying.
static FSkeletalMeshLODModel * CreateCopy (const FSkeletalMeshLODModel *Other)
Create a new FSkeletalMeshLODModel on the heap.
static void DeclareCustomVersions (FArchive &Ar)
Data Fields
TArray< FBoneIndexType > ActiveBoneIndices
Bone hierarchy subset active for this LOD.
bool bIsBuildDataAvailable
bool bIsRawSkeletalMeshBulkDataEmpty
FThreadSafeBuildStringID BuildStringID
TArray< uint32 > IndexBuffer
Index buffer, covering all sections.
int32 MaxImportVertex
The max index in MeshToImportVertexMap, ie.
TArray< int32 > MeshToImportVertexMap
For each point in this LOD model that maps to its source point in the FMeshDescription that produced it.
uint32 NumTexCoords
The number of unique texture coordinate sets in this lod.
uint32 NumVertices
FString RawSkeletalMeshBulkDataID
This ID is use to create the DDC key, it must be set when we save the FRawSkeletalMeshBulkData.
TArray< FBoneIndexType > RequiredBones
Bones that should be updated when rendering this LOD.
TArray< FSkelMeshSection > Sections
Sections.
TMap< FName, FImportedSkinWeightProfileData > SkinWeightProfiles
Set of skin weight profile, identified by a FName which matches FSkinWeightProfileInfo.Name in the owning Skeletal Mesh.
TMap< int32, FSkelMeshSourceSectionUserData > UserSectionsData
TMap< FName, FSkeletalMeshModelVertexAttribute > VertexAttributes
Set of vertex attributes identified by an FName.
Private Member Functions
FSkeletalMeshLODModel (const FSkeletalMeshLODModel &Other)=delete
FSkeletalMeshLODModel & operator= (const FSkeletalMeshLODModel &Other)=default
Private Attributes
FCriticalSection * BulkDataReadMutex
TArray< FSkelMeshImportedMeshInfo > ImportedMeshInfos
FWordBulkData LegacyRawPointIndices_DEPRECATED
TArray< uint32 > RawPointIndices2
For each point in this LOD model that maps to its source point in FSkeletalMeshImportData.
FIntBulkData RawPointIndices_DEPRECATED
FRawSkeletalMeshBulkData RawSkeletalMeshBulkData_DEPRECATED
Friends
struct FSkeletalMeshSourceModel
FArchive & operator<< (FArchive &Ar, FSkelMeshImportedMeshInfo &Info)
Detailed Description
All data to define a certain LOD model for a skeletal mesh.
Definition at line 293 of file SkeletalMeshLODModel.h.
Constructor & Destructor Documentation
FSkeletalMeshLODModel() [1/3]
FSkeletalMeshLODModel::FSkeletalMeshLODModel () inline
Constructor (default)
Definition at line 365 of file SkeletalMeshLODModel.h.
References bIsBuildDataAvailable, bIsRawSkeletalMeshBulkDataEmpty, BuildStringID, BulkDataReadMutex, MaxImportVertex, NumTexCoords, NumVertices, RawSkeletalMeshBulkDataID, TEXT, and FGuid::ToString().
Referenced by FSkeletalMeshLODModel(), FSkeletalMeshLODModel(), CopyStructure(), CreateCopy(), Empty(), and operator=().
~FSkeletalMeshLODModel()
FSkeletalMeshLODModel::~FSkeletalMeshLODModel () inline
Definition at line 380 of file SkeletalMeshLODModel.h.
References BulkDataReadMutex.
FSkeletalMeshLODModel() [2/3]
FSkeletalMeshLODModel::FSkeletalMeshLODModel (FSkeletalMeshLODModel && InOther) inline
Definition at line 390 of file SkeletalMeshLODModel.h.
References FSkeletalMeshLODModel(), ActiveBoneIndices, bIsBuildDataAvailable, bIsRawSkeletalMeshBulkDataEmpty, BuildStringID, BulkDataReadMutex, ImportedMeshInfos, IndexBuffer, MaxImportVertex, MeshToImportVertexMap, MoveTemp(), NumTexCoords, NumVertices, RawPointIndices2, RawSkeletalMeshBulkDataID, RequiredBones, Sections, SkinWeightProfiles, UserSectionsData, and VertexAttributes.
FSkeletalMeshLODModel() [3/3]
FSkeletalMeshLODModel::FSkeletalMeshLODModel (const FSkeletalMeshLODModel & Other) private delete
References FSkeletalMeshLODModel(), and Other.
Member Function Documentation
CopyStructure()
void FSkeletalMeshLODModel::CopyStructure (FSkeletalMeshLODModel * Destination, const FSkeletalMeshLODModel * Source) static
Copy one structure to the other, make sure all bulk data is unlock and the data can be read before copying.
It also use a private mutex to make sure it's thread safe to copy the same source multiple time in multiple thread.
References FSkeletalMeshLODModel(), and Source.
Referenced by CreateCopy().
CreateCopy()
FSkeletalMeshLODModel * FSkeletalMeshLODModel::CreateCopy (const FSkeletalMeshLODModel * Other) inline static
Create a new FSkeletalMeshLODModel on the heap.
Copy data from the "FSkeletalMeshLODModel* Other" to the just created LODModel return the heap allocated LODModel. This function is thread safe since its use the thread safe CopyStructure function to copy the data from Other.
Definition at line 618 of file SkeletalMeshLODModel.h.
References FSkeletalMeshLODModel(), CopyStructure(), and Other.
DeclareCustomVersions()
void FSkeletalMeshLODModel::DeclareCustomVersions (FArchive & Ar) static
References Ar.
DoSectionsUse16BitBoneIndex()
bool FSkeletalMeshLODModel::DoSectionsUse16BitBoneIndex () const
Empty()
void FSkeletalMeshLODModel::Empty () inline
Definition at line 414 of file SkeletalMeshLODModel.h.
References FSkeletalMeshLODModel(), and BulkDataReadMutex.
GetClothMappingData()
void FSkeletalMeshLODModel::GetClothMappingData (TArray< FMeshToMeshVertData > & MappingData, TArray< FClothBufferIndexMapping > & OutClothIndexMapping) const
Fill array with APEX cloth mapping data.
Parameters
MappingData Array to fill.
GetLODModelDeriveDataKey()
FString FSkeletalMeshLODModel::GetLODModelDeriveDataKey () const
Build a derive data key with the user section data (UserSectionsData) and the original bulk data.
GetMaxBoneInfluences()
int32 FSkeletalMeshLODModel::GetMaxBoneInfluences () const
GetMeshDescription()
void FSkeletalMeshLODModel::GetMeshDescription (const USkeletalMesh * InSkeletalMesh, const int32 InLODIndex, FMeshDescription & OutMeshDescription) const
Fills in a representation of this model into the given mesh description object.
Existing mesh description data is emptied.
GetNonClothVertices()
void FSkeletalMeshLODModel::GetNonClothVertices (TArray< FSoftSkinVertex > & OutVertices) const
Similar to GetVertices but ignores vertices from clothing sections to avoid getting duplicate vertices from clothing sections if not needed.
Parameters
OutVertices Array to fill
GetNumNonClothingVertices()
int32 FSkeletalMeshLODModel::GetNumNonClothingVertices () const
GetRawPointIndices() [1/2]
TArray< uint32 > & FSkeletalMeshLODModel::GetRawPointIndices () inline
Accessor for the RawPointIndice which is editor only data: array of the original point (wedge) indices for each of the vertices in a FSkeletalMeshLODModel.
Definition at line 348 of file SkeletalMeshLODModel.h.
References RawPointIndices2.
GetRawPointIndices() [2/2]
const TArray< uint32 > & FSkeletalMeshLODModel::GetRawPointIndices () const inline
Accessor for the RawPointIndice which is editor only data: array of the original point (wedge) indices for each of the vertices in a FSkeletalMeshLODModel.
Definition at line 342 of file SkeletalMeshLODModel.h.
References RawPointIndices2.
GetResourceSizeEx()
void FSkeletalMeshLODModel::GetResourceSizeEx (FResourceSizeEx & CumulativeResourceSize) const
GetSectionFromVertexIndex()
void FSkeletalMeshLODModel::GetSectionFromVertexIndex (int32 InVertIndex, int32 & OutSectionIndex, int32 & OutVertIndex) const
Utility for finding the section that a particular vertex is in.
GetVertices()
void FSkeletalMeshLODModel::GetVertices (TArray< FSoftSkinVertex > & Vertices) const
Fill array with vertex position and tangent data from skel mesh chunks.
Parameters
Vertices Array to fill.
HasClothData()
bool FSkeletalMeshLODModel::HasClothData () const
Returns
true if any chunks have cloth data.
NumNonClothingSections()
int32 FSkeletalMeshLODModel::NumNonClothingSections () const
operator=()
FSkeletalMeshLODModel & FSkeletalMeshLODModel::operator= (const FSkeletalMeshLODModel & Other) private default
References FSkeletalMeshLODModel(), and Other.
Serialize()
void FSkeletalMeshLODModel::Serialize (FArchive & Ar, UObject * Owner, int32 Idx)
Special serialize function passing the owning UObject along as required by FUnytpedBulkData serialization.
Parameters
Ar Archive to serialize with
Owner UObject this structure is serialized within
Idx Index of current array entry being serialized
References Ar, and Owner.
SyncronizeUserSectionsDataArray()
void FSkeletalMeshLODModel::SyncronizeUserSectionsDataArray (bool bResetNonUsedSection = false)
Make sure user section data is present for every original sections.
UE_DEPRECATED()
FSkeletalMeshLODModel::UE_DEPRECATED (5. 0, "Please do not access this function anymore. This data is not use anymore.") & inline
Definition at line 353 of file SkeletalMeshLODModel.h.
References RawSkeletalMeshBulkData_DEPRECATED.
UpdateChunkedSectionInfo()
void FSkeletalMeshLODModel::UpdateChunkedSectionInfo (const FString & SkeletalMeshName)
This function will update the chunked information for each section.
Only old data before the skeletal mesh build refactor should need to call this function.
Friends And Related Symbol Documentation
FSkeletalMeshSourceModel
friend struct FSkeletalMeshSourceModel friend
Definition at line 422 of file SkeletalMeshLODModel.h.
References FSkeletalMeshSourceModel.
Referenced by FSkeletalMeshSourceModel.
operator<<
FArchive & operator<< (FArchive & Ar, FSkelMeshImportedMeshInfo & Info) friend
Definition at line 437 of file SkeletalMeshLODModel.h.
References Ar, and Info.
Field Documentation
ActiveBoneIndices
TArray<FBoneIndexType> FSkeletalMeshLODModel::ActiveBoneIndices
Bone hierarchy subset active for this LOD.
This is a map between the bones index of this LOD (as used by the vertex structs) and the bone index in the reference skeleton of this SkeletalMesh.
Definition at line 318 of file SkeletalMeshLODModel.h.
Referenced by FSkeletalMeshLODModel().
bIsBuildDataAvailable
bool FSkeletalMeshLODModel::bIsBuildDataAvailable
Definition at line 361 of file SkeletalMeshLODModel.h.
Referenced by FSkeletalMeshLODModel(), and FSkeletalMeshLODModel().
bIsRawSkeletalMeshBulkDataEmpty
bool FSkeletalMeshLODModel::bIsRawSkeletalMeshBulkDataEmpty
Definition at line 362 of file SkeletalMeshLODModel.h.
Referenced by FSkeletalMeshLODModel(), and FSkeletalMeshLODModel().
BuildStringID
FThreadSafeBuildStringID FSkeletalMeshLODModel::BuildStringID mutable
Definition at line 594 of file SkeletalMeshLODModel.h.
Referenced by FSkeletalMeshLODModel(), and FSkeletalMeshLODModel().
BulkDataReadMutex
FCriticalSection* FSkeletalMeshLODModel::BulkDataReadMutex private
Definition at line 458 of file SkeletalMeshLODModel.h.
Referenced by FSkeletalMeshLODModel(), FSkeletalMeshLODModel(), ~FSkeletalMeshLODModel(), and Empty().
ImportedMeshInfos
TArray<FSkelMeshImportedMeshInfo> FSkeletalMeshLODModel::ImportedMeshInfos private
Definition at line 443 of file SkeletalMeshLODModel.h.
Referenced by FSkeletalMeshLODModel().
IndexBuffer
TArray<uint32> FSkeletalMeshLODModel::IndexBuffer
Index buffer, covering all sections.
Definition at line 312 of file SkeletalMeshLODModel.h.
Referenced by FSkeletalMeshLODModel().
LegacyRawPointIndices_DEPRECATED
FWordBulkData FSkeletalMeshLODModel::LegacyRawPointIndices_DEPRECATED private
Definition at line 452 of file SkeletalMeshLODModel.h.
MaxImportVertex
int32 FSkeletalMeshLODModel::MaxImportVertex
The max index in MeshToImportVertexMap, ie.
the number of imported (raw) verts.
Definition at line 339 of file SkeletalMeshLODModel.h.
Referenced by FSkeletalMeshLODModel(), and FSkeletalMeshLODModel().
MeshToImportVertexMap
TArray<int32> FSkeletalMeshLODModel::MeshToImportVertexMap
For each point in this LOD model that maps to its source point in the FMeshDescription that produced it.
I.e. a linear map mapping the result of GetVertices() to its matching FVertexId entry in the original FMeshDescription.
Definition at line 336 of file SkeletalMeshLODModel.h.
Referenced by FSkeletalMeshLODModel().
NumTexCoords
uint32 FSkeletalMeshLODModel::NumTexCoords
The number of unique texture coordinate sets in this lod.
Definition at line 309 of file SkeletalMeshLODModel.h.
Referenced by FSkeletalMeshLODModel(), and FSkeletalMeshLODModel().
NumVertices
uint32 FSkeletalMeshLODModel::NumVertices
Definition at line 307 of file SkeletalMeshLODModel.h.
Referenced by FSkeletalMeshLODModel(), and FSkeletalMeshLODModel().
RawPointIndices2
TArray<uint32> FSkeletalMeshLODModel::RawPointIndices2 private
For each point in this LOD model that maps to its source point in FSkeletalMeshImportData.
I.e. a linear map mapping the result of GetVertices() to its matching FSkeletalMeshImportData::Points entry. This can be used to map back to alternative skin weight profiles and vertex attributes on the import data.
Definition at line 449 of file SkeletalMeshLODModel.h.
Referenced by FSkeletalMeshLODModel(), GetRawPointIndices(), and GetRawPointIndices().
RawPointIndices_DEPRECATED
FIntBulkData FSkeletalMeshLODModel::RawPointIndices_DEPRECATED private
Definition at line 451 of file SkeletalMeshLODModel.h.
RawSkeletalMeshBulkData_DEPRECATED
FRawSkeletalMeshBulkData FSkeletalMeshLODModel::RawSkeletalMeshBulkData_DEPRECATED private
Definition at line 453 of file SkeletalMeshLODModel.h.
Referenced by UE_DEPRECATED().
RawSkeletalMeshBulkDataID
FString FSkeletalMeshLODModel::RawSkeletalMeshBulkDataID
This ID is use to create the DDC key, it must be set when we save the FRawSkeletalMeshBulkData.
Definition at line 360 of file SkeletalMeshLODModel.h.
Referenced by FSkeletalMeshLODModel(), and FSkeletalMeshLODModel().
RequiredBones
TArray<FBoneIndexType> FSkeletalMeshLODModel::RequiredBones
Bones that should be updated when rendering this LOD.
This may include bones that are not required for rendering. All parents for bones in this array should be present as well - that is, a complete path from the root to each bone. For bone LOD code to work, this array must be in strictly increasing order, to allow easy merging of other required bones.
Definition at line 325 of file SkeletalMeshLODModel.h.
Referenced by FSkeletalMeshLODModel().
Sections
TArray<FSkelMeshSection> FSkeletalMeshLODModel::Sections
Sections.
Definition at line 297 of file SkeletalMeshLODModel.h.
Referenced by FSkeletalMeshLODModel().
SkinWeightProfiles
TMap<FName, FImportedSkinWeightProfileData> FSkeletalMeshLODModel::SkinWeightProfiles
Set of skin weight profile, identified by a FName which matches FSkinWeightProfileInfo.Name in the owning Skeletal Mesh.
Definition at line 328 of file SkeletalMeshLODModel.h.
Referenced by FSkeletalMeshLODModel().
UserSectionsData
TMap<int32, FSkelMeshSourceSectionUserData> FSkeletalMeshLODModel::UserSectionsData
Definition at line 305 of file SkeletalMeshLODModel.h.
Referenced by FSkeletalMeshLODModel().
VertexAttributes
TMap<FName, FSkeletalMeshModelVertexAttribute> FSkeletalMeshLODModel::VertexAttributes
Set of vertex attributes identified by an FName.
Definition at line 331 of file SkeletalMeshLODModel.h.
Referenced by FSkeletalMeshLODModel().
The documentation for this class was generated from the following file:
Runtime/Engine/Public/Rendering/SkeletalMeshLODModel.h