Unreal Engine 5.6 C++ API: FQuatFloat96NoW Class Reference
FQuatFloat96NoW Class Reference
#include "AnimationCompression.h"
Public Member Functions
FQuatFloat96NoW ()
FQuatFloat96NoW (const FQuat4f &Quat)
FQuatFloat96NoW (float InX, float InY, float InZ)
void FromQuat (const FQuat4f &Quat)
void ToQuat (FQuat4f &Out) const
Static Public Member Functions
template<bool bIsDataAligned = true>
static FQuat4f ToQuat (const float *Values)
Data Fields
union {
struct {
float X
float Y
float Z
}
};
Friends
FArchive & operator<< (FArchive &Ar, FQuatFloat96NoW &Quat)
Detailed Description
Definition at line 219 of file AnimationCompression.h.
Constructor & Destructor Documentation
FQuatFloat96NoW() [1/3]
FQuatFloat96NoW::FQuatFloat96NoW () inline
Definition at line 235 of file AnimationCompression.h.
References FQuatFloat96NoW().
Referenced by FQuatFloat96NoW(), and operator<<.
FQuatFloat96NoW() [2/3]
FQuatFloat96NoW::FQuatFloat96NoW (const FQuat4f & Quat) inline explicit
Definition at line 238 of file AnimationCompression.h.
References FromQuat(), and Quat.
FQuatFloat96NoW() [3/3]
FQuatFloat96NoW::FQuatFloat96NoW (float InX, float InY, float InZ) inline
Definition at line 243 of file AnimationCompression.h.
References X, Y, and Z.
Member Function Documentation
FromQuat()
void FQuatFloat96NoW::FromQuat (const FQuat4f & Quat) inline
Definition at line 249 of file AnimationCompression.h.
References UE::Math::TQuat< T >::Normalize(), Quat, UE_REAL_TO_FLOAT, UE::Math::TQuat< T >::W, X, UE::Math::TQuat< T >::X, Y, UE::Math::TQuat< T >::Y, Z, and UE::Math::TQuat< T >::Z.
Referenced by FQuatFloat96NoW().
ToQuat() [1/2]
template<bool bIsDataAligned = true> FQuat4f FQuatFloat96NoW::ToQuat (const float * Values) inline static
Definition at line 266 of file AnimationCompression.h.
References AnimationCompressionUtils::UnalignedRead(), X, Y, and Z.
Referenced by DecompressRotation(), FAnimationCompression_PerTrackUtils::DecompressRotation(), and ToQuat().
ToQuat() [2/2]
void FQuatFloat96NoW::ToQuat (FQuat4f & Out) const inline
Definition at line 276 of file AnimationCompression.h.
References PRAGMA_DISABLE_DEPRECATION_WARNINGS, PRAGMA_ENABLE_DEPRECATION_WARNINGS, and ToQuat().
Friends And Related Symbol Documentation
operator<<
FArchive & operator<< (FArchive & Ar, FQuatFloat96NoW & Quat) friend
Definition at line 283 of file AnimationCompression.h.
References FQuatFloat96NoW(), Ar, and Quat.
Field Documentation
[union]
union { ... } FQuatFloat96NoW
X
float FQuatFloat96NoW::X
Definition at line 226 of file AnimationCompression.h.
Referenced by FQuatFloat96NoW(), FromQuat(), and ToQuat().
Y
float FQuatFloat96NoW::Y
Definition at line 227 of file AnimationCompression.h.
Referenced by FQuatFloat96NoW(), FromQuat(), and ToQuat().
Z
float FQuatFloat96NoW::Z
Definition at line 228 of file AnimationCompression.h.
Referenced by FQuatFloat96NoW(), FromQuat(), and ToQuat().
The documentation for this class was generated from the following file:
Runtime/Engine/Public/AnimationCompression.h