Unreal Engine 5.6 C++ API: TraceServices::TPagedArrayIterator< ItemType, PageType > Class Template Reference
TraceServices::TPagedArrayIterator< ItemType, PageType > Class Template Reference
#include "PagedArray.h"
Public Member Functions
TPagedArrayIterator ()
TPagedArrayIterator (const TPagedArray< ItemType, PageType > &InOuter, uint64 InItemIndex)
const ItemType * GetCurrentItem () const
uint64 GetCurrentItemIndex () const
const PageType * GetCurrentPage () const
uint64 GetCurrentPageIndex () const
const ItemType * NextItem ()
const PageType * NextPage ()
operator bool () const
const ItemType & operator* () const
TPagedArrayIterator & operator++ ()
TPagedArrayIterator operator++ (int)
TPagedArrayIterator & operator-- ()
TPagedArrayIterator operator-- (int)
const ItemType * operator-> () const
const ItemType * PrevItem ()
const PageType * PrevPage ()
const PageType * SetCurrentPage (uint64 PageIndex)
const ItemType * SetPosition (uint64 InItemIndex)
Private Member Functions
void DebugCheckState ()
void OnCurrentPageChanged ()
void SetPositionInternal (uint64 InItemIndex)
Private Attributes
const ItemType * CurrentItem = nullptr
uint64 CurrentItemIndex = 0
const ItemType * CurrentPageFirstItem = nullptr
uint64 CurrentPageIndex = 0
const ItemType * CurrentPageLastItem = nullptr
const TPagedArray< ItemType, PageType > * Outer = nullptr
Friends
FORCEINLINE friend bool operator!= (const TPagedArrayIterator &Lhs, const TPagedArrayIterator &Rhs)
Detailed Description
template<typename ItemType, typename PageType>
class TraceServices::TPagedArrayIterator< ItemType, PageType >
Definition at line 68 of file PagedArray.h.
Constructor & Destructor Documentation
TPagedArrayIterator() [1/2]
template<typename ItemType, typename PageType> TraceServices::TPagedArrayIterator< ItemType, PageType >::TPagedArrayIterator () inline
Definition at line 71 of file PagedArray.h.
TPagedArrayIterator() [2/2]
template<typename ItemType, typename PageType> TraceServices::TPagedArrayIterator< ItemType, PageType >::TPagedArrayIterator (const TPagedArray< ItemType, PageType > & InOuter, uint64 InItemIndex) inline
Definition at line 75 of file PagedArray.h.
Member Function Documentation
DebugCheckState()
template<typename ItemType, typename PageType> void TraceServices::TPagedArrayIterator< ItemType, PageType >::DebugCheckState () inline private
Definition at line 365 of file PagedArray.h.
Referenced by TraceServices::TPagedArrayIterator< InItemType, InPageType >::TPagedArrayIterator(), TraceServices::TPagedArrayIterator< InItemType, InPageType >::NextItem(), TraceServices::TPagedArrayIterator< InItemType, InPageType >::NextPage(), TraceServices::TPagedArrayIterator< InItemType, InPageType >::PrevItem(), TraceServices::TPagedArrayIterator< InItemType, InPageType >::PrevPage(), TraceServices::TPagedArrayIterator< InItemType, InPageType >::SetCurrentPage(), and TraceServices::TPagedArrayIterator< InItemType, InPageType >::SetPosition().
GetCurrentItem()
template<typename ItemType, typename PageType> const ItemType * TraceServices::TPagedArrayIterator< ItemType, PageType >::GetCurrentItem () const inline
Definition at line 177 of file PagedArray.h.
GetCurrentItemIndex()
template<typename ItemType, typename PageType> uint64 TraceServices::TPagedArrayIterator< ItemType, PageType >::GetCurrentItemIndex () const inline
Definition at line 172 of file PagedArray.h.
GetCurrentPage()
template<typename ItemType, typename PageType> const PageType * TraceServices::TPagedArrayIterator< ItemType, PageType >::GetCurrentPage () const inline
Definition at line 95 of file PagedArray.h.
Referenced by TraceServices::TMonotonicTimeline< InEventType, SettingsType >::FindEventUsingPageInitialStack(), TraceServices::TPagedArrayIterator< InItemType, InPageType >::NextPage(), and TraceServices::TPagedArrayIterator< InItemType, InPageType >::PrevPage().
GetCurrentPageIndex()
template<typename ItemType, typename PageType> uint64 TraceServices::TPagedArrayIterator< ItemType, PageType >::GetCurrentPageIndex () const inline
Definition at line 90 of file PagedArray.h.
NextItem()
template<typename ItemType, typename PageType> const ItemType * TraceServices::TPagedArrayIterator< ItemType, PageType >::NextItem () inline
Definition at line 210 of file PagedArray.h.
Referenced by TraceServices::TPagedArrayIterator< InItemType, InPageType >::operator++(), and TraceServices::TPagedArrayIterator< InItemType, InPageType >::operator++().
NextPage()
template<typename ItemType, typename PageType> const PageType * TraceServices::TPagedArrayIterator< ItemType, PageType >::NextPage () inline
Definition at line 149 of file PagedArray.h.
Referenced by TraceServices::TMonotonicTimeline< InEventType, SettingsType >::FindEventUsingPageInitialStack(), and TraceServices::TPagedArrayIterator< InItemType, InPageType >::NextItem().
OnCurrentPageChanged()
template<typename ItemType, typename PageType> void TraceServices::TPagedArrayIterator< ItemType, PageType >::OnCurrentPageChanged () inline private
Definition at line 275 of file PagedArray.h.
Referenced by TraceServices::TPagedArrayIterator< InItemType, InPageType >::NextPage(), TraceServices::TPagedArrayIterator< InItemType, InPageType >::PrevPage(), TraceServices::TPagedArrayIterator< InItemType, InPageType >::SetCurrentPage(), and TraceServices::TPagedArrayIterator< InItemType, InPageType >::SetPositionInternal().
operator bool()
template<typename ItemType, typename PageType> TraceServices::TPagedArrayIterator< ItemType, PageType >::operator bool () const inline explicit
Definition at line 243 of file PagedArray.h.
operator*()
template<typename ItemType, typename PageType> const ItemType & TraceServices::TPagedArrayIterator< ItemType, PageType >::operator* () const inline
Definition at line 233 of file PagedArray.h.
operator++() [1/2]
template<typename ItemType, typename PageType> TPagedArrayIterator & TraceServices::TPagedArrayIterator< ItemType, PageType >::operator++ () inline
Definition at line 248 of file PagedArray.h.
operator++() [2/2]
template<typename ItemType, typename PageType> TPagedArrayIterator TraceServices::TPagedArrayIterator< ItemType, PageType >::operator++ (int) inline
Definition at line 254 of file PagedArray.h.
operator--() [1/2]
template<typename ItemType, typename PageType> TPagedArrayIterator & TraceServices::TPagedArrayIterator< ItemType, PageType >::operator-- () inline
Definition at line 261 of file PagedArray.h.
operator--() [2/2]
template<typename ItemType, typename PageType> TPagedArrayIterator TraceServices::TPagedArrayIterator< ItemType, PageType >::operator-- (int) inline
Definition at line 267 of file PagedArray.h.
operator->()
template<typename ItemType, typename PageType> const ItemType * TraceServices::TPagedArrayIterator< ItemType, PageType >::operator-> () const inline
Definition at line 238 of file PagedArray.h.
PrevItem()
template<typename ItemType, typename PageType> const ItemType * TraceServices::TPagedArrayIterator< ItemType, PageType >::PrevItem () inline
Definition at line 190 of file PagedArray.h.
Referenced by TraceServices::PagedArrayAlgoImpl::LowerBoundInternal(), TraceServices::TPagedArrayIterator< InItemType, InPageType >::operator--(), TraceServices::TPagedArrayIterator< InItemType, InPageType >::operator--(), and TraceServices::PagedArrayAlgoImpl::UpperBoundInternal().
PrevPage()
template<typename ItemType, typename PageType> const PageType * TraceServices::TPagedArrayIterator< ItemType, PageType >::PrevPage () inline
Definition at line 129 of file PagedArray.h.
Referenced by TraceServices::TPagedArrayIterator< InItemType, InPageType >::PrevItem().
SetCurrentPage()
template<typename ItemType, typename PageType> const PageType * TraceServices::TPagedArrayIterator< ItemType, PageType >::SetCurrentPage (uint64 PageIndex) inline
Definition at line 100 of file PagedArray.h.
SetPosition()
template<typename ItemType, typename PageType> const ItemType * TraceServices::TPagedArrayIterator< ItemType, PageType >::SetPosition (uint64 InItemIndex) inline
Definition at line 182 of file PagedArray.h.
SetPositionInternal()
template<typename ItemType, typename PageType> void TraceServices::TPagedArrayIterator< ItemType, PageType >::SetPositionInternal (uint64 InItemIndex) inline private
Definition at line 289 of file PagedArray.h.
Referenced by TraceServices::TPagedArrayIterator< InItemType, InPageType >::TPagedArrayIterator(), and TraceServices::TPagedArrayIterator< InItemType, InPageType >::SetPosition().
Friends And Related Symbol Documentation
operator!=
template<typename ItemType, typename PageType> FORCEINLINE friend bool operator!= (const TPagedArrayIterator< ItemType, PageType > & Lhs, const TPagedArrayIterator< ItemType, PageType > & Rhs) friend
Definition at line 313 of file PagedArray.h.
Field Documentation
CurrentItem
template<typename ItemType, typename PageType> const ItemType* TraceServices::TPagedArrayIterator< ItemType, PageType >::CurrentItem = nullptr private
Definition at line 376 of file PagedArray.h.
CurrentItemIndex
template<typename ItemType, typename PageType> uint64 TraceServices::TPagedArrayIterator< ItemType, PageType >::CurrentItemIndex = 0 private
Definition at line 375 of file PagedArray.h.
Referenced by TraceServices::TPagedArrayIterator< InItemType, InPageType >::operator!=.
CurrentPageFirstItem
template<typename ItemType, typename PageType> const ItemType* TraceServices::TPagedArrayIterator< ItemType, PageType >::CurrentPageFirstItem = nullptr private
Definition at line 373 of file PagedArray.h.
CurrentPageIndex
template<typename ItemType, typename PageType> uint64 TraceServices::TPagedArrayIterator< ItemType, PageType >::CurrentPageIndex = 0 private
Definition at line 372 of file PagedArray.h.
Referenced by TraceServices::TPagedArrayIterator< InItemType, InPageType >::SetPositionInternal().
CurrentPageLastItem
template<typename ItemType, typename PageType> const ItemType* TraceServices::TPagedArrayIterator< ItemType, PageType >::CurrentPageLastItem = nullptr private
Definition at line 374 of file PagedArray.h.
Outer
template<typename ItemType, typename PageType> const TPagedArray<ItemType, PageType>* TraceServices::TPagedArrayIterator< ItemType, PageType >::Outer = nullptr private
Definition at line 371 of file PagedArray.h.
Referenced by TraceServices::TPagedArrayIterator< InItemType, InPageType >::operator!=.
The documentation for this class was generated from the following file:
Developer/TraceServices/Public/Common/PagedArray.h