Unreal Engine 5.6 C++ API: SharedPointerInternals::FSharedReferencer< Mode > Class Template Reference
SharedPointerInternals::FSharedReferencer< Mode > Class Template Reference
FSharedReferencer is a wrapper around a pointer to a reference controller that is used by either a TSharedRef or a TSharedPtr to keep track of a referenced object's lifetime.
#include "SharedPointerInternals.h"
Public Member Functions
FORCEINLINE FSharedReferencer ()
Constructor for an empty shared referencer object.
FORCEINLINE FSharedReferencer (FSharedReferencer &&InSharedReference)
Move constructor creates no new references.
FORCEINLINE FSharedReferencer (FSharedReferencer const &InSharedReference)
Copy constructor creates a new reference to the existing object.
FSharedReferencer (FWeakReferencer< Mode > &&InWeakReference)
Creates a shared referencer object from a weak referencer object.
FSharedReferencer (FWeakReferencer< Mode > const &InWeakReference)
Creates a shared referencer object from a weak referencer object.
FSharedReferencer (TReferenceControllerBase< Mode > *InReferenceController)
Constructor that counts a single reference to the specified object.
FORCEINLINE ~FSharedReferencer ()
Destructor.
FORCEINLINE const int32 GetSharedReferenceCount () const
Returns the number of shared references to this object (including this reference.)
FORCEINLINE const bool IsUnique () const
Returns true if this is the only shared reference to this object.
FORCEINLINE const bool IsValid () const
Tests to see whether or not this shared counter contains a valid reference.
FSharedReferencer & operator= (FSharedReferencer &&InSharedReference)
Move assignment operator adds no references to the assigned object.
FSharedReferencer & operator= (FSharedReferencer const &InSharedReference)
Assignment operator adds a reference to the assigned object.
Private Attributes
TReferenceControllerBase< Mode > * ReferenceController
Pointer to the reference controller for the object a shared reference/pointer is referencing.
Friends
template<ESPMode OtherMode>
class FWeakReferencer
Detailed Description
template<ESPMode Mode>
class SharedPointerInternals::FSharedReferencer< Mode >
FSharedReferencer is a wrapper around a pointer to a reference controller that is used by either a TSharedRef or a TSharedPtr to keep track of a referenced object's lifetime.
Definition at line 523 of file SharedPointerInternals.h.
Constructor & Destructor Documentation
FSharedReferencer() [1/6]
template<ESPMode Mode> FORCEINLINE SharedPointerInternals::FSharedReferencer< Mode >::FSharedReferencer () inline
Constructor for an empty shared referencer object.
Definition at line 528 of file SharedPointerInternals.h.
References FORCEINLINE, and ReferenceController.
Referenced by FSharedReferencer(), FSharedReferencer(), operator=(), and operator=().
FSharedReferencer() [2/6]
template<ESPMode Mode> SharedPointerInternals::FSharedReferencer< Mode >::FSharedReferencer (TReferenceControllerBase< Mode > * InReferenceController) inline explicit
Constructor that counts a single reference to the specified object.
Definition at line 533 of file SharedPointerInternals.h.
References ReferenceController.
FSharedReferencer() [3/6]
template<ESPMode Mode> FORCEINLINE SharedPointerInternals::FSharedReferencer< Mode >::FSharedReferencer (FSharedReferencer< Mode > const & InSharedReference) inline
Copy constructor creates a new reference to the existing object.
Definition at line 538 of file SharedPointerInternals.h.
References FSharedReferencer(), FORCEINLINE, and ReferenceController.
FSharedReferencer() [4/6]
template<ESPMode Mode> FORCEINLINE SharedPointerInternals::FSharedReferencer< Mode >::FSharedReferencer (FSharedReferencer< Mode > && InSharedReference) inline
Move constructor creates no new references.
Definition at line 550 of file SharedPointerInternals.h.
References FSharedReferencer(), FORCEINLINE, and ReferenceController.
FSharedReferencer() [5/6]
template<ESPMode Mode> SharedPointerInternals::FSharedReferencer< Mode >::FSharedReferencer (FWeakReferencer< Mode > const & InWeakReference) inline
Creates a shared referencer object from a weak referencer object.
This will only result in a valid object reference if the object already has at least one other shared referencer.
Definition at line 558 of file SharedPointerInternals.h.
References FWeakReferencer, and ReferenceController.
FSharedReferencer() [6/6]
template<ESPMode Mode> SharedPointerInternals::FSharedReferencer< Mode >::FSharedReferencer (FWeakReferencer< Mode > && InWeakReference) inline
Creates a shared referencer object from a weak referencer object.
This will only result in a valid object reference if the object already has at least one other shared referencer.
Definition at line 577 of file SharedPointerInternals.h.
References FWeakReferencer, and ReferenceController.
~FSharedReferencer()
template<ESPMode Mode> FORCEINLINE SharedPointerInternals::FSharedReferencer< Mode >::~FSharedReferencer () inline
Destructor.
Definition at line 600 of file SharedPointerInternals.h.
References FORCEINLINE, and ReferenceController.
Member Function Documentation
GetSharedReferenceCount()
template<ESPMode Mode> FORCEINLINE const int32 SharedPointerInternals::FSharedReferencer< Mode >::GetSharedReferenceCount () const inline
Returns the number of shared references to this object (including this reference.)
Returns
Number of shared references to the object (including this reference.)
Definition at line 675 of file SharedPointerInternals.h.
References FORCEINLINE, and ReferenceController.
IsUnique()
template<ESPMode Mode> FORCEINLINE const bool SharedPointerInternals::FSharedReferencer< Mode >::IsUnique () const inline
Returns true if this is the only shared reference to this object.
Note that there may be outstanding weak references left.
Returns
True if there is only one shared reference to the object, and this is it!
Definition at line 686 of file SharedPointerInternals.h.
References FORCEINLINE, and ReferenceController.
IsValid()
template<ESPMode Mode> FORCEINLINE const bool SharedPointerInternals::FSharedReferencer< Mode >::IsValid () const inline
Tests to see whether or not this shared counter contains a valid reference.
Returns
True if reference is valid
Definition at line 665 of file SharedPointerInternals.h.
References FORCEINLINE, and ReferenceController.
operator=() [1/2]
template<ESPMode Mode> FSharedReferencer & SharedPointerInternals::FSharedReferencer< Mode >::operator= (FSharedReferencer< Mode > && InSharedReference) inline
Move assignment operator adds no references to the assigned object.
If this counter was previously referencing an object, that reference will be released.
Definition at line 639 of file SharedPointerInternals.h.
References FSharedReferencer(), and ReferenceController.
operator=() [2/2]
template<ESPMode Mode> FSharedReferencer & SharedPointerInternals::FSharedReferencer< Mode >::operator= (FSharedReferencer< Mode > const & InSharedReference) inline
Assignment operator adds a reference to the assigned object.
If this counter was previously referencing an object, that reference will be released.
Definition at line 612 of file SharedPointerInternals.h.
References FSharedReferencer(), and ReferenceController.
Friends And Related Symbol Documentation
FWeakReferencer
template<ESPMode Mode> template<ESPMode OtherMode> friend class FWeakReferencer friend
Definition at line 694 of file SharedPointerInternals.h.
References FWeakReferencer.
Referenced by FSharedReferencer(), FSharedReferencer(), and FWeakReferencer.
Field Documentation
ReferenceController
template<ESPMode Mode> TReferenceControllerBase<Mode>* SharedPointerInternals::FSharedReferencer< Mode >::ReferenceController private
Pointer to the reference controller for the object a shared reference/pointer is referencing.
Definition at line 699 of file SharedPointerInternals.h.
Referenced by FSharedReferencer(), FSharedReferencer(), FSharedReferencer(), FSharedReferencer(), FSharedReferencer(), FSharedReferencer(), ~FSharedReferencer(), GetSharedReferenceCount(), IsUnique(), IsValid(), operator=(), operator=(), and SharedPointerInternals::FWeakReferencer< Mode >::operator=().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Templates/SharedPointerInternals.h