Unreal Engine 5.6 C++ API: UE::FWordMutex Class Reference
UE::FWordMutex Class Reference final
A mutex that is the size of a pointer and does not depend on ParkingLot.
#include "WordMutex.h"
Public Member Functions
constexpr FWordMutex ()=default
FWordMutex (const FWordMutex &)=delete
void Lock ()
FWordMutex & operator= (const FWordMutex &)=delete
bool TryLock ()
void Unlock ()
Private Member Functions
void LockSlow ()
void UnlockSlow (UPTRINT CurrentState)
Private Attributes
std::atomic< UPTRINT > State = 0
Static Private Attributes
static constexpr UPTRINT IsLockedFlag = 1 << 0
static constexpr UPTRINT IsQueueLockedFlag = 1 << 1
static constexpr UPTRINT QueueMask = ~(IsLockedFlag | IsQueueLockedFlag)
Detailed Description
A mutex that is the size of a pointer and does not depend on ParkingLot.
Prefer FMutex to FWordMutex whenever possible. This mutex is not fair and does not support recursive locking.
Definition at line 20 of file WordMutex.h.
Constructor & Destructor Documentation
FWordMutex() [1/2]
UE::FWordMutex::FWordMutex () constexpr default
Referenced by FWordMutex(), and operator=().
FWordMutex() [2/2]
UE::FWordMutex::FWordMutex (const FWordMutex &) delete
References FWordMutex().
Member Function Documentation
Lock()
void UE::FWordMutex::Lock () inline
Definition at line 34 of file WordMutex.h.
References IsLockedFlag, LIKELY, LockSlow(), and State.
LockSlow()
void UE::FWordMutex::LockSlow () private
References UE_API.
Referenced by Lock().
operator=()
FWordMutex & UE::FWordMutex::operator= (const FWordMutex &) delete
References FWordMutex().
TryLock()
bool UE::FWordMutex::TryLock () inline
Definition at line 28 of file WordMutex.h.
References IsLockedFlag, and State.
Unlock()
void UE::FWordMutex::Unlock () inline
Definition at line 45 of file WordMutex.h.
References checkSlow, IsLockedFlag, IsQueueLockedFlag, LIKELY, QueueMask, State, and UnlockSlow().
UnlockSlow()
void UE::FWordMutex::UnlockSlow (UPTRINT CurrentState) private
References UE_API.
Referenced by Unlock().
Field Documentation
IsLockedFlag
UPTRINT UE::FWordMutex::IsLockedFlag = 1 << 0 static constexpr private
Definition at line 68 of file WordMutex.h.
Referenced by Lock(), TryLock(), and Unlock().
IsQueueLockedFlag
UPTRINT UE::FWordMutex::IsQueueLockedFlag = 1 << 1 static constexpr private
Definition at line 69 of file WordMutex.h.
Referenced by Unlock().
QueueMask
UPTRINT UE::FWordMutex::QueueMask = ~(IsLockedFlag | IsQueueLockedFlag) static constexpr private
Definition at line 70 of file WordMutex.h.
Referenced by Unlock().
State
std::atomic<UPTRINT> UE::FWordMutex::State = 0 private
Definition at line 72 of file WordMutex.h.
Referenced by Lock(), TryLock(), and Unlock().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Async/WordMutex.h