Unreal Engine 5.6 C++ API: SEditableTextBox Class Reference
SEditableTextBox Class Reference
Editable text box widget.
#include "SEditableTextBox.h"
Public Member Functions
virtual ~SEditableTextBox ()
void AdvanceSearch (const bool InReverse=false)
Advance the current search to the next match (does nothing if not currently searching)
bool AnyTextSelected () const
Query to see if any text is selected within the document.
void BeginSearch (const FText &InSearchText, const ESearchCase::Type InSearchCase=ESearchCase::IgnoreCase, const bool InReverse=false)
Begin a new text search (this is called automatically when the bound search text changes)
void ClearSelection ()
Clear the active text selection.
void Construct (const FArguments &InArgs)
Construct this widget.
void EnableTextInputMethodContext ()
Register and activate the IME context for the text layout of this textbox.
FText GetHintText () const
Returns the Hint text string.
FText GetSearchText () const
Get the text that is currently being searched for (if any)
FText GetSelectedText () const
Get the currently selected text.
FText GetText () const
Returns the text string.
void GoTo (const ETextLocation NewLocation)
Move the cursor to the specified location.
void GoTo (const FTextLocation &NewLocation)
Move the cursor to the given location in the document.
bool HasError () const
virtual bool HasKeyboardFocus () const override
Checks to see if this widget currently has the keyboard focus.
bool IsPassword () const
bool IsReadOnly () const
virtual FReply OnFocusReceived (const FGeometry &MyGeometry, const FFocusEvent &InFocusEvent) override
Called when focus is given to this widget.
virtual FReply OnKeyDown (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent) override
Called after a key is pressed when this widget has focus (this event bubbles if not handled)
void ScrollTo (const ETextLocation NewLocation)
Scroll to the given location in the document (without moving the cursor)
void ScrollTo (const FTextLocation &NewLocation)
Scroll to the given location in the document (without moving the cursor)
void SelectAllText ()
Select all the text in the document.
void SetAllowContextMenu (TAttribute< bool > InAllowContextMenu)
See the AllowContextMenu attribute.
void SetClearKeyboardFocusOnCommit (const TAttribute< bool > &InClearKeyboardFocusOnCommit)
Sets whether to clear keyboard focus when pressing enter to commit changes.
void SetError (const FString &InError)
void SetError (const FText &InError)
If InError is a non-empty string the TextBox will the ErrorReporting provided during construction If no error reporting was provided, the TextBox will create a default error reporter.
void SetFocusedForegroundColor (const TAttribute< FSlateColor > &InFocusedForegroundColor)
Sets the text color and opacity when this box has keyboard focus(overrides Style)
void SetFont (const TAttribute< FSlateFontInfo > &InFont)
Sets the font used to draw the text.
void SetHintText (const TAttribute< FText > &InHintText)
See the HintText attribute.
void SetIsCaretMovedWhenGainFocus (const TAttribute< bool > &InIsCaretMovedWhenGainFocus)
Workaround as we loose focus when the auto completion closes.
void SetIsPassword (TAttribute< bool > InIsPassword)
See the IsPassword attribute.
void SetIsReadOnly (TAttribute< bool > InIsReadOnly)
See the IsReadOnly attribute.
void SetJustification (const TAttribute< ETextJustify::Type > &InJustification)
See Justification attribute.
void SetMaximumLength (const TAttribute< int32 > &InMaximumLength)
Sets the maximum text length that will be accepted by the widget.
void SetMinimumDesiredWidth (const TAttribute< float > &InMinimumDesiredWidth)
Sets the minimum width that a text box should be.
void SetOnKeyCharHandler (FOnKeyChar InOnKeyCharHandler)
Sets the OnKeyCharHandler to provide first chance handling of the SEditableText's OnKeyChar event.
void SetOnKeyDownHandler (FOnKeyDown InOnKeyDownHandler)
Sets the OnKeyDownHandler to provide first chance handling of the SEditableText's OnKeyDown event.
void SetOverflowPolicy (TOptional< ETextOverflowPolicy > InOverflowPolicy)
Sets the overflow policy for this text block.
void SetReadOnlyForegroundColor (const TAttribute< FSlateColor > &InReadOnlyForegroundColor)
Sets the text color and opacity when read-only (overrides Style)
void SetRevertTextOnEscape (const TAttribute< bool > &InRevertTextOnEscape)
Sets whether to allow the user to back out of changes when they press the escape key.
void SetSearchText (const TAttribute< FText > &InSearchText)
Set the text that is currently being searched for (if any)
void SetSelectAllTextOnCommit (const TAttribute< bool > &InSelectAllTextOnCommit)
Sets whether to select all text when pressing enter to commit changes.
void SetSelectAllTextWhenFocused (const TAttribute< bool > &InSelectAllTextWhenFocused)
Sets whether to select all text when the user clicks to give focus on the widget.
void SetSelectWordOnMouseDoubleClick (const TAttribute< bool > &InSelectWordOnMouseDoubleClick)
Sets whether to select select word on mouse double click.
void SetStyle (const FEditableTextBoxStyle *InStyle)
See attribute Style.
void SetText (const TAttribute< FText > &InNewText)
Sets the text string currently being edited.
void SetTextBlockStyle (const FTextBlockStyle *InTextStyle)
Sets the text block style currently used.
void SetTextBoxBackgroundColor (const TAttribute< FSlateColor > &InBackgroundColor)
Sets the color of the background/border around the editable text (overrides Style)
void SetTextBoxForegroundColor (const TAttribute< FSlateColor > &InForegroundColor)
Sets the text color and opacity (overrides Style)
void SetTextFlowDirection (const TOptional< ETextFlowDirection > &InTextFlowDirection)
See TextFlowDirection attribute.
void SetTextShapingMethod (const TOptional< ETextShapingMethod > &InTextShapingMethod)
See TextShapingMethod attribute.
void SetVirtualKeyboardDismissAction (TAttribute< EVirtualKeyboardDismissAction > InVirtualKeyboardDismissAction)
Set the VirtualKeyboardDismissAction attribute.
Text SearchText ForegroundColor FocusedForegroundColor IsPassword SelectAllTextWhenFocused ClearKeyboardFocusOnCommit MaximumLength OnContextMenuOpening OnTextChanged OnVerifyTextChanged SelectAllTextOnCommit OnKeyCharHandler BackgroundColor ErrorReporting VirtualKeyboardOptions VirtualKeyboardDismissAction TextFlowDirection SLATE_ARGUMENT (TOptional< ETextOverflowPolicy >, OverflowPolicy) SLATE_END_ARGS() 1 SEditableTextBox()
Determines what happens to text that is clipped and doesnt fit within the allotted area for this text box.
Text SearchText ForegroundColor FocusedForegroundColor IsPassword SelectAllTextWhenFocused ClearKeyboardFocusOnCommit MaximumLength OnContextMenuOpening OnTextChanged OnVerifyTextChanged SelectAllTextOnCommit OnKeyCharHandler BackgroundColor ErrorReporting VirtualKeyboardOptions VirtualKeyboardDismissAction SLATE_ARGUMENT (TOptional< ETextShapingMethod >, TextShapingMethod) SLATE_ARGUMENT(TOptional< ETextFlowDirection >
Which text shaping method should we use?
Text SearchText ForegroundColor FocusedForegroundColor IsPassword SelectAllTextWhenFocused ClearKeyboardFocusOnCommit MaximumLength SLATE_ATTRIBUTE (bool, AllowContextMenu) SLATE_EVENT(FOnContextMenuOpening
Whether the context menu can be opened.
Text SearchText ForegroundColor FocusedForegroundColor IsPassword SLATE_ATTRIBUTE (bool, IsCaretMovedWhenGainFocus) SLATE_ATTRIBUTE(bool
Workaround as we loose focus when the auto completion closes.
Text SearchText ForegroundColor FocusedForegroundColor SLATE_ATTRIBUTE (bool, IsReadOnly) SLATE_ATTRIBUTE(bool
Sets whether this text box can actually be modified interactively by the user.
Text SearchText ForegroundColor FocusedForegroundColor IsPassword SelectAllTextWhenFocused SLATE_ATTRIBUTE (bool, RevertTextOnEscape) SLATE_ATTRIBUTE(bool
Whether to allow the user to back out of changes when they press the escape key.
Text SearchText ForegroundColor FocusedForegroundColor IsPassword SelectAllTextWhenFocused ClearKeyboardFocusOnCommit MaximumLength OnContextMenuOpening OnTextChanged OnVerifyTextChanged SelectAllTextOnCommit SLATE_ATTRIBUTE (bool, SelectWordOnMouseDoubleClick) SLATE_EVENT(FOnKeyChar
Whether to select word on mouse double click on the widget.
Text SearchText ForegroundColor FocusedForegroundColor IsPassword SelectAllTextWhenFocused ClearKeyboardFocusOnCommit MaximumLength OnContextMenuOpening OnTextChanged OnVerifyTextChanged SelectAllTextOnCommit OnKeyCharHandler BackgroundColor ErrorReporting SLATE_ATTRIBUTE (EKeyboardType, VirtualKeyboardType) SLATE_ARGUMENT(FVirtualKeyboardOptions
The type of virtual keyboard to use on mobile devices.
Text SearchText ForegroundColor FocusedForegroundColor IsPassword SelectAllTextWhenFocused ClearKeyboardFocusOnCommit SLATE_ATTRIBUTE (ETextJustify::Type, Justification) SLATE_ATTRIBUTE(int32
How should the value be justified in the editable text field.
Text SearchText ForegroundColor FocusedForegroundColor IsPassword SelectAllTextWhenFocused ClearKeyboardFocusOnCommit MaximumLength OnContextMenuOpening OnTextChanged OnVerifyTextChanged SelectAllTextOnCommit OnKeyCharHandler BackgroundColor ErrorReporting VirtualKeyboardOptions SLATE_ATTRIBUTE (EVirtualKeyboardTrigger, VirtualKeyboardTrigger) SLATE_ATTRIBUTE(EVirtualKeyboardDismissAction
The type of event that will trigger the display of the virtual keyboard.
Text SearchText ForegroundColor FocusedForegroundColor IsPassword SelectAllTextWhenFocused ClearKeyboardFocusOnCommit MaximumLength OnContextMenuOpening OnTextChanged OnVerifyTextChanged SLATE_ATTRIBUTE (float, MinDesiredWidth) SLATE_ATTRIBUTE(bool
Minimum width that a text block should be.
Text SearchText ForegroundColor FocusedForegroundColor IsPassword SelectAllTextWhenFocused ClearKeyboardFocusOnCommit MaximumLength OnContextMenuOpening OnTextChanged OnVerifyTextChanged SelectAllTextOnCommit OnKeyCharHandler BackgroundColor SLATE_ATTRIBUTE (FMargin, Padding) SLATE_ARGUMENT(TSharedPtr< class IErrorReportingWidget >
Padding between the box/border and the text widget inside (overrides Style)
Text SearchText ForegroundColor SLATE_ATTRIBUTE (FSlateColor, ReadOnlyForegroundColor) SLATE_ATTRIBUTE(FSlateColor
Text color and opacity when read-only (overrides Style)
Text SearchText SLATE_ATTRIBUTE (FSlateFontInfo, Font) SLATE_ATTRIBUTE(FSlateColor
Font color and opacity (overrides Style)
Text SLATE_ATTRIBUTE (FText, HintText) SLATE_ATTRIBUTE(FText
Hint text that appears when there is no text in the text box.
SLATE_BEGIN_ARGS (SEditableTextBox)
Text SearchText ForegroundColor FocusedForegroundColor IsPassword SelectAllTextWhenFocused ClearKeyboardFocusOnCommit MaximumLength OnContextMenuOpening SLATE_EVENT (FMenuExtensionDelegate, ContextMenuExtender) SLATE_EVENT(FOnTextChanged
Menu extender for the right-click context menu.
Text SearchText ForegroundColor FocusedForegroundColor IsPassword SelectAllTextWhenFocused ClearKeyboardFocusOnCommit MaximumLength OnContextMenuOpening OnTextChanged OnVerifyTextChanged SelectAllTextOnCommit OnKeyCharHandler SLATE_EVENT (FOnKeyDown, OnKeyDownHandler) SLATE_ATTRIBUTE(FSlateColor
Callback delegate to have first chance handling of the OnKeyDown event.
Text SearchText ForegroundColor FocusedForegroundColor IsPassword SelectAllTextWhenFocused ClearKeyboardFocusOnCommit MaximumLength OnContextMenuOpening OnTextChanged SLATE_EVENT (FOnTextCommitted, OnTextCommitted) SLATE_EVENT(FOnVerifyTextChanged
Called whenever the text is committed.
SLATE_STYLE_ARGUMENT (FEditableTextBoxStyle, Style) SLATE_ATTRIBUTE(FText
The styling of the textbox.
virtual bool SupportsKeyboardFocus () const override
Checks to see if this widget supports keyboard focus.
Public Member Functions inherited from SBorder
virtual int32 OnPaint (const FPaintArgs &Args, const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, FSlateWindowElementList &OutDrawElements, int32 LayerId, const FWidgetStyle &InWidgetStyle, bool bParentEnabled) const override
The widget should respond by populating the OutDrawElements array with FDrawElements that represent it and any of its children.
Public Member Functions inherited from SCompoundWidget
virtual FChildren * GetChildren () override
Returns the useful children (if any) of this widget.
virtual FSlateColor GetForegroundColor () const override
virtual void OnArrangeChildren (const FGeometry &AllottedGeometry, FArrangedChildren &ArrangedChildren) const override
Compute the Geometry of all the children and add populate the ArrangedChildren list with their values.
virtual void SetVisibility (TAttribute< EVisibility > InVisibility) override final
Public Member Functions inherited from SWidget
template<typename MetaDataType>
void AddMetadata (const TSharedRef< MetaDataType > &AddMe)
Add metadata to this widget.
virtual const FSlateInvalidationRoot * Advanced_AsInvalidationRoot () const
FORCEINLINE TSharedPtr< SWidget > Advanced_GetPaintParentWidget () const
virtual bool Advanced_IsInvalidationRoot () const
virtual bool Advanced_IsWindow () const
Is this widget derivative of SWindow.
void ArrangeChildren (const FGeometry &AllottedGeometry, FArrangedChildren &ArrangedChildren, bool bUpdateAttributes=false) const
Non-virtual entry point for arrange children.
void AssignParentWidget (TSharedPtr< SWidget > InParent)
FORCEINLINE void CacheVolatility ()
Recalculates volatility of the widget and caches the result.
FSlateRect CalculateCullingAndClippingRules (const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, bool &bClipToBounds, bool &bAlwaysClip, bool &bIntersectClipBounds) const
Calculates what if any clipping state changes need to happen when drawing this widget.
bool ConditionallyDetatchParentWidget (SWidget *InExpectedParent)
void EnableToolTipForceField (const bool bEnableForceField)
Sets whether this widget is a "tool tip force field".
FORCEINLINE void ForceVolatile (bool bForce)
Should this widget always appear as volatile for any layout caching host widget.
virtual FChildren * GetAllChildren ()
Returns the children (if any) of this widget that are used by the invalidation system.
template<typename MetaDataType>
TArray< TSharedRef< MetaDataType > > GetAllMetaData () const
Get all metadata of the type provided.
const FGeometry & GetCachedGeometry () const
bool GetCanTick () const
FORCEINLINE EWidgetClipping GetClipping () const
FName GetCreatedInLocation () const
FORCEINLINE FMargin GetCullingBoundsExtension () const
const TOptional< FSlateClippingState > & GetCurrentClippingState () const
Returns the clipping state to clip this widget against its parent.
UE::Slate::FDeprecateVector2DResult GetDesiredSize () const
virtual FSlateColor GetDisabledForegroundColor () const
EFlowDirectionPreference GetFlowDirectionPreference () const
Gets the desired flow direction for the layout.
template<typename MetaDataType>
TSharedPtr< MetaDataType > GetMetaData () const
Get the metadata of the type provided.
const FGeometry & GetPaintSpaceGeometry () const
Gets the last geometry used to Tick the widget.
FORCEINLINE TSharedPtr< SWidget > GetParentWidget () const
const FSlateWidgetPersistentState & GetPersistentState () const
FORCEINLINE EWidgetPixelSnapping GetPixelSnapping () const
const FWidgetProxyHandle GetProxyHandle () const
virtual FString GetReadableLocation () const
virtual float GetRelativeLayoutScale (const int32 ChildIndex, float LayoutScaleMultiplier) const
What is the Child's scale relative to this widget.
FORCEINLINE float GetRenderOpacity () const
FORCEINLINE const TOptional< FSlateRenderTransform > & GetRenderTransform () const
FORCEINLINE UE::Slate::FDeprecateVector2DResult GetRenderTransformPivot () const
FORCEINLINE UE::Slate::FDeprecateVector2DResult GetRenderTransformPivotWithRespectToFlowDirection () const
FORCEINLINE TOptional< FSlateRenderTransform > GetRenderTransformWithRespectToFlowDirection () const
FORCEINLINE TStatId GetStatID (bool bForDeferredUse=false) const
virtual FName GetTag () const
const FGeometry & GetTickSpaceGeometry () const
Gets the last geometry used to Tick the widget.
virtual TSharedPtr< IToolTip > GetToolTip ()
FName GetType () const
FString GetTypeAsString () const
FORCEINLINE EVisibility GetVisibility () const
virtual EWindowZone::Type GetWindowZoneOverride () const
Called when the mouse is moved over the widget's window, to determine if we should report whether OS-specific features should be active at this location (such as a title bar grip, system menu, etc.) Usually you should not need to override this function.
bool HasActiveTimers () const
Does this widget have any active timers?
bool HasAnyUpdateFlags (EWidgetUpdateFlags FlagsToCheck) const
TOptional< EFocusCause > HasAnyUserFocus () const
Gets whether or not any users have this widget focused, and if so the type of focus (first one found).
bool HasAnyUserFocusOrFocusedDescendants () const
bool HasFocusedDescendants () const
bool HasMouseCapture () const
Checks to see if this widget is the current mouse captor.
bool HasMouseCaptureByUser (int32 UserIndex, TOptional< int32 > PointerIndex=TOptional< int32 >()) const
Checks to see if this widget has mouse capture from the provided user.
bool HasRegisteredSlateAttribute () const
bool HasToolTipForceField () const
TOptional< EFocusCause > HasUserFocus (int32 UserIndex) const
Gets whether or not the specified users has this widget focused, and if so the type of focus.
bool HasUserFocusedDescendants (int32 UserIndex) const
Gets whether or not the specified users has this widget or any descendant focused.
void Invalidate (EInvalidateWidgetReason InvalidateReason)
Invalidates the widget from the view of a layout caching widget that may own this widget.
bool IsAttributesUpdatesEnabled () const
bool IsDirectlyHovered () const
FORCEINLINE bool IsEnabled () const
bool IsHovered () const
virtual bool IsInteractable () const
FORCEINLINE bool IsParentValid () const
FORCEINLINE bool IsVolatile () const
Whether or not a widget is volatile and will update every frame without being invalidated.
FORCEINLINE bool IsVolatileIndirectly () const
This widget is volatile because its parent or some ancestor is volatile.
void MarkPrepassAsDirty ()
In fast path, if the widget is mark, do a full Prepass on its next update to calculate it's desired size.
bool NeedsPrepass () const
virtual FReply OnAnalogValueChanged (const FGeometry &MyGeometry, const FAnalogInputEvent &InAnalogInputEvent)
Called when an analog value changes on a button that supports analog.
virtual FCursorReply OnCursorQuery (const FGeometry &MyGeometry, const FPointerEvent &CursorEvent) const
The system asks each widget under the mouse to provide a cursor.
virtual FReply OnDragDetected (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Called when Slate detects that a widget started to be dragged.
virtual void OnDragEnter (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called during drag and drop when the drag enters a widget.
virtual void OnDragLeave (const FDragDropEvent &DragDropEvent)
Called during drag and drop when the drag leaves a widget.
virtual FReply OnDragOver (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called during drag and drop when the the mouse is being dragged over a widget.
virtual FReply OnDrop (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called when the user is dropping something onto a widget; terminates drag and drop.
virtual void OnFinishedKeyInput ()
All the key (keyboard, gamepay, joystick, etc.) input from this frame has been routed.
virtual void OnFinishedPointerInput ()
All the pointer (mouse, touch, stylus, etc.) events from this frame have been routed.
virtual void OnFocusChanging (const FWeakWidgetPath &PreviousFocusPath, const FWidgetPath &NewWidgetPath, const FFocusEvent &InFocusEvent)
Called whenever a focus path is changing on all the widgets within the old and new focus paths.
virtual void OnFocusLost (const FFocusEvent &InFocusEvent)
Called when this widget loses focus.
virtual FReply OnKeyChar (const FGeometry &MyGeometry, const FCharacterEvent &InCharacterEvent)
Called after a character is entered while this widget has keyboard focus.
virtual FReply OnKeyUp (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
Called after a key is released when this widget has focus.
virtual TOptional< TSharedRef< SWidget > > OnMapCursor (const FCursorReply &CursorReply) const
After OnCursorQuery has specified a cursor type the system asks each widget under the mouse to map that cursor to a widget.
virtual FReply OnMotionDetected (const FGeometry &MyGeometry, const FMotionEvent &InMotionEvent)
Called when motion is detected (controller or device) e.g.
virtual FReply OnMouseButtonDoubleClick (const FGeometry &InMyGeometry, const FPointerEvent &InMouseEvent)
Called when a mouse button is double clicked.
virtual FReply OnMouseButtonDown (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system calls this method to notify the widget that a mouse button was pressed within it.
virtual FReply OnMouseButtonUp (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system calls this method to notify the widget that a mouse button was release within it.
virtual void OnMouseCaptureLost (const FCaptureLostEvent &CaptureLostEvent)
Called when this widget had captured the mouse, but that capture has been revoked for some reason.
virtual void OnMouseEnter (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system will use this event to notify a widget that the cursor has entered it.
virtual void OnMouseLeave (const FPointerEvent &MouseEvent)
The system will use this event to notify a widget that the cursor has left it.
virtual FReply OnMouseMove (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system calls this method to notify the widget that a mouse moved within it.
virtual FReply OnMouseWheel (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Called when the mouse wheel is spun.
virtual FNavigationReply OnNavigation (const FGeometry &MyGeometry, const FNavigationEvent &InNavigationEvent)
Called when navigation is requested e.g.
virtual FReply OnPreviewKeyDown (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
Called after a key is pressed when this widget or a child of this widget has focus If a widget handles this event, OnKeyDown will not be passed to the focused widget.
virtual FReply OnPreviewMouseButtonDown (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Just like OnMouseButtonDown, but tunnels instead of bubbling.
virtual FPopupMethodReply OnQueryPopupMethod () const
Popups can manifest in a NEW OS WINDOW or via an OVERLAY in an existing window.
virtual TOptional< bool > OnQueryShowFocus (const EFocusCause InFocusCause) const
Called to determine if we should render the focus brush.
virtual void OnToolTipClosing ()
Called when a tooltip displayed from this widget is being closed.
virtual FReply OnTouchEnded (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is ended (finger lifted)
virtual FReply OnTouchFirstMove (const FGeometry &MyGeometry, const FPointerEvent &TouchEvent)
Called when a touchpad touch first moves after TouchStarted.
virtual FReply OnTouchForceChanged (const FGeometry &MyGeometry, const FPointerEvent &TouchEvent)
Called when a touchpad touch force changes.
virtual FReply OnTouchGesture (const FGeometry &MyGeometry, const FPointerEvent &GestureEvent)
Called when the user performs a gesture on trackpad.
virtual FReply OnTouchMoved (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is moved (finger moved)
virtual FReply OnTouchStarted (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is started (finger down)
virtual TSharedPtr< FPopupLayer > OnVisualizePopup (const TSharedRef< SWidget > &PopupContent)
Visualize a new pop-up if possible.
virtual bool OnVisualizeTooltip (const TSharedPtr< SWidget > &TooltipContent)
Called when Slate wants to visualize tooltip.
int32 Paint (const FPaintArgs &Args, const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, FSlateWindowElementList &OutDrawElements, int32 LayerId, const FWidgetStyle &InWidgetStyle, bool bParentEnabled) const
Called to tell a widget to paint itself (and it's children).
TSharedRef< FActiveTimerHandle > RegisterActiveTimer (float TickPeriod, FWidgetActiveTimerDelegate TickFunction)
Registers an "active timer" delegate that will execute at some regular interval.
template<typename MetaDataType>
int32 RemoveMetaData (const TSharedRef< MetaDataType > &RemoveMe)
Remove metadata to this widget.
void SetCanTick (bool bInCanTick)
void SetClipping (EWidgetClipping InClipping)
Sets the clipping to bounds rules for this widget.
FORCEINLINE void SetCullingBoundsExtension (const FMargin &InCullingBoundsExtension)
Sets an additional culling padding that is added to a widget to give more leeway when culling widgets.
void SetCursor (const TAttribute< TOptional< EMouseCursor::Type > > &InCursor)
Set the cursor that should appear when this widget is hovered.
void SetEnabled (TAttribute< bool > InEnabledState)
Sets the enabled state of this widget.
void SetFlowDirectionPreference (EFlowDirectionPreference InFlowDirectionPreference)
Sets how content should flow in this panel, based on the current culture.
void SetOnMouseButtonDown (FPointerEventHandler EventHandler)
See OnMouseButtonDown event.
void SetOnMouseButtonUp (FPointerEventHandler EventHandler)
See OnMouseButtonUp event.
void SetOnMouseDoubleClick (FPointerEventHandler EventHandler)
See OnMouseDoubleClick event.
void SetOnMouseEnter (FNoReplyPointerEventHandler EventHandler)
See OnMouseEnter event.
void SetOnMouseLeave (FSimpleNoReplyPointerEventHandler EventHandler)
See OnMouseLeave event.
void SetOnMouseMove (FPointerEventHandler EventHandler)
See OnMouseMove event.
void SetPixelSnapping (EWidgetPixelSnapping InPixelSnappingMethod)
Sets the pixel snapping method for this widget.
FORCEINLINE void SetRenderOpacity (float InRenderOpacity)
FORCEINLINE void SetRenderTransform (TAttribute< TOptional< FSlateRenderTransform > > InTransform)
FORCEINLINE void SetRenderTransformPivot (TAttribute< FVector2D > InTransformPivot)
FORCEINLINE void SetTag (FName InTag)
void SetToolTip (const TAttribute< TSharedPtr< IToolTip > > &InToolTip)
Set the tool tip that should appear when this widget is hovered.
void SetToolTipText (const FText &InToolTipText)
Set the tool tip that should appear when this widget is hovered.
void SetToolTipText (const TAttribute< FText > &ToolTipText)
Set the tool tip that should appear when this widget is hovered.
FORCEINLINE bool ShouldInvalidatePrepassDueToVolatility ()
void SlatePrepass ()
DEPRECATED version of SlatePrepass that assumes no scaling beyond AppScale.
void SlatePrepass (float InLayoutScaleMultiplier)
Descends to leaf-most widgets in the hierarchy and gathers desired sizes on the way up.
virtual void Tick (const FGeometry &AllottedGeometry, const double InCurrentTime, const float InDeltaTime)
Ticks this widget with Geometry.
virtual FString ToString () const
virtual TOptional< FVirtualPointerPosition > TranslateMouseCoordinateForCustomHitTestChild (const SWidget &ChildWidget, const FGeometry &MyGeometry, const FVector2D ScreenSpaceMouseCoordinate, const FVector2D LastScreenSpaceMouseCoordinate) const
void UnRegisterActiveTimer (const TSharedRef< FActiveTimerHandle > &ActiveTimerHandle)
Unregisters an active timer handle.
virtual bool ValidatePathToChild (SWidget *InChild)
Public Member Functions inherited from FSlateControlledConstruction
FSlateControlledConstruction ()=default
virtual ~FSlateControlledConstruction ()=default
virtual const FSlateWidgetClassData & GetWidgetClass () const =0
void operator delete (void *mem)
Public Member Functions inherited from TSharedFromThis< SWidget >
TSharedRef< SWidget, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< SWidget, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Protected Member Functions
void OnEditableTextChanged (const FText &InText)
Callback for the editable text's OnTextChanged event.
void OnEditableTextCommitted (const FText &InText, ETextCommit::Type InCommitType)
Callback when the editable text is committed.
Protected Member Functions inherited from SBorder
virtual FVector2D ComputeDesiredSize (float) const override
Compute the ideal size necessary to display this widget.
TSlateAttributeRef< FSlateColor > GetBorderBackgroundColorAttribute () const
TSlateAttributeRef< const FSlateBrush * > GetBorderImageAttribute () const
FVector2D GetDesiredSizeScale () const
Get the desired size scale multiplier.
TSlateAttributeRef< FVector2D > GetDesiredSizeScaleAttribute () const
bool GetShowDisabledEffect () const
Get whether or not to show the disabled effect when this border is disabled.
TSlateAttributeRef< bool > GetShowDisabledEffectAttribute () const
Protected Member Functions inherited from SCompoundWidget
SCompoundWidget ()
Disallow public construction.
virtual ~SCompoundWidget ()
TSlateAttributeRef< FLinearColor > GetColorAndOpacityAttribute () const
TSlateAttributeRef< FVector2D > GetContentScaleAttribute () const
TSlateAttributeRef< FSlateColor > GetForegroundColorAttribute () const
Protected Member Functions inherited from SWidget
SWidget ()
Hidden default constructor.
virtual ~SWidget ()
Dtor ensures that active timer handles are UnRegistered with the SlateApplication.
FORCEINLINE bool Advanced_InvalidateVolatility ()
Recalculates and caches volatility and returns 'true' if the volatility changed.
virtual void CacheDesiredSize (float InLayoutScaleMultiplier)
The system calls this method.
EFlowDirection ComputeFlowDirection () const
Establishes a new flow direction potentially, if this widget has a particular preference for it and all its children.
virtual bool ComputeVolatility () const
Recomputes the volatility of the widget.
virtual bool CustomPrepass (float LayoutScaleMultiplier)
bool FindChildGeometries (const FGeometry &MyGeometry, const TSet< TSharedRef< SWidget > > &WidgetsToFind, TMap< TSharedRef< SWidget >, FArrangedWidget > &OutResult) const
Find the geometry of a descendant widget.
void FindChildGeometries_Helper (const FGeometry &MyGeometry, const TSet< TSharedRef< SWidget > > &WidgetsToFind, TMap< TSharedRef< SWidget >, FArrangedWidget > &OutResult) const
Actual implementation of FindChildGeometries.
FGeometry FindChildGeometry (const FGeometry &MyGeometry, TSharedRef< SWidget > WidgetToFind) const
Find the geometry of a descendant widget.
virtual TOptional< EMouseCursor::Type > GetCursor () const
The cursor to show when the mouse is hovering over this widget.
TSlateAttributeRef< bool > GetEnabledStateAttribute () const
virtual const FSlateBrush * GetFocusBrush () const
TSlateAttributeRef< bool > GetHoveredAttribute () const
float GetPrepassLayoutScaleMultiplier () const
TSlateAttributeRef< TOptional< FSlateRenderTransform > > GetRenderTransformAttribute () const
TSlateAttributeRef< FVector2D > GetRenderTransformPivotAttribute () const
TSlateAttributeRef< EVisibility > GetVisibilityAttribute () const
void InvalidateChildRemovedFromTree (SWidget &Child)
Called when a child is removed from the tree parent's widget tree either by removing it from a slot.
FORCEINLINE bool IsChildWidgetCulled (const FSlateRect &, const FArrangedWidget &) const
bool IsConstructed () const
Is the widget construction completed (did we called and returned from the Construct() function)
virtual void OnClippingChanged ()
Called when clipping is changed.
void Prepass_ChildLoop (float InLayoutScaleMultiplier, FChildren *MyChildren)
template<typename TargetValueType, typename SourceValueType>
bool SetAttribute (TAttribute< TargetValueType > &TargetValue, const TAttribute< SourceValueType > &SourceValue, EInvalidateWidgetReason BaseInvalidationReason)
Performs the attribute assignment and invalidates the widget minimally based on what actually changed.
void SetDebugInfo (const ANSICHAR *InType, const ANSICHAR *InFile, int32 OnLine, size_t InAllocSize)
Used by Slate to set the runtime debug info about this widget.
void SetHover (TAttribute< bool > InHovered)
Set the hover state.
void SetVolatilePrepass (bool bVolatile)
bool ShouldBeEnabled (bool InParentEnabled) const
Determines if this widget should be enabled.
void SWidgetConstruct (const FSlateBaseNamedArgs &Args)
Construct a SWidget based on initial parameters.
Protected Member Functions inherited from TSharedFromThis< SWidget >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Protected Attributes
TAttribute< FSlateColor > BackgroundColorOverride
Background color (overrides style)
TSharedPtr< SHorizontalBox > Box
Allows for inserting additional widgets that extend the functionality of the text box.
TSharedPtr< SEditableText > EditableText
Editable text widget.
TSharedPtr< class IErrorReportingWidget > ErrorReporting
SomeWidget reporting.
TAttribute< FSlateColor > FocusedForegroundColorOverride
Focused foreground color (overrides style)
TAttribute< FSlateFontInfo > FontOverride
Font (overrides style)
TAttribute< FSlateColor > ForegroundColorOverride
Foreground color (overrides style)
TAttribute< int32 > MaximumLength
Maximum text length that will be accepted by the widget.
FOnTextChanged OnTextChanged
Called when the text is changed interactively.
FOnTextCommitted OnTextCommitted
Called when the user commits their change to the editable text control.
FOnVerifyTextChanged OnVerifyTextChanged
Callback to verify text when changed.
TSharedPtr< SBox > PaddingBox
Box widget that adds padding around the editable text.
TAttribute< FMargin > PaddingOverride
Padding (overrides style)
TAttribute< FSlateColor > ReadOnlyForegroundColorOverride
Read-only foreground color (overrides style)
const FEditableTextBoxStyle * Style
Protected Attributes inherited from SCompoundWidget
FCompoundWidgetOneChildSlot ChildSlot
The slot that contains this widget's descendants.
Protected Attributes inherited from SWidget
uint8 bCanHaveChildren: 1
Can the widget ever support children?
uint8 bCanSupportFocus: 1
Can the widget ever support keyboard focus.
uint8 bClippingProxy: 1
Some widgets might be a complex hierarchy of child widgets you never see.
uint8 bHasCustomPrepass: 1
uint8 bHasRelativeLayoutScale: 1
uint8 bVolatilityAlwaysInvalidatesPrepass: 1
if this widget should always invalidate the prepass step when volatile
EWidgetClipping Clipping
Set to true if all content of the widget should clip to the bounds of this widget.
FMargin CullingBoundsExtension
Can be used to enlarge the culling bounds of this widget (pre-intersection), this can be useful if you've got children that you know are using rendering transforms to render outside their standard bounds, if that happens it's possible the parent might be culled before the descendant widget is entirely off screen.
EWidgetPixelSnapping PixelSnappingMethod
When set to EPixelSnappingMethod::SnapToPixel, the widget is drawn at the nearest pixel.
float RenderOpacity
The opacity of the widget.
Private Member Functions
FSlateColor DetermineBackgroundColor () const
FSlateFontInfo DetermineFont () const
FSlateColor DetermineForegroundColor () const
FMargin DeterminePadding () const
const FSlateBrush * GetBorderImage () const
Private Attributes
const FSlateBrush * BorderImageFocused
Styling: border image to draw when focused.
const FSlateBrush * BorderImageHovered
Styling: border image to draw when hovered.
const FSlateBrush * BorderImageNormal
Styling: border image to draw when not hovered or focused.
const FSlateBrush * BorderImageReadOnly
Styling: border image to draw when read only.
Additional Inherited Members
Static Public Member Functions inherited from FSlateControlledConstruction
static const FSlateWidgetClassData & StaticWidgetClass ()
Static Protected Member Functions inherited from SWidget
static TAttribute< EVisibility > AccessWidgetVisibilityAttribute (const TSharedRef< SWidget > &Widget)
Protected static helper to allow widgets to access the visibility attribute of other widgets directly.
static int32 FindChildUnderMouse (const FArrangedChildren &Children, const FPointerEvent &MouseEvent)
static int32 FindChildUnderPosition (const FArrangedChildren &Children, const UE::Slate::FDeprecateVector2DParameter &ArrangedSpacePosition)
Static Protected Member Functions inherited from TSharedFromThis< SWidget >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
Editable text box widget.
Definition at line 28 of file SEditableTextBox.h.
Constructor & Destructor Documentation
~SEditableTextBox()
virtual SEditableTextBox::~SEditableTextBox () virtual
Member Function Documentation
AdvanceSearch()
void SEditableTextBox::AdvanceSearch (const bool InReverse = false)
Advance the current search to the next match (does nothing if not currently searching)
AnyTextSelected()
bool SEditableTextBox::AnyTextSelected () const
Query to see if any text is selected within the document.
BeginSearch()
void SEditableTextBox::BeginSearch (const FText & InSearchText, const ESearchCase::Type InSearchCase = ESearchCase::IgnoreCase, const bool InReverse = false)
Begin a new text search (this is called automatically when the bound search text changes)
References ESearchCase::IgnoreCase.
ClearSelection()
void SEditableTextBox::ClearSelection ()
Clear the active text selection.
Construct()
void SEditableTextBox::Construct (const FArguments & InArgs)
Construct this widget.
Parameters
InArgs The declaration data for this widget
References Construct().
Referenced by Construct(), and SSearchBox::SLATE_EVENT().
DetermineBackgroundColor()
FSlateColor SEditableTextBox::DetermineBackgroundColor () const private
DetermineFont()
FSlateFontInfo SEditableTextBox::DetermineFont () const private
DetermineForegroundColor()
FSlateColor SEditableTextBox::DetermineForegroundColor () const private
DeterminePadding()
FMargin SEditableTextBox::DeterminePadding () const private
EnableTextInputMethodContext()
void SEditableTextBox::EnableTextInputMethodContext ()
Register and activate the IME context for the text layout of this textbox.
GetBorderImage()
const FSlateBrush * SEditableTextBox::GetBorderImage () const private
Returns
Border image for the text box based on the hovered and focused state
GetHintText()
FText SEditableTextBox::GetHintText () const inline
Returns the Hint text string.
Returns
Hint Text string
Definition at line 218 of file SEditableTextBox.h.
References EditableText.
GetSearchText()
FText SEditableTextBox::GetSearchText () const
Get the text that is currently being searched for (if any)
GetSelectedText()
FText SEditableTextBox::GetSelectedText () const
Get the currently selected text.
GetText()
FText SEditableTextBox::GetText () const inline
Returns the text string.
Returns
Text string
Definition at line 191 of file SEditableTextBox.h.
References EditableText, and GetText().
Referenced by GetText().
GoTo() [1/2]
void SEditableTextBox::GoTo (const ETextLocation NewLocation) inline
Move the cursor to the specified location.
Definition at line 388 of file SEditableTextBox.h.
References EditableText.
GoTo() [2/2]
void SEditableTextBox::GoTo (const FTextLocation & NewLocation)
Move the cursor to the given location in the document.
HasError()
bool SEditableTextBox::HasError () const
HasKeyboardFocus()
virtual bool SEditableTextBox::HasKeyboardFocus () const override virtual
Checks to see if this widget currently has the keyboard focus.
Returns
True if this widget has keyboard focus
Reimplemented from SWidget.
IsPassword()
bool SEditableTextBox::IsPassword () const inline
Definition at line 240 of file SEditableTextBox.h.
References EditableText.
Referenced by SLATE_ATTRIBUTE().
IsReadOnly()
bool SEditableTextBox::IsReadOnly () const inline
Definition at line 235 of file SEditableTextBox.h.
References EditableText.
Referenced by SLATE_ATTRIBUTE().
OnEditableTextChanged()
void SEditableTextBox::OnEditableTextChanged (const FText & InText) protected
Callback for the editable text's OnTextChanged event.
OnEditableTextCommitted()
void SEditableTextBox::OnEditableTextCommitted (const FText & InText, ETextCommit::Type InCommitType) protected
Callback when the editable text is committed.
OnFocusReceived()
virtual FReply SEditableTextBox::OnFocusReceived (const FGeometry & MyGeometry, const FFocusEvent & InFocusEvent) override virtual
Called when focus is given to this widget.
This event does not bubble.
Parameters
MyGeometry The Geometry of the widget receiving the event
InFocusEvent The FocusEvent
Returns
Returns whether the event was handled, along with other possible actions
Reimplemented from SWidget.
OnKeyDown()
virtual FReply SEditableTextBox::OnKeyDown (const FGeometry & MyGeometry, const FKeyEvent & InKeyEvent) override virtual
Called after a key is pressed when this widget has focus (this event bubbles if not handled)
Parameters
MyGeometry The Geometry of the widget receiving the event
InKeyEvent Key event
Returns
Returns whether the event was handled, along with other possible actions
Reimplemented from SWidget.
References Main.
ScrollTo() [1/2]
void SEditableTextBox::ScrollTo (const ETextLocation NewLocation) inline
Scroll to the given location in the document (without moving the cursor)
Definition at line 397 of file SEditableTextBox.h.
References EditableText.
ScrollTo() [2/2]
void SEditableTextBox::ScrollTo (const FTextLocation & NewLocation)
Scroll to the given location in the document (without moving the cursor)
SelectAllText()
void SEditableTextBox::SelectAllText ()
Select all the text in the document.
SetAllowContextMenu()
void SEditableTextBox::SetAllowContextMenu (TAttribute< bool > InAllowContextMenu)
See the AllowContextMenu attribute.
SetClearKeyboardFocusOnCommit()
void SEditableTextBox::SetClearKeyboardFocusOnCommit (const TAttribute< bool > & InClearKeyboardFocusOnCommit)
Sets whether to clear keyboard focus when pressing enter to commit changes.
Parameters
InClearKeyboardFocusOnCommit Clear keyboard focus when pressing enter?
SetError() [1/2]
void SEditableTextBox::SetError (const FString & InError)
SetError() [2/2]
void SEditableTextBox::SetError (const FText & InError)
If InError is a non-empty string the TextBox will the ErrorReporting provided during construction If no error reporting was provided, the TextBox will create a default error reporter.
SetFocusedForegroundColor()
void SEditableTextBox::SetFocusedForegroundColor (const TAttribute< FSlateColor > & InFocusedForegroundColor)
Sets the text color and opacity when this box has keyboard focus(overrides Style)
Parameters
InFocusedForegroundColor The focused color and opacity
SetFont()
void SEditableTextBox::SetFont (const TAttribute< FSlateFontInfo > & InFont)
Sets the font used to draw the text.
Parameters
InFont The new font to use
SetHintText()
void SEditableTextBox::SetHintText (const TAttribute< FText > & InHintText)
See the HintText attribute.
SetIsCaretMovedWhenGainFocus()
void SEditableTextBox::SetIsCaretMovedWhenGainFocus (const TAttribute< bool > & InIsCaretMovedWhenGainFocus)
Workaround as we loose focus when the auto completion closes.
Parameters
InIsCaretMovedWhenGainFocus Workaround
SetIsPassword()
void SEditableTextBox::SetIsPassword (TAttribute< bool > InIsPassword)
See the IsPassword attribute.
SetIsReadOnly()
void SEditableTextBox::SetIsReadOnly (TAttribute< bool > InIsReadOnly)
See the IsReadOnly attribute.
SetJustification()
void SEditableTextBox::SetJustification (const TAttribute< ETextJustify::Type > & InJustification)
See Justification attribute.
SetMaximumLength()
void SEditableTextBox::SetMaximumLength (const TAttribute< int32 > & InMaximumLength)
Sets the maximum text length that will be accepted by the widget.
Parameters
InMaximumLength Length to check for. Only values superior to 0 will be taken into account, otherwise no length check will occur.
SetMinimumDesiredWidth()
void SEditableTextBox::SetMinimumDesiredWidth (const TAttribute< float > & InMinimumDesiredWidth)
Sets the minimum width that a text box should be.
Parameters
InMinimumDesiredWidth The minimum width
SetOnKeyCharHandler()
void SEditableTextBox::SetOnKeyCharHandler (FOnKeyChar InOnKeyCharHandler)
Sets the OnKeyCharHandler to provide first chance handling of the SEditableText's OnKeyChar event.
Parameters
InOnKeyCharHandler Delegate to call during OnKeyChar event
SetOnKeyDownHandler()
void SEditableTextBox::SetOnKeyDownHandler (FOnKeyDown InOnKeyDownHandler)
Sets the OnKeyDownHandler to provide first chance handling of the SEditableText's OnKeyDown event.
Parameters
InOnKeyDownHandler Delegate to call during OnKeyDown event
SetOverflowPolicy()
void SEditableTextBox::SetOverflowPolicy (TOptional< ETextOverflowPolicy > InOverflowPolicy)
Sets the overflow policy for this text block.
SetReadOnlyForegroundColor()
void SEditableTextBox::SetReadOnlyForegroundColor (const TAttribute< FSlateColor > & InReadOnlyForegroundColor)
Sets the text color and opacity when read-only (overrides Style)
Parameters
InReadOnlyForegroundColor The read-only text color and opacity
SetRevertTextOnEscape()
void SEditableTextBox::SetRevertTextOnEscape (const TAttribute< bool > & InRevertTextOnEscape)
Sets whether to allow the user to back out of changes when they press the escape key.
Parameters
InRevertTextOnEscape Allow the user to back out of changes?
SetSearchText()
void SEditableTextBox::SetSearchText (const TAttribute< FText > & InSearchText)
Set the text that is currently being searched for (if any)
SetSelectAllTextOnCommit()
void SEditableTextBox::SetSelectAllTextOnCommit (const TAttribute< bool > & InSelectAllTextOnCommit)
Sets whether to select all text when pressing enter to commit changes.
Parameters
InSelectAllTextOnCommit Select all text when pressing enter?
SetSelectAllTextWhenFocused()
void SEditableTextBox::SetSelectAllTextWhenFocused (const TAttribute< bool > & InSelectAllTextWhenFocused)
Sets whether to select all text when the user clicks to give focus on the widget.
Parameters
InSelectAllTextWhenFocused Select all text when the user clicks?
SetSelectWordOnMouseDoubleClick()
void SEditableTextBox::SetSelectWordOnMouseDoubleClick (const TAttribute< bool > & InSelectWordOnMouseDoubleClick)
Sets whether to select select word on mouse double click.
Parameters
InSelectWordOnMouseDoubleClick Select select word on mouse double click?
SetStyle()
void SEditableTextBox::SetStyle (const FEditableTextBoxStyle * InStyle)
See attribute Style.
SetText()
void SEditableTextBox::SetText (const TAttribute< FText > & InNewText)
Sets the text string currently being edited.
Parameters
InNewText The new text string
SetTextBlockStyle()
void SEditableTextBox::SetTextBlockStyle (const FTextBlockStyle * InTextStyle)
Sets the text block style currently used.
Parameters
InTextStyle The new text string
SetTextBoxBackgroundColor()
void SEditableTextBox::SetTextBoxBackgroundColor (const TAttribute< FSlateColor > & InBackgroundColor)
Sets the color of the background/border around the editable text (overrides Style)
Parameters
InBackgroundColor The background/border color
SetTextBoxForegroundColor()
void SEditableTextBox::SetTextBoxForegroundColor (const TAttribute< FSlateColor > & InForegroundColor)
Sets the text color and opacity (overrides Style)
Parameters
InForegroundColor The text color and opacity
SetTextFlowDirection()
void SEditableTextBox::SetTextFlowDirection (const TOptional< ETextFlowDirection > & InTextFlowDirection)
See TextFlowDirection attribute.
SetTextShapingMethod()
void SEditableTextBox::SetTextShapingMethod (const TOptional< ETextShapingMethod > & InTextShapingMethod)
See TextShapingMethod attribute.
SetVirtualKeyboardDismissAction()
void SEditableTextBox::SetVirtualKeyboardDismissAction (TAttribute< EVirtualKeyboardDismissAction > InVirtualKeyboardDismissAction)
Set the VirtualKeyboardDismissAction attribute.
SLATE_ARGUMENT() [1/2]
Text SearchText ForegroundColor FocusedForegroundColor IsPassword SelectAllTextWhenFocused ClearKeyboardFocusOnCommit MaximumLength OnContextMenuOpening OnTextChanged OnVerifyTextChanged SelectAllTextOnCommit OnKeyCharHandler BackgroundColor ErrorReporting VirtualKeyboardOptions VirtualKeyboardDismissAction TextFlowDirection SEditableTextBox::SLATE_ARGUMENT (TOptional< ETextOverflowPolicy > , OverflowPolicy)
Determines what happens to text that is clipped and doesnt fit within the allotted area for this text box.
References SLATE_ARGUMENT(), and SBorder::SLATE_END_ARGS().
SLATE_ARGUMENT() [2/2]
Text SearchText ForegroundColor FocusedForegroundColor IsPassword SelectAllTextWhenFocused ClearKeyboardFocusOnCommit MaximumLength OnContextMenuOpening OnTextChanged OnVerifyTextChanged SelectAllTextOnCommit OnKeyCharHandler BackgroundColor ErrorReporting VirtualKeyboardOptions VirtualKeyboardDismissAction SEditableTextBox::SLATE_ARGUMENT (TOptional< ETextShapingMethod > , TextShapingMethod)
Which text shaping method should we use?
(unset to use the default returned by GetDefaultTextShapingMethod) Which text flow direction should we use? (unset to use the default returned by GetDefaultTextFlowDirection)
References SLATE_ARGUMENT().
Referenced by SLATE_ARGUMENT(), SLATE_ARGUMENT(), SLATE_ATTRIBUTE(), and SLATE_ATTRIBUTE().
SLATE_ATTRIBUTE() [1/13]
Text SearchText ForegroundColor FocusedForegroundColor IsPassword SelectAllTextWhenFocused ClearKeyboardFocusOnCommit MaximumLength SEditableTextBox::SLATE_ATTRIBUTE (bool , AllowContextMenu)
Whether the context menu can be opened.
Delegate to call before a context menu is opened. User returns the menu content or null to the disable context menu
References SLATE_ATTRIBUTE(), and SLATE_EVENT().
SLATE_ATTRIBUTE() [2/13]
Text SearchText ForegroundColor FocusedForegroundColor IsPassword SEditableTextBox::SLATE_ATTRIBUTE (bool , IsCaretMovedWhenGainFocus)
Workaround as we loose focus when the auto completion closes.
Whether to select all text when the user clicks to give focus on the widget
References SLATE_ATTRIBUTE().
SLATE_ATTRIBUTE() [3/13]
Text SearchText ForegroundColor FocusedForegroundColor SEditableTextBox::SLATE_ATTRIBUTE (bool , IsReadOnly)
Sets whether this text box can actually be modified interactively by the user.
Sets whether this text box is for storing a password
References IsPassword(), IsReadOnly(), and SLATE_ATTRIBUTE().
SLATE_ATTRIBUTE() [4/13]
Text SearchText ForegroundColor FocusedForegroundColor IsPassword SelectAllTextWhenFocused SEditableTextBox::SLATE_ATTRIBUTE (bool , RevertTextOnEscape)
Whether to allow the user to back out of changes when they press the escape key.
Whether to clear keyboard focus when pressing enter to commit changes
References SLATE_ATTRIBUTE().
SLATE_ATTRIBUTE() [5/13]
Text SearchText ForegroundColor FocusedForegroundColor IsPassword SelectAllTextWhenFocused ClearKeyboardFocusOnCommit MaximumLength OnContextMenuOpening OnTextChanged OnVerifyTextChanged SelectAllTextOnCommit SEditableTextBox::SLATE_ATTRIBUTE (bool , SelectWordOnMouseDoubleClick)
Whether to select word on mouse double click on the widget.
Callback delegate to have first chance handling of the OnKeyChar event
References SLATE_ATTRIBUTE(), and SLATE_EVENT().
SLATE_ATTRIBUTE() [6/13]
Text SearchText ForegroundColor FocusedForegroundColor IsPassword SelectAllTextWhenFocused ClearKeyboardFocusOnCommit MaximumLength OnContextMenuOpening OnTextChanged OnVerifyTextChanged SelectAllTextOnCommit OnKeyCharHandler BackgroundColor ErrorReporting SEditableTextBox::SLATE_ATTRIBUTE (EKeyboardType , VirtualKeyboardType)
The type of virtual keyboard to use on mobile devices.
Additional options for the virtual keyboard summoned by this widget
References SLATE_ARGUMENT(), and SLATE_ATTRIBUTE().
SLATE_ATTRIBUTE() [7/13]
Text SearchText ForegroundColor FocusedForegroundColor IsPassword SelectAllTextWhenFocused ClearKeyboardFocusOnCommit SEditableTextBox::SLATE_ATTRIBUTE (ETextJustify::Type , Justification)
How should the value be justified in the editable text field.
Maximum length of the text. Input will refuse text longer than that.
References MaximumLength, and SLATE_ATTRIBUTE().
SLATE_ATTRIBUTE() [8/13]
Text SearchText ForegroundColor FocusedForegroundColor IsPassword SelectAllTextWhenFocused ClearKeyboardFocusOnCommit MaximumLength OnContextMenuOpening OnTextChanged OnVerifyTextChanged SelectAllTextOnCommit OnKeyCharHandler BackgroundColor ErrorReporting VirtualKeyboardOptions SEditableTextBox::SLATE_ATTRIBUTE (EVirtualKeyboardTrigger , VirtualKeyboardTrigger)
The type of event that will trigger the display of the virtual keyboard.
The message action to take when the virtual keyboard is dismissed by the user
References SLATE_ATTRIBUTE().
SLATE_ATTRIBUTE() [9/13]
Text SearchText ForegroundColor FocusedForegroundColor IsPassword SelectAllTextWhenFocused ClearKeyboardFocusOnCommit MaximumLength OnContextMenuOpening OnTextChanged OnVerifyTextChanged SEditableTextBox::SLATE_ATTRIBUTE (float , MinDesiredWidth)
Minimum width that a text block should be.
Whether to select all text when pressing enter to commit changes
References SLATE_ATTRIBUTE().
SLATE_ATTRIBUTE() [10/13]
Text SearchText ForegroundColor FocusedForegroundColor IsPassword SelectAllTextWhenFocused ClearKeyboardFocusOnCommit MaximumLength OnContextMenuOpening OnTextChanged OnVerifyTextChanged SelectAllTextOnCommit OnKeyCharHandler BackgroundColor SEditableTextBox::SLATE_ATTRIBUTE (FMargin , Padding)
Padding between the box/border and the text widget inside (overrides Style)
Provide a alternative mechanism for error reporting.
References ErrorReporting, SBorder::Padding(), SLATE_ARGUMENT(), and SLATE_ATTRIBUTE().
SLATE_ATTRIBUTE() [11/13]
Text SearchText ForegroundColor SEditableTextBox::SLATE_ATTRIBUTE (FSlateColor , ReadOnlyForegroundColor)
Text color and opacity when read-only (overrides Style)
Text color and opacity when this box has keyboard focus (overrides Style)
References SLATE_ATTRIBUTE().
SLATE_ATTRIBUTE() [12/13]
Text SearchText SEditableTextBox::SLATE_ATTRIBUTE (FSlateFontInfo , Font)
Font color and opacity (overrides Style)
Text color and opacity (overrides Style)
References SLATE_ATTRIBUTE().
SLATE_ATTRIBUTE() [13/13]
Text SEditableTextBox::SLATE_ATTRIBUTE (FText , HintText)
Hint text that appears when there is no text in the text box.
Text to search for (a new search is triggered whenever this text changes)
References SLATE_ATTRIBUTE().
Referenced by SLATE_ATTRIBUTE(), SLATE_ATTRIBUTE(), SLATE_ATTRIBUTE(), SLATE_ATTRIBUTE(), SLATE_ATTRIBUTE(), SLATE_ATTRIBUTE(), SLATE_ATTRIBUTE(), SLATE_ATTRIBUTE(), SLATE_ATTRIBUTE(), SLATE_ATTRIBUTE(), SLATE_ATTRIBUTE(), SLATE_ATTRIBUTE(), SLATE_ATTRIBUTE(), and SLATE_EVENT().
SLATE_BEGIN_ARGS()
SEditableTextBox::SLATE_BEGIN_ARGS (SEditableTextBox) inline
Definition at line 33 of file SEditableTextBox.h.
References Left.
SLATE_EVENT() [1/3]
Text SearchText ForegroundColor FocusedForegroundColor IsPassword SelectAllTextWhenFocused ClearKeyboardFocusOnCommit MaximumLength OnContextMenuOpening SEditableTextBox::SLATE_EVENT (FMenuExtensionDelegate , ContextMenuExtender)
Menu extender for the right-click context menu.
Called whenever the text is changed programmatically or interactively by the user
References OnTextChanged, and SLATE_EVENT().
Referenced by SLATE_ATTRIBUTE(), SLATE_ATTRIBUTE(), SLATE_EVENT(), SLATE_EVENT(), and SLATE_EVENT().
SLATE_EVENT() [2/3]
Text SearchText ForegroundColor FocusedForegroundColor IsPassword SelectAllTextWhenFocused ClearKeyboardFocusOnCommit MaximumLength OnContextMenuOpening OnTextChanged OnVerifyTextChanged SelectAllTextOnCommit OnKeyCharHandler SEditableTextBox::SLATE_EVENT (FOnKeyDown , OnKeyDownHandler)
Callback delegate to have first chance handling of the OnKeyDown event.
The color of the background/border around the editable text (overrides Style)
References SLATE_ATTRIBUTE(), and SLATE_EVENT().
SLATE_EVENT() [3/3]
Text SearchText ForegroundColor FocusedForegroundColor IsPassword SelectAllTextWhenFocused ClearKeyboardFocusOnCommit MaximumLength OnContextMenuOpening OnTextChanged SEditableTextBox::SLATE_EVENT (FOnTextCommitted , OnTextCommitted)
Called whenever the text is committed.
This happens when the user presses enter or the text box loses focus. Called whenever the text is changed programmatically or interactively by the user
References OnTextCommitted, OnVerifyTextChanged, and SLATE_EVENT().
SLATE_STYLE_ARGUMENT()
SEditableTextBox::SLATE_STYLE_ARGUMENT (FEditableTextBoxStyle , Style)
The styling of the textbox.
Sets the text content for this editable text box widget
References Style, and Text.
SupportsKeyboardFocus()
virtual bool SEditableTextBox::SupportsKeyboardFocus () const override virtual
Checks to see if this widget supports keyboard focus.
Override this in derived classes.
Returns
True if this widget can take keyboard focus
Reimplemented from SWidget.
Field Documentation
BackgroundColorOverride
TAttribute<FSlateColor> SEditableTextBox::BackgroundColorOverride protected
Background color (overrides style)
Definition at line 448 of file SEditableTextBox.h.
BorderImageFocused
const FSlateBrush* SEditableTextBox::BorderImageFocused private
Styling: border image to draw when focused.
Definition at line 486 of file SEditableTextBox.h.
BorderImageHovered
const FSlateBrush* SEditableTextBox::BorderImageHovered private
Styling: border image to draw when hovered.
Definition at line 484 of file SEditableTextBox.h.
BorderImageNormal
const FSlateBrush* SEditableTextBox::BorderImageNormal private
Styling: border image to draw when not hovered or focused.
Definition at line 482 of file SEditableTextBox.h.
BorderImageReadOnly
const FSlateBrush* SEditableTextBox::BorderImageReadOnly private
Styling: border image to draw when read only.
Definition at line 488 of file SEditableTextBox.h.
Box
TSharedPtr<SHorizontalBox> SEditableTextBox::Box protected
Allows for inserting additional widgets that extend the functionality of the text box.
Definition at line 460 of file SEditableTextBox.h.
EditableText
TSharedPtr< SEditableText > SEditableTextBox::EditableText protected
Editable text widget.
Definition at line 436 of file SEditableTextBox.h.
Referenced by GetHintText(), GetText(), GoTo(), IsPassword(), IsReadOnly(), and ScrollTo().
ErrorReporting
TSharedPtr<class IErrorReportingWidget> SEditableTextBox::ErrorReporting protected
SomeWidget reporting.
Definition at line 463 of file SEditableTextBox.h.
Referenced by SLATE_ATTRIBUTE().
FocusedForegroundColorOverride
TAttribute<FSlateColor> SEditableTextBox::FocusedForegroundColorOverride protected
Focused foreground color (overrides style)
Definition at line 454 of file SEditableTextBox.h.
FontOverride
TAttribute<FSlateFontInfo> SEditableTextBox::FontOverride protected
Font (overrides style)
Definition at line 442 of file SEditableTextBox.h.
ForegroundColorOverride
TAttribute<FSlateColor> SEditableTextBox::ForegroundColorOverride protected
Foreground color (overrides style)
Definition at line 445 of file SEditableTextBox.h.
MaximumLength
TAttribute<int32> SEditableTextBox::MaximumLength protected
Maximum text length that will be accepted by the widget.
Definition at line 457 of file SEditableTextBox.h.
Referenced by SLATE_ATTRIBUTE().
OnTextChanged
FOnTextChanged SEditableTextBox::OnTextChanged protected
Called when the text is changed interactively.
Definition at line 466 of file SEditableTextBox.h.
Referenced by SSearchBox::SLATE_ATTRIBUTE(), and SLATE_EVENT().
OnTextCommitted
FOnTextCommitted SEditableTextBox::OnTextCommitted protected
Called when the user commits their change to the editable text control.
Definition at line 469 of file SEditableTextBox.h.
Referenced by SLATE_EVENT(), and SSearchBox::SLATE_EVENT().
OnVerifyTextChanged
FOnVerifyTextChanged SEditableTextBox::OnVerifyTextChanged protected
Callback to verify text when changed.
Will return an error message to denote problems.
Definition at line 472 of file SEditableTextBox.h.
Referenced by SLATE_EVENT(), and SSearchBox::SLATE_EVENT().
PaddingBox
TSharedPtr< SBox > SEditableTextBox::PaddingBox protected
Box widget that adds padding around the editable text.
Definition at line 433 of file SEditableTextBox.h.
PaddingOverride
TAttribute<FMargin> SEditableTextBox::PaddingOverride protected
Padding (overrides style)
Definition at line 439 of file SEditableTextBox.h.
ReadOnlyForegroundColorOverride
TAttribute<FSlateColor> SEditableTextBox::ReadOnlyForegroundColorOverride protected
Read-only foreground color (overrides style)
Definition at line 451 of file SEditableTextBox.h.
Style
const FEditableTextBoxStyle* SEditableTextBox::Style protected
Definition at line 430 of file SEditableTextBox.h.
Referenced by SLATE_STYLE_ARGUMENT(), and SSearchBox::SLATE_STYLE_ARGUMENT().
The documentation for this class was generated from the following file:
Runtime/Slate/Public/Widgets/Input/SEditableTextBox.h