Unreal Engine 5.6 C++ API: IPixelStreaming2AudioSink Class Reference
IPixelStreaming2AudioSink Class Reference abstract
An "Audio Sink" is an object that receives audio from a singular peer.
#include "IPixelStreaming2AudioSink.h"
Private Member Functions
virtual void AddAudioConsumer (const TWeakPtrVariant< IPixelStreaming2AudioConsumer > &AudioConsumer)=0
GENERATED_BODY () public
Add an audio consumer to the sink.
virtual void RemoveAudioConsumer (const TWeakPtrVariant< IPixelStreaming2AudioConsumer > &AudioConsumer)=0
UE_DEPRECATED (5.6, "RemoveAudioConsumer(IPixelStreaming2AudioConsumer*) has been deprecated. Please use RemoveAudioConsumer(const TWeakPtrVariant<IPixelStreaming2AudioConsumer>&) instead.") virtual void RemoveAudioConsumer(IPixelStreaming2AudioConsumer *AudioConsumer)
Remove an audio consumer to remove from the sink.
Detailed Description
An "Audio Sink" is an object that receives audio from a singular peer.
From here, you can add multiple consumers to output the received audio.
Definition at line 22 of file IPixelStreaming2AudioSink.h.
Member Function Documentation
AddAudioConsumer()
virtual void IPixelStreaming2AudioSink::AddAudioConsumer (const TWeakPtrVariant< IPixelStreaming2AudioConsumer > & AudioConsumer) private pure virtual
Implemented in UE::PixelStreaming2::FAudioSink.
Referenced by GENERATED_BODY().
GENERATED_BODY()
IPixelStreaming2AudioSink::GENERATED_BODY () inline private
Add an audio consumer to the sink.
Parameters
AudioConsumer The Audio consumer to add to the sink.
Definition at line 24 of file IPixelStreaming2AudioSink.h.
References AddAudioConsumer(), and UE_DEPRECATED().
RemoveAudioConsumer()
virtual void IPixelStreaming2AudioSink::RemoveAudioConsumer (const TWeakPtrVariant< IPixelStreaming2AudioConsumer > & AudioConsumer) private pure virtual
Implemented in UE::PixelStreaming2::FAudioSink.
Referenced by UE_DEPRECATED().
UE_DEPRECATED()
IPixelStreaming2AudioSink::UE_DEPRECATED (5. 6, "RemoveAudioConsumer(IPixelStreaming2AudioConsumer*) has been deprecated. Please use RemoveAudioConsumer(const TWeakPtrVariant<IPixelStreaming2AudioConsumer>&) instead.") inline private
Remove an audio consumer to remove from the sink.
Parameters
AudioConsumer The Audio consumer to remove from the sink.
Definition at line 40 of file IPixelStreaming2AudioSink.h.
References RemoveAudioConsumer().
Referenced by GENERATED_BODY().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Media/PixelStreaming2/Source/PixelStreaming2Core/Public/IPixelStreaming2AudioSink.h