Unreal Engine 5.6 C++ API: UInstancedSkinnedMeshComponent Class Reference
UInstancedSkinnedMeshComponent Class Reference abstract
#include "InstancedSkinnedMeshComponent.h"
Public Member Functions
UInstancedSkinnedMeshComponent (FVTableHelper &Helper)
virtual ~UInstancedSkinnedMeshComponent ()
virtual void BeginCacheForCookedPlatformData (const ITargetPlatform *TargetPlatform) override
virtual void BeginDestroy () override
void BuildSceneDesc (FPrimitiveSceneProxyDesc *InSceneProxyDesc, FPrimitiveSceneDesc &OutPrimitiveSceneDesc)
virtual FBoxSphereBounds CalcBounds (const FTransform &LocalToWorld) const override
virtual void ComputeHLODHash (class FHLODHashBuilder &HashBuilder) const override
virtual void CreateRenderState_Concurrent (FRegisterComponentContext *Context) override
virtual FPrimitiveSceneProxy * CreateSceneProxy () override
virtual void DestroyRenderState_Concurrent () override
TArrayView< const struct FAnimBankItem > GetAnimBankItems () const
virtual TStructOnScope< FActorComponentInstanceData > GetComponentInstanceData () const override
void GetCullDistances (int32 &OutStartCullDistance, int32 &OutEndCullDistance) const
bool GetCustomData (FPrimitiveInstanceId InstanceId, TArrayView< float > CustomDataFloats) const
Get all custom data values for specific instance, the size of the array view must match the NumCustomDataFloats.
bool GetInstanceBankIndex (FPrimitiveInstanceId InstanceId, int32 &OutBankIndex) const
Get the bank index for the instance specified.
int32 GetInstanceCount () const
int32 GetInstanceCountGPUOnly () const
const TArray< float > & GetInstanceCustomData () const
const TArray< FSkinnedMeshInstanceData > & GetInstanceData () const
int32 GetMinDrawDistance () const
virtual const Nanite::FResources * GetNaniteResources () const
int32 GetNumCustomDataFloats () const
FBox GetPrimitiveBoundsOverride () const
virtual bool IsCachedCookedPlatformDataLoaded (const ITargetPlatform *TargetPlatform) override
bool IsEnabled () const
virtual bool IsHLODRelevant () const override
virtual void OnRegister () override
virtual void OnUpdateTransform (EUpdateTransformFlags UpdateTransformFlags, ETeleportType Teleport) override
virtual void PostAssetCompilation ()
Called by the asset compilers (FAnimBankCompilingManager / FSkinnedAssetCompilingManager) when done to allow render state to be created.
virtual void PostEditChangeChainProperty (FPropertyChangedChainEvent &PropertyChangedEvent) override
virtual void PostEditUndo () override
virtual void PostLoad () override
virtual void RefreshBoneTransforms (FActorComponentTickFunction *TickFunction=nullptr) override
virtual void SendRenderInstanceData_Concurrent () override
virtual void Serialize (FArchive &Ar) override
void SetAnimBankItems (TArrayView< const struct FAnimBankItem > InAnimBankItems)
void SetCullDistances (int32 StartCullDistance, int32 EndCullDistance)
bool SetCustomData (FPrimitiveInstanceId InstanceId, TArrayView< const float > CustomDataFloats)
Update all custom data values for specific instance, the size of the array view must match the NumCustomDataFloats.
void SetNumGPUInstances (int32 InCount)
void SetPrimitiveBoundsOverride (const FBox &InBounds)
virtual void TickComponent (float DeltaTime, enum ELevelTick TickType, FActorComponentTickFunction *ThisTickFunction) override
UFUNCTION () 1 bool GetInstanceTransform(FPrimitiveInstanceId InstanceId
Get the transform for the instance specified.
UFUNCTION () 1 bool RemoveInstance(FPrimitiveInstanceId InstanceId)
Remove the instance specified.
UFUNCTION () 1 bool SetCustomDataValue(FPrimitiveInstanceId InstanceId
Update custom data for specific instance.
UFUNCTION () 1 FPrimitiveInstanceId AddInstance(const FTransform &InstanceTransform
Add an instance to this component.
UFUNCTION () 1 int32 AddAnimBankItem(const FAnimBankItem &BankItem)
UFUNCTION () 1 TArray< FPrimitiveInstanceId > AddInstances(const TArray< FTransform > &Transforms
Add multiple instances to this component.
UFUNCTION () 1 void ClearInstances()
Clear all instances being rendered by this component.
UFUNCTION () 1 void OptimizeInstanceData(bool bShouldRetainIdMap
Optimize the instance data by performing sorting according to spatial hash on the source data.
UFUNCTION () 1 void RemoveInstances(const TArray< FPrimitiveInstanceId > &InstancesToRemove)
Remove the instances specified.
UFUNCTION () 1 void SetNumCustomDataFloats(int32 InNumCustomDataFloats)
Update number of custom data entries per instance.
bool UsesGPUOnlyInstances () const
Data Fields
int32 BankIndex
const TArray< int32 > & BankIndices
const TArray< int32 > bool bShouldReturnIds
int32 bool bWorldSpace = false)
const TArray< int32 > bool bool bWorldSpace = false)
FTransform bool bWorldSpace = false) const
int32 CustomDataIndex
int32 float CustomDataValue
FTransform & OutInstanceTransform
Protected Member Functions
FPrimitiveInstanceId AddInstanceInternal (int32 InstanceIndex, const FTransform &InstanceTransform, int32 BankIndex, bool bWorldSpace)
void ApplyComponentInstanceData (struct FInstancedSkinnedMeshComponentInstanceData *ComponentInstanceData)
Applies the cached component instance data to a newly blueprint constructed component.
void CreateHitProxyData (TArray< TRefCountPtr< HHitProxy > > &HitProxies)
FInstanceDataManagerSourceDataDesc GetComponentDesc (ERHIFeatureLevel::Type FeatureLevel)
void PreApplyComponentInstanceData (struct FInstancedSkinnedMeshComponentInstanceData *ComponentInstanceData)
Handle changes that must happen before the proxy is recreated.
bool RemoveInstanceInternal (int32 InstanceIndex, bool InstanceAlreadyRemoved)
Protected Attributes
bool bIsInstanceDataApplyCompleted = true
TBitArray SelectedInstances
One bit per instance if the instance is selected.
Private Member Functions
void ApplyInheritedPerInstanceData (const UInstancedSkinnedMeshComponent *InArchetype)
TSharedPtr< FInstanceDataSceneProxy, ESPMode::ThreadSafe > CreateInstanceDataProxyGPUOnly () const
TSharedPtr< FInstanceDataSceneProxy, ESPMode::ThreadSafe > GetInstanceDataSceneProxy () const
TSharedPtr< FInstanceDataSceneProxy, ESPMode::ThreadSafe > GetOrCreateInstanceDataSceneProxy ()
void SetInstanceDataGPUOnly (bool bInInstancesGPUOnly)
void SetSkinnedAssetCallback ()
void SetupNewInstanceData (FSkinnedMeshInstanceData &InOutNewInstanceData, int32 InInstanceIndex, const FTransform3f &InInstanceTransform, int32 BankIndex)
Sets up new instance data to sensible defaults, creates physics counterparts if possible.
bool ShouldInheritPerInstanceData () const
bool ShouldInheritPerInstanceData (const UInstancedSkinnedMeshComponent *InArchetype) const
UPROPERTY () bool bIsInstanceDataGPUOnly
UPROPERTY () FBox PrimitiveBoundsOverride
UPROPERTY () float AnimationMinScreenSize=0.0f
Screen space footprint (in primary view) cutoff which dictates the far distance the instance will play back animation.
UPROPERTY () int32 InstanceEndCullDistance
Distance from camera at which each instance completely fades out.
UPROPERTY () int32 InstanceMinDrawDistance
Distance from camera at which each instance begins to draw.
UPROPERTY () int32 InstanceStartCullDistance
Distance from camera at which each instance begins to fade out.
GENERATED_UCLASS_BODY() protected UPROPERTY () int32 NumCustomDataFloats=0
Array of instances, bulk serialized.
UPROPERTY () int32 NumInstancesGPUOnly=0
UPROPERTY ()) TArray< float > InstanceCustomData
Array of custom data for instances.
UPROPERTY() uint8 bInheritPerInstanceData UPROPERTY ()) TArray< struct FAnimBankItem > AnimBankItems
If true, this component will avoid serializing its per instance data / those properties will also not be editable.
Static Private Member Functions
static FSkeletalMeshObject * CreateMeshObject (const FInstancedSkinnedMeshSceneProxyDesc &InMeshDesc, TConstArrayView< FAnimBankItem > InAnimBankItems, FSkeletalMeshRenderData *InRenderData, ERHIFeatureLevel::Type InFeatureLevel)
static FPrimitiveSceneProxy * CreateSceneProxy (const FInstancedSkinnedMeshSceneProxyDesc &Desc, bool bHideSkin, bool bShouldNaniteSkin, bool bIsEnabled, int32 MinLODIndex)
static bool ShouldForceRefPose ()
static bool ShouldUseSampledBounds ()
Private Attributes
FInstanceDataManager InstanceDataManager
Friends
class FInstancedSkinnedMeshComponentHelper
struct FInstancedSkinnedMeshComponentInstanceData
class FInstancedSkinnedMeshObject
class FInstancedSkinnedMeshSceneProxy
struct FInstancedSkinnedMeshSceneProxyDesc
struct FSkinnedMeshComponentDescriptorBase
Detailed Description
Definition at line 54 of file InstancedSkinnedMeshComponent.h.
Constructor & Destructor Documentation
UInstancedSkinnedMeshComponent()
UInstancedSkinnedMeshComponent::UInstancedSkinnedMeshComponent (FVTableHelper & Helper)
References UInstancedSkinnedMeshComponent().
Referenced by UInstancedSkinnedMeshComponent(), ~UInstancedSkinnedMeshComponent(), ApplyInheritedPerInstanceData(), and ShouldInheritPerInstanceData().
~UInstancedSkinnedMeshComponent()
virtual UInstancedSkinnedMeshComponent::~UInstancedSkinnedMeshComponent () virtual
References UInstancedSkinnedMeshComponent().
Member Function Documentation
AddInstanceInternal()
FPrimitiveInstanceId UInstancedSkinnedMeshComponent::AddInstanceInternal (int32 InstanceIndex, const FTransform & InstanceTransform, int32 BankIndex, bool bWorldSpace) protected
References BankIndex, and bWorldSpace.
ApplyComponentInstanceData()
void UInstancedSkinnedMeshComponent::ApplyComponentInstanceData (struct FInstancedSkinnedMeshComponentInstanceData * ComponentInstanceData) protected
Applies the cached component instance data to a newly blueprint constructed component.
References FInstancedSkinnedMeshComponentInstanceData.
ApplyInheritedPerInstanceData()
void UInstancedSkinnedMeshComponent::ApplyInheritedPerInstanceData (const UInstancedSkinnedMeshComponent * InArchetype) private
References UInstancedSkinnedMeshComponent().
BeginCacheForCookedPlatformData()
virtual void UInstancedSkinnedMeshComponent::BeginCacheForCookedPlatformData (const ITargetPlatform * TargetPlatform) override virtual
BeginDestroy()
virtual void UInstancedSkinnedMeshComponent::BeginDestroy () override virtual
References BeginDestroy().
Referenced by BeginDestroy().
BuildSceneDesc()
void UInstancedSkinnedMeshComponent::BuildSceneDesc (FPrimitiveSceneProxyDesc * InSceneProxyDesc, FPrimitiveSceneDesc & OutPrimitiveSceneDesc)
CalcBounds()
virtual FBoxSphereBounds UInstancedSkinnedMeshComponent::CalcBounds (const FTransform & LocalToWorld) const override virtual
ComputeHLODHash()
virtual void UInstancedSkinnedMeshComponent::ComputeHLODHash (class FHLODHashBuilder & HashBuilder) const override virtual
CreateHitProxyData()
void UInstancedSkinnedMeshComponent::CreateHitProxyData (TArray< TRefCountPtr< HHitProxy > > & HitProxies) protected
CreateInstanceDataProxyGPUOnly()
TSharedPtr< FInstanceDataSceneProxy, ESPMode::ThreadSafe > UInstancedSkinnedMeshComponent::CreateInstanceDataProxyGPUOnly () const private
CreateMeshObject()
FSkeletalMeshObject * UInstancedSkinnedMeshComponent::CreateMeshObject (const FInstancedSkinnedMeshSceneProxyDesc & InMeshDesc, TConstArrayView< FAnimBankItem > InAnimBankItems, FSkeletalMeshRenderData * InRenderData, ERHIFeatureLevel::Type InFeatureLevel) static private
References FInstancedSkinnedMeshSceneProxyDesc.
Referenced by FInstancedSkinnedMeshComponentHelper::CreateMeshObject().
CreateRenderState_Concurrent()
virtual void UInstancedSkinnedMeshComponent::CreateRenderState_Concurrent (FRegisterComponentContext * Context) override virtual
CreateSceneProxy() [1/2]
virtual FPrimitiveSceneProxy * UInstancedSkinnedMeshComponent::CreateSceneProxy () override virtual
Referenced by FInstancedSkinnedMeshComponentHelper::CreateSceneProxy().
CreateSceneProxy() [2/2]
FPrimitiveSceneProxy * UInstancedSkinnedMeshComponent::CreateSceneProxy (const FInstancedSkinnedMeshSceneProxyDesc & Desc, bool bHideSkin, bool bShouldNaniteSkin, bool bIsEnabled, int32 MinLODIndex) static private
References FInstancedSkinnedMeshSceneProxyDesc.
DestroyRenderState_Concurrent()
virtual void UInstancedSkinnedMeshComponent::DestroyRenderState_Concurrent () override virtual
GetAnimBankItems()
TArrayView< const struct FAnimBankItem > UInstancedSkinnedMeshComponent::GetAnimBankItems () const
References GetAnimBankItems().
Referenced by GetAnimBankItems().
GetComponentDesc()
FInstanceDataManagerSourceDataDesc UInstancedSkinnedMeshComponent::GetComponentDesc (ERHIFeatureLevel::Type FeatureLevel) protected
GetComponentInstanceData()
virtual TStructOnScope< FActorComponentInstanceData > UInstancedSkinnedMeshComponent::GetComponentInstanceData () const override virtual
GetCullDistances()
void UInstancedSkinnedMeshComponent::GetCullDistances (int32 & OutStartCullDistance, int32 & OutEndCullDistance) const inline
Definition at line 233 of file InstancedSkinnedMeshComponent.h.
GetCustomData()
bool UInstancedSkinnedMeshComponent::GetCustomData (FPrimitiveInstanceId InstanceId, TArrayView< float > CustomDataFloats) const
Get all custom data values for specific instance, the size of the array view must match the NumCustomDataFloats.
Returns True on success.
References GetCustomData().
Referenced by GetCustomData().
GetInstanceBankIndex()
bool UInstancedSkinnedMeshComponent::GetInstanceBankIndex (FPrimitiveInstanceId InstanceId, int32 & OutBankIndex) const
Get the bank index for the instance specified.
Returns True on success.
References GetInstanceBankIndex().
Referenced by GetInstanceBankIndex().
GetInstanceCount()
int32 UInstancedSkinnedMeshComponent::GetInstanceCount () const
References GetInstanceCount().
Referenced by GetInstanceCount().
GetInstanceCountGPUOnly()
int32 UInstancedSkinnedMeshComponent::GetInstanceCountGPUOnly () const inline
Definition at line 230 of file InstancedSkinnedMeshComponent.h.
GetInstanceCustomData()
const TArray< float > & UInstancedSkinnedMeshComponent::GetInstanceCustomData () const inline
Definition at line 227 of file InstancedSkinnedMeshComponent.h.
GetInstanceData()
const TArray< FSkinnedMeshInstanceData > & UInstancedSkinnedMeshComponent::GetInstanceData () const inline
Definition at line 228 of file InstancedSkinnedMeshComponent.h.
GetInstanceDataSceneProxy()
TSharedPtr< FInstanceDataSceneProxy, ESPMode::ThreadSafe > UInstancedSkinnedMeshComponent::GetInstanceDataSceneProxy () const private
GetMinDrawDistance()
int32 UInstancedSkinnedMeshComponent::GetMinDrawDistance () const inline
Definition at line 232 of file InstancedSkinnedMeshComponent.h.
GetNaniteResources()
virtual const Nanite::FResources * UInstancedSkinnedMeshComponent::GetNaniteResources () const virtual
GetNumCustomDataFloats()
int32 UInstancedSkinnedMeshComponent::GetNumCustomDataFloats () const inline
Definition at line 226 of file InstancedSkinnedMeshComponent.h.
References GetNumCustomDataFloats().
Referenced by GetNumCustomDataFloats().
GetOrCreateInstanceDataSceneProxy()
TSharedPtr< FInstanceDataSceneProxy, ESPMode::ThreadSafe > UInstancedSkinnedMeshComponent::GetOrCreateInstanceDataSceneProxy () private
GetPrimitiveBoundsOverride()
FBox UInstancedSkinnedMeshComponent::GetPrimitiveBoundsOverride () const inline
Definition at line 164 of file InstancedSkinnedMeshComponent.h.
IsCachedCookedPlatformDataLoaded()
virtual bool UInstancedSkinnedMeshComponent::IsCachedCookedPlatformDataLoaded (const ITargetPlatform * TargetPlatform) override virtual
IsEnabled()
bool UInstancedSkinnedMeshComponent::IsEnabled () const
References IsEnabled().
Referenced by IsEnabled().
IsHLODRelevant()
virtual bool UInstancedSkinnedMeshComponent::IsHLODRelevant () const override virtual
OnRegister()
virtual void UInstancedSkinnedMeshComponent::OnRegister () override virtual
OnUpdateTransform()
virtual void UInstancedSkinnedMeshComponent::OnUpdateTransform (EUpdateTransformFlags UpdateTransformFlags, ETeleportType Teleport) override virtual
PostAssetCompilation()
virtual void UInstancedSkinnedMeshComponent::PostAssetCompilation () virtual
Called by the asset compilers (FAnimBankCompilingManager / FSkinnedAssetCompilingManager) when done to allow render state to be created.
PostEditChangeChainProperty()
virtual void UInstancedSkinnedMeshComponent::PostEditChangeChainProperty (FPropertyChangedChainEvent & PropertyChangedEvent) override virtual
PostEditUndo()
virtual void UInstancedSkinnedMeshComponent::PostEditUndo () override virtual
PostLoad()
virtual void UInstancedSkinnedMeshComponent::PostLoad () override virtual
References PostLoad().
Referenced by PostLoad().
PreApplyComponentInstanceData()
void UInstancedSkinnedMeshComponent::PreApplyComponentInstanceData (struct FInstancedSkinnedMeshComponentInstanceData * ComponentInstanceData) protected
Handle changes that must happen before the proxy is recreated.
References FInstancedSkinnedMeshComponentInstanceData.
RefreshBoneTransforms()
virtual void UInstancedSkinnedMeshComponent::RefreshBoneTransforms (FActorComponentTickFunction * TickFunction = nullptr) override virtual
RemoveInstanceInternal()
bool UInstancedSkinnedMeshComponent::RemoveInstanceInternal (int32 InstanceIndex, bool InstanceAlreadyRemoved) protected
SendRenderInstanceData_Concurrent()
virtual void UInstancedSkinnedMeshComponent::SendRenderInstanceData_Concurrent () override virtual
Serialize()
virtual void UInstancedSkinnedMeshComponent::Serialize (FArchive & Ar) override virtual
References Ar, and Serialize().
Referenced by Serialize().
SetAnimBankItems()
void UInstancedSkinnedMeshComponent::SetAnimBankItems (TArrayView< const struct FAnimBankItem > InAnimBankItems)
References SetAnimBankItems().
Referenced by SetAnimBankItems().
SetCullDistances()
void UInstancedSkinnedMeshComponent::SetCullDistances (int32 StartCullDistance, int32 EndCullDistance)
SetCustomData()
bool UInstancedSkinnedMeshComponent::SetCustomData (FPrimitiveInstanceId InstanceId, TArrayView< const float > CustomDataFloats)
Update all custom data values for specific instance, the size of the array view must match the NumCustomDataFloats.
Returns True on success.
References SetCustomData().
Referenced by SetCustomData().
SetInstanceDataGPUOnly()
void UInstancedSkinnedMeshComponent::SetInstanceDataGPUOnly (bool bInInstancesGPUOnly) private
SetNumGPUInstances()
void UInstancedSkinnedMeshComponent::SetNumGPUInstances (int32 InCount)
SetPrimitiveBoundsOverride()
void UInstancedSkinnedMeshComponent::SetPrimitiveBoundsOverride (const FBox & InBounds) inline
Definition at line 165 of file InstancedSkinnedMeshComponent.h.
SetSkinnedAssetCallback()
void UInstancedSkinnedMeshComponent::SetSkinnedAssetCallback () private
SetupNewInstanceData()
void UInstancedSkinnedMeshComponent::SetupNewInstanceData (FSkinnedMeshInstanceData & InOutNewInstanceData, int32 InInstanceIndex, const FTransform3f & InInstanceTransform, int32 BankIndex) private
Sets up new instance data to sensible defaults, creates physics counterparts if possible.
References BankIndex.
ShouldForceRefPose()
bool UInstancedSkinnedMeshComponent::ShouldForceRefPose () static private
Referenced by FInstancedSkinnedMeshComponentHelper::GetComponentDesc().
ShouldInheritPerInstanceData() [1/2]
bool UInstancedSkinnedMeshComponent::ShouldInheritPerInstanceData () const private
ShouldInheritPerInstanceData() [2/2]
bool UInstancedSkinnedMeshComponent::ShouldInheritPerInstanceData (const UInstancedSkinnedMeshComponent * InArchetype) const private
References UInstancedSkinnedMeshComponent().
ShouldUseSampledBounds()
bool UInstancedSkinnedMeshComponent::ShouldUseSampledBounds () static private
Referenced by FInstancedSkinnedMeshComponentHelper::CalcBounds().
TickComponent()
virtual void UInstancedSkinnedMeshComponent::TickComponent (float DeltaTime, enum ELevelTick TickType, FActorComponentTickFunction * ThisTickFunction) override virtual
References DeltaTime.
UFUNCTION() [1/10]
UInstancedSkinnedMeshComponent::UFUNCTION ()
Get the transform for the instance specified.
Instance is returned in local space of this component unless bWorldSpace is set. Returns True on success.
References Category, and UFUNCTION().
UFUNCTION() [2/10]
UInstancedSkinnedMeshComponent::UFUNCTION ()
Remove the instance specified.
Returns True on success.
References Category, and UFUNCTION().
UFUNCTION() [3/10]
UInstancedSkinnedMeshComponent::UFUNCTION ()
Update custom data for specific instance.
References Category, and UFUNCTION().
UFUNCTION() [4/10]
UInstancedSkinnedMeshComponent::UFUNCTION () const &
Add an instance to this component.
Transform is given in local space of this component unless bWorldSpace is set.
References Category.
Referenced by UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
UFUNCTION() [5/10]
UInstancedSkinnedMeshComponent::UFUNCTION () const &
References Category, and UFUNCTION().
UFUNCTION() [6/10]
UInstancedSkinnedMeshComponent::UFUNCTION () const &
Add multiple instances to this component.
Transform is given in local space of this component unless bWorldSpace is set.
References Category, and UFUNCTION().
UFUNCTION() [7/10]
UInstancedSkinnedMeshComponent::UFUNCTION ()
Clear all instances being rendered by this component.
References Category, and UFUNCTION().
UFUNCTION() [8/10]
UInstancedSkinnedMeshComponent::UFUNCTION ()
Optimize the instance data by performing sorting according to spatial hash on the source data.
Note that this reorders the instances and thus any indexing will change. By default resets the ID mapping to identity.
Parameters
bShouldRetainIdMap If true, the id mapping is updated instead of reset to identity, this retains the validity of the IDs but adds some memory and storage cost (for the ID mapping).
References Category, and UFUNCTION().
UFUNCTION() [9/10]
UInstancedSkinnedMeshComponent::UFUNCTION () const &
Remove the instances specified.
Returns True on success.
References Category, and UFUNCTION().
UFUNCTION() [10/10]
UInstancedSkinnedMeshComponent::UFUNCTION ()
Update number of custom data entries per instance.
This applies to all instances and will reallocate the full custom data buffer and reset all values to 0
References Category, and UFUNCTION().
UPROPERTY() [1/10]
UInstancedSkinnedMeshComponent::UPROPERTY () private
References UPROPERTY().
UPROPERTY() [2/10]
UInstancedSkinnedMeshComponent::UPROPERTY () private
References UPROPERTY().
UPROPERTY() [3/10]
UInstancedSkinnedMeshComponent::UPROPERTY () private pure virtual
Screen space footprint (in primary view) cutoff which dictates the far distance the instance will play back animation.
Using 0.0 (the default) falls back to a global threshold, a negative value disables the cutoff.
References Animation, and Category.
UPROPERTY() [4/10]
UInstancedSkinnedMeshComponent::UPROPERTY () private
Distance from camera at which each instance completely fades out.
References Category.
UPROPERTY() [5/10]
UInstancedSkinnedMeshComponent::UPROPERTY () private
Distance from camera at which each instance begins to draw.
References Category.
UPROPERTY() [6/10]
UInstancedSkinnedMeshComponent::UPROPERTY () private
Distance from camera at which each instance begins to fade out.
References Category.
UPROPERTY() [7/10]
GENERATED_UCLASS_BODY() protected UInstancedSkinnedMeshComponent::UPROPERTY () private pure virtual
Array of instances, bulk serialized.
Defines the number of floats that will be available per instance for custom data
References Category.
Referenced by UPROPERTY(), UPROPERTY(), UPROPERTY(), and UPROPERTY().
UPROPERTY() [8/10]
UInstancedSkinnedMeshComponent::UPROPERTY () private pure virtual
References UPROPERTY().
UPROPERTY() [9/10]
UInstancedSkinnedMeshComponent::UPROPERTY () private
Array of custom data for instances.
This will contains NumCustomDataFloats*InstanceCount entries. The entries are represented sequantially, in instance order. Can be read in a material and manipulated through Blueprints. Example: If NumCustomDataFloats is 1, then each entry will belong to an instance. Custom data 0 will belong to Instance 0. Custom data 1 will belong to Instance 1 etc. Example: If NumCustomDataFloats is 2, then each pair of sequential entries belong to an instance. Custom data 0 and 1 will belong to Instance 0. Custom data 2 and 3 will belong to Instance 2 etc.
References Category, and meta.
UPROPERTY() [10/10]
UPROPERTY() uint8 bInheritPerInstanceData UInstancedSkinnedMeshComponent::UPROPERTY () private
If true, this component will avoid serializing its per instance data / those properties will also not be editable.
References Animation, Category, meta, and UPROPERTY().
UsesGPUOnlyInstances()
bool UInstancedSkinnedMeshComponent::UsesGPUOnlyInstances () const inline
Definition at line 162 of file InstancedSkinnedMeshComponent.h.
Friends And Related Symbol Documentation
FInstancedSkinnedMeshComponentHelper
friend class FInstancedSkinnedMeshComponentHelper friend
Definition at line 288 of file InstancedSkinnedMeshComponent.h.
References FInstancedSkinnedMeshComponentHelper.
Referenced by FInstancedSkinnedMeshComponentHelper.
FInstancedSkinnedMeshComponentInstanceData
friend struct FInstancedSkinnedMeshComponentInstanceData friend
Definition at line 289 of file InstancedSkinnedMeshComponent.h.
References FInstancedSkinnedMeshComponentInstanceData.
Referenced by ApplyComponentInstanceData(), FInstancedSkinnedMeshComponentInstanceData, and PreApplyComponentInstanceData().
FInstancedSkinnedMeshObject
friend class FInstancedSkinnedMeshObject friend
Definition at line 287 of file InstancedSkinnedMeshComponent.h.
References FInstancedSkinnedMeshObject.
Referenced by FInstancedSkinnedMeshObject.
FInstancedSkinnedMeshSceneProxy
friend class FInstancedSkinnedMeshSceneProxy friend
Definition at line 286 of file InstancedSkinnedMeshComponent.h.
References FInstancedSkinnedMeshSceneProxy.
Referenced by FInstancedSkinnedMeshSceneProxy.
FInstancedSkinnedMeshSceneProxyDesc
friend struct FInstancedSkinnedMeshSceneProxyDesc friend
Definition at line 290 of file InstancedSkinnedMeshComponent.h.
References FInstancedSkinnedMeshSceneProxyDesc.
Referenced by CreateMeshObject(), CreateSceneProxy(), and FInstancedSkinnedMeshSceneProxyDesc.
FSkinnedMeshComponentDescriptorBase
friend struct FSkinnedMeshComponentDescriptorBase friend
Definition at line 291 of file InstancedSkinnedMeshComponent.h.
References FSkinnedMeshComponentDescriptorBase.
Referenced by FSkinnedMeshComponentDescriptorBase.
Field Documentation
BankIndex
int32 UInstancedSkinnedMeshComponent::BankIndex
Definition at line 169 of file InstancedSkinnedMeshComponent.h.
Referenced by AddInstanceInternal(), and SetupNewInstanceData().
BankIndices
const TArray<int32>& UInstancedSkinnedMeshComponent::BankIndices
Definition at line 173 of file InstancedSkinnedMeshComponent.h.
bIsInstanceDataApplyCompleted
bool UInstancedSkinnedMeshComponent::bIsInstanceDataApplyCompleted = true protected
Definition at line 250 of file InstancedSkinnedMeshComponent.h.
bShouldReturnIds
const TArray<int32> bool UInstancedSkinnedMeshComponent::bShouldReturnIds
Definition at line 173 of file InstancedSkinnedMeshComponent.h.
bWorldSpace [1/3]
int32 bool UInstancedSkinnedMeshComponent::bWorldSpace = false)
Definition at line 169 of file InstancedSkinnedMeshComponent.h.
Referenced by AddInstanceInternal().
bWorldSpace [2/3]
const TArray<int32> bool bool UInstancedSkinnedMeshComponent::bWorldSpace = false)
Definition at line 173 of file InstancedSkinnedMeshComponent.h.
bWorldSpace [3/3]
FTransform bool UInstancedSkinnedMeshComponent::bWorldSpace = false) const
Definition at line 191 of file InstancedSkinnedMeshComponent.h.
CustomDataIndex
int32 UInstancedSkinnedMeshComponent::CustomDataIndex
Definition at line 177 of file InstancedSkinnedMeshComponent.h.
CustomDataValue
int32 float UInstancedSkinnedMeshComponent::CustomDataValue
Definition at line 177 of file InstancedSkinnedMeshComponent.h.
InstanceDataManager
FInstanceDataManager UInstancedSkinnedMeshComponent::InstanceDataManager private
Definition at line 284 of file InstancedSkinnedMeshComponent.h.
OutInstanceTransform
FTransform& UInstancedSkinnedMeshComponent::OutInstanceTransform
Definition at line 191 of file InstancedSkinnedMeshComponent.h.
SelectedInstances
TBitArray UInstancedSkinnedMeshComponent::SelectedInstances protected
One bit per instance if the instance is selected.
Definition at line 247 of file InstancedSkinnedMeshComponent.h.
The documentation for this class was generated from the following file:
Runtime/Engine/Classes/Components/InstancedSkinnedMeshComponent.h