Unreal Engine 5.6 C++ API: FNavigationReply Class Reference
FNavigationReply Class Reference
A FNavigationReply is something that a Slate navigation event returns to the system to notify it about the boundary rules for navigation.
#include "NavigationReply.h"
Public Member Functions
EUINavigationRule GetBoundaryRule () const
Get the navigation boundary rule.
const FNavigationDelegate & GetFocusDelegate () const
If the event replied with a delegate explicit boundary rule this returns the delegate to get the focus recipient.
const TSharedPtr< SWidget > & GetFocusRecipient () const
If the event replied with a constant explicit boundary rule this returns the desired focus recipient.
const TSharedPtr< SWidget > GetHandler () const
The widget that ultimately specified the boundary rule for the navigation.
Static Public Member Functions
static FNavigationReply Custom (const FNavigationDelegate &InFocusDelegate)
An event should return a FNavigationReply::Custom() to let the system know to call a custom delegate to get the widget to navigate to.
static FNavigationReply CustomBoundary (const FNavigationDelegate &InFocusDelegate)
An event should return a FNavigationReply::CustomBoundary() to let the system know to call a custom delegate to get the widget to navigate to is the widgets boundary is hit.
static FNavigationReply Escape ()
An event should return a FNavigationReply::Escape() to let the system know that a navigation can escape the bounds of this widget.
static FNavigationReply Explicit (TSharedPtr< SWidget > InFocusRecipient)
An event should return a FNavigationReply::Explicit() to let the system know to navigate to an explicit widget at the bounds of this widget.
static FNavigationReply Stop ()
An event should return a FNavigationReply::Stop() to let the system know to stop at the bounds of this widget.
static FNavigationReply Wrap ()
An event should return a FNavigationReply::Wrap() to let the system know to wrap at the bounds of this widget.
Private Member Functions
FNavigationReply ()
Hidden default constructor.
FNavigationReply (EUINavigationRule InBoundaryRule, TSharedPtr< SWidget > InFocusRecipient, const FNavigationDelegate &InFocusDelegate)
Verbose Constructor.
FNavigationReply & SetHandler (const TSharedRef< SWidget > &InHandler)
Set the widget that handled the event; undefined if never handled.
Private Attributes
EUINavigationRule BoundaryRule
TSharedPtr< SWidget > EventHandler
FNavigationDelegate FocusDelegate
TSharedPtr< SWidget > FocusRecipient
Friends
class FSlateApplication
class FSlateNavigationEventSimulator
class SWidget
Detailed Description
A FNavigationReply is something that a Slate navigation event returns to the system to notify it about the boundary rules for navigation.
For example, a widget may handle an OnNavigate event by asking the system to wrap if it's boundary is hit. To do this, return FNavigationReply::Wrap().
Definition at line 42 of file NavigationReply.h.
Constructor & Destructor Documentation
FNavigationReply() [1/2]
FNavigationReply::FNavigationReply () inline private
Hidden default constructor.
Definition at line 135 of file NavigationReply.h.
References BoundaryRule, Escape(), EventHandler, FocusDelegate, and FocusRecipient.
Referenced by Custom(), CustomBoundary(), Escape(), Explicit(), SetHandler(), Stop(), and Wrap().
FNavigationReply() [2/2]
FNavigationReply::FNavigationReply (EUINavigationRule InBoundaryRule, TSharedPtr< SWidget > InFocusRecipient, const FNavigationDelegate & InFocusDelegate) inline private
Verbose Constructor.
Used by SWidget when constructing from MetaData.
Definition at line 145 of file NavigationReply.h.
References BoundaryRule, EventHandler, FocusDelegate, and FocusRecipient.
Member Function Documentation
Custom()
FNavigationReply FNavigationReply::Custom (const FNavigationDelegate & InFocusDelegate) inline static
An event should return a FNavigationReply::Custom() to let the system know to call a custom delegate to get the widget to navigate to.
Definition at line 74 of file NavigationReply.h.
References FNavigationReply(), BoundaryRule, and FocusDelegate.
CustomBoundary()
FNavigationReply FNavigationReply::CustomBoundary (const FNavigationDelegate & InFocusDelegate) inline static
An event should return a FNavigationReply::CustomBoundary() to let the system know to call a custom delegate to get the widget to navigate to is the widgets boundary is hit.
Definition at line 85 of file NavigationReply.h.
References FNavigationReply(), BoundaryRule, and FocusDelegate.
Escape()
FNavigationReply FNavigationReply::Escape () inline static
An event should return a FNavigationReply::Escape() to let the system know that a navigation can escape the bounds of this widget.
Definition at line 116 of file NavigationReply.h.
References FNavigationReply(), and BoundaryRule.
Referenced by FNavigationReply().
Explicit()
FNavigationReply FNavigationReply::Explicit (TSharedPtr< SWidget > InFocusRecipient) inline static
An event should return a FNavigationReply::Explicit() to let the system know to navigate to an explicit widget at the bounds of this widget.
Definition at line 63 of file NavigationReply.h.
References FNavigationReply(), BoundaryRule, and FocusRecipient.
Referenced by SListView< TSharedPtr< FString > >::OnNavigation(), and STileView< ItemType >::OnNavigation().
GetBoundaryRule()
EUINavigationRule FNavigationReply::GetBoundaryRule () const inline
Get the navigation boundary rule.
Definition at line 50 of file NavigationReply.h.
References BoundaryRule.
GetFocusDelegate()
const FNavigationDelegate & FNavigationReply::GetFocusDelegate () const inline
If the event replied with a delegate explicit boundary rule this returns the delegate to get the focus recipient.
Delegate will be unbound if a constant widget was provided.
Definition at line 56 of file NavigationReply.h.
References FocusDelegate.
GetFocusRecipient()
const TSharedPtr< SWidget > & FNavigationReply::GetFocusRecipient () const inline
If the event replied with a constant explicit boundary rule this returns the desired focus recipient.
Otherwise returns an invalid pointer.
Definition at line 53 of file NavigationReply.h.
References FocusRecipient.
GetHandler()
const TSharedPtr< SWidget > FNavigationReply::GetHandler () const inline
The widget that ultimately specified the boundary rule for the navigation.
Definition at line 47 of file NavigationReply.h.
References EventHandler.
SetHandler()
FNavigationReply & FNavigationReply::SetHandler (const TSharedRef< SWidget > & InHandler) inline private
Set the widget that handled the event; undefined if never handled.
This method is to be used by SlateApplication only!
Definition at line 126 of file NavigationReply.h.
References FNavigationReply(), and EventHandler.
Stop()
FNavigationReply FNavigationReply::Stop () inline static
An event should return a FNavigationReply::Stop() to let the system know to stop at the bounds of this widget.
Definition at line 106 of file NavigationReply.h.
References FNavigationReply(), and BoundaryRule.
Referenced by ISlateViewport::OnNavigation().
Wrap()
FNavigationReply FNavigationReply::Wrap () inline static
An event should return a FNavigationReply::Wrap() to let the system know to wrap at the bounds of this widget.
Definition at line 96 of file NavigationReply.h.
References FNavigationReply(), and BoundaryRule.
Friends And Related Symbol Documentation
FSlateApplication
friend class FSlateApplication friend
Definition at line 159 of file NavigationReply.h.
References FSlateApplication.
Referenced by FSlateApplication.
FSlateNavigationEventSimulator
friend class FSlateNavigationEventSimulator friend
Definition at line 160 of file NavigationReply.h.
References FSlateNavigationEventSimulator.
Referenced by FSlateNavigationEventSimulator.
SWidget
friend class SWidget friend
Definition at line 161 of file NavigationReply.h.
References SWidget.
Referenced by SWidget.
Field Documentation
BoundaryRule
EUINavigationRule FNavigationReply::BoundaryRule private
Definition at line 157 of file NavigationReply.h.
Referenced by FNavigationReply(), FNavigationReply(), Custom(), CustomBoundary(), Escape(), Explicit(), GetBoundaryRule(), Stop(), and Wrap().
EventHandler
TSharedPtr<SWidget> FNavigationReply::EventHandler private
Definition at line 154 of file NavigationReply.h.
Referenced by FNavigationReply(), FNavigationReply(), GetHandler(), and SetHandler().
FocusDelegate
FNavigationDelegate FNavigationReply::FocusDelegate private
Definition at line 156 of file NavigationReply.h.
Referenced by FNavigationReply(), FNavigationReply(), Custom(), CustomBoundary(), and GetFocusDelegate().
FocusRecipient
TSharedPtr<SWidget> FNavigationReply::FocusRecipient private
Definition at line 155 of file NavigationReply.h.
Referenced by FNavigationReply(), FNavigationReply(), Explicit(), and GetFocusRecipient().
The documentation for this class was generated from the following file:
Runtime/SlateCore/Public/Input/NavigationReply.h