Unreal Engine 5.6 C++ API: USoundfieldEndpointSubmix Class Reference
USoundfieldEndpointSubmix Class Reference
#include "SoundSubmix.h"
Public Member Functions
bool RecurseCheckChild (const USoundSubmix *ChildSoundSubmix) const
void SanitizeLinks ()
UPROPERTY () FName SoundfieldEndpointType
Currently used format.
UPROPERTY () TArray< TObjectPtr< USoundfieldEffectBase > > SoundfieldEffectChain
UPROPERTY () TObjectPtr< USoundfieldEncodingSettingsBase > EncodingSettings
UPROPERTY () TObjectPtr< USoundfieldEndpointSettingsBase > EndpointSettings
UPROPERTY () TSubclassOf< UAudioEndpointSettingsBase > EndpointSettingsClass
UPROPERTY () TSubclassOf< USoundfieldEncodingSettingsBase > EncodingSettingsClass
Protected Member Functions
virtual void PostEditChangeProperty (struct FPropertyChangedEvent &PropertyChangedEvent) override
virtual void PostLoad () override
Private Member Functions
const USoundfieldEncodingSettingsBase * GetEncodingSettings () const
GENERATED_UCLASS_BODY() public const USoundfieldEndpointSettingsBase * GetEndpointSettings () const
TArray< USoundfieldEffectBase * > GetSoundfieldProcessors () const
Detailed Description
Definition at line 598 of file SoundSubmix.h.
Member Function Documentation
GetEncodingSettings()
const USoundfieldEncodingSettingsBase * USoundfieldEndpointSubmix::GetEncodingSettings () const private
GetEndpointSettings()
GENERATED_UCLASS_BODY() public const USoundfieldEndpointSettingsBase * USoundfieldEndpointSubmix::GetEndpointSettings () const private
GetSoundfieldProcessors()
TArray< USoundfieldEffectBase * > USoundfieldEndpointSubmix::GetSoundfieldProcessors () const private
PostEditChangeProperty()
virtual void USoundfieldEndpointSubmix::PostEditChangeProperty (struct FPropertyChangedEvent & PropertyChangedEvent) override protected virtual
PostLoad()
virtual void USoundfieldEndpointSubmix::PostLoad () override protected virtual
References PostLoad().
Referenced by PostLoad().
RecurseCheckChild()
bool USoundfieldEndpointSubmix::RecurseCheckChild (const USoundSubmix * ChildSoundSubmix) const
Returns
true if the child sound class exists in the tree
References RecurseCheckChild().
Referenced by RecurseCheckChild().
SanitizeLinks()
void USoundfieldEndpointSubmix::SanitizeLinks ()
References SanitizeLinks().
Referenced by SanitizeLinks().
UPROPERTY() [1/6]
USoundfieldEndpointSubmix::UPROPERTY ()
Currently used format.
References Category.
Referenced by UPROPERTY(), UPROPERTY(), UPROPERTY(), and UPROPERTY().
UPROPERTY() [2/6]
USoundfieldEndpointSubmix::UPROPERTY ()
References Category, and UPROPERTY().
UPROPERTY() [3/6]
USoundfieldEndpointSubmix::UPROPERTY ()
References Category, and UPROPERTY().
UPROPERTY() [4/6]
USoundfieldEndpointSubmix::UPROPERTY ()
References Category, and UPROPERTY().
UPROPERTY() [5/6]
USoundfieldEndpointSubmix::UPROPERTY ()
UPROPERTY() [6/6]
USoundfieldEndpointSubmix::UPROPERTY ()
References UPROPERTY().
The documentation for this class was generated from the following file:
Runtime/Engine/Classes/Sound/SoundSubmix.h