Unreal Engine 5.6 C++ API: UE::AnimNext::TPool< ElementType > Class Template Reference
UE::AnimNext::TPool< ElementType > Class Template Reference
#include "AnimNextPool.h"
Data Structures
struct FEntry
class TIterator
Public Types
typedef TIterator< const ElementType, false > RangedForConstIteratorType
typedef TIterator< const ElementType, true > RangedForConstReverseIteratorType
typedef TIterator< ElementType, false > RangedForIteratorType
typedef TIterator< ElementType, true > RangedForReverseIteratorType
Public Member Functions
FORCEINLINE RangedForIteratorType begin ()
DO NOT USE DIRECTLY STL-like iterators to enable range-based for loop support.
FORCEINLINE RangedForConstIteratorType begin () const
template<typename... ArgsType>
TPoolHandle< ElementType > Emplace (ArgsType &&... InArgs)
FORCEINLINE RangedForIteratorType end ()
FORCEINLINE RangedForConstIteratorType end () const
ElementType & Get (TPoolHandle< ElementType > InHandle)
const ElementType & Get (TPoolHandle< ElementType > InHandle) const
bool IsValidHandle (TPoolHandle< ElementType > InHandle) const
FORCEINLINE RangedForReverseIteratorType rbegin ()
FORCEINLINE RangedForConstReverseIteratorType rbegin () const
void Release (TPoolHandle< ElementType > InHandle, EAllowShrinking InAllowShrinking=EAllowShrinking::Default)
FORCEINLINE RangedForReverseIteratorType rend ()
FORCEINLINE RangedForConstReverseIteratorType rend () const
ElementType * TryGet (TPoolHandle< ElementType > InHandle)
const ElementType * TryGet (TPoolHandle< ElementType > InHandle) const
Private Attributes
TPagedArray< FEntry > Entries
uint32 HeadFreeIndex = MAX_uint32
Static Private Attributes
static uint32 SerialNumber = 0
Detailed Description
template<typename ElementType>
class UE::AnimNext::TPool< ElementType >
Definition at line 14 of file AnimNextPool.h.
Member Typedef Documentation
RangedForConstIteratorType
template<typename ElementType> typedef TIterator<const ElementType, false> UE::AnimNext::TPool< ElementType >::RangedForConstIteratorType
Definition at line 204 of file AnimNextPool.h.
RangedForConstReverseIteratorType
template<typename ElementType> typedef TIterator<const ElementType, true > UE::AnimNext::TPool< ElementType >::RangedForConstReverseIteratorType
Definition at line 206 of file AnimNextPool.h.
RangedForIteratorType
template<typename ElementType> typedef TIterator< ElementType, false> UE::AnimNext::TPool< ElementType >::RangedForIteratorType
Definition at line 203 of file AnimNextPool.h.
RangedForReverseIteratorType
template<typename ElementType> typedef TIterator< ElementType, true > UE::AnimNext::TPool< ElementType >::RangedForReverseIteratorType
Definition at line 205 of file AnimNextPool.h.
Member Function Documentation
begin() [1/2]
template<typename ElementType> FORCEINLINE RangedForIteratorType UE::AnimNext::TPool< ElementType >::begin () inline
DO NOT USE DIRECTLY STL-like iterators to enable range-based for loop support.
Definition at line 213 of file AnimNextPool.h.
References FORCEINLINE.
begin() [2/2]
template<typename ElementType> FORCEINLINE RangedForConstIteratorType UE::AnimNext::TPool< ElementType >::begin () const inline
Definition at line 214 of file AnimNextPool.h.
References FORCEINLINE.
Emplace()
template<typename ElementType> template<typename... ArgsType> TPoolHandle< ElementType > UE::AnimNext::TPool< ElementType >::Emplace (ArgsType &&... InArgs) inline
Definition at line 32 of file AnimNextPool.h.
References check, Emplace(), Entries, Forward(), Get(), Handle, HeadFreeIndex, MAX_uint32, UE::AnimNext::TPool< ElementType >::FEntry::SerialNumber, SerialNumber, and UE::AnimNext::TPool< ElementType >::FEntry::ValueOrNextFreeIndex.
Referenced by Emplace().
end() [1/2]
template<typename ElementType> FORCEINLINE RangedForIteratorType UE::AnimNext::TPool< ElementType >::end () inline
Definition at line 215 of file AnimNextPool.h.
References Entries, and FORCEINLINE.
end() [2/2]
template<typename ElementType> FORCEINLINE RangedForConstIteratorType UE::AnimNext::TPool< ElementType >::end () const inline
Definition at line 216 of file AnimNextPool.h.
References Entries, and FORCEINLINE.
Get() [1/2]
template<typename ElementType> ElementType & UE::AnimNext::TPool< ElementType >::Get (TPoolHandle< ElementType > InHandle) inline
Definition at line 86 of file AnimNextPool.h.
References check, Entries, Get(), UE::AnimNext::TPoolHandle< ElementType >::Index, and IsValidHandle().
Referenced by Emplace(), Get(), Get(), UE::AnimNext::TPool< ElementType >::TIterator< ElementType, false >::operator*(), UE::AnimNext::TPool< ElementType >::TIterator< ElementType, false >::operator->(), TryGet(), and TryGet().
Get() [2/2]
template<typename ElementType> const ElementType & UE::AnimNext::TPool< ElementType >::Get (TPoolHandle< ElementType > InHandle) const inline
Definition at line 92 of file AnimNextPool.h.
References check, Entries, Get(), UE::AnimNext::TPoolHandle< ElementType >::Index, and IsValidHandle().
IsValidHandle()
template<typename ElementType> bool UE::AnimNext::TPool< ElementType >::IsValidHandle (TPoolHandle< ElementType > InHandle) const inline
Definition at line 116 of file AnimNextPool.h.
References Entries, UE::AnimNext::TPoolHandle< ElementType >::Index, and UE::AnimNext::TPoolHandle< ElementType >::SerialNumber.
Referenced by Get(), Get(), Release(), TryGet(), and TryGet().
rbegin() [1/2]
template<typename ElementType> FORCEINLINE RangedForReverseIteratorType UE::AnimNext::TPool< ElementType >::rbegin () inline
Definition at line 217 of file AnimNextPool.h.
References Entries, and FORCEINLINE.
rbegin() [2/2]
template<typename ElementType> FORCEINLINE RangedForConstReverseIteratorType UE::AnimNext::TPool< ElementType >::rbegin () const inline
Definition at line 218 of file AnimNextPool.h.
References Entries, and FORCEINLINE.
Release()
template<typename ElementType> void UE::AnimNext::TPool< ElementType >::Release (TPoolHandle< ElementType > InHandle, EAllowShrinking InAllowShrinking = EAllowShrinking::Default) inline
Definition at line 66 of file AnimNextPool.h.
References Default, Entries, HeadFreeIndex, UE::AnimNext::TPoolHandle< ElementType >::Index, IsValidHandle(), UE::AnimNext::TPool< ElementType >::FEntry::SerialNumber, and UE::AnimNext::TPool< ElementType >::FEntry::ValueOrNextFreeIndex.
rend() [1/2]
template<typename ElementType> FORCEINLINE RangedForReverseIteratorType UE::AnimNext::TPool< ElementType >::rend () inline
Definition at line 219 of file AnimNextPool.h.
References FORCEINLINE.
rend() [2/2]
template<typename ElementType> FORCEINLINE RangedForConstReverseIteratorType UE::AnimNext::TPool< ElementType >::rend () const inline
Definition at line 220 of file AnimNextPool.h.
References FORCEINLINE.
TryGet() [1/2]
template<typename ElementType> ElementType * UE::AnimNext::TPool< ElementType >::TryGet (TPoolHandle< ElementType > InHandle) inline
Definition at line 98 of file AnimNextPool.h.
References Entries, Get(), UE::AnimNext::TPoolHandle< ElementType >::Index, and IsValidHandle().
TryGet() [2/2]
template<typename ElementType> const ElementType * UE::AnimNext::TPool< ElementType >::TryGet (TPoolHandle< ElementType > InHandle) const inline
Definition at line 107 of file AnimNextPool.h.
References Entries, Get(), UE::AnimNext::TPoolHandle< ElementType >::Index, and IsValidHandle().
Field Documentation
Entries
template<typename ElementType> TPagedArray<FEntry> UE::AnimNext::TPool< ElementType >::Entries private
Definition at line 23 of file AnimNextPool.h.
Referenced by Emplace(), end(), end(), Get(), Get(), IsValidHandle(), rbegin(), rbegin(), Release(), TryGet(), and TryGet().
HeadFreeIndex
template<typename ElementType> uint32 UE::AnimNext::TPool< ElementType >::HeadFreeIndex = MAX_uint32 private
Definition at line 25 of file AnimNextPool.h.
Referenced by Emplace(), and Release().
SerialNumber
template<typename ElementType> uint32 UE::AnimNext::TPool< ElementType >::SerialNumber = 0 inline static private
Definition at line 28 of file AnimNextPool.h.
Referenced by Emplace().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Experimental/AnimNext/Source/AnimNext/Internal/AnimNextPool.h