Unreal Engine 5.6 C++ API: TArenaPointer< T > Class Template Reference
TArenaPointer< T > Class Template Reference
#include "MemoryArena.h"
Public Member Functions
TArenaPointer ()=default
TArenaPointer (T *Ptr, uint16 ArenaIndex)
operator const T * () const
operator T* ()
T * operator-> ()
const T * operator-> () const
TArenaPointer & operator= (T *Rhs)
Public Member Functions inherited from FArenaPointer
FArenaPointer ()=default
FArenaPointer (void *Ptr, uint16 ArenaIndex)
FMemoryArena & Arena () const
void Free () const
FORCEINLINE const uint16 GetArenaIndex () const
FORCEINLINE void * GetPointer ()
FORCEINLINE const void * GetPointer () const
operator bool () const
FORCEINLINE void SetPointerAndArena (void *InPtr, uint16 InArenaTag)
Additional Inherited Members
Public Types inherited from FArenaPointer
enum { NoTag = 0 }
Detailed Description
template<typename T>
class TArenaPointer< T >
Definition at line 87 of file MemoryArena.h.
Constructor & Destructor Documentation
TArenaPointer() [1/2]
template<typename T> TArenaPointer< T >::TArenaPointer () default
Referenced by operator=().
TArenaPointer() [2/2]
template<typename T> TArenaPointer< T >::TArenaPointer (T * Ptr, uint16 ArenaIndex) inline
Definition at line 91 of file MemoryArena.h.
References FArenaPointer::FArenaPointer().
Member Function Documentation
operator const T *()
template<typename T> TArenaPointer< T >::operator const T * () const inline
Definition at line 96 of file MemoryArena.h.
References FArenaPointer::GetPointer().
operator T*()
template<typename T> TArenaPointer< T >::operator T* () inline
Definition at line 95 of file MemoryArena.h.
References FArenaPointer::GetPointer().
operator->() [1/2]
template<typename T> T * TArenaPointer< T >::operator-> () inline
Definition at line 97 of file MemoryArena.h.
References FArenaPointer::GetPointer().
operator->() [2/2]
template<typename T> const T * TArenaPointer< T >::operator-> () const inline
Definition at line 98 of file MemoryArena.h.
References FArenaPointer::GetPointer().
operator=()
template<typename T> TArenaPointer & TArenaPointer< T >::operator= (T * Rhs) inline
Definition at line 93 of file MemoryArena.h.
References TArenaPointer(), FArenaPointer::NoTag, and FArenaPointer::SetPointerAndArena().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Memory/MemoryArena.h