Unreal Engine 5.6 C++ API: FFrameNumberDetailsCustomization Class Reference
FFrameNumberDetailsCustomization Class Reference
Customize the FFrameNumber to support conversion from seconds/frames/timecode formats.
#include "FrameNumberDetailsCustomization.h"
Public Member Functions
FFrameNumberDetailsCustomization (TSharedPtr< INumericTypeInterface< double > > InNumericTypeInterface)
FFrameNumberDetailsCustomization (TWeakPtr< ISequencer > Sequencer)
virtual void CustomizeChildren (TSharedRef< IPropertyHandle > PropertyHandle, IDetailChildrenBuilder &ChildBuilder, IPropertyTypeCustomizationUtils &CustomizationUtils) override
Called when the children of the property should be customized or extra rows added.
virtual void CustomizeHeader (TSharedRef< IPropertyHandle > PropertyHandle, FDetailWidgetRow &HeaderRow, IPropertyTypeCustomizationUtils &CustomizationUtils) override
IPropertyTypeCustomization interface.
Public Member Functions inherited from IPropertyTypeCustomization
virtual ~IPropertyTypeCustomization ()
virtual bool ShouldInlineKey () const
Public Member Functions inherited from TSharedFromThis< IPropertyTypeCustomization >
TSharedRef< IPropertyTypeCustomization, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< IPropertyTypeCustomization, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Static Public Member Functions
static TSharedRef< IPropertyTypeCustomization > MakeInstance (TSharedPtr< INumericTypeInterface< double > > InNumericTypeInterface)
static TSharedRef< IPropertyTypeCustomization > MakeInstance (TWeakPtr< ISequencer > Sequencer)
Private Member Functions
FText OnGetTimeText () const
FText OnGetTimeToolTipText () const
void OnTimeTextCommitted (const FText &InText, ETextCommit::Type CommitInfo)
Private Attributes
TSharedPtr< IPropertyHandle > FrameNumberProperty
Store the property handle to the FrameNumber field so we can get/set the value on the object via text box callbacks.
TSharedPtr< INumericTypeInterface< double > > NumericTypeInterface
int32 UIClampMax
If they've used the UIMax metadata on the FFrameNumber property, we store that for use via text box callbacks.
int32 UIClampMin
If they've used the UIMin metadata on the FFrameNumber property, we store that for use via text box callbacks.
TWeakPtr< ISequencer > WeakSequencer
Additional Inherited Members
Protected Member Functions inherited from TSharedFromThis< IPropertyTypeCustomization >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions inherited from TSharedFromThis< IPropertyTypeCustomization >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
Customize the FFrameNumber to support conversion from seconds/frames/timecode formats.
Definition at line 15 of file FrameNumberDetailsCustomization.h.
Constructor & Destructor Documentation
FFrameNumberDetailsCustomization() [1/2]
FFrameNumberDetailsCustomization::FFrameNumberDetailsCustomization (TWeakPtr< ISequencer > Sequencer) inline
Definition at line 29 of file FrameNumberDetailsCustomization.h.
References WeakSequencer.
FFrameNumberDetailsCustomization() [2/2]
FFrameNumberDetailsCustomization::FFrameNumberDetailsCustomization (TSharedPtr< INumericTypeInterface< double > > InNumericTypeInterface) inline
Definition at line 33 of file FrameNumberDetailsCustomization.h.
References NumericTypeInterface.
Member Function Documentation
CustomizeChildren()
virtual void FFrameNumberDetailsCustomization::CustomizeChildren (TSharedRef< IPropertyHandle > PropertyHandle, IDetailChildrenBuilder & ChildBuilder, IPropertyTypeCustomizationUtils & CustomizationUtils) override virtual
Called when the children of the property should be customized or extra rows added.
Parameters
PropertyHandle Handle to the property being customized
StructBuilder A builder for adding children
StructCustomizationUtils Utilities for customization
Implements IPropertyTypeCustomization.
CustomizeHeader()
virtual void FFrameNumberDetailsCustomization::CustomizeHeader (TSharedRef< IPropertyHandle > PropertyHandle, FDetailWidgetRow & HeaderRow, IPropertyTypeCustomizationUtils & CustomizationUtils) inline override virtual
IPropertyTypeCustomization interface.
Implements IPropertyTypeCustomization.
Definition at line 39 of file FrameNumberDetailsCustomization.h.
MakeInstance() [1/2]
TSharedRef< IPropertyTypeCustomization > FFrameNumberDetailsCustomization::MakeInstance (TSharedPtr< INumericTypeInterface< double > > InNumericTypeInterface) inline static
Definition at line 19 of file FrameNumberDetailsCustomization.h.
References MakeShared(), and MoveTemp().
MakeInstance() [2/2]
TSharedRef< IPropertyTypeCustomization > FFrameNumberDetailsCustomization::MakeInstance (TWeakPtr< ISequencer > Sequencer) inline static
Definition at line 24 of file FrameNumberDetailsCustomization.h.
References MakeShared().
OnGetTimeText()
FText FFrameNumberDetailsCustomization::OnGetTimeText () const private
OnGetTimeToolTipText()
FText FFrameNumberDetailsCustomization::OnGetTimeToolTipText () const private
OnTimeTextCommitted()
void FFrameNumberDetailsCustomization::OnTimeTextCommitted (const FText & InText, ETextCommit::Type CommitInfo) private
Field Documentation
FrameNumberProperty
TSharedPtr<IPropertyHandle> FFrameNumberDetailsCustomization::FrameNumberProperty private
Store the property handle to the FrameNumber field so we can get/set the value on the object via text box callbacks.
Definition at line 52 of file FrameNumberDetailsCustomization.h.
NumericTypeInterface
TSharedPtr<INumericTypeInterface<double> > FFrameNumberDetailsCustomization::NumericTypeInterface private
Definition at line 49 of file FrameNumberDetailsCustomization.h.
Referenced by FFrameNumberDetailsCustomization().
UIClampMax
int32 FFrameNumberDetailsCustomization::UIClampMax private
If they've used the UIMax metadata on the FFrameNumber property, we store that for use via text box callbacks.
Definition at line 57 of file FrameNumberDetailsCustomization.h.
UIClampMin
int32 FFrameNumberDetailsCustomization::UIClampMin private
If they've used the UIMin metadata on the FFrameNumber property, we store that for use via text box callbacks.
Definition at line 55 of file FrameNumberDetailsCustomization.h.
WeakSequencer
TWeakPtr<ISequencer> FFrameNumberDetailsCustomization::WeakSequencer private
Definition at line 47 of file FrameNumberDetailsCustomization.h.
Referenced by FFrameNumberDetailsCustomization().
The documentation for this class was generated from the following file:
Editor/MovieSceneTools/Public/FrameNumberDetailsCustomization.h