Unreal Engine 5.6 C++ API: FManagedStorageFileWriteHandle Class Reference
FManagedStorageFileWriteHandle Class Reference
#include "IPlatformFileManagedStorageWrapper.h"
Public Member Functions
FManagedStorageFileWriteHandle (IFileHandle *InFileHandle, FPersistentManagedFile InFile)
virtual ~FManagedStorageFileWriteHandle ()
virtual bool Flush (const bool bFullFlush=false) override
Flushes file handle to disk.
virtual bool Read (uint8 *Destination, int64 BytesToRead) override
Read bytes from the file.
virtual bool ReadAt (uint8 *Destination, int64 BytesToRead, int64 Offset) override
virtual bool Seek (int64 NewPosition) override
Change the current write or read position.
virtual bool SeekFromEnd (int64 NewPositionRelativeToEnd=0) override
Change the current write or read position, relative to the end of the file.
virtual void ShrinkBuffers () override
Minimizes optional system or process cache kept for the file.
virtual int64 Size () override
Return the total size of the file.
virtual int64 Tell () override
Return the current write or read position.
virtual bool Truncate (int64 NewSize) override
Truncate the file to the given size (in bytes).
virtual bool Write (const uint8 *Source, int64 BytesToWrite) override
Write bytes to the file.
Public Member Functions inherited from IFileHandle
virtual ~IFileHandle ()
Destructor, also the only way to close the file handle.
Private Member Functions
bool TryManageFile ()
Static Private Member Functions
static bool IsReady ()
Private Attributes
FPersistentManagedFile File
TUniquePtr< IFileHandle > FileHandle
Detailed Description
Definition at line 650 of file IPlatformFileManagedStorageWrapper.h.
Constructor & Destructor Documentation
FManagedStorageFileWriteHandle()
FManagedStorageFileWriteHandle::FManagedStorageFileWriteHandle (IFileHandle * InFileHandle, FPersistentManagedFile InFile) inline
Definition at line 670 of file IPlatformFileManagedStorageWrapper.h.
References File, FileHandle, and MoveTemp().
~FManagedStorageFileWriteHandle()
virtual FManagedStorageFileWriteHandle::~FManagedStorageFileWriteHandle () inline virtual
Definition at line 676 of file IPlatformFileManagedStorageWrapper.h.
References FPersistentStorageManager::AddOrUpdateFile(), File, FileHandle, FPersistentStorageManager::Get(), and TryManageFile().
Member Function Documentation
Flush()
virtual bool FManagedStorageFileWriteHandle::Flush (const bool bFullFlush = false) inline override virtual
Flushes file handle to disk.
Parameters
bFullFlush true to flush everything about the file (including its meta-data) with a strong guarantee that it will be on disk by the time this function returns, or false to let the operating/file system have more leeway about when the data actually gets written to disk
Returns
true if operation completed successfully.
Implements IFileHandle.
Definition at line 752 of file IPlatformFileManagedStorageWrapper.h.
References ensureAlways, File, FileHandle, FPersistentStorageManager::Get(), None, TryManageFile(), and verify.
IsReady()
bool FManagedStorageFileWriteHandle::IsReady () inline static private
Definition at line 653 of file IPlatformFileManagedStorageWrapper.h.
References FPersistentStorageManager::IsReady().
Referenced by TryManageFile().
Read()
virtual bool FManagedStorageFileWriteHandle::Read (uint8 * Destination, int64 BytesToRead) inline override virtual
Read bytes from the file.
Parameters
Destination Buffer to holds the results, should be at least BytesToRead in size.
BytesToRead Number of bytes to read into the destination.
Returns
true if the operation completed successfully.
Implements IFileHandle.
Definition at line 703 of file IPlatformFileManagedStorageWrapper.h.
References FileHandle.
ReadAt()
virtual bool FManagedStorageFileWriteHandle::ReadAt (uint8 * Destination, int64 BytesToRead, int64 Offset) inline override virtual
Implements IFileHandle.
Definition at line 708 of file IPlatformFileManagedStorageWrapper.h.
References FileHandle.
Seek()
virtual bool FManagedStorageFileWriteHandle::Seek (int64 NewPosition) inline override virtual
Change the current write or read position.
Parameters
NewPosition new write or read position
Returns
true if the operation completed successfully.
Implements IFileHandle.
Definition at line 693 of file IPlatformFileManagedStorageWrapper.h.
References FileHandle.
SeekFromEnd()
virtual bool FManagedStorageFileWriteHandle::SeekFromEnd (int64 NewPositionRelativeToEnd = 0) inline override virtual
Change the current write or read position, relative to the end of the file.
Parameters
NewPositionRelativeToEnd new write or read position, relative to the end of the file should be <=0!
Returns
true if the operation completed successfully.
Implements IFileHandle.
Definition at line 698 of file IPlatformFileManagedStorageWrapper.h.
References FileHandle.
ShrinkBuffers()
virtual void FManagedStorageFileWriteHandle::ShrinkBuffers () inline override virtual
Minimizes optional system or process cache kept for the file.
Reimplemented from IFileHandle.
Definition at line 813 of file IPlatformFileManagedStorageWrapper.h.
References FileHandle.
Size()
virtual int64 FManagedStorageFileWriteHandle::Size () inline override virtual
Return the total size of the file.
Reimplemented from IFileHandle.
Definition at line 747 of file IPlatformFileManagedStorageWrapper.h.
References FileHandle.
Tell()
virtual int64 FManagedStorageFileWriteHandle::Tell () inline override virtual
Return the current write or read position.
Implements IFileHandle.
Definition at line 688 of file IPlatformFileManagedStorageWrapper.h.
References FileHandle.
Truncate()
virtual bool FManagedStorageFileWriteHandle::Truncate (int64 NewSize) inline override virtual
Truncate the file to the given size (in bytes).
Parameters
NewSize Truncated file size (in bytes).
Returns
true if the operation completed successfully.
Implements IFileHandle.
Definition at line 776 of file IPlatformFileManagedStorageWrapper.h.
References FPersistentStorageManager::AddOrUpdateFile(), Error, File, FileHandle, FPersistentStorageManager::Get(), None, RespectQuota, TEXT, TryManageFile(), UE_LOG, and verify.
TryManageFile()
bool FManagedStorageFileWriteHandle::TryManageFile () inline private
Definition at line 659 of file IPlatformFileManagedStorageWrapper.h.
References File, FPersistentStorageManager::Get(), IsReady(), and FPersistentStorageManager::TryManageFile().
Referenced by ~FManagedStorageFileWriteHandle(), Flush(), Truncate(), and Write().
Write()
virtual bool FManagedStorageFileWriteHandle::Write (const uint8 * Source, int64 BytesToWrite) inline override virtual
Write bytes to the file.
Parameters
Source Buffer to write, should be at least BytesToWrite in size.
BytesToWrite Number of bytes to write.
Returns
true if the operation completed successfully.
Implements IFileHandle.
Definition at line 713 of file IPlatformFileManagedStorageWrapper.h.
References FPersistentStorageManager::AddOrUpdateFile(), ensureAlways, Error, File, FileHandle, FPersistentStorageManager::Get(), FMath::Max, None, RespectQuota, Source, TEXT, TryManageFile(), UE_LOG, and verify.
Field Documentation
File
FPersistentManagedFile FManagedStorageFileWriteHandle::File private
Definition at line 820 of file IPlatformFileManagedStorageWrapper.h.
Referenced by FManagedStorageFileWriteHandle(), ~FManagedStorageFileWriteHandle(), Flush(), Truncate(), TryManageFile(), and Write().
FileHandle
TUniquePtr<IFileHandle> FManagedStorageFileWriteHandle::FileHandle private
Definition at line 819 of file IPlatformFileManagedStorageWrapper.h.
Referenced by FManagedStorageFileWriteHandle(), ~FManagedStorageFileWriteHandle(), Flush(), Read(), ReadAt(), Seek(), SeekFromEnd(), ShrinkBuffers(), Size(), Tell(), Truncate(), and Write().
The documentation for this class was generated from the following file:
Runtime/Core/Public/HAL/IPlatformFileManagedStorageWrapper.h