Unreal Engine 5.6 C++ API: FPositionVertexBuffer Class Reference
FPositionVertexBuffer Class Reference
A vertex buffer of positions.
#include "PositionVertexBuffer.h"
Public Member Functions
FPositionVertexBuffer ()
Default constructor.
~FPositionVertexBuffer ()
Destructor.
bool AppendVertices (const FStaticMeshBuildVertex *Vertices, const uint32 NumVerticesToAppend)
Appends the specified vertices to the end of the buffer.
void BindPositionVertexBuffer (const class FVertexFactory *VertexFactory, struct FStaticMeshDataType &Data) const
void CleanUp ()
Delete existing resources.
void ClearMetaData ()
FBufferRHIRef CreateRHIBuffer (FRHICommandListBase &RHICmdList)
Create an RHI vertex buffer with CPU data.
FORCEINLINE SIZE_T GetAllocatedSize () const
bool GetAllowCPUAccess () const
virtual FString GetFriendlyName () const override
FORCEINLINE uint32 GetNumVertices () const
FRHIShaderResourceView * GetSRV () const
FORCEINLINE uint32 GetStride () const
void * GetVertexData ()
const void * GetVertexData () const
void Init (const FConstMeshBuildVertexView &InVertices, bool bInNeedsCPUAccess=true)
void Init (const FPositionVertexBuffer &InVertexBuffer, bool bInNeedsCPUAccess=true)
Initializes this vertex buffer with the contents of the given vertex buffer.
void Init (const TArray< FStaticMeshBuildVertex > &InVertices, bool bInNeedsCPUAccess=true)
Initializes the buffer with the given vertices, used to convert legacy layouts.
void Init (const TArray< FVector3f > &InPositions, bool bInNeedsCPUAccess=true)
void Init (uint32 NumVertices, bool bInNeedsCPUAccess=true)
virtual void InitRHI (FRHICommandListBase &RHICmdList) override
Initializes the RHI resources used by this resource.
void InitRHIForStreaming (FRHIBuffer *IntermediateBuffer, FRHIResourceReplaceBatcher &Batcher)
Similar to Init/ReleaseRHI but only update existing SRV so references to the SRV stays valid.
void operator= (const FPositionVertexBuffer &Other)
Specialized assignment operator, only used when importing LOD's.
virtual void ReleaseRHI () override
Releases the RHI resources used by this resource.
void ReleaseRHIForStreaming (FRHIResourceReplaceBatcher &Batcher)
void Serialize (FArchive &Ar, bool bInNeedsCPUAccess)
Serializer.
void SerializeMetaData (FArchive &Ar)
void SetMetaData (uint32 InStride, uint32 InNumVertices)
FORCEINLINE FVector3f & VertexPosition (uint32 VertexIndex)
FORCEINLINE const FVector3f & VertexPosition (uint32 VertexIndex) const
Public Member Functions inherited from FVertexBuffer
RENDERCORE_API FVertexBuffer ()
RENDERCORE_API FVertexBuffer (const FVertexBuffer &)
virtual RENDERCORE_API ~FVertexBuffer ()
const FBufferRHIRef & GetRHI () const
RENDERCORE_API FVertexBuffer & operator= (const FVertexBuffer &Other)
RENDERCORE_API void SetRHI (const FBufferRHIRef &BufferRHI)
Public Member Functions inherited from FRenderResource
RENDERCORE_API FRenderResource ()
Default constructor.
RENDERCORE_API FRenderResource (const FRenderResource &)
Misc copy/assignment.
RENDERCORE_API FRenderResource (ERHIFeatureLevel::Type InFeatureLevel)
Constructor when we know what feature level this resource should support.
RENDERCORE_API FRenderResource (FRenderResource &&)
virtual RENDERCORE_API ~FRenderResource ()
Destructor used to catch unreleased resources.
EInitPhase GetInitPhase () const
int32 GetListIndex () const
FName GetOwnerName () const
FName GetResourceName () const
virtual RENDERCORE_API void InitResource (FRHICommandListBase &RHICmdList)
Initializes the resource.
FORCEINLINE bool IsInitialized () const
RENDERCORE_API FRenderResource & operator= (const FRenderResource &Other)
RENDERCORE_API FRenderResource & operator= (FRenderResource &&Other)
virtual RENDERCORE_API void ReleaseResource ()
Prepares the resource for deletion.
void SetOwnerName (FName InOwnerName)
SetOwnerName should be called before BeginInitResource for the owner name to be successfully tracked.
void SetResourceName (FName InResourceName)
RENDERCORE_API void UpdateRHI (FRHICommandListBase &RHICmdList)
If the resource's RHI resources have been initialized, then release and reinitialize it.
Private Member Functions
void AllocateData (bool bInNeedsCPUAccess=true)
Allocates the vertex data storage type.
Private Attributes
bool bNeedsCPUAccess = true
uint8 * Data
The cached vertex data pointer.
uint32 NumVertices
The cached number of vertices.
FShaderResourceViewRHIRef PositionComponentSRV
uint32 Stride
The cached vertex stride.
FPositionVertexData * VertexData
The vertex data storage type.
Additional Inherited Members
Public Types inherited from FRenderResource
enum class EInitPhase : uint8 { Pre , Default , MAX }
Controls initialization order of render resources.
Static Public Member Functions inherited from FRenderResource
static RENDERCORE_API void ChangeFeatureLevel (ERHIFeatureLevel::Type NewFeatureLevel)
Reinitializes render resources at a new feature level.
static RENDERCORE_API void InitPreRHIResources ()
Initialize all resources initialized before the RHI was initialized.
static RENDERCORE_API void ReleaseRHIForAllResources ()
Release all render resources that are currently initialized.
Data Fields inherited from FVertexBuffer
FBufferRHIRef VertexBufferRHI
Data Fields inherited from FRenderResource
ERenderResourceState ResourceState = ERenderResourceState::Default
Protected Member Functions inherited from FRenderResource
template<typename T>
FBufferRHIRef CreateRHIBuffer (FRHICommandListBase &RHICmdList, T &InOutResourceObject, uint32 ResourceCount, EBufferUsageFlags InBufferUsageFlags, const TCHAR *InDebugName)
const FStaticFeatureLevel GetFeatureLevel () const
FORCEINLINE bool HasValidFeatureLevel () const
void SetFeatureLevel (const FStaticFeatureLevel InFeatureLevel)
void SetInitPhase (EInitPhase InInitPhase)
Static Protected Member Functions inherited from FRenderResource
static RENDERCORE_API FRHICommandListBase & GetImmediateCommandList ()
Detailed Description
A vertex buffer of positions.
Definition at line 26 of file PositionVertexBuffer.h.
Constructor & Destructor Documentation
FPositionVertexBuffer()
FPositionVertexBuffer::FPositionVertexBuffer ()
Default constructor.
Referenced by Init(), and operator=().
~FPositionVertexBuffer()
FPositionVertexBuffer::~FPositionVertexBuffer ()
Destructor.
Member Function Documentation
AllocateData()
void FPositionVertexBuffer::AllocateData (bool bInNeedsCPUAccess = true) private
Allocates the vertex data storage type.
AppendVertices()
bool FPositionVertexBuffer::AppendVertices (const FStaticMeshBuildVertex * Vertices, const uint32 NumVerticesToAppend)
Appends the specified vertices to the end of the buffer.
Parameters
Vertices The vertex data to be appended. Must not be nullptr.
NumVerticesToAppend How many vertices should be added
Returns
true if append operation is successful
BindPositionVertexBuffer()
void FPositionVertexBuffer::BindPositionVertexBuffer (const class FVertexFactory * VertexFactory, struct FStaticMeshDataType & Data) const
References Data, and VertexFactory.
CleanUp()
void FPositionVertexBuffer::CleanUp ()
Delete existing resources.
ClearMetaData()
void FPositionVertexBuffer::ClearMetaData ()
CreateRHIBuffer()
FBufferRHIRef FPositionVertexBuffer::CreateRHIBuffer (FRHICommandListBase & RHICmdList)
Create an RHI vertex buffer with CPU data.
CPU data may be discarded after creation (see TResourceArray::Discard)
Referenced by FSkeletalMeshStreamIn::FIntermediateBuffers::CreateFromCPUData().
GetAllocatedSize()
FORCEINLINE SIZE_T FPositionVertexBuffer::GetAllocatedSize () const inline
Definition at line 106 of file PositionVertexBuffer.h.
References Data, FORCEINLINE, NumVertices, and Stride.
GetAllowCPUAccess()
bool FPositionVertexBuffer::GetAllowCPUAccess () const
GetFriendlyName()
virtual FString FPositionVertexBuffer::GetFriendlyName () const inline override virtual
Returns
The resource's friendly name. Typically a UObject name.
Reimplemented from FVertexBuffer.
Definition at line 118 of file PositionVertexBuffer.h.
References TEXT.
GetNumVertices()
FORCEINLINE uint32 FPositionVertexBuffer::GetNumVertices () const inline
Definition at line 100 of file PositionVertexBuffer.h.
References FORCEINLINE, and NumVertices.
Referenced by FMeshRenderBufferSetConversionUtil::UpdateVertexBuffersFromOverlays(), VertexPosition(), and VertexPosition().
GetSRV()
FRHIShaderResourceView * FPositionVertexBuffer::GetSRV () const inline
Definition at line 125 of file PositionVertexBuffer.h.
References PositionComponentSRV.
GetStride()
FORCEINLINE uint32 FPositionVertexBuffer::GetStride () const inline
Definition at line 96 of file PositionVertexBuffer.h.
References FORCEINLINE, and Stride.
GetVertexData() [1/2]
void * FPositionVertexBuffer::GetVertexData () inline
Definition at line 122 of file PositionVertexBuffer.h.
References Data.
GetVertexData() [2/2]
const void * FPositionVertexBuffer::GetVertexData () const inline
Definition at line 123 of file PositionVertexBuffer.h.
References Data.
Init() [1/5]
void FPositionVertexBuffer::Init (const FConstMeshBuildVertexView & InVertices, bool bInNeedsCPUAccess = true)
Init() [2/5]
void FPositionVertexBuffer::Init (const FPositionVertexBuffer & InVertexBuffer, bool bInNeedsCPUAccess = true)
Initializes this vertex buffer with the contents of the given vertex buffer.
Parameters
InVertexBuffer - The vertex buffer to initialize from.
References FPositionVertexBuffer().
Init() [3/5]
void FPositionVertexBuffer::Init (const TArray< FStaticMeshBuildVertex > & InVertices, bool bInNeedsCPUAccess = true)
Initializes the buffer with the given vertices, used to convert legacy layouts.
Parameters
InVertices - The vertices to initialize the buffer with.
Init() [4/5]
void FPositionVertexBuffer::Init (const TArray< FVector3f > & InPositions, bool bInNeedsCPUAccess = true)
Init() [5/5]
void FPositionVertexBuffer::Init (uint32 NumVertices, bool bInNeedsCPUAccess = true)
References NumVertices.
Referenced by FMeshRenderBufferSetConversionUtil::InitializeBuffersFromOverlays().
InitRHI()
virtual void FPositionVertexBuffer::InitRHI (FRHICommandListBase & RHICmdList) override virtual
Initializes the RHI resources used by this resource.
Called when entering the state where both the resource and the RHI have been initialized. This is only called by the rendering thread.
Reimplemented from FRenderResource.
InitRHIForStreaming()
void FPositionVertexBuffer::InitRHIForStreaming (FRHIBuffer * IntermediateBuffer, FRHIResourceReplaceBatcher & Batcher)
Similar to Init/ReleaseRHI but only update existing SRV so references to the SRV stays valid.
References IntermediateBuffer.
Referenced by FSkeletalMeshStreamIn::FIntermediateBuffers::TransferBuffers().
operator=()
void FPositionVertexBuffer::operator= (const FPositionVertexBuffer & Other)
Specialized assignment operator, only used when importing LOD's.
References FPositionVertexBuffer(), and Other.
ReleaseRHI()
virtual void FPositionVertexBuffer::ReleaseRHI () override virtual
Releases the RHI resources used by this resource.
Called when leaving the state where both the resource and the RHI have been initialized. This is only called by the rendering thread.
Reimplemented from FVertexBuffer.
ReleaseRHIForStreaming()
void FPositionVertexBuffer::ReleaseRHIForStreaming (FRHIResourceReplaceBatcher & Batcher)
Referenced by FSkeletalMeshStreamOut::ReleaseBuffers().
Serialize()
void FPositionVertexBuffer::Serialize (FArchive & Ar, bool bInNeedsCPUAccess)
Serializer.
Parameters
Ar Archive to serialize with
bInNeedsCPUAccess Whether the elements need to be accessed by the CPU
References Ar.
SerializeMetaData()
void FPositionVertexBuffer::SerializeMetaData (FArchive & Ar)
References Ar.
SetMetaData()
void FPositionVertexBuffer::SetMetaData (uint32 InStride, uint32 InNumVertices)
VertexPosition() [1/2]
FORCEINLINE FVector3f & FPositionVertexBuffer::VertexPosition (uint32 VertexIndex) inline
Definition at line 85 of file PositionVertexBuffer.h.
References checkSlow, Data, FORCEINLINE, GetNumVertices(), and Stride.
Referenced by FMeshRenderBufferSetConversionUtil::InitializeBuffersFromOverlays(), and FMeshRenderBufferSetConversionUtil::UpdateVertexBuffersFromOverlays().
VertexPosition() [2/2]
FORCEINLINE const FVector3f & FPositionVertexBuffer::VertexPosition (uint32 VertexIndex) const inline
Definition at line 90 of file PositionVertexBuffer.h.
References checkSlow, Data, FORCEINLINE, GetNumVertices(), and Stride.
Field Documentation
bNeedsCPUAccess
bool FPositionVertexBuffer::bNeedsCPUAccess = true private
Definition at line 143 of file PositionVertexBuffer.h.
Data
uint8* FPositionVertexBuffer::Data private
The cached vertex data pointer.
Definition at line 135 of file PositionVertexBuffer.h.
Referenced by BindPositionVertexBuffer(), GetAllocatedSize(), GetVertexData(), GetVertexData(), VertexPosition(), and VertexPosition().
NumVertices
uint32 FPositionVertexBuffer::NumVertices private
The cached number of vertices.
Definition at line 141 of file PositionVertexBuffer.h.
Referenced by GetAllocatedSize(), GetNumVertices(), and Init().
PositionComponentSRV
FShaderResourceViewRHIRef FPositionVertexBuffer::PositionComponentSRV private
Definition at line 129 of file PositionVertexBuffer.h.
Referenced by GetSRV().
Stride
uint32 FPositionVertexBuffer::Stride private
The cached vertex stride.
Definition at line 138 of file PositionVertexBuffer.h.
Referenced by GetAllocatedSize(), GetStride(), VertexPosition(), and VertexPosition().
VertexData
FPositionVertexData* FPositionVertexBuffer::VertexData private
The vertex data storage type.
Definition at line 132 of file PositionVertexBuffer.h.
The documentation for this class was generated from the following file:
Runtime/Engine/Public/Rendering/PositionVertexBuffer.h