Unreal Engine 5.6 C++ API: FNetworkPredictionTrace Class Reference
FNetworkPredictionTrace Class Reference
#include "NetworkPredictionTrace.h"
Public Types
enum class ETraceUserState : uint8 { Input , Sync , Aux , Physics }
Static Public Member Functions
static NETWORKPREDICTION_API void TraceBufferedInput (int32 NumBufferedFrames, bool bFault)
static NETWORKPREDICTION_API void TraceFixedTickOffset (int32 Offset, bool bChanged)
static NETWORKPREDICTION_API void TraceNetRecv (int32 Frame, int32 TimeMS)
static NETWORKPREDICTION_API void TraceOOBStateMod (int32 SimulationId, int32 Frame, const FAnsiStringView &StrView)
template<typename ModelDef, typename DriverType>
static void TracePhysicsStateAtFrame (int32 PhysicsFrame, Chaos::FRewindData *RewindData, DriverType *Driver)
template<typename ModelDef, typename DriverType>
static void TracePhysicsStateCurrent (DriverType *Driver)
template<typename ModelDef, typename PhysicsStateType>
static void TracePhysicsStateRecv (const PhysicsStateType &State)
static NETWORKPREDICTION_API void TracePIEStart ()
static NETWORKPREDICTION_API void TraceProduceInput (int32 TraceID)
static NETWORKPREDICTION_API void TracePushInputFrame (int32 Frame)
static NETWORKPREDICTION_API void TraceReconcile (const FAnsiStringView &StrView)
static NETWORKPREDICTION_API void TraceRollbackInject (int32 TraceID)
static NETWORKPREDICTION_API void TraceShouldReconcile (int32 TraceID)
static NETWORKPREDICTION_API void TraceSimState (int32 TraceID)
static NETWORKPREDICTION_API void TraceSimTick (int32 TraceID)
static NETWORKPREDICTION_API void TraceSimulationConfig (int32 TraceID, ENetRole NetRole, bool bHasNetConnection, const FNetworkPredictionInstanceArchetype &Archetype, const FNetworkPredictionInstanceConfig &Config, int32 ServiceMask)
template<typename ModelDef>
static void TraceSimulationCreated (FNetworkPredictionID ID, typename ModelDef::Driver *Driver)
static NETWORKPREDICTION_API void TraceSimulationScope (int32 TraceID)
static NETWORKPREDICTION_API void TraceSystemFault (const TCHAR *Fmt,...)
static NETWORKPREDICTION_API void TraceTick (int32 StartMS, int32 DeltaMS, int32 OutputFrame)
template<typename ModelDef, typename StateType>
static void TraceUserState (const StateType *State, ETraceUserState StateTypeEnum)
static NETWORKPREDICTION_API void TraceWorldFrameStart (UGameInstance *GameInstance, float DeltaSeconds)
static NETWORKPREDICTION_API void TraceWorldPreInit ()
Static Private Member Functions
static NETWORKPREDICTION_API void TraceSimulationCreated_Internal (FNetworkPredictionID ID, FStringBuilderBase &Builder)
static NETWORKPREDICTION_API void TraceUserState_Internal (ETraceUserState StateType, FAnsiStringBuilderBase &Builder)
Friends
struct FScopedSimulationTraceHelper
Detailed Description
Definition at line 134 of file NetworkPredictionTrace.h.
Member Enumeration Documentation
ETraceUserState
enum class FNetworkPredictionTrace::ETraceUserState : uint8 strong
Enumerator
Input
Sync
Aux
Physics
Definition at line 174 of file NetworkPredictionTrace.h.
Member Function Documentation
TraceBufferedInput()
NETWORKPREDICTION_API void FNetworkPredictionTrace::TraceBufferedInput (int32 NumBufferedFrames, bool bFault) static
References UE_API.
TraceFixedTickOffset()
NETWORKPREDICTION_API void FNetworkPredictionTrace::TraceFixedTickOffset (int32 Offset, bool bChanged) static
References UE_API.
TraceNetRecv()
NETWORKPREDICTION_API void FNetworkPredictionTrace::TraceNetRecv (int32 Frame, int32 TimeMS) static
References UE_API.
TraceOOBStateMod()
NETWORKPREDICTION_API void FNetworkPredictionTrace::TraceOOBStateMod (int32 SimulationId, int32 Frame, const FAnsiStringView & StrView) static
References UE_API.
TracePhysicsStateAtFrame()
template<typename ModelDef, typename DriverType> void FNetworkPredictionTrace::TracePhysicsStateAtFrame (int32 PhysicsFrame, Chaos::FRewindData * RewindData, DriverType * Driver) inline static
Definition at line 222 of file NetworkPredictionTrace.h.
References FNetworkPredictionDriverBase< ModelDef >::HasPhysics(), Physics, FNetworkPredictionDriverBase< ModelDef >::TracePhysicsState(), and TraceUserState_Internal().
TracePhysicsStateCurrent()
template<typename ModelDef, typename DriverType> void FNetworkPredictionTrace::TracePhysicsStateCurrent (DriverType * Driver) inline static
Definition at line 203 of file NetworkPredictionTrace.h.
References FNetworkPredictionDriverBase< ModelDef >::HasPhysics(), Physics, FNetworkPredictionDriverBase< ModelDef >::TracePhysicsState(), and TraceUserState_Internal().
TracePhysicsStateRecv()
template<typename ModelDef, typename PhysicsStateType> void FNetworkPredictionTrace::TracePhysicsStateRecv (const PhysicsStateType & State) inline static
Definition at line 242 of file NetworkPredictionTrace.h.
References FNetworkPredictionDriverBase< ModelDef >::HasPhysics(), npCheckSlow, Physics, State, FNetworkPredictionDriverBase< ModelDef >::TracePhysicsStateRecv(), and TraceUserState_Internal().
TracePIEStart()
NETWORKPREDICTION_API void FNetworkPredictionTrace::TracePIEStart () static
References UE_API.
TraceProduceInput()
NETWORKPREDICTION_API void FNetworkPredictionTrace::TraceProduceInput (int32 TraceID) static
References UE_API.
TracePushInputFrame()
NETWORKPREDICTION_API void FNetworkPredictionTrace::TracePushInputFrame (int32 Frame) static
References UE_API.
TraceReconcile()
NETWORKPREDICTION_API void FNetworkPredictionTrace::TraceReconcile (const FAnsiStringView & StrView) static
References UE_API.
TraceRollbackInject()
NETWORKPREDICTION_API void FNetworkPredictionTrace::TraceRollbackInject (int32 TraceID) static
References UE_API.
TraceShouldReconcile()
NETWORKPREDICTION_API void FNetworkPredictionTrace::TraceShouldReconcile (int32 TraceID) static
References UE_API.
TraceSimState()
NETWORKPREDICTION_API void FNetworkPredictionTrace::TraceSimState (int32 TraceID) static
References UE_API.
TraceSimTick()
NETWORKPREDICTION_API void FNetworkPredictionTrace::TraceSimTick (int32 TraceID) static
References UE_API.
TraceSimulationConfig()
NETWORKPREDICTION_API void FNetworkPredictionTrace::TraceSimulationConfig (int32 TraceID, ENetRole NetRole, bool bHasNetConnection, const FNetworkPredictionInstanceArchetype & Archetype, const FNetworkPredictionInstanceConfig & Config, int32 ServiceMask) static
References UE_API.
TraceSimulationCreated()
template<typename ModelDef> void FNetworkPredictionTrace::TraceSimulationCreated (FNetworkPredictionID ID, typename ModelDef::Driver * Driver) inline static
Definition at line 139 of file NetworkPredictionTrace.h.
References FNetworkPredictionDriverBase< ModelDef >::GetTraceString(), ID, and TraceSimulationCreated_Internal().
TraceSimulationCreated_Internal()
NETWORKPREDICTION_API void FNetworkPredictionTrace::TraceSimulationCreated_Internal (FNetworkPredictionID ID, FStringBuilderBase & Builder) static private
References ID, and UE_API.
Referenced by TraceSimulationCreated().
TraceSimulationScope()
NETWORKPREDICTION_API void FNetworkPredictionTrace::TraceSimulationScope (int32 TraceID) static
References UE_API.
TraceSystemFault()
NETWORKPREDICTION_API void FNetworkPredictionTrace::TraceSystemFault (const TCHAR * Fmt, ...) static
References UE_API.
TraceTick()
NETWORKPREDICTION_API void FNetworkPredictionTrace::TraceTick (int32 StartMS, int32 DeltaMS, int32 OutputFrame) static
References UE_API.
TraceUserState()
template<typename ModelDef, typename StateType> void FNetworkPredictionTrace::TraceUserState (const StateType * State, ETraceUserState StateTypeEnum) inline static
Definition at line 183 of file NetworkPredictionTrace.h.
References npCheckSlow, State, TraceUserState_Internal(), and FNetworkPredictionDriverBase< ModelDef >::TraceUserStateString().
TraceUserState_Internal()
NETWORKPREDICTION_API void FNetworkPredictionTrace::TraceUserState_Internal (ETraceUserState StateType, FAnsiStringBuilderBase & Builder) static private
References UE_API.
Referenced by TracePhysicsStateAtFrame(), TracePhysicsStateCurrent(), TracePhysicsStateRecv(), and TraceUserState().
TraceWorldFrameStart()
NETWORKPREDICTION_API void FNetworkPredictionTrace::TraceWorldFrameStart (UGameInstance * GameInstance, float DeltaSeconds) static
References UE_API.
TraceWorldPreInit()
NETWORKPREDICTION_API void FNetworkPredictionTrace::TraceWorldPreInit () static
References UE_API.
Friends And Related Symbol Documentation
FScopedSimulationTraceHelper
friend struct FScopedSimulationTraceHelper friend
Definition at line 271 of file NetworkPredictionTrace.h.
References FScopedSimulationTraceHelper.
Referenced by FScopedSimulationTraceHelper.
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/NetworkPrediction/Source/NetworkPrediction/Public/NetworkPredictionTrace.h