Unreal Engine 5.6 C++ API: IAnimBlueprintExtensionCopyTermDefaultsContext Class Reference
IAnimBlueprintExtensionCopyTermDefaultsContext Class Reference abstract
#include "IAnimBlueprintCopyTermDefaultsContext.h"
Public Member Functions
virtual ~IAnimBlueprintExtensionCopyTermDefaultsContext ()=default
UObject * GetClassDefaultObject () const
uint8 * GetDestinationPtr () const
int32 GetNodePropertyIndex () const
const uint8 * GetSourcePtr () const
const FProperty * GetTargetProperty () const
Protected Member Functions
virtual UObject * GetClassDefaultObjectImpl () const =0
virtual uint8 * GetDestinationPtrImpl () const =0
virtual int32 GetNodePropertyIndexImpl () const =0
virtual const uint8 * GetSourcePtrImpl () const =0
virtual const FProperty * GetTargetPropertyImpl () const =0
Detailed Description
Definition at line 89 of file IAnimBlueprintCopyTermDefaultsContext.h.
Constructor & Destructor Documentation
~IAnimBlueprintExtensionCopyTermDefaultsContext()
virtual IAnimBlueprintExtensionCopyTermDefaultsContext::~IAnimBlueprintExtensionCopyTermDefaultsContext () virtual default
Member Function Documentation
GetClassDefaultObject()
UObject * IAnimBlueprintExtensionCopyTermDefaultsContext::GetClassDefaultObject () const inline
Definition at line 95 of file IAnimBlueprintCopyTermDefaultsContext.h.
References GetClassDefaultObjectImpl().
GetClassDefaultObjectImpl()
virtual UObject * IAnimBlueprintExtensionCopyTermDefaultsContext::GetClassDefaultObjectImpl () const protected pure virtual
Referenced by GetClassDefaultObject().
GetDestinationPtr()
uint8 * IAnimBlueprintExtensionCopyTermDefaultsContext::GetDestinationPtr () const inline
Definition at line 101 of file IAnimBlueprintCopyTermDefaultsContext.h.
References GetDestinationPtrImpl().
GetDestinationPtrImpl()
virtual uint8 * IAnimBlueprintExtensionCopyTermDefaultsContext::GetDestinationPtrImpl () const protected pure virtual
Referenced by GetDestinationPtr().
GetNodePropertyIndex()
int32 IAnimBlueprintExtensionCopyTermDefaultsContext::GetNodePropertyIndex () const inline
Definition at line 107 of file IAnimBlueprintCopyTermDefaultsContext.h.
References GetNodePropertyIndexImpl().
GetNodePropertyIndexImpl()
virtual int32 IAnimBlueprintExtensionCopyTermDefaultsContext::GetNodePropertyIndexImpl () const protected pure virtual
Referenced by GetNodePropertyIndex().
GetSourcePtr()
const uint8 * IAnimBlueprintExtensionCopyTermDefaultsContext::GetSourcePtr () const inline
Definition at line 104 of file IAnimBlueprintCopyTermDefaultsContext.h.
References GetSourcePtrImpl().
GetSourcePtrImpl()
virtual const uint8 * IAnimBlueprintExtensionCopyTermDefaultsContext::GetSourcePtrImpl () const protected pure virtual
Referenced by GetSourcePtr().
GetTargetProperty()
const FProperty * IAnimBlueprintExtensionCopyTermDefaultsContext::GetTargetProperty () const inline
Definition at line 98 of file IAnimBlueprintCopyTermDefaultsContext.h.
References GetTargetPropertyImpl().
GetTargetPropertyImpl()
virtual const FProperty * IAnimBlueprintExtensionCopyTermDefaultsContext::GetTargetPropertyImpl () const protected pure virtual
Referenced by GetTargetProperty().
The documentation for this class was generated from the following file:
Editor/AnimGraph/Public/IAnimBlueprintCopyTermDefaultsContext.h