Unreal Engine 5.6 C++ API: UE::Geometry::TMeshSpatialSort< TriangleMeshType > Class Template Reference
UE::Geometry::TMeshSpatialSort< TriangleMeshType > Class Template Reference
Sorts a list meshes into a list of "Nests" where each Nest has an outer shell mesh and a list of contained-inside meshes.
#include "MeshSpatialSort.h"
Data Structures
struct FMeshNesting
Outputs.
Public Types
enum class ENestingMethod { InLargestParent , InSmallestParent }
Public Member Functions
TMeshSpatialSort ()
TMeshSpatialSort (TArrayView< const TriangleMeshType > InputMeshes, TArrayView< const FAxisAlignedBox3d > MeshBoundsIn=TArrayView< const FAxisAlignedBox3d >())
void Compute ()
Data Fields
bool bOnlyCheckSingleVertexForNesting = true
If true, we assume meshes don't intersect, so we can check if a whole mesh is inside another by testing a single vertex If false, we only consider a mesh inside another if every vertex of the smaller is inside the larger.
bool bOnlyNestNegativeVolumes = false
If true, only negative-volume meshes can be nested (i.e., can be included in an FMeshNesting InnerIndices array)
bool bOnlyParentPostiveVolumes = true
If true, only positive-volume meshes can be assigned the "OuterIndex" of an FMeshNesting Leads to more logical nesting, but note: if true, a negative volume that isn't inside any positive volume mesh will not show up in any nests at all.
TArrayView< const TriangleMeshType > InputMeshes
Meshes to be spatially sorted.
TArray< FAxisAlignedBox3d > MeshBounds
Optional array of bounding boxes for each mesh.
ENestingMethod NestingMethod = ENestingMethod::InLargestParent
Which algorithm is used to determine nesting.
TArray< FMeshNesting > Nests
Computed nests.
TArray< int > SkippedMeshIndices
Indices of meshes that are not included in the "Nests" output, e.g.
Private Member Functions
void InitBounds ()
Detailed Description
template<class TriangleMeshType>
class UE::Geometry::TMeshSpatialSort< TriangleMeshType >
Sorts a list meshes into a list of "Nests" where each Nest has an outer shell mesh and a list of contained-inside meshes.
For example, if you have a "Russian nesting doll" arrangement of meshes [A,B,C,D] where A holds B holds C holds D:
If NestingMethod is InSmallestParent, the output will be: Nest 1: Outer: A, Inner: B, Parent: Invalid Nest 2: Outer; C, Inner: D, Parent: B Nest 1 conceptually corresponds to the outer and inner walls of the first doll, and Nest 2 the same of the second doll. (Note if the orientation-related booleans are set to true, this would only hold if the mesh orientations are also alternating)
If NestingMethod is InLargestParent, the output will be: Nest 1: Outer: A; Inner: B, C, D; Parent: Invalid In this case Nest 1 conceptually corresponds to there being a single outer structure, and the inner structure is left unsorted (Note for InLargestParent mode, you typically want bOnlyNestNegativeVolumes to be false)
For similar functionality in 2D, see the TPlanarComplex class
Definition at line 34 of file MeshSpatialSort.h.
Member Enumeration Documentation
ENestingMethod
template<class TriangleMeshType> enum class UE::Geometry::TMeshSpatialSort::ENestingMethod strong
Enumerator
InLargestParent
InSmallestParent
Definition at line 48 of file MeshSpatialSort.h.
Constructor & Destructor Documentation
TMeshSpatialSort() [1/2]
template<class TriangleMeshType> UE::Geometry::TMeshSpatialSort< TriangleMeshType >::TMeshSpatialSort () inline
Definition at line 96 of file MeshSpatialSort.h.
TMeshSpatialSort() [2/2]
template<class TriangleMeshType> UE::Geometry::TMeshSpatialSort< TriangleMeshType >::TMeshSpatialSort (TArrayView< const TriangleMeshType > InputMeshes, TArrayView< const FAxisAlignedBox3d > MeshBoundsIn = TArrayView<const FAxisAlignedBox3d>()) inline
Definition at line 98 of file MeshSpatialSort.h.
References InputMeshes.
Member Function Documentation
Compute()
template<class TriangleMeshType> void UE::Geometry::TMeshSpatialSort< TriangleMeshType >::Compute () inline
Definition at line 111 of file MeshSpatialSort.h.
References TMathUtil< double >::Abs(), TArray< InElementType, InAllocatorType >::Add(), bOnlyCheckSingleVertexForNesting, bOnlyNestNegativeVolumes, bOnlyParentPostiveVolumes, UE::Geometry::TAxisAlignedBox3< RealType >::Contain(), ensure, UE::Geometry::TFastWindingTree< TriangleMeshType >::FastWindingNumber(), UE::Geometry::TMeshQueries< TriangleMeshType >::GetVolumeNonWatertight(), Info, InitBounds(), InLargestParent, UE::Geometry::TMeshSpatialSort< TriangleMeshType >::FMeshNesting::InnerIndices, InputMeshes, InSmallestParent, KINDA_SMALL_NUMBER, UE::Geometry::TAxisAlignedBox3< RealType >::MaxDim(), MeshBounds, NestingMethod, Nests, UE::Geometry::TMeshSpatialSort< TriangleMeshType >::FMeshNesting::OuterIndex, Parent, UE::Geometry::TMeshSpatialSort< TriangleMeshType >::FMeshNesting::ParentIndex, TArray< InElementType, InAllocatorType >::SetNum(), TArray< InElementType, InAllocatorType >::SetNumZeroed(), SkippedMeshIndices, TArray< InElementType, InAllocatorType >::Sort(), and UE::Geometry::Volume.
InitBounds()
template<class TriangleMeshType> void UE::Geometry::TMeshSpatialSort< TriangleMeshType >::InitBounds () inline private
Definition at line 280 of file MeshSpatialSort.h.
References UE::Geometry::TMeshQueries< TriangleMeshType >::GetBounds(), InputMeshes, UE::Geometry::Mesh, and MeshBounds.
Referenced by Compute().
Field Documentation
bOnlyCheckSingleVertexForNesting
template<class TriangleMeshType> bool UE::Geometry::TMeshSpatialSort< TriangleMeshType >::bOnlyCheckSingleVertexForNesting = true
If true, we assume meshes don't intersect, so we can check if a whole mesh is inside another by testing a single vertex If false, we only consider a mesh inside another if every vertex of the smaller is inside the larger.
Definition at line 74 of file MeshSpatialSort.h.
Referenced by Compute().
bOnlyNestNegativeVolumes
template<class TriangleMeshType> bool UE::Geometry::TMeshSpatialSort< TriangleMeshType >::bOnlyNestNegativeVolumes = false
If true, only negative-volume meshes can be nested (i.e., can be included in an FMeshNesting InnerIndices array)
Definition at line 62 of file MeshSpatialSort.h.
Referenced by Compute().
bOnlyParentPostiveVolumes
template<class TriangleMeshType> bool UE::Geometry::TMeshSpatialSort< TriangleMeshType >::bOnlyParentPostiveVolumes = true
If true, only positive-volume meshes can be assigned the "OuterIndex" of an FMeshNesting Leads to more logical nesting, but note: if true, a negative volume that isn't inside any positive volume mesh will not show up in any nests at all.
Definition at line 68 of file MeshSpatialSort.h.
Referenced by Compute().
InputMeshes
template<class TriangleMeshType> TArrayView<const TriangleMeshType> UE::Geometry::TMeshSpatialSort< TriangleMeshType >::InputMeshes
Meshes to be spatially sorted.
Definition at line 41 of file MeshSpatialSort.h.
Referenced by TMeshSpatialSort(), Compute(), and InitBounds().
MeshBounds
template<class TriangleMeshType> TArray<FAxisAlignedBox3d> UE::Geometry::TMeshSpatialSort< TriangleMeshType >::MeshBounds
Optional array of bounding boxes for each mesh.
Definition at line 46 of file MeshSpatialSort.h.
Referenced by Compute(), and InitBounds().
NestingMethod
template<class TriangleMeshType> ENestingMethod UE::Geometry::TMeshSpatialSort< TriangleMeshType >::NestingMethod = ENestingMethod::InLargestParent
Which algorithm is used to determine nesting.
Definition at line 57 of file MeshSpatialSort.h.
Referenced by Compute().
Nests
template<class TriangleMeshType> TArray<FMeshNesting> UE::Geometry::TMeshSpatialSort< TriangleMeshType >::Nests
Computed nests.
Definition at line 89 of file MeshSpatialSort.h.
Referenced by Compute().
SkippedMeshIndices
template<class TriangleMeshType> TArray<int> UE::Geometry::TMeshSpatialSort< TriangleMeshType >::SkippedMeshIndices
Indices of meshes that are not included in the "Nests" output, e.g.
negative-volume meshes that are not inside any positive-volume mesh if bOnlyParentPostiveVolumes
Definition at line 94 of file MeshSpatialSort.h.
Referenced by Compute().
The documentation for this class was generated from the following file:
Runtime/GeometryCore/Public/Spatial/MeshSpatialSort.h