Unreal Engine 5.6 C++ API: UE::ChaosDeformable::FIndexArrayBufferWithSRV Class Reference
UE::ChaosDeformable::FIndexArrayBufferWithSRV Class Reference
Integral GPU buffer compacting int32 to the smallest possible of uint8, uint16, or uint32.
#include "ChaosDeformableGPUBuffers.h"
Public Member Functions
void Force32BitPacking ()
uint32 GetBufferSize () const
int32 GetDataStride () const
FString GetFriendlyName () const override
int32 GetNumValues () const
int32 GetOffset () const
void Init (const FIntVector2 *InArray, const int32 Num)
void Init (const FIntVector3 *InArray, const int32 Num)
void Init (const FIntVector4 *InArray, const int32 Num)
void Init (const int32 *InArray, const int32 Num)
Convert float to uint8 with clamping, and optionaly shifting via MultOffset.
void Init (const TArray< FIntVector4 > &InArray)
void Init (const TArray< int32 > &InArray)
void Init (const uint32 *InArray, const int32 Num)
void InitRHI (FRHICommandListBase &RHICmdList) override
FRenderResource overrides.
void SetBufferName (const FString &InBufferName)
Public Member Functions inherited from FVertexBufferWithSRV
RENDERCORE_API FVertexBufferWithSRV ()
RENDERCORE_API ~FVertexBufferWithSRV ()
virtual RENDERCORE_API void ReleaseRHI () override
Releases the RHI resources used by this resource.
Public Member Functions inherited from FVertexBuffer
RENDERCORE_API FVertexBuffer ()
RENDERCORE_API FVertexBuffer (const FVertexBuffer &)
virtual RENDERCORE_API ~FVertexBuffer ()
const FBufferRHIRef & GetRHI () const
RENDERCORE_API FVertexBuffer & operator= (const FVertexBuffer &Other)
RENDERCORE_API void SetRHI (const FBufferRHIRef &BufferRHI)
Public Member Functions inherited from FRenderResource
RENDERCORE_API FRenderResource ()
Default constructor.
RENDERCORE_API FRenderResource (const FRenderResource &)
Misc copy/assignment.
RENDERCORE_API FRenderResource (ERHIFeatureLevel::Type InFeatureLevel)
Constructor when we know what feature level this resource should support.
RENDERCORE_API FRenderResource (FRenderResource &&)
virtual RENDERCORE_API ~FRenderResource ()
Destructor used to catch unreleased resources.
EInitPhase GetInitPhase () const
int32 GetListIndex () const
FName GetOwnerName () const
FName GetResourceName () const
virtual RENDERCORE_API void InitResource (FRHICommandListBase &RHICmdList)
Initializes the resource.
FORCEINLINE bool IsInitialized () const
RENDERCORE_API FRenderResource & operator= (const FRenderResource &Other)
RENDERCORE_API FRenderResource & operator= (FRenderResource &&Other)
virtual RENDERCORE_API void ReleaseResource ()
Prepares the resource for deletion.
void SetOwnerName (FName InOwnerName)
SetOwnerName should be called before BeginInitResource for the owner name to be successfully tracked.
void SetResourceName (FName InResourceName)
RENDERCORE_API void UpdateRHI (FRHICommandListBase &RHICmdList)
If the resource's RHI resources have been initialized, then release and reinitialize it.
Private Attributes
TArray< uint32 > Array
bool bForce32 = false
FString BufferName
bool bUint16 = false
bool bUint8 = false
End FRenderResource overrides.
int32 NumValues = INDEX_NONE
int32 Offset = 0
Additional Inherited Members
Public Types inherited from FRenderResource
enum class EInitPhase : uint8 { Pre , Default , MAX }
Controls initialization order of render resources.
Static Public Member Functions inherited from FRenderResource
static RENDERCORE_API void ChangeFeatureLevel (ERHIFeatureLevel::Type NewFeatureLevel)
Reinitializes render resources at a new feature level.
static RENDERCORE_API void InitPreRHIResources ()
Initialize all resources initialized before the RHI was initialized.
static RENDERCORE_API void ReleaseRHIForAllResources ()
Release all render resources that are currently initialized.
Data Fields inherited from FVertexBufferWithSRV
FShaderResourceViewRHIRef ShaderResourceViewRHI
SRV that views the entire texture.
FUnorderedAccessViewRHIRef UnorderedAccessViewRHI
optional UAV that views the entire texture
Data Fields inherited from FVertexBuffer
FBufferRHIRef VertexBufferRHI
Data Fields inherited from FRenderResource
ERenderResourceState ResourceState = ERenderResourceState::Default
Protected Member Functions inherited from FRenderResource
template<typename T>
FBufferRHIRef CreateRHIBuffer (FRHICommandListBase &RHICmdList, T &InOutResourceObject, uint32 ResourceCount, EBufferUsageFlags InBufferUsageFlags, const TCHAR *InDebugName)
const FStaticFeatureLevel GetFeatureLevel () const
FORCEINLINE bool HasValidFeatureLevel () const
void SetFeatureLevel (const FStaticFeatureLevel InFeatureLevel)
void SetInitPhase (EInitPhase InInitPhase)
Static Protected Member Functions inherited from FRenderResource
static RENDERCORE_API FRHICommandListBase & GetImmediateCommandList ()
Detailed Description
Integral GPU buffer compacting int32 to the smallest possible of uint8, uint16, or uint32.
Definition at line 69 of file ChaosDeformableGPUBuffers.h.
Member Function Documentation
Force32BitPacking()
void UE::ChaosDeformable::FIndexArrayBufferWithSRV::Force32BitPacking () inline
Definition at line 83 of file ChaosDeformableGPUBuffers.h.
References bForce32.
GetBufferSize()
uint32 UE::ChaosDeformable::FIndexArrayBufferWithSRV::GetBufferSize () const
GetDataStride()
int32 UE::ChaosDeformable::FIndexArrayBufferWithSRV::GetDataStride () const inline
Definition at line 86 of file ChaosDeformableGPUBuffers.h.
References bForce32, bUint16, and bUint8.
GetFriendlyName()
FString UE::ChaosDeformable::FIndexArrayBufferWithSRV::GetFriendlyName () const inline override virtual
Returns
The resource's friendly name. Typically a UObject name.
Reimplemented from FVertexBuffer.
Definition at line 92 of file ChaosDeformableGPUBuffers.h.
References BufferName.
GetNumValues()
int32 UE::ChaosDeformable::FIndexArrayBufferWithSRV::GetNumValues () const inline
Definition at line 85 of file ChaosDeformableGPUBuffers.h.
References NumValues.
GetOffset()
int32 UE::ChaosDeformable::FIndexArrayBufferWithSRV::GetOffset () const inline
Definition at line 87 of file ChaosDeformableGPUBuffers.h.
References Offset.
Init() [1/7]
void UE::ChaosDeformable::FIndexArrayBufferWithSRV::Init (const FIntVector2 * InArray, const int32 Num) inline
Definition at line 78 of file ChaosDeformableGPUBuffers.h.
References Init(), Num, and X.
Referenced by Init().
Init() [2/7]
void UE::ChaosDeformable::FIndexArrayBufferWithSRV::Init (const FIntVector3 * InArray, const int32 Num) inline
Definition at line 79 of file ChaosDeformableGPUBuffers.h.
References Init(), Num, and X.
Referenced by Init().
Init() [3/7]
void UE::ChaosDeformable::FIndexArrayBufferWithSRV::Init (const FIntVector4 * InArray, const int32 Num) inline
Definition at line 80 of file ChaosDeformableGPUBuffers.h.
References Init(), Num, and X.
Referenced by Init().
Init() [4/7]
void UE::ChaosDeformable::FIndexArrayBufferWithSRV::Init (const int32 * InArray, const int32 Num)
Convert float to uint8 with clamping, and optionaly shifting via MultOffset.
References Num.
Init() [5/7]
void UE::ChaosDeformable::FIndexArrayBufferWithSRV::Init (const TArray< FIntVector4 > & InArray) inline
Definition at line 81 of file ChaosDeformableGPUBuffers.h.
References Init(), and TArray< InElementType, InAllocatorType >::Num().
Referenced by Init().
Init() [6/7]
void UE::ChaosDeformable::FIndexArrayBufferWithSRV::Init (const TArray< int32 > & InArray) inline
Definition at line 77 of file ChaosDeformableGPUBuffers.h.
References Init(), and TArray< InElementType, InAllocatorType >::Num().
Referenced by Init().
Init() [7/7]
void UE::ChaosDeformable::FIndexArrayBufferWithSRV::Init (const uint32 * InArray, const int32 Num)
References Num.
InitRHI()
void UE::ChaosDeformable::FIndexArrayBufferWithSRV::InitRHI (FRHICommandListBase & RHICmdList) override virtual
FRenderResource overrides.
Reimplemented from FRenderResource.
SetBufferName()
void UE::ChaosDeformable::FIndexArrayBufferWithSRV::SetBufferName (const FString & InBufferName) inline
Definition at line 72 of file ChaosDeformableGPUBuffers.h.
References BufferName.
Field Documentation
Array
TArray<uint32> UE::ChaosDeformable::FIndexArrayBufferWithSRV::Array private
Definition at line 101 of file ChaosDeformableGPUBuffers.h.
bForce32
bool UE::ChaosDeformable::FIndexArrayBufferWithSRV::bForce32 = false private
Definition at line 97 of file ChaosDeformableGPUBuffers.h.
Referenced by Force32BitPacking(), and GetDataStride().
BufferName
FString UE::ChaosDeformable::FIndexArrayBufferWithSRV::BufferName private
Definition at line 100 of file ChaosDeformableGPUBuffers.h.
Referenced by GetFriendlyName(), and SetBufferName().
bUint16
bool UE::ChaosDeformable::FIndexArrayBufferWithSRV::bUint16 = false private
Definition at line 96 of file ChaosDeformableGPUBuffers.h.
Referenced by GetDataStride().
bUint8
bool UE::ChaosDeformable::FIndexArrayBufferWithSRV::bUint8 = false private
End FRenderResource overrides.
Definition at line 95 of file ChaosDeformableGPUBuffers.h.
Referenced by GetDataStride().
NumValues
int32 UE::ChaosDeformable::FIndexArrayBufferWithSRV::NumValues = INDEX_NONE private
Definition at line 99 of file ChaosDeformableGPUBuffers.h.
Referenced by GetNumValues().
Offset
int32 UE::ChaosDeformable::FIndexArrayBufferWithSRV::Offset = 0 private
Definition at line 98 of file ChaosDeformableGPUBuffers.h.
Referenced by GetOffset().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Experimental/ChaosFlesh/Source/ChaosFleshEngine/Public/ChaosFlesh/ChaosDeformableGPUBuffers.h