Unreal Engine 5.6 C++ API: FReimportManager Class Reference
FReimportManager Class Reference
Reimport manager for package resources with associated source files on disk.
#include "EditorReimportHandler.h"
Public Member Functions
virtual void AddReferencedObjects (FReferenceCollector &Collector) override
FGCObject interface.
virtual UNREALED_API bool CanReimport (UObject *Obj, TArray< FString > *ReimportSourceFilenames=nullptr) const
Check to see if we have a handler to manage the reimporting of the object.
DECLARE_MULTICAST_DELEGATE_OneParam (FPreReimportNotification, UObject *)
Gets the delegate that's fired prior to reimporting an asset.
DECLARE_MULTICAST_DELEGATE_TwoParams (FPostReimportNotification, UObject *, bool)
Gets the delegate that's fired after to reimporting an asset.
UNREALED_API void GetNewReimportPath (UObject *Obj, TArray< FString > &InOutFilenames, int32 SourceFileIndex=INDEX_NONE)
Opens a file dialog to request a new reimport path.
virtual FString GetReferencerName () const override
Overload this method to report a name for your referencer.
FPostReimportNotification & OnPostReimport ()
FPreReimportNotification & OnPreReimport ()
UNREALED_API void RegisterHandler (FReimportHandler &InHandler)
Register a reimport handler with the manager.
virtual UNREALED_API bool Reimport (UObject *Obj, bool bAskForNewFileIfMissing=false, bool bShowNotification=true, FString PreferredReimportFile=TEXT(""), FReimportHandler *SpecifiedReimportHandler=nullptr, int32 SourceFileIndex=INDEX_NONE, bool bForceNewFile=false, bool bAutomated=false, bool bInForceShowDialog=false)
Attempt to reimport the specified object from its source by giving registered reimport handlers a chance to try to reimport the object.
virtual UNREALED_API UE::Interchange::FAssetImportResultRef ReimportAsync (UObject *Obj, bool bAskForNewFileIfMissing=false, bool bShowNotification=true, FString PreferredReimportFile=TEXT(""), FReimportHandler *SpecifiedReimportHandler=nullptr, int32 SourceFileIndex=INDEX_NONE, bool bInForceNewFile=false, bool bAutomated=false, bool bForceShowDialog=false)
Attempt to reimport the specified object from its source by giving registered reimport handlers a chance to try to reimport the object.
virtual UNREALED_API bool ReimportMultiple (TArrayView< UObject * > Objects, bool bAskForNewFileIfMissing=false, bool bShowNotification=true, FString PreferredReimportFile=TEXT(""), FReimportHandler *SpecifiedReimportHandler=nullptr, int32 SourceFileIndex=INDEX_NONE, bool bForceNewFile=false, bool bAutomated=false)
Attempt to reimport multiple objects from its source by giving registered reimport handlers a chance to try to reimport the object.
UNREALED_API void UnregisterHandler (FReimportHandler &InHandler)
Unregister a reimport handler from the manager.
virtual UNREALED_API void UpdateReimportPath (UObject *Obj, const FString &Filename, int32 SourceFileIndex)
Update the reimport paths for the specified object.
virtual UNREALED_API void UpdateReimportPaths (UObject *Obj, const TArray< FString > &InFilenames)
Update the reimport paths for the specified object.
virtual UNREALED_API void ValidateAllSourceFileAndReimport (TArray< UObject * > &ToImportObjects, bool bShowNotification=true, int32 SourceFileIndex=INDEX_NONE, bool bForceNewFile=false, bool bAutomated=false)
Attemp to reimport all specified objects.
Static Public Member Functions
static UNREALED_API FReimportManager * Instance ()
Singleton function, provides access to the only instance of the class.
Private Member Functions
FReimportManager ()
Constructor.
FReimportManager (const FReimportManager &)
Copy constructor; intentionally left unimplemented.
~FReimportManager ()
Destructor.
void OnInterchangePostReimported (UObject *ReimportAsset) const
FReimportManager & operator= (const FReimportManager &)
Assignment operator; intentionally left unimplemented.
void SortHandlersIfNeeded ()
Sort Reimport handlers by priority if they are unsorted.
Private Member Functions inherited from FGCObject
FGCObject ()
Tells the global object that forwards AddReferencedObjects calls on to objects that a new object is requiring AddReferencedObjects call.
FGCObject (const FGCObject &Other)
FGCObject (EFlags Flags)
FGCObject (FGCObject &&Other)
virtual ~FGCObject ()
virtual bool GetReferencerPropertyName (UObject *Object, FString &OutPropertyName) const
Overload this method to report how the specified object is referenced, if necessary.
FGCObject & operator= (const FGCObject &)
FGCObject & operator= (FGCObject &&)
void RegisterGCObject ()
Register with GC, only needed if constructed with EFlags::RegisterLater or after unregistering.
void UnregisterGCObject ()
Unregister ahead of destruction.
Private Attributes
bool bHandlersNeedSorting
True when the Handlers array has been modified such that it needs sorting.
TArray< FReimportHandler * > Handlers
Reimport handlers registered with this manager.
FDelegateHandle InterchangePostReimportedDelegateHandle
FPostReimportNotification PostReimport
Delegate to call after the asset is reimported.
FPreReimportNotification PreReimport
Delegate to call before the asset is reimported.
Additional Inherited Members
Private Types inherited from FGCObject
enum class EFlags : uint32 { None = 0 , RegisterLater = 1 << 0 , AddStableNativeReferencesOnly = 1 << 1 }
Static Private Member Functions inherited from FGCObject
static void StaticInit ()
Initializes the global object referencer and adds it to the root set.
Static Private Attributes inherited from FGCObject
static UGCObjectReferencer * GGCObjectReferencer
The static object referencer object that is shared across all garbage collectible non-UObject objects.
Detailed Description
Reimport manager for package resources with associated source files on disk.
Definition at line 20 of file EditorReimportHandler.h.
Constructor & Destructor Documentation
FReimportManager() [1/2]
FReimportManager::FReimportManager () private
Constructor.
Referenced by FReimportManager(), Instance(), and operator=().
~FReimportManager()
FReimportManager::~FReimportManager () private
Destructor.
FReimportManager() [2/2]
FReimportManager::FReimportManager (const FReimportManager &) private
Copy constructor; intentionally left unimplemented.
References FReimportManager().
Member Function Documentation
AddReferencedObjects()
virtual void FReimportManager::AddReferencedObjects (FReferenceCollector & Collector) override virtual
FGCObject interface.
Implements FGCObject.
CanReimport()
virtual UNREALED_API bool FReimportManager::CanReimport (UObject * Obj, TArray< FString > * ReimportSourceFilenames = nullptr) const virtual
Check to see if we have a handler to manage the reimporting of the object.
Parameters
Obj Object we want to reimport
Returns
true if the object is capable of reimportatio
DECLARE_MULTICAST_DELEGATE_OneParam()
FReimportManager::DECLARE_MULTICAST_DELEGATE_OneParam (FPreReimportNotification , UObject *)
Gets the delegate that's fired prior to reimporting an asset.
Returns
The event delegate.
DECLARE_MULTICAST_DELEGATE_TwoParams()
FReimportManager::DECLARE_MULTICAST_DELEGATE_TwoParams (FPostReimportNotification , UObject * , bool)
Gets the delegate that's fired after to reimporting an asset.
Parameters
Whether the reimport was a success
Returns
The event delegate.
GetNewReimportPath()
UNREALED_API void FReimportManager::GetNewReimportPath (UObject * Obj, TArray< FString > & InOutFilenames, int32 SourceFileIndex = INDEX_NONE)
Opens a file dialog to request a new reimport path.
References INDEX_NONE.
GetReferencerName()
virtual FString FReimportManager::GetReferencerName () const inline override virtual
Overload this method to report a name for your referencer.
Implements FGCObject.
Definition at line 152 of file EditorReimportHandler.h.
References TEXT.
Instance()
UNREALED_API FReimportManager * FReimportManager::Instance () static
Singleton function, provides access to the only instance of the class.
Returns
Singleton instance of the manager
References FReimportManager().
Referenced by FReimportHandler::FReimportHandler(), and FReimportHandler::~FReimportHandler().
OnInterchangePostReimported()
void FReimportManager::OnInterchangePostReimported (UObject * ReimportAsset) const private
OnPostReimport()
FPostReimportNotification & FReimportManager::OnPostReimport () inline
Definition at line 145 of file EditorReimportHandler.h.
References PostReimport.
OnPreReimport()
FPreReimportNotification & FReimportManager::OnPreReimport () inline
Definition at line 136 of file EditorReimportHandler.h.
References PreReimport.
operator=()
FReimportManager & FReimportManager::operator= (const FReimportManager &) private
Assignment operator; intentionally left unimplemented.
References FReimportManager().
RegisterHandler()
UNREALED_API void FReimportManager::RegisterHandler (FReimportHandler & InHandler)
Register a reimport handler with the manager.
Parameters
InHandler Handler to register with the manager
Referenced by FReimportHandler::FReimportHandler().
Reimport()
virtual UNREALED_API bool FReimportManager::Reimport (UObject * Obj, bool bAskForNewFileIfMissing = false, bool bShowNotification = true, FString PreferredReimportFile = TEXT(""), FReimportHandler * SpecifiedReimportHandler = nullptr, int32 SourceFileIndex = INDEX_NONE, bool bForceNewFile = false, bool bAutomated = false, bool bInForceShowDialog = false) virtual
Attempt to reimport the specified object from its source by giving registered reimport handlers a chance to try to reimport the object.
Parameters
Obj Object to try reimporting
bAskForNewFileIfMissing If the file is missing, open a dialog to ask for a new one
bShowNotification True to show a notification when complete, false otherwise
PreferredReimportFile if not empty, will be use in case the original file is missing and bAskForNewFileIfMissing is set to false
SourceFileIndex which source file index you want to reimport default is INDEX_NONE(the factory will choose)
bAutomated True to skip dialog prompts
Returns
true if the object was handled by one of the reimport handlers; false otherwise
References INDEX_NONE.
ReimportAsync()
virtual UNREALED_API UE::Interchange::FAssetImportResultRef FReimportManager::ReimportAsync (UObject * Obj, bool bAskForNewFileIfMissing = false, bool bShowNotification = true, FString PreferredReimportFile = TEXT(""), FReimportHandler * SpecifiedReimportHandler = nullptr, int32 SourceFileIndex = INDEX_NONE, bool bInForceNewFile = false, bool bAutomated = false, bool bForceShowDialog = false) virtual
Attempt to reimport the specified object from its source by giving registered reimport handlers a chance to try to reimport the object.
Parameters
Obj Object to try reimporting
bAskForNewFileIfMissing If the file is missing, open a dialog to ask for a new one
bShowNotification True to show a notification when complete, false otherwise
PreferredReimportFile if not empty, will be use in case the original file is missing and bAskForNewFileIfMissing is set to false
SourceFileIndex which source file index you want to reimport default is INDEX_NONE(the factory will choose)
bAutomated True to skip dialog prompts
Returns
FAssetImportResultRef
References INDEX_NONE.
ReimportMultiple()
virtual UNREALED_API bool FReimportManager::ReimportMultiple (TArrayView< UObject * > Objects, bool bAskForNewFileIfMissing = false, bool bShowNotification = true, FString PreferredReimportFile = TEXT(""), FReimportHandler * SpecifiedReimportHandler = nullptr, int32 SourceFileIndex = INDEX_NONE, bool bForceNewFile = false, bool bAutomated = false) virtual
Attempt to reimport multiple objects from its source by giving registered reimport handlers a chance to try to reimport the object.
Parameters
Objects Objects to try reimporting
bAskForNewFileIfMissing If the file is missing, open a dialog to ask for a new one
bShowNotification True to show a notification when complete, false otherwise
PreferredReimportFile if not empty, will be use in case the original file is missing and bAskForNewFileIfMissing is set to false
SourceFileIndex which source file index you want to reimport default is INDEX_NONE(the factory will choose)
bAutomated True to skip dialog prompts
Returns
true if the objects all imported successfully, for more granular success reporting use FReimportManager::Reimport
References INDEX_NONE.
SortHandlersIfNeeded()
void FReimportManager::SortHandlersIfNeeded () private
Sort Reimport handlers by priority if they are unsorted.
UnregisterHandler()
UNREALED_API void FReimportManager::UnregisterHandler (FReimportHandler & InHandler)
Unregister a reimport handler from the manager.
Parameters
InHandler Handler to unregister from the manager
Referenced by FReimportHandler::~FReimportHandler().
UpdateReimportPath()
virtual UNREALED_API void FReimportManager::UpdateReimportPath (UObject * Obj, const FString & Filename, int32 SourceFileIndex) virtual
Update the reimport paths for the specified object.
Parameters
Obj Object to update
Filename The files we want to set to its import paths
SourceFileIndex the source file index to set the filename
References Filename.
UpdateReimportPaths()
virtual UNREALED_API void FReimportManager::UpdateReimportPaths (UObject * Obj, const TArray< FString > & InFilenames) virtual
Update the reimport paths for the specified object.
Parameters
Obj Object to update
InFilenames The files we want to set to its import paths
ValidateAllSourceFileAndReimport()
virtual UNREALED_API void FReimportManager::ValidateAllSourceFileAndReimport (TArray< UObject * > & ToImportObjects, bool bShowNotification = true, int32 SourceFileIndex = INDEX_NONE, bool bForceNewFile = false, bool bAutomated = false) virtual
Attemp to reimport all specified objects.
This function will verify that all source file exist and ask the user to decide on how the system will handle asset with missing source file path. Choice are:
Browse every missing source file path before starting the import process
Skip all asset that have a missing source file path
Cancel the whole reimport command
Parameters
ToImportObjects Objects to try reimporting
Parameters
bShowNotification True to show a notification when complete, false otherwise
Parameters
SourceFileIndex which source file index you want to reimport default is INDEX_NONE(the factory will chooseP)
Parameters
bAutomated True to skip dialog prompts
References INDEX_NONE.
Field Documentation
bHandlersNeedSorting
bool FReimportManager::bHandlersNeedSorting private
True when the Handlers array has been modified such that it needs sorting.
Definition at line 167 of file EditorReimportHandler.h.
Handlers
TArray<FReimportHandler*> FReimportManager::Handlers private
Reimport handlers registered with this manager.
Definition at line 164 of file EditorReimportHandler.h.
InterchangePostReimportedDelegateHandle
FDelegateHandle FReimportManager::InterchangePostReimportedDelegateHandle private
Definition at line 175 of file EditorReimportHandler.h.
PostReimport
FPostReimportNotification FReimportManager::PostReimport private
Delegate to call after the asset is reimported.
Definition at line 173 of file EditorReimportHandler.h.
Referenced by OnPostReimport().
PreReimport
FPreReimportNotification FReimportManager::PreReimport private
Delegate to call before the asset is reimported.
Definition at line 170 of file EditorReimportHandler.h.
Referenced by OnPreReimport().
The documentation for this class was generated from the following file:
Editor/UnrealEd/Public/EditorReimportHandler.h