Unreal Engine 5.6 C++ API: FMyBlueprintCommands Class Reference
FMyBlueprintCommands Class Reference
#include "SMyBlueprint.h"
Public Member Functions
FMyBlueprintCommands ()
Constructor.
virtual void RegisterCommands () override
Initialize commands.
Public Member Functions inherited from FBindingContext
FBindingContext (const FBindingContext &)=default
FBindingContext (const FName InContextName, const FText &InContextDesc, const FName InContextParent, const FName InStyleSetName)
Constructor.
FBindingContext (FBindingContext &&)=default
void AddBundle (const FName Name, const FText &Desc)
Adds a new command bundle to this context that can be referenced by name from commands within the context.
const FText & GetBundleLabel (const FName Name)
Gets a localized label of a command bundle.
const FText & GetContextDesc () const
FName GetContextName () const
FName GetContextParent () const
FName GetStyleSetName () const
FUICommandInfoDecl NewCommand (const FName InCommandName, const FText &InCommandLabel, const FText &InCommandDesc)
Creates a new command declaration used to populate commands with data.
FBindingContext & operator= (const FBindingContext &)=default
FBindingContext & operator= (FBindingContext &&)=default
bool operator== (const FBindingContext &Other) const
Public Member Functions inherited from TSharedFromThis< FBindingContext >
TSharedRef< FBindingContext, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FBindingContext, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Data Fields
TSharedPtr< FUICommandInfo > DeleteEntry
TSharedPtr< FUICommandInfo > FocusNode
TSharedPtr< FUICommandInfo > FocusNodeInNewTab
TSharedPtr< FUICommandInfo > GotoNativeVarDefinition
TSharedPtr< FUICommandInfo > ImplementFunction
TSharedPtr< FUICommandInfo > MoveFunctionToParent
TSharedPtr< FUICommandInfo > MoveVariableToParent
TSharedPtr< FUICommandInfo > OpenExternalGraph
TSharedPtr< FUICommandInfo > OpenGraph
TSharedPtr< FUICommandInfo > OpenGraphInNewTab
TSharedPtr< FUICommandInfo > PasteFunction
TSharedPtr< FUICommandInfo > PasteLocalVariable
TSharedPtr< FUICommandInfo > PasteMacro
TSharedPtr< FUICommandInfo > PasteVariable
Additional Inherited Members
Static Public Member Functions inherited from TCommands< FMyBlueprintCommands >
static FMyBlueprintCommands & Get ()
Get the singleton instance of this set of commands.
static const FBindingContext & GetContext ()
Get the BindingContext for this set of commands.
static bool IsRegistered ()
static void Register ()
Use this method to register commands.
static void Unregister ()
Use this method to clean up any resources used by the command set.
Static Public Attributes inherited from FBindingContext
static FOnBindingContextChanged CommandsChanged
A delegate that is called when commands are registered or unregistered with a binding context.
Protected Member Functions inherited from TCommands< FMyBlueprintCommands >
TCommands (const FName InContextName, const FText &InContextDesc, const FName InContextParent, const FName InStyleSetName)
Construct a set of commands; call this from your custom commands class.
virtual ~TCommands ()
Protected Member Functions inherited from TSharedFromThis< FBindingContext >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions inherited from TCommands< FMyBlueprintCommands >
static TWeakPtr< FMyBlueprintCommands > & GetInstance ()
A static instance of the command set.
Static Protected Member Functions inherited from TSharedFromThis< FBindingContext >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
Definition at line 56 of file SMyBlueprint.h.
Constructor & Destructor Documentation
FMyBlueprintCommands()
FMyBlueprintCommands::FMyBlueprintCommands () inline
Constructor.
Definition at line 60 of file SMyBlueprint.h.
References FMyBlueprintCommands(), TCommands< FMyBlueprintCommands >::TCommands(), NSLOCTEXT, and TEXT.
Referenced by FMyBlueprintCommands().
Member Function Documentation
RegisterCommands()
virtual void FMyBlueprintCommands::RegisterCommands () override virtual
Initialize commands.
Implements TCommands< FMyBlueprintCommands >.
Field Documentation
DeleteEntry
TSharedPtr<FUICommandInfo> FMyBlueprintCommands::DeleteEntry
Definition at line 72 of file SMyBlueprint.h.
FocusNode
TSharedPtr<FUICommandInfo> FMyBlueprintCommands::FocusNode
Definition at line 69 of file SMyBlueprint.h.
FocusNodeInNewTab
TSharedPtr<FUICommandInfo> FMyBlueprintCommands::FocusNodeInNewTab
Definition at line 70 of file SMyBlueprint.h.
GotoNativeVarDefinition
TSharedPtr<FUICommandInfo> FMyBlueprintCommands::GotoNativeVarDefinition
Definition at line 77 of file SMyBlueprint.h.
ImplementFunction
TSharedPtr<FUICommandInfo> FMyBlueprintCommands::ImplementFunction
Definition at line 71 of file SMyBlueprint.h.
MoveFunctionToParent
TSharedPtr<FUICommandInfo> FMyBlueprintCommands::MoveFunctionToParent
Definition at line 79 of file SMyBlueprint.h.
MoveVariableToParent
TSharedPtr<FUICommandInfo> FMyBlueprintCommands::MoveVariableToParent
Definition at line 78 of file SMyBlueprint.h.
OpenExternalGraph
TSharedPtr<FUICommandInfo> FMyBlueprintCommands::OpenExternalGraph
Definition at line 68 of file SMyBlueprint.h.
OpenGraph
TSharedPtr<FUICommandInfo> FMyBlueprintCommands::OpenGraph
Definition at line 66 of file SMyBlueprint.h.
OpenGraphInNewTab
TSharedPtr<FUICommandInfo> FMyBlueprintCommands::OpenGraphInNewTab
Definition at line 67 of file SMyBlueprint.h.
PasteFunction
TSharedPtr<FUICommandInfo> FMyBlueprintCommands::PasteFunction
Definition at line 75 of file SMyBlueprint.h.
PasteLocalVariable
TSharedPtr<FUICommandInfo> FMyBlueprintCommands::PasteLocalVariable
Definition at line 74 of file SMyBlueprint.h.
PasteMacro
TSharedPtr<FUICommandInfo> FMyBlueprintCommands::PasteMacro
Definition at line 76 of file SMyBlueprint.h.
PasteVariable
TSharedPtr<FUICommandInfo> FMyBlueprintCommands::PasteVariable
Definition at line 73 of file SMyBlueprint.h.
The documentation for this class was generated from the following file:
Editor/Kismet/Public/SMyBlueprint.h