Unreal Engine 5.6 C++ API: Metasound::FLiteralNode Class Reference
Metasound::FLiteralNode Class Reference
TLiteralNode represents a variable within a metasound graph.
#include "MetasoundLiteralNode.h"
Public Member Functions
METASOUNDFRONTEND_API FLiteralNode (const FVertexName &InInstanceName, const FGuid &InInstanceID, const FName &InDataTypeName, EVertexAccessType InAccessType, FOperatorFactorySharedRef InFactory)
virtual METASOUNDFRONTEND_API TSharedRef< IOperatorFactory, ESPMode::ThreadSafe > GetDefaultOperatorFactory () const override
Return a reference to the default operator factory.
virtual METASOUNDFRONTEND_API const FVertexInterface & GetVertexInterface () const override
Return the current vertex interface.
virtual METASOUNDFRONTEND_API bool IsVertexInterfaceSupported (const FVertexInterface &InInterface) const override
virtual METASOUNDFRONTEND_API bool SetVertexInterface (const FVertexInterface &InInterface) override
Public Member Functions inherited from Metasound::FNode
METASOUNDGRAPHCORE_API FNode (const FVertexName &InInstanceName, const FGuid &InInstanceID, const FNodeClassMetadata &InInfo, TSharedPtr< const IOperatorData > InOperatorData={})
virtual ~FNode ()=default
virtual METASOUNDGRAPHCORE_API const FGuid & GetInstanceID () const override
Return the ID of this specific instance of the node class.
virtual METASOUNDGRAPHCORE_API const FVertexName & GetInstanceName () const override
Return the name of this specific instance of the node class.
virtual METASOUNDGRAPHCORE_API const FNodeClassMetadata & GetMetadata () const override
Return metadata associated with this node.
virtual METASOUNDGRAPHCORE_API TSharedPtr< const IOperatorData > GetOperatorData () const override
virtual METASOUNDGRAPHCORE_API void SetDefaultInput (const FVertexName &InVertexName, const FLiteral &InLiteral) override
Set the default input literal for a vertex.
Public Member Functions inherited from Metasound::INode
virtual ~INode ()
Public Member Functions inherited from Metasound::INodeBase
virtual ~INodeBase ()=default
UE_DEPRECATED (5.6, "INodeBase will not expose dynamic FVertexInterface operations") virtual bool IsVertexInterfaceSupported(const FVertexInterface &InInterface) const
Expresses whether a specific vertex interface is supported.
UE_DEPRECATED (5.6, "INodeBase will not expose dynamic FVertexInterface operations") virtual bool SetVertexInterface(const FVertexInterface &InInterface)
Set the vertex interface.
UE_EXPERIMENTAL (5.6, "Node operator data is still under development") virtual METASOUNDGRAPHCORE_API TSharedPtr< const IOperatorData > GetOperatorData() const
Returns the configuration for the node.
Static Public Member Functions
static METASOUNDFRONTEND_API FNodeClassMetadata GetNodeMetadata (const FName &InDataTypeName, EVertexAccessType InAccessType)
Static Protected Member Functions
static METASOUNDFRONTEND_API FVertexInterface CreateVertexInterface (const FName &InDataTypeName, EVertexAccessType InAccessType)
Private Attributes
FOperatorFactorySharedRef Factory
FVertexInterface Interface
Detailed Description
TLiteralNode represents a variable within a metasound graph.
Definition at line 150 of file MetasoundLiteralNode.h.
Constructor & Destructor Documentation
FLiteralNode()
METASOUNDFRONTEND_API Metasound::FLiteralNode::FLiteralNode (const FVertexName & InInstanceName, const FGuid & InInstanceID, const FName & InDataTypeName, EVertexAccessType InAccessType, FOperatorFactorySharedRef InFactory)
References UE_API.
Referenced by Metasound::TLiteralNode< DataType >::TLiteralNode().
Member Function Documentation
CreateVertexInterface()
METASOUNDFRONTEND_API FVertexInterface Metasound::FLiteralNode::CreateVertexInterface (const FName & InDataTypeName, EVertexAccessType InAccessType) static protected
References UE_API.
Referenced by Metasound::TLiteralNode< DataType >::UE_DEPRECATED().
GetDefaultOperatorFactory()
virtual METASOUNDFRONTEND_API TSharedRef< IOperatorFactory, ESPMode::ThreadSafe > Metasound::FLiteralNode::GetDefaultOperatorFactory () const override virtual
Return a reference to the default operator factory.
Implements Metasound::INode.
References UE_API.
GetNodeMetadata()
METASOUNDFRONTEND_API FNodeClassMetadata Metasound::FLiteralNode::GetNodeMetadata (const FName & InDataTypeName, EVertexAccessType InAccessType) static
References UE_API.
Referenced by Metasound::TLiteralNode< DataType >::GetNodeInfo().
GetVertexInterface()
virtual METASOUNDFRONTEND_API const FVertexInterface & Metasound::FLiteralNode::GetVertexInterface () const override virtual
Return the current vertex interface.
Reimplemented from Metasound::FNode.
References UE_API.
IsVertexInterfaceSupported()
virtual METASOUNDFRONTEND_API bool Metasound::FLiteralNode::IsVertexInterfaceSupported (const FVertexInterface & InInterface) const override virtual
References UE_API.
SetVertexInterface()
virtual METASOUNDFRONTEND_API bool Metasound::FLiteralNode::SetVertexInterface (const FVertexInterface & InInterface) override virtual
References UE_API.
Field Documentation
Factory
FOperatorFactorySharedRef Metasound::FLiteralNode::Factory private
Definition at line 171 of file MetasoundLiteralNode.h.
Interface
FVertexInterface Metasound::FLiteralNode::Interface private
Definition at line 170 of file MetasoundLiteralNode.h.
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/Metasound/Source/MetasoundFrontend/Public/MetasoundLiteralNode.h