Unreal Engine 5.6 C++ API: FLandscapeComponentSceneProxy::FLandscapeLCI Class Reference
FLandscapeComponentSceneProxy::FLandscapeLCI Class Reference final
Public Member Functions
FLandscapeLCI (const ULandscapeComponent *InComponent, ERHIFeatureLevel::Type FeatureLevel, bool bVFRequiresPrimitiveUniformBuffer)
Initialization constructor.
virtual FLightInteraction GetInteraction (const FLightSceneProxy *LightSceneProxy) const override
Public Member Functions inherited from FLightCacheInterface
virtual ~FLightCacheInterface ()
void CreatePrecomputedLightingUniformBuffer_RenderingThread (ERHIFeatureLevel::Type FeatureLevel)
virtual FLightInteraction GetInteraction (const class FLightSceneProxy *LightSceneProxy) const =0
const FLightMap * GetLightMap () const
FLightMapInteraction GetLightMapInteraction (ERHIFeatureLevel::Type InFeatureLevel) const
FRHIUniformBuffer * GetPrecomputedLightingBuffer () const
const FLightmapResourceCluster * GetResourceCluster () const
const FShadowMap * GetShadowMap () const
FShadowMapInteraction GetShadowMapInteraction (ERHIFeatureLevel::Type InFeatureLevel) const
ELightInteractionType GetStaticInteraction (const FLightSceneProxy *LightSceneProxy, const TArray< FGuid > &IrrelevantLights) const
bool GetVirtualTextureLightmapProducer (ERHIFeatureLevel::Type FeatureLevel, FVirtualTextureProducerHandle &OutProducerHandle)
void SetGlobalVolumeLightmap (bool bInGlobalVolumeLightmap)
void SetLightMap (const FLightMap *InLightMap)
void SetPrecomputedLightingBuffer (FRHIUniformBuffer *InPrecomputedLightingUniformBuffer)
void SetResourceCluster (const FLightmapResourceCluster *InResourceCluster)
void SetShadowMap (const FShadowMap *InShadowMap)
Private Attributes
TArray< FGuid > IrrelevantLights
Additional Inherited Members
Data Fields inherited from FLightCacheInterface
bool bCanUsePrecomputedLightingParametersFromGPUScene = false
Detailed Description
Definition at line 708 of file LandscapeRender.h.
Constructor & Destructor Documentation
FLandscapeLCI()
FLandscapeComponentSceneProxy::FLandscapeLCI::FLandscapeLCI (const ULandscapeComponent * InComponent, ERHIFeatureLevel::Type FeatureLevel, bool bVFRequiresPrimitiveUniformBuffer) inline
Initialization constructor.
Definition at line 712 of file LandscapeRender.h.
References FLightCacheInterface::bCanUsePrecomputedLightingParametersFromGPUScene, FPrimitiveSceneProxy::bVFRequiresPrimitiveUniformBuffer, IrrelevantLights, FLightCacheInterface::SetLightMap(), FLightCacheInterface::SetResourceCluster(), FLightCacheInterface::SetShadowMap(), and FLandscapeComponentSceneProxy::ULandscapeComponent.
Member Function Documentation
GetInteraction()
virtual FLightInteraction FLandscapeComponentSceneProxy::FLandscapeLCI::GetInteraction (const FLightSceneProxy * LightSceneProxy) const override virtual
Field Documentation
IrrelevantLights
TArray<FGuid> FLandscapeComponentSceneProxy::FLandscapeLCI::IrrelevantLights private
Definition at line 742 of file LandscapeRender.h.
Referenced by FLandscapeLCI().
The documentation for this class was generated from the following file:
Runtime/Landscape/Public/LandscapeRender.h