Unreal Engine 5.6 C++ API: FTextFilterString Class Reference
FTextFilterString Class Reference
String used by the text filter.
#include "TextFilterUtils.h"
Public Member Functions
FTextFilterString ()
Default constructor.
FTextFilterString (const FName &InName)
Construct from a name.
FTextFilterString (const FString &InString)
Construct from a string.
FTextFilterString (const FTextFilterString &Other)
Move and copy constructors.
FTextFilterString (const TCHAR *InString)
FTextFilterString (FString &&InString)
FTextFilterString (FTextFilterString &&Other)
FORCEINLINE FName AsName () const
Get the internal uppercase string of this filter string as an FName.
FORCEINLINE const FString & AsString () const
Get the internal uppercase string of this filter string.
bool CanCompareNumeric (const FTextFilterString &InOther) const
Are the two given strings able to be compared numberically?
bool CompareFString (const FString &InOther, const ETextFilterTextComparisonMode InTextComparisonMode) const
Compare this string against the other FString, using the text comparison mode provided.
bool CompareFStringView (FStringView InOther, const ETextFilterTextComparisonMode InTextComparisonMode) const
Compare this string against a string view which has previously been converted to uppercase.
bool CompareName (const FName &InOther, const ETextFilterTextComparisonMode InTextComparisonMode) const
Compare this string against the other FName, using the text comparison mode provided.
bool CompareNumeric (const FTextFilterString &InOther, const ETextFilterComparisonOperation InComparisonOperation) const
Compare this string against the other, converting them to numbers and using the comparison operator provided - you should have tested CanCompareNumeric first!
bool CompareText (const FTextFilterString &InOther, const ETextFilterTextComparisonMode InTextComparisonMode) const
Compare this string against the other, using the text comparison mode provided.
FORCEINLINE bool IsEmpty () const
Is the internal string empty?
FTextFilterString & operator= (const FTextFilterString &Other)
Move and copy assignment.
FTextFilterString & operator= (FTextFilterString &&Other)
Private Member Functions
void UppercaseInternalString ()
Inline convert our internal string to uppercase.
Private Attributes
FString InternalString
The uppercase string to use for comparisons.
TArray< ANSICHAR > InternalStringAnsi
The uppercase ANSI version of string to use for comparisons.
Detailed Description
String used by the text filter.
The given string will be stored as uppercase since filter text always performs case-insensitive string comparisons, so this will minimize ToUpper calls.
Definition at line 37 of file TextFilterUtils.h.
Constructor & Destructor Documentation
FTextFilterString() [1/7]
FTextFilterString::FTextFilterString ()
Default constructor.
Referenced by FTextFilterString(), FTextFilterString(), CanCompareNumeric(), CompareNumeric(), CompareText(), operator=(), and operator=().
FTextFilterString() [2/7]
FTextFilterString::FTextFilterString (const FTextFilterString & Other)
Move and copy constructors.
References FTextFilterString(), and Other.
FTextFilterString() [3/7]
FTextFilterString::FTextFilterString (FTextFilterString && Other)
References FTextFilterString(), and Other.
FTextFilterString() [4/7]
FTextFilterString::FTextFilterString (const FString & InString)
Construct from a string.
FTextFilterString() [5/7]
FTextFilterString::FTextFilterString (FString && InString)
FTextFilterString() [6/7]
FTextFilterString::FTextFilterString (const TCHAR * InString)
FTextFilterString() [7/7]
FTextFilterString::FTextFilterString (const FName & InName)
Construct from a name.
References InName.
Member Function Documentation
AsName()
FORCEINLINE FName FTextFilterString::AsName () const inline
Get the internal uppercase string of this filter string as an FName.
Definition at line 84 of file TextFilterUtils.h.
References FName, FORCEINLINE, and InternalString.
Referenced by TextFilterExpressionParser::FTextToken::EvaluateAsComplexExpression().
AsString()
FORCEINLINE const FString & FTextFilterString::AsString () const inline
Get the internal uppercase string of this filter string.
Definition at line 78 of file TextFilterUtils.h.
References FORCEINLINE, and InternalString.
CanCompareNumeric()
bool FTextFilterString::CanCompareNumeric (const FTextFilterString & InOther) const
Are the two given strings able to be compared numberically?
References FTextFilterString().
CompareFString()
bool FTextFilterString::CompareFString (const FString & InOther, const ETextFilterTextComparisonMode InTextComparisonMode) const
Compare this string against the other FString, using the text comparison mode provided.
Referenced by ISequencerTextFilterExpressionContext::CompareFStringForExactBool().
CompareFStringView()
bool FTextFilterString::CompareFStringView (FStringView InOther, const ETextFilterTextComparisonMode InTextComparisonMode) const
Compare this string against a string view which has previously been converted to uppercase.
CompareName()
bool FTextFilterString::CompareName (const FName & InOther, const ETextFilterTextComparisonMode InTextComparisonMode) const
Compare this string against the other FName, using the text comparison mode provided.
CompareNumeric()
bool FTextFilterString::CompareNumeric (const FTextFilterString & InOther, const ETextFilterComparisonOperation InComparisonOperation) const
Compare this string against the other, converting them to numbers and using the comparison operator provided - you should have tested CanCompareNumeric first!
References FTextFilterString().
CompareText()
bool FTextFilterString::CompareText (const FTextFilterString & InOther, const ETextFilterTextComparisonMode InTextComparisonMode) const
Compare this string against the other, using the text comparison mode provided.
References FTextFilterString().
IsEmpty()
FORCEINLINE bool FTextFilterString::IsEmpty () const inline
Is the internal string empty?
Definition at line 90 of file TextFilterUtils.h.
References FORCEINLINE, and InternalString.
operator=() [1/2]
FTextFilterString & FTextFilterString::operator= (const FTextFilterString & Other)
Move and copy assignment.
References FTextFilterString(), and Other.
operator=() [2/2]
FTextFilterString & FTextFilterString::operator= (FTextFilterString && Other)
References FTextFilterString(), and Other.
UppercaseInternalString()
void FTextFilterString::UppercaseInternalString () private
Inline convert our internal string to uppercase.
Field Documentation
InternalString
FString FTextFilterString::InternalString private
The uppercase string to use for comparisons.
Definition at line 100 of file TextFilterUtils.h.
Referenced by AsName(), AsString(), and IsEmpty().
InternalStringAnsi
TArray<ANSICHAR> FTextFilterString::InternalStringAnsi private
The uppercase ANSI version of string to use for comparisons.
Definition at line 103 of file TextFilterUtils.h.
The documentation for this class was generated from the following file:
Runtime/Core/Public/Misc/TextFilterUtils.h