Unreal Engine 5.6 C++ API: ULevelEditorMiscSettings Class Reference
ULevelEditorMiscSettings Class Reference
#include "LevelEditorMiscSettings.h"
Public Member Functions
UPROPERTY () bool bPromptWhenAddingToLevelBeforeCheckout
UPROPERTY () bool bPromptWhenAddingToLevelOutsideBounds
UPROPERTY () FDirectoryPath EditorScreenshotSaveDirectory
The save directory for newly created screenshots.
UPROPERTY() uint32 bAllowBackgroundAudio UPROPERTY() uint32 bCreateNewAudioDeviceForPlayInEditor UPROPERTY() uint32 bEnableRealTimeAudio UPROPERTY () float EditorVolumeLevel
If checked lighting will be automatically applied to the level after a static lighting build is complete.
UPROPERTY () FVector MinimumBoundsForCheckingSize
UPROPERTY () TSubclassOf< ULevelStreaming > DefaultLevelStreamingClass
Enables audio feedback for certain operations in Unreal Editor, such as entering and exiting Play mode.
UPROPERTY ()) float PercentageThresholdForPrompt
Protected Member Functions
virtual UNREALED_API void PostEditChangeProperty (struct FPropertyChangedEvent &PropertyChangedEvent) override
Detailed Description
Definition at line 18 of file LevelEditorMiscSettings.h.
Member Function Documentation
PostEditChangeProperty()
virtual UNREALED_API void ULevelEditorMiscSettings::PostEditChangeProperty (struct FPropertyChangedEvent & PropertyChangedEvent) override protected virtual
References PostEditChangeProperty().
Referenced by PostEditChangeProperty().
UPROPERTY() [1/7]
ULevelEditorMiscSettings::UPROPERTY ()
References Category, and config.
UPROPERTY() [2/7]
ULevelEditorMiscSettings::UPROPERTY ()
References Category, and config.
UPROPERTY() [3/7]
ULevelEditorMiscSettings::UPROPERTY ()
The save directory for newly created screenshots.
References Category, config, and UPROPERTY().
UPROPERTY() [4/7]
UPROPERTY() uint32 bAllowBackgroundAudio UPROPERTY() uint32 bCreateNewAudioDeviceForPlayInEditor UPROPERTY() uint32 bEnableRealTimeAudio ULevelEditorMiscSettings::UPROPERTY ()
If checked lighting will be automatically applied to the level after a static lighting build is complete.
Otherwise you will be prompted to apply it If true, BSP will auto-update If true, the pivot offset for BSP will be automatically moved to stay centered on its vertices If true, Navigation will auto-update If enabled, replacing actors will respect the scale of the original actor. Otherwise, the replaced actors will have a scale of 1.0 If enabled, will avoid relabeling actors in UUnrealEdEngine::edactPasteSelected If enabled, will force checking references during a delete. Note: disabling this is for advanced usage only and not recommended. If checked audio playing in the editor will continue to play even if the editor is in the background If checked, will create a new audio engine instance for the play-in-editor window. Otherwise, will re-use the audio device used in content browser. If true audio will be enabled in the editor. Does not affect PIE Global volume setting for the editor
References Category, config, and Sound.
Referenced by UPROPERTY(), and UPROPERTY().
UPROPERTY() [5/7]
ULevelEditorMiscSettings::UPROPERTY ()
References Category, config, FVector, and UPROPERTY().
UPROPERTY() [6/7]
ULevelEditorMiscSettings::UPROPERTY ()
Enables audio feedback for certain operations in Unreal Editor, such as entering and exiting Play mode.
The default level streaming class to use when adding new streaming levels
References Category, and config.
UPROPERTY() [7/7]
ULevelEditorMiscSettings::UPROPERTY ()
References Category, config, float, and Meta.
The documentation for this class was generated from the following file:
Editor/UnrealEd/Classes/Settings/LevelEditorMiscSettings.h