Unreal Engine 5.6 C++ API: IDisplayClusterLightCardEditorShaders Class Reference
IDisplayClusterLightCardEditorShaders Class Reference
Display Cluster Light Card Editor Shaders module interface.
#include "IDisplayClusterLightCardEditorShaders.h"
Public Member Functions
virtual ~IDisplayClusterLightCardEditorShaders ()=default
Public Member Functions inherited from IModuleInterface
virtual ~IModuleInterface ()
Note: Even though this is an interface class we need a virtual destructor here because modules are deleted via a pointer to this interface.
virtual bool IsGameModule () const
Returns true if this module hosts gameplay code.
virtual void PostLoadCallback ()
Called after the module has been reloaded.
virtual void PreUnloadCallback ()
Called before the module has been unloaded.
virtual void ShutdownModule ()
Called before the module is unloaded, right before the module object is destroyed.
virtual void StartupModule ()
Called right after the module DLL has been loaded and the module object has been created Load dependent modules here, and they will be guaranteed to be available during ShutdownModule.
virtual bool SupportsAutomaticShutdown ()
Override this to set whether your module would like cleanup on application shutdown.
virtual bool SupportsDynamicReloading ()
Override this to set whether your module is allowed to be unloaded on the fly.
Static Public Member Functions
static IDisplayClusterLightCardEditorShaders & Get ()
Singleton-like access to this module's interface.
static bool IsAvailable ()
Checks to see if this module is loaded and ready.
Static Public Attributes
static constexpr const TCHAR * ModuleName = TEXT("DisplayClusterLightCardEditorShaders")
Detailed Description
Display Cluster Light Card Editor Shaders module interface.
Definition at line 12 of file IDisplayClusterLightCardEditorShaders.h.
Constructor & Destructor Documentation
~IDisplayClusterLightCardEditorShaders()
virtual IDisplayClusterLightCardEditorShaders::~IDisplayClusterLightCardEditorShaders () virtual default
Member Function Documentation
Get()
IDisplayClusterLightCardEditorShaders & IDisplayClusterLightCardEditorShaders::Get () inline static
Singleton-like access to this module's interface.
This is just for convenience! Beware of calling this during the shutdown phase, though. Your module might have been unloaded already.
Returns
Returns singleton instance, loading the module on demand if needed
Definition at line 26 of file IDisplayClusterLightCardEditorShaders.h.
References FModuleManager::GetModuleChecked(), and ModuleName.
IsAvailable()
bool IDisplayClusterLightCardEditorShaders::IsAvailable () inline static
Checks to see if this module is loaded and ready.
It is only valid to call Get() if IsAvailable() returns true.
Returns
True if the module is loaded and ready to use
Definition at line 36 of file IDisplayClusterLightCardEditorShaders.h.
References FModuleManager::Get(), FModuleManager::IsModuleLoaded(), and ModuleName.
Field Documentation
ModuleName
const TCHAR* IDisplayClusterLightCardEditorShaders::ModuleName = TEXT("DisplayClusterLightCardEditorShaders") static constexpr
Definition at line 15 of file IDisplayClusterLightCardEditorShaders.h.
Referenced by Get(), and IsAvailable().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/nDisplay/Source/DisplayClusterLightCardEditorShaders/Public/IDisplayClusterLightCardEditorShaders.h