Unreal Engine 5.6 C++ API: UE::Geometry::FSmallListSet::MappedValueIterator Class Reference
UE::Geometry::FSmallListSet::MappedValueIterator Class Reference
MappedValueIterator iterates over the values of a small list An optional mapping function can be provided which will then be applied to the values returned by the * operator.
#include "SmallListSet.h"
Public Member Functions
MappedValueIterator ()
int32 operator* () const
const MappedValueIterator & operator++ ()
Public Member Functions inherited from UE::Geometry::FSmallListSet::BaseValueIterator
BaseValueIterator ()
bool operator!= (const BaseValueIterator &Other) const
bool operator== (const BaseValueIterator &Other) const
Protected Member Functions
MappedValueIterator (const FSmallListSet *ListSetIn, int32 ListIndex, bool is_end, TFunction< int32(int32)> MapFuncIn)
Protected Member Functions inherited from UE::Geometry::FSmallListSet::BaseValueIterator
BaseValueIterator (const FSmallListSet *ListSetIn, int32 ListIndex, bool is_end)
void GotoNext ()
void GotoNextOverflow ()
void SetToEnd ()
Protected Attributes
TFunction< int32(int32)> MapFunc
Protected Attributes inherited from UE::Geometry::FSmallListSet::BaseValueIterator
int32 block_ptr
int32 cur_ptr
int32 cur_value
int32 iCur
int32 iEnd
int32 ListIndex
const FSmallListSet * ListSet
int32 N
Friends
class FSmallListSet
Detailed Description
MappedValueIterator iterates over the values of a small list An optional mapping function can be provided which will then be applied to the values returned by the * operator.
Definition at line 585 of file SmallListSet.h.
Constructor & Destructor Documentation
MappedValueIterator() [1/2]
UE::Geometry::FSmallListSet::MappedValueIterator::MappedValueIterator () inline
Definition at line 588 of file SmallListSet.h.
References UE::Geometry::FSmallListSet::BaseValueIterator::BaseValueIterator(), and MapFunc.
Referenced by operator++().
MappedValueIterator() [2/2]
UE::Geometry::FSmallListSet::MappedValueIterator::MappedValueIterator (const FSmallListSet * ListSetIn, int32 ListIndex, bool is_end, TFunction< int32(int32)> MapFuncIn) inline protected
Definition at line 605 of file SmallListSet.h.
References UE::Geometry::FSmallListSet::BaseValueIterator::BaseValueIterator(), FSmallListSet, UE::Geometry::FSmallListSet::BaseValueIterator::ListIndex, and MapFunc.
Member Function Documentation
operator*()
int32 UE::Geometry::FSmallListSet::MappedValueIterator::operator* () const inline
Definition at line 593 of file SmallListSet.h.
References UE::Geometry::FSmallListSet::BaseValueIterator::cur_value, and MapFunc.
operator++()
const MappedValueIterator & UE::Geometry::FSmallListSet::MappedValueIterator::operator++ () inline
Definition at line 598 of file SmallListSet.h.
References MappedValueIterator(), and UE::Geometry::FSmallListSet::BaseValueIterator::GotoNext().
Friends And Related Symbol Documentation
FSmallListSet
friend class FSmallListSet friend
Definition at line 612 of file SmallListSet.h.
References FSmallListSet.
Referenced by MappedValueIterator(), and FSmallListSet.
Field Documentation
MapFunc
TFunction<int32(int32)> UE::Geometry::FSmallListSet::MappedValueIterator::MapFunc protected
Definition at line 611 of file SmallListSet.h.
Referenced by MappedValueIterator(), MappedValueIterator(), and operator*().
The documentation for this class was generated from the following file:
Runtime/GeometryCore/Public/Util/SmallListSet.h