Unreal Engine 5.6 C++ API: FTetrahedralCollection Class Reference
FTetrahedralCollection Class Reference
FTetrahedralCollection (FGeometryCollection)
#include "TetrahedralCollection.h"
Public Member Functions
CHAOSFLESH_API FTetrahedralCollection ()
FTetrahedralCollection (FTetrahedralCollection &&)=default
FTetrahedralCollection (FTetrahedralCollection &)=delete
CHAOSFLESH_API void AppendCollection (const FTetrahedralCollection &InCollection)
CHAOSFLESH_API int32 AppendGeometry (const FTetrahedralCollection &GeometryCollection, int32 MaterialIDOffset=0, bool ReindexAllMaterials=true, const FTransform &TransformRoot=FTransform::Identity)
CHAOSFLESH_API void InitIncidentElements (const int32 GeometryIndex=-1)
Build IncidentElements and IncidentElementsLocalIndex.
FTetrahedralCollection & operator= (const FTetrahedralCollection &)=delete
FTetrahedralCollection & operator= (FTetrahedralCollection &&)=default
CHAOSFLESH_API void RemoveVertices (const TArray< int32 > &SortedVertexIndices)
Remove selected vertices.
CHAOSFLESH_API void ReorderElements (FName Group, const TArray< int32 > &NewOrder) override
Reorders elements in a group.
CHAOSFLESH_API void ReorderTetrahedralElements (const TArray< int32 > &NewOrder)
virtual CHAOSFLESH_API void SetDefaults (FName Group, uint32 StartSize, uint32 NumElements) override
CHAOSFLESH_API void UpdateBoundingBox ()
Static Public Member Functions
static CHAOSFLESH_API void Init (FTetrahedralCollection *Collection, const TArray< FVector > &Vertices, const TArray< FIntVector3 > &SurfaceElements, const TArray< FIntVector4 > &Elements, bool bReverseVertexOrder=true)
static CHAOSFLESH_API FTetrahedralCollection * NewTetrahedralCollection (const TArray< FVector > &Vertices, const TArray< FIntVector3 > &SurfaceElements, const TArray< FIntVector4 > &Elements, bool bReverseVertexOrder=true)
Create a GeometryCollection from Vertex and Indices arrays.
Data Fields
TManagedArray< FString > Guid
TManagedArray< TArray< int32 > > IncidentElements
TManagedArray< TArray< int32 > > IncidentElementsLocalIndex
TManagedArray< FIntVector4 > Tetrahedron
TManagedArray< int32 > TetrahedronCount
TManagedArray< int32 > TetrahedronStart
Static Public Attributes
static CHAOSFLESH_API const FName BindingsGroup
static CHAOSFLESH_API const FName GuidAttribute
static CHAOSFLESH_API const FName IncidentElementsAttribute
Incident Elements Attribute For each vertex, a list of tetrahedra that includes that vertex.
static CHAOSFLESH_API const FName IncidentElementsLocalIndexAttribute
Incident Elements Attribute For each incident element, the vertex's index in the tetrahedron.
static CHAOSFLESH_API const FName TetrahedralGroup
static CHAOSFLESH_API const FName TetrahedronAttribute
static CHAOSFLESH_API const FName TetrahedronCountAttribute
static CHAOSFLESH_API const FName TetrahedronStartAttribute
Protected Member Functions
virtual CHAOSFLESH_API void Append (const FManagedArrayCollection &InCollection) override
CHAOSFLESH_API void Construct ()
Private Types
typedef FGeometryCollection Super
Detailed Description
FTetrahedralCollection (FGeometryCollection)
Definition at line 19 of file TetrahedralCollection.h.
Member Typedef Documentation
Super
typedef FGeometryCollection FTetrahedralCollection::Super private
Definition at line 21 of file TetrahedralCollection.h.
Constructor & Destructor Documentation
FTetrahedralCollection() [1/3]
CHAOSFLESH_API FTetrahedralCollection::FTetrahedralCollection ()
Referenced by FTetrahedralCollection(), FTetrahedralCollection(), AppendCollection(), AppendGeometry(), Init(), FFleshCollection::NewFleshCollection(), NewTetrahedralCollection(), operator=(), and operator=().
FTetrahedralCollection() [2/3]
FTetrahedralCollection::FTetrahedralCollection (FTetrahedralCollection &) delete
References FTetrahedralCollection().
FTetrahedralCollection() [3/3]
FTetrahedralCollection::FTetrahedralCollection (FTetrahedralCollection &&) default
References FTetrahedralCollection().
Member Function Documentation
Append()
virtual CHAOSFLESH_API void FTetrahedralCollection::Append (const FManagedArrayCollection & InCollection) override protected virtual
AppendCollection()
CHAOSFLESH_API void FTetrahedralCollection::AppendCollection (const FTetrahedralCollection & InCollection)
References FTetrahedralCollection().
AppendGeometry()
CHAOSFLESH_API int32 FTetrahedralCollection::AppendGeometry (const FTetrahedralCollection & GeometryCollection, int32 MaterialIDOffset = 0, bool ReindexAllMaterials = true, const FTransform & TransformRoot = FTransform::Identity)
References FTetrahedralCollection(), and UE::Math::TTransform< double >::Identity.
Construct()
CHAOSFLESH_API void FTetrahedralCollection::Construct () protected
Init()
CHAOSFLESH_API void FTetrahedralCollection::Init (FTetrahedralCollection * Collection, const TArray< FVector > & Vertices, const TArray< FIntVector3 > & SurfaceElements, const TArray< FIntVector4 > & Elements, bool bReverseVertexOrder = true) static
References FTetrahedralCollection().
InitIncidentElements()
CHAOSFLESH_API void FTetrahedralCollection::InitIncidentElements (const int32 GeometryIndex = -1)
Build IncidentElements and IncidentElementsLocalIndex.
GeometryIndex - ID of the geometry entry to restrict operation to; -1 does all.
NewTetrahedralCollection()
CHAOSFLESH_API FTetrahedralCollection * FTetrahedralCollection::NewTetrahedralCollection (const TArray< FVector > & Vertices, const TArray< FIntVector3 > & SurfaceElements, const TArray< FIntVector4 > & Elements, bool bReverseVertexOrder = true) static
Create a GeometryCollection from Vertex and Indices arrays.
References FTetrahedralCollection().
operator=() [1/2]
FTetrahedralCollection & FTetrahedralCollection::operator= (const FTetrahedralCollection &) delete
References FTetrahedralCollection().
operator=() [2/2]
FTetrahedralCollection & FTetrahedralCollection::operator= (FTetrahedralCollection &&) default
References FTetrahedralCollection().
RemoveVertices()
CHAOSFLESH_API void FTetrahedralCollection::RemoveVertices (const TArray< int32 > & SortedVertexIndices)
Remove selected vertices.
ReorderElements()
CHAOSFLESH_API void FTetrahedralCollection::ReorderElements (FName Group, const TArray< int32 > & NewOrder) override
Reorders elements in a group.
NewOrder must be the same length as the group.
References Group.
ReorderTetrahedralElements()
CHAOSFLESH_API void FTetrahedralCollection::ReorderTetrahedralElements (const TArray< int32 > & NewOrder)
SetDefaults()
virtual CHAOSFLESH_API void FTetrahedralCollection::SetDefaults (FName Group, uint32 StartSize, uint32 NumElements) override virtual
References Group.
UpdateBoundingBox()
CHAOSFLESH_API void FTetrahedralCollection::UpdateBoundingBox ()
Field Documentation
BindingsGroup
CHAOSFLESH_API const FName FTetrahedralCollection::BindingsGroup static
Definition at line 69 of file TetrahedralCollection.h.
Guid
TManagedArray<FString> FTetrahedralCollection::Guid
Definition at line 101 of file TetrahedralCollection.h.
GuidAttribute
CHAOSFLESH_API const FName FTetrahedralCollection::GuidAttribute static
Definition at line 100 of file TetrahedralCollection.h.
IncidentElements
TManagedArray<TArray<int32> > FTetrahedralCollection::IncidentElements
Definition at line 88 of file TetrahedralCollection.h.
IncidentElementsAttribute
CHAOSFLESH_API const FName FTetrahedralCollection::IncidentElementsAttribute static
Incident Elements Attribute For each vertex, a list of tetrahedra that includes that vertex.
Definition at line 87 of file TetrahedralCollection.h.
IncidentElementsLocalIndex
TManagedArray<TArray<int32> > FTetrahedralCollection::IncidentElementsLocalIndex
Definition at line 95 of file TetrahedralCollection.h.
IncidentElementsLocalIndexAttribute
CHAOSFLESH_API const FName FTetrahedralCollection::IncidentElementsLocalIndexAttribute static
Incident Elements Attribute For each incident element, the vertex's index in the tetrahedron.
Definition at line 94 of file TetrahedralCollection.h.
TetrahedralGroup
CHAOSFLESH_API const FName FTetrahedralCollection::TetrahedralGroup static
Definition at line 68 of file TetrahedralCollection.h.
Tetrahedron
TManagedArray<FIntVector4> FTetrahedralCollection::Tetrahedron
Definition at line 76 of file TetrahedralCollection.h.
TetrahedronAttribute
CHAOSFLESH_API const FName FTetrahedralCollection::TetrahedronAttribute static
Definition at line 75 of file TetrahedralCollection.h.
TetrahedronCount
TManagedArray<int32> FTetrahedralCollection::TetrahedronCount
Definition at line 81 of file TetrahedralCollection.h.
TetrahedronCountAttribute
CHAOSFLESH_API const FName FTetrahedralCollection::TetrahedronCountAttribute static
Definition at line 80 of file TetrahedralCollection.h.
TetrahedronStart
TManagedArray<int32> FTetrahedralCollection::TetrahedronStart
Definition at line 79 of file TetrahedralCollection.h.
TetrahedronStartAttribute
CHAOSFLESH_API const FName FTetrahedralCollection::TetrahedronStartAttribute static
Definition at line 78 of file TetrahedralCollection.h.
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Experimental/ChaosFlesh/Source/ChaosFlesh/Public/ChaosFlesh/TetrahedralCollection.h