Unreal Engine 5.6 C++ API: UCancellableAsyncAction Class Reference
UCancellableAsyncAction Class Reference
#include "CancellableAsyncAction.h"
Private Member Functions
class FTimerManager * GetTimerManager () const
Wrapper function to get a timer manager for scheduling callbacks.
bool IsRegistered () const
Returns true if this action is registered with a valid game instance.
virtual bool ShouldBroadcastDelegates () const
This should be called prior to broadcasting delegates back into the event graph, this ensures the action is still valid.
UFUNCTION () 1 virtual bool IsActive() const
Returns true if this action is still active and has not completed or been cancelled.
GENERATED_BODY() public UFUNCTION () 1 virtual void Cancel()
Handle when this action is being destroyed to ensure that the action is canceled and child classes can clean up.
Detailed Description
Definition at line 15 of file CancellableAsyncAction.h.
Member Function Documentation
GetTimerManager()
class FTimerManager * UCancellableAsyncAction::GetTimerManager () const private
Wrapper function to get a timer manager for scheduling callbacks.
References GetTimerManager().
Referenced by GetTimerManager().
IsRegistered()
bool UCancellableAsyncAction::IsRegistered () const private
Returns true if this action is registered with a valid game instance.
References IsRegistered().
Referenced by IsRegistered().
ShouldBroadcastDelegates()
virtual bool UCancellableAsyncAction::ShouldBroadcastDelegates () const private virtual
This should be called prior to broadcasting delegates back into the event graph, this ensures the action is still valid.
Reimplemented in UAbilityAsync.
References ShouldBroadcastDelegates().
Referenced by ShouldBroadcastDelegates().
UFUNCTION() [1/2]
UCancellableAsyncAction::UFUNCTION () const private
Returns true if this action is still active and has not completed or been cancelled.
References Category, and UFUNCTION().
UFUNCTION() [2/2]
GENERATED_BODY() public UCancellableAsyncAction::UFUNCTION () private
Handle when this action is being destroyed to ensure that the action is canceled and child classes can clean up.
Cancel an asynchronous action, this attempts to cancel any lower level processes and also prevents delegates from being fired
References Cancel, and Category.
Referenced by UFUNCTION().
The documentation for this class was generated from the following file:
Runtime/Engine/Classes/Engine/CancellableAsyncAction.h