Unreal Engine 5.6 C++ API: FPrecomputedVisibilityHandler Class Reference
FPrecomputedVisibilityHandler Class Reference
Handles operations on precomputed visibility data for a level.
#include "Level.h"
Public Member Functions
FPrecomputedVisibilityHandler ()
~FPrecomputedVisibilityHandler ()
void ApplyWorldOffset (const FVector &InOffset)
Shifts origin of precomputed visibility volume by specified offset.
int32 GetId () const
void Invalidate (FSceneInterface *Scene)
Invalidates the level's precomputed visibility and frees any memory used by the handler.
void UpdateScene (FSceneInterface *Scene) const
Sets this visibility handler to be actively used by the rendering scene.
void UpdateVisibilityStats (bool bAllocating) const
Updates visibility stats.
Private Attributes
int32 Id
Id used by the renderer to know when cached visibility data is valid.
FVector2D PrecomputedVisibilityCellBucketOriginXY
World space origin of the cell grid.
TArray< FPrecomputedVisibilityBucket > PrecomputedVisibilityCellBuckets
Visibility bucket data.
int32 PrecomputedVisibilityCellBucketSizeXY
Number of cells in each bucket in x and y.
float PrecomputedVisibilityCellSizeXY
World space size of every cell in x and y.
float PrecomputedVisibilityCellSizeZ
World space height of every cell.
int32 PrecomputedVisibilityNumCellBuckets
Number of buckets in x and y.
Static Private Attributes
static int32 NextId
Friends
class FLightmassProcessor
class FSceneViewState
FArchive & operator<< (FArchive &Ar, FPrecomputedVisibilityHandler &D)
Detailed Description
Handles operations on precomputed visibility data for a level.
Definition at line 239 of file Level.h.
Constructor & Destructor Documentation
FPrecomputedVisibilityHandler()
FPrecomputedVisibilityHandler::FPrecomputedVisibilityHandler () inline
Definition at line 243 of file Level.h.
References Id, and NextId.
Referenced by operator<<.
~FPrecomputedVisibilityHandler()
FPrecomputedVisibilityHandler::~FPrecomputedVisibilityHandler () inline
Definition at line 249 of file Level.h.
References UpdateVisibilityStats().
Member Function Documentation
ApplyWorldOffset()
void FPrecomputedVisibilityHandler::ApplyWorldOffset (const FVector & InOffset)
Shifts origin of precomputed visibility volume by specified offset.
References FVector.
GetId()
int32 FPrecomputedVisibilityHandler::GetId () const inline
Returns
the Id
Definition at line 267 of file Level.h.
References Id.
Invalidate()
void FPrecomputedVisibilityHandler::Invalidate (FSceneInterface * Scene)
Invalidates the level's precomputed visibility and frees any memory used by the handler.
References Scene.
UpdateScene()
void FPrecomputedVisibilityHandler::UpdateScene (FSceneInterface * Scene) const
Sets this visibility handler to be actively used by the rendering scene.
References Scene.
UpdateVisibilityStats()
void FPrecomputedVisibilityHandler::UpdateVisibilityStats (bool bAllocating) const
Updates visibility stats.
Referenced by ~FPrecomputedVisibilityHandler().
Friends And Related Symbol Documentation
FLightmassProcessor
friend class FLightmassProcessor friend
Definition at line 296 of file Level.h.
References FLightmassProcessor.
Referenced by FLightmassProcessor.
FSceneViewState
friend class FSceneViewState friend
Definition at line 297 of file Level.h.
References FSceneViewState.
Referenced by FSceneViewState.
operator<<
FArchive & operator<< (FArchive & Ar, FPrecomputedVisibilityHandler & D) friend
References FPrecomputedVisibilityHandler(), and Ar.
Field Documentation
Id
int32 FPrecomputedVisibilityHandler::Id private
Id used by the renderer to know when cached visibility data is valid.
Definition at line 291 of file Level.h.
Referenced by FPrecomputedVisibilityHandler(), and GetId().
NextId
int32 FPrecomputedVisibilityHandler::NextId static private
Definition at line 288 of file Level.h.
Referenced by FPrecomputedVisibilityHandler().
PrecomputedVisibilityCellBucketOriginXY
FVector2D FPrecomputedVisibilityHandler::PrecomputedVisibilityCellBucketOriginXY private
World space origin of the cell grid.
Definition at line 274 of file Level.h.
PrecomputedVisibilityCellBuckets
TArray<FPrecomputedVisibilityBucket> FPrecomputedVisibilityHandler::PrecomputedVisibilityCellBuckets private
Visibility bucket data.
Definition at line 294 of file Level.h.
PrecomputedVisibilityCellBucketSizeXY
int32 FPrecomputedVisibilityHandler::PrecomputedVisibilityCellBucketSizeXY private
Number of cells in each bucket in x and y.
Definition at line 283 of file Level.h.
PrecomputedVisibilityCellSizeXY
float FPrecomputedVisibilityHandler::PrecomputedVisibilityCellSizeXY private
World space size of every cell in x and y.
Definition at line 277 of file Level.h.
PrecomputedVisibilityCellSizeZ
float FPrecomputedVisibilityHandler::PrecomputedVisibilityCellSizeZ private
World space height of every cell.
Definition at line 280 of file Level.h.
PrecomputedVisibilityNumCellBuckets
int32 FPrecomputedVisibilityHandler::PrecomputedVisibilityNumCellBuckets private
Number of buckets in x and y.
Definition at line 286 of file Level.h.
The documentation for this class was generated from the following file:
Runtime/Engine/Classes/Engine/Level.h