Unreal Engine 5.6 C++ API: FDurationTimer Class Reference
FDurationTimer Class Reference
Utility stopwatch class for tracking the duration of some action (tracks time in seconds and adds it to the specified variable on destruction).
#include "ScopedTimers.h"
Public Member Functions
FDurationTimer (double &AccumulatorIn)
double Start ()
double Stop ()
Protected Attributes
double & Accumulator
Time variable to update.
double StartTime
Start time, captured in ctor.
Detailed Description
Utility stopwatch class for tracking the duration of some action (tracks time in seconds and adds it to the specified variable on destruction).
Definition at line 31 of file ScopedTimers.h.
Constructor & Destructor Documentation
FDurationTimer()
FDurationTimer::FDurationTimer (double & AccumulatorIn) inline explicit
Definition at line 34 of file ScopedTimers.h.
References Accumulator, Seconds, and StartTime.
Referenced by FScopedABTimer::FScopedABTimer(), and FScopedDurationTimer::FScopedDurationTimer().
Member Function Documentation
Start()
double FDurationTimer::Start () inline
Definition at line 39 of file ScopedTimers.h.
References FAndroidTime::Seconds(), and StartTime.
Referenced by FScopedABTimer::FScopedABTimer().
Stop()
double FDurationTimer::Stop () inline
Definition at line 45 of file ScopedTimers.h.
References Accumulator, FAndroidTime::Seconds(), and StartTime.
Referenced by FScopedABTimer::~FScopedABTimer(), FScopedDurationTimer::~FScopedDurationTimer(), and FAutoScopedDurationTimer::GetTime().
Field Documentation
Accumulator
double& FDurationTimer::Accumulator protected
Time variable to update.
Definition at line 58 of file ScopedTimers.h.
Referenced by FDurationTimer(), FScopedABTimer::~FScopedABTimer(), and Stop().
StartTime
double FDurationTimer::StartTime protected
Start time, captured in ctor.
Definition at line 56 of file ScopedTimers.h.
Referenced by FDurationTimer(), Start(), and Stop().
The documentation for this class was generated from the following file:
Runtime/Core/Public/ProfilingDebugging/ScopedTimers.h