Unreal Engine 5.6 C++ API: AEQSTestingPawn Class Reference
AEQSTestingPawn Class Reference
#include "EQSTestingPawn.h"
Public Member Functions
virtual AIMODULE_API float GetHighlightRangePct () const override
virtual AIMODULE_API const FNavAgentProperties & GetNavAgentPropertiesRef () const override
virtual AIMODULE_API const FEnvQueryInstance * GetQueryInstance () const override
virtual AIMODULE_API const FEnvQueryResult * GetQueryResult () const override
virtual bool GetShouldDebugDrawLabels () const override
virtual bool GetShouldDrawFailedItems () const override
AIMODULE_API void OnPropertyChanged (const FName PropName)
virtual AIMODULE_API void PostEditChangeProperty (struct FPropertyChangedEvent &PropertyChangedEvent) override
virtual AIMODULE_API void PostEditMove (bool bFinished) override
virtual AIMODULE_API void PostLoad () override
virtual AIMODULE_API void PostTransacted (const FTransactionObjectEvent &TransactionEvent) override
AIMODULE_API void RunEQSQuery ()
virtual AIMODULE_API void TickActor (float DeltaTime, enum ELevelTick TickType, FActorTickFunction &ThisTickFunction) override
This pawn class spawns its controller in PostInitProperties to have it available in editor mode.
Public Member Functions inherited from ACharacter
void ApplyAsyncOutput (const FCharacterAsyncOutput &Output)
virtual void ApplyDamageMomentum (float DamageTaken, FDamageEvent const &DamageEvent, APawn *PawnInstigator, AActor *DamageCauser)
Apply momentum caused by damage.
virtual void BeginPlay () override
bool CanUseRootMotionRepMove (const FSimulatedRootMotionReplicatedMove &RootMotionRepMove, const FAnimMontageInstance &ClientMontageInstance) const
True if buffered move is usable to teleport client back to.
virtual void CheckJumpInput (float DeltaTime)
Trigger jump if jump button has been pressed.
virtual void ClearCrossLevelReferences () override
virtual void ClearJumpInput (float DeltaTime)
Update jump input state after having checked input.
virtual void ClientCheatFly_Implementation ()
virtual void ClientCheatGhost_Implementation ()
virtual void ClientCheatWalk_Implementation ()
void ClientMoveResponsePacked_Implementation (const FCharacterMoveResponsePackedBits &PackedBits)
bool ClientMoveResponsePacked_Validate (const FCharacterMoveResponsePackedBits &PackedBits)
DEPRECATED_CHARACTER_MOVEMENT_RPC (ClientAckGoodMove, ClientMoveResponsePacked) UFUNCTION() 1 void ClientAckGoodMove(float TimeStamp)
If no client adjustment is needed after processing received ServerMove(), ack the good move so client can remove it from SavedMoves.
DEPRECATED_CHARACTER_MOVEMENT_RPC (ClientAckGoodMove_Implementation, ClientMoveResponsePacked_Implementation) 1 void ClientAckGoodMove_Implementation(float TimeStamp)
DEPRECATED_CHARACTER_MOVEMENT_RPC (ClientAdjustPosition, ClientMoveResponsePacked) UFUNCTION() 1 void ClientAdjustPosition(float TimeStamp
Replicate position correction to client, associated with a timestamped servermove.
DEPRECATED_CHARACTER_MOVEMENT_RPC (ClientAdjustPosition_Implementation, ClientMoveResponsePacked_Implementation) 1 void ClientAdjustPosition_Implementation(float TimeStamp
DEPRECATED_CHARACTER_MOVEMENT_RPC (ClientAdjustRootMotionPosition, ClientMoveResponsePacked) UFUNCTION() 1 void ClientAdjustRootMotionPosition(float TimeStamp
Replicate position correction to client when using root motion for movement.
DEPRECATED_CHARACTER_MOVEMENT_RPC (ClientAdjustRootMotionPosition_Implementation, ClientMoveResponsePacked_Implementation) 1 void ClientAdjustRootMotionPosition_Implementation(float TimeStamp
DEPRECATED_CHARACTER_MOVEMENT_RPC (ClientAdjustRootMotionSourcePosition, ClientMoveResponsePacked) UFUNCTION() 1 void ClientAdjustRootMotionSourcePosition(float TimeStamp
Replicate root motion source correction to client when using root motion for movement.
DEPRECATED_CHARACTER_MOVEMENT_RPC (ClientAdjustRootMotionSourcePosition_Implementation, ClientMoveResponsePacked_Implementation) 1 void ClientAdjustRootMotionSourcePosition_Implementation(float TimeStamp
DEPRECATED_CHARACTER_MOVEMENT_RPC (ClientVeryShortAdjustPosition, ClientMoveResponsePacked) UFUNCTION() 1 void ClientVeryShortAdjustPosition(float TimeStamp
DEPRECATED_CHARACTER_MOVEMENT_RPC (ClientVeryShortAdjustPosition_Implementation, ClientMoveResponsePacked_Implementation) 1 void ClientVeryShortAdjustPosition_Implementation(float TimeStamp
DEPRECATED_CHARACTER_MOVEMENT_RPC (ServerMove, ServerMovePacked) UFUNCTION() 1 void ServerMove(float TimeStamp
Replicated function sent by client to server - contains client movement and view info.
DEPRECATED_CHARACTER_MOVEMENT_RPC (ServerMove_Implementation, ServerMovePacked_Implementation) 1 void ServerMove_Implementation(float TimeStamp
DEPRECATED_CHARACTER_MOVEMENT_RPC (ServerMoveDual, ServerMovePacked) UFUNCTION() 1 void ServerMoveDual(float TimeStamp0
Replicated function sent by client to server - contains client movement and view info for two moves.
DEPRECATED_CHARACTER_MOVEMENT_RPC (ServerMoveDual_Implementation, ServerMovePacked_Implementation) 1 void ServerMoveDual_Implementation(float TimeStamp0
DEPRECATED_CHARACTER_MOVEMENT_RPC (ServerMoveDualHybridRootMotion, ServerMovePacked) UFUNCTION() 1 void ServerMoveDualHybridRootMotion(float TimeStamp0
Replicated function sent by client to server - contains client movement and view info for two moves.
DEPRECATED_CHARACTER_MOVEMENT_RPC (ServerMoveDualHybridRootMotion_Implementation, ServerMovePacked_Implementation) 1 void ServerMoveDualHybridRootMotion_Implementation(float TimeStamp0
DEPRECATED_CHARACTER_MOVEMENT_RPC (ServerMoveDualNoBase, ServerMovePacked) UFUNCTION() 1 void ServerMoveDualNoBase(float TimeStamp0
Replicated function sent by client to server - contains client movement and view info for two moves.
DEPRECATED_CHARACTER_MOVEMENT_RPC (ServerMoveDualNoBase_Implementation, ServerMovePacked_Implementation) 1 void ServerMoveDualNoBase_Implementation(float TimeStamp0
DEPRECATED_CHARACTER_MOVEMENT_RPC (ServerMoveNoBase, ServerMovePacked) UFUNCTION() 1 void ServerMoveNoBase(float TimeStamp
Replicated function sent by client to server.
DEPRECATED_CHARACTER_MOVEMENT_RPC (ServerMoveNoBase_Implementation, ServerMovePacked_Implementation) 1 void ServerMoveNoBase_Implementation(float TimeStamp
DEPRECATED_CHARACTER_MOVEMENT_RPC (ServerMoveOld, ServerMovePacked) UFUNCTION() 1 void ServerMoveOld(float OldTimeStamp
DEPRECATED_CHARACTER_MOVEMENT_RPC (ServerMoveOld_Implementation, ServerMovePacked_Implementation) 1 void ServerMoveOld_Implementation(float OldTimeStamp
virtual void DisplayDebug (class UCanvas *Canvas, const FDebugDisplayInfo &DebugDisplay, float &YL, float &YPos) override
virtual void Falling ()
Called when the character's movement enters falling.
void FillAsyncInput (FCharacterAsyncInput &Input) const
Async simulation API.
template<class T>
T * FindComponentByClass () const
virtual UActorComponent * FindComponentByClass (const TSubclassOf< UActorComponent > ComponentClass) const override
int32 FindRootMotionRepMove (const FAnimMontageInstance &ClientMontageInstance) const
Find usable root motion replicated move from our buffer.
virtual void GatherCurrentMovement () override
FORCEINLINE const FBasedMovementInfo & GetBasedMovement () const
Accessor for BasedMovement.
virtual FQuat GetBaseRotationOffset () const
Get the saved rotation offset of mesh.
FORCEINLINE class UCapsuleComponent * GetCapsuleComponent () const
Returns CapsuleComponent subobject.
template<class T>
FORCEINLINE_DEBUGGABLE T * GetCharacterMovement () const
Returns CharacterMovement subobject.
FORCEINLINE UCharacterMovementComponent * GetCharacterMovement () const
virtual float GetDefaultHalfHeight () const override
Returns The half-height of the default Pawn, scaled by the component scale.
virtual FVector GetGravityDirection () const override
Returns vector direction of gravity.
virtual FQuat GetGravityTransform () const override
Returns a quaternion transforming from world space into gravity relative space.
virtual float GetJumpMaxHoldTime () const
Get the maximum jump time for the character.
FORCEINLINE class USkeletalMeshComponent * GetMesh () const
Returns Mesh subobject.
virtual UPrimitiveComponent * GetMovementBase () const override final
Return PrimitiveComponent we are based on (standing on, attached to, and moving on).
virtual UPawnMovementComponent * GetMovementComponent () const override
virtual FVector GetNavAgentLocation () const override
FORCEINLINE bool GetProxyIsJumpForceApplied () const
Indicates that this Character is currently under the force of a jump (if JumpMaxHoldTime is non-zero).
FORCEINLINE float GetReplayLastTransformUpdateTimeStamp () const
This is updated every frame to the latest timestamp, but only replicated to Replays, this is because we want to save positions to the replay replication connection each frame to ensure smooth movement.
FORCEINLINE const FBasedMovementInfo & GetReplicatedBasedMovement () const
Accessor for ReplicatedBasedMovement.
virtual FVector GetReplicatedGravityDirection () const
Returns replicated gravity direction for simulated proxies.
FORCEINLINE uint8 GetReplicatedMovementMode () const
CharacterMovement MovementMode (and custom mode) replicated for simulated proxies.
FORCEINLINE float GetReplicatedServerLastTransformUpdateTimeStamp () const
This is the value of the CharacterMovement timestamp, and is replicated down to SimulatedProxies to assist with visual smoothing of the character.
FORCEINLINE const FRepRootMotionMontage & GetRepRootMotion () const
Replicated Root Motion montage.
FRepRootMotionMontage & GetRepRootMotion_Mutable ()
Replicated Root Motion montage.
FAnimMontageInstance * GetRootMotionAnimMontageInstance () const
Get FAnimMontageInstance playing RootMotion.
virtual void GetSimpleCollisionCylinder (float &CollisionRadius, float &CollisionHalfHeight) const override
void InitializeAsyncOutput (FCharacterAsyncOutput &Output) const
bool IsCrouched () const
Set by character movement to specify that this Character is currently crouched.
virtual void Landed (const FHitResult &Hit)
Called upon landing when falling, to perform actions based on the Hit result.
virtual void MoveBlockedBy (const FHitResult &Impact)
Called when pawn's movement is blocked.
virtual void NotifyActorBeginOverlap (AActor *OtherActor)
virtual void NotifyActorEndOverlap (AActor *OtherActor)
virtual void NotifyJumpApex ()
Called when character's jump reaches Apex.
virtual void OnEndCrouch (float HalfHeightAdjust, float ScaledHalfHeightAdjust)
Called when Character stops crouching.
virtual void OnJumped_Implementation ()
virtual void OnMovementModeChanged (EMovementMode PrevMovementMode, uint8 PreviousCustomMode=0)
Called from CharacterMovementComponent to notify the character that the movement mode has changed.
virtual void OnRep_ReplicatedMovement () override
virtual void OnStartCrouch (float HalfHeightAdjust, float ScaledHalfHeightAdjust)
Called when Character crouches.
virtual void OnUpdateSimulatedPosition (const FVector &OldLocation, const FQuat &OldRotation)
Called on client after position update is received to respond to the new location and rotation.
virtual void OnWalkingOffLedge_Implementation (const FVector &PreviousFloorImpactNormal, const FVector &PreviousFloorContactNormal, const FVector &PreviousLocation, float TimeDelta)
virtual void PawnClientRestart () override
Called on the owning client of a player-controlled Pawn when it is restarted, this calls Restart()
virtual void PossessedBy (AController *NewController) override
Called when this Pawn is possessed.
virtual void PostInitializeComponents () override
virtual void PostNetReceive () override
virtual void PostNetReceiveLocationAndRotation () override
virtual void PreNetReceive () override
virtual void PreReplication (IRepChangedPropertyTracker &ChangedPropertyTracker) override
Called on the actor right before replication occurs.
virtual void PreReplicationForReplay (IRepChangedPropertyTracker &ChangedPropertyTracker) override
Called on the actor right before replication occurs.
virtual void RecalculateBaseEyeHeight () override
Set BaseEyeHeight based on current state.
void RecalculateCrouchedEyeHeight ()
Calculates the crouched eye height based on movement component settings.
virtual void ResetJumpState ()
Marks character as not trying to jump.
virtual void Restart () override
Called when the Pawn is being restarted (usually by being possessed by a Controller).
bool RestoreReplicatedMove (const FSimulatedRootMotionReplicatedMove &RootMotionRepMove)
Restore actor to an old buffered move.
virtual void RootMotionDebugClientPrintOnScreen_Implementation (const FString &InString)
void SaveRelativeBasedMovement (const FVector &NewRelativeLocation, const FRotator &NewRotation, bool bRelativeRotation)
Save a new relative location in BasedMovement and a new rotation with is either relative or absolute.
bool ServerMove_Validate (float TimeStamp, FVector_NetQuantize10 InAccel, FVector_NetQuantize100 ClientLoc, uint8 CompressedMoveFlags, uint8 ClientRoll, uint32 View, UPrimitiveComponent *ClientMovementBase, FName ClientBaseBoneName, uint8 ClientMovementMode)
bool ServerMoveDual_Validate (float TimeStamp0, FVector_NetQuantize10 InAccel0, uint8 PendingFlags, uint32 View0, float TimeStamp, FVector_NetQuantize10 InAccel, FVector_NetQuantize100 ClientLoc, uint8 NewFlags, uint8 ClientRoll, uint32 View, UPrimitiveComponent *ClientMovementBase, FName ClientBaseBoneName, uint8 ClientMovementMode)
bool ServerMoveDualHybridRootMotion_Validate (float TimeStamp0, FVector_NetQuantize10 InAccel0, uint8 PendingFlags, uint32 View0, float TimeStamp, FVector_NetQuantize10 InAccel, FVector_NetQuantize100 ClientLoc, uint8 NewFlags, uint8 ClientRoll, uint32 View, UPrimitiveComponent *ClientMovementBase, FName ClientBaseBoneName, uint8 ClientMovementMode)
bool ServerMoveDualNoBase_Validate (float TimeStamp0, FVector_NetQuantize10 InAccel0, uint8 PendingFlags, uint32 View0, float TimeStamp, FVector_NetQuantize10 InAccel, FVector_NetQuantize100 ClientLoc, uint8 NewFlags, uint8 ClientRoll, uint32 View, uint8 ClientMovementMode)
bool ServerMoveNoBase_Validate (float TimeStamp, FVector_NetQuantize10 InAccel, FVector_NetQuantize100 ClientLoc, uint8 CompressedMoveFlags, uint8 ClientRoll, uint32 View, uint8 ClientMovementMode)
bool ServerMoveOld_Validate (float OldTimeStamp, FVector_NetQuantize10 OldAccel, uint8 OldMoveFlags)
void ServerMovePacked_Implementation (const FCharacterServerMovePackedBits &PackedBits)
bool ServerMovePacked_Validate (const FCharacterServerMovePackedBits &PackedBits)
void SetAnimRootMotionTranslationScale (float InAnimRootMotionTranslationScale=1.f)
Sets scale to apply to root motion translation on this Character.
virtual void SetBase (UPrimitiveComponent *NewBase, const FName BoneName=NAME_None, bool bNotifyActor=true)
Sets the component the Character is walking on, used by CharacterMovement walking movement to be able to follow dynamic objects.
void SetIsCrouched (const bool bInIsCrouched)
Specifies whether this Character is currently crouched or not.
void SetProxyIsJumpForceApplied (const bool bInProxyIsJumpForceApplied)
Set to indicate that this Character is currently under the force of a jump (if JumpMaxHoldTime is non-zero).
virtual void SetReplicateMovement (bool bInReplicateMovement) override
Set whether this actor's movement replicates to network clients.
void SetRepRootMotion (const FRepRootMotionMontage &InRepRootMotion)
Replicated Root Motion montage.
virtual void SetupPlayerInputComponent (class UInputComponent *PlayerInputComponent) override
Allows a Pawn to set up custom input bindings.
virtual bool ShouldNotifyLanded (const struct FHitResult &Hit)
Returns true if the Landed() event should be called.
void SimulatedRootMotionPositionFixup (float DeltaSeconds)
Position fix up for Simulated Proxies playing Root Motion.
virtual void TornOff () override
virtual void TurnOff () override
Freeze pawn - stop sounds, animations, physics, weapon firing.
UFUNCTION () 1 bool CanJump() const
Check if the character can jump in the current state.
UFUNCTION () 1 bool HasAnyRootMotion() const
True if we are playing root motion from any source right now (anim root motion, root motion source)
UFUNCTION () 1 bool IsPlayingNetworkedRootMotionMontage() const
True if we are playing Root Motion right now, through a Montage with RootMotionMode == ERootMotionMode::RootMotionFromMontagesOnly.
UFUNCTION () 1 class UAnimMontage *GetCurrentMontage() const
Return current playing Montage.
UFUNCTION () 1 float GetAnimRootMotionTranslationScale() const
Scale to apply to root motion translation on this Character.
UFUNCTION () 1 virtual bool CanCrouch() const
UFUNCTION () 1 virtual bool IsJumpProvidingForce() const
True if jump is actively providing a force, such as when the jump key is held and the time it has been held is less than JumpMaxHoldTime.
UFUNCTION () 1 virtual float PlayAnimMontage(class UAnimMontage *AnimMontage
Play Animation Montage on the character mesh.
UFUNCTION () 1 virtual void CacheInitialMeshOffset(FVector MeshRelativeLocation
Cache mesh offset from capsule.
UFUNCTION () 1 virtual void Jump()
Make the character jump on the next update.
UFUNCTION () 1 virtual void LaunchCharacter(FVector LaunchVelocity
Set a pending launch velocity on the Character.
UPROPERTY() uint8 bIsCrouched UPROPERTY() uint8 bProxyIsJumpForceApplied UFUNCTION () 1 virtual void OnRep_IsCrouched()
Flag that we are receiving replication of the based movement.
UFUNCTION () 1 virtual void OnRep_ReplicatedBasedMovement()
Rep notify for ReplicatedBasedMovement.
UFUNCTION () 1 virtual void StopAnimMontage(class UAnimMontage *AnimMontage
Stop Animation Montage.
UFUNCTION () 1 virtual void StopJumping()
Stop the character from jumping on the next update.
UFUNCTION () 1 void ClientCheatFly()
UFUNCTION () 1 void ClientCheatGhost()
UFUNCTION () 1 void ClientCheatWalk()
UFUNCTION () 1 void ClientMoveResponsePacked(const FCharacterMoveResponsePackedBits &PackedBits)
UFUNCTION () 1 void OnJumped()
Event fired when the character has just started jumping.
UFUNCTION () 1 void OnLanded(const FHitResult &Hit)
Called upon landing when falling, to perform actions based on the Hit result.
UFUNCTION () 1 void OnLaunched(FVector LaunchVelocity
Let blueprint know that we were launched.
UFUNCTION () 1 void OnRep_ReplayLastTransformUpdateTimeStamp()
UFUNCTION () 1 void OnRep_RootMotion()
Handles replicated root motion properties on simulated proxies and position correction.
UFUNCTION () 1 void OnWalkingOffLedge(const FVector &PreviousFloorImpactNormal
Event fired when the Character is walking off a surface and is about to fall because CharacterMovement->CurrentFloor became unwalkable.
UFUNCTION () 1 void RootMotionDebugClientPrintOnScreen(const FString &InString)
UFUNCTION () 1 void ServerMovePacked(const FCharacterServerMovePackedBits &PackedBits)
UFUNCTION () FVector GetBaseTranslationOffset() const
Get the saved translation offset of mesh.
UFUNCTION ()) 1 bool IsPlayingRootMotion() const
True if we are playing Anim root motion right now.
UFUNCTION ()) 1 virtual void Crouch(bool bClientSimulation
Request the character to start crouching.
UFUNCTION ()) 1 virtual void UnCrouch(bool bClientSimulation
Request the character to stop crouching.
UFUNCTION ()) 1 void K2_OnEndCrouch(float HalfHeightAdjust
Event when Character stops crouching.
UFUNCTION ()) 1 void K2_OnMovementModeChanged(EMovementMode PrevMovementMode
Called from CharacterMovementComponent to notify the character that the movement mode has changed.
UFUNCTION ()) 1 void K2_OnStartCrouch(float HalfHeightAdjust
Event when Character crouches.
UFUNCTION ()) 1 void K2_UpdateCustomMovement(float DeltaTime)
Event for implementing custom character movement mode.
UFUNCTION ()) FRotator GetBaseRotationOffsetRotator() const
Get the saved rotation offset of mesh.
virtual void UnPossessed () override
Called when our Controller no longer possesses us.
virtual void UpdateNavigationRelevance () override
Update all components relevant for navigation generators to match bCanAffectNavigationGeneration flag.
UPROPERTY () FCharacterMovementUpdatedSignature OnCharacterMovementUpdated
Event triggered at the end of a CharacterMovementComponent movement update.
UPROPERTY () FCharacterReachedApexSignature OnReachedJumpApex
Broadcast when Character's jump reaches its apex.
UPROPERTY () FLandedSignature LandedDelegate
Called upon landing when falling, to perform actions based on the Hit result.
UPROPERTY () float CrouchedEyeHeight
Default crouched eye height.
UPROPERTY () float JumpForceTimeRemaining
Amount of jump force time remaining, if JumpMaxHoldTime > 0.
UPROPERTY () float JumpKeyHoldTime
Jump key Held Time.
UPROPERTY () float ProxyJumpForceStartedTime
Track last time a jump force started for a proxy.
UPROPERTY () FMovementModeChangedSignature MovementModeChangedDelegate
Multicast delegate for MovementMode changing.
UPROPERTY () FRootMotionMovementParams ClientRootMotionParams
For LocallyControlled Autonomous clients.
UPROPERTY () FRootMotionSourceGroup SavedRootMotion
For LocallyControlled Autonomous clients.
UPROPERTY () int32 JumpCurrentCount
Tracks the current number of jumps performed.
UPROPERTY () int32 JumpCurrentCountPreJump
Represents the current number of jumps performed before CheckJumpInput modifies JumpCurrentCount.
UPROPERTY () int32 JumpMaxCount
The max number of jumps the character can perform.
UPROPERTY () struct FRepRootMotionMontage RepRootMotion
Replicated Root Motion montage.
UPROPERTY () TArray< FSimulatedRootMotionReplicatedMove > RootMotionRepMoves
Array of previously received root motion moves from the server.
UPROPERTY ()) float JumpMaxHoldTime
The max time the jump key can be held.
Public Member Functions inherited from APawn
virtual void BecomeViewTarget (APlayerController *PC) override
virtual bool CanBeBaseForCharacter (APawn *APawn) const override
Overridden to defer to the RootComponent's CanCharacterStepUpOn setting if it is explicitly Yes or No.
virtual void Destroyed () override
virtual void DisableInput (APlayerController *PlayerController) override
void DispatchRestart (bool bCallClientRestart)
Wrapper function to call correct restart functions, enable bCallClientRestart if this is a locally owned player pawn or equivalent.
virtual void EditorApplyRotation (const FRotator &DeltaRotation, bool bAltDown, bool bShiftDown, bool bCtrlDown) override
virtual void EnableInput (APlayerController *PlayerController) override
virtual void EndPlay (const EEndPlayReason::Type EndPlayReason) override
virtual void EndViewTarget (APlayerController *PC) override
virtual void FaceRotation (FRotator NewControlRotation, float DeltaTime=0.f)
Updates Pawn's rotation to the given rotation, assumed to be the Controller's ControlRotation.
virtual void GetActorEyesViewPoint (FVector &Location, FRotator &Rotation) const override
template<class T>
T * GetController () const
Returns controller for this actor cast to the template type.
virtual FString GetHumanReadableName () const override
virtual void GetMoveGoalReachTest (const AActor *MovingActor, const FVector &MoveOffset, FVector &GoalOffset, float &GoalRadius, float &GoalHalfHeight) const override
Get cylinder for testing if actor has been reached.
virtual class UNetConnection * GetNetConnection () const override
virtual const AActor * GetNetOwner () const override
virtual UPlayer * GetNetOwningPlayer () override
virtual UPlayer * GetNetOwningPlayerAnyRole () override
virtual UPawnNoiseEmitterComponent * GetPawnNoiseEmitterComponent () const
Return our PawnNoiseEmitterComponent, if any.
virtual FVector GetPawnViewLocation () const
Returns Pawn's eye location.
virtual APhysicsVolume * GetPhysicsVolume () const override
Return Physics Volume for this Pawn.
APlayerState * GetPlayerState () const
If Pawn is possessed by a player, returns its Player State.
template<class T>
T * GetPlayerState () const
Templated convenience version of GetPlayerState.
template<class T>
T * GetPlayerStateChecked () const
Templated convenience version of GetPlayerState which checks the type is as presumed.
FORCEINLINE uint16 GetRemoteViewPitch () const
Replicated pitch value so we can see where remote clients are looking.
virtual FVector GetVelocity () const override
virtual FRotator GetViewRotation () const
Get the view rotation of the Pawn (direction they are looking, normally Controller->ControlRotation).
virtual bool InFreeCam () const
Returns true if player is viewing this Pawn in FreeCam.
bool InputEnabled () const
Whether this Pawn's input handling is enabled.
void Internal_AddMovementInput (FVector WorldAccel, bool bForce=false)
Internal function meant for use only within Pawn or by a PawnMovementComponent.
FVector Internal_ConsumeMovementInputVector ()
Internal function meant for use only within Pawn or by a PawnMovementComponent.
FVector Internal_GetLastMovementInputVector () const
Internal function meant for use only within Pawn or by a PawnMovementComponent.
FVector Internal_GetPendingMovementInputVector () const
Internal function meant for use only within Pawn or by a PawnMovementComponent.
virtual bool IsBasedOnActor (const AActor *Other) const override
bool IsLocalPlayerControllerViewingAPawn () const
virtual bool IsNetRelevantFor (const AActor *RealViewer, const AActor *ViewTarget, const FVector &SrcLocation) const override
void MoveIgnoreActorAdd (AActor *ActorToIgnore)
Add an Actor to ignore by Pawn's movement collision.
void MoveIgnoreActorRemove (AActor *ActorToIgnore)
Remove an Actor to ignore by Pawn's movement collision.
virtual void NotifyControllerChanged ()
Call to notify about a change in controller, on both the server and owning client.
virtual void NotifyRestarted ()
Notifies other systems that a pawn has been restarted.
virtual void OutsideWorldBounds () override
virtual void PawnStartFire (uint8 FireModeNum=0)
Handle StartFire() passed from PlayerController.
virtual void PostNetReceiveVelocity (const FVector &NewVelocity) override
virtual void PostRegisterAllComponents () override
virtual void PreInitializeComponents () override
virtual bool ReachedDesiredRotation ()
Return true if yaw is within AllowedYawError of desired yaw.
void SetController (AController *InController)
Sets controller for this actor.
virtual void SetPlayerDefaults ()
Make sure pawn properties are back to default.
void SetPlayerState (APlayerState *NewPlayerState)
Set the Pawn's Player State.
void SetRemoteViewPitch (double NewRemoteViewPitch)
Set Pawn ViewPitch, so we can see where remote clients are looking.
virtual bool ShouldTakeDamage (float Damage, FDamageEvent const &DamageEvent, AController *EventInstigator, AActor *DamageCauser) const
Return true if we are in a state to take damage (checked at the start of TakeDamage.
virtual bool ShouldTickIfViewportsOnly () const override
virtual float TakeDamage (float Damage, struct FDamageEvent const &DamageEvent, AController *EventInstigator, AActor *DamageCauser) override
virtual void TeleportSucceeded (bool bIsATest) override
UE_DEPRECATED (4.24, "IsControlled is deprecated. To check if this pawn is controlled by anything, then call IsPawnControlled. To check if this pawn is controlled only by the player then call IsPlayerControlled") UFUNCTION() 1 bool IsControlled() const
See if this actor is currently being controlled.
UE_DEPRECATED (5.0, "GetPawnPhysicsVolume is deprecated. Please use GetPhysicsVolume instead.") 1 virtual APhysicsVolume *GetPawnPhysicsVolume() const
Return Physics Volume for this Pawn.
UE_DEPRECATED (5.6, "This property is deprecated, use GetRemoteViewPitch()/RemoteViewPitch16 instead.") UPROPERTY() uint8 RemoteViewPitch
DEPRECTED, use RemoteViewPitch16 instead.
UFUNCTION () 1 APlayerController *GetLocalViewingPlayerController() const
Returns local Player Controller viewing this pawn, whether it is controlling or spectating.
UFUNCTION () 1 bool IsLocallyViewed() const
UFUNCTION () 1 FPlatformUserId GetPlatformUserId() const
Returns the Platform User ID of the PlayerController that is controlling this character.
UFUNCTION () 1 FRotator GetControlRotation() const
Get the rotation of the Controller, often the 'view' rotation of this Pawn.
UFUNCTION () 1 TSubclassOf< UInputComponent > GetOverrideInputComponentClass() const
UFUNCTION () 1 virtual bool IsBotControlled() const
Returns true if controlled by a bot.
UFUNCTION () 1 virtual bool IsLocallyControlled() const
Returns true if controlled by a local (not network) Controller.
UFUNCTION () 1 virtual bool IsMoveInputIgnored() const
Helper to see if move input is ignored.
UFUNCTION () 1 virtual bool IsPawnControlled() const
Check if this actor is currently being controlled at all (the actor has a valid Controller, which will be false for remote clients)
UFUNCTION () 1 virtual bool IsPlayerControlled() const
Returns true if controlled by a human player (possessed by a PlayerController).
UFUNCTION () 1 virtual FRotator GetBaseAimRotation() const
Return the aim rotation for the Pawn.
UFUNCTION () 1 virtual void OnRep_Controller()
Called when Controller is replicated.
UFUNCTION () 1 virtual void OnRep_PlayerState()
PlayerState Replication Notification Callback.
UFUNCTION () 1 virtual void SpawnDefaultController()
Spawn default controller for this Pawn, and get possessed by it.
UFUNCTION () 1 void PawnMakeNoise(float Loudness
Inform AIControllers that you've made a noise they might hear (they are sent a HearNoise message if they have bHearNoises==true) The instigator of this sound is the pawn which is used to call MakeNoise.
UFUNCTION () 1 void ReceiveControllerChanged(AController *OldController
Event called after a pawn's controller has changed, on the server and owning client.
UFUNCTION () 1 void ReceiveRestarted()
Event called after a pawn has been restarted, usually by a possession change.
UFUNCTION () AController *GetController() const
Returns controller for this actor.
UFUNCTION () static 1 AActor *GetMovementBaseActor(const APawn *Pawn)
Gets the owning actor of the Movement Base Component on which the pawn is standing.
UFUNCTION () virtual FVector GetNavAgentLocation() const override
Basically retrieved pawn's location on navmesh.
UFUNCTION ()) 1 FVector GetLastMovementInputVector() const
Return the last input vector in world space that was processed by ConsumeMovementInputVector(), which is usually done by the Pawn or PawnMovementComponent.
UFUNCTION ()) 1 FVector GetPendingMovementInputVector() const
Return the pending input vector in world space.
UFUNCTION ()) 1 virtual FVector ConsumeMovementInputVector()
Returns the pending input vector and resets it to zero.
UFUNCTION ()) 1 virtual void AddControllerPitchInput(float Val)
Add input (affecting Pitch) to the Controller's ControlRotation, if it is a local PlayerController.
UFUNCTION ()) 1 virtual void AddControllerRollInput(float Val)
Add input (affecting Roll) to the Controller's ControlRotation, if it is a local PlayerController.
UFUNCTION ()) 1 virtual void AddControllerYawInput(float Val)
Add input (affecting Yaw) to the Controller's ControlRotation, if it is a local PlayerController.
UFUNCTION ()) 1 virtual void AddMovementInput(FVector WorldDirection
Add movement input along the given world direction vector (usually normalized) scaled by 'ScaleValue'.
UFUNCTION ()) 1 virtual void DetachFromControllerPendingDestroy()
Call this function to detach safely pawn from its controller, knowing that we will be destroyed soon.
UFUNCTION ()) 1 void ReceivePossessed(AController *NewController)
Event called when the Pawn is possessed by a Controller.
UFUNCTION ()) 1 void ReceiveUnpossessed(AController *OldController)
Event called when the Pawn is no longer possessed by a Controller.
UFUNCTION ()) 1 void SetCanAffectNavigationGeneration(bool bNewValue
Use SetCanAffectNavigationGeneration to change this value at runtime.
void UpdateNavAgent ()
Updates MovementComponent's parameters used by navigation system.
UPROPERTY ()
Default class to use when pawn is controlled by AI.
UPROPERTY() TEnumAsByte< EAutoReceiveInput UPROPERTY () EAutoPossessAI AutoPossessAI
Determines which PlayerController, if any, should automatically possess the pawn when the level starts or when the pawn is spawned.
UPROPERTY () float BaseEyeHeight
Base eye height above collision center.
UPROPERTY () FPawnControllerChangedSignature ReceiveControllerChangedDelegate
Event called after a pawn's controller has changed, on the server and owning client.
UPROPERTY () FPawnRestartedSignature ReceiveRestartedDelegate
Event called after a pawn has been restarted, usually by a possession change.
UPROPERTY () TObjectPtr< AController > Controller
Controller currently possessing this Actor.
UPROPERTY () TObjectPtr< AController > LastHitBy
Controller of the last Actor that caused us damage.
UPROPERTY () TObjectPtr< AController > PreviousController
Previous controller that was controlling this pawn since the last controller change notification.
Protected Member Functions
AIMODULE_API void MakeOneStep ()
AIMODULE_API void Reset () override
AIMODULE_API void UpdateDrawing ()
Protected Member Functions inherited from ACharacter
virtual void BaseChange ()
Event called after actor's base changes (if SetBase was requested to notify us with bNotifyPawn).
virtual bool CanJumpInternal_Implementation () const
FBasedMovementInfo & GetReplicatedBasedMovement_Mutable ()
This is the Replicated version of relative movement.
bool JumpIsAllowedInternal () const
void SetReplayLastTransformUpdateTimeStamp (const float InReplayLastTransformUpdateTimeStamp)
This is updated every frame to the latest timestamp, but only replicated to Replays, this is because we want to save positions to the replay replication connection each frame to ensure smooth movement.
void SetReplicatedBasedMovement (const FBasedMovementInfo &InReplicatedBasedMovement)
This is the Replicated version of relative movement.
void SetReplicatedGravityDirection (const FVector &InReplicatedGravityDirection)
CharacterMovement Custom gravity direction replicated for simulated proxies.
void SetReplicatedMovementMode (const uint8 InReplicatedMovementMode)
Sets CharacterMovement MovementMode (and custom mode) replicated for simulated proxies.
void SetReplicatedServerLastTransformUpdateTimeStamp (const float InReplicatedServerLastTransformUpdateTimeStamp)
This is the value of the CharacterMovement timestamp, and is replicated down to SimulatedProxies to assist with visual smoothing of the character.
virtual bool ShouldReplicateAcceleration () const
Whether this Character should include acceleration data in its replicated movement.
UFUNCTION ()) 1 bool CanJumpInternal() const
Customizable event to check if the character can jump in the current state.
UPROPERTY () float AnimRootMotionTranslationScale
Scale to apply to root motion translation on this Character.
UPROPERTY () float ReplayLastTransformUpdateTimeStamp
UPROPERTY () float ReplicatedServerLastTransformUpdateTimeStamp
CharacterMovement ServerLastTransformUpdateTimeStamp value, replicated to simulated proxies.
UPROPERTY () FQuat BaseRotationOffset
Saved rotation offset of mesh.
UPROPERTY () FVector BaseTranslationOffset
Saved translation offset of mesh.
UPROPERTY () FVector_NetQuantizeNormal ReplicatedGravityDirection
CharacterMovement Custom gravity direction replicated for simulated proxies.
UPROPERTY () struct FBasedMovementInfo BasedMovement
Info about our current movement base (object we are standing on).
UPROPERTY () struct FBasedMovementInfo ReplicatedBasedMovement
Replicated version of relative movement.
UPROPERTY () uint8 ReplicatedMovementMode
When true, player wants to jump.
Protected Member Functions inherited from APawn
virtual UInputComponent * CreatePlayerInputComponent ()
Creates an InputComponent that can be used for custom input bindings.
virtual void DestroyPlayerInputComponent ()
Destroys the player input component and removes any references to it.
virtual AController * GetDamageInstigator (AController *InstigatedBy, const UDamageType &DamageType) const
Get the controller instigating the damage.
virtual void OnPlayerStateChanged (APlayerState *NewPlayerState, APlayerState *OldPlayerState)
Called on both the clientand server when ever SetPlayerState is called on this pawn.
UPROPERTY () FVector ControlInputVector
Accumulated control input vector, stored in world space.
UPROPERTY () FVector LastControlInputVector
The last control input vector that was processed by ConsumeMovementInputVector().
UPROPERTY () TSubclassOf< UInputComponent > OverrideInputComponentClass
If set, then this InputComponent class will be used instead of the Input Settings' DefaultInputComponentClass.
UPROPERTY () uint16 RemoteViewPitch16
Replicated so we can see where remote clients are looking.
Static Protected Member Functions
static AIMODULE_API void OnEditorSelectionChanged (UObject *NewSelection)
Protected Attributes
TSharedPtr< FEnvQueryInstance > QueryInstance
TArray< FEnvQueryInstance > StepResults
Protected Attributes inherited from ACharacter
FVector_NetQuantizeNormal PreNetReceivedGravityDirection
Cached version of the replicated gravity direction before replication.
Private Member Functions
GENERATED_UCLASS_BODY () UPROPERTY() TObjectPtr< UEnvQuery > QueryTemplate
UE_DEPRECATED_FORGAME (5.0, "QueryParams has been deprecated for a long while now. Will be removed in the next engine version.") UPROPERTY() TArray< FEnvNamedValue > QueryParams
optional parameters for query
UPROPERTY () EEnvQueryHightlightMode HighlightMode
UPROPERTY () float TimeLimitPerStep
UPROPERTY() uint32 bDrawLabels UPROPERTY() uint32 bDrawFailedItems UPROPERTY() uint32 bReRunQueryOnlyOnFinishedMove UPROPERTY() uint32 bShouldBeVisibleInGame UPROPERTY() uint32 bTickDuringGame UPROPERTY() uint32 bRunQueryOnSelectionChanged UPROPERTY() TEnumAsByte< EEnvQueryRunMode UPROPERTY () FNavAgentProperties NavAgentProperties
UPROPERTY () int32 StepToDebugDraw
UPROPERTY () TArray< FAIDynamicParam > QueryConfig
Additional Inherited Members
Data Fields inherited from ACharacter
FVector FVector UPrimitiveComponent FName bool bool bBaseRelativePosition
FVector UPrimitiveComponent FName bool bool bBaseRelativePosition
float FVector FVector_NetQuantizeNormal float UPrimitiveComponent FName bool bool bBaseRelativePosition
FRootMotionSourceGroup bool float FVector FVector_NetQuantizeNormal float UPrimitiveComponent FName bool bool bBaseRelativePosition
FRootMotionSourceGroup bool bHasAnimRootMotion
FVector FVector UPrimitiveComponent FName bool bHasBase
FVector UPrimitiveComponent FName bool bHasBase
float FVector FVector_NetQuantizeNormal float UPrimitiveComponent FName bool bHasBase
FRootMotionSourceGroup bool float FVector FVector_NetQuantizeNormal float UPrimitiveComponent FName bool bHasBase
bool bXYOverride
bool bool bZOverride
FVector_NetQuantize10 FVector_NetQuantize100 uint8 uint8 uint32 UPrimitiveComponent FName ClientBaseBoneName
FVector_NetQuantize10 uint8 uint32 float FVector_NetQuantize10 FVector_NetQuantize100 uint8 uint8 uint32 UPrimitiveComponent FName ClientBaseBoneName
FVector_NetQuantize10 FVector_NetQuantize100 ClientLoc
FVector_NetQuantize10 uint8 uint32 float FVector_NetQuantize10 FVector_NetQuantize100 ClientLoc
FVector_NetQuantize10 FVector_NetQuantize100 uint8 uint8 uint32 UPrimitiveComponent * ClientMovementBase
FVector_NetQuantize10 uint8 uint32 float FVector_NetQuantize10 FVector_NetQuantize100 uint8 uint8 uint32 UPrimitiveComponent * ClientMovementBase
FVector_NetQuantize10 FVector_NetQuantize100 uint8 uint8 uint32 UPrimitiveComponent FName uint8 ClientMovementMode
FVector_NetQuantize10 FVector_NetQuantize100 uint8 uint8 uint32 uint8 ClientMovementMode
FVector_NetQuantize10 uint8 uint32 float FVector_NetQuantize10 FVector_NetQuantize100 uint8 uint8 uint32 UPrimitiveComponent FName uint8 ClientMovementMode
FVector_NetQuantize10 uint8 uint32 float FVector_NetQuantize10 FVector_NetQuantize100 uint8 uint8 uint32 uint8 ClientMovementMode
FVector_NetQuantize10 FVector_NetQuantize100 uint8 uint8 ClientRoll
FVector_NetQuantize10 uint8 uint32 float FVector_NetQuantize10 FVector_NetQuantize100 uint8 uint8 ClientRoll
FVector_NetQuantize10 FVector_NetQuantize100 uint8 CompressedMoveFlags
FVector_NetQuantize10 InAccel
FVector_NetQuantize10 uint8 uint32 float FVector_NetQuantize10 InAccel
FVector_NetQuantize10 InAccel0
float InPlayRate = 1.f
FRotator MeshRelativeRotation
FVector FVector UPrimitiveComponent * NewBase
FVector UPrimitiveComponent * NewBase
FVector FVector UPrimitiveComponent FName NewBaseBoneName
FVector UPrimitiveComponent FName NewBaseBoneName
EMovementMode uint8 uint8 NewCustomMode
FVector_NetQuantize10 uint8 uint32 float FVector_NetQuantize10 FVector_NetQuantize100 uint8 NewFlags
FVector NewLoc
EMovementMode NewMovementMode
FVector FVector NewVel
uint32 NumActorOverlapEventsCounter
Incremented every time there is an Actor overlap event (start or stop) on this actor.
FVector_NetQuantize10 OldAccel
FVector_NetQuantize10 uint8 OldMoveFlags
FVector_NetQuantize10 uint8 PendingFlags
EMovementMode uint8 PrevCustomMode
const FVector & PreviousFloorContactNormal
const FVector const FVector & PreviousLocation
float ScaledHalfHeightAdjust
float FVector FVector_NetQuantizeNormal float UPrimitiveComponent * ServerBase
FRootMotionSourceGroup bool float FVector FVector_NetQuantizeNormal float UPrimitiveComponent * ServerBase
float FVector FVector_NetQuantizeNormal float UPrimitiveComponent FName ServerBoneName
FRootMotionSourceGroup bool float FVector FVector_NetQuantizeNormal float UPrimitiveComponent FName ServerBoneName
float FVector ServerLoc
FRootMotionSourceGroup bool float FVector ServerLoc
float ServerMontageTrackPosition
FRootMotionSourceGroup bool float ServerMontageTrackPosition
FVector FVector UPrimitiveComponent FName bool bool uint8 ServerMovementMode
FVector UPrimitiveComponent FName bool bool uint8 ServerMovementMode
float FVector FVector_NetQuantizeNormal float UPrimitiveComponent FName bool bool uint8 ServerMovementMode
FRootMotionSourceGroup bool float FVector FVector_NetQuantizeNormal float UPrimitiveComponent FName bool bool uint8 ServerMovementMode
FRootMotionSourceGroup ServerRootMotion
float FVector FVector_NetQuantizeNormal ServerRotation
FRootMotionSourceGroup bool float FVector FVector_NetQuantizeNormal ServerRotation
float FVector FVector_NetQuantizeNormal float ServerVelZ
FRootMotionSourceGroup bool float FVector FVector_NetQuantizeNormal float ServerVelZ
float FName StartSectionName = NAME_None)
const FVector const FVector float TimeDelta
FVector_NetQuantize10 uint8 uint32 float TimeStamp
FVector_NetQuantize10 FVector_NetQuantize100 uint8 uint8 uint32 View
FVector_NetQuantize10 uint8 uint32 float FVector_NetQuantize10 FVector_NetQuantize100 uint8 uint8 uint32 View
FVector_NetQuantize10 uint8 uint32 View0
Data Fields inherited from APawn
float AllowedYawError
Max difference between pawn's Rotation.Yaw and GetDesiredRotation().Yaw for pawn to be considered as having reached its desired rotation.
float bool bForce = false)
bool bForceUpdate = false)
FVector bool bUseNoiseMakerLocation = true
AController * NewController
FVector NoiseLocation
FVector bool AActor * NoiseMaker = nullptr)
float ScaleValue = 1.0f
Static Public Attributes inherited from ACharacter
static FName CapsuleComponentName
Name of the CapsuleComponent.
static FName CharacterMovementComponentName
Name of the CharacterMovement component.
static FName MeshComponentName
Name of the MeshComponent.
Static Public Attributes inherited from APawn
static FOnPawnBeginPlay OnPawnBeginPlay
a delegate that broadcasts a notification whenever BeginPlay() is called
Detailed Description
Definition at line 25 of file EQSTestingPawn.h.
Member Function Documentation
GENERATED_UCLASS_BODY()
AEQSTestingPawn::GENERATED_UCLASS_BODY () private
References APawn::Category, and UPROPERTY().
GetHighlightRangePct()
virtual AIMODULE_API float AEQSTestingPawn::GetHighlightRangePct () const override virtual
Reimplemented from IEQSQueryResultSourceInterface.
GetNavAgentPropertiesRef()
virtual AIMODULE_API const FNavAgentProperties & AEQSTestingPawn::GetNavAgentPropertiesRef () const override virtual
Reimplemented from APawn.
GetQueryInstance()
virtual AIMODULE_API const FEnvQueryInstance * AEQSTestingPawn::GetQueryInstance () const override virtual
Reimplemented from IEQSQueryResultSourceInterface.
GetQueryResult()
virtual AIMODULE_API const FEnvQueryResult * AEQSTestingPawn::GetQueryResult () const override virtual
GetShouldDebugDrawLabels()
virtual bool AEQSTestingPawn::GetShouldDebugDrawLabels () const inline override virtual
Reimplemented from IEQSQueryResultSourceInterface.
Definition at line 101 of file EQSTestingPawn.h.
GetShouldDrawFailedItems()
virtual bool AEQSTestingPawn::GetShouldDrawFailedItems () const inline override virtual
Reimplemented from IEQSQueryResultSourceInterface.
Definition at line 102 of file EQSTestingPawn.h.
MakeOneStep()
AIMODULE_API void AEQSTestingPawn::MakeOneStep () protected
OnEditorSelectionChanged()
AIMODULE_API void AEQSTestingPawn::OnEditorSelectionChanged (UObject * NewSelection) static protected
OnPropertyChanged()
AIMODULE_API void AEQSTestingPawn::OnPropertyChanged (const FName PropName)
PostEditChangeProperty()
virtual AIMODULE_API void AEQSTestingPawn::PostEditChangeProperty (struct FPropertyChangedEvent & PropertyChangedEvent) override virtual
Reimplemented from APawn.
PostEditMove()
virtual AIMODULE_API void AEQSTestingPawn::PostEditMove (bool bFinished) override virtual
PostLoad()
virtual AIMODULE_API void AEQSTestingPawn::PostLoad () override virtual
Reimplemented from ACharacter.
PostTransacted()
virtual AIMODULE_API void AEQSTestingPawn::PostTransacted (const FTransactionObjectEvent & TransactionEvent) override virtual
Reset()
AIMODULE_API void AEQSTestingPawn::Reset () override protected virtual
Reimplemented from APawn.
RunEQSQuery()
AIMODULE_API void AEQSTestingPawn::RunEQSQuery ()
TickActor()
virtual AIMODULE_API void AEQSTestingPawn::TickActor (float DeltaTime, enum ELevelTick TickType, FActorTickFunction & ThisTickFunction) override virtual
This pawn class spawns its controller in PostInitProperties to have it available in editor mode.
References DeltaTime.
UE_DEPRECATED_FORGAME()
AEQSTestingPawn::UE_DEPRECATED_FORGAME (5. 0, "QueryParams has been deprecated for a long while now. Will be removed in the next engine version.") private
optional parameters for query
References UE_DEPRECATED_FORGAME(), and UPROPERTY().
Referenced by UE_DEPRECATED_FORGAME().
UpdateDrawing()
AIMODULE_API void AEQSTestingPawn::UpdateDrawing () protected
UPROPERTY() [1/5]
AEQSTestingPawn::UPROPERTY () private
References APawn::Category, and UPROPERTY().
UPROPERTY() [2/5]
AEQSTestingPawn::UPROPERTY () private
References APawn::Category, and UPROPERTY().
UPROPERTY() [3/5]
UPROPERTY() uint32 bDrawLabels UPROPERTY() uint32 bDrawFailedItems UPROPERTY() uint32 bReRunQueryOnlyOnFinishedMove UPROPERTY() uint32 bShouldBeVisibleInGame UPROPERTY() uint32 bTickDuringGame UPROPERTY() uint32 bRunQueryOnSelectionChanged UPROPERTY() TEnumAsByte< EEnvQueryRunMode AEQSTestingPawn::UPROPERTY () private
References APawn::Category, Transient, and UPROPERTY().
UPROPERTY() [4/5]
AEQSTestingPawn::UPROPERTY () private
References APawn::Category, and UPROPERTY().
UPROPERTY() [5/5]
AEQSTestingPawn::UPROPERTY () private
References APawn::Category, and UPROPERTY().
Referenced by GENERATED_UCLASS_BODY(), UE_DEPRECATED_FORGAME(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), and UPROPERTY().
Field Documentation
QueryInstance
TSharedPtr<FEnvQueryInstance> AEQSTestingPawn::QueryInstance protected
Definition at line 81 of file EQSTestingPawn.h.
StepResults
TArray<FEnvQueryInstance> AEQSTestingPawn::StepResults protected
Definition at line 83 of file EQSTestingPawn.h.
The documentation for this class was generated from the following file:
Runtime/AIModule/Classes/EnvironmentQuery/EQSTestingPawn.h