Unreal Engine 5.6 C++ API: IMovieSceneChannelOverrideProvider Class Reference
IMovieSceneChannelOverrideProvider Class Reference abstract
Interface to be added to UMovieSceneSection types when they contain entity data.
#include "IMovieSceneChannelOverrideProvider.h"
Public Types
using FChannelOverrideProviderTraitsHandle = UE::MovieScene::FChannelOverrideProviderTraitsHandle
Public Member Functions
GENERATED_BODY () virtual UMovieSceneSectionChannelOverrideRegistry *GetChannelOverrideRegistry(bool bCreateIfMissing)=0
Gets the channel override container.
virtual FChannelOverrideProviderTraitsHandle GetChannelOverrideProviderTraits () const =0
Gets the naming/indexing traits for this provider.
virtual void OnChannelOverridesChanged ()=0
Called when channel overrides have been added or removed.
Detailed Description
Interface to be added to UMovieSceneSection types when they contain entity data.
Definition at line 149 of file IMovieSceneChannelOverrideProvider.h.
Member Typedef Documentation
FChannelOverrideProviderTraitsHandle
using IMovieSceneChannelOverrideProvider::FChannelOverrideProviderTraitsHandle = UE::MovieScene::FChannelOverrideProviderTraitsHandle
Definition at line 153 of file IMovieSceneChannelOverrideProvider.h.
Member Function Documentation
GENERATED_BODY()
IMovieSceneChannelOverrideProvider::GENERATED_BODY () pure virtual
Gets the channel override container.
GetChannelOverrideProviderTraits()
virtual FChannelOverrideProviderTraitsHandle IMovieSceneChannelOverrideProvider::GetChannelOverrideProviderTraits () const pure virtual
Gets the naming/indexing traits for this provider.
References GetChannelOverrideProviderTraits().
Referenced by GetChannelOverrideProviderTraits().
OnChannelOverridesChanged()
virtual void IMovieSceneChannelOverrideProvider::OnChannelOverridesChanged () pure virtual
Called when channel overrides have been added or removed.
Should invalidate the channel proxy.
References OnChannelOverridesChanged().
Referenced by OnChannelOverridesChanged().
The documentation for this class was generated from the following file:
Runtime/MovieScene/Public/Channels/IMovieSceneChannelOverrideProvider.h