Unreal Engine 5.6 C++ API: UGroomComponent Class Reference
UGroomComponent Class Reference
#include "GroomComponent.h"
Private Member Functions
virtual HAIRSTRANDSCORE_API void BeginDestroy () override
virtual HAIRSTRANDSCORE_API UPhysicsAsset * BuildAndCollect (FTransform &BoneTransform, TArray< TWeakObjectPtr< USkeletalMeshComponent > > &SourceComponents, TArray< TWeakObjectPtr< UPhysicsAsset > > &PhysicsAssets) const override
HAIRSTRANDSCORE_API void BuildSimulationTransform (FTransform &SimulationTransform) const
Build the local simulation transform that could be used in strands simulation.
virtual HAIRSTRANDSCORE_API FBoxSphereBounds CalcBounds (const FTransform &LocalToWorld) const override
virtual HAIRSTRANDSCORE_API bool CanEditChange (const FProperty *InProperty) const override
virtual HAIRSTRANDSCORE_API void CheckForErrors () override
void CheckHairStrandsUsage (int32 ElementIndex) const
virtual HAIRSTRANDSCORE_API void CollectPSOPrecacheData (const FPSOPrecacheParams &BasePrecachePSOParams, FMaterialInterfacePSOPrecacheParamsList &OutParams) override
bool ContainsGroupInstance (FHairGroupInstance *Instance) const
HAIRSTRANDSCORE_API void CreateHairSimulation (const int32 GroupIndex, const int32 LODIndex)
Create per Group/LOD the Niagara component.
virtual HAIRSTRANDSCORE_API void CreateRenderState_Concurrent (FRegisterComponentContext *Context) override
virtual HAIRSTRANDSCORE_API FPrimitiveSceneProxy * CreateSceneProxy () override
void DeleteDeferredHairGroupInstances ()
virtual HAIRSTRANDSCORE_API void DestroyRenderState_Concurrent () override
virtual HAIRSTRANDSCORE_API void DetachFromComponent (const FDetachmentTransformRules &DetachmentRules) override
virtual HAIRSTRANDSCORE_API void FinishDestroy () override
HAIRSTRANDSCORE_API float GetAnimationTime () const
virtual HAIRSTRANDSCORE_API int32 GetBestAvailableLOD () const override
Returns the best (i.e.
virtual HAIRSTRANDSCORE_API int32 GetDesiredSyncLOD () const override
~ Begin ILODSyncInterface Interface.
HAIRSTRANDSCORE_API int32 GetForcedLOD () const
virtual HAIRSTRANDSCORE_API int32 GetForceRenderedLOD () const override
Returns the LOD that will be forced to use for rendering, or INDEX_NONE if there is no forced LOD for rendering.
virtual HAIRSTRANDSCORE_API int32 GetForceStreamedLOD () const override
Returns the LOD that will be forced to stream in, or INDEX_NONE if there is no forced LOD for streaming.
UGroomCache * GetGroomCache () const
GroomCache.
HAIRSTRANDSCORE_API float GetGroomCacheDuration () const
UMeshComponent * GetGroomSolver () const
Get the groom solver from the component.
uint32 GetGroupCount () const
Hair group instance access.
FHairGroupInstance * GetGroupInstance (int32 Index)
const FHairGroupInstance * GetGroupInstance (int32 Index) const
HAIRSTRANDSCORE_API FHairStrandsDeformedResource * GetGuideStrandsDeformedResource (uint32 GroupIndex)
Return the guide hairs deformed resources.
HAIRSTRANDSCORE_API FHairStrandsDeformedRootResource * GetGuideStrandsDeformedRootResource (uint32 GroupIndex)
HAIRSTRANDSCORE_API FHairStrandsRestResource * GetGuideStrandsRestResource (uint32 GroupIndex)
Return the guide hairs rest resources.
HAIRSTRANDSCORE_API FHairStrandsRestRootResource * GetGuideStrandsRestRootResource (uint32 GroupIndex)
Return the guide hairs root resources.
HAIRSTRANDSCORE_API bool GetManualTick () const
virtual HAIRSTRANDSCORE_API UMaterialInterface * GetMaterial (int32 ElementIndex) const override
HAIRSTRANDSCORE_API UMaterialInterface * GetMaterial (int32 ElementIndex, EHairGeometryType GeometryType, bool bUseDefaultIfIncompatible) const
HAIRSTRANDSCORE_API EHairGeometryType GetMaterialGeometryType (int32 ElementIndex) const
virtual HAIRSTRANDSCORE_API int32 GetMaterialIndex (FName MaterialSlotName) const override
virtual HAIRSTRANDSCORE_API TArray< FName > GetMaterialSlotNames () const override
HAIRSTRANDSCORE_API int32 GetNumLODs () const
virtual HAIRSTRANDSCORE_API int32 GetNumMaterials () const override
virtual HAIRSTRANDSCORE_API int32 GetNumSyncLODs () const override
Returns the total number of LODs, including LODs that are streamed out and unavailable.
virtual HAIRSTRANDSCORE_API void GetResourceSizeEx (FResourceSizeEx &CumulativeResourceSize) override
HAIRSTRANDSCORE_API uint32 GetResourcesSize () const
virtual HAIRSTRANDSCORE_API void GetUsedMaterials (TArray< UMaterialInterface * > &OutMaterials, bool bGetDebugMaterials=false) const override
HAIRSTRANDSCORE_API void HandleFeatureLevelChanged (ERHIFeatureLevel::Type InFeatureLevel)
HAIRSTRANDSCORE_API void HandlePlatformPreviewChanged (ERHIFeatureLevel::Type InFeatureLevel)
void InitIfDependenciesReady (const bool bUpdateSimulation=true)
void InitResources (bool bIsBindingReloading=false)
HAIRSTRANDSCORE_API void Invalidate ()
HAIRSTRANDSCORE_API void InvalidateAndRecreate ()
virtual HAIRSTRANDSCORE_API bool IsCompiling () const override
HAIRSTRANDSCORE_API bool IsDeformationEnable (int32 GroupIndex) const
Check if the deformation is enabled or not (from the rigged guides or from the solver deformer)
bool IsLooping () const
virtual HAIRSTRANDSCORE_API bool IsMaterialSlotNameValid (FName MaterialSlotName) const override
HAIRSTRANDSCORE_API bool IsSimulationEnable (int32 GroupIndex, int32 LODIndex) const
Check if the simulation is enabled or not.
virtual HAIRSTRANDSCORE_API void OnAttachmentChanged () override
virtual HAIRSTRANDSCORE_API void OnComponentDestroyed (bool bDestroyingHierarchy) override
virtual HAIRSTRANDSCORE_API void OnRegister () override
virtual HAIRSTRANDSCORE_API void OnUnregister () override
HAIRSTRANDSCORE_API void PostCompilation ()
virtual HAIRSTRANDSCORE_API void PostEditChangeProperty (FPropertyChangedEvent &PropertyChangedEvent) override
virtual HAIRSTRANDSCORE_API void PostLoad () override
virtual HAIRSTRANDSCORE_API void PreEditChange (FProperty *PropertyAboutToChange) override
virtual HAIRSTRANDSCORE_API void PreFeatureLevelChange (ERHIFeatureLevel::Type PendingFeatureLevel) override
HAIRSTRANDSCORE_API void ReleaseHairSimulation ()
Release Niagara components.
HAIRSTRANDSCORE_API void ReleaseHairSimulation (const int32 GroupIndex)
void ReleaseResources ()
virtual HAIRSTRANDSCORE_API bool RequiresGameThreadEndOfFrameRecreate () const override
HAIRSTRANDSCORE_API void ResetAnimationTime ()
virtual HAIRSTRANDSCORE_API void SendRenderDynamicData_Concurrent () override
HAIRSTRANDSCORE_API void SetBinding (UGroomBindingAsset *InBinding)
HAIRSTRANDSCORE_API void SetForcedLOD (int32 LODIndex)
virtual HAIRSTRANDSCORE_API void SetForceRenderedLOD (int32 LODIndex) override
Sets the LOD to use for rendering, as a 0-based index.
virtual HAIRSTRANDSCORE_API void SetForceStreamedLOD (int32 LODIndex) override
Sets the LOD to force to stream in, as a 0-based index.
HAIRSTRANDSCORE_API void SetGroomAsset (UGroomAsset *Asset, UGroomBindingAsset *InBinding, const bool bUpdateSimulation=true)
void SetGroomSolver (UMeshComponent *InGroomSolver)
Set the groom solver onto the component.
HAIRSTRANDSCORE_API void SetHairRootScale (float Scale)
HAIRSTRANDSCORE_API void SetHairWidth (float HairWidth)
HAIRSTRANDSCORE_API void SetManualTick (bool bInManualTick)
HAIRSTRANDSCORE_API void SetScatterSceneLighting (bool Enable)
HAIRSTRANDSCORE_API void SetStableRasterization (bool bEnable)
HAIRSTRANDSCORE_API void SetUseCards (bool InbUseCards)
void SetValidation (bool bEnable)
HAIRSTRANDSCORE_API void SwitchSimulationLOD (const int32 PreviousLOD, const int32 CurrentLOD, const EHairLODSelectionType InLODSelectionType)
Enable/Disable hair simulation while transitioning from one LOD to another one.
HAIRSTRANDSCORE_API void TickAtThisTime (const float Time, bool bInIsRunning, bool bInBackwards, bool bInIsLooping)
virtual HAIRSTRANDSCORE_API void TickComponent (float DeltaTime, enum ELevelTick TickType, FActorComponentTickFunction *ThisTickFunction) override
UFUNCTION () HAIRSTRANDSCORE_API bool GetIsHairLengthScaleEnabled()
UFUNCTION () HAIRSTRANDSCORE_API void AddCollisionComponent(USkeletalMeshComponent *SkeletalMeshComponent)
UFUNCTION () HAIRSTRANDSCORE_API void ResetCollisionComponents()
UFUNCTION () HAIRSTRANDSCORE_API void ResetSimulation()
UFUNCTION () HAIRSTRANDSCORE_API void SetBindingAsset(UGroomBindingAsset *InBinding)
UFUNCTION () HAIRSTRANDSCORE_API void SetEnableSimulation(bool bInEnableSimulation)
UFUNCTION () HAIRSTRANDSCORE_API void SetGroomAsset(UGroomAsset *Asset)
UFUNCTION () HAIRSTRANDSCORE_API void SetGroomCache(UGroomCache *InGroomCache)
UFUNCTION () HAIRSTRANDSCORE_API void SetHairLengthScale(float Scale)
UFUNCTION () HAIRSTRANDSCORE_API void SetHairLengthScaleEnable(bool bEnable)
UFUNCTION () HAIRSTRANDSCORE_API void SetMeshDeformer(UMeshDeformer *InMeshDeformer)
UFUNCTION () HAIRSTRANDSCORE_API void SetPhysicsAsset(UPhysicsAsset *InPhysicsAsset)
UFUNCTION () UNiagaraComponent *GetNiagaraComponent(const int32 GroupIndex)
void UpdateGroomCache (float Time)
HAIRSTRANDSCORE_API void UpdateHairGroupsDesc ()
Update Group Description.
HAIRSTRANDSCORE_API void UpdateHairGroupsDescAndInvalidateRenderState (bool bInvalidate=true)
HAIRSTRANDSCORE_API void UpdateHairSimulation ()
Update Niagara components.
HAIRSTRANDSCORE_API void UpdateSimulatedGroups ()
Update simulated groups.
UPROPERTY () bool bLooping
UPROPERTY () bool bManualTick
UPROPERTY () bool bRunning
UPROPERTY () bool bUseCards
Force the groom to use cards/meshes geometry instead of strands.
UPROPERTY () FHairSimulationSettings SimulationSettings
Groom's simulation settings.
UPROPERTY () float ElapsedTime
UPROPERTY () FString AttachmentName
Optional socket name, where the groom component should be attached at, when parented with a skeletal mesh.
UPROPERTY () TArray< FHairGroupDesc > GroomGroupsDesc
Groom's groups info.
UPROPERTY () TArray< TObjectPtr< class UNiagaraComponent > > NiagaraComponents
Niagara components that will be attached to the system.
UPROPERTY () TObjectPtr< class UGroomBindingAsset > BindingAsset
Optional binding asset for binding a groom onto a skeletal mesh.
UPROPERTY () TObjectPtr< class UNiagaraSystem > AngularSpringsSystem
UPROPERTY () TObjectPtr< class UNiagaraSystem > CosseratRodsSystem
UPROPERTY () TObjectPtr< class UPhysicsAsset > PhysicsAsset
Physics asset to be used for hair simulation.
UPROPERTY () TObjectPtr< class USkeletalMesh > SourceSkeletalMesh
GENERATED_UCLASS_BODY() public UPROPERTY () TObjectPtr< UGroomCache > GroomCache
Groom asset .
UPROPERTY () TObjectPtr< UMaterialInterface > Cards_DefaultMaterial
UPROPERTY () TObjectPtr< UMaterialInterface > Meshes_DefaultMaterial
UPROPERTY () TObjectPtr< UMaterialInterface > Strands_DebugMaterial
UPROPERTY () TObjectPtr< UMaterialInterface > Strands_DefaultMaterial
UPROPERTY () TObjectPtr< UMeshDeformerInstance > MeshDeformerInstance
Object containing state for the bound MeshDeformer.
UPROPERTY ()) TObjectPtr< UMeshDeformer > MeshDeformer
If set the MeshDeformer will be applied on groom instance for deformation.
UPROPERTY ()) TObjectPtr< UMeshDeformerInstanceSettings > MeshDeformerInstanceSettings
Object containing instance settings for the bound MeshDeformer.
HAIRSTRANDSCORE_API void ValidateMaterials (bool bMapCheck) const
Private Attributes
bool bInitSimulation
Boolean to check when the simulation should be initialized.
bool bIsGroomAssetCallbackRegistered
bool bIsGroomBindingAssetCallbackRegistered
bool bPreviewMode = false
bool bResetSimulation
Boolean to check when the simulation should be reset.
bool bValidationEnable = true
TArray< TWeakObjectPtr< class USkeletalMeshComponent > > CollisionComponents
List of collision components to be used.
class UMeshComponent * DeformedMeshComponent
TSharedPtr< class IGroomCacheBuffers, ESPMode::ThreadSafe > GroomCacheBuffers
TSoftObjectPtr< UMeshComponent > GroomSolver = nullptr
Groom solver pointer.
TArray< TRefCountPtr< FHairGroupInstance > > HairGroupInstances
void * InitializedResources
float LODForcedIndex = -1.f
float LODPredictedIndex = -1.f
EHairLODSelectionType LODSelectionType = EHairLODSelectionType::Immediate
FMatrix PrevBoneMatrix
Previous bone matrix to compare the difference and decide to reset or not the simulation.
class UMeshComponent * RegisteredMeshComponent
Friends
class FGroomComponentRecreateRenderStateContext
class FHairCardsSceneProxy
class FHairStrandsSceneProxy
class UGroomBindingAsset
Additional Inherited Members
Public Member Functions inherited from UMeshComponent
const TArray< TObjectPtr< UMaterialInterface > > & GetComponentMaterialSlotsOverlayMaterial () const
Retrieve the material slots overly materials assigned to this component.
virtual void GetDefaultMaterialSlotsOverlayMaterial (TArray< TObjectPtr< UMaterialInterface > > &OutMaterialSlotOverlayMaterials) const
Get all default material slots overlay materials from the mesh.
float GetScalarParameterDefaultValue (const FName ParameterName)
Returns default value for the parameter input.
UFUNCTION () 1 void SetColorParameterValueOnMaterials(const FName ParameterName
Set all occurrences of Vector Material Parameters with ParameterName in the set of materials of the SkeletalMesh to ParameterValue.
UFUNCTION () 1 void SetScalarParameterValueOnMaterials(const FName ParameterName
Set all occurrences of Scalar Material Parameters with ParameterName in the set of materials of the SkeletalMesh to ParameterValue.
UFUNCTION () 1 void SetVectorParameterValueOnMaterials(const FName ParameterName
Set all occurrences of Vector Material Parameters with ParameterName in the set of materials of the SkeletalMesh to ParameterValue.
Data Fields inherited from UMeshComponent
const float ParameterValue
const FVector ParameterValue
const FLinearColor ParameterValue
Protected Member Functions inherited from UMeshComponent
void CacheMaterialParameterNameIndices ()
Retrieves all the (scalar/vector-)parameters from within the used materials on the SkeletalMesh, and stores material index vs parameter names.
virtual UMaterialInterface * GetDefaultOverlayMaterial () const
Get the default overlay material used by a mesh.
virtual float GetDefaultOverlayMaterialMaxDrawDistance () const
Get the default overlay material max draw distance.
void MarkCachedMaterialParameterNameIndicesDirty ()
Mark cache parameters map as dirty, cache will be rebuild once SetScalar/SetVector functions are called.
Protected Attributes inherited from UMeshComponent
uint8 bCachedMaterialParameterIndicesAreDirty: 1
Whether or not to cache material parameter to speed up setting scalar or vector value on materials.
TSortedMap< FName, FMaterialParameterCache, FDefaultAllocator, FNameFastLess > MaterialParameterCache
Detailed Description
Definition at line 28 of file GroomComponent.h.
Member Function Documentation
BeginDestroy()
virtual HAIRSTRANDSCORE_API void UGroomComponent::BeginDestroy () override private virtual
Reimplemented from UMeshComponent.
References BeginDestroy(), and UE_API.
Referenced by BeginDestroy().
BuildAndCollect()
virtual HAIRSTRANDSCORE_API UPhysicsAsset * UGroomComponent::BuildAndCollect (FTransform & BoneTransform, TArray< TWeakObjectPtr< USkeletalMeshComponent > > & SourceComponents, TArray< TWeakObjectPtr< UPhysicsAsset > > & PhysicsAssets) const override private virtual
References UE_API.
BuildSimulationTransform()
HAIRSTRANDSCORE_API void UGroomComponent::BuildSimulationTransform (FTransform & SimulationTransform) const private
Build the local simulation transform that could be used in strands simulation.
References UE_API.
CalcBounds()
virtual HAIRSTRANDSCORE_API FBoxSphereBounds UGroomComponent::CalcBounds (const FTransform & LocalToWorld) const override private virtual
References CalcBounds(), and UE_API.
Referenced by CalcBounds().
CanEditChange()
virtual HAIRSTRANDSCORE_API bool UGroomComponent::CanEditChange (const FProperty * InProperty) const override private virtual
References UE_API.
CheckForErrors()
virtual HAIRSTRANDSCORE_API void UGroomComponent::CheckForErrors () override private virtual
References UE_API.
CheckHairStrandsUsage()
void UGroomComponent::CheckHairStrandsUsage (int32 ElementIndex) const private
CollectPSOPrecacheData()
virtual HAIRSTRANDSCORE_API void UGroomComponent::CollectPSOPrecacheData (const FPSOPrecacheParams & BasePrecachePSOParams, FMaterialInterfacePSOPrecacheParamsList & OutParams) override private virtual
References CollectPSOPrecacheData(), and UE_API.
Referenced by CollectPSOPrecacheData().
ContainsGroupInstance()
bool UGroomComponent::ContainsGroupInstance (FHairGroupInstance * Instance) const inline private
Definition at line 276 of file GroomComponent.h.
References HairGroupInstances, and Instance.
CreateHairSimulation()
HAIRSTRANDSCORE_API void UGroomComponent::CreateHairSimulation (const int32 GroupIndex, const int32 LODIndex) private
Create per Group/LOD the Niagara component.
References CreateHairSimulation(), and UE_API.
Referenced by CreateHairSimulation().
CreateRenderState_Concurrent()
virtual HAIRSTRANDSCORE_API void UGroomComponent::CreateRenderState_Concurrent (FRegisterComponentContext * Context) override private virtual
References CreateRenderState_Concurrent(), and UE_API.
Referenced by CreateRenderState_Concurrent().
CreateSceneProxy()
virtual HAIRSTRANDSCORE_API FPrimitiveSceneProxy * UGroomComponent::CreateSceneProxy () override private virtual
References CreateSceneProxy(), and UE_API.
Referenced by CreateSceneProxy().
DeleteDeferredHairGroupInstances()
void UGroomComponent::DeleteDeferredHairGroupInstances () private
DestroyRenderState_Concurrent()
virtual HAIRSTRANDSCORE_API void UGroomComponent::DestroyRenderState_Concurrent () override private virtual
References DestroyRenderState_Concurrent(), and UE_API.
Referenced by DestroyRenderState_Concurrent().
DetachFromComponent()
virtual HAIRSTRANDSCORE_API void UGroomComponent::DetachFromComponent (const FDetachmentTransformRules & DetachmentRules) override private virtual
References DetachFromComponent(), and UE_API.
Referenced by DetachFromComponent().
FinishDestroy()
virtual HAIRSTRANDSCORE_API void UGroomComponent::FinishDestroy () override private virtual
References FinishDestroy(), and UE_API.
Referenced by FinishDestroy().
GetAnimationTime()
HAIRSTRANDSCORE_API float UGroomComponent::GetAnimationTime () const private
References GetAnimationTime(), and UE_API.
Referenced by GetAnimationTime().
GetBestAvailableLOD()
virtual HAIRSTRANDSCORE_API int32 UGroomComponent::GetBestAvailableLOD () const override private virtual
Returns the best (i.e.
lowest numbered) LOD that is streamed in and can be used for rendering immediately.
Callers can assume that any LOD worse (higher numbered) than this is also available.
Returns INDEX_NONE if no LODs are available, e.g. if there's no mesh set on the component. In this case, the LOD Sync Component won't take this component's desired LOD into account, but will still set a forced LOD on it in case it does get rendered.
Implements ILODSyncInterface.
References UE_API.
GetDesiredSyncLOD()
virtual HAIRSTRANDSCORE_API int32 UGroomComponent::GetDesiredSyncLOD () const override private virtual
~ Begin ILODSyncInterface Interface.
References UE_API.
GetForcedLOD()
HAIRSTRANDSCORE_API int32 UGroomComponent::GetForcedLOD () const private
References UE_API.
GetForceRenderedLOD()
virtual HAIRSTRANDSCORE_API int32 UGroomComponent::GetForceRenderedLOD () const override private virtual
Returns the LOD that will be forced to use for rendering, or INDEX_NONE if there is no forced LOD for rendering.
Note that this is not guaranteed to return the value that was set by the last call to SetForceRenderedLOD, as the implementation is permitted to change the force rendered LOD outside of calls to that function.
Implements ILODSyncInterface.
References UE_API.
GetForceStreamedLOD()
virtual HAIRSTRANDSCORE_API int32 UGroomComponent::GetForceStreamedLOD () const override private virtual
Returns the LOD that will be forced to stream in, or INDEX_NONE if there is no forced LOD for streaming.
Note that this is not guaranteed to return the value that was set by the last call to SetForceStreamedLOD, as the implementation is permitted to change the force streamed LOD outside of calls to that function.
Implements ILODSyncInterface.
References UE_API.
GetGroomCache()
UGroomCache * UGroomComponent::GetGroomCache () const inline private
GroomCache.
Definition at line 295 of file GroomComponent.h.
GetGroomCacheDuration()
HAIRSTRANDSCORE_API float UGroomComponent::GetGroomCacheDuration () const private
References GetGroomCacheDuration(), and UE_API.
Referenced by GetGroomCacheDuration().
GetGroomSolver()
UMeshComponent * UGroomComponent::GetGroomSolver () const inline private
Get the groom solver from the component.
Definition at line 315 of file GroomComponent.h.
References GroomSolver.
GetGroupCount()
uint32 UGroomComponent::GetGroupCount () const inline private
Hair group instance access.
Definition at line 273 of file GroomComponent.h.
References GetGroupCount(), and HairGroupInstances.
Referenced by GetGroupCount().
GetGroupInstance() [1/2]
FHairGroupInstance * UGroomComponent::GetGroupInstance (int32 Index) inline private
Definition at line 274 of file GroomComponent.h.
References HairGroupInstances.
GetGroupInstance() [2/2]
const FHairGroupInstance * UGroomComponent::GetGroupInstance (int32 Index) const inline private
Definition at line 275 of file GroomComponent.h.
References HairGroupInstances.
GetGuideStrandsDeformedResource()
HAIRSTRANDSCORE_API FHairStrandsDeformedResource * UGroomComponent::GetGuideStrandsDeformedResource (uint32 GroupIndex) private
Return the guide hairs deformed resources.
References GetGuideStrandsDeformedResource(), and UE_API.
Referenced by GetGuideStrandsDeformedResource().
GetGuideStrandsDeformedRootResource()
HAIRSTRANDSCORE_API FHairStrandsDeformedRootResource * UGroomComponent::GetGuideStrandsDeformedRootResource (uint32 GroupIndex) private
References GetGuideStrandsDeformedRootResource(), and UE_API.
Referenced by GetGuideStrandsDeformedRootResource().
GetGuideStrandsRestResource()
HAIRSTRANDSCORE_API FHairStrandsRestResource * UGroomComponent::GetGuideStrandsRestResource (uint32 GroupIndex) private
Return the guide hairs rest resources.
References GetGuideStrandsRestResource(), and UE_API.
Referenced by GetGuideStrandsRestResource().
GetGuideStrandsRestRootResource()
HAIRSTRANDSCORE_API FHairStrandsRestRootResource * UGroomComponent::GetGuideStrandsRestRootResource (uint32 GroupIndex) private
Return the guide hairs root resources.
References GetGuideStrandsRestRootResource(), and UE_API.
Referenced by GetGuideStrandsRestRootResource().
GetManualTick()
HAIRSTRANDSCORE_API bool UGroomComponent::GetManualTick () const private
References GetManualTick(), and UE_API.
Referenced by GetManualTick().
GetMaterial() [1/2]
virtual HAIRSTRANDSCORE_API UMaterialInterface * UGroomComponent::GetMaterial (int32 ElementIndex) const override private virtual
Reimplemented from UMeshComponent.
References UE_API.
GetMaterial() [2/2]
HAIRSTRANDSCORE_API UMaterialInterface * UGroomComponent::GetMaterial (int32 ElementIndex, EHairGeometryType GeometryType, bool bUseDefaultIfIncompatible) const private
References UE_API.
GetMaterialGeometryType()
HAIRSTRANDSCORE_API EHairGeometryType UGroomComponent::GetMaterialGeometryType (int32 ElementIndex) const private
References UE_API.
GetMaterialIndex()
virtual HAIRSTRANDSCORE_API int32 UGroomComponent::GetMaterialIndex (FName MaterialSlotName) const override private virtual
References UE_API.
GetMaterialSlotNames()
virtual HAIRSTRANDSCORE_API TArray< FName > UGroomComponent::GetMaterialSlotNames () const override private virtual
References UE_API.
GetNumLODs()
HAIRSTRANDSCORE_API int32 UGroomComponent::GetNumLODs () const private
References UE_API.
GetNumMaterials()
virtual HAIRSTRANDSCORE_API int32 UGroomComponent::GetNumMaterials () const override private virtual
Reimplemented from UMeshComponent.
References bPreviewMode, and UE_API.
GetNumSyncLODs()
virtual HAIRSTRANDSCORE_API int32 UGroomComponent::GetNumSyncLODs () const override private virtual
Returns the total number of LODs, including LODs that are streamed out and unavailable.
Returns 0 if there are no LODs, e.g. if there's no mesh set on the component.
Implements ILODSyncInterface.
References UE_API.
GetResourceSizeEx()
virtual HAIRSTRANDSCORE_API void UGroomComponent::GetResourceSizeEx (FResourceSizeEx & CumulativeResourceSize) override private virtual
References GetResourceSizeEx(), and UE_API.
Referenced by GetResourceSizeEx().
GetResourcesSize()
HAIRSTRANDSCORE_API uint32 UGroomComponent::GetResourcesSize () const private
References GetResourcesSize(), and UE_API.
Referenced by GetResourcesSize().
GetUsedMaterials()
virtual HAIRSTRANDSCORE_API void UGroomComponent::GetUsedMaterials (TArray< UMaterialInterface * > & OutMaterials, bool bGetDebugMaterials = false) const override private virtual
Reimplemented from UMeshComponent.
References UE_API.
HandleFeatureLevelChanged()
HAIRSTRANDSCORE_API void UGroomComponent::HandleFeatureLevelChanged (ERHIFeatureLevel::Type InFeatureLevel) private
References UE_API.
HandlePlatformPreviewChanged()
HAIRSTRANDSCORE_API void UGroomComponent::HandlePlatformPreviewChanged (ERHIFeatureLevel::Type InFeatureLevel) private
References UE_API.
InitIfDependenciesReady()
void UGroomComponent::InitIfDependenciesReady (const bool bUpdateSimulation = true) private
InitResources()
void UGroomComponent::InitResources (bool bIsBindingReloading = false) private
Invalidate()
HAIRSTRANDSCORE_API void UGroomComponent::Invalidate () private
References UE_API.
InvalidateAndRecreate()
HAIRSTRANDSCORE_API void UGroomComponent::InvalidateAndRecreate () private
References UE_API.
IsCompiling()
virtual HAIRSTRANDSCORE_API bool UGroomComponent::IsCompiling () const override private virtual
References UE_API.
IsDeformationEnable()
HAIRSTRANDSCORE_API bool UGroomComponent::IsDeformationEnable (int32 GroupIndex) const private
Check if the deformation is enabled or not (from the rigged guides or from the solver deformer)
References IsDeformationEnable(), and UE_API.
Referenced by IsDeformationEnable().
IsLooping()
bool UGroomComponent::IsLooping () const inline private
Definition at line 309 of file GroomComponent.h.
References IsLooping().
Referenced by IsLooping().
IsMaterialSlotNameValid()
virtual HAIRSTRANDSCORE_API bool UGroomComponent::IsMaterialSlotNameValid (FName MaterialSlotName) const override private virtual
References UE_API.
IsSimulationEnable()
HAIRSTRANDSCORE_API bool UGroomComponent::IsSimulationEnable (int32 GroupIndex, int32 LODIndex) const private
Check if the simulation is enabled or not.
References IsSimulationEnable(), and UE_API.
Referenced by IsSimulationEnable().
OnAttachmentChanged()
virtual HAIRSTRANDSCORE_API void UGroomComponent::OnAttachmentChanged () override private virtual
References OnAttachmentChanged(), and UE_API.
Referenced by OnAttachmentChanged().
OnComponentDestroyed()
virtual HAIRSTRANDSCORE_API void UGroomComponent::OnComponentDestroyed (bool bDestroyingHierarchy) override private virtual
References OnComponentDestroyed(), and UE_API.
Referenced by OnComponentDestroyed().
OnRegister()
virtual HAIRSTRANDSCORE_API void UGroomComponent::OnRegister () override private virtual
References OnRegister(), and UE_API.
Referenced by OnRegister().
OnUnregister()
virtual HAIRSTRANDSCORE_API void UGroomComponent::OnUnregister () override private virtual
References OnUnregister(), and UE_API.
Referenced by OnUnregister().
PostCompilation()
HAIRSTRANDSCORE_API void UGroomComponent::PostCompilation () private
References UE_API.
PostEditChangeProperty()
virtual HAIRSTRANDSCORE_API void UGroomComponent::PostEditChangeProperty (FPropertyChangedEvent & PropertyChangedEvent) override private virtual
References UE_API.
PostLoad()
virtual HAIRSTRANDSCORE_API void UGroomComponent::PostLoad () override private virtual
References PostLoad(), and UE_API.
Referenced by PostLoad().
PreEditChange()
virtual HAIRSTRANDSCORE_API void UGroomComponent::PreEditChange (FProperty * PropertyAboutToChange) override private virtual
References UE_API.
PreFeatureLevelChange()
virtual HAIRSTRANDSCORE_API void UGroomComponent::PreFeatureLevelChange (ERHIFeatureLevel::Type PendingFeatureLevel) override private virtual
References UE_API.
ReleaseHairSimulation() [1/2]
HAIRSTRANDSCORE_API void UGroomComponent::ReleaseHairSimulation () private
Release Niagara components.
References ReleaseHairSimulation(), and UE_API.
Referenced by ReleaseHairSimulation(), and ReleaseHairSimulation().
ReleaseHairSimulation() [2/2]
HAIRSTRANDSCORE_API void UGroomComponent::ReleaseHairSimulation (const int32 GroupIndex) private
References ReleaseHairSimulation(), and UE_API.
ReleaseResources()
void UGroomComponent::ReleaseResources () private
RequiresGameThreadEndOfFrameRecreate()
virtual HAIRSTRANDSCORE_API bool UGroomComponent::RequiresGameThreadEndOfFrameRecreate () const override private virtual
References RequiresGameThreadEndOfFrameRecreate(), and UE_API.
Referenced by RequiresGameThreadEndOfFrameRecreate().
ResetAnimationTime()
HAIRSTRANDSCORE_API void UGroomComponent::ResetAnimationTime () private
References ResetAnimationTime(), and UE_API.
Referenced by ResetAnimationTime().
SendRenderDynamicData_Concurrent()
virtual HAIRSTRANDSCORE_API void UGroomComponent::SendRenderDynamicData_Concurrent () override private virtual
References SendRenderDynamicData_Concurrent(), and UE_API.
Referenced by SendRenderDynamicData_Concurrent().
SetBinding()
HAIRSTRANDSCORE_API void UGroomComponent::SetBinding (UGroomBindingAsset * InBinding) private
References SetBinding(), UE_API, and UGroomBindingAsset.
Referenced by SetBinding().
SetForcedLOD()
HAIRSTRANDSCORE_API void UGroomComponent::SetForcedLOD (int32 LODIndex) private
References UE_API.
SetForceRenderedLOD()
virtual HAIRSTRANDSCORE_API void UGroomComponent::SetForceRenderedLOD (int32 LODIndex) override private virtual
Sets the LOD to use for rendering, as a 0-based index.
If LODIndex is negative, the rendering LOD selection behavior will be returned to normal.
This call has no effect on streaming behavior. If a LOD is requested that is not streamed in, the best available LOD will be used instead. If the requested LOD is streamed in later, it will be used without the caller needing to call this function again.
Implements ILODSyncInterface.
References UE_API.
SetForceStreamedLOD()
virtual HAIRSTRANDSCORE_API void UGroomComponent::SetForceStreamedLOD (int32 LODIndex) override private virtual
Sets the LOD to force to stream in, as a 0-based index.
If LODIndex is non-negative and LOD streaming is enabled, this call requests that the streaming system stream in LODs up to and including the specified LOD index, ignoring any other heuristics such as size on screen.
Note that there is no guarantee of how long it will take the requested LOD to stream in, and if memory is low it may never stream in.
If LODIndex is negative, the streaming behavior will be returned to normal.
This call has no effect while LOD streaming is disabled.
Implements ILODSyncInterface.
References UE_API.
SetGroomAsset()
HAIRSTRANDSCORE_API void UGroomComponent::SetGroomAsset (UGroomAsset * Asset, UGroomBindingAsset * InBinding, const bool bUpdateSimulation = true) private
References Asset, SetGroomAsset(), UE_API, and UGroomBindingAsset.
Referenced by SetGroomAsset(), and UFUNCTION().
SetGroomSolver()
void UGroomComponent::SetGroomSolver (UMeshComponent * InGroomSolver) inline private
Set the groom solver onto the component.
Definition at line 312 of file GroomComponent.h.
References GroomSolver.
SetHairRootScale()
HAIRSTRANDSCORE_API void UGroomComponent::SetHairRootScale (float Scale) private
References Scale, SetHairRootScale(), and UE_API.
Referenced by SetHairRootScale().
SetHairWidth()
HAIRSTRANDSCORE_API void UGroomComponent::SetHairWidth (float HairWidth) private
References SetHairWidth(), and UE_API.
Referenced by SetHairWidth().
SetManualTick()
HAIRSTRANDSCORE_API void UGroomComponent::SetManualTick (bool bInManualTick) private
References SetManualTick(), and UE_API.
Referenced by SetManualTick().
SetScatterSceneLighting()
HAIRSTRANDSCORE_API void UGroomComponent::SetScatterSceneLighting (bool Enable) private
References Enable, SetScatterSceneLighting(), and UE_API.
Referenced by SetScatterSceneLighting().
SetStableRasterization()
HAIRSTRANDSCORE_API void UGroomComponent::SetStableRasterization (bool bEnable) private
References SetStableRasterization(), and UE_API.
Referenced by SetStableRasterization().
SetUseCards()
HAIRSTRANDSCORE_API void UGroomComponent::SetUseCards (bool InbUseCards) private
References SetUseCards(), and UE_API.
Referenced by SetUseCards().
SetValidation()
void UGroomComponent::SetValidation (bool bEnable) inline private
Definition at line 248 of file GroomComponent.h.
References bValidationEnable, and SetValidation().
Referenced by SetValidation().
SwitchSimulationLOD()
HAIRSTRANDSCORE_API void UGroomComponent::SwitchSimulationLOD (const int32 PreviousLOD, const int32 CurrentLOD, const EHairLODSelectionType InLODSelectionType) private
Enable/Disable hair simulation while transitioning from one LOD to another one.
References SwitchSimulationLOD(), and UE_API.
Referenced by SwitchSimulationLOD().
TickAtThisTime()
HAIRSTRANDSCORE_API void UGroomComponent::TickAtThisTime (const float Time, bool bInIsRunning, bool bInBackwards, bool bInIsLooping) private
References TickAtThisTime(), Time, and UE_API.
Referenced by TickAtThisTime().
TickComponent()
virtual HAIRSTRANDSCORE_API void UGroomComponent::TickComponent (float DeltaTime, enum ELevelTick TickType, FActorComponentTickFunction * ThisTickFunction) override private virtual
References DeltaTime, TickComponent(), and UE_API.
Referenced by TickComponent().
UFUNCTION() [1/13]
UGroomComponent::UFUNCTION () private
References Category, UE_API, and UFUNCTION().
UFUNCTION() [2/13]
UGroomComponent::UFUNCTION () private
References Category, UE_API, and UFUNCTION().
UFUNCTION() [3/13]
UGroomComponent::UFUNCTION () private
References Category, UE_API, and UFUNCTION().
UFUNCTION() [4/13]
UGroomComponent::UFUNCTION () private
References Category, UE_API, and UFUNCTION().
UFUNCTION() [5/13]
UGroomComponent::UFUNCTION () private
References Category, UE_API, UFUNCTION(), and UGroomBindingAsset.
UFUNCTION() [6/13]
UGroomComponent::UFUNCTION () private
References Category, UE_API, and UFUNCTION().
UFUNCTION() [7/13]
UGroomComponent::UFUNCTION () private
References Asset, Category, SetGroomAsset(), and UE_API.
Referenced by UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), UFUNCTION(), and UFUNCTION().
UFUNCTION() [8/13]
UGroomComponent::UFUNCTION () private
References Category, and UE_API.
UFUNCTION() [9/13]
UGroomComponent::UFUNCTION () private
References Category, Scale, and UE_API.
UFUNCTION() [10/13]
UGroomComponent::UFUNCTION () private
References Category, UE_API, and UFUNCTION().
UFUNCTION() [11/13]
UGroomComponent::UFUNCTION () private
References Category, UE_API, and UFUNCTION().
UFUNCTION() [12/13]
UGroomComponent::UFUNCTION () private
References Category, UE_API, and UFUNCTION().
UFUNCTION() [13/13]
UGroomComponent::UFUNCTION () const inline private
Definition at line 228 of file GroomComponent.h.
References Category, and UFUNCTION().
UpdateGroomCache()
void UGroomComponent::UpdateGroomCache (float Time) private
References Time.
UpdateHairGroupsDesc()
HAIRSTRANDSCORE_API void UGroomComponent::UpdateHairGroupsDesc () private
Update Group Description.
References UE_API, and UpdateHairGroupsDesc().
Referenced by UpdateHairGroupsDesc().
UpdateHairGroupsDescAndInvalidateRenderState()
HAIRSTRANDSCORE_API void UGroomComponent::UpdateHairGroupsDescAndInvalidateRenderState (bool bInvalidate = true) private
References UE_API, and UpdateHairGroupsDescAndInvalidateRenderState().
Referenced by UpdateHairGroupsDescAndInvalidateRenderState().
UpdateHairSimulation()
HAIRSTRANDSCORE_API void UGroomComponent::UpdateHairSimulation () private
Update Niagara components.
References UE_API, and UpdateHairSimulation().
Referenced by UpdateHairSimulation().
UpdateSimulatedGroups()
HAIRSTRANDSCORE_API void UGroomComponent::UpdateSimulatedGroups () private
Update simulated groups.
References UE_API, and UpdateSimulatedGroups().
Referenced by UpdateSimulatedGroups().
UPROPERTY() [1/22]
UGroomComponent::UPROPERTY () private
References Category.
UPROPERTY() [2/22]
UGroomComponent::UPROPERTY () private
References Category.
UPROPERTY() [3/22]
UGroomComponent::UPROPERTY () private
References Category.
UPROPERTY() [4/22]
UGroomComponent::UPROPERTY () private
Force the groom to use cards/meshes geometry instead of strands.
References Category, and UPROPERTY().
UPROPERTY() [5/22]
UGroomComponent::UPROPERTY () private
Groom's simulation settings.
References Category, and UPROPERTY().
UPROPERTY() [6/22]
UGroomComponent::UPROPERTY () private
References Category, and transient.
UPROPERTY() [7/22]
UGroomComponent::UPROPERTY () private
Optional socket name, where the groom component should be attached at, when parented with a skeletal mesh.
References Category, and UPROPERTY().
UPROPERTY() [8/22]
UGroomComponent::UPROPERTY () private
Groom's groups info.
References Category.
UPROPERTY() [9/22]
UGroomComponent::UPROPERTY () private
Niagara components that will be attached to the system.
References Transient, and UPROPERTY().
UPROPERTY() [10/22]
UGroomComponent::UPROPERTY () private
Optional binding asset for binding a groom onto a skeletal mesh.
If the binding asset is not provided the projection is done at runtime, which implies a large GPU cost at startup time.
References Category, UGroomBindingAsset, and UPROPERTY().
UPROPERTY() [11/22]
UGroomComponent::UPROPERTY () private
References UPROPERTY().
UPROPERTY() [12/22]
UGroomComponent::UPROPERTY () private
References UPROPERTY().
UPROPERTY() [13/22]
UGroomComponent::UPROPERTY () private
Physics asset to be used for hair simulation.
References Category, and UPROPERTY().
UPROPERTY() [14/22]
UGroomComponent::UPROPERTY () private
References UPROPERTY().
UPROPERTY() [15/22]
GENERATED_UCLASS_BODY() public UGroomComponent::UPROPERTY () private
Groom asset .
References Category.
Referenced by UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), and UPROPERTY().
UPROPERTY() [16/22]
UGroomComponent::UPROPERTY () private
References UPROPERTY().
UPROPERTY() [17/22]
UGroomComponent::UPROPERTY () private
References UPROPERTY().
UPROPERTY() [18/22]
UGroomComponent::UPROPERTY () private
References UPROPERTY().
UPROPERTY() [19/22]
UGroomComponent::UPROPERTY () private
References UPROPERTY().
UPROPERTY() [20/22]
UGroomComponent::UPROPERTY () private
Object containing state for the bound MeshDeformer.
References Category, Transient, and UPROPERTY().
UPROPERTY() [21/22]
UGroomComponent::UPROPERTY () private
If set the MeshDeformer will be applied on groom instance for deformation.
References Category, MeshDeformer, Meta, ToolTip, and UPROPERTY().
UPROPERTY() [22/22]
UGroomComponent::UPROPERTY () private
Object containing instance settings for the bound MeshDeformer.
References Category, meta, and UPROPERTY().
ValidateMaterials()
HAIRSTRANDSCORE_API void UGroomComponent::ValidateMaterials (bool bMapCheck) const private
References UE_API.
Friends And Related Symbol Documentation
FGroomComponentRecreateRenderStateContext
friend class FGroomComponentRecreateRenderStateContext friend
Definition at line 373 of file GroomComponent.h.
References FGroomComponentRecreateRenderStateContext.
Referenced by FGroomComponentRecreateRenderStateContext.
FHairCardsSceneProxy
friend class FHairCardsSceneProxy friend
Definition at line 375 of file GroomComponent.h.
References FHairCardsSceneProxy.
Referenced by FHairCardsSceneProxy.
FHairStrandsSceneProxy
friend class FHairStrandsSceneProxy friend
Definition at line 374 of file GroomComponent.h.
References FHairStrandsSceneProxy.
Referenced by FHairStrandsSceneProxy.
UGroomBindingAsset
friend class UGroomBindingAsset friend
Definition at line 372 of file GroomComponent.h.
References UGroomBindingAsset.
Referenced by SetBinding(), SetGroomAsset(), UFUNCTION(), UGroomBindingAsset, and UPROPERTY().
Field Documentation
bInitSimulation
bool UGroomComponent::bInitSimulation private
Boolean to check when the simulation should be initialized.
Definition at line 100 of file GroomComponent.h.
bIsGroomAssetCallbackRegistered
bool UGroomComponent::bIsGroomAssetCallbackRegistered private
Definition at line 359 of file GroomComponent.h.
bIsGroomBindingAssetCallbackRegistered
bool UGroomComponent::bIsGroomBindingAssetCallbackRegistered private
Definition at line 360 of file GroomComponent.h.
bPreviewMode
bool UGroomComponent::bPreviewMode = false private
Definition at line 362 of file GroomComponent.h.
Referenced by GetNumMaterials().
bResetSimulation
bool UGroomComponent::bResetSimulation private
Boolean to check when the simulation should be reset.
Definition at line 97 of file GroomComponent.h.
bValidationEnable
bool UGroomComponent::bValidationEnable = true private
Definition at line 361 of file GroomComponent.h.
Referenced by SetValidation().
CollisionComponents
TArray<TWeakObjectPtr<class USkeletalMeshComponent> > UGroomComponent::CollisionComponents private
List of collision components to be used.
Definition at line 58 of file GroomComponent.h.
DeformedMeshComponent
class UMeshComponent* UGroomComponent::DeformedMeshComponent private
Definition at line 358 of file GroomComponent.h.
GroomCacheBuffers
TSharedPtr<class IGroomCacheBuffers, ESPMode::ThreadSafe> UGroomComponent::GroomCacheBuffers private
Definition at line 340 of file GroomComponent.h.
GroomSolver
TSoftObjectPtr<UMeshComponent> UGroomComponent::GroomSolver = nullptr private
Groom solver pointer.
Definition at line 378 of file GroomComponent.h.
Referenced by GetGroomSolver(), and SetGroomSolver().
HairGroupInstances
TArray<TRefCountPtr<FHairGroupInstance> > UGroomComponent::HairGroupInstances private
Definition at line 343 of file GroomComponent.h.
Referenced by ContainsGroupInstance(), GetGroupCount(), GetGroupInstance(), and GetGroupInstance().
InitializedResources
void* UGroomComponent::InitializedResources private
Definition at line 356 of file GroomComponent.h.
LODForcedIndex
float UGroomComponent::LODForcedIndex = -1.f private
Definition at line 367 of file GroomComponent.h.
LODPredictedIndex
float UGroomComponent::LODPredictedIndex = -1.f private
Definition at line 366 of file GroomComponent.h.
LODSelectionType
EHairLODSelectionType UGroomComponent::LODSelectionType = EHairLODSelectionType::Immediate private
Definition at line 365 of file GroomComponent.h.
PrevBoneMatrix
FMatrix UGroomComponent::PrevBoneMatrix private
Previous bone matrix to compare the difference and decide to reset or not the simulation.
Definition at line 103 of file GroomComponent.h.
RegisteredMeshComponent
class UMeshComponent* UGroomComponent::RegisteredMeshComponent private
Definition at line 357 of file GroomComponent.h.
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/HairStrands/Source/HairStrandsCore/Public/GroomComponent.h