Unreal Engine 5.6 C++ API: TUnion< TypeA, TypeB, TypeC, TypeD, TypeE, TypeF > Class Template Reference
TUnion< TypeA, TypeB, TypeC, TypeD, TypeE, TypeF > Class Template Reference
Represents a type which is the union of several other types; i.e.
#include "Union.h"
Public Member Functions
TUnion ()
Default constructor.
TUnion (const TUnion &Other)
Copy constructor.
TUnion (typename TCallTraits< TypeA >::ParamType InValue, TDisambiguater< 0 > Disambiguater=TDisambiguater< 0 >())
Initialization constructor.
TUnion (typename TCallTraits< TypeB >::ParamType InValue, TDisambiguater< 1 > Disambiguater=TDisambiguater< 1 >())
Initialization constructor.
TUnion (typename TCallTraits< TypeC >::ParamType InValue, TDisambiguater< 2 > Disambiguater=TDisambiguater< 2 >())
Initialization constructor.
TUnion (typename TCallTraits< TypeD >::ParamType InValue, TDisambiguater< 3 > Disambiguater=TDisambiguater< 3 >())
Initialization constructor.
TUnion (typename TCallTraits< TypeE >::ParamType InValue, TDisambiguater< 4 > Disambiguater=TDisambiguater< 4 >())
Initialization constructor.
TUnion (typename TCallTraits< TypeF >::ParamType InValue, TDisambiguater< 5 > Disambiguater=TDisambiguater< 5 >())
Initialization constructor.
~TUnion ()
Destructor.
uint8 GetCurrentSubtypeIndex () const
template<typename Subtype>
Subtype & GetSubtype ()
template<typename Subtype>
const Subtype & GetSubtype () const
template<typename Subtype>
bool HasSubtype () const
TUnion & operator= (const TUnion &Other)
bool operator== (const TUnion &Other) const
Equality comparison.
void Reset ()
Sets the union's value to NULL.
template<typename Subtype>
void ResetSubtype ()
If the union's current value is of the given subtype, sets the union's value to a NULL value.
void Serialize (FArchive &Ar)
template<typename Subtype>
Subtype * SetSubtype ()
Replaces the value of the union with a value of the given subtype.
template<typename Subtype>
Subtype * SetSubtype (typename TCallTraits< Subtype >::ParamType NewValue)
Replaces the value of the union with a value of the given subtype.
Private Member Functions
template<typename Subtype>
Subtype & InitSubtype ()
Sets the union's value to a default value of the given subtype.
Static Private Member Functions
static void FatalErrorUndefinedSubtype ()
template<typename Subtype, typename PointerType>
static void GetSubtypeIndexAndReference (const TUnion &Union, uint8 &OutIndex, PointerType &OutValuePointer)
Determines the index and reference to the potential value for the given union subtype.
Private Attributes
uint8 CurrentSubtypeIndex = (uint8)-1
The index of the subtype that the union's current value is of.
union {
TTypeCompatibleBytes< TypeA > A
TTypeCompatibleBytes< TypeB > B
TTypeCompatibleBytes< TypeC > C
TTypeCompatibleBytes< TypeD > D
TTypeCompatibleBytes< TypeE > E
TTypeCompatibleBytes< TypeF > F
} Values
The potential values for each subtype of the union.
Friends
uint32 GetTypeHash (const TUnion &Union)
Hash function.
Detailed Description
template<typename TypeA, typename TypeB = FNull, typename TypeC = FNull, typename TypeD = FNull, typename TypeE = FNull, typename TypeF = FNull>
class TUnion< TypeA, TypeB, TypeC, TypeD, TypeE, TypeF >
Represents a type which is the union of several other types; i.e.
it can have a value whose type is of any the union's subtypes. This differs from C union types by being type-safe, and supporting non-trivial data types as subtypes. Since a value for the union must be of a single subtype, the union stores potential values of different subtypes in overlapped memory, and keeps track of which one is currently valid.
TUnion should be considered deprecated and TVariant should be used instead for new code.
Definition at line 63 of file Union.h.
Constructor & Destructor Documentation
TUnion() [1/8]
template<typename TypeA, typename TypeB = FNull, typename TypeC = FNull, typename TypeD = FNull, typename TypeE = FNull, typename TypeF = FNull> TUnion< TypeA, TypeB, TypeC, TypeD, TypeE, TypeF >::TUnion () inline
Default constructor.
Definition at line 68 of file Union.h.
Referenced by TUnion(), GetSubtypeIndexAndReference(), GetTypeHash, operator=(), and operator==().
TUnion() [2/8]
template<typename TypeA, typename TypeB = FNull, typename TypeC = FNull, typename TypeD = FNull, typename TypeE = FNull, typename TypeF = FNull> TUnion< TypeA, TypeB, TypeC, TypeD, TypeE, TypeF >::TUnion (typename TCallTraits< TypeA >::ParamType InValue, TDisambiguater< 0 > Disambiguater = TDisambiguater<0>()) inline explicit
Initialization constructor.
Definition at line 72 of file Union.h.
References SetSubtype().
TUnion() [3/8]
template<typename TypeA, typename TypeB = FNull, typename TypeC = FNull, typename TypeD = FNull, typename TypeE = FNull, typename TypeF = FNull> TUnion< TypeA, TypeB, TypeC, TypeD, TypeE, TypeF >::TUnion (typename TCallTraits< TypeB >::ParamType InValue, TDisambiguater< 1 > Disambiguater = TDisambiguater<1>()) inline explicit
Initialization constructor.
Definition at line 78 of file Union.h.
References SetSubtype().
TUnion() [4/8]
template<typename TypeA, typename TypeB = FNull, typename TypeC = FNull, typename TypeD = FNull, typename TypeE = FNull, typename TypeF = FNull> TUnion< TypeA, TypeB, TypeC, TypeD, TypeE, TypeF >::TUnion (typename TCallTraits< TypeC >::ParamType InValue, TDisambiguater< 2 > Disambiguater = TDisambiguater<2>()) inline explicit
Initialization constructor.
Definition at line 84 of file Union.h.
References SetSubtype().
TUnion() [5/8]
template<typename TypeA, typename TypeB = FNull, typename TypeC = FNull, typename TypeD = FNull, typename TypeE = FNull, typename TypeF = FNull> TUnion< TypeA, TypeB, TypeC, TypeD, TypeE, TypeF >::TUnion (typename TCallTraits< TypeD >::ParamType InValue, TDisambiguater< 3 > Disambiguater = TDisambiguater<3>()) inline explicit
Initialization constructor.
Definition at line 90 of file Union.h.
References SetSubtype().
TUnion() [6/8]
template<typename TypeA, typename TypeB = FNull, typename TypeC = FNull, typename TypeD = FNull, typename TypeE = FNull, typename TypeF = FNull> TUnion< TypeA, TypeB, TypeC, TypeD, TypeE, TypeF >::TUnion (typename TCallTraits< TypeE >::ParamType InValue, TDisambiguater< 4 > Disambiguater = TDisambiguater<4>()) inline explicit
Initialization constructor.
Definition at line 96 of file Union.h.
References SetSubtype().
TUnion() [7/8]
template<typename TypeA, typename TypeB = FNull, typename TypeC = FNull, typename TypeD = FNull, typename TypeE = FNull, typename TypeF = FNull> TUnion< TypeA, TypeB, TypeC, TypeD, TypeE, TypeF >::TUnion (typename TCallTraits< TypeF >::ParamType InValue, TDisambiguater< 5 > Disambiguater = TDisambiguater<5>()) inline explicit
Initialization constructor.
Definition at line 102 of file Union.h.
References SetSubtype().
TUnion() [8/8]
template<typename TypeA, typename TypeB = FNull, typename TypeC = FNull, typename TypeD = FNull, typename TypeE = FNull, typename TypeF = FNull> TUnion< TypeA, TypeB, TypeC, TypeD, TypeE, TypeF >::TUnion (const TUnion< TypeA, TypeB, TypeC, TypeD, TypeE, TypeF > & Other) inline
Copy constructor.
Definition at line 108 of file Union.h.
References TUnion(), and Other.
~TUnion()
template<typename TypeA, typename TypeB = FNull, typename TypeC = FNull, typename TypeD = FNull, typename TypeE = FNull, typename TypeF = FNull> TUnion< TypeA, TypeB, TypeC, TypeD, TypeE, TypeF >::~TUnion () inline
Destructor.
Definition at line 114 of file Union.h.
References Reset().
Member Function Documentation
FatalErrorUndefinedSubtype()
template<typename TypeA, typename TypeB = FNull, typename TypeC = FNull, typename TypeD = FNull, typename TypeE = FNull, typename TypeF = FNull> void TUnion< TypeA, TypeB, TypeC, TypeD, TypeE, TypeF >::FatalErrorUndefinedSubtype () inline static private
Definition at line 396 of file Union.h.
References Fatal, TEXT, and UE_LOG.
Referenced by GetTypeHash, operator=(), operator==(), and Serialize().
GetCurrentSubtypeIndex()
template<typename TypeA, typename TypeB = FNull, typename TypeC = FNull, typename TypeD = FNull, typename TypeE = FNull, typename TypeF = FNull> uint8 TUnion< TypeA, TypeB, TypeC, TypeD, TypeE, TypeF >::GetCurrentSubtypeIndex () const inline
Returns
The index corresponding to the type currently stored in this union; useful for writing switches and indexing into tables.
Definition at line 214 of file Union.h.
References CurrentSubtypeIndex.
GetSubtype() [1/2]
template<typename TypeA, typename TypeB = FNull, typename TypeC = FNull, typename TypeD = FNull, typename TypeE = FNull, typename TypeF = FNull> template<typename Subtype> Subtype & TUnion< TypeA, TypeB, TypeC, TypeD, TypeE, TypeF >::GetSubtype () inline
Returns
A reference to the union's value of the given subtype. May only be called if the union's HasSubtype()==true for the given subtype.
Definition at line 168 of file Union.h.
References check, CurrentSubtypeIndex, and GetSubtypeIndexAndReference().
GetSubtype() [2/2]
template<typename TypeA, typename TypeB = FNull, typename TypeC = FNull, typename TypeD = FNull, typename TypeE = FNull, typename TypeF = FNull> template<typename Subtype> const Subtype & TUnion< TypeA, TypeB, TypeC, TypeD, TypeE, TypeF >::GetSubtype () const inline
Returns
A reference to the union's value of the given subtype. May only be called if the union's HasSubtype()==true for the given subtype.
Definition at line 153 of file Union.h.
References check, CurrentSubtypeIndex, and GetSubtypeIndexAndReference().
Referenced by InitSubtype(), and operator==().
GetSubtypeIndexAndReference()
template<typename TypeA, typename TypeB = FNull, typename TypeC = FNull, typename TypeD = FNull, typename TypeE = FNull, typename TypeF = FNull> template<typename Subtype, typename PointerType> void TUnion< TypeA, TypeB, TypeC, TypeD, TypeE, TypeF >::GetSubtypeIndexAndReference (const TUnion< TypeA, TypeB, TypeC, TypeD, TypeE, TypeF > & Union, uint8 & OutIndex, PointerType & OutValuePointer) inline static private
Determines the index and reference to the potential value for the given union subtype.
Definition at line 352 of file Union.h.
References TUnion().
Referenced by GetSubtype(), GetSubtype(), HasSubtype(), ResetSubtype(), SetSubtype(), and SetSubtype().
HasSubtype()
template<typename TypeA, typename TypeB = FNull, typename TypeC = FNull, typename TypeD = FNull, typename TypeE = FNull, typename TypeF = FNull> template<typename Subtype> bool TUnion< TypeA, TypeB, TypeC, TypeD, TypeE, TypeF >::HasSubtype () const inline
Returns
True if the union's value is of the given subtype.
Definition at line 122 of file Union.h.
References CurrentSubtypeIndex, and GetSubtypeIndexAndReference().
InitSubtype()
template<typename TypeA, typename TypeB = FNull, typename TypeC = FNull, typename TypeD = FNull, typename TypeE = FNull, typename TypeF = FNull> template<typename Subtype> Subtype & TUnion< TypeA, TypeB, TypeC, TypeD, TypeE, TypeF >::InitSubtype () inline private
Sets the union's value to a default value of the given subtype.
Definition at line 344 of file Union.h.
References GetSubtype().
operator=()
template<typename TypeA, typename TypeB = FNull, typename TypeC = FNull, typename TypeD = FNull, typename TypeE = FNull, typename TypeF = FNull> TUnion & TUnion< TypeA, TypeB, TypeC, TypeD, TypeE, TypeF >::operator= (const TUnion< TypeA, TypeB, TypeC, TypeD, TypeE, TypeF > & Other) inline
Definition at line 252 of file Union.h.
References TUnion(), FatalErrorUndefinedSubtype(), Other, and SetSubtype().
operator==()
template<typename TypeA, typename TypeB = FNull, typename TypeC = FNull, typename TypeD = FNull, typename TypeE = FNull, typename TypeF = FNull> bool TUnion< TypeA, TypeB, TypeC, TypeD, TypeE, TypeF >::operator== (const TUnion< TypeA, TypeB, TypeC, TypeD, TypeE, TypeF > & Other) const inline
Equality comparison.
Definition at line 271 of file Union.h.
References TUnion(), CurrentSubtypeIndex, FatalErrorUndefinedSubtype(), GetSubtype(), and Other.
Reset()
template<typename TypeA, typename TypeB = FNull, typename TypeC = FNull, typename TypeD = FNull, typename TypeE = FNull, typename TypeF = FNull> void TUnion< TypeA, TypeB, TypeC, TypeD, TypeE, TypeF >::Reset () inline
Sets the union's value to NULL.
Definition at line 220 of file Union.h.
References CurrentSubtypeIndex, and ResetSubtype().
Referenced by ~TUnion(), Serialize(), SetSubtype(), and SetSubtype().
ResetSubtype()
template<typename TypeA, typename TypeB = FNull, typename TypeC = FNull, typename TypeD = FNull, typename TypeE = FNull, typename TypeF = FNull> template<typename Subtype> void TUnion< TypeA, TypeB, TypeC, TypeD, TypeE, TypeF >::ResetSubtype () inline
If the union's current value is of the given subtype, sets the union's value to a NULL value.
Definition at line 134 of file Union.h.
References CurrentSubtypeIndex, and GetSubtypeIndexAndReference().
Referenced by Reset().
Serialize()
template<typename TypeA, typename TypeB = FNull, typename TypeC = FNull, typename TypeD = FNull, typename TypeE = FNull, typename TypeF = FNull> void TUnion< TypeA, TypeB, TypeC, TypeD, TypeE, TypeF >::Serialize (FArchive & Ar) inline
Definition at line 290 of file Union.h.
References Ar, CurrentSubtypeIndex, FatalErrorUndefinedSubtype(), and Reset().
SetSubtype() [1/2]
template<typename TypeA, typename TypeB = FNull, typename TypeC = FNull, typename TypeD = FNull, typename TypeE = FNull, typename TypeF = FNull> template<typename Subtype> Subtype * TUnion< TypeA, TypeB, TypeC, TypeD, TypeE, TypeF >::SetSubtype () inline
Replaces the value of the union with a value of the given subtype.
Definition at line 183 of file Union.h.
References CurrentSubtypeIndex, GetSubtypeIndexAndReference(), and Reset().
Referenced by TUnion(), TUnion(), TUnion(), TUnion(), TUnion(), TUnion(), and operator=().
SetSubtype() [2/2]
template<typename TypeA, typename TypeB = FNull, typename TypeC = FNull, typename TypeD = FNull, typename TypeE = FNull, typename TypeF = FNull> template<typename Subtype> Subtype * TUnion< TypeA, TypeB, TypeC, TypeD, TypeE, TypeF >::SetSubtype (typename TCallTraits< Subtype >::ParamType NewValue) inline
Replaces the value of the union with a value of the given subtype.
Definition at line 199 of file Union.h.
References CurrentSubtypeIndex, GetSubtypeIndexAndReference(), and Reset().
Friends And Related Symbol Documentation
GetTypeHash
template<typename TypeA, typename TypeB = FNull, typename TypeC = FNull, typename TypeD = FNull, typename TypeE = FNull, typename TypeF = FNull> uint32 GetTypeHash (const TUnion< TypeA, TypeB, TypeC, TypeD, TypeE, TypeF > & Union) friend
Hash function.
Definition at line 234 of file Union.h.
References TUnion(), FatalErrorUndefinedSubtype(), and GetTypeHash.
Referenced by GetTypeHash.
Field Documentation
A
template<typename TypeA, typename TypeB = FNull, typename TypeC = FNull, typename TypeD = FNull, typename TypeE = FNull, typename TypeF = FNull> TTypeCompatibleBytes<TypeA> TUnion< TypeA, TypeB, TypeC, TypeD, TypeE, TypeF >::A
Definition at line 331 of file Union.h.
B
template<typename TypeA, typename TypeB = FNull, typename TypeC = FNull, typename TypeD = FNull, typename TypeE = FNull, typename TypeF = FNull> TTypeCompatibleBytes<TypeB> TUnion< TypeA, TypeB, TypeC, TypeD, TypeE, TypeF >::B
Definition at line 332 of file Union.h.
C
template<typename TypeA, typename TypeB = FNull, typename TypeC = FNull, typename TypeD = FNull, typename TypeE = FNull, typename TypeF = FNull> TTypeCompatibleBytes<TypeC> TUnion< TypeA, TypeB, TypeC, TypeD, TypeE, TypeF >::C
Definition at line 333 of file Union.h.
CurrentSubtypeIndex
template<typename TypeA, typename TypeB = FNull, typename TypeC = FNull, typename TypeD = FNull, typename TypeE = FNull, typename TypeF = FNull> uint8 TUnion< TypeA, TypeB, TypeC, TypeD, TypeE, TypeF >::CurrentSubtypeIndex = (uint8)-1 private
The index of the subtype that the union's current value is of.
Definition at line 340 of file Union.h.
Referenced by GetCurrentSubtypeIndex(), GetSubtype(), GetSubtype(), HasSubtype(), operator==(), Reset(), ResetSubtype(), Serialize(), SetSubtype(), and SetSubtype().
D
template<typename TypeA, typename TypeB = FNull, typename TypeC = FNull, typename TypeD = FNull, typename TypeE = FNull, typename TypeF = FNull> TTypeCompatibleBytes<TypeD> TUnion< TypeA, TypeB, TypeC, TypeD, TypeE, TypeF >::D
Definition at line 334 of file Union.h.
E
template<typename TypeA, typename TypeB = FNull, typename TypeC = FNull, typename TypeD = FNull, typename TypeE = FNull, typename TypeF = FNull> TTypeCompatibleBytes<TypeE> TUnion< TypeA, TypeB, TypeC, TypeD, TypeE, TypeF >::E
Definition at line 335 of file Union.h.
F
template<typename TypeA, typename TypeB = FNull, typename TypeC = FNull, typename TypeD = FNull, typename TypeE = FNull, typename TypeF = FNull> TTypeCompatibleBytes<TypeF> TUnion< TypeA, TypeB, TypeC, TypeD, TypeE, TypeF >::F
Definition at line 336 of file Union.h.
[union]
union { ... } TUnion< TypeA, TypeB, TypeC, TypeD, TypeE, TypeF >::Values
The potential values for each subtype of the union.
The documentation for this class was generated from the following file:
Runtime/Core/Public/Containers/Union.h