Unreal Engine 5.6 C++ API: FFieldClass Class Reference
FFieldClass Class Reference
Object representing a type of an FField struct.
#include "Field.h"
Public Member Functions
FFieldClass (const TCHAR *InCPPName, uint64 InId, uint64 InCastFlags, FFieldClass *InSuperClass, FField *(*ConstructFnPtr)(const FFieldVariant &, const FName &, EObjectFlags))
~FFieldClass ()
FField * Construct (const FFieldVariant &InOwner, const FName &InName, EObjectFlags InFlags=RF_NoFlags) const
uint64 GetCastFlags () const
FField * GetDefaultObject ()
FString GetDescription () const
FText GetDisplayNameText () const
FName GetFName () const
uint64 GetId () const
FString GetName () const
int32 GetNextUniqueNameIndex ()
FFieldClass * GetSuperClass () const
bool HasAllCastFlags (const uint64 InCastFlags) const
bool HasAnyCastFlags (const uint64 InCastFlags) const
bool HasAnyClassFlags (EClassFlags FlagsToCheck) const
bool IsChildOf (const FFieldClass *InClass) const
Static Public Member Functions
static TArray< FFieldClass * > & GetAllFieldClasses ()
Gets the list of all field classes in existance.
static TMap< FName, FFieldClass * > & GetNameToFieldClassMap ()
Gets a mapping of all field class names to the actuall class objects.
Private Member Functions
FField * ConstructDefaultObject ()
Creates a default object instance of this class.
bool IsChildOf_Walk (const FFieldClass *InBaseClass) const
UE_NONCOPYABLE (FFieldClass)
Private Attributes
uint64 CastFlags
Cast flags used for casting to other classes.
EClassFlags ClassFlags
Class flags.
FField *(* ConstructFn)(const FFieldVariant &, const FName &, EObjectFlags)
Pointer to a function that can construct an instance of this class.
FField * DefaultObject
Default instance of this class.
uint64 Id
Unique Id of this field class (for casting)
FName Name
Name of this field class.
FFieldClass * SuperClass
Super of this class.
FThreadSafeCounter UnqiueNameIndexCounter
Counter for generating runtime unique names.
Friends
FArchive & operator<< (FArchive &Ar, FFieldClass &InField)
FArchive & operator<< (FArchive &Ar, FFieldClass *&InOutFieldClass)
Detailed Description
Object representing a type of an FField struct.
Mimics a subset of UObject reflection functions.
Definition at line 64 of file Field.h.
Constructor & Destructor Documentation
FFieldClass()
FFieldClass::FFieldClass (const TCHAR * InCPPName, uint64 InId, uint64 InCastFlags, FFieldClass * InSuperClass, FField *(* ConstructFnPtr)(const FFieldVariant &, const FName &, EObjectFlags)) explicit
References FFieldClass().
Referenced by FFieldClass(), GetSuperClass(), IsChildOf(), IsChildOf_Walk(), operator<<, operator<<, and UE_NONCOPYABLE().
~FFieldClass()
FFieldClass::~FFieldClass ()
Member Function Documentation
Construct()
FField * FFieldClass::Construct (const FFieldVariant & InOwner, const FName & InName, EObjectFlags InFlags = RF_NoFlags) const inline
Definition at line 129 of file Field.h.
References ConstructFn, InName, and RF_NoFlags.
ConstructDefaultObject()
FField * FFieldClass::ConstructDefaultObject () private
Creates a default object instance of this class.
Referenced by GetDefaultObject().
GetAllFieldClasses()
TArray< FFieldClass * > & FFieldClass::GetAllFieldClasses () static
Gets the list of all field classes in existance.
GetCastFlags()
uint64 FFieldClass::GetCastFlags () const inline
Definition at line 110 of file Field.h.
References CastFlags.
Referenced by FField::GetCastFlags().
GetDefaultObject()
FField * FFieldClass::GetDefaultObject () inline
Definition at line 139 of file Field.h.
References check, ConstructDefaultObject(), and DefaultObject.
GetDescription()
FString FFieldClass::GetDescription () const
GetDisplayNameText()
FText FFieldClass::GetDisplayNameText () const
GetFName()
FName FFieldClass::GetFName () const inline
Definition at line 102 of file Field.h.
References Name.
Referenced by FAnimatedPropertyKey::FromPropertyType().
GetId()
uint64 FFieldClass::GetId () const inline
Definition at line 106 of file Field.h.
References Id.
Referenced by IsChildOf().
GetName()
FString FFieldClass::GetName () const inline
Definition at line 98 of file Field.h.
References Name.
GetNameToFieldClassMap()
TMap< FName, FFieldClass * > & FFieldClass::GetNameToFieldClassMap () static
Gets a mapping of all field class names to the actuall class objects.
GetNextUniqueNameIndex()
int32 FFieldClass::GetNextUniqueNameIndex () inline
Definition at line 154 of file Field.h.
References UnqiueNameIndexCounter.
GetSuperClass()
FFieldClass * FFieldClass::GetSuperClass () const inline
Definition at line 134 of file Field.h.
References FFieldClass(), and SuperClass.
HasAllCastFlags()
bool FFieldClass::HasAllCastFlags (const uint64 InCastFlags) const inline
Definition at line 118 of file Field.h.
References CastFlags.
HasAnyCastFlags()
bool FFieldClass::HasAnyCastFlags (const uint64 InCastFlags) const inline
Definition at line 114 of file Field.h.
References CastFlags.
HasAnyClassFlags()
bool FFieldClass::HasAnyClassFlags (EClassFlags FlagsToCheck) const inline
Definition at line 149 of file Field.h.
References ClassFlags, and EnumHasAnyFlags().
IsChildOf()
bool FFieldClass::IsChildOf (const FFieldClass * InClass) const inline
Definition at line 122 of file Field.h.
References FFieldClass(), CastFlags, GetId(), and IsChildOf_Walk().
Referenced by UBlueprintMapLibrary::DECLARE_FUNCTION(), UBlueprintMapLibrary::DECLARE_FUNCTION(), UBlueprintSetLibrary::DECLARE_FUNCTION(), UKismetArrayLibrary::DECLARE_FUNCTION(), FField::IsA(), FField::IsA(), and FFrame::StepCompiledIn().
IsChildOf_Walk()
bool FFieldClass::IsChildOf_Walk (const FFieldClass * InBaseClass) const inline private
Definition at line 167 of file Field.h.
References FFieldClass().
Referenced by IsChildOf().
UE_NONCOPYABLE()
FFieldClass::UE_NONCOPYABLE (FFieldClass) private
References FFieldClass().
Friends And Related Symbol Documentation
operator<< [1/2]
FArchive & operator<< (FArchive & Ar, FFieldClass & InField) friend
Definition at line 159 of file Field.h.
References FFieldClass(), Ar, and check.
operator<< [2/2]
FArchive & operator<< (FArchive & Ar, FFieldClass *& InOutFieldClass) friend
References FFieldClass(), and Ar.
Field Documentation
CastFlags
uint64 FFieldClass::CastFlags private
Cast flags used for casting to other classes.
Definition at line 73 of file Field.h.
Referenced by GetCastFlags(), HasAllCastFlags(), HasAnyCastFlags(), and IsChildOf().
ClassFlags
EClassFlags FFieldClass::ClassFlags private
Class flags.
Definition at line 75 of file Field.h.
Referenced by HasAnyClassFlags().
ConstructFn
FField *(* FFieldClass::ConstructFn) (const FFieldVariant &, const FName &, EObjectFlags) private
Pointer to a function that can construct an instance of this class.
Definition at line 81 of file Field.h.
Referenced by Construct().
DefaultObject
FField* FFieldClass::DefaultObject private
Default instance of this class.
Definition at line 79 of file Field.h.
Referenced by GetDefaultObject().
Id
uint64 FFieldClass::Id private
Unique Id of this field class (for casting)
Definition at line 71 of file Field.h.
Referenced by GetId().
Name
FName FFieldClass::Name private
Name of this field class.
Definition at line 69 of file Field.h.
Referenced by GetFName(), and GetName().
SuperClass
FFieldClass* FFieldClass::SuperClass private
Super of this class.
Definition at line 77 of file Field.h.
Referenced by GetSuperClass().
UnqiueNameIndexCounter
FThreadSafeCounter FFieldClass::UnqiueNameIndexCounter private
Counter for generating runtime unique names.
Definition at line 83 of file Field.h.
Referenced by GetNextUniqueNameIndex().
The documentation for this class was generated from the following file:
Runtime/CoreUObject/Public/UObject/Field.h