Unreal Engine 5.6 C++ API: FToolCommandChangeSequence Class Reference
FToolCommandChangeSequence Class Reference
FCommandChangeSequence contains a list of FCommandChanges and associated target UObjects.
#include "ToolCommandChangeSequence.h"
Data Structures
struct FChangeElem
Public Member Functions
FToolCommandChangeSequence ()
void AppendChange (UObject *Target, TUniquePtr< FToolCommandChange > Change)
Add a change to the sequence.
virtual void Apply (UObject *Object) override
Apply sequence of changes in-order.
virtual void Revert (UObject *Object) override
Reverts sequence of changes in reverse-order.
virtual FString ToString () const override
Public Member Functions inherited from FCommandChange
virtual TUniquePtr< FChange > Execute (UObject *Object) final
Makes the change to the object, returning a new change that can be used to perfectly roll back this change.
virtual EChangeStyle GetChangeType () final
What style of change is this.
Public Member Functions inherited from FChange
virtual ~FChange ()
Virtual destructor.
virtual void AddReferencedObjects (FReferenceCollector &Collector)
Used by GC to collect referenced objects.
virtual bool HasExpired (UObject *Object) const
virtual void PrintToLog (FFeedbackContext &FeedbackContext, const int32 IndentLevel=0)
Prints this change to the log, including sub-changes if there are any.
Protected Attributes
TArray< TSharedPtr< FChangeElem > > Sequence
Additional Inherited Members
Public Types inherited from FChange
enum class EChangeStyle { InPlaceSwap , CommandPattern }
Protected Member Functions inherited from FChange
FChange ()
Protected default constructor.
Detailed Description
FCommandChangeSequence contains a list of FCommandChanges and associated target UObjects.
The sequence of changes is applied atomically.
Warning
if the target weak UObject pointers become invalid, those changes are skipped. Possibly leaves things in an undefined state...
Definition at line 16 of file ToolCommandChangeSequence.h.
Constructor & Destructor Documentation
FToolCommandChangeSequence()
FToolCommandChangeSequence::FToolCommandChangeSequence () inline
Definition at line 28 of file ToolCommandChangeSequence.h.
Member Function Documentation
AppendChange()
void FToolCommandChangeSequence::AppendChange (UObject * Target, TUniquePtr< FToolCommandChange > Change) inline
Add a change to the sequence.
Definition at line 33 of file ToolCommandChangeSequence.h.
References MakeShared(), MoveTemp(), Sequence, and Target.
Apply()
virtual void FToolCommandChangeSequence::Apply (UObject * Object) inline override virtual
Apply sequence of changes in-order.
Implements FChange.
Definition at line 42 of file ToolCommandChangeSequence.h.
References check, TSharedPtr< ObjectType, InMode >::Get(), TSharedPtr< ObjectType, InMode >::IsValid(), Object, and Sequence.
Revert()
virtual void FToolCommandChangeSequence::Revert (UObject * Object) inline override virtual
Reverts sequence of changes in reverse-order.
Implements FChange.
Definition at line 56 of file ToolCommandChangeSequence.h.
References check, TSharedPtr< ObjectType, InMode >::Get(), TSharedPtr< ObjectType, InMode >::IsValid(), Object, and Sequence.
ToString()
virtual FString FToolCommandChangeSequence::ToString () const inline override virtual
Returns
string describing this change sequenece
Reimplemented from FToolCommandChange.
Definition at line 70 of file ToolCommandChangeSequence.h.
References Sequence, and TEXT.
Field Documentation
Sequence
TArray<TSharedPtr<FChangeElem> > FToolCommandChangeSequence::Sequence protected
Definition at line 25 of file ToolCommandChangeSequence.h.
Referenced by AppendChange(), Apply(), Revert(), and ToString().
The documentation for this class was generated from the following file:
Runtime/InteractiveToolsFramework/Public/Changes/ToolCommandChangeSequence.h