Unreal Engine 5.6 C++ API: FPackedLevelActorBuilderCluster Class Reference
FPackedLevelActorBuilderCluster Class Reference
#include "PackedLevelActorTypes.h"
Public Member Functions
FPackedLevelActorBuilderCluster (FPackedLevelActorBuilderID InBuilderID)
virtual ~FPackedLevelActorBuilderCluster ()
virtual uint32 ComputeHash () const
virtual bool Equals (const FPackedLevelActorBuilderCluster &Other) const
FPackedLevelActorBuilderID GetBuilderID () const
Private Member Functions
FPackedLevelActorBuilderCluster (const FPackedLevelActorBuilderCluster &)=delete
FPackedLevelActorBuilderCluster & operator= (const FPackedLevelActorBuilderCluster &)=delete
Private Attributes
FPackedLevelActorBuilderID BuilderID
Detailed Description
Definition at line 14 of file PackedLevelActorTypes.h.
Constructor & Destructor Documentation
FPackedLevelActorBuilderCluster() [1/2]
FPackedLevelActorBuilderCluster::FPackedLevelActorBuilderCluster (FPackedLevelActorBuilderID InBuilderID) inline
Definition at line 19 of file PackedLevelActorTypes.h.
References BuilderID.
Referenced by FPackedLevelActorBuilderCluster(), Equals(), and operator=().
~FPackedLevelActorBuilderCluster()
virtual FPackedLevelActorBuilderCluster::~FPackedLevelActorBuilderCluster () inline virtual
Definition at line 21 of file PackedLevelActorTypes.h.
FPackedLevelActorBuilderCluster() [2/2]
FPackedLevelActorBuilderCluster::FPackedLevelActorBuilderCluster (const FPackedLevelActorBuilderCluster &) private delete
References FPackedLevelActorBuilderCluster().
Member Function Documentation
ComputeHash()
virtual uint32 FPackedLevelActorBuilderCluster::ComputeHash () const inline virtual
Definition at line 25 of file PackedLevelActorTypes.h.
References BuilderID, and FCrc::TypeCrc32().
Equals()
virtual bool FPackedLevelActorBuilderCluster::Equals (const FPackedLevelActorBuilderCluster & Other) const inline virtual
Definition at line 30 of file PackedLevelActorTypes.h.
References FPackedLevelActorBuilderCluster(), BuilderID, and Other.
GetBuilderID()
FPackedLevelActorBuilderID FPackedLevelActorBuilderCluster::GetBuilderID () const inline
Definition at line 23 of file PackedLevelActorTypes.h.
References BuilderID.
operator=()
FPackedLevelActorBuilderCluster & FPackedLevelActorBuilderCluster::operator= (const FPackedLevelActorBuilderCluster &) private delete
References FPackedLevelActorBuilderCluster().
Field Documentation
BuilderID
FPackedLevelActorBuilderID FPackedLevelActorBuilderCluster::BuilderID private
Definition at line 16 of file PackedLevelActorTypes.h.
Referenced by FPackedLevelActorBuilderCluster(), ComputeHash(), Equals(), and GetBuilderID().
The documentation for this class was generated from the following file:
Runtime/Engine/Public/PackedLevelActor/PackedLevelActorTypes.h