Unreal Engine 5.6 C++ API: TSharedFromThis< ObjectType, Mode > Class Template Reference
TSharedFromThis< ObjectType, Mode > Class Template Reference
Derive your class from TSharedFromThis to enable access to a TSharedRef directly from an object instance that's already been allocated.
#include "SharedPointer.h"
Public Member Functions
TSharedRef< ObjectType, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< ObjectType const, Mode > AsShared () const
Provides a shared reference to this object (const.) Note that is only valid to call this after a shared reference (or shared pointer) to the object has already been created.
template<typename SubobjectType>
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< ObjectType, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< ObjectType const, Mode > AsWeak () const
template<typename SubobjectType>
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
template<class SharedPtrType, ESPMode SharedPtrMode, class OtherType>
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
template<class SharedRefType, ESPMode SharedPtrMode, class OtherType>
FORCEINLINE void UpdateWeakReferenceInternal (TSharedRef< SharedRefType, SharedPtrMode > const *InSharedRef, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Protected Member Functions
TSharedFromThis ()
Hidden stub constructor.
TSharedFromThis (TSharedFromThis const &)
Hidden stub copy constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions
template<class OtherType>
static FORCEINLINE TSharedRef< OtherType const, Mode > SharedThis (const OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
template<class OtherType>
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Private Attributes
TWeakPtr< ObjectType, Mode > WeakThis
Weak reference to ourselves.
Detailed Description
template<class ObjectType, ESPMode Mode>
class TSharedFromThis< ObjectType, Mode >
Derive your class from TSharedFromThis to enable access to a TSharedRef directly from an object instance that's already been allocated.
Use the optional Mode template argument for thread-safety.
Definition at line 1570 of file SharedPointer.h.
Constructor & Destructor Documentation
TSharedFromThis() [1/2]
template<class ObjectType, ESPMode Mode> TSharedFromThis< ObjectType, Mode >::TSharedFromThis () inline protected
Hidden stub constructor.
Definition at line 1779 of file SharedPointer.h.
Referenced by TSharedFromThis(), and operator=().
TSharedFromThis() [2/2]
template<class ObjectType, ESPMode Mode> TSharedFromThis< ObjectType, Mode >::TSharedFromThis (TSharedFromThis< ObjectType, Mode > const &) inline protected
Hidden stub copy constructor.
Definition at line 1790 of file SharedPointer.h.
References TSharedFromThis().
~TSharedFromThis()
template<class ObjectType, ESPMode Mode> TSharedFromThis< ObjectType, Mode >::~TSharedFromThis () inline protected
Hidden destructor.
Definition at line 1799 of file SharedPointer.h.
Member Function Documentation
AsShared() [1/2]
template<class ObjectType, ESPMode Mode> TSharedRef< ObjectType, Mode > TSharedFromThis< ObjectType, Mode >::AsShared () inline nodiscard
Provides a shared reference to this object.
Note that is only valid to call this after a shared reference (or shared pointer) to the object has already been created. Also note that it is illegal to call this in the object's destructor.
Returns
Returns this object as a shared reference
Definition at line 1581 of file SharedPointer.h.
References check, MoveTemp(), SharedThis(), and WeakThis.
Referenced by AsSharedSubobject(), FMovieSceneChannelProxy::GetChannelByName(), and UE::Tasks::TaskConcurrencyLimiter_Private::FPimpl::Push().
AsShared() [2/2]
template<class ObjectType, ESPMode Mode> TSharedRef< ObjectType const, Mode > TSharedFromThis< ObjectType, Mode >::AsShared () const inline nodiscard
Provides a shared reference to this object (const.) Note that is only valid to call this after a shared reference (or shared pointer) to the object has already been created.
Also note that it is illegal to call this in the object's destructor.
Returns
Returns this object as a shared reference (const)
Definition at line 1608 of file SharedPointer.h.
References check, MoveTemp(), SharedThis(), and WeakThis.
AsSharedSubobject()
template<class ObjectType, ESPMode Mode> template<typename SubobjectType> TSharedRef< SubobjectType, Mode > TSharedFromThis< ObjectType, Mode >::AsSharedSubobject (SubobjectType * SubobjectPtr) const inline nodiscard
Provides a shared reference to a subobject of this object, i.e.
points to an object which shares the lifetime and refcount of this object, but isn't derived from TSharedFromThis. Note that is only valid to call this after a shared reference (or shared pointer) to the object has already been created. Also note that it is illegal to call this in the object's destructor.
Returns
Returns the subobject as a shared reference.
Definition at line 1637 of file SharedPointer.h.
References AsShared().
Referenced by AsWeakSubobject().
AsWeak() [1/2]
template<class ObjectType, ESPMode Mode> TWeakPtr< ObjectType, Mode > TSharedFromThis< ObjectType, Mode >::AsWeak () inline nodiscard
Provides a weak reference to this object.
Note that is only valid to call this after a shared reference (or shared pointer) to the object has already been created. Also note that it is illegal to call this in the object's destructor.
Returns
Returns this object as a weak pointer
Definition at line 1649 of file SharedPointer.h.
References check, and WeakThis.
AsWeak() [2/2]
template<class ObjectType, ESPMode Mode> TWeakPtr< ObjectType const, Mode > TSharedFromThis< ObjectType, Mode >::AsWeak () const inline nodiscard
Definition at line 1667 of file SharedPointer.h.
References check, and WeakThis.
AsWeakSubobject()
template<class ObjectType, ESPMode Mode> template<typename SubobjectType> TWeakPtr< SubobjectType, Mode > TSharedFromThis< ObjectType, Mode >::AsWeakSubobject (SubobjectType * SubobjectPtr) const inline nodiscard
Provides a weak pointer to a subobject of this object, i.e.
points to an object which shares the lifetime and refcount of this object, but isn't derived from TSharedFromThis. Note that is only valid to call this after a shared reference (or shared pointer) to the object has already been created. Also note that it is illegal to call this in the object's destructor.
Returns
Returns the subobject as a weak pointer.
Definition at line 1695 of file SharedPointer.h.
References AsSharedSubobject().
DoesSharedInstanceExist()
template<class ObjectType, ESPMode Mode> FORCEINLINE bool TSharedFromThis< ObjectType, Mode >::DoesSharedInstanceExist () const inline nodiscard
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
If this returns false, it means that your instance has either:
Not yet been assigned to a shared pointer (via MakeShared or MakeShareable).
Is currently within its constructor (so the shared instance isn't yet available).
Is currently within its destructor (so the shared instance is no longer available).
Definition at line 1771 of file SharedPointer.h.
References FORCEINLINE, and WeakThis.
operator=()
template<class ObjectType, ESPMode Mode> FORCEINLINE TSharedFromThis & TSharedFromThis< ObjectType, Mode >::operator= (TSharedFromThis< ObjectType, Mode > const &) inline protected
Hidden stub assignment operator.
Definition at line 1793 of file SharedPointer.h.
References TSharedFromThis(), and FORCEINLINE.
SharedThis() [1/2]
template<class ObjectType, ESPMode Mode> template<class OtherType> FORCEINLINE TSharedRef< OtherType const, Mode > TSharedFromThis< ObjectType, Mode >::SharedThis (const OtherType * ThisPtr) inline static nodiscard protected
Provides access to a shared reference to an object, given the object's 'this' pointer.
Uses the 'this' pointer to derive the object's actual type, then casts and returns an appropriately typed shared reference. Intentionally declared 'protected', as should only be called when the 'this' pointer can be passed.
Returns
Returns this object as a shared pointer (const)
Definition at line 1725 of file SharedPointer.h.
References FORCEINLINE, and StaticCastSharedRef().
SharedThis() [2/2]
template<class ObjectType, ESPMode Mode> template<class OtherType> FORCEINLINE TSharedRef< OtherType, Mode > TSharedFromThis< ObjectType, Mode >::SharedThis (OtherType * ThisPtr) inline static nodiscard protected
Provides access to a shared reference to an object, given the object's 'this' pointer.
Uses the 'this' pointer to derive the object's actual type, then casts and returns an appropriately typed shared reference. Intentionally declared 'protected', as should only be called when the 'this' pointer can be passed.
Returns
Returns this object as a shared pointer
Definition at line 1711 of file SharedPointer.h.
References FORCEINLINE, and StaticCastSharedRef().
Referenced by AsShared(), and AsShared().
UpdateWeakReferenceInternal() [1/2]
template<class ObjectType, ESPMode Mode> template<class SharedPtrType, ESPMode SharedPtrMode, class OtherType> FORCEINLINE void TSharedFromThis< ObjectType, Mode >::UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const * InSharedPtr, OtherType * InObject) const inline
INTERNAL USE ONLY – Do not call this method.
Freshens the internal weak pointer object using the supplied object pointer along with the authoritative shared reference to the object. Note that until this function is called, calls to AsShared() will result in an empty pointer.
Definition at line 1738 of file SharedPointer.h.
References FORCEINLINE, and WeakThis.
UpdateWeakReferenceInternal() [2/2]
template<class ObjectType, ESPMode Mode> template<class SharedRefType, ESPMode SharedPtrMode, class OtherType> FORCEINLINE void TSharedFromThis< ObjectType, Mode >::UpdateWeakReferenceInternal (TSharedRef< SharedRefType, SharedPtrMode > const * InSharedRef, OtherType * InObject) const inline
INTERNAL USE ONLY – Do not call this method.
Freshens the internal weak pointer object using the supplied object pointer along with the authoritative shared reference to the object. Note that until this function is called, calls to AsShared() will result in an empty pointer.
Definition at line 1754 of file SharedPointer.h.
References FORCEINLINE, and WeakThis.
Field Documentation
WeakThis
template<class ObjectType, ESPMode Mode> TWeakPtr< ObjectType, Mode > TSharedFromThis< ObjectType, Mode >::WeakThis mutable private
Weak reference to ourselves.
If we're destroyed then this weak pointer reference will be destructed with ourselves. Note this is declared mutable only so that UpdateWeakReferenceInternal() can update it.
Definition at line 1807 of file SharedPointer.h.
Referenced by AsShared(), AsShared(), AsWeak(), AsWeak(), DoesSharedInstanceExist(), UpdateWeakReferenceInternal(), and UpdateWeakReferenceInternal().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Templates/SharedPointer.h