Unreal Engine 5.6 C++ API: UE::Geometry::FLaplacianOffsetMeshOp Class Reference
UE::Geometry::FLaplacianOffsetMeshOp Class Reference
#include "MeshOffsetOps.h"
Public Member Functions
FLaplacianOffsetMeshOp (const FDynamicMesh3 *Mesh)
virtual void CalculateOffset (FProgressCancel *Progress) override
void Offset ()
Public Member Functions inherited from UE::Geometry::FMeshOffsetBaseOp
FMeshOffsetBaseOp (const FDynamicMesh3 *Mesh)
virtual void CalculateResult (FProgressCancel *Progress) override
Calculate the result of the operator.
double GetOffsetDistance (int32 VertexID, double DefaultValue=1.0) const
Public Member Functions inherited from UE::Geometry::FSimpleMeshProcessingBaseOp
MODELINGOPERATORS_API FSimpleMeshProcessingBaseOp (const FDynamicMesh3 *Mesh)
virtual ~FSimpleMeshProcessingBaseOp ()
MODELINGOPERATORS_API void SetTransform (const FTransformSRT3d &XForm)
MODELINGOPERATORS_API void UpdateResultMeshNormals ()
MODELINGOPERATORS_API void UpdateResultMeshPositions ()
Public Member Functions inherited from UE::Geometry::FDynamicMeshOperator
FDynamicMeshOperator ()
virtual ~FDynamicMeshOperator ()
TUniquePtr< FDynamicMesh3 > ExtractResult ()
const FGeometryResult & GetResultInfo () const
const FTransformSRT3d & GetResultTransform () const
virtual void SetResultInfo (const FGeometryResult &Info)
Set the output information.
virtual void SetResultTransform (const FTransformSRT3d &Transform)
Set the output transform.
Data Fields
bool bUniformWeights = true
double Softness = 0
Data Fields inherited from UE::Geometry::FMeshOffsetBaseOp
TSharedPtr< FMeshNormals > BaseNormals
bool bCreateShell = false
bool bFixedBoundary = false
FMeshBoundaryCache BoundaryCache
TSharedPtr< UE::Geometry::FMeshBoundaryLoops > BoundaryLoops
bool bUseWeightMap = false
FInterval1d OffsetRange = FInterval1d(0.0, 1.0)
double OffsetSign = 1.0
TSharedPtr< UE::Geometry::FIndexedWeightMap1f > WeightMap
Additional Inherited Members
Protected Attributes inherited from UE::Geometry::FSimpleMeshProcessingBaseOp
TArray< FVector3d > PositionBuffer
Protected Attributes inherited from UE::Geometry::FDynamicMeshOperator
FGeometryResult ResultInfo
TUniquePtr< FDynamicMesh3 > ResultMesh
FTransformSRT3d ResultTransform
Detailed Description
Definition at line 314 of file MeshOffsetOps.h.
Constructor & Destructor Documentation
FLaplacianOffsetMeshOp()
UE::Geometry::FLaplacianOffsetMeshOp::FLaplacianOffsetMeshOp (const FDynamicMesh3 * Mesh) inline
Definition at line 317 of file MeshOffsetOps.h.
References UE::Geometry::FMeshOffsetBaseOp::FMeshOffsetBaseOp(), and UE::Geometry::Mesh.
Member Function Documentation
CalculateOffset()
virtual void UE::Geometry::FLaplacianOffsetMeshOp::CalculateOffset (FProgressCancel * Progress) inline override virtual
Implements UE::Geometry::FMeshOffsetBaseOp.
Definition at line 322 of file MeshOffsetOps.h.
References Offset().
Offset()
void UE::Geometry::FLaplacianOffsetMeshOp::Offset () inline
Definition at line 327 of file MeshOffsetOps.h.
References UE::Geometry::FMeshOffsetBaseOp::BaseNormals, bUniformWeights, check, ClampedCotangent, UE::MeshDeformation::ConstructConstrainedMeshDeformer(), UE::Geometry::FMeshOffsetBaseOp::GetOffsetDistance(), TMathUtil< double >::Max(), UE::Geometry::FSimpleMeshProcessingBaseOp::PositionBuffer, UE::Geometry::FDynamicMeshOperator::ResultMesh, Softness, Uniform, and Weight.
Referenced by CalculateOffset().
Field Documentation
bUniformWeights
bool UE::Geometry::FLaplacianOffsetMeshOp::bUniformWeights = true
Definition at line 319 of file MeshOffsetOps.h.
Referenced by Offset().
Softness
double UE::Geometry::FLaplacianOffsetMeshOp::Softness = 0
Definition at line 320 of file MeshOffsetOps.h.
Referenced by Offset().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/MeshModelingToolset/Source/ModelingOperators/Public/DeformationOps/MeshOffsetOps.h