Unreal Engine 5.6 C++ API: FVariant Class Reference
FVariant Class Reference
Implements an extensible union of multiple types.
#include "Variant.h"
Public Member Functions
FVariant ()
Default constructor.
FVariant (const FVariant &)=default
FVariant (const TArray< uint8 > &InArray)
FVariant (const TCHAR *InString)
Creates and initializes a new instance from a TCHAR string.
FVariant (FVariant &&Other)
template<typename T>
FVariant (T InValue)
Creates and initializes a new instance with the specified value.
FVariant (TArray< uint8 > &&InArray)
Creates and initializes a new instance from a byte array.
~FVariant ()=default
void Empty ()
Empties the value.
const TArray< uint8 > & GetBytes () const
Gets the stored value as a byte array.
int32 GetSize () const
Gets the stored value's size (in bytes).
EVariantTypes GetType () const
Gets the stored value's type.
template<typename T>
T GetValue () const
Gets the stored value.
template<>
FORCEINLINE TArray< uint8 > GetValue () const
Gets the stored value for byte arrays.
bool IsEmpty () const
Checks whether the value is empty.
template<typename T>
operator T () const
Implicit conversion operator.
bool operator!= (const FVariant &Other) const
Comparison operator for inequality.
FVariant & operator= (const FVariant &)=default
FVariant & operator= (const TArray< uint8 > &InArray)
FVariant & operator= (const TCHAR *InString)
Assignment operator for TCHAR strings.
FVariant & operator= (FVariant &&Other)
template<typename T>
FVariant & operator= (T InValue)
Assignment operator.
FVariant & operator= (TArray< uint8 > &&InArray)
Assignment operator for byte arrays.
bool operator== (const FVariant &Other) const
Comparison operator for equality.
Private Attributes
EVariantTypes Type
Holds the type of the variant.
TArray< uint8 > Value
Holds the serialized value.
Friends
FArchive & operator<< (FArchive &Ar, FVariant &Variant)
Serializes the given variant type from or into the specified archive.
Detailed Description
Implements an extensible union of multiple types.
Variant types can be used to store a range of different built-in types, as well as user defined types. The values are internally serialized into a byte array, which means that only FArchive serializable types are supported at this time.
Definition at line 113 of file Variant.h.
Constructor & Destructor Documentation
FVariant() [1/7]
FVariant::FVariant () inline
Default constructor.
Definition at line 118 of file Variant.h.
References Empty(), and Type.
Referenced by FVariant(), FVariant(), operator!=(), operator<<, operator=(), operator=(), operator=(), operator=(), operator=(), operator=(), and operator==().
FVariant() [2/7]
FVariant::FVariant (const FVariant &) default
References FVariant().
~FVariant()
FVariant::~FVariant () default
FVariant() [3/7]
FVariant::FVariant (FVariant && Other) inline
Definition at line 126 of file Variant.h.
References FVariant(), Empty, MoveTemp(), Other, Type, and Value.
FVariant() [4/7]
template<typename T> FVariant::FVariant (T InValue) inline
Creates and initializes a new instance with the specified value.
Parameters
InValue The initial value.
Definition at line 150 of file Variant.h.
References TVariantTraits< T >::GetType(), Type, and Value.
FVariant() [5/7]
FVariant::FVariant (TArray< uint8 > && InArray) inline
Creates and initializes a new instance from a byte array.
Array values are passed straight through as an optimization. Please note that, if you serialize any complex types into arrays and then store them in FVariant, you will be responsible for ensuring byte ordering if the FVariant gets sent over the network.
Parameters
InValue- The initial value.
Definition at line 167 of file Variant.h.
References ByteArray, MoveTemp(), Type, and Value.
FVariant() [6/7]
FVariant::FVariant (const TArray< uint8 > & InArray) inline
Definition at line 171 of file Variant.h.
References ByteArray, Type, and Value.
FVariant() [7/7]
FVariant::FVariant (const TCHAR * InString) inline
Creates and initializes a new instance from a TCHAR string.
Parameters
InString The initial value.
Definition at line 181 of file Variant.h.
Member Function Documentation
Empty()
void FVariant::Empty () inline
Empties the value.
See also
IsEmpty
Definition at line 288 of file Variant.h.
References Empty, Type, and Value.
Referenced by FVariant().
GetBytes()
const TArray< uint8 > & FVariant::GetBytes () const inline
Gets the stored value as a byte array.
This method returns the internal representation of any value as an array of raw bytes. To retrieve values of type TArray<uint8> use GetValue<TArray<uint8>>() instead.
Returns
Byte array.
See also
GetValue
Definition at line 317 of file Variant.h.
References Value.
GetSize()
int32 FVariant::GetSize () const inline
Gets the stored value's size (in bytes).
Returns
Size of the value.
See also
GetType, GetValue
Definition at line 328 of file Variant.h.
References Value.
GetType()
EVariantTypes FVariant::GetType () const inline
Gets the stored value's type.
Returns
Type of the value.
See also
GetSize, GetValue
Definition at line 339 of file Variant.h.
References Type.
GetValue() [1/2]
template<typename T> T FVariant::GetValue () const inline
Gets the stored value.
This template function does not provide any automatic conversion between convertible types. The exact type of the value to be extracted must be known.
Returns
The value.
See also
GetSize, GetType
Definition at line 354 of file Variant.h.
References check, Enum, TVariantTraits< T >::GetType(), Type, UInt8, and Value.
Referenced by GetValue(), and operator T().
GetValue() [2/2]
template<> FORCEINLINE TArray< uint8 > FVariant::GetValue () const
Gets the stored value for byte arrays.
Array values are passed straight through as an optimization. Please note that, if you serialize any complex types into arrays and then store them in FVariant, you will be responsible for ensuring byte ordering if the FVariant gets send over the network.
To retrieve any value as an array of serialized bytes, use GetBytes() instead.
Returns
The byte array.
See also
GetBytes
Definition at line 403 of file Variant.h.
References ByteArray, check, FORCEINLINE, GetValue(), Type, and Value.
IsEmpty()
bool FVariant::IsEmpty () const inline
Checks whether the value is empty.
Returns
true if the value is empty, false otherwise.
See also
Empty
Definition at line 302 of file Variant.h.
References Empty, and Type.
operator T()
template<typename T> FVariant::operator T () const inline
Implicit conversion operator.
Parameters
T The type to convert the value to.
Returns
The value converted to the specified type.
Definition at line 252 of file Variant.h.
References GetValue().
operator!=()
bool FVariant::operator!= (const FVariant & Other) const inline
Comparison operator for inequality.
Parameters
Other The variant to compare with.
Returns
true if the values are not equal, false otherwise.
Definition at line 276 of file Variant.h.
References FVariant(), Other, Type, and Value.
operator=() [1/6]
FVariant & FVariant::operator= (const FVariant &) default
References FVariant().
operator=() [2/6]
FVariant & FVariant::operator= (const TArray< uint8 > & InArray) inline
Definition at line 223 of file Variant.h.
References FVariant(), ByteArray, Type, and Value.
operator=() [3/6]
FVariant & FVariant::operator= (const TCHAR * InString) inline
Assignment operator for TCHAR strings.
Parameters
InString The value to assign.
Returns
This instance.
Definition at line 237 of file Variant.h.
References FVariant().
operator=() [4/6]
FVariant & FVariant::operator= (FVariant && Other) inline
Definition at line 133 of file Variant.h.
References FVariant(), Empty, MoveTemp(), Other, Type, and Value.
operator=() [5/6]
template<typename T> FVariant & FVariant::operator= (T InValue) inline
Assignment operator.
Parameters
T The type of the value to assign.
InValue The value to assign.
Returns
This instance.
Definition at line 196 of file Variant.h.
References FVariant(), TVariantTraits< T >::GetType(), Type, and Value.
operator=() [6/6]
FVariant & FVariant::operator= (TArray< uint8 > && InArray) inline
Assignment operator for byte arrays.
Array values are passed straight through as an optimization. Please note that, if you serialize any complex types into arrays and then store them in FVariant, you will be responsible for ensuring byte ordering if the FVariant gets sent over the network.
Parameters
InArray The byte array to assign.
Returns
This instance.
Definition at line 216 of file Variant.h.
References FVariant(), ByteArray, MoveTemp(), Type, and Value.
operator==()
bool FVariant::operator== (const FVariant & Other) const inline
Comparison operator for equality.
Parameters
Other The variant to compare with.
Returns
true if the values are equal, false otherwise.
Definition at line 265 of file Variant.h.
References FVariant(), Other, Type, and Value.
Friends And Related Symbol Documentation
operator<<
FArchive & operator<< (FArchive & Ar, FVariant & Variant) friend
Serializes the given variant type from or into the specified archive.
Parameters
Ar The archive to serialize from or into.
Variant The value to serialize.
Returns
The archive.
Definition at line 375 of file Variant.h.
References FVariant(), Ar, Type, and Value.
Field Documentation
Type
EVariantTypes FVariant::Type private
Holds the type of the variant.
Definition at line 383 of file Variant.h.
Referenced by FVariant(), FVariant(), FVariant(), FVariant(), FVariant(), Empty(), GetType(), GetValue(), IsEmpty(), operator!=(), operator<<, operator=(), operator=(), operator=(), operator=(), and operator==().
Value
TArray<uint8> FVariant::Value private
Holds the serialized value.
Definition at line 386 of file Variant.h.
Referenced by FVariant(), FVariant(), FVariant(), FVariant(), Empty(), GetBytes(), GetSize(), GetValue(), operator!=(), operator<<, operator=(), operator=(), operator=(), operator=(), and operator==().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Misc/Variant.h