Unreal Engine 5.6 C++ API: FGPUBaseSkinAPEXClothVertexFactory Class Reference
FGPUBaseSkinAPEXClothVertexFactory Class Reference abstract
Vertex factory with vertex stream components for GPU-skinned and morph target streams.
#include "GPUSkinVertexFactory.h"
Data Structures
struct ClothShaderType
Public Member Functions
FGPUBaseSkinAPEXClothVertexFactory (uint32 InNumInfluencesPerVertex)
virtual ~FGPUBaseSkinAPEXClothVertexFactory ()
virtual FShaderResourceViewRHIRef GetClothBuffer ()
Get buffer containing cloth influences.
virtual const FShaderResourceViewRHIRef GetClothBuffer () const
virtual uint32 GetClothIndexOffset (uint32 VertexIndex, uint32 LODBias=0) const
Get offset from vertex index to cloth influence index at a given vertex index.
ClothShaderType & GetClothShaderData ()
accessor
const ClothShaderType & GetClothShaderData () const
virtual const FGPUBaseSkinVertexFactory * GetVertexFactory () const =0
virtual FGPUBaseSkinVertexFactory * GetVertexFactory ()=0
Static Public Member Functions
static bool IsClothEnabled (EShaderPlatform Platform)
Protected Attributes
ClothShaderType ClothShaderData
Detailed Description
Vertex factory with vertex stream components for GPU-skinned and morph target streams.
Definition at line 516 of file GPUSkinVertexFactory.h.
Constructor & Destructor Documentation
FGPUBaseSkinAPEXClothVertexFactory()
FGPUBaseSkinAPEXClothVertexFactory::FGPUBaseSkinAPEXClothVertexFactory (uint32 InNumInfluencesPerVertex) inline
Definition at line 595 of file GPUSkinVertexFactory.h.
References ClothShaderData.
Referenced by TGPUSkinAPEXClothVertexFactory< BoneInfluenceType >::TGPUSkinAPEXClothVertexFactory(), TGPUSkinAPEXClothVertexFactory< BoneInfluenceType >::GetClothVertexFactory(), and TGPUSkinAPEXClothVertexFactory< BoneInfluenceType >::GetClothVertexFactory().
~FGPUBaseSkinAPEXClothVertexFactory()
virtual FGPUBaseSkinAPEXClothVertexFactory::~FGPUBaseSkinAPEXClothVertexFactory () inline virtual
Definition at line 600 of file GPUSkinVertexFactory.h.
Member Function Documentation
GetClothBuffer() [1/2]
virtual FShaderResourceViewRHIRef FGPUBaseSkinAPEXClothVertexFactory::GetClothBuffer () inline virtual
Get buffer containing cloth influences.
Reimplemented in TGPUSkinAPEXClothVertexFactory< BoneInfluenceType >.
Definition at line 619 of file GPUSkinVertexFactory.h.
GetClothBuffer() [2/2]
virtual const FShaderResourceViewRHIRef FGPUBaseSkinAPEXClothVertexFactory::GetClothBuffer () const inline virtual
Reimplemented in TGPUSkinAPEXClothVertexFactory< BoneInfluenceType >.
Definition at line 620 of file GPUSkinVertexFactory.h.
GetClothIndexOffset()
virtual uint32 FGPUBaseSkinAPEXClothVertexFactory::GetClothIndexOffset (uint32 VertexIndex, uint32 LODBias = 0) const inline virtual
Get offset from vertex index to cloth influence index at a given vertex index.
The offset will be constant for all vertices in the same section.
Reimplemented in TGPUSkinAPEXClothVertexFactory< BoneInfluenceType >.
Definition at line 622 of file GPUSkinVertexFactory.h.
GetClothShaderData() [1/2]
ClothShaderType & FGPUBaseSkinAPEXClothVertexFactory::GetClothShaderData () inline
accessor
Definition at line 603 of file GPUSkinVertexFactory.h.
References ClothShaderData, and FORCEINLINE.
GetClothShaderData() [2/2]
const ClothShaderType & FGPUBaseSkinAPEXClothVertexFactory::GetClothShaderData () const inline
Definition at line 608 of file GPUSkinVertexFactory.h.
References ClothShaderData, and FORCEINLINE.
GetVertexFactory() [1/2]
virtual const FGPUBaseSkinVertexFactory * FGPUBaseSkinAPEXClothVertexFactory::GetVertexFactory () const pure virtual
Implemented in TGPUSkinAPEXClothVertexFactory< BoneInfluenceType >.
GetVertexFactory() [2/2]
virtual FGPUBaseSkinVertexFactory * FGPUBaseSkinAPEXClothVertexFactory::GetVertexFactory () pure virtual
Implemented in TGPUSkinAPEXClothVertexFactory< BoneInfluenceType >.
IsClothEnabled()
bool FGPUBaseSkinAPEXClothVertexFactory::IsClothEnabled (EShaderPlatform Platform) static
References Platform.
Field Documentation
ClothShaderData
ClothShaderType FGPUBaseSkinAPEXClothVertexFactory::ClothShaderData protected
Definition at line 625 of file GPUSkinVertexFactory.h.
Referenced by FGPUBaseSkinAPEXClothVertexFactory(), GetClothShaderData(), and GetClothShaderData().
The documentation for this class was generated from the following file:
Runtime/Engine/Public/GPUSkinVertexFactory.h