Unreal Engine 5.6 C++ API: TScriptDelegate< InThreadSafetyMode > Class Template Reference
TScriptDelegate< InThreadSafetyMode > Class Template Reference
Script delegate base class.
#include "ScriptDelegates.h"
Public Types
using ThreadSafetyMode = typename UE::Core::Private::TScriptDelegateTraits<InThreadSafetyMode>::ThreadSafetyMode
using WeakPtrType = typename UE::Core::Private::TScriptDelegateTraits<InThreadSafetyMode>::WeakPtrType
Public Member Functions
TScriptDelegate ()
Default constructor.
TScriptDelegate (const TScriptDelegate &Other)
template<typename OtherThreadSafetyMode UE_REQUIRES>
TScriptDelegate (const TScriptDelegate< OtherThreadSafetyMode > &Other)
void BindUFunction (UObject *InObject, const FName &InFunctionName)
Binds a UFunction to this delegate.
void Clear ()
Unbinds this delegate (another name to provide a similar interface to TMulticastScriptDelegate)
FName GetFunctionName () const
Gets the name of the function to call on the bound object.
UObject * GetUObject ()
Gets the object bound to this delegate.
const UObject * GetUObject () const
Gets the object bound to this delegate (const)
UObject * GetUObjectEvenIfUnreachable ()
Gets the object bound to this delegate, even if the object is unreachable.
const UObject * GetUObjectEvenIfUnreachable () const
Gets the object bound to this delegate (const), even if the object is unreachable.
WeakPtrType & GetUObjectRef ()
const WeakPtrType & GetUObjectRef () const
bool IsBound () const
Checks to see if the user object bound to this delegate is still valid.
bool IsBoundToObject (void const *InUserObject) const
Checks to see if this delegate is bound to the given user object.
bool IsBoundToObjectEvenIfUnreachable (void const *InUserObject) const
Checks to see if this delegate is bound to the given user object, even if the object is unreachable.
bool IsCompactable () const
Checks to see if the user object bound to this delegate will ever be valid again.
FORCEINLINE bool operator!= (const TScriptDelegate &Other) const
template<typename OtherThreadSafetyMode UE_REQUIRES>
FORCEINLINE bool operator!= (const TScriptDelegate< OtherThreadSafetyMode > &Other) const
TScriptDelegate & operator= (const TScriptDelegate &Other)
template<typename OtherThreadSafetyMode UE_REQUIRES>
TScriptDelegate & operator= (const TScriptDelegate< OtherThreadSafetyMode > &Other)
FORCEINLINE bool operator== (const TScriptDelegate &Other) const
Comparison operators.
template<typename OtherThreadSafetyMode UE_REQUIRES>
FORCEINLINE bool operator== (const TScriptDelegate< OtherThreadSafetyMode > &Other) const
template<class UObjectTemplate>
void ProcessDelegate (void *Parameters) const
Executes a delegate by calling the named function on the object bound to the delegate.
template<class UObjectTemplate>
FString ToString () const
Converts this delegate to a string representation.
void Unbind ()
Unbinds this delegate.
Static Public Member Functions
template<typename OtherThreadSafetyMode>
static TScriptDelegate CopyFrom (const TScriptDelegate< OtherThreadSafetyMode > &Other)
Protected Attributes
FName FunctionName
Name of the function to call on the bound object.
WeakPtrType Object
The object bound to this delegate, or nullptr if no object is bound.
Private Types
using Super = TDelegateAccessHandlerBase<ThreadSafetyMode>
Private Member Functions
template<class UObjectTemplate>
bool IsBound_Internal () const
Friends
template<typename>
class TScriptDelegate
class FCallDelegateHelper
uint32 GetTypeHash (const TScriptDelegate &Delegate)
FArchive & operator<< (FArchive &Ar, TScriptDelegate &D)
Delegate serialization.
void operator<< (FStructuredArchive::FSlot Slot, TScriptDelegate &D)
Delegate serialization.
struct TIsZeroConstructType< TScriptDelegate >
template<typename>
class TMulticastScriptDelegate
Detailed Description
template<typename InThreadSafetyMode>
class TScriptDelegate< InThreadSafetyMode >
Script delegate base class.
Definition at line 65 of file ScriptDelegates.h.
Member Typedef Documentation
Super
template<typename InThreadSafetyMode> using TScriptDelegate< InThreadSafetyMode >::Super = TDelegateAccessHandlerBase<ThreadSafetyMode> private
Definition at line 78 of file ScriptDelegates.h.
ThreadSafetyMode
template<typename InThreadSafetyMode> using TScriptDelegate< InThreadSafetyMode >::ThreadSafetyMode = typename UE::Core::Private::TScriptDelegateTraits<InThreadSafetyMode>::ThreadSafetyMode
Definition at line 68 of file ScriptDelegates.h.
WeakPtrType
template<typename InThreadSafetyMode> using TScriptDelegate< InThreadSafetyMode >::WeakPtrType = typename UE::Core::Private::TScriptDelegateTraits<InThreadSafetyMode>::WeakPtrType
Definition at line 69 of file ScriptDelegates.h.
Constructor & Destructor Documentation
TScriptDelegate() [1/3]
template<typename InThreadSafetyMode> TScriptDelegate< InThreadSafetyMode >::TScriptDelegate () inline
Default constructor.
Definition at line 86 of file ScriptDelegates.h.
TScriptDelegate() [2/3]
template<typename InThreadSafetyMode> TScriptDelegate< InThreadSafetyMode >::TScriptDelegate (const TScriptDelegate< InThreadSafetyMode > & Other) inline
Definition at line 91 of file ScriptDelegates.h.
TScriptDelegate() [3/3]
template<typename InThreadSafetyMode> template<typename OtherThreadSafetyMode UE_REQUIRES> TScriptDelegate< InThreadSafetyMode >::TScriptDelegate (const TScriptDelegate< OtherThreadSafetyMode > & Other) inline
Definition at line 104 of file ScriptDelegates.h.
Member Function Documentation
BindUFunction()
template<typename InThreadSafetyMode> void TScriptDelegate< InThreadSafetyMode >::BindUFunction (UObject * InObject, const FName & InFunctionName) inline
Binds a UFunction to this delegate.
Parameters
InObject The object to call the function on.
InFunctionName The name of the function to call.
Definition at line 180 of file ScriptDelegates.h.
Clear()
template<typename InThreadSafetyMode> void TScriptDelegate< InThreadSafetyMode >::Clear () inline
Unbinds this delegate (another name to provide a similar interface to TMulticastScriptDelegate)
Definition at line 251 of file ScriptDelegates.h.
CopyFrom()
template<typename InThreadSafetyMode> template<typename OtherThreadSafetyMode> TScriptDelegate TScriptDelegate< InThreadSafetyMode >::CopyFrom (const TScriptDelegate< OtherThreadSafetyMode > & Other) inline static
Definition at line 469 of file ScriptDelegates.h.
Referenced by TMulticastScriptDelegate< FThreadSafeDelegateMode >::Add(), TMulticastScriptDelegate< FThreadSafeDelegateMode >::Add(), TMulticastScriptDelegate< FThreadSafeDelegateMode >::AddUnique(), TMulticastScriptDelegate< FThreadSafeDelegateMode >::AddUnique(), TMulticastScriptDelegate< FThreadSafeDelegateMode >::Remove(), and TMulticastScriptDelegate< FThreadSafeDelegateMode >::Remove().
GetFunctionName()
template<typename InThreadSafetyMode> FName TScriptDelegate< InThreadSafetyMode >::GetFunctionName () const inline
Gets the name of the function to call on the bound object.
Returns
Function name
Definition at line 418 of file ScriptDelegates.h.
Referenced by TMulticastScriptDelegate< FThreadSafeDelegateMode >::Contains(), TScriptDelegate< typename UE::Core::Private::TScriptDelegateTraits< InThreadSafetyMode >::UnicastThreadSafetyModeForMulticasts >::GetTypeHash, TMulticastScriptDelegate< FThreadSafeDelegateMode >::RemoveInternal(), and TScriptDelegate< typename UE::Core::Private::TScriptDelegateTraits< InThreadSafetyMode >::UnicastThreadSafetyModeForMulticasts >::ToString().
GetUObject() [1/2]
template<typename InThreadSafetyMode> UObject * TScriptDelegate< InThreadSafetyMode >::GetUObject () inline
Gets the object bound to this delegate.
Returns
The object
Definition at line 356 of file ScriptDelegates.h.
Referenced by TScriptDelegate< typename UE::Core::Private::TScriptDelegateTraits< InThreadSafetyMode >::UnicastThreadSafetyModeForMulticasts >::IsBoundToObject(), and TScriptDelegate< typename UE::Core::Private::TScriptDelegateTraits< InThreadSafetyMode >::UnicastThreadSafetyModeForMulticasts >::ToString().
GetUObject() [2/2]
template<typename InThreadSafetyMode> const UObject * TScriptDelegate< InThreadSafetyMode >::GetUObject () const inline
Gets the object bound to this delegate (const)
Returns
The object
Definition at line 369 of file ScriptDelegates.h.
GetUObjectEvenIfUnreachable() [1/2]
template<typename InThreadSafetyMode> UObject * TScriptDelegate< InThreadSafetyMode >::GetUObjectEvenIfUnreachable () inline
Gets the object bound to this delegate, even if the object is unreachable.
Returns
The object
Definition at line 382 of file ScriptDelegates.h.
Referenced by TScriptDelegate< typename UE::Core::Private::TScriptDelegateTraits< InThreadSafetyMode >::UnicastThreadSafetyModeForMulticasts >::IsBoundToObjectEvenIfUnreachable().
GetUObjectEvenIfUnreachable() [2/2]
template<typename InThreadSafetyMode> const UObject * TScriptDelegate< InThreadSafetyMode >::GetUObjectEvenIfUnreachable () const inline
Gets the object bound to this delegate (const), even if the object is unreachable.
Returns
The object
Definition at line 395 of file ScriptDelegates.h.
GetUObjectRef() [1/2]
template<typename InThreadSafetyMode> WeakPtrType & TScriptDelegate< InThreadSafetyMode >::GetUObjectRef () inline
Definition at line 403 of file ScriptDelegates.h.
GetUObjectRef() [2/2]
template<typename InThreadSafetyMode> const WeakPtrType & TScriptDelegate< InThreadSafetyMode >::GetUObjectRef () const inline
Definition at line 408 of file ScriptDelegates.h.
IsBound()
template<typename InThreadSafetyMode> bool TScriptDelegate< InThreadSafetyMode >::IsBound () const inline
Checks to see if the user object bound to this delegate is still valid.
Returns
True if the object is still valid and it's safe to execute the function call
Definition at line 193 of file ScriptDelegates.h.
Referenced by TScriptDelegate< typename UE::Core::Private::TScriptDelegateTraits< InThreadSafetyMode >::UnicastThreadSafetyModeForMulticasts >::ToString().
IsBound_Internal()
template<typename InThreadSafetyMode> template<class UObjectTemplate> bool TScriptDelegate< InThreadSafetyMode >::IsBound_Internal () const inline private
Definition at line 159 of file ScriptDelegates.h.
Referenced by TScriptDelegate< typename UE::Core::Private::TScriptDelegateTraits< InThreadSafetyMode >::UnicastThreadSafetyModeForMulticasts >::IsBound().
IsBoundToObject()
template<typename InThreadSafetyMode> bool TScriptDelegate< InThreadSafetyMode >::IsBoundToObject (void const * InUserObject) const inline
Checks to see if this delegate is bound to the given user object.
Returns
True if this delegate is bound to InUserObject, false otherwise.
Definition at line 204 of file ScriptDelegates.h.
Referenced by TMulticastScriptDelegate< FThreadSafeDelegateMode >::RemoveAll().
IsBoundToObjectEvenIfUnreachable()
template<typename InThreadSafetyMode> bool TScriptDelegate< InThreadSafetyMode >::IsBoundToObjectEvenIfUnreachable (void const * InUserObject) const inline
Checks to see if this delegate is bound to the given user object, even if the object is unreachable.
Returns
True if this delegate is bound to InUserObject, false otherwise.
Definition at line 215 of file ScriptDelegates.h.
Referenced by TMulticastScriptDelegate< FThreadSafeDelegateMode >::Contains(), and TMulticastScriptDelegate< FThreadSafeDelegateMode >::RemoveInternal().
IsCompactable()
template<typename InThreadSafetyMode> bool TScriptDelegate< InThreadSafetyMode >::IsCompactable () const inline
Checks to see if the user object bound to this delegate will ever be valid again.
Returns
True if the object is still valid and it's safe to execute the function call
Definition at line 226 of file ScriptDelegates.h.
Referenced by TMulticastScriptDelegate< FThreadSafeDelegateMode >::CompactInvocationList(), TMulticastScriptDelegate< FThreadSafeDelegateMode >::operator<<, and TMulticastScriptDelegate< FThreadSafeDelegateMode >::RemoveAll().
operator!=() [1/2]
template<typename InThreadSafetyMode> FORCEINLINE bool TScriptDelegate< InThreadSafetyMode >::operator!= (const TScriptDelegate< InThreadSafetyMode > & Other) const inline
Definition at line 337 of file ScriptDelegates.h.
operator!=() [2/2]
template<typename InThreadSafetyMode> template<typename OtherThreadSafetyMode UE_REQUIRES> FORCEINLINE bool TScriptDelegate< InThreadSafetyMode >::operator!= (const TScriptDelegate< OtherThreadSafetyMode > & Other) const inline
Definition at line 346 of file ScriptDelegates.h.
operator=() [1/2]
template<typename InThreadSafetyMode> TScriptDelegate & TScriptDelegate< InThreadSafetyMode >::operator= (const TScriptDelegate< InThreadSafetyMode > & Other) inline
Definition at line 112 of file ScriptDelegates.h.
operator=() [2/2]
template<typename InThreadSafetyMode> template<typename OtherThreadSafetyMode UE_REQUIRES> TScriptDelegate & TScriptDelegate< InThreadSafetyMode >::operator= (const TScriptDelegate< OtherThreadSafetyMode > & Other) inline
Definition at line 136 of file ScriptDelegates.h.
operator==() [1/2]
template<typename InThreadSafetyMode> FORCEINLINE bool TScriptDelegate< InThreadSafetyMode >::operator== (const TScriptDelegate< InThreadSafetyMode > & Other) const inline
Comparison operators.
Definition at line 291 of file ScriptDelegates.h.
Referenced by TScriptDelegate< typename UE::Core::Private::TScriptDelegateTraits< InThreadSafetyMode >::UnicastThreadSafetyModeForMulticasts >::operator!=(), and TScriptDelegate< typename UE::Core::Private::TScriptDelegateTraits< InThreadSafetyMode >::UnicastThreadSafetyModeForMulticasts >::operator!=().
operator==() [2/2]
template<typename InThreadSafetyMode> template<typename OtherThreadSafetyMode UE_REQUIRES> FORCEINLINE bool TScriptDelegate< InThreadSafetyMode >::operator== (const TScriptDelegate< OtherThreadSafetyMode > & Other) const inline
Definition at line 316 of file ScriptDelegates.h.
ProcessDelegate()
template<typename InThreadSafetyMode> template<class UObjectTemplate> void TScriptDelegate< InThreadSafetyMode >::ProcessDelegate (void * Parameters) const inline
Executes a delegate by calling the named function on the object bound to the delegate.
You should always first verify that the delegate is safe to execute by calling IsBound() before calling this function. In general, you should never call this function directly. Instead, call Execute() on a derived class.
Parameters
Parameters Parameter structure
Definition at line 433 of file ScriptDelegates.h.
ToString()
template<typename InThreadSafetyMode> template<class UObjectTemplate> FString TScriptDelegate< InThreadSafetyMode >::ToString () const inline
Converts this delegate to a string representation.
Returns
Delegate in string format
Definition at line 262 of file ScriptDelegates.h.
Unbind()
template<typename InThreadSafetyMode> void TScriptDelegate< InThreadSafetyMode >::Unbind () inline
Unbinds this delegate.
Definition at line 240 of file ScriptDelegates.h.
Referenced by TScriptDelegate< typename UE::Core::Private::TScriptDelegateTraits< InThreadSafetyMode >::UnicastThreadSafetyModeForMulticasts >::Clear().
Friends And Related Symbol Documentation
TScriptDelegate
template<typename InThreadSafetyMode> template<typename> friend class TScriptDelegate friend
Definition at line 73 of file ScriptDelegates.h.
FCallDelegateHelper
template<typename InThreadSafetyMode> friend class FCallDelegateHelper friend
Definition at line 491 of file ScriptDelegates.h.
GetTypeHash
template<typename InThreadSafetyMode> uint32 GetTypeHash (const TScriptDelegate< InThreadSafetyMode > & Delegate) friend
Definition at line 461 of file ScriptDelegates.h.
Referenced by TScriptDelegate< typename UE::Core::Private::TScriptDelegateTraits< InThreadSafetyMode >::UnicastThreadSafetyModeForMulticasts >::GetTypeHash.
operator<< [1/2]
template<typename InThreadSafetyMode> FArchive & operator<< (FArchive & Ar, TScriptDelegate< InThreadSafetyMode > & D) friend
Delegate serialization.
Definition at line 273 of file ScriptDelegates.h.
operator<< [2/2]
template<typename InThreadSafetyMode> void operator<< (FStructuredArchive::FSlot Slot, TScriptDelegate< InThreadSafetyMode > & D) friend
Delegate serialization.
Definition at line 282 of file ScriptDelegates.h.
TIsZeroConstructType< TScriptDelegate >
template<typename InThreadSafetyMode> friend struct TIsZeroConstructType< TScriptDelegate > friend
Definition at line 491 of file ScriptDelegates.h.
TMulticastScriptDelegate
template<typename InThreadSafetyMode> template<typename> friend class TMulticastScriptDelegate friend
Definition at line 76 of file ScriptDelegates.h.
Field Documentation
FunctionName
template<typename InThreadSafetyMode> FName TScriptDelegate< InThreadSafetyMode >::FunctionName protected
Name of the function to call on the bound object.
Definition at line 488 of file ScriptDelegates.h.
Referenced by TMulticastScriptDelegate< FThreadSafeDelegateMode >::Contains(), and TMulticastScriptDelegate< FThreadSafeDelegateMode >::Contains().
Object
template<typename InThreadSafetyMode> WeakPtrType TScriptDelegate< InThreadSafetyMode >::Object protected
The object bound to this delegate, or nullptr if no object is bound.
Definition at line 485 of file ScriptDelegates.h.
Referenced by TMulticastScriptDelegate< FThreadSafeDelegateMode >::Contains(), TMulticastScriptDelegate< FThreadSafeDelegateMode >::Contains(), and TScriptDelegate< typename UE::Core::Private::TScriptDelegateTraits< InThreadSafetyMode >::UnicastThreadSafetyModeForMulticasts >::GetTypeHash.
The documentation for this class was generated from the following file:
Runtime/Core/Public/UObject/ScriptDelegates.h