Unreal Engine 5.6 C++ API: TAttributeArrayContainer< AttributeType > Class Template Reference
TAttributeArrayContainer< AttributeType > Class Template Reference
#include "AttributeArrayContainer.h"
Data Structures
struct FChunk
Public Member Functions
TAttributeArrayContainer ()=default
TAttributeArrayContainer (const AttributeType &InDefaultValue)
TArrayView< AttributeType > Get (int32 Index)
Gets the array attribute at the given index as a TArrayView.
TArrayView< const AttributeType > Get (int32 Index) const
Gets the array attribute at the given index as a TArrayView.
AttributeType GetDefault () const
int32 GetElementCount (int32 Index) const
Gets the element count of the array attribute at the given index.
uint32 GetHash (uint32 Crc=0) const
int32 GetReservedElementCount (int32 Index) const
Gets the reserved element count of the array attribute at the given index.
void Initialize (const int32 ElementCount, const AttributeType &Default)
Initializes the array to the given size with the default value.
void Insert (const int32 Index, const AttributeType &Default)
Expands the array if necessary so that the passed element index is valid.
TArrayView< AttributeType > InsertIntoElement (int32 Index, int32 SubArrayIndex, int32 InsertCount=1)
int32 Num () const
Return size of container.
void Remap (const TSparseArray< int32 > &IndexRemap, const AttributeType &Default)
Remaps elements according to the passed remapping table.
TArrayView< AttributeType > RemoveFromElement (int32 Index, int32 SubArrayIndex, int32 Count=1)
void Set (int32 Index, TArrayView< const AttributeType > Value)
Sets the attribute array at the given index to the given TArrayView.
TArrayView< AttributeType > SetElementSize (int32 Index, int32 Size, bool bSetCount, bool bSetDefault=true)
Sets the given attribute array element to have the given number of subarray elements.
void SetNum (const int32 ElementCount, const AttributeType &Default)
Sets the number of elements, each element itself being a subarray of items of type AttributeType.
void SetToDefault (const int32 Index, const AttributeType &Default)
Fills the index with the default value.
Static Private Member Functions
static int32 GetElementsInLastChunk (const int32 ElementCount)
static int32 GetNumRequiredChunks (const int32 ElementCount)
Private Attributes
TArray< FChunk > Chunks
AttributeType DefaultValue = AttributeType()
int32 NumElements = 0
Static Private Attributes
static const int32 ChunkBits = 8
static const int32 ChunkMask = ChunkSize - 1
static const int32 ChunkSize = (1 << ChunkBits)
Friends
FArchive & operator<< (FArchive &Ar, TAttributeArrayContainer< AttributeType > &Array)
Detailed Description
template<typename AttributeType>
class TAttributeArrayContainer< AttributeType >
Definition at line 11 of file AttributeArrayContainer.h.
Constructor & Destructor Documentation
TAttributeArrayContainer() [1/2]
template<typename AttributeType> TAttributeArrayContainer< AttributeType >::TAttributeArrayContainer () default
Referenced by operator<<, and Remap().
TAttributeArrayContainer() [2/2]
template<typename AttributeType> TAttributeArrayContainer< AttributeType >::TAttributeArrayContainer (const AttributeType & InDefaultValue) inline explicit
Definition at line 16 of file AttributeArrayContainer.h.
References DefaultValue.
Member Function Documentation
Get() [1/2]
template<typename AttributeType> TArrayView< AttributeType > TAttributeArrayContainer< AttributeType >::Get (int32 Index) inline
Gets the array attribute at the given index as a TArrayView.
Definition at line 142 of file AttributeArrayContainer.h.
References checkSlow, ChunkBits, ChunkMask, Chunks, TAttributeArrayContainer< AttributeType >::FChunk::Count, TAttributeArrayContainer< AttributeType >::FChunk::Data, TArray< InElementType, InAllocatorType >::GetData(), NumElements, and TAttributeArrayContainer< AttributeType >::FChunk::StartIndex.
Referenced by InsertIntoElement(), Remap(), and RemoveFromElement().
Get() [2/2]
template<typename AttributeType> TArrayView< const AttributeType > TAttributeArrayContainer< AttributeType >::Get (int32 Index) const inline
Gets the array attribute at the given index as a TArrayView.
Definition at line 152 of file AttributeArrayContainer.h.
References checkSlow, ChunkBits, ChunkMask, Chunks, TAttributeArrayContainer< AttributeType >::FChunk::Count, TAttributeArrayContainer< AttributeType >::FChunk::Data, TArray< InElementType, InAllocatorType >::GetData(), NumElements, and TAttributeArrayContainer< AttributeType >::FChunk::StartIndex.
GetDefault()
template<typename AttributeType> AttributeType TAttributeArrayContainer< AttributeType >::GetDefault () const inline
Definition at line 299 of file AttributeArrayContainer.h.
References DefaultValue.
GetElementCount()
template<typename AttributeType> int32 TAttributeArrayContainer< AttributeType >::GetElementCount (int32 Index) const inline
Gets the element count of the array attribute at the given index.
Definition at line 162 of file AttributeArrayContainer.h.
References checkSlow, ChunkBits, ChunkMask, Chunks, TAttributeArrayContainer< AttributeType >::FChunk::Count, and NumElements.
GetElementsInLastChunk()
template<typename AttributeType> int32 TAttributeArrayContainer< AttributeType >::GetElementsInLastChunk (const int32 ElementCount) inline static private
Definition at line 308 of file AttributeArrayContainer.h.
References ChunkMask, and ChunkSize.
Referenced by Initialize(), and SetNum().
GetHash()
template<typename AttributeType> uint32 TAttributeArrayContainer< AttributeType >::GetHash (uint32 Crc = 0) const inline
Definition at line 98 of file AttributeArrayContainer.h.
References Chunks, and FCrc::MemCrc32().
GetNumRequiredChunks()
template<typename AttributeType> int32 TAttributeArrayContainer< AttributeType >::GetNumRequiredChunks (const int32 ElementCount) inline static private
Definition at line 303 of file AttributeArrayContainer.h.
References ChunkBits, and ChunkSize.
Referenced by Initialize(), and SetNum().
GetReservedElementCount()
template<typename AttributeType> int32 TAttributeArrayContainer< AttributeType >::GetReservedElementCount (int32 Index) const inline
Gets the reserved element count of the array attribute at the given index.
Definition at line 172 of file AttributeArrayContainer.h.
References checkSlow, ChunkBits, ChunkMask, Chunks, TAttributeArrayContainer< AttributeType >::FChunk::MaxCount, and NumElements.
Initialize()
template<typename AttributeType> void TAttributeArrayContainer< AttributeType >::Initialize (const int32 ElementCount, const AttributeType & Default) inline
Initializes the array to the given size with the default value.
Definition at line 24 of file AttributeArrayContainer.h.
References check, Chunks, Default, GetElementsInLastChunk(), GetNumRequiredChunks(), and NumElements.
Insert()
template<typename AttributeType> void TAttributeArrayContainer< AttributeType >::Insert (const int32 Index, const AttributeType & Default) inline
Expands the array if necessary so that the passed element index is valid.
Newly created elements will be assigned the default value.
Definition at line 108 of file AttributeArrayContainer.h.
References check, Default, NumElements, and SetNum().
Referenced by Remap().
InsertIntoElement()
template<typename AttributeType> TArrayView< AttributeType > TAttributeArrayContainer< AttributeType >::InsertIntoElement (int32 Index, int32 SubArrayIndex, int32 InsertCount = 1) inline
Definition at line 252 of file AttributeArrayContainer.h.
References checkSlow, ChunkBits, ChunkMask, Chunks, TAttributeArrayContainer< AttributeType >::FChunk::Count, Get(), TArrayView< InElementType, InSizeType >::GetData(), TAttributeArrayContainer< AttributeType >::FChunk::MaxCount, NumElements, Algo::Rotate(), and SetElementSize().
Num()
template<typename AttributeType> int32 TAttributeArrayContainer< AttributeType >::Num () const inline
Return size of container.
Definition at line 21 of file AttributeArrayContainer.h.
References NumElements.
Remap()
template<typename AttributeType> void TAttributeArrayContainer< AttributeType >::Remap (const TSparseArray< int32 > & IndexRemap, const AttributeType & Default)
Remaps elements according to the passed remapping table.
Definition at line 371 of file AttributeArrayContainer.h.
References TAttributeArrayContainer(), Default, Get(), Insert(), MoveTemp(), and Set().
RemoveFromElement()
template<typename AttributeType> TArrayView< AttributeType > TAttributeArrayContainer< AttributeType >::RemoveFromElement (int32 Index, int32 SubArrayIndex, int32 Count = 1) inline
Definition at line 286 of file AttributeArrayContainer.h.
References Count, Get(), TArrayView< InElementType, InSizeType >::Num(), and SetElementSize().
Set()
template<typename AttributeType> void TAttributeArrayContainer< AttributeType >::Set (int32 Index, TArrayView< const AttributeType > Value) inline
Sets the attribute array at the given index to the given TArrayView.
Definition at line 182 of file AttributeArrayContainer.h.
References SetElementSize(), and Value.
Referenced by Remap().
SetElementSize()
template<typename AttributeType> TArrayView< AttributeType > TAttributeArrayContainer< AttributeType >::SetElementSize (int32 Index, int32 Size, bool bSetCount, bool bSetDefault = true) inline
Sets the given attribute array element to have the given number of subarray elements.
Definition at line 195 of file AttributeArrayContainer.h.
References checkSlow, ChunkBits, ChunkMask, Chunks, TAttributeArrayContainer< AttributeType >::FChunk::Count, TAttributeArrayContainer< AttributeType >::FChunk::Data, DefaultValue, TArray< InElementType, InAllocatorType >::GetData(), TAttributeArrayContainer< AttributeType >::FChunk::MaxCount, FMemory::Memmove(), TArray< InElementType, InAllocatorType >::Num(), TAttributeArrayContainer< AttributeType >::FChunk::NumElements, NumElements, TArray< InElementType, InAllocatorType >::SetNum(), TAttributeArrayContainer< AttributeType >::FChunk::StartIndex, and TSequenceHistory< HistorySize >::Size.
Referenced by InsertIntoElement(), RemoveFromElement(), and Set().
SetNum()
template<typename AttributeType> void TAttributeArrayContainer< AttributeType >::SetNum (const int32 ElementCount, const AttributeType & Default) inline
Sets the number of elements, each element itself being a subarray of items of type AttributeType.
Definition at line 42 of file AttributeArrayContainer.h.
References check, ChunkMask, Chunks, ChunkSize, TAttributeArrayContainer< AttributeType >::FChunk::Count, TAttributeArrayContainer< AttributeType >::FChunk::Data, Default, GetElementsInLastChunk(), GetNumRequiredChunks(), TAttributeArrayContainer< AttributeType >::FChunk::MaxCount, No, TAttributeArrayContainer< AttributeType >::FChunk::NumElements, NumElements, TArray< InElementType, InAllocatorType >::SetNum(), and TAttributeArrayContainer< AttributeType >::FChunk::StartIndex.
Referenced by Insert().
SetToDefault()
template<typename AttributeType> void TAttributeArrayContainer< AttributeType >::SetToDefault (const int32 Index, const AttributeType & Default) inline
Fills the index with the default value.
Definition at line 120 of file AttributeArrayContainer.h.
References checkSlow, ChunkBits, ChunkMask, Chunks, Default, and NumElements.
Friends And Related Symbol Documentation
operator<<
template<typename AttributeType> FArchive & operator<< (FArchive & Ar, TAttributeArrayContainer< AttributeType > & Array) friend
Definition at line 133 of file AttributeArrayContainer.h.
References TAttributeArrayContainer(), Ar, and Array.
Field Documentation
ChunkBits
template<typename AttributeType> const int32 TAttributeArrayContainer< AttributeType >::ChunkBits = 8 static private
Definition at line 313 of file AttributeArrayContainer.h.
Referenced by Get(), Get(), GetElementCount(), GetNumRequiredChunks(), GetReservedElementCount(), InsertIntoElement(), SetElementSize(), and SetToDefault().
ChunkMask
template<typename AttributeType> const int32 TAttributeArrayContainer< AttributeType >::ChunkMask = ChunkSize - 1 static private
Definition at line 315 of file AttributeArrayContainer.h.
Referenced by Get(), Get(), GetElementCount(), GetElementsInLastChunk(), GetReservedElementCount(), InsertIntoElement(), SetElementSize(), SetNum(), and SetToDefault().
Chunks
template<typename AttributeType> TArray<FChunk> TAttributeArrayContainer< AttributeType >::Chunks private
Definition at line 363 of file AttributeArrayContainer.h.
Referenced by Get(), Get(), GetElementCount(), GetHash(), GetReservedElementCount(), Initialize(), InsertIntoElement(), SetElementSize(), SetNum(), and SetToDefault().
ChunkSize
template<typename AttributeType> const int32 TAttributeArrayContainer< AttributeType >::ChunkSize = (1 << ChunkBits) static private
Definition at line 314 of file AttributeArrayContainer.h.
Referenced by TAttributeArrayContainer< AttributeType >::FChunk::FChunk(), GetElementsInLastChunk(), GetNumRequiredChunks(), and SetNum().
DefaultValue
template<typename AttributeType> AttributeType TAttributeArrayContainer< AttributeType >::DefaultValue = AttributeType() private
Definition at line 365 of file AttributeArrayContainer.h.
Referenced by TAttributeArrayContainer(), GetDefault(), and SetElementSize().
NumElements
template<typename AttributeType> int32 TAttributeArrayContainer< AttributeType >::NumElements = 0 private
Definition at line 364 of file AttributeArrayContainer.h.
Referenced by Get(), Get(), GetElementCount(), GetReservedElementCount(), Initialize(), Insert(), InsertIntoElement(), Num(), SetElementSize(), SetNum(), and SetToDefault().
The documentation for this class was generated from the following file:
Runtime/MeshDescription/Public/AttributeArrayContainer.h