Unreal Engine 5.6 C++ API: UStreamingSettings Class Reference
UStreamingSettings Class Reference
#include "CoreSettings.h"
Protected Member Functions
virtual void PostInitProperties () override
UPROPERTY()) uint32 FlushStreamingOnExit UPROPERTY () "
UPROPERTY()) uint32 UseBackgroundLevelStreaming UPROPERTY()) uint32 AsyncLoadingUseFullTimeLimit UPROPERTY () .")) float AsyncLoadingTimeLimit
Whether to use the entire time limit even if blocked on I/O.
UPROPERTY () .")) float LevelStreamingActorsUpdateTimeLimit
Maximum allowed time to spend for actor registration steps during level streaming (ms per frame)
UPROPERTY () .")) float LevelStreamingUnregisterComponentsTimeLimit
Maximum allowed time to spend while unregistering components during level streaming (ms per frame)
UPROPERTY ()) float PriorityAsyncLoadingExtraTime
UPROPERTY ()) float PriorityLevelStreamingActorsUpdateExtraTime
UPROPERTY ()) float TimeLimitExceededMinTime
UPROPERTY()) uint32 AsyncLoadingThreadEnabled UPROPERTY()) uint32 WarnIfTimeLimitExceeded UPROPERTY ()) float TimeLimitExceededMultiplier
UPROPERTY ()) int32 LevelStreamingAddPrimitiveGranularity
Batching granularity used to add primitives to scene in parallel when registering actor components during level streaming.
UPROPERTY ()) int32 LevelStreamingComponentsRegistrationGranularity
Batching granularity used to register actor components during level streaming.
UPROPERTY ()) int32 LevelStreamingComponentsUnregistrationGranularity
Batching granularity used to unregister actor components during level streaming.
UPROPERTY ()) int32 MinBulkDataSizeForAsyncLoading
Protected Attributes
UPROPERTY()) uint32 FlushStreamingOnExit ToolTip
Detailed Description
Definition at line 17 of file CoreSettings.h.
Member Function Documentation
PostInitProperties()
virtual void UStreamingSettings::PostInitProperties () override protected virtual
References Category, config, Debug, defaultconfig, Engine, GAsyncLoadingTimeLimit, GAsyncLoadingUseFullTimeLimit, GENERATED_BODY, GLevelStreamingActorsUpdateTimeLimit, GLevelStreamingAddPrimitiveGranularity, GLevelStreamingAllowLevelRequestsWhileAsyncLoadingInMatch, GLevelStreamingComponentsRegistrationGranularity, GLevelStreamingComponentsUnregistrationGranularity, GLevelStreamingContinuouslyIncrementalGCWhileLevelsPendingPurge, GLevelStreamingForceGCAfterLevelStreamedOut, GLevelStreamingForceRouteActorInitializeNextFrame, GLevelStreamingForceVerifyLevelsGotRemovedByGC, GLevelStreamingLowMemoryPendingPurgeCount, GLevelStreamingMaxLevelRequestsAtOnceWhileInMatch, GLevelStreamingRouteActorEndPlayForRemoveFromWorldGranularity, GLevelStreamingRouteActorInitializationGranularity, GLevelStreamingUnregisterComponentsTimeLimit, GPriorityAsyncLoadingExtraTime, GPriorityLevelStreamingActorsUpdateExtraTime, GUseBackgroundLevelStreaming, GUseUnifiedTimeBudgetForStreaming, meta, MinimalAPI, PostInitProperties(), ToolTip, UCLASS(), and UPROPERTY.
Referenced by PostInitProperties().
UPROPERTY() [1/12]
UPROPERTY()) uint32 FlushStreamingOnExit UStreamingSettings::UPROPERTY () protected
UPROPERTY() [2/12]
UPROPERTY()) uint32 UseBackgroundLevelStreaming UPROPERTY()) uint32 AsyncLoadingUseFullTimeLimit UStreamingSettings::UPROPERTY () protected
Whether to use the entire time limit even if blocked on I/O.
References Category, config, meta, ToolTip, and UPROPERTY().
UPROPERTY() [3/12]
UStreamingSettings::UPROPERTY () protected
Maximum allowed time to spend for actor registration steps during level streaming (ms per frame)
References Category, config, meta, ToolTip, and UPROPERTY().
UPROPERTY() [4/12]
UStreamingSettings::UPROPERTY () protected
Maximum allowed time to spend while unregistering components during level streaming (ms per frame)
References Category, config, meta, ToolTip, and UPROPERTY().
UPROPERTY() [5/12]
UStreamingSettings::UPROPERTY () protected
References Category, config, meta, ToolTip, and UPROPERTY().
UPROPERTY() [6/12]
UStreamingSettings::UPROPERTY () protected
References Category, config, meta, ToolTip, and UPROPERTY().
UPROPERTY() [7/12]
UStreamingSettings::UPROPERTY () protected
References Category, config, meta, ToolTip, and UPROPERTY().
UPROPERTY() [8/12]
UPROPERTY()) uint32 AsyncLoadingThreadEnabled UPROPERTY()) uint32 WarnIfTimeLimitExceeded UStreamingSettings::UPROPERTY () protected
References Category, config, float, meta, ToolTip, and UPROPERTY().
Referenced by UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), and UPROPERTY().
UPROPERTY() [9/12]
UStreamingSettings::UPROPERTY () protected
Batching granularity used to add primitives to scene in parallel when registering actor components during level streaming.
References Category, config, meta, ToolTip, and UPROPERTY().
UPROPERTY() [10/12]
UStreamingSettings::UPROPERTY () protected
Batching granularity used to register actor components during level streaming.
References Category, config, meta, ToolTip, and UPROPERTY().
UPROPERTY() [11/12]
UStreamingSettings::UPROPERTY () protected
Batching granularity used to unregister actor components during level streaming.
References Category, config, meta, ToolTip, and UPROPERTY().
UPROPERTY() [12/12]
UStreamingSettings::UPROPERTY () protected
References Category, config, meta, ToolTip, and UPROPERTY().
Field Documentation
ToolTip
UPROPERTY()) uint32 FlushStreamingOnExit UStreamingSettings::ToolTip protected
Initial value:
= "Enables the event driven loader in cooked builds (default). Disabling EDL will result in using deprecated loading path."))
        uint32 EventDrivenLoaderEnabled : 1
Definition at line 115 of file CoreSettings.h.
Referenced by PostInitProperties(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), and UPROPERTY().
The documentation for this class was generated from the following file:
Runtime/Engine/Classes/Engine/CoreSettings.h