Unreal Engine 5.6 C++ API: Metasound::MetasoundVariableNodesPrivate::TVariableMutatorOperator< DataType > Class Template Reference
Metasound::MetasoundVariableNodesPrivate::TVariableMutatorOperator< DataType > Class Template Reference
Operator for providing setting a variable.
#include "MetasoundVariableNodes.h"
Public Types
using FVariable = TVariable<DataType>
Public Types inherited from Metasound::IOperator
using FExecuteFunction = void(*)(IOperator*)
Pointer to execute function for an operator.
using FPostExecuteFunction = void(*)(IOperator*)
Pointer to post execute function for an operator.
using FResetFunction = void(*)(IOperator*, const FResetParams& InParams)
Pointer to initialize function for an operator.
Public Member Functions
TVariableMutatorOperator (TDataWriteReference< FVariable > InVariable, TDataReadReference< DataType > InData)
virtual ~TVariableMutatorOperator ()=default
virtual void BindInputs (FInputVertexInterfaceData &InVertexData) override
BindInputs binds data references in the IOperator with the FInputVertexInterfaceData.
virtual void BindOutputs (FOutputVertexInterfaceData &InVertexData) override
BindOutputs binds data references in the IOperator with the FOutputVertexInterfaceData.
virtual IOperator::FExecuteFunction GetExecuteFunction () override
Return the execution function to call during graph execution.
virtual IOperator::FPostExecuteFunction GetPostExecuteFunction () override
Return the FPostExecute function to call during graph post execution.
virtual IOperator::FResetFunction GetResetFunction () override
Return the reset function to call during graph execution.
void PostExecute ()
void Reset (const IOperator::FResetParams &InParams)
Public Member Functions inherited from Metasound::IOperator
virtual ~IOperator ()
UE_DEPRECATED (5.3, "Bind(FVertexInterfaceData&) has been replaced by BindInputs(FInputVertexInterfaceDAta&) and BindOutputs(FOutputVertexInterfaceData&)") virtual void METASOUNDGRAPHCORE_API Bind(FVertexInterfaceData &InVertexData) const
Bind(...) has been deprecated in favor of BindInputs(...) and BindOutputs(...).
UE_DEPRECATED (5.3, "GetInputs() has been replaced by BindInputs(FInputVertexInterfaceData&).") virtual FDataReferenceCollection METASOUNDGRAPHCORE_API GetInputs() const
GetInputs() has been deprecated in favor of BindInputs(...).
UE_DEPRECATED (5.3, "GetOutputs() has been replaced by BindOutputs(FOutputVertexInterfaceData&)") virtual FDataReferenceCollection METASOUNDGRAPHCORE_API GetOutputs() const
GetOutputs() has been deprecated in favor of BindOutputs(...).
Static Public Member Functions
static TUniquePtr< IOperator > CreateOperator (const FBuildOperatorParams &InParams, FBuildResults &OutResults)
static FVertexInterface DeclareVertexInterface ()
static const FNodeClassMetadata & GetNodeInfo ()
Static Private Member Functions
static void StaticPostExecute (IOperator *InOperator)
static void StaticReset (IOperator *InOperator, const IOperator::FResetParams &InParams)
Private Attributes
TDataReadReference< DataType > Data
TDataWriteReference< FVariable > Variable
Detailed Description
template<typename DataType>
class Metasound::MetasoundVariableNodesPrivate::TVariableMutatorOperator< DataType >
Operator for providing setting a variable.
Definition at line 132 of file MetasoundVariableNodes.h.
Member Typedef Documentation
FVariable
template<typename DataType> using Metasound::MetasoundVariableNodesPrivate::TVariableMutatorOperator< DataType >::FVariable = TVariable<DataType>
Definition at line 135 of file MetasoundVariableNodes.h.
Constructor & Destructor Documentation
TVariableMutatorOperator()
template<typename DataType> Metasound::MetasoundVariableNodesPrivate::TVariableMutatorOperator< DataType >::TVariableMutatorOperator (TDataWriteReference< FVariable > InVariable, TDataReadReference< DataType > InData) inline
Definition at line 179 of file MetasoundVariableNodes.h.
References Data, and Variable.
Referenced by StaticPostExecute(), and StaticReset().
~TVariableMutatorOperator()
template<typename DataType> virtual Metasound::MetasoundVariableNodesPrivate::TVariableMutatorOperator< DataType >::~TVariableMutatorOperator () virtual default
Member Function Documentation
BindInputs()
template<typename DataType> virtual void Metasound::MetasoundVariableNodesPrivate::TVariableMutatorOperator< DataType >::BindInputs (FInputVertexInterfaceData & InVertexData) inline override virtual
BindInputs binds data references in the IOperator with the FInputVertexInterfaceData.
All input data references should be bound to the InVertexData to support other MetaSound systems such as MetaSound BP API, Operator Caching, and live auditioning.
Note: The virtual function IOPerator::BindInputs(...) will be made a pure virtual when IOperator::GetInputs() is removed at or after release 5.5
Note: Binding an data reference may update the which underlying object the reference points to. Any operator which caches pointers or values from data references must update their cached pointers in the call to BindInputs(...). Operators which do not cache the underlying pointer of a data reference do not need to update anything after BindInputs(...)
Example: FMyOperator::FMyOperator(TDataReadReference<float> InGain, TDataReadReference<FAudioBuffer> InAudioBuffer) : Gain(InGain) , AudioBuffer(InAudioBuffer) { MyBufferPtr = AudioBuffer->GetData();
}
void FMyOperator::BindInputs(FInputVertexInterfaceData& InVertexData) { InVertexData.BindReadVertex("Gain", Gain); InVertexData.BindReadVertex("Audio", AudioBuffer);
// Update MyBufferPtr in case AudioBuffer references a new FAudioBuffer. MyBufferPtr = AudioBuffer->GetData(); }
Reimplemented from Metasound::IOperator.
Definition at line 207 of file MetasoundVariableNodes.h.
References Metasound::FInputVertexInterfaceData::BindReadVertex(), Metasound::FInputVertexInterfaceData::BindWriteVertex(), checkf, Data, Metasound::MetasoundVariableNodesPrivate::IsSupportedVertexData(), METASOUND_GET_PARAM_NAME, TEXT, and Variable.
BindOutputs()
template<typename DataType> virtual void Metasound::MetasoundVariableNodesPrivate::TVariableMutatorOperator< DataType >::BindOutputs (FOutputVertexInterfaceData & InVertexData) inline override virtual
BindOutputs binds data references in the IOperator with the FOutputVertexInterfaceData.
All output data references should be bound to the InVertexData to support other MetaSound systems such as MetaSound BP API, Operator Caching, and live auditioning.
Note: The virtual function IOPerator::BindOutputs(...) will be made a pure virtual when IOperator::GetOutputs() is removed at or after release 5.5
Note: Binding an data reference may update the which underlying object the reference points to. Any operator which caches pointers or values from data references must update their cached pointers in the call to BindOutputs(...). Operators which do not cache the underlying pointer of a data reference do not need to update anything after BindOutputs(...)
Example: FMyOperator::FMyOperator(TDataWriteReference<float> InGain, TDataWriteReference<FAudioBuffer> InAudioBuffer) : Gain(InGain) , AudioBuffer(InAudioBuffer) { MyBufferPtr = AudioBuffer->GetData();
}
void FMyOperator::BindOutputs(FOutputVertexInterfaceData& InVertexData) { InVertexData.BindReadVertex("Gain", Gain); InVertexData.BindReadVertex("Audio", AudioBuffer);
// Update MyBufferPtr in case AudioBuffer references a new FAudioBuffer. MyBufferPtr = AudioBuffer->GetData(); }
Reimplemented from Metasound::IOperator.
Definition at line 220 of file MetasoundVariableNodes.h.
References Metasound::FOutputVertexInterfaceData::BindWriteVertex(), METASOUND_GET_PARAM_NAME, and Variable.
CreateOperator()
template<typename DataType> TUniquePtr< IOperator > Metasound::MetasoundVariableNodesPrivate::TVariableMutatorOperator< DataType >::CreateOperator (const FBuildOperatorParams & InParams, FBuildResults & OutResults) inline static
Definition at line 186 of file MetasoundVariableNodes.h.
References Data, Metasound::FInputVertexInterfaceData::FindDataReference(), Metasound::FInputVertexInterfaceData::GetOrCreateDefaultDataReadReference(), Metasound::FBuildOperatorParams::InputData, MakeUnique(), METASOUND_GET_PARAM_NAME, Metasound::FBuildOperatorParams::OperatorSettings, TEXT, UE_LOG, Variable, and Verbose.
DeclareVertexInterface()
template<typename DataType> FVertexInterface Metasound::MetasoundVariableNodesPrivate::TVariableMutatorOperator< DataType >::DeclareVertexInterface () inline static
Definition at line 137 of file MetasoundVariableNodes.h.
References METASOUND_GET_PARAM_NAME.
Referenced by GetNodeInfo().
GetExecuteFunction()
template<typename DataType> virtual IOperator::FExecuteFunction Metasound::MetasoundVariableNodesPrivate::TVariableMutatorOperator< DataType >::GetExecuteFunction () inline override virtual
Return the execution function to call during graph execution.
The IOperator* argument to the FExecutionFunction will be the same IOperator instance which returned the execution function.
nullptr return values are valid and signal an IOperator which does not need to be executed.
Implements Metasound::IOperator.
Definition at line 236 of file MetasoundVariableNodes.h.
GetNodeInfo()
template<typename DataType> const FNodeClassMetadata & Metasound::MetasoundVariableNodesPrivate::TVariableMutatorOperator< DataType >::GetNodeInfo () inline static
Definition at line 152 of file MetasoundVariableNodes.h.
References DeclareVertexInterface(), Metasound::VariableNames::GetVariableMutatorNodeClassName(), Info, LOCTEXT, Metadata, Metasound::PluginAuthor, and Metasound::PluginNodeMissingPrompt.
GetPostExecuteFunction()
template<typename DataType> virtual IOperator::FPostExecuteFunction Metasound::MetasoundVariableNodesPrivate::TVariableMutatorOperator< DataType >::GetPostExecuteFunction () inline override virtual
Return the FPostExecute function to call during graph post execution.
The IOperator* argument to the FPostExecutionFunction will be the same IOperator instance which returned the execution function.
nullptr return values are valid and signal an IOperator which does not need to be post executed.
Implements Metasound::IOperator.
Definition at line 242 of file MetasoundVariableNodes.h.
References StaticPostExecute(), and Variable.
GetResetFunction()
template<typename DataType> virtual IOperator::FResetFunction Metasound::MetasoundVariableNodesPrivate::TVariableMutatorOperator< DataType >::GetResetFunction () inline override virtual
Return the reset function to call during graph execution.
The IOperator* argument to the FExecutionFunction will be the same IOperator instance which returned the execution function.
nullptr return values are valid and signal an IOperator which does not need to be reset.
Implements Metasound::IOperator.
Definition at line 256 of file MetasoundVariableNodes.h.
References StaticReset(), and Variable.
PostExecute()
template<typename DataType> void Metasound::MetasoundVariableNodesPrivate::TVariableMutatorOperator< DataType >::PostExecute () inline
Definition at line 226 of file MetasoundVariableNodes.h.
References Variable.
Referenced by StaticPostExecute().
Reset()
template<typename DataType> void Metasound::MetasoundVariableNodesPrivate::TVariableMutatorOperator< DataType >::Reset (const IOperator::FResetParams & InParams) inline
Definition at line 231 of file MetasoundVariableNodes.h.
References Metasound::IOperator::FResetParams::OperatorSettings, and Variable.
StaticPostExecute()
template<typename DataType> void Metasound::MetasoundVariableNodesPrivate::TVariableMutatorOperator< DataType >::StaticPostExecute (IOperator * InOperator) inline static private
Definition at line 272 of file MetasoundVariableNodes.h.
References TVariableMutatorOperator(), and PostExecute().
Referenced by GetPostExecuteFunction().
StaticReset()
template<typename DataType> void Metasound::MetasoundVariableNodesPrivate::TVariableMutatorOperator< DataType >::StaticReset (IOperator * InOperator, const IOperator::FResetParams & InParams) inline static private
Definition at line 277 of file MetasoundVariableNodes.h.
References TVariableMutatorOperator(), and Reset.
Referenced by GetResetFunction().
Field Documentation
Data
template<typename DataType> TDataReadReference<DataType> Metasound::MetasoundVariableNodesPrivate::TVariableMutatorOperator< DataType >::Data private
Definition at line 283 of file MetasoundVariableNodes.h.
Referenced by TVariableMutatorOperator(), BindInputs(), and CreateOperator().
Variable
template<typename DataType> TDataWriteReference<FVariable> Metasound::MetasoundVariableNodesPrivate::TVariableMutatorOperator< DataType >::Variable private
Definition at line 282 of file MetasoundVariableNodes.h.
Referenced by TVariableMutatorOperator(), BindInputs(), BindOutputs(), CreateOperator(), GetPostExecuteFunction(), GetResetFunction(), PostExecute(), and Reset().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/Metasound/Source/MetasoundGraphCore/Public/MetasoundVariableNodes.h