Unreal Engine 5.6 C++ API: FSequencerKeyCollection Class Reference
FSequencerKeyCollection Class Reference
A collection of keys gathered recursively from a particular node or nodes.
#include "SequencerKeyCollection.h"
Public Member Functions
SEQUENCER_API TOptional< FFrameNumber > FindFirstKeyInRange (const TRange< FFrameNumber > &Range, EFindKeyDirection Direction, EFindKeyType FindKeyType=EFindKeyType::FKT_All) const
Search forwards or backwards for the first key within the specified range.
SEQUENCER_API TArrayView< const FFrameNumber > GetKeysInRange (const TRange< FFrameNumber > &Range, EFindKeyType FindKeyType=EFindKeyType::FKT_All) const
Get a view of all key times that reside within the specified range.
SEQUENCER_API TOptional< FFrameNumber > GetNextKey (FFrameNumber FrameNumber, EFindKeyDirection Direction, const TRange< FFrameNumber > &Range, EFindKeyType FindKeyType=EFindKeyType::FKT_All) const
Search forwards or backwards for the next key from the specified frame number.
const FSequencerKeyCollectionSignature & GetSignature () const
Access the signature this collection was generated with.
UE_DEPRECATED (5.4, "Please use FindFirstKeyInRange which takes EFindKeyType, FindFirstSectionKeyInRange is no longer supported") SEQUENCER_API TOptional< FFrameNumber > FindFirstSectionKeyInRange(const TRange< FFrameNumber > &Range
UE_DEPRECATED (5.4, "Please use GetKeysInRange which takes EFindKeyType, GetSectionKeysInRange is no longer supported") SEQUENCER_API TArrayView< const FFrameNumber > GetSectionKeysInRange(const TRange< FFrameNumber > &Range) const
UE_DEPRECATED (5.4, "Please use GetNextKey which takes EFindKeyType, GetNextSectionKey is no longer supported") SEQUENCER_API TOptional< FFrameNumber > GetNextSectionKey(FFrameNumber FrameNumber
bool Update (const FSequencerKeyCollectionSignature &InSignature)
Update this key collection using the specified signature.
Data Fields
EFindKeyDirection Direction const { return FindFirstKeyInRange(Range, Direction, EFindKeyType::FKT_Sections)
EFindKeyDirection const TRange< FFrameNumber > &Range const { return GetNextKey(FrameNumber, Direction, Range, EFindKeyType::FKT_Sections)
EFindKeyDirection Direction
Private Attributes
TArray< FFrameNumber > AllGroupedTimes
All keys and section times grouped by the supplied threshold.
TArray< FFrameNumber > GroupedSectionTimes
Section times grouped by the supplied threshold.
TArray< FFrameNumber > GroupedTimes
Times grouped by the supplied threshold.
FSequencerKeyCollectionSignature Signature
The signature with which the above array was generated.
Detailed Description
A collection of keys gathered recursively from a particular node or nodes.
Definition at line 101 of file SequencerKeyCollection.h.
Member Function Documentation
FindFirstKeyInRange()
SEQUENCER_API TOptional< FFrameNumber > FSequencerKeyCollection::FindFirstKeyInRange (const TRange< FFrameNumber > & Range, EFindKeyDirection Direction, EFindKeyType FindKeyType = EFindKeyType::FKT_All) const
Search forwards or backwards for the first key within the specified range.
Parameters
Range The range to search within
Direction Whether to return the first or last key that reside in the given range
Returns
(Optional) the time of the key that matched the range
References Direction, and FKT_All.
GetKeysInRange()
SEQUENCER_API TArrayView< const FFrameNumber > FSequencerKeyCollection::GetKeysInRange (const TRange< FFrameNumber > & Range, EFindKeyType FindKeyType = EFindKeyType::FKT_All) const
Get a view of all key times that reside within the specified range.
Parameters
Range The range to search within
Returns
A (possibly empty) array view of all the times that lie within the range
References FKT_All.
Referenced by UE_DEPRECATED().
GetNextKey()
SEQUENCER_API TOptional< FFrameNumber > FSequencerKeyCollection::GetNextKey (FFrameNumber FrameNumber, EFindKeyDirection Direction, const TRange< FFrameNumber > & Range, EFindKeyType FindKeyType = EFindKeyType::FKT_All) const
Search forwards or backwards for the next key from the specified frame number.
Parameters
FrameNumber The frame number to search from
Direction Whether to return the next key or previous key from that time
Returns
(Optional) Frame number of the key that's next or previous from that time
References Direction, and FKT_All.
GetSignature()
const FSequencerKeyCollectionSignature & FSequencerKeyCollection::GetSignature () const inline
Access the signature this collection was generated with.
Returns
The signature that this collection was generated with
Definition at line 141 of file SequencerKeyCollection.h.
References Signature.
UE_DEPRECATED() [1/3]
FSequencerKeyCollection::UE_DEPRECATED (5. 4, "Please use FindFirstKeyInRange which takes EFindKeyType, FindFirstSectionKeyInRange is no longer supported") const &
UE_DEPRECATED() [2/3]
FSequencerKeyCollection::UE_DEPRECATED (5. 4, "Please use GetKeysInRange which takes EFindKeyType, GetSectionKeysInRange is no longer supported") const & inline
Definition at line 123 of file SequencerKeyCollection.h.
References const, FKT_Sections, and GetKeysInRange().
UE_DEPRECATED() [3/3]
FSequencerKeyCollection::UE_DEPRECATED (5. 4, "Please use GetNextKey which takes EFindKeyType, GetNextSectionKey is no longer supported")
Update()
bool FSequencerKeyCollection::Update (const FSequencerKeyCollectionSignature & InSignature)
Update this key collection using the specified signature.
Parameters
InSignature The signature to generate keys for, containing all key areas to use for the generation
Returns
true if this collection was updated, or false if it was already up to date
Field Documentation
AllGroupedTimes
TArray<FFrameNumber> FSequencerKeyCollection::AllGroupedTimes private
All keys and section times grouped by the supplied threshold.
Definition at line 159 of file SequencerKeyCollection.h.
const [1/2]
EFindKeyDirection Direction FSequencerKeyCollection::const { return FindFirstKeyInRange(Range, Direction, EFindKeyType::FKT_Sections)
Definition at line 114 of file SequencerKeyCollection.h.
Referenced by UE_DEPRECATED().
const [2/2]
EFindKeyDirection const TRange<FFrameNumber>& Range FSequencerKeyCollection::const { return GetNextKey(FrameNumber, Direction, Range, EFindKeyType::FKT_Sections)
Definition at line 134 of file SequencerKeyCollection.h.
Direction
EFindKeyDirection FSequencerKeyCollection::Direction
Definition at line 134 of file SequencerKeyCollection.h.
Referenced by FindFirstKeyInRange(), and GetNextKey().
GroupedSectionTimes
TArray<FFrameNumber> FSequencerKeyCollection::GroupedSectionTimes private
Section times grouped by the supplied threshold.
Definition at line 165 of file SequencerKeyCollection.h.
GroupedTimes
TArray<FFrameNumber> FSequencerKeyCollection::GroupedTimes private
Times grouped by the supplied threshold.
Definition at line 162 of file SequencerKeyCollection.h.
Signature
FSequencerKeyCollectionSignature FSequencerKeyCollection::Signature private
The signature with which the above array was generated.
Definition at line 168 of file SequencerKeyCollection.h.
Referenced by GetSignature().
The documentation for this class was generated from the following file:
Editor/Sequencer/Public/SequencerKeyCollection.h