Unreal Engine 5.6 C++ API: FLayoutExtender Class Reference
FLayoutExtender Class Reference
Class used for extending default layouts.
#include "LayoutExtender.h"
Data Structures
struct FExtendedArea
Extended area information.
struct FExtendedTab
Extended tab information.
Public Member Functions
void ExtendArea (FName ExtensionId, const FAreaExtension &AreaExtension)
Extend the area identified by the specified extension ID.
void ExtendAreaRecursive (const TSharedRef< FTabManager::FArea > &Area) const
Recursively extend the specified area.
void ExtendLayout (FTabId PredicateTabId, ELayoutExtensionPosition Position, FTabManager::FTab TabToAdd)
Extend the layout by defining a tab before or after the specified predicate tab ID.
void ExtendStack (FName ExtensionId, ELayoutExtensionPosition Position, FTabManager::FTab TabToAdd)
Extend the tab stack identified by the specified extension ID.
template<typename AllocatorType>
void FindStackExtensions (FName ExtensionID, ELayoutExtensionPosition Position, TArray< FTabManager::FTab, AllocatorType > &OutValues) const
Populate the specified container with the tabs that relate to the specified stack.
template<typename AllocatorType>
void FindTabExtensions (FTabId TabId, ELayoutExtensionPosition Position, TArray< FTabManager::FTab, AllocatorType > &OutValues) const
Populate the specified container with the tabs that relate to the specified tab ID.
Public Member Functions inherited from TSharedFromThis< FLayoutExtender >
TSharedRef< FLayoutExtender, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FLayoutExtender, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Private Attributes
TMultiMap< FName, FExtendedArea > AreaExtensions
Map of extensions for areas.
TMultiMap< FName, FExtendedTab > StackExtensions
Map of extensions for stacks.
TMultiMap< FTabId, FExtendedTab > TabExtensions
Map of extensions for tabs.
Additional Inherited Members
Protected Member Functions inherited from TSharedFromThis< FLayoutExtender >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions inherited from TSharedFromThis< FLayoutExtender >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
Class used for extending default layouts.
Definition at line 27 of file LayoutExtender.h.
Member Function Documentation
ExtendArea()
void FLayoutExtender::ExtendArea (FName ExtensionId, const FAreaExtension & AreaExtension)
Extend the area identified by the specified extension ID.
Parameters
ExtensionId The ID of the area to extend (FTabManager::FArea::ExtensionId)
AreaExtensions A callback to call with the default layout for the desired area
ExtendAreaRecursive()
void FLayoutExtender::ExtendAreaRecursive (const TSharedRef< FTabManager::FArea > & Area) const
Recursively extend the specified area.
ExtendLayout()
void FLayoutExtender::ExtendLayout (FTabId PredicateTabId, ELayoutExtensionPosition Position, FTabManager::FTab TabToAdd)
Extend the layout by defining a tab before or after the specified predicate tab ID.
Parameters
PredicateTabId The existing tab to place the extended tab before/after
Position Whether to place the new tab before or after this tab
TabToAdd The new tab definition
References Position.
ExtendStack()
void FLayoutExtender::ExtendStack (FName ExtensionId, ELayoutExtensionPosition Position, FTabManager::FTab TabToAdd)
Extend the tab stack identified by the specified extension ID.
Parameters
ExtensionId The ID of the area to extend (FTabManager::FStack::ExtensionId)
AreaExtensions A callback to call with the default layout for the desired area
Position Whether to place the new tab at the start or end of this stack. Above and below are not used for this case.
TabToAdd The new tab definition
References Position.
FindStackExtensions()
template<typename AllocatorType> void FLayoutExtender::FindStackExtensions (FName ExtensionID, ELayoutExtensionPosition Position, TArray< FTabManager::FTab, AllocatorType > & OutValues) const inline
Populate the specified container with the tabs that relate to the specified stack.
Parameters
TabId The existing tab that may be extended
Position The position to acquire extensions for (before/after)
OutValues The container to populate with extended tabs
Definition at line 92 of file LayoutExtender.h.
References TArray< InElementType, InAllocatorType >::Add(), Position, TArray< InElementType, InAllocatorType >::Reset(), and StackExtensions.
FindTabExtensions()
template<typename AllocatorType> void FLayoutExtender::FindTabExtensions (FTabId TabId, ELayoutExtensionPosition Position, TArray< FTabManager::FTab, AllocatorType > & OutValues) const inline
Populate the specified container with the tabs that relate to the specified tab ID.
Parameters
TabId The existing tab that may be extended
Position The position to acquire extensions for (before/after)
OutValues The container to populate with extended tabs
Definition at line 68 of file LayoutExtender.h.
References TArray< InElementType, InAllocatorType >::Add(), Position, TArray< InElementType, InAllocatorType >::Reset(), and TabExtensions.
Field Documentation
AreaExtensions
TMultiMap<FName, FExtendedArea> FLayoutExtender::AreaExtensions private
Map of extensions for areas.
Definition at line 146 of file LayoutExtender.h.
StackExtensions
TMultiMap<FName, FExtendedTab> FLayoutExtender::StackExtensions private
Map of extensions for stacks.
Definition at line 143 of file LayoutExtender.h.
Referenced by FindStackExtensions().
TabExtensions
TMultiMap<FTabId, FExtendedTab> FLayoutExtender::TabExtensions private
Map of extensions for tabs.
Definition at line 140 of file LayoutExtender.h.
Referenced by FindTabExtensions().
The documentation for this class was generated from the following file:
Runtime/Slate/Public/Framework/Docking/LayoutExtender.h