Unreal Engine 5.6 C++ API: FTickableObjectRenderThread Class Reference
FTickableObjectRenderThread Class Reference abstract
This class provides common registration for render thread tickable objects.
#include "TickableObjectRenderThread.h"
Data Structures
struct FRenderingThreadTickableObjectsArray
Static array of tickable objects that are ticked from rendering thread.
Public Member Functions
FTickableObjectRenderThread (bool bRegisterImmediately=true, bool bInHighFrequency=false)
Registers this instance with the static array of tickable objects.
virtual ~FTickableObjectRenderThread ()
Removes this instance from the static array of tickable objects.
virtual TStatId GetStatId () const =0
return the stat id to use for this tickable
virtual bool IsTickable () const =0
Pure virtual that must be overloaded by the inheriting class.
virtual bool NeedsRenderingResumedForRenderingThreadTick () const
Used to determine if a rendering thread tickable object must have rendering in a non-suspended state during it's Tick function.
void Register (bool bIsRenderingThreadObject=false)
Registers the object for ticking.
virtual void Tick (float DeltaTime)=0
Pure virtual that must be overloaded by the inheriting class.
void Unregister ()
Static Public Attributes
static RENDERCORE_API FRenderingThreadTickableObjectsArray RenderingThreadHighFrequencyTickableObjects
static RENDERCORE_API FRenderingThreadTickableObjectsArray RenderingThreadTickableObjects
Private Attributes
bool bHighFrequency
bool bRegistered
Detailed Description
This class provides common registration for render thread tickable objects.
It is an abstract base class requiring you to implement the Tick() method.
Definition at line 16 of file TickableObjectRenderThread.h.
Constructor & Destructor Documentation
FTickableObjectRenderThread()
FTickableObjectRenderThread::FTickableObjectRenderThread (bool bRegisterImmediately = true, bool bInHighFrequency = false) inline
Registers this instance with the static array of tickable objects.
Parameters
bRegisterImmediately true if the object should be registered immediately.
Definition at line 46 of file TickableObjectRenderThread.h.
References bHighFrequency, bRegistered, and Register().
Referenced by TRenderResourcePool< ResourceType, ResourcePoolPolicy, ResourceCreationArguments >::TRenderResourcePool(), TRenderResourcePool< ResourceType, ResourcePoolPolicy, ResourceCreationArguments >::TRenderResourcePool(), and FTickableObjectRenderThread::FRenderingThreadTickableObjectsArray::~FRenderingThreadTickableObjectsArray().
~FTickableObjectRenderThread()
virtual FTickableObjectRenderThread::~FTickableObjectRenderThread () inline virtual
Removes this instance from the static array of tickable objects.
Definition at line 59 of file TickableObjectRenderThread.h.
References Unregister().
Member Function Documentation
GetStatId()
virtual TStatId FTickableObjectRenderThread::GetStatId () const pure virtual
return the stat id to use for this tickable
Implemented in FBoneBufferPool, FClothBufferPool, and FShaderPipelineCache.
IsTickable()
virtual bool FTickableObjectRenderThread::IsTickable () const pure virtual
Pure virtual that must be overloaded by the inheriting class.
It is used to determine whether an object is ready to be ticked. This is required for example for all UObject derived classes as they might be loaded async and therefore won't be ready immediately.
Returns
true if class is ready to be ticked, false otherwise.
Implemented in FShaderPipelineCache, TRenderResourcePool< ResourceType, ResourcePoolPolicy, ResourceCreationArguments >, TRenderResourcePool< FVertexBufferAndSRV, FBoneBufferPoolPolicy, FSharedPoolPolicyData::CreationArguments >, and TRenderResourcePool< FVertexBufferAndSRV, FClothBufferPoolPolicy, FSharedPoolPolicyData::CreationArguments >.
NeedsRenderingResumedForRenderingThreadTick()
virtual bool FTickableObjectRenderThread::NeedsRenderingResumedForRenderingThreadTick () const inline virtual
Used to determine if a rendering thread tickable object must have rendering in a non-suspended state during it's Tick function.
Returns
true if the RHIResumeRendering should be called before tick if rendering has been suspended
Reimplemented in FShaderPipelineCache, TRenderResourcePool< ResourceType, ResourcePoolPolicy, ResourceCreationArguments >, TRenderResourcePool< FVertexBufferAndSRV, FBoneBufferPoolPolicy, FSharedPoolPolicyData::CreationArguments >, and TRenderResourcePool< FVertexBufferAndSRV, FClothBufferPoolPolicy, FSharedPoolPolicyData::CreationArguments >.
Definition at line 129 of file TickableObjectRenderThread.h.
Register()
void FTickableObjectRenderThread::Register (bool bIsRenderingThreadObject = false) inline
Registers the object for ticking.
Parameters
bIsRenderingThreadObject true if this object is owned by the rendering thread.
Definition at line 83 of file TickableObjectRenderThread.h.
References bHighFrequency, bRegistered, check, checkf, IsInRenderingThread(), RenderingThreadHighFrequencyTickableObjects, RenderingThreadTickableObjects, and TEXT.
Referenced by FTickableObjectRenderThread(), and TRenderResourcePool< ResourceType, ResourcePoolPolicy, ResourceCreationArguments >::InitRHI().
Tick()
virtual void FTickableObjectRenderThread::Tick (float DeltaTime) pure virtual
Pure virtual that must be overloaded by the inheriting class.
It will be called from within LevelTick.cpp after ticking all actors or from the rendering thread (depending on bIsRenderingThreadObject)
Parameters
DeltaTime Game time passed since the last call.
Implemented in FShaderPipelineCache, TRenderResourcePool< ResourceType, ResourcePoolPolicy, ResourceCreationArguments >, TRenderResourcePool< FVertexBufferAndSRV, FBoneBufferPoolPolicy, FSharedPoolPolicyData::CreationArguments >, and TRenderResourcePool< FVertexBufferAndSRV, FClothBufferPoolPolicy, FSharedPoolPolicyData::CreationArguments >.
References DeltaTime.
Unregister()
void FTickableObjectRenderThread::Unregister () inline
Definition at line 64 of file TickableObjectRenderThread.h.
References bHighFrequency, bRegistered, check, checkf, TArray< InElementType, InAllocatorType >::Find(), INDEX_NONE, IsInRenderingThread(), TArray< InElementType, InAllocatorType >::RemoveAt(), RenderingThreadHighFrequencyTickableObjects, RenderingThreadTickableObjects, and TEXT.
Referenced by ~FTickableObjectRenderThread(), and TRenderResourcePool< ResourceType, ResourcePoolPolicy, ResourceCreationArguments >::ReleaseRHI().
Field Documentation
bHighFrequency
bool FTickableObjectRenderThread::bHighFrequency private
Definition at line 136 of file TickableObjectRenderThread.h.
Referenced by FTickableObjectRenderThread(), Register(), and Unregister().
bRegistered
bool FTickableObjectRenderThread::bRegistered private
Definition at line 135 of file TickableObjectRenderThread.h.
Referenced by FTickableObjectRenderThread(), Register(), and Unregister().
RenderingThreadHighFrequencyTickableObjects
RENDERCORE_API FRenderingThreadTickableObjectsArray FTickableObjectRenderThread::RenderingThreadHighFrequencyTickableObjects static
Definition at line 39 of file TickableObjectRenderThread.h.
Referenced by Register(), and Unregister().
RenderingThreadTickableObjects
RENDERCORE_API FRenderingThreadTickableObjectsArray FTickableObjectRenderThread::RenderingThreadTickableObjects static
Definition at line 38 of file TickableObjectRenderThread.h.
Referenced by Register(), and Unregister().
The documentation for this class was generated from the following file:
Runtime/RenderCore/Public/TickableObjectRenderThread.h