Unreal Engine 5.6 C++ API: Metasound::ISender Class Reference
Metasound::ISender Class Reference abstract
#include "MetasoundRouter.h"
Public Member Functions
ISender (TSharedPtr< IDataChannel, ESPMode::ThreadSafe > InDataChannel, FName DataType)
virtual METASOUNDFRONTEND_API ~ISender ()
virtual int64 GetPayloadID () const =0
virtual bool PushLiteral (const FLiteral &InLiteral)=0
Public Member Functions inherited from Metasound::IDataTransmissionBase
IDataTransmissionBase ()=delete
IDataTransmissionBase (FName InDataType)
virtual ~IDataTransmissionBase ()=default
template<typename TSenderImplementation>
bool CheckType () const
template<typename TSenderImplementation>
TSenderImplementation & GetAs ()
template<typename TSenderImplementation>
const TSenderImplementation & GetAs () const
FName GetDataType () const
Protected Attributes
TSharedPtr< IDataChannel, ESPMode::ThreadSafe > DataChannel
Protected Attributes inherited from Metasound::IDataTransmissionBase
FName DataType
Detailed Description
Definition at line 248 of file MetasoundRouter.h.
Constructor & Destructor Documentation
ISender()
Metasound::ISender::ISender (TSharedPtr< IDataChannel, ESPMode::ThreadSafe > InDataChannel, FName DataType) inline
Definition at line 251 of file MetasoundRouter.h.
References Metasound::IDataTransmissionBase::IDataTransmissionBase(), DataChannel, and Metasound::IDataTransmissionBase::DataType.
Referenced by Metasound::TAudioSender< TDataType >::TAudioSender(), and Metasound::TSender< TDataType >::TSender().
~ISender()
virtual METASOUNDFRONTEND_API Metasound::ISender::~ISender () virtual
References UE_API.
Member Function Documentation
GetPayloadID()
virtual int64 Metasound::ISender::GetPayloadID () const pure virtual
Implemented in Metasound::TAudioSender< TDataType >, and Metasound::TSender< TDataType >.
Referenced by Metasound::TCopyableDataChannel< TDataType >::PushOpaque().
PushLiteral()
virtual bool Metasound::ISender::PushLiteral (const FLiteral & InLiteral) pure virtual
Implemented in Metasound::TAudioSender< TDataType >, and Metasound::TSender< TDataType >.
Field Documentation
DataChannel
TSharedPtr<IDataChannel, ESPMode::ThreadSafe> Metasound::ISender::DataChannel protected
Definition at line 264 of file MetasoundRouter.h.
Referenced by ISender(), and Metasound::TSender< TDataType >::PushToDataChannel().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/Metasound/Source/MetasoundFrontend/Public/MetasoundRouter.h