Unreal Engine 5.6 C++ API: IAnimBlueprintNodeOverrideAssetsContext Class Reference
IAnimBlueprintNodeOverrideAssetsContext Class Reference abstract
#include "IAnimBlueprintNodeOverrideAssetsContext.h"
Public Member Functions
virtual ~IAnimBlueprintNodeOverrideAssetsContext ()=default
template<typename AnimNodeType>
AnimNodeType & GetAnimNode () const
TArrayView< UObject *const > GetAssets () const
Protected Member Functions
virtual FAnimNode_Base * GetAnimNodeImpl () const =0
virtual UScriptStruct * GetAnimNodeTypeImpl () const =0
virtual TArrayView< UObject *const > GetAssetsImpl () const =0
Detailed Description
Definition at line 11 of file IAnimBlueprintNodeOverrideAssetsContext.h.
Constructor & Destructor Documentation
~IAnimBlueprintNodeOverrideAssetsContext()
virtual IAnimBlueprintNodeOverrideAssetsContext::~IAnimBlueprintNodeOverrideAssetsContext () virtual default
Member Function Documentation
GetAnimNode()
template<typename AnimNodeType> AnimNodeType & IAnimBlueprintNodeOverrideAssetsContext::GetAnimNode () const inline
Definition at line 18 of file IAnimBlueprintNodeOverrideAssetsContext.h.
References check, GetAnimNodeImpl(), and GetAnimNodeTypeImpl().
GetAnimNodeImpl()
virtual FAnimNode_Base * IAnimBlueprintNodeOverrideAssetsContext::GetAnimNodeImpl () const protected pure virtual
Referenced by GetAnimNode().
GetAnimNodeTypeImpl()
virtual UScriptStruct * IAnimBlueprintNodeOverrideAssetsContext::GetAnimNodeTypeImpl () const protected pure virtual
Referenced by GetAnimNode().
GetAssets()
TArrayView< UObject *const > IAnimBlueprintNodeOverrideAssetsContext::GetAssets () const inline
Definition at line 25 of file IAnimBlueprintNodeOverrideAssetsContext.h.
References GetAssetsImpl().
GetAssetsImpl()
virtual TArrayView< UObject *const > IAnimBlueprintNodeOverrideAssetsContext::GetAssetsImpl () const protected pure virtual
Referenced by GetAssets().
The documentation for this class was generated from the following file:
Editor/AnimGraph/Public/IAnimBlueprintNodeOverrideAssetsContext.h