Unreal Engine 5.6 C++ API: FScriptInterface Class Reference
FScriptInterface Class Reference
This utility class stores the FProperty data for an interface property used in both blueprint and native code.
#include "ScriptInterface.h"
Public Member Functions
FScriptInterface ()=default
Default constructor.
FScriptInterface (const FScriptInterface &)=default
Copyable.
FScriptInterface (UObject *InObjectPointer, void *InInterfacePointer)
Construction from object and interface.
void AddReferencedObjects (FReferenceCollector &Collector)
FORCEINLINE void * GetInterface () const
Returns the pointer to the native interface if it is valid.
FORCEINLINE UObject * GetObject () const
Returns the ObjectPointer contained by this FScriptInterface.
FORCEINLINE TObjectPtr< UObject > & GetObjectRef ()
Returns the ObjectPointer contained by this FScriptInterface.
FORCEINLINE bool operator!= (const FScriptInterface &Other) const
FScriptInterface & operator= (const FScriptInterface &)=default
FORCEINLINE bool operator== (const FScriptInterface &Other) const
Comparison operator, taking a reference to another FScriptInterface.
FORCEINLINE void SetInterface (void *InInterfacePointer)
Sets the value of the InterfacePointer for this FScriptInterface.
FORCEINLINE void SetObject (UObject *InObjectPointer)
Sets the value of the ObjectPointer for this FScriptInterface.
Protected Member Functions
FArchive & Serialize (FArchive &Ar, class UClass *InterfaceType)
Serialize ScriptInterface.
Private Attributes
void * InterfacePointer = nullptr
For native interfaces, pointer to the location of the interface object within the UObject referenced by ObjectPointer.
TObjectPtr< UObject > ObjectPointer = nullptr
A pointer to a UObject that implements an interface.
Friends
uint32 GetTypeHash (const FScriptInterface &Instance)
Detailed Description
This utility class stores the FProperty data for an interface property used in both blueprint and native code.
For objects natively implementing an interface, ObjectPointer and InterfacePointer point to different locations in the same UObject. For objects that only implement an interface in blueprint, only ObjectPointer will be set because there is no native representation. UClass::ImplementsInterface can be used along with Execute_ event wrappers to properly handle BP-implemented interfaces.
Definition at line 21 of file ScriptInterface.h.
Constructor & Destructor Documentation
FScriptInterface() [1/3]
FScriptInterface::FScriptInterface () default
Default constructor.
Referenced by FScriptInterface(), GetTypeHash, operator!=(), operator=(), and operator==().
FScriptInterface() [2/3]
FScriptInterface::FScriptInterface (UObject * InObjectPointer, void * InInterfacePointer) inline
Construction from object and interface.
Definition at line 49 of file ScriptInterface.h.
References InterfacePointer, and ObjectPointer.
FScriptInterface() [3/3]
FScriptInterface::FScriptInterface (const FScriptInterface &) default
Copyable.
References FScriptInterface().
Member Function Documentation
AddReferencedObjects()
void FScriptInterface::AddReferencedObjects (FReferenceCollector & Collector) inline
Definition at line 117 of file ScriptInterface.h.
References ObjectPointer.
GetInterface()
FORCEINLINE void * FScriptInterface::GetInterface () const inline
Returns the pointer to the native interface if it is valid.
Definition at line 78 of file ScriptInterface.h.
References FORCEINLINE, InterfacePointer, and ObjectPointer.
Referenced by TScriptInterface< const InterfaceType >::GetInterface(), operator!=(), and operator==().
GetObject()
FORCEINLINE UObject * FScriptInterface::GetObject () const inline
Returns the ObjectPointer contained by this FScriptInterface.
Definition at line 62 of file ScriptInterface.h.
References FORCEINLINE, and ObjectPointer.
Referenced by TScriptInterface< const InterfaceType >::GetObject().
GetObjectRef()
FORCEINLINE TObjectPtr< UObject > & FScriptInterface::GetObjectRef () inline
Returns the ObjectPointer contained by this FScriptInterface.
Definition at line 70 of file ScriptInterface.h.
References FORCEINLINE, and ObjectPointer.
Referenced by TScriptInterface< const InterfaceType >::GetObjectRef().
operator!=()
FORCEINLINE bool FScriptInterface::operator!= (const FScriptInterface & Other) const inline
Definition at line 112 of file ScriptInterface.h.
References FScriptInterface(), FORCEINLINE, GetInterface(), ObjectPointer, and Other.
operator=()
FScriptInterface & FScriptInterface::operator= (const FScriptInterface &) default
References FScriptInterface().
operator==()
FORCEINLINE bool FScriptInterface::operator== (const FScriptInterface & Other) const inline
Comparison operator, taking a reference to another FScriptInterface.
Definition at line 108 of file ScriptInterface.h.
References FScriptInterface(), FORCEINLINE, GetInterface(), ObjectPointer, and Other.
Serialize()
FArchive & FScriptInterface::Serialize (FArchive & Ar, class UClass * InterfaceType) protected
Serialize ScriptInterface.
References Ar.
SetInterface()
FORCEINLINE void FScriptInterface::SetInterface (void * InInterfacePointer) inline
Sets the value of the InterfacePointer for this FScriptInterface.
Definition at line 100 of file ScriptInterface.h.
References FORCEINLINE, and InterfacePointer.
Referenced by TScriptInterface< const InterfaceType >::SetInterface(), and SetObject().
SetObject()
FORCEINLINE void FScriptInterface::SetObject (UObject * InObjectPointer) inline
Sets the value of the ObjectPointer for this FScriptInterface.
Definition at line 88 of file ScriptInterface.h.
References FORCEINLINE, ObjectPointer, and SetInterface().
Referenced by TScriptInterface< const InterfaceType >::SetObject().
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FScriptInterface & Instance) friend
Definition at line 122 of file ScriptInterface.h.
References FScriptInterface(), GetTypeHash, and Instance.
Referenced by GetTypeHash.
Field Documentation
InterfacePointer
void* FScriptInterface::InterfacePointer = nullptr private
For native interfaces, pointer to the location of the interface object within the UObject referenced by ObjectPointer.
Definition at line 32 of file ScriptInterface.h.
Referenced by FScriptInterface(), GetInterface(), and SetInterface().
ObjectPointer
TObjectPtr<UObject> FScriptInterface::ObjectPointer = nullptr private
A pointer to a UObject that implements an interface.
Definition at line 27 of file ScriptInterface.h.
Referenced by FScriptInterface(), AddReferencedObjects(), GetInterface(), GetObject(), GetObjectRef(), operator!=(), operator==(), and SetObject().
The documentation for this class was generated from the following file:
Runtime/CoreUObject/Public/UObject/ScriptInterface.h