Unreal Engine 5.6 C++ API: FObjectPreSaveRootContext Class Reference
FObjectPreSaveRootContext Class Reference
Interface used by PreSaveRoot to access the save parameters.
#include "ObjectSaveContext.h"
Public Member Functions
FObjectPreSaveRootContext (const FObjectPreSaveRootContext &Other)
FObjectPreSaveRootContext (FObjectSaveContextData &InData)
void SetCleanupRequired (bool bCleanupRequired)
Set whether PostSaveRoot needs to take extra cleanup steps (false by default).
Public Member Functions inherited from FObjectPreSaveContext
FObjectPreSaveContext (const FObjectPreSaveContext &Other)
FObjectPreSaveContext (FObjectSaveContextData &InData)
UE::Cook::ECookingDLC GetCookingDLC () const
UE::Cook::ECookType GetCookType () const
EObjectSaveContextPhase GetPhase () const
Return which phase of SavePackage callbacks are active.
uint32 GetSaveFlags () const
Return the save flags (ESaveFlags) of the save.
const TCHAR * GetTargetFilename () const
The target Filename being saved into (not the temporary file for saving).
const ITargetPlatform * GetTargetPlatform () const
Return the targetplatform of the save, if cooking.
bool IsCookByTheBook () const
bool IsCooking () const
Report whether this is a save into a target-specific cooked format.
bool IsCookOnTheFly () const
bool IsCookTypeUnknown () const
bool IsDeterminismDebug () const
Applicable only to cook saves: True if the SavePackage call should write extra debug data for debugging cook determinism or incremental cook issues.
bool IsFirstConcurrentSave () const
Always true normally.
bool IsProceduralSave () const
Return whether the package is being saved due to a procedural save.
bool IsUpdatingLoadedPath () const
Return whether LoadedPath of the package being saved is being updated.
void RegisterDeterminismHelper (const TRefCountPtr< UE::Cook::IDeterminismHelper > &DeterminismHelper)
Ignored unless IsDeterminismDebug()=true.
UE_DEPRECATED (5.5, "Calling AddSaveOverride in UObject::PreSave is deprecated. Override UObject::CollectSaveOverrides and call AddSaveOverride on its context instead.") void AddSaveOverride(UObject *Target
Add a save override to specific object.
UE_DEPRECATED(5.6, "These dependencies should instead be reported in OnCookEvent(UE::Cook::ECookEvent::PlatformCookDependencies, ...) by calling FCookEventContext.AddLoadBuildDependency (@see CookEvents.h).") 1 void AddCookBuildDependency(UE UE_DEPRECATED (5.6, "These dependencies should instead be reported in OnCookEvent(UE::Cook::ECookEvent::PlatformCookDependencies, ...) by calling FCookEventContext.AddRuntimeDependency (@see CookEvents.h).") 1 void AddCookRuntimeDependency(FSoftObjectPath Dependency)
UE_DEPRECATED (5.6, "These dependencies should instead be reported in OnCookEvent(UE::Cook::ECookEvent::PlatformCookDependencies, ...) by calling FCookEventContext.HarvestCookRuntimeDependencies (@see CookEvents.h).") 1 void HarvestCookRuntimeDependencies(UObject *HarvestReferencesFrom)
Additional Inherited Members
Data Fields inherited from FObjectPreSaveContext
FObjectSaveOverride InOverride
Protected Attributes inherited from FObjectPreSaveContext
FObjectSaveContextData & Data
Detailed Description
Interface used by PreSaveRoot to access the save parameters.
Definition at line 519 of file ObjectSaveContext.h.
Constructor & Destructor Documentation
FObjectPreSaveRootContext() [1/2]
FObjectPreSaveRootContext::FObjectPreSaveRootContext (FObjectSaveContextData & InData) inline explicit
Definition at line 522 of file ObjectSaveContext.h.
References FObjectPreSaveContext::FObjectPreSaveContext().
Referenced by FObjectPreSaveRootContext().
FObjectPreSaveRootContext() [2/2]
FObjectPreSaveRootContext::FObjectPreSaveRootContext (const FObjectPreSaveRootContext & Other) inline
Definition at line 527 of file ObjectSaveContext.h.
References FObjectPreSaveContext::FObjectPreSaveContext(), FObjectPreSaveRootContext(), FObjectPreSaveContext::Data, and Other.
Member Function Documentation
SetCleanupRequired()
void FObjectPreSaveRootContext::SetCleanupRequired (bool bCleanupRequired) inline
Set whether PostSaveRoot needs to take extra cleanup steps (false by default).
Definition at line 533 of file ObjectSaveContext.h.
References FObjectPreSaveContext::Data.
The documentation for this class was generated from the following file:
Runtime/CoreUObject/Public/UObject/ObjectSaveContext.h