Unreal Engine 5.6 C++ API: IReviewCommentAPI Class Reference
IReviewCommentAPI Class Reference abstract
#include "ReviewComments.h"
Public Member Functions
const FReviewComment const FString const FReviewTopic const FString &virtual ~IReviewCommentAPI ()=default
const FReviewComment const FString & DECLARE_DELEGATE_TwoParams (OnEditCommentComplete, const FReviewComment &, const FString &) DECLARE_DELEGATE_TwoParams(OnGetReviewTopicForCLComplete
DECLARE_DELEGATE_TwoParams (OnGetCommentsComplete, const TArray< FReviewComment > &, const FString &) DECLARE_DELEGATE_TwoParams(OnPostCommentComplete
virtual void EditComment (const FReviewComment &Comment, const OnEditCommentComplete &OnComplete, bool bSilenceNotification=false) const =0
virtual void GetComments (const FReviewTopic &Topic, const OnGetCommentsComplete &OnComplete) const =0
virtual void GetOrCreateReviewTopicForCL (const FString &ChangelistNum, const OnGetReviewTopicForCLComplete &OnComplete) const =0
virtual void GetReviewTopicForCL (const FString &ChangelistNum, const OnGetReviewTopicForCLComplete &OnComplete) const =0
virtual FString GetUsername () const =0
virtual void PostComment (FReviewComment &Comment, const OnPostCommentComplete &OnComplete, bool bSilenceNotification=false) const =0
Public Member Functions inherited from TSharedFromThis< IReviewCommentAPI >
TSharedRef< IReviewCommentAPI, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< IReviewCommentAPI, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Additional Inherited Members
Protected Member Functions inherited from TSharedFromThis< IReviewCommentAPI >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions inherited from TSharedFromThis< IReviewCommentAPI >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
Definition at line 117 of file ReviewComments.h.
Constructor & Destructor Documentation
~IReviewCommentAPI()
const FReviewComment const FString const FReviewTopic const FString &virtual IReviewCommentAPI::~IReviewCommentAPI () virtual default
Member Function Documentation
DECLARE_DELEGATE_TwoParams() [1/2]
const FReviewComment const FString & IReviewCommentAPI::DECLARE_DELEGATE_TwoParams (OnEditCommentComplete , const FReviewComment & , const FString &)
References DECLARE_DELEGATE_TwoParams().
DECLARE_DELEGATE_TwoParams() [2/2]
IReviewCommentAPI::DECLARE_DELEGATE_TwoParams (OnGetCommentsComplete , const TArray< FReviewComment > & , const FString &)
Referenced by DECLARE_DELEGATE_TwoParams().
EditComment()
virtual void IReviewCommentAPI::EditComment (const FReviewComment & Comment, const OnEditCommentComplete & OnComplete, bool bSilenceNotification = false) const pure virtual
References EditComment().
Referenced by EditComment().
GetComments()
virtual void IReviewCommentAPI::GetComments (const FReviewTopic & Topic, const OnGetCommentsComplete & OnComplete) const pure virtual
References GetComments().
Referenced by GetComments().
GetOrCreateReviewTopicForCL()
virtual void IReviewCommentAPI::GetOrCreateReviewTopicForCL (const FString & ChangelistNum, const OnGetReviewTopicForCLComplete & OnComplete) const pure virtual
References GetOrCreateReviewTopicForCL().
Referenced by GetOrCreateReviewTopicForCL().
GetReviewTopicForCL()
virtual void IReviewCommentAPI::GetReviewTopicForCL (const FString & ChangelistNum, const OnGetReviewTopicForCLComplete & OnComplete) const pure virtual
References GetReviewTopicForCL().
Referenced by GetReviewTopicForCL().
GetUsername()
virtual FString IReviewCommentAPI::GetUsername () const pure virtual
References GetUsername().
Referenced by GetUsername().
PostComment()
virtual void IReviewCommentAPI::PostComment (FReviewComment & Comment, const OnPostCommentComplete & OnComplete, bool bSilenceNotification = false) const pure virtual
References PostComment().
Referenced by PostComment().
The documentation for this class was generated from the following file:
Editor/Kismet/Public/ReviewComments.h