Unreal Engine 5.6 C++ API: TSortableMapBase< KeyType, ValueType, SetAllocator, KeyFuncs > Class Template Reference
TSortableMapBase< KeyType, ValueType, SetAllocator, KeyFuncs > Class Template Reference
The base type of sortable maps.
#include "Map.h"
Data Structures
class FKeyComparisonClass
Extracts the pair's key from the map's pair structure and passes it to the user provided comparison class.
class FValueComparisonClass
Extracts the pair's value from the map's pair structure and passes it to the user provided comparison class.
Public Member Functions
template<typename PREDICATE_CLASS>
FORCEINLINE void KeySort (const PREDICATE_CLASS &Predicate)
Sorts the pairs array using each pair's Key as the sort criteria, then rebuilds the map's hash.
template<typename PREDICATE_CLASS>
FORCEINLINE void KeyStableSort (const PREDICATE_CLASS &Predicate)
Stable sorts the pairs array using each pair's Key as the sort criteria, then rebuilds the map's hash.
void SortFreeList ()
Sort the free element list so that subsequent additions will occur in the lowest available TSet index resulting in tighter packing without moving any existing items.
template<typename PREDICATE_CLASS>
FORCEINLINE void ValueSort (const PREDICATE_CLASS &Predicate)
Sorts the pairs array using each pair's Value as the sort criteria, then rebuilds the map's hash.
template<typename PREDICATE_CLASS>
FORCEINLINE void ValueStableSort (const PREDICATE_CLASS &Predicate)
Stable sorts the pairs array using each pair's Value as the sort criteria, then rebuilds the map's hash.
Public Member Functions inherited from TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >
FORCEINLINE ValueType & Add (const KeyType &InKey)
Set a default value associated with a key.
FORCEINLINE ValueType & Add (const KeyType &InKey, const ValueType &InValue)
Set the value associated with a key.
FORCEINLINE ValueType & Add (const KeyType &InKey, ValueType &&InValue)
FORCEINLINE ValueType & Add (const TTuple< KeyType, ValueType > &InKeyValue)
Set the value associated with a key.
FORCEINLINE ValueType & Add (KeyType &&InKey)
FORCEINLINE ValueType & Add (KeyType &&InKey, const ValueType &InValue)
FORCEINLINE ValueType & Add (KeyType &&InKey, ValueType &&InValue)
FORCEINLINE ValueType & Add (TTuple< KeyType, ValueType > &&InKeyValue)
FORCEINLINE ValueType & AddByHash (uint32 KeyHash, const KeyType &InKey)
See Add() and class documentation section on ByHash() functions.
FORCEINLINE ValueType & AddByHash (uint32 KeyHash, const KeyType &InKey, const ValueType &InValue)
See Add() and class documentation section on ByHash() functions.
FORCEINLINE ValueType & AddByHash (uint32 KeyHash, const KeyType &InKey, ValueType &&InValue)
FORCEINLINE ValueType & AddByHash (uint32 KeyHash, KeyType &&InKey)
FORCEINLINE ValueType & AddByHash (uint32 KeyHash, KeyType &&InKey, const ValueType &InValue)
FORCEINLINE ValueType & AddByHash (uint32 KeyHash, KeyType &&InKey, ValueType &&InValue)
TArray< ElementType > Array () const
Copy the key/value pairs in this map into an array.
FORCEINLINE TRangedForIterator begin ()
DO NOT USE DIRECTLY STL-like iterators to enable range-based for loop support.
FORCEINLINE TRangedForConstIterator begin () const
FORCEINLINE void Compact ()
Compacts the pair set to remove holes.
FORCEINLINE void CompactStable ()
Compacts the pair set to remove holes.
FORCEINLINE bool Contains (KeyConstPointerType Key) const
Check if map contains the specified key.
template<typename ComparableKey>
FORCEINLINE bool ContainsByHash (uint32 KeyHash, const ComparableKey &Key) const
See Contains() and class documentation section on ByHash() functions.
void CopyUnfrozen (const FMemoryUnfreezeContent &Context, void *Dst) const
FORCEINLINE void CountBytes (FArchive &Ar) const
Track the container's memory use through an archive.
FORCEINLINE TConstIterator CreateConstIterator () const
Creates a const iterator over all the pairs in this map.
FORCEINLINE TConstKeyIterator CreateConstKeyIterator (typename TConstKeyIterator::KeyArgumentType InKey) const
Creates a const iterator over the values associated with a specified key in a map.
FORCEINLINE TIterator CreateIterator ()
Creates an iterator over all the pairs in this map.
FORCEINLINE TKeyIterator CreateKeyIterator (typename TKeyIterator::KeyArgumentType InKey)
Creates an iterator over the values associated with a specified key in a map.
void Dump (FOutputDevice &Ar)
Describes the map's contents through an output device.
template<typename InitKeyType = KeyType>
ValueType & Emplace (InitKeyType &&InKey)
Set a default value associated with a key.
template<typename InitKeyType = KeyType, typename InitValueType = ValueType>
ValueType & Emplace (InitKeyType &&InKey, InitValueType &&InValue)
Sets the value associated with a key.
template<typename InitKeyType = KeyType>
ValueType & EmplaceByHash (uint32 KeyHash, InitKeyType &&InKey)
See Emplace() and class documentation section on ByHash() functions.
template<typename InitKeyType = KeyType, typename InitValueType = ValueType>
ValueType & EmplaceByHash (uint32 KeyHash, InitKeyType &&InKey, InitValueType &&InValue)
See Emplace() and class documentation section on ByHash() functions.
FORCEINLINE void Empty (int32 ExpectedNumElements=0)
Removes all elements from the map.
FORCEINLINE TRangedForIterator end ()
FORCEINLINE TRangedForConstIterator end () const
template<typename Predicate>
TMap< KeyType, ValueType, SetAllocator, KeyFuncs > FilterByPredicate (Predicate Pred) const
Filters the elements in the map based on a predicate functor.
FORCEINLINE ValueType * Find (KeyConstPointerType Key)
Find the value associated with a specified key.
FORCEINLINE const ValueType * Find (KeyConstPointerType Key) const
ElementType * FindArbitraryElement ()
Finds any pair in the map and returns a pointer to it.
const ElementType * FindArbitraryElement () const
template<typename ComparableKey>
FORCEINLINE ValueType * FindByHash (uint32 KeyHash, const ComparableKey &Key)
See Find() and class documentation section on ByHash() functions.
template<typename ComparableKey>
FORCEINLINE const ValueType * FindByHash (uint32 KeyHash, const ComparableKey &Key) const
template<typename ComparableKey>
FORCEINLINE ValueType & FindByHashChecked (uint32 KeyHash, const ComparableKey &Key)
template<typename ComparableKey>
FORCEINLINE const ValueType & FindByHashChecked (uint32 KeyHash, const ComparableKey &Key) const
FORCEINLINE ValueType & FindChecked (KeyConstPointerType Key)
Find a reference to the value associated with a specified key.
FORCEINLINE const ValueType & FindChecked (KeyConstPointerType Key) const
Find a reference to the value associated with a specified key.
FORCEINLINE FSetElementId FindId (KeyInitType Key) const
Finds the index of the first element that is assigned to the specified key.
template<typename ComparableKey>
FORCEINLINE FSetElementId FindIdByHash (uint32 KeyHash, const ComparableKey &Key) const
See FindId() and class documentation section on ByHash() functions.
const KeyType * FindKey (ValueInitType Value) const
Find the key associated with the specified value.
FORCEINLINE ValueType & FindOrAdd (const KeyType &Key)
Find the value associated with a specified key, or if none exists, adds a value using the default constructor.
FORCEINLINE ValueType & FindOrAdd (const KeyType &Key, const ValueType &Value)
Find the value associated with a specified key, or if none exists, adds a value using the default constructor.
FORCEINLINE ValueType & FindOrAdd (const KeyType &Key, ValueType &&Value)
FORCEINLINE ValueType & FindOrAdd (KeyType &&Key)
FORCEINLINE ValueType & FindOrAdd (KeyType &&Key, const ValueType &Value)
FORCEINLINE ValueType & FindOrAdd (KeyType &&Key, ValueType &&Value)
FORCEINLINE ValueType & FindOrAddByHash (uint32 KeyHash, const KeyType &Key)
See FindOrAdd() and class documentation section on ByHash() functions.
FORCEINLINE ValueType & FindOrAddByHash (uint32 KeyHash, const KeyType &Key, const ValueType &Value)
See FindOrAdd() and class documentation section on ByHash() functions.
FORCEINLINE ValueType & FindOrAddByHash (uint32 KeyHash, const KeyType &Key, ValueType &&Value)
FORCEINLINE ValueType & FindOrAddByHash (uint32 KeyHash, KeyType &&Key)
FORCEINLINE ValueType & FindOrAddByHash (uint32 KeyHash, KeyType &&Key, const ValueType &Value)
FORCEINLINE ValueType & FindOrAddByHash (uint32 KeyHash, KeyType &&Key, ValueType &&Value)
FORCEINLINE ValueType FindRef (KeyConstPointerType Key) const
Find the value associated with a specified key.
FORCEINLINE ValueType FindRef (KeyConstPointerType Key, ValueType DefaultValue) const
Find the value associated with a specified key.
template<typename Allocator>
void GenerateKeyArray (TArray< KeyType, Allocator > &OutArray) const
Generate an array from the keys in this map.
template<typename Allocator>
void GenerateValueArray (TArray< ValueType, Allocator > &OutArray) const
Generate an array from the values in this map.
FORCEINLINE ElementType & Get (FSetElementId Id)
Return a mapped pair by internal identifier.
FORCEINLINE const ElementType & Get (FSetElementId Id) const
Return a mapped pair by internal identifier.
FORCEINLINE SIZE_T GetAllocatedSize () const
Helper function to return the amount of memory allocated by this container .
template<typename Allocator>
int32 GetKeys (TArray< KeyType, Allocator > &OutKeys) const
Get the unique keys contained within this map.
template<typename InSetKeyFuncs, typename InSetAllocator>
int32 GetKeys (TSet< KeyType, InSetKeyFuncs, InSetAllocator > &OutKeys) const
Get the unique keys contained within this map.
FORCEINLINE int32 GetMaxIndex () const
bool IsEmpty () const
Returns true if the map is empty and contains no elements.
FORCEINLINE bool IsValidId (FSetElementId Id) const
Checks whether an element id is valid.
FORCEINLINE int32 Num () const
bool OrderIndependentCompareEqual (const TMapBase &Other) const
Compare this map with another for equality.
FORCEINLINE void Remove (FSetElementId Id)
Removes the element at the specified index.
FORCEINLINE int32 Remove (KeyConstPointerType InKey)
Remove all value associations for a key.
template<typename ComparableKey>
FORCEINLINE int32 RemoveByHash (uint32 KeyHash, const ComparableKey &Key)
See Remove() and class documentation section on ByHash() functions.
FORCEINLINE void Reserve (int32 Number)
Preallocates enough memory to contain Number elements.
FORCEINLINE void Reset ()
Efficiently empties out the map but preserves all allocations and capacities.
FORCEINLINE void Shrink ()
Shrinks the pair set to avoid slack.
void WriteMemoryImage (FMemoryImageWriter &Writer) const
Protected Types
using IntrusiveUnsetOptionalStateType = TSortableMapBase
typedef TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs > Super
Protected Types inherited from TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >
typedef TSet< ElementType, KeyFuncs, SetAllocator > ElementSetType
using IntrusiveUnsetOptionalStateType = TMapBase
Protected Member Functions
TSortableMapBase ()=default
TSortableMapBase (const TSortableMapBase &)=default
template<typename OtherSetAllocator>
TSortableMapBase (const TSortableMapBase< KeyType, ValueType, OtherSetAllocator, KeyFuncs > &Other)
Constructor for copying elements from a TMap with a different SetAllocator.
TSortableMapBase (FIntrusiveUnsetOptionalState Tag)
TSortableMapBase (TSortableMapBase &&)=default
template<typename OtherSetAllocator>
TSortableMapBase (TSortableMapBase< KeyType, ValueType, OtherSetAllocator, KeyFuncs > &&Other)
Constructor for moving elements from a TMap with a different SetAllocator.
TSortableMapBase & operator= (const TSortableMapBase &)=default
template<typename OtherSetAllocator>
TSortableMapBase & operator= (const TSortableMapBase< KeyType, ValueType, OtherSetAllocator, KeyFuncs > &Other)
Assignment operator for copying elements from a TMap with a different SetAllocator.
TSortableMapBase & operator= (TSortableMapBase &&)=default
template<typename OtherSetAllocator>
TSortableMapBase & operator= (TSortableMapBase< KeyType, ValueType, OtherSetAllocator, KeyFuncs > &&Other)
Assignment operator for moving elements from a TMap with a different SetAllocator.
bool operator== (FIntrusiveUnsetOptionalState Tag) const
Protected Member Functions inherited from TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >
TMapBase ()=default
TMapBase (const TMapBase &)=default
template<typename OtherSetAllocator>
TMapBase (const TMapBase< KeyType, ValueType, OtherSetAllocator, KeyFuncs > &Other)
Constructor for copying elements from a TMap with a different SetAllocator.
TMapBase (FIntrusiveUnsetOptionalState Tag)
TMapBase (TMapBase &&)=default
template<typename OtherSetAllocator>
TMapBase (TMapBase< KeyType, ValueType, OtherSetAllocator, KeyFuncs > &&Other)
Constructor for moving elements from a TMap with a different SetAllocator.
TMapBase & operator= (const TMapBase &)=default
template<typename OtherSetAllocator>
TMapBase & operator= (const TMapBase< KeyType, ValueType, OtherSetAllocator, KeyFuncs > &Other)
Assignment operator for copying elements from a TMap with a different SetAllocator.
TMapBase & operator= (TMapBase &&)=default
template<typename OtherSetAllocator>
TMapBase & operator= (TMapBase< KeyType, ValueType, OtherSetAllocator, KeyFuncs > &&Other)
Assignment operator for moving elements from a TMap with a different SetAllocator.
bool operator== (FIntrusiveUnsetOptionalState Tag) const
Static Protected Attributes
static constexpr bool bHasIntrusiveUnsetOptionalState = true
Static Protected Attributes inherited from TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >
static constexpr bool bHasIntrusiveUnsetOptionalState = true
Additional Inherited Members
Public Types inherited from TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >
typedef TPair< KeyType, ValueType > ElementType
typedef TTypeTraits< KeyType >::ConstPointerType KeyConstPointerType
typedef TTypeTraits< KeyType >::ConstInitType KeyInitType
using TRangedForConstIterator = TBaseIterator<true, true>
using TRangedForIterator = TBaseIterator<false, true>
typedef TTypeTraits< ValueType >::ConstInitType ValueInitType
Static Public Member Functions inherited from TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >
static void AppendHash (const FPlatformTypeLayoutParameters &LayoutParams, FSHA1 &Hasher)
Protected Attributes inherited from TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >
ElementSetType Pairs
A set of the key-value pairs in the map.
Detailed Description
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs>
class TSortableMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >
The base type of sortable maps.
Definition at line 1134 of file Map.h.
Member Typedef Documentation
IntrusiveUnsetOptionalStateType
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> using TSortableMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::IntrusiveUnsetOptionalStateType = TSortableMapBase protected
Definition at line 1179 of file Map.h.
Super
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> typedef TMapBase<KeyType, ValueType, SetAllocator, KeyFuncs> TSortableMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Super protected
Definition at line 1137 of file Map.h.
Constructor & Destructor Documentation
TSortableMapBase() [1/6]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> TSortableMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::TSortableMapBase () nodiscard protected default
Referenced by TSortableMapBase(), TSortableMapBase(), TSortableMapBase(), TSortableMapBase(), operator=(), operator=(), operator=(), and operator=().
TSortableMapBase() [2/6]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> TSortableMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::TSortableMapBase (TSortableMapBase< KeyType, ValueType, SetAllocator, KeyFuncs > &&) nodiscard protected default
References TSortableMapBase().
TSortableMapBase() [3/6]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> TSortableMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::TSortableMapBase (const TSortableMapBase< KeyType, ValueType, SetAllocator, KeyFuncs > &) nodiscard protected default
References TSortableMapBase().
TSortableMapBase() [4/6]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> template<typename OtherSetAllocator> TSortableMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::TSortableMapBase (TSortableMapBase< KeyType, ValueType, OtherSetAllocator, KeyFuncs > && Other) inline nodiscard protected
Constructor for moving elements from a TMap with a different SetAllocator.
Definition at line 1147 of file Map.h.
References TSortableMapBase(), MoveTemp(), and Other.
TSortableMapBase() [5/6]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> template<typename OtherSetAllocator> TSortableMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::TSortableMapBase (const TSortableMapBase< KeyType, ValueType, OtherSetAllocator, KeyFuncs > & Other) inline nodiscard protected
Constructor for copying elements from a TMap with a different SetAllocator.
Definition at line 1154 of file Map.h.
References TSortableMapBase(), and Other.
TSortableMapBase() [6/6]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> TSortableMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::TSortableMapBase (FIntrusiveUnsetOptionalState Tag) inline explicit nodiscard protected
Definition at line 1181 of file Map.h.
Member Function Documentation
KeySort()
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> template<typename PREDICATE_CLASS> FORCEINLINE void TSortableMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::KeySort (const PREDICATE_CLASS & Predicate) inline
Sorts the pairs array using each pair's Key as the sort criteria, then rebuilds the map's hash.
Invoked using "MyMapVar.KeySort(PREDICATE_CLASS());"
Definition at line 1199 of file Map.h.
References FORCEINLINE, TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Pairs, and Predicate.
KeyStableSort()
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> template<typename PREDICATE_CLASS> FORCEINLINE void TSortableMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::KeyStableSort (const PREDICATE_CLASS & Predicate) inline
Stable sorts the pairs array using each pair's Key as the sort criteria, then rebuilds the map's hash.
Invoked using "MyMapVar.KeySort(PREDICATE_CLASS());"
Definition at line 1209 of file Map.h.
References FORCEINLINE, TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Pairs, and Predicate.
operator=() [1/4]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> TSortableMapBase & TSortableMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::operator= (const TSortableMapBase< KeyType, ValueType, SetAllocator, KeyFuncs > &) protected default
References TSortableMapBase().
operator=() [2/4]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> template<typename OtherSetAllocator> TSortableMapBase & TSortableMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::operator= (const TSortableMapBase< KeyType, ValueType, OtherSetAllocator, KeyFuncs > & Other) inline protected
Assignment operator for copying elements from a TMap with a different SetAllocator.
Definition at line 1169 of file Map.h.
References TSortableMapBase(), and Other.
operator=() [3/4]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> TSortableMapBase & TSortableMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::operator= (TSortableMapBase< KeyType, ValueType, SetAllocator, KeyFuncs > &&) protected default
References TSortableMapBase().
operator=() [4/4]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> template<typename OtherSetAllocator> TSortableMapBase & TSortableMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::operator= (TSortableMapBase< KeyType, ValueType, OtherSetAllocator, KeyFuncs > && Other) inline protected
Assignment operator for moving elements from a TMap with a different SetAllocator.
Definition at line 1161 of file Map.h.
References TSortableMapBase(), MoveTemp(), and Other.
operator==()
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> bool TSortableMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::operator== (FIntrusiveUnsetOptionalState Tag) const inline nodiscard protected
Definition at line 1185 of file Map.h.
References TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::operator==().
Referenced by TConstKeyIterator< FFixedObjectBindingID, FName >::operator==(), and TMap< FName, TInstancedStruct< FAnimNextModuleInstanceComponent > >::operator==().
SortFreeList()
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> void TSortableMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::SortFreeList () inline
Sort the free element list so that subsequent additions will occur in the lowest available TSet index resulting in tighter packing without moving any existing items.
Also useful for some types of determinism.
See also
TSparseArray::SortFreeList() for more info.
Definition at line 1239 of file Map.h.
References TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Pairs.
ValueSort()
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> template<typename PREDICATE_CLASS> FORCEINLINE void TSortableMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::ValueSort (const PREDICATE_CLASS & Predicate) inline
Sorts the pairs array using each pair's Value as the sort criteria, then rebuilds the map's hash.
Invoked using "MyMapVar.ValueSort(PREDICATE_CLASS());"
Definition at line 1219 of file Map.h.
References FORCEINLINE, TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Pairs, and Predicate.
ValueStableSort()
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> template<typename PREDICATE_CLASS> FORCEINLINE void TSortableMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::ValueStableSort (const PREDICATE_CLASS & Predicate) inline
Stable sorts the pairs array using each pair's Value as the sort criteria, then rebuilds the map's hash.
Invoked using "MyMapVar.ValueSort(PREDICATE_CLASS());"
Definition at line 1229 of file Map.h.
References FORCEINLINE, TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Pairs, and Predicate.
Field Documentation
bHasIntrusiveUnsetOptionalState
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> bool TSortableMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::bHasIntrusiveUnsetOptionalState = true static constexpr protected
Definition at line 1178 of file Map.h.
The documentation for this class was generated from the following file:
Runtime/Core/Public/Containers/Map.h