Unreal Engine 5.6 C++ API: FWorkspaceItem Class Reference
FWorkspaceItem Class Reference
#include "WorkspaceItem.h"
Data Structures
struct FWorkspaceItemSort
Public Member Functions
virtual PRAGMA_DISABLE_DEPRECATION_WARNINGS ~FWorkspaceItem ()
TSharedRef< FWorkspaceItem > AddGroup (const FName &InName, const FText &InDisplayName, const FSlateIcon &InIcon=FSlateIcon(), const bool InSortChildren=false)
TSharedRef< FWorkspaceItem > AddGroup (const FName &InName, const FText &InDisplayName, const FText &InTooltipText, const FSlateIcon &InIcon=FSlateIcon(), const bool InSortChildren=false)
TSharedRef< FWorkspaceItem > AddGroup (const FText &InDisplayName, const FSlateIcon &InIcon=FSlateIcon(), const bool InSortChildren=false)
TSharedRef< FWorkspaceItem > AddGroup (const FText &InDisplayName, const FText &InTooltipText, const FSlateIcon &InIcon=FSlateIcon(), const bool InSortChildren=false)
void AddItem (const TSharedRef< FWorkspaceItem > &ItemToAdd)
virtual TSharedPtr< FTabSpawnerEntry > AsSpawnerEntry ()
void ClearItems ()
const TArray< TSharedRef< FWorkspaceItem > > & GetChildItems () const
const FText & GetDisplayName () const
const FName GetFName () const
const FSlateIcon & GetIcon () const
TSharedPtr< FWorkspaceItem > GetParent () const
const FText & GetTooltipText () const
bool HasChildrenIn (const TArray< TWeakPtr< FTabSpawnerEntry > > &AllowedSpawners)
void RemoveItem (const TSharedRef< FWorkspaceItem > &ItemToRemove)
void SortChildren ()
Public Member Functions inherited from TSharedFromThis< FWorkspaceItem >
TSharedRef< FWorkspaceItem, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FWorkspaceItem, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Static Public Member Functions
static TSharedRef< FWorkspaceItem > NewGroup (const FName &Name, const FText &DisplayName, const FSlateIcon &Icon=FSlateIcon(), const bool bSortChildren=false)
static TSharedRef< FWorkspaceItem > NewGroup (const FName &Name, const FText &DisplayName, const FText &TooltipText, const FSlateIcon &Icon=FSlateIcon(), const bool bSortChildren=false)
static TSharedRef< FWorkspaceItem > NewGroup (const FText &DisplayName, const FSlateIcon &Icon=FSlateIcon(), const bool bSortChildren=false)
static TSharedRef< FWorkspaceItem > NewGroup (const FText &DisplayName, const FText &TooltipText, const FSlateIcon &Icon=FSlateIcon(), const bool bSortChildren=false)
Protected Member Functions
FWorkspaceItem (const FName &InName, const FText &InDisplayName, const FSlateIcon &InIcon, const bool bInSortChildren)
FWorkspaceItem (const FName &InName, const FText &InDisplayName, const FText &InTooltipText, const FSlateIcon &InIcon, const bool bInSortChildren)
FWorkspaceItem (const FText &InDisplayName, const FSlateIcon &InIcon, const bool bInSortChildren)
FWorkspaceItem (const FText &InDisplayName, const FText &InTooltipText, const FSlateIcon &InIcon, const bool bInSortChildren)
UE_DEPRECATED (5.0, "Use DisplayNameAttribute instead.") FText DisplayName
UE_DEPRECATED (5.0, "Use TooltipTextAttribute instead.") FText TooltipText
Protected Member Functions inherited from TSharedFromThis< FWorkspaceItem >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Protected Attributes
bool bSortChildren
TArray< TSharedRef< FWorkspaceItem > > ChildItems
TAttribute< FText > DisplayNameAttribute
FSlateIcon Icon
TAttribute< FName > NameAttribute
TWeakPtr< FWorkspaceItem > ParentItem
TAttribute< FText > TooltipTextAttribute
Friends
template<typename ObjectType, ESPMode Mode>
class SharedPointerInternals::TIntrusiveReferenceController
Additional Inherited Members
Static Protected Member Functions inherited from TSharedFromThis< FWorkspaceItem >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
Definition at line 12 of file WorkspaceItem.h.
Constructor & Destructor Documentation
~FWorkspaceItem()
virtual PRAGMA_DISABLE_DEPRECATION_WARNINGS FWorkspaceItem::~FWorkspaceItem () inline virtual
Definition at line 173 of file WorkspaceItem.h.
FWorkspaceItem() [1/4]
FWorkspaceItem::FWorkspaceItem (const FText & InDisplayName, const FSlateIcon & InIcon, const bool bInSortChildren) inline protected
Definition at line 179 of file WorkspaceItem.h.
References bSortChildren, DisplayNameAttribute, Icon, and NameAttribute.
Referenced by FTabSpawnerEntry::FTabSpawnerEntry().
FWorkspaceItem() [2/4]
FWorkspaceItem::FWorkspaceItem (const FName & InName, const FText & InDisplayName, const FSlateIcon & InIcon, const bool bInSortChildren) inline protected
Definition at line 187 of file WorkspaceItem.h.
References bSortChildren, DisplayNameAttribute, Icon, InName, and NameAttribute.
FWorkspaceItem() [3/4]
FWorkspaceItem::FWorkspaceItem (const FText & InDisplayName, const FText & InTooltipText, const FSlateIcon & InIcon, const bool bInSortChildren) inline protected
Definition at line 195 of file WorkspaceItem.h.
References bSortChildren, DisplayNameAttribute, Icon, NameAttribute, and TooltipTextAttribute.
FWorkspaceItem() [4/4]
FWorkspaceItem::FWorkspaceItem (const FName & InName, const FText & InDisplayName, const FText & InTooltipText, const FSlateIcon & InIcon, const bool bInSortChildren) inline protected
Definition at line 204 of file WorkspaceItem.h.
References bSortChildren, DisplayNameAttribute, Icon, InName, NameAttribute, and TooltipTextAttribute.
Member Function Documentation
AddGroup() [1/4]
TSharedRef< FWorkspaceItem > FWorkspaceItem::AddGroup (const FName & InName, const FText & InDisplayName, const FSlateIcon & InIcon = FSlateIcon(), const bool InSortChildren = false) inline
Definition at line 62 of file WorkspaceItem.h.
References AddItem(), InName, and NewGroup().
AddGroup() [2/4]
TSharedRef< FWorkspaceItem > FWorkspaceItem::AddGroup (const FName & InName, const FText & InDisplayName, const FText & InTooltipText, const FSlateIcon & InIcon = FSlateIcon(), const bool InSortChildren = false) inline
Definition at line 76 of file WorkspaceItem.h.
References AddItem(), InName, and NewGroup().
AddGroup() [3/4]
TSharedRef< FWorkspaceItem > FWorkspaceItem::AddGroup (const FText & InDisplayName, const FSlateIcon & InIcon = FSlateIcon(), const bool InSortChildren = false) inline
Definition at line 55 of file WorkspaceItem.h.
References AddItem(), and NewGroup().
AddGroup() [4/4]
TSharedRef< FWorkspaceItem > FWorkspaceItem::AddGroup (const FText & InDisplayName, const FText & InTooltipText, const FSlateIcon & InIcon = FSlateIcon(), const bool InSortChildren = false) inline
Definition at line 69 of file WorkspaceItem.h.
References AddItem(), and NewGroup().
AddItem()
void FWorkspaceItem::AddItem (const TSharedRef< FWorkspaceItem > & ItemToAdd) inline
Definition at line 108 of file WorkspaceItem.h.
References bSortChildren, ChildItems, ParentItem, TSharedFromThis< FWorkspaceItem >::SharedThis(), and SortChildren().
Referenced by AddGroup(), AddGroup(), AddGroup(), and AddGroup().
AsSpawnerEntry()
virtual TSharedPtr< FTabSpawnerEntry > FWorkspaceItem::AsSpawnerEntry () inline virtual
Reimplemented in FTabSpawnerEntry.
Definition at line 141 of file WorkspaceItem.h.
Referenced by HasChildrenIn().
ClearItems()
void FWorkspaceItem::ClearItems () inline
Definition at line 131 of file WorkspaceItem.h.
References ChildItems.
GetChildItems()
const TArray< TSharedRef< FWorkspaceItem > > & FWorkspaceItem::GetChildItems () const inline
Definition at line 103 of file WorkspaceItem.h.
References ChildItems.
GetDisplayName()
const FText & FWorkspaceItem::GetDisplayName () const inline
Definition at line 88 of file WorkspaceItem.h.
References DisplayNameAttribute.
GetFName()
const FName FWorkspaceItem::GetFName () const inline
Definition at line 83 of file WorkspaceItem.h.
References NameAttribute.
GetIcon()
const FSlateIcon & FWorkspaceItem::GetIcon () const inline
Definition at line 98 of file WorkspaceItem.h.
References Icon.
GetParent()
TSharedPtr< FWorkspaceItem > FWorkspaceItem::GetParent () const inline
Definition at line 147 of file WorkspaceItem.h.
References ParentItem.
GetTooltipText()
const FText & FWorkspaceItem::GetTooltipText () const inline
Definition at line 93 of file WorkspaceItem.h.
References TooltipTextAttribute.
HasChildrenIn()
bool FWorkspaceItem::HasChildrenIn (const TArray< TWeakPtr< FTabSpawnerEntry > > & AllowedSpawners) inline
Definition at line 152 of file WorkspaceItem.h.
References AsSpawnerEntry(), ChildItems, TSharedPtr< ObjectType, InMode >::IsValid(), and TSharedPtr< ObjectType, InMode >::ToSharedRef().
NewGroup() [1/4]
TSharedRef< FWorkspaceItem > FWorkspaceItem::NewGroup (const FName & Name, const FText & DisplayName, const FSlateIcon & Icon = FSlateIcon(), const bool bSortChildren = false) inline static
Definition at line 40 of file WorkspaceItem.h.
References bSortChildren, Icon, MakeShared(), and Name.
NewGroup() [2/4]
TSharedRef< FWorkspaceItem > FWorkspaceItem::NewGroup (const FName & Name, const FText & DisplayName, const FText & TooltipText, const FSlateIcon & Icon = FSlateIcon(), const bool bSortChildren = false) inline static
Definition at line 50 of file WorkspaceItem.h.
References bSortChildren, Icon, MakeShared(), and Name.
NewGroup() [3/4]
TSharedRef< FWorkspaceItem > FWorkspaceItem::NewGroup (const FText & DisplayName, const FSlateIcon & Icon = FSlateIcon(), const bool bSortChildren = false) inline static
Definition at line 35 of file WorkspaceItem.h.
References bSortChildren, Icon, and MakeShared().
Referenced by AddGroup(), AddGroup(), AddGroup(), and AddGroup().
NewGroup() [4/4]
TSharedRef< FWorkspaceItem > FWorkspaceItem::NewGroup (const FText & DisplayName, const FText & TooltipText, const FSlateIcon & Icon = FSlateIcon(), const bool bSortChildren = false) inline static
Definition at line 45 of file WorkspaceItem.h.
References bSortChildren, Icon, and MakeShared().
RemoveItem()
void FWorkspaceItem::RemoveItem (const TSharedRef< FWorkspaceItem > & ItemToRemove) inline
Definition at line 126 of file WorkspaceItem.h.
References ChildItems.
SortChildren()
void FWorkspaceItem::SortChildren () inline
Definition at line 136 of file WorkspaceItem.h.
References ChildItems.
Referenced by AddItem().
UE_DEPRECATED() [1/2]
FWorkspaceItem::UE_DEPRECATED (5. 0, "Use DisplayNameAttribute instead.") protected
Referenced by UE_DEPRECATED().
UE_DEPRECATED() [2/2]
FWorkspaceItem::UE_DEPRECATED (5. 0, "Use TooltipTextAttribute instead.") protected
References UE_DEPRECATED().
Friends And Related Symbol Documentation
SharedPointerInternals::TIntrusiveReferenceController
template<typename ObjectType, ESPMode Mode> friend class SharedPointerInternals::TIntrusiveReferenceController friend
Definition at line 229 of file WorkspaceItem.h.
References SharedPointerInternals::TIntrusiveReferenceController.
Referenced by SharedPointerInternals::TIntrusiveReferenceController.
Field Documentation
bSortChildren
bool FWorkspaceItem::bSortChildren protected
Definition at line 221 of file WorkspaceItem.h.
Referenced by FWorkspaceItem(), FWorkspaceItem(), FWorkspaceItem(), FWorkspaceItem(), AddItem(), NewGroup(), NewGroup(), NewGroup(), and NewGroup().
ChildItems
TArray< TSharedRef<FWorkspaceItem> > FWorkspaceItem::ChildItems protected
Definition at line 223 of file WorkspaceItem.h.
Referenced by AddItem(), ClearItems(), GetChildItems(), HasChildrenIn(), RemoveItem(), and SortChildren().
DisplayNameAttribute
TAttribute<FText> FWorkspaceItem::DisplayNameAttribute protected
Definition at line 215 of file WorkspaceItem.h.
Referenced by FWorkspaceItem(), FWorkspaceItem(), FWorkspaceItem(), FWorkspaceItem(), GetDisplayName(), FTabSpawnerEntry::SetDisplayName(), and FTabSpawnerEntry::SetDisplayNameAttribute().
Icon
FSlateIcon FWorkspaceItem::Icon protected
Definition at line 213 of file WorkspaceItem.h.
Referenced by FWorkspaceItem(), FWorkspaceItem(), FWorkspaceItem(), FWorkspaceItem(), GetIcon(), NewGroup(), NewGroup(), NewGroup(), NewGroup(), and FTabSpawnerEntry::SetIcon().
NameAttribute
TAttribute<FName> FWorkspaceItem::NameAttribute protected
Definition at line 214 of file WorkspaceItem.h.
Referenced by FWorkspaceItem(), FWorkspaceItem(), FWorkspaceItem(), FWorkspaceItem(), and GetFName().
ParentItem
TWeakPtr<FWorkspaceItem> FWorkspaceItem::ParentItem protected
Definition at line 225 of file WorkspaceItem.h.
Referenced by AddItem(), and GetParent().
TooltipTextAttribute
TAttribute<FText> FWorkspaceItem::TooltipTextAttribute protected
Definition at line 216 of file WorkspaceItem.h.
Referenced by FWorkspaceItem(), FWorkspaceItem(), GetTooltipText(), FTabSpawnerEntry::SetTooltipText(), and FTabSpawnerEntry::SetTooltipTextAttribute().
The documentation for this class was generated from the following file:
Runtime/Slate/Public/Framework/Docking/WorkspaceItem.h