Unreal Engine 5.6 C++ API: FBlueprintAssetHandler Class Reference
FBlueprintAssetHandler Class Reference
Singleton class that marshals different blueprint asset handlers for different asset class types.
#include "BlueprintAssetHandler.h"
Public Member Functions
KISMET_API const IBlueprintAssetHandler * FindHandler (const UClass *InClass) const
Find a handler that applies to the specified class.
TArrayView< const FTopLevelAssetPath > GetRegisteredClassNames () const
Get all the currently registered class names.
template<typename HandlerType>
void RegisterHandler (FTopLevelAssetPath ClassPathName)
Register an asset for the specified class name.
KISMET_API void RegisterHandler (FTopLevelAssetPath ClassPathName, TUniquePtr< IBlueprintAssetHandler > &&InHandler)
Register an asset for the specified class name.
Static Public Member Functions
static KISMET_API FBlueprintAssetHandler & Get ()
Retrieve the singleton instance of this class.
Private Member Functions
FBlueprintAssetHandler ()
Private constructor - use singleton accessor (Get)
Private Attributes
TArray< FTopLevelAssetPath > ClassNames
Unsorted array of class names, one per-handler below.
TArray< TUniquePtr< IBlueprintAssetHandler > > Handlers
Array of handlers that relate to the class names above.
Detailed Description
Singleton class that marshals different blueprint asset handlers for different asset class types.
Definition at line 48 of file BlueprintAssetHandler.h.
Constructor & Destructor Documentation
FBlueprintAssetHandler()
FBlueprintAssetHandler::FBlueprintAssetHandler () private
Private constructor - use singleton accessor (Get)
Referenced by Get().
Member Function Documentation
FindHandler()
KISMET_API const IBlueprintAssetHandler * FBlueprintAssetHandler::FindHandler (const UClass * InClass) const
Find a handler that applies to the specified class.
Parameters
InClass The class to find a handler for
Returns
A valid asset handler, or nullptr if none exists for this class
Get()
KISMET_API FBlueprintAssetHandler & FBlueprintAssetHandler::Get () static
Retrieve the singleton instance of this class.
References FBlueprintAssetHandler().
GetRegisteredClassNames()
TArrayView< const FTopLevelAssetPath > FBlueprintAssetHandler::GetRegisteredClassNames () const inline
Get all the currently registered class names.
Definition at line 61 of file BlueprintAssetHandler.h.
References ClassNames.
RegisterHandler() [1/2]
template<typename HandlerType> void FBlueprintAssetHandler::RegisterHandler (FTopLevelAssetPath ClassPathName) inline
Register an asset for the specified class name.
Note
: Any assets whose class is a child of the specified class will use this handler (unless there is a more specific handler registered)
Parameters
ClassName The name of the class this handler relates to.
Definition at line 74 of file BlueprintAssetHandler.h.
References MakeUnique(), and RegisterHandler().
Referenced by RegisterHandler().
RegisterHandler() [2/2]
KISMET_API void FBlueprintAssetHandler::RegisterHandler (FTopLevelAssetPath ClassPathName, TUniquePtr< IBlueprintAssetHandler > && InHandler)
Register an asset for the specified class name.
Note
: Any assets whose class is a child of the specified class will use this handler (unless there is a more specific handler registered)
Parameters
ClassPathName The path name of the class this handler relates to.
InHandler The implementation of the handler to use
Field Documentation
ClassNames
TArray<FTopLevelAssetPath> FBlueprintAssetHandler::ClassNames private
Unsorted array of class names, one per-handler below.
Definition at line 105 of file BlueprintAssetHandler.h.
Referenced by GetRegisteredClassNames().
Handlers
TArray<TUniquePtr<IBlueprintAssetHandler> > FBlueprintAssetHandler::Handlers private
Array of handlers that relate to the class names above.
Definition at line 108 of file BlueprintAssetHandler.h.
The documentation for this class was generated from the following file:
Editor/Kismet/Public/BlueprintAssetHandler.h