Unreal Engine 5.6 C++ API: UE::FRecursiveMutex Class Reference
UE::FRecursiveMutex Class Reference final
An eight-byte mutex that is not fair and supports recursive locking.
#include "RecursiveMutex.h"
Public Member Functions
constexpr FRecursiveMutex ()=default
FRecursiveMutex (const FRecursiveMutex &)=delete
void Lock ()
FRecursiveMutex & operator= (const FRecursiveMutex &)=delete
bool TryLock ()
void Unlock ()
Private Member Functions
void LockSlow (uint32 CurrentState, uint32 CurrentThreadId)
void WakeWaitingThread ()
Private Attributes
std::atomic< uint32 > State = 0
std::atomic< uint32 > ThreadId = 0
Static Private Attributes
static constexpr uint32 LockCountMask = 0xffff'fffe
static constexpr uint32 LockCountShift = 1
static constexpr uint32 MayHaveWaitingLockFlag = 1 << 0
Detailed Description
An eight-byte mutex that is not fair and supports recursive locking.
Prefer FMutex when recursive locking is not required.
Definition at line 18 of file RecursiveMutex.h.
Constructor & Destructor Documentation
FRecursiveMutex() [1/2]
UE::FRecursiveMutex::FRecursiveMutex () constexpr default
Referenced by FRecursiveMutex(), and operator=().
FRecursiveMutex() [2/2]
UE::FRecursiveMutex::FRecursiveMutex (const FRecursiveMutex &) delete
References FRecursiveMutex().
Member Function Documentation
Lock()
void UE::FRecursiveMutex::Lock ()
References UE_API.
LockSlow()
void UE::FRecursiveMutex::LockSlow (uint32 CurrentState, uint32 CurrentThreadId) private
operator=()
FRecursiveMutex & UE::FRecursiveMutex::operator= (const FRecursiveMutex &) delete
References FRecursiveMutex().
TryLock()
bool UE::FRecursiveMutex::TryLock ()
References UE_API.
Unlock()
void UE::FRecursiveMutex::Unlock ()
References UE_API.
WakeWaitingThread()
void UE::FRecursiveMutex::WakeWaitingThread () private
Field Documentation
LockCountMask
uint32 UE::FRecursiveMutex::LockCountMask = 0xffff'fffe static constexpr private
Definition at line 36 of file RecursiveMutex.h.
LockCountShift
uint32 UE::FRecursiveMutex::LockCountShift = 1 static constexpr private
Definition at line 35 of file RecursiveMutex.h.
MayHaveWaitingLockFlag
uint32 UE::FRecursiveMutex::MayHaveWaitingLockFlag = 1 << 0 static constexpr private
Definition at line 34 of file RecursiveMutex.h.
State
std::atomic<uint32> UE::FRecursiveMutex::State = 0 private
Definition at line 38 of file RecursiveMutex.h.
ThreadId
std::atomic<uint32> UE::FRecursiveMutex::ThreadId = 0 private
Definition at line 39 of file RecursiveMutex.h.
The documentation for this class was generated from the following file:
Runtime/Core/Public/Async/RecursiveMutex.h