Unreal Engine 5.6 C++ API: UEdGraphPin Class Reference
UEdGraphPin Class Reference
#include "EdGraphPin.h"
Public Member Functions
~UEdGraphPin ()
Destructor.
void AddStructReferencedObjects (class FReferenceCollector &Collector)
Provides a reference collector with all object references this pin has.
void AssignByRefPassThroughConnection (UEdGraphPin *InTargetPin)
Connects the two pins as by-ref pass-through, allowing the input to auto-forward to the output pin.
void BreakAllPinLinks (bool bNotifyNodes=false, bool bAlwaysMarkDirty=true)
Break all links from this pin.
void BreakLinkTo (UEdGraphPin *ToPin, bool bAlwaysMarkDirty=true)
Break a link to the specified pin (if present)
void CopyPersistentDataFromOldPin (const UEdGraphPin &SourcePin)
Copies the persistent data (across a node refresh) from the SourcePin.
bool DoesDefaultValueMatchAutogenerated () const
Returns true if the current default value matches the autogenerated default value.
bool ExportTextItem (FString &ValueStr, int32 PortFlags) const
ExportText/ImportText.
FString GetDefaultAsString () const
Returns an internal string representation of the string/object/text default value, that is compatible with AutogeneratedDefaultValue and ImportText.
FText GetDefaultAsText () const
Returns a human readable FText representation of the string/object/text default value.
const FName GetFName () const
const FString GetLinkInfoString (const FString &InFunctionName, const FString &InInfoData, const UEdGraphPin *InToPin) const
Generate a string detailing the link this pin has to another pin.
const FString GetName () const
UEdGraphNode * GetOuter () const
FORCEINLINE class UEdGraphNode * GetOwningNode () const
Returns the node that owns this pin.
FORCEINLINE class UEdGraphNode * GetOwningNodeUnchecked () const
FEdGraphTerminalType GetPrimaryTerminalType () const
const class UEdGraphSchema * GetSchema () const
Shorthand way to access the schema of the graph that owns the node that owns this pin.
bool HasAnyConnections () const
Returns true if there are entries in the pin's LinkedTo array, or if it has SubPins, one of their SubPins arrays:
bool ImportTextItem (const TCHAR *&Buffer, int32 PortFlags, class UObject *Parent, FOutputDevice *ErrorText)
bool IsDefaultAsStringEmpty () const
Returns true if GetDefaultAsString will return an empty string.
bool IsPendingKill () const
void MakeLinkTo (UEdGraphPin *ToPin, bool bAlwaysMarkDirty=true)
Create a link.
void MarkAsGarbage ()
Marks the pin as 'trashed'.
bool Modify (bool bAlwaysMarkDirty=true)
Marks the owning node as modified.
void MovePersistentDataFromOldPin (UEdGraphPin &SourcePin)
Moves the persistent data (across a node refresh) from the SourcePin.
void ResetDefaultValue ()
Reset default values to empty.
void ResetToDefaults ()
Resets node to default constructor state.
void SafeSetHidden (bool bIsHidden)
Helper to safely set a pin's bHidden property only if it has no sub-pins that are influencing it to be hidden.
void SetOwningNode (UEdGraphNode *NewOwningNode)
Changes the owning node.
FORCEINLINE bool WasTrashed () const
Returns true if InvalidateAndTrash was ever called on this pin.
Static Public Member Functions
static bool AreOrphanPinsEnabled ()
static UEdGraphPin * CreatePin (UEdGraphNode *InOwningNode)
Creates a new pin.
static UEdGraphPin * CreatePinFromDeprecatedPin (class UEdGraphPin_Deprecated *DeprecatedPin)
Transition support for UEdGraphPins.
static UEdGraphPin * FindPinCreatedFromDeprecatedPin (class UEdGraphPin_Deprecated *DeprecatedPin)
static EEdGraphPinDirection GetComplementaryDirection (EEdGraphPinDirection InDirection)
Direction flipping utility; returns the complementary direction.
static void Purge ()
static void ResolveAllPinReferences ()
This needs to be called if you want to use pin data within PostEditUndo.
static void SanitizePinsPostUndoRedo ()
static void SerializeAsOwningNode (FArchive &Ar, TArray< UEdGraphPin * > &ArrayRef)
Serializes an array of pins as the owner.
static void ShutdownVerification ()
Verification that all pins have been destroyed after shutting down.
Data Fields
FString AutogeneratedDefaultValue
Initial default value (the autogenerated value, to identify if the user has modified the value), stored as a string.
uint8 bWasTrashed:1
True when InvalidateAndTrash was called.
TObjectPtr< class UObject > DefaultObject
If the default value for this pin should be an object, we store a pointer to it.
FText DefaultTextValue
If the default value for this pin should be an FText, it is stored here.
FString DefaultValue
Default value for this pin (used if the pin has no connections), stored as a string.
TEnumAsByte< enum EEdGraphPinDirection > Direction
Direction of flow of this pin (input or output)
TArray< UEdGraphPin * > LinkedTo
Set of pins that we are linked to.
UEdGraphPin * ParentPin
The pin that was split and generated this pin.
FGuid PinId
The pin's unique ID.
FName PinName
Name of this pin.
FString PinToolTip
Used as the display name if set.
FEdGraphPinType PinType
The type of information carried on this pin.
UEdGraphPin * ReferencePassThroughConnection
Pin that this pin uses for passing through reference connection.
int32 SourceIndex
Index of the pin in the source data structure represented by the graph, INDEX_NONE if not used.
TArray< UEdGraphPin * > SubPins
The pins created when a pin is split and hidden.
Private Member Functions
UEdGraphPin (UEdGraphNode *InOwningNode, const FGuid &PinGuid)
Private Constructor.
void DestroyImpl (bool bClearLinks)
Helper function for common destruction logic.
void InitFromDeprecatedPin (class UEdGraphPin_Deprecated *DeprecatedPin)
Backward compatibility code to populate this pin with data from the supplied deprecated UEdGraphPin.
bool Serialize (FArchive &Ar)
Static Private Member Functions
static void ConvertConnectedGhostNodesToRealNodes (UEdGraphNode *InNode, bool bAlwaysMarkDirty=true)
static FString ExportText_PinArray (const TArray< UEdGraphPin * > &PinArray)
static FString ExportText_PinReference (const UEdGraphPin *Pin)
static bool ImportText_PinArray (const TCHAR *&Buffer, TArray< UEdGraphPin * > &ArrayRef, UEdGraphPin *RequestingPin, EPinResolveType ResolveType)
static void ResolveReferencesToPin (UEdGraphPin *Pin, bool bStrictValidation=true)
static bool SerializePin (FArchive &Ar, UEdGraphPin *&PinRef, int32 ArrayIdx, UEdGraphPin *RequestingPin, EPinResolveType ResolveType, TArray< UEdGraphPin * > &OldPins)
static void SerializePinArray (FArchive &Ar, TArray< UEdGraphPin * > &ArrayRef, UEdGraphPin *RequestingPin, EPinResolveType ResolveType)
Private Attributes
UEdGraphNode * OwningNode
The node that owns this pin.
Friends
struct FEdGraphPinReference
Detailed Description
Definition at line 283 of file EdGraphPin.h.
Constructor & Destructor Documentation
~UEdGraphPin()
UEdGraphPin::~UEdGraphPin ()
Destructor.
UEdGraphPin()
UEdGraphPin::UEdGraphPin (UEdGraphNode * InOwningNode, const FGuid & PinGuid) private
Private Constructor.
Create pins using CreatePin since all pin instances are managed by TSharedPtr.
Referenced by AssignByRefPassThroughConnection(), BreakLinkTo(), CopyPersistentDataFromOldPin(), CreatePin(), CreatePinFromDeprecatedPin(), ExportText_PinReference(), FindPinCreatedFromDeprecatedPin(), GetLinkInfoString(), ImportText_PinArray(), MakeLinkTo(), MovePersistentDataFromOldPin(), ResolveReferencesToPin(), SerializePin(), and SerializePinArray().
Member Function Documentation
AddStructReferencedObjects()
void UEdGraphPin::AddStructReferencedObjects (class FReferenceCollector & Collector)
Provides a reference collector with all object references this pin has.
Should only be called by the owning node.
AreOrphanPinsEnabled()
bool UEdGraphPin::AreOrphanPinsEnabled () static
AssignByRefPassThroughConnection()
void UEdGraphPin::AssignByRefPassThroughConnection (UEdGraphPin * InTargetPin)
Connects the two pins as by-ref pass-through, allowing the input to auto-forward to the output pin.
References UEdGraphPin().
BreakAllPinLinks()
void UEdGraphPin::BreakAllPinLinks (bool bNotifyNodes = false, bool bAlwaysMarkDirty = true)
Break all links from this pin.
Referenced by FAnimGraphNodeAlphaOptions::HandlePostEditChangeProperty().
BreakLinkTo()
void UEdGraphPin::BreakLinkTo (UEdGraphPin * ToPin, bool bAlwaysMarkDirty = true)
Break a link to the specified pin (if present)
References UEdGraphPin().
ConvertConnectedGhostNodesToRealNodes()
void UEdGraphPin::ConvertConnectedGhostNodesToRealNodes (UEdGraphNode * InNode, bool bAlwaysMarkDirty = true) static private
CopyPersistentDataFromOldPin()
void UEdGraphPin::CopyPersistentDataFromOldPin (const UEdGraphPin & SourcePin)
Copies the persistent data (across a node refresh) from the SourcePin.
Parameters
SourcePin Source pin.
References UEdGraphPin().
CreatePin()
UEdGraphPin * UEdGraphPin::CreatePin (UEdGraphNode * InOwningNode) static
Creates a new pin.
Should be called from the OwningNode so it can be immediately added to the Pins array.
References UEdGraphPin().
CreatePinFromDeprecatedPin()
UEdGraphPin * UEdGraphPin::CreatePinFromDeprecatedPin (class UEdGraphPin_Deprecated * DeprecatedPin) static
Transition support for UEdGraphPins.
References UEdGraphPin().
DestroyImpl()
void UEdGraphPin::DestroyImpl (bool bClearLinks) private
Helper function for common destruction logic.
DoesDefaultValueMatchAutogenerated()
bool UEdGraphPin::DoesDefaultValueMatchAutogenerated () const
Returns true if the current default value matches the autogenerated default value.
ExportText_PinArray()
FString UEdGraphPin::ExportText_PinArray (const TArray< UEdGraphPin * > & PinArray) static private
ExportText_PinReference()
FString UEdGraphPin::ExportText_PinReference (const UEdGraphPin * Pin) static private
References UEdGraphPin().
ExportTextItem()
bool UEdGraphPin::ExportTextItem (FString & ValueStr, int32 PortFlags) const
ExportText/ImportText.
FindPinCreatedFromDeprecatedPin()
UEdGraphPin * UEdGraphPin::FindPinCreatedFromDeprecatedPin (class UEdGraphPin_Deprecated * DeprecatedPin) static
References UEdGraphPin().
GetComplementaryDirection()
EEdGraphPinDirection UEdGraphPin::GetComplementaryDirection (EEdGraphPinDirection InDirection) inline static
Direction flipping utility; returns the complementary direction.
Definition at line 434 of file EdGraphPin.h.
GetDefaultAsString()
FString UEdGraphPin::GetDefaultAsString () const
Returns an internal string representation of the string/object/text default value, that is compatible with AutogeneratedDefaultValue and ImportText.
Note
Do not directly compare this value with another to test for a default value. Instead use DoesDefaultValueMatch or DoesDefaultValueMatchAutogenerated on the schema.
GetDefaultAsText()
FText UEdGraphPin::GetDefaultAsText () const
Returns a human readable FText representation of the string/object/text default value.
GetFName()
const FName UEdGraphPin::GetFName () const inline
Definition at line 545 of file EdGraphPin.h.
References PinName.
Referenced by FEdGraphPinHandle::FEdGraphPinHandle(), and FEdGraphPinHandle::GetPin().
GetLinkInfoString()
const FString UEdGraphPin::GetLinkInfoString (const FString & InFunctionName, const FString & InInfoData, const UEdGraphPin * InToPin) const
Generate a string detailing the link this pin has to another pin.
@Param InFunctionName String with function name requesting the info @Param InInfoData String detailing the info (EG. Is Not linked to) @Param InToPin The relevant pin
References UEdGraphPin().
GetName()
const FString UEdGraphPin::GetName () const inline
Definition at line 544 of file EdGraphPin.h.
References PinName.
GetOuter()
UEdGraphNode * UEdGraphPin::GetOuter () const inline
Definition at line 546 of file EdGraphPin.h.
References GetOwningNodeUnchecked().
GetOwningNode()
FORCEINLINE class UEdGraphNode * UEdGraphPin::GetOwningNode () const inline
Returns the node that owns this pin.
Definition at line 424 of file EdGraphPin.h.
References check, FORCEINLINE, and OwningNode.
Referenced by FEdGraphPinHandle::FEdGraphPinHandle().
GetOwningNodeUnchecked()
FORCEINLINE class UEdGraphNode * UEdGraphPin::GetOwningNodeUnchecked () const inline
Definition at line 425 of file EdGraphPin.h.
References FORCEINLINE, and OwningNode.
Referenced by GetOuter().
GetPrimaryTerminalType()
FEdGraphTerminalType UEdGraphPin::GetPrimaryTerminalType () const
GetSchema()
const class UEdGraphSchema * UEdGraphPin::GetSchema () const
Shorthand way to access the schema of the graph that owns the node that owns this pin.
Referenced by SGraphPinNumSlider< NumericType >::GetDefaultValueVisibility(), and SRigVMActionMenu::GetSearchContextDesc().
HasAnyConnections()
bool UEdGraphPin::HasAnyConnections () const
Returns true if there are entries in the pin's LinkedTo array, or if it has SubPins, one of their SubPins arrays:
ImportText_PinArray()
bool UEdGraphPin::ImportText_PinArray (const TCHAR *& Buffer, TArray< UEdGraphPin * > & ArrayRef, UEdGraphPin * RequestingPin, EPinResolveType ResolveType) static private
References UEdGraphPin(), and Buffer.
ImportTextItem()
bool UEdGraphPin::ImportTextItem (const TCHAR *& Buffer, int32 PortFlags, class UObject * Parent, FOutputDevice * ErrorText)
References Buffer, and Parent.
InitFromDeprecatedPin()
void UEdGraphPin::InitFromDeprecatedPin (class UEdGraphPin_Deprecated * DeprecatedPin) private
Backward compatibility code to populate this pin with data from the supplied deprecated UEdGraphPin.
IsDefaultAsStringEmpty()
bool UEdGraphPin::IsDefaultAsStringEmpty () const
Returns true if GetDefaultAsString will return an empty string.
IsPendingKill()
bool UEdGraphPin::IsPendingKill () const inline
Definition at line 547 of file EdGraphPin.h.
References bWasTrashed.
Referenced by SGraphPinNumSlider< NumericType >::GetDefaultValueVisibility().
MakeLinkTo()
void UEdGraphPin::MakeLinkTo (UEdGraphPin * ToPin, bool bAlwaysMarkDirty = true)
Create a link.
Note, this does not check that schema allows it, and will not break any existing connections
References UEdGraphPin().
MarkAsGarbage()
void UEdGraphPin::MarkAsGarbage ()
Marks the pin as 'trashed'.
Does not remove the pin from the Owning Node's Pins list
Modify()
bool UEdGraphPin::Modify (bool bAlwaysMarkDirty = true)
Marks the owning node as modified.
MovePersistentDataFromOldPin()
void UEdGraphPin::MovePersistentDataFromOldPin (UEdGraphPin & SourcePin)
Moves the persistent data (across a node refresh) from the SourcePin.
Parameters
SourcePin Source pin.
References UEdGraphPin().
Purge()
void UEdGraphPin::Purge () static
ResetDefaultValue()
void UEdGraphPin::ResetDefaultValue () inline
Reset default values to empty.
This should not be called when AutogeneratedDefaultValue needs to be respected!
Definition at line 482 of file EdGraphPin.h.
References DefaultObject, DefaultTextValue, DefaultValue, and FText::GetEmpty().
Referenced by ResetToDefaults().
ResetToDefaults()
void UEdGraphPin::ResetToDefaults () inline
Resets node to default constructor state.
Definition at line 490 of file EdGraphPin.h.
References AutogeneratedDefaultValue, check, FText::GetEmpty(), INDEX_NONE, LinkedTo, PinName, PinType, ResetDefaultValue(), and SourceIndex.
ResolveAllPinReferences()
void UEdGraphPin::ResolveAllPinReferences () static
This needs to be called if you want to use pin data within PostEditUndo.
ResolveReferencesToPin()
void UEdGraphPin::ResolveReferencesToPin (UEdGraphPin * Pin, bool bStrictValidation = true) static private
References UEdGraphPin().
SafeSetHidden()
void UEdGraphPin::SafeSetHidden (bool bIsHidden) inline
Helper to safely set a pin's bHidden property only if it has no sub-pins that are influencing it to be hidden.
Definition at line 440 of file EdGraphPin.h.
References SubPins.
SanitizePinsPostUndoRedo()
void UEdGraphPin::SanitizePinsPostUndoRedo () static
Serialize()
bool UEdGraphPin::Serialize (FArchive & Ar) private
References Ar.
SerializeAsOwningNode()
void UEdGraphPin::SerializeAsOwningNode (FArchive & Ar, TArray< UEdGraphPin * > & ArrayRef) static
Serializes an array of pins as the owner.
Only the OwningNode should call this function.
References Ar.
SerializePin()
bool UEdGraphPin::SerializePin (FArchive & Ar, UEdGraphPin *& PinRef, int32 ArrayIdx, UEdGraphPin * RequestingPin, EPinResolveType ResolveType, TArray< UEdGraphPin * > & OldPins) static private
References UEdGraphPin(), and Ar.
SerializePinArray()
void UEdGraphPin::SerializePinArray (FArchive & Ar, TArray< UEdGraphPin * > & ArrayRef, UEdGraphPin * RequestingPin, EPinResolveType ResolveType) static private
References UEdGraphPin(), and Ar.
SetOwningNode()
void UEdGraphPin::SetOwningNode (UEdGraphNode * NewOwningNode)
Changes the owning node.
This will remove the pin from the old owning node's pin list and add itself to the new node's pin list.
ShutdownVerification()
void UEdGraphPin::ShutdownVerification () static
Verification that all pins have been destroyed after shutting down.
WasTrashed()
FORCEINLINE bool UEdGraphPin::WasTrashed () const inline
Returns true if InvalidateAndTrash was ever called on this pin.
Definition at line 534 of file EdGraphPin.h.
References bWasTrashed, and FORCEINLINE.
Friends And Related Symbol Documentation
FEdGraphPinReference
friend struct FEdGraphPinReference friend
Definition at line 285 of file EdGraphPin.h.
References FEdGraphPinReference.
Referenced by FEdGraphPinReference.
Field Documentation
AutogeneratedDefaultValue
FString UEdGraphPin::AutogeneratedDefaultValue
Initial default value (the autogenerated value, to identify if the user has modified the value), stored as a string.
Definition at line 366 of file EdGraphPin.h.
Referenced by ResetToDefaults().
bWasTrashed
uint8 UEdGraphPin::bWasTrashed
True when InvalidateAndTrash was called.
This pin is intended to be discarded and destroyed.
Definition at line 350 of file EdGraphPin.h.
Referenced by IsPendingKill(), and WasTrashed().
DefaultObject
TObjectPtr<class UObject> UEdGraphPin::DefaultObject
If the default value for this pin should be an object, we store a pointer to it.
Definition at line 369 of file EdGraphPin.h.
Referenced by ResetDefaultValue().
DefaultTextValue
FText UEdGraphPin::DefaultTextValue
If the default value for this pin should be an FText, it is stored here.
Definition at line 372 of file EdGraphPin.h.
Referenced by ResetDefaultValue().
DefaultValue
FString UEdGraphPin::DefaultValue
Default value for this pin (used if the pin has no connections), stored as a string.
Definition at line 363 of file EdGraphPin.h.
Referenced by ResetDefaultValue().
Direction
TEnumAsByte<enum EEdGraphPinDirection> UEdGraphPin::Direction
Direction of flow of this pin (input or output)
Definition at line 302 of file EdGraphPin.h.
Referenced by FEdGraphPinHandle::FEdGraphPinHandle(), SGraphPinNumSlider< NumericType >::GetDefaultValueVisibility(), FEdGraphPinHandle::GetPin(), and SRigVMActionMenu::GetSearchContextDesc().
LinkedTo
TArray<UEdGraphPin*> UEdGraphPin::LinkedTo
Set of pins that we are linked to.
Definition at line 375 of file EdGraphPin.h.
Referenced by ResetToDefaults().
OwningNode
UEdGraphNode* UEdGraphPin::OwningNode private
The node that owns this pin.
Definition at line 288 of file EdGraphPin.h.
Referenced by GetOwningNode(), and GetOwningNodeUnchecked().
ParentPin
UEdGraphPin* UEdGraphPin::ParentPin
The pin that was split and generated this pin.
Definition at line 381 of file EdGraphPin.h.
PinId
FGuid UEdGraphPin::PinId
The pin's unique ID.
Definition at line 293 of file EdGraphPin.h.
PinName
FName UEdGraphPin::PinName
Name of this pin.
Definition at line 296 of file EdGraphPin.h.
Referenced by GetFName(), GetName(), FAnimGraphNodeAlphaOptions::HandleCustomizePinData(), FAnimGraphNodeAlphaOptions::HandlePostEditChangeProperty(), and ResetToDefaults().
PinToolTip
FString UEdGraphPin::PinToolTip
Used as the display name if set.
The tool-tip describing this pin's purpose
Definition at line 357 of file EdGraphPin.h.
PinType
FEdGraphPinType UEdGraphPin::PinType
The type of information carried on this pin.
Definition at line 360 of file EdGraphPin.h.
Referenced by SRigVMActionMenu::GetSearchContextDesc(), and ResetToDefaults().
ReferencePassThroughConnection
UEdGraphPin* UEdGraphPin::ReferencePassThroughConnection
Pin that this pin uses for passing through reference connection.
Definition at line 384 of file EdGraphPin.h.
SourceIndex
int32 UEdGraphPin::SourceIndex
Index of the pin in the source data structure represented by the graph, INDEX_NONE if not used.
Definition at line 299 of file EdGraphPin.h.
Referenced by ResetToDefaults().
SubPins
TArray<UEdGraphPin*> UEdGraphPin::SubPins
The pins created when a pin is split and hidden.
Definition at line 378 of file EdGraphPin.h.
Referenced by SafeSetHidden().
The documentation for this class was generated from the following file:
Runtime/Engine/Classes/EdGraph/EdGraphPin.h