Unreal Engine 5.6 C++ API: UE::Text::Private::TDisplayStringPtrBase< ObjectType > Class Template Reference
UE::Text::Private::TDisplayStringPtrBase< ObjectType > Class Template Reference
Wrapper to give TRefCountPtr a minimal TSharedRef/TSharedPtr interface for backwards compatibility with code that was already using FTextDisplayStringRef/FTextDisplayStringPtr.
#include "LocalizedTextSourceTypes.h"
Public Member Functions
TDisplayStringPtrBase ()=default
TDisplayStringPtrBase (const TRefCountPtr< FRefCountedDisplayString > &InDisplayStringPtr)
bool IsValid () const
operator bool () const
ObjectType & operator* () const
ObjectType * operator-> () const
const TRefCountPtr< FRefCountedDisplayString > & Private_GetDisplayStringPtr () const
Protected Member Functions
FString & GetDisplayString () const
Protected Attributes
TRefCountPtr< FRefCountedDisplayString > DisplayStringPtr
Detailed Description
template<typename ObjectType>
class UE::Text::Private::TDisplayStringPtrBase< ObjectType >
Wrapper to give TRefCountPtr a minimal TSharedRef/TSharedPtr interface for backwards compatibility with code that was already using FTextDisplayStringRef/FTextDisplayStringPtr.
Definition at line 110 of file LocalizedTextSourceTypes.h.
Constructor & Destructor Documentation
TDisplayStringPtrBase() [1/2]
template<typename ObjectType> UE::Text::Private::TDisplayStringPtrBase< ObjectType >::TDisplayStringPtrBase () default
Referenced by UE::Text::Private::TDisplayStringPtr< FString >::TDisplayStringPtr(), UE::Text::Private::TDisplayStringPtr< FString >::TDisplayStringPtr(), UE::Text::Private::TDisplayStringPtr< FString >::TDisplayStringPtr(), UE::Text::Private::TDisplayStringRef< FString >::TDisplayStringRef(), and UE::Text::Private::TDisplayStringRef< FString >::TDisplayStringRef().
TDisplayStringPtrBase() [2/2]
template<typename ObjectType> UE::Text::Private::TDisplayStringPtrBase< ObjectType >::TDisplayStringPtrBase (const TRefCountPtr< FRefCountedDisplayString > & InDisplayStringPtr) inline explicit
Definition at line 117 of file LocalizedTextSourceTypes.h.
References DisplayStringPtr.
Member Function Documentation
GetDisplayString()
template<typename ObjectType> FString & UE::Text::Private::TDisplayStringPtrBase< ObjectType >::GetDisplayString () const inline nodiscard protected
Definition at line 148 of file LocalizedTextSourceTypes.h.
References check, DisplayStringPtr, and IsValid().
Referenced by UE::Text::Private::TDisplayStringPtr< FString >::Get(), UE::Text::Private::TDisplayStringRef< FString >::Get(), operator*(), and operator->().
IsValid()
template<typename ObjectType> bool UE::Text::Private::TDisplayStringPtrBase< ObjectType >::IsValid () const inline nodiscard
Definition at line 127 of file LocalizedTextSourceTypes.h.
References DisplayStringPtr.
Referenced by UE::Text::Private::TDisplayStringRef< FString >::TDisplayStringRef(), UE::Text::Private::TDisplayStringPtr< FString >::Get(), GetDisplayString(), operator bool(), and UE::Text::Private::TDisplayStringPtr< FString >::ToSharedRef().
operator bool()
template<typename ObjectType> UE::Text::Private::TDisplayStringPtrBase< ObjectType >::operator bool () const inline explicit nodiscard
Definition at line 122 of file LocalizedTextSourceTypes.h.
References IsValid().
operator*()
template<typename ObjectType> ObjectType & UE::Text::Private::TDisplayStringPtrBase< ObjectType >::operator* () const inline nodiscard
Definition at line 132 of file LocalizedTextSourceTypes.h.
References GetDisplayString().
operator->()
template<typename ObjectType> ObjectType * UE::Text::Private::TDisplayStringPtrBase< ObjectType >::operator-> () const inline nodiscard
Definition at line 137 of file LocalizedTextSourceTypes.h.
References GetDisplayString().
Private_GetDisplayStringPtr()
template<typename ObjectType> const TRefCountPtr< FRefCountedDisplayString > & UE::Text::Private::TDisplayStringPtrBase< ObjectType >::Private_GetDisplayStringPtr () const inline nodiscard
Definition at line 142 of file LocalizedTextSourceTypes.h.
References DisplayStringPtr.
Referenced by UE::Text::Private::TDisplayStringPtr< FString >::TDisplayStringPtr(), UE::Text::Private::TDisplayStringPtr< FString >::TDisplayStringPtr(), UE::Text::Private::TDisplayStringRef< FString >::TDisplayStringRef(), UE::Text::Private::TDisplayStringPtr< FString >::operator=(), UE::Text::Private::TDisplayStringPtr< FString >::operator=(), and UE::Text::Private::TDisplayStringRef< FString >::operator=().
Field Documentation
DisplayStringPtr
template<typename ObjectType> TRefCountPtr<FRefCountedDisplayString> UE::Text::Private::TDisplayStringPtrBase< ObjectType >::DisplayStringPtr protected
Definition at line 154 of file LocalizedTextSourceTypes.h.
Referenced by TDisplayStringPtrBase(), GetDisplayString(), IsValid(), UE::Text::Private::TDisplayStringPtr< FString >::operator=(), UE::Text::Private::TDisplayStringPtr< FString >::operator=(), UE::Text::Private::TDisplayStringRef< FString >::operator=(), Private_GetDisplayStringPtr(), UE::Text::Private::TDisplayStringPtr< FString >::Reset(), and UE::Text::Private::TDisplayStringPtr< FString >::ToSharedRef().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Internationalization/LocalizedTextSourceTypes.h