Unreal Engine 5.6 C++ API: FPackageName Class Reference
FPackageName Class Reference
#include "PackageName.h"
Public Types
enum class EConvertFlags { None = 0 , AllowDots = 0x1 }
enum class EErrorCode {
PackageNameUnknown , PackageNameEmptyPath , PackageNamePathNotMounted , PackageNamePathIsMemoryOnly ,
PackageNameSpacesNotAllowed , PackageNameContainsInvalidCharacters , LongPackageNames_PathTooShort , LongPackageNames_PathWithNoStartingSlash ,
LongPackageNames_PathWithTrailingSlash , LongPackageNames_PathWithDoubleSlash
}
enum class EFlexNameType { Invalid , PackageName , LocalPath , ObjectPath }
Indicates the format the input was in in functions that take flexible input that can be a LocalPath, PackageName, or ObjectPath.
enum class EPackageLocationFilter : uint8 {
None = 0 , IoDispatcher = 1 , FileSystem = 2 , MaxBit = FileSystem ,
ValidMask = (1 << MaxBit) - 1 , Any = 0xFF
}
enum class EPathFormatFlags : uint32 {
None = 0x0 , MountPointLeadingSlash = 0x1 , MountPointTrailingSlash = 0x2 , MountPointSlashes = MountPointLeadingSlash | MountPointTrailingSlash ,
MountPointNoSlashes = None
}
Flags for the output format of path functions.
typedef TFunctionRef< bool(const TCHAR *, const FFileStatData &)> FPackageNameStatVisitor
typedef TFunctionRef< bool(const TCHAR *)> FPackageNameVisitor
This will recurse over a directory structure looking for packages.
Public Member Functions
DECLARE_DELEGATE_RetVal_OneParam (bool, FDoesPackageExistOverride, FName)
Override whether a package exist or not.
DECLARE_MULTICAST_DELEGATE_TwoParams (FGetExplanationForUnavailablePackageDelegate, const FName &, FStringBuilderBase &)
Delegate type for allowing higher levels systems to provide additional context for why a package is not available.
DECLARE_MULTICAST_DELEGATE_TwoParams (FOnContentPathDismountedEvent, const FString &, const FString &)
Event that is triggered when a new content path is removed.
DECLARE_MULTICAST_DELEGATE_TwoParams (FOnContentPathMountedEvent, const FString &, const FString &)
Event that is triggered when a new content path is mounted.
UE_DEPRECATED (5.0, "Deprecated. UPackage::Guid has not been used by the engine for a long time. Call DoesPackageExist without a Guid.") static bool DoesPackageExist(const FString &LongPackageName
Checks if the package exists on disk.
UE_DEPRECATED (5.0, "Specifying AllowTextFormats is no longer supported. Text format is instead specified as a field on the result struct from IPackageResourceManager->OpenReadPackage.") static 1 bool FindPackageFileWithoutExtension(const FString &InPackageFilename
Static Public Member Functions
static FString ConvertToLongScriptPackageName (const TCHAR *InShortName)
Helper function for converting short to long script package name (InputCore -> /Script/InputCore)
static bool DoesPackageExist (const FPackagePath &PackagePath, bool bMatchCaseOnDisk=false, FPackagePath *OutPackagePath=nullptr)
Checks if the package exists on disk.
static bool DoesPackageExist (const FPackagePath &PackagePath, FPackagePath *OutPackagePath)
Checks if the package exists on disk.
static EPackageLocationFilter DoesPackageExistEx (const FPackagePath &PackagePath, EPackageLocationFilter Filter, bool bMatchCaseOnDisk=false, FPackagePath *OutPackagePath=nullptr)
Checks if the package exists in IOStore containers, on disk outside of IOStore, both, or neither.
static FDoesPackageExistOverride & DoesPackageExistOverride ()
static bool DoesPackageNameContainInvalidCharacters (FStringView InLongPackageName, EErrorCode *OutReason=nullptr)
static bool DoesPackageNameContainInvalidCharacters (FStringView InLongPackageName, FText *OutReason)
Checks if a package name contains characters that are invalid for package names.
static FString ExportTextPathToObjectPath (const FString &InExportTextPath)
static FString ExportTextPathToObjectPath (const TCHAR *InExportTextPath)
static FAnsiStringView ExportTextPathToObjectPath (FAnsiStringView InExportTextPath)
static FWideStringView ExportTextPathToObjectPath (FWideStringView InExportTextPath)
Returns the path to the object referred to by the supplied export text path, excluding the class name.
static FString FilenameToLongPackageName (const FString &InFilename)
Converts the supplied filename to long package name.
static bool FindPackageFileWithoutExtension (const FString &InPackageFilename, FString &OutFilename)
Checks if a package can be found using known package extensions (header extensions only; files with the extensions of other segments are not returned).
static bool FindPackagesInDirectories (TArray< FString > &OutPackages, const TArrayView< const FString > &RootDirs)
This will recurse over the given list of directory structures looking for packages.
static bool FindPackagesInDirectory (TArray< FString > &OutPackages, const FString &RootDir)
This will recurse over a directory structure looking for packages.
static FName * FindScriptPackageName (FName InShortName)
Finds long script package name associated with a short package name.
static bool FixPackageNameCase (FString &LongPackageName, FStringView Extension)
Converts a long package name to the case it exists as on disk.
static FString FormatErrorAsString (FStringView InPath, EErrorCode ErrorCode)
Return a user-readable string for the error code returned from a FPackageName function.
static FText FormatErrorAsText (FStringView InPath, EErrorCode ErrorCode)
Return a user-readable string for the error code returned from a FPackageName function.
static const FString & GetAssetPackageExtension ()
Returns the file extension for packages containing assets.
static FString GetContentPathForPackageRoot (FStringView InPackageRoot)
Get the path associated with the given package root.
static FString GetDelegateResolvedPackagePath (const FString &InSourcePackagePath)
Gets the resolved path of a long package as determined by the delegates registered with FCoreDelegates::PackageNameResolvers.
static void GetExplanationForUnavailablePackage (const FName &UnavailablePackageName, FStringBuilderBase &InOutExplanation)
Attempt to generate an explanation for why a particular package was not available for loading.
static FGetExplanationForUnavailablePackageDelegate & GetExplanationForUnavailablePackageDelegate ()
Accessor for installing callbacks for use with GetExplanationForUnavailablePackage.
static const TCHAR * GetGeneratedPackageSubPath ()
Return the text string used to mark the Generated directory of packages created by CookPackageSplitters.
static FString GetLocalizedPackagePath (const FString &InSourcePackagePath)
Gets the localized version of a long package path for the current culture, or returns the source package if there is no suitable localized package.
static FString GetLocalizedPackagePath (const FString &InSourcePackagePath, const FString &InCultureName)
Gets the localized version of a long package path for the given culture, or returns the source package if there is no suitable localized package.
static FString GetLongPackageAssetName (const FString &InLongPackageName)
Returns the clean asset name for the specified package, same as GetShortName.
static FString GetLongPackagePath (const FString &InLongPackageName)
Returns the path to the specified package, excluding the short package name e.g.
static const FString & GetMapPackageExtension ()
Returns the file extension for packages containing assets.
static FName GetModuleScriptPackageName (FName ModuleName)
Return the LongPackageName of module's native script package.
static FString GetModuleScriptPackageName (FStringView ModuleName)
static FString GetNormalizedObjectPath (const FString &ObjectPath)
Gets normalized object path i.e.
static FName GetPackageMountPoint (const FString &InPackagePath, bool InWithoutSlashes=true)
static FName GetPackageMountPoint (const TCHAR *InPackagePath, bool InWithoutSlashes=true)
static FName GetPackageMountPoint (FStringView InPackagePath, bool InWithoutSlashes=true)
Get the mount point for a given package path.
static FName GetShortFName (const FName &LongName)
static FName GetShortFName (const FString &LongName)
Converts package name to short name.
static FName GetShortFName (const TCHAR *LongName)
static FString GetShortName (const FName &LongName)
static FString GetShortName (const FString &LongName)
Converts package name to short name.
static FString GetShortName (const TCHAR *LongName)
static FString GetShortName (const UPackage *Package)
Converts package name to short name.
static FString GetSourcePackagePath (const FString &InLocalizedPackagePath)
Gets the source version of a localized long package path (it is also safe to pass non-localized paths into this function).
static const FString & GetTextAssetPackageExtension ()
Returns the file extension for packages containing text assets.
static const FString & GetTextMapPackageExtension ()
Returns the file extension for packages containing text maps.
static UE_INTERNAL UE::Core::FVersePath GetVersePath (const FTopLevelAssetPath &AssetPath)
Gets the versepath of the top level object.
static bool IsAssetPackageExtension (const TCHAR *Ext)
Returns whether the passed in extension is a valid binary asset package extension.
static bool IsInEngineTransientPackages (FStringView InPackageName)
Checks the root of the package's path to see if it is the EngineTransient package in specific, OR one of the packages in the directory of EngineTransient packages.
static bool IsLocalizedPackage (FStringView InPackageName)
Checks the root of the package's path to see if it is a localized package.
static bool IsMapPackageExtension (const TCHAR *Ext)
Returns whether the passed in extension is a valid binary map package extension.
static bool IsMemoryPackage (FStringView InPackageName)
Checks the root of the package's path to see if it's a memory package This should be set for packages that reside in memory and not on disk, we treat them similar to a script package.
static bool IsPackageExtension (const TCHAR *Ext)
Returns whether the passed in extension is a valid binary package extension.
static bool IsPackageExtension (EPackageExtension Extension)
Returns whether the passed in extension is a valid binary package extension.
static FORCEINLINE bool IsPackageFilename (FStringView Filename)
Returns whether the passed in filename ends with any of the known package extensions.
static bool IsScriptPackage (FStringView InPackageName)
Checks the root of the package's path to see if it is a script package.
static bool IsShortPackageName (const FName PossiblyLongName)
static bool IsShortPackageName (const FString &PossiblyLongName)
Checks if the string is a ShortPackageName.
static bool IsShortPackageName (FStringView PossiblyLongName)
static bool IsTempPackage (FStringView InPackageName)
Checks the root of the package's path to see if it is a temp package Temp packages are sometimes saved to disk, and sometimes only exist in memory.
static bool IsTextAssetPackageExtension (const TCHAR *Ext)
Returns whether the passed in extension is a valid text asset package extension.
static bool IsTextMapPackageExtension (const TCHAR *Ext)
Returns whether the passed in extension is a valid text map package extension.
static bool IsTextPackageExtension (const TCHAR *Ext)
Returns whether the passed in extension is a valid text package extension.
static bool IsTextPackageExtension (EPackageExtension Extension)
Returns whether the passed in extension is a text header extension.
static bool IsUnderGeneratedPackageSubPath (FStringView FileOrLongPackagePath)
Return whether a given packagename or file path is generated based on its name (we evaluate whether it is in a GetGeneratedPackageSubPath directory).
static bool IsValidLongPackageName (FStringView InLongPackageName, bool bIncludeReadOnlyRoots, FText *OutReason)
static bool IsValidLongPackageName (FStringView InLongPackageName, bool bIncludeReadOnlyRoots=false, EErrorCode *OutReason=nullptr)
Returns true if the path starts with a valid root (i.e.
static bool IsValidObjectPath (FStringView InObjectPath, FText *OutReason=nullptr)
Returns true if the path starts with a valid root (i.e.
static bool IsValidPath (FStringView InPath)
Returns true if the path starts with a valid root (i.e.
static bool IsValidTextForLongPackageName (FStringView InLongPackageName, EErrorCode *OutReason=nullptr)
Report whether a given name is the proper format for a PackageName, without checking whether it is in one of the registered mount points.
static bool IsValidTextForLongPackageName (FStringView InLongPackageName, FText *OutReason)
static bool IsVerseExtension (const TCHAR *Ext)
Returns whether the passed in extension is a valid verse extension.
static bool IsVersePackage (FStringView InPackageName)
Checks the package's path to see if it's a Verse package.
static void IteratePackagesInDirectory (const FString &RootDir, const FPackageNameStatVisitor &Visitor)
static void IteratePackagesInDirectory (const FString &RootDir, const FPackageNameVisitor &Visitor)
static FString LongPackageNameToFilename (const FString &InLongPackageName, const FString &InExtension=TEXT(""))
Converts a long package name to a file name with the supplied extension.
static bool MountPointExists (const FString &RootPath)
static bool MountPointExists (const TCHAR *RootPath)
static bool MountPointExists (FStringView RootPath)
Returns whether the specific logical root path is a valid mount point.
static void ObjectPathAppend (FStringBuilderBase &ObjectPath, FStringView NextName)
Combines an ObjectPath with an ObjectName.
static FString ObjectPathCombine (FStringView ObjectPath, FStringView NextName)
Combines an ObjectPath with an ObjectName, the same as ObjectPathAppend but returns the result rather than modifying the input argument.
static void ObjectPathSplitFirstName (FAnsiStringView Text, FAnsiStringView &OutFirst, FAnsiStringView &OutRemainder)
static void ObjectPathSplitFirstName (FWideStringView Text, FWideStringView &OutFirst, FWideStringView &OutRemainder)
Splits an ObjectPath string into the first component and the remainder.
static FString ObjectPathToObjectName (const FString &InObjectPath)
static FAnsiStringView ObjectPathToObjectName (FAnsiStringView InObjectPath)
static FWideStringView ObjectPathToObjectName (FWideStringView InObjectPath)
Returns the name of the leaf object referred to by the specified object path.
static FString ObjectPathToOuterPath (const FString &InObjectPath)
static FAnsiStringView ObjectPathToOuterPath (FAnsiStringView InObjectPath)
static FWideStringView ObjectPathToOuterPath (FWideStringView InObjectPath)
Returns the path name of the outer of the leaf object referred to by the specified object path.
static FString ObjectPathToPackageName (const FString &InObjectPath)
static FAnsiStringView ObjectPathToPackageName (FAnsiStringView InObjectPath)
static FWideStringView ObjectPathToPackageName (FWideStringView InObjectPath)
Returns the name of the package referred to by the specified object path.
static FString ObjectPathToPathWithinPackage (const FString &InObjectPath)
static FAnsiStringView ObjectPathToPathWithinPackage (FAnsiStringView InObjectPath)
static FWideStringView ObjectPathToPathWithinPackage (FWideStringView InObjectPath)
Returns any remaining object path after trimming the package name from the specified object path.
static FString ObjectPathToSubObjectPath (const FString &InObjectPath)
static FAnsiStringView ObjectPathToSubObjectPath (FAnsiStringView InObjectPath)
static FWideStringView ObjectPathToSubObjectPath (FWideStringView InObjectPath)
Returns the path from (and including) the subobject referred to by the specified object path.
static FOnContentPathDismountedEvent & OnContentPathDismounted ()
static FOnContentPathMountedEvent & OnContentPathMounted ()
static void OnCoreUObjectInitialized ()
If the FLongPackagePathsSingleton is not created yet, this function will create it and thus allow mount points to be added.
static bool ParseExportTextPath (const FString &InExportTextPath, FString *OutClassName, FString *OutObjectPath)
static bool ParseExportTextPath (const TCHAR *InExportTextPath, FStringView *OutClassName, FStringView *OutObjectPath)
static bool ParseExportTextPath (FAnsiStringView InExportTextPath, FAnsiStringView *OutClassName, FAnsiStringView *OutObjectPath)
static bool ParseExportTextPath (FWideStringView InExportTextPath, FWideStringView *OutClassName, FWideStringView *OutObjectPath)
Converts the supplied export text path to an object path and class name.
static TArray< FString > QueryMountPointLocalAbsPaths ()
Returns all of the local paths on disk of the root content paths, like "c:\MyProjects\ProjectA\Content", "d:\Unreal\Engine\Content", "c:\MyProjects\ProjectA\Plugins\MyPlugin\Content".
static void QueryRootContentPaths (TArray< FString > &OutRootContentPaths, bool bIncludeReadOnlyRoots=false, bool bWithoutLeadingSlashes=false, bool bWithoutTrailingSlashes=false)
Queries all of the root content paths, like "/Game/", "/Engine/", and any dynamically added paths.
static void RegisterMountPoint (const FString &RootPath, const FString &ContentPath)
This will insert a mount point at the head of the search chain (so it can overlap an existing mount point and win).
static void RegisterShortPackageNamesForUObjectModules ()
Registers all short package names found in ini files.
static bool SearchForPackageOnDisk (const FString &PackageName, FString *OutLongPackageName=NULL, FString *OutFilename=NULL)
Attempts to find a package given its short name on disk (very slow).
static void SplitFullObjectPath (const FString &InFullObjectPath, FString &OutClassName, FString &OutPackageName, FString &OutObjectName, FString &OutSubObjectName, bool bDetectClassName=true)
Split a full object path (Class /Path/To/A/Package.Object:Subobject1.Subobject2) into its constituent pieces.
static void SplitFullObjectPath (const FString &InFullObjectPath, FString &OutClassName, FString &OutPackageName, FString &OutObjectName, TArray< FString > &OutSubobjectNames, bool bDetectClassName=true)
Split a full object path (Class /Path/To/A/Package.Object:Subobject1.Subobject2) into its constituent pieces.
static void SplitFullObjectPath (FStringView InFullObjectPath, FStringView &OutClassName, FStringView &OutPackageName, FStringView &OutObjectName, FStringView &OutSubObjectName, bool bDetectClassName=true)
static void SplitFullObjectPath (FStringView InFullObjectPath, FStringView &OutClassName, FStringView &OutPackageName, FStringView &OutObjectName, TArray< FStringView > &OutSubobjectNames, bool bDetectClassName=true)
static bool SplitLongPackageName (const FString &InLongPackageName, FString &OutPackageRoot, FString &OutPackagePath, FString &OutPackageLeafName, const bool bStripRootLeadingSlash=false)
Test whether a given packagename is in a valid root, and convert it to root, path, and leafname components.
static void SplitPackageName (const FString &InLongPackageName, FString *OutPackageRoot, FString *OutPackagePath, FString *OutPackageLeafName, EPathFormatFlags Flags=EPathFormatFlags::MountPointSlashes)
static void SplitPackageName (FStringView InPackageName, FStringView *OutPackageRoot, FStringView *OutPackagePath, FStringView *OutPackageLeafName, EPathFormatFlags Flags=EPathFormatFlags::MountPointSlashes)
Convert a long package name into root, path, and leafname components.
static FString SplitPackageNameRoot (FName InPackageName, FString *OutRelativePath, EPathFormatFlags Flags=EPathFormatFlags::MountPointNoSlashes)
static FStringView SplitPackageNameRoot (FStringView InPackageName, FStringView *OutRelativePath, EPathFormatFlags Flags=EPathFormatFlags::MountPointNoSlashes)
Returns the top level 'directory' in a package name.
static bool TryConvertFilenameToLongPackageName (const FString &InFilename, FString &OutPackageName, FString *OutFailureReason=nullptr, const EConvertFlags Flags=EConvertFlags::None)
Tries to convert the supplied relative or absolute filename to a long package name/path starting with a root like /game This works on both package names and directories, and it does not validate that it actually exists on disk.
static bool TryConvertFilenameToLongPackageName (FStringView InFilename, FStringBuilderBase &OutPackageName, FStringBuilderBase *OutFailureReason=nullptr, const EConvertFlags Flags=EConvertFlags::None)
static bool TryConvertGameRelativePackagePathToLocalPath (FStringView RelativePackagePath, FString &OutLocalPath)
Tries to convert a file or directory in game-relative package name format to the corresponding local path Game-relative package names can be a full package path (/Game/Folder/File, /Engine/Folder/File, /PluginName/Folder/File) or a relative path (Folder/File).
static bool TryConvertLongPackageNameToFilename (const FString &InLongPackageName, FString &OutFilename, const FString &InExtension=TEXT(""))
Tries to convert a long package name to a file name with the supplied extension.
static bool TryConvertLongPackageNameToFilename (FStringView InLongPackageName, FString &OutFilename, FStringView InExtension={})
static bool TryConvertScriptPackageNameToModuleName (FStringView PackageName, FStringView &OutModuleName)
If PackageName is a script package (/Script/<ModuleName>), return true and set OutModuleName=<ModuleName>
static bool TryConvertShortPackagePathToLongInObjectPath (const FString &ObjectPath, FString &ConvertedObjectPath)
Tries to convert object path with short package name to object path with long package name found on disk (very slow)
static bool TryConvertToMountedPath (FStringView InPath, FString *OutLocalPathNoExtension, FString *OutPackageName, FString *OutObjectName, FString *OutSubObjectName, FString *OutExtension, EFlexNameType *OutFlexNameType=nullptr, EErrorCode *OutFailureReason=nullptr)
Find the MountPoint for a LocalPath, LongPackageName, or ObjectPath and return its elements.
static bool TryGetMountPointForPath (FStringView InFilePathOrPackageName, FStringBuilderBase &OutMountPointPackageName, FStringBuilderBase &OutMountPointFilePath, FStringBuilderBase &OutRelPath, EFlexNameType *OutFlexNameType=nullptr, EErrorCode *OutFailureReason=nullptr)
Find a mount point that contains the given LocalFilePath or PackageName, and if found, return the MountPoint and RelativePath.
static void UnRegisterMountPoint (const FString &RootPath, const FString &ContentPath)
This will remove a previously inserted mount point.
Data Fields
const FGuid * Guid
const FGuid FString bool InAllowTextFormats
FString bool InAllowTextFormats
const FGuid FString * OutFilename
FString & OutFilename
Static Private Member Functions
static EPackageLocationFilter InternalDoesPackageExistEx (const FPackagePath &PackagePath, EPackageLocationFilter Filterconst, bool bMatchCaseOnDisk=false, FPackagePath *OutPackagePath=nullptr)
static EPackageLocationFilter InternalDoesPackageExistEx (const FString &LongPackageName, EPackageLocationFilter Filterconst, bool bMatchCaseOnDisk=false, FPackagePath *OutPackagePath=nullptr)
static void InternalFilenameToLongPackageName (FStringView InFilename, FStringBuilderBase &OutPackageName)
Internal function used to rename filename to long package name.
static bool TryConvertToMountedPackagePath (const FString &InPath, FPackagePath &OutPackagePath, EErrorCode &OutFailureReason)
Internal helper to create a FPackagePath given LocalFilePath or PackageName, and if found, return the MountPoint, RelativePath, and PackageExtension.
static bool TryConvertToMountedPathComponents (FStringView InPath, FStringBuilderBase &OutMountPointPackageName, FStringBuilderBase &OutMountPointFilePath, FStringBuilderBase &OutRelPath, FStringBuilderBase &OutObjectName, EPackageExtension &OutExtension, FStringBuilderBase &OutCustomExtension, EFlexNameType *OutFlexNameType=nullptr, EErrorCode *OutFailureReason=nullptr)
Internal helper to find a mount point that contains the given LocalFilePath or PackageName, and if found, return the MountPoint, RelativePath, and PackageExtension.
Static Private Attributes
static FDoesPackageExistOverride DoesPackageExistOverrideDelegate
Delegate used to check whether a package exist without using the filesystem.
static FOnContentPathDismountedEvent OnContentPathDismountedEvent
Event that is triggered when a new content path is removed.
static FOnContentPathMountedEvent OnContentPathMountedEvent
Event that is triggered when a new content path is mounted.
Friends
struct ::UE::AssetRegistry::Impl::FScanPathContext
class FAssetRegistryConsoleCommands
class FPackagePath
class UAssetRegistryImpl
Detailed Description
Definition at line 33 of file PackageName.h.
Member Typedef Documentation
FPackageNameStatVisitor
typedef TFunctionRef<bool(const TCHAR*, const FFileStatData&)> FPackageName::FPackageNameStatVisitor
Definition at line 658 of file PackageName.h.
FPackageNameVisitor
typedef TFunctionRef<bool(const TCHAR*)> FPackageName::FPackageNameVisitor
This will recurse over a directory structure looking for packages.
Parameters
RootDirectory The root of the directory structure to recurse through
Visitor Visitor to call for each package file found (takes the package filename, and optionally the stat data for the file - returns true to continue iterating)
Definition at line 657 of file PackageName.h.
Member Enumeration Documentation
EConvertFlags
enum class FPackageName::EConvertFlags strong
Enumerator
None
AllowDots
When set, this will allow filenames following the wildcard pattern of *.*.*, rather than *.*.
Definition at line 58 of file PackageName.h.
EErrorCode
enum class FPackageName::EErrorCode strong
Enumerator
PackageNameUnknown
PackageNameEmptyPath
PackageNamePathNotMounted
PackageNamePathIsMemoryOnly
PackageNameSpacesNotAllowed
PackageNameContainsInvalidCharacters
LongPackageNames_PathTooShort
LongPackageNames_PathWithNoStartingSlash
LongPackageNames_PathWithTrailingSlash
LongPackageNames_PathWithDoubleSlash
Definition at line 44 of file PackageName.h.
EFlexNameType
enum class FPackageName::EFlexNameType strong
Indicates the format the input was in in functions that take flexible input that can be a LocalPath, PackageName, or ObjectPath.
Enumerator
Invalid
PackageName
LocalPath
ObjectPath
Definition at line 37 of file PackageName.h.
EPackageLocationFilter
enum class FPackageName::EPackageLocationFilter : uint8 strong
Enumerator
None
IoDispatcher
FileSystem
MaxBit
ValidMask
Any
Definition at line 404 of file PackageName.h.
EPathFormatFlags
enum class FPackageName::EPathFormatFlags : uint32 strong
Flags for the output format of path functions.
Enumerator
None
MountPointLeadingSlash
MountPointTrailingSlash
MountPointSlashes
MountPointNoSlashes
Definition at line 721 of file PackageName.h.
Member Function Documentation
ConvertToLongScriptPackageName()
FString FPackageName::ConvertToLongScriptPackageName (const TCHAR * InShortName) static
Helper function for converting short to long script package name (InputCore -> /Script/InputCore)
Parameters
InShortName Short package name.
Returns
Long package name.
DECLARE_DELEGATE_RetVal_OneParam()
FPackageName::DECLARE_DELEGATE_RetVal_OneParam (bool , FDoesPackageExistOverride , FName)
Override whether a package exist or not.
References DECLARE_DELEGATE_RetVal_OneParam().
Referenced by DECLARE_DELEGATE_RetVal_OneParam().
DECLARE_MULTICAST_DELEGATE_TwoParams() [1/3]
FPackageName::DECLARE_MULTICAST_DELEGATE_TwoParams (FGetExplanationForUnavailablePackageDelegate , const FName & , FStringBuilderBase &)
Delegate type for allowing higher levels systems to provide additional context for why a package is not available.
DECLARE_MULTICAST_DELEGATE_TwoParams() [2/3]
FPackageName::DECLARE_MULTICAST_DELEGATE_TwoParams (FOnContentPathDismountedEvent , const FString & , const FString &)
Event that is triggered when a new content path is removed.
DECLARE_MULTICAST_DELEGATE_TwoParams() [3/3]
FPackageName::DECLARE_MULTICAST_DELEGATE_TwoParams (FOnContentPathMountedEvent , const FString & , const FString &)
Event that is triggered when a new content path is mounted.
DoesPackageExist() [1/2]
bool FPackageName::DoesPackageExist (const FPackagePath & PackagePath, bool bMatchCaseOnDisk = false, FPackagePath * OutPackagePath = nullptr) static
Checks if the package exists on disk.
PackagePath must be a mounted path, otherwise returns false
Parameters
PackagePath Package package.
Guid If nonnull, and the package is found on disk but does not have this PackageGuid in its FPackageFileSummary::Guid, false is returned
bMatchCaseOnDisk If true, the OutPackagePath is modified to match the capitalization of the discovered file
OutPackagePath If nonnull and the package exists, set to a copy of PackagePath with the HeaderExtension set to the extension that exists on disk (and if bMatchCaseOnDisk is true, capitalization changed to match). If not found, this variable is not written
Returns
true if the specified package name points to an existing package, false otherwise.
References FPackagePath, and PackagePath.
DoesPackageExist() [2/2]
bool FPackageName::DoesPackageExist (const FPackagePath & PackagePath, FPackagePath * OutPackagePath) static
Checks if the package exists on disk.
PackagePath must be a mounted path, otherwise returns false
Parameters
PackagePath Package package.
OutPackagePath If nonnull and the package exists, set to a copy of PackagePath with the HeaderExtension set to the extension that exists on disk. If not found, this variable is not written
Returns
true if the specified package name points to an existing package, false otherwise.
References FPackagePath, and PackagePath.
DoesPackageExistEx()
EPackageLocationFilter FPackageName::DoesPackageExistEx (const FPackagePath & PackagePath, EPackageLocationFilter Filter, bool bMatchCaseOnDisk = false, FPackagePath * OutPackagePath = nullptr) static
Checks if the package exists in IOStore containers, on disk outside of IOStore, both, or neither.
Parameters
PackagePath Package package.
Filter Indication of where it should look for
Guid If non-null, and the package is found on disk but does not have this PackageGuid in its FPackageFileSummary::Guid, false is returned
bMatchCaseOnDisk If true, the OutPackagePath is modified to match the capitalization of the discovered file
OutPackagePath If non-null and the package exists, set to a copy of PackagePath with the HeaderExtension set to the extension that exists on disk (and if bMatchCaseOnDisk is true, capitalization changed to match). If not found, this variable is not written
Returns
the set of locations where the package exists (IoDispatcher or FileSystem, both or neither)
References Filter, FPackagePath, and PackagePath.
DoesPackageExistOverride()
FDoesPackageExistOverride & FPackageName::DoesPackageExistOverride () inline static
Definition at line 950 of file PackageName.h.
References DoesPackageExistOverride(), and DoesPackageExistOverrideDelegate.
Referenced by DoesPackageExistOverride().
DoesPackageNameContainInvalidCharacters() [1/2]
bool FPackageName::DoesPackageNameContainInvalidCharacters (FStringView InLongPackageName, EErrorCode * OutReason = nullptr) static
DoesPackageNameContainInvalidCharacters() [2/2]
bool FPackageName::DoesPackageNameContainInvalidCharacters (FStringView InLongPackageName, FText * OutReason) static
Checks if a package name contains characters that are invalid for package names.
ExportTextPathToObjectPath() [1/4]
FString FPackageName::ExportTextPathToObjectPath (const FString & InExportTextPath) static
ExportTextPathToObjectPath() [2/4]
FString FPackageName::ExportTextPathToObjectPath (const TCHAR * InExportTextPath) static
ExportTextPathToObjectPath() [3/4]
FAnsiStringView FPackageName::ExportTextPathToObjectPath (FAnsiStringView InExportTextPath) static
ExportTextPathToObjectPath() [4/4]
FWideStringView FPackageName::ExportTextPathToObjectPath (FWideStringView InExportTextPath) static
Returns the path to the object referred to by the supplied export text path, excluding the class name.
Parameters
InExportTextPath The export text path for an object. Takes on the form: ClassName'ObjectPath'
Returns
The path to the object referred to by the supplied export path.
FilenameToLongPackageName()
FString FPackageName::FilenameToLongPackageName (const FString & InFilename) static
Converts the supplied filename to long package name.
Throws a fatal error if the conversion is not successful.
Parameters
InFilename Filename to convert.
Returns
Long package name.
FindPackageFileWithoutExtension()
bool FPackageName::FindPackageFileWithoutExtension (const FString & InPackageFilename, FString & OutFilename) static
Checks if a package can be found using known package extensions (header extensions only; files with the extensions of other segments are not returned).
Parameters
InPackageFilename Package filename without the extension.
OutFilename If the package could be found, filename with the extension.
InAllowTextFormats Detect text format packages as well as binary (priority to text)
Returns
true if the package could be found on disk.
References OutFilename.
FindPackagesInDirectories()
bool FPackageName::FindPackagesInDirectories (TArray< FString > & OutPackages, const TArrayView< const FString > & RootDirs) static
This will recurse over the given list of directory structures looking for packages.
Parameters
OutPackages The output array that is filled out with the discovered file paths
RootDirss The roots of the directory structures to recurse through
Returns
Returns true if any packages have been found, otherwise false
FindPackagesInDirectory()
bool FPackageName::FindPackagesInDirectory (TArray< FString > & OutPackages, const FString & RootDir) static
This will recurse over a directory structure looking for packages.
Parameters
OutPackages The output array that is filled out with the discovered file paths
RootDir The root of the directory structure to recurse through
Returns
Returns true if any packages have been found, otherwise false
FindScriptPackageName()
FName * FPackageName::FindScriptPackageName (FName InShortName) static
Finds long script package name associated with a short package name.
Parameters
InShortName Short script package name.
Returns
Long script package name (/Script/Package) associated with short name or NULL.
FixPackageNameCase()
bool FPackageName::FixPackageNameCase (FString & LongPackageName, FStringView Extension) static
Converts a long package name to the case it exists as on disk.
Parameters
LongPackageName The long package name
Extension The extension for this package
Returns
True if the long package name was fixed up, false otherwise
References FixPackageNameCase().
Referenced by FixPackageNameCase().
FormatErrorAsString()
FString FPackageName::FormatErrorAsString (FStringView InPath, EErrorCode ErrorCode) static
Return a user-readable string for the error code returned from a FPackageName function.
Parameters
InPath the path that was passed to the convert function
ErrorCode The error code returned from the convert function
FormatErrorAsText()
FText FPackageName::FormatErrorAsText (FStringView InPath, EErrorCode ErrorCode) static
Return a user-readable string for the error code returned from a FPackageName function.
Parameters
InPath the path that was passed to the convert function
ErrorCode The error code returned from the convert function
GetAssetPackageExtension()
const FString & FPackageName::GetAssetPackageExtension () static
Returns the file extension for packages containing assets.
Returns
file extension for asset packages (dot included)
GetContentPathForPackageRoot()
FString FPackageName::GetContentPathForPackageRoot (FStringView InPackageRoot) static
Get the path associated with the given package root.
Parameters
InPackageRoot Package root to return the path for, e.g. /Game/, /Engine/, /PluginName/
Returns
Filesystem path associated with the provided package root
GetDelegateResolvedPackagePath()
FString FPackageName::GetDelegateResolvedPackagePath (const FString & InSourcePackagePath) static
Gets the resolved path of a long package as determined by the delegates registered with FCoreDelegates::PackageNameResolvers.
This allows systems such as localization to redirect requests for a package to a more appropriate alternative, or to nix the request altogether.
Parameters
InSourcePackagePath Path to the source package.
Returns
Resolved package path, or the source package path if there is no resolution occurs.
GetExplanationForUnavailablePackage()
void FPackageName::GetExplanationForUnavailablePackage (const FName & UnavailablePackageName, FStringBuilderBase & InOutExplanation) static
Attempt to generate an explanation for why a particular package was not available for loading.
Parameters
UnavailablePackageName The package that was requested but could not be loaded
InOutExplanation A string builder that will be populated with any available information about why the package was not available. The string builder will not be reset and will be appended to.
GetExplanationForUnavailablePackageDelegate()
FGetExplanationForUnavailablePackageDelegate & FPackageName::GetExplanationForUnavailablePackageDelegate () static
Accessor for installing callbacks for use with GetExplanationForUnavailablePackage.
GetGeneratedPackageSubPath()
const TCHAR * FPackageName::GetGeneratedPackageSubPath () static
Return the text string used to mark the Generated directory of packages created by CookPackageSplitters.
GetLocalizedPackagePath() [1/2]
FString FPackageName::GetLocalizedPackagePath (const FString & InSourcePackagePath) static
Gets the localized version of a long package path for the current culture, or returns the source package if there is no suitable localized package.
Parameters
InSourcePackagePath Path to the source package.
Returns
Localized package path, or the source package path if there is no suitable localized package.
GetLocalizedPackagePath() [2/2]
FString FPackageName::GetLocalizedPackagePath (const FString & InSourcePackagePath, const FString & InCultureName) static
Gets the localized version of a long package path for the given culture, or returns the source package if there is no suitable localized package.
Parameters
InSourcePackagePath Path to the source package.
InCultureName Culture name to get the localized package for.
Returns
Localized package path, or the source package path if there is no suitable localized package.
GetLongPackageAssetName()
FString FPackageName::GetLongPackageAssetName (const FString & InLongPackageName) static
Returns the clean asset name for the specified package, same as GetShortName.
Parameters
InLongPackageName Long Package Name
Returns
Clean asset name.
GetLongPackagePath()
FString FPackageName::GetLongPackagePath (const FString & InLongPackageName) static
Returns the path to the specified package, excluding the short package name e.g.
given /Game/Maps/MyMap returns /Game/Maps
Parameters
InLongPackageName Long Package Name.
Returns
The path containing the specified package.
Referenced by AnimationEditorUtils::CreateAnimationAsset(), and AnimationEditorUtils::ExecuteNewAnimAsset().
GetMapPackageExtension()
const FString & FPackageName::GetMapPackageExtension () static
Returns the file extension for packages containing assets.
Returns
file extension for asset packages (dot included)
Referenced by DoActionToAllPackages().
GetModuleScriptPackageName() [1/2]
FName FPackageName::GetModuleScriptPackageName (FName ModuleName) static
Return the LongPackageName of module's native script package.
Does not check whether module is native.
GetModuleScriptPackageName() [2/2]
FString FPackageName::GetModuleScriptPackageName (FStringView ModuleName) static
GetNormalizedObjectPath()
FString FPackageName::GetNormalizedObjectPath (const FString & ObjectPath) static
Gets normalized object path i.e.
with long package format.
Parameters
ObjectPath Path to the object.
Returns
Normalized path (or empty path, if short object path was given and it wasn't found on the disk).
References ObjectPath.
GetPackageMountPoint() [1/3]
FName FPackageName::GetPackageMountPoint (const FString & InPackagePath, bool InWithoutSlashes = true) static
GetPackageMountPoint() [2/3]
FName FPackageName::GetPackageMountPoint (const TCHAR * InPackagePath, bool InWithoutSlashes = true) static
GetPackageMountPoint() [3/3]
FName FPackageName::GetPackageMountPoint (FStringView InPackagePath, bool InWithoutSlashes = true) static
Get the mount point for a given package path.
Parameters
InPackagePath The package path to get the mount point for
InWithoutSlashes Optional parameters that keeps the slashes around the mount point if false
Returns
FName corresponding to the mount point, or Empty if invalid
GetShortFName() [1/3]
FName FPackageName::GetShortFName (const FName & LongName) static
GetShortFName() [2/3]
FName FPackageName::GetShortFName (const FString & LongName) static
Converts package name to short name.
Parameters
LongName Package name to convert.
Returns
Short package name.
GetShortFName() [3/3]
FName FPackageName::GetShortFName (const TCHAR * LongName) static
GetShortName() [1/4]
FString FPackageName::GetShortName (const FName & LongName) static
GetShortName() [2/4]
FString FPackageName::GetShortName (const FString & LongName) static
Converts package name to short name.
Parameters
LongName Package name to convert.
Returns
Short package name.
GetShortName() [3/4]
FString FPackageName::GetShortName (const TCHAR * LongName) static
GetShortName() [4/4]
FString FPackageName::GetShortName (const UPackage * Package) static
Converts package name to short name.
Parameters
Package Package with name to convert.
Returns
Short package name.
References Package.
GetSourcePackagePath()
FString FPackageName::GetSourcePackagePath (const FString & InLocalizedPackagePath) static
Gets the source version of a localized long package path (it is also safe to pass non-localized paths into this function).
Parameters
InLocalizedPackagePath Path to the localized package.
Returns
Source package path.
GetTextAssetPackageExtension()
const FString & FPackageName::GetTextAssetPackageExtension () static
Returns the file extension for packages containing text assets.
Returns
file extension for text asset packages (dot included)
GetTextMapPackageExtension()
const FString & FPackageName::GetTextMapPackageExtension () static
Returns the file extension for packages containing text maps.
Returns
file extension for text map packages (dot included)
GetVersePath()
UE_INTERNAL UE::Core::FVersePath FPackageName::GetVersePath (const FTopLevelAssetPath & AssetPath) static
Gets the versepath of the top level object.
Returns
The VersePath of the top level object
References UE_INTERNAL.
InternalDoesPackageExistEx() [1/2]
EPackageLocationFilter FPackageName::InternalDoesPackageExistEx (const FPackagePath & PackagePath, EPackageLocationFilter Filterconst, bool bMatchCaseOnDisk = false, FPackagePath * OutPackagePath = nullptr) static private
References FPackagePath, and PackagePath.
InternalDoesPackageExistEx() [2/2]
EPackageLocationFilter FPackageName::InternalDoesPackageExistEx (const FString & LongPackageName, EPackageLocationFilter Filterconst, bool bMatchCaseOnDisk = false, FPackagePath * OutPackagePath = nullptr) static private
References FPackagePath.
InternalFilenameToLongPackageName()
void FPackageName::InternalFilenameToLongPackageName (FStringView InFilename, FStringBuilderBase & OutPackageName) static private
Internal function used to rename filename to long package name.
Parameters
InFilename
OutPackageName Long package name.
IsAssetPackageExtension()
bool FPackageName::IsAssetPackageExtension (const TCHAR * Ext) static
Returns whether the passed in extension is a valid binary asset package extension.
Extensions with and without trailing dots are supported.
Parameters
Extension to test.
Returns
True if Ext is a binary asset extension, otherwise false
IsInEngineTransientPackages()
bool FPackageName::IsInEngineTransientPackages (FStringView InPackageName) static
Checks the root of the package's path to see if it is the EngineTransient package in specific, OR one of the packages in the directory of EngineTransient packages.
IsLocalizedPackage()
bool FPackageName::IsLocalizedPackage (FStringView InPackageName) static
Checks the root of the package's path to see if it is a localized package.
Returns
true if the root of the path matches any localized root path
IsMapPackageExtension()
bool FPackageName::IsMapPackageExtension (const TCHAR * Ext) static
Returns whether the passed in extension is a valid binary map package extension.
Extensions with and without trailing dots are supported.
Parameters
Extension to test.
Returns
True if Ext is a binary asset extension, otherwise false
IsMemoryPackage()
bool FPackageName::IsMemoryPackage (FStringView InPackageName) static
Checks the root of the package's path to see if it's a memory package This should be set for packages that reside in memory and not on disk, we treat them similar to a script package.
Returns
true if the root of the patch matches the memory path
IsPackageExtension() [1/2]
bool FPackageName::IsPackageExtension (const TCHAR * Ext) static
Returns whether the passed in extension is a valid binary package extension.
Extensions with and without trailing dots are supported.
Parameters
Extension to test.
Returns
True if Ext is either a binary asset or map extension, otherwise false
IsPackageExtension() [2/2]
bool FPackageName::IsPackageExtension (EPackageExtension Extension) static
Returns whether the passed in extension is a valid binary package extension.
Parameters
Extension to test.
Returns
True if Ext is either a binary asset or a binary map extension, otherwise false
IsPackageFilename()
FORCEINLINE bool FPackageName::IsPackageFilename (FStringView Filename) inline static
Returns whether the passed in filename ends with any of the known package extensions.
Parameters
Filename to test.
Returns
True if the filename ends with a package extension.
Definition at line 617 of file PackageName.h.
References Asset, Filename, FORCEINLINE, LexToString(), and Map.
IsScriptPackage()
bool FPackageName::IsScriptPackage (FStringView InPackageName) static
Checks the root of the package's path to see if it is a script package.
Returns
true if the root of the path matches the script path
IsShortPackageName() [1/3]
bool FPackageName::IsShortPackageName (const FName PossiblyLongName) static
IsShortPackageName() [2/3]
bool FPackageName::IsShortPackageName (const FString & PossiblyLongName) static
Checks if the string is a ShortPackageName.
A ShortPackageName is the leaf name after the last slash in a LongPackageName. Handling ShortPackageNames is useful for console commands and other UI. A ShortPackageName requires a search to convert to a LongPackageName.
Parameters
PossiblyLongName Package name.
Returns
true if the given name is a short package name (contains no slashes), false otherwise.
IsShortPackageName() [3/3]
bool FPackageName::IsShortPackageName (FStringView PossiblyLongName) static
IsTempPackage()
bool FPackageName::IsTempPackage (FStringView InPackageName) static
Checks the root of the package's path to see if it is a temp package Temp packages are sometimes saved to disk, and sometimes only exist in memory.
They are never in source control
Returns
true if the root of the patch matches the temp path
IsTextAssetPackageExtension()
bool FPackageName::IsTextAssetPackageExtension (const TCHAR * Ext) static
Returns whether the passed in extension is a valid text asset package extension.
Extensions with and without trailing dots are supported.
Parameters
Extension to test.
Returns
True if Ext is a text asset extension, otherwise false
IsTextMapPackageExtension()
bool FPackageName::IsTextMapPackageExtension (const TCHAR * Ext) static
Returns whether the passed in extension is a valid text map package extension.
Extensions with and without trailing dots are supported.
Parameters
Extension to test.
Returns
True if Ext is a text map extension, otherwise false
IsTextPackageExtension() [1/2]
bool FPackageName::IsTextPackageExtension (const TCHAR * Ext) static
Returns whether the passed in extension is a valid text package extension.
Extensions with and without trailing dots are supported.
Parameters
Extension to test.
Returns
True if Ext is either an text asset or a text map extension, otherwise false
IsTextPackageExtension() [2/2]
bool FPackageName::IsTextPackageExtension (EPackageExtension Extension) static
Returns whether the passed in extension is a text header extension.
Parameters
Extension to test.
Returns
True if Ext is either an text asset or a text map extension, otherwise false
IsUnderGeneratedPackageSubPath()
bool FPackageName::IsUnderGeneratedPackageSubPath (FStringView FileOrLongPackagePath) static
Return whether a given packagename or file path is generated based on its name (we evaluate whether it is in a GetGeneratedPackageSubPath directory).
IsValidLongPackageName() [1/2]
bool FPackageName::IsValidLongPackageName (FStringView InLongPackageName, bool bIncludeReadOnlyRoots, FText * OutReason) static
IsValidLongPackageName() [2/2]
bool FPackageName::IsValidLongPackageName (FStringView InLongPackageName, bool bIncludeReadOnlyRoots = false, EErrorCode * OutReason = nullptr) static
Returns true if the path starts with a valid root (i.e.
/Game/, /Engine/, etc) and contains no illegal characters.
Parameters
InLongPackageName The package name to test
bIncludeReadOnlyRoots If true, will include roots that you should not save to. (/Temp/, /Script/)
OutReason When returning false, this will provide a description of what was wrong with the name.
Returns
true if a valid long package name
IsValidObjectPath()
bool FPackageName::IsValidObjectPath (FStringView InObjectPath, FText * OutReason = nullptr) static
Returns true if the path starts with a valid root (i.e.
/Game/, /Engine/, etc) and contains no illegal characters. This validates that the packagename is valid, and also makes sure the object after package name is also correct. This will return false if passed a path starting with Classname'
Parameters
InObjectPath The object path to test
OutReason When returning false, this will provide a description of what was wrong with the name.
Returns
true if a valid object path
IsValidPath()
bool FPackageName::IsValidPath (FStringView InPath) static
Returns true if the path starts with a valid root (i.e.
/Game/, /Engine/, /Memory/, etc).
Parameters
InObjectPath The object path to test
Returns
true if a valid object path
IsValidTextForLongPackageName() [1/2]
bool FPackageName::IsValidTextForLongPackageName (FStringView InLongPackageName, EErrorCode * OutReason = nullptr) static
Report whether a given name is the proper format for a PackageName, without checking whether it is in one of the registered mount points.
Parameters
InLongPackageName The package name to test
OutReason When returning false, this will provide a description of what was wrong with the name.
Returns
true if valid text for a long package name
IsValidTextForLongPackageName() [2/2]
bool FPackageName::IsValidTextForLongPackageName (FStringView InLongPackageName, FText * OutReason) static
IsVerseExtension()
bool FPackageName::IsVerseExtension (const TCHAR * Ext) static
Returns whether the passed in extension is a valid verse extension.
Extensions with and without trailing dots are supported.
Parameters
Extension to test.
Returns
True if Ext is a verse extension, otherwise false
IsVersePackage()
bool FPackageName::IsVersePackage (FStringView InPackageName) static
Checks the package's path to see if it's a Verse package.
IteratePackagesInDirectory() [1/2]
void FPackageName::IteratePackagesInDirectory (const FString & RootDir, const FPackageNameStatVisitor & Visitor) static
IteratePackagesInDirectory() [2/2]
void FPackageName::IteratePackagesInDirectory (const FString & RootDir, const FPackageNameVisitor & Visitor) static
LongPackageNameToFilename()
FString FPackageName::LongPackageNameToFilename (const FString & InLongPackageName, const FString & InExtension = TEXT("")) static
Converts a long package name to a file name with the supplied extension.
Throws a fatal error if the conversion is not successful.
Parameters
InLongPackageName Long Package Name
InExtension Package extension.
Returns
Package filename.
MountPointExists() [1/3]
bool FPackageName::MountPointExists (const FString & RootPath) static
MountPointExists() [2/3]
bool FPackageName::MountPointExists (const TCHAR * RootPath) static
MountPointExists() [3/3]
bool FPackageName::MountPointExists (FStringView RootPath) static
Returns whether the specific logical root path is a valid mount point.
ObjectPathAppend()
void FPackageName::ObjectPathAppend (FStringBuilderBase & ObjectPath, FStringView NextName) static
Combines an ObjectPath with an ObjectName.
{ "/Package", "Object" } -> "/Package.Object" { "/Package.Object", "SubObject" } -> "/Package.Object:SubObject" { "/Package.Object:SubObject", "NextSubObject" } -> "/Package.Object:SubObject.NextSubObject" { "/Package", "Object.SubObject" } -> "/Package.Object:SubObject" { "/Package", "/OtherPackage.Object:SubObject" } -> "/OtherPackage.Object:SubObject"
References ObjectPath.
ObjectPathCombine()
FString FPackageName::ObjectPathCombine (FStringView ObjectPath, FStringView NextName) static
Combines an ObjectPath with an ObjectName, the same as ObjectPathAppend but returns the result rather than modifying the input argument.
References ObjectPath.
ObjectPathSplitFirstName() [1/2]
void FPackageName::ObjectPathSplitFirstName (FAnsiStringView Text, FAnsiStringView & OutFirst, FAnsiStringView & OutRemainder) static
References Text.
ObjectPathSplitFirstName() [2/2]
void FPackageName::ObjectPathSplitFirstName (FWideStringView Text, FWideStringView & OutFirst, FWideStringView & OutRemainder) static
Splits an ObjectPath string into the first component and the remainder.
"/Path/To/A/Package.Object:SubObject" -> { "/Path/To/A/Package", "Object:SubObject" } "Object:SubObject" -> { "Object", "SubObject" } "Object.SubObject" -> { "Object", "SubObject" }
References Text.
ObjectPathToObjectName() [1/3]
FString FPackageName::ObjectPathToObjectName (const FString & InObjectPath) static
ObjectPathToObjectName() [2/3]
FAnsiStringView FPackageName::ObjectPathToObjectName (FAnsiStringView InObjectPath) static
ObjectPathToObjectName() [3/3]
FWideStringView FPackageName::ObjectPathToObjectName (FWideStringView InObjectPath) static
Returns the name of the leaf object referred to by the specified object path.
Examples: "/Game/MyAsset.MyAsset:SubObject.AnotherObject" -> "AnotherObject" "/Game/MyAsset.MyAsset:SubObject" -> "SubObject" "/Game/MyAsset.MyAsset" -> "MyAsset" "/Game/MyAsset" -> "/Game/MyAsset"
ObjectPathToOuterPath() [1/3]
FString FPackageName::ObjectPathToOuterPath (const FString & InObjectPath) static
ObjectPathToOuterPath() [2/3]
FAnsiStringView FPackageName::ObjectPathToOuterPath (FAnsiStringView InObjectPath) static
ObjectPathToOuterPath() [3/3]
FWideStringView FPackageName::ObjectPathToOuterPath (FWideStringView InObjectPath) static
Returns the path name of the outer of the leaf object referred to by the specified object path.
Examples: "/Game/MyAsset.MyAsset:SubObject.AnotherObject" -> "/Game/MyAsset.MyAsset:SubObject" "/Game/MyAsset.MyAsset:SubObject" -> "/Game/MyAsset.MyAsset" "/Game/MyAsset.MyAsset" -> "/Game/MyAsset" "/Game/MyAsset" -> ""
ObjectPathToPackageName() [1/3]
FString FPackageName::ObjectPathToPackageName (const FString & InObjectPath) static
ObjectPathToPackageName() [2/3]
FAnsiStringView FPackageName::ObjectPathToPackageName (FAnsiStringView InObjectPath) static
ObjectPathToPackageName() [3/3]
FWideStringView FPackageName::ObjectPathToPackageName (FWideStringView InObjectPath) static
Returns the name of the package referred to by the specified object path.
Examples: "/Game/MyAsset.MyAsset:SubObject.AnotherObject" -> "/Game/MyAsset" "/Game/MyAsset.MyAsset:SubObject" -> "/Game/MyAsset" "/Game/MyAsset.MyAsset" -> "/Game/MyAsset" "/Game/MyAsset" -> "/Game/MyAsset"
ObjectPathToPathWithinPackage() [1/3]
FString FPackageName::ObjectPathToPathWithinPackage (const FString & InObjectPath) static
ObjectPathToPathWithinPackage() [2/3]
FAnsiStringView FPackageName::ObjectPathToPathWithinPackage (FAnsiStringView InObjectPath) static
ObjectPathToPathWithinPackage() [3/3]
FWideStringView FPackageName::ObjectPathToPathWithinPackage (FWideStringView InObjectPath) static
Returns any remaining object path after trimming the package name from the specified object path.
Examples: "/Game/MyAsset.MyAsset:SubObject.AnotherObject" -> "MyAsset:SubObject.AnotherObject" "/Game/MyAsset.MyAsset:SubObject" -> "MyAsset:SubObject" "/Game/MyAsset.MyAsset" -> "MyAsset" "/Game/MyAsset" -> ""
ObjectPathToSubObjectPath() [1/3]
FString FPackageName::ObjectPathToSubObjectPath (const FString & InObjectPath) static
ObjectPathToSubObjectPath() [2/3]
FAnsiStringView FPackageName::ObjectPathToSubObjectPath (FAnsiStringView InObjectPath) static
ObjectPathToSubObjectPath() [3/3]
FWideStringView FPackageName::ObjectPathToSubObjectPath (FWideStringView InObjectPath) static
Returns the path from (and including) the subobject referred to by the specified object path.
Examples: "/Game/MyAsset.MyAsset:SubObject.AnotherObject" -> "SubObject.AnotherObject" "/Game/MyAsset.MyAsset:SubObject" -> "SubObject" "/Game/MyAsset.MyAsset" -> "MyAsset" "/Game/MyAsset" -> "/Game/MyAsset"
OnContentPathDismounted()
FOnContentPathDismountedEvent & FPackageName::OnContentPathDismounted () inline static
Definition at line 671 of file PackageName.h.
References OnContentPathDismountedEvent.
OnContentPathMounted()
FOnContentPathMountedEvent & FPackageName::OnContentPathMounted () inline static
Definition at line 664 of file PackageName.h.
References OnContentPathMountedEvent.
OnCoreUObjectInitialized()
void FPackageName::OnCoreUObjectInitialized () static
If the FLongPackagePathsSingleton is not created yet, this function will create it and thus allow mount points to be added.
ParseExportTextPath() [1/4]
bool FPackageName::ParseExportTextPath (const FString & InExportTextPath, FString * OutClassName, FString * OutObjectPath) static
ParseExportTextPath() [2/4]
bool FPackageName::ParseExportTextPath (const TCHAR * InExportTextPath, FStringView * OutClassName, FStringView * OutObjectPath) static
ParseExportTextPath() [3/4]
bool FPackageName::ParseExportTextPath (FAnsiStringView InExportTextPath, FAnsiStringView * OutClassName, FAnsiStringView * OutObjectPath) static
ParseExportTextPath() [4/4]
bool FPackageName::ParseExportTextPath (FWideStringView InExportTextPath, FWideStringView * OutClassName, FWideStringView * OutObjectPath) static
Converts the supplied export text path to an object path and class name.
Parameters
InExportTextPath The export text path for an object. Takes on the form: ClassName'ObjectPath'
OutClassName The name of the class at the start of the path.
OutObjectPath The path to the object.
Returns
True if the supplied export text path could be parsed
QueryMountPointLocalAbsPaths()
TArray< FString > FPackageName::QueryMountPointLocalAbsPaths () static
Returns all of the local paths on disk of the root content paths, like "c:\MyProjects\ProjectA\Content", "d:\Unreal\Engine\Content", "c:\MyProjects\ProjectA\Plugins\MyPlugin\Content".
QueryRootContentPaths()
void FPackageName::QueryRootContentPaths (TArray< FString > & OutRootContentPaths, bool bIncludeReadOnlyRoots = false, bool bWithoutLeadingSlashes = false, bool bWithoutTrailingSlashes = false) static
Queries all of the root content paths, like "/Game/", "/Engine/", and any dynamically added paths.
Parameters
OutRootContentPaths [Out] List of content paths
bIncludeReadOnlyRoots Include read only root content paths such as "/Temp/"
bWithoutLeadingSlashes Strip slash at start of each path to end up with "Game/"
bWithoutTrailingSlashes Strip trailing slash at end of each path to end up with "/Game"
RegisterMountPoint()
void FPackageName::RegisterMountPoint (const FString & RootPath, const FString & ContentPath) static
This will insert a mount point at the head of the search chain (so it can overlap an existing mount point and win).
If you register a mount point (even if you do so only in certain circumstances) consider also adding a handler for GetExplanationForUnavailablePackage to help debug cases where a package can't be found
Parameters
RootPath Logical Root Path.
ContentPath Content Path on disk.
RegisterShortPackageNamesForUObjectModules()
void FPackageName::RegisterShortPackageNamesForUObjectModules () static
Registers all short package names found in ini files.
SearchForPackageOnDisk()
bool FPackageName::SearchForPackageOnDisk (const FString & PackageName, FString * OutLongPackageName = NULL, FString * OutFilename = NULL) static
Attempts to find a package given its short name on disk (very slow).
Parameters
PackageName Package to find.
OutLongPackageName Long package name corresponding to the found file (if any).
Returns
true if the specified package name points to an existing package, false otherwise.
References OutFilename, and PackageName.
SplitFullObjectPath() [1/4]
void FPackageName::SplitFullObjectPath (const FString & InFullObjectPath, FString & OutClassName, FString & OutPackageName, FString & OutObjectName, FString & OutSubObjectName, bool bDetectClassName = true) static
Split a full object path (Class /Path/To/A/Package.Object:Subobject1.Subobject2) into its constituent pieces.
Parameters
InFullObjectPath Full object path we want to split
OutClassName The extracted class name (Class)
OutPackageName The extracted package name (/Path/To/A/Package)
OutObjectName The extracted object name (Object)
OutSubObjectName The extracted subobject name (Subobject1.Subobject2) - Note: nested subobjects are not split
bDetectClassName If true, the optional Class will be detected and separated based on a space. If false, and there is a space, the space and text before it will be included in the other names. Spaces in those names is invalid, but some code ignores the invalidity in ObjectName if it only cares about packageName.
SplitFullObjectPath() [2/4]
void FPackageName::SplitFullObjectPath (const FString & InFullObjectPath, FString & OutClassName, FString & OutPackageName, FString & OutObjectName, TArray< FString > & OutSubobjectNames, bool bDetectClassName = true) static
Split a full object path (Class /Path/To/A/Package.Object:Subobject1.Subobject2) into its constituent pieces.
All subobjects are split individually and stored in an array.
Parameters
InFullObjectPath Full object path we want to split
OutClassName The extracted class name (Class)
OutPackageName The extracted package name (/Path/To/A/Package)
OutSubobjectNames The extracted object name (Object)
OutSubObjectName The extracted subobject names (Subobject1 and Subobject2)
bDetectClassName If true, the optional Class will be detected and separated based on a space. If false, and there is a space, the space and text before it will be included in the other names. Spaces in those names is invalid, but some code ignores the invalidity in ObjectName if it only cares about packageName.
SplitFullObjectPath() [3/4]
void FPackageName::SplitFullObjectPath (FStringView InFullObjectPath, FStringView & OutClassName, FStringView & OutPackageName, FStringView & OutObjectName, FStringView & OutSubObjectName, bool bDetectClassName = true) static
SplitFullObjectPath() [4/4]
void FPackageName::SplitFullObjectPath (FStringView InFullObjectPath, FStringView & OutClassName, FStringView & OutPackageName, FStringView & OutObjectName, TArray< FStringView > & OutSubobjectNames, bool bDetectClassName = true) static
SplitLongPackageName()
bool FPackageName::SplitLongPackageName (const FString & InLongPackageName, FString & OutPackageRoot, FString & OutPackagePath, FString & OutPackageLeafName, const bool bStripRootLeadingSlash = false) static
Test whether a given packagename is in a valid root, and convert it to root, path, and leafname components.
If not in a valid root, all output arguments are reset to empty.
Parameters
InLongPackageName Package Name, e.g. "/Game/Maps/TestMaps/MyMap". Also supports packagenames with extension (which are not valid package names), e.g. /Game/Maps/TestMaps/MyMap.umap.
OutPackageRoot The package root path, eg "/Game/"
OutPackagePath The path from the mount point to the package, eg "Maps/TestMaps/ @param OutPackageLeafName The leaf name, including extension if present, eg "MyMap" or "MyMap.umap". @param bStripRootLeadingSlash: If false, OutpackageRoot="/<RootName>/", otherwise "<RootName>/".
Returns
Whether the path is in a valid root.
SplitPackageName() [1/2]
void FPackageName::SplitPackageName (const FString & InLongPackageName, FString * OutPackageRoot, FString * OutPackagePath, FString * OutPackageLeafName, EPathFormatFlags Flags = EPathFormatFlags::MountPointSlashes) static
References Flags, and MountPointSlashes.
SplitPackageName() [2/2]
void FPackageName::SplitPackageName (FStringView InPackageName, FStringView * OutPackageRoot, FStringView * OutPackagePath, FStringView * OutPackageLeafName, EPathFormatFlags Flags = EPathFormatFlags::MountPointSlashes) static
Convert a long package name into root, path, and leafname components.
For the FStringView version, the returned FStringViews are views into the input FStringView.
Parameters
InLongPackageName Package Name, e.g. "/Game/Maps/TestMaps/MyMap". Also supports packagenames with extension (which are not valid package names), e.g. /Game/Maps/TestMaps/MyMap.umap.
OutPackageRoot The package root path, eg "/Game/"
OutPackagePath The path from the mount point to the package, eg "Maps/TestMaps/ @param OutPackageLeafName The leaf name, including extension if present, eg "MyMap" or "MyMap.umap". @param Flags Flags specifying which characters are included in OutputPackageRoot, @see EPathFormatFlags. Edge cases examples: "" -> "","","" "/" -> "", "", "" "/root" -> "", "", "" "/root/" -> "/root/", "", "" "/root/leaf" -> "/root/", "", "leaf" "/root/path/" -> "/root/", "path/", "" "/root/path/leaf" -> "/root/", "path/", "leaf"
References Flags, and MountPointSlashes.
SplitPackageNameRoot() [1/2]
FString FPackageName::SplitPackageNameRoot (FName InPackageName, FString * OutRelativePath, EPathFormatFlags Flags = EPathFormatFlags::MountPointNoSlashes) static
References Flags, and MountPointNoSlashes.
SplitPackageNameRoot() [2/2]
FStringView FPackageName::SplitPackageNameRoot (FStringView InPackageName, FStringView * OutRelativePath, EPathFormatFlags Flags = EPathFormatFlags::MountPointNoSlashes) static
Returns the top level 'directory' in a package name.
If the package is part of a plugin, the root will be the name of the associated plugin, otherwise it will be 'Engine' or 'Game'.
Note the slashes are removed by default (EPathFormatFlags::MountPointNoSlashes),
See also
EPathFormatFlags.
Default: "/PackageRoot/Path/Leaf" -> (return "PackageRoot"; OutRelativePath = "Path/Leaf") With EPathFormatFlags::MountPointSlashes: "/PackageRoot/Path/Leaf" -> (return "/PackageRoot/"; OutRelativePath = "Path/Leaf")
References Flags, and MountPointNoSlashes.
TryConvertFilenameToLongPackageName() [1/2]
bool FPackageName::TryConvertFilenameToLongPackageName (const FString & InFilename, FString & OutPackageName, FString * OutFailureReason = nullptr, const EConvertFlags Flags = EConvertFlags::None) static
Tries to convert the supplied relative or absolute filename to a long package name/path starting with a root like /game This works on both package names and directories, and it does not validate that it actually exists on disk.
Parameters
InFilename Filename to convert.
OutPackageName The resulting long package name if the conversion was successful.
OutFailureReason Description of an error if the conversion failed.
Flags Modifies the behaviour of how filename conversions are applied.
Returns
Returns true if the supplied filename properly maps to one of the long package roots.
References Flags, and None.
TryConvertFilenameToLongPackageName() [2/2]
bool FPackageName::TryConvertFilenameToLongPackageName (FStringView InFilename, FStringBuilderBase & OutPackageName, FStringBuilderBase * OutFailureReason = nullptr, const EConvertFlags Flags = EConvertFlags::None) static
References Flags, and None.
TryConvertGameRelativePackagePathToLocalPath()
bool FPackageName::TryConvertGameRelativePackagePathToLocalPath (FStringView RelativePackagePath, FString & OutLocalPath) static
Tries to convert a file or directory in game-relative package name format to the corresponding local path Game-relative package names can be a full package path (/Game/Folder/File, /Engine/Folder/File, /PluginName/Folder/File) or a relative path (Folder/File).
Full package paths must be in a mounted directory to be successfully converted.
Parameters
RelativePackagePath The path in game-relative package format (allowed to have or not have an extension).
OutLocalPath The corresponding local-path file (with the extension or lack of extension from the input).
Returns
Whether the conversion was successful.
TryConvertLongPackageNameToFilename() [1/2]
bool FPackageName::TryConvertLongPackageNameToFilename (const FString & InLongPackageName, FString & OutFilename, const FString & InExtension = TEXT("")) static
Tries to convert a long package name to a file name with the supplied extension.
This can be called on package paths as well, provide no extension in that case
Parameters
InLongPackageName Long Package Name
InExtension Package extension.
Returns
Package filename.
References OutFilename.
TryConvertLongPackageNameToFilename() [2/2]
bool FPackageName::TryConvertLongPackageNameToFilename (FStringView InLongPackageName, FString & OutFilename, FStringView InExtension = {}) static
References OutFilename.
TryConvertScriptPackageNameToModuleName()
bool FPackageName::TryConvertScriptPackageNameToModuleName (FStringView PackageName, FStringView & OutModuleName) static
If PackageName is a script package (/Script/<ModuleName>), return true and set OutModuleName=<ModuleName>
References PackageName.
TryConvertShortPackagePathToLongInObjectPath()
bool FPackageName::TryConvertShortPackagePathToLongInObjectPath (const FString & ObjectPath, FString & ConvertedObjectPath) static
Tries to convert object path with short package name to object path with long package name found on disk (very slow)
Parameters
ObjectPath Path to the object.
OutLongPackageName Converted object path.
Returns
True if succeeded. False otherwise.
References ObjectPath.
TryConvertToMountedPackagePath()
bool FPackageName::TryConvertToMountedPackagePath (const FString & InPath, FPackagePath & OutPackagePath, EErrorCode & OutFailureReason) static private
Internal helper to create a FPackagePath given LocalFilePath or PackageName, and if found, return the MountPoint, RelativePath, and PackageExtension.
Parameters
InPath The path to test, either a LocalFilePath, PackageName, or ObjectPath
OutPackagePath FPackagePath to store the converted InPath
OutFailureReason it is set to the failurereason if the MountPoint is not found, otherwise it is set to EErrorCode::PackageNameUnknown
Returns
True if InPath be converted (was not malformed)
References FPackagePath.
TryConvertToMountedPath()
bool FPackageName::TryConvertToMountedPath (FStringView InPath, FString * OutLocalPathNoExtension, FString * OutPackageName, FString * OutObjectName, FString * OutSubObjectName, FString * OutExtension, EFlexNameType * OutFlexNameType = nullptr, EErrorCode * OutFailureReason = nullptr) static
Find the MountPoint for a LocalPath, LongPackageName, or ObjectPath and return its elements.
Use this function instead of TryConvertFilenameToLongPackageName or TryConvertLongPackageNameToFilename if you need to handle InPaths that might be ObjectPaths.
Parameters
InPath The LocalPath (with path,name,extension), PackageName, or ObjectPath we want to
OutLocalPathNoExtension If non-null, will be set to the LocalPath with path and basename but not extension, or empty string if input was not mounted
OutPackageName If non-null, will be set to the LongPackageName, or empty string if input was not mounted
OutObjectName If non-null, will be set to the ObjectName, or empty string if the input was a LocalPath or PackageName or was not mounted
OutSubObjectName If non-null, will be set to the SubObjectName, or empty string if the input was a LocalPath or PackageName or was not mounted
OutExtension If non-null, will be set to the LocalPath's extension, or empty string if the input was not a LocalPath or was not mounted
OutFlexNameType If non-null, will be set to the FlexNameType of InPath.
OutFailureReason If non-null, will be set to the reason InPath could not be converted, or to EErrorCode::Unknown if the function was successful.
TryConvertToMountedPathComponents()
bool FPackageName::TryConvertToMountedPathComponents (FStringView InPath, FStringBuilderBase & OutMountPointPackageName, FStringBuilderBase & OutMountPointFilePath, FStringBuilderBase & OutRelPath, FStringBuilderBase & OutObjectName, EPackageExtension & OutExtension, FStringBuilderBase & OutCustomExtension, EFlexNameType * OutFlexNameType = nullptr, EErrorCode * OutFailureReason = nullptr) static private
Internal helper to find a mount point that contains the given LocalFilePath or PackageName, and if found, return the MountPoint, RelativePath, and PackageExtension.
Parameters
InPath The path to test, either a LocalFilePath, PackageName, or ObjectPath
OutMountPointPackageName If the MountPoint is found, the PackageName of the MountPoint is copied into this variable, otherwise it is set to empty string
OutMountPointFilePath If the MountPoint is found, the LocalFilePath of the MountPoint is copied into this variable, otherwise it is set to empty string
OutRelPath If the MountPoint is found, the RelativePath from the MountPoint to the PackageName is copied into this variable, otherwise it is set to empty string
OutObjectPath If the MountPoint is found and InPath was an ObjectPath, this variable is set to the object's relative path from the package: ObjectPath:SubObject1.SubObject2, otherwise it is set to the empty string
OutExtension If the MountPoint is found and InPath was a LocalFilePath, this variable is set to the EPackageExtension that was in the filepath, otherwise it is set to EPackageExtension::Unspecified
OutCustomExtension If the mount point was found and InPath was a filepath with extension and the extension was not a recognized package extension, this varialbe is set to the extension text (including .), otherwise it is set to the empty string
OutFlexNameType If non-null, it is set to whether InFilePathOrPackageName is a PackageName or Filename if the MountPoint is found, otherwise it is set to EFlexNameType::Invalid
OutFailureReason If non-null, it is set to the failurereason if the MountPoint is not found, otherwise it is set to EErrorCode::PackageNameUnknown
Returns
True if the MountPoint was found, else false
TryGetMountPointForPath()
bool FPackageName::TryGetMountPointForPath (FStringView InFilePathOrPackageName, FStringBuilderBase & OutMountPointPackageName, FStringBuilderBase & OutMountPointFilePath, FStringBuilderBase & OutRelPath, EFlexNameType * OutFlexNameType = nullptr, EErrorCode * OutFailureReason = nullptr) static
Find a mount point that contains the given LocalFilePath or PackageName, and if found, return the MountPoint and RelativePath.
Parameters
InFilePathOrPackageName The path to test, either a LocalFilePath or a PackageName or an ObjectPath
OutMountPointPackageName If the MountPoint is found, the PackageName of the MountPoint is copied into this variable, otherwise it is set to empty string
OutMountPointFilePath If the MountPoint is found, the LocalFilePath of the MountPoint is copied into this variable, otherwise it is set to empty string
OutRelPath If the MountPoint is found, the RelativePath from the MountPoint to InFilePathOrPackageName is copied into this variable, otherwise it is set to empty string If InFilePathOrPackageName was a filepath, the extension is removed before copying it into OutRelpath The OutRelPath is the same for both the LocalFilePath and the PackageName
OutFlexNameType If non-null, will be set to whether InFilePathOrPackageName was a PackageName or Filename if the MountPoint is found, otherwise it is set to EFlexNameType::Invalid
OutFailureReason If non-null, will be set to the reason InPath could not be converted, or to EErrorCode::Unknown if the function was successful.
Returns
True if the MountPoint was found, else false
UE_DEPRECATED() [1/2]
FPackageName::UE_DEPRECATED (5. 0, "Deprecated. UPackage::Guid has not been used by the engine for a long time. Call DoesPackageExist without a Guid.") const &
Checks if the package exists on disk.
Parameters
LongPackageName Package name.
Guid If nonnull, and the package is found on disk but does not have this PackageGuid in its FPackageFileSummary::Guid, false is returned
OutFilename Package filename on disk.
InAllowTextFormats Detect text format packages as well as binary (priority to text)
Returns
true if the specified package name points to an existing package, false otherwise.
UE_DEPRECATED() [2/2]
FPackageName::UE_DEPRECATED (5. 0, "Specifying AllowTextFormats is no longer supported. Text format is instead specified as a field on the result struct from IPackageResourceManager->OpenReadPackage.") const &
UnRegisterMountPoint()
void FPackageName::UnRegisterMountPoint (const FString & RootPath, const FString & ContentPath) static
This will remove a previously inserted mount point.
Parameters
RootPath Logical Root Path.
ContentPath Content Path on disk.
Friends And Related Symbol Documentation
::UE::AssetRegistry::Impl::FScanPathContext
friend struct ::UE::AssetRegistry::Impl::FScanPathContext friend
Definition at line 1039 of file PackageName.h.
FAssetRegistryConsoleCommands
friend class FAssetRegistryConsoleCommands friend
Definition at line 1037 of file PackageName.h.
References FAssetRegistryConsoleCommands.
Referenced by FAssetRegistryConsoleCommands.
FPackagePath
friend class FPackagePath friend
Definition at line 1034 of file PackageName.h.
References FPackagePath.
Referenced by DoesPackageExist(), DoesPackageExist(), DoesPackageExistEx(), FPackagePath, InternalDoesPackageExistEx(), InternalDoesPackageExistEx(), and TryConvertToMountedPackagePath().
UAssetRegistryImpl
friend class UAssetRegistryImpl friend
Definition at line 1038 of file PackageName.h.
References UAssetRegistryImpl.
Referenced by UAssetRegistryImpl.
Field Documentation
DoesPackageExistOverrideDelegate
FDoesPackageExistOverride FPackageName::DoesPackageExistOverrideDelegate static private
Delegate used to check whether a package exist without using the filesystem.
Definition at line 1032 of file PackageName.h.
Referenced by DoesPackageExistOverride().
Guid
const FGuid* FPackageName::Guid
Definition at line 368 of file PackageName.h.
InAllowTextFormats [1/2]
const FGuid FString bool FPackageName::InAllowTextFormats
Initial value:
= true)
    {
        return DoesPackageExist(LongPackageName, OutFilename, InAllowTextFormats);
    }
    static 1 bool DoesPackageExist(const FString& LongPackageName, FString* OutFilename = nullptr, bool InAllowTextFormats = true)
Definition at line 368 of file PackageName.h.
InAllowTextFormats [2/2]
FString bool FPackageName::InAllowTextFormats
Definition at line 937 of file PackageName.h.
OnContentPathDismountedEvent
FOnContentPathDismountedEvent FPackageName::OnContentPathDismountedEvent static private
Event that is triggered when a new content path is removed.
Definition at line 1029 of file PackageName.h.
Referenced by OnContentPathDismounted().
OnContentPathMountedEvent
FOnContentPathMountedEvent FPackageName::OnContentPathMountedEvent static private
Event that is triggered when a new content path is mounted.
Definition at line 1026 of file PackageName.h.
Referenced by OnContentPathMounted().
OutFilename [1/2]
const FGuid FString* FPackageName::OutFilename
Definition at line 368 of file PackageName.h.
Referenced by FindPackageFileWithoutExtension(), SearchForPackageOnDisk(), TryConvertLongPackageNameToFilename(), and TryConvertLongPackageNameToFilename().
OutFilename [2/2]
FString& FPackageName::OutFilename
Definition at line 937 of file PackageName.h.
The documentation for this class was generated from the following file:
Runtime/CoreUObject/Public/Misc/PackageName.h