Unreal Engine 5.6 C++ API: ACameraActor Class Reference
ACameraActor Class Reference
#include "CameraActor.h"
Public Member Functions
class UCameraComponent * GetCameraComponent () const
Returns CameraComponent subobject.
virtual class USceneComponent * GetDefaultAttachComponent () const override
virtual void NotifyCameraCut ()
Called to notify that this camera was cut to, so it can update things like interpolation if necessary.
virtual void PostLoadSubobjects (FObjectInstancingGraph *OuterInstanceGraph) override
virtual void Serialize (FArchive &Ar) override
UFUNCTION () 1 int32 GetAutoActivatePlayerIndex() const
Returns index of the player for whom we auto-activate, or INDEX_NONE (-1) if disabled.
Protected Member Functions
virtual void BeginPlay () override
Private Member Functions
UPROPERTY() uint32 bConstrainAspectRatio_DEPRECATED UPROPERTY () float AspectRatio_DEPRECATED
UPROPERTY () float FOVAngle_DEPRECATED
UPROPERTY () float PostProcessBlendWeight_DEPRECATED
UPROPERTY () struct FPostProcessSettings PostProcessSettings_DEPRECATED
UPROPERTY ()) TObjectPtr< class UCameraComponent > CameraComponent
Specifies which player controller, if any, should automatically use this Camera when the controller is active.
UPROPERTY ()) TObjectPtr< class USceneComponent > SceneComponent
Detailed Description
Definition at line 16 of file CameraActor.h.
Member Function Documentation
BeginPlay()
virtual void ACameraActor::BeginPlay () override protected virtual
GetCameraComponent()
class UCameraComponent * ACameraActor::GetCameraComponent () const inline
Returns CameraComponent subobject.
Definition at line 75 of file CameraActor.h.
GetDefaultAttachComponent()
virtual class USceneComponent * ACameraActor::GetDefaultAttachComponent () const override virtual
NotifyCameraCut()
virtual void ACameraActor::NotifyCameraCut () inline virtual
Called to notify that this camera was cut to, so it can update things like interpolation if necessary.
Typically called by the camera component.
Definition at line 81 of file CameraActor.h.
PostLoadSubobjects()
virtual void ACameraActor::PostLoadSubobjects (FObjectInstancingGraph * OuterInstanceGraph) override virtual
Serialize()
virtual void ACameraActor::Serialize (FArchive & Ar) override virtual
References Ar, and Serialize().
Referenced by Serialize().
UFUNCTION()
ACameraActor::UFUNCTION () const
Returns index of the player for whom we auto-activate, or INDEX_NONE (-1) if disabled.
References Category, UFUNCTION(), and UPROPERTY().
Referenced by UFUNCTION().
UPROPERTY() [1/6]
UPROPERTY() uint32 bConstrainAspectRatio_DEPRECATED ACameraActor::UPROPERTY () private
References UPROPERTY().
UPROPERTY() [2/6]
ACameraActor::UPROPERTY () private
References UPROPERTY().
UPROPERTY() [3/6]
ACameraActor::UPROPERTY () private
References UPROPERTY().
UPROPERTY() [4/6]
ACameraActor::UPROPERTY () private
References UPROPERTY().
UPROPERTY() [5/6]
ACameraActor::UPROPERTY () private
Specifies which player controller, if any, should automatically use this Camera when the controller is active.
The camera component for this camera
References Category, and meta.
Referenced by UFUNCTION(), UPROPERTY(), UPROPERTY(), UPROPERTY(), UPROPERTY(), and UPROPERTY().
UPROPERTY() [6/6]
ACameraActor::UPROPERTY () private
References Category, meta, and UPROPERTY().
The documentation for this class was generated from the following file:
Runtime/Engine/Classes/Camera/CameraActor.h