Unreal Engine 5.6 C++ API: FHashedName Class Reference
FHashedName Class Reference
#include "MemoryImage.h"
Public Member Functions
FHashedName ()
FHashedName (const FHashedName &InName)
FHashedName (const FName &InName)
FHashedName (const FString &InString)
FHashedName (const TCHAR *InString)
FHashedName (uint64 InHash)
uint64 GetHash () const
bool IsNone () const
bool operator!= (const FHashedName &Rhs) const
bool operator< (const FHashedName &Rhs) const
For sorting by name.
FHashedName & operator= (const FHashedName &InName)
bool operator== (const FHashedName &Rhs) const
Private Member Functions
DECLARE_EXPORTED_TYPE_LAYOUT (FHashedName, 1, NonVirtual)
LAYOUT_FIELD (uint64, Hash)
LAYOUT_FIELD_EDITORONLY (FHashedNameDebugString, DebugString)
void Save (FCbWriter &Writer) const
bool TryLoad (FCbFieldView Field)
Friends
uint32 GetTypeHash (const FHashedName &Name)
bool LoadFromCompactBinary (FCbFieldView Field, FHashedName &OutValue)
FArchive & operator<< (FArchive &Ar, FHashedName &String)
FCbWriter & operator<< (FCbWriter &Writer, const FHashedName &Value)
Detailed Description
Definition at line 857 of file MemoryImage.h.
Constructor & Destructor Documentation
FHashedName() [1/6]
FHashedName::FHashedName () inline
Definition at line 861 of file MemoryImage.h.
References Hash.
Referenced by FHashedName(), DECLARE_EXPORTED_TYPE_LAYOUT(), GetTypeHash, LoadFromCompactBinary, operator!=(), operator<(), operator<<, operator<<, operator=(), and operator==().
FHashedName() [2/6]
FHashedName::FHashedName (uint64 InHash) explicit
FHashedName() [3/6]
FHashedName::FHashedName (const FHashedName & InName)
References FHashedName(), and InName.
FHashedName() [4/6]
FHashedName::FHashedName (const TCHAR * InString)
FHashedName() [5/6]
FHashedName::FHashedName (const FString & InString)
FHashedName() [6/6]
FHashedName::FHashedName (const FName & InName)
References InName.
Member Function Documentation
DECLARE_EXPORTED_TYPE_LAYOUT()
FHashedName::DECLARE_EXPORTED_TYPE_LAYOUT (FHashedName , 1 , NonVirtual) private
References FHashedName().
GetHash()
uint64 FHashedName::GetHash () const inline
Definition at line 869 of file MemoryImage.h.
References Hash.
IsNone()
bool FHashedName::IsNone () const inline
Definition at line 870 of file MemoryImage.h.
References Hash.
LAYOUT_FIELD()
FHashedName::LAYOUT_FIELD (uint64 , Hash) private
References Hash.
LAYOUT_FIELD_EDITORONLY()
FHashedName::LAYOUT_FIELD_EDITORONLY (FHashedNameDebugString , DebugString) private
operator!=()
bool FHashedName::operator!= (const FHashedName & Rhs) const inline
Definition at line 877 of file MemoryImage.h.
References FHashedName(), and Hash.
operator<()
bool FHashedName::operator< (const FHashedName & Rhs) const inline
For sorting by name.
Definition at line 880 of file MemoryImage.h.
References FHashedName(), and Hash.
operator=()
FHashedName & FHashedName::operator= (const FHashedName & InName)
References FHashedName(), and InName.
operator==()
bool FHashedName::operator== (const FHashedName & Rhs) const inline
Definition at line 876 of file MemoryImage.h.
References FHashedName(), and Hash.
Save()
void FHashedName::Save (FCbWriter & Writer) const private
TryLoad()
bool FHashedName::TryLoad (FCbFieldView Field) private
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FHashedName & Name) friend
Definition at line 888 of file MemoryImage.h.
References FHashedName(), GetTypeHash, and Name.
Referenced by GetTypeHash.
LoadFromCompactBinary
bool LoadFromCompactBinary (FCbFieldView Field, FHashedName & OutValue) friend
References FHashedName().
operator<< [1/2]
FArchive & operator<< (FArchive & Ar, FHashedName & String) friend
Definition at line 882 of file MemoryImage.h.
References FHashedName(), Ar, and String.
operator<< [2/2]
FCbWriter & operator<< (FCbWriter & Writer, const FHashedName & Value) friend
Definition at line 906 of file MemoryImage.h.
References FHashedName(), and Value.
The documentation for this class was generated from the following file:
Runtime/Core/Public/Serialization/MemoryImage.h