Unreal Engine 5.6 C++ API: TStaticBitArray< NumBits > Class Template Reference
TStaticBitArray< NumBits > Class Template Reference
A statically sized bit array.
#include "StaticBitArray.h"
Data Structures
struct FBoolType
Public Member Functions
FORCEINLINE TStaticBitArray ()
Minimal initialization constructor.
FORCEINLINE TStaticBitArray (bool, uint32 InBitIndex)
Constructor to initialize to a single bit.
TStaticBitArray (const FString &Str)
Constructor to initialize from string.
FORCEINLINE bool HasAnyBitsSet () const
FORCEINLINE operator bool () const
FORCEINLINE TStaticBitArray & operator&= (const TStaticBitArray &Other)
FORCEINLINE bool operator== (const TStaticBitArray< NumBits > &B) const
FORCEINLINE TStaticBitReference< WordType > operator[] (int32 Index)
FORCEINLINE const TConstStaticBitReference< WordType > operator[] (int32 Index) const
FORCEINLINE TStaticBitArray & operator^= (const TStaticBitArray &Other)
FORCEINLINE TStaticBitArray & operator|= (const TStaticBitArray &Other)
UE_DEPRECATED (5.4, "Comparing a TStaticBitArray to zero has been deprecated - please use !BitArray.HasAnyBitsSet() instead") friend FORCEINLINE bool operator
This operator only exists to disambiguate == in statements of the form (flags == 0)
UE_DEPRECATED (5.4, "Implicitly constructing a TStaticBitArray from 0 has been deprecated - please use the default constructor instead") FORCEINLINE TStaticBitArray(UnspecifiedZeroType)
Constructor that allows initializing by assignment from 0.
Static Public Member Functions
static FORCEINLINE int32 Num ()
Private Types
typedef int32 *FBoolType::* UnspecifiedBoolType
typedef float *FBoolType::* UnspecifiedZeroType
typedef uint64 WordType
Private Member Functions
FORCEINLINE void Clear_ ()
Resets the bit array to a 0 value.
void ErrorInvalid_ () const
Reports an invalid string element in the bitset conversion.
void Trim_ ()
Clears any trailing bits in the last word.
Private Attributes
WordType Words [NumWords]
Static Private Attributes
static constexpr uint32 NumBitsPerWord = sizeof(WordType) * 8
static constexpr uint32 NumBitsPerWordLog2 = 6
static constexpr uint32 NumWords = ((NumBits + NumBitsPerWord - 1) & ~(NumBitsPerWord - 1)) / NumBitsPerWord
Friends
FORCEINLINE TStaticBitArray< NumBits > operator& (const TStaticBitArray< NumBits > &A, const TStaticBitArray< NumBits > &B)
FORCEINLINE TStaticBitArray< NumBits > operator^ (const TStaticBitArray< NumBits > &A, const TStaticBitArray< NumBits > &B)
FORCEINLINE TStaticBitArray< NumBits > operator| (const TStaticBitArray< NumBits > &A, const TStaticBitArray< NumBits > &B)
FORCEINLINE TStaticBitArray< NumBits > operator~ (const TStaticBitArray< NumBits > &A)
Detailed Description
template<uint32 NumBits>
class TStaticBitArray< NumBits >
A statically sized bit array.
Definition at line 74 of file StaticBitArray.h.
Member Typedef Documentation
UnspecifiedBoolType
template<uint32 NumBits> typedef int32* FBoolType::* TStaticBitArray< NumBits >::UnspecifiedBoolType private
Definition at line 79 of file StaticBitArray.h.
UnspecifiedZeroType
template<uint32 NumBits> typedef float* FBoolType::* TStaticBitArray< NumBits >::UnspecifiedZeroType private
Definition at line 80 of file StaticBitArray.h.
WordType
template<uint32 NumBits> typedef uint64 TStaticBitArray< NumBits >::WordType private
Definition at line 76 of file StaticBitArray.h.
Constructor & Destructor Documentation
TStaticBitArray() [1/3]
template<uint32 NumBits> FORCEINLINE TStaticBitArray< NumBits >::TStaticBitArray () inline nodiscard
Minimal initialization constructor.
Definition at line 85 of file StaticBitArray.h.
References Clear_(), and FORCEINLINE.
Referenced by operator&, operator&=(), operator==(), operator^, operator^=(), operator|, operator|=(), operator~, and UE_DEPRECATED().
TStaticBitArray() [2/3]
template<uint32 NumBits> FORCEINLINE TStaticBitArray< NumBits >::TStaticBitArray (bool , uint32 InBitIndex) inline nodiscard
Constructor to initialize to a single bit.
Definition at line 100 of file StaticBitArray.h.
References check, FORCEINLINE, NumBitsPerWord, NumWords, Word, and Words.
TStaticBitArray() [3/3]
template<uint32 NumBits> TStaticBitArray< NumBits >::TStaticBitArray (const FString & Str) inline explicit nodiscard
Constructor to initialize from string.
Definition at line 125 of file StaticBitArray.h.
References Clear_(), ErrorInvalid_(), operator[](), and TEXT.
Member Function Documentation
Clear_()
template<uint32 NumBits> FORCEINLINE void TStaticBitArray< NumBits >::Clear_ () inline private
Resets the bit array to a 0 value.
Definition at line 407 of file StaticBitArray.h.
References FORCEINLINE, NumWords, and Words.
Referenced by TStaticBitArray(), TStaticBitArray(), and UE_DEPRECATED().
ErrorInvalid_()
template<uint32 NumBits> void TStaticBitArray< NumBits >::ErrorInvalid_ () const inline private
Reports an invalid string element in the bitset conversion.
Definition at line 430 of file StaticBitArray.h.
References LowLevelFatalError, and TEXT.
Referenced by TStaticBitArray().
HasAnyBitsSet()
template<uint32 NumBits> FORCEINLINE bool TStaticBitArray< NumBits >::HasAnyBitsSet () const inline nodiscard
Definition at line 151 of file StaticBitArray.h.
References FORCEINLINE, NumWords, and Words.
Referenced by operator bool().
Num()
template<uint32 NumBits> FORCEINLINE int32 TStaticBitArray< NumBits >::Num () inline static nodiscard
Definition at line 169 of file StaticBitArray.h.
References FORCEINLINE.
operator bool()
template<uint32 NumBits> FORCEINLINE TStaticBitArray< NumBits >::operator bool () const inline explicit nodiscard
Definition at line 163 of file StaticBitArray.h.
References FORCEINLINE, and HasAnyBitsSet().
operator&=()
template<uint32 NumBits> FORCEINLINE TStaticBitArray & TStaticBitArray< NumBits >::operator&= (const TStaticBitArray< NumBits > & Other) inline
Definition at line 199 of file StaticBitArray.h.
References TStaticBitArray(), FORCEINLINE, NumWords, Other, and Words.
operator==()
template<uint32 NumBits> FORCEINLINE bool TStaticBitArray< NumBits >::operator== (const TStaticBitArray< NumBits > & B) const inline nodiscard
Definition at line 261 of file StaticBitArray.h.
References TStaticBitArray(), B, FORCEINLINE, NumWords, and Words.
operator[]() [1/2]
template<uint32 NumBits> FORCEINLINE TStaticBitReference< WordType > TStaticBitArray< NumBits >::operator[] (int32 Index) inline nodiscard
Definition at line 173 of file StaticBitArray.h.
References check, FORCEINLINE, NumBitsPerWord, and Words.
Referenced by TStaticBitArray().
operator[]() [2/2]
template<uint32 NumBits> FORCEINLINE const TConstStaticBitReference< WordType > TStaticBitArray< NumBits >::operator[] (int32 Index) const inline nodiscard
Definition at line 181 of file StaticBitArray.h.
References check, FORCEINLINE, NumBitsPerWord, and Words.
operator^=()
template<uint32 NumBits> FORCEINLINE TStaticBitArray & TStaticBitArray< NumBits >::operator^= (const TStaticBitArray< NumBits > & Other) inline
Definition at line 207 of file StaticBitArray.h.
References TStaticBitArray(), FORCEINLINE, NumWords, Other, and Words.
operator|=()
template<uint32 NumBits> FORCEINLINE TStaticBitArray & TStaticBitArray< NumBits >::operator|= (const TStaticBitArray< NumBits > & Other) inline
Definition at line 191 of file StaticBitArray.h.
References TStaticBitArray(), FORCEINLINE, NumWords, Other, and Words.
Trim_()
template<uint32 NumBits> void TStaticBitArray< NumBits >::Trim_ () inline private
Clears any trailing bits in the last word.
Definition at line 418 of file StaticBitArray.h.
References NumBitsPerWord, NumWords, and Words.
UE_DEPRECATED() [1/2]
template<uint32 NumBits> TStaticBitArray< NumBits >::UE_DEPRECATED (5. 4, "Comparing a TStaticBitArray< NumBits > to zero has been deprecated - please use !BitArray.HasAnyBitsSet() instead") nodiscard
This operator only exists to disambiguate == in statements of the form (flags == 0)
References TStaticBitArray(), A, FORCEINLINE, and Value.
UE_DEPRECATED() [2/2]
template<uint32 NumBits> TStaticBitArray< NumBits >::UE_DEPRECATED (5. 4, "Implicitly constructing a TStaticBitArray< NumBits > from 0 has been deprecated - please use the default constructor instead") inline nodiscard
Constructor that allows initializing by assignment from 0.
Definition at line 91 of file StaticBitArray.h.
References Clear_(), and FORCEINLINE.
Friends And Related Symbol Documentation
operator&
template<uint32 NumBits> FORCEINLINE TStaticBitArray< NumBits > operator& (const TStaticBitArray< NumBits > & A, const TStaticBitArray< NumBits > & B) friend
Definition at line 240 of file StaticBitArray.h.
References TStaticBitArray(), A, B, FORCEINLINE, NumWords, RESTRICT, and Words.
operator^
template<uint32 NumBits> FORCEINLINE TStaticBitArray< NumBits > operator^ (const TStaticBitArray< NumBits > & A, const TStaticBitArray< NumBits > & B) friend
Definition at line 255 of file StaticBitArray.h.
References TStaticBitArray(), A, B, and FORCEINLINE.
operator|
template<uint32 NumBits> FORCEINLINE TStaticBitArray< NumBits > operator| (const TStaticBitArray< NumBits > & A, const TStaticBitArray< NumBits > & B) friend
Definition at line 225 of file StaticBitArray.h.
References TStaticBitArray(), A, B, FORCEINLINE, NumWords, RESTRICT, and Words.
operator~
template<uint32 NumBits> FORCEINLINE TStaticBitArray< NumBits > operator~ (const TStaticBitArray< NumBits > & A) friend
Definition at line 215 of file StaticBitArray.h.
References TStaticBitArray(), A, FORCEINLINE, and NumWords.
Field Documentation
NumBitsPerWord
template<uint32 NumBits> uint32 TStaticBitArray< NumBits >::NumBitsPerWord = sizeof(WordType) * 8 static constexpr private
Definition at line 392 of file StaticBitArray.h.
Referenced by TStaticBitArray(), operator[](), operator[](), and Trim_().
NumBitsPerWordLog2
template<uint32 NumBits> uint32 TStaticBitArray< NumBits >::NumBitsPerWordLog2 = 6 static constexpr private
Definition at line 393 of file StaticBitArray.h.
NumWords
template<uint32 NumBits> uint32 TStaticBitArray< NumBits >::NumWords = ((NumBits + NumBitsPerWord - 1) & ~(NumBitsPerWord - 1)) / NumBitsPerWord static constexpr private
Definition at line 395 of file StaticBitArray.h.
Referenced by TStaticBitArray(), Clear_(), HasAnyBitsSet(), operator&, operator&=(), operator==(), operator^=(), operator|, operator|=(), operator~, and Trim_().
Words
template<uint32 NumBits> WordType TStaticBitArray< NumBits >::Words[NumWords] private
Definition at line 396 of file StaticBitArray.h.
Referenced by TStaticBitArray(), Clear_(), HasAnyBitsSet(), operator&, operator&=(), operator==(), operator[](), operator[](), operator^=(), operator|, operator|=(), and Trim_().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Containers/StaticBitArray.h