Unreal Engine 5.6 C++ API: UE::FSharedMutex Class Reference
UE::FSharedMutex Class Reference final
A four-byte shared mutex that is not fair and does not support recursive locking.
#include "SharedMutex.h"
Public Member Functions
constexpr FSharedMutex ()=default
FSharedMutex (const FSharedMutex &)=delete
void Lock ()
void LockShared ()
FSharedMutex & operator= (const FSharedMutex &)=delete
bool TryLock ()
bool TryLockShared ()
void Unlock ()
void UnlockShared ()
Private Member Functions
const void * GetLockAddress () const
const void * GetSharedLockAddress () const
void LockSharedSlow ()
void LockSlow ()
void WakeWaitingThread ()
void WakeWaitingThreads (uint32 LastState)
Private Attributes
std::atomic< uint32 > State = 0
Static Private Attributes
static constexpr uint32 IsLockedFlag = 1 << 0
static constexpr uint32 MayHaveWaitingLockFlag = 1 << 1
static constexpr uint32 MayHaveWaitingSharedLockFlag = 1 << 2
static constexpr uint32 SharedLockCountMask = 0xffff'fff8
static constexpr uint32 SharedLockCountShift = 3
Detailed Description
A four-byte shared mutex that is not fair and does not support recursive locking.
Prefer FMutex when shared locking is not required. All new shared locks will wait when any thread is waiting to take an exclusive lock. An exclusive lock and a shared lock may not be simultaneously held by the same thread.
Definition at line 21 of file SharedMutex.h.
Constructor & Destructor Documentation
FSharedMutex() [1/2]
UE::FSharedMutex::FSharedMutex () constexpr default
Referenced by FSharedMutex(), and operator=().
FSharedMutex() [2/2]
UE::FSharedMutex::FSharedMutex (const FSharedMutex &) delete
References FSharedMutex().
Member Function Documentation
GetLockAddress()
const void * UE::FSharedMutex::GetLockAddress () const private
GetSharedLockAddress()
const void * UE::FSharedMutex::GetSharedLockAddress () const private
Lock()
void UE::FSharedMutex::Lock () inline
Definition at line 37 of file SharedMutex.h.
References IsLockedFlag, LIKELY, LockSlow(), and State.
LockShared()
void UE::FSharedMutex::LockShared () inline
Definition at line 67 of file SharedMutex.h.
References IsLockedFlag, LIKELY, LockSharedSlow(), MayHaveWaitingLockFlag, SharedLockCountShift, and State.
LockSharedSlow()
void UE::FSharedMutex::LockSharedSlow () private
References UE_API.
Referenced by LockShared().
LockSlow()
void UE::FSharedMutex::LockSlow () private
References UE_API.
Referenced by Lock().
operator=()
FSharedMutex & UE::FSharedMutex::operator= (const FSharedMutex &) delete
References FSharedMutex().
TryLock()
bool UE::FSharedMutex::TryLock () inline
Definition at line 29 of file SharedMutex.h.
References IsLockedFlag, SharedLockCountMask, and State.
TryLockShared()
bool UE::FSharedMutex::TryLockShared () inline
Definition at line 59 of file SharedMutex.h.
References IsLockedFlag, MayHaveWaitingLockFlag, SharedLockCountShift, and State.
Unlock()
void UE::FSharedMutex::Unlock () inline
Definition at line 47 of file SharedMutex.h.
References checkSlow, IsLockedFlag, LIKELY, MayHaveWaitingLockFlag, MayHaveWaitingSharedLockFlag, State, and WakeWaitingThreads().
UnlockShared()
void UE::FSharedMutex::UnlockShared () inline
Definition at line 79 of file SharedMutex.h.
References checkSlow, LIKELY, MayHaveWaitingLockFlag, MayHaveWaitingSharedLockFlag, SharedLockCountMask, SharedLockCountShift, State, and WakeWaitingThread().
WakeWaitingThread()
void UE::FSharedMutex::WakeWaitingThread () private
References UE_API.
Referenced by UnlockShared().
WakeWaitingThreads()
void UE::FSharedMutex::WakeWaitingThreads (uint32 LastState) private
References UE_API.
Referenced by Unlock().
Field Documentation
IsLockedFlag
uint32 UE::FSharedMutex::IsLockedFlag = 1 << 0 static constexpr private
Definition at line 101 of file SharedMutex.h.
Referenced by Lock(), LockShared(), TryLock(), TryLockShared(), and Unlock().
MayHaveWaitingLockFlag
uint32 UE::FSharedMutex::MayHaveWaitingLockFlag = 1 << 1 static constexpr private
Definition at line 102 of file SharedMutex.h.
Referenced by LockShared(), TryLockShared(), Unlock(), and UnlockShared().
MayHaveWaitingSharedLockFlag
uint32 UE::FSharedMutex::MayHaveWaitingSharedLockFlag = 1 << 2 static constexpr private
Definition at line 103 of file SharedMutex.h.
Referenced by Unlock(), and UnlockShared().
SharedLockCountMask
uint32 UE::FSharedMutex::SharedLockCountMask = 0xffff'fff8 static constexpr private
Definition at line 105 of file SharedMutex.h.
Referenced by TryLock(), and UnlockShared().
SharedLockCountShift
uint32 UE::FSharedMutex::SharedLockCountShift = 3 static constexpr private
Definition at line 104 of file SharedMutex.h.
Referenced by LockShared(), TryLockShared(), and UnlockShared().
State
std::atomic<uint32> UE::FSharedMutex::State = 0 private
Definition at line 107 of file SharedMutex.h.
Referenced by Lock(), LockShared(), TryLock(), TryLockShared(), Unlock(), and UnlockShared().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Async/SharedMutex.h