Unreal Engine 5.6 C++ API: FStructBaseChain Class Reference
FStructBaseChain Class Reference
#include "Class.h"
Protected Member Functions
FStructBaseChain ()
FStructBaseChain (const FStructBaseChain &)=delete
~FStructBaseChain ()
FORCEINLINE bool IsChildOfUsingStructArray (const FStructBaseChain &Parent) const
FStructBaseChain & operator= (const FStructBaseChain &)=delete
void ReinitializeBaseChainArray ()
Private Attributes
int32 NumStructBasesInChainMinusOne
FStructBaseChain ** StructBaseChainArray
Friends
class UStruct
Detailed Description
Definition at line 363 of file Class.h.
Constructor & Destructor Documentation
FStructBaseChain() [1/2]
FStructBaseChain::FStructBaseChain () protected
Referenced by FStructBaseChain(), IsChildOfUsingStructArray(), and operator=().
~FStructBaseChain()
FStructBaseChain::~FStructBaseChain () protected
FStructBaseChain() [2/2]
FStructBaseChain::FStructBaseChain (const FStructBaseChain &) protected delete
References FStructBaseChain().
Member Function Documentation
IsChildOfUsingStructArray()
FORCEINLINE bool FStructBaseChain::IsChildOfUsingStructArray (const FStructBaseChain & Parent) const inline protected
Definition at line 375 of file Class.h.
References FStructBaseChain(), FORCEINLINE, NumStructBasesInChainMinusOne, Parent, and StructBaseChainArray.
Referenced by UStruct::UObjectBaseUtility.
operator=()
FStructBaseChain & FStructBaseChain::operator= (const FStructBaseChain &) protected delete
References FStructBaseChain().
ReinitializeBaseChainArray()
void FStructBaseChain::ReinitializeBaseChainArray () protected
Referenced by UStruct::UObjectBaseUtility.
Friends And Related Symbol Documentation
UStruct
friend class UStruct friend
Definition at line 385 of file Class.h.
References UStruct.
Referenced by UStruct.
Field Documentation
NumStructBasesInChainMinusOne
int32 FStructBaseChain::NumStructBasesInChainMinusOne private
Definition at line 383 of file Class.h.
Referenced by IsChildOfUsingStructArray().
StructBaseChainArray
FStructBaseChain** FStructBaseChain::StructBaseChainArray private
Definition at line 382 of file Class.h.
Referenced by IsChildOfUsingStructArray().
The documentation for this class was generated from the following file:
Runtime/CoreUObject/Public/UObject/Class.h