Unreal Engine 5.6 C++ API: TBasePlayerControllerIterator< T, LocalOnly > Class Template Reference
TBasePlayerControllerIterator< T, LocalOnly > Class Template Reference
#include "UnrealEngine.h"
Public Member Functions
TBasePlayerControllerIterator (class UWorld *InWorld)
operator bool () const
T * operator* () const
void operator++ ()
T * operator-> () const
Protected Member Functions
void AdvanceCurrent ()
void Next ()
Protected Attributes
T * Current
FConstPlayerControllerIterator Iter
Detailed Description
template<class T, bool LocalOnly>
class TBasePlayerControllerIterator< T, LocalOnly >
Definition at line 102 of file UnrealEngine.h.
Constructor & Destructor Documentation
TBasePlayerControllerIterator()
template<class T, bool LocalOnly> TBasePlayerControllerIterator< T, LocalOnly >::TBasePlayerControllerIterator (class UWorld * InWorld) inline
Definition at line 105 of file UnrealEngine.h.
Member Function Documentation
AdvanceCurrent()
template<class T, bool LocalOnly> void TBasePlayerControllerIterator< T, LocalOnly >::AdvanceCurrent () inline protected
Definition at line 134 of file UnrealEngine.h.
Referenced by TBasePlayerControllerIterator< T, true >::TBasePlayerControllerIterator(), and TBasePlayerControllerIterator< T, true >::Next().
Next()
template<class T, bool LocalOnly> void TBasePlayerControllerIterator< T, LocalOnly >::Next () inline protected
Definition at line 147 of file UnrealEngine.h.
Referenced by TBasePlayerControllerIterator< T, true >::operator++().
operator bool()
template<class T, bool LocalOnly> TBasePlayerControllerIterator< T, LocalOnly >::operator bool () const inline explicit
Definition at line 124 of file UnrealEngine.h.
operator*()
template<class T, bool LocalOnly> T * TBasePlayerControllerIterator< T, LocalOnly >::operator* () const inline
Definition at line 116 of file UnrealEngine.h.
operator++()
template<class T, bool LocalOnly> void TBasePlayerControllerIterator< T, LocalOnly >::operator++ () inline
Definition at line 112 of file UnrealEngine.h.
operator->()
template<class T, bool LocalOnly> T * TBasePlayerControllerIterator< T, LocalOnly >::operator-> () const inline
Definition at line 120 of file UnrealEngine.h.
Field Documentation
Current
template<class T, bool LocalOnly> T* TBasePlayerControllerIterator< T, LocalOnly >::Current protected
Definition at line 132 of file UnrealEngine.h.
Iter
template<class T, bool LocalOnly> FConstPlayerControllerIterator TBasePlayerControllerIterator< T, LocalOnly >::Iter protected
Definition at line 131 of file UnrealEngine.h.
The documentation for this class was generated from the following file:
Runtime/Engine/Public/UnrealEngine.h