Unreal Engine 5.6 C++ API: TBaseUFunctionDelegateInstance< UserClass, RetValType(ParamTypes...), UserPolicy, VarTypes... > Class Template Reference
TBaseUFunctionDelegateInstance< UserClass, RetValType(ParamTypes...), UserPolicy, VarTypes... > Class Template Reference
#include "DelegateInstancesImpl.h"
Public Member Functions
template<typename... InVarTypes>
TBaseUFunctionDelegateInstance (UserClass *InUserObject, const FName &InFunctionName, InVarTypes &&... Vars)
void CreateCopy (TDelegateBase< FNotThreadSafeDelegateMode > &Base) const final
void CreateCopy (TDelegateBase< FNotThreadSafeNotCheckedDelegateMode > &Base) const final
void CreateCopy (TDelegateBase< FThreadSafeDelegateMode > &Base) const final
RetValType Execute (ParamTypes... Params) const final
bool ExecuteIfSafe (ParamTypes... Params) const final
uint64 GetBoundProgramCounterForTimerManager () const final
const void * GetObjectForTimerManager () const final
UObject * GetUObject () const final
bool HasSameObject (FDelegateUserObjectConst InUserObject) const final
bool IsCompactable () const final
bool IsSafeToExecute () const final
Public Member Functions inherited from TCommonDelegateInstanceState< RetValType(ParamTypes...), UserPolicy, VarTypes... >
TCommonDelegateInstanceState (InVarTypes &&... Vars)
FDelegateHandle GetHandle () const final
Data Fields
UFunction * CachedFunction
FName FunctionName
TWeakObjectPtr< UserClass > UserObjectPtr
Private Types
using DelegateBaseType = typename UserPolicy::FDelegateExtras
using Super = TCommonDelegateInstanceState<RetValType(ParamTypes...), UserPolicy, VarTypes...>
Additional Inherited Members
Protected Attributes inherited from TCommonDelegateInstanceState< RetValType(ParamTypes...), UserPolicy, VarTypes... >
FDelegateHandle Handle
TTuple< VarTypes... > Payload
Detailed Description
template<class UserClass, typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes>
class TBaseUFunctionDelegateInstance< UserClass, RetValType(ParamTypes...), UserPolicy, VarTypes... >
Definition at line 61 of file DelegateInstancesImpl.h.
Member Typedef Documentation
DelegateBaseType
template<class UserClass, typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes> using TBaseUFunctionDelegateInstance< UserClass, RetValType(ParamTypes...), UserPolicy, VarTypes... >::DelegateBaseType = typename UserPolicy::FDelegateExtras private
Definition at line 65 of file DelegateInstancesImpl.h.
Super
template<class UserClass, typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes> using TBaseUFunctionDelegateInstance< UserClass, RetValType(ParamTypes...), UserPolicy, VarTypes... >::Super = TCommonDelegateInstanceState<RetValType(ParamTypes...), UserPolicy, VarTypes...> private
Definition at line 64 of file DelegateInstancesImpl.h.
Constructor & Destructor Documentation
TBaseUFunctionDelegateInstance()
template<class UserClass, typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes> template<typename... InVarTypes> TBaseUFunctionDelegateInstance< UserClass, RetValType(ParamTypes...), UserPolicy, VarTypes... >::TBaseUFunctionDelegateInstance (UserClass * InUserObject, const FName & InFunctionName, InVarTypes &&... Vars) inline explicit
Definition at line 71 of file DelegateInstancesImpl.h.
References CachedFunction, check, Forward(), FunctionName, and UserObjectPtr.
Referenced by CreateCopy(), CreateCopy(), and CreateCopy().
Member Function Documentation
CreateCopy() [1/3]
template<class UserClass, typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes> void TBaseUFunctionDelegateInstance< UserClass, RetValType(ParamTypes...), UserPolicy, VarTypes... >::CreateCopy (TDelegateBase< FNotThreadSafeDelegateMode > & Base) const inline final
Definition at line 145 of file DelegateInstancesImpl.h.
References TBaseUFunctionDelegateInstance().
CreateCopy() [2/3]
template<class UserClass, typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes> void TBaseUFunctionDelegateInstance< UserClass, RetValType(ParamTypes...), UserPolicy, VarTypes... >::CreateCopy (TDelegateBase< FNotThreadSafeNotCheckedDelegateMode > & Base) const inline final
Definition at line 150 of file DelegateInstancesImpl.h.
References TBaseUFunctionDelegateInstance().
CreateCopy() [3/3]
template<class UserClass, typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes> void TBaseUFunctionDelegateInstance< UserClass, RetValType(ParamTypes...), UserPolicy, VarTypes... >::CreateCopy (TDelegateBase< FThreadSafeDelegateMode > & Base) const inline final
Definition at line 140 of file DelegateInstancesImpl.h.
References TBaseUFunctionDelegateInstance().
Execute()
template<class UserClass, typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes> RetValType TBaseUFunctionDelegateInstance< UserClass, RetValType(ParamTypes...), UserPolicy, VarTypes... >::Execute (ParamTypes... Params) const inline final
Definition at line 155 of file DelegateInstancesImpl.h.
References CachedFunction, checkSlow, Forward(), IsSafeToExecute(), Params, TCommonDelegateInstanceState< RetValType(ParamTypes...), UserPolicy, VarTypes... >::Payload, and UserObjectPtr.
ExecuteIfSafe()
template<class UserClass, typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes> bool TBaseUFunctionDelegateInstance< UserClass, RetValType(ParamTypes...), UserPolicy, VarTypes... >::ExecuteIfSafe (ParamTypes... Params) const inline final
Definition at line 167 of file DelegateInstancesImpl.h.
References CachedFunction, Forward(), IsInGameThread(), Params, TCommonDelegateInstanceState< RetValType(ParamTypes...), UserPolicy, VarTypes... >::Payload, and UserObjectPtr.
GetBoundProgramCounterForTimerManager()
template<class UserClass, typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes> uint64 TBaseUFunctionDelegateInstance< UserClass, RetValType(ParamTypes...), UserPolicy, VarTypes... >::GetBoundProgramCounterForTimerManager () const inline final
Definition at line 105 of file DelegateInstancesImpl.h.
GetObjectForTimerManager()
template<class UserClass, typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes> const void * TBaseUFunctionDelegateInstance< UserClass, RetValType(ParamTypes...), UserPolicy, VarTypes... >::GetObjectForTimerManager () const inline final
Definition at line 100 of file DelegateInstancesImpl.h.
References UserObjectPtr.
GetUObject()
template<class UserClass, typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes> UObject * TBaseUFunctionDelegateInstance< UserClass, RetValType(ParamTypes...), UserPolicy, VarTypes... >::GetUObject () const inline final
Definition at line 95 of file DelegateInstancesImpl.h.
References UserObjectPtr.
HasSameObject()
template<class UserClass, typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes> bool TBaseUFunctionDelegateInstance< UserClass, RetValType(ParamTypes...), UserPolicy, VarTypes... >::HasSameObject (FDelegateUserObjectConst InUserObject) const inline final
Definition at line 111 of file DelegateInstancesImpl.h.
References UserObjectPtr.
IsCompactable()
template<class UserClass, typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes> bool TBaseUFunctionDelegateInstance< UserClass, RetValType(ParamTypes...), UserPolicy, VarTypes... >::IsCompactable () const inline final
Definition at line 122 of file DelegateInstancesImpl.h.
References UserObjectPtr.
IsSafeToExecute()
template<class UserClass, typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes> bool TBaseUFunctionDelegateInstance< UserClass, RetValType(ParamTypes...), UserPolicy, VarTypes... >::IsSafeToExecute () const inline final
Definition at line 131 of file DelegateInstancesImpl.h.
References UserObjectPtr.
Referenced by Execute().
Field Documentation
CachedFunction
template<class UserClass, typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes> UFunction* TBaseUFunctionDelegateInstance< UserClass, RetValType(ParamTypes...), UserPolicy, VarTypes... >::CachedFunction
Definition at line 186 of file DelegateInstancesImpl.h.
Referenced by TBaseUFunctionDelegateInstance(), Execute(), and ExecuteIfSafe().
FunctionName
template<class UserClass, typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes> FName TBaseUFunctionDelegateInstance< UserClass, RetValType(ParamTypes...), UserPolicy, VarTypes... >::FunctionName
Definition at line 189 of file DelegateInstancesImpl.h.
Referenced by TBaseUFunctionDelegateInstance().
UserObjectPtr
template<class UserClass, typename RetValType, typename... ParamTypes, typename UserPolicy, typename... VarTypes> TWeakObjectPtr<UserClass> TBaseUFunctionDelegateInstance< UserClass, RetValType(ParamTypes...), UserPolicy, VarTypes... >::UserObjectPtr
Definition at line 192 of file DelegateInstancesImpl.h.
Referenced by TBaseUFunctionDelegateInstance(), Execute(), ExecuteIfSafe(), GetObjectForTimerManager(), GetUObject(), HasSameObject(), IsCompactable(), and IsSafeToExecute().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Delegates/DelegateInstancesImpl.h