Unreal Engine 5.6 C++ API: FCanvasItem Class Reference
FCanvasItem Class Reference abstract
#include "CanvasItem.h"
Public Member Functions
FCanvasItem (const FVector2D &InPosition)
Basic render item.
virtual ~FCanvasItem ()
virtual void Draw (FCanvas *InCanvas)=0
virtual void Draw (FCanvas *InCanvas, const FVector2D &InPosition)
Draw this item (this will affect the items position for future draw calls that do no specify a position)
virtual void Draw (FCanvas *InCanvas, float X, float Y)
Draw this item (this will affect the items position for future draw calls that do no specify a position)
virtual void SetColor (const FLinearColor &InColor)
Data Fields
FBatchedElementParameters * BatchedElementParameters
bool bFreezeTime
ESimpleElementBlendMode BlendMode
FVector2D Position
uint32 StereoDepth
Protected Attributes
FLinearColor Color
Detailed Description
Definition at line 24 of file CanvasItem.h.
Constructor & Destructor Documentation
FCanvasItem()
FCanvasItem::FCanvasItem (const FVector2D & InPosition) inline
Basic render item.
Parameters
InPosition Draw position
Definition at line 32 of file CanvasItem.h.
References BatchedElementParameters, bFreezeTime, BlendMode, Color, Position, SE_BLEND_Opaque, and StereoDepth.
Referenced by FCanvasBorderItem::FCanvasBorderItem(), FCanvasBoxItem::FCanvasBoxItem(), FCanvasLineItem::FCanvasLineItem(), FCanvasLineItem::FCanvasLineItem(), FCanvasLineItem::FCanvasLineItem(), FCanvasNGonItem::FCanvasNGonItem(), FCanvasTriangleItem::FCanvasTriangleItem(), FCanvasTriangleItem::FCanvasTriangleItem(), FCanvasTriangleItem::FCanvasTriangleItem(), and FCanvasTriangleItem::FCanvasTriangleItem().
~FCanvasItem()
virtual FCanvasItem::~FCanvasItem () inline virtual
Definition at line 40 of file CanvasItem.h.
Member Function Documentation
Draw() [1/3]
virtual void FCanvasItem::Draw (FCanvas * InCanvas) pure virtual
Implemented in FCanvasBorderItem, FCanvasBoxItem, FCanvasLineItem, FCanvasNGonItem, FCanvasTextItemBase, FCanvasTileItem, and FCanvasTriangleItem.
Referenced by FCanvasBoxItem::Draw(), Draw(), Draw(), FCanvasTileItem::Draw(), and FCanvasTriangleItem::Draw().
Draw() [2/3]
virtual void FCanvasItem::Draw (FCanvas * InCanvas, const FVector2D & InPosition) inline virtual
Draw this item (this will affect the items position for future draw calls that do no specify a position)
Parameters
InCanvas Canvas on which to draw
InPosition Draw position - this will not preserve the items position
Reimplemented in FCanvasBorderItem, FCanvasBoxItem, FCanvasLineItem, FCanvasTextItemBase, FCanvasTileItem, and FCanvasTriangleItem.
Definition at line 52 of file CanvasItem.h.
References Draw(), and Position.
Draw() [3/3]
virtual void FCanvasItem::Draw (FCanvas * InCanvas, float X, float Y) inline virtual
Draw this item (this will affect the items position for future draw calls that do no specify a position)
Parameters
InCanvas Canvas on which to draw
X X Draw position
Y Y Draw position
Reimplemented in FCanvasBorderItem, FCanvasBoxItem, FCanvasLineItem, FCanvasTextItemBase, FCanvasTileItem, and FCanvasTriangleItem.
Definition at line 65 of file CanvasItem.h.
References Draw(), Position, X, and Y.
SetColor()
virtual void FCanvasItem::SetColor (const FLinearColor & InColor) inline virtual
Reimplemented in FCanvasBorderItem, FCanvasNGonItem, FCanvasTextItemBase, and FCanvasTriangleItem.
Definition at line 73 of file CanvasItem.h.
References Color.
Referenced by FCanvasBorderItem::SetColor(), and FCanvasTextItemBase::SetColor().
Field Documentation
BatchedElementParameters
FBatchedElementParameters* FCanvasItem::BatchedElementParameters
Definition at line 90 of file CanvasItem.h.
Referenced by FCanvasItem().
bFreezeTime
bool FCanvasItem::bFreezeTime
Definition at line 87 of file CanvasItem.h.
Referenced by FCanvasItem().
BlendMode
ESimpleElementBlendMode FCanvasItem::BlendMode
Definition at line 85 of file CanvasItem.h.
Referenced by FCanvasItem(), FCanvasShapedTextItem::FCanvasShapedTextItem(), FCanvasSimpleTextItem::FCanvasSimpleTextItem(), and FCanvasSimpleTextItem::FCanvasSimpleTextItem().
Color
FLinearColor FCanvasItem::Color protected
Definition at line 93 of file CanvasItem.h.
Referenced by FCanvasItem(), FCanvasNGonItem::FCanvasNGonItem(), SetColor(), and FCanvasNGonItem::SetupPosition().
Position
FVector2D FCanvasItem::Position
Definition at line 79 of file CanvasItem.h.
Referenced by FCanvasItem(), FCanvasTriangleItem::FCanvasTriangleItem(), Draw(), and Draw().
StereoDepth
uint32 FCanvasItem::StereoDepth
Definition at line 82 of file CanvasItem.h.
Referenced by FCanvasItem().
The documentation for this class was generated from the following file:
Runtime/Engine/Public/CanvasItem.h