Unreal Engine 5.6 C++ API: HarmonixMetasound::Analysis::FSpmcAnalysisResultQueue< T >::FReadCursor Class Reference
HarmonixMetasound::Analysis::FSpmcAnalysisResultQueue< T >::FReadCursor Class Reference
#include "SpmcAnalysisResultQueue.h"
Public Member Functions
FReadCursor ()
FReadCursor (FSpmcAnalysisResultQueue &InQueue)
FScopedItemConsumeRef ConsumeNext ()
bool DataAvailable () const
int32 NumDataAvailable () const
FScopedItemPeekRef PeekAhead (int32 NumberAhead)
void PeekAhead (int32 NumberAhead, FScopedItemPeekRef &Target)
FScopedItemPeekRef PeekNext ()
Data Fields
int32 NextExpectedSerialNumber { -1 }
int32 NextReadIndex { 0 }
const FSpmcAnalysisResultQueue * Queue
Detailed Description
template<typename T>
class HarmonixMetasound::Analysis::FSpmcAnalysisResultQueue< T >::FReadCursor
Definition at line 30 of file SpmcAnalysisResultQueue.h.
Constructor & Destructor Documentation
FReadCursor() [1/2]
template<typename T> HarmonixMetasound::Analysis::FSpmcAnalysisResultQueue< T >::FReadCursor::FReadCursor () inline
Definition at line 33 of file SpmcAnalysisResultQueue.h.
References NextReadIndex, and Queue.
FReadCursor() [2/2]
template<typename T> HarmonixMetasound::Analysis::FSpmcAnalysisResultQueue< T >::FReadCursor::FReadCursor (FSpmcAnalysisResultQueue & InQueue) inline
Definition at line 40 of file SpmcAnalysisResultQueue.h.
References HarmonixMetasound::Analysis::FSpmcAnalysisResultQueue< T >::FSpmcAnalysisResultQueue(), HarmonixMetasound::Analysis::FSpmcAnalysisResultQueue< T >::GetNextWriteIndex(), NextReadIndex, and Queue.
Member Function Documentation
ConsumeNext()
template<typename T> FScopedItemConsumeRef HarmonixMetasound::Analysis::FSpmcAnalysisResultQueue< T >::FReadCursor::ConsumeNext () inline
Definition at line 47 of file SpmcAnalysisResultQueue.h.
References DataAvailable(), NextReadIndex, and Queue.
DataAvailable()
template<typename T> bool HarmonixMetasound::Analysis::FSpmcAnalysisResultQueue< T >::FReadCursor::DataAvailable () const inline
Definition at line 91 of file SpmcAnalysisResultQueue.h.
References NextReadIndex, and Queue.
Referenced by ConsumeNext(), and PeekNext().
NumDataAvailable()
template<typename T> int32 HarmonixMetasound::Analysis::FSpmcAnalysisResultQueue< T >::FReadCursor::NumDataAvailable () const inline
Definition at line 96 of file SpmcAnalysisResultQueue.h.
References NextReadIndex, and Queue.
Referenced by PeekAhead(), and PeekAhead().
PeekAhead() [1/2]
template<typename T> FScopedItemPeekRef HarmonixMetasound::Analysis::FSpmcAnalysisResultQueue< T >::FReadCursor::PeekAhead (int32 NumberAhead) inline
Definition at line 66 of file SpmcAnalysisResultQueue.h.
References NextReadIndex, NumDataAvailable(), and Queue.
PeekAhead() [2/2]
template<typename T> void HarmonixMetasound::Analysis::FSpmcAnalysisResultQueue< T >::FReadCursor::PeekAhead (int32 NumberAhead, FScopedItemPeekRef & Target) inline
Definition at line 78 of file SpmcAnalysisResultQueue.h.
References NextReadIndex, NumDataAvailable(), Queue, and Target.
PeekNext()
template<typename T> FScopedItemPeekRef HarmonixMetasound::Analysis::FSpmcAnalysisResultQueue< T >::FReadCursor::PeekNext () inline
Definition at line 56 of file SpmcAnalysisResultQueue.h.
References DataAvailable(), NextReadIndex, and Queue.
Field Documentation
NextExpectedSerialNumber
template<typename T> int32 HarmonixMetasound::Analysis::FSpmcAnalysisResultQueue< T >::FReadCursor::NextExpectedSerialNumber { -1 }
Definition at line 113 of file SpmcAnalysisResultQueue.h.
Referenced by HarmonixMetasound::Analysis::FSpmcAnalysisResultQueue< T >::FScopedItemConsumeRef::FScopedItemConsumeRef(), HarmonixMetasound::Analysis::FSpmcAnalysisResultQueue< T >::FScopedItemPeekRef::FScopedItemPeekRef(), and HarmonixMetasound::Analysis::FSpmcAnalysisResultQueue< T >::FScopedItemPeekRef::ConnectTo().
NextReadIndex
template<typename T> int32 HarmonixMetasound::Analysis::FSpmcAnalysisResultQueue< T >::FReadCursor::NextReadIndex { 0 }
Definition at line 112 of file SpmcAnalysisResultQueue.h.
Referenced by FReadCursor(), FReadCursor(), ConsumeNext(), DataAvailable(), NumDataAvailable(), PeekAhead(), PeekAhead(), and PeekNext().
Queue
template<typename T> const FSpmcAnalysisResultQueue* HarmonixMetasound::Analysis::FSpmcAnalysisResultQueue< T >::FReadCursor::Queue
Definition at line 111 of file SpmcAnalysisResultQueue.h.
Referenced by FReadCursor(), FReadCursor(), HarmonixMetasound::Analysis::FSpmcAnalysisResultQueue< T >::FScopedItemConsumeRef::FScopedItemConsumeRef(), ConsumeNext(), DataAvailable(), NumDataAvailable(), PeekAhead(), PeekAhead(), and PeekNext().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/Harmonix/Source/HarmonixMetasound/Public/HarmonixMetasound/Analysis/SpmcAnalysisResultQueue.h