Unreal Engine 5.6 C++ API: FLoadTimeTracker Class Reference
FLoadTimeTracker Class Reference
High level load time tracker utility (such as initial engine startup or game specific timings)
#include "LoadTimeTracker.h"
Data Structures
struct FAccumulatorTracker
An accumulated stat group, with time and count for each instance.
struct FTimeAndCount
Track a time and count for a stat.
Public Member Functions
void DumpHighLevelLoadTimes () const
Prints out total time and individual times.
void DumpRawLoadTimes () const
Prints out raw load times for individual timers.
const TMap< FName, TArray< double > > & GetData () const
double & GetScopeTimeAccumulator (const FName &ScopeLabel, const FName &ScopeInstance)
Gets/adds a scoped time for a given label and instance.
bool IsAccumulating ()
void ReportScopeTime (double ScopeTime, const FName ScopeLabel)
Adds a scoped time for a given label.
void ResetHighLevelLoadTimes ()
void ResetRawLoadTimes ()
void StartAccumulatedLoadTimes ()
void StopAccumulatedLoadTimes ()
Static Public Member Functions
static void DumpHighLevelLoadTimesStatic ()
static void DumpRawLoadTimesStatic ()
static FLoadTimeTracker & Get ()
static void ResetRawLoadTimesStatic ()
static void StartAccumulatedLoadTimesStatic ()
static void StopAccumulatedLoadTimesStatic ()
Private Member Functions
FLoadTimeTracker ()
Private Attributes
TMap< FName, FAccumulatorTracker > AccumulatedTimeInfo
Map to track accumulated timings.
bool bAccumulating
We dont normally track accumulated load time info, only when this flag is true.
TMap< FName, TArray< double > > TimeInfo
Detailed Description
High level load time tracker utility (such as initial engine startup or game specific timings)
Definition at line 34 of file LoadTimeTracker.h.
Constructor & Destructor Documentation
FLoadTimeTracker()
FLoadTimeTracker::FLoadTimeTracker () private
Referenced by Get().
Member Function Documentation
DumpHighLevelLoadTimes()
void FLoadTimeTracker::DumpHighLevelLoadTimes () const
Prints out total time and individual times.
Referenced by DumpHighLevelLoadTimesStatic().
DumpHighLevelLoadTimesStatic()
void FLoadTimeTracker::DumpHighLevelLoadTimesStatic () inline static
Definition at line 48 of file LoadTimeTracker.h.
References DumpHighLevelLoadTimes(), and Get().
DumpRawLoadTimes()
void FLoadTimeTracker::DumpRawLoadTimes () const
Prints out raw load times for individual timers.
Referenced by DumpRawLoadTimesStatic().
DumpRawLoadTimesStatic()
void FLoadTimeTracker::DumpRawLoadTimesStatic () inline static
Definition at line 63 of file LoadTimeTracker.h.
References DumpRawLoadTimes(), and Get().
Get()
FLoadTimeTracker & FLoadTimeTracker::Get () static
References FLoadTimeTracker().
Referenced by DumpHighLevelLoadTimesStatic(), DumpRawLoadTimesStatic(), ResetRawLoadTimesStatic(), StartAccumulatedLoadTimesStatic(), and StopAccumulatedLoadTimesStatic().
GetData()
const TMap< FName, TArray< double > > & FLoadTimeTracker::GetData () const inline
Definition at line 53 of file LoadTimeTracker.h.
References TimeInfo.
GetScopeTimeAccumulator()
double & FLoadTimeTracker::GetScopeTimeAccumulator (const FName & ScopeLabel, const FName & ScopeInstance)
Gets/adds a scoped time for a given label and instance.
Records each instance individually
IsAccumulating()
bool FLoadTimeTracker::IsAccumulating () inline
Definition at line 89 of file LoadTimeTracker.h.
References bAccumulating.
ReportScopeTime()
void FLoadTimeTracker::ReportScopeTime (double ScopeTime, const FName ScopeLabel)
Adds a scoped time for a given label.
Records each instance individually
ResetHighLevelLoadTimes()
void FLoadTimeTracker::ResetHighLevelLoadTimes ()
ResetRawLoadTimes()
void FLoadTimeTracker::ResetRawLoadTimes ()
Referenced by ResetRawLoadTimesStatic().
ResetRawLoadTimesStatic()
void FLoadTimeTracker::ResetRawLoadTimesStatic () inline static
Definition at line 70 of file LoadTimeTracker.h.
References Get(), and ResetRawLoadTimes().
StartAccumulatedLoadTimes()
void FLoadTimeTracker::StartAccumulatedLoadTimes ()
Referenced by StartAccumulatedLoadTimesStatic().
StartAccumulatedLoadTimesStatic()
void FLoadTimeTracker::StartAccumulatedLoadTimesStatic () inline static
Definition at line 77 of file LoadTimeTracker.h.
References Get(), and StartAccumulatedLoadTimes().
StopAccumulatedLoadTimes()
void FLoadTimeTracker::StopAccumulatedLoadTimes ()
Referenced by StopAccumulatedLoadTimesStatic().
StopAccumulatedLoadTimesStatic()
void FLoadTimeTracker::StopAccumulatedLoadTimesStatic () inline static
Definition at line 84 of file LoadTimeTracker.h.
References Get(), and StopAccumulatedLoadTimes().
Field Documentation
AccumulatedTimeInfo
TMap<FName, FAccumulatorTracker> FLoadTimeTracker::AccumulatedTimeInfo private
Map to track accumulated timings.
Definition at line 256 of file LoadTimeTracker.h.
bAccumulating
bool FLoadTimeTracker::bAccumulating private
We dont normally track accumulated load time info, only when this flag is true.
Definition at line 259 of file LoadTimeTracker.h.
Referenced by IsAccumulating().
TimeInfo
TMap<FName, TArray<double> > FLoadTimeTracker::TimeInfo private
Definition at line 240 of file LoadTimeTracker.h.
Referenced by GetData().
The documentation for this class was generated from the following file:
Runtime/Core/Public/ProfilingDebugging/LoadTimeTracker.h