Unreal Engine 5.6 C++ API: FThreadSafeRefCountedObject Class Reference
FThreadSafeRefCountedObject Class Reference
Like FRefCountedObject, but the reference count is thread-safe.
#include "RefCounting.h"
Public Member Functions
FThreadSafeRefCountedObject ()=default
FThreadSafeRefCountedObject (const FThreadSafeRefCountedObject &Rhs)=delete
virtual ~FThreadSafeRefCountedObject ()
FReturnedRefCountValue AddRef () const
uint32 GetRefCount () const
FThreadSafeRefCountedObject & operator= (const FThreadSafeRefCountedObject &Rhs)=delete
uint32 Release () const
Private Types
using Super = UE::Private::TTransactionalAtomicRefCount<uint32>
Static Private Member Functions
static void DeleteThis (const Super *This)
Additional Inherited Members
Private Member Functions inherited from UE::Private::TTransactionalAtomicRefCount< uint32 >
uint32 AddRef () const
uint32 GetRefCount () const
uint32 Release () const
Detailed Description
Like FRefCountedObject, but the reference count is thread-safe.
Definition at line 282 of file RefCounting.h.
Member Typedef Documentation
Super
using FThreadSafeRefCountedObject::Super = UE::Private::TTransactionalAtomicRefCount<uint32> private
Definition at line 311 of file RefCounting.h.
Constructor & Destructor Documentation
FThreadSafeRefCountedObject() [1/2]
FThreadSafeRefCountedObject::FThreadSafeRefCountedObject () default
Referenced by FThreadSafeRefCountedObject(), DeleteThis(), and operator=().
FThreadSafeRefCountedObject() [2/2]
FThreadSafeRefCountedObject::FThreadSafeRefCountedObject (const FThreadSafeRefCountedObject & Rhs) delete
References FThreadSafeRefCountedObject().
~FThreadSafeRefCountedObject()
virtual FThreadSafeRefCountedObject::~FThreadSafeRefCountedObject () inline virtual
Definition at line 290 of file RefCounting.h.
References check, and UE::Private::TTransactionalAtomicRefCount< uint32 >::GetRefCount().
Member Function Documentation
AddRef()
FReturnedRefCountValue FThreadSafeRefCountedObject::AddRef () const inline
Definition at line 295 of file RefCounting.h.
References UE::Private::TTransactionalAtomicRefCount< uint32 >::AddRef().
DeleteThis()
void FThreadSafeRefCountedObject::DeleteThis (const Super * This) inline static private
Definition at line 313 of file RefCounting.h.
References FThreadSafeRefCountedObject().
GetRefCount()
uint32 FThreadSafeRefCountedObject::GetRefCount () const inline
Definition at line 305 of file RefCounting.h.
References UE::Private::TTransactionalAtomicRefCount< uint32 >::GetRefCount().
operator=()
FThreadSafeRefCountedObject & FThreadSafeRefCountedObject::operator= (const FThreadSafeRefCountedObject & Rhs) delete
References FThreadSafeRefCountedObject().
Release()
uint32 FThreadSafeRefCountedObject::Release () const inline
Definition at line 300 of file RefCounting.h.
References UE::Private::TTransactionalAtomicRefCount< uint32 >::Release().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Templates/RefCounting.h