Unreal Engine 5.6 C++ API: SDockTab Class Reference
SDockTab Class Reference
A tab widget that also holds on to some content that should be shown when this tab is selected.
#include "SDockTab.h"
Public Member Functions
SDockTab ()
Protected constructor; Widgets may only be constructed via a FArguments (i.e.: SNew(SDockTab))
void ActivateInParent (ETabActivationCause InActivationCause)
Make this tab active in its tabwell.
bool CanCloseTab () const
DECLARE_DELEGATE (FOnPersistVisualState)
Invoked w`en this tab should save some information about its content.
DECLARE_DELEGATE_OneParam (FExtendContextMenu, FMenuBuilder &)
Invoked to add entries to the tab context menu.
DECLARE_DELEGATE_OneParam (FOnTabClosedCallback, TSharedRef< SDockTab >)
Invoked when a tab is closing.
DECLARE_DELEGATE_OneParam (FOnTabRenamed, TSharedRef< SDockTab >)
Invoked when a tab is renamed.
DECLARE_DELEGATE_RetVal (bool, FCanCloseTab)
Delegate called before a tab is closed.
DECLARE_DELEGATE_TwoParams (FOnTabActivatedCallback, TSharedRef< SDockTab >, ETabActivationCause)
Invoked when a tab is activated.
void DrawAttention ()
Draws attention to the tab.
void ExtendContextMenu (FMenuBuilder &MenuBuilder)
Add any entries specific to this tab to the tab context menu.
void FlashTab ()
Flash the tab, used for drawing attention to it.
TSharedRef< SWidget > GetContent ()
const FSlateBrush * GetContentAreaBrush () const
What should the content area look like for this type of tab?
FMargin GetContentPadding () const
Padding around the content when it is presented by the SDockingTabStack.
TSharedPtr< class SDockingArea > GetDockArea () const
Gets the dock area that this resides in.
virtual FSlateColor GetForegroundColor () const
double GetLastActivationTime ()
Returns the time this tab was last activated.
const FTabId GetLayoutIdentifier () const
Gets this tab's layout identifier.
TSharedRef< SWidget > GetLeftContent ()
float GetOverlapWidth () const
The width that this tab will overlap with side-by-side tabs.
TSharedPtr< SDockingTabWell > GetParent () const
Gets the tab's tab well parent, or nothing, if it has none.
TSharedPtr< SDockingTabStack > GetParentDockTabStack () const
Gets the dock tab stack this dockable tab resides within, if any.
TSharedPtr< SWindow > GetParentWindow () const
Get the window in which this tab's tabmanager has placed it.
TSharedRef< SWidget > GetRightContent ()
const FSlateBrush * GetTabIcon () const
Gets the tab icon.
FText GetTabLabel () const
The label on the tab.
FText GetTabLabelSuffix () const
Get Label Suffix.
TSharedPtr< FTabManager > GetTabManagerPtr () const
Get the tab manager currently managing this tab.
ETabRole GetTabRole () const
Is this an MajorTab?
const FSlateBrush * GetTabWellBrush () const
Depending on the tabs we put into the tab well, we want a different background brush.
TSharedRef< SWidget > GetTitleBarRightContent ()
ETabRole GetVisualTabRole () const
Similar to GetTabRole() but returns the correct role for UI style and user input purposes.
bool HasSiblingTab (const FTabId &SiblingTabId, const bool TreatIndexNoneAsWildcard=true) const
Check to see whether this tab has a sibling tab with the given tab ID.
bool IsActive () const
bool IsForeground () const
virtual FReply OnDragDetected (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent) override
Called when Slate detects that a widget started to be dragged.
virtual void OnDragEnter (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent) override
Called during drag and drop when the drag enters a widget.
virtual void OnDragLeave (const FDragDropEvent &DragDropEvent) override
Called during drag and drop when the drag leaves a widget.
virtual FReply OnDrop (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent) override
Called when the user is dropping something onto a widget; terminates drag and drop.
virtual FReply OnMouseButtonDoubleClick (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent) override
Called when a mouse button is double clicked.
virtual FReply OnMouseButtonDown (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent) override
The system calls this method to notify the widget that a mouse button was pressed within it.
virtual FReply OnMouseButtonUp (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent) override
The system calls this method to notify the widget that a mouse button was release within it.
virtual FReply OnTouchEnded (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent) override
Called when a touchpad touch is ended (finger lifted)
virtual FReply OnTouchStarted (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent) override
Called when a touchpad touch is started (finger down)
void PersistVisualState ()
A chance for the tab's content to save any internal layout info.
void PlaySpawnAnim ()
Play an animation showing this tab as opening.
void ProvideDefaultLabel (const FText &InDefaultLabel)
Provide a default tab label in case the spawner did not set one.
void RemoveTabFromParent ()
Pulls this tab out of it's parent tab stack and destroys it Note: This does not check if its safe to remove the tab.
bool RequestCloseTab ()
Requests that the tab be closed.
void SetCanCloseTab (const FCanCloseTab &InOnTabClosing)
Set the handler to be invoked when the user requests that this tab be closed.
virtual void SetContent (TSharedRef< SWidget > InContent) override
Sets the content for this border.
void SetDraggedOverDockArea (const TSharedPtr< SDockingArea > &Area)
Used by the drag/drop operation to signal to this tab what it is dragging over.
void SetLabel (const TAttribute< FText > &InTabLabel)
The label that appears on the tab.
void SetLeftContent (TSharedRef< SWidget > InContent)
Content that appears in the TabWell to the left of the tabs.
void SetOnExtendContextMenu (const FExtendContextMenu &Handler)
Set the handler for extending the tab context menu.
void SetOnPersistVisualState (const FOnPersistVisualState &Handler)
Set the custom code to execute for saving visual state in this tab.
void SetOnTabActivated (const FOnTabActivatedCallback &InDelegate)
Set the handler that will be invoked when the tab is activated.
void SetOnTabClosed (const FOnTabClosedCallback &InDelegate)
Set the handler that will be invoked when the tab is closed.
void SetOnTabDraggedOverDockArea (const FSimpleDelegate InDelegate)
Set the handler that will be invoked when the tab is dragged over dock area.
void SetOnTabDrawerClosed (const FSimpleDelegate InDelegate)
Set the handler that will be invoked when the tab is closed from a drawer.
void SetOnTabDrawerOpened (const FSimpleDelegate InDelegate)
Set the handler that will be invoked when the tab is opened from a drawer.
void SetOnTabRelocated (const FSimpleDelegate InDelegate)
Set the handler that will be invoked when the tab is relocated to a new tab well.
void SetOnTabRenamed (const FOnTabRenamed &InDelegate)
Set the handler that will be invoked when the tab is renamed.
void SetParent (TSharedPtr< SDockingTabWell > Parent=TSharedPtr< SDockingTabWell >())
Sets the tab's tab well parent, or resets it if nothing is passed in.
void SetParentDockTabStackTabWellHidden (bool bIsTabWellHidden)
void SetRightContent (TSharedRef< SWidget > InContent)
Content that appears in the TabWell to the right of the tabs.
void SetShouldAutosize (const bool bNewShouldAutosize)
Set whether this tab should be sized based on its content.
TabWellContentLeft ContentPadding Label Tab icons are now being managed by tab spawners and toolkits In the rare case you need to set an icon use SetTabIcon () instead") FArguments & Icon(const FSlateBrush* InIcon)
void SetTabIcon (const TAttribute< const FSlateBrush * > InTabIcon)
Sets the tab icon.
void SetTabLabelOverflowPolicy (ETextOverflowPolicy InOverflowPolicy) const
Set the Label overflow policy.
void SetTabLabelSuffix (const TAttribute< FText > &InTabLabelSuffix)
Set Label Suffix.
void SetTabManager (const TSharedPtr< FTabManager > &InTabManager)
Set the tab manager that is controlling this tab.
void SetTabToolTipWidget (TSharedPtr< SToolTip > InTabToolTipWidget)
The tooltip text that appears on the tab.
void SetTitleBarRightContent (TSharedRef< SWidget > InContent)
Content that appears on the right side of the title bar in the window this stack is in.
bool ShouldAutosize () const
Should this tab be sized based on its content.
OnTabActivated OnTabDraggedOverDockArea OnCanCloseTab SLATE_ARGUMENT (bool, CanEverClose) SLATE_EVENT(FOnPersistVisualState
Whether this tab can ever be closed.
OnTabActivated OnTabDraggedOverDockArea SLATE_ARGUMENT (bool, ShouldAutosize) SLATE_EVENT(FCanCloseTab
When the close button is pressed, checks whether the tab can be closed in that moment.
TabWellContentLeft ContentPadding SLATE_ARGUMENT (ETabRole, TabRole) SLATE_ATTRIBUTE(FText
OnTabActivated OnTabDraggedOverDockArea OnCanCloseTab OnPersistVisualState OnTabDrawerClosed ForegroundColor SLATE_ATTRIBUTE (FLinearColor, IconColor) SLATE_ARGUMENT(ETextOverflowPolicy
OnTabActivated OnTabDraggedOverDockArea OnCanCloseTab OnPersistVisualState OnTabDrawerClosed SLATE_ATTRIBUTE (FLinearColor, TabColorScale) SLATE_ATTRIBUTE(FSlateColor
TabWellContentLeft ContentPadding Label SLATE_ATTRIBUTE (FText, LabelSuffix) UE_DEPRECATED(5.0
SLATE_BEGIN_ARGS (SDockTab)
SLATE_DEFAULT_SLOT (FArguments, Content) SLATE_NAMED_SLOT(FArguments
OnTabActivated OnTabDraggedOverDockArea OnCanCloseTab OnPersistVisualState OnTabDrawerClosed ForegroundColor LabelOverflowPolicy SLATE_END_ARGS () 1 void Construct(const FArguments &InArgs)
Construct the widget from the declaration.
OnTabActivated OnTabDraggedOverDockArea OnCanCloseTab OnPersistVisualState SLATE_EVENT (FExtendContextMenu, OnExtendContextMenu) SLATE_EVENT(FSimpleDelegate
Invoked when a tab is closed from a drawer.
SLATE_EVENT (FOnTabClosedCallback, OnTabClosed) SLATE_EVENT(FOnTabActivatedCallback
OnTabActivated SLATE_EVENT (FSimpleDelegate, OnTabRelocated) SLATE_EVENT(FSimpleDelegate
TabWellContentLeft SLATE_NAMED_SLOT (FArguments, TabWellContentRight) SLATE_ATTRIBUTE(FMargin
UE_DEPRECATED (5.0, "The tab manager is not guaranteed to exist, which will cause GetTabManager() to crash. Use GetTabManagerPtr() instead.") 1 TSharedRef< FTabManager > GetTabManager() const
Get the tab manager currently managing this tab.
void UpdateActivationTime ()
Updates the 'last activated' time to the current time.
Public Member Functions inherited from SBorder
virtual int32 OnPaint (const FPaintArgs &Args, const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, FSlateWindowElementList &OutDrawElements, int32 LayerId, const FWidgetStyle &InWidgetStyle, bool bParentEnabled) const override
The widget should respond by populating the OutDrawElements array with FDrawElements that represent it and any of its children.
Public Member Functions inherited from SCompoundWidget
virtual FChildren * GetChildren () override
Returns the useful children (if any) of this widget.
virtual void OnArrangeChildren (const FGeometry &AllottedGeometry, FArrangedChildren &ArrangedChildren) const override
Compute the Geometry of all the children and add populate the ArrangedChildren list with their values.
virtual void SetVisibility (TAttribute< EVisibility > InVisibility) override final
Public Member Functions inherited from SWidget
template<typename MetaDataType>
void AddMetadata (const TSharedRef< MetaDataType > &AddMe)
Add metadata to this widget.
virtual const FSlateInvalidationRoot * Advanced_AsInvalidationRoot () const
FORCEINLINE TSharedPtr< SWidget > Advanced_GetPaintParentWidget () const
virtual bool Advanced_IsInvalidationRoot () const
virtual bool Advanced_IsWindow () const
Is this widget derivative of SWindow.
void ArrangeChildren (const FGeometry &AllottedGeometry, FArrangedChildren &ArrangedChildren, bool bUpdateAttributes=false) const
Non-virtual entry point for arrange children.
void AssignParentWidget (TSharedPtr< SWidget > InParent)
FORCEINLINE void CacheVolatility ()
Recalculates volatility of the widget and caches the result.
FSlateRect CalculateCullingAndClippingRules (const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, bool &bClipToBounds, bool &bAlwaysClip, bool &bIntersectClipBounds) const
Calculates what if any clipping state changes need to happen when drawing this widget.
bool ConditionallyDetatchParentWidget (SWidget *InExpectedParent)
void EnableToolTipForceField (const bool bEnableForceField)
Sets whether this widget is a "tool tip force field".
FORCEINLINE void ForceVolatile (bool bForce)
Should this widget always appear as volatile for any layout caching host widget.
virtual FChildren * GetAllChildren ()
Returns the children (if any) of this widget that are used by the invalidation system.
template<typename MetaDataType>
TArray< TSharedRef< MetaDataType > > GetAllMetaData () const
Get all metadata of the type provided.
const FGeometry & GetCachedGeometry () const
bool GetCanTick () const
FORCEINLINE EWidgetClipping GetClipping () const
FName GetCreatedInLocation () const
FORCEINLINE FMargin GetCullingBoundsExtension () const
const TOptional< FSlateClippingState > & GetCurrentClippingState () const
Returns the clipping state to clip this widget against its parent.
UE::Slate::FDeprecateVector2DResult GetDesiredSize () const
virtual FSlateColor GetDisabledForegroundColor () const
EFlowDirectionPreference GetFlowDirectionPreference () const
Gets the desired flow direction for the layout.
template<typename MetaDataType>
TSharedPtr< MetaDataType > GetMetaData () const
Get the metadata of the type provided.
const FGeometry & GetPaintSpaceGeometry () const
Gets the last geometry used to Tick the widget.
FORCEINLINE TSharedPtr< SWidget > GetParentWidget () const
const FSlateWidgetPersistentState & GetPersistentState () const
FORCEINLINE EWidgetPixelSnapping GetPixelSnapping () const
const FWidgetProxyHandle GetProxyHandle () const
virtual FString GetReadableLocation () const
virtual float GetRelativeLayoutScale (const int32 ChildIndex, float LayoutScaleMultiplier) const
What is the Child's scale relative to this widget.
FORCEINLINE float GetRenderOpacity () const
FORCEINLINE const TOptional< FSlateRenderTransform > & GetRenderTransform () const
FORCEINLINE UE::Slate::FDeprecateVector2DResult GetRenderTransformPivot () const
FORCEINLINE UE::Slate::FDeprecateVector2DResult GetRenderTransformPivotWithRespectToFlowDirection () const
FORCEINLINE TOptional< FSlateRenderTransform > GetRenderTransformWithRespectToFlowDirection () const
FORCEINLINE TStatId GetStatID (bool bForDeferredUse=false) const
virtual FName GetTag () const
const FGeometry & GetTickSpaceGeometry () const
Gets the last geometry used to Tick the widget.
virtual TSharedPtr< IToolTip > GetToolTip ()
FName GetType () const
FString GetTypeAsString () const
FORCEINLINE EVisibility GetVisibility () const
virtual EWindowZone::Type GetWindowZoneOverride () const
Called when the mouse is moved over the widget's window, to determine if we should report whether OS-specific features should be active at this location (such as a title bar grip, system menu, etc.) Usually you should not need to override this function.
bool HasActiveTimers () const
Does this widget have any active timers?
bool HasAnyUpdateFlags (EWidgetUpdateFlags FlagsToCheck) const
TOptional< EFocusCause > HasAnyUserFocus () const
Gets whether or not any users have this widget focused, and if so the type of focus (first one found).
bool HasAnyUserFocusOrFocusedDescendants () const
bool HasFocusedDescendants () const
virtual bool HasKeyboardFocus () const
Checks to see if this widget currently has the keyboard focus.
bool HasMouseCapture () const
Checks to see if this widget is the current mouse captor.
bool HasMouseCaptureByUser (int32 UserIndex, TOptional< int32 > PointerIndex=TOptional< int32 >()) const
Checks to see if this widget has mouse capture from the provided user.
bool HasRegisteredSlateAttribute () const
bool HasToolTipForceField () const
TOptional< EFocusCause > HasUserFocus (int32 UserIndex) const
Gets whether or not the specified users has this widget focused, and if so the type of focus.
bool HasUserFocusedDescendants (int32 UserIndex) const
Gets whether or not the specified users has this widget or any descendant focused.
void Invalidate (EInvalidateWidgetReason InvalidateReason)
Invalidates the widget from the view of a layout caching widget that may own this widget.
bool IsAttributesUpdatesEnabled () const
bool IsDirectlyHovered () const
FORCEINLINE bool IsEnabled () const
bool IsHovered () const
virtual bool IsInteractable () const
FORCEINLINE bool IsParentValid () const
FORCEINLINE bool IsVolatile () const
Whether or not a widget is volatile and will update every frame without being invalidated.
FORCEINLINE bool IsVolatileIndirectly () const
This widget is volatile because its parent or some ancestor is volatile.
void MarkPrepassAsDirty ()
In fast path, if the widget is mark, do a full Prepass on its next update to calculate it's desired size.
bool NeedsPrepass () const
virtual FReply OnAnalogValueChanged (const FGeometry &MyGeometry, const FAnalogInputEvent &InAnalogInputEvent)
Called when an analog value changes on a button that supports analog.
virtual FCursorReply OnCursorQuery (const FGeometry &MyGeometry, const FPointerEvent &CursorEvent) const
The system asks each widget under the mouse to provide a cursor.
virtual FReply OnDragOver (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called during drag and drop when the the mouse is being dragged over a widget.
virtual void OnFinishedKeyInput ()
All the key (keyboard, gamepay, joystick, etc.) input from this frame has been routed.
virtual void OnFinishedPointerInput ()
All the pointer (mouse, touch, stylus, etc.) events from this frame have been routed.
virtual void OnFocusChanging (const FWeakWidgetPath &PreviousFocusPath, const FWidgetPath &NewWidgetPath, const FFocusEvent &InFocusEvent)
Called whenever a focus path is changing on all the widgets within the old and new focus paths.
virtual void OnFocusLost (const FFocusEvent &InFocusEvent)
Called when this widget loses focus.
virtual FReply OnFocusReceived (const FGeometry &MyGeometry, const FFocusEvent &InFocusEvent)
Called when focus is given to this widget.
virtual FReply OnKeyChar (const FGeometry &MyGeometry, const FCharacterEvent &InCharacterEvent)
Called after a character is entered while this widget has keyboard focus.
virtual FReply OnKeyDown (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
Called after a key is pressed when this widget has focus (this event bubbles if not handled)
virtual FReply OnKeyUp (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
Called after a key is released when this widget has focus.
virtual TOptional< TSharedRef< SWidget > > OnMapCursor (const FCursorReply &CursorReply) const
After OnCursorQuery has specified a cursor type the system asks each widget under the mouse to map that cursor to a widget.
virtual FReply OnMotionDetected (const FGeometry &MyGeometry, const FMotionEvent &InMotionEvent)
Called when motion is detected (controller or device) e.g.
virtual void OnMouseCaptureLost (const FCaptureLostEvent &CaptureLostEvent)
Called when this widget had captured the mouse, but that capture has been revoked for some reason.
virtual void OnMouseEnter (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system will use this event to notify a widget that the cursor has entered it.
virtual void OnMouseLeave (const FPointerEvent &MouseEvent)
The system will use this event to notify a widget that the cursor has left it.
virtual FReply OnMouseMove (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system calls this method to notify the widget that a mouse moved within it.
virtual FReply OnMouseWheel (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Called when the mouse wheel is spun.
virtual FNavigationReply OnNavigation (const FGeometry &MyGeometry, const FNavigationEvent &InNavigationEvent)
Called when navigation is requested e.g.
virtual FReply OnPreviewKeyDown (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
Called after a key is pressed when this widget or a child of this widget has focus If a widget handles this event, OnKeyDown will not be passed to the focused widget.
virtual FReply OnPreviewMouseButtonDown (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Just like OnMouseButtonDown, but tunnels instead of bubbling.
virtual FPopupMethodReply OnQueryPopupMethod () const
Popups can manifest in a NEW OS WINDOW or via an OVERLAY in an existing window.
virtual TOptional< bool > OnQueryShowFocus (const EFocusCause InFocusCause) const
Called to determine if we should render the focus brush.
virtual void OnToolTipClosing ()
Called when a tooltip displayed from this widget is being closed.
virtual FReply OnTouchFirstMove (const FGeometry &MyGeometry, const FPointerEvent &TouchEvent)
Called when a touchpad touch first moves after TouchStarted.
virtual FReply OnTouchForceChanged (const FGeometry &MyGeometry, const FPointerEvent &TouchEvent)
Called when a touchpad touch force changes.
virtual FReply OnTouchGesture (const FGeometry &MyGeometry, const FPointerEvent &GestureEvent)
Called when the user performs a gesture on trackpad.
virtual FReply OnTouchMoved (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is moved (finger moved)
virtual TSharedPtr< FPopupLayer > OnVisualizePopup (const TSharedRef< SWidget > &PopupContent)
Visualize a new pop-up if possible.
virtual bool OnVisualizeTooltip (const TSharedPtr< SWidget > &TooltipContent)
Called when Slate wants to visualize tooltip.
int32 Paint (const FPaintArgs &Args, const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, FSlateWindowElementList &OutDrawElements, int32 LayerId, const FWidgetStyle &InWidgetStyle, bool bParentEnabled) const
Called to tell a widget to paint itself (and it's children).
TSharedRef< FActiveTimerHandle > RegisterActiveTimer (float TickPeriod, FWidgetActiveTimerDelegate TickFunction)
Registers an "active timer" delegate that will execute at some regular interval.
template<typename MetaDataType>
int32 RemoveMetaData (const TSharedRef< MetaDataType > &RemoveMe)
Remove metadata to this widget.
void SetCanTick (bool bInCanTick)
void SetClipping (EWidgetClipping InClipping)
Sets the clipping to bounds rules for this widget.
FORCEINLINE void SetCullingBoundsExtension (const FMargin &InCullingBoundsExtension)
Sets an additional culling padding that is added to a widget to give more leeway when culling widgets.
void SetCursor (const TAttribute< TOptional< EMouseCursor::Type > > &InCursor)
Set the cursor that should appear when this widget is hovered.
void SetEnabled (TAttribute< bool > InEnabledState)
Sets the enabled state of this widget.
void SetFlowDirectionPreference (EFlowDirectionPreference InFlowDirectionPreference)
Sets how content should flow in this panel, based on the current culture.
void SetOnMouseButtonDown (FPointerEventHandler EventHandler)
See OnMouseButtonDown event.
void SetOnMouseButtonUp (FPointerEventHandler EventHandler)
See OnMouseButtonUp event.
void SetOnMouseDoubleClick (FPointerEventHandler EventHandler)
See OnMouseDoubleClick event.
void SetOnMouseEnter (FNoReplyPointerEventHandler EventHandler)
See OnMouseEnter event.
void SetOnMouseLeave (FSimpleNoReplyPointerEventHandler EventHandler)
See OnMouseLeave event.
void SetOnMouseMove (FPointerEventHandler EventHandler)
See OnMouseMove event.
void SetPixelSnapping (EWidgetPixelSnapping InPixelSnappingMethod)
Sets the pixel snapping method for this widget.
FORCEINLINE void SetRenderOpacity (float InRenderOpacity)
FORCEINLINE void SetRenderTransform (TAttribute< TOptional< FSlateRenderTransform > > InTransform)
FORCEINLINE void SetRenderTransformPivot (TAttribute< FVector2D > InTransformPivot)
FORCEINLINE void SetTag (FName InTag)
void SetToolTip (const TAttribute< TSharedPtr< IToolTip > > &InToolTip)
Set the tool tip that should appear when this widget is hovered.
void SetToolTipText (const FText &InToolTipText)
Set the tool tip that should appear when this widget is hovered.
void SetToolTipText (const TAttribute< FText > &ToolTipText)
Set the tool tip that should appear when this widget is hovered.
FORCEINLINE bool ShouldInvalidatePrepassDueToVolatility ()
void SlatePrepass ()
DEPRECATED version of SlatePrepass that assumes no scaling beyond AppScale.
void SlatePrepass (float InLayoutScaleMultiplier)
Descends to leaf-most widgets in the hierarchy and gathers desired sizes on the way up.
virtual bool SupportsKeyboardFocus () const
Checks to see if this widget supports keyboard focus.
virtual void Tick (const FGeometry &AllottedGeometry, const double InCurrentTime, const float InDeltaTime)
Ticks this widget with Geometry.
virtual FString ToString () const
virtual TOptional< FVirtualPointerPosition > TranslateMouseCoordinateForCustomHitTestChild (const SWidget &ChildWidget, const FGeometry &MyGeometry, const FVector2D ScreenSpaceMouseCoordinate, const FVector2D LastScreenSpaceMouseCoordinate) const
void UnRegisterActiveTimer (const TSharedRef< FActiveTimerHandle > &ActiveTimerHandle)
Unregisters an active timer handle.
virtual bool ValidatePathToChild (SWidget *InChild)
Public Member Functions inherited from FSlateControlledConstruction
FSlateControlledConstruction ()=default
virtual ~FSlateControlledConstruction ()=default
virtual const FSlateWidgetClassData & GetWidgetClass () const =0
void operator delete (void *mem)
Public Member Functions inherited from TSharedFromThis< SWidget >
TSharedRef< SWidget, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< SWidget, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Data Fields
TabWellContentLeft ContentPadding Label Tab icons are now being managed by tab spawners and toolkits In the rare case you need to set an icon manually
Protected Member Functions
EVisibility GetActiveTabIndicatorVisibility () const
UE::Slate::FDeprecateVector2DResult GetAnimatedScale () const
FText GetCloseButtonToolTipText () const
The close button tooltip showing the appropriate close command shortcut.
const FSlateBrush * GetColorOverlayImageBrush () const
const FDockTabStyle & GetCurrentStyle () const
FSlateColor GetFlashColor () const
const FSlateBrush * GetFlashOverlayImageBrush () const
float GetFlashValue () const
Get the desired color of tab.
FSlateColor GetIconColor () const
const FSlateBrush * GetImageBrush () const
FSlateColor GetTabColor () const
FMargin GetTabIconBorderPadding () const
TOptional< FVector2D > GetTabIconSize () const
FMargin GetTabPadding () const
EVisibility HandleIsCloseButtonVisible () const
FReply OnCloseButtonClicked ()
Called when the close button is clicked on the tab.
void ProvideDefaultIcon (const FSlateBrush *InDefaultIcon)
Provide a default tab icon.
void SetLayoutIdentifier (const FTabId &TabId)
Specify the TabId that was used to spawn this tab.
Protected Member Functions inherited from SBorder
virtual FVector2D ComputeDesiredSize (float) const override
Compute the ideal size necessary to display this widget.
TSlateAttributeRef< FSlateColor > GetBorderBackgroundColorAttribute () const
TSlateAttributeRef< const FSlateBrush * > GetBorderImageAttribute () const
FVector2D GetDesiredSizeScale () const
Get the desired size scale multiplier.
TSlateAttributeRef< FVector2D > GetDesiredSizeScaleAttribute () const
bool GetShowDisabledEffect () const
Get whether or not to show the disabled effect when this border is disabled.
TSlateAttributeRef< bool > GetShowDisabledEffectAttribute () const
Protected Member Functions inherited from SCompoundWidget
SCompoundWidget ()
Disallow public construction.
virtual ~SCompoundWidget ()
TSlateAttributeRef< FLinearColor > GetColorAndOpacityAttribute () const
TSlateAttributeRef< FVector2D > GetContentScaleAttribute () const
TSlateAttributeRef< FSlateColor > GetForegroundColorAttribute () const
Protected Member Functions inherited from SWidget
SWidget ()
Hidden default constructor.
virtual ~SWidget ()
Dtor ensures that active timer handles are UnRegistered with the SlateApplication.
FORCEINLINE bool Advanced_InvalidateVolatility ()
Recalculates and caches volatility and returns 'true' if the volatility changed.
virtual void CacheDesiredSize (float InLayoutScaleMultiplier)
The system calls this method.
EFlowDirection ComputeFlowDirection () const
Establishes a new flow direction potentially, if this widget has a particular preference for it and all its children.
virtual bool ComputeVolatility () const
Recomputes the volatility of the widget.
virtual bool CustomPrepass (float LayoutScaleMultiplier)
bool FindChildGeometries (const FGeometry &MyGeometry, const TSet< TSharedRef< SWidget > > &WidgetsToFind, TMap< TSharedRef< SWidget >, FArrangedWidget > &OutResult) const
Find the geometry of a descendant widget.
void FindChildGeometries_Helper (const FGeometry &MyGeometry, const TSet< TSharedRef< SWidget > > &WidgetsToFind, TMap< TSharedRef< SWidget >, FArrangedWidget > &OutResult) const
Actual implementation of FindChildGeometries.
FGeometry FindChildGeometry (const FGeometry &MyGeometry, TSharedRef< SWidget > WidgetToFind) const
Find the geometry of a descendant widget.
virtual TOptional< EMouseCursor::Type > GetCursor () const
The cursor to show when the mouse is hovering over this widget.
TSlateAttributeRef< bool > GetEnabledStateAttribute () const
virtual const FSlateBrush * GetFocusBrush () const
TSlateAttributeRef< bool > GetHoveredAttribute () const
float GetPrepassLayoutScaleMultiplier () const
TSlateAttributeRef< TOptional< FSlateRenderTransform > > GetRenderTransformAttribute () const
TSlateAttributeRef< FVector2D > GetRenderTransformPivotAttribute () const
TSlateAttributeRef< EVisibility > GetVisibilityAttribute () const
void InvalidateChildRemovedFromTree (SWidget &Child)
Called when a child is removed from the tree parent's widget tree either by removing it from a slot.
FORCEINLINE bool IsChildWidgetCulled (const FSlateRect &, const FArrangedWidget &) const
bool IsConstructed () const
Is the widget construction completed (did we called and returned from the Construct() function)
virtual void OnClippingChanged ()
Called when clipping is changed.
void Prepass_ChildLoop (float InLayoutScaleMultiplier, FChildren *MyChildren)
template<typename TargetValueType, typename SourceValueType>
bool SetAttribute (TAttribute< TargetValueType > &TargetValue, const TAttribute< SourceValueType > &SourceValue, EInvalidateWidgetReason BaseInvalidationReason)
Performs the attribute assignment and invalidates the widget minimally based on what actually changed.
void SetDebugInfo (const ANSICHAR *InType, const ANSICHAR *InFile, int32 OnLine, size_t InAllocSize)
Used by Slate to set the runtime debug info about this widget.
void SetHover (TAttribute< bool > InHovered)
Set the hover state.
void SetVolatilePrepass (bool bVolatile)
bool ShouldBeEnabled (bool InParentEnabled) const
Determines if this widget should be enabled.
void SWidgetConstruct (const FSlateBaseNamedArgs &Args)
Construct a SWidget based on initial parameters.
Protected Member Functions inherited from TSharedFromThis< SWidget >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Protected Attributes
bool bCanEverClose
Determines whether the close button for the tab is shown.
bool bShouldAutosize
Should this tab be auto-sized based on its content?
TSharedRef< SWidget > Content
The stuff to show when this tab is selected.
TAttribute< FMargin > ContentAreaPadding
TSharedPtr< SDockingArea > DraggedOverDockingArea
The dock area this tab is currently being dragged over.
FCurveSequence FlashTabCurve
Animation that causes the tab to flash.
const FDockTabStyle * GenericTabStyle
TAttribute< FLinearColor > IconColor
Color of this tab's icon.
TSharedPtr< SImage > IconWidget
Widget used to show the icon on the tab.
TSharedPtr< STextBlock > LabelSuffix
TSharedPtr< STextBlock > LabelWidget
Widget used to show the label on the tab.
double LastActivationTime
Time this tab was last activated.
FTabId LayoutIdentifier
The tab's layout identifier.
const FDockTabStyle * MajorTabStyle
The styles used to draw the tab in its various states.
TWeakPtr< FTabManager > MyTabManager
The tab manager that created this tab.
FCanCloseTab OnCanCloseTab
Delegate to execute to determine if we can close this tab.
FExtendContextMenu OnExtendContextMenu
FOnPersistVisualState OnPersistVisualState
Invoked during the Save Visual State pass; gives this tab a chance to save misc info about visual state.
FOnTabActivatedCallback OnTabActivated
Callback to call when this tab is activated.
FOnTabClosedCallback OnTabClosed
Callback to call when this tab is destroyed.
FSimpleDelegate OnTabDraggedOverDockArea
FSimpleDelegate OnTabDrawerClosedEvent
FSimpleDelegate OnTabDrawerOpenedEvent
FSimpleDelegate OnTabRelocated
FOnTabRenamed OnTabRenamed
Invoked when the tab is renamed.
TWeakPtr< SDockingTabWell > ParentPtr
The tab's parent tab well.
FCurveSequence SpawnAnimCurve
Animation that shows the tab opening up.
TAttribute< FLinearColor > TabColorScale
Color of this tab.
TAttribute< const FSlateBrush * > TabIcon
The icon on the tab.
TAttribute< FText > TabLabel
The label on the tab.
TAttribute< FText > TabLabelSuffix
A second text field at the end of the Label that takes precedence and isn't lost when space is restricted.
ETabRole TabRole
Is this an MajorTab?
TSharedRef< SWidget > TabWellContentLeft
TSharedRef< SWidget > TabWellContentRight
TSharedRef< SWidget > TitleBarContentRight
Protected Attributes inherited from SCompoundWidget
FCompoundWidgetOneChildSlot ChildSlot
The slot that contains this widget's descendants.
Protected Attributes inherited from SWidget
uint8 bCanHaveChildren: 1
Can the widget ever support children?
uint8 bCanSupportFocus: 1
Can the widget ever support keyboard focus.
uint8 bClippingProxy: 1
Some widgets might be a complex hierarchy of child widgets you never see.
uint8 bHasCustomPrepass: 1
uint8 bHasRelativeLayoutScale: 1
uint8 bVolatilityAlwaysInvalidatesPrepass: 1
if this widget should always invalidate the prepass step when volatile
EWidgetClipping Clipping
Set to true if all content of the widget should clip to the bounds of this widget.
FMargin CullingBoundsExtension
Can be used to enlarge the culling bounds of this widget (pre-intersection), this can be useful if you've got children that you know are using rendering transforms to render outside their standard bounds, if that happens it's possible the parent might be culled before the descendant widget is entirely off screen.
EWidgetPixelSnapping PixelSnappingMethod
When set to EPixelSnappingMethod::SnapToPixel, the widget is drawn at the nearest pixel.
float RenderOpacity
The opacity of the widget.
Private Member Functions
void CheckTabAllowed ()
void NotifyTabRelocated ()
EActiveTimerReturnType OnHandleUpdateStyle (double InCurrentTime, float InDeltaTime)
void OnParentSet ()
void OnTabDrawerClosed ()
void OnTabDrawerOpened ()
EActiveTimerReturnType TriggerActivateTab (double InCurrentTime, float InDeltaTime)
Activates the tab in its tab well.
void UpdateTabStyle ()
Private Attributes
TWeakPtr< FActiveTimerHandle > DragDropTimerHandle
The handle to the active tab activation tick.
TWeakPtr< FActiveTimerHandle > UpdateStyleTimerHandle
Friends
class FTabManager
class STabSidebar
Additional Inherited Members
Static Public Member Functions inherited from FSlateControlledConstruction
static const FSlateWidgetClassData & StaticWidgetClass ()
Static Protected Member Functions inherited from SWidget
static TAttribute< EVisibility > AccessWidgetVisibilityAttribute (const TSharedRef< SWidget > &Widget)
Protected static helper to allow widgets to access the visibility attribute of other widgets directly.
static int32 FindChildUnderMouse (const FArrangedChildren &Children, const FPointerEvent &MouseEvent)
static int32 FindChildUnderPosition (const FArrangedChildren &Children, const UE::Slate::FDeprecateVector2DParameter &ArrangedSpacePosition)
Static Protected Member Functions inherited from TSharedFromThis< SWidget >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
A tab widget that also holds on to some content that should be shown when this tab is selected.
Intended to be used in conjunction with SDockingTabStack.
Definition at line 49 of file SDockTab.h.
Constructor & Destructor Documentation
SDockTab()
SDockTab::SDockTab ()
Protected constructor; Widgets may only be constructed via a FArguments (i.e.: SNew(SDockTab))
References SDockTab().
Referenced by SDockTab(), and SLATE_BEGIN_ARGS().
Member Function Documentation
ActivateInParent()
void SDockTab::ActivateInParent (ETabActivationCause InActivationCause)
Make this tab active in its tabwell.
Parameters
InActivationMethod How this tab was activated.
References ActivateInParent().
Referenced by ActivateInParent().
CanCloseTab()
bool SDockTab::CanCloseTab () const
Returns
true if the tab can be closed right now. Example: Callback could ask user via dialog.
References CanCloseTab().
Referenced by CanCloseTab().
CheckTabAllowed()
void SDockTab::CheckTabAllowed () private
DECLARE_DELEGATE()
SDockTab::DECLARE_DELEGATE (FOnPersistVisualState)
Invoked w`en this tab should save some information about its content.
DECLARE_DELEGATE_OneParam() [1/3]
SDockTab::DECLARE_DELEGATE_OneParam (FExtendContextMenu , FMenuBuilder &)
Invoked to add entries to the tab context menu.
DECLARE_DELEGATE_OneParam() [2/3]
SDockTab::DECLARE_DELEGATE_OneParam (FOnTabClosedCallback , TSharedRef< SDockTab >)
Invoked when a tab is closing.
DECLARE_DELEGATE_OneParam() [3/3]
SDockTab::DECLARE_DELEGATE_OneParam (FOnTabRenamed , TSharedRef< SDockTab >)
Invoked when a tab is renamed.
DECLARE_DELEGATE_RetVal()
SDockTab::DECLARE_DELEGATE_RetVal (bool , FCanCloseTab)
Delegate called before a tab is closed.
Returning false will prevent the tab from closing
DECLARE_DELEGATE_TwoParams()
SDockTab::DECLARE_DELEGATE_TwoParams (FOnTabActivatedCallback , TSharedRef< SDockTab > , ETabActivationCause)
Invoked when a tab is activated.
DrawAttention()
void SDockTab::DrawAttention ()
Draws attention to the tab.
References DrawAttention().
Referenced by DrawAttention().
ExtendContextMenu()
void SDockTab::ExtendContextMenu (FMenuBuilder & MenuBuilder)
Add any entries specific to this tab to the tab context menu.
References ExtendContextMenu().
Referenced by ExtendContextMenu().
FlashTab()
void SDockTab::FlashTab ()
Flash the tab, used for drawing attention to it.
References FlashTab().
Referenced by FlashTab().
GetActiveTabIndicatorVisibility()
EVisibility SDockTab::GetActiveTabIndicatorVisibility () const protected
Returns
The visibility of the active tab indicator
GetAnimatedScale()
UE::Slate::FDeprecateVector2DResult SDockTab::GetAnimatedScale () const protected
Returns
the scaling of the tab based on the opening/closing animation
GetCloseButtonToolTipText()
FText SDockTab::GetCloseButtonToolTipText () const protected
The close button tooltip showing the appropriate close command shortcut.
GetColorOverlayImageBrush()
const FSlateBrush * SDockTab::GetColorOverlayImageBrush () const protected
Returns
the image brush for the tab's color overlay
GetContent()
TSharedRef< SWidget > SDockTab::GetContent ()
Returns
the content associated with this tab
References SWidget::SWidget(), and GetContent().
Referenced by GetContent().
GetContentAreaBrush()
const FSlateBrush * SDockTab::GetContentAreaBrush () const
What should the content area look like for this type of tab?
Documents, Apps, and Tool Panels have different backgrounds.
References GetContentAreaBrush().
Referenced by GetContentAreaBrush().
GetContentPadding()
FMargin SDockTab::GetContentPadding () const
Padding around the content when it is presented by the SDockingTabStack.
References GetContentPadding().
Referenced by GetContentPadding().
GetCurrentStyle()
const FDockTabStyle & SDockTab::GetCurrentStyle () const protected
Returns
the style currently applied to the dock tab
GetDockArea()
TSharedPtr< class SDockingArea > SDockTab::GetDockArea () const
Gets the dock area that this resides in.
References GetDockArea().
Referenced by GetDockArea().
GetFlashColor()
FSlateColor SDockTab::GetFlashColor () const protected
Returns
Returns a color to flash the background of this tab with
GetFlashOverlayImageBrush()
const FSlateBrush * SDockTab::GetFlashOverlayImageBrush () const protected
Returns
the image brush for the tab's flasher overlay
GetFlashValue()
float SDockTab::GetFlashValue () const protected
Get the desired color of tab.
These change during flashing.
GetForegroundColor()
virtual FSlateColor SDockTab::GetForegroundColor () const virtual
Returns
the Foreground color that this widget sets; unset options if the widget does not set a foreground color
Reimplemented from SCompoundWidget.
References GetForegroundColor().
Referenced by GetForegroundColor().
GetIconColor()
FSlateColor SDockTab::GetIconColor () const protected
Returns
Returns the color of this tab's icon
GetImageBrush()
const FSlateBrush * SDockTab::GetImageBrush () const protected
Returns
the image brush that best represents this tab's in its current state
GetLastActivationTime()
double SDockTab::GetLastActivationTime () inline
Returns the time this tab was last activated.
Definition at line 338 of file SDockTab.h.
References GetLastActivationTime(), and LastActivationTime.
Referenced by GetLastActivationTime().
GetLayoutIdentifier()
const FTabId SDockTab::GetLayoutIdentifier () const
Gets this tab's layout identifier.
References GetLayoutIdentifier().
Referenced by GetLayoutIdentifier().
GetLeftContent()
TSharedRef< SWidget > SDockTab::GetLeftContent ()
References SWidget::SWidget(), and GetLeftContent().
Referenced by GetLeftContent().
GetOverlapWidth()
float SDockTab::GetOverlapWidth () const
The width that this tab will overlap with side-by-side tabs.
References GetOverlapWidth().
Referenced by GetOverlapWidth().
GetParent()
TSharedPtr< SDockingTabWell > SDockTab::GetParent () const
Gets the tab's tab well parent, or nothing, if it has none.
References GetParent().
Referenced by GetParent().
GetParentDockTabStack()
TSharedPtr< SDockingTabStack > SDockTab::GetParentDockTabStack () const
Gets the dock tab stack this dockable tab resides within, if any.
References GetParentDockTabStack().
Referenced by GetParentDockTabStack().
GetParentWindow()
TSharedPtr< SWindow > SDockTab::GetParentWindow () const
Get the window in which this tab's tabmanager has placed it.
References GetParentWindow(), and SWidget::SWindow.
Referenced by GetParentWindow().
GetRightContent()
TSharedRef< SWidget > SDockTab::GetRightContent ()
References SWidget::SWidget(), and GetRightContent().
Referenced by GetRightContent().
GetTabColor()
FSlateColor SDockTab::GetTabColor () const protected
Returns
Returns a color to scale the background of this tab by
GetTabIcon()
const FSlateBrush * SDockTab::GetTabIcon () const
Gets the tab icon.
References GetTabIcon().
Referenced by GetTabIcon().
GetTabIconBorderPadding()
FMargin SDockTab::GetTabIconBorderPadding () const protected
Returns
the padding for the tab icon border
GetTabIconSize()
TOptional< FVector2D > SDockTab::GetTabIconSize () const protected
Returns
the size the tab icon should be
GetTabLabel()
FText SDockTab::GetTabLabel () const
The label on the tab.
References GetTabLabel().
Referenced by GetTabLabel().
GetTabLabelSuffix()
FText SDockTab::GetTabLabelSuffix () const
Get Label Suffix.
References GetTabLabelSuffix().
Referenced by GetTabLabelSuffix().
GetTabManagerPtr()
TSharedPtr< FTabManager > SDockTab::GetTabManagerPtr () const
Get the tab manager currently managing this tab.
Note that a user move the tab between Tab Managers, so this return value may change.
References FTabManager, and GetTabManagerPtr().
Referenced by GetTabManagerPtr().
GetTabPadding()
FMargin SDockTab::GetTabPadding () const protected
Returns
the padding for the tab widget
GetTabRole()
ETabRole SDockTab::GetTabRole () const
Is this an MajorTab?
A tool panel tab?
References GetTabRole().
Referenced by GetTabRole().
GetTabWellBrush()
const FSlateBrush * SDockTab::GetTabWellBrush () const
Depending on the tabs we put into the tab well, we want a different background brush.
References GetTabWellBrush().
Referenced by GetTabWellBrush().
GetTitleBarRightContent()
TSharedRef< SWidget > SDockTab::GetTitleBarRightContent ()
References SWidget::SWidget(), and GetTitleBarRightContent().
Referenced by GetTitleBarRightContent().
GetVisualTabRole()
ETabRole SDockTab::GetVisualTabRole () const
Similar to GetTabRole() but returns the correct role for UI style and user input purposes.
References GetVisualTabRole().
Referenced by GetVisualTabRole().
HandleIsCloseButtonVisible()
EVisibility SDockTab::HandleIsCloseButtonVisible () const protected
Returns
if the close button should be visible.
HasSiblingTab()
bool SDockTab::HasSiblingTab (const FTabId & SiblingTabId, const bool TreatIndexNoneAsWildcard = true) const
Check to see whether this tab has a sibling tab with the given tab ID.
Parameters
SiblingTabId The ID of the tab we want to find
TreatIndexNoneAsWildcard Note that this variable only takes effect if SiblingTabId has an InstanceId of INDEX_NONE. If true, we will consider this a "wildcard" search (matching any tab with the correct TabType, regardless of its InstanceId). If false, we will explicitly look for a tab with an InstanceId of INDEX_NONE
References HasSiblingTab().
Referenced by HasSiblingTab().
IsActive()
bool SDockTab::IsActive () const
Returns
True if this tab is currently focused
References IsActive().
Referenced by IsActive().
IsForeground()
bool SDockTab::IsForeground () const
Returns
True if this tab appears active; False otherwise
References IsForeground().
Referenced by IsForeground().
NotifyTabRelocated()
void SDockTab::NotifyTabRelocated () private
OnCloseButtonClicked()
FReply SDockTab::OnCloseButtonClicked () protected
Called when the close button is clicked on the tab.
OnDragDetected()
virtual FReply SDockTab::OnDragDetected (const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) override virtual
Called when Slate detects that a widget started to be dragged.
Usage: A widget can ask Slate to detect a drag. OnMouseDown() reply with FReply::Handled().DetectDrag(SharedThis(this)). Slate will either send an OnDragDetected() event or do nothing. If the user releases a mouse button or leaves the widget before a drag is triggered (maybe user started at the very edge) then no event will be sent.
Parameters
InMyGeometry Widget geometry
InMouseEvent MouseMove that triggered the drag
Reimplemented from SWidget.
References MouseEvent, and OnDragDetected().
Referenced by OnDragDetected().
OnDragEnter()
virtual void SDockTab::OnDragEnter (const FGeometry & MyGeometry, const FDragDropEvent & DragDropEvent) override virtual
Called during drag and drop when the drag enters a widget.
Enter/Leave events in slate are meant as lightweight notifications. So we do not want to capture mouse or set focus in response to these. However, OnDragEnter must also support external APIs (e.g. OLE Drag/Drop) Those require that we let them know whether we can handle the content being dragged OnDragEnter.
The concession is to return a can_handled/cannot_handle boolean rather than a full FReply.
Parameters
MyGeometry The geometry of the widget receiving the event.
DragDropEvent The drag and drop event.
Returns
A reply that indicated whether the contents of the DragDropEvent can potentially be processed by this widget.
Reimplemented from SWidget.
References OnDragEnter().
Referenced by OnDragEnter().
OnDragLeave()
virtual void SDockTab::OnDragLeave (const FDragDropEvent & DragDropEvent) override virtual
Called during drag and drop when the drag leaves a widget.
Parameters
DragDropEvent The drag and drop event.
Reimplemented from SWidget.
References OnDragLeave().
Referenced by OnDragLeave().
OnDrop()
virtual FReply SDockTab::OnDrop (const FGeometry & MyGeometry, const FDragDropEvent & DragDropEvent) override virtual
Called when the user is dropping something onto a widget; terminates drag and drop.
Parameters
MyGeometry The geometry of the widget receiving the event.
DragDropEvent The drag and drop event.
Returns
A reply that indicated whether this event was handled.
Reimplemented from SWidget.
References OnDrop().
Referenced by OnDrop().
OnHandleUpdateStyle()
EActiveTimerReturnType SDockTab::OnHandleUpdateStyle (double InCurrentTime, float InDeltaTime) private
OnMouseButtonDoubleClick()
virtual FReply SDockTab::OnMouseButtonDoubleClick (const FGeometry & InMyGeometry, const FPointerEvent & InMouseEvent) override virtual
Called when a mouse button is double clicked.
Override this in derived classes.
Parameters
InMyGeometry Widget geometry
InMouseEvent Mouse button event
Returns
Returns whether the event was handled, along with other possible actions
Reimplemented from SWidget.
References MouseEvent, and OnMouseButtonDoubleClick().
Referenced by OnMouseButtonDoubleClick().
OnMouseButtonDown()
virtual FReply SDockTab::OnMouseButtonDown (const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) override virtual
The system calls this method to notify the widget that a mouse button was pressed within it.
This event is bubbled.
Parameters
MyGeometry The Geometry of the widget receiving the event
MouseEvent Information about the input event
Returns
Whether the event was handled along with possible requests for the system to take action.
Reimplemented from SWidget.
References MouseEvent, and OnMouseButtonDown().
Referenced by OnMouseButtonDown().
OnMouseButtonUp()
virtual FReply SDockTab::OnMouseButtonUp (const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) override virtual
The system calls this method to notify the widget that a mouse button was release within it.
This event is bubbled.
Parameters
MyGeometry The Geometry of the widget receiving the event
MouseEvent Information about the input event
Returns
Whether the event was handled along with possible requests for the system to take action.
Reimplemented from SWidget.
References MouseEvent, and OnMouseButtonUp().
Referenced by OnMouseButtonUp().
OnParentSet()
void SDockTab::OnParentSet () private
OnTabDrawerClosed()
void SDockTab::OnTabDrawerClosed () private
Referenced by SLATE_EVENT().
OnTabDrawerOpened()
void SDockTab::OnTabDrawerOpened () private
OnTouchEnded()
virtual FReply SDockTab::OnTouchEnded (const FGeometry & MyGeometry, const FPointerEvent & InTouchEvent) override virtual
Called when a touchpad touch is ended (finger lifted)
Parameters
InTouchEvent The touch event generated
Reimplemented from SWidget.
References OnTouchEnded().
Referenced by OnTouchEnded().
OnTouchStarted()
virtual FReply SDockTab::OnTouchStarted (const FGeometry & MyGeometry, const FPointerEvent & InTouchEvent) override virtual
Called when a touchpad touch is started (finger down)
Parameters
InTouchEvent The touch event generated
Reimplemented from SWidget.
References OnTouchStarted().
Referenced by OnTouchStarted().
PersistVisualState()
void SDockTab::PersistVisualState ()
A chance for the tab's content to save any internal layout info.
References PersistVisualState().
Referenced by PersistVisualState().
PlaySpawnAnim()
void SDockTab::PlaySpawnAnim ()
Play an animation showing this tab as opening.
References PlaySpawnAnim().
Referenced by PlaySpawnAnim().
ProvideDefaultIcon()
void SDockTab::ProvideDefaultIcon (const FSlateBrush * InDefaultIcon) protected
Provide a default tab icon.
ProvideDefaultLabel()
void SDockTab::ProvideDefaultLabel (const FText & InDefaultLabel)
Provide a default tab label in case the spawner did not set one.
References ProvideDefaultLabel().
Referenced by ProvideDefaultLabel().
RemoveTabFromParent()
void SDockTab::RemoveTabFromParent ()
Pulls this tab out of it's parent tab stack and destroys it Note: This does not check if its safe to remove the tab.
Use RequestCloseTab to do this safely.
References RemoveTabFromParent().
Referenced by RemoveTabFromParent().
RequestCloseTab()
bool SDockTab::RequestCloseTab ()
Requests that the tab be closed.
Tabs may prevent closing depending on their state
References RequestCloseTab().
Referenced by RequestCloseTab().
SetCanCloseTab()
void SDockTab::SetCanCloseTab (const FCanCloseTab & InOnTabClosing)
Set the handler to be invoked when the user requests that this tab be closed.
References SetCanCloseTab().
Referenced by SetCanCloseTab().
SetContent()
virtual void SDockTab::SetContent (TSharedRef< SWidget > InContent) override virtual
Sets the content for this border.
Parameters
InContent The widget to use as content for the border
Reimplemented from SBorder.
References SWidget::SWidget(), and SetContent().
Referenced by SetContent().
SetDraggedOverDockArea()
void SDockTab::SetDraggedOverDockArea (const TSharedPtr< SDockingArea > & Area)
Used by the drag/drop operation to signal to this tab what it is dragging over.
References SetDraggedOverDockArea().
Referenced by SetDraggedOverDockArea().
SetLabel()
void SDockTab::SetLabel (const TAttribute< FText > & InTabLabel)
The label that appears on the tab.
References SetLabel().
Referenced by SetLabel().
SetLayoutIdentifier()
void SDockTab::SetLayoutIdentifier (const FTabId & TabId) protected
Specify the TabId that was used to spawn this tab.
SetLeftContent()
void SDockTab::SetLeftContent (TSharedRef< SWidget > InContent)
Content that appears in the TabWell to the left of the tabs.
References SWidget::SWidget(), and SetLeftContent().
Referenced by SetLeftContent().
SetOnExtendContextMenu()
void SDockTab::SetOnExtendContextMenu (const FExtendContextMenu & Handler)
Set the handler for extending the tab context menu.
References SetOnExtendContextMenu().
Referenced by SetOnExtendContextMenu().
SetOnPersistVisualState()
void SDockTab::SetOnPersistVisualState (const FOnPersistVisualState & Handler)
Set the custom code to execute for saving visual state in this tab.
e.g. ContentBrowser saves the visible filters.OnExtendContextMenu
References SetOnPersistVisualState().
Referenced by SetOnPersistVisualState().
SetOnTabActivated()
void SDockTab::SetOnTabActivated (const FOnTabActivatedCallback & InDelegate)
Set the handler that will be invoked when the tab is activated.
References SetOnTabActivated().
Referenced by SetOnTabActivated().
SetOnTabClosed()
void SDockTab::SetOnTabClosed (const FOnTabClosedCallback & InDelegate)
Set the handler that will be invoked when the tab is closed.
References SetOnTabClosed().
Referenced by SetOnTabClosed().
SetOnTabDraggedOverDockArea()
void SDockTab::SetOnTabDraggedOverDockArea (const FSimpleDelegate InDelegate)
Set the handler that will be invoked when the tab is dragged over dock area.
References SetOnTabDraggedOverDockArea().
Referenced by SetOnTabDraggedOverDockArea().
SetOnTabDrawerClosed()
void SDockTab::SetOnTabDrawerClosed (const FSimpleDelegate InDelegate)
Set the handler that will be invoked when the tab is closed from a drawer.
References SetOnTabDrawerClosed().
Referenced by SetOnTabDrawerClosed().
SetOnTabDrawerOpened()
void SDockTab::SetOnTabDrawerOpened (const FSimpleDelegate InDelegate)
Set the handler that will be invoked when the tab is opened from a drawer.
References SetOnTabDrawerOpened().
Referenced by SetOnTabDrawerOpened().
SetOnTabRelocated()
void SDockTab::SetOnTabRelocated (const FSimpleDelegate InDelegate)
Set the handler that will be invoked when the tab is relocated to a new tab well.
References SetOnTabRelocated().
Referenced by SetOnTabRelocated().
SetOnTabRenamed()
void SDockTab::SetOnTabRenamed (const FOnTabRenamed & InDelegate)
Set the handler that will be invoked when the tab is renamed.
References SetOnTabRenamed().
Referenced by SetOnTabRenamed().
SetParent()
void SDockTab::SetParent (TSharedPtr< SDockingTabWell > Parent = TSharedPtr< SDockingTabWell >())
Sets the tab's tab well parent, or resets it if nothing is passed in.
References Parent, and SetParent().
Referenced by SetParent().
SetParentDockTabStackTabWellHidden()
void SDockTab::SetParentDockTabStackTabWellHidden (bool bIsTabWellHidden)
SetRightContent()
void SDockTab::SetRightContent (TSharedRef< SWidget > InContent)
Content that appears in the TabWell to the right of the tabs.
References SWidget::SWidget(), and SetRightContent().
Referenced by SetRightContent().
SetShouldAutosize()
void SDockTab::SetShouldAutosize (const bool bNewShouldAutosize)
Set whether this tab should be sized based on its content.
References SetShouldAutosize().
Referenced by SetShouldAutosize().
SetTabIcon() [1/2]
TabWellContentLeft ContentPadding Label Tab icons are now being managed by tab spawners and toolkits In the rare case you need to set an icon use SDockTab::SetTabIcon () const & inline
Definition at line 102 of file SDockTab.h.
Referenced by SetTabIcon().
SetTabIcon() [2/2]
void SDockTab::SetTabIcon (const TAttribute< const FSlateBrush * > InTabIcon)
Sets the tab icon.
References SetTabIcon().
SetTabLabelOverflowPolicy()
void SDockTab::SetTabLabelOverflowPolicy (ETextOverflowPolicy InOverflowPolicy) const
Set the Label overflow policy.
References SetTabLabelOverflowPolicy().
Referenced by SetTabLabelOverflowPolicy().
SetTabLabelSuffix()
void SDockTab::SetTabLabelSuffix (const TAttribute< FText > & InTabLabelSuffix)
Set Label Suffix.
A second text field at the end of the Label that takes precedence and isn't lost when space is restricted
References SetTabLabelSuffix().
Referenced by SetTabLabelSuffix().
SetTabManager()
void SDockTab::SetTabManager (const TSharedPtr< FTabManager > & InTabManager)
Set the tab manager that is controlling this tab.
References FTabManager, and SetTabManager().
Referenced by SetTabManager().
SetTabToolTipWidget()
void SDockTab::SetTabToolTipWidget (TSharedPtr< SToolTip > InTabToolTipWidget)
The tooltip text that appears on the tab.
References SetTabToolTipWidget().
Referenced by SetTabToolTipWidget().
SetTitleBarRightContent()
void SDockTab::SetTitleBarRightContent (TSharedRef< SWidget > InContent)
Content that appears on the right side of the title bar in the window this stack is in.
References SWidget::SWidget(), and SetTitleBarRightContent().
Referenced by SetTitleBarRightContent().
ShouldAutosize()
bool SDockTab::ShouldAutosize () const
Should this tab be sized based on its content.
References ShouldAutosize().
Referenced by ShouldAutosize(), and SLATE_ARGUMENT().
SLATE_ARGUMENT() [1/3]
OnTabActivated OnTabDraggedOverDockArea OnCanCloseTab SDockTab::SLATE_ARGUMENT (bool , CanEverClose)
Whether this tab can ever be closed.
Example: certain programs may want to show tabs for the lifetime of the program.
References OnPersistVisualState, SLATE_ARGUMENT(), and SLATE_EVENT().
SLATE_ARGUMENT() [2/3]
OnTabActivated OnTabDraggedOverDockArea SDockTab::SLATE_ARGUMENT (bool , ShouldAutosize)
When the close button is pressed, checks whether the tab can be closed in that moment.
Example: Show dialog and ask user whether they're sure to close.
References OnCanCloseTab, ShouldAutosize(), SLATE_ARGUMENT(), and SLATE_EVENT().
SLATE_ARGUMENT() [3/3]
TabWellContentLeft ContentPadding SDockTab::SLATE_ARGUMENT (ETabRole , TabRole)
References SLATE_ARGUMENT(), SLATE_ATTRIBUTE(), and TabRole.
Referenced by SLATE_ARGUMENT(), SLATE_ARGUMENT(), SLATE_ARGUMENT(), and SLATE_ATTRIBUTE().
SLATE_ATTRIBUTE() [1/3]
OnTabActivated OnTabDraggedOverDockArea OnCanCloseTab OnPersistVisualState OnTabDrawerClosed ForegroundColor SDockTab::SLATE_ATTRIBUTE (FLinearColor , IconColor)
References IconColor, SLATE_ARGUMENT(), and SLATE_ATTRIBUTE().
SLATE_ATTRIBUTE() [2/3]
OnTabActivated OnTabDraggedOverDockArea OnCanCloseTab OnPersistVisualState OnTabDrawerClosed SDockTab::SLATE_ATTRIBUTE (FLinearColor , TabColorScale)
References SLATE_ATTRIBUTE(), and TabColorScale.
SLATE_ATTRIBUTE() [3/3]
TabWellContentLeft ContentPadding Label SDockTab::SLATE_ATTRIBUTE (FText , LabelSuffix)
References LabelSuffix, and SLATE_ATTRIBUTE().
Referenced by SLATE_ARGUMENT(), SLATE_ATTRIBUTE(), SLATE_ATTRIBUTE(), SLATE_ATTRIBUTE(), and SLATE_NAMED_SLOT().
SLATE_BEGIN_ARGS()
SDockTab::SLATE_BEGIN_ARGS (SDockTab) inline
Definition at line 73 of file SDockTab.h.
References SDockTab(), and PanelTab.
SLATE_DEFAULT_SLOT()
SDockTab::SLATE_DEFAULT_SLOT (FArguments , Content)
References Content, and TabWellContentLeft.
SLATE_END_ARGS()
OnTabActivated OnTabDraggedOverDockArea OnCanCloseTab OnPersistVisualState OnTabDrawerClosed ForegroundColor LabelOverflowPolicy SDockTab::SLATE_END_ARGS () const &
Construct the widget from the declaration.
References SBorder::Construct(), and SLATE_END_ARGS().
Referenced by SLATE_END_ARGS().
SLATE_EVENT() [1/3]
OnTabActivated OnTabDraggedOverDockArea OnCanCloseTab OnPersistVisualState SDockTab::SLATE_EVENT (FExtendContextMenu , OnExtendContextMenu)
Invoked when a tab is closed from a drawer.
This does not mean the tab or its contents is destroyed, just hidden. Use OnTabClosed for that
References OnExtendContextMenu, OnTabDrawerClosed(), and SLATE_EVENT().
SLATE_EVENT() [2/3]
SDockTab::SLATE_EVENT (FOnTabClosedCallback , OnTabClosed)
References OnTabActivated, and OnTabClosed.
Referenced by SLATE_ARGUMENT(), SLATE_ARGUMENT(), SLATE_EVENT(), and SLATE_EVENT().
SLATE_EVENT() [3/3]
OnTabActivated SDockTab::SLATE_EVENT (FSimpleDelegate , OnTabRelocated)
References OnTabDraggedOverDockArea, OnTabRelocated, and SLATE_EVENT().
SLATE_NAMED_SLOT()
TabWellContentLeft SDockTab::SLATE_NAMED_SLOT (FArguments , TabWellContentRight)
References SLATE_ATTRIBUTE(), SLATE_NAMED_SLOT(), and TabWellContentRight.
Referenced by SLATE_NAMED_SLOT().
TriggerActivateTab()
EActiveTimerReturnType SDockTab::TriggerActivateTab (double InCurrentTime, float InDeltaTime) private
Activates the tab in its tab well.
UE_DEPRECATED()
SDockTab::UE_DEPRECATED (5. 0, "The tab manager is not guaranteed to exist, which will cause GetTabManager() to crash. Use GetTabManagerPtr() instead.") const
Get the tab manager currently managing this tab.
Note that a user move the tab between Tab Managers, so this return value may change.
References FTabManager, and UE_DEPRECATED().
Referenced by UE_DEPRECATED().
UpdateActivationTime()
void SDockTab::UpdateActivationTime ()
Updates the 'last activated' time to the current time.
References UpdateActivationTime().
Referenced by UpdateActivationTime().
UpdateTabStyle()
void SDockTab::UpdateTabStyle () private
Friends And Related Symbol Documentation
FTabManager
friend class FTabManager friend
Definition at line 51 of file SDockTab.h.
References FTabManager.
Referenced by FTabManager, GetTabManagerPtr(), SetTabManager(), and UE_DEPRECATED().
STabSidebar
friend class STabSidebar friend
Definition at line 52 of file SDockTab.h.
References STabSidebar.
Referenced by STabSidebar.
Field Documentation
bCanEverClose
bool SDockTab::bCanEverClose protected
Determines whether the close button for the tab is shown.
Definition at line 433 of file SDockTab.h.
bShouldAutosize
bool SDockTab::bShouldAutosize protected
Should this tab be auto-sized based on its content?
Definition at line 482 of file SDockTab.h.
Content
TSharedRef<SWidget> SDockTab::Content protected
The stuff to show when this tab is selected.
Definition at line 421 of file SDockTab.h.
Referenced by SLATE_DEFAULT_SLOT().
ContentAreaPadding
TAttribute<FMargin> SDockTab::ContentAreaPadding protected
Definition at line 479 of file SDockTab.h.
DragDropTimerHandle
TWeakPtr<FActiveTimerHandle> SDockTab::DragDropTimerHandle private
The handle to the active tab activation tick.
Definition at line 413 of file SDockTab.h.
DraggedOverDockingArea
TSharedPtr<SDockingArea> SDockTab::DraggedOverDockingArea protected
The dock area this tab is currently being dragged over.
Used in nomad tabs to change style
Definition at line 503 of file SDockTab.h.
FlashTabCurve
FCurveSequence SDockTab::FlashTabCurve protected
Animation that causes the tab to flash.
Definition at line 497 of file SDockTab.h.
GenericTabStyle
const FDockTabStyle* SDockTab::GenericTabStyle protected
Definition at line 477 of file SDockTab.h.
IconColor
TAttribute<FLinearColor> SDockTab::IconColor protected
Color of this tab's icon.
Definition at line 488 of file SDockTab.h.
Referenced by SLATE_ATTRIBUTE().
IconWidget
TSharedPtr<SImage> SDockTab::IconWidget protected
Widget used to show the icon on the tab.
Definition at line 510 of file SDockTab.h.
LabelSuffix
TSharedPtr<STextBlock> SDockTab::LabelSuffix protected
Definition at line 507 of file SDockTab.h.
Referenced by SLATE_ATTRIBUTE().
LabelWidget
TSharedPtr<STextBlock> SDockTab::LabelWidget protected
Widget used to show the label on the tab.
Definition at line 506 of file SDockTab.h.
LastActivationTime
double SDockTab::LastActivationTime protected
Time this tab was last activated.
Definition at line 513 of file SDockTab.h.
Referenced by GetLastActivationTime().
LayoutIdentifier
FTabId SDockTab::LayoutIdentifier protected
The tab's layout identifier.
Definition at line 427 of file SDockTab.h.
MajorTabStyle
const FDockTabStyle* SDockTab::MajorTabStyle protected
The styles used to draw the tab in its various states.
Definition at line 476 of file SDockTab.h.
manually
TabWellContentLeft ContentPadding Label Tab icons are now being managed by tab spawners and toolkits In the rare case you need to set an icon SDockTab::manually
Definition at line 102 of file SDockTab.h.
MyTabManager
TWeakPtr<FTabManager> SDockTab::MyTabManager protected
The tab manager that created this tab.
Definition at line 418 of file SDockTab.h.
OnCanCloseTab
FCanCloseTab SDockTab::OnCanCloseTab protected
Delegate to execute to determine if we can close this tab.
Definition at line 454 of file SDockTab.h.
Referenced by SLATE_ARGUMENT().
OnExtendContextMenu
FExtendContextMenu SDockTab::OnExtendContextMenu protected
Definition at line 464 of file SDockTab.h.
Referenced by SLATE_EVENT().
OnPersistVisualState
FOnPersistVisualState SDockTab::OnPersistVisualState protected
Invoked during the Save Visual State pass; gives this tab a chance to save misc info about visual state.
e.g. Content Browser might save the current filters, current folder, whether some panel is collapsed, etc.
Definition at line 470 of file SDockTab.h.
Referenced by SLATE_ARGUMENT().
OnTabActivated
FOnTabActivatedCallback SDockTab::OnTabActivated protected
Callback to call when this tab is activated.
Definition at line 451 of file SDockTab.h.
Referenced by SLATE_EVENT().
OnTabClosed
FOnTabClosedCallback SDockTab::OnTabClosed protected
Callback to call when this tab is destroyed.
Definition at line 448 of file SDockTab.h.
Referenced by SLATE_EVENT().
OnTabDraggedOverDockArea
FSimpleDelegate SDockTab::OnTabDraggedOverDockArea protected
Definition at line 462 of file SDockTab.h.
Referenced by SLATE_EVENT().
OnTabDrawerClosedEvent
FSimpleDelegate SDockTab::OnTabDrawerClosedEvent protected
Definition at line 456 of file SDockTab.h.
OnTabDrawerOpenedEvent
FSimpleDelegate SDockTab::OnTabDrawerOpenedEvent protected
Definition at line 458 of file SDockTab.h.
OnTabRelocated
FSimpleDelegate SDockTab::OnTabRelocated protected
Definition at line 460 of file SDockTab.h.
Referenced by SLATE_EVENT().
OnTabRenamed
FOnTabRenamed SDockTab::OnTabRenamed protected
Invoked when the tab is renamed.
Definition at line 473 of file SDockTab.h.
ParentPtr
TWeakPtr<SDockingTabWell> SDockTab::ParentPtr protected
The tab's parent tab well.
Null if it is a floating tab.
Definition at line 436 of file SDockTab.h.
SpawnAnimCurve
FCurveSequence SDockTab::SpawnAnimCurve protected
Animation that shows the tab opening up.
Definition at line 494 of file SDockTab.h.
TabColorScale
TAttribute<FLinearColor> SDockTab::TabColorScale protected
Color of this tab.
Definition at line 485 of file SDockTab.h.
Referenced by SLATE_ATTRIBUTE().
TabIcon
TAttribute<const FSlateBrush*> SDockTab::TabIcon protected
The icon on the tab.
Definition at line 445 of file SDockTab.h.
TabLabel
TAttribute<FText> SDockTab::TabLabel protected
The label on the tab.
Definition at line 439 of file SDockTab.h.
TabLabelSuffix
TAttribute<FText> SDockTab::TabLabelSuffix protected
A second text field at the end of the Label that takes precedence and isn't lost when space is restricted.
Definition at line 442 of file SDockTab.h.
TabRole
ETabRole SDockTab::TabRole protected
Is this an MajorTab?
A tool panel tab?
Definition at line 430 of file SDockTab.h.
Referenced by SLATE_ARGUMENT().
TabWellContentLeft
TSharedRef<SWidget> SDockTab::TabWellContentLeft protected
Definition at line 422 of file SDockTab.h.
Referenced by SLATE_DEFAULT_SLOT().
TabWellContentRight
TSharedRef<SWidget> SDockTab::TabWellContentRight protected
Definition at line 423 of file SDockTab.h.
Referenced by SLATE_NAMED_SLOT().
TitleBarContentRight
TSharedRef<SWidget> SDockTab::TitleBarContentRight protected
Definition at line 424 of file SDockTab.h.
UpdateStyleTimerHandle
TWeakPtr<FActiveTimerHandle> SDockTab::UpdateStyleTimerHandle private
Definition at line 414 of file SDockTab.h.
The documentation for this class was generated from the following file:
Runtime/Slate/Public/Widgets/Docking/SDockTab.h