Unreal Engine 5.6 C++ API: UE::Sequencer::FLinkedOutlinerExtension Class Reference
UE::Sequencer::FLinkedOutlinerExtension Class Reference
Extension for a model that is linked somehow to an outliner model.
#include "LinkedOutlinerExtension.h"
Public Member Functions
FLinkedOutlinerExtension ()
TViewModelPtr< IOutlinerExtension > GetLinkedOutlinerItem () const
void SetLinkedOutlinerItem (const TViewModelPtr< IOutlinerExtension > &InOutlinerItem)
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID (FLinkedOutlinerExtension)
Private Attributes
TWeakViewModelPtr< IOutlinerExtension > WeakModel
Detailed Description
Extension for a model that is linked somehow to an outliner model.
This is the case for example in Sequencer where the channels of the sections in the track area are linked to the channel group items in the outliner.
Definition at line 22 of file LinkedOutlinerExtension.h.
Constructor & Destructor Documentation
FLinkedOutlinerExtension()
UE::Sequencer::FLinkedOutlinerExtension::FLinkedOutlinerExtension ()
Referenced by UE::Sequencer::FBindingLifetimeOverlayModel::UE_SEQUENCER_DECLARE_CASTABLE(), UE::Sequencer::FCategoryModel::UE_SEQUENCER_DECLARE_CASTABLE(), UE::Sequencer::FChannelModel::UE_SEQUENCER_DECLARE_CASTABLE(), UE::Sequencer::FLayerBarModel::UE_SEQUENCER_DECLARE_CASTABLE(), UE::Sequencer::FSectionModel::UE_SEQUENCER_DECLARE_CASTABLE(), and UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID().
Member Function Documentation
GetLinkedOutlinerItem()
TViewModelPtr< IOutlinerExtension > UE::Sequencer::FLinkedOutlinerExtension::GetLinkedOutlinerItem () const
SetLinkedOutlinerItem()
void UE::Sequencer::FLinkedOutlinerExtension::SetLinkedOutlinerItem (const TViewModelPtr< IOutlinerExtension > & InOutlinerItem)
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID()
UE::Sequencer::FLinkedOutlinerExtension::UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID (FLinkedOutlinerExtension)
References FLinkedOutlinerExtension().
Field Documentation
WeakModel
TWeakViewModelPtr<IOutlinerExtension> UE::Sequencer::FLinkedOutlinerExtension::WeakModel private
Definition at line 36 of file LinkedOutlinerExtension.h.
The documentation for this class was generated from the following file:
Editor/SequencerCore/Public/MVVM/Extensions/LinkedOutlinerExtension.h