Unreal Engine 5.6 C++ API: IMovieScenePlaybackClient Class Reference
IMovieScenePlaybackClient Class Reference abstract
Movie scene binding overrides interface.
#include "IMovieScenePlaybackClient.h"
Public Member Functions
virtual TOptional< EAspectRatioAxisConstraint > GetAspectRatioAxisConstraint () const
Whether this playback client wants a specific aspect ratio axis constraint during playback.
virtual UObject * GetInstanceData () const =0
Retrieve the optional instance data that should be used for this evaluation.
virtual bool GetIsReplicatedPlayback () const
virtual GENERATED_BODY() static MOVIESCENE_API UE bool RetrieveBindingOverrides (const FGuid &InBindingId, FMovieSceneSequenceID InSequenceID, TArray< UObject *, TInlineAllocator< 1 > > &OutObjects) const =0
Locate bound objects that relate to the specified binding ID.
virtual void WarpEvaluationRange (FMovieSceneEvaluationRange &InOutRange) const
Detailed Description
Movie scene binding overrides interface.
Definition at line 24 of file IMovieScenePlaybackClient.h.
Member Function Documentation
GetAspectRatioAxisConstraint()
virtual TOptional< EAspectRatioAxisConstraint > IMovieScenePlaybackClient::GetAspectRatioAxisConstraint () const inline virtual
Whether this playback client wants a specific aspect ratio axis constraint during playback.
Reimplemented in ALevelSequenceActor.
Definition at line 48 of file IMovieScenePlaybackClient.h.
References GetAspectRatioAxisConstraint().
Referenced by GetAspectRatioAxisConstraint().
GetInstanceData()
virtual UObject * IMovieScenePlaybackClient::GetInstanceData () const pure virtual
Retrieve the optional instance data that should be used for this evaluation.
Implemented in ALevelSequenceActor.
References GetInstanceData().
Referenced by GetInstanceData().
GetIsReplicatedPlayback()
virtual bool IMovieScenePlaybackClient::GetIsReplicatedPlayback () const inline virtual
Reimplemented in ALevelSequenceActor.
Definition at line 56 of file IMovieScenePlaybackClient.h.
RetrieveBindingOverrides()
virtual GENERATED_BODY() static MOVIESCENE_API UE bool IMovieScenePlaybackClient::RetrieveBindingOverrides (const FGuid & InBindingId, FMovieSceneSequenceID InSequenceID, TArray< UObject *, TInlineAllocator< 1 > > & OutObjects) const pure virtual
Locate bound objects that relate to the specified binding ID.
Parameters
InBindingId The GUID of the object binding in the movie scene
OutObjects Array to populate with bound objects
Returns
true to prevent default lookup of the binding in the sequence itself, else false
Implemented in ALevelSequenceActor.
References RetrieveBindingOverrides().
Referenced by RetrieveBindingOverrides().
WarpEvaluationRange()
virtual void IMovieScenePlaybackClient::WarpEvaluationRange (FMovieSceneEvaluationRange & InOutRange) const inline virtual
Definition at line 65 of file IMovieScenePlaybackClient.h.
The documentation for this class was generated from the following file:
Runtime/MovieScene/Public/IMovieScenePlaybackClient.h