Unreal Engine 5.6 C++ API: TCbWriter< InlineBufferSize > Class Template Reference
TCbWriter< InlineBufferSize > Class Template Reference
A writer for compact binary object, arrays, and fields that uses a fixed-size stack buffer.
#include "CompactBinaryWriter.h"
Public Member Functions
TCbWriter ()
TCbWriter (const TCbWriter &)=delete
TCbWriter & operator= (const TCbWriter &)=delete
Public Member Functions inherited from FCbWriter
FCbWriter ()
FCbWriter (const FCbWriter &)=delete
~FCbWriter ()
void AddArray (const FCbArray &Value)
void AddArray (const FCbArrayView &Value)
void AddArray (FUtf8StringView Name, const FCbArray &Value)
Copy the value (not the name) of an existing array.
void AddArray (FUtf8StringView Name, const FCbArrayView &Value)
Copy the value (not the name) of an existing array.
void AddAttachment (const FCbAttachment &Attachment)
void AddAttachment (FUtf8StringView Name, const FCbAttachment &Attachment)
Write a field referencing the attachment by its hash.
void AddBinary (const FCompositeBuffer &Value)
void AddBinary (const FSharedBuffer &Value)
void AddBinary (const void *Value, uint64 Size)
void AddBinary (FMemoryView Value)
void AddBinary (FUtf8StringView Name, const FCompositeBuffer &Value)
void AddBinary (FUtf8StringView Name, const FSharedBuffer &Value)
Write a binary field by copying the buffer.
void AddBinary (FUtf8StringView Name, const void *Value, uint64 Size)
Write a binary field by copying Size bytes from Value.
void AddBinary (FUtf8StringView Name, FMemoryView Value)
Write a binary field by copying the view.
void AddBinaryAttachment (const FIoHash &Value)
void AddBinaryAttachment (FUtf8StringView Name, const FIoHash &Value)
Write a field referencing a binary attachment by its hash.
void AddBool (bool bValue)
void AddBool (FUtf8StringView Name, bool bValue)
Write a bool field.
void AddCustom (FUtf8StringView FieldName, FUtf8StringView TypeName, FMemoryView Value)
Write a custom field with a string sub-type identifier.
void AddCustom (FUtf8StringView FieldName, uint64 TypeId, FMemoryView Value)
Write a custom field with an integer sub-type identifier.
void AddCustom (FUtf8StringView TypeName, FMemoryView Value)
void AddCustom (uint64 TypeId, FMemoryView Value)
void AddDateTime (FDateTime Value)
void AddDateTime (FUtf8StringView Name, FDateTime Value)
Write a date/time field.
void AddDateTimeTicks (FUtf8StringView Name, int64 Ticks)
Write a date/time field with the specified count of 100ns ticks since the epoch.
void AddDateTimeTicks (int64 Ticks)
void AddField (const FCbField &Value)
void AddField (const FCbFieldView &Value)
void AddField (FUtf8StringView Name, const FCbField &Value)
Copy the value (not the name) of an existing field.
void AddField (FUtf8StringView Name, const FCbFieldView &Value)
Copy the value (not the name) of an existing field.
void AddFloat (double Value)
void AddFloat (float Value)
void AddFloat (FUtf8StringView Name, double Value)
Write a float field from a 64-bit float value.
void AddFloat (FUtf8StringView Name, float Value)
Write a float field from a 32-bit float value.
void AddHash (const FIoHash &Value)
void AddHash (FUtf8StringView Name, const FIoHash &Value)
Write a hash field.
void AddInteger (FUtf8StringView Name, int32 Value)
Write an integer field.
void AddInteger (FUtf8StringView Name, int64 Value)
Write an integer field.
void AddInteger (FUtf8StringView Name, uint32 Value)
Write an integer field.
void AddInteger (FUtf8StringView Name, uint64 Value)
Write an integer field.
void AddInteger (int32 Value)
void AddInteger (int64 Value)
void AddInteger (uint32 Value)
void AddInteger (uint64 Value)
void AddNull ()
void AddNull (FUtf8StringView Name)
Write a null field.
void AddObject (const FCbObject &Value)
void AddObject (const FCbObjectView &Value)
void AddObject (FUtf8StringView Name, const FCbObject &Value)
Copy the value (not the name) of an existing object.
void AddObject (FUtf8StringView Name, const FCbObjectView &Value)
Copy the value (not the name) of an existing object.
void AddObjectAttachment (const FIoHash &Value)
void AddObjectAttachment (FUtf8StringView Name, const FIoHash &Value)
Write a field referencing an object attachment by its hash.
void AddObjectId (const FCbObjectId &Value)
void AddObjectId (FUtf8StringView Name, const FCbObjectId &Value)
Write an ObjectId field.
void AddString (FUtf8StringView Name, FUtf8StringView Value)
Write a string field by copying the UTF-8 value.
void AddString (FUtf8StringView Name, FWideStringView Value)
Write a string field by converting the UTF-16 value to UTF-8.
void AddString (FUtf8StringView Value)
void AddString (FWideStringView Value)
void AddTimeSpan (FTimespan Value)
void AddTimeSpan (FUtf8StringView Name, FTimespan Value)
Write a time span field.
void AddTimeSpanTicks (FUtf8StringView Name, int64 Ticks)
Write a time span field with the specified count of 100ns ticks.
void AddTimeSpanTicks (int64 Ticks)
void AddUuid (const FGuid &Value)
void AddUuid (FUtf8StringView Name, const FGuid &Value)
Write a UUID field.
void BeginArray ()
void BeginArray (FUtf8StringView Name)
Begin a new array.
void BeginObject ()
void BeginObject (FUtf8StringView Name)
Begin a new object.
void EndArray ()
End an array after its fields have been written.
void EndObject ()
End an object after its fields have been written.
uint64 GetSaveSize () const
The size of buffer (in bytes) required to serialize the fields that have been written.
FCbWriter & operator<< (bool Value)
FCbWriter & operator<< (const ANSICHAR *NameOrValue)
Write the field name if valid in this state, otherwise write the string value.
FCbWriter & operator<< (const FAnsiString &Value)
FCbWriter & operator<< (const FCbArray &Value)
FCbWriter & operator<< (const FCbArrayView &Value)
FCbWriter & operator<< (const FCbAttachment &Attachment)
FCbWriter & operator<< (const FCbField &Value)
FCbWriter & operator<< (const FCbFieldView &Value)
FCbWriter & operator<< (const FCbObject &Value)
FCbWriter & operator<< (const FCbObjectId &Value)
FCbWriter & operator<< (const FCbObjectView &Value)
FCbWriter & operator<< (const FGuid &Value)
FCbWriter & operator<< (const FIoHash &Value)
FCbWriter & operator<< (const FString &Value)
FCbWriter & operator<< (const FUtf8String &Value)
template<typename T, typename Allocator, std::void_t< decltype(std::declval< FCbWriter & >()<< std::declval< const T & >())> * = nullptr>
FCbWriter & operator<< (const TArray< T, Allocator > &Value)
FCbWriter & operator<< (const UTF8CHAR *NameOrValue)
Write the field name if valid in this state, otherwise write the string value.
FCbWriter & operator<< (const WIDECHAR *Value)
FCbWriter & operator<< (double Value)
FCbWriter & operator<< (FDateTime Value)
FCbWriter & operator<< (float Value)
FCbWriter & operator<< (FName Value)
FCbWriter & operator<< (FTimespan Value)
FCbWriter & operator<< (FUtf8StringView NameOrValue)
Write the field name if valid in this state, otherwise write the string value.
FCbWriter & operator<< (FWideStringView Value)
FCbWriter & operator<< (int32 Value)
FCbWriter & operator<< (int64 Value)
FCbWriter & operator<< (nullptr_t)
FCbWriter & operator<< (uint32 Value)
FCbWriter & operator<< (uint64 Value)
FCbWriter & operator= (const FCbWriter &)=delete
void Reset ()
Empty the writer without releasing any allocated memory.
FCbFieldIterator Save () const
Serialize the field(s) to an owned buffer and return it as an iterator.
void Save (FArchive &Ar) const
Serialize the field(s) to an archive.
FCbFieldViewIterator Save (FMutableMemoryView Buffer) const
Serialize the field(s) to memory.
FCbWriter & SetName (FUtf8StringView Name)
Sets the name of the next field to be written.
Private Attributes
uint8 Buffer [InlineBufferSize]
Additional Inherited Members
Protected Member Functions inherited from FCbWriter
FCbWriter (int64 InitialSize)
Reserve the specified size up front until the format is optimized.
Detailed Description
template<uint32 InlineBufferSize>
class TCbWriter< InlineBufferSize >
A writer for compact binary object, arrays, and fields that uses a fixed-size stack buffer.
See also
FCbWriter
Definition at line 476 of file CompactBinaryWriter.h.
Constructor & Destructor Documentation
TCbWriter() [1/2]
template<uint32 InlineBufferSize> TCbWriter< InlineBufferSize >::TCbWriter () inline
Definition at line 479 of file CompactBinaryWriter.h.
References FCbWriter::FCbWriter().
Referenced by TCbWriter(), and operator=().
TCbWriter() [2/2]
template<uint32 InlineBufferSize> TCbWriter< InlineBufferSize >::TCbWriter (const TCbWriter< InlineBufferSize > &) delete
References TCbWriter().
Member Function Documentation
operator=()
template<uint32 InlineBufferSize> TCbWriter & TCbWriter< InlineBufferSize >::operator= (const TCbWriter< InlineBufferSize > &) delete
References TCbWriter().
Field Documentation
Buffer
template<uint32 InlineBufferSize> uint8 TCbWriter< InlineBufferSize >::Buffer[InlineBufferSize] private
Definition at line 490 of file CompactBinaryWriter.h.
The documentation for this class was generated from the following file:
Runtime/Core/Public/Serialization/CompactBinaryWriter.h