Unreal Engine 5.6 C++ API: UE::Net::TStructNetTokenDataStoreHelper< T > Class Template Reference
UE::Net::TStructNetTokenDataStoreHelper< T > Class Template Reference
#include "StructNetTokenDataStoreHelper.h"
Public Types
using DataStoreType = TStructNetTokenDataStore<T>
Static Public Member Functions
static bool AddStateToReplayExportGroup (DataStoreType *StateTokenStore, T &InData, TSharedPtr< FNetFieldExportGroup > NetFieldExportGroup, UPackageMapClient &Map)
static bool GetStateFromReplayExportGroup (DataStoreType *StateTokenStore, T &OutData, FNetToken &StateToken, TSharedPtr< FNetFieldExportGroup > NetFieldExportGroup, UPackageMapClient &Map)
static bool NetSerializeAndExportToken (FArchive &Ar, UPackageMap *Map, T &InOutStateData)
static bool NetSerializeStateDataAsReplayData (DataStoreType *StateTokenStore, T &InOutStateData, FArchive &Ar, UPackageMapClient &PackageMapClient)
static void SerializeHelper (T &InOutData, FArchive &Ar, UPackageMap *Map)
static bool SetupReplayExportGroup (DataStoreType *StateTokenStore, UPackageMapClient &PackageMapClient)
Detailed Description
template<typename T>
class UE::Net::TStructNetTokenDataStoreHelper< T >
Definition at line 18 of file StructNetTokenDataStoreHelper.h.
Member Typedef Documentation
DataStoreType
template<typename T> using UE::Net::TStructNetTokenDataStoreHelper< T >::DataStoreType = TStructNetTokenDataStore<T>
Definition at line 22 of file StructNetTokenDataStoreHelper.h.
Member Function Documentation
AddStateToReplayExportGroup()
template<typename T> bool UE::Net::TStructNetTokenDataStoreHelper< T >::AddStateToReplayExportGroup (DataStoreType * StateTokenStore, T & InData, TSharedPtr< FNetFieldExportGroup > NetFieldExportGroup, UPackageMapClient & Map) inline static
Definition at line 169 of file StructNetTokenDataStoreHelper.h.
References FNetFieldExport::bExported, FBitWriter::GetBuffer(), TSharedPtr< ObjectType, InMode >::IsValid(), Map, No, TEXT, ToString(), UE_LOG, and UE::Verbose.
Referenced by NetSerializeStateDataAsReplayData(), and SetupReplayExportGroup().
GetStateFromReplayExportGroup()
template<typename T> bool UE::Net::TStructNetTokenDataStoreHelper< T >::GetStateFromReplayExportGroup (DataStoreType * StateTokenStore, T & OutData, FNetToken & StateToken, TSharedPtr< FNetFieldExportGroup > NetFieldExportGroup, UPackageMapClient & Map) inline static
Definition at line 149 of file StructNetTokenDataStoreHelper.h.
References TArray< InElementType, InAllocatorType >::GetData(), TSharedPtr< ObjectType, InMode >::IsValid(), Map, TArray< InElementType, InAllocatorType >::NumBytes(), and FBitReader::SetData().
Referenced by NetSerializeStateDataAsReplayData().
NetSerializeAndExportToken()
template<typename T> bool UE::Net::TStructNetTokenDataStoreHelper< T >::NetSerializeAndExportToken (FArchive & Ar, UPackageMap * Map, T & InOutStateData) inline static
Definition at line 41 of file StructNetTokenDataStoreHelper.h.
References Ar, Cast(), Map, NetSerializeStateDataAsReplayData(), SerializeHelper(), TEXT, ToString(), UE_LOG, and Warning.
NetSerializeStateDataAsReplayData()
template<typename T> bool UE::Net::TStructNetTokenDataStoreHelper< T >::NetSerializeStateDataAsReplayData (DataStoreType * StateTokenStore, T & InOutStateData, FArchive & Ar, UPackageMapClient & PackageMapClient) inline static
Definition at line 100 of file StructNetTokenDataStoreHelper.h.
References AddStateToReplayExportGroup(), Ar, TSharedPtr< ObjectType, InMode >::Get(), GetStateFromReplayExportGroup(), TSharedPtr< ObjectType, InMode >::IsValid(), No, SetupReplayExportGroup(), and ToString().
Referenced by NetSerializeAndExportToken().
SerializeHelper()
template<typename T> void UE::Net::TStructNetTokenDataStoreHelper< T >::SerializeHelper (T & InOutData, FArchive & Ar, UPackageMap * Map) inline static
Definition at line 24 of file StructNetTokenDataStoreHelper.h.
References Ar, Cast(), check, IsValid(), TSharedPtr< ObjectType, InMode >::IsValid(), Map, StaticStruct(), and Struct.
Referenced by NetSerializeAndExportToken().
SetupReplayExportGroup()
template<typename T> bool UE::Net::TStructNetTokenDataStoreHelper< T >::SetupReplayExportGroup (DataStoreType * StateTokenStore, UPackageMapClient & PackageMapClient) inline static
Definition at line 195 of file StructNetTokenDataStoreHelper.h.
References AddStateToReplayExportGroup(), TSharedPtr< ObjectType, InMode >::IsValid(), and MakeShared().
Referenced by NetSerializeStateDataAsReplayData().
The documentation for this class was generated from the following file:
Runtime/Engine/Public/Net/Iris/ReplicationSystem/StructNetTokenDataStoreHelper.h