Unreal Engine 5.6 C++ API: FScriptArrayHelper Class Reference
FScriptArrayHelper Class Reference
FScriptArrayHelper: Pseudo dynamic array.
#include "UnrealType.h"
Public Member Functions
FORCEINLINE FScriptArrayHelper (const FArrayProperty *InProperty, const void *InArray)
Constructor, brings together a property and an instance of the property located in memory.
FORCEINLINE int32 AddUninitializedValue ()
Add an uninitialized value to the end of the array.
int32 AddUninitializedValues (int32 Count)
Add uninitialized values to the end of the array.
FORCEINLINE int32 AddValue ()
Add a blank, constructed values to the end of the array.
int32 AddValues (int32 Count)
Add blank, constructed values to the end of the array.
void ClearValues (int32 Index, int32 Count=1)
Clear values in the array.
void CountBytes (FArchive &Ar) const
Used by memory counting archives to accumulate the size of this array.
void DestroyContainer_Unsafe ()
Destroys the container object - THERE SHOULD BE NO MORE USE OF THIS HELPER AFTER THIS FUNCTION IS CALLED!
void EmptyAndAddUninitializedValues (int32 Count)
Empty the array, then add uninitialized values to a given size.
void EmptyAndAddValues (int32 Count)
Empty the array, then add blank, constructed values to a given size.
void EmptyValues (int32 Slack=0)
Remove all values from the array, calling destructors, etc as appropriate.
bool ExpandForIndex (int32 Index)
Expand the array, if needed, so that the given index is valid.
FORCEINLINE uint8 * GetElementPtr (int32 Index=0)
Returns a uint8 pointer to an element in the array.
FORCEINLINE uint8 * GetRawPtr (int32 Index=0)
Returns a uint8 pointer to an element in the array.
void InsertValues (int32 Index, int32 Count=1)
Insert blank, constructed values into the array.
FORCEINLINE bool IsValidIndex (int32 Index) const
Index range check.
void MoveAssign (void *InOtherArray)
Move the allocation from another array and make it our own.
FORCEINLINE int32 Num () const
Return the number of elements in the array.
FORCEINLINE int32 NumUnchecked () const
Return the number of elements in the array without validating the state of the array.
void RemoveValues (int32 Index, int32 Count=1)
Remove values from the array, calling destructors, etc as appropriate.
void Resize (int32 Count)
Add or remove elements to set the array to a given size.
void SwapValues (int32 A, int32 B)
Swap two elements in the array, does not call constructors and destructors.
Static Public Member Functions
static FScriptArrayHelper CreateHelperFormInnerProperty (const FProperty *InInnerProperty, const void *InArray, EArrayPropertyFlags InArrayFlags=EArrayPropertyFlags::None)
Private Types
enum EInternal { Internal }
Private Member Functions
FScriptArrayHelper (EInternal, const FProperty *InInnerProperty, const void *InArray, int32 InElementSize, uint32 InElementAlignment, EArrayPropertyFlags InArrayFlags)
void ClearItems (int32 Index, int32 Count)
Internal function to call into the property system to clear elements.
void ConstructItems (int32 Index, int32 Count)
Internal function to call into the property system to construct / initialize elements.
void DestructItems (int32 Index, int32 Count)
Internal function to call into the property system to destruct elements.
template<typename CallableType>
auto WithScriptArray (CallableType &&Callable) const
Private Attributes
union {
FFreezableScriptArray * FreezableArray
FScriptArray * HeapArray
};
EArrayPropertyFlags ArrayFlags
uint32 ElementAlignment
int32 ElementSize
const FProperty * InnerProperty
Detailed Description
FScriptArrayHelper: Pseudo dynamic array.
Used to work with array properties in a sensible way.
Definition at line 3849 of file UnrealType.h.
Member Enumeration Documentation
EInternal
enum FScriptArrayHelper::EInternal private
Enumerator
Internal
Definition at line 3851 of file UnrealType.h.
Constructor & Destructor Documentation
FScriptArrayHelper() [1/2]
FORCEINLINE FScriptArrayHelper::FScriptArrayHelper (const FArrayProperty * InProperty, const void * InArray) inline
Constructor, brings together a property and an instance of the property located in memory.
Parameters
InProperty the property associated with this memory
InArray pointer to raw memory that corresponds to this array. This can be NULL, and sometimes is, but in that case almost all operations will crash.
Definition at line 3872 of file UnrealType.h.
References FScriptArrayHelper(), ArrayFlags, and FORCEINLINE.
Referenced by FPropertyBagArrayRef::FPropertyBagArrayRef(), FScriptArrayHelper(), FScriptArrayHelper_InContainer::FScriptArrayHelper_InContainer(), FScriptArrayHelper_InContainer::FScriptArrayHelper_InContainer(), and CreateHelperFormInnerProperty().
FScriptArrayHelper() [2/2]
FScriptArrayHelper::FScriptArrayHelper (EInternal , const FProperty * InInnerProperty, const void * InArray, int32 InElementSize, uint32 InElementAlignment, EArrayPropertyFlags InArrayFlags) inline private
Definition at line 4130 of file UnrealType.h.
References ArrayFlags, check, ElementAlignment, ElementSize, FreezableArray, HeapArray, and InnerProperty.
Member Function Documentation
AddUninitializedValue()
FORCEINLINE int32 FScriptArrayHelper::AddUninitializedValue () inline
Add an uninitialized value to the end of the array.
Returns
the index of the newly added item.
Definition at line 4026 of file UnrealType.h.
References AddUninitializedValues(), and FORCEINLINE.
AddUninitializedValues()
int32 FScriptArrayHelper::AddUninitializedValues (int32 Count) inline
Add uninitialized values to the end of the array.
Parameters
Count the number of items to insert.
Returns
the index of the first newly added item.
Definition at line 4015 of file UnrealType.h.
References Array, check, checkSlow, Count, ElementAlignment, ElementSize, Num, and WithScriptArray().
Referenced by AddUninitializedValue(), AddValues(), and EmptyAndAddUninitializedValues().
AddValue()
FORCEINLINE int32 FScriptArrayHelper::AddValue () inline
Add a blank, constructed values to the end of the array.
Returns
the index of the newly added item.
Definition at line 4006 of file UnrealType.h.
References AddValues(), and FORCEINLINE.
AddValues()
int32 FScriptArrayHelper::AddValues (int32 Count) inline
Add blank, constructed values to the end of the array.
Parameters
Count the number of items to insert.
Returns
the index of the first newly added item.
Definition at line 3996 of file UnrealType.h.
References AddUninitializedValues(), ConstructItems(), and Count.
Referenced by AddValue(), EmptyAndAddValues(), ExpandForIndex(), FRigVMMemoryHandle::GetData_Internal(), and Resize().
ClearItems()
void FScriptArrayHelper::ClearItems (int32 Index, int32 Count) inline private
Internal function to call into the property system to clear elements.
Parameters
Index first item to .
Count number of items to .
Definition at line 4204 of file UnrealType.h.
References checkSlow, Count, ElementSize, GetRawPtr(), InnerProperty, FMemory::Memzero(), and Num.
Referenced by ClearValues().
ClearValues()
void FScriptArrayHelper::ClearValues (int32 Index, int32 Count = 1) inline
Clear values in the array.
The meaning of clear is defined by the property system.
Parameters
Index first item to clear.
Count number of items to clear.
Definition at line 4077 of file UnrealType.h.
References check, ClearItems(), and Count.
ConstructItems()
void FScriptArrayHelper::ConstructItems (int32 Index, int32 Count) inline private
Internal function to call into the property system to construct / initialize elements.
Parameters
Index first item to .
Count number of items to .
Definition at line 4155 of file UnrealType.h.
References checkSlow, Count, ElementSize, GetRawPtr(), InnerProperty, FMemory::Memzero(), and Num.
CountBytes()
void FScriptArrayHelper::CountBytes (FArchive & Ar) const inline
Used by memory counting archives to accumulate the size of this array.
Parameters
Ar archive to accumulate sizes
Definition at line 4111 of file UnrealType.h.
References Ar, Array, ElementSize, and WithScriptArray().
CreateHelperFormInnerProperty()
FScriptArrayHelper FScriptArrayHelper::CreateHelperFormInnerProperty (const FProperty * InInnerProperty, const void * InArray, EArrayPropertyFlags InArrayFlags = EArrayPropertyFlags::None) inline static
Definition at line 4124 of file UnrealType.h.
References FScriptArrayHelper(), FProperty::GetElementSize(), and FProperty::GetMinAlignment().
DestroyContainer_Unsafe()
void FScriptArrayHelper::DestroyContainer_Unsafe () inline
Destroys the container object - THERE SHOULD BE NO MORE USE OF THIS HELPER AFTER THIS FUNCTION IS CALLED!
Definition at line 4119 of file UnrealType.h.
References Array, DestructItem(), and WithScriptArray().
DestructItems()
void FScriptArrayHelper::DestructItems (int32 Index, int32 Count) inline private
Internal function to call into the property system to destruct elements.
Parameters
Index first item to .
Count number of items to .
Definition at line 4182 of file UnrealType.h.
References checkSlow, Count, ElementSize, GetRawPtr(), InnerProperty, and Num.
EmptyAndAddUninitializedValues()
void FScriptArrayHelper::EmptyAndAddUninitializedValues (int32 Count) inline
Empty the array, then add uninitialized values to a given size.
Parameters
Count the number of items the array will have on completion.
Definition at line 3946 of file UnrealType.h.
References AddUninitializedValues(), check, checkSlow, Count, EmptyValues(), and Num.
EmptyAndAddValues()
void FScriptArrayHelper::EmptyAndAddValues (int32 Count) inline
Empty the array, then add blank, constructed values to a given size.
Parameters
Count the number of items the array will have on completion.
Definition at line 3935 of file UnrealType.h.
References AddValues(), check, checkSlow, Count, EmptyValues(), and Num.
EmptyValues()
void FScriptArrayHelper::EmptyValues (int32 Slack = 0) inline
Remove all values from the array, calling destructors, etc as appropriate.
Parameters
Slack used to presize the array for a subsequent add, to avoid reallocation.
Definition at line 4046 of file UnrealType.h.
References Array, checkSlow, DestructItems(), ElementAlignment, ElementSize, NumUnchecked(), and WithScriptArray().
Referenced by EmptyAndAddUninitializedValues(), and EmptyAndAddValues().
ExpandForIndex()
bool FScriptArrayHelper::ExpandForIndex (int32 Index) inline
Expand the array, if needed, so that the given index is valid.
Parameters
Index index for the item that we want to ensure is valid
Returns
true if expansion was necessary NOTE: This is not a count, it is an INDEX, so the final count will be at least Index+1 this matches the usage.
Definition at line 3959 of file UnrealType.h.
References AddValues(), check, checkSlow, and Num.
GetElementPtr()
FORCEINLINE uint8 * FScriptArrayHelper::GetElementPtr (int32 Index = 0) inline
Returns a uint8 pointer to an element in the array.
This call is identical to GetRawPtr and is here to provide interface parity with FScriptSetHelper*.
Parameters
Index index of the item to return a pointer to.
Returns
Pointer to this element, or NULL if the array is empty
Definition at line 3927 of file UnrealType.h.
References FORCEINLINE, and GetRawPtr().
GetRawPtr()
FORCEINLINE uint8 * FScriptArrayHelper::GetRawPtr (int32 Index = 0) inline
Returns a uint8 pointer to an element in the array.
Parameters
Index index of the item to return a pointer to.
Returns
Pointer to this element, or NULL if the array is empty
Definition at line 3911 of file UnrealType.h.
References Array, checkSlow, ElementSize, FORCEINLINE, IsValidIndex(), Num, and WithScriptArray().
Referenced by ClearItems(), ConstructItems(), FRigVMGraphEnumDetailCustomization::ContainerMemoryBlockToEnumPtr(), FRigVMGraphMathTypeDetailCustomization::ContainerMemoryBlockToValueRef(), FSequencerKeyStructGenerator::CopyInstanceToKey(), DestructItems(), FPropertyBagArrayRef::GetAddress(), EditorAnimUtils::GetAssetsFromProperties(), FRigVMMemoryHandle::GetData_Internal(), GetElementPtr(), FPropertyBagArrayRef::GetMutableAddress(), FTrackInstancePropertyBindings::FResolvedProperty::GetPropertyAddress(), and FPropertyChangedParams::GetPropertyValue().
InsertValues()
void FScriptArrayHelper::InsertValues (int32 Index, int32 Count = 1) inline
Insert blank, constructed values into the array.
Parameters
Index index of the first inserted item after completion
Count the number of items to insert.
Definition at line 4035 of file UnrealType.h.
References Array, check, ConstructItems(), Count, ElementAlignment, ElementSize, Num, and WithScriptArray().
IsValidIndex()
FORCEINLINE bool FScriptArrayHelper::IsValidIndex (int32 Index) const inline
Index range check.
Parameters
Index Index to check
Returns
true if accessing this element is legal.
Definition at line 3882 of file UnrealType.h.
References FORCEINLINE, and Num.
Referenced by FRigVMGraphEnumDetailCustomization::ContainerMemoryBlockToEnumPtr(), FRigVMGraphMathTypeDetailCustomization::ContainerMemoryBlockToValueRef(), FPropertyBagArrayRef::GetAddress(), FPropertyBagArrayRef::GetMutableAddress(), FTrackInstancePropertyBindings::FResolvedProperty::GetPropertyAddress(), FPropertyChangedParams::GetPropertyValue(), and GetRawPtr().
MoveAssign()
void FScriptArrayHelper::MoveAssign (void * InOtherArray) inline
Move the allocation from another array and make it our own.
Note
The arrays MUST be of the same type, and this function will NOT validate that!
Parameters
InOtherArray The array to move the allocation from.
Definition at line 4099 of file UnrealType.h.
References Array, checkSlow, DestructItems(), ElementAlignment, ElementSize, Num, and WithScriptArray().
Num()
FORCEINLINE int32 FScriptArrayHelper::Num () const inline
Return the number of elements in the array.
Returns
The number of elements in the array.
Definition at line 3890 of file UnrealType.h.
References Array, checkSlow, FORCEINLINE, and WithScriptArray().
Referenced by EditorAnimUtils::GetAssetsFromProperties(), and FRigVMMemoryHandle::GetData_Internal().
NumUnchecked()
FORCEINLINE int32 FScriptArrayHelper::NumUnchecked () const inline
Return the number of elements in the array without validating the state of the array.
Needed to allow reading of the num when the array is 'invalid' during its intrusive unset state.
Returns
The number of elements in the array.
Definition at line 3901 of file UnrealType.h.
References Array, FORCEINLINE, and WithScriptArray().
Referenced by EmptyValues().
RemoveValues()
void FScriptArrayHelper::RemoveValues (int32 Index, int32 Count = 1) inline
Remove values from the array, calling destructors, etc as appropriate.
Parameters
Index first item to remove.
Count number of items to remove.
Definition at line 4064 of file UnrealType.h.
References Array, check, Count, DestructItems(), ElementAlignment, ElementSize, Num, and WithScriptArray().
Referenced by Resize().
Resize()
void FScriptArrayHelper::Resize (int32 Count) inline
Add or remove elements to set the array to a given size.
Parameters
Count the number of items the array will have on completion.
Definition at line 3974 of file UnrealType.h.
References AddValues(), Count, Num, UE::Core::Private::OnInvalidArrayNum(), and RemoveValues().
SwapValues()
void FScriptArrayHelper::SwapValues (int32 A, int32 B) inline
Swap two elements in the array, does not call constructors and destructors.
Parameters
A index of one item to swap.
B index of the other item to swap.
Definition at line 4089 of file UnrealType.h.
References A, Array, B, ElementSize, and WithScriptArray().
WithScriptArray()
template<typename CallableType> auto FScriptArrayHelper::WithScriptArray (CallableType && Callable) const inline private
Definition at line 3854 of file UnrealType.h.
References ArrayFlags, FreezableArray, and HeapArray.
Referenced by AddUninitializedValues(), CountBytes(), DestroyContainer_Unsafe(), EmptyValues(), GetRawPtr(), InsertValues(), MoveAssign(), Num(), NumUnchecked(), RemoveValues(), and SwapValues().
Field Documentation
[union]
union { ... } FScriptArrayHelper
ArrayFlags
EArrayPropertyFlags FScriptArrayHelper::ArrayFlags private
Definition at line 4235 of file UnrealType.h.
Referenced by FScriptArrayHelper(), FScriptArrayHelper(), and WithScriptArray().
ElementAlignment
uint32 FScriptArrayHelper::ElementAlignment private
Definition at line 4234 of file UnrealType.h.
Referenced by FScriptArrayHelper(), AddUninitializedValues(), EmptyValues(), InsertValues(), MoveAssign(), and RemoveValues().
ElementSize
int32 FScriptArrayHelper::ElementSize private
Definition at line 4233 of file UnrealType.h.
Referenced by FScriptArrayHelper(), AddUninitializedValues(), ClearItems(), ConstructItems(), CountBytes(), DestructItems(), EmptyValues(), GetRawPtr(), InsertValues(), MoveAssign(), RemoveValues(), and SwapValues().
FreezableArray
FFreezableScriptArray* FScriptArrayHelper::FreezableArray
Definition at line 4231 of file UnrealType.h.
Referenced by FScriptArrayHelper(), and WithScriptArray().
HeapArray
FScriptArray* FScriptArrayHelper::HeapArray
Definition at line 4230 of file UnrealType.h.
Referenced by FScriptArrayHelper(), and WithScriptArray().
InnerProperty
const FProperty* FScriptArrayHelper::InnerProperty private
Definition at line 4227 of file UnrealType.h.
Referenced by FScriptArrayHelper(), ClearItems(), ConstructItems(), and DestructItems().
The documentation for this class was generated from the following file:
Runtime/CoreUObject/Public/UObject/UnrealType.h