Unreal Engine 5.6 C++ API: UE::Geometry::TMeshWindingNumberGrid< TriangleMeshType > Class Template Reference
UE::Geometry::TMeshWindingNumberGrid< TriangleMeshType > Class Template Reference
Sample mesh winding number (MWN) on a discrete grid.
#include "MeshWindingNumberGrid.h"
Public Types
enum EComputeModes { FullGrid = 0 , NarrowBand = 1 }
Public Member Functions
TMeshWindingNumberGrid (const TriangleMeshType *Mesh, TFastWindingTree< TriangleMeshType > *FastWinding, double CellSize)
constexpr const float & At (int I, int J, int K) const
FVector3f CellCenter (int I, int J, int K)
void Compute ()
FVector3i Dimensions () const
float GetValue (const FVector3i &IJK) const
Data Fields
int BufferCells = 1
bool bWantMeshSDFGrid = true
TFunction< bool()> CancelF = [](){ return false; }
if this function returns true, we should abort calculation
double CellSize
EComputeModes ComputeMode = EComputeModes::NarrowBand
TFastWindingTree< TriangleMeshType > * FastWinding
FVector3f GridOrigin
const TriangleMeshType * Mesh
TSweepingMeshSDF< TriangleMeshType > MeshSDF
FDenseGrid3f WindingGrid
float WindingIsoValue = 0.5f
Private Member Functions
void fill_spans (int ni, int nj, int nk, FDenseGrid3f &winding)
void make_grid (FVector3f origin, float dx, int ni, int nj, int nk, FDenseGrid3f &winding)
void make_grid_dense (FVector3f origin, float dx, int ni, int nj, int nk, FDenseGrid3f &winding)
Detailed Description
template<class TriangleMeshType>
class UE::Geometry::TMeshWindingNumberGrid< TriangleMeshType >
Sample mesh winding number (MWN) on a discrete grid.
Can sample full grid, or compute MWN values along a specific iso-contour and then fill in rest of grid with correctly-signed values via fast sweeping (this is the default)
TODO:
I think we are over-exploring the grid most of the time. eg along an x-ray that intersects the surface, we only need at most 2 cells, but we are computing at least 3, and possibly 5.
it may be better to use something like bloomenthal polygonizer continuation? where we are keeping track of active edges instead of active cells?
Definition at line 34 of file MeshWindingNumberGrid.h.
Member Enumeration Documentation
EComputeModes
template<class TriangleMeshType> enum UE::Geometry::TMeshWindingNumberGrid::EComputeModes
Enumerator
FullGrid
NarrowBand
Definition at line 48 of file MeshWindingNumberGrid.h.
Constructor & Destructor Documentation
TMeshWindingNumberGrid()
template<class TriangleMeshType> UE::Geometry::TMeshWindingNumberGrid< TriangleMeshType >::TMeshWindingNumberGrid (const TriangleMeshType * Mesh, TFastWindingTree< TriangleMeshType > * FastWinding, double CellSize) inline
Definition at line 74 of file MeshWindingNumberGrid.h.
References CellSize, FastWinding, float, Mesh, and MeshSDF.
Member Function Documentation
At()
template<class TriangleMeshType> const float & UE::Geometry::TMeshWindingNumberGrid< TriangleMeshType >::At (int I, int J, int K) const inline constexpr
Definition at line 122 of file MeshWindingNumberGrid.h.
References WindingGrid.
CellCenter()
template<class TriangleMeshType> FVector3f UE::Geometry::TMeshWindingNumberGrid< TriangleMeshType >::CellCenter (int I, int J, int K) inline
Definition at line 132 of file MeshWindingNumberGrid.h.
References CellSize, and GridOrigin.
Compute()
template<class TriangleMeshType> void UE::Geometry::TMeshWindingNumberGrid< TriangleMeshType >::Compute () inline
Definition at line 80 of file MeshWindingNumberGrid.h.
References BufferCells, bWantMeshSDFGrid, CellSize, ComputeMode, FastWinding, float, FullGrid, GridOrigin, UE::Geometry::TAxisAlignedBox3< RealType >::IsEmpty(), make_grid(), make_grid_dense(), UE::Geometry::TAxisAlignedBox3< RealType >::Max, MeshSDF, UE::Geometry::TAxisAlignedBox3< RealType >::Min, UE::Math::TVector< float >::One(), WindingGrid, UE::Math::TVector< T >::X, UE::Math::TVector< T >::Y, and UE::Math::TVector< T >::Z.
Referenced by UE::Geometry::FOccupancyGrid3::FOccupancyGrid3().
Dimensions()
template<class TriangleMeshType> FVector3i UE::Geometry::TMeshWindingNumberGrid< TriangleMeshType >::Dimensions () const inline
Definition at line 117 of file MeshWindingNumberGrid.h.
References WindingGrid.
Referenced by UE::Geometry::FOccupancyGrid3::FOccupancyGrid3().
fill_spans()
template<class TriangleMeshType> void UE::Geometry::TMeshWindingNumberGrid< TriangleMeshType >::fill_spans (int ni, int nj, int nk, FDenseGrid3f & winding) inline private
Definition at line 330 of file MeshWindingNumberGrid.h.
References TMathUtilConstants< float >::MaxReal, ParallelFor(), and WindingIsoValue.
GetValue()
template<class TriangleMeshType> float UE::Geometry::TMeshWindingNumberGrid< TriangleMeshType >::GetValue (const FVector3i & IJK) const inline
Definition at line 127 of file MeshWindingNumberGrid.h.
References WindingGrid.
make_grid()
template<class TriangleMeshType> void UE::Geometry::TMeshWindingNumberGrid< TriangleMeshType >::make_grid (FVector3f origin, float dx, int ni, int nj, int nk, FDenseGrid3f & winding) inline private
Definition at line 141 of file MeshWindingNumberGrid.h.
References TArray< InElementType, InAllocatorType >::Add(), TSet< InElementType, KeyFuncs, Allocator >::Add(), UE::Geometry::TDenseGrid3< ElemType >::Assign(), UE::Geometry::TDenseGrid3< ElemType >::Bounds(), CancelF, CellSize, UE::Geometry::FAxisAlignedBox3i::Contains(), FastWinding, float, IndexUtil::GridOffsets26, UE::Geometry::FAxisAlignedBox3i::Max, TMathUtilConstants< float >::MaxReal, MeshSDF, TArray< InElementType, InAllocatorType >::Num(), TSet< InElementType, KeyFuncs, Allocator >::Num(), UE::Geometry::FVector3i::One(), ParallelFor(), TArray< InElementType, InAllocatorType >::Reset(), TSet< InElementType, KeyFuncs, Allocator >::Reset(), UE::Geometry::TDenseGrid3< ElemType >::Resize(), TArray< InElementType, InAllocatorType >::SetNumZeroed(), UE::Geometry::TDenseGrid3< ElemType >::Size(), UE::Geometry::TDenseGrid3< ElemType >::ToIndex(), UE::Geometry::TDenseGrid3< ElemType >::ToLinear(), WindingIsoValue, UE::Geometry::FVector3i::X, UE::Geometry::FVector3i::Y, and UE::Geometry::FVector3i::Z.
Referenced by Compute().
make_grid_dense()
template<class TriangleMeshType> void UE::Geometry::TMeshWindingNumberGrid< TriangleMeshType >::make_grid_dense (FVector3f origin, float dx, int ni, int nj, int nk, FDenseGrid3f & winding) inline private
Definition at line 304 of file MeshWindingNumberGrid.h.
References FastWinding, float, ParallelFor(), UE::Geometry::TDenseGrid3< ElemType >::Resize(), UE::Geometry::TDenseGrid3< ElemType >::Size(), UE::Geometry::TDenseGrid3< ElemType >::ToIndex(), UE::Geometry::FVector3i::X, UE::Geometry::FVector3i::Y, and UE::Geometry::FVector3i::Z.
Referenced by Compute().
Field Documentation
BufferCells
template<class TriangleMeshType> int UE::Geometry::TMeshWindingNumberGrid< TriangleMeshType >::BufferCells = 1
Definition at line 44 of file MeshWindingNumberGrid.h.
Referenced by Compute().
bWantMeshSDFGrid
template<class TriangleMeshType> bool UE::Geometry::TMeshWindingNumberGrid< TriangleMeshType >::bWantMeshSDFGrid = true
Definition at line 61 of file MeshWindingNumberGrid.h.
Referenced by Compute().
CancelF
template<class TriangleMeshType> TFunction<bool()> UE::Geometry::TMeshWindingNumberGrid< TriangleMeshType >::CancelF = [](){ return false; }
if this function returns true, we should abort calculation
Definition at line 64 of file MeshWindingNumberGrid.h.
Referenced by make_grid().
CellSize
template<class TriangleMeshType> double UE::Geometry::TMeshWindingNumberGrid< TriangleMeshType >::CellSize
Definition at line 41 of file MeshWindingNumberGrid.h.
Referenced by TMeshWindingNumberGrid(), CellCenter(), Compute(), and make_grid().
ComputeMode
template<class TriangleMeshType> EComputeModes UE::Geometry::TMeshWindingNumberGrid< TriangleMeshType >::ComputeMode = EComputeModes::NarrowBand
Definition at line 53 of file MeshWindingNumberGrid.h.
Referenced by Compute().
FastWinding
template<class TriangleMeshType> TFastWindingTree<TriangleMeshType>* UE::Geometry::TMeshWindingNumberGrid< TriangleMeshType >::FastWinding
Definition at line 38 of file MeshWindingNumberGrid.h.
Referenced by TMeshWindingNumberGrid(), Compute(), make_grid(), and make_grid_dense().
GridOrigin
template<class TriangleMeshType> FVector3f UE::Geometry::TMeshWindingNumberGrid< TriangleMeshType >::GridOrigin
Definition at line 67 of file MeshWindingNumberGrid.h.
Referenced by UE::Geometry::FOccupancyGrid3::FOccupancyGrid3(), CellCenter(), and Compute().
Mesh
template<class TriangleMeshType> const TriangleMeshType* UE::Geometry::TMeshWindingNumberGrid< TriangleMeshType >::Mesh
Definition at line 37 of file MeshWindingNumberGrid.h.
Referenced by TMeshWindingNumberGrid().
MeshSDF
template<class TriangleMeshType> TSweepingMeshSDF<TriangleMeshType> UE::Geometry::TMeshWindingNumberGrid< TriangleMeshType >::MeshSDF
Definition at line 71 of file MeshWindingNumberGrid.h.
Referenced by TMeshWindingNumberGrid(), Compute(), and make_grid().
WindingGrid
template<class TriangleMeshType> FDenseGrid3f UE::Geometry::TMeshWindingNumberGrid< TriangleMeshType >::WindingGrid
Definition at line 68 of file MeshWindingNumberGrid.h.
Referenced by At(), Compute(), Dimensions(), and GetValue().
WindingIsoValue
template<class TriangleMeshType> float UE::Geometry::TMeshWindingNumberGrid< TriangleMeshType >::WindingIsoValue = 0.5f
Definition at line 57 of file MeshWindingNumberGrid.h.
Referenced by fill_spans(), and make_grid().
The documentation for this class was generated from the following file:
Runtime/GeometryCore/Public/Spatial/MeshWindingNumberGrid.h