Unreal Engine 5.6 C++ API: FAnimAttributeEntry Class Reference
FAnimAttributeEntry Class Reference
#include "SAnimAttributeView.h"
Public Member Functions
FAnimAttributeEntry ()=default
FAnimAttributeEntry (const FAnimationAttributeIdentifier &InIdentifier, const FName &InSnapshotDisplayName)
const FAnimationAttributeIdentifier & GetAnimationAttributeIdentifier () const
UE::Anim::FAttributeId GetAttributeId () const
int32 GetBoneIndex () const
FName GetBoneName () const
FName GetDisplayName () const
FName GetName () const
UScriptStruct * GetScriptStruct () const
FName GetSnapshotDisplayName () const
FName GetTypeName () const
TSharedRef< ITableRow > MakeTableRowWidget (const TSharedRef< STableViewBase > &InOwnerTable)
bool operator!= (const FAnimAttributeEntry &InOther) const
bool operator== (const FAnimAttributeEntry &InOther) const
Public Member Functions inherited from TSharedFromThis< FAnimAttributeEntry >
TSharedRef< FAnimAttributeEntry, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FAnimAttributeEntry, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Static Public Member Functions
static TSharedRef< FAnimAttributeEntry > MakeEntry (const FAnimationAttributeIdentifier &InIdentifier, const FName &InSnapshotDisplayName)
Private Attributes
FName CachedTypeName
FAnimationAttributeIdentifier Identifier
FName SnapshotDisplayName
Additional Inherited Members
Protected Member Functions inherited from TSharedFromThis< FAnimAttributeEntry >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions inherited from TSharedFromThis< FAnimAttributeEntry >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
Definition at line 30 of file SAnimAttributeView.h.
Constructor & Destructor Documentation
FAnimAttributeEntry() [1/2]
FAnimAttributeEntry::FAnimAttributeEntry () default
Referenced by operator!=(), and operator==().
FAnimAttributeEntry() [2/2]
FAnimAttributeEntry::FAnimAttributeEntry (const FAnimationAttributeIdentifier & InIdentifier, const FName & InSnapshotDisplayName)
Member Function Documentation
GetAnimationAttributeIdentifier()
const FAnimationAttributeIdentifier & FAnimAttributeEntry::GetAnimationAttributeIdentifier () const inline
Definition at line 54 of file SAnimAttributeView.h.
References Identifier.
GetAttributeId()
UE::Anim::FAttributeId FAnimAttributeEntry::GetAttributeId () const inline
Definition at line 49 of file SAnimAttributeView.h.
References GetBoneIndex(), and GetName().
GetBoneIndex()
int32 FAnimAttributeEntry::GetBoneIndex () const inline
Definition at line 42 of file SAnimAttributeView.h.
References Identifier.
Referenced by GetAttributeId().
GetBoneName()
FName FAnimAttributeEntry::GetBoneName () const inline
Definition at line 41 of file SAnimAttributeView.h.
References Identifier.
GetDisplayName()
FName FAnimAttributeEntry::GetDisplayName () const
GetName()
FName FAnimAttributeEntry::GetName () const inline
Definition at line 40 of file SAnimAttributeView.h.
References Identifier.
Referenced by GetAttributeId().
GetScriptStruct()
UScriptStruct * FAnimAttributeEntry::GetScriptStruct () const inline
Definition at line 44 of file SAnimAttributeView.h.
References Identifier.
GetSnapshotDisplayName()
FName FAnimAttributeEntry::GetSnapshotDisplayName () const inline
Definition at line 45 of file SAnimAttributeView.h.
References SnapshotDisplayName.
GetTypeName()
FName FAnimAttributeEntry::GetTypeName () const inline
Definition at line 43 of file SAnimAttributeView.h.
References CachedTypeName.
MakeEntry()
TSharedRef< FAnimAttributeEntry > FAnimAttributeEntry::MakeEntry (const FAnimationAttributeIdentifier & InIdentifier, const FName & InSnapshotDisplayName) static
MakeTableRowWidget()
TSharedRef< ITableRow > FAnimAttributeEntry::MakeTableRowWidget (const TSharedRef< STableViewBase > & InOwnerTable)
operator!=()
bool FAnimAttributeEntry::operator!= (const FAnimAttributeEntry & InOther) const inline
Definition at line 64 of file SAnimAttributeView.h.
References FAnimAttributeEntry().
operator==()
bool FAnimAttributeEntry::operator== (const FAnimAttributeEntry & InOther) const inline
Definition at line 59 of file SAnimAttributeView.h.
References FAnimAttributeEntry(), Identifier, and SnapshotDisplayName.
Field Documentation
CachedTypeName
FName FAnimAttributeEntry::CachedTypeName private
Definition at line 75 of file SAnimAttributeView.h.
Referenced by GetTypeName().
Identifier
FAnimationAttributeIdentifier FAnimAttributeEntry::Identifier private
Definition at line 71 of file SAnimAttributeView.h.
Referenced by GetAnimationAttributeIdentifier(), GetBoneIndex(), GetBoneName(), GetName(), GetScriptStruct(), and operator==().
SnapshotDisplayName
FName FAnimAttributeEntry::SnapshotDisplayName private
Definition at line 73 of file SAnimAttributeView.h.
Referenced by GetSnapshotDisplayName(), and operator==().
The documentation for this class was generated from the following file:
Editor/Persona/Public/SAnimAttributeView.h