Unreal Engine 5.6 C++ API: Metasound::FDataVertex Class Reference
Metasound::FDataVertex Class Reference
FDataVertex.
#include "MetasoundVertex.h"
Public Member Functions
FDataVertex ()=default
FDataVertex (const FVertexName &InVertexName, const FName &InDataTypeName, const FDataVertexMetadata &InMetadata, EVertexAccessType InAccessType)
FDataVertex Constructor.
virtual ~FDataVertex ()=default
Data Fields
EVertexAccessType AccessType
Access type of the vertex.
FName DataTypeName
Type name of data.
FVertexName VertexName
Name of vertex.
Detailed Description
FDataVertex.
An FDataVertex is a named vertex of a MetaSound node which can contain data.
Definition at line 92 of file MetasoundVertex.h.
Constructor & Destructor Documentation
FDataVertex() [1/2]
Metasound::FDataVertex::FDataVertex () default
Referenced by Metasound::FInputDataVertex::FInputDataVertex(), Metasound::FInputDataVertex::FInputDataVertex(), and Metasound::FInputDataVertex::FInputDataVertex().
FDataVertex() [2/2]
Metasound::FDataVertex::FDataVertex (const FVertexName & InVertexName, const FName & InDataTypeName, const FDataVertexMetadata & InMetadata, EVertexAccessType InAccessType) inline
FDataVertex Constructor.
@InVertexName - Name of vertex. @InDataTypeName - Name of data type. @InMetadata - Metadata pertaining to given vertex. @InAccessType - The access type of the vertex.
Definition at line 106 of file MetasoundVertex.h.
References AccessType, DataTypeName, Metadata, VertexName, and WITH_EDITORONLY_DATA.
~FDataVertex()
virtual Metasound::FDataVertex::~FDataVertex () virtual default
Field Documentation
AccessType
EVertexAccessType Metasound::FDataVertex::AccessType
Access type of the vertex.
Definition at line 131 of file MetasoundVertex.h.
Referenced by FDataVertex().
DataTypeName
FName Metasound::FDataVertex::DataTypeName
Type name of data.
Definition at line 123 of file MetasoundVertex.h.
Referenced by FDataVertex().
VertexName
FVertexName Metasound::FDataVertex::VertexName
Name of vertex.
Definition at line 120 of file MetasoundVertex.h.
Referenced by FDataVertex(), Metasound::MakeDestinationDataVertexKey(), and Metasound::MakeSourceDataVertexKey().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/Metasound/Source/MetasoundGraphCore/Public/MetasoundVertex.h