Unreal Engine 5.6 C++ API: FPersistentStorageManager Class Reference
FPersistentStorageManager Class Reference
#include "IPlatformFileManagedStorageWrapper.h"
Data Structures
struct FCategoryInfo
struct FRootDirInfo
Public Member Functions
FPersistentStorageManager ()
EPersistentStorageManagerFileSizeFlags AddOrUpdateFile (const FPersistentManagedFile &File, const int64 FileSize, EPersistentStorageManagerFileSizeFlags Flags=EPersistentStorageManagerFileSizeFlags::None)
TMap< FString, FPersistentStorageCategory::CategoryStat > GenerateCategoryStats () const
TOptional< FPersistentStorageCategory::CategoryStat > GetCategoryStat (const FString &InCategory) const
bool GetPersistentStorageSize (int64 &UsedSpace, int64 &RequiredSpace, int64 &OptionalSpace) const
Returns any additional required free space and optional free space.
bool GetPersistentStorageUsage (FString Path, int64 &UsedSpace, int64 &RemainingSpace, int64 &Quota, int64 *OptionalQuota=nullptr)
bool GetPersistentStorageUsageByCategory (const FString &InCategory, int64 &UsedSpace, int64 &RemainingSpace, int64 &Quota, int64 *OptionalQuota=nullptr)
TArrayView< const FString > GetRootDirectories () const
int64 GetTotalUsedSize () const
void Initialize ()
bool IsCategoryForFileFull (const FPersistentManagedFile &File) const
bool IsInitialized () const
bool RemoveFileFromManager (FPersistentManagedFile &File)
FPersistentManagedFile TryManageFile (const FString &Filename)
FPersistentManagedFile TryManageFile (FString &&Filename)
Static Public Member Functions
static FPersistentStorageManager & Get ()
Singleton access.
static bool IsReady ()
Private Member Functions
void TryManageFileInternal (FPersistentManagedFile &OutFile)
Static Private Member Functions
static FCategoryInfo InitCategories ()
Private Attributes
bool bInitialized
FCategoryInfo Categories
FRootDirInfo RootDirectories
Friends
class FManagedStorageScopeFileLock
Detailed Description
Definition at line 345 of file IPlatformFileManagedStorageWrapper.h.
Constructor & Destructor Documentation
FPersistentStorageManager()
FPersistentStorageManager::FPersistentStorageManager ()
Referenced by Get(), and Initialize().
Member Function Documentation
AddOrUpdateFile()
EPersistentStorageManagerFileSizeFlags FPersistentStorageManager::AddOrUpdateFile (const FPersistentManagedFile & File, const int64 FileSize, EPersistentStorageManagerFileSizeFlags Flags = EPersistentStorageManagerFileSizeFlags::None) inline
Definition at line 466 of file IPlatformFileManagedStorageWrapper.h.
References Categories, Flags, and None.
Referenced by FManagedStorageFileWriteHandle::~FManagedStorageFileWriteHandle(), TManagedStoragePlatformFile< BaseClass >::CopyFile(), Initialize(), TManagedStoragePlatformFile< BaseClass >::MoveFile(), TManagedStoragePlatformFile< BaseClass >::OpenWrite(), FManagedStorageFileWriteHandle::Truncate(), and FManagedStorageFileWriteHandle::Write().
GenerateCategoryStats()
TMap< FString, FPersistentStorageCategory::CategoryStat > FPersistentStorageManager::GenerateCategoryStats () const inline
Definition at line 577 of file IPlatformFileManagedStorageWrapper.h.
References TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Add(), Categories, Category, and TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Reserve().
Get()
FPersistentStorageManager & FPersistentStorageManager::Get () static
Singleton access.
References FPersistentStorageManager().
Referenced by FManagedStorageFileWriteHandle::~FManagedStorageFileWriteHandle(), TManagedStoragePlatformFile< BaseClass >::CopyFile(), TManagedStoragePlatformFile< BaseClass >::DeleteFile(), TManagedStoragePlatformFile< BaseClass >::DeleteFiles(), FManagedStorageFileWriteHandle::Flush(), Initialize(), TManagedStoragePlatformFile< BaseClass >::MoveFile(), TManagedStoragePlatformFile< BaseClass >::OpenWrite(), FManagedStorageFileWriteHandle::Truncate(), FManagedStorageFileWriteHandle::TryManageFile(), and FManagedStorageFileWriteHandle::Write().
GetCategoryStat()
TOptional< FPersistentStorageCategory::CategoryStat > FPersistentStorageManager::GetCategoryStat (const FString & InCategory) const inline
Definition at line 590 of file IPlatformFileManagedStorageWrapper.h.
References Categories, and Category.
GetPersistentStorageSize()
bool FPersistentStorageManager::GetPersistentStorageSize (int64 & UsedSpace, int64 & RequiredSpace, int64 & OptionalSpace) const inline
Returns any additional required free space and optional free space.
Parameters
RequiredSpace Required persistent storage space to run
OptionalSpace persistent storage categories marked as optional
Returns
Definition at line 551 of file IPlatformFileManagedStorageWrapper.h.
References Categories, and Category.
GetPersistentStorageUsage()
bool FPersistentStorageManager::GetPersistentStorageUsage (FString Path, int64 & UsedSpace, int64 & RemainingSpace, int64 & Quota, int64 * OptionalQuota = nullptr) inline
Parameters
Path path to check for free space
UsedSpace amount of used space
RemainingSpace amount of remaining free space
Quota total storage allocated to the related category
OptionalQuota subset of the storage which is optional i.e. will always be smaller then total Quota
Returns
returns if function succeeds
Definition at line 507 of file IPlatformFileManagedStorageWrapper.h.
References Categories, Category, FPaths::ConvertRelativePathToFull(), MoveTemp(), and Path.
GetPersistentStorageUsageByCategory()
bool FPersistentStorageManager::GetPersistentStorageUsageByCategory (const FString & InCategory, int64 & UsedSpace, int64 & RemainingSpace, int64 & Quota, int64 * OptionalQuota = nullptr) inline
Definition at line 528 of file IPlatformFileManagedStorageWrapper.h.
References Categories, Category, and Algo::FindBy().
GetRootDirectories()
TArrayView< const FString > FPersistentStorageManager::GetRootDirectories () const inline
Definition at line 606 of file IPlatformFileManagedStorageWrapper.h.
References RootDirectories.
Referenced by Initialize().
GetTotalUsedSize()
int64 FPersistentStorageManager::GetTotalUsedSize () const inline
Definition at line 487 of file IPlatformFileManagedStorageWrapper.h.
References Categories, and Category.
InitCategories()
FCategoryInfo FPersistentStorageManager::InitCategories () static private
Initialize()
void FPersistentStorageManager::Initialize () inline
Definition at line 362 of file IPlatformFileManagedStorageWrapper.h.
References FPersistentStorageManager(), AddOrUpdateFile(), ENamedThreads::AnyBackgroundThreadNormalTask, AsyncTask(), bInitialized, FFileStatData::bIsValid, Display, ensureAlways, Error, FFileStatData::FileSize, FManagedStorageScopeFileLock, Get(), IPlatformFile::GetPlatformPhysical(), GetRootDirectories(), IPlatformFile::GetStatData(), IPlatformFile::IterateDirectoryRecursively(), TEXT, ThreadSafe, TryManageFile(), UE_LOG, and Visit().
IsCategoryForFileFull()
bool FPersistentStorageManager::IsCategoryForFileFull (const FPersistentManagedFile & File) const inline
Definition at line 567 of file IPlatformFileManagedStorageWrapper.h.
References Categories.
Referenced by TManagedStoragePlatformFile< BaseClass >::OpenWrite().
IsInitialized()
bool FPersistentStorageManager::IsInitialized () const inline
Definition at line 562 of file IPlatformFileManagedStorageWrapper.h.
References bInitialized.
IsReady()
bool FPersistentStorageManager::IsReady () inline static
Definition at line 348 of file IPlatformFileManagedStorageWrapper.h.
References GConfig, and GIsCriticalError.
Referenced by FManagedStorageFileWriteHandle::IsReady(), and TManagedStoragePlatformFile< BaseClass >::IsReady().
RemoveFileFromManager()
bool FPersistentStorageManager::RemoveFileFromManager (FPersistentManagedFile & File) inline
Definition at line 477 of file IPlatformFileManagedStorageWrapper.h.
References Categories.
Referenced by TManagedStoragePlatformFile< BaseClass >::CopyFile(), TManagedStoragePlatformFile< BaseClass >::DeleteFile(), TManagedStoragePlatformFile< BaseClass >::DeleteFiles(), and TManagedStoragePlatformFile< BaseClass >::MoveFile().
TryManageFile() [1/2]
FPersistentManagedFile FPersistentStorageManager::TryManageFile (const FString & Filename) inline
Definition at line 424 of file IPlatformFileManagedStorageWrapper.h.
References FPaths::ConvertRelativePathToFull(), Filename, FPersistentManagedFile::FullFilename, and TryManageFileInternal().
Referenced by TManagedStoragePlatformFile< BaseClass >::CopyFile(), TManagedStoragePlatformFile< BaseClass >::DeleteFile(), TManagedStoragePlatformFile< BaseClass >::DeleteFiles(), Initialize(), TManagedStoragePlatformFile< BaseClass >::MoveFile(), TManagedStoragePlatformFile< BaseClass >::OpenWrite(), and FManagedStorageFileWriteHandle::TryManageFile().
TryManageFile() [2/2]
FPersistentManagedFile FPersistentStorageManager::TryManageFile (FString && Filename) inline
Definition at line 434 of file IPlatformFileManagedStorageWrapper.h.
References FPaths::ConvertRelativePathToFull(), Filename, FPersistentManagedFile::FullFilename, MoveTemp(), and TryManageFileInternal().
TryManageFileInternal()
void FPersistentStorageManager::TryManageFileInternal (FPersistentManagedFile & OutFile) inline private
Definition at line 445 of file IPlatformFileManagedStorageWrapper.h.
References Categories, Category, FPersistentManagedFile::Category, Algo::FindByPredicate(), FPersistentManagedFile::FullFilename, and RootDirectories.
Referenced by TryManageFile(), and TryManageFile().
Friends And Related Symbol Documentation
FManagedStorageScopeFileLock
friend class FManagedStorageScopeFileLock friend
Definition at line 609 of file IPlatformFileManagedStorageWrapper.h.
References FManagedStorageScopeFileLock.
Referenced by FManagedStorageScopeFileLock, and Initialize().
Field Documentation
bInitialized
bool FPersistentStorageManager::bInitialized private
Definition at line 611 of file IPlatformFileManagedStorageWrapper.h.
Referenced by Initialize(), and IsInitialized().
Categories
FCategoryInfo FPersistentStorageManager::Categories private
Definition at line 644 of file IPlatformFileManagedStorageWrapper.h.
Referenced by AddOrUpdateFile(), GenerateCategoryStats(), GetCategoryStat(), GetPersistentStorageSize(), GetPersistentStorageUsage(), GetPersistentStorageUsageByCategory(), GetTotalUsedSize(), FPersistentStorageManager::FRootDirInfo::Init(), IsCategoryForFileFull(), RemoveFileFromManager(), and TryManageFileInternal().
RootDirectories
FRootDirInfo FPersistentStorageManager::RootDirectories private
Definition at line 624 of file IPlatformFileManagedStorageWrapper.h.
Referenced by GetRootDirectories(), and TryManageFileInternal().
The documentation for this class was generated from the following file:
Runtime/Core/Public/HAL/IPlatformFileManagedStorageWrapper.h