Unreal Engine 5.6 C++ API: UE::Geometry::FIntrinsicEdgeFlipMesh Class Reference
UE::Geometry::FIntrinsicEdgeFlipMesh Class Reference
FIntrinsicEdgeFlipMesh augments the base class FSimpleIntrinsicEdgeFlipMesh with the addition of a 'normal coordinate' based correspondence with the surface mesh.
#include "IntrinsicTriangulationMesh.h"
Public Types
using FEdge = FSimpleIntrinsicEdgeFlipMesh::FEdge
using FEdgeAndCrossingIdx = IntrinsicCorrespondenceUtils::FNormalCoordinates::FEdgeAndCrossingIdx
typedef TEdgeCorrespondence< FIntrinsicEdgeFlipMesh > FEdgeCorrespondence
using FEdgeFlipInfo = FSimpleIntrinsicEdgeFlipMesh::FEdgeFlipInfo
using FSurfacePoint = IntrinsicCorrespondenceUtils::FSurfacePoint
typedef FSimpleIntrinsicEdgeFlipMesh MyBase
Public Types inherited from UE::Geometry::FSimpleIntrinsicEdgeFlipMesh
using FEdge = FDynamicMesh3::FEdge
Public Member Functions
FIntrinsicEdgeFlipMesh ()=delete
DYNAMICMESH_API FIntrinsicEdgeFlipMesh (const FDynamicMesh3 &SurfaceMesh)
FIntrinsicEdgeFlipMesh (const FIntrinsicEdgeFlipMesh &)=delete
FEdgeCorrespondence ComputeEdgeCorrespondence () const
DYNAMICMESH_API EMeshResult FlipEdge (int32 EID, FEdgeFlipInfo &EdgeFlipInfo)
Flip a single edge in the Intrinsic Mesh.
const FDynamicMesh3 * GetExtrinsicMesh () const
DYNAMICMESH_API TArray< FEdgeAndCrossingIdx > GetImplicitEdgeCrossings (const int32 SurfaceEID, const bool bReverse=false) const
Trace the specified surface (extrinsic) mesh edge across the intrinsic mesh.
const IntrinsicCorrespondenceUtils::FNormalCoordinates & GetNormalCoordinates () const
FSurfacePoint GetVertexSurfacePoint (int32 VID) const
bool IsSurfaceVertex (int VID) const
DYNAMICMESH_API TArray< FSurfacePoint > TraceEdge (int32 IntrinsicEID, double CoalesceThreshold=0., bool bReverse=false) const
DYNAMICMESH_API TArray< FSurfacePoint > TraceSurfaceEdge (int32 SurfaceEID, double CoalesceThreshold, bool bReverse=false) const
Trace the specified surface (extrinsic) mesh edge across the intrinsic mesh.
Public Member Functions inherited from UE::Geometry::FSimpleIntrinsicEdgeFlipMesh
FSimpleIntrinsicEdgeFlipMesh ()
DYNAMICMESH_API FSimpleIntrinsicEdgeFlipMesh (const FDynamicMesh3 &SrcMesh)
Constructor does ID-matching deep copy the basic mesh topology (but no attributes or groups)
FSimpleIntrinsicEdgeFlipMesh (const FSimpleIntrinsicEdgeFlipMesh &)=delete
bool AreSameOrientation (int32 EID) const
DYNAMICMESH_API void Clear ()
Discard all data.
DYNAMICMESH_API double EdgeCotanWeight (int32 EID) const
return 1/2 (cot(alpha_{ij}) + cot(beta_{ij})) where alpha_{ij} and beta_{ij} are the to interior angles opposite the specified edge, EID.
int32 EdgeCount () const
FRefCountVector::IndexEnumerable EdgeIndicesItr () const
DYNAMICMESH_API FVector2d EdgeOpposingAngles (int32 EID) const
return FVector2(alpha_{ij} , beta_{ij}) where alpha_{ij} and beta_{ij} are the two interior angles opposite the specified edge, EID.
DYNAMICMESH_API EMeshResult FlipEdge (int32 EID, FEdgeFlipInfo &EdgeFlipInfo)
Flip a single edge in the Intrinsic Mesh.
FEdge GetEdge (int32 EdgeID) const
double GetEdgeLength (int32 EID) const
DYNAMICMESH_API FIndex2i GetEdgeOpposingV (int32 EID) const
FIndex2i GetEdgeT (int32 EdgeID) const
FIndex2i GetEdgeV (int32 EdgeID) const
FIndex3i GetTriangle (int32 TriangleID) const
const FIndex3i & GetTriangleRef (int TriangleID) const
FVector3d GetTriEdgeLengths (const int32 TID) const
FIndex3i GetTriEdges (int32 TriangleID) const
double GetTriInternalAngleR (const int32 TID, const int32 IndexOf) const
FVector3d GetVertex (int32 VertexID) const
int32 GetVtxEdgeCount (int32 VID) const
bool IsBoundaryEdge (int32 EdgeID) const
bool IsBoundaryVertex (int32 VertexID) const
bool IsEdge (int32 EdgeID) const
bool IsTriangle (int32 TriangleID) const
bool IsVertex (int32 VertexID) const
int32 MaxEdgeID () const
int32 MaxTriangleID () const
int32 MaxVertexID () const
template<typename Vector3Type>
Vector3Type Permute (int32 Index, const Vector3Type &Src) const
cyclic permutation of the src vector such that the 'Index' entry in the src is the first entry in the result NB: Index must be 0, 1, or 2.
DYNAMICMESH_API void Reset (const FDynamicMesh3 &SrcMesh)
Reset the mesh to an ID-matching deep copy the basic mesh topology (but no attributes or groups)
int32 TriangleCount () const
FRefCountVector::IndexEnumerable TriangleIndicesItr () const
FSmallListSet::ValueEnumerable VtxEdgesItr (int32 VID) const
Protected Types
using FNormalCoordinates = IntrinsicCorrespondenceUtils::FNormalCoordinates
Protected Attributes
FNormalCoordinates NormalCoordinates
Protected Attributes inherited from UE::Geometry::FSimpleIntrinsicEdgeFlipMesh
const int32 AddOneModThree [3] = { 1, 2, 0 }
const int32 AddTwoModThree [3] = { 2, 0, 1 }
TDynamicVector< double > EdgeLengths
FRefCountVector EdgeRefCounts {}
TDynamicVector< FEdge > Edges
TDynamicVector< FVector3d > InternalAngles
TDynamicVector< FIndex3i > TriangleEdges
FRefCountVector TriangleRefCounts {}
TDynamicVector< FIndex3i > Triangles
FSmallListSet VertexEdgeLists
FRefCountVector VertexRefCounts {}
TDynamicVector< FVector3d > Vertices {}
Additional Inherited Members
Static Public Attributes inherited from UE::Geometry::FSimpleIntrinsicEdgeFlipMesh
static constexpr int InvalidID = IndexConstants::InvalidID
InvalidID indicates that a vertex/edge/triangle ID is invalid.
Protected Member Functions inherited from UE::Geometry::FSimpleIntrinsicEdgeFlipMesh
DYNAMICMESH_API FVector3d ComputeTriInternalAnglesR (const int32 TID) const
computes the angles based on the edge lengths, so must have valid EdgeLengths for this tri before calling.
DYNAMICMESH_API EMeshResult FlipEdgeTopology (int32 eab, FEdgeFlipInfo &FlipInfo)
update the mesh topology (e.g.
FVector3d GetEdgeLengthTriple (const FIndex3i &EIDs) const
DYNAMICMESH_API double GetOpposingVerticesDistance (int32 EID) const
DYNAMICMESH_API FIndex2i GetOrientedEdgeV (int32 EID, int32 TID) const
DYNAMICMESH_API int32 ReplaceEdgeTriangle (int32 eID, int32 tOld, int32 tNew)
replace tOld with tNew in an existing edge
int32 ReplaceTriangleEdge (int32 tID, int32 eOld, int32 eNew)
replace eOld with eNew in and existing triangle
void SetEdgeTrianglesInternal (int32 EdgeID, int32 t0, int32 t1)
update the existing edge to reference triangles t0 and t1
void SetEdgeVerticesInternal (int32 EdgeID, int32 a, int32 b)
update the existing edge to reference vertices 'a' and 'b'.
Detailed Description
FIntrinsicEdgeFlipMesh augments the base class FSimpleIntrinsicEdgeFlipMesh with the addition of a 'normal coordinate' based correspondence with the surface mesh.
This class supports both the trace of intrinsic mesh edges across the surface mesh, and the trace of surface mesh edges across the intrinsic mesh.
Note, because only edge flips are supported (no edge split or triangle pokes), the vertex set of the intrinsic mesh and the surface (i.e. extrinsic) mesh will be the same.
The expected use
// generate the implicit mesh from a surface mesh
FIntrinsicEdgeFlipMesh  ImplicitMesh(DynamicMesh);
    .. do some edge flips .. perhaps FlipToDelaunay( ImplicitMesh, ..)
 // if only a small percentage of the intrinsic edges are to be traced, this can be done directly as
 auto TracedIntrinsicEdge  =  ImplicitMesh.TraceEdge(IntrinsicEdgeID);
 // alternately if a large number of edges will be traced, a correspondence will be more efficient.
 // create a correspondence that allows the edges of the implicit mesh to be traced on the surface mesh
 FIntrinsicEdgeFlipMesh::FEdgeCorrespondence  Correspondence = ImplicitMesh.ComputeEdgeCorrespondence();
 for (.. doing multiple traces..  )
 {
     // trace desired edge across the surface mesh
     int32 IntrinsicEdgeID =
     auto TracedIntrinsicEdge  =  Correspondence.TraceEdge(IntrinsicEdgeID);
 }
NB: The lifetime of this structure should not exceed that of the original FDynamicMesh as this class holds a pointer to that mesh to reference locations on its surface. Also, this class isn't currently expected to work with surface meshes that have bow-ties.
Note: This assumes but does not check that the FDynamicMesh3 "Surface Mesh" has consistent orientation of all triangles.
Definition at line 643 of file IntrinsicTriangulationMesh.h.
Member Typedef Documentation
FEdge
using UE::Geometry::FIntrinsicEdgeFlipMesh::FEdge = FSimpleIntrinsicEdgeFlipMesh::FEdge
Definition at line 647 of file IntrinsicTriangulationMesh.h.
FEdgeAndCrossingIdx
using UE::Geometry::FIntrinsicEdgeFlipMesh::FEdgeAndCrossingIdx = IntrinsicCorrespondenceUtils::FNormalCoordinates::FEdgeAndCrossingIdx
Definition at line 650 of file IntrinsicTriangulationMesh.h.
FEdgeCorrespondence
typedef TEdgeCorrespondence< FIntrinsicEdgeFlipMesh > UE::Geometry::FIntrinsicEdgeFlipMesh::FEdgeCorrespondence
Definition at line 686 of file IntrinsicTriangulationMesh.h.
FEdgeFlipInfo
using UE::Geometry::FIntrinsicEdgeFlipMesh::FEdgeFlipInfo = FSimpleIntrinsicEdgeFlipMesh::FEdgeFlipInfo
Definition at line 648 of file IntrinsicTriangulationMesh.h.
FNormalCoordinates
using UE::Geometry::FIntrinsicEdgeFlipMesh::FNormalCoordinates = IntrinsicCorrespondenceUtils::FNormalCoordinates protected
Definition at line 740 of file IntrinsicTriangulationMesh.h.
FSurfacePoint
using UE::Geometry::FIntrinsicEdgeFlipMesh::FSurfacePoint = IntrinsicCorrespondenceUtils::FSurfacePoint
Definition at line 649 of file IntrinsicTriangulationMesh.h.
MyBase
typedef FSimpleIntrinsicEdgeFlipMesh UE::Geometry::FIntrinsicEdgeFlipMesh::MyBase
Definition at line 646 of file IntrinsicTriangulationMesh.h.
Constructor & Destructor Documentation
FIntrinsicEdgeFlipMesh() [1/3]
DYNAMICMESH_API UE::Geometry::FIntrinsicEdgeFlipMesh::FIntrinsicEdgeFlipMesh (const FDynamicMesh3 & SurfaceMesh)
References UE_API.
Referenced by FIntrinsicEdgeFlipMesh().
FIntrinsicEdgeFlipMesh() [2/3]
UE::Geometry::FIntrinsicEdgeFlipMesh::FIntrinsicEdgeFlipMesh () delete
FIntrinsicEdgeFlipMesh() [3/3]
UE::Geometry::FIntrinsicEdgeFlipMesh::FIntrinsicEdgeFlipMesh (const FIntrinsicEdgeFlipMesh &) delete
References FIntrinsicEdgeFlipMesh().
Member Function Documentation
ComputeEdgeCorrespondence()
FEdgeCorrespondence UE::Geometry::FIntrinsicEdgeFlipMesh::ComputeEdgeCorrespondence () const inline
Definition at line 688 of file IntrinsicTriangulationMesh.h.
FlipEdge()
DYNAMICMESH_API EMeshResult UE::Geometry::FIntrinsicEdgeFlipMesh::FlipEdge (int32 EID, FEdgeFlipInfo & EdgeFlipInfo)
Flip a single edge in the Intrinsic Mesh.
Parameters
EdgeFlipInfo [out] populated on return.
Returns
a success or failure info.
References UE_API.
GetExtrinsicMesh()
const FDynamicMesh3 * UE::Geometry::FIntrinsicEdgeFlipMesh::GetExtrinsicMesh () const inline
Returns
pointer the reference mesh, note the FIntrinsicTriangulation does not manage the lifetime of this mesh
Definition at line 658 of file IntrinsicTriangulationMesh.h.
References NormalCoordinates.
GetImplicitEdgeCrossings()
DYNAMICMESH_API TArray< FEdgeAndCrossingIdx > UE::Geometry::FIntrinsicEdgeFlipMesh::GetImplicitEdgeCrossings (const int32 SurfaceEID, const bool bReverse = false) const
Trace the specified surface (extrinsic) mesh edge across the intrinsic mesh.
By default this traces from vertex EdgeV.A to vertex EdgeV.B where EdgeV = SurfaceMesh.GetEdgeV(SurfaceEID).
Parameters
SurfaceEID - the surface edge to be traced
bReverse - reverses the direction of the trace giving EdgeV.B -> EdgeV.A
Returns
array of intrinsic edges crossed between the specified vertices. This can be used to compute the actual MeshPoints on the surface if desired.
References UE_API.
GetNormalCoordinates()
const IntrinsicCorrespondenceUtils::FNormalCoordinates & UE::Geometry::FIntrinsicEdgeFlipMesh::GetNormalCoordinates () const inline
Returns
NormalCoordinate data structure that counts the number of regular surface (extrinsic) mesh edge-crossings for each intrinsic mesh edge.
Definition at line 696 of file IntrinsicTriangulationMesh.h.
References NormalCoordinates.
GetVertexSurfacePoint()
FSurfacePoint UE::Geometry::FIntrinsicEdgeFlipMesh::GetVertexSurfacePoint (int32 VID) const inline
Returns
the position of the intrinsic vertex relative to the underlying surface mesh
Definition at line 732 of file IntrinsicTriangulationMesh.h.
IsSurfaceVertex()
bool UE::Geometry::FIntrinsicEdgeFlipMesh::IsSurfaceVertex (int VID) const inline
Returns
true if the intrinsic vertex corresponds to a surface vertex.
Definition at line 724 of file IntrinsicTriangulationMesh.h.
References UE::Geometry::FSimpleIntrinsicEdgeFlipMesh::IsVertex().
TraceEdge()
DYNAMICMESH_API TArray< FSurfacePoint > UE::Geometry::FIntrinsicEdgeFlipMesh::TraceEdge (int32 IntrinsicEID, double CoalesceThreshold = 0., bool bReverse = false) const
Returns
Array of FSurfacePoints relative to the surface mesh that represent the specified intrinsic mesh edge. This is directed relative to traversal of the first adjacent triangle (GetEdgeT().[0]), unless bReverse is true
Parameters
CoalesceThreshold - in barycentric units [0,1], edge crossings with in this threshold are snapped to the nearest vertex. and any resulting repetitions of vertex surface points are replaced with a single vertex surface point.
bReverse - if true, trace edge direction is reversed
Note: when tracing few edges, this method is preferred to using the FEdgeCorrespondence based tracing (see FEdgeCorrespondence below).
But when tracing a large percentage of the mesh edges the FEdgeCorrespondence will be faster as it reuses intermediate results.
References UE_API.
TraceSurfaceEdge()
DYNAMICMESH_API TArray< FSurfacePoint > UE::Geometry::FIntrinsicEdgeFlipMesh::TraceSurfaceEdge (int32 SurfaceEID, double CoalesceThreshold, bool bReverse = false) const
Trace the specified surface (extrinsic) mesh edge across the intrinsic mesh.
By default this traces from vertex EdgeV.A to vertex EdgeV.B where EdgeV = SurfaceMesh.GetEdgeV(SurfaceEID).
Parameters
SurfaceEID - the surface edge to be traced
bReverse - reverses the direction of the trace giving EdgeV.B -> EdgeV.A
Returns
array of surface points defined relative to the intrinsic mesh. In particular, the array will be a vertex followed by a sequence of (intrinsic) edge crossings.
References UE_API.
Field Documentation
NormalCoordinates
FNormalCoordinates UE::Geometry::FIntrinsicEdgeFlipMesh::NormalCoordinates protected
Definition at line 741 of file IntrinsicTriangulationMesh.h.
Referenced by GetExtrinsicMesh(), and GetNormalCoordinates().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/GeometryProcessing/Source/DynamicMesh/Public/Operations/IntrinsicTriangulationMesh.h