Unreal Engine 5.6 C++ API: FABTest Class Reference
FABTest Class Reference
#include "ABTesting.h"
Data Structures
struct FSample
Public Member Functions
FABTest ()
bool GetDoFirstScopeTest () const
bool IsActive ()
void ReportScopeTime (double ScopeTime)
const TCHAR * TickAndGetCommand ()
Static Public Member Functions
static void ABTestCmdFunc (const TArray< FString > &Args)
static FABTest & Get ()
static bool StaticIsActive ()
Private Member Functions
void FrameLogTick (double Delta)
void Start (FString *InABTestCmds, bool bScopeTest)
void StartFrameLog ()
void Stop ()
const TCHAR * SwitchTest (int32 Index)
Private Attributes
FString ABTestCmds [2]
int32 ABTestNumSamples
bool bABScopeTestActive
bool bABTestActive
bool bFrameLog
int32 CoolDown
uint32 Counts [2]
int32 CurrentTest
int32 HistoryNum
uint64 LastGCFrame
int32 MinFramesPerTrial
int32 NumResamples
int32 RemainingCoolDown
int32 RemainingPrint
int32 RemainingTrial
int32 ReportNum
TArray< uint32 > ResampleAccumulators
TArray< uint32 > ResampleCount
TArray< FSample > Samples
uint32 Spikes
FRandomStream Stream
uint32 TotalFrames
uint32 Totals [2]
double TotalScopeTimeInFrame
double TotalTime
Detailed Description
Definition at line 27 of file ABTesting.h.
Constructor & Destructor Documentation
FABTest()
FABTest::FABTest ()
Referenced by Get().
Member Function Documentation
ABTestCmdFunc()
void FABTest::ABTestCmdFunc (const TArray< FString > & Args) static
FrameLogTick()
void FABTest::FrameLogTick (double Delta) private
Get()
FABTest & FABTest::Get () static
References FABTest().
Referenced by FScopedABTimer::~FScopedABTimer(), and StaticIsActive().
GetDoFirstScopeTest()
bool FABTest::GetDoFirstScopeTest () const inline
Definition at line 46 of file ABTesting.h.
References CurrentTest.
IsActive()
bool FABTest::IsActive () inline
Definition at line 36 of file ABTesting.h.
References bABTestActive.
ReportScopeTime()
void FABTest::ReportScopeTime (double ScopeTime) inline
Definition at line 41 of file ABTesting.h.
References TotalScopeTimeInFrame.
Referenced by FScopedABTimer::~FScopedABTimer().
Start()
void FABTest::Start (FString * InABTestCmds, bool bScopeTest) private
StartFrameLog()
void FABTest::StartFrameLog () private
StaticIsActive()
bool FABTest::StaticIsActive () inline static
Definition at line 55 of file ABTesting.h.
References bABTestActive, and Get().
Stop()
void FABTest::Stop () private
SwitchTest()
const TCHAR * FABTest::SwitchTest (int32 Index) private
TickAndGetCommand()
const TCHAR * FABTest::TickAndGetCommand ()
Field Documentation
ABTestCmds
FString FABTest::ABTestCmds[2] private
Definition at line 76 of file ABTesting.h.
ABTestNumSamples
int32 FABTest::ABTestNumSamples private
Definition at line 77 of file ABTesting.h.
bABScopeTestActive
bool FABTest::bABScopeTestActive private
Definition at line 74 of file ABTesting.h.
bABTestActive
bool FABTest::bABTestActive private
Definition at line 73 of file ABTesting.h.
Referenced by IsActive(), and StaticIsActive().
bFrameLog
bool FABTest::bFrameLog private
Definition at line 75 of file ABTesting.h.
CoolDown
int32 FABTest::CoolDown private
Definition at line 85 of file ABTesting.h.
Counts
uint32 FABTest::Counts[2] private
Definition at line 100 of file ABTesting.h.
CurrentTest
int32 FABTest::CurrentTest private
Definition at line 79 of file ABTesting.h.
Referenced by GetDoFirstScopeTest().
HistoryNum
int32 FABTest::HistoryNum private
Definition at line 83 of file ABTesting.h.
LastGCFrame
uint64 FABTest::LastGCFrame private
Definition at line 107 of file ABTesting.h.
MinFramesPerTrial
int32 FABTest::MinFramesPerTrial private
Definition at line 86 of file ABTesting.h.
NumResamples
int32 FABTest::NumResamples private
Definition at line 87 of file ABTesting.h.
RemainingCoolDown
int32 FABTest::RemainingCoolDown private
Definition at line 78 of file ABTesting.h.
RemainingPrint
int32 FABTest::RemainingPrint private
Definition at line 81 of file ABTesting.h.
RemainingTrial
int32 FABTest::RemainingTrial private
Definition at line 80 of file ABTesting.h.
ReportNum
int32 FABTest::ReportNum private
Definition at line 84 of file ABTesting.h.
ResampleAccumulators
TArray<uint32> FABTest::ResampleAccumulators private
Definition at line 97 of file ABTesting.h.
ResampleCount
TArray<uint32> FABTest::ResampleCount private
Definition at line 98 of file ABTesting.h.
Samples
TArray<FSample> FABTest::Samples private
Definition at line 96 of file ABTesting.h.
Spikes
uint32 FABTest::Spikes private
Definition at line 104 of file ABTesting.h.
Stream
FRandomStream FABTest::Stream private
Definition at line 72 of file ABTesting.h.
TotalFrames
uint32 FABTest::TotalFrames private
Definition at line 103 of file ABTesting.h.
Totals
uint32 FABTest::Totals[2] private
Definition at line 99 of file ABTesting.h.
TotalScopeTimeInFrame
double FABTest::TotalScopeTimeInFrame private
Definition at line 106 of file ABTesting.h.
Referenced by ReportScopeTime().
TotalTime
double FABTest::TotalTime private
Definition at line 102 of file ABTesting.h.
The documentation for this class was generated from the following file:
Runtime/Core/Public/ProfilingDebugging/ABTesting.h