Unreal Engine 5.6 C++ API: TStructOnScope< T > Class Template Reference
TStructOnScope< T > Class Template Reference final
Typed FStructOnScope that exposes type-safe access to the wrapped struct.
#include "StructOnScope.h"
Public Member Functions
TStructOnScope ()=default
TStructOnScope (TStructOnScope &&InOther)=default
template<typename U, typename = typename TEnableIf<TIsDerivedFrom<typename TRemoveReference<U>::Type, T>::IsDerived, void>::Type>
TStructOnScope (U &&InStruct)
virtual ~TStructOnScope ()=default
template<typename U>
U * Cast ()
template<typename U>
const U * Cast () const
template<typename U>
U * CastChecked ()
template<typename U>
const U * CastChecked () const
T * Get () const
template<typename U, typename = typename TEnableIf<TIsDerivedFrom<typename TRemoveReference<U>::Type, T>::IsDerived, void>::Type, typename... TArgs>
void InitializeAs (TArgs &&... InArgs)
Initialize the TStructOnScope as a struct of type U which needs to derive from T @params InArgs The arguments to pass to the constructor of type U.
bool InitializeFrom (const FStructOnScope &InOther)
Initialize the TStructOnScope from a FStructOnScope containing data that derives from T @params InOther The FStructOnScope to initialize from.
bool InitializeFrom (FStructOnScope &&InOther)
Initialize the TStructOnScope from a FStructOnScope containing data that derives from T @params InOther The FStructOnScope to initialize from.
void InitializeFromChecked (const FStructOnScope &InOther)
Initialize the TStructOnScope from a FStructOnScope containing data that derives from T @params InOther The FStructOnScope to initialize from (will assert if it contains an invalid type to store for T)
void InitializeFromChecked (FStructOnScope &&InOther)
Initialize the TStructOnScope from a FStructOnScope containing data that derives from T @params InOther The FStructOnScope to initialize from (will assert if it contains an invalid type to store for T)
operator bool () const
T * operator-> () const
TStructOnScope & operator= (TStructOnScope &&InOther)=default
template<typename U, typename = typename TEnableIf<TIsDerivedFrom<typename TRemoveReference<U>::Type, T>::IsDerived, void>::Type>
TStructOnScope & operator= (U &&InStruct)
void Serialize (FArchive &Ar)
Public Member Functions inherited from FStructOnScope
FStructOnScope ()
FStructOnScope (const FStructOnScope &)=delete
FStructOnScope (const UStruct *InScriptStruct)
FStructOnScope (const UStruct *InScriptStruct, uint8 *InData)
FStructOnScope (FStructOnScope &&InOther)
virtual ~FStructOnScope ()
void AddReferencedObjects (FReferenceCollector &Collector)
virtual const UStruct * GetStruct () const
TWeakObjectPtr< const UStruct > & GetStructPtr ()
void Initialize (TWeakObjectPtr< const UStruct > InScriptStruct)
Re-initializes the scope with a specified UStruct.
virtual bool IsValid () const
FStructOnScope & operator= (const FStructOnScope &)=delete
FStructOnScope & operator= (FStructOnScope &&InOther)
virtual void Reset ()
Private Member Functions
virtual void Destroy ()
virtual UPackage * GetPackage () const
virtual uint8 * GetStructMemory ()
virtual const uint8 * GetStructMemory () const
virtual void Initialize ()
void Initialize (TWeakObjectPtr< const UStruct > InScriptStruct)
Re-initializes the scope with a specified UStruct.
virtual bool OwnsStructMemory () const
virtual void SetPackage (UPackage *InPackage)
Additional Inherited Members
Protected Attributes inherited from FStructOnScope
bool OwnsMemory
Whether the struct memory is owned by this instance.
TWeakObjectPtr< UPackage > Package
uint8 * SampleStructMemory
TWeakObjectPtr< const UStruct > ScriptStruct
Detailed Description
template<typename T>
class TStructOnScope< T >
Typed FStructOnScope that exposes type-safe access to the wrapped struct.
Definition at line 141 of file StructOnScope.h.
Constructor & Destructor Documentation
TStructOnScope() [1/3]
template<typename T> TStructOnScope< T >::TStructOnScope () default
Referenced by TStructOnScope(), Cast(), CastChecked(), operator=(), and operator=().
~TStructOnScope()
template<typename T> virtual TStructOnScope< T >::~TStructOnScope () virtual default
TStructOnScope() [2/3]
template<typename T> TStructOnScope< T >::TStructOnScope (TStructOnScope< T > && InOther) default
References TStructOnScope().
TStructOnScope() [3/3]
template<typename T> template<typename U, typename = typename TEnableIf<TIsDerivedFrom<typename TRemoveReference<U>::Type, T>::IsDerived, void>::Type> TStructOnScope< T >::TStructOnScope (U && InStruct) inline explicit
Definition at line 151 of file StructOnScope.h.
References FStructOnScope::FStructOnScope(), Cast(), Get(), and FStructOnScope::ScriptStruct.
Member Function Documentation
Cast() [1/2]
template<typename T> template<typename U> U * TStructOnScope< T >::Cast () inline
Definition at line 281 of file StructOnScope.h.
References TBaseStructureBase< T, bHasStaticStruct >::Get(), FStructOnScope::GetStruct(), and FStructOnScope::SampleStructMemory.
Referenced by TStructOnScope(), Cast(), CastChecked(), InitializeFrom(), InitializeFrom(), operator=(), and Serialize().
Cast() [2/2]
template<typename T> template<typename U> const U * TStructOnScope< T >::Cast () const inline
Definition at line 291 of file StructOnScope.h.
References TStructOnScope(), and Cast().
CastChecked() [1/2]
template<typename T> template<typename U> U * TStructOnScope< T >::CastChecked () inline
Definition at line 297 of file StructOnScope.h.
References Cast(), Fatal, TBaseStructureBase< T, bHasStaticStruct >::Get(), FStructOnScope::IsValid(), TEXT, and UE_LOG.
Referenced by CastChecked().
CastChecked() [2/2]
template<typename T> template<typename U> const U * TStructOnScope< T >::CastChecked () const inline
Definition at line 315 of file StructOnScope.h.
References TStructOnScope(), and CastChecked().
Destroy()
template<typename T> virtual void FStructOnScope::Destroy () inline private virtual
Reimplemented from FStructOnScope.
Definition at line 90 of file StructOnScope.h.
Referenced by InitializeAs(), InitializeFrom(), and InitializeFrom().
Get()
template<typename T> T * TStructOnScope< T >::Get () const inline
Definition at line 265 of file StructOnScope.h.
References FStructOnScope::SampleStructMemory.
Referenced by TStructOnScope(), operator->(), and operator=().
GetPackage()
template<typename T> virtual UPackage * FStructOnScope::GetPackage () const private virtual
Reimplemented from FStructOnScope.
GetStructMemory() [1/2]
template<typename T> virtual uint8 * FStructOnScope::GetStructMemory () inline private virtual
Reimplemented from FStructOnScope.
Definition at line 62 of file StructOnScope.h.
GetStructMemory() [2/2]
template<typename T> virtual const uint8 * FStructOnScope::GetStructMemory () const inline private virtual
Reimplemented from FStructOnScope.
Definition at line 67 of file StructOnScope.h.
Initialize() [1/2]
template<typename T> virtual void FStructOnScope::Initialize () inline private virtual
Reimplemented from FStructOnScope.
Definition at line 21 of file StructOnScope.h.
Referenced by InitializeFrom(), operator=(), and Serialize().
Initialize() [2/2]
template<typename T> void FStructOnScope::Initialize (TWeakObjectPtr< const UStruct > InScriptStruct) inline private
Re-initializes the scope with a specified UStruct.
Definition at line 125 of file StructOnScope.h.
InitializeAs()
template<typename T> template<typename U, typename = typename TEnableIf<TIsDerivedFrom<typename TRemoveReference<U>::Type, T>::IsDerived, void>::Type, typename... TArgs> void TStructOnScope< T >::InitializeAs (TArgs &&... InArgs) inline
Initialize the TStructOnScope as a struct of type U which needs to derive from T @params InArgs The arguments to pass to the constructor of type U.
Definition at line 178 of file StructOnScope.h.
References Destroy(), Forward(), TBaseStructureBase< T, bHasStaticStruct >::Get(), FStructOnScope::OwnsMemory, FStructOnScope::SampleStructMemory, and FStructOnScope::ScriptStruct.
InitializeFrom() [1/2]
template<typename T> bool TStructOnScope< T >::InitializeFrom (const FStructOnScope & InOther) inline
Initialize the TStructOnScope from a FStructOnScope containing data that derives from T @params InOther The FStructOnScope to initialize from.
Returns
True if the conversion was successful, false otherwise
Definition at line 195 of file StructOnScope.h.
References FStructOnScope::FStructOnScope(), Cast(), Destroy(), TBaseStructureBase< T, bHasStaticStruct >::Get(), FStructOnScope::GetStruct(), FStructOnScope::GetStructMemory(), Initialize(), and FStructOnScope::SampleStructMemory.
Referenced by InitializeFromChecked(), and InitializeFromChecked().
InitializeFrom() [2/2]
template<typename T> bool TStructOnScope< T >::InitializeFrom (FStructOnScope && InOther) inline
Initialize the TStructOnScope from a FStructOnScope containing data that derives from T @params InOther The FStructOnScope to initialize from.
Returns
True if the conversion was successful, false otherwise
Definition at line 219 of file StructOnScope.h.
References FStructOnScope::FStructOnScope(), Cast(), Destroy(), TBaseStructureBase< T, bHasStaticStruct >::Get(), and MoveTemp().
InitializeFromChecked() [1/2]
template<typename T> void TStructOnScope< T >::InitializeFromChecked (const FStructOnScope & InOther) inline
Initialize the TStructOnScope from a FStructOnScope containing data that derives from T @params InOther The FStructOnScope to initialize from (will assert if it contains an invalid type to store for T)
Definition at line 245 of file StructOnScope.h.
References FStructOnScope::FStructOnScope(), Fatal, TBaseStructureBase< T, bHasStaticStruct >::Get(), UObjectBaseUtility::GetName(), FStructOnScope::GetStruct(), InitializeFrom(), TEXT, and UE_LOG.
InitializeFromChecked() [2/2]
template<typename T> void TStructOnScope< T >::InitializeFromChecked (FStructOnScope && InOther) inline
Initialize the TStructOnScope from a FStructOnScope containing data that derives from T @params InOther The FStructOnScope to initialize from (will assert if it contains an invalid type to store for T)
Definition at line 257 of file StructOnScope.h.
References FStructOnScope::FStructOnScope(), Fatal, TBaseStructureBase< T, bHasStaticStruct >::Get(), InitializeFrom(), MoveTemp(), TEXT, and UE_LOG.
operator bool()
template<typename T> TStructOnScope< T >::operator bool () const inline explicit
Definition at line 275 of file StructOnScope.h.
References FStructOnScope::IsValid().
operator->()
template<typename T> T * TStructOnScope< T >::operator-> () const inline
Definition at line 270 of file StructOnScope.h.
References Get().
operator=() [1/2]
template<typename T> TStructOnScope & TStructOnScope< T >::operator= (TStructOnScope< T > && InOther) default
References TStructOnScope().
operator=() [2/2]
template<typename T> template<typename U, typename = typename TEnableIf<TIsDerivedFrom<typename TRemoveReference<U>::Type, T>::IsDerived, void>::Type> TStructOnScope & TStructOnScope< T >::operator= (U && InStruct) inline
Definition at line 161 of file StructOnScope.h.
References TStructOnScope(), Cast(), Get(), Initialize(), FStructOnScope::SampleStructMemory, and FStructOnScope::ScriptStruct.
OwnsStructMemory()
template<typename T> virtual bool FStructOnScope::OwnsStructMemory () const inline private virtual
Reimplemented from FStructOnScope.
Definition at line 57 of file StructOnScope.h.
Serialize()
template<typename T> void TStructOnScope< T >::Serialize (FArchive & Ar) inline
Definition at line 320 of file StructOnScope.h.
References Ar, Cast(), TBaseStructureBase< T, bHasStaticStruct >::Get(), Initialize(), UStruct::IsChildOf(), FStructOnScope::SampleStructMemory, FStructOnScope::ScriptStruct, and UScriptStruct::SerializeItem().
SetPackage()
template<typename T> virtual void FStructOnScope::SetPackage (UPackage * InPackage) private virtual
Reimplemented from FStructOnScope.
The documentation for this class was generated from the following file:
Runtime/CoreUObject/Public/UObject/StructOnScope.h