Unreal Engine 5.6 C++ API: FGPUTextureTransferModule Class Reference
FGPUTextureTransferModule Class Reference
#include "GPUTextureTransferModule.h"
Public Member Functions
UE::GPUTextureTransfer::TextureTransferPtr GetTextureTransfer ()
Get a texture transfer object that acts as a layer above the DVP library.
void Initialize ()
Load the DVP DLL and intialize the API.Note: This is a blocking call and could take upwards of 2s.
bool IsEnabled () const
Returns whether GPUDirect is enabled.
bool IsInitialized () const
Returns whether the DVP library was loaded and initialized.
virtual void ShutdownModule () override
Called before the module is unloaded, right before the module object is destroyed.
virtual void StartupModule () override
Called right after the module DLL has been loaded and the module object has been created Load dependent modules here, and they will be guaranteed to be available during ShutdownModule.
UE_DEPRECATED (5.6, "Use IsInitialized() and IsEnabled() instead.") static bool IsAvailable()
Public Member Functions inherited from IModuleInterface
virtual ~IModuleInterface ()
Note: Even though this is an interface class we need a virtual destructor here because modules are deleted via a pointer to this interface.
virtual bool IsGameModule () const
Returns true if this module hosts gameplay code.
virtual void PostLoadCallback ()
Called after the module has been reloaded.
virtual void PreUnloadCallback ()
Called before the module has been unloaded.
virtual bool SupportsAutomaticShutdown ()
Override this to set whether your module would like cleanup on application shutdown.
virtual bool SupportsDynamicReloading ()
Override this to set whether your module is allowed to be unloaded on the fly.
Static Public Member Functions
static FGPUTextureTransferModule & Get ()
Private Member Functions
void InitializeTextureTransfer ()
Initialize the DVP library and creates the ITextureTransfer objects.
bool LoadGPUDirectBinary ()
Load the DVP dll.
void OnEnableGPUDirectCVarChange (class IConsoleVariable *ConsoleVariable)
Initializes the DVP library when MediaIO.EnableGPUDirect is set to 1.
void UninitializeTextureTransfer ()
Clean up and uninitializes the DVP library.
Private Attributes
std::atomic< bool > bInitialized = false
Tracks whether the dvp library and texture transfer objects were successfully created.
FGPUDriverInfo CachedDriverInfo
Cached information about the GPU Driver.
void * TextureTransferHandle = nullptr
DVP DLL Handle.
TArray< UE::GPUTextureTransfer::TextureTransferPtr > TransferObjects
Texture transfer objects.
Static Private Attributes
static constexpr uint8 RHI_MAX = static_cast<uint8>(UE::GPUTextureTransfer::ERHI::RHI_MAX)
Max number of RHIs that GPUTextureTransfer supports.
Detailed Description
Definition at line 20 of file GPUTextureTransferModule.h.
Member Function Documentation
Get()
FGPUTextureTransferModule & FGPUTextureTransferModule::Get () static
GetTextureTransfer()
UE::GPUTextureTransfer::TextureTransferPtr FGPUTextureTransferModule::GetTextureTransfer ()
Get a texture transfer object that acts as a layer above the DVP library.
References GetTextureTransfer().
Referenced by GetTextureTransfer().
Initialize()
void FGPUTextureTransferModule::Initialize ()
Load the DVP DLL and intialize the API.Note: This is a blocking call and could take upwards of 2s.
References Initialize().
Referenced by Initialize().
InitializeTextureTransfer()
void FGPUTextureTransferModule::InitializeTextureTransfer () private
Initialize the DVP library and creates the ITextureTransfer objects.
References InitializeTextureTransfer().
Referenced by InitializeTextureTransfer().
IsEnabled()
bool FGPUTextureTransferModule::IsEnabled () const
Returns whether GPUDirect is enabled.
This reflects the value of MediaIO.EnableGPUDirect. You should check IsAvailable to know if the library is initialized.
References IsEnabled().
Referenced by IsEnabled().
IsInitialized()
bool FGPUTextureTransferModule::IsInitialized () const
Returns whether the DVP library was loaded and initialized.
If this returns false, GetTextureTransfer will trigger the library to initialize.
References IsInitialized().
Referenced by IsInitialized().
LoadGPUDirectBinary()
bool FGPUTextureTransferModule::LoadGPUDirectBinary () private
Load the DVP dll.
References LoadGPUDirectBinary().
Referenced by LoadGPUDirectBinary().
OnEnableGPUDirectCVarChange()
void FGPUTextureTransferModule::OnEnableGPUDirectCVarChange (class IConsoleVariable * ConsoleVariable) private
Initializes the DVP library when MediaIO.EnableGPUDirect is set to 1.
References OnEnableGPUDirectCVarChange().
Referenced by OnEnableGPUDirectCVarChange().
ShutdownModule()
virtual void FGPUTextureTransferModule::ShutdownModule () override virtual
Called before the module is unloaded, right before the module object is destroyed.
During normal shutdown, this is called in reverse order that modules finish StartupModule(). This means that, as long as a module references dependent modules in it's StartupModule(), it can safely reference those dependencies in ShutdownModule() as well.
Reimplemented from IModuleInterface.
References ShutdownModule().
Referenced by ShutdownModule().
StartupModule()
virtual void FGPUTextureTransferModule::StartupModule () override virtual
Called right after the module DLL has been loaded and the module object has been created Load dependent modules here, and they will be guaranteed to be available during ShutdownModule.
ie:
FModuleManager::Get().LoadModuleChecked(TEXT("HTTP"));
Reimplemented from IModuleInterface.
References StartupModule().
Referenced by StartupModule().
UE_DEPRECATED()
FGPUTextureTransferModule::UE_DEPRECATED (5. 6, "Use IsInitialized() and IsEnabled() instead.")
UninitializeTextureTransfer()
void FGPUTextureTransferModule::UninitializeTextureTransfer () private
Clean up and uninitializes the DVP library.
References UninitializeTextureTransfer().
Referenced by UninitializeTextureTransfer().
Field Documentation
bInitialized
std::atomic<bool> FGPUTextureTransferModule::bInitialized = false private
Tracks whether the dvp library and texture transfer objects were successfully created.
Definition at line 66 of file GPUTextureTransferModule.h.
CachedDriverInfo
FGPUDriverInfo FGPUTextureTransferModule::CachedDriverInfo private
Cached information about the GPU Driver.
Definition at line 72 of file GPUTextureTransferModule.h.
RHI_MAX
uint8 FGPUTextureTransferModule::RHI_MAX = static_cast<uint8>(UE::GPUTextureTransfer::ERHI::RHI_MAX) static constexpr private
Max number of RHIs that GPUTextureTransfer supports.
Definition at line 60 of file GPUTextureTransferModule.h.
TextureTransferHandle
void* FGPUTextureTransferModule::TextureTransferHandle = nullptr private
DVP DLL Handle.
Definition at line 63 of file GPUTextureTransferModule.h.
TransferObjects
TArray<UE::GPUTextureTransfer::TextureTransferPtr> FGPUTextureTransferModule::TransferObjects private
Texture transfer objects.
Definition at line 69 of file GPUTextureTransferModule.h.
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Media/MediaIOFramework/Source/GPUTextureTransfer/Public/GPUTextureTransferModule.h