Unreal Engine 5.6 C++ API: UE::FTimeout Class Reference
UE::FTimeout Class Reference
Utility class to create a timeout that will expire at a point in the future.
#include "Timeout.h"
Public Member Functions
FTimeout (const FTimeout &BaseTimeout, double TimeoutSeconds)
Construct a timeout that started at the same time as BaseTimeout, but with a new duration.
FTimeout (double TimeoutSeconds)
Construct a timeout that starts right now and will end after the passed in time in seconds.
FTimeout (FTimespan TimeoutValue)
Construct a timeout that starts right now and will end after the passed in timespan.
double GetElapsedSeconds () const
Returns time since the timeout was created, in seconds.
FTimespan GetElapsedTime () const
Returns time since the timeout was created, as a timespan.
uint32 GetRemainingRoundedUpMilliseconds () const
Intended for use in waiting functions, e.g.
double GetRemainingSeconds () const
Returns time left until the timeout expires (which can be negative) in seconds.
FTimespan GetRemainingTime () const
Returns time left until the timeout expires (which can be negative) as a timespan.
double GetTimeoutSeconds () const
Returns duration of timeout in seconds.
FTimespan GetTimeoutValue () const
Returns duration of timeout as a timespan.
FORCEINLINE bool IsAlwaysExpired () const
Returns true if this was created from AlwaysExpired and does not need to be repeatedly checked.
bool IsExpired () const
Return true if elapsed time is greater than the initially requested timeout.
void ModifyTimeoutSeconds (double DeltaTimeoutSeconds)
Safely modify the remaining time by adding the delta time in seconds to the timeout.
void SetTimeoutSeconds (double TimeoutSeconds)
Sets the timeout to new value in seconds.
void SetToExpired ()
Set this timeout to explicitly expired without recalculating start time.
UE_DEPRECATED (5.5, "Use IsExpired() instead.") explicit operator bool() const
FORCEINLINE bool WillNeverExpire () const
Returns true if this was created from Never and does not need to be repeatedly checked.
Static Public Member Functions
static FTimeout AlwaysExpired ()
Create a timeout that will always return true for IsExpired.
static FTimeout Never ()
Create a timeout that will never return true for IsExpired.
Private Member Functions
FTimeout (uint64 StartValue, uint64 TimeoutValue)
Private Attributes
uint64 StartCycles = 0
uint64 TimeoutCycles = 0
Static Private Attributes
static constexpr uint64 NeverExpireCycles = TNumericLimits<uint64>::Max()
static constexpr double NeverExpireSeconds = TNumericLimits<double>::Max()
Friends
bool operator!= (FTimeout Left, FTimeout Right)
bool operator== (FTimeout Left, FTimeout Right)
Detailed Description
Utility class to create a timeout that will expire at a point in the future.
Example usage:
FTimeout TimeoutFromTimespan(FTimespan::FromMilliseconds(2)); FTimeout TimeoutFromSeconds(0.002); while (!TimeoutFromSeconds.IsExpired()) { ... }
Definition at line 20 of file Timeout.h.
Constructor & Destructor Documentation
FTimeout() [1/4]
UE::FTimeout::FTimeout (double TimeoutSeconds) inline explicit
Construct a timeout that starts right now and will end after the passed in time in seconds.
Definition at line 82 of file Timeout.h.
References SetTimeoutSeconds(), and StartCycles.
Referenced by FTimeout(), AlwaysExpired(), Never(), operator!=, and operator==.
FTimeout() [2/4]
UE::FTimeout::FTimeout (const FTimeout & BaseTimeout, double TimeoutSeconds) inline explicit
Construct a timeout that started at the same time as BaseTimeout, but with a new duration.
Definition at line 89 of file Timeout.h.
References FTimeout(), SetTimeoutSeconds(), and StartCycles.
FTimeout() [3/4]
UE::FTimeout::FTimeout (FTimespan TimeoutValue) inline explicit
Construct a timeout that starts right now and will end after the passed in timespan.
Definition at line 164 of file Timeout.h.
References FTimespan::GetTotalSeconds(), FTimespan::MaxValue(), NeverExpireCycles, SetTimeoutSeconds(), StartCycles, and TimeoutCycles.
FTimeout() [4/4]
UE::FTimeout::FTimeout (uint64 StartValue, uint64 TimeoutValue) inline private
Definition at line 236 of file Timeout.h.
References StartCycles, and TimeoutCycles.
Member Function Documentation
AlwaysExpired()
FTimeout UE::FTimeout::AlwaysExpired () inline static
Create a timeout that will always return true for IsExpired.
Definition at line 61 of file Timeout.h.
References FTimeout(), and FAndroidTime::Cycles64().
GetElapsedSeconds()
double UE::FTimeout::GetElapsedSeconds () const inline
Returns time since the timeout was created, in seconds.
Definition at line 96 of file Timeout.h.
References FAndroidTime::Cycles64(), StartCycles, and FGenericPlatformTime::ToSeconds64().
Referenced by GetElapsedTime(), and GetRemainingSeconds().
GetElapsedTime()
FTimespan UE::FTimeout::GetElapsedTime () const inline
Returns time since the timeout was created, as a timespan.
Definition at line 178 of file Timeout.h.
References FTimespan::FromSeconds(), and GetElapsedSeconds().
GetRemainingRoundedUpMilliseconds()
uint32 UE::FTimeout::GetRemainingRoundedUpMilliseconds () const inline
Intended for use in waiting functions, e.g.
FEvent::Wait() returns the whole number (rounded up) of remaining milliseconds, clamped into [0, MAX_uint32] range
Definition at line 209 of file Timeout.h.
References FMath::Clamp(), FMath::DivideAndRoundUp(), GetRemainingTime(), FTimespan::GetTicks(), MAX_uint32, ETimespan::TicksPerMillisecond, and WillNeverExpire().
GetRemainingSeconds()
double UE::FTimeout::GetRemainingSeconds () const inline
Returns time left until the timeout expires (which can be negative) in seconds.
Definition at line 103 of file Timeout.h.
References GetElapsedSeconds(), GetTimeoutSeconds(), NeverExpireSeconds, and WillNeverExpire().
Referenced by GetRemainingTime().
GetRemainingTime()
FTimespan UE::FTimeout::GetRemainingTime () const inline
Returns time left until the timeout expires (which can be negative) as a timespan.
Definition at line 184 of file Timeout.h.
References FTimespan::FromSeconds(), GetRemainingSeconds(), FTimespan::MaxValue(), and WillNeverExpire().
Referenced by GetRemainingRoundedUpMilliseconds().
GetTimeoutSeconds()
double UE::FTimeout::GetTimeoutSeconds () const inline
Returns duration of timeout in seconds.
Definition at line 116 of file Timeout.h.
References TimeoutCycles, and FGenericPlatformTime::ToSeconds64().
Referenced by GetRemainingSeconds(), and GetTimeoutValue().
GetTimeoutValue()
FTimespan UE::FTimeout::GetTimeoutValue () const inline
Returns duration of timeout as a timespan.
Definition at line 195 of file Timeout.h.
References FTimespan::FromSeconds(), GetTimeoutSeconds(), FTimespan::MaxValue(), and WillNeverExpire().
IsAlwaysExpired()
FORCEINLINE bool UE::FTimeout::IsAlwaysExpired () const inline
Returns true if this was created from AlwaysExpired and does not need to be repeatedly checked.
Definition at line 67 of file Timeout.h.
References FORCEINLINE, and TimeoutCycles.
Referenced by IsExpired(), and ModifyTimeoutSeconds().
IsExpired()
bool UE::FTimeout::IsExpired () const inline
Return true if elapsed time is greater than the initially requested timeout.
Definition at line 31 of file Timeout.h.
References FAndroidTime::Cycles64(), IsAlwaysExpired(), StartCycles, TimeoutCycles, and WillNeverExpire().
Referenced by UE_DEPRECATED().
ModifyTimeoutSeconds()
void UE::FTimeout::ModifyTimeoutSeconds (double DeltaTimeoutSeconds) inline
Safely modify the remaining time by adding the delta time in seconds to the timeout.
Definition at line 135 of file Timeout.h.
References IsAlwaysExpired(), FGenericPlatformTime::SecondsToCycles64(), SetToExpired(), TimeoutCycles, and WillNeverExpire().
Never()
FTimeout UE::FTimeout::Never () inline static
Create a timeout that will never return true for IsExpired.
Definition at line 49 of file Timeout.h.
References FTimeout(), FAndroidTime::Cycles64(), and NeverExpireCycles.
Referenced by UE::Tasks::Private::FTaskBase::UE_DEPRECATED().
SetTimeoutSeconds()
void UE::FTimeout::SetTimeoutSeconds (double TimeoutSeconds) inline
Sets the timeout to new value in seconds.
Definition at line 122 of file Timeout.h.
References FGenericPlatformTime::SecondsToCycles64(), SetToExpired(), and TimeoutCycles.
Referenced by FTimeout(), FTimeout(), and FTimeout().
SetToExpired()
void UE::FTimeout::SetToExpired () inline
Set this timeout to explicitly expired without recalculating start time.
Definition at line 73 of file Timeout.h.
References TimeoutCycles.
Referenced by ModifyTimeoutSeconds(), and SetTimeoutSeconds().
UE_DEPRECATED()
UE::FTimeout::UE_DEPRECATED (5. 5, "Use IsExpired() instead.") const inline
Definition at line 24 of file Timeout.h.
References IsExpired().
WillNeverExpire()
FORCEINLINE bool UE::FTimeout::WillNeverExpire () const inline
Returns true if this was created from Never and does not need to be repeatedly checked.
Definition at line 55 of file Timeout.h.
References FORCEINLINE, NeverExpireCycles, and TimeoutCycles.
Referenced by GetRemainingRoundedUpMilliseconds(), GetRemainingSeconds(), GetRemainingTime(), GetTimeoutValue(), IsExpired(), and ModifyTimeoutSeconds().
Friends And Related Symbol Documentation
operator!=
bool operator!= (FTimeout Left, FTimeout Right) friend
Definition at line 230 of file Timeout.h.
References FTimeout(), Left, operator==, and Right.
operator==
bool operator== (FTimeout Left, FTimeout Right) friend
Definition at line 222 of file Timeout.h.
References FTimeout(), Left, and Right.
Referenced by operator!=.
Field Documentation
NeverExpireCycles
uint64 UE::FTimeout::NeverExpireCycles = TNumericLimits<uint64>::Max() static constexpr private
Definition at line 242 of file Timeout.h.
Referenced by FTimeout(), Never(), and WillNeverExpire().
NeverExpireSeconds
double UE::FTimeout::NeverExpireSeconds = TNumericLimits<double>::Max() static constexpr private
Definition at line 243 of file Timeout.h.
Referenced by GetRemainingSeconds().
StartCycles
uint64 UE::FTimeout::StartCycles = 0 private
Definition at line 246 of file Timeout.h.
Referenced by FTimeout(), FTimeout(), FTimeout(), FTimeout(), GetElapsedSeconds(), and IsExpired().
TimeoutCycles
uint64 UE::FTimeout::TimeoutCycles = 0 private
Definition at line 249 of file Timeout.h.
Referenced by FTimeout(), FTimeout(), GetTimeoutSeconds(), IsAlwaysExpired(), IsExpired(), ModifyTimeoutSeconds(), SetTimeoutSeconds(), SetToExpired(), and WillNeverExpire().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Misc/Timeout.h