Unreal Engine 5.6 C++ API: FWindowsSemaphore Class Reference
FWindowsSemaphore Class Reference
#include "WindowsSemaphore.h"
Public Member Functions
FWindowsSemaphore (int32 InitialCount, int32 MaxCount)
~FWindowsSemaphore ()
void Acquire ()
void Release (int32 Count=1)
bool TryAcquire (FTimespan Timeout=FTimespan::Zero())
UE_NONCOPYABLE (FWindowsSemaphore)
Private Attributes
HANDLE Semaphore
Detailed Description
Definition at line 10 of file WindowsSemaphore.h.
Constructor & Destructor Documentation
FWindowsSemaphore()
FWindowsSemaphore::FWindowsSemaphore (int32 InitialCount, int32 MaxCount) inline
Definition at line 15 of file WindowsSemaphore.h.
References checkfSlow, Semaphore, and TEXT.
Referenced by UE_NONCOPYABLE().
~FWindowsSemaphore()
FWindowsSemaphore::~FWindowsSemaphore () inline
Definition at line 21 of file WindowsSemaphore.h.
References Semaphore.
Member Function Documentation
Acquire()
void FWindowsSemaphore::Acquire () inline
Definition at line 26 of file WindowsSemaphore.h.
References checkfSlow, DWORD, Semaphore, and TEXT.
Release()
void FWindowsSemaphore::Release (int32 Count = 1) inline
Definition at line 39 of file WindowsSemaphore.h.
References checkfSlow, Count, Semaphore, and TEXT.
TryAcquire()
bool FWindowsSemaphore::TryAcquire (FTimespan Timeout = FTimespan::Zero()) inline
Definition at line 32 of file WindowsSemaphore.h.
References checkfSlow, DWORD, Semaphore, TEXT, Timeout, and FTimespan::Zero().
UE_NONCOPYABLE()
FWindowsSemaphore::UE_NONCOPYABLE (FWindowsSemaphore)
References FWindowsSemaphore().
Field Documentation
Semaphore
HANDLE FWindowsSemaphore::Semaphore private
Definition at line 47 of file WindowsSemaphore.h.
Referenced by FWindowsSemaphore(), ~FWindowsSemaphore(), Acquire(), Release(), and TryAcquire().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Windows/WindowsSemaphore.h