Unreal Engine 5.6 C++ API: FDriverVersion Class Reference
FDriverVersion Class Reference
#include "GenericPlatformDriver.h"
Public Member Functions
FDriverVersion ()=default
FDriverVersion (const FString &DriverVersionString)
uint32 GetVersionValue (uint32 Index) const
const TArray< uint32 > & GetVersionValues () const
bool operator!= (const FDriverVersion &Other) const
bool operator< (const FDriverVersion &Other) const
bool operator<= (const FDriverVersion &Other) const
bool operator== (const FDriverVersion &Other) const
bool operator> (const FDriverVersion &Other) const
bool operator>= (const FDriverVersion &Other) const
void Parse (const FString &DriverVersionString)
Private Attributes
TArray< uint32 > Values
Detailed Description
Definition at line 18 of file GenericPlatformDriver.h.
Constructor & Destructor Documentation
FDriverVersion() [1/2]
FDriverVersion::FDriverVersion () default
Referenced by operator!=(), operator<(), operator<=(), operator==(), operator>(), and operator>=().
FDriverVersion() [2/2]
FDriverVersion::FDriverVersion (const FString & DriverVersionString) inline
Definition at line 23 of file GenericPlatformDriver.h.
References Parse().
Member Function Documentation
GetVersionValue()
uint32 FDriverVersion::GetVersionValue (uint32 Index) const inline
Definition at line 81 of file GenericPlatformDriver.h.
References Values.
Referenced by FGPUDriverInfo::IsSameDriverVersionGeneration().
GetVersionValues()
const TArray< uint32 > & FDriverVersion::GetVersionValues () const inline
Definition at line 86 of file GenericPlatformDriver.h.
References Values.
operator!=()
bool FDriverVersion::operator!= (const FDriverVersion & Other) const inline
Definition at line 67 of file GenericPlatformDriver.h.
References FDriverVersion(), and Other.
operator<()
bool FDriverVersion::operator< (const FDriverVersion & Other) const inline
Definition at line 63 of file GenericPlatformDriver.h.
References FDriverVersion(), and Other.
operator<=()
bool FDriverVersion::operator<= (const FDriverVersion & Other) const inline
Definition at line 75 of file GenericPlatformDriver.h.
References FDriverVersion(), and Other.
operator==()
bool FDriverVersion::operator== (const FDriverVersion & Other) const inline
Definition at line 59 of file GenericPlatformDriver.h.
References FDriverVersion(), and Other.
operator>()
bool FDriverVersion::operator> (const FDriverVersion & Other) const inline
Definition at line 42 of file GenericPlatformDriver.h.
References FDriverVersion(), Other, and Values.
operator>=()
bool FDriverVersion::operator>= (const FDriverVersion & Other) const inline
Definition at line 71 of file GenericPlatformDriver.h.
References FDriverVersion(), and Other.
Parse()
void FDriverVersion::Parse (const FString & DriverVersionString) inline
Definition at line 28 of file GenericPlatformDriver.h.
References TCString< TCHAR >::Atoi(), TEXT, and Values.
Referenced by FDriverVersion(), and FDriverDenyListEntry::FDriverVersionDenyListEntry::FromString().
Field Documentation
Values
TArray<uint32> FDriverVersion::Values private
Definition at line 92 of file GenericPlatformDriver.h.
Referenced by GetVersionValue(), GetVersionValues(), operator>(), and Parse().
The documentation for this class was generated from the following file:
Runtime/Core/Public/GenericPlatform/GenericPlatformDriver.h