Unreal Engine 5.6 C++ API: IConsoleCommandExecutor Class Reference
IConsoleCommandExecutor Class Reference abstract
Handles executing console commands.
#include "IConsoleManager.h"
Public Member Functions
virtual ~IConsoleCommandExecutor ()=default
virtual bool AllowHotKeyClose () const =0
True if we allow the console to be closed using the "open console" hot-key.
virtual bool AllowMultiLine () const =0
True if we allow the console to create multi-line commands.
virtual bool Exec (const TCHAR *Input)=0
Execute the given command using this executor.
virtual FText GetDescription () const =0
Get the description of this executor.
virtual FText GetDisplayName () const =0
Get the display name of this executor.
virtual void GetExecHistory (TArray< FString > &Out)=0
Get the list of commands that this executor has recently processed.
virtual FText GetHintText () const =0
Get the hint text of this executor.
virtual struct FInputChord GetHotKey () const =0
Returns the hotkey for this executor.
virtual struct FInputChord GetIterateExecutorHotKey () const =0
Returns the hotkey to switch to the next executor.
virtual FName GetName () const =0
Get the name of this executor.
virtual void GetSuggestedCompletions (const TCHAR *Input, TArray< FConsoleSuggestion > &Out)=0
Get the list of auto-complete suggestions for the given command.
UE_DEPRECATED (5.5, "Use GetSuggestedCompletions instead") virtual void GetAutoCompleteSuggestions(const TCHAR *Input
Get the list of auto-complete suggestions for the given command.
Static Public Member Functions
static FName ModularFeatureName ()
Get the name identifying this modular feature set.
Data Fields
TArray< FString > & Out {}
Detailed Description
Handles executing console commands.
Definition at line 798 of file IConsoleManager.h.
Constructor & Destructor Documentation
~IConsoleCommandExecutor()
virtual IConsoleCommandExecutor::~IConsoleCommandExecutor () virtual default
Member Function Documentation
AllowHotKeyClose()
virtual bool IConsoleCommandExecutor::AllowHotKeyClose () const pure virtual
True if we allow the console to be closed using the "open console" hot-key.
Note
Some scripting languages use the default "open console" hot-key (~) in their code, so these should return false.
Implemented in FConsoleCommandExecutor.
AllowMultiLine()
virtual bool IConsoleCommandExecutor::AllowMultiLine () const pure virtual
True if we allow the console to create multi-line commands.
Implemented in FConsoleCommandExecutor.
Exec()
virtual bool IConsoleCommandExecutor::Exec (const TCHAR * Input) pure virtual
Execute the given command using this executor.
Returns
true if the command was recognized.
Implemented in FConsoleCommandExecutor.
References Input.
GetDescription()
virtual FText IConsoleCommandExecutor::GetDescription () const pure virtual
Get the description of this executor.
Implemented in FConsoleCommandExecutor.
GetDisplayName()
virtual FText IConsoleCommandExecutor::GetDisplayName () const pure virtual
Get the display name of this executor.
Implemented in FConsoleCommandExecutor.
GetExecHistory()
virtual void IConsoleCommandExecutor::GetExecHistory (TArray< FString > & Out) pure virtual
Get the list of commands that this executor has recently processed.
Implemented in FConsoleCommandExecutor.
References Out.
GetHintText()
virtual FText IConsoleCommandExecutor::GetHintText () const pure virtual
Get the hint text of this executor.
Implemented in FConsoleCommandExecutor.
GetHotKey()
virtual struct FInputChord IConsoleCommandExecutor::GetHotKey () const pure virtual
Returns the hotkey for this executor.
Implemented in FConsoleCommandExecutor.
References GetHotKey().
Referenced by GetHotKey().
GetIterateExecutorHotKey()
virtual struct FInputChord IConsoleCommandExecutor::GetIterateExecutorHotKey () const pure virtual
Returns the hotkey to switch to the next executor.
This is usually the same hotkey as GetHotKey but with a modifier, such as "`" turning into "Ctrl + `".
Implemented in FConsoleCommandExecutor.
References GetIterateExecutorHotKey().
Referenced by GetIterateExecutorHotKey().
GetName()
virtual FName IConsoleCommandExecutor::GetName () const pure virtual
Get the name of this executor.
Implemented in FConsoleCommandExecutor.
GetSuggestedCompletions()
virtual void IConsoleCommandExecutor::GetSuggestedCompletions (const TCHAR * Input, TArray< FConsoleSuggestion > & Out) pure virtual
Get the list of auto-complete suggestions for the given command.
Implemented in FConsoleCommandExecutor.
References Input, and Out.
ModularFeatureName()
FName IConsoleCommandExecutor::ModularFeatureName () inline static
Get the name identifying this modular feature set.
Definition at line 806 of file IConsoleManager.h.
References Name, and TEXT.
UE_DEPRECATED()
IConsoleCommandExecutor::UE_DEPRECATED (5. 5, "Use GetSuggestedCompletions instead") const
Get the list of auto-complete suggestions for the given command.
Field Documentation
Out
TArray<FString>& IConsoleCommandExecutor::Out {}
Definition at line 841 of file IConsoleManager.h.
Referenced by FConsoleCommandExecutor::GetExecHistory(), GetExecHistory(), FConsoleCommandExecutor::GetSuggestedCompletions(), and GetSuggestedCompletions().
The documentation for this class was generated from the following file:
Runtime/Core/Public/HAL/IConsoleManager.h