Unreal Engine 5.6 C++ API: FVertexFactoryType Class Reference
FVertexFactoryType Class Reference
An object used to represent the type of a vertex factory.
#include "VertexFactory.h"
Public Types
typedef FVertexFactoryShaderParameters *(* ConstructParametersType) (EShaderFrequency ShaderFrequency, const class FShaderParameterMap &ParameterMap)
typedef void(* GetParameterTypeElementShaderBindingsType) (EShaderFrequency ShaderFrequency, const FVertexFactoryShaderParameters *Parameters, const class FSceneInterface *Scene, const class FSceneView *View, const class FMeshMaterialShader *Shader, const EVertexInputStreamType InputStreamType, ERHIFeatureLevel::Type FeatureLevel, const class FVertexFactory *VertexFactory, const struct FMeshBatchElement &BatchElement, class FMeshDrawSingleShaderBindings &ShaderBindings, FVertexInputStreamArray &VertexStreams)
typedef const FTypeLayoutDesc *(* GetParameterTypeLayoutType) (EShaderFrequency ShaderFrequency)
typedef void(* GetPSOPrecacheVertexFetchElementsType) (EVertexInputStreamType VertexInputStreamType, FVertexDeclarationElementList &Elements)
typedef void(* ModifyCompilationEnvironmentType) (const FVertexFactoryShaderPermutationParameters &, FShaderCompilerEnvironment &)
typedef bool(* ShouldCacheType) (const FVertexFactoryShaderPermutationParameters &)
typedef void(* ValidateCompiledResultType) (const FVertexFactoryType *, EShaderPlatform, const FShaderParameterMap &ParameterMap, TArray< FString > &OutErrors)
Public Member Functions
RENDERCORE_API FVertexFactoryType (const TCHAR *InName, const TCHAR *InShaderFilename, EVertexFactoryFlags InFlags, ConstructParametersType InConstructParameters, GetParameterTypeLayoutType InGetParameterTypeLayout, GetParameterTypeElementShaderBindingsType InGetParameterTypeElementShaderBindings, GetPSOPrecacheVertexFetchElementsType InGetPSOPrecacheVertexFetchElements, ShouldCacheType InShouldCache, ModifyCompilationEnvironmentType InModifyCompilationEnvironment, ValidateCompiledResultType InValidateCompiledResult)
virtual RENDERCORE_API ~FVertexFactoryType ()
RENDERCORE_API void AddUniformBufferIncludesToEnvironment (FShaderCompilerEnvironment &OutEnvironment, EShaderPlatform Platform) const
Adds include statements for uniform buffers that this shader type references, and builds a prefix for the shader file with the include statements.
FVertexFactoryShaderParameters * CreateShaderParameters (EShaderFrequency ShaderFrequency, const class FShaderParameterMap &ParameterMap) const
EVertexFactoryFlags GetFlags () const
FName GetFName () const
const FHashedName & GetHashedName () const
const TCHAR * GetName () const
const TSet< const TCHAR *, TStringPointerSetKeyFuncs_DEPRECATED< const TCHAR * > > & GetReferencedUniformBufferNames () const
const TSet< const FShaderParametersMetadata * > & GetReferencedUniformBuffers () const
const TCHAR * GetShaderFilename () const
const TCHAR * GetShaderFwdFilename () const
void GetShaderParameterElementShaderBindings (EShaderFrequency ShaderFrequency, const FVertexFactoryShaderParameters *Parameters, const class FSceneInterface *Scene, const class FSceneView *View, const class FMeshMaterialShader *Shader, const EVertexInputStreamType InputStreamType, ERHIFeatureLevel::Type FeatureLevel, const class FVertexFactory *VertexFactory, const struct FMeshBatchElement &BatchElement, class FMeshDrawSingleShaderBindings &ShaderBindings, FVertexInputStreamArray &VertexStreams) const
const FTypeLayoutDesc * GetShaderParameterLayout (EShaderFrequency ShaderFrequency) const
void GetShaderPSOPrecacheVertexFetchElements (EVertexInputStreamType VertexInputStreamType, FVertexDeclarationElementList &Elements) const
RENDERCORE_API const FSHAHash & GetSourceHash (EShaderPlatform ShaderPlatform) const
Calculates a Hash based on this vertex factory type's source code and includes.
bool HasFlags (EVertexFactoryFlags FlagsToCheck) const
Returns true if this vertex factory supports ALL feature flags in FlagsToCheck.
bool IncludesFwdShaderFile () const
bool IsUsedWithMaterials () const
void ModifyCompilationEnvironment (const FVertexFactoryShaderPermutationParameters &Parameters, FShaderCompilerEnvironment &OutEnvironment) const
Calls the function ptr for the shader type on the given environment.
bool ShouldCache (const FVertexFactoryShaderPermutationParameters &Parameters) const
Should we cache the material's shadertype on this platform with this vertex factory?
bool SupportsCachingMeshDrawCommands () const
bool SupportsComputeShading () const
bool SupportsDynamicLighting () const
bool SupportsGPUSkinPassThrough () const
bool SupportsLandscape () const
bool SupportsLightmapBaking () const
bool SupportsLumenMeshCards () const
bool SupportsManualVertexFetch (ERHIFeatureLevel::Type InFeatureLevel) const
bool SupportsNaniteRendering () const
bool SupportsNullPixelShader () const
bool SupportsPositionOnly () const
bool SupportsPrecisePrevWorldPos () const
bool SupportsPrimitiveIdStream () const
bool SupportsPSOPrecaching () const
bool SupportsRayTracing () const
bool SupportsRayTracingDynamicGeometry () const
bool SupportsRayTracingProceduralPrimitive () const
bool SupportsStaticLighting () const
bool SupportsTriangleSorting () const
RENDERCORE_API void UpdateReferencedUniformBufferNames (const TMap< FString, TArray< const TCHAR * > > &ShaderFileToUniformBufferVariables)
void ValidateCompiledResult (EShaderPlatform Platform, const FShaderParameterMap &ParameterMap, TArray< FString > &OutErrors) const
Static Public Member Functions
static RENDERCORE_API bool CheckManualVertexFetchSupport (ERHIFeatureLevel::Type InFeatureLevel)
static int32 GetNumVertexFactoryTypes ()
static RENDERCORE_API const TArray< FVertexFactoryType * > & GetSortedMaterialTypes ()
static RENDERCORE_API TLinkedList< FVertexFactoryType * > *& GetTypeList ()
static RENDERCORE_API FVertexFactoryType * GetVFByName (const FHashedName &VFName)
Finds a FVertexFactoryType by name.
static void Initialize (const TMap< FString, TArray< const TCHAR * > > &ShaderFileToUniformBufferVariables)
Initialize FVertexFactoryType static members, this must be called before any VF types are created.
Private Attributes
ConstructParametersType ConstructParameters
EVertexFactoryFlags Flags
GetParameterTypeElementShaderBindingsType GetParameterTypeElementShaderBindings
GetParameterTypeLayoutType GetParameterTypeLayout
GetPSOPrecacheVertexFetchElementsType GetPSOPrecacheVertexFetchElements
TLinkedList< FVertexFactoryType * > GlobalListLink
FHashedName HashedName
ModifyCompilationEnvironmentType ModifyCompilationEnvironmentRef
const TCHAR * Name
TSet< const FShaderParametersMetadata * > ReferencedUniformBuffers
Cache of referenced uniform buffer structs.
const TCHAR * ShaderFilename
FString ShaderFwdFilename
ShouldCacheType ShouldCacheRef
FName TypeName
ValidateCompiledResultType ValidateCompiledResultRef
Static Private Attributes
static bool bInitializedSerializationHistory
Tracks whether serialization history for all shader types has been initialized.
static RENDERCORE_API uint32 NumVertexFactories
Friends
uint32 GetTypeHash (const FVertexFactoryType *Type)
Detailed Description
An object used to represent the type of a vertex factory.
Definition at line 313 of file VertexFactory.h.
Member Typedef Documentation
ConstructParametersType
typedef FVertexFactoryShaderParameters *(* FVertexFactoryType::ConstructParametersType) (EShaderFrequency ShaderFrequency, const class FShaderParameterMap &ParameterMap)
Definition at line 317 of file VertexFactory.h.
GetParameterTypeElementShaderBindingsType
typedef void(* FVertexFactoryType::GetParameterTypeElementShaderBindingsType) (EShaderFrequency ShaderFrequency, const FVertexFactoryShaderParameters *Parameters, const class FSceneInterface *Scene, const class FSceneView *View, const class FMeshMaterialShader *Shader, const EVertexInputStreamType InputStreamType, ERHIFeatureLevel::Type FeatureLevel, const class FVertexFactory *VertexFactory, const struct FMeshBatchElement &BatchElement, class FMeshDrawSingleShaderBindings &ShaderBindings, FVertexInputStreamArray &VertexStreams)
Definition at line 319 of file VertexFactory.h.
GetParameterTypeLayoutType
typedef const FTypeLayoutDesc *(* FVertexFactoryType::GetParameterTypeLayoutType) (EShaderFrequency ShaderFrequency)
Definition at line 318 of file VertexFactory.h.
GetPSOPrecacheVertexFetchElementsType
typedef void(* FVertexFactoryType::GetPSOPrecacheVertexFetchElementsType) (EVertexInputStreamType VertexInputStreamType, FVertexDeclarationElementList &Elements)
Definition at line 330 of file VertexFactory.h.
ModifyCompilationEnvironmentType
typedef void(* FVertexFactoryType::ModifyCompilationEnvironmentType) (const FVertexFactoryShaderPermutationParameters &, FShaderCompilerEnvironment &)
Definition at line 334 of file VertexFactory.h.
ShouldCacheType
typedef bool(* FVertexFactoryType::ShouldCacheType) (const FVertexFactoryShaderPermutationParameters &)
Definition at line 331 of file VertexFactory.h.
ValidateCompiledResultType
typedef void(* FVertexFactoryType::ValidateCompiledResultType) (const FVertexFactoryType *, EShaderPlatform, const FShaderParameterMap &ParameterMap, TArray< FString > &OutErrors)
Definition at line 335 of file VertexFactory.h.
Constructor & Destructor Documentation
FVertexFactoryType()
RENDERCORE_API FVertexFactoryType::FVertexFactoryType (const TCHAR * InName, const TCHAR * InShaderFilename, EVertexFactoryFlags InFlags, ConstructParametersType InConstructParameters, GetParameterTypeLayoutType InGetParameterTypeLayout, GetParameterTypeElementShaderBindingsType InGetParameterTypeElementShaderBindings, GetPSOPrecacheVertexFetchElementsType InGetPSOPrecacheVertexFetchElements, ShouldCacheType InShouldCache, ModifyCompilationEnvironmentType InModifyCompilationEnvironment, ValidateCompiledResultType InValidateCompiledResult)
References InName.
Referenced by GetTypeHash, and GetVFByName().
~FVertexFactoryType()
virtual RENDERCORE_API FVertexFactoryType::~FVertexFactoryType () virtual
Member Function Documentation
AddUniformBufferIncludesToEnvironment()
RENDERCORE_API void FVertexFactoryType::AddUniformBufferIncludesToEnvironment (FShaderCompilerEnvironment & OutEnvironment, EShaderPlatform Platform) const
Adds include statements for uniform buffers that this shader type references, and builds a prefix for the shader file with the include statements.
References Platform.
CheckManualVertexFetchSupport()
RENDERCORE_API bool FVertexFactoryType::CheckManualVertexFetchSupport (ERHIFeatureLevel::Type InFeatureLevel) static
Referenced by SupportsManualVertexFetch().
CreateShaderParameters()
FVertexFactoryShaderParameters * FVertexFactoryType::CreateShaderParameters (EShaderFrequency ShaderFrequency, const class FShaderParameterMap & ParameterMap) const inline
Definition at line 379 of file VertexFactory.h.
References ConstructParameters.
GetFlags()
EVertexFactoryFlags FVertexFactoryType::GetFlags () const inline
Definition at line 394 of file VertexFactory.h.
References Flags.
GetFName()
FName FVertexFactoryType::GetFName () const inline
Definition at line 374 of file VertexFactory.h.
References TypeName.
GetHashedName()
const FHashedName & FVertexFactoryType::GetHashedName () const inline
Definition at line 375 of file VertexFactory.h.
References HashedName.
Referenced by FMaterialShaderMap::AcquireMeshShaderMap(), and FMaterialShaderMap::GetMeshShaderMap().
GetName()
const TCHAR * FVertexFactoryType::GetName () const inline
Definition at line 373 of file VertexFactory.h.
References Name.
GetNumVertexFactoryTypes()
int32 FVertexFactoryType::GetNumVertexFactoryTypes () inline static
Definition at line 338 of file VertexFactory.h.
References NumVertexFactories.
GetReferencedUniformBufferNames()
const TSet< const TCHAR *, TStringPointerSetKeyFuncs_DEPRECATED< const TCHAR * > > & FVertexFactoryType::GetReferencedUniformBufferNames () const inline
Definition at line 486 of file VertexFactory.h.
References GetReferencedUniformBufferNames().
Referenced by GetReferencedUniformBufferNames().
GetReferencedUniformBuffers()
const TSet< const FShaderParametersMetadata * > & FVertexFactoryType::GetReferencedUniformBuffers () const inline
Definition at line 492 of file VertexFactory.h.
References ReferencedUniformBuffers.
GetShaderFilename()
const TCHAR * FVertexFactoryType::GetShaderFilename () const inline
Definition at line 376 of file VertexFactory.h.
References ShaderFilename.
Referenced by ModifyCompilationEnvironment().
GetShaderFwdFilename()
const TCHAR * FVertexFactoryType::GetShaderFwdFilename () const inline
Definition at line 377 of file VertexFactory.h.
References ShaderFwdFilename.
Referenced by ModifyCompilationEnvironment().
GetShaderParameterElementShaderBindings()
void FVertexFactoryType::GetShaderParameterElementShaderBindings (EShaderFrequency ShaderFrequency, const FVertexFactoryShaderParameters * Parameters, const class FSceneInterface * Scene, const class FSceneView * View, const class FMeshMaterialShader * Shader, const EVertexInputStreamType InputStreamType, ERHIFeatureLevel::Type FeatureLevel, const class FVertexFactory * VertexFactory, const struct FMeshBatchElement & BatchElement, class FMeshDrawSingleShaderBindings & ShaderBindings, FVertexInputStreamArray & VertexStreams) const inline
Definition at line 381 of file VertexFactory.h.
References Scene, and VertexFactory.
GetShaderParameterLayout()
const FTypeLayoutDesc * FVertexFactoryType::GetShaderParameterLayout (EShaderFrequency ShaderFrequency) const inline
Definition at line 380 of file VertexFactory.h.
References GetParameterTypeLayout.
GetShaderPSOPrecacheVertexFetchElements()
void FVertexFactoryType::GetShaderPSOPrecacheVertexFetchElements (EVertexInputStreamType VertexInputStreamType, FVertexDeclarationElementList & Elements) const inline
Definition at line 392 of file VertexFactory.h.
References GetPSOPrecacheVertexFetchElements.
GetSortedMaterialTypes()
RENDERCORE_API const TArray< FVertexFactoryType * > & FVertexFactoryType::GetSortedMaterialTypes () static
GetSourceHash()
RENDERCORE_API const FSHAHash & FVertexFactoryType::GetSourceHash (EShaderPlatform ShaderPlatform) const
Calculates a Hash based on this vertex factory type's source code and includes.
References ShaderPlatform.
GetTypeList()
RENDERCORE_API TLinkedList< FVertexFactoryType * > *& FVertexFactoryType::GetTypeList () static
Returns
The global shader factory list.
GetVFByName()
RENDERCORE_API FVertexFactoryType * FVertexFactoryType::GetVFByName (const FHashedName & VFName) static
Finds a FVertexFactoryType by name.
References FVertexFactoryType().
HasFlags()
bool FVertexFactoryType::HasFlags (EVertexFactoryFlags FlagsToCheck) const inline
Returns true if this vertex factory supports ALL feature flags in FlagsToCheck.
Definition at line 400 of file VertexFactory.h.
References EnumHasAllFlags(), and Flags.
Referenced by IncludesFwdShaderFile(), IsUsedWithMaterials(), SupportsCachingMeshDrawCommands(), SupportsComputeShading(), SupportsDynamicLighting(), SupportsGPUSkinPassThrough(), SupportsLandscape(), SupportsLightmapBaking(), SupportsLumenMeshCards(), SupportsManualVertexFetch(), SupportsNaniteRendering(), SupportsNullPixelShader(), SupportsPositionOnly(), SupportsPrecisePrevWorldPos(), SupportsPrimitiveIdStream(), SupportsPSOPrecaching(), SupportsRayTracing(), SupportsRayTracingDynamicGeometry(), SupportsRayTracingProceduralPrimitive(), SupportsStaticLighting(), and SupportsTriangleSorting().
IncludesFwdShaderFile()
bool FVertexFactoryType::IncludesFwdShaderFile () const inline
Definition at line 423 of file VertexFactory.h.
References HasFlags(), and IncludesFwdShader.
Referenced by ModifyCompilationEnvironment().
Initialize()
void FVertexFactoryType::Initialize (const TMap< FString, TArray< const TCHAR * > > & ShaderFileToUniformBufferVariables) static
Initialize FVertexFactoryType static members, this must be called before any VF types are created.
IsUsedWithMaterials()
bool FVertexFactoryType::IsUsedWithMaterials () const inline
Definition at line 405 of file VertexFactory.h.
References HasFlags(), and UsedWithMaterials.
ModifyCompilationEnvironment()
void FVertexFactoryType::ModifyCompilationEnvironment (const FVertexFactoryShaderPermutationParameters & Parameters, FShaderCompilerEnvironment & OutEnvironment) const inline
Calls the function ptr for the shader type on the given environment.
Parameters
Environment - shader compile environment to modify
Definition at line 455 of file VertexFactory.h.
References TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Add(), GetShaderFilename(), GetShaderFwdFilename(), IncludesFwdShaderFile(), FShaderCompilerEnvironment::IncludeVirtualPathToContentsMap, FShaderCompilerEnvironment::SetDefine(), and TEXT.
ShouldCache()
bool FVertexFactoryType::ShouldCache (const FVertexFactoryShaderPermutationParameters & Parameters) const inline
Should we cache the material's shadertype on this platform with this vertex factory?
Definition at line 445 of file VertexFactory.h.
References ShouldCacheRef.
SupportsCachingMeshDrawCommands()
bool FVertexFactoryType::SupportsCachingMeshDrawCommands () const inline
Definition at line 410 of file VertexFactory.h.
References HasFlags(), and SupportsCachingMeshDrawCommands.
SupportsComputeShading()
bool FVertexFactoryType::SupportsComputeShading () const inline
Definition at line 420 of file VertexFactory.h.
References HasFlags(), and SupportsComputeShading.
SupportsDynamicLighting()
bool FVertexFactoryType::SupportsDynamicLighting () const inline
Definition at line 407 of file VertexFactory.h.
References HasFlags(), and SupportsDynamicLighting.
SupportsGPUSkinPassThrough()
bool FVertexFactoryType::SupportsGPUSkinPassThrough () const inline
Definition at line 419 of file VertexFactory.h.
References HasFlags(), and SupportsGPUSkinPassThrough.
SupportsLandscape()
bool FVertexFactoryType::SupportsLandscape () const inline
Definition at line 422 of file VertexFactory.h.
References HasFlags(), and SupportsLandscape.
SupportsLightmapBaking()
bool FVertexFactoryType::SupportsLightmapBaking () const inline
Definition at line 416 of file VertexFactory.h.
References HasFlags(), and SupportsLightmapBaking.
SupportsLumenMeshCards()
bool FVertexFactoryType::SupportsLumenMeshCards () const inline
Definition at line 421 of file VertexFactory.h.
References HasFlags(), and SupportsLumenMeshCards.
SupportsManualVertexFetch()
bool FVertexFactoryType::SupportsManualVertexFetch (ERHIFeatureLevel::Type InFeatureLevel) const inline
Definition at line 426 of file VertexFactory.h.
References CheckManualVertexFetchSupport(), HasFlags(), and SupportsManualVertexFetch.
Referenced by FStaticMeshComponentHelper::CollectPSOPrecacheDataImpl(), and FVertexFactory::SupportsManualVertexFetch().
SupportsNaniteRendering()
bool FVertexFactoryType::SupportsNaniteRendering () const inline
Definition at line 412 of file VertexFactory.h.
References HasFlags(), and SupportsNaniteRendering.
SupportsNullPixelShader()
bool FVertexFactoryType::SupportsNullPixelShader () const inline
Definition at line 418 of file VertexFactory.h.
References DoesNotSupportNullPixelShader, and HasFlags().
Referenced by FVertexFactory::SupportsNullPixelShader().
SupportsPositionOnly()
bool FVertexFactoryType::SupportsPositionOnly () const inline
Definition at line 409 of file VertexFactory.h.
References HasFlags(), and SupportsPositionOnly.
SupportsPrecisePrevWorldPos()
bool FVertexFactoryType::SupportsPrecisePrevWorldPos () const inline
Definition at line 408 of file VertexFactory.h.
References HasFlags(), and SupportsPrecisePrevWorldPos.
SupportsPrimitiveIdStream()
bool FVertexFactoryType::SupportsPrimitiveIdStream () const inline
Definition at line 411 of file VertexFactory.h.
References HasFlags(), and SupportsPrimitiveIdStream.
Referenced by FVertexFactory::SupportsGPUScene().
SupportsPSOPrecaching()
bool FVertexFactoryType::SupportsPSOPrecaching () const inline
Definition at line 417 of file VertexFactory.h.
References HasFlags(), and SupportsPSOPrecaching.
SupportsRayTracing()
bool FVertexFactoryType::SupportsRayTracing () const inline
Definition at line 413 of file VertexFactory.h.
References HasFlags(), and SupportsRayTracing.
SupportsRayTracingDynamicGeometry()
bool FVertexFactoryType::SupportsRayTracingDynamicGeometry () const inline
Definition at line 414 of file VertexFactory.h.
References HasFlags(), and SupportsRayTracingDynamicGeometry.
SupportsRayTracingProceduralPrimitive()
bool FVertexFactoryType::SupportsRayTracingProceduralPrimitive () const inline
Definition at line 415 of file VertexFactory.h.
References HasFlags(), and SupportsRayTracingProceduralPrimitive.
SupportsStaticLighting()
bool FVertexFactoryType::SupportsStaticLighting () const inline
Definition at line 406 of file VertexFactory.h.
References HasFlags(), and SupportsStaticLighting.
SupportsTriangleSorting()
bool FVertexFactoryType::SupportsTriangleSorting () const inline
Definition at line 424 of file VertexFactory.h.
References HasFlags(), and SupportsTriangleSorting.
Referenced by FVertexFactory::SupportsTriangleSorting().
UpdateReferencedUniformBufferNames()
RENDERCORE_API void FVertexFactoryType::UpdateReferencedUniformBufferNames (const TMap< FString, TArray< const TCHAR * > > & ShaderFileToUniformBufferVariables)
ValidateCompiledResult()
void FVertexFactoryType::ValidateCompiledResult (EShaderPlatform Platform, const FShaderParameterMap & ParameterMap, TArray< FString > & OutErrors) const inline
Definition at line 477 of file VertexFactory.h.
References Platform.
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FVertexFactoryType * Type) friend
Definition at line 434 of file VertexFactory.h.
References FVertexFactoryType(), and GetTypeHash.
Referenced by GetTypeHash.
Field Documentation
bInitializedSerializationHistory
bool FVertexFactoryType::bInitializedSerializationHistory static private
Tracks whether serialization history for all shader types has been initialized.
Definition at line 504 of file VertexFactory.h.
ConstructParameters
ConstructParametersType FVertexFactoryType::ConstructParameters private
Definition at line 512 of file VertexFactory.h.
Referenced by CreateShaderParameters().
Flags
EVertexFactoryFlags FVertexFactoryType::Flags private
Definition at line 511 of file VertexFactory.h.
Referenced by GetFlags(), and HasFlags().
GetParameterTypeElementShaderBindings
GetParameterTypeElementShaderBindingsType FVertexFactoryType::GetParameterTypeElementShaderBindings private
Definition at line 514 of file VertexFactory.h.
GetParameterTypeLayout
GetParameterTypeLayoutType FVertexFactoryType::GetParameterTypeLayout private
Definition at line 513 of file VertexFactory.h.
Referenced by GetShaderParameterLayout().
GetPSOPrecacheVertexFetchElements
GetPSOPrecacheVertexFetchElementsType FVertexFactoryType::GetPSOPrecacheVertexFetchElements private
Definition at line 515 of file VertexFactory.h.
Referenced by GetShaderPSOPrecacheVertexFetchElements().
GlobalListLink
TLinkedList<FVertexFactoryType*> FVertexFactoryType::GlobalListLink private
Definition at line 522 of file VertexFactory.h.
HashedName
FHashedName FVertexFactoryType::HashedName private
Definition at line 510 of file VertexFactory.h.
Referenced by GetHashedName().
ModifyCompilationEnvironmentRef
ModifyCompilationEnvironmentType FVertexFactoryType::ModifyCompilationEnvironmentRef private
Definition at line 518 of file VertexFactory.h.
Name
const TCHAR* FVertexFactoryType::Name private
Definition at line 506 of file VertexFactory.h.
Referenced by GetName().
NumVertexFactories
RENDERCORE_API uint32 FVertexFactoryType::NumVertexFactories static private
Definition at line 501 of file VertexFactory.h.
Referenced by GetNumVertexFactoryTypes().
ReferencedUniformBuffers
TSet<const FShaderParametersMetadata*> FVertexFactoryType::ReferencedUniformBuffers private
Cache of referenced uniform buffer structs.
These are derived from source files so they need to be flushed when editing and recompiling shaders on the fly. FShaderType::Initialize will add the referenced uniform buffers, but this set may be updated by FlushShaderFileCache
Definition at line 530 of file VertexFactory.h.
Referenced by GetReferencedUniformBuffers().
ShaderFilename
const TCHAR* FVertexFactoryType::ShaderFilename private
Definition at line 507 of file VertexFactory.h.
Referenced by GetShaderFilename().
ShaderFwdFilename
FString FVertexFactoryType::ShaderFwdFilename private
Definition at line 508 of file VertexFactory.h.
Referenced by GetShaderFwdFilename().
ShouldCacheRef
ShouldCacheType FVertexFactoryType::ShouldCacheRef private
Definition at line 516 of file VertexFactory.h.
Referenced by ShouldCache().
TypeName
FName FVertexFactoryType::TypeName private
Definition at line 509 of file VertexFactory.h.
Referenced by GetFName().
ValidateCompiledResultRef
ValidateCompiledResultType FVertexFactoryType::ValidateCompiledResultRef private
Definition at line 519 of file VertexFactory.h.
The documentation for this class was generated from the following file:
Runtime/RenderCore/Public/VertexFactory.h