Unreal Engine 5.6 C++ API: TWorldPartitionHandle< Impl > Class Template Reference
TWorldPartitionHandle< Impl > Class Template Reference
#include "WorldPartitionHandle.h"
Data Structures
struct TActorDescContainerCollectionDeprecated
Public Member Functions
FORCEINLINE TWorldPartitionHandle ()
FORCEINLINE TWorldPartitionHandle (const TWorldPartitionHandle &Other)
FORCEINLINE TWorldPartitionHandle (FWorldPartitionActorDescInstance *InActorDescInstance)
template<class U>
FORCEINLINE TWorldPartitionHandle (TActorDescContainerCollection< U > *ContainerCollection, const FGuid &ActorGuid)
template<class U>
FORCEINLINE TWorldPartitionHandle (TActorDescContainerInstanceCollection< U > *ContainerCollection, const FGuid &ActorGuid)
FORCEINLINE TWorldPartitionHandle (TUniquePtr< FWorldPartitionActorDescInstance > *InActorDescInstance)
FORCEINLINE TWorldPartitionHandle (TWorldPartitionHandle &&Other)
template<typename T>
FORCEINLINE TWorldPartitionHandle (TWorldPartitionHandle< T > &&Other)
FORCEINLINE TWorldPartitionHandle (UActorDescContainerInstance *InContainerInstance, const FGuid &InActorGuid)
FORCEINLINE ~TWorldPartitionHandle ()
const FGuid ActorDescInstance (nullptr)
FORCEINLINE void DecRefCount ()
FORCEINLINE AActor * GetActor () const
FORCEINLINE FWorldPartitionActorDescInstance * GetInstance () const
FORCEINLINE void IncRefCount ()
FORCEINLINE bool IsLoaded () const
FORCEINLINE bool IsValid () const
FORCEINLINE bool operator!= (const TWorldPartitionHandle &Other) const
template<typename T>
FORCEINLINE bool operator!= (const TWorldPartitionHandle< T > &Other) const
FORCEINLINE FWorldPartitionActorDescInstance * operator* () const
FORCEINLINE FWorldPartitionActorDescInstance * operator-> () const
FORCEINLINE TWorldPartitionHandle & operator= (const TWorldPartitionHandle &Other)
template<typename T>
FORCEINLINE TWorldPartitionHandle< Impl > & operator= (const TWorldPartitionHandle< T > &Other)
FORCEINLINE TWorldPartitionHandle< Impl > & operator= (TWorldPartitionHandle &&Other)
template<typename T>
FORCEINLINE TWorldPartitionHandle< Impl > & operator= (TWorldPartitionHandle< T > &&Other)
FORCEINLINE bool operator== (const TWorldPartitionHandle &Other) const
template<typename T>
FORCEINLINE bool operator== (const TWorldPartitionHandle< T > &Other) const
FORCEINLINE void Reset ()
FORCEINLINE TWorldPartitionHandle< FWorldPartitionHandleImpl > ToHandle () const
FORCEINLINE TWorldPartitionHandle< FWorldPartitionReferenceImpl > ToReference () const
UE_DEPRECATED (5.4, "Use FActorDescContainerInstance version") FORCEINLINE TWorldPartitionHandle(UActorDescContainer *InContainer
UE_DEPRECATED (5.4, "Use FWorldPartitionActorDescInstance version") FORCEINLINE TWorldPartitionHandle(TUniquePtr< FWorldPartitionActorDesc > *InActorDesc)
UE_DEPRECATED (5.4, "Use GetInstance instead") FORCEINLINE FWorldPartitionActorDesc *Get() const
Data Fields
TUniquePtr< FWorldPartitionActorDescInstance > * ActorDescInstance
const FGuid & ActorGuid: ContainerInstance(nullptr)
TWeakObjectPtr< UActorDescContainerInstance > ContainerInstance
Friends
FORCEINLINE uint32 GetTypeHash (const TWorldPartitionHandle< Impl > &HandleBase)
Detailed Description
template<typename Impl>
class TWorldPartitionHandle< Impl >
Definition at line 111 of file WorldPartitionHandle.h.
Constructor & Destructor Documentation
TWorldPartitionHandle() [1/9]
template<typename Impl> FORCEINLINE TWorldPartitionHandle< Impl >::TWorldPartitionHandle () inline
Definition at line 114 of file WorldPartitionHandle.h.
TWorldPartitionHandle() [2/9]
template<typename Impl> FORCEINLINE TWorldPartitionHandle< Impl >::TWorldPartitionHandle (TUniquePtr< FWorldPartitionActorDescInstance > * InActorDescInstance) inline
Definition at line 119 of file WorldPartitionHandle.h.
TWorldPartitionHandle() [3/9]
template<typename Impl> FORCEINLINE TWorldPartitionHandle< Impl >::TWorldPartitionHandle (FWorldPartitionActorDescInstance * InActorDescInstance) inline
Definition at line 129 of file WorldPartitionHandle.h.
TWorldPartitionHandle() [4/9]
template<typename Impl> FORCEINLINE TWorldPartitionHandle< Impl >::TWorldPartitionHandle (UActorDescContainerInstance * InContainerInstance, const FGuid & InActorGuid) inline
Definition at line 144 of file WorldPartitionHandle.h.
TWorldPartitionHandle() [5/9]
template<typename Impl> template<class U> FORCEINLINE TWorldPartitionHandle< Impl >::TWorldPartitionHandle (TActorDescContainerInstanceCollection< U > * ContainerCollection, const FGuid & ActorGuid) inline
Definition at line 155 of file WorldPartitionHandle.h.
TWorldPartitionHandle() [6/9]
template<typename Impl> template<class U> FORCEINLINE TWorldPartitionHandle< Impl >::TWorldPartitionHandle (TActorDescContainerCollection< U > * ContainerCollection, const FGuid & ActorGuid) inline
Definition at line 192 of file WorldPartitionHandle.h.
TWorldPartitionHandle() [7/9]
template<typename Impl> FORCEINLINE TWorldPartitionHandle< Impl >::TWorldPartitionHandle (const TWorldPartitionHandle< Impl > & Other) inline
Definition at line 199 of file WorldPartitionHandle.h.
TWorldPartitionHandle() [8/9]
template<typename Impl> FORCEINLINE TWorldPartitionHandle< Impl >::TWorldPartitionHandle (TWorldPartitionHandle< Impl > && Other) inline
Definition at line 206 of file WorldPartitionHandle.h.
TWorldPartitionHandle() [9/9]
template<typename Impl> template<typename T> FORCEINLINE TWorldPartitionHandle< Impl >::TWorldPartitionHandle (TWorldPartitionHandle< T > && Other) inline
Definition at line 224 of file WorldPartitionHandle.h.
~TWorldPartitionHandle()
template<typename Impl> FORCEINLINE TWorldPartitionHandle< Impl >::~TWorldPartitionHandle () inline
Definition at line 230 of file WorldPartitionHandle.h.
Member Function Documentation
ActorDescInstance()
template<typename Impl> const FGuid TWorldPartitionHandle< Impl >::ActorDescInstance (nullptr) inline
Definition at line 180 of file WorldPartitionHandle.h.
DecRefCount()
template<typename Impl> FORCEINLINE void TWorldPartitionHandle< Impl >::DecRefCount () inline
Definition at line 407 of file WorldPartitionHandle.h.
Referenced by TWorldPartitionHandle< FWorldPartitionHandleImpl >::~TWorldPartitionHandle(), TWorldPartitionHandle< FWorldPartitionHandleImpl >::operator=(), TWorldPartitionHandle< FWorldPartitionHandleImpl >::operator=(), TWorldPartitionHandle< FWorldPartitionHandleImpl >::operator=(), TWorldPartitionHandle< FWorldPartitionHandleImpl >::operator=(), and TWorldPartitionHandle< FWorldPartitionHandleImpl >::Reset().
GetActor()
template<typename Impl> FORCEINLINE AActor * TWorldPartitionHandle< Impl >::GetActor () const inline
Definition at line 346 of file WorldPartitionHandle.h.
GetInstance()
template<typename Impl> FORCEINLINE FWorldPartitionActorDescInstance * TWorldPartitionHandle< Impl >::GetInstance () const inline
Definition at line 331 of file WorldPartitionHandle.h.
Referenced by TWorldPartitionHandle< FWorldPartitionHandleImpl >::operator*(), TWorldPartitionHandle< FWorldPartitionHandleImpl >::operator->(), and TWorldPartitionHandle< FWorldPartitionHandleImpl >::operator==().
IncRefCount()
template<typename Impl> FORCEINLINE void TWorldPartitionHandle< Impl >::IncRefCount () inline
Definition at line 402 of file WorldPartitionHandle.h.
Referenced by TWorldPartitionHandle< FWorldPartitionHandleImpl >::TWorldPartitionHandle(), TWorldPartitionHandle< FWorldPartitionHandleImpl >::TWorldPartitionHandle(), TWorldPartitionHandle< FWorldPartitionHandleImpl >::TWorldPartitionHandle(), TWorldPartitionHandle< FWorldPartitionHandleImpl >::TWorldPartitionHandle(), TWorldPartitionHandle< FWorldPartitionHandleImpl >::operator=(), TWorldPartitionHandle< FWorldPartitionHandleImpl >::operator=(), and TWorldPartitionHandle< FWorldPartitionHandleImpl >::operator=().
IsLoaded()
template<typename Impl> FORCEINLINE bool TWorldPartitionHandle< Impl >::IsLoaded () const inline
Definition at line 341 of file WorldPartitionHandle.h.
Referenced by FWorldPartitionHandlePinRefScope::FWorldPartitionHandlePinRefScope().
IsValid()
template<typename Impl> FORCEINLINE bool TWorldPartitionHandle< Impl >::IsValid () const inline
Definition at line 336 of file WorldPartitionHandle.h.
Referenced by TWorldPartitionHandle< FWorldPartitionHandleImpl >::TWorldPartitionHandle(), TWorldPartitionHandle< FWorldPartitionHandleImpl >::TWorldPartitionHandle(), TWorldPartitionHandle< FWorldPartitionHandleImpl >::TWorldPartitionHandle(), TWorldPartitionHandle< FWorldPartitionHandleImpl >::TWorldPartitionHandle(), TWorldPartitionHandle< FWorldPartitionHandleImpl >::~TWorldPartitionHandle(), TWorldPartitionHandle< FWorldPartitionHandleImpl >::GetActor(), TWorldPartitionHandle< FWorldPartitionHandleImpl >::GetInstance(), TWorldPartitionHandle< FWorldPartitionHandleImpl >::IsLoaded(), TWorldPartitionHandle< FWorldPartitionHandleImpl >::operator=(), TWorldPartitionHandle< FWorldPartitionHandleImpl >::operator=(), TWorldPartitionHandle< FWorldPartitionHandleImpl >::operator=(), TWorldPartitionHandle< FWorldPartitionHandleImpl >::operator=(), and TWorldPartitionHandle< FWorldPartitionHandleImpl >::Reset().
operator!=() [1/2]
template<typename Impl> FORCEINLINE bool TWorldPartitionHandle< Impl >::operator!= (const TWorldPartitionHandle< Impl > & Other) const inline
Definition at line 383 of file WorldPartitionHandle.h.
operator!=() [2/2]
template<typename Impl> template<typename T> FORCEINLINE bool TWorldPartitionHandle< Impl >::operator!= (const TWorldPartitionHandle< T > & Other) const inline
Definition at line 396 of file WorldPartitionHandle.h.
operator*()
template<typename Impl> FORCEINLINE FWorldPartitionActorDescInstance * TWorldPartitionHandle< Impl >::operator* () const inline
Definition at line 326 of file WorldPartitionHandle.h.
operator->()
template<typename Impl> FORCEINLINE FWorldPartitionActorDescInstance * TWorldPartitionHandle< Impl >::operator-> () const inline
Definition at line 321 of file WorldPartitionHandle.h.
operator=() [1/4]
template<typename Impl> FORCEINLINE TWorldPartitionHandle & TWorldPartitionHandle< Impl >::operator= (const TWorldPartitionHandle< Impl > & Other) inline
Definition at line 238 of file WorldPartitionHandle.h.
operator=() [2/4]
template<typename Impl> template<typename T> FORCEINLINE TWorldPartitionHandle< Impl > & TWorldPartitionHandle< Impl >::operator= (const TWorldPartitionHandle< T > & Other) inline
Definition at line 280 of file WorldPartitionHandle.h.
operator=() [3/4]
template<typename Impl> FORCEINLINE TWorldPartitionHandle< Impl > & TWorldPartitionHandle< Impl >::operator= (TWorldPartitionHandle< Impl > && Other) inline
Definition at line 259 of file WorldPartitionHandle.h.
operator=() [4/4]
template<typename Impl> template<typename T> FORCEINLINE TWorldPartitionHandle< Impl > & TWorldPartitionHandle< Impl >::operator= (TWorldPartitionHandle< T > && Other) inline
Definition at line 299 of file WorldPartitionHandle.h.
operator==() [1/2]
template<typename Impl> FORCEINLINE bool TWorldPartitionHandle< Impl >::operator== (const TWorldPartitionHandle< Impl > & Other) const inline
Definition at line 378 of file WorldPartitionHandle.h.
operator==() [2/2]
template<typename Impl> template<typename T> FORCEINLINE bool TWorldPartitionHandle< Impl >::operator== (const TWorldPartitionHandle< T > & Other) const inline
Definition at line 390 of file WorldPartitionHandle.h.
Reset()
template<typename Impl> FORCEINLINE void TWorldPartitionHandle< Impl >::Reset () inline
Definition at line 362 of file WorldPartitionHandle.h.
ToHandle()
template<typename Impl> FORCEINLINE TWorldPartitionHandle< FWorldPartitionHandleImpl > TWorldPartitionHandle< Impl >::ToHandle () const inline
Definition at line 213 of file WorldPartitionHandle.h.
ToReference()
template<typename Impl> FORCEINLINE TWorldPartitionHandle< FWorldPartitionReferenceImpl > TWorldPartitionHandle< Impl >::ToReference () const inline
Definition at line 218 of file WorldPartitionHandle.h.
UE_DEPRECATED() [1/3]
template<typename Impl> TWorldPartitionHandle< Impl >::UE_DEPRECATED (5. 4, "Use FActorDescContainerInstance version")
UE_DEPRECATED() [2/3]
template<typename Impl> TWorldPartitionHandle< Impl >::UE_DEPRECATED (5. 4, "Use FWorldPartitionActorDescInstance version") inline
Definition at line 170 of file WorldPartitionHandle.h.
UE_DEPRECATED() [3/3]
template<typename Impl> TWorldPartitionHandle< Impl >::UE_DEPRECATED (5. 4, "Use GetInstance instead") const inline
Definition at line 351 of file WorldPartitionHandle.h.
Friends And Related Symbol Documentation
GetTypeHash
template<typename Impl> FORCEINLINE uint32 GetTypeHash (const TWorldPartitionHandle< Impl > & HandleBase) friend
Definition at line 373 of file WorldPartitionHandle.h.
Field Documentation
ActorDescInstance
template<typename Impl> TUniquePtr<FWorldPartitionActorDescInstance>* TWorldPartitionHandle< Impl >::ActorDescInstance
Definition at line 413 of file WorldPartitionHandle.h.
Referenced by TWorldPartitionHandle< FWorldPartitionHandleImpl >::GetTypeHash.
ActorGuid
template<typename Impl> const FGuid& TWorldPartitionHandle< Impl >::ActorGuid
Definition at line 178 of file WorldPartitionHandle.h.
ContainerInstance
template<typename Impl> TWeakObjectPtr<UActorDescContainerInstance> TWorldPartitionHandle< Impl >::ContainerInstance
Definition at line 412 of file WorldPartitionHandle.h.
The documentation for this class was generated from the following file:
Runtime/Engine/Public/WorldPartition/WorldPartitionHandle.h