Unreal Engine 5.6 C++ API: TCbBufferFactory< Type, ViewType > Class Template Reference
TCbBufferFactory< Type, ViewType > Class Template Reference
Factory functions for types derived from TCbBuffer.
#include "CompactBinary.h"
Static Public Member Functions
static Type Clone (const ViewType &Value)
Construct a value from an owned clone of its memory.
static Type Clone (const void *const Data)
Construct a value from an owned clone of its memory.
static Type MakeView (const ViewType &Value, FSharedBuffer OuterBuffer=FSharedBuffer())
Construct a value from a read-only view of its memory and its optional outer buffer.
static Type MakeView (const void *const Data, FSharedBuffer OuterBuffer=FSharedBuffer())
Construct a value from a read-only view of its memory and its optional outer buffer.
Detailed Description
template<typename Type, typename ViewType>
class TCbBufferFactory< Type, ViewType >
Factory functions for types derived from TCbBuffer.
This uses the curiously recurring template pattern to construct the correct derived type, that must inherit from TCbBuffer and this type to expose the factory functions.
Definition at line 1208 of file CompactBinary.h.
Member Function Documentation
Clone() [1/2]
template<typename Type, typename ViewType> Type TCbBufferFactory< Type, ViewType >::Clone (const ViewType & Value) inline static nodiscard
Construct a value from an owned clone of its memory.
Definition at line 1218 of file CompactBinary.h.
References MakeView(), and Value.
Clone() [2/2]
template<typename Type, typename ViewType> Type TCbBufferFactory< Type, ViewType >::Clone (const void *const Data) inline static nodiscard
Construct a value from an owned clone of its memory.
Definition at line 1212 of file CompactBinary.h.
References Clone().
Referenced by Clone().
MakeView() [1/2]
template<typename Type, typename ViewType> Type TCbBufferFactory< Type, ViewType >::MakeView (const ViewType & Value, FSharedBuffer OuterBuffer = FSharedBuffer()) inline static nodiscard
Construct a value from a read-only view of its memory and its optional outer buffer.
Definition at line 1232 of file CompactBinary.h.
References MoveTemp(), and Value.
MakeView() [2/2]
template<typename Type, typename ViewType> Type TCbBufferFactory< Type, ViewType >::MakeView (const void *const Data, FSharedBuffer OuterBuffer = FSharedBuffer()) inline static nodiscard
Construct a value from a read-only view of its memory and its optional outer buffer.
Definition at line 1226 of file CompactBinary.h.
References MakeView(), and MoveTemp().
Referenced by Clone(), and MakeView().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Serialization/CompactBinary.h