Unreal Engine 5.6 C++ API: UE::Geometry::FNonManifoldMappingSupport Class Reference
UE::Geometry::FNonManifoldMappingSupport Class Reference
#include "NonManifoldMappingSupport.h"
Public Member Functions
GEOMETRYCORE_API FNonManifoldMappingSupport (const FDynamicMesh3 &Mesh)
GEOMETRYCORE_API int32 GetOriginalNonManifoldVertexID (const int32 vid) const
bool IsNonManifoldVertexID (const int32 vid) const
GEOMETRYCORE_API bool IsNonManifoldVertexInSource () const
GEOMETRYCORE_API void Reset (const FDynamicMesh3 &Mesh)
Update the support for a new DynamicMesh.
Static Public Member Functions
static GEOMETRYCORE_API bool AttachNonManifoldVertexMappingData (const TArray< int32 > &VertexToNonManifoldVertexIDMap, FDynamicMesh3 &MeshInOut)
static void RemoveAllNonManifoldMappingData (FDynamicMesh3 &MeshInOut)
static GEOMETRYCORE_API void RemoveNonManifoldVertexMappingData (FDynamicMesh3 &MeshInOut)
Static Public Attributes
static GEOMETRYCORE_API FName NonManifoldMeshVIDsAttrName
Protected Attributes
const FDynamicMesh3 * DynamicMesh = nullptr
const FNonManifoldSourceVertexIdAttribute * NonManifoldSrcVIDsAttribute = nullptr
Detailed Description
Definition at line 35 of file NonManifoldMappingSupport.h.
Constructor & Destructor Documentation
FNonManifoldMappingSupport()
GEOMETRYCORE_API UE::Geometry::FNonManifoldMappingSupport::FNonManifoldMappingSupport (const FDynamicMesh3 & Mesh)
References UE::Geometry::Mesh.
Member Function Documentation
AttachNonManifoldVertexMappingData()
GEOMETRYCORE_API bool UE::Geometry::FNonManifoldMappingSupport::AttachNonManifoldVertexMappingData (const TArray< int32 > & VertexToNonManifoldVertexIDMap, FDynamicMesh3 & MeshInOut) static
GetOriginalNonManifoldVertexID()
GEOMETRYCORE_API int32 UE::Geometry::FNonManifoldMappingSupport::GetOriginalNonManifoldVertexID (const int32 vid) const
Referenced by IsNonManifoldVertexID().
IsNonManifoldVertexID()
bool UE::Geometry::FNonManifoldMappingSupport::IsNonManifoldVertexID (const int32 vid) const inline
Definition at line 58 of file NonManifoldMappingSupport.h.
References GetOriginalNonManifoldVertexID().
IsNonManifoldVertexInSource()
GEOMETRYCORE_API bool UE::Geometry::FNonManifoldMappingSupport::IsNonManifoldVertexInSource () const
RemoveAllNonManifoldMappingData()
void UE::Geometry::FNonManifoldMappingSupport::RemoveAllNonManifoldMappingData (FDynamicMesh3 & MeshInOut) inline static
Definition at line 100 of file NonManifoldMappingSupport.h.
References RemoveNonManifoldVertexMappingData().
RemoveNonManifoldVertexMappingData()
GEOMETRYCORE_API void UE::Geometry::FNonManifoldMappingSupport::RemoveNonManifoldVertexMappingData (FDynamicMesh3 & MeshInOut) static
Referenced by RemoveAllNonManifoldMappingData().
Reset()
GEOMETRYCORE_API void UE::Geometry::FNonManifoldMappingSupport::Reset (const FDynamicMesh3 & Mesh)
Update the support for a new DynamicMesh.
References UE::Geometry::Mesh.
Field Documentation
DynamicMesh
const FDynamicMesh3* UE::Geometry::FNonManifoldMappingSupport::DynamicMesh = nullptr protected
Definition at line 114 of file NonManifoldMappingSupport.h.
NonManifoldMeshVIDsAttrName
GEOMETRYCORE_API FName UE::Geometry::FNonManifoldMappingSupport::NonManifoldMeshVIDsAttrName static
Definition at line 108 of file NonManifoldMappingSupport.h.
NonManifoldSrcVIDsAttribute
const FNonManifoldSourceVertexIdAttribute* UE::Geometry::FNonManifoldMappingSupport::NonManifoldSrcVIDsAttribute = nullptr protected
Definition at line 113 of file NonManifoldMappingSupport.h.
The documentation for this class was generated from the following file:
Runtime/GeometryCore/Public/DynamicMesh/NonManifoldMappingSupport.h