Unreal Engine 5.6 C++ API: Metasound::IReceiver Class Reference
Metasound::IReceiver Class Reference
#include "MetasoundRouter.h"
Public Member Functions
IReceiver (TSharedPtr< IDataChannel, ESPMode::ThreadSafe > InDataChannel, FName DataType)
virtual METASOUNDFRONTEND_API ~IReceiver ()
Public Member Functions inherited from Metasound::IDataTransmissionBase
IDataTransmissionBase ()=delete
IDataTransmissionBase (FName InDataType)
virtual ~IDataTransmissionBase ()=default
template<typename TSenderImplementation>
bool CheckType () const
template<typename TSenderImplementation>
TSenderImplementation & GetAs ()
template<typename TSenderImplementation>
const TSenderImplementation & GetAs () const
FName GetDataType () const
Protected Attributes
TSharedPtr< IDataChannel, ESPMode::ThreadSafe > DataChannel
Protected Attributes inherited from Metasound::IDataTransmissionBase
FName DataType
Detailed Description
Definition at line 231 of file MetasoundRouter.h.
Constructor & Destructor Documentation
IReceiver()
Metasound::IReceiver::IReceiver (TSharedPtr< IDataChannel, ESPMode::ThreadSafe > InDataChannel, FName DataType) inline
Definition at line 234 of file MetasoundRouter.h.
References Metasound::IDataTransmissionBase::IDataTransmissionBase(), DataChannel, and Metasound::IDataTransmissionBase::DataType.
Referenced by Metasound::TAudioReceiver< TDataType >::TAudioReceiver(), and Metasound::TReceiver< TDataType >::TReceiver().
~IReceiver()
virtual METASOUNDFRONTEND_API Metasound::IReceiver::~IReceiver () virtual
References UE_API.
Field Documentation
DataChannel
TSharedPtr<IDataChannel, ESPMode::ThreadSafe> Metasound::IReceiver::DataChannel protected
Definition at line 243 of file MetasoundRouter.h.
Referenced by IReceiver(), Metasound::TReceiver< TDataType >::CanPop(), Metasound::TAudioReceiver< TDataType >::Pop(), and Metasound::TReceiver< TDataType >::Pop().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/Metasound/Source/MetasoundFrontend/Public/MetasoundRouter.h