Unreal Engine 5.6 C++ API: FSlateDefaultInputMapping Class Reference
FSlateDefaultInputMapping Class Reference
#include "SlateApplication.h"
Public Member Functions
virtual FInputDeviceId GetInputDeviceIdForKeyboard () const override
virtual FInputDeviceId GetInputDeviceIdForMouse () const override
virtual int32 GetUserIndexForController (int32 ControllerId) const override
virtual TOptional< int32 > GetUserIndexForController (int32 ControllerId, FKey InKey) const override
virtual int32 GetUserIndexForKeyboard () const override
virtual int32 GetUserIndexForMouse () const override
Public Member Functions inherited from ISlateInputManager
virtual ~ISlateInputManager ()=default
virtual TOptional< int32 > GetUserIndexForInputDevice (FInputDeviceId InputDeviceId) const
virtual TOptional< int32 > GetUserIndexForPlatformUser (FPlatformUserId PlatformUser) const
Detailed Description
Definition at line 147 of file SlateApplication.h.
Member Function Documentation
GetInputDeviceIdForKeyboard()
virtual FInputDeviceId FSlateDefaultInputMapping::GetInputDeviceIdForKeyboard () const inline override virtual
Implements ISlateInputManager.
Definition at line 158 of file SlateApplication.h.
References IPlatformInputDeviceMapper::Get(), and IPlatformInputDeviceMapper::GetDefaultInputDevice().
GetInputDeviceIdForMouse()
virtual FInputDeviceId FSlateDefaultInputMapping::GetInputDeviceIdForMouse () const inline override virtual
Implements ISlateInputManager.
Definition at line 153 of file SlateApplication.h.
References IPlatformInputDeviceMapper::Get(), and IPlatformInputDeviceMapper::GetDefaultInputDevice().
GetUserIndexForController() [1/2]
virtual int32 FSlateDefaultInputMapping::GetUserIndexForController (int32 ControllerId) const inline override virtual
Reimplemented from ISlateInputManager.
Definition at line 163 of file SlateApplication.h.
GetUserIndexForController() [2/2]
virtual TOptional< int32 > FSlateDefaultInputMapping::GetUserIndexForController (int32 ControllerId, FKey InKey) const inline override virtual
Implements ISlateInputManager.
Definition at line 164 of file SlateApplication.h.
References GetUserIndexForController().
Referenced by GetUserIndexForController().
GetUserIndexForKeyboard()
virtual int32 FSlateDefaultInputMapping::GetUserIndexForKeyboard () const inline override virtual
Implements ISlateInputManager.
Definition at line 151 of file SlateApplication.h.
GetUserIndexForMouse()
virtual int32 FSlateDefaultInputMapping::GetUserIndexForMouse () const inline override virtual
Implements ISlateInputManager.
Definition at line 150 of file SlateApplication.h.
The documentation for this class was generated from the following file:
Runtime/Slate/Public/Framework/Application/SlateApplication.h