Unreal Engine 5.6 C++ API: TMeshElementContainer< ElementIDType >::TElementIDs::TConstIterator Class Reference
TMeshElementContainer< ElementIDType >::TElementIDs::TConstIterator Class Reference
#include "MeshElementContainer.h"
Public Member Functions
FORCEINLINE TConstIterator (TConstSetBitIterator<> &&It)
FORCEINLINE ElementIDType operator* () const
FORCEINLINE TConstIterator & operator++ ()
Private Attributes
TConstSetBitIterator Iterator
Friends
FORCEINLINE bool operator!= (const TConstIterator &Lhs, const TConstIterator &Rhs)
FORCEINLINE bool operator== (const TConstIterator &Lhs, const TConstIterator &Rhs)
Detailed Description
template<typename ElementIDType>
class TMeshElementContainer< ElementIDType >::TElementIDs::TConstIterator
Definition at line 306 of file MeshElementContainer.h.
Constructor & Destructor Documentation
TConstIterator()
template<typename ElementIDType> FORCEINLINE TMeshElementContainer< ElementIDType >::TElementIDs::TConstIterator::TConstIterator (TConstSetBitIterator<> && It) inline explicit
Definition at line 309 of file MeshElementContainer.h.
References FORCEINLINE, Iterator, and MoveTemp().
Referenced by operator!=, operator++(), and operator==.
Member Function Documentation
operator*()
template<typename ElementIDType> FORCEINLINE ElementIDType TMeshElementContainer< ElementIDType >::TElementIDs::TConstIterator::operator* () const inline
Definition at line 319 of file MeshElementContainer.h.
References FORCEINLINE, INDEX_NONE, and Iterator.
operator++()
template<typename ElementIDType> FORCEINLINE TConstIterator & TMeshElementContainer< ElementIDType >::TElementIDs::TConstIterator::operator++ () inline
Definition at line 313 of file MeshElementContainer.h.
References TConstIterator(), FORCEINLINE, and Iterator.
Friends And Related Symbol Documentation
operator!=
template<typename ElementIDType> FORCEINLINE bool operator!= (const TConstIterator & Lhs, const TConstIterator & Rhs) friend
Definition at line 329 of file MeshElementContainer.h.
References TConstIterator(), FORCEINLINE, and Iterator.
operator==
template<typename ElementIDType> FORCEINLINE bool operator== (const TConstIterator & Lhs, const TConstIterator & Rhs) friend
Definition at line 324 of file MeshElementContainer.h.
References TConstIterator(), FORCEINLINE, and Iterator.
Field Documentation
Iterator
template<typename ElementIDType> TConstSetBitIterator TMeshElementContainer< ElementIDType >::TElementIDs::TConstIterator::Iterator private
Definition at line 335 of file MeshElementContainer.h.
Referenced by TConstIterator(), operator!=, operator*(), operator++(), and operator==.
The documentation for this class was generated from the following file:
Runtime/MeshDescription/Public/MeshElementContainer.h