Unreal Engine 5.6 C++ API: FCbValue Class Reference
FCbValue Class Reference
A type that provides unchecked access to compact binary values.
#include "CompactBinaryValue.h"
Public Member Functions
FCbValue (ECbFieldType Type, const void *Value)
FCbArrayView AsArrayView () const
FORCEINLINE FIoHash AsAttachment () const
FMemoryView AsBinary () const
FORCEINLINE FIoHash AsBinaryAttachment () const
bool AsBool () const
FCbCustomById AsCustomById () const
FCbCustomByName AsCustomByName () const
int64 AsDateTimeTicks () const
float AsFloat32 () const
double AsFloat64 () const
FIoHash AsHash () const
uint64 AsInteger (UE::CompactBinary::Private::FIntegerParams Params, ECbFieldError *OutError=nullptr, uint64 Default=0) const
Access as an integer, with both positive and negative values returned as unsigned.
int64 AsIntegerNegative () const
uint64 AsIntegerPositive () const
FORCEINLINE FIoHash AsObjectAttachment () const
FCbObjectId AsObjectId () const
FCbObjectView AsObjectView () const
FUtf8StringView AsString (ECbFieldError *OutError=nullptr, FUtf8StringView Default=FUtf8StringView()) const
Access as a string.
int64 AsTimeSpanTicks () const
FGuid AsUuid () const
FORCEINLINE const void * GetData () const
FORCEINLINE ECbFieldType GetType () const
Private Attributes
const void * Data
ECbFieldType Type
Detailed Description
A type that provides unchecked access to compact binary values.
The main purpose of the type is to efficiently switch on field type. For every other use case, prefer to use the field, array, and object types directly. The accessors here do not check the type before reading the value, which means they can read out of bounds even on a valid compact binary value if the wrong accessor is used.
Definition at line 22 of file CompactBinaryValue.h.
Constructor & Destructor Documentation
FCbValue()
FORCEINLINE FCbValue::FCbValue (ECbFieldType Type, const void * Value)
Definition at line 83 of file CompactBinaryValue.h.
References Data, FORCEINLINE, and Type.
Member Function Documentation
AsArrayView()
FORCEINLINE FCbArrayView FCbValue::AsArrayView () const
Definition at line 94 of file CompactBinaryValue.h.
References FORCEINLINE.
AsAttachment()
FORCEINLINE FIoHash FCbValue::AsAttachment () const inline
Definition at line 51 of file CompactBinaryValue.h.
References AsHash(), and FORCEINLINE.
AsBinary()
FORCEINLINE FMemoryView FCbValue::AsBinary () const
Definition at line 99 of file CompactBinaryValue.h.
References Bytes, Data, FORCEINLINE, MakeMemoryView(), and ReadVarUInt().
AsBinaryAttachment()
FORCEINLINE FIoHash FCbValue::AsBinaryAttachment () const inline
Definition at line 50 of file CompactBinaryValue.h.
References AsHash(), and FORCEINLINE.
AsBool()
FORCEINLINE bool FCbValue::AsBool () const
Definition at line 172 of file CompactBinaryValue.h.
References FORCEINLINE, and Type.
AsCustomById()
FORCEINLINE FCbCustomById FCbValue::AsCustomById () const
Definition at line 207 of file CompactBinaryValue.h.
References Bytes, Data, DataSize, FORCEINLINE, MakeMemoryView(), ReadVarUInt(), and Value.
AsCustomByName()
FORCEINLINE FCbCustomByName FCbValue::AsCustomByName () const
Definition at line 221 of file CompactBinaryValue.h.
References Bytes, Data, DataSize, FORCEINLINE, MakeMemoryView(), ReadVarUInt(), and Value.
AsDateTimeTicks()
FORCEINLINE int64 FCbValue::AsDateTimeTicks () const
Definition at line 192 of file CompactBinaryValue.h.
References Data, FORCEINLINE, NETWORK_ORDER64, and FGenericPlatformMemory::ReadUnaligned().
AsFloat32()
FORCEINLINE float FCbValue::AsFloat32 () const
Definition at line 160 of file CompactBinaryValue.h.
References Data, FORCEINLINE, NETWORK_ORDER32, FGenericPlatformMemory::ReadUnaligned(), and Value.
AsFloat64()
FORCEINLINE double FCbValue::AsFloat64 () const
Definition at line 166 of file CompactBinaryValue.h.
References Data, FORCEINLINE, NETWORK_ORDER64, FGenericPlatformMemory::ReadUnaligned(), and Value.
AsHash()
FORCEINLINE FIoHash FCbValue::AsHash () const
Definition at line 177 of file CompactBinaryValue.h.
References Data, and FORCEINLINE.
Referenced by AsAttachment(), AsBinaryAttachment(), and AsObjectAttachment().
AsInteger()
FORCEINLINE uint64 FCbValue::AsInteger (UE::CompactBinary::Private::FIntegerParams Params, ECbFieldError * OutError = nullptr, uint64 Default = 0) const
Access as an integer, with both positive and negative values returned as unsigned.
Checks for range errors and uses the default if OutError is not null.
Definition at line 126 of file CompactBinaryValue.h.
References Data, Default, FORCEINLINE, None, Params, RangeError, ReadVarUInt(), Type, and Value.
AsIntegerNegative()
FORCEINLINE int64 FCbValue::AsIntegerNegative () const
Definition at line 154 of file CompactBinaryValue.h.
References Data, FORCEINLINE, and ReadVarUInt().
AsIntegerPositive()
FORCEINLINE uint64 FCbValue::AsIntegerPositive () const
Definition at line 148 of file CompactBinaryValue.h.
References Data, FORCEINLINE, and ReadVarUInt().
AsObjectAttachment()
FORCEINLINE FIoHash FCbValue::AsObjectAttachment () const inline
Definition at line 49 of file CompactBinaryValue.h.
References AsHash(), and FORCEINLINE.
AsObjectId()
FORCEINLINE FCbObjectId FCbValue::AsObjectId () const
Definition at line 202 of file CompactBinaryValue.h.
References Data, FORCEINLINE, and MakeMemoryView().
AsObjectView()
FORCEINLINE FCbObjectView FCbValue::AsObjectView () const
Definition at line 89 of file CompactBinaryValue.h.
References FORCEINLINE.
AsString()
FORCEINLINE FUtf8StringView FCbValue::AsString (ECbFieldError * OutError = nullptr, FUtf8StringView Default = FUtf8StringView()) const
Access as a string.
Checks for range errors and uses the default if OutError is not null.
Definition at line 107 of file CompactBinaryValue.h.
References Data, Default, FORCEINLINE, None, RangeError, and ReadVarUInt().
AsTimeSpanTicks()
FORCEINLINE int64 FCbValue::AsTimeSpanTicks () const
Definition at line 197 of file CompactBinaryValue.h.
References Data, FORCEINLINE, NETWORK_ORDER64, and FGenericPlatformMemory::ReadUnaligned().
AsUuid()
FORCEINLINE FGuid FCbValue::AsUuid () const
Definition at line 182 of file CompactBinaryValue.h.
References Data, FORCEINLINE, NETWORK_ORDER32, FGenericPlatformMemory::ReadUnaligned(), and Value.
GetData()
FORCEINLINE const void * FCbValue::GetData () const inline
Definition at line 65 of file CompactBinaryValue.h.
References Data, and FORCEINLINE.
GetType()
FORCEINLINE ECbFieldType FCbValue::GetType () const inline
Definition at line 64 of file CompactBinaryValue.h.
References FORCEINLINE, and Type.
Field Documentation
Data
const void* FCbValue::Data private
Definition at line 68 of file CompactBinaryValue.h.
Referenced by FCbValue(), AsBinary(), AsCustomById(), AsCustomByName(), AsDateTimeTicks(), AsFloat32(), AsFloat64(), AsHash(), AsInteger(), AsIntegerNegative(), AsIntegerPositive(), AsObjectId(), AsString(), AsTimeSpanTicks(), AsUuid(), and GetData().
Type
ECbFieldType FCbValue::Type private
Definition at line 69 of file CompactBinaryValue.h.
Referenced by FCbValue(), AsBool(), AsInteger(), and GetType().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Serialization/CompactBinaryValue.h