Unreal Engine 5.6 C++ API: FPackedLevelActorBuilder Class Reference
FPackedLevelActorBuilder Class Reference
FPackedLevelActorBuilder handles packing of ALevelInstance actors into APackedLevelActor actors and Blueprints.
#include "PackedLevelActorBuilder.h"
Public Member Functions
FPackedLevelActorBuilder ()
template<class T>
void AddBuilder ()
void ClusterActor (FPackedLevelActorBuilderContext &InContext, AActor *InActor)
bool CreateOrUpdateBlueprint (ILevelInstanceInterface *InLevelInstance, TSoftObjectPtr< UBlueprint > InBlueprintAsset, bool bCheckoutAndSave=true, bool bPromptForSave=true)
bool CreateOrUpdateBlueprint (TSoftObjectPtr< UWorld > InWorldAsset, TSoftObjectPtr< UBlueprint > InBlueprintAsset, bool bCheckoutAndSave=true, bool bPromptForSave=true)
bool PackActor (APackedLevelActor *InPackedLevelActor)
bool PackActor (APackedLevelActor *InPackedLevelActor, ILevelInstanceInterface *InLevelInstanceToPack)
bool PackActor (APackedLevelActor *InPackedLevelActor, TSoftObjectPtr< UWorld > InWorldAsset)
void UpdateBlueprint (UBlueprint *Blueprint, bool bCheckoutAndSave=true)
Static Public Member Functions
static TSharedPtr< FPackedLevelActorBuilder > CreateDefaultBuilder ()
static UBlueprint * CreatePackedLevelActorBlueprint (TSoftObjectPtr< UBlueprint > InBlueprintAsset, TSoftObjectPtr< UWorld > InWorldAsset, bool bInCompile)
static UBlueprint * CreatePackedLevelActorBlueprintWithDialog (TSoftObjectPtr< UBlueprint > InBlueprintAsset, TSoftObjectPtr< UWorld > InWorldAsset, bool bInCompile)
static const FString & GetPackedBPPrefix ()
Private Member Functions
FPackedLevelActorBuilder (const FPackedLevelActorBuilder &)=delete
bool CreateOrUpdateBlueprintFromPacked (APackedLevelActor *InPackedActor, TSoftObjectPtr< UBlueprint > InBlueprintAsset, bool bCheckoutAndSave, bool bPromptForSave)
bool CreateOrUpdateBlueprintFromUnpacked (ILevelInstanceInterface *InLevelInstance, TSoftObjectPtr< UBlueprint > InBlueprintAsset, bool bCheckoutAndSave, bool bPromptForSave)
ALevelInstance * CreateTransientLevelInstanceForPacking (TSoftObjectPtr< UWorld > InWorldAsset, const FVector &InLocation, const FRotator &InRotator, const FWorldPartitionActorFilter &InFilter)
FPackedLevelActorBuilder & operator= (const FPackedLevelActorBuilder &)=delete
bool PackActor (FPackedLevelActorBuilderContext &InContext)
Private Attributes
TMap< FPackedLevelActorBuilderID, TUniquePtr< IPackedLevelActorBuilder > > Builders
TSet< UClass * > ClassDiscards
FPreviewScene PreviewScene
Friends
class FPackedLevelActorBuilderContext
Detailed Description
FPackedLevelActorBuilder handles packing of ALevelInstance actors into APackedLevelActor actors and Blueprints.
Definition at line 27 of file PackedLevelActorBuilder.h.
Constructor & Destructor Documentation
FPackedLevelActorBuilder() [1/2]
FPackedLevelActorBuilder::FPackedLevelActorBuilder ()
Referenced by FPackedLevelActorBuilder(), and operator=().
FPackedLevelActorBuilder() [2/2]
FPackedLevelActorBuilder::FPackedLevelActorBuilder (const FPackedLevelActorBuilder &) private delete
References FPackedLevelActorBuilder().
Member Function Documentation
AddBuilder()
template<class T> void FPackedLevelActorBuilder::AddBuilder () inline
Definition at line 55 of file PackedLevelActorBuilder.h.
References Builders, check, and MakeUnique().
ClusterActor()
void FPackedLevelActorBuilder::ClusterActor (FPackedLevelActorBuilderContext & InContext, AActor * InActor)
References FPackedLevelActorBuilderContext.
CreateDefaultBuilder()
TSharedPtr< FPackedLevelActorBuilder > FPackedLevelActorBuilder::CreateDefaultBuilder () static
CreateOrUpdateBlueprint() [1/2]
bool FPackedLevelActorBuilder::CreateOrUpdateBlueprint (ILevelInstanceInterface * InLevelInstance, TSoftObjectPtr< UBlueprint > InBlueprintAsset, bool bCheckoutAndSave = true, bool bPromptForSave = true)
CreateOrUpdateBlueprint() [2/2]
bool FPackedLevelActorBuilder::CreateOrUpdateBlueprint (TSoftObjectPtr< UWorld > InWorldAsset, TSoftObjectPtr< UBlueprint > InBlueprintAsset, bool bCheckoutAndSave = true, bool bPromptForSave = true)
CreateOrUpdateBlueprintFromPacked()
bool FPackedLevelActorBuilder::CreateOrUpdateBlueprintFromPacked (APackedLevelActor * InPackedActor, TSoftObjectPtr< UBlueprint > InBlueprintAsset, bool bCheckoutAndSave, bool bPromptForSave) private
CreateOrUpdateBlueprintFromUnpacked()
bool FPackedLevelActorBuilder::CreateOrUpdateBlueprintFromUnpacked (ILevelInstanceInterface * InLevelInstance, TSoftObjectPtr< UBlueprint > InBlueprintAsset, bool bCheckoutAndSave, bool bPromptForSave) private
CreatePackedLevelActorBlueprint()
UBlueprint * FPackedLevelActorBuilder::CreatePackedLevelActorBlueprint (TSoftObjectPtr< UBlueprint > InBlueprintAsset, TSoftObjectPtr< UWorld > InWorldAsset, bool bInCompile) static
CreatePackedLevelActorBlueprintWithDialog()
UBlueprint * FPackedLevelActorBuilder::CreatePackedLevelActorBlueprintWithDialog (TSoftObjectPtr< UBlueprint > InBlueprintAsset, TSoftObjectPtr< UWorld > InWorldAsset, bool bInCompile) static
CreateTransientLevelInstanceForPacking()
ALevelInstance * FPackedLevelActorBuilder::CreateTransientLevelInstanceForPacking (TSoftObjectPtr< UWorld > InWorldAsset, const FVector & InLocation, const FRotator & InRotator, const FWorldPartitionActorFilter & InFilter) private
References FVector.
GetPackedBPPrefix()
const FString & FPackedLevelActorBuilder::GetPackedBPPrefix () static
operator=()
FPackedLevelActorBuilder & FPackedLevelActorBuilder::operator= (const FPackedLevelActorBuilder &) private delete
References FPackedLevelActorBuilder().
PackActor() [1/4]
bool FPackedLevelActorBuilder::PackActor (APackedLevelActor * InPackedLevelActor)
PackActor() [2/4]
bool FPackedLevelActorBuilder::PackActor (APackedLevelActor * InPackedLevelActor, ILevelInstanceInterface * InLevelInstanceToPack)
PackActor() [3/4]
bool FPackedLevelActorBuilder::PackActor (APackedLevelActor * InPackedLevelActor, TSoftObjectPtr< UWorld > InWorldAsset)
PackActor() [4/4]
bool FPackedLevelActorBuilder::PackActor (FPackedLevelActorBuilderContext & InContext) private
References FPackedLevelActorBuilderContext.
UpdateBlueprint()
void FPackedLevelActorBuilder::UpdateBlueprint (UBlueprint * Blueprint, bool bCheckoutAndSave = true)
Friends And Related Symbol Documentation
FPackedLevelActorBuilderContext
friend class FPackedLevelActorBuilderContext friend
Definition at line 76 of file PackedLevelActorBuilder.h.
References FPackedLevelActorBuilderContext.
Referenced by ClusterActor(), FPackedLevelActorBuilderContext, and PackActor().
Field Documentation
Builders
TMap<FPackedLevelActorBuilderID, TUniquePtr<IPackedLevelActorBuilder> > FPackedLevelActorBuilder::Builders private
Definition at line 81 of file PackedLevelActorBuilder.h.
Referenced by AddBuilder().
ClassDiscards
TSet<UClass*> FPackedLevelActorBuilder::ClassDiscards private
Definition at line 80 of file PackedLevelActorBuilder.h.
PreviewScene
FPreviewScene FPackedLevelActorBuilder::PreviewScene private
Definition at line 82 of file PackedLevelActorBuilder.h.
The documentation for this class was generated from the following file:
Runtime/Engine/Public/PackedLevelActor/PackedLevelActorBuilder.h