Unreal Engine 5.6 C++ API: TRDGEventScopeGuard< TScopeType > Class Template Reference
TRDGEventScopeGuard< TScopeType > Class Template Reference
#include "RenderGraphEvent.h"
Public Member Functions
template<typename... TArgs>
TRDGEventScopeGuard (FRDGScopeState &State, ERDGScopeFlags Flags, TArgs &&... Args)
~TRDGEventScopeGuard ()
Private Member Functions
TRDGEventScopeGuard (TRDGEventScopeGuard &&)=delete
TRDGEventScopeGuard (TRDGEventScopeGuard const &)=delete
Private Attributes
FRDGScope *const Scope
FRDGScopeState & State
Static Private Attributes
static constexpr uint32 TypeMask = 1u << FRDGScope::FStorage::GetTypeIndex<TScopeType>()
Detailed Description
template<typename TScopeType>
class TRDGEventScopeGuard< TScopeType >
Definition at line 328 of file RenderGraphEvent.h.
Constructor & Destructor Documentation
TRDGEventScopeGuard() [1/3]
template<typename TScopeType> TRDGEventScopeGuard< TScopeType >::TRDGEventScopeGuard (TRDGEventScopeGuard< TScopeType > const &) private delete
References TRDGEventScopeGuard().
Referenced by TRDGEventScopeGuard(), and TRDGEventScopeGuard().
TRDGEventScopeGuard() [2/3]
template<typename TScopeType> TRDGEventScopeGuard< TScopeType >::TRDGEventScopeGuard (TRDGEventScopeGuard< TScopeType > &&) private delete
References TRDGEventScopeGuard().
TRDGEventScopeGuard() [3/3]
template<typename TScopeType> template<typename... TArgs> TRDGEventScopeGuard< TScopeType >::TRDGEventScopeGuard (FRDGScopeState & State, ERDGScopeFlags Flags, TArgs &&... Args) inline
References Flags, and State.
~TRDGEventScopeGuard()
template<typename TScopeType> TRDGEventScopeGuard< TScopeType >::~TRDGEventScopeGuard () inline
Field Documentation
Scope
template<typename TScopeType> FRDGScope* const TRDGEventScopeGuard< TScopeType >::Scope private
Definition at line 331 of file RenderGraphEvent.h.
State
template<typename TScopeType> FRDGScopeState& TRDGEventScopeGuard< TScopeType >::State private
Definition at line 330 of file RenderGraphEvent.h.
Referenced by TRDGEventScopeGuard().
TypeMask
template<typename TScopeType> uint32 TRDGEventScopeGuard< TScopeType >::TypeMask = 1u << FRDGScope::FStorage::GetTypeIndex<TScopeType>() static constexpr private
Definition at line 342 of file RenderGraphEvent.h.
The documentation for this class was generated from the following file:
Runtime/RenderCore/Public/RenderGraphEvent.h