Unreal Engine 5.6 C++ API: TGPUSkinAPEXClothVertexFactory< BoneInfluenceType > Class Template Reference
TGPUSkinAPEXClothVertexFactory< BoneInfluenceType > Class Template Reference
#include "GPUSkinVertexFactory.h"
Public Types
typedef TGPUSkinVertexFactory< BoneInfluenceType > Super
Public Types inherited from FRenderResource
enum class EInitPhase : uint8 { Pre , Default , MAX }
Controls initialization order of render resources.
Public Member Functions
TGPUSkinAPEXClothVertexFactory (ERHIFeatureLevel::Type InFeatureLevel, uint32 InNumBones, uint32 InNumVertices, uint32 InBaseVertexIndex, uint32 InNumInfluencesPerVertex, bool bInUsedForPassthroughVertexFactory)
Constructor presizing bone matrices array to used amount.
virtual ~TGPUSkinAPEXClothVertexFactory () override
Destructor takes care of the Data pointer.
const FShaderResourceViewRHIRef GetClothBuffer () const override
FShaderResourceViewRHIRef GetClothBuffer () override
Get buffer containing cloth influences.
uint32 GetClothIndexOffset (uint32 VertexIndex, uint32 LODBias=0) const override
Get offset from vertex index to cloth influence index at a given vertex index.
virtual FGPUBaseSkinAPEXClothVertexFactory const * GetClothVertexFactory () const override
virtual FGPUBaseSkinAPEXClothVertexFactory * GetClothVertexFactory () override
Cloth vertex factory access.
virtual FVertexFactoryType * GetType () const override
virtual const FGPUBaseSkinVertexFactory * GetVertexFactory () const override
virtual FGPUBaseSkinVertexFactory * GetVertexFactory () override
virtual void InitRHI (FRHICommandListBase &RHICmdList) override
Creates declarations for each of the vertex stream components and initializes the device resource.
virtual void ReleaseRHI () override
Releases the RHI resources used by this resource.
virtual void SetData (FRHICommandListBase &RHICmdList, const FGPUSkinDataType *InData) override
An implementation of the interface used by TSynchronizedResource to update the resource with new data from the game thread.
Public Member Functions inherited from FGPUBaseSkinAPEXClothVertexFactory
FGPUBaseSkinAPEXClothVertexFactory (uint32 InNumInfluencesPerVertex)
virtual ~FGPUBaseSkinAPEXClothVertexFactory ()
ClothShaderType & GetClothShaderData ()
accessor
const ClothShaderType & GetClothShaderData () const
Public Member Functions inherited from TGPUSkinVertexFactory< BoneInfluenceType >
TGPUSkinVertexFactory (ERHIFeatureLevel::Type InFeatureLevel, uint32 InNumBones, uint32 InNumVertices, uint32 InBaseVertexIndex, bool bInUsedForPassthroughVertexFactory)
Constructor presizing bone matrices array to used amount.
virtual GPUSkinBoneInfluenceType GetBoneInfluenceType () const override
Public Member Functions inherited from FGPUBaseSkinVertexFactory
FGPUBaseSkinVertexFactory (ERHIFeatureLevel::Type InFeatureLevel, uint32 InNumBones, uint32 InNumVertices, uint32 InBaseVertexIndex, bool bInUsedForPassthroughVertexFactory)
virtual ~FGPUBaseSkinVertexFactory ()
void CopyDataTypeForLocalVertexFactory (FLocalVertexFactory::FDataType &OutDestData) const
uint32 GetBaseVertexIndex () const
uint32 GetBoneBufferSize () const
virtual const FShaderResourceViewRHIRef GetColorComponentsSRV () const
virtual const uint32 GetColorIndexMask () const
const class FMorphVertexBuffer * GetMorphVertexBuffer (bool bPrevious) const
uint32 GetMorphVertexBufferUpdatedFrameNumber () const
virtual uint32 GetNumBoneInfluences () const
uint32 GetNumBones () const
virtual uint32 GetNumTexCoords () const
uint32 GetNumVertices () const
void GetOverrideVertexStreams (FVertexInputStreamArray &VertexStreams) const
virtual const FShaderResourceViewRHIRef GetPositionsSRV () const
const FVertexStreamComponent & GetPositionStreamComponent () const
FShaderDataType & GetShaderData ()
accessor
const FShaderDataType & GetShaderData () const
virtual const FShaderResourceViewRHIRef GetTangentsSRV () const
const FVertexStreamComponent & GetTangentStreamComponent (int Index) const
virtual const FShaderResourceViewRHIRef GetTextureCoordinatesSRV () const
virtual FShaderResourceViewRHIRef GetTriangleSortingPositionSRV () const override
FRHIUniformBuffer * GetUniformBuffer () const
virtual bool IsMorphTarget () const
bool IsReadyForStaticMeshCaching () const
bool IsUniformBufferValid () const
void MarkUniformBufferDirty ()
void SetData (const FGPUSkinDataType *InData)
An implementation of the interface used by TSynchronizedResource to update the resource with new data from the game thread.
void UpdateMorphState (FRHICommandListBase &RHICmdList, bool bUseMorphTarget)
Morph vertex factory functions.
void UpdateUniformBuffer (FRHICommandListBase &RHICmdList)
virtual bool Use16BitBoneIndex () const
Public Member Functions inherited from FVertexFactory
FVertexFactory (ERHIFeatureLevel::Type InFeatureLevel)
virtual RENDERCORE_API ~FVertexFactory ()
FVertexDeclarationRHIRef & GetDeclaration ()
const FVertexDeclarationRHIRef & GetDeclaration (EVertexInputStreamType InputStreamType) const
int32 GetPrimitiveIdStreamIndex (const FStaticFeatureLevel InFeatureLevel, EVertexInputStreamType InputStreamType) const
RENDERCORE_API void GetStreams (ERHIFeatureLevel::Type InFeatureLevel, EVertexInputStreamType VertexStreamType, FVertexInputStreamArray &OutVertexStreams) const
bool NeedsDeclaration () const
RENDERCORE_API void OffsetInstanceStreams (uint32 InstanceOffset, EVertexInputStreamType VertexStreamType, FVertexInputStreamArray &VertexStreams) const
virtual bool RendersPrimitivesAsCameraFacingSprites () const
void SetDeclaration (FVertexDeclarationRHIRef &NewDeclaration)
bool SupportsGPUScene (const FStaticFeatureLevel InFeatureLevel) const
bool SupportsManualVertexFetch (const FStaticFeatureLevel InFeatureLevel) const
bool SupportsNullPixelShader () const
Indicates whether the vertex factory supports a null pixel shader.
virtual bool SupportsPositionAndNormalOnlyStream () const
Indicates whether the vertex factory supports a position-and-normal-only stream.
virtual bool SupportsPositionOnlyStream () const
Indicates whether the vertex factory supports a position-only stream.
bool SupportsTriangleSorting () const
Public Member Functions inherited from FRenderResource
RENDERCORE_API FRenderResource ()
Default constructor.
RENDERCORE_API FRenderResource (const FRenderResource &)
Misc copy/assignment.
RENDERCORE_API FRenderResource (ERHIFeatureLevel::Type InFeatureLevel)
Constructor when we know what feature level this resource should support.
RENDERCORE_API FRenderResource (FRenderResource &&)
virtual RENDERCORE_API ~FRenderResource ()
Destructor used to catch unreleased resources.
virtual FString GetFriendlyName () const
EInitPhase GetInitPhase () const
int32 GetListIndex () const
FName GetOwnerName () const
FName GetResourceName () const
virtual RENDERCORE_API void InitResource (FRHICommandListBase &RHICmdList)
Initializes the resource.
FORCEINLINE bool IsInitialized () const
RENDERCORE_API FRenderResource & operator= (const FRenderResource &Other)
RENDERCORE_API FRenderResource & operator= (FRenderResource &&Other)
virtual RENDERCORE_API void ReleaseResource ()
Prepares the resource for deletion.
void SetOwnerName (FName InOwnerName)
SetOwnerName should be called before BeginInitResource for the owner name to be successfully tracked.
void SetResourceName (FName InResourceName)
RENDERCORE_API void UpdateRHI (FRHICommandListBase &RHICmdList)
If the resource's RHI resources have been initialized, then release and reinitialize it.
Static Public Member Functions
static void ModifyCompilationEnvironment (const FVertexFactoryShaderPermutationParameters &Parameters, FShaderCompilerEnvironment &OutEnvironment)
static bool ShouldCompilePermutation (const FVertexFactoryShaderPermutationParameters &Parameters)
Static Public Member Functions inherited from FGPUBaseSkinAPEXClothVertexFactory
static bool IsClothEnabled (EShaderPlatform Platform)
Static Public Member Functions inherited from TGPUSkinVertexFactory< BoneInfluenceType >
static void GetPSOPrecacheVertexFetchElements (EVertexInputStreamType VertexInputStreamType, FVertexDeclarationElementList &Elements)
static void GetVertexElements (ERHIFeatureLevel::Type FeatureLevel, EVertexInputStreamType InputStreamType, FGPUSkinDataType &GPUSkinData, FVertexDeclarationElementList &Elements)
static void ModifyCompilationEnvironment (const FVertexFactoryShaderPermutationParameters &Parameters, FShaderCompilerEnvironment &OutEnvironment)
static bool ShouldCompilePermutation (const FVertexFactoryShaderPermutationParameters &Parameters)
Static Public Member Functions inherited from FGPUBaseSkinVertexFactory
static bool GetAlwaysUseDeformerForUnlimitedBoneInfluences (EShaderPlatform Platform)
Returns true if mesh LODs with Unlimited Bone Influences must always be rendered using a Mesh Deformer for the given shader platform.
static int32 GetBoneInfluenceLimitForAsset (int32 AssetProvidedLimit, const ITargetPlatform *TargetPlatform=nullptr)
static int32 GetMaxGPUSkinBones (const class ITargetPlatform *TargetPlatform=nullptr)
static int32 GetMinimumPerPlatformMaxGPUSkinBonesValue ()
static bool GetUnlimitedBoneInfluences (const ITargetPlatform *TargetPlatform=nullptr)
static bool UseUnlimitedBoneInfluences (uint32 MaxBoneInfluences, const ITargetPlatform *TargetPlatform=nullptr)
Static Public Member Functions inherited from FVertexFactory
static void GetPSOPrecacheVertexFetchElements (EVertexInputStreamType VertexInputStreamType, FVertexDeclarationElementList &Elements)
Can be overridden by FVertexFactory subclasses which have EVertexFactoryFlags::SupportsPSOPrecaching set - this function will only be called when that flag is set.
static void ModifyCompilationEnvironment (const FVertexFactoryShaderPermutationParameters &Parameters, FShaderCompilerEnvironment &OutEnvironment)
Can be overridden by FVertexFactory subclasses to modify their compile environment just before compilation occurs.
static void ValidateCompiledResult (const FVertexFactoryType *Type, EShaderPlatform Platform, const FShaderParameterMap &ParameterMap, TArray< FString > &OutErrors)
Can be overridden by FVertexFactory subclasses to fail a compile based on compilation output.
Static Public Member Functions inherited from FRenderResource
static RENDERCORE_API void ChangeFeatureLevel (ERHIFeatureLevel::Type NewFeatureLevel)
Reinitializes render resources at a new feature level.
static RENDERCORE_API void InitPreRHIResources ()
Initialize all resources initialized before the RHI was initialized.
static RENDERCORE_API void ReleaseRHIForAllResources ()
Release all render resources that are currently initialized.
Static Public Attributes
static FVertexFactoryType StaticType
Static Public Attributes inherited from TGPUSkinVertexFactory< BoneInfluenceType >
static FVertexFactoryType StaticType
Static Public Attributes inherited from FGPUBaseSkinVertexFactory
static const uint32 GHardwareMaxGPUSkinBones = 65536
Protected Attributes
FGPUSkinAPEXClothDataType * ClothDataPtr = nullptr
Alias pointer to TUniquePtr<FGPUSkinDataType> Data of FGPUBaseSkinVertexFactory.
Protected Attributes inherited from FGPUBaseSkinAPEXClothVertexFactory
ClothShaderType ClothShaderData
Protected Attributes inherited from FGPUBaseSkinVertexFactory
TUniquePtr< FGPUSkinDataType > Data
stream component data bound to this vertex factory
TRefCountPtr< FRHIStreamSourceSlot > MorphDeltaBufferSlot
int32 MorphDeltaStreamIndex = -1
FShaderDataType ShaderData
dynamic data need for setting the shader
FUniformBufferRHIRef UniformBuffer
Shader bindings are stored here in the uniform buffer.
Protected Attributes inherited from FVertexFactory
bool bNeedsDeclaration = true
FVertexStreamList Streams
The vertex streams used to render the factory.
Additional Inherited Members
Data Fields inherited from FRenderResource
ERenderResourceState ResourceState = ERenderResourceState::Default
Protected Types inherited from FVertexFactory
typedef TArray< FVertexStream, TInlineAllocator< 8 > > FVertexStreamList
Protected Member Functions inherited from TGPUSkinVertexFactory< BoneInfluenceType >
virtual void AddVertexElements (FVertexDeclarationElementList &OutElements) override
Add the decl elements for the streams.
Protected Member Functions inherited from FVertexFactory
FVertexElement AccessStreamComponent (const FVertexStreamComponent &Component, uint8 AttributeIndex)
Creates a vertex element for a vertex stream components.
RENDERCORE_API FVertexElement AccessStreamComponent (const FVertexStreamComponent &Component, uint8 AttributeIndex, EVertexInputStreamType InputStreamType)
Creates a vertex element for a vertex stream component.
RENDERCORE_API bool AddPrimitiveIdStreamElement (EVertexInputStreamType InputStreamType, FVertexDeclarationElementList &Elements, uint8 AttributeIndex, uint8 AttributeIndex_Mobile)
RENDERCORE_API void InitDeclaration (const FVertexDeclarationElementList &Elements, EVertexInputStreamType StreamType=EVertexInputStreamType::Default)
Initializes the vertex declaration.
void SetPrimitiveIdStreamIndex (const FStaticFeatureLevel InFeatureLevel, EVertexInputStreamType InputStreamType, int32 StreamIndex)
Protected Member Functions inherited from FRenderResource
template<typename T>
FBufferRHIRef CreateRHIBuffer (FRHICommandListBase &RHICmdList, T &InOutResourceObject, uint32 ResourceCount, EBufferUsageFlags InBufferUsageFlags, const TCHAR *InDebugName)
const FStaticFeatureLevel GetFeatureLevel () const
FORCEINLINE bool HasValidFeatureLevel () const
void SetFeatureLevel (const FStaticFeatureLevel InFeatureLevel)
void SetInitPhase (EInitPhase InInitPhase)
Static Protected Member Functions inherited from TGPUSkinVertexFactory< BoneInfluenceType >
static void GetVertexElements (ERHIFeatureLevel::Type FeatureLevel, EVertexInputStreamType InputStreamType, FGPUSkinDataType &GPUSkinData, FVertexDeclarationElementList &Elements, FVertexStreamList &InOutStreams, int32 &OutMorphDeltaStreamIndex)
Static Protected Member Functions inherited from FVertexFactory
template<typename VertexStreamListType>
static FVertexElement AccessStreamComponent (const FVertexStreamComponent &Component, uint8 AttributeIndex, VertexStreamListType &InOutStreams)
Creates a vertex element for a vertex stream components.
Static Protected Member Functions inherited from FRenderResource
static RENDERCORE_API FRHICommandListBase & GetImmediateCommandList ()
Detailed Description
template<GPUSkinBoneInfluenceType BoneInfluenceType>
class TGPUSkinAPEXClothVertexFactory< BoneInfluenceType >
Definition at line 637 of file GPUSkinVertexFactory.h.
Member Typedef Documentation
Super
template<GPUSkinBoneInfluenceType BoneInfluenceType> typedef TGPUSkinVertexFactory<BoneInfluenceType> TGPUSkinAPEXClothVertexFactory< BoneInfluenceType >::Super
Definition at line 641 of file GPUSkinVertexFactory.h.
Constructor & Destructor Documentation
TGPUSkinAPEXClothVertexFactory()
template<GPUSkinBoneInfluenceType BoneInfluenceType> TGPUSkinAPEXClothVertexFactory< BoneInfluenceType >::TGPUSkinAPEXClothVertexFactory (ERHIFeatureLevel::Type InFeatureLevel, uint32 InNumBones, uint32 InNumVertices, uint32 InBaseVertexIndex, uint32 InNumInfluencesPerVertex, bool bInUsedForPassthroughVertexFactory) inline
Constructor presizing bone matrices array to used amount.
Parameters
InBoneMatrices Reference to shared bone matrices array.
Definition at line 676 of file GPUSkinVertexFactory.h.
References FGPUBaseSkinAPEXClothVertexFactory::FGPUBaseSkinAPEXClothVertexFactory(), and TGPUSkinVertexFactory< BoneInfluenceType >::TGPUSkinVertexFactory().
Referenced by GetType().
~TGPUSkinAPEXClothVertexFactory()
template<GPUSkinBoneInfluenceType BoneInfluenceType> virtual TGPUSkinAPEXClothVertexFactory< BoneInfluenceType >::~TGPUSkinAPEXClothVertexFactory () inline override virtual
Destructor takes care of the Data pointer.
Since FGPUBaseSkinVertexFactory does not know the real type of the Data, delete the data here instead.
Definition at line 685 of file GPUSkinVertexFactory.h.
References checkf, ClothDataPtr, FGPUBaseSkinVertexFactory::Data, and TEXT.
Member Function Documentation
GetClothBuffer() [1/2]
template<GPUSkinBoneInfluenceType BoneInfluenceType> const FShaderResourceViewRHIRef TGPUSkinAPEXClothVertexFactory< BoneInfluenceType >::GetClothBuffer () const inline override virtual
Reimplemented from FGPUBaseSkinAPEXClothVertexFactory.
Definition at line 649 of file GPUSkinVertexFactory.h.
References ClothDataPtr.
GetClothBuffer() [2/2]
template<GPUSkinBoneInfluenceType BoneInfluenceType> FShaderResourceViewRHIRef TGPUSkinAPEXClothVertexFactory< BoneInfluenceType >::GetClothBuffer () inline override virtual
Get buffer containing cloth influences.
Reimplemented from FGPUBaseSkinAPEXClothVertexFactory.
Definition at line 644 of file GPUSkinVertexFactory.h.
References ClothDataPtr.
GetClothIndexOffset()
template<GPUSkinBoneInfluenceType BoneInfluenceType> uint32 TGPUSkinAPEXClothVertexFactory< BoneInfluenceType >::GetClothIndexOffset (uint32 VertexIndex, uint32 LODBias = 0) const inline override virtual
Get offset from vertex index to cloth influence index at a given vertex index.
The offset will be constant for all vertices in the same section.
Reimplemented from FGPUBaseSkinAPEXClothVertexFactory.
Definition at line 654 of file GPUSkinVertexFactory.h.
References FClothBufferIndexMapping::BaseVertexIndex, checkf, ClothDataPtr, FClothBufferIndexMapping::LODBiasStride, FClothBufferIndexMapping::MappingOffset, and TEXT.
GetClothVertexFactory() [1/2]
template<GPUSkinBoneInfluenceType BoneInfluenceType> virtual FGPUBaseSkinAPEXClothVertexFactory const * TGPUSkinAPEXClothVertexFactory< BoneInfluenceType >::GetClothVertexFactory () const inline override virtual
Reimplemented from FGPUBaseSkinVertexFactory.
Definition at line 717 of file GPUSkinVertexFactory.h.
References FGPUBaseSkinAPEXClothVertexFactory::FGPUBaseSkinAPEXClothVertexFactory().
GetClothVertexFactory() [2/2]
template<GPUSkinBoneInfluenceType BoneInfluenceType> virtual FGPUBaseSkinAPEXClothVertexFactory * TGPUSkinAPEXClothVertexFactory< BoneInfluenceType >::GetClothVertexFactory () inline override virtual
Cloth vertex factory access.
Reimplemented from FGPUBaseSkinVertexFactory.
Definition at line 712 of file GPUSkinVertexFactory.h.
References FGPUBaseSkinAPEXClothVertexFactory::FGPUBaseSkinAPEXClothVertexFactory().
GetType()
template<GPUSkinBoneInfluenceType BoneInfluenceType> virtual FVertexFactoryType * TGPUSkinAPEXClothVertexFactory< BoneInfluenceType >::GetType () const override virtual
Reimplemented from TGPUSkinVertexFactory< BoneInfluenceType >.
References TGPUSkinAPEXClothVertexFactory().
GetVertexFactory() [1/2]
template<GPUSkinBoneInfluenceType BoneInfluenceType> virtual const FGPUBaseSkinVertexFactory * TGPUSkinAPEXClothVertexFactory< BoneInfluenceType >::GetVertexFactory () const inline override virtual
Implements FGPUBaseSkinAPEXClothVertexFactory.
Definition at line 707 of file GPUSkinVertexFactory.h.
GetVertexFactory() [2/2]
template<GPUSkinBoneInfluenceType BoneInfluenceType> virtual FGPUBaseSkinVertexFactory * TGPUSkinAPEXClothVertexFactory< BoneInfluenceType >::GetVertexFactory () inline override virtual
Implements FGPUBaseSkinAPEXClothVertexFactory.
Definition at line 702 of file GPUSkinVertexFactory.h.
InitRHI()
template<GPUSkinBoneInfluenceType BoneInfluenceType> virtual void TGPUSkinAPEXClothVertexFactory< BoneInfluenceType >::InitRHI (FRHICommandListBase & RHICmdList) override virtual
Creates declarations for each of the vertex stream components and initializes the device resource.
Reimplemented from TGPUSkinVertexFactory< BoneInfluenceType >.
ModifyCompilationEnvironment()
template<GPUSkinBoneInfluenceType BoneInfluenceType> void TGPUSkinAPEXClothVertexFactory< BoneInfluenceType >::ModifyCompilationEnvironment (const FVertexFactoryShaderPermutationParameters & Parameters, FShaderCompilerEnvironment & OutEnvironment) static
ReleaseRHI()
template<GPUSkinBoneInfluenceType BoneInfluenceType> virtual void TGPUSkinAPEXClothVertexFactory< BoneInfluenceType >::ReleaseRHI () override virtual
Releases the RHI resources used by this resource.
Called when leaving the state where both the resource and the RHI have been initialized. This is only called by the rendering thread.
Reimplemented from TGPUSkinVertexFactory< BoneInfluenceType >.
SetData()
template<GPUSkinBoneInfluenceType BoneInfluenceType> virtual void TGPUSkinAPEXClothVertexFactory< BoneInfluenceType >::SetData (FRHICommandListBase & RHICmdList, const FGPUSkinDataType * InData) override virtual
An implementation of the interface used by TSynchronizedResource to update the resource with new data from the game thread.
Parameters
InData - new stream component data
Reimplemented from FGPUBaseSkinVertexFactory.
ShouldCompilePermutation()
template<GPUSkinBoneInfluenceType BoneInfluenceType> bool TGPUSkinAPEXClothVertexFactory< BoneInfluenceType >::ShouldCompilePermutation (const FVertexFactoryShaderPermutationParameters & Parameters) static
Field Documentation
ClothDataPtr
template<GPUSkinBoneInfluenceType BoneInfluenceType> FGPUSkinAPEXClothDataType* TGPUSkinAPEXClothVertexFactory< BoneInfluenceType >::ClothDataPtr = nullptr protected
Alias pointer to TUniquePtr<FGPUSkinDataType> Data of FGPUBaseSkinVertexFactory.
Note memory isn't managed through this pointer.
Definition at line 733 of file GPUSkinVertexFactory.h.
Referenced by ~TGPUSkinAPEXClothVertexFactory(), GetClothBuffer(), GetClothBuffer(), and GetClothIndexOffset().
StaticType
template<GPUSkinBoneInfluenceType BoneInfluenceType> FVertexFactoryType TGPUSkinAPEXClothVertexFactory< BoneInfluenceType >::StaticType static
Definition at line 639 of file GPUSkinVertexFactory.h.
The documentation for this class was generated from the following file:
Runtime/Engine/Public/GPUSkinVertexFactory.h