Unreal Engine 5.6 C++ API: UParticleModuleLocationPrimitiveCylinder_Seeded Class Reference
UParticleModuleLocationPrimitiveCylinder_Seeded Class Reference
#include "ParticleModuleLocationPrimitiveCylinder_Seeded.h"
Private Member Functions
virtual void EmitterLoopingNotify (FParticleEmitterInstance *Owner) override
GENERATED_UCLASS_BODY () UPROPERTY() struct FParticleRandomSeedInfo RandomSeedInfo
The random seed(s) to use for looking up values in StartLocation.
virtual FParticleRandomSeedInfo * GetRandomSeedInfo () override
Detailed Description
Definition at line 14 of file ParticleModuleLocationPrimitiveCylinder_Seeded.h.
Member Function Documentation
EmitterLoopingNotify()
virtual void UParticleModuleLocationPrimitiveCylinder_Seeded::EmitterLoopingNotify (FParticleEmitterInstance * Owner) override private virtual
References Owner.
GENERATED_UCLASS_BODY()
UParticleModuleLocationPrimitiveCylinder_Seeded::GENERATED_UCLASS_BODY () private
The random seed(s) to use for looking up values in StartLocation.
References Category, and UParticleModuleLocationPrimitiveCylinder::UPROPERTY().
GetRandomSeedInfo()
virtual FParticleRandomSeedInfo * UParticleModuleLocationPrimitiveCylinder_Seeded::GetRandomSeedInfo () inline override private virtual
Definition at line 24 of file ParticleModuleLocationPrimitiveCylinder_Seeded.h.
References GetRandomSeedInfo().
Referenced by GetRandomSeedInfo().
The documentation for this class was generated from the following file:
Runtime/Engine/Classes/Particles/Location/ParticleModuleLocationPrimitiveCylinder_Seeded.h