Unreal Engine 5.6 C++ API: UE::Sequencer::FViewModelHierarchyOperation Class Reference
UE::Sequencer::FViewModelHierarchyOperation Class Reference
Scoped utility class for batching change notifications on a view model hierarchy This class works by keeping track of models that have been changed in some way, along with their previous sibling and parent pointers before any change was made.
#include "ViewModelHierarchy.h"
Data Structures
struct FCachedHierarchicalPosition
struct FOperationAccumulationBuffer
Public Member Functions
FViewModelHierarchyOperation (const TSharedPtr< FSharedViewModelData > &InSharedData)
~FViewModelHierarchyOperation ()
void PreHierarchicalChange (const TSharedPtr< FViewModel > &InChangedNode)
Called before a change is made to the specified model's parent or previous sibling.
template<typename ViewModelType>
UE_DEPRECATED (5.5, "Please use the FSharedViewModelData overload by passing ->GetSharedData()") explicit FViewModelHierarchyOperation(const TSharedPtr< ViewModelType > &InAnyModel)
Private Member Functions
void Construct ()
Private Attributes
TSharedPtr< FOperationAccumulationBuffer > AccumulationBuffer
Accumulation buffer shared between all active FViewModelHierarchyOperations.
FViewModelHierarchyOperation * OldOperation
Pointer to the most recently active operation before this one existed.
TSharedPtr< FSharedViewModelData > SharedData
Shared data that contains the bound event handlers for any model.
Detailed Description
Scoped utility class for batching change notifications on a view model hierarchy This class works by keeping track of models that have been changed in some way, along with their previous sibling and parent pointers before any change was made.
With this information, when all FViewModelHierarchyOperation's have gone out of scope we can compare everything with its original pointers, and only dispatch change events in the case where they have actually changed. This enables reliable and accurate event processing in cases where large updates are made to a hierarchy with little or no meaningful change to the hierarchy.
Within any given hierarhcy of FViewModelHierarchyOperation scopes, there is guaranteed to be a maximum of one event triggered for each changed node. This is achieved by tracking which models have already been handled during the event processing.
Definition at line 290 of file ViewModelHierarchy.h.
Constructor & Destructor Documentation
FViewModelHierarchyOperation()
UE::Sequencer::FViewModelHierarchyOperation::FViewModelHierarchyOperation (const TSharedPtr< FSharedViewModelData > & InSharedData) explicit
Referenced by UE_DEPRECATED().
~FViewModelHierarchyOperation()
UE::Sequencer::FViewModelHierarchyOperation::~FViewModelHierarchyOperation ()
Member Function Documentation
Construct()
void UE::Sequencer::FViewModelHierarchyOperation::Construct () private
Referenced by UE_DEPRECATED().
PreHierarchicalChange()
void UE::Sequencer::FViewModelHierarchyOperation::PreHierarchicalChange (const TSharedPtr< FViewModel > & InChangedNode)
Called before a change is made to the specified model's parent or previous sibling.
UE_DEPRECATED()
template<typename ViewModelType> UE::Sequencer::FViewModelHierarchyOperation::UE_DEPRECATED (5. 5, "Please use the FSharedViewModelData overload by passing ->GetSharedData()") const & inline
Definition at line 295 of file ViewModelHierarchy.h.
References FViewModelHierarchyOperation(), Construct(), and SharedData.
Field Documentation
AccumulationBuffer
TSharedPtr<FOperationAccumulationBuffer> UE::Sequencer::FViewModelHierarchyOperation::AccumulationBuffer private
Accumulation buffer shared between all active FViewModelHierarchyOperations.
Definition at line 327 of file ViewModelHierarchy.h.
OldOperation
FViewModelHierarchyOperation* UE::Sequencer::FViewModelHierarchyOperation::OldOperation private
Pointer to the most recently active operation before this one existed.
Definition at line 329 of file ViewModelHierarchy.h.
SharedData
TSharedPtr<FSharedViewModelData> UE::Sequencer::FViewModelHierarchyOperation::SharedData private
Shared data that contains the bound event handlers for any model.
Definition at line 325 of file ViewModelHierarchy.h.
Referenced by UE_DEPRECATED().
The documentation for this class was generated from the following file:
Editor/SequencerCore/Public/MVVM/ViewModels/ViewModelHierarchy.h