Unreal Engine 5.6 C++ API: FBoolPropertyTrackEditor Class Reference
FBoolPropertyTrackEditor Class Reference
A property track editor for Booleans.
#include "BoolPropertyTrackEditor.h"
Public Member Functions
FBoolPropertyTrackEditor (TSharedRef< ISequencer > InSequencer)
Constructor.
Public Member Functions inherited from FPropertyTrackEditor< UMovieSceneBoolTrack >
FPropertyTrackEditor (TSharedRef< ISequencer > InSequencer)
Constructor.
~FPropertyTrackEditor ()
virtual bool SupportsSequence (UMovieSceneSequence *InSequence) const override
Returns whether a sequence is supported by this tool.
virtual bool SupportsType (TSubclassOf< UMovieSceneTrack > Type) const override
Returns whether a track class is supported by this tool.
Public Member Functions inherited from FKeyframeTrackEditor< UMovieSceneBoolTrack >
FKeyframeTrackEditor (TSharedRef< ISequencer > InSequencer)
Constructor.
~FKeyframeTrackEditor ()
Virtual destructor.
virtual void BuildTrackContextMenu (FMenuBuilder &MenuBuilder, UMovieSceneTrack *Track) override
Builds the context menu for the track.
Public Member Functions inherited from FMovieSceneTrackEditor
FMovieSceneTrackEditor (TSharedRef< ISequencer > InSequencer)
Constructor.
virtual ~FMovieSceneTrackEditor ()
Destructor.
void AnimatablePropertyChanged (FOnKeyProperty OnKeyProperty)
virtual void BindCommands (TSharedRef< FUICommandList > SequencerCommandBindings) override
Allows the track editors to bind commands.
virtual void BuildAddTrackMenu (FMenuBuilder &MenuBuilder) override
Builds up the sequencer's "Add Track" menu.
virtual void BuildObjectBindingColumnWidgets (TFunctionRef< TSharedRef< SHorizontalBox >()> GetEditBox, const UE::Sequencer::TViewModelPtr< UE::Sequencer::FObjectBindingModel > &ObjectBinding, const UE::Sequencer::FCreateOutlinerViewParams &InParams, const FName &InColumnName) override
Build a column widget for the specified object binding on the outliner.
virtual void BuildObjectBindingTrackMenu (FMenuBuilder &MenuBuilder, const TArray< FGuid > &ObjectBindings, const UClass *ObjectClass) override
Builds up the object binding track menu for the outliner.
virtual TSharedPtr< SWidget > BuildOutlinerColumnWidget (const FBuildColumnWidgetParams &Params, const FName &ColumnName) override
Builds an outliner column widget for the outliner nodes which represent tracks which are edited by this editor.
virtual TSharedPtr< SWidget > BuildOutlinerEditColumnWidget (const FGuid &ObjectBinding, UMovieSceneTrack *Track, const FBuildEditWidgetParams &Params) override
Builds a widget for the edit column for outliner nodes which represent tracks which are edited by this editor.
virtual TSharedPtr< SWidget > BuildOutlinerEditWidget (const FGuid &ObjectBinding, UMovieSceneTrack *Track, const FBuildEditWidgetParams &Params) override
Builds a widget for the add column for outliner nodes which represent tracks which are edited by this editor.
virtual void BuildPinnedAddTrackMenu (FMenuBuilder &MenuBuilder) override
Builds up the sequencer's "Add Track" menu.
virtual void BuildTrackSidebarMenu (FMenuBuilder &MenuBuilder, UMovieSceneTrack *Track) override
Builds the sidebar menu for the track.
FFindOrCreateHandleResult FindOrCreateHandleToObject (UObject *Object, bool bCreateHandleIfMissing=true, const FName &CreatedFolderName=NAME_None)
template<typename TrackClass>
FFindOrCreateRootTrackResult< TrackClass > FindOrCreateRootTrack ()
Find or add a track of the specified type in the focused movie scene.
FFindOrCreateTrackResult FindOrCreateTrackForObject (const FGuid &ObjectHandle, TSubclassOf< UMovieSceneTrack > TrackClass, FName PropertyName=NAME_None, bool bCreateTrackIfMissing=true)
UMovieSceneSequence * GetMovieSceneSequence () const
TSharedPtr< ISequencer > GetSequencer () const
FFrameNumber GetTimeForKey ()
virtual bool HandleAssetAdded (UObject *Asset, const FGuid &TargetObjectGuid) override
Called when an asset is dropped into Sequencer.
virtual bool OnAllowDrop (const FDragDropEvent &DragDropEvent, FSequencerDragDropParams &DragDropParams) override
Called when attempting to drop an asset directly onto a track.
virtual FReply OnDrop (const FDragDropEvent &DragDropEvent, const FSequencerDragDropParams &DragDropParams) override
Called when an asset is dropped directly onto a track.
virtual void OnInitialize () override
Called when the instance of this track editor is initialized.
virtual void OnRelease () override
Called when the instance of this track editor is released.
virtual void Tick (float DeltaTime) override
Ticks this tool.
void UpdatePlaybackRange ()
Public Member Functions inherited from TSharedFromThis< FMovieSceneTrackEditor >
TSharedRef< FMovieSceneTrackEditor, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FMovieSceneTrackEditor, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Public Member Functions inherited from ISequencerTrackEditor
virtual ~ISequencerTrackEditor ()
Virtual destructor.
virtual void BuildObjectBindingContextMenu (FMenuBuilder &MenuBuilder, const TArray< FGuid > &ObjectBindings, const UClass *ObjectClass)
Builds up the object binding cpmtext menu for the outliner.
virtual void BuildObjectBindingEditButtons (TSharedPtr< SHorizontalBox > EditBox, const FGuid &ObjectBinding, const UClass *ObjectClass)
Deprecated in principle, not practice (due to difficulty deprecating public virtual functions).
virtual bool CanAddTransformKeysForSelectedObjects () const
Whether or not we can add a transform key for a selected object.
virtual void ExtendObjectBindingTrackMenu (TSharedRef< FExtender > Extender, const TArray< FGuid > &ObjectBindings, const UClass *ObjectClass)
Extend the object binding track menu for the specified binding and class.
virtual bool GetDefaultExpansionState (UMovieSceneTrack *InTrack) const
virtual const FSlateBrush * GetIconBrush () const
Gets an icon brush for this track editor.
virtual bool HasTransformKeyBindings () const
virtual bool HasTransformKeyOverridePriority () const
If true this track has priority when setting transform keys and should be the only one to set them.
virtual bool IsResizable (UMovieSceneTrack *InTrack) const
virtual void ObjectImplicitlyAdded (UObject *InObject)
Handle this object being implicitly added.
virtual void ObjectImplicitlyRemoved (UObject *InObject)
Handle this object being implicitly removed.
virtual void OnAddTransformKeysForSelectedObjects (EMovieSceneTransformChannel Channel)
Adds transform tracks and keys to the selected objects in the level.
virtual void OnPostSaveWorld (UWorld *World)
Called after the sequencer has re-evaluated all objects after saving the level.
virtual void OnPreSaveWorld (UWorld *World)
Called before the sequencer restores pre-animated state on all objects before saving the level.
virtual void ProcessKeyOperation (FFrameNumber InKeyTime, const UE::Sequencer::FKeyOperation &Operation, ISequencer &InSequencer, TArray< UE::Sequencer::FAddKeyResult > *OutResults=nullptr)
Add keys for the following sections based on an external value if possible.
virtual void Resize (float NewSize, UMovieSceneTrack *InTrack)
Resize this track.
Static Public Member Functions
static TSharedRef< ISequencerTrackEditor > CreateTrackEditor (TSharedRef< ISequencer > OwningSequencer)
Creates an instance of this class (called by a sequencer).
static TArray< FAnimatedPropertyKey, TInlineAllocator< 1 > > GetAnimatedPropertyTypes ()
Retrieve a list of all property types that this track editor animates.
Static Public Member Functions inherited from FMovieSceneTrackEditor
static void BeginKeying (FFrameNumber InFrameNumber)
Initiate keying when there is more than one object to key (ie.
static void EndKeying ()
Protected Member Functions
virtual void GenerateKeysFromPropertyChanged (const FPropertyChangedParams &PropertyChangedParams, UMovieSceneSection *SectionToKey, FGeneratedTrackKeys &OutGeneratedKeys) override
Generates keys based on the new value from the property property change parameters.
virtual FText GetDisplayName () const override
The display name text to use in the UX.
virtual TSharedRef< ISequencerSection > MakeSectionInterface (UMovieSceneSection &SectionObject, UMovieSceneTrack &Track, FGuid ObjectBinding) override
Called to generate a section layout for a particular section.
Protected Member Functions inherited from FPropertyTrackEditor< UMovieSceneBoolTrack >
virtual UMovieSceneTrack * AddTrack (UMovieScene *FocusedMovieScene, const FGuid &ObjectHandle, TSubclassOf< class UMovieSceneTrack > TrackClass, FName UniqueTypeName) override
Add a new track to the sequence.
void AddWatchedProperty (FAnimatedPropertyKey PropertyKey)
Adds a callback for property changes for the supplied property type name.
virtual bool ForCustomizedUseOnly ()
When true, this track editor will only be used on properties which have specified it as a custom track class.
virtual void InitializeNewTrack (UMovieSceneBoolTrack *NewTrack, FPropertyChangedParams PropertyChangedParams)
Initialized values on a track after it's been created, but before any sections or keys have been added.
virtual void OnAnimatedPropertyChanged (const FPropertyChangedParams &PropertyChangedParams)
Called by the details panel when an animatable property changes.
Protected Member Functions inherited from FKeyframeTrackEditor< UMovieSceneBoolTrack >
FKeyPropertyResult AddKeysToObjects (TArrayView< UObject *const > ObjectsToKey, FFrameNumber KeyTime, ESequencerKeyMode KeyMode, TSubclassOf< UMovieSceneTrack > TrackClass, FName PropertyName, TFunction< void(UMovieSceneBoolTrack *)> OnInitializeNewTrack, const GenerateKeysCallback &OnGenerateKeys)
FKeyPropertyResult AddKeysToSection (UMovieSceneSection *Section, FFrameNumber KeyTime, const FGeneratedTrackKeys &Keys, ESequencerKeyMode KeyMode, EKeyFrameTrackEditorSetDefault SetDefault=EKeyFrameTrackEditorSetDefault::SetDefault)
virtual bool ModifyGeneratedKeysByCurrentAndWeight (UObject *Object, UMovieSceneTrack *Track, UMovieSceneSection *SectionToKey, FFrameNumber Time, FGeneratedTrackKeys &GeneratedTotalKeys, float Weight) const
Scale the generated keys by the the current value and the weight.
Protected Member Functions inherited from FMovieSceneTrackEditor
UMovieScene * GetFocusedMovieScene () const
Gets the currently focused movie scene, if any.
Protected Member Functions inherited from TSharedFromThis< FMovieSceneTrackEditor >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Additional Inherited Members
Public Types inherited from FKeyframeTrackEditor< UMovieSceneBoolTrack >
using GenerateKeysCallback
Static Protected Member Functions inherited from FKeyframeTrackEditor< UMovieSceneBoolTrack >
static bool CanAutoKeySection (UMovieSceneSection *Section, FFrameNumber Time)
Check whether we can autokey the specified section at the specified time.
Static Protected Member Functions inherited from TSharedFromThis< FMovieSceneTrackEditor >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
A property track editor for Booleans.
Definition at line 35 of file BoolPropertyTrackEditor.h.
Constructor & Destructor Documentation
FBoolPropertyTrackEditor()
FBoolPropertyTrackEditor::FBoolPropertyTrackEditor (TSharedRef< ISequencer > InSequencer) inline
Constructor.
Parameters
InSequencer The sequencer instance to be used by this tool.
Definition at line 45 of file BoolPropertyTrackEditor.h.
References FPropertyTrackEditor< UMovieSceneBoolTrack >::FPropertyTrackEditor(), and GetAnimatedPropertyTypes().
Member Function Documentation
CreateTrackEditor()
TSharedRef< ISequencerTrackEditor > FBoolPropertyTrackEditor::CreateTrackEditor (TSharedRef< ISequencer > OwningSequencer) static
Creates an instance of this class (called by a sequencer).
Parameters
OwningSequencer The sequencer instance to be used by this tool.
Returns
The new instance of this class.
GenerateKeysFromPropertyChanged()
virtual void FBoolPropertyTrackEditor::GenerateKeysFromPropertyChanged (const FPropertyChangedParams & PropertyChangedParams, UMovieSceneSection * SectionToKey, FGeneratedTrackKeys & OutGeneratedKeys) override protected virtual
Generates keys based on the new value from the property property change parameters.
Parameters
PropertyChangedParams Parameters associated with the property change.
OutGeneratedKeys Array of keys that are generated from the changed property
Implements FPropertyTrackEditor< UMovieSceneBoolTrack >.
GetAnimatedPropertyTypes()
TArray< FAnimatedPropertyKey, TInlineAllocator< 1 > > FBoolPropertyTrackEditor::GetAnimatedPropertyTypes () inline static
Retrieve a list of all property types that this track editor animates.
Definition at line 52 of file BoolPropertyTrackEditor.h.
References FAnimatedPropertyKey::FromPropertyTypeName().
Referenced by FBoolPropertyTrackEditor().
GetDisplayName()
virtual FText FBoolPropertyTrackEditor::GetDisplayName () const override protected virtual
The display name text to use in the UX.
Currently only used for sorting.
Reimplemented from FPropertyTrackEditor< UMovieSceneBoolTrack >.
MakeSectionInterface()
virtual TSharedRef< ISequencerSection > FBoolPropertyTrackEditor::MakeSectionInterface (UMovieSceneSection & SectionObject, UMovieSceneTrack & Track, FGuid ObjectBinding) override protected virtual
Called to generate a section layout for a particular section.
Parameters
SectionObject The section to make UI for.
Track The track that owns the section.
ObjectBinding the object binding for the track that owns the section, if there is one.
Reimplemented from FMovieSceneTrackEditor.
The documentation for this class was generated from the following file:
Editor/MovieSceneTools/Public/TrackEditors/PropertyTrackEditors/BoolPropertyTrackEditor.h