Unreal Engine 5.6 C++ API: FSequencerSectionPainter Class Reference
FSequencerSectionPainter Class Reference abstract
Class that wraps up common section painting functionality.
#include "SequencerSectionPainter.h"
Public Member Functions
virtual ~FSequencerSectionPainter ()
Virtual destructor.
FLinearColor GetSectionColor () const
virtual const FTimeToPixel & GetTimeConverter () const =0
Get a time-to-pixel converter for the section.
UMovieSceneTrack * GetTrack () const
Get the track that this painter is painting sections for.
int32 PaintSectionBackground ()
Paint the section background with the tint stored on the track.
virtual int32 PaintSectionBackground (const FLinearColor &Tint)=0
Paint the section background with the specified tint override.
UE_NONCOPYABLE (FSequencerSectionPainter) FSequencerSectionPainter(FSlateWindowElementList &OutDrawElements
Constructor.
Static Public Member Functions
static FLinearColor BlendColor (FLinearColor InColor)
Blend the specified color with the default track color.
Data Fields
bool bIsHighlighted
Whether the section is hovered or not.
bool bIsSelected
Whether the section is selected or not.
bool bParentEnabled
Whether our parent widget is enabled or not.
FSlateWindowElementList & DrawElements
List of slate draw elements - publicly modifiable.
float GhostAlpha
Whether the section is to be drawn semi-transparent or not.
FGeometry HeaderGeometry
The header geometry of the section.
const FGeometry & InSectionGeometry
int32 LayerId
The layer ID we're painting on.
const FGeometry TSharedPtr< UE::Sequencer::FSectionModel > Section
FSlateRect SectionClippingRect
The full clipping rectangle for the section.
FGeometry SectionGeometry
The full geometry of the section.
TSharedPtr< UE::Sequencer::FSectionModel > SectionModel
The section we are painting.
Detailed Description
Class that wraps up common section painting functionality.
Definition at line 40 of file SequencerSectionPainter.h.
Constructor & Destructor Documentation
~FSequencerSectionPainter()
virtual FSequencerSectionPainter::~FSequencerSectionPainter () virtual
Virtual destructor.
Member Function Documentation
BlendColor()
FLinearColor FSequencerSectionPainter::BlendColor (FLinearColor InColor) static
Blend the specified color with the default track color.
References BlendColor().
Referenced by BlendColor().
GetSectionColor()
FLinearColor FSequencerSectionPainter::GetSectionColor () const
References GetSectionColor().
Referenced by GetSectionColor().
GetTimeConverter()
virtual const FTimeToPixel & FSequencerSectionPainter::GetTimeConverter () const pure virtual
Get a time-to-pixel converter for the section.
References GetTimeConverter().
Referenced by GetTimeConverter().
GetTrack()
UMovieSceneTrack * FSequencerSectionPainter::GetTrack () const
Get the track that this painter is painting sections for.
References GetTrack().
Referenced by GetTrack().
PaintSectionBackground() [1/2]
int32 FSequencerSectionPainter::PaintSectionBackground ()
Paint the section background with the tint stored on the track.
References PaintSectionBackground().
PaintSectionBackground() [2/2]
virtual int32 FSequencerSectionPainter::PaintSectionBackground (const FLinearColor & Tint) pure virtual
Paint the section background with the specified tint override.
References PaintSectionBackground().
Referenced by TSubSectionMixin< ParentSectionClass >::OnPaintSection(), PaintSectionBackground(), and PaintSectionBackground().
UE_NONCOPYABLE()
FSequencerSectionPainter::UE_NONCOPYABLE (FSequencerSectionPainter) &
Constructor.
Field Documentation
bIsHighlighted
bool FSequencerSectionPainter::bIsHighlighted
Whether the section is hovered or not.
Definition at line 94 of file SequencerSectionPainter.h.
bIsSelected
bool FSequencerSectionPainter::bIsSelected
Whether the section is selected or not.
Definition at line 97 of file SequencerSectionPainter.h.
Referenced by TSubSectionMixin< ParentSectionClass >::GetSectionTime().
bParentEnabled
bool FSequencerSectionPainter::bParentEnabled
Whether our parent widget is enabled or not.
Definition at line 91 of file SequencerSectionPainter.h.
DrawElements
FSlateWindowElementList& FSequencerSectionPainter::DrawElements
List of slate draw elements - publicly modifiable.
Definition at line 76 of file SequencerSectionPainter.h.
GhostAlpha
float FSequencerSectionPainter::GhostAlpha
Whether the section is to be drawn semi-transparent or not.
Definition at line 100 of file SequencerSectionPainter.h.
HeaderGeometry
FGeometry FSequencerSectionPainter::HeaderGeometry
The header geometry of the section.
This is the same as SectionGeometry for collapsed sections, but just the height of the top row for expanded sections.
Definition at line 82 of file SequencerSectionPainter.h.
InSectionGeometry
const FGeometry& FSequencerSectionPainter::InSectionGeometry
Definition at line 46 of file SequencerSectionPainter.h.
LayerId
int32 FSequencerSectionPainter::LayerId
The layer ID we're painting on.
Definition at line 88 of file SequencerSectionPainter.h.
Referenced by TSubSectionMixin< ParentSectionClass >::OnPaintSection().
Section
const FGeometry TSharedPtr<UE::Sequencer::FSectionModel> FSequencerSectionPainter::Section
Definition at line 46 of file SequencerSectionPainter.h.
SectionClippingRect
FSlateRect FSequencerSectionPainter::SectionClippingRect
The full clipping rectangle for the section.
Definition at line 85 of file SequencerSectionPainter.h.
SectionGeometry
FGeometry FSequencerSectionPainter::SectionGeometry
The full geometry of the section.
This is the width of the track area in the case of infinite sections
Definition at line 79 of file SequencerSectionPainter.h.
SectionModel
TSharedPtr<UE::Sequencer::FSectionModel> FSequencerSectionPainter::SectionModel
The section we are painting.
Definition at line 73 of file SequencerSectionPainter.h.
The documentation for this class was generated from the following file:
Editor/Sequencer/Public/SequencerSectionPainter.h