Unreal Engine 5.6 C++ API: Metasound::VertexDataPrivate::FOutputBinding Class Reference
Metasound::VertexDataPrivate::FOutputBinding Class Reference
#include "MetasoundVertexData.h"
Public Member Functions
METASOUNDGRAPHCORE_API FOutputBinding (const FOutputDataVertex &InVertex)
METASOUNDGRAPHCORE_API FOutputBinding (const FVertexName &InVertexName, FAnyDataReference &&InReference)
METASOUNDGRAPHCORE_API FOutputBinding (FOutputDataVertex &&InVertex)
template<typename DataReferenceType>
void Bind (DataReferenceType &InOutDataReference)
METASOUNDGRAPHCORE_API void Bind (FOutputBinding &InBinding)
template<typename DataReferenceType>
void BindRead (DataReferenceType &InOutDataReference)
template<typename DataType>
void BindValue (const TDataValueReference< DataType > &InOutDataReference)
template<typename DataType>
void BindWrite (TDataWriteReference< DataType > &InOutDataReference)
METASOUNDGRAPHCORE_API EDataReferenceAccessType GetAccessType () const
METASOUNDGRAPHCORE_API const FAnyDataReference * GetDataReference () const
template<typename AsType>
AsType GetDataReferenceAs () const
METASOUNDGRAPHCORE_API FDataReferenceID GetDataReferenceID () const
template<typename AsType, typename ... ArgTypes>
AsType GetOrConstructAs (ArgTypes &&... Args) const
METASOUNDGRAPHCORE_API const FOutputDataVertex & GetVertex () const
METASOUNDGRAPHCORE_API bool IsBound () const
template<typename DataReferenceType>
void Set (const DataReferenceType &InDataReference)
METASOUNDGRAPHCORE_API void Set (FAnyDataReference &&InAnyDataReference)
template<typename DataType>
void SetValue (const DataType &InValue)
Private Attributes
TOptional< FAnyDataReference > Data
FOutputDataVertex Vertex
Detailed Description
Definition at line 320 of file MetasoundVertexData.h.
Constructor & Destructor Documentation
FOutputBinding() [1/3]
METASOUNDGRAPHCORE_API Metasound::VertexDataPrivate::FOutputBinding::FOutputBinding (FOutputDataVertex && InVertex)
References UE_API.
Referenced by Bind().
FOutputBinding() [2/3]
METASOUNDGRAPHCORE_API Metasound::VertexDataPrivate::FOutputBinding::FOutputBinding (const FOutputDataVertex & InVertex)
References UE_API.
FOutputBinding() [3/3]
METASOUNDGRAPHCORE_API Metasound::VertexDataPrivate::FOutputBinding::FOutputBinding (const FVertexName & InVertexName, FAnyDataReference && InReference)
References UE_API.
Member Function Documentation
Bind() [1/2]
template<typename DataReferenceType> void Metasound::VertexDataPrivate::FOutputBinding::Bind (DataReferenceType & InOutDataReference) inline
Definition at line 346 of file MetasoundVertexData.h.
References Bind(), and Set().
Referenced by Bind().
Bind() [2/2]
METASOUNDGRAPHCORE_API void Metasound::VertexDataPrivate::FOutputBinding::Bind (FOutputBinding & InBinding)
References FOutputBinding(), and UE_API.
BindRead()
template<typename DataReferenceType> void Metasound::VertexDataPrivate::FOutputBinding::BindRead (DataReferenceType & InOutDataReference) inline
Definition at line 334 of file MetasoundVertexData.h.
References Set().
BindValue()
template<typename DataType> void Metasound::VertexDataPrivate::FOutputBinding::BindValue (const TDataValueReference< DataType > & InOutDataReference) inline
Definition at line 328 of file MetasoundVertexData.h.
References Set().
BindWrite()
template<typename DataType> void Metasound::VertexDataPrivate::FOutputBinding::BindWrite (TDataWriteReference< DataType > & InOutDataReference) inline
Definition at line 340 of file MetasoundVertexData.h.
References Set().
GetAccessType()
METASOUNDGRAPHCORE_API EDataReferenceAccessType Metasound::VertexDataPrivate::FOutputBinding::GetAccessType () const
References UE_API.
GetDataReference()
METASOUNDGRAPHCORE_API const FAnyDataReference * Metasound::VertexDataPrivate::FOutputBinding::GetDataReference () const
References UE_API.
GetDataReferenceAs()
template<typename AsType> AsType Metasound::VertexDataPrivate::FOutputBinding::GetDataReferenceAs () const inline
Definition at line 396 of file MetasoundVertexData.h.
References check, and Data.
Referenced by Metasound::FOutputVertexInterfaceData::GetDataReadReference(), Metasound::FOutputVertexInterfaceData::GetDataWriteReference(), GetOrConstructAs(), and Metasound::FOutputVertexInterfaceData::GetValue().
GetDataReferenceID()
METASOUNDGRAPHCORE_API FDataReferenceID Metasound::VertexDataPrivate::FOutputBinding::GetDataReferenceID () const
References UE_API.
GetOrConstructAs()
template<typename AsType, typename ... ArgTypes> AsType Metasound::VertexDataPrivate::FOutputBinding::GetOrConstructAs (ArgTypes &&... Args) const inline
Definition at line 406 of file MetasoundVertexData.h.
References Metasound::VertexDataPrivate::TFactoryFacade< Type >::CreateWithArgs(), Data, Forward(), and GetDataReferenceAs().
GetVertex()
METASOUNDGRAPHCORE_API const FOutputDataVertex & Metasound::VertexDataPrivate::FOutputBinding::GetVertex () const
References UE_API.
IsBound()
METASOUNDGRAPHCORE_API bool Metasound::VertexDataPrivate::FOutputBinding::IsBound () const
References UE_API.
Referenced by Metasound::FOutputVertexInterfaceData::GetValue().
Set() [1/2]
template<typename DataReferenceType> void Metasound::VertexDataPrivate::FOutputBinding::Set (const DataReferenceType & InDataReference) inline
Definition at line 372 of file MetasoundVertexData.h.
References check, Metasound::VertexDataPrivate::CheckAccessTypeCompatibility(), Data, and Vertex.
Referenced by Bind(), BindRead(), BindValue(), and BindWrite().
Set() [2/2]
METASOUNDGRAPHCORE_API void Metasound::VertexDataPrivate::FOutputBinding::Set (FAnyDataReference && InAnyDataReference)
References UE_API.
SetValue()
template<typename DataType> void Metasound::VertexDataPrivate::FOutputBinding::SetValue (const DataType & InValue) inline
Definition at line 420 of file MetasoundVertexData.h.
References Metasound::VertexDataPrivate::CheckAccessTypeCompatibility(), Metasound::TDataValueReference< DataType >::CreateNew(), Data, and Vertex.
Field Documentation
Data
TOptional<FAnyDataReference> Metasound::VertexDataPrivate::FOutputBinding::Data private
Definition at line 429 of file MetasoundVertexData.h.
Referenced by GetDataReferenceAs(), GetOrConstructAs(), Set(), and SetValue().
Vertex
FOutputDataVertex Metasound::VertexDataPrivate::FOutputBinding::Vertex private
Definition at line 428 of file MetasoundVertexData.h.
Referenced by Set(), and SetValue().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/Metasound/Source/MetasoundGraphCore/Public/MetasoundVertexData.h