Unreal Engine 5.6 C++ API: IPixelStreamingEditorModule Class Reference
IPixelStreamingEditorModule Class Reference abstract
The public interface of the Pixel Streaming Editor module.
#include "IPixelStreamingEditorModule.h"
Public Member Functions
virtual FString GetSignallingDomain ()=0
Get the domain for the inbuilt c++ signalling server.
virtual TSharedPtr< UE::PixelStreamingServers::IServer > GetSignallingServer ()=0
Get the inbuilt C++ signalling server.
virtual int32 GetStreamerPort ()=0
Get the port streamers connect to for the inbuilt c++ signalling server.
virtual int32 GetViewerPort ()=0
Get the port viewers connect to for the inbuilt c++ signalling server.
virtual void SetSignallingDomain (const FString &InSignallingDomain)=0
Set the domain for the inbuilt c++ signalling server.
virtual void SetStreamerPort (int32 InStreamerPort)=0
Set the port streamers connect to for the inbuilt c++ signalling server.
virtual void SetViewerPort (int32 InViewerPort)=0
Set the port viewers connect to for the inbuilt c++ signalling server.
virtual void StartSignalling ()=0
Start the inbuilt C++ signalling server.
virtual void StartStreaming (UE::EditorPixelStreaming::EStreamTypes InStreamType)=0
Starts the editor specific streamer.
virtual void StopSignalling ()=0
Stop the inbuilt C++ signalling server.
virtual void StopStreaming ()=0
Starts the editor specific streamer.
virtual bool UseExternalSignallingServer ()=0
Get if streamers should use an external signalling server or the inbuilt c++ signalling server.
virtual void UseExternalSignallingServer (bool bUseExternalSignallingServer)=0
Set if streamers should use an external signalling server or the inbuilt c++ signalling server.
Public Member Functions inherited from IModuleInterface
virtual ~IModuleInterface ()
Note: Even though this is an interface class we need a virtual destructor here because modules are deleted via a pointer to this interface.
virtual bool IsGameModule () const
Returns true if this module hosts gameplay code.
virtual void PostLoadCallback ()
Called after the module has been reloaded.
virtual void PreUnloadCallback ()
Called before the module has been unloaded.
virtual void ShutdownModule ()
Called before the module is unloaded, right before the module object is destroyed.
virtual void StartupModule ()
Called right after the module DLL has been loaded and the module object has been created Load dependent modules here, and they will be guaranteed to be available during ShutdownModule.
virtual bool SupportsAutomaticShutdown ()
Override this to set whether your module would like cleanup on application shutdown.
virtual bool SupportsDynamicReloading ()
Override this to set whether your module is allowed to be unloaded on the fly.
Static Public Member Functions
static IPixelStreamingEditorModule & Get ()
Singleton-like access to this module's interface.
static bool IsAvailable ()
Checks to see if this module is loaded.
Detailed Description
The public interface of the Pixel Streaming Editor module.
Definition at line 14 of file IPixelStreamingEditorModule.h.
Member Function Documentation
Get()
IPixelStreamingEditorModule & IPixelStreamingEditorModule::Get () inline static
Singleton-like access to this module's interface.
Beware of calling this during the shutdown phase, though. Your module might have been unloaded already.
Returns
Returns singleton instance, loading the module on demand if needed
Definition at line 23 of file IPixelStreamingEditorModule.h.
References FModuleManager::LoadModuleChecked().
GetSignallingDomain()
virtual FString IPixelStreamingEditorModule::GetSignallingDomain () pure virtual
Get the domain for the inbuilt c++ signalling server.
Returns
FString The inbuilt c++ signalling server's domain
GetSignallingServer()
virtual TSharedPtr< UE::PixelStreamingServers::IServer > IPixelStreamingEditorModule::GetSignallingServer () pure virtual
Get the inbuilt C++ signalling server.
Returns
TSharedPtr<UE::PixelStreamingServers::IServer> The signalling server
GetStreamerPort()
virtual int32 IPixelStreamingEditorModule::GetStreamerPort () pure virtual
Get the port streamers connect to for the inbuilt c++ signalling server.
Returns
int32 The inbuilt c++ signalling server's port for streamers connect to
GetViewerPort()
virtual int32 IPixelStreamingEditorModule::GetViewerPort () pure virtual
Get the port viewers connect to for the inbuilt c++ signalling server.
Returns
int32 The inbuilt c++ signalling server's port for viewers connect to
IsAvailable()
bool IPixelStreamingEditorModule::IsAvailable () inline static
Checks to see if this module is loaded.
Returns
True if the module is loaded.
Definition at line 33 of file IPixelStreamingEditorModule.h.
References FModuleManager::Get(), and FModuleManager::IsModuleLoaded().
SetSignallingDomain()
virtual void IPixelStreamingEditorModule::SetSignallingDomain (const FString & InSignallingDomain) pure virtual
Set the domain for the inbuilt c++ signalling server.
Parameters
InSignallingDomain The domain for the inbuilt c++ signalling server
SetStreamerPort()
virtual void IPixelStreamingEditorModule::SetStreamerPort (int32 InStreamerPort) pure virtual
Set the port streamers connect to for the inbuilt c++ signalling server.
Parameters
InStreamerPort The port streamers connect to for the inbuilt c++ signalling server
SetViewerPort()
virtual void IPixelStreamingEditorModule::SetViewerPort (int32 InViewerPort) pure virtual
Set the port viewers connect to for the inbuilt c++ signalling server.
Parameters
InViewerPort The port viewers connect to for the inbuilt c++ signalling server
StartSignalling()
virtual void IPixelStreamingEditorModule::StartSignalling () pure virtual
Start the inbuilt C++ signalling server.
StartStreaming()
virtual void IPixelStreamingEditorModule::StartStreaming (UE::EditorPixelStreaming::EStreamTypes InStreamType) pure virtual
Starts the editor specific streamer.
Parameters
InStreamType The stream type for this streamer.
StopSignalling()
virtual void IPixelStreamingEditorModule::StopSignalling () pure virtual
Stop the inbuilt C++ signalling server.
StopStreaming()
virtual void IPixelStreamingEditorModule::StopStreaming () pure virtual
Starts the editor specific streamer.
UseExternalSignallingServer() [1/2]
virtual bool IPixelStreamingEditorModule::UseExternalSignallingServer () pure virtual
Get if streamers should use an external signalling server or the inbuilt c++ signalling server.
Returns
true Use an external signalling server
false Use the inbuilt c++ signalling server
UseExternalSignallingServer() [2/2]
virtual void IPixelStreamingEditorModule::UseExternalSignallingServer (bool bUseExternalSignallingServer) pure virtual
Set if streamers should use an external signalling server or the inbuilt c++ signalling server.
Parameters
bUseExternalSignallingServer Should streamers use an external signalling server
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Media/PixelStreaming/Source/PixelStreamingEditor/Public/IPixelStreamingEditorModule.h