Unreal Engine 5.6 C++ API: UE::Shader::FPreshaderData Class Reference
UE::Shader::FPreshaderData Class Reference
#include "Preshader.h"
Public Member Functions
void AppendHash (FXxHash64Builder &OutHasher) const
FPreshaderValue Evaluate (FUniformExpressionSet *UniformExpressionSet, const struct FMaterialRenderContext &Context, FPreshaderStack &Stack) const
FPreshaderValue EvaluateConstant (const FMaterial &Material, FPreshaderStack &Stack) const
FPreshaderLabel GetLabel ()
LAYOUT_FIELD (TMemoryImageArray< EValueComponentType >, StructComponentTypes)
LAYOUT_FIELD (TMemoryImageArray< FPreshaderStructType >, StructTypes)
LAYOUT_FIELD (TMemoryImageArray< FScriptName >, Names)
LAYOUT_FIELD (TMemoryImageArray< uint8 >, Data)
const int32 Num () const
void SetLabel (FPreshaderLabel InLabel)
template<>
FPreshaderData & Write (const FHashedMaterialParameterInfo &Value)
template<>
FPreshaderData & Write (const FName &Value)=delete
Can't write FName, use FScriptName instead.
template<>
FPreshaderData & Write (const FScriptName &Value)
template<>
FPreshaderData & Write (const FType &Value)
template<>
FPreshaderData & Write (const FValue &Value)
template<typename T>
FPreshaderData & Write (const T &Value)
void WriteData (const void *Value, uint32 Size)
FPreshaderLabel WriteJump (EPreshaderOpcode Op)
void WriteJump (EPreshaderOpcode Op, FPreshaderLabel Label)
void WriteName (const FScriptName &Name)
FPreshaderData & WriteOpcode (EPreshaderOpcode Op)
void WriteType (const FType &Type)
void WriteValue (const FValue &Value)
Private Member Functions
DECLARE_TYPE_LAYOUT (FPreshaderData, NonVirtual)
Friends
bool operator!= (const FPreshaderData &Lhs, const FPreshaderData &Rhs)
bool operator== (const FPreshaderData &Lhs, const FPreshaderData &Rhs)
Detailed Description
Definition at line 97 of file Preshader.h.
Member Function Documentation
AppendHash()
void UE::Shader::FPreshaderData::AppendHash (FXxHash64Builder & OutHasher) const
DECLARE_TYPE_LAYOUT()
UE::Shader::FPreshaderData::DECLARE_TYPE_LAYOUT (FPreshaderData , NonVirtual) private
Evaluate()
FPreshaderValue UE::Shader::FPreshaderData::Evaluate (FUniformExpressionSet * UniformExpressionSet, const struct FMaterialRenderContext & Context, FPreshaderStack & Stack) const
EvaluateConstant()
FPreshaderValue UE::Shader::FPreshaderData::EvaluateConstant (const FMaterial & Material, FPreshaderStack & Stack) const
References Material.
GetLabel()
FPreshaderLabel UE::Shader::FPreshaderData::GetLabel ()
LAYOUT_FIELD() [1/4]
UE::Shader::FPreshaderData::LAYOUT_FIELD (TMemoryImageArray< EValueComponentType > , StructComponentTypes)
LAYOUT_FIELD() [2/4]
UE::Shader::FPreshaderData::LAYOUT_FIELD (TMemoryImageArray< FPreshaderStructType > , StructTypes)
LAYOUT_FIELD() [3/4]
UE::Shader::FPreshaderData::LAYOUT_FIELD (TMemoryImageArray< FScriptName > , Names)
References Names.
LAYOUT_FIELD() [4/4]
UE::Shader::FPreshaderData::LAYOUT_FIELD (TMemoryImageArray< uint8 > , Data)
Num()
const int32 UE::Shader::FPreshaderData::Num () const inline
Definition at line 116 of file Preshader.h.
SetLabel()
void UE::Shader::FPreshaderData::SetLabel (FPreshaderLabel InLabel)
Write() [1/6]
template<> FPreshaderData & UE::Shader::FPreshaderData::Write (const FHashedMaterialParameterInfo & Value) inline
Definition at line 146 of file Preshader.h.
References Value, Write(), and Write().
Referenced by Write().
Write() [2/6]
template<> FPreshaderData & UE::Shader::FPreshaderData::Write (const FName & Value) delete
Can't write FName, use FScriptName instead.
References Value.
Write() [3/6]
template<> FPreshaderData & UE::Shader::FPreshaderData::Write (const FScriptName & Value) inline
Definition at line 133 of file Preshader.h.
References Value, and WriteName().
Write() [4/6]
template<> FPreshaderData & UE::Shader::FPreshaderData::Write (const FType & Value) inline
Definition at line 136 of file Preshader.h.
References Value, and WriteType().
Write() [5/6]
template<> FPreshaderData & UE::Shader::FPreshaderData::Write (const FValue & Value) inline
Definition at line 139 of file Preshader.h.
References Value, and WriteValue().
Write() [6/6]
template<typename T> FPreshaderData & UE::Shader::FPreshaderData::Write (const T & Value) inline
Definition at line 130 of file Preshader.h.
References Value, and WriteData().
Referenced by Write().
WriteData()
void UE::Shader::FPreshaderData::WriteData (const void * Value, uint32 Size)
References TSequenceHistory< HistorySize >::Size, and Value.
Referenced by Write().
WriteJump() [1/2]
FPreshaderLabel UE::Shader::FPreshaderData::WriteJump (EPreshaderOpcode Op)
WriteJump() [2/2]
void UE::Shader::FPreshaderData::WriteJump (EPreshaderOpcode Op, FPreshaderLabel Label)
WriteName()
void UE::Shader::FPreshaderData::WriteName (const FScriptName & Name)
References Name.
Referenced by Write().
WriteOpcode()
FPreshaderData & UE::Shader::FPreshaderData::WriteOpcode (EPreshaderOpcode Op) inline
Definition at line 148 of file Preshader.h.
References ensure, UE::Shader::Nop, and Write.
WriteType()
void UE::Shader::FPreshaderData::WriteType (const FType & Type)
Referenced by Write().
WriteValue()
void UE::Shader::FPreshaderData::WriteValue (const FValue & Value)
References Value.
Referenced by Write().
Friends And Related Symbol Documentation
operator!=
bool operator!= (const FPreshaderData & Lhs, const FPreshaderData & Rhs) friend
Definition at line 106 of file Preshader.h.
References operator==.
operator==
bool operator== (const FPreshaderData & Lhs, const FPreshaderData & Rhs) friend
Definition at line 101 of file Preshader.h.
Referenced by operator!=.
The documentation for this class was generated from the following file:
Runtime/Engine/Public/Shader/Preshader.h