Unreal Engine 5.6 C++ API: FStaticMeshCompilingManager Class Reference
FStaticMeshCompilingManager Class Reference
#include "StaticMeshCompiler.h"
Data Structures
struct FFinishCompilationOptions
Public Member Functions
void AddStaticMeshes (TArrayView< UStaticMesh *const > InStaticMeshes)
Adds static meshes compiled asynchronously so they are monitored.
void AddStaticMeshesWithDependencies (TArrayView< UStaticMesh *const > InStaticMeshes)
Adds static meshes (with dependencies that are still compiling) compiled asynchronously so they are monitored.
void FinishAllCompilation () override
Blocks until completion of all async static mesh compilation.
void FinishCompilation (TArrayView< UStaticMesh *const > InStaticMeshes, const FFinishCompilationOptions &Options=FFinishCompilationOptions())
Blocks until completion of the requested static meshes.
EQueuedWorkPriority GetBasePriority (UStaticMesh *InStaticMesh) const
Returns the priority at which the given static mesh should be scheduled.
int32 GetNumRemainingMeshes () const
Returns the number of outstanding texture compilations.
FQueuedThreadPool * GetThreadPool () const
Returns the threadpool where static mesh compilation should be scheduled.
bool IsAsyncCompilationAllowed (UStaticMesh *InStaticMesh) const
Returns if asynchronous compilation is allowed for this static mesh.
bool IsAsyncCompilationCancelable () const
Returns true if the cancelation feature is currently activated.
bool IsAsyncStaticMeshCompilationEnabled () const
Returns true if the feature is currently activated.
void Shutdown () override
Cancel any pending work and blocks until it is safe to shut down.
Static Public Member Functions
static FStaticMeshCompilingManager & Get ()
static FName GetStaticAssetTypeName ()
Get the name of the asset type this compiler handles.
Private Member Functions
FStaticMeshCompilingManager ()
void FinishCompilationForObjects (TArrayView< UObject *const > InObjects) override
Handle generic finish compilation.
void FinishCompilationsForGame ()
FTextFormat GetAssetNameFormat () const override
Returns an FTextFormat representing a localized singular/plural formatter for this resource name.
FName GetAssetTypeName () const override
A unique name among all asset compiling manager to identify the type of asset this manager handles.
TArrayView< FName > GetDependentTypeNames () const override
Return other asset types that should preferably be handled before this one.
int32 GetNumRemainingAssets () const override
Returns the number of remaining compilations.
void MarkCompilationAsCanceled (TArrayView< UObject *const > InObjects) override
Mark compilation of the provided static meshes as canceled.
void OnPostReachabilityAnalysis ()
void PostCompilation (TArrayView< UStaticMesh *const > InStaticMeshes)
void PostCompilation (UStaticMesh *StaticMesh)
void ProcessAsyncTasks (bool bLimitExecutionTime=false) override
Called once per frame, fetches completed tasks and applies them to the scene.
void ProcessStaticMeshes (bool bLimitExecutionTime, int32 MinBatchSize=1)
void Reschedule ()
void SchedulePendingCompilations ()
void UpdateCompilationNotification ()
virtual ~IAssetCompilingManager ()
virtual void ProcessAsyncTasks (const AssetCompilation::FProcessAsyncTaskParams &Params)
Called once per frame, fetches completed tasks and applies them to the scene.
Private Attributes
bool bHasShutdown = false
TUniquePtr< FAsyncCompilationNotification > Notification
FDelegateHandle PostReachabilityAnalysisHandle
TSet< TWeakObjectPtr< UStaticMesh > > RegisteredStaticMesh
TMap< TWeakObjectPtr< UStaticMesh >, TSet< TWeakObjectPtr< UStaticMesh > > > ReverseDependencyLookup
TSet< TWeakObjectPtr< UStaticMesh > > StaticMeshesWithPendingDependencies
Friends
class FAssetCompilingManager
Detailed Description
Definition at line 18 of file StaticMeshCompiler.h.
Constructor & Destructor Documentation
FStaticMeshCompilingManager()
FStaticMeshCompilingManager::FStaticMeshCompilingManager () private
Referenced by Get().
Member Function Documentation
AddStaticMeshes()
void FStaticMeshCompilingManager::AddStaticMeshes (TArrayView< UStaticMesh *const > InStaticMeshes)
Adds static meshes compiled asynchronously so they are monitored.
AddStaticMeshesWithDependencies()
void FStaticMeshCompilingManager::AddStaticMeshesWithDependencies (TArrayView< UStaticMesh *const > InStaticMeshes)
Adds static meshes (with dependencies that are still compiling) compiled asynchronously so they are monitored.
FinishAllCompilation()
void FStaticMeshCompilingManager::FinishAllCompilation () override virtual
Blocks until completion of all async static mesh compilation.
Implements IAssetCompilingManager.
FinishCompilation()
void FStaticMeshCompilingManager::FinishCompilation (TArrayView< UStaticMesh *const > InStaticMeshes, const FFinishCompilationOptions & Options = FFinishCompilationOptions())
Blocks until completion of the requested static meshes.
FinishCompilationForObjects()
void FStaticMeshCompilingManager::FinishCompilationForObjects (TArrayView< UObject *const > InObjects) override private virtual
Handle generic finish compilation.
Reimplemented from IAssetCompilingManager.
FinishCompilationsForGame()
void FStaticMeshCompilingManager::FinishCompilationsForGame () private
Get()
FStaticMeshCompilingManager & FStaticMeshCompilingManager::Get () static
References FStaticMeshCompilingManager().
Referenced by FAsyncRegisterLevelContext::CreateInstance().
GetAssetNameFormat()
FTextFormat FStaticMeshCompilingManager::GetAssetNameFormat () const override private virtual
Returns an FTextFormat representing a localized singular/plural formatter for this resource name.
Note: Should be in a similar form as "{0}|plural(one=Singular Name,other=Plural Name)"
Implements IAssetCompilingManager.
GetAssetTypeName()
FName FStaticMeshCompilingManager::GetAssetTypeName () const override private virtual
A unique name among all asset compiling manager to identify the type of asset this manager handles.
Implements IAssetCompilingManager.
GetBasePriority()
EQueuedWorkPriority FStaticMeshCompilingManager::GetBasePriority (UStaticMesh * InStaticMesh) const
Returns the priority at which the given static mesh should be scheduled.
GetDependentTypeNames()
TArrayView< FName > FStaticMeshCompilingManager::GetDependentTypeNames () const override private virtual
Return other asset types that should preferably be handled before this one.
Implements IAssetCompilingManager.
GetNumRemainingAssets()
int32 FStaticMeshCompilingManager::GetNumRemainingAssets () const override private virtual
Returns the number of remaining compilations.
Implements IAssetCompilingManager.
GetNumRemainingMeshes()
int32 FStaticMeshCompilingManager::GetNumRemainingMeshes () const
Returns the number of outstanding texture compilations.
GetStaticAssetTypeName()
FName FStaticMeshCompilingManager::GetStaticAssetTypeName () static
Get the name of the asset type this compiler handles.
GetThreadPool()
FQueuedThreadPool * FStaticMeshCompilingManager::GetThreadPool () const
Returns the threadpool where static mesh compilation should be scheduled.
IsAsyncCompilationAllowed()
bool FStaticMeshCompilingManager::IsAsyncCompilationAllowed (UStaticMesh * InStaticMesh) const
Returns if asynchronous compilation is allowed for this static mesh.
IsAsyncCompilationCancelable()
bool FStaticMeshCompilingManager::IsAsyncCompilationCancelable () const
Returns true if the cancelation feature is currently activated.
IsAsyncStaticMeshCompilationEnabled()
bool FStaticMeshCompilingManager::IsAsyncStaticMeshCompilationEnabled () const
Returns true if the feature is currently activated.
Referenced by FAsyncRegisterLevelContext::CreateInstance().
MarkCompilationAsCanceled()
void FStaticMeshCompilingManager::MarkCompilationAsCanceled (TArrayView< UObject *const > InObjects) override private virtual
Mark compilation of the provided static meshes as canceled.
Reimplemented from IAssetCompilingManager.
OnPostReachabilityAnalysis()
void FStaticMeshCompilingManager::OnPostReachabilityAnalysis () private
PostCompilation() [1/2]
void FStaticMeshCompilingManager::PostCompilation (TArrayView< UStaticMesh *const > InStaticMeshes) private
PostCompilation() [2/2]
void FStaticMeshCompilingManager::PostCompilation (UStaticMesh * StaticMesh) private
References StaticMesh.
ProcessAsyncTasks()
void FStaticMeshCompilingManager::ProcessAsyncTasks (bool bLimitExecutionTime = false) override private virtual
Called once per frame, fetches completed tasks and applies them to the scene.
Implements IAssetCompilingManager.
ProcessStaticMeshes()
void FStaticMeshCompilingManager::ProcessStaticMeshes (bool bLimitExecutionTime, int32 MinBatchSize = 1) private
Reschedule()
void FStaticMeshCompilingManager::Reschedule () private
SchedulePendingCompilations()
void FStaticMeshCompilingManager::SchedulePendingCompilations () private
Shutdown()
void FStaticMeshCompilingManager::Shutdown () override virtual
Cancel any pending work and blocks until it is safe to shut down.
Implements IAssetCompilingManager.
UpdateCompilationNotification()
void FStaticMeshCompilingManager::UpdateCompilationNotification () private
Friends And Related Symbol Documentation
FAssetCompilingManager
friend class FAssetCompilingManager friend
Definition at line 95 of file StaticMeshCompiler.h.
References FAssetCompilingManager.
Referenced by FAssetCompilingManager.
Field Documentation
bHasShutdown
bool FStaticMeshCompilingManager::bHasShutdown = false private
Definition at line 113 of file StaticMeshCompiler.h.
Notification
TUniquePtr<FAsyncCompilationNotification> FStaticMeshCompilingManager::Notification private
Definition at line 117 of file StaticMeshCompiler.h.
PostReachabilityAnalysisHandle
FDelegateHandle FStaticMeshCompilingManager::PostReachabilityAnalysisHandle private
Definition at line 129 of file StaticMeshCompiler.h.
RegisteredStaticMesh
TSet<TWeakObjectPtr<UStaticMesh> > FStaticMeshCompilingManager::RegisteredStaticMesh private
Definition at line 114 of file StaticMeshCompiler.h.
ReverseDependencyLookup
TMap<TWeakObjectPtr<UStaticMesh>, TSet<TWeakObjectPtr<UStaticMesh> > > FStaticMeshCompilingManager::ReverseDependencyLookup private
Definition at line 116 of file StaticMeshCompiler.h.
StaticMeshesWithPendingDependencies
TSet<TWeakObjectPtr<UStaticMesh> > FStaticMeshCompilingManager::StaticMeshesWithPendingDependencies private
Definition at line 115 of file StaticMeshCompiler.h.
The documentation for this class was generated from the following file:
Runtime/Engine/Public/StaticMeshCompiler.h