Unreal Engine 5.6 C++ API: UUVEditorMeshSelectionMechanic Class Reference
UUVEditorMeshSelectionMechanic Class Reference
Mechanic for selecting elements of a dynamic mesh in the UV editor.
#include "UVEditorMeshSelectionMechanic.h"
Data Structures
struct FRaycastResult
Public Types
using ESelectionMode = UUVToolSelectionAPI::EUVEditorSelectionMode
using FDynamicMeshAABBTree3 = UE::Geometry::FDynamicMeshAABBTree3
using FModeChangeOptions = UUVToolSelectionAPI::FSelectionMechanicModeChangeOptions
using FUVToolSelection = UE::Geometry::FUVToolSelection
Public Member Functions
virtual ~UUVEditorMeshSelectionMechanic ()
virtual FInputRayHit BeginHoverSequenceHitTest (const FInputDeviceRay &PressPos, bool bSourceIsLivePreview)
virtual void DrawHUD (FCanvas *Canvas, IToolsContextRenderAPI *RenderAPI)
TArray< FUVToolSelection > GetAllCanonicalTrianglesInUnwrapRadius (const FVector2d &UnwrapWorldHitPoint, double Radius) const
void Initialize (UWorld *World, UWorld *LivePreviewWorld, UUVToolSelectionAPI *SelectionAPI)
bool IsEnabled ()
virtual FInputRayHit IsHitByClick (const FInputDeviceRay &ClickPos, bool bSourceIsLivePreview)
virtual void LivePreviewDrawHUD (FCanvas *Canvas, IToolsContextRenderAPI *RenderAPI)
virtual void LivePreviewRender (IToolsContextRenderAPI *RenderAPI)
virtual void OnBeginHover (const FInputDeviceRay &DevicePos)
virtual void OnClicked (const FInputDeviceRay &ClickPos, bool bSourceIsLivePreview)
virtual void OnEndHover ()
virtual bool OnUpdateHover (const FInputDeviceRay &DevicePos, bool bSourceIsLivePreview)
virtual void OnUpdateModifierState (int ModifierID, bool bIsOn)
bool RaycastCanonicals (const FRay &WorldRay, bool bRaycastIsForUnwrap, bool bPreferSelected, FRaycastResult &HitOut) const
This is a helper method that doesn't get used in normal selection mechanic operation, but can be used by clients if they need to raycast canonical meshes, since the mechanic already keeps aabb trees for them.
virtual void Render (IToolsContextRenderAPI *RenderAPI) override
void SetIsEnabled (bool bIsEnabled)
void SetSelectionMode (ESelectionMode TargetMode, const FModeChangeOptions &Options=FModeChangeOptions())
Sets selection mode for the mechanic.
void SetShowHoveredElements (bool bShow)
void SetTargets (const TArray< TObjectPtr< UUVEditorToolMeshInput > > &TargetsIn)
virtual void Setup (UInteractiveTool *ParentTool) override
virtual void Shutdown () override
Data Fields
FSimpleMulticastDelegate OnDragSelectionChanged
Broadcasted whenever the marquee mechanic rectangle is changed, since these changes don't trigger normal selection broadcasts.
Protected Member Functions
bool GetHitTid (const FInputDeviceRay &ClickPos, int32 &TidOut, int32 &AssetIDOut, bool bUseUnwrap, int32 *ExistingSelectionObjectIndexOut=nullptr)
TSharedPtr< FDynamicMeshAABBTree3 > GetMeshSpatial (int32 TargetId, bool bUseUnwrap) const
void ModifyExistingSelection (TSet< int32 > &SelectionSetToModify, const TArray< int32 > &SelectedIDs)
void OnDragRectangleChanged (const FCameraRectangle &CurrentRectangle, bool bSourceIsLivePreview)
void OnDragRectangleFinished (const FCameraRectangle &Rectangle, bool bCancelled, bool bSourceIsLivePreview)
void OnDragRectangleStarted ()
bool ShouldAddToSelection () const
bool ShouldRemoveFromSelection () const
bool ShouldRestartSelection () const
bool ShouldToggleFromSelection () const
Protected Attributes
TArray< TSharedPtr< FDynamicMeshAABBTree3 > > AppliedMeshSpatials
TArray< const FUVToolSelection * > AssetIDToPreDragSelection
TArray< const FUVToolSelection * > AssetIDToPreDragUnsetSelection
bool bCtrlToggle = false
bool bIsEnabled = false
bool bShiftToggle = false
bool bShowHoveredElements = true
FViewCameraState CameraState
TObjectPtr< UUVToolEmitChangeAPI > EmitChangeAPI = nullptr
TObjectPtr< APreviewGeometryActor > HoverGeometryActor = nullptr
TWeakObjectPtr< ULineSetComponent > HoverLineSet = nullptr
TWeakObjectPtr< UPointSetComponent > HoverPointSet = nullptr
TWeakObjectPtr< UTriangleSetComponent > HoverTriangleSet = nullptr
TObjectPtr< UMaterialInstanceDynamic > HoverTriangleSetMaterial = nullptr
TObjectPtr< UUVToolLivePreviewAPI > LivePreviewAPI = nullptr
TObjectPtr< UInputBehaviorSet > LivePreviewBehaviorSet = nullptr
TObjectPtr< ULocalInputBehaviorSource > LivePreviewBehaviorSource = nullptr
TObjectPtr< ULocalSingleClickInputBehavior > LivePreviewClickTargetRouter = nullptr
TObjectPtr< ULocalMouseHoverBehavior > LivePreviewHoverBehaviorTargetRouter = nullptr
TObjectPtr< APreviewGeometryActor > LivePreviewHoverGeometryActor = nullptr
TWeakObjectPtr< ULineSetComponent > LivePreviewHoverLineSet = nullptr
TWeakObjectPtr< UPointSetComponent > LivePreviewHoverPointSet = nullptr
TWeakObjectPtr< UTriangleSetComponent > LivePreviewHoverTriangleSet = nullptr
TWeakObjectPtr< UInputRouter > LivePreviewInputRouter = nullptr
TObjectPtr< URectangleMarqueeMechanic > LivePreviewMarqueeMechanic = nullptr
TObjectPtr< URectangleMarqueeMechanic > MarqueeMechanic = nullptr
TArray< FUVToolSelection > PreDragSelections
TArray< FUVToolSelection > PreDragUnsetSelections
TObjectPtr< UUVToolSelectionAPI > SelectionAPI = nullptr
ESelectionMode SelectionMode
TArray< TObjectPtr< UUVEditorToolMeshInput > > Targets
TObjectPtr< ULocalSingleClickInputBehavior > UnwrapClickTargetRouter = nullptr
TObjectPtr< ULocalMouseHoverBehavior > UnwrapHoverBehaviorTargetRouter = nullptr
TArray< TSharedPtr< FDynamicMeshAABBTree3 > > UnwrapMeshSpatials
TObjectPtr< UUVToolViewportButtonsAPI > ViewportButtonsAPI = nullptr
Static Protected Attributes
static const int32 CtrlModifierID = 2
static const int32 ShiftModifierID = 1
Private Attributes
CURRENT_FILE_ID___LINE___GENERATED_BODY
Detailed Description
Mechanic for selecting elements of a dynamic mesh in the UV editor.
Interacts heavily with UUVToolSelectionAPI, which actually stores selections.
Definition at line 34 of file UVEditorMeshSelectionMechanic.h.
Member Typedef Documentation
ESelectionMode
using UUVEditorMeshSelectionMechanic::ESelectionMode = UUVToolSelectionAPI::EUVEditorSelectionMode
Definition at line 76 of file UVEditorMeshSelectionMechanic.h.
FDynamicMeshAABBTree3
using UUVEditorMeshSelectionMechanic::FDynamicMeshAABBTree3 = UE::Geometry::FDynamicMeshAABBTree3
Definition at line 39 of file UVEditorMeshSelectionMechanic.h.
FModeChangeOptions
using UUVEditorMeshSelectionMechanic::FModeChangeOptions = UUVToolSelectionAPI::FSelectionMechanicModeChangeOptions
Definition at line 77 of file UVEditorMeshSelectionMechanic.h.
FUVToolSelection
using UUVEditorMeshSelectionMechanic::FUVToolSelection = UE::Geometry::FUVToolSelection
Definition at line 40 of file UVEditorMeshSelectionMechanic.h.
Constructor & Destructor Documentation
~UUVEditorMeshSelectionMechanic()
virtual UUVEditorMeshSelectionMechanic::~UUVEditorMeshSelectionMechanic () inline virtual
Definition at line 42 of file UVEditorMeshSelectionMechanic.h.
Member Function Documentation
BeginHoverSequenceHitTest()
virtual FInputRayHit UUVEditorMeshSelectionMechanic::BeginHoverSequenceHitTest (const FInputDeviceRay & PressPos, bool bSourceIsLivePreview) virtual
DrawHUD()
virtual void UUVEditorMeshSelectionMechanic::DrawHUD (FCanvas * Canvas, IToolsContextRenderAPI * RenderAPI) virtual
GetAllCanonicalTrianglesInUnwrapRadius()
TArray< FUVToolSelection > UUVEditorMeshSelectionMechanic::GetAllCanonicalTrianglesInUnwrapRadius (const FVector2d & UnwrapWorldHitPoint, double Radius) const
GetHitTid()
bool UUVEditorMeshSelectionMechanic::GetHitTid (const FInputDeviceRay & ClickPos, int32 & TidOut, int32 & AssetIDOut, bool bUseUnwrap, int32 * ExistingSelectionObjectIndexOut = nullptr) protected
References GetHitTid().
Referenced by GetHitTid().
GetMeshSpatial()
TSharedPtr< FDynamicMeshAABBTree3 > UUVEditorMeshSelectionMechanic::GetMeshSpatial (int32 TargetId, bool bUseUnwrap) const protected
References GetMeshSpatial().
Referenced by GetMeshSpatial().
Initialize()
void UUVEditorMeshSelectionMechanic::Initialize (UWorld * World, UWorld * LivePreviewWorld, UUVToolSelectionAPI * SelectionAPI)
References SelectionAPI.
IsEnabled()
bool UUVEditorMeshSelectionMechanic::IsEnabled () inline
Definition at line 55 of file UVEditorMeshSelectionMechanic.h.
References bIsEnabled.
IsHitByClick()
virtual FInputRayHit UUVEditorMeshSelectionMechanic::IsHitByClick (const FInputDeviceRay & ClickPos, bool bSourceIsLivePreview) virtual
LivePreviewDrawHUD()
virtual void UUVEditorMeshSelectionMechanic::LivePreviewDrawHUD (FCanvas * Canvas, IToolsContextRenderAPI * RenderAPI) virtual
LivePreviewRender()
virtual void UUVEditorMeshSelectionMechanic::LivePreviewRender (IToolsContextRenderAPI * RenderAPI) virtual
ModifyExistingSelection()
void UUVEditorMeshSelectionMechanic::ModifyExistingSelection (TSet< int32 > & SelectionSetToModify, const TArray< int32 > & SelectedIDs) protected
References ModifyExistingSelection().
Referenced by ModifyExistingSelection().
OnBeginHover()
virtual void UUVEditorMeshSelectionMechanic::OnBeginHover (const FInputDeviceRay & DevicePos) virtual
OnClicked()
virtual void UUVEditorMeshSelectionMechanic::OnClicked (const FInputDeviceRay & ClickPos, bool bSourceIsLivePreview) virtual
OnDragRectangleChanged()
void UUVEditorMeshSelectionMechanic::OnDragRectangleChanged (const FCameraRectangle & CurrentRectangle, bool bSourceIsLivePreview) protected
OnDragRectangleFinished()
void UUVEditorMeshSelectionMechanic::OnDragRectangleFinished (const FCameraRectangle & Rectangle, bool bCancelled, bool bSourceIsLivePreview) protected
OnDragRectangleStarted()
void UUVEditorMeshSelectionMechanic::OnDragRectangleStarted () protected
OnEndHover()
virtual void UUVEditorMeshSelectionMechanic::OnEndHover () virtual
OnUpdateHover()
virtual bool UUVEditorMeshSelectionMechanic::OnUpdateHover (const FInputDeviceRay & DevicePos, bool bSourceIsLivePreview) virtual
OnUpdateModifierState()
virtual void UUVEditorMeshSelectionMechanic::OnUpdateModifierState (int ModifierID, bool bIsOn) virtual
RaycastCanonicals()
bool UUVEditorMeshSelectionMechanic::RaycastCanonicals (const FRay & WorldRay, bool bRaycastIsForUnwrap, bool bPreferSelected, FRaycastResult & HitOut) const
This is a helper method that doesn't get used in normal selection mechanic operation, but can be used by clients if they need to raycast canonical meshes, since the mechanic already keeps aabb trees for them.
The mechanic does not need to be enabled to use this (and typically will not be, if a tool is doing its own raycasting).
Render()
virtual void UUVEditorMeshSelectionMechanic::Render (IToolsContextRenderAPI * RenderAPI) override virtual
SetIsEnabled()
void UUVEditorMeshSelectionMechanic::SetIsEnabled (bool bIsEnabled)
References bIsEnabled.
SetSelectionMode()
void UUVEditorMeshSelectionMechanic::SetSelectionMode (ESelectionMode TargetMode, const FModeChangeOptions & Options = FModeChangeOptions())
Sets selection mode for the mechanic.
SetShowHoveredElements()
void UUVEditorMeshSelectionMechanic::SetShowHoveredElements (bool bShow)
SetTargets()
void UUVEditorMeshSelectionMechanic::SetTargets (const TArray< TObjectPtr< UUVEditorToolMeshInput > > & TargetsIn)
Setup()
virtual void UUVEditorMeshSelectionMechanic::Setup (UInteractiveTool * ParentTool) override virtual
ShouldAddToSelection()
bool UUVEditorMeshSelectionMechanic::ShouldAddToSelection () const inline protected
Definition at line 186 of file UVEditorMeshSelectionMechanic.h.
References bCtrlToggle, bShiftToggle, and ShouldAddToSelection().
Referenced by ShouldAddToSelection().
ShouldRemoveFromSelection()
bool UUVEditorMeshSelectionMechanic::ShouldRemoveFromSelection () const inline protected
Definition at line 187 of file UVEditorMeshSelectionMechanic.h.
References bCtrlToggle, and bShiftToggle.
ShouldRestartSelection()
bool UUVEditorMeshSelectionMechanic::ShouldRestartSelection () const inline protected
Definition at line 189 of file UVEditorMeshSelectionMechanic.h.
References bCtrlToggle, and bShiftToggle.
ShouldToggleFromSelection()
bool UUVEditorMeshSelectionMechanic::ShouldToggleFromSelection () const inline protected
Definition at line 188 of file UVEditorMeshSelectionMechanic.h.
References bCtrlToggle, and bShiftToggle.
Shutdown()
virtual void UUVEditorMeshSelectionMechanic::Shutdown () override virtual
Field Documentation
AppliedMeshSpatials
TArray<TSharedPtr<FDynamicMeshAABBTree3> > UUVEditorMeshSelectionMechanic::AppliedMeshSpatials protected
Definition at line 168 of file UVEditorMeshSelectionMechanic.h.
AssetIDToPreDragSelection
TArray<const FUVToolSelection*> UUVEditorMeshSelectionMechanic::AssetIDToPreDragSelection protected
Definition at line 200 of file UVEditorMeshSelectionMechanic.h.
AssetIDToPreDragUnsetSelection
TArray<const FUVToolSelection*> UUVEditorMeshSelectionMechanic::AssetIDToPreDragUnsetSelection protected
Definition at line 201 of file UVEditorMeshSelectionMechanic.h.
bCtrlToggle
bool UUVEditorMeshSelectionMechanic::bCtrlToggle = false protected
Definition at line 181 of file UVEditorMeshSelectionMechanic.h.
Referenced by ShouldAddToSelection(), ShouldRemoveFromSelection(), ShouldRestartSelection(), and ShouldToggleFromSelection().
bIsEnabled
bool UUVEditorMeshSelectionMechanic::bIsEnabled = false protected
Definition at line 171 of file UVEditorMeshSelectionMechanic.h.
Referenced by IsEnabled(), and SetIsEnabled().
bShiftToggle
bool UUVEditorMeshSelectionMechanic::bShiftToggle = false protected
Definition at line 180 of file UVEditorMeshSelectionMechanic.h.
Referenced by ShouldAddToSelection(), ShouldRemoveFromSelection(), ShouldRestartSelection(), and ShouldToggleFromSelection().
bShowHoveredElements
bool UUVEditorMeshSelectionMechanic::bShowHoveredElements = true protected
Definition at line 172 of file UVEditorMeshSelectionMechanic.h.
CameraState
FViewCameraState UUVEditorMeshSelectionMechanic::CameraState protected
Definition at line 178 of file UVEditorMeshSelectionMechanic.h.
CtrlModifierID
const int32 UUVEditorMeshSelectionMechanic::CtrlModifierID = 2 static protected
Definition at line 183 of file UVEditorMeshSelectionMechanic.h.
CURRENT_FILE_ID___LINE___GENERATED_BODY
UUVEditorMeshSelectionMechanic::CURRENT_FILE_ID___LINE___GENERATED_BODY private
Definition at line 36 of file UVEditorMeshSelectionMechanic.h.
EmitChangeAPI
TObjectPtr<UUVToolEmitChangeAPI> UUVEditorMeshSelectionMechanic::EmitChangeAPI = nullptr protected
Definition at line 116 of file UVEditorMeshSelectionMechanic.h.
HoverGeometryActor
TObjectPtr<APreviewGeometryActor> UUVEditorMeshSelectionMechanic::HoverGeometryActor = nullptr protected
Definition at line 143 of file UVEditorMeshSelectionMechanic.h.
HoverLineSet
TWeakObjectPtr<ULineSetComponent> UUVEditorMeshSelectionMechanic::HoverLineSet = nullptr protected
Definition at line 146 of file UVEditorMeshSelectionMechanic.h.
HoverPointSet
TWeakObjectPtr<UPointSetComponent> UUVEditorMeshSelectionMechanic::HoverPointSet = nullptr protected
Definition at line 147 of file UVEditorMeshSelectionMechanic.h.
HoverTriangleSet
TWeakObjectPtr<UTriangleSetComponent> UUVEditorMeshSelectionMechanic::HoverTriangleSet = nullptr protected
Definition at line 145 of file UVEditorMeshSelectionMechanic.h.
HoverTriangleSetMaterial
TObjectPtr<UMaterialInstanceDynamic> UUVEditorMeshSelectionMechanic::HoverTriangleSetMaterial = nullptr protected
Definition at line 140 of file UVEditorMeshSelectionMechanic.h.
LivePreviewAPI
TObjectPtr<UUVToolLivePreviewAPI> UUVEditorMeshSelectionMechanic::LivePreviewAPI = nullptr protected
Definition at line 119 of file UVEditorMeshSelectionMechanic.h.
LivePreviewBehaviorSet
TObjectPtr<UInputBehaviorSet> UUVEditorMeshSelectionMechanic::LivePreviewBehaviorSet = nullptr protected
Definition at line 150 of file UVEditorMeshSelectionMechanic.h.
LivePreviewBehaviorSource
TObjectPtr<ULocalInputBehaviorSource> UUVEditorMeshSelectionMechanic::LivePreviewBehaviorSource = nullptr protected
Definition at line 153 of file UVEditorMeshSelectionMechanic.h.
LivePreviewClickTargetRouter
TObjectPtr<ULocalSingleClickInputBehavior> UUVEditorMeshSelectionMechanic::LivePreviewClickTargetRouter = nullptr protected
Definition at line 125 of file UVEditorMeshSelectionMechanic.h.
LivePreviewHoverBehaviorTargetRouter
TObjectPtr<ULocalMouseHoverBehavior> UUVEditorMeshSelectionMechanic::LivePreviewHoverBehaviorTargetRouter = nullptr protected
Definition at line 131 of file UVEditorMeshSelectionMechanic.h.
LivePreviewHoverGeometryActor
TObjectPtr<APreviewGeometryActor> UUVEditorMeshSelectionMechanic::LivePreviewHoverGeometryActor = nullptr protected
Definition at line 158 of file UVEditorMeshSelectionMechanic.h.
LivePreviewHoverLineSet
TWeakObjectPtr<ULineSetComponent> UUVEditorMeshSelectionMechanic::LivePreviewHoverLineSet = nullptr protected
Definition at line 161 of file UVEditorMeshSelectionMechanic.h.
LivePreviewHoverPointSet
TWeakObjectPtr<UPointSetComponent> UUVEditorMeshSelectionMechanic::LivePreviewHoverPointSet = nullptr protected
Definition at line 162 of file UVEditorMeshSelectionMechanic.h.
LivePreviewHoverTriangleSet
TWeakObjectPtr<UTriangleSetComponent> UUVEditorMeshSelectionMechanic::LivePreviewHoverTriangleSet = nullptr protected
Definition at line 160 of file UVEditorMeshSelectionMechanic.h.
LivePreviewInputRouter
TWeakObjectPtr<UInputRouter> UUVEditorMeshSelectionMechanic::LivePreviewInputRouter = nullptr protected
Definition at line 155 of file UVEditorMeshSelectionMechanic.h.
LivePreviewMarqueeMechanic
TObjectPtr<URectangleMarqueeMechanic> UUVEditorMeshSelectionMechanic::LivePreviewMarqueeMechanic = nullptr protected
Definition at line 137 of file UVEditorMeshSelectionMechanic.h.
MarqueeMechanic
TObjectPtr<URectangleMarqueeMechanic> UUVEditorMeshSelectionMechanic::MarqueeMechanic = nullptr protected
Definition at line 134 of file UVEditorMeshSelectionMechanic.h.
OnDragSelectionChanged
FSimpleMulticastDelegate UUVEditorMeshSelectionMechanic::OnDragSelectionChanged
Broadcasted whenever the marquee mechanic rectangle is changed, since these changes don't trigger normal selection broadcasts.
Definition at line 105 of file UVEditorMeshSelectionMechanic.h.
PreDragSelections
TArray<FUVToolSelection> UUVEditorMeshSelectionMechanic::PreDragSelections protected
Definition at line 196 of file UVEditorMeshSelectionMechanic.h.
PreDragUnsetSelections
TArray<FUVToolSelection> UUVEditorMeshSelectionMechanic::PreDragUnsetSelections protected
Definition at line 197 of file UVEditorMeshSelectionMechanic.h.
SelectionAPI
TObjectPtr<UUVToolSelectionAPI> UUVEditorMeshSelectionMechanic::SelectionAPI = nullptr protected
Definition at line 110 of file UVEditorMeshSelectionMechanic.h.
Referenced by Initialize().
SelectionMode
ESelectionMode UUVEditorMeshSelectionMechanic::SelectionMode protected
Definition at line 170 of file UVEditorMeshSelectionMechanic.h.
ShiftModifierID
const int32 UUVEditorMeshSelectionMechanic::ShiftModifierID = 1 static protected
Definition at line 182 of file UVEditorMeshSelectionMechanic.h.
Targets
TArray<TObjectPtr<UUVEditorToolMeshInput> > UUVEditorMeshSelectionMechanic::Targets protected
Definition at line 166 of file UVEditorMeshSelectionMechanic.h.
UnwrapClickTargetRouter
TObjectPtr<ULocalSingleClickInputBehavior> UUVEditorMeshSelectionMechanic::UnwrapClickTargetRouter = nullptr protected
Definition at line 122 of file UVEditorMeshSelectionMechanic.h.
UnwrapHoverBehaviorTargetRouter
TObjectPtr<ULocalMouseHoverBehavior> UUVEditorMeshSelectionMechanic::UnwrapHoverBehaviorTargetRouter = nullptr protected
Definition at line 128 of file UVEditorMeshSelectionMechanic.h.
UnwrapMeshSpatials
TArray<TSharedPtr<FDynamicMeshAABBTree3> > UUVEditorMeshSelectionMechanic::UnwrapMeshSpatials protected
Definition at line 167 of file UVEditorMeshSelectionMechanic.h.
ViewportButtonsAPI
TObjectPtr<UUVToolViewportButtonsAPI> UUVEditorMeshSelectionMechanic::ViewportButtonsAPI = nullptr protected
Definition at line 113 of file UVEditorMeshSelectionMechanic.h.
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Editor/UVEditor/Source/UVEditorTools/Public/Selection/UVEditorMeshSelectionMechanic.h