Unreal Engine 5.6 C++ API: FCursorReply Class Reference
FCursorReply Class Reference
A reply to the OnQueryCursor event.
#include "CursorReply.h"
Public Member Functions
EMouseCursor::Type GetCursorType () const
TSharedPtr< SWidget > GetCursorWidget () const
TSharedPtr< SWindow > GetCursorWindow () const
void SetCursorWidget (TSharedPtr< SWindow > InCursorWindow, TSharedPtr< SWidget > InCursorWidget)
Set the Cursor Widget, used by slate application to set the cursor widget if the MapCursor returns a widget.
Public Member Functions inherited from TReplyBase< FCursorReply >
TReplyBase (bool bIsHandled)
Public Member Functions inherited from FReplyBase
const TSharedPtr< SWidget > GetHandler () const
The widget that ultimately handled the event.
bool IsEventHandled () const
Static Public Member Functions
static FCursorReply Cursor (EMouseCursor::Type InCursor)
Respond with a specific cursor.
static FCursorReply Unhandled ()
Makes a NULL response meaning no prefersce.
Private Member Functions
FCursorReply ()
Internal constructor - makes a NULL result.
FCursorReply (EMouseCursor::Type InCursorType)
Internal constructor - makes a non-NULL result.
Private Attributes
TSharedPtr< SWidget > CursorWidget
Custom widget to render for cursor.
TSharedPtr< SWindow > CursorWindow
Window to render for cursor.
EMouseCursor::Type MouseCursor
The cursor type must be set is CursorWidget is invalid.
Additional Inherited Members
Protected Member Functions inherited from TReplyBase< FCursorReply >
FCursorReply & Me ()
FCursorReply & SetHandler (const TSharedRef< SWidget > &InHandler)
Set the widget that handled the event; undefined if never handled.
Protected Member Functions inherited from FReplyBase
FReplyBase (bool InIsHandled)
A reply can be handled or unhandled.
Protected Attributes inherited from FReplyBase
bool bIsHandled
Has a widget handled an event.
TSharedPtr< SWidget > EventHandler
Widget that handled the event that generated this reply.
Detailed Description
A reply to the OnQueryCursor event.
Definition at line 15 of file CursorReply.h.
Constructor & Destructor Documentation
FCursorReply() [1/2]
FCursorReply::FCursorReply () inline private
Internal constructor - makes a NULL result.
Definition at line 53 of file CursorReply.h.
References FCursorReply(), TReplyBase< FCursorReply >::TReplyBase(), Default, and MouseCursor.
Referenced by FCursorReply(), FCursorReply(), Cursor(), and Unhandled().
FCursorReply() [2/2]
FCursorReply::FCursorReply (EMouseCursor::Type InCursorType) inline private
Internal constructor - makes a non-NULL result.
Definition at line 59 of file CursorReply.h.
References FCursorReply(), TReplyBase< FCursorReply >::TReplyBase(), and MouseCursor.
Member Function Documentation
Cursor()
FCursorReply FCursorReply::Cursor (EMouseCursor::Type InCursor) inline static
Respond with a specific cursor.
This cursor will be used and no other widgets will be asked.
Definition at line 33 of file CursorReply.h.
References FCursorReply().
Referenced by SHyperlink::OnCursorQuery().
GetCursorType()
EMouseCursor::Type FCursorReply::GetCursorType () const inline
Returns
The requested MouseCursor if no custom widget is set and the event was handled.
Definition at line 45 of file CursorReply.h.
References MouseCursor.
GetCursorWidget()
TSharedPtr< SWidget > FCursorReply::GetCursorWidget () const inline
Returns
The custom Cursor Widget to render if set and the event was handled.
Definition at line 42 of file CursorReply.h.
References CursorWidget.
GetCursorWindow()
TSharedPtr< SWindow > FCursorReply::GetCursorWindow () const inline
Returns
The window to render the Cursor Widget in.
Definition at line 39 of file CursorReply.h.
References CursorWindow.
SetCursorWidget()
void FCursorReply::SetCursorWidget (TSharedPtr< SWindow > InCursorWindow, TSharedPtr< SWidget > InCursorWidget) inline
Set the Cursor Widget, used by slate application to set the cursor widget if the MapCursor returns a widget.
Definition at line 48 of file CursorReply.h.
References CursorWidget, and CursorWindow.
Unhandled()
FCursorReply FCursorReply::Unhandled () inline static
Makes a NULL response meaning no prefersce.
i.e. If your widget returns this, its parent will get to decide what the cursor shoudl be. This is the default behavior for a widget.
Definition at line 24 of file CursorReply.h.
References FCursorReply().
Referenced by UE::Sequencer::ITrackAreaHotspot::GetCursor(), and ISlateViewport::OnCursorQuery().
Field Documentation
CursorWidget
TSharedPtr<SWidget> FCursorReply::CursorWidget private
Custom widget to render for cursor.
Definition at line 68 of file CursorReply.h.
Referenced by GetCursorWidget(), and SetCursorWidget().
CursorWindow
TSharedPtr<SWindow> FCursorReply::CursorWindow private
Window to render for cursor.
Definition at line 65 of file CursorReply.h.
Referenced by GetCursorWindow(), and SetCursorWidget().
MouseCursor
EMouseCursor::Type FCursorReply::MouseCursor private
The cursor type must be set is CursorWidget is invalid.
Definition at line 71 of file CursorReply.h.
Referenced by FCursorReply(), FCursorReply(), and GetCursorType().
The documentation for this class was generated from the following file:
Runtime/SlateCore/Public/Input/CursorReply.h