Unreal Engine 5.6 C++ API: FPublicExportKey Class Reference
FPublicExportKey Class Reference
#include "AsyncLoading2.h"
Public Member Functions
FPublicExportKey ()
uint64 GetExportHash () const
FPackageId GetPackageId () const
bool IsNull () const
bool operator!= (const FPublicExportKey &Other) const
bool operator== (const FPublicExportKey &Other) const
Static Public Member Functions
static FPublicExportKey FromPackageImport (FPackageObjectIndex ObjectIndex, const TArrayView< const FPackageId > &ImportedPackageIds, const TArrayView< const uint64 > &ImportedPublicExportHashes)
static FPublicExportKey MakeKey (FPackageId PackageId, uint64 ExportHash)
Private Member Functions
FPublicExportKey (uint32 InPackageIdHigh, uint32 InPackageIdLow, uint32 InExportHashHigh, uint32 InExportHashLow)
Private Attributes
uint32 ExportHashHigh = 0
uint32 ExportHashLow = 0
uint32 PackageIdHigh = 0
uint32 PackageIdLow = 0
Friends
uint32 GetTypeHash (const FPublicExportKey &In)
Detailed Description
Definition at line 180 of file AsyncLoading2.h.
Constructor & Destructor Documentation
FPublicExportKey() [1/2]
FPublicExportKey::FPublicExportKey () inline
Definition at line 183 of file AsyncLoading2.h.
Referenced by FromPackageImport(), GetTypeHash, MakeKey(), operator!=(), and operator==().
FPublicExportKey() [2/2]
FPublicExportKey::FPublicExportKey (uint32 InPackageIdHigh, uint32 InPackageIdLow, uint32 InExportHashHigh, uint32 InExportHashLow) inline private
Definition at line 237 of file AsyncLoading2.h.
References ExportHashHigh, ExportHashLow, PackageIdHigh, and PackageIdLow.
Member Function Documentation
FromPackageImport()
FPublicExportKey FPublicExportKey::FromPackageImport (FPackageObjectIndex ObjectIndex, const TArrayView< const FPackageId > & ImportedPackageIds, const TArrayView< const uint64 > & ImportedPublicExportHashes) inline static
Definition at line 227 of file AsyncLoading2.h.
References FPublicExportKey(), check, FPackageImportReference::GetImportedPackageIndex(), FPackageImportReference::GetImportedPublicExportHashIndex(), FPackageObjectIndex::IsPackageImport(), MakeKey(), and FPackageObjectIndex::ToPackageImportRef().
GetExportHash()
uint64 FPublicExportKey::GetExportHash () const inline
Definition at line 197 of file AsyncLoading2.h.
References ExportHashHigh, and ExportHashLow.
Referenced by GetTypeHash, IsNull(), operator!=(), and operator==().
GetPackageId()
FPackageId FPublicExportKey::GetPackageId () const inline
Definition at line 192 of file AsyncLoading2.h.
References FPackageId::FromValue(), PackageIdHigh, and PackageIdLow.
Referenced by GetTypeHash, operator!=(), and operator==().
IsNull()
bool FPublicExportKey::IsNull () const inline
Definition at line 187 of file AsyncLoading2.h.
References GetExportHash().
MakeKey()
FPublicExportKey FPublicExportKey::MakeKey (FPackageId PackageId, uint64 ExportHash) inline static
Definition at line 219 of file AsyncLoading2.h.
References FPublicExportKey(), check, FPackageId::IsValid(), and FPackageId::Value().
Referenced by FromPackageImport().
operator!=()
bool FPublicExportKey::operator!= (const FPublicExportKey & Other) const inline
Definition at line 208 of file AsyncLoading2.h.
References FPublicExportKey(), GetExportHash(), GetPackageId(), and Other.
operator==()
bool FPublicExportKey::operator== (const FPublicExportKey & Other) const inline
Definition at line 202 of file AsyncLoading2.h.
References FPublicExportKey(), GetExportHash(), GetPackageId(), and Other.
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FPublicExportKey & In) friend
Definition at line 214 of file AsyncLoading2.h.
References FPublicExportKey(), GetExportHash(), GetPackageId(), GetTypeHash, and HashCombine().
Referenced by GetTypeHash.
Field Documentation
ExportHashHigh
uint32 FPublicExportKey::ExportHashHigh = 0 private
Definition at line 247 of file AsyncLoading2.h.
Referenced by FPublicExportKey(), and GetExportHash().
ExportHashLow
uint32 FPublicExportKey::ExportHashLow = 0 private
Definition at line 248 of file AsyncLoading2.h.
Referenced by FPublicExportKey(), and GetExportHash().
PackageIdHigh
uint32 FPublicExportKey::PackageIdHigh = 0 private
Definition at line 245 of file AsyncLoading2.h.
Referenced by FPublicExportKey(), and GetPackageId().
PackageIdLow
uint32 FPublicExportKey::PackageIdLow = 0 private
Definition at line 246 of file AsyncLoading2.h.
Referenced by FPublicExportKey(), and GetPackageId().
The documentation for this class was generated from the following file:
Runtime/CoreUObject/Public/Serialization/AsyncLoading2.h