Unreal Engine 5.6 C++ API: FChunkedFixedUObjectArray Class Reference
FChunkedFixedUObjectArray Class Reference
Simple array type that can be expanded without invalidating existing entries.
#include "UObjectArray.h"
Public Member Functions
FChunkedFixedUObjectArray ()
Constructor : Probably not thread safe.
~FChunkedFixedUObjectArray ()
int32 AddRange (int32 NumToAdd)
int32 AddSingle ()
FORCEINLINE int32 Capacity () const
Return the number max capacity of the array Thread safe, but you know, someone might have added more elements before this even returns.
int64 GetAllocatedSize () const
FORCEINLINE_DEBUGGABLE FUObjectItem * GetObjectPtr (int32 Index)
FORCEINLINE_DEBUGGABLE FUObjectItem const * GetObjectPtr (int32 Index) const
Return a pointer to the pointer to a given element.
FUObjectItem *** GetRootBlockForDebuggerVisualizers ()
Return a naked pointer to the fundamental data structure for debug visualizers.
FORCEINLINE bool IsValidIndex (int32 Index) const
Return if this index is valid Thread safe, if it is valid now, it is valid forever.
FORCEINLINE int32 Num () const
Return the number of elements in the array Thread safe, but you know, someone might have added more elements before this even returns.
FORCEINLINE FUObjectItem & operator[] (int32 Index)
FORCEINLINE FUObjectItem const & operator[] (int32 Index) const
Return a reference to an element.
void PreAllocate (int32 InMaxElements, bool bPreAllocateChunks)
Expands the array so that Element[Index] is allocated.
FORCEINLINE_DEBUGGABLE void PrefetchObjectPtr (int32 Index) const
Private Types
enum { NumElementsPerChunk = 64 * 1024 }
Private Member Functions
void ExpandChunksToIndex (int32 Index)
Allocates new chunk for the array.
TSAN_ATOMIC (int32) MaxElements
Maximum number of elements.
TSAN_ATOMIC (int32) NumChunks
Number of chunks we currently have.
TSAN_ATOMIC (int32) NumElements
Number of elements we currently have.
Private Attributes
int32 MaxChunks
Maximum number of chunks.
FUObjectItem ** Objects
Primary table to chunks of pointers.
FUObjectItem * PreAllocatedObjects
If requested, a contiguous memory where all objects are allocated.
Static Private Attributes
static constexpr bool bFUObjectItemIsPacked = 0
Detailed Description
Simple array type that can be expanded without invalidating existing entries.
This is critical to thread safe FNames.
Parameters
ElementType Type of the pointer we are storing in the array
MaxTotalElements absolute maximum number of elements this array can ever hold
ElementsPerChunk how many elements to allocate in a chunk
Definition at line 661 of file UObjectArray.h.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
NumElementsPerChunk
Definition at line 663 of file UObjectArray.h.
Constructor & Destructor Documentation
FChunkedFixedUObjectArray()
FChunkedFixedUObjectArray::FChunkedFixedUObjectArray () inline
Constructor : Probably not thread safe.
Definition at line 713 of file UObjectArray.h.
References MaxChunks, Objects, and PreAllocatedObjects.
~FChunkedFixedUObjectArray()
FChunkedFixedUObjectArray::~FChunkedFixedUObjectArray () inline
Definition at line 723 of file UObjectArray.h.
References MaxChunks, Objects, and PreAllocatedObjects.
Member Function Documentation
AddRange()
int32 FChunkedFixedUObjectArray::AddRange (int32 NumToAdd) inline
Definition at line 847 of file UObjectArray.h.
References UE::UObjectArrayPrivate::CheckUObjectLimitReached(), and ExpandChunksToIndex().
Referenced by AddSingle().
AddSingle()
int32 FChunkedFixedUObjectArray::AddSingle () inline
Definition at line 856 of file UObjectArray.h.
References AddRange().
Capacity()
FORCEINLINE int32 FChunkedFixedUObjectArray::Capacity () const inline
Return the number max capacity of the array Thread safe, but you know, someone might have added more elements before this even returns.
Returns
the maximum number of elements in the array
Definition at line 777 of file UObjectArray.h.
References FORCEINLINE.
ExpandChunksToIndex()
void FChunkedFixedUObjectArray::ExpandChunksToIndex (int32 Index) inline private
Allocates new chunk for the array.
Definition at line 687 of file UObjectArray.h.
References check, MaxChunks, NumElementsPerChunk, and Objects.
Referenced by AddRange().
GetAllocatedSize()
int64 FChunkedFixedUObjectArray::GetAllocatedSize () const inline
Definition at line 869 of file UObjectArray.h.
References MaxChunks, and NumElementsPerChunk.
GetObjectPtr() [1/2]
FORCEINLINE_DEBUGGABLE FUObjectItem * FChunkedFixedUObjectArray::GetObjectPtr (int32 Index) inline
Definition at line 808 of file UObjectArray.h.
References check, checkf, FORCEINLINE_DEBUGGABLE, IsValidIndex(), NumElementsPerChunk, Objects, and TEXT.
GetObjectPtr() [2/2]
FORCEINLINE_DEBUGGABLE FUObjectItem const * FChunkedFixedUObjectArray::GetObjectPtr (int32 Index) const inline
Return a pointer to the pointer to a given element.
Parameters
Index The Index of an element we want to retrieve the pointer-to-pointer for
Definition at line 797 of file UObjectArray.h.
References check, checkf, FORCEINLINE_DEBUGGABLE, IsValidIndex(), NumElementsPerChunk, Objects, and TEXT.
Referenced by operator[](), and operator[]().
GetRootBlockForDebuggerVisualizers()
FUObjectItem *** FChunkedFixedUObjectArray::GetRootBlockForDebuggerVisualizers () inline
Return a naked pointer to the fundamental data structure for debug visualizers.
Definition at line 864 of file UObjectArray.h.
IsValidIndex()
FORCEINLINE bool FChunkedFixedUObjectArray::IsValidIndex (int32 Index) const inline
Return if this index is valid Thread safe, if it is valid now, it is valid forever.
Other threads might be adding during this call.
Parameters
Index Index to test
Returns
true, if this is a valid
Definition at line 788 of file UObjectArray.h.
References FORCEINLINE, and Num.
Referenced by GetObjectPtr(), and GetObjectPtr().
Num()
FORCEINLINE int32 FChunkedFixedUObjectArray::Num () const inline
Return the number of elements in the array Thread safe, but you know, someone might have added more elements before this even returns.
Returns
the number of elements in the array
Definition at line 767 of file UObjectArray.h.
References FORCEINLINE.
operator[]() [1/2]
FORCEINLINE FUObjectItem & FChunkedFixedUObjectArray::operator[] (int32 Index) inline
Definition at line 840 of file UObjectArray.h.
References check, FORCEINLINE, and GetObjectPtr().
operator[]() [2/2]
FORCEINLINE FUObjectItem const & FChunkedFixedUObjectArray::operator[] (int32 Index) const inline
Return a reference to an element.
Parameters
Index Index to return
Returns
a reference to the pointer to the element Thread safe, if it is valid now, it is valid forever. This might return nullptr, but by then, some other thread might have made it non-nullptr.
Definition at line 834 of file UObjectArray.h.
References check, FORCEINLINE, and GetObjectPtr().
PreAllocate()
void FChunkedFixedUObjectArray::PreAllocate (int32 InMaxElements, bool bPreAllocateChunks) inline
Expands the array so that Element[Index] is allocated.
New pointers are all zero.
Parameters
Index The Index of an element we want to be sure is allocated
Definition at line 743 of file UObjectArray.h.
References check, MaxChunks, FMemory::Memzero(), NumElementsPerChunk, Objects, and PreAllocatedObjects.
PrefetchObjectPtr()
FORCEINLINE_DEBUGGABLE void FChunkedFixedUObjectArray::PrefetchObjectPtr (int32 Index) const inline
Definition at line 820 of file UObjectArray.h.
References FORCEINLINE_DEBUGGABLE, NumElementsPerChunk, Objects, and FGenericPlatformMisc::Prefetch().
TSAN_ATOMIC() [1/3]
FChunkedFixedUObjectArray::TSAN_ATOMIC (int32) private
Maximum number of elements.
TSAN_ATOMIC() [2/3]
FChunkedFixedUObjectArray::TSAN_ATOMIC (int32) private
Number of chunks we currently have.
TSAN_ATOMIC() [3/3]
FChunkedFixedUObjectArray::TSAN_ATOMIC (int32) private
Number of elements we currently have.
Field Documentation
bFUObjectItemIsPacked
bool FChunkedFixedUObjectArray::bFUObjectItemIsPacked = 0 static constexpr private
Definition at line 681 of file UObjectArray.h.
MaxChunks
int32 FChunkedFixedUObjectArray::MaxChunks private
Maximum number of chunks.
Definition at line 677 of file UObjectArray.h.
Referenced by FChunkedFixedUObjectArray(), ~FChunkedFixedUObjectArray(), ExpandChunksToIndex(), GetAllocatedSize(), and PreAllocate().
Objects
FUObjectItem** FChunkedFixedUObjectArray::Objects private
Primary table to chunks of pointers.
Definition at line 669 of file UObjectArray.h.
Referenced by FChunkedFixedUObjectArray(), ~FChunkedFixedUObjectArray(), ExpandChunksToIndex(), GetObjectPtr(), GetObjectPtr(), PreAllocate(), and PrefetchObjectPtr().
PreAllocatedObjects
FUObjectItem* FChunkedFixedUObjectArray::PreAllocatedObjects private
If requested, a contiguous memory where all objects are allocated.
Definition at line 671 of file UObjectArray.h.
Referenced by FChunkedFixedUObjectArray(), ~FChunkedFixedUObjectArray(), and PreAllocate().
The documentation for this class was generated from the following file:
Runtime/CoreUObject/Public/UObject/UObjectArray.h