Unreal Engine 5.6 C++ API: FMediaIOAudioOutput Class Reference
FMediaIOAudioOutput Class Reference
#include "MediaIOCoreAudioOutput.h"
Data Structures
struct FAudioOptions
struct TSampleConverter
Sample conversion helper template.
struct TSampleConverter< float >
Specialization for float buffers.
Public Member Functions
FMediaIOAudioOutput (Audio::FPatchOutputStrongPtr InPatchOutput, const FAudioOptions &InAudioOptions)
template<typename OutputType>
TArray< OutputType > GetAllAudioSamples () const
template<typename OutputType>
TArray< OutputType > GetAudioSamples () const
Get the audio sample that were accumulated.
template<typename OutputType>
TArray< OutputType > GetAudioSamples (uint32 NumSamplesToGet) const
UE_DEPRECATED (5.6, "This function is deprecated because it is not implemented. Use UMediaIOCoreSubsystem::OnBufferReceived() instead.") FOnBufferReceived &OnBufferReceived()
Static Public Member Functions
template<typename OutputType>
static TArray< OutputType > ConvertAndUpmixBuffer (TConstArrayView< float > InBuffer, int32 InNumInputChannels, int32 InNumOutputChannels)
Data Fields
uint32 MaxSampleLatency
Maximum number of samples to accumulate before they are discarded.
int32 NumInputChannels
Number of audio channels on the engine side.
int32 NumOutputChannels
Number of audio channels to output.
int32 NumSamplesPerFrame = 0
uint32 OutputSampleRate
FFrameRate TargetFrameRate
Private Member Functions
int32 GetAudioBuffer (int32 InNumSamplesToPop, float *OutBuffer) const
Audio::FAlignedFloatBuffer GetFloatBuffer (uint32 NumSamplesToGet) const
Private Attributes
FOnBufferReceived BufferReceivedDelegate
Callback called when a buffer is received.
Audio::FPatchOutputStrongPtr PatchOutput
The buffer accumulating audio samples.
Detailed Description
Definition at line 22 of file MediaIOCoreAudioOutput.h.
Constructor & Destructor Documentation
FMediaIOAudioOutput()
FMediaIOAudioOutput::FMediaIOAudioOutput (Audio::FPatchOutputStrongPtr InPatchOutput, const FAudioOptions & InAudioOptions)
Member Function Documentation
ConvertAndUpmixBuffer()
template<typename OutputType> TArray< OutputType > FMediaIOAudioOutput::ConvertAndUpmixBuffer (TConstArrayView< float > InBuffer, int32 InNumInputChannels, int32 InNumOutputChannels) inline static
@Note: Audio::DownmixBuffer was not used here because it does not convert data in place, this forces us to create an additional buffer to hold the final int32 values. Instead we upmix and convert the values in a single pass.
Definition at line 37 of file MediaIOCoreAudioOutput.h.
References AlignDown(), FMediaIOAudioOutput::TSampleConverter< OutputType >::ConvertSample(), float, TArray< InElementType, InAllocatorType >::GetData(), TArray< InElementType, InAllocatorType >::Num(), TArray< InElementType, InAllocatorType >::SetNum(), TArray< InElementType, InAllocatorType >::SetNumZeroed(), TEXT, TRACE_CPUPROFILER_EVENT_SCOPE, and Yes.
Referenced by GetAllAudioSamples(), GetAudioSamples(), and GetAudioSamples().
GetAllAudioSamples()
template<typename OutputType> TArray< OutputType > FMediaIOAudioOutput::GetAllAudioSamples () const inline
Definition at line 104 of file MediaIOCoreAudioOutput.h.
References ConvertAndUpmixBuffer(), GetAllAudioSamples(), GetFloatBuffer(), MaxSampleLatency, NumInputChannels, NumOutputChannels, and TRACE_CPUPROFILER_EVENT_SCOPE.
Referenced by GetAllAudioSamples().
GetAudioBuffer()
int32 FMediaIOAudioOutput::GetAudioBuffer (int32 InNumSamplesToPop, float * OutBuffer) const private
GetAudioSamples() [1/2]
template<typename OutputType> TArray< OutputType > FMediaIOAudioOutput::GetAudioSamples () const inline
Get the audio sample that were accumulated.
Definition at line 86 of file MediaIOCoreAudioOutput.h.
References ConvertAndUpmixBuffer(), GetAudioSamples(), GetFloatBuffer(), NumInputChannels, NumOutputChannels, NumSamplesPerFrame, and TRACE_CPUPROFILER_EVENT_SCOPE.
Referenced by GetAudioSamples(), and GetAudioSamples().
GetAudioSamples() [2/2]
template<typename OutputType> TArray< OutputType > FMediaIOAudioOutput::GetAudioSamples (uint32 NumSamplesToGet) const inline
Definition at line 95 of file MediaIOCoreAudioOutput.h.
References ConvertAndUpmixBuffer(), GetAudioSamples(), GetFloatBuffer(), NumInputChannels, NumOutputChannels, and TRACE_CPUPROFILER_EVENT_SCOPE.
GetFloatBuffer()
Audio::FAlignedFloatBuffer FMediaIOAudioOutput::GetFloatBuffer (uint32 NumSamplesToGet) const private
Referenced by GetAllAudioSamples(), GetAudioSamples(), and GetAudioSamples().
UE_DEPRECATED()
FMediaIOAudioOutput::UE_DEPRECATED (5. 6, "This function is deprecated because it is not implemented. Use UMediaIOCoreSubsystem::OnBufferReceived() instead.") & inline
Definition at line 112 of file MediaIOCoreAudioOutput.h.
References BufferReceivedDelegate.
Field Documentation
BufferReceivedDelegate
FOnBufferReceived FMediaIOAudioOutput::BufferReceivedDelegate private
Callback called when a buffer is received.
(Not used, deprecated)
Definition at line 162 of file MediaIOCoreAudioOutput.h.
Referenced by UE_DEPRECATED().
MaxSampleLatency
uint32 FMediaIOAudioOutput::MaxSampleLatency
Maximum number of samples to accumulate before they are discarded.
Definition at line 131 of file MediaIOCoreAudioOutput.h.
Referenced by GetAllAudioSamples().
NumInputChannels
int32 FMediaIOAudioOutput::NumInputChannels
Number of audio channels on the engine side.
Definition at line 123 of file MediaIOCoreAudioOutput.h.
Referenced by GetAllAudioSamples(), GetAudioSamples(), and GetAudioSamples().
NumOutputChannels
int32 FMediaIOAudioOutput::NumOutputChannels
Number of audio channels to output.
Definition at line 126 of file MediaIOCoreAudioOutput.h.
Referenced by GetAllAudioSamples(), GetAudioSamples(), and GetAudioSamples().
NumSamplesPerFrame
int32 FMediaIOAudioOutput::NumSamplesPerFrame = 0
Definition at line 120 of file MediaIOCoreAudioOutput.h.
Referenced by GetAudioSamples().
OutputSampleRate
uint32 FMediaIOAudioOutput::OutputSampleRate
Definition at line 133 of file MediaIOCoreAudioOutput.h.
PatchOutput
Audio::FPatchOutputStrongPtr FMediaIOAudioOutput::PatchOutput private
The buffer accumulating audio samples.
Definition at line 159 of file MediaIOCoreAudioOutput.h.
TargetFrameRate
FFrameRate FMediaIOAudioOutput::TargetFrameRate
Definition at line 128 of file MediaIOCoreAudioOutput.h.
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Media/MediaIOFramework/Source/MediaIOCore/Public/MediaIOCoreAudioOutput.h