Unreal Engine 5.6 C++ API: FWorldTileLayer Class Reference
FWorldTileLayer Class Reference
World layer information for tile tagging.
#include "WorldCompositionUtility.h"
Public Member Functions
FWorldTileLayer ()
bool operator== (const FWorldTileLayer &OtherLayer) const
Data Fields
bool DistanceStreamingEnabled
FString Name
Human readable name for this layer.
int32 Reserved0
FIntPoint Reserved1
int32 StreamingDistance
Distance starting from where tiles belonging to this layer will be streamed in.
Friends
FArchive & operator<< (FArchive &Ar, FWorldTileLayer &D)
void operator<< (FStructuredArchive::FSlot Slot, FWorldTileLayer &D)
Detailed Description
World layer information for tile tagging.
Definition at line 26 of file WorldCompositionUtility.h.
Constructor & Destructor Documentation
FWorldTileLayer()
FWorldTileLayer::FWorldTileLayer () inline
Definition at line 29 of file WorldCompositionUtility.h.
References DistanceStreamingEnabled, ForceInit, Name, Reserved0, Reserved1, StreamingDistance, and TEXT.
Referenced by operator<<, operator<<, and operator==().
Member Function Documentation
operator==()
bool FWorldTileLayer::operator== (const FWorldTileLayer & OtherLayer) const inline
Definition at line 38 of file WorldCompositionUtility.h.
References FWorldTileLayer(), DistanceStreamingEnabled, Name, and StreamingDistance.
Friends And Related Symbol Documentation
operator<< [1/2]
FArchive & operator<< (FArchive & Ar, FWorldTileLayer & D) friend
References FWorldTileLayer(), and Ar.
operator<< [2/2]
void operator<< (FStructuredArchive::FSlot Slot, FWorldTileLayer & D) friend
References FWorldTileLayer().
Field Documentation
DistanceStreamingEnabled
bool FWorldTileLayer::DistanceStreamingEnabled
Definition at line 56 of file WorldCompositionUtility.h.
Referenced by FWorldTileLayer(), and operator==().
Name
FString FWorldTileLayer::Name
Human readable name for this layer.
Definition at line 51 of file WorldCompositionUtility.h.
Referenced by FWorldTileLayer(), and operator==().
Reserved0
int32 FWorldTileLayer::Reserved0
Definition at line 52 of file WorldCompositionUtility.h.
Referenced by FWorldTileLayer().
Reserved1
FIntPoint FWorldTileLayer::Reserved1
Definition at line 53 of file WorldCompositionUtility.h.
Referenced by FWorldTileLayer().
StreamingDistance
int32 FWorldTileLayer::StreamingDistance
Distance starting from where tiles belonging to this layer will be streamed in.
Definition at line 55 of file WorldCompositionUtility.h.
Referenced by FWorldTileLayer(), and operator==().
The documentation for this class was generated from the following file:
Runtime/CoreUObject/Public/Misc/WorldCompositionUtility.h