Unreal Engine 5.6 C++ API: FMovieSceneTrackEditor Class Reference
FMovieSceneTrackEditor Class Reference abstract
Base class for handling key and section drawing and manipulation of a UMovieSceneTrack class.
#include "MovieSceneTrackEditor.h"
Data Structures
struct FFindOrCreateHandleResult
struct FFindOrCreateRootTrackResult
struct FFindOrCreateTrackResult
Public Member Functions
FMovieSceneTrackEditor (TSharedRef< ISequencer > InSequencer)
Constructor.
virtual ~FMovieSceneTrackEditor ()
Destructor.
virtual UMovieSceneTrack * AddTrack (UMovieScene *FocusedMovieScene, const FGuid &ObjectHandle, TSubclassOf< class UMovieSceneTrack > TrackClass, FName UniqueTypeName) override
Add a new track to the sequence.
void AnimatablePropertyChanged (FOnKeyProperty OnKeyProperty)
virtual void BindCommands (TSharedRef< FUICommandList > SequencerCommandBindings) override
Allows the track editors to bind commands.
virtual void BuildAddTrackMenu (FMenuBuilder &MenuBuilder) override
Builds up the sequencer's "Add Track" menu.
virtual void BuildObjectBindingColumnWidgets (TFunctionRef< TSharedRef< SHorizontalBox >()> GetEditBox, const UE::Sequencer::TViewModelPtr< UE::Sequencer::FObjectBindingModel > &ObjectBinding, const UE::Sequencer::FCreateOutlinerViewParams &InParams, const FName &InColumnName) override
Build a column widget for the specified object binding on the outliner.
virtual void BuildObjectBindingTrackMenu (FMenuBuilder &MenuBuilder, const TArray< FGuid > &ObjectBindings, const UClass *ObjectClass) override
Builds up the object binding track menu for the outliner.
virtual TSharedPtr< SWidget > BuildOutlinerColumnWidget (const FBuildColumnWidgetParams &Params, const FName &ColumnName) override
Builds an outliner column widget for the outliner nodes which represent tracks which are edited by this editor.
virtual TSharedPtr< SWidget > BuildOutlinerEditColumnWidget (const FGuid &ObjectBinding, UMovieSceneTrack *Track, const FBuildEditWidgetParams &Params) override
Builds a widget for the edit column for outliner nodes which represent tracks which are edited by this editor.
virtual TSharedPtr< SWidget > BuildOutlinerEditWidget (const FGuid &ObjectBinding, UMovieSceneTrack *Track, const FBuildEditWidgetParams &Params) override
Builds a widget for the add column for outliner nodes which represent tracks which are edited by this editor.
virtual void BuildPinnedAddTrackMenu (FMenuBuilder &MenuBuilder) override
Builds up the sequencer's "Add Track" menu.
virtual void BuildTrackContextMenu (FMenuBuilder &MenuBuilder, UMovieSceneTrack *Track) override
Builds the context menu for the track.
virtual void BuildTrackSidebarMenu (FMenuBuilder &MenuBuilder, UMovieSceneTrack *Track) override
Builds the sidebar menu for the track.
FFindOrCreateHandleResult FindOrCreateHandleToObject (UObject *Object, bool bCreateHandleIfMissing=true, const FName &CreatedFolderName=NAME_None)
template<typename TrackClass>
FFindOrCreateRootTrackResult< TrackClass > FindOrCreateRootTrack ()
Find or add a track of the specified type in the focused movie scene.
FFindOrCreateTrackResult FindOrCreateTrackForObject (const FGuid &ObjectHandle, TSubclassOf< UMovieSceneTrack > TrackClass, FName PropertyName=NAME_None, bool bCreateTrackIfMissing=true)
virtual FText GetDisplayName () const override
The display name text to use in the UX.
UMovieSceneSequence * GetMovieSceneSequence () const
TSharedPtr< ISequencer > GetSequencer () const
FFrameNumber GetTimeForKey ()
virtual bool HandleAssetAdded (UObject *Asset, const FGuid &TargetObjectGuid) override
Called when an asset is dropped into Sequencer.
virtual TSharedRef< ISequencerSection > MakeSectionInterface (UMovieSceneSection &SectionObject, UMovieSceneTrack &Track, FGuid ObjectBinding) override
Called to generate a section layout for a particular section.
virtual bool OnAllowDrop (const FDragDropEvent &DragDropEvent, FSequencerDragDropParams &DragDropParams) override
Called when attempting to drop an asset directly onto a track.
virtual FReply OnDrop (const FDragDropEvent &DragDropEvent, const FSequencerDragDropParams &DragDropParams) override
Called when an asset is dropped directly onto a track.
virtual void OnInitialize () override
Called when the instance of this track editor is initialized.
virtual void OnRelease () override
Called when the instance of this track editor is released.
virtual bool SupportsSequence (UMovieSceneSequence *InSequence) const override
Returns whether a sequence is supported by this tool.
virtual bool SupportsType (TSubclassOf< class UMovieSceneTrack > TrackClass) const override=0
Returns whether a track class is supported by this tool.
virtual void Tick (float DeltaTime) override
Ticks this tool.
void UpdatePlaybackRange ()
Public Member Functions inherited from TSharedFromThis< FMovieSceneTrackEditor >
TSharedRef< FMovieSceneTrackEditor, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FMovieSceneTrackEditor, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Public Member Functions inherited from ISequencerTrackEditor
virtual ~ISequencerTrackEditor ()
Virtual destructor.
virtual void BuildObjectBindingContextMenu (FMenuBuilder &MenuBuilder, const TArray< FGuid > &ObjectBindings, const UClass *ObjectClass)
Builds up the object binding cpmtext menu for the outliner.
virtual void BuildObjectBindingEditButtons (TSharedPtr< SHorizontalBox > EditBox, const FGuid &ObjectBinding, const UClass *ObjectClass)
Deprecated in principle, not practice (due to difficulty deprecating public virtual functions).
virtual bool CanAddTransformKeysForSelectedObjects () const
Whether or not we can add a transform key for a selected object.
virtual void ExtendObjectBindingTrackMenu (TSharedRef< FExtender > Extender, const TArray< FGuid > &ObjectBindings, const UClass *ObjectClass)
Extend the object binding track menu for the specified binding and class.
virtual bool GetDefaultExpansionState (UMovieSceneTrack *InTrack) const
virtual const FSlateBrush * GetIconBrush () const
Gets an icon brush for this track editor.
virtual bool HasTransformKeyBindings () const
virtual bool HasTransformKeyOverridePriority () const
If true this track has priority when setting transform keys and should be the only one to set them.
virtual bool IsResizable (UMovieSceneTrack *InTrack) const
virtual void ObjectImplicitlyAdded (UObject *InObject)
Handle this object being implicitly added.
virtual void ObjectImplicitlyRemoved (UObject *InObject)
Handle this object being implicitly removed.
virtual void OnAddTransformKeysForSelectedObjects (EMovieSceneTransformChannel Channel)
Adds transform tracks and keys to the selected objects in the level.
virtual void OnPostSaveWorld (UWorld *World)
Called after the sequencer has re-evaluated all objects after saving the level.
virtual void OnPreSaveWorld (UWorld *World)
Called before the sequencer restores pre-animated state on all objects before saving the level.
virtual void ProcessKeyOperation (FFrameNumber InKeyTime, const UE::Sequencer::FKeyOperation &Operation, ISequencer &InSequencer, TArray< UE::Sequencer::FAddKeyResult > *OutResults=nullptr)
Add keys for the following sections based on an external value if possible.
virtual void Resize (float NewSize, UMovieSceneTrack *InTrack)
Resize this track.
Static Public Member Functions
static void BeginKeying (FFrameNumber InFrameNumber)
Initiate keying when there is more than one object to key (ie.
static void EndKeying ()
Protected Member Functions
UMovieScene * GetFocusedMovieScene () const
Gets the currently focused movie scene, if any.
Protected Member Functions inherited from TSharedFromThis< FMovieSceneTrackEditor >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Private Attributes
TWeakPtr< ISequencer > WeakSequencerPtr
The sequencer bound to this handler.
Static Private Attributes
static bool bKeying
Indicates whether we're currently in a keying operation where multiple keys may be created (ie.
static TOptional< FFrameNumber > NextKeyTime
The key time to use during a multi key operation.
Additional Inherited Members
Static Protected Member Functions inherited from TSharedFromThis< FMovieSceneTrackEditor >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
Base class for handling key and section drawing and manipulation of a UMovieSceneTrack class.
Todo
Sequencer Interface needs cleanup
Definition at line 81 of file MovieSceneTrackEditor.h.
Constructor & Destructor Documentation
FMovieSceneTrackEditor()
FMovieSceneTrackEditor::FMovieSceneTrackEditor (TSharedRef< ISequencer > InSequencer)
Constructor.
Referenced by FKeyframeTrackEditor< TrackType >::FKeyframeTrackEditor().
~FMovieSceneTrackEditor()
virtual FMovieSceneTrackEditor::~FMovieSceneTrackEditor () virtual
Destructor.
Member Function Documentation
AddTrack()
virtual UMovieSceneTrack * FMovieSceneTrackEditor::AddTrack (UMovieScene * FocusedMovieScene, const FGuid & ObjectHandle, TSubclassOf< class UMovieSceneTrack > TrackClass, FName UniqueTypeName) override virtual
Add a new track to the sequence.
Implements ISequencerTrackEditor.
Reimplemented in FBindingLifetimeTrackEditor, FMediaTrackEditor, FPropertyTrackEditor< TrackType >, FPropertyTrackEditor< UMovieSceneBoolTrack >, and FSpawnTrackEditor.
AnimatablePropertyChanged()
void FMovieSceneTrackEditor::AnimatablePropertyChanged (FOnKeyProperty OnKeyProperty)
Referenced by FPropertyTrackEditor< TrackType >::OnAnimatedPropertyChanged().
BeginKeying()
void FMovieSceneTrackEditor::BeginKeying (FFrameNumber InFrameNumber) static
Initiate keying when there is more than one object to key (ie.
drag and drop assets). This will allow for different behaviors, ie. keying all at the current time or keying one after the other.
BindCommands()
virtual void FMovieSceneTrackEditor::BindCommands (TSharedRef< FUICommandList > SequencerCommandBindings) override virtual
Allows the track editors to bind commands.
Parameters
SequencerCommandBindings The command bindings to map to.
Implements ISequencerTrackEditor.
BuildAddTrackMenu()
virtual void FMovieSceneTrackEditor::BuildAddTrackMenu (FMenuBuilder & MenuBuilder) override virtual
Builds up the sequencer's "Add Track" menu.
Parameters
MenuBuilder The menu builder to change.
Implements ISequencerTrackEditor.
Reimplemented in FAudioTrackEditor, FMediaTrackEditor, and FSubTrackEditor.
BuildObjectBindingColumnWidgets()
virtual void FMovieSceneTrackEditor::BuildObjectBindingColumnWidgets (TFunctionRef< TSharedRef< SHorizontalBox >()> GetEditBox, const UE::Sequencer::TViewModelPtr< UE::Sequencer::FObjectBindingModel > & ObjectBinding, const UE::Sequencer::FCreateOutlinerViewParams & InParams, const FName & InColumnName) override virtual
Build a column widget for the specified object binding on the outliner.
Parameters
GetEditBox A function to retrieve the edit box to populate
ObjectBinding The object binding this is for.
Implements ISequencerTrackEditor.
BuildObjectBindingTrackMenu()
virtual void FMovieSceneTrackEditor::BuildObjectBindingTrackMenu (FMenuBuilder & MenuBuilder, const TArray< FGuid > & ObjectBindings, const UClass * ObjectClass) override virtual
Builds up the object binding track menu for the outliner.
Parameters
MenuBuilder The menu builder to change.
ObjectBinding The object binding this is for.
ObjectClass The class of the object this is for.
Implements ISequencerTrackEditor.
Reimplemented in FAudioTrackEditor, FBindingLifetimeTrackEditor, FChaosCacheTrackEditor, FSpawnTrackEditor, and UE::Sequencer::FCommonAnimationTrackEditor.
References ObjectBindings.
BuildOutlinerColumnWidget()
virtual TSharedPtr< SWidget > FMovieSceneTrackEditor::BuildOutlinerColumnWidget (const FBuildColumnWidgetParams & Params, const FName & ColumnName) override virtual
Builds an outliner column widget for the outliner nodes which represent tracks which are edited by this editor.
Parameters
Params Parameter struct containing data relevant to the edit widget
ColumnName The name of the column. See FCommonOutlinerNames
Returns
The the widget to display in the outliner, or an empty shared ptr if not widget is to be displayed.
Implements ISequencerTrackEditor.
Reimplemented in FAudioTrackEditor, and FCinematicShotTrackEditor.
References Params.
BuildOutlinerEditColumnWidget()
virtual TSharedPtr< SWidget > FMovieSceneTrackEditor::BuildOutlinerEditColumnWidget (const FGuid & ObjectBinding, UMovieSceneTrack * Track, const FBuildEditWidgetParams & Params) override virtual
Builds a widget for the edit column for outliner nodes which represent tracks which are edited by this editor.
Parameters
ObjectBinding The object binding associated with the track being edited by this editor.
Track The track being edited by this editor.
Params Parameter struct containing data relevant to the edit widget
Returns
The the widget to display in the outliner, or an empty shared ptr if not widget is to be displayed.
Implements ISequencerTrackEditor.
References Params.
BuildOutlinerEditWidget()
virtual TSharedPtr< SWidget > FMovieSceneTrackEditor::BuildOutlinerEditWidget (const FGuid & ObjectBinding, UMovieSceneTrack * Track, const FBuildEditWidgetParams & Params) override virtual
Builds a widget for the add column for outliner nodes which represent tracks which are edited by this editor.
Parameters
ObjectBinding The object binding associated with the track being edited by this editor.
Track The track being edited by this editor.
Params Parameter struct containing data relevant to the edit widget
Returns
The the widget to display in the outliner, or an empty shared ptr if not widget is to be displayed.
Implements ISequencerTrackEditor.
Reimplemented in FBindingLifetimeTrackEditor, FChaosCacheTrackEditor, FCustomPrimitiveDataTrackEditor, FMaterialTrackEditor, FMediaTrackEditor, FSpawnTrackEditor, FSubTrackEditor, and UE::Sequencer::FCommonAnimationTrackEditor.
References Params.
BuildPinnedAddTrackMenu()
virtual void FMovieSceneTrackEditor::BuildPinnedAddTrackMenu (FMenuBuilder & MenuBuilder) override virtual
Builds up the sequencer's "Add Track" menu.
for menu items pinned to the top
Parameters
MenuBuilder The menu builder to change.
Implements ISequencerTrackEditor.
Reimplemented in FTimeWarpTrackEditor.
BuildTrackContextMenu()
virtual void FMovieSceneTrackEditor::BuildTrackContextMenu (FMenuBuilder & MenuBuilder, UMovieSceneTrack * Track) override virtual
Builds the context menu for the track.
Parameters
MenuBuilder The menu builder to use to build the track menu.
Implements ISequencerTrackEditor.
Reimplemented in FCinematicShotTrackEditor, FComponentMaterialTrackEditor, FKeyframeTrackEditor< TrackType >, FKeyframeTrackEditor< UMovieSceneBoolTrack >, FKeyframeTrackEditor< UMovieSceneSubTrack >, and FKeyframeTrackEditor< UMovieSceneTimeWarpTrack >.
BuildTrackSidebarMenu()
virtual void FMovieSceneTrackEditor::BuildTrackSidebarMenu (FMenuBuilder & MenuBuilder, UMovieSceneTrack * Track) override virtual
Builds the sidebar menu for the track.
Parameters
MenuBuilder The menu builder to use to build the track menu.
Implements ISequencerTrackEditor.
EndKeying()
void FMovieSceneTrackEditor::EndKeying () static
FindOrCreateHandleToObject()
FFindOrCreateHandleResult FMovieSceneTrackEditor::FindOrCreateHandleToObject (UObject * Object, bool bCreateHandleIfMissing = true, const FName & CreatedFolderName = NAME_None)
References Object.
Referenced by FKeyframeTrackEditor< TrackType >::AddKeysToObjects().
FindOrCreateRootTrack()
template<typename TrackClass> FFindOrCreateRootTrackResult< TrackClass > FMovieSceneTrackEditor::FindOrCreateRootTrack () inline
Find or add a track of the specified type in the focused movie scene.
Parameters
TrackClass The class of the track to find or add.
Returns
The track results.
Definition at line 149 of file MovieSceneTrackEditor.h.
References GetSequencer().
FindOrCreateTrackForObject()
FFindOrCreateTrackResult FMovieSceneTrackEditor::FindOrCreateTrackForObject (const FGuid & ObjectHandle, TSubclassOf< UMovieSceneTrack > TrackClass, FName PropertyName = NAME_None, bool bCreateTrackIfMissing = true)
References PropertyName.
Referenced by FKeyframeTrackEditor< TrackType >::AddKeysToHandle().
GetDisplayName()
virtual FText FMovieSceneTrackEditor::GetDisplayName () const override virtual
The display name text to use in the UX.
Currently only used for sorting.
Implements ISequencerTrackEditor.
Reimplemented in FAudioTrackEditor, FBindingLifetimeTrackEditor, FBoolPropertyTrackEditor, FChaosCacheTrackEditor, FCinematicShotTrackEditor, FCustomPrimitiveDataTrackEditor, FKeyframeTrackEditor< TrackType >, FKeyframeTrackEditor< UMovieSceneBoolTrack >, FKeyframeTrackEditor< UMovieSceneSubTrack >, FKeyframeTrackEditor< UMovieSceneTimeWarpTrack >, FMaterialTrackEditor, FMediaTrackEditor, FPropertyTrackEditor< TrackType >, FPropertyTrackEditor< UMovieSceneBoolTrack >, FSubTrackEditor, FTimeWarpTrackEditor, and UE::Sequencer::FCommonAnimationTrackEditor.
GetFocusedMovieScene()
UMovieScene * FMovieSceneTrackEditor::GetFocusedMovieScene () const protected
Gets the currently focused movie scene, if any.
Returns
Focused movie scene, or nullptr if no movie scene is focused.
GetMovieSceneSequence()
UMovieSceneSequence * FMovieSceneTrackEditor::GetMovieSceneSequence () const
Returns
The current movie scene
GetSequencer()
TSharedPtr< ISequencer > FMovieSceneTrackEditor::GetSequencer () const
Returns
The sequencer bound to this handler
Referenced by FPropertyTrackEditor< TrackType >::~FPropertyTrackEditor(), FKeyframeTrackEditor< TrackType >::AddKeysToHandle(), FKeyframeTrackEditor< TrackType >::AddKeysToObjects(), FKeyframeTrackEditor< TrackType >::AddKeysToSection(), FPropertyTrackEditor< TrackType >::AddWatchedProperty(), FKeyframeTrackEditor< TrackType >::ClearDefaults(), and FindOrCreateRootTrack().
GetTimeForKey()
FFrameNumber FMovieSceneTrackEditor::GetTimeForKey ()
Returns
The current local time at which we should add a key
HandleAssetAdded()
virtual bool FMovieSceneTrackEditor::HandleAssetAdded (UObject * Asset, const FGuid & TargetObjectGuid) override virtual
Called when an asset is dropped into Sequencer.
Can potentially consume the asset so it doesn't get added as a spawnable.
Parameters
Asset The asset that is dropped in.
TargetObjectGuid The object guid this asset is dropped onto, if applicable.
Returns
true if we want to consume this asset, false otherwise.
Implements ISequencerTrackEditor.
Reimplemented in FAudioTrackEditor, FBindingLifetimeTrackEditor, FMediaTrackEditor, FSpawnTrackEditor, FSubTrackEditor, and UE::Sequencer::FCommonAnimationTrackEditor.
References Asset.
MakeSectionInterface()
virtual TSharedRef< ISequencerSection > FMovieSceneTrackEditor::MakeSectionInterface (UMovieSceneSection & SectionObject, UMovieSceneTrack & Track, FGuid ObjectBinding) override virtual
Called to generate a section layout for a particular section.
Parameters
SectionObject The section to make UI for.
Track The track that owns the section.
ObjectBinding the object binding for the track that owns the section, if there is one.
Implements ISequencerTrackEditor.
Reimplemented in FAudioTrackEditor, FBindingLifetimeTrackEditor, FBoolPropertyTrackEditor, FChaosCacheTrackEditor, FCinematicShotTrackEditor, FCustomPrimitiveDataTrackEditor, FMaterialTrackEditor, FMediaTrackEditor, FSubTrackEditor, FTimeWarpTrackEditor, and UE::Sequencer::FCommonAnimationTrackEditor.
OnAllowDrop()
virtual bool FMovieSceneTrackEditor::OnAllowDrop (const FDragDropEvent & DragDropEvent, FSequencerDragDropParams & DragDropParams) override virtual
Called when attempting to drop an asset directly onto a track.
Parameters
DragDropEvent The drag drop event.
DragDropParams The drag drop parameters.
Returns
Whether the drop event can be handled.
Implements ISequencerTrackEditor.
Reimplemented in FAudioTrackEditor, FSubTrackEditor, and UE::Sequencer::FCommonAnimationTrackEditor.
OnDrop()
virtual FReply FMovieSceneTrackEditor::OnDrop (const FDragDropEvent & DragDropEvent, const FSequencerDragDropParams & DragDropParams) override virtual
Called when an asset is dropped directly onto a track.
Parameters
DragDropEvent The drag drop event.
DragDropParams The drag drop parameters.
Returns
Whether the drop event was handled.
Implements ISequencerTrackEditor.
Reimplemented in FAudioTrackEditor, FSubTrackEditor, and UE::Sequencer::FCommonAnimationTrackEditor.
OnInitialize()
virtual void FMovieSceneTrackEditor::OnInitialize () override virtual
Called when the instance of this track editor is initialized.
Implements ISequencerTrackEditor.
Reimplemented in FAudioTrackEditor, FSubTrackEditor, and UE::Sequencer::FCommonAnimationTrackEditor.
OnRelease()
virtual void FMovieSceneTrackEditor::OnRelease () override virtual
Called when the instance of this track editor is released.
Implements ISequencerTrackEditor.
Reimplemented in FAudioTrackEditor, FMediaTrackEditor, FSubTrackEditor, and UE::Sequencer::FCommonAnimationTrackEditor.
SupportsSequence()
virtual bool FMovieSceneTrackEditor::SupportsSequence (UMovieSceneSequence * InSequence) const inline override virtual
Returns whether a sequence is supported by this tool.
Parameters
InSequence The sequence that could be supported.
Returns
true if the type is supported.
Implements ISequencerTrackEditor.
Reimplemented in FAudioTrackEditor, FBindingLifetimeTrackEditor, FChaosCacheTrackEditor, FCinematicShotTrackEditor, FMediaTrackEditor, FPropertyTrackEditor< TrackType >, FPropertyTrackEditor< UMovieSceneBoolTrack >, FSpawnTrackEditor, FSubTrackEditor, and FTimeWarpTrackEditor.
Definition at line 198 of file MovieSceneTrackEditor.h.
SupportsType()
virtual bool FMovieSceneTrackEditor::SupportsType (TSubclassOf< class UMovieSceneTrack > TrackClass) const override pure virtual
Returns whether a track class is supported by this tool.
Parameters
TrackClass The track class that could be supported.
Returns
true if the type is supported.
Implements ISequencerTrackEditor.
Implemented in FAudioTrackEditor, FBindingLifetimeTrackEditor, FChaosCacheTrackEditor, FComponentMaterialTrackEditor, FCustomPrimitiveDataTrackEditor, FKeyframeTrackEditor< TrackType >, FKeyframeTrackEditor< UMovieSceneBoolTrack >, FKeyframeTrackEditor< UMovieSceneSubTrack >, FKeyframeTrackEditor< UMovieSceneTimeWarpTrack >, FMediaTrackEditor, FPropertyTrackEditor< TrackType >, FPropertyTrackEditor< UMovieSceneBoolTrack >, FSpawnTrackEditor, and FSubTrackEditor.
Tick()
virtual void FMovieSceneTrackEditor::Tick (float DeltaTime) override virtual
Ticks this tool.
Parameters
DeltaTime The time since the last tick.
Implements ISequencerTrackEditor.
Reimplemented in FCinematicShotTrackEditor, and FMediaTrackEditor.
References DeltaTime.
UpdatePlaybackRange()
void FMovieSceneTrackEditor::UpdatePlaybackRange ()
Field Documentation
bKeying
bool FMovieSceneTrackEditor::bKeying static private
Indicates whether we're currently in a keying operation where multiple keys may be created (ie.
drag and drop)
Definition at line 219 of file MovieSceneTrackEditor.h.
NextKeyTime
TOptional<FFrameNumber> FMovieSceneTrackEditor::NextKeyTime static private
The key time to use during a multi key operation.
Only used if bKeying is true
Definition at line 216 of file MovieSceneTrackEditor.h.
WeakSequencerPtr
TWeakPtr<ISequencer> FMovieSceneTrackEditor::WeakSequencerPtr private
The sequencer bound to this handler.
Used to access movie scene and time info during auto-key
Definition at line 213 of file MovieSceneTrackEditor.h.
The documentation for this class was generated from the following file:
Editor/Sequencer/Public/MovieSceneTrackEditor.h