Unreal Engine 5.6 C++ API: IStringTableEngineBridge Class Reference
IStringTableEngineBridge Class Reference abstract
Interface to allow Core code to access String Table assets from the Engine.
#include "StringTableCore.h"
Data Structures
struct FScopedDeferFindOrLoad
Scope object used to temporarily defer String Table find/load (eg, during module load).
Public Types
typedef TFunction< void(FName, FName)> FLoadStringTableAssetCallback
Callback used when loading string table assets.
Static Public Member Functions
static bool CanFindOrLoadStringTableAsset ()
Check to see whether it is currently safe to attempt to find or load a string table asset.
static void CollectStringTableAssetReferences (FName &InOutTableId, FStructuredArchive::FSlot Slot)
Collect a string table asset reference.
static void FullyLoadStringTableAsset (FName &InOutTableId)
Fully load a string table asset by its name, synchronously.
static bool IsStringTableAssetBeingReplaced (const UStringTable *InStringTableAsset)
Is this string table asset being replaced due to a hot-reload?
static bool IsStringTableFromAsset (const FName InTableId)
Is this string table from an asset?
static int32 LoadStringTableAsset (const FName InTableId, FLoadStringTableAssetCallback InLoadedCallback=FLoadStringTableAssetCallback())
Load a string table asset by its name, potentially doing so asynchronously.
static void RedirectStringTableAsset (FName &InOutTableId)
Redirect string table asset by its name.
Protected Member Functions
virtual ~IStringTableEngineBridge ()=default
virtual bool CanFindOrLoadStringTableAssetImpl ()=0
virtual void CollectStringTableAssetReferencesImpl (FName &InOutTableId, FStructuredArchive::FSlot Slot)=0
virtual void FullyLoadStringTableAssetImpl (FName &InOutTableId)=0
virtual bool IsStringTableAssetBeingReplacedImpl (const UStringTable *InStringTableAsset)=0
virtual bool IsStringTableFromAssetImpl (const FName InTableId)=0
virtual int32 LoadStringTableAssetImpl (const FName InTableId, FLoadStringTableAssetCallback InLoadedCallback)=0
virtual void RedirectStringTableAssetImpl (FName &InOutTableId)=0
Static Protected Attributes
static std::atomic< int8 > DeferFindOrLoad
Whether String Table find/load is currently deferred (eg, during module load)
static IStringTableEngineBridge * InstancePtr
Singleton instance, populated by the derived type.
Detailed Description
Interface to allow Core code to access String Table assets from the Engine.
Definition at line 197 of file StringTableCore.h.
Member Typedef Documentation
FLoadStringTableAssetCallback
typedef TFunction<void(FName, FName)> IStringTableEngineBridge::FLoadStringTableAssetCallback
Callback used when loading string table assets.
Parameters
The name of the table we were asked to load.
The name of the table we actually loaded (may be different if redirected; will be empty if the load failed).
Definition at line 223 of file StringTableCore.h.
Constructor & Destructor Documentation
~IStringTableEngineBridge()
virtual IStringTableEngineBridge::~IStringTableEngineBridge () protected virtual default
Member Function Documentation
CanFindOrLoadStringTableAsset()
bool IStringTableEngineBridge::CanFindOrLoadStringTableAsset () inline static
Check to see whether it is currently safe to attempt to find or load a string table asset.
Returns
True if it is safe to attempt to find or load a string table asset, false otherwise.
Definition at line 229 of file StringTableCore.h.
References DeferFindOrLoad, InstancePtr, and FInternationalization::IsAvailable().
Referenced by FullyLoadStringTableAsset(), LoadStringTableAsset(), and RedirectStringTableAsset().
CanFindOrLoadStringTableAssetImpl()
virtual bool IStringTableEngineBridge::CanFindOrLoadStringTableAssetImpl () protected pure virtual
CollectStringTableAssetReferences()
void IStringTableEngineBridge::CollectStringTableAssetReferences (FName & InOutTableId, FStructuredArchive::FSlot Slot) inline static
Collect a string table asset reference.
Definition at line 284 of file StringTableCore.h.
References InstancePtr.
CollectStringTableAssetReferencesImpl()
virtual void IStringTableEngineBridge::CollectStringTableAssetReferencesImpl (FName & InOutTableId, FStructuredArchive::FSlot Slot) protected pure virtual
FullyLoadStringTableAsset()
void IStringTableEngineBridge::FullyLoadStringTableAsset (FName & InOutTableId) inline static
Fully load a string table asset by its name, synchronously.
Note
This should be used sparingly in places where it is definitely safe to perform a blocking load.
Definition at line 262 of file StringTableCore.h.
References CanFindOrLoadStringTableAsset(), check, and InstancePtr.
FullyLoadStringTableAssetImpl()
virtual void IStringTableEngineBridge::FullyLoadStringTableAssetImpl (FName & InOutTableId) protected pure virtual
IsStringTableAssetBeingReplaced()
bool IStringTableEngineBridge::IsStringTableAssetBeingReplaced (const UStringTable * InStringTableAsset) inline static
Is this string table asset being replaced due to a hot-reload?
Definition at line 299 of file StringTableCore.h.
References InstancePtr.
IsStringTableAssetBeingReplacedImpl()
virtual bool IStringTableEngineBridge::IsStringTableAssetBeingReplacedImpl (const UStringTable * InStringTableAsset) protected pure virtual
IsStringTableFromAsset()
bool IStringTableEngineBridge::IsStringTableFromAsset (const FName InTableId) inline static
Is this string table from an asset?
Definition at line 293 of file StringTableCore.h.
References InstancePtr.
IsStringTableFromAssetImpl()
virtual bool IStringTableEngineBridge::IsStringTableFromAssetImpl (const FName InTableId) protected pure virtual
LoadStringTableAsset()
int32 IStringTableEngineBridge::LoadStringTableAsset (const FName InTableId, FLoadStringTableAssetCallback InLoadedCallback = FLoadStringTableAssetCallback()) inline static
Load a string table asset by its name, potentially doing so asynchronously.
Note
If the string table is already loaded, or loading is perform synchronously, then the callback will be called before this function returns.
Returns
The async loading ID of the asset, or INDEX_NONE if no async loading was performed.
Definition at line 241 of file StringTableCore.h.
References CanFindOrLoadStringTableAsset(), check, INDEX_NONE, and InstancePtr.
LoadStringTableAssetImpl()
virtual int32 IStringTableEngineBridge::LoadStringTableAssetImpl (const FName InTableId, FLoadStringTableAssetCallback InLoadedCallback) protected pure virtual
RedirectStringTableAsset()
void IStringTableEngineBridge::RedirectStringTableAsset (FName & InOutTableId) inline static
Redirect string table asset by its name.
Definition at line 273 of file StringTableCore.h.
References CanFindOrLoadStringTableAsset(), check, and InstancePtr.
RedirectStringTableAssetImpl()
virtual void IStringTableEngineBridge::RedirectStringTableAssetImpl (FName & InOutTableId) protected pure virtual
Field Documentation
DeferFindOrLoad
std::atomic<int8> IStringTableEngineBridge::DeferFindOrLoad static protected
Whether String Table find/load is currently deferred (eg, during module load)
Definition at line 319 of file StringTableCore.h.
Referenced by IStringTableEngineBridge::FScopedDeferFindOrLoad::FScopedDeferFindOrLoad(), IStringTableEngineBridge::FScopedDeferFindOrLoad::~FScopedDeferFindOrLoad(), and CanFindOrLoadStringTableAsset().
InstancePtr
IStringTableEngineBridge* IStringTableEngineBridge::InstancePtr static protected
Singleton instance, populated by the derived type.
Definition at line 316 of file StringTableCore.h.
Referenced by CanFindOrLoadStringTableAsset(), CollectStringTableAssetReferences(), FullyLoadStringTableAsset(), IsStringTableAssetBeingReplaced(), IsStringTableFromAsset(), LoadStringTableAsset(), and RedirectStringTableAsset().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Internationalization/StringTableCore.h