Unreal Engine 5.6 C++ API: Metasound::TAutoConverterNode< FromDataType, ToDataType >::FCoverterOperatorFactory Class Reference
Metasound::TAutoConverterNode< FromDataType, ToDataType >::FCoverterOperatorFactory Class Reference
FConverterOperatorFactory creates an operator which converts from "FromDataType" to "ToDataType".
Public Member Functions
FCoverterOperatorFactory ()=default
virtual TUniquePtr< IOperator > CreateOperator (const FBuildOperatorParams &InParams, FBuildResults &OutResults) override
Public Member Functions inherited from Metasound::IOperatorFactory
virtual ~IOperatorFactory ()=default
Detailed Description
template<typename FromDataType, typename ToDataType>
class Metasound::TAutoConverterNode< FromDataType, ToDataType >::FCoverterOperatorFactory
FConverterOperatorFactory creates an operator which converts from "FromDataType" to "ToDataType".
Definition at line 198 of file MetasoundAutoConverterNode.h.
Constructor & Destructor Documentation
FCoverterOperatorFactory()
template<typename FromDataType, typename ToDataType> Metasound::TAutoConverterNode< FromDataType, ToDataType >::FCoverterOperatorFactory::FCoverterOperatorFactory () default
Member Function Documentation
CreateOperator()
template<typename FromDataType, typename ToDataType> virtual TUniquePtr< IOperator > Metasound::TAutoConverterNode< FromDataType, ToDataType >::FCoverterOperatorFactory::CreateOperator (const FBuildOperatorParams & InParams, FBuildResults & OutResults) inline override virtual
Implements Metasound::IOperatorFactory.
Definition at line 203 of file MetasoundAutoConverterNode.h.
References Metasound::TDataFactory< DataType, TDataWriteReference< DataType > >::CreateExplicitArgs(), Metasound::TAutoConverterNode< FromDataType, ToDataType >::GetInputName(), Metasound::FInputVertexInterfaceData::GetOrCreateDefaultDataReadReference(), Metasound::FBuildOperatorParams::InputData, MakeUnique(), MoveTemp(), and Metasound::FBuildOperatorParams::OperatorSettings.
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/Metasound/Source/MetasoundFrontend/Public/MetasoundAutoConverterNode.h