Unreal Engine 5.6 C++ API: Metasound::FAddressRouter Class Reference
Metasound::FAddressRouter Class Reference
#include "MetasoundRouter.h"
Data Structures
class FTransmissionAddressKey
Public Member Functions
FAddressRouter ()=default
METASOUNDFRONTEND_API FAddressRouter (const FAddressRouter &Other)
METASOUNDFRONTEND_API TSharedPtr< IDataChannel, ESPMode::ThreadSafe > FindDataChannel (const FTransmissionAddress &InAddress)
METASOUNDFRONTEND_API TSharedPtr< IDataChannel, ESPMode::ThreadSafe > GetDataChannel (const FTransmissionAddress &InAddress, const FOperatorSettings &InOperatorSettings)
METASOUNDFRONTEND_API TUniquePtr< IReceiver > RegisterNewReceiver (const FTransmissionAddress &InAddress, const FReceiverInitParams &InitParams)
template<typename TDataType>
TReceiverPtr< TDataType > RegisterNewReceiver (const FTransmissionAddress &InAddress, const FReceiverInitParams &InitParams)
METASOUNDFRONTEND_API TUniquePtr< ISender > RegisterNewSender (const FTransmissionAddress &InAddress, const FSenderInitParams &InitParams)
template<typename TDataType>
TSenderPtr< TDataType > RegisterNewSender (const FTransmissionAddress &InAddress, const FSenderInitParams &InitParams)
UE_DEPRECATED (5.1, "Pushing literals from the Metasound::FAddressRouter will no longer be supported in future released.") METASOUNDFRONTEND_API bool PushLiteral(const FName &InDataTypeName
METASOUNDFRONTEND_API bool UnregisterDataChannel (const FTransmissionAddress &InAddress)
METASOUNDFRONTEND_API bool UnregisterDataChannelIfUnconnected (const FTransmissionAddress &InAddress)
Data Fields
const FName & InChannelName
const FName const FLiteral & InParam
Private Attributes
TMap< FTransmissionAddressKey, TSharedRef< IDataChannel, ESPMode::ThreadSafe > > DataChannelMap
FCriticalSection DataChannelMapMutationLock
Detailed Description
Definition at line 1007 of file MetasoundRouter.h.
Constructor & Destructor Documentation
FAddressRouter() [1/2]
METASOUNDFRONTEND_API Metasound::FAddressRouter::FAddressRouter (const FAddressRouter & Other)
References FAddressRouter(), Other, and UE_API.
Referenced by FAddressRouter(), and FAddressRouter().
FAddressRouter() [2/2]
Metasound::FAddressRouter::FAddressRouter () default
References FAddressRouter().
Member Function Documentation
FindDataChannel()
METASOUNDFRONTEND_API TSharedPtr< IDataChannel, ESPMode::ThreadSafe > Metasound::FAddressRouter::FindDataChannel (const FTransmissionAddress & InAddress)
References UE_API.
GetDataChannel()
METASOUNDFRONTEND_API TSharedPtr< IDataChannel, ESPMode::ThreadSafe > Metasound::FAddressRouter::GetDataChannel (const FTransmissionAddress & InAddress, const FOperatorSettings & InOperatorSettings)
References UE_API.
RegisterNewReceiver() [1/2]
METASOUNDFRONTEND_API TUniquePtr< IReceiver > Metasound::FAddressRouter::RegisterNewReceiver (const FTransmissionAddress & InAddress, const FReceiverInitParams & InitParams)
References UE_API.
Referenced by RegisterNewReceiver().
RegisterNewReceiver() [2/2]
template<typename TDataType> TReceiverPtr< TDataType > Metasound::FAddressRouter::RegisterNewReceiver (const FTransmissionAddress & InAddress, const FReceiverInitParams & InitParams) inline
Definition at line 1019 of file MetasoundRouter.h.
References Metasound::Downcast(), TUniquePtr< T, Deleter >::IsValid(), MoveTemp(), and RegisterNewReceiver().
RegisterNewSender() [1/2]
METASOUNDFRONTEND_API TUniquePtr< ISender > Metasound::FAddressRouter::RegisterNewSender (const FTransmissionAddress & InAddress, const FSenderInitParams & InitParams)
References UE_API.
Referenced by RegisterNewSender().
RegisterNewSender() [2/2]
template<typename TDataType> TSenderPtr< TDataType > Metasound::FAddressRouter::RegisterNewSender (const FTransmissionAddress & InAddress, const FSenderInitParams & InitParams) inline
Definition at line 1033 of file MetasoundRouter.h.
References Metasound::Downcast(), TUniquePtr< T, Deleter >::IsValid(), MoveTemp(), and RegisterNewSender().
UE_DEPRECATED()
Metasound::FAddressRouter::UE_DEPRECATED (5. 1, "Pushing literals from the Metasound::FAddressRouter will no longer be supported in future released.") const &
UnregisterDataChannel()
METASOUNDFRONTEND_API bool Metasound::FAddressRouter::UnregisterDataChannel (const FTransmissionAddress & InAddress)
References UE_API, and UnregisterDataChannel().
Referenced by UnregisterDataChannel().
UnregisterDataChannelIfUnconnected()
METASOUNDFRONTEND_API bool Metasound::FAddressRouter::UnregisterDataChannelIfUnconnected (const FTransmissionAddress & InAddress)
References UE_API, and UnregisterDataChannelIfUnconnected().
Referenced by UnregisterDataChannelIfUnconnected().
Field Documentation
DataChannelMap
TMap<FTransmissionAddressKey, TSharedRef<IDataChannel, ESPMode::ThreadSafe> > Metasound::FAddressRouter::DataChannelMap private
Definition at line 1081 of file MetasoundRouter.h.
DataChannelMapMutationLock
FCriticalSection Metasound::FAddressRouter::DataChannelMapMutationLock private
Definition at line 1082 of file MetasoundRouter.h.
InChannelName
const FName& Metasound::FAddressRouter::InChannelName
Definition at line 1047 of file MetasoundRouter.h.
InParam
const FName const FLiteral& Metasound::FAddressRouter::InParam
Definition at line 1047 of file MetasoundRouter.h.
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/Metasound/Source/MetasoundFrontend/Public/MetasoundRouter.h