Unreal Engine 5.6 C++ API: UE::Insights::FTreeNodeGroupingByPathBreakdown Class Reference
UE::Insights::FTreeNodeGroupingByPathBreakdown Class Reference
Creates a tree hierarchy out of the path structure of string values.
#include "TreeNodeGrouping.h"
Public Member Functions
FTreeNodeGroupingByPathBreakdown (TSharedRef< FTableColumn > InColumnRef)
virtual ~FTreeNodeGroupingByPathBreakdown ()
TSharedRef< FTableColumn > GetColumn () const
virtual FName GetColumnId () const override
virtual void GroupNodes (const TArray< FTableTreeNodePtr > &Nodes, FTableTreeNode &ParentGroup, TWeakPtr< FTable > InParentTable, IAsyncOperationProgress &InAsyncOperationProgress) const override
Private Member Functions
INSIGHTS_DECLARE_RTTI (FTreeNodeGroupingByPathBreakdown, FTreeNodeGrouping)
Private Attributes
TSharedRef< FTableColumn > ColumnRef
Additional Inherited Members
Protected Member Functions inherited from UE::Insights::FTreeNodeGrouping
UE_DEPRECATED (5.6, "BrushName is not used") FName BrushName
Protected Attributes inherited from UE::Insights::FTreeNodeGrouping
FText Description
const FSlateBrush * Icon
FText ShortName
FText TitleName
Detailed Description
Creates a tree hierarchy out of the path structure of string values.
Definition at line 277 of file TreeNodeGrouping.h.
Constructor & Destructor Documentation
FTreeNodeGroupingByPathBreakdown()
UE::Insights::FTreeNodeGroupingByPathBreakdown::FTreeNodeGroupingByPathBreakdown (TSharedRef< FTableColumn > InColumnRef)
Referenced by INSIGHTS_DECLARE_RTTI().
~FTreeNodeGroupingByPathBreakdown()
virtual UE::Insights::FTreeNodeGroupingByPathBreakdown::~FTreeNodeGroupingByPathBreakdown () inline virtual
Definition at line 283 of file TreeNodeGrouping.h.
Member Function Documentation
GetColumn()
TSharedRef< FTableColumn > UE::Insights::FTreeNodeGroupingByPathBreakdown::GetColumn () const inline
Definition at line 288 of file TreeNodeGrouping.h.
References ColumnRef.
GetColumnId()
virtual FName UE::Insights::FTreeNodeGroupingByPathBreakdown::GetColumnId () const inline override virtual
Reimplemented from UE::Insights::FTreeNodeGrouping.
Definition at line 287 of file TreeNodeGrouping.h.
References ColumnRef.
GroupNodes()
virtual void UE::Insights::FTreeNodeGroupingByPathBreakdown::GroupNodes (const TArray< FTableTreeNodePtr > & Nodes, FTableTreeNode & ParentGroup, TWeakPtr< FTable > InParentTable, IAsyncOperationProgress & InAsyncOperationProgress) const override virtual
Reimplemented from UE::Insights::FTreeNodeGrouping.
INSIGHTS_DECLARE_RTTI()
UE::Insights::FTreeNodeGroupingByPathBreakdown::INSIGHTS_DECLARE_RTTI (FTreeNodeGroupingByPathBreakdown , FTreeNodeGrouping) private
References UE::Insights::FTreeNodeGrouping::FTreeNodeGrouping(), and FTreeNodeGroupingByPathBreakdown().
Field Documentation
ColumnRef
TSharedRef<FTableColumn> UE::Insights::FTreeNodeGroupingByPathBreakdown::ColumnRef private
Definition at line 291 of file TreeNodeGrouping.h.
Referenced by GetColumn(), and GetColumnId().
The documentation for this class was generated from the following file:
Developer/TraceInsightsCore/Public/InsightsCore/Table/ViewModels/TreeNodeGrouping.h