Unreal Engine 5.6 C++ API: FHazardPointerCollection::FHazardRecord Class Reference
FHazardPointerCollection::FHazardRecord Class Reference
Private Member Functions
FHazardRecord ()=default
void * GetHazard () const
void Release ()
void Retire ()
void * SetHazard (void *InHazard)
Private Attributes
std::atomic< uintptr_t > Hazard { FreeHazardEntry }
Static Private Attributes
static constexpr uintptr_t FreeHazardEntry = ~uintptr_t(0)
Friends
class FHazardPointerCollection
template<typename, bool>
class THazardPointer
Detailed Description
Definition at line 77 of file HazardPointer.h.
Constructor & Destructor Documentation
FHazardRecord()
FHazardPointerCollection::FHazardRecord::FHazardRecord () private default
Member Function Documentation
GetHazard()
void * FHazardPointerCollection::FHazardRecord::GetHazard () const inline private
Definition at line 96 of file HazardPointer.h.
References Hazard.
Referenced by FHazardPointerCollection::Acquire().
Release()
void FHazardPointerCollection::FHazardRecord::Release () inline private
Definition at line 116 of file HazardPointer.h.
References FreeHazardEntry, and Hazard.
Retire()
void FHazardPointerCollection::FHazardRecord::Retire () inline private
Definition at line 110 of file HazardPointer.h.
References Hazard.
SetHazard()
void * FHazardPointerCollection::FHazardRecord::SetHazard (void * InHazard) inline nodiscard private
Definition at line 102 of file HazardPointer.h.
References Hazard.
Friends And Related Symbol Documentation
FHazardPointerCollection
friend class FHazardPointerCollection friend
Definition at line 79 of file HazardPointer.h.
References FHazardPointerCollection.
Referenced by FHazardPointerCollection.
THazardPointer
template<typename, bool> friend class THazardPointer friend
Definition at line 82 of file HazardPointer.h.
References THazardPointer.
Referenced by THazardPointer.
Field Documentation
FreeHazardEntry
uintptr_t FHazardPointerCollection::FHazardRecord::FreeHazardEntry = ~uintptr_t(0) static constexpr private
Definition at line 83 of file HazardPointer.h.
Referenced by FHazardPointerCollection::Acquire(), and Release().
Hazard
std::atomic<uintptr_t> FHazardPointerCollection::FHazardRecord::Hazard { FreeHazardEntry } private
Definition at line 85 of file HazardPointer.h.
Referenced by FHazardPointerCollection::Acquire(), GetHazard(), Release(), Retire(), and SetHazard().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Experimental/Containers/HazardPointer.h