Unreal Engine 5.6 C++ API: TWidgetSlotWithAttributeSupport< SlotType > Class Template Reference
TWidgetSlotWithAttributeSupport< SlotType > Class Template Reference
A base slot that supports TSlateContainedAttribute.
#include "WidgetSlotWithAttributeSupport.h"
Data Structures
struct TSlateSlotAttribute
A SlateAttribute that is member variable of a FSlot.
Public Member Functions
virtual ~TWidgetSlotWithAttributeSupport ()
void Construct (const FChildren &SlotOwner, typename Super::FSlotArguments &&InArgs)
virtual FName GetContainerName () const override
virtual uint32 GetContainerSortOrder () const override
virtual SWidget & GetContainerWidget () const override
void RequestSortAttribute ()
Public Member Functions inherited from TSlotBase< SlotType >
void Construct (const FChildren &SlotOwner, FSlotArguments &&InArgs)
SlotType & Expose (SlotType *&OutVarToInit)
FSlotBase ()
FSlotBase (const FChildren &InParent)
FSlotBase (const FSlotBase &)=delete
FSlotBase (const TSharedRef< SWidget > &InWidget)
SlotType & operator[] (const TSharedRef< SWidget > &InChildWidget)
SlotType & operator[] (TSharedRef< SWidget > &&InChildWidget)
Public Member Functions inherited from FSlotBase
FSlotBase ()
FSlotBase (const FChildren &InParent)
FSlotBase (const FSlotBase &)=delete
FSlotBase (const TSharedRef< SWidget > &InWidget)
virtual ~FSlotBase ()
FORCEINLINE_DEBUGGABLE void AttachWidget (const TSharedRef< SWidget > &InWidget)
FORCEINLINE_DEBUGGABLE void AttachWidget (TSharedRef< SWidget > &&InWidget)
Attach the child widget the slot now owns.
const TSharedPtr< SWidget > DetachWidget ()
Remove the widget from its current slot.
const FChildren * GetOwner () const
Access the FChildren that own the slot.
SWidget * GetOwnerWidget () const
Access the widget that own the slot.
FORCEINLINE_DEBUGGABLE const TSharedRef< SWidget > & GetWidget () const
Access the widget in the current slot.
void Invalidate (EInvalidateWidgetReason InvalidateReason)
Invalidate the widget's owner.
FSlotBase & operator= (const FSlotBase &)=delete
void SetOwner (const FChildren &Children)
Set the owner of the slot.
Static Public Member Functions
static void RegisterAttributes (FSlateWidgetSlotAttributeInitializer &AttributeInitializer)
Private Types
using Super = TSlotBase<SlotType>
Additional Inherited Members
Public Types inherited from TSlotBase< SlotType >
enum EConstructSlotIsFChildren { ConstructSlotIsFChildren }
Argument to indicate the Slot is also its owner.
Protected Member Functions inherited from FSlotBase
template<typename TargetValueType, typename SourceValueType>
bool SetAttribute (TAttribute< TargetValueType > &TargetValue, const TAttribute< SourceValueType > &SourceValue, EInvalidateWidgetReason BaseInvalidationReason)
Performs the attribute assignment and invalidates the widget minimally based on what actually changed.
Detailed Description
template<typename SlotType>
class TWidgetSlotWithAttributeSupport< SlotType >
A base slot that supports TSlateContainedAttribute.
The FChildren that own the FSlot also needs to support SlateContainedAttribute.
See also
FChildren::SupportSlotWithSlateAttribute
Definition at line 20 of file WidgetSlotWithAttributeSupport.h.
Member Typedef Documentation
Super
template<typename SlotType> using TWidgetSlotWithAttributeSupport< SlotType >::Super = TSlotBase<SlotType> private
Definition at line 23 of file WidgetSlotWithAttributeSupport.h.
Constructor & Destructor Documentation
~TWidgetSlotWithAttributeSupport()
template<typename SlotType> virtual TWidgetSlotWithAttributeSupport< SlotType >::~TWidgetSlotWithAttributeSupport () inline virtual
Definition at line 38 of file WidgetSlotWithAttributeSupport.h.
References FSlotBase::GetOwnerWidget().
Member Function Documentation
Construct()
template<typename SlotType> void TWidgetSlotWithAttributeSupport< SlotType >::Construct (const FChildren & SlotOwner, typename Super::FSlotArguments && InArgs) inline
Definition at line 46 of file WidgetSlotWithAttributeSupport.h.
References checkf, TSlotBase< SlotType >::Construct(), FChildren::GetName(), FName::IsValid(), MoveTemp(), FChildren::SupportSlotWithSlateAttribute(), TEXT, and FName::ToString().
GetContainerName()
template<typename SlotType> virtual FName TWidgetSlotWithAttributeSupport< SlotType >::GetContainerName () const inline override virtual
Definition at line 76 of file WidgetSlotWithAttributeSupport.h.
References FChildren::GetName(), and FSlotBase::GetOwner().
GetContainerSortOrder()
template<typename SlotType> virtual uint32 TWidgetSlotWithAttributeSupport< SlotType >::GetContainerSortOrder () const inline override virtual
Definition at line 81 of file WidgetSlotWithAttributeSupport.h.
References check, FSlotBase::GetOwner(), and FChildren::NumSlot().
GetContainerWidget()
template<typename SlotType> virtual SWidget & TWidgetSlotWithAttributeSupport< SlotType >::GetContainerWidget () const inline override virtual
Definition at line 69 of file WidgetSlotWithAttributeSupport.h.
References checkf, FSlotBase::GetOwnerWidget(), and TEXT.
RegisterAttributes()
template<typename SlotType> void TWidgetSlotWithAttributeSupport< SlotType >::RegisterAttributes (FSlateWidgetSlotAttributeInitializer & AttributeInitializer) inline static
Definition at line 53 of file WidgetSlotWithAttributeSupport.h.
Referenced by TBasicLayoutWidgetSlot< SlotType >::RegisterAttributes().
RequestSortAttribute()
template<typename SlotType> void TWidgetSlotWithAttributeSupport< SlotType >::RequestSortAttribute () inline
Definition at line 57 of file WidgetSlotWithAttributeSupport.h.
References ensureAlwaysMsgf, FSlotBase::GetOwnerWidget(), and TEXT.
The documentation for this class was generated from the following file:
Runtime/SlateCore/Public/Layout/WidgetSlotWithAttributeSupport.h