Unreal Engine 5.6 C++ API: FRigVMCommentNodeDetailCustomization Class Reference
FRigVMCommentNodeDetailCustomization Class Reference
#include "RigVMCommentNodeDetailCustomization.h"
Public Member Functions
virtual void CustomizeDetails (IDetailLayoutBuilder &DetailBuilder) override
IDetailCustomization interface.
Public Member Functions inherited from IDetailCustomization
virtual ~IDetailCustomization ()
virtual void CustomizeDetails (const TSharedPtr< IDetailLayoutBuilder > &DetailBuilder)
Called when details should be customized, this version allows the customization to store a weak ptr to the layout builder.
virtual void PendingDelete ()
Called when no longer used and will be deleted.
Public Member Functions inherited from TSharedFromThis< IDetailCustomization >
TSharedRef< IDetailCustomization, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< IDetailCustomization, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Static Public Member Functions
static TSharedRef< IDetailCustomization > MakeInstance ()
Private Member Functions
FRigVMCommentNodeDetailCustomization ()
FLinearColor GetColor () const
TOptional< int > GetFontSize () const
FText GetText () const
void GetValuesFromNode (TWeakObjectPtr< URigVMCommentNode > Node)
ECheckBoxState IsColorBubbleEnabled () const
ECheckBoxState IsShowingBubbleEnabled () const
FReply OnChooseColor (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
void OnColorBubbleStateChanged (ECheckBoxState InValue)
void OnColorPicked (FLinearColor LinearColor)
void OnFontSizeChanged (int32 InValue, ETextCommit::Type Arg)
void OnShowingBubbleStateChanged (ECheckBoxState InValue)
void SetText (const FText &InNewText, ETextCommit::Type InCommitType)
void SetValues (TWeakObjectPtr< URigVMCommentNode > Node)
Private Attributes
bool bBubbleColorEnabled
URigVMBlueprint * BlueprintBeingCustomized
bool bShowingBubble
FString CommentText
int32 FontSize
TArray< TWeakObjectPtr< URigVMCommentNode > > ObjectsBeingCustomized
Additional Inherited Members
Protected Member Functions inherited from TSharedFromThis< IDetailCustomization >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions inherited from TSharedFromThis< IDetailCustomization >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
Definition at line 16 of file RigVMCommentNodeDetailCustomization.h.
Constructor & Destructor Documentation
FRigVMCommentNodeDetailCustomization()
FRigVMCommentNodeDetailCustomization::FRigVMCommentNodeDetailCustomization () inline private
Definition at line 18 of file RigVMCommentNodeDetailCustomization.h.
References BlueprintBeingCustomized.
Referenced by MakeInstance().
Member Function Documentation
CustomizeDetails()
virtual void FRigVMCommentNodeDetailCustomization::CustomizeDetails (IDetailLayoutBuilder & DetailBuilder) override virtual
IDetailCustomization interface.
Implements IDetailCustomization.
GetColor()
FLinearColor FRigVMCommentNodeDetailCustomization::GetColor () const private
GetFontSize()
TOptional< int > FRigVMCommentNodeDetailCustomization::GetFontSize () const private
GetText()
FText FRigVMCommentNodeDetailCustomization::GetText () const private
GetValuesFromNode()
void FRigVMCommentNodeDetailCustomization::GetValuesFromNode (TWeakObjectPtr< URigVMCommentNode > Node) private
IsColorBubbleEnabled()
ECheckBoxState FRigVMCommentNodeDetailCustomization::IsColorBubbleEnabled () const private
IsShowingBubbleEnabled()
ECheckBoxState FRigVMCommentNodeDetailCustomization::IsShowingBubbleEnabled () const private
MakeInstance()
TSharedRef< IDetailCustomization > FRigVMCommentNodeDetailCustomization::MakeInstance () inline static
Definition at line 26 of file RigVMCommentNodeDetailCustomization.h.
References FRigVMCommentNodeDetailCustomization(), and MakeShareable().
OnChooseColor()
FReply FRigVMCommentNodeDetailCustomization::OnChooseColor (const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) private
References MouseEvent.
OnColorBubbleStateChanged()
void FRigVMCommentNodeDetailCustomization::OnColorBubbleStateChanged (ECheckBoxState InValue) private
OnColorPicked()
void FRigVMCommentNodeDetailCustomization::OnColorPicked (FLinearColor LinearColor) private
References LinearColor.
OnFontSizeChanged()
void FRigVMCommentNodeDetailCustomization::OnFontSizeChanged (int32 InValue, ETextCommit::Type Arg) private
OnShowingBubbleStateChanged()
void FRigVMCommentNodeDetailCustomization::OnShowingBubbleStateChanged (ECheckBoxState InValue) private
SetText()
void FRigVMCommentNodeDetailCustomization::SetText (const FText & InNewText, ETextCommit::Type InCommitType) private
SetValues()
void FRigVMCommentNodeDetailCustomization::SetValues (TWeakObjectPtr< URigVMCommentNode > Node) private
Field Documentation
bBubbleColorEnabled
bool FRigVMCommentNodeDetailCustomization::bBubbleColorEnabled private
Definition at line 60 of file RigVMCommentNodeDetailCustomization.h.
BlueprintBeingCustomized
URigVMBlueprint* FRigVMCommentNodeDetailCustomization::BlueprintBeingCustomized private
Definition at line 36 of file RigVMCommentNodeDetailCustomization.h.
Referenced by FRigVMCommentNodeDetailCustomization().
bShowingBubble
bool FRigVMCommentNodeDetailCustomization::bShowingBubble private
Definition at line 59 of file RigVMCommentNodeDetailCustomization.h.
CommentText
FString FRigVMCommentNodeDetailCustomization::CommentText private
Definition at line 58 of file RigVMCommentNodeDetailCustomization.h.
FontSize
int32 FRigVMCommentNodeDetailCustomization::FontSize private
Definition at line 61 of file RigVMCommentNodeDetailCustomization.h.
ObjectsBeingCustomized
TArray<TWeakObjectPtr<URigVMCommentNode> > FRigVMCommentNodeDetailCustomization::ObjectsBeingCustomized private
Definition at line 37 of file RigVMCommentNodeDetailCustomization.h.
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/RigVM/Source/RigVMEditor/Public/Editor/RigVMCommentNodeDetailCustomization.h