Unreal Engine 5.6 C++ API: UE::Geometry::FSmallListSet::BaseValueIterator Class Reference
UE::Geometry::FSmallListSet::BaseValueIterator Class Reference
BaseValueIterator is a base class for ValueIterator and MappedValueIterator below.
#include "SmallListSet.h"
Public Member Functions
BaseValueIterator ()
bool operator!= (const BaseValueIterator &Other) const
bool operator== (const BaseValueIterator &Other) const
Protected Member Functions
BaseValueIterator (const FSmallListSet *ListSetIn, int32 ListIndex, bool is_end)
void GotoNext ()
void GotoNextOverflow ()
void SetToEnd ()
Protected Attributes
int32 block_ptr
int32 cur_ptr
int32 cur_value
int32 iCur
int32 iEnd
int32 ListIndex
const FSmallListSet * ListSet
int32 N
Friends
class FSmallListSet
Detailed Description
BaseValueIterator is a base class for ValueIterator and MappedValueIterator below.
Definition at line 406 of file SmallListSet.h.
Constructor & Destructor Documentation
BaseValueIterator() [1/2]
UE::Geometry::FSmallListSet::BaseValueIterator::BaseValueIterator () inline
Definition at line 409 of file SmallListSet.h.
References ListIndex, and ListSet.
Referenced by UE::Geometry::FSmallListSet::MappedValueIterator::MappedValueIterator(), UE::Geometry::FSmallListSet::MappedValueIterator::MappedValueIterator(), UE::Geometry::FSmallListSet::ValueIterator::ValueIterator(), UE::Geometry::FSmallListSet::ValueIterator::ValueIterator(), operator!=(), and operator==().
BaseValueIterator() [2/2]
UE::Geometry::FSmallListSet::BaseValueIterator::BaseValueIterator (const FSmallListSet * ListSetIn, int32 ListIndex, bool is_end) inline protected
Definition at line 453 of file SmallListSet.h.
References UE::Geometry::FSmallListSet::BLOCK_LIST_OFFSET, block_ptr, UE::Geometry::FSmallListSet::BLOCKSIZE, cur_ptr, FSmallListSet, GotoNext(), iCur, iEnd, ListIndex, ListSet, N, UE::Geometry::FSmallListSet::NullValue, and SetToEnd().
Member Function Documentation
GotoNext()
void UE::Geometry::FSmallListSet::BaseValueIterator::GotoNext () inline protected
Definition at line 425 of file SmallListSet.h.
References GotoNextOverflow(), N, and SetToEnd().
Referenced by BaseValueIterator(), UE::Geometry::FSmallListSet::MappedValueIterator::operator++(), and UE::Geometry::FSmallListSet::ValueIterator::operator++().
GotoNextOverflow()
void UE::Geometry::FSmallListSet::BaseValueIterator::GotoNextOverflow () inline protected
Definition at line 435 of file SmallListSet.h.
References cur_ptr, cur_value, iCur, iEnd, ListSet, UE::Geometry::FSmallListSet::NullValue, and SetToEnd().
Referenced by GotoNext().
operator!=()
bool UE::Geometry::FSmallListSet::BaseValueIterator::operator!= (const BaseValueIterator & Other) const inline
Definition at line 419 of file SmallListSet.h.
References BaseValueIterator(), cur_ptr, iCur, ListIndex, ListSet, and Other.
operator==()
bool UE::Geometry::FSmallListSet::BaseValueIterator::operator== (const BaseValueIterator & Other) const inline
Definition at line 415 of file SmallListSet.h.
References BaseValueIterator(), ListIndex, ListSet, and Other.
SetToEnd()
void UE::Geometry::FSmallListSet::BaseValueIterator::SetToEnd () inline protected
Definition at line 482 of file SmallListSet.h.
References block_ptr, cur_ptr, iCur, ListSet, and N.
Referenced by BaseValueIterator(), GotoNext(), and GotoNextOverflow().
Friends And Related Symbol Documentation
FSmallListSet
friend class FSmallListSet friend
Definition at line 498 of file SmallListSet.h.
References FSmallListSet.
Referenced by BaseValueIterator(), and FSmallListSet.
Field Documentation
block_ptr
int32 UE::Geometry::FSmallListSet::BaseValueIterator::block_ptr protected
Definition at line 492 of file SmallListSet.h.
Referenced by BaseValueIterator(), and SetToEnd().
cur_ptr
int32 UE::Geometry::FSmallListSet::BaseValueIterator::cur_ptr protected
Definition at line 496 of file SmallListSet.h.
Referenced by BaseValueIterator(), GotoNextOverflow(), operator!=(), and SetToEnd().
cur_value
int32 UE::Geometry::FSmallListSet::BaseValueIterator::cur_value protected
Definition at line 497 of file SmallListSet.h.
Referenced by GotoNextOverflow(), UE::Geometry::FSmallListSet::MappedValueIterator::operator*(), and UE::Geometry::FSmallListSet::ValueIterator::operator*().
iCur
int32 UE::Geometry::FSmallListSet::BaseValueIterator::iCur protected
Definition at line 495 of file SmallListSet.h.
Referenced by BaseValueIterator(), GotoNextOverflow(), operator!=(), and SetToEnd().
iEnd
int32 UE::Geometry::FSmallListSet::BaseValueIterator::iEnd protected
Definition at line 494 of file SmallListSet.h.
Referenced by BaseValueIterator(), and GotoNextOverflow().
ListIndex
int32 UE::Geometry::FSmallListSet::BaseValueIterator::ListIndex protected
Definition at line 491 of file SmallListSet.h.
Referenced by BaseValueIterator(), BaseValueIterator(), UE::Geometry::FSmallListSet::MappedValueIterator::MappedValueIterator(), UE::Geometry::FSmallListSet::ValueIterator::ValueIterator(), operator!=(), and operator==().
ListSet
const FSmallListSet* UE::Geometry::FSmallListSet::BaseValueIterator::ListSet protected
Definition at line 490 of file SmallListSet.h.
Referenced by BaseValueIterator(), BaseValueIterator(), GotoNextOverflow(), operator!=(), operator==(), and SetToEnd().
N
int32 UE::Geometry::FSmallListSet::BaseValueIterator::N protected
Definition at line 493 of file SmallListSet.h.
Referenced by BaseValueIterator(), GotoNext(), and SetToEnd().
The documentation for this class was generated from the following file:
Runtime/GeometryCore/Public/Util/SmallListSet.h