Unreal Engine 5.6 C++ API: Metasound::FVertexInterface Class Reference
Metasound::FVertexInterface Class Reference
FVertexInterface provides access to a collection of input and output vertex interfaces.
#include "MetasoundVertex.h"
Public Member Functions
FVertexInterface ()=default
Default constructor.
METASOUNDGRAPHCORE_API FVertexInterface (const FInputVertexInterface &InInputs, const FOutputVertexInterface &InOutputs)
Construct with an input and output interface.
METASOUNDGRAPHCORE_API FVertexInterface (FInputVertexInterface InInputs, FOutputVertexInterface InOutputs, FEnvironmentVertexInterface InEnvironmentVariables)
Construct with input, output and environment interface.
METASOUNDGRAPHCORE_API bool ContainsEnvironmentVertex (const FVertexName &InKey) const
Returns true if an output vertex with the given key exists.
METASOUNDGRAPHCORE_API bool ContainsInputVertex (const FVertexName &InKey) const
Returns true if an input vertex with the given key exists.
METASOUNDGRAPHCORE_API bool ContainsOutputVertex (const FVertexName &InName) const
Returns true if an output vertex with the given name exists.
METASOUNDGRAPHCORE_API FEnvironmentVertexInterface & GetEnvironmentInterface ()
Return the output interface.
METASOUNDGRAPHCORE_API const FEnvironmentVertexInterface & GetEnvironmentInterface () const
Return the output interface.
METASOUNDGRAPHCORE_API const FEnvironmentVertex & GetEnvironmentVertex (const FVertexName &InKey) const
Return an output vertex.
METASOUNDGRAPHCORE_API FInputVertexInterface & GetInputInterface ()
Return the input interface.
METASOUNDGRAPHCORE_API const FInputVertexInterface & GetInputInterface () const
Return the input interface.
METASOUNDGRAPHCORE_API const FInputDataVertex & GetInputVertex (const FVertexName &InKey) const
Return an input vertex.
METASOUNDGRAPHCORE_API FOutputVertexInterface & GetOutputInterface ()
Return the output interface.
METASOUNDGRAPHCORE_API const FOutputVertexInterface & GetOutputInterface () const
Return the output interface.
METASOUNDGRAPHCORE_API const FOutputDataVertex & GetOutputVertex (const FVertexName &InName) const
Return an output vertex.
Private Attributes
FEnvironmentVertexInterface EnvironmentInterface
FInputVertexInterface InputInterface
FOutputVertexInterface OutputInterface
Friends
bool METASOUNDGRAPHCORE_API operator!= (const FVertexInterface &InLHS, const FVertexInterface &InRHS)
Test for inequality between two interfaces.
bool METASOUNDGRAPHCORE_API operator== (const FVertexInterface &InLHS, const FVertexInterface &InRHS)
Test for equality between two interfaces.
Detailed Description
FVertexInterface provides access to a collection of input and output vertex interfaces.
Definition at line 746 of file MetasoundVertex.h.
Constructor & Destructor Documentation
FVertexInterface() [1/3]
Metasound::FVertexInterface::FVertexInterface () default
Default constructor.
Referenced by operator!=, and operator==.
FVertexInterface() [2/3]
METASOUNDGRAPHCORE_API Metasound::FVertexInterface::FVertexInterface (const FInputVertexInterface & InInputs, const FOutputVertexInterface & InOutputs)
Construct with an input and output interface.
References UE_API.
FVertexInterface() [3/3]
METASOUNDGRAPHCORE_API Metasound::FVertexInterface::FVertexInterface (FInputVertexInterface InInputs, FOutputVertexInterface InOutputs, FEnvironmentVertexInterface InEnvironmentVariables)
Construct with input, output and environment interface.
References UE_API.
Member Function Documentation
ContainsEnvironmentVertex()
METASOUNDGRAPHCORE_API bool Metasound::FVertexInterface::ContainsEnvironmentVertex (const FVertexName & InKey) const
Returns true if an output vertex with the given key exists.
References UE_API.
ContainsInputVertex()
METASOUNDGRAPHCORE_API bool Metasound::FVertexInterface::ContainsInputVertex (const FVertexName & InKey) const
Returns true if an input vertex with the given key exists.
References UE_API.
ContainsOutputVertex()
METASOUNDGRAPHCORE_API bool Metasound::FVertexInterface::ContainsOutputVertex (const FVertexName & InName) const
Returns true if an output vertex with the given name exists.
References InName, and UE_API.
GetEnvironmentInterface() [1/2]
METASOUNDGRAPHCORE_API FEnvironmentVertexInterface & Metasound::FVertexInterface::GetEnvironmentInterface ()
Return the output interface.
References UE_API.
GetEnvironmentInterface() [2/2]
METASOUNDGRAPHCORE_API const FEnvironmentVertexInterface & Metasound::FVertexInterface::GetEnvironmentInterface () const
Return the output interface.
References UE_API.
GetEnvironmentVertex()
METASOUNDGRAPHCORE_API const FEnvironmentVertex & Metasound::FVertexInterface::GetEnvironmentVertex (const FVertexName & InKey) const
Return an output vertex.
References UE_API.
GetInputInterface() [1/2]
METASOUNDGRAPHCORE_API FInputVertexInterface & Metasound::FVertexInterface::GetInputInterface ()
Return the input interface.
References UE_API.
GetInputInterface() [2/2]
METASOUNDGRAPHCORE_API const FInputVertexInterface & Metasound::FVertexInterface::GetInputInterface () const
Return the input interface.
References UE_API.
Referenced by Metasound::Frontend::MetasoundDataTypeRegistrationPrivate::RegisterDataTypeWithFrontendInternal().
GetInputVertex()
METASOUNDGRAPHCORE_API const FInputDataVertex & Metasound::FVertexInterface::GetInputVertex (const FVertexName & InKey) const
Return an input vertex.
References UE_API.
GetOutputInterface() [1/2]
METASOUNDGRAPHCORE_API FOutputVertexInterface & Metasound::FVertexInterface::GetOutputInterface ()
Return the output interface.
References UE_API.
GetOutputInterface() [2/2]
METASOUNDGRAPHCORE_API const FOutputVertexInterface & Metasound::FVertexInterface::GetOutputInterface () const
Return the output interface.
References UE_API.
GetOutputVertex()
METASOUNDGRAPHCORE_API const FOutputDataVertex & Metasound::FVertexInterface::GetOutputVertex (const FVertexName & InName) const
Return an output vertex.
References InName, and UE_API.
Friends And Related Symbol Documentation
operator!=
bool METASOUNDGRAPHCORE_API operator!= (const FVertexInterface & InLHS, const FVertexInterface & InRHS) friend
Test for inequality between two interfaces.
References FVertexInterface().
operator==
bool METASOUNDGRAPHCORE_API operator== (const FVertexInterface & InLHS, const FVertexInterface & InRHS) friend
Test for equality between two interfaces.
References FVertexInterface().
Field Documentation
EnvironmentInterface
FEnvironmentVertexInterface Metasound::FVertexInterface::EnvironmentInterface private
Definition at line 805 of file MetasoundVertex.h.
InputInterface
FInputVertexInterface Metasound::FVertexInterface::InputInterface private
Definition at line 803 of file MetasoundVertex.h.
OutputInterface
FOutputVertexInterface Metasound::FVertexInterface::OutputInterface private
Definition at line 804 of file MetasoundVertex.h.
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/Metasound/Source/MetasoundGraphCore/Public/MetasoundVertex.h