Unreal Engine 5.6 C++ API: FHazardPointerCollection Class Reference
FHazardPointerCollection Class Reference
FHazardPointerCollection is a collection that is used to aquire a Hazardpointer.
#include "HazardPointer.h"
Data Structures
class FHazardRecord
struct FHazardRecordChunk
struct FTlsData
class THazardDeleter
Public Member Functions
FHazardPointerCollection ()
~FHazardPointerCollection ()
template<bool Cached>
FHazardRecord * Acquire ()
template<typename D>
void Delete (D *Pointer, int32 CollectLimit=-1)
Private Member Functions
void Collect (TArray< HazardPointer_Impl::FHazardDeleter > &Collectables)
void Delete (const HazardPointer_Impl::FHazardDeleter &Deleter, int32 CollectLimit)
template<bool Cached>
FHazardRecord * Grow ()
Private Attributes
TArray< FTlsData * > AllTlsVariables
FCriticalSection AllTlsVariablesCS
uint32 CollectablesTlsSlot = FPlatformTLS::InvalidTlsSlot
TArray< FHazardRecordChunk * > HazardRecordBlocks
FCriticalSection HazardRecordBlocksCS
FHazardRecordChunk Head
std::atomic_uint TotalNumHazardRecords { HazardChunkSize }
Static Private Attributes
static constexpr uint32 HazardChunkSize = 32
Friends
template<typename, bool>
class THazardPointer
Detailed Description
FHazardPointerCollection is a collection that is used to aquire a Hazardpointer.
Definition at line 57 of file HazardPointer.h.
Constructor & Destructor Documentation
FHazardPointerCollection()
FHazardPointerCollection::FHazardPointerCollection () inline
Definition at line 174 of file HazardPointer.h.
References FAndroidTLS::AllocTlsSlot(), and CollectablesTlsSlot.
~FHazardPointerCollection()
FHazardPointerCollection::~FHazardPointerCollection ()
Member Function Documentation
Acquire()
template<bool Cached> FHazardRecord * FHazardPointerCollection::Acquire () inline
Definition at line 183 of file HazardPointer.h.
References checkSlow, FHazardPointerCollection::FHazardRecord::FreeHazardEntry, FHazardPointerCollection::FHazardRecord::GetHazard(), Grow(), FHazardPointerCollection::FHazardRecord::Hazard, HazardChunkSize, Head, FHazardPointerCollection::FHazardRecordChunk::Next, and FHazardPointerCollection::FHazardRecordChunk::Records.
Collect()
void FHazardPointerCollection::Collect (TArray< HazardPointer_Impl::FHazardDeleter > & Collectables) private
Delete() [1/2]
void FHazardPointerCollection::Delete (const HazardPointer_Impl::FHazardDeleter & Deleter, int32 CollectLimit) private
Delete() [2/2]
template<typename D> void FHazardPointerCollection::Delete (D * Pointer, int32 CollectLimit = -1) inline
Definition at line 230 of file HazardPointer.h.
References Delete, and Pointer.
Grow()
template<bool Cached> FHazardRecord * FHazardPointerCollection::Grow () private
Referenced by Acquire().
Friends And Related Symbol Documentation
THazardPointer
template<typename, bool> friend class THazardPointer friend
Definition at line 60 of file HazardPointer.h.
References THazardPointer.
Referenced by THazardPointer.
Field Documentation
AllTlsVariables
TArray<FTlsData*> FHazardPointerCollection::AllTlsVariables private
Definition at line 159 of file HazardPointer.h.
AllTlsVariablesCS
FCriticalSection FHazardPointerCollection::AllTlsVariablesCS private
Definition at line 157 of file HazardPointer.h.
CollectablesTlsSlot
uint32 FHazardPointerCollection::CollectablesTlsSlot = FPlatformTLS::InvalidTlsSlot private
Definition at line 162 of file HazardPointer.h.
Referenced by FHazardPointerCollection().
HazardChunkSize
uint32 FHazardPointerCollection::HazardChunkSize = 32 static constexpr private
Definition at line 138 of file HazardPointer.h.
Referenced by Acquire().
HazardRecordBlocks
TArray<FHazardRecordChunk*> FHazardPointerCollection::HazardRecordBlocks private
Definition at line 160 of file HazardPointer.h.
HazardRecordBlocksCS
FCriticalSection FHazardPointerCollection::HazardRecordBlocksCS private
Definition at line 158 of file HazardPointer.h.
Head
FHazardRecordChunk FHazardPointerCollection::Head private
Definition at line 155 of file HazardPointer.h.
Referenced by Acquire().
TotalNumHazardRecords
std::atomic_uint FHazardPointerCollection::TotalNumHazardRecords { HazardChunkSize } private
Definition at line 163 of file HazardPointer.h.
The documentation for this class was generated from the following file:
Runtime/Core/Public/Experimental/Containers/HazardPointer.h