Unreal Engine 5.6 C++ API: FFleshCollection Class Reference
FFleshCollection Class Reference
FFleshCollection (FTetrehidralCollection)
#include "FleshCollection.h"
Public Types
typedef GeometryCollection::Facades::FSelectionFacade::FSelectionKey FBindingKey
typedef FTetrahedralCollection Super
Public Member Functions
FFleshCollection ()
FFleshCollection (FFleshCollection &&)=default
FFleshCollection (FFleshCollection &)=delete
FFleshCollection & operator= (const FFleshCollection &)=delete
FFleshCollection & operator= (FFleshCollection &&)=default
Public Member Functions inherited from FTetrahedralCollection
CHAOSFLESH_API FTetrahedralCollection ()
FTetrahedralCollection (FTetrahedralCollection &&)=default
FTetrahedralCollection (FTetrahedralCollection &)=delete
CHAOSFLESH_API void AppendCollection (const FTetrahedralCollection &InCollection)
CHAOSFLESH_API int32 AppendGeometry (const FTetrahedralCollection &GeometryCollection, int32 MaterialIDOffset=0, bool ReindexAllMaterials=true, const FTransform &TransformRoot=FTransform::Identity)
CHAOSFLESH_API void InitIncidentElements (const int32 GeometryIndex=-1)
Build IncidentElements and IncidentElementsLocalIndex.
FTetrahedralCollection & operator= (const FTetrahedralCollection &)=delete
FTetrahedralCollection & operator= (FTetrahedralCollection &&)=default
CHAOSFLESH_API void RemoveVertices (const TArray< int32 > &SortedVertexIndices)
Remove selected vertices.
CHAOSFLESH_API void ReorderElements (FName Group, const TArray< int32 > &NewOrder) override
Reorders elements in a group.
CHAOSFLESH_API void ReorderTetrahedralElements (const TArray< int32 > &NewOrder)
virtual CHAOSFLESH_API void SetDefaults (FName Group, uint32 StartSize, uint32 NumElements) override
CHAOSFLESH_API void UpdateBoundingBox ()
Static Public Member Functions
static void Init (FFleshCollection *Collection, const TArray< FVector > &Vertices, const TArray< FIntVector3 > &SurfaceElements, const TArray< FIntVector4 > &Elements, bool bReverseVertexOrder=true)
static FFleshCollection * NewFleshCollection (const FTetrahedralCollection &Base)
Create a GeometryCollection from Vertex and Indices arrays.
static FFleshCollection * NewFleshCollection (const TArray< FVector > &Vertices, const TArray< FIntVector3 > &SurfaceElements, const TArray< FIntVector4 > &Elements, bool bReverseVertexOrder=true)
static FFleshCollection * NewFleshCollection (const TArray< FVector > &Vertices, const TArray< FIntVector4 > &Elements, const bool bReverseVertexOrder=true, const bool KeepInteriorFaces=false, const bool InvertFaces=false)
Static Public Member Functions inherited from FTetrahedralCollection
static CHAOSFLESH_API void Init (FTetrahedralCollection *Collection, const TArray< FVector > &Vertices, const TArray< FIntVector3 > &SurfaceElements, const TArray< FIntVector4 > &Elements, bool bReverseVertexOrder=true)
static CHAOSFLESH_API FTetrahedralCollection * NewTetrahedralCollection (const TArray< FVector > &Vertices, const TArray< FIntVector3 > &SurfaceElements, const TArray< FIntVector4 > &Elements, bool bReverseVertexOrder=true)
Create a GeometryCollection from Vertex and Indices arrays.
Data Fields
TManagedArray< float > Mass
Data Fields inherited from FTetrahedralCollection
TManagedArray< FString > Guid
TManagedArray< TArray< int32 > > IncidentElements
TManagedArray< TArray< int32 > > IncidentElementsLocalIndex
TManagedArray< FIntVector4 > Tetrahedron
TManagedArray< int32 > TetrahedronCount
TManagedArray< int32 > TetrahedronStart
Static Public Attributes
static const FName MassAttribute
Static Public Attributes inherited from FTetrahedralCollection
static CHAOSFLESH_API const FName BindingsGroup
static CHAOSFLESH_API const FName GuidAttribute
static CHAOSFLESH_API const FName IncidentElementsAttribute
Incident Elements Attribute For each vertex, a list of tetrahedra that includes that vertex.
static CHAOSFLESH_API const FName IncidentElementsLocalIndexAttribute
Incident Elements Attribute For each incident element, the vertex's index in the tetrahedron.
static CHAOSFLESH_API const FName TetrahedralGroup
static CHAOSFLESH_API const FName TetrahedronAttribute
static CHAOSFLESH_API const FName TetrahedronCountAttribute
static CHAOSFLESH_API const FName TetrahedronStartAttribute
Protected Member Functions
void Construct ()
Protected Member Functions inherited from FTetrahedralCollection
virtual CHAOSFLESH_API void Append (const FManagedArrayCollection &InCollection) override
CHAOSFLESH_API void Construct ()
Detailed Description
FFleshCollection (FTetrehidralCollection)
Definition at line 17 of file FleshCollection.h.
Member Typedef Documentation
FBindingKey
typedef GeometryCollection::Facades::FSelectionFacade::FSelectionKey FFleshCollection::FBindingKey
Definition at line 21 of file FleshCollection.h.
Super
typedef FTetrahedralCollection FFleshCollection::Super
Definition at line 20 of file FleshCollection.h.
Constructor & Destructor Documentation
FFleshCollection() [1/3]
FFleshCollection::FFleshCollection ()
Referenced by FFleshCollection(), FFleshCollection(), Init(), NewFleshCollection(), NewFleshCollection(), NewFleshCollection(), operator=(), and operator=().
FFleshCollection() [2/3]
FFleshCollection::FFleshCollection (FFleshCollection &) delete
References FFleshCollection().
FFleshCollection() [3/3]
FFleshCollection::FFleshCollection (FFleshCollection &&) default
References FFleshCollection().
Member Function Documentation
Construct()
void FFleshCollection::Construct () protected
Init()
void FFleshCollection::Init (FFleshCollection * Collection, const TArray< FVector > & Vertices, const TArray< FIntVector3 > & SurfaceElements, const TArray< FIntVector4 > & Elements, bool bReverseVertexOrder = true) static
References FFleshCollection().
NewFleshCollection() [1/3]
FFleshCollection * FFleshCollection::NewFleshCollection (const FTetrahedralCollection & Base) static
Create a GeometryCollection from Vertex and Indices arrays.
References FFleshCollection(), and FTetrahedralCollection::FTetrahedralCollection().
NewFleshCollection() [2/3]
FFleshCollection * FFleshCollection::NewFleshCollection (const TArray< FVector > & Vertices, const TArray< FIntVector3 > & SurfaceElements, const TArray< FIntVector4 > & Elements, bool bReverseVertexOrder = true) static
References FFleshCollection().
NewFleshCollection() [3/3]
FFleshCollection * FFleshCollection::NewFleshCollection (const TArray< FVector > & Vertices, const TArray< FIntVector4 > & Elements, const bool bReverseVertexOrder = true, const bool KeepInteriorFaces = false, const bool InvertFaces = false) static
References FFleshCollection().
operator=() [1/2]
FFleshCollection & FFleshCollection::operator= (const FFleshCollection &) delete
References FFleshCollection().
operator=() [2/2]
FFleshCollection & FFleshCollection::operator= (FFleshCollection &&) default
References FFleshCollection().
Field Documentation
Mass
TManagedArray<float> FFleshCollection::Mass
Definition at line 43 of file FleshCollection.h.
MassAttribute
const FName FFleshCollection::MassAttribute static
Definition at line 42 of file FleshCollection.h.
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Experimental/ChaosFlesh/Source/ChaosFlesh/Public/ChaosFlesh/FleshCollection.h