Unreal Engine 5.6 C++ API: FRigVMCallstack Class Reference
FRigVMCallstack Class Reference
#include "RigVMASTProxy.h"
Public Member Functions
bool Contains (const UObject *InEntry) const
FString GetCallPath (bool bIncludeLast=true) const
FRigVMCallstack GetCallStackUpTo (int32 InIndex) const
TArray< TWeakObjectPtr< UObject > > GetStack () const
const UObject * Last () const
int32 Num () const
bool operator!= (const FRigVMCallstack &Other) const
bool operator< (const FRigVMCallstack &Other) const
bool operator== (const FRigVMCallstack &Other) const
bool operator> (const FRigVMCallstack &Other) const
const UObject * operator[] (int32 InIndex) const
Private Member Functions
uint32 GetEntryTypeHash (int32 Index) const
Private Attributes
TArray< TWeakObjectPtr< UObject > > Stack
Friends
class FRigVMASTProxy
class FRigVMCallstackGuard
class FRigVMParserAST
uint32 GetTypeHash (const FRigVMCallstack &Callstack)
class URigVMCompiler
Detailed Description
Definition at line 13 of file RigVMASTProxy.h.
Member Function Documentation
Contains()
bool FRigVMCallstack::Contains (const UObject * InEntry) const
GetCallPath()
FString FRigVMCallstack::GetCallPath (bool bIncludeLast = true) const
Referenced by FRigVMASTProxy::GetSibling().
GetCallStackUpTo()
FRigVMCallstack FRigVMCallstack::GetCallStackUpTo (int32 InIndex) const
GetEntryTypeHash()
uint32 FRigVMCallstack::GetEntryTypeHash (int32 Index) const inline private
Definition at line 104 of file RigVMASTProxy.h.
References GetEntryTypeHash(), GetTypeHash(), HashCombine(), and Stack.
Referenced by GetEntryTypeHash(), and GetTypeHash.
GetStack()
TArray< TWeakObjectPtr< UObject > > FRigVMCallstack::GetStack () const inline
Definition at line 98 of file RigVMASTProxy.h.
References Stack.
Last()
const UObject * FRigVMCallstack::Last () const
Num()
int32 FRigVMCallstack::Num () const
Referenced by GetTypeHash.
operator!=()
bool FRigVMCallstack::operator!= (const FRigVMCallstack & Other) const inline
Definition at line 53 of file RigVMASTProxy.h.
References Other.
operator<()
bool FRigVMCallstack::operator< (const FRigVMCallstack & Other) const inline
Definition at line 58 of file RigVMASTProxy.h.
References Num, operator[](), and Other.
operator==()
bool FRigVMCallstack::operator== (const FRigVMCallstack & Other) const inline
Definition at line 37 of file RigVMASTProxy.h.
References Num, and Other.
operator>()
bool FRigVMCallstack::operator> (const FRigVMCallstack & Other) const inline
Definition at line 78 of file RigVMASTProxy.h.
References Num, operator[](), and Other.
operator[]()
const UObject * FRigVMCallstack::operator[] (int32 InIndex) const
Referenced by operator<(), and operator>().
Friends And Related Symbol Documentation
FRigVMASTProxy
friend class FRigVMASTProxy friend
Definition at line 121 of file RigVMASTProxy.h.
References FRigVMASTProxy.
Referenced by FRigVMASTProxy.
FRigVMCallstackGuard
friend class FRigVMCallstackGuard friend
Definition at line 120 of file RigVMASTProxy.h.
References FRigVMCallstackGuard.
Referenced by FRigVMCallstackGuard.
FRigVMParserAST
friend class FRigVMParserAST friend
Definition at line 119 of file RigVMASTProxy.h.
References FRigVMParserAST.
Referenced by FRigVMParserAST.
GetTypeHash
uint32 GetTypeHash (const FRigVMCallstack & Callstack) friend
Definition at line 32 of file RigVMASTProxy.h.
References GetEntryTypeHash(), and Num().
URigVMCompiler
friend class URigVMCompiler friend
Definition at line 122 of file RigVMASTProxy.h.
References URigVMCompiler.
Referenced by URigVMCompiler.
Field Documentation
Stack
TArray<TWeakObjectPtr<UObject> > FRigVMCallstack::Stack private
Definition at line 117 of file RigVMASTProxy.h.
Referenced by FRigVMASTProxy::FRigVMASTProxy(), GetEntryTypeHash(), FRigVMASTProxy::GetSibling(), GetStack(), and FRigVMASTProxy::operator=().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/RigVM/Source/RigVMDeveloper/Public/RigVMCompiler/RigVMASTProxy.h