Unreal Engine 5.6 C++ API: IStretcherAndPitchShifterFactory Class Reference
IStretcherAndPitchShifterFactory Class Reference abstract
#include "StretcherAndPitchShifterFactory.h"
Public Member Functions
virtual HARMONIXDSP_API ~IStretcherAndPitchShifterFactory ()
virtual const TArray< FName > & GetFactoryNames () const =0
Gets the name of this factory type.
virtual TSharedPtr< IStretcherAndPitchShifter, ESPMode::ThreadSafe > GetFreePitchShifter (const FTimeStretchConfig &InConfig)=0
The factory has the ability to pool pitch shifters.
virtual size_t GetMemoryUsedByPool () const =0
Should return number of bytes used by all of the shifters in the pool.
virtual bool HasFreePitchShifters (const FTimeStretchConfig &InConfig) const =0
The factory has the ability to pool pitch shifters.
virtual void ReleasePitchShifter (TSharedPtr< IStretcherAndPitchShifter, ESPMode::ThreadSafe >)=0
The factory has the ability to pool pitch shifters.
virtual void SetFormantVolumeCorrection (float DBPerHalfStepUp, float DBPerHalfStepDown, float DBMaxUp, float DBMaxDown)
Update the pitch shifters formant and volume correction settings for this factory TODO: Need to rethink how we expose pitch shifter settings.
Static Public Member Functions
static HARMONIXDSP_API void AddClient (IFeatureClient *Client, float SampleRate)
Statically adds a client to the factory module (if it hasn't already beed added) lets each instance of the factory module know about the client allowing them to do any necessary setup.
static HARMONIXDSP_API IStretcherAndPitchShifterFactory * FindBestFactory (const FTimeStretchConfig &InConfig)
Finds a factory with available pitch shifters.
static HARMONIXDSP_API IStretcherAndPitchShifterFactory * FindFactory (const FName InFactoryName)
Returns the instance of the factory with the registered name null if a factory has not been registerred with the given name.
static HARMONIXDSP_API TArray< IStretcherAndPitchShifterFactory * > GetAllRegisteredFactories ()
Gets all registered factory instances.
static HARMONIXDSP_API TArray< FName > GetAllRegisteredFactoryNames ()
Gets all registered factory names.
static HARMONIXDSP_API FName GetModularFeatureName ()
Get the name of all StretcherAndPitchShifter factories in the Modular Features registry.
static HARMONIXDSP_API int32 GetNumClients ()
static HARMONIXDSP_API bool HasClient (IFeatureClient *Client)
static HARMONIXDSP_API void RemoveClient (IFeatureClient *Client)
Statically removes a client from the factory module (if it hasn't already been removed) lets each instance know about the removed client allowing them to do any shut down if necessary.
Protected Member Functions
HARMONIXDSP_API IStretcherAndPitchShifterFactory ()
virtual void OnClientAdded (IFeatureClient *Client, float SampleRate)=0
Override this method to do custom setup when a client is added Clients are added statically and managed by the IStretcherAndPitchShifterFactory.
virtual void OnClientRemoved (IFeatureClient *Client)=0
Override this method to do custom teardown when a client is removed Clients are added statically and managed by the IStretcherAndPitchShifterFactory.
Static Private Member Functions
static HARMONIXDSP_API void ResetMemoryUsageBytes (uint64 MemoryUsageBytes)
Static Private Attributes
static HARMONIXDSP_API FCriticalSection ClientLock
static HARMONIXDSP_API TArray< IFeatureClient * > Clients
static HARMONIXDSP_API FAudioStreamCacheMemoryHandle MemoryHandle
static HARMONIXDSP_API size_t TotalMemoryUsed
Detailed Description
Definition at line 16 of file StretcherAndPitchShifterFactory.h.
Constructor & Destructor Documentation
IStretcherAndPitchShifterFactory()
HARMONIXDSP_API IStretcherAndPitchShifterFactory::IStretcherAndPitchShifterFactory () protected
References UE_API.
Referenced by FindBestFactory(), and FindFactory().
~IStretcherAndPitchShifterFactory()
virtual HARMONIXDSP_API IStretcherAndPitchShifterFactory::~IStretcherAndPitchShifterFactory () virtual
References UE_API.
Member Function Documentation
AddClient()
HARMONIXDSP_API void IStretcherAndPitchShifterFactory::AddClient (IFeatureClient * Client, float SampleRate) static
Statically adds a client to the factory module (if it hasn't already beed added) lets each instance of the factory module know about the client allowing them to do any necessary setup.
References Client, and UE_API.
FindBestFactory()
HARMONIXDSP_API IStretcherAndPitchShifterFactory * IStretcherAndPitchShifterFactory::FindBestFactory (const FTimeStretchConfig & InConfig) static
Finds a factory with available pitch shifters.
Returns
IStretcherAndPitchShifterFactory* instance
References IStretcherAndPitchShifterFactory(), and UE_API.
FindFactory()
HARMONIXDSP_API IStretcherAndPitchShifterFactory * IStretcherAndPitchShifterFactory::FindFactory (const FName InFactoryName) static
Returns the instance of the factory with the registered name null if a factory has not been registerred with the given name.
Returns
IStretcherAndPitchShifterFactory* instance
References IStretcherAndPitchShifterFactory(), and UE_API.
GetAllRegisteredFactories()
HARMONIXDSP_API TArray< IStretcherAndPitchShifterFactory * > IStretcherAndPitchShifterFactory::GetAllRegisteredFactories () static
Gets all registered factory instances.
Returns
Array of all factories.
References UE_API.
GetAllRegisteredFactoryNames()
HARMONIXDSP_API TArray< FName > IStretcherAndPitchShifterFactory::GetAllRegisteredFactoryNames () static
Gets all registered factory names.
Returns
Array of all factory names
References UE_API.
GetFactoryNames()
virtual const TArray< FName > & IStretcherAndPitchShifterFactory::GetFactoryNames () const pure virtual
Gets the name of this factory type.
This will uniquely identity itself, so it can be found by the FindFactory call below
Returns
Name of factory
GetFreePitchShifter()
virtual TSharedPtr< IStretcherAndPitchShifter, ESPMode::ThreadSafe > IStretcherAndPitchShifterFactory::GetFreePitchShifter (const FTimeStretchConfig & InConfig) pure virtual
The factory has the ability to pool pitch shifters.
Returns
Instance of an available pitch shifter
GetMemoryUsedByPool()
virtual size_t IStretcherAndPitchShifterFactory::GetMemoryUsedByPool () const pure virtual
Should return number of bytes used by all of the shifters in the pool.
GetModularFeatureName()
HARMONIXDSP_API FName IStretcherAndPitchShifterFactory::GetModularFeatureName () static
Get the name of all StretcherAndPitchShifter factories in the Modular Features registry.
Returns
"StretcherAndPitchShifter Factory"
References UE_API.
GetNumClients()
HARMONIXDSP_API int32 IStretcherAndPitchShifterFactory::GetNumClients () static
Returns
the number of unique clients added to the factory module
References UE_API.
HasClient()
HARMONIXDSP_API bool IStretcherAndPitchShifterFactory::HasClient (IFeatureClient * Client) static
Returns
whether the in "Client" has been added as a client to this factory module
References Client, and UE_API.
HasFreePitchShifters()
virtual bool IStretcherAndPitchShifterFactory::HasFreePitchShifters (const FTimeStretchConfig & InConfig) const pure virtual
The factory has the ability to pool pitch shifters.
This let's you know if GetFreePitchShifter will return a valid pitch shifter
OnClientAdded()
virtual void IStretcherAndPitchShifterFactory::OnClientAdded (IFeatureClient * Client, float SampleRate) protected pure virtual
Override this method to do custom setup when a client is added Clients are added statically and managed by the IStretcherAndPitchShifterFactory.
References Client.
OnClientRemoved()
virtual void IStretcherAndPitchShifterFactory::OnClientRemoved (IFeatureClient * Client) protected pure virtual
Override this method to do custom teardown when a client is removed Clients are added statically and managed by the IStretcherAndPitchShifterFactory.
References Client.
ReleasePitchShifter()
virtual void IStretcherAndPitchShifterFactory::ReleasePitchShifter (TSharedPtr< IStretcherAndPitchShifter, ESPMode::ThreadSafe >) pure virtual
The factory has the ability to pool pitch shifters.
Make sure to call this method with a pitch shifter you retrieved from GetFreePitchShifter
RemoveClient()
HARMONIXDSP_API void IStretcherAndPitchShifterFactory::RemoveClient (IFeatureClient * Client) static
Statically removes a client from the factory module (if it hasn't already been removed) lets each instance know about the removed client allowing them to do any shut down if necessary.
References Client, and UE_API.
ResetMemoryUsageBytes()
HARMONIXDSP_API void IStretcherAndPitchShifterFactory::ResetMemoryUsageBytes (uint64 MemoryUsageBytes) static private
References UE_API.
SetFormantVolumeCorrection()
virtual void IStretcherAndPitchShifterFactory::SetFormantVolumeCorrection (float DBPerHalfStepUp, float DBPerHalfStepDown, float DBMaxUp, float DBMaxDown) inline virtual
Update the pitch shifters formant and volume correction settings for this factory TODO: Need to rethink how we expose pitch shifter settings.
Definition at line 36 of file StretcherAndPitchShifterFactory.h.
Field Documentation
ClientLock
HARMONIXDSP_API FCriticalSection IStretcherAndPitchShifterFactory::ClientLock static private
Definition at line 139 of file StretcherAndPitchShifterFactory.h.
Clients
HARMONIXDSP_API TArray<IFeatureClient*> IStretcherAndPitchShifterFactory::Clients static private
Definition at line 141 of file StretcherAndPitchShifterFactory.h.
MemoryHandle
HARMONIXDSP_API FAudioStreamCacheMemoryHandle IStretcherAndPitchShifterFactory::MemoryHandle static private
Definition at line 145 of file StretcherAndPitchShifterFactory.h.
TotalMemoryUsed
HARMONIXDSP_API size_t IStretcherAndPitchShifterFactory::TotalMemoryUsed static private
Definition at line 143 of file StretcherAndPitchShifterFactory.h.
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/Harmonix/Source/HarmonixDsp/Public/HarmonixDsp/StretcherAndPitchShifterFactory.h