Unreal Engine 5.6 C++ API: TScale2< T > Class Template Reference
TScale2< T > Class Template Reference
Represents a 2D non-uniform scale (to disambiguate from an FVector2D, which is used for translation)
#include "TransformCalculus2D.h"
Public Types
using FReal = T
using Vector2Type = UE::Math::TVector2<T>
Public Member Functions
TScale2 ()
Ctor.
template<typename ArgType>
TScale2 (const UE::Math::TVector2< ArgType > &InScale)
Ctor.
TScale2 (T InScale)
Ctor.
TScale2 (T InScaleX, T InScaleY)
Ctor.
TScale2 Concatenate (const TScale2 &RHS) const
Concatenate two scales.
const Vector2Type & GetVector () const
Access to the underlying FVector2D that stores the scale.
TScale2 Inverse () const
Invert the scale.
bool operator!= (const TScale2 &Other) const
Inequality.
bool operator== (const TScale2 &Other) const
Equality.
template<typename ArgType>
UE::Math::TVector2< ArgType > TransformPoint (const UE::Math::TVector2< ArgType > &Point) const
Transform 2D Point.
template<typename ArgType>
UE::Math::TVector2< ArgType > TransformVector (const UE::Math::TVector2< ArgType > &Vector) const
Transform 2D Vector.
Private Attributes
Vector2Type Scale
Underlying storage of the 2D scale.
Detailed Description
template<typename T>
class TScale2< T >
Represents a 2D non-uniform scale (to disambiguate from an FVector2D, which is used for translation)
Definition at line 113 of file TransformCalculus2D.h.
Member Typedef Documentation
FReal
template<typename T> using TScale2< T >::FReal = T
Definition at line 118 of file TransformCalculus2D.h.
Vector2Type
template<typename T> using TScale2< T >::Vector2Type = UE::Math::TVector2<T>
Definition at line 119 of file TransformCalculus2D.h.
Constructor & Destructor Documentation
TScale2() [1/4]
template<typename T> TScale2< T >::TScale2 () inline nodiscard
Ctor.
initialize to an identity scale, 1.0.
Definition at line 122 of file TransformCalculus2D.h.
Referenced by TScale2< float >::Concatenate(), and TScale2< float >::Inverse().
TScale2() [2/4]
template<typename T> TScale2< T >::TScale2 (T InScale) inline explicit nodiscard
Ctor.
initialize from a uniform scale.
Definition at line 124 of file TransformCalculus2D.h.
TScale2() [3/4]
template<typename T> TScale2< T >::TScale2 (T InScaleX, T InScaleY) inline explicit nodiscard
Ctor.
initialize from a non-uniform scale.
Definition at line 126 of file TransformCalculus2D.h.
TScale2() [4/4]
template<typename T> template<typename ArgType> TScale2< T >::TScale2 (const UE::Math::TVector2< ArgType > & InScale) inline explicit nodiscard
Ctor.
initialize from an FVector defining the 3D scale.
Definition at line 129 of file TransformCalculus2D.h.
Member Function Documentation
Concatenate()
template<typename T> TScale2 TScale2< T >::Concatenate (const TScale2< T > & RHS) const inline nodiscard
Concatenate two scales.
Definition at line 146 of file TransformCalculus2D.h.
GetVector()
template<typename T> const Vector2Type & TScale2< T >::GetVector () const inline nodiscard
Access to the underlying FVector2D that stores the scale.
Definition at line 169 of file TransformCalculus2D.h.
Referenced by TMatrix2x2< float >::GetScale().
Inverse()
template<typename T> TScale2 TScale2< T >::Inverse () const inline nodiscard
Invert the scale.
Definition at line 151 of file TransformCalculus2D.h.
operator!=()
template<typename T> bool TScale2< T >::operator!= (const TScale2< T > & Other) const inline nodiscard
Inequality.
Definition at line 163 of file TransformCalculus2D.h.
operator==()
template<typename T> bool TScale2< T >::operator== (const TScale2< T > & Other) const inline nodiscard
Equality.
Definition at line 157 of file TransformCalculus2D.h.
Referenced by TScale2< float >::operator!=().
TransformPoint()
template<typename T> template<typename ArgType> UE::Math::TVector2< ArgType > TScale2< T >::TransformPoint (const UE::Math::TVector2< ArgType > & Point) const inline nodiscard
Transform 2D Point.
Definition at line 133 of file TransformCalculus2D.h.
Referenced by TScale2< float >::TransformVector().
TransformVector()
template<typename T> template<typename ArgType> UE::Math::TVector2< ArgType > TScale2< T >::TransformVector (const UE::Math::TVector2< ArgType > & Vector) const inline nodiscard
Transform 2D Vector.
Definition at line 140 of file TransformCalculus2D.h.
Field Documentation
Scale
template<typename T> Vector2Type TScale2< T >::Scale private
Underlying storage of the 2D scale.
Definition at line 176 of file TransformCalculus2D.h.
Referenced by TScale2< float >::Concatenate().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Math/TransformCalculus2D.h