Unreal Engine 5.6 C++ API: SWidget Class Reference
SWidget Class Reference abstract
HOW TO DEPRECATE SLATE_ATTRIBUTES.
#include "SWidget.h"
Data Structures
struct TSlateAttribute
A SlateAttribute that is member variable of a SWidget.
struct TSlateAttribute< FText, EInvalidateWidgetReason::None >
struct TSlateAttribute< FText, InInvalidationReasonValue >
struct TSlateAttributeRef
A Reference to a TSlateAttribute.
struct TSlateAttributeRef< FText, EInvalidateWidgetReason::None >
struct TSlateAttributeRef< FText, InInvalidationReasonValue >
struct TSlateManagedAttribute
A SlateAttribute that is NOT a member variable of a SWidget.
struct TSlateManagedAttribute< FText, EInvalidateWidgetReason::None >
struct TSlateManagedAttribute< FText, InInvalidationReasonValue >
Public Member Functions
template<typename MetaDataType>
void AddMetadata (const TSharedRef< MetaDataType > &AddMe)
Add metadata to this widget.
virtual const FSlateInvalidationRoot * Advanced_AsInvalidationRoot () const
FORCEINLINE TSharedPtr< SWidget > Advanced_GetPaintParentWidget () const
virtual bool Advanced_IsInvalidationRoot () const
virtual bool Advanced_IsWindow () const
Is this widget derivative of SWindow.
void ArrangeChildren (const FGeometry &AllottedGeometry, FArrangedChildren &ArrangedChildren, bool bUpdateAttributes=false) const
Non-virtual entry point for arrange children.
void AssignParentWidget (TSharedPtr< SWidget > InParent)
FORCEINLINE void CacheVolatility ()
Recalculates volatility of the widget and caches the result.
FSlateRect CalculateCullingAndClippingRules (const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, bool &bClipToBounds, bool &bAlwaysClip, bool &bIntersectClipBounds) const
Calculates what if any clipping state changes need to happen when drawing this widget.
bool ConditionallyDetatchParentWidget (SWidget *InExpectedParent)
void EnableToolTipForceField (const bool bEnableForceField)
Sets whether this widget is a "tool tip force field".
FORCEINLINE void ForceVolatile (bool bForce)
Should this widget always appear as volatile for any layout caching host widget.
virtual FChildren * GetAllChildren ()
Returns the children (if any) of this widget that are used by the invalidation system.
template<typename MetaDataType>
TArray< TSharedRef< MetaDataType > > GetAllMetaData () const
Get all metadata of the type provided.
const FGeometry & GetCachedGeometry () const
bool GetCanTick () const
virtual FChildren * GetChildren ()=0
Returns the useful children (if any) of this widget.
FORCEINLINE EWidgetClipping GetClipping () const
FName GetCreatedInLocation () const
FORCEINLINE FMargin GetCullingBoundsExtension () const
const TOptional< FSlateClippingState > & GetCurrentClippingState () const
Returns the clipping state to clip this widget against its parent.
UE::Slate::FDeprecateVector2DResult GetDesiredSize () const
virtual FSlateColor GetDisabledForegroundColor () const
EFlowDirectionPreference GetFlowDirectionPreference () const
Gets the desired flow direction for the layout.
virtual FSlateColor GetForegroundColor () const
template<typename MetaDataType>
TSharedPtr< MetaDataType > GetMetaData () const
Get the metadata of the type provided.
const FGeometry & GetPaintSpaceGeometry () const
Gets the last geometry used to Tick the widget.
FORCEINLINE TSharedPtr< SWidget > GetParentWidget () const
const FSlateWidgetPersistentState & GetPersistentState () const
FORCEINLINE EWidgetPixelSnapping GetPixelSnapping () const
const FWidgetProxyHandle GetProxyHandle () const
virtual FString GetReadableLocation () const
virtual float GetRelativeLayoutScale (const int32 ChildIndex, float LayoutScaleMultiplier) const
What is the Child's scale relative to this widget.
FORCEINLINE float GetRenderOpacity () const
FORCEINLINE const TOptional< FSlateRenderTransform > & GetRenderTransform () const
FORCEINLINE UE::Slate::FDeprecateVector2DResult GetRenderTransformPivot () const
FORCEINLINE UE::Slate::FDeprecateVector2DResult GetRenderTransformPivotWithRespectToFlowDirection () const
FORCEINLINE TOptional< FSlateRenderTransform > GetRenderTransformWithRespectToFlowDirection () const
FORCEINLINE TStatId GetStatID (bool bForDeferredUse=false) const
virtual FName GetTag () const
const FGeometry & GetTickSpaceGeometry () const
Gets the last geometry used to Tick the widget.
virtual TSharedPtr< IToolTip > GetToolTip ()
FName GetType () const
FString GetTypeAsString () const
FORCEINLINE EVisibility GetVisibility () const
virtual EWindowZone::Type GetWindowZoneOverride () const
Called when the mouse is moved over the widget's window, to determine if we should report whether OS-specific features should be active at this location (such as a title bar grip, system menu, etc.) Usually you should not need to override this function.
bool HasActiveTimers () const
Does this widget have any active timers?
bool HasAnyUpdateFlags (EWidgetUpdateFlags FlagsToCheck) const
TOptional< EFocusCause > HasAnyUserFocus () const
Gets whether or not any users have this widget focused, and if so the type of focus (first one found).
bool HasAnyUserFocusOrFocusedDescendants () const
bool HasFocusedDescendants () const
virtual bool HasKeyboardFocus () const
Checks to see if this widget currently has the keyboard focus.
bool HasMouseCapture () const
Checks to see if this widget is the current mouse captor.
bool HasMouseCaptureByUser (int32 UserIndex, TOptional< int32 > PointerIndex=TOptional< int32 >()) const
Checks to see if this widget has mouse capture from the provided user.
bool HasRegisteredSlateAttribute () const
bool HasToolTipForceField () const
TOptional< EFocusCause > HasUserFocus (int32 UserIndex) const
Gets whether or not the specified users has this widget focused, and if so the type of focus.
bool HasUserFocusedDescendants (int32 UserIndex) const
Gets whether or not the specified users has this widget or any descendant focused.
void Invalidate (EInvalidateWidgetReason InvalidateReason)
Invalidates the widget from the view of a layout caching widget that may own this widget.
bool IsAttributesUpdatesEnabled () const
bool IsDirectlyHovered () const
FORCEINLINE bool IsEnabled () const
bool IsHovered () const
virtual bool IsInteractable () const
FORCEINLINE bool IsParentValid () const
FORCEINLINE bool IsVolatile () const
Whether or not a widget is volatile and will update every frame without being invalidated.
FORCEINLINE bool IsVolatileIndirectly () const
This widget is volatile because its parent or some ancestor is volatile.
void MarkPrepassAsDirty ()
In fast path, if the widget is mark, do a full Prepass on its next update to calculate it's desired size.
bool NeedsPrepass () const
virtual FReply OnAnalogValueChanged (const FGeometry &MyGeometry, const FAnalogInputEvent &InAnalogInputEvent)
Called when an analog value changes on a button that supports analog.
virtual FCursorReply OnCursorQuery (const FGeometry &MyGeometry, const FPointerEvent &CursorEvent) const
The system asks each widget under the mouse to provide a cursor.
virtual FReply OnDragDetected (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Called when Slate detects that a widget started to be dragged.
virtual void OnDragEnter (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called during drag and drop when the drag enters a widget.
virtual void OnDragLeave (const FDragDropEvent &DragDropEvent)
Called during drag and drop when the drag leaves a widget.
virtual FReply OnDragOver (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called during drag and drop when the the mouse is being dragged over a widget.
virtual FReply OnDrop (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called when the user is dropping something onto a widget; terminates drag and drop.
virtual void OnFinishedKeyInput ()
All the key (keyboard, gamepay, joystick, etc.) input from this frame has been routed.
virtual void OnFinishedPointerInput ()
All the pointer (mouse, touch, stylus, etc.) events from this frame have been routed.
virtual void OnFocusChanging (const FWeakWidgetPath &PreviousFocusPath, const FWidgetPath &NewWidgetPath, const FFocusEvent &InFocusEvent)
Called whenever a focus path is changing on all the widgets within the old and new focus paths.
virtual void OnFocusLost (const FFocusEvent &InFocusEvent)
Called when this widget loses focus.
virtual FReply OnFocusReceived (const FGeometry &MyGeometry, const FFocusEvent &InFocusEvent)
Called when focus is given to this widget.
virtual FReply OnKeyChar (const FGeometry &MyGeometry, const FCharacterEvent &InCharacterEvent)
Called after a character is entered while this widget has keyboard focus.
virtual FReply OnKeyDown (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
Called after a key is pressed when this widget has focus (this event bubbles if not handled)
virtual FReply OnKeyUp (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
Called after a key is released when this widget has focus.
virtual TOptional< TSharedRef< SWidget > > OnMapCursor (const FCursorReply &CursorReply) const
After OnCursorQuery has specified a cursor type the system asks each widget under the mouse to map that cursor to a widget.
virtual FReply OnMotionDetected (const FGeometry &MyGeometry, const FMotionEvent &InMotionEvent)
Called when motion is detected (controller or device) e.g.
virtual FReply OnMouseButtonDoubleClick (const FGeometry &InMyGeometry, const FPointerEvent &InMouseEvent)
Called when a mouse button is double clicked.
virtual FReply OnMouseButtonDown (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system calls this method to notify the widget that a mouse button was pressed within it.
virtual FReply OnMouseButtonUp (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system calls this method to notify the widget that a mouse button was release within it.
virtual void OnMouseCaptureLost (const FCaptureLostEvent &CaptureLostEvent)
Called when this widget had captured the mouse, but that capture has been revoked for some reason.
virtual void OnMouseEnter (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system will use this event to notify a widget that the cursor has entered it.
virtual void OnMouseLeave (const FPointerEvent &MouseEvent)
The system will use this event to notify a widget that the cursor has left it.
virtual FReply OnMouseMove (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system calls this method to notify the widget that a mouse moved within it.
virtual FReply OnMouseWheel (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Called when the mouse wheel is spun.
virtual FNavigationReply OnNavigation (const FGeometry &MyGeometry, const FNavigationEvent &InNavigationEvent)
Called when navigation is requested e.g.
virtual FReply OnPreviewKeyDown (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
Called after a key is pressed when this widget or a child of this widget has focus If a widget handles this event, OnKeyDown will not be passed to the focused widget.
virtual FReply OnPreviewMouseButtonDown (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Just like OnMouseButtonDown, but tunnels instead of bubbling.
virtual FPopupMethodReply OnQueryPopupMethod () const
Popups can manifest in a NEW OS WINDOW or via an OVERLAY in an existing window.
virtual TOptional< bool > OnQueryShowFocus (const EFocusCause InFocusCause) const
Called to determine if we should render the focus brush.
virtual void OnToolTipClosing ()
Called when a tooltip displayed from this widget is being closed.
virtual FReply OnTouchEnded (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is ended (finger lifted)
virtual FReply OnTouchFirstMove (const FGeometry &MyGeometry, const FPointerEvent &TouchEvent)
Called when a touchpad touch first moves after TouchStarted.
virtual FReply OnTouchForceChanged (const FGeometry &MyGeometry, const FPointerEvent &TouchEvent)
Called when a touchpad touch force changes.
virtual FReply OnTouchGesture (const FGeometry &MyGeometry, const FPointerEvent &GestureEvent)
Called when the user performs a gesture on trackpad.
virtual FReply OnTouchMoved (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is moved (finger moved)
virtual FReply OnTouchStarted (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is started (finger down)
virtual TSharedPtr< FPopupLayer > OnVisualizePopup (const TSharedRef< SWidget > &PopupContent)
Visualize a new pop-up if possible.
virtual bool OnVisualizeTooltip (const TSharedPtr< SWidget > &TooltipContent)
Called when Slate wants to visualize tooltip.
int32 Paint (const FPaintArgs &Args, const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, FSlateWindowElementList &OutDrawElements, int32 LayerId, const FWidgetStyle &InWidgetStyle, bool bParentEnabled) const
Called to tell a widget to paint itself (and it's children).
TSharedRef< FActiveTimerHandle > RegisterActiveTimer (float TickPeriod, FWidgetActiveTimerDelegate TickFunction)
Registers an "active timer" delegate that will execute at some regular interval.
template<typename MetaDataType>
int32 RemoveMetaData (const TSharedRef< MetaDataType > &RemoveMe)
Remove metadata to this widget.
void SetCanTick (bool bInCanTick)
void SetClipping (EWidgetClipping InClipping)
Sets the clipping to bounds rules for this widget.
FORCEINLINE void SetCullingBoundsExtension (const FMargin &InCullingBoundsExtension)
Sets an additional culling padding that is added to a widget to give more leeway when culling widgets.
void SetCursor (const TAttribute< TOptional< EMouseCursor::Type > > &InCursor)
Set the cursor that should appear when this widget is hovered.
void SetEnabled (TAttribute< bool > InEnabledState)
Sets the enabled state of this widget.
void SetFlowDirectionPreference (EFlowDirectionPreference InFlowDirectionPreference)
Sets how content should flow in this panel, based on the current culture.
void SetOnMouseButtonDown (FPointerEventHandler EventHandler)
See OnMouseButtonDown event.
void SetOnMouseButtonUp (FPointerEventHandler EventHandler)
See OnMouseButtonUp event.
void SetOnMouseDoubleClick (FPointerEventHandler EventHandler)
See OnMouseDoubleClick event.
void SetOnMouseEnter (FNoReplyPointerEventHandler EventHandler)
See OnMouseEnter event.
void SetOnMouseLeave (FSimpleNoReplyPointerEventHandler EventHandler)
See OnMouseLeave event.
void SetOnMouseMove (FPointerEventHandler EventHandler)
See OnMouseMove event.
void SetPixelSnapping (EWidgetPixelSnapping InPixelSnappingMethod)
Sets the pixel snapping method for this widget.
FORCEINLINE void SetRenderOpacity (float InRenderOpacity)
FORCEINLINE void SetRenderTransform (TAttribute< TOptional< FSlateRenderTransform > > InTransform)
FORCEINLINE void SetRenderTransformPivot (TAttribute< FVector2D > InTransformPivot)
FORCEINLINE void SetTag (FName InTag)
void SetToolTip (const TAttribute< TSharedPtr< IToolTip > > &InToolTip)
Set the tool tip that should appear when this widget is hovered.
void SetToolTipText (const FText &InToolTipText)
Set the tool tip that should appear when this widget is hovered.
void SetToolTipText (const TAttribute< FText > &ToolTipText)
Set the tool tip that should appear when this widget is hovered.
virtual void SetVisibility (TAttribute< EVisibility > InVisibility)
FORCEINLINE bool ShouldInvalidatePrepassDueToVolatility ()
void SlatePrepass ()
DEPRECATED version of SlatePrepass that assumes no scaling beyond AppScale.
void SlatePrepass (float InLayoutScaleMultiplier)
Descends to leaf-most widgets in the hierarchy and gathers desired sizes on the way up.
virtual bool SupportsKeyboardFocus () const
Checks to see if this widget supports keyboard focus.
virtual void Tick (const FGeometry &AllottedGeometry, const double InCurrentTime, const float InDeltaTime)
Ticks this widget with Geometry.
virtual FString ToString () const
virtual TOptional< FVirtualPointerPosition > TranslateMouseCoordinateForCustomHitTestChild (const SWidget &ChildWidget, const FGeometry &MyGeometry, const FVector2D ScreenSpaceMouseCoordinate, const FVector2D LastScreenSpaceMouseCoordinate) const
void UnRegisterActiveTimer (const TSharedRef< FActiveTimerHandle > &ActiveTimerHandle)
Unregisters an active timer handle.
virtual bool ValidatePathToChild (SWidget *InChild)
Public Member Functions inherited from FSlateControlledConstruction
FSlateControlledConstruction ()=default
virtual ~FSlateControlledConstruction ()=default
virtual const FSlateWidgetClassData & GetWidgetClass () const =0
void operator delete (void *mem)
Public Member Functions inherited from TSharedFromThis< SWidget >
TSharedRef< SWidget, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< SWidget, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Protected Member Functions
SWidget ()
Hidden default constructor.
virtual ~SWidget ()
Dtor ensures that active timer handles are UnRegistered with the SlateApplication.
FORCEINLINE bool Advanced_InvalidateVolatility ()
Recalculates and caches volatility and returns 'true' if the volatility changed.
virtual void CacheDesiredSize (float InLayoutScaleMultiplier)
The system calls this method.
virtual FVector2D ComputeDesiredSize (float LayoutScaleMultiplier) const =0
Compute the ideal size necessary to display this widget.
EFlowDirection ComputeFlowDirection () const
Establishes a new flow direction potentially, if this widget has a particular preference for it and all its children.
virtual bool ComputeVolatility () const
Recomputes the volatility of the widget.
virtual bool CustomPrepass (float LayoutScaleMultiplier)
bool FindChildGeometries (const FGeometry &MyGeometry, const TSet< TSharedRef< SWidget > > &WidgetsToFind, TMap< TSharedRef< SWidget >, FArrangedWidget > &OutResult) const
Find the geometry of a descendant widget.
void FindChildGeometries_Helper (const FGeometry &MyGeometry, const TSet< TSharedRef< SWidget > > &WidgetsToFind, TMap< TSharedRef< SWidget >, FArrangedWidget > &OutResult) const
Actual implementation of FindChildGeometries.
FGeometry FindChildGeometry (const FGeometry &MyGeometry, TSharedRef< SWidget > WidgetToFind) const
Find the geometry of a descendant widget.
virtual TOptional< EMouseCursor::Type > GetCursor () const
The cursor to show when the mouse is hovering over this widget.
TSlateAttributeRef< bool > GetEnabledStateAttribute () const
virtual const FSlateBrush * GetFocusBrush () const
TSlateAttributeRef< bool > GetHoveredAttribute () const
float GetPrepassLayoutScaleMultiplier () const
TSlateAttributeRef< TOptional< FSlateRenderTransform > > GetRenderTransformAttribute () const
TSlateAttributeRef< FVector2D > GetRenderTransformPivotAttribute () const
TSlateAttributeRef< EVisibility > GetVisibilityAttribute () const
void InvalidateChildRemovedFromTree (SWidget &Child)
Called when a child is removed from the tree parent's widget tree either by removing it from a slot.
FORCEINLINE bool IsChildWidgetCulled (const FSlateRect &, const FArrangedWidget &) const
bool IsConstructed () const
Is the widget construction completed (did we called and returned from the Construct() function)
virtual void OnClippingChanged ()
Called when clipping is changed.
void Prepass_ChildLoop (float InLayoutScaleMultiplier, FChildren *MyChildren)
template<typename TargetValueType, typename SourceValueType>
bool SetAttribute (TAttribute< TargetValueType > &TargetValue, const TAttribute< SourceValueType > &SourceValue, EInvalidateWidgetReason BaseInvalidationReason)
Performs the attribute assignment and invalidates the widget minimally based on what actually changed.
void SetDebugInfo (const ANSICHAR *InType, const ANSICHAR *InFile, int32 OnLine, size_t InAllocSize)
Used by Slate to set the runtime debug info about this widget.
void SetHover (TAttribute< bool > InHovered)
Set the hover state.
void SetVolatilePrepass (bool bVolatile)
bool ShouldBeEnabled (bool InParentEnabled) const
Determines if this widget should be enabled.
void SWidgetConstruct (const FSlateBaseNamedArgs &Args)
Construct a SWidget based on initial parameters.
Protected Member Functions inherited from TSharedFromThis< SWidget >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions
static TAttribute< EVisibility > AccessWidgetVisibilityAttribute (const TSharedRef< SWidget > &Widget)
Protected static helper to allow widgets to access the visibility attribute of other widgets directly.
static int32 FindChildUnderMouse (const FArrangedChildren &Children, const FPointerEvent &MouseEvent)
static int32 FindChildUnderPosition (const FArrangedChildren &Children, const UE::Slate::FDeprecateVector2DParameter &ArrangedSpacePosition)
Static Protected Member Functions inherited from TSharedFromThis< SWidget >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Protected Attributes
uint8 bCanHaveChildren: 1
Can the widget ever support children?
uint8 bCanSupportFocus: 1
Can the widget ever support keyboard focus.
uint8 bClippingProxy: 1
Some widgets might be a complex hierarchy of child widgets you never see.
uint8 bHasCustomPrepass: 1
uint8 bHasRelativeLayoutScale: 1
uint8 bVolatilityAlwaysInvalidatesPrepass: 1
if this widget should always invalidate the prepass step when volatile
EWidgetClipping Clipping
Set to true if all content of the widget should clip to the bounds of this widget.
FMargin CullingBoundsExtension
Can be used to enlarge the culling bounds of this widget (pre-intersection), this can be useful if you've got children that you know are using rendering transforms to render outside their standard bounds, if that happens it's possible the parent might be culled before the descendant widget is entirely off screen.
EWidgetPixelSnapping PixelSnappingMethod
When set to EPixelSnappingMethod::SnapToPixel, the widget is drawn at the nearest pixel.
float RenderOpacity
The opacity of the widget.
Private Member Functions
void AddMetadataInternal (const TSharedRef< ISlateMetaData > &AddMe)
void AddUpdateFlags (EWidgetUpdateFlags FlagsToAdd)
void ExecuteActiveTimers (double CurrentTime, float DeltaTime)
Iterates over the active timer handles on the widget and executes them if their interval has elapsed.
virtual void OnArrangeChildren (const FGeometry &AllottedGeometry, FArrangedChildren &ArrangedChildren) const =0
Compute the Geometry of all the children and add populate the ArrangedChildren list with their values.
virtual int32 OnPaint (const FPaintArgs &Args, const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, FSlateWindowElementList &OutDrawElements, int32 LayerId, const FWidgetStyle &InWidgetStyle, bool bParentEnabled) const =0
The widget should respond by populating the OutDrawElements array with FDrawElements that represent it and any of its children.
void Prepass_Internal (float LayoutScaleMultiplier)
template<typename MetaDataType>
int32 RemoveAllMetaData ()
template<typename MetaDataType>
bool RemoveMetaData ()
void RemoveUpdateFlags (EWidgetUpdateFlags FlagsToRemove)
void SetDesiredSize (const FVector2D &InDesiredSize)
Explicitly set the desired size.
void SetFastPathProxyHandle (const FWidgetProxyHandle &Handle)
void SetFastPathProxyHandle (const FWidgetProxyHandle &Handle, FSlateInvalidationWidgetVisibility Visibility, bool bParentVolatile)
void SetFastPathSortOrder (const FSlateInvalidationWidgetSortOrder SortOrder)
SLATE_DECLARE_WIDGET_API (SWidget, FSlateControlledConstruction, 1) friend class FWidgetProxy
void UpdateFastPathVisibility (FSlateInvalidationWidgetVisibility ParentVisibility, FHittestGrid *ParentHittestGrid)
void UpdateFastPathVolatility (bool bParentVolatile)
void UpdateFastPathWidgetRemoved (FHittestGrid *ParentHittestGrid)
void UpdateWidgetProxy (int32 NewLayerId, FSlateCachedElementsHandle &CacheHandle)
Private Attributes
uint8 bCachedVolatile: 1
The last cached volatility of this widget.
uint8 bDesiredSizeSet: 1
Is the DesiredSize set.
uint8 bEnabledAttributesUpdate: 1
Are bound Slate Attributes will be updated once per frame.
uint8 bForceVolatile: 1
Should we be forcing this widget to be volatile at all times and redrawn every frame?
uint8 bHasActiveTimers: 1
Is there at least one ActiveTimer currently registered.
uint8 bHasRegisteredSlateAttribute: 1
Is there at least one SlateAttribute currently registered.
uint8 bInheritedVolatility: 1
If we're owned by a volatile widget, we need inherit that volatility and use as part of our volatility, but don't cache it.
uint8 bIsDeclarativeSyntaxConstructionCompleted: 1
The SNew or SAssignedNew construction is completed.
uint8 bIsHoveredAttributeSet: 1
Is the attribute IsHovered is set?
uint8 bNeedsPrepass: 1
Are we currently updating the desired size?
uint8 bPrepassLayoutScaleMultiplierSet: 1
Is the PrepassLayoutScaleMultiplier set.
uint8 bToolTipForceFieldEnabled: 1
Whether this widget is a "tool tip force field".
FName CreatedInLocation
Full file path (and line) in which this widget was created.
FVector2f DesiredSize
Stores the ideal size this widget wants to be.
TSlateAttribute< bool > EnabledStateAttribute
Whether or not this widget is enabled.
FWidgetProxyHandle FastPathProxyHandle
Handle to the proxy when on the fast path.
EFlowDirectionPreference FlowDirectionPreference
Flow direction preference.
TSlateAttribute< bool > HoveredAttribute
Whether or not this widget is hovered.
TArray< TSharedRef< ISlateMetaData > > MetaData
Metadata associated with this widget.
TWeakPtr< SWidget > ParentWidgetPtr
Pointer to this widgets parent widget.
FSlateWidgetPersistentState PersistentState
float PrepassLayoutScaleMultiplierValue
TSlateAttribute< TOptional< FSlateRenderTransform > > RenderTransformAttribute
Render transform of this widget.
TSlateAttribute< FVector2D > RenderTransformPivotAttribute
Render transform pivot of this widget (in normalized local space)
FName Tag
Tag for this widget.
FName TypeOfWidget
Debugging information on the type of widget we're creating for the Widget Reflector.
EWidgetUpdateFlags UpdateFlags
The different updates this widget needs next frame.
TSlateAttribute< EVisibility > VisibilityAttribute
Is this widget visible, hidden or collapsed.
Friends
class FSlateAttributeMetaData
struct FSlateCachedElementList
class FSlateInvalidationRoot
class FSlateInvalidationWidgetList
class FSlateTrace
class FSlateWindowElementList
class SWindow
template<class WidgetType, typename RequiredArgsPayloadType>
struct TSlateDecl
Additional Inherited Members
Static Public Member Functions inherited from FSlateControlledConstruction
static const FSlateWidgetClassData & StaticWidgetClass ()
Detailed Description
HOW TO DEPRECATE SLATE_ATTRIBUTES.
SLATE_ATTRIBUTE(ECheckBoxState, IsChecked)
UE_DEPRECATED(4.xx, "Please use IsChecked(TAttribute<ECheckBoxState>)") FArguments& IsChecked(bool InIsChecked) { _IsChecked = InIsChecked ? ECheckBoxState::Checked : ECheckBoxState::Unchecked; return Me(); }
// This version would prevent ambiguous conversions. FArguments& IsChecked(ECheckBoxState InIsChecked) { _IsChecked = InIsChecked; return Me(); } Abstract base class for Slate widgets.
STOP. DO NOT INHERIT DIRECTLY FROM WIDGET!
Inheritance: Widget is not meant to be directly inherited. Instead consider inheriting from LeafWidget or Panel, which represent intended use cases and provide a succinct set of methods which to override.
SWidget is the base class for all interactive Slate entities. SWidget's public interface describes everything that a Widget can do and is fairly complex as a result.
Events: Events in Slate are implemented as virtual functions that the Slate system will call on a Widget in order to notify the Widget about an important occurrence (e.g. a key press) or querying the Widget regarding some information (e.g. what mouse cursor should be displayed).
Widget provides a default implementation for most events; the default implementation does nothing and does not handle the event.
Some events are able to reply to the system by returning an FReply, FCursorReply, or similar object.
Definition at line 153 of file SWidget.h.
Constructor & Destructor Documentation
SWidget()
SWidget::SWidget () protected
Hidden default constructor.
Use SNew(WidgetClassName) to instantiate new widgets.
See also
SNew
Referenced by SRigVMActionMenu::~SRigVMActionMenu(), SMultiBoxWidget::AddElement(), SErrorHint::AsWidget(), SErrorText::AsWidget(), SToolTip::AsWidget(), UE::Sequencer::STrackAreaLaneView::AsWidget(), UE::Insights::SFilterConfiguratorRow::AvailableFilterOperators_OnGenerateWidget(), UE::Insights::SFilterConfiguratorRow::AvailableFilters_OnGenerateWidget(), SPrivateAssetsDialog::BuildAssetViewForReferencerAssets(), SDeleteAssetsDialog::BuildCantUseReplaceReferencesWidget(), SDeleteAssetsDialog::BuildDeleteDialog(), SDeleteAssetsDialog::BuildForceDeleteWidget(), SReferenceTree::BuildMenuWidget(), SPrivateAssetsDialog::BuildPrivatizeDialog(), SDeleteAssetsDialog::BuildProgressDialog(), SPrivateAssetsDialog::BuildProgressDialog(), SDeleteAssetsDialog::BuildReplaceReferencesWidget(), ConditionallyDetatchParentWidget(), STabDrawer::Construct(), SSequencerFilter::ConstructBasicFilterWidget(), UE::Sequencer::SOutlinerViewRow::ConstructChildren(), SSequencerFilter::ConstructDefaultFilterWidget(), UE::Insights::STableTreeViewRow::CreateCellWidget(), SRigVMEditorSelectedDebugObjectWidget::CreateDebugObjectItemWidget(), SRigVMVariantWidget::CreateDefaultVariantRefContextMenu(), SRigVMVariantWidget::CreateDefaultVariantRefRow(), SGraphPaletteItem::CreateIconWidget(), SGraphPaletteItem::CreateIconWidget(), SDesignerView::CreateOverlayUI(), SReferenceSectionSelectionWidget::CreateSectionListWidgetMenu(), SBoneSelectionWidget::CreateSkeletonWidgetMenu(), SDeleteAssetsDialog::CreateThumbnailWidget(), SGraphActionMenu::DECLARE_DELEGATE_RetVal_TwoParams(), SBlueprintDiff::DefaultEmptyPanel(), SDetailsDiff::DefaultEmptyPanel(), STransformViewportToolBar::FillCameraSpeedMenu(), STransformViewportToolBar::FillLayer2DSnapMenu(), STransformViewportToolBar::FillLocationGridSnapMenu(), STransformViewportToolBar::FillRotationGridSnapMenu(), STransformViewportToolBar::FillScaleGridSnapMenu(), UE::Insights::SFilterConfiguratorRow::FilterGroupOperators_OnGenerateWidget(), STransformViewportToolBar::GenerateSurfaceSnappingMenu(), SEditorViewportViewMenu::GenerateViewMenuContent(), UE::Insights::SFilterConfiguratorRow::GenerateWidgetForColumn(), UE::Insights::STableTreeViewCell::GenerateWidgetForColumn(), UE::Insights::STableTreeViewRow::GenerateWidgetForColumn(), UE::SequenceNavigator::SNavigationToolTreeRow::GenerateWidgetForColumn(), UE::Sequencer::SOutlinerViewRow::GenerateWidgetForColumn(), UE::Insights::STableTreeViewCell::GenerateWidgetForNameColumn(), UE::Insights::STableTreeViewCell::GenerateWidgetForTableColumn(), SWidgetSwitcher::GetActiveWidget(), SGraphPanel::GetAllPins(), SSplitter2x2::GetBottomLeftContent(), SSplitter2x2::GetBottomRightContent(), SWeakWidget::GetChildWidget(), SBorder::GetContent(), SDockTab::GetContent(), SMultiBoxWidget::GetCustomizationVisibility(), SBoneTreeMenu::GetFilterTextWidget(), SDockTab::GetLeftContent(), SCommonAnimatedSwitcher::GetPendingActiveWidget(), SGraphPin::GetPinImageWidget(), SSequencerFilter::GetRightClickMenuContent(), SDockTab::GetRightContent(), SDockTab::GetTitleBarRightContent(), SSplitter2x2::GetTopLeftContent(), SSplitter2x2::GetTopRightContent(), InvalidateChildRemovedFromTree(), SContentReference::MakeAssetPickerMenu(), SRigVMGraphFunctionBulkEditWidget::MakeAssetViewForReferencedAssets(), SDeleteAssetsDialog::MakeAssetViewForReferencerAssets(), SScalabilitySettings::MakeAutoButtonWidget(), SScalabilitySettings::MakeButtonWidget(), SDeleteAssetsDialog::MakeConsolidationAssetPicker(), SFixedSampledSequenceRuler::MakeContextMenu(), SScalabilitySettings::MakeDefaultButtonWidget(), SScalabilitySettings::MakeHeaderButtonWidget(), SNameComboBox::MakeItemWidget(), STextComboBox::MakeItemWidget(), STextComboPopup::MakeItemWidget(), SOverridePropertiesWidget::MakeOverrideWidget(), STransformViewportToolBar::MakeSurfaceSnappingButton(), STransformViewportToolBar::MakeTransformToolBar(), SBasePoseViewport::MakeViewportToolbar(), SRigVMVariantTagWidget::OnBuildAddTagMenuContent(), SRigVMFindReferences::OnContextMenuOpening(), SDataflowSimulationPanel::OnCreatePreviewPlaybackModeWidget(), SResetToDefaultMenu::OnGenerateResetToDefaultMenuContent(), SDeleteAssetsDialog::OnGetAssetContextMenu(), SRigVMGraphFunctionBulkEditWidget::OnGetAssetContextMenu(), SToolBarComboButtonBlock::OnGetMenuContent(), SToolBarStackButtonBlock::OnGetMenuContent(), STabDrawer::OnGlobalFocusChanging(), SKismetDebugTreeView::OnMakeContextMenu(), SFacesOutliner::OnOpenContextMenu(), STransformOutliner::OnOpenContextMenu(), SVerticesOutliner::OnOpenContextMenu(), SGraphPanel::OnSummonContextMenu(), SRigVMVariantWidget::OnVariantRefTreeContextMenu(), SVirtualWindow::OnVisualizeTooltip(), SCanvas::RemoveSlot(), SConstraintCanvas::RemoveSlot(), SOverlay::RemoveSlot(), SRadialBox::RemoveSlot(), SResponsiveGridPanel::RemoveSlot(), SScrollBox::RemoveSlot(), SSplitter::RemoveSlot(), SUniformGridPanel::RemoveSlot(), SSplitter2x2::SetBottomLeftContent(), SSplitter2x2::SetBottomRightContent(), SBackgroundBlur::SetContent(), SBorder::SetContent(), SBox::SetContent(), SDockTab::SetContent(), SDPIScaler::SetContent(), SScaleBox::SetContent(), SScissorRectBox::SetContent(), SWeakWidget::SetContent(), SWindowTitleBarArea::SetContent(), SZoomPan::SetContent(), SDockTab::SetLeftContent(), SGraphPin::SetPinImageWidget(), SDockTab::SetRightContent(), SDockTab::SetTitleBarRightContent(), SSplitter2x2::SetTopLeftContent(), SSplitter2x2::SetTopRightContent(), SGraphEditor::SLATE_ARGUMENT(), SGraphPreviewer::SLATE_ARGUMENT(), SLoadGuard::SLATE_ARGUMENT(), SRigVMBulkEditWidget::SLATE_ARGUMENT(), SRigVMBulkEditWidget::SLATE_ARGUMENT(), SSubMenuHandler::SLATE_ARGUMENT(), SWindowTitleBar::SLATE_ATTRIBUTE(), SCompoundWidget::SLATE_DECLARE_WIDGET_API(), SLATE_DECLARE_WIDGET_API(), SRigVMBulkEditWidget::SLATE_EVENT(), SGraphPanel::SummonContextMenu(), SViewport::TranslateMouseCoordinateForCustomHitTestChild(), TranslateMouseCoordinateForCustomHitTestChild(), ValidatePathToChild(), and SWidgetSwitcher::ValidatePathToChild().
~SWidget()
virtual SWidget::~SWidget () protected virtual
Dtor ensures that active timer handles are UnRegistered with the SlateApplication.
Member Function Documentation
AccessWidgetVisibilityAttribute()
TAttribute< EVisibility > SWidget::AccessWidgetVisibilityAttribute (const TSharedRef< SWidget > & Widget) inline static protected
Protected static helper to allow widgets to access the visibility attribute of other widgets directly.
Parameters
Widget The widget to get the visibility attribute of
Definition at line 1588 of file SWidget.h.
References TSharedRef< ObjectType, InMode >::Get().
AddMetadata()
template<typename MetaDataType> void SWidget::AddMetadata (const TSharedRef< MetaDataType > & AddMe) inline
Add metadata to this widget.
Parameters
AddMe the metadata to add to the widget.
Definition at line 1366 of file SWidget.h.
References AddMetadataInternal().
Referenced by STileView< ItemType >::SLATE_END_ARGS(), SListView< TSharedPtr< FString > >::SLATE_EVENT(), and STreeView< FRigVMSearchResult >::SLATE_EVENT().
AddMetadataInternal()
void SWidget::AddMetadataInternal (const TSharedRef< ISlateMetaData > & AddMe) private
Referenced by AddMetadata().
AddUpdateFlags()
void SWidget::AddUpdateFlags (EWidgetUpdateFlags FlagsToAdd) inline private
Definition at line 748 of file SWidget.h.
References FastPathProxyHandle, and UpdateFlags.
Referenced by SetCanTick(), and SetVolatilePrepass().
Advanced_AsInvalidationRoot()
virtual const FSlateInvalidationRoot * SWidget::Advanced_AsInvalidationRoot () const inline virtual
Reimplemented in SInvalidationPanel, and SWindow.
Definition at line 1508 of file SWidget.h.
References FSlateInvalidationRoot.
Advanced_GetPaintParentWidget()
FORCEINLINE TSharedPtr< SWidget > SWidget::Advanced_GetPaintParentWidget () const inline
Definition at line 685 of file SWidget.h.
References FORCEINLINE, and PersistentState.
Advanced_InvalidateVolatility()
FORCEINLINE bool SWidget::Advanced_InvalidateVolatility () inline protected
Recalculates and caches volatility and returns 'true' if the volatility changed.
Definition at line 1132 of file SWidget.h.
References CacheVolatility(), FORCEINLINE, and IsVolatile().
Advanced_IsInvalidationRoot()
virtual bool SWidget::Advanced_IsInvalidationRoot () const inline virtual
Reimplemented in SInvalidationPanel, SVirtualWindow, and SWindow.
Definition at line 1507 of file SWidget.h.
Advanced_IsWindow()
virtual bool SWidget::Advanced_IsWindow () const inline virtual
Is this widget derivative of SWindow.
Reimplemented in SWindow.
Definition at line 1506 of file SWidget.h.
ArrangeChildren()
void SWidget::ArrangeChildren (const FGeometry & AllottedGeometry, FArrangedChildren & ArrangedChildren, bool bUpdateAttributes = false) const
Non-virtual entry point for arrange children.
ensures common work is executed before calling the virtual ArrangeChildren function. Compute the Geometry of all the children and add populate the ArrangedChildren list with their values. Each type of Layout panel should arrange children based on desired behavior.
Optionally, update the collapsed attributes (attributes that affect the visibility) of the children before executing the virtual ArrangeChildren function. The visibility attribute is updated once per frame (see SlatePrepass). Use the option when you are calling ArrangeChildren outside of the regular SWidget Paint/Tick.
Parameters
AllottedGeometry The geometry allotted for this widget by its parent.
ArrangedChildren The array to which to add the WidgetGeometries that represent the arranged children.
bUpdateAttributes Update the collapsed attributes.
Referenced by SNodePanel::SNode::OnPaint().
AssignParentWidget()
void SWidget::AssignParentWidget (TSharedPtr< SWidget > InParent)
CacheDesiredSize()
virtual void SWidget::CacheDesiredSize (float InLayoutScaleMultiplier) protected virtual
The system calls this method.
It performs a breadth-first traversal of every visible widget and asks each widget to cache how big it needs to be in order to present all of its content.
Reimplemented in SEditableText, SGridPanel, and SResponsiveGridPanel.
CacheVolatility()
FORCEINLINE void SWidget::CacheVolatility () inline
Recalculates volatility of the widget and caches the result.
Should be called any time anything examined by your implementation of ComputeVolatility is changed.
Definition at line 1096 of file SWidget.h.
References bCachedVolatile, bForceVolatile, ComputeVolatility(), and FORCEINLINE.
Referenced by Advanced_InvalidateVolatility().
CalculateCullingAndClippingRules()
FSlateRect SWidget::CalculateCullingAndClippingRules (const FGeometry & AllottedGeometry, const FSlateRect & MyCullingRect, bool & bClipToBounds, bool & bAlwaysClip, bool & bIntersectClipBounds) const
Calculates what if any clipping state changes need to happen when drawing this widget.
Returns
the culling rect that should be used going forward.
ComputeDesiredSize()
virtual FVector2D SWidget::ComputeDesiredSize (float LayoutScaleMultiplier) const protected pure virtual
Compute the ideal size necessary to display this widget.
For aggregate widgets (e.g. panels) this size should include the size necessary to show all of its children. CacheDesiredSize() guarantees that the size of descendants is computed and cached before that of the parents, so it is safe to call GetDesiredSize() for any children while implementing this method.
Note that ComputeDesiredSize() is meant as an aide to the developer. It is NOT meant to be very robust in many cases. If your widget is simulating a bouncing ball, you should just return a reasonable size; e.g. 160x160. Let the programmer set up a reasonable rule of resizing the bouncy ball simulation.
Parameters
LayoutScaleMultiplier This parameter is safe to ignore for almost all widgets; only really affects text measuring.
Returns
The desired size.
Implemented in SAudioMaterialButton, SAudioMaterialEnvelope, SAudioMaterialKnob, SAudioMaterialLabeledKnob, SAudioMaterialLabeledSlider, SAudioMaterialMeter, SAudioMaterialSlider, SAudioMeter, SAudioRadialSlider, SAudioSliderBase, SBorder, SBox, SBoxPanel, SButton, SCanvas, SCircularThrobber, SColorBlock, SColorGradientEditor, SColorSpectrum, SColorWheel, SComplexGradient, SCompoundWidget, SConstraintCanvas, SCurveEditorEventChannelView, SCurveEditorKeyBarView, SCurveEditorView, SCurveEditorViewStacked, SDebugCanvas, SDPIScaler, SEditableText, SExpandableArea, SFixedSampledSequenceRuler, SFixedSampledSequenceVectorViewer, SFixedSampledSequenceViewer, SFxWidget, SGraphNodeComment, SGridPanel, SImage, SKeyEditInterface, SLeafWidget, SLinkedBox, SLoadGuard, SNodePanel, SNodePanel::SNode, SObjectBindingTag, SOutputLogDialog, SOverlay, SPanel, SPlayheadOverlay, SProgressBar, SRadialBox, SResponsiveGridPanel, SSafeZone, SSampledSequenceValueGridOverlay, SScaleBox, SScissorRectBox, SScrollBarTrack, SScrollPanel, SSeparator, SSlider, SSpacer, SSplitter2x2, SSplitter, SSynth2DSlider, SSynthKnob, STabDrawer, STextBlock, STooltipPresenter, STriggerThresholdLineWidget, SUniformGridPanel, SUniformWrapPanel, SViewport, SVirtualJoystick, SVirtualKeyboardEntry, SVirtualWindow, SVisualAttachmentBox, SWeakWidget, SWidgetSwitcher, SWindow, SWindowTitleBarArea, SWrapBox, UE::Sequencer::SCompoundTrackLaneView, UE::Sequencer::SOutlinerViewRow, UE::Sequencer::STrackAreaView, and UE::Sequencer::STrackLane.
ComputeFlowDirection()
EFlowDirection SWidget::ComputeFlowDirection () const inline protected
Establishes a new flow direction potentially, if this widget has a particular preference for it and all its children.
Definition at line 1283 of file SWidget.h.
References FlowDirectionPreference, FLayoutLocalization::GetLocalizedLayoutDirection(), GSlateFlowDirection, LeftToRight, and RightToLeft.
ComputeVolatility()
virtual bool SWidget::ComputeVolatility () const inline protected virtual
Recomputes the volatility of the widget.
If you have additional state you automatically want to make the widget volatile, you should sample that information here.
Reimplemented in SAudioMeter, SCircularThrobber, SEditableText, SProgressBar, SScrollBox, SSpinningImage, STableViewBase, SThrobber, STooltipPresenter, SWidgetSwitcher, and SWindow.
Definition at line 1581 of file SWidget.h.
Referenced by CacheVolatility().
ConditionallyDetatchParentWidget()
bool SWidget::ConditionallyDetatchParentWidget (SWidget * InExpectedParent)
References SWidget().
CustomPrepass()
virtual bool SWidget::CustomPrepass (float LayoutScaleMultiplier) inline protected virtual
Reimplemented in SGraphPanel, SInvalidationPanel, SLinkedBox, SScaleBox, and SWindow.
Definition at line 701 of file SWidget.h.
EnableToolTipForceField()
void SWidget::EnableToolTipForceField (const bool bEnableForceField)
Sets whether this widget is a "tool tip force field".
That is, tool-tips should never spawn over the area occupied by this widget, and will instead be repelled to an outside edge
Parameters
bEnableForceField True to enable tool tip force field for this widget
ExecuteActiveTimers()
void SWidget::ExecuteActiveTimers (double CurrentTime, float DeltaTime) private
Iterates over the active timer handles on the widget and executes them if their interval has elapsed.
References DeltaTime.
FindChildGeometries()
bool SWidget::FindChildGeometries (const FGeometry & MyGeometry, const TSet< TSharedRef< SWidget > > & WidgetsToFind, TMap< TSharedRef< SWidget >, FArrangedWidget > & OutResult) const protected
Find the geometry of a descendant widget.
This method assumes that WidgetsToFind are a descendants of this widget. Note that not all widgets are guaranteed to be found; OutResult will contain null entries for missing widgets.
Parameters
MyGeometry The geometry of this widget.
WidgetsToFind The widgets whose geometries we wish to discover.
OutResult A map of widget references to their respective geometries.
Returns
True if all the WidgetGeometries were found. False otherwise.
FindChildGeometries_Helper()
void SWidget::FindChildGeometries_Helper (const FGeometry & MyGeometry, const TSet< TSharedRef< SWidget > > & WidgetsToFind, TMap< TSharedRef< SWidget >, FArrangedWidget > & OutResult) const protected
Actual implementation of FindChildGeometries.
Parameters
MyGeometry The geometry of this widget.
WidgetsToFind The widgets whose geometries we wish to discover.
OutResult A map of widget references to their respective geometries.
FindChildGeometry()
FGeometry SWidget::FindChildGeometry (const FGeometry & MyGeometry, TSharedRef< SWidget > WidgetToFind) const protected
Find the geometry of a descendant widget.
This method assumes that WidgetToFind is a descendant of this widget.
Parameters
MyGeometry The geometry of this widget.
WidgetToFind The widget whose geometry we wish to discover.
Returns
the geometry of WidgetToFind.
Referenced by SListViewSelectorDropdownMenu< ListType >::OnKeyDown().
FindChildUnderMouse()
int32 SWidget::FindChildUnderMouse (const FArrangedChildren & Children, const FPointerEvent & MouseEvent) static protected
Returns
The index of the child that the mouse is currently hovering
References MouseEvent.
FindChildUnderPosition()
int32 SWidget::FindChildUnderPosition (const FArrangedChildren & Children, const UE::Slate::FDeprecateVector2DParameter & ArrangedSpacePosition) static protected
Returns
The index of the child that is under the specified position
ForceVolatile()
FORCEINLINE void SWidget::ForceVolatile (bool bForce) inline
Should this widget always appear as volatile for any layout caching host widget.
A volatile widget's geometry and layout data will never be cached, and neither will any children.
Parameters
bForce should we force the widget to be volatile?
Definition at line 1075 of file SWidget.h.
References bForceVolatile, FORCEINLINE, Invalidate(), and PaintAndVolatility.
GetAllChildren()
virtual FChildren * SWidget::GetAllChildren () inline virtual
Returns the children (if any) of this widget that are used by the invalidation system.
This is used by the FastPath system to generate the correct information for every widget.
Note
Prefer GetChildren. Some widget may hide widget from you.
Should be name GetFastPathChildren or GetInvalidationChildren
Reimplemented in SNodePanel.
Definition at line 847 of file SWidget.h.
References GetChildren().
GetAllMetaData()
template<typename MetaDataType> TArray< TSharedRef< MetaDataType > > SWidget::GetAllMetaData () const inline
Get all metadata of the type provided.
Returns
all the metadata found of the specified type.
Definition at line 1345 of file SWidget.h.
References TArray< InElementType, InAllocatorType >::Add(), MetaData, SCOPE_CYCLE_COUNTER, and StaticCastSharedRef().
GetCachedGeometry()
const FGeometry & SWidget::GetCachedGeometry () const
GetCanTick()
bool SWidget::GetCanTick () const inline
Definition at line 663 of file SWidget.h.
References HasAnyUpdateFlags(), and NeedsTick.
GetChildren()
virtual FChildren * SWidget::GetChildren () pure virtual
Returns the useful children (if any) of this widget.
Some widget type may hide widget if they are needed by the system. Allows for iteration over the Widget's children regardless of how they are actually stored.
Note
Should be renamed to GetVisibleChildren (not ALL children will be returned in all cases).
Implemented in SBox, SBoxPanel, SCanvas, SCompoundWidget, SConstraintCanvas, SDPIScaler, SEditableText, SGridPanel, SInvalidationPanel, SLeafWidget, SNodePanel, SNodePanel::SNode, SOverlay, SPanel, SRadialBox, SResponsiveGridPanel, SScissorRectBox, SScrollBarTrack, SScrollPanel, SSplitter2x2, SSplitter, STooltipPresenter, SUniformGridPanel, SUniformWrapPanel, SWeakWidget, SWidgetSwitcher, SWindowTitleBarArea, SWrapBox, UE::Sequencer::SCompoundTrackLaneView, UE::Sequencer::STrackAreaView, and UE::Sequencer::STrackLane.
Referenced by GetAllChildren().
GetClipping()
FORCEINLINE EWidgetClipping SWidget::GetClipping () const inline
Returns
The current clipping rules for this widget.
Definition at line 1226 of file SWidget.h.
References Clipping, and FORCEINLINE.
GetCreatedInLocation()
FName SWidget::GetCreatedInLocation () const
Returns
An FName of the widget's code location (full path with number == line number of the file)
GetCullingBoundsExtension()
FORCEINLINE FMargin SWidget::GetCullingBoundsExtension () const inline
Returns
CullingBoundsExtension
Definition at line 1257 of file SWidget.h.
References CullingBoundsExtension, and FORCEINLINE.
GetCurrentClippingState()
const TOptional< FSlateClippingState > & SWidget::GetCurrentClippingState () const inline
Returns the clipping state to clip this widget against its parent.
Definition at line 1503 of file SWidget.h.
References PersistentState.
GetCursor()
virtual TOptional< EMouseCursor::Type > SWidget::GetCursor () const protected virtual
The cursor to show when the mouse is hovering over this widget.
GetDesiredSize()
UE::Slate::FDeprecateVector2DResult SWidget::GetDesiredSize () const
Returns
the DesiredSize that was computed the last time CacheDesiredSize() was called.
Referenced by SNodePanel::SNode::ComputeDesiredSize(), and SNodePanel::SNode::GetDesiredSizeForMarquee2f().
GetDisabledForegroundColor()
virtual FSlateColor SWidget::GetDisabledForegroundColor () const virtual
Returns
the Foreground color that this widget sets when this widget or any of its ancestors are disabled; unset options if the widget does not set a foreground color
Reimplemented in SButton.
GetEnabledStateAttribute()
TSlateAttributeRef< bool > SWidget::GetEnabledStateAttribute () const inline protected
Returns
an attribute reference of EnabledStateAttribute
Definition at line 1690 of file SWidget.h.
References EnabledStateAttribute, and TSharedFromThis< SWidget >::SharedThis().
GetFlowDirectionPreference()
EFlowDirectionPreference SWidget::GetFlowDirectionPreference () const inline
Gets the desired flow direction for the layout.
Definition at line 1276 of file SWidget.h.
References FlowDirectionPreference.
GetFocusBrush()
virtual const FSlateBrush * SWidget::GetFocusBrush () const protected virtual
Returns
a brush to draw focus, nullptr if no focus drawing is desired
Reimplemented in SEditableText, and SViewport.
GetForegroundColor()
virtual FSlateColor SWidget::GetForegroundColor () const virtual
Returns
the Foreground color that this widget sets; unset options if the widget does not set a foreground color
Reimplemented in SButton, SCheckBox, SCommentBubble, SCompoundWidget, and SDockTab.
GetHoveredAttribute()
TSlateAttributeRef< bool > SWidget::GetHoveredAttribute () const inline protected
Returns
an attribute reference of HoveredAttribute
Definition at line 1692 of file SWidget.h.
References HoveredAttribute, and TSharedFromThis< SWidget >::SharedThis().
GetMetaData()
template<typename MetaDataType> TSharedPtr< MetaDataType > SWidget::GetMetaData () const inline
Get the metadata of the type provided.
Returns
the first metadata of the type supplied that we encounter
Definition at line 1325 of file SWidget.h.
References MetaData, SCOPE_CYCLE_COUNTER, and StaticCastSharedRef().
GetPaintSpaceGeometry()
const FGeometry & SWidget::GetPaintSpaceGeometry () const
Gets the last geometry used to Tick the widget.
This data may not exist yet if this call happens prior to the widget having been ticked/painted, or it may be out of date, or a frame behind.
GetParentWidget()
FORCEINLINE TSharedPtr< SWidget > SWidget::GetParentWidget () const inline
Definition at line 683 of file SWidget.h.
References FORCEINLINE, and ParentWidgetPtr.
GetPersistentState()
const FSlateWidgetPersistentState & SWidget::GetPersistentState () const inline
Definition at line 670 of file SWidget.h.
References PersistentState.
Referenced by SNumericEntryBox< NumericType >::Tick().
GetPixelSnapping()
FORCEINLINE EWidgetPixelSnapping SWidget::GetPixelSnapping () const inline
Returns
The current pixel snapping rules for this widget.
Definition at line 1237 of file SWidget.h.
References FORCEINLINE, and PixelSnappingMethod.
GetPrepassLayoutScaleMultiplier()
float SWidget::GetPrepassLayoutScaleMultiplier () const inline protected
Definition at line 1629 of file SWidget.h.
References bPrepassLayoutScaleMultiplierSet, and PrepassLayoutScaleMultiplierValue.
GetProxyHandle()
const FWidgetProxyHandle SWidget::GetProxyHandle () const inline
Definition at line 671 of file SWidget.h.
References FastPathProxyHandle.
GetReadableLocation()
virtual FString SWidget::GetReadableLocation () const virtual
Returns
A String of the widget's code location in readable format "BaseFileName(LineNumber)"
GetRelativeLayoutScale()
virtual float SWidget::GetRelativeLayoutScale (const int32 ChildIndex, float LayoutScaleMultiplier) const virtual
What is the Child's scale relative to this widget.
Reimplemented in SDPIScaler, SNodePanel, SNodePanel::SNode, SScaleBox, and SZoomPan.
GetRenderOpacity()
FORCEINLINE float SWidget::GetRenderOpacity () const inline
Returns
the render opacity of the widget.
Definition at line 1141 of file SWidget.h.
References FORCEINLINE, and RenderOpacity.
GetRenderTransform()
FORCEINLINE const TOptional< FSlateRenderTransform > & SWidget::GetRenderTransform () const inline
Returns
the render transform of the widget.
Definition at line 1162 of file SWidget.h.
References FORCEINLINE, and RenderTransformAttribute.
GetRenderTransformAttribute()
TSlateAttributeRef< TOptional< FSlateRenderTransform > > SWidget::GetRenderTransformAttribute () const inline protected
Returns
an attribute reference of RenderTransformAttribute
Definition at line 1696 of file SWidget.h.
References RenderTransformAttribute, and TSharedFromThis< SWidget >::SharedThis().
GetRenderTransformPivot()
FORCEINLINE UE::Slate::FDeprecateVector2DResult SWidget::GetRenderTransformPivot () const inline
Returns
the pivot point of the render transform.
Definition at line 1208 of file SWidget.h.
References UE::Slate::CastToVector2f(), FORCEINLINE, and RenderTransformPivotAttribute.
GetRenderTransformPivotAttribute()
TSlateAttributeRef< FVector2D > SWidget::GetRenderTransformPivotAttribute () const inline protected
Returns
an attribute reference of RenderTransformPivotAttribute
Definition at line 1698 of file SWidget.h.
References RenderTransformPivotAttribute, and TSharedFromThis< SWidget >::SharedThis().
GetRenderTransformPivotWithRespectToFlowDirection()
FORCEINLINE UE::Slate::FDeprecateVector2DResult SWidget::GetRenderTransformPivotWithRespectToFlowDirection () const inline
Definition at line 1186 of file SWidget.h.
References UE::Slate::CastToVector2f(), FORCEINLINE, GSlateFlowDirection, LeftToRight, LIKELY, RenderTransformPivotAttribute, and UE::Math::TVector2< T >::X.
GetRenderTransformWithRespectToFlowDirection()
FORCEINLINE TOptional< FSlateRenderTransform > SWidget::GetRenderTransformWithRespectToFlowDirection () const inline
Definition at line 1167 of file SWidget.h.
References FORCEINLINE, GSlateFlowDirection, LeftToRight, LIKELY, RenderTransformAttribute, Transform, and Translation.
GetStatID()
FORCEINLINE TStatId SWidget::GetStatID (bool bForDeferredUse = false) const inline
Definition at line 791 of file SWidget.h.
References FORCEINLINE, and GCycleStatsShouldEmitNamedEvents.
GetTag()
virtual FName SWidget::GetTag () const virtual
Returns
The name this widget was tagged with
GetTickSpaceGeometry()
const FGeometry & SWidget::GetTickSpaceGeometry () const
Gets the last geometry used to Tick the widget.
This data may not exist yet if this call happens prior to the widget having been ticked/painted, or it may be out of date, or a frame behind.
We recommend not to use this data unless there's no other way to solve your problem. Normally in Slate we try and handle these issues by making a dependent widget part of the hierarchy, as to avoid frame behind or what are referred to as hysteresis problems, both caused by depending on geometry from the previous frame being used to advise how to layout a dependent object the current frame.
GetToolTip()
virtual TSharedPtr< IToolTip > SWidget::GetToolTip () virtual
Returns
The tool tip associated with this widget; Invalid reference if there is not one
Reimplemented in SGraphNode, and SGraphPin.
GetType()
FName SWidget::GetType () const
Returns
The widget's type as an FName ID
GetTypeAsString()
FString SWidget::GetTypeAsString () const
Returns
A String of the widget's type
GetVisibility()
FORCEINLINE EVisibility SWidget::GetVisibility () const inline
Returns
is this widget visible, hidden or collapsed.
Note
this widget can be visible but if a parent is hidden or collapsed, it would not show on screen.
Definition at line 992 of file SWidget.h.
References FORCEINLINE, and VisibilityAttribute.
Referenced by SNodePanel::SNode::ComputeDesiredSize(), and SNodePanel::SNode::OnArrangeChildren().
GetVisibilityAttribute()
TSlateAttributeRef< EVisibility > SWidget::GetVisibilityAttribute () const inline protected
Returns
an attribute reference of VisibilityAttribute
Definition at line 1694 of file SWidget.h.
References TSharedFromThis< SWidget >::SharedThis(), and VisibilityAttribute.
GetWindowZoneOverride()
virtual EWindowZone::Type SWidget::GetWindowZoneOverride () const virtual
Called when the mouse is moved over the widget's window, to determine if we should report whether OS-specific features should be active at this location (such as a title bar grip, system menu, etc.) Usually you should not need to override this function.
Returns
The window "zone" the cursor is over, or EWindowZone::Unspecified if no special behavior is needed
Reimplemented in SAppIconWidget, SExtensionPanel, SWindowTitleBar, and SWindowTitleBarArea.
HasActiveTimers()
bool SWidget::HasActiveTimers () const inline
Does this widget have any active timers?
Definition at line 1668 of file SWidget.h.
References bHasActiveTimers.
HasAnyUpdateFlags()
bool SWidget::HasAnyUpdateFlags (EWidgetUpdateFlags FlagsToCheck) const inline
Definition at line 693 of file SWidget.h.
References EnumHasAnyFlags(), and UpdateFlags.
Referenced by GetCanTick().
HasAnyUserFocus()
TOptional< EFocusCause > SWidget::HasAnyUserFocus () const
Gets whether or not any users have this widget focused, and if so the type of focus (first one found).
Returns
The optional will be set with the focus cause, if unset this widget doesn't have focus.
HasAnyUserFocusOrFocusedDescendants()
bool SWidget::HasAnyUserFocusOrFocusedDescendants () const
Returns
whether or not any users have this widget focused, or any descendant focused.
HasFocusedDescendants()
bool SWidget::HasFocusedDescendants () const
Returns
Whether this widget has any descendants with keyboard focus
HasKeyboardFocus()
virtual bool SWidget::HasKeyboardFocus () const virtual
Checks to see if this widget currently has the keyboard focus.
Returns
True if this widget has keyboard focus
Reimplemented in SEditableTextBox, SSequencerSearchBox, SSpinBox< NumericType >, and SSpinBox< float >.
Referenced by SListViewSelectorDropdownMenu< ListType >::OnKeyDown().
HasMouseCapture()
bool SWidget::HasMouseCapture () const
Checks to see if this widget is the current mouse captor.
Returns
True if this widget has captured the mouse
Referenced by FArguments< ItemType >::OnDragDetected(), and FArguments< ItemType >::OnMouseButtonUp().
HasMouseCaptureByUser()
bool SWidget::HasMouseCaptureByUser (int32 UserIndex, TOptional< int32 > PointerIndex = TOptional< int32 >()) const
Checks to see if this widget has mouse capture from the provided user.
Returns
True if this widget has captured the mouse
HasRegisteredSlateAttribute()
bool SWidget::HasRegisteredSlateAttribute () const inline
Returns
true if the widgets has any bound slate attribute.
Definition at line 666 of file SWidget.h.
References bHasRegisteredSlateAttribute.
Referenced by RemoveAllMetaData(), RemoveMetaData(), and RemoveMetaData().
HasToolTipForceField()
bool SWidget::HasToolTipForceField () const inline
Returns
True if a tool tip force field is active on this widget
Definition at line 957 of file SWidget.h.
References bToolTipForceFieldEnabled.
HasUserFocus()
TOptional< EFocusCause > SWidget::HasUserFocus (int32 UserIndex) const
Gets whether or not the specified users has this widget focused, and if so the type of focus.
Returns
The optional will be set with the focus cause, if unset this widget doesn't have focus.
HasUserFocusedDescendants()
bool SWidget::HasUserFocusedDescendants (int32 UserIndex) const
Gets whether or not the specified users has this widget or any descendant focused.
Returns
The optional will be set with the focus cause, if unset this widget doesn't have focus.
Invalidate()
void SWidget::Invalidate (EInvalidateWidgetReason InvalidateReason)
Invalidates the widget from the view of a layout caching widget that may own this widget.
will force the owning widget to redraw and cache children on the next paint pass.
Referenced by TSlotlessChildren< ChildType >::Add(), TWeakChild< ChildType >::AttachWidget(), ForceVolatile(), TSlotlessChildren< ChildType >::Insert(), FScopedWidgetSlotArguments< FNodeSlot >::Move(), SetCullingBoundsExtension(), SetFlowDirectionPreference(), SetRenderOpacity(), SetWidgetAttribute(), FScopedWidgetSlotArguments< FNodeSlot >::Sort(), TSlotlessChildren< ChildType >::Sort(), FScopedWidgetSlotArguments< FNodeSlot >::StableSort(), FScopedWidgetSlotArguments< FNodeSlot >::Swap(), and TSlotlessChildren< ChildType >::Swap().
InvalidateChildRemovedFromTree()
void SWidget::InvalidateChildRemovedFromTree (SWidget & Child) protected
Called when a child is removed from the tree parent's widget tree either by removing it from a slot.
This can also be called manually if you've got some non-slot based what of no longer reporting children An example of a widget that needs manual calling is SWidgetSwitcher. It keeps all its children but only arranges and paints a single "active" one. Once a child becomes inactive, its cached data should be removed.
References SWidget(), and Child.
IsAttributesUpdatesEnabled()
bool SWidget::IsAttributesUpdatesEnabled () const inline
Returns
true if the widgets will update its registered slate attributes automatically or they need to be updated manually.
Definition at line 668 of file SWidget.h.
References bEnabledAttributesUpdate.
IsChildWidgetCulled()
FORCEINLINE bool SWidget::IsChildWidgetCulled (const FSlateRect & , const FArrangedWidget &) const inline protected
Definition at line 1117 of file SWidget.h.
References FORCEINLINE.
Referenced by SNodePanel::SNode::OnPaint().
IsConstructed()
bool SWidget::IsConstructed () const inline protected
Is the widget construction completed (did we called and returned from the Construct() function)
Definition at line 1525 of file SWidget.h.
References bIsDeclarativeSyntaxConstructionCompleted.
Referenced by SListView< TSharedPtr< FString > >::SetItemsSource().
IsDirectlyHovered()
bool SWidget::IsDirectlyHovered () const
Returns
True if this widget is directly hovered
IsEnabled()
FORCEINLINE bool SWidget::IsEnabled () const inline
Returns
Whether or not this widget is enabled
Definition at line 931 of file SWidget.h.
References EnabledStateAttribute, and FORCEINLINE.
Referenced by SNumericEntryBox< NumericType >::IsToggleEnabled(), ShouldBeEnabled(), and SRigVMEnumPicker::SLATE_ARGUMENT().
IsHovered()
bool SWidget::IsHovered () const inline
Returns
True if this widget hovered
Note
IsHovered used to be virtual. Use SetHover to assign an attribute if you need to override the default behavior.
Definition at line 966 of file SWidget.h.
References HoveredAttribute.
Referenced by FArguments< ItemType >::GetBorder(), and UE::Insights::STableTreeViewCell::GetHintIconVisibility().
IsInteractable()
virtual bool SWidget::IsInteractable () const inline virtual
Returns
Is this widget interactive or not? Defaults to false
Reimplemented in SAudioMaterialKnob, SAudioMaterialSlider, SButton, SCheckBox, SEditableText, SSlider, SSynth2DSlider, and SSynthKnob.
Definition at line 937 of file SWidget.h.
IsParentValid()
FORCEINLINE bool SWidget::IsParentValid () const inline
Definition at line 682 of file SWidget.h.
References FORCEINLINE, and ParentWidgetPtr.
IsVolatile()
FORCEINLINE bool SWidget::IsVolatile () const inline
Whether or not a widget is volatile and will update every frame without being invalidated.
Definition at line 1062 of file SWidget.h.
References bCachedVolatile, and FORCEINLINE.
Referenced by Advanced_InvalidateVolatility().
IsVolatileIndirectly()
FORCEINLINE bool SWidget::IsVolatileIndirectly () const inline
This widget is volatile because its parent or some ancestor is volatile.
Note
only valid if the widget is contained by an InvalidationRoot (the proxy is valid).
Definition at line 1068 of file SWidget.h.
References bInheritedVolatility, and FORCEINLINE.
MarkPrepassAsDirty()
void SWidget::MarkPrepassAsDirty () inline
In fast path, if the widget is mark, do a full Prepass on its next update to calculate it's desired size.
This does not invalidate the widget.
Definition at line 1105 of file SWidget.h.
References bNeedsPrepass.
Referenced by SListView< TSharedPtr< FString > >::GeneratePinnedWidgetForItem().
NeedsPrepass()
bool SWidget::NeedsPrepass () const inline
Definition at line 651 of file SWidget.h.
References bNeedsPrepass.
OnAnalogValueChanged()
virtual FReply SWidget::OnAnalogValueChanged (const FGeometry & MyGeometry, const FAnalogInputEvent & InAnalogInputEvent) virtual
Called when an analog value changes on a button that supports analog.
Parameters
MyGeometry The Geometry of the widget receiving the event
InAnalogInputEvent Analog input event
Returns
Returns whether the event was handled, along with other possible actions
Reimplemented in SAnalogSlider, SKeySelector, SScrollBox, and SViewport.
OnArrangeChildren()
virtual void SWidget::OnArrangeChildren (const FGeometry & AllottedGeometry, FArrangedChildren & ArrangedChildren) const private pure virtual
Compute the Geometry of all the children and add populate the ArrangedChildren list with their values.
Each type of Layout panel should arrange children based on desired behavior.
Parameters
AllottedGeometry The geometry allotted for this widget by its parent.
ArrangedChildren The array to which to add the WidgetGeometries that represent the arranged children.
Implemented in SBox, SBoxPanel, SCanvas, SCompoundWidget, SConstraintCanvas, SDPIScaler, SEditableText, SFilterBarClippingHorizontalBox, SFxWidget, SGraphPanel, SGridPanel, SLeafWidget, SNodePanel, SNodePanel::SNode, SOverlay, SPanel, SRadialBox, SResponsiveGridPanel, SSafeZone, SScaleBox, SScissorRectBox, SScrollBarTrack, SScrollPanel, SSplitter2x2, SSplitter, STabDrawer, STextScroller, STooltipPresenter, SUniformGridPanel, SUniformWrapPanel, SViewport, SVirtualWindow, SVisualAttachmentBox, SWeakWidget, SWidgetSwitcher, SWindowTitleBarArea, SWrapBox, SZoomPan, UE::Sequencer::SCompoundTrackLaneView, UE::Sequencer::SOutlinerViewRow, UE::Sequencer::STrackAreaView, and UE::Sequencer::STrackLane.
OnClippingChanged()
virtual void SWidget::OnClippingChanged () protected virtual
Called when clipping is changed.
Should be used to forward clipping states onto potentially hidden children that actually are responsible for clipping the content.
Reimplemented in SScrollBox, and STableViewBase.
OnCursorQuery()
virtual FCursorReply SWidget::OnCursorQuery (const FGeometry & MyGeometry, const FPointerEvent & CursorEvent) const virtual
The system asks each widget under the mouse to provide a cursor.
This event is bubbled.
Returns
FCursorReply::Unhandled() if the event is not handled; return FCursorReply::Cursor() otherwise.
Reimplemented in SColorSpectrum, SColorWheel, SCommentBubble, SDesignSurface, SEditableText, SGraphNodeResizable, SHyperlink, SNodePanel, SScrollBox, SSpinBox< NumericType >, SSpinBox< float >, SSplitter2x2, SSplitter, STabDrawer, STableViewBase, SViewport, SWindow, UE::Sequencer::STrackAreaView, and UE::Sequencer::STrackLane.
OnDragDetected()
virtual FReply SWidget::OnDragDetected (const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) virtual
Called when Slate detects that a widget started to be dragged.
Usage: A widget can ask Slate to detect a drag. OnMouseDown() reply with FReply::Handled().DetectDrag(SharedThis(this)). Slate will either send an OnDragDetected() event or do nothing. If the user releases a mouse button or leaves the widget before a drag is triggered (maybe user started at the very edge) then no event will be sent.
Parameters
InMyGeometry Widget geometry
InMouseEvent MouseMove that triggered the drag
Reimplemented in FArguments< ItemType >, SDesignerView, SDockTab, SDragAndDropVerticalBox, SRigVMEditorGraphExplorer, STableRow< ItemType >, STableRow< FDataflowOutlinerTreeItemBonePtr >, STableRow< FDisplayedBoneMappingInfoPtr >, STableRow< FFilterConfiguratorNodePtr >, STableRow< FGeometryCollectionFacesTreeItemFacePtr >, STableRow< FGeometryCollectionVerticesTreeItemVertexPtr >, STableRow< FNavigationToolItemPtr >, STableRow< FSCSEditorTreeNodePtrType >, STableRow< FTableTreeNodePtr >, STableRow< TSharedPtr< const FCollectionSpreadSheetItem > >, STableRow< TSharedPtr< const FSelectionViewItem > >, STableRow< TSharedPtr< FAnimAttributeEntry > >, STableRow< TSharedPtr< FBoneTrackPair > >, STableRow< TSharedPtr< FNodeLayoutRow > >, STableRow< TSharedPtr< FRigStackEntry > >, STableRow< TSharedPtr< FRigVMEditorGraphExplorerTreeElement > >, STableRow< TSharedPtr< FRigVMVariableMappingInfoPtr > >, STableRow< TSharedPtr< FVariantTreeRowInfo > >, STableRow< TSharedPtr< SRigVMGraphFunctionLocalizationItem > >, STableRow< TSharedRef< FRigVMTreeNode > >, STableRow< TWeakViewModelPtr< IOutlinerExtension > >, UE::Insights::STableTreeViewRow, UE::Sequencer::SColumnToggleWidget, and UE::Sequencer::SOutlinerViewRow.
References MouseEvent.
Referenced by SFilterableObjectList::FListRow::FListRow().
OnDragEnter()
virtual void SWidget::OnDragEnter (const FGeometry & MyGeometry, const FDragDropEvent & DragDropEvent) virtual
Called during drag and drop when the drag enters a widget.
Enter/Leave events in slate are meant as lightweight notifications. So we do not want to capture mouse or set focus in response to these. However, OnDragEnter must also support external APIs (e.g. OLE Drag/Drop) Those require that we let them know whether we can handle the content being dragged OnDragEnter.
The concession is to return a can_handled/cannot_handle boolean rather than a full FReply.
Parameters
MyGeometry The geometry of the widget receiving the event.
DragDropEvent The drag and drop event.
Returns
A reply that indicated whether the contents of the DragDropEvent can potentially be processed by this widget.
Reimplemented in FArguments< ItemType >, SDesignerView, SDockTab, SDragAndDropVerticalBox, SGraphNode, SGraphNodeComment, SGraphPaletteItem, SGraphPanel, SGraphPin, SGraphPinKnot, SMultiBlockBaseWidget, STableRow< ItemType >, STableRow< FDataflowOutlinerTreeItemBonePtr >, STableRow< FDisplayedBoneMappingInfoPtr >, STableRow< FFilterConfiguratorNodePtr >, STableRow< FGeometryCollectionFacesTreeItemFacePtr >, STableRow< FGeometryCollectionVerticesTreeItemVertexPtr >, STableRow< FNavigationToolItemPtr >, STableRow< FSCSEditorTreeNodePtrType >, STableRow< FTableTreeNodePtr >, STableRow< TSharedPtr< const FCollectionSpreadSheetItem > >, STableRow< TSharedPtr< const FSelectionViewItem > >, STableRow< TSharedPtr< FAnimAttributeEntry > >, STableRow< TSharedPtr< FBoneTrackPair > >, STableRow< TSharedPtr< FNodeLayoutRow > >, STableRow< TSharedPtr< FRigStackEntry > >, STableRow< TSharedPtr< FRigVMEditorGraphExplorerTreeElement > >, STableRow< TSharedPtr< FRigVMVariableMappingInfoPtr > >, STableRow< TSharedPtr< FVariantTreeRowInfo > >, STableRow< TSharedPtr< SRigVMGraphFunctionLocalizationItem > >, STableRow< TSharedRef< FRigVMTreeNode > >, STableRow< TWeakViewModelPtr< IOutlinerExtension > >, UE::Insights::STableTreeViewCell, UE::Sequencer::SColumnToggleWidget, and UE::Sequencer::STrackAreaView.
Referenced by UE::Insights::STableTreeViewCell::OnDragEnter().
OnDragLeave()
virtual void SWidget::OnDragLeave (const FDragDropEvent & DragDropEvent) virtual
Called during drag and drop when the drag leaves a widget.
Parameters
DragDropEvent The drag and drop event.
Reimplemented in FArguments< ItemType >, SDesignerView, SDockTab, SDragAndDropVerticalBox, SGraphNode, SGraphPaletteItem, SGraphPanel, SGraphPin, STableRow< ItemType >, STableRow< FDataflowOutlinerTreeItemBonePtr >, STableRow< FDisplayedBoneMappingInfoPtr >, STableRow< FFilterConfiguratorNodePtr >, STableRow< FGeometryCollectionFacesTreeItemFacePtr >, STableRow< FGeometryCollectionVerticesTreeItemVertexPtr >, STableRow< FNavigationToolItemPtr >, STableRow< FSCSEditorTreeNodePtrType >, STableRow< FTableTreeNodePtr >, STableRow< TSharedPtr< const FCollectionSpreadSheetItem > >, STableRow< TSharedPtr< const FSelectionViewItem > >, STableRow< TSharedPtr< FAnimAttributeEntry > >, STableRow< TSharedPtr< FBoneTrackPair > >, STableRow< TSharedPtr< FNodeLayoutRow > >, STableRow< TSharedPtr< FRigStackEntry > >, STableRow< TSharedPtr< FRigVMEditorGraphExplorerTreeElement > >, STableRow< TSharedPtr< FRigVMVariableMappingInfoPtr > >, STableRow< TSharedPtr< FVariantTreeRowInfo > >, STableRow< TSharedPtr< SRigVMGraphFunctionLocalizationItem > >, STableRow< TSharedRef< FRigVMTreeNode > >, STableRow< TWeakViewModelPtr< IOutlinerExtension > >, UE::Insights::STableTreeViewCell, and UE::Sequencer::STrackAreaView.
Referenced by UE::Insights::STableTreeViewCell::OnDragLeave().
OnDragOver()
virtual FReply SWidget::OnDragOver (const FGeometry & MyGeometry, const FDragDropEvent & DragDropEvent) virtual
Called during drag and drop when the the mouse is being dragged over a widget.
Parameters
MyGeometry The geometry of the widget receiving the event.
DragDropEvent The drag and drop event.
Returns
A reply that indicated whether this event was handled.
Reimplemented in FArguments< ItemType >, SDataflowGraphEditor, SDesignerView, SDragAndDropVerticalBox, SEditableText, SGraphNode, SGraphPanel, SGraphPin, SMultiBlockBaseWidget, SMultiBoxWidget, SSCSEditorDragDropTree, STableRow< ItemType >, STableRow< FDataflowOutlinerTreeItemBonePtr >, STableRow< FDisplayedBoneMappingInfoPtr >, STableRow< FFilterConfiguratorNodePtr >, STableRow< FGeometryCollectionFacesTreeItemFacePtr >, STableRow< FGeometryCollectionVerticesTreeItemVertexPtr >, STableRow< FNavigationToolItemPtr >, STableRow< FSCSEditorTreeNodePtrType >, STableRow< FTableTreeNodePtr >, STableRow< TSharedPtr< const FCollectionSpreadSheetItem > >, STableRow< TSharedPtr< const FSelectionViewItem > >, STableRow< TSharedPtr< FAnimAttributeEntry > >, STableRow< TSharedPtr< FBoneTrackPair > >, STableRow< TSharedPtr< FNodeLayoutRow > >, STableRow< TSharedPtr< FRigStackEntry > >, STableRow< TSharedPtr< FRigVMEditorGraphExplorerTreeElement > >, STableRow< TSharedPtr< FRigVMVariableMappingInfoPtr > >, STableRow< TSharedPtr< FVariantTreeRowInfo > >, STableRow< TSharedPtr< SRigVMGraphFunctionLocalizationItem > >, STableRow< TSharedRef< FRigVMTreeNode > >, STableRow< TWeakViewModelPtr< IOutlinerExtension > >, UE::Sequencer::SOutlinerView, and UE::Sequencer::STrackAreaView.
OnDrop()
virtual FReply SWidget::OnDrop (const FGeometry & MyGeometry, const FDragDropEvent & DragDropEvent) virtual
Called when the user is dropping something onto a widget; terminates drag and drop.
Parameters
MyGeometry The geometry of the widget receiving the event.
DragDropEvent The drag and drop event.
Returns
A reply that indicated whether this event was handled.
Reimplemented in FArguments< ItemType >, SDataflowGraphEditor, SDesignerView, SDockTab, SDragAndDropVerticalBox, SEditableText, SGraphNode, SGraphNodeComment, SGraphPaletteItem, SGraphPanel, SGraphPin, SMultiBlockBaseWidget, SMultiBoxWidget, SRigVMNodeLayoutWidget, SSCSEditorDragDropTree, STableRow< ItemType >, STableRow< FDataflowOutlinerTreeItemBonePtr >, STableRow< FDisplayedBoneMappingInfoPtr >, STableRow< FFilterConfiguratorNodePtr >, STableRow< FGeometryCollectionFacesTreeItemFacePtr >, STableRow< FGeometryCollectionVerticesTreeItemVertexPtr >, STableRow< FNavigationToolItemPtr >, STableRow< FSCSEditorTreeNodePtrType >, STableRow< FTableTreeNodePtr >, STableRow< TSharedPtr< const FCollectionSpreadSheetItem > >, STableRow< TSharedPtr< const FSelectionViewItem > >, STableRow< TSharedPtr< FAnimAttributeEntry > >, STableRow< TSharedPtr< FBoneTrackPair > >, STableRow< TSharedPtr< FNodeLayoutRow > >, STableRow< TSharedPtr< FRigStackEntry > >, STableRow< TSharedPtr< FRigVMEditorGraphExplorerTreeElement > >, STableRow< TSharedPtr< FRigVMVariableMappingInfoPtr > >, STableRow< TSharedPtr< FVariantTreeRowInfo > >, STableRow< TSharedPtr< SRigVMGraphFunctionLocalizationItem > >, STableRow< TSharedRef< FRigVMTreeNode > >, STableRow< TWeakViewModelPtr< IOutlinerExtension > >, UE::Sequencer::SOutlinerView, and UE::Sequencer::STrackAreaView.
OnFinishedKeyInput()
virtual void SWidget::OnFinishedKeyInput () virtual
All the key (keyboard, gamepay, joystick, etc.) input from this frame has been routed.
This is a widget's chance to act on any accumulated data.
OnFinishedPointerInput()
virtual void SWidget::OnFinishedPointerInput () virtual
All the pointer (mouse, touch, stylus, etc.) events from this frame have been routed.
This is a widget's chance to act on any accumulated data.
Reimplemented in SInteractiveCurveEditorView, and SViewport.
OnFocusChanging()
virtual void SWidget::OnFocusChanging (const FWeakWidgetPath & PreviousFocusPath, const FWidgetPath & NewWidgetPath, const FFocusEvent & InFocusEvent) virtual
Called whenever a focus path is changing on all the widgets within the old and new focus paths.
Reimplemented in SMultiBoxWidget, and SScrollBox.
OnFocusLost()
virtual void SWidget::OnFocusLost (const FFocusEvent & InFocusEvent) virtual
Called when this widget loses focus.
This event does not bubble.
Parameters
InFocusEvent The FocusEvent
Reimplemented in SButton, SCommonTileView< ItemType >, SEditableText, SInputKeySelector, SNodePanel, SScrollBox, SSlider, SSuggestionTextBox, SSynth2DSlider, SSynthKnob, STableViewBase, SViewport, and SVirtualKeyboardEntry.
OnFocusReceived()
virtual FReply SWidget::OnFocusReceived (const FGeometry & MyGeometry, const FFocusEvent & InFocusEvent) virtual
Called when focus is given to this widget.
This event does not bubble.
Parameters
MyGeometry The Geometry of the widget receiving the event
InFocusEvent The FocusEvent
Returns
Returns whether the event was handled, along with other possible actions
Reimplemented in SCommonListView< ItemType >, SCommonTileView< ItemType >, SCommonTreeView< ItemType >, SCurveEditorTreeTextFilter, SEditableText, SEditableTextBox, SEditorViewport, SMultiBoxWidget, SNumericEntryBox< NumericType >, SScrollBox, SSequencerSearchBox, SSpinBox< NumericType >, SSpinBox< float >, SViewport, SVirtualKeyboardEntry, and SWindow.
Referenced by SCommonListView< ItemType >::OnFocusReceived(), SCommonTileView< ItemType >::OnFocusReceived(), and SCommonTreeView< ItemType >::OnFocusReceived().
OnKeyChar()
virtual FReply SWidget::OnKeyChar (const FGeometry & MyGeometry, const FCharacterEvent & InCharacterEvent) virtual
Called after a character is entered while this widget has keyboard focus.
Parameters
MyGeometry The Geometry of the widget receiving the event
InCharacterEvent Character event
Returns
Returns whether the event was handled, along with other possible actions
Reimplemented in SEditableText, SMultiBoxWidget, and SViewport.
OnKeyDown()
virtual FReply SWidget::OnKeyDown (const FGeometry & MyGeometry, const FKeyEvent & InKeyEvent) virtual
Called after a key is pressed when this widget has focus (this event bubbles if not handled)
Parameters
MyGeometry The Geometry of the widget receiving the event
InKeyEvent Key event
Returns
Returns whether the event was handled, along with other possible actions
Reimplemented in FOnSelectionChanged<>, SAudioMaterialKnob, SAudioMaterialSlider, SBoneTreeMenu, SButton, SCheckBox, SClassPickerDialog, SColorGradientEditor, SCurveEditorPanel, SCurveEditorTree, SDataflowGraphEditor, SDataflowMembersWidget, SDeleteAssetsDialog, SDesignerView, SEditableText, SEditableTextBox, SEditorViewport, SFindInBlueprints, SGlobalPlayWorldActions, SGraphActionMenu, SGraphPanel, SInputKeySelector, SKeySelector, SListView< ItemType >, SListView< FCurveEditorTreeItemID >, SListView< FName >, SListView< FSCSEditorTreeNodePtrType >, SListView< ListType >, SListView< OptionType >, SListView< TSharedPtr< class FComponentClassComboEntry > >, SListView< TSharedPtr< class FDebugLineItem > >, SListView< TSharedPtr< class FFilterConfiguratorNode > >, SListView< TSharedPtr< class FTableTreeNode > >, SListView< TSharedPtr< const FCollectionSpreadSheetItem > >, SListView< TSharedPtr< const FSelectionViewItem > >, SListView< TSharedPtr< EAudioOscilloscopeTriggerMode > >, SListView< TSharedPtr< ECSVImportType > >, SListView< TSharedPtr< ERichCurveInterpMode > >, SListView< TSharedPtr< FAnimAttributeEntry > >, SListView< TSharedPtr< FBlueprintDebugObjectInstance > >, SListView< TSharedPtr< FBlueprintDifferenceTreeEntry > >, SListView< TSharedPtr< FDataflowOutlinerTreeItem > >, SListView< TSharedPtr< FDisplayedBoneMappingInfo > >, SListView< TSharedPtr< FGeometryCollectionFacesTreeItem > >, SListView< TSharedPtr< FGeometryCollectionVerticesTreeItem > >, SListView< TSharedPtr< FGraphActionNode > >, SListView< TSharedPtr< FName > >, SListView< TSharedPtr< FPendingDelete > >, SListView< TSharedPtr< FPendingPrivateAsset > >, SListView< TSharedPtr< FRigStackEntry > >, SListView< TSharedPtr< FRigVMDebugObjectInstance > >, SListView< TSharedPtr< FRigVMEditorGraphExplorerTreeElement > >, SListView< TSharedPtr< FRigVMStringWithTag > >, SListView< TSharedPtr< FSequencerFilterSuggestionListEntryBase > >, SListView< TSharedPtr< FString > >, SListView< TSharedPtr< FText > >, SListView< TSharedPtr< int32 > >, SListView< TSharedPtr< SBlueprintNamespaceEntry::FPathTreeNodeItem > >, SListView< TSharedPtr< SBoneTreeMenu::FBoneNameInfo > >, SListView< TSharedPtr< SReadOnlyHierarchyView::FItem > >, SListView< TSharedPtr< SRigVMNodeLayoutWidget::FNodeLayoutRow > >, SListView< TSharedPtr< SRigVMVariantWidget::FVariantTreeRowInfo > >, SListView< TSharedPtr< UE::Insights::FFilter > >, SListView< TSharedPtr< UE::Insights::FFilterGroupOperator > >, SListView< TSharedPtr< UE::Insights::IFilterOperator > >, SListView< TSharedRef< FRigVMTreeNode > >, SListView< TSharedRef< UE::Insights::ITableTreeViewPreset > >, SListView< TWeakPtr< FViewModel > >, SListView< TWeakViewModelPtr< IOutlinerExtension > >, SListView< UObject * >, SListViewSelectorDropdownMenu< ListType >, SMultiBoxWidget, SMyBlueprint, SNodePanel, SNumericEntryBox< NumericType >, SOutputLogDialog, SPrivateAssetsDialog, SRigVMFindReferences, SRigVMNodeLayoutWidget, SSCSEditor, SSkinWeightProfileImportOptions, SSlider, SSpinBox< NumericType >, SSpinBox< float >, SSuggestionTextBox, SSynth2DSlider, SSynthKnob, STableViewBase, STextComboPopup, STreeView< ItemType >, STreeView< FCurveEditorTreeItemID >, STreeView< FKeyTreeItem >, STreeView< FReferenceTreeItemPtr >, STreeView< FRigVMSearchResult >, STreeView< FSCSEditorTreeNodePtrType >, STreeView< FSearchResult >, STreeView< TSharedPtr< class FDebugLineItem > >, STreeView< TSharedPtr< class FFilterConfiguratorNode > >, STreeView< TSharedPtr< class FTableTreeNode > >, STreeView< TSharedPtr< FBlueprintDifferenceTreeEntry > >, STreeView< TSharedPtr< FDataflowOutlinerTreeItem > >, STreeView< TSharedPtr< FGeometryCollectionFacesTreeItem > >, STreeView< TSharedPtr< FGeometryCollectionVerticesTreeItem > >, STreeView< TSharedPtr< FGraphActionNode > >, STreeView< TSharedPtr< FRigStackEntry > >, STreeView< TSharedPtr< FRigVMEditorGraphExplorerTreeElement > >, STreeView< TSharedPtr< FRigVMVariableMappingInfo > >, STreeView< TSharedPtr< SBlueprintNamespaceEntry::FPathTreeNodeItem > >, STreeView< TSharedPtr< SBoneTreeMenu::FBoneNameInfo > >, STreeView< TSharedPtr< SReadOnlyHierarchyView::FItem > >, STreeView< TSharedPtr< SRigVMNodeLayoutWidget::FNodeLayoutRow > >, STreeView< TSharedPtr< SRigVMVariantWidget::FVariantTreeRowInfo > >, STreeView< TSharedRef< FRigVMTreeNode > >, STreeView< TWeakPtr< FViewModel > >, STreeView< TWeakViewModelPtr< IOutlinerExtension > >, SViewport, UE::Insights::STableTreeView, UE::Sequencer::SOutlinerView, and UE::Sequencer::STrackAreaView.
Referenced by SComboBox< OptionType >::OnKeyDown(), and SListViewSelectorDropdownMenu< ListType >::OnKeyDown().
OnKeyUp()
virtual FReply SWidget::OnKeyUp (const FGeometry & MyGeometry, const FKeyEvent & InKeyEvent) virtual
Called after a key is released when this widget has focus.
Parameters
MyGeometry The Geometry of the widget receiving the event
InKeyEvent Key event
Returns
Returns whether the event was handled, along with other possible actions
Reimplemented in SAudioMaterialKnob, SAudioMaterialSlider, SButton, SCheckBox, SDataflowGraphEditor, SDesignerView, SEditableText, SInputKeySelector, SNodePanel, SSlider, SSynth2DSlider, SSynthKnob, SViewport, and UE::Sequencer::STrackAreaView.
OnMapCursor()
virtual TOptional< TSharedRef< SWidget > > SWidget::OnMapCursor (const FCursorReply & CursorReply) const virtual
After OnCursorQuery has specified a cursor type the system asks each widget under the mouse to map that cursor to a widget.
This event is bubbled.
Returns
TOptional<TSharedRef<SWidget>>() if you don't have a mapping otherwise return the Widget to show.
Reimplemented in SViewport.
OnMotionDetected()
virtual FReply SWidget::OnMotionDetected (const FGeometry & MyGeometry, const FMotionEvent & InMotionEvent) virtual
Called when motion is detected (controller or device) e.g.
Someone tilts or shakes their controller.
Parameters
InMotionEvent The motion event generated
Reimplemented in SViewport.
OnMouseButtonDoubleClick()
virtual FReply SWidget::OnMouseButtonDoubleClick (const FGeometry & InMyGeometry, const FPointerEvent & InMouseEvent) virtual
Called when a mouse button is double clicked.
Override this in derived classes.
Parameters
InMyGeometry Widget geometry
InMouseEvent Mouse button event
Returns
Returns whether the event was handled, along with other possible actions
Reimplemented in FArguments< ItemType >, SButton, SCheckBox, SColorGradientEditor, SColorSpectrum, SColorWheel, SDataflowEdNode, SDockTab, SEditableText, SGraphNode, SGraphPanel, SRigVMGraphNode, SSplitter, STableRow< ItemType >, STableRow< FDataflowOutlinerTreeItemBonePtr >, STableRow< FDisplayedBoneMappingInfoPtr >, STableRow< FFilterConfiguratorNodePtr >, STableRow< FGeometryCollectionFacesTreeItemFacePtr >, STableRow< FGeometryCollectionVerticesTreeItemVertexPtr >, STableRow< FNavigationToolItemPtr >, STableRow< FSCSEditorTreeNodePtrType >, STableRow< FTableTreeNodePtr >, STableRow< TSharedPtr< const FCollectionSpreadSheetItem > >, STableRow< TSharedPtr< const FSelectionViewItem > >, STableRow< TSharedPtr< FAnimAttributeEntry > >, STableRow< TSharedPtr< FBoneTrackPair > >, STableRow< TSharedPtr< FNodeLayoutRow > >, STableRow< TSharedPtr< FRigStackEntry > >, STableRow< TSharedPtr< FRigVMEditorGraphExplorerTreeElement > >, STableRow< TSharedPtr< FRigVMVariableMappingInfoPtr > >, STableRow< TSharedPtr< FVariantTreeRowInfo > >, STableRow< TSharedPtr< SRigVMGraphFunctionLocalizationItem > >, STableRow< TSharedRef< FRigVMTreeNode > >, STableRow< TWeakViewModelPtr< IOutlinerExtension > >, STableViewBase, SViewport, SWindowTitleBarArea, UE::SequenceNavigator::SNavigationToolTreeRow, UE::Sequencer::SChannelView, UE::Sequencer::SColumnToggleWidget, and UE::Sequencer::STrackAreaView.
OnMouseButtonDown()
virtual FReply SWidget::OnMouseButtonDown (const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) virtual
The system calls this method to notify the widget that a mouse button was pressed within it.
This event is bubbled.
Parameters
MyGeometry The Geometry of the widget receiving the event
MouseEvent Information about the input event
Returns
Whether the event was handled along with possible requests for the system to take action.
Reimplemented in FArguments< ItemType >, SAnalogSlider, SAudioMaterialButton, SAudioMaterialKnob, SAudioMaterialSlider, SAudioSpectrogram, SAudioSpectrumPlot, SButton, SCheckBox, SColorBlock, SColorGradientEditor, SColorSpectrum, SColorWheel, SDefaultGraphActionWidget, SDesignerView, SDesignSurface, SDetailsSplitter, SDockTab, SDragAndDropVerticalBox, SEditableText, SGraphNode, SGraphNodeResizable, SGraphPaletteItem, SGraphPanel, SInputKeySelector, SInteractiveCurveEditorView, SKeySelector, SListView< ItemType >, SListView< ItemType >::SListViewPinnedRowWidget, SListView< FCurveEditorTreeItemID >, SListView< FName >, SListView< FSCSEditorTreeNodePtrType >, SListView< ListType >, SListView< OptionType >, SListView< TSharedPtr< class FComponentClassComboEntry > >, SListView< TSharedPtr< class FDebugLineItem > >, SListView< TSharedPtr< class FFilterConfiguratorNode > >, SListView< TSharedPtr< class FTableTreeNode > >, SListView< TSharedPtr< const FCollectionSpreadSheetItem > >, SListView< TSharedPtr< const FSelectionViewItem > >, SListView< TSharedPtr< EAudioOscilloscopeTriggerMode > >, SListView< TSharedPtr< ECSVImportType > >, SListView< TSharedPtr< ERichCurveInterpMode > >, SListView< TSharedPtr< FAnimAttributeEntry > >, SListView< TSharedPtr< FBlueprintDebugObjectInstance > >, SListView< TSharedPtr< FBlueprintDifferenceTreeEntry > >, SListView< TSharedPtr< FDataflowOutlinerTreeItem > >, SListView< TSharedPtr< FDisplayedBoneMappingInfo > >, SListView< TSharedPtr< FGeometryCollectionFacesTreeItem > >, SListView< TSharedPtr< FGeometryCollectionVerticesTreeItem > >, SListView< TSharedPtr< FGraphActionNode > >, SListView< TSharedPtr< FName > >, SListView< TSharedPtr< FPendingDelete > >, SListView< TSharedPtr< FPendingPrivateAsset > >, SListView< TSharedPtr< FRigStackEntry > >, SListView< TSharedPtr< FRigVMDebugObjectInstance > >, SListView< TSharedPtr< FRigVMEditorGraphExplorerTreeElement > >, SListView< TSharedPtr< FRigVMStringWithTag > >, SListView< TSharedPtr< FSequencerFilterSuggestionListEntryBase > >, SListView< TSharedPtr< FString > >, SListView< TSharedPtr< FText > >, SListView< TSharedPtr< int32 > >, SListView< TSharedPtr< SBlueprintNamespaceEntry::FPathTreeNodeItem > >, SListView< TSharedPtr< SBoneTreeMenu::FBoneNameInfo > >, SListView< TSharedPtr< SReadOnlyHierarchyView::FItem > >, SListView< TSharedPtr< SRigVMNodeLayoutWidget::FNodeLayoutRow > >, SListView< TSharedPtr< SRigVMVariantWidget::FVariantTreeRowInfo > >, SListView< TSharedPtr< UE::Insights::FFilter > >, SListView< TSharedPtr< UE::Insights::FFilterGroupOperator > >, SListView< TSharedPtr< UE::Insights::IFilterOperator > >, SListView< TSharedRef< FRigVMTreeNode > >, SListView< TSharedRef< UE::Insights::ITableTreeViewPreset > >, SListView< TWeakPtr< FViewModel > >, SListView< TWeakViewModelPtr< IOutlinerExtension > >, SListView< UObject * >, SNodePanel, SRigVMGraphNode, SRigVMGraphPinCategory, SRigVMVariantCapsule, SRigVMVariantGuidWidget, SScrollBar, SScrollBox, SSCS_RowWidget, SSlider, SSpinBox< NumericType >, SSpinBox< float >, SSplitter2x2, SSplitter, SSynth2DSlider, SSynthKnob, STabDrawer, STableRow< ItemType >, STableRow< FDataflowOutlinerTreeItemBonePtr >, STableRow< FDisplayedBoneMappingInfoPtr >, STableRow< FFilterConfiguratorNodePtr >, STableRow< FGeometryCollectionFacesTreeItemFacePtr >, STableRow< FGeometryCollectionVerticesTreeItemVertexPtr >, STableRow< FNavigationToolItemPtr >, STableRow< FSCSEditorTreeNodePtrType >, STableRow< FTableTreeNodePtr >, STableRow< TSharedPtr< const FCollectionSpreadSheetItem > >, STableRow< TSharedPtr< const FSelectionViewItem > >, STableRow< TSharedPtr< FAnimAttributeEntry > >, STableRow< TSharedPtr< FBoneTrackPair > >, STableRow< TSharedPtr< FNodeLayoutRow > >, STableRow< TSharedPtr< FRigStackEntry > >, STableRow< TSharedPtr< FRigVMEditorGraphExplorerTreeElement > >, STableRow< TSharedPtr< FRigVMVariableMappingInfoPtr > >, STableRow< TSharedPtr< FVariantTreeRowInfo > >, STableRow< TSharedPtr< SRigVMGraphFunctionLocalizationItem > >, STableRow< TSharedRef< FRigVMTreeNode > >, STableRow< TWeakViewModelPtr< IOutlinerExtension > >, STableViewBase, SViewport, SWindow, UE::Sequencer::SChannelView, UE::Sequencer::SColumnToggleWidget, UE::Sequencer::STrackAreaView, and UE::Sequencer::STrackLane.
References MouseEvent.
Referenced by SBorder::SLATE_EVENT(), SImage::SLATE_EVENT(), and SSpinningImage::SLATE_EVENT().
OnMouseButtonUp()
virtual FReply SWidget::OnMouseButtonUp (const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) virtual
The system calls this method to notify the widget that a mouse button was release within it.
This event is bubbled.
Parameters
MyGeometry The Geometry of the widget receiving the event
MouseEvent Information about the input event
Returns
Whether the event was handled along with possible requests for the system to take action.
Reimplemented in FArguments< ItemType >, SAnalogSlider, SAudioMaterialButton, SAudioMaterialKnob, SAudioMaterialSlider, SAudioSpectrogram, SAudioSpectrumPlot, SButton, SCheckBox, SColorGradientEditor, SColorSpectrum, SColorWheel, SCurveEditorViewNormalized, SDesignerView, SDesignSurface, SDockTab, SEditableText, SGraphNode, SGraphNodeComment, SGraphNodeResizable, SGraphPanel, SGraphPin, SHeaderRow, SInteractiveCurveEditorView, SListView< ItemType >, SListView< FCurveEditorTreeItemID >, SListView< FName >, SListView< FSCSEditorTreeNodePtrType >, SListView< ListType >, SListView< OptionType >, SListView< TSharedPtr< class FComponentClassComboEntry > >, SListView< TSharedPtr< class FDebugLineItem > >, SListView< TSharedPtr< class FFilterConfiguratorNode > >, SListView< TSharedPtr< class FTableTreeNode > >, SListView< TSharedPtr< const FCollectionSpreadSheetItem > >, SListView< TSharedPtr< const FSelectionViewItem > >, SListView< TSharedPtr< EAudioOscilloscopeTriggerMode > >, SListView< TSharedPtr< ECSVImportType > >, SListView< TSharedPtr< ERichCurveInterpMode > >, SListView< TSharedPtr< FAnimAttributeEntry > >, SListView< TSharedPtr< FBlueprintDebugObjectInstance > >, SListView< TSharedPtr< FBlueprintDifferenceTreeEntry > >, SListView< TSharedPtr< FDataflowOutlinerTreeItem > >, SListView< TSharedPtr< FDisplayedBoneMappingInfo > >, SListView< TSharedPtr< FGeometryCollectionFacesTreeItem > >, SListView< TSharedPtr< FGeometryCollectionVerticesTreeItem > >, SListView< TSharedPtr< FGraphActionNode > >, SListView< TSharedPtr< FName > >, SListView< TSharedPtr< FPendingDelete > >, SListView< TSharedPtr< FPendingPrivateAsset > >, SListView< TSharedPtr< FRigStackEntry > >, SListView< TSharedPtr< FRigVMDebugObjectInstance > >, SListView< TSharedPtr< FRigVMEditorGraphExplorerTreeElement > >, SListView< TSharedPtr< FRigVMStringWithTag > >, SListView< TSharedPtr< FSequencerFilterSuggestionListEntryBase > >, SListView< TSharedPtr< FString > >, SListView< TSharedPtr< FText > >, SListView< TSharedPtr< int32 > >, SListView< TSharedPtr< SBlueprintNamespaceEntry::FPathTreeNodeItem > >, SListView< TSharedPtr< SBoneTreeMenu::FBoneNameInfo > >, SListView< TSharedPtr< SReadOnlyHierarchyView::FItem > >, SListView< TSharedPtr< SRigVMNodeLayoutWidget::FNodeLayoutRow > >, SListView< TSharedPtr< SRigVMVariantWidget::FVariantTreeRowInfo > >, SListView< TSharedPtr< UE::Insights::FFilter > >, SListView< TSharedPtr< UE::Insights::FFilterGroupOperator > >, SListView< TSharedPtr< UE::Insights::IFilterOperator > >, SListView< TSharedRef< FRigVMTreeNode > >, SListView< TSharedRef< UE::Insights::ITableTreeViewPreset > >, SListView< TWeakPtr< FViewModel > >, SListView< TWeakViewModelPtr< IOutlinerExtension > >, SListView< UObject * >, SNodePanel, SRigVMGraphNodeComment, SScrollBar, SScrollBox, SSlider, SSpinBox< NumericType >, SSpinBox< float >, SSplitter2x2, SSplitter, SSynth2DSlider, SSynthKnob, STabDrawer, STableRow< ItemType >, STableRow< FDataflowOutlinerTreeItemBonePtr >, STableRow< FDisplayedBoneMappingInfoPtr >, STableRow< FFilterConfiguratorNodePtr >, STableRow< FGeometryCollectionFacesTreeItemFacePtr >, STableRow< FGeometryCollectionVerticesTreeItemVertexPtr >, STableRow< FNavigationToolItemPtr >, STableRow< FSCSEditorTreeNodePtrType >, STableRow< FTableTreeNodePtr >, STableRow< TSharedPtr< const FCollectionSpreadSheetItem > >, STableRow< TSharedPtr< const FSelectionViewItem > >, STableRow< TSharedPtr< FAnimAttributeEntry > >, STableRow< TSharedPtr< FBoneTrackPair > >, STableRow< TSharedPtr< FNodeLayoutRow > >, STableRow< TSharedPtr< FRigStackEntry > >, STableRow< TSharedPtr< FRigVMEditorGraphExplorerTreeElement > >, STableRow< TSharedPtr< FRigVMVariableMappingInfoPtr > >, STableRow< TSharedPtr< FVariantTreeRowInfo > >, STableRow< TSharedPtr< SRigVMGraphFunctionLocalizationItem > >, STableRow< TSharedRef< FRigVMTreeNode > >, STableRow< TWeakViewModelPtr< IOutlinerExtension > >, STableViewBase, SViewport, SWindow, UE::SequenceNavigator::SNavigationToolTreeRow, UE::Sequencer::SChannelView, UE::Sequencer::SColumnToggleWidget, UE::Sequencer::STrackAreaView, and UE::Sequencer::STrackLane.
References MouseEvent.
Referenced by SBorder::SLATE_EVENT().
OnMouseCaptureLost()
virtual void SWidget::OnMouseCaptureLost (const FCaptureLostEvent & CaptureLostEvent) virtual
Called when this widget had captured the mouse, but that capture has been revoked for some reason.
Reimplemented in SAudioMaterialSlider, SButton, SNodePanel, SScrollBox, SSlider, STableViewBase, UE::Sequencer::SColumnToggleWidget, and UE::Sequencer::STrackAreaView.
OnMouseEnter()
virtual void SWidget::OnMouseEnter (const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) virtual
The system will use this event to notify a widget that the cursor has entered it.
This event is uses a custom bubble strategy.
Parameters
MyGeometry The Geometry of the widget receiving the event
MouseEvent Information about the input event
Reimplemented in SButton, SCheckBox, SCurveEditorPanel, SDesignerView, SEditorViewportToolbarMenu, SGraphNodeResizable, SGraphPin, SInteractiveCurveEditorView, SNodePanel::SNode, SScrollBar, SScrollBox, SSubMenuHandler, STableViewBase, SViewport, SViewportToolBarComboMenu, SViewportToolBarIconMenu, UE::Insights::STableTreeViewCell, UE::Sequencer::SColumnToggleWidget, UE::Sequencer::SOutlinerViewRow, and UE::Sequencer::STrackAreaView.
References MouseEvent.
Referenced by SNodePanel::SNode::OnMouseEnter(), and UE::Insights::STableTreeViewCell::OnMouseEnter().
OnMouseLeave()
virtual void SWidget::OnMouseLeave (const FPointerEvent & MouseEvent) virtual
The system will use this event to notify a widget that the cursor has left it.
This event is uses a custom bubble strategy.
Parameters
MouseEvent Information about the input event
Reimplemented in SAudioSpectrumPlot, SButton, SCheckBox, SColorGradientEditor, SCommonListView< ItemType >, SCommonTileView< ItemType >, SCommonTreeView< ItemType >, SCurveEditorPanel, SDesignerView, SDetailsSplitter, SGraphNodeResizable, SGraphPin, SInteractiveCurveEditorView, SNodePanel::SNode, SScrollBar, SScrollBox, SSplitter, SSubMenuHandler, STabDrawer, STableViewBase, SViewport, UE::Insights::STableTreeViewCell, UE::Sequencer::SChannelView, UE::Sequencer::SColumnToggleWidget, UE::Sequencer::SOutlinerViewRow, and UE::Sequencer::STrackAreaView.
References MouseEvent.
Referenced by SNodePanel::SNode::OnMouseLeave(), and UE::Insights::STableTreeViewCell::OnMouseLeave().
OnMouseMove()
virtual FReply SWidget::OnMouseMove (const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) virtual
The system calls this method to notify the widget that a mouse moved within it.
This event is bubbled.
Parameters
MyGeometry The Geometry of the widget receiving the event
MouseEvent Information about the input event
Returns
Whether the event was handled along with possible requests for the system to take action.
Reimplemented in SAudioMaterialKnob, SAudioMaterialSlider, SAudioSpectrumPlot, SButton, SColorGradientEditor, SColorSpectrum, SColorWheel, SDesignerView, SDesignSurface, SDetailsSplitter, SEditableText, SGraphNodeResizable, SGraphPanel, SGraphPin, SInteractiveCurveEditorView, SKeySelector, SNodePanel, SScrollBar, SScrollBox, SSlider, SSpinBox< NumericType >, SSpinBox< float >, SSplitter2x2, SSplitter, SSynth2DSlider, SSynthKnob, STabDrawer, STableViewBase, SViewport, SWindow, UE::Sequencer::SChannelView, UE::Sequencer::STrackAreaView, and UE::Sequencer::STrackLane.
References MouseEvent.
Referenced by SBorder::SLATE_EVENT().
OnMouseWheel()
virtual FReply SWidget::OnMouseWheel (const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) virtual
Called when the mouse wheel is spun.
This event is bubbled.
Parameters
MouseEvent Mouse event
Returns
Returns whether the event was handled, along with other possible actions
Reimplemented in SDesignSurface, SGraphNodeDocumentation, SInteractiveCurveEditorView, SKeySelector, SNodePanel, SScrollBox, SSpinBox< NumericType >, SSpinBox< float >, STableViewBase, SViewport, and UE::Sequencer::STrackAreaView.
References MouseEvent.
OnNavigation()
virtual FNavigationReply SWidget::OnNavigation (const FGeometry & MyGeometry, const FNavigationEvent & InNavigationEvent) virtual
Called when navigation is requested e.g.
Left Joystick, Direction Pad, Arrow Keys can generate navigation events.
Parameters
InNavigationEvent The navigation event generated
Reimplemented in SAnalogSlider, SCommonHierarchicalScrollBox, SInputKeySelector, SListView< ItemType >, SListView< FCurveEditorTreeItemID >, SListView< FName >, SListView< FSCSEditorTreeNodePtrType >, SListView< ListType >, SListView< OptionType >, SListView< TSharedPtr< class FComponentClassComboEntry > >, SListView< TSharedPtr< class FDebugLineItem > >, SListView< TSharedPtr< class FFilterConfiguratorNode > >, SListView< TSharedPtr< class FTableTreeNode > >, SListView< TSharedPtr< const FCollectionSpreadSheetItem > >, SListView< TSharedPtr< const FSelectionViewItem > >, SListView< TSharedPtr< EAudioOscilloscopeTriggerMode > >, SListView< TSharedPtr< ECSVImportType > >, SListView< TSharedPtr< ERichCurveInterpMode > >, SListView< TSharedPtr< FAnimAttributeEntry > >, SListView< TSharedPtr< FBlueprintDebugObjectInstance > >, SListView< TSharedPtr< FBlueprintDifferenceTreeEntry > >, SListView< TSharedPtr< FDataflowOutlinerTreeItem > >, SListView< TSharedPtr< FDisplayedBoneMappingInfo > >, SListView< TSharedPtr< FGeometryCollectionFacesTreeItem > >, SListView< TSharedPtr< FGeometryCollectionVerticesTreeItem > >, SListView< TSharedPtr< FGraphActionNode > >, SListView< TSharedPtr< FName > >, SListView< TSharedPtr< FPendingDelete > >, SListView< TSharedPtr< FPendingPrivateAsset > >, SListView< TSharedPtr< FRigStackEntry > >, SListView< TSharedPtr< FRigVMDebugObjectInstance > >, SListView< TSharedPtr< FRigVMEditorGraphExplorerTreeElement > >, SListView< TSharedPtr< FRigVMStringWithTag > >, SListView< TSharedPtr< FSequencerFilterSuggestionListEntryBase > >, SListView< TSharedPtr< FString > >, SListView< TSharedPtr< FText > >, SListView< TSharedPtr< int32 > >, SListView< TSharedPtr< SBlueprintNamespaceEntry::FPathTreeNodeItem > >, SListView< TSharedPtr< SBoneTreeMenu::FBoneNameInfo > >, SListView< TSharedPtr< SReadOnlyHierarchyView::FItem > >, SListView< TSharedPtr< SRigVMNodeLayoutWidget::FNodeLayoutRow > >, SListView< TSharedPtr< SRigVMVariantWidget::FVariantTreeRowInfo > >, SListView< TSharedPtr< UE::Insights::FFilter > >, SListView< TSharedPtr< UE::Insights::FFilterGroupOperator > >, SListView< TSharedPtr< UE::Insights::IFilterOperator > >, SListView< TSharedRef< FRigVMTreeNode > >, SListView< TSharedRef< UE::Insights::ITableTreeViewPreset > >, SListView< TWeakPtr< FViewModel > >, SListView< TWeakViewModelPtr< IOutlinerExtension > >, SListView< UObject * >, SScrollBox, SSlider, STileView< ItemType >, and SViewport.
Referenced by SListView< TSharedPtr< FString > >::OnNavigation().
OnPaint()
virtual int32 SWidget::OnPaint (const FPaintArgs & Args, const FGeometry & AllottedGeometry, const FSlateRect & MyCullingRect, FSlateWindowElementList & OutDrawElements, int32 LayerId, const FWidgetStyle & InWidgetStyle, bool bParentEnabled) const private pure virtual
The widget should respond by populating the OutDrawElements array with FDrawElements that represent it and any of its children.
Called by the non-virtual OnPaint to enforce pre/post conditions during OnPaint.
Parameters
Args All the arguments necessary to paint this widget (
Todo
umg: move all params into this struct)
Parameters
AllottedGeometry The FGeometry that describes an area in which the widget should appear.
MyCullingRect The rectangle representing the bounds currently being used to completely cull widgets. Unless IsChildWidgetCulled(...) returns true, you should paint the widget.
OutDrawElements A list of FDrawElements to populate with the output.
LayerId The Layer onto which this widget should be rendered.
InColorAndOpacity Color and Opacity to be applied to all the descendants of the widget being painted
bParentEnabled True if the parent of this widget is enabled.
Returns
The maximum layer ID attained by this widget or any of its children.
Implemented in FArguments< ItemType >, PropertyInfoViewStyle::SIndent, SAudioMaterialButton, SAudioMaterialEnvelope, SAudioMaterialKnob, SAudioMaterialMeter, SAudioMaterialSlider, SAudioMeter, SAudioSpectrogram, SAudioSpectrumPlot, SBackgroundBlur, SBorder, SBox, SButton, SCanvas, SCircularThrobber, SColorBlock, SColorGradientEditor, SColorSpectrum, SColorWheel, SCommonAnimatedSwitcher, SComplexGradient, SCompoundWidget, SConstraintCanvas, SCurveViewerPanel, SDebugCanvas, SDesignSurface, SDetailsSplitter, SDragAndDropVerticalBox, SEditableText, SEnableBox, SExpanderArrow, SFixedSampledSequenceRuler, SFixedSampledSequenceVectorViewer, SFixedSampledSequenceViewer, SFxWidget, SGameLayerManager, SGraphPanel, SGridPanel, SImage, SInteractiveCurveEditorView, SInvalidationPanel, SLayeredImage, SLeafWidget, SNodePanel::SNode, SNotificationBackground, SOverlay, SPanel, SPlayheadOverlay, SPopup, SProgressBar, SResponsiveGridPanel, SSampledSequenceValueGridOverlay, SScaleBox, SScissorRectBox, SScrollBox, SSimpleGradient, SSlider, SSpacer, SSpinBox< NumericType >, SSpinBox< float >, SSpinningImage, SSplitter2x2, SSplitter, SSynth2DSlider, SSynthKnob, STabDrawer, STableRow< ItemType >, STableRow< FDataflowOutlinerTreeItemBonePtr >, STableRow< FDisplayedBoneMappingInfoPtr >, STableRow< FFilterConfiguratorNodePtr >, STableRow< FGeometryCollectionFacesTreeItemFacePtr >, STableRow< FGeometryCollectionVerticesTreeItemVertexPtr >, STableRow< FNavigationToolItemPtr >, STableRow< FSCSEditorTreeNodePtrType >, STableRow< FTableTreeNodePtr >, STableRow< TSharedPtr< const FCollectionSpreadSheetItem > >, STableRow< TSharedPtr< const FSelectionViewItem > >, STableRow< TSharedPtr< FAnimAttributeEntry > >, STableRow< TSharedPtr< FBoneTrackPair > >, STableRow< TSharedPtr< FNodeLayoutRow > >, STableRow< TSharedPtr< FRigStackEntry > >, STableRow< TSharedPtr< FRigVMEditorGraphExplorerTreeElement > >, STableRow< TSharedPtr< FRigVMVariableMappingInfoPtr > >, STableRow< TSharedPtr< FVariantTreeRowInfo > >, STableRow< TSharedPtr< SRigVMGraphFunctionLocalizationItem > >, STableRow< TSharedRef< FRigVMTreeNode > >, STableRow< TWeakViewModelPtr< IOutlinerExtension > >, STableViewBase, STextBlock, STextScroller, STriggerThresholdLineWidget, SViewport, SVirtualJoystick, SVirtualKeyboardEntry, SVirtualWindow, SVisualAttachmentBox, SWeakWidget, SWindow, SWindowTitleBarArea, UE::Sequencer::SChannelView, UE::Sequencer::SCompoundTrackLaneView, UE::Sequencer::SOutlinerView, UE::Sequencer::SOutlinerViewRow, UE::Sequencer::STrackAreaView, and UE::Sequencer::STrackLane.
References FSlateWindowElementList.
OnPreviewKeyDown()
virtual FReply SWidget::OnPreviewKeyDown (const FGeometry & MyGeometry, const FKeyEvent & InKeyEvent) virtual
Called after a key is pressed when this widget or a child of this widget has focus If a widget handles this event, OnKeyDown will not be passed to the focused widget.
This event is primarily to allow parent widgets to consume an event before a child widget processes it and it should be used only when there is no better design alternative.
Parameters
MyGeometry The Geometry of the widget receiving the event
InKeyEvent Key event
Returns
Returns whether the event was handled, along with other possible actions
Reimplemented in SInputKeySelector, and SSequencerSearchBox.
OnPreviewMouseButtonDown()
virtual FReply SWidget::OnPreviewMouseButtonDown (const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) virtual
Just like OnMouseButtonDown, but tunnels instead of bubbling.
If this event is handled, OnMouseButtonDown will not be sent.
Use this event sparingly as preview events generally make UIs more difficult to reason about.
Reimplemented in SInputKeySelector, SScrollBox, and STableViewBase.
References MouseEvent.
OnQueryPopupMethod()
virtual FPopupMethodReply SWidget::OnQueryPopupMethod () const virtual
Popups can manifest in a NEW OS WINDOW or via an OVERLAY in an existing window.
This can be set explicitly on SMenuAnchor, or can be determined by a scoping widget. A scoping widget can reply to OnQueryPopupMethod() to drive all its descendants' poup methods.
e.g. Fullscreen games cannot summon a new window, so game SViewports will reply with EPopupMethod::UserCurrentWindow. This makes all the menu anchors within them use the current window.
Reimplemented in SViewport, and SVirtualWindow.
OnQueryShowFocus()
virtual TOptional< bool > SWidget::OnQueryShowFocus (const EFocusCause InFocusCause) const virtual
Called to determine if we should render the focus brush.
Parameters
InFocusCause The cause of focus
Reimplemented in SViewport.
OnToolTipClosing()
virtual void SWidget::OnToolTipClosing () virtual
Called when a tooltip displayed from this widget is being closed.
Reimplemented in SGraphNode.
OnTouchEnded()
virtual FReply SWidget::OnTouchEnded (const FGeometry & MyGeometry, const FPointerEvent & InTouchEvent) virtual
Called when a touchpad touch is ended (finger lifted)
Parameters
InTouchEvent The touch event generated
Reimplemented in FArguments< ItemType >, SCommonListView< ItemType >, SCommonTreeView< ItemType >, SDesignSurface, SDockTab, SNodePanel, SScrollBox, SSlider, STableRow< ItemType >, STableRow< FDataflowOutlinerTreeItemBonePtr >, STableRow< FDisplayedBoneMappingInfoPtr >, STableRow< FFilterConfiguratorNodePtr >, STableRow< FGeometryCollectionFacesTreeItemFacePtr >, STableRow< FGeometryCollectionVerticesTreeItemVertexPtr >, STableRow< FNavigationToolItemPtr >, STableRow< FSCSEditorTreeNodePtrType >, STableRow< FTableTreeNodePtr >, STableRow< TSharedPtr< const FCollectionSpreadSheetItem > >, STableRow< TSharedPtr< const FSelectionViewItem > >, STableRow< TSharedPtr< FAnimAttributeEntry > >, STableRow< TSharedPtr< FBoneTrackPair > >, STableRow< TSharedPtr< FNodeLayoutRow > >, STableRow< TSharedPtr< FRigStackEntry > >, STableRow< TSharedPtr< FRigVMEditorGraphExplorerTreeElement > >, STableRow< TSharedPtr< FRigVMVariableMappingInfoPtr > >, STableRow< TSharedPtr< FVariantTreeRowInfo > >, STableRow< TSharedPtr< SRigVMGraphFunctionLocalizationItem > >, STableRow< TSharedRef< FRigVMTreeNode > >, STableRow< TWeakViewModelPtr< IOutlinerExtension > >, STableViewBase, SViewport, and SVirtualJoystick.
OnTouchFirstMove()
virtual FReply SWidget::OnTouchFirstMove (const FGeometry & MyGeometry, const FPointerEvent & TouchEvent) virtual
Called when a touchpad touch first moves after TouchStarted.
Parameters
InTouchEvent The touch event generated
Reimplemented in SViewport.
OnTouchForceChanged()
virtual FReply SWidget::OnTouchForceChanged (const FGeometry & MyGeometry, const FPointerEvent & TouchEvent) virtual
Called when a touchpad touch force changes.
Parameters
InTouchEvent The touch event generated
Reimplemented in SViewport.
OnTouchGesture()
virtual FReply SWidget::OnTouchGesture (const FGeometry & MyGeometry, const FPointerEvent & GestureEvent) virtual
Called when the user performs a gesture on trackpad.
This event is bubbled.
Parameters
GestureEvent gesture event
Returns
Returns whether the event was handled, along with other possible actions
Reimplemented in SDesignSurface, SNodePanel, and SViewport.
OnTouchMoved()
virtual FReply SWidget::OnTouchMoved (const FGeometry & MyGeometry, const FPointerEvent & InTouchEvent) virtual
Called when a touchpad touch is moved (finger moved)
Parameters
InTouchEvent The touch event generated
Reimplemented in SCommonListView< ItemType >, SCommonTileView< ItemType >, SCommonTreeView< ItemType >, SSlider, STableViewBase, SViewport, and SVirtualJoystick.
OnTouchStarted()
virtual FReply SWidget::OnTouchStarted (const FGeometry & MyGeometry, const FPointerEvent & InTouchEvent) virtual
Called when a touchpad touch is started (finger down)
Parameters
InTouchEvent The touch event generated
Reimplemented in FArguments< ItemType >, SDockTab, SSlider, STableRow< ItemType >, STableRow< FDataflowOutlinerTreeItemBonePtr >, STableRow< FDisplayedBoneMappingInfoPtr >, STableRow< FFilterConfiguratorNodePtr >, STableRow< FGeometryCollectionFacesTreeItemFacePtr >, STableRow< FGeometryCollectionVerticesTreeItemVertexPtr >, STableRow< FNavigationToolItemPtr >, STableRow< FSCSEditorTreeNodePtrType >, STableRow< FTableTreeNodePtr >, STableRow< TSharedPtr< const FCollectionSpreadSheetItem > >, STableRow< TSharedPtr< const FSelectionViewItem > >, STableRow< TSharedPtr< FAnimAttributeEntry > >, STableRow< TSharedPtr< FBoneTrackPair > >, STableRow< TSharedPtr< FNodeLayoutRow > >, STableRow< TSharedPtr< FRigStackEntry > >, STableRow< TSharedPtr< FRigVMEditorGraphExplorerTreeElement > >, STableRow< TSharedPtr< FRigVMVariableMappingInfoPtr > >, STableRow< TSharedPtr< FVariantTreeRowInfo > >, STableRow< TSharedPtr< SRigVMGraphFunctionLocalizationItem > >, STableRow< TSharedRef< FRigVMTreeNode > >, STableRow< TWeakViewModelPtr< IOutlinerExtension > >, STableViewBase, SViewport, and SVirtualJoystick.
OnVisualizePopup()
virtual TSharedPtr< FPopupLayer > SWidget::OnVisualizePopup (const TSharedRef< SWidget > & PopupContent) virtual
Visualize a new pop-up if possible.
If it's not possible for this widget to host the pop-up content you'll get back an invalid pointer to the layer. The returned FPopupLayer allows you to remove the pop-up when you're done with it
Parameters
PopupContent The widget to try and host overlaid on top of the widget.
Returns
a valid FPopupLayer if this widget supported hosting it. You can call Remove() on this to destroy the pop-up.
Reimplemented in SWindow.
OnVisualizeTooltip()
virtual bool SWidget::OnVisualizeTooltip (const TSharedPtr< SWidget > & TooltipContent) virtual
Called when Slate wants to visualize tooltip.
If nobody handles this event, Slate will use default tooltip visualization. If you override this event, you should probably return true.
Parameters
TooltipContent The TooltipContent that I may want to visualize.
Returns
true if this widget visualized the tooltip content; i.e., the event is handled.
Reimplemented in SGameLayerManager, SMultiBoxWidget, and SVirtualWindow.
Paint()
int32 SWidget::Paint (const FPaintArgs & Args, const FGeometry & AllottedGeometry, const FSlateRect & MyCullingRect, FSlateWindowElementList & OutDrawElements, int32 LayerId, const FWidgetStyle & InWidgetStyle, bool bParentEnabled) const
Called to tell a widget to paint itself (and it's children).
The widget should respond by populating the OutDrawElements array with FDrawElements that represent it and any of its children.
Parameters
Args All the arguments necessary to paint this widget (
Todo
umg: move all params into this struct)
Parameters
AllottedGeometry The FGeometry that describes an area in which the widget should appear.
MyCullingRect The clipping rectangle allocated for this widget and its children.
OutDrawElements A list of FDrawElements to populate with the output.
LayerId The Layer onto which this widget should be rendered.
InColorAndOpacity Color and Opacity to be applied to all the descendants of the widget being painted
bParentEnabled True if the parent of this widget is enabled.
Returns
The maximum layer ID attained by this widget or any of its children.
References FSlateWindowElementList.
Referenced by SNodePanel::SNode::OnPaint().
Prepass_ChildLoop()
void SWidget::Prepass_ChildLoop (float InLayoutScaleMultiplier, FChildren * MyChildren) protected
Prepass_Internal()
void SWidget::Prepass_Internal (float LayoutScaleMultiplier) private
RegisterActiveTimer()
TSharedRef< FActiveTimerHandle > SWidget::RegisterActiveTimer (float TickPeriod, FWidgetActiveTimerDelegate TickFunction)
Registers an "active timer" delegate that will execute at some regular interval.
TickFunction will not be called until the specified interval has elapsed once. A widget can register as many delegates as it needs. Be careful when registering to avoid duplicate active timers.
An active timer can be UnRegistered in one of three ways:
Call UnRegisterActiveTimer using the active timer handle that is returned here.
Have your delegate return EActiveTimerReturnType::Stop.
Destroying the widget
Active Timers
Slate may go to sleep when there is no user interaction for some time to save power. However, some UI elements may need to "drive" the UI even when the user is not providing any input (ie, animations, viewport rendering, async polling, etc). A widget notifies Slate of this by registering an "Active Timer" that is executed at a specified frequency to drive the UI. In this way, slate can go to sleep when there is no input and no active timer needs to fire. When any active timer needs to fire, all of Slate will do a Tick and Paint pass.
Parameters
Period The time period to wait between each execution of the timer. Pass zero to fire the timer once per frame. If an interval is missed, the delegate is NOT called more than once.
TimerFunction The active timer delegate to call every Period seconds.
Returns
An active timer handle that can be used to UnRegister later.
RemoveAllMetaData()
template<typename MetaDataType> int32 SWidget::RemoveAllMetaData () inline private
Definition at line 1394 of file SWidget.h.
References checkf, HasRegisteredSlateAttribute(), MetaData, and TEXT.
RemoveMetaData() [1/2]
template<typename MetaDataType> bool SWidget::RemoveMetaData () inline private
Definition at line 1410 of file SWidget.h.
References checkf, HasRegisteredSlateAttribute(), MetaData, and TEXT.
RemoveMetaData() [2/2]
template<typename MetaDataType> int32 SWidget::RemoveMetaData (const TSharedRef< MetaDataType > & RemoveMe) inline
Remove metadata to this widget.
Returns
Number of removed elements.
Definition at line 1376 of file SWidget.h.
References checkf, HasRegisteredSlateAttribute(), INDEX_NONE, MetaData, and TEXT.
RemoveUpdateFlags()
void SWidget::RemoveUpdateFlags (EWidgetUpdateFlags FlagsToRemove) inline private
Definition at line 755 of file SWidget.h.
References FastPathProxyHandle, and UpdateFlags.
Referenced by SetCanTick(), and SetVolatilePrepass().
SetAttribute()
template<typename TargetValueType, typename SourceValueType> bool SWidget::SetAttribute (TAttribute< TargetValueType > & TargetValue, const TAttribute< SourceValueType > & SourceValue, EInvalidateWidgetReason BaseInvalidationReason) inline protected
Performs the attribute assignment and invalidates the widget minimally based on what actually changed.
So if the boundness of the attribute didn't change volatility won't need to be recalculated. Returns true if the value changed.
Definition at line 1684 of file SWidget.h.
References SetWidgetAttribute().
SetCanTick()
void SWidget::SetCanTick (bool bInCanTick) inline
Definition at line 662 of file SWidget.h.
References AddUpdateFlags(), NeedsTick, and RemoveUpdateFlags().
Referenced by SHorizontalBox::SHorizontalBox(), SStackBox::SStackBox(), SVerticalBox::SVerticalBox(), SAppIconWidget::SLATE_ATTRIBUTE(), and SPopup::SLATE_DEFAULT_SLOT().
SetClipping()
void SWidget::SetClipping (EWidgetClipping InClipping)
Sets the clipping to bounds rules for this widget.
Referenced by SMultiColumnTableRow< ItemType >::GenerateColumns().
SetCullingBoundsExtension()
FORCEINLINE void SWidget::SetCullingBoundsExtension (const FMargin & InCullingBoundsExtension) inline
Sets an additional culling padding that is added to a widget to give more leeway when culling widgets.
Useful if several child widgets have rendering beyond their bounds.
Definition at line 1246 of file SWidget.h.
References CullingBoundsExtension, FORCEINLINE, Invalidate(), and Layout.
SetCursor()
void SWidget::SetCursor (const TAttribute< TOptional< EMouseCursor::Type > > & InCursor)
Set the cursor that should appear when this widget is hovered.
SetDebugInfo()
void SWidget::SetDebugInfo (const ANSICHAR * InType, const ANSICHAR * InFile, int32 OnLine, size_t InAllocSize) protected
Used by Slate to set the runtime debug info about this widget.
SetDesiredSize()
void SWidget::SetDesiredSize (const FVector2D & InDesiredSize) inline private
Explicitly set the desired size.
This is highly advanced functionality that is meant to be used in conjunction with overriding CacheDesiredSize. Use ComputeDesiredSize() instead.
Definition at line 738 of file SWidget.h.
References bDesiredSizeSet, and DesiredSize.
SetEnabled()
void SWidget::SetEnabled (TAttribute< bool > InEnabledState) inline
Sets the enabled state of this widget.
Parameters
InEnabledState An attribute containing the enabled state or a delegate to call to get the enabled state.
Definition at line 925 of file SWidget.h.
References EnabledStateAttribute, and MoveTemp().
SetFastPathProxyHandle() [1/2]
void SWidget::SetFastPathProxyHandle (const FWidgetProxyHandle & Handle) inline private
Definition at line 726 of file SWidget.h.
References FastPathProxyHandle, and Handle.
SetFastPathProxyHandle() [2/2]
void SWidget::SetFastPathProxyHandle (const FWidgetProxyHandle & Handle, FSlateInvalidationWidgetVisibility Visibility, bool bParentVolatile) private
References Handle, and Visibility.
SetFastPathSortOrder()
void SWidget::SetFastPathSortOrder (const FSlateInvalidationWidgetSortOrder SortOrder) private
SetFlowDirectionPreference()
void SWidget::SetFlowDirectionPreference (EFlowDirectionPreference InFlowDirectionPreference) inline
Sets how content should flow in this panel, based on the current culture.
By default all panels inherit the state of the widget above. If they set a new flow direction it will be inherited down the tree.
Definition at line 1266 of file SWidget.h.
References FlowDirectionPreference, Invalidate(), and Paint.
SetHover()
void SWidget::SetHover (TAttribute< bool > InHovered) inline protected
Set the hover state.
Once set, the attribute that the ownership and SWidget code will not update the attribute value. You can return the control to the SWidget code by setting an empty TAttribute.
Definition at line 980 of file SWidget.h.
References bIsHoveredAttributeSet, HoveredAttribute, TAttribute< ObjectType >::IsSet(), and MoveTemp().
SetOnMouseButtonDown()
void SWidget::SetOnMouseButtonDown (FPointerEventHandler EventHandler)
See OnMouseButtonDown event.
SetOnMouseButtonUp()
void SWidget::SetOnMouseButtonUp (FPointerEventHandler EventHandler)
See OnMouseButtonUp event.
SetOnMouseDoubleClick()
void SWidget::SetOnMouseDoubleClick (FPointerEventHandler EventHandler)
See OnMouseDoubleClick event.
SetOnMouseEnter()
void SWidget::SetOnMouseEnter (FNoReplyPointerEventHandler EventHandler)
See OnMouseEnter event.
SetOnMouseLeave()
void SWidget::SetOnMouseLeave (FSimpleNoReplyPointerEventHandler EventHandler)
See OnMouseLeave event.
SetOnMouseMove()
void SWidget::SetOnMouseMove (FPointerEventHandler EventHandler)
See OnMouseMove event.
SetPixelSnapping()
void SWidget::SetPixelSnapping (EWidgetPixelSnapping InPixelSnappingMethod)
Sets the pixel snapping method for this widget.
SetRenderOpacity()
FORCEINLINE void SWidget::SetRenderOpacity (float InRenderOpacity) inline
Parameters
InOpacity The opacity of the widget during rendering.
Definition at line 1147 of file SWidget.h.
References FORCEINLINE, Invalidate(), Paint, and RenderOpacity.
SetRenderTransform()
FORCEINLINE void SWidget::SetRenderTransform (TAttribute< TOptional< FSlateRenderTransform > > InTransform) inline
Parameters
InTransform the render transform to set for the widget (transforms from widget's local space). TOptional<> to allow code to skip expensive overhead if there is no render transform applied.
Definition at line 1202 of file SWidget.h.
References FORCEINLINE, MoveTemp(), and RenderTransformAttribute.
SetRenderTransformPivot()
FORCEINLINE void SWidget::SetRenderTransformPivot (TAttribute< FVector2D > InTransformPivot) inline
Parameters
InTransformPivot Sets the pivot point of the widget's render transform (in normalized local space).
Definition at line 1215 of file SWidget.h.
References FORCEINLINE, MoveTemp(), and RenderTransformPivotAttribute.
SetTag()
FORCEINLINE void SWidget::SetTag (FName InTag) inline
Definition at line 1156 of file SWidget.h.
References FORCEINLINE, and Tag.
SetToolTip()
void SWidget::SetToolTip (const TAttribute< TSharedPtr< IToolTip > > & InToolTip)
Set the tool tip that should appear when this widget is hovered.
SetToolTipText() [1/2]
void SWidget::SetToolTipText (const FText & InToolTipText)
Set the tool tip that should appear when this widget is hovered.
SetToolTipText() [2/2]
void SWidget::SetToolTipText (const TAttribute< FText > & ToolTipText)
Set the tool tip that should appear when this widget is hovered.
SetVisibility()
virtual void SWidget::SetVisibility (TAttribute< EVisibility > InVisibility) virtual
Parameters
InVisibility should this widget be
Reimplemented in SCompoundWidget, SLeafWidget, and SPanel.
References Main.
SetVolatilePrepass()
void SWidget::SetVolatilePrepass (bool bVolatile) inline protected
Definition at line 699 of file SWidget.h.
References AddUpdateFlags(), NeedsVolatilePrepass, and RemoveUpdateFlags().
ShouldBeEnabled()
bool SWidget::ShouldBeEnabled (bool InParentEnabled) const inline protected
Determines if this widget should be enabled.
Parameters
InParentEnabled true if the parent of this widget is enabled
Returns
true if the widget is enabled
Definition at line 1568 of file SWidget.h.
References IsEnabled().
Referenced by SNodePanel::SNode::OnPaint().
ShouldInvalidatePrepassDueToVolatility()
FORCEINLINE bool SWidget::ShouldInvalidatePrepassDueToVolatility () inline
Definition at line 1084 of file SWidget.h.
References bVolatilityAlwaysInvalidatesPrepass, and FORCEINLINE.
SLATE_DECLARE_WIDGET_API()
SWidget::SLATE_DECLARE_WIDGET_API (SWidget , FSlateControlledConstruction , 1) private
References FSlateControlledConstruction::FSlateControlledConstruction(), and SWidget().
SlatePrepass() [1/2]
void SWidget::SlatePrepass ()
DEPRECATED version of SlatePrepass that assumes no scaling beyond AppScale.
Referenced by SListView< TSharedPtr< FString > >::GeneratePinnedWidgetForItem().
SlatePrepass() [2/2]
void SWidget::SlatePrepass (float InLayoutScaleMultiplier)
Descends to leaf-most widgets in the hierarchy and gathers desired sizes on the way up.
i.e. Caches the desired size of all of this widget's children recursively, then caches desired size for itself.
SupportsKeyboardFocus()
virtual bool SWidget::SupportsKeyboardFocus () const virtual
Checks to see if this widget supports keyboard focus.
Override this in derived classes.
Returns
True if this widget can take keyboard focus
Reimplemented in SAudioMaterialKnob, SAudioMaterialSlider, SButton, SCheckBox, SColorGradientEditor, SCurveEditorPanel, SCurveEditorTreeTextFilter, SDesignSurface, SEditableText, SEditableTextBox, SEditorViewport, SGlobalPlayWorldActions, SGraphPanel, SInputKeySelector, SKeySelector, SListView< ItemType >, SListView< FCurveEditorTreeItemID >, SListView< FName >, SListView< FSCSEditorTreeNodePtrType >, SListView< ListType >, SListView< OptionType >, SListView< TSharedPtr< class FComponentClassComboEntry > >, SListView< TSharedPtr< class FDebugLineItem > >, SListView< TSharedPtr< class FFilterConfiguratorNode > >, SListView< TSharedPtr< class FTableTreeNode > >, SListView< TSharedPtr< const FCollectionSpreadSheetItem > >, SListView< TSharedPtr< const FSelectionViewItem > >, SListView< TSharedPtr< EAudioOscilloscopeTriggerMode > >, SListView< TSharedPtr< ECSVImportType > >, SListView< TSharedPtr< ERichCurveInterpMode > >, SListView< TSharedPtr< FAnimAttributeEntry > >, SListView< TSharedPtr< FBlueprintDebugObjectInstance > >, SListView< TSharedPtr< FBlueprintDifferenceTreeEntry > >, SListView< TSharedPtr< FDataflowOutlinerTreeItem > >, SListView< TSharedPtr< FDisplayedBoneMappingInfo > >, SListView< TSharedPtr< FGeometryCollectionFacesTreeItem > >, SListView< TSharedPtr< FGeometryCollectionVerticesTreeItem > >, SListView< TSharedPtr< FGraphActionNode > >, SListView< TSharedPtr< FName > >, SListView< TSharedPtr< FPendingDelete > >, SListView< TSharedPtr< FPendingPrivateAsset > >, SListView< TSharedPtr< FRigStackEntry > >, SListView< TSharedPtr< FRigVMDebugObjectInstance > >, SListView< TSharedPtr< FRigVMEditorGraphExplorerTreeElement > >, SListView< TSharedPtr< FRigVMStringWithTag > >, SListView< TSharedPtr< FSequencerFilterSuggestionListEntryBase > >, SListView< TSharedPtr< FString > >, SListView< TSharedPtr< FText > >, SListView< TSharedPtr< int32 > >, SListView< TSharedPtr< SBlueprintNamespaceEntry::FPathTreeNodeItem > >, SListView< TSharedPtr< SBoneTreeMenu::FBoneNameInfo > >, SListView< TSharedPtr< SReadOnlyHierarchyView::FItem > >, SListView< TSharedPtr< SRigVMNodeLayoutWidget::FNodeLayoutRow > >, SListView< TSharedPtr< SRigVMVariantWidget::FVariantTreeRowInfo > >, SListView< TSharedPtr< UE::Insights::FFilter > >, SListView< TSharedPtr< UE::Insights::FFilterGroupOperator > >, SListView< TSharedPtr< UE::Insights::IFilterOperator > >, SListView< TSharedRef< FRigVMTreeNode > >, SListView< TSharedRef< UE::Insights::ITableTreeViewPreset > >, SListView< TWeakPtr< FViewModel > >, SListView< TWeakViewModelPtr< IOutlinerExtension > >, SListView< UObject * >, SMultiBoxWidget, SNumericEntryBox< NumericType >, SOutputLogDialog, SScrollBox, SSequencerSearchBox, SSlider, SSpinBox< NumericType >, SSpinBox< float >, SSuggestionTextBox, SSynth2DSlider, SSynthKnob, STabDrawer, STableViewBase, SViewport, SVirtualJoystick, SVirtualKeyboardEntry, SVirtualWindow, SWindow, and UE::Sequencer::STrackAreaView.
SWidgetConstruct()
void SWidget::SWidgetConstruct (const FSlateBaseNamedArgs & Args) protected
Construct a SWidget based on initial parameters.
Tick()
virtual void SWidget::Tick (const FGeometry & AllottedGeometry, const double InCurrentTime, const float InDeltaTime) virtual
Ticks this widget with Geometry.
Override in derived classes, but always call the parent implementation.
Parameters
AllottedGeometry The space allotted for this widget
InCurrentTime Current absolute real time
InDeltaTime Real time passed since last tick
Reimplemented in FOnSelectionChanged<>, SActorEditorContext, SAnimAttributeView, SAnimAttributeViewer, SAssetEditorViewportsOverlay, SAudioOscilloscopePanelWidget, SBlueprintDiff, SBlueprintEditorSelectedDebugObjectWidget, SCommentBubble, SCurveEditorEventChannelView, SCurveEditorKeyBarView, SCurveEditorPanel, SCurveEditorTreeFilterStatusBar, SCurveEditorView, SCurveEditorViewNormalized, SCurveEditorViewStacked, SCurveViewerPanel, SDesignerView, SDesignSurface, SDetailsDiff, SEditableText, SEditorViewport, SFixedSampledSequenceViewer, SFixedSampledSequenceViewerPanel, SGameLayerManager, SGraphNode, SGraphNodeComment, SGraphNodeDocumentation, SGraphPin, SInteractiveCurveEditorView, SKismetDebugTreeView, SKismetInspector, SMyBlueprint, SNodePanel, SNodeTitle, SNumericEntryBox< NumericType >, SRadialBox, SResetToDefaultMenu, SResetToDefaultPropertyEditor, SRigVMActionMenu, SRigVMBulkEditWidget, SRigVMChangesTreeView, SRigVMDetailsInspector, SRigVMEditorGraphExplorer, SRigVMEditorSelectedDebugObjectWidget, SRigVMGraphNode, SRigVMGraphNodeComment, SRigVMGraphPinCurveFloat, SRigVMNodeLayoutWidget, SRigVMNodePreviewWidget, SRigVMVariantTagWidget, SRigVMVariantWidget, SSampledSequenceValueGridOverlay, SScrollBar, SScrollBox, SSpinBox< NumericType >, SSpinBox< float >, STableViewBase, STreeView< ItemType >, STreeView< FCurveEditorTreeItemID >, STreeView< FKeyTreeItem >, STreeView< FReferenceTreeItemPtr >, STreeView< FRigVMSearchResult >, STreeView< FSCSEditorTreeNodePtrType >, STreeView< FSearchResult >, STreeView< TSharedPtr< class FDebugLineItem > >, STreeView< TSharedPtr< class FFilterConfiguratorNode > >, STreeView< TSharedPtr< class FTableTreeNode > >, STreeView< TSharedPtr< FBlueprintDifferenceTreeEntry > >, STreeView< TSharedPtr< FDataflowOutlinerTreeItem > >, STreeView< TSharedPtr< FGeometryCollectionFacesTreeItem > >, STreeView< TSharedPtr< FGeometryCollectionVerticesTreeItem > >, STreeView< TSharedPtr< FGraphActionNode > >, STreeView< TSharedPtr< FRigStackEntry > >, STreeView< TSharedPtr< FRigVMEditorGraphExplorerTreeElement > >, STreeView< TSharedPtr< FRigVMVariableMappingInfo > >, STreeView< TSharedPtr< SBlueprintNamespaceEntry::FPathTreeNodeItem > >, STreeView< TSharedPtr< SBoneTreeMenu::FBoneNameInfo > >, STreeView< TSharedPtr< SReadOnlyHierarchyView::FItem > >, STreeView< TSharedPtr< SRigVMNodeLayoutWidget::FNodeLayoutRow > >, STreeView< TSharedPtr< SRigVMVariantWidget::FVariantTreeRowInfo > >, STreeView< TSharedRef< FRigVMTreeNode > >, STreeView< TWeakPtr< FViewModel > >, STreeView< TWeakViewModelPtr< IOutlinerExtension > >, SViewport, SVirtualJoystick, SVirtualKeyboardEntry, SVPBookmarkListView, SWindow, SWrapBox, UE::Insights::STableTreeView, UE::Sequencer::SColumnToggleWidget, UE::Sequencer::SOutlinerView, UE::Sequencer::SOutlinerViewRow, UE::Sequencer::STrackAreaView, and UE::Sequencer::STrackLane.
Referenced by SRigVMActionMenu::Tick().
ToString()
virtual FString SWidget::ToString () const virtual
Returns
A String representation of the widget
Reimplemented in SWindow.
Referenced by SNumericRotatorInputBox< float >::ConstructPitch(), SNumericRotatorInputBox< float >::ConstructRoll(), and SNumericRotatorInputBox< float >::ConstructYaw().
TranslateMouseCoordinateForCustomHitTestChild()
virtual TOptional< FVirtualPointerPosition > SWidget::TranslateMouseCoordinateForCustomHitTestChild (const SWidget & ChildWidget, const FGeometry & MyGeometry, const FVector2D ScreenSpaceMouseCoordinate, const FVector2D LastScreenSpaceMouseCoordinate) const virtual
Reimplemented in SViewport.
References SWidget().
UnRegisterActiveTimer()
void SWidget::UnRegisterActiveTimer (const TSharedRef< FActiveTimerHandle > & ActiveTimerHandle)
Unregisters an active timer handle.
This is optional, as the delegate can UnRegister itself by returning EActiveTimerReturnType::Stop.
UpdateFastPathVisibility()
void SWidget::UpdateFastPathVisibility (FSlateInvalidationWidgetVisibility ParentVisibility, FHittestGrid * ParentHittestGrid) private
UpdateFastPathVolatility()
void SWidget::UpdateFastPathVolatility (bool bParentVolatile) private
UpdateFastPathWidgetRemoved()
void SWidget::UpdateFastPathWidgetRemoved (FHittestGrid * ParentHittestGrid) private
UpdateWidgetProxy()
void SWidget::UpdateWidgetProxy (int32 NewLayerId, FSlateCachedElementsHandle & CacheHandle) private
ValidatePathToChild()
virtual bool SWidget::ValidatePathToChild (SWidget * InChild) inline virtual
Reimplemented in SWidgetSwitcher.
Definition at line 680 of file SWidget.h.
References SWidget().
Friends And Related Symbol Documentation
FSlateAttributeMetaData
friend class FSlateAttributeMetaData friend
Definition at line 160 of file SWidget.h.
References FSlateAttributeMetaData.
Referenced by FSlateAttributeMetaData.
FSlateCachedElementList
friend struct FSlateCachedElementList friend
Definition at line 166 of file SWidget.h.
References FSlateCachedElementList.
Referenced by FSlateCachedElementList.
FSlateInvalidationRoot
friend class FSlateInvalidationRoot friend
Definition at line 161 of file SWidget.h.
References FSlateInvalidationRoot.
Referenced by Advanced_AsInvalidationRoot(), and FSlateInvalidationRoot.
FSlateInvalidationWidgetList
friend class FSlateInvalidationWidgetList friend
Definition at line 162 of file SWidget.h.
References FSlateInvalidationWidgetList.
Referenced by FSlateInvalidationWidgetList.
FSlateTrace
friend class FSlateTrace friend
Definition at line 165 of file SWidget.h.
References FSlateTrace.
Referenced by FSlateTrace.
FSlateWindowElementList
friend class FSlateWindowElementList friend
Definition at line 163 of file SWidget.h.
References FSlateWindowElementList.
Referenced by SInteractiveCurveEditorView::DrawBackground(), SInteractiveCurveEditorView::DrawBufferedCurves(), SAudioSpectrumPlot::DrawCrosshairAndAxisLabels(), SCurveViewerPanel::DrawCurves(), SInteractiveCurveEditorView::DrawCurves(), SColorGradientEditor::DrawGradientStopMark(), SAudioSpectrumPlot::DrawGrid(), SFixedSampledSequenceViewer::DrawGridLines(), SInteractiveCurveEditorView::DrawGridLines(), UE::Sequencer::SChannelView::DrawLane(), SPlayheadOverlay::DrawPlayhead(), SFixedSampledSequenceRuler::DrawPlayheadHandle(), SAudioSpectrumPlot::DrawPowerSpectrum(), SDesignerView::DrawResolution(), SFixedSampledSequenceRuler::DrawRulerTicks(), SAudioSpectrumPlot::DrawSolidBackgroundRectangle(), SFixedSampledSequenceRuler::DrawTickTimeString(), SInteractiveCurveEditorView::DrawValueIndicatorLines(), FSlateWindowElementList, SGridPanel::LayoutDebugPaint(), SResponsiveGridPanel::LayoutDebugPaint(), PropertyInfoViewStyle::SIndent::OnPaint(), SAudioMaterialButton::OnPaint(), SAudioMaterialEnvelope::OnPaint(), SAudioMaterialKnob::OnPaint(), SAudioMaterialMeter::OnPaint(), SAudioMaterialSlider::OnPaint(), SAudioMeter::OnPaint(), SAudioSpectrogram::OnPaint(), SAudioSpectrumPlot::OnPaint(), SBackgroundBlur::OnPaint(), SBorder::OnPaint(), SBox::OnPaint(), SButton::OnPaint(), SCanvas::OnPaint(), SCircularThrobber::OnPaint(), SColorBlock::OnPaint(), SColorGradientEditor::OnPaint(), SColorSpectrum::OnPaint(), SColorWheel::OnPaint(), SCommonAnimatedSwitcher::OnPaint(), SComplexGradient::OnPaint(), SCompoundWidget::OnPaint(), SConstraintCanvas::OnPaint(), SCurveViewerPanel::OnPaint(), SDebugCanvas::OnPaint(), SDesignSurface::OnPaint(), SDetailsSplitter::OnPaint(), SEditableText::OnPaint(), SEnableBox::OnPaint(), SExpanderArrow::OnPaint(), SFixedSampledSequenceRuler::OnPaint(), SFixedSampledSequenceVectorViewer::OnPaint(), SFixedSampledSequenceViewer::OnPaint(), SFxWidget::OnPaint(), SGameLayerManager::OnPaint(), SGraphPanel::OnPaint(), SGridPanel::OnPaint(), SImage::OnPaint(), SInteractiveCurveEditorView::OnPaint(), SInvalidationPanel::OnPaint(), SLayeredImage::OnPaint(), SLeafWidget::OnPaint(), SNodePanel::SNode::OnPaint(), SNotificationBackground::OnPaint(), SOverlay::OnPaint(), SPanel::OnPaint(), SPlayheadOverlay::OnPaint(), SPopup::OnPaint(), SProgressBar::OnPaint(), SResponsiveGridPanel::OnPaint(), SSampledSequenceValueGridOverlay::OnPaint(), SScaleBox::OnPaint(), SScissorRectBox::OnPaint(), SScrollBox::OnPaint(), SSimpleGradient::OnPaint(), SSlider::OnPaint(), SSpacer::OnPaint(), SSpinBox< NumericType >::OnPaint(), SSpinningImage::OnPaint(), SSplitter2x2::OnPaint(), SSplitter::OnPaint(), SSynth2DSlider::OnPaint(), SSynthKnob::OnPaint(), STabDrawer::OnPaint(), STableViewBase::OnPaint(), STextBlock::OnPaint(), STextScroller::OnPaint(), STriggerThresholdLineWidget::OnPaint(), SViewport::OnPaint(), SVirtualJoystick::OnPaint(), SVirtualKeyboardEntry::OnPaint(), SVirtualWindow::OnPaint(), SVisualAttachmentBox::OnPaint(), SWeakWidget::OnPaint(), OnPaint(), SWindow::OnPaint(), SWindowTitleBarArea::OnPaint(), UE::Sequencer::SChannelView::OnPaint(), UE::Sequencer::SCompoundTrackLaneView::OnPaint(), UE::Sequencer::SOutlinerView::OnPaint(), UE::Sequencer::SOutlinerViewRow::OnPaint(), UE::Sequencer::STrackAreaView::OnPaint(), UE::Sequencer::STrackLane::OnPaint(), SDesignerView::OnPaintBackground(), SDesignSurface::OnPaintBackground(), UE::Sequencer::SOutlinerViewRow::OnPaintDropIndicator(), Paint(), SPanel::PaintArrangedChildren(), SDesignSurface::PaintBackgroundAsLines(), SNodePanel::PaintBackgroundAsLines(), SNodePanel::PaintComment(), SDetailsSplitter::PaintCopyPropertyButton(), UE::Sequencer::STrackLane::PaintLaneForeground(), SNodePanel::PaintMarquee(), SDetailsSplitter::PaintPropertyConnector(), SNodePanel::PaintSoftwareCursor(), SNodePanel::PaintSurroundSunkenShadow(), SInteractiveCurveEditorView::PaintView(), SWindow::PaintWindow(), and SInvalidationPanel::UpdateCachePrequisites().
SWindow
friend class SWindow friend
Definition at line 164 of file SWidget.h.
References SWindow.
Referenced by SBlueprintDiff::CreateDiffWindow(), SBlueprintDiff::CreateDiffWindow(), SDockTab::GetParentWindow(), UE::Sequencer::SOutlinerTrackColorPicker::OnColorPickerClosed(), SCurveEditorFilterPanel::OpenDialog(), SWindowTitleBarArea::SetGameWindow(), SGenericDialogWidget::SetWindow(), SBlueprintDiff::SLATE_ARGUMENT(), SDetailsDiff::SLATE_ARGUMENT(), SMiniCurveEditor::SLATE_ARGUMENT(), SWindowTitleBar::SLATE_ATTRIBUTE(), and SWindow.
TSlateDecl
template<class WidgetType, typename RequiredArgsPayloadType> friend struct TSlateDecl friend
Definition at line 168 of file SWidget.h.
References TSlateDecl.
Referenced by TSlateDecl.
Field Documentation
bCachedVolatile
uint8 SWidget::bCachedVolatile private
The last cached volatility of this widget.
Cached so that we don't need to recompute volatility every frame.
Definition at line 1737 of file SWidget.h.
Referenced by CacheVolatility(), and IsVolatile().
bCanHaveChildren
uint8 SWidget::bCanHaveChildren protected
Can the widget ever support children?
This will be false on SLeafWidgets, rather than setting this directly, you should probably inherit from SLeafWidget.
Definition at line 1716 of file SWidget.h.
bCanSupportFocus
uint8 SWidget::bCanSupportFocus protected
Can the widget ever support keyboard focus.
Definition at line 1710 of file SWidget.h.
Referenced by SHorizontalBox::SHorizontalBox(), SStackBox::SStackBox(), SVerticalBox::SVerticalBox(), SPopup::SLATE_DEFAULT_SLOT(), and STooltipPresenter::SLATE_DEFAULT_SLOT().
bClippingProxy
uint8 SWidget::bClippingProxy protected
Some widgets might be a complex hierarchy of child widgets you never see.
Some of those widgets would expose their clipping option normally, but may not personally be responsible for clipping so even though it may be set to clip, this flag is used to inform painting that this widget doesn't really do the clipping.
Definition at line 1724 of file SWidget.h.
bDesiredSizeSet
uint8 SWidget::bDesiredSizeSet private
Is the DesiredSize set.
Definition at line 1761 of file SWidget.h.
Referenced by SetDesiredSize().
bEnabledAttributesUpdate
uint8 SWidget::bEnabledAttributesUpdate private
Are bound Slate Attributes will be updated once per frame.
Definition at line 1749 of file SWidget.h.
Referenced by IsAttributesUpdatesEnabled().
bForceVolatile
uint8 SWidget::bForceVolatile private
Should we be forcing this widget to be volatile at all times and redrawn every frame?
Definition at line 1734 of file SWidget.h.
Referenced by CacheVolatility(), and ForceVolatile().
bHasActiveTimers
uint8 SWidget::bHasActiveTimers private
Is there at least one ActiveTimer currently registered.
Definition at line 1758 of file SWidget.h.
Referenced by HasActiveTimers().
bHasCustomPrepass
uint8 SWidget::bHasCustomPrepass protected
Definition at line 1767 of file SWidget.h.
Referenced by SLinkedBox::SLinkedBox().
bHasRegisteredSlateAttribute
uint8 SWidget::bHasRegisteredSlateAttribute private
Is there at least one SlateAttribute currently registered.
Definition at line 1746 of file SWidget.h.
Referenced by HasRegisteredSlateAttribute().
bHasRelativeLayoutScale
uint8 SWidget::bHasRelativeLayoutScale protected
Definition at line 1769 of file SWidget.h.
Referenced by SNodePanel::SNode::SNode().
bInheritedVolatility
uint8 SWidget::bInheritedVolatility private
If we're owned by a volatile widget, we need inherit that volatility and use as part of our volatility, but don't cache it.
Definition at line 1740 of file SWidget.h.
Referenced by IsVolatileIndirectly().
bIsDeclarativeSyntaxConstructionCompleted
uint8 SWidget::bIsDeclarativeSyntaxConstructionCompleted private
The SNew or SAssignedNew construction is completed.
Definition at line 1752 of file SWidget.h.
Referenced by IsConstructed().
bIsHoveredAttributeSet
uint8 SWidget::bIsHoveredAttributeSet private
Is the attribute IsHovered is set?
Definition at line 1755 of file SWidget.h.
Referenced by SetHover().
bNeedsPrepass
uint8 SWidget::bNeedsPrepass private
Are we currently updating the desired size?
Definition at line 1743 of file SWidget.h.
Referenced by MarkPrepassAsDirty(), and NeedsPrepass().
bPrepassLayoutScaleMultiplierSet
uint8 SWidget::bPrepassLayoutScaleMultiplierSet private
Is the PrepassLayoutScaleMultiplier set.
Definition at line 1764 of file SWidget.h.
Referenced by GetPrepassLayoutScaleMultiplier().
bToolTipForceFieldEnabled
uint8 SWidget::bToolTipForceFieldEnabled private
Whether this widget is a "tool tip force field".
That is, tool-tips should never spawn over the area occupied by this widget, and will instead be repelled to an outside edge
Definition at line 1731 of file SWidget.h.
Referenced by HasToolTipForceField().
bVolatilityAlwaysInvalidatesPrepass
uint8 SWidget::bVolatilityAlwaysInvalidatesPrepass protected
if this widget should always invalidate the prepass step when volatile
Definition at line 1772 of file SWidget.h.
Referenced by ShouldInvalidatePrepassDueToVolatility().
Clipping
EWidgetClipping SWidget::Clipping protected
Set to true if all content of the widget should clip to the bounds of this widget.
Definition at line 1784 of file SWidget.h.
Referenced by GetClipping(), STileView< ItemType >::SLATE_END_ARGS(), SListView< TSharedPtr< FString > >::SLATE_EVENT(), and STreeView< FRigVMSearchResult >::SLATE_EVENT().
CreatedInLocation
FName SWidget::CreatedInLocation private
Full file path (and line) in which this widget was created.
Definition at line 1857 of file SWidget.h.
CullingBoundsExtension
FMargin SWidget::CullingBoundsExtension protected
Can be used to enlarge the culling bounds of this widget (pre-intersection), this can be useful if you've got children that you know are using rendering transforms to render outside their standard bounds, if that happens it's possible the parent might be culled before the descendant widget is entirely off screen.
For those cases, you should extend the bounds of the culling area to add a bit more slack to how culling is performed to this panel.
Definition at line 1830 of file SWidget.h.
Referenced by GetCullingBoundsExtension(), and SetCullingBoundsExtension().
DesiredSize
FVector2f SWidget::DesiredSize private
Stores the ideal size this widget wants to be.
See bDesiredSizeSet.
Definition at line 1815 of file SWidget.h.
Referenced by SSplitter::HandleResizingBySize(), SetDesiredSize(), SAudioInputWidget::SetDesiredSizeOverride(), SAudioMaterialLabeledSlider::SetDesiredSizeOverride(), SAudioRadialSlider::SetDesiredSizeOverride(), SAudioSliderBase::SetDesiredSizeOverride(), SDesignSurface::ZoomToLocation(), and SNodePanel::ZoomToLocation().
EnabledStateAttribute
TSlateAttribute<bool> SWidget::EnabledStateAttribute private
Whether or not this widget is enabled.
Definition at line 1804 of file SWidget.h.
Referenced by GetEnabledStateAttribute(), IsEnabled(), and SetEnabled().
FastPathProxyHandle
FWidgetProxyHandle SWidget::FastPathProxyHandle mutable private
Handle to the proxy when on the fast path.
Definition at line 1706 of file SWidget.h.
Referenced by AddUpdateFlags(), GetProxyHandle(), RemoveUpdateFlags(), and SetFastPathProxyHandle().
FlowDirectionPreference
EFlowDirectionPreference SWidget::FlowDirectionPreference private
Flow direction preference.
Definition at line 1795 of file SWidget.h.
Referenced by ComputeFlowDirection(), GetFlowDirectionPreference(), and SetFlowDirectionPreference().
HoveredAttribute
TSlateAttribute<bool> SWidget::HoveredAttribute private
Whether or not this widget is hovered.
Definition at line 1807 of file SWidget.h.
Referenced by GetHoveredAttribute(), IsHovered(), and SetHover().
MetaData
TArray<TSharedRef<ISlateMetaData> > SWidget::MetaData private
Metadata associated with this widget.
Definition at line 1837 of file SWidget.h.
Referenced by GetAllMetaData(), GetMetaData(), RemoveAllMetaData(), RemoveMetaData(), and RemoveMetaData().
ParentWidgetPtr
TWeakPtr<SWidget> SWidget::ParentWidgetPtr private
Pointer to this widgets parent widget.
If it is null this is a root widget or it is not in the widget tree
Definition at line 1840 of file SWidget.h.
Referenced by GetParentWidget(), and IsParentValid().
PersistentState
FSlateWidgetPersistentState SWidget::PersistentState mutable private
Definition at line 1812 of file SWidget.h.
Referenced by Advanced_GetPaintParentWidget(), GetCurrentClippingState(), and GetPersistentState().
PixelSnappingMethod
EWidgetPixelSnapping SWidget::PixelSnappingMethod protected
When set to EPixelSnappingMethod::SnapToPixel, the widget is drawn at the nearest pixel.
Will improve sharpness but could show a stepping effect when moved in an animation. By default everything in slate is Inherit, and the default state all things inherit is SnapToPixel.
Definition at line 1791 of file SWidget.h.
Referenced by GetPixelSnapping().
PrepassLayoutScaleMultiplierValue
float SWidget::PrepassLayoutScaleMultiplierValue private
Definition at line 1810 of file SWidget.h.
Referenced by GetPrepassLayoutScaleMultiplier().
RenderOpacity
float SWidget::RenderOpacity protected
The opacity of the widget.
Automatically applied during rendering.
Definition at line 1833 of file SWidget.h.
Referenced by GetRenderOpacity(), and SetRenderOpacity().
RenderTransformAttribute
TSlateAttribute<TOptional<FSlateRenderTransform> > SWidget::RenderTransformAttribute private
Render transform of this widget.
TOptional<> to allow code to skip expensive overhead if there is no render transform applied.
Definition at line 1821 of file SWidget.h.
Referenced by GetRenderTransform(), GetRenderTransformAttribute(), GetRenderTransformWithRespectToFlowDirection(), and SetRenderTransform().
RenderTransformPivotAttribute
TSlateAttribute<FVector2D> SWidget::RenderTransformPivotAttribute private
Render transform pivot of this widget (in normalized local space)
Definition at line 1818 of file SWidget.h.
Referenced by GetRenderTransformPivot(), GetRenderTransformPivotAttribute(), GetRenderTransformPivotWithRespectToFlowDirection(), and SetRenderTransformPivot().
Tag
FName SWidget::Tag private
Tag for this widget.
Definition at line 1843 of file SWidget.h.
Referenced by SetTag().
TypeOfWidget
FName SWidget::TypeOfWidget private
Debugging information on the type of widget we're creating for the Widget Reflector.
Definition at line 1846 of file SWidget.h.
UpdateFlags
EWidgetUpdateFlags SWidget::UpdateFlags private
The different updates this widget needs next frame.
Definition at line 1798 of file SWidget.h.
Referenced by AddUpdateFlags(), HasAnyUpdateFlags(), and RemoveUpdateFlags().
VisibilityAttribute
TSlateAttribute<EVisibility> SWidget::VisibilityAttribute private
Is this widget visible, hidden or collapsed.
Definition at line 1801 of file SWidget.h.
Referenced by GetVisibility(), and GetVisibilityAttribute().
The documentation for this class was generated from the following file:
Runtime/SlateCore/Public/Widgets/SWidget.h