Unreal Engine 5.6 C++ API: FDelayedDrag Class Reference
FDelayedDrag Class Reference
Helper class to assist with delayed drag operations.
#include "DelayedDrag.h"
Public Member Functions
FDelayedDrag (FVector2D InInitialPosition, FKey InEffectiveKey)
Construct this drag helper with an initial posision, and a key (probably mouse button) required for dragging.
bool AttemptDragStart (const FPointerEvent &MouseEvent)
Attempt to start a drag from the given mouse event.
void ForceDragStart ()
Force the state of this helper to be 'dragging'.
const FVector2D & GetInitialPosition () const
Get the initial start position (before any drag has started)
bool IsDragging () const
Check whether we have initiated a drag or not.
void SetTriggerScaleFactor (float InTriggerScaleFactor)
Assign a new scale factor to apply to the drag trigger distance.
Protected Attributes
bool bHasInitiatedDrag
True where the distance dragged is sufficient to have started a drag.
float DistanceDragged
The amount we have dragged.
FKey EffectiveKey
The key that must be pressed to initiate the drag.
FVector2D InitialPosition
The initial position of the drag start.
float TriggerDistance
The minimum distance that must be moved before the drag initiates.
Detailed Description
Helper class to assist with delayed drag operations.
Definition at line 10 of file DelayedDrag.h.
Constructor & Destructor Documentation
FDelayedDrag()
FDelayedDrag::FDelayedDrag (FVector2D InInitialPosition, FKey InEffectiveKey) inline
Construct this drag helper with an initial posision, and a key (probably mouse button) required for dragging.
Definition at line 15 of file DelayedDrag.h.
References bHasInitiatedDrag, DistanceDragged, EffectiveKey, FSlateApplication::Get(), FSlateApplication::GetDragTriggerDistance(), InitialPosition, and TriggerDistance.
Referenced by FCurveEditorDelayedDrag::FCurveEditorDelayedDrag().
Member Function Documentation
AttemptDragStart()
bool FDelayedDrag::AttemptDragStart (const FPointerEvent & MouseEvent) inline
Attempt to start a drag from the given mouse event.
Definition at line 31 of file DelayedDrag.h.
References bHasInitiatedDrag, DistanceDragged, EffectiveKey, ForceDragStart(), MouseEvent, and TriggerDistance.
ForceDragStart()
void FDelayedDrag::ForceDragStart () inline
Force the state of this helper to be 'dragging'.
Definition at line 28 of file DelayedDrag.h.
References bHasInitiatedDrag.
Referenced by AttemptDragStart().
GetInitialPosition()
const FVector2D & FDelayedDrag::GetInitialPosition () const inline
Get the initial start position (before any drag has started)
Definition at line 22 of file DelayedDrag.h.
References InitialPosition.
IsDragging()
bool FDelayedDrag::IsDragging () const inline
Check whether we have initiated a drag or not.
Definition at line 25 of file DelayedDrag.h.
References bHasInitiatedDrag.
SetTriggerScaleFactor()
void FDelayedDrag::SetTriggerScaleFactor (float InTriggerScaleFactor) inline
Assign a new scale factor to apply to the drag trigger distance.
Definition at line 46 of file DelayedDrag.h.
References FSlateApplication::Get(), FMath::Max, and TriggerDistance.
Referenced by FCurveEditorDelayedDrag::FCurveEditorDelayedDrag().
Field Documentation
bHasInitiatedDrag
bool FDelayedDrag::bHasInitiatedDrag protected
True where the distance dragged is sufficient to have started a drag.
Definition at line 56 of file DelayedDrag.h.
Referenced by FDelayedDrag(), AttemptDragStart(), ForceDragStart(), and IsDragging().
DistanceDragged
float FDelayedDrag::DistanceDragged protected
The amount we have dragged.
Definition at line 58 of file DelayedDrag.h.
Referenced by FDelayedDrag(), and AttemptDragStart().
EffectiveKey
FKey FDelayedDrag::EffectiveKey protected
The key that must be pressed to initiate the drag.
Definition at line 62 of file DelayedDrag.h.
Referenced by FDelayedDrag(), and AttemptDragStart().
InitialPosition
FVector2D FDelayedDrag::InitialPosition protected
The initial position of the drag start.
Definition at line 54 of file DelayedDrag.h.
Referenced by FDelayedDrag(), and GetInitialPosition().
TriggerDistance
float FDelayedDrag::TriggerDistance protected
The minimum distance that must be moved before the drag initiates.
Definition at line 60 of file DelayedDrag.h.
Referenced by FDelayedDrag(), AttemptDragStart(), and SetTriggerScaleFactor().
The documentation for this class was generated from the following file:
Runtime/Slate/Public/Framework/DelayedDrag.h