Unreal Engine 5.6 C++ API: UE::SharedBuffer::Private::TBufferOwnerDeleteFunction< DeleteFunctionType > Class Template Reference
UE::SharedBuffer::Private::TBufferOwnerDeleteFunction< DeleteFunctionType > Class Template Reference final
#include "SharedBuffer.h"
Public Member Functions
TBufferOwnerDeleteFunction (const void *Data, uint64 Size, DeleteFunctionType &&InDeleteFunction)
TBufferOwnerDeleteFunction (void *Data, uint64 Size, DeleteFunctionType &&InDeleteFunction)
Private Member Functions
virtual void FreeBuffer () final
Free the buffer and any associated resources.
Private Attributes
std::decay_t< DeleteFunctionType > DeleteFunction
Additional Inherited Members
Public Types inherited from FBufferOwner
enum class EBufferOwnerFlags : uint8 { None = 0 , Owned = 1 << 0 , Immutable = 1 << 1 , Materialized = 1 << 2 }
Protected Member Functions inherited from FBufferOwner
FBufferOwner ()=default
FBufferOwner (const FBufferOwner &)=delete
FBufferOwner (void *InData, uint64 InSize)
virtual ~FBufferOwner ()
void * GetData ()
uint64 GetSize ()
uint32 GetTotalRefCount () const
bool IsImmutable () const
bool IsMaterialized () const
bool IsOwned () const
void Materialize ()
virtual void MaterializeBuffer ()
Materialize the buffer by making it ready to be accessed.
FBufferOwner & operator= (const FBufferOwner &)=delete
void SetBuffer (void *InData, uint64 InSize)
void SetIsImmutable ()
void SetIsMaterialized ()
void SetIsOwned ()
Detailed Description
template<typename DeleteFunctionType>
class UE::SharedBuffer::Private::TBufferOwnerDeleteFunction< DeleteFunctionType >
Definition at line 521 of file SharedBuffer.h.
Constructor & Destructor Documentation
TBufferOwnerDeleteFunction() [1/2]
template<typename DeleteFunctionType> UE::SharedBuffer::Private::TBufferOwnerDeleteFunction< DeleteFunctionType >::TBufferOwnerDeleteFunction (void * Data, uint64 Size, DeleteFunctionType && InDeleteFunction) inline explicit
Definition at line 524 of file SharedBuffer.h.
References FBufferOwner::FBufferOwner(), FBufferOwner::Data, DeleteFunction, Forward(), FBufferOwner::SetIsMaterialized(), FBufferOwner::SetIsOwned(), and FBufferOwner::Size.
Referenced by TBufferOwnerDeleteFunction().
TBufferOwnerDeleteFunction() [2/2]
template<typename DeleteFunctionType> UE::SharedBuffer::Private::TBufferOwnerDeleteFunction< DeleteFunctionType >::TBufferOwnerDeleteFunction (const void * Data, uint64 Size, DeleteFunctionType && InDeleteFunction) inline explicit
Definition at line 532 of file SharedBuffer.h.
References TBufferOwnerDeleteFunction(), FBufferOwner::Data, Forward(), FBufferOwner::SetIsImmutable(), and FBufferOwner::Size.
Member Function Documentation
FreeBuffer()
template<typename DeleteFunctionType> virtual void UE::SharedBuffer::Private::TBufferOwnerDeleteFunction< DeleteFunctionType >::FreeBuffer () inline final private virtual
Free the buffer and any associated resources.
This is called when the last shared reference is released. The destructor will be called when the last weak reference is released. A buffer owner will always call this function before the calling the destructor, unless an exception was thrown by the constructor.
Implements FBufferOwner.
Definition at line 539 of file SharedBuffer.h.
References DeleteFunction, GetData(), FBufferOwner::GetSize(), and Invoke().
Field Documentation
DeleteFunction
template<typename DeleteFunctionType> std::decay_t<DeleteFunctionType> UE::SharedBuffer::Private::TBufferOwnerDeleteFunction< DeleteFunctionType >::DeleteFunction private
Definition at line 544 of file SharedBuffer.h.
Referenced by TBufferOwnerDeleteFunction(), and FreeBuffer().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Memory/SharedBuffer.h