Unreal Engine 5.6 C++ API: FShaderResourceParameter Class Reference
FShaderResourceParameter Class Reference
A shader resource binding (textures or samplerstates).
#include "ShaderParameters.h"
Public Member Functions
FShaderResourceParameter ()=default
RENDERCORE_API void Bind (const FShaderParameterMap &ParameterMap, const TCHAR *ParameterName, EShaderParameterFlags Flags=SPF_Optional)
uint32 GetBaseIndex () const
uint32 GetNumResources () const
EShaderParameterType GetType () const
bool IsBound () const
bool IsInitialized () const
Private Member Functions
DECLARE_EXPORTED_TYPE_LAYOUT (FShaderResourceParameter, RENDERCORE_API, NonVirtual)
LAYOUT_FIELD_INITIALIZED (EShaderParameterType, Type, {})
LAYOUT_FIELD_INITIALIZED (uint16, BaseIndex, 0)
LAYOUT_FIELD_INITIALIZED (uint8, NumResources, 0)
Friends
RENDERCORE_API FArchive & operator<< (FArchive &Ar, FShaderResourceParameter &P)
Detailed Description
A shader resource binding (textures or samplerstates).
Definition at line 90 of file ShaderParameters.h.
Constructor & Destructor Documentation
FShaderResourceParameter()
FShaderResourceParameter::FShaderResourceParameter () default
Referenced by DECLARE_EXPORTED_TYPE_LAYOUT(), and operator<<.
Member Function Documentation
Bind()
RENDERCORE_API void FShaderResourceParameter::Bind (const FShaderParameterMap & ParameterMap, const TCHAR * ParameterName, EShaderParameterFlags Flags = SPF_Optional)
References Flags, and SPF_Optional.
DECLARE_EXPORTED_TYPE_LAYOUT()
FShaderResourceParameter::DECLARE_EXPORTED_TYPE_LAYOUT (FShaderResourceParameter , RENDERCORE_API , NonVirtual) private
References FShaderResourceParameter().
GetBaseIndex()
uint32 FShaderResourceParameter::GetBaseIndex () const inline
Definition at line 102 of file ShaderParameters.h.
GetNumResources()
uint32 FShaderResourceParameter::GetNumResources () const inline
Definition at line 103 of file ShaderParameters.h.
GetType()
EShaderParameterType FShaderResourceParameter::GetType () const inline
Definition at line 104 of file ShaderParameters.h.
IsBound()
bool FShaderResourceParameter::IsBound () const inline
Definition at line 99 of file ShaderParameters.h.
Referenced by SetTextureParameter().
IsInitialized()
bool FShaderResourceParameter::IsInitialized () const inline
Definition at line 100 of file ShaderParameters.h.
LAYOUT_FIELD_INITIALIZED() [1/3]
FShaderResourceParameter::LAYOUT_FIELD_INITIALIZED (EShaderParameterType , Type , {}) private
LAYOUT_FIELD_INITIALIZED() [2/3]
FShaderResourceParameter::LAYOUT_FIELD_INITIALIZED (uint16 , BaseIndex , 0) private
LAYOUT_FIELD_INITIALIZED() [3/3]
FShaderResourceParameter::LAYOUT_FIELD_INITIALIZED (uint8 , NumResources , 0) private
Friends And Related Symbol Documentation
operator<<
RENDERCORE_API FArchive & operator<< (FArchive & Ar, FShaderResourceParameter & P) friend
References FShaderResourceParameter(), and Ar.
The documentation for this class was generated from the following file:
Runtime/RenderCore/Public/ShaderParameters.h