Unreal Engine 5.6 C++ API: FPoly Class Reference
FPoly Class Reference
#include "Polys.h"
Public Types
typedef TArray< FVector3f, TInlineAllocator< 16 > > VerticesArrayType
Public Member Functions
FPoly ()
Constructor, initializing all member variables.
float Area ()
Computes the 2D area of the polygon.
int32 CalcNormal (bool bSilent=0)
Compute normal of an FPoly.
bool DoesLineIntersect (FVector Start, FVector End, FVector *Intersect=NULL)
Checks to see if the specified line intersects this poly or not.
int32 Faces (const FPoly &Test) const
Return whether this poly and Test are facing each other.
int32 Finalize (ABrush *InOwner, int32 NoError)
Compute all remaining polygon parameters (normal, etc) that are blank.
int32 Fix ()
Fix up an editor poly by deleting vertices that are identical.
FVector GetMidPoint ()
Computes the mid point of the polygon (in local space).
int32 GetVertexIndex (FVector3f &InVtx)
Finds the index of the specific vertex.
void Init ()
Initialize everything in an editor polygon structure to defaults.
void InsertVertex (int32 InPos, FVector InVtx)
Inserts a vertex into the poly at a specific position.
int32 IsBackfaced (const FVector3f &Point) const
bool IsConvex ()
Checks to see if this polygon is a convex shape.
bool IsCoplanar ()
Checks to see if all the vertices on a polygon are coplanar.
int32 IsCoplanar (const FPoly &Test) const
bool OnPlane (FVector InVtx)
Checks to see if the specified vertex lies on this polygons plane.
bool OnPoly (FVector InVtx)
Checks to see if the specified vertex is on this poly.
int32 RemoveColinears ()
Remove colinear vertices and check convexity.
void RemoveVertex (FVector InVtx)
Removes a vertex from the polygons list of vertices.
void Reverse ()
Reverse an FPoly by reversing the normal and reversing the order of its vertices.
void Rotate (const FRotator3f &Rotation)
Rotate an editor polygon.
void Scale (const FVector3f &Scale)
Scale an editor polygon.
int32 Split (const FVector3f &InNormal, const FVector3f &InBase)
Split a poly and keep only the front half.
int32 SplitWithNode (const UModel *Model, int32 iNode, FPoly *FrontPoly, FPoly *BackPoly, int32 VeryPrecise) const
Split with a Bsp node.
int32 SplitWithPlane (const FVector3f &InBase, const FVector3f &InNormal, FPoly *FrontPoly, FPoly *BackPoly, int32 VeryPrecise) const
Split with plane.
int32 SplitWithPlaneFast (const FPlane &Plane, FPoly *FrontPoly, FPoly *BackPoly) const
Split with plane quickly for in-game geometry operations.
void Transform (const FVector3f &PostAdd)
Transform an editor polygon with a post-transformation addition.
int32 Triangulate (ABrush *InOwnerBrush, TArray< FPoly > &OutTriangles)
Breaks down this polygon into triangles.
Static Public Member Functions
static FPoly BuildAndCutInfiniteFPoly (const FPlane &InPlane, const TArray< FPlane > &InCutPlanes, ABrush *InOwnerBrush)
static FPoly BuildInfiniteFPoly (const FPlane &InPlane)
Builds a huge poly aligned with the specified plane.
template<typename ArrayType>
static void GetOutsideWindings (ABrush *InOwnerBrush, ArrayType &InPolygons, TArray< TArray< FVector3f > > &InWindings)
Takes a set of polygons and returns a vertex array representing the outside winding for them.
template<typename ArrayType>
static void OptimizeIntoConvexPolys (ABrush *InOwnerBrush, ArrayType &InPolygons)
Optimizes a set of polygons into a smaller set of convex polygons.
Data Fields
TObjectPtr< ABrush > Actor
FVector3f Base
int32 iBrushPoly
int32 iLink
int32 iLinkSurf
FName ItemName
float LightMapScale
FLightmassPrimitiveSettings LightmassSettings
TObjectPtr< UMaterialInterface > Material
FVector3f Normal
uint32 PolyFlags
FName RulesetVariation
uint32 SmoothingMask
FVector3f TextureU
FVector3f TextureV
VerticesArrayType Vertices
Friends
bool operator!= (const FPoly &A, const FPoly &B)
FArchive & operator<< (FArchive &Ar, FPoly &Poly)
bool operator== (const FPoly &A, const FPoly &B)
Detailed Description
Definition at line 37 of file Polys.h.
Member Typedef Documentation
VerticesArrayType
typedef TArray<FVector3f,TInlineAllocator<16> > FPoly::VerticesArrayType
Definition at line 41 of file Polys.h.
Constructor & Destructor Documentation
FPoly()
FPoly::FPoly ()
Constructor, initializing all member variables.
Referenced by BuildAndCutInfiniteFPoly(), BuildInfiniteFPoly(), Faces(), GetOutsideWindings(), IsCoplanar(), operator!=, operator<<, operator==, SplitWithNode(), SplitWithPlane(), and SplitWithPlaneFast().
Member Function Documentation
Area()
float FPoly::Area ()
Computes the 2D area of the polygon.
Returns zero if the polygon has less than three verices.
BuildAndCutInfiniteFPoly()
FPoly FPoly::BuildAndCutInfiniteFPoly (const FPlane & InPlane, const TArray< FPlane > & InCutPlanes, ABrush * InOwnerBrush) static
References FPoly().
BuildInfiniteFPoly()
FPoly FPoly::BuildInfiniteFPoly (const FPlane & InPlane) static
Builds a huge poly aligned with the specified plane.
This poly is carved up by the calling routine and used as a capping poly following a clip operation.
Parameters
InPlane The plane to lay the polygon on.
InCutPlanes The planes to split the poly with.
InOwnerBrush The brush that owns the polygons.
Returns
The resulting polygon
References FPoly().
CalcNormal()
int32 FPoly::CalcNormal (bool bSilent = 0)
Compute normal of an FPoly.
Works even if FPoly has 180-degree-angled sides (which are often created during T-joint elimination). Returns nonzero result (plus sets normal vector to zero) if a problem occurs.
DoesLineIntersect()
bool FPoly::DoesLineIntersect (FVector Start, FVector End, FVector * Intersect = NULL)
Checks to see if the specified line intersects this poly or not.
If "Intersect" is a valid pointer, it is filled in with the intersection point.
References End, and FVector.
Faces()
int32 FPoly::Faces (const FPoly & Test) const
Return whether this poly and Test are facing each other.
The polys are facing if they are noncoplanar, one or more of Test's points is in front of this poly, and one or more of this poly's points are behind Test.
References FPoly(), and Test.
Finalize()
int32 FPoly::Finalize (ABrush * InOwner, int32 NoError)
Compute all remaining polygon parameters (normal, etc) that are blank.
Returns 0 if ok, nonzero if problem.
Referenced by GetOutsideWindings().
Fix()
int32 FPoly::Fix ()
Fix up an editor poly by deleting vertices that are identical.
Sets vertex count to zero if it collapses. Returns number of vertices, 0 or >=3.
GetMidPoint()
FVector FPoly::GetMidPoint ()
Computes the mid point of the polygon (in local space).
References FVector.
GetOutsideWindings()
template<typename ArrayType> void FPoly::GetOutsideWindings (ABrush * InOwnerBrush, ArrayType & InPolygons, TArray< TArray< FVector3f > > & InWindings) inline static
Takes a set of polygons and returns a vertex array representing the outside winding for them.
NOTE : This will work for convex or concave sets of polygons but not for concave polygons with holes.
Parameters
InOwnerBrush The brush that owns the polygons.
InPolygons An array of FPolys that you want to get the winding for
InWindings The resulting sets of vertices that represent the windings
Definition at line 234 of file Polys.h.
References FPoly(), TArray< InElementType, InAllocatorType >::Add(), TArray< InElementType, InAllocatorType >::AddUnique(), TArray< InElementType, InAllocatorType >::Append(), TArray< InElementType, InAllocatorType >::Count, Edge, TArray< InElementType, InAllocatorType >::Empty(), UE::Math::TVector< T >::Equals(), Exchange(), Finalize(), TArray< InElementType, InAllocatorType >::Find(), FVector, Init(), Normal, TArray< InElementType, InAllocatorType >::Num(), TArray< InElementType, InAllocatorType >::RemoveAt(), Triangulate(), Vertex, FEdge::Vertex, and Vertices.
GetVertexIndex()
int32 FPoly::GetVertexIndex (FVector3f & InVtx)
Finds the index of the specific vertex.
Parameters
InVtx The vertex to find the index of
Returns
The index of the vertex, if found. Otherwise INDEX_NONE.
Init()
void FPoly::Init ()
Initialize everything in an editor polygon structure to defaults.
Changes to these default values should also be mirrored to UPolysExporterT3D::ExportText(...).
Referenced by GetOutsideWindings().
InsertVertex()
void FPoly::InsertVertex (int32 InPos, FVector InVtx)
Inserts a vertex into the poly at a specific position.
References FVector.
IsBackfaced()
int32 FPoly::IsBackfaced (const FVector3f & Point) const inline
Definition at line 383 of file Polys.h.
References Base, Normal, and Point.
IsConvex()
bool FPoly::IsConvex ()
Checks to see if this polygon is a convex shape.
Returns
true if this polygon is convex.
IsCoplanar() [1/2]
bool FPoly::IsCoplanar ()
Checks to see if all the vertices on a polygon are coplanar.
IsCoplanar() [2/2]
int32 FPoly::IsCoplanar (const FPoly & Test) const inline
Definition at line 385 of file Polys.h.
References FPoly(), Base, Normal, and Test.
OnPlane()
bool FPoly::OnPlane (FVector InVtx)
Checks to see if the specified vertex lies on this polygons plane.
References FVector.
OnPoly()
bool FPoly::OnPoly (FVector InVtx)
Checks to see if the specified vertex is on this poly.
Assumes the vertex is on the same plane as the poly and that the poly is convex.
This can be combined with FMath::LinePlaneIntersection to perform a line-fpoly intersection test.
References FVector.
OptimizeIntoConvexPolys()
template<typename ArrayType> void FPoly::OptimizeIntoConvexPolys (ABrush * InOwnerBrush, ArrayType & InPolygons) static
Optimizes a set of polygons into a smaller set of convex polygons.
Parameters
InOwnerBrush The brush that owns the polygons.
InPolygons An array of FPolys that will be replaced with a new set of polygons that are merged together as much as possible.
RemoveColinears()
int32 FPoly::RemoveColinears ()
Remove colinear vertices and check convexity.
Returns 1 if convex, 0 if nonconvex or collapsed.
RemoveVertex()
void FPoly::RemoveVertex (FVector InVtx)
Removes a vertex from the polygons list of vertices.
References FVector.
Reverse()
void FPoly::Reverse ()
Reverse an FPoly by reversing the normal and reversing the order of its vertices.
Rotate()
void FPoly::Rotate (const FRotator3f & Rotation)
Rotate an editor polygon.
References Rotation.
Scale()
void FPoly::Scale (const FVector3f & Scale)
Scale an editor polygon.
References Scale().
Referenced by Scale().
Split()
int32 FPoly::Split (const FVector3f & InNormal, const FVector3f & InBase)
Split a poly and keep only the front half.
Returns number of vertices, 0 if clipped away.
SplitWithNode()
int32 FPoly::SplitWithNode (const UModel * Model, int32 iNode, FPoly * FrontPoly, FPoly * BackPoly, int32 VeryPrecise) const
Split with a Bsp node.
References FPoly().
SplitWithPlane()
int32 FPoly::SplitWithPlane (const FVector3f & InBase, const FVector3f & InNormal, FPoly * FrontPoly, FPoly * BackPoly, int32 VeryPrecise) const
Split with plane.
Meant to be numerically stable.
References FPoly().
SplitWithPlaneFast()
int32 FPoly::SplitWithPlaneFast (const FPlane & Plane, FPoly * FrontPoly, FPoly * BackPoly) const
Split with plane quickly for in-game geometry operations.
Results are always valid. May return sliver polys.
References FPoly(), and Plane.
Transform()
void FPoly::Transform (const FVector3f & PostAdd)
Transform an editor polygon with a post-transformation addition.
Triangulate()
int32 FPoly::Triangulate (ABrush * InOwnerBrush, TArray< FPoly > & OutTriangles)
Breaks down this polygon into triangles.
The triangles are then returned to the caller in an array.
Parameters
InOwnerBrush The brush that owns this polygon.
OutTriangles An array to store the resulting triangles in.
Returns
The number of triangles created
Referenced by GetOutsideWindings().
Friends And Related Symbol Documentation
operator!=
bool operator!= (const FPoly & A, const FPoly & B) friend
Definition at line 405 of file Polys.h.
References FPoly(), A, and B.
operator<<
FArchive & operator<< (FArchive & Ar, FPoly & Poly) friend
References FPoly(), and Ar.
operator==
bool operator== (const FPoly & A, const FPoly & B) friend
Definition at line 388 of file Polys.h.
References FPoly(), A, and B.
Field Documentation
Actor
TObjectPtr<ABrush> FPoly::Actor
Definition at line 49 of file Polys.h.
Base
FVector3f FPoly::Base
Definition at line 43 of file Polys.h.
Referenced by IsBackfaced(), and IsCoplanar().
iBrushPoly
int32 FPoly::iBrushPoly
Definition at line 55 of file Polys.h.
iLink
int32 FPoly::iLink
Definition at line 53 of file Polys.h.
iLinkSurf
int32 FPoly::iLinkSurf
Definition at line 54 of file Polys.h.
ItemName
FName FPoly::ItemName
Definition at line 52 of file Polys.h.
LightMapScale
float FPoly::LightMapScale
Definition at line 57 of file Polys.h.
LightmassSettings
FLightmassPrimitiveSettings FPoly::LightmassSettings
Definition at line 61 of file Polys.h.
Material
TObjectPtr<UMaterialInterface> FPoly::Material
Definition at line 50 of file Polys.h.
Normal
FVector3f FPoly::Normal
Definition at line 44 of file Polys.h.
Referenced by GetOutsideWindings(), IsBackfaced(), and IsCoplanar().
PolyFlags
uint32 FPoly::PolyFlags
Definition at line 48 of file Polys.h.
RulesetVariation
FName FPoly::RulesetVariation
Definition at line 51 of file Polys.h.
SmoothingMask
uint32 FPoly::SmoothingMask
Definition at line 56 of file Polys.h.
TextureU
FVector3f FPoly::TextureU
Definition at line 45 of file Polys.h.
TextureV
FVector3f FPoly::TextureV
Definition at line 46 of file Polys.h.
Vertices
VerticesArrayType FPoly::Vertices
Definition at line 47 of file Polys.h.
Referenced by GetOutsideWindings().
The documentation for this class was generated from the following file:
Runtime/Engine/Classes/Engine/Polys.h