Unreal Engine 5.6 C++ API: UE::FDerivedData Class Reference
UE::FDerivedData Class Reference
Derived Data Reference.
#include "DerivedData.h"
Public Member Functions
FDerivedData ()=default
Constructs a null reference.
FDerivedData (const DerivedData::Private::FCookedData &CookedData)
Constructs a reference from the private representation of a cooked reference.
EDerivedDataFlags GetFlags () const
Returns the flags, which are mainly relevant for staged references.
bool HasData () const
Returns true if this is a non-null reference.
bool IsCooked () const
Returns true if this is a cooked reference.
bool IsNull () const
Returns true if this is a null reference.
operator bool () const
Returns true if this is a non-null reference.
bool ReferenceEquals (const FDerivedData &Other) const
Returns true if this and the other are equivalent references.
uint32 ReferenceHash () const
Returns a hash that factors in the same members as ReferenceEquals.
void Reset ()
Resets the reference to null.
void Serialize (FArchive &Ar, UObject *Owner)
Serializes this reference to or from a cooked package.
Static Public Attributes
static const FDerivedData Null
A null reference.
Private Attributes
DerivedData::Private::FCookedData CookedData
Friends
FStringBuilderBase & operator<< (FStringBuilderBase &Builder, const FDerivedData &DerivedData)
Appends the name and description of this reference to the builder.
Detailed Description
Derived Data Reference.
Provides a consistent way to reference derived data:
That has the same API for the editor as for builds with cooked packages.
That has the same API to load from the cache as from a raw buffer, a compressed buffer, or a cooked package.
That supports asynchronous, event-driven, prioritized loading of derived data.
That supports saving to a cooked package without loading from the cache, when using Zen.
That replaces serialized bulk data, such as FByteBulkData, in a cooked package.
Definition at line 79 of file DerivedData.h.
Constructor & Destructor Documentation
FDerivedData() [1/2]
UE::FDerivedData::FDerivedData () default
Constructs a null reference.
References CookedData.
Referenced by operator<<, ReferenceEquals(), and Reset().
FDerivedData() [2/2]
UE::FDerivedData::FDerivedData (const DerivedData::Private::FCookedData & CookedData) inline explicit
Constructs a reference from the private representation of a cooked reference.
Definition at line 150 of file DerivedData.h.
References CookedData.
Member Function Documentation
GetFlags()
EDerivedDataFlags UE::FDerivedData::GetFlags () const inline
Returns the flags, which are mainly relevant for staged references.
Definition at line 107 of file DerivedData.h.
References CookedData.
HasData()
bool UE::FDerivedData::HasData () const inline
Returns true if this is a non-null reference.
Definition at line 101 of file DerivedData.h.
References IsNull().
IsCooked()
bool UE::FDerivedData::IsCooked () const inline
Returns true if this is a cooked reference.
Definition at line 104 of file DerivedData.h.
References CookedData.
IsNull()
bool UE::FDerivedData::IsNull () const inline
Returns true if this is a null reference.
Definition at line 155 of file DerivedData.h.
References CookedData.
Referenced by HasData(), and operator bool().
operator bool()
UE::FDerivedData::operator bool () const inline explicit
Returns true if this is a non-null reference.
Definition at line 98 of file DerivedData.h.
References IsNull().
ReferenceEquals()
bool UE::FDerivedData::ReferenceEquals (const FDerivedData & Other) const
Returns true if this and the other are equivalent references.
References FDerivedData(), Other, and UE_API.
ReferenceHash()
uint32 UE::FDerivedData::ReferenceHash () const
Returns a hash that factors in the same members as ReferenceEquals.
References UE_API.
Reset()
void UE::FDerivedData::Reset () inline
Resets the reference to null.
Definition at line 92 of file DerivedData.h.
References FDerivedData().
Serialize()
void UE::FDerivedData::Serialize (FArchive & Ar, UObject * Owner)
Serializes this reference to or from a cooked package.
References Ar, Flags, Key, Name, Owner, and UE_API.
Friends And Related Symbol Documentation
operator<<
FStringBuilderBase & operator<< (FStringBuilderBase & Builder, const FDerivedData & DerivedData) friend
Appends the name and description of this reference to the builder.
References FDerivedData(), and UE_API.
Field Documentation
CookedData
DerivedData::Private::FCookedData UE::FDerivedData::CookedData private
Definition at line 143 of file DerivedData.h.
Referenced by FDerivedData(), FDerivedData(), GetFlags(), IsCooked(), and IsNull().
Null
const FDerivedData UE::FDerivedData::Null inline static
A null reference.
Definition at line 83 of file DerivedData.h.
The documentation for this class was generated from the following file:
Runtime/CoreUObject/Public/Serialization/DerivedData.h