Unreal Engine 5.6 C++ API: IDetailPropertyRow Class Reference
IDetailPropertyRow Class Reference abstract
A single row for a property in a details panel.
#include "IDetailPropertyRow.h"
Public Member Functions
virtual ~IDetailPropertyRow ()
virtual FDetailWidgetDecl * CustomNameWidget ()=0
Gives a non-owning pointer to name widget on existing custom property widget if it exists.
virtual FDetailWidgetDecl * CustomResetToDefaultWidget ()=0
Gives a non-owning pointer to reset to default widget on existing custom property widget if it exists.
virtual FDetailWidgetDecl * CustomValueWidget ()=0
Gives a non-owning pointer to value widget on existing custom property widget if it exists.
virtual FDetailWidgetRow & CustomWidget (bool bShowChildren=false)=0
Overrides the property widget.
virtual IDetailPropertyRow & DisplayName (const FText &InDisplayName)=0
Sets the localized display name of the property.
virtual IDetailPropertyRow & DragDropHandler (TSharedPtr< IDetailDragDropHandler > InDragDropHandler)=0
Sets a handler for this property row to be a source or target of drag-and-drop operations.
virtual IDetailPropertyRow & EditCondition (TAttribute< bool > EditConditionValue, FOnBooleanValueChanged OnEditConditionValueChanged, ECustomEditConditionMode EditConditionMode=ECustomEditConditionMode::Override)=0
Sets an edit condition for this property.
virtual IDetailPropertyRow & EditConditionHides (bool bEditConditionHidesValue)=0
Sets whether or not the edit condition for this property should affect its visibility.
virtual void GetDefaultWidgets (TSharedPtr< SWidget > &OutNameWidget, TSharedPtr< SWidget > &OutValueWidget, bool bAddWidgetDecoration=false)=0
Returns the name and value widget of this property row.
virtual void GetDefaultWidgets (TSharedPtr< SWidget > &OutNameWidget, TSharedPtr< SWidget > &OutValueWidget, FDetailWidgetRow &Row, bool bAddWidgetDecoration=false)=0
Returns the name and value widget of this property row.
virtual TSharedPtr< IPropertyHandle > GetPropertyHandle () const =0
virtual IDetailPropertyRow & IsEnabled (TAttribute< bool > InIsEnabled)=0
Sets whether or not this property is enabled.
virtual bool IsExpanded () const =0
Returns the property row expansion state.
virtual IDetailPropertyRow & OverrideResetToDefault (const FResetToDefaultOverride &ResetToDefault)=0
Overrides the behavior of reset to default.
virtual IDetailPropertyRow & ShouldAutoExpand (bool bForceExpansion=true)=0
Sets whether or not this property should auto-expand.
virtual IDetailPropertyRow & ShowPropertyButtons (bool bShowPropertyButtons)=0
Sets whether or not we show the default property editing buttons for this property.
virtual IDetailPropertyRow & ToolTip (const FText &InToolTip)=0
Sets the localized tooltip of the property.
virtual IDetailPropertyRow & Visibility (TAttribute< EVisibility > Visibility)=0
Sets the visibility of this property.
Detailed Description
A single row for a property in a details panel.
Definition at line 179 of file IDetailPropertyRow.h.
Constructor & Destructor Documentation
~IDetailPropertyRow()
virtual IDetailPropertyRow::~IDetailPropertyRow () inline virtual
Definition at line 182 of file IDetailPropertyRow.h.
Member Function Documentation
CustomNameWidget()
virtual FDetailWidgetDecl * IDetailPropertyRow::CustomNameWidget () pure virtual
Gives a non-owning pointer to name widget on existing custom property widget if it exists.
Returns
Pointer to name widget if custom property widget already exists, nullptr otherwise
CustomResetToDefaultWidget()
virtual FDetailWidgetDecl * IDetailPropertyRow::CustomResetToDefaultWidget () pure virtual
Gives a non-owning pointer to reset to default widget on existing custom property widget if it exists.
Returns
Pointer to reset to default widget if custom property widget already exists, nullptr otherwise
CustomValueWidget()
virtual FDetailWidgetDecl * IDetailPropertyRow::CustomValueWidget () pure virtual
Gives a non-owning pointer to value widget on existing custom property widget if it exists.
Returns
Pointer to value widget if custom property widget already exists, nullptr otherwise
CustomWidget()
virtual FDetailWidgetRow & IDetailPropertyRow::CustomWidget (bool bShowChildren = false) pure virtual
Overrides the property widget.
Destroys any existing custom property widgets.
Parameters
bShowChildren Whether or not to still show any children of this property
Returns
a row for the property that custom widgets can be added to
Referenced by FGameModeInfoCustomizer::CustomizeGameModeSetting().
DisplayName()
virtual IDetailPropertyRow & IDetailPropertyRow::DisplayName (const FText & InDisplayName) pure virtual
Sets the localized display name of the property.
Parameters
InDisplayName The name of the property
DragDropHandler()
virtual IDetailPropertyRow & IDetailPropertyRow::DragDropHandler (TSharedPtr< IDetailDragDropHandler > InDragDropHandler) pure virtual
Sets a handler for this property row to be a source or target of drag-and-drop operations.
Parameters
InDragDropHandler Handler used when starting a drag or accepting a drop operation
EditCondition()
virtual IDetailPropertyRow & IDetailPropertyRow::EditCondition (TAttribute< bool > EditConditionValue, FOnBooleanValueChanged OnEditConditionValueChanged, ECustomEditConditionMode EditConditionMode = ECustomEditConditionMode::Override) pure virtual
Sets an edit condition for this property.
If the edit condition fails, the property is not editable This will add a checkbox before the name of the property that users can click to toggle the edit condition Properties with built in edit conditions will override this automatically. If the
Parameters
EditConditionValue Attribute for the value of the edit condition (true indicates that the edit condition passes)
OnEditConditionValueChanged Delegate called when the edit condition value changes
EditConditionMode Should this custom edit condition override or merge with the existing edit condition of the property (if any)?
References Override.
EditConditionHides()
virtual IDetailPropertyRow & IDetailPropertyRow::EditConditionHides (bool bEditConditionHidesValue) pure virtual
Sets whether or not the edit condition for this property should affect its visibility.
If the edit condition fails, the property will be hidden outright.
Parameters
bEditConditionHidesValue if true the property be shown/hidden based on the edit condition
GetDefaultWidgets() [1/2]
virtual void IDetailPropertyRow::GetDefaultWidgets (TSharedPtr< SWidget > & OutNameWidget, TSharedPtr< SWidget > & OutValueWidget, bool bAddWidgetDecoration = false) pure virtual
Returns the name and value widget of this property row.
You can use this widget to apply further customization to existing widgets (by using this with CustomWidget)
Parameters
OutNameWidget The default name widget
OutValueWidget The default value widget
GetDefaultWidgets() [2/2]
virtual void IDetailPropertyRow::GetDefaultWidgets (TSharedPtr< SWidget > & OutNameWidget, TSharedPtr< SWidget > & OutValueWidget, FDetailWidgetRow & Row, bool bAddWidgetDecoration = false) pure virtual
Returns the name and value widget of this property row.
You can use this widget to apply further customization to existing widgets (by using this with CustomWidget)
Parameters
OutNameWidget The default name widget
OutValueWidget The default value widget
OutCustomRow The default widget row
GetPropertyHandle()
virtual TSharedPtr< IPropertyHandle > IDetailPropertyRow::GetPropertyHandle () const pure virtual
Returns
the property handle for the property on this row
IsEnabled()
virtual IDetailPropertyRow & IDetailPropertyRow::IsEnabled (TAttribute< bool > InIsEnabled) pure virtual
Sets whether or not this property is enabled.
Parameters
InIsEnabled Attribute for the enabled state of the property (true to enable the property)
IsExpanded()
virtual bool IDetailPropertyRow::IsExpanded () const pure virtual
Returns the property row expansion state.
Returns
Will return true if the row is expanded, false if not
OverrideResetToDefault()
virtual IDetailPropertyRow & IDetailPropertyRow::OverrideResetToDefault (const FResetToDefaultOverride & ResetToDefault) pure virtual
Overrides the behavior of reset to default.
Parameters
ResetToDefault Contains the delegates needed to override the behavior of reset to default
ShouldAutoExpand()
virtual IDetailPropertyRow & IDetailPropertyRow::ShouldAutoExpand (bool bForceExpansion = true) pure virtual
Sets whether or not this property should auto-expand.
Parameters
bForceExpansion true to force the property to be expanded
ShowPropertyButtons()
virtual IDetailPropertyRow & IDetailPropertyRow::ShowPropertyButtons (bool bShowPropertyButtons) pure virtual
Sets whether or not we show the default property editing buttons for this property.
Parameters
bShowPropertyButtons if true property buttons for this property will be shown.
Referenced by FGameModeInfoCustomizer::CustomizeGameModeSetting().
ToolTip()
virtual IDetailPropertyRow & IDetailPropertyRow::ToolTip (const FText & InToolTip) pure virtual
Sets the localized tooltip of the property.
Parameters
InToolTip The tooltip of the property
Visibility()
virtual IDetailPropertyRow & IDetailPropertyRow::Visibility (TAttribute< EVisibility > Visibility) pure virtual
Sets the visibility of this property.
Parameters
Visibility Attribute for the visibility of this property
References Visibility().
Referenced by Visibility().
The documentation for this class was generated from the following file:
Editor/PropertyEditor/Public/IDetailPropertyRow.h