Unreal Engine 5.6 C++ API: UE::Geometry::FMeshHeightMapEvaluator Class Reference
UE::Geometry::FMeshHeightMapEvaluator Class Reference
A mesh evaluator for mesh height as color data.
#include "MeshHeightMapEvaluator.h"
Public Types
enum class EHeightRangeMode { Absolute , RelativeBounds }
Public Types inherited from UE::Geometry::FMeshMapEvaluator
enum class EAccumulateMode { Add , Overwrite , Last }
Accumulate mode informs the baker how samples should be accumulated into the buffer.
enum class EComponents { Float1 = 1 , Float2 = 2 , Float3 = 3 , Float4 = 4 }
The number of float components of an evaluator result/target.
Public Member Functions
FMeshHeightMapEvaluator ()=default
FMeshHeightMapEvaluator (const FMeshHeightMapEvaluator &)=default
virtual DYNAMICMESH_API const TArray< EComponents > & DataLayout () const override
FMeshHeightMapEvaluator & operator= (const FMeshHeightMapEvaluator &)=default
virtual DYNAMICMESH_API void Setup (const FMeshBaseBaker &Baker, FEvaluationContext &Context) override
Invoked at start of bake to setup this evaluator and return an evaluation context to the baker.
virtual EMeshMapEvaluatorType Type () const override
Public Member Functions inherited from UE::Geometry::FMeshMapEvaluator
virtual ~FMeshMapEvaluator ()=default
Static Public Member Functions
static DYNAMICMESH_API void EvaluateChannel (const int DataIdx, float *&In, float &Out, void *EvalData)
static DYNAMICMESH_API void EvaluateColor (const int DataIdx, float *&In, FVector4f &Out, void *EvalData)
static DYNAMICMESH_API void EvaluateDefault (float *&Out, void *EvalData)
static DYNAMICMESH_API void EvaluateSample (float *&Out, const FCorrespondenceSample &Sample, void *EvalData)
Data Fields
FInterval1f Range
EHeightRangeMode RangeMode = EHeightRangeMode::Absolute
Protected Attributes
FInterval1f CachedRange
const IMeshBakerDetailSampler * DetailSampler = nullptr
Private Member Functions
DYNAMICMESH_API float SampleFunction (const FCorrespondenceSample &SampleData) const
Additional Inherited Members
Static Protected Member Functions inherited from UE::Geometry::FMeshMapEvaluator
static void WriteToBuffer (float *&Out, const float Data)
Write float data to a float buffer and increment.
static void WriteToBuffer (float *&Out, const FVector2f &Data)
Write FVector2f data to a float buffer and increment.
static void WriteToBuffer (float *&Out, const FVector3f &Data)
Write FVector3f data to a float buffer and increment.
static void WriteToBuffer (float *&Out, const FVector4f &Data)
Write FVector4f data to a float buffer and increment.
Detailed Description
A mesh evaluator for mesh height as color data.
Definition at line 20 of file MeshHeightMapEvaluator.h.
Member Enumeration Documentation
EHeightRangeMode
enum class UE::Geometry::FMeshHeightMapEvaluator::EHeightRangeMode strong
Enumerator
Absolute
RelativeBounds
Definition at line 23 of file MeshHeightMapEvaluator.h.
Constructor & Destructor Documentation
FMeshHeightMapEvaluator() [1/2]
UE::Geometry::FMeshHeightMapEvaluator::FMeshHeightMapEvaluator () default
Referenced by FMeshHeightMapEvaluator(), and operator=().
FMeshHeightMapEvaluator() [2/2]
UE::Geometry::FMeshHeightMapEvaluator::FMeshHeightMapEvaluator (const FMeshHeightMapEvaluator &) default
References FMeshHeightMapEvaluator().
Member Function Documentation
DataLayout()
virtual DYNAMICMESH_API const TArray< EComponents > & UE::Geometry::FMeshHeightMapEvaluator::DataLayout () const override virtual
Returns
the data layout of the evaluator
Implements UE::Geometry::FMeshMapEvaluator.
References UE_API.
EvaluateChannel()
DYNAMICMESH_API void UE::Geometry::FMeshHeightMapEvaluator::EvaluateChannel (const int DataIdx, float *& In, float & Out, void * EvalData) static
References UE_API.
EvaluateColor()
DYNAMICMESH_API void UE::Geometry::FMeshHeightMapEvaluator::EvaluateColor (const int DataIdx, float *& In, FVector4f & Out, void * EvalData) static
References UE_API.
EvaluateDefault()
DYNAMICMESH_API void UE::Geometry::FMeshHeightMapEvaluator::EvaluateDefault (float *& Out, void * EvalData) static
References UE_API.
EvaluateSample()
DYNAMICMESH_API void UE::Geometry::FMeshHeightMapEvaluator::EvaluateSample (float *& Out, const FCorrespondenceSample & Sample, void * EvalData) static
References UE_API.
operator=()
FMeshHeightMapEvaluator & UE::Geometry::FMeshHeightMapEvaluator::operator= (const FMeshHeightMapEvaluator &) default
References FMeshHeightMapEvaluator().
SampleFunction()
DYNAMICMESH_API float UE::Geometry::FMeshHeightMapEvaluator::SampleFunction (const FCorrespondenceSample & SampleData) const private
References UE_API.
Setup()
virtual DYNAMICMESH_API void UE::Geometry::FMeshHeightMapEvaluator::Setup (const FMeshBaseBaker & Baker, FEvaluationContext & Context) override virtual
Invoked at start of bake to setup this evaluator and return an evaluation context to the baker.
The evaluation context indicates to the baker how the evaluator should be invoked. See FEvaluationContext for more details.
Parameters
Baker the baker that owns this evaluator.
Context [out] the evaluation context.
Implements UE::Geometry::FMeshMapEvaluator.
References UE_API.
Type()
virtual EMeshMapEvaluatorType UE::Geometry::FMeshHeightMapEvaluator::Type () const inline override virtual
Returns
the type of evaluator.
Implements UE::Geometry::FMeshMapEvaluator.
Definition at line 43 of file MeshHeightMapEvaluator.h.
References UE::Geometry::Height.
Field Documentation
CachedRange
FInterval1f UE::Geometry::FMeshHeightMapEvaluator::CachedRange protected
Definition at line 56 of file MeshHeightMapEvaluator.h.
DetailSampler
const IMeshBakerDetailSampler* UE::Geometry::FMeshHeightMapEvaluator::DetailSampler = nullptr protected
Definition at line 55 of file MeshHeightMapEvaluator.h.
Range
FInterval1f UE::Geometry::FMeshHeightMapEvaluator::Range
Definition at line 31 of file MeshHeightMapEvaluator.h.
RangeMode
EHeightRangeMode UE::Geometry::FMeshHeightMapEvaluator::RangeMode = EHeightRangeMode::Absolute
Definition at line 30 of file MeshHeightMapEvaluator.h.
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/GeometryProcessing/Source/DynamicMesh/Public/Sampling/MeshHeightMapEvaluator.h