Unreal Engine 5.6 C++ API: UVolumeTexture Class Reference
UVolumeTexture Class Reference
#include "VolumeTexture.h"
Public Member Functions
virtual int32 CalcCumulativeLODSize (int32 NumLODs) const final override
uint32 CalcTextureMemorySize (int32 MipCount) const
Calculates the size of this texture in bytes if it had MipCount miplevels streamed in.
virtual uint32 CalcTextureMemorySizeEnum (ETextureMipCount Enum) const override
Calculates the size of this texture if it had MipCount miplevels streamed in.
virtual FTextureResource * CreateResource () override
virtual void GetAssetRegistryTags (FAssetRegistryTagsContext Context) const override
virtual TMap< FString, FTexturePlatformData * > * GetCookedPlatformData () override
virtual FString GetDesc () override
virtual EMaterialValueType GetMaterialType () const override
virtual uint32 GetMaximumDimension () const override
Return maximum dimension for this texture type.
int32 GetNumMips () const
EPixelFormat GetPixelFormat () const
FTexturePlatformData * GetPlatformData ()
Get the derived data for this texture on this platform.
const FTexturePlatformData * GetPlatformData () const
Get the const derived data for this texture on this platform.
virtual void GetResourceSizeEx (FResourceSizeEx &CumulativeResourceSize) override
virtual FTexturePlatformData ** GetRunningPlatformData () override
int32 GetSizeX () const
int32 GetSizeY () const
int32 GetSizeZ () const
virtual uint32 GetSurfaceArraySize () const override
virtual float GetSurfaceDepth () const override
virtual float GetSurfaceHeight () const override
virtual float GetSurfaceWidth () const override
virtual TextureAddress GetTextureAddressX () const override
virtual TextureAddress GetTextureAddressY () const override
virtual TextureAddress GetTextureAddressZ () const override
virtual ETextureClass GetTextureClass () const override
virtual bool IsDefaultTexture () const override
virtual void PostEditChangeProperty (FPropertyChangedEvent &PropertyChangedEvent) override
virtual void PostLoad () override
virtual void Serialize (FArchive &Ar) override
void SetDefaultSource2DTileSize ()
void SetPlatformData (FTexturePlatformData *PlatformData)
Set the derived data for this texture on this platform.
virtual bool StreamIn (int32 NewMipCount, bool bHighPrio) final override
virtual bool StreamOut (int32 NewMipCount) final override
UE_DEPRECATED (5.4, "Implement the version that takes FAssetRegistryTagsContext instead.") virtual void GetAssetRegistryTags(TArray< FAssetRegistryTag > &OutTags) const override
virtual void UpdateResourceWithParams (EUpdateResourceFlags InFlags) override
bool UpdateSourceFromFunction (TFunction< void(int32, int32, int32, void *)> Func, int32 SizeX, int32 SizeY, int32 SizeZ, ETextureSourceFormat Format)
Updates a volume texture from a user function, which allows for arbitrary UVolumeTexture objects to be filled.
bool UpdateSourceFromSourceTexture ()
UPROPERTY ()
The addressing mode to use for the X, Y and Z axis.
Static Public Member Functions
static class UVolumeTexture * CreateTransient (int32 InSizeX, int32 InSizeY, int32 InSizeZ, EPixelFormat InFormat=PF_B8G8R8A8, const FName InName=NAME_None)
Creates and initializes a new VolumeTexture with the requested settings.
Data Fields
AdvancedDisplay TEnumAsByte< enum TextureAddress > AddressMode = TA_Wrap
AssetRegistrySearchable
TMap< FString, FTexturePlatformData * > CookedPlatformData
Protected Member Functions
void UpdateMipGenSettings ()
Private Member Functions
GENERATED_UCLASS_BODY () FTexturePlatformData *PrivatePlatformData
The derived data for this texture on this platform.
Detailed Description
Definition at line 16 of file VolumeTexture.h.
Member Function Documentation
CalcCumulativeLODSize()
virtual int32 UVolumeTexture::CalcCumulativeLODSize (int32 NumLODs) const inline final override virtual
Definition at line 137 of file VolumeTexture.h.
References CalcTextureMemorySize().
CalcTextureMemorySize()
uint32 UVolumeTexture::CalcTextureMemorySize (int32 MipCount) const
Calculates the size of this texture in bytes if it had MipCount miplevels streamed in.
Parameters
MipCount Number of mips to calculate size for, counting from the smallest 1x1 mip-level and up.
Returns
Size of MipCount mips in bytes
Referenced by CalcCumulativeLODSize().
CalcTextureMemorySizeEnum()
virtual uint32 UVolumeTexture::CalcTextureMemorySizeEnum (ETextureMipCount Enum) const override virtual
Calculates the size of this texture if it had MipCount miplevels streamed in.
Parameters
Enum Which mips to calculate size for.
Returns
Total size of all specified mips, in bytes
References Enum.
CreateResource()
virtual FTextureResource * UVolumeTexture::CreateResource () override virtual
CreateTransient()
class UVolumeTexture * UVolumeTexture::CreateTransient (int32 InSizeX, int32 InSizeY, int32 InSizeZ, EPixelFormat InFormat = PF_B8G8R8A8, const FName InName = NAME_None) static
Creates and initializes a new VolumeTexture with the requested settings.
References InName, and PF_B8G8R8A8.
GENERATED_UCLASS_BODY()
UVolumeTexture::GENERATED_UCLASS_BODY () private
The derived data for this texture on this platform.
GetAssetRegistryTags()
virtual void UVolumeTexture::GetAssetRegistryTags (FAssetRegistryTagsContext Context) const override virtual
References GetAssetRegistryTags().
Referenced by GetAssetRegistryTags(), and UE_DEPRECATED().
GetCookedPlatformData()
virtual TMap< FString, FTexturePlatformData * > * UVolumeTexture::GetCookedPlatformData () inline override virtual
Definition at line 105 of file VolumeTexture.h.
References CookedPlatformData.
GetDesc()
virtual FString UVolumeTexture::GetDesc () override virtual
References GetDesc().
Referenced by GetDesc().
GetMaterialType()
virtual EMaterialValueType UVolumeTexture::GetMaterialType () const inline override virtual
Definition at line 101 of file VolumeTexture.h.
References MCT_VolumeTexture.
GetMaximumDimension()
virtual uint32 UVolumeTexture::GetMaximumDimension () const override virtual
Return maximum dimension for this texture type.
GetNumMips()
int32 UVolumeTexture::GetNumMips () const
References GetNumMips().
Referenced by GetNumMips().
GetPixelFormat()
EPixelFormat UVolumeTexture::GetPixelFormat () const
References GetPixelFormat().
Referenced by GetPixelFormat().
GetPlatformData() [1/2]
FTexturePlatformData * UVolumeTexture::GetPlatformData ()
Get the derived data for this texture on this platform.
References GetPlatformData().
Referenced by GetPlatformData(), and GetPlatformData().
GetPlatformData() [2/2]
const FTexturePlatformData * UVolumeTexture::GetPlatformData () const
Get the const derived data for this texture on this platform.
References GetPlatformData().
GetResourceSizeEx()
virtual void UVolumeTexture::GetResourceSizeEx (FResourceSizeEx & CumulativeResourceSize) override virtual
References GetResourceSizeEx().
Referenced by GetResourceSizeEx().
GetRunningPlatformData()
virtual FTexturePlatformData ** UVolumeTexture::GetRunningPlatformData () override virtual
GetSizeX()
int32 UVolumeTexture::GetSizeX () const
References GetSizeX().
Referenced by GetSizeX().
GetSizeY()
int32 UVolumeTexture::GetSizeY () const
References GetSizeY().
Referenced by GetSizeY().
GetSizeZ()
int32 UVolumeTexture::GetSizeZ () const
References GetSizeZ().
Referenced by GetSizeZ().
GetSurfaceArraySize()
virtual uint32 UVolumeTexture::GetSurfaceArraySize () const inline override virtual
Definition at line 91 of file VolumeTexture.h.
GetSurfaceDepth()
virtual float UVolumeTexture::GetSurfaceDepth () const inline override virtual
Definition at line 90 of file VolumeTexture.h.
References FTexture::GetSizeZ().
GetSurfaceHeight()
virtual float UVolumeTexture::GetSurfaceHeight () const inline override virtual
Definition at line 89 of file VolumeTexture.h.
References FTexture::GetSizeY().
GetSurfaceWidth()
virtual float UVolumeTexture::GetSurfaceWidth () const inline override virtual
Definition at line 88 of file VolumeTexture.h.
References FTexture::GetSizeX().
GetTextureAddressX()
virtual TextureAddress UVolumeTexture::GetTextureAddressX () const inline override virtual
Definition at line 92 of file VolumeTexture.h.
References AddressMode.
GetTextureAddressY()
virtual TextureAddress UVolumeTexture::GetTextureAddressY () const inline override virtual
Definition at line 93 of file VolumeTexture.h.
References AddressMode.
GetTextureAddressZ()
virtual TextureAddress UVolumeTexture::GetTextureAddressZ () const inline override virtual
Definition at line 94 of file VolumeTexture.h.
References AddressMode.
GetTextureClass()
virtual ETextureClass UVolumeTexture::GetTextureClass () const inline override virtual
Definition at line 87 of file VolumeTexture.h.
References GetTextureClass().
Referenced by GetTextureClass().
IsDefaultTexture()
virtual bool UVolumeTexture::IsDefaultTexture () const override virtual
PostEditChangeProperty()
virtual void UVolumeTexture::PostEditChangeProperty (FPropertyChangedEvent & PropertyChangedEvent) override virtual
PostLoad()
virtual void UVolumeTexture::PostLoad () override virtual
References PostLoad().
Referenced by PostLoad().
Serialize()
virtual void UVolumeTexture::Serialize (FArchive & Ar) override virtual
References Ar, and Serialize().
Referenced by Serialize().
SetDefaultSource2DTileSize()
void UVolumeTexture::SetDefaultSource2DTileSize ()
SetPlatformData()
void UVolumeTexture::SetPlatformData (FTexturePlatformData * PlatformData)
Set the derived data for this texture on this platform.
References SetPlatformData().
Referenced by SetPlatformData().
StreamIn()
virtual bool UVolumeTexture::StreamIn (int32 NewMipCount, bool bHighPrio) final override virtual
StreamOut()
virtual bool UVolumeTexture::StreamOut (int32 NewMipCount) final override virtual
UE_DEPRECATED()
UVolumeTexture::UE_DEPRECATED (5. 4, "Implement the version that takes FAssetRegistryTagsContext instead.") const & override
References GetAssetRegistryTags(), and UE_DEPRECATED().
Referenced by UE_DEPRECATED().
UpdateMipGenSettings()
void UVolumeTexture::UpdateMipGenSettings () protected
UpdateResourceWithParams()
virtual void UVolumeTexture::UpdateResourceWithParams (EUpdateResourceFlags InFlags) override virtual
UpdateSourceFromFunction()
bool UVolumeTexture::UpdateSourceFromFunction (TFunction< void(int32, int32, int32, void *)> Func, int32 SizeX, int32 SizeY, int32 SizeZ, ETextureSourceFormat Format)
Updates a volume texture from a user function, which allows for arbitrary UVolumeTexture objects to be filled.
The pointer passed to the user function is owned by UVolumeTexture and should be cast to the required type before being filled up with the new voxel data.
Parameters
Func A function taking the x, y, z position as input and returning the texture data for this position.
SizeX The width of the volume texture.
SizeY The height of the volume texture.
SizeZ The depth of the volume texture.
Format The input volume texture format.
References Format, and UpdateSourceFromFunction().
Referenced by UpdateSourceFromFunction().
UpdateSourceFromSourceTexture()
bool UVolumeTexture::UpdateSourceFromSourceTexture ()
References UpdateSourceFromSourceTexture().
Referenced by UpdateSourceFromSourceTexture().
UPROPERTY()
UVolumeTexture::UPROPERTY ()
The addressing mode to use for the X, Y and Z axis.
Field Documentation
AddressMode
AdvancedDisplay TEnumAsByte<enum TextureAddress> UVolumeTexture::AddressMode = TA_Wrap
Definition at line 54 of file VolumeTexture.h.
Referenced by GetTextureAddressX(), GetTextureAddressY(), and GetTextureAddressZ().
AssetRegistrySearchable
UVolumeTexture::AssetRegistrySearchable
Definition at line 53 of file VolumeTexture.h.
CookedPlatformData
TMap<FString, FTexturePlatformData*> UVolumeTexture::CookedPlatformData
Definition at line 33 of file VolumeTexture.h.
Referenced by GetCookedPlatformData().
The documentation for this class was generated from the following file:
Runtime/Engine/Classes/Engine/VolumeTexture.h