Unreal Engine 5.6 C++ API: UE::FWindowsSharedMutex Class Reference
UE::FWindowsSharedMutex Class Reference final
A shared (read/write) mutex that does not support recursive locking.
#include "WindowsPlatformMutex.h"
Public Member Functions
FORCEINLINE FWindowsSharedMutex ()
FWindowsSharedMutex (const FWindowsSharedMutex &)=delete
~FWindowsSharedMutex ()
FORCEINLINE void Lock ()
FORCEINLINE void LockShared ()
FWindowsSharedMutex & operator= (const FWindowsSharedMutex &)=delete
FORCEINLINE bool TryLock ()
FORCEINLINE bool TryLockShared ()
FORCEINLINE void Unlock ()
FORCEINLINE void UnlockShared ()
Private Member Functions
bool IsLocked ()
Private Attributes
Windows::SRWLOCK Mutex
Detailed Description
A shared (read/write) mutex that does not support recursive locking.
Prefer FSharedMutex.
SRWLOCK: https://learn.microsoft.com/en-us/windows/win32/sync/slim-reader-writer&ndash;srw&ndash;locks
Definition at line 64 of file WindowsPlatformMutex.h.
Constructor & Destructor Documentation
FWindowsSharedMutex() [1/2]
UE::FWindowsSharedMutex::FWindowsSharedMutex (const FWindowsSharedMutex &) delete
References FWindowsSharedMutex().
Referenced by FWindowsSharedMutex(), and operator=().
FWindowsSharedMutex() [2/2]
FORCEINLINE UE::FWindowsSharedMutex::FWindowsSharedMutex () inline
Definition at line 70 of file WindowsPlatformMutex.h.
References FORCEINLINE, Windows::InitializeSRWLock(), and Mutex.
~FWindowsSharedMutex()
UE::FWindowsSharedMutex::~FWindowsSharedMutex () inline
Definition at line 75 of file WindowsPlatformMutex.h.
References checkf, IsLocked(), and TEXT.
Member Function Documentation
IsLocked()
bool UE::FWindowsSharedMutex::IsLocked () inline private
Definition at line 111 of file WindowsPlatformMutex.h.
References Mutex, Windows::ReleaseSRWLockExclusive(), and Windows::TryAcquireSRWLockExclusive().
Referenced by ~FWindowsSharedMutex().
Lock()
FORCEINLINE void UE::FWindowsSharedMutex::Lock () inline
Definition at line 85 of file WindowsPlatformMutex.h.
References Windows::AcquireSRWLockExclusive(), FORCEINLINE, and Mutex.
LockShared()
FORCEINLINE void UE::FWindowsSharedMutex::LockShared () inline
Definition at line 100 of file WindowsPlatformMutex.h.
References Windows::AcquireSRWLockShared(), FORCEINLINE, and Mutex.
operator=()
FWindowsSharedMutex & UE::FWindowsSharedMutex::operator= (const FWindowsSharedMutex &) delete
References FWindowsSharedMutex().
TryLock()
FORCEINLINE bool UE::FWindowsSharedMutex::TryLock () inline
Definition at line 80 of file WindowsPlatformMutex.h.
References FORCEINLINE, Mutex, and Windows::TryAcquireSRWLockExclusive().
TryLockShared()
FORCEINLINE bool UE::FWindowsSharedMutex::TryLockShared () inline
Definition at line 95 of file WindowsPlatformMutex.h.
References FORCEINLINE, Mutex, and Windows::TryAcquireSRWLockShared().
Unlock()
FORCEINLINE void UE::FWindowsSharedMutex::Unlock () inline
Definition at line 90 of file WindowsPlatformMutex.h.
References FORCEINLINE, Mutex, and Windows::ReleaseSRWLockExclusive().
UnlockShared()
FORCEINLINE void UE::FWindowsSharedMutex::UnlockShared () inline
Definition at line 105 of file WindowsPlatformMutex.h.
References FORCEINLINE, Mutex, and Windows::ReleaseSRWLockShared().
Field Documentation
Mutex
Windows::SRWLOCK UE::FWindowsSharedMutex::Mutex private
Definition at line 121 of file WindowsPlatformMutex.h.
Referenced by FWindowsSharedMutex(), IsLocked(), Lock(), LockShared(), TryLock(), TryLockShared(), Unlock(), and UnlockShared().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Windows/WindowsPlatformMutex.h