Unreal Engine 5.6 C++ API: FMemoryUnfreezeContent Class Reference
FMemoryUnfreezeContent Class Reference
#include "MemoryImageWriter.h"
Public Member Functions
FMemoryUnfreezeContent (const FPointerTableBase *InPointerTable)
FMemoryUnfreezeContent (const FPointerTableBase *InPointerTable, const FPlatformTypeLayoutParameters &InLayoutParams)
const FTypeLayoutDesc * GetDerivedTypeDesc (const FTypeLayoutDesc &StaticTypeDesc, int32 TypeIndex) const
const FPointerTableBase * TryGetPrevPointerTable () const
template<typename T>
uint32 UnfreezeObject (const T &Object, void *OutDst) const
uint32 UnfreezeObject (const void *Object, const FTypeLayoutDesc &TypeDesc, void *OutDst) const
Data Fields
bool bIsFrozenForCurrentPlatform
FPlatformTypeLayoutParameters FrozenLayoutParameters
const FPointerTableBase * PrevPointerTable = nullptr
Detailed Description
Definition at line 77 of file MemoryImageWriter.h.
Constructor & Destructor Documentation
FMemoryUnfreezeContent() [1/2]
FMemoryUnfreezeContent::FMemoryUnfreezeContent (const FPointerTableBase * InPointerTable) inline explicit
Definition at line 80 of file MemoryImageWriter.h.
References bIsFrozenForCurrentPlatform, FrozenLayoutParameters, and PrevPointerTable.
FMemoryUnfreezeContent() [2/2]
FMemoryUnfreezeContent::FMemoryUnfreezeContent (const FPointerTableBase * InPointerTable, const FPlatformTypeLayoutParameters & InLayoutParams) inline
Definition at line 87 of file MemoryImageWriter.h.
References bIsFrozenForCurrentPlatform, FrozenLayoutParameters, and PrevPointerTable.
Member Function Documentation
GetDerivedTypeDesc()
const FTypeLayoutDesc * FMemoryUnfreezeContent::GetDerivedTypeDesc (const FTypeLayoutDesc & StaticTypeDesc, int32 TypeIndex) const
TryGetPrevPointerTable()
const FPointerTableBase * FMemoryUnfreezeContent::TryGetPrevPointerTable () const inline
Definition at line 94 of file MemoryImageWriter.h.
References PrevPointerTable.
Referenced by UnfreezeObject().
UnfreezeObject() [1/2]
template<typename T> uint32 FMemoryUnfreezeContent::UnfreezeObject (const T & Object, void * OutDst) const inline
Definition at line 104 of file MemoryImageWriter.h.
References GetTypeLayoutDesc(), Object, TryGetPrevPointerTable(), and UnfreezeObject().
UnfreezeObject() [2/2]
uint32 FMemoryUnfreezeContent::UnfreezeObject (const void * Object, const FTypeLayoutDesc & TypeDesc, void * OutDst) const inline
Definition at line 98 of file MemoryImageWriter.h.
References Object, and FTypeLayoutDesc::UnfrozenCopyFunc.
Referenced by UnfreezeObject().
Field Documentation
bIsFrozenForCurrentPlatform
bool FMemoryUnfreezeContent::bIsFrozenForCurrentPlatform
Definition at line 114 of file MemoryImageWriter.h.
Referenced by FMemoryUnfreezeContent(), and FMemoryUnfreezeContent().
FrozenLayoutParameters
FPlatformTypeLayoutParameters FMemoryUnfreezeContent::FrozenLayoutParameters
Definition at line 113 of file MemoryImageWriter.h.
Referenced by FMemoryUnfreezeContent(), and FMemoryUnfreezeContent().
PrevPointerTable
const FPointerTableBase* FMemoryUnfreezeContent::PrevPointerTable = nullptr
Definition at line 110 of file MemoryImageWriter.h.
Referenced by FMemoryUnfreezeContent(), FMemoryUnfreezeContent(), and TryGetPrevPointerTable().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Serialization/MemoryImageWriter.h