Unreal Engine 5.6 C++ API: FMemStackBase Class Reference
FMemStackBase Class Reference
Simple linear-allocation memory stack.
#include "MemStack.h"
Data Structures
struct FTaggedMemory
Public Types
enum class EPageSize : uint8 { Small , Large }
Public Member Functions
FMemStackBase (const FMemStackBase &)=delete
FMemStackBase (EPageSize PageSize=EPageSize::Small)
FMemStackBase (FMemStackBase &&Other)
~FMemStackBase ()
FORCEINLINE void * Alloc (size_t AllocSize, size_t Alignment)
FORCEINLINE bool CanFitInPage (size_t AllocSize, size_t Alignment) const
bool ContainsPointer (const void *Pointer) const
FORCEINLINE void Flush ()
int32 GetByteCount () const
FORCEINLINE int32 GetNumMarks ()
FORCEINLINE uint8 * GetTop () const
FORCEINLINE bool IsEmpty () const
return true if this stack is empty.
FMemStackBase & operator= (FMemStackBase &&Other)
FORCEINLINE uint8 * PushBytes (size_t AllocSize, size_t Alignment)
Protected Attributes
bool bShouldEnforceAllocMarks = false
Private Member Functions
void AllocateNewChunk (int32 MinSize)
Allocate a new chunk of memory of at least MinSize size, updates the memory stack's Chunks table and ActiveChunks counter.
void FreeChunks (FTaggedMemory *NewTopChunk)
Frees the chunks above the specified chunk on the stack.
Private Attributes
uint8 * End = nullptr
int32 NumMarks = 0
The number of marks on this stack.
EPageSize PageSize = EPageSize::Small
The page size to use when allocating.
uint8 * Top = nullptr
FTaggedMemory * TopChunk = nullptr
class FMemMark * TopMark = nullptr
The top mark on the stack.
Friends
class FMemMark
void * operator new (size_t Size, FMemStackBase &Mem, EMemOned Tag, int32 Count=1)
void * operator new (size_t Size, FMemStackBase &Mem, EMemZeroed Tag, int32 Count=1)
void * operator new (size_t Size, FMemStackBase &Mem, int32 Count=1)
void * operator new (size_t Size, std::align_val_t Align, FMemStackBase &Mem, EMemOned Tag, int32 Count=1)
void * operator new (size_t Size, std::align_val_t Align, FMemStackBase &Mem, EMemZeroed Tag, int32 Count=1)
void * operator new (size_t Size, std::align_val_t Align, FMemStackBase &Mem, int32 Count=1)
void * operator new[] (size_t Size, FMemStackBase &Mem, EMemOned Tag, int32 Count=1)
void * operator new[] (size_t Size, FMemStackBase &Mem, EMemZeroed Tag, int32 Count=1)
void * operator new[] (size_t Size, FMemStackBase &Mem, int32 Count=1)
void * operator new[] (size_t Size, std::align_val_t Align, FMemStackBase &Mem, EMemOned Tag, int32 Count=1)
void * operator new[] (size_t Size, std::align_val_t Align, FMemStackBase &Mem, EMemZeroed Tag, int32 Count=1)
void * operator new[] (size_t Size, std::align_val_t Align, FMemStackBase &Mem, int32 Count=1)
Detailed Description
Simple linear-allocation memory stack.
Items are allocated via PushBytes() or the specialized operator new()s. Items are freed en masse by using FMemMark to Pop() them.
Definition at line 77 of file MemStack.h.
Member Enumeration Documentation
EPageSize
enum class FMemStackBase::EPageSize : uint8 strong
Enumerator
Small
Large
Definition at line 80 of file MemStack.h.
Constructor & Destructor Documentation
FMemStackBase() [1/3]
FMemStackBase::FMemStackBase (EPageSize PageSize = EPageSize::Small)
References PageSize, and Small.
Referenced by FMemStackBase(), FMemStackBase(), FMemMark, operator new, operator new, operator new, operator new, operator new, operator new, operator new[], operator new[], operator new[], operator new[], operator new[], operator new[], and operator=().
FMemStackBase() [2/3]
FMemStackBase::FMemStackBase (const FMemStackBase &) delete
References FMemStackBase().
FMemStackBase() [3/3]
FMemStackBase::FMemStackBase (FMemStackBase && Other) inline
Definition at line 92 of file MemStack.h.
References FMemStackBase(), MoveTemp(), and Other.
~FMemStackBase()
FMemStackBase::~FMemStackBase () inline
Definition at line 114 of file MemStack.h.
References check, FreeChunks(), GIsCriticalError, and NumMarks.
Member Function Documentation
Alloc()
FORCEINLINE void * FMemStackBase::Alloc (size_t AllocSize, size_t Alignment) inline
Definition at line 132 of file MemStack.h.
References Align, AllocateNewChunk(), bShouldEnforceAllocMarks, check, checkSlow, End, FORCEINLINE, NumMarks, and Top.
Referenced by PushBytes().
AllocateNewChunk()
void FMemStackBase::AllocateNewChunk (int32 MinSize) private
Allocate a new chunk of memory of at least MinSize size, updates the memory stack's Chunks table and ActiveChunks counter.
References MinSize.
Referenced by Alloc().
CanFitInPage()
FORCEINLINE bool FMemStackBase::CanFitInPage (size_t AllocSize, size_t Alignment) const inline
Definition at line 125 of file MemStack.h.
References Align, End, FORCEINLINE, and Top.
ContainsPointer()
bool FMemStackBase::ContainsPointer (const void * Pointer) const
References Pointer.
Flush()
FORCEINLINE void FMemStackBase::Flush () inline
Definition at line 171 of file MemStack.h.
References check, FORCEINLINE, FreeChunks(), and NumMarks.
FreeChunks()
void FMemStackBase::FreeChunks (FTaggedMemory * NewTopChunk) private
Frees the chunks above the specified chunk on the stack.
Referenced by ~FMemStackBase(), Flush(), and operator=().
GetByteCount()
int32 FMemStackBase::GetByteCount () const
Returns
the number of bytes allocated for this FMemStack that are currently in use.
GetNumMarks()
FORCEINLINE int32 FMemStackBase::GetNumMarks () inline
Definition at line 176 of file MemStack.h.
References FORCEINLINE, and NumMarks.
GetTop()
FORCEINLINE uint8 * FMemStackBase::GetTop () const inline
Definition at line 160 of file MemStack.h.
References FORCEINLINE, and Top.
IsEmpty()
FORCEINLINE bool FMemStackBase::IsEmpty () const inline
return true if this stack is empty.
Definition at line 166 of file MemStack.h.
References FORCEINLINE, and TopChunk.
operator=()
FMemStackBase & FMemStackBase::operator= (FMemStackBase && Other) inline
Definition at line 97 of file MemStack.h.
References FMemStackBase(), bShouldEnforceAllocMarks, End, FreeChunks(), NumMarks, Other, Top, TopChunk, and TopMark.
PushBytes()
FORCEINLINE uint8 * FMemStackBase::PushBytes (size_t AllocSize, size_t Alignment) inline
Definition at line 120 of file MemStack.h.
References Alloc(), FORCEINLINE, and FMath::Max.
Referenced by New(), NewOned(), and NewZeroed().
Friends And Related Symbol Documentation
FMemMark
friend class FMemMark friend
Definition at line 187 of file MemStack.h.
References FMemStackBase(), Align(), Count, FMemMark, and TSequenceHistory< HistorySize >::Size.
Referenced by FMemMark.
operator new [1/6]
void * operator new (size_t Size, FMemStackBase & Mem, EMemOned Tag, int32 Count = 1) friend
Definition at line 314 of file MemStack.h.
References FMemStackBase(), checkSlow, Count, FMemory::Memset(), and TSequenceHistory< HistorySize >::Size.
operator new [2/6]
void * operator new (size_t Size, FMemStackBase & Mem, EMemZeroed Tag, int32 Count = 1) friend
Definition at line 296 of file MemStack.h.
References FMemStackBase(), checkSlow, Count, FMemory::Memzero(), and TSequenceHistory< HistorySize >::Size.
operator new [3/6]
void * operator new (size_t Size, FMemStackBase & Mem, int32 Count = 1) friend
Definition at line 282 of file MemStack.h.
References FMemStackBase(), checkSlow, Count, and TSequenceHistory< HistorySize >::Size.
operator new [4/6]
void * operator new (size_t Size, std::align_val_t Align, FMemStackBase & Mem, EMemOned Tag, int32 Count = 1) friend
Definition at line 323 of file MemStack.h.
References FMemStackBase(), Align(), checkSlow, Count, FMemory::Memset(), and TSequenceHistory< HistorySize >::Size.
operator new [5/6]
void * operator new (size_t Size, std::align_val_t Align, FMemStackBase & Mem, EMemZeroed Tag, int32 Count = 1) friend
Definition at line 305 of file MemStack.h.
References FMemStackBase(), Align(), checkSlow, Count, FMemory::Memzero(), and TSequenceHistory< HistorySize >::Size.
operator new [6/6]
void * operator new (size_t Size, std::align_val_t Align, FMemStackBase & Mem, int32 Count = 1) friend
Definition at line 289 of file MemStack.h.
References FMemStackBase(), Align(), checkSlow, Count, and TSequenceHistory< HistorySize >::Size.
operator new[] [1/6]
void * operator new[] (size_t Size, FMemStackBase & Mem, EMemOned Tag, int32 Count = 1) friend
Definition at line 364 of file MemStack.h.
References FMemStackBase(), checkSlow, Count, FMemory::Memset(), and TSequenceHistory< HistorySize >::Size.
operator new[] [2/6]
void * operator new[] (size_t Size, FMemStackBase & Mem, EMemZeroed Tag, int32 Count = 1) friend
Definition at line 346 of file MemStack.h.
References FMemStackBase(), checkSlow, Count, FMemory::Memzero(), and TSequenceHistory< HistorySize >::Size.
operator new[] [3/6]
void * operator new[] (size_t Size, FMemStackBase & Mem, int32 Count = 1) friend
Definition at line 332 of file MemStack.h.
References FMemStackBase(), checkSlow, Count, and TSequenceHistory< HistorySize >::Size.
operator new[] [4/6]
void * operator new[] (size_t Size, std::align_val_t Align, FMemStackBase & Mem, EMemOned Tag, int32 Count = 1) friend
Definition at line 373 of file MemStack.h.
References FMemStackBase(), Align(), checkSlow, Count, FMemory::Memset(), and TSequenceHistory< HistorySize >::Size.
operator new[] [5/6]
void * operator new[] (size_t Size, std::align_val_t Align, FMemStackBase & Mem, EMemZeroed Tag, int32 Count = 1) friend
Definition at line 355 of file MemStack.h.
References FMemStackBase(), Align(), checkSlow, Count, FMemory::Memzero(), and TSequenceHistory< HistorySize >::Size.
operator new[] [6/6]
void * operator new[] (size_t Size, std::align_val_t Align, FMemStackBase & Mem, int32 Count = 1) friend
Definition at line 339 of file MemStack.h.
References FMemStackBase(), Align(), checkSlow, Count, and TSequenceHistory< HistorySize >::Size.
Field Documentation
bShouldEnforceAllocMarks
bool FMemStackBase::bShouldEnforceAllocMarks = false protected
Definition at line 239 of file MemStack.h.
Referenced by Alloc(), and operator=().
End
uint8* FMemStackBase::End = nullptr private
Definition at line 226 of file MemStack.h.
Referenced by Alloc(), CanFitInPage(), and operator=().
NumMarks
int32 FMemStackBase::NumMarks = 0 private
The number of marks on this stack.
Definition at line 233 of file MemStack.h.
Referenced by ~FMemStackBase(), Alloc(), Flush(), GetNumMarks(), and operator=().
PageSize
EPageSize FMemStackBase::PageSize = EPageSize::Small private
The page size to use when allocating.
Definition at line 236 of file MemStack.h.
Referenced by FMemStackBase().
Top
uint8* FMemStackBase::Top = nullptr private
Definition at line 225 of file MemStack.h.
Referenced by Alloc(), CanFitInPage(), GetTop(), and operator=().
TopChunk
FTaggedMemory* FMemStackBase::TopChunk = nullptr private
Definition at line 227 of file MemStack.h.
Referenced by IsEmpty(), and operator=().
TopMark
class FMemMark* FMemStackBase::TopMark = nullptr private
The top mark on the stack.
Definition at line 230 of file MemStack.h.
Referenced by operator=().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Misc/MemStack.h