Unreal Engine 5.6 C++ API: SEditableText Class Reference
SEditableText Class Reference
Editable text widget.
#include "SEditableText.h"
Public Member Functions
~SEditableText ()
Destructor.
void AdvanceSearch (const bool InReverse=false)
Advance the current search to the next match (does nothing if not currently searching)
bool AnyTextSelected () const
Query to see if any text is selected within the document.
void BeginSearch (const FText &InSearchText, const ESearchCase::Type InSearchCase=ESearchCase::IgnoreCase, const bool InReverse=false)
Begin a new text search (this is called automatically when the bound search text changes)
void ClearSelection ()
Clear the active text selection.
void Construct (const FArguments &InArgs)
Construct this widget.
void EnableTextInputMethodContext ()
Register and activate the IME context for this text layout.
FSlateFontInfo GetFont () const
Gets the font used to draw the text.
FText GetHintText () const
Get the text that appears when there is no text in the text box.
FText GetSearchText () const
Get the text that is currently being searched for (if any)
FText GetSelectedText () const
Get the currently selected text.
FTextSelection GetSelection () const
Get the current selection.
FText GetText () const
Returns the text string.
void GoTo (const ETextLocation NewLocation)
Move the cursor specified location.
void GoTo (const FTextLocation &NewLocation)
Move the cursor to the given location in the document (will also scroll to this point)
virtual bool IsIntegratedKeyboardEnabled () const override
Is the widget currently has IntegratedKeyboard enabled?
virtual bool IsMultiLineTextEdit () const override
Is the text edit multi-line aware?
virtual bool IsTextPassword () const override
Is the text displaying a password and should be obscured?
virtual bool IsTextReadOnly () const override
Is the text currently read-only?
void ScrollTo (const ETextLocation NewLocation)
Scroll to the given location in the document (without moving the cursor)
void ScrollTo (const FTextLocation &NewLocation)
Scroll to the given location in the document (without moving the cursor)
void SelectAllText ()
Select all the text in the document.
void SelectText (const FTextLocation &InSelectionStart, const FTextLocation &InCursorLocation)
Select a block of text.
void SetAllowContextMenu (const TAttribute< bool > &InAllowContextMenu)
See the AllowContextMenu attribute.
void SetClearKeyboardFocusOnCommit (const TAttribute< bool > &InClearKeyboardFocusOnCommit)
Sets whether to clear keyboard focus when pressing enter to commit changes.
void SetColorAndOpacity (TAttribute< FSlateColor > Color)
See the ColorAndOpacity attribute.
bool SetEditableText (const FText &InNewText)
Sets the text currently being edited Note: Doesn't override the bound Text attribute, nor does it call OnTextChanged.
void SetEnableIntegratedKeyboard (const TAttribute< bool > &InEnableIntegratedKeyboard)
See the EnableIntegratedKeyboard attribute.
void SetFont (const TAttribute< FSlateFontInfo > &InNewFont)
Sets the font used to draw the text.
void SetHintText (const TAttribute< FText > &InHintText)
See the HintText attribute.
void SetIsCaretMovedWhenGainFocus (const TAttribute< bool > &InIsCaretMovedWhenGainFocus)
Workaround as we loose focus when the auto completion closes.
void SetIsPassword (TAttribute< bool > InIsPassword)
See the IsPassword attribute.
void SetIsReadOnly (TAttribute< bool > InIsReadOnly)
See the IsReadOnly attribute.
void SetJustification (const TAttribute< ETextJustify::Type > &InJustification)
See Justification attribute.
void SetMinDesiredWidth (const TAttribute< float > &InMinDesiredWidth)
Sets the minimum width that a text block should be.
void SetOnKeyCharHandler (FOnKeyChar InOnKeyCharHandler)
Sets the OnKeyCharHandler to provide first chance handling of the OnKeyChar event.
void SetOnKeyDownHandler (FOnKeyDown InOnKeyDownHandler)
Sets the OnKeyDownHandler to provide first chance handling of the OnKeyDown event.
void SetOverflowPolicy (TOptional< ETextOverflowPolicy > InOverflowPolicy)
Sets the overflow policy for this text block.
void SetRevertTextOnEscape (const TAttribute< bool > &InRevertTextOnEscape)
Sets whether to allow the user to back out of changes when they press the escape key.
void SetSearchText (const TAttribute< FText > &InSearchText)
Set the text that is currently being searched for (if any)
void SetSelectAllTextOnCommit (const TAttribute< bool > &InSelectAllTextOnCommit)
Sets whether to select all text when pressing enter to commit changes.
void SetSelectAllTextWhenFocused (const TAttribute< bool > &InSelectAllTextWhenFocused)
Sets whether to select all text when the user clicks to give focus on the widget.
void SetSelectWordOnMouseDoubleClick (const TAttribute< bool > &InSelectWordOnMouseDoubleClick)
Sets whether to select word on the mouse double click.
void SetText (const TAttribute< FText > &InNewText)
Sets the text currently being edited.
void SetTextBlockStyle (const FTextBlockStyle *InTextStyle)
@See TextStyle
void SetTextFlowDirection (const TOptional< ETextFlowDirection > &InTextFlowDirection)
See TextFlowDirection attribute.
void SetTextShapingMethod (const TOptional< ETextShapingMethod > &InTextShapingMethod)
See TextShapingMethod attribute.
void SetTextStyle (const FEditableTextStyle &InNewTextStyle)
Sets the text style used to draw the text.
void SetVirtualKeyboardDismissAction (TAttribute< EVirtualKeyboardDismissAction > InVirtualKeyboardDismissAction)
Set the VirtualKeyboardDismissAction attribute.
HintText Style ColorAndOpacity BackgroundImageComposing IsReadOnly IsCaretMovedWhenGainFocus SelectWordOnMouseDoubleClick ClearKeyboardFocusOnCommit AllowContextMenu OnContextMenuOpening OnTextChanged MinDesiredWidth OnKeyCharHandler ContextMenuExtender VirtualKeyboardOptions VirtualKeyboardDismissAction TextFlowDirection SLATE_ARGUMENT (TOptional< ETextOverflowPolicy >, OverflowPolicy) SLATE_END_ARGS() 1 SEditableText()
Determines what happens to text that is clipped and doesnt fit within the allotted area for this widget.
HintText Style ColorAndOpacity BackgroundImageComposing IsReadOnly IsCaretMovedWhenGainFocus SelectWordOnMouseDoubleClick ClearKeyboardFocusOnCommit AllowContextMenu OnContextMenuOpening OnTextChanged MinDesiredWidth OnKeyCharHandler ContextMenuExtender VirtualKeyboardOptions VirtualKeyboardDismissAction SLATE_ARGUMENT (TOptional< ETextShapingMethod >, TextShapingMethod) SLATE_ARGUMENT(TOptional< ETextFlowDirection >
Which text shaping method should we use?
HintText Style ColorAndOpacity BackgroundImageComposing IsReadOnly IsCaretMovedWhenGainFocus SelectWordOnMouseDoubleClick ClearKeyboardFocusOnCommit AllowContextMenu SLATE_ATTRIBUTE (bool, EnableIntegratedKeyboard) SLATE_EVENT(FOnContextMenuOpening
Whether the IntegratedKeyboard is enabled.
HintText Style ColorAndOpacity BackgroundImageComposing IsReadOnly SLATE_ATTRIBUTE (bool, IsPassword) SLATE_ATTRIBUTE(bool
Sets whether this text box is for storing a password.
HintText Style ColorAndOpacity BackgroundImageComposing IsReadOnly IsCaretMovedWhenGainFocus SelectWordOnMouseDoubleClick SLATE_ATTRIBUTE (bool, RevertTextOnEscape) SLATE_ATTRIBUTE(bool
Whether to allow the user to back out of changes when they press the escape key.
HintText Style ColorAndOpacity BackgroundImageComposing IsReadOnly IsCaretMovedWhenGainFocus SelectWordOnMouseDoubleClick ClearKeyboardFocusOnCommit AllowContextMenu OnContextMenuOpening OnTextChanged MinDesiredWidth SLATE_ATTRIBUTE (bool, SelectAllTextOnCommit) SLATE_EVENT(FOnKeyChar
Whether to select all text when pressing enter to commit changes.
HintText Style ColorAndOpacity BackgroundImageComposing IsReadOnly IsCaretMovedWhenGainFocus SLATE_ATTRIBUTE (bool, SelectAllTextWhenFocused) SLATE_ATTRIBUTE(bool
Whether to select all text when the user clicks to give focus on the widget.
HintText Style ColorAndOpacity SLATE_ATTRIBUTE (const FSlateBrush *, BackgroundImageSelected) SLATE_ATTRIBUTE(const FSlateBrush *
Background image for the selected text (overrides Style)
HintText Style ColorAndOpacity BackgroundImageComposing SLATE_ATTRIBUTE (const FSlateBrush *, CaretImage) SLATE_ATTRIBUTE(bool
Image brush used for the caret (overrides Style)
HintText Style ColorAndOpacity BackgroundImageComposing IsReadOnly IsCaretMovedWhenGainFocus SelectWordOnMouseDoubleClick ClearKeyboardFocusOnCommit AllowContextMenu OnContextMenuOpening OnTextChanged MinDesiredWidth OnKeyCharHandler ContextMenuExtender SLATE_ATTRIBUTE (EKeyboardType, VirtualKeyboardType) SLATE_ARGUMENT(FVirtualKeyboardOptions
The type of virtual keyboard to use on mobile devices.
HintText Style ColorAndOpacity BackgroundImageComposing IsReadOnly IsCaretMovedWhenGainFocus SelectWordOnMouseDoubleClick ClearKeyboardFocusOnCommit SLATE_ATTRIBUTE (ETextJustify::Type, Justification) SLATE_ATTRIBUTE(bool
How should the value be justified in the editable text field.
HintText Style ColorAndOpacity BackgroundImageComposing IsReadOnly IsCaretMovedWhenGainFocus SelectWordOnMouseDoubleClick ClearKeyboardFocusOnCommit AllowContextMenu OnContextMenuOpening OnTextChanged MinDesiredWidth OnKeyCharHandler ContextMenuExtender VirtualKeyboardOptions SLATE_ATTRIBUTE (EVirtualKeyboardTrigger, VirtualKeyboardTrigger) SLATE_ATTRIBUTE(EVirtualKeyboardDismissAction
The type of event that will trigger the display of the virtual keyboard.
HintText Style SLATE_ATTRIBUTE (FSlateFontInfo, Font) SLATE_ATTRIBUTE(FSlateColor
Sets the font used to draw the text (overrides Style)
HintText SLATE_ATTRIBUTE (FText, SearchText) SLATE_STYLE_ARGUMENT(FEditableTextStyle
Text to search for (a new search is triggered whenever this text changes)
SLATE_ATTRIBUTE (FText, Text) SLATE_ATTRIBUTE(FText
Sets the text content for this editable text widget.
SLATE_BEGIN_ARGS (SEditableText)
HintText Style ColorAndOpacity BackgroundImageComposing IsReadOnly IsCaretMovedWhenGainFocus SelectWordOnMouseDoubleClick ClearKeyboardFocusOnCommit AllowContextMenu OnContextMenuOpening SLATE_EVENT (FOnIsTypedCharValid, OnIsTypedCharValid) SLATE_EVENT(FOnTextChanged
This is NOT for validating input!
HintText Style ColorAndOpacity BackgroundImageComposing IsReadOnly IsCaretMovedWhenGainFocus SelectWordOnMouseDoubleClick ClearKeyboardFocusOnCommit AllowContextMenu OnContextMenuOpening OnTextChanged MinDesiredWidth OnKeyCharHandler SLATE_EVENT (FOnKeyDown, OnKeyDownHandler) SLATE_EVENT(FMenuExtensionDelegate
Callback delegate to have first chance handling of the OnKeyDown event.
HintText Style ColorAndOpacity BackgroundImageComposing IsReadOnly IsCaretMovedWhenGainFocus SelectWordOnMouseDoubleClick ClearKeyboardFocusOnCommit AllowContextMenu OnContextMenuOpening OnTextChanged SLATE_EVENT (FOnTextCommitted, OnTextCommitted) SLATE_ATTRIBUTE(float
Called whenever the text is committed.
Public Member Functions inherited from SWidget
template<typename MetaDataType>
void AddMetadata (const TSharedRef< MetaDataType > &AddMe)
Add metadata to this widget.
virtual const FSlateInvalidationRoot * Advanced_AsInvalidationRoot () const
FORCEINLINE TSharedPtr< SWidget > Advanced_GetPaintParentWidget () const
virtual bool Advanced_IsInvalidationRoot () const
virtual bool Advanced_IsWindow () const
Is this widget derivative of SWindow.
void ArrangeChildren (const FGeometry &AllottedGeometry, FArrangedChildren &ArrangedChildren, bool bUpdateAttributes=false) const
Non-virtual entry point for arrange children.
void AssignParentWidget (TSharedPtr< SWidget > InParent)
FORCEINLINE void CacheVolatility ()
Recalculates volatility of the widget and caches the result.
FSlateRect CalculateCullingAndClippingRules (const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, bool &bClipToBounds, bool &bAlwaysClip, bool &bIntersectClipBounds) const
Calculates what if any clipping state changes need to happen when drawing this widget.
bool ConditionallyDetatchParentWidget (SWidget *InExpectedParent)
void EnableToolTipForceField (const bool bEnableForceField)
Sets whether this widget is a "tool tip force field".
FORCEINLINE void ForceVolatile (bool bForce)
Should this widget always appear as volatile for any layout caching host widget.
virtual FChildren * GetAllChildren ()
Returns the children (if any) of this widget that are used by the invalidation system.
template<typename MetaDataType>
TArray< TSharedRef< MetaDataType > > GetAllMetaData () const
Get all metadata of the type provided.
const FGeometry & GetCachedGeometry () const
bool GetCanTick () const
FORCEINLINE EWidgetClipping GetClipping () const
FName GetCreatedInLocation () const
FORCEINLINE FMargin GetCullingBoundsExtension () const
const TOptional< FSlateClippingState > & GetCurrentClippingState () const
Returns the clipping state to clip this widget against its parent.
UE::Slate::FDeprecateVector2DResult GetDesiredSize () const
virtual FSlateColor GetDisabledForegroundColor () const
EFlowDirectionPreference GetFlowDirectionPreference () const
Gets the desired flow direction for the layout.
virtual FSlateColor GetForegroundColor () const
template<typename MetaDataType>
TSharedPtr< MetaDataType > GetMetaData () const
Get the metadata of the type provided.
const FGeometry & GetPaintSpaceGeometry () const
Gets the last geometry used to Tick the widget.
FORCEINLINE TSharedPtr< SWidget > GetParentWidget () const
const FSlateWidgetPersistentState & GetPersistentState () const
FORCEINLINE EWidgetPixelSnapping GetPixelSnapping () const
const FWidgetProxyHandle GetProxyHandle () const
virtual FString GetReadableLocation () const
virtual float GetRelativeLayoutScale (const int32 ChildIndex, float LayoutScaleMultiplier) const
What is the Child's scale relative to this widget.
FORCEINLINE float GetRenderOpacity () const
FORCEINLINE const TOptional< FSlateRenderTransform > & GetRenderTransform () const
FORCEINLINE UE::Slate::FDeprecateVector2DResult GetRenderTransformPivot () const
FORCEINLINE UE::Slate::FDeprecateVector2DResult GetRenderTransformPivotWithRespectToFlowDirection () const
FORCEINLINE TOptional< FSlateRenderTransform > GetRenderTransformWithRespectToFlowDirection () const
FORCEINLINE TStatId GetStatID (bool bForDeferredUse=false) const
virtual FName GetTag () const
const FGeometry & GetTickSpaceGeometry () const
Gets the last geometry used to Tick the widget.
virtual TSharedPtr< IToolTip > GetToolTip ()
FName GetType () const
FString GetTypeAsString () const
FORCEINLINE EVisibility GetVisibility () const
virtual EWindowZone::Type GetWindowZoneOverride () const
Called when the mouse is moved over the widget's window, to determine if we should report whether OS-specific features should be active at this location (such as a title bar grip, system menu, etc.) Usually you should not need to override this function.
bool HasActiveTimers () const
Does this widget have any active timers?
bool HasAnyUpdateFlags (EWidgetUpdateFlags FlagsToCheck) const
TOptional< EFocusCause > HasAnyUserFocus () const
Gets whether or not any users have this widget focused, and if so the type of focus (first one found).
bool HasAnyUserFocusOrFocusedDescendants () const
bool HasFocusedDescendants () const
virtual bool HasKeyboardFocus () const
Checks to see if this widget currently has the keyboard focus.
bool HasMouseCapture () const
Checks to see if this widget is the current mouse captor.
bool HasMouseCaptureByUser (int32 UserIndex, TOptional< int32 > PointerIndex=TOptional< int32 >()) const
Checks to see if this widget has mouse capture from the provided user.
bool HasRegisteredSlateAttribute () const
bool HasToolTipForceField () const
TOptional< EFocusCause > HasUserFocus (int32 UserIndex) const
Gets whether or not the specified users has this widget focused, and if so the type of focus.
bool HasUserFocusedDescendants (int32 UserIndex) const
Gets whether or not the specified users has this widget or any descendant focused.
void Invalidate (EInvalidateWidgetReason InvalidateReason)
Invalidates the widget from the view of a layout caching widget that may own this widget.
bool IsAttributesUpdatesEnabled () const
bool IsDirectlyHovered () const
FORCEINLINE bool IsEnabled () const
bool IsHovered () const
FORCEINLINE bool IsParentValid () const
FORCEINLINE bool IsVolatile () const
Whether or not a widget is volatile and will update every frame without being invalidated.
FORCEINLINE bool IsVolatileIndirectly () const
This widget is volatile because its parent or some ancestor is volatile.
void MarkPrepassAsDirty ()
In fast path, if the widget is mark, do a full Prepass on its next update to calculate it's desired size.
bool NeedsPrepass () const
virtual FReply OnAnalogValueChanged (const FGeometry &MyGeometry, const FAnalogInputEvent &InAnalogInputEvent)
Called when an analog value changes on a button that supports analog.
virtual FReply OnDragDetected (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Called when Slate detects that a widget started to be dragged.
virtual void OnDragEnter (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent)
Called during drag and drop when the drag enters a widget.
virtual void OnDragLeave (const FDragDropEvent &DragDropEvent)
Called during drag and drop when the drag leaves a widget.
virtual void OnFinishedKeyInput ()
All the key (keyboard, gamepay, joystick, etc.) input from this frame has been routed.
virtual void OnFinishedPointerInput ()
All the pointer (mouse, touch, stylus, etc.) events from this frame have been routed.
virtual void OnFocusChanging (const FWeakWidgetPath &PreviousFocusPath, const FWidgetPath &NewWidgetPath, const FFocusEvent &InFocusEvent)
Called whenever a focus path is changing on all the widgets within the old and new focus paths.
virtual TOptional< TSharedRef< SWidget > > OnMapCursor (const FCursorReply &CursorReply) const
After OnCursorQuery has specified a cursor type the system asks each widget under the mouse to map that cursor to a widget.
virtual FReply OnMotionDetected (const FGeometry &MyGeometry, const FMotionEvent &InMotionEvent)
Called when motion is detected (controller or device) e.g.
virtual void OnMouseCaptureLost (const FCaptureLostEvent &CaptureLostEvent)
Called when this widget had captured the mouse, but that capture has been revoked for some reason.
virtual void OnMouseEnter (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
The system will use this event to notify a widget that the cursor has entered it.
virtual void OnMouseLeave (const FPointerEvent &MouseEvent)
The system will use this event to notify a widget that the cursor has left it.
virtual FReply OnMouseWheel (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Called when the mouse wheel is spun.
virtual FNavigationReply OnNavigation (const FGeometry &MyGeometry, const FNavigationEvent &InNavigationEvent)
Called when navigation is requested e.g.
virtual FReply OnPreviewKeyDown (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
Called after a key is pressed when this widget or a child of this widget has focus If a widget handles this event, OnKeyDown will not be passed to the focused widget.
virtual FReply OnPreviewMouseButtonDown (const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)
Just like OnMouseButtonDown, but tunnels instead of bubbling.
virtual FPopupMethodReply OnQueryPopupMethod () const
Popups can manifest in a NEW OS WINDOW or via an OVERLAY in an existing window.
virtual TOptional< bool > OnQueryShowFocus (const EFocusCause InFocusCause) const
Called to determine if we should render the focus brush.
virtual void OnToolTipClosing ()
Called when a tooltip displayed from this widget is being closed.
virtual FReply OnTouchEnded (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is ended (finger lifted)
virtual FReply OnTouchFirstMove (const FGeometry &MyGeometry, const FPointerEvent &TouchEvent)
Called when a touchpad touch first moves after TouchStarted.
virtual FReply OnTouchForceChanged (const FGeometry &MyGeometry, const FPointerEvent &TouchEvent)
Called when a touchpad touch force changes.
virtual FReply OnTouchGesture (const FGeometry &MyGeometry, const FPointerEvent &GestureEvent)
Called when the user performs a gesture on trackpad.
virtual FReply OnTouchMoved (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is moved (finger moved)
virtual FReply OnTouchStarted (const FGeometry &MyGeometry, const FPointerEvent &InTouchEvent)
Called when a touchpad touch is started (finger down)
virtual TSharedPtr< FPopupLayer > OnVisualizePopup (const TSharedRef< SWidget > &PopupContent)
Visualize a new pop-up if possible.
virtual bool OnVisualizeTooltip (const TSharedPtr< SWidget > &TooltipContent)
Called when Slate wants to visualize tooltip.
int32 Paint (const FPaintArgs &Args, const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, FSlateWindowElementList &OutDrawElements, int32 LayerId, const FWidgetStyle &InWidgetStyle, bool bParentEnabled) const
Called to tell a widget to paint itself (and it's children).
TSharedRef< FActiveTimerHandle > RegisterActiveTimer (float TickPeriod, FWidgetActiveTimerDelegate TickFunction)
Registers an "active timer" delegate that will execute at some regular interval.
template<typename MetaDataType>
int32 RemoveMetaData (const TSharedRef< MetaDataType > &RemoveMe)
Remove metadata to this widget.
void SetCanTick (bool bInCanTick)
void SetClipping (EWidgetClipping InClipping)
Sets the clipping to bounds rules for this widget.
FORCEINLINE void SetCullingBoundsExtension (const FMargin &InCullingBoundsExtension)
Sets an additional culling padding that is added to a widget to give more leeway when culling widgets.
void SetCursor (const TAttribute< TOptional< EMouseCursor::Type > > &InCursor)
Set the cursor that should appear when this widget is hovered.
void SetEnabled (TAttribute< bool > InEnabledState)
Sets the enabled state of this widget.
void SetFlowDirectionPreference (EFlowDirectionPreference InFlowDirectionPreference)
Sets how content should flow in this panel, based on the current culture.
void SetOnMouseButtonDown (FPointerEventHandler EventHandler)
See OnMouseButtonDown event.
void SetOnMouseButtonUp (FPointerEventHandler EventHandler)
See OnMouseButtonUp event.
void SetOnMouseDoubleClick (FPointerEventHandler EventHandler)
See OnMouseDoubleClick event.
void SetOnMouseEnter (FNoReplyPointerEventHandler EventHandler)
See OnMouseEnter event.
void SetOnMouseLeave (FSimpleNoReplyPointerEventHandler EventHandler)
See OnMouseLeave event.
void SetOnMouseMove (FPointerEventHandler EventHandler)
See OnMouseMove event.
void SetPixelSnapping (EWidgetPixelSnapping InPixelSnappingMethod)
Sets the pixel snapping method for this widget.
FORCEINLINE void SetRenderOpacity (float InRenderOpacity)
FORCEINLINE void SetRenderTransform (TAttribute< TOptional< FSlateRenderTransform > > InTransform)
FORCEINLINE void SetRenderTransformPivot (TAttribute< FVector2D > InTransformPivot)
FORCEINLINE void SetTag (FName InTag)
void SetToolTip (const TAttribute< TSharedPtr< IToolTip > > &InToolTip)
Set the tool tip that should appear when this widget is hovered.
void SetToolTipText (const FText &InToolTipText)
Set the tool tip that should appear when this widget is hovered.
void SetToolTipText (const TAttribute< FText > &ToolTipText)
Set the tool tip that should appear when this widget is hovered.
virtual void SetVisibility (TAttribute< EVisibility > InVisibility)
FORCEINLINE bool ShouldInvalidatePrepassDueToVolatility ()
void SlatePrepass ()
DEPRECATED version of SlatePrepass that assumes no scaling beyond AppScale.
void SlatePrepass (float InLayoutScaleMultiplier)
Descends to leaf-most widgets in the hierarchy and gathers desired sizes on the way up.
virtual FString ToString () const
virtual TOptional< FVirtualPointerPosition > TranslateMouseCoordinateForCustomHitTestChild (const SWidget &ChildWidget, const FGeometry &MyGeometry, const FVector2D ScreenSpaceMouseCoordinate, const FVector2D LastScreenSpaceMouseCoordinate) const
void UnRegisterActiveTimer (const TSharedRef< FActiveTimerHandle > &ActiveTimerHandle)
Unregisters an active timer handle.
virtual bool ValidatePathToChild (SWidget *InChild)
Public Member Functions inherited from FSlateControlledConstruction
FSlateControlledConstruction ()=default
virtual ~FSlateControlledConstruction ()=default
virtual const FSlateWidgetClassData & GetWidgetClass () const =0
void operator delete (void *mem)
Public Member Functions inherited from TSharedFromThis< SWidget >
TSharedRef< SWidget, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< SWidget, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Protected Member Functions
virtual TSharedPtr< SWidget > BuildContextMenuContent () const override
Build the context menu content to use for this widget (if any)
virtual void CacheDesiredSize (float LayoutScaleMultiplier) override
The system calls this method.
virtual bool CanInsertCarriageReturn () const override
Are we currently able to insert a carriage return?
virtual bool CanTypeCharacter (const TCHAR InChar) const override
Are we able to insert the given character into our text?
virtual FVector2D ComputeDesiredSize (float LayoutScaleMultiplier) const override
Compute the ideal size necessary to display this widget.
virtual bool ComputeVolatility () const override
Recomputes the volatility of the widget.
virtual void EnsureActiveTick () override
Ensure that we will get a Tick() soon (either due to having active focus, or something having changed progmatically and requiring an update) Does nothing if the active tick timer is already enabled.
virtual FChildren * GetChildren () override
Returns the useful children (if any) of this widget.
virtual const FSlateBrush * GetFocusBrush () const
virtual TSharedRef< SWidget > GetSlateWidget () override
Get the Slate widget this interface is representing (may not be called during destruction)
virtual TSharedPtr< SWidget > GetSlateWidgetPtr () override
Get the Slate widget this interface is representing (may be null during destruction)
virtual EVirtualKeyboardDismissAction GetVirtualKeyboardDismissAction () const override
Get the message action to take when the virtual keyboard is dismissed by the user.
virtual FVirtualKeyboardOptions GetVirtualKeyboardOptions () const override
Get the options for the virtual keyboard used for this widget.
virtual EVirtualKeyboardTrigger GetVirtualKeyboardTrigger () const override
Get the type of event that will trigger the display of the virtual keyboard.
virtual EKeyboardType GetVirtualKeyboardType () const override
Get the type of virtual keyboard to use for this widget.
virtual bool IsInteractable () const override
virtual void OnArrangeChildren (const FGeometry &AllottedGeometry, FArrangedChildren &ArrangedChildren) const override
Compute the Geometry of all the children and add populate the ArrangedChildren list with their values.
virtual void OnCursorMoved (const FTextLocation &InLocation) override
Called when the cursor is moved within the text area.
virtual FCursorReply OnCursorQuery (const FGeometry &MyGeometry, const FPointerEvent &CursorEvent) const override
The system asks each widget under the mouse to provide a cursor.
virtual FReply OnDragOver (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent) override
Called during drag and drop when the the mouse is being dragged over a widget.
virtual FReply OnDrop (const FGeometry &MyGeometry, const FDragDropEvent &DragDropEvent) override
Called when the user is dropping something onto a widget; terminates drag and drop.
virtual void OnFocusLost (const FFocusEvent &InFocusEvent) override
Called when this widget loses focus.
virtual FReply OnFocusReceived (const FGeometry &MyGeometry, const FFocusEvent &InFocusEvent) override
Called when focus is given to this widget.
virtual FReply OnKeyChar (const FGeometry &MyGeometry, const FCharacterEvent &InCharacterEvent) override
Called after a character is entered while this widget has keyboard focus.
virtual FReply OnKeyDown (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent) override
Called after a key is pressed when this widget has focus (this event bubbles if not handled)
virtual FReply OnKeyUp (const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent) override
Called after a key is released when this widget has focus.
virtual FReply OnMouseButtonDoubleClick (const FGeometry &InMyGeometry, const FPointerEvent &InMouseEvent) override
Called when a mouse button is double clicked.
virtual FReply OnMouseButtonDown (const FGeometry &InMyGeometry, const FPointerEvent &InMouseEvent) override
The system calls this method to notify the widget that a mouse button was pressed within it.
virtual FReply OnMouseButtonUp (const FGeometry &InMyGeometry, const FPointerEvent &InMouseEvent) override
The system calls this method to notify the widget that a mouse button was release within it.
virtual FReply OnMouseMove (const FGeometry &InMyGeometry, const FPointerEvent &InMouseEvent) override
The system calls this method to notify the widget that a mouse moved within it.
virtual int32 OnPaint (const FPaintArgs &Args, const FGeometry &AllottedGeometry, const FSlateRect &MyCullingRect, FSlateWindowElementList &OutDrawElements, int32 LayerId, const FWidgetStyle &InWidgetStyle, bool bParentEnabled) const override
The widget should respond by populating the OutDrawElements array with FDrawElements that represent it and any of its children.
virtual void OnTextChanged (const FText &InText) override
Called when the text has been changed by an edit operation.
virtual void OnTextCommitted (const FText &InText, const ETextCommit::Type InTextAction) override
Called when the text control has committed its current edit changes.
virtual bool ShouldClearKeyboardFocusOnCommit () const override
Should we clear the keyboard focus when the user commits text to this widget?
virtual bool ShouldClearTextSelectionOnFocusLoss () const override
Should the text clear its selection the widget loses focus?
virtual bool ShouldJumpCursorToEndWhenFocused () const override
Should the cursor be jumped to the end of the document when the widget gains focus?
virtual bool ShouldRevertTextOnEscape () const override
Should we revert the text back to its original state when the user presses escape?
virtual bool ShouldSelectAllTextOnCommit () const override
Should we select all text when the user commits text to this widget?
virtual bool ShouldSelectAllTextWhenFocused () const override
Should the text be selected when the widget gains focus?
virtual bool ShouldSelectWordOnMouseDoubleClick () const override
Should we select word on mouse double click?
virtual bool SupportsKeyboardFocus () const override
Checks to see if this widget supports keyboard focus.
void SynchronizeTextStyle ()
Synchronize the text style currently set (including from overrides) and update the text layout if required.
virtual void Tick (const FGeometry &AllottedGeometry, const double InCurrentTime, const float InDeltaTime) override
Ticks this widget with Geometry.
virtual float UpdateAndClampHorizontalScrollBar (const float InViewOffset, const float InViewFraction, const EVisibility InVisiblityOverride) override
Called when the fraction and offset of the horizontal scroll area has been recalculated.
virtual float UpdateAndClampVerticalScrollBar (const float InViewOffset, const float InViewFraction, const EVisibility InVisiblityOverride) override
Called when the fraction and offset of the vertical scroll area has been recalculated.
Protected Member Functions inherited from SWidget
SWidget ()
Hidden default constructor.
virtual ~SWidget ()
Dtor ensures that active timer handles are UnRegistered with the SlateApplication.
FORCEINLINE bool Advanced_InvalidateVolatility ()
Recalculates and caches volatility and returns 'true' if the volatility changed.
EFlowDirection ComputeFlowDirection () const
Establishes a new flow direction potentially, if this widget has a particular preference for it and all its children.
virtual bool CustomPrepass (float LayoutScaleMultiplier)
bool FindChildGeometries (const FGeometry &MyGeometry, const TSet< TSharedRef< SWidget > > &WidgetsToFind, TMap< TSharedRef< SWidget >, FArrangedWidget > &OutResult) const
Find the geometry of a descendant widget.
void FindChildGeometries_Helper (const FGeometry &MyGeometry, const TSet< TSharedRef< SWidget > > &WidgetsToFind, TMap< TSharedRef< SWidget >, FArrangedWidget > &OutResult) const
Actual implementation of FindChildGeometries.
FGeometry FindChildGeometry (const FGeometry &MyGeometry, TSharedRef< SWidget > WidgetToFind) const
Find the geometry of a descendant widget.
virtual TOptional< EMouseCursor::Type > GetCursor () const
The cursor to show when the mouse is hovering over this widget.
TSlateAttributeRef< bool > GetEnabledStateAttribute () const
TSlateAttributeRef< bool > GetHoveredAttribute () const
float GetPrepassLayoutScaleMultiplier () const
TSlateAttributeRef< TOptional< FSlateRenderTransform > > GetRenderTransformAttribute () const
TSlateAttributeRef< FVector2D > GetRenderTransformPivotAttribute () const
TSlateAttributeRef< EVisibility > GetVisibilityAttribute () const
void InvalidateChildRemovedFromTree (SWidget &Child)
Called when a child is removed from the tree parent's widget tree either by removing it from a slot.
FORCEINLINE bool IsChildWidgetCulled (const FSlateRect &, const FArrangedWidget &) const
bool IsConstructed () const
Is the widget construction completed (did we called and returned from the Construct() function)
virtual void OnClippingChanged ()
Called when clipping is changed.
void Prepass_ChildLoop (float InLayoutScaleMultiplier, FChildren *MyChildren)
template<typename TargetValueType, typename SourceValueType>
bool SetAttribute (TAttribute< TargetValueType > &TargetValue, const TAttribute< SourceValueType > &SourceValue, EInvalidateWidgetReason BaseInvalidationReason)
Performs the attribute assignment and invalidates the widget minimally based on what actually changed.
void SetDebugInfo (const ANSICHAR *InType, const ANSICHAR *InFile, int32 OnLine, size_t InAllocSize)
Used by Slate to set the runtime debug info about this widget.
void SetHover (TAttribute< bool > InHovered)
Set the hover state.
void SetVolatilePrepass (bool bVolatile)
bool ShouldBeEnabled (bool InParentEnabled) const
Determines if this widget should be enabled.
void SWidgetConstruct (const FSlateBaseNamedArgs &Args)
Construct a SWidget based on initial parameters.
Protected Member Functions inherited from TSharedFromThis< SWidget >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Protected Attributes
TWeakPtr< FActiveTimerHandle > ActiveTickTimer
The timer that is actively driving this widget to Tick() even when Slate is idle.
TAttribute< const FSlateBrush * > BackgroundImageSelected
Background image for the selected text.
TAttribute< bool > bAllowContextMenu
Whether to disable the context menu.
TAttribute< bool > bClearKeyboardFocusOnCommit
Whether to clear keyboard focus when pressing enter to commit changes.
TAttribute< bool > bEnableIntegratedKeyboard
Whether to enable integrated keyboard.
TAttribute< bool > bIsCaretMovedWhenGainFocus
Workaround as we loose focus when the auto completion closes.
TAttribute< bool > bIsPassword
Sets whether this text box is for storing a password.
TAttribute< bool > bIsReadOnly
Sets whether this text box can actually be modified interactively by the user.
TAttribute< bool > bRevertTextOnEscape
Whether to allow the user to back out of changes when they press the escape key.
TAttribute< bool > bSelectAllTextOnCommit
Whether to select all text when pressing enter to commit changes.
TAttribute< bool > bSelectAllTextWhenFocused
Whether to select all text when the user clicks to give focus on the widget.
TAttribute< bool > bSelectWordOnMouseDoubleClick
Whether to select word on mouse double click.
TAttribute< FSlateColor > ColorAndOpacity
Text color and opacity.
TUniquePtr< FSlateEditableTextLayout > EditableTextLayout
The text layout that deals with the editable text.
TAttribute< FSlateFontInfo > Font
The font used to draw the text.
TSharedPtr< FExtender > MenuExtender
Menu extender for right-click context menu.
TAttribute< float > MinDesiredWidth
Prevents the editable text from being smaller than desired in certain cases (e.g.
FOnContextMenuOpening OnContextMenuOpening
Delegate to call before a context menu is opened.
FOnIsTypedCharValid OnIsTypedCharValid
Called when a character is typed and we want to know if the text field supports typing this character.
FOnKeyChar OnKeyCharHandler
Callback delegate to have first chance handling of the OnKeyChar event.
FOnKeyDown OnKeyDownHandler
Callback delegate to have first chance handling of the OnKeyDown event.
FOnTextChanged OnTextChangedCallback
Called whenever the text is changed programmatically or interactively by the user.
FOnTextCommitted OnTextCommittedCallback
Called whenever the text is committed.
TSharedPtr< FPlainTextLayoutMarshaller > PlainTextMarshaller
Text marshaller used by the editable text layout.
TAttribute< EVirtualKeyboardDismissAction > VirtualKeyboardDismissAction
The message action to take when the virtual keyboard is dismissed by the user.
FVirtualKeyboardOptions VirtualKeyboardOptions
Additional options used by the virtual keyboard summoned by this widget.
TAttribute< EVirtualKeyboardTrigger > VirtualKeyboardTrigger
The type of event that will trigger the display of the virtual keyboard.
TAttribute< EKeyboardType > VirtualKeyboardType
The type of virtual keyboard to use for editing this text on mobile.
TSharedPtr< IBreakIterator > WordBreakIterator
The iterator to use to detect word boundaries.
Protected Attributes inherited from SWidget
uint8 bCanHaveChildren: 1
Can the widget ever support children?
uint8 bCanSupportFocus: 1
Can the widget ever support keyboard focus.
uint8 bClippingProxy: 1
Some widgets might be a complex hierarchy of child widgets you never see.
uint8 bHasCustomPrepass: 1
uint8 bHasRelativeLayoutScale: 1
uint8 bVolatilityAlwaysInvalidatesPrepass: 1
if this widget should always invalidate the prepass step when volatile
EWidgetClipping Clipping
Set to true if all content of the widget should clip to the bounds of this widget.
FMargin CullingBoundsExtension
Can be used to enlarge the culling bounds of this widget (pre-intersection), this can be useful if you've got children that you know are using rendering transforms to render outside their standard bounds, if that happens it's possible the parent might be culled before the descendant widget is entirely off screen.
EWidgetPixelSnapping PixelSnappingMethod
When set to EPixelSnappingMethod::SnapToPixel, the widget is drawn at the nearest pixel.
float RenderOpacity
The opacity of the widget.
Additional Inherited Members
Static Public Member Functions inherited from FSlateControlledConstruction
static const FSlateWidgetClassData & StaticWidgetClass ()
Static Protected Member Functions inherited from SWidget
static TAttribute< EVisibility > AccessWidgetVisibilityAttribute (const TSharedRef< SWidget > &Widget)
Protected static helper to allow widgets to access the visibility attribute of other widgets directly.
static int32 FindChildUnderMouse (const FArrangedChildren &Children, const FPointerEvent &MouseEvent)
static int32 FindChildUnderPosition (const FArrangedChildren &Children, const UE::Slate::FDeprecateVector2DParameter &ArrangedSpacePosition)
Static Protected Member Functions inherited from TSharedFromThis< SWidget >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
Editable text widget.
Definition at line 37 of file SEditableText.h.
Constructor & Destructor Documentation
~SEditableText()
SEditableText::~SEditableText ()
Destructor.
Member Function Documentation
AdvanceSearch()
void SEditableText::AdvanceSearch (const bool InReverse = false)
Advance the current search to the next match (does nothing if not currently searching)
AnyTextSelected()
bool SEditableText::AnyTextSelected () const
Query to see if any text is selected within the document.
BeginSearch()
void SEditableText::BeginSearch (const FText & InSearchText, const ESearchCase::Type InSearchCase = ESearchCase::IgnoreCase, const bool InReverse = false)
Begin a new text search (this is called automatically when the bound search text changes)
References ESearchCase::IgnoreCase.
BuildContextMenuContent()
virtual TSharedPtr< SWidget > SEditableText::BuildContextMenuContent () const override protected virtual
Build the context menu content to use for this widget (if any)
Implements ISlateEditableTextWidget.
CacheDesiredSize()
virtual void SEditableText::CacheDesiredSize (float InLayoutScaleMultiplier) override protected virtual
The system calls this method.
It performs a breadth-first traversal of every visible widget and asks each widget to cache how big it needs to be in order to present all of its content.
Reimplemented from SWidget.
CanInsertCarriageReturn()
virtual bool SEditableText::CanInsertCarriageReturn () const override protected virtual
Are we currently able to insert a carriage return?
(some widgets have modifier keys that need to be pressed)
Implements ISlateEditableTextWidget.
CanTypeCharacter()
virtual bool SEditableText::CanTypeCharacter (const TCHAR InChar) const override protected virtual
Are we able to insert the given character into our text?
Implements ISlateEditableTextWidget.
ClearSelection()
void SEditableText::ClearSelection ()
Clear the active text selection.
ComputeDesiredSize()
virtual FVector2D SEditableText::ComputeDesiredSize (float LayoutScaleMultiplier) const override protected virtual
Compute the ideal size necessary to display this widget.
For aggregate widgets (e.g. panels) this size should include the size necessary to show all of its children. CacheDesiredSize() guarantees that the size of descendants is computed and cached before that of the parents, so it is safe to call GetDesiredSize() for any children while implementing this method.
Note that ComputeDesiredSize() is meant as an aide to the developer. It is NOT meant to be very robust in many cases. If your widget is simulating a bouncing ball, you should just return a reasonable size; e.g. 160x160. Let the programmer set up a reasonable rule of resizing the bouncy ball simulation.
Parameters
LayoutScaleMultiplier This parameter is safe to ignore for almost all widgets; only really affects text measuring.
Returns
The desired size.
Implements SWidget.
ComputeVolatility()
virtual bool SEditableText::ComputeVolatility () const override protected virtual
Recomputes the volatility of the widget.
If you have additional state you automatically want to make the widget volatile, you should sample that information here.
Reimplemented from SWidget.
References Main.
Construct()
void SEditableText::Construct (const FArguments & InArgs)
Construct this widget.
Parameters
InArgs The declaration data for this widget
References Construct().
Referenced by Construct().
EnableTextInputMethodContext()
void SEditableText::EnableTextInputMethodContext ()
Register and activate the IME context for this text layout.
EnsureActiveTick()
virtual void SEditableText::EnsureActiveTick () override protected virtual
Ensure that we will get a Tick() soon (either due to having active focus, or something having changed progmatically and requiring an update) Does nothing if the active tick timer is already enabled.
Implements ISlateEditableTextWidget.
GetChildren()
virtual FChildren * SEditableText::GetChildren () override protected virtual
Returns the useful children (if any) of this widget.
Some widget type may hide widget if they are needed by the system. Allows for iteration over the Widget's children regardless of how they are actually stored.
Note
Should be renamed to GetVisibleChildren (not ALL children will be returned in all cases).
Implements SWidget.
GetFocusBrush()
virtual const FSlateBrush * SEditableText::GetFocusBrush () const protected virtual
Returns
a brush to draw focus, nullptr if no focus drawing is desired
Reimplemented from SWidget.
GetFont()
FSlateFontInfo SEditableText::GetFont () const
Gets the font used to draw the text.
References GetFont().
Referenced by GetFont().
GetHintText()
FText SEditableText::GetHintText () const
Get the text that appears when there is no text in the text box.
References GetHintText().
Referenced by GetHintText().
GetSearchText()
FText SEditableText::GetSearchText () const
Get the text that is currently being searched for (if any)
References GetSearchText().
Referenced by GetSearchText().
GetSelectedText()
FText SEditableText::GetSelectedText () const
Get the currently selected text.
GetSelection()
FTextSelection SEditableText::GetSelection () const
Get the current selection.
GetSlateWidget()
virtual TSharedRef< SWidget > SEditableText::GetSlateWidget () override protected virtual
Get the Slate widget this interface is representing (may not be called during destruction)
Implements ISlateEditableTextWidget.
GetSlateWidgetPtr()
virtual TSharedPtr< SWidget > SEditableText::GetSlateWidgetPtr () override protected virtual
Get the Slate widget this interface is representing (may be null during destruction)
Implements ISlateEditableTextWidget.
GetText()
FText SEditableText::GetText () const
Returns the text string.
Returns
Text string
References GetText().
Referenced by GetText().
GetVirtualKeyboardDismissAction()
virtual EVirtualKeyboardDismissAction SEditableText::GetVirtualKeyboardDismissAction () const override protected virtual
Get the message action to take when the virtual keyboard is dismissed by the user.
Implements ISlateEditableTextWidget.
GetVirtualKeyboardOptions()
virtual FVirtualKeyboardOptions SEditableText::GetVirtualKeyboardOptions () const override protected virtual
Get the options for the virtual keyboard used for this widget.
Implements ISlateEditableTextWidget.
GetVirtualKeyboardTrigger()
virtual EVirtualKeyboardTrigger SEditableText::GetVirtualKeyboardTrigger () const override protected virtual
Get the type of event that will trigger the display of the virtual keyboard.
Implements ISlateEditableTextWidget.
GetVirtualKeyboardType()
virtual EKeyboardType SEditableText::GetVirtualKeyboardType () const override protected virtual
Get the type of virtual keyboard to use for this widget.
Implements ISlateEditableTextWidget.
GoTo() [1/2]
void SEditableText::GoTo (const ETextLocation NewLocation)
Move the cursor specified location.
GoTo() [2/2]
void SEditableText::GoTo (const FTextLocation & NewLocation)
Move the cursor to the given location in the document (will also scroll to this point)
IsIntegratedKeyboardEnabled()
virtual bool SEditableText::IsIntegratedKeyboardEnabled () const override virtual
Is the widget currently has IntegratedKeyboard enabled?
Implements ISlateEditableTextWidget.
IsInteractable()
virtual bool SEditableText::IsInteractable () const override protected virtual
Returns
Is this widget interactive or not? Defaults to false
Reimplemented from SWidget.
IsMultiLineTextEdit()
virtual bool SEditableText::IsMultiLineTextEdit () const override virtual
Is the text edit multi-line aware?
Implements ISlateEditableTextWidget.
IsTextPassword()
virtual bool SEditableText::IsTextPassword () const override virtual
Is the text displaying a password and should be obscured?
Implements ISlateEditableTextWidget.
IsTextReadOnly()
virtual bool SEditableText::IsTextReadOnly () const override virtual
Is the text currently read-only?
Implements ISlateEditableTextWidget.
OnArrangeChildren()
virtual void SEditableText::OnArrangeChildren (const FGeometry & AllottedGeometry, FArrangedChildren & ArrangedChildren) const override protected virtual
Compute the Geometry of all the children and add populate the ArrangedChildren list with their values.
Each type of Layout panel should arrange children based on desired behavior.
Parameters
AllottedGeometry The geometry allotted for this widget by its parent.
ArrangedChildren The array to which to add the WidgetGeometries that represent the arranged children.
Implements SWidget.
OnCursorMoved()
virtual void SEditableText::OnCursorMoved (const FTextLocation & InLocation) override protected virtual
Called when the cursor is moved within the text area.
Implements ISlateEditableTextWidget.
OnCursorQuery()
virtual FCursorReply SEditableText::OnCursorQuery (const FGeometry & MyGeometry, const FPointerEvent & CursorEvent) const override protected virtual
The system asks each widget under the mouse to provide a cursor.
This event is bubbled.
Returns
FCursorReply::Unhandled() if the event is not handled; return FCursorReply::Cursor() otherwise.
Reimplemented from SWidget.
OnDragOver()
virtual FReply SEditableText::OnDragOver (const FGeometry & MyGeometry, const FDragDropEvent & DragDropEvent) override protected virtual
Called during drag and drop when the the mouse is being dragged over a widget.
Parameters
MyGeometry The geometry of the widget receiving the event.
DragDropEvent The drag and drop event.
Returns
A reply that indicated whether this event was handled.
Reimplemented from SWidget.
OnDrop()
virtual FReply SEditableText::OnDrop (const FGeometry & MyGeometry, const FDragDropEvent & DragDropEvent) override protected virtual
Called when the user is dropping something onto a widget; terminates drag and drop.
Parameters
MyGeometry The geometry of the widget receiving the event.
DragDropEvent The drag and drop event.
Returns
A reply that indicated whether this event was handled.
Reimplemented from SWidget.
OnFocusLost()
virtual void SEditableText::OnFocusLost (const FFocusEvent & InFocusEvent) override protected virtual
Called when this widget loses focus.
This event does not bubble.
Parameters
InFocusEvent The FocusEvent
Reimplemented from SWidget.
OnFocusReceived()
virtual FReply SEditableText::OnFocusReceived (const FGeometry & MyGeometry, const FFocusEvent & InFocusEvent) override protected virtual
Called when focus is given to this widget.
This event does not bubble.
Parameters
MyGeometry The Geometry of the widget receiving the event
InFocusEvent The FocusEvent
Returns
Returns whether the event was handled, along with other possible actions
Reimplemented from SWidget.
OnKeyChar()
virtual FReply SEditableText::OnKeyChar (const FGeometry & MyGeometry, const FCharacterEvent & InCharacterEvent) override protected virtual
Called after a character is entered while this widget has keyboard focus.
Parameters
MyGeometry The Geometry of the widget receiving the event
InCharacterEvent Character event
Returns
Returns whether the event was handled, along with other possible actions
Reimplemented from SWidget.
OnKeyDown()
virtual FReply SEditableText::OnKeyDown (const FGeometry & MyGeometry, const FKeyEvent & InKeyEvent) override protected virtual
Called after a key is pressed when this widget has focus (this event bubbles if not handled)
Parameters
MyGeometry The Geometry of the widget receiving the event
InKeyEvent Key event
Returns
Returns whether the event was handled, along with other possible actions
Reimplemented from SWidget.
OnKeyUp()
virtual FReply SEditableText::OnKeyUp (const FGeometry & MyGeometry, const FKeyEvent & InKeyEvent) override protected virtual
Called after a key is released when this widget has focus.
Parameters
MyGeometry The Geometry of the widget receiving the event
InKeyEvent Key event
Returns
Returns whether the event was handled, along with other possible actions
Reimplemented from SWidget.
OnMouseButtonDoubleClick()
virtual FReply SEditableText::OnMouseButtonDoubleClick (const FGeometry & InMyGeometry, const FPointerEvent & InMouseEvent) override protected virtual
Called when a mouse button is double clicked.
Override this in derived classes.
Parameters
InMyGeometry Widget geometry
InMouseEvent Mouse button event
Returns
Returns whether the event was handled, along with other possible actions
Reimplemented from SWidget.
OnMouseButtonDown()
virtual FReply SEditableText::OnMouseButtonDown (const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) override protected virtual
The system calls this method to notify the widget that a mouse button was pressed within it.
This event is bubbled.
Parameters
MyGeometry The Geometry of the widget receiving the event
MouseEvent Information about the input event
Returns
Whether the event was handled along with possible requests for the system to take action.
Reimplemented from SWidget.
OnMouseButtonUp()
virtual FReply SEditableText::OnMouseButtonUp (const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) override protected virtual
The system calls this method to notify the widget that a mouse button was release within it.
This event is bubbled.
Parameters
MyGeometry The Geometry of the widget receiving the event
MouseEvent Information about the input event
Returns
Whether the event was handled along with possible requests for the system to take action.
Reimplemented from SWidget.
OnMouseMove()
virtual FReply SEditableText::OnMouseMove (const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) override protected virtual
The system calls this method to notify the widget that a mouse moved within it.
This event is bubbled.
Parameters
MyGeometry The Geometry of the widget receiving the event
MouseEvent Information about the input event
Returns
Whether the event was handled along with possible requests for the system to take action.
Reimplemented from SWidget.
OnPaint()
virtual int32 SEditableText::OnPaint (const FPaintArgs & Args, const FGeometry & AllottedGeometry, const FSlateRect & MyCullingRect, FSlateWindowElementList & OutDrawElements, int32 LayerId, const FWidgetStyle & InWidgetStyle, bool bParentEnabled) const override protected virtual
The widget should respond by populating the OutDrawElements array with FDrawElements that represent it and any of its children.
Called by the non-virtual OnPaint to enforce pre/post conditions during OnPaint.
Parameters
Args All the arguments necessary to paint this widget (
Todo
umg: move all params into this struct)
Parameters
AllottedGeometry The FGeometry that describes an area in which the widget should appear.
MyCullingRect The rectangle representing the bounds currently being used to completely cull widgets. Unless IsChildWidgetCulled(...) returns true, you should paint the widget.
OutDrawElements A list of FDrawElements to populate with the output.
LayerId The Layer onto which this widget should be rendered.
InColorAndOpacity Color and Opacity to be applied to all the descendants of the widget being painted
bParentEnabled True if the parent of this widget is enabled.
Returns
The maximum layer ID attained by this widget or any of its children.
Implements SWidget.
References SWidget::FSlateWindowElementList.
OnTextChanged()
virtual void SEditableText::OnTextChanged (const FText & InText) override protected virtual
Called when the text has been changed by an edit operation.
Implements ISlateEditableTextWidget.
Referenced by SLATE_EVENT().
OnTextCommitted()
virtual void SEditableText::OnTextCommitted (const FText & InText, const ETextCommit::Type InTextAction) override protected virtual
Called when the text control has committed its current edit changes.
Implements ISlateEditableTextWidget.
Referenced by SLATE_EVENT().
ScrollTo() [1/2]
void SEditableText::ScrollTo (const ETextLocation NewLocation)
Scroll to the given location in the document (without moving the cursor)
ScrollTo() [2/2]
void SEditableText::ScrollTo (const FTextLocation & NewLocation)
Scroll to the given location in the document (without moving the cursor)
SelectAllText()
void SEditableText::SelectAllText ()
Select all the text in the document.
SelectText()
void SEditableText::SelectText (const FTextLocation & InSelectionStart, const FTextLocation & InCursorLocation)
Select a block of text.
SetAllowContextMenu()
void SEditableText::SetAllowContextMenu (const TAttribute< bool > & InAllowContextMenu)
See the AllowContextMenu attribute.
References SetAllowContextMenu().
Referenced by SetAllowContextMenu().
SetClearKeyboardFocusOnCommit()
void SEditableText::SetClearKeyboardFocusOnCommit (const TAttribute< bool > & InClearKeyboardFocusOnCommit)
Sets whether to clear keyboard focus when pressing enter to commit changes.
Parameters
InClearKeyboardFocusOnCommit Clear keyboard focus when pressing enter?
References SetClearKeyboardFocusOnCommit().
Referenced by SetClearKeyboardFocusOnCommit().
SetColorAndOpacity()
void SEditableText::SetColorAndOpacity (TAttribute< FSlateColor > Color)
See the ColorAndOpacity attribute.
References Color, and SetColorAndOpacity().
Referenced by SetColorAndOpacity().
SetEditableText()
bool SEditableText::SetEditableText (const FText & InNewText)
Sets the text currently being edited Note: Doesn't override the bound Text attribute, nor does it call OnTextChanged.
Parameters
InNewText The new editable text
Returns
true if the text was updated, false if the text was already up-to-date
References SetEditableText().
Referenced by SetEditableText().
SetEnableIntegratedKeyboard()
void SEditableText::SetEnableIntegratedKeyboard (const TAttribute< bool > & InEnableIntegratedKeyboard)
See the EnableIntegratedKeyboard attribute.
References SetEnableIntegratedKeyboard().
Referenced by SetEnableIntegratedKeyboard().
SetFont()
void SEditableText::SetFont (const TAttribute< FSlateFontInfo > & InNewFont)
Sets the font used to draw the text.
Parameters
InNewFont The new font to use
References SetFont().
Referenced by SetFont().
SetHintText()
void SEditableText::SetHintText (const TAttribute< FText > & InHintText)
See the HintText attribute.
References SetHintText().
Referenced by SetHintText().
SetIsCaretMovedWhenGainFocus()
void SEditableText::SetIsCaretMovedWhenGainFocus (const TAttribute< bool > & InIsCaretMovedWhenGainFocus)
Workaround as we loose focus when the auto completion closes.
Parameters
InIsCaretMovedWhenGainFocus Workaround
References SetIsCaretMovedWhenGainFocus().
Referenced by SetIsCaretMovedWhenGainFocus().
SetIsPassword()
void SEditableText::SetIsPassword (TAttribute< bool > InIsPassword)
See the IsPassword attribute.
References SetIsPassword().
Referenced by SetIsPassword().
SetIsReadOnly()
void SEditableText::SetIsReadOnly (TAttribute< bool > InIsReadOnly)
See the IsReadOnly attribute.
References SetIsReadOnly().
Referenced by SetIsReadOnly().
SetJustification()
void SEditableText::SetJustification (const TAttribute< ETextJustify::Type > & InJustification)
See Justification attribute.
References SetJustification().
Referenced by SetJustification().
SetMinDesiredWidth()
void SEditableText::SetMinDesiredWidth (const TAttribute< float > & InMinDesiredWidth)
Sets the minimum width that a text block should be.
Parameters
InMinDesiredWidth The minimum width
References SetMinDesiredWidth().
Referenced by SetMinDesiredWidth().
SetOnKeyCharHandler()
void SEditableText::SetOnKeyCharHandler (FOnKeyChar InOnKeyCharHandler) inline
Sets the OnKeyCharHandler to provide first chance handling of the OnKeyChar event.
Parameters
InOnKeyCharHandler Delegate to call during OnKeyChar event
Definition at line 331 of file SEditableText.h.
References OnKeyCharHandler, and SetOnKeyCharHandler().
Referenced by SetOnKeyCharHandler().
SetOnKeyDownHandler()
void SEditableText::SetOnKeyDownHandler (FOnKeyDown InOnKeyDownHandler) inline
Sets the OnKeyDownHandler to provide first chance handling of the OnKeyDown event.
Parameters
InOnKeyDownHandler Delegate to call during OnKeyDown event
Definition at line 341 of file SEditableText.h.
References OnKeyDownHandler.
SetOverflowPolicy()
void SEditableText::SetOverflowPolicy (TOptional< ETextOverflowPolicy > InOverflowPolicy)
Sets the overflow policy for this text block.
SetRevertTextOnEscape()
void SEditableText::SetRevertTextOnEscape (const TAttribute< bool > & InRevertTextOnEscape)
Sets whether to allow the user to back out of changes when they press the escape key.
Parameters
InRevertTextOnEscape Allow the user to back out of changes?
References SetRevertTextOnEscape().
Referenced by SetRevertTextOnEscape().
SetSearchText()
void SEditableText::SetSearchText (const TAttribute< FText > & InSearchText)
Set the text that is currently being searched for (if any)
References SetSearchText().
Referenced by SetSearchText().
SetSelectAllTextOnCommit()
void SEditableText::SetSelectAllTextOnCommit (const TAttribute< bool > & InSelectAllTextOnCommit)
Sets whether to select all text when pressing enter to commit changes.
Parameters
InSelectAllTextOnCommit Select all text when pressing enter?
References SetSelectAllTextOnCommit().
Referenced by SetSelectAllTextOnCommit().
SetSelectAllTextWhenFocused()
void SEditableText::SetSelectAllTextWhenFocused (const TAttribute< bool > & InSelectAllTextWhenFocused)
Sets whether to select all text when the user clicks to give focus on the widget.
Parameters
InSelectAllTextWhenFocused Select all text when the user clicks?
References SetSelectAllTextWhenFocused().
Referenced by SetSelectAllTextWhenFocused().
SetSelectWordOnMouseDoubleClick()
void SEditableText::SetSelectWordOnMouseDoubleClick (const TAttribute< bool > & InSelectWordOnMouseDoubleClick)
Sets whether to select word on the mouse double click.
Parameters
InSelectWordOnMouseDoubleClick Select word on the mouse double click
References SetSelectWordOnMouseDoubleClick().
Referenced by SetSelectWordOnMouseDoubleClick().
SetText()
void SEditableText::SetText (const TAttribute< FText > & InNewText)
Sets the text currently being edited.
Parameters
InNewText The new text
References SetText().
Referenced by SetText().
SetTextBlockStyle()
void SEditableText::SetTextBlockStyle (const FTextBlockStyle * InTextStyle)
@See TextStyle
Sets the text block style used to draw the text
Parameters
InTextStyle The new text block style to use
References SetTextBlockStyle().
Referenced by SetTextBlockStyle().
SetTextFlowDirection()
void SEditableText::SetTextFlowDirection (const TOptional< ETextFlowDirection > & InTextFlowDirection)
See TextFlowDirection attribute.
SetTextShapingMethod()
void SEditableText::SetTextShapingMethod (const TOptional< ETextShapingMethod > & InTextShapingMethod)
See TextShapingMethod attribute.
SetTextStyle()
void SEditableText::SetTextStyle (const FEditableTextStyle & InNewTextStyle)
Sets the text style used to draw the text.
Parameters
NewTextStyle The new text style to use
References SetTextStyle().
Referenced by SetTextStyle().
SetVirtualKeyboardDismissAction()
void SEditableText::SetVirtualKeyboardDismissAction (TAttribute< EVirtualKeyboardDismissAction > InVirtualKeyboardDismissAction)
Set the VirtualKeyboardDismissAction attribute.
References SetVirtualKeyboardDismissAction().
Referenced by SetVirtualKeyboardDismissAction().
ShouldClearKeyboardFocusOnCommit()
virtual bool SEditableText::ShouldClearKeyboardFocusOnCommit () const override protected virtual
Should we clear the keyboard focus when the user commits text to this widget?
Implements ISlateEditableTextWidget.
ShouldClearTextSelectionOnFocusLoss()
virtual bool SEditableText::ShouldClearTextSelectionOnFocusLoss () const override protected virtual
Should the text clear its selection the widget loses focus?
Implements ISlateEditableTextWidget.
ShouldJumpCursorToEndWhenFocused()
virtual bool SEditableText::ShouldJumpCursorToEndWhenFocused () const override protected virtual
Should the cursor be jumped to the end of the document when the widget gains focus?
Implements ISlateEditableTextWidget.
ShouldRevertTextOnEscape()
virtual bool SEditableText::ShouldRevertTextOnEscape () const override protected virtual
Should we revert the text back to its original state when the user presses escape?
Implements ISlateEditableTextWidget.
ShouldSelectAllTextOnCommit()
virtual bool SEditableText::ShouldSelectAllTextOnCommit () const override protected virtual
Should we select all text when the user commits text to this widget?
Implements ISlateEditableTextWidget.
ShouldSelectAllTextWhenFocused()
virtual bool SEditableText::ShouldSelectAllTextWhenFocused () const override protected virtual
Should the text be selected when the widget gains focus?
Implements ISlateEditableTextWidget.
ShouldSelectWordOnMouseDoubleClick()
virtual bool SEditableText::ShouldSelectWordOnMouseDoubleClick () const override protected virtual
Should we select word on mouse double click?
Implements ISlateEditableTextWidget.
SLATE_ARGUMENT() [1/2]
HintText Style ColorAndOpacity BackgroundImageComposing IsReadOnly IsCaretMovedWhenGainFocus SelectWordOnMouseDoubleClick ClearKeyboardFocusOnCommit AllowContextMenu OnContextMenuOpening OnTextChanged MinDesiredWidth OnKeyCharHandler ContextMenuExtender VirtualKeyboardOptions VirtualKeyboardDismissAction TextFlowDirection SEditableText::SLATE_ARGUMENT (TOptional< ETextOverflowPolicy > , OverflowPolicy)
Determines what happens to text that is clipped and doesnt fit within the allotted area for this widget.
Constructor
References SLATE_ARGUMENT(), and SLATE_END_ARGS.
SLATE_ARGUMENT() [2/2]
HintText Style ColorAndOpacity BackgroundImageComposing IsReadOnly IsCaretMovedWhenGainFocus SelectWordOnMouseDoubleClick ClearKeyboardFocusOnCommit AllowContextMenu OnContextMenuOpening OnTextChanged MinDesiredWidth OnKeyCharHandler ContextMenuExtender VirtualKeyboardOptions VirtualKeyboardDismissAction SEditableText::SLATE_ARGUMENT (TOptional< ETextShapingMethod > , TextShapingMethod)
Which text shaping method should we use?
(unset to use the default returned by GetDefaultTextShapingMethod) Which text flow direction should we use? (unset to use the default returned by GetDefaultTextFlowDirection)
References SLATE_ARGUMENT().
Referenced by SLATE_ARGUMENT(), SLATE_ARGUMENT(), and SLATE_ATTRIBUTE().
SLATE_ATTRIBUTE() [1/13]
HintText Style ColorAndOpacity BackgroundImageComposing IsReadOnly IsCaretMovedWhenGainFocus SelectWordOnMouseDoubleClick ClearKeyboardFocusOnCommit AllowContextMenu SEditableText::SLATE_ATTRIBUTE (bool , EnableIntegratedKeyboard)
Whether the IntegratedKeyboard is enabled.
Delegate to call before a context menu is opened. User returns the menu content or null to the disable context menu
References OnContextMenuOpening, SLATE_ATTRIBUTE(), and SLATE_EVENT().
SLATE_ATTRIBUTE() [2/13]
HintText Style ColorAndOpacity BackgroundImageComposing IsReadOnly SEditableText::SLATE_ATTRIBUTE (bool , IsPassword)
Sets whether this text box is for storing a password.
Workaround as we loose focus when the auto completion closes.
References SLATE_ATTRIBUTE().
SLATE_ATTRIBUTE() [3/13]
HintText Style ColorAndOpacity BackgroundImageComposing IsReadOnly IsCaretMovedWhenGainFocus SelectWordOnMouseDoubleClick SEditableText::SLATE_ATTRIBUTE (bool , RevertTextOnEscape)
Whether to allow the user to back out of changes when they press the escape key.
Whether to clear keyboard focus when pressing enter to commit changes
References SLATE_ATTRIBUTE().
SLATE_ATTRIBUTE() [4/13]
HintText Style ColorAndOpacity BackgroundImageComposing IsReadOnly IsCaretMovedWhenGainFocus SelectWordOnMouseDoubleClick ClearKeyboardFocusOnCommit AllowContextMenu OnContextMenuOpening OnTextChanged MinDesiredWidth SEditableText::SLATE_ATTRIBUTE (bool , SelectAllTextOnCommit)
Whether to select all text when pressing enter to commit changes.
Callback delegate to have first chance handling of the OnKeyChar event
References OnKeyCharHandler, SLATE_ATTRIBUTE(), and SLATE_EVENT().
SLATE_ATTRIBUTE() [5/13]
HintText Style ColorAndOpacity BackgroundImageComposing IsReadOnly IsCaretMovedWhenGainFocus SEditableText::SLATE_ATTRIBUTE (bool , SelectAllTextWhenFocused)
Whether to select all text when the user clicks to give focus on the widget.
Whether to select word on mouse double click on the widget
References SLATE_ATTRIBUTE().
SLATE_ATTRIBUTE() [6/13]
HintText Style ColorAndOpacity SEditableText::SLATE_ATTRIBUTE (const FSlateBrush * , BackgroundImageSelected) const
Background image for the selected text (overrides Style)
Background image for the composing text (overrides Style)
References BackgroundImageSelected, and SLATE_ATTRIBUTE().
SLATE_ATTRIBUTE() [7/13]
HintText Style ColorAndOpacity BackgroundImageComposing SEditableText::SLATE_ATTRIBUTE (const FSlateBrush * , CaretImage)
Image brush used for the caret (overrides Style)
Sets whether this text box can actually be modified interactively by the user
References SLATE_ATTRIBUTE().
SLATE_ATTRIBUTE() [8/13]
HintText Style ColorAndOpacity BackgroundImageComposing IsReadOnly IsCaretMovedWhenGainFocus SelectWordOnMouseDoubleClick ClearKeyboardFocusOnCommit AllowContextMenu OnContextMenuOpening OnTextChanged MinDesiredWidth OnKeyCharHandler ContextMenuExtender SEditableText::SLATE_ATTRIBUTE (EKeyboardType , VirtualKeyboardType)
The type of virtual keyboard to use on mobile devices.
Additional options used by the virtual keyboard summoned by this widget
References SLATE_ARGUMENT(), SLATE_ATTRIBUTE(), VirtualKeyboardOptions, and VirtualKeyboardType.
SLATE_ATTRIBUTE() [9/13]
HintText Style ColorAndOpacity BackgroundImageComposing IsReadOnly IsCaretMovedWhenGainFocus SelectWordOnMouseDoubleClick ClearKeyboardFocusOnCommit SEditableText::SLATE_ATTRIBUTE (ETextJustify::Type , Justification)
How should the value be justified in the editable text field.
Whether the context menu can be opened
References SLATE_ATTRIBUTE().
SLATE_ATTRIBUTE() [10/13]
HintText Style ColorAndOpacity BackgroundImageComposing IsReadOnly IsCaretMovedWhenGainFocus SelectWordOnMouseDoubleClick ClearKeyboardFocusOnCommit AllowContextMenu OnContextMenuOpening OnTextChanged MinDesiredWidth OnKeyCharHandler ContextMenuExtender VirtualKeyboardOptions SEditableText::SLATE_ATTRIBUTE (EVirtualKeyboardTrigger , VirtualKeyboardTrigger)
The type of event that will trigger the display of the virtual keyboard.
The message action to take when the virtual keyboard is dismissed by the user
References SLATE_ATTRIBUTE(), VirtualKeyboardDismissAction, and VirtualKeyboardTrigger.
SLATE_ATTRIBUTE() [11/13]
HintText Style SEditableText::SLATE_ATTRIBUTE (FSlateFontInfo , Font)
Sets the font used to draw the text (overrides Style)
Text color and opacity (overrides Style)
References ColorAndOpacity, Font, and SLATE_ATTRIBUTE().
SLATE_ATTRIBUTE() [12/13]
HintText SEditableText::SLATE_ATTRIBUTE (FText , SearchText)
Text to search for (a new search is triggered whenever this text changes)
The style of the text block, which dictates the font, color
References SLATE_ATTRIBUTE(), and SLATE_STYLE_ARGUMENT.
SLATE_ATTRIBUTE() [13/13]
SEditableText::SLATE_ATTRIBUTE (FText , Text)
Sets the text content for this editable text widget.
The text that appears when there is nothing typed into the search box
References Text.
Referenced by SLATE_ATTRIBUTE(), SLATE_ATTRIBUTE(), SLATE_ATTRIBUTE(), SLATE_ATTRIBUTE(), SLATE_ATTRIBUTE(), SLATE_ATTRIBUTE(), SLATE_ATTRIBUTE(), SLATE_ATTRIBUTE(), SLATE_ATTRIBUTE(), SLATE_ATTRIBUTE(), SLATE_ATTRIBUTE(), SLATE_ATTRIBUTE(), and SLATE_EVENT().
SLATE_BEGIN_ARGS()
SEditableText::SLATE_BEGIN_ARGS (SEditableText) inline
Definition at line 40 of file SEditableText.h.
References Keyboard_Default, and Left.
SLATE_EVENT() [1/3]
HintText Style ColorAndOpacity BackgroundImageComposing IsReadOnly IsCaretMovedWhenGainFocus SelectWordOnMouseDoubleClick ClearKeyboardFocusOnCommit AllowContextMenu OnContextMenuOpening SEditableText::SLATE_EVENT (FOnIsTypedCharValid , OnIsTypedCharValid)
This is NOT for validating input!
Called whenever a character is typed. Not called for copy, paste, or any other text changes! Called whenever the text is changed programmatically or interactively by the user
References OnIsTypedCharValid, OnTextChanged(), and SLATE_EVENT().
Referenced by SLATE_ATTRIBUTE(), SLATE_ATTRIBUTE(), SLATE_EVENT(), SLATE_EVENT(), and SLATE_EVENT().
SLATE_EVENT() [2/3]
HintText Style ColorAndOpacity BackgroundImageComposing IsReadOnly IsCaretMovedWhenGainFocus SelectWordOnMouseDoubleClick ClearKeyboardFocusOnCommit AllowContextMenu OnContextMenuOpening OnTextChanged MinDesiredWidth OnKeyCharHandler SEditableText::SLATE_EVENT (FOnKeyDown , OnKeyDownHandler)
Callback delegate to have first chance handling of the OnKeyDown event.
Menu extender for the right-click context menu
References OnKeyDownHandler, and SLATE_EVENT().
SLATE_EVENT() [3/3]
HintText Style ColorAndOpacity BackgroundImageComposing IsReadOnly IsCaretMovedWhenGainFocus SelectWordOnMouseDoubleClick ClearKeyboardFocusOnCommit AllowContextMenu OnContextMenuOpening OnTextChanged SEditableText::SLATE_EVENT (FOnTextCommitted , OnTextCommitted)
Called whenever the text is committed.
This happens when the user presses enter or the text box loses focus. Minimum width that a text block should be
References MinDesiredWidth, OnTextCommitted(), SLATE_ATTRIBUTE(), and SLATE_EVENT().
SupportsKeyboardFocus()
virtual bool SEditableText::SupportsKeyboardFocus () const override protected virtual
Checks to see if this widget supports keyboard focus.
Override this in derived classes.
Returns
True if this widget can take keyboard focus
Reimplemented from SWidget.
SynchronizeTextStyle()
void SEditableText::SynchronizeTextStyle () protected
Synchronize the text style currently set (including from overrides) and update the text layout if required.
Tick()
virtual void SEditableText::Tick (const FGeometry & AllottedGeometry, const double InCurrentTime, const float InDeltaTime) override protected virtual
Ticks this widget with Geometry.
Override in derived classes, but always call the parent implementation.
Parameters
AllottedGeometry The space allotted for this widget
InCurrentTime Current absolute real time
InDeltaTime Real time passed since last tick
Reimplemented from SWidget.
UpdateAndClampHorizontalScrollBar()
virtual float SEditableText::UpdateAndClampHorizontalScrollBar (const float InViewOffset, const float InViewFraction, const EVisibility InVisiblityOverride) override protected virtual
Called when the fraction and offset of the horizontal scroll area has been recalculated.
This function should apply the new values to any scrollbars, and return a clamped horizontal scroll value
Implements ISlateEditableTextWidget.
UpdateAndClampVerticalScrollBar()
virtual float SEditableText::UpdateAndClampVerticalScrollBar (const float InViewOffset, const float InViewFraction, const EVisibility InVisiblityOverride) override protected virtual
Called when the fraction and offset of the vertical scroll area has been recalculated.
This function should apply the new values to any scrollbars, and return a clamped vertical scroll value
Implements ISlateEditableTextWidget.
Field Documentation
ActiveTickTimer
TWeakPtr<FActiveTimerHandle> SEditableText::ActiveTickTimer protected
The timer that is actively driving this widget to Tick() even when Slate is idle.
Definition at line 527 of file SEditableText.h.
BackgroundImageSelected
TAttribute<const FSlateBrush*> SEditableText::BackgroundImageSelected protected
Background image for the selected text.
Definition at line 476 of file SEditableText.h.
Referenced by SLATE_ATTRIBUTE().
bAllowContextMenu
TAttribute<bool> SEditableText::bAllowContextMenu protected
Whether to disable the context menu.
Definition at line 503 of file SEditableText.h.
bClearKeyboardFocusOnCommit
TAttribute<bool> SEditableText::bClearKeyboardFocusOnCommit protected
Whether to clear keyboard focus when pressing enter to commit changes.
Definition at line 494 of file SEditableText.h.
bEnableIntegratedKeyboard
TAttribute<bool> SEditableText::bEnableIntegratedKeyboard protected
Whether to enable integrated keyboard.
Definition at line 506 of file SEditableText.h.
bIsCaretMovedWhenGainFocus
TAttribute<bool> SEditableText::bIsCaretMovedWhenGainFocus protected
Workaround as we loose focus when the auto completion closes.
Definition at line 485 of file SEditableText.h.
bIsPassword
TAttribute<bool> SEditableText::bIsPassword protected
Sets whether this text box is for storing a password.
Definition at line 482 of file SEditableText.h.
bIsReadOnly
TAttribute<bool> SEditableText::bIsReadOnly protected
Sets whether this text box can actually be modified interactively by the user.
Definition at line 479 of file SEditableText.h.
bRevertTextOnEscape
TAttribute<bool> SEditableText::bRevertTextOnEscape protected
Whether to allow the user to back out of changes when they press the escape key.
Definition at line 491 of file SEditableText.h.
bSelectAllTextOnCommit
TAttribute<bool> SEditableText::bSelectAllTextOnCommit protected
Whether to select all text when pressing enter to commit changes.
Definition at line 497 of file SEditableText.h.
bSelectAllTextWhenFocused
TAttribute<bool> SEditableText::bSelectAllTextWhenFocused protected
Whether to select all text when the user clicks to give focus on the widget.
Definition at line 488 of file SEditableText.h.
bSelectWordOnMouseDoubleClick
TAttribute<bool> SEditableText::bSelectWordOnMouseDoubleClick protected
Whether to select word on mouse double click.
Definition at line 500 of file SEditableText.h.
ColorAndOpacity
TAttribute<FSlateColor> SEditableText::ColorAndOpacity protected
Text color and opacity.
Definition at line 473 of file SEditableText.h.
Referenced by SLATE_ATTRIBUTE().
EditableTextLayout
TUniquePtr<FSlateEditableTextLayout> SEditableText::EditableTextLayout protected
The text layout that deals with the editable text.
Definition at line 467 of file SEditableText.h.
Font
TAttribute<FSlateFontInfo> SEditableText::Font protected
The font used to draw the text.
Definition at line 470 of file SEditableText.h.
Referenced by SLATE_ATTRIBUTE().
MenuExtender
TSharedPtr<FExtender> SEditableText::MenuExtender protected
Menu extender for right-click context menu.
Definition at line 524 of file SEditableText.h.
MinDesiredWidth
TAttribute<float> SEditableText::MinDesiredWidth protected
Prevents the editable text from being smaller than desired in certain cases (e.g.
when it is empty)
Definition at line 521 of file SEditableText.h.
Referenced by SLATE_EVENT().
OnContextMenuOpening
FOnContextMenuOpening SEditableText::OnContextMenuOpening protected
Delegate to call before a context menu is opened.
Definition at line 509 of file SEditableText.h.
Referenced by SLATE_ATTRIBUTE().
OnIsTypedCharValid
FOnIsTypedCharValid SEditableText::OnIsTypedCharValid protected
Called when a character is typed and we want to know if the text field supports typing this character.
Definition at line 512 of file SEditableText.h.
Referenced by SLATE_EVENT().
OnKeyCharHandler
FOnKeyChar SEditableText::OnKeyCharHandler protected
Callback delegate to have first chance handling of the OnKeyChar event.
Definition at line 533 of file SEditableText.h.
Referenced by SetOnKeyCharHandler(), and SLATE_ATTRIBUTE().
OnKeyDownHandler
FOnKeyDown SEditableText::OnKeyDownHandler protected
Callback delegate to have first chance handling of the OnKeyDown event.
Definition at line 536 of file SEditableText.h.
Referenced by SetOnKeyDownHandler(), and SLATE_EVENT().
OnTextChangedCallback
FOnTextChanged SEditableText::OnTextChangedCallback protected
Called whenever the text is changed programmatically or interactively by the user.
Definition at line 515 of file SEditableText.h.
OnTextCommittedCallback
FOnTextCommitted SEditableText::OnTextCommittedCallback protected
Called whenever the text is committed.
This happens when the user presses enter or the text box loses focus.
Definition at line 518 of file SEditableText.h.
PlainTextMarshaller
TSharedPtr<FPlainTextLayoutMarshaller> SEditableText::PlainTextMarshaller protected
Text marshaller used by the editable text layout.
Definition at line 464 of file SEditableText.h.
VirtualKeyboardDismissAction
TAttribute<EVirtualKeyboardDismissAction> SEditableText::VirtualKeyboardDismissAction protected
The message action to take when the virtual keyboard is dismissed by the user.
Definition at line 548 of file SEditableText.h.
Referenced by SLATE_ATTRIBUTE().
VirtualKeyboardOptions
FVirtualKeyboardOptions SEditableText::VirtualKeyboardOptions protected
Additional options used by the virtual keyboard summoned by this widget.
Definition at line 542 of file SEditableText.h.
Referenced by SLATE_ATTRIBUTE().
VirtualKeyboardTrigger
TAttribute<EVirtualKeyboardTrigger> SEditableText::VirtualKeyboardTrigger protected
The type of event that will trigger the display of the virtual keyboard.
Definition at line 545 of file SEditableText.h.
Referenced by SLATE_ATTRIBUTE().
VirtualKeyboardType
TAttribute<EKeyboardType> SEditableText::VirtualKeyboardType protected
The type of virtual keyboard to use for editing this text on mobile.
Definition at line 539 of file SEditableText.h.
Referenced by SLATE_ATTRIBUTE().
WordBreakIterator
TSharedPtr<IBreakIterator> SEditableText::WordBreakIterator mutable protected
The iterator to use to detect word boundaries.
Definition at line 530 of file SEditableText.h.
The documentation for this class was generated from the following file:
Runtime/Slate/Public/Widgets/Input/SEditableText.h