Unreal Engine 5.6 C++ API: ASkyLight Class Reference
ASkyLight Class Reference
#include "SkyLight.h"
Public Member Functions
class USkyLightComponent * GetLightComponent () const
Returns LightComponent subobject.
UPROPERTY() uint32 bEnabled UFUNCTION () 1 virtual void OnRep_bEnabled()
replicated copy of LightComponent's bEnabled property
Private Member Functions
virtual bool ActorTypeSupportsDataLayer () const override
GENERATED_UCLASS_BODY () 1 virtual void GetLifetimeReplicatedProps(TArray< FLifetimeProperty > &OutLifetimeProps) const override
UPROPERTY ()) TObjectPtr< class USkyLightComponent > LightComponent
Detailed Description
Definition at line 11 of file SkyLight.h.
Member Function Documentation
ActorTypeSupportsDataLayer()
virtual bool ASkyLight::ActorTypeSupportsDataLayer () const inline override private virtual
Reimplemented from AInfo.
Definition at line 19 of file SkyLight.h.
GENERATED_UCLASS_BODY()
ASkyLight::GENERATED_UCLASS_BODY () const & override private
GetLightComponent()
class USkyLightComponent * ASkyLight::GetLightComponent () const inline
Returns LightComponent subobject.
Definition at line 35 of file SkyLight.h.
References GetLightComponent().
Referenced by GetLightComponent().
UFUNCTION()
UPROPERTY() uint32 bEnabled ASkyLight::UFUNCTION ()
replicated copy of LightComponent's bEnabled property
Replication Notification Callbacks
References UFUNCTION().
Referenced by UFUNCTION().
UPROPERTY()
ASkyLight::UPROPERTY () private
Todo
document
References Category, Light, meta, and UPROPERTY().
Referenced by UPROPERTY().
The documentation for this class was generated from the following file:
Runtime/Engine/Classes/Engine/SkyLight.h