Unreal Engine 5.6 C++ API: FBufferOwner Class Reference
FBufferOwner Class Reference abstract
A reference-counted owner for a buffer, which is a raw pointer and size.
#include "SharedBuffer.h"
Public Types
enum class EBufferOwnerFlags : uint8 { None = 0 , Owned = 1 << 0 , Immutable = 1 << 1 , Materialized = 1 << 2 }
Protected Member Functions
FBufferOwner ()=default
FBufferOwner (const FBufferOwner &)=delete
FBufferOwner (void *InData, uint64 InSize)
virtual ~FBufferOwner ()
virtual void FreeBuffer ()=0
Free the buffer and any associated resources.
void * GetData ()
uint64 GetSize ()
uint32 GetTotalRefCount () const
bool IsImmutable () const
bool IsMaterialized () const
bool IsOwned () const
void Materialize ()
virtual void MaterializeBuffer ()
Materialize the buffer by making it ready to be accessed.
FBufferOwner & operator= (const FBufferOwner &)=delete
void SetBuffer (void *InData, uint64 InSize)
void SetIsImmutable ()
void SetIsMaterialized ()
void SetIsOwned ()
Private Member Functions
void AddSharedReference ()
void AddWeakReference ()
FRIEND_ENUM_CLASS_FLAGS (EBufferOwnerFlags)
bool IsUniqueOwnedMutable () const
Returns whether this has one total reference, is owned, and is not immutable.
void ReleaseSharedReference ()
void ReleaseWeakReference ()
bool TryAddSharedReference ()
Static Private Member Functions
static constexpr EBufferOwnerFlags GetFlags (uint64 RefCountsAndFlags)
static constexpr uint32 GetSharedRefCount (uint64 RefCountsAndFlags)
static constexpr uint32 GetTotalRefCount (uint64 RefCountsAndFlags)
static constexpr uint32 GetWeakRefCount (uint64 RefCountsAndFlags)
static constexpr uint64 SetFlags (EBufferOwnerFlags Flags)
static constexpr uint64 SetSharedRefCount (uint32 RefCount)
static constexpr uint64 SetWeakRefCount (uint32 RefCount)
Private Attributes
void * Data = nullptr
std::atomic< uint64 > ReferenceCountsAndFlags {0}
uint64 Size = 0
Static Private Attributes
static constexpr uint32 RefCountMask = 0x3fffffff
Friends
class FSharedBuffer
class FUniqueBuffer
class FWeakSharedBuffer
struct UE::SharedBuffer::Private::FSharedOps
struct UE::SharedBuffer::Private::FWeakOps
Detailed Description
A reference-counted owner for a buffer, which is a raw pointer and size.
A buffer owner may own its memory or provide a view into memory owned externally. When used as a non-owning view, the viewed memory must be guaranteed to outlive the buffer owner. When this lifetime guarantee cannot be satisfied, MakeOwned may be called on the reference to the buffer to clone into a new buffer owner that owns the memory.
A buffer owner must be referenced and accessed through one of its three reference types: FUniqueBuffer, FSharedBuffer, or FWeakSharedBuffer.
FUniqueBuffer and FSharedBuffer offer static functions to create a buffer using private buffer owner types that are ideal for most use cases. The TakeOwnership function allows creation of a buffer with a custom delete function. Advanced use cases require deriving from FBufferOwner to enable storage of arbitrary members alongside the data and size, and to enable materialization of the buffer to be deferred.
A derived type must call SetIsOwned from its constructor if they own (or will own) the buffer. A derived type must call SetIsImmutable from its constructor if they want the buffer to become permanently immutable after it is stored in FSharedBuffer, forcing MoveToUnique() to clone it. A derived type must call SetIsMaterialized from its constructor, unless it implements deferred materialization by overriding MaterializeBuffer.
Definition at line 51 of file SharedBuffer.h.
Member Enumeration Documentation
EBufferOwnerFlags
enum class FBufferOwner::EBufferOwnerFlags : uint8 strong
Enumerator
None
Owned
Immutable
Materialized
Definition at line 587 of file SharedBuffer.h.
Constructor & Destructor Documentation
FBufferOwner() [1/3]
FBufferOwner::FBufferOwner () protected default
Referenced by FBufferOwner(), UE::SharedBuffer::Private::TBufferOwnerDeleteFunction< DeleteFunctionType >::TBufferOwnerDeleteFunction(), and operator=().
FBufferOwner() [2/3]
FBufferOwner::FBufferOwner (const FBufferOwner &) protected delete
References FBufferOwner().
FBufferOwner() [3/3]
FBufferOwner::FBufferOwner (void * InData, uint64 InSize) inline protected
Definition at line 597 of file SharedBuffer.h.
References Data, and Size.
~FBufferOwner()
FBufferOwner::~FBufferOwner () inline protected virtual
Definition at line 603 of file SharedBuffer.h.
References checkSlow, and GetTotalRefCount().
Member Function Documentation
AddSharedReference()
void FBufferOwner::AddSharedReference () inline private
Definition at line 690 of file SharedBuffer.h.
References AddWeakReference(), checkSlow, GetSharedRefCount(), RefCountMask, ReferenceCountsAndFlags, and SetSharedRefCount().
AddWeakReference()
void FBufferOwner::AddWeakReference () inline private
Definition at line 729 of file SharedBuffer.h.
References checkSlow, GetWeakRefCount(), RefCountMask, ReferenceCountsAndFlags, and SetWeakRefCount().
Referenced by AddSharedReference().
FreeBuffer()
virtual void FBufferOwner::FreeBuffer () protected pure virtual
Free the buffer and any associated resources.
This is called when the last shared reference is released. The destructor will be called when the last weak reference is released. A buffer owner will always call this function before the calling the destructor, unless an exception was thrown by the constructor.
Implemented in UE::SharedBuffer::Private::TBufferOwnerDeleteFunction< DeleteFunctionType >, and UE::SharedBuffer::Private::TBufferOwnerTArray< T, Allocator >.
Referenced by ReleaseSharedReference().
FRIEND_ENUM_CLASS_FLAGS()
FBufferOwner::FRIEND_ENUM_CLASS_FLAGS (EBufferOwnerFlags) private
GetData()
void * FBufferOwner::GetData () inline protected
Definition at line 613 of file SharedBuffer.h.
References Data, and Materialize().
GetFlags()
constexpr EBufferOwnerFlags FBufferOwner::GetFlags (uint64 RefCountsAndFlags) inline static constexpr private
Definition at line 108 of file SharedBuffer.h.
Referenced by IsImmutable(), IsMaterialized(), IsOwned(), and IsUniqueOwnedMutable().
GetSharedRefCount()
constexpr uint32 FBufferOwner::GetSharedRefCount (uint64 RefCountsAndFlags) inline static constexpr private
Definition at line 104 of file SharedBuffer.h.
References RefCountMask.
Referenced by AddSharedReference(), GetTotalRefCount(), ReleaseSharedReference(), and TryAddSharedReference().
GetSize()
uint64 FBufferOwner::GetSize () inline protected
Definition at line 619 of file SharedBuffer.h.
References Materialize(), and Size.
Referenced by UE::SharedBuffer::Private::TBufferOwnerDeleteFunction< DeleteFunctionType >::FreeBuffer().
GetTotalRefCount() [1/2]
uint32 FBufferOwner::GetTotalRefCount () const inline protected
Definition at line 670 of file SharedBuffer.h.
References GetTotalRefCount(), and ReferenceCountsAndFlags.
Referenced by ~FBufferOwner(), GetTotalRefCount(), and IsUniqueOwnedMutable().
GetTotalRefCount() [2/2]
uint32 FBufferOwner::GetTotalRefCount (uint64 RefCountsAndFlags) inline static constexpr private
Definition at line 675 of file SharedBuffer.h.
References GetSharedRefCount(), and GetWeakRefCount().
GetWeakRefCount()
constexpr uint32 FBufferOwner::GetWeakRefCount (uint64 RefCountsAndFlags) inline static constexpr private
Definition at line 106 of file SharedBuffer.h.
References RefCountMask.
Referenced by AddWeakReference(), GetTotalRefCount(), and ReleaseWeakReference().
IsImmutable()
bool FBufferOwner::IsImmutable () const inline protected
Definition at line 641 of file SharedBuffer.h.
References EnumHasAnyFlags(), GetFlags(), Immutable, and ReferenceCountsAndFlags.
IsMaterialized()
bool FBufferOwner::IsMaterialized () const inline protected
Definition at line 660 of file SharedBuffer.h.
References EnumHasAnyFlags(), GetFlags(), Materialized, and ReferenceCountsAndFlags.
Referenced by Materialize().
IsOwned()
bool FBufferOwner::IsOwned () const inline protected
Definition at line 631 of file SharedBuffer.h.
References EnumHasAnyFlags(), GetFlags(), Owned, and ReferenceCountsAndFlags.
IsUniqueOwnedMutable()
bool FBufferOwner::IsUniqueOwnedMutable () const inline private
Returns whether this has one total reference, is owned, and is not immutable.
Definition at line 683 of file SharedBuffer.h.
References GetFlags(), GetTotalRefCount(), Immutable, Owned, and ReferenceCountsAndFlags.
Materialize()
void FBufferOwner::Materialize () inline protected
Definition at line 651 of file SharedBuffer.h.
References checkSlow, IsMaterialized(), and MaterializeBuffer().
Referenced by GetData(), and GetSize().
MaterializeBuffer()
void FBufferOwner::MaterializeBuffer () inline protected virtual
Materialize the buffer by making it ready to be accessed.
This will be called before any access to the data or size, unless SetIsMaterialized is called by the constructor. Accesses from multiple threads will cause multiple calls to this function until at least one has finished.
Definition at line 608 of file SharedBuffer.h.
References SetIsMaterialized().
Referenced by Materialize().
operator=()
FBufferOwner & FBufferOwner::operator= (const FBufferOwner &) protected delete
References FBufferOwner().
ReleaseSharedReference()
void FBufferOwner::ReleaseSharedReference () inline private
Definition at line 700 of file SharedBuffer.h.
References checkSlow, Data, FreeBuffer(), GetSharedRefCount(), ReferenceCountsAndFlags, ReleaseWeakReference(), SetSharedRefCount(), and Size.
ReleaseWeakReference()
void FBufferOwner::ReleaseWeakReference () inline private
Definition at line 735 of file SharedBuffer.h.
References checkSlow, GetWeakRefCount(), ReferenceCountsAndFlags, and SetWeakRefCount().
Referenced by ReleaseSharedReference().
SetBuffer()
void FBufferOwner::SetBuffer (void * InData, uint64 InSize) inline protected
Definition at line 625 of file SharedBuffer.h.
References Data, and Size.
Referenced by UE::SharedBuffer::Private::TBufferOwnerTArray< T, Allocator >::TBufferOwnerTArray().
SetFlags()
constexpr uint64 FBufferOwner::SetFlags (EBufferOwnerFlags Flags) inline static constexpr private
Definition at line 109 of file SharedBuffer.h.
References Flags.
Referenced by SetIsImmutable(), SetIsMaterialized(), and SetIsOwned().
SetIsImmutable()
void FBufferOwner::SetIsImmutable () inline protected
Definition at line 646 of file SharedBuffer.h.
References Immutable, ReferenceCountsAndFlags, and SetFlags().
Referenced by UE::SharedBuffer::Private::TBufferOwnerDeleteFunction< DeleteFunctionType >::TBufferOwnerDeleteFunction().
SetIsMaterialized()
void FBufferOwner::SetIsMaterialized () inline protected
Definition at line 665 of file SharedBuffer.h.
References Materialized, ReferenceCountsAndFlags, and SetFlags().
Referenced by UE::SharedBuffer::Private::TBufferOwnerDeleteFunction< DeleteFunctionType >::TBufferOwnerDeleteFunction(), UE::SharedBuffer::Private::TBufferOwnerTArray< T, Allocator >::TBufferOwnerTArray(), and MaterializeBuffer().
SetIsOwned()
void FBufferOwner::SetIsOwned () inline protected
Definition at line 636 of file SharedBuffer.h.
References Owned, ReferenceCountsAndFlags, and SetFlags().
Referenced by UE::SharedBuffer::Private::TBufferOwnerDeleteFunction< DeleteFunctionType >::TBufferOwnerDeleteFunction(), and UE::SharedBuffer::Private::TBufferOwnerTArray< T, Allocator >::TBufferOwnerTArray().
SetSharedRefCount()
constexpr uint64 FBufferOwner::SetSharedRefCount (uint32 RefCount) inline static constexpr private
Definition at line 105 of file SharedBuffer.h.
Referenced by AddSharedReference(), ReleaseSharedReference(), and TryAddSharedReference().
SetWeakRefCount()
constexpr uint64 FBufferOwner::SetWeakRefCount (uint32 RefCount) inline static constexpr private
Definition at line 107 of file SharedBuffer.h.
Referenced by AddWeakReference(), and ReleaseWeakReference().
TryAddSharedReference()
bool FBufferOwner::TryAddSharedReference () inline private
Definition at line 713 of file SharedBuffer.h.
References GetSharedRefCount(), ReferenceCountsAndFlags, SetSharedRefCount(), and Value.
Friends And Related Symbol Documentation
FSharedBuffer
friend class FSharedBuffer friend
Definition at line 121 of file SharedBuffer.h.
References FSharedBuffer.
Referenced by FSharedBuffer.
FUniqueBuffer
friend class FUniqueBuffer friend
Definition at line 120 of file SharedBuffer.h.
References FUniqueBuffer.
Referenced by FUniqueBuffer.
FWeakSharedBuffer
friend class FWeakSharedBuffer friend
Definition at line 122 of file SharedBuffer.h.
References FWeakSharedBuffer.
Referenced by FWeakSharedBuffer.
UE::SharedBuffer::Private::FSharedOps
friend struct UE::SharedBuffer::Private::FSharedOps friend
Definition at line 123 of file SharedBuffer.h.
UE::SharedBuffer::Private::FWeakOps
friend struct UE::SharedBuffer::Private::FWeakOps friend
Definition at line 124 of file SharedBuffer.h.
Field Documentation
Data
void* FBufferOwner::Data = nullptr private
Definition at line 127 of file SharedBuffer.h.
Referenced by FBufferOwner(), UE::SharedBuffer::Private::TBufferOwnerDeleteFunction< DeleteFunctionType >::TBufferOwnerDeleteFunction(), UE::SharedBuffer::Private::TBufferOwnerDeleteFunction< DeleteFunctionType >::TBufferOwnerDeleteFunction(), GetData(), ReleaseSharedReference(), and SetBuffer().
RefCountMask
uint32 FBufferOwner::RefCountMask = 0x3fffffff static constexpr private
Definition at line 101 of file SharedBuffer.h.
Referenced by AddSharedReference(), AddWeakReference(), GetSharedRefCount(), and GetWeakRefCount().
ReferenceCountsAndFlags
std::atomic<uint64> FBufferOwner::ReferenceCountsAndFlags {0} private
Definition at line 129 of file SharedBuffer.h.
Referenced by AddSharedReference(), AddWeakReference(), GetTotalRefCount(), IsImmutable(), IsMaterialized(), IsOwned(), IsUniqueOwnedMutable(), ReleaseSharedReference(), ReleaseWeakReference(), SetIsImmutable(), SetIsMaterialized(), SetIsOwned(), and TryAddSharedReference().
Size
uint64 FBufferOwner::Size = 0 private
Definition at line 128 of file SharedBuffer.h.
Referenced by FBufferOwner(), UE::SharedBuffer::Private::TBufferOwnerDeleteFunction< DeleteFunctionType >::TBufferOwnerDeleteFunction(), UE::SharedBuffer::Private::TBufferOwnerDeleteFunction< DeleteFunctionType >::TBufferOwnerDeleteFunction(), GetSize(), ReleaseSharedReference(), and SetBuffer().
The documentation for this class was generated from the following file:
Runtime/Core/Public/Memory/SharedBuffer.h