Unreal Engine 5.6 C++ API: FStreamingGenerationActorDescViewMap Class Reference
FStreamingGenerationActorDescViewMap Class Reference
#include "WorldPartitionStreamingGeneration.h"
Public Member Functions
FStreamingGenerationActorDescViewMap ()
FStreamingGenerationActorDescViewMap (const FStreamingGenerationActorDescViewMap &)=delete
FStreamingGenerationActorDescViewMap (FStreamingGenerationActorDescViewMap &&)=default
FStreamingGenerationActorDescView * Emplace (const FGuid &InActorGuid, FStreamingGenerationActorDescView &&InActorDescView)
FStreamingGenerationActorDescView * Emplace (const FWorldPartitionActorDescInstance *InActorDescInstance)
template<class ClassType>
TArray< const FStreamingGenerationActorDescView * > FindByExactNativeClass () const
TArray< const FStreamingGenerationActorDescView * > FindByExactNativeClass (UClass *InExactNativeClass) const
const FStreamingGenerationActorDescView * FindByGuid (const FGuid &InGuid) const
const FStreamingGenerationActorDescView & FindByGuidChecked (const FGuid &InGuid) const
template<class Func>
void ForEachActorDescView (Func InFunc) const
const TMap< FGuid, FStreamingGenerationActorDescView * > & GetActorDescViewsByGuid () const
PRAGMA_ENABLE_DEPRECATION_WARNINGS FORCEINLINE int32 Num () const
FStreamingGenerationActorDescViewMap & operator= (const FStreamingGenerationActorDescViewMap &)=delete
FStreamingGenerationActorDescViewMap & operator= (FStreamingGenerationActorDescViewMap &&)=default
PRAGMA_DISABLE_DEPRECATION_WARNINGS UE_DEPRECATED (5.4, "Use FStreamingGenerationActorDescView version instead") FWorldPartitionActorDescView *Emplace(const FGuid &InActorGuid
UE_DEPRECATED (5.4, "Use FWorldPartitionActorDescInstance version instead") class FWorldPartitionActorDescView *Emplace(const FWorldPartitionActorDesc *InActorDesc)
Data Fields
PRAGMA_DISABLE_DEPRECATION_WARNINGS const FWorldPartitionActorDescView & InActorDescView { return nullptr
Protected Attributes
TArray< TUniquePtr< FStreamingGenerationActorDescView > > ActorDescViewList
TMultiMap< FName, const FStreamingGenerationActorDescView * > ActorDescViewsByClass
TMap< FGuid, FStreamingGenerationActorDescView * > ActorDescViewsByGuid
Private Member Functions
FStreamingGenerationActorDescView * FindByGuid (const FGuid &InGuid)
FStreamingGenerationActorDescView & FindByGuidChecked (const FGuid &InGuid)
template<class Func>
void ForEachActorDescView (Func InFunc)
Friends
class FWorldPartitionStreamingGenerator
Detailed Description
Definition at line 127 of file WorldPartitionStreamingGeneration.h.
Constructor & Destructor Documentation
FStreamingGenerationActorDescViewMap() [1/3]
FStreamingGenerationActorDescViewMap::FStreamingGenerationActorDescViewMap ()
Referenced by FStreamingGenerationActorDescViewMap(), FStreamingGenerationActorDescViewMap(), operator=(), and operator=().
FStreamingGenerationActorDescViewMap() [2/3]
FStreamingGenerationActorDescViewMap::FStreamingGenerationActorDescViewMap (const FStreamingGenerationActorDescViewMap &) delete
References FStreamingGenerationActorDescViewMap().
FStreamingGenerationActorDescViewMap() [3/3]
FStreamingGenerationActorDescViewMap::FStreamingGenerationActorDescViewMap (FStreamingGenerationActorDescViewMap &&) default
References FStreamingGenerationActorDescViewMap().
Member Function Documentation
Emplace() [1/2]
FStreamingGenerationActorDescView * FStreamingGenerationActorDescViewMap::Emplace (const FGuid & InActorGuid, FStreamingGenerationActorDescView && InActorDescView)
References InActorDescView.
Referenced by UE_DEPRECATED().
Emplace() [2/2]
FStreamingGenerationActorDescView * FStreamingGenerationActorDescViewMap::Emplace (const FWorldPartitionActorDescInstance * InActorDescInstance)
References PRAGMA_DISABLE_DEPRECATION_WARNINGS.
FindByExactNativeClass() [1/2]
template<class ClassType> TArray< const FStreamingGenerationActorDescView * > FStreamingGenerationActorDescViewMap::FindByExactNativeClass () const inline
Definition at line 217 of file WorldPartitionStreamingGeneration.h.
References FindByExactNativeClass().
Referenced by FindByExactNativeClass().
FindByExactNativeClass() [2/2]
TArray< const FStreamingGenerationActorDescView * > FStreamingGenerationActorDescViewMap::FindByExactNativeClass (UClass * InExactNativeClass) const
FindByGuid() [1/2]
FStreamingGenerationActorDescView * FStreamingGenerationActorDescViewMap::FindByGuid (const FGuid & InGuid) inline private
Definition at line 146 of file WorldPartitionStreamingGeneration.h.
References ActorDescViewsByGuid.
FindByGuid() [2/2]
const FStreamingGenerationActorDescView * FStreamingGenerationActorDescViewMap::FindByGuid (const FGuid & InGuid) const inline
Definition at line 202 of file WorldPartitionStreamingGeneration.h.
References ActorDescViewsByGuid.
FindByGuidChecked() [1/2]
FStreamingGenerationActorDescView & FStreamingGenerationActorDescViewMap::FindByGuidChecked (const FGuid & InGuid) inline private
Definition at line 155 of file WorldPartitionStreamingGeneration.h.
References ActorDescViewsByGuid.
FindByGuidChecked() [2/2]
const FStreamingGenerationActorDescView & FStreamingGenerationActorDescViewMap::FindByGuidChecked (const FGuid & InGuid) const inline
Definition at line 211 of file WorldPartitionStreamingGeneration.h.
References ActorDescViewsByGuid.
ForEachActorDescView() [1/2]
template<class Func> void FStreamingGenerationActorDescViewMap::ForEachActorDescView (Func InFunc) inline private
Definition at line 133 of file WorldPartitionStreamingGeneration.h.
References ActorDescViewList.
ForEachActorDescView() [2/2]
template<class Func> void FStreamingGenerationActorDescViewMap::ForEachActorDescView (Func InFunc) const inline
Definition at line 189 of file WorldPartitionStreamingGeneration.h.
References ActorDescViewList.
GetActorDescViewsByGuid()
const TMap< FGuid, FStreamingGenerationActorDescView * > & FStreamingGenerationActorDescViewMap::GetActorDescViewsByGuid () const inline
Definition at line 224 of file WorldPartitionStreamingGeneration.h.
References ActorDescViewsByGuid.
Num()
PRAGMA_ENABLE_DEPRECATION_WARNINGS FORCEINLINE int32 FStreamingGenerationActorDescViewMap::Num () const inline
Definition at line 183 of file WorldPartitionStreamingGeneration.h.
References ActorDescViewList, and FORCEINLINE.
operator=() [1/2]
FStreamingGenerationActorDescViewMap & FStreamingGenerationActorDescViewMap::operator= (const FStreamingGenerationActorDescViewMap &) delete
References FStreamingGenerationActorDescViewMap().
operator=() [2/2]
FStreamingGenerationActorDescViewMap & FStreamingGenerationActorDescViewMap::operator= (FStreamingGenerationActorDescViewMap &&) default
References FStreamingGenerationActorDescViewMap().
UE_DEPRECATED() [1/2]
PRAGMA_DISABLE_DEPRECATION_WARNINGS FStreamingGenerationActorDescViewMap::UE_DEPRECATED (5. 4, "Use FStreamingGenerationActorDescView version instead") const &
UE_DEPRECATED() [2/2]
FStreamingGenerationActorDescViewMap::UE_DEPRECATED (5. 4, "Use FWorldPartitionActorDescInstance version instead") const inline
Definition at line 178 of file WorldPartitionStreamingGeneration.h.
References Emplace().
Friends And Related Symbol Documentation
FWorldPartitionStreamingGenerator
friend class FWorldPartitionStreamingGenerator friend
Definition at line 129 of file WorldPartitionStreamingGeneration.h.
References FWorldPartitionStreamingGenerator.
Referenced by FWorldPartitionStreamingGenerator.
Field Documentation
ActorDescViewList
TArray<TUniquePtr<FStreamingGenerationActorDescView> > FStreamingGenerationActorDescViewMap::ActorDescViewList protected
Definition at line 227 of file WorldPartitionStreamingGeneration.h.
Referenced by ForEachActorDescView(), ForEachActorDescView(), and Num().
ActorDescViewsByClass
TMultiMap<FName, const FStreamingGenerationActorDescView*> FStreamingGenerationActorDescViewMap::ActorDescViewsByClass protected
Definition at line 230 of file WorldPartitionStreamingGeneration.h.
ActorDescViewsByGuid
TMap<FGuid, FStreamingGenerationActorDescView*> FStreamingGenerationActorDescViewMap::ActorDescViewsByGuid protected
Definition at line 229 of file WorldPartitionStreamingGeneration.h.
Referenced by FindByGuid(), FindByGuid(), FindByGuidChecked(), FindByGuidChecked(), and GetActorDescViewsByGuid().
InActorDescView
PRAGMA_DISABLE_DEPRECATION_WARNINGS const FWorldPartitionActorDescView& FStreamingGenerationActorDescViewMap::InActorDescView { return nullptr
Definition at line 176 of file WorldPartitionStreamingGeneration.h.
Referenced by Emplace().
The documentation for this class was generated from the following file:
Runtime/Engine/Public/WorldPartition/WorldPartitionStreamingGeneration.h