Unreal Engine 5.6 C++ API: UE::Geometry::FImageTiling Class Reference
UE::Geometry::FImageTiling Class Reference
#include "ImageTile.h"
Public Member Functions
FImageTiling (const FImageDimensions DimensionsIn, const int32 TileWidthIn, const int32 TileHeightIn)
FImageTile GetTile (const int32 LinearTileIndex, const int32 Padding=0) const
int32 Num () const
int32 NumTilesX () const
int32 NumTilesY () const
void SetTiling (const FImageDimensions DimensionsIn, const int32 TileWidthIn, const int32 TileHeightIn)
Private Attributes
FImageDimensions Dimensions
int32 TileHeight = 32
int32 TileWidth = 32
Detailed Description
Definition at line 112 of file ImageTile.h.
Constructor & Destructor Documentation
FImageTiling()
UE::Geometry::FImageTiling::FImageTiling (const FImageDimensions DimensionsIn, const int32 TileWidthIn, const int32 TileHeightIn) inline
Definition at line 120 of file ImageTile.h.
References SetTiling().
Member Function Documentation
GetTile()
FImageTile UE::Geometry::FImageTiling::GetTile (const int32 LinearTileIndex, const int32 Padding = 0) const inline
Returns
the tile data corresponding to the linear index [0, NumTiles()-1] w/ optional padding.
Definition at line 149 of file ImageTile.h.
References FMath::Clamp(), Dimensions, NumTilesX(), Padding, TileHeight, TileWidth, UE::Geometry::FVector2i::X, and UE::Geometry::FVector2i::Y.
Num()
int32 UE::Geometry::FImageTiling::Num () const inline
Definition at line 143 of file ImageTile.h.
References NumTilesX(), and NumTilesY().
NumTilesX()
int32 UE::Geometry::FImageTiling::NumTilesX () const inline
Definition at line 133 of file ImageTile.h.
References Dimensions, and TileWidth.
Referenced by GetTile(), and Num().
NumTilesY()
int32 UE::Geometry::FImageTiling::NumTilesY () const inline
Definition at line 138 of file ImageTile.h.
References Dimensions, and TileHeight.
Referenced by Num().
SetTiling()
void UE::Geometry::FImageTiling::SetTiling (const FImageDimensions DimensionsIn, const int32 TileWidthIn, const int32 TileHeightIn) inline
Definition at line 125 of file ImageTile.h.
References checkSlow, FMath::Clamp(), Dimensions, FMath::Max, TileHeight, and TileWidth.
Referenced by FImageTiling().
Field Documentation
Dimensions
FImageDimensions UE::Geometry::FImageTiling::Dimensions private
Definition at line 115 of file ImageTile.h.
Referenced by GetTile(), NumTilesX(), NumTilesY(), and SetTiling().
TileHeight
int32 UE::Geometry::FImageTiling::TileHeight = 32 private
Definition at line 117 of file ImageTile.h.
Referenced by GetTile(), NumTilesY(), and SetTiling().
TileWidth
int32 UE::Geometry::FImageTiling::TileWidth = 32 private
Definition at line 116 of file ImageTile.h.
Referenced by GetTile(), NumTilesX(), and SetTiling().
The documentation for this class was generated from the following file:
Runtime/GeometryCore/Public/Image/ImageTile.h