Unreal Engine 5.6 C++ API: FPropertyPairsMap Class Reference
FPropertyPairsMap Class Reference
A simple name/value pairs map.
#include "PropertyPairsMap.h"
Public Member Functions
FORCEINLINE void AddProperty (FName InName, FName InValue=NAME_None)
Add a property/value pair to the map.
template<class Func>
FORCEINLINE void ForEachProperty (Func InFunc)
Iterate through the property map and invoke a functor that can optionally break iteration by returning false.
FORCEINLINE bool GetProperty (const TCHAR *InName, FName *OutValue=nullptr) const
FORCEINLINE bool GetProperty (FName InName, FName *OutValue=nullptr) const
Gets the value associated with the provided property.
FORCEINLINE bool HasProperty (const TCHAR *InName) const
FORCEINLINE bool HasProperty (FName InName) const
Test if the provided property exists in the map.
FORCEINLINE bool IsEmpty () const
FORCEINLINE int32 Num () const
bool operator!= (const FPropertyPairsMap &InOther) const
bool operator== (const FPropertyPairsMap &InOther) const
Compare this map with another for equality, ignoring ordering.
FORCEINLINE FString ToString () const
Converts this property map to a string representation.
Protected Attributes
TMap< FName, FName > Properties
Friends
FORCEINLINE friend FArchive & operator<< (FArchive &InAr, FPropertyPairsMap &InPropertyPairsMap)
Serialize this property map to the provided archive.
Detailed Description
A simple name/value pairs map.
Definition at line 12 of file PropertyPairsMap.h.
Member Function Documentation
AddProperty()
FORCEINLINE void FPropertyPairsMap::AddProperty (FName InName, FName InValue = NAME_None) inline
Add a property/value pair to the map.
This will replace any existing property with the new value.
Parameters
InName Name of the property.
InValue Optional value to be associated with the property.
Definition at line 21 of file PropertyPairsMap.h.
References FORCEINLINE, InName, and Properties.
ForEachProperty()
template<class Func> FORCEINLINE void FPropertyPairsMap::ForEachProperty (Func InFunc) inline
Iterate through the property map and invoke a functor that can optionally break iteration by returning false.
Parameters
InFunc Function to invoke on the properties of the map.
Definition at line 103 of file PropertyPairsMap.h.
References FORCEINLINE, Name, Properties, and Value.
GetProperty() [1/2]
FORCEINLINE bool FPropertyPairsMap::GetProperty (const TCHAR * InName, FName * OutValue = nullptr) const inline
Definition at line 63 of file PropertyPairsMap.h.
References FNAME_Find, FORCEINLINE, GetProperty(), InName, and PropertyName.
GetProperty() [2/2]
FORCEINLINE bool FPropertyPairsMap::GetProperty (FName InName, FName * OutValue = nullptr) const inline
Gets the value associated with the provided property.
Parameters
InName Name of the property. @out OutValue Value associated with the provided property.
Returns
True if the property exist in the map.
Definition at line 50 of file PropertyPairsMap.h.
References FORCEINLINE, InName, and Properties.
Referenced by GetProperty(), HasProperty(), and HasProperty().
HasProperty() [1/2]
FORCEINLINE bool FPropertyPairsMap::HasProperty (const TCHAR * InName) const inline
Definition at line 37 of file PropertyPairsMap.h.
References FNAME_Find, FORCEINLINE, GetProperty(), InName, and PropertyName.
HasProperty() [2/2]
FORCEINLINE bool FPropertyPairsMap::HasProperty (FName InName) const inline
Test if the provided property exists in the map.
Parameters
InName Name of the property.
Returns
True if the property exist in the map.
Definition at line 32 of file PropertyPairsMap.h.
References FORCEINLINE, GetProperty(), and InName.
IsEmpty()
FORCEINLINE bool FPropertyPairsMap::IsEmpty () const inline
Returns
True if the property map is empty.
Definition at line 117 of file PropertyPairsMap.h.
References FORCEINLINE, and Properties.
Num()
FORCEINLINE int32 FPropertyPairsMap::Num () const inline
Returns
The number of properties in the map.
Definition at line 123 of file PropertyPairsMap.h.
References FORCEINLINE, and Properties.
operator!=()
bool FPropertyPairsMap::operator!= (const FPropertyPairsMap & InOther) const inline
Definition at line 80 of file PropertyPairsMap.h.
operator==()
bool FPropertyPairsMap::operator== (const FPropertyPairsMap & InOther) const inline
Compare this map with another for equality, ignoring ordering.
Parameters
InOther Other property map to compare against.
Returns
True if the property maps contains the same properties and values.
Definition at line 75 of file PropertyPairsMap.h.
References Properties.
ToString()
FORCEINLINE FString FPropertyPairsMap::ToString () const inline
Converts this property map to a string representation.
Returns
The string representation.
Definition at line 133 of file PropertyPairsMap.h.
References TStringBuilderBase< CharType >::Append(), TStringBuilderBase< CharType >::AppendChar(), FORCEINLINE, Name, Properties, TStringBuilderBase< CharType >::RemoveSuffix(), TEXT, TStringBuilderBase< CharType >::ToString(), and Value.
Friends And Related Symbol Documentation
operator<<
FORCEINLINE friend FArchive & operator<< (FArchive & InAr, FPropertyPairsMap & InPropertyPairsMap) friend
Serialize this property map to the provided archive.
Parameters
Ar Archive to serialize to.
InPropertyPairsMap Property map to serialize.
Returns
Archive used to serialize the property map.
Definition at line 92 of file PropertyPairsMap.h.
References FORCEINLINE, and Properties.
Field Documentation
Properties
TMap<FName, FName> FPropertyPairsMap::Properties protected
Definition at line 164 of file PropertyPairsMap.h.
Referenced by AddProperty(), ForEachProperty(), GetProperty(), IsEmpty(), Num(), operator<<, operator==(), and ToString().
The documentation for this class was generated from the following file:
Runtime/Engine/Public/PropertyPairsMap.h