Unreal Engine 5.6 C++ API: FRDGResource Class Reference
FRDGResource Class Reference
Generic graph resource.
#include "RenderGraphResources.h"
Public Member Functions
FRDGResource (const FRDGResource &)=delete
virtual ~FRDGResource ()=default
FRHIResource * GetRHI () const
virtual RENDERCORE_API void MarkResourceAsUsed ()
The following methods may only be called during pass execution.
Data Fields
const TCHAR *const Name = nullptr
Protected Member Functions
FRDGResource (const TCHAR *InName)
FRHIResource * GetRHIUnchecked () const
bool HasRHI () const
RENDERCORE_API void ValidateRHIAccess () const
Protected Attributes
FRHIResource * ResourceRHI = nullptr
Private Attributes
uint8 bAllowRHIAccess: 1
friend FRDGBarrierValidation
friend FRDGBuilder
friend FRDGUserValidation
Detailed Description
Generic graph resource.
Definition at line 130 of file RenderGraphResources.h.
Constructor & Destructor Documentation
FRDGResource() [1/2]
FRDGResource::FRDGResource (const FRDGResource &) delete
References FRDGResource().
Referenced by FRDGResource(), FRDGUniformBuffer::FRDGUniformBuffer(), and FRDGView::FRDGView().
~FRDGResource()
virtual FRDGResource::~FRDGResource () virtual default
FRDGResource() [2/2]
FRDGResource::FRDGResource (const TCHAR * InName) inline protected
Definition at line 158 of file RenderGraphResources.h.
References bAllowRHIAccess, InName, Name, and RDG_ENABLE_DEBUG.
Member Function Documentation
GetRHI()
FRHIResource * FRDGResource::GetRHI () const inline
Definition at line 149 of file RenderGraphResources.h.
References IF_RDG_ENABLE_DEBUG, ResourceRHI, and ValidateRHIAccess().
Referenced by FRDGBuffer::GetRHI(), FRDGShaderResourceView::GetRHI(), FRDGTexture::GetRHI(), FRDGUniformBuffer::GetRHI(), FRDGUnorderedAccessView::GetRHI(), and GetShaderParameterResourceRHI().
GetRHIUnchecked()
FRHIResource * FRDGResource::GetRHIUnchecked () const inline protected
Definition at line 165 of file RenderGraphResources.h.
References ResourceRHI.
Referenced by FRDGBuffer::GetRHIUnchecked(), FRDGShaderResourceView::GetRHIUnchecked(), FRDGTexture::GetRHIUnchecked(), FRDGUniformBuffer::GetRHIUnchecked(), and FRDGUnorderedAccessView::GetRHIUnchecked().
HasRHI()
bool FRDGResource::HasRHI () const inline protected
Definition at line 170 of file RenderGraphResources.h.
References ResourceRHI.
MarkResourceAsUsed()
virtual RENDERCORE_API void FRDGResource::MarkResourceAsUsed () virtual
The following methods may only be called during pass execution.
Marks this resource as actually used by a resource. This is to track what dependencies on pass was actually unnecessary.
Reimplemented in FRDGUniformBuffer.
Referenced by FComputeShaderUtils::AddPass().
ValidateRHIAccess()
RENDERCORE_API void FRDGResource::ValidateRHIAccess () const protected
Referenced by FRDGTextureUAV::GetParentRHI(), and GetRHI().
Field Documentation
bAllowRHIAccess
uint8 FRDGResource::bAllowRHIAccess private
Definition at line 183 of file RenderGraphResources.h.
Referenced by FRDGResource().
FRDGBarrierValidation
friend FRDGResource::FRDGBarrierValidation private
Definition at line 188 of file RenderGraphResources.h.
FRDGBuilder
friend FRDGResource::FRDGBuilder private
Definition at line 186 of file RenderGraphResources.h.
FRDGUserValidation
friend FRDGResource::FRDGUserValidation private
Definition at line 187 of file RenderGraphResources.h.
Name
const TCHAR* const FRDGResource::Name = nullptr
Definition at line 137 of file RenderGraphResources.h.
Referenced by FRDGResource(), FRDGView::FRDGView(), FComputeShaderUtils::AddPass(), FRDGBuffer::GetIndirectRHICallBuffer(), FRDGExternalAccessQueue::Validate(), and FComputeShaderUtils::ValidateIndirectArgsBuffer().
ResourceRHI
FRHIResource* FRDGResource::ResourceRHI = nullptr protected
Definition at line 175 of file RenderGraphResources.h.
Referenced by GetRHI(), GetRHIUnchecked(), HasRHI(), and FRDGViewableResource::SetRHI().
The documentation for this class was generated from the following file:
Runtime/RenderCore/Public/RenderGraphResources.h