Unreal Engine 5.6 C++ API: SSplitter2x2::FSlot Class Reference
SSplitter2x2::FSlot Class Reference
Public Member Functions
FSlot (const TSharedRef< SWidget > &InWidget)
void Construct (const FChildren &SlotOwner, FSlotArguments &&InArg)
FVector2D GetPercentage () const
SLATE_SLOT_BEGIN_ARGS (FSlot, TSlotBase< FSlot >) SLATE_ATTRIBUTE(FVector2D
Percentage SLATE_SLOT_END_ARGS () void SetPercentage(const FVector2D &Value)
Sets the percentage attribute.
Public Member Functions inherited from TSlotBase< FSlot >
void Construct (const FChildren &SlotOwner, FSlotArguments &&InArgs)
FSlot & Expose (FSlot *&OutVarToInit)
FSlotBase ()
FSlotBase (const FChildren &InParent)
FSlotBase (const FSlotBase &)=delete
FSlotBase (const TSharedRef< SWidget > &InWidget)
FSlot & operator[] (TSharedRef< SWidget > &&InChildWidget)
Public Member Functions inherited from FSlotBase
FSlotBase ()
FSlotBase (const FChildren &InParent)
FSlotBase (const FSlotBase &)=delete
FSlotBase (const TSharedRef< SWidget > &InWidget)
virtual ~FSlotBase ()
FORCEINLINE_DEBUGGABLE void AttachWidget (const TSharedRef< SWidget > &InWidget)
FORCEINLINE_DEBUGGABLE void AttachWidget (TSharedRef< SWidget > &&InWidget)
Attach the child widget the slot now owns.
const TSharedPtr< SWidget > DetachWidget ()
Remove the widget from its current slot.
const FChildren * GetOwner () const
Access the FChildren that own the slot.
SWidget * GetOwnerWidget () const
Access the widget that own the slot.
FORCEINLINE_DEBUGGABLE const TSharedRef< SWidget > & GetWidget () const
Access the widget in the current slot.
void Invalidate (EInvalidateWidgetReason InvalidateReason)
Invalidate the widget's owner.
FSlotBase & operator= (const FSlotBase &)=delete
void SetOwner (const FChildren &Children)
Set the owner of the slot.
Private Attributes
TAttribute< FVector2D > PercentageAttribute
The percentage of the alloted space of the splitter that this slot requires.
Additional Inherited Members
Public Types inherited from TSlotBase< FSlot >
enum EConstructSlotIsFChildren
Argument to indicate the Slot is also its owner.
Protected Member Functions inherited from FSlotBase
template<typename TargetValueType, typename SourceValueType>
bool SetAttribute (TAttribute< TargetValueType > &TargetValue, const TAttribute< SourceValueType > &SourceValue, EInvalidateWidgetReason BaseInvalidationReason)
Performs the attribute assignment and invalidates the widget minimally based on what actually changed.
Detailed Description
Definition at line 416 of file SSplitter.h.
Constructor & Destructor Documentation
FSlot()
SSplitter2x2::FSlot::FSlot (const TSharedRef< SWidget > & InWidget)
Referenced by SLATE_SLOT_BEGIN_ARGS().
Member Function Documentation
Construct()
void SSplitter2x2::FSlot::Construct (const FChildren & SlotOwner, FSlotArguments && InArg)
GetPercentage()
FVector2D SSplitter2x2::FSlot::GetPercentage () const inline
Definition at line 433 of file SSplitter.h.
References PercentageAttribute.
SLATE_SLOT_BEGIN_ARGS()
SSplitter2x2::FSlot::SLATE_SLOT_BEGIN_ARGS (FSlot , TSlotBase< FSlot >)
References FSlot(), and Percentage.
SLATE_SLOT_END_ARGS()
Percentage SSplitter2x2::FSlot::SLATE_SLOT_END_ARGS () const & inline
Sets the percentage attribute.
Parameters
Value The new percentage value
Definition at line 421 of file SSplitter.h.
References PercentageAttribute, SLATE_SLOT_END_ARGS(), and Value.
Referenced by SLATE_SLOT_END_ARGS().
Field Documentation
PercentageAttribute
TAttribute<FVector2D> SSplitter2x2::FSlot::PercentageAttribute private
The percentage of the alloted space of the splitter that this slot requires.
Definition at line 444 of file SSplitter.h.
Referenced by GetPercentage(), and SLATE_SLOT_END_ARGS().
The documentation for this class was generated from the following file:
Runtime/Slate/Public/Widgets/Layout/SSplitter.h