Unreal Engine 5.6 C++ API: UBTDecorator_Loop Class Reference
UBTDecorator_Loop Class Reference
#include "BTDecorator_Loop.h"
Protected Member Functions
virtual AIMODULE_API void OnNodeActivation (FBehaviorTreeSearchData &SearchData) override
Private Member Functions
virtual AIMODULE_API void CleanupMemory (UBehaviorTreeComponent &OwnerComp, uint8 *NodeMemory, EBTMemoryClear::Type CleanupType) const override
virtual AIMODULE_API void DescribeRuntimeValues (const UBehaviorTreeComponent &OwnerComp, uint8 *NodeMemory, EBTDescriptionVerbosity::Type Verbosity, TArray< FString > &Values) const override
GENERATED_UCLASS_BODY () UPROPERTY()) FValueOrBBKey_Int32 NumLoops
number of executions
virtual AIMODULE_API uint16 GetInstanceMemorySize () const override
virtual AIMODULE_API FName GetNodeIconName () const override
virtual AIMODULE_API FString GetStaticDescription () const override
virtual AIMODULE_API void InitializeMemory (UBehaviorTreeComponent &OwnerComp, uint8 *NodeMemory, EBTMemoryInit::Type InitType) const override
UPROPERTY () bool bInfiniteLoop
infinite loop
UPROPERTY ()) FValueOrBBKey_Float InfiniteLoopTimeoutTime
timeout (when looping infinitely, when we finish a loop we will check whether we have spent this time looping, if we have we will stop looping).
Detailed Description
Definition at line 22 of file BTDecorator_Loop.h.
Member Function Documentation
CleanupMemory()
virtual AIMODULE_API void UBTDecorator_Loop::CleanupMemory (UBehaviorTreeComponent & OwnerComp, uint8 * NodeMemory, EBTMemoryClear::Type CleanupType) const override private virtual
References CleanupMemory().
Referenced by CleanupMemory().
DescribeRuntimeValues()
virtual AIMODULE_API void UBTDecorator_Loop::DescribeRuntimeValues (const UBehaviorTreeComponent & OwnerComp, uint8 * NodeMemory, EBTDescriptionVerbosity::Type Verbosity, TArray< FString > & Values) const override private virtual
References DescribeRuntimeValues().
Referenced by DescribeRuntimeValues().
GENERATED_UCLASS_BODY()
UBTDecorator_Loop::GENERATED_UCLASS_BODY () private
number of executions
References Category, meta, and UPROPERTY().
GetInstanceMemorySize()
virtual AIMODULE_API uint16 UBTDecorator_Loop::GetInstanceMemorySize () const override private virtual
References GetInstanceMemorySize().
Referenced by GetInstanceMemorySize().
GetNodeIconName()
virtual AIMODULE_API FName UBTDecorator_Loop::GetNodeIconName () const override private virtual
GetStaticDescription()
virtual AIMODULE_API FString UBTDecorator_Loop::GetStaticDescription () const override private virtual
References GetStaticDescription().
Referenced by GetStaticDescription().
InitializeMemory()
virtual AIMODULE_API void UBTDecorator_Loop::InitializeMemory (UBehaviorTreeComponent & OwnerComp, uint8 * NodeMemory, EBTMemoryInit::Type InitType) const override private virtual
References InitializeMemory().
Referenced by InitializeMemory().
OnNodeActivation()
virtual AIMODULE_API void UBTDecorator_Loop::OnNodeActivation (FBehaviorTreeSearchData & SearchData) override protected virtual
UPROPERTY() [1/2]
UBTDecorator_Loop::UPROPERTY () private
infinite loop
References Category, and UPROPERTY().
Referenced by GENERATED_UCLASS_BODY(), UPROPERTY(), and UPROPERTY().
UPROPERTY() [2/2]
UBTDecorator_Loop::UPROPERTY () private
timeout (when looping infinitely, when we finish a loop we will check whether we have spent this time looping, if we have we will stop looping).
A negative value means loop forever.
References Category, meta, and UPROPERTY().
The documentation for this class was generated from the following file:
Runtime/AIModule/Classes/BehaviorTree/Decorators/BTDecorator_Loop.h