Unreal Engine 5.6 C++ API: FPerformanceTrackingChart Class Reference
FPerformanceTrackingChart Class Reference
Chart for a single portion of gameplay (e.g., gameplay or in-game-shop or settings menu open) WARNING: If you add members here, you MUST also update AccumulateWith() as it accumulates each measure from another chart.
#include "ChartCreation.h"
Public Member Functions
FPerformanceTrackingChart ()
FPerformanceTrackingChart (const FDateTime &InStartTime, const FString &InChartLabel)
virtual ~FPerformanceTrackingChart ()
void AccumulateWith (const FPerformanceTrackingChart &Chart)
void ChangeLabel (const FString &NewLabel)
void DumpChartsToOutputLog (double WallClockElapsed, const TArray< const FPerformanceTrackingChart * > &Charts, const FString &InMapName)
void DumpChartToAnalyticsParams (const FString &InMapName, TArray< struct FAnalyticsEventAttribute > &InParamArray, bool bIncludeClientHWInfo, bool bIncludeHistograms=true) const
void DumpFPSChart (const FString &InMapName)
double GetAverageFramerate () const
double GetAvgHitchesPerMinute () const
double GetAvgHitchFrameLength () const
int64 GetNumFrames () const
int64 GetNumHitches () const
double GetPercentFramesIOBusy (int32 StartingBin=0) const
double GetPercentHitchTime (bool bSubtractHitchThreshold=true) const
double GetPercentMissedVSync (int32 TargetFPS) const
double GetTotalHitchFrameTime (bool bSubtractHitchThreshold=true) const
Sum of all recorded hitch lengths (in seconds)
double GetTotalTime () const
void PauseCharting ()
virtual void ProcessFrame (const FFrameData &FrameData) override
void Reset (const FDateTime &InStartTime)
void ResumeCharting ()
virtual void StartCharting () override
virtual void StopCharting () override
Public Member Functions inherited from IPerformanceDataConsumer
virtual ~IPerformanceDataConsumer ()
Data Fields
double AccumulatedChartTime
Total accumulated raw (including idle) time spent with the chart registered.
FHistogram AsyncPackageQueueHistogram
bool bIsChartingPaused
FDateTime CaptureStartTime
Start time of the capture.
FString ChartLabel
FString DeviceProfileName
WARNING: This value could technically change while data collection is ongoing.
FHistogram DynamicResHistogram
int FramesDisregarded
Number of frames that were disregarded because the frame was too long.
FHistogram FrametimeHistogram
FHistogram HitchTimeHistogram
int32 MaxDrawCalls
Total number of draw calls made.
int32 MaxDrawnPrimitives
Total number of primitives drawn.
double MaxFlushAsyncLoadingTime
uint64 MaxPhysicalMemory
int32 MaxPlayerTicks
Total number of player ticks (note: it is up to the game to populate this field) WARNING: Legacy fields.
int32 MaxVehicleTicks
Total number of vehicle ticks (note: it is up to the game to populate this field) WARNING: Legacy field.
uint64 MaxVirtualMemory
uint64 MinAvailablePhysicalMemory
int32 MinDrawCalls
int32 MinDrawnPrimitives
uint64 MinPhysicalMemory
int32 MinPlayerTicks
uint64 MinVirtualMemory
uint32 NumFramesAtCriticalMemoryPressure
uint32 NumFramesBound_GameThread
Number of frames for each time of <boundtype>
uint32 NumFramesBound_GPU
uint32 NumFramesBound_RenderThread
uint32 NumFramesBound_RHIThread
int StartBatteryLevel
float StartTemperatureLevel
int StopBatteryLevel
float StopTemperatureLevel
double TimeDisregarded
Total time (sec) that were disregarded because the frame was too long.
int32 TotalDrawCalls
int64 TotalDrawnPrimitives
int32 TotalFlushAsyncLoadingCalls
double TotalFlushAsyncLoadingTime
Total time spent flushing async loading (in seconds), and call count.
double TotalFramesBoundTime_GameThread
Time spent bound on each kind of thing (in seconds)
double TotalFramesBoundTime_GPU
double TotalFramesBoundTime_RenderThread
double TotalFramesBoundTime_RHIThread
double TotalFrameTime_GameThread
Total time spent on each thread (in seconds)
double TotalFrameTime_GPU
double TotalFrameTime_RenderThread
double TotalFrameTime_RHIThread
int32 TotalGameThreadBoundHitchCount
Total number of hitches bound by each kind of thing.
int32 TotalGPUBoundHitchCount
uint64 TotalPhysicalMemoryUsed
int32 TotalPlayerTicks
int32 TotalRenderThreadBoundHitchCount
int32 TotalRHIThreadBoundHitchCount
uint32 TotalSyncLoadCount
Total number of sync loads.
int32 TotalVehicleTicks
uint64 TotalVirtualMemoryUsed
Detailed Description
Chart for a single portion of gameplay (e.g., gameplay or in-game-shop or settings menu open) WARNING: If you add members here, you MUST also update AccumulateWith() as it accumulates each measure from another chart.
Definition at line 140 of file ChartCreation.h.
Constructor & Destructor Documentation
FPerformanceTrackingChart() [1/2]
FPerformanceTrackingChart::FPerformanceTrackingChart ()
Referenced by AccumulateWith().
FPerformanceTrackingChart() [2/2]
FPerformanceTrackingChart::FPerformanceTrackingChart (const FDateTime & InStartTime, const FString & InChartLabel)
~FPerformanceTrackingChart()
virtual FPerformanceTrackingChart::~FPerformanceTrackingChart () virtual
Member Function Documentation
AccumulateWith()
void FPerformanceTrackingChart::AccumulateWith (const FPerformanceTrackingChart & Chart)
References FPerformanceTrackingChart().
ChangeLabel()
void FPerformanceTrackingChart::ChangeLabel (const FString & NewLabel) inline
Definition at line 312 of file ChartCreation.h.
References ChartLabel.
DumpChartsToOutputLog()
void FPerformanceTrackingChart::DumpChartsToOutputLog (double WallClockElapsed, const TArray< const FPerformanceTrackingChart * > & Charts, const FString & InMapName)
DumpChartToAnalyticsParams()
void FPerformanceTrackingChart::DumpChartToAnalyticsParams (const FString & InMapName, TArray< struct FAnalyticsEventAttribute > & InParamArray, bool bIncludeClientHWInfo, bool bIncludeHistograms = true) const
DumpFPSChart()
void FPerformanceTrackingChart::DumpFPSChart (const FString & InMapName)
GetAverageFramerate()
double FPerformanceTrackingChart::GetAverageFramerate () const inline
Definition at line 267 of file ChartCreation.h.
References GetNumFrames(), and GetTotalTime().
GetAvgHitchesPerMinute()
double FPerformanceTrackingChart::GetAvgHitchesPerMinute () const inline
Definition at line 297 of file ChartCreation.h.
References GetNumHitches(), and GetTotalTime().
GetAvgHitchFrameLength()
double FPerformanceTrackingChart::GetAvgHitchFrameLength () const inline
Definition at line 305 of file ChartCreation.h.
References HitchTimeHistogram.
GetNumFrames()
int64 FPerformanceTrackingChart::GetNumFrames () const inline
Definition at line 262 of file ChartCreation.h.
References FrametimeHistogram.
Referenced by GetAverageFramerate(), and GetPercentMissedVSync().
GetNumHitches()
int64 FPerformanceTrackingChart::GetNumHitches () const inline
Definition at line 272 of file ChartCreation.h.
References HitchTimeHistogram.
Referenced by GetAvgHitchesPerMinute().
GetPercentFramesIOBusy()
double FPerformanceTrackingChart::GetPercentFramesIOBusy (int32 StartingBin = 0) const
GetPercentHitchTime()
double FPerformanceTrackingChart::GetPercentHitchTime (bool bSubtractHitchThreshold = true) const inline
Definition at line 283 of file ChartCreation.h.
References GetTotalHitchFrameTime(), and GetTotalTime().
GetPercentMissedVSync()
double FPerformanceTrackingChart::GetPercentMissedVSync (int32 TargetFPS) const inline
Definition at line 290 of file ChartCreation.h.
References GetNumFrames(), GetTotalTime(), and FMath::Max.
GetTotalHitchFrameTime()
double FPerformanceTrackingChart::GetTotalHitchFrameTime (bool bSubtractHitchThreshold = true) const
Sum of all recorded hitch lengths (in seconds)
Parameters
bSubtractHitchThreshold Bias towards larger hitches by removing "acceptable" frame time
Referenced by GetPercentHitchTime().
GetTotalTime()
double FPerformanceTrackingChart::GetTotalTime () const inline
Definition at line 257 of file ChartCreation.h.
References FrametimeHistogram.
Referenced by GetAverageFramerate(), GetAvgHitchesPerMinute(), GetPercentHitchTime(), and GetPercentMissedVSync().
PauseCharting()
void FPerformanceTrackingChart::PauseCharting ()
ProcessFrame()
virtual void FPerformanceTrackingChart::ProcessFrame (const FFrameData & FrameData) override virtual
Implements IPerformanceDataConsumer.
Reset()
void FPerformanceTrackingChart::Reset (const FDateTime & InStartTime)
ResumeCharting()
void FPerformanceTrackingChart::ResumeCharting ()
StartCharting()
virtual void FPerformanceTrackingChart::StartCharting () override virtual
Implements IPerformanceDataConsumer.
StopCharting()
virtual void FPerformanceTrackingChart::StopCharting () override virtual
Implements IPerformanceDataConsumer.
Field Documentation
AccumulatedChartTime
double FPerformanceTrackingChart::AccumulatedChartTime
Total accumulated raw (including idle) time spent with the chart registered.
Definition at line 219 of file ChartCreation.h.
AsyncPackageQueueHistogram
FHistogram FPerformanceTrackingChart::AsyncPackageQueueHistogram
Definition at line 156 of file ChartCreation.h.
bIsChartingPaused
bool FPerformanceTrackingChart::bIsChartingPaused
Definition at line 235 of file ChartCreation.h.
CaptureStartTime
FDateTime FPerformanceTrackingChart::CaptureStartTime
Start time of the capture.
Definition at line 216 of file ChartCreation.h.
ChartLabel
FString FPerformanceTrackingChart::ChartLabel
Definition at line 144 of file ChartCreation.h.
Referenced by ChangeLabel().
DeviceProfileName
FString FPerformanceTrackingChart::DeviceProfileName
WARNING: This value could technically change while data collection is ongoing.
Hanlding such changes is not handled by this code.
Definition at line 233 of file ChartCreation.h.
DynamicResHistogram
FHistogram FPerformanceTrackingChart::DynamicResHistogram
Definition at line 153 of file ChartCreation.h.
FramesDisregarded
int FPerformanceTrackingChart::FramesDisregarded
Number of frames that were disregarded because the frame was too long.
This is probably a clock glitch or an app returning from background, suspend, etc, and can really skew the data.
Definition at line 224 of file ChartCreation.h.
FrametimeHistogram
FHistogram FPerformanceTrackingChart::FrametimeHistogram
Definition at line 147 of file ChartCreation.h.
Referenced by GetNumFrames(), and GetTotalTime().
HitchTimeHistogram
FHistogram FPerformanceTrackingChart::HitchTimeHistogram
Definition at line 150 of file ChartCreation.h.
Referenced by GetAvgHitchFrameLength(), and GetNumHitches().
MaxDrawCalls
int32 FPerformanceTrackingChart::MaxDrawCalls
Total number of draw calls made.
Definition at line 191 of file ChartCreation.h.
MaxDrawnPrimitives
int32 FPerformanceTrackingChart::MaxDrawnPrimitives
Total number of primitives drawn.
Definition at line 211 of file ChartCreation.h.
MaxFlushAsyncLoadingTime
double FPerformanceTrackingChart::MaxFlushAsyncLoadingTime
Definition at line 179 of file ChartCreation.h.
MaxPhysicalMemory
uint64 FPerformanceTrackingChart::MaxPhysicalMemory
Definition at line 239 of file ChartCreation.h.
MaxPlayerTicks
int32 FPerformanceTrackingChart::MaxPlayerTicks
Total number of player ticks (note: it is up to the game to populate this field) WARNING: Legacy fields.
These should more properly be handled by deriving the class and providing game-specific data as necessary.
Definition at line 199 of file ChartCreation.h.
MaxVehicleTicks
int32 FPerformanceTrackingChart::MaxVehicleTicks
Total number of vehicle ticks (note: it is up to the game to populate this field) WARNING: Legacy field.
These should more properly be handled by deriving the class and providing game-specific data as necessary.
Definition at line 207 of file ChartCreation.h.
MaxVirtualMemory
uint64 FPerformanceTrackingChart::MaxVirtualMemory
Definition at line 240 of file ChartCreation.h.
MinAvailablePhysicalMemory
uint64 FPerformanceTrackingChart::MinAvailablePhysicalMemory
Definition at line 243 of file ChartCreation.h.
MinDrawCalls
int32 FPerformanceTrackingChart::MinDrawCalls
Definition at line 192 of file ChartCreation.h.
MinDrawnPrimitives
int32 FPerformanceTrackingChart::MinDrawnPrimitives
Definition at line 212 of file ChartCreation.h.
MinPhysicalMemory
uint64 FPerformanceTrackingChart::MinPhysicalMemory
Definition at line 241 of file ChartCreation.h.
MinPlayerTicks
int32 FPerformanceTrackingChart::MinPlayerTicks
Definition at line 200 of file ChartCreation.h.
MinVirtualMemory
uint64 FPerformanceTrackingChart::MinVirtualMemory
Definition at line 242 of file ChartCreation.h.
NumFramesAtCriticalMemoryPressure
uint32 FPerformanceTrackingChart::NumFramesAtCriticalMemoryPressure
Definition at line 238 of file ChartCreation.h.
NumFramesBound_GameThread
uint32 FPerformanceTrackingChart::NumFramesBound_GameThread
Number of frames for each time of <boundtype>
Definition at line 159 of file ChartCreation.h.
NumFramesBound_GPU
uint32 FPerformanceTrackingChart::NumFramesBound_GPU
Definition at line 162 of file ChartCreation.h.
NumFramesBound_RenderThread
uint32 FPerformanceTrackingChart::NumFramesBound_RenderThread
Definition at line 160 of file ChartCreation.h.
NumFramesBound_RHIThread
uint32 FPerformanceTrackingChart::NumFramesBound_RHIThread
Definition at line 161 of file ChartCreation.h.
StartBatteryLevel
int FPerformanceTrackingChart::StartBatteryLevel
Definition at line 229 of file ChartCreation.h.
StartTemperatureLevel
float FPerformanceTrackingChart::StartTemperatureLevel
Definition at line 226 of file ChartCreation.h.
StopBatteryLevel
int FPerformanceTrackingChart::StopBatteryLevel
Definition at line 230 of file ChartCreation.h.
StopTemperatureLevel
float FPerformanceTrackingChart::StopTemperatureLevel
Definition at line 227 of file ChartCreation.h.
TimeDisregarded
double FPerformanceTrackingChart::TimeDisregarded
Total time (sec) that were disregarded because the frame was too long.
This is probably a clock glitch or an app returning from background, suspend, etc, and can really skew the data.
Definition at line 222 of file ChartCreation.h.
TotalDrawCalls
int32 FPerformanceTrackingChart::TotalDrawCalls
Definition at line 193 of file ChartCreation.h.
TotalDrawnPrimitives
int64 FPerformanceTrackingChart::TotalDrawnPrimitives
Definition at line 213 of file ChartCreation.h.
TotalFlushAsyncLoadingCalls
int32 FPerformanceTrackingChart::TotalFlushAsyncLoadingCalls
Definition at line 178 of file ChartCreation.h.
TotalFlushAsyncLoadingTime
double FPerformanceTrackingChart::TotalFlushAsyncLoadingTime
Total time spent flushing async loading (in seconds), and call count.
Definition at line 177 of file ChartCreation.h.
TotalFramesBoundTime_GameThread
double FPerformanceTrackingChart::TotalFramesBoundTime_GameThread
Time spent bound on each kind of thing (in seconds)
Definition at line 165 of file ChartCreation.h.
TotalFramesBoundTime_GPU
double FPerformanceTrackingChart::TotalFramesBoundTime_GPU
Definition at line 168 of file ChartCreation.h.
TotalFramesBoundTime_RenderThread
double FPerformanceTrackingChart::TotalFramesBoundTime_RenderThread
Definition at line 166 of file ChartCreation.h.
TotalFramesBoundTime_RHIThread
double FPerformanceTrackingChart::TotalFramesBoundTime_RHIThread
Definition at line 167 of file ChartCreation.h.
TotalFrameTime_GameThread
double FPerformanceTrackingChart::TotalFrameTime_GameThread
Total time spent on each thread (in seconds)
Definition at line 171 of file ChartCreation.h.
TotalFrameTime_GPU
double FPerformanceTrackingChart::TotalFrameTime_GPU
Definition at line 174 of file ChartCreation.h.
TotalFrameTime_RenderThread
double FPerformanceTrackingChart::TotalFrameTime_RenderThread
Definition at line 172 of file ChartCreation.h.
TotalFrameTime_RHIThread
double FPerformanceTrackingChart::TotalFrameTime_RHIThread
Definition at line 173 of file ChartCreation.h.
TotalGameThreadBoundHitchCount
int32 FPerformanceTrackingChart::TotalGameThreadBoundHitchCount
Total number of hitches bound by each kind of thing.
Definition at line 185 of file ChartCreation.h.
TotalGPUBoundHitchCount
int32 FPerformanceTrackingChart::TotalGPUBoundHitchCount
Definition at line 188 of file ChartCreation.h.
TotalPhysicalMemoryUsed
uint64 FPerformanceTrackingChart::TotalPhysicalMemoryUsed
Definition at line 244 of file ChartCreation.h.
TotalPlayerTicks
int32 FPerformanceTrackingChart::TotalPlayerTicks
Definition at line 201 of file ChartCreation.h.
TotalRenderThreadBoundHitchCount
int32 FPerformanceTrackingChart::TotalRenderThreadBoundHitchCount
Definition at line 186 of file ChartCreation.h.
TotalRHIThreadBoundHitchCount
int32 FPerformanceTrackingChart::TotalRHIThreadBoundHitchCount
Definition at line 187 of file ChartCreation.h.
TotalSyncLoadCount
uint32 FPerformanceTrackingChart::TotalSyncLoadCount
Total number of sync loads.
Definition at line 182 of file ChartCreation.h.
TotalVehicleTicks
int32 FPerformanceTrackingChart::TotalVehicleTicks
Definition at line 208 of file ChartCreation.h.
TotalVirtualMemoryUsed
uint64 FPerformanceTrackingChart::TotalVirtualMemoryUsed
Definition at line 245 of file ChartCreation.h.
The documentation for this class was generated from the following file:
Runtime/Engine/Public/ChartCreation.h