Unreal Engine 5.6 C++ API: FLightInteraction Class Reference
FLightInteraction Class Reference
Information about an interaction between a light and a mesh.
#include "SceneManagement.h"
Public Member Functions
FLightInteraction (ELightInteractionType InType)
Minimal initialization constructor.
ELightInteractionType GetType () const
Static Public Member Functions
static FLightInteraction Dynamic ()
static FLightInteraction Irrelevant ()
static FLightInteraction LightMap ()
static FLightInteraction ShadowMap2D ()
Private Attributes
ELightInteractionType Type
Detailed Description
Information about an interaction between a light and a mesh.
Definition at line 341 of file SceneManagement.h.
Constructor & Destructor Documentation
FLightInteraction()
FLightInteraction::FLightInteraction (ELightInteractionType InType) inline
Minimal initialization constructor.
Definition at line 357 of file SceneManagement.h.
References Type.
Referenced by Dynamic(), Irrelevant(), LightMap(), and ShadowMap2D().
Member Function Documentation
Dynamic()
FLightInteraction FLightInteraction::Dynamic () inline static
Definition at line 346 of file SceneManagement.h.
References FLightInteraction(), and LIT_Dynamic.
GetType()
ELightInteractionType FLightInteraction::GetType () const inline
Definition at line 352 of file SceneManagement.h.
References Type.
Irrelevant()
FLightInteraction FLightInteraction::Irrelevant () inline static
Definition at line 348 of file SceneManagement.h.
References FLightInteraction(), and LIT_CachedIrrelevant.
LightMap()
FLightInteraction FLightInteraction::LightMap () inline static
Definition at line 347 of file SceneManagement.h.
References FLightInteraction(), and LIT_CachedLightMap.
ShadowMap2D()
FLightInteraction FLightInteraction::ShadowMap2D () inline static
Definition at line 349 of file SceneManagement.h.
References FLightInteraction(), and LIT_CachedSignedDistanceFieldShadowMap2D.
Field Documentation
Type
ELightInteractionType FLightInteraction::Type private
Definition at line 362 of file SceneManagement.h.
Referenced by FLightInteraction(), and GetType().
The documentation for this class was generated from the following file:
Runtime/Engine/Public/SceneManagement.h