Unreal Engine 5.6 C++ API: UE::Sequencer::FObjectBindingModel Class Reference
UE::Sequencer::FObjectBindingModel Class Reference
#include "ObjectBindingModel.h"
Data Structures
struct FPropertyMenuData
Public Member Functions
FObjectBindingModel (FSequenceModel *OwnerModel, const FMovieSceneBinding &InBinding)
~FObjectBindingModel ()
void AddTrack (UMovieSceneTrack *Track)
void BuildContextMenu (FMenuBuilder &MenuBuilder) override
Get context menu contents.
void BuildOrganizeContextMenu (FMenuBuilder &MenuBuilder) override
void BuildSidebarMenu (FMenuBuilder &MenuBuilder) override
bool CanDelete (FText *OutErrorMessage) const override
bool CanDrag () const override
Returns whether the model can be dragged.
bool CanRename () const override
TSharedPtr< SWidget > CreateOutlinerViewForColumn (const FCreateOutlinerViewParams &InParams, const FName &InColumnName) override
Create the visual outliner widget for the specified column.
void Delete () override
virtual const UClass * FindObjectClass () const
TSharedRef< SWidget > GetAddTrackMenuContent ()
bool GetDefaultExpansionState () const override
Get the default expansion state if it wasn't saved in the movie-scene data.
virtual FGuid GetDesiredParentBinding () const
const FSlateBrush * GetIconBrush () const override
Gets the icon for the outliner item.
void GetIdentifierForGrouping (TStringBuilder< 128 > &OutString) const override
virtual FSlateColor GetInvalidBindingLabelColor () const
FText GetLabel () const override
Gets the label for the outliner item.
FSlateColor GetLabelColor () const override
Gets the color for the outliner item label.
FText GetLabelToolTipText () const override
Gets the tooltip text for the outliner item.
FGuid GetObjectGuid () const override
FOutlinerSizing GetOutlinerSizing () const override
Return the desired size for the owning model.
FSortingKey GetSortingKey () const override
Called by the part to sort this model among its siblings.
virtual FText GetTooltipForSingleObjectBinding () const
FViewModelVariantIterator GetTopLevelChildTrackAreaModels () const override
FViewModelVariantIterator GetTrackAreaModelList () const override
FTrackAreaParameters GetTrackAreaParameters () const override
virtual EObjectBindingType GetType () const
void RemoveTrack (UMovieSceneTrack *Track)
void Rename (const FText &NewName) override
void SetCustomOrder (int32 InCustomOrder) override
Set a custom sort index for this view model.
virtual void SetParentBindingID (const FGuid &InObjectBindingID)
void SortChildren () override
Called when the model should sort its immediate children.
virtual bool SupportsRebinding () const
UE_SEQUENCER_DECLARE_CASTABLE (FObjectBindingModel, FEvaluableOutlinerItemModel, IObjectBindingExtension, IDraggableOutlinerExtension, ITrackAreaExtension, IGroupableExtension, IRenameableExtension, ISortableExtension, IDeletableExtension)
Public Member Functions inherited from UE::Sequencer::FEvaluableOutlinerItemModel
virtual bool IsDeactivated () const override
Returns whether this item is deactivated.
bool IsMuted () const override
Returns whether this item is muted.
bool IsSolo () const override
Returns whether this item is solo.
virtual void SetIsDeactivated (const bool bInIsDeactivated) override
Set this item's deactivated state.
void SetIsMuted (bool bIsMuted) override
Set this item's mute state.
void SetIsSoloed (bool bIsSoloed) override
Enable or disable solo for this object.
UE_SEQUENCER_DECLARE_CASTABLE (FEvaluableOutlinerItemModel, FOutlinerItemModel, IMutableExtension, ISoloableExtension, IDeactivatableExtension)
Public Member Functions inherited from UE::Sequencer::FOutlinerItemModel
UE_SEQUENCER_DECLARE_CASTABLE (FOutlinerItemModel, FViewModel, FOutlinerItemModelMixin)
Public Member Functions inherited from UE::Sequencer::TOutlinerModelMixin< FViewModel >
TOutlinerModelMixin (ArgTypes &&... InArgs)
virtual FViewModel * AsViewModel ()
TOutlinerModelMixin< FViewModel > operator= (const TOutlinerModelMixin< FViewModel > &)=delete
Public Member Functions inherited from UE::Sequencer::FViewModel
FViewModel ()
Builds a new data model.
FViewModel (const FViewModel &)=delete
virtual ~FViewModel ()
template<typename T, typename... InArgTypes>
T & AddDynamicExtension (const TViewModelTypeID< T > &TypeID, InArgTypes &&... Args)
Adds a dynamic extension to this data model.
template<typename T, typename... InArgTypes>
T & AddDynamicExtension (InArgTypes &&... Args)
Adds a dynamic extension to this data model.
template<typename T>
TViewModelPtr< T > CastParent () const
Gets the parent data model.
template<typename T>
TViewModelPtr< T > CastThisShared ()
Casts this data model to an extension, or to a child class implementation.
template<typename T>
TViewModelPtr< const T > CastThisShared () const
Casts this data model to an extension, or to a child class implementation.
template<typename T>
TSharedPtr< T > CastThisSharedChecked ()
Casts this data model to an extension, or to a child class implementation.
template<typename T>
TSharedPtr< const T > CastThisSharedChecked () const
Casts this data model to an extension, or to a child class implementation.
void DiscardAllChildren ()
Unlinks the head of the children list.
template<typename T>
TViewModelPtr< T > FindAncestorOfType (bool bIncludeThis=false) const
Finds the first ancestor view model that implements the given type.
FViewModelPtr FindAncestorOfType (FViewModelTypeID Type, bool bIncludeThis=false) const
Finds a parent data model of a given type among the ancestry of this data model.
FViewModelPtr FindAncestorOfTypes (TArrayView< const FViewModelTypeID > Types, bool bIncludeThis=false) const
Finds a parent data model that supports all the given interface types among the ancestry of this data model.
TOptional< FViewModelChildren > FindChildList (EViewModelListType InType)
Retrieve the first child list that matches the specified type (if any)
FParentModelIterator GetAncestors (bool bIncludeThis=false) const
Iterates over the ancestry of this data model.
template<typename T>
TParentModelIterator< T > GetAncestorsOfType (bool bIncludeThis=false) const
Iterates over all ancestors of a given time along the ancestry of this data model.
FViewModelChildren GetChildList (EViewModelListType InType)
Retrieve the first child list that matches the specified type.
FViewModelListIterator GetChildren (EViewModelListType InFilter=EViewModelListType::Everything) const
Gets an iterator for the data model's default children list.
template<typename T>
TViewModelListIterator< T > GetChildrenOfType (EViewModelListType InFilter=EViewModelListType::Everything) const
Gets children of a given type from the view-model's children lists, or the specified list.
FParentFirstChildIterator GetDescendants (bool bIncludeThis=false, EViewModelListType InFilter=EViewModelListType::Everything) const
Gets all children and their descendants in the hierarchy below this data model.
template<typename T>
TParentFirstChildIterator< T > GetDescendantsOfType (bool bIncludeThis=false, EViewModelListType InFilter=EViewModelListType::Everything) const
Gets all children and descendants of a given type in the hierarchy below this data model.
void GetDescendantsOfType (FViewModelTypeID Type, TArray< TSharedPtr< FViewModel > > &OutChildren, EViewModelListType InFilter=EViewModelListType::Everything) const
Gets all children and descendants of a given type in the hierarchy below this data model.
int32 GetHierarchicalDepth () const
Gets the hierarchical depth of this data model, i.e.
uint32 GetModelID () const
Get this model's unique, non-persistent and non-deterministic ID.
TSharedPtr< FViewModel > GetNextSibling () const
Gets the next sibling of this data model in the children list it belongs to.
FViewModelPtr GetParent () const
Gets the parent data model.
TSharedPtr< FViewModel > GetPreviousSibling () const
Gets the next sibling of this data model in the children list it belongs to.
FViewModelPtr GetRoot () const
Returns the root model of the hierarchy, i.e.
TSharedPtr< FSharedViewModelData > GetSharedData () const
bool HasChildren () const
Returns whether this model has any children in any of its child lists.
bool IsConstructed () const
FViewModel & operator= (const FViewModel &)=delete
void RemoveFromParent ()
Remove this model from its parent.
void SetSharedData (TSharedPtr< FSharedViewModelData > InSharedData)
UE_SEQUENCER_DECLARE_CASTABLE (FViewModel, FDynamicExtensionContainer)
Public Member Functions inherited from UE::Sequencer::ICastable
template<typename RetType, typename InterfaceType, typename ... ArgTypes, typename ... ParamTypes>
RetType CastedCall (RetType(InterfaceType::*MemberFunc)(ArgTypes...), ParamTypes &&... InArgs)
template<typename RetType, typename InterfaceType, typename ... ArgTypes, typename ... ParamTypes>
RetType CastedCall (RetType(InterfaceType::*MemberFunc)(ArgTypes...), ParamTypes &&... InArgs) const
void * CastRaw (FViewModelTypeID InType)
const void * CastRaw (FViewModelTypeID InType) const
template<typename T>
T * CastThis ()
template<typename T>
const T * CastThis () const
template<typename T>
T * CastThisChecked ()
template<typename T>
const T * CastThisChecked () const
const FCastableTypeTable & GetTypeTable () const
template<typename T>
bool IsA () const
bool IsA (FViewModelTypeID InType) const
Public Member Functions inherited from TSharedFromThis< FViewModel >
TSharedRef< FViewModel, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FViewModel, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Public Member Functions inherited from UE::Sequencer::FDynamicExtensionContainer
FDynamicExtensionContainer ()=default
FDynamicExtensionContainer (const FDynamicExtensionContainer &)=delete
virtual ~FDynamicExtensionContainer ()
template<typename T>
T * CastDynamic ()
void * CastDynamic (FViewModelTypeID Type)
SEQUENCERCORE_API const void * CastDynamic (FViewModelTypeID Type) const
template<typename T>
T * CastDynamicChecked ()
template<typename T>
const T * CastDynamicChecked () const
void * CastDynamicChecked (FViewModelTypeID Type)
const void * CastDynamicChecked (FViewModelTypeID Type) const
template<typename T>
TDynamicExtensionContainerIteratorProxy< T > FilterDynamic ()
FDynamicExtensionContainer & operator= (const FDynamicExtensionContainer &)=delete
SEQUENCERCORE_API void RemoveDynamicExtension (FViewModelTypeID Type)
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID_API (SEQUENCERCORE_API, FDynamicExtensionContainer) template< typename T > const T *CastDynamic() const
Public Member Functions inherited from UE::Sequencer::FOutlinerItemModelMixin
FOutlinerItemModelMixin ()
TSharedPtr< SWidget > CreateContextMenuWidget (const FCreateOutlinerContextMenuWidgetParams &InParams) override
Build the context menu widget for this outliner item.
virtual void CreateCurveModels (TArray< TUniquePtr< FCurveModel > > &OutCurveModels) override
Populate the specified array with curve models that are represented by this tree item.
virtual TSharedPtr< SWidget > GenerateCurveEditorTreeWidget (const FName &InColumnName, TWeakPtr< FCurveEditor > InCurveEditor, FCurveEditorTreeItemID InTreeItemID, const TSharedRef< ITableRow > &InTableRow) override
Generate the widget content for the specified column name of the curve editor tree view.
virtual TSharedPtr< ICurveEditorTreeItem > GetCurveEditorTreeItem () const override
Gets the curve editor item for this view-model.
TSharedPtr< FSequencerEditorViewModel > GetEditor () const
FName GetIdentifier () const override
Return the identifier of the owning model.
FSlateColor GetLabelColor () const override
Gets the color for the outliner item label.
virtual TOptional< FString > GetUniquePathName () const override
Get optional unique path name.
virtual bool HasCurves () const override
Whether this view-model has any curves and needs to have a curve editor item created.
bool IsDimmed () const override
bool IsExpanded () const override
Gets whether this outliner item is expanded.
bool IsFilteredOut () const override
Gets whether this outliner item has been filtered out.
bool IsPinned () const override
Returns whether this item is pinned, or is in a pinned branch.
virtual bool PassesFilter (const FCurveEditorTreeFilter *InFilter) const override
Check whether this tree item passes the specified filter.
void SetExpansion (bool bInIsExpanded) override
Sets the expansion state of this outliner item.
Public Member Functions inherited from UE::Sequencer::FOutlinerExtensionShim
virtual EOutlinerSelectionState GetSelectionState () const override
Gets the outliner item's selection state.
virtual void SetFilteredOut (bool bInIsFilteredOut) override
Sets whether this outliner item is being filtered out.
virtual void SetSelectionState (EOutlinerSelectionState InState) override
Sets the outliner item's selection state.
virtual bool ShouldAnchorToTop () const override
Public Member Functions inherited from UE::Sequencer::IOutlinerExtension
virtual TSharedRef< SWidget > CreateOutlinerView (const FCreateOutlinerViewParams &InParams)
(deprecated) Create the outliner view for the label column
virtual const FSlateBrush * GetIconOverlayBrush () const
Gets the overlay icon for the outliner item.
virtual FSlateColor GetIconTint () const
Gets the icon tint color for the outliner item.
virtual FText GetIconToolTipText () const
Gets the tooltip text for the outliner item icon.
virtual FSlateFontInfo GetLabelFont () const
Gets the font for the outliner item.
virtual bool HasBackground () const
Gets whether the outliner item has a background.
virtual void ToggleSelectionState (EOutlinerSelectionState InState, bool bInValue)
Toggles a bit in the outliner item's selection state.
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID (IOutlinerExtension) virtual ~IOutlinerExtension()
Public Member Functions inherited from UE::Sequencer::FGeometryExtensionShim
FVirtualGeometry GetVirtualGeometry () const override
void ReportVirtualGeometry (const FVirtualGeometry &InVirtualGeometry) override
Public Member Functions inherited from UE::Sequencer::IGeometryExtension
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID (IGeometryExtension) virtual ~IGeometryExtension()
Public Member Functions inherited from UE::Sequencer::FPinnableExtensionShim
virtual void ReportPinnedParent (bool bInIsInPinnedBranch) override
Lets parent items report to their children that they are in a pinned branch.
virtual void SetPinned (bool bInIsPinned) override
Sets whether this item is pinned.
Public Member Functions inherited from UE::Sequencer::IPinnableExtension
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID (IPinnableExtension) virtual ~IPinnableExtension()
Public Member Functions inherited from UE::Sequencer::FHoveredExtensionShim
virtual bool IsHovered () const
virtual void OnHovered ()
virtual void OnUnhovered ()
Public Member Functions inherited from UE::Sequencer::IHoveredExtension
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID (IHoveredExtension) virtual ~IHoveredExtension()
Public Member Functions inherited from UE::Sequencer::IDimmableExtension
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID (IDimmableExtension) virtual ~IDimmableExtension()
Public Member Functions inherited from UE::Sequencer::FCurveEditorTreeItemExtensionShim
FCurveEditorTreeItemID GetCurveEditorItemID () const override
Gets the curve editor ID for this view-model.
void OnAddedToCurveEditor (FCurveEditorTreeItemID ItemID, TSharedPtr< FCurveEditor > CurveEditor)
Called when this view-model has a curve editor item created for it.
void OnRemovedFromCurveEditor (TSharedPtr< FCurveEditor > CurveEditor)
Called when this view-model's curve editor item is removed.
Public Member Functions inherited from UE::Sequencer::ICurveEditorTreeItemExtension
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID (ICurveEditorTreeItemExtension) virtual ~ICurveEditorTreeItemExtension()
Public Member Functions inherited from ICurveEditorTreeItem
virtual ~ICurveEditorTreeItem ()
Public Member Functions inherited from UE::Sequencer::IMutableExtension
virtual bool IsInheritable () const
Returns whether this mutable can be muted by a parent, and should report its mute state to a parent.
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID (IMutableExtension) virtual ~IMutableExtension()
Public Member Functions inherited from UE::Sequencer::ISoloableExtension
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID (ISoloableExtension) virtual ~ISoloableExtension()
Public Member Functions inherited from UE::Sequencer::IDeactivatableExtension
virtual ~IDeactivatableExtension ()
virtual bool IsInheritable () const
Returns whether this deactivatable can be deactivated by a parent, and should report its deactivated state to a parent.
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID (IDeactivatableExtension)
Public Member Functions inherited from UE::Sequencer::IObjectBindingExtension
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID (IObjectBindingExtension) virtual ~IObjectBindingExtension()
Public Member Functions inherited from UE::Sequencer::IDraggableOutlinerExtension
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID (IDraggableOutlinerExtension) virtual ~IDraggableOutlinerExtension()
Public Member Functions inherited from UE::Sequencer::ITrackAreaExtension
template<typename T>
TTypedIterator< T, FViewModelVariantIterator > GetTrackAreaModelListAs () const
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID (ITrackAreaExtension) virtual ~ITrackAreaExtension()
Public Member Functions inherited from UE::Sequencer::IGroupableExtension
FString GetIdentifierForGrouping () const
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID (IGroupableExtension) virtual ~IGroupableExtension()
Public Member Functions inherited from UE::Sequencer::IRenameableExtension
bool IsRenameValid (const FText &NewName, FText &OutErrorMessage) const
FSimpleMulticastDelegate & OnRenameRequested ()
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID (IRenameableExtension) virtual ~IRenameableExtension()
Public Member Functions inherited from UE::Sequencer::ISortableExtension
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID (ISortableExtension) virtual ~ISortableExtension()
Public Member Functions inherited from UE::Sequencer::IDeletableExtension
UE_SEQUENCER_DECLARE_VIEW_MODEL_TYPE_ID (IDeletableExtension) virtual ~IDeletableExtension()
Static Public Member Functions
static EViewModelListType GetTopLevelChildTrackAreaGroupType ()
Static Public Member Functions inherited from UE::Sequencer::ICastable
template<typename T>
static T * CastWeakPtr (const TWeakPtr< ICastable > &InWeakPtr)
template<typename T>
static TSharedPtr< T > CastWeakPtrShared (const TWeakPtr< ICastable > &InWeakPtr)
Static Public Member Functions inherited from UE::Sequencer::IOutlinerExtension
static FString GetPathName (const FViewModel &Item)
Utility method to get the full path name of the given model.
static void GetPathName (const FViewModel &Item, FStringBuilderBase &OutString)
Utility method to get the full path name of the given model.
static FString GetPathName (const TSharedPtr< const FViewModel > Item)
Utility method to get the full path name of the given model.
static FString GetPathName (const TSharedPtr< FViewModel > Item)
Utility method to get the full path name of the given model.
static FString GetPathName (const TWeakPtr< const FViewModel > Item)
Utility method to get the full path name of the given model.
Static Public Member Functions inherited from UE::Sequencer::IGeometryExtension
static float UpdateVirtualGeometry (float InitialVirtualPosition, TSharedPtr< FViewModel > InInitialItem)
Static Public Member Functions inherited from UE::Sequencer::FPinnableExtensionShim
static void UpdateCachedPinnedState (TSharedPtr< FViewModel > RootModel)
Looks for any direct child of RootModel that is pinnable, and reports all their descendants that they are in a pinned branch, to make that lookup faster.
Static Public Member Functions inherited from UE::Sequencer::ISortableExtension
static void SortChildren (FViewModelChildren &Children, ESortingMode SortingMode)
Utility function for sorting children based on their sorting key.
static void SortChildren (TSharedPtr< FViewModel > ParentModel, ESortingMode SortingMode)
Utility function for sorting children based on their sorting key.
Protected Member Functions
void OnConstruct () override
Called once for this model when it is added to a parent that has valid shared data.
Protected Member Functions inherited from UE::Sequencer::FViewModel
FViewModelChildren GetChildrenForList (FViewModelListHead *ListHead)
Retrieve the children for the specified child list head.
void RegisterChildList (FViewModelListHead *InChildren)
Chain a new children list to the existing children lists.
void SetSharedDataFromConstructor (TSharedPtr< FSharedViewModelData > InSharedData)
Protected Member Functions inherited from TSharedFromThis< FViewModel >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Protected Member Functions inherited from UE::Sequencer::FDynamicExtensionContainer
template<typename T, typename... InArgTypes>
T & AddDynamicExtension (TSharedRef< FViewModel > InOwner, InArgTypes &&... Args)
void PostInitializeExtensions ()
void ReinitializeExtensions ()
template<typename T>
void RemoveDynamicExtension ()
Protected Member Functions inherited from UE::Sequencer::FOutlinerItemModelMixin
virtual void BuildDisplayOptionsMenu (FMenuBuilder &MenuBuilder)
virtual void BuildSectionColorTintsMenu (FMenuBuilder &MenuBuilder)
virtual void BuildTrackOptionsMenu (FMenuBuilder &MenuBuilder, const TArray< UMovieSceneTrack * > &InTracks)
virtual void BuildTrackRowOptionsMenu (FMenuBuilder &MenuBuilder)
void SetExpansionWithoutSaving (bool bInIsExpanded)
Set expansion state without saving it in the movie-scene data.
void SetIdentifier (FName InNewIdentifier)
Set identifier for computing node paths.
Protected Attributes
TSharedPtr< FBindingLifetimeOverlayModel > BindingLifetimeOverlayModel
TSharedPtr< FLayerBarModel > LayerBar
FGuid ObjectBindingID
FSequenceModel * OwnerModel
FGuid ParentObjectBindingID
FViewModelListHead TopLevelChildTrackAreaList
FViewModelListHead TrackAreaList
Protected Attributes inherited from UE::Sequencer::ICastable
FDynamicExtensionContainer * DynamicTypes = nullptr
Protected Attributes inherited from UE::Sequencer::FOutlinerItemModelMixin
FViewModelListHead OutlinerChildList
Protected Attributes inherited from UE::Sequencer::FOutlinerExtensionShim
bool bIsExpanded = false
bool bIsFilteredOut = false
EOutlinerSelectionState SelectionState = EOutlinerSelectionState::None
Protected Attributes inherited from UE::Sequencer::FGeometryExtensionShim
FVirtualGeometry VirtualGeometry
Protected Attributes inherited from UE::Sequencer::FHoveredExtensionShim
bool bIsHovered = false
Private Member Functions
void AddPropertyMenuItem (FMenuBuilder &AddTrackMenuBuilder, const FPropertyMenuData &KeyablePropertyMenuData)
void AddPropertyMenuItems (FMenuBuilder &AddTrackMenuBuilder, int32 NumStartingBlocks, TArray< FPropertyPath > KeyablePropertyPaths, int32 PropertyNameIndexStart)
void AddTagMenu (FMenuBuilder &MenuBuilder)
ECheckBoxState GetTagCheckState (FName TagName)
void HandleAddTag (FName TagName)
void HandleAddTrackSubMenuNew (FMenuBuilder &AddTrackMenuBuilder, TArray< FPropertyPath > KeyablePropertyPaths, int32 PropertyNameIndexStart)
void HandleDeleteTag (FName TagName)
void HandlePropertyMenuItemExecute (FPropertyPath PropertyPath)
void HandleTemplateActorClassPicked (UClass *ChosenClass)
void OnFinishedChangingDynamicBindingProperties (const FPropertyChangedEvent &ChangeEvent, TSharedPtr< FStructOnScope > ValueStruct)
void ToggleTag (FName TagName)
Additional Inherited Members
Public Types inherited from UE::Sequencer::FOutlinerItemModelMixin
using Implements = TImplements<IOutlinerExtension, IGeometryExtension, IPinnableExtension, IHoveredExtension, IDimmableExtension, ICurveEditorTreeItemExtension>
Static Public Attributes inherited from ICurveEditorTreeItem
static const FColumnNames ColumnNames
Static Protected Member Functions inherited from TSharedFromThis< FViewModel >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
Definition at line 43 of file ObjectBindingModel.h.
Constructor & Destructor Documentation
FObjectBindingModel()
UE::Sequencer::FObjectBindingModel::FObjectBindingModel (FSequenceModel * OwnerModel, const FMovieSceneBinding & InBinding)
References OwnerModel.
Referenced by UE_SEQUENCER_DECLARE_CASTABLE(), UE::Sequencer::FPossessableModel::UE_SEQUENCER_DECLARE_CASTABLE(), and UE::Sequencer::FSpawnableModel::UE_SEQUENCER_DECLARE_CASTABLE().
~FObjectBindingModel()
UE::Sequencer::FObjectBindingModel::~FObjectBindingModel ()
Member Function Documentation
AddPropertyMenuItem()
void UE::Sequencer::FObjectBindingModel::AddPropertyMenuItem (FMenuBuilder & AddTrackMenuBuilder, const FPropertyMenuData & KeyablePropertyMenuData) private
AddPropertyMenuItems()
void UE::Sequencer::FObjectBindingModel::AddPropertyMenuItems (FMenuBuilder & AddTrackMenuBuilder, int32 NumStartingBlocks, TArray< FPropertyPath > KeyablePropertyPaths, int32 PropertyNameIndexStart) private
AddTagMenu()
void UE::Sequencer::FObjectBindingModel::AddTagMenu (FMenuBuilder & MenuBuilder) private
AddTrack()
void UE::Sequencer::FObjectBindingModel::AddTrack (UMovieSceneTrack * Track)
BuildContextMenu()
void UE::Sequencer::FObjectBindingModel::BuildContextMenu (FMenuBuilder & MenuBuilder) override virtual
Get context menu contents.
Reimplemented from UE::Sequencer::FOutlinerItemModelMixin.
BuildOrganizeContextMenu()
void UE::Sequencer::FObjectBindingModel::BuildOrganizeContextMenu (FMenuBuilder & MenuBuilder) override virtual
Reimplemented from UE::Sequencer::FOutlinerItemModelMixin.
BuildSidebarMenu()
void UE::Sequencer::FObjectBindingModel::BuildSidebarMenu (FMenuBuilder & MenuBuilder) override virtual
Reimplemented from UE::Sequencer::FOutlinerItemModelMixin.
CanDelete()
bool UE::Sequencer::FObjectBindingModel::CanDelete (FText * OutErrorMessage) const override virtual
Implements UE::Sequencer::IDeletableExtension.
CanDrag()
bool UE::Sequencer::FObjectBindingModel::CanDrag () const override virtual
Returns whether the model can be dragged.
Implements UE::Sequencer::IDraggableOutlinerExtension.
CanRename()
bool UE::Sequencer::FObjectBindingModel::CanRename () const override virtual
Implements UE::Sequencer::IRenameableExtension.
CreateOutlinerViewForColumn()
TSharedPtr< SWidget > UE::Sequencer::FObjectBindingModel::CreateOutlinerViewForColumn (const FCreateOutlinerViewParams & InParams, const FName & InColumnName) override virtual
Create the visual outliner widget for the specified column.
Reimplemented from UE::Sequencer::IOutlinerExtension.
Delete()
void UE::Sequencer::FObjectBindingModel::Delete () override virtual
Implements UE::Sequencer::IDeletableExtension.
Reimplemented in UE::Sequencer::FPossessableModel, and UE::Sequencer::FSpawnableModel.
FindObjectClass()
virtual const UClass * UE::Sequencer::FObjectBindingModel::FindObjectClass () const virtual
Reimplemented in UE::Sequencer::FPossessableModel, and UE::Sequencer::FSpawnableModel.
GetAddTrackMenuContent()
TSharedRef< SWidget > UE::Sequencer::FObjectBindingModel::GetAddTrackMenuContent ()
GetDefaultExpansionState()
bool UE::Sequencer::FObjectBindingModel::GetDefaultExpansionState () const override virtual
Get the default expansion state if it wasn't saved in the movie-scene data.
Reimplemented from UE::Sequencer::FOutlinerItemModelMixin.
GetDesiredParentBinding()
virtual FGuid UE::Sequencer::FObjectBindingModel::GetDesiredParentBinding () const virtual
GetIconBrush()
const FSlateBrush * UE::Sequencer::FObjectBindingModel::GetIconBrush () const override virtual
Gets the icon for the outliner item.
Reimplemented from UE::Sequencer::IOutlinerExtension.
GetIdentifierForGrouping()
void UE::Sequencer::FObjectBindingModel::GetIdentifierForGrouping (TStringBuilder< 128 > & OutString) const override virtual
Implements UE::Sequencer::IGroupableExtension.
GetInvalidBindingLabelColor()
virtual FSlateColor UE::Sequencer::FObjectBindingModel::GetInvalidBindingLabelColor () const inline virtual
Reimplemented in UE::Sequencer::FPossessableModel, and UE::Sequencer::FSpawnableModel.
Definition at line 122 of file ObjectBindingModel.h.
References FLinearColor::Red.
GetLabel()
FText UE::Sequencer::FObjectBindingModel::GetLabel () const override virtual
Gets the label for the outliner item.
Reimplemented from UE::Sequencer::IOutlinerExtension.
GetLabelColor()
FSlateColor UE::Sequencer::FObjectBindingModel::GetLabelColor () const override virtual
Gets the color for the outliner item label.
Reimplemented from UE::Sequencer::IOutlinerExtension.
GetLabelToolTipText()
FText UE::Sequencer::FObjectBindingModel::GetLabelToolTipText () const override virtual
Gets the tooltip text for the outliner item.
Reimplemented from UE::Sequencer::IOutlinerExtension.
GetObjectGuid()
FGuid UE::Sequencer::FObjectBindingModel::GetObjectGuid () const override virtual
Implements UE::Sequencer::IObjectBindingExtension.
GetOutlinerSizing()
FOutlinerSizing UE::Sequencer::FObjectBindingModel::GetOutlinerSizing () const override virtual
Return the desired size for the owning model.
Implements UE::Sequencer::IOutlinerExtension.
GetSortingKey()
FSortingKey UE::Sequencer::FObjectBindingModel::GetSortingKey () const override virtual
Called by the part to sort this model among its siblings.
Implements UE::Sequencer::ISortableExtension.
GetTagCheckState()
ECheckBoxState UE::Sequencer::FObjectBindingModel::GetTagCheckState (FName TagName) private
GetTooltipForSingleObjectBinding()
virtual FText UE::Sequencer::FObjectBindingModel::GetTooltipForSingleObjectBinding () const virtual
Reimplemented in UE::Sequencer::FSpawnableModel.
GetTopLevelChildTrackAreaGroupType()
EViewModelListType UE::Sequencer::FObjectBindingModel::GetTopLevelChildTrackAreaGroupType () static
GetTopLevelChildTrackAreaModels()
FViewModelVariantIterator UE::Sequencer::FObjectBindingModel::GetTopLevelChildTrackAreaModels () const override virtual
Reimplemented from UE::Sequencer::ITrackAreaExtension.
GetTrackAreaModelList()
FViewModelVariantIterator UE::Sequencer::FObjectBindingModel::GetTrackAreaModelList () const override virtual
Implements UE::Sequencer::ITrackAreaExtension.
GetTrackAreaParameters()
FTrackAreaParameters UE::Sequencer::FObjectBindingModel::GetTrackAreaParameters () const override virtual
Implements UE::Sequencer::ITrackAreaExtension.
GetType()
virtual EObjectBindingType UE::Sequencer::FObjectBindingModel::GetType () const virtual
Reimplemented in UE::Sequencer::FPossessableModel, and UE::Sequencer::FSpawnableModel.
HandleAddTag()
void UE::Sequencer::FObjectBindingModel::HandleAddTag (FName TagName) private
HandleAddTrackSubMenuNew()
void UE::Sequencer::FObjectBindingModel::HandleAddTrackSubMenuNew (FMenuBuilder & AddTrackMenuBuilder, TArray< FPropertyPath > KeyablePropertyPaths, int32 PropertyNameIndexStart) private
HandleDeleteTag()
void UE::Sequencer::FObjectBindingModel::HandleDeleteTag (FName TagName) private
HandlePropertyMenuItemExecute()
void UE::Sequencer::FObjectBindingModel::HandlePropertyMenuItemExecute (FPropertyPath PropertyPath) private
HandleTemplateActorClassPicked()
void UE::Sequencer::FObjectBindingModel::HandleTemplateActorClassPicked (UClass * ChosenClass) private
OnConstruct()
void UE::Sequencer::FObjectBindingModel::OnConstruct () override protected virtual
Called once for this model when it is added to a parent that has valid shared data.
Reimplemented from UE::Sequencer::FViewModel.
Reimplemented in UE::Sequencer::FPossessableModel, and UE::Sequencer::FSpawnableModel.
OnFinishedChangingDynamicBindingProperties()
void UE::Sequencer::FObjectBindingModel::OnFinishedChangingDynamicBindingProperties (const FPropertyChangedEvent & ChangeEvent, TSharedPtr< FStructOnScope > ValueStruct) private
RemoveTrack()
void UE::Sequencer::FObjectBindingModel::RemoveTrack (UMovieSceneTrack * Track)
Rename()
void UE::Sequencer::FObjectBindingModel::Rename (const FText & NewName) override virtual
Implements UE::Sequencer::IRenameableExtension.
SetCustomOrder()
void UE::Sequencer::FObjectBindingModel::SetCustomOrder (int32 InCustomOrder) override virtual
Set a custom sort index for this view model.
Implements UE::Sequencer::ISortableExtension.
SetParentBindingID()
virtual void UE::Sequencer::FObjectBindingModel::SetParentBindingID (const FGuid & InObjectBindingID) virtual
SortChildren()
void UE::Sequencer::FObjectBindingModel::SortChildren () override virtual
Called when the model should sort its immediate children.
Implements UE::Sequencer::ISortableExtension.
SupportsRebinding()
virtual bool UE::Sequencer::FObjectBindingModel::SupportsRebinding () const virtual
Reimplemented in UE::Sequencer::FPossessableModel.
ToggleTag()
void UE::Sequencer::FObjectBindingModel::ToggleTag (FName TagName) private
UE_SEQUENCER_DECLARE_CASTABLE()
UE::Sequencer::FObjectBindingModel::UE_SEQUENCER_DECLARE_CASTABLE (FObjectBindingModel , FEvaluableOutlinerItemModel , IObjectBindingExtension , IDraggableOutlinerExtension , ITrackAreaExtension , IGroupableExtension , IRenameableExtension , ISortableExtension , IDeletableExtension)
References FObjectBindingModel().
Field Documentation
BindingLifetimeOverlayModel
TSharedPtr<FBindingLifetimeOverlayModel> UE::Sequencer::FObjectBindingModel::BindingLifetimeOverlayModel protected
Definition at line 168 of file ObjectBindingModel.h.
LayerBar
TSharedPtr<FLayerBarModel> UE::Sequencer::FObjectBindingModel::LayerBar protected
Definition at line 167 of file ObjectBindingModel.h.
ObjectBindingID
FGuid UE::Sequencer::FObjectBindingModel::ObjectBindingID protected
Definition at line 163 of file ObjectBindingModel.h.
OwnerModel
FSequenceModel* UE::Sequencer::FObjectBindingModel::OwnerModel protected
Definition at line 169 of file ObjectBindingModel.h.
Referenced by FObjectBindingModel(), and UE::Sequencer::FPossessableModel::FPossessableModel().
ParentObjectBindingID
FGuid UE::Sequencer::FObjectBindingModel::ParentObjectBindingID protected
Definition at line 164 of file ObjectBindingModel.h.
TopLevelChildTrackAreaList
FViewModelListHead UE::Sequencer::FObjectBindingModel::TopLevelChildTrackAreaList protected
Definition at line 166 of file ObjectBindingModel.h.
TrackAreaList
FViewModelListHead UE::Sequencer::FObjectBindingModel::TrackAreaList protected
Definition at line 165 of file ObjectBindingModel.h.
The documentation for this class was generated from the following file:
Editor/Sequencer/Public/MVVM/ViewModels/ObjectBindingModel.h