Unreal Engine 5.6 C++ API: FShaderMapBase Class Reference
FShaderMapBase Class Reference abstract
#include "Shader.h"
Public Member Functions
virtual RENDERCORE_API ~FShaderMapBase ()
RENDERCORE_API void AssignContent (TMemoryImageObject< FShaderMapContent > InContent)
void AssociateWithAsset (const FName &AssetPath)
Associates a shadermap with an asset (note: one shadermap can be used by several assets, e.g.
void AssociateWithAssets (const FShaderMapAssetPaths &AssetPaths)
virtual void DumpShaderList (FShaderListReport &Out) const
RENDERCORE_API void FinalizeContent ()
const FShaderMapAssetPaths & GetAssociatedAssets () const
const FShaderMapContent * GetContent () const
uint32 GetFrozenContentSize () const
FShaderMapContent * GetMutableContent ()
void GetOutdatedTypes (TArray< const FShaderType * > &OutdatedShaderTypes, TArray< const FShaderPipelineType * > &OutdatedShaderPipelineTypes, TArray< const FVertexFactoryType * > &OutdatedFactoryTypes) const
EShaderPermutationFlags GetPermutationFlags () const
const FShaderMapPointerTable & GetPointerTable () const
FShaderMapResource * GetResource () const
FShaderMapResource * GetResourceChecked () const
RENDERCORE_API FShaderMapResourceCode * GetResourceCode ()
virtual void GetShaderList (TMap< FHashedName, TShaderRef< FShader > > &OutShaders) const =0
Builds a list of the shaders in a shader map.
virtual void GetShaderPipelineList (TArray< FShaderPipelineRef > &OutShaderPipelines) const =0
EShaderPlatform GetShaderPlatform () const
void SaveShaderStableKeys (EShaderPlatform TargetShaderPlatform, const struct FStableShaderKeyAndValue &SaveKeyVal)
RENDERCORE_API bool Serialize (FArchive &Ar, bool bInlineShaderResources, bool bLoadingCooked, bool bInlineShaderCode=false, const FName &SerializingAsset=NAME_None)
RENDERCORE_API bool Serialize (FShaderSerializeContext &Ctx)
RENDERCORE_API FString ToString () const
RENDERCORE_API void UnfreezeContent ()
Protected Member Functions
RENDERCORE_API FShaderMapBase ()
RENDERCORE_API void AssignCopy (const FShaderMapBase &Source)
virtual FShaderMapPointerTable * CreatePointerTable () const =0
RENDERCORE_API void DestroyContent ()
virtual const FTypeLayoutDesc & GetContentTypeDesc () const =0
RENDERCORE_API void InitResource ()
virtual void PostFinalizeContent ()
Private Attributes
FShaderMapAssetPaths AssociatedAssets
List of the assets that are using this shadermap.
TRefCountPtr< FShaderMapResourceCode > Code
TMemoryImageObject< FShaderMapContent > Content
uint32 NumFrozenShaders
EShaderPermutationFlags PermutationFlags
FShaderMapPointerTable * PointerTable
TRefCountPtr< FShaderMapResource > Resource
Detailed Description
Definition at line 2512 of file Shader.h.
Constructor & Destructor Documentation
~FShaderMapBase()
virtual RENDERCORE_API FShaderMapBase::~FShaderMapBase () virtual
FShaderMapBase()
RENDERCORE_API FShaderMapBase::FShaderMapBase () protected
Referenced by AssignCopy().
Member Function Documentation
AssignContent()
RENDERCORE_API void FShaderMapBase::AssignContent (TMemoryImageObject< FShaderMapContent > InContent)
Referenced by FGlobalShaderMapSection::FGlobalShaderMapSection().
AssignCopy()
RENDERCORE_API void FShaderMapBase::AssignCopy (const FShaderMapBase & Source) protected
References FShaderMapBase(), and Source.
AssociateWithAsset()
void FShaderMapBase::AssociateWithAsset (const FName & AssetPath) inline
Associates a shadermap with an asset (note: one shadermap can be used by several assets, e.g.
MIs). This helps cooker lay out the shadermaps (and shaders) in the file open order, if provided. Maps not associated with any assets may be placed after all maps associated with known assets. Global shadermaps need to be associated with a "Global" asset
Definition at line 2576 of file Shader.h.
References AssociatedAssets.
Referenced by FGlobalShaderMapSection::FGlobalShaderMapSection().
AssociateWithAssets()
void FShaderMapBase::AssociateWithAssets (const FShaderMapAssetPaths & AssetPaths) inline
Definition at line 2581 of file Shader.h.
References AssociatedAssets.
CreatePointerTable()
virtual FShaderMapPointerTable * FShaderMapBase::CreatePointerTable () const protected pure virtual
Implemented in TShaderMap< ContentType, PointerTableType >, TShaderMap< FGlobalShaderMapContent, FShaderMapPointerTable >, and TShaderMap< FMaterialShaderMapContent, FShaderMapPointerTable >.
DestroyContent()
RENDERCORE_API void FShaderMapBase::DestroyContent () protected
DumpShaderList()
virtual void FShaderMapBase::DumpShaderList (FShaderListReport & Out) const inline virtual
Reimplemented in FMaterialShaderMap.
Definition at line 2533 of file Shader.h.
References FShaderMapContent::DumpShaderList(), and GetContent().
FinalizeContent()
RENDERCORE_API void FShaderMapBase::FinalizeContent ()
Referenced by TShaderMap< FMaterialShaderMapContent, FShaderMapPointerTable >::FinalizeContent().
GetAssociatedAssets()
const FShaderMapAssetPaths & FShaderMapBase::GetAssociatedAssets () const inline
Definition at line 2586 of file Shader.h.
References AssociatedAssets.
GetContent()
const FShaderMapContent * FShaderMapBase::GetContent () const inline
Definition at line 2522 of file Shader.h.
References Content.
Referenced by DumpShaderList(), and TShaderMap< FMaterialShaderMapContent, FShaderMapPointerTable >::GetContent().
GetContentTypeDesc()
virtual const FTypeLayoutDesc & FShaderMapBase::GetContentTypeDesc () const protected pure virtual
Implemented in TShaderMap< ContentType, PointerTableType >, TShaderMap< FGlobalShaderMapContent, FShaderMapPointerTable >, and TShaderMap< FMaterialShaderMapContent, FShaderMapPointerTable >.
GetFrozenContentSize()
uint32 FShaderMapBase::GetFrozenContentSize () const inline
Definition at line 2540 of file Shader.h.
References Content.
Referenced by FMaterialShaderMap::IsValidForRendering().
GetMutableContent()
FShaderMapContent * FShaderMapBase::GetMutableContent () inline
Definition at line 2523 of file Shader.h.
References Content, and UnfreezeContent().
Referenced by TShaderMap< FMaterialShaderMapContent, FShaderMapPointerTable >::GetMutableContent().
GetOutdatedTypes()
void FShaderMapBase::GetOutdatedTypes (TArray< const FShaderType * > & OutdatedShaderTypes, TArray< const FShaderPipelineType * > & OutdatedShaderPipelineTypes, TArray< const FVertexFactoryType * > & OutdatedFactoryTypes) const inline
Definition at line 2564 of file Shader.h.
References Content.
GetPermutationFlags()
EShaderPermutationFlags FShaderMapBase::GetPermutationFlags () const inline
Definition at line 2551 of file Shader.h.
References GetPermutationFlags(), and PermutationFlags.
Referenced by GetPermutationFlags().
GetPointerTable()
const FShaderMapPointerTable & FShaderMapBase::GetPointerTable () const inline
Definition at line 2521 of file Shader.h.
References check, and PointerTable.
Referenced by TShaderMap< FMaterialShaderMapContent, FShaderMapPointerTable >::GetPointerTable().
GetResource()
FShaderMapResource * FShaderMapBase::GetResource () const inline
Definition at line 2519 of file Shader.h.
References Resource.
GetResourceChecked()
FShaderMapResource * FShaderMapBase::GetResourceChecked () const inline
Definition at line 2520 of file Shader.h.
References check, and Resource.
GetResourceCode()
RENDERCORE_API FShaderMapResourceCode * FShaderMapBase::GetResourceCode ()
Referenced by TShaderMap< FMaterialShaderMapContent, FShaderMapPointerTable >::FinalizeContent().
GetShaderList()
virtual void FShaderMapBase::GetShaderList (TMap< FHashedName, TShaderRef< FShader > > & OutShaders) const pure virtual
Builds a list of the shaders in a shader map.
Key is FShaderType::TypeName
Implemented in FGlobalShaderMapSection, and FMaterialShaderMap.
GetShaderPipelineList()
virtual void FShaderMapBase::GetShaderPipelineList (TArray< FShaderPipelineRef > & OutShaderPipelines) const pure virtual
Implemented in FGlobalShaderMapSection, and FMaterialShaderMap.
GetShaderPlatform()
EShaderPlatform FShaderMapBase::GetShaderPlatform () const inline
Definition at line 2539 of file Shader.h.
References Content.
InitResource()
RENDERCORE_API void FShaderMapBase::InitResource () protected
PostFinalizeContent()
virtual void FShaderMapBase::PostFinalizeContent () inline protected virtual
Reimplemented in FMaterialShaderMap.
Definition at line 2603 of file Shader.h.
SaveShaderStableKeys()
void FShaderMapBase::SaveShaderStableKeys (EShaderPlatform TargetShaderPlatform, const struct FStableShaderKeyAndValue & SaveKeyVal) inline
Definition at line 2568 of file Shader.h.
References Content.
Serialize() [1/2]
RENDERCORE_API bool FShaderMapBase::Serialize (FArchive & Ar, bool bInlineShaderResources, bool bLoadingCooked, bool bInlineShaderCode = false, const FName & SerializingAsset = NAME_None)
References Ar, and Serialize().
Referenced by Serialize(), and Serialize().
Serialize() [2/2]
RENDERCORE_API bool FShaderMapBase::Serialize (FShaderSerializeContext & Ctx)
References Serialize().
ToString()
RENDERCORE_API FString FShaderMapBase::ToString () const
UnfreezeContent()
RENDERCORE_API void FShaderMapBase::UnfreezeContent ()
Referenced by GetMutableContent().
Field Documentation
AssociatedAssets
FShaderMapAssetPaths FShaderMapBase::AssociatedAssets private
List of the assets that are using this shadermap.
This is only available in the editor (cooker) to influence ordering of shader libraries.
Definition at line 2608 of file Shader.h.
Referenced by AssociateWithAsset(), AssociateWithAssets(), and GetAssociatedAssets().
Code
TRefCountPtr<FShaderMapResourceCode> FShaderMapBase::Code private
Definition at line 2611 of file Shader.h.
Content
TMemoryImageObject<FShaderMapContent> FShaderMapBase::Content private
Definition at line 2613 of file Shader.h.
Referenced by GetContent(), GetFrozenContentSize(), GetMutableContent(), GetOutdatedTypes(), GetShaderPlatform(), and SaveShaderStableKeys().
NumFrozenShaders
uint32 FShaderMapBase::NumFrozenShaders private
Definition at line 2614 of file Shader.h.
PermutationFlags
EShaderPermutationFlags FShaderMapBase::PermutationFlags private
Definition at line 2615 of file Shader.h.
Referenced by GetPermutationFlags().
PointerTable
FShaderMapPointerTable* FShaderMapBase::PointerTable private
Definition at line 2612 of file Shader.h.
Referenced by GetPointerTable().
Resource
TRefCountPtr<FShaderMapResource> FShaderMapBase::Resource private
Definition at line 2610 of file Shader.h.
Referenced by GetResource(), and GetResourceChecked().
The documentation for this class was generated from the following file:
Runtime/RenderCore/Public/Shader.h