Unreal Engine 5.6 C++ API: FShaderPipelineCompileJob Class Reference
FShaderPipelineCompileJob Class Reference
#include "ShaderCompilerJobTypes.h"
Public Member Functions
RENDERCORE_API FShaderPipelineCompileJob (int32 NumStages)
RENDERCORE_API FShaderPipelineCompileJob (uint32 InHash, uint32 InId, EShaderCompileJobPriority InPriroity, const FShaderPipelineCompileJobKey &InKey)
virtual RENDERCORE_API void AppendDebugName (FStringBuilderBase &OutName) const override
virtual RENDERCORE_API void AppendDiagnostics (FString &OutDiagnostics, int32 InJobIndex, int32 InNumJobs, const TCHAR *Indentation=nullptr) const override final
Generates a diagnostics string for this compile job suitable for the output log.
virtual RENDERCORE_API FShaderCompilerInputHash GetInputHash () override
Returns hash of all inputs for this job (needed for caching).
virtual RENDERCORE_API void OnComplete () override
virtual void SerializeOutput (FArchive &Ar) override
virtual RENDERCORE_API void SerializeOutput (FShaderCacheSerializeContext &Ctx) override
Serializes (and deserializes) the output for caching purposes.
Public Member Functions inherited from FShaderCommonCompileJob
uint32 AddRef () const
bool Equals (const FShaderCommonCompileJob &Rhs) const
void ForEachSingleShaderJob (const TFunction< void(const FShaderCompileJob &SingleJob)> &Predicate) const
Calls the specified predicate for each single compile job, i.e.
void ForEachSingleShaderJob (const TFunction< void(FShaderCompileJob &SingleJob)> &Predicate)
uint32 GetRefCount () const
FShaderPipelineCompileJob * GetShaderPipelineJob ()
const FShaderPipelineCompileJob * GetShaderPipelineJob () const
FShaderCompileJob * GetSingleShaderJob ()
const FShaderCompileJob * GetSingleShaderJob () const
uint32 Release () const
void UpdateInputHash ()
void UpdateStatus (EShaderCompileJobStatus NewStatus)
Data Fields
FShaderPipelineCompileJobKey Key
TArray< TRefCountPtr< FShaderCompileJob > > StageJobs
Data Fields inherited from FShaderCommonCompileJob
uint8 bBypassCache: 1
Whether or not to bypass the job/ddc caches when executing this job.
uint8 bErrorsAreLikelyToBeCode: 1
uint8 bFinalized: 1
true if the results of the shader compile have been processed.
uint8 bInputHashSet: 1
Whether we hashed the inputs.
uint8 bIsDefaultMaterial: 1
Whether or not we are a default material.
uint8 bIsGlobalShader: 1
Whether or not we are a global shader.
uint8 bReleased: 1
true if the results of the shader compile have been released from the FShaderCompilerManager.
uint8 bSucceeded: 1
Output of the shader compile.
EShaderCompilerWorkerType CurrentWorker
uint32 Hash
uint32 Id
Id of the shader map this shader belongs to.
FShaderCompilerInputHash InputHash
Hash of all the job inputs.
FShaderJobCacheRef JobCacheRef
int32 JobIndex
TSharedPtr< FShaderCompileJobStatus > JobStatusPtr
FShaderCommonCompileJob * NextLink = nullptr
Linked list support – not using TIntrusiveLinkedList because we want lock free insertion not supported by the core class.
FThreadSafeCounter NumRefs
EShaderCompileJobPriority PendingPriority
FPendingShaderMapCompileResultsPtr PendingShaderMap
FShaderCommonCompileJob ** PrevLink = nullptr
EShaderCompileJobPriority Priority
TPimplPtr< UE::DerivedData::FRequestOwner > RequestOwner
double TimeAddedToPendingQueue = 0.0
In-engine timestamp of being added to a pending queue.
double TimeAssignedToExecution = 0.0
In-engine timestamp of being assigned to a worker.
double TimeExecutionCompleted = 0.0
In-engine timestamp of job being completed.
double TimeTaskSubmitJobs = 0.0
Time spent in tasks generated in FShaderJobCache::SubmitJobs, plus stall time on mutex locks in those tasks.
double TimeTaskSubmitJobsStall = 0.0
EShaderCompileJobType Type
Static Public Attributes
static const EShaderCompileJobType Type = EShaderCompileJobType::Pipeline
Additional Inherited Members
Static Public Member Functions inherited from FShaderCommonCompileJob
static RENDERCORE_API uint32 GetNextJobId ()
This returns a unique id for a shader compiler job.
Protected Member Functions inherited from FShaderCommonCompileJob
FShaderCommonCompileJob (EShaderCompileJobType InType, uint32 InHash, uint32 InId, EShaderCompileJobPriority InPriority)
virtual ~FShaderCommonCompileJob ()
Detailed Description
Definition at line 410 of file ShaderCompilerJobTypes.h.
Constructor & Destructor Documentation
FShaderPipelineCompileJob() [1/2]
RENDERCORE_API FShaderPipelineCompileJob::FShaderPipelineCompileJob (int32 NumStages)
References FShaderPipelineCompileJob().
Referenced by FShaderPipelineCompileJob(), and FShaderPipelineCompileJob().
FShaderPipelineCompileJob() [2/2]
RENDERCORE_API FShaderPipelineCompileJob::FShaderPipelineCompileJob (uint32 InHash, uint32 InId, EShaderCompileJobPriority InPriroity, const FShaderPipelineCompileJobKey & InKey)
References FShaderPipelineCompileJob().
Member Function Documentation
AppendDebugName()
virtual RENDERCORE_API void FShaderPipelineCompileJob::AppendDebugName (FStringBuilderBase & OutName) const override virtual
Implements FShaderCommonCompileJob.
AppendDiagnostics()
virtual RENDERCORE_API void FShaderPipelineCompileJob::AppendDiagnostics (FString & OutDiagnostics, int32 InJobIndex, int32 InNumJobs, const TCHAR * Indentation = nullptr) const final override virtual
Generates a diagnostics string for this compile job suitable for the output log.
Implements FShaderCommonCompileJob.
GetInputHash()
virtual RENDERCORE_API FShaderCompilerInputHash FShaderPipelineCompileJob::GetInputHash () override virtual
Returns hash of all inputs for this job (needed for caching).
Reimplemented from FShaderCommonCompileJob.
OnComplete()
virtual RENDERCORE_API void FShaderPipelineCompileJob::OnComplete () override virtual
Implements FShaderCommonCompileJob.
SerializeOutput() [1/2]
virtual void FShaderPipelineCompileJob::SerializeOutput (FArchive & Ar) inline override virtual
Reimplemented from FShaderCommonCompileJob.
Definition at line 421 of file ShaderCompilerJobTypes.h.
References Ar, and SerializeOutput().
Referenced by SerializeOutput().
SerializeOutput() [2/2]
virtual RENDERCORE_API void FShaderPipelineCompileJob::SerializeOutput (FShaderCacheSerializeContext & Ctx) override virtual
Serializes (and deserializes) the output for caching purposes.
Reimplemented from FShaderCommonCompileJob.
Field Documentation
Key
FShaderPipelineCompileJobKey FShaderPipelineCompileJob::Key
Definition at line 415 of file ShaderCompilerJobTypes.h.
StageJobs
TArray<TRefCountPtr<FShaderCompileJob> > FShaderPipelineCompileJob::StageJobs
Definition at line 416 of file ShaderCompilerJobTypes.h.
Type
const EShaderCompileJobType FShaderPipelineCompileJob::Type = EShaderCompileJobType::Pipeline static
Definition at line 413 of file ShaderCompilerJobTypes.h.
The documentation for this class was generated from the following file:
Runtime/RenderCore/Public/ShaderCompilerJobTypes.h