Unreal Engine 5.6 C++ API: FUObjectAnnotationSparseSearchable< TAnnotation, bAutoRemove > Class Template Reference
FUObjectAnnotationSparseSearchable< TAnnotation, bAutoRemove > Class Template Reference
FUObjectAnnotationSparseSearchable is a helper class that is used to store sparse, slow, temporary, editor only, external or other low priority information about UObjects...and also provides the ability to find a object based on the unique annotation.
#include "UObjectAnnotation.h"
Public Member Functions
virtual ~FUObjectAnnotationSparseSearchable ()
Destructor, removes all annotations, which removes the annotation as a uobject destruction listener.
void AddAnnotation (const UObjectBase *Object, const TAnnotation &Annotation)
Add an annotation to the annotation list.
void AddAnnotation (const UObjectBase *Object, TAnnotation &&Annotation)
UObject * Find (const TAnnotation &Annotation)
Find the UObject associated with a given annotation.
virtual SIZE_T GetAllocatedSize () const override
Returns the size of heap memory allocated internally by this listener.
virtual void NotifyUObjectDeleted (const UObjectBase *Object, int32 Index) override
Interface for FUObjectAllocator::FUObjectDeleteListener.
virtual void OnUObjectArrayShutdown () override
Called when UObject Array is being shut down, this is where all listeners should be removed from it.
void RemoveAllAnnotations ()
Removes all annotation from the annotation list.
void RemoveAnnotation (const UObjectBase *Object)
Removes an annotation from the annotation list.
Public Member Functions inherited from FUObjectAnnotationSparse< TAnnotation, bAutoRemove >
FUObjectAnnotationSparse ()
Constructor, initializes to nothing.
virtual ~FUObjectAnnotationSparse ()
Destructor, removes all annotations, which removes the annotation as a uobject destruction listener.
void AddAnnotation (const UObjectBase *Object, const TAnnotation &Annotation)
void AddAnnotation (const UObjectBase *Object, TAnnotation &&Annotation)
Add an annotation to the annotation list.
TAnnotation GetAndRemoveAnnotation (const UObjectBase *Object)
Removes an annotation from the annotation list and returns the annotation if it had one.
FORCEINLINE TAnnotation GetAnnotation (const UObjectBase *Object)
Return the annotation associated with a uobject.
const TMap< const UObjectBase *, TAnnotation > & GetAnnotationMap () const
Return the annotation map.
void RemoveAllAnnotations ()
Removes all annotation from the annotation list.
void RemoveAnnotation (const UObjectBase *Object)
Removes an annotation from the annotation list.
void Reserve (int32 ExpectedNumElements)
Reserves memory for the annotation map for the specified number of elements, used to avoid reallocations.
Public Member Functions inherited from FUObjectArray::FUObjectDeleteListener
virtual ~FUObjectDeleteListener ()
virtual void NotifyUObjectDeleted (const class UObjectBase *Object, int32 Index)=0
Provides notification that a UObjectBase has been removed from the uobject array.
Private Types
typedef FUObjectAnnotationSparse< TAnnotation, bAutoRemove > Super
Private Member Functions
template<typename T>
void AddAnnotationInternal (const UObjectBase *Object, T &&Annotation)
Private Attributes
TMap< TAnnotation, const UObjectBase * > InverseAnnotationMap
Inverse Map annotation to live object.
FTransactionallySafeCriticalSection InverseAnnotationMapCritical
Additional Inherited Members
Protected Attributes inherited from FUObjectAnnotationSparse< TAnnotation, bAutoRemove >
FTransactionallySafeRWLock AnnotationCacheCritical
const UObjectBase * AnnotationCacheKey = nullptr
Key for a one-item cache of the last lookup into AnnotationMap.
TAnnotation AnnotationCacheValue
Value for a one-item cache of the last lookup into AnnotationMap.
TMap< const UObjectBase *, TAnnotation > AnnotationMap
Map from live objects to an annotation.
FTransactionallySafeRWLock AnnotationMapCritical
Guards the annotation map, cache key and cache value.
Detailed Description
template<typename TAnnotation, bool bAutoRemove>
class FUObjectAnnotationSparseSearchable< TAnnotation, bAutoRemove >
FUObjectAnnotationSparseSearchable is a helper class that is used to store sparse, slow, temporary, editor only, external or other low priority information about UObjects...and also provides the ability to find a object based on the unique annotation.
All of the restrictions mentioned for FUObjectAnnotationSparse apply
Parameters
TAnnotation type of the annotation
bAutoRemove if true, annotation will automatically be removed, otherwise in non-final builds it will verify that the annotation was removed by other means prior to destruction.
Definition at line 391 of file UObjectAnnotation.h.
Member Typedef Documentation
Super
template<typename TAnnotation, bool bAutoRemove> typedef FUObjectAnnotationSparse<TAnnotation, bAutoRemove> FUObjectAnnotationSparseSearchable< TAnnotation, bAutoRemove >::Super private
Definition at line 393 of file UObjectAnnotation.h.
Constructor & Destructor Documentation
~FUObjectAnnotationSparseSearchable()
template<typename TAnnotation, bool bAutoRemove> virtual FUObjectAnnotationSparseSearchable< TAnnotation, bAutoRemove >::~FUObjectAnnotationSparseSearchable () inline virtual
Destructor, removes all annotations, which removes the annotation as a uobject destruction listener.
Definition at line 415 of file UObjectAnnotation.h.
References RemoveAllAnnotations().
Member Function Documentation
AddAnnotation() [1/2]
template<typename TAnnotation, bool bAutoRemove> void FUObjectAnnotationSparseSearchable< TAnnotation, bAutoRemove >::AddAnnotation (const UObjectBase * Object, const TAnnotation & Annotation) inline
Add an annotation to the annotation list.
If the Annotation is the default, then the annotation is removed.
Parameters
Object Object to annotate.
Annotation Annotation to associate with Object.
Definition at line 465 of file UObjectAnnotation.h.
References AddAnnotationInternal(), and Object.
AddAnnotation() [2/2]
template<typename TAnnotation, bool bAutoRemove> void FUObjectAnnotationSparseSearchable< TAnnotation, bAutoRemove >::AddAnnotation (const UObjectBase * Object, TAnnotation && Annotation) inline
Definition at line 470 of file UObjectAnnotation.h.
References AddAnnotationInternal(), MoveTemp(), and Object.
AddAnnotationInternal()
template<typename TAnnotation, bool bAutoRemove> template<typename T> void FUObjectAnnotationSparseSearchable< TAnnotation, bAutoRemove >::AddAnnotationInternal (const UObjectBase * Object, T && Annotation) inline private
Definition at line 435 of file UObjectAnnotation.h.
References FUObjectAnnotationSparse< TAnnotation, bAutoRemove >::AddAnnotation(), checkSlow, Forward(), FUObjectAnnotationSparse< TAnnotation, bAutoRemove >::GetAnnotation(), InverseAnnotationMap, InverseAnnotationMapCritical, Object, and RemoveAnnotation().
Referenced by AddAnnotation(), and AddAnnotation().
Find()
template<typename TAnnotation, bool bAutoRemove> UObject * FUObjectAnnotationSparseSearchable< TAnnotation, bAutoRemove >::Find (const TAnnotation & Annotation) inline
Find the UObject associated with a given annotation.
Parameters
Annotation Annotation to find
Returns
Object associated with this annotation or NULL if none found
Definition at line 426 of file UObjectAnnotation.h.
References checkSlow, InverseAnnotationMap, and InverseAnnotationMapCritical.
GetAllocatedSize()
template<typename TAnnotation, bool bAutoRemove> virtual SIZE_T FUObjectAnnotationSparseSearchable< TAnnotation, bAutoRemove >::GetAllocatedSize () const inline override virtual
Returns the size of heap memory allocated internally by this listener.
Reimplemented from FUObjectAnnotationSparse< TAnnotation, bAutoRemove >.
Definition at line 506 of file UObjectAnnotation.h.
References FUObjectAnnotationSparse< TAnnotation, bAutoRemove >::GetAllocatedSize(), and InverseAnnotationMap.
NotifyUObjectDeleted()
template<typename TAnnotation, bool bAutoRemove> virtual void FUObjectAnnotationSparseSearchable< TAnnotation, bAutoRemove >::NotifyUObjectDeleted (const UObjectBase * Object, int32 Index) inline override virtual
Interface for FUObjectAllocator::FUObjectDeleteListener.
Parameters
Object object that has been destroyed
Index index of object that is being deleted
Reimplemented from FUObjectAnnotationSparse< TAnnotation, bAutoRemove >.
Definition at line 401 of file UObjectAnnotation.h.
References Object, and RemoveAnnotation().
OnUObjectArrayShutdown()
template<typename TAnnotation, bool bAutoRemove> virtual void FUObjectAnnotationSparseSearchable< TAnnotation, bAutoRemove >::OnUObjectArrayShutdown () inline override virtual
Called when UObject Array is being shut down, this is where all listeners should be removed from it.
Reimplemented from FUObjectAnnotationSparse< TAnnotation, bAutoRemove >.
Definition at line 406 of file UObjectAnnotation.h.
References GUObjectArray, and RemoveAllAnnotations().
RemoveAllAnnotations()
template<typename TAnnotation, bool bAutoRemove> void FUObjectAnnotationSparseSearchable< TAnnotation, bAutoRemove >::RemoveAllAnnotations () inline
Removes all annotation from the annotation list.
Definition at line 499 of file UObjectAnnotation.h.
References InverseAnnotationMap, InverseAnnotationMapCritical, and FUObjectAnnotationSparse< TAnnotation, bAutoRemove >::RemoveAllAnnotations().
Referenced by ~FUObjectAnnotationSparseSearchable(), and OnUObjectArrayShutdown().
RemoveAnnotation()
template<typename TAnnotation, bool bAutoRemove> void FUObjectAnnotationSparseSearchable< TAnnotation, bAutoRemove >::RemoveAnnotation (const UObjectBase * Object) inline
Removes an annotation from the annotation list.
Parameters
Object Object to de-annotate.
Definition at line 480 of file UObjectAnnotation.h.
References checkSlow, FUObjectAnnotationSparse< TAnnotation, bAutoRemove >::GetAndRemoveAnnotation(), InverseAnnotationMap, InverseAnnotationMapCritical, and Object.
Referenced by AddAnnotationInternal(), and NotifyUObjectDeleted().
Field Documentation
InverseAnnotationMap
template<typename TAnnotation, bool bAutoRemove> TMap<TAnnotation, const UObjectBase *> FUObjectAnnotationSparseSearchable< TAnnotation, bAutoRemove >::InverseAnnotationMap private
Inverse Map annotation to live object.
Definition at line 515 of file UObjectAnnotation.h.
Referenced by AddAnnotationInternal(), Find(), GetAllocatedSize(), RemoveAllAnnotations(), and RemoveAnnotation().
InverseAnnotationMapCritical
template<typename TAnnotation, bool bAutoRemove> FTransactionallySafeCriticalSection FUObjectAnnotationSparseSearchable< TAnnotation, bAutoRemove >::InverseAnnotationMapCritical private
Definition at line 516 of file UObjectAnnotation.h.
Referenced by AddAnnotationInternal(), Find(), RemoveAllAnnotations(), and RemoveAnnotation().
The documentation for this class was generated from the following file:
Runtime/CoreUObject/Public/UObject/UObjectAnnotation.h