Unreal Engine 5.6 C++ API: Metasound::TArraySubsetOperator< ArrayType > Class Template Reference
Metasound::TArraySubsetOperator< ArrayType > Class Template Reference
TArraySubsetOperator slices an array on trigger.
#include "MetasoundArrayNodes.h"
Public Types
using ElementType = typename MetasoundArrayNodesPrivate::TArrayElementType<ArrayType>::Type
using FArrayDataReadReference = TDataReadReference<ArrayType>
using FArrayDataWriteReference = TDataWriteReference<ArrayType>
Public Types inherited from Metasound::IOperator
using FExecuteFunction = void(*)(IOperator*)
Pointer to execute function for an operator.
using FPostExecuteFunction = void(*)(IOperator*)
Pointer to post execute function for an operator.
using FResetFunction = void(*)(IOperator*, const FResetParams& InParams)
Pointer to initialize function for an operator.
Public Member Functions
TArraySubsetOperator (TDataReadReference< FTrigger > InTrigger, FArrayDataReadReference InInputArray, TDataReadReference< int32 > InStartIndex, TDataReadReference< int32 > InEndIndex, TDataWriteReference< ArrayType > InOutputArray)
virtual ~TArraySubsetOperator ()=default
virtual void BindInputs (FInputVertexInterfaceData &InVertexData) override
BindInputs binds data references in the IOperator with the FInputVertexInterfaceData.
virtual void BindOutputs (FOutputVertexInterfaceData &InVertexData) override
BindOutputs binds data references in the IOperator with the FOutputVertexInterfaceData.
void Execute ()
virtual FDataReferenceCollection GetInputs () const override
virtual FDataReferenceCollection GetOutputs () const override
void Reset (const IOperator::FResetParams &InParams)
Public Member Functions inherited from Metasound::TExecutableOperator< TArraySubsetOperator< ArrayType > >
virtual ~TExecutableOperator ()
virtual FExecuteFunction GetExecuteFunction () override
Return the execution function to call during graph execution.
virtual FPostExecuteFunction GetPostExecuteFunction () override
Return the FPostExecute function to call during graph post execution.
virtual FResetFunction GetResetFunction () override
Return the reset function to call during graph execution.
Public Member Functions inherited from Metasound::IOperator
virtual ~IOperator ()
UE_DEPRECATED (5.3, "Bind(FVertexInterfaceData&) has been replaced by BindInputs(FInputVertexInterfaceDAta&) and BindOutputs(FOutputVertexInterfaceData&)") virtual void METASOUNDGRAPHCORE_API Bind(FVertexInterfaceData &InVertexData) const
Bind(...) has been deprecated in favor of BindInputs(...) and BindOutputs(...).
UE_DEPRECATED (5.3, "GetInputs() has been replaced by BindInputs(FInputVertexInterfaceData&).") virtual FDataReferenceCollection METASOUNDGRAPHCORE_API GetInputs() const
GetInputs() has been deprecated in favor of BindInputs(...).
UE_DEPRECATED (5.3, "GetOutputs() has been replaced by BindOutputs(FOutputVertexInterfaceData&)") virtual FDataReferenceCollection METASOUNDGRAPHCORE_API GetOutputs() const
GetOutputs() has been deprecated in favor of BindOutputs(...).
Static Public Member Functions
static TUniquePtr< IOperator > CreateOperator (const FBuildOperatorParams &InParams, FBuildResults &OutResults)
static const FVertexInterface & GetDefaultInterface ()
static const FNodeClassMetadata & GetNodeInfo ()
Private Attributes
TDataReadReference< int32 > EndIndex
FArrayDataReadReference InputArray
FArrayDataWriteReference OutputArray
TDataReadReference< int32 > StartIndex
TDataReadReference< FTrigger > Trigger
Detailed Description
template<typename ArrayType>
class Metasound::TArraySubsetOperator< ArrayType >
TArraySubsetOperator slices an array on trigger.
Definition at line 697 of file MetasoundArrayNodes.h.
Member Typedef Documentation
ElementType
template<typename ArrayType> using Metasound::TArraySubsetOperator< ArrayType >::ElementType = typename MetasoundArrayNodesPrivate::TArrayElementType<ArrayType>::Type
Definition at line 702 of file MetasoundArrayNodes.h.
FArrayDataReadReference
template<typename ArrayType> using Metasound::TArraySubsetOperator< ArrayType >::FArrayDataReadReference = TDataReadReference<ArrayType>
Definition at line 700 of file MetasoundArrayNodes.h.
FArrayDataWriteReference
template<typename ArrayType> using Metasound::TArraySubsetOperator< ArrayType >::FArrayDataWriteReference = TDataWriteReference<ArrayType>
Definition at line 701 of file MetasoundArrayNodes.h.
Constructor & Destructor Documentation
TArraySubsetOperator()
template<typename ArrayType> Metasound::TArraySubsetOperator< ArrayType >::TArraySubsetOperator (TDataReadReference< FTrigger > InTrigger, FArrayDataReadReference InInputArray, TDataReadReference< int32 > InStartIndex, TDataReadReference< int32 > InEndIndex, TDataWriteReference< ArrayType > InOutputArray) inline
Definition at line 766 of file MetasoundArrayNodes.h.
References EndIndex, InputArray, OutputArray, StartIndex, and Trigger.
~TArraySubsetOperator()
template<typename ArrayType> virtual Metasound::TArraySubsetOperator< ArrayType >::~TArraySubsetOperator () virtual default
Member Function Documentation
BindInputs()
template<typename ArrayType> virtual void Metasound::TArraySubsetOperator< ArrayType >::BindInputs (FInputVertexInterfaceData & InVertexData) inline override virtual
BindInputs binds data references in the IOperator with the FInputVertexInterfaceData.
All input data references should be bound to the InVertexData to support other MetaSound systems such as MetaSound BP API, Operator Caching, and live auditioning.
Note: The virtual function IOPerator::BindInputs(...) will be made a pure virtual when IOperator::GetInputs() is removed at or after release 5.5
Note: Binding an data reference may update the which underlying object the reference points to. Any operator which caches pointers or values from data references must update their cached pointers in the call to BindInputs(...). Operators which do not cache the underlying pointer of a data reference do not need to update anything after BindInputs(...)
Example: FMyOperator::FMyOperator(TDataReadReference<float> InGain, TDataReadReference<FAudioBuffer> InAudioBuffer) : Gain(InGain) , AudioBuffer(InAudioBuffer) { MyBufferPtr = AudioBuffer->GetData();
}
void FMyOperator::BindInputs(FInputVertexInterfaceData& InVertexData) { InVertexData.BindReadVertex("Gain", Gain); InVertexData.BindReadVertex("Audio", AudioBuffer);
// Update MyBufferPtr in case AudioBuffer references a new FAudioBuffer. MyBufferPtr = AudioBuffer->GetData(); }
Reimplemented from Metasound::IOperator.
Definition at line 789 of file MetasoundArrayNodes.h.
References Metasound::FInputVertexInterfaceData::BindReadVertex(), EndIndex, InputArray, METASOUND_GET_PARAM_NAME, StartIndex, and Trigger.
BindOutputs()
template<typename ArrayType> virtual void Metasound::TArraySubsetOperator< ArrayType >::BindOutputs (FOutputVertexInterfaceData & InVertexData) inline override virtual
BindOutputs binds data references in the IOperator with the FOutputVertexInterfaceData.
All output data references should be bound to the InVertexData to support other MetaSound systems such as MetaSound BP API, Operator Caching, and live auditioning.
Note: The virtual function IOPerator::BindOutputs(...) will be made a pure virtual when IOperator::GetOutputs() is removed at or after release 5.5
Note: Binding an data reference may update the which underlying object the reference points to. Any operator which caches pointers or values from data references must update their cached pointers in the call to BindOutputs(...). Operators which do not cache the underlying pointer of a data reference do not need to update anything after BindOutputs(...)
Example: FMyOperator::FMyOperator(TDataWriteReference<float> InGain, TDataWriteReference<FAudioBuffer> InAudioBuffer) : Gain(InGain) , AudioBuffer(InAudioBuffer) { MyBufferPtr = AudioBuffer->GetData();
}
void FMyOperator::BindOutputs(FOutputVertexInterfaceData& InVertexData) { InVertexData.BindReadVertex("Gain", Gain); InVertexData.BindReadVertex("Audio", AudioBuffer);
// Update MyBufferPtr in case AudioBuffer references a new FAudioBuffer. MyBufferPtr = AudioBuffer->GetData(); }
Reimplemented from Metasound::IOperator.
Definition at line 799 of file MetasoundArrayNodes.h.
References Metasound::FOutputVertexInterfaceData::BindReadVertex(), METASOUND_GET_PARAM_NAME, and OutputArray.
CreateOperator()
template<typename ArrayType> TUniquePtr< IOperator > Metasound::TArraySubsetOperator< ArrayType >::CreateOperator (const FBuildOperatorParams & InParams, FBuildResults & OutResults) inline static
Definition at line 746 of file MetasoundArrayNodes.h.
References Metasound::TDataFactory< DataType, TDataWriteReference< DataType > >::CreateExplicitArgs(), EndIndex, Metasound::FInputVertexInterfaceData::GetOrCreateDefaultDataReadReference(), InputArray, Metasound::FBuildOperatorParams::InputData, MakeUnique(), METASOUND_GET_PARAM_NAME, Metasound::FBuildOperatorParams::OperatorSettings, OutputArray, StartIndex, and Trigger.
Execute()
template<typename ArrayType> void Metasound::TArraySubsetOperator< ArrayType >::Execute () inline
Definition at line 806 of file MetasoundArrayNodes.h.
References EndIndex, InputArray, FMath::Max, FMath::Min, Num, OutputArray, StartIndex, and Trigger.
GetDefaultInterface()
template<typename ArrayType> const FVertexInterface & Metasound::TArraySubsetOperator< ArrayType >::GetDefaultInterface () inline static
Definition at line 704 of file MetasoundArrayNodes.h.
References InputArray, and METASOUND_GET_PARAM_NAME_AND_METADATA.
Referenced by GetNodeInfo().
GetInputs()
template<typename ArrayType> virtual FDataReferenceCollection Metasound::TArraySubsetOperator< ArrayType >::GetInputs () const inline override virtual
Definition at line 777 of file MetasoundArrayNodes.h.
References checkNoEntry.
GetNodeInfo()
template<typename ArrayType> const FNodeClassMetadata & Metasound::TArraySubsetOperator< ArrayType >::GetNodeInfo () inline static
Definition at line 724 of file MetasoundArrayNodes.h.
References TArray< InElementType, InAllocatorType >::Append(), Metasound::MetasoundArrayNodesPrivate::CreateArrayNodeClassMetadata(), GetDefaultInterface(), Metasound::GetMetasoundDataTypeDisplayText(), Metasound::GetMetasoundDataTypeName(), Metasound::FNodeClassMetadata::Keywords, Metadata, METASOUND_LOCTEXT, METASOUND_LOCTEXT_FORMAT, and TEXT.
GetOutputs()
template<typename ArrayType> virtual FDataReferenceCollection Metasound::TArraySubsetOperator< ArrayType >::GetOutputs () const inline override virtual
Definition at line 783 of file MetasoundArrayNodes.h.
References checkNoEntry.
Reset()
template<typename ArrayType> void Metasound::TArraySubsetOperator< ArrayType >::Reset (const IOperator::FResetParams & InParams) inline
Definition at line 824 of file MetasoundArrayNodes.h.
References OutputArray.
Field Documentation
EndIndex
template<typename ArrayType> TDataReadReference<int32> Metasound::TArraySubsetOperator< ArrayType >::EndIndex private
Definition at line 834 of file MetasoundArrayNodes.h.
Referenced by TArraySubsetOperator(), BindInputs(), CreateOperator(), and Execute().
InputArray
template<typename ArrayType> FArrayDataReadReference Metasound::TArraySubsetOperator< ArrayType >::InputArray private
Definition at line 832 of file MetasoundArrayNodes.h.
Referenced by TArraySubsetOperator(), BindInputs(), CreateOperator(), Execute(), and GetDefaultInterface().
OutputArray
template<typename ArrayType> FArrayDataWriteReference Metasound::TArraySubsetOperator< ArrayType >::OutputArray private
Definition at line 835 of file MetasoundArrayNodes.h.
Referenced by TArraySubsetOperator(), BindOutputs(), CreateOperator(), Execute(), and Reset().
StartIndex
template<typename ArrayType> TDataReadReference<int32> Metasound::TArraySubsetOperator< ArrayType >::StartIndex private
Definition at line 833 of file MetasoundArrayNodes.h.
Referenced by TArraySubsetOperator(), BindInputs(), CreateOperator(), and Execute().
Trigger
template<typename ArrayType> TDataReadReference<FTrigger> Metasound::TArraySubsetOperator< ArrayType >::Trigger private
Definition at line 831 of file MetasoundArrayNodes.h.
Referenced by TArraySubsetOperator(), BindInputs(), CreateOperator(), and Execute().
The documentation for this class was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/Metasound/Source/MetasoundFrontend/Public/MetasoundArrayNodes.h