Unreal Engine 5.6 C++ API: UEnvQueryGenerator_SimpleGrid Class Reference
UEnvQueryGenerator_SimpleGrid Class Reference
#include "EnvQueryGenerator_SimpleGrid.h"
Private Member Functions
GENERATED_UCLASS_BODY () UPROPERTY()) FAIDataProviderFloatValue GridSize
half of square's extent, like a radius
virtual AIMODULE_API void GenerateItems (FEnvQueryInstance &QueryInstance) const override
virtual AIMODULE_API FText GetDescriptionDetails () const override
virtual AIMODULE_API FText GetDescriptionTitle () const override
UPROPERTY () FAIDataProviderFloatValue SpaceBetween
generation density
UPROPERTY () TSubclassOf< UEnvQueryContext > GenerateAround
context
Detailed Description
Definition at line 18 of file EnvQueryGenerator_SimpleGrid.h.
Member Function Documentation
GENERATED_UCLASS_BODY()
UEnvQueryGenerator_SimpleGrid::GENERATED_UCLASS_BODY () private
half of square's extent, like a radius
References Category, meta, and UPROPERTY().
GenerateItems()
virtual AIMODULE_API void UEnvQueryGenerator_SimpleGrid::GenerateItems (FEnvQueryInstance & QueryInstance) const override private virtual
References GenerateItems().
Referenced by GenerateItems().
GetDescriptionDetails()
virtual AIMODULE_API FText UEnvQueryGenerator_SimpleGrid::GetDescriptionDetails () const override private virtual
References GetDescriptionDetails().
Referenced by GetDescriptionDetails().
GetDescriptionTitle()
virtual AIMODULE_API FText UEnvQueryGenerator_SimpleGrid::GetDescriptionTitle () const override private virtual
References GetDescriptionTitle().
Referenced by GetDescriptionTitle().
UPROPERTY() [1/2]
UEnvQueryGenerator_SimpleGrid::UPROPERTY () private
generation density
References Category, and UPROPERTY().
Referenced by GENERATED_UCLASS_BODY(), UPROPERTY(), and UPROPERTY().
UPROPERTY() [2/2]
UEnvQueryGenerator_SimpleGrid::UPROPERTY () private
context
References Category, and UPROPERTY().
The documentation for this class was generated from the following file:
Runtime/AIModule/Classes/EnvironmentQuery/Generators/EnvQueryGenerator_SimpleGrid.h