Unreal Engine 5.6 C++ API: FLinkerLoad Class Reference
FLinkerLoad Class Reference
#include "LinkerLoad.h"
Data Structures
struct FPackagePrecacheInfo
Helper struct to keep track of background file reads.
Public Member Functions
virtual ~FLinkerLoad ()
virtual bool AttachExternalReadDependency (FExternalReadCallback &ReadCallback) override
Adds external read dependency.
void BuildPathName (FString &OutPathName, FPackageIndex ExportIndex) const
Builds a string containing the full path for a resource in the export table.
bool CreateImportClassAndPackage (FName ClassName, FName PackageName, FPackageIndex &ClassIdx, FPackageIndex &PackageIdx)
Attempts to find the index for the given class object in the import list and adds it + its package if it does not exist.
void DestroyLoader ()
void Detach ()
Detaches linker from bulk data and exports and removes itself from array of loaders.
void DetachExports ()
Only detaches the linker from its exports and the reset their cached state in the linker without touching bulkdata or underlying loader.
void DetachLoader ()
Detaches all bulkdata currently attached to the FLinkerLoad followed by destroying the internal loader.
UObject * FindExistingExport (int32 ExportIndex)
Before loading a persistent object from disk, this function can be used to discover the object in memory.
UObject * FindExistingImport (int32 ImportIndex)
bool FindImport (FPackageIndex OuterIndex, FName ObjectName, FPackageIndex &OutObjectIndex)
Locates package index for a given name in an outer.
bool FindImport (FStringView FullObjectPath, FPackageIndex &OutObjectIndex)
Finds an import given the full object path as a string.
bool FindImportClassAndPackage (FName ClassName, FPackageIndex &ClassIdx, FPackageIndex &PackageIdx)
Locates the class adjusted index and its package adjusted index for a given class name in the import map.
bool FindImportPackage (FName PackageName, FPackageIndex &PackageIdx)
Locates package index for a UPackage import.
bool FinishExternalReadDependencies (double TimeLimit)
Finalizes external dependencies till time limit is exceeded.
ELinkerStatus FixupExportMap ()
Allows object instances to be converted to other classes upon loading a package.
virtual void FlushCache () override
Flush Loader Cache.
virtual void ForceBlueprintFinalization () override
Inform the archive that blueprint finalization is pending.
virtual UObject * GetArchetypeFromLoader (const UObject *Obj) override
Called to retrieve the archetype from the event driven loader.
virtual FString GetArchiveName () const override
Returns the name of the Archive.
FORCEINLINE FAsyncArchive * GetAsyncLoader ()
virtual FString GetDebugName () const override
Returns a descriptor of the PackagePath this Linker is reading from or writing to, usable for an identifier in warning and log messages.
FName GetExportClassPackage (int32 i)
FORCEINLINE const FLinkerInstancingContext & GetInstancingContext () const
virtual FLinker * GetLinker () override
If this archive is a FLinkerLoad or FLinkerSave, returns a pointer to the FLinker portion.
FArchive * GetLoader_Unsafe () const
Access the underlying archive.
FORCEINLINE int32 GetOwnerThreadId () const
Returns ID of the thread that created this linker.
const FPackagePath & GetPackagePath () const
Get the PackagePath being loaded.
const UE::FPackageTrailer * GetPackageTrailer () const
bool HasAnyObjectsPendingLoad () const
Checks if the linker has any objects in the export table that require loading.
FORCEINLINE bool HasFinishedInitialization () const
Returns whether linker has finished (potentially) async initialization.
bool HasLoader () const
bool IsBlueprintFinalizationPending () const
Query method to help handle recursive behavior.
FORCEINLINE bool IsDestroyingLoader () const
bool IsPackageRelocated () const
bool IsValidPackageIndex (FPackageIndex InIndex)
Test whether the given package index is a valid import or export in this package.
void LoadAllObjects (bool bForcePreload)
Loads all objects in package.
void LoadAndDetachAllBulkData ()
Detaches linker from bulk data.
virtual void MarkScriptSerializationEnd (const UObject *Obj) override
Called when an object stops serializing property data using script serialization.
virtual void MarkScriptSerializationStart (const UObject *Obj) override
Called when an object begins serializing property data using script serialization.
void Preload (UObject *Object) override
Serialize the object data for the specified object from the unreal package file.
void PRIVATE_PatchNewObjectIntoExport (int32 OldExportIndex, UObject *NewObject, FUObjectSerializeContext *InLoadContext=nullptr, bool bHideGarbageObjects=true)
UObject * RequestPlaceholderValue (const FProperty *Property, const UClass *ObjectType, const TCHAR *ObjectPath)
Gives external code the ability to create FLinkerPlaceholderBase objects in place of loads that may violate the LOAD_DeferDependencyLoads state.
UObject * ResolveResource (FPackageIndex ResourceIndex)
Returns the Object associated with the resource indicated.
FName ResolveResourceName (FPackageIndex ResourceIndex)
Returns the ObjectName associated with the resource indicated.
virtual bool SerializeBulkData (FBulkData &BulkData, const FBulkDataSerializationParams &Params) override
Serialize bulk data.
ELinkerStatus SerializeGatherableTextDataMap (bool bForceEnableForCommandlet=false)
Serializes the gatherable text data container.
ELinkerStatus SerializeThumbnails (bool bForceEnableForCommandlet=false)
Serializes thumbnails.
UE_DEPRECATED (5.5, "GetSerializeContext is not supported. Use FUObjectThreadContext::Get().GetSerializeContext().") 1 virtual FUObjectSerializeContext *GetSerializeContext() override
UE_DEPRECATED (5.5, "LOAD_RegenerateBulkDataGuids is now obsolete so this method no longer has any purpose.") bool ShouldRegenerateGuids() const
UE_DEPRECATED (5.6, "This function was used only for the now-deleted Conform functionality and will be removed. Contact Epic if you need this function.") int32 FindExportIndex(FName ClassName
void Verify ()
EVerifyResult VerifyImport (int32 ImportIndex)
A wrapper around VerifyImportInner.
bool WillTextureBeLoaded (UClass *Class, int32 ExportIndex)
Checks if the specified export should be loaded or not.
Public Member Functions inherited from FLinker
FLinker (ELinkerType::Type InType, UPackage *InRoot)
Constructor.
virtual ~FLinker ()
bool FilterExport (const FObjectExport &Export)
Test and object against the load flag filters.
FString GetExportFullName (FPackageIndex PackageIndex, const TCHAR *FakeRoot=nullptr, bool bResolveForcedExports=false)
Return the full name of the UObject represented by the specified package index.
FString GetExportFullName (int32 ExportIndex, const TCHAR *FakeRoot=nullptr, bool bResolveForcedExports=false)
Return the full name of the UObject represented by the specified export.
FString GetExportPathName (FPackageIndex PackageIndex, const TCHAR *FakeRoot=nullptr, bool bResolveForcedExports=false)
Return the path name of the UObject represented by the specified export.
FString GetExportPathName (int32 ExportIndex, const TCHAR *FakeRoot=nullptr, bool bResolveForcedExports=false)
Return the path name of the UObject represented by the specified export.
FString GetFullImpExpName (FPackageIndex PackageIndex)
Return the full name of the UObject represented by the specified export.
FString GetPathName (FPackageIndex PackageIndex)
Return the path name of the UObject represented by the specified import.
FORCEINLINE ELinkerType::Type GetType () const
void Serialize (FArchive &Ar)
I/O function.
UE_DEPRECATED (5.6, "No longer supported. Contact Epic if you need this functionality.") class FSHA1 *ScriptSHA
UE_DEPRECATED (5.6, "No longer supported. Contact Epic if you need this functionality.") void GetScriptSHAKey(uint8 *OutKey)
UE_DEPRECATED (5.6, "No longer supported. Contact Epic if you need this functionality.") void StartScriptSHAGeneration()
UE_DEPRECATED (5.6, "No longer supported. Contact Epic if you need this functionality.") void UpdateScriptSHAKey(const TArray< uint8 > &ScriptCode)
Public Member Functions inherited from FLinkerTables
bool AnyExportIsInImport (int32 ImportIndex) const
Return if any export is in the import.
bool AnyExportShareOuterWithImport (int32 ImportIndex) const
Return if any export share an outer with the import.
bool DoResourcesShareOutermost (FPackageIndex LinkerIndexLHS, FPackageIndex LinkerIndexRHS) const
Return if two resources share the same outermost.
FORCEINLINE FObjectExport & Exp (FPackageIndex Index)
Check that this Index is non-null and an export and return an import.
FORCEINLINE FObjectExport const & Exp (FPackageIndex Index) const
FORCEINLINE FObjectExport * ExpPtr (FPackageIndex Index)
Return an export for this index.
SIZE_T GetAllocatedSize () const
Returns the amount of memory allocated by this container, not including sizeof(*this).
FName GetClassName (FPackageIndex PackageIndex)
Gets the class name for the specified PackageIndex.
FName GetExportClassName (FPackageIndex PackageIndex)
Gets the class name for the specified index in the export map.
FName GetExportClassName (int32 ExportIdx)
Gets the class name for the specified index in the export map.
FString GetExportFullName (const FString &RootPackagePath, int32 ExportIndex, bool bResolveForcedExports=false)
Return the full name of the UObject represented by the specified export.
FString GetExportPathName (const FString &RootPackagePath, int32 ExportIndex, bool bResolveForcedExports=false)
Return the path name of the UObject represented by the specified export.
FName GetImportClassName (FPackageIndex PackageIndex)
Gets the class name for the specified index in the import map.
FName GetImportClassName (int32 ImportIdx)
Gets the class name for the specified index in the import map.
FString GetImportFullName (FPackageIndex PackageIndex)
Return the full name of the UObject represented by the specified package index.
FString GetImportFullName (int32 ImportIndex)
Return the full name of the UObject represented by the specified import.
FString GetImportPathName (FPackageIndex PackageIndex)
Return the path name of the UObject represented by the specified import.
FString GetImportPathName (int32 ImportIndex)
Return the path name of the UObject represented by the specified import.
FORCEINLINE FObjectImport & Imp (FPackageIndex Index)
Check that this Index is non-null and an import and return an import.
FORCEINLINE FObjectImport const & Imp (FPackageIndex Index) const
FORCEINLINE FObjectResource & ImpExp (FPackageIndex Index)
Check that this Index is non-null and return an import or export.
FORCEINLINE FObjectResource const & ImpExp (FPackageIndex Index) const
Check that this Index is non-null and return an import or export.
FORCEINLINE FObjectResource * ImpExpPtr (FPackageIndex Index)
Return an import or export for this index.
bool ImportIsInAnyExport (int32 ImportIndex) const
Return if the import is in any export.
FORCEINLINE FObjectImport * ImpPtr (FPackageIndex Index)
Return an import for this index.
FPackageIndex ResourceGetOutermost (FPackageIndex LinkerIndex) const
Return the outermost resource package index of the resource pointed by LinkerIndex.
bool ResourceIsIn (FPackageIndex LinkerIndex, FPackageIndex OuterIndex) const
Return if a resource has the specified other resource in its outer chain.
void SerializeSearchableNamesMap (FArchive &Ar)
Serializes the searchable name map.
void SerializeSearchableNamesMap (FStructuredArchive::FSlot Slot)
Public Member Functions inherited from FArchiveUObject
template<class T>
FORCEINLINE FArchive & operator<< (TCheckedObjPtr< T > &Value)
Serializes a UObject wrapped in a TCheckedObjPtr container, using the above operator, and verifies the serialized object is derived from the correct base class, to prevent illegal casting.
Public Member Functions inherited from FArchive
FArchive ()=default
FArchive (const FArchive &)=default
virtual ~FArchive ()
virtual bool AtEnd ()
Returns true if the current location within the backing data storage is at the end, always returns false if there is no storage.
FORCEINLINE FArchive & ByteOrderSerialize (void *V, int32 Length)
Serialize data of Length bytes, taking into account byte swapping if needed.
void ByteSwap (void *V, int32 Length)
Used to do byte swapping on small items.
void ClearError ()
Sets ArIsError to false, this does not clear any CriticalErrors.
virtual bool Close ()
Attempts to close and finalize any handles used for backing data storage, returns true if it succeeded.
FORCEINLINE bool ContainsCode () const
Returns true if this archive contains native or generated code.
FORCEINLINE bool ContainsMap () const
Returns true if this archive contains a ULevel or UWorld object.
FORCEINLINE const ITargetPlatform * CookingTarget () const
Returns the cooking target platform.
virtual void CountBytes (SIZE_T InNum, SIZE_T InMax)
Called to get the computed size from a size-detecting archive after it has finished serializing.
int32 CustomVer (const struct FGuid &Key) const
Queries a custom version from the archive.
FORCEINLINE bool DoDelta () const
Returns true if this archive should handle delta serialization for properties.
FORCEINLINE bool DoIntraPropertyDelta () const
Returns true if this archive should perform delta serialization within properties (e.g.
virtual uint32 EngineNetVer () const
Returns the engine-global network protocol version for this archive.
FORCEINLINE FEngineVersionBase EngineVer () const
Returns the compiled engine version used for this archive.
template<SIZE_T Size>
FORCEINLINE bool FastPathLoad (void *InDest)
virtual void Flush ()
Attempts to finish writing any buffered data to disk/permanent storage.
FORCEINLINE bool ForceByteSwapping () const
Returns true if this archive should always swap bytes, ignoring endian rules.
virtual uint32 GameNetVer () const
Returns the game-specific network protocol version for this archive.
FArchiveState & GetArchiveState ()
Returns the low level archive state for this archive.
const FArchiveState & GetArchiveState () const
virtual FArchive * GetCacheableArchive ()
Returns a pointer to an archive that represents the same data that the current archive covers, but that can be cached and reused later In the case of standard archives, this function will just return a pointer to itself.
FORCEINLINE FArchiveCookContext * GetCookContext ()
virtual const FCustomVersionContainer & GetCustomVersions () const
Gets the custom version numbers for this archive.
FORCEINLINE uint32 GetDebugSerializationFlags () const
Returns the editor-only debug serialization flags.
FORCEINLINE bool GetError () const
virtual FArchiveState & GetInnermostState ()
Returns lowest level archive state, proxy archives will override this.
FORCEINLINE int64 GetMaxSerializeSize () const
Returns the maximum size of data that this archive is allowed to serialize.
virtual const FUObjectMigrationContext * GetMigrationContext () const
When migrating objects, we may need some context as to the intent of the migration during serialization.
FORCEINLINE uint32 GetPortFlags () const
Returns this archive's property serialization modifier flags.
FArchiveSavePackageData * GetSavePackageData ()
FORCEINLINE class FProperty * GetSerializedProperty () const
Gets the property that is currently being serialized.
FORCEINLINE const FArchiveSerializedPropertyChain * GetSerializedPropertyChain () const
Get the raw serialized property chain for this archive.
void GetSerializedPropertyChain (TArray< class FProperty * > &OutProperties) const
Gets the chain of properties that are currently being serialized.
FORCEINLINE bool HasAllPortFlags (uint32 Flags) const
Checks to see if all of the passed in property serialization modifier flags are set.
FORCEINLINE bool HasAnyPortFlags (uint32 Flags) const
Checks to see if any of the passed in property serialization modifier flags are set.
FORCEINLINE bool IsAllowingLazyLoading () const
Returns true if this archive sould allow lazy loading of bulk / secondary data.
FORCEINLINE bool IsByteSwapping ()
Returns true if data larger than 1 byte should be swapped to deal with endian mismatches.
FORCEINLINE bool IsCooking () const
Checks whether the archive is used for cooking.
FORCEINLINE bool IsCountingMemory () const
Returns true if this archive is counting memory, normally CountBytes is called to get the size.
FORCEINLINE bool IsCriticalError () const
Returns true if this archive contains critical errors that cannot be recovered from.
FORCEINLINE bool IsError () const
Returns true if this archive contains errors, which means that further serialization is generally not safe.
bool IsFilterEditorOnly () const
Indicates whether this archive is filtering editor-only on save or contains data that had editor-only content stripped.
FORCEINLINE bool IsForcingUnicode () const
Returns true if this archive wants to always save strings in UTF16 format even if they are ANSI characters.
FORCEINLINE bool IsIgnoringArchetypeRef () const
Returns true if this archive should ignore archetype references for structs and classes.
FORCEINLINE bool IsIgnoringClassGeneratedByRef () const
Returns true if this archive should ignore the ClassGeneratedBy reference in UClass.
FORCEINLINE bool IsIgnoringClassRef () const
Returns true if this archive should ignore the Class reference in UObject.
FORCEINLINE bool IsIgnoringOuterRef () const
Returns true if this archive should ignore the Outer reference in UObject.
FORCEINLINE bool IsLoading () const
Returns true if this archive is for loading data.
FORCEINLINE bool IsLoadingFromCookedPackage () const
Returns true if this archive is loading from a cooked package.
FORCEINLINE constexpr bool IsMigratingRemoteObjects () const
Returns true if this Archive is migrating remote object.
FORCEINLINE bool IsModifyingWeakAndStrongReferences () const
Returns true if this archive should modify/search weak object references as well as strong ones.
FORCEINLINE bool IsNetArchive () const
Whether or not this archive is serializing data being sent/received by the netcode.
FORCEINLINE bool IsObjectReferenceCollector () const
Returns true if this archive is only looking for UObject references.
FORCEINLINE bool IsPersistent () const
Returns true if this archive is saving or loading data destined for persistent storage and should skip transient data.
virtual bool IsProxyOf (FArchive *InOther) const
Determine if the given archive is a valid "child" of this archive.
bool IsSaveGame () const
Indicates whether this archive is saving or loading game state.
FORCEINLINE bool IsSaving () const
Returns true if this archive is for saving data, this can also be a pre-save preparation archive.
FORCEINLINE bool IsSerializingDefaults () const
Returns true if this archive is currently serializing class/struct default values.
FORCEINLINE bool IsTextFormat () const
Returns true if this archive serializes to a structured text format.
FORCEINLINE bool IsTransacting () const
Returns true if this archive is transacting, which is used to keep track of changes to objects for things like the editor undo system.
FORCEINLINE int32 LicenseeUEVer () const
Returns the licensee-specific version used for this archive, will be 0 by default.
template<typename FmtType, typename... Types>
void Logf (const FmtType &Fmt, Types... Args)
virtual void MarkSearchableName (const TObjectPtr< const UObject > &TypeObject, const FName &ValueName) const
Called to register a reference to a specific name value, of type TypeObject (UEnum or UStruct normally).
template<class T>
FORCEINLINE FArchive & operator<< (TCheckedObjPtr< T > &Value)
Serializes a UObject wrapped in a TCheckedObjPtr container, using the above operator, and verifies the serialized object is derived from the correct base class, to prevent illegal casting.
FArchive & operator= (const FArchive &ArchiveToCopy)=default
virtual void PopFileRegionType ()
virtual void PushFileRegionType (EFileRegionType Type)
Called whilst cooking to provide file region hints to the cooker.
FORCEINLINE bool RequiresLocalizationGather () const
Returns true if this archive contains data required to be gathered for localization.
virtual void Reset ()
Resets all of the base archive members.
virtual void ResetCustomVersions ()
Resets the custom version numbers for this archive.
virtual void SerializeBits (void *V, int64 LengthBits)
void SerializeCompressed (void *V, int64 Length, FName CompressionFormatCannotChange, ECompressionFlags Flags=COMPRESS_NoFlags, bool bTreatBufferAsFileReader=false)
Serializes and compresses/ uncompresses data.
void SerializeCompressedNew (void *V, int64 Length)
Serializes and compresses/ uncompresses data with default compressor choices.
void SerializeCompressedNew (void *V, int64 Length, FName CompressionFormatToEncode, FName CompressionFormatToDecodeOldV1Files, ECompressionFlags Flags=COMPRESS_NoFlags, bool bTreatBufferAsFileReader=false, int64 *OutPartialReadLength=nullptr)
Serializes and compresses/ uncompresses data.
virtual void SerializeInt (uint32 &Value, uint32 Max)
virtual void SerializeIntPacked (uint32 &Value)
Packs int value into bytes of 7 bits with 8th bit for 'more'.
virtual void SerializeIntPacked64 (uint64 &Value)
void SetArchiveState (const FArchiveState &InState)
Modifies current archive state, can be used to override flags.
void SetByteSwapping (bool Enabled)
Toggle byte order swapping.
virtual bool SetCompressionMap (TArray< FCompressedChunk > *CompressedChunks, ECompressionFlags CompressionFlags)
Sets mapping from offsets/ sizes that are going to be used for seeking and serialization to what is actually stored on disk.
void SetCriticalError ()
Sets the archiver IsCriticalError and IsError to true.
void SetCustomVersion (const struct FGuid &Key, int32 Version, FName FriendlyName)
Sets a specific custom version.
virtual void SetCustomVersions (const FCustomVersionContainer &CustomVersionContainer)
Sets the custom version numbers for this archive.
virtual void SetEngineNetVer (const uint32 InEngineNetVer)
Sets the archive engine network version.
virtual void SetEngineVer (const FEngineVersionBase &InVer)
Sets the archive engine version.
void SetError ()
Sets ArIsError to true.
virtual void SetFilterEditorOnly (bool InFilterEditorOnly)
Sets a flag indicating that this archive needs to filter editor-only content.
virtual void SetForceUnicode (bool bInForceUnicode)
Sets whether this archive wants to force saving as Unicode.
virtual void SetGameNetVer (const uint32 InGameNetVer)
Sets the archive game network version.
virtual void SetIsLoading (bool bInIsLoading)
Sets whether this archive is for loading data.
virtual void SetIsLoadingFromCookedPackage (bool bInIsLoadingFromCookedPackage)
Sets whether the archive is loading from a cooked package.
virtual void SetIsPersistent (bool bInIsPersistent)
Sets whether this archive is to persistent storage.
virtual void SetIsSaving (bool bInIsSaving)
Sets whether this archive is for saving data.
virtual void SetIsTextFormat (bool bInIsTextFormat)
Sets whether this archive is in text format.
virtual void SetIsTransacting (bool bInIsTransacting)
Sets whether this archive is for transacting.
virtual void SetLicenseeUEVer (int32 InVer)
Sets the archive licensee version number.
void SetMigratingRemoteObjects (bool bMigrating)
If set true, this archive is migrating remote objects.
void SetPortFlags (uint32 InPortFlags)
Sets the archive's property serialization modifier flags.
void SetSavePackageData (FArchiveSavePackageData *InSavePackageData)
Marks that this archive is one of the archives used by SavePackage, and provides access to data and functions used only during savepackage, such as the cook data bundle for information about the cook being conducted (if applicable) and writing build dependencies for assetregistry.
void SetShouldSkipUpdateCustomVersion (bool bShouldSkip)
If set true, UsingCurrentVersion will not query the version registry to get the latest version data for the key if the version key is already set in the local container.
virtual void SetUEVer (FPackageFileVersion InVer)
Sets the archive version number.
virtual void SetUseUnversionedPropertySerialization (bool bInUseUnversioned)
Sets whether tagged property serialization should be replaced by faster unversioned serialization.
virtual void SetWantBinaryPropertySerialization (bool bInWantBinaryPropertySerialization)
Sets whether this archive wants binary property serialization.
FORCEINLINE bool ShouldSkipBulkData () const
Returns true if this archive should ignore bulk data.
FORCEINLINE bool ShouldSkipCompilingAssets () const
Returns true if it is allowed to skip serialization on assets still being compiled to avoid waiting unless strictly necessary.
virtual bool ShouldSkipProperty (const FProperty *InProperty) const
Checks whether the archive wants to skip the property independent of the other flags.
FORCEINLINE bool ShouldSkipUpdateCustomVersion () const
Returns true if this Archive does not update the custom version data for a given key if has already been set previously in the local custom versions container.
void StartSerializingDefaults ()
Sets a flag indicating that this archive is currently serializing class/struct defaults.
void StopSerializingDefaults ()
Indicate that this archive is no longer serializing class/struct defaults.
void ThisContainsCode ()
Sets a flag indicating that this archive contains native or generated code.
void ThisContainsMap ()
Sets a flag indicating that this archive contains a ULevel or UWorld object.
void ThisRequiresLocalizationGather ()
Sets a flag indicating that this archive contains data required to be gathered for localization.
UE_DEPRECATED (5.5, "Use GetCookContext or CookingTarget or GetSavePackageData") FArchiveCookData *GetCookData()
UE_DEPRECATED (5.5, "Use SetSavePackageData.") void SetCookData(FArchiveCookData *InCookData)
FORCEINLINE FPackageFileVersion UEVer () const
Returns the global engine serialization version used for this archive.
virtual bool UseToResolveEnumerators () const
Checks whether the archive is used to resolve out-of-date enum indexes If function returns true, the archive should be called only for objects containing user defined enum.
FORCEINLINE bool UseUnversionedPropertySerialization () const
Returns true if tagged property serialization should be replaced by faster unversioned serialization.
virtual void UsingCustomVersion (const struct FGuid &Guid)
Registers the custom version to the archive.
FORCEINLINE bool WantBinaryPropertySerialization () const
Returns true if this archive wants properties to be serialized in binary form instead of safer but slower tagged form.
Static Public Member Functions
static void AddGameNameRedirect (const FName OldName, const FName NewName)
Add a new redirect from old game name to new game name for ImportMap.
static void AddKnownMissingPackage (FName PackageName)
Register that a package is now known missing and that it should silence future warnings/issues.
static void CreateActiveRedirectsMap (const FString &GEngineIniName)
Add redirects to FLinkerLoad static map.
static FLinkerLoad * CreateLinker (FUObjectSerializeContext *LoadContext, UPackage *Parent, const FPackagePath &PackagePath, uint32 LoadFlags, FArchive *InLoader=nullptr, const FLinkerInstancingContext *InstancingContext=nullptr)
Creates and returns a FLinkerLoad object.
static FLinkerLoad * FindExistingLinkerForPackage (const UPackage *Package)
Looks for an existing linker for the given package, without trying to make one if it doesn't exist.
static FName FindNewNameForClass (FName OldClassName, bool bIsInstance)
Utility functions to query the object name redirects list for the current name for a class.
static FName FindNewNameForEnum (FName OldEnumName)
Utility functions to query the enum name redirects list for the current name for an enum.
static FName FindNewNameForStruct (FName OldStructName)
Utility functions to query the struct name redirects list for the current name for a struct.
static FString FindNewPathNameForClass (const FString &OldClassNameOrPathName, bool bIsInstance)
Utility functions to query the object name redirects list for the current name for a class.
static TArray< FName > FindPreviousNamesForClass (const FString &CurrentClassPath, bool bIsInstance)
Utility functions to query the object name redirects list for previous names for a class.
static TArray< FString > FindPreviousPathNamesForClass (const FString &CurrentClassPath, bool bIsInstance, bool bIncludeShortNames=false)
Utility functions to query the object name redirects list for previous names for a class.
static FORCEINLINE int32 GetHashBucket (FName Object)
static bool GetPreloadingEnabled ()
static void InvalidateExport (UObject *OldObject, bool bHideGarbageObjects=true)
Invalidates the future loading of a specific object, so that subsequent loads will fail This is used to invalidate sub objects of a replaced object that may no longer be valid.
static bool IsImportLazyLoadEnabled ()
Determines if imports can be lazily loaded.
static bool IsKnownMissingPackage (FName PackageName)
Utility functions to check the list of known missing packages and silence any warnings that may have occurred on load.
static void OnNewFileAdded (const FString &Filename)
static void OnPakFileMounted (const IPakFile &PakFile)
static void PRIVATE_ForceLoadAllDependencies (UPackage *Package)
Wraps a call to the package linker's ResolveAllImports().
static void PRIVATE_PatchNewObjectIntoExport (UObject *OldObject, UObject *NewObject, FUObjectSerializeContext *InLoadContext=nullptr, bool bHideGarbageObjects=true)
Replaces OldObject's entry in its linker with NewObject, so that all subsequent loads of OldObject will return NewObject.
static bool RemoveKnownMissingPackage (FName PackageName)
Register that a package is no longer known missing and that it should be searched for again in the future.
static void SetPreloadingEnabled (bool bEnabled)
static FORCEINLINE ELinkerType::Type StaticType ()
static bool TryGetPreloadedLoader (const FPackagePath &InPackagePath, FOpenPackageResult &OutResult)
Static Public Member Functions inherited from FArchiveUObject
static FArchive & SerializeLazyObjectPtr (FArchive &Ar, FLazyObjectPtr &Value)
static FArchive & SerializeObjectPtr (FArchive &Ar, FObjectPtr &Value)
static FArchive & SerializeSoftObjectPath (FArchive &Ar, FSoftObjectPath &Value)
static FArchive & SerializeSoftObjectPtr (FArchive &Ar, FSoftObjectPtr &Value)
static FArchive & SerializeWeakObjectPtr (FArchive &Ar, FWeakObjectPtr &Value)
Data Fields
void * AsyncRoot
The async package associated with this linker.
bool bForceSimpleIndexToObject
bool bHaveImportsBeenVerified
Indicates whether the imports for this loader have been verified.
bool bIsAsyncLoader
True if Loader is FAsyncArchive.
bool bLockoutLegacyOperations
TSet< FBulkData * > BulkDataLoaders
Bulk data that use the FLinkerLoad to track the state of the file on disk.
UE::FMutex BulkDataMutex
Used when accessing BulkDataLoaders/EditorBulkDataLoaders to ensure thread safety.
FName ClassPackage
TSet< UE::Serialization::FEditorBulkData * > EditorBulkDataLoaders
TUniquePtr< int32[]> ExportHash
FName FName FPackageIndex ExportOuterIndex
TArray< FExternalReadCallback > ExternalReadDependencies
List of external read dependencies that must be finished to load this package.
uint32 LoadFlags
Flags determining loading behavior.
FName FName ObjectName
TArray< FPackageIndex > PreloadDependencies
List of imports and exports that must be serialized before other exports...all packed together, see FirstExportDependency.
UObject * TemplateForGetArchetypeFromLoader
Data Fields inherited from FLinker
TArray< FObjectDataResource > DataResourceMap
Raw/bulk data references.
bool FilterClientButNotServer
If true, filter out exports that are for clients but not servers.
bool FilterServerButNotClient
If true, filter out exports that are for servers but not clients.
TArray< FGatherableTextData > GatherableTextDataMap
Gatherable text data contained within this package.
UPackage * LinkerRoot
The top-level UPackage object for the package associated with this linker.
TArray< FNameEntryId > NameMap
Names used by objects contained within this package.
TArray< FSoftObjectPath > SoftObjectPathList
List of SoftObjectPath contained in this package,.
FPackageFileSummary Summary
Table of contents for this package's file.
Data Fields inherited from FLinkerTables
TArray< FCellExport > CellExportMap
The list of FCellExports found in the package.
TArray< FCellImport > CellImportMap
The list of FCellImports found in the package.
TArray< TArray< FPackageIndex > > DependsMap
List of dependency lists for each export.
TArray< FObjectExport > ExportMap
The list of FObjectExports found in the package.
TArray< FObjectImport > ImportMap
The list of FObjectImports found in the package.
TMap< FPackageIndex, TArray< FName > > SearchableNamesMap
List of Searchable Names, by object containing them.
TArray< FName > SoftPackageReferenceList
List of packages that are soft referenced by this package.
Data Fields inherited from FArchive
FFastPathLoadBuffer * ActiveFPLB
uint8 ArAllowLazyLoading: 1
Whether to allow lazy loading of bulk/secondary data.
uint8 ArContainsCode: 1
Quickly tell if an archive contains script code.
uint8 ArContainsMap: 1
Used to determine whether FArchive contains a level or world.
const struct FCustomPropertyListNode * ArCustomPropertyList
Custom property list attribute.
uint32 ArDebugSerializationFlags
Custom serialization modifier flags can be used for anything.
UE_DEPRECATED(5.6, "Public access to ArRequiresLocalizationGather has been deprecated - please use Ar.RequiresLocalizationGather() and Ar.ThisRequiresLocalizationGather() for getting and setting respectively.") uint8 ArRequiresLocalizationGather uint8 ArForceByteSwapping: 1
Used to determine whether FArchive contains data required to be gathered for localization.
uint8 ArIgnoreArchetypeRef: 1
If true, we will not serialize archetype references for structs and classes.
uint8 ArIgnoreClassGeneratedByRef: 1
If true, we will not serialize ClassGeneratedBy reference in UClass.
uint8 ArIgnoreClassRef: 1
If true, UObject::Serialize will skip serialization of the Class property.
uint8 ArIgnoreOuterRef: 1
If true, we will not serialize the Outer reference in UObject.
uint8 ArIsCountingMemory: 1
Whether this archive is counting memory.
uint8 ArIsFilterEditorOnly: 1
Whether editor only properties are being filtered from the archive (or has been filtered).
uint8 ArIsModifyingWeakAndStrongReferences: 1
Whether a reference collector is modifying the references and wants both weak and strong ones.
uint8 ArIsNetArchive: 1
Whether or not this archive is sending/receiving network data.
uint8 ArIsObjectReferenceCollector: 1
Whether this archive only cares about serializing object references.
uint8 ArIsSaveGame: 1
Whether this archive is saving/loading game state.
int64 ArMaxSerializeSize
Max size of data that this archive is allowed to serialize.
uint8 ArMergeOverrides: 1
Set to false if OverriddenProperties should be cleared at the beginning of SerializeVersionedTaggedProperties.
uint8 ArNoDelta: 1
If true, do not perform delta serialization of properties.
uint8 ArNoIntraPropertyDelta: 1
If true, do not perform delta serialization within properties (e.g.
uint32 ArPortFlags
Modifier flags that be used when serializing UProperties.
uint8 ArPreserveArrayElements: 1
Set TRUE to stop arrays from being cleared before they're loaded.
int32 ArSerializingDefaults
Whether we are currently serializing defaults.
uint8 ArShouldSkipBulkData: 1
Whether bulk data serialization should be skipped or not.
uint8 ArUseCustomPropertyList: 1
Set TRUE to use the custom property list attribute for serialization.
FFastPathLoadBuffer InlineFPLB
Static Public Attributes
static constexpr int32 ExportHashCount = 256
Hash table for exports.
Protected Types
enum ELinkerStatus { LINKER_Failed = 0 , LINKER_Loaded = 1 , LINKER_TimedOut = 2 }
Linker loading status.
enum EVerifyResult { VERIFY_Failed = 0 , VERIFY_Success = 1 , VERIFY_Redirected = 2 }
Verify result.
Protected Member Functions
FLinkerLoad (UPackage *InParent, const FPackagePath &PackagePath, uint32 InLoadFlags, FLinkerInstancingContext InstancingContext=FLinkerInstancingContext())
Private constructor, passing arguments through from CreateLinker.
ELinkerStatus CreateLoader (TFunction< void()> &&InSummaryReadyCallback)
Creates loader used to serialize content.
FArchive * GetLoader () const
void SetLoader (FArchive *InLoader, bool bInLoaderNeedsEngineVersionChecks)
ELinkerStatus Tick (float InTimeLimit, bool bInUseTimeLimit, bool bInUseFullTimeLimit, TMap< TPair< FName, FPackageIndex >, FPackageIndex > *ObjectNameWithOuterToExportMap)
Ticks an in-flight linker and spends InTimeLimit seconds on creation.
Protected Member Functions inherited from FArchive
virtual void SerializeBool (bool &D)
Serializes a Boolean value from or into an archive.
void SetShouldSkipCompilingAssets (bool Enabled)
Set whether or not it is allowed to skip serialization on assets still being compiled to avoid waiting unless strictly necessary.
Private Member Functions
ELinkerStatus ApplyInstancingContext ()
virtual void AttachBulkData (UE::Serialization::FEditorBulkData *BulkData) override
virtual void AttachBulkData (UObject *Owner, FBulkData *BulkData) override
Attaches/ associates the passed in bulk data object with the linker.
void BadNameIndexError (int32 NameIndex)
void BadSoftObjectPathError (int32 SoftObjIndex)
UObject * CreateExport (int32 Index)
UObject * CreateExportAndPreload (int32 ExportIndex, bool bForcePreload=false)
Creates export and preload if requested.
ELinkerStatus CreateExportHash ()
0 *00 0C0r0e0ates the export hash.
UObject * CreateImport (int32 Index)
bool DeferExportCreation (const int32 ExportIndex, UObject *Outer)
Stubs in a ULinkerPlaceholderExportObject for the specified export (if one is required, meaning: the export's LoadClass is not fully formed).
bool DeferPotentialCircularImport (const int32 ImportIndex)
Determines if the specified import should be deferred.
void DetachAllBulkData (bool bEnsureBulkDataIsLoaded)
Detaches all attached bulk data objects.
virtual void DetachBulkData (FBulkData *BulkData, bool bEnsureBulkDataIsLoaded) override
Detaches the passed in bulk data object from the linker.
virtual void DetachBulkData (UE::Serialization::FEditorBulkData *BulkData, bool bEnsureBulkDataIsLoaded) override
void DetachExport (int32 i)
bool DoesSavedClassMatchActualClass (int32 ExportIndex) const
Returns a bool indicating that the class the object (specified by ExportIndex) was saved with matches the class that it was created with.
void FinalizeBlueprint (UClass *LoadClass)
Takes the supplied serialized class and serializes in its CDO, then regenerates both.
ELinkerStatus FinalizeCreation (TMap< TPair< FName, FPackageIndex >, FPackageIndex > *ObjectNameWithOuterToExportMap)
Finalizes linker creation, adding linker to loaders array and potentially verifying imports.
int32 FindCDOExportIndex (UClass *LoadClass)
Iterates through this linker's ExportMap, looking for the corresponding class-default-object for the specified class (assumes that the supplied class is an export itself, making this a Blueprint package).
void FindDirectChildExportsFromExportTable (int32 ExportIndex, TArray< int32 > &OutChildExports)
Helper for recursion in PRIVATE_ForceLoadAllDependencies; searches the Export table to find all children of the given ExportIndex.
ELinkerStatus FindExistingExports ()
Finds existing exports in memory and matches them up with this linker.
FLinkerLoad * FindExistingLinkerForImport (int32 ImportIndex) const
Attempts to lookup and return the corresponding FLinkerLoad object for the specified import WITHOUT invoking a load, or continuing to load the import package (will only return one if it has already been created... could still be in the process of loading).
UObject * FindImport (UClass *ImportClass, UObject *ImportOuter, const TCHAR *Name)
Finds import, tries to fall back to dynamic class if the object could not be found.
void FixupDuplicateExports ()
Nulls duplicated exports and fixes indexes in ExportMap to point to original objects instead of duplicates.
ELinkerStatus FixupImportMap ()
Fixes up the import map, performing remapping for backward compatibility and such.
void FixupSoftObjectPathForInstancedPackage (FSoftObjectPath &InOutSoftObjectPath)
Remaps SoftObjectPaths using InstancingContextRemap.
bool ForceRegenerateClass (UClass *ImportClass)
Sometimes we have to instantiate an export object that is of an imported type, and sometimes in those scenarios (thanks to cyclic dependencies) the type class could be a Blueprint type that is half resolved.
const UObject * GetCurrentObjectAtIndex (FPackageIndex ObjectIndex) const
Helper that returns the current object (import or export) specified by package index.
UClass * GetExportLoadClass (int32 ExportIndex)
Utility function for easily retrieving the specified export's UClass.
bool HasPerformedFullExportResolvePass ()
bool HasUnresolvedDependencies () const
Query method to help catch recursive behavior.
UObject * IndexToObject (FPackageIndex Index)
void InvalidateExportIndex (int32 ExportIndex, bool bHideGarbageObjects)
Recursive helper for InvalidateExport.
bool IsContextInstanced () const
bool IsExportBeingResolved (int32 ExportIndex)
Checks to see if an export (or one up its outer chain) is currently in the middle of having its class dependency force-regenerated.
bool IsImportNative (const int32 ImportIndex) const
Determines if the specified import belongs to a native "compiled in" package (as opposed to an asset-file package).
bool IsPackageReferenceAllowed (UPackage *InPackage)
Validate if the current linker may reference a certain package Checks if the reference to a certain package from this linker is legal if that package isn't externally referenceable (i.e private outiside its plugin)
bool IsSoftObjectRemappingEnabled () const
bool IsSuppressableBlueprintImportError (int32 ImportIndex) const
Determines if the Object Import error should be suppressed.
bool IsTimeLimitExceeded (const TCHAR *CurrentTask, int32 Granularity=1)
Returns whether the time limit allotted has been exceeded, if enabled.
virtual FArchive & operator<< (FField *&Value)
Serializes a Field value from or into this archive.
virtual FORCEINLINE FArchive & operator<< (FLazyObjectPtr &LazyObjectPtr) override
Serializes a lazy object pointer value from or into this archive.
virtual FORCEINLINE FArchive & operator<< (FName &Name) override
Serializes an FName value from or into this archive.
virtual FArchive & operator<< (FObjectPtr &ObjectPtr) override
Serializes a wrapped object pointer value from or into this archive.
virtual FArchive & operator<< (FSoftObjectPath &Value) override
Serializes soft object paths from or into this archive.
virtual FArchive & operator<< (FSoftObjectPtr &Value) override
Serializes asset pointer from or into this archive.
virtual FArchive & operator<< (FText &Value)
Serializes an FText value from or into an archive.
virtual FArchive & operator<< (FWeakObjectPtr &Value) override
Serializes FWeakObjectPtr value from or into this archive.
template<class T>
FORCEINLINE FArchive & operator<< (TCheckedObjPtr< T > &Value)
Serializes a UObject wrapped in a TCheckedObjPtr container, using the above operator, and verifies the serialized object is derived from the correct base class, to prevent illegal casting.
virtual FArchive & operator<< (UObject *&Object) override
Serializes an UObject value from or into this archive.
virtual void PopDebugDataString () override
virtual void PopSerializedProperty (class FProperty *InProperty, const bool bIsEditorOnlyProperty) override
Pop a property that was previously being serialized off the property stack.
ELinkerStatus PopulateInstancingContext ()
Generate remapping for the instancing context if this is an instanced package.
virtual FORCEINLINE bool Precache (int64 PrecacheOffset, int64 PrecacheSize) override
Hint the archive that the region starting at passed in offset and spanning the passed in size is going to be read soon and should be precached.
ELinkerStatus ProcessPackageSummary (TMap< TPair< FName, FPackageIndex >, FPackageIndex > *ObjectNameWithOuterToExportMap)
virtual void PushDebugDataString (const FName &DebugData) override
Debug stack storage if you want to add data to the archive for usage further down the serialization stack this should be used in conjunction with the FScopeAddDebugData struct.
virtual void PushSerializedProperty (class FProperty *InProperty, const bool bIsEditorOnlyProperty) override
Push a property that is currently being serialized onto the property stack.
bool RegenerateBlueprintClass (UClass *LoadClass, UObject *ExportObject)
Regenerates/Refreshes a blueprint class.
ELinkerStatus RelocateReferences ()
void ReplaceExportIndexes (const FPackageIndex &OldIndex, const FPackageIndex &NewIndex)
Replaces all instances of OldIndex in ExportMap with NewIndex.
void ResetDeferredLoadingState ()
void ResetStatusInfo ()
Sets the basic linker archive info.
void ResolveAllImports ()
Iterates through the ImportMap and calls CreateImport() for every entry, creating/loading each import as we go.
void ResolvedDeferredSubobjects (ULinkerPlaceholderExportObject *OwningPlaceholder)
Helper function to recursively resolve placeholders that were waiting for their outer.
void ResolveDeferredDependencies (UStruct *LoadStruct)
Combs the ImportMap for any imports that were deferred, and then creates them (via CreateImport).
void ResolveDeferredExports (UClass *LoadClass)
Combs the ExportMap for any stubbed in ULinkerPlaceholderExportObjects, and finalizes the real export's class before actually creating it (exports are deferred when their class isn't fully formed at the time CreateExport() is called).
int32 ResolveDependencyPlaceholder (class FLinkerPlaceholderBase *Placeholder, UClass *ReferencingClass=nullptr, const FName ObjectPath=NAME_None)
Loads the import that the Placeholder was initially stubbed in for (NOTE: this could cause recursive behavior), and then replaces all known placeholder references with the proper class.
void ResolvePlaceholder (ULinkerPlaceholderExportObject *Placeholder)
Called when a class is loaded and its now safe to load deferred instances.
virtual FORCEINLINE void Seek (int64 InPos) override
Attempts to set the current offset into backing data storage, this will do nothing if there is no storage.
void Serialize (FArchive &Ar)
I/O function.
virtual FORCEINLINE void Serialize (void *V, int64 Length) override
void SerializeBulkMeta (UE::BulkData::Private::FBulkMetaData &Meta, FBulkDataCookedIndex &CookedIndex, int64 &DuplicateSerialOffset, int32 ElementSize)
ELinkerStatus SerializeDataResourceMap ()
Serializes the data resource map.
ELinkerStatus SerializeDependsMap ()
Serializes the depends map.
ELinkerStatus SerializeExportMap ()
Serializes the export map.
ELinkerStatus SerializeImportMap ()
Serializes the import map.
ELinkerStatus SerializeNameMap ()
Serializes the name map.
ELinkerStatus SerializePackageFileSummary ()
Start the process of serializing the package file summary if needed.
ELinkerStatus SerializePackageFileSummaryInternal ()
Does the actual serialization of the package file summary.
ELinkerStatus SerializePackageTrailer ()
Serializes the header for the package trailer, allowing us to identify the payloads of the package.
ELinkerStatus SerializePreloadDependencies ()
Serializes the preload dependencies.
ELinkerStatus SerializeSoftObjectPathList ()
Serializes the soft object map.
virtual void SetDebugSerializationFlags (uint32 InCustomFlags) override
Sets the archives custom serialization modifier flags (nothing to do with PortFlags or Custom versions)
void SetPackagePath (const FPackagePath &PackagePath)
Set the packagepath being loaded.
virtual void SetSerializedProperty (FProperty *InProperty) override
Overrides the property that is currently being serialized.
virtual void SetSerializedPropertyChain (const FArchiveSerializedPropertyChain *InSerializedPropertyChain, class FProperty *InSerializedPropertyOverride=nullptr) override
Set the raw serialized property chain for this archive, optionally overriding the serialized property too (or null to use the head of the property chain)
bool ShouldCreateThrottledSlowTask () const
Test whether we should report progress or not based on how recently we last created a progress task.
FORCEINLINE bool ShouldReportProgress () const
Test whether we should report progress or not.
virtual FORCEINLINE int64 Tell () override
Returns the current location within the backing data storage, which can possibly be passed to Seek later to restore a read/write location.
virtual FORCEINLINE int64 TotalSize () override
Returns total size of the backing data storage.
UClass * TryCreatePlaceholderClassForExport (int32 ExportIndex)
Utility function to create a placeholder class for the specified export.
UClass * TryCreatePlaceholderClassImport (int32 ImportIndex)
Utility function for callers to try and create a placeholder class object in the specified import slot if it represents a class object.
ELinkerStatus UpdateFromPackageFileSummary ()
Updates the linker, loader and root package with data from the package file summary.
bool VerifyImportInner (const int32 ImportIndex, FString &WarningSuffix)
Safely verify that an import in the ImportMap points to a good object.
Static Private Member Functions
static FLinkerLoad * CreateLinkerAsync (FUObjectSerializeContext *LoadContext, UPackage *Parent, const FPackagePath &PackagePath, uint32 LoadFlags, const FLinkerInstancingContext *InstancingContext, TFunction< void()> &&InSummaryReadyCallback)
Creates a FLinkerLoad object for async creation.
static UObject * FindImportFast (UClass *ImportClass, UObject *ImportOuter, FName Name, bool bFindObjectbyName=false)
Finds import, tries to fall back to dynamic class if the object could not be found.
Private Attributes
bool bDetachedLoader
Tracks if DetachLoader has been called or not.
bool bExportsDuplicatesFixed: 1
Check to avoid multiple export duplicate fixups in case we don't save asset.
bool bFixupExportMapDone:1
Used for ActiveClassRedirects functionality.
bool bHasAppliedInstancingContext: 1
Whether we already applied the instancing context to the soft object list.
bool bHasConstructedExportsReaders:1
Whether we have already constructed the exports readers.
bool bHasFinishedInitialization:1
Whether we are already fully initialized.
bool bHasFixedUpImportMap:1
Whether we already fixed up import map.
bool bHasFoundExistingExports:1
Whether we already matched up existing exports.
bool bHasPopulatedInstancingContext:1
Whether we already populated the instancing context.
bool bHasRelocatedReferences:1
Whether we already relocated references.
bool bHasSerializedPackageFileSummary:1
Whether we already serialized the package file summary.
bool bHasSerializedPackageTrailer: 1
Whether we already serialized the package trailer.
bool bHasSerializedPreloadDependencies:1
Whether we already serialized preload dependencies.
bool bIsDestroyingLoader
True if the linker is currently deleting loader.
bool bIsGatheringDependencies:1
Whether we are gathering dependencies, can be used to streamline VerifyImports, etc.
bool bIsLoadingToPropertyBagObject: 1
Set when the loader is serializing to a property bag placeholder object.
bool bIsPackageRelocated: 1
Cache if the package is relocated or not.
bool bIsSerializingScriptProperties: 1
TRUE when the loader is actively serializing an object's script properties data.
bool bLoaderNeedsEngineVersionChecks: 1
Whether the loader needs version and correctness checks (see OpenReadPackage)
bool bTimeLimitExceeded:1
Whether time limit is/ has been exceeded in current/ last tick.
bool bUseFullTimeLimit:1
Whether to use the full time limit, even if we're blocked on I/O.
bool bUseTimeLimit:1
Whether to use a time limit for async linker creation.
int32 DependsMapIndex
Current index into depends map, used by async linker creation for spreading out serializing dependsmap entries.
int32 ExportHashIndex
Current index into export hash map, used by async linker creation for spreading out hashing exports.
int32 ExportMapIndex
Current index into export map, used by async linker creation for spreading out serializing exportmap entries.
TArray< FStructuredArchiveChildReader * > ExportReaders
int32 GatherableTextDataMapIndex
Current index into gatherable text data map, used by async linker creation for spreading out serializing text entries.
int32 ImportMapIndex
Current index into import map, used by async linker creation for spreading out serializing importmap entries.
TSet< int32 > ImportsToVerifyOnCreate
Set of imports that require additional verification at creation time.
FLinkerInstancingContext InstancingContext
The linker instancing context.
int32 IsTimeLimitExceededCallCount
Call count of IsTimeLimitExceeded.
FArchive * Loader
The archive that actually reads the raw data from disk.
FScopedSlowTask * LoadProgressScope
Feedback scope that is created to house the slow task of an asynchronous linker load.
int32 OwnerThread
Id of the thread that created this linker.
FPackagePath PackagePath
The packagepath being loaded.
TUniquePtr< UE::FPackageTrailer > PackageTrailer
The trailer for the package.
int32 SoftObjectPathListIndex
Current index into soft object path list, used by async linker creation for spreading out serializing soft object path entries.
FStructuredArchive * StructuredArchive
Structured archive interface.
FArchiveFormatterType * StructuredArchiveFormatter
TOptional< FStructuredArchive::FRecord > StructuredArchiveRootRecord
double TickStartTime
Time at begin of Tick function.
float TimeLimit
Current time limit to use if bUseTimeLimit is true.
Static Private Attributes
static bool bActiveRedirectsMapInitialized
Makes sure the deprecated active redirects inis have been read.
static bool bPreloadingEnabled
static FName NAME_LoadErrors
Friends
class FAsyncLoadingThread2
struct FAsyncPackage
struct FAsyncPackage2
struct FResolvingExportTracker
FORCEINLINE friend FArchive & operator<< (FArchive &Ar, ANSICHAR &Value)
Serializes an ANSICHAR value from or into an archive.
FORCEINLINE friend FArchive & operator<< (FArchive &Ar, bool &D)
FORCEINLINE friend FArchive & operator<< (FArchive &Ar, double &Value)
Serializes a double precision floating point value from or into an archive.
FORCEINLINE friend FArchive & operator<< (FArchive &Ar, float &Value)
Serializes a single precision floating point value from or into an archive.
FArchive & operator<< (FArchive &Ar, FString &Value)
Serializes an FString value from or into an archive.
FORCEINLINE friend FArchive & operator<< (FArchive &Ar, int16 &Value)
Serializes a signed 16-bit integer value from or into an archive.
FORCEINLINE friend FArchive & operator<< (FArchive &Ar, int32 &Value)
Serializes a signed 32-bit integer value from or into an archive.
FArchive & operator<< (FArchive &Ar, int64 &Value)
Serializes a signed 64-bit integer value from or into an archive.
FORCEINLINE friend FArchive & operator<< (FArchive &Ar, int8 &Value)
Serializes a signed 8-bit integer value from or into an archive.
FORCEINLINE friend FArchive & operator<< (FArchive &Ar, uint16 &Value)
Serializes an unsigned 16-bit integer value from or into an archive.
FORCEINLINE friend FArchive & operator<< (FArchive &Ar, uint32 &Value)
Serializes an unsigned 32-bit integer value from or into an archive.
FORCEINLINE friend FArchive & operator<< (FArchive &Ar, uint64 &Value)
Serializes a unsigned 64-bit integer value from or into an archive.
FORCEINLINE friend FArchive & operator<< (FArchive &Ar, uint8 &Value)
Serializes an unsigned 8-bit integer value from or into an archive.
FORCEINLINE friend FArchive & operator<< (FArchive &Ar, UTF32CHAR &Value)
Serializes a UTF32CHAR value from or into an archive.
FORCEINLINE friend FArchive & operator<< (FArchive &Ar, WIDECHAR &Value)
Serializes a WIDECHAR value from or into an archive.
class UObject
class UPackageMap
Additional Inherited Members
Static Protected Member Functions inherited from FArchive
static void LinkProxy (FArchiveState &Inner, FArchiveState &Proxy)
static void UnlinkProxy (FArchiveState &Inner, FArchiveState &Proxy)
Detailed Description
Definition at line 118 of file LinkerLoad.h.
Member Enumeration Documentation
ELinkerStatus
enum FLinkerLoad::ELinkerStatus protected
Linker loading status.
Enumerator
LINKER_Failed
Error occured when loading.
LINKER_Loaded
Operation completed successfully.
LINKER_TimedOut
Operation took more time than allowed.
Definition at line 133 of file LinkerLoad.h.
EVerifyResult
enum FLinkerLoad::EVerifyResult protected
Verify result.
Enumerator
VERIFY_Failed
Error occured when verifying import (can be fatal).
VERIFY_Success
Verify completed successfully.
VERIFY_Redirected
Verify completed successfully and followed a redirector.
Definition at line 144 of file LinkerLoad.h.
Constructor & Destructor Documentation
~FLinkerLoad()
virtual FLinkerLoad::~FLinkerLoad () virtual
FLinkerLoad()
FLinkerLoad::FLinkerLoad (UPackage * InParent, const FPackagePath & PackagePath, uint32 InLoadFlags, FLinkerInstancingContext InstancingContext = FLinkerInstancingContext()) protected
Private constructor, passing arguments through from CreateLinker.
Parameters
Parent Parent object to load into, can be NULL (most likely case)
PackagePath Path of the package data to load
LoadFlags Load flags determining behavior
InstancingContext The instancing context for remapping imports if needed.
References InstancingContext, and PackagePath.
Referenced by CreateLinker(), CreateLinkerAsync(), FindExistingLinkerForImport(), and FindExistingLinkerForPackage().
Member Function Documentation
AddGameNameRedirect()
void FLinkerLoad::AddGameNameRedirect (const FName OldName, const FName NewName) static
Add a new redirect from old game name to new game name for ImportMap.
AddKnownMissingPackage()
void FLinkerLoad::AddKnownMissingPackage (FName PackageName) static
Register that a package is now known missing and that it should silence future warnings/issues.
References PackageName.
ApplyInstancingContext()
ELinkerStatus FLinkerLoad::ApplyInstancingContext () private
AttachBulkData() [1/2]
virtual void FLinkerLoad::AttachBulkData (UE::Serialization::FEditorBulkData * BulkData) override private virtual
Reimplemented from FArchive.
References BulkData.
AttachBulkData() [2/2]
virtual void FLinkerLoad::AttachBulkData (UObject * Owner, FBulkData * BulkData) override private virtual
Attaches/ associates the passed in bulk data object with the linker.
Parameters
Owner UObject owning the bulk data
BulkData Bulk data object to associate
Reimplemented from FArchive.
References BulkData, Owner, and UObject.
AttachExternalReadDependency()
virtual bool FLinkerLoad::AttachExternalReadDependency (FExternalReadCallback & ReadCallback) override virtual
Adds external read dependency.
Returns
true if dependency has been added
Reimplemented from FArchive.
BadNameIndexError()
void FLinkerLoad::BadNameIndexError (int32 NameIndex) private
Referenced by operator<<().
BadSoftObjectPathError()
void FLinkerLoad::BadSoftObjectPathError (int32 SoftObjIndex) private
BuildPathName()
void FLinkerLoad::BuildPathName (FString & OutPathName, FPackageIndex ExportIndex) const
Builds a string containing the full path for a resource in the export table.
Parameters
OutPathName [out] Will contain the full path for the resource
ResourceIndex Index of a resource in the export table
References BuildPathName().
Referenced by BuildPathName().
CreateActiveRedirectsMap()
void FLinkerLoad::CreateActiveRedirectsMap (const FString & GEngineIniName) static
Add redirects to FLinkerLoad static map.
CreateExport()
UObject * FLinkerLoad::CreateExport (int32 Index) private
References UObject.
CreateExportAndPreload()
UObject * FLinkerLoad::CreateExportAndPreload (int32 ExportIndex, bool bForcePreload = false) private
Creates export and preload if requested.
Parameters
Index Index of the export in export map.
bForcePreload Whether to explicitly call Preload (serialize) right away instead of being called from EndLoad().
Returns
Created object.
References UObject.
CreateExportHash()
ELinkerStatus FLinkerLoad::CreateExportHash () private
0 *00 0C0r0e0ates the export hash.
CreateImport()
UObject * FLinkerLoad::CreateImport (int32 Index) private
References UObject.
CreateImportClassAndPackage()
bool FLinkerLoad::CreateImportClassAndPackage (FName ClassName, FName PackageName, FPackageIndex & ClassIdx, FPackageIndex & PackageIdx)
Attempts to find the index for the given class object in the import list and adds it + its package if it does not exist.
References PackageName.
CreateLinker()
FLinkerLoad * FLinkerLoad::CreateLinker (FUObjectSerializeContext * LoadContext, UPackage * Parent, const FPackagePath & PackagePath, uint32 LoadFlags, FArchive * InLoader = nullptr, const FLinkerInstancingContext * InstancingContext = nullptr) static
Creates and returns a FLinkerLoad object.
Parameters
Parent Parent object to load into, can be NULL (most likely case)
PackagePath Path of the package on disk to load
LoadFlags Load flags determining behavior
InLoader Loader archive override
InstancingContext Context to remap package name when loading a package on disk into a package with a different name
Returns
new FLinkerLoad object for Parent/ Filename
References FArchive::FArchive(), FLinkerLoad(), InstancingContext, LoadFlags, PackagePath, and Parent.
CreateLinkerAsync()
FLinkerLoad * FLinkerLoad::CreateLinkerAsync (FUObjectSerializeContext * LoadContext, UPackage * Parent, const FPackagePath & PackagePath, uint32 LoadFlags, const FLinkerInstancingContext * InstancingContext, TFunction< void()> && InSummaryReadyCallback) static private
Creates a FLinkerLoad object for async creation.
Tick has to be called manually till it returns true in which case the returned linker object has finished the async creation process.
Parameters
Parent Parent object to load into, can be NULL (most likely case)
PackagePath Path of the package data to load
LoadFlags Load flags determining behavior
InstancingContext Context to remap package name when loading a package on disk into a package with a different name
Returns
new FLinkerLoad object for Parent/ Filename
References FLinkerLoad(), InstancingContext, LoadFlags, PackagePath, and Parent.
CreateLoader()
ELinkerStatus FLinkerLoad::CreateLoader (TFunction< void()> && InSummaryReadyCallback) protected
Creates loader used to serialize content.
DeferExportCreation()
bool FLinkerLoad::DeferExportCreation (const int32 ExportIndex, UObject * Outer) private
Stubs in a ULinkerPlaceholderExportObject for the specified export (if one is required, meaning: the export's LoadClass is not fully formed).
This should rarely happen, but has been seen in cyclic Blueprint scenarios involving Blueprinted components.
Parameters
ExportIndex Identifies the export you want deferred.
Outer The outer of the export to potentially defer
Returns
True if the export has been deferred (and should not be loaded).
References Outer, and UObject.
DeferPotentialCircularImport()
bool FLinkerLoad::DeferPotentialCircularImport (const int32 ImportIndex) private
Determines if the specified import should be deferred.
If so, it will instantiate a placeholder object in its place.
Parameters
ImportIndex An index into this linker's ImportMap, specifying which import to check.
Returns
True if the specified import was deferred, other wise false (it is ok to load it).
DestroyLoader()
void FLinkerLoad::DestroyLoader ()
Detach()
void FLinkerLoad::Detach ()
Detaches linker from bulk data and exports and removes itself from array of loaders.
DetachAllBulkData()
void FLinkerLoad::DetachAllBulkData (bool bEnsureBulkDataIsLoaded) private
Detaches all attached bulk data objects.
Parameters
bEnsureBulkDataIsLoaded Whether to ensure that the bulk data is loaded before detaching
DetachBulkData() [1/2]
virtual void FLinkerLoad::DetachBulkData (FBulkData * BulkData, bool bEnsureBulkDataIsLoaded) override private virtual
Detaches the passed in bulk data object from the linker.
Parameters
BulkData Bulk data object to detach
bEnsureBulkDataIsLoaded Whether to ensure that the bulk data is loaded before detaching
Reimplemented from FArchive.
References BulkData.
DetachBulkData() [2/2]
virtual void FLinkerLoad::DetachBulkData (UE::Serialization::FEditorBulkData * BulkData, bool bEnsureBulkDataIsLoaded) override private virtual
Reimplemented from FArchive.
References BulkData.
DetachExport()
void FLinkerLoad::DetachExport (int32 i) private
DetachExports()
void FLinkerLoad::DetachExports ()
Only detaches the linker from its exports and the reset their cached state in the linker without touching bulkdata or underlying loader.
DetachLoader()
void FLinkerLoad::DetachLoader ()
Detaches all bulkdata currently attached to the FLinkerLoad followed by destroying the internal loader.
This is a fairly dangerous method to call as it will leave the FLinkerLoad in a state where using it as a FArchive will cause an assert/crash. It is intended as a short/medium term fix to an internal engine issue and will be deprecated as soon as possible.
DoesSavedClassMatchActualClass()
bool FLinkerLoad::DoesSavedClassMatchActualClass (int32 ExportIndex) const private
Returns a bool indicating that the class the object (specified by ExportIndex) was saved with matches the class that it was created with.
Most commonly this returns false when native user (non-coreuobject) code has required a specific class of a specific type
FinalizeBlueprint()
void FLinkerLoad::FinalizeBlueprint (UClass * LoadClass) private
Takes the supplied serialized class and serializes in its CDO, then regenerates both.
Parameters
LoadClass The loaded blueprint class (assumes that it has been fully loaded/serialized).
FinalizeCreation()
ELinkerStatus FLinkerLoad::FinalizeCreation (TMap< TPair< FName, FPackageIndex >, FPackageIndex > * ObjectNameWithOuterToExportMap) private
Finalizes linker creation, adding linker to loaders array and potentially verifying imports.
FindCDOExportIndex()
int32 FLinkerLoad::FindCDOExportIndex (UClass * LoadClass) private
Iterates through this linker's ExportMap, looking for the corresponding class-default-object for the specified class (assumes that the supplied class is an export itself, making this a Blueprint package).
Parameters
LoadClass The Blueprint class that this linker is in charge of loading (also belonging to its ExportMap).
Returns
An index into this linker's ExportMap array (INDEX_NONE if the CDO wasn't found).
FindDirectChildExportsFromExportTable()
void FLinkerLoad::FindDirectChildExportsFromExportTable (int32 ExportIndex, TArray< int32 > & OutChildExports) private
Helper for recursion in PRIVATE_ForceLoadAllDependencies; searches the Export table to find all children of the given ExportIndex.
Does not search recursively - does not find children of children.
FindExistingExport()
UObject * FLinkerLoad::FindExistingExport (int32 ExportIndex)
Before loading a persistent object from disk, this function can be used to discover the object in memory.
This could happen in the editor when you save a package (which destroys the linker) and then play PIE, which would cause the Linker to be recreated. However, the objects are still in memory, so there is no need to reload them.
Parameters
ExportIndex The index of the export to hunt down
Returns
The object that was found, or null if it wasn't found
References FindExistingExport(), and UObject.
Referenced by FindExistingExport().
FindExistingExports()
ELinkerStatus FLinkerLoad::FindExistingExports () private
Finds existing exports in memory and matches them up with this linker.
This is required for PIE to work correctly and also for script compilation as saving a package will reset its linker and loading will reload/ replace existing objects without a linker.
FindExistingImport()
UObject * FLinkerLoad::FindExistingImport (int32 ImportIndex)
Parameters
ImportIndex The index of the import to hunt down
Returns
The object that was found, or null if it wasn't found
References FindExistingImport(), and UObject.
Referenced by FindExistingImport().
FindExistingLinkerForImport()
FLinkerLoad * FLinkerLoad::FindExistingLinkerForImport (int32 ImportIndex) const private
Attempts to lookup and return the corresponding FLinkerLoad object for the specified import WITHOUT invoking a load, or continuing to load the import package (will only return one if it has already been created... could still be in the process of loading).
Parameters
ImportIndex Specifies the import that you would like a linker for.
Returns
The imports associated linker (null if it hasn't been created yet).
References FLinkerLoad().
FindExistingLinkerForPackage()
FLinkerLoad * FLinkerLoad::FindExistingLinkerForPackage (const UPackage * Package) static
Looks for an existing linker for the given package, without trying to make one if it doesn't exist.
References FLinkerLoad(), FindExistingLinkerForPackage(), and Package.
Referenced by FindExistingLinkerForPackage().
FindImport() [1/3]
bool FLinkerLoad::FindImport (FPackageIndex OuterIndex, FName ObjectName, FPackageIndex & OutObjectIndex)
Locates package index for a given name in an outer.
References ObjectName.
FindImport() [2/3]
bool FLinkerLoad::FindImport (FStringView FullObjectPath, FPackageIndex & OutObjectIndex)
Finds an import given the full object path as a string.
Note: since imports are stored in an array, it needs to linearly search for each import in the object path.
FindImport() [3/3]
UObject * FLinkerLoad::FindImport (UClass * ImportClass, UObject * ImportOuter, const TCHAR * Name) private
Finds import, tries to fall back to dynamic class if the object could not be found.
References Name, and UObject.
FindImportClassAndPackage()
bool FLinkerLoad::FindImportClassAndPackage (FName ClassName, FPackageIndex & ClassIdx, FPackageIndex & PackageIdx)
Locates the class adjusted index and its package adjusted index for a given class name in the import map.
FindImportFast()
UObject * FLinkerLoad::FindImportFast (UClass * ImportClass, UObject * ImportOuter, FName Name, bool bFindObjectbyName = false) static private
Finds import, tries to fall back to dynamic class if the object could not be found.
References Name, and UObject.
FindImportPackage()
bool FLinkerLoad::FindImportPackage (FName PackageName, FPackageIndex & PackageIdx)
Locates package index for a UPackage import.
References PackageName.
FindNewNameForClass()
FName FLinkerLoad::FindNewNameForClass (FName OldClassName, bool bIsInstance) static
Utility functions to query the object name redirects list for the current name for a class.
Parameters
OldClassName An old class name, without path
Returns
Current name of the class. It will be None if no redirect found
FindNewNameForEnum()
FName FLinkerLoad::FindNewNameForEnum (FName OldEnumName) static
Utility functions to query the enum name redirects list for the current name for an enum.
Parameters
OldEnumName An old enum name, without path
Returns
Current full path of the enum. It will be None if no redirect found
FindNewNameForStruct()
FName FLinkerLoad::FindNewNameForStruct (FName OldStructName) static
Utility functions to query the struct name redirects list for the current name for a struct.
Parameters
OldStructName An old struct name, without path
Returns
Current full path of the struct. It will be None if no redirect found
FindNewPathNameForClass()
FString FLinkerLoad::FindNewPathNameForClass (const FString & OldClassNameOrPathName, bool bIsInstance) static
Utility functions to query the object name redirects list for the current name for a class.
Parameters
OldClassNameOrPathName An old class name or pathname
Returns
Current full path of the class. It will be empty if no redirect found
FindPreviousNamesForClass()
TArray< FName > FLinkerLoad::FindPreviousNamesForClass (const FString & CurrentClassPath, bool bIsInstance) static
Utility functions to query the object name redirects list for previous names for a class.
Parameters
CurrentClassPath The current name of the class, with a full path
bIsInstance If true, we're an instance, so check instance only maps as well
Returns
Names without path of all classes that were redirected to this name. Empty if none found.
FindPreviousPathNamesForClass()
TArray< FString > FLinkerLoad::FindPreviousPathNamesForClass (const FString & CurrentClassPath, bool bIsInstance, bool bIncludeShortNames = false) static
Utility functions to query the object name redirects list for previous names for a class.
Parameters
CurrentClassPath The current name of the class, with a full path
bIsInstance If true, we're an instance, so check instance only maps as well
bIncludeShortNames If true, also include short names without a package
Returns
Full object paths of all classes that were redirected to this name. Empty if none found.
FinishExternalReadDependencies()
bool FLinkerLoad::FinishExternalReadDependencies (double TimeLimit)
Finalizes external dependencies till time limit is exceeded.
Returns
true if all dependencies are finished, false otherwise
References TimeLimit.
FixupDuplicateExports()
void FLinkerLoad::FixupDuplicateExports () private
Nulls duplicated exports and fixes indexes in ExportMap to point to original objects instead of duplicates.
FixupExportMap()
ELinkerStatus FLinkerLoad::FixupExportMap ()
Allows object instances to be converted to other classes upon loading a package.
FixupImportMap()
ELinkerStatus FLinkerLoad::FixupImportMap () private
Fixes up the import map, performing remapping for backward compatibility and such.
FixupSoftObjectPathForInstancedPackage()
void FLinkerLoad::FixupSoftObjectPathForInstancedPackage (FSoftObjectPath & InOutSoftObjectPath) private
Remaps SoftObjectPaths using InstancingContextRemap.
FlushCache()
virtual void FLinkerLoad::FlushCache () override virtual
Flush Loader Cache.
Reimplemented from FArchive.
ForceBlueprintFinalization()
virtual void FLinkerLoad::ForceBlueprintFinalization () override virtual
Inform the archive that blueprint finalization is pending.
Reimplemented from FArchive.
ForceRegenerateClass()
bool FLinkerLoad::ForceRegenerateClass (UClass * ImportClass) private
Sometimes we have to instantiate an export object that is of an imported type, and sometimes in those scenarios (thanks to cyclic dependencies) the type class could be a Blueprint type that is half resolved.
To avoid having to re-instance objects on load, we have to ensure that the class is fully regenerated before we spawn any instances of it. That's where this function comes in. It will make sure that the specified class is fully loaded, finalized, and regenerated.
NOTE: be wary, if called in the wrong place, then this could introduce nasty infinite recursion!
Parameters
ImportClass The class you want to make sure is fully regenerated.
Returns
True if the class could be regenerated (false if it didn't have its linker set).
GetArchetypeFromLoader()
virtual UObject * FLinkerLoad::GetArchetypeFromLoader (const UObject * Obj) override virtual
Called to retrieve the archetype from the event driven loader.
If this returns null, then call GetArchetype yourself.
Reimplemented from FArchive.
References GetArchetypeFromLoader(), and UObject.
Referenced by GetArchetypeFromLoader().
GetArchiveName()
virtual FString FLinkerLoad::GetArchiveName () const override virtual
Returns the name of the Archive.
Useful for getting the name of the package a struct or object is in when a loading error occurs.
This is overridden for the specific Archive Types
Reimplemented from FArchive.
GetAsyncLoader()
FORCEINLINE FAsyncArchive * FLinkerLoad::GetAsyncLoader () inline
Definition at line 175 of file LinkerLoad.h.
References bIsAsyncLoader, FORCEINLINE, and Loader.
GetCurrentObjectAtIndex()
const UObject * FLinkerLoad::GetCurrentObjectAtIndex (FPackageIndex ObjectIndex) const private
Helper that returns the current object (import or export) specified by package index.
Does not attempt to resolve the object. See related function: IndexToObject.
References UObject.
GetDebugName()
virtual FString FLinkerLoad::GetDebugName () const inline override virtual
Returns a descriptor of the PackagePath this Linker is reading from or writing to, usable for an identifier in warning and log messages.
Reimplemented from FLinker.
Definition at line 180 of file LinkerLoad.h.
References GetPackagePath().
GetExportClassPackage()
FName FLinkerLoad::GetExportClassPackage (int32 i)
GetExportLoadClass()
UClass * FLinkerLoad::GetExportLoadClass (int32 ExportIndex) private
Utility function for easily retrieving the specified export's UClass.
Parameters
ExportIndex Index of the export you want a class for.
Returns
The class that the specified export's ClassIndex references.
GetHashBucket()
FORCEINLINE int32 FLinkerLoad::GetHashBucket (FName Object) inline static
Definition at line 303 of file LinkerLoad.h.
References ExportHashCount, FORCEINLINE, GetTypeHash(), and Object.
GetInstancingContext()
FORCEINLINE const FLinkerInstancingContext & FLinkerLoad::GetInstancingContext () const inline
Definition at line 191 of file LinkerLoad.h.
References FORCEINLINE, and InstancingContext.
GetLinker()
virtual FLinker * FLinkerLoad::GetLinker () inline override virtual
If this archive is a FLinkerLoad or FLinkerSave, returns a pointer to the FLinker portion.
Reimplemented from FArchive.
Definition at line 623 of file LinkerLoad.h.
References FLinker::FLinker().
GetLoader()
FArchive * FLinkerLoad::GetLoader () const inline protected
Definition at line 254 of file LinkerLoad.h.
References FArchive::FArchive(), and Loader.
GetLoader_Unsafe()
FArchive * FLinkerLoad::GetLoader_Unsafe () const inline
Access the underlying archive.
Note that if this is a text archive, the loader will point to a generic text file, and not a binary archive as in the past. General access to the underlying file format is discouraged and should only be done after checking that the linker package is what you expect it to be (i.e. !IsTextFormat())
Definition at line 262 of file LinkerLoad.h.
References FArchive::FArchive(), and Loader.
GetOwnerThreadId()
FORCEINLINE int32 FLinkerLoad::GetOwnerThreadId () const inline
Returns ID of the thread that created this linker.
Definition at line 615 of file LinkerLoad.h.
References FORCEINLINE, and OwnerThread.
GetPackagePath()
const FPackagePath & FLinkerLoad::GetPackagePath () const inline
Get the PackagePath being loaded.
For linkers created from LoadPackage this will be a mounted and extension-specified path, but it may be unmounted and unspecified for other linkers
Definition at line 186 of file LinkerLoad.h.
References PackagePath.
Referenced by GetDebugName().
GetPackageTrailer()
const UE::FPackageTrailer * FLinkerLoad::GetPackageTrailer () const inline
Definition at line 196 of file LinkerLoad.h.
References PackageTrailer.
GetPreloadingEnabled()
bool FLinkerLoad::GetPreloadingEnabled () static
HasAnyObjectsPendingLoad()
bool FLinkerLoad::HasAnyObjectsPendingLoad () const
Checks if the linker has any objects in the export table that require loading.
HasFinishedInitialization()
FORCEINLINE bool FLinkerLoad::HasFinishedInitialization () const inline
Returns whether linker has finished (potentially) async initialization.
Returns
true if initialized, false if pending.
Definition at line 609 of file LinkerLoad.h.
References bHasFinishedInitialization, and FORCEINLINE.
HasLoader()
bool FLinkerLoad::HasLoader () const inline
Definition at line 267 of file LinkerLoad.h.
References Loader.
HasPerformedFullExportResolvePass()
bool FLinkerLoad::HasPerformedFullExportResolvePass () private
HasUnresolvedDependencies()
bool FLinkerLoad::HasUnresolvedDependencies () const private
Query method to help catch recursive behavior.
When this returns true, a dependency placeholder is in the middle of being resolved by ResolveDependencyPlaceholder(). Used so a nested call would know to complete that placeholder before continuing.
Returns
True if ResolveDependencyPlaceholder() is being ran on a placeholder that has yet to be resolved.
IndexToObject()
UObject * FLinkerLoad::IndexToObject (FPackageIndex Index) private
References UObject.
InvalidateExport()
void FLinkerLoad::InvalidateExport (UObject * OldObject, bool bHideGarbageObjects = true) static
Invalidates the future loading of a specific object, so that subsequent loads will fail This is used to invalidate sub objects of a replaced object that may no longer be valid.
References InvalidateExport(), and UObject.
Referenced by InvalidateExport().
InvalidateExportIndex()
void FLinkerLoad::InvalidateExportIndex (int32 ExportIndex, bool bHideGarbageObjects) private
Recursive helper for InvalidateExport.
Invalidates an export even if it does not have a UObject* in memory, and recursively invalidates child exports.
IsBlueprintFinalizationPending()
bool FLinkerLoad::IsBlueprintFinalizationPending () const
Query method to help handle recursive behavior.
When this returns true, this linker is in the middle of, or is about to call FinalizeBlueprint() (for a blueprint class somewhere in the current callstack). Needed when we get to finalizing a sub-class before we've finished finalizing its super (so we know we need to finish finalizing the super first).
Returns
True if FinalizeBlueprint() is currently being ran (or about to be ran) for an export (Blueprint) class.
IsContextInstanced()
bool FLinkerLoad::IsContextInstanced () const private
IsDestroyingLoader()
FORCEINLINE bool FLinkerLoad::IsDestroyingLoader () const inline
Definition at line 282 of file LinkerLoad.h.
References bIsDestroyingLoader, and FORCEINLINE.
IsExportBeingResolved()
bool FLinkerLoad::IsExportBeingResolved (int32 ExportIndex) private
Checks to see if an export (or one up its outer chain) is currently in the middle of having its class dependency force-regenerated.
This function is meant to help avoid unnecessary recursion, as ForceRegenerateClass() does nothing itself to stave off infinite recursion.
Parameters
ExportIndex Identifies the export you're about to call CreateExport() on.
Returns
True if the specified export's class (or one up its outer chain) is currently being force-regenerated.
IsImportLazyLoadEnabled()
bool FLinkerLoad::IsImportLazyLoadEnabled () inline static
Determines if imports can be lazily loaded.
This relies on compile-time enabling of UE_WITH_OBJECT_HANDLE_LATE_RESOLVE from ObjectHandle.h as well as other factors.
Returns
true if imports can be lazily loaded
Definition at line 388 of file LinkerLoad.h.
Referenced by RemoveKnownMissingPackage().
IsImportNative()
bool FLinkerLoad::IsImportNative (const int32 ImportIndex) const private
Determines if the specified import belongs to a native "compiled in" package (as opposed to an asset-file package).
Recursive if the specified import is not a package itself.
Parameters
ImportIndex An index into the ImportMap, defining the import you wish to check.
Returns
True if the specified import comes from (or is) a "compiled in" package, otherwise false (it is an asset import).
IsKnownMissingPackage()
bool FLinkerLoad::IsKnownMissingPackage (FName PackageName) static
Utility functions to check the list of known missing packages and silence any warnings that may have occurred on load.
Returns
true if the provided package is in the KnownMissingPackage list
References PackageName.
IsPackageReferenceAllowed()
bool FLinkerLoad::IsPackageReferenceAllowed (UPackage * InPackage) private
Validate if the current linker may reference a certain package Checks if the reference to a certain package from this linker is legal if that package isn't externally referenceable (i.e private outiside its plugin)
Parameters
InPackage the package to validate
Returns
true if the package can be referenced from this linker
IsPackageRelocated()
bool FLinkerLoad::IsPackageRelocated () const inline
Definition at line 202 of file LinkerLoad.h.
References bIsPackageRelocated.
IsSoftObjectRemappingEnabled()
bool FLinkerLoad::IsSoftObjectRemappingEnabled () const private
IsSuppressableBlueprintImportError()
bool FLinkerLoad::IsSuppressableBlueprintImportError (int32 ImportIndex) const private
Determines if the Object Import error should be suppressed.
Parameters
ImportIndex Internal index into this linker's ImportMap, references the import to check for suppression.
Returns
True if the import error should be suppressed
IsTimeLimitExceeded()
bool FLinkerLoad::IsTimeLimitExceeded (const TCHAR * CurrentTask, int32 Granularity = 1) private
Returns whether the time limit allotted has been exceeded, if enabled.
Parameters
CurrentTask description of current task performed for logging spilling over time limit
Granularity Granularity on which to check timing, useful in cases where FPlatformTime::Seconds is slow (e.g. PC)
Returns
true if time limit has been exceeded (and is enabled), false otherwise (including if time limit is disabled)
IsValidPackageIndex()
bool FLinkerLoad::IsValidPackageIndex (FPackageIndex InIndex)
Test whether the given package index is a valid import or export in this package.
LoadAllObjects()
void FLinkerLoad::LoadAllObjects (bool bForcePreload)
Loads all objects in package.
Parameters
bForcePreload Whether to explicitly call Preload (serialize) right away instead of being called from EndLoad()
LoadAndDetachAllBulkData()
void FLinkerLoad::LoadAndDetachAllBulkData ()
Detaches linker from bulk data.
MarkScriptSerializationEnd()
virtual void FLinkerLoad::MarkScriptSerializationEnd (const UObject * Obj) override virtual
Called when an object stops serializing property data using script serialization.
Reimplemented from FArchive.
References MarkScriptSerializationEnd(), and UObject.
Referenced by MarkScriptSerializationEnd().
MarkScriptSerializationStart()
virtual void FLinkerLoad::MarkScriptSerializationStart (const UObject * Obj) override virtual
Called when an object begins serializing property data using script serialization.
Reimplemented from FArchive.
References MarkScriptSerializationStart(), and UObject.
Referenced by MarkScriptSerializationStart().
OnNewFileAdded()
void FLinkerLoad::OnNewFileAdded (const FString & Filename) static
References Filename.
OnPakFileMounted()
void FLinkerLoad::OnPakFileMounted (const IPakFile & PakFile) static
operator<<() [1/10]
virtual FArchive & FArchive::operator<< (FField *& Value) inline private virtual
Serializes a Field value from or into this archive.
This operator can be implemented by sub-classes that wish to serialize UObject instances.
Parameters
Value The value to serialize.
Returns
This instance.
Reimplemented from FArchiveUObject.
Definition at line 26 of file Archive.h.
operator<<() [2/10]
virtual FORCEINLINE FArchive & FLinkerLoad::operator<< (FLazyObjectPtr & Value) inline override private virtual
Serializes a lazy object pointer value from or into this archive.
Most of the time, FLazyObjectPtrs are serialized as UObject*, but some archives need to override this.
Parameters
Value The value to serialize.
Returns
This instance.
Reimplemented from FArchiveUObject.
Definition at line 1091 of file LinkerLoad.h.
References FArchive::FArchive(), Ar, FORCEINLINE, ID, and LazyObjectPtr.
operator<<() [3/10]
virtual FORCEINLINE FArchive & FLinkerLoad::operator<< (FName & Value) inline override private virtual
Serializes an FName value from or into this archive.
This operator can be implemented by sub-classes that wish to serialize FName instances.
Parameters
Value The value to serialize.
Returns
This instance.
Reimplemented from FArchiveUObject.
Definition at line 1106 of file LinkerLoad.h.
References FArchive::FArchive(), Ar, BadNameIndexError(), FName::CreateFromDisplayId(), FName, FORCEINLINE, Name, FLinker::NameMap, and FArchive::SetCriticalError().
operator<<() [4/10]
virtual FArchive & FLinkerLoad::operator<< (FObjectPtr & Value) override private virtual
Serializes a wrapped object pointer value from or into this archive.
Most of the time, FObjectPtrs are serialized as UObject*, but some archives need to override this.
Parameters
Value The value to serialize.
Returns
This instance.
Reimplemented from FArchiveUObject.
References FArchive::FArchive().
operator<<() [5/10]
virtual FArchive & FLinkerLoad::operator<< (FSoftObjectPath & Value) override private virtual
Serializes soft object paths from or into this archive.
Parameters
Value Soft object path to serialize.
Returns
This instance.
Reimplemented from FArchiveUObject.
References FArchive::FArchive(), and Value.
operator<<() [6/10]
virtual FArchive & FArchiveUObject::operator<< (FSoftObjectPtr & Value) inline override private virtual
Serializes asset pointer from or into this archive.
Most of the time, FSoftObjectPtr are serialized as UObject *, but some archives need to override this.
Parameters
Value The asset pointer to serialize.
Returns
This instance.
Reimplemented from FArchiveUObject.
Definition at line 31 of file ArchiveUObject.h.
operator<<() [7/10]
virtual FArchive & FArchive::operator<< (FText & Value) private virtual
Serializes an FText value from or into an archive.
Parameters
Ar The archive to serialize from or to.
Value The value to serialize.
Reimplemented from FArchiveUObject.
References FArchive::FArchive(), FLinker::FLinker(), and UObject.
operator<<() [8/10]
virtual FArchive & FArchiveUObject::operator<< (FWeakObjectPtr & Value) inline override private virtual
Serializes FWeakObjectPtr value from or into this archive.
This operator can be implemented by sub-classes that wish to serialize FWeakObjectPtr instances.
Parameters
Value The value to serialize.
Returns
This instance.
Reimplemented from FArchiveUObject.
Definition at line 33 of file ArchiveUObject.h.
operator<<() [9/10]
template<class T> FORCEINLINE FArchive & FArchive::operator<< (TCheckedObjPtr< T > & Value) inline private
Serializes a UObject wrapped in a TCheckedObjPtr container, using the above operator, and verifies the serialized object is derived from the correct base class, to prevent illegal casting.
Parameters
Value The value to serialize.
Returns
This instance.
Definition at line 26 of file Archive.h.
operator<<() [10/10]
virtual FArchive & FLinkerLoad::operator<< (UObject *& Value) override private virtual
Serializes an UObject value from or into this archive.
This operator can be implemented by sub-classes that wish to serialize UObject instances.
Parameters
Value The value to serialize.
Returns
This instance.
Reimplemented from FArchiveUObject.
References FArchive::FArchive(), Object, and UObject.
PopDebugDataString()
virtual void FLinkerLoad::PopDebugDataString () inline override private virtual
Reimplemented from FArchive.
Definition at line 551 of file LinkerLoad.h.
References Loader, and FArchive::PopDebugDataString().
PopSerializedProperty()
virtual void FLinkerLoad::PopSerializedProperty (class FProperty * InProperty, const bool bIsEditorOnlyProperty) inline override private virtual
Pop a property that was previously being serialized off the property stack.
Parameters
InProperty Pointer to the property that was previously being serialized
bIsEditorOnlyProperty True if the property is editor only (call FProperty::IsEditorOnlyProperty to work this out, as the archive can't since it can't access CoreUObject types)
Reimplemented from FArchive.
Definition at line 1148 of file LinkerLoad.h.
References Loader, and FArchive::PopSerializedProperty().
PopulateInstancingContext()
ELinkerStatus FLinkerLoad::PopulateInstancingContext () private
Generate remapping for the instancing context if this is an instanced package.
Precache()
virtual FORCEINLINE bool FLinkerLoad::Precache (int64 PrecacheOffset, int64 PrecacheSize) inline override private virtual
Hint the archive that the region starting at passed in offset and spanning the passed in size is going to be read soon and should be precached.
The function returns whether the precache operation has completed or not which is an important hint for code knowing that it deals with potential async I/O. The archive is free to either not implement this function or only partially precache so it is required that given sufficient time the function will return true. Archives not based on async I/O should always return true.
This function will not change the current archive position.
Parameters
PrecacheOffset Offset at which to begin precaching.
PrecacheSize Number of bytes to precache
Returns
false if precache operation is still pending, true otherwise
Reimplemented from FArchive.
Definition at line 1031 of file LinkerLoad.h.
References bDetachedLoader, checkf, FORCEINLINE, Loader, and TEXT.
Preload()
void FLinkerLoad::Preload (UObject * Object) override virtual
Serialize the object data for the specified object from the unreal package file.
Loads any additional resources required for the object to be in a valid state to receive the loaded data, such as the object's Outer, Class, or ObjectArchetype.
When this function exits, Object is guaranteed to contain the data stored that was stored on disk.
Parameters
Object The object to load data for. If the data for this object isn't stored in this FLinkerLoad, routes the call to the appropriate linker. Data serialization is skipped if the object has already been loaded (as indicated by the RF_NeedLoad flag not set for the object), so safe to call on objects that have already been loaded. Note that this function assumes that Object has already been initialized against its template object. If Object is a UClass and the class default object has already been created, calls Preload for the class default object as well.
Reimplemented from FArchive.
References Object, Preload(), and UObject.
Referenced by Preload().
PRIVATE_ForceLoadAllDependencies()
void FLinkerLoad::PRIVATE_ForceLoadAllDependencies (UPackage * Package) static
Wraps a call to the package linker's ResolveAllImports().
Parameters
Package The package whose imports you want all loaded.
WARNING!!! This function shouldn't be used carelessly, and serves as a hacky entrypoint to FLinkerLoad's privates. It should only be used at very specific times, and in very specific cases. If you're unsure, DON'T TRY TO USE IT!!!
References Package, and PRIVATE_ForceLoadAllDependencies().
Referenced by PRIVATE_ForceLoadAllDependencies().
PRIVATE_PatchNewObjectIntoExport() [1/2]
void FLinkerLoad::PRIVATE_PatchNewObjectIntoExport (int32 OldExportIndex, UObject * NewObject, FUObjectSerializeContext * InLoadContext = nullptr, bool bHideGarbageObjects = true)
References NewObject(), PRIVATE_PatchNewObjectIntoExport(), and UObject.
PRIVATE_PatchNewObjectIntoExport() [2/2]
void FLinkerLoad::PRIVATE_PatchNewObjectIntoExport (UObject * OldObject, UObject * NewObject, FUObjectSerializeContext * InLoadContext = nullptr, bool bHideGarbageObjects = true) static
Replaces OldObject's entry in its linker with NewObject, so that all subsequent loads of OldObject will return NewObject.
This is used to update instanced components that were serialized out, but regenerated during compile-on-load
OldObject will be consigned to oblivion, and NewObject will take its place.
WARNING!!! This function is potentially very dangerous! It should only be used at very specific times, and in very specific cases. If you're unsure, DON'T TRY TO USE IT!!!
References NewObject(), PRIVATE_PatchNewObjectIntoExport(), and UObject.
Referenced by PRIVATE_PatchNewObjectIntoExport(), and PRIVATE_PatchNewObjectIntoExport().
ProcessPackageSummary()
ELinkerStatus FLinkerLoad::ProcessPackageSummary (TMap< TPair< FName, FPackageIndex >, FPackageIndex > * ObjectNameWithOuterToExportMap) private
PushDebugDataString()
virtual void FLinkerLoad::PushDebugDataString (const FName & DebugData) inline override private virtual
Debug stack storage if you want to add data to the archive for usage further down the serialization stack this should be used in conjunction with the FScopeAddDebugData struct.
Reimplemented from FArchive.
Definition at line 544 of file LinkerLoad.h.
References Loader, and FArchive::PushDebugDataString().
PushSerializedProperty()
virtual void FLinkerLoad::PushSerializedProperty (class FProperty * InProperty, const bool bIsEditorOnlyProperty) inline override private virtual
Push a property that is currently being serialized onto the property stack.
Parameters
InProperty Pointer to the property that is currently being serialized
bIsEditorOnlyProperty True if the property is editor only (call FProperty::IsEditorOnlyProperty to work this out, as the archive can't since it can't access CoreUObject types)
Reimplemented from FArchive.
Definition at line 1143 of file LinkerLoad.h.
References Loader, and FArchive::PushSerializedProperty().
RegenerateBlueprintClass()
bool FLinkerLoad::RegenerateBlueprintClass (UClass * LoadClass, UObject * ExportObject) private
Regenerates/Refreshes a blueprint class.
Parameters
LoadClass Instance of the class currently being loaded and which is the parent for the blueprint
ExportObject Current object bein exported
Returns
Returns true if regeneration was successful, otherwise false
References UObject.
RelocateReferences()
ELinkerStatus FLinkerLoad::RelocateReferences () private
RemoveKnownMissingPackage()
bool FLinkerLoad::RemoveKnownMissingPackage (FName PackageName) static
Register that a package is no longer known missing and that it should be searched for again in the future.
Returns
true if the provided package was removed from the KnownMissingPackage list
References IsImportLazyLoadEnabled(), and PackageName.
ReplaceExportIndexes()
void FLinkerLoad::ReplaceExportIndexes (const FPackageIndex & OldIndex, const FPackageIndex & NewIndex) private
Replaces all instances of OldIndex in ExportMap with NewIndex.
RequestPlaceholderValue()
UObject * FLinkerLoad::RequestPlaceholderValue (const FProperty * Property, const UClass * ObjectType, const TCHAR * ObjectPath)
Gives external code the ability to create FLinkerPlaceholderBase objects in place of loads that may violate the LOAD_DeferDependencyLoads state.
This will only produce a placeholder if LOAD_DeferDependencyLoads is set for this linker.
NOTE: For now, this will only produce UClass placeholders, as that is the only type we've identified needing.
Parameters
Property The property for which you want to defer loading the value.
ObjectType The expected type of the object you want to defer loading of.
ObjectPath The full object/package path for the expected object.
Returns
A FLinkerPlaceholderBase UObject that can be used in place of the import dependency.
References Property, and UObject.
ResetDeferredLoadingState()
void FLinkerLoad::ResetDeferredLoadingState () private
ResetStatusInfo()
void FLinkerLoad::ResetStatusInfo () private
Sets the basic linker archive info.
ResolveAllImports()
void FLinkerLoad::ResolveAllImports () private
Iterates through the ImportMap and calls CreateImport() for every entry, creating/loading each import as we go.
This also makes sure that class imports have had ResolveDeferredDependencies() completely executed for them (even those already running through it earlier in the callstack).
ResolvedDeferredSubobjects()
void FLinkerLoad::ResolvedDeferredSubobjects (ULinkerPlaceholderExportObject * OwningPlaceholder) private
Helper function to recursively resolve placeholders that were waiting for their outer.
ResolveDeferredDependencies()
void FLinkerLoad::ResolveDeferredDependencies (UStruct * LoadStruct) private
Combs the ImportMap for any imports that were deferred, and then creates them (via CreateImport).
Parameters
LoadStruct The (Blueprint) class or struct that you want resolved (so that it no longer contains dependency placeholders).
ResolveDeferredExports()
void FLinkerLoad::ResolveDeferredExports (UClass * LoadClass) private
Combs the ExportMap for any stubbed in ULinkerPlaceholderExportObjects, and finalizes the real export's class before actually creating it (exports are deferred when their class isn't fully formed at the time CreateExport() is called).
Also, this function ensures that deferred CDO
serialization is executed (expects its class to be fully resolved at this point).
Parameters
LoadClass A fully loaded/serialized class that may have property references to placeholder export objects (in need of fix-up).
ResolveDependencyPlaceholder()
int32 FLinkerLoad::ResolveDependencyPlaceholder (class FLinkerPlaceholderBase * Placeholder, UClass * ReferencingClass = nullptr, const FName ObjectPath = NAME_None) private
Loads the import that the Placeholder was initially stubbed in for (NOTE: this could cause recursive behavior), and then replaces all known placeholder references with the proper class.
Parameters
Placeholder A ULinkerPlaceholderClass that was substituted in place of a deferred dependency.
ReferencingClass The (Blueprint) class that was loading, while we deferred dependencies (now referencing the placeholder).
ObjectPath Optional param that denotes the full object/package path for the object the placeholder is supposed to represent (used when the passed placeholder is not tied to an import in the linker's ImportMap).
Returns
The number of placeholder references replaced (could be none, if this was recursively resolved).
ResolvePlaceholder()
void FLinkerLoad::ResolvePlaceholder (ULinkerPlaceholderExportObject * Placeholder) private
Called when a class is loaded and its now safe to load deferred instances.
ResolveResource()
UObject * FLinkerLoad::ResolveResource (FPackageIndex ResourceIndex)
Returns the Object associated with the resource indicated.
Parameters
ResourceIndex location of the object resource
Returns
The UObject at ResourceIndex, or nullptr if not found
References UObject.
ResolveResourceName()
FName FLinkerLoad::ResolveResourceName (FPackageIndex ResourceIndex)
Returns the ObjectName associated with the resource indicated.
Parameters
ResourceIndex location of the object resource
Returns
ObjectName for the FObjectResource at ResourceIndex, or NAME_None if not found
Seek()
virtual FORCEINLINE void FLinkerLoad::Seek (int64 InPos) inline override private virtual
Attempts to set the current offset into backing data storage, this will do nothing if there is no storage.
Reimplemented from FArchive.
Definition at line 1040 of file LinkerLoad.h.
References bDetachedLoader, checkf, FORCEINLINE, Loader, and TEXT.
Serialize() [1/2]
void FLinker::Serialize (FArchive & Ar) private
I/O function.
Parameters
Ar the archive to read/write into
Serialize() [2/2]
virtual FORCEINLINE void FLinkerLoad::Serialize (void * V, int64 Length) inline override private virtual
Reimplemented from FArchive.
Definition at line 1069 of file LinkerLoad.h.
References bDetachedLoader, bIsLoadingToPropertyBagObject, bIsSerializingScriptProperties, checkf, checkSlow, FORCEINLINE, FAndroidTLS::GetCurrentThreadId(), Loader, OwnerThread, Tell(), TEXT, and UNLIKELY.
SerializeBulkData()
virtual bool FLinkerLoad::SerializeBulkData (FBulkData & BulkData, const FBulkDataSerializationParams & Params) override virtual
Serialize bulk data.
Parameters
BulkData Bulk data object to serialize
Params Serialization parameters
Returns
true if the bulk data was serialized, false to fallback to default serialization (inline)
Reimplemented from FArchive.
References BulkData, and Params.
SerializeBulkMeta()
void FLinkerLoad::SerializeBulkMeta (UE::BulkData::Private::FBulkMetaData & Meta, FBulkDataCookedIndex & CookedIndex, int64 & DuplicateSerialOffset, int32 ElementSize) private
References Meta.
SerializeDataResourceMap()
ELinkerStatus FLinkerLoad::SerializeDataResourceMap () private
Serializes the data resource map.
SerializeDependsMap()
ELinkerStatus FLinkerLoad::SerializeDependsMap () private
Serializes the depends map.
SerializeExportMap()
ELinkerStatus FLinkerLoad::SerializeExportMap () private
Serializes the export map.
SerializeGatherableTextDataMap()
ELinkerStatus FLinkerLoad::SerializeGatherableTextDataMap (bool bForceEnableForCommandlet = false)
Serializes the gatherable text data container.
SerializeImportMap()
ELinkerStatus FLinkerLoad::SerializeImportMap () private
Serializes the import map.
SerializeNameMap()
ELinkerStatus FLinkerLoad::SerializeNameMap () private
Serializes the name map.
SerializePackageFileSummary()
ELinkerStatus FLinkerLoad::SerializePackageFileSummary () private
Start the process of serializing the package file summary if needed.
SerializePackageFileSummaryInternal()
ELinkerStatus FLinkerLoad::SerializePackageFileSummaryInternal () private
Does the actual serialization of the package file summary.
SerializePackageTrailer()
ELinkerStatus FLinkerLoad::SerializePackageTrailer () private
Serializes the header for the package trailer, allowing us to identify the payloads of the package.
SerializePreloadDependencies()
ELinkerStatus FLinkerLoad::SerializePreloadDependencies () private
Serializes the preload dependencies.
SerializeSoftObjectPathList()
ELinkerStatus FLinkerLoad::SerializeSoftObjectPathList () private
Serializes the soft object map.
SerializeThumbnails()
ELinkerStatus FLinkerLoad::SerializeThumbnails (bool bForceEnableForCommandlet = false)
Serializes thumbnails.
SetDebugSerializationFlags()
virtual void FLinkerLoad::SetDebugSerializationFlags (uint32 InCustomFlags) inline override private virtual
Sets the archives custom serialization modifier flags (nothing to do with PortFlags or Custom versions)
Parameters
InCustomFlags the new flags to use for custom serialization
Reimplemented from FArchive.
Definition at line 1160 of file LinkerLoad.h.
References Loader, and FArchiveState::SetDebugSerializationFlags().
SetLoader()
void FLinkerLoad::SetLoader (FArchive * InLoader, bool bInLoaderNeedsEngineVersionChecks) protected
References FArchive::FArchive().
SetPackagePath()
void FLinkerLoad::SetPackagePath (const FPackagePath & PackagePath) private
Set the packagepath being loaded.
References PackagePath.
SetPreloadingEnabled()
void FLinkerLoad::SetPreloadingEnabled (bool bEnabled) static
SetSerializedProperty()
virtual void FLinkerLoad::SetSerializedProperty (FProperty * InProperty) inline override private virtual
Overrides the property that is currently being serialized.
Note
: You likely want to call PushSerializedProperty/PopSerializedProperty instead
Parameters
InProperty Pointer to the property that is currently being serialized
Reimplemented from FArchive.
Definition at line 1132 of file LinkerLoad.h.
References Loader, and FArchiveState::SetSerializedProperty().
SetSerializedPropertyChain()
virtual void FLinkerLoad::SetSerializedPropertyChain (const FArchiveSerializedPropertyChain * InSerializedPropertyChain, class FProperty * InSerializedPropertyOverride = nullptr) inline override private virtual
Set the raw serialized property chain for this archive, optionally overriding the serialized property too (or null to use the head of the property chain)
Reimplemented from FArchive.
Definition at line 1137 of file LinkerLoad.h.
References Loader, and FArchiveState::SetSerializedPropertyChain().
ShouldCreateThrottledSlowTask()
bool FLinkerLoad::ShouldCreateThrottledSlowTask () const private
Test whether we should report progress or not based on how recently we last created a progress task.
ShouldReportProgress()
FORCEINLINE bool FLinkerLoad::ShouldReportProgress () const inline private
Test whether we should report progress or not.
Definition at line 536 of file LinkerLoad.h.
References FORCEINLINE, IsAsyncLoading, LOAD_Async, LOAD_Quiet, and LoadFlags.
StaticType()
FORCEINLINE ELinkerType::Type FLinkerLoad::StaticType () inline static
Definition at line 157 of file LinkerLoad.h.
References FORCEINLINE, and ELinkerType::Load.
Tell()
virtual FORCEINLINE int64 FLinkerLoad::Tell () inline override private virtual
Returns the current location within the backing data storage, which can possibly be passed to Seek later to restore a read/write location.
If this returns -1, there is no backing data storage and Seek will not function.
Reimplemented from FArchive.
Definition at line 1049 of file LinkerLoad.h.
References bDetachedLoader, checkf, FORCEINLINE, Loader, and TEXT.
Referenced by Serialize().
Tick()
ELinkerStatus FLinkerLoad::Tick (float InTimeLimit, bool bInUseTimeLimit, bool bInUseFullTimeLimit, TMap< TPair< FName, FPackageIndex >, FPackageIndex > * ObjectNameWithOuterToExportMap) protected
Ticks an in-flight linker and spends InTimeLimit seconds on creation.
This is a soft time limit used if bInUseTimeLimit is true.
Parameters
InTimeLimit Soft time limit to use if bInUseTimeLimit is true
bInUseTimeLimit Whether to use a (soft) timelimit
bInUseFullTimeLimit Whether to use the entire time limit, even if blocked on I/O
Returns
true if linker has finished creation, false if it is still in flight
TotalSize()
virtual FORCEINLINE int64 FLinkerLoad::TotalSize () inline override private virtual
Returns total size of the backing data storage.
Reimplemented from FArchive.
Definition at line 1058 of file LinkerLoad.h.
References bDetachedLoader, checkf, FORCEINLINE, Loader, and TEXT.
TryCreatePlaceholderClassForExport()
UClass * FLinkerLoad::TryCreatePlaceholderClassForExport (int32 ExportIndex) private
Utility function to create a placeholder class for the specified export.
This will be called if the export could not resolve its LoadClass import. In that case, its data might still be serializable (into a property bag).
Parameters
ExportIndex Index of the export that's missing its type.
Returns
The placeholder type that will be used to load the export's data.
TryCreatePlaceholderClassImport()
UClass * FLinkerLoad::TryCreatePlaceholderClassImport (int32 ImportIndex) private
Utility function for callers to try and create a placeholder class object in the specified import slot if it represents a class object.
This allows for objects to still be serialized even if missing its class type on load (the data will be serialized into a property bag).
Note: If the import is already non-NULL, this will not create a placeholder class (and the function will return NULL as a result).
Parameters
ImportIndex Index of the import that may be a missing class.
Returns
A reference to the placeholder class (if created), otherwise NULL.
TryGetPreloadedLoader()
bool FLinkerLoad::TryGetPreloadedLoader (const FPackagePath & InPackagePath, FOpenPackageResult & OutResult) static
UE_DEPRECATED() [1/3]
FLinkerLoad::UE_DEPRECATED (5. 5, "GetSerializeContext is not supported. Use FUObjectThreadContext::Get().GetSerializeContext().") override
UE_DEPRECATED() [2/3]
FLinkerLoad::UE_DEPRECATED (5. 5, "LOAD_RegenerateBulkDataGuids is now obsolete so this method no longer has any purpose.") const inline
Definition at line 1007 of file LinkerLoad.h.
References bool.
UE_DEPRECATED() [3/3]
FLinkerLoad::UE_DEPRECATED (5. 6, "This function was used only for the now-deleted Conform functionality and will be removed. Contact Epic if you need this function.")
UpdateFromPackageFileSummary()
ELinkerStatus FLinkerLoad::UpdateFromPackageFileSummary () private
Updates the linker, loader and root package with data from the package file summary.
Verify()
void FLinkerLoad::Verify ()
VerifyImport()
EVerifyResult FLinkerLoad::VerifyImport (int32 ImportIndex)
A wrapper around VerifyImportInner.
If the VerifyImportInner (previously VerifyImport) fails, this function will look for a UObjectRedirector that will point to the real location of the object. You will see this if an object was renamed to a different package or group, but something that was referencing the object was not not currently open. (Rename fixes up references of all loaded objects, but naturally not for ones that aren't loaded).
Parameters
ImportIndex The index into this package's ImportMap to verify
Returns
Verify import result
VerifyImportInner()
bool FLinkerLoad::VerifyImportInner (const int32 ImportIndex, FString & WarningSuffix) private
Safely verify that an import in the ImportMap points to a good object.
This decides whether or not a failure to load the object redirector in the wrapper is a fatal error or not (return value)
Parameters
i The index into this packages ImportMap to verify
WarningSuffix [out] additional information about the load failure that should be appended to the name of the object in the load failure dialog.
Returns
true if the wrapper should crash if it can't find a good object redirector to load
WillTextureBeLoaded()
bool FLinkerLoad::WillTextureBeLoaded (UClass * Class, int32 ExportIndex)
Checks if the specified export should be loaded or not.
Performs similar checks as CreateExport().
Parameters
ExportIndex Index of the export to check
Returns
true of the export should be loaded
References Class, and WillTextureBeLoaded().
Referenced by WillTextureBeLoaded().
Friends And Related Symbol Documentation
FAsyncLoadingThread2
friend class FAsyncLoadingThread2 friend
Definition at line 129 of file LinkerLoad.h.
References FAsyncLoadingThread2.
Referenced by FAsyncLoadingThread2.
FAsyncPackage
friend struct FAsyncPackage friend
Definition at line 127 of file LinkerLoad.h.
References FAsyncPackage.
Referenced by FAsyncPackage.
FAsyncPackage2
friend struct FAsyncPackage2 friend
Definition at line 128 of file LinkerLoad.h.
References FAsyncPackage2.
Referenced by FAsyncPackage2.
FResolvingExportTracker
friend struct FResolvingExportTracker friend
Definition at line 130 of file LinkerLoad.h.
References FResolvingExportTracker.
Referenced by FResolvingExportTracker.
operator<< [1/15]
FORCEINLINE friend FArchive & operator<< (FArchive & Ar, ANSICHAR & Value) friend
Serializes an ANSICHAR value from or into an archive.
Parameters
Ar The archive to serialize from or to.
Value The value to serialize.
Definition at line 26 of file Archive.h.
operator<< [2/15]
FORCEINLINE friend FArchive & operator<< (FArchive & Ar, bool & D) friend
Definition at line 26 of file Archive.h.
operator<< [3/15]
FORCEINLINE friend FArchive & operator<< (FArchive & Ar, double & Value) friend
Serializes a double precision floating point value from or into an archive.
Parameters
Ar The archive to serialize from or to.
Value The value to serialize.
Definition at line 26 of file Archive.h.
operator<< [4/15]
FORCEINLINE friend FArchive & operator<< (FArchive & Ar, float & Value) friend
Serializes a single precision floating point value from or into an archive.
Parameters
Ar The archive to serialize from or to.
Value The value to serialize.
Definition at line 26 of file Archive.h.
operator<< [5/15]
FArchive & operator<< (FArchive & Ar, FString & Value) friend
Serializes an FString value from or into an archive.
Parameters
Ar The archive to serialize from or to.
Value The value to serialize.
operator<< [6/15]
FORCEINLINE friend FArchive & operator<< (FArchive & Ar, int16 & Value) friend
Serializes a signed 16-bit integer value from or into an archive.
Parameters
Ar The archive to serialize from or to.
Value The value to serialize.
Definition at line 26 of file Archive.h.
operator<< [7/15]
FORCEINLINE friend FArchive & operator<< (FArchive & Ar, int32 & Value) friend
Serializes a signed 32-bit integer value from or into an archive.
Parameters
Ar The archive to serialize from or to.
Value The value to serialize.
Definition at line 26 of file Archive.h.
operator<< [8/15]
FArchive & operator<< (FArchive & Ar, int64 & Value) friend
Serializes a signed 64-bit integer value from or into an archive.
Parameters
Ar The archive to serialize from or to.
Value The value to serialize.
Definition at line 26 of file Archive.h.
operator<< [9/15]
FORCEINLINE friend FArchive & operator<< (FArchive & Ar, int8 & Value) friend
Serializes a signed 8-bit integer value from or into an archive.
Parameters
Ar The archive to serialize from or to.
Value The value to serialize.
Definition at line 26 of file Archive.h.
operator<< [10/15]
FORCEINLINE friend FArchive & operator<< (FArchive & Ar, uint16 & Value) friend
Serializes an unsigned 16-bit integer value from or into an archive.
Parameters
Ar The archive to serialize from or to.
Value The value to serialize.
Definition at line 26 of file Archive.h.
operator<< [11/15]
FORCEINLINE friend FArchive & operator<< (FArchive & Ar, uint32 & Value) friend
Serializes an unsigned 32-bit integer value from or into an archive.
Parameters
Ar The archive to serialize from or to.
Value The value to serialize.
Definition at line 26 of file Archive.h.
operator<< [12/15]
FORCEINLINE friend FArchive & operator<< (FArchive & Ar, uint64 & Value) friend
Serializes a unsigned 64-bit integer value from or into an archive.
Parameters
Ar The archive to serialize from or to.
Value The value to serialize.
Definition at line 26 of file Archive.h.
operator<< [13/15]
FORCEINLINE friend FArchive & operator<< (FArchive & Ar, uint8 & Value) friend
Serializes an unsigned 8-bit integer value from or into an archive.
Parameters
Ar The archive to serialize from or to.
Value The value to serialize.
Definition at line 26 of file Archive.h.
operator<< [14/15]
FORCEINLINE friend FArchive & operator<< (FArchive & Ar, UTF32CHAR & Value) friend
Serializes a UTF32CHAR value from or into an archive.
Parameters
Ar The archive to serialize from or to.
Value The value to serialize.
Definition at line 26 of file Archive.h.
operator<< [15/15]
FORCEINLINE friend FArchive & operator<< (FArchive & Ar, WIDECHAR & Value) friend
Serializes a WIDECHAR value from or into an archive.
Parameters
Ar The archive to serialize from or to.
Value The value to serialize.
Definition at line 26 of file Archive.h.
UObject
friend class UObject friend
Definition at line 125 of file LinkerLoad.h.
References UObject.
Referenced by AttachBulkData(), CreateExport(), CreateExportAndPreload(), CreateImport(), DeferExportCreation(), FindExistingExport(), FindExistingImport(), FindImport(), FindImportFast(), GetArchetypeFromLoader(), GetCurrentObjectAtIndex(), IndexToObject(), InvalidateExport(), MarkScriptSerializationEnd(), MarkScriptSerializationStart(), operator<<(), operator<<(), Preload(), PRIVATE_PatchNewObjectIntoExport(), PRIVATE_PatchNewObjectIntoExport(), RegenerateBlueprintClass(), RequestPlaceholderValue(), ResolveResource(), and UObject.
UPackageMap
friend class UPackageMap friend
Definition at line 126 of file LinkerLoad.h.
References UPackageMap.
Referenced by UPackageMap.
Field Documentation
AsyncRoot
void* FLinkerLoad::AsyncRoot
The async package associated with this linker.
Definition at line 288 of file LinkerLoad.h.
bActiveRedirectsMapInitialized
bool FLinkerLoad::bActiveRedirectsMapInitialized static private
Makes sure the deprecated active redirects inis have been read.
Definition at line 529 of file LinkerLoad.h.
bDetachedLoader
bool FLinkerLoad::bDetachedLoader private
Tracks if DetachLoader has been called or not.
Definition at line 214 of file LinkerLoad.h.
Referenced by Precache(), Seek(), Serialize(), Tell(), and TotalSize().
bExportsDuplicatesFixed
bool FLinkerLoad::bExportsDuplicatesFixed private
Check to avoid multiple export duplicate fixups in case we don't save asset.
Definition at line 471 of file LinkerLoad.h.
bFixupExportMapDone
bool FLinkerLoad::bFixupExportMapDone private
Used for ActiveClassRedirects functionality.
Definition at line 453 of file LinkerLoad.h.
bForceSimpleIndexToObject
bool FLinkerLoad::bForceSimpleIndexToObject
Definition at line 170 of file LinkerLoad.h.
bHasAppliedInstancingContext
bool FLinkerLoad::bHasAppliedInstancingContext private
Whether we already applied the instancing context to the soft object list.
Definition at line 451 of file LinkerLoad.h.
bHasConstructedExportsReaders
bool FLinkerLoad::bHasConstructedExportsReaders private
Whether we have already constructed the exports readers.
Definition at line 441 of file LinkerLoad.h.
bHasFinishedInitialization
bool FLinkerLoad::bHasFinishedInitialization private
Whether we are already fully initialized.
Definition at line 457 of file LinkerLoad.h.
Referenced by HasFinishedInitialization().
bHasFixedUpImportMap
bool FLinkerLoad::bHasFixedUpImportMap private
Whether we already fixed up import map.
Definition at line 445 of file LinkerLoad.h.
bHasFoundExistingExports
bool FLinkerLoad::bHasFoundExistingExports private
Whether we already matched up existing exports.
Definition at line 455 of file LinkerLoad.h.
bHasPopulatedInstancingContext
bool FLinkerLoad::bHasPopulatedInstancingContext private
Whether we already populated the instancing context.
Definition at line 447 of file LinkerLoad.h.
bHasRelocatedReferences
bool FLinkerLoad::bHasRelocatedReferences private
Whether we already relocated references.
Definition at line 449 of file LinkerLoad.h.
bHasSerializedPackageFileSummary
bool FLinkerLoad::bHasSerializedPackageFileSummary private
Whether we already serialized the package file summary.
Definition at line 437 of file LinkerLoad.h.
bHasSerializedPackageTrailer
bool FLinkerLoad::bHasSerializedPackageTrailer private
Whether we already serialized the package trailer.
Definition at line 439 of file LinkerLoad.h.
bHasSerializedPreloadDependencies
bool FLinkerLoad::bHasSerializedPreloadDependencies private
Whether we already serialized preload dependencies.
Definition at line 443 of file LinkerLoad.h.
bHaveImportsBeenVerified
bool FLinkerLoad::bHaveImportsBeenVerified
Indicates whether the imports for this loader have been verified.
Definition at line 167 of file LinkerLoad.h.
bIsAsyncLoader
bool FLinkerLoad::bIsAsyncLoader
True if Loader is FAsyncArchive.
Definition at line 174 of file LinkerLoad.h.
Referenced by GetAsyncLoader().
bIsDestroyingLoader
bool FLinkerLoad::bIsDestroyingLoader private
True if the linker is currently deleting loader.
Definition at line 211 of file LinkerLoad.h.
Referenced by IsDestroyingLoader().
bIsGatheringDependencies
bool FLinkerLoad::bIsGatheringDependencies private
Whether we are gathering dependencies, can be used to streamline VerifyImports, etc.
Definition at line 459 of file LinkerLoad.h.
bIsLoadingToPropertyBagObject
bool FLinkerLoad::bIsLoadingToPropertyBagObject private
Set when the loader is serializing to a property bag placeholder object.
Definition at line 477 of file LinkerLoad.h.
Referenced by Serialize().
bIsPackageRelocated
bool FLinkerLoad::bIsPackageRelocated private
Cache if the package is relocated or not.
Definition at line 474 of file LinkerLoad.h.
Referenced by IsPackageRelocated().
bIsSerializingScriptProperties
bool FLinkerLoad::bIsSerializingScriptProperties private
TRUE when the loader is actively serializing an object's script properties data.
Definition at line 480 of file LinkerLoad.h.
Referenced by Serialize().
bLoaderNeedsEngineVersionChecks
bool FLinkerLoad::bLoaderNeedsEngineVersionChecks private
Whether the loader needs version and correctness checks (see OpenReadPackage)
Definition at line 467 of file LinkerLoad.h.
bLockoutLegacyOperations
bool FLinkerLoad::bLockoutLegacyOperations
Definition at line 171 of file LinkerLoad.h.
bPreloadingEnabled
bool FLinkerLoad::bPreloadingEnabled static private
Definition at line 816 of file LinkerLoad.h.
bTimeLimitExceeded
bool FLinkerLoad::bTimeLimitExceeded private
Whether time limit is/ has been exceeded in current/ last tick.
Definition at line 461 of file LinkerLoad.h.
BulkDataLoaders
TSet<FBulkData*> FLinkerLoad::BulkDataLoaders
Bulk data that use the FLinkerLoad to track the state of the file on disk.
Definition at line 295 of file LinkerLoad.h.
BulkDataMutex
UE::FMutex FLinkerLoad::BulkDataMutex
Used when accessing BulkDataLoaders/EditorBulkDataLoaders to ensure thread safety.
Definition at line 292 of file LinkerLoad.h.
bUseFullTimeLimit
bool FLinkerLoad::bUseFullTimeLimit private
Whether to use the full time limit, even if we're blocked on I/O.
Definition at line 465 of file LinkerLoad.h.
bUseTimeLimit
bool FLinkerLoad::bUseTimeLimit private
Whether to use a time limit for async linker creation.
Definition at line 463 of file LinkerLoad.h.
ClassPackage
FName FLinkerLoad::ClassPackage
Definition at line 707 of file LinkerLoad.h.
DependsMapIndex
int32 FLinkerLoad::DependsMapIndex private
Current index into depends map, used by async linker creation for spreading out serializing dependsmap entries.
Definition at line 431 of file LinkerLoad.h.
EditorBulkDataLoaders
TSet<UE::Serialization::FEditorBulkData*> FLinkerLoad::EditorBulkDataLoaders
Definition at line 296 of file LinkerLoad.h.
ExportHash
TUniquePtr<int32[]> FLinkerLoad::ExportHash
Definition at line 301 of file LinkerLoad.h.
ExportHashCount
int32 FLinkerLoad::ExportHashCount = 256 static constexpr
Hash table for exports.
Definition at line 300 of file LinkerLoad.h.
Referenced by GetHashBucket().
ExportHashIndex
int32 FLinkerLoad::ExportHashIndex private
Current index into export hash map, used by async linker creation for spreading out hashing exports.
Definition at line 433 of file LinkerLoad.h.
ExportMapIndex
int32 FLinkerLoad::ExportMapIndex private
Current index into export map, used by async linker creation for spreading out serializing exportmap entries.
Definition at line 423 of file LinkerLoad.h.
ExportOuterIndex
FName FName FPackageIndex FLinkerLoad::ExportOuterIndex
Definition at line 707 of file LinkerLoad.h.
ExportReaders
TArray<FStructuredArchiveChildReader*> FLinkerLoad::ExportReaders private
Definition at line 223 of file LinkerLoad.h.
ExternalReadDependencies
TArray<FExternalReadCallback> FLinkerLoad::ExternalReadDependencies
List of external read dependencies that must be finished to load this package.
Definition at line 316 of file LinkerLoad.h.
GatherableTextDataMapIndex
int32 FLinkerLoad::GatherableTextDataMapIndex private
Current index into gatherable text data map, used by async linker creation for spreading out serializing text entries.
Definition at line 419 of file LinkerLoad.h.
ImportMapIndex
int32 FLinkerLoad::ImportMapIndex private
Current index into import map, used by async linker creation for spreading out serializing importmap entries.
Definition at line 421 of file LinkerLoad.h.
ImportsToVerifyOnCreate
TSet<int32> FLinkerLoad::ImportsToVerifyOnCreate private
Set of imports that require additional verification at creation time.
Definition at line 240 of file LinkerLoad.h.
InstancingContext
FLinkerInstancingContext FLinkerLoad::InstancingContext private
The linker instancing context.
Definition at line 234 of file LinkerLoad.h.
Referenced by FLinkerLoad(), CreateLinker(), CreateLinkerAsync(), and GetInstancingContext().
IsTimeLimitExceededCallCount
int32 FLinkerLoad::IsTimeLimitExceededCallCount private
Call count of IsTimeLimitExceeded.
Definition at line 484 of file LinkerLoad.h.
Loader
FArchive* FLinkerLoad::Loader private
The archive that actually reads the raw data from disk.
Definition at line 231 of file LinkerLoad.h.
Referenced by GetAsyncLoader(), GetLoader(), GetLoader_Unsafe(), HasLoader(), PopDebugDataString(), PopSerializedProperty(), Precache(), PushDebugDataString(), PushSerializedProperty(), Seek(), Serialize(), SetDebugSerializationFlags(), SetSerializedProperty(), SetSerializedPropertyChain(), Tell(), and TotalSize().
LoadFlags
uint32 FLinkerLoad::LoadFlags
Flags determining loading behavior.
Definition at line 165 of file LinkerLoad.h.
Referenced by CreateLinker(), CreateLinkerAsync(), and ShouldReportProgress().
LoadProgressScope
FScopedSlowTask* FLinkerLoad::LoadProgressScope private
Feedback scope that is created to house the slow task of an asynchronous linker load.
Raw ptr so we don't pull in TUniquePtr for everything.
Definition at line 533 of file LinkerLoad.h.
NAME_LoadErrors
FName FLinkerLoad::NAME_LoadErrors static private
Definition at line 526 of file LinkerLoad.h.
ObjectName
FName FName FLinkerLoad::ObjectName
Definition at line 707 of file LinkerLoad.h.
Referenced by FindImport().
OwnerThread
int32 FLinkerLoad::OwnerThread private
Id of the thread that created this linker.
This is to guard against using this linker on other threads than the one it was created on
Definition at line 490 of file LinkerLoad.h.
Referenced by GetOwnerThreadId(), and Serialize().
PackagePath
FPackagePath FLinkerLoad::PackagePath private
The packagepath being loaded.
Definition at line 225 of file LinkerLoad.h.
Referenced by FLinkerLoad(), CreateLinker(), CreateLinkerAsync(), GetPackagePath(), and SetPackagePath().
PackageTrailer
TUniquePtr<UE::FPackageTrailer> FLinkerLoad::PackageTrailer private
The trailer for the package.
Definition at line 237 of file LinkerLoad.h.
Referenced by GetPackageTrailer().
PreloadDependencies
TArray<FPackageIndex> FLinkerLoad::PreloadDependencies
List of imports and exports that must be serialized before other exports...all packed together, see FirstExportDependency.
Definition at line 311 of file LinkerLoad.h.
SoftObjectPathListIndex
int32 FLinkerLoad::SoftObjectPathListIndex private
Current index into soft object path list, used by async linker creation for spreading out serializing soft object path entries.
Definition at line 417 of file LinkerLoad.h.
StructuredArchive
FStructuredArchive* FLinkerLoad::StructuredArchive private
Structured archive interface.
Wraps underlying loader to provide contextual metadata to the values being written which ultimately allows text based serialization of the data
Definition at line 220 of file LinkerLoad.h.
StructuredArchiveFormatter
FArchiveFormatterType* FLinkerLoad::StructuredArchiveFormatter private
Definition at line 221 of file LinkerLoad.h.
StructuredArchiveRootRecord
TOptional<FStructuredArchive::FRecord> FLinkerLoad::StructuredArchiveRootRecord private
Definition at line 222 of file LinkerLoad.h.
TemplateForGetArchetypeFromLoader
UObject* FLinkerLoad::TemplateForGetArchetypeFromLoader
Definition at line 169 of file LinkerLoad.h.
TickStartTime
double FLinkerLoad::TickStartTime private
Time at begin of Tick function.
Used for time limit determination.
Definition at line 488 of file LinkerLoad.h.
TimeLimit
float FLinkerLoad::TimeLimit private
Current time limit to use if bUseTimeLimit is true.
Definition at line 486 of file LinkerLoad.h.
Referenced by FinishExternalReadDependencies().
The documentation for this class was generated from the following file:
Runtime/CoreUObject/Public/UObject/LinkerLoad.h