Unreal Engine 5.6 C++ API: TDelegateBase< ThreadSafetyMode > Class Template Reference
TDelegateBase< ThreadSafetyMode > Class Template Reference
Base class for unicast delegates.
#include "DelegateBase.h"
Public Member Functions
TDelegateBase (TDelegateBase &&Other)
template<typename OtherThreadSafetyMode>
TDelegateBase (TDelegateBase< OtherThreadSafetyMode > &&Other)
~TDelegateBase ()
SIZE_T GetAllocatedSize () const
Returns the amount of memory allocated by this delegate, not including sizeof(*this).
uint64 GetBoundProgramCounterForTimerManager () const
Returns the address of the method pointer which can be used to learn the address of the function that will be executed.
FORCEINLINE FDelegateHandle GetHandle () const
Gets a handle to the delegate.
FORCEINLINE const void * GetObjectForTimerManager () const
Returns a pointer to an object bound to this delegate, intended for quick lookup in the timer manager,.
FORCEINLINE class UObject * GetUObject () const
If this is a UFunction or UObject delegate, return the UObject.
FORCEINLINE bool IsBound () const
Checks to see if the user object bound to this delegate is still valid.
FORCEINLINE bool IsBoundToObject (FDelegateUserObjectConst InUserObject) const
Checks to see if this delegate is bound to the given user object.
FORCEINLINE bool IsCompactable () const
Checks to see if this delegate can ever become valid again - if not, it can be removed from broadcast lists or otherwise repurposed.
TDelegateBase & operator= (TDelegateBase &&Other)
FORCEINLINE void Unbind ()
Unbinds this delegate.
Protected Member Functions
TDelegateBase ()=default
FORCEINLINE IDelegateInstance * GetDelegateInstanceProtected ()
Gets the delegate instance.
FORCEINLINE const IDelegateInstance * GetDelegateInstanceProtected () const
Private Types
using Super = TDelegateAccessHandlerBase<ThreadSafetyMode>
Private Member Functions
template<typename OtherThreadSafetyMode>
void MoveAssign (TDelegateBase< OtherThreadSafetyMode > &&Other)
template<typename OtherThreadSafetyMode>
void MoveConstruct (TDelegateBase< OtherThreadSafetyMode > &&Other)
FORCEINLINE void UnbindUnchecked ()
Private Attributes
FDelegateAllocatorType::ForElementType< FAlignedInlineDelegateType > DelegateAllocator
int32 DelegateSize
Private Attributes inherited from FDelegateAllocation
FDelegateAllocatorType::ForElementType< FAlignedInlineDelegateType > DelegateAllocator
int32 DelegateSize = 0
Friends
template<typename>
class TDelegateBase
class FWriteLockedDelegateAllocation
template<typename, typename, typename, typename...>
class TBaseFunctorDelegateInstance
template<bool, class, typename, typename, typename...>
class TBaseRawMethodDelegateInstance
template<ESPMode, typename, typename, typename, typename...>
class TBaseSPLambdaDelegateInstance
template<bool, class, ESPMode, typename, typename, typename...>
class TBaseSPMethodDelegateInstance
template<typename, typename, typename...>
class TBaseStaticDelegateInstance
template<class, typename, typename, typename...>
class TBaseUFunctionDelegateInstance
template<bool, class, typename, typename, typename...>
class TBaseUObjectMethodDelegateInstance
template<typename>
class TMulticastDelegateBase
template<typename, typename, typename, typename...>
class TWeakBaseFunctorDelegateInstance
struct TWriteLockedDelegateAllocation< ThreadSafetyMode >
Detailed Description
template<typename ThreadSafetyMode>
class TDelegateBase< ThreadSafetyMode >
Base class for unicast delegates.
Definition at line 128 of file DelegateBase.h.
Member Typedef Documentation
Super
template<typename ThreadSafetyMode> using TDelegateBase< ThreadSafetyMode >::Super = TDelegateAccessHandlerBase<ThreadSafetyMode> private
Definition at line 133 of file DelegateBase.h.
Constructor & Destructor Documentation
TDelegateBase() [1/3]
template<typename ThreadSafetyMode> TDelegateBase< ThreadSafetyMode >::TDelegateBase () explicit protected default
~TDelegateBase()
template<typename ThreadSafetyMode> TDelegateBase< ThreadSafetyMode >::~TDelegateBase () inline
Definition at line 176 of file DelegateBase.h.
TDelegateBase() [2/3]
template<typename ThreadSafetyMode> TDelegateBase< ThreadSafetyMode >::TDelegateBase (TDelegateBase< ThreadSafetyMode > && Other) inline
Definition at line 181 of file DelegateBase.h.
TDelegateBase() [3/3]
template<typename ThreadSafetyMode> template<typename OtherThreadSafetyMode> TDelegateBase< ThreadSafetyMode >::TDelegateBase (TDelegateBase< OtherThreadSafetyMode > && Other) inline explicit
Definition at line 194 of file DelegateBase.h.
Member Function Documentation
GetAllocatedSize()
template<typename ThreadSafetyMode> SIZE_T TDelegateBase< ThreadSafetyMode >::GetAllocatedSize () const inline
Returns the amount of memory allocated by this delegate, not including sizeof(*this).
Definition at line 212 of file DelegateBase.h.
GetBoundProgramCounterForTimerManager()
template<typename ThreadSafetyMode> uint64 TDelegateBase< ThreadSafetyMode >::GetBoundProgramCounterForTimerManager () const inline
Returns the address of the method pointer which can be used to learn the address of the function that will be executed.
Returns nullptr if this delegate type does not directly invoke a function pointer.
Note: Only intended to be used to aid debugging of delegates.
Returns
The address of the function pointer that would be executed by this delegate
Definition at line 286 of file DelegateBase.h.
GetDelegateInstanceProtected() [1/2]
template<typename ThreadSafetyMode> FORCEINLINE IDelegateInstance * TDelegateBase< ThreadSafetyMode >::GetDelegateInstanceProtected () inline protected
Gets the delegate instance.
Not intended for use by user code.
Returns
The delegate instance.
See also
SetDelegateInstance
Definition at line 346 of file DelegateBase.h.
Referenced by TMulticastDelegateBase< FDefaultDelegateUserPolicy >::Broadcast(), TDelegateBase< FThreadSafetyMode >::GetBoundProgramCounterForTimerManager(), TDelegateBase< FThreadSafetyMode >::GetHandle(), TDelegateBase< FThreadSafetyMode >::GetObjectForTimerManager(), TDelegateBase< FThreadSafetyMode >::GetUObject(), TDelegateBase< FThreadSafetyMode >::IsBound(), TDelegateBase< FThreadSafetyMode >::IsBoundToObject(), TDelegateBase< FThreadSafetyMode >::IsCompactable(), TMulticastDelegateBase< FDefaultDelegateUserPolicy >::RemoveAll(), TMulticastDelegateBase< FDefaultDelegateUserPolicy >::RemoveDelegateInstance(), and TDelegateBase< FThreadSafetyMode >::UnbindUnchecked().
GetDelegateInstanceProtected() [2/2]
template<typename ThreadSafetyMode> FORCEINLINE const IDelegateInstance * TDelegateBase< ThreadSafetyMode >::GetDelegateInstanceProtected () const inline protected
Definition at line 351 of file DelegateBase.h.
GetHandle()
template<typename ThreadSafetyMode> FORCEINLINE FDelegateHandle TDelegateBase< ThreadSafetyMode >::GetHandle () const inline
Gets a handle to the delegate.
Returns
The delegate instance.
Definition at line 331 of file DelegateBase.h.
GetObjectForTimerManager()
template<typename ThreadSafetyMode> FORCEINLINE const void * TDelegateBase< ThreadSafetyMode >::GetObjectForTimerManager () const inline
Returns a pointer to an object bound to this delegate, intended for quick lookup in the timer manager,.
Returns
A pointer to an object referenced by the delegate.
Definition at line 270 of file DelegateBase.h.
GetUObject()
template<typename ThreadSafetyMode> FORCEINLINE class UObject * TDelegateBase< ThreadSafetyMode >::GetUObject () const inline
If this is a UFunction or UObject delegate, return the UObject.
Returns
The object associated with this delegate if there is one.
Definition at line 244 of file DelegateBase.h.
IsBound()
template<typename ThreadSafetyMode> FORCEINLINE bool TDelegateBase< ThreadSafetyMode >::IsBound () const inline
Checks to see if the user object bound to this delegate is still valid.
Returns
True if the user object is still valid and it's safe to execute the function call.
Definition at line 257 of file DelegateBase.h.
IsBoundToObject()
template<typename ThreadSafetyMode> FORCEINLINE bool TDelegateBase< ThreadSafetyMode >::IsBoundToObject (FDelegateUserObjectConst InUserObject) const inline
Checks to see if this delegate is bound to the given user object.
Returns
True if this delegate is bound to InUserObject, false otherwise.
Definition at line 299 of file DelegateBase.h.
IsCompactable()
template<typename ThreadSafetyMode> FORCEINLINE bool TDelegateBase< ThreadSafetyMode >::IsCompactable () const inline
Checks to see if this delegate can ever become valid again - if not, it can be removed from broadcast lists or otherwise repurposed.
Returns
True if the delegate is compatable, false otherwise.
Definition at line 318 of file DelegateBase.h.
MoveAssign()
template<typename ThreadSafetyMode> template<typename OtherThreadSafetyMode> void TDelegateBase< ThreadSafetyMode >::MoveAssign (TDelegateBase< OtherThreadSafetyMode > && Other) inline private
Definition at line 368 of file DelegateBase.h.
Referenced by TDelegateBase< FThreadSafetyMode >::operator=().
MoveConstruct()
template<typename ThreadSafetyMode> template<typename OtherThreadSafetyMode> void TDelegateBase< ThreadSafetyMode >::MoveConstruct (TDelegateBase< OtherThreadSafetyMode > && Other) inline private
Definition at line 358 of file DelegateBase.h.
Referenced by TDelegateBase< FThreadSafetyMode >::TDelegateBase(), and TDelegateBase< FThreadSafetyMode >::TDelegateBase().
operator=()
template<typename ThreadSafetyMode> TDelegateBase & TDelegateBase< ThreadSafetyMode >::operator= (TDelegateBase< ThreadSafetyMode > && Other) inline
Definition at line 186 of file DelegateBase.h.
Unbind()
template<typename ThreadSafetyMode> FORCEINLINE void TDelegateBase< ThreadSafetyMode >::Unbind () inline
Unbinds this delegate.
Definition at line 202 of file DelegateBase.h.
Referenced by TDelegateBase< FThreadSafetyMode >::~TDelegateBase(), and TMulticastDelegateBase< FDefaultDelegateUserPolicy >::RemoveDelegateInstance().
UnbindUnchecked()
template<typename ThreadSafetyMode> FORCEINLINE void TDelegateBase< ThreadSafetyMode >::UnbindUnchecked () inline private
Definition at line 389 of file DelegateBase.h.
Referenced by TDelegateBase< FThreadSafetyMode >::MoveAssign(), and TDelegateBase< FThreadSafetyMode >::Unbind().
Friends And Related Symbol Documentation
TDelegateBase
template<typename ThreadSafetyMode> template<typename> friend class TDelegateBase friend
Definition at line 139 of file DelegateBase.h.
FWriteLockedDelegateAllocation
template<typename ThreadSafetyMode> friend class FWriteLockedDelegateAllocation friend
Definition at line 165 of file DelegateBase.h.
TBaseFunctorDelegateInstance
template<typename ThreadSafetyMode> template<typename, typename, typename, typename...> friend class TBaseFunctorDelegateInstance friend
Definition at line 160 of file DelegateBase.h.
TBaseRawMethodDelegateInstance
template<typename ThreadSafetyMode> template<bool, class, typename, typename, typename...> friend class TBaseRawMethodDelegateInstance friend
Definition at line 151 of file DelegateBase.h.
TBaseSPLambdaDelegateInstance
template<typename ThreadSafetyMode> template<ESPMode, typename, typename, typename, typename...> friend class TBaseSPLambdaDelegateInstance friend
Definition at line 148 of file DelegateBase.h.
TBaseSPMethodDelegateInstance
template<typename ThreadSafetyMode> template<bool, class, ESPMode, typename, typename, typename...> friend class TBaseSPMethodDelegateInstance friend
Definition at line 145 of file DelegateBase.h.
TBaseStaticDelegateInstance
template<typename ThreadSafetyMode> template<typename, typename, typename...> friend class TBaseStaticDelegateInstance friend
Definition at line 157 of file DelegateBase.h.
TBaseUFunctionDelegateInstance
template<typename ThreadSafetyMode> template<class, typename, typename, typename...> friend class TBaseUFunctionDelegateInstance friend
Definition at line 142 of file DelegateBase.h.
TBaseUObjectMethodDelegateInstance
template<typename ThreadSafetyMode> template<bool, class, typename, typename, typename...> friend class TBaseUObjectMethodDelegateInstance friend
Definition at line 154 of file DelegateBase.h.
TMulticastDelegateBase
template<typename ThreadSafetyMode> template<typename> friend class TMulticastDelegateBase friend
Definition at line 136 of file DelegateBase.h.
TWeakBaseFunctorDelegateInstance
template<typename ThreadSafetyMode> template<typename, typename, typename, typename...> friend class TWeakBaseFunctorDelegateInstance friend
Definition at line 163 of file DelegateBase.h.
TWriteLockedDelegateAllocation< ThreadSafetyMode >
template<typename ThreadSafetyMode> friend struct TWriteLockedDelegateAllocation< ThreadSafetyMode > friend
Definition at line 121 of file DelegateBase.h.
Field Documentation
DelegateAllocator
template<typename ThreadSafetyMode> FDelegateAllocatorType::ForElementType<FAlignedInlineDelegateType> FDelegateAllocation::DelegateAllocator private
Definition at line 96 of file DelegateBase.h.
DelegateSize
template<typename ThreadSafetyMode> int32 FDelegateAllocation::DelegateSize private
Definition at line 97 of file DelegateBase.h.
The documentation for this class was generated from the following file:
Runtime/Core/Public/Delegates/DelegateBase.h