Unreal Engine 5.6 C++ API: Runtime/RenderCore/Public/ClearQuad.h File Reference
ClearQuad.h File Reference
#include "Math/Color.h"
#include "Math/IntPoint.h"
#include "Math/IntRect.h"
#include "Math/UnrealMathSSE.h"
#include "Math/Vector4.h"
#include "RenderResource.h"
#include "Templates/Function.h"
Data Structures
struct FClearQuadCallbacks
class FClearVertexBuffer
Functions
RENDERCORE_API void ClearUAV (FRHICommandList &RHICmdList, FRHIUnorderedAccessView *Buffer, uint32 NumBytes, uint32 Value, bool bBarriers=true)
void DrawClearQuad (FRHICommandList &RHICmdList, bool bClearColor, const FLinearColor &Color, bool bClearDepth, float Depth, bool bClearStencil, uint32 Stencil)
void DrawClearQuad (FRHICommandList &RHICmdList, bool bClearColor, const FLinearColor &Color, bool bClearDepth, float Depth, bool bClearStencil, uint32 Stencil, FIntPoint ViewSize, FIntRect ExcludeRect)
void DrawClearQuad (FRHICommandList &RHICmdList, const FLinearColor &Color)
void DrawClearQuad (FRHICommandList &RHICmdList, const FLinearColor &Color, FClearQuadCallbacks ClearQuadCallbacks)
RENDERCORE_API void DrawClearQuadAlpha (FRHICommandList &RHICmdList, float Alpha)
RENDERCORE_API void DrawClearQuadMRT (FRHICommandList &RHICmdList, bool bClearColor, int32 NumClearColors, const FLinearColor *ClearColorArray, bool bClearDepth, float Depth, bool bClearStencil, uint32 Stencil)
RENDERCORE_API void DrawClearQuadMRT (FRHICommandList &RHICmdList, bool bClearColor, int32 NumClearColors, const FLinearColor *ClearColorArray, bool bClearDepth, float Depth, bool bClearStencil, uint32 Stencil, FClearQuadCallbacks ClearQuadCallbacks)
RENDERCORE_API void DrawClearQuadMRT (FRHICommandList &RHICmdList, bool bClearColor, int32 NumClearColors, const FLinearColor *ClearColorArray, bool bClearDepth, float Depth, bool bClearStencil, uint32 Stencil, FIntPoint ViewSize, FIntRect ExcludeRect)
RENDERCORE_API void DrawClearQuadMRTWithUints (FRHICommandList &RHICmdList, bool bClearColor, int32 NumClearColors, const FLinearColor *ClearColorArray, bool bClearDepth, float Depth, bool bClearStencil, uint32 Stencil, uint8 NumUintOutput)
Variables
RENDERCORE_API TGlobalResource< FClearVertexBuffer > GClearVertexBuffer
Function Documentation
ClearUAV()
RENDERCORE_API void ClearUAV (FRHICommandList & RHICmdList, FRHIUnorderedAccessView * Buffer, uint32 NumBytes, uint32 Value, bool bBarriers = true) extern
References Buffer, and Value.
DrawClearQuad() [1/4]
void DrawClearQuad (FRHICommandList & RHICmdList, bool bClearColor, const FLinearColor & Color, bool bClearDepth, float Depth, bool bClearStencil, uint32 Stencil) inline
Definition at line 43 of file ClearQuad.h.
References Color, Depth, DrawClearQuadMRT(), and Stencil.
DrawClearQuad() [2/4]
void DrawClearQuad (FRHICommandList & RHICmdList, bool bClearColor, const FLinearColor & Color, bool bClearDepth, float Depth, bool bClearStencil, uint32 Stencil, FIntPoint ViewSize, FIntRect ExcludeRect) inline
Definition at line 48 of file ClearQuad.h.
References Color, Depth, DrawClearQuadMRT(), and Stencil.
DrawClearQuad() [3/4]
void DrawClearQuad (FRHICommandList & RHICmdList, const FLinearColor & Color) inline
Definition at line 53 of file ClearQuad.h.
References Color, and DrawClearQuadMRT().
DrawClearQuad() [4/4]
void DrawClearQuad (FRHICommandList & RHICmdList, const FLinearColor & Color, FClearQuadCallbacks ClearQuadCallbacks) inline
Definition at line 58 of file ClearQuad.h.
References Color, and DrawClearQuadMRT().
DrawClearQuadAlpha()
RENDERCORE_API void DrawClearQuadAlpha (FRHICommandList & RHICmdList, float Alpha) extern
References Alpha.
DrawClearQuadMRT() [1/3]
RENDERCORE_API void DrawClearQuadMRT (FRHICommandList & RHICmdList, bool bClearColor, int32 NumClearColors, const FLinearColor * ClearColorArray, bool bClearDepth, float Depth, bool bClearStencil, uint32 Stencil) extern
References Depth, and Stencil.
Referenced by DrawClearQuad(), DrawClearQuad(), DrawClearQuad(), and DrawClearQuad().
DrawClearQuadMRT() [2/3]
RENDERCORE_API void DrawClearQuadMRT (FRHICommandList & RHICmdList, bool bClearColor, int32 NumClearColors, const FLinearColor * ClearColorArray, bool bClearDepth, float Depth, bool bClearStencil, uint32 Stencil, FClearQuadCallbacks ClearQuadCallbacks) extern
References Depth, and Stencil.
DrawClearQuadMRT() [3/3]
RENDERCORE_API void DrawClearQuadMRT (FRHICommandList & RHICmdList, bool bClearColor, int32 NumClearColors, const FLinearColor * ClearColorArray, bool bClearDepth, float Depth, bool bClearStencil, uint32 Stencil, FIntPoint ViewSize, FIntRect ExcludeRect) extern
References Depth, and Stencil.
DrawClearQuadMRTWithUints()
RENDERCORE_API void DrawClearQuadMRTWithUints (FRHICommandList & RHICmdList, bool bClearColor, int32 NumClearColors, const FLinearColor * ClearColorArray, bool bClearDepth, float Depth, bool bClearStencil, uint32 Stencil, uint8 NumUintOutput) extern
References Depth, and Stencil.
Variable Documentation
GClearVertexBuffer
RENDERCORE_API TGlobalResource<FClearVertexBuffer> GClearVertexBuffer extern