Unreal Engine 5.6 C++ API: Runtime/Core/Public/Serialization/CompactBinarySerialization.h File Reference
CompactBinarySerialization.h File Reference
#include "Containers/ContainersFwd.h"
#include "Containers/StringFwd.h"
#include "CoreTypes.h"
#include "IO/IoHash.h"
#include "Memory/MemoryFwd.h"
#include "Memory/MemoryView.h"
#include "Memory/SharedBuffer.h"
#include "Serialization/CompactBinary.h"
#include "Templates/Function.h"
Namespaces
namespace UE
Utility functions for applying transformations to meshes.
namespace UE::Serialization
namespace UE::Serialization::Private
Functions
void CompactBinaryToCompactJson (const FCbArrayView &Array, FUtf8StringBuilderBase &Builder)
void CompactBinaryToCompactJson (const FCbArrayView &Array, FWideStringBuilderBase &Builder)
void CompactBinaryToCompactJson (const FCbFieldView &Field, FUtf8StringBuilderBase &Builder)
Convert the compact binary to JSON in a compact format with no added whitespace.
void CompactBinaryToCompactJson (const FCbFieldView &Field, FWideStringBuilderBase &Builder)
void CompactBinaryToCompactJson (const FCbObjectView &Object, FUtf8StringBuilderBase &Builder)
void CompactBinaryToCompactJson (const FCbObjectView &Object, FWideStringBuilderBase &Builder)
void CompactBinaryToJson (const FCbArrayView &Array, FUtf8StringBuilderBase &Builder)
void CompactBinaryToJson (const FCbArrayView &Array, FWideStringBuilderBase &Builder)
void CompactBinaryToJson (const FCbFieldView &Field, FUtf8StringBuilderBase &Builder)
Convert the compact binary to JSON in a multi-line format with indentation.
void CompactBinaryToJson (const FCbFieldView &Field, FWideStringBuilderBase &Builder)
void CompactBinaryToJson (const FCbObjectView &Object, FUtf8StringBuilderBase &Builder)
void CompactBinaryToJson (const FCbObjectView &Object, FWideStringBuilderBase &Builder)
FCbField LoadCompactBinary (FArchive &Ar, FCbBufferAllocator Allocator=FUniqueBuffer::Alloc)
Load a compact binary field from an archive.
bool LoadFromCompactBinary (FCbFieldView Field, bool &OutValue, const bool Default=false)
bool LoadFromCompactBinary (FCbFieldView Field, double &OutValue, const double Default=0.0)
bool LoadFromCompactBinary (FCbFieldView Field, FCbObjectId &OutValue, const FCbObjectId &Default=FCbObjectId())
bool LoadFromCompactBinary (FCbFieldView Field, FDateTime &OutValue)
bool LoadFromCompactBinary (FCbFieldView Field, FDateTime &OutValue, FDateTime Default)
bool LoadFromCompactBinary (FCbFieldView Field, FGuid &OutValue)
bool LoadFromCompactBinary (FCbFieldView Field, FGuid &OutValue, const FGuid &Default)
bool LoadFromCompactBinary (FCbFieldView Field, FIoHash &OutValue, const FIoHash &Default=FIoHash())
bool LoadFromCompactBinary (FCbFieldView Field, float &OutValue, const float Default=0.0f)
bool LoadFromCompactBinary (FCbFieldView Field, FName &OutValue)
bool LoadFromCompactBinary (FCbFieldView Field, FUtf8String &OutValue)
bool LoadFromCompactBinary (FCbFieldView Field, FUtf8StringBuilderBase &OutValue)
LoadFromCompactBinary attempts to load the output value from compact binary.
bool LoadFromCompactBinary (FCbFieldView Field, FWideString &OutValue)
bool LoadFromCompactBinary (FCbFieldView Field, FWideStringBuilderBase &OutValue)
bool LoadFromCompactBinary (FCbFieldView Field, int16 &OutValue, const int16 Default=0)
bool LoadFromCompactBinary (FCbFieldView Field, int32 &OutValue, const int32 Default=0)
bool LoadFromCompactBinary (FCbFieldView Field, int64 &OutValue, const int64 Default=0)
bool LoadFromCompactBinary (FCbFieldView Field, int8 &OutValue, const int8 Default=0)
template<typename T, typename Allocator>
bool LoadFromCompactBinary (FCbFieldView Field, TArray< T, Allocator > &OutValue)
bool LoadFromCompactBinary (FCbFieldView Field, UE::FUtf8SharedString &OutString)
bool LoadFromCompactBinary (FCbFieldView Field, UE::FWideSharedString &OutString)
bool LoadFromCompactBinary (FCbFieldView Field, uint16 &OutValue, const uint16 Default=0)
bool LoadFromCompactBinary (FCbFieldView Field, uint32 &OutValue, const uint32 Default=0)
bool LoadFromCompactBinary (FCbFieldView Field, uint64 &OutValue, const uint64 Default=0)
bool LoadFromCompactBinary (FCbFieldView Field, uint8 &OutValue, const uint8 Default=0)
void UE::Serialization::Private::LogFieldTooLargeForArrayWarning (uint64 FieldLength)
Utility for logging problems with FCbField.
uint64 MeasureCompactBinary (FMemoryView View, ECbFieldType Type=ECbFieldType::HasFieldType)
Determine the size in bytes of the compact binary field at the start of the view.
FArchive & operator<< (FArchive &Ar, FCbArray &Array)
FArchive & operator<< (FArchive &Ar, FCbField &Field)
Serialize a compact binary value to/from an archive.
FArchive & operator<< (FArchive &Ar, FCbObject &Object)
void SaveCompactBinary (FArchive &Ar, const FCbArrayView &Array)
void SaveCompactBinary (FArchive &Ar, const FCbFieldView &Field)
Save a compact binary value to an archive.
void SaveCompactBinary (FArchive &Ar, const FCbObjectView &Object)
bool TryMeasureCompactBinary (FMemoryView InView, ECbFieldType &OutType, uint64 &OutSize, ECbFieldType InType=ECbFieldType::HasFieldType)
Try to determine the type and size of the compact binary field at the start of the view.
Function Documentation
CompactBinaryToCompactJson() [1/6]
void CompactBinaryToCompactJson (const FCbArrayView & Array, FUtf8StringBuilderBase & Builder)
References Array.
CompactBinaryToCompactJson() [2/6]
void CompactBinaryToCompactJson (const FCbArrayView & Array, FWideStringBuilderBase & Builder)
References Array.
CompactBinaryToCompactJson() [3/6]
void CompactBinaryToCompactJson (const FCbFieldView & Field, FUtf8StringBuilderBase & Builder)
Convert the compact binary to JSON in a compact format with no added whitespace.
CompactBinaryToCompactJson() [4/6]
void CompactBinaryToCompactJson (const FCbFieldView & Field, FWideStringBuilderBase & Builder)
CompactBinaryToCompactJson() [5/6]
void CompactBinaryToCompactJson (const FCbObjectView & Object, FUtf8StringBuilderBase & Builder)
References Object.
CompactBinaryToCompactJson() [6/6]
void CompactBinaryToCompactJson (const FCbObjectView & Object, FWideStringBuilderBase & Builder)
References Object.
CompactBinaryToJson() [1/6]
void CompactBinaryToJson (const FCbArrayView & Array, FUtf8StringBuilderBase & Builder)
References Array.
CompactBinaryToJson() [2/6]
void CompactBinaryToJson (const FCbArrayView & Array, FWideStringBuilderBase & Builder)
References Array.
CompactBinaryToJson() [3/6]
void CompactBinaryToJson (const FCbFieldView & Field, FUtf8StringBuilderBase & Builder)
Convert the compact binary to JSON in a multi-line format with indentation.
CompactBinaryToJson() [4/6]
void CompactBinaryToJson (const FCbFieldView & Field, FWideStringBuilderBase & Builder)
CompactBinaryToJson() [5/6]
void CompactBinaryToJson (const FCbObjectView & Object, FUtf8StringBuilderBase & Builder)
References Object.
CompactBinaryToJson() [6/6]
void CompactBinaryToJson (const FCbObjectView & Object, FWideStringBuilderBase & Builder)
References Object.
LoadCompactBinary()
FCbField LoadCompactBinary (FArchive & Ar, FCbBufferAllocator Allocator = FUniqueBuffer::Alloc)
Load a compact binary field from an archive.
The field may be an array or an object, which the caller can convert to by using AsArray or AsObject as appropriate. The buffer allocator is called to provide the buffer for the field to load into once its size has been determined.
Parameters
Ar Archive to read the field from. An error state is set on failure.
Allocator Allocator for the buffer that the field is loaded into.
Returns
A field with a reference to the allocated buffer, or a default field on failure.
References FUniqueBuffer::Alloc(), Allocator, and Ar.
LoadFromCompactBinary() [1/25]
bool LoadFromCompactBinary (FCbFieldView Field, bool & OutValue, const bool Default = false) inline
Definition at line 174 of file CompactBinarySerialization.h.
References FCbFieldView::AsBool(), Default, and FCbFieldView::HasError().
LoadFromCompactBinary() [2/25]
bool LoadFromCompactBinary (FCbFieldView Field, double & OutValue, const double Default = 0.0) inline
Definition at line 168 of file CompactBinarySerialization.h.
References FCbFieldView::AsDouble(), Default, and FCbFieldView::HasError().
LoadFromCompactBinary() [3/25]
bool LoadFromCompactBinary (FCbFieldView Field, FCbObjectId & OutValue, const FCbObjectId & Default = FCbObjectId()) inline
Definition at line 192 of file CompactBinarySerialization.h.
References FCbFieldView::AsObjectId(), Default, and FCbFieldView::HasError().
LoadFromCompactBinary() [4/25]
bool LoadFromCompactBinary (FCbFieldView Field, FDateTime & OutValue)
LoadFromCompactBinary() [5/25]
bool LoadFromCompactBinary (FCbFieldView Field, FDateTime & OutValue, FDateTime Default)
References Default.
LoadFromCompactBinary() [6/25]
bool LoadFromCompactBinary (FCbFieldView Field, FGuid & OutValue)
LoadFromCompactBinary() [7/25]
bool LoadFromCompactBinary (FCbFieldView Field, FGuid & OutValue, const FGuid & Default)
References Default.
LoadFromCompactBinary() [8/25]
bool LoadFromCompactBinary (FCbFieldView Field, FIoHash & OutValue, const FIoHash & Default = FIoHash()) inline
Definition at line 180 of file CompactBinarySerialization.h.
References FCbFieldView::AsHash(), Default, and FCbFieldView::HasError().
LoadFromCompactBinary() [9/25]
bool LoadFromCompactBinary (FCbFieldView Field, float & OutValue, const float Default = 0.0f) inline
Definition at line 162 of file CompactBinarySerialization.h.
References FCbFieldView::AsFloat(), Default, and FCbFieldView::HasError().
LoadFromCompactBinary() [10/25]
bool LoadFromCompactBinary (FCbFieldView Field, FName & OutValue)
LoadFromCompactBinary() [11/25]
bool LoadFromCompactBinary (FCbFieldView Field, FUtf8String & OutValue)
LoadFromCompactBinary() [12/25]
bool LoadFromCompactBinary (FCbFieldView Field, FUtf8StringBuilderBase & OutValue)
LoadFromCompactBinary attempts to load the output value from compact binary.
Implementations of LoadCompactBinary are expected to assign the output even on failure. Implementations may accept an optional default value to assign in case of load failure.
Returns
true if required fields had the values with the correct type and range, otherwise false.
Referenced by LoadFromCompactBinary().
LoadFromCompactBinary() [13/25]
bool LoadFromCompactBinary (FCbFieldView Field, FWideString & OutValue)
LoadFromCompactBinary() [14/25]
bool LoadFromCompactBinary (FCbFieldView Field, FWideStringBuilderBase & OutValue)
LoadFromCompactBinary() [15/25]
bool LoadFromCompactBinary (FCbFieldView Field, int16 & OutValue, const int16 Default = 0) inline
Definition at line 120 of file CompactBinarySerialization.h.
References FCbFieldView::AsInt16(), Default, and FCbFieldView::HasError().
LoadFromCompactBinary() [16/25]
bool LoadFromCompactBinary (FCbFieldView Field, int32 & OutValue, const int32 Default = 0) inline
Definition at line 126 of file CompactBinarySerialization.h.
References FCbFieldView::AsInt32(), Default, and FCbFieldView::HasError().
LoadFromCompactBinary() [17/25]
bool LoadFromCompactBinary (FCbFieldView Field, int64 & OutValue, const int64 Default = 0) inline
Definition at line 132 of file CompactBinarySerialization.h.
References FCbFieldView::AsInt64(), Default, and FCbFieldView::HasError().
LoadFromCompactBinary() [18/25]
bool LoadFromCompactBinary (FCbFieldView Field, int8 & OutValue, const int8 Default = 0) inline
Definition at line 114 of file CompactBinarySerialization.h.
References FCbFieldView::AsInt8(), Default, and FCbFieldView::HasError().
LoadFromCompactBinary() [19/25]
template<typename T, typename Allocator> bool LoadFromCompactBinary (FCbFieldView Field, TArray< T, Allocator > & OutValue) inline
Definition at line 199 of file CompactBinarySerialization.h.
References FCbFieldView::AsArrayView(), TArray< InElementType, InAllocatorType >::Emplace_GetRef(), FCbFieldView::HasError(), LoadFromCompactBinary(), UE::Serialization::Private::LogFieldTooLargeForArrayWarning(), MAX_int32, FCbArrayView::Num(), and TArray< InElementType, InAllocatorType >::Reset().
LoadFromCompactBinary() [20/25]
bool LoadFromCompactBinary (FCbFieldView Field, UE::FUtf8SharedString & OutString)
LoadFromCompactBinary() [21/25]
bool LoadFromCompactBinary (FCbFieldView Field, UE::FWideSharedString & OutString)
LoadFromCompactBinary() [22/25]
bool LoadFromCompactBinary (FCbFieldView Field, uint16 & OutValue, const uint16 Default = 0) inline
Definition at line 144 of file CompactBinarySerialization.h.
References FCbFieldView::AsUInt16(), Default, and FCbFieldView::HasError().
LoadFromCompactBinary() [23/25]
bool LoadFromCompactBinary (FCbFieldView Field, uint32 & OutValue, const uint32 Default = 0) inline
Definition at line 150 of file CompactBinarySerialization.h.
References FCbFieldView::AsUInt32(), Default, and FCbFieldView::HasError().
LoadFromCompactBinary() [24/25]
bool LoadFromCompactBinary (FCbFieldView Field, uint64 & OutValue, const uint64 Default = 0) inline
Definition at line 156 of file CompactBinarySerialization.h.
References FCbFieldView::AsUInt64(), Default, and FCbFieldView::HasError().
LoadFromCompactBinary() [25/25]
bool LoadFromCompactBinary (FCbFieldView Field, uint8 & OutValue, const uint8 Default = 0) inline
Definition at line 138 of file CompactBinarySerialization.h.
References FCbFieldView::AsUInt8(), Default, and FCbFieldView::HasError().
MeasureCompactBinary()
uint64 MeasureCompactBinary (FMemoryView View, ECbFieldType Type = ECbFieldType::HasFieldType)
Determine the size in bytes of the compact binary field at the start of the view.
This may be called on an incomplete or invalid field, in which case the returned size is zero. A size can always be extracted from a valid field with no name if a view of at least the first 10 bytes is provided, regardless of field size. For fields with names, the size of view needed to calculate a size is at most 10 + MaxNameLen + MeasureVarUInt(MaxNameLen).
This function can be used when streaming a field, for example, to determine the size of buffer to fill before attempting to construct a field from it.
Parameters
View A memory view that may contain the start of a field.
Type HasFieldType means that View contains the type. Otherwise, use the given type.
References HasFieldType.
operator<<() [1/3]
FArchive & operator<< (FArchive & Ar, FCbArray & Array)
References Ar, and Array.
operator<<() [2/3]
FArchive & operator<< (FArchive & Ar, FCbField & Field)
Serialize a compact binary value to/from an archive.
References Ar.
operator<<() [3/3]
FArchive & operator<< (FArchive & Ar, FCbObject & Object)
References Ar, and Object.
SaveCompactBinary() [1/3]
void SaveCompactBinary (FArchive & Ar, const FCbArrayView & Array)
References Ar, and Array.
SaveCompactBinary() [2/3]
void SaveCompactBinary (FArchive & Ar, const FCbFieldView & Field)
Save a compact binary value to an archive.
References Ar.
SaveCompactBinary() [3/3]
void SaveCompactBinary (FArchive & Ar, const FCbObjectView & Object)
References Ar, and Object.
TryMeasureCompactBinary()
bool TryMeasureCompactBinary (FMemoryView InView, ECbFieldType & OutType, uint64 & OutSize, ECbFieldType InType = ECbFieldType::HasFieldType)
Try to determine the type and size of the compact binary field at the start of the view.
This may be called on an incomplete or invalid field, in which case it will return false, with OutSize being 0 for invalid fields, otherwise the minimum view size necessary to make progress in measuring the field on the next call to this function.
Note
A return of true from this function does not indicate that the entire field is valid.
Parameters
InView A memory view that may contain the start of a field.
OutType The type (with flags) of the field. None is written until a value is available.
OutSize The total field size for a return of true, 0 for invalid fields, or the size to make progress in measuring the field on the next call to this function.
InType HasFieldType means that InView contains the type. Otherwise, use the given type.
Returns
true if the size of the field was determined, otherwise false.
References HasFieldType.