Unreal Engine 5.6 C++ API: Runtime/Core/Public/Misc/CoreMisc.h File Reference
CoreMisc.h File Reference
#include "Containers/Array.h"
#include "Containers/ContainerAllocationPolicies.h"
#include "Containers/Map.h"
#include "Containers/UnrealString.h"
#include "CoreGlobals.h"
#include "CoreTypes.h"
#include "HAL/PlatformProperties.h"
#include "HAL/ThreadSingleton.h"
#include "Logging/LogVerbosity.h"
#include "Math/IntPoint.h"
#include "Misc/Build.h"
#include "Misc/Exec.h"
#include "Templates/Function.h"
#include "UObject/NameTypes.h"
Data Structures
class FAutoNamedEventsToggler
Enables named events when profiling.
struct FBoolConfigValueHelper
Helper structure for boolean values in config.
class FContextSupplier
struct FMaintenance
struct FScopedScriptExceptionHandler
Exception handler stack used for script exceptions.
class FSelfRegisteringExec
Exec handler that registers itself and is being routed via StaticExec.
class FStaticSelfRegisteringExec
Registers a static Exec function using FSelfRegisteringExec.
class FStaticSelfRegisteringExec_Dev
Registers a static Exec_Dev function using FSelfRegisteringExec.
class FStaticSelfRegisteringExec_Editor
Registers a static Exec_Editor function using FSelfRegisteringExec.
struct FUrlConfig
Helper for obtaining the default Url configuration.
Macros
#define DO_BLUEPRINT_GUARD 1
This define enables the blueprint runaway and exception stack trace checks If this is true, it will create a FBlueprintContextTracker (previously FBlueprintExceptionTracker) which is defined in Script.h.
#define SCRIPT_AUDIT_ROUTINES 1
This define enables ScriptAudit exec commands.
Typedefs
typedef TFunction< void(ELogVerbosity::Type, const TCHAR *, const TCHAR *)> FScriptExceptionHandlerFunc
Function signature for handlers for script exceptions.
Functions
class FDerivedDataCacheInterface * GetDerivedDataCache ()
Returns the derived data cache interface if it is available, otherwise null.
class FDerivedDataCacheInterface & GetDerivedDataCacheRef ()
Returns the derived data cache interface, or fatal error if it is not available.
class ITargetPlatformManagerModule * GetTargetPlatformManager (bool bFailOnInitErrors=true)
Return the Target Platform Manager interface, if it is available, otherwise return nullptr.
class ITargetPlatformManagerModule & GetTargetPlatformManagerRef ()
Return the Target Platform Manager interface, fatal error if it is not available.
FORCEINLINE bool IsRunningClientOnly ()
Check to see if this executable was launched as a client only game process that should not load server data.
FORCEINLINE bool IsRunningDedicatedServer ()
Check to see if this executable was launched as a dedicated server process and should not load client only data.
FORCEINLINE bool IsRunningGame ()
Check to see if this executable was launched as a game (not editor or dedicated server) process.
bool StringHasBadDashes (const TCHAR *Str)
class FDerivedDataCacheInterface * TryGetDerivedDataCache ()
Returns the derived data cache interface if it is available and initialized, otherwise null.
bool WillNeedAudioVisualData ()
Return true if we are currently in a commandlet is targeting platforms with AV requirements (ie not a server) or we are not targetingother platforms, and the current platform needs to render (CanEverRender())
Macro Definition Documentation
DO_BLUEPRINT_GUARD
#define DO_BLUEPRINT_GUARD 1
This define enables the blueprint runaway and exception stack trace checks If this is true, it will create a FBlueprintContextTracker (previously FBlueprintExceptionTracker) which is defined in Script.h.
Definition at line 340 of file CoreMisc.h.
SCRIPT_AUDIT_ROUTINES
#define SCRIPT_AUDIT_ROUTINES 1
This define enables ScriptAudit exec commands.
Definition at line 349 of file CoreMisc.h.
Typedef Documentation
FScriptExceptionHandlerFunc
typedef TFunction<void(ELogVerbosity::Type , const TCHAR* , const TCHAR*)> FScriptExceptionHandlerFunc
Function signature for handlers for script exceptions.
Definition at line 258 of file CoreMisc.h.
Function Documentation
GetDerivedDataCache()
class FDerivedDataCacheInterface * GetDerivedDataCache ()
Returns the derived data cache interface if it is available, otherwise null.
GetDerivedDataCacheRef()
class FDerivedDataCacheInterface & GetDerivedDataCacheRef ()
Returns the derived data cache interface, or fatal error if it is not available.
GetTargetPlatformManager()
class ITargetPlatformManagerModule * GetTargetPlatformManager (bool bFailOnInitErrors = true)
Return the Target Platform Manager interface, if it is available, otherwise return nullptr.
Parameters
bFailOnInitErrors If true (default) and errors occur during init of the TPM, an error will be logged and the process may terminate, otherwise will return whether there was an error or not.
Returns
The Target Platform Manager interface, if it is available, otherwise return nullptr.
GetTargetPlatformManagerRef()
class ITargetPlatformManagerModule & GetTargetPlatformManagerRef ()
Return the Target Platform Manager interface, fatal error if it is not available.
IsRunningClientOnly()
FORCEINLINE bool IsRunningClientOnly ()
Check to see if this executable was launched as a client only game process that should not load server data.
This will be true for packaged builds with a Client target type which will define WITH_SERVER_CODE=0. An editor build can be launched with -clientonly to set this to true, but it will be false during single process PlayInEditor mode. This function should not be used for gameplay or networking purposes, check for NM_Client instead.
Definition at line 202 of file CoreMisc.h.
References FORCEINLINE.
IsRunningDedicatedServer()
FORCEINLINE bool IsRunningDedicatedServer ()
Check to see if this executable was launched as a dedicated server process and should not load client only data.
An editor build can be launched with -server to set this to true, but it will be false during single process PlayInEditor mode. This function should not be used for gameplay or networking purposes, check for NM_DedicatedServer instead.
Definition at line 152 of file CoreMisc.h.
References FORCEINLINE.
Referenced by FApp::CanEverRender(), FApp::CanEverRenderAudio(), UActorComponent::GetNetMode(), UActorComponent::IsNetMode(), and PhysSingleThreadedMode().
IsRunningGame()
FORCEINLINE bool IsRunningGame ()
Check to see if this executable was launched as a game (not editor or dedicated server) process.
This is true for both client only and client/server packaged games, call IsRunningClientOnly to differentiate. An editor build can be launched with -game to set this to true, but it will be false during single process PlayInEditor mode. This function should not be used for gameplay or networking purposes, check the NetMode instead.
Definition at line 177 of file CoreMisc.h.
References FORCEINLINE.
Referenced by FApp::IsGame().
StringHasBadDashes()
bool StringHasBadDashes (const TCHAR * Str)
TryGetDerivedDataCache()
class FDerivedDataCacheInterface * TryGetDerivedDataCache ()
Returns the derived data cache interface if it is available and initialized, otherwise null.
WillNeedAudioVisualData()
bool WillNeedAudioVisualData ()
Return true if we are currently in a commandlet is targeting platforms with AV requirements (ie not a server) or we are not targetingother platforms, and the current platform needs to render (CanEverRender())