Unreal Engine 5.6 C++ API: Runtime/Engine/Classes/Engine/DemoNetDriver.h File Reference
DemoNetDriver.h File Reference
#include "CoreMinimal.h"
#include "UObject/ObjectMacros.h"
#include "Serialization/BitReader.h"
#include "Misc/NetworkGuid.h"
#include "Engine/EngineBaseTypes.h"
#include "GameFramework/Actor.h"
#include "Misc/EngineVersion.h"
#include "GameFramework/PlayerController.h"
#include "Engine/NetDriver.h"
#include "Engine/PackageMapClient.h"
#include "Misc/NetworkVersion.h"
#include "NetworkReplayStreaming.h"
#include "Engine/DemoNetConnection.h"
#include "Net/RepLayout.h"
#include "Net/Core/Connection/NetResult.h"
#include "Net/ReplayResult.h"
#include "Templates/Atomic.h"
#include "Net/UnrealNetwork.h"
#include "ReplayHelper.h"
#include "DemoNetDriver.generated.h"
Data Structures
struct FDemoSavedRepObjectState
class FQueuedReplayTask
Typedefs
typedef TArray< struct FDemoSavedRepObjectState > FDemoSavedPropertyState
Functions
DECLARE_DELEGATE_OneParam (FOnGotoTimeDelegate, const bool)
PRAGMA_ENABLE_DEPRECATION_WARNINGS DECLARE_MULTICAST_DELEGATE (FOnDemoFinishPlaybackDelegate)
DECLARE_MULTICAST_DELEGATE (FOnDemoFinishRecordingDelegate)
DECLARE_MULTICAST_DELEGATE (FOnGotoTimeMCDelegate)
DECLARE_MULTICAST_DELEGATE_OneParam (FOnDemoStartedDelegate, UDemoNetDriver *)
DECLARE_MULTICAST_DELEGATE_OneParam (FOnPauseChannelsDelegate, const bool)
PRAGMA_DISABLE_DEPRECATION_WARNINGS UE_DEPRECATED (5.1, "No longer used") DECLARE_MULTICAST_DELEGATE_TwoParams(FOnDemoFailedToStartDelegate
USTRUCT () struct FRollbackNetStartupActorInfo
Information about net startup actors that need to be rolled back by being destroyed and re-created.
Typedef Documentation
FDemoSavedPropertyState
typedef TArray<struct FDemoSavedRepObjectState> FDemoSavedPropertyState
Definition at line 132 of file DemoNetDriver.h.
Function Documentation
DECLARE_DELEGATE_OneParam()
DECLARE_DELEGATE_OneParam (FOnGotoTimeDelegate , const bool)
DECLARE_MULTICAST_DELEGATE() [1/3]
PRAGMA_ENABLE_DEPRECATION_WARNINGS DECLARE_MULTICAST_DELEGATE (FOnDemoFinishPlaybackDelegate)
References DECLARE_MULTICAST_DELEGATE.
DECLARE_MULTICAST_DELEGATE() [2/3]
DECLARE_MULTICAST_DELEGATE (FOnDemoFinishRecordingDelegate)
References DECLARE_MULTICAST_DELEGATE.
DECLARE_MULTICAST_DELEGATE() [3/3]
DECLARE_MULTICAST_DELEGATE (FOnGotoTimeMCDelegate)
DECLARE_MULTICAST_DELEGATE_OneParam() [1/2]
DECLARE_MULTICAST_DELEGATE_OneParam (FOnDemoStartedDelegate , UDemoNetDriver *)
References PRAGMA_DISABLE_DEPRECATION_WARNINGS.
DECLARE_MULTICAST_DELEGATE_OneParam() [2/2]
DECLARE_MULTICAST_DELEGATE_OneParam (FOnPauseChannelsDelegate , const bool)
References DECLARE_MULTICAST_DELEGATE_OneParam.
UE_DEPRECATED()
PRAGMA_DISABLE_DEPRECATION_WARNINGS UE_DEPRECATED (5. 1, "No longer used")
References DECLARE_MULTICAST_DELEGATE_TwoParams, and PRAGMA_ENABLE_DEPRECATION_WARNINGS.
USTRUCT()
USTRUCT ()
Information about net startup actors that need to be rolled back by being destroyed and re-created.
Definition at line 66 of file DemoNetDriver.h.
References Ar, TArray< InElementType, InAllocatorType >::CountBytes(), TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::CountBytes(), FVector, GENERATED_BODY, TSharedPtr< ObjectType, InMode >::Get(), Location, Name, Rotation, and UPROPERTY.