var dir_234072ddc78cfddda610dccb0d7a1f28 =
[
    [ "Commands", "dir_5d211b511de399da95ac3d845a7f293e.html", "dir_5d211b511de399da95ac3d845a7f293e" ],
    [ "Properties", "dir_4b7b7998257c003c1020f35e066aea4d.html", "dir_4b7b7998257c003c1020f35e066aea4d" ],
    [ "Sculpting", "dir_f97bbe49c64e28dde8a9ed69942820e8.html", "dir_f97bbe49c64e28dde8a9ed69942820e8" ],
    [ "ToolActivities", "dir_3ed9edfc030faf0165e8313330c8572a.html", "dir_3ed9edfc030faf0165e8313330c8572a" ],
    [ "AddPrimitiveTool.h", "AddPrimitiveTool_8h.html", "AddPrimitiveTool_8h" ],
    [ "CombineMeshesTool.h", "CombineMeshesTool_8h.html", "CombineMeshesTool_8h" ],
    [ "ConvertToPolygonsTool.h", "ConvertToPolygonsTool_8h.html", "ConvertToPolygonsTool_8h" ],
    [ "CSGMeshesTool.h", "CSGMeshesTool_8h.html", "CSGMeshesTool_8h" ],
    [ "CutMeshWithMeshTool.h", "CutMeshWithMeshTool_8h.html", "CutMeshWithMeshTool_8h" ],
    [ "DeformMeshPolygonsTool.h", "DeformMeshPolygonsTool_8h.html", "DeformMeshPolygonsTool_8h" ],
    [ "DisplaceMeshTool.h", "DisplaceMeshTool_8h.html", "DisplaceMeshTool_8h" ],
    [ "DrawAndRevolveTool.h", "DrawAndRevolveTool_8h.html", "DrawAndRevolveTool_8h" ],
    [ "DrawPolygonTool.h", "DrawPolygonTool_8h.html", "DrawPolygonTool_8h" ],
    [ "DynamicMeshBrushTool.h", "DynamicMeshBrushTool_8h.html", "DynamicMeshBrushTool_8h" ],
    [ "DynamicMeshSculptTool.h", "DynamicMeshSculptTool_8h.html", "DynamicMeshSculptTool_8h" ],
    [ "EditMeshPolygonsTool.h", "EditMeshPolygonsTool_8h.html", "EditMeshPolygonsTool_8h" ],
    [ "HoleFillTool.h", "HoleFillTool_8h.html", "HoleFillTool_8h" ],
    [ "LatticeDeformerTool.h", "LatticeDeformerTool_8h.html", "LatticeDeformerTool_8h" ],
    [ "MeshAttributePaintTool.h", "MeshAttributePaintTool_8h.html", "MeshAttributePaintTool_8h" ],
    [ "MeshGroupPaintTool.h", "MeshGroupPaintTool_8h.html", "MeshGroupPaintTool_8h" ],
    [ "MeshModelingTools.h", "MeshModelingTools_8h.html", "MeshModelingTools_8h" ],
    [ "MeshSpaceDeformerTool.h", "MeshSpaceDeformerTool_8h.html", "MeshSpaceDeformerTool_8h" ],
    [ "MeshVertexPaintTool.h", "MeshVertexPaintTool_8h.html", "MeshVertexPaintTool_8h" ],
    [ "MeshVertexSculptTool.h", "MeshVertexSculptTool_8h.html", "MeshVertexSculptTool_8h" ],
    [ "OffsetMeshTool.h", "OffsetMeshTool_8h.html", "OffsetMeshTool_8h" ],
    [ "ProjectToTargetTool.h", "ProjectToTargetTool_8h.html", "ProjectToTargetTool_8h" ],
    [ "RecomputeUVsTool.h", "RecomputeUVsTool_8h.html", "RecomputeUVsTool_8h" ],
    [ "RemeshMeshTool.h", "RemeshMeshTool_8h.html", "RemeshMeshTool_8h" ],
    [ "RemoveOccludedTrianglesTool.h", "RemoveOccludedTrianglesTool_8h.html", "RemoveOccludedTrianglesTool_8h" ],
    [ "SmoothMeshTool.h", "SmoothMeshTool_8h.html", "SmoothMeshTool_8h" ],
    [ "UVLayoutTool.h", "UVLayoutTool_8h.html", "UVLayoutTool_8h" ],
    [ "UVProjectionTool.h", "UVProjectionTool_8h.html", "UVProjectionTool_8h" ],
    [ "WeldMeshEdgesTool.h", "WeldMeshEdgesTool_8h.html", "WeldMeshEdgesTool_8h" ]
];