Unreal Engine 5.6 C++ API: Runtime/Engine/Classes/Components/DirectionalLightComponent.h File Reference
DirectionalLightComponent.h File Reference
#include "CoreMinimal.h"
#include "UObject/ObjectMacros.h"
#include "Engine/EngineTypes.h"
#include "Components/LightComponent.h"
#include "DirectionalLightComponent.generated.h"
Data Structures
class UDirectionalLightComponent
Functions
UCLASS ()
A light component that has parallel rays.
Variables
editinlinenew
meta =(BlueprintSpawnableComponent)
Function Documentation
UCLASS()
UCLASS ()
A light component that has parallel rays.
Will provide a uniform lighting across any affected surface (eg. The Sun). This will affect all objects in the defined light-mass importance volume.
Variable Documentation
editinlinenew
editinlinenew
Definition at line 17 of file DirectionalLightComponent.h.
meta
meta =(BlueprintSpawnableComponent)
Definition at line 17 of file DirectionalLightComponent.h.
Referenced by UDirectionalLightComponent::GENERATED_UCLASS_BODY(), UDirectionalLightComponent::UPROPERTY(), UDirectionalLightComponent::UPROPERTY(), UDirectionalLightComponent::UPROPERTY(), UDirectionalLightComponent::UPROPERTY(), UDirectionalLightComponent::UPROPERTY(), UDirectionalLightComponent::UPROPERTY(), UDirectionalLightComponent::UPROPERTY(), UDirectionalLightComponent::UPROPERTY(), UDirectionalLightComponent::UPROPERTY(), UDirectionalLightComponent::UPROPERTY(), UDirectionalLightComponent::UPROPERTY(), UDirectionalLightComponent::UPROPERTY(), UDirectionalLightComponent::UPROPERTY(), UDirectionalLightComponent::UPROPERTY(), UDirectionalLightComponent::UPROPERTY(), UDirectionalLightComponent::UPROPERTY(), UDirectionalLightComponent::UPROPERTY(), UDirectionalLightComponent::UPROPERTY(), UDirectionalLightComponent::UPROPERTY(), UDirectionalLightComponent::UPROPERTY(), and UDirectionalLightComponent::UPROPERTY().