Unreal Engine 5.6 C++ API: Runtime/Engine/Classes/EdGraph/EdGraphPin.h File Reference
EdGraphPin.h File Reference
#include "CoreMinimal.h"
#include "UObject/ObjectMacros.h"
#include "UObject/Object.h"
#include "UObject/ObjectPtr.h"
#include "Misc/Guid.h"
#include "UObject/Class.h"
#include "UObject/WeakObjectPtr.h"
#include "Templates/Casts.h"
#include "EdGraph/EdGraphNode.h"
#include "EdGraphPin.generated.h"
Data Structures
struct TStructOpsTypeTraits< FEdGraphPinType >
class UEdGraphPin
Enumerations
enum class EPinInsertPosition { Before , After }
Functions
FORCEINLINE FArchive & operator<< (FArchive &Ar, FSimpleMemberReference &Data)
USTRUCT () struct FEdGraphPinType
Struct used to define the type of information carried on this pin.
Enumeration Type Documentation
EPinInsertPosition
enum class EPinInsertPosition strong
Enumerator
Before
After
Definition at line 19 of file EdGraphPin.h.
Function Documentation
operator<<()
FORCEINLINE FArchive & operator<< (FArchive & Ar, FSimpleMemberReference & Data)
Definition at line 66 of file EdGraphPin.h.
References Ar, and FORCEINLINE.
USTRUCT()
USTRUCT ()
Struct used to define the type of information carried on this pin.
Most often the Class that this member is defined in. Could be a UPackage if it is a native delegate signature function (declared globally).
Name of the member
The Guid of the member
Category of pin type
Sub-category of pin type
Sub-category object
Sub-category member reference
Data used to determine value types when bIsMap is true
UE_DEPRECATED(4.17) Whether or not this pin represents an array of values
Whether or not this pin is a value passed by reference or not
Whether or not this pin is a immutable const value
Whether or not this is a weak reference
Whether or not this is a "wrapped" Unreal object ptr type (e.g. TSubclassOf<T> instead of UClass*)
Set to true if the type was serialized prior to BlueprintPinsUseRealNumbers
Constructors
Sets the pin referred to by this struct
Gets the pin referred to by this struct
The node that owns the pin referred to by this struct. Updated at Set and Save time.
The pin's unique ID. Updated at Set and Save time.
Definition at line 25 of file EdGraphPin.h.
References Cast(), GENERATED_USTRUCT_BODY, operator=(), operator==(), Other, Reset, and UPROPERTY.