Unreal Engine 5.6 C++ API: Runtime/MovieScene/Public/EditorSequenceNavigationDefs.h File Reference
EditorSequenceNavigationDefs.h File Reference
#include "EditorSequenceNavigationDefs.generated.h"
Data Structures
struct TStructOpsTypeTraits< FNavigationToolSerializedTree >
Macros
#define UE_API MOVIESCENE_API
Functions
UENUM() enum class ENavigationToolItemFlags ENUM_CLASS_FLAGS (ENavigationToolItemFlags)
USTRUCT () struct FNavigationToolSerializedItem
Macro Definition Documentation
UE_API
#define UE_API MOVIESCENE_API
Definition at line 7 of file EditorSequenceNavigationDefs.h.
Function Documentation
ENUM_CLASS_FLAGS()
UENUM() enum class ENavigationToolItemFlags ENUM_CLASS_FLAGS (ENavigationToolItemFlags)
USTRUCT()
USTRUCT ()
Index of this tree node relative to the parent node children items. Can be used as means of ordering.
Index of this tree node in the owning tree
Absolute Index of the Parent Node in the owning tree. If INDEX_NONE, it means Parent is Root.
Absolute indices of the children in the owning tree
Pointer to the tree that owns this node
Items specific to this Navigation Tool Instance, rather than being shared across Navigation Tools (e.g. Expansion flags)
Map of the column Ids to their overriden (i.e. saved) visibility
Active list of item filters
Definition at line 22 of file EditorSequenceNavigationDefs.h.
References GENERATED_BODY, GetTypeHash(), IsValid(), operator==(), and UPROPERTY.