Unreal Engine 5.6 C++ API: S:/Development/U_E/UE_5.6/Engine/Plugins/Media/PixelStreaming2/Source/PixelStreaming2RTC/Internal/EpicRtcVideoCommon.h File Reference
EpicRtcVideoCommon.h File Reference
#include "Containers/Utf8String.h"
#include "Video/DependencyDescriptor.h"
#include "Video/GenericFrameInfo.h"
#include "Video/VideoEncoder.h"
#include "epic_rtc/containers/epic_rtc_array.h"
#include "epic_rtc/containers/epic_rtc_string_view.h"
#include "epic_rtc/core/video/video_buffer.h"
#include "epic_rtc/core/video/video_codec_info.h"
#include "epic_rtc_helper/memory/ref_count_impl_helper.h"
Data Structures
class UE::PixelStreaming2::FEpicRtcBoolArray
class UE::PixelStreaming2::FEpicRtcCodecBufferUsageArray
class UE::PixelStreaming2::FEpicRtcDecodeTargetIndicationArray
class UE::PixelStreaming2::FEpicRtcEncodedVideoBuffer
class UE::PixelStreaming2::FEpicRtcFrameDependencyStructure
class UE::PixelStreaming2::FEpicRtcGenericFrameInfo
class UE::PixelStreaming2::FEpicRtcGenericFrameInfoArray
class UE::PixelStreaming2::FEpicRtcInt32Array
class UE::PixelStreaming2::FEpicRtcParameterPair
class UE::PixelStreaming2::FEpicRtcParameterPairArray
class UE::PixelStreaming2::FEpicRtcPixelFormatArray
class UE::PixelStreaming2::FEpicRtcScalabilityModeArray
class UE::PixelStreaming2::FEpicRtcString
class UE::PixelStreaming2::FEpicRtcVideoCodecInfo
class UE::PixelStreaming2::FEpicRtcVideoFrameTypeArray
class UE::PixelStreaming2::FEpicRtcVideoParameterPairArray
class UE::PixelStreaming2::FEpicRtcVideoResolutionArray
class UE::PixelStreaming2::FEpicRtcVideoResolutionBitrateLimitsArray
class UE::PixelStreaming2::FVideoCodecInfoArray
Namespaces
namespace UE
Utility functions for applying transformations to meshes.
namespace UE::PixelStreaming2
Functions
FORCEINLINE bool operator== (const EpicRtcVideoResolution &Lhs, const EpicRtcVideoResolution &Rhs)
Function Documentation
operator==()
FORCEINLINE bool operator== (const EpicRtcVideoResolution & Lhs, const EpicRtcVideoResolution & Rhs)
Definition at line 16 of file EpicRtcVideoCommon.h.
References FORCEINLINE.
Referenced by DECLARE_DYNAMIC_DELEGATE_TwoParams(), DECLARE_MULTICAST_DELEGATE_OneParam(), DECLARE_MULTICAST_DELEGATE_OneParam(), DECLARE_STATS_GROUP(), ENUM_CLASS_FLAGS(), ENUM_CLASS_FLAGS(), FPropertyValueIterator::FRIEND_ENUM_CLASS_FLAGS(), MS_ALIGN(), FConstStructView::operator!=(), FStructView::operator!=(), FWidgetReference::operator!=(), TConstStructView< BaseStructT >::operator!=(), TStructView< BaseStructT >::operator!=(), UE::Geometry::FSparseDynamicPointOctree3::ParallelInsertDensePointSet(), SHADER_PARAMETER_TEXTURE(), UE_DEPRECATED(), UE_DEPRECATED(), UWorldPartitionDestructibleHLODComponent::UPROPERTY(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), and USTRUCT().