Unreal Engine 5.6 C++ API: Runtime/Engine/Classes/PhysicsEngine/ExternalSpatialAccelerationPayload.h File Reference
ExternalSpatialAccelerationPayload.h File Reference
#include "Chaos/ChaosArchive.h"
#include "Chaos/Declares.h"
#include "Chaos/GeometryParticlesfwd.h"
#include "Chaos/ParticleHandleFwd.h"
#include "Chaos/SpatialAccelerationFwd.h"
#include "UObject/Object.h"
#include "UObject/ObjectKey.h"
#include "ExternalSpatialAccelerationPayload.generated.h"
Typedefs
using IExternalSpatialAcceleration = Chaos::ISpatialAcceleration<FExternalSpatialAccelerationPayload, Chaos::FReal, 3>
Functions
FORCEINLINE_DEBUGGABLE Chaos::FChaosArchive & operator<< (Chaos::FChaosArchive &Ar, FExternalSpatialAccelerationPayload &AccelerationHandle)
USTRUCT () struct FExternalSpatialAccelerationPayload
This is a Chaos spatial acceleration payload that can be used for spatial acceleration structures that are meant to only be used in external contexts.
Typedef Documentation
IExternalSpatialAcceleration
using IExternalSpatialAcceleration = Chaos::ISpatialAcceleration<FExternalSpatialAccelerationPayload, Chaos::FReal, 3>
Definition at line 58 of file ExternalSpatialAccelerationPayload.h.
Function Documentation
operator<<()
FORCEINLINE_DEBUGGABLE Chaos::FChaosArchive & operator<< (Chaos::FChaosArchive & Ar, FExternalSpatialAccelerationPayload & AccelerationHandle)
Definition at line 70 of file ExternalSpatialAccelerationPayload.h.
References Ar, and FORCEINLINE_DEBUGGABLE.
USTRUCT()
USTRUCT ()
This is a Chaos spatial acceleration payload that can be used for spatial acceleration structures that are meant to only be used in external contexts.
This provides safety as we aren't holding particle handles directly but rather going through the primitive component's physics object interface to grab them when needed.
Definition at line 22 of file ExternalSpatialAccelerationPayload.h.
References Ar, Component, GENERATED_BODY, GetTypeHash(), INDEX_NONE, Initialize, IsValid(), operator!=(), operator==(), and Other.