Unreal Engine 5.6 C++ API: Runtime/CoreUObject/Public/UObject/FastReferenceCollector.h File Reference
FastReferenceCollector.h File Reference
#include "CoreMinimal.h"
#include "Stats/Stats.h"
#include "UObject/GarbageCollection.h"
#include "UObject/GarbageCollectionSchema.h"
#include "UObject/Class.h"
#include "UObject/Package.h"
#include "Async/TaskGraphInterfaces.h"
#include "UObject/UnrealType.h"
#include "Misc/ScopeLock.h"
#include "HAL/PlatformProcess.h"
#include "UObject/FieldPath.h"
#include "Async/ParallelFor.h"
#include "UObject/UObjectArray.h"
#include "UObject/DynamicallyTypedValue.h"
#include "UObject/GCObject.h"
Data Structures
class FGarbageCollectionTracer
Interface to allow external systems to trace additional object references, used for bridging GCs.
struct FGCInternals
Helper to give GC internals friend access to certain core classes.
class FSimpleReferenceProcessorBase
Simple single-threaded reference processor base class for use with CollectReferences()
struct UE::GC::FDebugSchemaStackNode
Maintains a stack of schemas currently processed by reachability analysis for debugging referencing property names.
struct UE::GC::FDebugSchemaStackNoOpScope
struct UE::GC::FDebugSchemaStackScope
class UE::GC::FPrefetchingObjectIterator
struct UE::GC::FProcessorStats
struct UE::GC::FSlowARO
struct UE::GC::FStructArray
struct UE::GC::FSuspendedStructBatch
struct UE::GC::FWeakReferenceInfo
struct UE::GC::FWorkBlock
Fixed block of reachable objects waiting to be processed.
class UE::GC::FWorkBlockifier
Reachable objects waiting to be processed.
struct UE::GC::FWorkerContext
Thread-local context containing initial objects and references to collect.
struct UE::GC::Private::FMemberUnpacked
struct UE::GC::Private::FMemberWordUnpacked
struct UE::GC::Private::FStridedReferenceArray
struct UE::GC::Private::FStridedReferenceIterator
struct UE::GC::Private::FStridedReferenceView
class UE::GC::TDefaultCollector< ProcessorType >
Default reference collector for CollectReferences()
struct UE::GC::TDirectDispatcher< ProcessorType >
Forwards references directly to ProcessorType::HandleTokenStreamObjectReference(), unlike TBatchDispatcher.
class UE::GC::TFastReferenceCollector< ProcessorType, CollectorType >
Helper class that looks for UObject references by traversing UClass token stream and calls AddReferencedObjects.
struct UE::GC::TFastReferenceCollector< ProcessorType, CollectorType >::HasFlushWork< T, typename >
struct UE::GC::TFastReferenceCollector< ProcessorType, CollectorType >::HasFlushWork< T, std::void_t< decltype(std::declval< T >().FlushWork())> >
struct UE::GC::TGetDispatcherType< CollectorType, ProcessorType, class >
Namespaces
namespace UE
Utility functions for applying transformations to meshes.
namespace UE::GC
namespace UE::GC::Private
Typedefs
using EGCTokenType = UE::GC::EOrigin
using UE::GC::ETokenlessId = EMemberlessId
using FGCArrayStruct = UE::GC::FWorkerContext
using UE::GC::FTokenId = FMemberId
using FTokenInfo = UE::GC::FMemberInfo
Enumerations
enum class EGCOptions : uint32 {
None = 0 , Parallel = 1 << 0 , AutogenerateSchemas = 1 << 1 , UE_DEPRECATED =(5.4, "WithPendingKill should no longer be used. Use EliminateGarbage.") = 1 << 2 ,
EliminateGarbage = 1 << 2 , IncrementalReachability = 1 << 3
}
enum class UE::GC::ELoot { UE::GC::Nothing , UE::GC::Block , UE::GC::ARO , UE::GC::Context }
Functions
FORCEINLINE FStridedReferenceIterator UE::GC::Private::begin (FStridedReferenceView View)
template<class DispatcherType>
FORCEINLINE_DEBUGGABLE void UE::GC::Private::CallARO (DispatcherType &Dispatcher, uint8 *Instance, FMemberWord Word)
template<class DispatcherType>
FORCEINLINE_DEBUGGABLE void UE::GC::Private::CallARO (DispatcherType &Dispatcher, UObject *Instance, FMemberWord Word)
template<class DispatcherType>
FORCEINLINE void UE::GC::Private::CallSlowARO (DispatcherType &, uint32 SlowAROIdx, uint8 *Instance, uint32 MemberIdx)
template<class DispatcherType>
FORCEINLINE_DEBUGGABLE void UE::GC::Private::CallSlowARO (DispatcherType &Dispatcher, uint32 SlowAROIdx, UObject *Instance, uint32 MemberIdx)
template<class CollectorType, class ProcessorType>
static FORCEINLINE void CollectReferences (ProcessorType &Processor, UE::GC::FWorkerContext &Context)
template<class ProcessorType>
static FORCEINLINE void CollectReferences (ProcessorType &Processor, UE::GC::FWorkerContext &Context)
FORCEINLINE FStridedReferenceIterator UE::GC::Private::end (FStridedReferenceView View)
ENUM_CLASS_FLAGS (EGCOptions)
template<class CollectorType, class ProcessorType>
TDirectDispatcher< ProcessorType > UE::GC::GetDispatcher (CollectorType &Collector, ProcessorType &Processor, FWorkerContext &Context)
FORCEINLINE int32 UE::GC::Private::GetNum (FStridedReferenceView View)
int32 GetNumCollectReferenceWorkers ()
FORCEINLINE const uint8 * UE::GC::Private::GetSparseData (const FScriptSparseArray &Array)
FORCEINLINE uint8 * UE::GC::Private::GetSparseData (FScriptSparseArray &Array)
constexpr bool IsEliminatingGarbage (EGCOptions Options)
constexpr bool IsParallel (EGCOptions Options)
static FORCENOINLINE void UE::GC::Private::LogIllegalTypeFatal (EMemberType Type, uint32 Idx, uint8 *)
static FORCENOINLINE void UE::GC::Private::LogIllegalTypeFatal (EMemberType Type, uint32 Idx, UObject *Instance)
void UE::GC::PadObjectArray (TArray< UObject * > &Objects)
void UE::GC::ProcessAsync (void(*ProcessSync)(void *, FWorkerContext &), void *Processor, FWorkerContext &InitialContext)
Allocates contexts and coordinator, kicks worker tasks that also call ProcessSync.
ELoot UE::GC::StealWork (FWorkerContext &Context, FReferenceCollector &Collector, FWorkBlock *&OutBlock, EGCOptions Options)
void UE::GC::SuspendWork (FWorkerContext &Context)
FORCEINLINE FStridedReferenceView UE::GC::Private::ToView (FStridedReferenceArray In)
UE_DEPRECATED (5.4, "IsPendingKill should no longer be used. Use IsEliminatingGarbage.") inline const expr bool IsPendingKill(EGCOptions Options)
template<class DispatcherType>
FORCEINLINE_DEBUGGABLE void UE::GC::Private::VisitDynamicallyTypedValue (DispatcherType &Dispatcher, UE::FDynamicallyTypedValue &Value)
template<class DispatcherType>
FORCEINLINE_DEBUGGABLE void UE::GC::Private::VisitFieldPath (DispatcherType &Dispatcher, FFieldPath &FieldPath, EOrigin Origin, uint32 MemberIdx)
template<class DispatcherType>
FORCEINLINE_DEBUGGABLE void UE::GC::Private::VisitFieldPathArray (DispatcherType &Dispatcher, TArray< FFieldPath > &FieldPaths, EOrigin Origin, uint32 MemberIdx)
template<class DispatcherType, typename ObjectType>
FORCEINLINE_DEBUGGABLE void UE::GC::Private::VisitMembers (DispatcherType &Dispatcher, FSchemaView Schema, ObjectType *Instance)
template<class DispatcherType>
FORCENOINLINE void UE::GC::Private::VisitNestedStructMembers (DispatcherType &Dispatcher, FSchemaView Schema, uint8 *Instance)
template<class DispatcherType>
void UE::GC::Private::VisitNestedStructMembers (DispatcherType &Dispatcher, FSchemaView Schema, uint8 *Instance)
template<class DispatcherType>
FORCEINLINE_DEBUGGABLE void UE::GC::Private::VisitOptional (DispatcherType &Dispatcher, FSchemaView StructSchema, uint8 *Instance)
template<class DispatcherType>
FORCEINLINE_DEBUGGABLE void UE::GC::Private::VisitSparseStructArray (DispatcherType &Dispatcher, FSchemaView StructSchema, FScriptSparseArray &Array)
template<class DispatcherType, class ArrayType>
FORCEINLINE_DEBUGGABLE void UE::GC::Private::VisitStructArray (DispatcherType &Dispatcher, FSchemaView StructSchema, ArrayType &Array)
template<class DispatcherType>
FORCEINLINE_DEBUGGABLE void UE::GC::Private::VisitStructs (DispatcherType &Dispatcher, FSchemaView StructSchema, uint8 *It, const int32 Num)
Variables
constexpr EGCOptions UE::GC::DefaultOptions = EGCOptions::AutogenerateSchemas
static constexpr uint32 UE::GC::ObjectLookahead = 16
Typedef Documentation
EGCTokenType
using EGCTokenType = UE::GC::EOrigin
Definition at line 1172 of file FastReferenceCollector.h.
FGCArrayStruct
using FGCArrayStruct = UE::GC::FWorkerContext
Definition at line 1173 of file FastReferenceCollector.h.
FTokenInfo
using FTokenInfo = UE::GC::FMemberInfo
Definition at line 1171 of file FastReferenceCollector.h.
Enumeration Type Documentation
EGCOptions
enum class EGCOptions : uint32 strong
Enumerator
None
Parallel
AutogenerateSchemas
UE_DEPRECATED
EliminateGarbage
IncrementalReachability
Definition at line 42 of file FastReferenceCollector.h.
Function Documentation
CollectReferences() [1/2]
template<class CollectorType, class ProcessorType> FORCEINLINE void CollectReferences (ProcessorType & Processor, UE::GC::FWorkerContext & Context) static
Definition at line 1145 of file FastReferenceCollector.h.
References UE::GC::Context, FORCEINLINE, UE::GC::GIsIncrementalReachabilityPending, IsParallel(), and UE::GC::ProcessAsync().
Referenced by CollectReferences().
CollectReferences() [2/2]
template<class ProcessorType> FORCEINLINE void CollectReferences (ProcessorType & Processor, UE::GC::FWorkerContext & Context) static
Definition at line 1161 of file FastReferenceCollector.h.
References CollectReferences(), UE::GC::Context, and FORCEINLINE.
ENUM_CLASS_FLAGS()
ENUM_CLASS_FLAGS (EGCOptions)
GetNumCollectReferenceWorkers()
int32 GetNumCollectReferenceWorkers ()
IsEliminatingGarbage()
bool IsEliminatingGarbage (EGCOptions Options) inline constexpr
Definition at line 55 of file FastReferenceCollector.h.
References EliminateGarbage.
IsParallel()
bool IsParallel (EGCOptions Options) inline constexpr
Definition at line 53 of file FastReferenceCollector.h.
References Parallel.
Referenced by UE::GC::FWorkBlockifier::Add(), CollectReferences(), and UE::GC::FWorkBlockifier::PopFullBlock().
UE_DEPRECATED()
UE_DEPRECATED (5. 4, "IsPendingKill should no longer be used. Use IsEliminatingGarbage.") const
Definition at line 56 of file FastReferenceCollector.h.
References EliminateGarbage.