Unreal Engine 5.6 C++ API: Runtime/CoreUObject/Public/UObject/Field.h File Reference
Field.h File Reference
#include "Containers/Array.h"
#include "Containers/LinkedListBuilder.h"
#include "Containers/Map.h"
#include "Containers/StringFwd.h"
#include "Containers/UnrealString.h"
#include "CoreTypes.h"
#include "Delegates/Delegate.h"
#include "HAL/PlatformMath.h"
#include "HAL/PreprocessorHelpers.h"
#include "HAL/UnrealMemory.h"
#include "Internationalization/Text.h"
#include "Math/RandomStream.h"
#include "Misc/AssertionMacros.h"
#include "Misc/CString.h"
#include "Misc/EnumClassFlags.h"
#include "Misc/Guid.h"
#include "Misc/Optional.h"
#include "Serialization/Archive.h"
#include "Serialization/StructuredArchive.h"
#include "Serialization/StructuredArchiveAdapters.h"
#include "Serialization/StructuredArchiveSlots.h"
#include "Templates/EnableIf.h"
#include "Templates/IsAbstract.h"
#include "Templates/IsEnum.h"
#include "Templates/Requires.h"
#include "Templates/TypeHash.h"
#include "Templates/UnrealTemplate.h"
#include "Templates/UnrealTypeTraits.h"
#include "UObject/CoreNative.h"
#include "UObject/GarbageCollection.h"
#include "UObject/NameTypes.h"
#include "UObject/Object.h"
#include "UObject/ObjectMacros.h"
#include "UObject/PersistentObjectPtr.h"
#include "UObject/Script.h"
#include "UObject/SparseDelegate.h"
#include "UObject/UObjectGlobals.h"
#include "UObject/UnrealNames.h"
#include "UObject/WeakObjectPtr.h"
#include <type_traits>
Data Structures
class FField
Base class of reflection data objects.
class FFieldClass
Object representing a type of an FField struct.
class FFieldVariant
Special container that can hold either UObject or FField.
union FFieldVariant::FFieldObjectUnion
Macros
#define DECLARE_FIELD(TClass, TSuperClass, TStaticFlags)
#define DECLARE_FIELD_API(TClass, TSuperClass, TStaticFlags, TRequiredAPI)
#define DECLARE_FIELD_NEW_IMPLEMENTATION(TClass)
#define IMPLEMENT_FIELD(TClass)
#define IMPLEMENT_FIELD_CONSTRUCT_IMPLEMENTATION(TClass)
Functions
template<typename FieldType>
FORCEINLINE const FieldType * CastField (const FField *Src)
template<typename FieldType>
FORCEINLINE FieldType * CastField (FField *Src)
template<typename FieldType>
FUNCTION_NON_NULL_RETURN_START FORCEINLINE const FieldType * CastFieldChecked (const FField *Src) FUNCTION_NON_NULL_RETURN_END
template<typename FieldType>
FUNCTION_NON_NULL_RETURN_START FORCEINLINE FieldType * CastFieldChecked (FField *Src) FUNCTION_NON_NULL_RETURN_END
template<typename FieldType>
FORCEINLINE const FieldType * CastFieldCheckedNullAllowed (const FField *Src)
template<typename FieldType>
FORCEINLINE FieldType * CastFieldCheckedNullAllowed (FField *Src)
template<typename FieldType>
FORCEINLINE FieldType * ExactCastField (const FField *Src)
template<typename FieldType>
FORCEINLINE FieldType * ExactCastField (FField *Src)
template<typename FieldType>
FieldType * FindFProperty (const TCHAR *InFieldPath)
Templated version of FindFieldByPath.
FField * FindFPropertyByPath (const TCHAR *InFieldPath)
Finds a field given a path to the field (Package.Class[:Subobject:...]:FieldName)
FName GetFNameSafe (const FField *InField)
Gets the name of the provided field.
FString GetFullNameSafe (const FField *InField)
Gets the full name of the provided field.
FString GetNameSafe (const FField *InField)
Gets the name of the provided field.
FString GetPathNameSafe (const FField *InField)
Gets the path name of the provided field.
template<typename FieldType>
void SerializeSingleField (FArchive &Ar, FieldType *&Field, FFieldVariant Owner)
Helper function for serializing FField to an archive.
Macro Definition Documentation
DECLARE_FIELD
#define DECLARE_FIELD (TClass, TSuperClass, TStaticFlags)
Value:
    DECLARE_FIELD_API(TClass, TSuperClass, TStaticFlags, NO_API)
Definition at line 191 of file Field.h.
DECLARE_FIELD_API
#define DECLARE_FIELD_API (TClass, TSuperClass, TStaticFlags, TRequiredAPI)
Definition at line 194 of file Field.h.
DECLARE_FIELD_NEW_IMPLEMENTATION
#define DECLARE_FIELD_NEW_IMPLEMENTATION (TClass)
Value:
        ThisClass* Mem = (ThisClass*)FMemory::Malloc(InSize); \
        new (Mem) TClass(EC_InternalUseOnlyConstructor, TClass::StaticClass()); \
        return Mem;
Definition at line 181 of file Field.h.
IMPLEMENT_FIELD
#define IMPLEMENT_FIELD (TClass)
Value:
FField* TClass::Construct(const FFieldVariant& InOwner, const FName& InName, EObjectFlags InFlags) \
{ \
    IMPLEMENT_FIELD_CONSTRUCT_IMPLEMENTATION(TClass) \
} \
FFieldClass* TClass::StaticClass() \
{ \
    static FFieldClass StaticFieldClass(TEXT(PREPROCESSOR_TO_STRING(TClass)), TClass::StaticClassCastFlagsPrivate(), TClass::StaticClassCastFlags(), TClass::Super::StaticClass(), &TClass::Construct); \
    return &StaticFieldClass; \
} \
Definition at line 249 of file Field.h.
IMPLEMENT_FIELD_CONSTRUCT_IMPLEMENTATION
#define IMPLEMENT_FIELD_CONSTRUCT_IMPLEMENTATION (TClass)
Value:
        FField* Instance = new TClass(InOwner, InName, InFlags); \
        return Instance;
Definition at line 241 of file Field.h.
Function Documentation
CastField() [1/2]
template<typename FieldType> FORCEINLINE const FieldType * CastField (const FField * Src)
Definition at line 975 of file Field.h.
References FORCEINLINE, and FField::IsA().
CastField() [2/2]
template<typename FieldType> FORCEINLINE FieldType * CastField (FField * Src)
Definition at line 969 of file Field.h.
References FORCEINLINE, and FField::IsA().
Referenced by FPropertyBagArrayRef::FPropertyBagArrayRef(), FPropertyBagSetRef::FPropertyBagSetRef(), TFieldPath< T >::TFieldPath(), FComponentEditorUtils::ApplyDefaultValueChange(), FComponentEditorUtils::ApplyDefaultValueChange(), RigVMTypeUtils::AreCompatible(), FRigVMGraphEnumDetailCustomization::ContainerMemoryBlockToEnumPtr(), FRigVMGraphMathTypeDetailCustomization::ContainerMemoryBlockToValueRef(), UBlueprintMapLibrary::DECLARE_FUNCTION(), UBlueprintMapLibrary::DECLARE_FUNCTION(), UBlueprintMapLibrary::DECLARE_FUNCTION(), UBlueprintMapLibrary::DECLARE_FUNCTION(), UBlueprintMapLibrary::DECLARE_FUNCTION(), UBlueprintMapLibrary::DECLARE_FUNCTION(), UBlueprintMapLibrary::DECLARE_FUNCTION(), UBlueprintMapLibrary::DECLARE_FUNCTION(), UBlueprintMapLibrary::DECLARE_FUNCTION(), UBlueprintMapLibrary::DECLARE_FUNCTION(), UBlueprintMapLibrary::DECLARE_FUNCTION(), UBlueprintMapLibrary::DECLARE_FUNCTION(), UBlueprintSetLibrary::DECLARE_FUNCTION(), UBlueprintSetLibrary::DECLARE_FUNCTION(), UBlueprintSetLibrary::DECLARE_FUNCTION(), UBlueprintSetLibrary::DECLARE_FUNCTION(), UBlueprintSetLibrary::DECLARE_FUNCTION(), UBlueprintSetLibrary::DECLARE_FUNCTION(), UBlueprintSetLibrary::DECLARE_FUNCTION(), UBlueprintSetLibrary::DECLARE_FUNCTION(), UBlueprintSetLibrary::DECLARE_FUNCTION(), UBlueprintSetLibrary::DECLARE_FUNCTION(), UBlueprintSetLibrary::DECLARE_FUNCTION(), UBlueprintSetLibrary::DECLARE_FUNCTION(), UBlueprintSetLibrary::DECLARE_FUNCTION(), UBlueprintSetLibrary::DECLARE_FUNCTION(), UBlueprintSetLibrary::DECLARE_FUNCTION(), UKismetArrayLibrary::DECLARE_FUNCTION(), UKismetArrayLibrary::DECLARE_FUNCTION(), UKismetArrayLibrary::DECLARE_FUNCTION(), UKismetArrayLibrary::DECLARE_FUNCTION(), UKismetArrayLibrary::DECLARE_FUNCTION(), UKismetArrayLibrary::DECLARE_FUNCTION(), UKismetArrayLibrary::DECLARE_FUNCTION(), UKismetArrayLibrary::DECLARE_FUNCTION(), UKismetArrayLibrary::DECLARE_FUNCTION(), UKismetArrayLibrary::DECLARE_FUNCTION(), UKismetArrayLibrary::DECLARE_FUNCTION(), UKismetArrayLibrary::DECLARE_FUNCTION(), UKismetArrayLibrary::DECLARE_FUNCTION(), UKismetArrayLibrary::DECLARE_FUNCTION(), UKismetArrayLibrary::DECLARE_FUNCTION(), UKismetArrayLibrary::DECLARE_FUNCTION(), UKismetArrayLibrary::DECLARE_FUNCTION(), UKismetArrayLibrary::DECLARE_FUNCTION(), UKismetArrayLibrary::DECLARE_FUNCTION(), UKismetArrayLibrary::DECLARE_FUNCTION(), UKismetArrayLibrary::DECLARE_FUNCTION(), UKismetArrayLibrary::DECLARE_FUNCTION(), UKismetArrayLibrary::DECLARE_FUNCTION(), UKismetArrayLibrary::DECLARE_FUNCTION(), UKismetArrayLibrary::DECLARE_FUNCTION(), UE::Private::TDoesParamMatchImpl< T >::DoesMatchProperty(), UE::Private::TDoesParamMatchImpl< T< ReferenceType > >::DoesMatchProperty(), UE::Private::TDoesParamMatchImpl< TArray< ContainedType > >::DoesMatchProperty(), UE::Private::TDoesParamMatchImpl< TMap< KeyType, ValueType > >::DoesMatchProperty(), UE::Private::TDoesParamMatchImpl< TMulticastDelegate< SignatureType > >::DoesMatchProperty(), UE::Private::TDoesParamMatchImpl< TOptional< ContainedType > >::DoesMatchProperty(), UE::Private::TDoesParamMatchImpl< TScriptDelegate< SignatureType > >::DoesMatchProperty(), UE::Private::TDoesParamMatchImpl< TSet< ContainedType > >::DoesMatchProperty(), UE::Private::TDoesParamMatchImpl< TSparseDynamicDelegate< SignatureType, OwningClass, InfoGetter > >::DoesMatchProperty(), FindFProperty(), FAnimatedPropertyKey::FromProperty(), FBindingObject::Get(), FRigVMMemoryHandle::GetArrayElementProperty(), EditorAnimUtils::GetAssetsFromProperties(), FPropertyChangedParams::GetPropertyValue(), FMediaIOCustomizationBase::GetPropertyValueFromPropertyHandle(), FPropertyTrackEditor< TrackType >::InitializeNewTrack(), IsCustomDeltaProperty(), FRigVMMemoryHandle::IsEnum(), FRigVMMemoryHandle::IsEnumArray(), FRigVMMemoryHandle::IsObject(), FRigVMMemoryHandle::IsObjectArray(), FRigVMMemoryHandle::IsStruct(), FRigVMMemoryHandle::IsStructArray(), UE::StateTree::PropertyRefHelpers::Validator< T, decltype(TBaseStructure< T >::Get, void())>::IsValid(), UE::StateTree::PropertyRefHelpers::Validator< T, typename TEnableIf< TIsDerivedFrom< typename TRemovePointer< T >::Type, UObject >::IsDerived >::Type >::IsValid(), UE::StateTree::PropertyRefHelpers::Validator< T, typename TEnableIf< TIsEnum< T >::Value >::Type >::IsValid(), UE::StateTree::PropertyRefHelpers::Validator< T, typename TEnableIf< TIsTArray_V< T >, void >::Type >::IsValid(), FFrame::ReadVariableSize(), SerializeSingleField(), and FFrame::StepCompiledInRef().
CastFieldChecked() [1/2]
template<typename FieldType> FUNCTION_NON_NULL_RETURN_START FORCEINLINE const FieldType * CastFieldChecked (const FField * Src)
Definition at line 1008 of file Field.h.
References checkf, FORCEINLINE, FUNCTION_NON_NULL_RETURN_END, and TEXT.
CastFieldChecked() [2/2]
template<typename FieldType> FUNCTION_NON_NULL_RETURN_START FORCEINLINE FieldType * CastFieldChecked (FField * Src)
Definition at line 994 of file Field.h.
References checkf, FORCEINLINE, FUNCTION_NON_NULL_RETURN_END, and TEXT.
Referenced by FRigVMMemoryHandle::GetArrayElementPropertyChecked(), FRigVMMemoryHandle::GetData_Internal(), IAnimBlueprintNodeCopyTermDefaultsContext::GetDestinationNode(), FTrackInstancePropertyBindings::FResolvedProperty::GetPropertyAddress(), IAnimBlueprintNodeCopyTermDefaultsContext::GetSourceNode(), FPoseLinkMappingRecord::MakeFromArrayEntry(), TAllFieldsIterator< T >::operator*(), and TAllFieldsIterator< T >::operator->().
CastFieldCheckedNullAllowed() [1/2]
template<typename FieldType> FORCEINLINE const FieldType * CastFieldCheckedNullAllowed (const FField * Src)
Definition at line 1033 of file Field.h.
References checkf, FORCEINLINE, FField::IsA(), and TEXT.
CastFieldCheckedNullAllowed() [2/2]
template<typename FieldType> FORCEINLINE FieldType * CastFieldCheckedNullAllowed (FField * Src)
Definition at line 1021 of file Field.h.
References checkf, FORCEINLINE, FField::IsA(), and TEXT.
ExactCastField() [1/2]
template<typename FieldType> FORCEINLINE FieldType * ExactCastField (const FField * Src)
Definition at line 987 of file Field.h.
References FORCEINLINE, and FField::GetClass().
ExactCastField() [2/2]
template<typename FieldType> FORCEINLINE FieldType * ExactCastField (FField * Src)
Definition at line 981 of file Field.h.
References FORCEINLINE, and FField::GetClass().
FindFProperty()
template<typename FieldType> FieldType * FindFProperty (const TCHAR * InFieldPath) inline
Templated version of FindFieldByPath.
Definition at line 1120 of file Field.h.
References CastField(), and FindFPropertyByPath().
Referenced by FindFProperty(), FindUFieldOrFProperty(), and FKismetVariableDragDropAction::GetVariableProperty().
FindFPropertyByPath()
FField * FindFPropertyByPath (const TCHAR * InFieldPath)
Finds a field given a path to the field (Package.Class[:Subobject:...]:FieldName)
Referenced by FindFProperty().
GetFNameSafe()
FName GetFNameSafe (const FField * InField) inline
Gets the name of the provided field.
If the field pointer is null, the result is "none"
Definition at line 1079 of file Field.h.
References FField::GetFName().
GetFullNameSafe()
FString GetFullNameSafe (const FField * InField)
Gets the full name of the provided field.
If the field pointer is null, the result is "none"
GetNameSafe()
FString GetNameSafe (const FField * InField) inline
Gets the name of the provided field.
If the field pointer is null, the result is "none"
Definition at line 1093 of file Field.h.
References FField::GetName(), and TEXT.
Referenced by UE::GC::Private::LogIllegalTypeFatal().
GetPathNameSafe()
FString GetPathNameSafe (const FField * InField)
Gets the path name of the provided field.
If the field pointer is null, the result is "none"
Referenced by FRepHandleIterator::FRepHandleIterator(), UE::GC::Private::LogIllegalTypeFatal(), and FGameplayAbilityInputBinds::TryFixShortEnumName().
SerializeSingleField()
template<typename FieldType> void SerializeSingleField (FArchive & Ar, FieldType *& Field, FFieldVariant Owner) inline
Helper function for serializing FField to an archive.
This function fully serializes the field and its properties.
Definition at line 1048 of file Field.h.
References Ar, CastField(), check, FField::Construct(), Owner, and RF_NoFlags.