Unreal Engine 5.6 C++ API: S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/GameplayAbilities/Source/GameplayAbilities/Public/GameplayEffectAttributeCaptureDefinition.h File Reference
GameplayEffectAttributeCaptureDefinition.h File Reference
#include "AttributeSet.h"
#include "GameplayEffectAttributeCaptureDefinition.generated.h"
Macros
#define UE_API GAMEPLAYABILITIES_API
Functions
UENUM() enum class EGameplayEffectAttributeCaptureSource USTRUCT () struct FGameplayEffectAttributeCaptureDefinition
Enumeration for options of where to capture gameplay attributes from for gameplay effects.
Macro Definition Documentation
UE_API
#define UE_API GAMEPLAYABILITIES_API
Definition at line 8 of file GameplayEffectAttributeCaptureDefinition.h.
Function Documentation
USTRUCT()
UENUM() enum class EGameplayEffectAttributeCaptureSource USTRUCT ()
Enumeration for options of where to capture gameplay attributes from for gameplay effects.
Struct defining gameplay attribute capture options for gameplay effects
Gameplay attribute to capture
Source of the gameplay attribute
Whether the attribute should be snapshotted or not
Equality/Inequality operators
Get type hash for the capture definition; Implemented to allow usage in TMap
Parameters
CaptureDef Capture definition to get the type hash of
Definition at line 22 of file GameplayEffectAttributeCaptureDefinition.h.
References BlueprintType, Capture, Category, GENERATED_USTRUCT_BODY, GetTypeHash(), Hash, HashCombine(), operator!=(), operator==(), Other, UE_API, and UPROPERTY.