Unreal Engine 5.6 C++ API: Runtime/GameplayTasks/Classes/GameplayTask.h File Reference
GameplayTask.h File Reference
#include "CoreMinimal.h"
#include "UObject/ObjectMacros.h"
#include "UObject/Object.h"
#include "Templates/SubclassOf.h"
#include "UObject/ScriptInterface.h"
#include "UObject/ScriptMacros.h"
#include "GameplayTaskOwnerInterface.h"
#include "UObject/WeakInterfacePtr.h"
#include "GameplayTaskTypes.h"
#include "GameplayTask.generated.h"
Data Structures
struct FGameplayTaskInstanceClassPredicate
struct FGameplayTaskInstanceNamePredicate
class UGameplayTask
Functions
GAMEPLAYTASKS_API DECLARE_LOG_CATEGORY_EXTERN (LogGameplayTasks, Log, All)
UCLASS ()
UENUM() enum class EGameplayTaskState UENUM() enum class ETaskResourceOverlapPolicy USTRUCT () struct FGameplayResourceSet
Variables
config = Game
Function Documentation
DECLARE_LOG_CATEGORY_EXTERN()
GAMEPLAYTASKS_API DECLARE_LOG_CATEGORY_EXTERN (LogGameplayTasks , Log , All)
References Active, All, Finished, Log, Paused, and Uninitialized.
UCLASS()
UCLASS ()
USTRUCT()
UENUM() enum class EGameplayTaskState UENUM() enum class ETaskResourceOverlapPolicy USTRUCT ()
Mind that this constructor takes flags not individual IDs
Definition at line 44 of file GameplayTask.h.
References BlueprintType, Clear(), ensure, Flags, GENERATED_USTRUCT_BODY, operator!=(), operator==(), and Other.
Variable Documentation
config
config = Game
Definition at line 144 of file GameplayTask.h.
Referenced by UGameplayTask::UPROPERTY().