Unreal Engine 5.6 C++ API: S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/GameplayAbilities/Source/GameplayAbilities/Public/GameplayEffect.h File Reference
GameplayEffect.h File Reference
#include "CoreMinimal.h"
#include "UObject/ObjectMacros.h"
#include "UObject/Object.h"
#include "UObject/Class.h"
#include "Templates/SubclassOf.h"
#include "Engine/NetSerialization.h"
#include "Engine/EngineTypes.h"
#include "GameplayTagContainer.h"
#include "Engine/CurveTable.h"
#include "AttributeSet.h"
#include "EngineDefines.h"
#include "GameplayEffectTypes.h"
#include "GameplayEffectAggregator.h"
#include "GameplayPrediction.h"
#include "GameplayTagAssetInterface.h"
#include "GameplayAbilitySpec.h"
#include "ActiveGameplayEffectIterator.h"
#include "UObject/ObjectKey.h"
#include "VisualLogger/VisualLoggerDebugSnapshotInterface.h"
#include "VisualLogger/VisualLoggerTypes.h"
#include "GameplayEffect.generated.h"
Data Structures
struct FCustomModifierDependencyHandle
Helper struct to hold data about external dependencies for custom modifiers.
struct FGameplayEffectConstants
Enumeration outlining the possible gameplay effect magnitude calculation policies.
struct FScopedActiveGameplayEffectLock
FScopedActiveGameplayEffectLock Provides a mechanism for locking the active gameplay effect list while possibly invoking callbacks into gamecode.
struct TStructOpsTypeTraits< FActiveGameplayEffectsContainer >
Active GameplayEffects Container -Bucket of ActiveGameplayEffects -Needed for FFastArraySerialization.
struct TStructOpsTypeTraits< FGameplayEffectModifierMagnitude >
struct TStructOpsTypeTraits< FGameplayEffectVersion >
Macros
#define GAMEPLAYEFFECT_SCOPE_LOCK()
#define UE_API GAMEPLAYABILITIES_API
Functions
USTRUCT() struct FActiveGameplayEffect DECLARE_DELEGATE_RetVal_OneParam (bool, FActiveGameplayEffectQueryCustomMatch, const FActiveGameplayEffect &)
Active GameplayEffect instance -What GameplayEffect Spec -Start time -When to execute next -Replication callbacks.
DECLARE_DYNAMIC_DELEGATE_TwoParams (FActiveGameplayEffectQueryCustomMatch_Dynamic, FActiveGameplayEffect, Effect, bool &, bMatches)
UCLASS ()
UGameplayEffect The GameplayEffect definition.
USTRUCT () struct FAttributeBasedFloat
Struct representing a float whose magnitude is dictated by a backing attribute and a calculation policy, follows basic form of: (Coefficient * (PreMultiplyAdditiveValue + [Eval'd Attribute Value According to Policy])) + PostMultiplyAdditiveValue.
Macro Definition Documentation
GAMEPLAYEFFECT_SCOPE_LOCK
#define GAMEPLAYEFFECT_SCOPE_LOCK ()
Value:
FScopedActiveGameplayEffectLock ActiveScopeLock(*this);
Definition at line 2023 of file GameplayEffect.h.
UE_API
#define UE_API GAMEPLAYABILITIES_API
Definition at line 27 of file GameplayEffect.h.
Referenced by FScopedActiveGameplayEffectLock::FScopedActiveGameplayEffectLock(), and FScopedActiveGameplayEffectLock::~FScopedActiveGameplayEffectLock().
Function Documentation
DECLARE_DELEGATE_RetVal_OneParam()
USTRUCT() struct FActiveGameplayEffect DECLARE_DELEGATE_RetVal_OneParam (bool , FActiveGameplayEffectQueryCustomMatch , const FActiveGameplayEffect &)
Active GameplayEffect instance -What GameplayEffect Spec -Start time -When to execute next -Replication callbacks.
References DECLARE_DELEGATE_RetVal_OneParam.
DECLARE_DYNAMIC_DELEGATE_TwoParams()
DECLARE_DYNAMIC_DELEGATE_TwoParams (FActiveGameplayEffectQueryCustomMatch_Dynamic , FActiveGameplayEffect , Effect , bool & , bMatches)
References BlueprintType, Category, DECLARE_DYNAMIC_DELEGATE_TwoParams, GENERATED_USTRUCT_BODY, operator!=(), operator=(), operator==(), Other, UE_API, UPROPERTY, and USTRUCT.
UCLASS()
UCLASS ()
UGameplayEffect The GameplayEffect definition.
This is the data asset defined in the editor that drives everything. This is only blueprintable to allow for templating gameplay effects. Gameplay effects should NOT contain blueprint graphs.
References Attribute, Blueprintable, Category, Deprecated, Duration, GENERATED_UCLASS_BODY, meta, MinimalAPI, PostLoad, PreSave, PrioritizeCategories, ShortTooltip, Tags, Transient, UE_API, UE_DEPRECATED, and UPROPERTY.
USTRUCT()
USTRUCT ()
Struct representing a float whose magnitude is dictated by a backing attribute and a calculation policy, follows basic form of: (Coefficient * (PreMultiplyAdditiveValue + [Eval'd Attribute Value According to Policy])) + PostMultiplyAdditiveValue.
Gameplay Effects Data needs to be versioned (e.g.
Generic querying data structure for active GameplayEffects.
Every set condition within this query must match in order for the query to match.
This is a cut down version of the gameplay effect spec used for RPCs.
GameplayEffect Specification.
Struct used to handle a collection of captured source and target attributes.
Struct used to hold the result of a gameplay attribute capture; Initially seeded by definition data, but then populated by ability system component when appropriate.
Saves list of modified attributes, to use for gameplay cues or later processing.
Gameplay effect duration policies.
Structure that is used to combine tags from parent and child blueprints in a safe way.
FGameplayEffectCue This is a cosmetic cue that can be tied to a UGameplayEffect.
FGameplayModifierInfo Tells us "Who/What we" modify Does not tell us how exactly.
Struct representing the definition of a custom execution for a gameplay effect.
Struct for gameplay effects that apply only if another gameplay effect (or execution) was successfully applied.
Enumeration representing the types of scoped modifier aggregator usages available.
Struct representing the magnitude of a gameplay effect modifier, potentially calculated in numerous different ways.
Struct for holding SetBytCaller data.
Structure to encapsulate magnitudes that are calculated via custom calculation.
Struct representing modifier info used exclusively for "scoped" executions that happen instantaneously. These are folded into a calculation only for the extent of the calculation and never permanently added to an aggregator.
Custom executions run special logic from an outside class each time the gameplay effect executes.
This is essentially a GameplayTag + a Min/Max level range that is used to map the level of a GameplayEffect to a normalized value used by the GameplayCue system.
Enumeration of policies for dealing with duration of a gameplay effect while stacking Enumeration of policies for dealing with the period of a gameplay effect while stacking Enumeration of policies for dealing gameplay effect stacks that expire (in duration based effects). Enumeration of policies for dealing with the period of a gameplay effect when inhibition is removed Holds evaluated magnitude from a GameplayEffect modifier
Tells us: -What UGameplayEffect (const data) -What Level -Who instigated
FGameplayEffectSpec is modifiable. We start with initial conditions and modifications be applied to it. In this sense, it is stateful/mutable but it is still distinct from an FActiveGameplayEffect which in an applied instance of an FGameplayEffectSpec.
i.e. individual query elements are ANDed together.
Lets us ask things like: Give me duration/magnitude of active gameplay effects with these tags Give me handles to all activate gameplay effects modifying this attribute.
Any requirements specified in the query are required: must meet "all" not "one".
going from Monolithic to Modular) Unfortunately, the Custom Package Versioning doesn't work for this case, because we're upgrading outside of the Serialize function. For that reason we want to store a UProperty that says what version we're on. Unfortunately that propagates from Parent to Child (inheritance rules) so to overcome that, we have a special UStruct that always serializes its data (so it will always be loaded, not inherited). Here is how to do that:
Return false in Identical (which effectively disables delta serialization).
Reset the value in PostInitProperties, thereby not using the inherited value on the initial preload.
Ensure the CurrentVersion field isn't marked up as a UPROPERTY to avoid automatic copying between parent/child.
Implement Serialize to ensure the CurrentVersion is still serialized.
Constructor
Calculate and return the magnitude of the float given the specified gameplay effect spec.
Note
: This function assumes (and asserts on) the existence of the required captured attribute within the spec. It is the responsibility of the caller to verify that the spec is properly setup before calling this function.
Parameters
InRelevantSpec Gameplay effect spec providing the backing attribute capture
Returns
Evaluated magnitude based upon the spec & calculation policy
Coefficient to the attribute calculation
Additive value to the attribute calculation, added in before the coefficient applies
Additive value to the attribute calculation, added in after the coefficient applies
Attribute backing the calculation
If a curve table entry is specified, the attribute will be used as a lookup into the curve instead of using the attribute directly.
Calculation policy in regards to the attribute
Channel to terminate evaluation on when using AttributeEvaluatedUpToChannel calculation type
Filter to use on source tags; If specified, only modifiers applied with all of these tags will factor into the calculation
Filter to use on target tags; If specified, only modifiers applied with all of these tags will factor into the calculation
Equality/Inequality operators
Calculate and return the magnitude of the float given the specified gameplay effect spec.
Note
: This function assumes (and asserts on) the existence of the required captured attribute within the spec. It is the responsibility of the caller to verify that the spec is properly setup before calling this function.
Parameters
InRelevantSpec Gameplay effect spec providing the backing attribute capture
Returns
Evaluated magnitude based upon the spec & calculation policy
Coefficient to the custom calculation
Additive value to the attribute calculation, added in before the coefficient applies
Additive value to the attribute calculation, added in after the coefficient applies
If a curve table entry is specified, the OUTPUT of this custom class magnitude (including the pre and post additive values) lookup into the curve instead of using the attribute directly.
Equality/Inequality operators
The Name the caller (code or blueprint) will use to set this magnitude by.
Equality/Inequality operators
Default Constructor
Constructors for setting value in code (for automation tests)
Determines if the magnitude can be properly calculated with the specified gameplay effect spec (could fail if relying on an attribute not present, etc.)
Parameters
InRelevantSpec Gameplay effect spec to check for magnitude calculation
Returns
Whether or not the magnitude can be properly calculated
Attempts to calculate the magnitude given the provided spec. May fail if necessary information (such as captured attributes) is missing from the spec.
Parameters
InRelevantSpec Gameplay effect spec to use to calculate the magnitude with
OutCalculatedMagnitude [OUT] Calculated value of the magnitude, will be set to 0.f in the event of failure
Returns
True if the calculation was successful, false if it was not
Attempts to recalculate the magnitude given a changed aggregator. This will only recalculate if we are a modifier that is linked (non snapshot) to the given aggregator.
Gather all of the attribute capture definitions necessary to compute the magnitude and place them into the provided array
Parameters
OutCaptureDefs [OUT] Array populated with necessary attribute capture definitions
Returns the magnitude as it was entered in data. Only applies to ScalableFloat or any other type that can return data without context
Returns the DataName associated with this magnitude if it is set by caller
Returns SetByCaller data structure, for inspection purposes
Returns the custom magnitude calculation class, if any, for this magnitude. Only applies to CustomMagnitudes
Implementing Serialize to clear references to assets that are not needed
Type of calculation to perform to derive the magnitude
Magnitude value represented by a scalable float
Magnitude value represented by an attribute-based float (Coefficient * (PreMultiplyAdditiveValue + [Eval'd Attribute Value According to Policy])) + PostMultiplyAdditiveValue
Magnitude value represented by a custom calculation class
Magnitude value represented by a SetByCaller magnitude
Backing attribute that the scoped modifier is for
Identifier for aggregator if acting as a transient "temporary variable" aggregator
Type of aggregator backing the scoped mod
Modifier operation to perform
Magnitude of the scoped modifier
Evaluation channel settings of the scoped modifier
Source tag requirements for the modifier to apply
Target tag requirements for the modifier to apply
gameplay effect that will be applied to the target
Tags that the source must have for this GE to apply. If this is blank, then there are no requirements to apply the EffectClass.
Gathers and populates the specified array with the capture definitions that the execution would like in order to perform its custom calculation. Up to the individual execution calculation to handle if some of them are missing or not.
Parameters
OutCaptureDefs [OUT] Capture definitions requested by the execution
Custom execution calculation class to run when the gameplay effect executes
These tags are passed into the execution as is, and may be used to do conditional logic
Modifiers that are applied "in place" during the execution calculation
Other Gameplay Effects that will be applied to the target of this execution if the execution is successful. Note if no execution class is selected, these will always apply.
The Attribute we modify or the GE we modify modifies.
The numeric operation of this modifier: Override, Add, Multiply, etc When multiple modifiers aggregate together, the equation is: ((BaseValue + AddBase) * MultiplyAdditive / DivideAdditive * MultiplyCompound) + AddFinal
Magnitude of the modifier
Evaluation channel settings of the modifier
Equality/Inequality operators
The attribute to use as the source for cue magnitude. If none use level
The minimum level that this Cue supports
The maximum level that this Cue supports
Tags passed to the gameplay cue handler when this cue is activated
Tags that I inherited and tags that I added minus tags that I removed
Tags that I have (in addition to my parent's tags)
Tags that should be removed (only if my parent had them). Note: we cannot use this to remove a tag that exists on a target. It only modifies the result of CombinedTags.
Apply the Added and Removed tags to the passed-in container (does not have to be the previously configured Parent!)
Add a tag that will appear in addition to any inherited tags
Remove a tag that will be omitted from any inherited tags
In the event that the modifier spec requires custom magnitude calculations, this is the authoritative, last evaluated value of the magnitude
These structures are the only ones that should internally be able to update the EvaluatedMagnitude. Any gamecode that gets its hands on FModifierSpec should never be setting EvaluatedMagnitude manually
The attribute that has been modified
Total magnitude applied to that attribute
Returns whether the spec actually has a valid capture yet or not
Returns
True if the spec has a valid attribute capture, false if it does not
Attempts to calculate the magnitude of the captured attribute given the specified parameters. Can fail if the spec doesn't have a valid capture yet.
Parameters
InEvalParams Parameters to evaluate the attribute under
OutMagnitude [OUT] Computed magnitude
Returns
True if the magnitude was successfully calculated, false if it was not
Attempts to calculate the magnitude of the captured attribute given the specified parameters, up to the specified evaluation channel (inclusive). Can fail if the spec doesn't have a valid capture yet.
Parameters
InEvalParams Parameters to evaluate the attribute under
FinalChannel Evaluation channel to terminate the calculation at
OutMagnitude [OUT] Computed magnitude
Returns
True if the magnitude was successfully calculated, false if it was not
Attempts to calculate the magnitude of the captured attribute given the specified parameters, including a starting base value. Can fail if the spec doesn't have a valid capture yet.
Parameters
InEvalParams Parameters to evaluate the attribute under
InBaseValue Base value to evaluate the attribute under
OutMagnitude [OUT] Computed magnitude
Returns
True if the magnitude was successfully calculated, false if it was not
Attempts to calculate the base value of the captured attribute given the specified parameters. Can fail if the spec doesn't have a valid capture yet.
Parameters
OutBaseValue [OUT] Computed base value
Returns
True if the base value was successfully calculated, false if it was not
Attempts to calculate the "bonus" magnitude (final - base value) of the captured attribute given the specified parameters. Can fail if the spec doesn't have a valid capture yet.
Parameters
InEvalParams Parameters to evaluate the attribute under
OutBonusMagnitude [OUT] Computed bonus magnitude
Returns
True if the bonus magnitude was successfully calculated, false if it was not
Attempts to calculate the contribution of the specified GE to the captured attribute given the specified parameters. Can fail if the spec doesn't have a valid capture yet.
Parameters
InEvalParams Parameters to evaluate the attribute under
ActiveHandle Handle of the gameplay effect to query about
OutBonusMagnitude [OUT] Computed bonus magnitude
Returns
True if the bonus magnitude was successfully calculated, false if it was not
Attempts to populate the specified aggregator with a snapshot of the backing captured aggregator. Can fail if the spec doesn't have a valid capture yet.
Parameters
OutAggregatorSnapshot [OUT] Snapshotted aggregator, if possible
Returns
True if the aggregator was successfully snapshotted, false if it was not
Attempts to populate the specified aggregator with all of the mods of the backing captured aggregator. Can fail if the spec doesn't have a valid capture yet.
Parameters
OutAggregatorToAddTo [OUT] Aggregator with mods appended, if possible
Returns
True if the aggregator had mods successfully added to it, false if it did not
Gathers made for a given capture. Note all mods are returned but only some will be qualified (use Qualified() func to determine)
Simple accessor to backing capture definition
Register this handle with linked aggregators
Unregister this handle with linked aggregators
Return true if this capture should be recalculated if the given aggregator has changed
Swaps any internal references From aggregator To aggregator. Used when cloning
Copy of the definition the spec should adhere to for capturing
Ref to the aggregator for the captured attribute
Add a definition to be captured by the owner of the container. Will not add the definition if its exact match already exists within the container.
Parameters
InCaptureDefinition Definition to capture with
Capture source or target attributes from the specified component. Should be called by the container's owner.
Parameters
InAbilitySystemComponent Component to capture attributes from
InCaptureSource Whether to capture attributes as source or target
Find a capture spec within the container matching the specified capture definition, if possible.
Parameters
InDefinition Capture definition to use as the search basis
bOnlyIncludeValidCapture If true, even if a spec is found, it won't be returned if it doesn't also have a valid capture already
Returns
The found attribute spec matching the specified search params, if any
Determines if the container has specs with valid captures for all of the specified definitions.
Parameters
InCaptureDefsToCheck Capture definitions to check for
Returns
True if the container has valid capture attributes for all of the specified definitions, false if it does not
Returns whether the container has at least one spec w/o snapshotted attributes
Registers any linked aggregators to notify this active handle if they are dirtied
Unregisters any linked aggregators from notifying this active handle if they are dirtied
Swaps any internal references From aggregator To aggregator. Used when cloning
Captured attributes from the source of a gameplay effect
Captured attributes from the target of a gameplay effect
If true, has at least one capture spec that did not request a snapshot
Can be called manually but it is preferred to use the 3 parameter constructor
Initialize the spec as a linked spec. The original spec's context is preserved except for the original GE asset tags, which are stripped out
Copies SetbyCallerMagnitudes from OriginalSpec into this
Copies SetbuCallerMagnitudes, but only if magnitudes don't exist in our map (slower but preserves data)
Determines if the spec has capture specs with valid captures for all of the specified definitions.
Parameters
InCaptureDefsToCheck Capture definitions to check for
Returns
True if the container has valid capture attributes for all of the specified definitions, false if it does not
Looks for an existing modified attribute struct, may return NULL
Adds a new modified attribute struct, will always add so check to see if it exists first
Helper function to attempt to calculate the duration of the spec from its GE definition
Parameters
OutDefDuration Computed duration of the spec from its GE definition; Not the actual duration of the spec
Returns
True if the calculation was successful, false if it was not
Sets duration. This should only be called as the GameplayEffect is being created and applied; Ignores calls after attribute capture
Returns the Period for the effect. If DurationPolicy is Instant this will forcibly return NO_PERIOD
Sets the stack count for this GE to NewStackCount if stacking is supported.
Returns the stack count for this GE spec.
Set the context info: who and where this spec came from.
Appends all tags granted by this gameplay effect spec
Appends all blocked ability tags granted by this gameplay effect spec
Appends all tags that apply to this gameplay effect spec
Sets the magnitude of a SetByCaller modifier
Sets the magnitude of a SetByCaller modifier
Returns the magnitude of a SetByCaller modifier. Will return 0.f and Warn if the magnitude has not been set.
Returns the magnitude of a SetByCaller modifier. Will return 0.f and Warn if the magnitude has not been set.
Get the computed magnitude of the modifier on the spec with the specified index
Parameters
ModifierIdx Modifier to get
bFactorInStackCount If true, the calculation will include the stack count
Returns
Computed magnitude
Get the computed magnitude of the modifier on the spec with the specified index
Parameters
ModifierIdx Modifier to get
Returns
Computed magnitude
Fills out the modifier magnitudes inside the Modifier Specs
Recapture attributes from source and target for cloning
Recaptures source actor tags of this spec without modifying anything else
Helper function to initialize all of the capture definitions required by the spec
Helper function that returns the duration after applying relevant modifiers from the source and target ability system components
Dynamically add an asset tag not originally from the source GE definition; Added to DynamicAssetTags as well as injected into the captured source spec tags
Dynamically append asset tags not originally from the source GE definition; Added to DynamicAssetTags as well as injected into the captured source spec tags
Simple const accessor to the dynamic asset tags
GameplayEfect definition. The static data that this spec points to.
A list of attributes that were modified during the application of this spec
Attributes captured by the spec that are relevant to custom calculations, potentially in owned modifiers, etc.; NOT replicated to clients
other effects that need to be applied to the target if this effect is successful
The duration in seconds of this effect instantaneous effects should have a duration of FGameplayEffectConstants::INSTANT_APPLICATION effects that last forever should have a duration of FGameplayEffectConstants::INFINITE_DURATION
The period in seconds of this effect, nonperiodic effects should have a period of FGameplayEffectConstants::NO_PERIOD
Captured Source Tags on GameplayEffectSpec creation
Tags from the target, captured during execute
Tags that are granted and that did not come from the UGameplayEffect def. These are replicated.
Tags that are on this effect spec and that did not come from the UGameplayEffect def. These are replicated.
The calculated modifiers for this effect
Total number of stacks of this effect
Whether the spec has had its source attribute capture completed or not yet
Whether the spec has had its target attribute capture completed or not yet
Whether the duration of the spec is locked or not; If it is, attempts to set it will fail
List of abilities granted by this effect
Map of set by caller magnitudes
This tells us how we got here (who / what applied us)
The level this effect was applied at
GameplayEfect definition. The static data that this spec points to.
Native delegate for providing custom matching conditions.
BP-exposed delegate for providing custom matching conditions.
Query that is matched against tags this GE gives
Query that is matched against tags this GE has
Query that is matched against spec tags the source of this GE has
Query that is matched against all tags the source of this GE has
Matches on GameplayEffects which modify given attribute.
Matches on GameplayEffects which come from this source
Matches on GameplayEffects with this definition
Handles to ignore as matches, even if other criteria is met
Returns true if Effect matches all specified criteria of this query, including CustomMatch delegates if bound. Returns false otherwise.
Returns true if Effect matches all specified criteria of this query. This does NOT check FActiveGameplayEffectQueryCustomMatch since this is performed on the spec (possibly prior to applying). Note: it would be reasonable to support a custom delegate that operated on the FGameplayEffectSpec itself.
Returns true if the query is empty/default. E.g., it has no data set.
Creates an effect query that will match if there are any common tags between the given tags and an ActiveGameplayEffect's owning tags
Creates an effect query that will match if all of the given tags are in the ActiveGameplayEffect's owning tags
Creates an effect query that will match if there are no common tags between the given tags and an ActiveGameplayEffect's owning tags
Creates an effect query that will match if there are any common tags between the given tags and an ActiveGameplayEffect's tags
Creates an effect query that will match if all of the given tags are in the ActiveGameplayEffect's tags
Creates an effect query that will match if there are no common tags between the given tags and an ActiveGameplayEffect's tags
Creates an effect query that will match if there are any common tags between the given tags and an ActiveGameplayEffect's source spec tags
Creates an effect query that will match if all of the given tags are in the ActiveGameplayEffect's source spec tags
Creates an effect query that will match if there are no common tags between the given tags and an ActiveGameplayEffect's source spec tags
Bind this to override the default query-matching code.
Returns true if Effect matches the criteria of this query, which will be overridden by CustomMatch if it is bound. Returns false otherwise.
used to match with InheritableOwnedTagsContainer
used to match with InheritableGameplayEffectTags
used to reject matches with InheritableOwnedTagsContainer
used to reject matches with InheritableGameplayEffectTags
Matches on GameplayEffects which modify given attribute
Matches on GameplayEffects which come from this source
Matches on GameplayEffects with this definition
Handles to ignore as matches, even if other criteria is met
The version the owning GameplayEffect is currently set to
By always returning false here, we can disable delta serialization
We must use a custom serializer to make sure CurrentVersion serializes properly (without markup to avoid unwanted copying)
Definition at line 123 of file GameplayEffect.h.
References Category, GENERATED_USTRUCT_BODY, operator!=(), operator==(), Other, and UPROPERTY.