Unreal Engine 5.6 C++ API: Runtime/Engine/Classes/GameFramework/GameModeBase.h File Reference
GameModeBase.h File Reference
#include "CoreMinimal.h"
#include "UObject/ObjectMacros.h"
#include "Misc/Guid.h"
#include "Templates/SubclassOf.h"
#include "GameFramework/Actor.h"
#include "GameFramework/Pawn.h"
#include "GameFramework/Info.h"
#include "Engine/ServerStatReplicator.h"
#include "Online/CoreOnline.h"
#include "Net/Core/Connection/NetEnums.h"
#include "GameFramework/PlayerController.h"
#include "GameModeBase.generated.h"
Data Structures
class AGameModeBase
class FGameModeEvents
GameModeBase events, particularly for use by plugins.
Functions
DECLARE_DELEGATE_RetVal (bool, FCanUnpause)
Default delegate that provides an implementation for those that don't have special needs other than a toggle.
DECLARE_LOG_CATEGORY_EXTERN (LogGameMode, Log, All)
UCLASS ()
The GameModeBase defines the game being played.
Variables
meta = (ShortTooltip = "Game Mode Base defines the game being played, its rules, scoring, and other facets of the game type.")
Function Documentation
DECLARE_DELEGATE_RetVal()
DECLARE_DELEGATE_RetVal (bool , FCanUnpause)
Default delegate that provides an implementation for those that don't have special needs other than a toggle.
DECLARE_LOG_CATEGORY_EXTERN()
DECLARE_LOG_CATEGORY_EXTERN (LogGameMode , Log , All)
References All, and Log.
UCLASS()
UCLASS ()
The GameModeBase defines the game being played.
It governs the game rules, scoring, what actors are allowed to exist in this game type, and who may enter the game.
It is only instanced on the server and will never exist on the client.
A GameModeBase actor is instantiated when the level is initialized for gameplay in C++ UGameEngine::LoadMap().
The class of this GameMode actor is determined by (in order) either the URL ?game=xxx, the GameMode Override value set in the World Settings, or the DefaultGameMode entry set in the game's Project Settings.
See also
https://docs.unrealengine.com/latest/INT/Gameplay/Framework/GameMode/index.html
Variable Documentation
meta
meta = (ShortTooltip = "Game Mode Base defines the game being played, its rules, scoring, and other facets of the game type.")
Definition at line 46 of file GameModeBase.h.
Referenced by AGameModeBase::UFUNCTION(), AGameModeBase::UFUNCTION(), AGameModeBase::UFUNCTION(), AGameModeBase::UFUNCTION(), AGameModeBase::UFUNCTION(), AGameModeBase::UFUNCTION(), and AGameModeBase::UPROPERTY().