Unreal Engine 5.6 C++ API: Runtime/Core/Public/GenericPlatform/GenericPlatform.h File Reference
GenericPlatform.h File Reference
Data Structures
struct FGenericPlatformTypes
Generic types for almost all compilers and platforms.
struct SelectIntPointerType< T32BITS, T64BITS, PointerSize >
struct SelectIntPointerType< T32BITS, T64BITS, 4 >
struct SelectIntPointerType< T32BITS, T64BITS, 8 >
Functions
FGenericPlatformTypes::UTF8CHAR & operator%= (FGenericPlatformTypes::UTF8CHAR &Ch, FGenericPlatformTypes::UTF8CHAR InValue)
template<typename T>
auto operator%= (FGenericPlatformTypes::UTF8CHAR &Ch, T &&InValue) -> decltype((FGenericPlatformTypes::UTF8CHAR &)(*(unsigned char *)&Ch %=(T &&) InValue))
FGenericPlatformTypes::UTF8CHAR & operator&= (FGenericPlatformTypes::UTF8CHAR &Ch, FGenericPlatformTypes::UTF8CHAR InValue)
template<typename T>
auto operator&= (FGenericPlatformTypes::UTF8CHAR &Ch, T &&InValue) -> decltype((FGenericPlatformTypes::UTF8CHAR &)(*(unsigned char *)&Ch &=(T &&) InValue))
FGenericPlatformTypes::UTF8CHAR & operator*= (FGenericPlatformTypes::UTF8CHAR &Ch, FGenericPlatformTypes::UTF8CHAR InValue)
template<typename T>
auto operator*= (FGenericPlatformTypes::UTF8CHAR &Ch, T &&InValue) -> decltype((FGenericPlatformTypes::UTF8CHAR &)(*(unsigned char *)&Ch *=(T &&) InValue))
constexpr FGenericPlatformTypes::UTF8CHAR & operator++ (FGenericPlatformTypes::UTF8CHAR &Ch)
constexpr FGenericPlatformTypes::UTF8CHAR operator++ (FGenericPlatformTypes::UTF8CHAR &Ch, int)
FGenericPlatformTypes::UTF8CHAR & operator+= (FGenericPlatformTypes::UTF8CHAR &Ch, FGenericPlatformTypes::UTF8CHAR InValue)
template<typename T>
auto operator+= (FGenericPlatformTypes::UTF8CHAR &Ch, T &&InValue) -> decltype((FGenericPlatformTypes::UTF8CHAR &)(*(unsigned char *)&Ch+=(T &&) InValue))
constexpr FGenericPlatformTypes::UTF8CHAR & operator-- (FGenericPlatformTypes::UTF8CHAR &Ch)
constexpr FGenericPlatformTypes::UTF8CHAR operator-- (FGenericPlatformTypes::UTF8CHAR &Ch, int)
FGenericPlatformTypes::UTF8CHAR & operator-= (FGenericPlatformTypes::UTF8CHAR &Ch, FGenericPlatformTypes::UTF8CHAR InValue)
template<typename T>
auto operator-= (FGenericPlatformTypes::UTF8CHAR &Ch, T &&InValue) -> decltype((FGenericPlatformTypes::UTF8CHAR &)(*(unsigned char *)&Ch -=(T &&) InValue))
FGenericPlatformTypes::UTF8CHAR & operator/= (FGenericPlatformTypes::UTF8CHAR &Ch, FGenericPlatformTypes::UTF8CHAR InValue)
template<typename T>
auto operator/= (FGenericPlatformTypes::UTF8CHAR &Ch, T &&InValue) -> decltype((FGenericPlatformTypes::UTF8CHAR &)(*(unsigned char *)&Ch/=(T &&) InValue))
FGenericPlatformTypes::UTF8CHAR & operator<<= (FGenericPlatformTypes::UTF8CHAR &Ch, FGenericPlatformTypes::UTF8CHAR InValue)
template<typename T>
auto operator<<= (FGenericPlatformTypes::UTF8CHAR &Ch, T &&InValue) -> decltype((FGenericPlatformTypes::UTF8CHAR &)(*(unsigned char *)&Ch<<=(T &&) InValue))
FGenericPlatformTypes::UTF8CHAR & operator>>= (FGenericPlatformTypes::UTF8CHAR &Ch, FGenericPlatformTypes::UTF8CHAR InValue)
template<typename T>
auto operator>>= (FGenericPlatformTypes::UTF8CHAR &Ch, T &&InValue) -> decltype((FGenericPlatformTypes::UTF8CHAR &)(*(unsigned char *)&Ch > >=(T &&) InValue))
FGenericPlatformTypes::UTF8CHAR & operator^= (FGenericPlatformTypes::UTF8CHAR &Ch, FGenericPlatformTypes::UTF8CHAR InValue)
template<typename T>
auto operator^= (FGenericPlatformTypes::UTF8CHAR &Ch, T &&InValue) -> decltype((FGenericPlatformTypes::UTF8CHAR &)(*(unsigned char *)&Ch ^=(T &&) InValue))
FGenericPlatformTypes::UTF8CHAR & operator|= (FGenericPlatformTypes::UTF8CHAR &Ch, FGenericPlatformTypes::UTF8CHAR InValue)
template<typename T>
auto operator|= (FGenericPlatformTypes::UTF8CHAR &Ch, T &&InValue) -> decltype((FGenericPlatformTypes::UTF8CHAR &)(*(unsigned char *)&Ch|=(T &&) InValue))
Function Documentation
operator%=() [1/2]
FGenericPlatformTypes::UTF8CHAR & operator%= (FGenericPlatformTypes::UTF8CHAR & Ch, FGenericPlatformTypes::UTF8CHAR InValue) inline
Definition at line 122 of file GenericPlatform.h.
operator%=() [2/2]
template<typename T> auto operator%= (FGenericPlatformTypes::UTF8CHAR & Ch, T && InValue) -> decltype((FGenericPlatformTypes::UTF8CHAR&)(*(unsigned char*)&Ch %= (T&&)InValue)) inline
Definition at line 111 of file GenericPlatform.h.
operator&=() [1/2]
FGenericPlatformTypes::UTF8CHAR & operator&= (FGenericPlatformTypes::UTF8CHAR & Ch, FGenericPlatformTypes::UTF8CHAR InValue) inline
Definition at line 123 of file GenericPlatform.h.
operator&=() [2/2]
template<typename T> auto operator&= (FGenericPlatformTypes::UTF8CHAR & Ch, T && InValue) -> decltype((FGenericPlatformTypes::UTF8CHAR&)(*(unsigned char*)&Ch &= (T&&)InValue)) inline
Definition at line 112 of file GenericPlatform.h.
operator*=() [1/2]
FGenericPlatformTypes::UTF8CHAR & operator*= (FGenericPlatformTypes::UTF8CHAR & Ch, FGenericPlatformTypes::UTF8CHAR InValue) inline
Definition at line 121 of file GenericPlatform.h.
operator*=() [2/2]
template<typename T> auto operator*= (FGenericPlatformTypes::UTF8CHAR & Ch, T && InValue) -> decltype((FGenericPlatformTypes::UTF8CHAR&)(*(unsigned char*)&Ch *= (T&&)InValue)) inline
Definition at line 110 of file GenericPlatform.h.
operator++() [1/2]
FGenericPlatformTypes::UTF8CHAR & operator++ (FGenericPlatformTypes::UTF8CHAR & Ch) constexpr
Definition at line 102 of file GenericPlatform.h.
Referenced by DECLARE_STATS_GROUP(), USTRUCT(), USTRUCT(), and USTRUCT().
operator++() [2/2]
FGenericPlatformTypes::UTF8CHAR operator++ (FGenericPlatformTypes::UTF8CHAR & Ch, int) constexpr
Definition at line 104 of file GenericPlatform.h.
operator+=() [1/2]
FGenericPlatformTypes::UTF8CHAR & operator+= (FGenericPlatformTypes::UTF8CHAR & Ch, FGenericPlatformTypes::UTF8CHAR InValue) inline
Definition at line 118 of file GenericPlatform.h.
operator+=() [2/2]
template<typename T> auto operator+= (FGenericPlatformTypes::UTF8CHAR & Ch, T && InValue) -> decltype((FGenericPlatformTypes::UTF8CHAR&)(*(unsigned char*)&Ch += (T&&)InValue)) inline
Definition at line 107 of file GenericPlatform.h.
Referenced by USTRUCT().
operator--() [1/2]
FGenericPlatformTypes::UTF8CHAR & operator-- (FGenericPlatformTypes::UTF8CHAR & Ch) constexpr
Definition at line 103 of file GenericPlatform.h.
Referenced by USTRUCT().
operator--() [2/2]
FGenericPlatformTypes::UTF8CHAR operator-- (FGenericPlatformTypes::UTF8CHAR & Ch, int) constexpr
Definition at line 105 of file GenericPlatform.h.
operator-=() [1/2]
FGenericPlatformTypes::UTF8CHAR & operator-= (FGenericPlatformTypes::UTF8CHAR & Ch, FGenericPlatformTypes::UTF8CHAR InValue) inline
Definition at line 119 of file GenericPlatform.h.
operator-=() [2/2]
template<typename T> auto operator-= (FGenericPlatformTypes::UTF8CHAR & Ch, T && InValue) -> decltype((FGenericPlatformTypes::UTF8CHAR&)(*(unsigned char*)&Ch -= (T&&)InValue)) inline
Definition at line 108 of file GenericPlatform.h.
operator/=() [1/2]
FGenericPlatformTypes::UTF8CHAR & operator/= (FGenericPlatformTypes::UTF8CHAR & Ch, FGenericPlatformTypes::UTF8CHAR InValue) inline
Definition at line 120 of file GenericPlatform.h.
operator/=() [2/2]
template<typename T> auto operator/= (FGenericPlatformTypes::UTF8CHAR & Ch, T && InValue) -> decltype((FGenericPlatformTypes::UTF8CHAR&)(*(unsigned char*)&Ch /= (T&&)InValue)) inline
Definition at line 109 of file GenericPlatform.h.
operator<<=() [1/2]
FGenericPlatformTypes::UTF8CHAR & operator<<= (FGenericPlatformTypes::UTF8CHAR & Ch, FGenericPlatformTypes::UTF8CHAR InValue) inline
Definition at line 126 of file GenericPlatform.h.
operator<<=() [2/2]
template<typename T> auto operator<<= (FGenericPlatformTypes::UTF8CHAR & Ch, T && InValue) -> decltype((FGenericPlatformTypes::UTF8CHAR&)(*(unsigned char*)&Ch <<= (T&&)InValue)) inline
Definition at line 115 of file GenericPlatform.h.
operator>>=() [1/2]
FGenericPlatformTypes::UTF8CHAR & operator>>= (FGenericPlatformTypes::UTF8CHAR & Ch, FGenericPlatformTypes::UTF8CHAR InValue) inline
Definition at line 127 of file GenericPlatform.h.
operator>>=() [2/2]
template<typename T> auto operator>>= (FGenericPlatformTypes::UTF8CHAR & Ch, T && InValue) -> decltype((FGenericPlatformTypes::UTF8CHAR&)(*(unsigned char*)&Ch >>= (T&&)InValue)) inline
Definition at line 116 of file GenericPlatform.h.
operator^=() [1/2]
FGenericPlatformTypes::UTF8CHAR & operator^= (FGenericPlatformTypes::UTF8CHAR & Ch, FGenericPlatformTypes::UTF8CHAR InValue) inline
Definition at line 125 of file GenericPlatform.h.
operator^=() [2/2]
template<typename T> auto operator^= (FGenericPlatformTypes::UTF8CHAR & Ch, T && InValue) -> decltype((FGenericPlatformTypes::UTF8CHAR&)(*(unsigned char*)&Ch ^= (T&&)InValue)) inline
Definition at line 114 of file GenericPlatform.h.
operator|=() [1/2]
FGenericPlatformTypes::UTF8CHAR & operator|= (FGenericPlatformTypes::UTF8CHAR & Ch, FGenericPlatformTypes::UTF8CHAR InValue) inline
Definition at line 124 of file GenericPlatform.h.
operator|=() [2/2]
template<typename T> auto operator|= (FGenericPlatformTypes::UTF8CHAR & Ch, T && InValue) -> decltype((FGenericPlatformTypes::UTF8CHAR&)(*(unsigned char*)&Ch |= (T&&)InValue)) inline
Definition at line 113 of file GenericPlatform.h.