Unreal Engine 5.6 C++ API: Runtime/Engine/Public/GPUSkinVertexFactory.h File Reference
GPUSkinVertexFactory.h File Reference
#include "CoreMinimal.h"
#include "Stats/Stats.h"
#include "RHI.h"
#include "RenderResource.h"
#include "BoneIndices.h"
#include "GPUSkinPublicDefs.h"
#include "UniformBuffer.h"
#include "VertexFactory.h"
#include "LocalVertexFactory.h"
#include "ResourcePool.h"
#include "Matrix3x4.h"
#include "SkeletalMeshTypes.h"
Data Structures
class FBoneBufferPool
A pool for vertex buffers with consistent usage, bucketed for efficiency.
class FBoneBufferPoolPolicy
The policy for pooling bone vertex buffers.
class FClothBufferPool
A pool for vertex buffers with consistent usage, bucketed for efficiency.
class FClothBufferPoolPolicy
The policy for pooling bone vertex buffers.
class FGPUBaseSkinAPEXClothVertexFactory
Vertex factory with vertex stream components for GPU-skinned and morph target streams.
struct FGPUBaseSkinAPEXClothVertexFactory::ClothShaderType
class FGPUBaseSkinVertexFactory
Vertex factory with vertex stream components for GPU skinned vertices.
struct FGPUBaseSkinVertexFactory::FShaderDataType
class FGPUBaseSkinVertexFactory::FUpdateScope
struct FGPUSkinAPEXClothDataType
Stream component data bound to Apex cloth vertex factory.
struct FGPUSkinDataType
Stream component data bound to GPU skinned vertex factory.
class FGPUSkinPassThroughFactoryLooseParameters
struct FGPUSkinPassThroughFactoryLooseParameters::FTypeInfo
struct FGPUSkinPassThroughFactoryLooseParameters::zzFirstMemberId
struct FGPUSkinPassThroughFactoryLooseParameters::zzNextMemberIdFrameNumber
struct FGPUSkinPassThroughFactoryLooseParameters::zzNextMemberIdPositionBuffer
struct FGPUSkinPassThroughFactoryLooseParameters::zzNextMemberIdPreSkinnedTangentBuffer
struct FGPUSkinPassThroughFactoryLooseParameters::zzNextMemberIdPreviousPositionBuffer
class FGPUSkinPassthroughVertexFactory
Vertex factory with vertex stream components for GPU-skinned streams.
struct FGPUSkinPassthroughVertexFactory::FAddVertexAttributeDesc
Structure used for calls to SetVertexAttributes().
class FSharedPoolPolicyData
Shared data & implementation for the different types of pool.
struct FVertexBufferAndSRV
Struct to pool the vertex buffer & SRV together.
class TGPUSkinAPEXClothVertexFactory< BoneInfluenceType >
class TGPUSkinVertexFactory< BoneInfluenceType >
Vertex factory with vertex stream components for GPU skinned vertices.
Macros
#define SET_BONE_DATA(B, X)
Enumerations
enum GPUSkinBoneInfluenceType { DefaultBoneInfluence , UnlimitedBoneInfluence }
Functions
const FShaderParametersMetadata * GetForwardDeclaredShaderParametersStructMetadata (const FGPUSkinPassThroughFactoryLooseParameters *DummyPtr)
bool IsValidRef (const FVertexBufferAndSRV &Buffer)
Helper function to test whether the buffer is valid.
constexpr bool operator! (FGPUSkinPassthroughVertexFactory::EVertexAttributeFlags E)
constexpr FGPUSkinPassthroughVertexFactory::EVertexAttributeFlags operator& (FGPUSkinPassthroughVertexFactory::EVertexAttributeFlags Lhs, FGPUSkinPassthroughVertexFactory::EVertexAttributeFlags Rhs)
FGPUSkinPassthroughVertexFactory::EVertexAttributeFlags & operator&= (FGPUSkinPassthroughVertexFactory::EVertexAttributeFlags &Lhs, FGPUSkinPassthroughVertexFactory::EVertexAttributeFlags Rhs)
constexpr FGPUSkinPassthroughVertexFactory::EVertexAttributeFlags operator^ (FGPUSkinPassthroughVertexFactory::EVertexAttributeFlags Lhs, FGPUSkinPassthroughVertexFactory::EVertexAttributeFlags Rhs)
FGPUSkinPassthroughVertexFactory::EVertexAttributeFlags & operator^= (FGPUSkinPassthroughVertexFactory::EVertexAttributeFlags &Lhs, FGPUSkinPassthroughVertexFactory::EVertexAttributeFlags Rhs)
constexpr FGPUSkinPassthroughVertexFactory::EVertexAttributeFlags operator| (FGPUSkinPassthroughVertexFactory::EVertexAttributeFlags Lhs, FGPUSkinPassthroughVertexFactory::EVertexAttributeFlags Rhs)
FGPUSkinPassthroughVertexFactory::EVertexAttributeFlags & operator|= (FGPUSkinPassthroughVertexFactory::EVertexAttributeFlags &Lhs, FGPUSkinPassthroughVertexFactory::EVertexAttributeFlags Rhs)
constexpr FGPUSkinPassthroughVertexFactory::EVertexAttributeFlags operator~ (FGPUSkinPassthroughVertexFactory::EVertexAttributeFlags E)
Macro Definition Documentation
SET_BONE_DATA
#define SET_BONE_DATA (B, X)
Value:
B.SetMatrixTranspose(X)
Definition at line 24 of file GPUSkinVertexFactory.h.
Enumeration Type Documentation
GPUSkinBoneInfluenceType
enum GPUSkinBoneInfluenceType
Enumerator
DefaultBoneInfluence
UnlimitedBoneInfluence
Definition at line 157 of file GPUSkinVertexFactory.h.
Function Documentation
GetForwardDeclaredShaderParametersStructMetadata()
const FShaderParametersMetadata * GetForwardDeclaredShaderParametersStructMetadata (const FGPUSkinPassThroughFactoryLooseParameters * DummyPtr)
IsValidRef()
bool IsValidRef (const FVertexBufferAndSRV & Buffer) inline
Helper function to test whether the buffer is valid.
Parameters
Buffer Buffer to test
Returns
True if the buffer is valid otherwise false
Definition at line 92 of file GPUSkinVertexFactory.h.
References Buffer, and IsValidRef().
Referenced by USkeletalMeshComponent::IsRunningParallelEvaluation(), FSlateTexture2DRHIRef::IsValid(), FStaticMeshVertexBuffer::IsValid(), IsValidRef(), SetUniformBufferParameter(), and USTRUCT().
operator!()
bool operator! (FGPUSkinPassthroughVertexFactory::EVertexAttributeFlags E) inline constexpr
Definition at line 836 of file GPUSkinVertexFactory.h.
operator&()
FGPUSkinPassthroughVertexFactory::EVertexAttributeFlags operator& (FGPUSkinPassthroughVertexFactory::EVertexAttributeFlags Lhs, FGPUSkinPassthroughVertexFactory::EVertexAttributeFlags Rhs) inline constexpr
Definition at line 836 of file GPUSkinVertexFactory.h.
operator&=()
FGPUSkinPassthroughVertexFactory::EVertexAttributeFlags & operator&= (FGPUSkinPassthroughVertexFactory::EVertexAttributeFlags & Lhs, FGPUSkinPassthroughVertexFactory::EVertexAttributeFlags Rhs) inline
Definition at line 836 of file GPUSkinVertexFactory.h.
operator^()
FGPUSkinPassthroughVertexFactory::EVertexAttributeFlags operator^ (FGPUSkinPassthroughVertexFactory::EVertexAttributeFlags Lhs, FGPUSkinPassthroughVertexFactory::EVertexAttributeFlags Rhs) inline constexpr
Definition at line 836 of file GPUSkinVertexFactory.h.
operator^=()
FGPUSkinPassthroughVertexFactory::EVertexAttributeFlags & operator^= (FGPUSkinPassthroughVertexFactory::EVertexAttributeFlags & Lhs, FGPUSkinPassthroughVertexFactory::EVertexAttributeFlags Rhs) inline
Definition at line 836 of file GPUSkinVertexFactory.h.
operator|()
FGPUSkinPassthroughVertexFactory::EVertexAttributeFlags operator| (FGPUSkinPassthroughVertexFactory::EVertexAttributeFlags Lhs, FGPUSkinPassthroughVertexFactory::EVertexAttributeFlags Rhs) inline constexpr
Definition at line 836 of file GPUSkinVertexFactory.h.
operator|=()
FGPUSkinPassthroughVertexFactory::EVertexAttributeFlags & operator|= (FGPUSkinPassthroughVertexFactory::EVertexAttributeFlags & Lhs, FGPUSkinPassthroughVertexFactory::EVertexAttributeFlags Rhs) inline
Definition at line 836 of file GPUSkinVertexFactory.h.
operator~()
FGPUSkinPassthroughVertexFactory::EVertexAttributeFlags operator~ (FGPUSkinPassthroughVertexFactory::EVertexAttributeFlags E) inline constexpr
Definition at line 836 of file GPUSkinVertexFactory.h.