Unreal Engine 5.6 C++ API: Runtime/Engine/Classes/Engine/HitResult.h File Reference
HitResult.h File Reference
#include "CoreMinimal.h"
#include "Chaos/PhysicsObject.h"
#include "Engine/NetSerialization.h"
#include "Engine/ActorInstanceHandle.h"
#include "HitResult.generated.h"
Data Structures
struct TIsPODType< FHitResult >
struct TStructOpsTypeTraits< FHitResult >
Functions
USTRUCT ()) struct FHitResult
Structure containing information about one hit of a trace, such as point of impact and surface normal at that point.
Function Documentation
USTRUCT()
USTRUCT ()
Structure containing information about one hit of a trace, such as point of impact and surface normal at that point.
Face index we hit (for complex hits with triangle meshes).
'Time' of impact along trace direction (ranging from 0.0 to 1.0) if there is a hit, indicating time between TraceStart and TraceEnd. For swept movement (but not queries) this may be pulled back slightly from the actual time of impact, to prevent precision problems with adjacent geometry.
The distance from the TraceStart to the Location in world space. This value is 0 if there was an initial overlap (trace started inside another colliding object).
The location in world space where the moving shape would end up against the impacted object, if there is a hit. Equal to the point of impact for line tests. Example: for a sphere trace test, this is the point where the center of the sphere would be located when it touched the other object. For swept movement (but not queries) this may not equal the final location of the shape since hits are pulled back slightly to prevent precision issues from overlapping another surface.
Location in world space of the actual contact of the trace shape (box, sphere, ray, etc) with the impacted object. Example: for a sphere trace test, this is the point where the surface of the sphere touches the other object.
Note
: In the case of initial overlap (bStartPenetrating=true), ImpactPoint will be the same as Location because there is no meaningful single impact point to report.
Normal of the hit in world space, for the object that was swept. Equal to ImpactNormal for line tests. This is computed for capsules and spheres, otherwise it will be the same as ImpactNormal. Example: for a sphere trace test, this is a normalized vector pointing in towards the center of the sphere at the point of impact.
Normal of the hit in world space, for the object that was hit by the sweep, if any. For example if a sphere hits a flat plane, this is a normalized vector pointing out from the plane. In the case of impact with a corner or edge of a surface, usually the "most opposing" normal (opposed to the query direction) is chosen.
Start location of the trace. For example if a sphere is swept against the world, this is the starting location of the center of the sphere.
End location of the trace; this is NOT where the impact occurred (if any), but the furthest point in the attempted sweep. For example if a sphere is swept against the world, this would be the center of the sphere if there was no blocking hit.
If this test started in penetration (bStartPenetrating is true) and a depenetration vector can be computed, this value is the distance along Normal that will result in moving out of penetration. If the distance cannot be computed, this distance will be zero.
If the hit result is from a collision this will have extra info about the item that hit the second item.
Extra data about item that was hit (hit primitive specific).
Index to item that was hit, also hit primitive specific.
Indicates if this hit was a result of blocking collision. If false, there was no hit or it was an overlap/touch instead.
Whether the trace started in penetration, i.e. with an initial blocking overlap. In the case of penetration, if PenetrationDepth > 0.f, then it will represent the distance along the Normal vector that will result in minimal contact between the swept shape and the object that was hit. In this case, ImpactNormal will be the normal opposed to movement at that location (ie, Normal may not equal ImpactNormal). ImpactPoint will be the same as Location, since there is no single impact point to report.
Physical material that was hit.
Note
Must set bReturnPhysicalMaterial on the swept PrimitiveComponent or in the query params for this to be returned.
Handle to the object hit by the trace.
PrimitiveComponent hit by the trace.
The object that owns the PhysicsObject. This is used to determine if the PhysicsObject is still valid when not owned by an Actor
PhysicsObjects hit by the query. Not exposed to blueprints for the time being
Name of bone we hit (for skeletal meshes).
Name of the my bone which took part in hit event (in case of two skeletal meshes colliding).
Initialize empty hit result with given time.
Initialize empty hit result with given time, TraceStart, and TraceEnd
Ctor for easily creating "fake" hits from limited data.
Reset hit result while optionally saving TraceStart and TraceEnd.
Utility to return the Actor that owns the Component that was hit.
Utility to return the Component that was hit.
Optimized serialize function
Return true if there was a blocking hit that was not caused by starting in penetration.
Static utility function that returns the first 'blocking' hit in an array of results.
Static utility function that returns the number of blocking hits in array.
Static utility function that returns the number of overlapping hits in array.
Get a copy of the HitResult with relevant information reversed. For example when receiving a hit from another object, we reverse the normals.
Definition at line 19 of file HitResult.h.
References Ar, BlueprintType, Component, Distance, End, FORCEINLINE, FVector, GENERATED_BODY, HasNativeBreak, HasNativeMake, INDEX_NONE, Init, InTime, Item, Location, Map, FMemory::Memzero(), meta, NoInit, Normal, TArray< InElementType, InAllocatorType >::Num(), Reset, Time, ToString(), and UPROPERTY.