Unreal Engine 5.6 C++ API: Runtime/InputCore/Classes/InputCoreTypes.h File Reference
InputCoreTypes.h File Reference
#include "UObject/ObjectMacros.h"
#include "UObject/Object.h"
#include "UObject/Class.h"
#include "Misc/Attribute.h"
#include "InputCoreTypes.generated.h"
Data Structures
struct EKeys
struct EKeys::FCategoryDisplayInfo
struct EKeys::FPairedKeyDetails
Stores some data which make up a pair from the "root" key of the pair.
struct FInputKeyManager
struct FKeyDetails
struct TStructOpsTypeTraits< FKey >
Enumerations
enum class EPairedAxis : uint8 { Unpaired , X , Y , Z }
Defines the controller hands for tracking.
Functions
DECLARE_DELEGATE_RetVal_OneParam (FText, FGetKeyDisplayNameSignature, const FKey)
INPUTCORE_API DECLARE_LOG_CATEGORY_EXTERN (LogInput, Log, All)
UENUM () namespace ETouchType
Various states of touch inputs.
USTRUCT () struct FKey
Enumeration Type Documentation
EPairedAxis
enum class EPairedAxis : uint8 strong
Defines the controller hands for tracking.
Could be expanded, as needed, to facilitate non-handheld controllers
Enumerator
Unpaired
X
Y
Z
Definition at line 40 of file InputCoreTypes.h.
Function Documentation
DECLARE_DELEGATE_RetVal_OneParam()
DECLARE_DELEGATE_RetVal_OneParam (FText , FGetKeyDisplayNameSignature , const FKey)
DECLARE_LOG_CATEGORY_EXTERN()
INPUTCORE_API DECLARE_LOG_CATEGORY_EXTERN (LogInput , Log , All)
References All, BlueprintType, Hidden, Left, Log, and Right.
UENUM()
UENUM ()
Various states of touch inputs.
This entry is special. NUM_TOUCH_KEYS - 1, is used for the cursor so that it's represented as another finger index, but doesn't overlap with touch input indexes.
Definition at line 225 of file InputCoreTypes.h.
References BlueprintType, Hidden, and UMETA.
USTRUCT()
USTRUCT ()
Definition at line 48 of file InputCoreTypes.h.
References Ar, Blueprintable, BlueprintType, Buffer, Category, FName, GENERATED_USTRUCT_BODY, GetTypeHash(), InName, IsValid(), Key, operator!=(), operator<(), operator==(), Parent, ToString(), and UPROPERTY.