Unreal Engine 5.6 C++ API: Runtime/Slate/Public/Framework/Commands/InputChord.h File Reference
InputChord.h File Reference
#include "CoreMinimal.h"
#include "CoreTypes.h"
#include "GenericPlatform/GenericApplication.h"
#include "InputCoreTypes.h"
#include "Internationalization/Text.h"
#include "Misc/Optional.h"
#include "UObject/ObjectMacros.h"
#include "InputChord.generated.h"
Functions
UE_DEPRECATED (4.21, "Use FInputChord instead of FInputGesture") typedef struct FInputChord FInputGesture
USTRUCT () struct FInputChord
An Input Chord is a key and the modifier keys that are to be held with it.
Function Documentation
UE_DEPRECATED()
UE_DEPRECATED (4. 21, "Use FInputChord instead of FInputGesture")
USTRUCT()
USTRUCT ()
An Input Chord is a key and the modifier keys that are to be held with it.
The Key is the core of the chord.
Whether the shift key is part of the chord.
Whether the control key is part of the chord.
Whether the alt key is part of the chord.
Whether the command key is part of the chord.
The ways two chords can be related to each other. A chord is considered masking when it has all the same modifier keys as another chord plus more.
Returns the relationship between this chord and another.
Creates and initializes a new instance.
Parameters
InKey
InModifierKeys
Creates and initializes a new instance.
Parameters
InKey
InModifierKeys
Copy constructor.
Parameters
Other
Move constructor.
Parameters
Other
Copy assignment operator.
Parameters
Other
Move assignment operator.
Parameters
Other
Compares this input chord with another for equality.
Parameters
Other The other chord to compare with.
Returns
true if the chords are equal, false otherwise.
Compares this input chord with another for inequality.
Parameters
Other The other chord to compare with.
Returns
true if the chords are equal, false otherwise.
Gets a localized string that represents the chord.
Returns
A localized string.
Gets the key represented as a localized string.
Returns
A localized string.
Gets the localized string for the modifier portion of the coord.
Parameters
ModifierAppender. Text to append between each modifier and the key. If this is not specified a '+' character will be used
Checks whether this chord requires an modifier keys to be pressed.
Returns
true if modifier keys must be pressed, false otherwise.
Determines if this chord is valid. A chord is valid if it has a non modifier key that must be pressed and zero or more modifier keys that must be pressed
Returns
true if the chord is valid
Sets this chord to a new key and modifier state based on the provided template Should not be called directly. Only used by the key binding editor to set user defined keys
Gets a type hash value for the specified chord.
Parameters
Chord The input chord to get the hash value for.
Returns
The hash value.
Definition at line 22 of file InputChord.h.
References EModifierKey::Alt, BlueprintType, Category, EModifierKey::Command, EModifierKey::Control, GENERATED_USTRUCT_BODY, GetTypeHash(), Key, None, operator!=(), operator=(), operator==(), Other, Same, EModifierKey::Shift, UPROPERTY, and USTRUCT.