Unreal Engine 5.6 C++ API: Runtime/Core/Public/Math/InterpCurvePoint.h File Reference
InterpCurvePoint.h File Reference
#include "CoreTypes.h"
#include "HAL/UnrealMemory.h"
#include "Math/UnrealMathUtility.h"
#include "Math/Color.h"
#include "Math/Vector2D.h"
#include "Containers/EnumAsByte.h"
#include "Math/Vector.h"
#include "Math/Quat.h"
#include "Math/TwoVectors.h"
Data Structures
class FInterpCurvePoint< T >
Template for interpolation points.
Typedefs
typedef FInterpCurvePoint< float > FInterpCurvePointFloat
typedef FInterpCurvePoint< FLinearColor > FInterpCurvePointLinearColor
typedef FInterpCurvePoint< FQuat > FInterpCurvePointQuat
typedef FInterpCurvePoint< FTwoVectors > FInterpCurvePointTwoVectors
typedef FInterpCurvePoint< FVector > FInterpCurvePointVector
typedef FInterpCurvePoint< FVector2D > FInterpCurvePointVector2D
Enumerations
enum EInterpCurveMode {
CIM_Linear , CIM_CurveAuto , CIM_Constant , CIM_CurveUser ,
CIM_CurveBreak , CIM_CurveAutoClamped , CIM_Unknown
}
Functions
template<class U>
void AutoCalcTangent (const FQuat &PrevP, const FQuat &P, const FQuat &NextP, const U &Tension, FQuat &OutTan)
This actually returns the control point not a tangent.
template<class T, class U>
void AutoCalcTangent (const T &PrevP, const T &P, const T &NextP, const U &Tension, T &OutTan)
Computes Tangent for a curve segment.
float ClampFloatTangent (float PrevPointVal, float PrevTime, float CurPointVal, float CurTime, float NextPointVal, float NextTime)
Clamps a tangent formed by the specified control point values.
template<class T>
void ComputeClampableFloatVectorCurveTangent (float PrevTime, const T &PrevPoint, float CurTime, const T &CurPoint, float NextTime, const T &NextPoint, float Tension, bool bWantClamping, T &OutTangent)
Computes a tangent for the specified control point; supports clamping, but only works with floats or contiguous arrays of floats.
void ComputeCurveTangent (float PrevTime, const float &PrevPoint, float CurTime, const float &CurPoint, float NextTime, const float &NextPoint, float Tension, bool bWantClamping, float &OutTangent)
Computes a tangent for the specified control point.
void ComputeCurveTangent (float PrevTime, const FTwoVectors &PrevPoint, float CurTime, const FTwoVectors &CurPoint, float NextTime, const FTwoVectors &NextPoint, float Tension, bool bWantClamping, FTwoVectors &OutTangent)
Computes a tangent for the specified control point.
void ComputeCurveTangent (float PrevTime, const FVector &PrevPoint, float CurTime, const FVector &CurPoint, float NextTime, const FVector &NextPoint, float Tension, bool bWantClamping, FVector &OutTangent)
Computes a tangent for the specified control point.
void ComputeCurveTangent (float PrevTime, const FVector2D &PrevPoint, float CurTime, const FVector2D &CurPoint, float NextTime, const FVector2D &NextPoint, float Tension, bool bWantClamping, FVector2D &OutTangent)
Computes a tangent for the specified control point.
template<class T>
void ComputeCurveTangent (float PrevTime, const T &PrevPoint, float CurTime, const T &CurPoint, float NextTime, const T &NextPoint, float Tension, bool bWantClamping, T &OutTangent)
Computes a tangent for the specified control point.
template<class U>
void CurveFindIntervalBounds (const FInterpCurvePoint< FLinearColor > &Start, const FInterpCurvePoint< FLinearColor > &End, FLinearColor &CurrentMin, FLinearColor &CurrentMax, const U &Dummy)
template<class U>
void CurveFindIntervalBounds (const FInterpCurvePoint< float > &Start, const FInterpCurvePoint< float > &End, float &CurrentMin, float &CurrentMax, const U &Dummy)
template<class U>
void CurveFindIntervalBounds (const FInterpCurvePoint< FTwoVectors > &Start, const FInterpCurvePoint< FTwoVectors > &End, FTwoVectors &CurrentMin, FTwoVectors &CurrentMax, const U &Dummy)
template<class U>
void CurveFindIntervalBounds (const FInterpCurvePoint< FVector > &Start, const FInterpCurvePoint< FVector > &End, FVector &CurrentMin, FVector &CurrentMax, const U &Dummy)
template<class U>
void CurveFindIntervalBounds (const FInterpCurvePoint< FVector2D > &Start, const FInterpCurvePoint< FVector2D > &End, FVector2D &CurrentMin, FVector2D &CurrentMax, const U &Dummy)
template<class T, class U>
void CurveFindIntervalBounds (const FInterpCurvePoint< T > &Start, const FInterpCurvePoint< T > &End, T &CurrentMin, T &CurrentMax, const U &Dummy)
void CurveFloatFindIntervalBounds (const FInterpCurvePoint< float > &Start, const FInterpCurvePoint< float > &End, float &CurrentMin, float &CurrentMax)
Calculate bounds of float intervals.
void CurveLinearColorFindIntervalBounds (const FInterpCurvePoint< FLinearColor > &Start, const FInterpCurvePoint< FLinearColor > &End, FLinearColor &CurrentMin, FLinearColor &CurrentMax)
Calculate bounds of color intervals.
void CurveTwoVectorsFindIntervalBounds (const FInterpCurvePoint< FTwoVectors > &Start, const FInterpCurvePoint< FTwoVectors > &End, FTwoVectors &CurrentMin, FTwoVectors &CurrentMax)
Calculate bounds of twovector intervals.
void CurveVector2DFindIntervalBounds (const FInterpCurvePoint< FVector2D > &Start, const FInterpCurvePoint< FVector2D > &End, FVector2D &CurrentMin, FVector2D &CurrentMax)
Calculate bounds of 2D vector intervals.
void CurveVectorFindIntervalBounds (const FInterpCurvePoint< FVector > &Start, const FInterpCurvePoint< FVector > &End, FVector &CurrentMin, FVector &CurrentMax)
Calculate bounds of vector intervals.
Typedef Documentation
FInterpCurvePointFloat
typedef FInterpCurvePoint<float> FInterpCurvePointFloat
Definition at line 441 of file InterpCurvePoint.h.
FInterpCurvePointLinearColor
typedef FInterpCurvePoint<FLinearColor> FInterpCurvePointLinearColor
Definition at line 446 of file InterpCurvePoint.h.
FInterpCurvePointQuat
typedef FInterpCurvePoint<FQuat> FInterpCurvePointQuat
Definition at line 444 of file InterpCurvePoint.h.
FInterpCurvePointTwoVectors
typedef FInterpCurvePoint<FTwoVectors> FInterpCurvePointTwoVectors
Definition at line 445 of file InterpCurvePoint.h.
FInterpCurvePointVector
typedef FInterpCurvePoint<FVector> FInterpCurvePointVector
Definition at line 443 of file InterpCurvePoint.h.
FInterpCurvePointVector2D
typedef FInterpCurvePoint<FVector2D> FInterpCurvePointVector2D
Definition at line 442 of file InterpCurvePoint.h.
Enumeration Type Documentation
EInterpCurveMode
enum EInterpCurveMode
Enumerator
CIM_Linear
A straight line between two keypoint values.
CIM_CurveAuto
A cubic-hermite curve between two keypoints, using Arrive/Leave tangents.
These tangents will be automatically updated when points are moved, etc. Tangents are unclamped and will plateau at curve start and end points.
CIM_Constant
The out value is held constant until the next key, then will jump to that value.
CIM_CurveUser
A smooth curve just like CIM_Curve, but tangents are not automatically updated so you can have manual control over them (eg.
in Curve Editor).
CIM_CurveBreak
A curve like CIM_Curve, but the arrive and leave tangents are not forced to be the same, so you can create a 'corner' at this key.
CIM_CurveAutoClamped
A cubic-hermite curve between two keypoints, using Arrive/Leave tangents.
These tangents will be automatically updated when points are moved, etc. Tangents are clamped and will plateau at curve start and end points.
CIM_Unknown
Invalid or unknown curve type.
Definition at line 15 of file InterpCurvePoint.h.
Function Documentation
AutoCalcTangent() [1/2]
template<class U> void AutoCalcTangent (const FQuat & PrevP, const FQuat & P, const FQuat & NextP, const U & Tension, FQuat & OutTan) inline
This actually returns the control point not a tangent.
This is expected by the CubicInterp function for Quaternions
Definition at line 206 of file InterpCurvePoint.h.
References UE::Math::TQuat< double >::CalcTangents().
AutoCalcTangent() [2/2]
template<class T, class U> void AutoCalcTangent (const T & PrevP, const T & P, const T & NextP, const U & Tension, T & OutTan) inline
Computes Tangent for a curve segment.
Definition at line 196 of file InterpCurvePoint.h.
Referenced by ComputeClampableFloatVectorCurveTangent(), and ComputeCurveTangent().
ClampFloatTangent()
float ClampFloatTangent (float PrevPointVal, float PrevTime, float CurPointVal, float CurTime, float NextPointVal, float NextTime)
Clamps a tangent formed by the specified control point values.
Referenced by ComputeClampableFloatVectorCurveTangent().
ComputeClampableFloatVectorCurveTangent()
template<class T> void ComputeClampableFloatVectorCurveTangent (float PrevTime, const T & PrevPoint, float CurTime, const T & CurPoint, float NextTime, const T & NextPoint, float Tension, bool bWantClamping, T & OutTangent) inline
Computes a tangent for the specified control point; supports clamping, but only works with floats or contiguous arrays of floats.
Definition at line 236 of file InterpCurvePoint.h.
References AutoCalcTangent(), ClampFloatTangent(), float, FMath::Max, and UE_KINDA_SMALL_NUMBER.
Referenced by ComputeCurveTangent(), ComputeCurveTangent(), ComputeCurveTangent(), and ComputeCurveTangent().
ComputeCurveTangent() [1/5]
void ComputeCurveTangent (float PrevTime, const float & PrevPoint, float CurTime, const float & CurPoint, float NextTime, const float & NextPoint, float Tension, bool bWantClamping, float & OutTangent) inline
Computes a tangent for the specified control point.
Special case for float types; supports clamping.
Definition at line 284 of file InterpCurvePoint.h.
References ComputeClampableFloatVectorCurveTangent().
ComputeCurveTangent() [2/5]
void ComputeCurveTangent (float PrevTime, const FTwoVectors & PrevPoint, float CurTime, const FTwoVectors & CurPoint, float NextTime, const FTwoVectors & NextPoint, float Tension, bool bWantClamping, FTwoVectors & OutTangent) inline
Computes a tangent for the specified control point.
Special case for FTwoVectors types; supports clamping.
Definition at line 332 of file InterpCurvePoint.h.
References ComputeClampableFloatVectorCurveTangent().
ComputeCurveTangent() [3/5]
void ComputeCurveTangent (float PrevTime, const FVector & PrevPoint, float CurTime, const FVector & CurPoint, float NextTime, const FVector & NextPoint, float Tension, bool bWantClamping, FVector & OutTangent) inline
Computes a tangent for the specified control point.
Special case for FVector types; supports clamping.
Definition at line 300 of file InterpCurvePoint.h.
References ComputeClampableFloatVectorCurveTangent(), and FVector.
ComputeCurveTangent() [4/5]
void ComputeCurveTangent (float PrevTime, const FVector2D & PrevPoint, float CurTime, const FVector2D & CurPoint, float NextTime, const FVector2D & NextPoint, float Tension, bool bWantClamping, FVector2D & OutTangent) inline
Computes a tangent for the specified control point.
Special case for FVector2D types; supports clamping.
Definition at line 316 of file InterpCurvePoint.h.
References ComputeClampableFloatVectorCurveTangent().
ComputeCurveTangent() [5/5]
template<class T> void ComputeCurveTangent (float PrevTime, const T & PrevPoint, float CurTime, const T & CurPoint, float NextTime, const T & NextPoint, float Tension, bool bWantClamping, T & OutTangent) inline
Computes a tangent for the specified control point.
General case, doesn't support clamping.
Definition at line 214 of file InterpCurvePoint.h.
References AutoCalcTangent(), FMath::Max, and UE_KINDA_SMALL_NUMBER.
Referenced by FInterpCurve< T >::AutoSetTangents().
CurveFindIntervalBounds() [1/6]
template<class U> void CurveFindIntervalBounds (const FInterpCurvePoint< FLinearColor > & Start, const FInterpCurvePoint< FLinearColor > & End, FLinearColor & CurrentMin, FLinearColor & CurrentMax, const U & Dummy) inline
Definition at line 435 of file InterpCurvePoint.h.
References CurveLinearColorFindIntervalBounds(), and End.
CurveFindIntervalBounds() [2/6]
template<class U> void CurveFindIntervalBounds (const FInterpCurvePoint< float > & Start, const FInterpCurvePoint< float > & End, float & CurrentMin, float & CurrentMax, const U & Dummy) inline
Definition at line 407 of file InterpCurvePoint.h.
References CurveFloatFindIntervalBounds(), and End.
CurveFindIntervalBounds() [3/6]
template<class U> void CurveFindIntervalBounds (const FInterpCurvePoint< FTwoVectors > & Start, const FInterpCurvePoint< FTwoVectors > & End, FTwoVectors & CurrentMin, FTwoVectors & CurrentMax, const U & Dummy) inline
Definition at line 428 of file InterpCurvePoint.h.
References CurveTwoVectorsFindIntervalBounds(), and End.
CurveFindIntervalBounds() [4/6]
template<class U> void CurveFindIntervalBounds (const FInterpCurvePoint< FVector > & Start, const FInterpCurvePoint< FVector > & End, FVector & CurrentMin, FVector & CurrentMax, const U & Dummy) inline
Definition at line 421 of file InterpCurvePoint.h.
References CurveVectorFindIntervalBounds(), End, and FVector.
CurveFindIntervalBounds() [5/6]
template<class U> void CurveFindIntervalBounds (const FInterpCurvePoint< FVector2D > & Start, const FInterpCurvePoint< FVector2D > & End, FVector2D & CurrentMin, FVector2D & CurrentMax, const U & Dummy)
Definition at line 414 of file InterpCurvePoint.h.
References CurveVector2DFindIntervalBounds(), and End.
CurveFindIntervalBounds() [6/6]
template<class T, class U> void CurveFindIntervalBounds (const FInterpCurvePoint< T > & Start, const FInterpCurvePoint< T > & End, T & CurrentMin, T & CurrentMax, const U & Dummy) inline
Definition at line 402 of file InterpCurvePoint.h.
References End.
Referenced by FInterpCurve< T >::CalcBounds().
CurveFloatFindIntervalBounds()
void CurveFloatFindIntervalBounds (const FInterpCurvePoint< float > & Start, const FInterpCurvePoint< float > & End, float & CurrentMin, float & CurrentMax)
Calculate bounds of float intervals.
Parameters
Start interp curve point at Start
End interp curve point at End
CurrentMin Input and Output could be updated if needs new interval minimum bound
CurrentMax Input and Output could be updated if needs new interval maximmum bound
References End.
Referenced by CurveFindIntervalBounds().
CurveLinearColorFindIntervalBounds()
void CurveLinearColorFindIntervalBounds (const FInterpCurvePoint< FLinearColor > & Start, const FInterpCurvePoint< FLinearColor > & End, FLinearColor & CurrentMin, FLinearColor & CurrentMax)
Calculate bounds of color intervals.
Parameters
Start interp curve point at Start
End interp curve point at End
CurrentMin Input and Output could be updated if needs new interval minimum bound
CurrentMax Input and Output could be updated if needs new interval maximmum bound
References End.
Referenced by CurveFindIntervalBounds().
CurveTwoVectorsFindIntervalBounds()
void CurveTwoVectorsFindIntervalBounds (const FInterpCurvePoint< FTwoVectors > & Start, const FInterpCurvePoint< FTwoVectors > & End, FTwoVectors & CurrentMin, FTwoVectors & CurrentMax)
Calculate bounds of twovector intervals.
Parameters
Start interp curve point at Start
End interp curve point at End
CurrentMin Input and Output could be updated if needs new interval minimum bound
CurrentMax Input and Output could be updated if needs new interval maximmum bound
References End.
Referenced by CurveFindIntervalBounds().
CurveVector2DFindIntervalBounds()
void CurveVector2DFindIntervalBounds (const FInterpCurvePoint< FVector2D > & Start, const FInterpCurvePoint< FVector2D > & End, FVector2D & CurrentMin, FVector2D & CurrentMax)
Calculate bounds of 2D vector intervals.
Parameters
Start interp curve point at Start
End interp curve point at End
CurrentMin Input and Output could be updated if needs new interval minimum bound
CurrentMax Input and Output could be updated if needs new interval maximmum bound
References End.
Referenced by CurveFindIntervalBounds().
CurveVectorFindIntervalBounds()
void CurveVectorFindIntervalBounds (const FInterpCurvePoint< FVector > & Start, const FInterpCurvePoint< FVector > & End, FVector & CurrentMin, FVector & CurrentMax)
Calculate bounds of vector intervals.
Parameters
Start interp curve point at Start
End interp curve point at End
CurrentMin Input and Output could be updated if needs new interval minimum bound
CurrentMax Input and Output could be updated if needs new interval maximmum bound
References End, and FVector.
Referenced by CurveFindIntervalBounds().