Unreal Engine 5.6 C++ API: Runtime/Core/Public/Templates/Invoke.h File Reference
Invoke.h File Reference
#include "CoreTypes.h"
#include "Traits/MemberFunctionPtrOuter.h"
#include "Templates/UnrealTemplate.h"
#include <type_traits>
Data Structures
struct TInvokeResult< FuncType, ArgTypes >
Trait for the type of the result when invoking a callable with the given argument types.
struct UE::Core::Private::TInvokeResult_Impl< typename, FuncType, ArgTypes >
struct UE::Core::Private::TInvokeResult_Impl< decltype((void) Invoke(DeclVal< FuncType >(), DeclVal< ArgTypes >()...)), FuncType, ArgTypes... >
Namespaces
namespace UE
Utility functions for applying transformations to meshes.
namespace UE::Core
namespace UE::Core::Private
TAdderRef and TAdderReserverRef are type-erasing adapters that allow a function to add to (and reserve) a container without the function knowing about the specific type of the container.
Macros
#define UE_PROJECTION(FuncName)
Wraps up a named non-member function so that it can easily be passed as a callable.
#define UE_PROJECTION_MEMBER(Type, FuncName)
Wraps up a named member function so that it can easily be passed as a callable.
Typedefs
template<typename FuncType, typename... ArgTypes>
using TInvokeResult_T = typename TInvokeResult<FuncType, ArgTypes...>::Type
Functions
template<typename OuterType, typename TargetType>
constexpr auto UE::Core::Private::DereferenceIfNecessary (TargetType &&Target, const volatile OuterType *TargetPtr) -> decltype((TargetType &&) Target)
template<typename OuterType, typename TargetType>
constexpr auto UE::Core::Private::DereferenceIfNecessary (TargetType &&Target,...) -> decltype(*(TargetType &&) Target)
template<typename FuncType, typename... ArgTypes>
FORCEINLINE auto Invoke (FuncType &&Func, ArgTypes &&... Args) -> decltype(Forward< FuncType >(Func)(Forward< ArgTypes >(Args)...))
Invokes a callable with a set of arguments.
template<typename PtrMemFunType, typename TargetType, typename... ArgTypes, typename ObjType = TMemberFunctionPtrOuter_T<PtrMemFunType>>
FORCEINLINE auto Invoke (PtrMemFunType PtrMemFun, TargetType &&Target, ArgTypes &&... Args) -> decltype((UE::Core::Private::DereferenceIfNecessary< ObjType >(Forward< TargetType >(Target), &Target).*PtrMemFun)(Forward< ArgTypes >(Args)...))
template<typename ReturnType, typename ObjType, typename TargetType>
FORCEINLINE auto Invoke (ReturnType ObjType::*pdm, TargetType &&Target) -> decltype(UE::Core::Private::DereferenceIfNecessary< ObjType >(Forward< TargetType >(Target), &Target).*pdm)
Macro Definition Documentation
UE_PROJECTION
#define UE_PROJECTION (FuncName)
Value:
    [](auto&&... Args) -> decltype(auto) \
    { \
        return FuncName(Forward<decltype(Args)>(Args)...); \
    }
Wraps up a named non-member function so that it can easily be passed as a callable.
This allows functions with overloads or default arguments to be treated correctly.
Example:
TArray<FMyType> Array = ...;
// Doesn't compile, because you can't take the address of an overloaded function when its type needs to be deduced. Algo::SortBy(Array, &LexToString);
// Works as expected Algo::SortBy(Array, UE_PROJECTION(LexToString));
Definition at line 84 of file Invoke.h.
UE_PROJECTION_MEMBER
#define UE_PROJECTION_MEMBER (Type, FuncName)
Value:
    [](auto&& Obj, auto&&... Args) -> decltype(auto) \
    { \
        return UE::Core::Private::DereferenceIfNecessary<Type>(Forward<decltype(Obj)>(Obj), &Obj).FuncName(Forward<decltype(Args)>(Args)...); \
    }
Wraps up a named member function so that it can easily be passed as a callable.
This allows functions with overloads or default arguments to be treated correctly.
Example:
TArray<UObject*> Array = ...;
// Doesn't compile, because &UObject::GetFullName loses the default argument and passes // FString (UObject::*)(const UObject*) to Algo::SortBy<>(), which is not a valid projection. Algo::SortBy(Array, &UObject::GetFullName);
// Works as expected Algo::SortBy(Array, UE_PROJECTION_MEMBER(UObject, GetFullName));
Definition at line 105 of file Invoke.h.
Typedef Documentation
TInvokeResult_T
template<typename FuncType, typename... ArgTypes> using TInvokeResult_T = typename TInvokeResult<FuncType, ArgTypes...>::Type
Definition at line 135 of file Invoke.h.
Function Documentation
Invoke() [1/3]
template<typename FuncType, typename... ArgTypes> FORCEINLINE auto Invoke (FuncType && Func, ArgTypes &&... Args) -> decltype(Forward<FuncType>(Func)(Forward<ArgTypes>(Args)...))
Invokes a callable with a set of arguments.
Allows the following:
Calling a functor object given a set of arguments.
Calling a function pointer given a set of arguments.
Calling a member function given a reference to an object and a set of arguments.
Calling a member function given a pointer (including smart pointers) to an object and a set of arguments.
Projecting via a data member pointer given a reference to an object.
Projecting via a data member pointer given a pointer (including smart pointers) to an object.
See: http://en.cppreference.com/w/cpp/utility/functional/invoke
Definition at line 44 of file Invoke.h.
References FORCEINLINE, and Forward().
Referenced by Algo::Accumulate(), Algo::AllOf(), Algo::BinarySearchBy(), TraceServices::PagedArrayAlgoImpl::BinarySearchClosestInternal(), LowLevelTasks::TTaskDelegate< ReturnType(ParamTypes...), TotalSize >::TTaskDelegateImpl< TCallableType, false >::Call(), LowLevelTasks::TTaskDelegate< ReturnType(ParamTypes...), TotalSize >::TTaskDelegateImpl< TCallableType, true >::Call(), UE::Core::Private::Function::TFunctionRefCaller< Functor, Ret, ParamTypes >::Call(), UE::Sequencer::ICastable::CastedCall(), UE::Sequencer::ICastable::CastedCall(), Algo::Private::Compare(), UE::Graph::ConvertToGraph(), Algo::CopyIf(), Algo::CountBy(), Algo::CountIf(), AwaitableTask_Detail::TPromise< ReturnType, CallableType >::Execute(), UE::Tasks::Private::TExecutableTaskBase< TaskBodyType, ResultType, Enable >::ExecuteTask(), UE::Tasks::Private::TExecutableTaskBase< TaskBodyType, typename TEnableIf< std::is_same_v< TInvokeResult_T< TaskBodyType >, void > >::Type >::ExecuteTask(), RangedForIteratorType< FAnimNextTraitEventPtr >::FilterByPredicate(), TArrayView< FTransform >::FilterByPredicate(), UE::Geometry::FGeometrySet3::FindAllCurvesSatisfying(), UE::Geometry::FGeometrySet3::FindAllPointsSatisfying(), AlgoImpl::FindBy(), UE::Sequencer::FViewModelListIterator::FindBy(), UE::Sequencer::TTypedIteratorBase< T, IteratorType >::FindBy(), AlgoImpl::FindByPredicate(), RangedForIteratorType< FAnimNextTraitEventPtr >::FindByPredicate(), TArrayView< FTransform >::FindByPredicate(), AlgoImpl::FindLastBy(), AlgoImpl::FindLastByPredicate(), RangedForIteratorType< FAnimNextTraitEventPtr >::FindLastByPredicate(), TArrayView< FTransform >::FindLastByPredicate(), Algo::ForEach(), Algo::ForEachIf(), FStreamableHandle::ForEachLoadedAsset(), UE::SharedBuffer::Private::TBufferOwnerDeleteFunction< DeleteFunctionType >::FreeBuffer(), AlgoImpl::HeapSiftDown(), AlgoImpl::HeapSiftUp(), Algo::Private::Includes(), AlgoImpl::IndexOfBy(), AlgoImpl::IndexOfByPredicate(), RangedForIteratorType< FAnimNextTraitEventPtr >::IndexOfByPredicate(), TArrayView< FTransform >::IndexOfByPredicate(), TSparseArray< SetElementType, typename Allocator::SparseArrayAllocator >::IndexOfByPredicate(), AlgoImpl::IntroSortInternal(), SharedPointerInternals::TDeleterHolder< DeleterType, bIsZeroSize >::InvokeDeleter(), SharedPointerInternals::TDeleterHolder< DeleterType, false >::InvokeDeleter(), UE::Core::Private::Tuple::TVisitTupleElements_Impl< TIntegerSequence< uint32, Indices... > >::InvokeFunc(), AlgoImpl::IsHeapInternal(), AlgoImpl::IsSortedBy(), FDisplayClusterShaderParameters_ICVFX::FCameraSettings::IterateViewportResourcesByPredicate(), FDisplayClusterShaderParameters_ICVFX::IterateViewportResourcesByPredicate(), UE::String::JoinByTo(), UE::String::JoinQuotedByTo(), UE::String::JoinTupleByTo(), UE::String::JoinTupleQuotedByTo(), AlgoImpl::KahnTopologicalSort_CreateWorkingGraph(), AlgoImpl::LegacySortInternal(), AlgoImpl::LowerBoundInternal(), TraceServices::PagedArrayAlgoImpl::LowerBoundInternal(), AlgoImpl::MaxElementBy(), AlgoImpl::Merge(), AlgoImpl::MinElementBy(), Algo::Private::Mismatch(), Algo::NoneOf(), Algo::NoneOf(), TOverrideVoidReturnInvoker< ReturnType, FuncType >::operator()(), TReversePredicate< PredicateType >::operator()(), RangedForIteratorType< FAnimNextTraitEventPtr >::RemoveAll(), RangedForIteratorType< FAnimNextTraitEventPtr >::RemoveAllSwap(), Algo::RemoveIf(), Algo::ReplaceIf(), AlgoImpl::SelectRandomWeightedBy(), Algo::StableRemoveIf(), AlgoImpl::StableSortInternal(), FSharedBuffer::TakeOwnership(), FUniqueBuffer::TakeOwnership(), Algo::Transform(), Algo::TransformAccumulate(), Algo::TransformIf(), AlgoImpl::Unique(), AlgoImpl::UpperBoundInternal(), and TraceServices::PagedArrayAlgoImpl::UpperBoundInternal().
Invoke() [2/3]
template<typename PtrMemFunType, typename TargetType, typename... ArgTypes, typename ObjType = TMemberFunctionPtrOuter_T<PtrMemFunType>> FORCEINLINE auto Invoke (PtrMemFunType PtrMemFun, TargetType && Target, ArgTypes &&... Args) -> decltype((UE::Core::Private::DereferenceIfNecessary<ObjType>(Forward<TargetType>(Target), &Target).*PtrMemFun)(Forward<ArgTypes>(Args)...))
Definition at line 63 of file Invoke.h.
References UE::Core::Private::DereferenceIfNecessary(), FORCEINLINE, Forward(), and Target.
Invoke() [3/3]
template<typename ReturnType, typename ObjType, typename TargetType> FORCEINLINE auto Invoke (ReturnType ObjType::* pdm, TargetType && Target) -> decltype(UE::Core::Private::DereferenceIfNecessary<ObjType>(Forward<TargetType>(Target), &Target).*pdm)
Definition at line 51 of file Invoke.h.
References UE::Core::Private::DereferenceIfNecessary(), FORCEINLINE, Forward(), and Target.