Unreal Engine 5.6 C++ API: Runtime/Core/Public/IO/IoChunkId.h File Reference
IoChunkId.h File Reference
#include "CoreTypes.h"
#include "Containers/StringFwd.h"
#include "Memory/MemoryView.h"
#include "Misc/ByteSwap.h"
#include "String/BytesToHex.h"
Data Structures
class FIoChunkId
Identifier to a chunk of data.
Enumerations
enum class EIoChunkType : uint8 {
Invalid = 0 , ExportBundleData = 1 , BulkData = 2 , OptionalBulkData = 3 ,
MemoryMappedBulkData = 4 , ScriptObjects = 5 , ContainerHeader = 6 , ExternalFile = 7 ,
ShaderCodeLibrary = 8 , ShaderCode = 9 , PackageStoreEntry = 10 , DerivedData = 11 ,
EditorDerivedData = 12 , PackageResource = 13 , MAX
}
Addressable chunk types.
Functions
FIoChunkId CreateBulkDataIoChunkId (uint64 ChunkId, uint16 ChunkIndex, uint8 ChunkGroup, EIoChunkType IoChunkType)
Used to create a FIoChunkId that references a bulkdata chunk.
FIoChunkId CreateContainerHeaderChunkId (const FIoContainerId &ContainerId)
Returns a container header I/O chunk ID.
FIoChunkId CreateExternalFileChunkId (const FStringView Filename)
Returns a file data I/O chunk ID for the specified filename.
FIoChunkId CreateIoChunkId (uint64 ChunkId, uint16 ChunkIndex, EIoChunkType IoChunkType)
Creates a chunk identifier (generic – prefer specialized versions where possible).
FIoChunkId CreatePackageDataChunkId (const FPackageId &PackageId)
Returns a package data I/O chunk ID for the specified package ID.
bool IsBulkDataType (const EIoChunkType Type)
FString LexToString (const EIoChunkType Type)
Enumeration Type Documentation
EIoChunkType
enum class EIoChunkType : uint8 strong
Addressable chunk types.
The enumerators have explicitly defined values here to encourage backward/forward compatible updates.
Also note that for certain discriminators, Zen Store will assume certain things about the structure of the chunk ID so changes must be made carefully.
Enumerator
Invalid
ExportBundleData
BulkData
OptionalBulkData
MemoryMappedBulkData
ScriptObjects
ContainerHeader
ExternalFile
ShaderCodeLibrary
ShaderCode
PackageStoreEntry
DerivedData
EditorDerivedData
PackageResource
MAX
Definition at line 27 of file IoChunkId.h.
Function Documentation
CreateBulkDataIoChunkId()
FIoChunkId CreateBulkDataIoChunkId (uint64 ChunkId, uint16 ChunkIndex, uint8 ChunkGroup, EIoChunkType IoChunkType) inline
Used to create a FIoChunkId that references a bulkdata chunk.
TODO Cannot use FBulkDataChunkGroup directly here as it is in CoreUObject
Parameters
ChunkId FPackageId
ChunkIndex MultiOutputIindex [0 = disabled, 1 enabled]
ChunkGroup FBulkDataCookedIndex
IoChunkType EIoChunkType
Definition at line 189 of file IoChunkId.h.
References checkfSlow, checkSlow, ExternalFile, IsBulkDataType(), NETWORK_ORDER16, FIoChunkId::Set(), and TEXT.
CreateContainerHeaderChunkId()
FIoChunkId CreateContainerHeaderChunkId (const FIoContainerId & ContainerId)
Returns a container header I/O chunk ID.
CreateExternalFileChunkId()
FIoChunkId CreateExternalFileChunkId (const FStringView Filename)
Returns a file data I/O chunk ID for the specified filename.
References Filename.
CreateIoChunkId()
FIoChunkId CreateIoChunkId (uint64 ChunkId, uint16 ChunkIndex, EIoChunkType IoChunkType) inline
Creates a chunk identifier (generic – prefer specialized versions where possible).
Definition at line 160 of file IoChunkId.h.
References checkfSlow, checkSlow, ExternalFile, IsBulkDataType(), NETWORK_ORDER16, FIoChunkId::Set(), and TEXT.
Referenced by FIoDispatcherInternal::HasPackageData().
CreatePackageDataChunkId()
FIoChunkId CreatePackageDataChunkId (const FPackageId & PackageId)
Returns a package data I/O chunk ID for the specified package ID.
IsBulkDataType()
bool IsBulkDataType (const EIoChunkType Type) inline
Definition at line 48 of file IoChunkId.h.
References BulkData, MemoryMappedBulkData, and OptionalBulkData.
Referenced by CreateBulkDataIoChunkId(), and CreateIoChunkId().
LexToString()
FString LexToString (const EIoChunkType Type)