Unreal Engine 5.6 C++ API: Editor/UnrealEd/Public/Kismet2/KismetDebugUtilities.h File Reference
KismetDebugUtilities.h File Reference
#include "CoreMinimal.h"
#include "UObject/Object.h"
#include "UObject/Class.h"
#include "Engine/Selection.h"
#include "KismetDebugUtilities.generated.h"
Data Structures
struct FBlueprintObjectsBeingDebuggedIterator
class FKismetDebugUtilities
struct FKismetTraceSample
struct FObjectsBeingDebuggedIterator
struct FPropertyInstanceInfo
struct FPropertyInstanceInfo::FPropertyInstance
used to determine whether an object's property has been visited yet when generating FDebugInfo
Functions
DECLARE_LOG_CATEGORY_EXTERN (LogBlueprintDebug, Log, All)
uint32 GetTypeHash (const FPropertyInstanceInfo::FPropertyInstance &PropertyInstance)
bool operator== (const FPropertyInstanceInfo::FPropertyInstance &A, const FPropertyInstanceInfo::FPropertyInstance &B)
UENUM () enum class EBlueprintBreakpointReloadMethod
Indicates how to restore breakpoints when a Blueprint asset is reloaded.
Function Documentation
DECLARE_LOG_CATEGORY_EXTERN()
DECLARE_LOG_CATEGORY_EXTERN (LogBlueprintDebug , Log , All)
References All, and Log.
GetTypeHash()
uint32 GetTypeHash (const FPropertyInstanceInfo::FPropertyInstance & PropertyInstance) inline
Definition at line 109 of file KismetDebugUtilities.h.
References GetTypeHash(), GetTypeHash(), HashCombine(), FPropertyInstanceInfo::FPropertyInstance::Property, and FPropertyInstanceInfo::FPropertyInstance::Value.
Referenced by GetTypeHash().
operator==()
bool operator== (const FPropertyInstanceInfo::FPropertyInstance & A, const FPropertyInstanceInfo::FPropertyInstance & B) inline
Definition at line 114 of file KismetDebugUtilities.h.
References A, and B.
UENUM()
UENUM ()
Indicates how to restore breakpoints when a Blueprint asset is reloaded.
Restore all breakpoints and keep their saved enabled/disabled state.
Restore all breakpoints and disable on reload.
Discard all breakpoints on reload.
Definition at line 27 of file KismetDebugUtilities.h.