Unreal Engine 5.6 C++ API: Runtime/Landscape/Classes/LandscapeProxy.h File Reference
LandscapeProxy.h File Reference
#include "CoreMinimal.h"
#include "Stats/Stats.h"
#include "UObject/ObjectMacros.h"
#include "Misc/Guid.h"
#include "Engine/EngineTypes.h"
#include "GameFramework/Actor.h"
#include "PhysicsEngine/BodyInstance.h"
#include "Async/AsyncWork.h"
#include "Engine/Texture.h"
#include "UObject/PerPlatformProperties.h"
#include "LandscapeNaniteComponent.h"
#include "LandscapeWeightmapUsage.h"
#include "LandscapeHeightfieldCollisionComponent.h"
#include "VT/RuntimeVirtualTextureEnum.h"
#include "ActorPartition/PartitionActor.h"
#include "ILandscapeSplineInterface.h"
#include "Engine/Texture2DArray.h"
#include "WorldPartition/WorldPartitionHandle.h"
#include "LandscapeProxy.generated.h"
Data Structures
class FAsyncGrassTask
struct FAsyncWorkMonitor
struct FAsyncWorkMonitor::FAsyncWorkTypeInfo
struct FCachedLandscapeFoliage
struct FCachedLandscapeFoliage::FGrassComp
struct FCachedLandscapeFoliage::FGrassCompKey
struct FCachedLandscapeFoliage::FGrassCompKeyFuncs
class FLandscapePhysicalMaterialBuilder
Helper class used to Build or monitor Landscape Physical Material.
class FLandscapeProxyComponentDataChangedParams
Helper class to store proxy changes information.
struct FOnLandscapeProxyFixupSharedDataParams
struct FOnLandscapeProxyMaterialChangedParams
Namespaces
namespace UE
Utility functions for applying transformations to meshes.
namespace UE::Landscape
namespace UE::Landscape::Nanite
Functions
DECLARE_MULTICAST_DELEGATE_TwoParams (FOnLandscapeProxyComponentDataChanged, ALandscapeProxy *, const FLandscapeProxyComponentDataChangedParams &)
DECLARE_MULTICAST_DELEGATE_TwoParams (FOnLandscapeProxyFixupSharedDataDelegate, ALandscapeProxy *, const FOnLandscapeProxyFixupSharedDataParams &)
DECLARE_MULTICAST_DELEGATE_TwoParams (FOnLandscapeProxyMaterialChanged, ALandscapeProxy *, const FOnLandscapeProxyMaterialChangedParams &)
DEFINE_ACTORDESC_TYPE (ALandscapeProxy, FLandscapeActorDesc)
UCLASS ()
UENUM() enum class ELandscapeLayerPaintingRestriction UENUM() enum class ELandscapeLayerDisplayMode UENUM() enum class ELandscapeHLODTextureSizePolicy UENUM() enum class ELandscapeHLODMeshSourceLODPolicy UENUM () namespace ELandscapeLODFalloff
UPROPERTY () TObjectPtr< UMaterialInterface > Material
USTRUCT () struct FLandscapeImportLayerInfo
Structure storing Layer Data for import.
Variables
FLandscapeEditorLayerSettings is deprecated
please use FLandscapeTargetLayerSettings instead FLandscapeEditorLayerSettings
please use FLandscapePerLODMaterialOverride instead FLandscapeProxyMaterialOverride
int32 GGrassMapUseRuntimeGeneration
LANDSCAPE_API bool GLandscapeEditModeActive
hidecategories
showcategories =(Lighting, Rendering, Transformation)
Function Documentation
DECLARE_MULTICAST_DELEGATE_TwoParams() [1/3]
DECLARE_MULTICAST_DELEGATE_TwoParams (FOnLandscapeProxyComponentDataChanged , ALandscapeProxy * , const FLandscapeProxyComponentDataChangedParams &)
DECLARE_MULTICAST_DELEGATE_TwoParams() [2/3]
DECLARE_MULTICAST_DELEGATE_TwoParams (FOnLandscapeProxyFixupSharedDataDelegate , ALandscapeProxy * , const FOnLandscapeProxyFixupSharedDataParams &)
DECLARE_MULTICAST_DELEGATE_TwoParams() [3/3]
DECLARE_MULTICAST_DELEGATE_TwoParams (FOnLandscapeProxyMaterialChanged , ALandscapeProxy * , const FOnLandscapeProxyMaterialChangedParams &)
DEFINE_ACTORDESC_TYPE()
DEFINE_ACTORDESC_TYPE (ALandscapeProxy , FLandscapeActorDesc)
UCLASS()
UCLASS ()
UENUM()
UENUM() enum class ELandscapeLayerPaintingRestriction UENUM() enum class ELandscapeLayerDisplayMode UENUM() enum class ELandscapeHLODTextureSizePolicy UENUM() enum class ELandscapeHLODMeshSourceLODPolicy UENUM ()
Default mode.
Square Root give more natural transition, and also keep the same LOD.
Definition at line 248 of file LandscapeProxy.h.
References Linear, and UMETA.
UPROPERTY()
UPROPERTY ()
References Material.
Referenced by USTRUCT().
USTRUCT()
USTRUCT ()
Structure storing Layer Data for import.
Definition at line 88 of file LandscapeProxy.h.
References Category, GENERATED_USTRUCT_BODY, operator==(), Other, and UPROPERTY().
Variable Documentation
deprecated
FLandscapeProxyMaterialOverride is deprecated
Definition at line 116 of file LandscapeProxy.h.
FLandscapeEditorLayerSettings
please use FLandscapeTargetLayerSettings instead FLandscapeEditorLayerSettings
Initial value:
{
     GENERATED_USTRUCT_BODY()
}
Definition at line 116 of file LandscapeProxy.h.
Referenced by USTRUCT().
FLandscapeProxyMaterialOverride
please use FLandscapePerLODMaterialOverride instead FLandscapeProxyMaterialOverride
Initial value:
{
     GENERATED_USTRUCT_BODY()
     UPROPERTY()
    FPerPlatformInt LODIndex
Definition at line 374 of file LandscapeProxy.h.
GGrassMapUseRuntimeGeneration
int32 GGrassMapUseRuntimeGeneration extern
GLandscapeEditModeActive
LANDSCAPE_API bool GLandscapeEditModeActive extern
hidecategories
hidecategories
Definition at line 412 of file LandscapeProxy.h.
showcategories
showcategories =(Lighting, Rendering, Transformation)
Definition at line 412 of file LandscapeProxy.h.