Unreal Engine 5.6 C++ API: Runtime/CoreUObject/Public/UObject/Linker.h File Reference
Linker.h File Reference
#include "Containers/Array.h"
#include "Containers/ArrayView.h"
#include "Containers/Map.h"
#include "Containers/Set.h"
#include "Containers/UnrealString.h"
#include "CoreMinimal.h"
#include "CoreTypes.h"
#include "Internationalization/GatherableTextData.h"
#include "Logging/LogMacros.h"
#include "Misc/AssertionMacros.h"
#include "Serialization/StructuredArchive.h"
#include "Serialization/StructuredArchiveSlots.h"
#include "Templates/RefCounting.h"
#include "UObject/LinkerInstancingContext.h"
#include "UObject/NameTypes.h"
#include "UObject/ObjectMacros.h"
#include "UObject/ObjectResource.h"
#include "UObject/PackageFileSummary.h"
Data Structures
struct FCompressedChunk
Information about a compressed chunk in a file.
class FLinker
Manages the data associated with an Unreal package.
class FLinkerTables
Namespaces
namespace ELinkerType
Macros
#define LLF_AllFlags 0xFFFFFFFF
Mask of all flags.
#define LLF_None 0x00000000
Empty flag set.
#define LLF_PayloadInSeparateFile 0x00000001
If set, payload is [going to be] stored in separate file.
#define LLF_SerializeCompressed 0x00000002
If set, payload should be [un]compressed during serialization.
Typedefs
typedef uint32 ELazyLoaderFlags
Flags serialized with the lazy loader.
Enumerations
enum ELinkerType::Type { ELinkerType::None , ELinkerType::Load , ELinkerType::Save }
Functions
template<typename T>
FORCEINLINE T * Cast (FLinker *Src)
template<typename T>
FORCEINLINE T * CastChecked (FLinker *Src)
void ConditionalFlushAsyncLoadingForSave (UPackage *InPackage)
Conditionally flush async loading for a specific package if there's any pending async requests.
DECLARE_LOG_CATEGORY_EXTERN (LogLinker, Log, All)
void DeleteLoader (FLinkerLoad *Loader)
Queues linker for deletion.
void DeleteLoaders ()
Deletes all linkers that have finished loading.
void EnsureLoadingComplete (UPackage *Package)
FLinkerLoad * GetPackageLinker (UPackage *InOuter, const FPackagePath &PackagePath, uint32 LoadFlags, UPackageMap *Sandbox, FArchive *InReaderOverride=nullptr, FUObjectSerializeContext **InOutLoadContext=nullptr, FLinkerLoad *ImportLinker=nullptr, const FLinkerInstancingContext *InstancingContext=nullptr)
Gets a linker for a package and returns it without loading any objects.
FString GetPrestreamPackageLinkerName (const TCHAR *InLongPackageName, bool bSkipIfExists=true)
void ResetLinkerExports (UPackage *InPackage)
Reset the linker exports associated with the package.
void ResetLoaders (TArrayView< UObject * > InOuters)
void ResetLoaders (UObject *InOuter)
Remove references to the linker for the given package and delete the linker.
void ResetLoadersForSave (TArrayView< FPackageSaveInfo > InPackages)
Reset the loaders for the given packages if they are using the given filenames, so we can write to the files.
void ResetLoadersForSave (UPackage *Package, const TCHAR *Filename)
Reset the loader for the given package if it is using the given filename, so we can write to the file.
UE_DEPRECATED (5.4, "Use GetPackageLinker instead") 1 FLinkerLoad *LoadPackageLinker(UPackage *InOuter
Loads a linker for a package and returns it without loading any objects.
Variables
const FPackagePath uint32 UPackageMap FArchive * InReaderOverride = nullptr)
const FPackagePath uint32 UPackageMap FArchive TFunctionRef< void(FLinkerLoad *LoadedLinker)> LinkerLoadedCallback
const FPackagePath uint32 LoadFlags = LOAD_None
const FPackagePath & PackagePath
const FPackagePath uint32 UPackageMap * Sandbox = nullptr
Macro Definition Documentation
LLF_AllFlags
#define LLF_AllFlags 0xFFFFFFFF
Mask of all flags.
Definition at line 639 of file Linker.h.
LLF_None
#define LLF_None 0x00000000
Empty flag set.
Definition at line 625 of file Linker.h.
LLF_PayloadInSeparateFile
#define LLF_PayloadInSeparateFile 0x00000001
If set, payload is [going to be] stored in separate file.
Definition at line 629 of file Linker.h.
LLF_SerializeCompressed
#define LLF_SerializeCompressed 0x00000002
If set, payload should be [un]compressed during serialization.
Only bulk data that doesn't require any special serialization or endian conversion can be compressed! The code will simply serialize a block from disk and use the byte order agnostic Serialize(Data, Length) function to fill the memory.
Definition at line 635 of file Linker.h.
Typedef Documentation
ELazyLoaderFlags
typedef uint32 ELazyLoaderFlags
Flags serialized with the lazy loader.
Definition at line 620 of file Linker.h.
Function Documentation
Cast()
template<typename T> FORCEINLINE T * Cast (FLinker * Src)
Definition at line 600 of file Linker.h.
References FORCEINLINE, and FLinker::GetType().
CastChecked()
template<typename T> FORCEINLINE T * CastChecked (FLinker * Src)
Definition at line 606 of file Linker.h.
References check, FORCEINLINE, and FLinker::GetType().
ConditionalFlushAsyncLoadingForSave()
void ConditionalFlushAsyncLoadingForSave (UPackage * InPackage)
Conditionally flush async loading for a specific package if there's any pending async requests.
Parameters
InPackage The package to flush for
References ConditionalFlushAsyncLoadingForSave().
Referenced by ConditionalFlushAsyncLoadingForSave().
DECLARE_LOG_CATEGORY_EXTERN()
DECLARE_LOG_CATEGORY_EXTERN (LogLinker , Log , All)
References All, and Log.
DeleteLoader()
void DeleteLoader (FLinkerLoad * Loader)
Queues linker for deletion.
References DeleteLoader().
Referenced by DeleteLoader().
DeleteLoaders()
void DeleteLoaders ()
Deletes all linkers that have finished loading.
References DeleteLoaders().
Referenced by DeleteLoaders().
EnsureLoadingComplete()
void EnsureLoadingComplete (UPackage * Package)
References EnsureLoadingComplete(), and Package.
Referenced by EnsureLoadingComplete().
GetPackageLinker()
FLinkerLoad * GetPackageLinker (UPackage * InOuter, const FPackagePath & PackagePath, uint32 LoadFlags, UPackageMap * Sandbox, FArchive * InReaderOverride = nullptr, FUObjectSerializeContext ** InOutLoadContext = nullptr, FLinkerLoad * ImportLinker = nullptr, const FLinkerInstancingContext * InstancingContext = nullptr)
Gets a linker for a package and returns it without loading any objects.
Parameters
InOuter Package if known, can be null
PackagePath Package resource to load, must not be empty
LoadFlags Flags to pass to the new linker
Sandbox Additional sandbox for loading
CompatibleGuid Net GUID
InReaderOverride Optional archive to use for reading package data
InOutLoadContext Optional load context. If the package linker is already associated with a context that's currently loading objects that context will be returned in this param
ImportLinker Optional import linker that triggered the linker creation. it will pass in its instancing context if a linker is created, take precedence over the optional InstancingContext
InstancingContext Optional instancing context to pass in if a linker is created
Returns
Pointer to the loaded linker or null if the file didn't exist
References GetPackageLinker(), InOuter, InReaderOverride, LoadFlags, PackagePath, and Sandbox.
Referenced by GetPackageLinker().
GetPrestreamPackageLinkerName()
FString GetPrestreamPackageLinkerName (const TCHAR * InLongPackageName, bool bSkipIfExists = true)
References GetPrestreamPackageLinkerName().
Referenced by GetPrestreamPackageLinkerName().
ResetLinkerExports()
void ResetLinkerExports (UPackage * InPackage)
Reset the linker exports associated with the package.
Note
, this might flush async loading if the linker is owned by the loading thread
References ResetLinkerExports().
Referenced by ResetLinkerExports().
ResetLoaders() [1/2]
void ResetLoaders (TArrayView< UObject * > InOuters)
References ResetLoaders().
ResetLoaders() [2/2]
void ResetLoaders (UObject * InOuter)
Remove references to the linker for the given package and delete the linker.
Can be called after the package has finished loading. Flushes async loading.
References InOuter, and ResetLoaders().
Referenced by ResetLoaders(), and ResetLoaders().
ResetLoadersForSave() [1/2]
void ResetLoadersForSave (TArrayView< FPackageSaveInfo > InPackages)
Reset the loaders for the given packages if they are using the given filenames, so we can write to the files.
Parameters
InPackage The package we are saving along with their filename
References ResetLoadersForSave().
ResetLoadersForSave() [2/2]
void ResetLoadersForSave (UPackage * Package, const TCHAR * Filename)
Reset the loader for the given package if it is using the given filename, so we can write to the file.
Parameters
Package The package we are saving
Filename The filename we are saving too
References Filename, Package, and ResetLoadersForSave().
Referenced by ResetLoadersForSave(), and ResetLoadersForSave().
UE_DEPRECATED()
UE_DEPRECATED (5. 4, "Use GetPackageLinker instead")
Loads a linker for a package and returns it without loading any objects.
Parameters
InOuter Package if known, can be null
PackagePath Package resource to load, must not be empty
LoadFlags Flags to pass to the new linker
Sandbox Additional sandbox for loading
CompatibleGuid Net GUID
InReaderOverride Optional archive to use for reading package data
LinkerLoadedCallback Callback when the linker is loaded (or not found)
Returns
Pointer to the loaded linker or null if the file didn't exist
Variable Documentation
InReaderOverride
const FPackagePath uint32 UPackageMap FArchive * InReaderOverride = nullptr)
Definition at line 657 of file Linker.h.
Referenced by GetPackageLinker(), LoadPackage(), and LoadPackage().
LinkerLoadedCallback
const FPackagePath uint32 UPackageMap FArchive TFunctionRef<void(FLinkerLoad* LoadedLinker)> LinkerLoadedCallback
Definition at line 657 of file Linker.h.
LoadFlags
const FPackagePath uint32 LoadFlags = LOAD_None
Definition at line 657 of file Linker.h.
Referenced by DECLARE_DELEGATE_ThreeParams(), ConstructorHelpersInternal::FindOrLoadObject(), ConstructorHelpersInternal::FindOrLoadObject< UPackage >(), UKismetInternationalizationLibrary::GetLocalizedCultures(), GetPackageLinker(), FExternalPackageHelper::LoadObjectsFromExternalPackages(), LoadPackage(), LoadPackage(), LoadPackageAsync(), ResolveName(), SafeLoadError(), StaticLoadAsset(), StaticLoadClass(), and StaticLoadObject().
PackagePath
const FPackagePath & PackagePath
Definition at line 657 of file Linker.h.
Referenced by FPackageName::DoesPackageExist(), FPackageName::DoesPackageExist(), IPackageResourceManager::DoesPackageExist(), FPackageName::DoesPackageExistEx(), IPackageResourceManager::FileSize(), UE::FindPayloadsInPackageFile(), GetPackageLinker(), FPackageName::InternalDoesPackageExistEx(), IAsyncPackageLoader::LoadPackage(), IAsyncPackageLoader::LoadPackage(), FLinkerSave::OnPostSave(), IPackageResourceManager::OpenAsyncReadPackage(), IPackageResourceManager::OpenAsyncReadPackage(), IPackageResourceManager::OpenMappedHandleToPackage(), IPackageResourceManager::OpenMappedHandleToPackage(), IPackageResourceManager::OpenReadPackage(), FPackagePath::operator<<, UPackage::SetLoadedPath(), IAsyncPackageLoader::ShouldAlwaysLoadPackageAsync(), UE::Virtualization::Experimental::IVirtualizationSourceControlUtilities::SyncPayloadSidecarFile(), UE::FPackageTrailer::TryLoadFromPackage(), IPackageResourceManager::TryMatchCaseOnDisk(), IPackageResourceManager::TryRegisterPreloadableArchive(), IPackageResourceManager::TryTakePreloadableArchive(), IPackageResourceManager::UE_DEPRECATED(), IPackageResourceManager::UE_DEPRECATED(), IPackageResourceManager::UE_DEPRECATED(), and IPackageResourceManager::UnRegisterPreloadableArchive().
Sandbox
const FPackagePath uint32 UPackageMap * Sandbox = nullptr
Definition at line 657 of file Linker.h.
Referenced by GetPackageLinker(), StaticLoadClass(), and StaticLoadObject().