Unreal Engine 5.6 C++ API: Runtime/LiveLinkInterface/Public/LiveLinkTypes.h File Reference
LiveLinkTypes.h File Reference
#include "Concepts/GetTypeHashable.h"
#include "Containers/Array.h"
#include "Containers/Map.h"
#include "Containers/UnrealString.h"
#include "CoreMinimal.h"
#include "HAL/PlatformTime.h"
#include "HAL/UnrealMemory.h"
#include "LiveLinkRefSkeleton.h"
#include "Math/Transform.h"
#include "Math/TransformVectorized.h"
#include "Math/UnrealMathSSE.h"
#include "Misc/AssertionMacros.h"
#include "Misc/FrameRate.h"
#include "Misc/FrameTime.h"
#include "Misc/Guid.h"
#include "Misc/QualifiedFrameTime.h"
#include "Serialization/Archive.h"
#include "Templates/Casts.h"
#include "Templates/Models.h"
#include "Templates/RemoveReference.h"
#include "Templates/UnrealTemplate.h"
#include "Templates/UnrealTypeTraits.h"
#include "UObject/Class.h"
#include "UObject/NameTypes.h"
#include "UObject/ObjectMacros.h"
#include "UObject/PropertyPortFlags.h"
#include "UObject/StructOnScope.h"
#include "UObject/UObjectGlobals.h"
#include "UObject/UnrealNames.h"
#include "LiveLinkTypes.generated.h"
Data Structures
class FLiveLinkBaseDataStruct< BaseType >
Wrapper around FStructOnScope to handle FLiveLinkBaseFrameData Can safely cast to the specific outer type.
struct FLiveLinkBaseDataStruct< BaseType >::FCastImpl< Type >
struct FLiveLinkSubjectFrameData
Wrapper around static and dynamic data to be used when fetching a subject complete data.
Typedefs
using FLiveLinkBlueprintDataStruct = FLiveLinkBaseDataStruct<FLiveLinkBaseBlueprintData>
Specialization of our wrapped struct for FLiveLinkBaseBlueprintData.
using FLiveLinkFrameDataStruct = FLiveLinkBaseDataStruct<FLiveLinkBaseFrameData>
Specialization of our wrapped struct for FLiveLinkBaseFrameData.
using FLiveLinkFrameIdentifier = int32
using FLiveLinkStaticDataStruct = FLiveLinkBaseDataStruct<FLiveLinkBaseStaticData>
Specialization of our wrapped struct for FLiveLinkBaseStaticData.
Functions
bool IsValid () const
operator FQualifiedFrameTime () const
FLiveLinkTimeCode & operator= (const FQualifiedFrameTime &InFrameTime)
struct UE_DEPRECATED (4.23, "FLiveLinkCurveIntegrationData is no longer used, please use FLiveLinkBaseStaticData::PropertyNames and FLiveLinkBaseFrameData::PropertyValues instead.") FLiveLinkCurveIntegrationData
struct UE_DEPRECATED (4.23, "FLiveLinkCurveKey is no longer used, please use FLiveLinkBaseStaticData::PropertyNames and FLiveLinkBaseFrameData::PropertyValues instead.") FLiveLinkCurveKey
struct UE_DEPRECATED (4.23, "FLiveLinkFrame is no longer used, please use the LiveLink animation role instead.") FLiveLinkFrame
Store frame information for animation data.
struct UE_DEPRECATED (4.23, "FLiveLinkSubjectFrame is no longer used, please use the LiveLink animation role instead.") FLiveLinkSubjectFrame
Store a subject complete frame data.
struct UE_DEPRECATED (4.23, "FOptionalCurveElement is no longer used, please use FLiveLinkBaseStaticData::PropertyNames and FLiveLinkBaseFrameData::PropertyValues instead.") FOptionalCurveElement
UPROPERTY () float CurveValue
USTRUCT () struct FLiveLinkBaseFrameData
Base data structure for each frame coming in for a subject.
Variables
FLiveLinkFrameData is no longer please use the LiveLink roles instead FLiveLinkCurveElement
FLiveLinkFrameData is no longer please use the LiveLink animation role instead FLiveLinkFrameData
PRAGMA_DISABLE_DEPRECATION_WARNINGS FLiveLinkFrameRate is no longer please use FFrameRate from TimeManagement instead FLiveLinkFrameRate
FLiveLinkTimeCode is no longer please use FQualifiedFrameTime from TimeManagement instead FLiveLinkTimeCode
static LIVELINKINTERFACE_API const FLiveLinkFrameRate FPS_100
static LIVELINKINTERFACE_API const FLiveLinkFrameRate FPS_120
static LIVELINKINTERFACE_API const FLiveLinkFrameRate FPS_15
static LIVELINKINTERFACE_API const FLiveLinkFrameRate FPS_24
static LIVELINKINTERFACE_API const FLiveLinkFrameRate FPS_240
static LIVELINKINTERFACE_API const FLiveLinkFrameRate FPS_25
static LIVELINKINTERFACE_API const FLiveLinkFrameRate FPS_30
static LIVELINKINTERFACE_API const FLiveLinkFrameRate FPS_48
static LIVELINKINTERFACE_API const FLiveLinkFrameRate FPS_50
static LIVELINKINTERFACE_API const FLiveLinkFrameRate FPS_60
static LIVELINKINTERFACE_API const FLiveLinkFrameRate NTSC_24
static LIVELINKINTERFACE_API const FLiveLinkFrameRate NTSC_30
static LIVELINKINTERFACE_API const FLiveLinkFrameRate NTSC_60
PRAGMA_DISABLE_DEPRECATION_WARNINGS FLiveLinkFrameRate is no longer used
Typedef Documentation
FLiveLinkBlueprintDataStruct
using FLiveLinkBlueprintDataStruct = FLiveLinkBaseDataStruct<FLiveLinkBaseBlueprintData>
Specialization of our wrapped struct for FLiveLinkBaseBlueprintData.
Definition at line 519 of file LiveLinkTypes.h.
FLiveLinkFrameDataStruct
using FLiveLinkFrameDataStruct = FLiveLinkBaseDataStruct<FLiveLinkBaseFrameData>
Specialization of our wrapped struct for FLiveLinkBaseFrameData.
Definition at line 516 of file LiveLinkTypes.h.
FLiveLinkFrameIdentifier
using FLiveLinkFrameIdentifier = int32
Definition at line 209 of file LiveLinkTypes.h.
FLiveLinkStaticDataStruct
using FLiveLinkStaticDataStruct = FLiveLinkBaseDataStruct<FLiveLinkBaseStaticData>
Specialization of our wrapped struct for FLiveLinkBaseStaticData.
Definition at line 513 of file LiveLinkTypes.h.
Function Documentation
IsValid()
bool IsValid () const
Definition at line 543 of file LiveLinkTypes.h.
Referenced by FPostProcessMaterialNode::FPostProcessMaterialNode(), FPostProcessMaterialNode::FPostProcessMaterialNode(), FPostProcessMaterialNode::FPostProcessMaterialNode(), TObjectArrayIterator< TObjectClass >::Advance(), Harmonix::TDynamicObjectPool< TObject >::Allocate(), CleanupPointerArray(), UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::Compute(), SRigVMActionMenu::ConstructActionContext(), FLODMask::ContainsLOD(), DECLARE_STATS_GROUP(), UE::MovieScene::TEntityTaskComponents< T >::Dispatch_PerAllocation(), UE::MovieScene::TEntityTaskComponents< T >::Dispatch_PerEntity(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::DoTraversal(), ENUM_CLASS_FLAGS(), DisplayClusterHelpers::game::FindAllActors(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::FindAllHitTrianglesImpl(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::FindAllIntersections(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::FindAllSelfIntersections(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::FindNearestHitTriangleImpl(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::FindNearestTriangle(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::FindNearestTriangles(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::FindNearestVertex(), FMovieSceneClipboardBuilder::FindOrAddKeyTrack(), FGraphSplineOverlapResult::GetBestPinWidget(), FMovieSceneEvaluationTree::GetNode(), FMovieSceneEvaluationTree::GetNode(), FShaderPipeline::GetNumShaders(), FWidgetReference::GetPreviewSlate(), FShaderPipeline::GetShader(), FShaderPipeline::GetShaders(), GetTypedElementDebugId< FActorElementData >(), GetValid(), GetValid(), GetValid(), FWorldPartitionHelpersPrivate::GetWorldPartition(), FWorldPartitionHelpersPrivate::GetWorldPartition(), FWorldPartitionHelpersPrivate::GetWorldPartition(), FWorldPartitionHelpersPrivate::GetWorldPartition(), FUObjectArray::IndexToValidObject(), FActorDragDropOp::Init(), TActorIteratorBase< FActorIterator >::IsActorSuitable(), UE::Tasks::Private::FTaskHandle::IsAwaitable(), UE::Tasks::Private::FTaskHandle::IsCompleted(), FLODMask::IsDithered(), FLODMask::IsLODRange(), FUObjectArray::IsValid(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::IsWithinDistanceSquared(), UE::MovieScene::TEntityTaskComponentsImpl< TIntegerSequence< int, Indices... >, T... >::Iterate_PerAllocationImpl(), UE::MovieScene::TEntityTaskComponentsImpl< TIntegerSequence< int, Indices... >, T... >::Iterate_PerEntityImpl(), UE::Tasks::Private::FTaskHandle::Launch(), MovieSceneToolHelpers::MergeValue(), UE::Sequencer::FSectionModel::NeedsLayout(), SRigVMActionMenu::OnActionSelected(), TExternalDirtyActorsTracker< StoreType >::OnPackageDirtyStateChanged(), FNavigationElementHandle::operator bool(), UE::PixelStreaming2::TObserverVariant< T >::operator bool(), TConstStructView< BaseStructT >::operator->(), TStructView< BaseStructT >::operator->(), FEnvQueryItem::operator<(), TPimplPtr< T, EPimplPtrMode::DeepCopy >::operator=(), TScriptDelegate< typename UE::Core::Private::TScriptDelegateTraits< InThreadSafetyMode >::UnicastThreadSafetyModeForMulticasts >::ProcessDelegate(), FHashTable::Remove(), THashTable< InAllocator >::Remove(), TStaticHashTable< HashSize, IndexSize >::Remove(), UE::MovieScene::TEntityTaskComponents< T >::RunInline_PerAllocation(), UE::MovieScene::TEntityTaskComponents< T >::RunInline_PerEntity(), UE::MovieScene::TEntityTaskComponents< T >::ScheduleImpl(), UE::Transaction::FSerializedObjectInfo::SetObject(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::TestAnyHitTriangle(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::TestIntersection(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::TestIntersection(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::TestIntersection(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::TestSelfIntersection(), TFutureBase< ResultType >::Then(), UCLASS(), UE::Tasks::Private::FTaskHandle::UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), FDisplayClusterActorRef::UpdateWorldPtr(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::Validate(), UE::Tasks::Private::FTaskHandle::Wait(), and UE::Tasks::Private::FTaskHandle::Wait().
operator FQualifiedFrameTime()
operator FQualifiedFrameTime () const
Definition at line 601 of file LiveLinkTypes.h.
References FrameRate, FMath::RoundToZero(), and Seconds.
operator=()
FLiveLinkTimeCode & operator= (const FQualifiedFrameTime & InFrameTime)
Definition at line 608 of file LiveLinkTypes.h.
References FFrameRate::AsDecimal(), FFrameTime::AsDecimal(), FFrameRate::Denominator, FLiveLinkFrameRate, FLiveLinkTimeCode, FrameRate, FFrameRate::Numerator, FQualifiedFrameTime::Rate, FMath::RoundToZero(), Seconds, and FQualifiedFrameTime::Time.
Referenced by UE_DEPRECATED().
UE_DEPRECATED() [1/5]
struct UE_DEPRECATED (4. 23, "FLiveLinkCurveIntegrationData is no longer used, please use FLiveLinkBaseStaticData::PropertyNames and FLiveLinkBaseFrameData::PropertyValues instead.")
Definition at line 665 of file LiveLinkTypes.h.
UE_DEPRECATED() [2/5]
struct UE_DEPRECATED (4. 23, "FLiveLinkCurveKey is no longer used, please use FLiveLinkBaseStaticData::PropertyNames and FLiveLinkBaseFrameData::PropertyValues instead.")
Definition at line 665 of file LiveLinkTypes.h.
UE_DEPRECATED() [3/5]
struct UE_DEPRECATED (4. 23, "FLiveLinkFrame is no longer used, please use the LiveLink animation role instead.")
Store frame information for animation data.
Definition at line 665 of file LiveLinkTypes.h.
UE_DEPRECATED() [4/5]
struct UE_DEPRECATED (4. 23, "FLiveLinkSubjectFrame is no longer used, please use the LiveLink animation role instead.")
Store a subject complete frame data.
Definition at line 665 of file LiveLinkTypes.h.
UE_DEPRECATED() [5/5]
struct UE_DEPRECATED (4. 23, "FOptionalCurveElement is no longer used, please use FLiveLinkBaseStaticData::PropertyNames and FLiveLinkBaseFrameData::PropertyValues instead.")
Curve Value
Whether this value is set or not
Definition at line 665 of file LiveLinkTypes.h.
References Ar, FLiveLinkCurveElement, IsValid(), MetaData, operator<<(), operator=(), UE_DEPRECATED, and Value.
UPROPERTY()
UPROPERTY ()
References float, UE_DEPRECATED, and USTRUCT.
USTRUCT()
USTRUCT ()
Base data structure for each frame coming in for a subject.
Store animation frame data.
Base blueprint data structure for a subject frame Can be used to do blueprint facilitator per role.
Base static data structure for a subject Use to store information that is common to every frame.
Note
subclass can't contains reference to UObject
Time in seconds the frame was created.
Frame's metadata.
Values of the properties defined in the static structure. Use FLiveLinkBaseStaticData.FindPropertyValue to evaluate.
Time at which this frame was received - populated once inside pipeline
This frame identifier - populated once inside pipeline
Return the LiveLinkTime struct constructed from this frame data.
Names for each curve values that will be sent for each frame
Definition at line 38 of file LiveLinkTypes.h.
References Ar, BlueprintType, Category, GENERATED_BODY, GetTypeHash(), InName, Name, operator<<(), operator==(), Other, ToString(), UPROPERTY, and Value.
Variable Documentation
FLiveLinkCurveElement
FLiveLinkFrameData is no longer please use the LiveLink roles instead FLiveLinkCurveElement
Initial value:
{
public:
     GENERATED_BODY()
    FLiveLinkCurveElement()
        : CurveName(NAME_None)
        , CurveValue(0.f)
    { }
    FLiveLinkCurveElement(FName InCurveName, float InCurveValue)
        : CurveName(InCurveName)
        , CurveValue(InCurveValue)
    { }
     UPROPERTY()
    FName CurveName
Definition at line 625 of file LiveLinkTypes.h.
Referenced by UE_DEPRECATED().
FLiveLinkFrameData
FLiveLinkFrameData is no longer please use the LiveLink animation role instead FLiveLinkFrameData
Initial value:
{
     GENERATED_BODY()
     UPROPERTY()
    TArray<FTransform> Transforms
Definition at line 652 of file LiveLinkTypes.h.
FLiveLinkFrameRate
PRAGMA_DISABLE_DEPRECATION_WARNINGS FLiveLinkFrameRate is no longer please use FFrameRate from TimeManagement instead FLiveLinkFrameRate
Definition at line 537 of file LiveLinkTypes.h.
Referenced by operator=().
FLiveLinkTimeCode
FLiveLinkTimeCode is no longer please use FQualifiedFrameTime from TimeManagement instead FLiveLinkTimeCode
Definition at line 594 of file LiveLinkTypes.h.
Referenced by operator=().
FPS_100
LIVELINKINTERFACE_API const FLiveLinkFrameRate FPS_100 static
Definition at line 555 of file LiveLinkTypes.h.
FPS_120
LIVELINKINTERFACE_API const FLiveLinkFrameRate FPS_120 static
Definition at line 556 of file LiveLinkTypes.h.
FPS_15
LIVELINKINTERFACE_API const FLiveLinkFrameRate FPS_15 static
Definition at line 548 of file LiveLinkTypes.h.
FPS_24
LIVELINKINTERFACE_API const FLiveLinkFrameRate FPS_24 static
Definition at line 549 of file LiveLinkTypes.h.
FPS_240
LIVELINKINTERFACE_API const FLiveLinkFrameRate FPS_240 static
Definition at line 557 of file LiveLinkTypes.h.
FPS_25
LIVELINKINTERFACE_API const FLiveLinkFrameRate FPS_25 static
Definition at line 550 of file LiveLinkTypes.h.
FPS_30
LIVELINKINTERFACE_API const FLiveLinkFrameRate FPS_30 static
Definition at line 551 of file LiveLinkTypes.h.
FPS_48
LIVELINKINTERFACE_API const FLiveLinkFrameRate FPS_48 static
Definition at line 552 of file LiveLinkTypes.h.
FPS_50
LIVELINKINTERFACE_API const FLiveLinkFrameRate FPS_50 static
Definition at line 553 of file LiveLinkTypes.h.
FPS_60
LIVELINKINTERFACE_API const FLiveLinkFrameRate FPS_60 static
Definition at line 554 of file LiveLinkTypes.h.
NTSC_24
LIVELINKINTERFACE_API const FLiveLinkFrameRate NTSC_24 static
Definition at line 559 of file LiveLinkTypes.h.
NTSC_30
LIVELINKINTERFACE_API const FLiveLinkFrameRate NTSC_30 static
Definition at line 560 of file LiveLinkTypes.h.
NTSC_60
LIVELINKINTERFACE_API const FLiveLinkFrameRate NTSC_60 static
Definition at line 561 of file LiveLinkTypes.h.
used
FLiveLinkFrameData is no longer used
Definition at line 536 of file LiveLinkTypes.h.