Unreal Engine 5.6 C++ API: Runtime/Core/Public/Containers/LockFreeList.h File Reference
LockFreeList.h File Reference
#include "Containers/Array.h"
#include "Containers/ContainersFwd.h"
#include "CoreGlobals.h"
#include "CoreTypes.h"
#include "HAL/PlatformAtomics.h"
#include "HAL/PlatformProcess.h"
#include "HAL/ThreadSafeCounter.h"
#include "Logging/LogMacros.h"
#include "Misc/AssertionMacros.h"
#include "Misc/NoopCounter.h"
#include "Templates/AlignmentTemplates.h"
#include "Templates/Function.h"
#include <atomic>
Data Structures
struct FIndexedLockFreeLink
struct FLockFreeLinkPolicy
class FLockFreePointerFIFOBase< T, TPaddingForCacheContention, TABAInc >
class FLockFreePointerListLIFOBase< T, TPaddingForCacheContention, TABAInc >
class FLockFreePointerListLIFORoot< TPaddingForCacheContention, TABAInc >
class FStallingTaskQueue< T, TPaddingForCacheContention, NumPriorities >
class TClosableLockFreePointerListUnorderedSingleConsumer< T, TPaddingForCacheContention >
class TLockFreeAllocOnceIndexedAllocator< T, MaxTotalItems, ItemsPerPage >
class TLockFreePointerListFIFO< T, TPaddingForCacheContention >
class TLockFreePointerListLIFO< T >
class TLockFreePointerListLIFOPad< T, TPaddingForCacheContention >
class TLockFreePointerListUnordered< T, TPaddingForCacheContention >
Macros
#define checkLockFreePointerList checkSlow
#define MAX_LOCK_FREE_LINKS (1 << 26)
#define MAX_LOCK_FREE_LINKS_AS_BITS (26)
#define MAX_TagBitsValue (uint64(1) << (64 - MAX_LOCK_FREE_LINKS_AS_BITS))
Functions
DECLARE_LOG_CATEGORY_EXTERN (LogLockFreeList, Log, All)
void DoTestCriticalStall ()
GCC_ALIGN (8)
void * LockFreeAllocLinks (SIZE_T AllocSize)
void LockFreeFreeLinks (SIZE_T AllocSize, void *Ptr)
void LockFreeLinksExhausted (uint32 TotalNum)
void LockFreeTagCounterHasOverflowed ()
MS_ALIGN (8) struct FIndexedPointer
FORCEINLINE void TestCriticalStall ()
Variables
int32 GTestCriticalStalls
Macro Definition Documentation
checkLockFreePointerList
#define checkLockFreePointerList checkSlow
Definition at line 24 of file LockFreeList.h.
Referenced by TLockFreeAllocOnceIndexedAllocator< FIndexedLockFreeLink,(1<< 26), 16384 >::GetItem(), TLockFreeAllocOnceIndexedAllocator< FIndexedLockFreeLink,(1<< 26), 16384 >::GetRawItem(), MS_ALIGN(), FStallingTaskQueue< T, TPaddingForCacheContention, NumPriorities >::Pop(), TClosableLockFreePointerListUnorderedSingleConsumer< T, TPaddingForCacheContention >::PopAllAndClose(), and FStallingTaskQueue< T, TPaddingForCacheContention, NumPriorities >::Push().
MAX_LOCK_FREE_LINKS
#define MAX_LOCK_FREE_LINKS (1 << 26)
Definition at line 56 of file LockFreeList.h.
Referenced by MS_ALIGN().
MAX_LOCK_FREE_LINKS_AS_BITS
#define MAX_LOCK_FREE_LINKS_AS_BITS (26)
Definition at line 55 of file LockFreeList.h.
Referenced by MS_ALIGN().
MAX_TagBitsValue
#define MAX_TagBitsValue (uint64(1) << (64 - MAX_LOCK_FREE_LINKS_AS_BITS))
Definition at line 130 of file LockFreeList.h.
Referenced by FLockFreePointerListLIFORoot< TPaddingForCacheContention, TABAInc >::FLockFreePointerListLIFORoot().
Function Documentation
DECLARE_LOG_CATEGORY_EXTERN()
DECLARE_LOG_CATEGORY_EXTERN (LogLockFreeList , Log , All)
References All, and Log.
DoTestCriticalStall()
void DoTestCriticalStall ()
References GTestCriticalStalls.
Referenced by TestCriticalStall().
GCC_ALIGN()
GCC_ALIGN (8)
LockFreeAllocLinks()
void * LockFreeAllocLinks (SIZE_T AllocSize)
Referenced by TLockFreeAllocOnceIndexedAllocator< FIndexedLockFreeLink,(1<< 26), 16384 >::GetRawItem().
LockFreeFreeLinks()
void LockFreeFreeLinks (SIZE_T AllocSize, void * Ptr)
Referenced by TLockFreeAllocOnceIndexedAllocator< FIndexedLockFreeLink,(1<< 26), 16384 >::GetRawItem().
LockFreeLinksExhausted()
void LockFreeLinksExhausted (uint32 TotalNum)
Referenced by TLockFreeAllocOnceIndexedAllocator< FIndexedLockFreeLink,(1<< 26), 16384 >::Alloc().
LockFreeTagCounterHasOverflowed()
void LockFreeTagCounterHasOverflowed ()
Referenced by MS_ALIGN().
MS_ALIGN()
MS_ALIGN (8)
Definition at line 134 of file LockFreeList.h.
References checkLockFreePointerList, Exchange(), FORCEINLINE, Init, InterlockedCompareExchange, IsAligned(), LockFreeTagCounterHasOverflowed(), MAX_LOCK_FREE_LINKS, MAX_LOCK_FREE_LINKS_AS_BITS, operator!=(), operator==(), Other, TestCriticalStall(), UNLIKELY, and Value.
TestCriticalStall()
FORCEINLINE void TestCriticalStall ()
Definition at line 37 of file LockFreeList.h.
References DoTestCriticalStall(), FORCEINLINE, and GTestCriticalStalls.
Referenced by MS_ALIGN(), FLockFreePointerFIFOBase< T, TPaddingForCacheContention, TABAInc >::Pop(), and FLockFreePointerFIFOBase< T, TPaddingForCacheContention, TABAInc >::Push().
Variable Documentation
GTestCriticalStalls
int32 GTestCriticalStalls extern
Referenced by DoTestCriticalStall(), and TestCriticalStall().