Unreal Engine 5.6 C++ API: Runtime/Core/Public/Logging/LogVerbosity.h File Reference
LogVerbosity.h File Reference
#include "CoreTypes.h"
Namespaces
namespace ELogVerbosity
Enum that defines the verbosity levels of the logging system.
Enumerations
enum ELogVerbosity::Type : uint8 {
ELogVerbosity::NoLogging = 0 , ELogVerbosity::Fatal , ELogVerbosity::Error , ELogVerbosity::Warning ,
ELogVerbosity::Display , ELogVerbosity::Log , ELogVerbosity::Verbose , ELogVerbosity::VeryVerbose ,
ELogVerbosity::All = VeryVerbose , ELogVerbosity::NumVerbosity , ELogVerbosity::VerbosityMask = 0xf , ELogVerbosity::SetColor = 0x40 ,
ELogVerbosity::BreakOnLog = 0x80
}
Functions
ELogVerbosity::Type ParseLogVerbosityFromString (const FString &VerbosityString)
Converts a string to verbosity.
const TCHAR * ToString (ELogVerbosity::Type Verbosity)
Converts verbosity to a string.
Function Documentation
ParseLogVerbosityFromString()
ELogVerbosity::Type ParseLogVerbosityFromString (const FString & VerbosityString) extern
Converts a string to verbosity.
Parameters
VerbosityString verbosity in string form (e.g., "Log", "Display", or "Fatal")
Returns
Parsed verbosity from the string (or Log if the string was invalid)
ToString()
const TCHAR * ToString (ELogVerbosity::Type Verbosity)
Converts verbosity to a string.
Parameters
Verbosity verbosity enum
Returns
String representation of the verbosity enum
Referenced by FActorDescContainerInitParams::FActorDescContainerInitParams(), FHLODHashContext::FHLODHashContext(), FResourceDiskSize::FResourceDiskSize(), Audio::IQuartzQuantizedCommand::AboutToStart(), UE::Net::TStructNetTokenDataStoreHelper< T >::AddStateToReplayExportGroup(), DisplayClusterHelpers::str::ArrayToStr(), Audio::IQuartzQuantizedCommand::Cancel(), FActorDescContainerInitParams::ContainerName(), FStreamableDownloadCachePin::Create(), ENUM_CLASS_FLAGS(), Metasound::TAutoConverterNode< FromDataType, ToDataType >::FConverterOperator::Execute(), Audio::IQuartzQuantizedCommand::FailedToQueue(), RigVMTypeUtils::FindObjectFromCPPTypeObjectPath(), IAnimationDataModel::GenerateDebugStateString(), ICompressionFormat::GetCompressedBufferSize(), FUniformBufferStaticSlotRegistry::GetDebugDescription(), FShaderCode::GetFinalizedResource(), FField::GetFlags(), UObjectBase::GetFlags(), FGlobalShaderMap::GetShader(), FShaderMapContent::GetShader(), FRigVMStringWithTag::GetStringWithTag(), FMaxErrorStatTracker< DataType, SortType, MaxItems >::LogErrorStat(), DisplayClusterHelpers::str::MapToStr(), UE::Net::TStructNetTokenDataStoreHelper< T >::NetSerializeAndExportToken(), UE::Net::TStructNetTokenDataStoreHelper< T >::NetSerializeStateDataAsReplayData(), Audio::IQuartzQuantizedCommand::OnClockPaused(), Audio::IQuartzQuantizedCommand::OnClockStarted(), Audio::IQuartzQuantizedCommand::OnFinalCallback(), Audio::IQuartzQuantizedCommand::OnQueued(), FField::SetFlagsTo(), ToString(), EBuildConfigurations::UE_DEPRECATED(), EBuildTargets::UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UObjectBase::UE_DEPRECATED(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), and USTRUCT().