Unreal Engine 5.6 C++ API: Runtime/Engine/Public/Materials/MaterialInstance.h File Reference
MaterialInstance.h File Reference
#include "CoreMinimal.h"
#include "Materials/MaterialOverrideNanite.h"
#include "UObject/ObjectMacros.h"
#include "Misc/Guid.h"
#include "Materials/MaterialInterface.h"
#include "Materials/MaterialInstanceBasePropertyOverrides.h"
#include "MaterialInstance.generated.h"
Data Structures
struct FPostProcessBlendableOverrides
Enumerations
enum class EMaterialInstanceClearParameterFlag {
None = 0u , Numeric = (1u << 0) , Texture = (1u << 1) , Static = (1u << 2) ,
AllNonStatic = Numeric | Texture , All = AllNonStatic | Static
}
Functions
template<class T>
bool CompareValueArraysByExpressionGUID (const TArray< T > &InA, const TArray< T > &InB)
ENUM_CLASS_FLAGS (EMaterialInstanceClearParameterFlag)
USTRUCT () struct FScalarParameterAtlasInstanceData
Editable scalar parameter.
Enumeration Type Documentation
EMaterialInstanceClearParameterFlag
enum class EMaterialInstanceClearParameterFlag strong
Enumerator
None
Numeric
Texture
Static
AllNonStatic
All
Definition at line 534 of file MaterialInstance.h.
Function Documentation
CompareValueArraysByExpressionGUID()
template<class T> bool CompareValueArraysByExpressionGUID (const TArray< T > & InA, const TArray< T > & InB)
Definition at line 501 of file MaterialInstance.h.
References A, B, TArray< InElementType, InAllocatorType >::Num(), and TArray< InElementType, InAllocatorType >::Sort().
ENUM_CLASS_FLAGS()
ENUM_CLASS_FLAGS (EMaterialInstanceClearParameterFlag)
References None.
USTRUCT()
USTRUCT ()
Editable scalar parameter.
Editable font parameter.
Editable sparse volume texture parameter.
Editable runtime virtual texture parameter.
Editable texture collection parameter.
Editable texture parameter.
Editable vector parameter.
Key value of NONE represents override of UserSceneTexture output
Definition at line 30 of file MaterialInstance.h.
References GENERATED_BODY, operator!=(), operator==(), Other, and UPROPERTY.