Unreal Engine 5.6 C++ API: Runtime/Engine/Public/MaterialShared.h File Reference
MaterialShared.h File Reference
#include "CoreMinimal.h"
#include "Containers/IndirectArray.h"
#include "Containers/ArrayView.h"
#include "Misc/Guid.h"
#include "Engine/EngineTypes.h"
#include "Templates/RefCounting.h"
#include "Templates/UniquePtr.h"
#include "Misc/SecureHash.h"
#include "RHIDefinitions.h"
#include "RHIUniformBufferLayoutInitializer.h"
#include "RenderResource.h"
#include "RenderDeferredCleanup.h"
#include "UniformBuffer.h"
#include "Shader.h"
#include "VertexFactory.h"
#include "SceneTypes.h"
#include "StaticParameterSet.h"
#include "Misc/Optional.h"
#include "Serialization/MemoryWriter.h"
#include "Serialization/ArchiveProxy.h"
#include "MaterialRecursionGuard.h"
#include "MaterialSceneTextureId.h"
#include "MaterialShaderPrecompileMode.h"
#include "MaterialValueType.h"
#include "VirtualTexturing.h"
#include "Templates/UnrealTemplate.h"
#include "ShaderCompilerCore.h"
#include "PSOPrecache.h"
#include "UObject/ObjectMacros.h"
#include "Rendering/SubstrateMaterialShared.h"
#include "Shader/Preshader.h"
#include "Shader/ShaderTypes.h"
#include <atomic>
#include "MaterialShared.generated.h"
Data Structures
struct FDebugShaderPipelineInfo
struct FDebugShaderTypeInfo
class FMaterial
FMaterial serves 3 intertwined purposes: Represents a material to the material compilation process, and provides hooks for extensibility (CompileProperty, etc) Represents a material to the renderer, with functions to access material properties Stores a cached shader map, and other transient output from a compile, which is necessary with async shader compiling (when a material finishes async compilation, the shader map and compile errors need to be stored somewhere)
class FMaterialCompilationOutput
Stores outputs from the material compile that need to be saved.
struct FMaterialCompileTargetParameters
Fully describes a material compilation target.
class FMaterialExpressionKey
Uniquely identifies a material expression output.
class FMaterialExternalTextureParameterInfo
class FMaterialFunctionCompileState
Function specific compiler state.
class FMaterialNumericParameterInfo
struct FMaterialProcessedSource
struct FMaterialRenderContext
The context of a material being rendered.
class FMaterialResource
Implementation of the FMaterial interface for a UMaterial or UMaterialInstance.
struct FMaterialResourceForCooking
An FMaterialResource and other information needed for cooking it.
struct FMaterialResourceLocOnDisk
class FMaterialResourceMemoryWriter
class FMaterialResourceProxyReader
class FMaterialResourceWriteScope
class FMaterialShaderMap
The set of material shaders for a single material.
struct FMaterialShaderMap::FAsyncLoadContext
A context returned by BeginLoadFromDerivedDataCache that can be queried to know the state of the async request.
class FMaterialShaderMapContent
struct FMaterialShaderMapContent::FProjectMeshShaderMapToKey
class FMaterialShaderMapId
Contains all the information needed to uniquely identify a FMaterialShaderMap.
struct FMaterialShaderParameters
struct FMaterialShaderParametersBase
class FMaterialTextureCollectionParameterInfo
class FMaterialTextureParameterInfo
class FMaterialUniformParameterEvaluation
Represents the evaluation of a material parameter directly to a byte offset in the preshader uniform buffer.
class FMaterialUniformPreshaderField
class FMaterialUniformPreshaderHeader
class FMaterialUpdateContext
This class takes care of all of the details you need to worry about when modifying a UMaterial on the main thread.
struct FMaterialUpdateContext::EOptions
Options controlling what is done before/after the material is updated.
class FMaterialVirtualTextureStack
class FMeshMaterialShaderMap
The shaders which the render the material on a mesh generated by a particular vertex factory type.
class FUniformExpressionSet
Stores all uniform expressions for a material generated from a material translation.
union FUniformExpressionSet::FVTPackedStackAndLayerIndex
class FUniformParameterOverrides
struct FUniformParameterOverrides::FNumericParameterKey
struct FUniformParameterOverrides::FTextureParameterKey
Namespaces
namespace EMaterialShaderMapUsage
Usage options for a shader map.
namespace UE
Utility functions for applying transformations to meshes.
namespace UE::Cook
Macros
#define ALLOW_SHADERMAP_DEBUG_DATA (!(UE_BUILD_SHIPPING || (UE_BUILD_TEST && !PLATFORM_DESKTOP)))
#define ME_CAPTION_HEIGHT 18
#define ME_PREV_THUMBNAIL_SZ 256
#define ME_STD_BORDER 8
#define ME_STD_HPADDING 32
#define ME_STD_LABEL_PAD 16
#define ME_STD_TAB_HEIGHT 21
#define ME_STD_THUMBNAIL_SZ 96
#define ME_STD_VPADDING 16
#define UE_CHECK_FMATERIAL_LIFETIME PLATFORM_WINDOWS
Enumerations
enum ECompiledPartialDerivativeVariation { CompiledPDV_FiniteDifferences , CompiledPDV_Analytic , CompiledPDV_MAX }
Enum that contains entries for the ways that material properties can be compiled with partial derivative calculations.
enum struct EDeferredParamStrictness { ELoose , EStrict }
enum EMaterialCommonBasis {
MCB_Tangent , MCB_Local , MCB_TranslatedWorld , MCB_World ,
MCB_View , MCB_Camera , MCB_MeshParticle , MCB_Instance ,
MCB_PeriodicWorld , MCB_FirstPerson , MCB_MAX
}
The common bases of material.
enum class EMaterialTextureParameterType : uint32 {
Standard2D , Cube , Array2D , ArrayCube ,
Volume , Virtual , SparseVolume , Count
}
Must invalidate ShaderVersion.ush when changing.
enum class EMaterialTranslateValidationFlags : uint32 { None = 0 , Strict_RuntimeVirtualTexture = 1 << 0 }
Flags that define the behavior of material translation validation.
enum EMaterialShaderMapUsage::Type {
EMaterialShaderMapUsage::Default , EMaterialShaderMapUsage::LightmassExportEmissive , EMaterialShaderMapUsage::LightmassExportDiffuse , EMaterialShaderMapUsage::LightmassExportOpacity ,
EMaterialShaderMapUsage::LightmassExportNormal , EMaterialShaderMapUsage::MaterialExportBaseColor , EMaterialShaderMapUsage::MaterialExportSpecular , EMaterialShaderMapUsage::MaterialExportNormal ,
EMaterialShaderMapUsage::MaterialExportTangent , EMaterialShaderMapUsage::MaterialExportMetallic , EMaterialShaderMapUsage::MaterialExportRoughness , EMaterialShaderMapUsage::MaterialExportAnisotropy ,
EMaterialShaderMapUsage::MaterialExportAO , EMaterialShaderMapUsage::MaterialExportEmissive , EMaterialShaderMapUsage::MaterialExportOpacity , EMaterialShaderMapUsage::MaterialExportOpacityMask ,
EMaterialShaderMapUsage::MaterialExportSubSurfaceColor , EMaterialShaderMapUsage::MaterialExportClearCoat , EMaterialShaderMapUsage::MaterialExportClearCoatRoughness , EMaterialShaderMapUsage::MaterialExportCustomOutput ,
EMaterialShaderMapUsage::MaterialExportShadingModel , EMaterialShaderMapUsage::MaterialExportRefraction
}
Functions
bool AllowDitheredLODTransition (ERHIFeatureLevel::Type FeatureLevel)
Whether to allow dithered LOD transitions for a specific feature level.
bool CanConnectMaterialValueTypes (const uint32 InputType, const uint32 OutputType)
Check whether a combination of EMaterialValueType flags can be connected.
void ConvertToMultilineToolTip (const FString &InToolTip, const int32 TargetLineLength, TArray< FString > &OutToolTip)
Parses a string into multiple lines, for use with tooltips.
DECLARE_LOG_CATEGORY_EXTERN (LogMaterial, Log, All)
bool DoesMaterialUseTexture (const UMaterialInterface *Material, const UTexture *CheckTexture)
Check whether the specified texture is needed to render the material instance.
ENUM_CLASS_FLAGS (EMaterialTranslateValidationFlags) enum ECompiledMaterialProperty
Enum that contains entries for the ways that material properties need to be compiled.
void GetCmdLineFilterShaderFormats (TArray< FName > &InOutShderFormats)
int32 GetCmdLineMaterialQualityToCache ()
What material quality level should we explicitly cook for?
FName GetMaterialQualityLevelFName (EMaterialQualityLevel::Type InMaterialQualityLevel)
void GetMaterialQualityLevelName (EMaterialQualityLevel::Type InMaterialQualityLevel, FString &OutName)
Creates a string that represents the given quality level.
void GetMaterialValueTypeDescriptions (const uint32 MaterialValueType, TArray< FText > &OutDescriptions)
Given a combination of EMaterialValueType flags, get text descriptions of all types.
uint32 GetNumComponents (EMaterialValueType Type)
uint8 GetRayTracingMaskFromMaterial (const EBlendMode BlendMode)
uint32 GetUseSubsurfaceProfileShadingModelMask ()
bool IsAdditiveBlendMode (const FMaterial &In)
bool IsAdditiveBlendMode (const FMaterialShaderParameters &In)
bool IsAdditiveBlendMode (const UMaterialInterface &In)
bool IsAdditiveBlendMode (EBlendMode BlendMode)
bool IsAlphaCompositeBlendMode (const FMaterial &In)
bool IsAlphaCompositeBlendMode (const FMaterialShaderParameters &In)
bool IsAlphaCompositeBlendMode (const UMaterialInterface &In)
bool IsAlphaCompositeBlendMode (EBlendMode BlendMode)
bool IsAlphaHoldoutBlendMode (const FMaterial &In)
bool IsAlphaHoldoutBlendMode (const FMaterialShaderParameters &In)
bool IsAlphaHoldoutBlendMode (const UMaterialInterface &In)
bool IsAlphaHoldoutBlendMode (EBlendMode BlendMode)
bool IsFloatNumericType (EMaterialValueType InType)
bool IsLWCType (EMaterialValueType InType)
bool IsMaskedBlendMode (const FMaterial &In)
bool IsMaskedBlendMode (const FMaterialShaderParameters &In)
bool IsMaskedBlendMode (const UMaterialInterface &In)
bool IsMaskedBlendMode (EBlendMode BlendMode)
bool IsMaterialValueType (EMaterialValueType InType, EMaterialValueType InCompare)
bool IsModulateBlendMode (const FMaterial &In)
bool IsModulateBlendMode (const FMaterialShaderParameters &In)
bool IsModulateBlendMode (const UMaterialInterface &In)
bool IsModulateBlendMode (EBlendMode BlendMode)
bool IsNumericType (EMaterialValueType InType)
bool IsOpaqueBlendMode (const FMaterial &In)
bool IsOpaqueBlendMode (const FMaterialShaderParameters &In)
bool IsOpaqueBlendMode (const UMaterialInterface &In)
bool IsOpaqueBlendMode (EBlendMode BlendMode)
Blend modes utility functions.
bool IsOpaqueOrMaskedBlendMode (const FMaterial &In)
bool IsOpaqueOrMaskedBlendMode (const FMaterialShaderParameters &In)
bool IsOpaqueOrMaskedBlendMode (const UMaterialInterface &In)
bool IsOpaqueOrMaskedBlendMode (EBlendMode BlendMode)
bool IsPrimitiveType (EMaterialValueType InType)
bool IsSubsurfaceShadingModel (FMaterialShadingModelField ShadingModel)
bool IsTranslucentBlendMode (const FMaterial &In)
bool IsTranslucentBlendMode (const FMaterialShaderParameters &In)
bool IsTranslucentBlendMode (const UMaterialInterface &In)
bool IsTranslucentBlendMode (EBlendMode BlendMode)
bool IsTranslucentOnlyBlendMode (const FMaterial &In)
bool IsTranslucentOnlyBlendMode (const FMaterialShaderParameters &In)
bool IsTranslucentOnlyBlendMode (const UMaterialInterface &In)
bool IsTranslucentOnlyBlendMode (EBlendMode BlendMode)
bool IsUIntNumericType (EMaterialValueType InType)
bool IsUsingNewMaterialTranslatorPrototype ()
EMaterialValueType MakeLWCType (EMaterialValueType Type)
EMaterialValueType MakeNonLWCType (EMaterialValueType Type)
FArchive & operator<< (FArchive &Ar, FMaterialResourceLocOnDisk &Loc)
bool ShouldIncludeMaterialInDefaultOpaquePass (const FMaterial &Material)
UE_DEPRECATED (5.8, "Should call UMaterialExpression::IsAllowedIn on the Class' DefaultObject") extern 1 bool IsAllowedExpressionType(const UClass *Class
Returns whether the given expression class is allowed.
UENUM () enum class ELWCFunctionKind
bool UseSubsurfaceProfile (FMaterialShadingModelField ShadingModel)
Variables
const bool bMaterialFunction
constexpr uint32 NumMaterialTextureParameterTypes = (uint32)EMaterialTextureParameterType::Count
Macro Definition Documentation
ALLOW_SHADERMAP_DEBUG_DATA
#define ALLOW_SHADERMAP_DEBUG_DATA (!(UE_BUILD_SHIPPING || (UE_BUILD_TEST && !PLATFORM_DESKTOP)))
Definition at line 112 of file MaterialShared.h.
ME_CAPTION_HEIGHT
#define ME_CAPTION_HEIGHT 18
Definition at line 102 of file MaterialShared.h.
ME_PREV_THUMBNAIL_SZ
#define ME_PREV_THUMBNAIL_SZ 256
Definition at line 107 of file MaterialShared.h.
ME_STD_BORDER
#define ME_STD_BORDER 8
Definition at line 105 of file MaterialShared.h.
ME_STD_HPADDING
#define ME_STD_HPADDING 32
Definition at line 104 of file MaterialShared.h.
ME_STD_LABEL_PAD
#define ME_STD_LABEL_PAD 16
Definition at line 108 of file MaterialShared.h.
ME_STD_TAB_HEIGHT
#define ME_STD_TAB_HEIGHT 21
Definition at line 109 of file MaterialShared.h.
ME_STD_THUMBNAIL_SZ
#define ME_STD_THUMBNAIL_SZ 96
Definition at line 106 of file MaterialShared.h.
ME_STD_VPADDING
#define ME_STD_VPADDING 16
Definition at line 103 of file MaterialShared.h.
UE_CHECK_FMATERIAL_LIFETIME
#define UE_CHECK_FMATERIAL_LIFETIME PLATFORM_WINDOWS
Definition at line 115 of file MaterialShared.h.
Enumeration Type Documentation
ECompiledPartialDerivativeVariation
enum ECompiledPartialDerivativeVariation
Enum that contains entries for the ways that material properties can be compiled with partial derivative calculations.
Standard material shaders using the automatic hardware FiniteDifferences, Nanite uses Analytic, and we will likely need to add a separate one for raytracing at a later date.
Enumerator
CompiledPDV_FiniteDifferences
CompiledPDV_Analytic
CompiledPDV_MAX
Definition at line 1854 of file MaterialShared.h.
EDeferredParamStrictness
enum struct EDeferredParamStrictness strong
Enumerator
ELoose
EStrict
Definition at line 322 of file MaterialShared.h.
EMaterialCommonBasis
enum EMaterialCommonBasis
The common bases of material.
Enumerator
MCB_Tangent
MCB_Local
MCB_TranslatedWorld
MCB_World
MCB_View
MCB_Camera
MCB_MeshParticle
MCB_Instance
MCB_PeriodicWorld
MCB_FirstPerson
MCB_MAX
Definition at line 306 of file MaterialShared.h.
EMaterialTextureParameterType
enum class EMaterialTextureParameterType : uint32 strong
Must invalidate ShaderVersion.ush when changing.
Enumerator
Standard2D
Cube
Array2D
ArrayCube
Volume
Virtual
SparseVolume
Count
Definition at line 506 of file MaterialShared.h.
EMaterialTranslateValidationFlags
enum class EMaterialTranslateValidationFlags : uint32 strong
Flags that define the behavior of material translation validation.
Enumerator
None
Strict_RuntimeVirtualTexture
Definition at line 1828 of file MaterialShared.h.
Function Documentation
AllowDitheredLODTransition()
bool AllowDitheredLODTransition (ERHIFeatureLevel::Type FeatureLevel)
Whether to allow dithered LOD transitions for a specific feature level.
CanConnectMaterialValueTypes()
bool CanConnectMaterialValueTypes (const uint32 InputType, const uint32 OutputType) extern
Check whether a combination of EMaterialValueType flags can be connected.
References CanConnectMaterialValueTypes().
Referenced by CanConnectMaterialValueTypes().
ConvertToMultilineToolTip()
void ConvertToMultilineToolTip (const FString & InToolTip, const int32 TargetLineLength, TArray< FString > & OutToolTip) extern
Parses a string into multiple lines, for use with tooltips.
References ConvertToMultilineToolTip().
Referenced by ConvertToMultilineToolTip().
DECLARE_LOG_CATEGORY_EXTERN()
DECLARE_LOG_CATEGORY_EXTERN (LogMaterial , Log , All)
References All, and Log.
DoesMaterialUseTexture()
bool DoesMaterialUseTexture (const UMaterialInterface * Material, const UTexture * CheckTexture)
Check whether the specified texture is needed to render the material instance.
Parameters
Texture The texture to check.
Returns
bool - true if the material uses the specified texture.
References Input, and Material.
ENUM_CLASS_FLAGS()
ENUM_CLASS_FLAGS (EMaterialTranslateValidationFlags)
Enum that contains entries for the ways that material properties need to be compiled.
This 'inherits' from EMaterialProperty in the sense that all of its values start after the values in EMaterialProperty. Each material property is compiled once for its usual shader frequency, determined by GetShaderFrequency(), And then this enum contains entries for extra compiles of a material property with a different shader frequency. This is necessary for material properties which need to be evaluated in multiple shader frequencies.
Definition at line 1833 of file MaterialShared.h.
GetCmdLineFilterShaderFormats()
void GetCmdLineFilterShaderFormats (TArray< FName > & InOutShderFormats)
GetCmdLineMaterialQualityToCache()
int32 GetCmdLineMaterialQualityToCache ()
What material quality level should we explicitly cook for?
Returns
Quality level or INDEX_NONE if the switch was not specified.
Note
: -CacheMaterialQuality=
GetMaterialQualityLevelFName()
FName GetMaterialQualityLevelFName (EMaterialQualityLevel::Type InMaterialQualityLevel) extern
GetMaterialQualityLevelName()
void GetMaterialQualityLevelName (EMaterialQualityLevel::Type InMaterialQualityLevel, FString & OutName) extern
Creates a string that represents the given quality level.
GetMaterialValueTypeDescriptions()
void GetMaterialValueTypeDescriptions (const uint32 MaterialValueType, TArray< FText > & OutDescriptions) extern
Given a combination of EMaterialValueType flags, get text descriptions of all types.
References GetMaterialValueTypeDescriptions().
Referenced by GetMaterialValueTypeDescriptions().
GetNumComponents()
uint32 GetNumComponents (EMaterialValueType Type) inline
Returns
the number of components in a vector type.
Definition at line 206 of file MaterialShared.h.
References MCT_Bool, MCT_Float, MCT_Float1, MCT_Float2, MCT_Float3, MCT_Float4, MCT_LWCScalar, MCT_LWCVector2, MCT_LWCVector3, MCT_LWCVector4, MCT_StaticBool, MCT_UInt, MCT_UInt1, MCT_UInt2, MCT_UInt3, and MCT_UInt4.
GetRayTracingMaskFromMaterial()
uint8 GetRayTracingMaskFromMaterial (const EBlendMode BlendMode)
GetUseSubsurfaceProfileShadingModelMask()
uint32 GetUseSubsurfaceProfileShadingModelMask () inline
Definition at line 135 of file MaterialShared.h.
IsAdditiveBlendMode() [1/4]
bool IsAdditiveBlendMode (const FMaterial & In)
IsAdditiveBlendMode() [2/4]
bool IsAdditiveBlendMode (const FMaterialShaderParameters & In)
IsAdditiveBlendMode() [3/4]
bool IsAdditiveBlendMode (const UMaterialInterface & In)
IsAdditiveBlendMode() [4/4]
bool IsAdditiveBlendMode (EBlendMode BlendMode)
IsAlphaCompositeBlendMode() [1/4]
bool IsAlphaCompositeBlendMode (const FMaterial & In)
IsAlphaCompositeBlendMode() [2/4]
bool IsAlphaCompositeBlendMode (const FMaterialShaderParameters & In)
IsAlphaCompositeBlendMode() [3/4]
bool IsAlphaCompositeBlendMode (const UMaterialInterface & In)
IsAlphaCompositeBlendMode() [4/4]
bool IsAlphaCompositeBlendMode (EBlendMode BlendMode)
IsAlphaHoldoutBlendMode() [1/4]
bool IsAlphaHoldoutBlendMode (const FMaterial & In)
IsAlphaHoldoutBlendMode() [2/4]
bool IsAlphaHoldoutBlendMode (const FMaterialShaderParameters & In)
IsAlphaHoldoutBlendMode() [3/4]
bool IsAlphaHoldoutBlendMode (const UMaterialInterface & In)
IsAlphaHoldoutBlendMode() [4/4]
bool IsAlphaHoldoutBlendMode (EBlendMode BlendMode)
IsFloatNumericType()
bool IsFloatNumericType (EMaterialValueType InType) inline
Definition at line 240 of file MaterialShared.h.
References IsMaterialValueType(), MCT_Float, and MCT_LWCType.
IsLWCType()
bool IsLWCType (EMaterialValueType InType) inline
Definition at line 235 of file MaterialShared.h.
References IsMaterialValueType(), and MCT_LWCType.
IsMaskedBlendMode() [1/4]
bool IsMaskedBlendMode (const FMaterial & In)
IsMaskedBlendMode() [2/4]
bool IsMaskedBlendMode (const FMaterialShaderParameters & In)
IsMaskedBlendMode() [3/4]
bool IsMaskedBlendMode (const UMaterialInterface & In)
IsMaskedBlendMode() [4/4]
bool IsMaskedBlendMode (EBlendMode BlendMode)
Referenced by FMaterial::ShouldCastDynamicShadows().
IsMaterialValueType()
bool IsMaterialValueType (EMaterialValueType InType, EMaterialValueType InCompare) inline
Definition at line 230 of file MaterialShared.h.
Referenced by IsFloatNumericType(), IsLWCType(), IsNumericType(), IsPrimitiveType(), and IsUIntNumericType().
IsModulateBlendMode() [1/4]
bool IsModulateBlendMode (const FMaterial & In)
IsModulateBlendMode() [2/4]
bool IsModulateBlendMode (const FMaterialShaderParameters & In)
IsModulateBlendMode() [3/4]
bool IsModulateBlendMode (const UMaterialInterface & In)
IsModulateBlendMode() [4/4]
bool IsModulateBlendMode (EBlendMode BlendMode)
IsNumericType()
bool IsNumericType (EMaterialValueType InType) inline
Definition at line 250 of file MaterialShared.h.
References IsMaterialValueType(), MCT_Float, MCT_LWCType, MCT_ShadingModel, and MCT_UInt.
IsOpaqueBlendMode() [1/4]
bool IsOpaqueBlendMode (const FMaterial & In)
IsOpaqueBlendMode() [2/4]
bool IsOpaqueBlendMode (const FMaterialShaderParameters & In)
IsOpaqueBlendMode() [3/4]
bool IsOpaqueBlendMode (const UMaterialInterface & In)
IsOpaqueBlendMode() [4/4]
bool IsOpaqueBlendMode (EBlendMode BlendMode)
Blend modes utility functions.
Referenced by FMaterial::ShouldCastDynamicShadows().
IsOpaqueOrMaskedBlendMode() [1/4]
bool IsOpaqueOrMaskedBlendMode (const FMaterial & In)
IsOpaqueOrMaskedBlendMode() [2/4]
bool IsOpaqueOrMaskedBlendMode (const FMaterialShaderParameters & In)
IsOpaqueOrMaskedBlendMode() [3/4]
bool IsOpaqueOrMaskedBlendMode (const UMaterialInterface & In)
IsOpaqueOrMaskedBlendMode() [4/4]
bool IsOpaqueOrMaskedBlendMode (EBlendMode BlendMode)
Referenced by FPrimitiveComponentHelper::GetUsedMaterialPropertyDesc().
IsPrimitiveType()
bool IsPrimitiveType (EMaterialValueType InType) inline
Definition at line 256 of file MaterialShared.h.
References IsMaterialValueType(), MCT_Bool, MCT_Float, MCT_LWCType, MCT_ShadingModel, MCT_StaticBool, and MCT_UInt.
IsSubsurfaceShadingModel()
bool IsSubsurfaceShadingModel (FMaterialShadingModelField ShadingModel) inline
Definition at line 123 of file MaterialShared.h.
IsTranslucentBlendMode() [1/4]
bool IsTranslucentBlendMode (const FMaterial & In)
IsTranslucentBlendMode() [2/4]
bool IsTranslucentBlendMode (const FMaterialShaderParameters & In)
IsTranslucentBlendMode() [3/4]
bool IsTranslucentBlendMode (const UMaterialInterface & In)
IsTranslucentBlendMode() [4/4]
bool IsTranslucentBlendMode (EBlendMode BlendMode)
IsTranslucentOnlyBlendMode() [1/4]
bool IsTranslucentOnlyBlendMode (const FMaterial & In)
IsTranslucentOnlyBlendMode() [2/4]
bool IsTranslucentOnlyBlendMode (const FMaterialShaderParameters & In)
IsTranslucentOnlyBlendMode() [3/4]
bool IsTranslucentOnlyBlendMode (const UMaterialInterface & In)
IsTranslucentOnlyBlendMode() [4/4]
bool IsTranslucentOnlyBlendMode (EBlendMode BlendMode)
Referenced by FMaterial::ShouldCastDynamicShadows().
IsUIntNumericType()
bool IsUIntNumericType (EMaterialValueType InType) inline
Definition at line 245 of file MaterialShared.h.
References IsMaterialValueType(), and MCT_UInt.
IsUsingNewMaterialTranslatorPrototype()
bool IsUsingNewMaterialTranslatorPrototype ()
MakeLWCType()
EMaterialValueType MakeLWCType (EMaterialValueType Type) inline
Definition at line 274 of file MaterialShared.h.
References MCT_Float, MCT_Float1, MCT_Float2, MCT_Float3, MCT_Float4, MCT_LWCScalar, MCT_LWCVector2, MCT_LWCVector3, and MCT_LWCVector4.
MakeNonLWCType()
EMaterialValueType MakeNonLWCType (EMaterialValueType Type) inline
Definition at line 262 of file MaterialShared.h.
References MCT_Float1, MCT_Float2, MCT_Float3, MCT_Float4, MCT_LWCScalar, MCT_LWCVector2, MCT_LWCVector3, and MCT_LWCVector4.
operator<<()
FArchive & operator<< (FArchive & Ar, FMaterialResourceLocOnDisk & Loc) inline
Definition at line 3212 of file MaterialShared.h.
References Ar, FMaterialResourceLocOnDisk::FeatureLevel, FMaterialResourceLocOnDisk::Offset, and FMaterialResourceLocOnDisk::QualityLevel.
ShouldIncludeMaterialInDefaultOpaquePass()
bool ShouldIncludeMaterialInDefaultOpaquePass (const FMaterial & Material) inline
Definition at line 3345 of file MaterialShared.h.
References Material.
UE_DEPRECATED()
UE_DEPRECATED (5. 8, "Should call UMaterialExpression::IsAllowedIn on the Class' DefaultObject") const
Returns whether the given expression class is allowed.
UENUM()
UENUM ()
Definition at line 287 of file MaterialShared.h.
References Add, Max, and Other.
UseSubsurfaceProfile()
bool UseSubsurfaceProfile (FMaterialShadingModelField ShadingModel) inline
Definition at line 130 of file MaterialShared.h.
Variable Documentation
bMaterialFunction
const bool bMaterialFunction
Definition at line 1958 of file MaterialShared.h.
NumMaterialTextureParameterTypes
uint32 NumMaterialTextureParameterTypes = (uint32)EMaterialTextureParameterType::Count inline constexpr
Definition at line 518 of file MaterialShared.h.
Referenced by FUniformExpressionSet::LAYOUT_ARRAY().