Unreal Engine 5.6 C++ API: Runtime/Engine/Public/Materials/MaterialInstanceUpdateParameterSet.h File Reference
MaterialInstanceUpdateParameterSet.h File Reference
#include "Materials/Material.h"
#include "Materials/MaterialInstance.h"
#include "Materials/MaterialExpressionMaterialAttributeLayers.h"
#include "Materials/MaterialExpressionMaterialFunctionCall.h"
#include "Misc/App.h"
Namespaces
namespace MaterialInstance_Private
Functions
template<typename ExpressionType>
void MaterialInstance_Private::FindClosestExpressionByGUIDRecursive (const FName &InName, const FGuid &InGUID, TConstArrayView< TObjectPtr< UMaterialExpression > > InMaterialExpression, ExpressionType *&OutExpression)
Workaround - Similar to base call but evaluates all expressions found, not just the first.
template<typename ParameterType, typename ExpressionType>
bool MaterialInstance_Private::UpdateParameter_FullTraversal (ParameterType &Parameter, UMaterial *ParentMaterial)
template<typename ParameterType, typename ExpressionType>
bool UpdateParameterSet (TArray< FDoubleVectorParameterValue > &Parameters, UMaterial *ParentMaterial)
template<typename ParameterType, typename ExpressionType>
bool UpdateParameterSet (TArray< FFontParameterValue > &Parameters, UMaterial *ParentMaterial)
template<typename ParameterType, typename ExpressionType>
bool UpdateParameterSet (TArray< FRuntimeVirtualTextureParameterValue > &Parameters, UMaterial *ParentMaterial)
template<typename ParameterType, typename ExpressionType>
bool UpdateParameterSet (TArray< FScalarParameterValue > &Parameters, UMaterial *ParentMaterial)
Overloads for UpdateParameterSet to use cached data for types that can leverage it.
template<typename ParameterType, typename ExpressionType>
bool UpdateParameterSet (TArray< FSparseVolumeTextureParameterValue > &Parameters, UMaterial *ParentMaterial)
template<typename ParameterType, typename ExpressionType>
bool UpdateParameterSet (TArray< FStaticComponentMaskParameter > &Parameters, UMaterial *ParentMaterial)
template<typename ParameterType, typename ExpressionType>
bool UpdateParameterSet (TArray< FStaticSwitchParameter > &Parameters, UMaterial *ParentMaterial)
template<typename ParameterType, typename ExpressionType>
bool UpdateParameterSet (TArray< FTextureCollectionParameterValue > &Parameters, UMaterial *ParentMaterial)
template<typename ParameterType, typename ExpressionType>
bool UpdateParameterSet (TArray< FTextureParameterValue > &Parameters, UMaterial *ParentMaterial)
template<typename ParameterType, typename ExpressionType>
bool UpdateParameterSet (TArray< FVectorParameterValue > &Parameters, UMaterial *ParentMaterial)
template<typename ParameterType, typename ExpressionType>
bool UpdateParameterSet (TArray< ParameterType > &Parameters, UMaterial *ParentMaterial)
This function takes a array of parameter structs and attempts to establish a reference to the expression object each parameter represents.
template<typename ParameterType, typename ExpressionType>
bool MaterialInstance_Private::UpdateParameterSet_FullTraversal (TArray< ParameterType > &Parameters, UMaterial *ParentMaterial)
template<typename ParameterType, typename ExpressionType>
bool MaterialInstance_Private::UpdateParameterSet_WithCachedData (EMaterialParameterType ParamTypeEnum, TArray< ParameterType > &Parameters, UMaterial *ParentMaterial)
Function Documentation
UpdateParameterSet() [1/11]
template<typename ParameterType, typename ExpressionType> bool UpdateParameterSet (TArray< FDoubleVectorParameterValue > & Parameters, UMaterial * ParentMaterial)
Definition at line 261 of file MaterialInstanceUpdateParameterSet.h.
References MaterialInstance_Private::UpdateParameterSet_WithCachedData().
UpdateParameterSet() [2/11]
template<typename ParameterType, typename ExpressionType> bool UpdateParameterSet (TArray< FFontParameterValue > & Parameters, UMaterial * ParentMaterial)
Definition at line 276 of file MaterialInstanceUpdateParameterSet.h.
References MaterialInstance_Private::UpdateParameterSet_WithCachedData().
UpdateParameterSet() [3/11]
template<typename ParameterType, typename ExpressionType> bool UpdateParameterSet (TArray< FRuntimeVirtualTextureParameterValue > & Parameters, UMaterial * ParentMaterial)
Definition at line 281 of file MaterialInstanceUpdateParameterSet.h.
References MaterialInstance_Private::UpdateParameterSet_WithCachedData().
UpdateParameterSet() [4/11]
template<typename ParameterType, typename ExpressionType> bool UpdateParameterSet (TArray< FScalarParameterValue > & Parameters, UMaterial * ParentMaterial)
Overloads for UpdateParameterSet to use cached data for types that can leverage it.
Definition at line 251 of file MaterialInstanceUpdateParameterSet.h.
References MaterialInstance_Private::UpdateParameterSet_WithCachedData().
UpdateParameterSet() [5/11]
template<typename ParameterType, typename ExpressionType> bool UpdateParameterSet (TArray< FSparseVolumeTextureParameterValue > & Parameters, UMaterial * ParentMaterial)
Definition at line 286 of file MaterialInstanceUpdateParameterSet.h.
References MaterialInstance_Private::UpdateParameterSet_WithCachedData().
UpdateParameterSet() [6/11]
template<typename ParameterType, typename ExpressionType> bool UpdateParameterSet (TArray< FStaticComponentMaskParameter > & Parameters, UMaterial * ParentMaterial)
Definition at line 296 of file MaterialInstanceUpdateParameterSet.h.
References MaterialInstance_Private::UpdateParameterSet_WithCachedData().
UpdateParameterSet() [7/11]
template<typename ParameterType, typename ExpressionType> bool UpdateParameterSet (TArray< FStaticSwitchParameter > & Parameters, UMaterial * ParentMaterial)
Definition at line 291 of file MaterialInstanceUpdateParameterSet.h.
References MaterialInstance_Private::UpdateParameterSet_WithCachedData().
UpdateParameterSet() [8/11]
template<typename ParameterType, typename ExpressionType> bool UpdateParameterSet (TArray< FTextureCollectionParameterValue > & Parameters, UMaterial * ParentMaterial)
Definition at line 271 of file MaterialInstanceUpdateParameterSet.h.
References MaterialInstance_Private::UpdateParameterSet_WithCachedData().
UpdateParameterSet() [9/11]
template<typename ParameterType, typename ExpressionType> bool UpdateParameterSet (TArray< FTextureParameterValue > & Parameters, UMaterial * ParentMaterial)
Definition at line 266 of file MaterialInstanceUpdateParameterSet.h.
References MaterialInstance_Private::UpdateParameterSet_WithCachedData().
UpdateParameterSet() [10/11]
template<typename ParameterType, typename ExpressionType> bool UpdateParameterSet (TArray< FVectorParameterValue > & Parameters, UMaterial * ParentMaterial)
Definition at line 256 of file MaterialInstanceUpdateParameterSet.h.
References MaterialInstance_Private::UpdateParameterSet_WithCachedData().
UpdateParameterSet() [11/11]
template<typename ParameterType, typename ExpressionType> bool UpdateParameterSet (TArray< ParameterType > & Parameters, UMaterial * ParentMaterial)
This function takes a array of parameter structs and attempts to establish a reference to the expression object each parameter represents.
If a reference exists, the function checks to see if the parameter has been renamed.
Parameters
Parameters Array of parameters to operate on.
ParentMaterial Parent material to search in for expressions.
Returns
Returns whether or not any of the parameters was changed.
Definition at line 245 of file MaterialInstanceUpdateParameterSet.h.
References MaterialInstance_Private::UpdateParameterSet_FullTraversal().