Unreal Engine 5.6 C++ API: Runtime/Engine/Public/MaterialTypes.h File Reference
MaterialTypes.h File Reference
#include "CoreMinimal.h"
#include "Misc/Guid.h"
#include "Misc/EnumClassFlags.h"
#include "Serialization/MemoryLayout.h"
#include "UObject/SoftObjectPtr.h"
#include "Shader/ShaderTypes.h"
#include "MaterialTypes.generated.h"
Data Structures
struct FMaterialParameterMetadata
Holds a value, along with editor-only metadata that describes that value.
struct FMaterialParameterValue
struct FMaterialTextureValue
struct FMemoryImageMaterialParameterInfo
struct FSubstrateCompilationConfig
Enumerations
enum class EMaterialGetParameterValueFlags : uint32 {
None = 0u , CheckNonOverrides = (1u << 0) , CheckInstanceOverrides = (1u << 1) , CheckAll = CheckNonOverrides | CheckInstanceOverrides ,
Default = CheckAll
}
enum class EMaterialSetParameterValueFlags : uint32 { None = 0u , SetCurveAtlas = (1u << 0) }
Functions
UENUM() enum class EMaterialParameterType DECLARE_INTRINSIC_TYPE_LAYOUT (EMaterialParameterType)
ENUM_CLASS_FLAGS (EMaterialGetParameterValueFlags)
ENUM_CLASS_FLAGS (EMaterialSetParameterValueFlags)
EMaterialParameterType GetMaterialParameterTypeFromString (FString TypeName)
UE::Shader::FType GetShaderValueType (EMaterialParameterType Type)
const UEnum * GetStaticMaterialParameterTypeEnum ()
bool IsNumericMaterialParameter (EMaterialParameterType InType)
bool IsStaticMaterialParameter (EMaterialParameterType InType)
FString MaterialParameterTypeToString (EMaterialParameterType Type)
UENUM() enum EMaterialParameterAssociation USTRUCT () struct FMaterialParameterInfo
Variables
constexpr int32 NumMaterialEditorOnlyParameterTypes = NumMaterialParameterTypes - NumMaterialRuntimeParameterTypes
constexpr int32 NumMaterialParameterTypes = (int32)EMaterialParameterType::Num
constexpr int32 NumMaterialRuntimeParameterTypes = (int32)EMaterialParameterType::NumRuntime
Enumeration Type Documentation
EMaterialGetParameterValueFlags
enum class EMaterialGetParameterValueFlags : uint32 strong
Enumerator
None
CheckNonOverrides
CheckInstanceOverrides
CheckAll
Default
Definition at line 257 of file MaterialTypes.h.
EMaterialSetParameterValueFlags
enum class EMaterialSetParameterValueFlags : uint32 strong
Enumerator
None
SetCurveAtlas
Definition at line 268 of file MaterialTypes.h.
Function Documentation
DECLARE_INTRINSIC_TYPE_LAYOUT()
UENUM() enum class EMaterialParameterType DECLARE_INTRINSIC_TYPE_LAYOUT (EMaterialParameterType)
ENUM_CLASS_FLAGS() [1/2]
ENUM_CLASS_FLAGS (EMaterialGetParameterValueFlags)
ENUM_CLASS_FLAGS() [2/2]
ENUM_CLASS_FLAGS (EMaterialSetParameterValueFlags)
References A, B, BlueprintType, G, and R.
GetMaterialParameterTypeFromString()
EMaterialParameterType GetMaterialParameterTypeFromString (FString TypeName) inline
Definition at line 251 of file MaterialTypes.h.
References Enum, FName, and GetStaticMaterialParameterTypeEnum().
GetShaderValueType()
UE::Shader::FType GetShaderValueType (EMaterialParameterType Type) extern
Referenced by FUniformExpressionSet::GetDefaultParameterValue().
GetStaticMaterialParameterTypeEnum()
const UEnum * GetStaticMaterialParameterTypeEnum () inline
Definition at line 238 of file MaterialTypes.h.
References check, Enum, and StaticEnum().
Referenced by GetMaterialParameterTypeFromString(), and MaterialParameterTypeToString().
IsNumericMaterialParameter()
bool IsNumericMaterialParameter (EMaterialParameterType InType) inline
Definition at line 211 of file MaterialTypes.h.
IsStaticMaterialParameter()
bool IsStaticMaterialParameter (EMaterialParameterType InType) inline
Definition at line 224 of file MaterialTypes.h.
MaterialParameterTypeToString()
FString MaterialParameterTypeToString (EMaterialParameterType Type) inline
Definition at line 245 of file MaterialTypes.h.
References Enum, and GetStaticMaterialParameterTypeEnum().
USTRUCT()
UENUM() enum EMaterialParameterAssociation USTRUCT ()
Whether this is a global parameter, or part of a layer or blend
Layer or blend index this parameter is part of. INDEX_NONE for global parameters.
Definition at line 30 of file MaterialTypes.h.
References Append(), Ar, BlueprintType, Category, FName, FORCEINLINE, GENERATED_USTRUCT_BODY, GetTypeHash(), HashCombine(), INDEX_NONE, InName, Name, NameToScriptName(), operator!=(), operator<<(), operator==(), ToString(), UPROPERTY, and Value.
Variable Documentation
NumMaterialEditorOnlyParameterTypes
int32 NumMaterialEditorOnlyParameterTypes = NumMaterialParameterTypes - NumMaterialRuntimeParameterTypes inline constexpr
Definition at line 209 of file MaterialTypes.h.
NumMaterialParameterTypes
int32 NumMaterialParameterTypes = (int32)EMaterialParameterType::Num inline constexpr
Definition at line 207 of file MaterialTypes.h.
NumMaterialRuntimeParameterTypes
int32 NumMaterialRuntimeParameterTypes = (int32)EMaterialParameterType::NumRuntime inline constexpr
Definition at line 208 of file MaterialTypes.h.