Unreal Engine 5.6 C++ API: Runtime/Core/Public/Templates/MemoryOps.h File Reference
MemoryOps.h File Reference
#include "CoreTypes.h"
#include "HAL/UnrealMemory.h"
#include "Templates/IsTriviallyCopyAssignable.h"
#include "Templates/IsTriviallyCopyConstructible.h"
#include "Templates/Requires.h"
#include "Templates/UnrealTypeTraits.h"
#include "Traits/UseBitwiseSwap.h"
#include <new>
#include <type_traits>
Namespaces
namespace UE
Utility functions for applying transformations to meshes.
namespace UE::Core
namespace UE::Core::Private
TAdderRef and TAdderReserverRef are type-erasing adapters that allow a function to add to (and reserve) a container without the function knowing about the specific type of the container.
namespace UE::Core::Private::MemoryOps
Functions
template<typename ElementType, typename SizeType UE_REQUIRES>
FORCEINLINE bool CompareItems (const ElementType *A, const ElementType *B, SizeType Count)
template<typename ElementType, typename SizeType UE_REQUIRES>
FORCENOINLINE bool CompareItems (const ElementType *A, const ElementType *B, SizeType Count)
template<typename DestinationElementType, typename SourceElementType, typename SizeType UE_REQUIRES>
FORCEINLINE void ConstructItems (void *Dest, const SourceElementType *Source, SizeType Count)
Constructs a range of items into memory from a set of arguments.
template<typename DestinationElementType, typename SourceElementType, typename SizeType UE_REQUIRES>
FORCENOINLINE void ConstructItems (void *Dest, const SourceElementType *Source, SizeType Count)
template<typename ElementType, typename SizeType UE_REQUIRES>
FORCEINLINE void CopyAssignItems (ElementType *Dest, const ElementType *Source, SizeType Count)
Copy assigns a range of items.
template<typename ElementType, typename SizeType UE_REQUIRES>
FORCENOINLINE void CopyAssignItems (ElementType *Dest, const ElementType *Source, SizeType Count)
template<typename ElementType, typename SizeType UE_REQUIRES>
FORCEINLINE void DefaultConstructItems (void *Address, SizeType Count)
Default constructs a range of items in memory.
template<typename ElementType, typename SizeType UE_REQUIRES>
FORCENOINLINE void DefaultConstructItems (void *Address, SizeType Count)
template<typename ElementType>
FORCEINLINE void DestructItem (ElementType *Element)
Destructs a single item in memory.
template<typename ElementType, typename SizeType UE_REQUIRES>
FORCEINLINE void DestructItems (ElementType *Element, SizeType Count)
Destructs a range of items in memory.
template<typename ElementType, typename SizeType UE_REQUIRES>
FORCENOINLINE void DestructItems (ElementType *Element, SizeType Count)
template<typename ElementType, typename SizeType UE_REQUIRES>
FORCEINLINE void MoveAssignItems (ElementType *Dest, const ElementType *Source, SizeType Count)
Move assigns a range of items.
template<typename ElementType, typename SizeType UE_REQUIRES>
FORCENOINLINE void MoveAssignItems (ElementType *Dest, const ElementType *Source, SizeType Count)
template<typename ElementType, typename SizeType UE_REQUIRES>
FORCEINLINE void MoveConstructItems (void *Dest, const ElementType *Source, SizeType Count)
Move constructs a range of items into memory.
template<typename ElementType, typename SizeType UE_REQUIRES>
FORCENOINLINE void MoveConstructItems (void *Dest, const ElementType *Source, SizeType Count)
template<typename DestinationElementType, typename SourceElementType, typename SizeType>
FORCEINLINE void RelocateConstructItem (void *Dest, const SourceElementType *Source)
Relocates a single items to a new memory location as a new type.
template<typename DestinationElementType, typename SourceElementType, typename SizeType UE_REQUIRES>
FORCEINLINE void RelocateConstructItems (void *Dest, SourceElementType *Source, SizeType Count)
Relocates a range of items to a new memory location as a new type.
template<typename DestinationElementType, typename SourceElementType, typename SizeType UE_REQUIRES>
FORCENOINLINE void RelocateConstructItems (void *Dest, SourceElementType *Source, SizeType Count)
Variables
template<typename DestinationElementType, typename SourceElementType>
constexpr bool UE::Core::Private::MemoryOps::TCanBitwiseRelocate_V
Function Documentation
CompareItems() [1/2]
template<typename ElementType, typename SizeType UE_REQUIRES> FORCEINLINE bool CompareItems (const ElementType * A, const ElementType * B, SizeType Count)
Definition at line 339 of file MemoryOps.h.
References A, B, Count, FORCEINLINE, and FMemory::Memcmp().
Referenced by operator==(), RangedForIteratorType< FAnimNextTraitEventPtr >::operator==(), and UE::Geometry::TDynamicVector< Type, BlockSize >::operator==.
CompareItems() [2/2]
template<typename ElementType, typename SizeType UE_REQUIRES> FORCENOINLINE bool CompareItems (const ElementType * A, const ElementType * B, SizeType Count)
Definition at line 348 of file MemoryOps.h.
References A, B, Count, and FORCENOINLINE.
ConstructItems() [1/2]
template<typename DestinationElementType, typename SourceElementType, typename SizeType UE_REQUIRES> FORCEINLINE void ConstructItems (void * Dest, const SourceElementType * Source, SizeType Count)
Constructs a range of items into memory from a set of arguments.
The arguments come from an another array.
Parameters
Dest The memory location to start copying into.
Source A pointer to the first argument to pass to the constructor.
Count The number of elements to copy.
Definition at line 127 of file MemoryOps.h.
References Count, FORCEINLINE, FMemory::Memcpy(), and Source.
Referenced by FScriptArrayHelper::AddValues(), RangedForIteratorType< FAnimNextTraitEventPtr >::Append(), RangedForIteratorType< FAnimNextTraitEventPtr >::Append(), RangedForIteratorType< FAnimNextTraitEventPtr >::Append(), RangedForIteratorType< FAnimNextTraitEventPtr >::Append(), RangedForIteratorType< FAnimNextTraitEventPtr >::Append(), TDeque< InElementType, InAllocatorType >::CopyElements(), RangedForIteratorType< FAnimNextTraitEventPtr >::CopyToEmpty(), RangedForIteratorType< FAnimNextTraitEventPtr >::CopyToEmptyWithSlack(), TDeque< InElementType, InAllocatorType >::CopyUnchecked(), RangedForIteratorType< FAnimNextTraitEventPtr >::Insert(), RangedForIteratorType< FAnimNextTraitEventPtr >::Insert(), RangedForIteratorType< FAnimNextTraitEventPtr >::Insert(), RangedForIteratorType< FAnimNextTraitEventPtr >::Insert(), FScriptArrayHelper::InsertValues(), and TSet< class UObject * >::operator=().
ConstructItems() [2/2]
template<typename DestinationElementType, typename SourceElementType, typename SizeType UE_REQUIRES> FORCENOINLINE void ConstructItems (void * Dest, const SourceElementType * Source, SizeType Count)
Definition at line 140 of file MemoryOps.h.
References Count, FORCENOINLINE, and Source.
CopyAssignItems() [1/2]
template<typename ElementType, typename SizeType UE_REQUIRES> FORCEINLINE void CopyAssignItems (ElementType * Dest, const ElementType * Source, SizeType Count)
Copy assigns a range of items.
Parameters
Dest The memory location to start assigning to.
Source A pointer to the first item to assign.
Count The number of elements to assign.
Definition at line 163 of file MemoryOps.h.
References Count, FORCEINLINE, FMemory::Memcpy(), and Source.
Referenced by TTraversalHistory< KDOP_IDX_TYPE >::AddNode(), and FMaterialShaderMap::GetEstimatedLWCFuncUsages().
CopyAssignItems() [2/2]
template<typename ElementType, typename SizeType UE_REQUIRES> FORCENOINLINE void CopyAssignItems (ElementType * Dest, const ElementType * Source, SizeType Count)
Definition at line 172 of file MemoryOps.h.
References Count, FORCENOINLINE, and Source.
DefaultConstructItems() [1/2]
template<typename ElementType, typename SizeType UE_REQUIRES> FORCEINLINE void DefaultConstructItems (void * Address, SizeType Count)
Default constructs a range of items in memory.
Parameters
Elements The address of the first memory location to construct at.
Count The number of elements to destruct.
Definition at line 37 of file MemoryOps.h.
References Count, FORCEINLINE, and FMemory::Memset().
Referenced by MallocBinnedPrivate::TGlobalRecycler< NumSmallPools >::FBundlePointer::FBundlePointer(), RangedForIteratorType< FAnimNextTraitEventPtr >::AddDefaulted(), RangedForIteratorType< FAnimNextTraitEventPtr >::AddDefaulted(), RangedForIteratorType< FAnimNextTraitEventPtr >::AddDefaulted_GetRef(), TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::AllocateHashBuckets(), UE::MovieScene::FComponentTypeInfo::TComplexComponentOpsBase< T >::ConstructItems(), TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::Internal::GetOrCreatePoolInfo(), TEvaluationTreeEntryContainer< ElementType >::Insert(), RangedForIteratorType< FAnimNextTraitEventPtr >::InsertDefaulted(), RangedForIteratorType< FAnimNextTraitEventPtr >::InsertDefaulted(), RangedForIteratorType< FAnimNextTraitEventPtr >::InsertDefaulted_GetRef(), TEvaluationTreeEntryContainer< ElementType >::ReserveEntry(), and RangedForIteratorType< FAnimNextTraitEventPtr >::SetNum().
DefaultConstructItems() [2/2]
template<typename ElementType, typename SizeType UE_REQUIRES> FORCENOINLINE void DefaultConstructItems (void * Address, SizeType Count)
Definition at line 46 of file MemoryOps.h.
References Count, and FORCENOINLINE.
DestructItem()
template<typename ElementType> FORCEINLINE void DestructItem (ElementType * Element)
Destructs a single item in memory.
Parameters
Elements A pointer to the item to destruct.
Note
: This function is optimized for values of T, and so will not dynamically dispatch destructor calls if T's destructor is virtual.
Definition at line 65 of file MemoryOps.h.
References FORCEINLINE.
Referenced by TClosableMpscQueue< T >::~TClosableMpscQueue(), TMpscQueue< T, AllocatorType >::~TMpscQueue(), TSpscQueue< T, AllocatorType >::~TSpscQueue(), UE::Tasks::Private::TTaskWithResult< ResultType >::~TTaskWithResult(), TClosableMpscQueue< T >::Close_NonMember(), UE::TConsumeAllMpmcQueue< T, AllocatorType >::ConsumeAll(), TMpscQueue< T, AllocatorType >::Dequeue(), TSpscQueue< T, AllocatorType >::Dequeue(), FScriptArrayHelper::DestroyContainer_Unsafe(), SharedPointerInternals::TIntrusiveReferenceController< ObjectType, Mode >::DestroyObject(), TOptional< FAnyDataReference >(*)(const FOperatorSettings &InSettings, FName DataType, const FLiteral &InLiteral, EDataReferenceAccessType InAccessType)::DestroyValue(), UE::Core::Private::TDestructorCaller< T >::Destruct(), UScriptStruct::TCppStructOps< CPPSTRUCT >::Destruct(), TClosableMpscQueue< T >::Enqueue(), TGraphTask< TTask >::ExecuteTask(), UE::Tasks::Private::TExecutableTaskBase< TaskBodyType, ResultType, Enable >::ExecuteTask(), UE::Tasks::Private::TExecutableTaskBase< TaskBodyType, typename TEnableIf< std::is_same_v< TInvokeResult_T< TaskBodyType >, void > >::Type >::ExecuteTask(), TSparseArray< SetElementType, typename Allocator::SparseArrayAllocator >::Move(), TDeque< InElementType, InAllocatorType >::PopFirst(), TDeque< InElementType, InAllocatorType >::PopLast(), TRingBuffer< T, AllocatorT >::RemoveAll(), RangedForIteratorType< FAnimNextTraitEventPtr >::RemoveAtImpl(), RangedForIteratorType< FAnimNextTraitEventPtr >::RemoveAtSwapImpl(), TDeque< InElementType, InAllocatorType >::TryPopFirst(), TDeque< InElementType, InAllocatorType >::TryPopLast(), and UE::UE_DEPRECATED().
DestructItems() [1/2]
template<typename ElementType, typename SizeType UE_REQUIRES> FORCEINLINE void DestructItems (ElementType * Element, SizeType Count)
Destructs a range of items in memory.
Parameters
Elements A pointer to the first item to destruct.
Count The number of elements to destruct.
Note
: This function is optimized for values of T, and so will not dynamically dispatch destructor calls if T's destructor is virtual.
Definition at line 93 of file MemoryOps.h.
References Count, and FORCEINLINE.
Referenced by RangedForIteratorType< FAnimNextTraitEventPtr >::~TArray(), TBasicArray< T >::~TBasicArray(), TSortedMap< FFrontendQueryKey, FFrontendQueryPartition >::AllocateMemoryForEmplace(), TRingBuffer< T, AllocatorT >::DestructRange(), RangedForIteratorType< FAnimNextTraitEventPtr >::Empty(), FScriptSetHelper::EmptyElements(), FScriptArrayHelper::EmptyValues(), FScriptMapHelper::EmptyValues(), FScriptArrayHelper::MoveAssign(), FScriptMapHelper::MoveAssign(), RangedForIteratorType< FAnimNextTraitEventPtr >::operator=(), RangedForIteratorType< FAnimNextTraitEventPtr >::operator=(), RangedForIteratorType< FAnimNextTraitEventPtr >::operator=(), RangedForIteratorType< FAnimNextTraitEventPtr >::operator=(), RangedForIteratorType< FAnimNextTraitEventPtr >::operator=(), RangedForIteratorType< FAnimNextTraitEventPtr >::operator=(), RangedForIteratorType< FAnimNextTraitEventPtr >::operator=(), TSet< class UObject * >::operator=(), RangedForIteratorType< FAnimNextTraitEventPtr >::RemoveAll(), FScriptMapHelper::RemoveAt(), FScriptSetHelper::RemoveAt(), TBasicArray< T >::RemoveAt(), RangedForIteratorType< FAnimNextTraitEventPtr >::RemoveAtImpl(), RangedForIteratorType< FAnimNextTraitEventPtr >::RemoveAtSwapImpl(), RangedForIteratorType< FAnimNextTraitEventPtr >::RemoveSingle(), FScriptArrayHelper::RemoveValues(), RangedForIteratorType< FAnimNextTraitEventPtr >::Reset(), TDeque< InElementType, InAllocatorType >::Reset(), and TRingBuffer< T, AllocatorT >::ShiftLastToFirst().
DestructItems() [2/2]
template<typename ElementType, typename SizeType UE_REQUIRES> FORCENOINLINE void DestructItems (ElementType * Element, SizeType Count)
Definition at line 101 of file MemoryOps.h.
References Count, and FORCENOINLINE.
MoveAssignItems() [1/2]
template<typename ElementType, typename SizeType UE_REQUIRES> FORCEINLINE void MoveAssignItems (ElementType * Dest, const ElementType * Source, SizeType Count)
Move assigns a range of items.
Parameters
Dest The memory location to start move assigning to.
Source A pointer to the first item to move assign.
Count The number of elements to move assign.
Definition at line 314 of file MemoryOps.h.
References Count, FORCEINLINE, FMemory::Memmove(), and Source.
MoveAssignItems() [2/2]
template<typename ElementType, typename SizeType UE_REQUIRES> FORCENOINLINE void MoveAssignItems (ElementType * Dest, const ElementType * Source, SizeType Count)
Definition at line 323 of file MemoryOps.h.
References Count, FORCENOINLINE, and Source.
MoveConstructItems() [1/2]
template<typename ElementType, typename SizeType UE_REQUIRES> FORCEINLINE void MoveConstructItems (void * Dest, const ElementType * Source, SizeType Count)
Move constructs a range of items into memory.
Parameters
Dest The memory location to start moving into.
Source A pointer to the first item to move from.
Count The number of elements to move.
Definition at line 282 of file MemoryOps.h.
References Count, FORCEINLINE, FMemory::Memmove(), and Source.
Referenced by TRingBuffer< T, AllocatorT >::MoveAppendRange().
MoveConstructItems() [2/2]
template<typename ElementType, typename SizeType UE_REQUIRES> FORCENOINLINE void MoveConstructItems (void * Dest, const ElementType * Source, SizeType Count)
Definition at line 291 of file MemoryOps.h.
References Count, FORCENOINLINE, and Source.
RelocateConstructItem()
template<typename DestinationElementType, typename SourceElementType, typename SizeType> FORCEINLINE void RelocateConstructItem (void * Dest, const SourceElementType * Source)
Relocates a single items to a new memory location as a new type.
This is a so-called 'destructive move' for which there is no single operation in C++ but which can be implemented very efficiently in general.
Parameters
Dest The memory location to relocate to.
Source A pointer to the first item to relocate.
Definition at line 191 of file MemoryOps.h.
References FORCEINLINE, FMemory::Memmove(), Source, UE::Core::Private::MemoryOps::TCanBitwiseRelocate_V, and TUseBitwiseSwap< T >::Value.
RelocateConstructItems() [1/2]
template<typename DestinationElementType, typename SourceElementType, typename SizeType UE_REQUIRES> FORCEINLINE void RelocateConstructItems (void * Dest, SourceElementType * Source, SizeType Count)
Relocates a range of items to a new memory location as a new type.
This is a so-called 'destructive move' for which there is no single operation in C++ but which can be implemented very efficiently in general.
Parameters
Dest The memory location to relocate to.
Source A pointer to the first item to relocate.
Count The number of elements to relocate.
Definition at line 234 of file MemoryOps.h.
References Count, FORCEINLINE, FMemory::Memmove(), and Source.
Referenced by RangedForIteratorType< FAnimNextTraitEventPtr >::Append(), TSparseArray< SetElementType, typename Allocator::SparseArrayAllocator >::Compact(), RangedForIteratorType< FAnimNextTraitEventPtr >::Insert(), RangedForIteratorType< FAnimNextTraitEventPtr >::Insert(), TEvaluationTreeEntryContainer< ElementType >::Insert(), TBasicArray< T >::InsertUninitialized(), RangedForIteratorType< FAnimNextTraitEventPtr >::InsertUninitializedImpl(), RangedForIteratorType< FAnimNextTraitEventPtr >::InsertUninitializedImpl(), TDeque< InElementType, InAllocatorType >::Linearize(), MoveByRelocate(), TFixedAllocator< NumInlineElements >::ForElementType< ElementType >::MoveToEmpty(), TNonRelocatableInlineAllocator< NumInlineElements >::ForElementType< ElementType >::MoveToEmpty(), TSizedInlineAllocator< NumInlineElements, IndexSize, SecondaryAllocator >::ForElementType< ElementType >::MoveToEmpty(), RangedForIteratorType< FAnimNextTraitEventPtr >::RemoveAll(), TBasicArray< T >::RemoveAt(), RangedForIteratorType< FAnimNextTraitEventPtr >::RemoveAtImpl(), RangedForIteratorType< FAnimNextTraitEventPtr >::RemoveAtImpl(), RangedForIteratorType< FAnimNextTraitEventPtr >::RemoveAtSwapImpl(), RangedForIteratorType< FAnimNextTraitEventPtr >::RemoveAtSwapImpl(), RangedForIteratorType< FAnimNextTraitEventPtr >::RemoveSingle(), TEvaluationTreeEntryContainer< ElementType >::ReserveEntry(), TNonRelocatableInlineAllocator< NumInlineElements >::ForElementType< ElementType >::ResizeAllocation(), TSizedInlineAllocator< NumInlineElements, IndexSize, SecondaryAllocator >::ForElementType< ElementType >::ResizeAllocation(), and TDeque< InElementType, InAllocatorType >::ShiftElementsLeft().
RelocateConstructItems() [2/2]
template<typename DestinationElementType, typename SourceElementType, typename SizeType UE_REQUIRES> FORCENOINLINE void RelocateConstructItems (void * Dest, SourceElementType * Source, SizeType Count)
Definition at line 254 of file MemoryOps.h.
References Count, FORCENOINLINE, and Source.