Unreal Engine 5.6 C++ API: Runtime/Core/Public/Memory/MemoryView.h File Reference
MemoryView.h File Reference
#include "CoreTypes.h"
#include "HAL/PlatformString.h"
#include "Math/NumericLimits.h"
#include "Math/UnrealMathUtility.h"
#include "Memory/MemoryFwd.h"
#include "Templates/AndOrNot.h"
#include "Templates/EnableIf.h"
#include "Templates/Identity.h"
#include "Templates/IsConst.h"
#include "Templates/PointerIsConvertibleFromTo.h"
#include "Templates/UnrealTemplate.h"
#include "Traits/IsContiguousContainer.h"
#include <initializer_list>
Data Structures
class TMemoryView< DataType >
A non-owning view of a contiguous region of memory.
Functions
constexpr TMemoryView< const void > MakeMemoryView (const void *Data, uint64 Size)
Make a non-owning const view of Size bytes starting at Data.
template<typename ContainerType UE_REQUIRES>
constexpr auto MakeMemoryView (ContainerType &&Container)
Make a non-owning view of the memory of the contiguous container.
template<typename DataType, typename DataEndType>
auto MakeMemoryView (DataType *Data, DataEndType *DataEnd)
Make a non-owning view starting at Data and ending at DataEnd.
template<typename T>
constexpr TMemoryView< const void > MakeMemoryView (std::initializer_list< typename TIdentity< T >::Type > List)
Make a non-owning view of the memory of the initializer list.
constexpr TMemoryView< void > MakeMemoryView (void *Data, uint64 Size)
Make a non-owning mutable view of Size bytes starting at Data.
template<typename DataType>
constexpr TMemoryView< DataType > operator+ (const TMemoryView< DataType > &View, uint64 Offset)
Advances the start of the view by an offset, which is clamped to stay within the view.
template<typename DataType>
constexpr TMemoryView< DataType > operator+ (uint64 Offset, const TMemoryView< DataType > &View)
Advances the start of the view by an offset, which is clamped to stay within the view.
Function Documentation
MakeMemoryView() [1/5]
TMemoryView< const void > MakeMemoryView (const void * Data, uint64 Size) inline nodiscard constexpr
Make a non-owning const view of Size bytes starting at Data.
Definition at line 263 of file MemoryView.h.
References TMemoryView< DataType >::Data, and TSequenceHistory< HistorySize >::Size.
MakeMemoryView() [2/5]
template<typename ContainerType UE_REQUIRES> auto MakeMemoryView (ContainerType && Container) inline nodiscard constexpr
Make a non-owning view of the memory of the contiguous container.
Definition at line 295 of file MemoryView.h.
References TMemoryView< DataType >::TMemoryView, Container, GetData(), GetNum(), and TIsConst< T >::Value.
MakeMemoryView() [3/5]
template<typename DataType, typename DataEndType> auto MakeMemoryView (DataType * Data, DataEndType * DataEnd) inline nodiscard
Make a non-owning view starting at Data and ending at DataEnd.
Definition at line 270 of file MemoryView.h.
References TMemoryView< DataType >::TMemoryView, and TMemoryView< DataType >::Data.
MakeMemoryView() [4/5]
template<typename T> TMemoryView< const void > MakeMemoryView (std::initializer_list< typename TIdentity< T >::Type > List) inline nodiscard constexpr
Make a non-owning view of the memory of the initializer list.
This overload is only available when the element type does not need to be deduced.
Definition at line 285 of file MemoryView.h.
References GetData(), and GetNum().
MakeMemoryView() [5/5]
TMemoryView< void > MakeMemoryView (void * Data, uint64 Size) inline nodiscard constexpr
Make a non-owning mutable view of Size bytes starting at Data.
Definition at line 257 of file MemoryView.h.
References TMemoryView< DataType >::Data, and TSequenceHistory< HistorySize >::Size.
Referenced by FMemoryReaderView::FMemoryReaderView(), FCbValue::AsBinary(), FCbValue::AsCustomById(), FCbValue::AsCustomByName(), FCbValue::AsObjectId(), FIoBuffer::GetMutableView(), TraceServices::TCachedStringStore< WIDECHAR >::GetOffsetOfString(), FCbFieldView::GetValueView(), FCbObjectId::GetView(), FIoBuffer::GetView(), FLargeMemoryWriter::GetView(), TCbFieldIterator< FieldType >::TryGetRangeView(), and UE::Private::WorldPartition::UpdateHash().
operator+() [1/2]
template<typename DataType> TMemoryView< DataType > operator+ (const TMemoryView< DataType > & View, uint64 Offset) inline nodiscard constexpr
Advances the start of the view by an offset, which is clamped to stay within the view.
Definition at line 244 of file MemoryView.h.
References TMemoryView< DataType >::TMemoryView.
operator+() [2/2]
template<typename DataType> TMemoryView< DataType > operator+ (uint64 Offset, const TMemoryView< DataType > & View) inline nodiscard constexpr
Advances the start of the view by an offset, which is clamped to stay within the view.
Definition at line 251 of file MemoryView.h.
References TMemoryView< DataType >::TMemoryView.