Unreal Engine 5.6 C++ API: S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/Metasound/Source/MetasoundFrontend/Public/MetasoundFrontendDocumentBuilder.h File Reference
MetasoundFrontendDocumentBuilder.h File Reference
#include "Containers/Map.h"
#include "Interfaces/MetasoundFrontendInterfaceRegistry.h"
#include "MetasoundFrontendDocumentCacheInterface.h"
#include "MetasoundDocumentInterface.h"
#include "MetasoundFrontendDocument.h"
#include "MetasoundFrontendDocumentModifyDelegates.h"
#include "MetasoundFrontendRegistries.h"
#include "MetasoundFrontendTransform.h"
#include "MetasoundVertex.h"
#include "Templates/Function.h"
#include "UObject/ScriptInterface.h"
#include "MetasoundFrontendDocumentBuilder.generated.h"
Data Structures
struct Metasound::Frontend::FModifyInterfaceOptions
struct Metasound::Frontend::FNamedEdge
Namespaces
namespace Metasound
standard Midi Controller ID according to the MIDI Association reference: https://www.midi.org/specifications-old/item/table-3-control-change-messages-data-bytes-2
namespace Metasound::Frontend
Macros
#define UE_API METASOUNDFRONTEND_API
Typedefs
using Metasound::Frontend::FConstClassAndNodeFunctionRef = TFunctionRef<void(const FMetasoundFrontendClass&, const FMetasoundFrontendNode&)>
using Metasound::Frontend::FFinalizeNodeFunctionRef = TFunctionRef<void(FMetasoundFrontendNode&, const Metasound::Frontend::FNodeRegistryKey&)>
Enumerations
enum class Metasound::Frontend::EInvalidEdgeReason : uint8 {
Metasound::Frontend::None = 0 , Metasound::Frontend::MismatchedAccessType , Metasound::Frontend::MismatchedDataType , Metasound::Frontend::MissingInput ,
Metasound::Frontend::MissingOutput , Metasound::Frontend::COUNT
}
Functions
METASOUNDFRONTEND_API FString Metasound::Frontend::LexToString (const EInvalidEdgeReason &InReason)
UCLASS() class UMetaSoundBuilderDocument USTRUCT () struct FMetaSoundFrontendDocumentBuilder
Macro Definition Documentation
UE_API
#define UE_API METASOUNDFRONTEND_API
Definition at line 18 of file MetasoundFrontendDocumentBuilder.h.
Function Documentation
USTRUCT()
UCLASS() class UMetaSoundBuilderDocument USTRUCT ()
Definition at line 148 of file MetasoundFrontendDocumentBuilder.h.
References CastChecked(), ExistingName, FName, GENERATED_BODY, InName, InOptions, IsValid(), Name, FGuid::NewGuid(), Owner, Params, Transform, Transient, UE_API, UE_DEPRECATED, UE_EXPERIMENTAL, UPROPERTY, and Vertex.