Unreal Engine 5.6 C++ API: S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/Metasound/Source/MetasoundFrontend/Public/MetasoundFrontendLiteral.h File Reference
MetasoundFrontendLiteral.h File Reference
#include "AudioParameterControllerInterface.h"
#include "MetasoundLiteral.h"
#include <type_traits>
#include "MetasoundFrontendLiteral.generated.h"
Namespaces
namespace Metasound
standard Midi Controller ID according to the MIDI Association reference: https://www.midi.org/specifications-old/item/table-3-control-change-messages-data-bytes-2
namespace Metasound::Frontend
Macros
#define UE_API METASOUNDFRONTEND_API
Functions
METASOUNDFRONTEND_API EMetasoundFrontendLiteralType Metasound::Frontend::GetMetasoundFrontendLiteralType (ELiteralType InLiteralType)
METASOUNDFRONTEND_API ELiteralType Metasound::Frontend::GetMetasoundLiteralType (EMetasoundFrontendLiteralType InLiteralType)
USTRUCT ()) struct FMetasoundFrontendLiteral
Variables
UENUM () enum class EMetasoundFrontendLiteralType
Injection Request Arguments.
Macro Definition Documentation
UE_API
#define UE_API METASOUNDFRONTEND_API
Definition at line 12 of file MetasoundFrontendLiteral.h.
Function Documentation
USTRUCT()
USTRUCT ()
Definition at line 68 of file MetasoundFrontendLiteral.h.
References A, B, BlueprintType, Clear(), Empty, GENERATED_BODY, IsValid(), meta, Num, operator==(), ToString(), UE_API, and UPROPERTY.
Variable Documentation
UENUM
UENUM () inline final
Injection Request Arguments.
Specifies what space a kinematic target is defined in Danny TODO this is much better than the similar mechanism in PCC and RBWC (which has a bUseSkeletalAnimation) - switch them to use this.
Additional information about a selection event.
Enumerates the source of the navigation.
Enumerates rounding options.
Enumerates brush image types.
Possible options for mirroring the brush image.
Enumerates tiling options for image drawing.
SProgressBar Fill Style.
Lists can exist as regular lists or as backing widgets for a tree.
Settings for the level sequence player actor.
What method should be used for serialziing.
Structure storing Layer Data for import.
Type of change we want to apply to a selection.
Level of severity of messages emitted by Tool framework.
Determines how a currently active tool is shutdown when switching to another tool.
UInteractiveToolManager can emit change events for the active tool in various ways.
FInputCaptureUpdate uses this type to indicate what state the capturing Behavior would like to transition to, based on the input event.
Used by FInputCaptureRequest to indicate whether the InputBehavior wants to capture or ignore an input event.
Various states of touch inputs.
Cell State.
Specifies the reference point of the local position.
Indicates whether an animation is additive, and what kind.
Filtering method for deciding whether to trigger a notify.
Raw Curve data for serialization.
Enum used to indicate desired behavior for MoveComponentTo latent function.
Possible columns for an FMatrix.
Different methods for interpolating rotation between transforms.
Struct for RootMotion Finish Velocity options.
Setting that controls behavior when movement is restricted to a 2D plane defined by a specific axis/normal, so that movement along the locked axis is not be possible.
Enumerates supported shader compression formats.
Enumerates VRS Fixed-foveation levels.
used by GetDefaultBackBufferPixelFormat
used by FPostProcessSettings AutoExposure
Enumerates available options for alpha channel through post processing.
Enumerates available options for Vertex Deformation Outputs Velocity.
Enumerates available options for velocity pass.
Enumerates available options for early Z-passes.
Enumerates available options for custom depth.
Enumerates available compositing sample counts.
Describes how often this component is allowed to move.
Types of valid physical material mask colors which may be associated with a physical material.
Controls behavior of WalkableSlopeOverride, determining how to affect walkability of surfaces for Characters.
Specifies if an AI pawn will automatically be possessed by an AI controller.
The network role of an actor on a local/remote network context.
Enum for controlling buckets for update rate optimizations if we need to stagger Multiple actor populations separately.
Enum used to indicate what type of timeline signature a function matches.
Enumerates available MobileLocalLightSetting.
Enumerates available GBufferFormats.
MegaLights Shadow type for a light component.
Ray Tracing Shadows type.
The default float precision for material's pixel shaders on mobile devices.
Deprecated rules for setting transform on attachment, new functions should use FAttachmentTransformRules isntead.
Enum to indicate if a node has advanced-display-pins, and whether they are shown.
Draw styles for data.
Types of coordinate space accepted by the functions.
Camera shake duration type.
Find and Replace Method for FMirrorFindReplaceExpression.
Determines the behavior this node will use when updating and evaluating.
AnimNotifies marked as BranchingPoints will create these markers on their Begin/End times.
Dummy types used to mark up missing types when creating property bags.
Getter and setter result code.
Configure settings for the 2D Level Editor.
Controls the level of support you want to have for widget property binding.
Pair of state guid and its associated state handle created at compilation.
Fallback behavior indicating what to do after failing to select a state.
Describes the origin of an applied transition.
Indicates how TagQueries from slots and parent object will be processed against Tags from a find request.
Available Icvfx camera sync types.
Control how active Weights are used to affect point radius.
Mode passed to ApplyMeshBevelSelection to control how the input Selection should be interpreted as selecting an area of the mesh to Bevel.
Control how details like mesh attributes are handled when one mesh is appended to another.
Enumeration for ways a single GameplayEffect asset can stack.
Gameplay effect duration policies.
Enumeration representing the types of scoped modifier aggregator usages available.
EGameplayCueNotify_AttachPolicy.
These are generic, nonpayload carrying events that are replicated between the client and server.
SDI Output type.
SDI Input type.
Timecode formats.
SDI transport type.
Quad link transport type.
Single angle : both wheels steer by the same amount AngleRatio : outer wheels on corner steer less than the inner ones by set ratio Ackermann : Ackermann steering principle is applied.
Input Options.
Sets per-muscle parameters for custom muscle contraction.
Encapsulates the parameters required to initiate an injection request.
Struct data structure to store curve names and muscle names
Specifies if the gameplay cue notify should attach to the target actor. FGameplayCueNotify_PlacementInfo
Specifies how the gameplay cue notify will be positioned in the world.
Struct representing modifier info used exclusively for "scoped" executions that happen instantaneously. These are folded into a calculation only for the extent of the calculation and never permanently added to an aggregator.
Enumeration of policies for dealing with duration of a gameplay effect while stacking Enumeration of policies for dealing with the period of a gameplay effect while stacking Enumeration of policies for dealing gameplay effect stacks that expire (in duration based effects). Enumeration of policies for dealing with the period of a gameplay effect when inhibition is removed Holds evaluated magnitude from a GameplayEffect modifier
Data that describes what happened in an attribute modification. This is passed to ability set callbacks
Controls the distribution of sample radii
Struct used to define how traces should be handled.
Runtime representation of an event description.
Property bag alterations result code.
These are used in the UI to display error message.
They create stopping points when the Montage is being ticked to dispatch events.
Camera shake duration.
Controls where the sampler for different texture lookups comes from defines how MipValue is used Describes how to handle lighting of translucent objets Determines how the refraction offset should be computed for the material. Determines how the refraction account for the coverage with Substrate. It can only be used when Substrate is enabled. Determines how the pixel depth offset is evaluated and applied. Must match PODM_LEGACY in MaterialTemplace.ush. Enumerates available options for the translucency sort policy.
Warning
When this enum is updated please update CVarGBufferFormat comments
When this enum is updated please update CVarMobileForwardEnableLocalLights comments Controls the way that the width scale property affects animation trails. Specifies how particle collision is computed for GPU particles
Enum used to describe what type of collision is enabled on a body.
Container for Animation Update Rate parameters. They are shared for all components of an Actor, so they can be updated in sync.
Describes if an actor can enter a low network bandwidth dormant mode Specifies which player index will pass input to this actor/component
Specifies why an actor is being deleted/removed from a level
See also
FWalkableSlopeOverride
UCharacterMovementComponent::GetWalkableFloorAngle(), UCharacterMovementComponent::SetWalkableFloorAngle() Struct allowing control over "walkable" normals, by allowing a restriction or relaxation of what steepness is normally walkable.
The renderer will always generate premultiplied RGBA with alpha as translucency (0 = fully opaque; 1 = fully translucent).
MovementComponent is an abstract component class that defines functionality for moving a PrimitiveComponent (our UpdatedComponent) each tick. Base functionality includes:
Restricting movement to a plane or axis.
Utility functions for special handling of collision results (SlideAlongSurface(), ComputeSlideVector(), TwoWallAdjust()).
Utility functions for moving when there may be initial penetration (SafeMoveUpdatedComponent(), ResolvePenetration()).
Automatically registering the component tick and finding a component to move on the owning Actor. Normally the root component of the owning actor is moved, however another component may be selected (see SetUpdatedComponent()). During swept (non-teleporting) movement only collision of UpdatedComponent is considered, attached components will teleport to the end location ignoring collision.
This can be different in some cases, e.g. for instanced meshes.
This allows different modes to control how tools activate/deactivate on undo/redo, which is necessary because some modes (eg Modeling Mode) do not support redo "into" a Tool, while others require it (like Paint Mode)
Dictates when compression should be used. Utility struct used to wrap serialized data and handle compression / decompression.
Enumerates the genesis of the navigation, where generated the navigation Enumerates horizontal alignment options, i.e. for widget slots. Enumerates vertical alignment options, i.e. for widget slots. Enumerates possible placements for pop-up menus. Enumerates widget orientations. Enumerates scroll directions. Additional information about a text committal
Specifies what space the simulation should run in Properties common to all collision shape types
Rate at which the input value rises
Rate at which the input value falls
Controller input curve, various predefined options, linear, squared, or user can specify a custom curve function
Controller input curve - should be a normalized float curve, i.e. time from 0 to 1 and values between 0 and 1 This curve is only sued if the InputCurveFunction above is set to CustomCurve
Change an output value using max rise and fall rates
Definition at line 40 of file MetasoundFrontendLiteral.h.