Unreal Engine 5.6 C++ API: S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/Metasound/Source/MetasoundFrontend/Public/MetasoundFrontendDocument.h File Reference
MetasoundFrontendDocument.h File Reference
#include "Algo/Transform.h"
#include "Containers/Array.h"
#include "Containers/Map.h"
#include "IAudioParameterInterfaceRegistry.h"
#include "Internationalization/Text.h"
#include "MetasoundAccessPtr.h"
#include "MetasoundFrontendLiteral.h"
#include "MetasoundOperatorData.h"
#include "MetasoundNodeInterface.h"
#include "MetasoundVertex.h"
#include "Misc/Guid.h"
#include "StructUtils/InstancedStruct.h"
#include "StructUtils/SharedStruct.h"
#include "Templates/Function.h"
#include "Templates/Invoke.h"
#include "Templates/TypeHash.h"
#include "UObject/NoExportTypes.h"
#include "MetasoundFrontendDocument.generated.h"
Data Structures
struct TStructOpsTypeTraits< FMetasoundCommentNodeIntVector >
Migratory type to avoid adding dependency on Slate FDeprecateSlateVector2D, and by extension, bring in unnecessary Engine dependencies therein.
Namespaces
namespace Metasound
standard Midi Controller ID according to the MIDI Association reference: https://www.midi.org/specifications-old/item/table-3-control-change-messages-data-bytes-2
namespace Metasound::Frontend
namespace Metasound::Frontend::DisplayStyle
namespace Metasound::Frontend::DisplayStyle::EdgeAnimation
namespace Metasound::Frontend::DisplayStyle::NodeLayout
Macros
#define UE_API METASOUNDFRONTEND_API
Typedefs
using Metasound::Frontend::FForEachLiteralFunctionRef = TFunctionRef<void(const FName& InDataTypeName, const FMetasoundFrontendLiteral&)>
Signature of function called for each found literal.
Functions
METASOUNDFRONTEND_API EMetasoundFrontendVertexAccessType Metasound::Frontend::CoreVertexAccessTypeToFrontendVertexAccessType (Metasound::EVertexAccessType InAccessType)
constexpr FGuid Metasound::Frontend::DefaultPageID (0, 0, 0, 0)
METASOUNDFRONTEND_API void Metasound::Frontend::ForEachLiteral (const FMetasoundFrontendClass &InClass, FForEachLiteralFunctionRef OnLiteral)
Execute the provided function for each literal on a FMetasoundFrontendClass.
METASOUNDFRONTEND_API void Metasound::Frontend::ForEachLiteral (const FMetasoundFrontendClassInterface &InClassInterface, FForEachLiteralFunctionRef OnLiteral)
METASOUNDFRONTEND_API void Metasound::Frontend::ForEachLiteral (const FMetasoundFrontendDocument &InDoc, FForEachLiteralFunctionRef OnLiteral)
Execute the provided function for each literal on a FMetasoundFrontendDocument.
METASOUNDFRONTEND_API void Metasound::Frontend::ForEachLiteral (const FMetasoundFrontendDocument &InDoc, FForEachLiteralFunctionRef OnLiteral, const FGuid &InPageID)
Execute the provided function for each literal on a FMetasoundFrontendDocument filtered by the given PageID.
METASOUNDFRONTEND_API void Metasound::Frontend::ForEachLiteral (const FMetasoundFrontendGraphClass &InGraphClass, FForEachLiteralFunctionRef OnLiteral)
Execute the provided function for each literal on a FMetasoundFrontendGraphClass.
METASOUNDFRONTEND_API void Metasound::Frontend::ForEachLiteral (const FMetasoundFrontendGraphClass &InGraphClass, FForEachLiteralFunctionRef OnLiteral, const FGuid &InPageID)
Execute the provided function for each literal on a FMetasoundFrontendGraphClass filtered by the given PageID.
METASOUNDFRONTEND_API void Metasound::Frontend::ForEachLiteral (const FMetasoundFrontendNode &InNode, FForEachLiteralFunctionRef OnLiteral)
Execute the provided function for each literal on a FMetasoundFrontendNode.
METASOUNDFRONTEND_API EVertexAccessType Metasound::Frontend::FrontendVertexAccessTypeToCoreVertexAccessType (EMetasoundFrontendVertexAccessType InAccessType)
METASOUNDFRONTEND_API const TCHAR * LexToString (EMetasoundFrontendClassType InClassType)
METASOUNDFRONTEND_API const TCHAR * LexToString (EMetasoundFrontendVertexAccessType InVertexAccess)
METASOUNDFRONTEND_API bool Metasound::Frontend::StringToClassType (const FString &InString, EMetasoundFrontendClassType &OutClassType)
UENUM () enum class EMetasoundFrontendVertexAccessType
USTRUCT () struct FMetaSoundFrontendNodeConfiguration
Struct for configuring a node.
Variables
const FLinearColor METASOUNDFRONTEND_API Metasound::Frontend::DisplayStyle::EdgeAnimation::DefaultColor
const FVector2D METASOUNDFRONTEND_API Metasound::Frontend::DisplayStyle::NodeLayout::DefaultOffsetX
const FVector2D METASOUNDFRONTEND_API Metasound::Frontend::DisplayStyle::NodeLayout::DefaultOffsetY
constexpr TCHAR Metasound::Frontend::DefaultPageName [] = TEXT("Default")
const FGuid METASOUNDFRONTEND_API Metasound::FrontendInvalidID
Macro Definition Documentation
UE_API
#define UE_API METASOUNDFRONTEND_API
Definition at line 28 of file MetasoundFrontendDocument.h.
Function Documentation
LexToString() [1/2]
METASOUNDFRONTEND_API const TCHAR * LexToString (EMetasoundFrontendClassType InClassType)
Referenced by TProperty_Numeric< InTCppType >::TConvertAndSet< FromType, ToType >::TConvertAndSet(), FPlatformCompressionUtilities::AppendHash(), Metasound::FAnyDataReference::TGetAs< TDataValueReference< DataType > >::Get(), Metasound::FAnyDataReference::TGetAs< TDataWriteReference< DataType > >::Get(), TProperty_Numeric< InTCppType >::GetNumericPropertyValueToString(), TProperty_Numeric< InTCppType >::GetNumericPropertyValueToString_InContainer(), FCookStatsManager::ImplCreateKeyValueArray(), FCookStatsManager::ImplCreateKeyValueArray(), FCookStatsManager::ImplCreateKeyValueArray(), FPackageName::IsPackageFilename(), FShaderPreprocessOutput::LogError(), Metasound::TSender< TDataType >::PushLiteral(), SGraphPinNum< NumericType >::SetNumericValue(), FInBunch::ToString(), FOutBunch::ToString(), UE::Math::TIntPoint< IntType >::ToString(), USTRUCT(), USTRUCT(), and USTRUCT().
LexToString() [2/2]
METASOUNDFRONTEND_API const TCHAR * LexToString (EMetasoundFrontendVertexAccessType InVertexAccess)
UENUM()
UENUM ()
Definition at line 128 of file MetasoundFrontendDocument.h.
References Unset, and Value.
USTRUCT()
USTRUCT ()
Struct for configuring a node.
You can inherit from this and include data passed to the operator and/or data used to determine an override of the node's interface.
In order for node configuration data to be editable in the details panel, UProperties on your substruct should be marked with EditAnywhere.
Optional custom details customizations can be registered via IMetasoundEditorModule::RegisterCustomNodeConfigurationDetailsCustomization
Example: USTRUCT() struct FMetaSoundExperimentalExampleNodeConfiguration : public FMetaSoundFrontendNodeConfiguration { GENERATED_BODY()
UPROPERTY(EditAnywhere, Category = General, meta = (ClampMin = "1", ClampMax = "1000")) uint32 NumInputs;
virtual TInstancedStruct<FMetasoundFrontendClassInterface> OverrideDefaultInterface(const FMetasoundFrontendClass& InNodeClass) const;
virtual TSharedPtr<const Metasound::IOperatorData> GetOperatorData() const override; }
Provide any data needed by IOperators instantiated from this node.
Definition at line 229 of file MetasoundFrontendDocument.h.
References FLinearColor::Black, Color, Depth, GENERATED_BODY, Position, TSequenceHistory< HistorySize >::Size, UPROPERTY, and UE::Math::TIntVector2< int32 >::ZeroValue.