Unreal Engine 5.6 C++ API: Runtime/Core/Public/Templates/Models.h File Reference
Models.h File Reference
#include "Templates/Identity.h"
Data Structures
struct TModels< Concept, Args >
Traits class which does concept checking.
Namespaces
namespace UE
Utility functions for applying transformations to meshes.
namespace UE::Core
namespace UE::Core::Private
TAdderRef and TAdderReserverRef are type-erasing adapters that allow a function to add to (and reserve) a container without the function knowing about the specific type of the container.
Functions
template<typename Concept, typename... Ts>
static char(& UE::Core::Private::ModelsResolve (...))[1]
template<typename Concept, typename... Ts>
static char(& UE::Core::Private::ModelsResolve (decltype(&Concept::template Requires< Ts... >) *))[2]
template<typename Concept, typename... Args>
auto Refines () -> int(&)[!!TModels_V< Concept, Args... > *2 - 1]
Helper function which can be used as an expression in a concept to refine ('inherit') another concept.
Variables
template<typename Concept, typename... Args>
constexpr bool TModels_V = sizeof(UE::Core::Private::ModelsResolve<Concept, Args...>(0)) == 2
Trait which does concept checking.
Function Documentation
Refines()
template<typename Concept, typename... Args> auto Refines () -> int(&)[!!TModels_V< Concept, Args... > *2 - 1]
Helper function which can be used as an expression in a concept to refine ('inherit') another concept.
It should be used as expression-based variant of the TModels_V trait. If the arguments model the given concept, Refines<Concept, Args...> is a valid expression, otherwise it is not.
See the CCopyablePointer example below.
References TModels_V.
Variable Documentation
TModels_V
template<typename Concept, typename... Args> bool TModels_V = sizeof(UE::Core::Private::ModelsResolve<Concept, Args...>(0)) == 2 constexpr
Trait which does concept checking.
Definition at line 57 of file Models.h.
Referenced by FHashBuilder::Append(), UE::SequenceNavigator::TNavigationToolItemInherits< FNavigationToolColorColumn, FNavigationToolColumn >::Cast(), TSequencerChannelInterfaceCommon< ChannelType >::CreateCurveEditorModel_Raw(), TSequencerChannelInterfaceCommon< ChannelType >::CreateKeyEditor_Raw(), TGraphTask< TTask >::ExecuteTask(), MetasoundArrayHashPrivate::GetArrayContentHashGuid(), UScriptStruct::TCppStructOps< CPPSTRUCT >::GetCapabilities(), TPropertyTypeFundamentals< InTCppType >::GetComputedFlagsPropertyFlags(), UScriptStruct::TCppStructOps< CPPSTRUCT >::GetStructTypeHash(), UE::SequenceNavigator::TNavigationToolItemType< T, bool >::GetTypeId(), UStruct::IsChildOf(), FAsyncTask< FAsyncSoundWavePCMWriteWorker >::MarkAsCanceled(), TFutureBase< ResultType >::Next(), Refines(), UE::Anim::AttributeTypes::RegisterType(), UScriptStruct::TCppStructOps< CPPSTRUCT >::Serialize(), UScriptStruct::TCppStructOps< CPPSTRUCT >::Serialize(), TOctree2< FVolumeLightingSample, FLightVolumeOctreeSemantics >::SetOctreeSemanticsElementId(), TOctree_DEPRECATED< ElementType, OctreeSemantics >::SetOctreeSemanticsElementId(), TSoftObjectPtr(), and UE::MovieScene::TEntityGroupingHandlerImpl< GroupingPolicy, TIntegerSequence< int, ComponentIndices... >, ComponentTypes... >::VisitLinkedEntities().