Unreal Engine 5.6 C++ API: S:/Development/U_E/UE_5.6/Engine/Plugins/Experimental/ChaosModularVehicle/Source/ChaosModularVehicleEngine/Public/ChaosModularVehicle/ModularVehicleBaseComponent.h File Reference
ModularVehicleBaseComponent.h File Reference
#include "ChaosModularVehicle/ChaosSimModuleManagerAsyncCallback.h"
#include "SimModule/SimModulesInclude.h"
#include "SimModule/ModuleInput.h"
#include "ChaosModularVehicle/InputProducer.h"
#include "ChaosModularVehicle/ModularVehicleSimulationCU.h"
#include "Chaos/ParticleHandleFwd.h"
#include "Components/PrimitiveComponent.h"
#include "Components/ActorComponent.h"
#include "Containers/Map.h"
#include "UObject/ObjectKey.h"
#include "ModularVehicleBaseComponent.generated.h"
Namespaces
namespace Chaos
Macros
#define UE_API CHAOSMODULARVEHICLEENGINE_API
Functions
DECLARE_LOG_CATEGORY_EXTERN (LogModularBase, Log, All)
UCLASS () =Physics
Since hair-card generation can be controlled external to this plugin, this
provides a way for those external generators a way to store their own generation data along with the groom/cards-entry.
USTRUCT () struct FConstructionData
Additional replicated state.
Variables
hidecategories
meta = (BlueprintSpawnableComponent)
Macro Definition Documentation
UE_API
#define UE_API CHAOSMODULARVEHICLEENGINE_API
Definition at line 18 of file ModularVehicleBaseComponent.h.
Function Documentation
DECLARE_LOG_CATEGORY_EXTERN()
DECLARE_LOG_CATEGORY_EXTERN (LogModularBase , Log , All)
References All, and Log.
UCLASS()
UCLASS () =Physics inline
Since hair-card generation can be controlled external to this plugin, this
provides a way for those external generators a way to store their own generation data along with the groom/cards-entry.
Base class for storing a list of gameplay tags as an ini list.
Network physics manager to initialize data required for rewind/resim.
Sound Submix class meant for sending soundfield-encoded audio to an external endpoint, such as a hardware binaural renderer that supports ambisonics.
Sound Submix class meant for sending audio to an external endpoint, such as controller haptics or an additional audio device.
NavMovementComponent defines base functionality for MovementComponents that move any 'agent' that may be involved in AI pathfinding.
Provides linear resistance to a trigger while it is being pressed between a start and end value.
Sets simple trigger feedback.
A property that effect the triggers on a gamepad.
A property that can be used to change the color of an input device's light over time with a curve.
Set the color of an Input Device to a static color.
CharacterMovementComponent handles movement logic for the associated Character owner.
A fake connection that will absorb traffic and auto ack every packet.
Utility class for engine types.
Imported spreadsheet table.
Implements the settings for garbage collection.
A placeable actor that represents a participating media material around a planet, e.g.
A geometry layer within the stereo rendered viewport.
A placeable actor that represents a planet atmosphere material and simulates sky and light scattering within it.
A placeable actor that represents a heterogeneous volume.
DEPRECATED Replace with UBTTask_Wait that now accepts blackboard keys Wait task node.
RunBehavior task allows pushing subtrees on execution stack.
Settings for how developers interact with assets.
Configure per-project performance settings for the Editor.
Configure per-project settings for the Level Editor.
Class used to define settings for Smart Object navigation and collision validation.
Base class for space partitioning structure that can be used to store smart object locations.
All configuration UObjects should inherit from this class.
Selected-Attribute settings Attribute Paint Tool.
These are properties that do not get enabled/disabled based on the action.
Helper struct to wrap basic functionalities to store the index of a slot in a SmartObject definition
It is possible to specify two set of validation parameters. The one labeled "entry" is used for validating entry locations and other general collision validation. A separate set can be defined for checking exit locations. This allows the exit location checking to be relaxed. E.g. we might not allow to enter the SO on water area, but it is fine to exit on water. The values of the CDO are used, the users are expected to derive from this class to create custom settings. Describes how Smart Object or slot was changed. Struct describing a change in Smart Object or Slot.
Stored in default config, per-project
Subtree asset can't be changed in runtime!
This limitation is caused by support for subtree's root level decorators, which are injected into parent tree, and structure of running tree cannot be modified in runtime (see: BTNode: ExecutionIndex, MemoryOffset)
Use RunBehaviorDynamic task for subtrees that need to be changed in runtime.
Wait for the time specified by a Blackboard key when executed.
See also
https://docs.unrealengine.com/en-US/Engine/Actors/FogEffects/SkyAtmosphere/index.html
clouds.
See also
TODO address to the documentation.
Handle to a particular row in a table
Type of a socket on a scene component.
Useful for testing scaling. Use net.SimulateConnections command to add at runtime.
It supports various movement modes including: walking, falling, swimming, flying, custom.
Movement is affected primarily by current Velocity and Acceleration. Acceleration is updated each frame based on the input vector accumulated thus far (see UPawnMovementComponent::GetPendingInputVector()).
Networking is fully implemented, with server-client correction and prediction included.
See also
ACharacter, UPawnMovementComponent
https://docs.unrealengine.com/latest/INT/Gameplay/Framework/Pawn/Character/
This will NOT reset the device color when the property is done evaluating. You can think of this as a "One Shot" effect, where you set the device property color.
NOTE: This property has platform specific implementations and may behave differently per platform. See the docs for more details on each platform. Data required for setting the Input Device Color
NOTE: This property has platform specific implementations and may behave differently per platform. See the docs for more details on each platform.
Base network physics data that will be used by physics
This is used for both the central list and additional lists Base class for storing a list of restricted gameplay tags as an ini list. This is used for both the central list and additional lists
Average of the minimum and maximum principal curvatures
Maximum principal curvature
Minimum principal curvature
Product of the minimum and maximum principal curvatures
Definition at line 172 of file BakeMeshAttributeToolCommon.h.
References Gaussian, Max, UENUM, and UMETA.
USTRUCT()
USTRUCT ()
Additional replicated state.
Definition at line 30 of file ModularVehicleBaseComponent.h.
References GENERATED_BODY, and Guid.
Variable Documentation
hidecategories
hidecategories
Definition at line 108 of file ModularVehicleBaseComponent.h.
Referenced by CompileShadingModelBlendFunction(), CompileSubstrateBlendFunction(), DECLARE_DWORD_COUNTER_STAT_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_MULTICAST_DELEGATE(), ENUM_CLASS_FLAGS(), ENUM_CLASS_FLAGS(), operator!=(), UCLASS(), UCLASS(), and FScopedSkeletalMeshRenderData::USkeletalMesh.
meta
meta = (BlueprintSpawnableComponent)
Definition at line 108 of file ModularVehicleBaseComponent.h.
Referenced by CompileShadingModelBlendFunction(), DECLARE_DELEGATE_RetVal_OneParam(), DECLARE_DELEGATE_ThreeParams(), DECLARE_DWORD_COUNTER_STAT_EXTERN(), DECLARE_DYNAMIC_DELEGATE(), DECLARE_DYNAMIC_DELEGATE_RetVal_OneParam(), DECLARE_DYNAMIC_DELEGATE_RetVal_TwoParams(), DECLARE_DYNAMIC_DELEGATE_ThreeParams(), DECLARE_DYNAMIC_DELEGATE_TwoParams(), DECLARE_DYNAMIC_MULTICAST_DELEGATE(), DECLARE_DYNAMIC_MULTICAST_DELEGATE(), DECLARE_DYNAMIC_MULTICAST_DELEGATE(), DECLARE_DYNAMIC_MULTICAST_DELEGATE(), DECLARE_DYNAMIC_MULTICAST_DELEGATE(), DECLARE_DYNAMIC_MULTICAST_DELEGATE(), DECLARE_DYNAMIC_MULTICAST_DELEGATE(), DECLARE_DYNAMIC_MULTICAST_DELEGATE(), DECLARE_DYNAMIC_MULTICAST_DELEGATE(), DECLARE_DYNAMIC_MULTICAST_DELEGATE(), DECLARE_DYNAMIC_MULTICAST_DELEGATE(), DECLARE_DYNAMIC_MULTICAST_DELEGATE(), DECLARE_DYNAMIC_MULTICAST_DELEGATE(), DECLARE_DYNAMIC_MULTICAST_DELEGATE(), DECLARE_DYNAMIC_MULTICAST_DELEGATE(), DECLARE_DYNAMIC_MULTICAST_DELEGATE(), DECLARE_DYNAMIC_MULTICAST_DELEGATE(), DECLARE_DYNAMIC_MULTICAST_DELEGATE(), DECLARE_DYNAMIC_MULTICAST_DELEGATE(), DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(), DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(), DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(), DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(), DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(), DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(), DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(), DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(), DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(), DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(), DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(), DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(), DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(), DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(), DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(), DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(), DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(), DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(), DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(), DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(), DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(), DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(), DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(), DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(), DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(), DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(), DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(), DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(), DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(), DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(), DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(), DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(), DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(), DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(), DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(), DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(), DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_MULTICAST_DELEGATE_OneParam(), DECLARE_MULTICAST_DELEGATE_OneParam(), DECLARE_MULTICAST_DELEGATE_OneParam(), DECLARE_MULTICAST_DELEGATE_OneParam(), DECLARE_MULTICAST_DELEGATE_OneParam(), DECLARE_MULTICAST_DELEGATE_OneParam(), ENUM_CLASS_FLAGS(), ENUM_CLASS_FLAGS(), ENUM_CLASS_FLAGS(), ENUM_CLASS_FLAGS(), ENUM_CLASS_FLAGS(), ENUM_RANGE_BY_COUNT(), IGameplayCueInterface::GameplayCueDefaultHandler(), IMovieSceneBoundObjectProxy::GENERATED_BODY(), ABrush::GENERATED_UCLASS_BODY(), ALevelStreamingVolume::GENERATED_UCLASS_BODY(), UAbilitySystemTestAttributeSet::GENERATED_UCLASS_BODY(), UAIBlueprintHelperLibrary::GENERATED_UCLASS_BODY(), UAnimCurveCompressionCodec_CompressedRichCurve::GENERATED_UCLASS_BODY(), UAnimCurveCompressionCodec_UniformlySampled::GENERATED_UCLASS_BODY(), UAnimNotifyState_TimedParticleEffect::GENERATED_UCLASS_BODY(), UAnimSequence::GENERATED_UCLASS_BODY(), UBlueprintGameplayTagLibrary::GENERATED_UCLASS_BODY(), UBoxReflectionCaptureComponent::GENERATED_UCLASS_BODY(), UBTDecorator_Loop::GENERATED_UCLASS_BODY(), UEnvQueryGenerator_ActorsOfClass::GENERATED_UCLASS_BODY(), UEnvQueryGenerator_SimpleGrid::GENERATED_UCLASS_BODY(), UFbxStaticMeshImportData::GENERATED_UCLASS_BODY(), UKismetNodeHelperLibrary::GENERATED_UCLASS_BODY(), UKismetStringTableLibrary::GENERATED_UCLASS_BODY(), ULandscapeSplineSegment::GENERATED_UCLASS_BODY(), ULightComponent::GENERATED_UCLASS_BODY(), ULODSyncComponent::GENERATED_UCLASS_BODY(), UParticleModuleColor::GENERATED_UCLASS_BODY(), UPlaneReflectionCaptureComponent::GENERATED_UCLASS_BODY(), USphereReflectionCaptureComponent::GENERATED_UCLASS_BODY(), USpotLightComponent::GENERATED_UCLASS_BODY(), UUVEditorChannelEditTargetProperties::GetAssetNames(), USoundWave::GetLoadingBehavior(), Metasound::TDataReferenceTypeInfo< HarmonixMetasound::FMidiStepSequenceAsset >::GetTypeDisplayText(), GetTypeHash(), operator!=(), operator<<(), UEditorPerformanceProjectSettings::PostEditChangeProperty(), UStreamingSettings::PostInitProperties(), ADocumentationActor::PostLoad(), PREDECLARE_GEOMETRY(), PREDECLARE_GEOMETRY(), PREDECLARE_GEOMETRY(), PREDECLARE_USE_GEOMETRY_CLASS(), PREDECLARE_USE_GEOMETRY_CLASS(), ALODActor::PreSave(), UCLASS(), UCLASS(), UCLASS(), UCLASS(), UCLASS(), ALevelSequenceActor::UE_DEPRECATED(), IAnimationDataController::UE_DEPRECATED(), IAnimationDataController::UE_DEPRECATED(), IAnimationDataController::UE_DEPRECATED(), IAnimationDataController::UE_DEPRECATED(), IAnimationDataController::UE_DEPRECATED(), IAnimationDataController::UE_DEPRECATED(), IDisplayClusterBlueprintAPI::UE_DEPRECATED(), IDisplayClusterBlueprintAPI::UE_DEPRECATED(), IDisplayClusterBlueprintAPI::UE_DEPRECATED(), IDisplayClusterBlueprintAPI::UE_DEPRECATED(), IDisplayClusterBlueprintAPI::UE_DEPRECATED(), IDisplayClusterBlueprintAPI::UE_DEPRECATED(), IDisplayClusterBlueprintAPI::UE_DEPRECATED(), IDisplayClusterBlueprintAPI::UE_DEPRECATED(), IDisplayClusterBlueprintAPI::UE_DEPRECATED(), IDisplayClusterBlueprintAPI::UE_DEPRECATED(), IDisplayClusterBlueprintAPI::UE_DEPRECATED(), IDisplayClusterBlueprintAPI::UE_DEPRECATED(), IDisplayClusterBlueprintAPI::UE_DEPRECATED(), IDisplayClusterBlueprintAPI::UE_DEPRECATED(), IDisplayClusterBlueprintAPI::UE_DEPRECATED(), IVPInteraction::UE_DEPRECATED(), IVPInteraction::UE_DEPRECATED(), UAbilitySystemBlueprintLibrary::UE_DEPRECATED(), UAbilitySystemBlueprintLibrary::UE_DEPRECATED(), UAbilitySystemBlueprintLibrary::UE_DEPRECATED(), UAbilitySystemBlueprintLibrary::UE_DEPRECATED(), UAISenseConfig_Hearing::UE_DEPRECATED(), UAnimDataModel::UE_DEPRECATED(), UBaseDynamicMeshComponent::UE_DEPRECATED(), UBaseDynamicMeshComponent::UE_DEPRECATED(), UBaseDynamicMeshComponent::UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UGroomAsset::UE_DEPRECATED(), UGroomAsset::UE_DEPRECATED(), UGroomAsset::UE_DEPRECATED(), UGroomAsset::UE_DEPRECATED(), UGroomAsset::UE_DEPRECATED(), UGroomAsset::UE_DEPRECATED(), UGroomAsset::UE_DEPRECATED(), UGroomAsset::UE_DEPRECATED(), UGroomAsset::UE_DEPRECATED(), UGroomAsset::UE_DEPRECATED(), UGroomAsset::UE_DEPRECATED(), UInstancedStaticMeshComponent::UE_DEPRECATED(), UPhysicsHandleComponent::UE_DEPRECATED(), URendererSettings::UE_DEPRECATED(), UVPScoutingSubsystem::UE_DEPRECATED(), UVPScoutingSubsystem::UE_DEPRECATED(), UVPScoutingSubsystem::UE_DEPRECATED(), UVPScoutingSubsystem::UE_DEPRECATED(), UVPScoutingSubsystem::UE_DEPRECATED(), UVPScoutingSubsystem::UE_DEPRECATED(), UVPScoutingSubsystem::UE_DEPRECATED(), UVPScoutingSubsystem::UE_DEPRECATED(), UVPScoutingSubsystem::UE_DEPRECATED(), UVPScoutingSubsystem::UE_DEPRECATED(), UVPScoutingSubsystem::UE_DEPRECATED(), UVPScoutingSubsystem::UE_DEPRECATED(), UVPScoutingSubsystem::UE_DEPRECATED(), UVPScoutingSubsystem::UE_DEPRECATED(), UVPScoutingSubsystem::UE_DEPRECATED(), UVPScoutingSubsystem::UE_DEPRECATED(), UVPScoutingSubsystem::UE_DEPRECATED(), UVPScoutingSubsystem::UE_DEPRECATED(), UVPScoutingSubsystem::UE_DEPRECATED(), UVPScoutingSubsystem::UE_DEPRECATED(), UVPScoutingSubsystem::UE_DEPRECATED(), UVPScoutingSubsystem::UE_DEPRECATED(), UVPScoutingSubsystem::UE_DEPRECATED(), UVPScoutingSubsystem::UE_DEPRECATED(), UVPScoutingSubsystem::UE_DEPRECATED(), UVPScoutingSubsystem::UE_DEPRECATED(), UVPScoutingSubsystem::UE_DEPRECATED(), UVPScoutingSubsystem::UE_DEPRECATED(), UVPScoutingSubsystem::UE_DEPRECATED(), UVPScoutingSubsystem::UE_DEPRECATED(), UVPScoutingSubsystem::UE_DEPRECATED(), UVPScoutingSubsystem::UE_DEPRECATED(), UVPScoutingSubsystem::UE_DEPRECATED(), UVPScoutingSubsystem::UE_DEPRECATED(), UVPScoutingSubsystemGestureManagerBase::UE_DEPRECATED(), UVPScoutingSubsystemGestureManagerBase::UE_DEPRECATED(), UVPScoutingSubsystemGestureManagerBase::UE_DEPRECATED(), UENUM(), UENUM(), UENUM(), AAmbientSound::UFUNCTION(), AAmbientSound::UFUNCTION(), AAmbientSound::UFUNCTION(), AAmbientSound::UFUNCTION(), AAmbientSound::UFUNCTION(), ACharacter::UFUNCTION(), ACharacter::UFUNCTION(), ACharacter::UFUNCTION(), ACharacter::UFUNCTION(), ACharacter::UFUNCTION(), ACharacter::UFUNCTION(), ACharacter::UFUNCTION(), ACharacter::UFUNCTION(), ACharacter::UFUNCTION(), AController::UFUNCTION(), AController::UFUNCTION(), AController::UFUNCTION(), AController::UFUNCTION(), AController::UFUNCTION(), AController::UFUNCTION(), AController::UFUNCTION(), AController::UFUNCTION(), ADecalActor::UFUNCTION(), ADecalActor::UFUNCTION(), ADecalActor::UFUNCTION(), AEmitter::UFUNCTION(), AEmitter::UFUNCTION(), AEmitter::UFUNCTION(), AEmitter::UFUNCTION(), AEmitter::UFUNCTION(), AEmitter::UFUNCTION(), AEmitter::UFUNCTION(), AEmitter::UFUNCTION(), AEmitter::UFUNCTION(), AEmitter::UFUNCTION(), ALevelScriptActor::UFUNCTION(), ANavLinkProxy::UFUNCTION(), ARadialForceActor::UFUNCTION(), ARadialForceActor::UFUNCTION(), ARadialForceActor::UFUNCTION(), ARadialForceActor::UFUNCTION(), IGameplayTagAssetInterface::UFUNCTION(), IInterface_AssetUserData::UFUNCTION(), IMovieSceneEasingFunction::UFUNCTION(), IMovieSceneTransformOrigin::UFUNCTION(), ISoundEffectPresetWidgetInterface::UFUNCTION(), IWorldPartitionDestructibleInHLODInterface::UFUNCTION(), UAbilitySystemBlueprintLibrary::UFUNCTION(), UAbilitySystemBlueprintLibrary::UFUNCTION(), UAbilitySystemBlueprintLibrary::UFUNCTION(), UAbilitySystemBlueprintLibrary::UFUNCTION(), UAbilitySystemBlueprintLibrary::UFUNCTION(), UAbilitySystemBlueprintLibrary::UFUNCTION(), UAbilitySystemBlueprintLibrary::UFUNCTION(), UAbilitySystemBlueprintLibrary::UFUNCTION(), UAbilitySystemBlueprintLibrary::UFUNCTION(), UAbilitySystemBlueprintLibrary::UFUNCTION(), UAbilitySystemBlueprintLibrary::UFUNCTION(), UAbilitySystemBlueprintLibrary::UFUNCTION(), UActorComponent::UFUNCTION(), UActorComponent::UFUNCTION(), UActorComponent::UFUNCTION(), UActorComponent::UFUNCTION(), UActorComponent::UFUNCTION(), UActorComponent::UFUNCTION(), UActorComponent::UFUNCTION(), UActorComponent::UFUNCTION(), UActorComponent::UFUNCTION(), UActorComponent::UFUNCTION(), UActorComponent::UFUNCTION(), UActorComponent::UFUNCTION(), UActorComponent::UFUNCTION(), UActorComponent::UFUNCTION(), UActorComponent::UFUNCTION(), UActorComponent::UFUNCTION(), UAIBlueprintHelperLibrary::UFUNCTION(), UAIBlueprintHelperLibrary::UFUNCTION(), UAIBlueprintHelperLibrary::UFUNCTION(), UAIBlueprintHelperLibrary::UFUNCTION(), UAIBlueprintHelperLibrary::UFUNCTION(), UAIBlueprintHelperLibrary::UFUNCTION(), UAIBlueprintHelperLibrary::UFUNCTION(), UAIBlueprintHelperLibrary::UFUNCTION(), UAIBlueprintHelperLibrary::UFUNCTION(), UAIBlueprintHelperLibrary::UFUNCTION(), UAnimNotifyLibrary::UFUNCTION(), UAnimNotifyLibrary::UFUNCTION(), UAnimNotifyLibrary::UFUNCTION(), UAnimNotifyLibrary::UFUNCTION(), UAnimNotifyLibrary::UFUNCTION(), UAnimNotifyState::UFUNCTION(), UAnimNotifyState::UFUNCTION(), UAnimNotifyState::UFUNCTION(), UBlueprintGameplayTagLibrary::UFUNCTION(), UBlueprintGameplayTagLibrary::UFUNCTION(), UBlueprintGameplayTagLibrary::UFUNCTION(), UBlueprintGameplayTagLibrary::UFUNCTION(), UBlueprintGameplayTagLibrary::UFUNCTION(), UBlueprintGameplayTagLibrary::UFUNCTION(), UBlueprintGameplayTagLibrary::UFUNCTION(), UBlueprintGameplayTagLibrary::UFUNCTION(), UBlueprintGameplayTagLibrary::UFUNCTION(), UBlueprintGameplayTagLibrary::UFUNCTION(), UBlueprintGameplayTagLibrary::UFUNCTION(), UBlueprintGameplayTagLibrary::UFUNCTION(), UBlueprintGameplayTagLibrary::UFUNCTION(), UBlueprintGameplayTagLibrary::UFUNCTION(), UBlueprintGameplayTagLibrary::UFUNCTION(), UBlueprintGameplayTagLibrary::UFUNCTION(), UBlueprintGameplayTagLibrary::UFUNCTION(), UBlueprintGameplayTagLibrary::UFUNCTION(), UBlueprintGameplayTagLibrary::UFUNCTION(), UBlueprintGameplayTagLibrary::UFUNCTION(), UBlueprintGameplayTagLibrary::UFUNCTION(), UBlueprintGameplayTagLibrary::UFUNCTION(), UBlueprintGameplayTagLibrary::UFUNCTION(), UBlueprintGameplayTagLibrary::UFUNCTION(), UBlueprintGameplayTagLibrary::UFUNCTION(), UBlueprintGameplayTagLibrary::UFUNCTION(), UBlueprintGameplayTagLibrary::UFUNCTION(), UBlueprintGameplayTagLibrary::UFUNCTION(), UBlueprintGameplayTagLibrary::UFUNCTION(), UBlueprintGameplayTagLibrary::UFUNCTION(), UBlueprintGameplayTagLibrary::UFUNCTION(), UBlueprintGameplayTagLibrary::UFUNCTION(), UBlueprintMapLibrary::UFUNCTION(), UBlueprintMapLibrary::UFUNCTION(), UBlueprintSetLibrary::UFUNCTION(), UBlueprintSetLibrary::UFUNCTION(), UBoundsCopyComponent::UFUNCTION(), UBoundsCopyComponent::UFUNCTION(), UFUNCTION(), UGameplayCueNotify_Static::UFUNCTION(), UInputComponent::UFUNCTION(), UInputComponent::UFUNCTION(), UInputComponent::UFUNCTION(), UInputComponent::UFUNCTION(), UInputComponent::UFUNCTION(), UInputComponent::UFUNCTION(), UInputComponent::UFUNCTION(), UInputComponent::UFUNCTION(), UKismetArrayLibrary::UFUNCTION(), UKismetArrayLibrary::UFUNCTION(), UKismetArrayLibrary::UFUNCTION(), UKismetArrayLibrary::UFUNCTION(), UKismetArrayLibrary::UFUNCTION(), UKismetArrayLibrary::UFUNCTION(), UKismetArrayLibrary::UFUNCTION(), UKismetArrayLibrary::UFUNCTION(), UKismetInputLibrary::UFUNCTION(), UKismetInputLibrary::UFUNCTION(), UKismetInternationalizationLibrary::UFUNCTION(), UKismetInternationalizationLibrary::UFUNCTION(), UKismetInternationalizationLibrary::UFUNCTION(), UKismetInternationalizationLibrary::UFUNCTION(), UKismetInternationalizationLibrary::UFUNCTION(), UKismetInternationalizationLibrary::UFUNCTION(), UKismetNodeHelperLibrary::UFUNCTION(), UKismetNodeHelperLibrary::UFUNCTION(), UKismetNodeHelperLibrary::UFUNCTION(), UKismetNodeHelperLibrary::UFUNCTION(), UKismetNodeHelperLibrary::UFUNCTION(), UKismetNodeHelperLibrary::UFUNCTION(), UKismetNodeHelperLibrary::UFUNCTION(), UKismetNodeHelperLibrary::UFUNCTION(), UKismetNodeHelperLibrary::UFUNCTION(), UKismetNodeHelperLibrary::UFUNCTION(), UKismetNodeHelperLibrary::UFUNCTION(), UKismetNodeHelperLibrary::UFUNCTION(), UKismetStringLibrary::UFUNCTION(), UKismetStringLibrary::UFUNCTION(), UKismetStringLibrary::UFUNCTION(), UKismetStringLibrary::UFUNCTION(), UKismetStringLibrary::UFUNCTION(), UKismetStringTableLibrary::UFUNCTION(), UKismetStringTableLibrary::UFUNCTION(), UKismetStringTableLibrary::UFUNCTION(), UKismetStringTableLibrary::UFUNCTION(), UKismetStringTableLibrary::UFUNCTION(), UKismetStringTableLibrary::UFUNCTION(), UKismetStringTableLibrary::UFUNCTION(), ULightComponent::UFUNCTION(), ULightComponent::UFUNCTION(), ULightComponent::UFUNCTION(), ULightComponentBase::UFUNCTION(), UMeshComponent::UFUNCTION(), UMovieSceneCondition::UFUNCTION(), UMovieSceneCondition::UFUNCTION(), UMovieSceneCondition::UFUNCTION(), UPhysicalAnimationComponent::UFUNCTION(), UPhysicalAnimationComponent::UFUNCTION(), UPhysicalAnimationComponent::UFUNCTION(), UPhysicalAnimationComponent::UFUNCTION(), UPhysicsConstraintComponent::UFUNCTION(), UPhysicsConstraintComponent::UFUNCTION(), UVOIPTalker::UFUNCTION(), UINTERFACE(), UActorComponent::UninitializeComponent(), AAudioVolume::UPROPERTY(), AAudioVolume::UPROPERTY(), AAudioVolume::UPROPERTY(), AAudioVolume::UPROPERTY(), ABrush::UPROPERTY(), ACameraActor::UPROPERTY(), ACameraActor::UPROPERTY(), ACharacter::UPROPERTY(), ACharacter::UPROPERTY(), ACharacter::UPROPERTY(), AEmitter::UPROPERTY(), AExponentialHeightFog::UPROPERTY(), ALevelSequenceActor::UPROPERTY(), ALevelSequenceActor::UPROPERTY(), ALevelSequenceActor::UPROPERTY(), ALevelSequenceActor::UPROPERTY(), ALevelSequenceMediaController::UPROPERTY(), ASceneCapture::UPROPERTY(), ASkeletalMeshActor::UPROPERTY(), ASkyLight::UPROPERTY(), AVPBookmarkActor::UPROPERTY(), AVPBookmarkActor::UPROPERTY(), AVPBookmarkActor::UPROPERTY(), AVRTool::UPROPERTY(), AVRTool::UPROPERTY(), AWorldDataLayers::UPROPERTY(), AWorldPartitionMiniMap::UPROPERTY(), UAbilitySystemTestAttributeSet::UPROPERTY(), UAISenseConfig_Hearing::UPROPERTY(), UAISenseConfig_Sight::UPROPERTY(), UAISenseConfig_Sight::UPROPERTY(), UAISenseConfig_Sight::UPROPERTY(), UAISenseConfig_Sight::UPROPERTY(), UAISenseConfig_Sight::UPROPERTY(), UAISenseConfig_Sight::UPROPERTY(), UAnimDataModel::UPROPERTY(), UAnimDataModel::UPROPERTY(), UAnimDataModel::UPROPERTY(), UAnimDataModel::UPROPERTY(), UAnimDataModel::UPROPERTY(), UAnimDataModel::UPROPERTY(), UAnimDataModel::UPROPERTY(), UAnimNotify_PlayParticleEffect::UPROPERTY(), UAnimNotify_PlaySound::UPROPERTY(), UAnimNotify_PlaySound::UPROPERTY(), UAnimNotify_PlaySound::UPROPERTY(), UAnimNotify_PlaySound::UPROPERTY(), UAnimNotifyState_TimedParticleEffect::UPROPERTY(), UAnimNotifyState_TimedParticleEffect::UPROPERTY(), UAnimNotifyState_TimedParticleEffect::UPROPERTY(), UAnimNotifyState_TimedParticleEffect::UPROPERTY(), UAnimSequence::UPROPERTY(), UAnimSequence::UPROPERTY(), UAnimSequence::UPROPERTY(), UAnimSequence::UPROPERTY(), UAnimSequence::UPROPERTY(), UAssetManagerSettings::UPROPERTY(), UAssetManagerSettings::UPROPERTY(), UAssetTagsGameplayEffectComponent::UPROPERTY(), UBaseDynamicMeshComponent::UPROPERTY(), UBaseDynamicMeshComponent::UPROPERTY(), UBaseDynamicMeshComponent::UPROPERTY(), UBaseDynamicMeshComponent::UPROPERTY(), UBaseDynamicMeshComponent::UPROPERTY(), UBaseDynamicMeshComponent::UPROPERTY(), UBaseDynamicMeshComponent::UPROPERTY(), UBlackboardKeyType_Class::UPROPERTY(), UBlackboardKeyType_Object::UPROPERTY(), UBlackboardKeyType_Rotator::UPROPERTY(), UBlackboardKeyType_Vector::UPROPERTY(), UBoundsCopyComponent::UPROPERTY(), UBoundsCopyComponent::UPROPERTY(), UBoundsCopyComponent::UPROPERTY(), UBTDecorator_Blackboard::UPROPERTY(), UBTDecorator_Blackboard::UPROPERTY(), UBTDecorator_Blackboard::UPROPERTY(), UBTDecorator_Blackboard::UPROPERTY(), UBTDecorator_Loop::UPROPERTY(), UBTDecorator_TagCooldown::UPROPERTY(), UBTDecorator_TagCooldown::UPROPERTY(), UBTDecorator_TagCooldown::UPROPERTY(), UCurveLinearColor::UPROPERTY(), UCurveLinearColor::UPROPERTY(), UCurveLinearColor::UPROPERTY(), UCurveLinearColor::UPROPERTY(), UCurveLinearColor::UPROPERTY(), UCurveLinearColor::UPROPERTY(), UCurveLinearColor::UPROPERTY(), UDataLayerInstancePrivate::UPROPERTY(), UDataLayerInstanceWithAsset::UPROPERTY(), UDeprecatedDataLayerInstance::UPROPERTY(), UEditorPerformanceProjectSettings::UPROPERTY(), UEditorPerformanceProjectSettings::UPROPERTY(), UEditorPerformanceProjectSettings::UPROPERTY(), UEditorPerformanceProjectSettings::UPROPERTY(), UEditorPerformanceProjectSettings::UPROPERTY(), UEditorPerformanceProjectSettings::UPROPERTY(), UEditorProjectAppearanceSettings::UPROPERTY(), UEditorProjectAppearanceSettings::UPROPERTY(), UEditorProjectAppearanceSettings::UPROPERTY(), UEditorProjectAppearanceSettings::UPROPERTY(), UEditorProjectAppearanceSettings::UPROPERTY(), UEditorProjectAppearanceSettings::UPROPERTY(), UEditorProjectAppearanceSettings::UPROPERTY(), UEditorProjectAppearanceSettings::UPROPERTY(), UEditorProjectAppearanceSettings::UPROPERTY(), UEditorProjectAppearanceSettings::UPROPERTY(), UEditorProjectAppearanceSettings::UPROPERTY(), UEditorProjectAppearanceSettings::UPROPERTY(), UEditorProjectAppearanceSettings::UPROPERTY(), UEditorProjectAppearanceSettings::UPROPERTY(), UEditorProjectAppearanceSettings::UPROPERTY(), UEditorProjectAssetSettings::UPROPERTY(), UEnvQueryGenerator_Donut::UPROPERTY(), UEnvQueryGenerator_Donut::UPROPERTY(), UEnvQueryGenerator_OnCircle::UPROPERTY(), UEnvQueryGenerator_OnCircle::UPROPERTY(), UEnvQueryGenerator_OnCircle::UPROPERTY(), UEnvQueryGenerator_OnCircle::UPROPERTY(), UEnvQueryInstanceBlueprintWrapper::UPROPERTY(), UFbxImportUI::UPROPERTY(), UFbxImportUI::UPROPERTY(), UFbxImportUI::UPROPERTY(), UFbxImportUI::UPROPERTY(), UFbxImportUI::UPROPERTY(), UFbxImportUI::UPROPERTY(), UFbxImportUI::UPROPERTY(), UFbxImportUI::UPROPERTY(), UFbxImportUI::UPROPERTY(), UFbxImportUI::UPROPERTY(), UFbxImportUI::UPROPERTY(), UFbxImportUI::UPROPERTY(), UFbxImportUI::UPROPERTY(), UFbxImportUI::UPROPERTY(), UFbxImportUI::UPROPERTY(), UFbxImportUI::UPROPERTY(), UFbxImportUI::UPROPERTY(), UFbxImportUI::UPROPERTY(), UFbxImportUI::UPROPERTY(), UFbxImportUI::UPROPERTY(), UFbxImportUI::UPROPERTY(), UFbxImportUI::UPROPERTY(), UFbxImportUI::UPROPERTY(), UFbxImportUI::UPROPERTY(), UFbxImportUI::UPROPERTY(), UFbxImportUI::UPROPERTY(), UFbxImportUI::UPROPERTY(), UFbxStaticMeshImportData::UPROPERTY(), UFbxStaticMeshImportData::UPROPERTY(), UFbxTextureImportData::UPROPERTY(), UFbxTextureImportData::UPROPERTY(), UFbxTextureImportData::UPROPERTY(), UFbxTextureImportData::UPROPERTY(), UFbxTextureImportData::UPROPERTY(), UFbxTextureImportData::UPROPERTY(), UFbxTextureImportData::UPROPERTY(), UFbxTextureImportData::UPROPERTY(), UFbxTextureImportData::UPROPERTY(), UFloatingPawnMovement::UPROPERTY(), UGameplayAbilitiesDeveloperSettings::UPROPERTY(), UGameplayAbilitiesDeveloperSettings::UPROPERTY(), UGameplayAbilitiesDeveloperSettings::UPROPERTY(), UGameplayAbilitiesDeveloperSettings::UPROPERTY(), UGameplayAbilitiesDeveloperSettings::UPROPERTY(), UGameplayAbilitiesDeveloperSettings::UPROPERTY(), UGameplayAbilitiesDeveloperSettings::UPROPERTY(), UGameplayAbilitiesDeveloperSettings::UPROPERTY(), UGameplayAbilitiesDeveloperSettings::UPROPERTY(), UGameplayAbilitiesDeveloperSettings::UPROPERTY(), UGameplayAbilitiesDeveloperSettings::UPROPERTY(), UGameplayAbilitiesDeveloperSettings::UPROPERTY(), UGameplayAbilitiesDeveloperSettings::UPROPERTY(), UGameplayAbilitiesDeveloperSettings::UPROPERTY(), UGameplayAbilitiesDeveloperSettings::UPROPERTY(), UGameplayAbilitiesDeveloperSettings::UPROPERTY(), UGameplayAbilitiesEditorDeveloperSettings::UPROPERTY(), UGameplayAbilitiesEditorDeveloperSettings::UPROPERTY(), UGameplayAbilitiesEditorDeveloperSettings::UPROPERTY(), UGameplayCueNotify_Static::UPROPERTY(), UGroomAsset::UPROPERTY(), UGroomAsset::UPROPERTY(), UHierarchicalLODSettings::UPROPERTY(), UHierarchicalLODSettings::UPROPERTY(), UHierarchicalLODSettings::UPROPERTY(), UInstancedStaticMeshComponent::UPROPERTY(), UInstancedStaticMeshComponent::UPROPERTY(), UInterpToMovementComponent::UPROPERTY(), UInterpToMovementComponent::UPROPERTY(), ULevelEditor2DSettings::UPROPERTY(), ULevelEditor2DSettings::UPROPERTY(), ULightComponent::UPROPERTY(), ULightComponent::UPROPERTY(), ULightComponent::UPROPERTY(), ULightComponent::UPROPERTY(), ULightComponent::UPROPERTY(), ULightComponent::UPROPERTY(), ULightComponent::UPROPERTY(), ULightComponent::UPROPERTY(), ULightComponent::UPROPERTY(), ULightComponent::UPROPERTY(), ULightComponent::UPROPERTY(), ULightComponent::UPROPERTY(), ULightComponent::UPROPERTY(), ULightComponent::UPROPERTY(), ULightComponent::UPROPERTY(), ULightComponent::UPROPERTY(), ULightComponent::UPROPERTY(), ULightComponent::UPROPERTY(), ULightComponent::UPROPERTY(), ULightComponent::UPROPERTY(), ULightComponentBase::UPROPERTY(), ULightComponentBase::UPROPERTY(), ULightComponentBase::UPROPERTY(), ULightComponentBase::UPROPERTY(), ULightComponentBase::UPROPERTY(), ULightComponentBase::UPROPERTY(), UMeshSimplificationSettings::UPROPERTY(), UMeshSimplificationSettings::UPROPERTY(), UNiagaraDataInterfaceGeometryCollection::UPROPERTY(), UNiagaraDataInterfaceGeometryCollection::UPROPERTY(), UNiagaraDataInterfaceGeometryCollection::UPROPERTY(), UParticleModuleLocationBoneSocket::UPROPERTY(), UPhysicalAnimationComponent::UPROPERTY(), UPhysicsConstraintComponent::UPROPERTY(), UPhysicsHandleComponent::UPROPERTY(), UPhysicsHandleComponent::UPROPERTY(), UPhysicsHandleComponent::UPROPERTY(), UPhysicsHandleComponent::UPROPERTY(), UPhysicsHandleComponent::UPROPERTY(), UPhysicsSpringComponent::UPROPERTY(), UPhysicsSpringComponent::UPROPERTY(), UPhysicsSpringComponent::UPROPERTY(), UProjectileMovementComponent::UPROPERTY(), UProjectileMovementComponent::UPROPERTY(), UProjectileMovementComponent::UPROPERTY(), UProjectileMovementComponent::UPROPERTY(), UProjectileMovementComponent::UPROPERTY(), UProjectileMovementComponent::UPROPERTY(), UProjectileMovementComponent::UPROPERTY(), UProjectileMovementComponent::UPROPERTY(), UProjectileMovementComponent::UPROPERTY(), UProjectileMovementComponent::UPROPERTY(), UProjectileMovementComponent::UPROPERTY(), UPROPERTY(), UProxyLODMeshSimplificationSettings::UPROPERTY(), UReflectionCaptureComponent::UPROPERTY(), UReflectionCaptureComponent::UPROPERTY(), URendererSettings::UPROPERTY(), URendererSettings::UPROPERTY(), URendererSettings::UPROPERTY(), URendererSettings::UPROPERTY(), URendererSettings::UPROPERTY(), URendererSettings::UPROPERTY(), URendererSettings::UPROPERTY(), URendererSettings::UPROPERTY(), URendererSettings::UPROPERTY(), URendererSettings::UPROPERTY(), URendererSettings::UPROPERTY(), URendererSettings::UPROPERTY(), URendererSettings::UPROPERTY(), URendererSettings::UPROPERTY(), URendererSettings::UPROPERTY(), URendererSettings::UPROPERTY(), URendererSettings::UPROPERTY(), URendererSettings::UPROPERTY(), URendererSettings::UPROPERTY(), URendererSettings::UPROPERTY(), URendererSettings::UPROPERTY(), URendererSettings::UPROPERTY(), URendererSettings::UPROPERTY(), URendererSettings::UPROPERTY(), URendererSettings::UPROPERTY(), URendererSettings::UPROPERTY(), URendererSettings::UPROPERTY(), URendererSettings::UPROPERTY(), URendererSettings::UPROPERTY(), URuntimeVirtualTextureComponent::UPROPERTY(), URuntimeVirtualTextureComponent::UPROPERTY(), URuntimeVirtualTextureComponent::UPROPERTY(), URuntimeVirtualTextureComponent::UPROPERTY(), URuntimeVirtualTextureComponent::UPROPERTY(), URuntimeVirtualTextureComponent::UPROPERTY(), URuntimeVirtualTextureComponent::UPROPERTY(), URuntimeVirtualTextureComponent::UPROPERTY(), URuntimeVirtualTextureComponent::UPROPERTY(), USceneCaptureComponent::UPROPERTY(), USceneCaptureComponent::UPROPERTY(), USceneCaptureComponent::UPROPERTY(), USceneCaptureComponent::UPROPERTY(), USkeletalMeshSimplificationSettings::UPROPERTY(), USoundWave::UPROPERTY(), USoundWave::UPROPERTY(), USoundWave::UPROPERTY(), USoundWave::UPROPERTY(), USoundWave::UPROPERTY(), USoundWave::UPROPERTY(), USpotLightComponent::UPROPERTY(), USpringArmComponent::UPROPERTY(), USpringArmComponent::UPROPERTY(), USpringArmComponent::UPROPERTY(), USpringArmComponent::UPROPERTY(), USpringArmComponent::UPROPERTY(), USpringArmComponent::UPROPERTY(), UStreamingSettings::UPROPERTY(), UStreamingSettings::UPROPERTY(), UStreamingSettings::UPROPERTY(), UStreamingSettings::UPROPERTY(), UStreamingSettings::UPROPERTY(), UStreamingSettings::UPROPERTY(), UStreamingSettings::UPROPERTY(), UStreamingSettings::UPROPERTY(), UStreamingSettings::UPROPERTY(), UStreamingSettings::UPROPERTY(), UStreamingSettings::UPROPERTY(), UVirtualTexturePoolConfig::UPROPERTY(), UVirtualTexturePoolConfig::UPROPERTY(), UWaterMeshComponent::UPROPERTY(), UWaterMeshComponent::UPROPERTY(), UWaterMeshComponent::UPROPERTY(), UWaterMeshComponent::UPROPERTY(), UWaterMeshComponent::UPROPERTY(), UWindDirectionalSourceComponent::UPROPERTY(), UWorldPartitionStreamingSourceComponent::UPROPERTY(), UWorldPartitionStreamingSourceComponent::UPROPERTY(), UWorldPartitionStreamingSourceComponent::UPROPERTY(), FScopedSkeletalMeshRenderData::USkeletalMesh, USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), and USTRUCT().