Unreal Engine 5.6 C++ API: Runtime/MovieScene/Public/MovieSceneSpawnable.h File Reference
MovieSceneSpawnable.h File Reference
#include "CoreMinimal.h"
#include "UObject/ObjectMacros.h"
#include "Misc/Guid.h"
#include "MovieSceneDynamicBinding.h"
#include "MovieSceneSpawnable.generated.h"
Namespaces
namespace UE
Utility functions for applying transformations to meshes.
namespace UE::MovieScene
Functions
UENUM() enum class ESpawnOwnership USTRUCT () struct FMovieSceneSpawnable
MovieSceneSpawnable describes an object that can be spawned for this MovieScene.
Function Documentation
USTRUCT()
UENUM() enum class ESpawnOwnership USTRUCT ()
MovieSceneSpawnable describes an object that can be spawned for this MovieScene.
FMovieSceneSpawnable initialization constructor
Check if the specified object is a spawnable template
Parameters
InObject The object to test
Returns
true if the specified object is a spawnable template, false otherwise
Indicate that the specified object is a spawnable template object
Parameters
InObject The object to mark
Get the template object for this spawnable
Returns
Object template
See also
GetGuid, GetName
Get the template object for this spawnable
Returns
Object template
See also
GetGuid, GetName
Set the object template to the specified object directly. Used for Copy/Paste, typically you should use CopyObjectTemplate.
Copy the specified object into this spawnable's template
Parameters
InSourceObject The source object to use. This object will be duplicated into the spawnable.
MovieSceneSequence The movie scene sequence to which this spawnable belongs
Get the unique identifier of the spawnable object.
Returns
Object GUID.
See also
GetClass, GetName
Set the unique identifier of this spawnable object
Parameters
InGuid The new GUID for this spawnable
Note
Be careful - this guid may be referenced by spawnable/possessable child-parent relationships.
See also
GetGuid
Get the name of the spawnable object.
Returns
Object name.
See also
GetClass, GetGuid
Set the name of the spawnable object.
@InName The desired spawnable name.
Report the specified GUID as being an inner possessable dependency for this spawnable
Parameters
PossessableGuid The guid pertaining to the inner possessable
Remove the specified GUID from this spawnables list of dependent possessables
Parameters
PossessableGuid The guid pertaining to the inner possessable
Returns
const access to the child possessables set
Get a value indicating what is responsible for this object once it's spawned
Set a value indicating what is responsible for this object once it's spawned
Optional spawn transform
Get the name of the level to spawn into.
Returns
Level name.
Set the name of the level to spawn into.
@InLevelName The desired spawnable level name.
Get the name to use for spawning this object into a networked level
Automatically determine a value for bNetAddressableName based on the spawnable type
Array of tags that can be used for grouping and categorizing.
When enabled, this spawnable will always be respawned if it gets destroyed externally. When disabled, this object will only ever be spawned once for each spawn key even if it is destroyed externally.
When enabled, the actor will be spawned with a unique name so that it can be addressable between clients and servers.
Unique identifier of the spawnable object.
Name label
Set of GUIDs to possessable object bindings that are bound to an object inside this spawnable
Property indicating where ownership responsibility for this object lies
Name of level to spawn into
Definition at line 38 of file MovieSceneSpawnable.h.
References Actor, Category, checkf, FORCEINLINE, GENERATED_BODY, Guid, UObjectBaseUtility::HasAnyFlags(), InName, Name, FGuid::NewGuid(), operator<(), RF_ClassDefaultObject, Tags, TEXT, UE_DEPRECATED, and UPROPERTY.