Unreal Engine 5.6 C++ API: S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/GameplayAbilities/Source/GameplayAbilities/Public/Sequencer/MovieSceneGameplayCueSections.h File Reference
MovieSceneGameplayCueSections.h File Reference
#include "CoreTypes.h"
#include "UObject/ObjectMacros.h"
#include "MovieSceneSection.h"
#include "Sections/MovieSceneHookSection.h"
#include "Channels/MovieSceneChannel.h"
#include "Channels/MovieSceneChannelData.h"
#include "Channels/MovieSceneChannelTraits.h"
#include "MovieSceneClipboard.h"
#include "GameplayCueInterface.h"
#include "MovieSceneObjectBindingID.h"
#include "MovieSceneGameplayCueSections.generated.h"
Data Structures
struct TMovieSceneChannelTraits< FMovieSceneGameplayCueChannel >
Namespaces
namespace MovieSceneClipboard
Helper functions for defining conversions between types.
Functions
bool EvaluateChannel (const FMovieSceneGameplayCueChannel *InChannel, FFrameTime InTime, FMovieSceneGameplayCueKey &OutValue)
template<>
FName MovieSceneClipboard::GetKeyTypeName< FMovieSceneGameplayCueKey > ()
USTRUCT () struct FMovieSceneGameplayCueKey
Function Documentation
EvaluateChannel()
bool EvaluateChannel (const FMovieSceneGameplayCueChannel * InChannel, FFrameTime InTime, FMovieSceneGameplayCueKey & OutValue) inline
Definition at line 137 of file MovieSceneGameplayCueSections.h.
References InTime.
Referenced by Sequencer::AddOrUpdateKey(), Sequencer::DeleteKeys(), EvaluateChannel(), TAddKeyImpl< FMovieSceneDoubleChannel, double >::ModifyByCurrentAndWeight(), TAddKeyImpl< FMovieSceneFloatChannel, float >::ModifyByCurrentAndWeight(), TAddKeyImpl< FMovieSceneIntegerChannel, int32 >::ModifyByCurrentAndWeight(), and MovieSceneImpl::TChannelValueHelper< ChannelType, ValueType >::SetUserValueFromTime().
USTRUCT()
USTRUCT ()
Location cue took place at - relative to the attached component if applicable
Normal of impact that caused cue
When attached to a skeletal mesh component, specifies a socket to trigger the cue at
Magnitude of source gameplay effect, normalzed from 0-1. Use this for "how strong is the gameplay effect" (0=min, 1=,max)
Instigator actor, the actor that owns the ability system component.
The physical actor that actually did the damage, can be a weapon or projectile
PhysMat of the hit, if there was a hit.
The level of that GameplayEffect
If originating from an ability, this will be the level of that ability
Attach the gameplay cue to the track's bound object in sequencer
Definition at line 18 of file MovieSceneGameplayCueSections.h.
References Category, Cue, ForceInitToZero, FVector, GENERATED_BODY, Location, meta, Normal, and UPROPERTY.