Unreal Engine 5.6 C++ API: Runtime/MovieScene/Public/MovieSceneSection.h File Reference
MovieSceneSection.h File Reference
#include "Conditions/MovieSceneCondition.h"
#include "Containers/Array.h"
#include "Containers/ArrayView.h"
#include "Containers/ContainersFwd.h"
#include "Containers/Map.h"
#include "CoreMinimal.h"
#include "CoreTypes.h"
#include "Evaluation/Blending/MovieSceneBlendType.h"
#include "Evaluation/MovieSceneCompletionMode.h"
#include "Evaluation/MovieSceneEvaluationCustomVersion.h"
#include "EventHandlers/ISectionEventHandler.h"
#include "EventHandlers/MovieSceneDataEventContainer.h"
#include "Decorations/MovieSceneDecorationContainer.h"
#include "HAL/PlatformCrt.h"
#include "Math/Range.h"
#include "Math/RangeBound.h"
#include "Misc/AssertionMacros.h"
#include "Misc/FrameNumber.h"
#include "Misc/QualifiedFrameTime.h"
#include "Misc/FrameRate.h"
#include "Misc/FrameTime.h"
#include "Misc/Optional.h"
#include "Misc/Timecode.h"
#include "MovieSceneFrameMigration.h"
#include "MovieSceneSequenceID.h"
#include "MovieSceneSignedObject.h"
#include "Templates/SharedPointer.h"
#include "UObject/NameTypes.h"
#include "UObject/ObjectMacros.h"
#include "UObject/ScriptInterface.h"
#include "UObject/UObjectGlobals.h"
#include "MovieSceneSection.generated.h"
Namespaces
namespace UE
Utility functions for applying transformations to meshes.
namespace UE::MovieScene
Enumerations
enum class EMovieSceneChannelProxyType : uint8 { Static , Dynamic }
Enumeration defining how a section's channel proxy behaves.
enum class EMovieSceneTransformChannel : uint32 {
None = 0x000 , TranslationX = 0x001 , TranslationY = 0x002 , TranslationZ = 0x004 ,
Translation = TranslationX | TranslationY | TranslationZ , RotationX = 0x008 , RotationY = 0x010 , RotationZ = 0x020 ,
Rotation = RotationX | RotationY | RotationZ , ScaleX = 0x040 , ScaleY = 0x080 , ScaleZ = 0x100 ,
Scale = ScaleX | ScaleY | ScaleZ , AllTransform = Translation | Rotation | Scale , Weight = 0x200 , All = Translation | Rotation | Scale | Weight
}
Defines for common transform 'type' sections.
Functions
DECLARE_MULTICAST_DELEGATE_OneParam (FOnMovieSceneSectionChanged, UMovieSceneSection *)
Delegate for when a section is removed from a track.
DECLARE_MULTICAST_DELEGATE_TwoParams (FOnMovieSceneSectionAddedToTrack, UMovieSceneTrack *, UMovieSceneSection *)
Delegate for when a section is added to a track.
template<typename SectionParams>
UCLASS() class UMovieSceneSection FFrameNumber GetFirstLoopStartOffsetAtTrimTime (FQualifiedFrameTime TrimTime, const SectionParams &Params, FFrameNumber StartFrame, FFrameRate FrameRate)
Base class for movie scene sections.
USTRUCT () struct FMovieSceneSectionEvalOptions
Enumeration Type Documentation
EMovieSceneChannelProxyType
enum class EMovieSceneChannelProxyType : uint8 strong
Enumeration defining how a section's channel proxy behaves.
Enumerator
Static
Once constructed, the channel proxy will not change even on serialization.
The channel proxy has a static layout and the memory for each channel is always valid.
Dynamic
The channel proxy layout can be affected by serialization or duplication and must be updated on such changes.
Definition at line 72 of file MovieSceneSection.h.
EMovieSceneTransformChannel
enum class EMovieSceneTransformChannel : uint32 strong
Defines for common transform 'type' sections.
Moved here to avoid extra module dependencies
Enumerator
None
TranslationX
TranslationY
TranslationZ
Translation
RotationX
RotationY
RotationZ
Rotation
ScaleX
ScaleY
ScaleZ
Scale
AllTransform
Weight
All
Definition at line 211 of file MovieSceneSection.h.
Function Documentation
DECLARE_MULTICAST_DELEGATE_OneParam()
DECLARE_MULTICAST_DELEGATE_OneParam (FOnMovieSceneSectionChanged , UMovieSceneSection *)
Delegate for when a section is removed from a track.
DECLARE_MULTICAST_DELEGATE_TwoParams()
DECLARE_MULTICAST_DELEGATE_TwoParams (FOnMovieSceneSectionAddedToTrack , UMovieSceneTrack * , UMovieSceneSection *)
Delegate for when a section is added to a track.
GetFirstLoopStartOffsetAtTrimTime()
template<typename SectionParams> UCLASS() class UMovieSceneSection FFrameNumber GetFirstLoopStartOffsetAtTrimTime (FQualifiedFrameTime TrimTime, const SectionParams & Params, FFrameNumber StartFrame, FFrameRate FrameRate) inline
Base class for movie scene sections.
Definition at line 866 of file MovieSceneSection.h.
References FrameRate, GetFirstLoopStartOffsetAtTrimTime(), FMath::IsNearlyZero(), and Params.
Referenced by GetFirstLoopStartOffsetAtTrimTime().
USTRUCT()
USTRUCT ()
When set to "RestoreState", this section will restore any animation back to its previous state
Automatically applied ease in duration in frames
Automatically applied ease out time
Whether to manually override this section's ease in time
Manually override this section's ease in duration in frames
Whether to manually override this section's ease out time
Manually override this section's ease-out duration in frames
The global timecode at which this target is based (ie. the timecode at the beginning of the movie scene section when it was recorded)
Definition at line 86 of file MovieSceneSection.h.
References Category, GENERATED_BODY, and UPROPERTY.