Unreal Engine 5.6 C++ API: Runtime/MovieSceneTracks/Public/Sections/MovieSceneActorReferenceSection.h File Reference
MovieSceneActorReferenceSection.h File Reference
#include "Channels/MovieSceneChannel.h"
#include "Channels/MovieSceneChannelData.h"
#include "Channels/MovieSceneChannelTraits.h"
#include "Containers/Array.h"
#include "Containers/ArrayView.h"
#include "Containers/Map.h"
#include "Containers/UnrealString.h"
#include "CoreMinimal.h"
#include "Curves/IntegralCurve.h"
#include "Curves/KeyHandle.h"
#include "HAL/Platform.h"
#include "HAL/PlatformCrt.h"
#include "Math/Range.h"
#include "Misc/AssertionMacros.h"
#include "Misc/FrameNumber.h"
#include "Misc/FrameRate.h"
#include "Misc/FrameTime.h"
#include "Misc/Guid.h"
#include "MovieSceneFwd.h"
#include "MovieSceneObjectBindingID.h"
#include "MovieSceneSection.h"
#include "UObject/NameTypes.h"
#include "UObject/ObjectMacros.h"
#include "UObject/UObjectGlobals.h"
#include "MovieSceneActorReferenceSection.generated.h"
Functions
USTRUCT() struct FMovieSceneActorReferenceData UCLASS() class UMovieSceneActorReferenceSection bool EvaluateChannel (const FMovieSceneActorReferenceData *InChannel, FFrameTime InTime, FMovieSceneActorReferenceKey &OutValue)
A curve of events.
USTRUCT () struct FMovieSceneActorReferenceKey
Function Documentation
EvaluateChannel()
USTRUCT() struct FMovieSceneActorReferenceData UCLASS() class UMovieSceneActorReferenceSection bool EvaluateChannel (const FMovieSceneActorReferenceData * InChannel, FFrameTime InTime, FMovieSceneActorReferenceKey & OutValue) inline
A curve of events.
A single actor reference point section
Definition at line 218 of file MovieSceneActorReferenceSection.h.
References EvaluateChannel(), and InTime.
USTRUCT()
USTRUCT ()
Definition at line 38 of file MovieSceneActorReferenceSection.h.
References A, B, Category, GENERATED_BODY, Object, operator!=(), operator==(), and UPROPERTY.