Unreal Engine 5.6 C++ API: Runtime/MovieScene/Public/MovieSceneFrameMigration.h File Reference
MovieSceneFrameMigration.h File Reference
#include "Containers/Array.h"
#include "CoreTypes.h"
#include "Math/Range.h"
#include "Math/RangeBound.h"
#include "Misc/FrameNumber.h"
#include "MovieSceneFwd.h"
#include "Serialization/StructuredArchive.h"
#include "UObject/Class.h"
#include "UObject/ObjectMacros.h"
#include "MovieSceneFrameMigration.generated.h"
Data Structures
struct TStructOpsTypeTraits< FMovieSceneFrameRange >
Functions
template<typename T>
void ConvertInsertAndSort (int32 IndexAt, FFrameNumber NewFrame, T &Value, TArray< FFrameNumber > &Times, TArray< T > &Values)
Set the value at the specified time and index into the arrays, sorted and converted to frame numbers We need this since some legacy channels and sections may not be sorted and we now expect time,value arrays to be sorted.
USTRUCT () struct FMovieSceneFrameRange
Type used to convert from a FFloatRange to a TRange<FFrameNumber>
Function Documentation
ConvertInsertAndSort()
template<typename T> void ConvertInsertAndSort (int32 IndexAt, FFrameNumber NewFrame, T & Value, TArray< FFrameNumber > & Times, TArray< T > & Values) inline
Set the value at the specified time and index into the arrays, sorted and converted to frame numbers We need this since some legacy channels and sections may not be sorted and we now expect time,value arrays to be sorted.
Definition at line 120 of file MovieSceneFrameMigration.h.
References TArray< InElementType, InAllocatorType >::Emplace(), TArray< InElementType, InAllocatorType >::Insert(), and Value.
USTRUCT()
USTRUCT ()
Type used to convert from a FFloatRange to a TRange<FFrameNumber>
The actual frame number range, custom serialized
Default construction to an empty frame range
Construction from a frame range
Convert this frame number from a float range
Custom serializer for the frame number range
Serialize this frame range from a mismatched type (only FFloatRange supported)
Get this range's lower bound
Get this range's upper bound
Equality operator
Definition at line 26 of file MovieSceneFrameMigration.h.
References A, Ar, B, Buffer, TRange< ElementType >::Empty(), GENERATED_BODY, operator==(), Parent, and Value.