Unreal Engine 5.6 C++ API: Runtime/MovieScene/Public/MovieSceneFwd.h File Reference
MovieSceneFwd.h File Reference
#include "CoreTypes.h"
#include "Stats/Stats.h"
#include "Misc/EnumClassFlags.h"
#include "HAL/PreprocessorHelpers.h"
#include "MovieSceneFwd.generated.h"
Namespaces
namespace UE
Utility functions for applying transformations to meshes.
namespace UE::MovieScene
Macros
#define MOVIESCENE_DETAILED_SCOPE_CYCLE_COUNTER(...)
#define MOVIESCENE_DETAILED_STATS 0
#define UE_MOVIESCENE_ENTITY_DEBUG !UE_BUILD_SHIPPING
#define UE_MOVIESCENE_EVENTS WITH_EDITOR
#define UE_MOVIESCENE_EXPENSIVE_CONSISTENCY_CHECKS 0
#define UE_MOVIESCENE_TODO(MSG)
#define UE_MOVIESCENE_TODO_IMPL(x)
Functions
MOVIESCENE_API DECLARE_LOG_CATEGORY_EXTERN (LogMovieSceneECS, Log, All)
DECLARE_STATS_GROUP (TEXT("Movie Scene Evaluation"), STATGROUP_MovieSceneEval, STATCAT_Advanced)
MOVIESCENE_API void EmitLegacyOutOfBoundsError (UObject *ErrorContext, FFrameRate InFrameRate, double InTime)
UENUM() enum class EMovieSceneEvaluationType UENUM() enum class EUpdateClockSource UENUM() enum class EMovieSceneSequenceFlags ENUM_CLASS_FLAGS (EMovieSceneSequenceFlags)
Enum used to define how to update to a particular time.
UENUM()) enum class EMovieSceneServerClientMask ENUM_CLASS_FLAGS (EMovieSceneServerClientMask) MOVIESCENE_API DECLARE_LOG_CATEGORY_EXTERN(LogMovieScene
MOVIESCENE_API FFrameRate GetLegacyConversionFrameRate ()
UENUM () namespace EMovieScenePlayerStatus
MOVIESCENE_API FFrameNumber UpgradeLegacyMovieSceneTime (UObject *ErrorContext, FFrameRate InFrameRate, double InTime)
Variables
UENUM()) enum class EMovieSceneServerClientMask All
UENUM()) enum class EMovieSceneServerClientMask Log
Macro Definition Documentation
MOVIESCENE_DETAILED_SCOPE_CYCLE_COUNTER
#define MOVIESCENE_DETAILED_SCOPE_CYCLE_COUNTER (...)
Definition at line 152 of file MovieSceneFwd.h.
Referenced by FPersistentEvaluationData::Add(), FPersistentEvaluationData::Add(), TPropertyTrackExecutionToken< PropertyValueType, IntermediateType >::Execute(), FPersistentEvaluationData::Find(), FPersistentEvaluationData::Find(), FPersistentEvaluationData::Find(), FPersistentEvaluationData::Get(), FPersistentEvaluationData::Get(), FPersistentEvaluationData::Get(), FPersistentEvaluationData::GetOrAdd(), FPersistentEvaluationData::GetOrAdd(), FPersistentEvaluationData::Reset(), and FPersistentEvaluationData::Reset().
MOVIESCENE_DETAILED_STATS
#define MOVIESCENE_DETAILED_STATS 0
Definition at line 25 of file MovieSceneFwd.h.
UE_MOVIESCENE_ENTITY_DEBUG
#define UE_MOVIESCENE_ENTITY_DEBUG !UE_BUILD_SHIPPING
Definition at line 21 of file MovieSceneFwd.h.
UE_MOVIESCENE_EVENTS
#define UE_MOVIESCENE_EVENTS WITH_EDITOR
Definition at line 13 of file MovieSceneFwd.h.
UE_MOVIESCENE_EXPENSIVE_CONSISTENCY_CHECKS
#define UE_MOVIESCENE_EXPENSIVE_CONSISTENCY_CHECKS 0
Definition at line 17 of file MovieSceneFwd.h.
UE_MOVIESCENE_TODO
#define UE_MOVIESCENE_TODO (MSG)
Definition at line 165 of file MovieSceneFwd.h.
UE_MOVIESCENE_TODO_IMPL
#define UE_MOVIESCENE_TODO_IMPL (x)
Value:
_Pragma (#x)
Definition at line 159 of file MovieSceneFwd.h.
Function Documentation
DECLARE_LOG_CATEGORY_EXTERN()
MOVIESCENE_API DECLARE_LOG_CATEGORY_EXTERN (LogMovieSceneECS , Log , All)
References All, DECLARE_LOG_CATEGORY_EXTERN, and Log.
DECLARE_STATS_GROUP()
DECLARE_STATS_GROUP (TEXT("Movie Scene Evaluation") , STATGROUP_MovieSceneEval , STATCAT_Advanced)
References DECLARE_STATS_GROUP, and TEXT.
EmitLegacyOutOfBoundsError()
MOVIESCENE_API void EmitLegacyOutOfBoundsError (UObject * ErrorContext, FFrameRate InFrameRate, double InTime)
References EmitLegacyOutOfBoundsError(), and InTime.
Referenced by EmitLegacyOutOfBoundsError().
ENUM_CLASS_FLAGS() [1/2]
UENUM() enum class EMovieSceneEvaluationType UENUM() enum class EUpdateClockSource UENUM() enum class EMovieSceneSequenceFlags ENUM_CLASS_FLAGS (EMovieSceneSequenceFlags)
Enum used to define how to update to a particular time.
Bitfield flags that define special behavior for any UMovieSceneSequence.
References All, Client, Flags, Hidden, meta, None, and Server.
ENUM_CLASS_FLAGS() [2/2]
UENUM()) enum class EMovieSceneServerClientMask ENUM_CLASS_FLAGS (EMovieSceneServerClientMask)
GetLegacyConversionFrameRate()
MOVIESCENE_API FFrameRate GetLegacyConversionFrameRate ()
References GetLegacyConversionFrameRate().
Referenced by GetLegacyConversionFrameRate().
UENUM()
UENUM ()
Definition at line 39 of file MovieSceneFwd.h.
References MAX, Paused, and Playing.
UpgradeLegacyMovieSceneTime()
MOVIESCENE_API FFrameNumber UpgradeLegacyMovieSceneTime (UObject * ErrorContext, FFrameRate InFrameRate, double InTime)
References InTime, and UpgradeLegacyMovieSceneTime().
Referenced by UpgradeLegacyMovieSceneTime().
Variable Documentation
All
UENUM()) enum class EMovieSceneServerClientMask All
Definition at line 139 of file MovieSceneFwd.h.
Referenced by FLogCategoryLogContentComparisonCommandlet::FLogCategoryLogContentComparisonCommandlet(), FLogCategoryLogCore::FLogCategoryLogCore(), FLogCategoryLogExec::FLogCategoryLogExec(), FLogCategoryLogExit::FLogCategoryLogExit(), FLogCategoryLogHAL::FLogCategoryLogHAL(), FLogCategoryLogInit::FLogCategoryLogInit(), FLogCategoryLogLoad::FLogCategoryLogLoad(), FLogCategoryLogLocalization::FLogCategoryLogLocalization(), FLogCategoryLogLongPackageNames::FLogCategoryLogLongPackageNames(), FLogCategoryLogMemory::FLogCategoryLogMemory(), FLogCategoryLogNetPackageMap::FLogCategoryLogNetPackageMap(), FLogCategoryLogNetSerialization::FLogCategoryLogNetSerialization(), FLogCategoryLogOutputDevice::FLogCategoryLogOutputDevice(), FLogCategoryLogProcess::FLogCategoryLogProcess(), FLogCategoryLogProfilingDebugging::FLogCategoryLogProfilingDebugging(), FLogCategoryLogScript::FLogCategoryLogScript(), FLogCategoryLogSerialization::FLogCategoryLogSerialization(), FLogCategoryLogSHA::FLogCategoryLogSHA(), FLogCategoryLogStats::FLogCategoryLogStats(), FLogCategoryLogStreaming::FLogCategoryLogStreaming(), FLogCategoryLogTemp::FLogCategoryLogTemp(), FLogCategoryLogUnrealMath::FLogCategoryLogUnrealMath(), FLogCategoryLogUnrealMatrix::FLogCategoryLogUnrealMatrix(), FLogCategoryLogUVEditor::FLogCategoryLogUVEditor(), FLogCategoryLogVirtualization::FLogCategoryLogVirtualization(), FMovieSceneEvaluationTree::FMovieSceneEvaluationTree(), FGraphDiffControl::FNodeDiffContext::FNodeDiffContext(), CSV_DECLARE_CATEGORY_MODULE_EXTERN(), DECLARE_DYNAMIC_DELEGATE_RetVal_TwoParams(), DECLARE_LOG_CATEGORY_CLASS(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), HarmonixMetasound::DECLARE_LOG_CATEGORY_EXTERN(), LowLevelTasks::DECLARE_LOG_CATEGORY_EXTERN(), WorldPartitionCommandletHelpers::DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_STATS_GROUP(), DEFINE_LOG_CATEGORY_STATIC(), DEFINE_LOG_CATEGORY_STATIC(), DEFINE_LOG_CATEGORY_STATIC(), ENUM_CLASS_FLAGS(), UENUM(), UENUM(), and UStruct::Visit().
Log
UENUM()) enum class EMovieSceneServerClientMask Log
Definition at line 139 of file MovieSceneFwd.h.
Referenced by FLogCategoryLogContentComparisonCommandlet::FLogCategoryLogContentComparisonCommandlet(), FLogCategoryLogCore::FLogCategoryLogCore(), FLogCategoryLogExit::FLogCategoryLogExit(), FLogCategoryLogHAL::FLogCategoryLogHAL(), FLogCategoryLogInit::FLogCategoryLogInit(), FLogCategoryLogLoad::FLogCategoryLogLoad(), FLogCategoryLogLocalization::FLogCategoryLogLocalization(), FLogCategoryLogLongPackageNames::FLogCategoryLogLongPackageNames(), FLogCategoryLogMemory::FLogCategoryLogMemory(), FLogCategoryLogOutputDevice::FLogCategoryLogOutputDevice(), FLogCategoryLogProcess::FLogCategoryLogProcess(), FLogCategoryLogProfilingDebugging::FLogCategoryLogProfilingDebugging(), FLogCategoryLogSerialization::FLogCategoryLogSerialization(), FLogCategoryLogStats::FLogCategoryLogStats(), FLogCategoryLogTemp::FLogCategoryLogTemp(), FLogCategoryLogUnrealMath::FLogCategoryLogUnrealMath(), FLogCategoryLogUnrealMatrix::FLogCategoryLogUnrealMatrix(), FLogCategoryLogUVEditor::FLogCategoryLogUVEditor(), FLogCategoryLogVirtualization::FLogCategoryLogVirtualization(), FLogScopedCategoryAndVerbosityOverride::FOverride::FOverride(), UE::Logging::Private::BasicFatalLog(), UE::Logging::Private::BasicFatalLogWithProgramCounter(), UE::Logging::Private::BasicLog(), FLoggedPlatformFile::CopyFile(), FEdGraphToken::Create(), FEdGraphToken::Create(), FEdGraphToken::Create(), FEdGraphToken::Create(), FLoggedPlatformFile::CreateDirectory(), FEdGraphToken::CreateInternal(), CSV_DECLARE_CATEGORY_MODULE_EXTERN(), TNetRewindHistory< DataType >::DebugData(), UE::Math::TMatrix< double >::DebugPrint(), DECLARE_LOG_CATEGORY_CLASS(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), DECLARE_LOG_CATEGORY_EXTERN(), HarmonixMetasound::DECLARE_LOG_CATEGORY_EXTERN(), LowLevelTasks::DECLARE_LOG_CATEGORY_EXTERN(), WorldPartitionCommandletHelpers::DECLARE_LOG_CATEGORY_EXTERN(), DEFINE_LOG_CATEGORY_STATIC(), DEFINE_LOG_CATEGORY_STATIC(), FLoggedPlatformFile::DeleteDirectory(), FLoggedPlatformFile::DeleteDirectoryRecursively(), FLoggedPlatformFile::DeleteFile(), FLoggedPlatformFile::DirectoryExists(), TNetSimCueDispatcher< ModelDef >::DispatchCueRecord(), FBulkData::DumpBulkDataUsage(), FStatsHierarchical::DumpMeasurements(), TOctree2< FVolumeLightingSample, FLightVolumeOctreeSemantics >::DumpStats(), TOctree_DEPRECATED< ElementType, OctreeSemantics >::DumpStats(), UE::Logging::Private::FatalLogWithFieldArray(), UE::Logging::Private::FatalLogWithFieldArray(), UE::Logging::Private::FatalLogWithFields(), UE::Logging::Private::FatalLogWithNoFields(), UE::Logging::Private::FatalLogWithNoFields(), FLoggedPlatformFile::FileExists(), FLoggedPlatformFile::FileSize(), FNetworkPredictionModelDefRegistry::FinalizeTypes(), FLoggedPlatformFile::GetAccessTimeStamp(), FLoggedPlatformFile::GetFilenameOnDisk(), BlendSpaceAnalysis::GetFrameDirs(), TShaderRefBase< ShaderType, FShaderMapPointerTable >::GetGraphicsShader(), TShaderRefBase< ShaderType, FShaderMapPointerTable >::GetRHIShaderBase(), FLoggedPlatformFile::GetStatData(), FLoggedPlatformFile::GetTimeStamp(), FNetSimCueDispatcher::Invoke(), FLoggedPlatformFile::IsReadOnly(), FLoggedPlatformFile::IterateDirectory(), FLoggedPlatformFile::IterateDirectoryRecursively(), FLoggedPlatformFile::IterateDirectoryStat(), FLoggedPlatformFile::IterateDirectoryStatRecursively(), UE::Cook::FCookDependencyContext::LogError(), FOutputDevice::Logf(), UE::Cook::FCookDependencyContext::LogInvalidated(), UE::Logging::Private::LogWithFieldArray(), UE::Logging::Private::LogWithFieldArray(), UE::Logging::Private::LogWithFields(), UE::Logging::Private::LogWithNoFields(), UE::Logging::Private::LogWithNoFields(), FLoggedPlatformFile::MoveFile(), TNetSimCueDispatcher< ModelDef >::NetRecvSavedCues(), TNetSimCueDispatcher< ModelDef >::NotifyRollback(), UE::FGenericPlatformIoDispatcher::OnInitialize(), FLoggedPlatformFile::OpenAsyncRead(), FLoggedPlatformFile::OpenRead(), FLoggedPlatformFile::OpenWrite(), FStringOutputDeviceCountLines::operator+=(), FAssetData::PrintAssetData(), FPackedLevelActorBuilderContext::Report(), Harmonix::Dsp::Effects::FFourBiquads::SetFilter(), FLoggedPlatformFile::SetReadOnly(), FLoggedPlatformFile::SetTimeStamp(), UE::Math::TQuat< T >::ToRotationVector(), BlendSpaceAnalysis::UE_LOG(), BlendSpaceAnalysis::UE_LOG(), BlendSpaceAnalysis::UE_LOG(), BlendSpaceAnalysis::UE_LOG(), and USTRUCT().