Unreal Engine 5.6 C++ API: Runtime/MovieScene/Public/MovieSceneTimeHelpers.h File Reference
MovieSceneTimeHelpers.h File Reference
#include "Containers/UnrealString.h"
#include "CoreTypes.h"
#include "Math/NumericLimits.h"
#include "Math/Range.h"
#include "Math/RangeBound.h"
#include "Math/UnrealMathUtility.h"
#include "Misc/AssertionMacros.h"
#include "Misc/FrameNumber.h"
#include "Misc/FrameTime.h"
Data Structures
class UE::MovieScene::TimeHelpers
Namespaces
namespace UE
Utility functions for applying transformations to meshes.
namespace UE::MovieScene
Functions
FFrameTime UE::MovieScene::ClampToDiscreteRange (FFrameTime InTime, const TRange< FFrameNumber > &InRange)
Clamp the specified time to a range.
template<>
TRange< FFrameNumber > UE::MovieScene::ConvertRange (const TRange< FFrameTime > &Range)
template<typename InBoundType, typename OutBoundType>
TRange< OutBoundType > UE::MovieScene::ConvertRange (const TRange< InBoundType > &Range)
Converts a range from one type of bounds to another.
TRange< FFrameNumber > UE::MovieScene::ConvertToDiscreteRange (const TRange< FFrameTime > &InRange)
TRange< FFrameTime > UE::MovieScene::ConvertToFrameTimeRange (const TRange< FFrameNumber > &InRange)
Convert a frame number range into a frame time range.
TRange< FFrameTime > UE::MovieScene::ConvertToFrameTimeRange (const TRange< float > &InRange)
template<typename T>
TRange< T > UE::MovieScene::DilateRange (const TRange< T > &InRange, T LowerAmount, T UpperAmount)
Dilate the specified range by adding a specific size to the lower and upper bounds (if closed)
FFrameNumber UE::MovieScene::DiscreteExclusiveUpper (const TRange< FFrameNumber > &InRange)
Return the first frame number not contained by the specified range.
FFrameNumber UE::MovieScene::DiscreteExclusiveUpper (const TRangeBound< FFrameNumber > &InUpperBound)
Return the first frame number that is not contained by the specified closed upper bound.
FFrameNumber UE::MovieScene::DiscreteInclusiveLower (const TRange< FFrameNumber > &InRange)
Return the first frame number included by the specified range.
FFrameNumber UE::MovieScene::DiscreteInclusiveLower (const TRangeBound< FFrameNumber > &InLowerBound)
Return the first frame number included by the specified closed lower bound.
bool UE::MovieScene::DiscreteRangeIsEmpty (const TRange< FFrameNumber > &InRange)
Check whether the specified range contains any integer frame numbers or not.
int32 UE::MovieScene::DiscreteSize (const TRange< FFrameNumber > &InRange)
Calculate the size of a discrete frame range, taking into account inclusive/exclusive boundaries.
template<typename T>
TRange< T > UE::MovieScene::ExpandRange (const TRange< T > &InRange, T Amount)
Expand the specified range by subtracting the specified amount from the lower bound, and adding it to the upper bound.
bool UE::MovieScene::IsEmptyOrZeroSize (const TRange< FFrameNumber > &InRange)
Return whether the given range is empty or zero frames wide.
FString LexToString (const TRange< FFrameNumber > &InRange)
TRange< FFrameNumber > UE::MovieScene::MakeDiscreteRange (FFrameNumber MinInclusive, FFrameNumber MaxExclusive)
Make a new range that includes the given minimum and excludes the given maximum.
TRange< FFrameNumber > UE::MovieScene::MakeDiscreteRangeFromLower (const TRangeBound< FFrameNumber > &InLowerBound, int32 DiscreteSize)
Make a new range using the specified lower bound, and a given size.
TRange< FFrameNumber > UE::MovieScene::MakeDiscreteRangeFromUpper (const TRangeBound< FFrameNumber > &InUpperBound, int32 DiscreteSize)
Make a new range using the specified upper bound, and a given size.
TRange< FFrameNumber > UE::MovieScene::MakeHullRange (const TRange< FFrameNumber > &InRange)
Make a new range that includes both the lower and upper bounds of the given range.
TRange< FFrameNumber > UE::MovieScene::MakeHullRange (FFrameNumber MinInclusive, FFrameNumber MaxInclusive)
Make a new range that includes both the given minimum and maximum.
template<typename T>
TRange< T > UE::MovieScene::TranslateRange (const TRange< T > &InRange, T Amount)
Translate the specified range by adding the specified amount to both bounds.
Function Documentation
LexToString()
FString LexToString (const TRange< FFrameNumber > & InRange) inline
Definition at line 394 of file MovieSceneTimeHelpers.h.
References TRange< ElementType >::GetLowerBound(), TRange< ElementType >::GetUpperBound(), TRangeBound< ElementType >::GetValue(), TRangeBound< ElementType >::IsInclusive(), TRangeBound< ElementType >::IsOpen(), and TEXT.