Unreal Engine 5.6 C++ API: Runtime/MovieScene/Public/Variants/MovieSceneTimeWarpVariant.h File Reference
MovieSceneTimeWarpVariant.h File Reference
#include "MovieSceneNumericVariant.h"
#include "MovieSceneTimeWarpVariant.generated.h"
Data Structures
struct TStructOpsTypeTraits< FMovieSceneTimeWarpVariant >
Namespaces
namespace UE
Utility functions for applying transformations to meshes.
namespace UE::MovieScene
Functions
UENUM() enum class EMovieSceneTimeWarpType USTRUCT ()) struct FMovieSceneTimeWarpVariant
Enumeration defining the type stored within an FMovieSceneTimeWarpVariant.
Function Documentation
USTRUCT()
UENUM() enum class EMovieSceneTimeWarpType USTRUCT ()
Enumeration defining the type stored within an FMovieSceneTimeWarpVariant.
Numeric variant type that represents a 'time-warp' operation transforming a time into another time.
By default this variant is a literal value that represents a play rate of 1.0 (ie, a 1:1 mapping), but it can be customized to provide a wide range of different transformations such as looping, clamping and custom curves
Default construction: initializes this struct to a constant play rate of 1.0
Initialize this time-warp with a specific constant play rate
Initialize this time-warp with a specific fixed frame number
Initialize this time-warp with a looping time-warp
Initialize this time-warp with a time-warp that clamps the time to a specific range
Initialize this time-warp with custom time-warp getter
Copy construction that performs a shallow copy
Copy-assignment that performs a shallow copy
Move-construction
Move-assignment
Assignment from a literal play rate
Equality-comparison
Inequality-comparison
Return a shallow copy of this variant via bit-wise copy. If the contained type is a custom object, the object ptr will be copied directly
Return a deep copy of this variant. If the contained type is a custom object, the object will be duplicated into the new outer, otherwise a bitwise copy is performed.
If this variant wraps a UMovieSceneTimeWarpGetter, turn it into an unsafe weak reference.
Warning
: This will result in a dangling pointer if it is not referenced strongly elsewhere. Use with caution.
Remap the specified time using this time-warp
Parameters
InTime The time to remap
Returns
The time-warped time
Retrieve the type of this variant as an enumeration
Make this time-warp play at a constant play-rate
Make this time-warp always return a fixed frame number
Make this time-warp transform from one frame rate to another
Make this time-warp loop within the specified bounds
Make this time-warp clamp to the specified bounds
Make this time-warp loop within the specified bounds
Make this time-warp clamp to the specified bounds
Make this time-warp a custom dynamic value
Scale this time-warp by a factor
Definition at line 49 of file MovieSceneTimeWarpVariant.h.
References A, Ar, B, BlueprintType, Buffer, DeepCopy, GENERATED_BODY, HasNativeBreak, HasNativeMake, InTime, meta, MoveTemp(), NoInit, operator!=(), operator=(), operator==(), Other, Parent, PLATFORM_LITTLE_ENDIAN, and UPROPERTY.