Unreal Engine 5.6 C++ API: Runtime/MovieScene/Public/Channels/MovieSceneDoubleChannel.h File Reference
MovieSceneDoubleChannel.h File Reference
#include "Channels/MovieSceneCurveChannelCommon.h"
#include "Containers/Array.h"
#include "Containers/ArrayView.h"
#include "Containers/EnumAsByte.h"
#include "CoreTypes.h"
#include "Curves/KeyHandle.h"
#include "Curves/RealCurve.h"
#include "Curves/RichCurve.h"
#include "HAL/PlatformCrt.h"
#include "KeyParams.h"
#include "Math/Range.h"
#include "Misc/FrameNumber.h"
#include "Misc/FrameRate.h"
#include "Misc/FrameTime.h"
#include "Misc/Optional.h"
#include "MovieSceneChannel.h"
#include "MovieSceneChannelData.h"
#include "MovieSceneChannelTraits.h"
#include "Serialization/StructuredArchive.h"
#include "Templates/Tuple.h"
#include "Templates/UnrealTemplate.h"
#include "UObject/Class.h"
#include "UObject/ObjectMacros.h"
#include "Misc/EnumClassFlags.h"
#include "MovieSceneDoubleChannel.generated.h"
Data Structures
struct TIsPODType< FMovieSceneDoubleValue >
struct TMovieSceneChannelTraits< FMovieSceneDoubleChannel >
struct TStructOpsTypeTraits< FMovieSceneDoubleChannel >
struct TStructOpsTypeTraits< FMovieSceneDoubleValue >
Namespaces
namespace UE
Utility functions for applying transformations to meshes.
namespace UE::MovieScene
namespace UE::MovieScene::Interpolation
This file contains structures that represent specific interpolation algorithms for either a continuous or discrete range.
Functions
MOVIESCENE_API FKeyHandle AddKeyToChannel (FMovieSceneDoubleChannel *Channel, FFrameNumber InFrameNumber, double InValue, EMovieSceneKeyInterpolation Interpolation)
Overload for adding a new key to a double channel at a given time.
MOVIESCENE_API void AssignValue (FMovieSceneDoubleChannel *InChannel, FKeyHandle InKeyHandle, double InValue)
MOVIESCENE_API void AssignValue (FMovieSceneDoubleChannel *InChannel, FKeyHandle InKeyHandle, float InValue)
MOVIESCENE_API void Dilate (FMovieSceneDoubleChannel *InChannel, FFrameNumber Origin, double DilationFactor)
Overload for dilating double channel data.
MOVIESCENE_API EMovieSceneKeyInterpolation GetInterpolationMode (FMovieSceneDoubleChannel *InChannel, const FFrameNumber &InTime, EMovieSceneKeyInterpolation DefaultInterpolationMode)
Overload for getting the interpolation mode for a channel at a specified time, it could be the previous key's mode.See UE::MovieScene::GetInterpolationMode for default implementation.
MOVIESCENE_API void InvertValue (double &InOutValue)
MOVIESCENE_API void InvertValue (float &InOutValue)
MOVIESCENE_API void UE::MovieScene::OnRemapChannelKeyTime (const FMovieSceneChannel *Channel, const IRetimingInterface &Retimer, FFrameNumber PreviousTime, FFrameNumber CurrentTime, FMovieSceneDoubleValue &InOutValue)
USTRUCT () struct FMovieSceneDoubleValue
MOVIESCENE_API bool ValueExistsAtTime (const FMovieSceneDoubleChannel *InChannel, FFrameNumber InFrameNumber, const FMovieSceneDoubleValue &InValue)
Overloads for common utility functions.
MOVIESCENE_API bool ValueExistsAtTime (const FMovieSceneDoubleChannel *InChannel, FFrameNumber InFrameNumber, double Value)
MOVIESCENE_API bool ValueExistsAtTime (const FMovieSceneDoubleChannel *InChannel, FFrameNumber InFrameNumber, float Value)
Function Documentation
AddKeyToChannel()
MOVIESCENE_API FKeyHandle AddKeyToChannel (FMovieSceneDoubleChannel * Channel, FFrameNumber InFrameNumber, double InValue, EMovieSceneKeyInterpolation Interpolation)
Overload for adding a new key to a double channel at a given time.
See UE::MovieScene::AddKeyToChannel for default implementation.
References Interpolation.
Referenced by Sequencer::AddKeyForExternalValue(), Sequencer::AddOrUpdateKey(), TAddKeyImpl< ChannelType, ValueType >::Apply(), TAddKeyImpl< FMovieSceneBoolChannel, bool >::Apply(), TAddKeyImpl< FMovieSceneDoubleChannel, double >::Apply(), TAddKeyImpl< FMovieSceneFloatChannel, float >::Apply(), and TAddKeyImpl< FMovieSceneIntegerChannel, int32 >::Apply().
AssignValue() [1/2]
MOVIESCENE_API void AssignValue (FMovieSceneDoubleChannel * InChannel, FKeyHandle InKeyHandle, double InValue)
Referenced by MovieSceneImpl::TChannelValueHelper< ChannelType, ValueType >::SetKeyFromUserValue().
AssignValue() [2/2]
MOVIESCENE_API void AssignValue (FMovieSceneDoubleChannel * InChannel, FKeyHandle InKeyHandle, float InValue)
Dilate()
MOVIESCENE_API void Dilate (FMovieSceneDoubleChannel * InChannel, FFrameNumber Origin, double DilationFactor)
Overload for dilating double channel data.
See UE::MovieScene::Dilate for default implementation.
References Origin.
GetInterpolationMode()
MOVIESCENE_API EMovieSceneKeyInterpolation GetInterpolationMode (FMovieSceneDoubleChannel * InChannel, const FFrameNumber & InTime, EMovieSceneKeyInterpolation DefaultInterpolationMode)
Overload for getting the interpolation mode for a channel at a specified time, it could be the previous key's mode.See UE::MovieScene::GetInterpolationMode for default implementation.
References InTime.
Referenced by Sequencer::AddKeyForExternalValue(), Sequencer::AddOrUpdateKey(), TAddKeyImpl< ChannelType, ValueType >::Apply(), TAddKeyImpl< FMovieSceneBoolChannel, bool >::Apply(), TAddKeyImpl< FMovieSceneDoubleChannel, double >::Apply(), TAddKeyImpl< FMovieSceneFloatChannel, float >::Apply(), TAddKeyImpl< FMovieSceneIntegerChannel, int32 >::Apply(), and GetTimeWarpMode().
InvertValue() [1/2]
MOVIESCENE_API void InvertValue (double & InOutValue)
InvertValue() [2/2]
MOVIESCENE_API void InvertValue (float & InOutValue)
USTRUCT()
USTRUCT ()
double value = 8 bytes tangent data = 4 floats + byte enum = 4*4 + 1 = 17 bytes, rounded up to 20 bytes on clang-win64 interp and tangent modes = 2 byte enums = 2 bytes total = 30 bytes
Definition at line 51 of file MovieSceneDoubleChannel.h.
References Ar, Category, GENERATED_BODY, operator!=(), operator<<(), operator==(), Other, FArchive::Serialize(), Tangent, UPROPERTY, and Value.
ValueExistsAtTime() [1/3]
MOVIESCENE_API bool ValueExistsAtTime (const FMovieSceneDoubleChannel * InChannel, FFrameNumber InFrameNumber, const FMovieSceneDoubleValue & InValue)
Overloads for common utility functions.
Referenced by TAddKeyImpl< ChannelType, ValueType >::Apply(), TAddKeyImpl< FMovieSceneBoolChannel, bool >::Apply(), TAddKeyImpl< FMovieSceneDoubleChannel, double >::Apply(), TAddKeyImpl< FMovieSceneFloatChannel, float >::Apply(), and TAddKeyImpl< FMovieSceneIntegerChannel, int32 >::Apply().
ValueExistsAtTime() [2/3]
MOVIESCENE_API bool ValueExistsAtTime (const FMovieSceneDoubleChannel * InChannel, FFrameNumber InFrameNumber, double Value)
References Value.
ValueExistsAtTime() [3/3]
MOVIESCENE_API bool ValueExistsAtTime (const FMovieSceneDoubleChannel * InChannel, FFrameNumber InFrameNumber, float Value)
References Value.