Unreal Engine 5.6 C++ API: Runtime/MovieScene/Public/Evaluation/MovieSceneEvalTemplate.h File Reference
MovieSceneEvalTemplate.h File Reference
#include "CoreMinimal.h"
#include "CoreTypes.h"
#include "Evaluation/MovieSceneCompletionMode.h"
#include "Evaluation/MovieSceneEvalTemplateBase.h"
#include "Evaluation/MovieSceneExecutionTokens.h"
#include "Evaluation/MovieScenePlayback.h"
#include "Evaluation/PersistentEvaluationData.h"
#include "Math/Range.h"
#include "Misc/AssertionMacros.h"
#include "Misc/FrameNumber.h"
#include "Misc/FrameTime.h"
#include "Misc/InlineValue.h"
#include "MovieSceneSection.h"
#include "Templates/Decay.h"
#include "Templates/EnableIf.h"
#include "Templates/PointerIsConvertibleFromTo.h"
#include "Templates/UnrealTemplate.h"
#include "Templates/UnrealTypeTraits.h"
#include "UObject/Class.h"
#include "UObject/ObjectMacros.h"
#include "UObject/WeakObjectPtr.h"
#include "UObject/WeakObjectPtrTemplates.h"
#include "MovieSceneEvalTemplate.generated.h"
Data Structures
struct TStructOpsTypeTraits< FMovieSceneEvalTemplatePtr >
Functions
USTRUCT() struct FMovieSceneEvalTemplate USTRUCT () struct FMovieSceneEvalTemplatePtr
Structure used for movie scene evaluation templates contained within a track.
Function Documentation
USTRUCT()
USTRUCT() struct FMovieSceneEvalTemplate USTRUCT ()
Structure used for movie scene evaluation templates contained within a track.
Typically these are defined as one per-section. Serialized into a FMovieSceneEvaluationTemplate contained within the sequence itself (for fast initialization at runtime). Templates are executed in a 3-phase algorithm: 1) Initialize: (opt-in) Called at the start of the frame. Able to access mutable state from the playback context. Used to initialize any persistent state required for the evaluation pass. 2) Evaluate: Potentially called on a thread. Should (where possible) perform all costly evaluation logic, accumulating into execution tokens which will be executed at a later time on the game thread. 3) Execute: Called on all previously submitted execution tokens to apply the evaluated state to the movie scene player Custom serialized type that allows serializing structs derived from FMovieSceneEvalTemplate, and attempts to store an evaluation template in inline memory if possible
Default construction to an empty container
Construction from any FMovieSceneEvalTemplate derivative
Copy construction/assignment
Templates are moveable
Serialize the template
Definition at line 209 of file MovieSceneEvalTemplate.h.
References Ar, checkf, UScriptStruct::ICppStructOps::Construct(), UScriptStruct::ICppStructOps::Copy(), Forward(), GENERATED_BODY, UScriptStruct::ICppStructOps::GetAlignment(), UScriptStruct::ICppStructOps::GetSize(), operator=(), Reset, TEXT, USTRUCT, and Value.