Unreal Engine 5.6 C++ API: Runtime/MovieScene/Public/Evaluation/MovieSceneSegment.h File Reference
MovieSceneSegment.h File Reference
#include "CoreMinimal.h"
#include "Misc/FrameTime.h"
#include "UObject/ObjectMacros.h"
#include "UObject/Class.h"
#include "Containers/ArrayView.h"
#include "UObject/SequencerObjectVersion.h"
#include "MovieSceneFrameMigration.h"
#include "MovieSceneSegment.generated.h"
Data Structures
struct TStructOpsTypeTraits< FMovieSceneSegment >
struct TStructOpsTypeTraits< FMovieSceneSegmentIdentifier >
Functions
UENUM() enum class ESectionEvaluationFlags ENUM_CLASS_FLAGS (ESectionEvaluationFlags)
Enumeration specifying how to evaluate a particular section when inside a segment.
USTRUCT () struct FMovieSceneSegmentIdentifier
A unique identifier for a segment within a FMovieSceneEvaluationTrackSegments container.
Function Documentation
ENUM_CLASS_FLAGS()
UENUM() enum class ESectionEvaluationFlags ENUM_CLASS_FLAGS (ESectionEvaluationFlags)
Enumeration specifying how to evaluate a particular section when inside a segment.
USTRUCT()
USTRUCT ()
A unique identifier for a segment within a FMovieSceneEvaluationTrackSegments container.
Information about a single segment of an evaluation track.
Evaluation data that specifies information about what to evaluate for a given template.
Custom serializer as this is just a type-safe int
Default constructor
Construction from an implementaiton index (probably a section)
Construction from an implementaiton index and a time to force evaluation at
Construction from an implementaiton index and custom eval flags
Check if this is a preroll eval
Check if this is a postroll eval
The implementation index we should evaluate (index into FMovieSceneEvaluationTrack::ChildTemplates)
A forced time to evaluate this section at
Additional flags for evaluating this section
Custom serializer to accomodate the inline allocator on our array
The segment's range
Whether this segment has been generated yet or not
Array of implementations that reside at the segment's range
Definition at line 33 of file MovieSceneSegment.h.
References A, Ar, B, GENERATED_BODY, GetTypeHash(), ID, INDEX_NONE, IsValid(), operator!=(), operator<<(), operator==(), and UPROPERTY.