Unreal Engine 5.6 C++ API: Runtime/MovieScene/Public/Evaluation/Blending/MovieSceneBlendType.h File Reference
MovieSceneBlendType.h File Reference
#include "CoreMinimal.h"
#include "HAL/Platform.h"
#include "Misc/AssertionMacros.h"
#include "Stats/Stats.h"
#include "UObject/Class.h"
#include "UObject/ObjectMacros.h"
#include "MovieSceneBlendType.generated.h"
Data Structures
struct FMovieSceneBlendTypeField
Type that specifies a set of blend types that are supported for a particular section.
struct FMovieSceneBlendTypeFieldIterator
Functions
MOVIESCENE_API FMovieSceneBlendTypeFieldIterator begin (const FMovieSceneBlendTypeField &Field)
MOVIESCENE_API FMovieSceneBlendTypeFieldIterator end (const FMovieSceneBlendTypeField &Field)
UENUM() enum class EMovieSceneBlendType USTRUCT () struct FOptionalMovieSceneBlendType
Movie scene blend type enumeration.
Function Documentation
begin()
MOVIESCENE_API FMovieSceneBlendTypeFieldIterator begin (const FMovieSceneBlendTypeField & Field)
Referenced by UE::GC::FPrefetchingObjectIterator::FPrefetchingObjectIterator(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), and USTRUCT().
end()
MOVIESCENE_API FMovieSceneBlendTypeFieldIterator end (const FMovieSceneBlendTypeField & Field)
Referenced by FGainMatrix::FGainMatrix(), UE::GC::FPrefetchingObjectIterator::FPrefetchingObjectIterator(), GetTypeHash(), FGainMatrix::Lerp(), operator==(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), and USTRUCT().
USTRUCT()
UENUM() enum class EMovieSceneBlendType USTRUCT ()
Movie scene blend type enumeration.
Optional blend type structure
Assignment from a EMovieSceneBlendType enumeration
Check if this blend type has been set
Get this blend type. Must have been set to a valid enumeration.
The actual blend type
Boolean indicating whether BlendType is valid
Definition at line 36 of file MovieSceneBlendType.h.
References A, B, BlueprintType, Category, check, GENERATED_BODY, IsValid(), operator=(), operator==(), and UPROPERTY.