Unreal Engine 5.6 C++ API: Runtime/MovieScene/Public/Evaluation/MovieSceneTimeWarping.h File Reference
MovieSceneTimeWarping.h File Reference
#include "Containers/UnrealString.h"
#include "CoreMinimal.h"
#include "HAL/Platform.h"
#include "Math/Range.h"
#include "Math/RangeBound.h"
#include "Misc/AssertionMacros.h"
#include "Misc/FrameNumber.h"
#include "Misc/FrameTime.h"
#include "MovieSceneTimeTransform.h"
#include "UObject/ObjectMacros.h"
#include "MovieSceneTimeWarping.generated.h"
Functions
FString LexToString (const FMovieSceneTimeWarping &InWarping)
Convert a FMovieSceneTimeWarping into a string.
PRAGMA_DISABLE_DEPRECATION_WARNINGS FFrameNumber operator* (FFrameNumber InFrame, const FMovieSceneTimeWarping &RHS)
FFrameTime operator* (FFrameTime InTime, const FMovieSceneTimeWarping &RHS)
FFrameNumber & operator*= (FFrameNumber &InFrame, const FMovieSceneTimeWarping &RHS)
FFrameTime & operator*= (FFrameTime &InTime, const FMovieSceneTimeWarping &RHS)
USTRUCT () struct FMovieSceneTimeWarping
Transform time by warping it around from end to start.
Function Documentation
LexToString()
FString LexToString (const FMovieSceneTimeWarping & InWarping) inline
Convert a FMovieSceneTimeWarping into a string.
Definition at line 307 of file MovieSceneTimeWarping.h.
References TEXT.
operator*() [1/2]
PRAGMA_DISABLE_DEPRECATION_WARNINGS FFrameNumber operator* (FFrameNumber InFrame, const FMovieSceneTimeWarping & RHS) inline
Definition at line 139 of file MovieSceneTimeWarping.h.
References checkSlow.
operator*() [2/2]
FFrameTime operator* (FFrameTime InTime, const FMovieSceneTimeWarping & RHS) inline
Definition at line 146 of file MovieSceneTimeWarping.h.
References checkSlow, and InTime.
operator*=() [1/2]
FFrameNumber & operator*= (FFrameNumber & InFrame, const FMovieSceneTimeWarping & RHS) inline
Definition at line 153 of file MovieSceneTimeWarping.h.
operator*=() [2/2]
FFrameTime & operator*= (FFrameTime & InTime, const FMovieSceneTimeWarping & RHS) inline
Definition at line 159 of file MovieSceneTimeWarping.h.
References InTime.
USTRUCT()
USTRUCT ()
Transform time by warping it around from end to start.
This is mostly useful for looping things.
Returns the length of the warping.
Returns whether this warping transform is doing anything.
Returns a range that encompasses the whole warping time span.
Returns a transformation that takes us from a local time into a given loop back to the root time.
Transforms the given frame and returns the warped frame time along with the warp index we ended up in.
Transforms the given time and returns the warped time along with the warp index we ended up in.
Transforms the given time by warping it by a specific warp count, regardless of how many warps are needed in theory to stay in the warping range.
Transforms the given range in a "naive" way, i.e. its lower and upper bounds are transformed independently by this time warping. This means that the output range could be "inside-out"... that is, the output lower bound could be greater than the output upper bound, like, for instance, in the case of the input range starting near the end of a loop, and ending near the beginning of another loop.
Transforms the given range by time-warping its lower bound, and computing an upper bound so that the size of the input range is preserved. So if the input range starts in the middle of a loop and lasts 3 loops, the output range will start in the middle of the first loop, and last 3 times as long as the Length of this time warp.
Transforms the given range by time-warping it and figuring out if it "covered" a full loop or not. If it covered a full loop, return a full-loop range, i.e. a range that goes from StartOffset to (Length - EndOffset). If it didn't cover a full loop, return the transformed range, which should be a subset of the full loop range mentioned above.
Definition at line 22 of file MovieSceneTimeWarping.h.
References A, B, check, End, TRangeBound< ElementType >::Exclusive(), GENERATED_BODY, TRangeBound< ElementType >::Inclusive(), InTime, IsValid(), operator!=(), operator==(), UE_DEPRECATED, and UPROPERTY.