Unreal Engine 5.6 C++ API: S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/Harmonix/Source/HarmonixMetasound/Public/HarmonixMetasound/Utils/MusicTempometerUtilities.h File Reference
MusicTempometerUtilities.h File Reference
#include "MusicTempometerUtilities.generated.h"
Namespaces
namespace MusicTempometerUtilities
Utility methods used by the UMusicTempometerComponent, also publically exposed for other systems to use.
Functions
void HARMONIXMETASOUND_API MusicTempometerUtilities::UpdateMaterialParameterCollectionFromClock (const UObject *InWorldContextObject, TWeakObjectPtr< UMaterialParameterCollectionInstance > &InOutMaterialParameterCollectionInstance, const TObjectPtr< UMaterialParameterCollection > &InMaterialParameterCollection, const FMusicTempometerMPCParameters &InMCPParameters, const UMusicClockComponent *InClockComponent)
Update the supplied material parameter collection instance (create if null) with song position data extracted from the supplied clock.
void HARMONIXMETASOUND_API MusicTempometerUtilities::UpdateMaterialParameterCollectionFromSongPos (const UObject *InWorldContextObject, TWeakObjectPtr< UMaterialParameterCollectionInstance > &InOutMaterialParameterCollectionInstance, const TObjectPtr< UMaterialParameterCollection > &InMaterialParameterCollection, const FMusicTempometerMPCParameters &InMCPParameters, const FMidiSongPos &InMidiSongPos)
Update the supplied material parameter collection instance (create if null) with data from the supplied song position.
USTRUCT () struct FMusicTempometerMPCParameters
Parameters used when creating/updating the corresponding Material Parameter Collection.
Function Documentation
USTRUCT()
USTRUCT ()
Parameters used when creating/updating the corresponding Material Parameter Collection.
Seconds from the beginning of the entire music authoring. Includes all count-in and pickup bars (ie. won't be negative when the music starts, and bar 1 beat 1 may not be at 0.0 seconds!
Bars from the beginning of the music. Includes all count-in and pickup bars (ie. won't be negative when the music starts, and bar 1 beat 1 of the music may not be equal to elapsed bar 0.0! NOTE: This Bar, unlike the Bar in the MusicTimestamp structure, is floating point and will include a fractional portion.
Total Beats from the beginning of the music. Includes all count-in and pickup bars/beats (ie. won't be negative when the music starts, and elapsed beat 0.0 may not equal a timestamp of bar 1 beat 1!
Seconds from Bar 1 Beat 1 of the music. If the music has a count-in or pickup bars this number may be negative when the music starts!
This is the bar member of the MusicTimestamp structure which represents a classic "music time" where bar 1 beat 1 is the beginning of the music AFTER count-in and pickups. If the music has a count-in or pickup bars this number may be negative (or zero) until bar 1 beat 1 is reached! NOTE: Unlike "BarsFromCountIn", Bar here will be an integer! This because it is the bar from the MusicTimestamp structure which also provides a "beat in bar" member to denote a "distance into the bar".
This is the beat member of the MusicTimestamp structure which represents a classic "music time" where bar 1 beat 1 is the beginning of the music AFTER count-in and pickups. If the music has a count-in or pickup bars this number may be negative (or zero) until bar 1 beat 1 is reached! NOTE: beat in this context is 1 based! The first beat in a bar is beat 1! Note: This is a floating point number.
Progress of the current bar [0, 1]. This is the same as the fractional part of BarsFromCountIn.
Progress of the current beat [0, 1]. This is the same as the fractional part of BeatsFromCountIn;
Current time signature numerator (beats per bar).
Current time signature denominator (scale from note duration to beat).
Current tempo (beats per minute).
0 or 1, represents whether the rest of the parameters are defaults (0) or the current state of a clock (1).
Definition at line 13 of file MusicTempometerUtilities.h.
References BlueprintType, Category, GENERATED_BODY, FName::IsNone(), IsValid(), operator!=(), operator==(), Other, and UPROPERTY.