Unreal Engine 5.6 C++ API: UE::SculptFalloffs Namespace Reference
UE::SculptFalloffs Namespace Reference
Functions
static TUniqueFunction< double(const FSculptBrushStamp &, const FVector3d &)> MakeInverseBoxFalloff ()
static TUniqueFunction< double(const FSculptBrushStamp &, const FVector3d &)> MakeInverseFalloff ()
static TUniqueFunction< double(const FSculptBrushStamp &, const FVector3d &)> MakeLinearBoxFalloff ()
static TUniqueFunction< double(const FSculptBrushStamp &, const FVector3d &)> MakeLinearFalloff ()
static TUniqueFunction< double(const FSculptBrushStamp &, const FVector3d &)> MakeRoundBoxFalloff ()
static TUniqueFunction< double(const FSculptBrushStamp &, const FVector3d &)> MakeRoundFalloff ()
static TUniqueFunction< double(const FSculptBrushStamp &, const FVector3d &)> MakeSmoothBoxFalloff ()
static TUniqueFunction< double(const FSculptBrushStamp &, const FVector3d &)> MakeStandardSmoothFalloff ()
Function Documentation
MakeInverseBoxFalloff()
TUniqueFunction< double(const FSculptBrushStamp &, const FVector3d &)> UE::SculptFalloffs::MakeInverseBoxFalloff () static
Definition at line 182 of file StampFalloffs.h.
References UE::Geometry::Box, TMathUtil< double >::Clamp(), FSculptBrushStamp::Falloff, TMathUtilConstants< double >::InvSqrt2, FSculptBrushStamp::LocalFrame, UE::Geometry::Position, FSculptBrushStamp::Radius, TMathUtil< double >::Sqrt(), UE::Geometry::TFrame3< RealType >::ToFramePoint(), and UE::Math::TVector< double >::Zero().
MakeInverseFalloff()
TUniqueFunction< double(const FSculptBrushStamp &, const FVector3d &)> UE::SculptFalloffs::MakeInverseFalloff () static
Definition at line 54 of file StampFalloffs.h.
References TMathUtil< double >::Clamp(), Distance, FSculptBrushStamp::Falloff, FSculptBrushStamp::LocalFrame, UE::Geometry::TFrame3< RealType >::Origin, UE::Geometry::Position, FSculptBrushStamp::Radius, and Weight.
MakeLinearBoxFalloff()
TUniqueFunction< double(const FSculptBrushStamp &, const FVector3d &)> UE::SculptFalloffs::MakeLinearBoxFalloff () static
Definition at line 122 of file StampFalloffs.h.
References UE::Geometry::Box, TMathUtil< double >::Clamp(), FSculptBrushStamp::Falloff, TMathUtilConstants< double >::InvSqrt2, FSculptBrushStamp::LocalFrame, UE::Geometry::Position, FSculptBrushStamp::Radius, TMathUtil< double >::Sqrt(), UE::Geometry::TFrame3< RealType >::ToFramePoint(), and UE::Math::TVector< double >::Zero().
MakeLinearFalloff()
TUniqueFunction< double(const FSculptBrushStamp &, const FVector3d &)> UE::SculptFalloffs::MakeLinearFalloff () static
Definition at line 34 of file StampFalloffs.h.
References TMathUtil< double >::Clamp(), Distance, FSculptBrushStamp::Falloff, FSculptBrushStamp::LocalFrame, UE::Geometry::TFrame3< RealType >::Origin, UE::Geometry::Position, FSculptBrushStamp::Radius, and Weight.
MakeRoundBoxFalloff()
TUniqueFunction< double(const FSculptBrushStamp &, const FVector3d &)> UE::SculptFalloffs::MakeRoundBoxFalloff () static
Definition at line 152 of file StampFalloffs.h.
References UE::Geometry::Box, TMathUtil< double >::Clamp(), FSculptBrushStamp::Falloff, TMathUtilConstants< double >::InvSqrt2, FSculptBrushStamp::LocalFrame, UE::Geometry::Position, FSculptBrushStamp::Radius, TMathUtil< double >::Sqrt(), UE::Geometry::TFrame3< RealType >::ToFramePoint(), and UE::Math::TVector< double >::Zero().
MakeRoundFalloff()
TUniqueFunction< double(const FSculptBrushStamp &, const FVector3d &)> UE::SculptFalloffs::MakeRoundFalloff () static
Definition at line 73 of file StampFalloffs.h.
References TMathUtil< double >::Clamp(), Distance, FSculptBrushStamp::Falloff, FSculptBrushStamp::LocalFrame, UE::Geometry::TFrame3< RealType >::Origin, UE::Geometry::Position, and FSculptBrushStamp::Radius.
MakeSmoothBoxFalloff()
TUniqueFunction< double(const FSculptBrushStamp &, const FVector3d &)> UE::SculptFalloffs::MakeSmoothBoxFalloff () static
Definition at line 91 of file StampFalloffs.h.
References UE::Geometry::Box, TMathUtil< double >::Clamp(), FSculptBrushStamp::Falloff, TMathUtilConstants< double >::InvSqrt2, FSculptBrushStamp::LocalFrame, UE::Geometry::Position, FSculptBrushStamp::Radius, TMathUtil< double >::Sqrt(), UE::Geometry::TFrame3< RealType >::ToFramePoint(), and UE::Math::TVector< double >::Zero().
MakeStandardSmoothFalloff()
TUniqueFunction< double(const FSculptBrushStamp &, const FVector3d &)> UE::SculptFalloffs::MakeStandardSmoothFalloff () static
Definition at line 15 of file StampFalloffs.h.
References TMathUtil< double >::Clamp(), Distance, FSculptBrushStamp::Falloff, FSculptBrushStamp::LocalFrame, UE::Geometry::TFrame3< RealType >::Origin, UE::Geometry::Position, FSculptBrushStamp::Radius, and Weight.