Unreal Engine 5.6 C++ API: Sequencer Namespace Reference
Sequencer Namespace Reference
Stub/default implementations for ISequencerChannelInterface functions.
Data Structures
struct CLegacyCurveModelCreatable
Concept for detecting deprecated CreateCurveEditorModel signatures that will no longer be called in later versions.
struct CLegacyKeyEditorCreatable
Functions
template<typename ChannelType, typename ValueType>
TOptional< FKeyHandle > AddKeyForExternalValue (ChannelType *InChannel, const TMovieSceneExternalValue< ValueType > &InExternalValue, FFrameNumber InTime, ISequencer &InSequencer, const FGuid &InObjectBindingID, FTrackInstancePropertyBindings *InPropertyBindings)
Retrieve a channel's external value, and add it to the channel as a new key (or update an existing key with its value)
template<typename ChannelType>
FKeyHandle AddOrUpdateKey (ChannelType *InChannel, UMovieSceneSection *InSectionToKey, FFrameNumber InTime, ISequencer &InSequencer, const FGuid &InObjectBindingID, FTrackInstancePropertyBindings *InPropertyBindings)
Add or update a key for this channel's current value.
template<typename ChannelType, typename ValueType>
FKeyHandle AddOrUpdateKey (ChannelType *InChannel, UMovieSceneSection *SectionToKey, const TMovieSceneExternalValue< ValueType > &InExternalValue, FFrameNumber InTime, ISequencer &InSequencer, const FGuid &InObjectBindingID, FTrackInstancePropertyBindings *InPropertyBindings)
Add or update a key for this channel's current value, using an external value if possible.
bool CanCreateKeyEditor (const FMovieSceneChannel *InChannel)
Check whether the specified channel can create a key editor widget that should be placed on the sequencer node tree.
template<typename ChannelType>
void CopyKeys (ChannelType *InChannel, const UMovieSceneSection *InSection, FName KeyAreaName, FMovieSceneClipboardBuilder &ClipboardBuilder, TArrayView< const FKeyHandle > InHandles)
Copy the specified keys from a channel.
TSharedPtr< UE::Sequencer::FChannelModel > CreateChannelModel (const FMovieSceneChannelHandle &InChannelHandle, const UE::Sequencer::FSectionModel &InSection, FName InChannelName)
Create a new channel model for this type of channel.
TSharedPtr< UE::Sequencer::STrackAreaLaneView > CreateChannelView (const FMovieSceneChannelHandle &InChannelHandle, TWeakPtr< UE::Sequencer::FChannelModel > InWeakModel, const UE::Sequencer::FCreateTrackLaneViewParams &Parameters)
Create a new channel view for this type of channel.
SEQUENCER_API TUniquePtr< FCurveModel > CreateCurveEditorModel (const FMovieSceneChannelHandle &ChannelHandle, const UE::Sequencer::FCreateCurveEditorModelParams &Params)
Create a new model for the specified channel that can be used on the curve editor interface.
TSharedRef< SWidget > CreateKeyEditor (const FMovieSceneChannelHandle &InChannel, const UE::Sequencer::FCreateKeyEditorParams &Params)
Create a key editor widget for the specified channel with the channel's specialized editor data.
template<typename ChannelType>
TEnableIf< TMovieSceneChannelTraits< ChannelType >::SupportsDefaults >::Type DeleteKeys (ChannelType *InChannel, TArrayView< const FKeyHandle > InHandles, FFrameNumber InTime)
Delete the specified keys.
template<typename ChannelType>
TEnableIf<!TMovieSceneChannelTraits< ChannelType >::SupportsDefaults >::Type DeleteKeys (ChannelType *InChannel, TArrayView< const FKeyHandle > InHandles, FFrameNumber InTime)
SEQUENCER_API int32 DrawExtra (FMovieSceneChannel *InChannel, const UMovieSceneSection *InOwner, const FSequencerChannelPaintArgs &PaintArgs, int32 LayerId)
Draw additional content in addition to keys for a particular channel.
SEQUENCER_API void DrawKeys (FMovieSceneChannel *Channel, TArrayView< const FKeyHandle > InHandles, const UMovieSceneSection *InOwner, TArrayView< FKeyDrawParams > OutKeyDrawParams)
Gather key draw information from a channel for a specific set of keys.
template<typename ChannelType, typename ValueType>
FKeyHandle EvaluateAndAddKey (ChannelType *InChannel, const TMovieSceneChannelData< ValueType > &InChannelData, FFrameNumber InTime, ISequencer &InSequencer, ValueType InDefaultValue=ValueType{})
Add a key at the specified time (or update an existing key) with the channel's current value at that time.
template<typename ChannelType>
void ExtendKeyMenu (FMenuBuilder &MenuBuilder, TSharedPtr< FExtender > MenuExtender, TArray< TExtendKeyMenuParams< ChannelType > > &&InChannels, TWeakPtr< ISequencer > InSequencer)
Extend the specified selected key context menu.
template<typename ChannelType>
void ExtendSectionMenu (FMenuBuilder &MenuBuilder, TSharedPtr< FExtender > InMenuExtender, TArray< TMovieSceneChannelHandle< ChannelType > > &&InChannels, const TArray< TWeakObjectPtr< UMovieSceneSection > > &InWeakSections, TWeakPtr< ISequencer > InWeakSequencer)
Extend the specified selected section context menu.
template<typename ChannelType>
TSharedPtr< ISidebarChannelExtension > ExtendSidebarMenu (FMenuBuilder &MenuBuilder, TSharedPtr< FExtender > InMenuExtender, TArray< TMovieSceneChannelHandle< ChannelType > > &&InChannels, const TArray< TWeakObjectPtr< UMovieSceneSection > > &InWeakSections, TWeakPtr< ISequencer > InWeakSequencer)
Extend the specified selected sidebar menu.
template<typename ChannelType>
TSharedPtr< FStructOnScope > GetKeyStruct (const TMovieSceneChannelHandle< ChannelType > &ChannelHandle, FKeyHandle KeyHandle)
Get a transient key structure that can be added to a details panel to enable editing of a single key.
template<typename ChannelType>
void PasteKeys (ChannelType *InChannel, UMovieSceneSection *Section, const FMovieSceneClipboardKeyTrack &KeyTrack, const FMovieSceneClipboardEnvironment &SrcEnvironment, const FSequencerPasteEnvironment &DstEnvironment, TArray< FKeyHandle > &OutPastedKeys)
Paste the clipboard contents onto a channel.
bool ShouldShowCurve (const FMovieSceneChannel *Channel, UMovieSceneSection *InSection)
Whether this channel should draw a curve on its editor UI.
SEQUENCER_API bool SupportsCurveEditorModels (const FMovieSceneChannelHandle &ChannelHandle)
Whether the specified channel handle supports curve models or not.
template<typename T>
UE_DEPRECATED (5.5, "CreateCurveEditorModel(const TMovieSceneChannelHandle<T>&, UMovieSceneSection*, TSharedRef<ISequencer>) has been deprecated. Please update your signature to use FCreateCurveEditorModelParams") void CreateCurveEditorModelDeprecatedSignature()
template<typename T>
UE_DEPRECATED (5.5, "CreateKeyEditor(const TMovieSceneChannelHandle<T>&, UMovieSceneSection*, const FGuid&, TWeakPtr<FTrackInstancePropertyBindings>, TWeakPtr<ISequencer>); has been deprecated. Please update your signature to use FCreateKeyEditorParams") void CreateKeyEditorDeprecatedSignature()
Detailed Description
Stub/default implementations for ISequencerChannelInterface functions.
Custom behaviour should be implemented by overloading the relevant function with the necessary channel/data types. For example, to overload how to draw keys for FMyCustomChannelType, implement the following function in the same namespace as FMyCustomChannelType:
void DrawKeys(FMyCustomChannelType* Channel, TArrayView<const FKeyHandle> InHandles, TArrayView<FKeyDrawParams> OutKeyDrawParams) { ... }
Function Documentation
AddKeyForExternalValue()
template<typename ChannelType, typename ValueType> TOptional< FKeyHandle > Sequencer::AddKeyForExternalValue (ChannelType * InChannel, const TMovieSceneExternalValue< ValueType > & InExternalValue, FFrameNumber InTime, ISequencer & InSequencer, const FGuid & InObjectBindingID, FTrackInstancePropertyBindings * InPropertyBindings)
Retrieve a channel's external value, and add it to the channel as a new key (or update an existing key with its value)
Parameters
InChannel The channel to create a key for
InExternalValue The external value definition
InTime The time at which to add a key
InSequencer The currently active sequencer
InObjectBindingID The object binding ID that this section's track is bound to
InPropertyBindings Optionally supplied helper for accessing an object's property pertaining to this channel
Returns
(Optional) A handle to the added (or updated) key
Definition at line 223 of file SequencerChannelTraits.h.
References AddKeyToChannel(), IMovieScenePlayer::FindBoundObjects(), ISequencer::GetFocusedTemplateID(), GetInterpolationMode(), ISequencer::GetKeyInterpolation(), InTime, FGuid::IsValid(), Object, TMovieSceneExternalValue< T >::OnGetExternalValue, Value, and WeakObject.
Referenced by AddOrUpdateKey().
AddOrUpdateKey() [1/2]
template<typename ChannelType> FKeyHandle Sequencer::AddOrUpdateKey (ChannelType * InChannel, UMovieSceneSection * InSectionToKey, FFrameNumber InTime, ISequencer & InSequencer, const FGuid & InObjectBindingID, FTrackInstancePropertyBindings * InPropertyBindings)
Add or update a key for this channel's current value.
Parameters
InChannel The channel to create a key for
InSectionToKey The Section to key
InTime The time at which to add a key
InSequencer The currently active sequencer
InObjectBindingID The object binding ID that this section's track is bound to
InPropertyBindings Optionally supplied helper for accessing an object's property pertaining to this channel
Returns
A handle to the added (or updated) key
Definition at line 267 of file SequencerChannelTraits.h.
References EvaluateAndAddKey(), and InTime.
AddOrUpdateKey() [2/2]
template<typename ChannelType, typename ValueType> FKeyHandle Sequencer::AddOrUpdateKey (ChannelType * InChannel, UMovieSceneSection * SectionToKey, const TMovieSceneExternalValue< ValueType > & InExternalValue, FFrameNumber InTime, ISequencer & InSequencer, const FGuid & InObjectBindingID, FTrackInstancePropertyBindings * InPropertyBindings)
Add or update a key for this channel's current value, using an external value if possible.
Parameters
InChannel The channel to create a key for
InSectionToKey The Section to key
InExternalValue The external value definition
InTime The time at which to add a key
InSequencer The currently active sequencer
InObjectBindingID The object binding ID that this section's track is bound to
InPropertyBindings Optionally supplied helper for accessing an object's property pertaining to this channel
Returns
A handle to the added (or updated) key
Definition at line 293 of file SequencerChannelTraits.h.
References AddKeyForExternalValue(), AddKeyToChannel(), EvaluateChannel(), GetInterpolationMode(), ISequencer::GetKeyInterpolation(), Handle, and InTime.
CanCreateKeyEditor()
bool Sequencer::CanCreateKeyEditor (const FMovieSceneChannel * InChannel) inline
Check whether the specified channel can create a key editor widget that should be placed on the sequencer node tree.
Parameters
InChannel The channel to check
Returns
true if a key editor can be created, false otherwise
Definition at line 168 of file SequencerChannelTraits.h.
CopyKeys()
template<typename ChannelType> void Sequencer::CopyKeys (ChannelType * InChannel, const UMovieSceneSection * InSection, FName KeyAreaName, FMovieSceneClipboardBuilder & ClipboardBuilder, TArrayView< const FKeyHandle > InHandles)
Copy the specified keys from a channel.
Parameters
InChannel The channel to duplicate keys in
InSection The section that owns this channel
KeyAreaName The name of the key area representing this channel
ClipboardBuilder Structure for populating the clipboard
InHandles Array of key handles that should be copied
Definition at line 379 of file SequencerChannelTraits.h.
References FMovieSceneClipboardKeyTrack::AddKey(), FMovieSceneClipboardBuilder::FindOrAddKeyTrack(), Handle, and INDEX_NONE.
Referenced by TSequencerChannelInterfaceCommon< ChannelType >::CopyKeys_Raw().
CreateChannelModel()
TSharedPtr< UE::Sequencer::FChannelModel > Sequencer::CreateChannelModel (const FMovieSceneChannelHandle & InChannelHandle, const UE::Sequencer::FSectionModel & InSection, FName InChannelName) inline
Create a new channel model for this type of channel.
Parameters
InChannelHandle The channel handle to create a model for
InSectionModel The section that owns this channel model
InChannelName The identifying name of this channel
Returns
(Optional) A new model to be used as part of the Sequencer MVVM framework
Definition at line 474 of file SequencerChannelTraits.h.
CreateChannelView()
TSharedPtr< UE::Sequencer::STrackAreaLaneView > Sequencer::CreateChannelView (const FMovieSceneChannelHandle & InChannelHandle, TWeakPtr< UE::Sequencer::FChannelModel > InWeakModel, const UE::Sequencer::FCreateTrackLaneViewParams & Parameters) inline
Create a new channel view for this type of channel.
Parameters
InChannelHandle The channel handle to create a model for
InWeakModel The model that is creating the view. Should not be Pinned persistently.
Parameters View construction parameters
Returns
(Optional) A new view to be shown on the track area
Definition at line 487 of file SequencerChannelTraits.h.
Referenced by TSequencerChannelInterfaceCommon< ChannelType >::CreateChannelView_Raw().
CreateCurveEditorModel()
SEQUENCER_API TUniquePtr< FCurveModel > Sequencer::CreateCurveEditorModel (const FMovieSceneChannelHandle & ChannelHandle, const UE::Sequencer::FCreateCurveEditorModelParams & Params)
Create a new model for the specified channel that can be used on the curve editor interface.
Returns
(Optional) A new model to be added to a curve editor
References Params.
CreateKeyEditor()
TSharedRef< SWidget > Sequencer::CreateKeyEditor (const FMovieSceneChannelHandle & InChannel, const UE::Sequencer::FCreateKeyEditorParams & Params) inline
Create a key editor widget for the specified channel with the channel's specialized editor data.
Such widgets are placed on the sequencer node tree for a given key area node.
Parameters
InChannel The channel to create a key editor for
Params Creation parameters containing all the necessary structures for creating the key editor
Returns
The key editor widget
Definition at line 182 of file SequencerChannelTraits.h.
References SNullWidget::NullWidget, and Params.
DeleteKeys() [1/2]
template<typename ChannelType> TEnableIf< TMovieSceneChannelTraits< ChannelType >::SupportsDefaults >::Type Sequencer::DeleteKeys (ChannelType * InChannel, TArrayView< const FKeyHandle > InHandles, FFrameNumber InTime)
Delete the specified keys.
If all keys are removed, the current value at that time will be set as the default value for the channel
Parameters
Channel The channel to remove the keys from
InHandles The key handles to delete
InTime The time at which to evaluate for the default value if there are no keys remaining
Definition at line 346 of file SequencerChannelTraits.h.
References EvaluateChannel(), InTime, and Value.
Referenced by TSequencerChannelInterfaceCommon< ChannelType >::DeleteKeys_Raw().
DeleteKeys() [2/2]
template<typename ChannelType> TEnableIf<!TMovieSceneChannelTraits< ChannelType >::SupportsDefaults >::Type Sequencer::DeleteKeys (ChannelType * InChannel, TArrayView< const FKeyHandle > InHandles, FFrameNumber InTime)
Definition at line 364 of file SequencerChannelTraits.h.
References InTime.
DrawExtra()
SEQUENCER_API int32 Sequencer::DrawExtra (FMovieSceneChannel * InChannel, const UMovieSceneSection * InOwner, const FSequencerChannelPaintArgs & PaintArgs, int32 LayerId)
Draw additional content in addition to keys for a particular channel.
Parameters
InChannel The channel to draw extra display information for
InOwner The owning movie scene section for this channel
PaintArgs Paint arguments containing the draw element list, time-to-pixel converter and other structures
LayerId The slate layer to paint onto
Returns
The new slate layer ID for subsequent elements to paint onto
Referenced by TSequencerChannelInterfaceCommon< ChannelType >::DrawExtra_Raw().
DrawKeys()
SEQUENCER_API void Sequencer::DrawKeys (FMovieSceneChannel * Channel, TArrayView< const FKeyHandle > InHandles, const UMovieSceneSection * InOwner, TArrayView< FKeyDrawParams > OutKeyDrawParams)
Gather key draw information from a channel for a specific set of keys.
Parameters
InChannel The channel to draw keys
InHandles Array of key handles that should be displayed
InOwner The owning movie scene section for this channel
OutKeyDrawParams Array to receive key draw information. Must be exactly the size of InHandles
EvaluateAndAddKey()
template<typename ChannelType, typename ValueType> FKeyHandle Sequencer::EvaluateAndAddKey (ChannelType * InChannel, const TMovieSceneChannelData< ValueType > & InChannelData, FFrameNumber InTime, ISequencer & InSequencer, ValueType InDefaultValue = ValueType{})
Add a key at the specified time (or update an existing key) with the channel's current value at that time.
Parameters
InChannel The channel to create a key for
InChannelData The channel's data
InTime The time at which to add a key
InSequencer The currently active sequencer
InDefaultValue The default value to use if evaluation of the channel failed
Returns
A handle to the added (or updated) key
Definition at line 198 of file SequencerChannelTraits.h.
References InTime.
Referenced by AddOrUpdateKey().
ExtendKeyMenu()
template<typename ChannelType> void Sequencer::ExtendKeyMenu (FMenuBuilder & MenuBuilder, TSharedPtr< FExtender > MenuExtender, TArray< TExtendKeyMenuParams< ChannelType > > && InChannels, TWeakPtr< ISequencer > InSequencer)
Extend the specified selected key context menu.
Parameters
MenuBuilder The menu builder that will construct the section context menu
Channels An array of all channels that are currently selected, in no particular order
Sections An array of all sections that the selected channels reside in
InSequencer The sequencer that is currently active
Definition at line 145 of file SequencerChannelTraits.h.
ExtendSectionMenu()
template<typename ChannelType> void Sequencer::ExtendSectionMenu (FMenuBuilder & MenuBuilder, TSharedPtr< FExtender > InMenuExtender, TArray< TMovieSceneChannelHandle< ChannelType > > && InChannels, const TArray< TWeakObjectPtr< UMovieSceneSection > > & InWeakSections, TWeakPtr< ISequencer > InWeakSequencer)
Extend the specified selected section context menu.
Parameters
MenuBuilder The menu builder that will construct the section context menu
Channels An array of all channels that are currently selected, in no particular order
Sections An array of all sections that the selected channels reside in
InSequencer The sequencer that is currently active
Definition at line 110 of file SequencerChannelTraits.h.
ExtendSidebarMenu()
template<typename ChannelType> TSharedPtr< ISidebarChannelExtension > Sequencer::ExtendSidebarMenu (FMenuBuilder & MenuBuilder, TSharedPtr< FExtender > InMenuExtender, TArray< TMovieSceneChannelHandle< ChannelType > > && InChannels, const TArray< TWeakObjectPtr< UMovieSceneSection > > & InWeakSections, TWeakPtr< ISequencer > InWeakSequencer)
Extend the specified selected sidebar menu.
Parameters
MenuBuilder The menu builder that will construct the section context menu
InMenuExtender The extender for the menu
InChannels An array of all channels that are currently selected, in no particular order
InWeakSections An array of all sections that the selected channels reside in
InWeakSequencer The sequencer that is currently active
Definition at line 127 of file SequencerChannelTraits.h.
GetKeyStruct()
template<typename ChannelType> TSharedPtr< FStructOnScope > Sequencer::GetKeyStruct (const TMovieSceneChannelHandle< ChannelType > & ChannelHandle, FKeyHandle KeyHandle)
Get a transient key structure that can be added to a details panel to enable editing of a single key.
Parameters
ChannelHandle Handle to the channel in which the key resides
KeyHandle A handle to the key to edit
Returns
A shared struct object, or nullptr
Definition at line 157 of file SequencerChannelTraits.h.
References FSequencerKeyStructGenerator::CreateKeyStructInstance(), and FSequencerKeyStructGenerator::Get().
Referenced by TSequencerChannelInterfaceCommon< ChannelType >::GetKeyStruct_Raw().
PasteKeys()
template<typename ChannelType> void Sequencer::PasteKeys (ChannelType * InChannel, UMovieSceneSection * Section, const FMovieSceneClipboardKeyTrack & KeyTrack, const FMovieSceneClipboardEnvironment & SrcEnvironment, const FSequencerPasteEnvironment & DstEnvironment, TArray< FKeyHandle > & OutPastedKeys)
Paste the clipboard contents onto a channel.
Parameters
InChannel The channel to duplicate keys in
Section The section that owns this channel
KeyTrack The clipboard track to paste
SrcEnvironment The source clipboard environment that was originally copied
DstEnvironment The destination clipboard environment that we're copying to
OutPastedKeys Array of key handles that should receive any pasted keys
Definition at line 422 of file SequencerChannelTraits.h.
References TArray< InElementType, InAllocatorType >::Add(), FMovieSceneClipboardEnvironment::CardinalTime, TRange< ElementType >::Hull(), FMovieSceneClipboardKeyTrack::IterateKeys(), Key, FMovieSceneClipboardEnvironment::TickResolution, Time, FMovieSceneClipboardEnvironment::TimeTransform, and FFrameRate::TransformTime().
Referenced by TSequencerChannelInterfaceCommon< ChannelType >::PasteKeys_Raw().
ShouldShowCurve()
bool Sequencer::ShouldShowCurve (const FMovieSceneChannel * Channel, UMovieSceneSection * InSection) inline
Whether this channel should draw a curve on its editor UI.
Parameters
Channel The channel to query
InSection The section that owns the channel
Returns
true to show the curve on the UI, false otherwise
Definition at line 499 of file SequencerChannelTraits.h.
SupportsCurveEditorModels()
SEQUENCER_API bool Sequencer::SupportsCurveEditorModels (const FMovieSceneChannelHandle & ChannelHandle)
Whether the specified channel handle supports curve models or not.
UE_DEPRECATED() [1/2]
template<typename T> Sequencer::UE_DEPRECATED (5. 5, "CreateCurveEditorModel(const TMovieSceneChannelHandle<T>&, UMovieSceneSection*, TSharedRef<ISequencer>) has been deprecated. Please update your signature to use FCreateCurveEditorModelParams")
Definition at line 36 of file SequencerChannelInterface.h.
UE_DEPRECATED() [2/2]
template<typename T> Sequencer::UE_DEPRECATED (5. 5, "CreateKeyEditor(const TMovieSceneChannelHandle<T>&, UMovieSceneSection*, const FGuid&, TWeakPtr<FTrackInstancePropertyBindings>, TWeakPtr<ISequencer>); has been deprecated. Please update your signature to use FCreateKeyEditorParams")
Definition at line 42 of file SequencerChannelInterface.h.