Unreal Engine 5.6 C++ API: SubsurfaceProfile Namespace Reference
SubsurfaceProfile Namespace Reference
Functions
FName CreateSubsurfaceProfileParameterName (const USubsurfaceProfile *InProfile)
FRHITexture * GetSSProfilesPreIntegratedTextureWithFallback ()
float GetSubsurfaceProfileId (const USubsurfaceProfile *In)
FName GetSubsurfaceProfileParameterName ()
FRHITexture * GetSubsurfaceProfileTexture ()
FRHITexture * GetSubsurfaceProfileTextureWithFallback ()
void UpdateSubsurfaceProfileTexture (class FRDGBuilder &GraphBuilder, EShaderPlatform ShaderPlatform)
Function Documentation
CreateSubsurfaceProfileParameterName()
FName SubsurfaceProfile::CreateSubsurfaceProfileParameterName (const USubsurfaceProfile * InProfile)
References CreateSubsurfaceProfileParameterName().
Referenced by CreateSubsurfaceProfileParameterName().
GetSSProfilesPreIntegratedTextureWithFallback()
FRHITexture * SubsurfaceProfile::GetSSProfilesPreIntegratedTextureWithFallback ()
References GetSSProfilesPreIntegratedTextureWithFallback().
Referenced by GetSSProfilesPreIntegratedTextureWithFallback().
GetSubsurfaceProfileId()
float SubsurfaceProfile::GetSubsurfaceProfileId (const USubsurfaceProfile * In)
References GetSubsurfaceProfileId().
Referenced by GetSubsurfaceProfileId().
GetSubsurfaceProfileParameterName()
FName SubsurfaceProfile::GetSubsurfaceProfileParameterName ()
References GetSubsurfaceProfileParameterName().
Referenced by GetSubsurfaceProfileParameterName().
GetSubsurfaceProfileTexture()
FRHITexture * SubsurfaceProfile::GetSubsurfaceProfileTexture ()
References GetSubsurfaceProfileTexture().
Referenced by GetSubsurfaceProfileTexture().
GetSubsurfaceProfileTextureWithFallback()
FRHITexture * SubsurfaceProfile::GetSubsurfaceProfileTextureWithFallback ()
References GetSubsurfaceProfileTextureWithFallback().
Referenced by GetSubsurfaceProfileTextureWithFallback().
UpdateSubsurfaceProfileTexture()
void SubsurfaceProfile::UpdateSubsurfaceProfileTexture (class FRDGBuilder & GraphBuilder, EShaderPlatform ShaderPlatform)
References ShaderPlatform, and UpdateSubsurfaceProfileTexture().
Referenced by UpdateSubsurfaceProfileTexture().