Unreal Engine 5.6 C++ API: UE::Net Namespace Reference
UE::Net Namespace Reference
Responsible for creating headers allowing remote factories to spawn replicated actors.
Namespaces
namespace Metric
namespace Private
===================== NetSerialize and NetDeltaSerialize customization.
Data Structures
class FDefaultFaultHandler
Default Fault Handler.
class FNetConnectionFaultRecovery
NetConnection Fault Recovery.
class FNetIDVariant
Simple variant wrapper to hold a generic or Iris network object ID (FNetworkGUID or FNetRefHandle).
class FNetPing
Central class for handling all Player/NetConnection ping collection and calculation.
struct FNetworkMetric
struct FNetworkMetricSnapshot
struct FPingValues
Struct for returning ping values, in seconds.
class FScopedIgnoreStaticActorDestruction
struct FStatelessHandshakeFailureInfo
Contains the information necessary for processing a failed stateless handshake, on the Game Thread.
class TNetControlMessageImpl
class TStructNetTokenDataStoreHelper
Typedefs
typedef TMap< FNetworkGUID, TWeakObjectPtr< UObject > > FDormantObjectMap
typedef TFunctionRef< void(FObjectKey OwnerActorKey, FObjectKey ObjectKey, const TSharedRef< FObjectReplicator > &ReplicatorRef)> FExecuteForEachDormantReplicator
Function definition allowed in the ForEach functions.
using FHandshakeFailureFunc = TUniqueFunction<void(FStatelessHandshakeFailureInfo HandshakeFailureInfo)>
Callback function for handling a failed stateless handshake.
Enumerations
enum class EHandshakeFailureReason { None , WrongVersion }
Reasons for handshake failures.
enum class EHandshakePacketModifier : uint8 { None = 0x00 , RestartHandshake = 0x01 }
Flags/modifiers affecting how handshake packets are handled (e.g.
enum class EHandshakePacketType : uint8 {
InitialPacket = 0 , Challenge = 1 , Response = 2 , Ack = 3 ,
RestartHandshake = 4 , RestartResponse = 5 , VersionUpgrade = 6 , Last = VersionUpgrade
}
The different handshake packet types.
enum class EHandshakeVersion : uint8 {
Original = 0 , Randomized = 1 , NetCLVersion = 2 , SessionClientId = 3 ,
NetCLUpgradeMessage = 4 , Latest = NetCLUpgradeMessage
}
The different handshake protocol versions.
enum class ENetUpgradeSource : uint8 { ControlChannel , StatelessHandshake }
The source of a net upgrade message.
Functions
TStaticBitArray< COND_Max > BuildConditionMapFromRepFlags (const FReplicationFlags &RepFlags)
Builds a new ConditionMap given the input RepFlags.
uint32 CountReplicatedSubObjectsOfActor (AActor *ReplicatedActor)
Utility function that counts the number of replicated subobjects owned by a given actor.
ENUM_CLASS_FLAGS (EHandshakePacketModifier)
constexpr SIZE_T GetGameplayEffectContextNetSerializerSafeQuantizedSize ()
uint32 GetTypeHash (const FNetIDVariant &NetID)
static bool IsValidPingType (EPingType PingType)
Whether or not an EPingType value is valid.
bool ShouldIgnoreStaticActorDestruction ()
UE_NET_DECLARE_SERIALIZER (FCharacterNetworkSerializationPackedBitsNetSerializer, 1)
UE_NET_DECLARE_SERIALIZER (FGameplayAbilityRepAnimMontageNetSerializer, GAMEPLAYABILITIES_API)
UE_NET_DECLARE_SERIALIZER (FGameplayAbilityTargetingLocationInfoNetSerializer, GAMEPLAYABILITIES_API)
UE_NET_DECLARE_SERIALIZER (FGameplayEffectContextHandleNetSerializer, GAMEPLAYABILITIES_API)
UE_NET_DECLARE_SERIALIZER (FGameplayEffectContextNetSerializer, GAMEPLAYABILITIES_API)
UE_NET_DECLARE_SERIALIZER (FGameplayTagContainerNetSerializer, GAMEPLAYTAGS_API)
UE_NET_DECLARE_SERIALIZER (FGameplayTagNetSerializer, GAMEPLAYTAGS_API)
UE_NET_DECLARE_SERIALIZER (FHitResultNetSerializer, 1)
UE_NET_DECLARE_SERIALIZER (FMinimalGameplayCueReplicationProxyNetSerializer, GAMEPLAYABILITIES_API)
UE_NET_DECLARE_SERIALIZER (FMinimalReplicationTagCountMapNetSerializer, GAMEPLAYABILITIES_API)
UE_NET_DECLARE_SERIALIZER (FRootMotionSourceGroupNetSerializer, 1)
UE_NET_DECLARE_SERIALIZER (FUniqueNetIdReplNetSerializer, 1)
Variables
int32 GRPCDoSScopeDebugging
Whether or not debugging/ensures for RPC DoS Tick/Packet scopes should be enabled.
static constexpr EHandshakeVersion HandshakeCompatibilityBreaks [] = { EHandshakeVersion::SessionClientId }
List of EHandshakeVersion's which break net compatibility (sorted from earliest to latest)
Detailed Description
Responsible for creating headers allowing remote factories to spawn replicated actors.
Typedef Documentation
FDormantObjectMap
typedef TMap<FNetworkGUID, TWeakObjectPtr<UObject> > UE::Net::FDormantObjectMap
Definition at line 19 of file NetDormantHolder.h.
FExecuteForEachDormantReplicator
typedef TFunctionRef<void(FObjectKey OwnerActorKey, FObjectKey ObjectKey, const TSharedRef<FObjectReplicator>& ReplicatorRef)> UE::Net::FExecuteForEachDormantReplicator
Function definition allowed in the ForEach functions.
Definition at line 17 of file NetDormantHolder.h.
FHandshakeFailureFunc
using UE::Net::FHandshakeFailureFunc = TUniqueFunction<void(FStatelessHandshakeFailureInfo HandshakeFailureInfo)>
Callback function for handling a failed stateless handshake.
Triggered when processing incoming packets.
Parameters
HandshakeFailureInfo Information about the handshake failure.
Definition at line 109 of file StatelessConnectHandlerComponent.h.
Enumeration Type Documentation
EHandshakeFailureReason
enum class UE::Net::EHandshakeFailureReason strong
Reasons for handshake failures.
Enumerator
None
WrongVersion
Definition at line 78 of file StatelessConnectHandlerComponent.h.
EHandshakePacketModifier
enum class UE::Net::EHandshakePacketModifier : uint8 strong
Flags/modifiers affecting how handshake packets are handled (e.g.
restart handshake packets)
Enumerator
None
RestartHandshake
Definition at line 66 of file StatelessConnectHandlerComponent.h.
EHandshakePacketType
enum class UE::Net::EHandshakePacketType : uint8 strong
The different handshake packet types.
Enumerator
InitialPacket
Challenge
Response
Ack
RestartHandshake
RestartResponse
VersionUpgrade
Last
Definition at line 50 of file StatelessConnectHandlerComponent.h.
EHandshakeVersion
enum class UE::Net::EHandshakeVersion : uint8 strong
The different handshake protocol versions.
Enumerator
Original
Randomized
NetCLVersion
SessionClientId
Net compatibility break.
NetCLUpgradeMessage
Latest
Definition at line 29 of file StatelessConnectHandlerComponent.h.
ENetUpgradeSource
enum class UE::Net::ENetUpgradeSource : uint8 strong
The source of a net upgrade message.
Enumerator
ControlChannel
StatelessHandshake
Definition at line 106 of file NetConnection.h.
Function Documentation
BuildConditionMapFromRepFlags()
TStaticBitArray< COND_Max > UE::Net::BuildConditionMapFromRepFlags (const FReplicationFlags & RepFlags) inline
Builds a new ConditionMap given the input RepFlags.
This can be used to determine whether or not a given property should be considered enabled / disabled based on ELifetimeCondition.
Definition at line 135 of file RepLayout.h.
References FReplicationFlags::bNetInitial, FReplicationFlags::bNetOwner, FReplicationFlags::bNetSimulated, FReplicationFlags::bReplay, and FReplicationFlags::bRepPhysics.
Referenced by FSendingRepState::UE_DEPRECATED().
CountReplicatedSubObjectsOfActor()
uint32 UE::Net::CountReplicatedSubObjectsOfActor (AActor * ReplicatedActor)
Utility function that counts the number of replicated subobjects owned by a given actor.
Be aware that this function is not cheap because it needs to iterate and count all replicated components and their subobjects too.
References ReplicatedActor.
ENUM_CLASS_FLAGS()
UE::Net::ENUM_CLASS_FLAGS (EHandshakePacketModifier)
GetGameplayEffectContextNetSerializerSafeQuantizedSize()
SIZE_T UE::Net::GetGameplayEffectContextNetSerializerSafeQuantizedSize () constexpr
Definition at line 20 of file GameplayEffectContextNetSerializer.h.
GetTypeHash()
uint32 UE::Net::GetTypeHash (const FNetIDVariant & NetID) inline
Definition at line 63 of file NetIDVariant.h.
References TVariant< T, Ts >::Get(), GetTypeHash(), UE::Net::FNetIDVariant::GetVariant(), HashCombineFast(), and TVariant< T, Ts >::IsType().
Referenced by UE::Net::Private::FActorDormantReplicators::FDormantObjectReplicatorKeyFuncs::GetKeyHash(), UE::Net::Private::FDormantReplicatorHolder::FActorDormantReplicatorsKeyFuncs::GetKeyHash(), and GetTypeHash().
IsValidPingType()
bool UE::Net::IsValidPingType (EPingType PingType) static
Whether or not an EPingType value is valid.
Definition at line 103 of file NetPing.h.
References FMath::IsPowerOfTwo().
ShouldIgnoreStaticActorDestruction()
bool UE::Net::ShouldIgnoreStaticActorDestruction ()
UE_NET_DECLARE_SERIALIZER() [1/12]
UE::Net::UE_NET_DECLARE_SERIALIZER (FCharacterNetworkSerializationPackedBitsNetSerializer , 1)
References UE_NET_DECLARE_SERIALIZER().
UE_NET_DECLARE_SERIALIZER() [2/12]
UE::Net::UE_NET_DECLARE_SERIALIZER (FGameplayAbilityRepAnimMontageNetSerializer , GAMEPLAYABILITIES_API)
Referenced by UE_NET_DECLARE_SERIALIZER().
UE_NET_DECLARE_SERIALIZER() [3/12]
UE::Net::UE_NET_DECLARE_SERIALIZER (FGameplayAbilityTargetingLocationInfoNetSerializer , GAMEPLAYABILITIES_API)
UE_NET_DECLARE_SERIALIZER() [4/12]
UE::Net::UE_NET_DECLARE_SERIALIZER (FGameplayEffectContextHandleNetSerializer , GAMEPLAYABILITIES_API)
UE_NET_DECLARE_SERIALIZER() [5/12]
UE::Net::UE_NET_DECLARE_SERIALIZER (FGameplayEffectContextNetSerializer , GAMEPLAYABILITIES_API)
UE_NET_DECLARE_SERIALIZER() [6/12]
UE::Net::UE_NET_DECLARE_SERIALIZER (FGameplayTagContainerNetSerializer , GAMEPLAYTAGS_API)
UE_NET_DECLARE_SERIALIZER() [7/12]
UE::Net::UE_NET_DECLARE_SERIALIZER (FGameplayTagNetSerializer , GAMEPLAYTAGS_API)
UE_NET_DECLARE_SERIALIZER() [8/12]
UE::Net::UE_NET_DECLARE_SERIALIZER (FHitResultNetSerializer , 1)
UE_NET_DECLARE_SERIALIZER() [9/12]
UE::Net::UE_NET_DECLARE_SERIALIZER (FMinimalGameplayCueReplicationProxyNetSerializer , GAMEPLAYABILITIES_API)
UE_NET_DECLARE_SERIALIZER() [10/12]
UE::Net::UE_NET_DECLARE_SERIALIZER (FMinimalReplicationTagCountMapNetSerializer , GAMEPLAYABILITIES_API)
UE_NET_DECLARE_SERIALIZER() [11/12]
UE::Net::UE_NET_DECLARE_SERIALIZER (FRootMotionSourceGroupNetSerializer , 1)
UE_NET_DECLARE_SERIALIZER() [12/12]
UE::Net::UE_NET_DECLARE_SERIALIZER (FUniqueNetIdReplNetSerializer , 1)
Variable Documentation
GRPCDoSScopeDebugging
int32 UE::Net::GRPCDoSScopeDebugging extern
Whether or not debugging/ensures for RPC DoS Tick/Packet scopes should be enabled.
Referenced by FRPCDoSDetection::GetPacketScope(), FRPCDoSDetection::GetSequentialRPCScope(), FRPCDoSDetection::GetTickScope(), FRPCDoSDetection::PostReceivedPacket(), FRPCDoSDetection::PreReceivedPacket(), FRPCDoSDetection::PreSequentialRPC(), and FRPCDoSDetection::TScopeBase< T >::SetActive().
HandshakeCompatibilityBreaks
EHandshakeVersion UE::Net::HandshakeCompatibilityBreaks[] = { EHandshakeVersion::SessionClientId } static constexpr
List of EHandshakeVersion's which break net compatibility (sorted from earliest to latest)
Definition at line 44 of file StatelessConnectHandlerComponent.h.