Unreal Engine 5.6 C++ API: BlendSpaceAnalysis Namespace Reference
BlendSpaceAnalysis Namespace Reference
This will be used to preserve values as far as possible when switching between analysis functions, so it contains all the parameters used by the engine functions.
Functions
PERSONA_API bool CalculateAngularVelocity (FVector &Result, const UBlendSpace &BlendSpace, const ULinearAnalysisProperties *AnalysisProperties, const UAnimSequence &Animation, const float RateScale)
PERSONA_API void CalculateBoneOrientation (FVector &RollPitchYaw, const UAnimSequence &Animation, const int32 Key, const FName BoneName, const FTransform &BoneOffset, const UEulerAnalysisProperties *AnalysisProperties, const FVector &FrameFacingDir, const FVector &FrameRightDir, const FVector &FrameUpDir)
CalculateBoneOrientation (RollPitchYaw1, Animation, FirstKey, BoneName, BoneOffset, AnalysisProperties, FrameFacingDir, FrameRightDir, FrameUpDir)
CalculateBoneOrientation (RollPitchYaw2, Animation, LastKey, BoneName, BoneOffset, AnalysisProperties, FrameFacingDir, FrameRightDir, FrameUpDir)
template<typename FunctionType>
static bool CalculateComponentSampleValue (double &Result, const FunctionType &Fn, const UBlendSpace &BlendSpace, const UEulerAnalysisProperties *AnalysisProperties, const UAnimSequence &Animation, const float RateScale)
Helper to extract the component from the FVector functions.
template<typename FunctionType>
static bool CalculateComponentSampleValue (double &Result, const FunctionType &Fn, const UBlendSpace &BlendSpace, const ULinearAnalysisProperties *AnalysisProperties, const UAnimSequence &Animation, const float RateScale)
Helper to extract the component from the FVector functions.
template<typename FunctionType>
static bool CalculateComponentSampleValue (float &Result, const FunctionType &Fn, const UBlendSpace &BlendSpace, const UEulerAnalysisProperties *AnalysisProperties, const UAnimSequence &Animation, const float RateScale)
Helper to extract the component from the FVector functions as a float (pass through to double version)
template<typename FunctionType>
static bool CalculateComponentSampleValue (float &Result, const FunctionType &Fn, const UBlendSpace &BlendSpace, const ULinearAnalysisProperties *AnalysisProperties, const UAnimSequence &Animation, const float RateScale)
Helper to extract the component from the FVector functions as a float (pass through to double version)
PERSONA_API bool CalculateDeltaOrientation (FVector &Result, const UBlendSpace &BlendSpace, const UEulerAnalysisProperties *AnalysisProperties, const UAnimSequence &Animation, const float RateScale)
PERSONA_API bool CalculateDeltaPosition (FVector &Result, const UBlendSpace &BlendSpace, const ULinearAnalysisProperties *AnalysisProperties, const UAnimSequence &Animation, const float RateScale)
CalculateFrameTM (bNeedToUpdateFrameTM, FrameTM, FirstKey, AnalysisProperties, Animation)
CalculateFrameTM (bNeedToUpdateFrameTM, FrameTM, LastKey, AnalysisProperties, Animation)
template<typename T>
void CalculateFrameTM (bool &bNeedToUpdateFrameTM, FTransform &FrameTM, const int32 SampleKey, const T &AnalysisProperties, const UAnimSequence &Animation)
PERSONA_API bool CalculateOrientation (FVector &Result, const UBlendSpace &BlendSpace, const UEulerAnalysisProperties *AnalysisProperties, const UAnimSequence &Animation, const float RateScale)
PERSONA_API bool CalculateOrientationRate (FVector &Result, const UBlendSpace &BlendSpace, const UEulerAnalysisProperties *AnalysisProperties, const UAnimSequence &Animation, const float RateScale)
PERSONA_API bool CalculatePosition (FVector &Result, const UBlendSpace &BlendSpace, const ULinearAnalysisProperties *AnalysisProperties, const UAnimSequence &Animation, const float RateScale)
PERSONA_API bool CalculateVelocity (FVector &Result, const UBlendSpace &BlendSpace, const ULinearAnalysisPropertiesBase *AnalysisProperties, const UAnimSequence &Animation, const float RateScale)
for (int32 Key=FirstKey;Key !=LastKey+1;++Key)
PERSONA_API FVector GetAxisFromTM (const FTransform &TM, EAnalysisLinearAxis Axis)
PERSONA_API bool GetBoneInfo (const UAnimSequence &Animation, const FBoneSocketTarget &BoneSocket, FTransform &BoneOffset, FName &BoneName)
PERSONA_API FTransform GetBoneTransform (const UAnimSequence &Animation, int32 Key, const FName &BoneName)
GetFrameDirs (FrameFacingDir, FrameUpDir, FrameRightDir, FrameTM, AnalysisProperties)
template<typename T>
void GetFrameDirs (FVector &FrameFacingDir, FVector &FrameUpDir, FVector &FrameRightDir, const FTransform &FrameTM, const T &AnalysisProperties)
if (!AnalysisProperties||NumSampledKeys<=0)
if (!GetBoneInfo(Animation, AnalysisProperties->BoneSocket, BoneOffset, BoneName))
if (AnalysisProperties->EulerCalculationMethod==EEulerCalculationMethod::AimDirection)
if (Fn(Value, BlendSpace, AnalysisProperties, Animation, RateScale))
if (NumSampledKeys==1)
const FQuat PitchQuat (FrameRightDir, -FMath::DegreesToRadians(Pitch))
Result Set (0, 0, 0)
RollPitchYaw Set (Roll, Pitch, Yaw)
template<typename FunctionType, typename T>
UE_DEPRECATED (5.6, "Use function with strongly typed AnalysisProperties") static bool CalculateComponentSampleValue(double &Result
Helper to extract the component from the FVector functions.
template<typename T>
UE_DEPRECATED (5.6, "Use function with strongly typed AnalysisProperties") static bool CalculatePosition(FVector &Result
Result * UE_LOG (LogAnimation, Log, TEXT("%s angular velocity = %f %f %f"), *BoneName.ToString(), Result.X, Result.Y, Result.Z)
UE_LOG (LogAnimation, Log, TEXT("%s Orientation = %f %f %f"), *BoneName.ToString(), Result.X, Result.Y, Result.Z)
Result * UE_LOG (LogAnimation, Log, TEXT("%s Orientation rate = %f %f %f"), *BoneName.ToString(), Result.X, Result.Y, Result.Z)
Result * UE_LOG (LogAnimation, Log, TEXT("%s vel = %f %f %f"), *BoneName.ToString(), Result.X, Result.Y, Result.Z)
const FQuat YawQuat (FrameUpDir, FMath::DegreesToRadians(Yaw))
Variables
const FVector AimForwardDir = BlendSpaceAnalysis::GetAxisFromTM(TM, AnalysisProperties->BoneFacingAxis)
const FVector AimRightDir = BlendSpaceAnalysis::GetAxisFromTM(TM, AnalysisProperties->BoneRightAxis)
const FunctionType const UBlendSpace const T * AnalysisProperties
const FunctionType const UBlendSpace const T const UAnimSequence & Animation
const FunctionType const UBlendSpace & BlendSpace
bool bNeedToUpdateFrameTM = true
FName BoneName
FTransform BoneOffset
FTransform BoneTM1 = GetBoneTransform(Animation, FirstKey, BoneName)
FTransform BoneTM2 = GetBoneTransform(Animation, LastKey, BoneName)
bool bResult = CalculateComponentSampleValue(DoubleResult, Fn, BlendSpace, AnalysisProperties, Animation, RateScale)
int32 ComponentIndex = (int32)AnalysisProperties->FunctionAxis
double DeltaTime = Animation.GetPlayLength() / double(NumSampledKeys)
else
return false
int32 FirstKey
const FunctionType & Fn
const double Forward = UnYawedAimForwardDir | FrameFacingDir
const UAnimSequence const int32 const FName const FTransform const T const FVector & FrameFacingDir
const UAnimSequence const int32 const FName const FTransform const T const FVector const FVector & FrameRightDir
FTransform FrameTM
const UAnimSequence const int32 const FName const FTransform const T const FVector const FVector const FVector & FrameUpDir
const UAnimSequence const int32 Key
int32 LastKey
int32 NumKeys = FMath::Max(1 + LastKey - FirstKey, 1)
const double Pitch = FMath::RadiansToDegrees(FMath::Atan2(Up, Forward))
const FunctionType const UBlendSpace const T const UAnimSequence const float RateScale
FVector RelativePos1 = FrameTM.InverseTransformPosition(TM1.GetTranslation())
FVector RelativePos2 = FrameTM.InverseTransformPosition(TM2.GetTranslation())
Result = float(DoubleResult)
const double Roll
FVector RollPitchYaw1
FVector RollPitchYaw2
const FTransform TM = BoneOffset * BoneTM
FTransform TM1 = BoneOffset * BoneTM1
FTransform TM2 = BoneOffset * BoneTM2
return true
const FVector UnYawedAimForwardDir = YawQuat.UnrotateVector(AimForwardDir)
const FVector UnYawedAimRightDir = YawQuat.UnrotateVector(AimRightDir)
const FVector UnYawedUnPitchedAimRightDir = PitchQuat.UnrotateVector(UnYawedAimRightDir)
const double Up = UnYawedAimForwardDir | FrameUpDir
double Yaw
Detailed Description
This will be used to preserve values as far as possible when switching between analysis functions, so it contains all the parameters used by the engine functions.
User defined can inherit from this and add their own - then the user-defined MakeCache function should replace any base class cache that is passed in with their own.
Function Documentation
CalculateAngularVelocity()
PERSONA_API bool BlendSpaceAnalysis::CalculateAngularVelocity (FVector & Result, const UBlendSpace & BlendSpace, const ULinearAnalysisProperties * AnalysisProperties, const UAnimSequence & Animation, const float RateScale) extern
References AnalysisProperties, Animation, BlendSpace, CalculateAngularVelocity(), FVector, RateScale, and Result.
Referenced by CalculateAngularVelocity().
CalculateBoneOrientation() [1/3]
PERSONA_API void BlendSpaceAnalysis::CalculateBoneOrientation (FVector & RollPitchYaw, const UAnimSequence & Animation, const int32 Key, const FName BoneName, const FTransform & BoneOffset, const UEulerAnalysisProperties * AnalysisProperties, const FVector & FrameFacingDir, const FVector & FrameRightDir, const FVector & FrameUpDir) extern
References AnalysisProperties, Animation, BoneName, BoneOffset, CalculateBoneOrientation(), FrameFacingDir, FrameRightDir, FrameUpDir, FVector, and Key.
Referenced by CalculateBoneOrientation(), CalculateBoneOrientation(), CalculateBoneOrientation(), and GetFrameDirs().
CalculateBoneOrientation() [2/3]
BlendSpaceAnalysis::CalculateBoneOrientation (RollPitchYaw1 , Animation , FirstKey , BoneName , BoneOffset , AnalysisProperties , FrameFacingDir , FrameRightDir , FrameUpDir)
References AnalysisProperties, Animation, BoneName, BoneOffset, CalculateBoneOrientation(), FirstKey, FrameFacingDir, FrameRightDir, FrameUpDir, and RollPitchYaw1.
CalculateBoneOrientation() [3/3]
BlendSpaceAnalysis::CalculateBoneOrientation (RollPitchYaw2 , Animation , LastKey , BoneName , BoneOffset , AnalysisProperties , FrameFacingDir , FrameRightDir , FrameUpDir)
References AnalysisProperties, Animation, BoneName, BoneOffset, CalculateBoneOrientation(), FrameFacingDir, FrameRightDir, FrameUpDir, LastKey, Result, RollPitchYaw1, and RollPitchYaw2.
CalculateComponentSampleValue() [1/4]
template<typename FunctionType> bool BlendSpaceAnalysis::CalculateComponentSampleValue (double & Result, const FunctionType & Fn, const UBlendSpace & BlendSpace, const UEulerAnalysisProperties * AnalysisProperties, const UAnimSequence & Animation, const float RateScale) static
Helper to extract the component from the FVector functions.
Definition at line 295 of file BlendSpaceAnalysis.h.
References AnalysisProperties, Animation, BlendSpace, CalculateComponentSampleValue(), ComponentIndex, Fn, FVector, RateScale, Result, and Value.
CalculateComponentSampleValue() [2/4]
template<typename FunctionType> bool BlendSpaceAnalysis::CalculateComponentSampleValue (double & Result, const FunctionType & Fn, const UBlendSpace & BlendSpace, const ULinearAnalysisProperties * AnalysisProperties, const UAnimSequence & Animation, const float RateScale) static
Helper to extract the component from the FVector functions.
Definition at line 272 of file BlendSpaceAnalysis.h.
References AnalysisProperties, Animation, BlendSpace, CalculateComponentSampleValue(), ComponentIndex, Fn, FVector, GetAxisFromTM(), UE::Math::TTransform< double >::Identity, RateScale, Result, Value, and UE::Math::TVector< double >::ZeroVector.
Referenced by CalculateComponentSampleValue(), CalculateComponentSampleValue(), CalculateComponentSampleValue(), CalculateComponentSampleValue(), and UE_DEPRECATED().
CalculateComponentSampleValue() [3/4]
template<typename FunctionType> bool BlendSpaceAnalysis::CalculateComponentSampleValue (float & Result, const FunctionType & Fn, const UBlendSpace & BlendSpace, const UEulerAnalysisProperties * AnalysisProperties, const UAnimSequence & Animation, const float RateScale) static
Helper to extract the component from the FVector functions as a float (pass through to double version)
Definition at line 337 of file BlendSpaceAnalysis.h.
References AnalysisProperties, Animation, BlendSpace, bResult, CalculateComponentSampleValue(), float, Fn, RateScale, and Result.
CalculateComponentSampleValue() [4/4]
template<typename FunctionType> bool BlendSpaceAnalysis::CalculateComponentSampleValue (float & Result, const FunctionType & Fn, const UBlendSpace & BlendSpace, const ULinearAnalysisProperties * AnalysisProperties, const UAnimSequence & Animation, const float RateScale) static
Helper to extract the component from the FVector functions as a float (pass through to double version)
Definition at line 318 of file BlendSpaceAnalysis.h.
References AnalysisProperties, Animation, BlendSpace, bResult, CalculateComponentSampleValue(), float, Fn, RateScale, and Result.
CalculateDeltaOrientation()
PERSONA_API bool BlendSpaceAnalysis::CalculateDeltaOrientation (FVector & Result, const UBlendSpace & BlendSpace, const UEulerAnalysisProperties * AnalysisProperties, const UAnimSequence & Animation, const float RateScale) extern
References AnalysisProperties, Animation, BlendSpace, CalculateDeltaOrientation(), FVector, RateScale, and Result.
Referenced by CalculateDeltaOrientation().
CalculateDeltaPosition()
PERSONA_API bool BlendSpaceAnalysis::CalculateDeltaPosition (FVector & Result, const UBlendSpace & BlendSpace, const ULinearAnalysisProperties * AnalysisProperties, const UAnimSequence & Animation, const float RateScale) extern
References AnalysisProperties, Animation, BlendSpace, CalculateDeltaPosition(), FVector, RateScale, and Result.
Referenced by CalculateDeltaPosition().
CalculateFrameTM() [1/3]
BlendSpaceAnalysis::CalculateFrameTM (bNeedToUpdateFrameTM , FrameTM , FirstKey , AnalysisProperties , Animation)
References AnalysisProperties, Animation, bNeedToUpdateFrameTM, CalculateFrameTM(), FirstKey, and FrameTM.
CalculateFrameTM() [2/3]
BlendSpaceAnalysis::CalculateFrameTM (bNeedToUpdateFrameTM , FrameTM , LastKey , AnalysisProperties , Animation)
References AnalysisProperties, Animation, bNeedToUpdateFrameTM, CalculateFrameTM(), FrameFacingDir, FrameRightDir, FrameTM, FrameUpDir, GetFrameDirs(), and LastKey.
CalculateFrameTM() [3/3]
template<typename T> void BlendSpaceAnalysis::CalculateFrameTM (bool & bNeedToUpdateFrameTM, FTransform & FrameTM, const int32 SampleKey, const T & AnalysisProperties, const UAnimSequence & Animation)
Definition at line 229 of file BlendSpaceAnalysis.h.
References AnalysisProperties, Animation, bNeedToUpdateFrameTM, CalculateFrameTM(), FrameTM, GetBoneInfo(), and GetBoneTransform().
Referenced by CalculateFrameTM(), CalculateFrameTM(), CalculateFrameTM(), for(), and GetFrameDirs().
CalculateOrientation()
PERSONA_API bool BlendSpaceAnalysis::CalculateOrientation (FVector & Result, const UBlendSpace & BlendSpace, const UEulerAnalysisProperties * AnalysisProperties, const UAnimSequence & Animation, const float RateScale) extern
References AnalysisProperties, Animation, BlendSpace, CalculateOrientation(), FVector, RateScale, and Result.
Referenced by CalculateOrientation().
CalculateOrientationRate()
PERSONA_API bool BlendSpaceAnalysis::CalculateOrientationRate (FVector & Result, const UBlendSpace & BlendSpace, const UEulerAnalysisProperties * AnalysisProperties, const UAnimSequence & Animation, const float RateScale) extern
References AnalysisProperties, Animation, BlendSpace, CalculateOrientationRate(), FVector, RateScale, and Result.
Referenced by CalculateOrientationRate().
CalculatePosition()
PERSONA_API bool BlendSpaceAnalysis::CalculatePosition (FVector & Result, const UBlendSpace & BlendSpace, const ULinearAnalysisProperties * AnalysisProperties, const UAnimSequence & Animation, const float RateScale) extern
References AnalysisProperties, Animation, BlendSpace, CalculatePosition(), FVector, RateScale, and Result.
Referenced by CalculatePosition(), and UE_DEPRECATED().
CalculateVelocity()
PERSONA_API bool BlendSpaceAnalysis::CalculateVelocity (FVector & Result, const UBlendSpace & BlendSpace, const ULinearAnalysisPropertiesBase * AnalysisProperties, const UAnimSequence & Animation, const float RateScale) extern
References AnalysisProperties, Animation, BlendSpace, CalculateVelocity(), FVector, RateScale, and Result.
Referenced by CalculateVelocity().
for()
BlendSpaceAnalysis::for (int32 Key = FirstKey; Key != LastKey + 1; ++Key)
Definition at line 500 of file BlendSpaceAnalysis.h.
References AnalysisProperties, Animation, bNeedToUpdateFrameTM, BoneName, BoneOffset, CalculateFrameTM(), FirstKey, FrameTM, FVector, GetBoneTransform(), Key, LastKey, Result, and TM.
GetAxisFromTM()
PERSONA_API FVector BlendSpaceAnalysis::GetAxisFromTM (const FTransform & TM, EAnalysisLinearAxis Axis)
References Axis, FVector, GetAxisFromTM(), and TM.
Referenced by CalculateComponentSampleValue(), GetAxisFromTM(), and GetFrameDirs().
GetBoneInfo()
PERSONA_API bool BlendSpaceAnalysis::GetBoneInfo (const UAnimSequence & Animation, const FBoneSocketTarget & BoneSocket, FTransform & BoneOffset, FName & BoneName)
References Animation, BoneName, BoneOffset, and GetBoneInfo().
Referenced by CalculateFrameTM(), GetBoneInfo(), and if().
GetBoneTransform()
PERSONA_API FTransform BlendSpaceAnalysis::GetBoneTransform (const UAnimSequence & Animation, int32 Key, const FName & BoneName)
References Animation, BoneName, GetBoneTransform(), and Key.
Referenced by CalculateFrameTM(), for(), and GetBoneTransform().
GetFrameDirs() [1/2]
BlendSpaceAnalysis::GetFrameDirs (FrameFacingDir , FrameUpDir , FrameRightDir , FrameTM , AnalysisProperties)
References AnalysisProperties, Animation, bNeedToUpdateFrameTM, BoneName, BoneOffset, CalculateBoneOrientation(), CalculateFrameTM(), FirstKey, FrameFacingDir, FrameRightDir, FrameTM, FrameUpDir, FVector, GetFrameDirs(), Key, LastKey, Log, and Result.
GetFrameDirs() [2/2]
template<typename T> void BlendSpaceAnalysis::GetFrameDirs (FVector & FrameFacingDir, FVector & FrameUpDir, FVector & FrameRightDir, const FTransform & FrameTM, const T & AnalysisProperties)
Definition at line 258 of file BlendSpaceAnalysis.h.
References AnalysisProperties, UE::Math::TVector< double >::CrossProduct(), FrameFacingDir, FrameRightDir, FrameTM, FrameUpDir, FVector, GetAxisFromTM(), and GetFrameDirs().
Referenced by CalculateFrameTM(), GetFrameDirs(), and GetFrameDirs().
if() [1/5]
BlendSpaceAnalysis::if (!AnalysisProperties||NumSampledKeys<= 0)
Definition at line 478 of file BlendSpaceAnalysis.h.
References AnalysisProperties.
if() [2/5]
BlendSpaceAnalysis::if (! GetBoneInfoAnimation, AnalysisProperties->BoneSocket, BoneOffset, BoneName)
Definition at line 485 of file BlendSpaceAnalysis.h.
References AnalysisProperties, Animation, BoneName, BoneOffset, and GetBoneInfo().
if() [3/5]
BlendSpaceAnalysis::if (AnalysisProperties-> EulerCalculationMethod = = EEulerCalculationMethod::AimDirection)
Definition at line 654 of file BlendSpaceAnalysis.h.
References AimRightDir, AnalysisProperties, UE::Math::TVector< double >::DotProduct(), FrameFacingDir, FrameRightDir, FMath::RadiansToDegrees(), and Yaw.
if() [4/5]
BlendSpaceAnalysis::if (Fn(Value, BlendSpace, AnalysisProperties, Animation, RateScale))
Definition at line 439 of file BlendSpaceAnalysis.h.
References AnalysisProperties, Animation, BlendSpace, ComponentIndex, Fn, RateScale, Result, and Value.
if() [5/5]
BlendSpaceAnalysis::if (NumSampledKeys = = 1)
Definition at line 573 of file BlendSpaceAnalysis.h.
References Result.
PitchQuat()
const FQuat BlendSpaceAnalysis::PitchQuat (FrameRightDir , - FMath::DegreesToRadiansPitch)
References FMath::DegreesToRadians(), FrameRightDir, Pitch, and PitchQuat().
Referenced by PitchQuat().
Set() [1/2]
Result BlendSpaceAnalysis::Set (0 , 0 , 0)
References Result.
Set() [2/2]
RollPitchYaw BlendSpaceAnalysis::Set (Roll , Pitch , Yaw)
References Pitch, Roll, and Yaw.
UE_DEPRECATED() [1/2]
template<typename FunctionType, typename T> BlendSpaceAnalysis::UE_DEPRECATED (5. 6, "Use function with strongly typed AnalysisProperties") &
Helper to extract the component from the FVector functions.
Helper to extract the component from the FVector functions as a float (pass through to double version)
References CalculateComponentSampleValue(), and Result.
UE_DEPRECATED() [2/2]
template<typename T> BlendSpaceAnalysis::UE_DEPRECATED (5. 6, "Use function with strongly typed AnalysisProperties") &
References AnalysisProperties, Animation, BlendSpace, CalculatePosition(), FVector, RateScale, and Result.
UE_LOG() [1/4]
Result * BlendSpaceAnalysis::UE_LOG (LogAnimation , Log , TEXT("%s angular velocity = %f %f %f") , *BoneName. ToString(), Result. X, Result. Y, Result. Z)
References BoneName, Log, and Result.
UE_LOG() [2/4]
BlendSpaceAnalysis::UE_LOG (LogAnimation , Log , TEXT("%s Orientation = %f %f %f") , *BoneName. ToString(), Result. X, Result. Y, Result. Z)
References BoneName, Log, and Result.
UE_LOG() [3/4]
Result * BlendSpaceAnalysis::UE_LOG (LogAnimation , Log , TEXT("%s Orientation rate = %f %f %f") , *BoneName. ToString(), Result. X, Result. Y, Result. Z)
References BoneName, Log, and Result.
UE_LOG() [4/4]
Result * BlendSpaceAnalysis::UE_LOG (LogAnimation , Log , TEXT("%s vel = %f %f %f") , *BoneName. ToString(), Result. X, Result. Y, Result. Z)
References BoneName, Log, and Result.
YawQuat()
const FQuat BlendSpaceAnalysis::YawQuat (FrameUpDir , FMath::DegreesToRadians(Yaw))
References FMath::DegreesToRadians(), FrameUpDir, Yaw, and YawQuat().
Referenced by YawQuat().
Variable Documentation
AimForwardDir
const FVector BlendSpaceAnalysis::AimForwardDir = BlendSpaceAnalysis::GetAxisFromTM(TM, AnalysisProperties->BoneFacingAxis)
Definition at line 650 of file BlendSpaceAnalysis.h.
AimRightDir
const FVector BlendSpaceAnalysis::AimRightDir = BlendSpaceAnalysis::GetAxisFromTM(TM, AnalysisProperties->BoneRightAxis)
Definition at line 651 of file BlendSpaceAnalysis.h.
Referenced by if().
AnalysisProperties
const UBlendSpace const T * BlendSpaceAnalysis::AnalysisProperties
Definition at line 433 of file BlendSpaceAnalysis.h.
Referenced by CalculateAngularVelocity(), CalculateBoneOrientation(), CalculateBoneOrientation(), CalculateBoneOrientation(), CalculateComponentSampleValue(), CalculateComponentSampleValue(), CalculateComponentSampleValue(), CalculateComponentSampleValue(), CalculateDeltaOrientation(), CalculateDeltaPosition(), CalculateFrameTM(), CalculateFrameTM(), CalculateFrameTM(), CalculateOrientation(), CalculateOrientationRate(), CalculatePosition(), CalculateVelocity(), for(), GetFrameDirs(), GetFrameDirs(), if(), if(), if(), if(), and UE_DEPRECATED().
Animation
const UBlendSpace const T const UAnimSequence & BlendSpaceAnalysis::Animation
Definition at line 434 of file BlendSpaceAnalysis.h.
Referenced by CalculateAngularVelocity(), CalculateBoneOrientation(), CalculateBoneOrientation(), CalculateBoneOrientation(), CalculateComponentSampleValue(), CalculateComponentSampleValue(), CalculateComponentSampleValue(), CalculateComponentSampleValue(), CalculateDeltaOrientation(), CalculateDeltaPosition(), CalculateFrameTM(), CalculateFrameTM(), CalculateFrameTM(), CalculateOrientation(), CalculateOrientationRate(), CalculatePosition(), CalculateVelocity(), for(), GetBoneInfo(), GetBoneTransform(), GetFrameDirs(), if(), if(), and UE_DEPRECATED().
BlendSpace
const UBlendSpace & BlendSpaceAnalysis::BlendSpace
Definition at line 432 of file BlendSpaceAnalysis.h.
Referenced by CalculateAngularVelocity(), CalculateComponentSampleValue(), CalculateComponentSampleValue(), CalculateComponentSampleValue(), CalculateComponentSampleValue(), CalculateDeltaOrientation(), CalculateDeltaPosition(), CalculateOrientation(), CalculateOrientationRate(), CalculatePosition(), CalculateVelocity(), if(), and UE_DEPRECATED().
bNeedToUpdateFrameTM
bool BlendSpaceAnalysis::bNeedToUpdateFrameTM = true
Definition at line 496 of file BlendSpaceAnalysis.h.
Referenced by CalculateFrameTM(), CalculateFrameTM(), CalculateFrameTM(), for(), and GetFrameDirs().
BoneName
FName BlendSpaceAnalysis::BoneName
Definition at line 484 of file BlendSpaceAnalysis.h.
Referenced by CalculateBoneOrientation(), CalculateBoneOrientation(), CalculateBoneOrientation(), for(), GetBoneInfo(), GetBoneTransform(), GetFrameDirs(), if(), UE_LOG(), UE_LOG(), UE_LOG(), and UE_LOG().
BoneOffset
FTransform BlendSpaceAnalysis::BoneOffset
Definition at line 483 of file BlendSpaceAnalysis.h.
Referenced by CalculateBoneOrientation(), CalculateBoneOrientation(), CalculateBoneOrientation(), for(), GetBoneInfo(), GetFrameDirs(), and if().
BoneTM1
FTransform BlendSpaceAnalysis::BoneTM1 = GetBoneTransform(Animation, FirstKey, BoneName)
Definition at line 544 of file BlendSpaceAnalysis.h.
BoneTM2
FTransform BlendSpaceAnalysis::BoneTM2 = GetBoneTransform(Animation, LastKey, BoneName)
Definition at line 549 of file BlendSpaceAnalysis.h.
bResult
return BlendSpaceAnalysis::bResult = CalculateComponentSampleValue(DoubleResult, Fn, BlendSpace, AnalysisProperties, Animation, RateScale)
Definition at line 462 of file BlendSpaceAnalysis.h.
Referenced by CalculateComponentSampleValue(), and CalculateComponentSampleValue().
ComponentIndex
int32 BlendSpaceAnalysis::ComponentIndex = (int32)AnalysisProperties->FunctionAxis
Definition at line 438 of file BlendSpaceAnalysis.h.
Referenced by CalculateComponentSampleValue(), CalculateComponentSampleValue(), and if().
DeltaTime
double BlendSpaceAnalysis::DeltaTime = Animation.GetPlayLength() / double(NumSampledKeys)
Definition at line 586 of file BlendSpaceAnalysis.h.
else
BlendSpaceAnalysis::else
Initial value:
{
        Yaw = FMath::RadiansToDegrees(FMath::Atan2(
            FVector::DotProduct(AimForwardDir, FrameRightDir), FVector::DotProduct(AimForwardDir, FrameFacingDir)))
Definition at line 662 of file BlendSpaceAnalysis.h.
false
return BlendSpaceAnalysis::false
Definition at line 444 of file BlendSpaceAnalysis.h.
FirstKey
int32 BlendSpaceAnalysis::FirstKey
Initial value:
= FMath::Clamp(
        (int32) (float(NumSampledKeys) * AnalysisProperties->StartTimeFraction), 0, NumSampledKeys)
Definition at line 490 of file BlendSpaceAnalysis.h.
Referenced by CalculateBoneOrientation(), CalculateFrameTM(), for(), and GetFrameDirs().
Fn
const FunctionType & BlendSpaceAnalysis::Fn
Definition at line 431 of file BlendSpaceAnalysis.h.
Referenced by CalculateComponentSampleValue(), CalculateComponentSampleValue(), CalculateComponentSampleValue(), CalculateComponentSampleValue(), and if().
Forward
const double BlendSpaceAnalysis::Forward = UnYawedAimForwardDir | FrameFacingDir
Definition at line 674 of file BlendSpaceAnalysis.h.
FrameFacingDir
FVector BlendSpaceAnalysis::FrameFacingDir
Definition at line 643 of file BlendSpaceAnalysis.h.
Referenced by CalculateBoneOrientation(), CalculateBoneOrientation(), CalculateBoneOrientation(), CalculateFrameTM(), GetFrameDirs(), GetFrameDirs(), and if().
FrameRightDir
FVector BlendSpaceAnalysis::FrameRightDir
Definition at line 644 of file BlendSpaceAnalysis.h.
Referenced by CalculateBoneOrientation(), CalculateBoneOrientation(), CalculateBoneOrientation(), CalculateFrameTM(), GetFrameDirs(), GetFrameDirs(), if(), and PitchQuat().
FrameTM
FTransform BlendSpaceAnalysis::FrameTM
Definition at line 495 of file BlendSpaceAnalysis.h.
Referenced by CalculateFrameTM(), CalculateFrameTM(), CalculateFrameTM(), for(), GetFrameDirs(), and GetFrameDirs().
FrameUpDir
FVector BlendSpaceAnalysis::FrameUpDir
Initial value:
{
    const FTransform BoneTM = GetBoneTransform(Animation, Key, BoneName)
Definition at line 645 of file BlendSpaceAnalysis.h.
Referenced by CalculateBoneOrientation(), CalculateBoneOrientation(), CalculateBoneOrientation(), CalculateFrameTM(), GetFrameDirs(), GetFrameDirs(), and YawQuat().
Key
const UAnimSequence const int32 BlendSpaceAnalysis::Key
Definition at line 639 of file BlendSpaceAnalysis.h.
Referenced by CalculateBoneOrientation(), for(), GetBoneTransform(), and GetFrameDirs().
LastKey
int32 BlendSpaceAnalysis::LastKey
Initial value:
= FMath::Clamp(
        (int32) (float(NumSampledKeys) * AnalysisProperties->EndTimeFraction), FirstKey, NumSampledKeys)
Definition at line 492 of file BlendSpaceAnalysis.h.
Referenced by CalculateBoneOrientation(), CalculateFrameTM(), for(), and GetFrameDirs().
NumKeys
int32 BlendSpaceAnalysis::NumKeys = FMath::Max(1 + LastKey - FirstKey, 1)
Definition at line 594 of file BlendSpaceAnalysis.h.
Pitch
const double BlendSpaceAnalysis::Pitch = FMath::RadiansToDegrees(FMath::Atan2(Up, Forward))
Definition at line 675 of file BlendSpaceAnalysis.h.
Referenced by PitchQuat(), and Set().
RateScale
const UBlendSpace const T const UAnimSequence const float BlendSpaceAnalysis::RateScale
Initial value:
{
    FVector Value
Definition at line 435 of file BlendSpaceAnalysis.h.
Referenced by CalculateAngularVelocity(), CalculateComponentSampleValue(), CalculateComponentSampleValue(), CalculateComponentSampleValue(), CalculateComponentSampleValue(), CalculateDeltaOrientation(), CalculateDeltaPosition(), CalculateOrientation(), CalculateOrientationRate(), CalculatePosition(), CalculateVelocity(), if(), and UE_DEPRECATED().
RelativePos1
FVector BlendSpaceAnalysis::RelativePos1 = FrameTM.InverseTransformPosition(TM1.GetTranslation())
Definition at line 546 of file BlendSpaceAnalysis.h.
RelativePos2
FVector BlendSpaceAnalysis::RelativePos2 = FrameTM.InverseTransformPosition(TM2.GetTranslation())
Definition at line 551 of file BlendSpaceAnalysis.h.
Result
BlendSpaceAnalysis::Result = float(DoubleResult)
Definition at line 463 of file BlendSpaceAnalysis.h.
Referenced by CalculateAngularVelocity(), CalculateBoneOrientation(), CalculateComponentSampleValue(), CalculateComponentSampleValue(), CalculateComponentSampleValue(), CalculateComponentSampleValue(), CalculateDeltaOrientation(), CalculateDeltaPosition(), CalculateOrientation(), CalculateOrientationRate(), CalculatePosition(), CalculateVelocity(), for(), GetFrameDirs(), if(), if(), Set(), UE_DEPRECATED(), UE_DEPRECATED(), UE_LOG(), UE_LOG(), UE_LOG(), and UE_LOG().
Roll
const double BlendSpaceAnalysis::Roll
Initial value:
= FMath::RadiansToDegrees(FMath::Atan2(
        FVector::DotProduct(UnYawedUnPitchedAimRightDir, -FrameUpDir),
        FVector::DotProduct(UnYawedUnPitchedAimRightDir, FrameRightDir)))
Definition at line 683 of file BlendSpaceAnalysis.h.
Referenced by Set().
RollPitchYaw1
FVector BlendSpaceAnalysis::RollPitchYaw1
Definition at line 782 of file BlendSpaceAnalysis.h.
Referenced by CalculateBoneOrientation(), and CalculateBoneOrientation().
RollPitchYaw2
FVector BlendSpaceAnalysis::RollPitchYaw2
Definition at line 790 of file BlendSpaceAnalysis.h.
Referenced by CalculateBoneOrientation().
TM
const FTransform BlendSpaceAnalysis::TM = BoneOffset * BoneTM
Definition at line 649 of file BlendSpaceAnalysis.h.
Referenced by for(), and GetAxisFromTM().
TM1
FTransform BlendSpaceAnalysis::TM1 = BoneOffset * BoneTM1
Definition at line 545 of file BlendSpaceAnalysis.h.
TM2
FTransform BlendSpaceAnalysis::TM2 = BoneOffset * BoneTM2
Definition at line 550 of file BlendSpaceAnalysis.h.
true
return BlendSpaceAnalysis::true
Definition at line 509 of file BlendSpaceAnalysis.h.
UnYawedAimForwardDir
const FVector BlendSpaceAnalysis::UnYawedAimForwardDir = YawQuat.UnrotateVector(AimForwardDir)
Definition at line 672 of file BlendSpaceAnalysis.h.
UnYawedAimRightDir
const FVector BlendSpaceAnalysis::UnYawedAimRightDir = YawQuat.UnrotateVector(AimRightDir)
Definition at line 678 of file BlendSpaceAnalysis.h.
UnYawedUnPitchedAimRightDir
const FVector BlendSpaceAnalysis::UnYawedUnPitchedAimRightDir = PitchQuat.UnrotateVector(UnYawedAimRightDir)
Definition at line 681 of file BlendSpaceAnalysis.h.
Up
const double BlendSpaceAnalysis::Up = UnYawedAimForwardDir | FrameUpDir
Definition at line 673 of file BlendSpaceAnalysis.h.
Yaw
double BlendSpaceAnalysis::Yaw
Definition at line 653 of file BlendSpaceAnalysis.h.
Referenced by if(), Set(), and YawQuat().