Unreal Engine 5.6 C++ API: TraceServices::PagedArrayAlgo Namespace Reference
TraceServices::PagedArrayAlgo Namespace Reference
Functions
template<typename ItemType, typename PageType>
FORCEINLINE auto BinarySearchClosest (const TPagedArray< ItemType, PageType > &PagedArray, const ItemType &Value) -> decltype(GetNum(PagedArray))
template<typename ItemType, typename PageType, typename SortPredicateType>
FORCEINLINE auto BinarySearchClosest (const TPagedArray< ItemType, PageType > &PagedArray, const ItemType &Value, SortPredicateType SortPredicate) -> decltype(GetNum(PagedArray))
Performs binary search, resulting in position of the first element closest to Value.
template<typename ItemType, typename PageType, typename ValueType, typename ProjectionType>
FORCEINLINE auto BinarySearchClosestBy (const TPagedArray< ItemType, PageType > &PagedArray, const ValueType &Value, ProjectionType Projection) -> decltype(GetNum(PagedArray))
template<typename ItemType, typename PageType, typename ValueType, typename ProjectionType, typename SortPredicateType>
FORCEINLINE auto BinarySearchClosestBy (const TPagedArray< ItemType, PageType > &PagedArray, const ValueType &Value, ProjectionType Projection, SortPredicateType SortPredicate) -> decltype(GetNum(PagedArray))
Performs binary search, resulting in position of the first element with projected value closest to Value.
template<typename ItemType, typename PageType>
FORCEINLINE auto LowerBound (const TPagedArray< ItemType, PageType > &PagedArray, const ItemType &Value) -> decltype(GetNum(PagedArray))
template<typename ItemType, typename PageType, typename SortPredicateType>
FORCEINLINE auto LowerBound (const TPagedArray< ItemType, PageType > &PagedArray, const ItemType &Value, SortPredicateType SortPredicate) -> decltype(GetNum(PagedArray))
Performs binary search, resulting in position of the first element >= Value.
template<typename ItemType, typename PageType, typename ValueType, typename ProjectionType>
FORCEINLINE auto LowerBoundBy (const TPagedArray< ItemType, PageType > &PagedArray, const ValueType &Value, ProjectionType Projection) -> decltype(GetNum(PagedArray))
template<typename ItemType, typename PageType, typename ValueType, typename ProjectionType, typename SortPredicateType>
FORCEINLINE auto LowerBoundBy (const TPagedArray< ItemType, PageType > &PagedArray, const ValueType &Value, ProjectionType Projection, SortPredicateType SortPredicate) -> decltype(GetNum(PagedArray))
Performs binary search, resulting in position of the first element with projected value >= Value.
template<typename ItemType, typename PageType>
FORCEINLINE auto UpperBound (const TPagedArray< ItemType, PageType > &PagedArray, const ItemType &Value) -> decltype(GetNum(PagedArray))
template<typename ItemType, typename PageType, typename SortPredicateType>
FORCEINLINE auto UpperBound (const TPagedArray< ItemType, PageType > &PagedArray, const ItemType &Value, SortPredicateType SortPredicate) -> decltype(GetNum(PagedArray))
Performs binary search, resulting in position of the first element > Value.
template<typename ItemType, typename PageType, typename ValueType, typename ProjectionType>
FORCEINLINE auto UpperBoundBy (const TPagedArray< ItemType, PageType > &PagedArray, const ValueType &Value, ProjectionType Projection) -> decltype(GetNum(PagedArray))
template<typename ItemType, typename PageType, typename ValueType, typename ProjectionType, typename SortPredicateType>
FORCEINLINE auto UpperBoundBy (const TPagedArray< ItemType, PageType > &PagedArray, const ValueType &Value, ProjectionType Projection, SortPredicateType SortPredicate) -> decltype(GetNum(PagedArray))
Performs binary search, resulting in position of the first element with projected value > Value.
Function Documentation
BinarySearchClosest() [1/2]
template<typename ItemType, typename PageType> FORCEINLINE auto TraceServices::PagedArrayAlgo::BinarySearchClosest (const TPagedArray< ItemType, PageType > & PagedArray, const ItemType & Value) -> decltype(GetNum(PagedArray))
Definition at line 1107 of file PagedArray.h.
References TraceServices::PagedArrayAlgoImpl::BinarySearchClosestInternal(), FORCEINLINE, TraceServices::GetNum(), and Value.
BinarySearchClosest() [2/2]
template<typename ItemType, typename PageType, typename SortPredicateType> FORCEINLINE auto TraceServices::PagedArrayAlgo::BinarySearchClosest (const TPagedArray< ItemType, PageType > & PagedArray, const ItemType & Value, SortPredicateType SortPredicate) -> decltype(GetNum(PagedArray))
Performs binary search, resulting in position of the first element closest to Value.
Parameters
PagedArray The paged array to search through; must be already sorted by SortPredicate.
Value The value to look for
SortPredicate The predicate for sort comparison; defaults to <.
Returns
The position of the first element closest to Value; == 0 if Num == 0, otherwise is a value in range [0 .. Num-1].
Definition at line 1101 of file PagedArray.h.
References TraceServices::PagedArrayAlgoImpl::BinarySearchClosestInternal(), FORCEINLINE, TraceServices::GetNum(), and Value.
BinarySearchClosestBy() [1/2]
template<typename ItemType, typename PageType, typename ValueType, typename ProjectionType> FORCEINLINE auto TraceServices::PagedArrayAlgo::BinarySearchClosestBy (const TPagedArray< ItemType, PageType > & PagedArray, const ValueType & Value, ProjectionType Projection) -> decltype(GetNum(PagedArray))
Definition at line 1130 of file PagedArray.h.
References TraceServices::PagedArrayAlgoImpl::BinarySearchClosestInternal(), FORCEINLINE, TraceServices::GetNum(), Projection(), and Value.
BinarySearchClosestBy() [2/2]
template<typename ItemType, typename PageType, typename ValueType, typename ProjectionType, typename SortPredicateType> FORCEINLINE auto TraceServices::PagedArrayAlgo::BinarySearchClosestBy (const TPagedArray< ItemType, PageType > & PagedArray, const ValueType & Value, ProjectionType Projection, SortPredicateType SortPredicate) -> decltype(GetNum(PagedArray))
Performs binary search, resulting in position of the first element with projected value closest to Value.
Parameters
PagedArray The paged array to search through; must be already sorted by SortPredicate.
Value The value to look for
Projection The functor or data member pointer; called via Invoke to compare to Value.
SortPredicate The predicate for sort comparison; defaults to <.
Returns
The position of the first element with projected value closest to Value; == 0 if Num == 0, otherwise is a value in range [0 .. Num-1].
Definition at line 1124 of file PagedArray.h.
References TraceServices::PagedArrayAlgoImpl::BinarySearchClosestInternal(), FORCEINLINE, TraceServices::GetNum(), Projection(), and Value.
LowerBound() [1/2]
template<typename ItemType, typename PageType> FORCEINLINE auto TraceServices::PagedArrayAlgo::LowerBound (const TPagedArray< ItemType, PageType > & PagedArray, const ItemType & Value) -> decltype(GetNum(PagedArray))
Definition at line 1017 of file PagedArray.h.
References FORCEINLINE, TraceServices::GetNum(), TraceServices::PagedArrayAlgoImpl::LowerBoundInternal(), and Value.
LowerBound() [2/2]
template<typename ItemType, typename PageType, typename SortPredicateType> FORCEINLINE auto TraceServices::PagedArrayAlgo::LowerBound (const TPagedArray< ItemType, PageType > & PagedArray, const ItemType & Value, SortPredicateType SortPredicate) -> decltype(GetNum(PagedArray))
Performs binary search, resulting in position of the first element >= Value.
Parameters
PagedArray The paged array to search through; must be already sorted by SortPredicate.
Value The value to look for
SortPredicate Predicate for sort comparison; defaults to <.
Returns
Position of the first element >= Value; may be == Num.
Definition at line 1011 of file PagedArray.h.
References FORCEINLINE, TraceServices::GetNum(), TraceServices::PagedArrayAlgoImpl::LowerBoundInternal(), and Value.
LowerBoundBy() [1/2]
template<typename ItemType, typename PageType, typename ValueType, typename ProjectionType> FORCEINLINE auto TraceServices::PagedArrayAlgo::LowerBoundBy (const TPagedArray< ItemType, PageType > & PagedArray, const ValueType & Value, ProjectionType Projection) -> decltype(GetNum(PagedArray))
Definition at line 1040 of file PagedArray.h.
References FORCEINLINE, TraceServices::GetNum(), TraceServices::PagedArrayAlgoImpl::LowerBoundInternal(), Projection(), and Value.
LowerBoundBy() [2/2]
template<typename ItemType, typename PageType, typename ValueType, typename ProjectionType, typename SortPredicateType> FORCEINLINE auto TraceServices::PagedArrayAlgo::LowerBoundBy (const TPagedArray< ItemType, PageType > & PagedArray, const ValueType & Value, ProjectionType Projection, SortPredicateType SortPredicate) -> decltype(GetNum(PagedArray))
Performs binary search, resulting in position of the first element with projected value >= Value.
Parameters
PagedArray The paged array to search through, must be already sorted by SortPredicate.
Value The value to look for
Projection Functor or data member pointer; called via Invoke to compare to Value.
SortPredicate Predicate for sort comparison; defaults to <.
Returns
Position of the first element with projected value >= Value; may be == Num.
Definition at line 1034 of file PagedArray.h.
References FORCEINLINE, TraceServices::GetNum(), TraceServices::PagedArrayAlgoImpl::LowerBoundInternal(), Projection(), and Value.
UpperBound() [1/2]
template<typename ItemType, typename PageType> FORCEINLINE auto TraceServices::PagedArrayAlgo::UpperBound (const TPagedArray< ItemType, PageType > & PagedArray, const ItemType & Value) -> decltype(GetNum(PagedArray))
Definition at line 1062 of file PagedArray.h.
References FORCEINLINE, TraceServices::GetNum(), TraceServices::PagedArrayAlgoImpl::UpperBoundInternal(), and Value.
UpperBound() [2/2]
template<typename ItemType, typename PageType, typename SortPredicateType> FORCEINLINE auto TraceServices::PagedArrayAlgo::UpperBound (const TPagedArray< ItemType, PageType > & PagedArray, const ItemType & Value, SortPredicateType SortPredicate) -> decltype(GetNum(PagedArray))
Performs binary search, resulting in position of the first element > Value.
Parameters
PagedArray The paged array to search through, must be already sorted by SortPredicate.
Value The value to look for
SortPredicate Predicate for sort comparison; defaults to <.
Returns
Position of the first element > Value; may be == Num.
Definition at line 1056 of file PagedArray.h.
References FORCEINLINE, TraceServices::GetNum(), TraceServices::PagedArrayAlgoImpl::UpperBoundInternal(), and Value.
UpperBoundBy() [1/2]
template<typename ItemType, typename PageType, typename ValueType, typename ProjectionType> FORCEINLINE auto TraceServices::PagedArrayAlgo::UpperBoundBy (const TPagedArray< ItemType, PageType > & PagedArray, const ValueType & Value, ProjectionType Projection) -> decltype(GetNum(PagedArray))
Definition at line 1085 of file PagedArray.h.
References FORCEINLINE, TraceServices::GetNum(), Projection(), TraceServices::PagedArrayAlgoImpl::UpperBoundInternal(), and Value.
UpperBoundBy() [2/2]
template<typename ItemType, typename PageType, typename ValueType, typename ProjectionType, typename SortPredicateType> FORCEINLINE auto TraceServices::PagedArrayAlgo::UpperBoundBy (const TPagedArray< ItemType, PageType > & PagedArray, const ValueType & Value, ProjectionType Projection, SortPredicateType SortPredicate) -> decltype(GetNum(PagedArray))
Performs binary search, resulting in position of the first element with projected value > Value.
Parameters
PagedArray The paged array to search through, must be already sorted by SortPredicate.
Value The value to look for
Projection Functor or data member pointer; called via Invoke to compare to Value.
SortPredicate Predicate for sort comparison; defaults to <.
Returns
Position of the first element with projected value > Value; may be == Num.
Definition at line 1079 of file PagedArray.h.
References FORCEINLINE, TraceServices::GetNum(), Projection(), TraceServices::PagedArrayAlgoImpl::UpperBoundInternal(), and Value.