Unreal Engine 5.6 C++ API: ObjectTools Namespace Reference
ObjectTools Namespace Reference
Data Structures
class FArchiveTopLevelReferenceCollector
An archive for collecting object references that are top-level objects.
struct FConsolidationResults
Helper struct to detail the results of a consolidation operation.
struct FMoveDialogInfo
Information that can be gathered from the move dialog.
class FMoveInfo
Target package and object name for moving an asset.
struct FPackageGroupName
A simple struct to represent the package group name triplet.
struct FReplaceRequest
Helper struct for batch replacements where Old references get replaced with New.
Enumerations
enum class EAllowCancelDuringDelete : uint8 { AllowCancel , CancelNotAllowed }
enum class EAllowCancelDuringPrivatize : uint8 { AllowCancel , CancelNotAllowed }
enum class EInUseSearchFlags : uint32 { None = 0 , SkipCompilingAssets = 1 }
enum EInUseSearchOption { SO_CurrentLevel , SO_VisibleLevels , SO_LoadedLevels }
Options for in use object tagging.
Functions
UNREALED_API void AccumulateObjectReferencersForObjectRecursive (UObject *Object, TArray< UObject * > &Referencers, const bool bRecurseMaterial)
Recursively add the objects referencers to a single array.
UNREALED_API bool AddExtraLocalizedVariantsToDelete (const TArray< FAssetData > &InAssetsToDelete, TArray< FAssetData > &OutAssetsWithVariantsToDelete)
Gathers additional localized variants to delete.
UNREALED_API void AddExtraObjectsToDelete (TArray< UObject * > &ObjectsToDelete)
Gathers additional objects to delete such as map built data.
UNREALED_API void AddLanguageVariants (TArray< UObject * > &OutObjects, TMap< UObject *, FString > &OutObjectToLanguageExtMap, USoundWave *Wave)
Finds all language variants for the passed in sound wave.
UNREALED_API void AppendFactoryFileExtensions (UFactory *InFactory, FString &out_Filetypes, FString &out_Extensions)
Generates a list of file types for a given class.
UNREALED_API void AppendFormatsFileExtensions (const TArray< FString > &InFormats, FString &out_FileTypes, FString &out_Extensions)
Populates two strings with all of the file types and extensions the format list provides.
UNREALED_API void AppendFormatsFileExtensions (const TArray< FString > &InFormats, FString &out_FileTypes, FString &out_Extensions, TMultiMap< uint32, UFactory * > &out_FilterIndexToFactory)
Populates two strings with all of the file types and extensions the format list provides.
UNREALED_API bool AreClassesInterchangeable (const UClass *ClassA, const UClass *ClassB)
Determines if two classes are interchangeable.
UNREALED_API bool AreObjectsOfEquivalantType (const TArray< UObject * > &InProposedObjects)
Determines if an array of objects are all of interchangeable types.
UNREALED_API void AssembleListOfExporters (TArray< UExporter * > &OutExporters)
Iterates over all classes and assembles a list of non-abstract UExport-derived type instances.
UNREALED_API void BatchGetArchetypeInstances (TArrayView< UObject * > InObjects, TArray< TArray< UObject * > > &OutInstances)
Batch version of UObject::GetArchetypeInstances.
UNREALED_API void CleanupAfterSuccessfulDelete (const TArray< UPackage * > &ObjectsDeletedSuccessfully, bool bPerformReferenceCheck=true)
Collects garbage and marks truely empty packages for delete.
UNREALED_API void CompileBlueprintsAfterRefUpdate (const TArray< UObject * > &ObjectsConsolidatedWithin)
UNREALED_API bool ComposeStringOfReferencingObjects (TArray< FReferencerInformation > &References, FString &RefObjNames, FString &DefObjNames)
Utility function to compose a string list of referencing objects.
UNREALED_API FConsolidationResults ConsolidateObjects (TArrayView< FReplaceRequest > Requests, TSet< UObject * > &ObjectsToConsolidateWithin, TSet< UObject * > &ObjectsToNotConsolidateWithin, bool bShouldDeleteAfterConsolidate, bool bWarnAboutRootSet=true)
UNREALED_API FConsolidationResults ConsolidateObjects (UObject *ObjectToConsolidateTo, TArray< UObject * > &ObjectsToConsolidate, bool bShowDeleteConfirmation=true)
Consolidates objects by replacing all references/uses of the provided "objects to consolidate" with references to the "object to consolidate to." This is useful for situations such as when a particular asset is duplicated in multiple places and it would be handy to allow all uses to point to one particular copy of the asset.
UNREALED_API FConsolidationResults ConsolidateObjects (UObject *ObjectToConsolidateTo, TArray< UObject * > &ObjectsToConsolidate, TSet< UObject * > &ObjectsToConsolidateWithin, TSet< UObject * > &ObjectsToNotConsolidateWithin, bool bShouldDeleteAfterConsolidate, bool bWarnAboutRootSet=true)
UNREALED_API void CopyReferences (const TArray< UObject * > &SelectedObjects)
Copies references for selected generic browser objects to the clipboard.
UNREALED_API int32 DeleteAssets (const TArray< FAssetData > &AssetsToDelete, bool bShowConfirmation=true)
Deletes the list of objects.
UNREALED_API int32 DeleteObjects (const TArray< UObject * > &ObjectsToDelete, bool bShowConfirmation=true, EAllowCancelDuringDelete AllowCancelDuringDelete=EAllowCancelDuringDelete::AllowCancel)
Deletes the list of objects.
UNREALED_API int32 DeleteObjectsUnchecked (const TArray< UObject * > &ObjectsToDelete)
Deletes the list of objects without checking if they are still being used.
UNREALED_API void DeleteRedirector (UObjectRedirector *Redirector)
Sends the redirector to the deleted redirectors package where it will be cleaned up later.
UNREALED_API bool DeleteSingleObject (UObject *ObjectToDelete, bool bPerformReferenceCheck=true)
Delete a single object.
UNREALED_API void DuplicateObjects (const TArray< UObject * > &SelectedObjects, const FString &SourcePath=TEXT(""), const FString &DestinationPath=TEXT(""), bool bOpenDialog=true, TArray< UObject * > *OutNewObjects=NULL)
Duplicates a list of objects.
UNREALED_API UObject * DuplicateSingleObject (UObject *Object, const FPackageGroupName &PGN, TSet< UPackage * > &InOutPackagesUserRefusedToFullyLoad, bool bPromptToOverwrite=true, TMap< TSoftObjectPtr< UObject >, TSoftObjectPtr< UObject > > *DuplicatedObjects=nullptr)
Duplicates a single object.
ENUM_CLASS_FLAGS (EInUseSearchFlags)
UNREALED_API int32 ForceDeleteObjects (const TArray< UObject * > &ObjectsToDelete, bool ShowConfirmation=true)
Deletes the list of objects.
UNREALED_API void ForceReplaceReferences (TArrayView< FReplaceRequest > Requests, TSet< UObject * > &ObjectsToReplaceWithin)
UNREALED_API void ForceReplaceReferences (UObject *ObjectToReplaceWith, TArray< UObject * > &ObjectsToReplace)
Forcefully replaces references to passed in objects.
UNREALED_API void ForceReplaceReferences (UObject *ObjectToReplaceWith, TArray< UObject * > &ObjectsToReplace, TSet< UObject * > &ObjectsToReplaceWithin)
UNREALED_API void GatherObjectReferencersForDeletion (UObject *InObject, bool &bOutIsReferenced, bool &bOutIsReferencedByUndo, FReferencerInformationList *OutMemoryReferences=nullptr, bool bInRequireReferencingProperties=false)
Find referencers of an object to be deleted.
UNREALED_API bool GatherPropertyChainsToObject (const UObject *SourceObject, const UObject *ObjectToSearchFor, TArray< FString > &OutFoundPropertyChains)
Given a SourceObject and ObjectToSearchFor will attempt to find the ObjectToSearchFor on the given object.
UNREALED_API void GatherSubObjectsForReferenceReplacement (TSet< UObject * > &InObjects, TSet< UObject * > &ObjectsToExclude, TSet< UObject * > &OutObjectsAndSubObjects)
Find any subobjects that might also need references replaced for a deep copy.
UNREALED_API void GenerateFactoryFileExtensions (const TArray< UFactory * > &InFactories, FString &out_Filetypes, FString &out_Extensions, TMultiMap< uint32, UFactory * > &out_FilterIndexToFactory)
Populates two strings with all of the file types and extensions the provided factories support.
UNREALED_API void GenerateFactoryFileExtensions (const UFactory *InFactory, FString &out_Filetypes, FString &out_Extensions, TMultiMap< uint32, UFactory * > &out_FilterIndexToFactory)
Populates two strings with all of the file types and extensions the provided factory supports.
UNREALED_API FString GetDefaultTooltipForFunction (const UFunction *Function)
Gets the non-specific tooltip for the given UFunction.
UNREALED_API void GetDirectoryFromObjectPath (const UObject *Obj, FString &OutResult)
Assembles a path from the outer chain of the specified object.
UNREALED_API bool GetMoveDialogInfo (const FText &DialogTitle, UObject *Object, bool bUniqueDefaultName, const FString &SourcePath, const FString &DestinationPath, FMoveDialogInfo &InOutInfo)
Helper function for RenameObjectsInternal.
UNREALED_API FText GetUserFacingFunctionName (const UFunction *Function, bool bAllowFriendlyNames=false)
Gets the user-facing name for the given UFunction.
bool HandleFullyLoadingPackages (const TArray< UObject * > &Objects, const FText &OperationText)
Handles fully loading packages for a set of passed in objects.
UNREALED_API bool IsClassRedirector (const UClass *Class)
Determines if a given class is a redirector.
UNREALED_API bool IsClassValidForPlacing (const UClass *InClass)
Determines if the class is placeable in a world.
UNREALED_API bool IsObjectBrowsable (UObject *Obj)
Returns true if the specified object can be displayed in a content browser.
UNREALED_API TSharedPtr< SWindow > OpenPropertiesForSelectedObjects (const TArray< UObject * > &SelectedObjects)
Opens a property window for the selected objects.
UNREALED_API int32 PrivatizeAssets (const TArray< FAssetData > &AssetsToPrivatize, bool bShowConfirmation=true, const EAssetAccessSpecifier InAssetAccessSpecifier=EAssetAccessSpecifier::Private)
Privatizes the list of Assets (marks their packages as NotExternallyReferenceable)
UNREALED_API int32 PrivatizeObjects (const TArray< UObject * > &InObjectsToPrivatize, bool bShowConfirmation=true, EAllowCancelDuringPrivatize AllowCancelDuringPrivatize=EAllowCancelDuringPrivatize::AllowCancel, const EAssetAccessSpecifier InAssetAccessSpecifier=EAssetAccessSpecifier::Private)
Privatizes the list of objects (marks their packages as NotExternallyReferencable)
UNREALED_API void RemoveDeletedObjectsFromPropertyWindows (TArray< UObject * > &DeletedObjects)
Removes deleted objects from open property windows.
UNREALED_API bool RenameObjects (const TArray< UObject * > &SelectedObjects, bool bIncludeLocInstances, const FString &SourcePath=TEXT(""), const FString &DestinationPath=TEXT(""), bool bOpenDialog=true)
Renames an object and leaves redirectors so other content that references it does not break Also renames all loc instances of the same asset.
UNREALED_API bool RenameObjectsInternal (const TArray< UObject * > &Objects, bool bLocPackages, const TMap< UObject *, FString > *ObjectToLanguageExtMap, const FString &SourcePath, const FString &DestinationPath, bool bOpenDialog)
Internal implementation of rename objects with refs.
UNREALED_API bool RenameSingleObject (UObject *Object, FPackageGroupName &PGN, TSet< UPackage * > &InOutPackagesUserRefusedToFullyLoad, FText &InOutErrorMessage, const TMap< UObject *, FString > *ObjectToLanguageExtMap=NULL, bool bLeaveRedirector=true)
Renames a single object.
UNREALED_API FString SanitizeInvalidChars (const FString &InText, const FString &InvalidChars)
Converts all specified invalid characters to _.
UNREALED_API FString SanitizeInvalidChars (const FString &InText, const TCHAR *InvalidChars)
Converts all specified invalid characters to _.
UNREALED_API void SanitizeInvalidCharsInline (FString &InText, const TCHAR *InvalidChars)
Converts all specified invalid characters to _.
UNREALED_API FString SanitizeObjectName (const FString &InObjectName)
Converts all invalid object name characters to _.
UNREALED_API FString SanitizeObjectPath (const FString &InObjectPath)
Converts all invalid object path characters to _.
UNREALED_API void SelectActorsInLevelDirectlyReferencingObject (UObject *RefObj)
Select the object referencers in the level.
UNREALED_API void SelectObjectAndExternalReferencersInLevel (UObject *Object, const bool bRecurseMaterial)
Select the object and it's external referencers' referencers in the level.
bool ShowDeleteConfirmationDialog (const TArray< UObject * > &ObjectsToDelete)
Shows a confirmation dialog asking the user if it is ok to delete the packages containing the supplied objects.
UNREALED_API void ShowReferencedObjs (UObject *Object)
Displays all of the objects the passed in object references.
UNREALED_API void ShowReferencedObjs (UObject *Object, ICollectionContainer *CollectionContainer, FName CollectionName, ECollectionShareType::Type ShareType)
Displays all of the objects the passed in object references.
UNREALED_API void ShowReferenceGraph (UObject *ObjectToGraph)
Displays a tree(currently) of all assets which reference the passed in object.
UNREALED_API void ShowReferencers (const TArray< UObject * > &SelectedObjects)
UNREALED_API void TagInUseObjects (EInUseSearchOption SearchOption, EInUseSearchFlags InUseSearchFlags=EInUseSearchFlags::None)
Tags objects which are in use by levels specified by the search option.
UE_DEPRECATED (5.1, "No longer used.") UNREALED_API bool IsAssetValidForPlacing(UWorld *InWorld
UE_DEPRECATED (5.6, "Use the ICollectionContainer overload instead.") UNREALED_API void ShowReferencedObjs(UObject *Object
Displays all of the objects the passed in object references.
Variables
const FString & CollectionName
const FString & ObjectPath
const FString ECollectionShareType::Type ShareType = ECollectionShareType::CST_Private)
Enumeration Type Documentation
EAllowCancelDuringDelete
enum class ObjectTools::EAllowCancelDuringDelete : uint8 strong
Enumerator
AllowCancel
CancelNotAllowed
Definition at line 134 of file ObjectTools.h.
EAllowCancelDuringPrivatize
enum class ObjectTools::EAllowCancelDuringPrivatize : uint8 strong
Enumerator
AllowCancel
CancelNotAllowed
Definition at line 140 of file ObjectTools.h.
EInUseSearchFlags
enum class ObjectTools::EInUseSearchFlags : uint32 strong
Enumerator
None
SkipCompilingAssets
Definition at line 593 of file ObjectTools.h.
EInUseSearchOption
enum ObjectTools::EInUseSearchOption
Options for in use object tagging.
Enumerator
SO_CurrentLevel
SO_VisibleLevels
SO_LoadedLevels
Definition at line 586 of file ObjectTools.h.
Function Documentation
AccumulateObjectReferencersForObjectRecursive()
UNREALED_API void ObjectTools::AccumulateObjectReferencersForObjectRecursive (UObject * Object, TArray< UObject * > & Referencers, const bool bRecurseMaterial)
Recursively add the objects referencers to a single array.
Parameters
Object Object whose references are to be selected
Referencers Array of objects being referenced in level
bRecurseMaterial Whether or not we're allowed to recurse the material
References AccumulateObjectReferencersForObjectRecursive(), and Object.
Referenced by AccumulateObjectReferencersForObjectRecursive().
AddExtraLocalizedVariantsToDelete()
UNREALED_API bool ObjectTools::AddExtraLocalizedVariantsToDelete (const TArray< FAssetData > & InAssetsToDelete, TArray< FAssetData > & OutAssetsWithVariantsToDelete)
Gathers additional localized variants to delete.
Parameters
InAssetsToDelete Initial list of assets to delete
OutAssetsWithVariantsToDelete Final list of assets to delete (initial + variants if the user requested it)
Returns
Whether or not the function succeeded. If it returns false, the delete process should be interrupted.
References AddExtraLocalizedVariantsToDelete().
Referenced by AddExtraLocalizedVariantsToDelete().
AddExtraObjectsToDelete()
UNREALED_API void ObjectTools::AddExtraObjectsToDelete (TArray< UObject * > & ObjectsToDelete)
Gathers additional objects to delete such as map built data.
Parameters
ObjectsToDelete List of objects to delete that is appended by additional objects that should be deleted
References AddExtraObjectsToDelete().
Referenced by AddExtraObjectsToDelete().
AddLanguageVariants()
UNREALED_API void ObjectTools::AddLanguageVariants (TArray< UObject * > & OutObjects, TMap< UObject *, FString > & OutObjectToLanguageExtMap, USoundWave * Wave)
Finds all language variants for the passed in sound wave.
Parameters
OutObjects A list of found localized sound wave objects
OutObjectToLanguageExtMap A mapping of sound wave objects to their language extension
Wave The sound wave to search for
References Wave.
AppendFactoryFileExtensions()
UNREALED_API void ObjectTools::AppendFactoryFileExtensions (UFactory * InFactory, FString & out_Filetypes, FString & out_Extensions)
Generates a list of file types for a given class.
Parameters
SupportedExtensions If not null only extension in the list can be added
AppendFormatsFileExtensions() [1/2]
UNREALED_API void ObjectTools::AppendFormatsFileExtensions (const TArray< FString > & InFormats, FString & out_FileTypes, FString & out_Extensions)
Populates two strings with all of the file types and extensions the format list provides.
Parameters
InFormats Array of supported file types. Each entry needs to be of the form "ext;Description" where ext is the file extension.
out_FileTypes File types supported by the provided array of formats, concatenated into a string
out_Extensions Extensions supported by the provided array of formats, concatenated into a string
SupportedExtensions If not null only extension in the list can be added
AppendFormatsFileExtensions() [2/2]
UNREALED_API void ObjectTools::AppendFormatsFileExtensions (const TArray< FString > & InFormats, FString & out_FileTypes, FString & out_Extensions, TMultiMap< uint32, UFactory * > & out_FilterIndexToFactory)
Populates two strings with all of the file types and extensions the format list provides.
Parameters
InFormats Array of supported file types. Each entry needs to be of the form "ext;Description" where ext is the file extension.
out_FileTypes File types supported by the provided array of formats, concatenated into a string
out_Extensions Extensions supported by the provided array of formats, concatenated into a string
out_FilterIndexToFactory Add INDEX_NONE entry for all provided Formats
SupportedExtensions If not null only extension in the list can be added
AreClassesInterchangeable()
UNREALED_API bool ObjectTools::AreClassesInterchangeable (const UClass * ClassA, const UClass * ClassB)
Determines if two classes are interchangeable.
This would tell you if you could substitute one object reference for another. For example, Material and MaterialInstances are interchangeable.
Parameters
ClassA The first class
ClassB The second class
Returns
true if they are interchangeable otherwise false.
References AreClassesInterchangeable().
Referenced by AreClassesInterchangeable().
AreObjectsOfEquivalantType()
UNREALED_API bool ObjectTools::AreObjectsOfEquivalantType (const TArray< UObject * > & InProposedObjects)
Determines if an array of objects are all of interchangeable types.
Parameters
InProposedObjects The objects to check.
Returns
true if all objects are interchangeable, otherwise false.
References AreObjectsOfEquivalantType().
Referenced by AreObjectsOfEquivalantType().
AssembleListOfExporters()
UNREALED_API void ObjectTools::AssembleListOfExporters (TArray< UExporter * > & OutExporters)
Iterates over all classes and assembles a list of non-abstract UExport-derived type instances.
BatchGetArchetypeInstances()
UNREALED_API void ObjectTools::BatchGetArchetypeInstances (TArrayView< UObject * > InObjects, TArray< TArray< UObject * > > & OutInstances)
Batch version of UObject::GetArchetypeInstances.
Can be considerably faster in large worlds when querying multiple objects with the same UClass, as it only traverses the world once per UClass. Null pointers are allowed for InObjects, returning an empty output.
Parameters
InObjects list of objects to query for archetype instances
OutInstances per InObjects array element, receives the list of objects which have the given object in its archetype chain
References BatchGetArchetypeInstances().
Referenced by BatchGetArchetypeInstances().
CleanupAfterSuccessfulDelete()
UNREALED_API void ObjectTools::CleanupAfterSuccessfulDelete (const TArray< UPackage * > & ObjectsDeletedSuccessfully, bool bPerformReferenceCheck = true)
Collects garbage and marks truely empty packages for delete.
Parameters
ObjectsDeletedSuccessfully The list of objects that were recently deleted but not yet cleaned up
References CleanupAfterSuccessfulDelete().
Referenced by CleanupAfterSuccessfulDelete().
CompileBlueprintsAfterRefUpdate()
UNREALED_API void ObjectTools::CompileBlueprintsAfterRefUpdate (const TArray< UObject * > & ObjectsConsolidatedWithin)
ComposeStringOfReferencingObjects()
UNREALED_API bool ObjectTools::ComposeStringOfReferencingObjects (TArray< FReferencerInformation > & References, FString & RefObjNames, FString & DefObjNames)
Utility function to compose a string list of referencing objects.
Parameters
References Array of references to the relevant object
RefObjNames String list of all objects
DefObjNames String list of all objects referenced in default properties
Returns
Whether or not any objects are in default properties
References ComposeStringOfReferencingObjects().
Referenced by ComposeStringOfReferencingObjects().
ConsolidateObjects() [1/3]
UNREALED_API FConsolidationResults ObjectTools::ConsolidateObjects (TArrayView< FReplaceRequest > Requests, TSet< UObject * > & ObjectsToConsolidateWithin, TSet< UObject * > & ObjectsToNotConsolidateWithin, bool bShouldDeleteAfterConsolidate, bool bWarnAboutRootSet = true)
ConsolidateObjects() [2/3]
UNREALED_API FConsolidationResults ObjectTools::ConsolidateObjects (UObject * ObjectToConsolidateTo, TArray< UObject * > & ObjectsToConsolidate, bool bShowDeleteConfirmation = true)
Consolidates objects by replacing all references/uses of the provided "objects to consolidate" with references to the "object to consolidate to." This is useful for situations such as when a particular asset is duplicated in multiple places and it would be handy to allow all uses to point to one particular copy of the asset.
When executed, the function first attempts to directly replace all relevant references located within objects that are already loaded and in memory. Next, it deletes the "objects to consolidate," leaving behind object redirectors to the "object to consolidate to" in their wake.
Parameters
ObjectToConsolidateTo Object to which all references of the "objects to consolidate" will instead refer to after this operation completes
ObjectsToConsolidate Objects which all references of which will be replaced with references to the "object to consolidate to"; each will also be deleted
Requests Batch of consolidations. All objects consilidated to, i.e. FReplaceRequest::New, must be non-null.
Note
This function performs NO type checking, by design. It is potentially dangerous to replace references of one type with another, so utilize caution.
The "objects to consolidate" are DELETED by this function.
Returns
Structure of consolidation results, specifying which packages were dirtied, which objects failed consolidation (if any), etc.
ConsolidateObjects() [3/3]
UNREALED_API FConsolidationResults ObjectTools::ConsolidateObjects (UObject * ObjectToConsolidateTo, TArray< UObject * > & ObjectsToConsolidate, TSet< UObject * > & ObjectsToConsolidateWithin, TSet< UObject * > & ObjectsToNotConsolidateWithin, bool bShouldDeleteAfterConsolidate, bool bWarnAboutRootSet = true)
CopyReferences()
UNREALED_API void ObjectTools::CopyReferences (const TArray< UObject * > & SelectedObjects)
Copies references for selected generic browser objects to the clipboard.
DeleteAssets()
UNREALED_API int32 ObjectTools::DeleteAssets (const TArray< FAssetData > & AssetsToDelete, bool bShowConfirmation = true)
Deletes the list of objects.
Parameters
AssetsToDelete The list of assets to delete
bShowConfirmation True when a dialog should prompt the user that they are about to delete something
Returns
The number of assets successfully deleted
References DeleteAssets().
Referenced by DeleteAssets().
DeleteObjects()
UNREALED_API int32 ObjectTools::DeleteObjects (const TArray< UObject * > & ObjectsToDelete, bool bShowConfirmation = true, EAllowCancelDuringDelete AllowCancelDuringDelete = EAllowCancelDuringDelete::AllowCancel)
Deletes the list of objects.
Parameters
ObjectsToDelete The list of objects to delete
bShowConfirmation True when a dialog should prompt the user that they are about to delete something
Returns
The number of objects successfully deleted
References AllowCancel, and DeleteObjects().
Referenced by DeleteObjects().
DeleteObjectsUnchecked()
UNREALED_API int32 ObjectTools::DeleteObjectsUnchecked (const TArray< UObject * > & ObjectsToDelete)
Deletes the list of objects without checking if they are still being used.
This should not be called directly this is primarily used by the delete system after it has done the work of making sure it's safe to delete.
Parameters
ObjectsToDelete The list of objects to delete
Returns
The number of objects successfully deleted
References DeleteObjectsUnchecked().
Referenced by DeleteObjectsUnchecked().
DeleteRedirector()
UNREALED_API void ObjectTools::DeleteRedirector (UObjectRedirector * Redirector)
Sends the redirector to the deleted redirectors package where it will be cleaned up later.
DeleteSingleObject()
UNREALED_API bool ObjectTools::DeleteSingleObject (UObject * ObjectToDelete, bool bPerformReferenceCheck = true)
Delete a single object.
Parameters
ObjectToDelete The object to delete
Returns
If the object was successfully
References DeleteSingleObject().
Referenced by DeleteSingleObject().
DuplicateObjects()
UNREALED_API void ObjectTools::DuplicateObjects (const TArray< UObject * > & SelectedObjects, const FString & SourcePath = TEXT(""), const FString & DestinationPath = TEXT(""), bool bOpenDialog = true, TArray< UObject * > * OutNewObjects = NULL)
Duplicates a list of objects.
Parameters
SelectedObjects The objects to delete.
SourcePath A path to use to form a relative path for the copied objects.
DestinationPath A path to use as a default destination for the copied objects.
OpenDialog If true, a dialog will open to prompt the user for path information.
OutNewObjects If non-NULL, returns the list of duplicated objects.
DuplicateSingleObject()
UNREALED_API UObject * ObjectTools::DuplicateSingleObject (UObject * Object, const FPackageGroupName & PGN, TSet< UPackage * > & InOutPackagesUserRefusedToFullyLoad, bool bPromptToOverwrite = true, TMap< TSoftObjectPtr< UObject >, TSoftObjectPtr< UObject > > * DuplicatedObjects = nullptr)
Duplicates a single object.
Parameters
Object The objects to delete.
PGN The new package, group, and name of the object.
InOutPackagesUserRefusedToFullyLoad A set of packages the user opted out of fully loading. This is used internally to prevent asking multiple times.
bPromptToOverwrite If true the user will be prompted to overwrite if duplicating to an existing object. If false, the duplication will always happen
DuplicatedObjects If non-null, the map is filled with all objects (including sub-objects) that were duplicated with their source object as key @retun The duplicated object or NULL if a failure occurred.
References Object.
ENUM_CLASS_FLAGS()
ObjectTools::ENUM_CLASS_FLAGS (EInUseSearchFlags)
ForceDeleteObjects()
UNREALED_API int32 ObjectTools::ForceDeleteObjects (const TArray< UObject * > & ObjectsToDelete, bool ShowConfirmation = true)
Deletes the list of objects.
Parameters
ObjectsToDelete The list of objects to delete
ShowConfirmation Show the confirmation dialog.
Returns
The number of objects successfully deleted
References ForceDeleteObjects().
Referenced by ForceDeleteObjects().
ForceReplaceReferences() [1/3]
UNREALED_API void ObjectTools::ForceReplaceReferences (TArrayView< FReplaceRequest > Requests, TSet< UObject * > & ObjectsToReplaceWithin)
References ForceReplaceReferences().
ForceReplaceReferences() [2/3]
UNREALED_API void ObjectTools::ForceReplaceReferences (UObject * ObjectToReplaceWith, TArray< UObject * > & ObjectsToReplace)
Forcefully replaces references to passed in objects.
Parameters
ObjectToReplaceWith Any references found to 'ObjectsToReplace' will be replaced with this object. If the object is nullptr references will be nulled.
ObjectsToReplace An array of objects that should be replaced with 'ObjectToReplaceWith'
Requests Batch of replacements where all FReplaceRequest::Old are replaced with FReplaceRequest::New for each request
References ForceReplaceReferences().
Referenced by ForceReplaceReferences(), ForceReplaceReferences(), and ForceReplaceReferences().
ForceReplaceReferences() [3/3]
UNREALED_API void ObjectTools::ForceReplaceReferences (UObject * ObjectToReplaceWith, TArray< UObject * > & ObjectsToReplace, TSet< UObject * > & ObjectsToReplaceWithin)
References ForceReplaceReferences().
GatherObjectReferencersForDeletion()
UNREALED_API void ObjectTools::GatherObjectReferencersForDeletion (UObject * InObject, bool & bOutIsReferenced, bool & bOutIsReferencedByUndo, FReferencerInformationList * OutMemoryReferences = nullptr, bool bInRequireReferencingProperties = false)
Find referencers of an object to be deleted.
Parameters
InObject The object to be deleted.
bOutIsReferenced Set if the object is currently referenced
bOutIsReferencedByUndo Set if the object is currently referenced by an undo transaction
OutMemoryReferences Optional pointer if specific information is required about referencers
bInRequireReferencingProperties Whether referencing properties information should be filled. (Opt-in only has it can degrade performance)
References GatherObjectReferencersForDeletion().
Referenced by GatherObjectReferencersForDeletion().
GatherPropertyChainsToObject()
UNREALED_API bool ObjectTools::GatherPropertyChainsToObject (const UObject * SourceObject, const UObject * ObjectToSearchFor, TArray< FString > & OutFoundPropertyChains)
Given a SourceObject and ObjectToSearchFor will attempt to find the ObjectToSearchFor on the given object.
If the ObjectToSearchFor is found this will report back properties needed to traverse to find this pointer. This is useful to find out where a reference is being pulled in from.
Uses the CVar ObjectTools.MaxTimesToCheckSameObject to configure how many times the same object should be checked and traversed. This is to help avoid circular dependencies.
Parameters
SourceObject - which object we will scan the properties on to attempt to find the given ObjectToSearchFor
ObjectToSearchFor - which object we will look for on each property of the SourceObject
OutFoundPropertyChains - an array of strings for which properties to traverse to find the ObjectToSearchFor
Returns
true when the ObjectToSearchFor is found, otherwise false.
References GatherPropertyChainsToObject().
Referenced by GatherPropertyChainsToObject().
GatherSubObjectsForReferenceReplacement()
UNREALED_API void ObjectTools::GatherSubObjectsForReferenceReplacement (TSet< UObject * > & InObjects, TSet< UObject * > & ObjectsToExclude, TSet< UObject * > & OutObjectsAndSubObjects)
Find any subobjects that might also need references replaced for a deep copy.
Parameters
InObjects The objects that are going to have their references replaced
ObjectsToExclude Any objects that should not have their references replaced
OutObjectsAndSubobjects The complete list of objects and any subobjects that should have references replaced
References GatherSubObjectsForReferenceReplacement().
Referenced by GatherSubObjectsForReferenceReplacement().
GenerateFactoryFileExtensions() [1/2]
UNREALED_API void ObjectTools::GenerateFactoryFileExtensions (const TArray< UFactory * > & InFactories, FString & out_Filetypes, FString & out_Extensions, TMultiMap< uint32, UFactory * > & out_FilterIndexToFactory)
Populates two strings with all of the file types and extensions the provided factories support.
Parameters
InFactories Factories whose supported file types and extensions should be retrieved
out_Filetypes File types supported by the provided factory, concatenated into a string
out_Extensions Extensions supported by the provided factory, concatenated into a string
SupportedExtensions If not null only extension in the list can be added
GenerateFactoryFileExtensions() [2/2]
UNREALED_API void ObjectTools::GenerateFactoryFileExtensions (const UFactory * InFactory, FString & out_Filetypes, FString & out_Extensions, TMultiMap< uint32, UFactory * > & out_FilterIndexToFactory)
Populates two strings with all of the file types and extensions the provided factory supports.
Parameters
InFactory Factory whose supported file types and extensions should be retrieved
out_Filetypes File types supported by the provided factory, concatenated into a string
out_Extensions Extensions supported by the provided factory, concatenated into a string
SupportedExtensions If not null only extension in the list can be added
GetDefaultTooltipForFunction()
UNREALED_API FString ObjectTools::GetDefaultTooltipForFunction (const UFunction * Function)
Gets the non-specific tooltip for the given UFunction.
Parameters
Function the function to find the tooltip for
Returns
the tooltip as a string
References Function, and GetDefaultTooltipForFunction().
Referenced by GetDefaultTooltipForFunction().
GetDirectoryFromObjectPath()
UNREALED_API void ObjectTools::GetDirectoryFromObjectPath (const UObject * Obj, FString & OutResult)
Assembles a path from the outer chain of the specified object.
GetMoveDialogInfo()
UNREALED_API bool ObjectTools::GetMoveDialogInfo (const FText & DialogTitle, UObject * Object, bool bUniqueDefaultName, const FString & SourcePath, const FString & DestinationPath, FMoveDialogInfo & InOutInfo)
Helper function for RenameObjectsInternal.
This function Updates a FMoveDialogInfo with information from the user. If OkToAll was pressed, it simply updates the relevant information.
Parameters
DialogTitle The title text for the dialog, if it opens
Object The object for which to provide move information.
bUniqueDefaultName If true, when the user is prompted for a name the default supplied name will be unique.
SourcePath A path to use to form a relative path for the renamed objects.
DestinationPath The default target path for the objects. If empty string, the default will be based on the the package name.
InOutInfo The information gathered from the move dialog.
Returns
true if the move information was successfully extracted from the dialog.
References Object.
GetUserFacingFunctionName()
UNREALED_API FText ObjectTools::GetUserFacingFunctionName (const UFunction * Function, bool bAllowFriendlyNames = false)
Gets the user-facing name for the given UFunction.
Parameters
Function the function to find the name for
bAllowFriendlyNames set to true if you will allow a FriendlyName (name with spaces which does not match the Function's Name)
Returns
the name as localized text
References Function, and GetUserFacingFunctionName().
Referenced by GetUserFacingFunctionName().
HandleFullyLoadingPackages()
bool ObjectTools::HandleFullyLoadingPackages (const TArray< UObject * > & Objects, const FText & OperationText)
Handles fully loading packages for a set of passed in objects.
Parameters
Objects Array of objects whose packages need to be fully loaded
OperationString Localization key for a string describing the operation; appears in the warning string presented to the user.
Returns
true if all packages where fully loaded, false otherwise
IsClassRedirector()
UNREALED_API bool ObjectTools::IsClassRedirector (const UClass * Class)
Determines if a given class is a redirector.
Parameters
Class The class
Returns
true if the class is a redirector, otherwise false.
References Class, and IsClassRedirector().
Referenced by IsClassRedirector().
IsClassValidForPlacing()
UNREALED_API bool ObjectTools::IsClassValidForPlacing (const UClass * InClass)
Determines if the class is placeable in a world.
Parameters
InClass Class to test.
Returns
true if the class can be placed in the world.
References IsClassValidForPlacing().
Referenced by IsClassValidForPlacing().
IsObjectBrowsable()
UNREALED_API bool ObjectTools::IsObjectBrowsable (UObject * Obj)
Returns true if the specified object can be displayed in a content browser.
OpenPropertiesForSelectedObjects()
UNREALED_API TSharedPtr< SWindow > ObjectTools::OpenPropertiesForSelectedObjects (const TArray< UObject * > & SelectedObjects)
Opens a property window for the selected objects.
Parameters
SelectedObjects The objects to view in the property window
Returns
Pointer to the new properties window.
PrivatizeAssets()
UNREALED_API int32 ObjectTools::PrivatizeAssets (const TArray< FAssetData > & AssetsToPrivatize, bool bShowConfirmation = true, const EAssetAccessSpecifier InAssetAccessSpecifier = EAssetAccessSpecifier::Private)
Privatizes the list of Assets (marks their packages as NotExternallyReferenceable)
Parameters
AssetsToPrivatize The list of assets to privatize
bShowConfirmation True when a dialog should prompt the user that they are about to privatize something and going to break references
Returns
The number of assets successfully privatized
References Private, and PrivatizeAssets().
Referenced by PrivatizeAssets().
PrivatizeObjects()
UNREALED_API int32 ObjectTools::PrivatizeObjects (const TArray< UObject * > & InObjectsToPrivatize, bool bShowConfirmation = true, EAllowCancelDuringPrivatize AllowCancelDuringPrivatize = EAllowCancelDuringPrivatize::AllowCancel, const EAssetAccessSpecifier InAssetAccessSpecifier = EAssetAccessSpecifier::Private)
Privatizes the list of objects (marks their packages as NotExternallyReferencable)
Parameters
InObjectsToPrivatize The list of objects to privatize
bShowConfirmation True when the dialog should prompt the user that they are about to privatize something and doing so would break references
AllowCancelDuringPrivatize Whether or not canceling is allowed when not showing the confirmation dialog
Returns
The number of objects successfully privatized
References AllowCancel, Private, and PrivatizeObjects().
Referenced by PrivatizeObjects().
RemoveDeletedObjectsFromPropertyWindows()
UNREALED_API void ObjectTools::RemoveDeletedObjectsFromPropertyWindows (TArray< UObject * > & DeletedObjects)
Removes deleted objects from open property windows.
Parameters
DeletedObjects The objects to remove
RenameObjects()
UNREALED_API bool ObjectTools::RenameObjects (const TArray< UObject * > & SelectedObjects, bool bIncludeLocInstances, const FString & SourcePath = TEXT(""), const FString & DestinationPath = TEXT(""), bool bOpenDialog = true)
Renames an object and leaves redirectors so other content that references it does not break Also renames all loc instances of the same asset.
Parameters
Objects The objects to rename
bIncludeLocInstances If true, the objects belong in localized packages
SourcePath A path to use to form a relative path for the renamed objects.
DestinationPath The default target path for the objects. If empty string, the default will be based on the the package name.
OpenDialog If true, a dialog will open to prompt the user for path information.
Returns
true when all objects were renamed successfully
RenameObjectsInternal()
UNREALED_API bool ObjectTools::RenameObjectsInternal (const TArray< UObject * > & Objects, bool bLocPackages, const TMap< UObject *, FString > * ObjectToLanguageExtMap, const FString & SourcePath, const FString & DestinationPath, bool bOpenDialog)
Internal implementation of rename objects with refs.
Parameters
Objects The objects to rename
bLocPackages If true, the objects belong in localized packages
ObjectToLanguageExtMap A mapping of object to matching language (for fixing up localization if the objects are moved). Note: Not used if bLocPackages is false
SourcePath A path to use to form a relative path for the renamed objects.
DestinationPath The default target path for the objects. If empty string, the default will be based on the the package name.
OpenDialog If true, a dialog will open to prompt the user for path information.
Returns
true when all objects were renamed successfully
RenameSingleObject()
UNREALED_API bool ObjectTools::RenameSingleObject (UObject * Object, FPackageGroupName & PGN, TSet< UPackage * > & InOutPackagesUserRefusedToFullyLoad, FText & InOutErrorMessage, const TMap< UObject *, FString > * ObjectToLanguageExtMap = NULL, bool bLeaveRedirector = true)
Renames a single object.
Parameters
Object The object to rename
PGN The new package, group, and name of the object.
InOutPackagesUserRefusedToFullyLoad A set of packages the user opted out of fully loading. This is used internally to prevent asking multiple times.
InOutErrorMessage A string with any errors that occurred during the rename.
ObjectToLanguageExtMap A mapping of object to matching language (for fixing up localization if the objects are moved). Note: Not used if bLocPackages is false
bLeaveRedirector If true, a redirector will be left to allow unloaded assets to maintain a reference to the renamed object
Returns
true when the object was renamed successfully
References Object.
SanitizeInvalidChars() [1/2]
UNREALED_API FString ObjectTools::SanitizeInvalidChars (const FString & InText, const FString & InvalidChars)
Converts all specified invalid characters to _.
SanitizeInvalidChars() [2/2]
UNREALED_API FString ObjectTools::SanitizeInvalidChars (const FString & InText, const TCHAR * InvalidChars)
Converts all specified invalid characters to _.
SanitizeInvalidCharsInline()
UNREALED_API void ObjectTools::SanitizeInvalidCharsInline (FString & InText, const TCHAR * InvalidChars)
Converts all specified invalid characters to _.
SanitizeObjectName()
UNREALED_API FString ObjectTools::SanitizeObjectName (const FString & InObjectName)
Converts all invalid object name characters to _.
SanitizeObjectPath()
UNREALED_API FString ObjectTools::SanitizeObjectPath (const FString & InObjectPath)
Converts all invalid object path characters to _.
SelectActorsInLevelDirectlyReferencingObject()
UNREALED_API void ObjectTools::SelectActorsInLevelDirectlyReferencingObject (UObject * RefObj)
Select the object referencers in the level.
Parameters
Object Object whose references are to be selected
References SelectActorsInLevelDirectlyReferencingObject().
Referenced by SelectActorsInLevelDirectlyReferencingObject().
SelectObjectAndExternalReferencersInLevel()
UNREALED_API void ObjectTools::SelectObjectAndExternalReferencersInLevel (UObject * Object, const bool bRecurseMaterial)
Select the object and it's external referencers' referencers in the level.
This function calls AccumulateObjectReferencersForObjectRecursive to recursively build a list of objects to check for referencers in the level
Parameters
Object Object whose references are to be selected
bRecurseMaterial Whether or not we're allowed to recurse the material
References Object, and SelectObjectAndExternalReferencersInLevel().
Referenced by SelectObjectAndExternalReferencersInLevel().
ShowDeleteConfirmationDialog()
bool ObjectTools::ShowDeleteConfirmationDialog (const TArray< UObject * > & ObjectsToDelete)
Shows a confirmation dialog asking the user if it is ok to delete the packages containing the supplied objects.
Parameters
ObjectsToDelete The list of objects to delete
Returns
true if the user accepted the dialog or no dialog was necessary
References ShowDeleteConfirmationDialog().
Referenced by ShowDeleteConfirmationDialog().
ShowReferencedObjs() [1/2]
UNREALED_API void ObjectTools::ShowReferencedObjs (UObject * Object)
Displays all of the objects the passed in object references.
Parameters
Object Object whose references should be displayed
References Object.
Referenced by ShowReferencedObjs().
ShowReferencedObjs() [2/2]
UNREALED_API void ObjectTools::ShowReferencedObjs (UObject * Object, ICollectionContainer * CollectionContainer, FName CollectionName, ECollectionShareType::Type ShareType)
Displays all of the objects the passed in object references.
Parameters
Object Object whose references should be displayed
CollectionContainer The collection container for any created collection
CollectionName Name of a collection that needs to be made with these referenced objects
ShareType The share type of any created collection
References CollectionName, Object, ShareType, and ShowReferencedObjs().
ShowReferenceGraph()
UNREALED_API void ObjectTools::ShowReferenceGraph (UObject * ObjectToGraph)
Displays a tree(currently) of all assets which reference the passed in object.
Parameters
ObjectToGraph The object to find references to.
InBrowsableTypes A mapping of classes to browsable types. The tool only shows browsable types or actors
ShowReferencers()
UNREALED_API void ObjectTools::ShowReferencers (const TArray< UObject * > & SelectedObjects)
TagInUseObjects()
UNREALED_API void ObjectTools::TagInUseObjects (EInUseSearchOption SearchOption, EInUseSearchFlags InUseSearchFlags = EInUseSearchFlags::None)
Tags objects which are in use by levels specified by the search option.
Parameters
SearchOption The search option for finding in use objects
bShouldSkipCompilingAssets Whether to avoid stalls on assets still being compiled.
References None.
UE_DEPRECATED() [1/2]
ObjectTools::UE_DEPRECATED (5. 1, "No longer used.")
UE_DEPRECATED() [2/2]
ObjectTools::UE_DEPRECATED (5. 6, "Use the ICollectionContainer overload instead.")
Displays all of the objects the passed in object references.
Parameters
Object Object whose references should be displayed
CollectionName Name of a collection that needs to be made with these referenced objects
ShareType The share type of any created collection
Variable Documentation
CollectionName
const FString& ObjectTools::CollectionName
Definition at line 259 of file ObjectTools.h.
Referenced by ShowReferencedObjs().
ObjectPath
const FString& ObjectTools::ObjectPath
Definition at line 624 of file ObjectTools.h.
ShareType
const FString ECollectionShareType::Type ObjectTools::ShareType = ECollectionShareType::CST_Private)
Definition at line 259 of file ObjectTools.h.
Referenced by ShowReferencedObjs().