Unreal Engine 5.6 C++ API: QualityLevelProperty Namespace Reference
QualityLevelProperty Namespace Reference
Data Structures
struct FSavedData
Functions
template<typename _ValueType>
TMap< int32, _ValueType > ConvertQualityLevelData (const TMap< EPerQualityLevels, _ValueType > &Data)
template<typename _ValueType>
TMap< EPerQualityLevels, _ValueType > ConvertQualityLevelData (const TMap< int32, _ValueType > &Data)
_ValueType ConvertQualtiyLevelData (const TMap< EPerQualityLevels, _ValueType > &Data)
_ValueType ConvertQualtiyLevelData (const TMap< int32, _ValueType > &Data)
int32 FNameToQualityLevel (FName QL)
TArray< FName > GetEnginePlatformsForPlatformOrGroupName (const FString &InPlatformName)
FSupportedQualityLevelArray PerPlatformOverrideMapping (FString &InPlatformName, UObject *RequestingAsset=nullptr)
FName QualityLevelToFName (int32 QL)
template<typename _ValueType>
UE_DEPRECATED (5.5, "Use ConvertQualityLevelData.") TMap< int32
UENUM () enum class UE_DEPRECATED(5.1
Variables
Use EPerQualityLevels instead since we need to expose as an ENUM in blueprint Cinematic
Use EPerQualityLevels instead since we need to expose as an ENUM in blueprint Epic
Use EPerQualityLevels instead since we need to expose as an ENUM in blueprint EQualityLevels
Use EPerQualityLevels instead since we need to expose as an ENUM in blueprint High
Use EPerQualityLevels instead since we need to expose as an ENUM in blueprint Medium
Use EPerQualityLevels instead since we need to expose as an ENUM in blueprint Num
Function Documentation
ConvertQualityLevelData() [1/2]
template<typename _ValueType> TMap< int32, _ValueType > QualityLevelProperty::ConvertQualityLevelData (const TMap< EPerQualityLevels, _ValueType > & Data)
Referenced by ConvertQualtiyLevelData(), ConvertQualtiyLevelData(), and FScopedSkeletalMeshRenderData::USkeletalMesh.
ConvertQualityLevelData() [2/2]
template<typename _ValueType> TMap< EPerQualityLevels, _ValueType > QualityLevelProperty::ConvertQualityLevelData (const TMap< int32, _ValueType > & Data)
ConvertQualtiyLevelData() [1/2]
_ValueType QualityLevelProperty::ConvertQualtiyLevelData (const TMap< EPerQualityLevels, _ValueType > & Data)
Definition at line 54 of file PerQualityLevelProperties.h.
References ConvertQualityLevelData(), and ConvertQualtiyLevelData().
Referenced by ConvertQualtiyLevelData(), and ConvertQualtiyLevelData().
ConvertQualtiyLevelData() [2/2]
_ValueType QualityLevelProperty::ConvertQualtiyLevelData (const TMap< int32, _ValueType > & Data)
Definition at line 62 of file PerQualityLevelProperties.h.
References ConvertQualityLevelData(), and ConvertQualtiyLevelData().
FNameToQualityLevel()
int32 QualityLevelProperty::FNameToQualityLevel (FName QL)
GetEnginePlatformsForPlatformOrGroupName()
TArray< FName > QualityLevelProperty::GetEnginePlatformsForPlatformOrGroupName (const FString & InPlatformName)
PerPlatformOverrideMapping()
FSupportedQualityLevelArray QualityLevelProperty::PerPlatformOverrideMapping (FString & InPlatformName, UObject * RequestingAsset = nullptr)
QualityLevelToFName()
FName QualityLevelProperty::QualityLevelToFName (int32 QL)
UE_DEPRECATED()
template<typename _ValueType> QualityLevelProperty::UE_DEPRECATED (5. 5, "Use ConvertQualityLevelData.")
UENUM()
QualityLevelProperty::UENUM ()
Variable Documentation
Cinematic
Use EPerQualityLevels instead since we need to expose as an ENUM in blueprint QualityLevelProperty::Cinematic
Definition at line 44 of file PerQualityLevelProperties.h.
Epic
Use EPerQualityLevels instead since we need to expose as an ENUM in blueprint QualityLevelProperty::Epic
Definition at line 43 of file PerQualityLevelProperties.h.
EQualityLevels
Use EPerQualityLevels instead since we need to expose as an ENUM in blueprint QualityLevelProperty::EQualityLevels
Definition at line 38 of file PerQualityLevelProperties.h.
High
Use EPerQualityLevels instead since we need to expose as an ENUM in blueprint QualityLevelProperty::High
Definition at line 42 of file PerQualityLevelProperties.h.
Medium
Use EPerQualityLevels instead since we need to expose as an ENUM in blueprint QualityLevelProperty::Medium
Definition at line 41 of file PerQualityLevelProperties.h.
Num
Use EPerQualityLevels instead since we need to expose as an ENUM in blueprint QualityLevelProperty::Num
Definition at line 45 of file PerQualityLevelProperties.h.