Unreal Engine 5.6 C++ API: FAISystem Namespace Reference
FAISystem Namespace Reference
AIController is the base class of controllers for AI-controlled Pawns.
Functions
FORCEINLINE EAIOptionFlag::Type BoolToAIOption (bool Value)
AIMODULE_API bool CheckIsTargetInSightCone (const FVector &StartLocation, const FVector &ConeDirectionNormal, float PeripheralVisionAngleCos, float ConeDirectionBackwardOffset, float NearClippingRadiusSq, float const FarClippingRadiusSq, const FVector &TargetLocation)
AIMODULE_API FVector FindClosestLocation (const FVector &Origin, const TArray< FVector > &Locations)
FORCEINLINE bool IsValidControllerAndHasValidPawn (const AController *Controller)
FORCEINLINE bool IsValidDirection (const FVector &TestVector)
FORCEINLINE bool IsValidLocation (const FVector &TestLocation)
FORCEINLINE bool IsValidOrientation (const FQuat &TestOrientation)
FORCEINLINE bool IsValidRotation (const FRotator &TestRotation)
FORCEINLINE bool PickAIOption (EAIOptionFlag::Type Option, bool DefaultOption)
Variables
constexpr float InfiniteInterval = -FLT_MAX
constexpr FVector InvalidDirection = FVector(0, UE::Math::TVectorConstInit{})
constexpr FVector InvalidLocation = FVector(FLT_MAX, UE::Math::TVectorConstInit{})
AIMODULE_API const FQuat InvalidOrientation
constexpr float InvalidRange = -1.f
AIMODULE_API const FRotator InvalidRotation
constexpr uint32 InvalidUnsignedID = uint32(INDEX_NONE)
Detailed Description
AIController is the base class of controllers for AI-controlled Pawns.
Controllers are non-physical actors that can be attached to a pawn to control its actions. AIControllers manage the artificial intelligence for the pawns they control. In networked games, they only exist on the server.
See also
https://docs.unrealengine.com/latest/INT/Gameplay/Framework/Controller/
Function Documentation
BoolToAIOption()
FORCEINLINE EAIOptionFlag::Type FAISystem::BoolToAIOption (bool Value)
Definition at line 89 of file AITypes.h.
References FORCEINLINE, and Value.
CheckIsTargetInSightCone()
AIMODULE_API bool FAISystem::CheckIsTargetInSightCone (const FVector & StartLocation, const FVector & ConeDirectionNormal, float PeripheralVisionAngleCos, float ConeDirectionBackwardOffset, float NearClippingRadiusSq, float const FarClippingRadiusSq, const FVector & TargetLocation)
References FVector.
FindClosestLocation()
AIMODULE_API FVector FAISystem::FindClosestLocation (const FVector & Origin, const TArray< FVector > & Locations)
References FVector, and Origin.
IsValidControllerAndHasValidPawn()
FORCEINLINE bool FAISystem::IsValidControllerAndHasValidPawn (const AController * Controller)
Definition at line 460 of file AIController.h.
References FORCEINLINE, AController::GetPawn(), and IsValidControllerAndHasValidPawn().
Referenced by IsValidControllerAndHasValidPawn().
IsValidDirection()
FORCEINLINE bool FAISystem::IsValidDirection (const FVector & TestVector)
Definition at line 43 of file AITypes.h.
References FORCEINLINE, FVector, IsValidLocation(), and UE::Math::TVector< T >::IsZero().
IsValidLocation()
FORCEINLINE bool FAISystem::IsValidLocation (const FVector & TestLocation)
Definition at line 36 of file AITypes.h.
References FORCEINLINE, FVector, InvalidLocation, UE::Math::TVector< T >::X, UE::Math::TVector< T >::Y, and UE::Math::TVector< T >::Z.
Referenced by IsValidDirection().
IsValidOrientation()
FORCEINLINE bool FAISystem::IsValidOrientation (const FQuat & TestOrientation)
Definition at line 53 of file AITypes.h.
References FORCEINLINE, and InvalidOrientation.
IsValidRotation()
FORCEINLINE bool FAISystem::IsValidRotation (const FRotator & TestRotation)
Definition at line 48 of file AITypes.h.
References FORCEINLINE, and InvalidRotation.
PickAIOption()
FORCEINLINE bool FAISystem::PickAIOption (EAIOptionFlag::Type Option, bool DefaultOption)
Definition at line 84 of file AITypes.h.
References FORCEINLINE.
Variable Documentation
InfiniteInterval
float FAISystem::InfiniteInterval = -FLT_MAX constexpr
Definition at line 33 of file AITypes.h.
InvalidDirection
FVector FAISystem::InvalidDirection = FVector(0, UE::Math::TVectorConstInit{}) inline constexpr
Definition at line 31 of file AITypes.h.
InvalidLocation
FVector FAISystem::InvalidLocation = FVector(FLT_MAX, UE::Math::TVectorConstInit{}) inline constexpr
Definition at line 30 of file AITypes.h.
Referenced by FFocusKnowledge::FFocusItem::FFocusItem(), FAISightQuery::ForgetPreviousResult(), ICrowdAgentInterface::GENERATED_IINTERFACE_BODY(), FActorPerceptionInfo::GetLastStimulusLocation(), FActorPerceptionInfo::GetReceiverLocation(), FActorPerceptionInfo::GetStimulusLocation(), IsValidLocation(), FBTFocusMemory::Reset(), USTRUCT(), USTRUCT(), and USTRUCT().
InvalidOrientation
AIMODULE_API const FQuat FAISystem::InvalidOrientation extern
Referenced by IsValidOrientation().
InvalidRange
float FAISystem::InvalidRange = -1.f constexpr
Definition at line 32 of file AITypes.h.
InvalidRotation
AIMODULE_API const FRotator FAISystem::InvalidRotation extern
Referenced by IsValidRotation().
InvalidUnsignedID
uint32 FAISystem::InvalidUnsignedID = uint32(INDEX_NONE) constexpr
Definition at line 34 of file AITypes.h.