Unreal Engine 5.6 C++ API: UE::UnrealEd Namespace Reference
UE::UnrealEd Namespace Reference
Data Structures
struct FLocationGridSnapMenuOptions
struct FViewportCameraMenuOptions
Enumerations
enum EHidableViewModeMenuSections : uint8 { Exposure = 0 , GPUSkinCache = 1 , RayTracingDebug = 2 }
Lists View Mode Menu Sections which can be shown/hidden based on specific menu requirements.
Functions
UNREALED_API void AddDefaultShowFlags (UToolMenu *InMenu)
Adds common flags sections to the specified menu.
UNREALED_API void AddExposureSection (UToolMenu *InMenu, const TSharedPtr< SEditorViewport > &EditorViewport)
UNREALED_API TSharedRef< SWidget > BuildRotationGridCheckBoxList (FName InExtentionHook, const FText &InHeading, const TArray< float > &InGridSizes, ERotationGridMode InGridMode, const FRotationGridCheckboxListExecuteActionDelegate &InExecuteAction, const FRotationGridCheckboxListIsCheckedDelegate &InIsActionChecked, const TSharedPtr< FUICommandList > &InCommandList={})
UNREALED_API void ConstructScreenPercentageMenu (UToolMenu *InMenu)
TSharedRef< SWidget > CreateActiveViewportWidget (FEditorViewportClient &InViewportClient)
UNREALED_API FToolMenuEntry CreateAssetViewerProfileSubmenu ()
TSharedRef< SWidget > CreateCameraMenuWidget (const TSharedRef< SEditorViewport > &InViewport, bool bInShowExposureSettings=false)
UNREALED_API FToolMenuEntry CreateCameraSpeedMenu ()
UNREALED_API FToolMenuEntry CreateCameraSubmenu (const FViewportCameraMenuOptions &InOptions={})
TSharedRef< SWidget > CreateCurrentPercentageWidget (FEditorViewportClient &InViewportClient)
TSharedRef< SWidget > CreateCurrentScreenPercentageSettingWidget (FEditorViewportClient &InViewportClient)
TSharedRef< SWidget > CreateCurrentScreenPercentageWidget (FEditorViewportClient &InViewportClient)
UNREALED_API FToolMenuEntry CreateDefaultShowSubmenu ()
Creates a Show submenu with commonly used show flags.
TSharedRef< SWidget > CreateFarViewPlaneMenuWidget (const TSharedRef< SEditorViewport > &InViewport)
TSharedRef< SWidget > CreateFOVMenuWidget (const TSharedRef< SEditorViewport > &InViewport)
UNREALED_API TSharedRef< SWidget > CreateLocationGridSnapMenu (const FLocationGridSnapMenuOptions &InMenuOptions={})
TSharedRef< SWidget > CreateNearViewPlaneMenuWidget (const TSharedRef< SEditorViewport > &InViewport)
UNREALED_API FToolMenuEntry CreateNumericEntry (const FName InName, const FText &InLabel, const FText &InTooltip, const FCanExecuteAction &InCanExecuteAction, const FNumericEntryExecuteActionDelegate &InOnValueChanged, const TAttribute< float > &InGetValue, float InMinValue=0.0f, float InMaxValue=1.0f, int32 InMaxFractionalDigits=2)
UNREALED_API FToolMenuEntry CreateNumericEntry (const FName InName, const FText &InLabel, const FText &InTooltip, const FCanExecuteAction &InCanExecuteAction, const FNumericEntryExecuteActionDelegateInt32 &InOnValueChanged, const TAttribute< int32 > &InGetValue, int32 InMinValue=0, int32 InMaxValue=1)
UNREALED_API FToolMenuEntry CreatePerformanceAndScalabilitySubmenu ()
UNREALED_API FToolMenuEntry CreatePreviewLODSelectionSubmenu (TWeakPtr< IPreviewLODController > LODController)
Creates a submenu that displays and manipulates the current LOD of the provided LODController.
UNREALED_API FToolMenuEntry CreateRemoveRealtimeOverrideEntry (TWeakPtr< SEditorViewport > WeakViewport)
UNREALED_API FToolMenuEntry CreateResetScalabilitySubmenu ()
TSharedRef< SWidget > CreateResolutionsWidget (FEditorViewportClient &InViewportClient)
UNREALED_API TSharedRef< SWidget > CreateRotationGridSnapMenu (const FRotationGridCheckboxListExecuteActionDelegate &InExecuteDelegate, const FRotationGridCheckboxListIsCheckedDelegate &InIsCheckedDelegate, const TAttribute< bool > &InIsEnabledDelegate=TAttribute< bool >(true), const TSharedPtr< FUICommandList > &InCommandList={})
UNREALED_API FToolMenuEntry CreateScalabilitySubmenu ()
UNREALED_API TSharedRef< SWidget > CreateScaleGridSnapMenu (const FScaleGridCheckboxListExecuteActionDelegate &InExecuteDelegate, const FScaleGridCheckboxListIsCheckedDelegate &InIsCheckedDelegate, const TArray< float > &InGridSizes, const TAttribute< bool > &InIsEnabledDelegate=TAttribute< bool >(true), const TSharedPtr< FUICommandList > &InCommandList={}, const TAttribute< bool > &ShowPreserveNonUniformScaleOption=TAttribute< bool >(false), const FUIAction &PreserveNonUniformScaleUIAction=FUIAction())
UNREALED_API FToolMenuEntry CreateScreenPercentageSubmenu ()
TSharedRef< SWidget > CreateSetFromWidget (FEditorViewportClient &InViewportClient)
UNREALED_API FToolMenuEntry CreateShowSubmenu (const FNewToolMenuChoice &InSubmenuChoice)
Creates a Show submenu with custom content.
UNREALED_API FToolMenuEntry CreateSnappingSubmenu ()
UNREALED_API FToolMenuEntry CreateToggleRealtimeEntry ()
UNREALED_API FToolMenuEntry CreateTransformsSubmenu ()
UNREALED_API FToolMenuEntry CreateViewModesSubmenu ()
UNREALED_API UUnrealEdViewportToolbarContext * CreateViewportToolbarDefaultContext (const TWeakPtr< SEditorViewport > &InViewport)
Create a Viewport Toolbar Context with common values (many Asset Editors have the same settings)
DECLARE_DELEGATE_OneParam (FLocationGridCheckboxListExecuteActionDelegate, int)
DECLARE_DELEGATE_OneParam (FNumericEntryExecuteActionDelegate, float)
DECLARE_DELEGATE_OneParam (FNumericEntryExecuteActionDelegateInt32, int32)
DECLARE_DELEGATE_OneParam (FScaleGridCheckboxListExecuteActionDelegate, int)
DECLARE_DELEGATE_RetVal (TArray< float >, FLocationGridValuesArrayDelegate)
DECLARE_DELEGATE_RetVal_OneParam (bool, DoesViewModeMenuShowSectionDelegate, EHidableViewModeMenuSections)
DECLARE_DELEGATE_RetVal_OneParam (bool, FLocationGridCheckboxListIsCheckedDelegate, int)
DECLARE_DELEGATE_RetVal_OneParam (bool, FScaleGridCheckboxListIsCheckedDelegate, int)
DECLARE_DELEGATE_RetVal_OneParam (bool, IsViewModeSupportedDelegate, EViewModeIndex)
DECLARE_DELEGATE_RetVal_TwoParams (bool, FRotationGridCheckboxListIsCheckedDelegate, int, ERotationGridMode)
DECLARE_DELEGATE_TwoParams (FOnViewportClientCamSpeedChanged, const TSharedRef< SEditorViewport > &, int32)
DECLARE_DELEGATE_TwoParams (FOnViewportClientCamSpeedScalarChanged, const TSharedRef< SEditorViewport > &, float)
DECLARE_DELEGATE_TwoParams (FRotationGridCheckboxListExecuteActionDelegate, int, ERotationGridMode)
UNREALED_API void ExtendPreviewSceneSettingsWithTabEntry (FName InAssetViewerProfileSubmenuName)
UNREALED_API void FillPreviewLODSelectionSubmenu (UToolMenu *InToolMenu, TWeakPtr< IPreviewLODController > LODController)
Fills the given UToolMenu with the appropriate menu items to reflect & manipulate the provided LODController.
UNREALED_API void GenerateViewportTypeMenu (UToolMenu *InMenu)
UNREALED_API FText GetCameraSpeedLabel (const TWeakPtr< SEditorViewport > &WeakViewport)
UNREALED_API FText GetCameraSpeedTooltip ()
UNREALED_API FName GetCameraSubmenuIconFNameFromViewportType (const ELevelViewportType ViewportType)
UNREALED_API FText GetCameraSubmenuLabelFromViewportType (const ELevelViewportType ViewportType)
UNREALED_API FSlateIcon GetIconFromCoordSystem (ECoordSystem InCoordSystem)
UNREALED_API TAttribute< bool > GetIsPerspectiveAttribute (const TSharedPtr< FEditorViewportClient > &InViewportClient)
Creates an attribute that provides whether the viewport client is in perspective view.
UNREALED_API FText GetLocationGridLabel ()
UNREALED_API TAttribute< EVisibility > GetPerspectiveOnlyVisibility (const TSharedPtr< FEditorViewportClient > &InViewportClient)
Returns Visible if the provided Viewport Client is in perspective view, Collapsed if not.
UNREALED_API FText GetRotationGridLabel ()
UNREALED_API FText GetScaleGridLabel ()
UNREALED_API FSlateIcon GetViewModesSubmenuIcon (const TWeakPtr< SEditorViewport > &InViewport)
UNREALED_API FSlateIcon GetViewModesSubmenuIcon (const UGameViewportClient *InViewportClient)
UNREALED_API FText GetViewModesSubmenuLabel (const UGameViewportClient *InViewportClient)
UNREALED_API FText GetViewModesSubmenuLabel (TWeakPtr< SEditorViewport > InViewport)
UNREALED_API FOnViewportClientCamSpeedChanged & OnViewportClientCamSpeedChanged ()
UNREALED_API FOnViewportClientCamSpeedScalarChanged & OnViewportClientCamSpeedScalarChanged ()
UNREALED_API void PopulateCameraMenu (UToolMenu *InMenu, const FViewportCameraMenuOptions &InOptions={})
UNREALED_API void PopulateViewModesMenu (UToolMenu *InMenu)
Populate a given UToolMenu with entries for a View Modes viewport toolbar submenu.
UNREALED_API bool ShouldShowViewportRealtimeWarning (const FEditorViewportClient &ViewportClient)
UNREALED_API bool ShowNewViewportToolbars ()
The value of this function is controlled by the CVAR "ToolMenusViewportToolbars".
UNREALED_API bool ShowOldViewportToolbars ()
The value of this function is controlled by the CVAR "ToolMenusViewportToolbars".
UE_DEPRECATED (5.6, "Use CreateAssetViewerProfileSubmenu() instead.") UNREALED_API FToolMenuEntry CreateViewportToolbarAssetViewerProfileSubmenu()
UE_DEPRECATED (5.6, "Use CreateCameraSubmenu() instead.") UNREALED_API FToolMenuEntry CreateViewportToolbarCameraSubmenu()
UE_DEPRECATED (5.6, "Use CreateLocationGridSnapMenu() using FLocationGridSnapMenuOptions as argument instead.") UNREALED_API TSharedRef< SWidget > CreateLocationGridSnapMenu(const FLocationGridCheckboxListExecuteActionDelegate &InExecuteDelegate
UE_DEPRECATED (5.6, "Use CreateSnappingSubmenu() instead.") UNREALED_API FToolMenuEntry CreateViewportToolbarSnappingSubmenu()
UE_DEPRECATED (5.6, "Use CreateTransformsSubmenu() instead.") UNREALED_API FToolMenuEntry CreateViewportToolbarTransformsSection()
UE_DEPRECATED (5.6, "Use CreateViewModesSubmenu() instead.") UNREALED_API FToolMenuEntry CreateViewportToolbarViewModesSubmenu()
UE_DEPRECATED (5.6, "Use the native FToolMenuEntry::InitSubmenu() functions.") UNREALED_API FToolMenuEntry CreateCheckboxSubmenu(const FName InName
UE_DEPRECATED (5.6, "Use the options parameters of CreateCameraSubmenu() or PopulateCameraMenu() instead.") UNREALED_API void ExtendCameraSubmenu(FName InCameraOptionsSubmenuName
Adds Field of View and Far/Near View Plane entries to the specified Camera Submenu.
UE_DEPRECATED (5.6, "Viewport toolbar no longer has a Select Menu.") UNREALED_API FToolMenuEntry CreateViewportToolbarSelectSection()
UE_DEPRECATED_FORGAME (5.6, "Do not use. Will be made private.") UNREALED_API bool IsScalabilityWarningVisible()
Variables
bool bInShowViewPlaneEntries = true)
const TAttribute< FText > const TAttribute< FText > const FToolMenuExecuteAction const FToolMenuCanExecuteAction const FToolMenuGetActionCheckState & InCheckboxActionCheckState
const TAttribute< FText > const TAttribute< FText > const FToolMenuExecuteAction const FToolMenuCanExecuteAction & InCheckboxCanExecuteAction
const TAttribute< FText > const TAttribute< FText > const FToolMenuExecuteAction & InCheckboxExecuteAction
const FLocationGridCheckboxListIsCheckedDelegate const TArray< float > const TAttribute< bool > const TSharedPtr< FUICommandList > & InCommandList
const FLocationGridCheckboxListIsCheckedDelegate const TArray< float > & InGridSizes
const FLocationGridCheckboxListIsCheckedDelegate & InIsCheckedDelegate
const FLocationGridCheckboxListIsCheckedDelegate const TArray< float > const TAttribute< bool > & InIsEnabledDelegate = TAttribute<bool>(true)
const TAttribute< FText > & InLabel
const TAttribute< FText > const TAttribute< FText > const FToolMenuExecuteAction const FToolMenuCanExecuteAction const FToolMenuGetActionCheckState const FNewToolMenuChoice & InMakeMenu
const TAttribute< FText > const TAttribute< FText > & InToolTip
Enumeration Type Documentation
EHidableViewModeMenuSections
enum UE::UnrealEd::EHidableViewModeMenuSections : uint8
Lists View Mode Menu Sections which can be shown/hidden based on specific menu requirements.
Enumerator
Exposure
GPUSkinCache
RayTracingDebug
Definition at line 32 of file UnrealEdViewportToolbar.h.
Function Documentation
AddDefaultShowFlags()
UNREALED_API void UE::UnrealEd::AddDefaultShowFlags (UToolMenu * InMenu)
Adds common flags sections to the specified menu.
References AddDefaultShowFlags().
Referenced by AddDefaultShowFlags().
AddExposureSection()
UNREALED_API void UE::UnrealEd::AddExposureSection (UToolMenu * InMenu, const TSharedPtr< SEditorViewport > & EditorViewport)
References AddExposureSection().
Referenced by AddExposureSection().
BuildRotationGridCheckBoxList()
UNREALED_API TSharedRef< SWidget > UE::UnrealEd::BuildRotationGridCheckBoxList (FName InExtentionHook, const FText & InHeading, const TArray< float > & InGridSizes, ERotationGridMode InGridMode, const FRotationGridCheckboxListExecuteActionDelegate & InExecuteAction, const FRotationGridCheckboxListIsCheckedDelegate & InIsActionChecked, const TSharedPtr< FUICommandList > & InCommandList = {})
References BuildRotationGridCheckBoxList(), InCommandList, and InGridSizes.
Referenced by BuildRotationGridCheckBoxList().
ConstructScreenPercentageMenu()
UNREALED_API void UE::UnrealEd::ConstructScreenPercentageMenu (UToolMenu * InMenu)
References ConstructScreenPercentageMenu().
Referenced by ConstructScreenPercentageMenu().
CreateActiveViewportWidget()
TSharedRef< SWidget > UE::UnrealEd::CreateActiveViewportWidget (FEditorViewportClient & InViewportClient)
References CreateActiveViewportWidget().
Referenced by CreateActiveViewportWidget().
CreateAssetViewerProfileSubmenu()
UNREALED_API FToolMenuEntry UE::UnrealEd::CreateAssetViewerProfileSubmenu ()
References CreateAssetViewerProfileSubmenu().
Referenced by CreateAssetViewerProfileSubmenu().
CreateCameraMenuWidget()
TSharedRef< SWidget > UE::UnrealEd::CreateCameraMenuWidget (const TSharedRef< SEditorViewport > & InViewport, bool bInShowExposureSettings = false)
References CreateCameraMenuWidget().
Referenced by CreateCameraMenuWidget().
CreateCameraSpeedMenu()
UNREALED_API FToolMenuEntry UE::UnrealEd::CreateCameraSpeedMenu ()
References CreateCameraSpeedMenu().
Referenced by CreateCameraSpeedMenu().
CreateCameraSubmenu()
UNREALED_API FToolMenuEntry UE::UnrealEd::CreateCameraSubmenu (const FViewportCameraMenuOptions & InOptions = {})
References InOptions.
CreateCurrentPercentageWidget()
TSharedRef< SWidget > UE::UnrealEd::CreateCurrentPercentageWidget (FEditorViewportClient & InViewportClient)
References CreateCurrentPercentageWidget().
Referenced by CreateCurrentPercentageWidget().
CreateCurrentScreenPercentageSettingWidget()
TSharedRef< SWidget > UE::UnrealEd::CreateCurrentScreenPercentageSettingWidget (FEditorViewportClient & InViewportClient)
References CreateCurrentScreenPercentageSettingWidget().
Referenced by CreateCurrentScreenPercentageSettingWidget().
CreateCurrentScreenPercentageWidget()
TSharedRef< SWidget > UE::UnrealEd::CreateCurrentScreenPercentageWidget (FEditorViewportClient & InViewportClient)
References CreateCurrentScreenPercentageWidget().
Referenced by CreateCurrentScreenPercentageWidget().
CreateDefaultShowSubmenu()
UNREALED_API FToolMenuEntry UE::UnrealEd::CreateDefaultShowSubmenu ()
Creates a Show submenu with commonly used show flags.
References CreateDefaultShowSubmenu().
Referenced by CreateDefaultShowSubmenu().
CreateFarViewPlaneMenuWidget()
TSharedRef< SWidget > UE::UnrealEd::CreateFarViewPlaneMenuWidget (const TSharedRef< SEditorViewport > & InViewport)
References CreateFarViewPlaneMenuWidget().
Referenced by CreateFarViewPlaneMenuWidget().
CreateFOVMenuWidget()
TSharedRef< SWidget > UE::UnrealEd::CreateFOVMenuWidget (const TSharedRef< SEditorViewport > & InViewport)
References CreateFOVMenuWidget().
Referenced by CreateFOVMenuWidget().
CreateLocationGridSnapMenu()
UNREALED_API TSharedRef< SWidget > UE::UnrealEd::CreateLocationGridSnapMenu (const FLocationGridSnapMenuOptions & InMenuOptions = {})
Referenced by UE_DEPRECATED().
CreateNearViewPlaneMenuWidget()
TSharedRef< SWidget > UE::UnrealEd::CreateNearViewPlaneMenuWidget (const TSharedRef< SEditorViewport > & InViewport)
References CreateNearViewPlaneMenuWidget().
Referenced by CreateNearViewPlaneMenuWidget().
CreateNumericEntry() [1/2]
UNREALED_API FToolMenuEntry UE::UnrealEd::CreateNumericEntry (const FName InName, const FText & InLabel, const FText & InTooltip, const FCanExecuteAction & InCanExecuteAction, const FNumericEntryExecuteActionDelegate & InOnValueChanged, const TAttribute< float > & InGetValue, float InMinValue = 0.0f, float InMaxValue = 1.0f, int32 InMaxFractionalDigits = 2)
References CreateNumericEntry(), InLabel, and InName.
Referenced by CreateNumericEntry(), and CreateNumericEntry().
CreateNumericEntry() [2/2]
UNREALED_API FToolMenuEntry UE::UnrealEd::CreateNumericEntry (const FName InName, const FText & InLabel, const FText & InTooltip, const FCanExecuteAction & InCanExecuteAction, const FNumericEntryExecuteActionDelegateInt32 & InOnValueChanged, const TAttribute< int32 > & InGetValue, int32 InMinValue = 0, int32 InMaxValue = 1)
References CreateNumericEntry(), InLabel, and InName.
CreatePerformanceAndScalabilitySubmenu()
UNREALED_API FToolMenuEntry UE::UnrealEd::CreatePerformanceAndScalabilitySubmenu ()
References CreatePerformanceAndScalabilitySubmenu().
Referenced by CreatePerformanceAndScalabilitySubmenu().
CreatePreviewLODSelectionSubmenu()
UNREALED_API FToolMenuEntry UE::UnrealEd::CreatePreviewLODSelectionSubmenu (TWeakPtr< IPreviewLODController > LODController)
Creates a submenu that displays and manipulates the current LOD of the provided LODController.
This should be invoked from within a dynamic menu or section to provide the correct controller.
References CreatePreviewLODSelectionSubmenu().
Referenced by CreatePreviewLODSelectionSubmenu().
CreateRemoveRealtimeOverrideEntry()
UNREALED_API FToolMenuEntry UE::UnrealEd::CreateRemoveRealtimeOverrideEntry (TWeakPtr< SEditorViewport > WeakViewport)
References CreateRemoveRealtimeOverrideEntry().
Referenced by CreateRemoveRealtimeOverrideEntry().
CreateResetScalabilitySubmenu()
UNREALED_API FToolMenuEntry UE::UnrealEd::CreateResetScalabilitySubmenu ()
References CreateResetScalabilitySubmenu().
Referenced by CreateResetScalabilitySubmenu().
CreateResolutionsWidget()
TSharedRef< SWidget > UE::UnrealEd::CreateResolutionsWidget (FEditorViewportClient & InViewportClient)
References CreateResolutionsWidget().
Referenced by CreateResolutionsWidget().
CreateRotationGridSnapMenu()
UNREALED_API TSharedRef< SWidget > UE::UnrealEd::CreateRotationGridSnapMenu (const FRotationGridCheckboxListExecuteActionDelegate & InExecuteDelegate, const FRotationGridCheckboxListIsCheckedDelegate & InIsCheckedDelegate, const TAttribute< bool > & InIsEnabledDelegate = TAttribute< bool >(true), const TSharedPtr< FUICommandList > & InCommandList = {})
References InCommandList, InIsCheckedDelegate, and InIsEnabledDelegate.
CreateScalabilitySubmenu()
UNREALED_API FToolMenuEntry UE::UnrealEd::CreateScalabilitySubmenu ()
References CreateScalabilitySubmenu().
Referenced by CreateScalabilitySubmenu().
CreateScaleGridSnapMenu()
UNREALED_API TSharedRef< SWidget > UE::UnrealEd::CreateScaleGridSnapMenu (const FScaleGridCheckboxListExecuteActionDelegate & InExecuteDelegate, const FScaleGridCheckboxListIsCheckedDelegate & InIsCheckedDelegate, const TArray< float > & InGridSizes, const TAttribute< bool > & InIsEnabledDelegate = TAttribute< bool >(true), const TSharedPtr< FUICommandList > & InCommandList = {}, const TAttribute< bool > & ShowPreserveNonUniformScaleOption = TAttribute< bool >(false), const FUIAction & PreserveNonUniformScaleUIAction = FUIAction())
References InCommandList, InGridSizes, InIsCheckedDelegate, and InIsEnabledDelegate.
CreateScreenPercentageSubmenu()
UNREALED_API FToolMenuEntry UE::UnrealEd::CreateScreenPercentageSubmenu ()
References CreateScreenPercentageSubmenu().
Referenced by CreateScreenPercentageSubmenu().
CreateSetFromWidget()
TSharedRef< SWidget > UE::UnrealEd::CreateSetFromWidget (FEditorViewportClient & InViewportClient)
References CreateSetFromWidget().
Referenced by CreateSetFromWidget().
CreateShowSubmenu()
UNREALED_API FToolMenuEntry UE::UnrealEd::CreateShowSubmenu (const FNewToolMenuChoice & InSubmenuChoice)
Creates a Show submenu with custom content.
References CreateShowSubmenu().
Referenced by CreateShowSubmenu().
CreateSnappingSubmenu()
UNREALED_API FToolMenuEntry UE::UnrealEd::CreateSnappingSubmenu ()
References CreateSnappingSubmenu().
Referenced by CreateSnappingSubmenu().
CreateToggleRealtimeEntry()
UNREALED_API FToolMenuEntry UE::UnrealEd::CreateToggleRealtimeEntry ()
References CreateToggleRealtimeEntry().
Referenced by CreateToggleRealtimeEntry().
CreateTransformsSubmenu()
UNREALED_API FToolMenuEntry UE::UnrealEd::CreateTransformsSubmenu ()
References CreateTransformsSubmenu().
Referenced by CreateTransformsSubmenu().
CreateViewModesSubmenu()
UNREALED_API FToolMenuEntry UE::UnrealEd::CreateViewModesSubmenu ()
References CreateViewModesSubmenu().
Referenced by CreateViewModesSubmenu().
CreateViewportToolbarDefaultContext()
UNREALED_API UUnrealEdViewportToolbarContext * UE::UnrealEd::CreateViewportToolbarDefaultContext (const TWeakPtr< SEditorViewport > & InViewport)
Create a Viewport Toolbar Context with common values (many Asset Editors have the same settings)
References CreateViewportToolbarDefaultContext().
Referenced by CreateViewportToolbarDefaultContext().
DECLARE_DELEGATE_OneParam() [1/4]
UE::UnrealEd::DECLARE_DELEGATE_OneParam (FLocationGridCheckboxListExecuteActionDelegate , int)
References DECLARE_DELEGATE_OneParam().
Referenced by DECLARE_DELEGATE_OneParam(), DECLARE_DELEGATE_OneParam(), DECLARE_DELEGATE_OneParam(), and DECLARE_DELEGATE_OneParam().
DECLARE_DELEGATE_OneParam() [2/4]
UE::UnrealEd::DECLARE_DELEGATE_OneParam (FNumericEntryExecuteActionDelegate , float)
References DECLARE_DELEGATE_OneParam().
DECLARE_DELEGATE_OneParam() [3/4]
UE::UnrealEd::DECLARE_DELEGATE_OneParam (FNumericEntryExecuteActionDelegateInt32 , int32)
References DECLARE_DELEGATE_OneParam().
DECLARE_DELEGATE_OneParam() [4/4]
UE::UnrealEd::DECLARE_DELEGATE_OneParam (FScaleGridCheckboxListExecuteActionDelegate , int)
References DECLARE_DELEGATE_OneParam().
DECLARE_DELEGATE_RetVal()
UE::UnrealEd::DECLARE_DELEGATE_RetVal (TArray< float > , FLocationGridValuesArrayDelegate)
References DECLARE_DELEGATE_RetVal().
Referenced by DECLARE_DELEGATE_RetVal().
DECLARE_DELEGATE_RetVal_OneParam() [1/4]
UE::UnrealEd::DECLARE_DELEGATE_RetVal_OneParam (bool , DoesViewModeMenuShowSectionDelegate , EHidableViewModeMenuSections)
DECLARE_DELEGATE_RetVal_OneParam() [2/4]
UE::UnrealEd::DECLARE_DELEGATE_RetVal_OneParam (bool , FLocationGridCheckboxListIsCheckedDelegate , int)
References DECLARE_DELEGATE_RetVal_OneParam().
Referenced by DECLARE_DELEGATE_RetVal_OneParam(), and DECLARE_DELEGATE_RetVal_OneParam().
DECLARE_DELEGATE_RetVal_OneParam() [3/4]
UE::UnrealEd::DECLARE_DELEGATE_RetVal_OneParam (bool , FScaleGridCheckboxListIsCheckedDelegate , int)
References DECLARE_DELEGATE_RetVal_OneParam().
DECLARE_DELEGATE_RetVal_OneParam() [4/4]
UE::UnrealEd::DECLARE_DELEGATE_RetVal_OneParam (bool , IsViewModeSupportedDelegate , EViewModeIndex)
DECLARE_DELEGATE_RetVal_TwoParams()
UE::UnrealEd::DECLARE_DELEGATE_RetVal_TwoParams (bool , FRotationGridCheckboxListIsCheckedDelegate , int , ERotationGridMode)
References DECLARE_DELEGATE_RetVal_TwoParams().
Referenced by DECLARE_DELEGATE_RetVal_TwoParams().
DECLARE_DELEGATE_TwoParams() [1/3]
UE::UnrealEd::DECLARE_DELEGATE_TwoParams (FOnViewportClientCamSpeedChanged , const TSharedRef< SEditorViewport > & , int32)
References DECLARE_DELEGATE_TwoParams().
DECLARE_DELEGATE_TwoParams() [2/3]
UE::UnrealEd::DECLARE_DELEGATE_TwoParams (FOnViewportClientCamSpeedScalarChanged , const TSharedRef< SEditorViewport > & , float)
References DECLARE_DELEGATE_TwoParams().
DECLARE_DELEGATE_TwoParams() [3/3]
UE::UnrealEd::DECLARE_DELEGATE_TwoParams (FRotationGridCheckboxListExecuteActionDelegate , int , ERotationGridMode)
References DECLARE_DELEGATE_TwoParams().
Referenced by DECLARE_DELEGATE_TwoParams(), DECLARE_DELEGATE_TwoParams(), and DECLARE_DELEGATE_TwoParams().
ExtendPreviewSceneSettingsWithTabEntry()
UNREALED_API void UE::UnrealEd::ExtendPreviewSceneSettingsWithTabEntry (FName InAssetViewerProfileSubmenuName)
References ExtendPreviewSceneSettingsWithTabEntry().
Referenced by ExtendPreviewSceneSettingsWithTabEntry().
FillPreviewLODSelectionSubmenu()
UNREALED_API void UE::UnrealEd::FillPreviewLODSelectionSubmenu (UToolMenu * InToolMenu, TWeakPtr< IPreviewLODController > LODController)
Fills the given UToolMenu with the appropriate menu items to reflect & manipulate the provided LODController.
References FillPreviewLODSelectionSubmenu().
Referenced by FillPreviewLODSelectionSubmenu().
GenerateViewportTypeMenu()
UNREALED_API void UE::UnrealEd::GenerateViewportTypeMenu (UToolMenu * InMenu)
References GenerateViewportTypeMenu().
Referenced by GenerateViewportTypeMenu().
GetCameraSpeedLabel()
UNREALED_API FText UE::UnrealEd::GetCameraSpeedLabel (const TWeakPtr< SEditorViewport > & WeakViewport)
References GetCameraSpeedLabel().
Referenced by GetCameraSpeedLabel().
GetCameraSpeedTooltip()
UNREALED_API FText UE::UnrealEd::GetCameraSpeedTooltip ()
References GetCameraSpeedTooltip().
Referenced by GetCameraSpeedTooltip().
GetCameraSubmenuIconFNameFromViewportType()
UNREALED_API FName UE::UnrealEd::GetCameraSubmenuIconFNameFromViewportType (const ELevelViewportType ViewportType)
References GetCameraSubmenuIconFNameFromViewportType().
Referenced by GetCameraSubmenuIconFNameFromViewportType().
GetCameraSubmenuLabelFromViewportType()
UNREALED_API FText UE::UnrealEd::GetCameraSubmenuLabelFromViewportType (const ELevelViewportType ViewportType)
References GetCameraSubmenuLabelFromViewportType().
Referenced by GetCameraSubmenuLabelFromViewportType().
GetIconFromCoordSystem()
UNREALED_API FSlateIcon UE::UnrealEd::GetIconFromCoordSystem (ECoordSystem InCoordSystem)
GetIsPerspectiveAttribute()
UNREALED_API TAttribute< bool > UE::UnrealEd::GetIsPerspectiveAttribute (const TSharedPtr< FEditorViewportClient > & InViewportClient)
Creates an attribute that provides whether the viewport client is in perspective view.
References GetIsPerspectiveAttribute().
Referenced by GetIsPerspectiveAttribute().
GetLocationGridLabel()
UNREALED_API FText UE::UnrealEd::GetLocationGridLabel ()
GetPerspectiveOnlyVisibility()
UNREALED_API TAttribute< EVisibility > UE::UnrealEd::GetPerspectiveOnlyVisibility (const TSharedPtr< FEditorViewportClient > & InViewportClient)
Returns Visible if the provided Viewport Client is in perspective view, Collapsed if not.
References GetPerspectiveOnlyVisibility().
Referenced by GetPerspectiveOnlyVisibility().
GetRotationGridLabel()
UNREALED_API FText UE::UnrealEd::GetRotationGridLabel ()
GetScaleGridLabel()
UNREALED_API FText UE::UnrealEd::GetScaleGridLabel ()
GetViewModesSubmenuIcon() [1/2]
UNREALED_API FSlateIcon UE::UnrealEd::GetViewModesSubmenuIcon (const TWeakPtr< SEditorViewport > & InViewport)
References GetViewModesSubmenuIcon().
Referenced by GetViewModesSubmenuIcon(), and GetViewModesSubmenuIcon().
GetViewModesSubmenuIcon() [2/2]
UNREALED_API FSlateIcon UE::UnrealEd::GetViewModesSubmenuIcon (const UGameViewportClient * InViewportClient)
References GetViewModesSubmenuIcon().
GetViewModesSubmenuLabel() [1/2]
UNREALED_API FText UE::UnrealEd::GetViewModesSubmenuLabel (const UGameViewportClient * InViewportClient)
References GetViewModesSubmenuLabel().
GetViewModesSubmenuLabel() [2/2]
UNREALED_API FText UE::UnrealEd::GetViewModesSubmenuLabel (TWeakPtr< SEditorViewport > InViewport)
References GetViewModesSubmenuLabel().
Referenced by GetViewModesSubmenuLabel(), and GetViewModesSubmenuLabel().
OnViewportClientCamSpeedChanged()
UNREALED_API FOnViewportClientCamSpeedChanged & UE::UnrealEd::OnViewportClientCamSpeedChanged ()
References OnViewportClientCamSpeedChanged().
Referenced by OnViewportClientCamSpeedChanged().
OnViewportClientCamSpeedScalarChanged()
UNREALED_API FOnViewportClientCamSpeedScalarChanged & UE::UnrealEd::OnViewportClientCamSpeedScalarChanged ()
References OnViewportClientCamSpeedScalarChanged().
Referenced by OnViewportClientCamSpeedScalarChanged().
PopulateCameraMenu()
UNREALED_API void UE::UnrealEd::PopulateCameraMenu (UToolMenu * InMenu, const FViewportCameraMenuOptions & InOptions = {})
References InOptions, and PopulateCameraMenu().
Referenced by PopulateCameraMenu().
PopulateViewModesMenu()
UNREALED_API void UE::UnrealEd::PopulateViewModesMenu (UToolMenu * InMenu)
Populate a given UToolMenu with entries for a View Modes viewport toolbar submenu.
Parameters
InMenu The menu to populate with entries.
References PopulateViewModesMenu().
Referenced by PopulateViewModesMenu().
ShouldShowViewportRealtimeWarning()
UNREALED_API bool UE::UnrealEd::ShouldShowViewportRealtimeWarning (const FEditorViewportClient & ViewportClient)
References ShouldShowViewportRealtimeWarning().
Referenced by ShouldShowViewportRealtimeWarning().
ShowNewViewportToolbars()
UNREALED_API bool UE::UnrealEd::ShowNewViewportToolbars ()
The value of this function is controlled by the CVAR "ToolMenusViewportToolbars".
ShowOldViewportToolbars()
UNREALED_API bool UE::UnrealEd::ShowOldViewportToolbars ()
The value of this function is controlled by the CVAR "ToolMenusViewportToolbars".
UE_DEPRECATED() [1/9]
UE::UnrealEd::UE_DEPRECATED (5. 6, "Use CreateAssetViewerProfileSubmenu() instead.")
UE_DEPRECATED() [2/9]
UE::UnrealEd::UE_DEPRECATED (5. 6, "Use CreateCameraSubmenu() instead.")
References UE_DEPRECATED().
UE_DEPRECATED() [3/9]
UE::UnrealEd::UE_DEPRECATED (5. 6, "Use CreateLocationGridSnapMenu() using FLocationGridSnapMenuOptions as argument instead.") const &
References CreateLocationGridSnapMenu().
UE_DEPRECATED() [4/9]
UE::UnrealEd::UE_DEPRECATED (5. 6, "Use CreateSnappingSubmenu() instead.")
References UE_DEPRECATED().
UE_DEPRECATED() [5/9]
UE::UnrealEd::UE_DEPRECATED (5. 6, "Use CreateTransformsSubmenu() instead.")
Referenced by UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
UE_DEPRECATED() [6/9]
UE::UnrealEd::UE_DEPRECATED (5. 6, "Use CreateViewModesSubmenu() instead.")
References UE_DEPRECATED().
UE_DEPRECATED() [7/9]
UE::UnrealEd::UE_DEPRECATED (5. 6, "Use the native FToolMenuEntry::InitSubmenu() functions.") const
References InName.
UE_DEPRECATED() [8/9]
UE::UnrealEd::UE_DEPRECATED (5. 6, "Use the options parameters of CreateCameraSubmenu() or PopulateCameraMenu() instead.")
Adds Field of View and Far/Near View Plane entries to the specified Camera Submenu.
UE_DEPRECATED() [9/9]
UE::UnrealEd::UE_DEPRECATED (5. 6, "Viewport toolbar no longer has a Select Menu.")
References UE_DEPRECATED().
UE_DEPRECATED_FORGAME()
UE::UnrealEd::UE_DEPRECATED_FORGAME (5. 6, "Do not use. Will be made private.")
References UE_DEPRECATED_FORGAME().
Referenced by UE_DEPRECATED_FORGAME().
Variable Documentation
bInShowViewPlaneEntries
bool UE::UnrealEd::bInShowViewPlaneEntries = true)
Definition at line 229 of file UnrealEdViewportToolbar.h.
InCheckboxActionCheckState
const TAttribute<FText> const TAttribute<FText> const FToolMenuExecuteAction const FToolMenuCanExecuteAction const FToolMenuGetActionCheckState& UE::UnrealEd::InCheckboxActionCheckState
Definition at line 159 of file UnrealEdViewportToolbar.h.
InCheckboxCanExecuteAction
const TAttribute<FText> const TAttribute<FText> const FToolMenuExecuteAction const FToolMenuCanExecuteAction& UE::UnrealEd::InCheckboxCanExecuteAction
Definition at line 158 of file UnrealEdViewportToolbar.h.
InCheckboxExecuteAction
const TAttribute<FText> const TAttribute<FText> const FToolMenuExecuteAction& UE::UnrealEd::InCheckboxExecuteAction
Definition at line 157 of file UnrealEdViewportToolbar.h.
InCommandList
const FLocationGridCheckboxListIsCheckedDelegate const TArray<float> const TAttribute<bool> const TSharedPtr<FUICommandList>& UE::UnrealEd::InCommandList
Initial value:
= {}
)
Definition at line 124 of file UnrealEdViewportToolbar.h.
Referenced by BuildRotationGridCheckBoxList(), CreateRotationGridSnapMenu(), and CreateScaleGridSnapMenu().
InGridSizes
const FLocationGridCheckboxListIsCheckedDelegate const TArray<float>& UE::UnrealEd::InGridSizes
Definition at line 122 of file UnrealEdViewportToolbar.h.
Referenced by BuildRotationGridCheckBoxList(), and CreateScaleGridSnapMenu().
InIsCheckedDelegate
const FLocationGridCheckboxListIsCheckedDelegate& UE::UnrealEd::InIsCheckedDelegate
Definition at line 121 of file UnrealEdViewportToolbar.h.
Referenced by CreateRotationGridSnapMenu(), and CreateScaleGridSnapMenu().
InIsEnabledDelegate
const FLocationGridCheckboxListIsCheckedDelegate const TArray<float> const TAttribute<bool>& UE::UnrealEd::InIsEnabledDelegate = TAttribute<bool>(true)
Definition at line 123 of file UnrealEdViewportToolbar.h.
Referenced by CreateRotationGridSnapMenu(), and CreateScaleGridSnapMenu().
InLabel
const TAttribute<FText>& UE::UnrealEd::InLabel
Definition at line 155 of file UnrealEdViewportToolbar.h.
Referenced by CreateNumericEntry(), and CreateNumericEntry().
InMakeMenu
const TAttribute<FText> const TAttribute<FText> const FToolMenuExecuteAction const FToolMenuCanExecuteAction const FToolMenuGetActionCheckState const FNewToolMenuChoice& UE::UnrealEd::InMakeMenu
Definition at line 160 of file UnrealEdViewportToolbar.h.
InToolTip
const TAttribute<FText> const TAttribute<FText>& UE::UnrealEd::InToolTip
Definition at line 156 of file UnrealEdViewportToolbar.h.