Unreal Engine 5.6 C++ API: Metasound::MetasoundArrayNodesPrivate Namespace Reference
Metasound::MetasoundArrayNodesPrivate Namespace Reference
Data Structures
struct TArrayElementType
struct TArrayElementType< TArray< ElementType > >
struct TArrayNodeSupport
Functions
METASOUNDFRONTEND_API FNodeClassMetadata CreateArrayNodeClassMetadata (const FName &InDataTypeName, const FName &InOperatorName, const FText &InDisplayName, const FText &InDescription, const FVertexInterface &InDefaultInterface, int32 MajorVersion=1, int32 MinorVersion=0, bool bIsDeprecated=false)
template<typename ArrayType, typename std::enable_if< TArrayNodeSupport< ArrayType >::bIsArrayConcatSupported, bool >::type = true>
bool RegisterArrayConcatNode ()
template<typename ArrayType, typename std::enable_if< TArrayNodeSupport< ArrayType >::bIsArrayGetSupported, bool >::type = true>
bool RegisterArrayGetNode ()
template<typename ArrayType, typename std::enable_if< TArrayNodeSupport< ArrayType >::bIsArrayNumSupported, bool >::type = true>
bool RegisterArrayLastIndexNode ()
template<typename ArrayType, typename std::enable_if< TArrayNodeSupport< ArrayType >::bIsArrayNumSupported, bool >::type = true>
bool RegisterArrayNumNode ()
template<typename ArrayType, typename std::enable_if< TArrayNodeSupport< ArrayType >::bIsArrayRandomGetSupported, bool >::type = true>
bool RegisterArrayRandomGetNode ()
template<typename ArrayType, typename std::enable_if< TArrayNodeSupport< ArrayType >::bIsArraySetSupported, bool >::type = true>
bool RegisterArraySetNode ()
template<typename ArrayType, typename std::enable_if< TArrayNodeSupport< ArrayType >::bIsArrayShuffleSupported, bool >::type = true>
bool RegisterArrayShuffleNode ()
template<typename ArrayType, typename std::enable_if< TArrayNodeSupport< ArrayType >::bIsArraySubsetSupported, bool >::type = true>
bool RegisterArraySubsetNode ()
Function Documentation
CreateArrayNodeClassMetadata()
METASOUNDFRONTEND_API FNodeClassMetadata Metasound::MetasoundArrayNodesPrivate::CreateArrayNodeClassMetadata (const FName & InDataTypeName, const FName & InOperatorName, const FText & InDisplayName, const FText & InDescription, const FVertexInterface & InDefaultInterface, int32 MajorVersion = 1, int32 MinorVersion = 0, bool bIsDeprecated = false)
Referenced by Metasound::TArrayConcatOperator< ArrayType >::GetNodeInfo(), Metasound::TArrayGetOperator< ArrayType >::GetNodeInfo(), Metasound::TArrayLastIndexOperator< ArrayType >::GetNodeInfo(), Metasound::TArrayNumOperator< ArrayType >::GetNodeInfo(), Metasound::TArrayRandomGetOperator< ArrayType >::GetNodeInfo(), Metasound::TArraySetOperator< ArrayType >::GetNodeInfo(), Metasound::TArrayShuffleOperator< ArrayType >::GetNodeInfo(), and Metasound::TArraySubsetOperator< ArrayType >::GetNodeInfo().
RegisterArrayConcatNode()
template<typename ArrayType, typename std::enable_if< TArrayNodeSupport< ArrayType >::bIsArrayConcatSupported, bool >::type = true> bool Metasound::MetasoundArrayNodesPrivate::RegisterArrayConcatNode ()
Definition at line 112 of file MetasoundArrayNodesRegistration.h.
References Metasound::MetasoundArrayNodesPrivate::TArrayNodeSupport< ArrayType >::bIsArrayConcatSupported, and Metasound::Frontend::RegisterNode().
RegisterArrayGetNode()
template<typename ArrayType, typename std::enable_if< TArrayNodeSupport< ArrayType >::bIsArrayGetSupported, bool >::type = true> bool Metasound::MetasoundArrayNodesPrivate::RegisterArrayGetNode ()
Definition at line 64 of file MetasoundArrayNodesRegistration.h.
References Metasound::Frontend::RegisterNode().
RegisterArrayLastIndexNode()
template<typename ArrayType, typename std::enable_if< TArrayNodeSupport< ArrayType >::bIsArrayNumSupported, bool >::type = true> bool Metasound::MetasoundArrayNodesPrivate::RegisterArrayLastIndexNode ()
Definition at line 170 of file MetasoundArrayNodesRegistration.h.
References Metasound::Frontend::RegisterNode().
RegisterArrayNumNode()
template<typename ArrayType, typename std::enable_if< TArrayNodeSupport< ArrayType >::bIsArrayNumSupported, bool >::type = true> bool Metasound::MetasoundArrayNodesPrivate::RegisterArrayNumNode ()
Definition at line 129 of file MetasoundArrayNodesRegistration.h.
References Metasound::Frontend::RegisterNode().
RegisterArrayRandomGetNode()
template<typename ArrayType, typename std::enable_if< TArrayNodeSupport< ArrayType >::bIsArrayRandomGetSupported, bool >::type = true> bool Metasound::MetasoundArrayNodesPrivate::RegisterArrayRandomGetNode ()
Definition at line 156 of file MetasoundArrayNodesRegistration.h.
References Metasound::Frontend::RegisterNode().
RegisterArraySetNode()
template<typename ArrayType, typename std::enable_if< TArrayNodeSupport< ArrayType >::bIsArraySetSupported, bool >::type = true> bool Metasound::MetasoundArrayNodesPrivate::RegisterArraySetNode ()
Definition at line 78 of file MetasoundArrayNodesRegistration.h.
References Metasound::MetasoundArrayNodesPrivate::TArrayNodeSupport< ArrayType >::bIsArraySetSupported, and Metasound::Frontend::RegisterNode().
RegisterArrayShuffleNode()
template<typename ArrayType, typename std::enable_if< TArrayNodeSupport< ArrayType >::bIsArrayShuffleSupported, bool >::type = true> bool Metasound::MetasoundArrayNodesPrivate::RegisterArrayShuffleNode ()
Definition at line 142 of file MetasoundArrayNodesRegistration.h.
References Metasound::Frontend::RegisterNode().
RegisterArraySubsetNode()
template<typename ArrayType, typename std::enable_if< TArrayNodeSupport< ArrayType >::bIsArraySubsetSupported, bool >::type = true> bool Metasound::MetasoundArrayNodesPrivate::RegisterArraySubsetNode ()
Definition at line 95 of file MetasoundArrayNodesRegistration.h.
References Metasound::MetasoundArrayNodesPrivate::TArrayNodeSupport< ArrayType >::bIsArraySubsetSupported, and Metasound::Frontend::RegisterNode().