Unreal Engine 5.6 C++ API: LandscapeDataAccess Namespace Reference
LandscapeDataAccess Namespace Reference
Functions
FORCEINLINE float GetLocalHeight (uint16 Height)
FORCEINLINE uint16 GetTexHeight (float Height)
FORCEINLINE FColor PackHeight (uint16 Height)
FORCEINLINE float UnpackHeight (const FColor &InHeightmapSample)
FORCEINLINE FVector UnpackNormal (const FColor &InHeightmapSample)
Variables
constexpr int32 MaxValue = 65535
constexpr float MidValue = 32768.f
Function Documentation
GetLocalHeight()
FORCEINLINE float LandscapeDataAccess::GetLocalHeight (uint16 Height)
Definition at line 28 of file LandscapeDataAccess.h.
References FORCEINLINE, LANDSCAPE_ZSCALE, and MidValue.
Referenced by FLandscapeComponentDataInterface::GetLocalHeight(), FLandscapeComponentDataInterface::GetLocalHeight(), FLandscapeComponentDataInterfaceBase::GetLocalHeight(), FLandscapeComponentDataInterfaceBase::GetLocalVertex(), and UnpackHeight().
GetTexHeight()
FORCEINLINE uint16 LandscapeDataAccess::GetTexHeight (float Height)
Definition at line 33 of file LandscapeDataAccess.h.
References FMath::Clamp(), FORCEINLINE, LANDSCAPE_INV_ZSCALE, MaxValue, and MidValue.
PackHeight()
FORCEINLINE FColor LandscapeDataAccess::PackHeight (uint16 Height)
Definition at line 38 of file LandscapeDataAccess.h.
References Color, ForceInit, FORCEINLINE, and MoveTemp().
UnpackHeight()
FORCEINLINE float LandscapeDataAccess::UnpackHeight (const FColor & InHeightmapSample)
Definition at line 46 of file LandscapeDataAccess.h.
References FORCEINLINE, FColor::G, GetLocalHeight(), and FColor::R.
UnpackNormal()
FORCEINLINE FVector LandscapeDataAccess::UnpackNormal (const FColor & InHeightmapSample)
Definition at line 52 of file LandscapeDataAccess.h.
References FColor::A, FColor::B, FORCEINLINE, FVector, FMath::Max, Normal, and FMath::Square().
Referenced by FLandscapeComponentDataInterface::GetLocalTangentVectors(), and FLandscapeComponentDataInterfaceBase::GetLocalTangentVectors().
Variable Documentation
MaxValue
int32 LandscapeDataAccess::MaxValue = 65535 inline constexpr
Definition at line 26 of file LandscapeDataAccess.h.
Referenced by GetTexHeight().
MidValue
float LandscapeDataAccess::MidValue = 32768.f inline constexpr
Definition at line 27 of file LandscapeDataAccess.h.
Referenced by GetLocalHeight(), and GetTexHeight().