Unreal Engine 5.6 C++ API: FastDecimalFormat Namespace Reference
FastDecimalFormat Namespace Reference
Provides efficient and culture aware number formatting and parsing.
Namespaces
namespace Internal
Functions
const FDecimalNumberFormattingRules & GetCultureAgnosticFormattingRules ()
Get the formatting rules to use when you don't care about culture.
template<typename T>
FORCEINLINE FString NumberToString (const T InVal, const FDecimalNumberFormattingRules &InFormattingRules, const FNumberFormattingOptions &InFormattingOptions)
template<typename T>
FORCEINLINE void NumberToString (const T InVal, const FDecimalNumberFormattingRules &InFormattingRules, const FNumberFormattingOptions &InFormattingOptions, FString &OutString)
uint64 Pow10 (const int32 InExponent)
Return the value of 10^exp for the given exponent value.
FORCEINLINE bool StringToNumber (const TCHAR *InStr, const FDecimalNumberFormattingRules &InFormattingRules, const FNumberParsingOptions &InParsingOptions, double &OutVal, int32 *OutParsedLen=nullptr)
FORCEINLINE bool StringToNumber (const TCHAR *InStr, const FDecimalNumberFormattingRules &InFormattingRules, const FNumberParsingOptions &InParsingOptions, float &OutVal, int32 *OutParsedLen=nullptr)
FORCEINLINE bool StringToNumber (const TCHAR *InStr, const FDecimalNumberFormattingRules &InFormattingRules, const FNumberParsingOptions &InParsingOptions, int16 &OutVal, int32 *OutParsedLen=nullptr)
FORCEINLINE bool StringToNumber (const TCHAR *InStr, const FDecimalNumberFormattingRules &InFormattingRules, const FNumberParsingOptions &InParsingOptions, int32 &OutVal, int32 *OutParsedLen=nullptr)
FORCEINLINE bool StringToNumber (const TCHAR *InStr, const FDecimalNumberFormattingRules &InFormattingRules, const FNumberParsingOptions &InParsingOptions, int64 &OutVal, int32 *OutParsedLen=nullptr)
FORCEINLINE bool StringToNumber (const TCHAR *InStr, const FDecimalNumberFormattingRules &InFormattingRules, const FNumberParsingOptions &InParsingOptions, int8 &OutVal, int32 *OutParsedLen=nullptr)
FORCEINLINE bool StringToNumber (const TCHAR *InStr, const FDecimalNumberFormattingRules &InFormattingRules, const FNumberParsingOptions &InParsingOptions, uint16 &OutVal, int32 *OutParsedLen=nullptr)
FORCEINLINE bool StringToNumber (const TCHAR *InStr, const FDecimalNumberFormattingRules &InFormattingRules, const FNumberParsingOptions &InParsingOptions, uint32 &OutVal, int32 *OutParsedLen=nullptr)
FORCEINLINE bool StringToNumber (const TCHAR *InStr, const FDecimalNumberFormattingRules &InFormattingRules, const FNumberParsingOptions &InParsingOptions, uint64 &OutVal, int32 *OutParsedLen=nullptr)
FORCEINLINE bool StringToNumber (const TCHAR *InStr, const FDecimalNumberFormattingRules &InFormattingRules, const FNumberParsingOptions &InParsingOptions, uint8 &OutVal, int32 *OutParsedLen=nullptr)
FORCEINLINE bool StringToNumber (const TCHAR *InStr, const int32 InStrLen, const FDecimalNumberFormattingRules &InFormattingRules, const FNumberParsingOptions &InParsingOptions, double &OutVal, int32 *OutParsedLen=nullptr)
FORCEINLINE bool StringToNumber (const TCHAR *InStr, const int32 InStrLen, const FDecimalNumberFormattingRules &InFormattingRules, const FNumberParsingOptions &InParsingOptions, float &OutVal, int32 *OutParsedLen=nullptr)
FORCEINLINE bool StringToNumber (const TCHAR *InStr, const int32 InStrLen, const FDecimalNumberFormattingRules &InFormattingRules, const FNumberParsingOptions &InParsingOptions, int16 &OutVal, int32 *OutParsedLen=nullptr)
FORCEINLINE bool StringToNumber (const TCHAR *InStr, const int32 InStrLen, const FDecimalNumberFormattingRules &InFormattingRules, const FNumberParsingOptions &InParsingOptions, int32 &OutVal, int32 *OutParsedLen=nullptr)
FORCEINLINE bool StringToNumber (const TCHAR *InStr, const int32 InStrLen, const FDecimalNumberFormattingRules &InFormattingRules, const FNumberParsingOptions &InParsingOptions, int64 &OutVal, int32 *OutParsedLen=nullptr)
FORCEINLINE bool StringToNumber (const TCHAR *InStr, const int32 InStrLen, const FDecimalNumberFormattingRules &InFormattingRules, const FNumberParsingOptions &InParsingOptions, int8 &OutVal, int32 *OutParsedLen=nullptr)
FORCEINLINE bool StringToNumber (const TCHAR *InStr, const int32 InStrLen, const FDecimalNumberFormattingRules &InFormattingRules, const FNumberParsingOptions &InParsingOptions, uint16 &OutVal, int32 *OutParsedLen=nullptr)
FORCEINLINE bool StringToNumber (const TCHAR *InStr, const int32 InStrLen, const FDecimalNumberFormattingRules &InFormattingRules, const FNumberParsingOptions &InParsingOptions, uint32 &OutVal, int32 *OutParsedLen=nullptr)
FORCEINLINE bool StringToNumber (const TCHAR *InStr, const int32 InStrLen, const FDecimalNumberFormattingRules &InFormattingRules, const FNumberParsingOptions &InParsingOptions, uint64 &OutVal, int32 *OutParsedLen=nullptr)
FORCEINLINE bool StringToNumber (const TCHAR *InStr, const int32 InStrLen, const FDecimalNumberFormattingRules &InFormattingRules, const FNumberParsingOptions &InParsingOptions, uint8 &OutVal, int32 *OutParsedLen=nullptr)
Detailed Description
Provides efficient and culture aware number formatting and parsing.
You would call FastDecimalFormat::NumberToString to convert a number to the correct decimal representation based on the given formatting rules and options. You would call FastDecimalFormat::StringToNumber to convert a string containing a culture correct decimal representation of a number into an actual number. The primary consumer of this is FText, however you can use it for other things. GetCultureAgnosticFormattingRules can provide formatting rules for cases where you don't care about culture.
Note
If you use the version of FastDecimalFormat::NumberToString that takes an output string, the formatted number will be appended to the existing contents of the string.
Function Documentation
GetCultureAgnosticFormattingRules()
const FDecimalNumberFormattingRules & FastDecimalFormat::GetCultureAgnosticFormattingRules ()
Get the formatting rules to use when you don't care about culture.
Referenced by TDefaultNumericTypeInterface< NumericType >::FromString().
NumberToString() [1/2]
template<typename T> FORCEINLINE FString FastDecimalFormat::NumberToString (const T InVal, const FDecimalNumberFormattingRules & InFormattingRules, const FNumberFormattingOptions & InFormattingOptions)
Definition at line 144 of file FastDecimalFormat.h.
References FORCEINLINE.
NumberToString() [2/2]
template<typename T> FORCEINLINE void FastDecimalFormat::NumberToString (const T InVal, const FDecimalNumberFormattingRules & InFormattingRules, const FNumberFormattingOptions & InFormattingOptions, FString & OutString)
Definition at line 115 of file FastDecimalFormat.h.
References FORCEINLINE, FastDecimalFormat::Internal::FractionalToString(), and FastDecimalFormat::Internal::IntegralToString().
Referenced by FVariablePrecisionNumericInterface::ToString(), and TDefaultNumericTypeInterface< NumericType >::ToString().
Pow10()
uint64 FastDecimalFormat::Pow10 (const int32 InExponent)
Return the value of 10^exp for the given exponent value.
Note
The maximum exponent supported is 10^18.
StringToNumber() [1/20]
FORCEINLINE bool FastDecimalFormat::StringToNumber (const TCHAR * InStr, const FDecimalNumberFormattingRules & InFormattingRules, const FNumberParsingOptions & InParsingOptions, double & OutVal, int32 * OutParsedLen = nullptr)
Definition at line 190 of file FastDecimalFormat.h.
StringToNumber() [2/20]
FORCEINLINE bool FastDecimalFormat::StringToNumber (const TCHAR * InStr, const FDecimalNumberFormattingRules & InFormattingRules, const FNumberParsingOptions & InParsingOptions, float & OutVal, int32 * OutParsedLen = nullptr)
Definition at line 189 of file FastDecimalFormat.h.
StringToNumber() [3/20]
FORCEINLINE bool FastDecimalFormat::StringToNumber (const TCHAR * InStr, const FDecimalNumberFormattingRules & InFormattingRules, const FNumberParsingOptions & InParsingOptions, int16 & OutVal, int32 * OutParsedLen = nullptr)
Definition at line 180 of file FastDecimalFormat.h.
StringToNumber() [4/20]
FORCEINLINE bool FastDecimalFormat::StringToNumber (const TCHAR * InStr, const FDecimalNumberFormattingRules & InFormattingRules, const FNumberParsingOptions & InParsingOptions, int32 & OutVal, int32 * OutParsedLen = nullptr)
Definition at line 181 of file FastDecimalFormat.h.
StringToNumber() [5/20]
FORCEINLINE bool FastDecimalFormat::StringToNumber (const TCHAR * InStr, const FDecimalNumberFormattingRules & InFormattingRules, const FNumberParsingOptions & InParsingOptions, int64 & OutVal, int32 * OutParsedLen = nullptr)
Definition at line 182 of file FastDecimalFormat.h.
StringToNumber() [6/20]
FORCEINLINE bool FastDecimalFormat::StringToNumber (const TCHAR * InStr, const FDecimalNumberFormattingRules & InFormattingRules, const FNumberParsingOptions & InParsingOptions, int8 & OutVal, int32 * OutParsedLen = nullptr)
Definition at line 179 of file FastDecimalFormat.h.
StringToNumber() [7/20]
FORCEINLINE bool FastDecimalFormat::StringToNumber (const TCHAR * InStr, const FDecimalNumberFormattingRules & InFormattingRules, const FNumberParsingOptions & InParsingOptions, uint16 & OutVal, int32 * OutParsedLen = nullptr)
Definition at line 185 of file FastDecimalFormat.h.
StringToNumber() [8/20]
FORCEINLINE bool FastDecimalFormat::StringToNumber (const TCHAR * InStr, const FDecimalNumberFormattingRules & InFormattingRules, const FNumberParsingOptions & InParsingOptions, uint32 & OutVal, int32 * OutParsedLen = nullptr)
Definition at line 186 of file FastDecimalFormat.h.
StringToNumber() [9/20]
FORCEINLINE bool FastDecimalFormat::StringToNumber (const TCHAR * InStr, const FDecimalNumberFormattingRules & InFormattingRules, const FNumberParsingOptions & InParsingOptions, uint64 & OutVal, int32 * OutParsedLen = nullptr)
Definition at line 187 of file FastDecimalFormat.h.
StringToNumber() [10/20]
FORCEINLINE bool FastDecimalFormat::StringToNumber (const TCHAR * InStr, const FDecimalNumberFormattingRules & InFormattingRules, const FNumberParsingOptions & InParsingOptions, uint8 & OutVal, int32 * OutParsedLen = nullptr)
Definition at line 184 of file FastDecimalFormat.h.
StringToNumber() [11/20]
FORCEINLINE bool FastDecimalFormat::StringToNumber (const TCHAR * InStr, const int32 InStrLen, const FDecimalNumberFormattingRules & InFormattingRules, const FNumberParsingOptions & InParsingOptions, double & OutVal, int32 * OutParsedLen = nullptr)
Definition at line 190 of file FastDecimalFormat.h.
References FAST_DECIMAL_PARSE_FRACTIONAL_IMPL.
StringToNumber() [12/20]
FORCEINLINE bool FastDecimalFormat::StringToNumber (const TCHAR * InStr, const int32 InStrLen, const FDecimalNumberFormattingRules & InFormattingRules, const FNumberParsingOptions & InParsingOptions, float & OutVal, int32 * OutParsedLen = nullptr)
Definition at line 189 of file FastDecimalFormat.h.
References FAST_DECIMAL_PARSE_FRACTIONAL_IMPL.
StringToNumber() [13/20]
FORCEINLINE bool FastDecimalFormat::StringToNumber (const TCHAR * InStr, const int32 InStrLen, const FDecimalNumberFormattingRules & InFormattingRules, const FNumberParsingOptions & InParsingOptions, int16 & OutVal, int32 * OutParsedLen = nullptr)
Definition at line 180 of file FastDecimalFormat.h.
References FAST_DECIMAL_PARSE_INTEGER_IMPL.
StringToNumber() [14/20]
FORCEINLINE bool FastDecimalFormat::StringToNumber (const TCHAR * InStr, const int32 InStrLen, const FDecimalNumberFormattingRules & InFormattingRules, const FNumberParsingOptions & InParsingOptions, int32 & OutVal, int32 * OutParsedLen = nullptr)
Definition at line 181 of file FastDecimalFormat.h.
References FAST_DECIMAL_PARSE_INTEGER_IMPL.
StringToNumber() [15/20]
FORCEINLINE bool FastDecimalFormat::StringToNumber (const TCHAR * InStr, const int32 InStrLen, const FDecimalNumberFormattingRules & InFormattingRules, const FNumberParsingOptions & InParsingOptions, int64 & OutVal, int32 * OutParsedLen = nullptr)
Definition at line 182 of file FastDecimalFormat.h.
References FAST_DECIMAL_PARSE_INTEGER_IMPL.
StringToNumber() [16/20]
FORCEINLINE bool FastDecimalFormat::StringToNumber (const TCHAR * InStr, const int32 InStrLen, const FDecimalNumberFormattingRules & InFormattingRules, const FNumberParsingOptions & InParsingOptions, int8 & OutVal, int32 * OutParsedLen = nullptr)
Definition at line 179 of file FastDecimalFormat.h.
Referenced by TDefaultNumericTypeInterface< NumericType >::FromString().
StringToNumber() [17/20]
FORCEINLINE bool FastDecimalFormat::StringToNumber (const TCHAR * InStr, const int32 InStrLen, const FDecimalNumberFormattingRules & InFormattingRules, const FNumberParsingOptions & InParsingOptions, uint16 & OutVal, int32 * OutParsedLen = nullptr)
Definition at line 185 of file FastDecimalFormat.h.
References FAST_DECIMAL_PARSE_INTEGER_IMPL.
StringToNumber() [18/20]
FORCEINLINE bool FastDecimalFormat::StringToNumber (const TCHAR * InStr, const int32 InStrLen, const FDecimalNumberFormattingRules & InFormattingRules, const FNumberParsingOptions & InParsingOptions, uint32 & OutVal, int32 * OutParsedLen = nullptr)
Definition at line 186 of file FastDecimalFormat.h.
References FAST_DECIMAL_PARSE_INTEGER_IMPL.
StringToNumber() [19/20]
FORCEINLINE bool FastDecimalFormat::StringToNumber (const TCHAR * InStr, const int32 InStrLen, const FDecimalNumberFormattingRules & InFormattingRules, const FNumberParsingOptions & InParsingOptions, uint64 & OutVal, int32 * OutParsedLen = nullptr)
Definition at line 187 of file FastDecimalFormat.h.
References FAST_DECIMAL_PARSE_INTEGER_IMPL.
StringToNumber() [20/20]
FORCEINLINE bool FastDecimalFormat::StringToNumber (const TCHAR * InStr, const int32 InStrLen, const FDecimalNumberFormattingRules & InFormattingRules, const FNumberParsingOptions & InParsingOptions, uint8 & OutVal, int32 * OutParsedLen = nullptr)
Definition at line 184 of file FastDecimalFormat.h.
References FAST_DECIMAL_PARSE_INTEGER_IMPL.