Unreal Engine 5.6 C++ API: UE::ShaderPermutationUtils Namespace Reference
UE::ShaderPermutationUtils Namespace Reference
Functions
template<typename TDimension, typename... Ts>
void FormatPermutationDomain (const TShaderPermutationDomain< TDimension, Ts... > &InShaderPermutationDomain, FString &OutString, bool bFullNames, const TCHAR *Prefix)
void FormatPermutationDomain (const TShaderPermutationDomain<> &InShaderPermutationDomain, FString &OutString, bool bFullNames, const TCHAR *Prefix)
template<typename TDimension>
void FormatPermutationParameter (const typename TDimension::Type &E, FString &OutString, bool bFullNames, const TCHAR *Prefix)
bool ShouldCompileWithWaveSize (const FShaderPermutationParameters &Parameters, int32 WaveSize)
bool ShouldPrecacheWithWaveSize (const FShaderPermutationParameters &Parameters, int32 WaveSize)
Function Documentation
FormatPermutationDomain() [1/2]
template<typename TDimension, typename... Ts> void UE::ShaderPermutationUtils::FormatPermutationDomain (const TShaderPermutationDomain< TDimension, Ts... > & InShaderPermutationDomain, FString & OutString, bool bFullNames, const TCHAR * Prefix)
Definition at line 52 of file ShaderPermutationUtils.h.
References FormatPermutationDomain(), FormatPermutationParameter(), TEXT, and Value.
FormatPermutationDomain() [2/2]
void UE::ShaderPermutationUtils::FormatPermutationDomain (const TShaderPermutationDomain<> & InShaderPermutationDomain, FString & OutString, bool bFullNames, const TCHAR * Prefix)
Definition at line 46 of file ShaderPermutationUtils.h.
References FORCEINLINE.
Referenced by FormatPermutationDomain(), and FormatPermutationParameter().
FormatPermutationParameter()
template<typename TDimension> void UE::ShaderPermutationUtils::FormatPermutationParameter (const typename TDimension::Type & E, FString & OutString, bool bFullNames, const TCHAR * Prefix)
Definition at line 95 of file ShaderPermutationUtils.h.
References FormatPermutationDomain(), TEXT, and FShaderPermutationBool::ToDefineValue().
Referenced by FormatPermutationDomain().
ShouldCompileWithWaveSize()
bool UE::ShaderPermutationUtils::ShouldCompileWithWaveSize (const FShaderPermutationParameters & Parameters, int32 WaveSize) inline
Definition at line 11 of file ShaderPermutationUtils.h.
References FShaderPermutationParameters::Platform.
ShouldPrecacheWithWaveSize()
bool UE::ShaderPermutationUtils::ShouldPrecacheWithWaveSize (const FShaderPermutationParameters & Parameters, int32 WaveSize) inline
Definition at line 30 of file ShaderPermutationUtils.h.