Unreal Engine 5.6 C++ API: ActorElementDataUtil Namespace Reference
ActorElementDataUtil Namespace Reference
Functions
AActor * GetActorFromHandle (const FTypedElementHandle &InHandle, const bool bSilent=false)
Attempt to get the actor from the given element handle.
AActor * GetActorFromHandleChecked (const FTypedElementHandle &InHandle)
Attempt to get the actor from the given element handle, asserting if the element handle doesn't contain FActorElementData.
template<typename ElementHandleType>
TArray< AActor * > GetActorsFromHandles (TArrayView< const ElementHandleType > InHandles, const bool bSilent=false)
Attempt to get the actors from the given element handles.
template<typename ElementHandleType>
TArray< AActor * > GetActorsFromHandlesChecked (TArrayView< const ElementHandleType > InHandles)
Attempt to get the actors from the given element handles, asserting if any element handle doesn't contain FActorElementData.
Function Documentation
GetActorFromHandle()
AActor * ActorElementDataUtil::GetActorFromHandle (const FTypedElementHandle & InHandle, const bool bSilent = false)
Attempt to get the actor from the given element handle.
Note
This is not typically something you'd want to use outside of data access within an interface implementation.
Returns
The actor if the element handle contains FActorElementData, otherwise null.
Referenced by GetActorsFromHandles().
GetActorFromHandleChecked()
AActor * ActorElementDataUtil::GetActorFromHandleChecked (const FTypedElementHandle & InHandle)
Attempt to get the actor from the given element handle, asserting if the element handle doesn't contain FActorElementData.
Note
This is not typically something you'd want to use outside of data access within an interface implementation.
Returns
The actor.
Referenced by GetActorsFromHandlesChecked().
GetActorsFromHandles()
template<typename ElementHandleType> TArray< AActor * > ActorElementDataUtil::GetActorsFromHandles (TArrayView< const ElementHandleType > InHandles, const bool bSilent = false)
Attempt to get the actors from the given element handles.
Note
This is not typically something you'd want to use outside of data access within an interface implementation.
Returns
The actors of any element handles that contain FActorElementData, skipping any that don't.
Definition at line 53 of file ActorElementData.h.
References Actor, Actors, GetActorFromHandle(), Handle, and TArrayView< InElementType, InSizeType >::Num().
GetActorsFromHandlesChecked()
template<typename ElementHandleType> TArray< AActor * > ActorElementDataUtil::GetActorsFromHandlesChecked (TArrayView< const ElementHandleType > InHandles)
Attempt to get the actors from the given element handles, asserting if any element handle doesn't contain FActorElementData.
Note
This is not typically something you'd want to use outside of data access within an interface implementation.
Returns
The actors.
Definition at line 75 of file ActorElementData.h.
References Actors, GetActorFromHandleChecked(), Handle, and TArrayView< InElementType, InSizeType >::Num().