Unreal Engine 5.6 C++ API: UE::PixelStreaming2 Namespace Reference
UE::PixelStreaming2 Namespace Reference
Namespaces
namespace RTCStatCategories
namespace VideoProducerIdentifiers
Data Structures
class FAudioCapturer
class FAudioPatchMixer
class FAudioProducer
An audio input capable of listening to UE submix's as well as receiving user audio via the PushAudio method.
class FAudioSink
class FAudioSource
struct FBufferBuilder
class FEpicRtcAllocator
class FEpicRtcAudioCapturer
FEpicRtcAudioCapturer overrides the default PushAudio behaviour of the FAudioCapturer in order to break up the pushed audio into 10ms chunks.
class FEpicRtcAudioSink
class FEpicRtcAudioSource
class FEpicRtcAudioTrackObserver
class FEpicRtcAudioTrackObserverFactory
class FEpicRtcBoolArray
class FEpicRtcCodecBufferUsageArray
class FEpicRtcDataTrack
class FEpicRtcDataTrackObserver
class FEpicRtcDataTrackObserverFactory
class FEpicRtcDecodeTargetIndicationArray
class FEpicRtcEncodedVideoBuffer
class FEpicRtcFrameDependencyStructure
class FEpicRtcGenericFrameInfo
class FEpicRtcGenericFrameInfoArray
class FEpicRtcInt32Array
class FEpicRtcLogFilter
class FEpicRtcLogsRedirector
class FEpicRtcMutliplexDataTrack
class FEpicRtcParameterPair
class FEpicRtcParameterPairArray
class FEpicRtcPixelFormatArray
class FEpicRtcRoomObserver
class FEpicRtcScalabilityModeArray
class FEpicRtcSessionObserver
class FEpicRtcStatsCollector
class FEpicRtcString
class FEpicRtcTickConferenceTask
class FEpicRtcVideoCapturer
class FEpicRtcVideoCodecInfo
class FEpicRtcVideoDecoderInitializer
class FEpicRtcVideoEncoderInitializer
class FEpicRtcVideoFrameTypeArray
class FEpicRtcVideoParameterPairArray
class FEpicRtcVideoResolutionArray
class FEpicRtcVideoResolutionBitrateLimitsArray
class FEpicRtcVideoSink
Video sink class that receives a frame from EpicRtc and passes the frame to all added consumers.
class FEpicRtcVideoSource
A source of video frames for an EpicRtc peer.
class FEpicRtcVideoTrackObserver
class FEpicRtcVideoTrackObserverFactory
class FEpicRtcWebsocket
class FEpicRtcWebsocketFactory
class FMixAudioTask
class FPatchInputProxy
struct FPixelStreaming2SimulcastLayer
A struct representing the simulcast paramaters of a single simulcast layer used by PixelStreaming2.
struct FPixelStreamingTaskDeleter
TUniquePtr custom deleter that handle automatic unregistering of the task.
class FPixelStreamingTickableTask
Base class for a tickable task.
class FRTCStatsCollector
class FSoundGenerator
An ISoundGenerator implementation to pump some audio from EpicRtc into this synth component.
class FStat
struct FStatConfig
class FStreamerReconnectTimer
An interval timer that triggers reconnects when IPixelStreaming2Streamer has it session disconnect.
class FVideoCapturer
The start of PixelCapture pipeline.
class FVideoCodecInfoArray
class FVideoProducer
class FVideoProducerBackBuffer
Use this if you want to send the contents of the UE backbuffer.
class FVideoProducerMediaCapture
Use this if you want to send media capture frames as video input.
class FVideoProducerPIEViewport
An extension of the back buffer input that can handle PIE sessions.
class FVideoProducerRenderTarget
Use this if you want to send the contents of a render target.
class FVideoProducerUserData
class FVideoSink
class FVideoSource
class FVideoSourceGroup
class ILogManipulator
An interface providing functionality for manipulating EpicRtc logs.
class TEpicRtcTrack
struct TFakeDeleter
class TObserverVariant
class TThreadSafeMap
A TThreadSafeMapBase specialization that only allows a single value associated with each key whilst being thread safe.
Typedefs
using FStatVariant = TVariant<TYPE_OF_NULLPTR, double, FString, bool>
template<typename T>
using TUniqueTaskPtr = TUniquePtr<T, struct FPixelStreamingTaskDeleter>
Functions
template<typename T>
void DoOnGameThread (T &&Func)
template<typename T>
void DoOnGameThreadAndWait (uint32 Timeout, T &&Func)
PIXELSTREAMING2_API void ExtendJsonWithField (const FString &Descriptor, FString FieldName, FString StringValue, FString &OutNewDescriptor, bool &OutSuccess)
Extends an existing JSON string with a new name: value property.
PIXELSTREAMING2_API void ExtractJsonFromDescriptor (FString Descriptor, FString FieldName, FString &OutStringValue, bool &OutSuccess)
Extract a field's value from a JSON string.
size_t GetByteSizeOf (const FString &&Value)
template<typename T>
size_t GetByteSizeOf (const T &&Value)
template<typename T>
size_t GetByteSizeOf (const TArray< T > &&Value)
template<typename TEnumType>
FString GetCVarStringFromEnum (TEnumType Value)
const void * GetDataPointer (const FString &&Value)
template<typename T>
const void * GetDataPointer (const T &&Value)
template<typename T>
const void * GetDataPointer (const TArray< T > &&Value)
template<typename TEnumType>
TEnumType GetEnumFromCVar (const TAutoConsoleVariable< FString > &CVar)
PIXELSTREAMING2SERVERS_API int GetNextAvailablePort (TOptional< int > StartingPort=FNullOpt(0))
TArray< FPixelStreaming2SimulcastLayer > GetSimulcastParameters ()
FORCEINLINE uint32 GetTypeHash (const FStat &Obj)
template<typename TCodec>
bool IsDecoderSupported ()
template<typename TCodec>
bool IsEncoderSupported ()
template<typename TCodec>
bool IsHardwareDecoderSupported ()
As windows supports many RHIs and many codecs, we need to check at runtime if the current codec and RHI is compatible.
template<typename TCodec>
bool IsHardwareEncoderSupported ()
As windows supports many RHIs and many codecs, we need to check at runtime if the current codec and RHI is compatible.
PIXELSTREAMING2_API bool IsPlatformSupported ()
template<typename TCodec>
bool IsSoftwareDecoderSupported ()
template<typename TCodec>
bool IsSoftwareEncoderSupported ()
PIXELSTREAMING2_API bool IsStreamingSupported ()
FString ReadString (const uint8 *&Data, uint32_t &Size)
Reads a string represented by 2 bytes length (in bytes) followed by UTF16 characters.
template<typename T>
TObserverVariant< T > TObserver (TWeakInterfacePtr< T > WeakObserver)
template<typename T>
TObserverVariant< T > TObserver (TWeakPtr< T > WeakObserver)
EpicRtcStringView ToEpicRtcStringView (const FUtf8String &Str)
FString ToString (const EpicRtcStringView &Str)
FString ToString (const TSharedPtr< FJsonObject > &JsonObj, bool bPretty=true)
FString ToString (EpicRtcErrorCode Error)
FString ToString (EpicRtcRoomState State)
FString ToString (EpicRtcTrackState State)
FString ToString (EpicRtcVideoCodec Codec)
Variables
enum PIXELSTREAMING2RTC_API EDisplayFlags
enum PIXELSTREAMING2RTC_API GRAPH = 1 << 1
PIXELSTREAMING2_API TThreadSafeMap< uintptr_t, UPixelStreaming2Input * > InputComponents
constexpr uint32_t NumSimulcastLayers = 3
constexpr uint32_t ScalingFactor = 2
const TStaticArray< EVideoCodec, 4 > SupportedVideoCodecs = { EVideoCodec::H264, EVideoCodec::AV1, EVideoCodec::VP8, EVideoCodec::VP9 }
enum PIXELSTREAMING2RTC_API TEXT = 1 << 0
constexpr EpicRtcLogLevel UnrealLogToEpicRtcCategoryMap []
Typedef Documentation
FStatVariant
using UE::PixelStreaming2::FStatVariant = TVariant<TYPE_OF_NULLPTR, double, FString, bool>
Definition at line 46 of file RTCStatsCollector.h.
TUniqueTaskPtr
template<typename T> using UE::PixelStreaming2::TUniqueTaskPtr = TUniquePtr<T, struct FPixelStreamingTaskDeleter>
Definition at line 10 of file TickableTask.h.
Function Documentation
DoOnGameThread()
template<typename T> void UE::PixelStreaming2::DoOnGameThread (T && Func)
Definition at line 11 of file UtilsAsync.h.
References AsyncTask(), ENamedThreads::GameThread, and IsInGameThread().
DoOnGameThreadAndWait()
template<typename T> void UE::PixelStreaming2::DoOnGameThreadAndWait (uint32 Timeout, T && Func)
Definition at line 24 of file UtilsAsync.h.
References AsyncTask(), ENamedThreads::GameThread, FGenericPlatformProcess::GetSynchEventFromPool(), IsInGameThread(), FGenericPlatformProcess::ReturnSynchEventToPool(), and Timeout.
ExtendJsonWithField()
PIXELSTREAMING2_API void UE::PixelStreaming2::ExtendJsonWithField (const FString & Descriptor, FString FieldName, FString StringValue, FString & OutNewDescriptor, bool & OutSuccess)
Extends an existing JSON string with a new name: value property.
Parameters
Descriptor The JSON string.
FieldName The field name to add the json string.
StringValue The value to set in the new field.
OutNewDescriptor The new JSON string.
OutSuccess True if we were able to extend the JSON string.
ExtractJsonFromDescriptor()
PIXELSTREAMING2_API void UE::PixelStreaming2::ExtractJsonFromDescriptor (FString Descriptor, FString FieldName, FString & OutStringValue, bool & OutSuccess)
Extract a field's value from a JSON string.
Parameters
Descriptor The JSON string.
FieldName The field name to extract a value from.
OutStringValue The value from the extracted field.
OutSuccess True if we were able to extract the value.
GetByteSizeOf() [1/3]
size_t UE::PixelStreaming2::GetByteSizeOf (const FString && Value) inline
Definition at line 29 of file EpicRtcDataTrack.h.
References Value.
GetByteSizeOf() [2/3]
template<typename T> size_t UE::PixelStreaming2::GetByteSizeOf (const T && Value) inline
Definition at line 12 of file EpicRtcDataTrack.h.
References Value.
Referenced by UE::PixelStreaming2::FEpicRtcDataTrack::EncodeMessage(), and UE::PixelStreaming2::FBufferBuilder::Insert().
GetByteSizeOf() [3/3]
template<typename T> size_t UE::PixelStreaming2::GetByteSizeOf (const TArray< T > && Value) inline
Definition at line 46 of file EpicRtcDataTrack.h.
References Value.
GetCVarStringFromEnum()
template<typename TEnumType> FString UE::PixelStreaming2::GetCVarStringFromEnum (TEnumType Value)
Definition at line 31 of file PixelStreaming2PluginSettings.h.
References StaticEnum(), and Value.
GetDataPointer() [1/3]
const void * UE::PixelStreaming2::GetDataPointer (const FString && Value) inline
Definition at line 37 of file EpicRtcDataTrack.h.
References Value.
GetDataPointer() [2/3]
template<typename T> const void * UE::PixelStreaming2::GetDataPointer (const T && Value) inline
Definition at line 21 of file EpicRtcDataTrack.h.
References Value.
Referenced by UE::PixelStreaming2::FBufferBuilder::Insert().
GetDataPointer() [3/3]
template<typename T> const void * UE::PixelStreaming2::GetDataPointer (const TArray< T > && Value) inline
Definition at line 55 of file EpicRtcDataTrack.h.
References Value.
GetEnumFromCVar()
template<typename TEnumType> TEnumType UE::PixelStreaming2::GetEnumFromCVar (const TAutoConsoleVariable< FString > & CVar)
Definition at line 23 of file PixelStreaming2PluginSettings.h.
References checkf, INDEX_NONE, StaticEnum(), and TEXT.
GetNextAvailablePort()
PIXELSTREAMING2SERVERS_API int UE::PixelStreaming2::GetNextAvailablePort (TOptional< int > StartingPort = FNullOpt(0)) extern
GetSimulcastParameters()
TArray< FPixelStreaming2SimulcastLayer > UE::PixelStreaming2::GetSimulcastParameters () inline
Definition at line 30 of file UtilsVideo.h.
References TArray< InElementType, InAllocatorType >::Add(), NumSimulcastLayers, and ScalingFactor.
GetTypeHash()
FORCEINLINE uint32 UE::PixelStreaming2::GetTypeHash (const FStat & Obj)
Definition at line 128 of file RTCStatsCollector.h.
References FORCEINLINE, UE::PixelStreaming2::FStat::GetName(), and GetTypeHash().
Referenced by GetTypeHash().
IsDecoderSupported()
template<typename TCodec> bool UE::PixelStreaming2::IsDecoderSupported ()
Definition at line 115 of file UtilsCoder.h.
References IsHardwareDecoderSupported(), and IsSoftwareDecoderSupported().
IsEncoderSupported()
template<typename TCodec> bool UE::PixelStreaming2::IsEncoderSupported ()
Definition at line 65 of file UtilsCoder.h.
References IsHardwareEncoderSupported(), and IsSoftwareEncoderSupported().
IsHardwareDecoderSupported()
template<typename TCodec> bool UE::PixelStreaming2::IsHardwareDecoderSupported ()
As windows supports many RHIs and many codecs, we need to check at runtime if the current codec and RHI is compatible.
To remove nested switch-cases, this function is templated to take a video decoder config of the target codec. eg:
IsHardwareDecoderSupported<FVideoDecoderConfigVP8>(); OR IsHardwareDecoderSupported<FVideoDecoderConfigAV1>(); OR ...
Definition at line 82 of file UtilsCoder.h.
References Instance, and MakeShared().
Referenced by IsDecoderSupported().
IsHardwareEncoderSupported()
template<typename TCodec> bool UE::PixelStreaming2::IsHardwareEncoderSupported ()
As windows supports many RHIs and many codecs, we need to check at runtime if the current codec and RHI is compatible.
To remove nested switch-cases, this function is templated to take a video encoder config of the target codec. eg:
IsHardwareEncoderSupported<FVideoEncoderConfigH264>(); OR IsHardwareEncoderSupported<FVideoEncoderConfigAV1>(); OR ...
Definition at line 32 of file UtilsCoder.h.
References Instance, and MakeShared().
Referenced by IsEncoderSupported().
IsPlatformSupported()
PIXELSTREAMING2_API bool UE::PixelStreaming2::IsPlatformSupported () inline
Definition at line 42 of file UtilsCore.h.
References FText::FromString(), EAppMsgType::Ok, FMessageDialog::Open(), TEXT, and UE_CALL_ONCE.
IsSoftwareDecoderSupported()
template<typename TCodec> bool UE::PixelStreaming2::IsSoftwareDecoderSupported ()
Definition at line 108 of file UtilsCoder.h.
References Instance, and MakeShared().
Referenced by IsDecoderSupported().
IsSoftwareEncoderSupported()
template<typename TCodec> bool UE::PixelStreaming2::IsSoftwareEncoderSupported ()
Definition at line 58 of file UtilsCoder.h.
References Instance, and MakeShared().
Referenced by IsEncoderSupported().
IsStreamingSupported()
PIXELSTREAMING2_API bool UE::PixelStreaming2::IsStreamingSupported () inline
Definition at line 31 of file UtilsCore.h.
References IsAllowCommandletRendering(), and IsRunningCommandlet().
ReadString()
FString UE::PixelStreaming2::ReadString (const uint8 *& Data, uint32_t & Size) inline
Reads a string represented by 2 bytes length (in bytes) followed by UTF16 characters.
String and length are encoded in little endian format.
Definition at line 192 of file UtilsString.h.
References check, and TSequenceHistory< HistorySize >::Size.
TObserver() [1/2]
template<typename T> TObserverVariant< T > UE::PixelStreaming2::TObserver (TWeakInterfacePtr< T > WeakObserver) inline
Definition at line 82 of file EpicRtcObserver.h.
TObserver() [2/2]
template<typename T> TObserverVariant< T > UE::PixelStreaming2::TObserver (TWeakPtr< T > WeakObserver) inline
Definition at line 76 of file EpicRtcObserver.h.
ToEpicRtcStringView()
EpicRtcStringView UE::PixelStreaming2::ToEpicRtcStringView (const FUtf8String & Str) inline
Definition at line 183 of file UtilsString.h.
ToString() [1/6]
FString UE::PixelStreaming2::ToString (const EpicRtcStringView & Str) inline
Definition at line 177 of file UtilsString.h.
ToString() [2/6]
FString UE::PixelStreaming2::ToString (const TSharedPtr< FJsonObject > & JsonObj, bool bPretty = true) inline
Definition at line 161 of file UtilsString.h.
References Create, and TSharedPtr< ObjectType, InMode >::ToSharedRef().
ToString() [3/6]
FString UE::PixelStreaming2::ToString (EpicRtcErrorCode Error) inline
Definition at line 21 of file UtilsString.h.
References UE::Error, and TEXT.
ToString() [4/6]
FString UE::PixelStreaming2::ToString (EpicRtcRoomState State) inline
Definition at line 127 of file UtilsString.h.
References State, and TEXT.
ToString() [5/6]
FString UE::PixelStreaming2::ToString (EpicRtcTrackState State) inline
Definition at line 147 of file UtilsString.h.
References State, and TEXT.
ToString() [6/6]
FString UE::PixelStreaming2::ToString (EpicRtcVideoCodec Codec) inline
Definition at line 100 of file UtilsString.h.
References TEXT.
Variable Documentation
EDisplayFlags
enum PIXELSTREAMING2RTC_API UE::PixelStreaming2::EDisplayFlags
Definition at line 32 of file RTCStatsCollector.h.
GRAPH
enum PIXELSTREAMING2RTC_API UE::PixelStreaming2::GRAPH = 1 << 1
Definition at line 36 of file RTCStatsCollector.h.
InputComponents
PIXELSTREAMING2_API TThreadSafeMap<uintptr_t, UPixelStreaming2Input*> UE::PixelStreaming2::InputComponents extern
NumSimulcastLayers
uint32_t UE::PixelStreaming2::NumSimulcastLayers = 3 constexpr
Definition at line 15 of file UtilsVideo.h.
Referenced by GetSimulcastParameters().
ScalingFactor
uint32_t UE::PixelStreaming2::ScalingFactor = 2 constexpr
Definition at line 17 of file UtilsVideo.h.
Referenced by GetSimulcastParameters().
SupportedVideoCodecs
const TStaticArray<EVideoCodec, 4> UE::PixelStreaming2::SupportedVideoCodecs = { EVideoCodec::H264, EVideoCodec::AV1, EVideoCodec::VP8, EVideoCodec::VP9 }
Definition at line 13 of file UtilsVideo.h.
TEXT
enum PIXELSTREAMING2RTC_API UE::PixelStreaming2::TEXT = 1 << 0
Definition at line 35 of file RTCStatsCollector.h.
Referenced by GetEnumFromCVar(), IsPlatformSupported(), ToString(), ToString(), ToString(), and ToString().
UnrealLogToEpicRtcCategoryMap
EpicRtcLogLevel UE::PixelStreaming2::UnrealLogToEpicRtcCategoryMap[] constexpr
Initial value:
= {
        EpicRtcLogLevel::Off,
        EpicRtcLogLevel::Critical,
        EpicRtcLogLevel::Error,
        EpicRtcLogLevel::Warning,
        EpicRtcLogLevel::Info,
        EpicRtcLogLevel::Info,
        EpicRtcLogLevel::Debug,
        EpicRtcLogLevel::Trace,
        EpicRtcLogLevel::Trace
    }
Definition at line 16 of file EpicRtcLogging.h.