Unreal Engine 5.6 C++ API: UE::Geometry::ExactPredicates Namespace Reference
UE::Geometry::ExactPredicates Namespace Reference
Functions
template<typename RealType>
RealType Facing2 (const TVector2< RealType > &A, const TVector2< RealType > &B, const TVector2< RealType > &Direction)
double GEOMETRYCORE_API Facing2D (const double *PA, const double *PB, const double *Direction)
float GEOMETRYCORE_API Facing2D (const float *PA, const float *PB, const float *PC)
template<typename RealType>
RealType Facing3 (const TVector< RealType > &A, const TVector< RealType > &B, const TVector< RealType > &C, const TVector< RealType > &Direction)
TVector-only version that can run in float or double.
double GEOMETRYCORE_API Facing3D (const double *PA, const double *PB, const double *PC, const double *Direction)
float GEOMETRYCORE_API Facing3D (const float *PA, const float *PB, const float *PC, const float *Direction)
void GEOMETRYCORE_API GlobalInit ()
Must be called once for exact predicates to work.
double GEOMETRYCORE_API InCircle (const double *PA, const double *PB, const double *PC, const double *PD)
float GEOMETRYCORE_API InCircle (const float *PA, const float *PB, const float *PC, const float *PD)
template<typename RealType>
RealType InCircle2 (const TVector2< RealType > &A, const TVector2< RealType > &B, const TVector2< RealType > &C, const TVector2< RealType > &D)
TVector2-only version that can run in float or double.
double GEOMETRYCORE_API InCircleInexact (const double *PA, const double *PB, const double *PC, const double *PD)
float GEOMETRYCORE_API InCircleInexact (const float *PA, const float *PB, const float *PC, const float *PD)
double GEOMETRYCORE_API InSphere (const double *PA, const double *PB, const double *PC, const double *PD, const double *PE)
template<typename RealType>
RealType InSphere3 (const TVector< RealType > &A, const TVector< RealType > &B, const TVector< RealType > &C, const TVector< RealType > &D, const TVector< RealType > &E)
TVector-only version that can run in float or double.
double GEOMETRYCORE_API InSphereInexact (const double *PA, const double *PB, const double *PC, const double *PD, const double *PE)
template<typename RealType>
RealType Orient2 (const TVector2< RealType > &A, const TVector2< RealType > &B, const TVector2< RealType > &C)
TVector2-only version that can run in float or double.
double GEOMETRYCORE_API Orient2D (const double *PA, const double *PB, const double *PC)
float GEOMETRYCORE_API Orient2D (const float *PA, const float *PB, const float *PC)
double GEOMETRYCORE_API Orient2DInexact (const double *PA, const double *PB, const double *PC)
float GEOMETRYCORE_API Orient2DInexact (const float *PA, const float *PB, const float *PC)
double GEOMETRYCORE_API Orient2DOrigin (double ax, double ay, double bx, double by)
float GEOMETRYCORE_API Orient2DOrigin (float ax, float ay, float bx, float by)
template<typename RealType>
RealType Orient2Origin (const TVector2< RealType > &A, const TVector2< RealType > &B)
template<typename RealType>
RealType Orient3 (const TVector< RealType > &A, const TVector< RealType > &B, const TVector< RealType > &C, const TVector< RealType > &D)
TVector-only version that can run in float or double.
double GEOMETRYCORE_API Orient3D (const double *PA, const double *PB, const double *PC, const double *PD)
float GEOMETRYCORE_API Orient3D (const float *PA, const float *PB, const float *PC, const float *PD)
double GEOMETRYCORE_API Orient3DInexact (const double *PA, const double *PB, const double *PC, const double *PD)
float GEOMETRYCORE_API Orient3DInexact (const float *PA, const float *PB, const float *PC, const float *PD)
Function Documentation
Facing2()
template<typename RealType> RealType UE::Geometry::ExactPredicates::Facing2 (const TVector2< RealType > & A, const TVector2< RealType > & B, const TVector2< RealType > & Direction)
Returns
value w/ sign indicating whether the normal of line AB is facing Direction (and 0 if parallel) (i.e. the sign of -PerpCW(B-A) dot Dir)
Definition at line 114 of file ExactPredicates.h.
References A, B, Facing2D(), UE::Math::TVector2< T >::X, and UE::Math::TVector2< T >::Y.
Facing2D() [1/2]
double GEOMETRYCORE_API UE::Geometry::ExactPredicates::Facing2D (const double * PA, const double * PB, const double * Direction)
Referenced by Facing2().
Facing2D() [2/2]
float GEOMETRYCORE_API UE::Geometry::ExactPredicates::Facing2D (const float * PA, const float * PB, const float * PC)
Facing3()
template<typename RealType> RealType UE::Geometry::ExactPredicates::Facing3 (const TVector< RealType > & A, const TVector< RealType > & B, const TVector< RealType > & C, const TVector< RealType > & Direction)
TVector-only version that can run in float or double.
Returns
value w/ sign indicating whether triangle ABC is facing Direction, or 0 if it is parallel to Direction
Definition at line 127 of file ExactPredicates.h.
References A, B, Facing3D(), UE::Math::TVector< T >::X, UE::Math::TVector< T >::Y, and UE::Math::TVector< T >::Z.
Facing3D() [1/2]
double GEOMETRYCORE_API UE::Geometry::ExactPredicates::Facing3D (const double * PA, const double * PB, const double * PC, const double * Direction)
Referenced by Facing3().
Facing3D() [2/2]
float GEOMETRYCORE_API UE::Geometry::ExactPredicates::Facing3D (const float * PA, const float * PB, const float * PC, const float * Direction)
GlobalInit()
void GEOMETRYCORE_API UE::Geometry::ExactPredicates::GlobalInit ()
Must be called once for exact predicates to work.
Will be called by GeometryAlgorithmsModule startup, so you don't need to manually call this.
InCircle() [1/2]
double GEOMETRYCORE_API UE::Geometry::ExactPredicates::InCircle (const double * PA, const double * PB, const double * PC, const double * PD)
Referenced by InCircle2().
InCircle() [2/2]
float GEOMETRYCORE_API UE::Geometry::ExactPredicates::InCircle (const float * PA, const float * PB, const float * PC, const float * PD)
InCircle2()
template<typename RealType> RealType UE::Geometry::ExactPredicates::InCircle2 (const TVector2< RealType > & A, const TVector2< RealType > & B, const TVector2< RealType > & C, const TVector2< RealType > & D)
TVector2-only version that can run in float or double.
Returns
value indicating whether point D is inside, outside, or exactly on the circle passing through ABC Note: Sign of the result depends on the orientation of triangle ABC – Counterclockwise: Inside is positive Clockwise: Inside is negative
Definition at line 154 of file ExactPredicates.h.
References A, B, and InCircle().
InCircleInexact() [1/2]
double GEOMETRYCORE_API UE::Geometry::ExactPredicates::InCircleInexact (const double * PA, const double * PB, const double * PC, const double * PD)
InCircleInexact() [2/2]
float GEOMETRYCORE_API UE::Geometry::ExactPredicates::InCircleInexact (const float * PA, const float * PB, const float * PC, const float * PD)
InSphere()
double GEOMETRYCORE_API UE::Geometry::ExactPredicates::InSphere (const double * PA, const double * PB, const double * PC, const double * PD, const double * PE)
Referenced by InSphere3().
InSphere3()
template<typename RealType> RealType UE::Geometry::ExactPredicates::InSphere3 (const TVector< RealType > & A, const TVector< RealType > & B, const TVector< RealType > & C, const TVector< RealType > & D, const TVector< RealType > & E)
TVector-only version that can run in float or double.
Returns
value indicating whether point E is inside, outside, or exactly on the sphere passing through ABCD Note: Sign of the result depends on the orientation of tetrahedron ABCD
Definition at line 179 of file ExactPredicates.h.
References A, B, InSphere(), UE::Math::TVector< T >::X, UE::Math::TVector< T >::Y, and UE::Math::TVector< T >::Z.
InSphereInexact()
double GEOMETRYCORE_API UE::Geometry::ExactPredicates::InSphereInexact (const double * PA, const double * PB, const double * PC, const double * PD, const double * PE)
Orient2()
template<typename RealType> RealType UE::Geometry::ExactPredicates::Orient2 (const TVector2< RealType > & A, const TVector2< RealType > & B, const TVector2< RealType > & C)
TVector2-only version that can run in float or double.
Returns
value indicating which side of line AB point C is on, or 0 if ABC are collinear
Definition at line 71 of file ExactPredicates.h.
References A, B, and Orient2D().
Orient2D() [1/2]
double GEOMETRYCORE_API UE::Geometry::ExactPredicates::Orient2D (const double * PA, const double * PB, const double * PC)
Referenced by Orient2().
Orient2D() [2/2]
float GEOMETRYCORE_API UE::Geometry::ExactPredicates::Orient2D (const float * PA, const float * PB, const float * PC)
Orient2DInexact() [1/2]
double GEOMETRYCORE_API UE::Geometry::ExactPredicates::Orient2DInexact (const double * PA, const double * PB, const double * PC)
Orient2DInexact() [2/2]
float GEOMETRYCORE_API UE::Geometry::ExactPredicates::Orient2DInexact (const float * PA, const float * PB, const float * PC)
Orient2DOrigin() [1/2]
double GEOMETRYCORE_API UE::Geometry::ExactPredicates::Orient2DOrigin (double ax, double ay, double bx, double by)
Referenced by Orient2Origin().
Orient2DOrigin() [2/2]
float GEOMETRYCORE_API UE::Geometry::ExactPredicates::Orient2DOrigin (float ax, float ay, float bx, float by)
Orient2Origin()
template<typename RealType> RealType UE::Geometry::ExactPredicates::Orient2Origin (const TVector2< RealType > & A, const TVector2< RealType > & B) inline
Definition at line 80 of file ExactPredicates.h.
References A, B, and Orient2DOrigin().
Referenced by UE::Geometry::TIntrRay3Triangle3< float >::FindWatertightIntersectionInternal().
Orient3()
template<typename RealType> RealType UE::Geometry::ExactPredicates::Orient3 (const TVector< RealType > & A, const TVector< RealType > & B, const TVector< RealType > & C, const TVector< RealType > & D)
TVector-only version that can run in float or double.
Returns
value indicating which side of triangle ABC point D is on, or 0 if ABCD are coplanar
Definition at line 90 of file ExactPredicates.h.
References A, B, and Orient3D().
Referenced by UE::Geometry::TExactIntrTriangle3Triangle3< float >::FindOrTestWithoutCoplanar(), and UE::Geometry::TetUtil::IsInsideExact().
Orient3D() [1/2]
double GEOMETRYCORE_API UE::Geometry::ExactPredicates::Orient3D (const double * PA, const double * PB, const double * PC, const double * PD)
Referenced by Orient3().
Orient3D() [2/2]
float GEOMETRYCORE_API UE::Geometry::ExactPredicates::Orient3D (const float * PA, const float * PB, const float * PC, const float * PD)
Orient3DInexact() [1/2]
double GEOMETRYCORE_API UE::Geometry::ExactPredicates::Orient3DInexact (const double * PA, const double * PB, const double * PC, const double * PD)
Orient3DInexact() [2/2]
float GEOMETRYCORE_API UE::Geometry::ExactPredicates::Orient3DInexact (const float * PA, const float * PB, const float * PC, const float * PD)