Unreal Engine 5.6 C++ API: EditorUtilities Namespace Reference
EditorUtilities Namespace Reference
Namespaces
namespace ECopyOptions
Options for CopyActorProperties.
Data Structures
struct FCopyOptions
Copy options structure for CopyActorProperties.
struct FMultiStepsImportObjectParams
Parameters for the ImportCreateObjectStep and ImportObjectPropertiesStep.
Functions
UNREALED_API int32 CopyActorProperties (AActor *SourceActor, AActor *TargetActor, const FCopyOptions &Options=FCopyOptions(ECopyOptions::Default))
Copies properties from one actor to another.
UNREALED_API void CopySingleProperty (const UObject *const InSourceObject, UObject *const InTargetObject, FProperty *const InProperty)
Helper function for CopyActorProperties().
UNREALED_API UActorComponent * FindMatchingComponentInstance (UActorComponent *SourceComponent, AActor *TargetActor)
Guiven an actor in the editor world, and SourceComponent from Simulation or PIE world find the matching component in the Editor World.
UNREALED_API AActor * GetEditorWorldCounterpartActor (AActor *Actor)
Given an actor in a Simulation or PIE world, tries to find a counterpart actor in the editor world.
UNREALED_API AActor * GetSimWorldCounterpartActor (AActor *Actor)
Given an actor in the editor world, tries to find a counterpart actor in a Simulation or PIE world.
UNREALED_API const TCHAR * ImportCreateObjectsStep (FMultiStepsImportObjectParams &InParams)
Parse text and create the objects for the object specified.
UNREALED_API const TCHAR * ImportObjectsPropertiesStep (FMultiStepsImportObjectParams &InParams)
Parse text and import the properties for the object specified and its subobjects.
Function Documentation
CopyActorProperties()
UNREALED_API int32 EditorUtilities::CopyActorProperties (AActor * SourceActor, AActor * TargetActor, const FCopyOptions & Options = FCopyOptions(ECopyOptions::Default))
Copies properties from one actor to another.
Designed for propagating changes made to PIE actors back to their EditorWorld counterpart, or pushing spawned actor changes back to a Blueprint CDO object. You can pass the 'PreviewOnly' option to count the properties that would be copied instead of actually copying them.
Parameters
SourceActor Actor to copy properties from
TargetActor Actor that will be modified with properties propagated from the source actor
Options Optional options for this copy action (see ECopyOptions::Type)
Returns
The number of properties that were copied over (properties that were filtered out, or were already identical, are not counted.)
References CopyActorProperties(), and EditorUtilities::ECopyOptions::Default.
Referenced by CopyActorProperties().
CopySingleProperty()
UNREALED_API void EditorUtilities::CopySingleProperty (const UObject *const InSourceObject, UObject *const InTargetObject, FProperty *const InProperty)
Helper function for CopyActorProperties().
Copies a single property form a source object to a target object.
References CopySingleProperty().
Referenced by CopySingleProperty().
FindMatchingComponentInstance()
UNREALED_API UActorComponent * EditorUtilities::FindMatchingComponentInstance (UActorComponent * SourceComponent, AActor * TargetActor)
Guiven an actor in the editor world, and SourceComponent from Simulation or PIE world find the matching component in the Editor World.
Parameters
SourceComponent SouceCompoent in SIM world
TargetActor TargetActor in editor world
Returns
the sound editor component or NULL if we couldn't find
References FindMatchingComponentInstance().
Referenced by FindMatchingComponentInstance().
GetEditorWorldCounterpartActor()
UNREALED_API AActor * EditorUtilities::GetEditorWorldCounterpartActor (AActor * Actor)
Given an actor in a Simulation or PIE world, tries to find a counterpart actor in the editor world.
Parameters
Actor The simulation world actor that we want to find a counterpart for
Returns
The found editor world actor, or NULL if we couldn't find a counterpart
References Actor, and GetEditorWorldCounterpartActor().
Referenced by GetEditorWorldCounterpartActor().
GetSimWorldCounterpartActor()
UNREALED_API AActor * EditorUtilities::GetSimWorldCounterpartActor (AActor * Actor)
Given an actor in the editor world, tries to find a counterpart actor in a Simulation or PIE world.
Parameters
Actor The editor world actor that we want to find a counterpart for
Returns
The found Simulation or PIE world actor, or NULL if we couldn't find a counterpart
References Actor, and GetSimWorldCounterpartActor().
Referenced by GetSimWorldCounterpartActor().
ImportCreateObjectsStep()
UNREALED_API const TCHAR * EditorUtilities::ImportCreateObjectsStep (FMultiStepsImportObjectParams & InParams)
Parse text and create the objects for the object specified.
See ImportObjectPropertiesStep for the next step of the multi steps object import
Parameters
InParams Parameters for object the multistep object import; see declaration of FMultiStepsImportObjectParams.
Returns
nullptr if the objects couldn't be imported
References ImportCreateObjectsStep().
Referenced by ImportCreateObjectsStep().
ImportObjectsPropertiesStep()
UNREALED_API const TCHAR * EditorUtilities::ImportObjectsPropertiesStep (FMultiStepsImportObjectParams & InParams)
Parse text and import the properties for the object specified and its subobjects.
Call ImportCreateObjectsStep before calling this function to create the subobjects
Parameters
InParams Parameters for object the multistep object import; see declaration of FMultiStepsImportObjectParams.
Returns
nullptr if the values couldn't be imported
References ImportObjectsPropertiesStep().
Referenced by ImportObjectsPropertiesStep().