Unreal Engine 5.6 C++ API: IntersectionUtil Namespace Reference
IntersectionUtil Namespace Reference
IntersectionUtil contains functions to compute intersections between geometric objects.
Functions
template<typename RealType>
FLinearIntersection LineSphereIntersection (const TVector< RealType > &LineOrigin, const TVector< RealType > &LineDirection, const TVector< RealType > &SphereCenter, RealType SphereRadius)
template<typename RealType>
bool LineSphereIntersection (const TVector< RealType > &LineOrigin, const TVector< RealType > &LineDirection, const TVector< RealType > &SphereCenter, RealType SphereRadius, FLinearIntersection &ResultOut)
Intersect line with sphere and return intersection info (# hits, ray parameters)
template<typename RealType>
bool LineSphereTest (const TVector< RealType > &LineOrigin, const TVector< RealType > &LineDirection, const TVector< RealType > &SphereCenter, RealType SphereRadius)
Test if line intersects sphere.
template<typename RealType>
bool RayCircleIntersection (const TVector< RealType > &RayOrigin, const TVector< RealType > &RayDirection, const TVector< RealType > &CircleCenter, RealType CircleRadius, const TVector< RealType > &CircleNormal, FLinearIntersection &Result)
Intersect ray with circle and return intersection info (# hits, ray parameters)
template<typename RealType>
FLinearIntersection RaySphereIntersection (const TVector< RealType > &RayOrigin, const TVector< RealType > &RayDirection, const TVector< RealType > &SphereCenter, RealType SphereRadius)
template<typename RealType>
bool RaySphereIntersection (const TVector< RealType > &RayOrigin, const TVector< RealType > &RayDirection, const TVector< RealType > &SphereCenter, RealType SphereRadius, FLinearIntersection &Result)
Intersect ray with sphere and return intersection info (# hits, ray parameters)
template<typename RealType>
bool RaySphereTest (const TVector< RealType > &RayOrigin, const TVector< RealType > &RayDirection, const TVector< RealType > &SphereCenter, RealType SphereRadius)
template<typename RealType>
bool RayTriangleTest (const TVector< RealType > &RayOrigin, const TVector< RealType > &RayDirection, const TVector< RealType > &V0, const TVector< RealType > &V1, const TVector< RealType > &V2)
Detailed Description
IntersectionUtil contains functions to compute intersections between geometric objects.
Function Documentation
LineSphereIntersection() [1/2]
template<typename RealType> FLinearIntersection IntersectionUtil::LineSphereIntersection (const TVector< RealType > & LineOrigin, const TVector< RealType > & LineDirection, const TVector< RealType > & SphereCenter, RealType SphereRadius)
Definition at line 177 of file IntersectionUtil.h.
References LineSphereIntersection().
LineSphereIntersection() [2/2]
template<typename RealType> bool IntersectionUtil::LineSphereIntersection (const TVector< RealType > & LineOrigin, const TVector< RealType > & LineDirection, const TVector< RealType > & SphereCenter, RealType SphereRadius, FLinearIntersection & ResultOut)
Intersect line with sphere and return intersection info (# hits, ray parameters)
Returns
true if line intersects sphere
Definition at line 133 of file IntersectionUtil.h.
References UE::Math::TVector< T >::Dot(), UE::Geometry::FLinearIntersection::intersects, UE::Geometry::TInterval1< RealType >::Max, UE::Geometry::TInterval1< RealType >::Min, UE::Geometry::FLinearIntersection::numIntersections, UE::Geometry::FLinearIntersection::parameter, and UE::Math::TVector< T >::SquaredLength().
Referenced by LineSphereIntersection(), RaySphereIntersection(), and RaySphereIntersection().
LineSphereTest()
template<typename RealType> bool IntersectionUtil::LineSphereTest (const TVector< RealType > & LineOrigin, const TVector< RealType > & LineDirection, const TVector< RealType > & SphereCenter, RealType SphereRadius)
Test if line intersects sphere.
Returns
true if line intersects sphere
Definition at line 104 of file IntersectionUtil.h.
References UE::Math::TVector< T >::Dot(), and UE::Math::TVector< T >::SquaredLength().
RayCircleIntersection()
template<typename RealType> bool IntersectionUtil::RayCircleIntersection (const TVector< RealType > & RayOrigin, const TVector< RealType > & RayDirection, const TVector< RealType > & CircleCenter, RealType CircleRadius, const TVector< RealType > & CircleNormal, FLinearIntersection & Result)
Intersect ray with circle and return intersection info (# hits, ray parameters)
Returns
true if ray intersects circle
Definition at line 279 of file IntersectionUtil.h.
References UE::Math::TVector< T >::DotProduct(), FMath::IsNearlyZero(), Plane, FMath::RayPlaneIntersectionParam(), and UE::Math::TVector< T >::SizeSquared().
RaySphereIntersection() [1/2]
template<typename RealType> FLinearIntersection IntersectionUtil::RaySphereIntersection (const TVector< RealType > & RayOrigin, const TVector< RealType > & RayDirection, const TVector< RealType > & SphereCenter, RealType SphereRadius)
Definition at line 263 of file IntersectionUtil.h.
References LineSphereIntersection().
RaySphereIntersection() [2/2]
template<typename RealType> bool IntersectionUtil::RaySphereIntersection (const TVector< RealType > & RayOrigin, const TVector< RealType > & RayDirection, const TVector< RealType > & SphereCenter, RealType SphereRadius, FLinearIntersection & Result)
Intersect ray with sphere and return intersection info (# hits, ray parameters)
Returns
true if ray intersects sphere
Definition at line 232 of file IntersectionUtil.h.
References LineSphereIntersection().
Referenced by UE::Geometry::TDynamicVerticesOctree3< SourceType >::FindNearestHitVertex().
RaySphereTest()
template<typename RealType> bool IntersectionUtil::RaySphereTest (const TVector< RealType > & RayOrigin, const TVector< RealType > & RayDirection, const TVector< RealType > & SphereCenter, RealType SphereRadius)
Returns
true if ray intersects sphere
Definition at line 194 of file IntersectionUtil.h.
References UE::Math::TVector< T >::Dot(), and UE::Math::TVector< T >::SquaredLength().
RayTriangleTest()
template<typename RealType> bool IntersectionUtil::RayTriangleTest (const TVector< RealType > & RayOrigin, const TVector< RealType > & RayDirection, const TVector< RealType > & V0, const TVector< RealType > & V1, const TVector< RealType > & V2)
Definition at line 38 of file IntersectionUtil.h.
References UE::Math::TVector< T >::Cross(), and UE::Math::TVector< T >::Dot().
Referenced by UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::TestAnyHitTriangle().