Unreal Engine 5.6 C++ API: PropertyCustomizationHelpers Namespace Reference
PropertyCustomizationHelpers Namespace Reference
Functions
PROPERTYEDITOR_API void AddCallInEditorFunctionCallWidgetsForClass (IDetailGroup &RootGroup, const UClass *Class, const FPropertyFunctionCallDelegates &InArgs)
PROPERTYEDITOR_API void AddCallInEditorFunctionCallWidgetsForClass (IDetailLayoutBuilder &DetailBuilder, const UClass *Class, const FPropertyFunctionCallDelegates &InArgs)
PROPERTYEDITOR_API void AddFunctionCallWidgets (IDetailGroup &RootGroup, const TArrayView< UFunction * > &InCallInEditorFunctions, const FPropertyFunctionCallDelegates &InArgs)
PROPERTYEDITOR_API void AddFunctionCallWidgets (IDetailLayoutBuilder &DetailBuilder, const TArrayView< UFunction * > &InCallInEditorFunctions, const FPropertyFunctionCallDelegates &InArgs)
PROPERTYEDITOR_API void CreateNewInstanceOfEditInlineObjectClass (TSharedRef< IPropertyHandle > PropertyHandle, UClass *Class, EPropertyValueSetFlags::Type Flags=EPropertyValueSetFlags::DefaultFlags)
PROPERTYEDITOR_API void GetCallInEditorFunctionsForClass (const UClass *InClass, const TFunctionRef< bool(const UFunction *)> &InFunctionFilter, TArray< UFunction * > &OutCallInEditorFunctions, EFieldIterationFlags InIterationFlags=EFieldIterationFlags::IncludeSuper)
PROPERTYEDITOR_API void GetCallInEditorFunctionsForClass (const UClass *InClass, TArray< UFunction * > &OutCallInEditorFunctions, EFieldIterationFlags InIterationFlags=EFieldIterationFlags::IncludeSuper)
PROPERTYEDITOR_API TArray< const UClass * > GetClassesFromMetadataString (const FString &MetadataString)
Parse and load the given metadata string into a list of allowed classes.
PROPERTYEDITOR_API FBoolProperty * GetEditConditionProperty (const FProperty *InProperty, bool &bNegate)
PROPERTYEDITOR_API TArray< UFactory * > GetNewAssetFactoriesForClasses (const TArray< const UClass * > &Classes)
Returns a list of factories which can be used to create new assets, based on the supplied class.
PROPERTYEDITOR_API TArray< UFactory * > GetNewAssetFactoriesForClasses (const TArray< const UClass * > &Classes, const TArray< const UClass * > &DisallowedClasses)
Returns a list of factories which can be used to create new assets, based on the supplied classes and respecting the disallowed set.
PROPERTYEDITOR_API TArray< const UScriptStruct * > GetStructsFromMetadataString (const FString &MetadataString)
Parse and load the given metadata string into a list of allowed structs.
PROPERTYEDITOR_API TSharedRef< SWidget > MakeActorPickerAnchorButton (FOnGetActorFilters OnGetActorFilters, FOnActorSelected OnActorSelectedFromPicker)
PROPERTYEDITOR_API TSharedRef< SWidget > MakeActorPickerWithMenu (AActor *const InitialActor, const bool AllowClear, const bool AllowPickingLevelInstanceContent, FOnShouldFilterActor ActorFilter, FOnActorSelected OnSet, FSimpleDelegate OnClose, FSimpleDelegate OnUseSelected, bool bDisplayUseSelected=true, bool bShowTransient=false)
PROPERTYEDITOR_API TSharedRef< SWidget > MakeActorPickerWithMenu (AActor *const InitialActor, const bool AllowClear, FOnShouldFilterActor ActorFilter, FOnActorSelected OnSet, FSimpleDelegate OnClose, FSimpleDelegate OnUseSelected)
PROPERTYEDITOR_API TSharedRef< SWidget > MakeAddButton (FSimpleDelegate OnAddClicked, TAttribute< FText > OptionalToolTipText=FText(), TAttribute< bool > IsEnabled=true)
PROPERTYEDITOR_API TSharedRef< SWidget > MakeAssetPickerAnchorButton (FOnGetAllowedClasses OnGetAllowedClasses, FOnAssetSelected OnAssetSelectedFromPicker, const TSharedPtr< IPropertyHandle > &PropertyHandle=TSharedPtr< IPropertyHandle >())
PROPERTYEDITOR_API TSharedRef< SWidget > MakeAssetPickerWithMenu (const FAssetData &InitialObject, const bool AllowClear, const bool AllowCopyPaste, const TArray< const UClass * > &AllowedClasses, const TArray< const UClass * > &DisallowedClasses, const TArray< UFactory * > &NewAssetFactories, FOnShouldFilterAsset OnShouldFilterAsset, FOnAssetSelected OnSet, FSimpleDelegate OnClose, const TSharedPtr< IPropertyHandle > &PropertyHandle=TSharedPtr< IPropertyHandle >(), const TArray< FAssetData > &OwnerAssetArray=TArray< FAssetData >())
PROPERTYEDITOR_API TSharedRef< SWidget > MakeAssetPickerWithMenu (const FAssetData &InitialObject, const bool AllowClear, const bool AllowCopyPaste, const TArray< const UClass * > &AllowedClasses, const TArray< UFactory * > &NewAssetFactories, FOnShouldFilterAsset OnShouldFilterAsset, FOnAssetSelected OnSet, FSimpleDelegate OnClose, const TSharedPtr< IPropertyHandle > &PropertyHandle=TSharedPtr< IPropertyHandle >(), const TArray< FAssetData > &OwnerAssetArray=TArray< FAssetData >())
PROPERTYEDITOR_API TSharedRef< SWidget > MakeAssetPickerWithMenu (const FAssetData &InitialObject, const bool AllowClear, const TArray< const UClass * > &AllowedClasses, const TArray< const UClass * > &DisallowedClasses, const TArray< UFactory * > &NewAssetFactories, FOnShouldFilterAsset OnShouldFilterAsset, FOnAssetSelected OnSet, FSimpleDelegate OnClose, const TSharedPtr< IPropertyHandle > &PropertyHandle=TSharedPtr< IPropertyHandle >(), const TArray< FAssetData > &OwnerAssetArray=TArray< FAssetData >())
PROPERTYEDITOR_API TSharedRef< SWidget > MakeAssetPickerWithMenu (const FAssetData &InitialObject, const bool AllowClear, const TArray< const UClass * > &AllowedClasses, const TArray< UFactory * > &NewAssetFactories, FOnShouldFilterAsset OnShouldFilterAsset, FOnAssetSelected OnSet, FSimpleDelegate OnClose, const TSharedPtr< IPropertyHandle > &PropertyHandle=TSharedPtr< IPropertyHandle >(), const TArray< FAssetData > &OwnerAssetArray=TArray< FAssetData >())
PROPERTYEDITOR_API TSharedRef< SWidget > MakeBrowseButton (FSimpleDelegate OnFindClicked, TAttribute< FText > OptionalToolTipText=FText(), TAttribute< bool > IsEnabled=true, const bool IsActor=false, const TAttribute< const FSlateBrush * > &InIconOverride=TAttribute< const FSlateBrush * >())
PROPERTYEDITOR_API TSharedRef< SWidget > MakeClearButton (FSimpleDelegate OnClearClicked, TAttribute< FText > OptionalToolTipText=FText(), TAttribute< bool > IsEnabled=true)
PROPERTYEDITOR_API TSharedRef< SWidget > MakeClearOptionalButton (FSimpleDelegate OnClearOptional, TAttribute< FText > OptionalToolTipText=FText(), TAttribute< bool > IsEnabled=true)
PROPERTYEDITOR_API TSharedRef< SWidget > MakeComponentPickerWithMenu (UActorComponent *const InitialComponent, const bool AllowClear, FOnShouldFilterActor ActorFilter, FOnShouldFilterComponent ComponentFilter, FOnComponentSelected OnSet, FSimpleDelegate OnClose)
PROPERTYEDITOR_API TSharedRef< SWidget > MakeCustomButton (const FSlateBrush *IconBrush, FSimpleDelegate OnClicked, TAttribute< FText > ToolTipText=FText(), TAttribute< bool > IsEnabled=true, TAttribute< EVisibility > IsVisible=EVisibility::Visible)
PROPERTYEDITOR_API TSharedRef< SWidget > MakeDeleteButton (FSimpleDelegate OnDeleteClicked, TAttribute< FText > OptionalToolTipText=FText(), TAttribute< bool > IsEnabled=true)
PROPERTYEDITOR_API TSharedRef< SWidget > MakeDocumentationButton (const TSharedRef< FPropertyEditor > &InPropertyEditor)
PROPERTYEDITOR_API TSharedRef< SWidget > MakeEditButton (FSimpleDelegate OnEditClicked, TAttribute< FText > OptionalToolTipText=FText(), TAttribute< bool > IsEnabled=true)
PROPERTYEDITOR_API TSharedRef< SWidget > MakeEditConfigHierarchyButton (FSimpleDelegate OnEditConfigClicked, TAttribute< FText > OptionalToolTipText=FText(), TAttribute< bool > IsEnabled=true)
PROPERTYEDITOR_API TSharedRef< SWidget > MakeEditInlineObjectClassPicker (TSharedRef< IPropertyHandle > PropertyHandle, FOnClassPicked OnClassPicked, TSharedPtr< IClassViewerFilter > AdditionalClassFilter=nullptr)
PROPERTYEDITOR_API TSharedRef< SWidget > MakeEmptyButton (FSimpleDelegate OnEmptyClicked, TAttribute< FText > OptionalToolTipText=FText(), TAttribute< bool > IsEnabled=true)
PROPERTYEDITOR_API TSharedRef< SWidget > MakeFunctionCallButton (const FPropertyFunctionCallArgs &InArgs)
PROPERTYEDITOR_API TSharedRef< SWidget > MakeInsertDeleteDuplicateButton (FExecuteAction OnInsertClicked, FExecuteAction OnDeleteClicked, FExecuteAction OnDuplicateClicked)
PROPERTYEDITOR_API void MakeInstancedPropertyCustomUI (TMap< FName, IDetailGroup * > &ExistingGroup, IDetailCategoryBuilder &BaseCategory, TSharedRef< IPropertyHandle > &BaseProperty, FOnInstancedPropertyIteration AddRowDelegate)
Loops through all of an instanced object property's child properties and call AddRowDelegate on properties that needs to be added to the UI to let us customize it.
PROPERTYEDITOR_API TSharedRef< SWidget > MakeInteractiveActorPicker (FOnGetAllowedClasses OnGetAllowedClasses, FOnShouldFilterActor OnShouldFilterActor, FOnActorSelected OnActorSelectedFromPicker)
PROPERTYEDITOR_API TSharedRef< SWidget > MakeNewBlueprintButton (FSimpleDelegate OnNewBlueprintClicked, TAttribute< FText > OptionalToolTipText=FText(), TAttribute< bool > IsEnabled=true)
PROPERTYEDITOR_API TSharedRef< SWidget > MakePickOptionalButton (FOnSetOptional OnSetOptional, FSimpleDelegate OnClearOptional, const TSharedRef< FPropertyNode > &PropertyNode, TAttribute< FText > OptionalToolTipText=FText(), TAttribute< bool > IsEnabled=true)
PROPERTYEDITOR_API TSharedRef< SWidget > MakePropertyComboBox (const FPropertyComboBoxArgs &InArgs)
Build a combo button that you bind to a Name/String/Enum property or display using general delegates, using an arguments structure.
PROPERTYEDITOR_API TSharedRef< SWidget > MakePropertyComboBox (const TSharedPtr< IPropertyHandle > &InPropertyHandle, FOnGetPropertyComboBoxStrings OnGetStrings=FOnGetPropertyComboBoxStrings(), FOnGetPropertyComboBoxValue OnGetValue=FOnGetPropertyComboBoxValue(), FOnPropertyComboBoxValueSelected OnValueSelected=FOnPropertyComboBoxValueSelected())
Build a combo button that you bind to a Name/String/Enum property or display using general delegates.
PROPERTYEDITOR_API TSharedRef< SWidget > MakeRemoveButton (FSimpleDelegate OnRemoveClicked, TAttribute< FText > OptionalToolTipText=FText(), TAttribute< bool > IsEnabled=true)
PROPERTYEDITOR_API TSharedRef< SWidget > MakeResetButton (FSimpleDelegate OnResetClicked, TAttribute< FText > OptionalToolTipText=FText(), TAttribute< bool > IsEnabled=true)
PROPERTYEDITOR_API TSharedRef< SWidget > MakeSaveButton (FSimpleDelegate OnSaveClicked, TAttribute< FText > OptionalToolTipText=FText(), TAttribute< bool > IsEnabled=true)
PROPERTYEDITOR_API TSharedRef< SWidget > MakeSceneDepthPicker (FOnSceneDepthLocationSelected OnSceneDepthLocationSelected)
PROPERTYEDITOR_API TSharedRef< SWidget > MakeSetOptionalButton (FOnSetOptional OnSetOptional, TAttribute< FText > OptionalToolTipText=FText(), TAttribute< bool > IsEnabled=true)
PROPERTYEDITOR_API TSharedRef< SWidget > MakeUseSelectedButton (FSimpleDelegate OnUseSelectedClicked, TAttribute< FText > OptionalToolTipText=FText(), TAttribute< bool > IsEnabled=true, const bool IsActor=false)
PROPERTYEDITOR_API TSharedRef< SWidget > MakeVisibilityButton (FOnClicked OnVisibilityClicked, TAttribute< FText > OptionalToolTipText=FText(), TAttribute< bool > VisibilityDelegate=true)
Function Documentation
AddCallInEditorFunctionCallWidgetsForClass() [1/2]
PROPERTYEDITOR_API void PropertyCustomizationHelpers::AddCallInEditorFunctionCallWidgetsForClass (IDetailGroup & RootGroup, const UClass * Class, const FPropertyFunctionCallDelegates & InArgs)
References Class.
AddCallInEditorFunctionCallWidgetsForClass() [2/2]
PROPERTYEDITOR_API void PropertyCustomizationHelpers::AddCallInEditorFunctionCallWidgetsForClass (IDetailLayoutBuilder & DetailBuilder, const UClass * Class, const FPropertyFunctionCallDelegates & InArgs)
References Class.
AddFunctionCallWidgets() [1/2]
PROPERTYEDITOR_API void PropertyCustomizationHelpers::AddFunctionCallWidgets (IDetailGroup & RootGroup, const TArrayView< UFunction * > & InCallInEditorFunctions, const FPropertyFunctionCallDelegates & InArgs)
AddFunctionCallWidgets() [2/2]
PROPERTYEDITOR_API void PropertyCustomizationHelpers::AddFunctionCallWidgets (IDetailLayoutBuilder & DetailBuilder, const TArrayView< UFunction * > & InCallInEditorFunctions, const FPropertyFunctionCallDelegates & InArgs)
CreateNewInstanceOfEditInlineObjectClass()
PROPERTYEDITOR_API void PropertyCustomizationHelpers::CreateNewInstanceOfEditInlineObjectClass (TSharedRef< IPropertyHandle > PropertyHandle, UClass * Class, EPropertyValueSetFlags::Type Flags = EPropertyValueSetFlags::DefaultFlags)
References Class, EPropertyValueSetFlags::DefaultFlags, and Flags.
GetCallInEditorFunctionsForClass() [1/2]
PROPERTYEDITOR_API void PropertyCustomizationHelpers::GetCallInEditorFunctionsForClass (const UClass * InClass, const TFunctionRef< bool(const UFunction *)> & InFunctionFilter, TArray< UFunction * > & OutCallInEditorFunctions, EFieldIterationFlags InIterationFlags = EFieldIterationFlags::IncludeSuper)
Parameters
InFunctionFilter A filter to select candidate UFunctions
References IncludeSuper.
GetCallInEditorFunctionsForClass() [2/2]
PROPERTYEDITOR_API void PropertyCustomizationHelpers::GetCallInEditorFunctionsForClass (const UClass * InClass, TArray< UFunction * > & OutCallInEditorFunctions, EFieldIterationFlags InIterationFlags = EFieldIterationFlags::IncludeSuper)
References IncludeSuper.
GetClassesFromMetadataString()
PROPERTYEDITOR_API TArray< const UClass * > PropertyCustomizationHelpers::GetClassesFromMetadataString (const FString & MetadataString)
Parse and load the given metadata string into a list of allowed classes.
The metadata string is likely from something like AllowedClasses or DisallowedClasses.
GetEditConditionProperty()
PROPERTYEDITOR_API FBoolProperty * PropertyCustomizationHelpers::GetEditConditionProperty (const FProperty * InProperty, bool & bNegate)
Returns
the FBoolProperty edit condition property if one exists.
GetNewAssetFactoriesForClasses() [1/2]
PROPERTYEDITOR_API TArray< UFactory * > PropertyCustomizationHelpers::GetNewAssetFactoriesForClasses (const TArray< const UClass * > & Classes)
Returns a list of factories which can be used to create new assets, based on the supplied class.
GetNewAssetFactoriesForClasses() [2/2]
PROPERTYEDITOR_API TArray< UFactory * > PropertyCustomizationHelpers::GetNewAssetFactoriesForClasses (const TArray< const UClass * > & Classes, const TArray< const UClass * > & DisallowedClasses)
Returns a list of factories which can be used to create new assets, based on the supplied classes and respecting the disallowed set.
GetStructsFromMetadataString()
PROPERTYEDITOR_API TArray< const UScriptStruct * > PropertyCustomizationHelpers::GetStructsFromMetadataString (const FString & MetadataString)
Parse and load the given metadata string into a list of allowed structs.
The metadata string is likely from something like AllowedClasses or DisallowedClasses.
MakeActorPickerAnchorButton()
PROPERTYEDITOR_API TSharedRef< SWidget > PropertyCustomizationHelpers::MakeActorPickerAnchorButton (FOnGetActorFilters OnGetActorFilters, FOnActorSelected OnActorSelectedFromPicker)
MakeActorPickerWithMenu() [1/2]
PROPERTYEDITOR_API TSharedRef< SWidget > PropertyCustomizationHelpers::MakeActorPickerWithMenu (AActor *const InitialActor, const bool AllowClear, const bool AllowPickingLevelInstanceContent, FOnShouldFilterActor ActorFilter, FOnActorSelected OnSet, FSimpleDelegate OnClose, FSimpleDelegate OnUseSelected, bool bDisplayUseSelected = true, bool bShowTransient = false)
MakeActorPickerWithMenu() [2/2]
PROPERTYEDITOR_API TSharedRef< SWidget > PropertyCustomizationHelpers::MakeActorPickerWithMenu (AActor *const InitialActor, const bool AllowClear, FOnShouldFilterActor ActorFilter, FOnActorSelected OnSet, FSimpleDelegate OnClose, FSimpleDelegate OnUseSelected)
MakeAddButton()
PROPERTYEDITOR_API TSharedRef< SWidget > PropertyCustomizationHelpers::MakeAddButton (FSimpleDelegate OnAddClicked, TAttribute< FText > OptionalToolTipText = FText(), TAttribute< bool > IsEnabled = true)
MakeAssetPickerAnchorButton()
PROPERTYEDITOR_API TSharedRef< SWidget > PropertyCustomizationHelpers::MakeAssetPickerAnchorButton (FOnGetAllowedClasses OnGetAllowedClasses, FOnAssetSelected OnAssetSelectedFromPicker, const TSharedPtr< IPropertyHandle > & PropertyHandle = TSharedPtr< IPropertyHandle >())
MakeAssetPickerWithMenu() [1/4]
PROPERTYEDITOR_API TSharedRef< SWidget > PropertyCustomizationHelpers::MakeAssetPickerWithMenu (const FAssetData & InitialObject, const bool AllowClear, const bool AllowCopyPaste, const TArray< const UClass * > & AllowedClasses, const TArray< const UClass * > & DisallowedClasses, const TArray< UFactory * > & NewAssetFactories, FOnShouldFilterAsset OnShouldFilterAsset, FOnAssetSelected OnSet, FSimpleDelegate OnClose, const TSharedPtr< IPropertyHandle > & PropertyHandle = TSharedPtr< IPropertyHandle >(), const TArray< FAssetData > & OwnerAssetArray = TArray< FAssetData >())
MakeAssetPickerWithMenu() [2/4]
PROPERTYEDITOR_API TSharedRef< SWidget > PropertyCustomizationHelpers::MakeAssetPickerWithMenu (const FAssetData & InitialObject, const bool AllowClear, const bool AllowCopyPaste, const TArray< const UClass * > & AllowedClasses, const TArray< UFactory * > & NewAssetFactories, FOnShouldFilterAsset OnShouldFilterAsset, FOnAssetSelected OnSet, FSimpleDelegate OnClose, const TSharedPtr< IPropertyHandle > & PropertyHandle = TSharedPtr< IPropertyHandle >(), const TArray< FAssetData > & OwnerAssetArray = TArray< FAssetData >())
MakeAssetPickerWithMenu() [3/4]
PROPERTYEDITOR_API TSharedRef< SWidget > PropertyCustomizationHelpers::MakeAssetPickerWithMenu (const FAssetData & InitialObject, const bool AllowClear, const TArray< const UClass * > & AllowedClasses, const TArray< const UClass * > & DisallowedClasses, const TArray< UFactory * > & NewAssetFactories, FOnShouldFilterAsset OnShouldFilterAsset, FOnAssetSelected OnSet, FSimpleDelegate OnClose, const TSharedPtr< IPropertyHandle > & PropertyHandle = TSharedPtr< IPropertyHandle >(), const TArray< FAssetData > & OwnerAssetArray = TArray< FAssetData >())
MakeAssetPickerWithMenu() [4/4]
PROPERTYEDITOR_API TSharedRef< SWidget > PropertyCustomizationHelpers::MakeAssetPickerWithMenu (const FAssetData & InitialObject, const bool AllowClear, const TArray< const UClass * > & AllowedClasses, const TArray< UFactory * > & NewAssetFactories, FOnShouldFilterAsset OnShouldFilterAsset, FOnAssetSelected OnSet, FSimpleDelegate OnClose, const TSharedPtr< IPropertyHandle > & PropertyHandle = TSharedPtr< IPropertyHandle >(), const TArray< FAssetData > & OwnerAssetArray = TArray< FAssetData >())
MakeBrowseButton()
PROPERTYEDITOR_API TSharedRef< SWidget > PropertyCustomizationHelpers::MakeBrowseButton (FSimpleDelegate OnFindClicked, TAttribute< FText > OptionalToolTipText = FText(), TAttribute< bool > IsEnabled = true, const bool IsActor = false, const TAttribute< const FSlateBrush * > & InIconOverride = TAttribute< const FSlateBrush * >())
References IsActor.
Referenced by FGameModeInfoCustomizer::CustomizeGameModeDefaultClass(), and FGameModeInfoCustomizer::CustomizeGameModeSetting().
MakeClearButton()
PROPERTYEDITOR_API TSharedRef< SWidget > PropertyCustomizationHelpers::MakeClearButton (FSimpleDelegate OnClearClicked, TAttribute< FText > OptionalToolTipText = FText(), TAttribute< bool > IsEnabled = true)
MakeClearOptionalButton()
PROPERTYEDITOR_API TSharedRef< SWidget > PropertyCustomizationHelpers::MakeClearOptionalButton (FSimpleDelegate OnClearOptional, TAttribute< FText > OptionalToolTipText = FText(), TAttribute< bool > IsEnabled = true)
MakeComponentPickerWithMenu()
PROPERTYEDITOR_API TSharedRef< SWidget > PropertyCustomizationHelpers::MakeComponentPickerWithMenu (UActorComponent *const InitialComponent, const bool AllowClear, FOnShouldFilterActor ActorFilter, FOnShouldFilterComponent ComponentFilter, FOnComponentSelected OnSet, FSimpleDelegate OnClose)
MakeCustomButton()
PROPERTYEDITOR_API TSharedRef< SWidget > PropertyCustomizationHelpers::MakeCustomButton (const FSlateBrush * IconBrush, FSimpleDelegate OnClicked, TAttribute< FText > ToolTipText = FText(), TAttribute< bool > IsEnabled = true, TAttribute< EVisibility > IsVisible = EVisibility::Visible)
References EVisibility::Visible.
MakeDeleteButton()
PROPERTYEDITOR_API TSharedRef< SWidget > PropertyCustomizationHelpers::MakeDeleteButton (FSimpleDelegate OnDeleteClicked, TAttribute< FText > OptionalToolTipText = FText(), TAttribute< bool > IsEnabled = true)
MakeDocumentationButton()
PROPERTYEDITOR_API TSharedRef< SWidget > PropertyCustomizationHelpers::MakeDocumentationButton (const TSharedRef< FPropertyEditor > & InPropertyEditor)
MakeEditButton()
PROPERTYEDITOR_API TSharedRef< SWidget > PropertyCustomizationHelpers::MakeEditButton (FSimpleDelegate OnEditClicked, TAttribute< FText > OptionalToolTipText = FText(), TAttribute< bool > IsEnabled = true)
MakeEditConfigHierarchyButton()
PROPERTYEDITOR_API TSharedRef< SWidget > PropertyCustomizationHelpers::MakeEditConfigHierarchyButton (FSimpleDelegate OnEditConfigClicked, TAttribute< FText > OptionalToolTipText = FText(), TAttribute< bool > IsEnabled = true)
MakeEditInlineObjectClassPicker()
PROPERTYEDITOR_API TSharedRef< SWidget > PropertyCustomizationHelpers::MakeEditInlineObjectClassPicker (TSharedRef< IPropertyHandle > PropertyHandle, FOnClassPicked OnClassPicked, TSharedPtr< IClassViewerFilter > AdditionalClassFilter = nullptr)
MakeEmptyButton()
PROPERTYEDITOR_API TSharedRef< SWidget > PropertyCustomizationHelpers::MakeEmptyButton (FSimpleDelegate OnEmptyClicked, TAttribute< FText > OptionalToolTipText = FText(), TAttribute< bool > IsEnabled = true)
MakeFunctionCallButton()
PROPERTYEDITOR_API TSharedRef< SWidget > PropertyCustomizationHelpers::MakeFunctionCallButton (const FPropertyFunctionCallArgs & InArgs)
MakeInsertDeleteDuplicateButton()
PROPERTYEDITOR_API TSharedRef< SWidget > PropertyCustomizationHelpers::MakeInsertDeleteDuplicateButton (FExecuteAction OnInsertClicked, FExecuteAction OnDeleteClicked, FExecuteAction OnDuplicateClicked)
MakeInstancedPropertyCustomUI()
PROPERTYEDITOR_API void PropertyCustomizationHelpers::MakeInstancedPropertyCustomUI (TMap< FName, IDetailGroup * > & ExistingGroup, IDetailCategoryBuilder & BaseCategory, TSharedRef< IPropertyHandle > & BaseProperty, FOnInstancedPropertyIteration AddRowDelegate)
Loops through all of an instanced object property's child properties and call AddRowDelegate on properties that needs to be added to the UI to let us customize it.
Parameters
ExistingGroup A map used internally to determine the existing group categories. Should be empty.
BaseCategory The category that will be used as the root of the instanced object properties.
BaseProperty The instanced class property.
AddRowDelegate The delegate that will be called on each child property.
MakeInteractiveActorPicker()
PROPERTYEDITOR_API TSharedRef< SWidget > PropertyCustomizationHelpers::MakeInteractiveActorPicker (FOnGetAllowedClasses OnGetAllowedClasses, FOnShouldFilterActor OnShouldFilterActor, FOnActorSelected OnActorSelectedFromPicker)
MakeNewBlueprintButton()
PROPERTYEDITOR_API TSharedRef< SWidget > PropertyCustomizationHelpers::MakeNewBlueprintButton (FSimpleDelegate OnNewBlueprintClicked, TAttribute< FText > OptionalToolTipText = FText(), TAttribute< bool > IsEnabled = true)
Referenced by FGameModeInfoCustomizer::CustomizeGameModeDefaultClass(), and FGameModeInfoCustomizer::CustomizeGameModeSetting().
MakePickOptionalButton()
PROPERTYEDITOR_API TSharedRef< SWidget > PropertyCustomizationHelpers::MakePickOptionalButton (FOnSetOptional OnSetOptional, FSimpleDelegate OnClearOptional, const TSharedRef< FPropertyNode > & PropertyNode, TAttribute< FText > OptionalToolTipText = FText(), TAttribute< bool > IsEnabled = true)
MakePropertyComboBox() [1/2]
PROPERTYEDITOR_API TSharedRef< SWidget > PropertyCustomizationHelpers::MakePropertyComboBox (const FPropertyComboBoxArgs & InArgs)
Build a combo button that you bind to a Name/String/Enum property or display using general delegates, using an arguments structure.
Parameters
InArgs Options used to create combo box
MakePropertyComboBox() [2/2]
PROPERTYEDITOR_API TSharedRef< SWidget > PropertyCustomizationHelpers::MakePropertyComboBox (const TSharedPtr< IPropertyHandle > & InPropertyHandle, FOnGetPropertyComboBoxStrings OnGetStrings = FOnGetPropertyComboBoxStrings(), FOnGetPropertyComboBoxValue OnGetValue = FOnGetPropertyComboBoxValue(), FOnPropertyComboBoxValueSelected OnValueSelected = FOnPropertyComboBoxValueSelected())
Build a combo button that you bind to a Name/String/Enum property or display using general delegates.
Parameters
InPropertyHandle If set, will bind to a specific property. If this is null, all 3 delegates must be set
OnGetStrings Delegate that will generate the list of possible strings. If not set will generate using property handle
OnGetValue Delegate that is called to get the current string value to display. If not set will generate using property handle
OnValueSelected Delegate called when a string is selected. If not set will set the property handle
MakeRemoveButton()
PROPERTYEDITOR_API TSharedRef< SWidget > PropertyCustomizationHelpers::MakeRemoveButton (FSimpleDelegate OnRemoveClicked, TAttribute< FText > OptionalToolTipText = FText(), TAttribute< bool > IsEnabled = true)
MakeResetButton()
PROPERTYEDITOR_API TSharedRef< SWidget > PropertyCustomizationHelpers::MakeResetButton (FSimpleDelegate OnResetClicked, TAttribute< FText > OptionalToolTipText = FText(), TAttribute< bool > IsEnabled = true)
MakeSaveButton()
PROPERTYEDITOR_API TSharedRef< SWidget > PropertyCustomizationHelpers::MakeSaveButton (FSimpleDelegate OnSaveClicked, TAttribute< FText > OptionalToolTipText = FText(), TAttribute< bool > IsEnabled = true)
MakeSceneDepthPicker()
PROPERTYEDITOR_API TSharedRef< SWidget > PropertyCustomizationHelpers::MakeSceneDepthPicker (FOnSceneDepthLocationSelected OnSceneDepthLocationSelected)
MakeSetOptionalButton()
PROPERTYEDITOR_API TSharedRef< SWidget > PropertyCustomizationHelpers::MakeSetOptionalButton (FOnSetOptional OnSetOptional, TAttribute< FText > OptionalToolTipText = FText(), TAttribute< bool > IsEnabled = true)
MakeUseSelectedButton()
PROPERTYEDITOR_API TSharedRef< SWidget > PropertyCustomizationHelpers::MakeUseSelectedButton (FSimpleDelegate OnUseSelectedClicked, TAttribute< FText > OptionalToolTipText = FText(), TAttribute< bool > IsEnabled = true, const bool IsActor = false)
References IsActor.
Referenced by FGameModeInfoCustomizer::CustomizeGameModeDefaultClass(), and FGameModeInfoCustomizer::CustomizeGameModeSetting().
MakeVisibilityButton()
PROPERTYEDITOR_API TSharedRef< SWidget > PropertyCustomizationHelpers::MakeVisibilityButton (FOnClicked OnVisibilityClicked, TAttribute< FText > OptionalToolTipText = FText(), TAttribute< bool > VisibilityDelegate = true)