Unreal Engine 5.6 C++ API: FComputeShaderUtils Namespace Reference
FComputeShaderUtils Namespace Reference
All utils for compute shaders.
Namespaces
namespace Private
Functions
RENDERCORE_API FRDGBufferRef AddIndirectArgsSetupCsPass1D (FRDGBuilder &GraphBuilder, ERHIFeatureLevel::Type FeatureLevel, FRDGBuffer *InputCountBuffer, const TCHAR *OutputBufferName, uint32 Divisor, uint32 InputCountOffset=0U, uint32 Multiplier=1U)
Create and set up an 1D indirect dispatch argument from some GPU-side integer in a buffer (InputCountBuffer).
template<typename TShaderClass>
FRDGPassRef AddPass (FRDGBuilder &GraphBuilder, FRDGEventName &&PassName, const TShaderRef< TShaderClass > &ComputeShader, typename TShaderClass::FParameters *Parameters, FIntVector GroupCount)
template<typename TShaderClass>
FRDGPassRef AddPass (FRDGBuilder &GraphBuilder, FRDGEventName &&PassName, const TShaderRef< TShaderClass > &ComputeShader, typename TShaderClass::FParameters *Parameters, FRDGBufferRef IndirectArgsBuffer, uint32 IndirectArgsOffset, FRDGDispatchLateParamCallback &&DispatchLateParamCallback=FRDGDispatchLateParamCallback())
template<typename TShaderClass>
FRDGPassRef AddPass (FRDGBuilder &GraphBuilder, FRDGEventName &&PassName, const TShaderRef< TShaderClass > &ComputeShader, typename TShaderClass::FParameters *Parameters, FRDGDispatchGroupCountCallback &&GroupCountCallback)
template<typename TShaderClass>
FRDGPassRef AddPass (FRDGBuilder &GraphBuilder, FRDGEventName &&PassName, ERDGPassFlags PassFlags, const TShaderRef< TShaderClass > &ComputeShader, const FShaderParametersMetadata *ParametersMetadata, typename TShaderClass::FParameters *Parameters, FIntVector GroupCount)
Dispatch a compute shader to render graph builder with its parameters.
template<typename TShaderClass>
FRDGPassRef AddPass (FRDGBuilder &GraphBuilder, FRDGEventName &&PassName, ERDGPassFlags PassFlags, const TShaderRef< TShaderClass > &ComputeShader, const FShaderParametersMetadata *ParametersMetadata, typename TShaderClass::FParameters *Parameters, FRDGDispatchGroupCountCallback &&GroupCountCallback)
Dispatch a compute shader to render graph builder with its parameters.
template<typename TShaderClass>
FRDGPassRef AddPass (FRDGBuilder &GraphBuilder, FRDGEventName &&PassName, ERDGPassFlags PassFlags, const TShaderRef< TShaderClass > &ComputeShader, typename TShaderClass::FParameters *Parameters, FIntVector GroupCount)
template<typename TShaderClass>
FRDGPassRef AddPass (FRDGBuilder &GraphBuilder, FRDGEventName &&PassName, ERDGPassFlags PassFlags, const TShaderRef< TShaderClass > &ComputeShader, typename TShaderClass::FParameters *Parameters, FRDGBufferRef IndirectArgsBuffer, uint32 IndirectArgsOffset, FRDGDispatchLateParamCallback &&DispatchLateParamCallback=FRDGDispatchLateParamCallback())
Dispatch a compute shader to render graph builder with its parameters.
template<typename TShaderClass>
void Dispatch (FRHIComputeCommandList &RHICmdList, const TShaderRef< TShaderClass > &ComputeShader, const FShaderParametersMetadata *ParametersMetadata, const typename TShaderClass::FParameters &Parameters, FIntVector GroupCount)
Dispatch a compute shader to rhi command list with its parameters.
template<typename TShaderClass>
void Dispatch (FRHIComputeCommandList &RHICmdList, const TShaderRef< TShaderClass > &ComputeShader, const typename TShaderClass::FParameters &Parameters, FIntVector GroupCount)
template<typename TShaderClass>
void DispatchIndirect (FRHIComputeCommandList &RHICmdList, const TShaderRef< TShaderClass > &ComputeShader, const typename TShaderClass::FParameters &Parameters, FRDGBufferRef IndirectArgsBuffer, uint32 IndirectArgOffset)
Dispatch a compute shader to rhi command list with its parameters and indirect args.
template<typename TShaderClass>
void DispatchIndirect (FRHIComputeCommandList &RHICmdList, const TShaderRef< TShaderClass > &ComputeShader, const typename TShaderClass::FParameters &Parameters, FRHIBuffer *IndirectArgsBuffer, uint32 IndirectArgOffset)
Indirect dispatch a compute shader to rhi command list with its parameters.
FIntVector GetGroupCount (const FIntPoint &ThreadCount, const FIntPoint &GroupSize)
FIntVector GetGroupCount (const FIntPoint &ThreadCount, const int32 GroupSize)
FIntVector GetGroupCount (const FIntVector &ThreadCount, const FIntVector &GroupSize)
FIntVector GetGroupCount (const FIntVector &ThreadCount, const int32 GroupSize)
FIntVector GetGroupCount (const int32 ThreadCount, const int32 GroupSize)
Compute the number of groups to dispatch.
FIntVector GetGroupCountWrapped (const int32 TargetGroupCount)
Wrapping number of groups to Y and Z dimension if X group count overflows GRHIMaxDispatchThreadGroupsPerDimension.
FIntVector GetGroupCountWrapped (const int32 ThreadCount, const int32 GroupSize)
Compute the number of groups to dispatch and allow wrapping to Y and Z dimension if X group count overflows.
void ValidateGroupCount (const FIntVector &GroupCount)
void ValidateIndirectArgsBuffer (const FRDGBufferRef IndirectArgsBuffer, uint32 IndirectArgOffset)
void ValidateIndirectArgsBuffer (uint32 IndirectArgsBufferSize, uint32 IndirectArgOffset)
Variables
static constexpr int32 kGolden2DGroupSize = 8
Ideal size of group size 8x8 to occupy at least an entire wave on GCN, two warp on Nvidia.
static constexpr int32 WrappedGroupStride = 128
Constant stride used when wrapping too large 1D dispatches using GetGroupCountWrapped, selected as 128 appears to be the lowest common denominator for mobile (GLES 3.1).
Detailed Description
All utils for compute shaders.
Function Documentation
AddIndirectArgsSetupCsPass1D()
RENDERCORE_API FRDGBufferRef FComputeShaderUtils::AddIndirectArgsSetupCsPass1D (FRDGBuilder & GraphBuilder, ERHIFeatureLevel::Type FeatureLevel, FRDGBuffer * InputCountBuffer, const TCHAR * OutputBufferName, uint32 Divisor, uint32 InputCountOffset = 0U, uint32 Multiplier = 1U)
Create and set up an 1D indirect dispatch argument from some GPU-side integer in a buffer (InputCountBuffer).
Sets up a group count as (InputCountBuffer[InputCountOffset] * Multiplier + Divisor - 1U) / Divisor; Commonly use Divisor <=> number of threads per group.
References Multiplier.
AddPass() [1/7]
template<typename TShaderClass> FRDGPassRef FComputeShaderUtils::AddPass (FRDGBuilder & GraphBuilder, FRDGEventName && PassName, const TShaderRef< TShaderClass > & ComputeShader, typename TShaderClass::FParameters * Parameters, FIntVector GroupCount) inline
Definition at line 626 of file RenderGraphUtils.h.
References AddPass(), Compute, and Forward().
AddPass() [2/7]
template<typename TShaderClass> FRDGPassRef FComputeShaderUtils::AddPass (FRDGBuilder & GraphBuilder, FRDGEventName && PassName, const TShaderRef< TShaderClass > & ComputeShader, typename TShaderClass::FParameters * Parameters, FRDGBufferRef IndirectArgsBuffer, uint32 IndirectArgsOffset, FRDGDispatchLateParamCallback && DispatchLateParamCallback = FRDGDispatchLateParamCallback()) inline
Definition at line 686 of file RenderGraphUtils.h.
References AddPass(), Compute, Forward(), and MoveTemp().
AddPass() [3/7]
template<typename TShaderClass> FRDGPassRef FComputeShaderUtils::AddPass (FRDGBuilder & GraphBuilder, FRDGEventName && PassName, const TShaderRef< TShaderClass > & ComputeShader, typename TShaderClass::FParameters * Parameters, FRDGDispatchGroupCountCallback && GroupCountCallback) inline
Definition at line 638 of file RenderGraphUtils.h.
References AddPass(), Compute, Forward(), and MoveTemp().
AddPass() [4/7]
template<typename TShaderClass> FRDGPassRef FComputeShaderUtils::AddPass (FRDGBuilder & GraphBuilder, FRDGEventName && PassName, ERDGPassFlags PassFlags, const TShaderRef< TShaderClass > & ComputeShader, const FShaderParametersMetadata * ParametersMetadata, typename TShaderClass::FParameters * Parameters, FIntVector GroupCount) inline
Dispatch a compute shader to render graph builder with its parameters.
Definition at line 550 of file RenderGraphUtils.h.
References FRDGBuilder::AddPass(), AsyncCompute, checkf, ClearUnusedGraphResources(), Compute, Copy, Dispatch(), EnumHasAnyFlags(), Forward(), Raster, TEXT, and ValidateGroupCount().
Referenced by AddPass(), AddPass(), AddPass(), and AddPass().
AddPass() [5/7]
template<typename TShaderClass> FRDGPassRef FComputeShaderUtils::AddPass (FRDGBuilder & GraphBuilder, FRDGEventName && PassName, ERDGPassFlags PassFlags, const TShaderRef< TShaderClass > & ComputeShader, const FShaderParametersMetadata * ParametersMetadata, typename TShaderClass::FParameters * Parameters, FRDGDispatchGroupCountCallback && GroupCountCallback) inline
Dispatch a compute shader to render graph builder with its parameters.
GroupCount is supplied through a callback. This allows adding a dispatch with unknown GroupCount but the value must be ready before the pass is executed.
Definition at line 581 of file RenderGraphUtils.h.
References FRDGBuilder::AddPass(), AsyncCompute, checkf, ClearUnusedGraphResources(), Compute, Copy, Dispatch(), EnumHasAnyFlags(), Forward(), MoveTemp(), Raster, TEXT, ValidateGroupCount(), UE::Math::TIntVector3< InIntType >::X, UE::Math::TIntVector3< InIntType >::Y, and UE::Math::TIntVector3< InIntType >::Z.
AddPass() [6/7]
template<typename TShaderClass> FRDGPassRef FComputeShaderUtils::AddPass (FRDGBuilder & GraphBuilder, FRDGEventName && PassName, ERDGPassFlags PassFlags, const TShaderRef< TShaderClass > & ComputeShader, typename TShaderClass::FParameters * Parameters, FIntVector GroupCount) inline
Definition at line 613 of file RenderGraphUtils.h.
References AddPass(), and Forward().
AddPass() [7/7]
template<typename TShaderClass> FRDGPassRef FComputeShaderUtils::AddPass (FRDGBuilder & GraphBuilder, FRDGEventName && PassName, ERDGPassFlags PassFlags, const TShaderRef< TShaderClass > & ComputeShader, typename TShaderClass::FParameters * Parameters, FRDGBufferRef IndirectArgsBuffer, uint32 IndirectArgsOffset, FRDGDispatchLateParamCallback && DispatchLateParamCallback = FRDGDispatchLateParamCallback()) inline
Dispatch a compute shader to render graph builder with its parameters.
Definition at line 651 of file RenderGraphUtils.h.
References FRDGBuilder::AddPass(), AsyncCompute, checkf, ClearUnusedGraphResources(), Compute, FRDGBuffer::Desc, DispatchIndirect(), Forward(), FRDGBuffer::GetIndirectRHICallBuffer(), FRDGResource::MarkResourceAsUsed(), MoveTemp(), FRDGResource::Name, TEXT, FRDGBufferDesc::Usage, and ValidateIndirectArgsBuffer().
Dispatch() [1/2]
template<typename TShaderClass> void FComputeShaderUtils::Dispatch (FRHIComputeCommandList & RHICmdList, const TShaderRef< TShaderClass > & ComputeShader, const FShaderParametersMetadata * ParametersMetadata, const typename TShaderClass::FParameters & Parameters, FIntVector GroupCount) inline
Dispatch a compute shader to rhi command list with its parameters.
Definition at line 491 of file RenderGraphUtils.h.
References FComputeShaderUtils::Private::AfterDispatch(), FComputeShaderUtils::Private::PrepareDispatch(), ValidateGroupCount(), UE::Math::TIntVector3< InIntType >::X, UE::Math::TIntVector3< InIntType >::Y, and UE::Math::TIntVector3< InIntType >::Z.
Referenced by AddPass(), AddPass(), and Dispatch().
Dispatch() [2/2]
template<typename TShaderClass> void FComputeShaderUtils::Dispatch (FRHIComputeCommandList & RHICmdList, const TShaderRef< TShaderClass > & ComputeShader, const typename TShaderClass::FParameters & Parameters, FIntVector GroupCount) inline
Definition at line 506 of file RenderGraphUtils.h.
References Dispatch().
DispatchIndirect() [1/2]
template<typename TShaderClass> void FComputeShaderUtils::DispatchIndirect (FRHIComputeCommandList & RHICmdList, const TShaderRef< TShaderClass > & ComputeShader, const typename TShaderClass::FParameters & Parameters, FRDGBufferRef IndirectArgsBuffer, uint32 IndirectArgOffset) inline
Dispatch a compute shader to rhi command list with its parameters and indirect args.
Definition at line 534 of file RenderGraphUtils.h.
References FComputeShaderUtils::Private::AfterDispatch(), FRDGBuffer::GetIndirectRHICallBuffer(), FComputeShaderUtils::Private::PrepareDispatch(), and ValidateIndirectArgsBuffer().
DispatchIndirect() [2/2]
template<typename TShaderClass> void FComputeShaderUtils::DispatchIndirect (FRHIComputeCommandList & RHICmdList, const TShaderRef< TShaderClass > & ComputeShader, const typename TShaderClass::FParameters & Parameters, FRHIBuffer * IndirectArgsBuffer, uint32 IndirectArgOffset) inline
Indirect dispatch a compute shader to rhi command list with its parameters.
Definition at line 518 of file RenderGraphUtils.h.
References FComputeShaderUtils::Private::AfterDispatch(), FComputeShaderUtils::Private::PrepareDispatch(), and ValidateIndirectArgsBuffer().
Referenced by AddPass().
GetGroupCount() [1/5]
FIntVector FComputeShaderUtils::GetGroupCount (const FIntPoint & ThreadCount, const FIntPoint & GroupSize) inline
Definition at line 356 of file RenderGraphUtils.h.
References FMath::DivideAndRoundUp(), UE::Math::TIntPoint< InIntType >::X, and UE::Math::TIntPoint< InIntType >::Y.
GetGroupCount() [2/5]
FIntVector FComputeShaderUtils::GetGroupCount (const FIntPoint & ThreadCount, const int32 GroupSize) inline
Definition at line 363 of file RenderGraphUtils.h.
References FMath::DivideAndRoundUp(), UE::Math::TIntPoint< InIntType >::X, and UE::Math::TIntPoint< InIntType >::Y.
GetGroupCount() [3/5]
FIntVector FComputeShaderUtils::GetGroupCount (const FIntVector & ThreadCount, const FIntVector & GroupSize) inline
Definition at line 370 of file RenderGraphUtils.h.
References FMath::DivideAndRoundUp(), UE::Math::TIntVector3< InIntType >::X, UE::Math::TIntVector3< InIntType >::Y, and UE::Math::TIntVector3< InIntType >::Z.
GetGroupCount() [4/5]
FIntVector FComputeShaderUtils::GetGroupCount (const FIntVector & ThreadCount, const int32 GroupSize) inline
Definition at line 377 of file RenderGraphUtils.h.
References FMath::DivideAndRoundUp(), UE::Math::TIntVector3< InIntType >::X, UE::Math::TIntVector3< InIntType >::Y, and UE::Math::TIntVector3< InIntType >::Z.
GetGroupCount() [5/5]
FIntVector FComputeShaderUtils::GetGroupCount (const int32 ThreadCount, const int32 GroupSize) inline
Compute the number of groups to dispatch.
Definition at line 349 of file RenderGraphUtils.h.
References FMath::DivideAndRoundUp().
GetGroupCountWrapped() [1/2]
FIntVector FComputeShaderUtils::GetGroupCountWrapped (const int32 TargetGroupCount) inline
Wrapping number of groups to Y and Z dimension if X group count overflows GRHIMaxDispatchThreadGroupsPerDimension.
Calculate the linear group index as (or use GetUnWrappedDispatchGroupId(GroupId) in ComputeShaderUtils.ush): uint LinearGroupId = GroupId.X + (GroupId.Z * WrappedGroupStride + GroupId.Y) * WrappedGroupStride; Note that you must use an early out because LinearGroupId may be larger than the ideal due to wrapping.
Definition at line 398 of file RenderGraphUtils.h.
References check, FMath::DivideAndRoundUp(), WrappedGroupStride, UE::Math::TIntVector3< InIntType >::X, UE::Math::TIntVector3< InIntType >::Y, and UE::Math::TIntVector3< InIntType >::Z.
Referenced by TClearReplacementCS< EClearReplacementResourceType::Buffer, FClearReplacementBase_Uint_Bounds >::GetGroupCount(), and GetGroupCountWrapped().
GetGroupCountWrapped() [2/2]
FIntVector FComputeShaderUtils::GetGroupCountWrapped (const int32 ThreadCount, const int32 GroupSize) inline
Compute the number of groups to dispatch and allow wrapping to Y and Z dimension if X group count overflows.
Calculate the linear group index as (or use GetUnWrappedDispatchGroupId(GroupId) in ComputeShaderUtils.ush): uint LinearGroupId = GroupId.X + (GroupId.Z * WrappedGroupStride + GroupId.Y) * WrappedGroupStride; Note that you must use an early out because LinearGroupId may be larger than the ideal due to wrapping.
Definition at line 426 of file RenderGraphUtils.h.
References FMath::DivideAndRoundUp(), and GetGroupCountWrapped().
ValidateGroupCount()
void FComputeShaderUtils::ValidateGroupCount (const FIntVector & GroupCount) inline
Definition at line 431 of file RenderGraphUtils.h.
References ensure, UE::Math::TIntVector3< InIntType >::X, UE::Math::TIntVector3< InIntType >::Y, and UE::Math::TIntVector3< InIntType >::Z.
Referenced by AddPass(), AddPass(), and Dispatch().
ValidateIndirectArgsBuffer() [1/2]
void FComputeShaderUtils::ValidateIndirectArgsBuffer (const FRDGBufferRef IndirectArgsBuffer, uint32 IndirectArgOffset) inline
Definition at line 451 of file RenderGraphUtils.h.
References checkf, FRDGBuffer::Desc, EnumHasAnyFlags(), FRDGBuffer::GetSize(), FRDGResource::Name, TEXT, FRDGBufferDesc::Usage, and ValidateIndirectArgsBuffer().
ValidateIndirectArgsBuffer() [2/2]
void FComputeShaderUtils::ValidateIndirectArgsBuffer (uint32 IndirectArgsBufferSize, uint32 IndirectArgOffset) inline
Definition at line 438 of file RenderGraphUtils.h.
References checkf, and TEXT.
Referenced by AddPass(), DispatchIndirect(), DispatchIndirect(), and ValidateIndirectArgsBuffer().
Variable Documentation
kGolden2DGroupSize
int32 FComputeShaderUtils::kGolden2DGroupSize = 8 static constexpr
Ideal size of group size 8x8 to occupy at least an entire wave on GCN, two warp on Nvidia.
Definition at line 346 of file RenderGraphUtils.h.
WrappedGroupStride
int32 FComputeShaderUtils::WrappedGroupStride = 128 static constexpr
Constant stride used when wrapping too large 1D dispatches using GetGroupCountWrapped, selected as 128 appears to be the lowest common denominator for mobile (GLES 3.1).
For PC (with ~64k groups / dimension) this yields ~8M groups (500M threads @ group size 64) before even wrapping into Z. NOTE: this value must match WRAPPED_GROUP_STRIDE in ComputeShaderUtils.ush
Definition at line 390 of file RenderGraphUtils.h.
Referenced by GetGroupCountWrapped().