Unreal Engine 5.6 C++ API: UE::Anim::Conversion Namespace Reference
UE::Anim::Conversion Namespace Reference
Functions
template<typename BoneIndexTypeA, typename BoneIndexTypeB>
BoneIndexTypeB MakeIndex (BoneIndexTypeA BoneIndex, const FBoneContainer &BoneContainer)
template<>
FMeshPoseBoneIndex MakeIndex (FCompactPoseBoneIndex BoneIndex, const FBoneContainer &BoneContainer)
template<>
FCompactPoseBoneIndex MakeIndex (FMeshPoseBoneIndex BoneIndex, const FBoneContainer &BoneContainer)
Function Documentation
MakeIndex() [1/3]
template<typename BoneIndexTypeA, typename BoneIndexTypeB> BoneIndexTypeB UE::Anim::Conversion::MakeIndex (BoneIndexTypeA BoneIndex, const FBoneContainer & BoneContainer)
Definition at line 48 of file AttributesContainer.h.
Referenced by UE::Anim::TAttributeContainer< BoneIndexType, InAllocator >::CopyFrom().
MakeIndex() [2/3]
template<> FMeshPoseBoneIndex UE::Anim::Conversion::MakeIndex (FCompactPoseBoneIndex BoneIndex, const FBoneContainer & BoneContainer) inline
Definition at line 54 of file AttributesContainer.h.
References FBoneContainer::GetBoneIndicesArray(), INDEX_NONE, TArray< InElementType, InAllocatorType >::IsValidIndex(), and FBoneContainer::MakeMeshPoseIndex().
MakeIndex() [3/3]
template<> FCompactPoseBoneIndex UE::Anim::Conversion::MakeIndex (FMeshPoseBoneIndex BoneIndex, const FBoneContainer & BoneContainer) inline
Definition at line 62 of file AttributesContainer.h.
References FBoneContainer::MakeCompactPoseIndex().