Unreal Engine 5.6 C++ API: CookedMetaDataUtil Namespace Reference
CookedMetaDataUtil Namespace Reference
Cooked meta-data for a UEnum.
Namespaces
namespace Internal
Functions
template<typename CookedMetaDataType>
CookedMetaDataType * FindCookedMetaData (UObject *Outer, const TCHAR *Name)
template<typename CookedMetaDataType>
CookedMetaDataType * NewCookedMetaData (UObject *Outer, FName Name, TSubclassOf< CookedMetaDataType > Class=CookedMetaDataType::StaticClass())
template<typename CookedMetaDataType, typename CookedMetaDataPtrType>
void PurgeCookedMetaData (CookedMetaDataPtrType &CookedMetaDataPtr)
Detailed Description
Cooked meta-data for a UEnum.
Cooked meta-data for a UScriptStruct, including its nested FProperty data. Cooked meta-data for a UClass, including its nested FProperty and UFunction data.
Function Documentation
FindCookedMetaData()
template<typename CookedMetaDataType> CookedMetaDataType * CookedMetaDataUtil::FindCookedMetaData (UObject * Outer, const TCHAR * Name)
Definition at line 195 of file CookedMetaData.h.
References FindCookedMetaData(), Name, and Outer.
Referenced by FindCookedMetaData().
NewCookedMetaData()
template<typename CookedMetaDataType> CookedMetaDataType * CookedMetaDataUtil::NewCookedMetaData (UObject * Outer, FName Name, TSubclassOf< CookedMetaDataType > Class = CookedMetaDataType::StaticClass())
Definition at line 189 of file CookedMetaData.h.
References Class, Name, NewCookedMetaData(), NewObject, Outer, RF_Public, and RF_Standalone.
Referenced by NewCookedMetaData().
PurgeCookedMetaData()
template<typename CookedMetaDataType, typename CookedMetaDataPtrType> void CookedMetaDataUtil::PurgeCookedMetaData (CookedMetaDataPtrType & CookedMetaDataPtr)
Definition at line 201 of file CookedMetaData.h.
References CookedMetaDataUtil::Internal::PrepareCookedMetaDataForPurge(), and PurgeCookedMetaData().
Referenced by PurgeCookedMetaData().