Unreal Engine 5.6 C++ API: IndexUtil Namespace Reference
IndexUtil Namespace Reference
Data Structures
struct FIndex2i
2-index tuple.
Functions
template<typename Func>
FIndex3i ApplyMap (const FIndex3i &Val, Func MapFunc)
template<typename T, typename Func>
UE::Math::TVector< T > ApplyMap (const UE::Math::TVector< T > &Val, Func MapFunc)
template<typename Func>
void ApplyMap (FIndex3i &Val, Func MapFunc)
Replace Val with MapFunc[Val] using index operator.
template<typename T, typename Func>
void ApplyMap (UE::Math::TVector< T > &Val, Func MapFunc)
Replace Val with MapFunc[Val] using index operator.
template<typename T, typename Func>
bool ArrayCheck (const TArray< T > &ToCheck, Func CheckFn)
template<typename T, typename Vec>
int FindEdgeIndexInTri (T VertexID1, T VertexID2, const Vec &TriangleVerts)
Find unordered edge [VertexID1,VertexID2] in TriangleVerts.
int FindEdgeOtherVertex (const FIndex2i &EdgeVerts, int VertexID)
int FindSharedEdgeVertex (const FIndex2i &EdgeVerts1, const FIndex2i &EdgeVerts2)
template<typename T, typename Vec>
int FindTriIndex (T VertexID, const Vec &TriangleVerts)
template<typename T, typename Vec>
int FindTriOrderedEdge (T VertexID1, T VertexID2, const Vec &TriangleVerts)
Find ordered edge [VertexID1,VertexID2] in TriangleVerts.
template<typename T, typename Vec>
int FindTriOtherIndex (T VertexID1, T VertexID2, const Vec &TriangleVerts)
Find ordered edge [VertexID1,VertexID2] in TriangleVerts and then return the index of the remaining third vertex.
int FindTriOtherVtx (int VertexID1, int VertexID2, const TDynamicVector< FIndex3i > &TriIndexArray, int TriangleIndex)
Find ordered edge [VertexID1,VertexID2] in a triangle that is in an array of triangles, and return remaining third vertex.
template<typename T, typename Vec>
int FindTriOtherVtx (T VertexID1, T VertexID2, const Vec &TriangleVerts)
Find ordered edge [VertexID1,VertexID2] in TriangleVerts and then return the remaining third vertex.
template<typename T, typename Vec>
int FindTriOtherVtxUnsafe (T VertexID1, T VertexID2, const Vec &TriangleVerts)
Find third vertex of triangle that is not VertexID1 or VertexID2.
int GetOtherTriIndex (int i0, int i1)
If i0 and i1 are unordered indices into a triangle, each in range 0-2, return the third index.
template<typename T, typename Vec>
bool OrientTriEdge (T &Vertex1, T &Vertex2, const Vec &TriangleVerts)
Assuming [Vertex1,Vertex2] is an unordered edge in TriangleVerts, return Vertex1 and Vertex2 in the correct order (ie the same as TriangleVerts)
template<typename T, typename Vec>
int OrientTriEdgeAndFindOtherVtx (T &Vertex1, T &Vertex2, const Vec &TriangleVerts)
Assuming [Vertex1,Vertex2] is an unordered edge in TriangleVerts, return Vertex1 and Vertex2 in the correct order (ie the same as TriangleVerts), and returns the vertex ID of the other vertex.
template<typename T>
bool SamePairUnordered (T a0, T a1, T b0, T b1)
Variables
GEOMETRYCORE_API const int BoxFaceNormals [6]
Box Face Normal Axes associated with BoxFaces.
GEOMETRYCORE_API const int BoxFaces [6][4]
Corner vertices of box faces - see FOrientedBox3.GetCorner for points associated w/ indexing.
GEOMETRYCORE_API const FVector2i BoxFacesUV [4]
Corner unit-UV ordering of box faces - {0,0}, {1,0}, {1,1}, {0,1}.
GEOMETRYCORE_API const FVector3i GridOffsets26 [26]
all permutations of (+-1, +-1, +-1), can be used to iterate over connected face/edge/corner neighbours of a grid cell
GEOMETRYCORE_API const FVector2i GridOffsets4 [4]
integer indices offsets in x/y directions
GEOMETRYCORE_API const FVector3i GridOffsets6 [6]
integer indices offsets in x/y/z directions, corresponds w/ BoxFaces directions
GEOMETRYCORE_API const FVector2i GridOffsets8 [8]
integer indices offsets in x/y directions and diagonals
Function Documentation
ApplyMap() [1/4]
template<typename Func> FIndex3i IndexUtil::ApplyMap (const FIndex3i & Val, Func MapFunc)
Returns
MapFunc[Val] using index operator
Definition at line 271 of file IndexUtil.h.
ApplyMap() [2/4]
template<typename T, typename Func> UE::Math::TVector< T > IndexUtil::ApplyMap (const UE::Math::TVector< T > & Val, Func MapFunc)
Returns
MapFunc[Val] using index operator
Definition at line 281 of file IndexUtil.h.
ApplyMap() [3/4]
template<typename Func> void IndexUtil::ApplyMap (FIndex3i & Val, Func MapFunc)
Replace Val with MapFunc[Val] using index operator.
Definition at line 248 of file IndexUtil.h.
ApplyMap() [4/4]
template<typename T, typename Func> void IndexUtil::ApplyMap (UE::Math::TVector< T > & Val, Func MapFunc)
Replace Val with MapFunc[Val] using index operator.
Definition at line 259 of file IndexUtil.h.
ArrayCheck()
template<typename T, typename Func> bool IndexUtil::ArrayCheck (const TArray< T > & ToCheck, Func CheckFn)
Returns
false if CheckFn returns false on any element of ToCheck, true otherwise
Definition at line 290 of file IndexUtil.h.
References Value.
Referenced by UE::Geometry::FMeshRegionOperator::BackPropropagate().
FindEdgeIndexInTri()
template<typename T, typename Vec> int IndexUtil::FindEdgeIndexInTri (T VertexID1, T VertexID2, const Vec & TriangleVerts) inline
Find unordered edge [VertexID1,VertexID2] in TriangleVerts.
Returns
index in range 0-2, or InvalidID if not found
Definition at line 74 of file IndexUtil.h.
References IndexConstants::InvalidID, and SamePairUnordered().
FindEdgeOtherVertex()
int IndexUtil::FindEdgeOtherVertex (const FIndex2i & EdgeVerts, int VertexID) inline
Returns
the vertex in the pair ev that is not v, or InvalidID if not found
Definition at line 49 of file IndexUtil.h.
References UE::Geometry::FIndex2i::A, UE::Geometry::FIndex2i::B, and IndexConstants::InvalidID.
Referenced by UE::Geometry::FSubRegionRemesher::InitializeFromVertexROI().
FindSharedEdgeVertex()
int IndexUtil::FindSharedEdgeVertex (const FIndex2i & EdgeVerts1, const FIndex2i & EdgeVerts2) inline
Returns
the vertex that is the same in both EdgeVerts1 and EdgeVerts2, or InvalidID if not found
Definition at line 37 of file IndexUtil.h.
References UE::Geometry::FIndex2i::A, UE::Geometry::FIndex2i::B, and IndexConstants::InvalidID.
FindTriIndex()
template<typename T, typename Vec> int IndexUtil::FindTriIndex (T VertexID, const Vec & TriangleVerts) inline
Returns
index 0/1/2 of VertexID in TriangleVerts, or InvalidID if not found
Definition at line 61 of file IndexUtil.h.
References IndexConstants::InvalidID.
Referenced by UE::MeshDeformation::ConstructFullCotangentLaplacian(), and UE::Geometry::FMeshEdgesFromTriangleSubIndices::InitializeFromEdgeIDs().
FindTriOrderedEdge()
template<typename T, typename Vec> int IndexUtil::FindTriOrderedEdge (T VertexID1, T VertexID2, const Vec & TriangleVerts) inline
Find ordered edge [VertexID1,VertexID2] in TriangleVerts.
Returns
index in range 0-2, or InvalidID if not found
Definition at line 88 of file IndexUtil.h.
References IndexConstants::InvalidID.
Referenced by UE::Geometry::FSimpleIntrinsicEdgeFlipMesh::AreSameOrientation().
FindTriOtherIndex()
template<typename T, typename Vec> int IndexUtil::FindTriOtherIndex (T VertexID1, T VertexID2, const Vec & TriangleVerts) inline
Find ordered edge [VertexID1,VertexID2] in TriangleVerts and then return the index of the remaining third vertex.
Returns
index of third vertex, or InvalidID if not found
Definition at line 163 of file IndexUtil.h.
References IndexConstants::InvalidID, and SamePairUnordered().
FindTriOtherVtx() [1/2]
int IndexUtil::FindTriOtherVtx (int VertexID1, int VertexID2, const TDynamicVector< FIndex3i > & TriIndexArray, int TriangleIndex) inline
Find ordered edge [VertexID1,VertexID2] in a triangle that is in an array of triangles, and return remaining third vertex.
Parameters
VertexID1 first vertex of edge
VertexID2 second vertex of edge
TriIndexArray array of triangle tuples
TriangleIndex which triangle in array to search
Returns
vertex id of other vertex, or InvalidID if not found
Definition at line 143 of file IndexUtil.h.
References IndexConstants::InvalidID, SamePairUnordered(), and UE::Geometry::Triangle.
FindTriOtherVtx() [2/2]
template<typename T, typename Vec> int IndexUtil::FindTriOtherVtx (T VertexID1, T VertexID2, const Vec & TriangleVerts) inline
Find ordered edge [VertexID1,VertexID2] in TriangleVerts and then return the remaining third vertex.
Returns
vertex id of other vertex, or InvalidID if not found
Definition at line 123 of file IndexUtil.h.
References IndexConstants::InvalidID, and SamePairUnordered().
FindTriOtherVtxUnsafe()
template<typename T, typename Vec> int IndexUtil::FindTriOtherVtxUnsafe (T VertexID1, T VertexID2, const Vec & TriangleVerts) inline
Find third vertex of triangle that is not VertexID1 or VertexID2.
Triangle must contain VertexID1 and VertexID2 or result will be incorrect.
Returns
VertexID of third vertex, or incorrect result if precondition is not met
Definition at line 101 of file IndexUtil.h.
GetOtherTriIndex()
int IndexUtil::GetOtherTriIndex (int i0, int i1) inline
If i0 and i1 are unordered indices into a triangle, each in range 0-2, return the third index.
Definition at line 179 of file IndexUtil.h.
OrientTriEdge()
template<typename T, typename Vec> bool IndexUtil::OrientTriEdge (T & Vertex1, T & Vertex2, const Vec & TriangleVerts) inline
Assuming [Vertex1,Vertex2] is an unordered edge in TriangleVerts, return Vertex1 and Vertex2 in the correct order (ie the same as TriangleVerts)
Warning
result is garbage if either vertex is not an edge in TriangleVerts
Returns
true if order was swapped
Definition at line 193 of file IndexUtil.h.
OrientTriEdgeAndFindOtherVtx()
template<typename T, typename Vec> int IndexUtil::OrientTriEdgeAndFindOtherVtx (T & Vertex1, T & Vertex2, const Vec & TriangleVerts) inline
Assuming [Vertex1,Vertex2] is an unordered edge in TriangleVerts, return Vertex1 and Vertex2 in the correct order (ie the same as TriangleVerts), and returns the vertex ID of the other vertex.
Returns
ID of third vertex, or InvalidID if the edge was not found
Definition at line 229 of file IndexUtil.h.
References IndexConstants::InvalidID, and SamePairUnordered().
SamePairUnordered()
template<typename T> bool IndexUtil::SamePairUnordered (T a0, T a1, T b0, T b1) inline
Returns
true if [a0,a1] and [b0,b1] are the same pair, ignoring order
Definition at line 26 of file IndexUtil.h.
Referenced by FindEdgeIndexInTri(), FindTriOtherIndex(), FindTriOtherVtx(), FindTriOtherVtx(), and OrientTriEdgeAndFindOtherVtx().
Variable Documentation
BoxFaceNormals
GEOMETRYCORE_API const int IndexUtil::BoxFaceNormals[6] extern
Box Face Normal Axes associated with BoxFaces.
Use Sign(BoxFaceNormals[i]) * Box.Axis(Abs(BoxFaceNormals[i])-1) to get vector
Referenced by UE::Geometry::FMinimalBoxMeshGenerator::Generate().
BoxFaces
GEOMETRYCORE_API const int IndexUtil::BoxFaces[6][4] extern
Corner vertices of box faces - see FOrientedBox3.GetCorner for points associated w/ indexing.
Referenced by UE::Geometry::FMinimalBoxMeshGenerator::Generate().
BoxFacesUV
GEOMETRYCORE_API const FVector2i IndexUtil::BoxFacesUV[4] extern
Corner unit-UV ordering of box faces - {0,0}, {1,0}, {1,1}, {0,1}.
Referenced by UE::Geometry::FMinimalBoxMeshGenerator::Generate().
GridOffsets26
GEOMETRYCORE_API const FVector3i IndexUtil::GridOffsets26[26] extern
all permutations of (+-1, +-1, +-1), can be used to iterate over connected face/edge/corner neighbours of a grid cell
Referenced by UE::Geometry::TMeshWindingNumberGrid< TriangleMeshType >::make_grid(), and UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::make_level_set3_parallel_floodfill().
GridOffsets4
GEOMETRYCORE_API const FVector2i IndexUtil::GridOffsets4[4] extern
integer indices offsets in x/y directions
GridOffsets6
GEOMETRYCORE_API const FVector3i IndexUtil::GridOffsets6[6] extern
integer indices offsets in x/y/z directions, corresponds w/ BoxFaces directions
Referenced by UE::Geometry::FMarchingCubes::generate_continuation().
GridOffsets8
GEOMETRYCORE_API const FVector2i IndexUtil::GridOffsets8[8] extern
integer indices offsets in x/y directions and diagonals
Referenced by UE::Geometry::TMarchingPixelInfill< PixelType >::ComputeInfill().