Unreal Engine 5.6 C++ API: PropertyVisitorHelpers Namespace Reference
PropertyVisitorHelpers Namespace Reference
Namespaces
namespace Private
Functions
void PathAppendString (TArrayView< const FPropertyVisitorInfo > Path, FStringBuilderBase &Out, const TCHAR *Separator=TEXT("."))
bool PathIsContainedWithin (TArrayView< const FPropertyVisitorInfo > Path, TArrayView< const FPropertyVisitorInfo > OtherPath, bool *bIsEqual=nullptr)
Is this property path contained in the specified one.
FArchiveSerializedPropertyChain PathToSerializedPropertyChain (TArrayView< const FPropertyVisitorInfo > Path)
Convert the given path to a serialized property chain.
FString PathToString (TArrayView< const FPropertyVisitorInfo > Path, const TCHAR *Separator=TEXT("."))
Convert the given path to a string.
void PathToString (TArrayView< const FPropertyVisitorInfo > Path, FStringBuilderBase &Out, const TCHAR *Separator=TEXT("."))
template<typename Type>
void * ResolveVisitedPath (const Type *RootObject, void *RootData, const FPropertyVisitorPath &Path)
Given a FPropertyVisitorPath, attempt to resolve that to a valid data pointer.
template<typename Type>
void * ResolveVisitedPathInfo_Generic (Type *This, FPropertyVisitorPath &Path, void *Data, const FPropertyVisitorInfo &Info)
A generic implementation of ResolveVisitedPathInfo that uses Visit to find the property data pointer.
template<typename Type>
void * ResolveVisitedPathInfo_Generic (Type *This, void *Data, const FPropertyVisitorInfo &Info)
UE_DEPRECATED (5.7, "Visit is deprecated, please use Visit with context instead.") 1 EPropertyVisitorControlFlow VisitProperty(const UStruct *PropertyOwner
EPropertyVisitorControlFlow VisitProperty (const UStruct *PropertyOwner, const FProperty *Property, FPropertyVisitorContext &Context, const TFunctionRef< EPropertyVisitorControlFlow(const FPropertyVisitorContext &)> InFunc)
Visit the property from an instance.
Variables
const FProperty FPropertyVisitorPath const FPropertyVisitorData & InData
const FProperty FPropertyVisitorPath const FPropertyVisitorData const TFunctionRef< EPropertyVisitorControlFlow(const FPropertyVisitorPath &, const FPropertyVisitorData &)> InFunc
const FProperty FPropertyVisitorPath & Path
const FProperty * Property
Function Documentation
PathAppendString()
void PropertyVisitorHelpers::PathAppendString (TArrayView< const FPropertyVisitorInfo > Path, FStringBuilderBase & Out, const TCHAR * Separator = TEXT("."))
References Path, PathAppendString(), and TEXT.
Referenced by PathAppendString().
PathIsContainedWithin()
bool PropertyVisitorHelpers::PathIsContainedWithin (TArrayView< const FPropertyVisitorInfo > Path, TArrayView< const FPropertyVisitorInfo > OtherPath, bool * bIsEqual = nullptr)
Is this property path contained in the specified one.
Parameters
OtherPath property path to check if it is contained in
bIsEqual optional parameter to know if it fully match
Returns
true if it is contained in the specified path
References Path, and PathIsContainedWithin().
Referenced by PathIsContainedWithin().
PathToSerializedPropertyChain()
FArchiveSerializedPropertyChain PropertyVisitorHelpers::PathToSerializedPropertyChain (TArrayView< const FPropertyVisitorInfo > Path)
Convert the given path to a serialized property chain.
References Path, and PathToSerializedPropertyChain().
Referenced by PathToSerializedPropertyChain().
PathToString() [1/2]
FString PropertyVisitorHelpers::PathToString (TArrayView< const FPropertyVisitorInfo > Path, const TCHAR * Separator = TEXT("."))
Convert the given path to a string.
References Path, PathToString(), and TEXT.
Referenced by PathToString(), and PathToString().
PathToString() [2/2]
void PropertyVisitorHelpers::PathToString (TArrayView< const FPropertyVisitorInfo > Path, FStringBuilderBase & Out, const TCHAR * Separator = TEXT("."))
References Path, PathToString(), and TEXT.
ResolveVisitedPath()
template<typename Type> void * PropertyVisitorHelpers::ResolveVisitedPath (const Type * RootObject, void * RootData, const FPropertyVisitorPath & Path)
Given a FPropertyVisitorPath, attempt to resolve that to a valid data pointer.
RootObject is required to implement ResolveVisitedPathInfo to provide the resolver logic.
Definition at line 293 of file PropertyVisitor.h.
References Path, FPropertyVisitorInfo::Property, and PropertyVisitorHelpers::Private::ResolveVisitedPathInfo().
ResolveVisitedPathInfo_Generic() [1/2]
template<typename Type> void * PropertyVisitorHelpers::ResolveVisitedPathInfo_Generic (Type * This, FPropertyVisitorPath & Path, void * Data, const FPropertyVisitorInfo & Info)
A generic implementation of ResolveVisitedPathInfo that uses Visit to find the property data pointer.
This may be used as the ResolveVisitedPathInfo implementation for your type if it doesn't have a more optimized version.
Definition at line 314 of file PropertyVisitor.h.
References Info, Path, and StepOver.
Referenced by ResolveVisitedPathInfo_Generic().
ResolveVisitedPathInfo_Generic() [2/2]
template<typename Type> void * PropertyVisitorHelpers::ResolveVisitedPathInfo_Generic (Type * This, void * Data, const FPropertyVisitorInfo & Info)
Definition at line 343 of file PropertyVisitor.h.
References Info, Path, and ResolveVisitedPathInfo_Generic().
UE_DEPRECATED()
PropertyVisitorHelpers::UE_DEPRECATED (5. 7, "Visit is deprecated , please use Visit with context instead.") const
VisitProperty()
EPropertyVisitorControlFlow PropertyVisitorHelpers::VisitProperty (const UStruct * PropertyOwner, const FProperty * Property, FPropertyVisitorContext & Context, const TFunctionRef< EPropertyVisitorControlFlow(const FPropertyVisitorContext &)> InFunc)
Visit the property from an instance.
References InFunc, Property, and VisitProperty().
Referenced by VisitProperty().
Variable Documentation
InData
const FProperty FPropertyVisitorPath const FPropertyVisitorData& PropertyVisitorHelpers::InData
Definition at line 350 of file PropertyVisitor.h.
InFunc
const FProperty FPropertyVisitorPath const FPropertyVisitorData const TFunctionRef<EPropertyVisitorControlFlow(const FPropertyVisitorPath& , const FPropertyVisitorData&)> PropertyVisitorHelpers::InFunc
Definition at line 350 of file PropertyVisitor.h.
Referenced by VisitProperty().
Path
const FProperty FPropertyVisitorPath& PropertyVisitorHelpers::Path
Definition at line 350 of file PropertyVisitor.h.
Referenced by PathAppendString(), PathIsContainedWithin(), PathToSerializedPropertyChain(), PathToString(), PathToString(), ResolveVisitedPath(), ResolveVisitedPathInfo_Generic(), and ResolveVisitedPathInfo_Generic().
Property
const FProperty* PropertyVisitorHelpers::Property
Definition at line 350 of file PropertyVisitor.h.
Referenced by VisitProperty().