Unreal Engine 5.6 C++ API: ChaosInterface Namespace Reference
ChaosInterface Namespace Reference
Data Structures
struct FScopedSceneReadLock
Functions
void CalculateMassPropertiesFromShapeCollection (Chaos::FMassProperties &OutProperties, const Chaos::FShapesArray &InShapes, const TArray< bool > &bContributesToMass, float InDensityKGPerCM)
void CalculateMassPropertiesFromShapeCollection (Chaos::FMassProperties &OutProperties, const TArray< FPhysicsShapeHandle > &InShapes, float InDensityKGPerCM)
Generate the mass properties for a set of shapes in the space of the shapes' owner.
Chaos::EChaosCollisionTraceFlag ConvertCollisionTraceFlag (ECollisionTraceFlag Flag)
void CreateGeometry (const FGeometryAddParams &InParams, TArray< Chaos::FImplicitObjectPtr > &OutGeoms, Chaos::FShapesArray &OutShapes)
Create the Chaos Geometry based on the geometry parameters.
UPrimitiveComponent * GetPrimitiveComponentFromUserData (const Chaos::FGeometryParticle &Actor)
UPhysicalMaterial * GetUserData (const Chaos::FChaosPhysicsMaterial &Material)
FBodyInstance * GetUserData (const Chaos::FGeometryParticle &Actor)
bool HasValidUserData (const Chaos::FGeometryParticle &Actor)
FQueryFilterData MakeQueryFilterData (const FCollisionFilterData &FilterData, EQueryFlags QueryFlags, const FCollisionQueryParams &Params)
UE_DEPRECATED (5.4, "Use CreateGeometry with FImplicitObjectPtr instead") void 1 CreateGeometry(const FGeometryAddParams &InParams
Variables
TArray< TUniquePtr< Chaos::FImplicitObject > > & OutGeoms
TArray< TUniquePtr< Chaos::FImplicitObject > > Chaos::FShapesArray & OutShapes
Function Documentation
CalculateMassPropertiesFromShapeCollection() [1/2]
void ChaosInterface::CalculateMassPropertiesFromShapeCollection (Chaos::FMassProperties & OutProperties, const Chaos::FShapesArray & InShapes, const TArray< bool > & bContributesToMass, float InDensityKGPerCM)
References CalculateMassPropertiesFromShapeCollection().
CalculateMassPropertiesFromShapeCollection() [2/2]
void ChaosInterface::CalculateMassPropertiesFromShapeCollection (Chaos::FMassProperties & OutProperties, const TArray< FPhysicsShapeHandle > & InShapes, float InDensityKGPerCM)
Generate the mass properties for a set of shapes in the space of the shapes' owner.
Rotation will be built into the inertia matrix (it may not be diagonal) and RotationOfMass will be identity.
References CalculateMassPropertiesFromShapeCollection().
Referenced by CalculateMassPropertiesFromShapeCollection(), and CalculateMassPropertiesFromShapeCollection().
ConvertCollisionTraceFlag()
Chaos::EChaosCollisionTraceFlag ChaosInterface::ConvertCollisionTraceFlag (ECollisionTraceFlag Flag)
CreateGeometry()
void ChaosInterface::CreateGeometry (const FGeometryAddParams & InParams, TArray< Chaos::FImplicitObjectPtr > & OutGeoms, Chaos::FShapesArray & OutShapes)
Create the Chaos Geometry based on the geometry parameters.
References OutGeoms, and OutShapes.
GetPrimitiveComponentFromUserData()
UPrimitiveComponent * ChaosInterface::GetPrimitiveComponentFromUserData (const Chaos::FGeometryParticle & Actor)
References Actor.
GetUserData() [1/2]
UPhysicalMaterial * ChaosInterface::GetUserData (const Chaos::FChaosPhysicsMaterial & Material)
References Material.
GetUserData() [2/2]
FBodyInstance * ChaosInterface::GetUserData (const Chaos::FGeometryParticle & Actor)
References Actor.
HasValidUserData()
bool ChaosInterface::HasValidUserData (const Chaos::FGeometryParticle & Actor)
References Actor.
MakeQueryFilterData()
FQueryFilterData ChaosInterface::MakeQueryFilterData (const FCollisionFilterData & FilterData, EQueryFlags QueryFlags, const FCollisionQueryParams & Params) inline
Definition at line 37 of file ChaosInterfaceWrapper.h.
References Params.
UE_DEPRECATED()
ChaosInterface::UE_DEPRECATED (5. 4, "Use CreateGeometry with FImplicitObjectPtr instead") const &
Variable Documentation
OutGeoms
TArray<TUniquePtr<Chaos::FImplicitObject> >& ChaosInterface::OutGeoms
Definition at line 24 of file ChaosInterfaceUtils.h.
Referenced by CreateGeometry().
OutShapes
TArray<TUniquePtr<Chaos::FImplicitObject> > Chaos::FShapesArray& ChaosInterface::OutShapes
Definition at line 24 of file ChaosInterfaceUtils.h.
Referenced by CreateGeometry().