Unreal Engine 5.6 C++ API: UE::Private::WorldPartition Namespace Reference
UE::Private::WorldPartition Namespace Reference
Data Structures
struct FStreamingDescriptor
Functions
template<class HashBuilder>
void UpdateHash (HashBuilder &Builder, bool Value)
template<class HashBuilder>
void UpdateHash (HashBuilder &Builder, const FActorContainerID &Value)
template<class HashBuilder>
void UpdateHash (HashBuilder &Builder, const FGuid &Value)
template<class HashBuilder>
void UpdateHash (HashBuilder &Builder, const FName &Value)
template<class HashBuilder>
void UpdateHash (HashBuilder &Builder, const FString &Value)
template<class HashBuilder>
void UpdateHash (HashBuilder &Builder, const FTopLevelAssetPath &Value)
template<class HashBuilder>
void UpdateHash (HashBuilder &Builder, const FTransform &Value)
template<class T, class HashBuilder>
void UpdateHash (HashBuilder &Builder, const T &Value)
template<class T, class HashBuilder>
void UpdateHash (HashBuilder &Builder, const TArray< T > &Values)
Function Documentation
UpdateHash() [1/9]
template<class HashBuilder> void UE::Private::WorldPartition::UpdateHash (HashBuilder & Builder, bool Value)
Definition at line 81 of file WorldPartitionUtils.h.
References Value.
UpdateHash() [2/9]
template<class HashBuilder> void UE::Private::WorldPartition::UpdateHash (HashBuilder & Builder, const FActorContainerID & Value)
Definition at line 87 of file WorldPartitionUtils.h.
References Value.
UpdateHash() [3/9]
template<class HashBuilder> void UE::Private::WorldPartition::UpdateHash (HashBuilder & Builder, const FGuid & Value)
Definition at line 51 of file WorldPartitionUtils.h.
References Value.
UpdateHash() [4/9]
template<class HashBuilder> void UE::Private::WorldPartition::UpdateHash (HashBuilder & Builder, const FName & Value)
Definition at line 57 of file WorldPartitionUtils.h.
References MakeMemoryView(), FName::StringBufferSize, and Value.
UpdateHash() [5/9]
template<class HashBuilder> void UE::Private::WorldPartition::UpdateHash (HashBuilder & Builder, const FString & Value)
Definition at line 64 of file WorldPartitionUtils.h.
References Value.
UpdateHash() [6/9]
template<class HashBuilder> void UE::Private::WorldPartition::UpdateHash (HashBuilder & Builder, const FTopLevelAssetPath & Value)
Definition at line 70 of file WorldPartitionUtils.h.
References UpdateHash(), and Value.
UpdateHash() [7/9]
template<class HashBuilder> void UE::Private::WorldPartition::UpdateHash (HashBuilder & Builder, const FTransform & Value)
Definition at line 76 of file WorldPartitionUtils.h.
References Value.
UpdateHash() [8/9]
template<class T, class HashBuilder> void UE::Private::WorldPartition::UpdateHash (HashBuilder & Builder, const T & Value)
References Value.
Referenced by UpdateHash(), and UpdateHash().
UpdateHash() [9/9]
template<class T, class HashBuilder> void UE::Private::WorldPartition::UpdateHash (HashBuilder & Builder, const TArray< T > & Values)
Definition at line 93 of file WorldPartitionUtils.h.
References UpdateHash().