Unreal Engine 5.6 C++ API: UE::Math::anonymous_namespace{ScaleRotationTranslationMatrix.h} Namespace Reference
UE::Math::anonymous_namespace{ScaleRotationTranslationMatrix.h} Namespace Reference
Functions
template<typename T>
void GetSinCos (T &S, T &C, T Degrees)
Function Documentation
GetSinCos()
template<typename T> void UE::Math::anonymous_namespace{ScaleRotationTranslationMatrix.h}::GetSinCos (T & S, T & C, T Degrees)
Definition at line 41 of file ScaleRotationTranslationMatrix.h.
References Degrees, FMath::DegreesToRadians(), GetSinCos(), and FMath::SinCos().
Referenced by GetSinCos().