Unreal Engine 5.6 C++ API: ForEachImpl Namespace Reference
ForEachImpl Namespace Reference
Typedefs
template<typename ElementIDType, typename ForEachFunc>
using JumpTableType = TJumpTable<void(FName, ForEachFunc, FMeshAttributeArraySetBase*), TTupleArity<AttributeTypes>::Value>
Functions
template<typename ElementIDType, typename ForEachFunc, uint32 I>
static void Dispatch (FName Name, ForEachFunc Fn, FMeshAttributeArraySetBase *Attributes)
template<typename ElementIDType, typename ForEachFunc, uint32... Is>
static constexpr JumpTableType< ElementIDType, ForEachFunc > MakeJumpTable (TIntegerSequence< uint32, Is... >)
Typedef Documentation
JumpTableType
template<typename ElementIDType, typename ForEachFunc> using ForEachImpl::JumpTableType = TJumpTable<void(FName, ForEachFunc, FMeshAttributeArraySetBase*), TTupleArity<AttributeTypes>::Value>
Definition at line 2179 of file MeshAttributeArray.h.
Function Documentation
Dispatch()
template<typename ElementIDType, typename ForEachFunc, uint32 I> void ForEachImpl::Dispatch (FName Name, ForEachFunc Fn, FMeshAttributeArraySetBase * Attributes) static
Definition at line 2183 of file MeshAttributeArray.h.
References Name.
Referenced by MakeJumpTable().
MakeJumpTable()
template<typename ElementIDType, typename ForEachFunc, uint32... Is> constexpr JumpTableType< ElementIDType, ForEachFunc > ForEachImpl::MakeJumpTable (TIntegerSequence< uint32, Is... >) static constexpr
Definition at line 2202 of file MeshAttributeArray.h.
References Dispatch().
Referenced by TAttributesSet< FVertexID >::ForEach().