Unreal Engine 5.6 C++ API: AlgoImpl Namespace Reference
AlgoImpl Namespace Reference
Data Structures
struct FKahnContext
Some variables shared with subfunctions.
struct FMutuallyReachableVertexSetContext
Scratch variables shared across multiple calls to FindMostIndependentMutuallyReachableVertexSet.
struct TLess
struct TRangePointerType
Traits class whose Type member is the pointer type to an element of the range.
struct TRangePointerType< T[N]>
Typedefs
typedef int32 FKahnHandle
KahnTopologicalSort converts vertices and edges from ElementType to indexes of the vertex in the original UniqueRange of ElementType.
Functions
template<typename RangeType, typename ValueType, typename ProjectionType>
TRangePointerType< typenameTRemoveReference< RangeType >::Type >::Type FindBy (RangeType &&Range, const ValueType &Value, ProjectionType Proj)
template<typename RangeType, typename PredicateType>
TRangePointerType< typenameTRemoveReference< RangeType >::Type >::Type FindByPredicate (RangeType &&Range, PredicateType Pred)
template<typename T, typename ValueType, typename ProjectionType>
T * FindLastBy (T *First, SIZE_T Num, const ValueType &Value, ProjectionType Proj)
template<typename T, typename PredicateType>
T * FindLastByPredicate (T *First, SIZE_T Num, PredicateType Pred)
const TSet< FKahnHandle > & FindMostIndependentMutuallyReachableVertexSet (FKahnContext &Context)
Called when there is a MutuallyReachableVertexSet (aka no vertices are independent).
template<typename WhereType, typename WhatType>
constexpr WhereType * FindSequence (WhereType *First, WhereType *Last, WhatType *WhatFirst, WhatType *WhatLast)
template<typename IndexType>
FORCEINLINE IndexType HeapGetLeftChildIndex (IndexType Index)
Gets the index of the left child of node at Index.
template<typename IndexType>
FORCEINLINE IndexType HeapGetParentIndex (IndexType Index)
Gets the parent index for node at Index.
template<typename RangeValueType, typename IndexType, typename ProjectionType, typename PredicateType>
FORCEINLINE void HeapifyInternal (RangeValueType *First, IndexType Num, ProjectionType Proj, PredicateType Predicate)
Builds an implicit min-heap from a range of elements.
template<typename IndexType>
FORCEINLINE bool HeapIsLeaf (IndexType Index, IndexType Count)
Checks if node located at Index is a leaf or not.
template<typename RangeValueType, typename IndexType, typename ProjectionType, typename PredicateType>
FORCEINLINE void HeapSiftDown (RangeValueType *Heap, IndexType Index, const IndexType Count, const ProjectionType &InProj, const PredicateType &Predicate)
Fixes a possible violation of order property between node at Index and a child.
template<class RangeValueType, typename IndexType, typename ProjectionType, class PredicateType>
FORCEINLINE IndexType HeapSiftUp (RangeValueType *Heap, IndexType RootIndex, IndexType NodeIndex, const ProjectionType &InProj, const PredicateType &Predicate)
Fixes a possible violation of order property between node at NodeIndex and a parent.
template<typename RangeValueType, typename IndexType, typename ProjectionType, class PredicateType>
void HeapSortInternal (RangeValueType *First, IndexType Num, ProjectionType Proj, PredicateType Predicate)
Performs heap sort on the elements.
template<typename RangeType, typename ValueType, typename ProjectionType>
auto IndexOfBy (const RangeType &Range, const ValueType &Value, ProjectionType Proj)
template<typename RangeType, typename PredicateType>
auto IndexOfByPredicate (const RangeType &Range, PredicateType Pred)
template<typename T, typename IndexType, typename ProjectionType, typename PredicateType>
void IntroSortInternal (T *First, IndexType Num, ProjectionType Proj, PredicateType Predicate)
Implementation of an introspective sort.
template<typename RangeValueType, typename IndexType, typename ProjectionType, typename PredicateType>
bool IsHeapInternal (const RangeValueType *Heap, IndexType Num, ProjectionType Projection, PredicateType Predicate)
Verifies that the range is a min-heap (parent <= child) This is the internal function used by IsHeap overrides.
template<typename T, typename IndexType, typename ProjectionType, typename PredType>
bool IsSortedBy (const T *Range, IndexType RangeSize, ProjectionType Proj, PredType Pred)
template<typename RangeType, typename GetElementDependenciesType>
void KahnTopologicalSort_CreateWorkingGraph (FKahnContext &Context, RangeType &UniqueRange, GetElementDependenciesType GetElementDependencies, TSet< FKahnHandle > &OutInitialIndependents)
Convert UniqueRange and GetElementDependencies into handles, dependency count, dependencies, and referencers.
template<typename T, typename ProjectionType, typename PredicateType>
void LegacySortInternal (T *First, int32 Num, ProjectionType Projection, PredicateType Predicate)
Sort elements using user defined predicate class.
template<typename RangeValueType, typename SizeType, typename PredicateValueType, typename ProjectionType, typename SortPredicateType>
FORCEINLINE SizeType LowerBoundInternal (RangeValueType *First, const SizeType Num, const PredicateValueType &Value, ProjectionType Projection, SortPredicateType SortPredicate)
Performs binary search, resulting in position of the first element >= Value.
template<typename RangeType, typename ProjectionType, typename PredicateType>
TRangePointerType< RangeType >::Type MaxElementBy (RangeType &Range, ProjectionType Proj, PredicateType Pred)
template<typename T, typename ProjectionType, typename PredicateType>
void Merge (T *First, int32 Mid, int32 Num, ProjectionType Projection, PredicateType Predicate)
template<typename RangeType, typename ProjectionType, typename PredicateType>
TRangePointerType< RangeType >::Type MinElementBy (RangeType &Range, ProjectionType Proj, PredicateType Pred)
template<typename T>
FORCEINLINE void Reverse (T *Array, int32 ArraySize)
template<typename T>
int32 RotateInternal (T *First, int32 Num, int32 Count)
template<typename RangeType, typename ProjectionType>
TRangePointerType< typenameTRemoveReference< RangeType >::Type >::Type SelectRandomWeightedBy (RangeType &&Range, ProjectionType Proj)
template<typename T, typename ProjectionType, typename PredicateType>
void StableSortInternal (T *First, int32 Num, ProjectionType Projection, PredicateType Predicate)
Sort elements using user defined projection and predicate classes.
template<typename T, typename SizeType, typename ProjectionType, typename BinaryPredicate>
SizeType Unique (T *Array, SizeType ArraySize, ProjectionType Proj, BinaryPredicate Predicate)
template<typename RangeValueType, typename SizeType, typename PredicateValueType, typename ProjectionType, typename SortPredicateType>
FORCEINLINE SizeType UpperBoundInternal (RangeValueType *First, const SizeType Num, const PredicateValueType &Value, ProjectionType Projection, SortPredicateType SortPredicate)
Performs binary search, resulting in position of the first element that is larger than the given value.
Variables
constexpr int32 MinMergeSubgroupSize = 2
Typedef Documentation
FKahnHandle
typedef int32 AlgoImpl::FKahnHandle
KahnTopologicalSort converts vertices and edges from ElementType to indexes of the vertex in the original UniqueRange of ElementType.
FKahnHandle is how vertices are represented during the graph algorithm
Definition at line 22 of file KahnTopologicalSort.h.
Function Documentation
FindBy()
template<typename RangeType, typename ValueType, typename ProjectionType> TRangePointerType< typenameTRemoveReference< RangeType >::Type >::Type AlgoImpl::FindBy (RangeType && Range, const ValueType & Value, ProjectionType Proj)
Definition at line 13 of file Find.h.
References Forward(), Invoke(), and Value.
Referenced by Algo::Find(), and Algo::FindBy().
FindByPredicate()
template<typename RangeType, typename PredicateType> TRangePointerType< typenameTRemoveReference< RangeType >::Type >::Type AlgoImpl::FindByPredicate (RangeType && Range, PredicateType Pred)
Definition at line 27 of file Find.h.
References Forward(), and Invoke().
Referenced by Algo::FindByPredicate().
FindLastBy()
template<typename T, typename ValueType, typename ProjectionType> T * AlgoImpl::FindLastBy (T * First, SIZE_T Num, const ValueType & Value, ProjectionType Proj)
Definition at line 12 of file FindLast.h.
References First, Invoke(), Last, Num, and Value.
Referenced by Algo::FindLast(), and Algo::FindLastBy().
FindLastByPredicate()
template<typename T, typename PredicateType> T * AlgoImpl::FindLastByPredicate (T * First, SIZE_T Num, PredicateType Pred)
Definition at line 26 of file FindLast.h.
References First, Invoke(), Last, and Num.
Referenced by Algo::FindLastByPredicate().
FindMostIndependentMutuallyReachableVertexSet()
const TSet< FKahnHandle > & AlgoImpl::FindMostIndependentMutuallyReachableVertexSet (FKahnContext & Context) inline
Called when there is a MutuallyReachableVertexSet (aka no vertices are independent).
It returns the most-independent maximal MutuallyReachableVertexSet.
Definition at line 225 of file KahnTopologicalSort.h.
References TArray< InElementType, InAllocatorType >::Add(), TSet< InElementType, KeyFuncs, Allocator >::Add(), TSet< InElementType, KeyFuncs, Allocator >::Append(), check, checkf, TSet< InElementType, KeyFuncs, Allocator >::Contains(), TSet< InElementType, KeyFuncs, Allocator >::CreateIterator(), AlgoImpl::FMutuallyReachableVertexSetContext::Culprits, AlgoImpl::FMutuallyReachableVertexSetContext::Cycle, INDEX_NONE, TSet< InElementType, KeyFuncs, Allocator >::Intersect(), TArray< InElementType, InAllocatorType >::IsEmpty(), TSet< InElementType, KeyFuncs, Allocator >::IsEmpty(), AlgoImpl::FMutuallyReachableVertexSetContext::MaximalMRVS, No, TArray< InElementType, InAllocatorType >::Num(), TArray< InElementType, InAllocatorType >::Pop(), TSet< InElementType, KeyFuncs, Allocator >::Remove(), TArray< InElementType, InAllocatorType >::Reserve(), TSet< InElementType, KeyFuncs, Allocator >::Reserve(), TArray< InElementType, InAllocatorType >::Reset(), TSet< InElementType, KeyFuncs, Allocator >::Reset(), AlgoImpl::FMutuallyReachableVertexSetContext::Stack, TEXT, Vertex, AlgoImpl::FMutuallyReachableVertexSetContext::VisitedDependencies, and AlgoImpl::FMutuallyReachableVertexSetContext::VisitedReferences.
Referenced by Algo::KahnTopologicalSort().
FindSequence()
template<typename WhereType, typename WhatType> WhereType * AlgoImpl::FindSequence (WhereType * First, WhereType * Last, WhatType * WhatFirst, WhatType * WhatLast) constexpr
Definition at line 10 of file FindSequence.h.
References First, and Last.
Referenced by Algo::FindSequence().
HeapGetLeftChildIndex()
template<typename IndexType> FORCEINLINE IndexType AlgoImpl::HeapGetLeftChildIndex (IndexType Index)
Gets the index of the left child of node at Index.
Parameters
Index Node for which the left child index is to be returned.
Returns
Index of the left child.
Definition at line 20 of file BinaryHeap.h.
References FORCEINLINE.
Referenced by HeapIsLeaf(), and HeapSiftDown().
HeapGetParentIndex()
template<typename IndexType> FORCEINLINE IndexType AlgoImpl::HeapGetParentIndex (IndexType Index)
Gets the parent index for node at Index.
Parameters
Index node index.
Returns
Parent index.
Definition at line 44 of file BinaryHeap.h.
References FORCEINLINE.
Referenced by HeapifyInternal(), HeapSiftUp(), and IsHeapInternal().
HeapifyInternal()
template<typename RangeValueType, typename IndexType, typename ProjectionType, typename PredicateType> FORCEINLINE void AlgoImpl::HeapifyInternal (RangeValueType * First, IndexType Num, ProjectionType Proj, PredicateType Predicate)
Builds an implicit min-heap from a range of elements.
This is the internal function used by Heapify overrides.
Parameters
First pointer to the first element to heapify
Num the number of items to heapify
Proj The projection to apply to the elements.
Predicate A binary predicate object used to specify if one element should precede another.
Definition at line 147 of file BinaryHeap.h.
References checkf, First, FORCEINLINE, HeapGetParentIndex(), HeapSiftDown(), Num, Predicate, and TEXT.
Referenced by Algo::Heapify(), Algo::Heapify(), Algo::HeapifyBy(), Algo::HeapifyBy(), and HeapSortInternal().
HeapIsLeaf()
template<typename IndexType> FORCEINLINE bool AlgoImpl::HeapIsLeaf (IndexType Index, IndexType Count)
Checks if node located at Index is a leaf or not.
Parameters
Index Node index.
Returns
true if node is a leaf, false otherwise.
Definition at line 32 of file BinaryHeap.h.
References Count, FORCEINLINE, and HeapGetLeftChildIndex().
Referenced by HeapSiftDown().
HeapSiftDown()
template<typename RangeValueType, typename IndexType, typename ProjectionType, typename PredicateType> FORCEINLINE void AlgoImpl::HeapSiftDown (RangeValueType * Heap, IndexType Index, const IndexType Count, const ProjectionType & InProj, const PredicateType & Predicate)
Fixes a possible violation of order property between node at Index and a child.
Parameters
Heap Pointer to the first element of a binary heap.
Index Node index.
Count Size of the heap.
InProj The projection to apply to the elements.
Predicate A binary predicate object used to specify if one element should precede another.
Definition at line 59 of file BinaryHeap.h.
References Count, FORCEINLINE, Heap, HeapGetLeftChildIndex(), HeapIsLeaf(), Invoke(), Predicate, Projection(), and Swap.
Referenced by HeapifyInternal(), RangedForIteratorType< FAnimNextTraitEventPtr >::HeapPop(), RangedForIteratorType< FAnimNextTraitEventPtr >::HeapPopDiscard(), RangedForIteratorType< FAnimNextTraitEventPtr >::HeapRemoveAt(), and HeapSortInternal().
HeapSiftUp()
template<class RangeValueType, typename IndexType, typename ProjectionType, class PredicateType> FORCEINLINE IndexType AlgoImpl::HeapSiftUp (RangeValueType * Heap, IndexType RootIndex, IndexType NodeIndex, const ProjectionType & InProj, const PredicateType & Predicate)
Fixes a possible violation of order property between node at NodeIndex and a parent.
Parameters
Heap Pointer to the first element of a binary heap.
RootIndex How far to go up?
NodeIndex Node index.
InProj The projection to apply to the elements.
Predicate A binary predicate object used to specify if one element should precede another.
Returns
The new index of the node that was at NodeIndex
Definition at line 109 of file BinaryHeap.h.
References FORCEINLINE, Heap, HeapGetParentIndex(), Invoke(), Predicate, Projection(), and Swap.
Referenced by RangedForIteratorType< FAnimNextTraitEventPtr >::HeapPush(), RangedForIteratorType< FAnimNextTraitEventPtr >::HeapPush(), RangedForIteratorType< FAnimNextTraitEventPtr >::HeapRemoveAt(), and FGraphAStar< TGraph, Policy, TSearchNode, DoRangeCheck >::FOpenList::Modify().
HeapSortInternal()
template<typename RangeValueType, typename IndexType, typename ProjectionType, class PredicateType> void AlgoImpl::HeapSortInternal (RangeValueType * First, IndexType Num, ProjectionType Proj, PredicateType Predicate)
Performs heap sort on the elements.
This is the internal sorting function used by HeapSort overrides.
Parameters
First pointer to the first element to sort
Num the number of elements to sort
Proj The projection to apply to the elements.
Predicate A binary predicate object used to specify if one element should precede another.
Definition at line 181 of file BinaryHeap.h.
References checkf, First, HeapifyInternal(), HeapSiftDown(), Num, Predicate, Swap, and TEXT.
Referenced by Algo::HeapSort(), Algo::HeapSort(), Algo::HeapSortBy(), Algo::HeapSortBy(), and IntroSortInternal().
IndexOfBy()
template<typename RangeType, typename ValueType, typename ProjectionType> auto AlgoImpl::IndexOfBy (const RangeType & Range, const ValueType & Value, ProjectionType Proj)
Definition at line 12 of file IndexOf.h.
References GetData(), GetNum(), Invoke(), Num, and Value.
Referenced by Algo::IndexOf(), and Algo::IndexOfBy().
IndexOfByPredicate()
template<typename RangeType, typename PredicateType> auto AlgoImpl::IndexOfByPredicate (const RangeType & Range, PredicateType Pred)
Definition at line 30 of file IndexOf.h.
References GetData(), GetNum(), Invoke(), and Num.
Referenced by Algo::IndexOfByPredicate().
IntroSortInternal()
template<typename T, typename IndexType, typename ProjectionType, typename PredicateType> void AlgoImpl::IntroSortInternal (T * First, IndexType Num, ProjectionType Proj, PredicateType Predicate)
Implementation of an introspective sort.
Starts with quick sort and switches to heap sort when the iteration depth is too big. The sort is unstable, meaning that the ordering of equal items is not necessarily preserved. This is the internal sorting function used by IntroSort overrides.
Parameters
First pointer to the first element to sort
Num the number of items to sort
Proj The projection to sort by when applied to the element.
Predicate predicate class
Definition at line 27 of file IntroSort.h.
References Count, First, HeapSortInternal(), Invoke(), Item, Max, Num, Predicate, and Swap.
Referenced by Algo::IntroSort(), Algo::IntroSort(), Algo::IntroSortBy(), and Algo::IntroSortBy().
IsHeapInternal()
template<typename RangeValueType, typename IndexType, typename ProjectionType, typename PredicateType> bool AlgoImpl::IsHeapInternal (const RangeValueType * Heap, IndexType Num, ProjectionType Projection, PredicateType Predicate)
Verifies that the range is a min-heap (parent <= child) This is the internal function used by IsHeap overrides.
Parameters
Heap Pointer to the first element of a binary heap.
Num the number of items in the heap.
Projection The projection to apply to the elements.
Predicate A binary predicate object used to specify if one element should precede another.
Returns
returns true if the range is a min-heap
Definition at line 25 of file IsHeap.h.
References Heap, HeapGetParentIndex(), Invoke(), Num, Predicate, and Projection().
Referenced by Algo::IsHeap(), Algo::IsHeap(), Algo::IsHeapBy(), and Algo::IsHeapBy().
IsSortedBy()
template<typename T, typename IndexType, typename ProjectionType, typename PredType> bool AlgoImpl::IsSortedBy (const T * Range, IndexType RangeSize, ProjectionType Proj, PredType Pred)
Definition at line 15 of file IsSorted.h.
References Invoke().
Referenced by Algo::IsSorted(), Algo::IsSorted(), Algo::IsSortedBy(), and Algo::IsSortedBy().
KahnTopologicalSort_CreateWorkingGraph()
template<typename RangeType, typename GetElementDependenciesType> void AlgoImpl::KahnTopologicalSort_CreateWorkingGraph (FKahnContext & Context, RangeType & UniqueRange, GetElementDependenciesType GetElementDependencies, TSet< FKahnHandle > & OutInitialIndependents) inline
Convert UniqueRange and GetElementDependencies into handles, dependency count, dependencies, and referencers.
Definition at line 167 of file KahnTopologicalSort.h.
References TArray< InElementType, InAllocatorType >::Add(), TSet< InElementType, KeyFuncs, Allocator >::Add(), check, TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Find(), TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::FindOrAdd(), GetNum(), Handle, INDEX_NONE, Invoke(), No, TArray< InElementType, InAllocatorType >::Num(), TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Reserve(), TArray< InElementType, InAllocatorType >::SetNum(), and Algo::Sort().
Referenced by Algo::KahnTopologicalSort().
LegacySortInternal()
template<typename T, typename ProjectionType, typename PredicateType> void AlgoImpl::LegacySortInternal (T * First, int32 Num, ProjectionType Projection, PredicateType Predicate)
Sort elements using user defined predicate class.
The sort is unstable, meaning that the ordering of equal items is not necessarily preserved. This is the internal sorting function used by Sort overrides. This used to be Algo::Sort and is now considered legacy.
Parameters
First pointer to the first element to sort
Num the number of items to sort
Predicate predicate class
Definition at line 23 of file LegacySort.h.
References Count, First, Invoke(), Item, Max, Num, Predicate, Projection(), and Swap.
Referenced by Algo::LegacySort(), Algo::LegacySort(), Algo::LegacySortBy(), and Algo::LegacySortBy().
LowerBoundInternal()
template<typename RangeValueType, typename SizeType, typename PredicateValueType, typename ProjectionType, typename SortPredicateType> FORCEINLINE SizeType AlgoImpl::LowerBoundInternal (RangeValueType * First, const SizeType Num, const PredicateValueType & Value, ProjectionType Projection, SortPredicateType SortPredicate)
Performs binary search, resulting in position of the first element >= Value.
Parameters
First Pointer to array
Num Number of elements in array
Value Value to look for
Projection Called on values in array to get type that can be compared to Value
SortPredicate Predicate for sort comparison
Returns
Position of the first element >= Value, may be == Num
Definition at line 23 of file BinarySearch.h.
References First, FORCEINLINE, Invoke(), Num, Projection(), TSequenceHistory< HistorySize >::Size, and Value.
Referenced by Algo::LowerBound(), Algo::LowerBound(), Algo::LowerBoundBy(), Algo::LowerBoundBy(), Merge(), and TRotationInPlaceMerge< TRotationPolicy >::Merge().
MaxElementBy()
template<typename RangeType, typename ProjectionType, typename PredicateType> TRangePointerType< RangeType >::Type AlgoImpl::MaxElementBy (RangeType & Range, ProjectionType Proj, PredicateType Pred)
Definition at line 14 of file MaxElement.h.
References Invoke().
Referenced by Algo::MaxElement(), Algo::MaxElement(), Algo::MaxElementBy(), and Algo::MaxElementBy().
Merge()
template<typename T, typename ProjectionType, typename PredicateType> void AlgoImpl::Merge (T * First, int32 Mid, int32 Num, ProjectionType Projection, PredicateType Predicate)
Definition at line 16 of file StableSort.h.
References First, Invoke(), LowerBoundInternal(), Num, Predicate, Projection(), RotateInternal(), and UpperBoundInternal().
MinElementBy()
template<typename RangeType, typename ProjectionType, typename PredicateType> TRangePointerType< RangeType >::Type AlgoImpl::MinElementBy (RangeType & Range, ProjectionType Proj, PredicateType Pred)
Definition at line 14 of file MinElement.h.
References Invoke().
Referenced by Algo::MinElement(), Algo::MinElement(), Algo::MinElementBy(), and Algo::MinElementBy().
Reverse()
template<typename T> FORCEINLINE void AlgoImpl::Reverse (T * Array, int32 ArraySize)
Definition at line 11 of file Reverse.h.
References Array, FORCEINLINE, and Swap.
Referenced by Algo::Reverse(), Algo::Reverse(), and Algo::Reverse().
RotateInternal()
template<typename T> int32 AlgoImpl::RotateInternal (T * First, int32 Num, int32 Count)
Definition at line 11 of file Rotate.h.
References Count, End, First, Num, and Swap.
Referenced by Merge(), and Algo::Rotate().
SelectRandomWeightedBy()
template<typename RangeType, typename ProjectionType> TRangePointerType< typenameTRemoveReference< RangeType >::Type >::Type AlgoImpl::SelectRandomWeightedBy (RangeType && Range, ProjectionType Proj) nodiscard
Definition at line 15 of file SelectRandomWeighted.h.
References Algo::Accumulate(), Forward(), Invoke(), and Weight.
Referenced by Algo::SelectRandomWeightedBy().
StableSortInternal()
template<typename T, typename ProjectionType, typename PredicateType> void AlgoImpl::StableSortInternal (T * First, int32 Num, ProjectionType Projection, PredicateType Predicate)
Sort elements using user defined projection and predicate classes.
The sort is stable, meaning that the ordering of equal items is preserved. This is the internal sorting function used by the Algo::Sort overloads.
Parameters
First Pointer to the first element to sort.
Num The number of items to sort.
Projection A projection to apply to each element to get the value to sort by.
Predicate A predicate class which compares two projected elements and returns whether one occurs before the other.
Definition at line 50 of file StableSort.h.
References First, Invoke(), Merge, MinMergeSubgroupSize, Num, Predicate, Projection(), and Swap.
Referenced by Algo::StableSort(), Algo::StableSort(), Algo::StableSortBy(), and Algo::StableSortBy().
Unique()
template<typename T, typename SizeType, typename ProjectionType, typename BinaryPredicate> SizeType AlgoImpl::Unique (T * Array, SizeType ArraySize, ProjectionType Proj, BinaryPredicate Predicate)
Definition at line 13 of file Unique.h.
References Array, Invoke(), MoveTemp(), and Predicate.
UpperBoundInternal()
template<typename RangeValueType, typename SizeType, typename PredicateValueType, typename ProjectionType, typename SortPredicateType> FORCEINLINE SizeType AlgoImpl::UpperBoundInternal (RangeValueType * First, const SizeType Num, const PredicateValueType & Value, ProjectionType Projection, SortPredicateType SortPredicate)
Performs binary search, resulting in position of the first element that is larger than the given value.
Parameters
First Pointer to array
Num Number of elements in array
Value Value to look for
SortPredicate Predicate for sort comparison
Returns
Position of the first element > Value, may be == Num
Definition at line 56 of file BinarySearch.h.
References First, FORCEINLINE, Invoke(), Num, Projection(), TSequenceHistory< HistorySize >::Size, and Value.
Referenced by Merge(), TRotationInPlaceMerge< TRotationPolicy >::Merge(), Algo::UpperBound(), Algo::UpperBound(), Algo::UpperBoundBy(), and Algo::UpperBoundBy().
Variable Documentation
MinMergeSubgroupSize
int32 AlgoImpl::MinMergeSubgroupSize = 2 inline constexpr
Definition at line 38 of file StableSort.h.
Referenced by StableSortInternal().