Unreal Engine 5.6 C++ API: UE::StateTree::PropertyRefHelpers Namespace Reference
UE::StateTree::PropertyRefHelpers Namespace Reference
Data Structures
struct Validator
struct Validator< FBoolProperty::TCppType >
struct Validator< FByteProperty::TCppType >
struct Validator< FDoubleProperty::TCppType >
struct Validator< FFloatProperty::TCppType >
struct Validator< FInt64Property::TCppType >
struct Validator< FIntProperty::TCppType >
struct Validator< FNameProperty::TCppType >
struct Validator< FStrProperty::TCppType >
struct Validator< FTextProperty::TCppType >
struct Validator< T, decltype(TBaseStructure< T >::Get, void())>
struct Validator< T, typename TEnableIf< TIsDerivedFrom< typename TRemovePointer< T >::Type, UObject >::IsDerived >::Type >
struct Validator< T, typename TEnableIf< TIsEnum< T >::Value >::Type >
struct Validator< T, typename TEnableIf< TIsTArray_V< T >, void >::Type >
struct Validator< void >
Functions
FEdGraphPinType STATETREEMODULE_API GetBlueprintPropertyRefInternalTypeAsPin (const FStateTreeBlueprintPropertyRef &InPropertyRef)
void STATETREEMODULE_API GetBlueprintPropertyRefInternalTypeFromPin (const FEdGraphPinType &PinType, EStateTreePropertyRefType &OutRefType, bool &bOutIsArray, UObject *&OutObjectType)
template<class T>
static T * GetMutablePtrToProperty (const FStateTreePropertyRef &PropertyRef, FStateTreeInstanceStorage &InstanceDataStorage, const FStateTreeExecutionFrame &ExecutionFrame, const FStateTreeExecutionFrame *ParentExecutionFrame, const FProperty **OutSourceProperty=nullptr)
template<class... T>
static TTuple< T *... > GetMutablePtrTupleToProperty (const FStateTreePropertyRef &PropertyRef, FStateTreeInstanceStorage &InstanceDataStorage, const FStateTreeExecutionFrame &ExecutionFrame, const FStateTreeExecutionFrame *ParentExecutionFrame)
FEdGraphPinType STATETREEMODULE_API GetPropertyRefInternalTypeAsPin (const FProperty &RefProperty, const void *PropertyRefAddress)
TArray< FEdGraphPinType, TInlineAllocator< 1 > > STATETREEMODULE_API GetPropertyRefInternalTypesAsPins (const FProperty &RefProperty)
bool STATETREEMODULE_API IsBlueprintPropertyRefCompatibleWithProperty (const FProperty &SourceProperty, const void *PropertyRefAddress)
bool STATETREEMODULE_API IsPropertyAccessibleForPropertyRef (const FProperty &SourceProperty, TConstArrayView< FBindingChainElement > BindingChain, FStateTreeBindableStructDesc SourceStruct)
bool STATETREEMODULE_API IsPropertyAccessibleForPropertyRef (TConstArrayView< FPropertyBindingPathIndirection > SourcePropertyPathIndirections, FStateTreeBindableStructDesc SourceStruct)
bool STATETREEMODULE_API IsPropertyCompatibleWithClass (const FProperty &Property, const class UClass &Class)
bool STATETREEMODULE_API IsPropertyCompatibleWithEnum (const FProperty &Property, const class UEnum &Enum)
bool STATETREEMODULE_API IsPropertyCompatibleWithStruct (const FProperty &Property, const class UScriptStruct &Struct)
bool STATETREEMODULE_API IsPropertyRef (const FProperty &Property)
bool STATETREEMODULE_API IsPropertyRefCompatibleWithProperty (const FProperty &RefProperty, const FProperty &SourceProperty, const void *PropertyRefAddress, const void *SourceAddress)
bool STATETREEMODULE_API IsPropertyRefMarkedAsOptional (const FProperty &RefProperty, const void *PropertyRefAddress)
UE_DEPRECATED (5.6, "Use the overload taking FPropertyBindingPathIndirection instead") bool STATETREEMODULE_API IsPropertyAccessibleForPropertyRef(TConstArrayView< FStateTreePropertyPathIndirection > SourcePropertyPathIndirections
Variables
STATETREEMODULE_API const FName CanRefToArrayName
STATETREEMODULE_API const FName IsRefToArrayName
STATETREEMODULE_API const FName RefTypeName
FStateTreeBindableStructDesc SourceStruct
Function Documentation
GetBlueprintPropertyRefInternalTypeAsPin()
FEdGraphPinType STATETREEMODULE_API UE::StateTree::PropertyRefHelpers::GetBlueprintPropertyRefInternalTypeAsPin (const FStateTreeBlueprintPropertyRef & InPropertyRef)
Parameters
InPropertyRef PropertyRef to get internal type from.
Returns
PinType for Blueprint PropertyRef's internal type
References GetBlueprintPropertyRefInternalTypeAsPin().
Referenced by GetBlueprintPropertyRefInternalTypeAsPin().
GetBlueprintPropertyRefInternalTypeFromPin()
void STATETREEMODULE_API UE::StateTree::PropertyRefHelpers::GetBlueprintPropertyRefInternalTypeFromPin (const FEdGraphPinType & PinType, EStateTreePropertyRefType & OutRefType, bool & bOutIsArray, UObject *& OutObjectType)
Parameters
PinType Pin to get type from.
OutRefType PropertyRef's referenced type.
bOutIsArray True if PropertyRef references an array property.
OutObjectType Referenced type's specific object.
References GetBlueprintPropertyRefInternalTypeFromPin().
Referenced by GetBlueprintPropertyRefInternalTypeFromPin().
GetMutablePtrToProperty()
template<class T> T * UE::StateTree::PropertyRefHelpers::GetMutablePtrToProperty (const FStateTreePropertyRef & PropertyRef, FStateTreeInstanceStorage & InstanceDataStorage, const FStateTreeExecutionFrame & ExecutionFrame, const FStateTreeExecutionFrame * ParentExecutionFrame, const FProperty ** OutSourceProperty = nullptr) static
Parameters
PropertyRef Property's reference to get pointer to.
InstanceDataStorage Instance Data Storage.
ExecutionFrame Execution frame owning referenced property.
ParentExecutionFrame Parent of execution frame owning referenced property.
OutSourceProperty On success, returns referenced property.
Returns
Pointer to referenced property value if succeeded.
Definition at line 26 of file StateTreePropertyRef.h.
References check, FStateTreeExecutionContext::FindFrame(), UE::StateTree::InstanceData::GetDataViewOrTemporary(), GetMutablePtrToProperty(), and IsPropertyRef().
Referenced by GetMutablePtrToProperty(), and USTRUCT().
GetMutablePtrTupleToProperty()
template<class... T> TTuple< T *... > UE::StateTree::PropertyRefHelpers::GetMutablePtrTupleToProperty (const FStateTreePropertyRef & PropertyRef, FStateTreeInstanceStorage & InstanceDataStorage, const FStateTreeExecutionFrame & ExecutionFrame, const FStateTreeExecutionFrame * ParentExecutionFrame) static
Parameters
PropertyRef Property's reference to get pointer to.
InstanceDataStorage Instance Data Storage
ExecutionFrame Execution frame owning referenced property
ParentExecutionFrame Parent of execution frame owning referenced property
Returns
A tuple of pointer to referenced property if succeeded.
Definition at line 85 of file StateTreePropertyRef.h.
References UE::StateTree::InstanceData::GetDataViewOrTemporary().
Referenced by FStateTreePropertyRefExternalHandle::GetMutablePtrTuple(), and USTRUCT().
GetPropertyRefInternalTypeAsPin()
FEdGraphPinType STATETREEMODULE_API UE::StateTree::PropertyRefHelpers::GetPropertyRefInternalTypeAsPin (const FProperty & RefProperty, const void * PropertyRefAddress)
Parameters
RefProperty Property of PropertyRef type
PropertyRefAddress Address of PropertyRef.
Returns
PinType for PropertyRef's internal type
References GetPropertyRefInternalTypeAsPin().
Referenced by GetPropertyRefInternalTypeAsPin().
GetPropertyRefInternalTypesAsPins()
TArray< FEdGraphPinType, TInlineAllocator< 1 > > STATETREEMODULE_API UE::StateTree::PropertyRefHelpers::GetPropertyRefInternalTypesAsPins (const FProperty & RefProperty)
Parameters
RefProperty Property of PropertyRef type
Returns
PinTypes for PropertyRef's internal types
References GetPropertyRefInternalTypesAsPins().
Referenced by GetPropertyRefInternalTypesAsPins().
IsBlueprintPropertyRefCompatibleWithProperty()
bool STATETREEMODULE_API UE::StateTree::PropertyRefHelpers::IsBlueprintPropertyRefCompatibleWithProperty (const FProperty & SourceProperty, const void * PropertyRefAddress)
Parameters
SourceProperty Property to check it's type compatibility.
PropertyRefAddress Address of PropertyRef
Returns
true if SourceProperty type is compatible with Blueprint PropertyRef.
IsPropertyAccessibleForPropertyRef() [1/2]
bool STATETREEMODULE_API UE::StateTree::PropertyRefHelpers::IsPropertyAccessibleForPropertyRef (const FProperty & SourceProperty, TConstArrayView< FBindingChainElement > BindingChain, FStateTreeBindableStructDesc SourceStruct)
Parameters
SourceProperty Referenced property.
BindingChain Binding chain to referenced property.
SourceStruct Bindable owner of referenced property.
Returns
true if property can be referenced by PropertyRef.
References IsPropertyAccessibleForPropertyRef(), and SourceStruct.
IsPropertyAccessibleForPropertyRef() [2/2]
bool STATETREEMODULE_API UE::StateTree::PropertyRefHelpers::IsPropertyAccessibleForPropertyRef (TConstArrayView< FPropertyBindingPathIndirection > SourcePropertyPathIndirections, FStateTreeBindableStructDesc SourceStruct)
Parameters
SourcePropertyPathIndirections Path indirections of the referenced property.
SourceStruct Bindable owner of referenced property.
Returns
true if property can be referenced by PropertyRef.
References SourceStruct.
Referenced by IsPropertyAccessibleForPropertyRef().
IsPropertyCompatibleWithClass()
bool STATETREEMODULE_API UE::StateTree::PropertyRefHelpers::IsPropertyCompatibleWithClass (const FProperty & Property, const class UClass & Class)
References Class, and Property.
IsPropertyCompatibleWithEnum()
bool STATETREEMODULE_API UE::StateTree::PropertyRefHelpers::IsPropertyCompatibleWithEnum (const FProperty & Property, const class UEnum & Enum)
References Enum, and Property.
IsPropertyCompatibleWithStruct()
bool STATETREEMODULE_API UE::StateTree::PropertyRefHelpers::IsPropertyCompatibleWithStruct (const FProperty & Property, const class UScriptStruct & Struct)
References Property, and Struct.
IsPropertyRef()
bool STATETREEMODULE_API UE::StateTree::PropertyRefHelpers::IsPropertyRef (const FProperty & Property)
Parameters
Property Property to check
Returns
true if Property is a PropertyRef
References Property.
Referenced by GetMutablePtrToProperty().
IsPropertyRefCompatibleWithProperty()
bool STATETREEMODULE_API UE::StateTree::PropertyRefHelpers::IsPropertyRefCompatibleWithProperty (const FProperty & RefProperty, const FProperty & SourceProperty, const void * PropertyRefAddress, const void * SourceAddress)
Parameters
RefProperty Property of PropertyRef type.
SourceProperty Property to check its type compatibility.
PropertyRefAddress Address of PropertyRef
SourceAddress Address of checked property value.
Returns
true if SourceProperty type is compatible with PropertyRef.
IsPropertyRefMarkedAsOptional()
bool STATETREEMODULE_API UE::StateTree::PropertyRefHelpers::IsPropertyRefMarkedAsOptional (const FProperty & RefProperty, const void * PropertyRefAddress)
Parameters
RefProperty Property of PropertyRef type.
PropertyRefAddress Address of PropertyRef.
Returns
true if PropertyRef is marked as optional.
References IsPropertyRefMarkedAsOptional().
Referenced by IsPropertyRefMarkedAsOptional().
UE_DEPRECATED()
UE::StateTree::PropertyRefHelpers::UE_DEPRECATED (5. 6, "Use the overload taking FPropertyBindingPathIndirection instead")
Variable Documentation
CanRefToArrayName
STATETREEMODULE_API const FName UE::StateTree::PropertyRefHelpers::CanRefToArrayName extern
IsRefToArrayName
STATETREEMODULE_API const FName UE::StateTree::PropertyRefHelpers::IsRefToArrayName extern
RefTypeName
STATETREEMODULE_API const FName UE::StateTree::PropertyRefHelpers::RefTypeName extern
SourceStruct
FStateTreeBindableStructDesc UE::StateTree::PropertyRefHelpers::SourceStruct
Definition at line 45 of file StateTreePropertyRefHelpers.h.
Referenced by IsPropertyAccessibleForPropertyRef(), and IsPropertyAccessibleForPropertyRef().