Unreal Engine 5.6 C++ API: UE::Core::Private Namespace Reference
UE::Core::Private Namespace Reference
TAdderRef and TAdderReserverRef are type-erasing adapters that allow a function to add to (and reserve) a container without the function knowing about the specific type of the container.
Namespaces
namespace Atomic
namespace Decay
namespace ElementType
namespace FormatStringSan
namespace Function
Private implementation details of TFunction and TFunctionRef.
namespace IsEnumClass
namespace IsInvocable
namespace MemoryOps
namespace PimplPtr
namespace PointerIsConvertibleFromTo
namespace Tuple
namespace Unsafe
Data Structures
struct CIntCallable
struct CIntrusiveUnsettable
struct FCountingOutputIterator
This is a basic object which counts how many times it has been incremented.
struct FFromStrCast
class FPlayInEditorLoadingScope
struct FSharedFromThisBase
struct FSharedRecursiveMutexLink
class FTCHARToUTF8_Convert
struct TAdderReserverVTable
struct TAdderReserverVTableImpl
struct TAdderVTable
struct TAdderVTableImpl
struct TAlwaysFArchive
A shim to get at FArchive through a dependent name, allowing TVariant.h to not include Archive.h.
struct TContainsReferenceType
Determine if any of the types in a template parameter pack are references.
struct TCopyConstructorCaller
An adapter for calling a copy constructor of a type.
struct TCopyConstructorLookup
A utility for calling a type's copy constructor based on an index into a template parameter pack.
struct TDestructibleVariantStorage
struct TDestructorCaller
An adapter for calling DestructItem.
struct TDestructorLookup
Lookup a type in a template parameter pack by its index and call the destructor.
struct TEnumerateIter
struct TInvokeResult_Impl
struct TInvokeResult_Impl< decltype((void) Invoke(DeclVal< FuncType >(), DeclVal< ArgTypes >()...)), FuncType, ArgTypes... >
struct TIsImplicitlyConstructibleImpl
struct TIsImplicitlyConstructibleImpl< T, ArgType >
struct TIsTNotNullParam
struct TIsTNotNullParam< TNotNull< T > >
struct TIsType
Determine if the type with the provided index in the template parameter pack is the same.
class TMaybeObjectPtr
struct TMoveConstructorCaller
A utility for calling a type's move constructor based on an index into a template parameter pack.
struct TMoveConstructorLookup
A utility for calling a type's move constructor based on an index into a template parameter pack.
class TMutableView
struct TMutableViewTraits
struct TMutableViewTraits< TArray< TObjectPtr< T > >, ViewType >
struct TMutableViewTraits< TMap< K, V >, ViewType >
struct TMutableViewTraits< TObjectPtr< T >, ViewType >
struct TMutableViewTraits< TSet< TObjectPtr< V > >, ViewType >
struct TNonIntrusiveOptionalStorage
struct TNotNullBase
struct TNotNullBase< T * >
struct TObjectPtrDecayTypeOf
struct TObjectPtrDecayTypeOf< TArray< T > >
struct TObjectPtrDecayTypeOf< TMap< K, V > >
struct TObjectPtrDecayTypeOf< TNonNullPtr< TObjectPtr< T > > >
struct TObjectPtrDecayTypeOf< TObjectPtr< T > >
struct TObjectPtrDecayTypeOf< TSet< T > >
struct TObjectPtrWrapTypeOf
struct TObjectPtrWrapTypeOf< T * >
struct TObjectPtrWrapTypeOf< TArray< T > >
struct TObjectPtrWrapTypeOf< TArrayView< T > >
struct TObjectPtrWrapTypeOf< TMap< K, V > >
struct TObjectPtrWrapTypeOf< TSet< T > >
struct TOptionalStorage
struct TParameterPackTypeIndex
Entry-point for looking up the index of a type in a template parameter pack.
struct TParameterPackTypeIndexHelper
Helper to lookup indices of each type in a template parameter pack.
struct TParameterPackTypeIndexHelper< N, LookupType, T, Ts... >
When different type than the lookup is at the front of the parameter pack, we increase the index and move to the next type.
struct TParameterPackTypeIndexHelper< N, T, T, Ts... >
When the type we're looking up bubbles up to the top, we return the current index.
struct TPrivateAccess
struct TProjectionMemberData
struct TProjectionMemberData< MemberType ClassType::* >
struct TProjectionMemberFunction
struct TProjectionMemberFunction< FunctionType ClassType::* >
struct TPtrVariantBase
struct TReverseIterationAdapter
struct TReverseIterationAdapter< ElementType(&)[N]>
struct TScriptDelegateTraits
struct TTypePackContainsDuplicates
Determine if all the types in a template parameter pack has duplicate types.
struct TTypePackContainsDuplicates< T >
A template parameter pack containing a single type has no duplicates.
struct TTypePackContainsDuplicates< T, T, Ts... >
A template parameter pack containing the same type adjacently contains duplicate types.
struct TTypePackContainsDuplicates< T, U, Rest... >
Check all pairs of types in a template parameter pack to determine if any type is duplicated.
struct TVariantLoadFromArchiveCaller
A utility for loading a specific type from FArchive into a TVariant.
struct TVariantLoadFromArchiveLookup
A utility for loading a type from FArchive based on an index into a template parameter pack.
struct TVariantStorage
Determine the max alignof and sizeof of all types in a template parameter pack and provide a type that is compatible with those sizes.
struct TWrapper
Work around used to separate pack expansion of EncodedIndices and VariantIndices in VisitImpl below when defining the Invokers array.
Typedefs
template<typename AllocatorInstanceType>
using TAllocatorSizeType_T = decltype(std::declval<AllocatorInstanceType&>().GetInitialCapacity())
template<typename T>
using TToStringType_T = decltype(GetBindingType(std::declval<T>()))
Enumerations
enum class ENullTerminatedString { No = 0 , Yes = 1 }
Functions
template<typename From, typename To>
constexpr bool BackwardCompatibilityCheck ()
template<typename FromArrayType, typename ToArrayType>
UE_NODEBUG constexpr bool CanMoveTArrayPointersBetweenArrayTypes ()
template<typename... Ts>
FORCEINLINE const TVariantStorage< Ts... > & CastToStorage (const TVariant< Ts... > &Variant)
template<typename... Ts>
FORCEINLINE TVariantStorage< Ts... > && CastToStorage (TVariant< Ts... > &&Variant)
template<typename... Ts>
FORCEINLINE TVariantStorage< Ts... > & CastToStorage (TVariant< Ts... > &Variant)
Cast a TVariant to its private base.
template<typename CharType>
void CharTextStaticAssert ()
template<typename CharType, typename ArgType>
ArgType && CheckCharType (ArgType &&Arg)
ANSICHAR * Convert (ANSICHAR *Dest, int32 DestLen, const UTF8CHAR *Src)
ANSICHAR * Convert (ANSICHAR *Dest, int32 DestLen, const UTF8CHAR *Src, int32 SrcLen)
UCS2CHAR * Convert (UCS2CHAR *Dest, int32 DestLen, const UTF8CHAR *Src)
UCS2CHAR * Convert (UCS2CHAR *Dest, int32 DestLen, const UTF8CHAR *Src, int32 SrcLen)
UTF8CHAR * Convert (UTF8CHAR *Dest, int32 DestLen, const UCS2CHAR *Src)
UTF8CHAR * Convert (UTF8CHAR *Dest, int32 DestLen, const UCS2CHAR *Src, int32 SrcLen)
UTF8CHAR * Convert (UTF8CHAR *Dest, int32 DestLen, const UTF32CHAR *Src)
UTF8CHAR * Convert (UTF8CHAR *Dest, int32 DestLen, const UTF32CHAR *Src, int32 SrcLen)
UTF8CHAR * Convert (UTF8CHAR *Dest, int32 DestLen, const WIDECHAR *Src)
UTF8CHAR * Convert (UTF8CHAR *Dest, int32 DestLen, const WIDECHAR *Src, int32 SrcLen)
WIDECHAR * Convert (WIDECHAR *Dest, int32 DestLen, const UTF8CHAR *Src)
WIDECHAR * Convert (WIDECHAR *Dest, int32 DestLen, const UTF8CHAR *Src, int32 SrcLen)
constexpr SIZE_T DecodeIndex (SIZE_T EncodedIndex, SIZE_T VariantIndex, const SIZE_T *VariantSizes)
Inverse operation of EncodeIndices.
void * DelegateAllocate (size_t Size, FDelegateAllocation &Allocation)
template<typename OuterType, typename TargetType>
constexpr auto DereferenceIfNecessary (TargetType &&Target, const volatile OuterType *TargetPtr) -> decltype((TargetType &&) Target)
template<typename OuterType, typename TargetType>
constexpr auto DereferenceIfNecessary (TargetType &&Target,...) -> decltype(*(TargetType &&) Target)
template<typename T>
SIZE_T EncodeIndices (const T &Variant)
Encode the stored index of a bunch of variants into a single value used to lookup a Visit invocation function.
template<typename Variant0, typename... Variants>
SIZE_T EncodeIndices (const Variant0 &First, const Variants &... Rest)
template<typename AllocatorType>
UE_NODEBUG constexpr uint32 GetAllocatorFlags ()
const FString & GetBindingType (const FString &Str)
const FStringView & GetBindingType (const FStringView &StringView)
const TCHAR * GetBindingType (const TCHAR *Ptr)
int32 GetConvertedLength (const ANSICHAR *Dest, const UTF8CHAR *Src)
int32 GetConvertedLength (const ANSICHAR *Dest, const UTF8CHAR *Src, int32 SrcLen)
int32 GetConvertedLength (const UCS2CHAR *Dest, const UTF8CHAR *Src)
int32 GetConvertedLength (const UCS2CHAR *Dest, const UTF8CHAR *Src, int32 SrcLen)
int32 GetConvertedLength (const UTF8CHAR *Dest, const UCS2CHAR *Src)
int32 GetConvertedLength (const UTF8CHAR *Dest, const UCS2CHAR *Src, int32 SrcLen)
int32 GetConvertedLength (const UTF8CHAR *Dest, const UTF32CHAR *Src)
int32 GetConvertedLength (const UTF8CHAR *Dest, const UTF32CHAR *Src, int32 SrcLen)
int32 GetConvertedLength (const UTF8CHAR *Dest, const WIDECHAR *Src)
int32 GetConvertedLength (const UTF8CHAR *Dest, const WIDECHAR *Src, int32 SrcLen)
int32 GetConvertedLength (const WIDECHAR *Dest, const UTF8CHAR *Src)
int32 GetConvertedLength (const WIDECHAR *Dest, const UTF8CHAR *Src, int32 SrcLen)
template<typename T>
FORCEINLINE decltype(auto) GetDataHelper (T &&Arg)
TOptional< FModuleManager > & GetModuleManagerSingleton ()
template<typename SrcEncoding, typename DestEncoding>
constexpr bool IsCharEncodingCompatibleWithImpl ()
template<typename SrcEncoding, typename DestEncoding>
constexpr bool IsCharEncodingSimplyConvertibleToImpl ()
template<typename Encoding>
constexpr bool IsFixedWidthEncodingImpl ()
Tests whether an encoding has fixed-width characters.
template<typename ObjectType, ESPMode Mode>
FORCEINLINE TSharedRef< ObjectType, Mode > MakeSharedRef (ObjectType *InObject, SharedPointerInternals::TReferenceControllerBase< Mode > *InSharedReferenceCount)
template<typename Concept, typename... Ts>
static char(& ModelsResolve (...))[1]
template<typename Concept, typename... Ts>
static char(& ModelsResolve (decltype(&Concept::template Requires< Ts... >) *))[2]
constexpr bool ModuleNameEquals (const char *Lhs, const char *Rhs)
void OnInvalidAlignedHeapAllocatorNum (int32 NewNum, SIZE_T NumBytesPerElement)
void OnInvalidArrayNum (unsigned long long NewNum)
void OnInvalidConcurrentLinearArrayAllocatorNum (int32 NewNum, SIZE_T NumBytesPerElement)
void OnInvalidMemStackAllocatorNum (int32 NewNum, SIZE_T NumBytesPerElement)
void OnInvalidSetNum (unsigned long long NewNum)
void OnInvalidSizedHeapAllocatorNum (int32 IndexSize, int64 NewNum, SIZE_T NumBytesPerElement)
template<typename LhsType, bool bLhsStrength, typename RhsType, bool bRhsStrength>
bool operator!= (const TPtrVariantBase< LhsType, bLhsStrength > &Lhs, const TPtrVariantBase< RhsType, bRhsStrength > &Rhs)
template<typename LhsType, bool bLhsStrength, typename RhsType>
bool operator!= (const TPtrVariantBase< LhsType, bLhsStrength > &Lhs, RhsType *Rhs)
template<typename LhsType, typename RhsType, bool bRhsStrength>
bool operator!= (LhsType *Lhs, const TPtrVariantBase< RhsType, bRhsStrength > &Rhs)
template<typename LhsType, bool bLhsStrength, typename RhsType, bool bRhsStrength UE_REQUIRES>
bool operator== (const TPtrVariantBase< LhsType, bLhsStrength > &Lhs, const TPtrVariantBase< RhsType, bRhsStrength > &Rhs)
template<typename LhsType, bool bLhsStrength, typename RhsType UE_REQUIRES>
bool operator== (const TPtrVariantBase< LhsType, bLhsStrength > &Lhs, RhsType *Rhs)
template<typename LhsType, typename RhsType, bool bRhsStrength UE_REQUIRES>
bool operator== (LhsType *Lhs, const TPtrVariantBase< RhsType, bRhsStrength > &Rhs)
template<uint32 Flags, typename AllocatorInstanceType>
FORCENOINLINE void ReallocForCopy (uint32 ElementSize, uint32 ElementAlignment, TAllocatorSizeType_T< AllocatorInstanceType > NewMax, TAllocatorSizeType_T< AllocatorInstanceType > PrevMax, AllocatorInstanceType &AllocatorInstance, TAllocatorSizeType_T< AllocatorInstanceType > ArrayNum, TAllocatorSizeType_T< AllocatorInstanceType > &ArrayMax)
template<uint32 Flags, typename AllocatorInstanceType>
FORCENOINLINE TAllocatorSizeType_T< AllocatorInstanceType > ReallocGrow (uint32 ElementSize, uint32 ElementAlignment, TAllocatorSizeType_T< AllocatorInstanceType > Count, AllocatorInstanceType &AllocatorInstance, TAllocatorSizeType_T< AllocatorInstanceType > &ArrayNum, TAllocatorSizeType_T< AllocatorInstanceType > &ArrayMax)
template<uint32 Flags, typename AllocatorInstanceType>
FORCENOINLINE TAllocatorSizeType_T< AllocatorInstanceType > ReallocGrow1_DoAlloc (uint32 ElementSize, uint32 ElementAlignment, AllocatorInstanceType &AllocatorInstance, TAllocatorSizeType_T< AllocatorInstanceType > &ArrayMax)
template<uint32 Flags, typename AllocatorInstanceType>
FORCEINLINE TAllocatorSizeType_T< AllocatorInstanceType > ReallocGrow1_DoAlloc_Impl (uint32 ElementSize, uint32 ElementAlignment, AllocatorInstanceType &AllocatorInstance, TAllocatorSizeType_T< AllocatorInstanceType > &ArrayMax)
template<uint32 Flags, typename AllocatorInstanceType>
FORCENOINLINE TAllocatorSizeType_T< AllocatorInstanceType > ReallocGrow1_DoAlloc_Tiny (uint16 ElementSizeAndAlignment, AllocatorInstanceType &AllocatorInstance, TAllocatorSizeType_T< AllocatorInstanceType > &ArrayMax)
template<uint32 Flags, typename AllocatorInstanceType>
FORCENOINLINE void ReallocShrink (uint32 ElementSize, uint32 ElementAlignment, AllocatorInstanceType &AllocatorInstance, TAllocatorSizeType_T< AllocatorInstanceType > ArrayNum, TAllocatorSizeType_T< AllocatorInstanceType > &ArrayMax)
template<uint32 Flags, typename AllocatorInstanceType>
FORCENOINLINE void ReallocTo (uint32 ElementSize, uint32 ElementAlignment, TAllocatorSizeType_T< AllocatorInstanceType > NewMax, AllocatorInstanceType &AllocatorInstance, TAllocatorSizeType_T< AllocatorInstanceType > ArrayNum, TAllocatorSizeType_T< AllocatorInstanceType > &ArrayMax)
void RecordAssetLog (const FName &CategoryName, ELogVerbosity::Type Verbosity, const FAssetLog &AssetLog, const FString &Message, const ANSICHAR *File, int32 Line)
static UE_NODEBUG char(& ResolveIsTArrayPtr (...))[1]
template<typename ElementType, typename AllocatorType>
static UE_NODEBUG char(& ResolveIsTArrayPtr (const volatile TArray< ElementType, AllocatorType > *))[2]
template<typename CharType>
constexpr int32 StringLength (const CharType *InString)
template<typename... ArgTypes>
constexpr auto StringViewGetData (ArgTypes &&... Args) -> decltype(GetData(Forward< ArgTypes >(Args)...))
Allow GetData to called unqualified from a scope with its own overload of GetData.
void StripNegativeZero (double &InFloat)
int32 Strlen32 (const UTF32CHAR *String)
template<typename Class, typename MemberType>
constexpr bool TIsMemberPointerToFunction (MemberType Class::*)
template<SIZE_T N>
auto ToUTF8Literal (const char(&Array)[N]) -> const UTF8CHAR(&)[N]
constexpr UTF8CHAR ToUTF8Literal (unsigned long long Ch)
template<>
struct UE_DEPRECATED (5.3, "TScriptDelegate<FWeakObjectPtr> and TMulticastScriptDelegate<FWeakObjectPtr> have been deprecated, please use FScriptDelegate or FMulticastScriptDelegate respectively.") TScriptDelegateTraits< FWeakObjectPtr >
template<SIZE_T EncodedIndex, SIZE_T... VariantIndices, typename Func, typename... Variants>
decltype(auto) VisitApplyEncoded (Func &&Callable, Variants &&... Args)
Invocation detail for a single combination of stored variant indices.
template<typename Func, SIZE_T... EncodedIndices, SIZE_T... VariantIndices, typename... Variants>
decltype(auto) VisitImpl (SIZE_T EncodedIndex, Func &&Callable, TIntegerSequence< SIZE_T, EncodedIndices... > &&, TIntegerSequence< SIZE_T, VariantIndices... > &&VariantIndicesSeq, Variants &&... Args)
Implementation detail for Visit(Callable, Variants...).
Variables
constexpr int32 InvalidWeakObjectIndex = 0
Specifies the ObjectIndex used for invalid object pointers.
template<typename T, typename Container>
constexpr TAdderVTable< T > GAdderVTableImpl & TAdderVTableImpl
template<typename DestType, typename SourceType>
constexpr bool TArrayElementsAreCompatible_V = std::disjunction_v<std::is_same<DestType, std::decay_t<SourceType>>, std::is_constructible<DestType, SourceType>>
template<typename InElementType, typename... ArgTypes>
constexpr bool TCanBeConvertedToFromAll_V = (std::is_convertible_v<ArgTypes, InElementType> && ...)
template<typename T, T Val>
constexpr T TForceConstEval_V = Val
template<typename T>
constexpr bool TIsTArrayOrDerivedFromTArray_V = sizeof(ResolveIsTArrayPtr((T*)nullptr)) == 2
template<typename... ArgTypes>
constexpr bool TIsTNotNullParam_V = TIsTNotNullParam<ArgTypes...>::Value
template<auto Storage, auto PtrToMember>
TPrivateAccess< Storage, PtrToMember > TPrivateAccess< Storage, PtrToMember >::Instance
Detailed Description
TAdderRef and TAdderReserverRef are type-erasing adapters that allow a function to add to (and reserve) a container without the function knowing about the specific type of the container.
Utilities for concepts checks.
implementation
Module implementation boilerplate for regular modules.
Facilities to allow types to have an intrusive invalid state which can act as TOptional's 'unset' state, saving space.
This allows the container and allocator to vary without having to change the function signature or make it a template.
Example:
void AddThree(TAdderRef<int32> Adder) { Adder.Add(3); }
void AddZeroToFour(TAdderReserverRef<int32> AdderReserver) { AdderReserver.Reserver(AdderReserver.Num() + 5); for (int Val = 0; Val != 5; ++Val) { AdderReserver.Add(Val); } }
TArray<int32, TInlineAllocator<10>> Arr; TSet<int32> Set;
AddThree(Arr); // Arr == { 3 } AddThree(Set); // Set == { 3 } AddZeroToFour(Arr); // Arr == { 3, 0, 1, 2, 3, 4 } AddZeroToFour(Set); // Set == { 3, 0, 1, 2, 4 } - only contains one 3 because it's a set
A class in such a state will only ever be compared against FIntrusiveUnsetOptionalState or destructed.
A class should implement a constructor taking FIntrusiveUnsetOptionalState, and an equality comparison operator against FIntrusiveUnsetOptionalState, which will put a class instance into the 'unset' state (in the case of the constructor) and allow testing of its unset state.
A public constexpr static data member of type bool called bHasIntrusiveUnsetOptionalState should be defined and set to true. There must also be a public typedef/alias called IntrusiveUnsetOptionalStateType and set to the type itself. This enables the optimization of this type within TOptional.
These functions should be public - regular user code will not be able to call them as they will not be able to construct an FIntrusiveUnsetOptionalState object to pass.
Example:
struct FMyType { // This static member should be constexpr, public and equal to true. static constexpr bool bHasIntrusiveUnsetOptionalState = true;
explicit FMyType(int32 InIndex) { // Validate class invariant. check(InIndex >= 0);
Index = InIndex; }
// This constructor will only ever be called by TOptional<FMyType> to enter its // 'unset' state. explicit FMyType(FIntrusiveUnsetOptionalState) { // Since negative indices are illegal as per the class invariant, we can use -1 // here as TOptional's 'unset' state, which no legal class instance will have. Index = -1; }
// This comparison function will only ever be called by TOptional to check if the // object is in the 'unset' state. It does not need to be commutative like most // comparison operators, nor is an operator!= necessary. bool operator==(FIntrusiveUnsetOptionalState) const { return Index == -1; }
private: // Non-negative indices are part of the class invariant. int32 Index; };
This macro is used to expose a module's main class to the rest of the engine. You must use this macro in one of your modules C++ modules, in order for the 'InitializeModule' function to be declared in such a way that the engine can find it. Also, this macro will handle the case where a module is statically linked with the engine instead of dynamically loaded.
This macro is intended for modules that do NOT contain gameplay code. If your module does contain game classes, use IMPLEMENT_GAME_MODULE instead.
Usage: IMPLEMENT_MODULE(<My Module Class>, <Module name string>)
See also
IMPLEMENT_GAME_MODULE
In this case, a successful concept check means that a given C++ expression is well-formed. No guarantees are given about the correctness, behavior or complexity of the runtime behaviour of that expression.
Concepts are structs with a rather unusual definition:
struct CConcept { template <[...concept parameters...]> auto Requires([...placeholder variables...]) -> decltype([...expression(s) to test the validity of...]); };
The prefix C is reserved for concepts, and concepts should be directly named as an adjective and not like a predicate, i.e.: CEqualityComparable - good CIsComparable - bad CHasEqualsOperator - bad
Concepts can be checked using the TModels_V trait or TModels traits class:
TModels_V<Concept, [...arguments...]> TModels<Concept, [...arguments...]>::Value
The arguments are forwarded to the template parameters of the concept's Requires() function, which will attempt to compile the expression(s) in the return value, and SFINAE is utilized to test whether that succeeded.
The placeholders are simply any variable declarations you need to write your expression(s).
Note that 'legal C++' doesn't necessarily mean that the expression will compile when used. The concept check only tests that the syntax is valid. Instantiation of function template bodies may still fail. See the CContainerLvalueAddable example below.
Typedef Documentation
TAllocatorSizeType_T
template<typename AllocatorInstanceType> using UE::Core::Private::TAllocatorSizeType_T = decltype(std::declval<AllocatorInstanceType&>().GetInitialCapacity())
Definition at line 363 of file Array.h.
TToStringType_T
template<typename T> using UE::Core::Private::TToStringType_T = decltype(GetBindingType(std::declval<T>()))
Definition at line 29 of file Paths.h.
Enumeration Type Documentation
ENullTerminatedString
enum class UE::Core::Private::ENullTerminatedString strong
Enumerator
No
Yes
Definition at line 348 of file StringConv.h.
Function Documentation
BackwardCompatibilityCheck()
template<typename From, typename To> bool UE::Core::Private::BackwardCompatibilityCheck () inline constexpr
Definition at line 44 of file ScriptDelegates.h.
CanMoveTArrayPointersBetweenArrayTypes()
template<typename FromArrayType, typename ToArrayType> UE_NODEBUG constexpr bool UE::Core::Private::CanMoveTArrayPointersBetweenArrayTypes () nodiscard constexpr
Definition at line 314 of file Array.h.
References TLosesQualifiersFromTo_V, UE_NODEBUG, TCanMoveBetweenAllocators< FromAllocatorType, ToAllocatorType >::Value, and TIsBitwiseConstructible< T, Arg >::Value.
Referenced by RangedForIteratorType< FAnimNextTraitEventPtr >::MoveOrCopy(), and RangedForIteratorType< FAnimNextTraitEventPtr >::MoveOrCopyWithSlack().
CastToStorage() [1/3]
template<typename... Ts> FORCEINLINE const TVariantStorage< Ts... > & UE::Core::Private::CastToStorage (const TVariant< Ts... > & Variant)
Definition at line 360 of file TVariantMeta.h.
References FORCEINLINE.
CastToStorage() [2/3]
template<typename... Ts> FORCEINLINE TVariantStorage< Ts... > && UE::Core::Private::CastToStorage (TVariant< Ts... > && Variant)
Definition at line 354 of file TVariantMeta.h.
References FORCEINLINE.
CastToStorage() [3/3]
template<typename... Ts> FORCEINLINE TVariantStorage< Ts... > & UE::Core::Private::CastToStorage (TVariant< Ts... > & Variant)
Cast a TVariant to its private base.
Definition at line 348 of file TVariantMeta.h.
References FORCEINLINE.
Referenced by TVariant< TYPE_OF_NULLPTR, double, FString, bool >::TVariant(), TVariant< TYPE_OF_NULLPTR, double, FString, bool >::TVariant(), TVariant< TYPE_OF_NULLPTR, double, FString, bool >::TVariant(), TVariant< TYPE_OF_NULLPTR, double, FString, bool >::TVariant(), TVariant< TYPE_OF_NULLPTR, double, FString, bool >::Emplace(), TVariant< TYPE_OF_NULLPTR, double, FString, bool >::Get(), TVariant< TYPE_OF_NULLPTR, double, FString, bool >::TryGet(), and VisitApplyEncoded().
CharTextStaticAssert()
template<typename CharType> void UE::Core::Private::CharTextStaticAssert ()
Definition at line 1308 of file Platform.h.
CheckCharType()
template<typename CharType, typename ArgType> ArgType && UE::Core::Private::CheckCharType (ArgType && Arg) inline
Definition at line 95 of file StringOverload.h.
References TIsContiguousContainer< T >::Value.
Convert() [1/12]
ANSICHAR * UE::Core::Private::Convert (ANSICHAR * Dest, int32 DestLen, const UTF8CHAR * Src)
Convert() [2/12]
ANSICHAR * UE::Core::Private::Convert (ANSICHAR * Dest, int32 DestLen, const UTF8CHAR * Src, int32 SrcLen)
Convert() [3/12]
UCS2CHAR * UE::Core::Private::Convert (UCS2CHAR * Dest, int32 DestLen, const UTF8CHAR * Src)
Convert() [4/12]
UCS2CHAR * UE::Core::Private::Convert (UCS2CHAR * Dest, int32 DestLen, const UTF8CHAR * Src, int32 SrcLen)
Convert() [5/12]
UTF8CHAR * UE::Core::Private::Convert (UTF8CHAR * Dest, int32 DestLen, const UCS2CHAR * Src)
Convert() [6/12]
UTF8CHAR * UE::Core::Private::Convert (UTF8CHAR * Dest, int32 DestLen, const UCS2CHAR * Src, int32 SrcLen)
Convert() [7/12]
UTF8CHAR * UE::Core::Private::Convert (UTF8CHAR * Dest, int32 DestLen, const UTF32CHAR * Src)
Convert() [8/12]
UTF8CHAR * UE::Core::Private::Convert (UTF8CHAR * Dest, int32 DestLen, const UTF32CHAR * Src, int32 SrcLen)
Convert() [9/12]
UTF8CHAR * UE::Core::Private::Convert (UTF8CHAR * Dest, int32 DestLen, const WIDECHAR * Src)
Referenced by FGenericPlatformString::Convert(), and FGenericPlatformString::Convert().
Convert() [10/12]
UTF8CHAR * UE::Core::Private::Convert (UTF8CHAR * Dest, int32 DestLen, const WIDECHAR * Src, int32 SrcLen)
Convert() [11/12]
WIDECHAR * UE::Core::Private::Convert (WIDECHAR * Dest, int32 DestLen, const UTF8CHAR * Src)
Convert() [12/12]
WIDECHAR * UE::Core::Private::Convert (WIDECHAR * Dest, int32 DestLen, const UTF8CHAR * Src, int32 SrcLen)
DecodeIndex()
SIZE_T UE::Core::Private::DecodeIndex (SIZE_T EncodedIndex, SIZE_T VariantIndex, const SIZE_T * VariantSizes) constexpr
Inverse operation of EncodeIndices.
Decodes an encoded index into the individual index for the specified variant index.
Definition at line 335 of file TVariantMeta.h.
Referenced by VisitApplyEncoded().
DelegateAllocate()
void * UE::Core::Private::DelegateAllocate (size_t Size, FDelegateAllocation & Allocation)
References DelegateAllocate(), and TSequenceHistory< HistorySize >::Size.
Referenced by DelegateAllocate(), and operator new().
DereferenceIfNecessary() [1/2]
template<typename OuterType, typename TargetType> auto UE::Core::Private::DereferenceIfNecessary (TargetType && Target, const volatile OuterType * TargetPtr) -> decltype((TargetType&&)Target) constexpr
Definition at line 14 of file Invoke.h.
References Target.
Referenced by Invoke(), and Invoke().
DereferenceIfNecessary() [2/2]
template<typename OuterType, typename TargetType> auto UE::Core::Private::DereferenceIfNecessary (TargetType && Target, ...) -> decltype(*(TargetType&&)Target) constexpr
Definition at line 22 of file Invoke.h.
References Target.
EncodeIndices() [1/2]
template<typename T> SIZE_T UE::Core::Private::EncodeIndices (const T & Variant) inline
Encode the stored index of a bunch of variants into a single value used to lookup a Visit invocation function.
Definition at line 323 of file TVariantMeta.h.
Referenced by EncodeIndices(), and Visit().
EncodeIndices() [2/2]
template<typename Variant0, typename... Variants> SIZE_T UE::Core::Private::EncodeIndices (const Variant0 & First, const Variants &... Rest) inline
Definition at line 329 of file TVariantMeta.h.
References EncodeIndices(), First, and TVariantSize_V.
GetAllocatorFlags()
template<typename AllocatorType> UE_NODEBUG constexpr uint32 UE::Core::Private::GetAllocatorFlags () nodiscard constexpr
Definition at line 372 of file Array.h.
References TAllocatorTraitsBase< AllocatorType >::SupportsElementAlignment, TAllocatorTraitsBase< AllocatorType >::SupportsSlackTracking, and UE_NODEBUG.
GetBindingType() [1/3]
const FString & UE::Core::Private::GetBindingType (const FString & Str)
GetBindingType() [2/3]
const FStringView & UE::Core::Private::GetBindingType (const FStringView & StringView)
GetBindingType() [3/3]
const TCHAR * UE::Core::Private::GetBindingType (const TCHAR * Ptr)
GetConvertedLength() [1/12]
int32 UE::Core::Private::GetConvertedLength (const ANSICHAR * Dest, const UTF8CHAR * Src)
GetConvertedLength() [2/12]
int32 UE::Core::Private::GetConvertedLength (const ANSICHAR * Dest, const UTF8CHAR * Src, int32 SrcLen)
GetConvertedLength() [3/12]
int32 UE::Core::Private::GetConvertedLength (const UCS2CHAR * Dest, const UTF8CHAR * Src)
GetConvertedLength() [4/12]
int32 UE::Core::Private::GetConvertedLength (const UCS2CHAR * Dest, const UTF8CHAR * Src, int32 SrcLen)
GetConvertedLength() [5/12]
int32 UE::Core::Private::GetConvertedLength (const UTF8CHAR * Dest, const UCS2CHAR * Src)
GetConvertedLength() [6/12]
int32 UE::Core::Private::GetConvertedLength (const UTF8CHAR * Dest, const UCS2CHAR * Src, int32 SrcLen)
GetConvertedLength() [7/12]
int32 UE::Core::Private::GetConvertedLength (const UTF8CHAR * Dest, const UTF32CHAR * Src)
GetConvertedLength() [8/12]
int32 UE::Core::Private::GetConvertedLength (const UTF8CHAR * Dest, const UTF32CHAR * Src, int32 SrcLen)
GetConvertedLength() [9/12]
int32 UE::Core::Private::GetConvertedLength (const UTF8CHAR * Dest, const WIDECHAR * Src)
Referenced by FGenericPlatformString::ConvertedLength(), and FGenericPlatformString::ConvertedLength().
GetConvertedLength() [10/12]
int32 UE::Core::Private::GetConvertedLength (const UTF8CHAR * Dest, const WIDECHAR * Src, int32 SrcLen)
GetConvertedLength() [11/12]
int32 UE::Core::Private::GetConvertedLength (const WIDECHAR * Dest, const UTF8CHAR * Src)
GetConvertedLength() [12/12]
int32 UE::Core::Private::GetConvertedLength (const WIDECHAR * Dest, const UTF8CHAR * Src, int32 SrcLen)
GetDataHelper()
template<typename T> FORCEINLINE decltype(auto) UE::Core::Private::GetDataHelper (T && Arg) nodiscard
Definition at line 308 of file Array.h.
References FORCEINLINE, Forward(), and GetData().
Referenced by RangedForIteratorType< FAnimNextTraitEventPtr >::Append().
GetModuleManagerSingleton()
TOptional< FModuleManager > & UE::Core::Private::GetModuleManagerSingleton ()
IsCharEncodingCompatibleWithImpl()
template<typename SrcEncoding, typename DestEncoding> bool UE::Core::Private::IsCharEncodingCompatibleWithImpl () constexpr
Definition at line 15 of file IsCharEncodingCompatibleWith.h.
References TIsCharType_V.
IsCharEncodingSimplyConvertibleToImpl()
template<typename SrcEncoding, typename DestEncoding> bool UE::Core::Private::IsCharEncodingSimplyConvertibleToImpl () constexpr
Definition at line 13 of file IsCharEncodingSimplyConvertibleTo.h.
References TIsCharEncodingCompatibleWith_V, and TIsFixedWidthCharEncoding_V.
IsFixedWidthEncodingImpl()
template<typename Encoding> bool UE::Core::Private::IsFixedWidthEncodingImpl () constexpr
Tests whether an encoding has fixed-width characters.
Definition at line 18 of file IsFixedWidthCharEncoding.h.
MakeSharedRef()
template<typename ObjectType, ESPMode Mode> FORCEINLINE TSharedRef< ObjectType, Mode > UE::Core::Private::MakeSharedRef (ObjectType * InObject, SharedPointerInternals::TReferenceControllerBase< Mode > * InSharedReferenceCount)
Definition at line 137 of file SharedPointer.h.
References FORCEINLINE.
Referenced by MakeShared().
ModelsResolve() [1/2]
template<typename Concept, typename... Ts> char(& UE::Core::Private::ModelsResolve (...))[1] static
ModelsResolve() [2/2]
template<typename Concept, typename... Ts> char(& UE::Core::Private::ModelsResolve (decltype &::< ... >Ts *))[2] static
ModuleNameEquals()
bool UE::Core::Private::ModuleNameEquals (const char * Lhs, const char * Rhs) constexpr
Definition at line 894 of file ModuleManager.h.
OnInvalidAlignedHeapAllocatorNum()
void UE::Core::Private::OnInvalidAlignedHeapAllocatorNum (int32 NewNum, SIZE_T NumBytesPerElement)
Referenced by TAlignedHeapAllocator< Alignment >::ForAnyElementType::ResizeAllocation().
OnInvalidArrayNum()
void UE::Core::Private::OnInvalidArrayNum (unsigned long long NewNum)
Referenced by RangedForIteratorType< FAnimNextTraitEventPtr >::CopyToEmptyWithSlack(), RangedForIteratorType< FAnimNextTraitEventPtr >::Empty(), RangedForIteratorType< FAnimNextTraitEventPtr >::MoveOrCopy(), RangedForIteratorType< FAnimNextTraitEventPtr >::MoveOrCopyWithSlack(), ReallocGrow(), ReallocGrow1_DoAlloc_Impl(), RangedForIteratorType< FAnimNextTraitEventPtr >::Reserve(), RangedForIteratorType< FAnimNextTraitEventPtr >::Reset(), FScriptArrayHelper::Resize(), RangedForIteratorType< FAnimNextTraitEventPtr >::SetNum(), RangedForIteratorType< FAnimNextTraitEventPtr >::SetNumUninitialized(), RangedForIteratorType< FAnimNextTraitEventPtr >::SetNumZeroed(), and RangedForIteratorType< FAnimNextTraitEventPtr >::TArray().
OnInvalidConcurrentLinearArrayAllocatorNum()
void UE::Core::Private::OnInvalidConcurrentLinearArrayAllocatorNum (int32 NewNum, SIZE_T NumBytesPerElement)
Referenced by TLinearArrayAllocatorBase< BlockAllocationTag, ThreadPolicy >::ForElementType< FScriptContainerElement >::ResizeAllocation().
OnInvalidMemStackAllocatorNum()
void UE::Core::Private::OnInvalidMemStackAllocatorNum (int32 NewNum, SIZE_T NumBytesPerElement)
Referenced by TMemStackAllocator< Alignment >::ForElementType< FScriptContainerElement >::ResizeAllocation().
OnInvalidSetNum()
void UE::Core::Private::OnInvalidSetNum (unsigned long long NewNum)
Referenced by TSet< class UObject * >::Reserve().
OnInvalidSizedHeapAllocatorNum()
void UE::Core::Private::OnInvalidSizedHeapAllocatorNum (int32 IndexSize, int64 NewNum, SIZE_T NumBytesPerElement)
Referenced by TSizedHeapAllocator< IndexSize, BaseMallocType >::ForAnyElementType::ResizeAllocation(), and TSizedHeapAllocator< IndexSize, BaseMallocType >::ForAnyElementType::ResizeAllocation().
operator!=() [1/3]
template<typename LhsType, bool bLhsStrength, typename RhsType, bool bRhsStrength> bool UE::Core::Private::operator!= (const TPtrVariantBase< LhsType, bLhsStrength > & Lhs, const TPtrVariantBase< RhsType, bRhsStrength > & Rhs)
Definition at line 192 of file PointerVariants.h.
operator!=() [2/3]
template<typename LhsType, bool bLhsStrength, typename RhsType> bool UE::Core::Private::operator!= (const TPtrVariantBase< LhsType, bLhsStrength > & Lhs, RhsType * Rhs)
Definition at line 220 of file PointerVariants.h.
operator!=() [3/3]
template<typename LhsType, typename RhsType, bool bRhsStrength> bool UE::Core::Private::operator!= (LhsType * Lhs, const TPtrVariantBase< RhsType, bRhsStrength > & Rhs)
Definition at line 206 of file PointerVariants.h.
operator==() [1/3]
template<typename LhsType, bool bLhsStrength, typename RhsType, bool bRhsStrength UE_REQUIRES> bool UE::Core::Private::operator== (const TPtrVariantBase< LhsType, bLhsStrength > & Lhs, const TPtrVariantBase< RhsType, bRhsStrength > & Rhs)
Definition at line 186 of file PointerVariants.h.
operator==() [2/3]
template<typename LhsType, bool bLhsStrength, typename RhsType UE_REQUIRES> bool UE::Core::Private::operator== (const TPtrVariantBase< LhsType, bLhsStrength > & Lhs, RhsType * Rhs)
Definition at line 214 of file PointerVariants.h.
operator==() [3/3]
template<typename LhsType, typename RhsType, bool bRhsStrength UE_REQUIRES> bool UE::Core::Private::operator== (LhsType * Lhs, const TPtrVariantBase< RhsType, bRhsStrength > & Rhs)
Definition at line 200 of file PointerVariants.h.
ReallocForCopy()
template<uint32 Flags, typename AllocatorInstanceType> FORCENOINLINE void UE::Core::Private::ReallocForCopy (uint32 ElementSize, uint32 ElementAlignment, TAllocatorSizeType_T< AllocatorInstanceType > NewMax, TAllocatorSizeType_T< AllocatorInstanceType > PrevMax, AllocatorInstanceType & AllocatorInstance, TAllocatorSizeType_T< AllocatorInstanceType > ArrayNum, TAllocatorSizeType_T< AllocatorInstanceType > & ArrayMax)
Definition at line 593 of file Array.h.
References Flags, and FORCENOINLINE.
Referenced by RangedForIteratorType< FAnimNextTraitEventPtr >::CopyToEmpty(), RangedForIteratorType< FAnimNextTraitEventPtr >::CopyToEmptyWithSlack(), and TArrayPrivateFriend::Serialize().
ReallocGrow()
template<uint32 Flags, typename AllocatorInstanceType> FORCENOINLINE TAllocatorSizeType_T< AllocatorInstanceType > UE::Core::Private::ReallocGrow (uint32 ElementSize, uint32 ElementAlignment, TAllocatorSizeType_T< AllocatorInstanceType > Count, AllocatorInstanceType & AllocatorInstance, TAllocatorSizeType_T< AllocatorInstanceType > & ArrayNum, TAllocatorSizeType_T< AllocatorInstanceType > & ArrayMax)
Definition at line 460 of file Array.h.
References checkSlow, UE::Count, Flags, FORCENOINLINE, and OnInvalidArrayNum().
Referenced by RangedForIteratorType< FAnimNextTraitEventPtr >::AddUninitialized(), and RangedForIteratorType< FAnimNextTraitEventPtr >::InsertUninitializedImpl().
ReallocGrow1_DoAlloc()
template<uint32 Flags, typename AllocatorInstanceType> FORCENOINLINE TAllocatorSizeType_T< AllocatorInstanceType > UE::Core::Private::ReallocGrow1_DoAlloc (uint32 ElementSize, uint32 ElementAlignment, AllocatorInstanceType & AllocatorInstance, TAllocatorSizeType_T< AllocatorInstanceType > & ArrayMax)
Definition at line 448 of file Array.h.
References FORCENOINLINE, and ReallocGrow1_DoAlloc_Impl().
Referenced by RangedForIteratorType< FAnimNextTraitEventPtr >::AddUninitialized(), RangedForIteratorType< FAnimNextTraitEventPtr >::Emplace(), RangedForIteratorType< FAnimNextTraitEventPtr >::Emplace_GetRef(), and RangedForIteratorType< FAnimNextTraitEventPtr >::InsertUninitializedImpl().
ReallocGrow1_DoAlloc_Impl()
template<uint32 Flags, typename AllocatorInstanceType> FORCEINLINE TAllocatorSizeType_T< AllocatorInstanceType > UE::Core::Private::ReallocGrow1_DoAlloc_Impl (uint32 ElementSize, uint32 ElementAlignment, AllocatorInstanceType & AllocatorInstance, TAllocatorSizeType_T< AllocatorInstanceType > & ArrayMax)
Definition at line 392 of file Array.h.
References Flags, FORCEINLINE, and OnInvalidArrayNum().
Referenced by ReallocGrow1_DoAlloc(), and ReallocGrow1_DoAlloc_Tiny().
ReallocGrow1_DoAlloc_Tiny()
template<uint32 Flags, typename AllocatorInstanceType> FORCENOINLINE TAllocatorSizeType_T< AllocatorInstanceType > UE::Core::Private::ReallocGrow1_DoAlloc_Tiny (uint16 ElementSizeAndAlignment, AllocatorInstanceType & AllocatorInstance, TAllocatorSizeType_T< AllocatorInstanceType > & ArrayMax)
Definition at line 438 of file Array.h.
References FORCENOINLINE, and ReallocGrow1_DoAlloc_Impl().
Referenced by RangedForIteratorType< FAnimNextTraitEventPtr >::AddUninitialized(), RangedForIteratorType< FAnimNextTraitEventPtr >::Emplace(), RangedForIteratorType< FAnimNextTraitEventPtr >::Emplace_GetRef(), and RangedForIteratorType< FAnimNextTraitEventPtr >::InsertUninitializedImpl().
ReallocShrink()
template<uint32 Flags, typename AllocatorInstanceType> FORCENOINLINE void UE::Core::Private::ReallocShrink (uint32 ElementSize, uint32 ElementAlignment, AllocatorInstanceType & AllocatorInstance, TAllocatorSizeType_T< AllocatorInstanceType > ArrayNum, TAllocatorSizeType_T< AllocatorInstanceType > & ArrayMax)
Definition at line 522 of file Array.h.
References Flags, and FORCENOINLINE.
Referenced by RangedForIteratorType< FAnimNextTraitEventPtr >::Pop(), RangedForIteratorType< FAnimNextTraitEventPtr >::RemoveAllSwap(), RangedForIteratorType< FAnimNextTraitEventPtr >::RemoveAt(), RangedForIteratorType< FAnimNextTraitEventPtr >::RemoveAt(), RangedForIteratorType< FAnimNextTraitEventPtr >::RemoveAtSwap(), RangedForIteratorType< FAnimNextTraitEventPtr >::RemoveAtSwap(), and RangedForIteratorType< FAnimNextTraitEventPtr >::RemoveSwap().
ReallocTo()
template<uint32 Flags, typename AllocatorInstanceType> FORCENOINLINE void UE::Core::Private::ReallocTo (uint32 ElementSize, uint32 ElementAlignment, TAllocatorSizeType_T< AllocatorInstanceType > NewMax, AllocatorInstanceType & AllocatorInstance, TAllocatorSizeType_T< AllocatorInstanceType > ArrayNum, TAllocatorSizeType_T< AllocatorInstanceType > & ArrayMax)
Definition at line 557 of file Array.h.
References Flags, and FORCENOINLINE.
Referenced by RangedForIteratorType< FAnimNextTraitEventPtr >::Empty(), RangedForIteratorType< FAnimNextTraitEventPtr >::Reserve(), and RangedForIteratorType< FAnimNextTraitEventPtr >::Shrink().
RecordAssetLog()
void UE::Core::Private::RecordAssetLog (const FName & CategoryName, ELogVerbosity::Type Verbosity, const FAssetLog & AssetLog, const FString & Message, const ANSICHAR * File, int32 Line)
References Line.
ResolveIsTArrayPtr() [1/2]
UE_NODEBUG char(& UE::Core::Private::ResolveIsTArrayPtr (...))[1] static
References UE_NODEBUG.
ResolveIsTArrayPtr() [2/2]
template<typename ElementType, typename AllocatorType> UE_NODEBUG char(& UE::Core::Private::ResolveIsTArrayPtr (const volatile TArray< ElementType, AllocatorType > *))[2] static
References UE_NODEBUG.
StringLength()
template<typename CharType> int32 UE::Core::Private::StringLength (const CharType * InString) constexpr
Definition at line 32 of file StringView.h.
References UE::Count.
StringViewGetData()
template<typename... ArgTypes> auto UE::Core::Private::StringViewGetData (ArgTypes &&... Args) -> decltype(GetData(Forward<ArgTypes>(Args)...)) inline constexpr
Allow GetData to called unqualified from a scope with its own overload of GetData.
Definition at line 26 of file StringView.h.
References Forward(), and GetData().
StripNegativeZero()
void UE::Core::Private::StripNegativeZero (double & InFloat)
Strlen32()
int32 UE::Core::Private::Strlen32 (const UTF32CHAR * String)
Referenced by TCString< T >::Strlen().
TIsMemberPointerToFunction()
template<typename Class, typename MemberType> bool UE::Core::Private::TIsMemberPointerToFunction (MemberType Class::*) inline constexpr
Definition at line 56 of file Projection.h.
References Class.
Referenced by Projection().
ToUTF8Literal() [1/2]
template<SIZE_T N> auto UE::Core::Private::ToUTF8Literal (const char(&) Array[N]) -> const UTF8CHAR(&)[N]
Definition at line 1287 of file Platform.h.
References Array, and FORCEINLINE.
ToUTF8Literal() [2/2]
UTF8CHAR UE::Core::Private::ToUTF8Literal (unsigned long long Ch) constexpr
Definition at line 1291 of file Platform.h.
References FORCEINLINE.
UE_DEPRECATED()
template<> struct UE::Core::Private::UE_DEPRECATED (5. 3, "TScriptDelegate<FWeakObjectPtr> and TMulticastScriptDelegate<FWeakObjectPtr> have been deprecated , please use FScriptDelegate or FMulticastScriptDelegate respectively.")
Definition at line 1 of file ScriptDelegates.h.
VisitApplyEncoded()
template<SIZE_T EncodedIndex, SIZE_T... VariantIndices, typename Func, typename... Variants> decltype(auto) UE::Core::Private::VisitApplyEncoded (Func && Callable, Variants &&... Args) inline
Invocation detail for a single combination of stored variant indices.
Definition at line 367 of file TVariantMeta.h.
References CastToStorage(), DecodeIndex(), Forward(), and TVariantSize_V.
Referenced by VisitImpl().
VisitImpl()
template<typename Func, SIZE_T... EncodedIndices, SIZE_T... VariantIndices, typename... Variants> decltype(auto) UE::Core::Private::VisitImpl (SIZE_T EncodedIndex, Func && Callable, TIntegerSequence< SIZE_T, EncodedIndices... > && , TIntegerSequence< SIZE_T, VariantIndices... > && VariantIndicesSeq, Variants &&... Args)
Implementation detail for Visit(Callable, Variants...).
Builds an array of invokers, and forwards the variants to the callable for the specific EncodedIndex
Definition at line 390 of file TVariantMeta.h.
References Forward(), and VisitApplyEncoded().
Referenced by Visit().
Variable Documentation
InvalidWeakObjectIndex
int32 UE::Core::Private::InvalidWeakObjectIndex = 0 inline constexpr
Specifies the ObjectIndex used for invalid object pointers.
Definition at line 34 of file WeakObjectPtr.h.
Referenced by FWeakObjectPtr::GetObjectIndex_Private(), FWeakObjectPtr::Internal_GetObjectItem(), FWeakObjectPtr::IsExplicitlyNull(), and FWeakObjectPtr::Reset().
TAdderVTableImpl
template<typename T, typename Container> TAdderReserverVTable<T, SizeType> GAdderReserverVTableImpl & UE::Core::Private::TAdderVTableImpl constexpr
Definition at line 97 of file AdderRef.h.
TArrayElementsAreCompatible_V
template<typename DestType, typename SourceType> bool UE::Core::Private::TArrayElementsAreCompatible_V = std::disjunction_v<std::is_same<DestType, std::decay_t<SourceType>>, std::is_constructible<DestType, SourceType>> constexpr
Definition at line 349 of file Array.h.
TCanBeConvertedToFromAll_V
template<typename InElementType, typename... ArgTypes> bool UE::Core::Private::TCanBeConvertedToFromAll_V = (std::is_convertible_v<ArgTypes, InElementType> && ...) constexpr
Definition at line 18 of file StaticArray.h.
TForceConstEval_V
template<typename T, T Val> T UE::Core::Private::TForceConstEval_V = Val constexpr
Definition at line 235 of file UnrealTemplate.h.
TIsTArrayOrDerivedFromTArray_V
template<typename T> bool UE::Core::Private::TIsTArrayOrDerivedFromTArray_V = sizeof(ResolveIsTArrayPtr((T*)nullptr)) == 2 constexpr
Definition at line 356 of file Array.h.
TIsTNotNullParam_V
template<typename... ArgTypes> bool UE::Core::Private::TIsTNotNullParam_V = TIsTNotNullParam<ArgTypes...>::Value inline constexpr
Definition at line 92 of file NotNull.h.
Referenced by TNotNull< T * >::~TNotNull().
TPrivateAccess< Storage, PtrToMember >::Instance
template<auto Storage, auto PtrToMember> TPrivateAccess<Storage, PtrToMember> UE::Core::Private::TPrivateAccess< Storage, PtrToMember >::Instance
Definition at line 22 of file DefinePrivateMemberPtr.h.