Unreal Engine 5.6 C++ API: UE::Private Namespace Reference
UE::Private Namespace Reference
The global memory allocator.
Namespaces
namespace BlueprintDependencies
namespace LocGen
namespace WorldPartition
Data Structures
struct FIoRequestListTraits
struct FLookupTableEntry
struct TCPPTypeToPropertyType
struct TCPPTypeToPropertyType< bool >
struct TCPPTypeToPropertyType< double >
struct TCPPTypeToPropertyType< float >
struct TCPPTypeToPropertyType< FName >
struct TCPPTypeToPropertyType< FString >
struct TCPPTypeToPropertyType< FText >
struct TCPPTypeToPropertyType< int16 >
struct TCPPTypeToPropertyType< int32 >
struct TCPPTypeToPropertyType< int64 >
struct TCPPTypeToPropertyType< int8 >
struct TCPPTypeToPropertyType< TArray< T > >
struct TCPPTypeToPropertyType< TLazyObjectPtr< T > >
struct TCPPTypeToPropertyType< TMap< K, V > >
struct TCPPTypeToPropertyType< TMulticastDelegate< T > >
struct TCPPTypeToPropertyType< TObjectPtr< T > >
struct TCPPTypeToPropertyType< TOptional< T > >
struct TCPPTypeToPropertyType< TScriptDelegate< T > >
struct TCPPTypeToPropertyType< TScriptInterface< T > >
struct TCPPTypeToPropertyType< TSoftClassPtr< T > >
struct TCPPTypeToPropertyType< TSoftObjectPtr< T > >
struct TCPPTypeToPropertyType< TSparseDynamicDelegate< A, B, C > >
struct TCPPTypeToPropertyType< TSubclassOf< T > >
struct TCPPTypeToPropertyType< TWeakObjectPtr< T > >
struct TCPPTypeToPropertyType< uint16 >
struct TCPPTypeToPropertyType< uint32 >
struct TCPPTypeToPropertyType< uint64 >
struct TCPPTypeToPropertyType< uint8 >
struct TDoesParamMatchImpl
struct TDoesParamMatchImpl< T< ReferenceType > >
struct TDoesParamMatchImpl< TArray< ContainedType > >
struct TDoesParamMatchImpl< TMap< KeyType, ValueType > >
struct TDoesParamMatchImpl< TMulticastDelegate< SignatureType > >
struct TDoesParamMatchImpl< TOptional< ContainedType > >
struct TDoesParamMatchImpl< TScriptDelegate< SignatureType > >
struct TDoesParamMatchImpl< TSet< ContainedType > >
struct TDoesParamMatchImpl< TSparseDynamicDelegate< SignatureType, OwningClass, InfoGetter > >
struct TDoesStaticFunctionSignatureMatchImpl
struct TDoesStaticFunctionSignatureMatchImpl< ReturnType(Args...)>
struct TDoesStaticFunctionSignatureMatchImpl< void(Args...)>
class TIntrusiveListIterator
struct TIsUHTUEnum
struct TIsUHTUEnum< T, std::void_t< decltype(&T::StaticEnum)> >
struct TIsUHTUStruct
struct TIsUHTUStruct< T, std::void_t< decltype(&T::StaticStruct)> >
class TTransactionalAtomicRefCount
Functions
void CheckRefCountIsNonZero ()
UNREALED_API TSharedRef< SWindow > CreateModalDialogWindow (const FText &InTitle, TSharedRef< SWidget > Contents, ESizingRule Sizing, FVector2D MinDimensions)
template<typename Arg, typename... Args>
bool DoesParamMatch (const FProperty *Param)
template<typename T>
bool DoesReferencePropertyMatch (const T *Property, UClass *Type)
template<>
bool DoesReferencePropertyMatch< FClassProperty > (const FClassProperty *Property, UClass *Type)
template<>
bool DoesReferencePropertyMatch< FSoftClassProperty > (const FSoftClassProperty *Property, UClass *Type)
FORCEINLINE uint32 MurmurFinalize32 (uint32 Hash)
void SetMultiprocessId (int32 MultiprocessId)
UNREALED_API void ShowModalDialogWindow (TSharedRef< SWindow > Window)
UNREALED_API void ShowNonModalDialogWindow (TSharedRef< SWindow > Window)
Variables
class FMalloc * GMalloc
Detailed Description
The global memory allocator.
UE::Private::TTransactionalAtomicRefCount manages a transactionally-safe atomic refcount value.
Most callers should use FMemory::Malloc instead of accessing GMalloc directly. FMemory wraps GMalloc but also provides low-level memory tracking and AutoRTFM support.
This is used by FRefCountBase, FThreadSafeRefCountedObject and TRefCountingMixin (in thread-safe mode).
Function Documentation
CheckRefCountIsNonZero()
void UE::Private::CheckRefCountIsNonZero ()
Referenced by UE::Private::TTransactionalAtomicRefCount< uint32 >::ImmediatelyRelease(), and UE::Private::TTransactionalAtomicRefCount< uint32 >::Release().
CreateModalDialogWindow()
UNREALED_API TSharedRef< SWindow > UE::Private::CreateModalDialogWindow (const FText & InTitle, TSharedRef< SWidget > Contents, ESizingRule Sizing, FVector2D MinDimensions)
Referenced by SModalEditorDialog< ResultType >::ShowNonModal(), SModalEditorDialog< ResultType >::ShowNonModal(), and SModalEditorDialog< ResultType >::SLATE_END_ARGS().
DoesParamMatch()
template<typename Arg, typename... Args> bool UE::Private::DoesParamMatch (const FProperty * Param)
Definition at line 224 of file FunctionUtilsPrivate.h.
References UE::Private::TDoesParamMatchImpl< T >::DoesMatchProperty(), DoesParamMatch(), FProperty::HasAnyPropertyFlags(), and FField::Next.
Referenced by UE::Private::TDoesStaticFunctionSignatureMatchImpl< ReturnType(Args...)>::DoesMatch(), UE::Private::TDoesStaticFunctionSignatureMatchImpl< void(Args...)>::DoesMatch(), and DoesParamMatch().
DoesReferencePropertyMatch()
template<typename T> bool UE::Private::DoesReferencePropertyMatch (const T * Property, UClass * Type)
Definition at line 123 of file FunctionUtilsPrivate.h.
References check, and Property.
Referenced by UE::Private::TDoesParamMatchImpl< T< ReferenceType > >::DoesMatchProperty().
DoesReferencePropertyMatch< FClassProperty >()
template<> bool UE::Private::DoesReferencePropertyMatch< FClassProperty > (const FClassProperty * Property, UClass * Type)
Definition at line 129 of file FunctionUtilsPrivate.h.
References check, and Property.
DoesReferencePropertyMatch< FSoftClassProperty >()
template<> bool UE::Private::DoesReferencePropertyMatch< FSoftClassProperty > (const FSoftClassProperty * Property, UClass * Type)
Definition at line 135 of file FunctionUtilsPrivate.h.
References check, and Property.
MurmurFinalize32()
FORCEINLINE uint32 UE::Private::MurmurFinalize32 (uint32 Hash)
Definition at line 17 of file TypeHash.h.
References FORCEINLINE, and Hash.
Referenced by PointerHash().
SetMultiprocessId()
void UE::Private::SetMultiprocessId (int32 MultiprocessId)
ShowModalDialogWindow()
UNREALED_API void UE::Private::ShowModalDialogWindow (TSharedRef< SWindow > Window)
Referenced by SModalEditorDialog< ResultType >::SLATE_END_ARGS().
ShowNonModalDialogWindow()
UNREALED_API void UE::Private::ShowNonModalDialogWindow (TSharedRef< SWindow > Window)
Referenced by SModalEditorDialog< ResultType >::ShowNonModal(), and SModalEditorDialog< ResultType >::ShowNonModal().
Variable Documentation
GMalloc
class FMalloc* UE::Private::GMalloc extern
Referenced by UE::Tasks::Private::TExecutableTask< TaskBodyType >::operator delete(), and UE::Tasks::Private::TExecutableTask< TaskBodyType >::operator new().