Unreal Engine 5.6 C++ API: ENamedThreads Namespace Reference
ENamedThreads Namespace Reference
Forward declaration for ENamedThreads.
Data Structures
struct FRenderThreadStatics
Enumerations
enum Type : int32 {
UnusedAnchor = -1 , RHIThread , GameThread , ActualRenderingThread = GameThread + 1 ,
AnyThread = 0xff , MainQueue = 0x000 , LocalQueue = 0x100 , NumQueues = 2 ,
ThreadIndexMask = 0xff , QueueIndexMask = 0x100 , QueueIndexShift = 8 , NormalTaskPriority = 0x000 ,
HighTaskPriority = 0x200 , NumTaskPriorities = 2 , TaskPriorityMask = 0x200 , TaskPriorityShift = 9 ,
NormalThreadPriority = 0x000 , HighThreadPriority = 0x400 , BackgroundThreadPriority = 0x800 , NumThreadPriorities = 3 ,
ThreadPriorityMask = 0xC00 , ThreadPriorityShift = 10 , GameThread_Local = GameThread | LocalQueue , ActualRenderingThread_Local = ActualRenderingThread | LocalQueue ,
AnyHiPriThreadNormalTask = AnyThread | HighThreadPriority | NormalTaskPriority , AnyHiPriThreadHiPriTask = AnyThread | HighThreadPriority | HighTaskPriority , AnyNormalThreadNormalTask = AnyThread | NormalThreadPriority | NormalTaskPriority , AnyNormalThreadHiPriTask = AnyThread | NormalThreadPriority | HighTaskPriority ,
AnyBackgroundThreadNormalTask = AnyThread | BackgroundThreadPriority | NormalTaskPriority , AnyBackgroundHiPriTask = AnyThread | BackgroundThreadPriority | HighTaskPriority
}
Functions
FORCEINLINE int32 GetQueueIndex (Type ThreadAndIndex)
FORCEINLINE Type GetRenderThread ()
FORCEINLINE Type GetRenderThread_Local ()
FORCEINLINE int32 GetTaskPriority (Type ThreadAndIndex)
FORCEINLINE Type GetThreadIndex (Type ThreadAndIndex)
FORCEINLINE int32 GetThreadPriorityIndex (Type ThreadAndIndex)
FORCEINLINE Type SetPriorities (Type ThreadAndIndex, int32 PriorityIndex, bool bHiPri)
FORCEINLINE Type SetPriorities (Type ThreadAndIndex, Type ThreadPriority, Type TaskPriority)
FORCEINLINE void SetRenderThread (Type Thread)
FORCEINLINE void SetRenderThread_Local (Type Thread)
FORCEINLINE Type SetTaskPriority (Type ThreadAndIndex, Type TaskPriority)
FORCEINLINE Type SetThreadPriority (Type ThreadAndIndex, Type ThreadPriority)
Variables
int32 bHasBackgroundThreads
int32 bHasHighPriorityThreads
Detailed Description
Forward declaration for ENamedThreads.
Enumeration Type Documentation
Type
enum ENamedThreads::Type : int32
Enumerator
UnusedAnchor
RHIThread
The always-present, named threads are listed next.
GameThread
ActualRenderingThread
AnyThread
not actually a thread index.
Means "Unknown Thread" or "Any Unnamed Thread"
MainQueue
High bits are used for a queue index and priority.
LocalQueue
NumQueues
ThreadIndexMask
QueueIndexMask
QueueIndexShift
NormalTaskPriority
High bits are used for a queue index task priority and thread priority.
HighTaskPriority
NumTaskPriorities
TaskPriorityMask
TaskPriorityShift
NormalThreadPriority
HighThreadPriority
BackgroundThreadPriority
NumThreadPriorities
ThreadPriorityMask
ThreadPriorityShift
GameThread_Local
Combinations.
ActualRenderingThread_Local
AnyHiPriThreadNormalTask
AnyHiPriThreadHiPriTask
AnyNormalThreadNormalTask
AnyNormalThreadHiPriTask
AnyBackgroundThreadNormalTask
AnyBackgroundHiPriTask
Definition at line 56 of file TaskGraphInterfaces.h.
Function Documentation
GetQueueIndex()
FORCEINLINE int32 ENamedThreads::GetQueueIndex (Type ThreadAndIndex)
Definition at line 153 of file TaskGraphInterfaces.h.
References FORCEINLINE, QueueIndexMask, and QueueIndexShift.
GetRenderThread()
FORCEINLINE Type ENamedThreads::GetRenderThread ()
Definition at line 123 of file TaskGraphInterfaces.h.
Referenced by FRenderCommand::GetDesiredThread().
GetRenderThread_Local()
FORCEINLINE Type ENamedThreads::GetRenderThread_Local ()
Definition at line 128 of file TaskGraphInterfaces.h.
Referenced by ENUM_CLASS_FLAGS(), and FInitStaticResourceRenderThreadTask::GetDesiredThread().
GetTaskPriority()
FORCEINLINE int32 ENamedThreads::GetTaskPriority (Type ThreadAndIndex)
Definition at line 158 of file TaskGraphInterfaces.h.
References FORCEINLINE, TaskPriorityMask, and TaskPriorityShift.
GetThreadIndex()
FORCEINLINE Type ENamedThreads::GetThreadIndex (Type ThreadAndIndex)
Definition at line 148 of file TaskGraphInterfaces.h.
References AnyThread, FORCEINLINE, and ThreadIndexMask.
Referenced by FReturnGraphTask::DoTask().
GetThreadPriorityIndex()
FORCEINLINE int32 ENamedThreads::GetThreadPriorityIndex (Type ThreadAndIndex)
Definition at line 163 of file TaskGraphInterfaces.h.
References check, FORCEINLINE, NumThreadPriorities, ThreadPriorityMask, and ThreadPriorityShift.
SetPriorities() [1/2]
FORCEINLINE Type ENamedThreads::SetPriorities (Type ThreadAndIndex, int32 PriorityIndex, bool bHiPri)
Definition at line 181 of file TaskGraphInterfaces.h.
References check, FORCEINLINE, HighTaskPriority, NormalTaskPriority, NumThreadPriorities, ThreadIndexMask, and ThreadPriorityShift.
SetPriorities() [2/2]
FORCEINLINE Type ENamedThreads::SetPriorities (Type ThreadAndIndex, Type ThreadPriority, Type TaskPriority)
Definition at line 170 of file TaskGraphInterfaces.h.
References check, FORCEINLINE, TaskPriorityMask, ThreadIndexMask, and ThreadPriorityMask.
Referenced by FAutoConsoleTaskPriority::Get().
SetRenderThread()
FORCEINLINE void ENamedThreads::SetRenderThread (Type Thread)
Definition at line 133 of file TaskGraphInterfaces.h.
SetRenderThread_Local()
FORCEINLINE void ENamedThreads::SetRenderThread_Local (Type Thread)
Definition at line 138 of file TaskGraphInterfaces.h.
SetTaskPriority()
FORCEINLINE Type ENamedThreads::SetTaskPriority (Type ThreadAndIndex, Type TaskPriority)
Definition at line 200 of file TaskGraphInterfaces.h.
References check, FORCEINLINE, TaskPriorityMask, and ThreadIndexMask.
Referenced by FAutoConsoleTaskPriority::Get().
SetThreadPriority()
FORCEINLINE Type ENamedThreads::SetThreadPriority (Type ThreadAndIndex, Type ThreadPriority)
Definition at line 190 of file TaskGraphInterfaces.h.
References check, FORCEINLINE, ThreadIndexMask, and ThreadPriorityMask.
Variable Documentation
bHasBackgroundThreads
int32 ENamedThreads::bHasBackgroundThreads extern
Referenced by FAutoConsoleTaskPriority::Get().
bHasHighPriorityThreads
int32 ENamedThreads::bHasHighPriorityThreads extern
Referenced by FAutoConsoleTaskPriority::Get().