Unreal Engine 5.6 C++ API: UE::LWC Namespace Reference
UE::LWC Namespace Reference
Functions
template<typename TDest, typename TSrc, typename InAllocatorType>
TArray< TDest, InAllocatorType > ConvertArrayType (const TArray< TSrc, InAllocatorType > &From)
template<typename TDest, typename TSrc, typename InAllocatorType>
TArray< TDest, InAllocatorType > ConvertArrayTypeClampMax (const TArray< TSrc, InAllocatorType > &From)
template<>
FORCEINLINE int32 FloatToIntCastChecked (double FloatValue)
template<>
FORCEINLINE int64 FloatToIntCastChecked (double FloatValue)
template<>
FORCEINLINE int32 FloatToIntCastChecked (float FloatValue)
template<>
FORCEINLINE int64 FloatToIntCastChecked (float FloatValue)
template<typename OutIntType, typename InFloatType>
FORCEINLINE OutIntType FloatToIntCastChecked (InFloatType FloatValue)
FORCEINLINE FVector3f NarrowWorldPositionChecked (const FVector &WorldPosition)
FORCEINLINE FVector3f NarrowWorldPositionChecked (const FVector::FReal InX, const FVector::FReal InY, const FVector::FReal InZ)
Variables
constexpr FVector::FReal DefaultFloatPrecision = 1./16.
Function Documentation
ConvertArrayType()
template<typename TDest, typename TSrc, typename InAllocatorType> TArray< TDest, InAllocatorType > UE::LWC::ConvertArrayType (const TArray< TSrc, InAllocatorType > & From)
Definition at line 2622 of file UnrealMathUtility.h.
References Converted, Item, and TArray< InElementType, InAllocatorType >::Num().
ConvertArrayTypeClampMax()
template<typename TDest, typename TSrc, typename InAllocatorType> TArray< TDest, InAllocatorType > UE::LWC::ConvertArrayTypeClampMax (const TArray< TSrc, InAllocatorType > & From)
Definition at line 2643 of file UnrealMathUtility.h.
References Converted, Item, FMath::Min, and TArray< InElementType, InAllocatorType >::Num().
FloatToIntCastChecked() [1/5]
template<> FORCEINLINE int32 UE::LWC::FloatToIntCastChecked (double FloatValue)
Definition at line 2695 of file UnrealMathUtility.h.
References checkf, FORCEINLINE, and TEXT.
FloatToIntCastChecked() [2/5]
template<> FORCEINLINE int64 UE::LWC::FloatToIntCastChecked (double FloatValue)
Definition at line 2703 of file UnrealMathUtility.h.
References checkf, FORCEINLINE, and TEXT.
FloatToIntCastChecked() [3/5]
template<> FORCEINLINE int32 UE::LWC::FloatToIntCastChecked (float FloatValue)
Definition at line 2677 of file UnrealMathUtility.h.
References checkf, FORCEINLINE, and TEXT.
FloatToIntCastChecked() [4/5]
template<> FORCEINLINE int64 UE::LWC::FloatToIntCastChecked (float FloatValue)
Definition at line 2686 of file UnrealMathUtility.h.
References checkf, FORCEINLINE, and TEXT.
FloatToIntCastChecked() [5/5]
template<typename OutIntType, typename InFloatType> FORCEINLINE OutIntType UE::LWC::FloatToIntCastChecked (InFloatType FloatValue)
Definition at line 2668 of file UnrealMathUtility.h.
References FORCEINLINE.
NarrowWorldPositionChecked() [1/2]
FORCEINLINE FVector3f UE::LWC::NarrowWorldPositionChecked (const FVector & WorldPosition)
Definition at line 2772 of file Vector.h.
References DefaultFloatPrecision, FloatCastChecked(), FORCEINLINE, FVector, UE::Math::TVector< T >::X, UE::Math::TVector< T >::Y, and UE::Math::TVector< T >::Z.
NarrowWorldPositionChecked() [2/2]
FORCEINLINE FVector3f UE::LWC::NarrowWorldPositionChecked (const FVector::FReal InX, const FVector::FReal InY, const FVector::FReal InZ)
Definition at line 2782 of file Vector.h.
References DefaultFloatPrecision, FloatCastChecked(), FORCEINLINE, UE::Math::TVector< T >::X, UE::Math::TVector< T >::Y, and UE::Math::TVector< T >::Z.
Variable Documentation
DefaultFloatPrecision
FVector::FReal UE::LWC::DefaultFloatPrecision = 1./16. inline constexpr
Definition at line 2769 of file Vector.h.
Referenced by NarrowWorldPositionChecked(), and NarrowWorldPositionChecked().