Unreal Engine 5.6 C++ API: UE::Landscape Namespace Reference
UE::Landscape Namespace Reference
Namespaces
namespace EditLayers
namespace Grass
namespace Nanite
Data Structures
class FBatchTextureCopy
struct FHeightmapTexel
struct FNeighborSnapshots
class FRDGBuilderRecorder
This struct is usually meant to be allocated on the game thread (where there's no FRDGBuilder, which is Render Thread-only) and allows to queue successive operations (lambdas) onto a single render command, sharing the same FRDGBuilder.
struct FTextureCopyChannelMapping
Represents the DestinationChannel->SourceChannel binding.DestinationChannel is used as index.
struct FTextureCopyRequest
Typedefs
typedef EDirectionFlags EEdgeFlags
typedef EDirectionIndex EEdgeIndex
typedef EDirectionFlags ENeighborFlags
typedef EDirectionIndex ENeighborIndex
Enumerations
enum class EBuildFlags : uint8 { None = 0 , WriteFinalLog = (1 << 0) , ForceRebuild = (1 << 1) }
enum class EDirectionFlags : uint8 {
Bottom = 0x00000001 , BottomRight = 0x00000002 , Right = 0x00000004 , TopRight = 0x00000008 ,
Top = 0x00000010 , TopLeft = 0x00000020 , Left = 0x00000040 , BottomLeft = 0x00000080 ,
None = 0 , AllCorners = BottomRight | TopRight | TopLeft | BottomLeft , AllEdges = Bottom | Right | Top | Left , All = AllEdges | AllCorners
}
enum class EDirectionIndex : uint8 {
Bottom = 0 , BottomRight = 1 , Right = 2 , TopRight = 3 ,
Top = 4 , TopLeft = 5 , Left = 6 , BottomLeft = 7 ,
First = 0 , Last = 7 , Count = 8 , FirstEdge = 0 ,
LastEdge = 6 , EdgeCount = 4 , FirstCorner = 1 , LastCorner = 7 ,
CornerCount = 4
}
enum class EOutdatedDataFlags : uint8 {
None = 0 , GrassMaps = (1 << 0) , PhysicalMaterials = (1 << 1) , NaniteMeshes = (1 << 2) ,
PackageModified = (1 << 3) , LastPlusOne , Last = LastPlusOne - 1 , All = (GrassMaps | PhysicalMaterials | NaniteMeshes | PackageModified)
}
Functions
void LANDSCAPE_API BuildAll (EBuildFlags InBuildFlags)
void LANDSCAPE_API BuildGrassMaps (EBuildFlags InBuildFlags)
void LANDSCAPE_API BuildNanite (EBuildFlags InBuildFlags)
void LANDSCAPE_API BuildPhysicalMaterial (EBuildFlags InBuildFlags)
LANDSCAPE_API bool CanRenderGrassMap (ULandscapeComponent *Component)
LANDSCAPE_API FString ConvertTargetLayerNamesToString (const TArrayView< const FName > &InTargetLayerNames)
Concatenates the target layer names in parameter into a string.
LANDSCAPE_API ULandscapeMaterialInstanceConstant * CreateLandscapeLayerThumbnailMIC (FMaterialUpdateContext &MaterialUpdateContext, UMaterialInterface *LandscapeMaterial, FName LayerName)
Create a thumbnail material for a given layer.
LANDSCAPE_API ULandscapeLayerInfoObject * CreateTargetLayerInfo (const FName &InLayerName, const FString &InFilePath)
Creates a new layer info object, using the default template if available, or a new empty one.
LANDSCAPE_API ULandscapeLayerInfoObject * CreateTargetLayerInfo (const FName &InLayerName, const FString &InFilePath, const FString &InFileName)
Creates a new layer info object, using the default template if available, or a new empty one at the path: InFilePath/InFilename.
LANDSCAPE_API UMaterialInstance * CreateToolLandscapeMaterialInstanceConstant (UMaterialInterface *BaseMaterial)
Returns a pointer to a newly created ULandscapeMaterialInstanceConstant.
LANDSCAPE_API bool DeleteActors (const TArray< AActor * > &InActorsToDelete, UWorld *InWorld, bool bInAllowUI)
Helper to delete one or multiple actors.
LANDSCAPE_API bool DoesPlatformSupportEditLayers (EShaderPlatform InShaderPlatform)
Returns true if edit layers (GPU landscape tools) are enabled on this platform : Note: this is intended for the editor but is in runtime code since global shaders need to exist in runtime modules.
ENeighborFlags EdgesToAffectedNeighbors (EEdgeFlags LocalEdgeFlags)
ENUM_CLASS_FLAGS (EOutdatedDataFlags)
const FString & GetDirectionString (EDirectionIndex Index)
LANDSCAPE_API ELandscapeToolTargetTypeFlags GetLandscapeToolTargetTypeAsFlags (ELandscapeToolTargetType InTargetType)
LANDSCAPE_API FString GetLandscapeToolTargetTypeFlagsAsString (ELandscapeToolTargetTypeFlags InTargetTypeFlags)
LANDSCAPE_API ELandscapeToolTargetType GetLandscapeToolTargetTypeSingleFlagAsType (ELandscapeToolTargetTypeFlags InSingleFlag)
LANDSCAPE_API FString GetLayerInfoObjectPackageName (const FName &InLayerName, const FString &InPackagePath, FName &OutLayerObjectName)
Returns a generated package name for a Layer Info Object.
FIntPoint GetNeighborRelativePosition (ENeighborIndex NeighborIndex)
uint32 GetOutdatedDataFlagIndex (EOutdatedDataFlags InFlag)
LANDSCAPE_API FString GetSharedAssetsPath (const FString &InPath)
Returns a generated path used for Landscape Shared Assets.
LANDSCAPE_API FString GetSharedAssetsPath (const ULevel *InLevel)
Returns a generated path used for Landscape Shared Assets.
uint32 GetTypeHash (const FTextureCopyRequest &InKey)
bool LANDSCAPE_API HasModifiedLandscapes ()
Returns true if there are some landscapes in the editor world that have been automatically modified and are in need of being saved (see LandscapeDirtyingMode)
LANDSCAPE_API bool IsRuntimeGrassMapGenerationSupported ()
LANDSCAPE_API bool IsVisibilityLayer (const ULandscapeLayerInfoObject *InLayerInfoObject)
Returns true if the provided layer info object is the current visibility layer.
void LANDSCAPE_API MarkModifiedLandscapesAsDirty (EBuildFlags InBuildFlags)
bool NeedsFixedGridVertexFactory (EShaderPlatform InShaderPlatform)
bool operator== (const FTextureCopyRequest &InEntryA, const FTextureCopyRequest &InEntryB)
void LANDSCAPE_API SaveModifiedLandscapes (EBuildFlags InBuildFlags)
Dirties and saves the landscapes in the editor world that have been automatically modified and are in need of being saved (see LandscapeDirtyingMode)
bool ShouldBuildGrassMapRenderingResources ()
EDirectionFlags ToFlag (EDirectionIndex Index)
UE_DEPRECATED (5.6, "This Get function is deprecated. Please use new GetLayerInfo and pass in a full asset package path.") LANDSCAPE_API FString GetLayerInfoObjectPackageName(const ULevel *InLevel
Returns a generated package name for a Layer Info Object.
struct UE_DEPRECATED (5.6, "This helper struct is deprecated. Please use utility methods in LandscapeEditorUtils.") FLayerInfoFinder
UE_DEPRECATED (5.6, "Use the function with the EBuildFlags param") void LANDSCAPE_API MarkModifiedLandscapesAsDirty()
struct UE_EXPERIMENTAL (5.5, "Landscape edit layers batched merge is still being actively developed, this API may change.") FScratchRenderTargetParams
Variables
const FName & InLayerName
const FName FName & OutLayerObjectName
Typedef Documentation
EEdgeFlags
typedef EDirectionFlags UE::Landscape::EEdgeFlags
Definition at line 64 of file LandscapeEdgeFixup.h.
EEdgeIndex
typedef EDirectionIndex UE::Landscape::EEdgeIndex
Definition at line 63 of file LandscapeEdgeFixup.h.
ENeighborFlags
typedef EDirectionFlags UE::Landscape::ENeighborFlags
Definition at line 66 of file LandscapeEdgeFixup.h.
ENeighborIndex
typedef EDirectionIndex UE::Landscape::ENeighborIndex
Definition at line 65 of file LandscapeEdgeFixup.h.
Enumeration Type Documentation
EBuildFlags
enum class UE::Landscape::EBuildFlags : uint8 strong
Enumerator
None
WriteFinalLog
ForceRebuild
Definition at line 67 of file LandscapeEditTypes.h.
EDirectionFlags
enum class UE::Landscape::EDirectionFlags : uint8 strong
Enumerator
Bottom
BottomRight
Right
TopRight
Top
TopLeft
Left
BottomLeft
None
AllCorners
AllEdges
All
Definition at line 46 of file LandscapeEdgeFixup.h.
EDirectionIndex
enum class UE::Landscape::EDirectionIndex : uint8 strong
Enumerator
Bottom
BottomRight
Right
TopRight
Top
TopLeft
Left
BottomLeft
First
Last
Count
FirstEdge
LastEdge
EdgeCount
FirstCorner
LastCorner
CornerCount
Definition at line 21 of file LandscapeEdgeFixup.h.
EOutdatedDataFlags
enum class UE::Landscape::EOutdatedDataFlags : uint8 strong
Enumerator
None
GrassMaps
PhysicalMaterials
NaniteMeshes
PackageModified
LastPlusOne
Last
All
Definition at line 41 of file LandscapeEditTypes.h.
Function Documentation
BuildAll()
void LANDSCAPE_API UE::Landscape::BuildAll (EBuildFlags InBuildFlags)
References BuildAll().
Referenced by BuildAll(), and BuildNanite().
BuildGrassMaps()
void LANDSCAPE_API UE::Landscape::BuildGrassMaps (EBuildFlags InBuildFlags)
References BuildGrassMaps(), BuildPhysicalMaterial(), and UE_DEPRECATED().
Referenced by BuildGrassMaps(), and MarkModifiedLandscapesAsDirty().
BuildNanite()
void LANDSCAPE_API UE::Landscape::BuildNanite (EBuildFlags InBuildFlags)
References BuildAll(), BuildNanite(), and UE_DEPRECATED().
Referenced by BuildNanite(), and BuildPhysicalMaterial().
BuildPhysicalMaterial()
void LANDSCAPE_API UE::Landscape::BuildPhysicalMaterial (EBuildFlags InBuildFlags)
References BuildNanite(), BuildPhysicalMaterial(), and UE_DEPRECATED().
Referenced by BuildGrassMaps(), and BuildPhysicalMaterial().
CanRenderGrassMap()
LANDSCAPE_API bool UE::Landscape::CanRenderGrassMap (ULandscapeComponent * Component)
References Component.
ConvertTargetLayerNamesToString()
LANDSCAPE_API FString UE::Landscape::ConvertTargetLayerNamesToString (const TArrayView< const FName > & InTargetLayerNames)
Concatenates the target layer names in parameter into a string.
CreateLandscapeLayerThumbnailMIC()
LANDSCAPE_API ULandscapeMaterialInstanceConstant * UE::Landscape::CreateLandscapeLayerThumbnailMIC (FMaterialUpdateContext & MaterialUpdateContext, UMaterialInterface * LandscapeMaterial, FName LayerName)
Create a thumbnail material for a given layer.
Can return nullptr if the option to disable landscape thumbnails has been turned on
CreateTargetLayerInfo() [1/2]
LANDSCAPE_API ULandscapeLayerInfoObject * UE::Landscape::CreateTargetLayerInfo (const FName & InLayerName, const FString & InFilePath)
Creates a new layer info object, using the default template if available, or a new empty one.
Sets asset file name as LayerName_LayerInfo_d
Parameters
InLayerName The layer name of the created asset info
InFilePath New asset file path, typically is CurrentLevel/SharedAssetPath or the LandscapeEditorObject->TargetLayerAssetFilePath->DirectoryPath
Returns
a new LandscapeLayerInfoObject.
References CreateTargetLayerInfo(), and InLayerName.
Referenced by CreateTargetLayerInfo(), and CreateTargetLayerInfo().
CreateTargetLayerInfo() [2/2]
LANDSCAPE_API ULandscapeLayerInfoObject * UE::Landscape::CreateTargetLayerInfo (const FName & InLayerName, const FString & InFilePath, const FString & InFileName)
Creates a new layer info object, using the default template if available, or a new empty one at the path: InFilePath/InFilename.
Parameters
InLayerName The layer name of the created asset info
InFilePath New asset file path, typically is CurrentLevel/SharedAssetPath or the LandscapeEditorObject->TargetLayerAssetFilePath->DirectoryPath
InFileName The unique file name of the created asset
Returns
a new LandscapeLayerInfoObject.
References CreateTargetLayerInfo(), and InLayerName.
CreateToolLandscapeMaterialInstanceConstant()
LANDSCAPE_API UMaterialInstance * UE::Landscape::CreateToolLandscapeMaterialInstanceConstant (UMaterialInterface * BaseMaterial)
Returns a pointer to a newly created ULandscapeMaterialInstanceConstant.
Parameters
BaseMaterial The base material appended to the debug name and set as parent of MaterialInstance
Returns
Pointer to ULandscapeMaterialInstanceConstant
DeleteActors()
LANDSCAPE_API bool UE::Landscape::DeleteActors (const TArray< AActor * > & InActorsToDelete, UWorld * InWorld, bool bInAllowUI)
Helper to delete one or multiple actors.
Parameters
InActorsToDelete the list of actors to delete. Cannot contain null entries and all actors should be part of the world passed in InWorld
InWorld world to which all actors to be deleted belong
bInAllowUI allows the standard delete actors UX to be displayed, allowing the user to remove lingering reference to these actors, etc.
Returns
true if all actors could be properly deleted
DoesPlatformSupportEditLayers()
LANDSCAPE_API bool UE::Landscape::DoesPlatformSupportEditLayers (EShaderPlatform InShaderPlatform)
Returns true if edit layers (GPU landscape tools) are enabled on this platform : Note: this is intended for the editor but is in runtime code since global shaders need to exist in runtime modules.
EdgesToAffectedNeighbors()
ENeighborFlags UE::Landscape::EdgesToAffectedNeighbors (EEdgeFlags LocalEdgeFlags)
ENUM_CLASS_FLAGS()
UE::Landscape::ENUM_CLASS_FLAGS (EOutdatedDataFlags)
GetDirectionString()
const FString & UE::Landscape::GetDirectionString (EDirectionIndex Index)
GetLandscapeToolTargetTypeAsFlags()
LANDSCAPE_API ELandscapeToolTargetTypeFlags UE::Landscape::GetLandscapeToolTargetTypeAsFlags (ELandscapeToolTargetType InTargetType)
GetLandscapeToolTargetTypeFlagsAsString()
LANDSCAPE_API FString UE::Landscape::GetLandscapeToolTargetTypeFlagsAsString (ELandscapeToolTargetTypeFlags InTargetTypeFlags)
GetLandscapeToolTargetTypeSingleFlagAsType()
LANDSCAPE_API ELandscapeToolTargetType UE::Landscape::GetLandscapeToolTargetTypeSingleFlagAsType (ELandscapeToolTargetTypeFlags InSingleFlag)
GetLayerInfoObjectPackageName()
LANDSCAPE_API FString UE::Landscape::GetLayerInfoObjectPackageName (const FName & InLayerName, const FString & InPackagePath, FName & OutLayerObjectName)
Returns a generated package name for a Layer Info Object.
Parameters
InLayerName The LayerName of the Layer Info Object
InPackagePath Base package path that will be used, should be Current Level SharedAssetPath or the LandscapeEditorObject->TargetLayerAssetFilePath
OutLayerObjectName The generated object name for Layer Info Object
References InLayerName, and OutLayerObjectName.
GetNeighborRelativePosition()
FIntPoint UE::Landscape::GetNeighborRelativePosition (ENeighborIndex NeighborIndex)
GetOutdatedDataFlagIndex()
uint32 UE::Landscape::GetOutdatedDataFlagIndex (EOutdatedDataFlags InFlag) inline
Definition at line 60 of file LandscapeEditTypes.h.
References check, LastPlusOne, and None.
GetSharedAssetsPath() [1/2]
LANDSCAPE_API FString UE::Landscape::GetSharedAssetsPath (const FString & InPath)
Returns a generated path used for Landscape Shared Assets.
Parameters
InPath Path used as a basis to generate shared assets path. If /Temp/, it will be replaced by the last valid path used for level.
Returns
Path used for Landscape Shared Assets
GetSharedAssetsPath() [2/2]
LANDSCAPE_API FString UE::Landscape::GetSharedAssetsPath (const ULevel * InLevel)
Returns a generated path used for Landscape Shared Assets.
Parameters
InLevel Level's Path will be used as a basis to generate shared assets path. If /Temp/, it will be replaced by the last valid path used for level.
Returns
Path used for Landscape Shared Assets
GetTypeHash()
uint32 UE::Landscape::GetTypeHash (const FTextureCopyRequest & InKey)
HasModifiedLandscapes()
bool LANDSCAPE_API UE::Landscape::HasModifiedLandscapes ()
Returns true if there are some landscapes in the editor world that have been automatically modified and are in need of being saved (see LandscapeDirtyingMode)
IsRuntimeGrassMapGenerationSupported()
LANDSCAPE_API bool UE::Landscape::IsRuntimeGrassMapGenerationSupported ()
IsVisibilityLayer()
LANDSCAPE_API bool UE::Landscape::IsVisibilityLayer (const ULandscapeLayerInfoObject * InLayerInfoObject)
Returns true if the provided layer info object is the current visibility layer.
References Find, IsVisibilityLayer(), and UE_DEPRECATED().
Referenced by IsVisibilityLayer().
MarkModifiedLandscapesAsDirty()
void LANDSCAPE_API UE::Landscape::MarkModifiedLandscapesAsDirty (EBuildFlags InBuildFlags)
References BuildGrassMaps(), MarkModifiedLandscapesAsDirty(), and UE_DEPRECATED().
Referenced by MarkModifiedLandscapesAsDirty(), and UE_DEPRECATED().
NeedsFixedGridVertexFactory()
bool UE::Landscape::NeedsFixedGridVertexFactory (EShaderPlatform InShaderPlatform)
operator==()
bool UE::Landscape::operator== (const FTextureCopyRequest & InEntryA, const FTextureCopyRequest & InEntryB)
SaveModifiedLandscapes()
void LANDSCAPE_API UE::Landscape::SaveModifiedLandscapes (EBuildFlags InBuildFlags)
Dirties and saves the landscapes in the editor world that have been automatically modified and are in need of being saved (see LandscapeDirtyingMode)
ShouldBuildGrassMapRenderingResources()
bool UE::Landscape::ShouldBuildGrassMapRenderingResources ()
ToFlag()
EDirectionFlags UE::Landscape::ToFlag (EDirectionIndex Index)
UE_DEPRECATED() [1/3]
UE::Landscape::UE_DEPRECATED (5. 6, "This Get function is deprecated. Please use new GetLayerInfo and pass in a full asset package path.") const
Returns a generated package name for a Layer Info Object.
Parameters
InLevel Level's Path will be used as a basis to generate package's path. If /Temp/, it will be replaced by the last valid path used for level.
InLayerName The LayerName of the Layer Info Object
OutLayerObjectName The generated object name for Layer Info Object
Returns
UE_DEPRECATED() [2/3]
struct UE::Landscape::UE_DEPRECATED (5. 6, "This helper struct is deprecated. Please use utility methods in LandscapeEditorUtils.")
Definition at line 335 of file LandscapeUtils.h.
UE_DEPRECATED() [3/3]
UE::Landscape::UE_DEPRECATED (5. 6, "Use the function with the EBuildFlags param")
References MarkModifiedLandscapesAsDirty().
Referenced by BuildGrassMaps(), BuildNanite(), BuildPhysicalMaterial(), IsVisibilityLayer(), and MarkModifiedLandscapesAsDirty().
UE_EXPERIMENTAL()
struct UE::Landscape::UE_EXPERIMENTAL (5. 5, "Landscape edit layers batched merge is still being actively developed, this API may change.")
Allows to specify a friendly name for this render target (for the duration that the scratch render target is in use : a new name will be used the next time it's recycled)
Use this to make sure the returned render target has the exact dimension as was requested (if false, a larger RT might be recycled)
Requires the render target to have the ETextureCreateFlags::UAV flag
Requires the render target to have the ETextureCreateFlags::TargetArraySlicesIndependently flag
Requested (minimal) resolution for this render target
Number of slices requested for this render target. 0 means the render target will be a UTextureRenderTarget2D, > 0 means it will be a UTextureRenderTarget2DArray
Format of the requested render target
Default clear color of the requested render target
(optional) State the render target should be in when it's being requested
Definition at line 259 of file LandscapeEditResourcesSubsystem.h.
References GENERATED_BODY, Initialize, Transient, and UPROPERTY.
Variable Documentation
InLayerName
const FName& UE::Landscape::InLayerName
Definition at line 315 of file LandscapeUtils.h.
Referenced by CreateTargetLayerInfo(), CreateTargetLayerInfo(), and GetLayerInfoObjectPackageName().
OutLayerObjectName
const FName FName& UE::Landscape::OutLayerObjectName
Definition at line 315 of file LandscapeUtils.h.
Referenced by GetLayerInfoObjectPackageName().