Unreal Engine 5.6 C++ API: SharedPointerInternals Namespace Reference
SharedPointerInternals Namespace Reference
SharedPointerInternals contains internal workings of shared and weak pointers.
Data Structures
struct DefaultDeleter
Deletes an object via the standard delete operator.
struct FConstCastTag
struct FNullTag
class FSharedReferencer
FSharedReferencer is a wrapper around a pointer to a reference controller that is used by either a TSharedRef or a TSharedPtr to keep track of a referenced object's lifetime.
struct FStaticCastTag
Dummy structures used internally as template arguments for typecasts.
class FWeakReferencer
FWeakReferencer is a wrapper around a pointer to a reference controller that is used by a TWeakPtr to keep track of a referenced object's lifetime.
struct TDeleterHolder
struct TDeleterHolder< DeleterType, false >
class TIntrusiveReferenceController
struct TRawPtrProxy
Proxy structure for implicitly converting raw pointers to shared/weak pointers.
struct TRawPtrProxyWithDeleter
Proxy structure for implicitly converting raw pointers to shared/weak pointers.
class TReferenceControllerBase
class TReferenceControllerWithDeleter
Functions
template<class SharedPtrType, class ObjectType>
FORCEINLINE void EnableSharedFromThis (SharedPtrType *InSharedPtrOrRef, ObjectType const *InObject)
Templated helper function (const) that creates a shared pointer from an object instance.
template<ESPMode Mode, typename ObjectType, typename DeleterType>
TReferenceControllerBase< Mode > * NewCustomReferenceController (ObjectType *Object, DeleterType &&Deleter)
Creates a custom reference controller with a specified deleter.
template<ESPMode Mode, typename ObjectType>
TReferenceControllerBase< Mode > * NewDefaultReferenceController (ObjectType *Object)
Creates a reference controller which just calls delete.
template<ESPMode Mode, typename ObjectType, typename... ArgTypes>
TIntrusiveReferenceController< ObjectType, Mode > * NewIntrusiveReferenceController (ArgTypes &&... Args)
Creates an intrusive reference controller.
Detailed Description
SharedPointerInternals contains internal workings of shared and weak pointers.
You should hopefully never have to use anything inside this namespace directly.
Function Documentation
EnableSharedFromThis()
template<class SharedPtrType, class ObjectType> FORCEINLINE void SharedPointerInternals::EnableSharedFromThis (SharedPtrType * InSharedPtrOrRef, ObjectType const * InObject)
Templated helper function (const) that creates a shared pointer from an object instance.
Definition at line 858 of file SharedPointerInternals.h.
References FORCEINLINE, and IsDerivedFromSharedFromThis().
Referenced by TSharedPtr< FAnimNextTraitEvent, ESPMode::ThreadSafe >::TSharedPtr(), TSharedPtr< FAnimNextTraitEvent, ESPMode::ThreadSafe >::TSharedPtr(), TSharedPtr< FAnimNextTraitEvent, ESPMode::ThreadSafe >::TSharedPtr(), TSharedPtr< FAnimNextTraitEvent, ESPMode::ThreadSafe >::TSharedPtr(), TSharedPtr< FAnimNextTraitEvent, ESPMode::ThreadSafe >::TSharedPtr(), TSharedRef< INavigationToolItem >::TSharedRef(), TSharedRef< INavigationToolItem >::TSharedRef(), TSharedRef< INavigationToolItem >::TSharedRef(), and TSharedRef< INavigationToolItem >::Init().
NewCustomReferenceController()
template<ESPMode Mode, typename ObjectType, typename DeleterType> TReferenceControllerBase< Mode > * SharedPointerInternals::NewCustomReferenceController (ObjectType * Object, DeleterType && Deleter) inline
Creates a custom reference controller with a specified deleter.
Definition at line 456 of file SharedPointerInternals.h.
References Forward(), and Object.
NewDefaultReferenceController()
template<ESPMode Mode, typename ObjectType> TReferenceControllerBase< Mode > * SharedPointerInternals::NewDefaultReferenceController (ObjectType * Object) inline
Creates a reference controller which just calls delete.
Definition at line 449 of file SharedPointerInternals.h.
References Object.
NewIntrusiveReferenceController()
template<ESPMode Mode, typename ObjectType, typename... ArgTypes> TIntrusiveReferenceController< ObjectType, Mode > * SharedPointerInternals::NewIntrusiveReferenceController (ArgTypes &&... Args) inline
Creates an intrusive reference controller.
Definition at line 463 of file SharedPointerInternals.h.
References Forward().
Referenced by MakeShared().