Unreal Engine 5.6 C++ API: HarmonixDsp Namespace Reference
HarmonixDsp Namespace Reference
Namespaces
namespace FAudioBuffer
Functions
float ClampDB (float dB)
float dBFS (float Linear)
float DBToLinear (float dB)
int8 DBToMidiLinear (float dB)
float FRandSample ()
void GenerateA220Sawtooth (float *Output, uint32 NumFrames, uint32 SampleRate)
HARMONIXDSP_API void GenerateSine (float *Output, uint32 NumFrames, float Frequency, float SampleRate, float &Phase)
Fill a mono output buffer with a sine wave.
HARMONIXDSP_API void GenerateWhiteNoise (float *Output, uint32 NumFrames, float Gain=1.0f)
fill an output buffer with random sample samples are in the range [-gain, gain]
HARMONIXDSP_API void GenerateWhiteNoise (int16 *Output, uint32 NumFrames, float Gain=1.0f)
template<class T>
void GenerateWhiteNoiseEq (T *Output, uint32 NumFrames, float Gain)
float LinearToDB (float Gain)
double Log10 (double Value)
float Log10 (float Value)
float MapLinearToDecibelRange (float ValueLinear, float MaxDecibels, float RangeDecibels)
float Midi14BitLinearToDB (int32 Level)
float MidiLinearToDB (int8 Level)
void PanToGainsConstantPower (float Pan, float &OutLeftGain, float &OutRightGain)
Variables
const float kCentsPerOctave = 1200.0f
static const float kDbMax = 12.0f
static const float kDbMin = -10000.0f
static const float kDbSilence = -96.0f
const float kOctavesPerCent = 1.0f / kCentsPerOctave
const float kTinyGain = 0.00001f
Function Documentation
ClampDB()
float HarmonixDsp::ClampDB (float dB) inline
Definition at line 44 of file AudioUtility.h.
References FMath::Clamp(), kDbMax, and kDbSilence.
dBFS()
float HarmonixDsp::dBFS (float Linear) inline
Definition at line 91 of file AudioUtility.h.
References kDbMin, Linear, and Log10().
Referenced by FMusicalAudioBus::GetAudioLevel().
DBToLinear()
float HarmonixDsp::DBToLinear (float dB) inline
Definition at line 49 of file AudioUtility.h.
DBToMidiLinear()
int8 HarmonixDsp::DBToMidiLinear (float dB) inline
Definition at line 54 of file AudioUtility.h.
References Max, and MAX_int8.
FRandSample()
float HarmonixDsp::FRandSample () inline
Definition at line 109 of file AudioUtility.h.
References checkSlow, and X.
GenerateA220Sawtooth()
void HarmonixDsp::GenerateA220Sawtooth (float * Output, uint32 NumFrames, uint32 SampleRate)
References NumFrames.
GenerateSine()
HARMONIXDSP_API void HarmonixDsp::GenerateSine (float * Output, uint32 NumFrames, float Frequency, float SampleRate, float & Phase)
Fill a mono output buffer with a sine wave.
Parameters
Output - The output buffer
NumFrames - The number of sample frames to generate
Frequency - The frequency of the sine wave
SampleRate - The sample rate at which to generate the sine wave
Phase - The phase to start (and to use for future calls if desired)
References Frequency, and NumFrames.
GenerateWhiteNoise() [1/2]
HARMONIXDSP_API void HarmonixDsp::GenerateWhiteNoise (float * Output, uint32 NumFrames, float Gain = 1.0f)
fill an output buffer with random sample samples are in the range [-gain, gain]
Parameters
output the buffer of floating point samples to write to
numFrames the number of samples to write
gain (optional) the upper range of the samples. defaults to one.
References NumFrames.
Referenced by GenerateWhiteNoiseEq().
GenerateWhiteNoise() [2/2]
HARMONIXDSP_API void HarmonixDsp::GenerateWhiteNoise (int16 * Output, uint32 NumFrames, float Gain = 1.0f)
References NumFrames.
GenerateWhiteNoiseEq()
template<class T> void HarmonixDsp::GenerateWhiteNoiseEq (T * Output, uint32 NumFrames, float Gain)
Definition at line 22 of file Generate.h.
References GenerateWhiteNoise(), and NumFrames.
Referenced by TAudioBuffer< DataType >::FillWithWhiteNoise().
LinearToDB()
float HarmonixDsp::LinearToDB (float Gain) inline
Definition at line 60 of file AudioUtility.h.
References kDbSilence, and Log10().
Referenced by Harmonix::Dsp::Effects::TMultiChannelBiquadFilter< T, COUNT >::SetTargetGain().
Log10() [1/2]
double HarmonixDsp::Log10 (double Value) inline
Definition at line 39 of file AudioUtility.h.
References Value.
Log10() [2/2]
float HarmonixDsp::Log10 (float Value) inline
Definition at line 34 of file AudioUtility.h.
References Value.
Referenced by dBFS(), LinearToDB(), Midi14BitLinearToDB(), and MidiLinearToDB().
MapLinearToDecibelRange()
float HarmonixDsp::MapLinearToDecibelRange (float ValueLinear, float MaxDecibels, float RangeDecibels)
Midi14BitLinearToDB()
float HarmonixDsp::Midi14BitLinearToDB (int32 Level) inline
Definition at line 80 of file AudioUtility.h.
References kDbSilence, Log10(), Max, and MAX_int16.
MidiLinearToDB()
float HarmonixDsp::MidiLinearToDB (int8 Level) inline
Definition at line 70 of file AudioUtility.h.
References kDbSilence, Log10(), Max, and MAX_int8.
PanToGainsConstantPower()
void HarmonixDsp::PanToGainsConstantPower (float Pan, float & OutLeftGain, float & OutRightGain) inline
Definition at line 117 of file AudioUtility.h.
References FMath::IsNearlyZero(), kTinyGain, and UE_HALF_PI.
Variable Documentation
kCentsPerOctave
const float HarmonixDsp::kCentsPerOctave = 1200.0f
Definition at line 24 of file AudioUtility.h.
kDbMax
const float HarmonixDsp::kDbMax = 12.0f static
Definition at line 22 of file AudioUtility.h.
Referenced by ClampDB().
kDbMin
const float HarmonixDsp::kDbMin = -10000.0f static
Definition at line 18 of file AudioUtility.h.
Referenced by dBFS().
kDbSilence
const float HarmonixDsp::kDbSilence = -96.0f static
Definition at line 20 of file AudioUtility.h.
Referenced by ClampDB(), FMusicalAudioBus::GetAudioLevel(), LinearToDB(), Midi14BitLinearToDB(), and MidiLinearToDB().
kOctavesPerCent
const float HarmonixDsp::kOctavesPerCent = 1.0f / kCentsPerOctave
Definition at line 25 of file AudioUtility.h.
kTinyGain
const float HarmonixDsp::kTinyGain = 0.00001f
Definition at line 32 of file AudioUtility.h.
Referenced by FGainMatrix::ApplyAndAccumulateToBuffer(), FGainMatrix::ApplyToBuffer(), FGainMatrix::PanSample(), and PanToGainsConstantPower().