Unreal Engine 5.6 C++ API: ObjectPtr_Private Namespace Reference
ObjectPtr_Private Namespace Reference
Data Structures
struct Friend
class TNonAccessTrackedObjectPtr
struct TRawPointerType
struct TRawPointerType< const TObjectPtr< T > >
struct TRawPointerType< const volatile TObjectPtr< T > >
struct TRawPointerType< TObjectPtr< T > >
struct TRawPointerType< volatile TObjectPtr< T > >
Functions
template<typename T>
FORCEINLINE const T * CoerceToPointer (const T *Other)
Coerce to pointer through implicit conversion to const T* (overload through less specific "const T*" parameter to avoid ambiguity with other coercion options that may also exist.
template<typename T, typename U UE_REQUIRES>
FORCEINLINE std::common_type_t< const T *, U > CoerceToPointer (const U &Other)
Coerce to pointer through implicit conversion to CommonPointerType where CommonPointerType is deduced, and must be a C++ pointer, not a wrapper type.
template<typename T, typename U UE_REQUIRES>
FORCEINLINE auto CoerceToPointer (const U &Other) -> decltype(Other.Get())
Coerce to pointer through the use of a ".Get()" member, which is the convention within Unreal smart pointer types.
template<typename T>
FORCEINLINE T * Get (const FObjectPtr &ObjectPtr)
Resolve and return the underlying reference.
template<typename T, typename U, decltype(CoerceToPointer< T >(std::declval< U >())==std::declval< const T * >()) * = nullptr UE_REQUIRES(!TIsTObjectPtr_V<U>)>
bool IsObjectPtrEqual (const TObjectPtr< T > &Ptr, const U &Other)
Perform shallow equality check between a TObjectPtr and another (non TObjectPtr) type that we can coerce to a pointer.
template<typename T, typename U>
bool IsObjectPtrEqualToRawPtrOfRelatedType (const TObjectPtr< T > &Ptr, const U *Other)
template<typename T>
FORCEINLINE bool IsObjectPtrNull (const FObjectPtr &ObjectPtr)
Check for NULL without resolving the handle.
template<typename T>
char(& ResolveTypeIsComplete (...))[1]
template<typename T, int = sizeof(T)>
char(& ResolveTypeIsComplete (int))[2]
Function Documentation
CoerceToPointer() [1/3]
template<typename T> FORCEINLINE const T * ObjectPtr_Private::CoerceToPointer (const T * Other)
Coerce to pointer through implicit conversion to const T* (overload through less specific "const T*" parameter to avoid ambiguity with other coercion options that may also exist.
Definition at line 339 of file ObjectPtr.h.
References FORCEINLINE, and Other.
Referenced by IsObjectPtrEqual().
CoerceToPointer() [2/3]
template<typename T, typename U UE_REQUIRES> FORCEINLINE std::common_type_t< const T *, U > ObjectPtr_Private::CoerceToPointer (const U & Other)
Coerce to pointer through implicit conversion to CommonPointerType where CommonPointerType is deduced, and must be a C++ pointer, not a wrapper type.
Definition at line 364 of file ObjectPtr.h.
References FORCEINLINE, and Other.
CoerceToPointer() [3/3]
template<typename T, typename U UE_REQUIRES> FORCEINLINE auto ObjectPtr_Private::CoerceToPointer (const U & Other) -> decltype(Other.Get())
Coerce to pointer through the use of a ".Get()" member, which is the convention within Unreal smart pointer types.
Definition at line 375 of file ObjectPtr.h.
References FORCEINLINE, and Other.
Get()
template<typename T> FORCEINLINE T * ObjectPtr_Private::Get (const FObjectPtr & ObjectPtr)
Resolve and return the underlying reference.
Definition at line 440 of file ObjectPtr.h.
References FORCEINLINE, and FObjectPtr::Get().
Referenced by TObjectPtr< T >::Get(), and TObjectPtr< T >::GetInternalRef().
IsObjectPtrEqual()
template<typename T, typename U, decltype(CoerceToPointer< T >(std::declval< U >())==std::declval< const T * >()) * = nullptr UE_REQUIRES(!TIsTObjectPtr_V<U>)> bool ObjectPtr_Private::IsObjectPtrEqual (const TObjectPtr< T > & Ptr, const U & Other)
Perform shallow equality check between a TObjectPtr and another (non TObjectPtr) type that we can coerce to a pointer.
Definition at line 414 of file ObjectPtr.h.
References CoerceToPointer(), IsObjectPtrEqualToRawPtrOfRelatedType(), and Other.
Referenced by operator!=(), operator==(), and TObjectPtr< T >::operator==().
IsObjectPtrEqualToRawPtrOfRelatedType()
template<typename T, typename U> bool ObjectPtr_Private::IsObjectPtrEqualToRawPtrOfRelatedType (const TObjectPtr< T > & Ptr, const U * Other)
Definition at line 381 of file ObjectPtr.h.
References TObjectPtr< T >::GetNoReadNoCheck(), TObjectPtr< T >::GetNoResolveNoCheck(), TObjectPtr< T >::IsResolved(), and Other.
Referenced by IsObjectPtrEqual().
IsObjectPtrNull()
template<typename T> FORCEINLINE bool ObjectPtr_Private::IsObjectPtrNull (const FObjectPtr & ObjectPtr)
Check for NULL without resolving the handle.
Definition at line 428 of file ObjectPtr.h.
References bool, and FORCEINLINE.
Referenced by TObjectPtr< T >::operator bool(), TObjectPtr< T >::operator!(), TObjectPtr< T >::operator==(), and TObjectPtr< T >::operator==().
ResolveTypeIsComplete() [1/2]
template<typename T> char(& ObjectPtr_Private::ResolveTypeIsComplete (...))[1]
ResolveTypeIsComplete() [2/2]
template<typename T, int = sizeof(T)> char(& ObjectPtr_Private::ResolveTypeIsComplete (int))[2]