Unreal Engine 5.6 C++ API: UE::Geometry Namespace Reference
UE::Geometry Namespace Reference
Namespaces
namespace CurveUtil
namespace Debug
namespace DenseGrid
namespace ExactPredicates
namespace FaceNormalClustering
namespace FTetWild
namespace GeodesicSingleTriangleUtils
Utils to define vectors relative to the local surface of a mesh and given such a vector, functions to trace across the face of a single triangle within a mesh to find where the vector intersects a triangle edge.
namespace IntrinsicCorrespondenceUtils
namespace LinearColors
Color constants in Linear color space.
namespace MeshClusterSimplify
namespace PolyEditActivityUtil
namespace SplineUtil
namespace TetUtil
namespace TriangleUtil
Triangle utility functions.
namespace UVEditorAnalytics
namespace UVUnwrapMeshUtil
namespace VectorUtil
Data Structures
class ExpandEnumerable
Generic "enumerable" object that provides begin/end semantics for an ExpandIterator suitable for use with range-based for.
class ExpandIterator
Wrapper around existing iterator that returns multiple values, of potentially different type, for each value that input iterator returns.
class FAbortableBackgroundTask
FAbortableBackgroundTask is a FNonAbandonableTask intended for long-running background computations that might need to be interrupted, such as expensive operations driven by a UI tool that the user may wish to cancel.
struct FActorAdapter
FActorAdapter is used by FMeshSceneAdapter to represent all the child info for an AActor.
struct FActorChildMesh
FActorChildMesh represents a 3D Mesh attached to an Actor.
class FAffineKelvinlet
class FApproximateActorsImpl
Implementation of IGeometryProcessing_ApproximateActors.
struct FArrangement2d
Arrangement2d constructs a planar arrangement of a set of 2D line segments.
class FArrayIndexSetsDecomposition
FArrayIndexSetsDecomposition represents a decomposition of an integer index set into subsets, which are stored as arrays (ie this is just an array of arrays, where each sub-array has a unique integer identifier)
class FArrowGenerator
Generate a 3D arrow.
class FAsyncTaskExecuterWithAbort
FAsyncTaskExecuterWithAbort is an extension of FAsyncTask that adds a bAbort flag.
class FAsyncTaskExecuterWithProgressCancel
class FAverageOverlayToVertices
Compute the per-vertex values which are the weighted average of all vertex element values stored in the overlay.
struct FAxisAlignedBox2i
struct FAxisAlignedBox3i
class FBasePositionSnapSolver3
FBasePositionSnapSolver3 is a base class for 3D position snapping implementations.
class FBaseRevolveGenerator
FBaseRevolveGenerator is a base class for simple surface-of-revolution generators.
class FBCSplineFilter
class FBendMeshOp
class FBiLaplacianPullKelvinlet
class FBooleanMeshesOp
class FBoxFilter
struct FBoxShape3d
FBoxShape is a 3D oriented box.
class FBoxSphereGenerator
Generate a sphere by pushing a boxes vertices onto a sphere – often more useful.
struct FBRIOPoints
Generate a "Biased Randomized Insertion Order" (BRIO) ordering for a point set by randomly bucketing the points, then applying Z-Order-Curve sorting (above) to each bucket This gives an ordering with point locality but enough randomization to typically avoid worst case behavior if using the ordering for Delaunay meshing.
class FCapsuleGenerator
Generate a Capsule mesh, with UVs wrapped cylindrically.
struct FCapsuleShape3d
FCapsuleShape is a 3D oriented capsule/sphyl.
struct FClusterKMeans
class FColliderMesh
FColliderMesh is a minimal representation of an Indexed Triangle Mesh suitable to use with a TMeshAABBTree3.
class FColliderMeshProjectionTarget
Projection target API wrapper for an FColliderMesh.
class FCompactMaps
Stores index remapping for vertices and triangles.
struct FComponentCollisionSettings
Component/BodySetup collision settings (eg StaticMeshComponent) we might need to pass through the functions below.
struct FComputePCA3Options
struct FComputeTangentsOptions
Options used by TMeshTangents for tangents computation.
struct FConstraintProjectionData
class FConvexDecomposition3
struct FConvexShape3d
FConvexShape is a 3D convex hull, currently stored as a triangle mesh.
class FCotanSmoothingOp
class FCubeGrid
Class representing an adjustable and resizable power-of-two grid in which faces can be selected.
class FCubeGridBooleanOp
Operator meant to be used with UCubeGridTool that adds or subtracts a box to/from an input mesh, with options to weld the box's corners to make ramps/corners.
class FCurvedStairGenerator
Generate an oriented Curved Stair mesh.
class FCurveSweepOp
class FCylinderGenerator
Generate a cylinder with optional end caps.
class FDeformableEdgePath
Given a single path initially defined by edges on a FDynamicMesh (the SurfaceMesh), this class uses an intrinsic mesh with the same vertex set to minimize the length of the path on the surface mesh.
class FDelaunay2
class FDelaunay3
class FDetectPerDynamicMeshExteriorVisibility
class FDiscMeshGenerator
Generate planar disc (a circle polygon)
class FDisplaceMesh
class FDynamicFlagArray
Utility class that allows for get/set of a flag for each integer ID, where the flag set automatically grows to contain whatever integer ID is passed.
class FDynamicGraph
class FDynamicGraph2
class FDynamicGraph3
class FDynamicGraphN
Implementation of DGraph that has no dimensionality, ie no data stored for vertices besides indices.
class FDynamicMesh3
FDynamicMesh3 is a dynamic triangle mesh class.
class FDynamicMeshAttributeChangeSet
FDynamicMeshAttributeChangeSet stores a set of UV and Normal changes for a FDynamicMesh3.
class FDynamicMeshAttributeSet
FDynamicMeshAttributeSet manages a set of extended attributes for a FDynamicMesh3.
class FDynamicMeshAttributeSetChangeTracker
FDynamicMeshAttributeSetChangeTracker constructs a well-formed set of TDynamicMeshAttributeChange objects (stored in a FDynamicMeshAttributeChangeSet).
class FDynamicMeshChange
FDynamicMeshChange stores a "change" in a FDynamicMesh3, which in this context means the replacement of one set of triangles with a second set, that may have different vertices/attributes.
class FDynamicMeshChangeTracker
FDynamicMeshChangeTracker tracks changes to a FDynamicMesh and returns a FDynamicMeshChange instance that represents this change and allows it to be reverted/reapplied.
class FDynamicMeshEditor
FDynamicMeshEditor implements low-level mesh editing operations.
struct FDynamicMeshEditResult
FDynamicMeshEditResult is used to return information about new mesh elements created by mesh changes, primarily in FDynamicMeshEditor.
class FDynamicMeshOctree3
FDynamicMeshOctree3 is an extension of FSparseDynamicOctree3 for the triangles of a FDynamicMesh3 instance.
class FDynamicMeshOperator
FDynamicMeshOperator is a base interface for operator implementations that can produce a FDynamicMesh3 with associated FTransformSRT3d.
class FDynamicMeshSculptLayers
class FDynamicMeshTangents
FDynamicMeshTangents is a helper object for accessing tangents stored in the AttributeSet of a FDynamicMesh3.
class FDynamicMeshTriangleAttributeChange
class FDynamicMeshUDIMClassifier
FDynamicMeshUDIMClassifier is a utility class for identifying active UDIMs from a FDynamicMesh's UV overlay.
class FDynamicMeshUVEditor
FDynamicMeshUVEditor implements various UV overlay editing operations.
struct FDynamicMeshUVMesh
Wrapper around a Mesh and UV Overlay that provides UVs triangles as vertices.
class FDynamicMeshUVPacker
FDynamicMeshUVPacker implements various strategies for packing UV islands in a UV Overlay.
class FDynamicMeshUVTransfer
Transfers UVs from a low-resolution mesh to a high-resolution mesh.
struct FDynamicSubmesh3
struct FEdgeConstraint
FEdgeConstraint is a constraint on a triangle mesh edge.
class FEdgeLoop
Sequential lists of vertices/edges in a mesh that form a closed loop.
class FEdgeLoopInsertionOp
class FEdgePath
FEdgePath is is little more than a double link-list that exposes IDs instead of node pointers.
class FEdgeSpan
Sequential lists of vertices/edges in a mesh that is not closed.
class FEditNormalsOp
class FElementLinearization
FElementLinearization maps a potentially-sparse index list into a linear array.
struct FExteriorVisibilitySampling
class FExtrudeBoundaryEdges
class FExtrudeBoundaryEdgesFixLayout
class FExtrudeMesh
Note: FExtrudeMesh might someday be removed.
class FExtrudeMeshFixLayout
class FExtrudeOp
class FFFDLattice
Free-form deformation lattice.
struct FFillOptions
class FFlareMeshOp
class FFlatTriangulationMeshGenerator
Generate planar triangulation of a Polygon.
class FFloatingStairGenerator
Generate an oriented Floating Stair mesh.
struct FForceGeometryNamespaceToExist
class FGeneralizedCylinderGenerator
Sweep a 2D Profile Polygon along a 3D Path.
class FGenerateCrossSectionOp
struct FGeometryError
FGeometryError represents an error code/message emitted by a geometry operation.
struct FGeometryResult
FGeometryResult represents a combined "success/failure/etc" state for a geometry operation along with a set of Error and Warning codes/messages.
struct FGeometrySelection
FGeometrySelection represents a subset of geometric elements of a larger object, for example a Mesh (currently the only use case).
struct FGeometrySelectionBounds
3D Bounding information for a FGeometrySelection
struct FGeometrySelectionDelta
FGeometrySelectionDelta represents a change to the set of elements in a FGeometrySelection.
class FGeometrySelectionEditor
FGeometrySelectionEditor is a utility/helper class used for modifying a FGeometrySelection.
struct FGeometrySelectionElements
3D Geometry representing a FGeometrySelection, for example suitable for passing to rendering code, etc
struct FGeometrySelectionHitQueryConfig
FGeometrySelectionHitQueryConfig defines the desired settings for a "hit query" on selected meshes/objects.
class FGeometrySelectionPreview
FGeometrySelectionPreview is a combined FGeometrySelection and FGeometrySelectionEditor.
struct FGeometrySelectionUpdateConfig
FGeometrySelectionUpdateConfig is passed to various Selection Editing functions/classes to indicate what type of change should be applied to a FGeometrySelection (based on additional parameters, generally)
struct FGeometrySelectionUpdateResult
class FGeometrySet3
FGeometrySet3 stores a set of 3D Points and Polyline curves, and supports spatial queries against these sets.
struct FGeometryWarning
FGeometryWarning represents a warning code/message emitted by a geometry operation.
struct FGeoSelectionID
FGeoSelectionID provides a pair of 32-bit unsigned integers that can be packed into a 64-bit unsigned integer for use with FGeometrySelection.
class FGridBoxMeshGenerator
Generate a mesh of a box that has "gridded" faces, i.e.
class FGroupEdgeInserter
Used to insert group edges and group edge loops.
class FGroupEdgeInsertionOp
class FGroupTopology
Given a per-triangle integer ("group"), FGroupTopology extracts a group-level topological graph from an input Mesh.
class FGroupTopologyDeformer
FGroupTopologyDeformer supports deforming a Mesh based on an overlaid FGroupTopology.
struct FGroupTopologySelection
FGroupTopologySelection represents a set of selected elements of a FGroupTopology.
class FGroupVisualizationCache
FGroupVisualizationCache is intended to be used as a cache for per-group information that would be used to visualize PolyGroups, in particular drawing the Polygroup ID for each group.
class FHoleFillOp
class FilteredIterator
Wrapper around an existing iterator that skips over values for which the filter_func returns false.
class FImageAdapter
FImageAdapter is a wrapper around different types of TImageBuilder that provides a standard interface, which allows functions that don't need to know about the specific image type to operate on "any" image.
class FImageDimensions
FImageDimensions provides various functions for working with size/indices/coordinates of a 2D image, as well as standard UV spaces.
class FImageOccupancyMap
ImageOccupancyMap calculates and stores coverage information for a 2D image/texture, for example coverage derived from UV islands of a mesh, 2D polygons, etc.
class FImageTile
class FImageTiling
struct FIndex2i
2-index tuple.
struct FIndex3i
3-index tuple.
struct FIndex4i
4-index tuple.
class FIndexFlagSet
This class provides optionally sparse or dense boolean flags for a set of integer indices.
class FIndexPriorityQueue
This is a min-heap priority queue class that does not use an object for each queue node.
class FInsetMeshRegion
FInsetMeshRegion implements local inset of a mesh region.
struct FInterval1i
class FIntrinsicEdgeFlipMesh
FIntrinsicEdgeFlipMesh augments the base class FSimpleIntrinsicEdgeFlipMesh with the addition of a 'normal coordinate' based correspondence with the surface mesh.
class FIntrinsicMesh
FIntrinsicMesh extends the FSimpleIntrinsicMesh with the addition of a 'normal coordinate' based correspondence with the surface mesh.
class FIntrinsicTriangulation
Class that manages the intrinsic triangulation of a given FDynamicMesh.
class FIterativeOffsetMeshOp
class FIterativeSmoothingOp
class FJoinMeshLoops
FJoinMeshLoops connects two open loops of a mesh with a quad-strip.
class FLaplacianOffsetMeshOp
class FLaplacianPullKelvinlet
class FLatticeDeformerOp
struct FLatticeExecutionInfo
struct FLevelSetShape3d
FLevelSetShape is a 3D signed distance function sampled on a regular grid.
class FLinearExtrusionOp
LinearExtrusionOp extrudes a set of triangles of a mesh in a linear direction, with various options for how to process that extrusion.
struct FLinearIntersection
FLinearIntersection contains intersection information returned by linear/primitive intersection functions.
class FLinearStairGenerator
Generate an oriented Linear Stair mesh.
class FLocalPlanarSimplify
class FMarchingCubes
class FMergeCoincidentMeshEdges
FMergeCoincidentMeshEdges finds pairs of boundary edges of the mesh that are identical (ie have endpoint vertices at the same locations) and merges the pair into a single edge.
class FMeshAttributeTransfer
FMeshAttributeTransfer transfers attributes from a SourceMesh to a TargetMesh.
class FMeshAutoUVImpl
Implementation of IGeometryProcessing_MeshAutoUV.
class FMeshBakerDynamicMeshSampler
DynamicMesh bake detail sampler for baking 1 detail mesh to 1 target mesh.
class FMeshBaseBaker
class FMeshBevel
FMeshBevel applies a "Bevel" operation to edges of a FDynamicMesh3.
class FMeshBones
FMeshBones is a utility class for manipulating mesh bone attributes.
class FMeshBoolean
MeshBoolean – perform a boolean operation on two input meshes.
class FMeshBoundaryCache
class FMeshBoundaryLoops
class FMeshConnectedComponents
FMeshConnectedComponents calculates Connected Components of a Mesh, or sub-regions of a Mesh.
class FMeshConstantMapEvaluator
A mesh evaluator for constant data.
class FMeshConstraintCurve
class FMeshConstraints
FMeshConstraints is a set of Edge and Vertex constraints for a Triangle Mesh.
class FMeshConstraintsUtil
Utility functions for configuring a FMeshConstraints instance.
class FMeshConvexHull
Calculate Convex Hull of a Mesh.
class FMeshCurvatureMapBaker
class FMeshCurvatureMapEvaluator
A mesh evaluator for mesh curvatures.
class FMeshDerivatives
First derivatives of some mesh quantities with respect to particular vertex positions.
class FMeshEdgeSelection
Currently a thin wrapper of a TSet<int> of Edge IDs paired with a Mesh; the backing storage will likely change as we need to optimize in the future.
class FMeshEdgesFromTriangleSubIndices
class FMeshFaceSelection
class FMeshGenericWorldPositionColorBaker
Bake Colors based on arbitrary Position/Normal sampling.
class FMeshGenericWorldPositionNormalBaker
Bake Tangent-Space Normals based on arbitrary Position/Normal sampling.
class FMeshGeodesicSurfaceTracer
Class that, given a starting location and direction, traces a geodesic path along a mesh.
class FMeshHeightMapEvaluator
A mesh evaluator for mesh height as color data.
class FMeshImageBaker
class FMeshImageBakingCache
struct FMeshIndexMappings
FMeshIndexMappings stores a set of integer IndexMaps for a mesh This is a convenient object to have, to avoid passing around large numbers of separate maps.
class FMeshIsoCurves
Insert edges on a mesh along the isocurve where some scalar value function over the mesh surface crosses a specified value.
struct FMeshIsoCurveSettings
class FMeshMapBaker
class FMeshMapBakerQueue
Multi-producer/single-consumer queue for the ordered processing of data in FMeshMapBaker.
class FMeshMapEvaluator
class FMeshMapTileBuffer
Image tile storage for map bakes.
class FMeshMeshCut
Cut a mesh where it crosses a second mesh – resolving all intersections, but not deleting geometry.
class FMeshMirror
class FMeshMultiResampleImageBaker
class FMeshMultiResampleImageEvaluator
A mesh evaluator for sampling multiple 2D textures by material ID.
class FMeshNormalMapBaker
class FMeshNormalMapEvaluator
A mesh evaluator for tangent space normals.
class FMeshNormals
FMeshNormals is a utility class that can calculate and store various types of normal vectors for a FDynamicMesh.
class FMeshOcclusionMapBaker
class FMeshOcclusionMapEvaluator
A mesh evaluator for occlusion data (Ambient Occlusion & Bent Normals).
class FMeshOffsetBaseOp
Base class for Mesh Offset operations (ie displacement along some kind of normal) Optionally duplicates input mesh and joins the two together, either by welding along shared border or creating quad-strip join.
class FMeshPaths
Given a mesh and a set of edges, walk connected edges to form a set of paths.
class FMeshPlanarSymmetry
FMeshPlanarSymmetry detects pairwise symmetry relationships between vertices in a mesh, given a symmetry frame.
class FMeshPlaneCut
Cut the Mesh with the Plane.
class FMeshPlaneCutFixLayout
class FMeshProjectionHull
Calculate a Convex Hull for a Mesh by first Projecting all vertices to a plane, computing a 2D convex polygon that contains them, and then sweeping that 2D hull to create an extruded 3D volume.
class FMeshProjectionTarget
FMeshProjectionTarget provides an IProjectionTarget interface to a FDynamicMesh + FDynamicMeshAABBTree3 Use to project points to mesh surface.
class FMeshPropertyMapBaker
class FMeshPropertyMapEvaluator
A mesh evaluator for mesh properties as color data.
class FMeshRefinerBase
This is a base class that implements common functionality for various triangle mesh resampling strategies (ie FRemesher and FReducer).
class FMeshRefinerBaseFixLayout
class FMeshRegionBoundaryLoops
Extract FEdgeLoops on the boundary of a set of triangles of a mesh.
class FMeshRegionGraph
FMeshRegionGraph represents neighbourhood relationships between mesh patches.
class FMeshRegionOperator
This class automatically extracts a submesh from a mesh, and can re-insert it after you have edited it, as long as you have not messed up the boundary.
class FMeshRepairOrientation
Invert triangles as needed to a consistent ~"outward" orientation.
class FMeshResampleImageBaker
class FMeshResampleImageEvaluator
A mesh evaluator for sampling 2D texture data.
class FMeshResolveTJunctions
FMeshResolveTJunctions splits edges to create matching vertices at T-Junctions in the mesh.
class FMeshSceneAdapter
FMeshSceneAdapter creates an internal representation of an Actor/Component/Asset hierarchy, so that a minimal set of Mesh data structures can be constructed for the unique Meshes (generally Assets).
struct FMeshSceneAdapterBuildOptions
Configuration for FMeshSceneAdapter::Build()
struct FMeshSceneRayHit
FMeshSceneRayHit is returned by various ray-intersection functions below.
class FMeshSelfCut
class FMeshSelfUnion
MeshSelfUnion – perform a "Mesh Boolean" style union of a mesh on itself, resolving any self intersections and welding the new boundaries as needed.
class FMeshShapeGenerator
Base class for triangle mesh generators (eg like to generate sphere, cylinder, etc) Subclasses must implement Generate()
class FMeshSimpleShapeApproximation
FMeshSimpleShapeApproximation can calculate various "simple" shape approximations for a set of meshes, by fitting various primitives/hulls/etc to each mesh.
class FMeshSnapOpenBoundaries
Similar to FMeshResolveTJunctions, but does not add any vertices to the mesh.
class FMeshSpaceDeformerOp
class FMeshSurfacePath
Walk the surface of an FDynamicMesh to try find a planar path connecting two points.
struct FMeshSurfacePoint
class FMeshSurfacePointSampling
FMeshSurfacePointSampling computes oriented point samples on the surface of a Mesh using various sampling strategies, with controls over sample spacing.
class FMeshSurfaceUVSampler
FMeshSurfaceUVSampler computes FMeshUVSampleInfo's on a given mesh at given UV-space positions, this info can then be used by an external function to compute some application-specific sample.
class FMeshSurfaceUVSamplerFixLayout
struct FMeshTriEdgeID
FMeshTriEdgeID identifies an edge in a triangle mesh based on the triangle ID/Index and the "edge index" 0/1/2 in the triangle.
struct FMeshTriInfoCache
struct FMeshTriOrderedEdgeID
FMeshTriOrderedEdgeID identifies an oriented edge in a triangle mesh based on indices into the triangle vertices.
struct FMeshTypeContainer
FMeshTypeContainer is a wrapper for an object that contains a unique Mesh of some kind, which is used by an FActorChildMesh to represent that unique mesh.
struct FMeshUVSampleInfo
Information about a UV sample.
class FMeshUVShellMapEvaluator
A mesh evaluator for mesh properties as color data.
class FMeshVertexBaker
class FMeshVertexColorBrushOp
class FMeshVertexCurvatureCache
FMeshVertexCurvatureCache calculates and stores various per-vertex Curvature types for a Mesh, as well as some statistics for those values.
class FMeshVertexSelection
class FMeshWeights
FMeshWeights implements various techniques for computing local weights of a mesh, for example one-ring weights like Cotangent or Mean-Value.
class FMinimalBoxMeshGenerator
Generate an oriented Box mesh with the smallest number of triangles possible (6 vertices, 12 triangles)
class FMinimalHoleFiller
Construct a "minimal" fill surface for the hole.
class FMirrorOp
struct FModuloIteration
FModuloIteration is used to iterate over a range of indices [0,N) using modulo-arithmetic.
struct FNegativeSpaceSampleSettings
class FNonManifoldMappingSupport
class FNormalFlowRemesher
Remeshing with "face aligned projection".
struct FOccupancyGrid3
Sample mesh occupancy in a voxel grid by using the mesh's winding number, on voxel corners, to determine whether the voxel is fully contained within the interior of the mesh, touches the mesh's boundary, or is fully contained on the exterior of the mesh.
class FOffsetMeshRegion
FOffsetMeshRegion implements local extrusion/offset of a mesh region.
class FOffsetMeshRegionFixLayout
struct FOptionallySparseIndexMap
Index map that supports dense or sparse storage, or a simple formula-based map (e.g.
class FPatchBasedMeshUVGenerator
FPatchBasedMeshUVGenerator is an automatic UV generator for a triangle mesh that, generally, works by first decomposing the mesh into small patches for which a "known good" parameterization can be computed, and then incrementally merging those patches into larger ones to create final UV islands.
class FPinchKelvinlet
class FPlanarFlipsOptimization
If both triangles on an edge are coplanar, we can arbitrarily flip the interior edge to improve triangle quality.
class FPlanarHoleFiller
Fill a set of boundary loops with planar surfaces.
class FPlanarPolygonMeshGenerator
Generate planar triangulation of a Polygon.
class FPlaneCutOp
class FPNTriangles
FPNTriangles implements curved PN (Point-Normal) Triangles (Curved PN Triangles, Vlachos, 2001).
class FPointPlanarSnapSolver
FPointPlanarSnapSolver solves for a Point snap location on a plane, based on an input Point and a set of target points and lines in the plane.
class FPointSetHashtable
FPointSetHashTable builds a spatial data structure that supports efficient range queries on a point set (in FPointSetAdapterd form).
class FPolygonEdgeMeshGenerator
Mesh generator that generates a quad for each edge of a closed polygon.
struct FPolygroupLayer
FPolygroupLayer represents a polygroup set on a FDynamicMesh3, which supports a "default" group set stored on the mesh, and then N extended group layers stored in the mesh AttributeSet.
class FPolygroupRemesh
PolygroupRemesh – remesh only considering polygroup features (topological corners and bends on polygroup edges) This can help clean up low poly meshes that have extra vertices along straight edges e.g.
class FPolygroupRemeshFixLayout
struct FPolygroupSet
Polygroup sets can be stored in multiple places.
class FPolygroupsGenerator
FPolygroupsGenerator generates (face/tri/poly)groups for an input mesh based on the geometry and attributes of the input mesh.
struct FPriorityOrderPoints
Generate a "priority ordering" for a point set.
class FProfileSweepGenerator
Much like FGeneralizedCylinderGenerator, but allows an arbitrary profile curve to be swept, and gives control over the frames of the sweep curve.
class FPullKelvinlet
class FPuncturedDiscMeshGenerator
Generate planar disc with a hole.
class FQuadGridPatch
FQuadGridPatch represents a set of quads, formed by pairs of triangles, arranged in a 2D grid pattern.
class FQueueRemesher
Extension to Remesher that is smarter about which edges/vertices to touch:
class FQuickAxisRotator
class FQuickAxisTranslater
FQuickAxisTranslater implements the underpinnings for "quick" axis transformations, ie axis-gizmo-like behavior without having to explicitly click on an axis.
class FQuickTransformer
class FRaySpatialSnapSolver
FRaySpatialSnapSolver solves for a Point snap location based on an input Ray and a set of snap targets (3D points and 3D lines).
class FRecomputeUVsOp
class FRectangleMeshGenerator
Generate planar rectangular mesh with variable number of subdivisions along width and height.
class FRefCountVector
FRefCountVector is used to keep track of which indices in a linear Index list are in use/referenced.
class FRegionOffsetOp
RegionOffsetOp extrudes a set of triangles of a mesh in a linear direction, with various options for how to process that extrusion.
class FRemesher
FRemesher implements edge flip/split/collapse/smooth Remeshing.
class FRemeshMeshOp
class FRemoveOccludedTrianglesOp
struct FRenderCaptureConfig
struct FRenderCaptureCoordinateConverter2D
Render capture images use the render target coordinate system, which is defined such that:
class FRenderCaptureMapEvaluator
class FRenderCaptureOcclusionHandler
struct FRenderCaptureTextures
struct FRenderCaptureTypeFlags
FRenderCaptureTypeFlags is a set of per-capture-type booleans.
class FRestrictedSubRegionRemesher
FRestrictedSubRegionRemesher is similar to FSubRegionRemesher but does not allow the ROI to grow outside of the original ROI boundary.
class FRevolvePlanarPathGenerator
Revolve a planar polyline (in the XY plane) around the +Z axis along a circular path (+X, +Y) in the 2D polyline is mapped to (+X, 0, +Z)
class FRevolvePlanarPolygonGenerator
Revolve a planar polygon (in the XY plane) around the +Z axis along a circular path (+X, +Y) in the 2D polygon is mapped to (+X, 0, +Z)
class FRoundedRectangleMeshGenerator
Adds rounded corners to the rectangle mesh.
class FScaleKelvinlet
struct FSceneCaptureConfig
class FSceneCapturePhotoSet
FSceneCapturePhotoSet creates a set of render captures for a given World and set of Actors, stored as a SpatialPhotoSet for each desired render buffer type.
class FSceneCapturePhotoSetSampler
struct FSceneGeometryID
struct FSceneGeometryPoint
class FSceneGeometrySpatialCache
class FSegmentTree3
FSegmentTree3 is a spatial data structure for a set of 3D line segments.
struct FSelectionRenderHelper
class FSelectiveTessellate
Given an input mesh and a tessellation pattern, this operator generates a new tessellated mesh where the triangles affected are subtriangulated according to the rules specified by the pattern.
class FSelfUnionMeshesOp
class FSharpBiLaplacianPullKelvinlet
class FSharpLaplacianPullKelvinlet
struct FSimpleCollisionToMeshAttributeSettings
struct FSimpleCollisionTriangulationSettings
class FSimpleHoleFiller
Fill an EdgeLoop hole with triangles.
class FSimpleIntrinsicEdgeFlipMesh
Intrinsic Meshes:
class FSimpleIntrinsicMesh
FSimpleIntrinsicMesh extends FSimpleIntrinsicEdgeFlipMesh to support edge splits and triangle pokes in addition to edge flips.
class FSimpleMeshProcessingBaseOp
Dynamic Mesh Operator that has a separate PositionBuffer that contains copy of input vertex positions.
struct FSimpleShapeSet3d
FSimpleShapeSet stores a set of simple geometry shapes useful for things like collision detection/etc.
struct FSizedDisjointSet
Disjoint set with additional storage to track the size of each set.
class FSkinBindingOp
class FSmallListSet
FSmallListSet stores a set of short integer-valued variable-size lists.
class FSmoothDynamicMeshAttributes
Smooth scalar data of any dimension that is stored via TDynamicMeshOverlay.
class FSmoothDynamicMeshVertexSkinWeights
Subclass of TSmoothBoneWeights for dealing with smoothing of bone weights stored in the FDynamicMeshVertexSkinWeightsAttribute.
struct FSmoothFillOptions
Fill parameters.
class FSmoothHoleFiller
This fills a hole in a mesh by doing a trivial fill, then doing a remesh, then a laplacian smooth, then a second remesh.
class FSmoothingOpBase
class FSparseDynamicOctree3
FSparseDynamicOctree3 sorts objects with axis-aligned bounding boxes into a dynamic sparse octree of axis-aligned uniform grid cells.
class FSparseDynamicPointOctree3
FSparseDynamicPointOctree3 sorts Points with axis-aligned bounding boxes into a dynamic sparse octree of axis-aligned uniform grid cells.
struct FSparseOctreeCell
FSparseOctreeCell is a Node in a SparseDynamicOctree3.
struct FSparsePointOctreeCell
FSparsePointOctreeCell is a Node in a SparseDynamicOctree3.
struct FSpatialPhotoParams
class FSphereCovering
class FSphereGenerator
Generate a sphere mesh, with UVs wrapped cylindrically.
class FSphereShape3d
FSphereShape is a 3D sphere.
class FSpiralRevolvePlanarPolygonGenerator
Revolve a planar polygon (in the XY plane) around the +Z axis along a spiral path.
class FSpiralStairGenerator
Generate an oriented Curved Stair mesh.
class FSplitAttributeWelder
FSplitAttributeWelder can be used to weld split-attributes that share the same vertex in the parent mesh (e.g.
class FStairGenerator
Base Stair mesh generator class.
class FSubRegionRemesher
FSubRegionRemesher is an extension of FRemesher that allows for constraining remeshing to a localized region of a mesh.
class FSweepGeneratorBase
class FTessellationPattern
An abstract class for writing tessellation patterns.
class FTexture2DBuilder
Texture2DBuilder is a utility class for creating/modifying various types of UTexture2D.
class FTransferBoneWeights
Transfer bone weights from one mesh (source) to another (target).
class FTransferVertexColorAttribute
Transfer vertex colors from one mesh (source) to another (target).
class FTriangleGroupTopology
FTriangleGroupTopology is a simplification of FGroupTopology that just represents a normal mesh.
class FTriangleLinearization
Used linearize the TriIds in a mesh as a single array and allow mapping from array offset to mesh TriId.
class FTriangulateCurvesOp
FTriangulateCurvesOp triangulates polygons/paths generated from USplineComponent inputs.
class FTwistKelvinlet
class FTwistMeshOp
class FUniformTessellate
Given an input mesh and a tessellation level, this operator generates a new tessellated mesh where every triangle in the input mesh is uniformly subtriangulated into (TessellationNum + 1)^2 triangles.
class FUniqueIndexSet
FUniqueIndexSet is used to construct a list of unique elements of integers in range [0, MaxValue].
class FUVEditorTexelDensityOp
class FUVEditorUVAlignOp
class FUVEditorUVDistributeOp
class FUVEditorUVTransformBaseOp
class FUVEditorUVTransformOp
struct FUVEditResult
class FUVLayoutOp
class FUVMetrics
class FUVPacker
FUVPacker implements various strategies for packing UV islands in a generic mesh class.
class FUVProjectionOp
class FUVToolSelection
Class that represents a selection in the canonical unwrap of a UV editor input object.
struct FVector2i
2D 32-bit integer Vector
struct FVector3i
3D 32-bit integer Vector
class FVertexColorSmoothBrushOp
class FVertexColorSoftenBrushOp
Soften brush averages colors at any vertices that have split elements, effectively un-splitting them Currently this averaging is done in a single step, ie falloff/etc is ignored, but it could be done more gradually...
class FVertexConnectedComponents
Vertex-based connected components class – can work with any mesh that has vertex IDs Also supports linking spatially-close vertices in the same component.
struct FVertexConstraint
FVertexConstraint is a constraint on a triangle mesh vertex.
struct FVertexInfo
FVertexInfo stores information about vertex attributes - position, normal, color, UV.
class FVertexLinearization
Used to linearize the VtxIds in a mesh as a single array and allow mapping from array offset to mesh VtxId.
class FVertexPaintBrushOp
class FVertexPositionCache
Basic cache of vertex positions.
class FVerticalCylinderGeneratorBase
Generate a cylinder with optional end caps.
class FVoxelBaseOp
class FVoxelBlendMeshesOp
class FVoxelMorphologyMeshesOp
class FVoxelSolidifyMeshesOp
class FWeldEdgeSequence
Weld a pair of group edges.
class FWindingNumberBasedSolidify
Use marching cubes to remesh an arbitrary function that provides a winding-number like scalar value to a solid surface.
class FWorldRenderCapture
FWorldRenderCapture captures a rendering of a set of Actors in a World from a specific viewpoint.
class FWorldSpaceProjectionTarget
struct FZOrderCurvePoints
Generate a "z-order curve" ordering for a point set by distributing the points to a quad- or octree and then reading the points indices back in tree traversal order This is useful for giving the points spatial locality – so points that are close together in the ordering tend to be close together spatially, also.
class IDynamicMeshOperatorFactory
A IDynamicMeshOperatorFactory is a base interface to a factory that creates FDynamicMeshOperators.
class IGenericDataOperatorFactory
A IDynamicMeshOperatorFactory is a base interface to a factory that creates TGenericDataOperator instances that create the given ResultType.
class IHoleFiller
class IIntersectionTarget
IIntersectionTarget is an object that can be intersected with a ray.
class IMeshBakerDetailSampler
Base bake detail sampler class.
class IMeshSpatial
IMeshSpatial is an extension of ISpatial specifically for meshes.
class IMeshSpatialWrapper
Abstract interface to a spatial data structure for a mesh.
class IOrientedProjectionTarget
IOrientedProjectionTarget is a projection target that can return a normal in addition to the projected point.
class IProjectionTarget
IProjectionTarget is an object that supports projecting a 3D point onto it.
class ISceneGeometrySpatial
class ISpatial
ISpatial is a base interface for spatial queries.
class MappedIterator
Wrapper around an object of type IteratorT that provides STL iterator-like semantics, that converts from the iteration type (FromType) to a new type (ToType).
class TAttrBasedQuadricError
Quadric Error type for use in volume memory-less simplification with volume preservation constraints.
struct TAxisAlignedBox2
struct TAxisAlignedBox3
class TBackgroundModelingComputeSource
TBackgroundModelingComputeSource is a container that can be used to repeatedly execute a background computation.
class TBaseKelvinlet
class TBasicBlockedDenseGrid3
TBasicBlockedDenseGrid3 represents a 3D blocked uniform grid.
class TBlendPairedKelvinlet
class TBlockData3
class TBlockData3< bool, BlockSize_ >
struct TBlockData3Layout
class TBlockedDenseGrid3
TBlockedDenseGrid adds thread-safe access functions to the 3D blocked uniform grid, TBasicBlockedDenseGrid3.
class TBlockedGrid3
TBlockedGrid3 represents a 3D uniform grid.
class TBlockedGrid3Layout
class TBoneWeightsDataSource
Interface for getting the bone weights data.
class TBooleanPolygon2Polygon2
Produces the boolean'd result of PolygonA and PolygonB depending on the OperationType.
struct TBoundedImplicitFunction3
struct TBoundsGridIndexer3
class TCachingMeshSDF
This is variant of TSweepingMeshSDF that does lazy evaluation of actual Distances, using mesh spatial data structure.
struct TCapsule3
struct TCircle2
struct TCircle3
struct TClusterCenterArray
class TConstObjectSharedAccess
TConstObjectSharedAccess provides a way for the owner of some object (eg a Mesh) to share read-only access to that object with background threads.
struct TConstrainedDelaunay2
This is a version of FDelaunay (which can also do Constrained Delaunay triangulation), but with added support for:
class TConvexHull2
class TConvexHull3
Calculate the Convex Hull of a 3D point set as a Triangle Mesh.
struct TConvexHullSimplificationSettings
class TDeleterTask
TDeleterTask is a task that takes ownership of another FAsyncTask that is (presumably) still executing some operation.
class TDenseGrid2
2D dense grid of scalar values.
class TDenseGrid3
3D dense grid of floating-point scalar values.
class TDiscreteKernel2
2D Discretized Kernel (ie 2D grid/matrix of values)
struct TDistanceFieldToSkeletalField
This class converts the interval [-falloff,falloff] to [0,1], Then applies Wyvill falloff function (1-t^2)^3.
class TDistLine2AxisAlignedBox2
Compute unsigned distance between 2D line and 2D axis aligned box.
class TDistLine3Circle3
Compute unsigned distance and closest-points between 3D line and 3D circle.
class TDistLine3Line3
Compute distance between two 3D lines.
class TDistLine3Ray3
Compute distance between 3D line and 3D ray.
class TDistLine3Segment3
Compute unsigned distance between 3D line and 3D segment.
class TDistLine3Triangle3
Compute unsigned distance between 3D line and 3D triangle.
class TDistPoint3Triangle3
Compute unsigned distance between 3D Point and 3D Triangle.
class TDistRay3Segment3
Compute distance between 3D ray and 3D segment.
class TDistSegment2AxisAlignedBox2
Compute unsigned distance between 2D segment and 2D axis aligned box.
class TDistSegment3Triangle3
Compute unsigned distance between 3D segment and 3D triangle.
class TDistTriangle3Triangle3
Compute unsigned distance between 3D segment and 3D triangle.
class TDynamicAttributeBase
Base class for attributes that live on a dynamic mesh (or similar dynamic object)
class TDynamicAttributeChangeBase
Generic base class for change tracking of an attribute layer.
class TDynamicAttributeSetBase
Generic base class for managing a set of registered attributes that must all be kept up to date.
class TDynamicBoneAttributeBase
TDynamicAttributeBase is a base class for storing per-bone data.
class TDynamicMeshAttributeChange
TDynamicMeshAttributeChange represents a change to an attribute overlay of a FDynamicMesh3.
class TDynamicMeshOverlay
TDynamicMeshOverlay is an add-on to a FDynamicMesh3 that allows for per-triangle storage of an "element" (eg like a per-triangle UV or normal).
class TDynamicMeshScalarTriangleAttribute
TDynamicMeshScalarTriangleAttribute is an extension of TDynamicMeshTriangleAttribute for scalar-valued attributes.
class TDynamicMeshTriangleAttribute
TDynamicMeshTriangleAttribute is an add-on to a FDynamicMesh3 that allows for per-triangle storage of an attribute value.
class TDynamicMeshVectorOverlay
TDynamicMeshVectorOverlay is an convenient extension of TDynamicMeshOverlay that adds a specific N-element Vector type to the template, and adds accessor functions that convert between that N-element vector type and the N-element arrays used by TDynamicMeshOverlay.
class TDynamicPointSet3
TDynamicPointSet3 implements a dynamic 3D point set, templated on real-value type (float or double).
class TDynamicVector
class TDynamicVectorN
class TDynamicVertexAttribute
TDynamicVertexAttribute provides per-vertex storage of an attribute value.
class TDynamicVertexAttributeChange
class TDynamicVertexSkinWeightsAttribute
Forward declarations.
class TDynamicVertexSkinWeightsAttributeChange
class TDynamicVerticesOctree3
TDynamicVerticesOctree3 is an extension of FSparseDynamicPointOctree3 for the vertices of a FDynamicXYZ3 instance (eg FDynamicMesh3, TDynamicPointSet3, FDynamicGraph, etc) This extension does several things: 1) provides a simplified API based on vertex IDs to various Octree functions 2) tracks ModifiedBounds box of modified areas.
struct TEdgeCorrespondence
TEdgeCorrespondence allows intrinsic edges to be traced across the underlying surface mesh.
class TExactIntrTriangle3Triangle3
struct TExtremePoints3
Helper class to find the dimensions spanned by a point cloud and (if it spans 3 dimensions) the indices of four 'extreme' points forming a (non-degenerate, volume > 0) tetrahedron.
class TFastWindingTree
Fast Mesh Winding Number extension to a TMeshAABBTree3.
class TFibonacciLattice
A 2D point set based on the Fibonacci sequence where the i'th point of an N point set can be directly computed.
class TFitCapsule3
Fit a Capsule to a set of 3D points.
struct TFrame3
TFrame3 is an object that represents an oriented 3D coordinate frame, ie orthogonal X/Y/Z axes at a point in space.
class TGaussian1
1D Gaussian
class TGaussian2
2D Gaussian
class TGaussian3
3D Gaussian
class TGeneralPolygon2
TGeneralPolygon2 is a 2D polygon with holes.
class TGenericDataOperator
TGenericDataOperator is a base interface for operator implementations that can produce an object of arbitrary data type.
class TGridSampler
Given a linear index into a square grid of given size, gives back the [0,1) XY coordinate of the grid cell center (assuming linear index increases first in X and then in Y).
struct THalfspace3
class THemisphericalFibonacci
A hemisphere point set generated using a Fibonacci lattice where the i'th point of an N point set can be computed directly.
class TImageBuilder
TImageBuilder is used to create and populate a 2D image with a templated "pixel" type.
class TImplicitBlend
struct TImplicitFunction3
struct TImplicitLine3
Implicit Distance-Field Line Object/Primitive, surface shape at isovalue=0 (defined by Distance-Radius) is a capsule.
class TImplicitMorphology
struct TImplicitPoint3
Implicit Distance-Field Point Object/Primitive, surface shape at isovalue=0 (defined by Distance-Radius) is a sphere.
class TImplicitSolidify
Use marching cubes to remesh a triangle mesh to a solid surface Uses fast winding number to decide what is inside vs outside.
class TIncrementalMeshDijkstra
TIncrementalMeshDijkstra computes graph distances on a mesh from seed point(s) using Dijkstra's algorithm.
class TIndexedWeightMap
FIndexedWeightMap stores an array of values, the intention is that these are "weights" on indices, for example per-vertex weights.
struct TIndexMap
TIndexMap stores mappings between indices, which are assumed to be an integer type.
struct TIndexMeshArrayAdapter
Faster adapter specifically for the common index mesh case.
struct TIndexVectorMeshArrayAdapter
Second version of the above faster adapter – for the case where triangle indices are packed into an integer vector type instead of flat.
class TIntersector1
TIntersector1 computes the intersection of one-dimensional intervals [u0,u1] and [v0,v1].
struct TInterval1
class TIntrLine2Line2
Compute intersection between two 2D lines.
class TIntrLine2Triangle2
Compute intersection between 2D Line and 2D Triangle.
class TIntrRay3AxisAlignedBox3
Compute intersection between 3D ray and 3D axis-aligned box.
class TIntrRay3OrientedBox3
Compute intersection between 3D ray and 3D oriented box.
class TIntrRay3Triangle3
Compute intersection between 3D ray and 3D triangle.
class TIntrSegment2Segment2
Calculate intersection between two 2D line segments.
class TIntrSegment2Triangle2
Compute intersection between 2D segment and 2D triangle.
class TIntrTriangle2AxisAlignedBox2
Compute intersection between a 2D triangle and a 2D axis-aligned box.
class TIntrTriangle2Triangle2
Compute intersection between 2D triangles.
class TIntrTriangle3Triangle3
Compute intersection between 3D triangles use Test() for fast boolean query, does not compute intersection info use Find() to compute full information By default fully-contained co-planar triangles are not reported as intersecting.
class TKelvinletIntegrator
struct TLine2
TLine2 is a two-dimensional infinite line.
struct TLine3
TLine3 is a three-dimensional infinite line.
class TMarchingPixelInfill
TMarchingPixelInfill implements a very basic infilling strategy where the missing pixel with the most "known" neighbours is set to the average value of those neighbours, and this is iterated until all missing pixels are known.
struct TMatrix2
struct TMatrix3
class TMeshAABBTree3
class TMeshDijkstra
TMeshDijkstra computes graph distances on a mesh from seed point(s) using Dijkstra's algorithm.
class TMeshLocalParam
TMeshLocalParam computes a local UV parameterization of a set of connected PointsWithNormals, where "local" means "in a geodesic disc around a starting point".
class TMeshQueries
class TMeshSimplification
Implementation of Garland & Heckbert Quadric Error Metric (QEM) Triangle Mesh Simplification.
class TMeshSpatialSort
Sorts a list meshes into a list of "Nests" where each Nest has an outer shell mesh and a list of contained-inside meshes.
class TMeshSurfaceUVSampler
Consider using FMeshSurfaceUVSampler instead, it is more flexible and easier to understand!
class TMeshTangents
TMeshTangents is a utility class that can calculate and store various types of tangent vectors for a FDynamicMesh.
class TMeshUniformSurfaceSampling
class TMeshWindingNumberGrid
Sample mesh winding number (MWN) on a discrete grid.
struct TMeshWrapperAdapterd
TMeshWrapperAdapterd<T> can be used to present an arbitrary Mesh / Adapter type as a FTriangleMeshAdapterd.
class TMinVolumeBox3
Calculate a Minimal-Volume Oriented Box for a set of 3D points.
struct TMinVolumeBox3Internal
class TMinVolumeSphere3
Calculate a Minimal-Volume Sphere for a set of 3D points.
struct TMinVolumeSphere3Internal
class TModelingOpTask
TModelingOpTask is an FAbortableBackgroundTask that executes a modeling operator of template type OpType.
class TNormalHistogram
TNormalHistogram calculates/represents a histogram on a 3D sphere.
class TOffsetPolygon2
Offsets a given polygon (a polyline or closed polygon), determined by EndType by a given amount.
struct TOrientedBox2
struct TOrientedBox3
TOrientedBox3 is a non-axis-aligned 3D box defined by a 3D frame and extents along the axes of that frame The frame is at the center of the box.
class TPairExpandEnumerable
Generic "enumerable" object that provides begin/end semantics for an TPairExpandIterator suitable for use with range-based for.
class TPairExpandIterator
Wrapper around existing integer iterator that returns either 0, 1, or 2 integers for each value that the original iterator returns.
class TPCA3
struct TPlanarComplex
struct TPlane3
class TPointHashGrid2
Hash Grid for values associated with 2D points.
class TPointHashGrid3
Hash Grid for values associated with 3D points.
struct TPointSetAdapter
TPointSetAdapter provides a very generic interface to an indexable list of points.
class TPolygon2
TPolygon2 is a 2D polygon represented as a list of Vertices.
class TPolyline
TPolyline represents a dimensional independent polyline stored as a list of Vertices.
class TPolylinePolicy
class TPolylinePolicy< T, 2 >
class TPolylinePolicy< T, 3 >
struct TQuadricError
QuadricError represents a quadratic function that evaluates distance to plane.
struct TQuaternion
class TRemoveOccludedTriangles
Remove "occluded" triangles, i.e.
struct TRenderCaptureTypeData
class TSampledScalarField2
TSampledScalarField2 implements a generic 2D grid of values that can be interpolated in various ways.
struct TSampleSetStatisticBuilder
Helper class for reducing the amount of boilerplace code when building a set of TSampleSetStatistics values.
struct TSampleSetStatistics
TSampleSetStatistics stores and calculates statistics for a scalar sample set, such as the range of values, mean, variance, etc.
struct TScaleGridIndexer2
Convert between integer grid coordinates and scaled real-valued coordinates (ie assumes integer grid origin == real origin)
struct TScaleGridIndexer3
Convert between integer grid coordinates and scaled real-valued coordinates (ie assumes integer grid origin == real origin)
struct TSegment2
struct TSegment3
struct TShiftGridIndexer2
Convert between integer grid coordinates and scaled+translated real-valued coordinates.
struct TShiftGridIndexer3
Convert between integer grid coordinates and scaled+translated real-valued coordinates.
struct TSkeletalImplicitLine3
Skeletal implicit line primitive.
struct TSkeletalRicciNaryBlend3
Boolean Union of N implicit functions (F_1 or F_2 or ... or F_N) Or if bSubtract=true, Subtraction: (F_1 - (F_2 or F_3 or ... or F_N)) We expect this to be used with "Skeletal Field" inputs (e.g.
class TSmoothBoneWeights
Collection of algorithms for smoothing bone weights.
class TSparseGrid2
Dynamic sparse 2D grid.
class TSparseGrid3
Dynamic sparse 3D grid.
struct TSparseListSet
TSparseListSet stores a sparse set of indexed variable-size lists.
class TSparseNarrowBandMeshSDF
Compute discretely-sampled (ie gridded) signed distance field for a mesh within a specified narrow band.
struct TSpatialPhoto
TSpatialPhoto represents a 2D image located in 3D space, ie the image plus camera parameters, which is essentially a "Photograph" of some 3D scene (hence the name)
class TSpatialPhotoSet
TSpatialPhotoSet is a set of TSpatialPhotos.
struct TSphere3
class TSphericalFibonacci
A Spherical Fibonacci (SF) Point Set is a set of points that are roughly evenly distributed on a sphere.
class TSweepingMeshSDF
Compute discretely-sampled (ie gridded) signed distance field for a mesh The basic approach is, first compute exact Distances in a narrow band, and then extend out to rest of Grid using fast "sweeping" (ie like a distance transform).
struct TTetrahedron3
class TTransformSequence3
TTransformSequence3 represents a sequence of 3D transforms.
class TTransformSRT3
TTransformSRT3 is a variant of the standard UE FTransform/TTransform that uses the UE::Geometry::TQuaternion instead of the UE::Math::TQuat.
struct TTriangle2
struct TTriangle3
struct TTriangleMeshAdapter
Most generic / lazy example of a triangle mesh adapter; possibly useful for prototyping / building on top of (but slower than making a more specific-case adapter)
class TTriLinearGridInterpolant
Tri-linear interpolant for a 3D dense Grid.
class TVector2Arrays
Structure-of-Array (SoA) storage for a list of 2-vectors.
class TVector3Arrays
Structure-of-Array (SoA) storage for a list of 3-vectors.
class TVectorSetAnalysis3
TVectorSetAnalysis3 computes various analyses of a set of input Vectors (currently mainly clustering.
class TVolPresQuadricError
Quadric Error type for use in memory-less simplification with volume preservation constraints.
struct TWatertightRay3
class TWeightedSamplingAliasTable
Typedefs
typedef TAttrBasedQuadricError< double > FAttrBasedQuadricErrord
typedef TAttrBasedQuadricError< float > FAttrBasedQuadricErrorf
typedef TMeshSimplification< FAttrBasedQuadricErrord > FAttrMeshSimplification
typedef TAxisAlignedBox2< double > FAxisAlignedBox2d
typedef TAxisAlignedBox2< float > FAxisAlignedBox2f
typedef TAxisAlignedBox3< double > FAxisAlignedBox3d
typedef TAxisAlignedBox3< float > FAxisAlignedBox3f
typedef TBlendPairedKelvinlet< FTwistKelvinlet, FBiLaplacianPullKelvinlet > FBiLaplacianTwistPullKelvinlet
typedef TBlendPairedKelvinlet< FBiLaplacianPullKelvinlet, FLaplacianPullKelvinlet > FBlendPullKelvinlet
typedef TBlendPairedKelvinlet< FSharpBiLaplacianPullKelvinlet, FSharpLaplacianPullKelvinlet > FBlendPullSharpKelvinlet
typedef TBlockedDenseGrid3< double > FBlockedDenseGrid3d
typedef TBlockedDenseGrid3< float > FBlockedDenseGrid3f
typedef TBlockedDenseGrid3< int > FBlockedDenseGrid3i
typedef TBlockedGrid3< bool, 8 > FBlockedGrid3b
typedef TBlockedGrid3< double, 8 > FBlockedGrid3d
typedef TBlockedGrid3< float, 8 > FBlockedGrid3f
typedef TBlockedGrid3< int, 8 > FBlockedGrid3i
typedef TBoundsGridIndexer3< double > FBoundsGridIndexer3d
typedef TBoundsGridIndexer3< float > FBoundsGridIndexer3f
using FBSplineFilter = FBCSplineFilter<EBCSplineType::BSpline, false>
typedef TCapsule3< double > FCapsule3d
typedef TCapsule3< float > FCapsule3f
using FCatmullRomFilter = FBCSplineFilter<EBCSplineType::CatmullRom, false>
typedef TCircle2< double > FCircle2d
typedef TCircle2< float > FCircle2f
typedef TCircle3< double > FCircle3d
typedef TCircle3< float > FCircle3f
typedef TConstrainedDelaunay2< double > FConstrainedDelaunay2d
typedef TConstrainedDelaunay2< float > FConstrainedDelaunay2f
typedef TConvexHull2< double > FConvexHull2d
typedef TConvexHull2< float > FConvexHull2f
typedef TConvexHull3< double > FConvexHull3d
typedef TConvexHull3< float > FConvexHull3f
typedef TDenseGrid2< double > FDenseGrid2d
typedef TDenseGrid2< float > FDenseGrid2f
typedef TDenseGrid2< int32 > FDenseGrid2i
typedef TDenseGrid3< double > FDenseGrid3d
typedef TDenseGrid3< float > FDenseGrid3f
typedef TDenseGrid3< int > FDenseGrid3i
typedef TDifferencePolygon2Polygon2< TGeneralPolygon2< double >, double > FDifferenceGeneralPolygon2GeneralPolygon2d
typedef TDifferencePolygon2Polygon2< TGeneralPolygon2< float >, float > FDifferenceGeneralPolygon2GeneralPolygon2f
typedef TDistLine2AxisAlignedBox2< double > FDistLine2AxisAlignedBox2d
typedef TDistLine2AxisAlignedBox2< float > FDistLine2AxisAlignedBox2f
typedef TDistLine3Circle3< double > FDistLine3Circle3d
typedef TDistLine3Circle3< float > FDistLine3Circle3f
typedef TDistLine3Line3< double > FDistLine3Line3d
typedef TDistLine3Line3< float > FDistLine3Line3f
typedef TDistLine3Ray3< double > FDistLine3Ray3d
typedef TDistLine3Ray3< float > FDistLine3Ray3f
typedef TDistLine3Segment3< double > FDistLine3Segment3d
typedef TDistLine3Segment3< float > FDistLine3Segment3f
typedef TDistLine3Triangle3< double > FDistLine3Triangle3d
typedef TDistLine3Triangle3< float > FDistLine3Triangle3f
typedef TDistPoint3Triangle3< double > FDistPoint3Triangle3d
typedef TDistPoint3Triangle3< float > FDistPoint3Triangle3f
typedef TDistRay3Segment3< double > FDistRay3Segment3d
typedef TDistRay3Segment3< float > FDistRay3Segment3f
typedef TDistSegment2AxisAlignedBox2< double > FDistSegment2AxisAlignedBox2d
typedef TDistSegment2AxisAlignedBox2< float > FDistSegment2AxisAlignedBox2f
typedef TDistSegment3Triangle3< double > FDistSegment3Triangle3d
typedef TDistSegment3Triangle3< float > FDistSegment3Triangle3f
typedef TDistTriangle3Triangle3< double > FDistTriangle3Triangle3d
typedef TDistTriangle3Triangle3< float > FDistTriangle3Triangle3f
typedef FDynamicGraph2< double > FDynamicGraph2d
typedef FDynamicGraph3< double > FDynamicGraph3d
typedef TMeshAABBTree3< FDynamicMesh3 > FDynamicMeshAABBTree3
typedef TDynamicAttributeBase< FDynamicMesh3 > FDynamicMeshAttributeBase
typedef TDynamicAttributeChangeBase< FDynamicMesh3 > FDynamicMeshAttributeChangeBase
typedef TDynamicAttributeSetBase< FDynamicMesh3 > FDynamicMeshAttributeSetBase
using FDynamicMeshBoneColorAttribute = TDynamicBoneAttributeBase<FDynamicMesh3, FVector4f>
using FDynamicMeshBoneNameAttribute = TDynamicBoneAttributeBase<FDynamicMesh3, FName>
using FDynamicMeshBoneParentIndexAttribute = TDynamicBoneAttributeBase<FDynamicMesh3, int32>
using FDynamicMeshBonePoseAttribute = TDynamicBoneAttributeBase<FDynamicMesh3, FTransform>
typedef TDynamicMeshAttributeChange< float, 4 > FDynamicMeshColorChange
Standard Color overlay change type - 4-element float.
typedef TDynamicMeshVectorOverlay< float, 4, FVector4f > FDynamicMeshColorOverlay
Standard Color overlay type - 4-element float (rbga)
typedef TDynamicMeshScalarTriangleAttribute< int32 > FDynamicMeshMaterialAttribute
Standard per-triangle integer material ID.
typedef TDynamicMeshAttributeChange< float, 3 > FDynamicMeshNormalChange
Standard Normal overlay change type - 3-element float.
typedef TDynamicMeshVectorOverlay< float, 3, FVector3f > FDynamicMeshNormalOverlay
Standard Normal overlay type - 3-element float.
typedef TDynamicMeshScalarTriangleAttribute< int32 > FDynamicMeshPolygroupAttribute
Per-triangle integer polygroup ID.
typedef TDynamicMeshVertexAttribute< double, 3 > FDynamicMeshSculptLayerAttribute
Per-vertex position offsets.
typedef FDynamicMeshTriangleAttributeChange< int32, 1 > FDynamicMeshTriGroupChange
Standard per-triangle integer attribute change type.
typedef TDynamicMeshAttributeChange< float, 2 > FDynamicMeshUVChange
Standard UV overlay change type - 2-element float.
typedef TDynamicMeshVectorOverlay< float, 2, FVector2f > FDynamicMeshUVOverlay
Standard UV overlay type - 2-element float.
using FDynamicMeshVertexSkinWeightsAttribute = TDynamicVertexSkinWeightsAttribute<FDynamicMesh3>
typedef TDynamicMeshVertexAttribute< float, 1 > FDynamicMeshWeightAttribute
Per-vertex scalar float weight.
typedef TDynamicMeshAttributeChange< float, 1 > FDynamicMeshWeightChange
Standard weight map change type - 1-element float.
typedef TDynamicPointSet3< double > FDynamicPointSet3d
typedef TDynamicPointSet3< float > FDynamicPointSet3f
typedef TExactIntrTriangle3Triangle3< double > FExactIntrTriangle3Triangle3d
typedef TExactIntrTriangle3Triangle3< float > FExactIntrTriangle3Triangle3f
typedef TExclusiveOrPolygon2Polygon2< TGeneralPolygon2< double >, double > FExclusiveOrGeneralPolygon2GeneralPolygon2d
typedef TExclusiveOrPolygon2Polygon2< TGeneralPolygon2< float >, float > FExclusiveOrGeneralPolygon2GeneralPolygon2f
typedef TExtremePoints3< double > FExtremePoints3d
typedef TExtremePoints3< float > FExtremePoints3f
typedef TFitCapsule3< double > FFitCapsule3d
typedef TFitCapsule3< float > FFitCapsule3f
typedef TFrame3< double > FFrame3d
typedef TFrame3< float > FFrame3f
typedef TGeneralPolygon2< double > FGeneralPolygon2d
typedef TGeneralPolygon2< float > FGeneralPolygon2f
typedef THalfspace3< double > FHalfspace3d
typedef THalfspace3< float > FHalfspace3f
typedef TImplicitLine3< double > FImplicitLine3d
typedef TImplicitLine3< float > FImplicitLine3f
typedef TImplicitPoint3< double > FImplicitPoint3d
typedef TImplicitPoint3< float > FImplicitPoint3f
typedef TIndexedWeightMap< float > FIndexedWeightMap
typedef TIndexedWeightMap< double > FIndexedWeightMap1d
typedef TIndexedWeightMap< float > FIndexedWeightMap1f
typedef TIndexMap< int > FIndexMapi
typedef TIndexMeshArrayAdapter< uint32, double > FIndexMeshArrayAdapterd
typedef TIntersectPolygon2Polygon2< TGeneralPolygon2< double >, double > FIntersectGeneralPolygon2GeneralPolygon2d
typedef TIntersectPolygon2Polygon2< TGeneralPolygon2< float >, float > FIntersectGeneralPolygon2GeneralPolygon2f
typedef TIntersector1< double > FIntersector1d
typedef TIntersector1< float > FIntersector1f
typedef TInterval1< double > FInterval1d
typedef TInterval1< float > FInterval1f
typedef TIntrLine2Line2< double > FIntrLine2Line2d
typedef TIntrLine2Line2< float > FIntrLine2Line2f
typedef TIntrLine2Triangle2< double > FIntrLine2Triangle2d
typedef TIntrLine2Triangle2< float > FIntrLine2Triangle2f
typedef TIntrRay3AxisAlignedBox3< double > FIntrRay3AxisAlignedBox3d
typedef TIntrRay3AxisAlignedBox3< float > FIntrRay3AxisAlignedBox3f
typedef TIntrRay3OrientedBox3< double > FIntrRay3OrientedBox3d
typedef TIntrRay3OrientedBox3< float > FIntrRay3OrientedBox3f
typedef TIntrRay3Triangle3< double > FIntrRay3Triangle3d
typedef TIntrRay3Triangle3< float > FIntrRay3Triangle3f
typedef TIntrSegment2Segment2< double > FIntrSegment2Segment2d
typedef TIntrSegment2Segment2< float > FIntrSegment2Segment2f
typedef TIntrSegment2Triangle2< double > FIntrSegment2Triangle2d
typedef TIntrSegment2Triangle2< float > FIntrSegment2Triangle2f
typedef TIntrTriangle2AxisAlignedBox2< double > FIntrTriangle2AxisAlignedBox2d
typedef TIntrTriangle2AxisAlignedBox2< float > FIntrTriangle2AxisAlignedBox2f
typedef TIntrTriangle2Triangle2< double > FIntrTriangle2Triangle2d
typedef TIntrTriangle2Triangle2< float > FIntrTriangle2Triangle2f
typedef TIntrTriangle3Triangle3< double > FIntrTriangle3Triangle3d
typedef TIntrTriangle3Triangle3< float > FIntrTriangle3Triangle3f
typedef TBlendPairedKelvinlet< FTwistKelvinlet, FLaplacianPullKelvinlet > FLaplacianTwistPullKelvinlet
typedef TLine2< double > FLine2d
typedef TLine2< float > FLine2f
typedef TLine3< double > FLine3d
typedef TLine3< float > FLine3f
typedef TMatrix2< double > FMatrix2d
typedef TMatrix2< float > FMatrix2f
typedef TMatrix3< double > FMatrix3d
typedef TMatrix3< float > FMatrix3f
typedef TMeshTangents< double > FMeshTangentsd
typedef TMeshTangents< float > FMeshTangentsf
using FMeshUniformSurfaceSampling = TMeshUniformSurfaceSampling<FDynamicMesh3, double>
typedef TMinVolumeBox3< double > FMinVolumeBox3d
typedef TMinVolumeBox3< float > FMinVolumeBox3f
typedef TMinVolumeSphere3< double > FMinVolumeSphere3d
typedef TMinVolumeSphere3< float > FMinVolumeSphere3f
using FMitchellNetravaliFilter = FBCSplineFilter<EBCSplineType::MitchellNetravali, false>
typedef TOffsetPolygon2< TArrayView< TVector2< double > >, double > FOffsetPolygon2d
typedef TOffsetPolygon2< TArrayView< TVector2< float > >, float > FOffsetPolygon2f
typedef TOrientedBox2< double > FOrientedBox2d
typedef TOrientedBox2< float > FOrientedBox2f
typedef TOrientedBox3< double > FOrientedBox3d
typedef TOrientedBox3< float > FOrientedBox3f
typedef TPCA3< double > FPCA3d
typedef TPCA3< float > FPCA3f
typedef TPlanarComplex< double > FPlanarComplexd
typedef TPlanarComplex< float > FPlanarComplexf
typedef TPlane3< double > FPlane3d
typedef TPlane3< float > FPlane3f
typedef TPointSetAdapter< double > FPointSetAdapterd
typedef TPointSetAdapter< float > FPointSetAdapterf
typedef TPolygon2< double > FPolygon2d
typedef TPolygon2< float > FPolygon2f
typedef TPolyline2< double > FPolyline2d
typedef TPolyline2< float > FPolyline2f
typedef TPolyline3< double > FPolyline3d
typedef TPolyline3< float > FPolyline3f
typedef TMeshSimplification< FQuadricErrord > FQEMSimplification
typedef TQuadricError< double > FQuadricErrord
typedef TQuadricError< float > FQuadricErrorf
typedef TQuaternion< double > FQuaterniond
typedef TQuaternion< float > FQuaternionf
typedef TSampledScalarField2< double, double > FSampledScalarField2d
typedef TSampledScalarField2< float, float > FSampledScalarField2f
typedef TSampleSetStatistics< double > FSampleSetStatisticsd
typedef TSampleSetStatistics< float > FSampleSetStatisticsf
typedef TScaleGridIndexer2< double > FScaleGridIndexer2d
typedef TScaleGridIndexer2< float > FScaleGridIndexer2f
typedef TScaleGridIndexer3< double > FScaleGridIndexer3d
typedef TScaleGridIndexer3< float > FScaleGridIndexer3f
typedef TSegment2< double > FSegment2d
typedef TSegment2< float > FSegment2f
typedef TSegment3< double > FSegment3d
typedef TSegment3< float > FSegment3f
typedef TConstObjectSharedAccess< FDynamicMesh3 > FSharedConstDynamicMesh3
typedef TShiftGridIndexer2< double > FShiftGridIndexer2d
typedef TShiftGridIndexer2< float > FShiftGridIndexer2f
typedef TShiftGridIndexer3< double > FShiftGridIndexer3d
typedef TShiftGridIndexer3< float > FShiftGridIndexer3f
typedef TSkeletalImplicitLine3< double > FSkeletalImplicitLine3d
typedef TSkeletalImplicitLine3< float > FSkeletalImplicitLine3f
typedef TSpatialPhoto< float > FSpatialPhoto1f
typedef TSpatialPhoto< FVector3f > FSpatialPhoto3f
typedef TSpatialPhoto< FVector4f > FSpatialPhoto4f
typedef TSpatialPhotoSet< float, float > FSpatialPhotoSet1f
typedef TSpatialPhotoSet< FVector3f, float > FSpatialPhotoSet3f
typedef TSpatialPhotoSet< FVector4f, float > FSpatialPhotoSet4f
typedef TSphere3< double > FSphere3d
typedef TSphere3< float > FSphere3f
typedef TTetrahedron3< double > FTetrahedron3d
typedef TTetrahedron3< float > FTetrahedron3f
typedef TTransformSequence3< double > FTransformSequence3d
typedef TTransformSequence3< float > FTransformSequence3f
typedef TTransformSRT3< double > FTransformSRT3d
typedef TTransformSRT3< float > FTransformSRT3f
typedef TTriangle2< double > FTriangle2d
typedef TTriangle2< float > FTriangle2f
typedef TTriangle3< double > FTriangle3d
typedef TTriangle3< float > FTriangle3f
typedef TTriangle3< int > FTriangle3i
typedef TTriangleMeshAdapter< double > FTriangleMeshAdapterd
typedef TTriangleMeshAdapter< float > FTriangleMeshAdapterf
typedef TUnionPolygon2Polygon2< TGeneralPolygon2< double >, double > FUnionGeneralPolygon2GeneralPolygon2d
typedef TUnionPolygon2Polygon2< TGeneralPolygon2< float >, float > FUnionGeneralPolygon2GeneralPolygon2f
typedef TVectorSetAnalysis3< double > FVectorSetAnalysis3d
typedef TVectorSetAnalysis3< float > FVectorSetAnalysis3f
typedef TMeshSimplification< FVolPresQuadricErrord > FVolPresMeshSimplification
typedef TVolPresQuadricError< double > FVolPresQuadricErrord
typedef TVolPresQuadricError< float > FVolPresQuadricErrorf
typedef TWatertightRay3< double > FWatertightRay3d
typedef TWatertightRay3< float > FWatertightRay3f
using FWeightedSamplingAliasTabled = TWeightedSamplingAliasTable<double>
using FWeightedSamplingAliasTablef = TWeightedSamplingAliasTable<float>
template<EPolygonBooleanOp OperationType>
using TBooleanGeneralPolygon2GeneralPolygon2d = TBooleanPolygon2Polygon2<OperationType, TGeneralPolygon2<double>, double>
template<EPolygonBooleanOp OperationType>
using TBooleanGeneralPolygon2GeneralPolygon2f = TBooleanPolygon2Polygon2<OperationType, TGeneralPolygon2<float>, float>
template<typename GeometryType, typename RealType>
using TDifferencePolygon2Polygon2 = TBooleanPolygon2Polygon2<EPolygonBooleanOp::Difference, GeometryType, RealType>
Produces the result of PolygonA with the shape of PolygonB removed.
typedef TDiscreteKernel2< double > TDiscreteKernel2d
typedef TDiscreteKernel2< float > TDiscreteKernel2f
template<typename AttribValueType, int AttribDimension>
using TDynamicMeshVertexAttribute = TDynamicVertexAttribute<AttribValueType, AttribDimension, FDynamicMesh3>
using TDynamicVector2d = TDynamicVectorN<double, 2>
using TDynamicVector2f = TDynamicVectorN<float, 2>
using TDynamicVector2i = TDynamicVectorN<int, 2>
using TDynamicVector3d = TDynamicVectorN<double, 3>
using TDynamicVector3f = TDynamicVectorN<float, 3>
using TDynamicVector3i = TDynamicVectorN<int, 3>
template<typename GeometryType, typename RealType>
using TExclusiveOrPolygon2Polygon2 = TBooleanPolygon2Polygon2<EPolygonBooleanOp::ExclusiveOr, GeometryType, RealType>
Produces the areas of each polygon not present in the other as a combined result.
typedef TGaussian1< double > TGaussian1d
typedef TGaussian1< float > TGaussian1f
typedef TGaussian2< double > TGaussian2d
typedef TGaussian2< float > TGaussian2f
typedef TGaussian3< double > TGaussian3d
typedef TGaussian3< float > TGaussian3f
template<typename GeometryType, typename RealType>
using TIntersectPolygon2Polygon2 = TBooleanPolygon2Polygon2<EPolygonBooleanOp::Intersect, GeometryType, RealType>
Produces the areas of each polygon that are also present in the other as a combined result.
template<typename PointDataType>
using TPointHashGrid2d = TPointHashGrid2<PointDataType, double>
template<typename PointDataType>
using TPointHashGrid2f = TPointHashGrid2<PointDataType, float>
template<typename PointDataType>
using TPointHashGrid3d = TPointHashGrid3<PointDataType, double>
template<typename PointDataType>
using TPointHashGrid3f = TPointHashGrid3<PointDataType, float>
template<typename T>
using TPolyline2 = TPolyline<T, 2>
template<typename T>
using TPolyline3 = TPolyline<T, 3>
template<typename GeometryType, typename RealType>
using TUnionPolygon2Polygon2 = TBooleanPolygon2Polygon2<EPolygonBooleanOp::Union, GeometryType, RealType>
Produces the combined result of PolygonA and PolygonB.
Enumerations
enum class EActorMeshComponentType {
StaticMesh , InstancedStaticMesh , HierarchicalInstancedStaticMesh , InternallyGeneratedComponent ,
Unknown
}
EActorMeshComponentType enum is used to determine which type of Component an FActorChildMesh represents.
enum class EBackgroundComputeTaskStatus {
ValidResultAvailable , DirtyResultAvailable , Aborted , InProgress ,
NotComputing
}
This status is returned by TBackgroundModelingComputeSource to indicate what state a background computation is in.
enum class EBCSplineType { BSpline , CatmullRom , MitchellNetravali }
enum EBox2FitCriteria { Area , Perimeter }
enum EBox3FitCriteria { Volume , SurfaceArea }
enum class ECapType { None = 0 , FlatTriangulation = 1 , FlatMidpointFan = 2 }
ECapType indicates the type of cap to use on a sweep.
enum EComponentCollisionSupportLevel { ReadOnly = 0 , ReadWrite = 1 }
enum class EConvexErrorMethod { RelativeVolume }
enum class EDetectedSimpleShapeType {
None = 0 , Sphere = 2 , Box = 4 , Capsule = 8 ,
Convex = 16
}
EDetectedSimpleShapeType is used to identify auto-detected simple shapes for a mesh/etc.
enum EDiTO { DiTO_12 = 0 , DiTO_14 = 1 , DiTO_20 = 2 , DiTO_26 = 3 }
selects the number of extremal vertices and directional vector family for the DiTO - K algorithm, with implementations for K = {12, 14, 20, 26}
enum class EEdgeRefineFlags {
NoConstraint = 0 , NoFlip = 1 , NoSplit = 2 , NoCollapse = 4 ,
FullyConstrained = NoFlip | NoSplit | NoCollapse , SplitsOnly = NoFlip | NoCollapse , FlipOnly = NoSplit | NoCollapse , CollapseOnly = NoFlip | NoSplit
}
EEdgeRefineFlags indicate constraints on triangle mesh edges.
enum class EEnumerateSelectionConversionParams { ContainSelection , ExpandSelection }
enum class EEnumerateSelectionMapping : uint8 { None = 0 , FacesToFaces = 1 << 0 , FacesToEdges = 1 << 1 , Default = FacesToFaces }
enum class EFBMMode : uint8 { Standard , Turbulent , Ridge }
enum class EGeometryElementType { Vertex = 1 , Edge = 2 , Face = 4 }
Type of selected Elements in a FGeometrySelection.
enum class EGeometryPointType { Triangle = 0 , Edge = 1 , Vertex = 2 }
enum class EGeometryResultType {
Success = 0 , InProgress = 1 , Cancelled = 2 , PartialResult = 3 ,
Failure = 4
}
EGeometryResultType is a generic result-code for use by geometry operations.
enum class EGeometrySelectionChangeType { Add , Remove , Replace }
Type of change, relative to a FGeometrySelection.
enum class EGeometrySelectionCombineModes : uint8 { Add , Subtract , Intersection }
enum class EGeometryTopologyType { Triangle = 1 , Polygroup = 2 }
Type of selected Topology in a FGeometrySelection.
enum class EImageTilingMethod { Clamp , Wrap }
enum class ELatticeInterpolation : uint8 { Linear = 0 , Cubic = 1 }
enum class ELocalParamTypes : uint8 { PlanarProjection = 1 , ExponentialMap = 2 , ExponentialMapUpwindAvg = 3 }
Type of local parameterization.
enum class EMeshAttributeTransferError {
InvalidSource , InvalidTarget , SourceMissingAttribute , TargetMissingAttribute ,
InvalidOperationForInputs
}
enum class EMeshAttributeTransferType { MaterialID }
enum class EMeshComponents : uint8 {
None = 0 , VertexNormals = 1 , VertexColors = 2 , VertexUVs = 4 ,
FaceGroups = 8 , All = 15
}
enum class EMeshMapEvaluatorType {
Constant , Normal , Occlusion , Curvature ,
Property , ResampleImage , MultiResampleImage , RenderCapture ,
UVShell , Height
}
enum class EMeshOcclusionMapType : uint8 { None = 0 , AmbientOcclusion = 1 , BentNormal = 2 , All = 3 }
enum class EMeshPropertyBakeType {
Position = 1 , Normal = 2 , FacetNormal = 3 , UVPosition = 4 ,
MaterialID = 5
}
enum class EMeshPropertyMapType {
Position = 1 , Normal = 2 , FacetNormal = 3 , UVPosition = 4 ,
MaterialID = 5 , VertexColor = 6 , PolyGroupID = 7
}
enum class EMeshResult {
Ok = 0 , Failed_NotAVertex = 1 , Failed_NotATriangle = 2 , Failed_NotAnEdge = 3 ,
Failed_BrokenTopology = 10 , Failed_HitValenceLimit = 11 , Failed_IsBoundaryEdge = 20 , Failed_FlippedEdgeExists = 21 ,
Failed_IsBowtieVertex = 22 , Failed_InvalidNeighbourhood = 23 , Failed_FoundDuplicateTriangle = 24 , Failed_CollapseTetrahedron = 25 ,
Failed_CollapseTriangle = 26 , Failed_NotABoundaryEdge = 27 , Failed_SameOrientation = 28 , Failed_CollapseQuad = 29 ,
Failed_WouldCreateBowtie = 30 , Failed_VertexAlreadyExists = 31 , Failed_CannotAllocateVertex = 32 , Failed_VertexStillReferenced = 33 ,
Failed_WouldCreateNonmanifoldEdge = 50 , Failed_TriangleAlreadyExists = 51 , Failed_CannotAllocateTriangle = 52 , Failed_UnrecoverableError = 1000 ,
Failed_Unsupported = 1001
}
EMeshResult is returned by various mesh/graph operations to either indicate success, or communicate which type of error ocurred (some errors are recoverable, and some not).
enum class EMeshSurfaceSamplerQueryType : uint8 { UVOnly , TriangleAndUV }
Types of query that FMeshSurfaceUVSampler/TMeshSurfaceUVSampler supports.
enum class EOcclusionCalculationMode { FastWindingNumber = 0 , SimpleOcclusionTest = 1 }
enum class EOcclusionMapType : uint8 { None = 0 , AmbientOcclusion = 1 , BentNormal = 2 , All = 3 }
enum class EOcclusionTriangleSampling { Centroids = 0 , Vertices = 1 , VerticesAndCentroids = 2 }
enum class EOperationValidationResult { Ok = 0 , Failed_UnknownReason = 1 , Failed_InvalidTopology = 2 }
EOperationValidationResult is meant to be returned by Validate() functions of Operation classes (eg like ExtrudeMesh, etc) to indicate whether the operation can be successfully applied.
enum class EPolygonBooleanOp : uint8 { Union , Difference , Intersect , ExclusiveOr }
enum class EPolygonOffsetEndType : uint8 {
Polygon , Joined , Butt , Square ,
Round
}
enum class EPolygonOffsetJoinType : uint8 { Square , Round , Miter }
enum class EProfileSweepPolygonGrouping : uint8 { Single , PerFace , PerSweepSegment , PerProfileSegment }
enum class EProfileSweepQuadSplit : uint8 { Uniform , ShortestDiagonal }
enum class ERecomputeUVsIslandMode { PolyGroups = 0 , UVIslands = 1 }
enum class ERecomputeUVsUnwrapType { ExpMap = 0 , ConformalFreeBoundary = 1 , SpectralConformal = 2 }
enum class ERenderCaptureChannel {
BaseColor = 1 , Roughness = 2 , Metallic = 4 , Specular = 8 ,
Emissive = 16 , WorldNormal = 32 , DeviceDepth = 64 , CombinedMRS = 128 ,
Opacity = 256 , SubsurfaceColor = 512
}
enum class ERenderCaptureType {
BaseColor = 1 , Roughness = 2 , Metallic = 4 , Specular = 8 ,
Emissive = 16 , WorldNormal = 32 , DeviceDepth = 64 , CombinedMRS = 128 ,
Opacity = 256 , SubsurfaceColor = 512
}
ERenderCaptureType defines which type of render buffer should be captured.
enum class ERootfindingModes { SingleLerp , LerpSteps , Bisection }
enum class ERoundedRectangleCorner : uint8 {
None = 0 , BottomLeft = 1 , BottomRight = 2 , TopLeft = 4 ,
TopRight = 8 , All = 15
}
enum class ESceneMeshType { StaticMeshAsset , Unknown }
ESceneMeshType is used to indicate which type of Mesh a FMeshTypeContainer contains.
enum class ESimpleShapeType {
Sphere = 2 , Box = 4 , Capsule = 8 , Convex = 16 ,
LevelSet = 32
}
Supported/known types of Simple Shapes.
enum class ESimplificationResult {
Ok_Collapsed = 0 , Ignored_CannotCollapse = 1 , Ignored_EdgeIsFullyConstrained = 2 , Ignored_EdgeTooLong = 3 ,
Ignored_Constrained = 4 , Ignored_CreatesFlip = 5 , Failed_OpNotSuccessful = 6 , Failed_NotAnEdge = 7 ,
Failed_IsolatedTriangle = 8 , Failed_GeometricDeviation = 9 , Ignored_CreatesTinyTriangle = 10
}
enum class ESkinBindingType : uint8 { DirectDistance = 0 , GeodesicVoxel = 1 }
enum class ESurfacePointType { Vertex = 0 , Edge = 1 , Triangle = 2 }
enum class EUVEditorAlignAnchorBackend { UDIMTile , BoundingBox , Manual }
enum class EUVEditorAlignDirectionBackend {
None , Top , Bottom , Left ,
Right , CenterVertically , CenterHorizontally
}
enum class EUVEditorAlignDistributeGroupingModeBackend { IndividualBoundingBoxes , EnclosingBoundingBox , IndividualVertices }
enum class EUVEditorDistributeModeBackend {
None , LeftEdges , RightEdges , TopEdges ,
BottomEdges , CentersVertically , CentersHorizontally , VerticalSpace ,
HorizontalSpace , MinimallyRemoveOverlap
}
enum class EUVEditorPivotTypeBackend { Origin , IndividualBoundingBoxCenter , BoundingBoxCenter , Manual }
enum class EUVEditorTranslationModeBackend { Relative , Absolute }
enum class EUVEditorUVTransformTypeBackend { Transform , Align , Distribute }
enum class EUVLayoutOpLayoutModes { TransformOnly = 0 , RepackToUnitRect = 1 , StackInUnitRect = 2 , Normalize = 3 }
enum class EUVTexelDensityOpModes { ScaleGlobal = 0 , ScaleIslands = 1 , Normalize = 2 }
enum class EValidityCheckFailMode { ReturnOnly = 0 , Check = 1 , Ensure = 2 }
EValidityCheckFailMode is passed to CheckValidity() functions of various classes to specify how validity checks should fail.
Functions
template<typename IterT>
IterT AdvanceIterator (IterT Start, int64 N)
template<typename ContainerType, typename ElementType, typename SizeType>
TIndexedContainerIterator< ContainerType, ElementType, SizeType > AdvanceIterator (TIndexedContainerIterator< ContainerType, ElementType, SizeType > Begin, SizeType N)
template<typename T>
T AngleD (const UE::Math::TVector2< T > &V1, const UE::Math::TVector2< T > &V2)
template<typename T>
T AngleD (const UE::Math::TVector< T > &V1, const UE::Math::TVector< T > &V2)
Computes the Angle between V1 and V2, assuming they are already normalized.
template<typename T>
T AngleR (const UE::Math::TVector2< T > &V1, const UE::Math::TVector2< T > &V2)
template<typename T>
T AngleR (const UE::Math::TVector< T > &V1, const UE::Math::TVector< T > &V2)
Computes the Angle between V1 and V2, assuming they are already normalized.
GEOMETRYSCRIPTINGCORE_API void AppendError (TArray< FGeometryScriptDebugMessage > *DebugMessages, EGeometryScriptErrorType ErrorTypeIn, const FText &MessageIn)
These variants of AppendError/Warning are for direct write to a debug message array.
GEOMETRYSCRIPTINGCORE_API void AppendError (UGeometryScriptDebug *Debug, EGeometryScriptErrorType ErrorTypeIn, const FText &MessageIn)
MODELINGCOMPONENTS_API bool AppendSimpleCollision (const UPrimitiveComponent *SourceComponent, FSimpleShapeSet3d *ShapeSetOut, const FTransform3d &Transform)
Apply Transform to the existing Simple Collision geometry in Component and then append to to ShapeSetOut.
MODELINGCOMPONENTS_API bool AppendSimpleCollision (const UPrimitiveComponent *SourceComponent, FSimpleShapeSet3d *ShapeSetOut, const TArray< FTransform3d > &TransformSeqeuence)
Apply TransformSequence (in-order) to the existing Simple Collision geometry in Component and then append to to ShapeSetOut.
GEOMETRYSCRIPTINGCORE_API void AppendWarning (TArray< FGeometryScriptDebugMessage > *DebugMessages, EGeometryScriptErrorType WarningTypeIn, const FText &MessageIn)
GEOMETRYSCRIPTINGCORE_API void AppendWarning (UGeometryScriptDebug *Debug, EGeometryScriptErrorType WarningTypeIn, const FText &MessageIn)
DYNAMICMESH_API bool AreSelectionsIdentical (const FGeometrySelection &SelectionA, const FGeometrySelection &SelectionB)
Test if SelectionA and SelectionB are the same selection.
static double AsZeroToTwoPi (double AngleR)
return AngleR in [0,2pi) range.
template<typename T>
UE::Math::TVector< T > Blend3 (const UE::Math::TVector< T > &A, const UE::Math::TVector< T > &B, const UE::Math::TVector< T > &C, const T &WeightA, const T &WeightB, const T &WeightC)
bool GEOMETRYALGORITHMS_API BSplineCurveFit (const TArray< FVector2f > &DataPoints, const int32 SplineDegree, const int32 NumControlPoints, TArray< FVector2f > &ControlPointsOut)
Compute the control points that result from a best fit of the provided 2d data points when using b-splines of the specified degree.
bool GEOMETRYALGORITHMS_API BSplineCurveFit (const TArray< FVector3f > &DataPoints, const int32 SplineDegree, const int32 NumControlPoints, TArray< FVector3f > &ControlPointsOut)
Compute the control points that result from a best fit of the provided 3d data points when using b-splines of the specified degree.
template<typename EnumeratorType, typename SetType>
void CollectVertexPositions (const FDynamicMesh3 &Mesh, EnumeratorType Enumeration, SetType &Output)
Call SetType.Add(VertexPosition) for all valid vertex indices in for_each(Enumeration)
DYNAMICMESH_API bool CombineSelectionInPlace (FGeometrySelection &SelectionA, const FGeometrySelection &SelectionB, EGeometrySelectionCombineModes CombineMode)
Combine the elements of SelectionA and SelectionB using the provided CombineMode, and store the result in SelectionA.
MODELINGCOMPONENTS_API void CommitDynamicMeshViaMeshDescription (FMeshDescription &&CurrentMeshDescription, IMeshDescriptionCommitter &MeshDescriptionCommitter, const UE::Geometry::FDynamicMesh3 &Mesh, const IDynamicMeshCommitter::FDynamicMeshCommitInfo &CommitInfo)
GEOMETRYCORE_API bool CompactAttributeValues (const FDynamicMesh3 &Mesh, TDynamicMeshScalarTriangleAttribute< int32 > &TriangleAttrib, FInterval1i &OldMaxAttributeRangeOut, int &NewMaxAttributeValueOut, TArray< int32 > &OldToNewMapOut, TArray< int32 > &NewToOldMapOut, bool &bWasCompactOut)
Compact the values of an integer Triangle Attribute, ie so that the attribute values are dense in range 0..N.
MODELINGCOMPONENTS_API bool ComponentTypeSupportsCollision (const UPrimitiveComponent *Component, EComponentCollisionSupportLevel SupportLevel=EComponentCollisionSupportLevel::ReadWrite)
DYNAMICMESH_API void ComputeArbitraryTrianglePatchUVs (FDynamicMesh3 &Mesh, FDynamicMeshUVOverlay &UVOverlay, const TArray< int32 > &TriangleSet)
Create a new single UV island for the provided TriangleSet in the given Mesh/UVOverlay, by computing an ExpMap parameterization based on an automatically-detected midpoint of the triangle patch.
DYNAMICMESH_API double ComputeAverageUVScaleRatioAlongVertexPath (const FDynamicMesh3 &Mesh, const FDynamicMeshUVOverlay &UVOverlay, const TArray< int32 > &VertexPath, double *PathLengthOut=nullptr, double *UVPathLengthOut=nullptr)
Compute the total UVLength/MeshLength ratio along the given VertexPath.
FAxisAlignedBox3d MODELINGCOMPONENTS_API ComputeBoundsFromTriangleROI (const FDynamicMesh3 &Mesh, const TArray< int32 > &TriangleROI, const FTransform3d *Transform=nullptr)
Computes the axis aligned bounding box from a given triangle region of interest, useful to compute a DepthBias.
FAxisAlignedBox3d MODELINGCOMPONENTS_API ComputeBoundsFromVertexROI (const FDynamicMesh3 &Mesh, const TArray< int32 > &VertexROI, const FTransform3d *Transform=nullptr)
Computes the axis aligned bounding box from a given vertex region of interest, useful to compute a DepthBias.
DYNAMICMESH_API FFrame3d ComputeFaceSelectionFrame (const FDynamicMesh3 &Mesh, const TArray< int32 > &Triangles, bool bIsDefinitelySingleComponent=false)
Try to compute a good "Frame" for the selected Triangles of the Mesh.
DYNAMICMESH_API int32 ComputeGroupIDBound (const FDynamicMesh3 &Mesh, const FDynamicMeshPolygroupAttribute *Layer)
DYNAMICMESH_API void ComputeInsetLineSegmentsFromEdges (const FDynamicMesh3 &Mesh, const TArray< int32 > &EdgeList, double InsetDistance, TArray< FLine3d > &InsetLinesOut)
For each edge in EdgeList, compute a line segment offset from the original edge by distance InsetDistance.
DYNAMICMESH_API bool ComputeMaterialIDRange (const FDynamicMesh3 &Mesh, FInterval1i &MaterialIDRange)
Compute inclusive range [0...N] of MaterialID values currently in use on Mesh (ie range always includes 0)
DYNAMICMESH_API bool ComputeMaterialIDsForVertexPath (const FDynamicMesh3 &Mesh, const TArray< int32 > &VertexPath, bool bIsLoop, TArray< int32 > &EdgeMaterialIDsOut, int32 FallbackMaterialID=0)
Compute a MaterialID for each edge along the VertexPath based on the MaterialID of adjacent triangles.
DYNAMICMESH_API void ComputeNewGroupIDsAlongEdgeLoop (FDynamicMesh3 &Mesh, const TArray< int32 > &LoopEdgeIDs, TArray< int32 > &NewLoopEdgeGroupIDsOut, TArray< int32 > &NewGroupIDsOut, TFunctionRef< bool(int32 Eid1, int32 Eid2)> EdgesShouldHaveSameGroupFunc)
Compute a new set of GroupIDs along an edge loop under the assumption that the edge loop is about to be split and new geometry introduced.
DYNAMICMESH_API void ComputeNormalsForQuadPatch (FDynamicMesh3 &Mesh, const FQuadGridPatch &QuadPatch)
Create a new Normals "island" (ie surrounded by hard edges) for the QuadPatch of the Mesh,.
template<typename RealType>
TOrientedBox3< RealType > GEOMETRYCORE_API ComputeOrientedBBox (const EDiTO DiTO_K, const int32 NumPoints, TFunctionRef< UE::Math::TVector< RealType >(int32)> GetPointFunc)
template<typename RealType>
TOrientedBox3< RealType > GEOMETRYCORE_API ComputeOrientedBBox (const TArray< TVector< RealType > > &SampleDirections, const int32 NumPoints, TFunctionRef< UE::Math::TVector< RealType >(int32)> GetPointFunc)
MODELINGCOMPONENTS_API TArray< FSpatialPhotoParams > ComputeStandardExteriorSpatialPhotoParameters (UWorld *Unused, const TArray< AActor * > &Actors, const TArray< UActorComponent * > &Components, FImageDimensions PhotoDimensions, double HorizontalFOVDegrees, double NearPlaneDist, bool bFaces, bool bUpperCorners, bool bLowerCorners, bool bUpperEdges, bool bSideEdges)
DYNAMICMESH_API bool ComputeUVIslandForQuadPatch (FDynamicMesh3 &Mesh, const FQuadGridPatch &QuadPatch, double UVScaleFactor=1.0, int UVOverlayIndex=0)
Create a new UV Island for the QuadPatch triangles of the Mesh, and then assign UVs based on the grid layout.
MODELINGCOMPONENTS_API void ConfigureSceneCapture (FSceneCapturePhotoSet &SceneCapture, const TArray< TObjectPtr< AActor > > &Actors, const FSceneCaptureConfig &Config, bool bAllowCancel)
template<typename RealType>
TArray< FIndex3i > GEOMETRYALGORITHMS_API ConstrainedDelaunayTriangulate (const TGeneralPolygon2< RealType > &GeneralPolygon)
Convenience function; invokes TConstrainedDelaunay2::Triangulate with most-often-used options.
template<typename RealType>
TArray< FIndex3i > GEOMETRYALGORITHMS_API ConstrainedDelaunayTriangulateWithVertices (const TGeneralPolygon2< RealType > &GeneralPolygon, TArray< TVector2< RealType > > &OutVertices)
Convenience function; invokes TConstrainedDelaunay2::Triangulate with most-often-used options.
MODELINGCOMPONENTS_API bool ConvertComplexCollisionToMeshes (IInterface_CollisionDataProvider *CollisionDataProvider, UE::Geometry::FDynamicMesh3 &MeshOut, const FTransformSequence3d &TransformSeqeuence, bool &bFoundMeshErrorsOut, bool bWeldEdges=true, bool bSetToPerTriangleNormals=false)
Extract the complex collision geometry from CollisionDataProvider as a dynamic mesh.
GEOMETRYCORE_API bool ConvertLoopToTriOrderedEdgeLoop (const FDynamicMesh3 &Mesh, const TArray< int32 > &VertexLoop, const TArray< int32 > &EdgeLoop, TArray< FMeshTriOrderedEdgeID > &TriOrderedEdgesLoopOut)
Variant of ConvertLoopToTriOrderedEdgeLoop that always encodes using EdgeTriangles.A, ie suitable for encoding open border loops.
GEOMETRYCORE_API bool ConvertLoopToTriOrderedEdgeLoop (const FDynamicMesh3 &Mesh, const TArray< int32 > &VertexLoop, const TArray< int32 > &EdgeLoop, TFunctionRef< int(int EdgeID, int TriangleA, int TriangleB)> SelectEdgeTriangleFunc, TArray< FMeshTriOrderedEdgeID > &TriOrderedEdgesLoopOut)
Convert the input Vertex/Edge loop into an edge loop representation that is independent of Vertex/Edge IDs.
DYNAMICMESH_API bool ConvertPolygroupSelectionToIncidentOverlaySelection (const UE::Geometry::FDynamicMesh3 &Mesh, const FGroupTopology &GroupTopology, const FGeometrySelection &MeshSelection, TSet< int > &TrianglesOut, TSet< int > &VerticesOut, FGeometrySelection *TriangleVertexSelectionIncidentToEdgeOrVertexSelection=nullptr)
Like ConvertPolygroupSelectionToOverlaySelection but only includes overlay elements that are immediately incident to Polygroup Vertices/Edges.
DYNAMICMESH_API bool ConvertPolygroupSelectionToOverlaySelection (const UE::Geometry::FDynamicMesh3 &Mesh, const FPolygroupSet &GroupSet, const FGeometrySelection &MeshSelection, TSet< int > &TrianglesOut, TSet< int > &VerticesOut)
Convert the given MeshSelection to a list of Triangles and Vertices into the Mesh, which can be used to represent a selection of overlay elements.
DYNAMICMESH_API bool ConvertPolygroupSelectionToTopologySelection (const FGeometrySelection &MeshSelection, const UE::Geometry::FDynamicMesh3 &Mesh, const FGroupTopology *GroupTopology, FGroupTopologySelection &TopologySelectionOut)
Convert a MeshSelection with Polygroup topology type to a FGroupTopologySelection.
UE_DEPRECATED(5.5, "This version of ConvertSelection is deprecated, please use the version with the EENumerateSelectionConversionParams parameter going forward.") DYNAMICMESH_API bool ConvertSelection(const UE DYNAMICMESH_API bool ConvertSelection (const UE::Geometry::FDynamicMesh3 &Mesh, const FGroupTopology *GroupTopology, const FGeometrySelection &FromSelectionIn, FGeometrySelection &ToSelectionOut, const EEnumerateSelectionConversionParams ConversionParams)
Convert Selection from one type to another, based on geometry/topology types in FromSelectionIn and ToSelectionOut.
MODELINGCOMPONENTS_API void ConvertSimpleCollisionToDynamicMeshes (const FKAggregateGeom &AggGeom, FVector ExternalScale, TFunctionRef< void(int32 Index, const FKShapeElem &, FDynamicMesh3 &Mesh)> PerElementMeshCallback, const FSimpleCollisionTriangulationSettings &TriangulationSettings, const FSimpleCollisionToMeshAttributeSettings &MeshAttributeSettings=FSimpleCollisionToMeshAttributeSettings())
MODELINGCOMPONENTS_API void ConvertSimpleCollisionToDynamicMeshes (const FKAggregateGeom &AggGeom, FVector ExternalScale, TFunctionRef< void(int32 Index, const FKShapeElem &, FDynamicMesh3 &Mesh)> PerElementMeshCallback, TFunctionRef< bool(const FKShapeElem &)> IncludeElement, const FSimpleCollisionTriangulationSettings &TriangulationSettings, const FSimpleCollisionToMeshAttributeSettings &MeshAttributeSettings=FSimpleCollisionToMeshAttributeSettings())
MODELINGCOMPONENTS_API void ConvertSimpleCollisionToMeshes (const FKAggregateGeom &AggGeom, UE::Geometry::FDynamicMesh3 &MeshOut, const FTransformSequence3d &TransformSequence, int32 SphereResolution=16, bool bSetToPerTriangleNormals=false, bool bInitializeConvexUVs=false, TFunction< void(int, const FDynamicMesh3 &)> PerElementMeshCallback=nullptr, bool bApproximateLevelSetWithCubes=true, FVector ExternalScale=FVector::OneVector)
Extract the simple collision geometry from AggGeom as meshes (ie spheres and capsules are tessellated) and accumulate into MeshOut.
DYNAMICMESH_API bool ConvertTriangleSelectionToOverlaySelection (const UE::Geometry::FDynamicMesh3 &Mesh, const FGeometrySelection &MeshSelection, TSet< int > &TrianglesOut, TSet< int > &VerticesOut, FGeometrySelection *TriangleVertexSelectionIncidentToEdgeSelection=nullptr)
Convert the given MeshSelection to a list of Triangles and Vertices into the Mesh, which can be used to represent a selection of overlay elements.
GEOMETRYCORE_API bool ConvertTriOrderedEdgeLoopToLoop (const FDynamicMesh3 &Mesh, const TArray< FMeshTriOrderedEdgeID > &TriOrderedEdgesLoopOut, TArray< int32 > &VertexLoop, TArray< int32 > *EdgeLoop=nullptr)
Recover the current Vertex and Edge loops given an encoded loop of FMeshTriOrderedEdgeID.
GEOMETRYCORE_API bool CopyVertexNormalsToOverlay (const FDynamicMesh3 &Mesh, FDynamicMeshNormalOverlay &NormalOverlayOut, bool bCompactElements=false)
Copies vertex normals to a given overlay (clearing it before use if it has any elements).
GEOMETRYCORE_API bool CopyVertexUVsToOverlay (const FDynamicMesh3 &Mesh, FDynamicMeshUVOverlay &UVOverlayOut, bool bCompactElements=false)
Copies vertex UVs to a given overlay (clearing it before use if it has any elements).
MESHMODELINGTOOLSEXP_API UPreviewMesh * CreateBakePreviewMesh (UObject *Tool, UToolTarget *ToolTarget, UWorld *World)
template<typename RealType>
TQuadricError< RealType > CreateSeamQuadric (const TVector< RealType > &p0, const TVector< RealType > &p1, const TVector< RealType > &AdjFaceNormal)
A "Seam Quadric" is a quadric defined with respect to the plane passing through the edge p1-p0, but perpendicular to the adjacent face.
template<typename T>
UE::Math::TVector< T > Cross (const UE::Math::TVector< T > &V1, const UE::Math::TVector< T > &V2)
template<typename RealType>
static TMatrix3< RealType > CrossProductMatrix (const UE::Math::TVector< RealType > &A)
MODELINGCOMPONENTS_API bool DeregisterSceneSnappingManager (UInteractiveToolsContext *ToolsContext)
Remove any existing UModelingSceneSnappingManager from the ToolsContext's ContextObjectStore.
template<typename T>
T Distance (const UE::Math::TVector2< T > &V1, const UE::Math::TVector2< T > &V2)
template<typename T>
T Distance (const UE::Math::TVector< T > &V1, const UE::Math::TVector< T > &V2)
template<typename T>
T DistanceSquared (const UE::Math::TVector2< T > &V1, const UE::Math::TVector2< T > &V2)
template<typename T>
T DistanceSquared (const UE::Math::TVector< T > &V1, const UE::Math::TVector< T > &V2)
template<typename RealType>
bool DoesCylinderContainPoint (const TVector< RealType > &CylinderCenter, const TVector< RealType > &NormalizedCylinderAxis, RealType CylinderRadius, RealType CylindeHeight, const TVector< RealType > &QueryPoint)
Test if QueryPoint is inside (or on) the given cylinder.
template<typename RealType>
bool DoesCylinderIntersectBox (const TAxisAlignedBox3< RealType > &Box, const TVector< RealType > &CylinderCenter, const TVector< RealType > &CylinderDirection, RealType CylinderRadius, RealType CylinderHeight)
Compute intersection between a cylinder and a 3D axis-aligned box.
template<typename Real>
GEOMETRYCORE_API bool DoesTriangleIntersectCircle2D (const TVector2< Real > &A, const TVector2< Real > &B, const TVector2< Real > &C, const TVector2< Real > &Center, double RadiusSquared)
template<typename T>
T Dot (const UE::Math::TVector< T > &V1, const UE::Math::TVector< T > &V2)
template<typename T>
constexpr T DotPerp (const UE::Math::TVector2< T > &V1, const UE::Math::TVector2< T > &V2)
bool GEOMETRYCORE_API EmbedProjectedPath (FDynamicMesh3 *Mesh, int StartTriID, FFrame3d Frame, const TArray< FVector2d > &Path2D, TArray< int > &OutPathVertices, TArray< int > &OutVertexCorrespondence, bool bClosePath, FMeshFaceSelection *EnclosedFaces=nullptr, double PtSnapVertexOrEdgeThresholdSq=FMathf::ZeroTolerance *100)
Embed a 2D path into a mesh by projection, starting the walk from a given triangle.
bool GEOMETRYCORE_API EmbedProjectedPaths (FDynamicMesh3 *Mesh, const TArrayView< const int > StartTriIDs, FFrame3d Frame, const TArrayView< const TArray< FVector2d > > AllPaths, TArray< TArray< int > > &OutAllPathVertices, TArray< TArray< int > > &OutAllVertexCorrespondence, bool bClosePaths, FMeshFaceSelection *EnclosedFaces, double PtSnapVertexOrEdgeThresholdSq=FMathf::ZeroTolerance *100)
Embed multiple 2D paths into a mesh by projection, starting the walks from the given triangles.
ENUM_CLASS_FLAGS (EEnumerateSelectionMapping)
ENUM_CLASS_FLAGS (EMeshOcclusionMapType)
ENUM_CLASS_FLAGS (EOcclusionMapType)
ENUM_CLASS_FLAGS (ERoundedRectangleCorner)
ENUM_CLASS_FLAGS (ESimpleShapeType)
DYNAMICMESH_API bool EnumeratePolygroupSelectionEdges (const FGeometrySelection &MeshSelection, const UE::Geometry::FDynamicMesh3 &Mesh, const UE::Geometry::FGroupTopology &GroupTopology, TFunctionRef< void(int32)> EdgeFunc)
Version of EnumeratePolygroupSelectionEdges which uses GroupTopology.
DYNAMICMESH_API bool EnumeratePolygroupSelectionEdges (const FGeometrySelection &MeshSelection, const UE::Geometry::FDynamicMesh3 &Mesh, const UE::Geometry::FPolygroupSet &GroupSet, TFunctionRef< void(int32)> EdgeFunc)
Call EdgeFunc for each mesh EdgeID included in MeshSelection, where MeshSelection has polygroup topology.
DYNAMICMESH_API bool EnumeratePolygroupSelectionElements (const FGeometrySelection &MeshSelection, const UE::Geometry::FDynamicMesh3 &Mesh, const FGroupTopology *GroupTopology, TFunctionRef< void(int32, const FVector3d &)> VertexFunc, TFunctionRef< void(int32, const FSegment3d &)> EdgeFunc, TFunctionRef< void(int32, const FTriangle3d &)> TriangleFunc, const FTransform *ApplyTransform=nullptr, const bool bMapFacesToEdgeLoops=false)
Prefer EnumeratePolygroupSelectionElements with Flags parameter.
DYNAMICMESH_API bool EnumeratePolygroupSelectionElements (const FGeometrySelection &MeshSelection, const UE::Geometry::FDynamicMesh3 &Mesh, const FGroupTopology *GroupTopology, TFunctionRef< void(int32, const FVector3d &)> VertexFunc, TFunctionRef< void(int32, const FSegment3d &)> EdgeFunc, TFunctionRef< void(int32, const FTriangle3d &)> TriangleFunc, const FTransform *ApplyTransform=nullptr, const EEnumerateSelectionMapping Flags=EEnumerateSelectionMapping::Default)
Enumerates the renderable geometry for a given MeshSelection when in Polygroup Topology mode.
DYNAMICMESH_API bool EnumeratePolygroupSelectionTriangles (const FGeometrySelection &MeshSelection, const UE::Geometry::FDynamicMesh3 &Mesh, const UE::Geometry::FPolygroupSet &GroupSet, TFunctionRef< void(int32)> TriangleFunc)
Call TriangleFunc for each mesh TriangleID included in MeshSelection, where MeshSelection has polygroup topology.
DYNAMICMESH_API bool EnumeratePolygroupSelectionVertices (const FGeometrySelection &GroupSelection, const UE::Geometry::FDynamicMesh3 &Mesh, const FGroupTopology *GroupTopology, const FTransform &ApplyTransform, TFunctionRef< void(uint64, const FVector3d &)> VertexFunc)
Call VertexFunc for each selected Mesh element (vertex/edge/tri) in the set of polygroup faces/edges/corners specified by GroupSelection (relative to GroupTopology parameter) ApplyTransform will be applied to Vertex Positions before calling VertexFunc.
DYNAMICMESH_API bool EnumerateSelectionEdges (const FGeometrySelection &MeshSelection, const UE::Geometry::FDynamicMesh3 &Mesh, TFunctionRef< void(int32)> EdgeFunc, const UE::Geometry::FPolygroupSet *UseGroupSet=nullptr)
Call EdgeFunc for each mesh EdgeID included in MeshSelection.
DYNAMICMESH_API bool EnumerateSelectionTriangles (const FGeometrySelection &MeshSelection, const UE::Geometry::FDynamicMesh3 &Mesh, TFunctionRef< void(int32)> TriangleFunc, const UE::Geometry::FPolygroupSet *UseGroupSet=nullptr)
Call TriangleFunc for each mesh TriangleID included in MeshSelection.
DYNAMICMESH_API bool EnumerateTriangleSelectionEdges (const FGeometrySelection &MeshSelection, const UE::Geometry::FDynamicMesh3 &Mesh, TFunctionRef< void(int32)> EdgeFunc)
Call EdgeFunc for each mesh EdgeID included in MeshSelection.
DYNAMICMESH_API bool EnumerateTriangleSelectionElements (const FGeometrySelection &MeshSelection, const UE::Geometry::FDynamicMesh3 &Mesh, TFunctionRef< void(int32, const FVector3d &)> VertexFunc, TFunctionRef< void(int32, const FSegment3d &)> EdgeFunc, TFunctionRef< void(int32, const FTriangle3d &)> TriangleFunc, const FTransform *ApplyTransform=nullptr, const bool bMapFacesToEdgeLoops=false)
Prefer EnumerateTriangleSelectionElements with Flags parameter.
DYNAMICMESH_API bool EnumerateTriangleSelectionElements (const FGeometrySelection &MeshSelection, const UE::Geometry::FDynamicMesh3 &Mesh, TFunctionRef< void(int32, const FVector3d &)> VertexFunc, TFunctionRef< void(int32, const FSegment3d &)> EdgeFunc, TFunctionRef< void(int32, const FTriangle3d &)> TriangleFunc, const FTransform *ApplyTransform=nullptr, const EEnumerateSelectionMapping Flags=EEnumerateSelectionMapping::Default)
Enumerates the renderable geometry for a given MeshSelection when in Triangle Topology mode.
DYNAMICMESH_API bool EnumerateTriangleSelectionTriangles (const FGeometrySelection &MeshSelection, const UE::Geometry::FDynamicMesh3 &Mesh, TFunctionRef< void(int32)> TriangleFunc)
Call TriangleFunc for each mesh TriangleID included in MeshSelection.
DYNAMICMESH_API bool EnumerateTriangleSelectionVertices (const FGeometrySelection &MeshSelection, const UE::Geometry::FDynamicMesh3 &Mesh, const FTransform *ApplyTransform, TFunctionRef< void(uint64, const FVector3d &)> VertexFunc)
Call VertexFunc for each selected Mesh element (vertex/edge/tri) in MeshSelection.
DYNAMICMESH_API bool FindInSelectionByTopologyID (const FGeometrySelection &GeometrySelection, uint32 TopologyID, uint64 &FoundValue)
Assuming that the uint64 values in the GeometrySelection are encoded FGeoSelectionID's, find the item that has a matching TopologyID, ignoring the GeometryID.
MODELINGCOMPONENTS_API UModelingSceneSnappingManager * FindModelingSceneSnappingManager (UInteractiveToolManager *ToolManager)
Find an existing UModelingSceneSnappingManager in the ToolsContext's ContextObjectStore.
template<typename TrisConnectedPredicate>
FIndex3i FindNextAdjacentTriangleAroundVtx (const FDynamicMesh3 *Mesh, int32 VertexID, int32 FromTriangleID, int32 PrevTriangleID, TrisConnectedPredicate TrisConnectedTest)
Walk around VertexID from FromTriangleID to next connected triangle if it exists, walking "away" from PrevTriangleID.
DYNAMICMESH_API const FDynamicMeshPolygroupAttribute * FindPolygroupLayerByName (const FDynamicMesh3 &Mesh, FName Name)
Find the first FDynamicMeshPolygroupAttribute with the given FName in a the AttributeSet of a Mesh.
DYNAMICMESH_API FDynamicMeshPolygroupAttribute * FindPolygroupLayerByName (FDynamicMesh3 &Mesh, FName Name)
Find the first FDynamicMeshPolygroupAttribute with the given FName in a the AttributeSet of a Mesh.
DYNAMICMESH_API int32 FindPolygroupLayerIndex (const FDynamicMesh3 &Mesh, const FDynamicMeshPolygroupAttribute *Layer)
DYNAMICMESH_API int32 FindPolygroupLayerIndexByName (const FDynamicMesh3 &Mesh, FName Name)
GEOMETRYCORE_API int32 FindSharedEdgeInTriangles (const FDynamicMesh3 &Mesh, int32 Triangle0, int32 Triangle1)
GEOMETRYCORE_API FIndex2i FindVertexEdgesInTriangle (const FDynamicMesh3 &Mesh, int32 TriangleID, int32 VertexID)
Find the two edges in a Triangle that are connected to a given Vertex of the triangle.
template<typename RealType>
bool FitKDOPVertices3 (TArrayView< const UE::Math::TVector< RealType > > PlaneDirections, const int32 NumPoints, TFunctionRef< UE::Math::TVector< RealType >(int32)> GetPointFunc, TArray< UE::Math::TVector< RealType > > &OutVertices, TArray< UE::Math::TPlane< RealType > > *OptionalOutPlanes=nullptr, RealType Epsilon=TMathUtil< RealType >::Epsilon, RealType VertexSnapDistance=(RealType) 0.1, RealType Inflate=(RealType) 0.1)
Compute the vertices (and optionally planes) of a k-DOP bounding convex hull containing the points returned by GetPointFunc.
template<typename RealType>
bool GEOMETRYCORE_API FitKDOPVertices3 (TArrayView< const UE::Math::TVector< RealType > > PlaneDirections, const int32 NumPoints, TFunctionRef< UE::Math::TVector< RealType >(int32)> GetPointFunc, TFunctionRef< bool(int32)> FilterFunc, TArray< UE::Math::TVector< RealType > > &OutVertices, TArray< UE::Math::TPlane< RealType > > *OptionalOutPlanes=nullptr, RealType Epsilon=TMathUtil< RealType >::Epsilon, RealType VertexSnapDistance=(RealType) 0.1, RealType Inflate=(RealType) 0.1)
Compute the vertices (and optionally planes) of a k-DOP bounding convex hull containing the points returned by GetPointFunc where FilterFunc returns true.
template<typename RealType>
bool FitKDOPVertices3 (TArrayView< const UE::Math::TVector< RealType > > PlaneDirections, const TArray< UE::Math::TVector< RealType > > &Points, TArray< UE::Math::TVector< RealType > > &OutVertices, TArray< UE::Math::TPlane< RealType > > *OptionalOutPlanes=nullptr, RealType Epsilon=TMathUtil< RealType >::Epsilon, RealType VertexSnapDistance=(RealType) 0.1, RealType Inflate=(RealType) 0.1)
Compute the vertices (and optionally planes) of a k-DOP bounding convex hull containing Points.
template<typename RealType>
TOrientedBox2< RealType > FitOrientedBox2ConvexHull (int32 NumPts, TFunctionRef< TVector2< RealType >(int32)> GetHullPt, EBox2FitCriteria FitMethod=EBox2FitCriteria::Area)
Use the rotating calipers algorithm to find a best-fit oriented bounding box of a convex hull.
template<typename RealType>
TOrientedBox2< RealType > GEOMETRYCORE_API FitOrientedBox2ConvexHull (int32 NumPts, TFunctionRef< TVector2< RealType >(int32)> GetHullPt, TFunctionRef< RealType(RealType, RealType)> FitFn)
Use the rotating calipers algorithm to find a best-fit oriented bounding box of a convex hull.
template<typename RealType>
TOrientedBox2< RealType > FitOrientedBox2Points (TArrayView< const TVector2< RealType > > Points, EBox2FitCriteria FitMethod=EBox2FitCriteria::Area)
Use the rotating calipers algorithm to find a best-fit oriented bounding box of a point set.
template<typename RealType>
TOrientedBox2< RealType > GEOMETRYCORE_API FitOrientedBox2Points (TArrayView< const TVector2< RealType > > Points, TFunctionRef< RealType(RealType, RealType)> FitFn)
Use the rotating calipers algorithm to find a best-fit oriented bounding box of a point set.
template<typename RealType>
TOrientedBox2< RealType > FitOrientedBox2SimplePolygon (TArrayView< const TVector2< RealType > > Polygon, EBox2FitCriteria FitMethod=EBox2FitCriteria::Area)
Use the rotating calipers algorithm to find a best-fit oriented bounding box of a simple polygon.
template<typename RealType>
TOrientedBox2< RealType > GEOMETRYCORE_API FitOrientedBox2SimplePolygon (TArrayView< const TVector2< RealType > > Polygon, TFunctionRef< RealType(RealType, RealType)> FitFn)
Use the rotating calipers algorithm to find a best-fit oriented bounding box of a simple polygon.
template<typename RealType>
TOrientedBox3< RealType > GEOMETRYCORE_API FitOrientedBox3Points (int32 NumPoints, TFunctionRef< TVector< RealType >(int32)> GetPointFunc, TFunctionRef< bool(int32)> Filter, EBox3FitCriteria FitMethod=EBox3FitCriteria::Volume, RealType SameNormalTolerance=0, FProgressCancel *ProgressCancel=nullptr)
Compute a close-fitting oriented bounding box to the given points.
template<typename RealType>
TOrientedBox3< RealType > FitOrientedBox3Points (TArrayView< const TVector< RealType > > Points, EBox3FitCriteria FitMethod=EBox3FitCriteria::Volume, RealType SameNormalTolerance=0, FProgressCancel *ProgressCancel=nullptr)
Compute a close-fitting oriented bounding box to the given points.
int32 DYNAMICMESH_API FlipToDelaunay (FIntrinsicEdgeFlipMesh &IntrinsicMesh, TSet< int > &Uncorrected, const int32 MaxFlipCount=TMathUtilConstants< int >::MaxReal)
int32 DYNAMICMESH_API FlipToDelaunay (FIntrinsicMesh &IntrinsicMesh, TSet< int > &Uncorrected, const int32 MaxFlipCount=TMathUtilConstants< int >::MaxReal)
int32 DYNAMICMESH_API FlipToDelaunay (FIntrinsicTriangulation &IntrinsicMesh, TSet< int > &Uncorrected, const int32 MaxFlipCount=TMathUtilConstants< int >::MaxReal)
int32 DYNAMICMESH_API FlipToDelaunay (FSimpleIntrinsicEdgeFlipMesh &IntrinsicMesh, TSet< int > &Uncorrected, const int32 MaxFlipCount=TMathUtilConstants< int >::MaxReal)
Perform edge flips on intrinsic mesh until either the MaxFlipCount is reached or the mesh is fully Delaunay.
int32 DYNAMICMESH_API FlipToDelaunay (FSimpleIntrinsicMesh &IntrinsicMesh, TSet< int > &Uncorrected, const int32 MaxFlipCount=TMathUtilConstants< int >::MaxReal)
template<typename FunctionType>
void ForEachCaptureType (const FunctionType &Function)
template<typename T>
T FractalBrownianMotionNoise (const EFBMMode FBMMode, const uint32 OctaveCount, const Math::TVector2< T > Coords, const T Lacunarity, const T Gain, const T Smoothness, const T Gamma)
template<typename RealType>
void GenerateArcSegments (int32 NumSteps, RealType Radius, RealType StartAngle, RealType EndAngle, const TVector< RealType > &Center, const TVector< RealType > &AxisX, const TVector< RealType > &AxisY, const TTransformSRT3< RealType > &Transform, TFunctionRef< void(const TVector< RealType > &A, const TVector< RealType > &B)> EmitLineFunc)
call EmitLineFunc for the line segments that make up the Circular Arc defined by the given parameters and sampled with NumSteps vertices
template<typename RealType>
void GenerateBoxSegments (const TVector< RealType > &HalfDimensions, const TVector< RealType > &Center, const TVector< RealType > &AxisX, const TVector< RealType > &AxisY, const TVector< RealType > &AxisZ, const TTransformSRT3< RealType > &Transform, TFunctionRef< void(const TVector< RealType > &A, const TVector< RealType > &B)> EmitLineFunc)
call EmitLineFunc for the 12 line segments defined by the given box parameters
template<typename RealType>
void GenerateCircleSegments (int32 NumSteps, RealType Radius, const TVector< RealType > &Center, const TVector< RealType > &AxisX, const TVector< RealType > &AxisY, const TTransformSRT3< RealType > &Transform, TFunctionRef< void(const TVector< RealType > &A, const TVector< RealType > &B)> EmitLineFunc)
call EmitLineFunc for the line segments that make up the Circle defined by the given parameters and sampled with NumSteps vertices
FTriangleMeshAdapterd GetArrayMesh (TArray< FVector > &Vertices, TArray< FIntVector > &Triangles)
Example function to generate a generic mesh adapter from arrays.
MODELINGCOMPONENTS_API const UBodySetup * GetBodySetup (const UPrimitiveComponent *SourceComponent)
MODELINGCOMPONENTS_API UBodySetup * GetBodySetup (UPrimitiveComponent *SourceComponent)
MODELINGCOMPONENTS_API FComponentCollisionSettings GetCollisionSettings (const UPrimitiveComponent *Component)
MODELINGCOMPONENTS_API bool GetCollisionShapes (const UPrimitiveComponent *Component, FKAggregateGeom &AggGeomOut)
Get current Component collision shapes.
MODELINGCOMPONENTS_API bool GetCollisionShapes (const UPrimitiveComponent *Component, FSimpleShapeSet3d &ShapeSetOut)
Get current Component collision shapes.
MODELINGCOMPONENTS_API bool GetCurrentGeometrySelectionForTarget (const FToolBuilderState &SceneState, UToolTarget *Target, FGeometrySelection &SelectionOut)
Given a FToolBuilderState, find an available FGeometrySelection for the given ToolTarget (via the UGeometrySelectionManager in the ContextObjectStore)
MODELINGCOMPONENTS_API bool GetCurrentGeometrySelectionForTarget (UInteractiveToolManager *ToolManager, UToolTarget *Target, FGeometrySelection &SelectionOut)
Find an available FGeometrySelection for the given ToolTarget (via the UGeometrySelectionManager in the ContextObjectStore)
MODELINGCOMPONENTS_API bool GetCurrentSelectionWorldFrameBounds (const FToolBuilderState &SceneState, FFrame3d &OutWorldFrame, FAxisAlignedBox3d &OutWorldBounds, bool &bOutIsElementSelection)
Find the frame and bounds representative of the current selection, if there is one.
FRenderCaptureConfig MODELINGCOMPONENTS_API GetDefaultRenderCaptureConfig (ERenderCaptureType CaptureType)
const void * GetDetailMeshTrianglePoint_Nearest (const IMeshBakerDetailSampler *DetailSpatial, const FVector3d &BasePoint, int32 &DetailTriangleOut, FVector3d &DetailTriBaryCoords)
Compute base/detail mesh correspondence by nearest distance.
const void * GetDetailMeshTrianglePoint_Raycast (const IMeshBakerDetailSampler *DetailSpatial, const FVector3d &BasePoint, const FVector3d &BaseNormal, int32 &DetailTriangleOut, FVector3d &DetailTriBaryCoords, double Thickness, bool bFailToNearestPoint)
Compute base/detail mesh correspondence by raycast.
MODELINGCOMPONENTS_API FDynamicMesh3 GetDynamicMeshViaMeshDescription (IMeshDescriptionProvider &MeshDescriptionProvider, const FGetMeshParameters &InGetMeshParams=FGetMeshParameters())
void GetFKElement (const FCapsule3d &Capsule, FKSphylElem &CapsuleInOut)
Convert FCapsule3d to FKSphylElem.
void GetFKElement (const FDynamicMesh3 &Mesh, FKConvexElem &ConvexInOut)
Convert FDynamicMesh3 to FKConvexElem.
void GetFKElement (const FOrientedBox3d &Box, FKBoxElem &BoxInOut)
Convert FOrientedBox3d to FKBoxElem.
void GetFKElement (const FSphere3d &Sphere, FKSphereElem &ElemInOut)
Convert FSphere3d to FKSphereElem.
void GetFKElement (const FTransform3d &GridTransform, const FDenseGrid3f &Grid, float CellSize, FKLevelSetElem &LevelSetOut)
Create FKLevelSet from the given grid information.
MODELINGCOMPONENTS_API FIndex2i GetGroupEdgeRepresentativeVerts (const FGroupTopology &TopologyIn, int GroupEdgeID)
Returns a pair of vertex ID's that are representative of a group edge, to be able to identify a selected group edge independently of a group topology object.
MODELINGCOMPONENTS_API FIndex2i GetGroupEdgeRepresentativeVerts (const FGroupTopology &TopologyIn, int GroupEdgeID, const FCompactMaps &CompactMaps)
Returns a pair of vertex ID's that are representative of a group edge, to be able to identify a selected group edge independently of a group topology object.
FViewMatrices GetRenderCaptureViewMatrices (const FFrame3d &ViewFrame, double HorzFOVDegrees, double NearPlaneDist, FImageDimensions ViewRect)
Returns the view matrices corresponding to the given render capture cameara parameters Useful to get the needed information to unproject the DeviceDepth render capture e.g., using the following.
MODELINGCOMPONENTS_API FSceneCaptureConfig GetSceneCaptureConfig (const FSceneCapturePhotoSet &SceneCapture, FSceneCapturePhotoSet::ECaptureTypeStatus QueryStatus=FSceneCapturePhotoSet::ECaptureTypeStatus::Computed)
DYNAMICMESH_API bool GetSelectionBoundaryCorners (const UE::Geometry::FDynamicMesh3 &Mesh, const UE::Geometry::FGroupTopology *GroupTopology, const UE::Geometry::FGeometrySelection &ReferenceSelection, TSet< int32 > &BorderCornerIDsOut, TSet< int32 > &CurCornerIDsOut)
Given a EGeometryTopologyType::Polygroup selection, return the corner IDs of the polygroup corners on the boundary of the selection.
DYNAMICMESH_API bool GetSelectionBoundaryVertices (const UE::Geometry::FDynamicMesh3 &Mesh, const UE::Geometry::FGroupTopology *GroupTopology, const UE::Geometry::FGeometrySelection &ReferenceSelection, TSet< int32 > &BorderVidsOut, TSet< int32 > &CurVerticesOut)
Given a selection, return the vertex IDs of the vertices on the boundary of this selection.
void GetShape (const FKBoxElem &BoxElem, FBoxShape3d &BoxShapeOut)
Convert FKBoxElem to FBoxShape3d.
void GetShape (const FKConvexElem &ConvexElem, FConvexShape3d &ConvexShapeOut)
Convert FKConvexElem to FConvexShape3d.
void GetShape (const FKConvexElem &ConvexElem, FDynamicMesh3 &MeshOut)
Convert FKConvexElem to FDynamicMesh3.
void GetShape (const FKLevelSetElem &LevelSetElem, FLevelSetShape3d &LevelSetShapeOut)
Convert FKLevelSetElem to FLevelSetShape3d.
void GetShape (const FKSphereElem &SphereElem, FSphereShape3d &SphereShapeOut)
Convert FKSphereElem to FSphereShape3d.
void GetShape (const FKSphylElem &CapsuleElem, UE::Geometry::FCapsuleShape3d &CapsuleShapeOut)
Convert FKSphylElem to FCapsuleShape3d.
void GetShapeSet (const FKAggregateGeom &AggGeom, FSimpleShapeSet3d &ShapeSetOut)
Convert FKAggregateGeom to FSimpleShapeSet3d.
MESHMODELINGTOOLSEXP_API AActor * GetTargetActorViaIPersistentDynamicMeshSource (UToolTarget *Target)
MODELINGCOMPONENTS_API void GetTexturesFromRenderCaptureBaker (FMeshMapBaker &Baker, FRenderCaptureTextures &TexturesOut)
DYNAMICMESH_API bool GetTriangleSelectionFrame (const FGeometrySelection &MeshSelection, const UE::Geometry::FDynamicMesh3 &Mesh, FFrame3d &SelectionFrameOut)
Compute a 3D Frame suitable for use as a 3D transform gizmo position/orientation for the given MeshSelection.
FORCEINLINE uint32 GetTypeHash (const FIndex2i &Index)
FORCEINLINE uint32 GetTypeHash (const FIndex3i &Index)
FORCEINLINE uint32 GetTypeHash (const FIndex4i &Index)
FORCEINLINE uint32 GetTypeHash (const FSceneGeometryID &Identifier)
FORCEINLINE uint32 GetTypeHash (const FVector2i &Vector)
FORCEINLINE uint32 GetTypeHash (const FVector3i &Vector)
template<typename T>
constexpr UE::Math::TVector2< T > GetXY (const UE::Math::TVector< T > &V)
template<typename T>
constexpr UE::Math::TVector2< T > GetXZ (const UE::Math::TVector< T > &V)
template<typename T>
constexpr UE::Math::TVector2< T > GetYZ (const UE::Math::TVector< T > &V)
MODELINGCOMPONENTS_API bool HaveAvailableGeometrySelection (const FToolBuilderState &SceneState)
void MODELINGCOMPONENTS_API InitializeGeometrySelectionVisualization (UPreviewGeometry *PreviewGeom, UGeometrySelectionVisualizationProperties *Settings, const FDynamicMesh3 &SourceMesh, const FGeometrySelection &Selection, const FGroupTopology *GroupTopology=nullptr, const FGeometrySelection *TriangleVertexSelection=nullptr, const TArray< int > *TriangleROI=nullptr, const FTransform *ApplyTransform=nullptr)
Initialize the geometry selection preview geometry.
DYNAMICMESH_API bool InitializeSelectionFromTriangles (const UE::Geometry::FDynamicMesh3 &Mesh, const FGroupTopology *GroupTopology, TArrayView< const int > Triangles, FGeometrySelection &SelectionOut)
Convert Triangle IDs to target Selection type.
bool DYNAMICMESH_API IsBoxMesh (const FDynamicMesh3 &Mesh, FOrientedBox3d &BoxOut, double AngleToleranceDeg=0.1, double PlaneDistanceTolerance=1e-2)
Detect if input Mesh is a meshed box, and if so return analytic box in BoxOut.
bool DYNAMICMESH_API IsCapsuleMesh (const FDynamicMesh3 &Mesh, FCapsule3d &CapsuleOut, double RelativeDeviationTol=0.025, double MaxAngleRangeDegrees=72)
Detect if input Mesh is a meshed approximation of an analytic Capsule, and if so return best guess in CapsuleOut.
template<typename RealType>
GEOMETRYCORE_API bool IsInside (const TCapsule3< RealType > &OuterCapsule, const TCapsule3< RealType > &InnerCapsule)
template<typename RealType>
GEOMETRYCORE_API bool IsInside (const TCapsule3< RealType > &OuterCapsule, const TOrientedBox3< RealType > &InnerBox)
template<typename RealType>
GEOMETRYCORE_API bool IsInside (const TCapsule3< RealType > &OuterCapsule, const TSphere3< RealType > &InnerSphere)
template<typename RealType, typename GridType>
bool IsInside (const TCapsule3< RealType > &OuterCapsule, const TTriLinearGridInterpolant< GridType > &InnerGrid)
template<typename RealType, typename EnumerablePointsType, typename E = decltype(DeclVal<EnumerablePointsType>().begin())>
bool IsInside (const TCapsule3< RealType > &OuterCapsule, EnumerablePointsType EnumerablePts)
template<typename RealType>
GEOMETRYCORE_API bool IsInside (const TOrientedBox3< RealType > &OuterBox, const TCapsule3< RealType > &InnerCapsule)
template<typename RealType>
GEOMETRYCORE_API bool IsInside (const TOrientedBox3< RealType > &OuterBox, const TOrientedBox3< RealType > &InnerBox)
template<typename RealType>
GEOMETRYCORE_API bool IsInside (const TOrientedBox3< RealType > &OuterBox, const TSphere3< RealType > &InnerSphere)
template<typename RealType, typename GridType>
bool IsInside (const TOrientedBox3< RealType > &OuterBox, const TTriLinearGridInterpolant< GridType > &InnerGrid)
template<typename RealType, typename EnumerablePointsType, typename E = decltype(DeclVal<EnumerablePointsType>().begin())>
bool IsInside (const TOrientedBox3< RealType > &OuterBox, EnumerablePointsType EnumerablePts)
template<typename RealType>
GEOMETRYCORE_API bool IsInside (const TSphere3< RealType > &OuterSphere, const TCapsule3< RealType > &InnerCapsule)
template<typename RealType>
GEOMETRYCORE_API bool IsInside (const TSphere3< RealType > &OuterSphere, const TOrientedBox3< RealType > &InnerBox)
template<typename RealType>
GEOMETRYCORE_API bool IsInside (const TSphere3< RealType > &OuterSphere, const TSphere3< RealType > &InnerSphere)
template<typename RealType, typename GridType>
bool IsInside (const TSphere3< RealType > &OuterSphere, const TTriLinearGridInterpolant< GridType > &InnerGrid)
template<typename RealType, typename EnumerablePointsType, typename E = decltype(DeclVal<EnumerablePointsType>().begin())>
bool IsInside (const TSphere3< RealType > &OuterSphere, EnumerablePointsType EnumerablePts)
template<typename RealType, typename GridType>
bool IsInside (const TTriLinearGridInterpolant< GridType > &OuterGrid, const TTransform< RealType > &OuterGridTransform, const TCapsule3< RealType > &InnerCapsule)
Test if the axis-aligned bounding box of InnerCapsule is completely inside the negative region of the signed distance field discretized on OuterGrid.
template<typename RealType, typename GridType>
bool IsInside (const TTriLinearGridInterpolant< GridType > &OuterGrid, const TTransform< RealType > &OuterGridTransform, const TOrientedBox3< RealType > &InnerBox)
Test if the axis-aligned bounding box of InnerBox is completely inside the negative region of the signed distance field discretized on OuterGrid.
template<typename RealType, typename GridType>
bool IsInside (const TTriLinearGridInterpolant< GridType > &OuterGrid, const TTransform< RealType > &OuterGridTransform, const TSphere3< RealType > &InnerSphere)
Test if the axis-aligned bounding box of InnerSphere is completely inside the negative region of the signed distance field discretized on OuterGrid.
template<typename RealType, typename GridType, typename EnumerablePointsType, typename E = decltype(DeclVal<EnumerablePointsType>().begin())>
bool IsInside (const TTriLinearGridInterpolant< GridType > &OuterGrid, const TTransform< RealType > &OuterGridTransform, EnumerablePointsType EnumerablePts)
Test if all enumerable points are inside the negative region of the signed distance field discretized on OuterGrid.
template<typename RealType, typename GridType>
bool IsInside (const TTriLinearGridInterpolant< GridType > &OuterGrid, const UE::Geometry::TAxisAlignedBox3< RealType > &InnerAABB)
template<typename RealType, typename GridType1, typename GridType2>
bool IsInside (const TTriLinearGridInterpolant< GridType1 > &OuterGrid, const TTransform< RealType > &OuterGridTransform, const TTriLinearGridInterpolant< GridType2 > &InnerGrid, const TTransform< RealType > &InnerGridTransform)
Test if the axis-aligned bounding box of InnerGrid is completely inside the negative region of the signed distance field discretized on OuterGrid.
template<typename RealType>
bool IsInsideHull (TArrayView< THalfspace3< RealType > > Halfspaces, const TCapsule3< RealType > &InnerCapsule)
Test if the convex volume defined by a set of Halfspaces contains InnerCapsule.
template<typename RealType>
bool IsInsideHull (TArrayView< THalfspace3< RealType > > Halfspaces, const TOrientedBox3< RealType > &InnerBox)
Test if the convex volume defined by a set of Halfspaces contains InnerBox.
template<typename RealType>
bool IsInsideHull (TArrayView< THalfspace3< RealType > > Halfspaces, const TSphere3< RealType > &InnerSphere)
Test if the convex volume defined by a set of Halfspaces contains InnerSphere.
template<typename RealType, typename GridType>
bool IsInsideHull (TArrayView< THalfspace3< RealType > > Halfspaces, const TTriLinearGridInterpolant< GridType > &InnerGrid)
template<typename RealType, typename EnumerablePointsType, typename E = decltype(DeclVal<EnumerablePointsType>().begin())>
bool IsInsideHull (TArrayView< THalfspace3< RealType > > Halfspaces, EnumerablePointsType EnumerablePts)
Test if the convex volume defined by a set of Halfspaces contains InnerSphere.
template<typename T>
constexpr bool IsNormalized (const UE::Math::TVector2< T > &Vector, const T Tolerance=TMathUtil< T >::ZeroTolerance)
template<typename T>
constexpr bool IsNormalized (const UE::Math::TVector< T > &Vector, const T Tolerance=TMathUtil< T >::ZeroTolerance)
bool DYNAMICMESH_API IsSphereMesh (const FDynamicMesh3 &Mesh, FSphere3d &SphereOut, double RelativeDeviationTol=0.025, double MaxAngleRangeDegrees=72)
Detect if input Mesh is a meshed approximation of an analytic Sphere, and if so return best guess in SphereOut.
template<typename IterT>
int64 IteratorDistance (IterT Begin, IterT End)
template<typename ContainerType, typename ElementType, typename SizeType>
int64 IteratorDistance (TIndexedContainerIterator< ContainerType, ElementType, SizeType > Begin, TIndexedContainerIterator< ContainerType, ElementType, SizeType > End)
template<typename T>
T Length (const UE::Math::TVector< T > &V)
template<typename T>
TFrame3< T > Lerp (const TFrame3< T > &A, const TFrame3< T > &B, T Alpha)
template<typename T>
UE::Math::TVector2< T > Lerp (const UE::Math::TVector2< T > &A, const UE::Math::TVector2< T > &B, T Alpha)
template<typename T>
UE::Math::TVector4< T > Lerp (const UE::Math::TVector4< T > &A, const UE::Math::TVector4< T > &B, T Alpha)
template<typename T>
UE::Math::TVector< T > Lerp (const UE::Math::TVector< T > &A, const UE::Math::TVector< T > &B, T Alpha)
DYNAMICMESH_API bool MakeBoundaryConnectedSelection (const UE::Geometry::FDynamicMesh3 &Mesh, const FGroupTopology *GroupTopology, const FGeometrySelection &ReferenceSelection, TFunctionRef< bool(FGeoSelectionID)> SelectionIDPredicate, FGeometrySelection &BoundaryConnectedSelection)
Create a selection of the elements adjacent to the "Border" of the given ReferenceSelection and return in BoundaryConnectedSelection.
FPointSetAdapterd GEOMETRYCORE_API MakeBoundaryEdgeMidpointsAdapter (const FDynamicMesh3 *Mesh)
FTriangleMeshAdapterd GEOMETRYCORE_API MakeDynamicMeshAdapter (const FDynamicMesh3 *Mesh)
FPointSetAdapterd GEOMETRYCORE_API MakeEdgeMidpointsAdapter (const FDynamicMesh3 *Mesh)
FPointSetAdapterd GEOMETRYCORE_API MakePointsAdapter (const FDynamicPointSet3d *PointSet)
MODELINGCOMPONENTS_API TUniquePtr< FMeshMapBaker > MakeRenderCaptureBaker (FDynamicMesh3 *BaseMesh, TSharedPtr< FMeshTangentsd, ESPMode::ThreadSafe > BaseMeshTangents, TSharedPtr< TArray< int32 >, ESPMode::ThreadSafe > BaseMeshUVCharts, FSceneCapturePhotoSet *SceneCapture, FSceneCapturePhotoSetSampler *Sampler, FRenderCaptureTypeFlags PendingBake, int32 TargetUVLayer, EBakeTextureResolution TextureImageSize, EBakeTextureSamplesPerPixel SamplesPerPixel, FRenderCaptureOcclusionHandler *OcclusionHandler)
GEOMETRYSCRIPTINGCORE_API FGeometryScriptDebugMessage MakeScriptError (EGeometryScriptErrorType ErrorTypeIn, const FText &MessageIn)
GEOMETRYSCRIPTINGCORE_API FGeometryScriptDebugMessage MakeScriptWarning (EGeometryScriptErrorType WarningTypeIn, const FText &MessageIn)
DYNAMICMESH_API bool MakeSelectAllConnectedSelection (const UE::Geometry::FDynamicMesh3 &Mesh, const FGroupTopology *GroupTopology, const FGeometrySelection &ReferenceSelection, TFunctionRef< bool(FGeoSelectionID)> SelectionIDPredicate, TFunctionRef< bool(FGeoSelectionID A, FGeoSelectionID B)> IsConnectedPredicate, FGeometrySelection &AllConnectedSelection)
Expand the input ReferenceSelection to include all "connected" elements and return in AllConnectedSelection.
DYNAMICMESH_API bool MakeSelectAllSelection (const UE::Geometry::FDynamicMesh3 &Mesh, const FGroupTopology *GroupTopology, TFunctionRef< bool(FGeoSelectionID)> SelectionIDPredicate, FGeometrySelection &AllSelection)
Select all elements of the provided Mesh and GroupTopology that pass the provided SelectionIDPredicate, and store in the output AllSelection.
FTriangleMeshAdapterd GEOMETRYCORE_API MakeTransformedDynamicMeshAdapter (const FDynamicMesh3 *Mesh, FTransform3d Transform)
FPointSetAdapterd GEOMETRYCORE_API MakeTriCentroidsAdapter (const FDynamicMesh3 *Mesh)
DYNAMICMESH_API FString MakeUniqueGroupLayerName (const FDynamicMesh3 &Mesh, FString BaseName)
template<typename T>
constexpr UE::Math::TVector< T > MakeUnitVector3 (int32 Axis)
FPointSetAdapterd GEOMETRYCORE_API MakeVerticesAdapter (const FDynamicMesh3 *Mesh)
FVector3i Max (const FVector3i &V0, const FVector3i &V1)
template<typename T>
constexpr UE::Math::TVector< T > Max (const UE::Math::TVector< T > &V0, const UE::Math::TVector< T > &V1)
template<typename T>
constexpr T MaxAbsElement (const UE::Math::TVector< T > &Vector)
template<typename T>
constexpr int32 MaxAbsElementIndex (const UE::Math::TVector< T > &Vector)
template<typename T>
constexpr T MaxElement (const UE::Math::TVector< T > &Vector)
template<typename T>
constexpr int32 MaxElementIndex (const UE::Math::TVector< T > &Vector)
FVector3i Min (const FVector3i &V0, const FVector3i &V1)
template<typename T>
constexpr UE::Math::TVector< T > Min (const UE::Math::TVector< T > &V0, const UE::Math::TVector< T > &V1)
template<typename T>
constexpr T MinAbsElement (const UE::Math::TVector< T > &Vector)
template<typename T>
constexpr int32 MinAbsElementIndex (const UE::Math::TVector< T > &Vector)
template<typename T>
constexpr T MinElement (const UE::Math::TVector< T > &Vector)
template<typename T>
constexpr int32 MinElementIndex (const UE::Math::TVector< T > &Vector)
template<typename T>
T Normalize (UE::Math::TVector2< T > &Vector, const T Epsilon=0)
template<typename T>
T Normalize (UE::Math::TVector< T > &Vector, const T Epsilon=0)
template<typename T>
UE::Math::TVector2< T > Normalized (const UE::Math::TVector2< T > &Vector, const T Epsilon=0)
template<typename T>
constexpr UE::Math::TVector< T > Normalized (const UE::Math::TVector< T > &Vector, const T Epsilon=0)
template<typename RealType>
TQuaternion< RealType > operator* (const TQuaternion< RealType > &A, const TQuaternion< RealType > &B)
template<typename RealType>
TVector< RealType > operator* (const TQuaternion< RealType > &Q, const UE::Math::TVector< RealType > &V)
template<typename RealType>
TQuaternion< RealType > operator* (const TQuaternion< RealType > &Q, RealType Scalar)
FVector2i operator* (int32 Scalar, const FVector2i &V)
FVector3i operator* (int32 Scalar, const FVector3i &V)
template<typename RealType>
TQuaternion< RealType > operator* (RealType Scalar, const TQuaternion< RealType > &Q)
template<typename RealType>
TMatrix2< RealType > operator* (RealType Scale, const TMatrix2< RealType > &Mat)
template<typename RealType>
TMatrix3< RealType > operator* (RealType Scale, const TMatrix3< RealType > &Mat)
template<typename RealType>
TQuaternion< RealType > operator+ (const TQuaternion< RealType > &A, const TQuaternion< RealType > &B)
template<typename RealType>
TQuaternion< RealType > operator- (const TQuaternion< RealType > &A, const TQuaternion< RealType > &B)
std::ostream & operator<< (std::ostream &os, const FVector2i &Vec)
std::ostream & operator<< (std::ostream &os, const FVector3i &Vec)
template<typename RealType>
std::ostream & operator<< (std::ostream &os, const UE::Math::TVector< RealType > &Vec)
template<typename RealType>
TOrientedBox3< RealType > GEOMETRYCORE_API OptimizeOrientedBox3Points (const TOrientedBox3< RealType > &InitialBox, int32 NumIterations, int32 NumPoints, TFunctionRef< TVector< RealType >(int32)> GetPointFunc, TFunctionRef< bool(int32)> Filter, EBox3FitCriteria FitMethod=EBox3FitCriteria::Volume, FProgressCancel *ProgressCancel=nullptr)
Improve an oriented bounding box fit iteratively.
template<typename T>
T Orient (const UE::Math::TVector2< T > &A, const UE::Math::TVector2< T > &B, const UE::Math::TVector2< T > &C)
template<typename RealType>
int Orientation (RealType X1, RealType Y1, RealType X2, RealType Y2, RealType &TwiceSignedArea)
template<typename IntType, typename T, typename TransformFuncT, typename ReduceFuncT>
T ParallelTransformReduce (IntType Num, const T &Init, TransformFuncT Transform, ReduceFuncT Reduce, int64 InNumTasks)
template<typename IntType, typename T, typename InitFuncT, typename TransformFuncT, typename ReduceFuncT>
void ParallelTransformReduce (IntType Num, InitFuncT InitFunc, TransformFuncT Transform, ReduceFuncT Reduce, T &Out, int64 InNumTasks)
template<typename T, typename IterT, typename TransformFuncT, typename ReduceFuncT>
T ParallelTransformReduce (IterT BeginIterator, IterT EndIterator, const T &Init, TransformFuncT Transform, ReduceFuncT Reduce, int64 InNumTasks)
template<typename T, typename IterT, typename InitFuncT, typename TransformFuncT, typename ReduceFuncT>
void ParallelTransformReduce (IterT BeginIterator, IterT EndIterator, InitFuncT InitFunc, TransformFuncT Transform, ReduceFuncT Reduce, T &Out, int64 InNumTasks)
template<typename T>
constexpr UE::Math::TVector2< T > PerpCW (const UE::Math::TVector2< T > &V)
GEOMETRYCORE_API bool PointInTriangle2d (double X0, double Y0, double X1, double Y1, double X2, double Y2, double X3, double Y3, double &A, double &B, double &C)
template<typename RealType>
RealType PointSegmentDistance (const TVector< RealType > &x0, const TVector< RealType > &x1, const TVector< RealType > &x2)
GEOMETRYCORE_API double PointTriangleDistance (const FVector3d &x0, const FVector3d &x1, const FVector3d &x2, const FVector3d &x3)
GEOMETRYCORE_API float PointTriangleDistance (const FVector3f &x0, const FVector3f &x1, const FVector3f &x2, const FVector3f &x3)
GEOMETRYALGORITHMS_API bool PolygonsDifference (TArrayView< const FGeneralPolygon2d > PosPolygons, TArrayView< const FGeneralPolygon2d > NegPolygons, TArray< FGeneralPolygon2d > &ResultOut)
Populate ResultOut with the difference of PosPolygons minus NegPolygons.
GEOMETRYALGORITHMS_API bool PolygonsExclusiveOr (TArrayView< const FGeneralPolygon2d > SubjPolygons, TArrayView< const FGeneralPolygon2d > ClipPolygons, TArray< FGeneralPolygon2d > &ResultOut)
Populate ResultOut with the 'exclusive or' of SubjPolygons with ClipPolygons.
GEOMETRYALGORITHMS_API bool PolygonsIntersection (TArrayView< const FGeneralPolygon2d > SubjPolygons, TArrayView< const FGeneralPolygon2d > ClipPolygons, TArray< FGeneralPolygon2d > &ResultOut)
Populate ResultOut with the intersection of SubjPolygons with ClipPolygons.
GEOMETRYALGORITHMS_API bool PolygonsOffset (double Offset, TArrayView< const FGeneralPolygon2d > Polygons, TArray< FGeneralPolygon2d > &ResultOut, bool bCopyInputOnFailure, double MiterLimit, EPolygonOffsetJoinType JoinType=EPolygonOffsetJoinType::Square, EPolygonOffsetEndType EndType=EPolygonOffsetEndType::Polygon, double MaxStepsPerRadian=-1.0, double DefaultStepsPerRadianScale=1.0)
GEOMETRYALGORITHMS_API bool PolygonsOffsets (double FirstOffset, double SecondOffset, TArrayView< const FGeneralPolygon2d > Polygons, TArray< FGeneralPolygon2d > &ResultOut, bool bCopyInputOnFailure, double MiterLimit, EPolygonOffsetJoinType JoinType=EPolygonOffsetJoinType::Square, EPolygonOffsetEndType EndType=EPolygonOffsetEndType::Polygon, double MaxStepsPerRadian=-1.0, double DefaultStepsPerRadianScale=1.0)
GEOMETRYALGORITHMS_API bool PolygonsUnion (TArrayView< const FGeneralPolygon2d > Polygons, TArray< FGeneralPolygon2d > &ResultOut, bool bCopyInputOnFailure)
Populate ResultOut with the union of the input Polygons.
MODELINGCOMPONENTS_API bool RegisterSceneSnappingManager (UInteractiveToolsContext *ToolsContext)
If one does not already exist, create a new instance of UModelingSceneSnappingManager and add it to the ToolsContext's ContextObjectStore.
MODELINGCOMPONENTS_API bool SetSimpleCollision (UPrimitiveComponent *Component, const FSimpleShapeSet3d *ShapeSet, FComponentCollisionSettings CollisionSettings=FComponentCollisionSettings())
Replace existing Simple Collision geometry in Component with that defined by ShapeSet, and update the Component/BodySetup collision settings.
MODELINGCOMPONENTS_API bool SetToolOutputGeometrySelectionForTarget (UInteractiveTool *Tool, UToolTarget *Target, const FGeometrySelection &OutputSelection)
Allow a Tool to return an "output" FGeometrySelection for the given ToolTarget (presumably on Tool Shutdown) Target must be an "active" selection target in the current UGeometrySelectionManager.
template<typename T>
T SignedAngleR (const UE::Math::TVector2< T > &V1, const UE::Math::TVector2< T > &V2)
template<typename RealType>
RealType SnapToIncrement (RealType Value, RealType Increment, RealType Offset=0)
Snap Value to steps of Increment (centered at 0, ie steps are -Increment, 0, Increment, 2*Increment, ...).
DYNAMICMESH_API FVector3d SolveInsetVertexPositionFromLinePair (const FVector3d &Position, const FLine3d &InsetEdgeLine1, const FLine3d &InsetEdgeLine2)
Solve for a new inset position by finding the intersection point a pair of inset-lines (or handle parallel-lines case).
DYNAMICMESH_API void SolveInsetVertexPositionsFromInsetLines (const FDynamicMesh3 &Mesh, const TArray< FLine3d > &InsetEdgeLines, const TArray< int32 > &VertexIDs, TArray< FVector3d > &VertexPositionsOut, bool bIsLoop)
For each vertex in VertexIDs, compute inset position based on list of precomputed inset lines and store in VertexPositionsOut.
void MODELINGCOMPONENTS_API SplineDeformDynamicMesh (USplineMeshComponent &SplineMeshComponent, FDynamicMesh3 &Mesh, bool bUpdateTangentSpace=true)
Applies a deformation as defined by the SplineMeshComponent to the dynamic mesh The normal, tangent, and bi-tangent will be updated if bUpdateTangentSpace is selected.
GEOMETRYCORE_API bool SplitBoundaryVertexTrianglesIntoSubsets (const FDynamicMesh3 *Mesh, int32 VertexID, int32 SplitEdgeID, TArray< int32 > &TriangleSet0, TArray< int32 > &TriangleSet1)
Split the triangle one-ring at VertexID into two triangle sets by "cutting" it with edge SplitEdgeID that is connected to VertexID.
GEOMETRYCORE_API bool SplitInteriorVertexTrianglesIntoSubsets (const FDynamicMesh3 *Mesh, int32 VertexID, int32 SplitEdgeID0, int32 SplitEdgeID1, TArray< int32 > &TriangleSet0, TArray< int32 > &TriangleSet1)
Split the triangle one-ring at VertexID into two triangle sets by "cutting" it with two edges SplitEdgeID0 and SplitEdgeID1 that are both connected to VertexID.
template<typename Real>
double SquaredDistanceFromLineIntegratedAlongSegment (const TLine3< Real > &Line, const TSegment3< Real > &Segment)
Integrates the squared distance to a line along a given segment.
template<typename T>
T SquaredLength (const UE::Math::TVector< T > &V)
double SumPathLength (const FDeformableEdgePath &DeformableEdgePath)
template<typename RealType>
GEOMETRYCORE_API bool TestIntersection (const THalfspace3< RealType > &Halfspace, const TCapsule3< RealType > &Capsule)
template<typename RealType>
GEOMETRYCORE_API bool TestIntersection (const THalfspace3< RealType > &Halfspace, const TOrientedBox3< RealType > &Box)
template<typename RealType>
GEOMETRYCORE_API bool TestIntersection (const THalfspace3< RealType > &Halfspace, const TSphere3< RealType > &Sphere)
template<typename Real>
GEOMETRYCORE_API bool TestIntersection (const TSegment2< Real > &Segment, const TAxisAlignedBox2< Real > &Box)
template<typename T>
constexpr FColor ToFColor (const UE::Math::TVector4< T > &Vector)
template<typename T>
FLinearColor ToLinearColor (const UE::Math::TVector4< T > &V)
template<typename T>
constexpr FLinearColor ToLinearColor (const UE::Math::TVector< T > &Vector)
template<typename T>
UE::Math::TVector4< T > ToVector4 (const FLinearColor &Color)
MODELINGCOMPONENTS_API bool TransformSimpleCollision (UPrimitiveComponent *Component, const FTransform3d &Transform)
Apply Transform to any Simple Collision geometry owned by Component.
template<typename OverlayType, typename EnumeratorType, typename OutputSetType>
void TrianglesToOverlayElements (const OverlayType *Overlay, EnumeratorType TriangleEnumeration, OutputSetType &ElementsOut)
For a given list/enumeration of Triangles, and an Overlay, find all the Elements in all the Triangles.
GEOMETRYCORE_API void TriangleToVertexIDs (const FDynamicMesh3 *Mesh, TConstArrayView< int > TriangleIDs, TArray< int > &VertexIDsOut)
Find list of unique vertices that are contained in one or more triangles.
struct UE_DEPRECATED (5.3, "FRenderCaptureOptions is only used by deprecated functions, see those deprecation notes for more info.") MODELINGCOMPONENTS_API FRenderCaptureOptions
struct UE_DEPRECATED (5.3, "FRenderCaptureUpdate is only used by deprecated functions, see those deprecation notes for more info.") MODELINGCOMPONENTS_API FRenderCaptureUpdate
UE_DEPRECATED (5.3, "Please use ConfigureSceneCapture and FSceneCapturePhotoSet::Compute instead.") MODELINGCOMPONENTS_API TUniquePtr< FSceneCapturePhotoSet > CapturePhotoSet(const TArray< TObjectPtr< AActor > > &Actors
This function computes the SceneCapture for the first time.
UE_DEPRECATED (5.3, "Please use GetSceneCaptureConfig instead.") MODELINGCOMPONENTS_API FRenderCaptureOptions GetComputedPhotoSetOptions(const TUniquePtr< FSceneCapturePhotoSet > &SceneCapture)
UE_DEPRECATED (5.3, "Please use the overload where PendingBake has type FRenderCaptureTypeFlags instead.") MODELINGCOMPONENTS_API TUniquePtr< FMeshMapBaker > MakeRenderCaptureBaker(FDynamicMesh3 *BaseMesh
UE_DEPRECATED (5.3, "Please use UpdateSceneCapture instead.") MODELINGCOMPONENTS_API FRenderCaptureUpdate UpdatePhotoSets(const TUniquePtr< FSceneCapturePhotoSet > &SceneCapture
This function efficiently updates the given SceneCapture and returns a struct indicating which channels were updated.
UE_DEPRECATED (5.4, "Please use the overload passing Baker by reference. Using smart pointers was an error since ownership semantics were not intended.") MODELINGCOMPONENTS_API void GetTexturesFromRenderCaptureBaker(const TUniquePtr< FMeshMapBaker > &Baker
PRAGMA_DISABLE_DEPRECATION_WARNINGS UE_DEPRECATED (5.4, "Please use the overload passing SceneCapture by reference. Using smart pointers was an error since ownership semantics were not intended.") MODELINGCOMPONENTS_API void ConfigureSceneCapture(const TUniquePtr< FSceneCapturePhotoSet > &SceneCapture
UE_DEPRECATED (5.5, "EnumerateTriangleSelectionVertices with ApplyTransform passed a reference is deprecated. " "Please use the function of the same name which takes ApplyTransform as a pointer instead") DYNAMICMESH_API bool EnumerateTriangleSelectionVertices(const FGeometrySelection &MeshSelection
Prefer pointer version for ApplyTransform in EnumerateTriangleSelectionVertices.
UE_DEPRECATED (5.5, "Use GetDynamicMeshViaMeshDescription which takes a FGetMeshParameters instead.") MODELINGCOMPONENTS_API FDynamicMesh3 GetDynamicMeshViaMeshDescription(IMeshDescriptionProvider &MeshDescriptionProvider
template<typename T>
UE::Math::TVector< T > UnitCross (const UE::Math::TVector< T > &V1, const UE::Math::TVector< T > &V2)
void MODELINGCOMPONENTS_API UpdateGeometrySelectionVisualization (UPreviewGeometry *PreviewGeom, UGeometrySelectionVisualizationProperties *Settings)
Update the geometry selection preview geometry according to Settings.
DYNAMICMESH_API void UpdateGroupSelectionViaRaycast (const FColliderMesh *ColliderMesh, const FGroupTopology *GroupTopology, FGeometrySelectionEditor *Editor, const FRay3d &LocalRay, const FGeometrySelectionUpdateConfig &UpdateConfig, FGeometrySelectionUpdateResult &ResultOut)
Update a FGeometrySelection (via the Editor) of mesh polygroup faces/edges/corners, based on a raycast.
MODELINGCOMPONENTS_API FRenderCaptureTypeFlags UpdateSceneCapture (FSceneCapturePhotoSet &SceneCapture, const TArray< TObjectPtr< AActor > > &Actors, const FSceneCaptureConfig &DesiredConfig, bool bAllowCancel)
DYNAMICMESH_API bool UpdateSelectionWithNewElements (FGeometrySelectionEditor *Editor, EGeometrySelectionChangeType ChangeType, const TArray< uint64 > &NewIDs, FGeometrySelectionDelta *DeltaOut=nullptr)
Update a FGeometrySelection (via the Editor)
MODELINGCOMPONENTS_API void UpdateSimpleCollision (UBodySetup *BodySetup, const FKAggregateGeom *NewGeometry, UStaticMesh *StaticMesh, FComponentCollisionSettings NewCollisionSettings=FComponentCollisionSettings())
Replace existing Simple Collision geometry in BodySetup with that defined by NewGeometry, and update the Component/BodySetup collision settings.
DYNAMICMESH_API void UpdateTriangleSelectionViaRaycast (const FColliderMesh *ColliderMesh, FGeometrySelectionEditor *Editor, const FRay3d &LocalRay, const FGeometrySelectionUpdateConfig &UpdateConfig, FGeometrySelectionUpdateResult &ResultOut)
Update a FGeometrySelection (via the Editor) of mesh vertices/edges/triangles based on a raycast.
MESHMODELINGTOOLSEXP_API void UpdateUVLayerNames (FString &UVLayer, TArray< FString > &UVLayerNamesList, const FDynamicMesh3 &Mesh)
Updates a tool property set's UVLayerNamesList from the list of UV layers on a given mesh.
GEOMETRYCORE_API void VertexToTriangleOneRing (const FDynamicMesh3 *Mesh, TConstArrayView< int > VertexIDs, TSet< int > &TriangleIDsOut)
Find all the triangles in all the one rings of a set of vertices.
Variables
PRAGMA_DISABLE_DEPRECATION_WARNINGS const TArray< TObjectPtr< AActor > > & Actors
const UE::Geometry::FDynamicMesh3 const FTransform & ApplyTransform
PRAGMA_DISABLE_DEPRECATION_WARNINGS const TArray< TObjectPtr< AActor > > const FSceneCaptureConfig bool bAllowCancel
TSharedPtr< FMeshTangentsd, ESPMode::ThreadSafe > BaseMeshTangents
TSharedPtr< FMeshTangentsd, ESPMode::ThreadSafe > TSharedPtr< TArray< int32 >, ESPMode::ThreadSafe > BaseMeshUVCharts
bool bRequestTangents
PRAGMA_DISABLE_DEPRECATION_WARNINGS const TArray< TObjectPtr< AActor > > const FSceneCaptureConfig & Config
const TArray< TObjectPtr< AActor > > const FSceneCaptureConfig & DesiredConfig
const UE::Geometry::FDynamicMesh3 & Mesh
TSharedPtr< FMeshTangentsd, ESPMode::ThreadSafe > TSharedPtr< TArray< int32 >, ESPMode::ThreadSafe > FSceneCapturePhotoSet FSceneCapturePhotoSetSampler FRenderCaptureOptions int32 EBakeTextureResolution EBakeTextureSamplesPerPixel FRenderCaptureOcclusionHandler * OcclusionHandler
const FRenderCaptureOptions & Options
TSharedPtr< FMeshTangentsd, ESPMode::ThreadSafe > TSharedPtr< TArray< int32 >, ESPMode::ThreadSafe > FSceneCapturePhotoSet FSceneCapturePhotoSetSampler FRenderCaptureOptions PendingBake
FSceneCapturePhotoSet::ECaptureTypeStatus QueryStatus = FSceneCapturePhotoSet::ECaptureTypeStatus::Computed)
TSharedPtr< FMeshTangentsd, ESPMode::ThreadSafe > TSharedPtr< TArray< int32 >, ESPMode::ThreadSafe > FSceneCapturePhotoSet FSceneCapturePhotoSetSampler * Sampler
TSharedPtr< FMeshTangentsd, ESPMode::ThreadSafe > TSharedPtr< TArray< int32 >, ESPMode::ThreadSafe > FSceneCapturePhotoSet FSceneCapturePhotoSetSampler FRenderCaptureOptions int32 EBakeTextureResolution EBakeTextureSamplesPerPixel SamplesPerPixel
TSharedPtr< FMeshTangentsd, ESPMode::ThreadSafe > TSharedPtr< TArray< int32 >, ESPMode::ThreadSafe > FSceneCapturePhotoSet * SceneCapture
TSharedPtr< FMeshTangentsd, ESPMode::ThreadSafe > TSharedPtr< TArray< int32 >, ESPMode::ThreadSafe > FSceneCapturePhotoSet FSceneCapturePhotoSetSampler FRenderCaptureOptions int32 TargetUVLayer
TSharedPtr< FMeshTangentsd, ESPMode::ThreadSafe > TSharedPtr< TArray< int32 >, ESPMode::ThreadSafe > FSceneCapturePhotoSet FSceneCapturePhotoSetSampler FRenderCaptureOptions int32 EBakeTextureResolution TextureImageSize
FRenderCaptureTextures & TexturesOut
const FRenderCaptureOptions FRenderCaptureUpdate & Update
const UE::Geometry::FDynamicMesh3 const FTransform TFunctionRef< void(uint64, const FVector3d &)> VertexFunc
Typedef Documentation
FAttrBasedQuadricErrord
typedef TAttrBasedQuadricError<double> UE::Geometry::FAttrBasedQuadricErrord
Definition at line 716 of file QuadricError.h.
FAttrBasedQuadricErrorf
typedef TAttrBasedQuadricError<float> UE::Geometry::FAttrBasedQuadricErrorf
Definition at line 715 of file QuadricError.h.
FAttrMeshSimplification
typedef TMeshSimplification< FAttrBasedQuadricErrord > UE::Geometry::FAttrMeshSimplification
Definition at line 436 of file MeshSimplification.h.
FAxisAlignedBox2d
typedef TAxisAlignedBox2<double> UE::Geometry::FAxisAlignedBox2d
Definition at line 860 of file BoxTypes.h.
FAxisAlignedBox2f
typedef TAxisAlignedBox2<float> UE::Geometry::FAxisAlignedBox2f
Definition at line 859 of file BoxTypes.h.
FAxisAlignedBox3d
typedef TAxisAlignedBox3<double> UE::Geometry::FAxisAlignedBox3d
Definition at line 862 of file BoxTypes.h.
FAxisAlignedBox3f
typedef TAxisAlignedBox3<float> UE::Geometry::FAxisAlignedBox3f
Definition at line 861 of file BoxTypes.h.
FBiLaplacianTwistPullKelvinlet
typedef TBlendPairedKelvinlet< FTwistKelvinlet, FBiLaplacianPullKelvinlet > UE::Geometry::FBiLaplacianTwistPullKelvinlet
Definition at line 661 of file Kelvinlets.h.
FBlendPullKelvinlet
typedef TBlendPairedKelvinlet< FBiLaplacianPullKelvinlet, FLaplacianPullKelvinlet > UE::Geometry::FBlendPullKelvinlet
Definition at line 662 of file Kelvinlets.h.
FBlendPullSharpKelvinlet
typedef TBlendPairedKelvinlet< FSharpBiLaplacianPullKelvinlet, FSharpLaplacianPullKelvinlet > UE::Geometry::FBlendPullSharpKelvinlet
Definition at line 663 of file Kelvinlets.h.
FBlockedDenseGrid3d
typedef TBlockedDenseGrid3<double> UE::Geometry::FBlockedDenseGrid3d
Definition at line 907 of file BlockedDenseGrid3.h.
FBlockedDenseGrid3f
typedef TBlockedDenseGrid3<float> UE::Geometry::FBlockedDenseGrid3f
Definition at line 906 of file BlockedDenseGrid3.h.
FBlockedDenseGrid3i
typedef TBlockedDenseGrid3<int> UE::Geometry::FBlockedDenseGrid3i
Definition at line 908 of file BlockedDenseGrid3.h.
FBlockedGrid3b
typedef TBlockedGrid3<bool, 8> UE::Geometry::FBlockedGrid3b
Definition at line 718 of file BlockedDenseGrid3.h.
FBlockedGrid3d
typedef TBlockedGrid3<double, 8> UE::Geometry::FBlockedGrid3d
Definition at line 714 of file BlockedDenseGrid3.h.
FBlockedGrid3f
typedef TBlockedGrid3<float, 8> UE::Geometry::FBlockedGrid3f
Definition at line 713 of file BlockedDenseGrid3.h.
FBlockedGrid3i
typedef TBlockedGrid3<int, 8> UE::Geometry::FBlockedGrid3i
Definition at line 715 of file BlockedDenseGrid3.h.
FBoundsGridIndexer3d
typedef TBoundsGridIndexer3<double> UE::Geometry::FBoundsGridIndexer3d
Definition at line 140 of file GridIndexing3.h.
FBoundsGridIndexer3f
typedef TBoundsGridIndexer3<float> UE::Geometry::FBoundsGridIndexer3f
Definition at line 139 of file GridIndexing3.h.
FBSplineFilter
using UE::Geometry::FBSplineFilter = FBCSplineFilter<EBCSplineType::BSpline, false>
Definition at line 132 of file BCSplineFilter.h.
FCapsule3d
typedef TCapsule3<double> UE::Geometry::FCapsule3d
Definition at line 128 of file CapsuleTypes.h.
FCapsule3f
typedef TCapsule3<float> UE::Geometry::FCapsule3f
Definition at line 127 of file CapsuleTypes.h.
FCatmullRomFilter
using UE::Geometry::FCatmullRomFilter = FBCSplineFilter<EBCSplineType::CatmullRom, false>
Definition at line 133 of file BCSplineFilter.h.
FCircle2d
typedef TCircle2<double> UE::Geometry::FCircle2d
Definition at line 138 of file CircleTypes.h.
FCircle2f
typedef TCircle2<float> UE::Geometry::FCircle2f
Definition at line 137 of file CircleTypes.h.
FCircle3d
typedef TCircle3<double> UE::Geometry::FCircle3d
Definition at line 281 of file CircleTypes.h.
FCircle3f
typedef TCircle3<float> UE::Geometry::FCircle3f
Definition at line 280 of file CircleTypes.h.
FConstrainedDelaunay2d
typedef TConstrainedDelaunay2<double> UE::Geometry::FConstrainedDelaunay2d
Definition at line 179 of file ConstrainedDelaunay2.h.
FConstrainedDelaunay2f
typedef TConstrainedDelaunay2<float> UE::Geometry::FConstrainedDelaunay2f
Definition at line 178 of file ConstrainedDelaunay2.h.
FConvexHull2d
typedef TConvexHull2<double> UE::Geometry::FConvexHull2d
Definition at line 150 of file ConvexHull2.h.
FConvexHull2f
typedef TConvexHull2<float> UE::Geometry::FConvexHull2f
Definition at line 149 of file ConvexHull2.h.
FConvexHull3d
typedef TConvexHull3<double> UE::Geometry::FConvexHull3d
Definition at line 312 of file ConvexHull3.h.
FConvexHull3f
typedef TConvexHull3<float> UE::Geometry::FConvexHull3f
Definition at line 311 of file ConvexHull3.h.
FDenseGrid2d
typedef TDenseGrid2<double> UE::Geometry::FDenseGrid2d
Definition at line 189 of file DenseGrid2.h.
FDenseGrid2f
typedef TDenseGrid2<float> UE::Geometry::FDenseGrid2f
Definition at line 188 of file DenseGrid2.h.
FDenseGrid2i
typedef TDenseGrid2<int32> UE::Geometry::FDenseGrid2i
Definition at line 190 of file DenseGrid2.h.
FDenseGrid3d
typedef TDenseGrid3<double> UE::Geometry::FDenseGrid3d
Definition at line 234 of file DenseGrid3.h.
FDenseGrid3f
typedef TDenseGrid3<float> UE::Geometry::FDenseGrid3f
Definition at line 233 of file DenseGrid3.h.
FDenseGrid3i
typedef TDenseGrid3<int> UE::Geometry::FDenseGrid3i
Definition at line 235 of file DenseGrid3.h.
FDifferenceGeneralPolygon2GeneralPolygon2d
typedef TDifferencePolygon2Polygon2<TGeneralPolygon2<double>, double> UE::Geometry::FDifferenceGeneralPolygon2GeneralPolygon2d
Definition at line 55 of file PolygonIntersectionUtils.h.
FDifferenceGeneralPolygon2GeneralPolygon2f
typedef TDifferencePolygon2Polygon2<TGeneralPolygon2<float>, float> UE::Geometry::FDifferenceGeneralPolygon2GeneralPolygon2f
Definition at line 54 of file PolygonIntersectionUtils.h.
FDistLine2AxisAlignedBox2d
typedef TDistLine2AxisAlignedBox2<double> UE::Geometry::FDistLine2AxisAlignedBox2d
Definition at line 225 of file DistLine2AxisAlignedBox2.h.
FDistLine2AxisAlignedBox2f
typedef TDistLine2AxisAlignedBox2<float> UE::Geometry::FDistLine2AxisAlignedBox2f
Definition at line 224 of file DistLine2AxisAlignedBox2.h.
FDistLine3Circle3d
typedef TDistLine3Circle3<double> UE::Geometry::FDistLine3Circle3d
Definition at line 53 of file DistLine3Circle3.h.
FDistLine3Circle3f
typedef TDistLine3Circle3<float> UE::Geometry::FDistLine3Circle3f
Definition at line 52 of file DistLine3Circle3.h.
FDistLine3Line3d
typedef TDistLine3Line3<double> UE::Geometry::FDistLine3Line3d
Definition at line 104 of file DistLine3Line3.h.
FDistLine3Line3f
typedef TDistLine3Line3<float> UE::Geometry::FDistLine3Line3f
Definition at line 103 of file DistLine3Line3.h.
FDistLine3Ray3d
typedef TDistLine3Ray3<double> UE::Geometry::FDistLine3Ray3d
Definition at line 113 of file DistLine3Ray3.h.
FDistLine3Ray3f
typedef TDistLine3Ray3<float> UE::Geometry::FDistLine3Ray3f
Definition at line 112 of file DistLine3Ray3.h.
FDistLine3Segment3d
typedef TDistLine3Segment3<double> UE::Geometry::FDistLine3Segment3d
Definition at line 127 of file DistLine3Segment3.h.
FDistLine3Segment3f
typedef TDistLine3Segment3<float> UE::Geometry::FDistLine3Segment3f
Definition at line 126 of file DistLine3Segment3.h.
FDistLine3Triangle3d
typedef TDistLine3Triangle3<double> UE::Geometry::FDistLine3Triangle3d
Definition at line 132 of file DistLine3Triangle3.h.
FDistLine3Triangle3f
typedef TDistLine3Triangle3<float> UE::Geometry::FDistLine3Triangle3f
Definition at line 131 of file DistLine3Triangle3.h.
FDistPoint3Triangle3d
typedef TDistPoint3Triangle3<double> UE::Geometry::FDistPoint3Triangle3d
Definition at line 251 of file DistPoint3Triangle3.h.
FDistPoint3Triangle3f
typedef TDistPoint3Triangle3<float> UE::Geometry::FDistPoint3Triangle3f
Definition at line 250 of file DistPoint3Triangle3.h.
FDistRay3Segment3d
typedef TDistRay3Segment3<double> UE::Geometry::FDistRay3Segment3d
Definition at line 395 of file DistRay3Segment3.h.
FDistRay3Segment3f
typedef TDistRay3Segment3<float> UE::Geometry::FDistRay3Segment3f
Definition at line 394 of file DistRay3Segment3.h.
FDistSegment2AxisAlignedBox2d
typedef TDistSegment2AxisAlignedBox2<double> UE::Geometry::FDistSegment2AxisAlignedBox2d
Definition at line 85 of file DistSegment2AxisAlignedBox2.h.
FDistSegment2AxisAlignedBox2f
typedef TDistSegment2AxisAlignedBox2<float> UE::Geometry::FDistSegment2AxisAlignedBox2f
Definition at line 84 of file DistSegment2AxisAlignedBox2.h.
FDistSegment3Triangle3d
typedef TDistSegment3Triangle3<double> UE::Geometry::FDistSegment3Triangle3d
Definition at line 92 of file DistSegment3Triangle3.h.
FDistSegment3Triangle3f
typedef TDistSegment3Triangle3<float> UE::Geometry::FDistSegment3Triangle3f
Definition at line 91 of file DistSegment3Triangle3.h.
FDistTriangle3Triangle3d
typedef TDistTriangle3Triangle3<double> UE::Geometry::FDistTriangle3Triangle3d
Definition at line 137 of file DistTriangle3Triangle3.h.
FDistTriangle3Triangle3f
typedef TDistTriangle3Triangle3<float> UE::Geometry::FDistTriangle3Triangle3f
Definition at line 136 of file DistTriangle3Triangle3.h.
FDynamicGraph2d
typedef FDynamicGraph2<double> UE::Geometry::FDynamicGraph2d
Definition at line 246 of file DynamicGraph2.h.
FDynamicGraph3d
typedef FDynamicGraph3<double> UE::Geometry::FDynamicGraph3d
Definition at line 151 of file DynamicGraph3.h.
FDynamicMeshAABBTree3
typedef TMeshAABBTree3< FDynamicMesh3 > UE::Geometry::FDynamicMeshAABBTree3
Definition at line 20 of file TransferBoneWeights.h.
FDynamicMeshAttributeBase
typedef TDynamicAttributeBase<FDynamicMesh3> UE::Geometry::FDynamicMeshAttributeBase
Definition at line 256 of file DynamicAttribute.h.
FDynamicMeshAttributeChangeBase
typedef TDynamicAttributeChangeBase<FDynamicMesh3> UE::Geometry::FDynamicMeshAttributeChangeBase
Definition at line 57 of file DynamicAttribute.h.
FDynamicMeshAttributeSetBase
typedef TDynamicAttributeSetBase<FDynamicMesh3> UE::Geometry::FDynamicMeshAttributeSetBase
Definition at line 424 of file DynamicAttribute.h.
FDynamicMeshBoneColorAttribute
typedef TDynamicBoneAttributeBase< FDynamicMesh3, FVector4f > UE::Geometry::FDynamicMeshBoneColorAttribute = TDynamicBoneAttributeBase<FDynamicMesh3, FVector4f>
Definition at line 168 of file DynamicBoneAttribute.h.
FDynamicMeshBoneNameAttribute
typedef TDynamicBoneAttributeBase< FDynamicMesh3, FName > UE::Geometry::FDynamicMeshBoneNameAttribute = TDynamicBoneAttributeBase<FDynamicMesh3, FName>
Definition at line 166 of file DynamicBoneAttribute.h.
FDynamicMeshBoneParentIndexAttribute
typedef TDynamicBoneAttributeBase< FDynamicMesh3, int32 > UE::Geometry::FDynamicMeshBoneParentIndexAttribute = TDynamicBoneAttributeBase<FDynamicMesh3, int32>
Definition at line 167 of file DynamicBoneAttribute.h.
FDynamicMeshBonePoseAttribute
typedef TDynamicBoneAttributeBase< FDynamicMesh3, FTransform > UE::Geometry::FDynamicMeshBonePoseAttribute = TDynamicBoneAttributeBase<FDynamicMesh3, FTransform>
Definition at line 169 of file DynamicBoneAttribute.h.
FDynamicMeshColorChange
typedef TDynamicMeshAttributeChange<float, 4> UE::Geometry::FDynamicMeshColorChange
Standard Color overlay change type - 4-element float.
Definition at line 101 of file DynamicMeshChangeTracker.h.
FDynamicMeshColorOverlay
typedef TDynamicMeshVectorOverlay<float, 4, FVector4f> UE::Geometry::FDynamicMeshColorOverlay
Standard Color overlay type - 4-element float (rbga)
Definition at line 45 of file DynamicMeshAttributeSet.h.
FDynamicMeshMaterialAttribute
typedef TDynamicMeshScalarTriangleAttribute<int32> UE::Geometry::FDynamicMeshMaterialAttribute
Standard per-triangle integer material ID.
Definition at line 47 of file DynamicMeshAttributeSet.h.
FDynamicMeshNormalChange
typedef TDynamicMeshAttributeChange<float,3> UE::Geometry::FDynamicMeshNormalChange
Standard Normal overlay change type - 3-element float.
Definition at line 99 of file DynamicMeshChangeTracker.h.
FDynamicMeshNormalOverlay
typedef TDynamicMeshVectorOverlay<float, 3, FVector3f> UE::Geometry::FDynamicMeshNormalOverlay
Standard Normal overlay type - 3-element float.
Definition at line 43 of file DynamicMeshAttributeSet.h.
FDynamicMeshPolygroupAttribute
typedef TDynamicMeshScalarTriangleAttribute<int32> UE::Geometry::FDynamicMeshPolygroupAttribute
Per-triangle integer polygroup ID.
Definition at line 50 of file DynamicMeshAttributeSet.h.
FDynamicMeshSculptLayerAttribute
typedef TDynamicMeshVertexAttribute<double, 3> UE::Geometry::FDynamicMeshSculptLayerAttribute
Per-vertex position offsets.
Definition at line 17 of file DynamicMeshSculptLayers.h.
FDynamicMeshTriGroupChange
typedef FDynamicMeshTriangleAttributeChange<int32,1> UE::Geometry::FDynamicMeshTriGroupChange
Standard per-triangle integer attribute change type.
Definition at line 103 of file DynamicMeshChangeTracker.h.
FDynamicMeshUVChange
typedef TDynamicMeshAttributeChange<float,2> UE::Geometry::FDynamicMeshUVChange
Standard UV overlay change type - 2-element float.
Definition at line 97 of file DynamicMeshChangeTracker.h.
FDynamicMeshUVOverlay
typedef TDynamicMeshVectorOverlay<float, 2, FVector2f> UE::Geometry::FDynamicMeshUVOverlay
Standard UV overlay type - 2-element float.
Definition at line 41 of file DynamicMeshAttributeSet.h.
FDynamicMeshVertexSkinWeightsAttribute
typedef TDynamicVertexSkinWeightsAttribute< FDynamicMesh3 > UE::Geometry::FDynamicMeshVertexSkinWeightsAttribute = TDynamicVertexSkinWeightsAttribute<FDynamicMesh3>
Definition at line 19 of file SmoothBoneWeights.h.
FDynamicMeshWeightAttribute
typedef TDynamicMeshVertexAttribute<float, 1> UE::Geometry::FDynamicMeshWeightAttribute
Per-vertex scalar float weight.
Definition at line 53 of file DynamicMeshAttributeSet.h.
FDynamicMeshWeightChange
typedef TDynamicMeshAttributeChange<float, 1> UE::Geometry::FDynamicMeshWeightChange
Standard weight map change type - 1-element float.
Definition at line 106 of file DynamicMeshChangeTracker.h.
FDynamicPointSet3d
typedef TDynamicPointSet3<double> UE::Geometry::FDynamicPointSet3d
Definition at line 304 of file DynamicPointSet3.h.
FDynamicPointSet3f
typedef TDynamicPointSet3<float> UE::Geometry::FDynamicPointSet3f
Definition at line 303 of file DynamicPointSet3.h.
FExactIntrTriangle3Triangle3d
typedef TExactIntrTriangle3Triangle3<double> UE::Geometry::FExactIntrTriangle3Triangle3d
Definition at line 211 of file ExactIntrTriangle3Triangle3.h.
FExactIntrTriangle3Triangle3f
typedef TExactIntrTriangle3Triangle3<float> UE::Geometry::FExactIntrTriangle3Triangle3f
Definition at line 210 of file ExactIntrTriangle3Triangle3.h.
FExclusiveOrGeneralPolygon2GeneralPolygon2d
typedef TExclusiveOrPolygon2Polygon2<TGeneralPolygon2<double>, double> UE::Geometry::FExclusiveOrGeneralPolygon2GeneralPolygon2d
Definition at line 69 of file PolygonIntersectionUtils.h.
FExclusiveOrGeneralPolygon2GeneralPolygon2f
typedef TExclusiveOrPolygon2Polygon2<TGeneralPolygon2<float>, float> UE::Geometry::FExclusiveOrGeneralPolygon2GeneralPolygon2f
Definition at line 68 of file PolygonIntersectionUtils.h.
FExtremePoints3d
typedef TExtremePoints3<double> UE::Geometry::FExtremePoints3d
Definition at line 310 of file ConvexHull3.h.
FExtremePoints3f
typedef TExtremePoints3<float> UE::Geometry::FExtremePoints3f
Definition at line 309 of file ConvexHull3.h.
FFitCapsule3d
typedef TFitCapsule3<double> UE::Geometry::FFitCapsule3d
Definition at line 57 of file FitCapsule3.h.
FFitCapsule3f
typedef TFitCapsule3<float> UE::Geometry::FFitCapsule3f
Definition at line 56 of file FitCapsule3.h.
FFrame3d
typedef TFrame3<double> UE::Geometry::FFrame3d
Definition at line 478 of file FrameTypes.h.
FFrame3f
typedef TFrame3<float> UE::Geometry::FFrame3f
Definition at line 477 of file FrameTypes.h.
FGeneralPolygon2d
typedef TGeneralPolygon2<double> UE::Geometry::FGeneralPolygon2d
Definition at line 351 of file GeneralPolygon2.h.
FGeneralPolygon2f
typedef TGeneralPolygon2<float> UE::Geometry::FGeneralPolygon2f
Definition at line 352 of file GeneralPolygon2.h.
FHalfspace3d
typedef THalfspace3<double> UE::Geometry::FHalfspace3d
Definition at line 60 of file HalfspaceTypes.h.
FHalfspace3f
typedef THalfspace3<float> UE::Geometry::FHalfspace3f
Definition at line 59 of file HalfspaceTypes.h.
FImplicitLine3d
typedef TImplicitLine3<double> UE::Geometry::FImplicitLine3d
Definition at line 78 of file ImplicitFunctions.h.
FImplicitLine3f
typedef TImplicitLine3<float> UE::Geometry::FImplicitLine3f
Definition at line 77 of file ImplicitFunctions.h.
FImplicitPoint3d
typedef TImplicitPoint3<double> UE::Geometry::FImplicitPoint3d
Definition at line 53 of file ImplicitFunctions.h.
FImplicitPoint3f
typedef TImplicitPoint3<float> UE::Geometry::FImplicitPoint3f
Definition at line 52 of file ImplicitFunctions.h.
FIndexedWeightMap
typedef TIndexedWeightMap<float> UE::Geometry::FIndexedWeightMap
Definition at line 69 of file WeightMapTypes.h.
FIndexedWeightMap1d
typedef TIndexedWeightMap<double> UE::Geometry::FIndexedWeightMap1d
Definition at line 71 of file WeightMapTypes.h.
FIndexedWeightMap1f
typedef TIndexedWeightMap<float> UE::Geometry::FIndexedWeightMap1f
Definition at line 70 of file WeightMapTypes.h.
FIndexMapi
typedef TIndexMap<int> UE::Geometry::FIndexMapi
Definition at line 199 of file GeometryTypes.h.
FIndexMeshArrayAdapterd
typedef TIndexMeshArrayAdapter<uint32, double> UE::Geometry::FIndexMeshArrayAdapterd
Definition at line 229 of file MeshAdapter.h.
FIntersectGeneralPolygon2GeneralPolygon2d
typedef TIntersectPolygon2Polygon2<TGeneralPolygon2<double>, double> UE::Geometry::FIntersectGeneralPolygon2GeneralPolygon2d
Definition at line 62 of file PolygonIntersectionUtils.h.
FIntersectGeneralPolygon2GeneralPolygon2f
typedef TIntersectPolygon2Polygon2<TGeneralPolygon2<float>, float> UE::Geometry::FIntersectGeneralPolygon2GeneralPolygon2f
Definition at line 61 of file PolygonIntersectionUtils.h.
FIntersector1d
typedef TIntersector1<double> UE::Geometry::FIntersector1d
Definition at line 112 of file Intersector1.h.
FIntersector1f
typedef TIntersector1<float> UE::Geometry::FIntersector1f
Definition at line 113 of file Intersector1.h.
FInterval1d
typedef TInterval1<double> UE::Geometry::FInterval1d
Definition at line 231 of file BoxTypes.h.
FInterval1f
typedef TInterval1<float> UE::Geometry::FInterval1f
Definition at line 230 of file BoxTypes.h.
FIntrLine2Line2d
typedef TIntrLine2Line2<double> UE::Geometry::FIntrLine2Line2d
Definition at line 193 of file IntrLine2Line2.h.
FIntrLine2Line2f
typedef TIntrLine2Line2<float> UE::Geometry::FIntrLine2Line2f
Definition at line 194 of file IntrLine2Line2.h.
FIntrLine2Triangle2d
typedef TIntrLine2Triangle2<double> UE::Geometry::FIntrLine2Triangle2d
Definition at line 269 of file IntrLine2Triangle2.h.
FIntrLine2Triangle2f
typedef TIntrLine2Triangle2<float> UE::Geometry::FIntrLine2Triangle2f
Definition at line 268 of file IntrLine2Triangle2.h.
FIntrRay3AxisAlignedBox3d
typedef TIntrRay3AxisAlignedBox3<double> UE::Geometry::FIntrRay3AxisAlignedBox3d
Definition at line 234 of file IntrRay3AxisAlignedBox3.h.
FIntrRay3AxisAlignedBox3f
typedef TIntrRay3AxisAlignedBox3<float> UE::Geometry::FIntrRay3AxisAlignedBox3f
Definition at line 233 of file IntrRay3AxisAlignedBox3.h.
FIntrRay3OrientedBox3d
typedef TIntrRay3OrientedBox3<double> UE::Geometry::FIntrRay3OrientedBox3d
Definition at line 68 of file IntrRay3OrientedBox3.h.
FIntrRay3OrientedBox3f
typedef TIntrRay3OrientedBox3<float> UE::Geometry::FIntrRay3OrientedBox3f
Definition at line 67 of file IntrRay3OrientedBox3.h.
FIntrRay3Triangle3d
typedef TIntrRay3Triangle3<double> UE::Geometry::FIntrRay3Triangle3d
Definition at line 319 of file IntrRay3Triangle3.h.
FIntrRay3Triangle3f
typedef TIntrRay3Triangle3<float> UE::Geometry::FIntrRay3Triangle3f
Definition at line 318 of file IntrRay3Triangle3.h.
FIntrSegment2Segment2d
typedef TIntrSegment2Segment2<double> UE::Geometry::FIntrSegment2Segment2d
Definition at line 306 of file IntrSegment2Segment2.h.
FIntrSegment2Segment2f
typedef TIntrSegment2Segment2<float> UE::Geometry::FIntrSegment2Segment2f
Definition at line 307 of file IntrSegment2Segment2.h.
FIntrSegment2Triangle2d
typedef TIntrSegment2Triangle2<double> UE::Geometry::FIntrSegment2Triangle2d
Definition at line 222 of file IntrSegment2Triangle2.h.
FIntrSegment2Triangle2f
typedef TIntrSegment2Triangle2<float> UE::Geometry::FIntrSegment2Triangle2f
Definition at line 221 of file IntrSegment2Triangle2.h.
FIntrTriangle2AxisAlignedBox2d
typedef TIntrTriangle2AxisAlignedBox2<double> UE::Geometry::FIntrTriangle2AxisAlignedBox2d
Definition at line 132 of file IntrTriangle2AxisAlignedBox2.h.
FIntrTriangle2AxisAlignedBox2f
typedef TIntrTriangle2AxisAlignedBox2<float> UE::Geometry::FIntrTriangle2AxisAlignedBox2f
Definition at line 131 of file IntrTriangle2AxisAlignedBox2.h.
FIntrTriangle2Triangle2d
typedef TIntrTriangle2Triangle2<double> UE::Geometry::FIntrTriangle2Triangle2d
Definition at line 321 of file IntrTriangle2Triangle2.h.
FIntrTriangle2Triangle2f
typedef TIntrTriangle2Triangle2<float> UE::Geometry::FIntrTriangle2Triangle2f
Definition at line 320 of file IntrTriangle2Triangle2.h.
FIntrTriangle3Triangle3d
typedef TIntrTriangle3Triangle3<double> UE::Geometry::FIntrTriangle3Triangle3d
Definition at line 863 of file IntrTriangle3Triangle3.h.
FIntrTriangle3Triangle3f
typedef TIntrTriangle3Triangle3<float> UE::Geometry::FIntrTriangle3Triangle3f
Definition at line 862 of file IntrTriangle3Triangle3.h.
FLaplacianTwistPullKelvinlet
typedef TBlendPairedKelvinlet< FTwistKelvinlet, FLaplacianPullKelvinlet > UE::Geometry::FLaplacianTwistPullKelvinlet
Definition at line 660 of file Kelvinlets.h.
FLine2d
typedef TLine2<double> UE::Geometry::FLine2d
Definition at line 134 of file LineTypes.h.
FLine2f
typedef TLine2<float> UE::Geometry::FLine2f
Definition at line 135 of file LineTypes.h.
FLine3d
typedef TLine3<double> UE::Geometry::FLine3d
Definition at line 221 of file LineTypes.h.
FLine3f
typedef TLine3<float> UE::Geometry::FLine3f
Definition at line 222 of file LineTypes.h.
FMatrix2d
typedef TMatrix2<double> UE::Geometry::FMatrix2d
Definition at line 512 of file MatrixTypes.h.
FMatrix2f
typedef TMatrix2<float> UE::Geometry::FMatrix2f
Definition at line 511 of file MatrixTypes.h.
FMatrix3d
typedef TMatrix3<double> UE::Geometry::FMatrix3d
Definition at line 510 of file MatrixTypes.h.
FMatrix3f
typedef TMatrix3<float> UE::Geometry::FMatrix3f
Definition at line 509 of file MatrixTypes.h.
FMeshTangentsd
typedef TMeshTangents<double> UE::Geometry::FMeshTangentsd
Definition at line 293 of file MeshTangents.h.
FMeshTangentsf
typedef TMeshTangents<float> UE::Geometry::FMeshTangentsf
Definition at line 292 of file MeshTangents.h.
FMeshUniformSurfaceSampling
using UE::Geometry::FMeshUniformSurfaceSampling = TMeshUniformSurfaceSampling<FDynamicMesh3, double>
Definition at line 143 of file MeshSurfacePointSampling.h.
FMinVolumeBox3d
typedef TMinVolumeBox3<double> UE::Geometry::FMinVolumeBox3d
Definition at line 64 of file MinVolumeBox3.h.
FMinVolumeBox3f
typedef TMinVolumeBox3<float> UE::Geometry::FMinVolumeBox3f
Definition at line 63 of file MinVolumeBox3.h.
FMinVolumeSphere3d
typedef TMinVolumeSphere3<double> UE::Geometry::FMinVolumeSphere3d
Definition at line 46 of file MinVolumeSphere3.h.
FMinVolumeSphere3f
typedef TMinVolumeSphere3<float> UE::Geometry::FMinVolumeSphere3f
Definition at line 45 of file MinVolumeSphere3.h.
FMitchellNetravaliFilter
using UE::Geometry::FMitchellNetravaliFilter = FBCSplineFilter<EBCSplineType::MitchellNetravali, false>
Definition at line 134 of file BCSplineFilter.h.
FOffsetPolygon2d
typedef TOffsetPolygon2<TArrayView<TVector2<double> >, double> UE::Geometry::FOffsetPolygon2d
Definition at line 50 of file PolygonOffsetUtils.h.
FOffsetPolygon2f
typedef TOffsetPolygon2<TArrayView<TVector2<float> >, float> UE::Geometry::FOffsetPolygon2f
Definition at line 49 of file PolygonOffsetUtils.h.
FOrientedBox2d
typedef TOrientedBox2<double> UE::Geometry::FOrientedBox2d
Definition at line 633 of file OrientedBoxTypes.h.
FOrientedBox2f
typedef TOrientedBox2<float> UE::Geometry::FOrientedBox2f
Definition at line 632 of file OrientedBoxTypes.h.
FOrientedBox3d
typedef TOrientedBox3<double> UE::Geometry::FOrientedBox3d
Definition at line 635 of file OrientedBoxTypes.h.
FOrientedBox3f
typedef TOrientedBox3<float> UE::Geometry::FOrientedBox3f
Definition at line 634 of file OrientedBoxTypes.h.
FPCA3d
typedef TPCA3<double> UE::Geometry::FPCA3d
Definition at line 40 of file PCA3.h.
FPCA3f
typedef TPCA3<float> UE::Geometry::FPCA3f
Definition at line 39 of file PCA3.h.
FPlanarComplexd
typedef TPlanarComplex<double> UE::Geometry::FPlanarComplexd
Definition at line 179 of file PlanarComplex.h.
FPlanarComplexf
typedef TPlanarComplex<float> UE::Geometry::FPlanarComplexf
Definition at line 180 of file PlanarComplex.h.
FPlane3d
typedef TPlane3<double> UE::Geometry::FPlane3d
Definition at line 205 of file PlaneTypes.h.
FPlane3f
typedef TPlane3<float> UE::Geometry::FPlane3f
Definition at line 204 of file PlaneTypes.h.
FPointSetAdapterd
typedef TPointSetAdapter<double> UE::Geometry::FPointSetAdapterd
Definition at line 36 of file PointSetAdapter.h.
FPointSetAdapterf
typedef TPointSetAdapter<float> UE::Geometry::FPointSetAdapterf
Definition at line 37 of file PointSetAdapter.h.
FPolygon2d
typedef TPolygon2<double> UE::Geometry::FPolygon2d
Definition at line 1066 of file Polygon2.h.
FPolygon2f
typedef TPolygon2<float> UE::Geometry::FPolygon2f
Definition at line 1067 of file Polygon2.h.
FPolyline2d
typedef TPolyline2<double> UE::Geometry::FPolyline2d
Definition at line 15 of file Polyline2.h.
FPolyline2f
typedef TPolyline2<float> UE::Geometry::FPolyline2f
Definition at line 16 of file Polyline2.h.
FPolyline3d
typedef TPolyline3<double> UE::Geometry::FPolyline3d
Definition at line 15 of file Polyline3.h.
FPolyline3f
typedef TPolyline3<float> UE::Geometry::FPolyline3f
Definition at line 16 of file Polyline3.h.
FQEMSimplification
typedef TMeshSimplification< FQuadricErrord > UE::Geometry::FQEMSimplification
Definition at line 438 of file MeshSimplification.h.
FQuadricErrord
typedef TQuadricError<double> UE::Geometry::FQuadricErrord
Definition at line 249 of file QuadricError.h.
FQuadricErrorf
typedef TQuadricError<float> UE::Geometry::FQuadricErrorf
Definition at line 248 of file QuadricError.h.
FQuaterniond
typedef TQuaternion<double> UE::Geometry::FQuaterniond
Definition at line 163 of file Quaternion.h.
FQuaternionf
typedef TQuaternion<float> UE::Geometry::FQuaternionf
Definition at line 162 of file Quaternion.h.
FSampledScalarField2d
typedef TSampledScalarField2<double, double> UE::Geometry::FSampledScalarField2d
Definition at line 192 of file SampledScalarField2.h.
FSampledScalarField2f
typedef TSampledScalarField2<float, float> UE::Geometry::FSampledScalarField2f
Definition at line 193 of file SampledScalarField2.h.
FSampleSetStatisticsd
typedef TSampleSetStatistics<double> UE::Geometry::FSampleSetStatisticsd
Definition at line 94 of file SampleSetStatistics.h.
FSampleSetStatisticsf
typedef TSampleSetStatistics<float> UE::Geometry::FSampleSetStatisticsf
Definition at line 93 of file SampleSetStatistics.h.
FScaleGridIndexer2d
typedef TScaleGridIndexer2<double> UE::Geometry::FScaleGridIndexer2d
Definition at line 52 of file GridIndexing2.h.
FScaleGridIndexer2f
typedef TScaleGridIndexer2<float> UE::Geometry::FScaleGridIndexer2f
Definition at line 51 of file GridIndexing2.h.
FScaleGridIndexer3d
typedef TScaleGridIndexer3<double> UE::Geometry::FScaleGridIndexer3d
Definition at line 53 of file GridIndexing3.h.
FScaleGridIndexer3f
typedef TScaleGridIndexer3<float> UE::Geometry::FScaleGridIndexer3f
Definition at line 52 of file GridIndexing3.h.
FSegment2d
typedef TSegment2<double> UE::Geometry::FSegment2d
Definition at line 433 of file SegmentTypes.h.
FSegment2f
typedef TSegment2<float> UE::Geometry::FSegment2f
Definition at line 432 of file SegmentTypes.h.
FSegment3d
typedef TSegment3<double> UE::Geometry::FSegment3d
Definition at line 663 of file SegmentTypes.h.
FSegment3f
typedef TSegment3<float> UE::Geometry::FSegment3f
Definition at line 662 of file SegmentTypes.h.
FSharedConstDynamicMesh3
typedef TConstObjectSharedAccess<FDynamicMesh3> UE::Geometry::FSharedConstDynamicMesh3
Definition at line 137 of file MeshSharingUtil.h.
FShiftGridIndexer2d
typedef TShiftGridIndexer2<double> UE::Geometry::FShiftGridIndexer2d
Definition at line 122 of file GridIndexing2.h.
FShiftGridIndexer2f
typedef TShiftGridIndexer2<float> UE::Geometry::FShiftGridIndexer2f
Definition at line 121 of file GridIndexing2.h.
FShiftGridIndexer3d
typedef TShiftGridIndexer3<double> UE::Geometry::FShiftGridIndexer3d
Definition at line 107 of file GridIndexing3.h.
FShiftGridIndexer3f
typedef TShiftGridIndexer3<float> UE::Geometry::FShiftGridIndexer3f
Definition at line 106 of file GridIndexing3.h.
FSkeletalImplicitLine3d
typedef TSkeletalImplicitLine3<double> UE::Geometry::FSkeletalImplicitLine3d
Definition at line 121 of file ImplicitFunctions.h.
FSkeletalImplicitLine3f
typedef TSkeletalImplicitLine3<float> UE::Geometry::FSkeletalImplicitLine3f
Definition at line 120 of file ImplicitFunctions.h.
FSpatialPhoto1f
typedef TSpatialPhoto<float> UE::Geometry::FSpatialPhoto1f
Definition at line 69 of file SpatialPhotoSet.h.
FSpatialPhoto3f
typedef TSpatialPhoto<FVector3f> UE::Geometry::FSpatialPhoto3f
Definition at line 68 of file SpatialPhotoSet.h.
FSpatialPhoto4f
typedef TSpatialPhoto<FVector4f> UE::Geometry::FSpatialPhoto4f
Definition at line 67 of file SpatialPhotoSet.h.
FSpatialPhotoSet1f
typedef TSpatialPhotoSet<float, float> UE::Geometry::FSpatialPhotoSet1f
Definition at line 144 of file SpatialPhotoSet.h.
FSpatialPhotoSet3f
typedef TSpatialPhotoSet<FVector3f, float> UE::Geometry::FSpatialPhotoSet3f
Definition at line 143 of file SpatialPhotoSet.h.
FSpatialPhotoSet4f
typedef TSpatialPhotoSet<FVector4f, float> UE::Geometry::FSpatialPhotoSet4f
Definition at line 142 of file SpatialPhotoSet.h.
FSphere3d
typedef TSphere3<double> UE::Geometry::FSphere3d
Definition at line 108 of file SphereTypes.h.
FSphere3f
typedef TSphere3<float> UE::Geometry::FSphere3f
Definition at line 107 of file SphereTypes.h.
FTetrahedron3d
typedef TTetrahedron3<double> UE::Geometry::FTetrahedron3d
Definition at line 419 of file TriangleTypes.h.
FTetrahedron3f
typedef TTetrahedron3<float> UE::Geometry::FTetrahedron3f
Definition at line 418 of file TriangleTypes.h.
FTransformSequence3d
typedef TTransformSequence3<double> UE::Geometry::FTransformSequence3d
Definition at line 231 of file TransformSequence.h.
FTransformSequence3f
typedef TTransformSequence3<float> UE::Geometry::FTransformSequence3f
Definition at line 230 of file TransformSequence.h.
FTransformSRT3d
typedef TTransformSRT3<double> UE::Geometry::FTransformSRT3d
Definition at line 422 of file TransformTypes.h.
FTransformSRT3f
typedef TTransformSRT3<float> UE::Geometry::FTransformSRT3f
Definition at line 421 of file TransformTypes.h.
FTriangle2d
typedef TTriangle2<double> UE::Geometry::FTriangle2d
Definition at line 254 of file TriangleTypes.h.
FTriangle2f
typedef TTriangle2<float> UE::Geometry::FTriangle2f
Definition at line 253 of file TriangleTypes.h.
FTriangle3d
typedef TTriangle3<double> UE::Geometry::FTriangle3d
Definition at line 325 of file TriangleTypes.h.
FTriangle3f
typedef TTriangle3<float> UE::Geometry::FTriangle3f
Definition at line 324 of file TriangleTypes.h.
FTriangle3i
typedef TTriangle3<int> UE::Geometry::FTriangle3i
Definition at line 326 of file TriangleTypes.h.
FTriangleMeshAdapterd
typedef TTriangleMeshAdapter<double> UE::Geometry::FTriangleMeshAdapterd
Definition at line 44 of file MeshAdapter.h.
FTriangleMeshAdapterf
typedef TTriangleMeshAdapter<float> UE::Geometry::FTriangleMeshAdapterf
Definition at line 45 of file MeshAdapter.h.
FUnionGeneralPolygon2GeneralPolygon2d
typedef TUnionPolygon2Polygon2<TGeneralPolygon2<double>, double> UE::Geometry::FUnionGeneralPolygon2GeneralPolygon2d
Definition at line 48 of file PolygonIntersectionUtils.h.
FUnionGeneralPolygon2GeneralPolygon2f
typedef TUnionPolygon2Polygon2<TGeneralPolygon2<float>, float> UE::Geometry::FUnionGeneralPolygon2GeneralPolygon2f
Definition at line 47 of file PolygonIntersectionUtils.h.
FVectorSetAnalysis3d
typedef TVectorSetAnalysis3<double> UE::Geometry::FVectorSetAnalysis3d
Definition at line 109 of file VectorSetAnalysis.h.
FVectorSetAnalysis3f
typedef TVectorSetAnalysis3<float> UE::Geometry::FVectorSetAnalysis3f
Definition at line 108 of file VectorSetAnalysis.h.
FVolPresMeshSimplification
typedef TMeshSimplification< FVolPresQuadricErrord > UE::Geometry::FVolPresMeshSimplification
Definition at line 437 of file MeshSimplification.h.
FVolPresQuadricErrord
typedef TVolPresQuadricError<double> UE::Geometry::FVolPresQuadricErrord
Definition at line 412 of file QuadricError.h.
FVolPresQuadricErrorf
typedef TVolPresQuadricError<float> UE::Geometry::FVolPresQuadricErrorf
Definition at line 411 of file QuadricError.h.
FWatertightRay3d
typedef TWatertightRay3<double> UE::Geometry::FWatertightRay3d
Definition at line 317 of file IntrRay3Triangle3.h.
FWatertightRay3f
typedef TWatertightRay3<float> UE::Geometry::FWatertightRay3f
Definition at line 316 of file IntrRay3Triangle3.h.
FWeightedSamplingAliasTabled
using UE::Geometry::FWeightedSamplingAliasTabled = TWeightedSamplingAliasTable<double>
Definition at line 144 of file MeshSurfacePointSampling.h.
FWeightedSamplingAliasTablef
using UE::Geometry::FWeightedSamplingAliasTablef = TWeightedSamplingAliasTable<float>
Definition at line 145 of file MeshSurfacePointSampling.h.
TBooleanGeneralPolygon2GeneralPolygon2d
template<EPolygonBooleanOp OperationType> using UE::Geometry::TBooleanGeneralPolygon2GeneralPolygon2d = TBooleanPolygon2Polygon2<OperationType, TGeneralPolygon2<double>, double>
Definition at line 41 of file PolygonIntersectionUtils.h.
TBooleanGeneralPolygon2GeneralPolygon2f
template<EPolygonBooleanOp OperationType> using UE::Geometry::TBooleanGeneralPolygon2GeneralPolygon2f = TBooleanPolygon2Polygon2<OperationType, TGeneralPolygon2<float>, float>
Definition at line 38 of file PolygonIntersectionUtils.h.
TDifferencePolygon2Polygon2
template<typename GeometryType, typename RealType> using UE::Geometry::TDifferencePolygon2Polygon2 = TBooleanPolygon2Polygon2<EPolygonBooleanOp::Difference, GeometryType, RealType>
Produces the result of PolygonA with the shape of PolygonB removed.
Both must be closed.
Definition at line 52 of file PolygonIntersectionUtils.h.
TDiscreteKernel2d
typedef TDiscreteKernel2<double> UE::Geometry::TDiscreteKernel2d
Definition at line 76 of file Gaussians.h.
TDiscreteKernel2f
typedef TDiscreteKernel2<float> UE::Geometry::TDiscreteKernel2f
Definition at line 75 of file Gaussians.h.
TDynamicMeshVertexAttribute
template<typename AttribValueType, int AttribDimension> using UE::Geometry::TDynamicMeshVertexAttribute = TDynamicVertexAttribute<AttribValueType, AttribDimension, FDynamicMesh3>
Definition at line 589 of file DynamicVertexAttribute.h.
TDynamicVector2d
using UE::Geometry::TDynamicVector2d = TDynamicVectorN<double, 2>
Definition at line 568 of file DynamicVector.h.
TDynamicVector2f
using UE::Geometry::TDynamicVector2f = TDynamicVectorN<float, 2>
Definition at line 566 of file DynamicVector.h.
TDynamicVector2i
using UE::Geometry::TDynamicVector2i = TDynamicVectorN<int, 2>
Definition at line 570 of file DynamicVector.h.
TDynamicVector3d
using UE::Geometry::TDynamicVector3d = TDynamicVectorN<double, 3>
Definition at line 567 of file DynamicVector.h.
TDynamicVector3f
using UE::Geometry::TDynamicVector3f = TDynamicVectorN<float, 3>
Definition at line 565 of file DynamicVector.h.
TDynamicVector3i
using UE::Geometry::TDynamicVector3i = TDynamicVectorN<int, 3>
Definition at line 569 of file DynamicVector.h.
TExclusiveOrPolygon2Polygon2
template<typename GeometryType, typename RealType> using UE::Geometry::TExclusiveOrPolygon2Polygon2 = TBooleanPolygon2Polygon2<EPolygonBooleanOp::ExclusiveOr, GeometryType, RealType>
Produces the areas of each polygon not present in the other as a combined result.
Both must be closed.
Definition at line 66 of file PolygonIntersectionUtils.h.
TGaussian1d
typedef TGaussian1<double> UE::Geometry::TGaussian1d
Definition at line 52 of file Gaussians.h.
TGaussian1f
typedef TGaussian1<float> UE::Geometry::TGaussian1f
Definition at line 51 of file Gaussians.h.
TGaussian2d
typedef TGaussian2<double> UE::Geometry::TGaussian2d
Definition at line 157 of file Gaussians.h.
TGaussian2f
typedef TGaussian2<float> UE::Geometry::TGaussian2f
Definition at line 156 of file Gaussians.h.
TGaussian3d
typedef TGaussian3<double> UE::Geometry::TGaussian3d
Definition at line 186 of file Gaussians.h.
TGaussian3f
typedef TGaussian3<float> UE::Geometry::TGaussian3f
Definition at line 185 of file Gaussians.h.
TIntersectPolygon2Polygon2
template<typename GeometryType, typename RealType> using UE::Geometry::TIntersectPolygon2Polygon2 = TBooleanPolygon2Polygon2<EPolygonBooleanOp::Intersect, GeometryType, RealType>
Produces the areas of each polygon that are also present in the other as a combined result.
Both must be closed.
Definition at line 59 of file PolygonIntersectionUtils.h.
TPointHashGrid2d
template<typename PointDataType> using UE::Geometry::TPointHashGrid2d = TPointHashGrid2<PointDataType, double>
Definition at line 221 of file PointHashGrid2.h.
TPointHashGrid2f
template<typename PointDataType> using UE::Geometry::TPointHashGrid2f = TPointHashGrid2<PointDataType, float>
Definition at line 222 of file PointHashGrid2.h.
TPointHashGrid3d
template<typename PointDataType> using UE::Geometry::TPointHashGrid3d = TPointHashGrid3<PointDataType, double>
Definition at line 444 of file PointHashGrid3.h.
TPointHashGrid3f
template<typename PointDataType> using UE::Geometry::TPointHashGrid3f = TPointHashGrid3<PointDataType, float>
Definition at line 445 of file PointHashGrid3.h.
TPolyline2
template<typename T> using UE::Geometry::TPolyline2 = TPolyline<T, 2>
Definition at line 13 of file Polyline2.h.
TPolyline3
template<typename T> using UE::Geometry::TPolyline3 = TPolyline<T, 3>
Definition at line 13 of file Polyline3.h.
TUnionPolygon2Polygon2
template<typename GeometryType, typename RealType> using UE::Geometry::TUnionPolygon2Polygon2 = TBooleanPolygon2Polygon2<EPolygonBooleanOp::Union, GeometryType, RealType>
Produces the combined result of PolygonA and PolygonB.
Both must be closed.
Definition at line 45 of file PolygonIntersectionUtils.h.
Enumeration Type Documentation
EActorMeshComponentType
enum class UE::Geometry::EActorMeshComponentType strong
EActorMeshComponentType enum is used to determine which type of Component an FActorChildMesh represents.
Enumerator
StaticMesh
InstancedStaticMesh
HierarchicalInstancedStaticMesh
InternallyGeneratedComponent
Unknown
Definition at line 195 of file MeshSceneAdapter.h.
EBackgroundComputeTaskStatus
enum class UE::Geometry::EBackgroundComputeTaskStatus strong
This status is returned by TBackgroundModelingComputeSource to indicate what state a background computation is in.
Enumerator
ValidResultAvailable
Computation of a result has finished and is waiting to be returned.
DirtyResultAvailable
We have a result available, but a recompute has been requested.
The status is not yet InProgress only because there is a delay of CancelActiveOpDelaySeconds between the request and operation restart, and we have not yet restarted.
Aborted
Last active computation was canceled and nothing new has happend yet.
InProgress
Computation is currently running.
NotComputing
Not running active computation, and last result has already been returned, so no new results to report.
Definition at line 75 of file BackgroundModelingComputeSource.h.
EBCSplineType
enum class UE::Geometry::EBCSplineType strong
Enumerator
BSpline
CatmullRom
MitchellNetravali
Definition at line 13 of file BCSplineFilter.h.
EBox2FitCriteria
enum UE::Geometry::EBox2FitCriteria
Enumerator
Area
Perimeter
Definition at line 15 of file FitOrientedBox2.h.
EBox3FitCriteria
enum UE::Geometry::EBox3FitCriteria
Enumerator
Volume
SurfaceArea
Definition at line 17 of file FitOrientedBox3.h.
ECapType
enum class UE::Geometry::ECapType strong
ECapType indicates the type of cap to use on a sweep.
Enumerator
None
FlatTriangulation
FlatMidpointFan
Definition at line 40 of file SweepGenerator.h.
EComponentCollisionSupportLevel
enum UE::Geometry::EComponentCollisionSupportLevel
Enumerator
ReadOnly
ReadWrite
Definition at line 33 of file ComponentCollisionUtil.h.
EConvexErrorMethod
enum class UE::Geometry::EConvexErrorMethod strong
Enumerator
RelativeVolume
Definition at line 29 of file ConvexDecomposition3.h.
EDetectedSimpleShapeType
enum class UE::Geometry::EDetectedSimpleShapeType strong
EDetectedSimpleShapeType is used to identify auto-detected simple shapes for a mesh/etc.
Enumerator
None
Object is not a simple shape.
Sphere
Object has been identified as a sphere.
Box
Object has been identified as a box.
Capsule
Object has been identified as a capsule.
Convex
Object has been identified as a Convex.
Definition at line 19 of file MeshSimpleShapeApproximation.h.
EDiTO
enum UE::Geometry::EDiTO
selects the number of extremal vertices and directional vector family for the DiTO - K algorithm, with implementations for K = {12, 14, 20, 26}
Enumerator
DiTO_12
DiTO_14
DiTO_20
DiTO_26
Definition at line 24 of file DiTOrientedBox.h.
EEdgeRefineFlags
enum class UE::Geometry::EEdgeRefineFlags strong
EEdgeRefineFlags indicate constraints on triangle mesh edges.
Enumerator
NoConstraint
Edge is unconstrained.
NoFlip
Edge cannot be flipped.
NoSplit
Edge cannot be split.
NoCollapse
Edge cannot be collapsed.
FullyConstrained
Edge cannot be flipped, split, or collapsed.
SplitsOnly
Edge can only be split.
FlipOnly
Edge can only flip.
CollapseOnly
Edge can only collapse.
Definition at line 18 of file MeshConstraints.h.
EEnumerateSelectionConversionParams
enum class UE::Geometry::EEnumerateSelectionConversionParams strong
Enumerator
ContainSelection
Converts to components whose constituent parts are all contained in the initial selection.
ExpandSelection
Converts to components where any of its constituent parts are included in the initial selection.
Definition at line 33 of file GeometrySelectionUtil.h.
EEnumerateSelectionMapping
enum class UE::Geometry::EEnumerateSelectionMapping : uint8 strong
Enumerator
None
FacesToFaces
FacesToEdges
Default
Definition at line 22 of file GeometrySelectionUtil.h.
EFBMMode
enum class UE::Geometry::EFBMMode : uint8 strong
Enumerator
Standard
Classic Perlin Noise.
Turbulent
Turbulent Modifier, creating upward bumps.
Ridge
Ridge Modifier, creating sharper creases and ridges.
Definition at line 13 of file ProceduralNoise.h.
EGeometryElementType
enum class UE::Geometry::EGeometryElementType strong
Type of selected Elements in a FGeometrySelection.
Enumerator
Vertex
Mesh Vertices, Polygroup Corners, ...
Edge
Mesh Edges, Polygroup Edges, ...
Face
Mesh Triangles, Polygroup Faces, ...
Definition at line 114 of file GeometrySelection.h.
EGeometryPointType
enum class UE::Geometry::EGeometryPointType strong
Enumerator
Triangle
Edge
Vertex
Definition at line 28 of file SceneGeometrySpatialCache.h.
EGeometryResultType
enum class UE::Geometry::EGeometryResultType strong
EGeometryResultType is a generic result-code for use by geometry operations.
Enumerator
Success
The Geometry Operation successfully completed.
InProgress
The Geometry Operation is in progress (this is intended for use in cases where there is a background computation that can be queried for incremental status/etc)
Cancelled
The Geometry Operation was Cancelled and did not complete.
PartialResult
The Geometry Operation completed but was not fully successful (eg some sub-computation failed and was gracefully handled, etc)
Failure
The Geometry Operation failed and no valid result was produced.
Definition at line 79 of file ProgressCancel.h.
EGeometrySelectionChangeType
enum class UE::Geometry::EGeometrySelectionChangeType strong
Type of change, relative to a FGeometrySelection.
Enumerator
Add
Elements Added to Selection.
Remove
Elements Removed from Selection.
Replace
Selected Elements replaced with a new set of Selected Elements.
Definition at line 230 of file GeometrySelection.h.
EGeometrySelectionCombineModes
enum class UE::Geometry::EGeometrySelectionCombineModes : uint8 strong
Enumerator
Add
Subtract
Intersection
Definition at line 546 of file GeometrySelectionUtil.h.
EGeometryTopologyType
enum class UE::Geometry::EGeometryTopologyType strong
Type of selected Topology in a FGeometrySelection.
Enumerator
Triangle
Polygroup
Definition at line 127 of file GeometrySelection.h.
EImageTilingMethod
enum class UE::Geometry::EImageTilingMethod strong
Enumerator
Clamp
Wrap
Definition at line 15 of file ImageBuilder.h.
ELatticeInterpolation
enum class UE::Geometry::ELatticeInterpolation : uint8 strong
Enumerator
Linear
Cubic
Definition at line 22 of file FFDLattice.h.
ELocalParamTypes
enum class UE::Geometry::ELocalParamTypes : uint8 strong
Type of local parameterization.
Enumerator
PlanarProjection
Calculate a planar projection.
ExponentialMap
Calculate Discrete Exponential Map.
ExponentialMapUpwindAvg
Calculate Discrete Exponential Map with Upwind-Averaging.
Definition at line 21 of file MeshLocalParam.h.
EMeshAttributeTransferError
enum class UE::Geometry::EMeshAttributeTransferError strong
Enumerator
InvalidSource
InvalidTarget
SourceMissingAttribute
TargetMissingAttribute
InvalidOperationForInputs
Definition at line 23 of file MeshAttributeTransfer.h.
EMeshAttributeTransferType
enum class UE::Geometry::EMeshAttributeTransferType strong
Enumerator
MaterialID
Definition at line 18 of file MeshAttributeTransfer.h.
EMeshComponents
enum class UE::Geometry::EMeshComponents : uint8 strong
Enumerator
None
VertexNormals
VertexColors
VertexUVs
FaceGroups
All
Definition at line 48 of file DynamicMesh3.h.
EMeshMapEvaluatorType
enum class UE::Geometry::EMeshMapEvaluatorType strong
Enumerator
Constant
Normal
Occlusion
Curvature
Property
ResampleImage
MultiResampleImage
RenderCapture
UVShell
Height
Definition at line 14 of file MeshMapEvaluator.h.
EMeshOcclusionMapType
enum class UE::Geometry::EMeshOcclusionMapType : uint8 strong
Enumerator
None
AmbientOcclusion
BentNormal
All
Definition at line 19 of file MeshOcclusionMapEvaluator.h.
EMeshPropertyBakeType
enum class UE::Geometry::EMeshPropertyBakeType strong
Enumerator
Position
Normal
FacetNormal
UVPosition
MaterialID
Definition at line 17 of file MeshPropertyMapBaker.h.
EMeshPropertyMapType
enum class UE::Geometry::EMeshPropertyMapType strong
Enumerator
Position
Normal
FacetNormal
UVPosition
MaterialID
VertexColor
PolyGroupID
Definition at line 18 of file MeshPropertyMapEvaluator.h.
EMeshResult
enum class UE::Geometry::EMeshResult strong
EMeshResult is returned by various mesh/graph operations to either indicate success, or communicate which type of error ocurred (some errors are recoverable, and some not).
Enumerator
Ok
Failed_NotAVertex
Failed_NotATriangle
Failed_NotAnEdge
Failed_BrokenTopology
Failed_HitValenceLimit
Failed_IsBoundaryEdge
Failed_FlippedEdgeExists
Failed_IsBowtieVertex
Failed_InvalidNeighbourhood
Failed_FoundDuplicateTriangle
Failed_CollapseTetrahedron
Failed_CollapseTriangle
Failed_NotABoundaryEdge
Failed_SameOrientation
Failed_CollapseQuad
Failed_WouldCreateBowtie
Failed_VertexAlreadyExists
Failed_CannotAllocateVertex
Failed_VertexStillReferenced
Failed_WouldCreateNonmanifoldEdge
Failed_TriangleAlreadyExists
Failed_CannotAllocateTriangle
Failed_UnrecoverableError
Failed_Unsupported
Definition at line 17 of file GeometryTypes.h.
EMeshSurfaceSamplerQueryType
enum class UE::Geometry::EMeshSurfaceSamplerQueryType : uint8 strong
Types of query that FMeshSurfaceUVSampler/TMeshSurfaceUVSampler supports.
Enumerator
UVOnly
Query with arbitrary UV value.
TriangleAndUV
Query with given TriangleID and UV that is assumed to lie within that Triangle.
Definition at line 108 of file MeshSurfaceSampler.h.
EOcclusionCalculationMode
enum class UE::Geometry::EOcclusionCalculationMode strong
Enumerator
FastWindingNumber
SimpleOcclusionTest
Definition at line 37 of file RemoveOccludedTriangles.h.
EOcclusionMapType
enum class UE::Geometry::EOcclusionMapType : uint8 strong
Enumerator
None
AmbientOcclusion
BentNormal
All
Definition at line 16 of file MeshOcclusionMapBaker.h.
EOcclusionTriangleSampling
enum class UE::Geometry::EOcclusionTriangleSampling strong
Enumerator
Centroids
Vertices
VerticesAndCentroids
Definition at line 30 of file RemoveOccludedTriangles.h.
EOperationValidationResult
enum class UE::Geometry::EOperationValidationResult strong
EOperationValidationResult is meant to be returned by Validate() functions of Operation classes (eg like ExtrudeMesh, etc) to indicate whether the operation can be successfully applied.
Enumerator
Ok
Failed_UnknownReason
Failed_InvalidTopology
Definition at line 58 of file GeometryTypes.h.
EPolygonBooleanOp
enum class UE::Geometry::EPolygonBooleanOp : uint8 strong
Enumerator
Union
Difference
Intersect
ExclusiveOr
Definition at line 10 of file PolygonIntersectionUtils.h.
EPolygonOffsetEndType
enum class UE::Geometry::EPolygonOffsetEndType : uint8 strong
Enumerator
Polygon
Joined
Butt
Square
Round
Definition at line 17 of file PolygonOffsetUtils.h.
EPolygonOffsetJoinType
enum class UE::Geometry::EPolygonOffsetJoinType : uint8 strong
Enumerator
Square
Round
Miter
Definition at line 10 of file PolygonOffsetUtils.h.
EProfileSweepPolygonGrouping
enum class UE::Geometry::EProfileSweepPolygonGrouping : uint8 strong
Enumerator
Single
One polygroup for entire output mesh.
PerFace
One polygroup per mesh quad/triangle.
PerSweepSegment
PerProfileSegment
Definition at line 935 of file SweepGenerator.h.
EProfileSweepQuadSplit
enum class UE::Geometry::EProfileSweepQuadSplit : uint8 strong
Enumerator
Uniform
Always split the quad in the same way relative sweep direction and profile direction.
ShortestDiagonal
Split the quad to connect the shortest diagonal.
Definition at line 948 of file SweepGenerator.h.
ERecomputeUVsIslandMode
enum class UE::Geometry::ERecomputeUVsIslandMode strong
Enumerator
PolyGroups
UVIslands
Definition at line 33 of file RecomputeUVsOp.h.
ERecomputeUVsUnwrapType
enum class UE::Geometry::ERecomputeUVsUnwrapType strong
Enumerator
ExpMap
ConformalFreeBoundary
SpectralConformal
Definition at line 24 of file RecomputeUVsOp.h.
ERenderCaptureChannel
enum class UE::Geometry::ERenderCaptureChannel strong
Enumerator
BaseColor
Roughness
Metallic
Specular
Emissive
WorldNormal
DeviceDepth
CombinedMRS
Opacity
SubsurfaceColor
Definition at line 13 of file RenderCaptureMapEvaluator.h.
ERenderCaptureType
enum class UE::Geometry::ERenderCaptureType strong
ERenderCaptureType defines which type of render buffer should be captured.
Enumerator
BaseColor
Roughness
Metallic
Specular
Emissive
WorldNormal
DeviceDepth
CombinedMRS
Opacity
SubsurfaceColor
Definition at line 21 of file WorldRenderCapture.h.
ERootfindingModes
enum class UE::Geometry::ERootfindingModes strong
Enumerator
SingleLerp
LerpSteps
Bisection
Definition at line 43 of file MarchingCubes.h.
ERoundedRectangleCorner
enum class UE::Geometry::ERoundedRectangleCorner : uint8 strong
Enumerator
None
BottomLeft
BottomRight
TopLeft
TopRight
All
Definition at line 64 of file RectangleMeshGenerator.h.
ESceneMeshType
enum class UE::Geometry::ESceneMeshType strong
ESceneMeshType is used to indicate which type of Mesh a FMeshTypeContainer contains.
Enumerator
StaticMeshAsset
Unknown
Definition at line 27 of file MeshSceneAdapter.h.
ESimpleShapeType
enum class UE::Geometry::ESimpleShapeType strong
Supported/known types of Simple Shapes.
Enumerator
Sphere
Box
Capsule
Convex
LevelSet
Definition at line 26 of file SimpleShapeSet3.h.
ESimplificationResult
enum class UE::Geometry::ESimplificationResult strong
Enumerator
Ok_Collapsed
Ignored_CannotCollapse
Ignored_EdgeIsFullyConstrained
Ignored_EdgeTooLong
Ignored_Constrained
Ignored_CreatesFlip
Failed_OpNotSuccessful
Failed_NotAnEdge
Failed_IsolatedTriangle
Failed_GeometricDeviation
Ignored_CreatesTinyTriangle
Definition at line 19 of file MeshSimplification.h.
ESkinBindingType
enum class UE::Geometry::ESkinBindingType : uint8 strong
Enumerator
DirectDistance
GeodesicVoxel
Definition at line 22 of file SkinBindingOp.h.
ESurfacePointType
enum class UE::Geometry::ESurfacePointType strong
Enumerator
Vertex
Edge
Triangle
Definition at line 23 of file EmbedSurfacePath.h.
EUVEditorAlignAnchorBackend
enum class UE::Geometry::EUVEditorAlignAnchorBackend strong
Enumerator
UDIMTile
BoundingBox
Manual
Definition at line 301 of file UVEditorUVTransformOp.h.
EUVEditorAlignDirectionBackend
enum class UE::Geometry::EUVEditorAlignDirectionBackend strong
Enumerator
None
Top
Bottom
Left
Right
CenterVertically
CenterHorizontally
Definition at line 290 of file UVEditorUVTransformOp.h.
EUVEditorAlignDistributeGroupingModeBackend
enum class UE::Geometry::EUVEditorAlignDistributeGroupingModeBackend strong
Enumerator
IndividualBoundingBoxes
EnclosingBoundingBox
IndividualVertices
Definition at line 323 of file UVEditorUVTransformOp.h.
EUVEditorDistributeModeBackend
enum class UE::Geometry::EUVEditorDistributeModeBackend strong
Enumerator
None
LeftEdges
RightEdges
TopEdges
BottomEdges
CentersVertically
CentersHorizontally
VerticalSpace
HorizontalSpace
MinimallyRemoveOverlap
Definition at line 309 of file UVEditorUVTransformOp.h.
EUVEditorPivotTypeBackend
enum class UE::Geometry::EUVEditorPivotTypeBackend strong
Enumerator
Origin
IndividualBoundingBoxCenter
BoundingBoxCenter
Manual
Definition at line 275 of file UVEditorUVTransformOp.h.
EUVEditorTranslationModeBackend
enum class UE::Geometry::EUVEditorTranslationModeBackend strong
Enumerator
Relative
Absolute
Definition at line 284 of file UVEditorUVTransformOp.h.
EUVEditorUVTransformTypeBackend
enum class UE::Geometry::EUVEditorUVTransformTypeBackend strong
Enumerator
Transform
Align
Distribute
Definition at line 268 of file UVEditorUVTransformOp.h.
EUVLayoutOpLayoutModes
enum class UE::Geometry::EUVLayoutOpLayoutModes strong
Enumerator
TransformOnly
RepackToUnitRect
StackInUnitRect
Normalize
Definition at line 22 of file UVLayoutOp.h.
EUVTexelDensityOpModes
enum class UE::Geometry::EUVTexelDensityOpModes strong
Enumerator
ScaleGlobal
ScaleIslands
Normalize
Definition at line 56 of file TexelDensityOp.h.
EValidityCheckFailMode
enum class UE::Geometry::EValidityCheckFailMode strong
EValidityCheckFailMode is passed to CheckValidity() functions of various classes to specify how validity checks should fail.
Enumerator
ReturnOnly
Function returns false if a failure is encountered.
Check
Function check()'s if a failure is encountered.
Ensure
Function ensure()'s if a failure is encountered.
Definition at line 71 of file GeometryTypes.h.
Function Documentation
AdvanceIterator() [1/2]
template<typename IterT> IterT UE::Geometry::AdvanceIterator (IterT Start, int64 N)
Definition at line 120 of file ParallelTransformReduce.h.
Referenced by ParallelTransformReduce(), and ParallelTransformReduce().
AdvanceIterator() [2/2]
template<typename ContainerType, typename ElementType, typename SizeType> TIndexedContainerIterator< ContainerType, ElementType, SizeType > UE::Geometry::AdvanceIterator (TIndexedContainerIterator< ContainerType, ElementType, SizeType > Begin, SizeType N)
Definition at line 139 of file ParallelTransformReduce.h.
AngleD() [1/2]
template<typename T> T UE::Geometry::AngleD (const UE::Math::TVector2< T > & V1, const UE::Math::TVector2< T > & V2)
Definition at line 92 of file VectorTypes.h.
References TMathUtil< RealType >::ACos(), and UE::Math::TVector2< T >::Dot().
Referenced by UE::Geometry::TPolygon2< double >::Chamfer(), UE::Geometry::FDynamicGraph2< double >::OpeningAngle(), UE::Geometry::VectorUtil::OpeningAngleD(), UE::Geometry::TPolygon2< double >::OpeningAngleDeg(), and UE::Geometry::VectorUtil::PlaneAngleSignedD().
AngleD() [2/2]
template<typename T> T UE::Geometry::AngleD (const UE::Math::TVector< T > & V1, const UE::Math::TVector< T > & V2)
Computes the Angle between V1 and V2, assuming they are already normalized.
Returns
the (positive) angle between V1 and V2 in degrees
Definition at line 242 of file VectorTypes.h.
References TMathUtil< RealType >::ACos(), and UE::Math::TVector< T >::Dot().
AngleR() [1/2]
template<typename T> T UE::Geometry::AngleR (const UE::Math::TVector2< T > & V1, const UE::Math::TVector2< T > & V2)
Definition at line 101 of file VectorTypes.h.
References TMathUtil< RealType >::ACos(), and UE::Math::TVector2< T >::Dot().
Referenced by AsZeroToTwoPi(), and UE::Geometry::VectorUtil::PlaneAngleSignedR().
AngleR() [2/2]
template<typename T> T UE::Geometry::AngleR (const UE::Math::TVector< T > & V1, const UE::Math::TVector< T > & V2)
Computes the Angle between V1 and V2, assuming they are already normalized.
Returns
the (positive) angle between V1 and V2 in radians
Definition at line 254 of file VectorTypes.h.
References TMathUtil< RealType >::ACos(), and UE::Math::TVector< T >::Dot().
AppendError() [1/2]
GEOMETRYSCRIPTINGCORE_API void UE::Geometry::AppendError (TArray< FGeometryScriptDebugMessage > * DebugMessages, EGeometryScriptErrorType ErrorTypeIn, const FText & MessageIn)
These variants of AppendError/Warning are for direct write to a debug message array.
This may be useful in cases where a function is async and needs to accumulate debug messages for later collation on a game thread.
References AppendError().
AppendError() [2/2]
GEOMETRYSCRIPTINGCORE_API void UE::Geometry::AppendError (UGeometryScriptDebug * Debug, EGeometryScriptErrorType ErrorTypeIn, const FText & MessageIn)
References AppendError().
Referenced by AppendError(), and AppendError().
AppendSimpleCollision() [1/2]
MODELINGCOMPONENTS_API bool UE::Geometry::AppendSimpleCollision (const UPrimitiveComponent * SourceComponent, FSimpleShapeSet3d * ShapeSetOut, const FTransform3d & Transform)
Apply Transform to the existing Simple Collision geometry in Component and then append to to ShapeSetOut.
References Transform.
AppendSimpleCollision() [2/2]
MODELINGCOMPONENTS_API bool UE::Geometry::AppendSimpleCollision (const UPrimitiveComponent * SourceComponent, FSimpleShapeSet3d * ShapeSetOut, const TArray< FTransform3d > & TransformSeqeuence)
Apply TransformSequence (in-order) to the existing Simple Collision geometry in Component and then append to to ShapeSetOut.
AppendWarning() [1/2]
GEOMETRYSCRIPTINGCORE_API void UE::Geometry::AppendWarning (TArray< FGeometryScriptDebugMessage > * DebugMessages, EGeometryScriptErrorType WarningTypeIn, const FText & MessageIn)
References AppendWarning().
AppendWarning() [2/2]
GEOMETRYSCRIPTINGCORE_API void UE::Geometry::AppendWarning (UGeometryScriptDebug * Debug, EGeometryScriptErrorType WarningTypeIn, const FText & MessageIn)
References AppendWarning().
Referenced by AppendWarning(), and AppendWarning().
AreSelectionsIdentical()
DYNAMICMESH_API bool UE::Geometry::AreSelectionsIdentical (const FGeometrySelection & SelectionA, const FGeometrySelection & SelectionB)
Test if SelectionA and SelectionB are the same selection.
This is currently relatively expensive on Polygroup selections due to how they are encoded
Returns
true if the selections are iddentical
AsZeroToTwoPi()
double UE::Geometry::AsZeroToTwoPi (double AngleR) static
return AngleR in [0,2pi) range.
The same polar point (r, AngleR) can be described by an infinite number of alternative angles, each offset by some multiple of 2pi, i.e. (r, AngleR + n * 2Pi). This selects the unique angle that falls in the [0,2pi) range.
Definition at line 366 of file MeshGeodesicSurfaceTracer.h.
References AngleR().
Blend3()
template<typename T> UE::Math::TVector< T > UE::Geometry::Blend3 (const UE::Math::TVector< T > & A, const UE::Math::TVector< T > & B, const UE::Math::TVector< T > & C, const T & WeightA, const T & WeightB, const T & WeightC)
Definition at line 365 of file VectorTypes.h.
References A, and B.
Referenced by UE::Geometry::TMeshTangents< float >::GetInterpolatedTriangleTangent().
BSplineCurveFit() [1/2]
bool GEOMETRYALGORITHMS_API UE::Geometry::BSplineCurveFit (const TArray< FVector2f > & DataPoints, const int32 SplineDegree, const int32 NumControlPoints, TArray< FVector2f > & ControlPointsOut)
Compute the control points that result from a best fit of the provided 2d data points when using b-splines of the specified degree.
This fit assumes the sample points are evenly spaced in 't' over the interval [0, 1]. and the knot vector has unique knots at j / (NumControlPoints - SplineDegree) for j in [0, (NumControlPoints - Degree)]. the knots at 0 and 1 each have multiplicity SplineDegree + 1, while the internal knots just have multiplicity 1.
Parameters
DataPoints - an array of 2d points the b-spline will attempt to fit
SplineDegree - the degree of the underling b-spline. Must be greater that 0.
NumControlPoints - requested number of control points solved for.
Note: requires SplineDegree < NumControlPoints <= DataPoints.Num()
ControlPointsOut - on successful return, an array of 2d control points of the specified length (on failure the array is unchanged).
Returns
true on success.
BSplineCurveFit() [2/2]
bool GEOMETRYALGORITHMS_API UE::Geometry::BSplineCurveFit (const TArray< FVector3f > & DataPoints, const int32 SplineDegree, const int32 NumControlPoints, TArray< FVector3f > & ControlPointsOut)
Compute the control points that result from a best fit of the provided 3d data points when using b-splines of the specified degree.
This fit assumes the sample points are evenly spaced in 't' over the interval [0, 1]. and the knot vector has unique knots at j / (NumControlPoints - SplineDegree) for j in [0, (NumControlPoints - Degree)]. the knots at 0 and 1 each have multiplicity SplineDegree + 1, while the internal knots just have multiplicity 1.
Parameters
DataPoints - an array of 3d points the b-spline will attempt to fit
SplineDegree - the degree of the underling b-spline. Must be greater that 0.
NumControlPoints - requested number of control points solved for. Note: requires SplineDegree < NumControlPoints <= DataPoints.Num()
ControlPointsOut - on successful return, an array of 3d control points of the specified length (on failure the array is unchanged).
Returns
true on success.
CollectVertexPositions()
template<typename EnumeratorType, typename SetType> void UE::Geometry::CollectVertexPositions (const FDynamicMesh3 & Mesh, EnumeratorType Enumeration, SetType & Output)
Call SetType.Add(VertexPosition) for all valid vertex indices in for_each(Enumeration)
Definition at line 112 of file MeshIndexUtil.h.
References Mesh.
CombineSelectionInPlace()
DYNAMICMESH_API bool UE::Geometry::CombineSelectionInPlace (FGeometrySelection & SelectionA, const FGeometrySelection & SelectionB, EGeometrySelectionCombineModes CombineMode)
Combine the elements of SelectionA and SelectionB using the provided CombineMode, and store the result in SelectionA.
Returns
true if the selectins were compatible (ie both the same type) and of supported geometry/topology type.
CommitDynamicMeshViaMeshDescription()
MODELINGCOMPONENTS_API void UE::Geometry::CommitDynamicMeshViaMeshDescription (FMeshDescription && CurrentMeshDescription, IMeshDescriptionCommitter & MeshDescriptionCommitter, const UE::Geometry::FDynamicMesh3 & Mesh, const IDynamicMeshCommitter::FDynamicMeshCommitInfo & CommitInfo)
References CommitDynamicMeshViaMeshDescription(), and Mesh.
Referenced by CommitDynamicMeshViaMeshDescription().
CompactAttributeValues()
GEOMETRYCORE_API bool UE::Geometry::CompactAttributeValues (const FDynamicMesh3 & Mesh, TDynamicMeshScalarTriangleAttribute< int32 > & TriangleAttrib, FInterval1i & OldMaxAttributeRangeOut, int & NewMaxAttributeValueOut, TArray< int32 > & OldToNewMapOut, TArray< int32 > & NewToOldMapOut, bool & bWasCompactOut)
Compact the values of an integer Triangle Attribute, ie so that the attribute values are dense in range 0..N.
Useful for (eg) compacting MaterialIDs or Polygroups. Note that this function cannot tell if values were removed from the "end" of the attribute value list. Some care must be taken in calling code to handle this case if using this function to determine whether compaction of other data structures is needed. Currently OldToNewMapOut and NewToOldMapOut are always populated even if the input is compact.
Parameters
OldMaxAttributeRangeOut min and max input attribute values, ie pre-compaction
NewMaxAttributeValueOut new max attribute value after compacting.
OldToNewMapOut generated mapping from previous IDs to new IDs (ie size is maximum input attrib value (+1), will contain InvalidID for any compacted values)
NewToOldMapOut generated mapping from new IDs to previous IDs (ie size is maximum output attribute value (+1), no invalid values)
bWasCompactOut set to true if the attribute set was already compact, IE was not modified by the operation
Returns
true on success (including if already compact). false if any Attribute Values were negative/InvalidID, cannot compact in this case
References Mesh.
ComponentTypeSupportsCollision()
MODELINGCOMPONENTS_API bool UE::Geometry::ComponentTypeSupportsCollision (const UPrimitiveComponent * Component, EComponentCollisionSupportLevel SupportLevel = EComponentCollisionSupportLevel::ReadWrite)
Returns
true if the component type supports collision settings
References Component, and ReadWrite.
ComputeArbitraryTrianglePatchUVs()
DYNAMICMESH_API void UE::Geometry::ComputeArbitraryTrianglePatchUVs (FDynamicMesh3 & Mesh, FDynamicMeshUVOverlay & UVOverlay, const TArray< int32 > & TriangleSet)
Create a new single UV island for the provided TriangleSet in the given Mesh/UVOverlay, by computing an ExpMap parameterization based on an automatically-detected midpoint of the triangle patch.
The UV scale is determined automatically based on the UV/3D area ratio of triangles adjacent to the TriangleSet (using a ratio of 1 if the triangles have no neighbours).
Parameters
TriangleSet a list of triangles, must be a single connected component
References Mesh.
ComputeAverageUVScaleRatioAlongVertexPath()
DYNAMICMESH_API double UE::Geometry::ComputeAverageUVScaleRatioAlongVertexPath (const FDynamicMesh3 & Mesh, const FDynamicMeshUVOverlay & UVOverlay, const TArray< int32 > & VertexPath, double * PathLengthOut = nullptr, double * UVPathLengthOut = nullptr)
Compute the total UVLength/MeshLength ratio along the given VertexPath.
Other 3D lengths can then be scaled to comparable UV-space lengths by multiplying by this value. Edges must exist between the vertices along the path, and loops are not considered. Each UV edge for a 3D edge is considered, ie if a 3D edge corresponds to 2 UV edges, both are counted, and if the 3D edge has no UV edges, it is skipped.
Parameters
VertexPath list of vertices which are connected by edges
PathLengthOut optional output param for sum of 3D edge lengths along path (arc length)
UVPathLengthOut optional output param for sum of UV edge lengths along path
Returns
UVPathLength / PathLength, or 1.0 if no valid UV edges along the path existed
References Mesh.
ComputeBoundsFromTriangleROI()
FAxisAlignedBox3d MODELINGCOMPONENTS_API UE::Geometry::ComputeBoundsFromTriangleROI (const FDynamicMesh3 & Mesh, const TArray< int32 > & TriangleROI, const FTransform3d * Transform = nullptr)
Computes the axis aligned bounding box from a given triangle region of interest, useful to compute a DepthBias.
References Mesh, and Transform.
ComputeBoundsFromVertexROI()
FAxisAlignedBox3d MODELINGCOMPONENTS_API UE::Geometry::ComputeBoundsFromVertexROI (const FDynamicMesh3 & Mesh, const TArray< int32 > & VertexROI, const FTransform3d * Transform = nullptr)
Computes the axis aligned bounding box from a given vertex region of interest, useful to compute a DepthBias.
References Mesh, and Transform.
ComputeFaceSelectionFrame()
DYNAMICMESH_API FFrame3d UE::Geometry::ComputeFaceSelectionFrame (const FDynamicMesh3 & Mesh, const TArray< int32 > & Triangles, bool bIsDefinitelySingleComponent = false)
Try to compute a good "Frame" for the selected Triangles of the Mesh.
Only the largest triangle-connected-component of Triangles is considered. The Frame Z is aligned with the area-weighted average normal of the connected triangles. Initially the Frame is placed at the area-weighted centroid of the connected triangles. Rays are cast along Z in both directions, if either hits, the Frame is translated to the nearer hit.
Parameters
bIsDefinitelySingleComponent if this is known, passing as true will speed up the computation
References Mesh.
ComputeGroupIDBound()
DYNAMICMESH_API int32 UE::Geometry::ComputeGroupIDBound (const FDynamicMesh3 & Mesh, const FDynamicMeshPolygroupAttribute * Layer)
Returns
Compute the upper bound of the group IDs for the given layer (one greater than the highest group ID)
References Mesh.
ComputeInsetLineSegmentsFromEdges()
DYNAMICMESH_API void UE::Geometry::ComputeInsetLineSegmentsFromEdges (const FDynamicMesh3 & Mesh, const TArray< int32 > & EdgeList, double InsetDistance, TArray< FLine3d > & InsetLinesOut)
For each edge in EdgeList, compute a line segment offset from the original edge by distance InsetDistance.
Assumes that each Edge is a boundary edge and so Triangle0 of that edge defines "inside" direction.
References Mesh.
ComputeMaterialIDRange()
DYNAMICMESH_API bool UE::Geometry::ComputeMaterialIDRange (const FDynamicMesh3 & Mesh, FInterval1i & MaterialIDRange)
Compute inclusive range [0...N] of MaterialID values currently in use on Mesh (ie range always includes 0)
Returns
true if MaterialIDs attribute exists (if false, Range is returned as [0,0])
References Mesh.
ComputeMaterialIDsForVertexPath()
DYNAMICMESH_API bool UE::Geometry::ComputeMaterialIDsForVertexPath (const FDynamicMesh3 & Mesh, const TArray< int32 > & VertexPath, bool bIsLoop, TArray< int32 > & EdgeMaterialIDsOut, int32 FallbackMaterialID = 0)
Compute a MaterialID for each edge along the VertexPath based on the MaterialID of adjacent triangles.
Currently, for each Edge, EdgeTriangle.A is used.
Parameters
VertexPath list of sequential vertices that are connected by mesh edges
bIsLoop is the path a loop?
EdgeMaterialIDsOut returned list of per-edge Material ID. Length is VertexPath.Num-1 for open paths and VertexPath.Num for loops
FallbackMaterialID default MaterialID to use if no Material attribute exists or no edge is found
Returns
true if MaterialIDs attribute exists
References Mesh.
ComputeNewGroupIDsAlongEdgeLoop()
DYNAMICMESH_API void UE::Geometry::ComputeNewGroupIDsAlongEdgeLoop (FDynamicMesh3 & Mesh, const TArray< int32 > & LoopEdgeIDs, TArray< int32 > & NewLoopEdgeGroupIDsOut, TArray< int32 > & NewGroupIDsOut, TFunctionRef< bool(int32 Eid1, int32 Eid2)> EdgesShouldHaveSameGroupFunc)
Compute a new set of GroupIDs along an edge loop under the assumption that the edge loop is about to be split and new geometry introduced.
The decision is based on a provided EdgesShouldHaveSameGroupFunc function which is called with sequential pairs of edges. For example if this function returns true when the GroupIDs are the same on both edges, then this function will create a new GroupID for each sequential span of non-matching GroupIDs (ie often the "expected" behavior).
Parameters
LoopEdgeIDs the EdgeIDs of the loop
NewLoopEdgeGroupIDsOut returned with new GroupID for each input EdgeID, same length as LoopEdgeIDs
NewGroupIDsOut list of newly-allocated GroupIDs
EdgesShouldHaveSameGroupFunc predicate that determines where new GroupIDs will be allocated
References Mesh.
ComputeNormalsForQuadPatch()
DYNAMICMESH_API void UE::Geometry::ComputeNormalsForQuadPatch (FDynamicMesh3 & Mesh, const FQuadGridPatch & QuadPatch)
Create a new Normals "island" (ie surrounded by hard edges) for the QuadPatch of the Mesh,.
References Mesh.
ComputeOrientedBBox() [1/2]
template<typename RealType> TOrientedBox3< RealType > GEOMETRYCORE_API UE::Geometry::ComputeOrientedBBox (const EDiTO DiTO_K, const int32 NumPoints, TFunctionRef< UE::Math::TVector< RealType >(int32)> GetPointFunc)
Returns
OrientedBox3 that contains the points provided by the given GetPointFunc
Heuristic-based computation of an object oriented bounding box that utilizes a small number of extremal vertices and an internal Di-Tetrahedron to generate the box orientation. Based on "Fast Computation of Tight-Fitting Oriented Bounding Boxes" by Larson and Kallberg (cf., Game Engine Gems 2)
Parameters
DiTO_K - selects the number of extremal vertices used by the method. More extremal vertices may produces a better result, but at a slightly higher cost
NumPoints - number points used in constructing the OrientedBox
GetPointFunc - returns a point for every index i = [0, NumPoints)
ComputeOrientedBBox() [2/2]
template<typename RealType> TOrientedBox3< RealType > GEOMETRYCORE_API UE::Geometry::ComputeOrientedBBox (const TArray< TVector< RealType > > & SampleDirections, const int32 NumPoints, TFunctionRef< UE::Math::TVector< RealType >(int32)> GetPointFunc)
Returns
OrientedBox3 that contains the points provided by the given GetPointFunc
Heuristic-based computation of an object oriented bounding box that utilizes a small number of extremal vertices and an internal Di-Tetrahedron to generate the box orientation. Based on "Fast Computation of Tight-Fitting Oriented Bounding Boxes" by Larson and Kallberg (cf., Game Engine Gems 2)
Parameters
SampleDirections - array of sample directions, ideally the direction vectors should be of the same length but no length checks are done internally.
NumPoints - number points used in constructing the OrientedBox
GetPointFunc - returns a point for every index i = [0, NumPoints)
The number of extreme vertices used by the method will be twice the number of sample directions.
ComputeStandardExteriorSpatialPhotoParameters()
MODELINGCOMPONENTS_API TArray< FSpatialPhotoParams > UE::Geometry::ComputeStandardExteriorSpatialPhotoParameters (UWorld * Unused, const TArray< AActor * > & Actors, const TArray< UActorComponent * > & Components, FImageDimensions PhotoDimensions, double HorizontalFOVDegrees, double NearPlaneDist, bool bFaces, bool bUpperCorners, bool bLowerCorners, bool bUpperEdges, bool bSideEdges)
References Actors, Components, and Unused.
ComputeUVIslandForQuadPatch()
DYNAMICMESH_API bool UE::Geometry::ComputeUVIslandForQuadPatch (FDynamicMesh3 & Mesh, const FQuadGridPatch & QuadPatch, double UVScaleFactor = 1.0, int UVOverlayIndex = 0)
Create a new UV Island for the QuadPatch triangles of the Mesh, and then assign UVs based on the grid layout.
References Mesh.
ConfigureSceneCapture()
MODELINGCOMPONENTS_API void UE::Geometry::ConfigureSceneCapture (FSceneCapturePhotoSet & SceneCapture, const TArray< TObjectPtr< AActor > > & Actors, const FSceneCaptureConfig & Config, bool bAllowCancel)
References Actors, bAllowCancel, Config, and SceneCapture.
Referenced by UE_DEPRECATED().
ConstrainedDelaunayTriangulate()
template<typename RealType> TArray< FIndex3i > GEOMETRYALGORITHMS_API UE::Geometry::ConstrainedDelaunayTriangulate (const TGeneralPolygon2< RealType > & GeneralPolygon)
Convenience function; invokes TConstrainedDelaunay2::Triangulate with most-often-used options.
Parameters
GeneralPolygon A general polygon, which may include holes.
Returns
An array of triangle indices. Indices refer to a flat array w/ the outer polygon vertices first, and the hole vertices appended after.
ConstrainedDelaunayTriangulateWithVertices()
template<typename RealType> TArray< FIndex3i > GEOMETRYALGORITHMS_API UE::Geometry::ConstrainedDelaunayTriangulateWithVertices (const TGeneralPolygon2< RealType > & GeneralPolygon, TArray< TVector2< RealType > > & OutVertices)
Convenience function; invokes TConstrainedDelaunay2::Triangulate with most-often-used options.
Parameters
GeneralPolygon A general polygon, which may include holes.
OutVertices Output array of vertices used in the triangulation.
Returns
An array of triangle indices.
ConvertComplexCollisionToMeshes()
MODELINGCOMPONENTS_API bool UE::Geometry::ConvertComplexCollisionToMeshes (IInterface_CollisionDataProvider * CollisionDataProvider, UE::Geometry::FDynamicMesh3 & MeshOut, const FTransformSequence3d & TransformSeqeuence, bool & bFoundMeshErrorsOut, bool bWeldEdges = true, bool bSetToPerTriangleNormals = false)
Extract the complex collision geometry from CollisionDataProvider as a dynamic mesh.
TransformSequence is applied to the mesh.
Parameters
bFoundMeshErrorsOut will be returned as true if potential non-manifold geometry was detected during construction (in that case some triangles will be disconnected)
bWeldEdges if true the mesh edges are welded
bSetToPerTriangleNormals if true and the mesh has a normals attribute overlay, the mesh is set to face normals, otherwise averaged vertex normals
ConvertLoopToTriOrderedEdgeLoop() [1/2]
GEOMETRYCORE_API bool UE::Geometry::ConvertLoopToTriOrderedEdgeLoop (const FDynamicMesh3 & Mesh, const TArray< int32 > & VertexLoop, const TArray< int32 > & EdgeLoop, TArray< FMeshTriOrderedEdgeID > & TriOrderedEdgesLoopOut)
Variant of ConvertLoopToTriOrderedEdgeLoop that always encodes using EdgeTriangles.A, ie suitable for encoding open border loops.
References Mesh.
ConvertLoopToTriOrderedEdgeLoop() [2/2]
GEOMETRYCORE_API bool UE::Geometry::ConvertLoopToTriOrderedEdgeLoop (const FDynamicMesh3 & Mesh, const TArray< int32 > & VertexLoop, const TArray< int32 > & EdgeLoop, TFunctionRef< int(int EdgeID, int TriangleA, int TriangleB)> SelectEdgeTriangleFunc, TArray< FMeshTriOrderedEdgeID > & TriOrderedEdgesLoopOut)
Convert the input Vertex/Edge loop into an edge loop representation that is independent of Vertex/Edge IDs.
See description of FMeshTriOrderedEdgeID for more information on how this works. But essentially the resulting TriOrderedEdgesLoopOut is stable across some topological changes, in particular if the vertices of the loop change but the triangle topology remains the same (eg if a bowtie vertex is disconnected, or if the mesh is disconnected along the edge loop), the encoded loop remains valid, while an explicit vertex or edge loop would not.
Parameters
SelectEdgeTriangleFunc This function is used to select which triangle to use for encoding at each edge
References Mesh.
ConvertPolygroupSelectionToIncidentOverlaySelection()
DYNAMICMESH_API bool UE::Geometry::ConvertPolygroupSelectionToIncidentOverlaySelection (const UE::Geometry::FDynamicMesh3 & Mesh, const FGroupTopology & GroupTopology, const FGeometrySelection & MeshSelection, TSet< int > & TrianglesOut, TSet< int > & VerticesOut, FGeometrySelection * TriangleVertexSelectionIncidentToEdgeOrVertexSelection = nullptr)
Like ConvertPolygroupSelectionToOverlaySelection but only includes overlay elements that are immediately incident to Polygroup Vertices/Edges.
If TriangleVertexSelectionIncidentToEdgeOrVertexSelection is not null and MeshSelection is an Edge or Vertex selection it will be set to a Vertex selection with Triangle Topology corresponding to the vertices touched by the edge selection. This is useful when users expect an edge selection to behave similarly to the incident vertex selection.
Returns
false if the MeshSelection topology type is not Polygroup and true otherwise
References ConvertPolygroupSelectionToIncidentOverlaySelection(), and Mesh.
Referenced by ConvertPolygroupSelectionToIncidentOverlaySelection().
ConvertPolygroupSelectionToOverlaySelection()
DYNAMICMESH_API bool UE::Geometry::ConvertPolygroupSelectionToOverlaySelection (const UE::Geometry::FDynamicMesh3 & Mesh, const FPolygroupSet & GroupSet, const FGeometrySelection & MeshSelection, TSet< int > & TrianglesOut, TSet< int > & VerticesOut)
Convert the given MeshSelection to a list of Triangles and Vertices into the Mesh, which can be used to represent a selection of overlay elements.
This is always possible since any FGeometrySelection can be represented as an overlay element selection because any overlay element can be represented as a (Triangle,Vertex) pair.
For Polygroup Faces, all triangles in the face are included. For Polygroup Edges, all triangles in any group adjacent to the edge are included. For Polygroup Corners, all triangles in any group touching the corner are included. See ConvertPolygroupSelectionToIncidentOverlaySelection for a similar function which only includes triangles immediately incident to the polygroup element
Returns
false if the MeshSelection topology type is not Polygroup and true otherwise
References ConvertPolygroupSelectionToOverlaySelection(), and Mesh.
Referenced by ConvertPolygroupSelectionToOverlaySelection().
ConvertPolygroupSelectionToTopologySelection()
DYNAMICMESH_API bool UE::Geometry::ConvertPolygroupSelectionToTopologySelection (const FGeometrySelection & MeshSelection, const UE::Geometry::FDynamicMesh3 & Mesh, const FGroupTopology * GroupTopology, FGroupTopologySelection & TopologySelectionOut)
Convert a MeshSelection with Polygroup topology type to a FGroupTopologySelection.
References ConvertPolygroupSelectionToTopologySelection(), and Mesh.
Referenced by ConvertPolygroupSelectionToTopologySelection().
ConvertSelection()
UE_DEPRECATED(5.5, "This version of ConvertSelection is deprecated, please use the version with the EENumerateSelectionConversionParams parameter going forward.") DYNAMICMESH_API bool ConvertSelection(const UE DYNAMICMESH_API bool UE::Geometry::ConvertSelection (const UE::Geometry::FDynamicMesh3 & Mesh, const FGroupTopology * GroupTopology, const FGeometrySelection & FromSelectionIn, FGeometrySelection & ToSelectionOut, const EEnumerateSelectionConversionParams ConversionParams)
Convert Selection from one type to another, based on geometry/topology types in FromSelectionIn and ToSelectionOut.
The following table describes the conversions, the FromSelectionIn/ToSelectionOut type are rows/columns respectively:
To: Triangle Polygroup
From: Vertex Edge Face Vertex Edge Face
Triangle Vertex 1 1 7 4# 7# 7#
Triangle Edge 1 1 8 4# 1# 8#
Triangle Face 1 1 1 4# 3# 2#
Polygroup Vertex 6# 9# 9 1 7# 7#
Polygroup Edge 5# 1# 8 1# 1 8#
Polygroup Face 1# 1# 1 1# 1# 1
Key: . These conversions are not implemented... yet? GroupTopology is ignored 1 - The implementation is obvious/unambiguous 2 - Polygroup faces containing any input triangle are selected 3 - Polygroup edges containing any input triangle edge are selected, but polygroup edges containing only input triangle vertices are not. 4 - Polygroup corners coinciding with any input triangle face/edge/vertex are selected 5 - All mesh vertices along the polygroup edge are selected 6 - All mesh vertices coinciding with polygroup corners are selected 7 - All Elements which immediately touch any input vertex/corner are selected 8 - All triangles or faces on either side of the any input edge are selected PolyEdge->TriFace includes all triangles in both groups which the edge borders 9 - All edges in each PolyEdge with touch any input Corner are selected All triangles in each PolyFace which touch any input Corner are selected
indicates GroupTopology must not be null for this combination. If this symbol is missing GroupTopology is ignored
Returns
true if conversion is supported and was computed successfully, return false otherwise
References ConvertSelection(), and Mesh.
Referenced by ConvertSelection(), and InitializeSelectionFromTriangles().
ConvertSimpleCollisionToDynamicMeshes() [1/2]
MODELINGCOMPONENTS_API void UE::Geometry::ConvertSimpleCollisionToDynamicMeshes (const FKAggregateGeom & AggGeom, FVector ExternalScale, TFunctionRef< void(int32 Index, const FKShapeElem &, FDynamicMesh3 &Mesh)> PerElementMeshCallback, const FSimpleCollisionTriangulationSettings & TriangulationSettings, const FSimpleCollisionToMeshAttributeSettings & MeshAttributeSettings = FSimpleCollisionToMeshAttributeSettings())
References FVector, and Mesh.
ConvertSimpleCollisionToDynamicMeshes() [2/2]
MODELINGCOMPONENTS_API void UE::Geometry::ConvertSimpleCollisionToDynamicMeshes (const FKAggregateGeom & AggGeom, FVector ExternalScale, TFunctionRef< void(int32 Index, const FKShapeElem &, FDynamicMesh3 &Mesh)> PerElementMeshCallback, TFunctionRef< bool(const FKShapeElem &)> IncludeElement, const FSimpleCollisionTriangulationSettings & TriangulationSettings, const FSimpleCollisionToMeshAttributeSettings & MeshAttributeSettings = FSimpleCollisionToMeshAttributeSettings())
References FVector, and Mesh.
ConvertSimpleCollisionToMeshes()
MODELINGCOMPONENTS_API void UE::Geometry::ConvertSimpleCollisionToMeshes (const FKAggregateGeom & AggGeom, UE::Geometry::FDynamicMesh3 & MeshOut, const FTransformSequence3d & TransformSequence, int32 SphereResolution = 16, bool bSetToPerTriangleNormals = false, bool bInitializeConvexUVs = false, TFunction< void(int, const FDynamicMesh3 &)> PerElementMeshCallback = nullptr, bool bApproximateLevelSetWithCubes = true, FVector ExternalScale = FVector::OneVector)
Extract the simple collision geometry from AggGeom as meshes (ie spheres and capsules are tessellated) and accumulate into MeshOut.
TransformSequence is applied to the meshes as they are accumulated, and not to the meshes passed to the PerElementMeshCallback.
Parameters
bSetToPerTriangleNormals if true and the mesh has a normals attribute overlay, the mesh is set to face normals, otherwise averaged vertex normals
bInitializeConvexUVs if true convex hulls have their UVs initialized to per-face planar projections, otherwise no UVs are set
PerElementMeshCallback if provided, called with each element mesh before transforming/appending to MeshOut. The int parameter is the shape type (EAggCollisionShape::Type), 0=Sphere, 1=Box, 2=Capsule, 3=Convex
bApproximateLevelSetWithCubes if true, level sets will be approximated with cubes; otherwise, marching cubes will be used to triangulate level set surfaces
ExternalScale if provided, apply external component scaling according to the simple collision shapes, in limited way that UE does so (e.g., so spheres w/ non-uniform scaling will still remain spheres)
References FVector, and UE::Math::TVector< double >::OneVector.
ConvertTriangleSelectionToOverlaySelection()
DYNAMICMESH_API bool UE::Geometry::ConvertTriangleSelectionToOverlaySelection (const UE::Geometry::FDynamicMesh3 & Mesh, const FGeometrySelection & MeshSelection, TSet< int > & TrianglesOut, TSet< int > & VerticesOut, FGeometrySelection * TriangleVertexSelectionIncidentToEdgeSelection = nullptr)
Convert the given MeshSelection to a list of Triangles and Vertices into the Mesh, which can be used to represent a selection of overlay elements.
This is always possible since any FGeometrySelection can be represented as an overlay element selection because any overlay element can be represented as a (Triangle,Vertex) pair.
If TriangleVertexSelectionIncidentToEdgeSelection is not null and MeshSelection is an Edge Selection it will be set to a Vertex selection with Triangle Topology corresponding to the vertices touched by the edge selection. This is useful when users expect an edge selection to behave similarly to the incident vertex selection.
Note
it is not necessarily the case that all vertices of triangles in TrianglesOut will be in VerticesOut.
Returns
false if the MeshSelection topology type is not Triangle and true otherwise
References ConvertTriangleSelectionToOverlaySelection(), and Mesh.
Referenced by ConvertTriangleSelectionToOverlaySelection().
ConvertTriOrderedEdgeLoopToLoop()
GEOMETRYCORE_API bool UE::Geometry::ConvertTriOrderedEdgeLoopToLoop (const FDynamicMesh3 & Mesh, const TArray< FMeshTriOrderedEdgeID > & TriOrderedEdgesLoopOut, TArray< int32 > & VertexLoop, TArray< int32 > * EdgeLoop = nullptr)
Recover the current Vertex and Edge loops given an encoded loop of FMeshTriOrderedEdgeID.
See FMeshTriOrderedEdgeID for details on this encoding, this function basically reverses ConvertLoopToTriOrderedEdgeLoop() for the current mesh topology
References Mesh.
CopyVertexNormalsToOverlay()
GEOMETRYCORE_API bool UE::Geometry::CopyVertexNormalsToOverlay (const FDynamicMesh3 & Mesh, FDynamicMeshNormalOverlay & NormalOverlayOut, bool bCompactElements = false)
Copies vertex normals to a given overlay (clearing it before use if it has any elements).
Parameters
bCompactElements If true, elements are compacted in the overlay
Returns
true if successful
References Mesh.
CopyVertexUVsToOverlay()
GEOMETRYCORE_API bool UE::Geometry::CopyVertexUVsToOverlay (const FDynamicMesh3 & Mesh, FDynamicMeshUVOverlay & UVOverlayOut, bool bCompactElements = false)
Copies vertex UVs to a given overlay (clearing it before use if it has any elements).
Parameters
bCompactElements If true, elements are compacted in the overlay
Returns
true if successful
References Mesh.
CreateBakePreviewMesh()
MESHMODELINGTOOLSEXP_API UPreviewMesh * UE::Geometry::CreateBakePreviewMesh (UObject * Tool, UToolTarget * ToolTarget, UWorld * World)
CreateSeamQuadric()
template<typename RealType> TQuadricError< RealType > UE::Geometry::CreateSeamQuadric (const TVector< RealType > & p0, const TVector< RealType > & p1, const TVector< RealType > & AdjFaceNormal)
A "Seam Quadric" is a quadric defined with respect to the plane passing through the edge p1-p0, but perpendicular to the adjacent face.
On return the quadric has been weighted by the length of the (p1-p0).
Definition at line 723 of file QuadricError.h.
References Edge, FMath::IsNearlyEqual(), FMath::IsNearlyZero(), UE::Geometry::TQuadricError< RealType >::Scale(), UE::Math::TVector< T >::SquaredLength(), Weight, and UE::Geometry::TQuadricError< RealType >::Zero().
Cross()
template<typename T> UE::Math::TVector< T > UE::Geometry::Cross (const UE::Math::TVector< T > & V1, const UE::Math::TVector< T > & V2)
Definition at line 222 of file VectorTypes.h.
References UE::Math::TVector< T >::X, UE::Math::TVector< T >::Y, and UE::Math::TVector< T >::Z.
Referenced by UE::Geometry::VectorUtil::Area().
CrossProductMatrix()
template<typename RealType> TMatrix3< RealType > UE::Geometry::CrossProductMatrix (const UE::Math::TVector< RealType > & A) inline static
Definition at line 498 of file MatrixTypes.h.
References A, and Zero.
Referenced by UE::Geometry::FTwistKelvinlet::FTwistKelvinlet(), FKelvinletBrushOp::ApplyBrush(), and FPinchKelvinletBrushOp::ApplyStamp().
DeregisterSceneSnappingManager()
MODELINGCOMPONENTS_API bool UE::Geometry::DeregisterSceneSnappingManager (UInteractiveToolsContext * ToolsContext)
Remove any existing UModelingSceneSnappingManager from the ToolsContext's ContextObjectStore.
Returns
true if the ContextObjectStore no longer has a UModelingSceneSnappingManager (whether it was removed, or did not exist)
References DeregisterSceneSnappingManager().
Referenced by DeregisterSceneSnappingManager().
Distance() [1/2]
template<typename T> T UE::Geometry::Distance (const UE::Math::TVector2< T > & V1, const UE::Math::TVector2< T > & V2)
Definition at line 74 of file VectorTypes.h.
References TMathUtil< RealType >::Sqrt(), UE::Math::TVector2< T >::X, and UE::Math::TVector2< T >::Y.
Referenced by UE::Geometry::TMeshDijkstra< PointSetType >::TMeshDijkstra(), UE::Geometry::FMeshBevel::DisplaceVertices(), UE::Geometry::TIncrementalMeshDijkstra< PointSetType >::FindMaxGraphDistancePointID(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::FindNearestTriangles(), UE::Geometry::TSphere3< float >::SignedDistance(), ToolSceneQueriesUtil::SnapDistanceToWorldGridSize(), UE::Geometry::TMeshQueries< TriangleMeshType >::TriDistanceSqr(), and UE::Geometry::TPlane3< FVector::FReal >::WhichSide().
Distance() [2/2]
template<typename T> T UE::Geometry::Distance (const UE::Math::TVector< T > & V1, const UE::Math::TVector< T > & V2)
Definition at line 196 of file VectorTypes.h.
References TMathUtil< RealType >::Sqrt(), UE::Math::TVector< T >::X, UE::Math::TVector< T >::Y, and UE::Math::TVector< T >::Z.
DistanceSquared() [1/2]
template<typename T> T UE::Geometry::DistanceSquared (const UE::Math::TVector2< T > & V1, const UE::Math::TVector2< T > & V2)
Definition at line 82 of file VectorTypes.h.
References UE::Math::TVector2< T >::X, and UE::Math::TVector2< T >::Y.
Referenced by UE::Geometry::FClusterKMeans::ComputeClusters(), FastTriWinding::ComputeCoeffs(), FastTriWinding::ComputeCoeffsSerial(), UE::Geometry::TDistLine2AxisAlignedBox2< float >::ComputeResult(), UE::Geometry::TDistPoint3Triangle3< float >::ComputeResult(), UE::Geometry::FVertexConnectedComponents::ConnectCloseVertices(), UE::Geometry::TSphere3< float >::Contains(), UE::Geometry::TPolygon2< double >::DistanceSquared(), UE::Geometry::TPolyline< T, 2 >< double >::DistanceSquared(), UE::Geometry::TSegment2< FVector::FReal >::DistanceSquared(), UE::Geometry::TSegment3< float >::DistanceSquared(), UE::Geometry::TIntrSegment2Segment2< double >::Find(), UE::Geometry::TIntrSegment2Triangle2< float >::Find(), UE::Geometry::FArrangement2d::find_nearest_boundary_vertex(), UE::Geometry::FArrangement2d::find_nearest_vertex(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::find_nearest_vertex(), UE::Geometry::TSphericalFibonacci< RealType >::FindIndex(), UE::Geometry::CurveUtil::FindNearestIndex(), UE::Geometry::FArrangement2d::insert_segment(), UE::Geometry::VectorUtil::IsObtuse(), UE::Geometry::FMergeCoincidentMeshEdges::IsSameEdge(), UE::Geometry::TPolygon2< double >::Simplify(), UE::Geometry::TPolyline< T, 2 >< double >::Simplify(), and UE::Geometry::TMeshLocalParam< PointSetType >::UpdateUVExpmapUpwind().
DistanceSquared() [2/2]
template<typename T> T UE::Geometry::DistanceSquared (const UE::Math::TVector< T > & V1, const UE::Math::TVector< T > & V2)
Definition at line 205 of file VectorTypes.h.
References UE::Math::TVector< T >::X, UE::Math::TVector< T >::Y, and UE::Math::TVector< T >::Z.
DoesCylinderContainPoint()
template<typename RealType> bool UE::Geometry::DoesCylinderContainPoint (const TVector< RealType > & CylinderCenter, const TVector< RealType > & NormalizedCylinderAxis, RealType CylinderRadius, RealType CylindeHeight, const TVector< RealType > & QueryPoint)
Test if QueryPoint is inside (or on) the given cylinder.
DoesCylinderIntersectBox()
template<typename RealType> bool UE::Geometry::DoesCylinderIntersectBox (const TAxisAlignedBox3< RealType > & Box, const TVector< RealType > & CylinderCenter, const TVector< RealType > & CylinderDirection, RealType CylinderRadius, RealType CylinderHeight)
Compute intersection between a cylinder and a 3D axis-aligned box.
References Box.
DoesTriangleIntersectCircle2D()
template<typename Real> GEOMETRYCORE_API bool UE::Geometry::DoesTriangleIntersectCircle2D (const TVector2< Real > & A, const TVector2< Real > & B, const TVector2< Real > & C, const TVector2< Real > & Center, double RadiusSquared)
References A, and B.
Dot()
template<typename T> T UE::Geometry::Dot (const UE::Math::TVector< T > & V1, const UE::Math::TVector< T > & V2)
Definition at line 216 of file VectorTypes.h.
References UE::Math::TVector< T >::X, UE::Math::TVector< T >::Y, and UE::Math::TVector< T >::Z.
Referenced by UE::Geometry::THalfspace3< float >::THalfspace3(), UE::Geometry::TPlane3< FVector::FReal >::TPlane3(), UE::Geometry::TSpatialPhotoSet< PixelType, RealType >::ComputeSampleLocation(), UE::Geometry::TFrame3< float >::ConstrainedAlignPerpAxes(), UE::Geometry::TLine2< double >::DistanceSquared(), UE::Geometry::TLine3< double >::DistanceSquared(), UE::Geometry::TPolygon2< double >::DistanceSquared(), UE::Geometry::TPolyline< T, 2 >< double >::DistanceSquared(), UE::Geometry::TSegment2< FVector::FReal >::DistanceSquared(), UE::Geometry::TSegment3< float >::DistanceSquared(), UE::Geometry::TMeshQueries< TriangleMeshType >::GetVolumeNonWatertight(), UE::Geometry::TVectorSetAnalysis3< float >::GreedyClusterVectors(), UE::Geometry::TOrientedBox3< float >::Merge(), UE::Geometry::TLine2< double >::NearestPoint(), UE::Geometry::TLine3< double >::NearestPoint(), UE::Geometry::TSegment2< FVector::FReal >::NearestPoint(), UE::Geometry::TSegment3< float >::NearestPoint(), UE::Geometry::TSegment2< FVector::FReal >::ProjectUnitRange(), UE::Geometry::TSegment3< float >::ProjectUnitRange(), SquaredDistanceFromLineIntegratedAlongSegment(), and UE::Geometry::TOrientedBox2< float >::ToLocalSpace().
DotPerp()
template<typename T> T UE::Geometry::DotPerp (const UE::Math::TVector2< T > & V1, const UE::Math::TVector2< T > & V2) constexpr
Returns
dot product of V1 with PerpCW(V2), ie V2 rotated 90 degrees clockwise
Definition at line 19 of file VectorTypes.h.
References UE::Math::TVector2< T >::X, and UE::Math::TVector2< T >::Y.
Referenced by UE::Geometry::VectorUtil::Area(), UE::Geometry::TPolygon2< double >::Chamfer(), UE::Geometry::VectorUtil::Circumcenter(), UE::Geometry::TIntrLine2Line2< double >::Classify(), UE::Geometry::TDistLine2AxisAlignedBox2< float >::DoQuery2D(), UE::Geometry::TIntrTriangle3Triangle3< float >::GetCoplanarIntersection(), UE::Geometry::TSegment2< FVector::FReal >::GetSide(), UE::Geometry::TLine2< double >::IntersectionPoint(), Orient(), SignedAngleR(), and UE::Geometry::TIntrLine2Triangle2< float >::TriangleLineRelations().
EmbedProjectedPath()
bool GEOMETRYCORE_API UE::Geometry::EmbedProjectedPath (FDynamicMesh3 * Mesh, int StartTriID, FFrame3d Frame, const TArray< FVector2d > & Path2D, TArray< int > & OutPathVertices, TArray< int > & OutVertexCorrespondence, bool bClosePath, FMeshFaceSelection * EnclosedFaces = nullptr, double PtSnapVertexOrEdgeThresholdSq = FMathf::ZeroTolerance *100)
Embed a 2D path into a mesh by projection, starting the walk from a given triangle.
Optionally select the triangles inside the path.
References Mesh, and TMathUtilConstants< float >::ZeroTolerance.
EmbedProjectedPaths()
bool GEOMETRYCORE_API UE::Geometry::EmbedProjectedPaths (FDynamicMesh3 * Mesh, const TArrayView< const int > StartTriIDs, FFrame3d Frame, const TArrayView< const TArray< FVector2d > > AllPaths, TArray< TArray< int > > & OutAllPathVertices, TArray< TArray< int > > & OutAllVertexCorrespondence, bool bClosePaths, FMeshFaceSelection * EnclosedFaces, double PtSnapVertexOrEdgeThresholdSq = FMathf::ZeroTolerance *100)
Embed multiple 2D paths into a mesh by projection, starting the walks from the given triangles.
Optionally select the triangles inside the paths.
References Mesh, and TMathUtilConstants< float >::ZeroTolerance.
ENUM_CLASS_FLAGS() [1/5]
UE::Geometry::ENUM_CLASS_FLAGS (EEnumerateSelectionMapping)
ENUM_CLASS_FLAGS() [2/5]
UE::Geometry::ENUM_CLASS_FLAGS (EMeshOcclusionMapType)
ENUM_CLASS_FLAGS() [3/5]
UE::Geometry::ENUM_CLASS_FLAGS (EOcclusionMapType)
ENUM_CLASS_FLAGS() [4/5]
UE::Geometry::ENUM_CLASS_FLAGS (ERoundedRectangleCorner)
ENUM_CLASS_FLAGS() [5/5]
UE::Geometry::ENUM_CLASS_FLAGS (ESimpleShapeType)
EnumeratePolygroupSelectionEdges() [1/2]
DYNAMICMESH_API bool UE::Geometry::EnumeratePolygroupSelectionEdges (const FGeometrySelection & MeshSelection, const UE::Geometry::FDynamicMesh3 & Mesh, const UE::Geometry::FGroupTopology & GroupTopology, TFunctionRef< void(int32)> EdgeFunc)
Version of EnumeratePolygroupSelectionEdges which uses GroupTopology.
Call EdgeFunc for each mesh EdgeID included in MeshSelection, where MeshSelection has polygroup topology. For Polygroup Faces, all edges (including internal, non-border edges) in the polygroup are included. For Polygroup Borders, includes all mesh edges which are a part of the selected GroupEdge(s)/BorderEdge(s) For Polygroup Corners, includes all mesh edges in all GroupEdge(s) which touch the selected Corner(s)
References EnumeratePolygroupSelectionEdges(), and Mesh.
EnumeratePolygroupSelectionEdges() [2/2]
DYNAMICMESH_API bool UE::Geometry::EnumeratePolygroupSelectionEdges (const FGeometrySelection & MeshSelection, const UE::Geometry::FDynamicMesh3 & Mesh, const UE::Geometry::FPolygroupSet & GroupSet, TFunctionRef< void(int32)> EdgeFunc)
Call EdgeFunc for each mesh EdgeID included in MeshSelection, where MeshSelection has polygroup topology.
For Polygroup Faces, all edges (including internal, non-border edges) in the polygroup are included. For Polygroup Borders, includes all mesh edges which are a part of the selected GroupEdge(s)/BorderEdge(s) For Polygroup Corners, includes all mesh edges in all GroupEdge(s) which touch the selected Corner(s)
For rendering purposes, use EnumeratePolygroupSelectionElements
References EnumeratePolygroupSelectionEdges(), and Mesh.
Referenced by EnumeratePolygroupSelectionEdges(), and EnumeratePolygroupSelectionEdges().
EnumeratePolygroupSelectionElements() [1/2]
DYNAMICMESH_API bool UE::Geometry::EnumeratePolygroupSelectionElements (const FGeometrySelection & MeshSelection, const UE::Geometry::FDynamicMesh3 & Mesh, const FGroupTopology * GroupTopology, TFunctionRef< void(int32, const FVector3d &)> VertexFunc, TFunctionRef< void(int32, const FSegment3d &)> EdgeFunc, TFunctionRef< void(int32, const FTriangle3d &)> TriangleFunc, const FTransform * ApplyTransform = nullptr, const bool bMapFacesToEdgeLoops = false)
Prefer EnumeratePolygroupSelectionElements with Flags parameter.
References ApplyTransform, EnumeratePolygroupSelectionElements(), Mesh, and VertexFunc.
Referenced by EnumeratePolygroupSelectionElements(), and EnumeratePolygroupSelectionElements().
EnumeratePolygroupSelectionElements() [2/2]
DYNAMICMESH_API bool UE::Geometry::EnumeratePolygroupSelectionElements (const FGeometrySelection & MeshSelection, const UE::Geometry::FDynamicMesh3 & Mesh, const FGroupTopology * GroupTopology, TFunctionRef< void(int32, const FVector3d &)> VertexFunc, TFunctionRef< void(int32, const FSegment3d &)> EdgeFunc, TFunctionRef< void(int32, const FTriangle3d &)> TriangleFunc, const FTransform * ApplyTransform = nullptr, const EEnumerateSelectionMapping Flags = EEnumerateSelectionMapping::Default)
Enumerates the renderable geometry for a given MeshSelection when in Polygroup Topology mode.
Calls VertexFunc/EdgeFunc/TriangleFunc for the vertices/edges/triangles identified by MeshSelection. Since a MeshSelection only stores vertices edges, or triangles, but not combined, only one of these functions will be invoked during a call to this function.
This function differs from the component specific variants (ex. EnumeratePolygroupSelectionTriangles) by only collecting the renderable geometry representations of the selection. For instance, a polygroup face may only want to render the triangles and border edges, while EnumeratePolygroupSelectionTriangles would collect all triangles and edges within that polygroup face. This is the difference between render representation and component conversion.
References ApplyTransform, Default, EnumeratePolygroupSelectionElements(), Flags, Mesh, and VertexFunc.
EnumeratePolygroupSelectionTriangles()
DYNAMICMESH_API bool UE::Geometry::EnumeratePolygroupSelectionTriangles (const FGeometrySelection & MeshSelection, const UE::Geometry::FDynamicMesh3 & Mesh, const UE::Geometry::FPolygroupSet & GroupSet, TFunctionRef< void(int32)> TriangleFunc)
Call TriangleFunc for each mesh TriangleID included in MeshSelection, where MeshSelection has polygroup topology.
For Polygroup Faces, all triangles in the face are included. For Polygroup Edges, currently all triangles in any group adjacent to the edge For Polygroup Corners, currently all triangles in any group touching the corner
References EnumeratePolygroupSelectionTriangles(), and Mesh.
Referenced by EnumeratePolygroupSelectionTriangles().
EnumeratePolygroupSelectionVertices()
DYNAMICMESH_API bool UE::Geometry::EnumeratePolygroupSelectionVertices (const FGeometrySelection & GroupSelection, const UE::Geometry::FDynamicMesh3 & Mesh, const FGroupTopology * GroupTopology, const FTransform & ApplyTransform, TFunctionRef< void(uint64, const FVector3d &)> VertexFunc)
Call VertexFunc for each selected Mesh element (vertex/edge/tri) in the set of polygroup faces/edges/corners specified by GroupSelection (relative to GroupTopology parameter) ApplyTransform will be applied to Vertex Positions before calling VertexFunc.
For Faces: enumerates all vertices in the selected polygroup(s), including internal, non-Corner vertices For Edges/Boundaries: enumerates the TriVerts which make up the selected PolyEdge(s) For Verts/Corners: returns the TriVert that corresponds to the selected Corner(s)
For rendering purposes, use EnumeratePolygroupSelectionElements
References ApplyTransform, EnumeratePolygroupSelectionVertices(), Mesh, and VertexFunc.
Referenced by EnumeratePolygroupSelectionVertices().
EnumerateSelectionEdges()
DYNAMICMESH_API bool UE::Geometry::EnumerateSelectionEdges (const FGeometrySelection & MeshSelection, const UE::Geometry::FDynamicMesh3 & Mesh, TFunctionRef< void(int32)> EdgeFunc, const UE::Geometry::FPolygroupSet * UseGroupSet = nullptr)
Call EdgeFunc for each mesh EdgeID included in MeshSelection.
EdgeFunc may be called multiple times for the same EdgeID. This will forward to EnumerateTriangleSelectionEdges() or EnumeratePolygroupSelectionEdges() depending on the selection topology type. If UseGroupSet and MeshSelection is for polygroups, the default Mesh group layer will be used. For polygroups - all edges and vertices within the polygroup are included, not exclusively Group Boundaries or Group Corners
References EnumerateSelectionEdges(), and Mesh.
Referenced by EnumerateSelectionEdges().
EnumerateSelectionTriangles()
DYNAMICMESH_API bool UE::Geometry::EnumerateSelectionTriangles (const FGeometrySelection & MeshSelection, const UE::Geometry::FDynamicMesh3 & Mesh, TFunctionRef< void(int32)> TriangleFunc, const UE::Geometry::FPolygroupSet * UseGroupSet = nullptr)
Call TriangleFunc for each mesh TriangleID included in MeshSelection.
TriangleFunc may be called multiple times for the same TriangleID. This will forward to EnumerateTriangleSelectionTriangles() or EnumeratePolygroupSelectionTriangles() depending on the selection topology type. If UseGroupSet and MeshSelection is for polygroups, the default Mesh group layer will be used.
References EnumerateSelectionTriangles(), and Mesh.
Referenced by EnumerateSelectionTriangles().
EnumerateTriangleSelectionEdges()
DYNAMICMESH_API bool UE::Geometry::EnumerateTriangleSelectionEdges (const FGeometrySelection & MeshSelection, const UE::Geometry::FDynamicMesh3 & Mesh, TFunctionRef< void(int32)> EdgeFunc)
Call EdgeFunc for each mesh EdgeID included in MeshSelection.
For Triangles, all 3 edges are included. For Edges, all selected edges are included For Vertices, all edges touching each selected vertex are included.
References EnumerateTriangleSelectionEdges(), and Mesh.
Referenced by EnumerateTriangleSelectionEdges().
EnumerateTriangleSelectionElements() [1/2]
DYNAMICMESH_API bool UE::Geometry::EnumerateTriangleSelectionElements (const FGeometrySelection & MeshSelection, const UE::Geometry::FDynamicMesh3 & Mesh, TFunctionRef< void(int32, const FVector3d &)> VertexFunc, TFunctionRef< void(int32, const FSegment3d &)> EdgeFunc, TFunctionRef< void(int32, const FTriangle3d &)> TriangleFunc, const FTransform * ApplyTransform = nullptr, const bool bMapFacesToEdgeLoops = false)
Prefer EnumerateTriangleSelectionElements with Flags parameter.
References ApplyTransform, EnumerateTriangleSelectionElements(), Mesh, and VertexFunc.
Referenced by EnumerateTriangleSelectionElements(), and EnumerateTriangleSelectionElements().
EnumerateTriangleSelectionElements() [2/2]
DYNAMICMESH_API bool UE::Geometry::EnumerateTriangleSelectionElements (const FGeometrySelection & MeshSelection, const UE::Geometry::FDynamicMesh3 & Mesh, TFunctionRef< void(int32, const FVector3d &)> VertexFunc, TFunctionRef< void(int32, const FSegment3d &)> EdgeFunc, TFunctionRef< void(int32, const FTriangle3d &)> TriangleFunc, const FTransform * ApplyTransform = nullptr, const EEnumerateSelectionMapping Flags = EEnumerateSelectionMapping::Default)
Enumerates the renderable geometry for a given MeshSelection when in Triangle Topology mode.
Calls VertexFunc/EdgeFunc/TriangleFunc for the vertices/edges/triangles identified by MeshSelection. Since a MeshSelection only stores vertices edges, or triangles, but not combined, only one of these functions will be invoked during a call to this function.
This function employs the component specific variants (ex. EnumerateTriangleSelectionTriangles) but the overall intention of this function is to collect the renderable geometry representations of the selection. In triangle topology mode only, there is not a difference between all selection elements and the desired rendered elements. However, this function is still used for render representation for consistency and clarity.
Parameters
ApplyTransform if non-null, transform is applied to the 3D geometry
References ApplyTransform, Default, EnumerateTriangleSelectionElements(), Flags, Mesh, and VertexFunc.
EnumerateTriangleSelectionTriangles()
DYNAMICMESH_API bool UE::Geometry::EnumerateTriangleSelectionTriangles (const FGeometrySelection & MeshSelection, const UE::Geometry::FDynamicMesh3 & Mesh, TFunctionRef< void(int32)> TriangleFunc)
Call TriangleFunc for each mesh TriangleID included in MeshSelection.
For Edges, both connected edges are included. For Vertices, all triangles in the vertex one-ring are included.
References EnumerateTriangleSelectionTriangles(), and Mesh.
Referenced by EnumerateTriangleSelectionTriangles().
EnumerateTriangleSelectionVertices()
DYNAMICMESH_API bool UE::Geometry::EnumerateTriangleSelectionVertices (const FGeometrySelection & MeshSelection, const UE::Geometry::FDynamicMesh3 & Mesh, const FTransform * ApplyTransform, TFunctionRef< void(uint64, const FVector3d &)> VertexFunc)
Call VertexFunc for each selected Mesh element (vertex/edge/tri) in MeshSelection.
ApplyTransform will be applied to Vertex Positions before calling VertexFunc
For Triangles: includes all 3 points which make up each selected triangle For Edges: includes both vertex endpoints of each selected edge For Vertices: includes each selected vertex
References ApplyTransform, EnumerateTriangleSelectionVertices(), Mesh, and VertexFunc.
Referenced by EnumerateTriangleSelectionVertices(), and UE_DEPRECATED().
FindInSelectionByTopologyID()
DYNAMICMESH_API bool UE::Geometry::FindInSelectionByTopologyID (const FGeometrySelection & GeometrySelection, uint32 TopologyID, uint64 & FoundValue)
Assuming that the uint64 values in the GeometrySelection are encoded FGeoSelectionID's, find the item that has a matching TopologyID, ignoring the GeometryID.
Parameters
FoundValue the hash value found
Returns
true if an item was found
FindModelingSceneSnappingManager()
MODELINGCOMPONENTS_API UModelingSceneSnappingManager * UE::Geometry::FindModelingSceneSnappingManager (UInteractiveToolManager * ToolManager)
Find an existing UModelingSceneSnappingManager in the ToolsContext's ContextObjectStore.
Returns
SelectionManager pointer or nullptr if not found
References FindModelingSceneSnappingManager().
Referenced by FindModelingSceneSnappingManager().
FindNextAdjacentTriangleAroundVtx()
template<typename TrisConnectedPredicate> FIndex3i UE::Geometry::FindNextAdjacentTriangleAroundVtx (const FDynamicMesh3 * Mesh, int32 VertexID, int32 FromTriangleID, int32 PrevTriangleID, TrisConnectedPredicate TrisConnectedTest)
Walk around VertexID from FromTriangleID to next connected triangle if it exists, walking "away" from PrevTriangleID.
Parameters
TrisConnectedFunc returns true if two triangles should be considered connected, to support breaking at seams/etc that are not in base mesh topology
Returns
triplet of values (FoundTriangleID, SharedEdgeID, IndexOfEdgeInFromTri), or all IndexConstants::InvalidID if not found
Definition at line 125 of file MeshIndexUtil.h.
References UE::Geometry::FIndex2i::A, UE::Geometry::FIndex3i::A, UE::Geometry::FIndex2i::B, UE::Geometry::FIndex3i::B, UE::Geometry::FIndex3i::C, check, IndexConstants::InvalidID, and Mesh.
FindPolygroupLayerByName() [1/2]
DYNAMICMESH_API const FDynamicMeshPolygroupAttribute * UE::Geometry::FindPolygroupLayerByName (const FDynamicMesh3 & Mesh, FName Name)
Find the first FDynamicMeshPolygroupAttribute with the given FName in a the AttributeSet of a Mesh.
Returns
nullptr if no Polygroup layer is found
References Mesh, and Name.
FindPolygroupLayerByName() [2/2]
DYNAMICMESH_API FDynamicMeshPolygroupAttribute * UE::Geometry::FindPolygroupLayerByName (FDynamicMesh3 & Mesh, FName Name)
Find the first FDynamicMeshPolygroupAttribute with the given FName in a the AttributeSet of a Mesh.
Returns
nullptr if no Polygroup layer is found
References Mesh, and Name.
FindPolygroupLayerIndex()
DYNAMICMESH_API int32 UE::Geometry::FindPolygroupLayerIndex (const FDynamicMesh3 & Mesh, const FDynamicMeshPolygroupAttribute * Layer)
Returns
index of Layer in Mesh AttributeSet, or -1 if not found
References Mesh.
FindPolygroupLayerIndexByName()
DYNAMICMESH_API int32 UE::Geometry::FindPolygroupLayerIndexByName (const FDynamicMesh3 & Mesh, FName Name)
Returns
index of the first Layer with the given FName in Mesh AttributeSet, or -1 if not found
References Mesh, and Name.
FindSharedEdgeInTriangles()
GEOMETRYCORE_API int32 UE::Geometry::FindSharedEdgeInTriangles (const FDynamicMesh3 & Mesh, int32 Triangle0, int32 Triangle1)
Returns
the ID of the shared edge betwen two given triangles, or IndexConstants::InvalidID if not found / invalid input
References Mesh.
FindVertexEdgesInTriangle()
GEOMETRYCORE_API FIndex2i UE::Geometry::FindVertexEdgesInTriangle (const FDynamicMesh3 & Mesh, int32 TriangleID, int32 VertexID)
Find the two edges in a Triangle that are connected to a given Vertex of the triangle.
Returns
edge pair, or (IndexConstants::InvalidID, IndexConstants::InvalidID) on error
References Mesh.
FitKDOPVertices3() [1/3]
template<typename RealType> bool UE::Geometry::FitKDOPVertices3 (TArrayView< const UE::Math::TVector< RealType > > PlaneDirections, const int32 NumPoints, TFunctionRef< UE::Math::TVector< RealType >(int32)> GetPointFunc, TArray< UE::Math::TVector< RealType > > & OutVertices, TArray< UE::Math::TPlane< RealType > > * OptionalOutPlanes = nullptr, RealType Epsilon = TMathUtil<RealType>::Epsilon, RealType VertexSnapDistance = (RealType)0.1, RealType Inflate = (RealType)0.1)
Compute the vertices (and optionally planes) of a k-DOP bounding convex hull containing the points returned by GetPointFunc.
Definition at line 36 of file FitKDOP3.h.
References FitKDOPVertices3().
FitKDOPVertices3() [2/3]
template<typename RealType> bool GEOMETRYCORE_API UE::Geometry::FitKDOPVertices3 (TArrayView< const UE::Math::TVector< RealType > > PlaneDirections, const int32 NumPoints, TFunctionRef< UE::Math::TVector< RealType >(int32)> GetPointFunc, TFunctionRef< bool(int32)> FilterFunc, TArray< UE::Math::TVector< RealType > > & OutVertices, TArray< UE::Math::TPlane< RealType > > * OptionalOutPlanes = nullptr, RealType Epsilon = TMathUtil< RealType >::Epsilon, RealType VertexSnapDistance = (RealType) 0.1, RealType Inflate = (RealType) 0.1)
Compute the vertices (and optionally planes) of a k-DOP bounding convex hull containing the points returned by GetPointFunc where FilterFunc returns true.
Referenced by FitKDOPVertices3(), and FitKDOPVertices3().
FitKDOPVertices3() [3/3]
template<typename RealType> bool UE::Geometry::FitKDOPVertices3 (TArrayView< const UE::Math::TVector< RealType > > PlaneDirections, const TArray< UE::Math::TVector< RealType > > & Points, TArray< UE::Math::TVector< RealType > > & OutVertices, TArray< UE::Math::TPlane< RealType > > * OptionalOutPlanes = nullptr, RealType Epsilon = TMathUtil<RealType>::Epsilon, RealType VertexSnapDistance = (RealType)0.1, RealType Inflate = (RealType)0.1)
Compute the vertices (and optionally planes) of a k-DOP bounding convex hull containing Points.
Definition at line 49 of file FitKDOP3.h.
References FitKDOPVertices3(), and Points.
FitOrientedBox2ConvexHull() [1/2]
template<typename RealType> TOrientedBox2< RealType > UE::Geometry::FitOrientedBox2ConvexHull (int32 NumPts, TFunctionRef< TVector2< RealType >(int32)> GetHullPt, EBox2FitCriteria FitMethod = EBox2FitCriteria::Area)
Use the rotating calipers algorithm to find a best-fit oriented bounding box of a convex hull.
Parameters
NumPts Number of points in the convex hull
GetHullPt Function(hull point index) -> hull point
FitMethod What criteria to optimize
Returns
A best-fit TOrientedBox2 that contains the points
Definition at line 121 of file FitOrientedBox2.h.
References Area, and FitOrientedBox2ConvexHull().
FitOrientedBox2ConvexHull() [2/2]
template<typename RealType> TOrientedBox2< RealType > GEOMETRYCORE_API UE::Geometry::FitOrientedBox2ConvexHull (int32 NumPts, TFunctionRef< TVector2< RealType >(int32)> GetHullPt, TFunctionRef< RealType(RealType, RealType)> FitFn)
Use the rotating calipers algorithm to find a best-fit oriented bounding box of a convex hull.
Parameters
NumPts Number of points in the convex hull
GetHullPt Function(hull point index) -> hull point
FitFn Function from (Width, Height) -> Fit metric; The box with the lowest fit metric will be chosen
Returns
A best-fit TOrientedBox2 that contains the points
Referenced by FitOrientedBox2ConvexHull().
FitOrientedBox2Points() [1/2]
template<typename RealType> TOrientedBox2< RealType > UE::Geometry::FitOrientedBox2Points (TArrayView< const TVector2< RealType > > Points, EBox2FitCriteria FitMethod = EBox2FitCriteria::Area)
Use the rotating calipers algorithm to find a best-fit oriented bounding box of a point set.
Note it internally computes a 2D convex hull of a point set, and is currently O(n log n) in the number of points.
Parameters
Points The points to fit
FitMethod What criteria to optimize
Returns
A best-fit TOrientedBox2 that contains the points
Definition at line 42 of file FitOrientedBox2.h.
References Area, FitOrientedBox2Points(), and Points.
FitOrientedBox2Points() [2/2]
template<typename RealType> TOrientedBox2< RealType > GEOMETRYCORE_API UE::Geometry::FitOrientedBox2Points (TArrayView< const TVector2< RealType > > Points, TFunctionRef< RealType(RealType, RealType)> FitFn)
Use the rotating calipers algorithm to find a best-fit oriented bounding box of a point set.
Note it internally computes a 2D convex hull of a point set, and is currently O(n log n) in the number of points.
Parameters
Points The points to fit
FitFn Function from (Width, Height) -> Fit metric; The box with the lowest fit metric will be chosen
Returns
A best-fit TOrientedBox2 that contains the points
References Points.
Referenced by FitOrientedBox2Points().
FitOrientedBox2SimplePolygon() [1/2]
template<typename RealType> TOrientedBox2< RealType > UE::Geometry::FitOrientedBox2SimplePolygon (TArrayView< const TVector2< RealType > > Polygon, EBox2FitCriteria FitMethod = EBox2FitCriteria::Area)
Use the rotating calipers algorithm to find a best-fit oriented bounding box of a simple polygon.
Note the polygon should not be self-intersecting. O(n) in the number of points.
Parameters
Polygon The vertices of the simple polygon to fit
FitMethod What criteria to optimize
Returns
A best-fit TOrientedBox2 that contains the points
Definition at line 81 of file FitOrientedBox2.h.
References Area, FitOrientedBox2SimplePolygon(), and Polygon.
FitOrientedBox2SimplePolygon() [2/2]
template<typename RealType> TOrientedBox2< RealType > GEOMETRYCORE_API UE::Geometry::FitOrientedBox2SimplePolygon (TArrayView< const TVector2< RealType > > Polygon, TFunctionRef< RealType(RealType, RealType)> FitFn)
Use the rotating calipers algorithm to find a best-fit oriented bounding box of a simple polygon.
Note the polygon should not be self-intersecting. O(n) in the number of points.
Parameters
Polygon The vertices of the simple polygon to fit
FitFn Function from (Width, Height) -> Fit metric; The box with the lowest fit metric will be chosen
Returns
A best-fit TOrientedBox2 that contains the points
References Polygon.
Referenced by FitOrientedBox2SimplePolygon().
FitOrientedBox3Points() [1/2]
template<typename RealType> TOrientedBox3< RealType > GEOMETRYCORE_API UE::Geometry::FitOrientedBox3Points (int32 NumPoints, TFunctionRef< TVector< RealType >(int32)> GetPointFunc, TFunctionRef< bool(int32)> Filter, EBox3FitCriteria FitMethod = EBox3FitCriteria::Volume, RealType SameNormalTolerance = 0, FProgressCancel * ProgressCancel = nullptr)
Compute a close-fitting oriented bounding box to the given points.
Relatively expensive; for a faster approximation use DiTOrientedBox.h's ComputeOrientedBBox
Parameters
NumPoints Number of points to consider
GetPointFunc Function providing array-style access into points
Filter Optional filter to include only a subset of the points in the output hull
FitMethod What criteria to optimize
SameNormalTolerance Tolerance for considering normals the same when choosing projection directions. If > 0, can save some computation if the convex hull is very large.
Returns
A best-fit TOrientedBox3 that contains the points
References Filter, and Volume.
Referenced by FitOrientedBox3Points().
FitOrientedBox3Points() [2/2]
template<typename RealType> TOrientedBox3< RealType > UE::Geometry::FitOrientedBox3Points (TArrayView< const TVector< RealType > > Points, EBox3FitCriteria FitMethod = EBox3FitCriteria::Volume, RealType SameNormalTolerance = 0, FProgressCancel * ProgressCancel = nullptr)
Compute a close-fitting oriented bounding box to the given points.
Relatively expensive; for a faster approximation use DiTOrientedBox.h's ComputeOrientedBBox
Parameters
Points The points to fit
FitMethod What criteria to optimize
SameNormalTolerance Tolerance for considering normals the same when choosing projection directions. If > 0, can save some computation if the convex hull is very large.
Returns
A best-fit TOrientedBox3 that contains the points
Definition at line 48 of file FitOrientedBox3.h.
References FitOrientedBox3Points(), Points, and Volume.
FlipToDelaunay() [1/5]
int32 DYNAMICMESH_API UE::Geometry::FlipToDelaunay (FIntrinsicEdgeFlipMesh & IntrinsicMesh, TSet< int > & Uncorrected, const int32 MaxFlipCount = TMathUtilConstants< int >::MaxReal)
FlipToDelaunay() [2/5]
int32 DYNAMICMESH_API UE::Geometry::FlipToDelaunay (FIntrinsicMesh & IntrinsicMesh, TSet< int > & Uncorrected, const int32 MaxFlipCount = TMathUtilConstants< int >::MaxReal)
FlipToDelaunay() [3/5]
int32 DYNAMICMESH_API UE::Geometry::FlipToDelaunay (FIntrinsicTriangulation & IntrinsicMesh, TSet< int > & Uncorrected, const int32 MaxFlipCount = TMathUtilConstants< int >::MaxReal)
FlipToDelaunay() [4/5]
int32 DYNAMICMESH_API UE::Geometry::FlipToDelaunay (FSimpleIntrinsicEdgeFlipMesh & IntrinsicMesh, TSet< int > & Uncorrected, const int32 MaxFlipCount = TMathUtilConstants< int >::MaxReal)
Perform edge flips on intrinsic mesh until either the MaxFlipCount is reached or the mesh is fully Delaunay.
Parameters
IntrinsicMesh - The mesh to be operated on.
Uncorrected - contains on return, all the edges that could not be flipped (e.g. edge shared by non-convex pair of triangles)
Returns
the number of flips.
Referenced by UE::MeshDeformation::ConstructFullIDTCotangentLaplacian(), and UE::MeshDeformation::ConstructIDTCotangentLaplacian().
FlipToDelaunay() [5/5]
int32 DYNAMICMESH_API UE::Geometry::FlipToDelaunay (FSimpleIntrinsicMesh & IntrinsicMesh, TSet< int > & Uncorrected, const int32 MaxFlipCount = TMathUtilConstants< int >::MaxReal)
ForEachCaptureType()
template<typename FunctionType> void UE::Geometry::ForEachCaptureType (const FunctionType & Function)
Definition at line 37 of file WorldRenderCapture.h.
References BaseColor, CombinedMRS, DeviceDepth, Emissive, Function, Metallic, Opacity, Roughness, Specular, SubsurfaceColor, and WorldNormal.
FractalBrownianMotionNoise()
template<typename T> T UE::Geometry::FractalBrownianMotionNoise (const EFBMMode FBMMode, const uint32 OctaveCount, const Math::TVector2< T > Coords, const T Lacunarity, const T Gain, const T Smoothness, const T Gamma)
Definition at line 32 of file ProceduralNoise.h.
References checkSlow, Gamma, FMath::PerlinNoise2D(), Ridge, Standard, Turbulent, UE::Math::TVector2< T >::X, and UE::Math::TVector2< T >::Y.
GenerateArcSegments()
template<typename RealType> void UE::Geometry::GenerateArcSegments (int32 NumSteps, RealType Radius, RealType StartAngle, RealType EndAngle, const TVector< RealType > & Center, const TVector< RealType > & AxisX, const TVector< RealType > & AxisY, const TTransformSRT3< RealType > & Transform, TFunctionRef< void(const TVector< RealType > &A, const TVector< RealType > &B)> EmitLineFunc)
call EmitLineFunc for the line segments that make up the Circular Arc defined by the given parameters and sampled with NumSteps vertices
Parameters
NumSteps number of vertices used to approximate arc
Radius radius of arc
StartAngle arc starts at this angle
EndAngle arc ends at this angle
AxisX first axis of arc
AxisY second axis of arc
Transform transform applied to each point
Definition at line 150 of file LineSegmentGenerators.h.
References A, Angle, B, TMathUtil< RealType >::Cos(), TMathUtil< RealType >::Sin(), Transform, and UE::Math::TVector< T >::Zero().
GenerateBoxSegments()
template<typename RealType> void UE::Geometry::GenerateBoxSegments (const TVector< RealType > & HalfDimensions, const TVector< RealType > & Center, const TVector< RealType > & AxisX, const TVector< RealType > & AxisY, const TVector< RealType > & AxisZ, const TTransformSRT3< RealType > & Transform, TFunctionRef< void(const TVector< RealType > &A, const TVector< RealType > &B)> EmitLineFunc)
call EmitLineFunc for the 12 line segments defined by the given box parameters
Parameters
HalfDimensions X/Y/Z dimensions of box
Center center of box
AxisX X axis of box
AxisY Y axis of box
AxisZ Z axis of box
Transform transform applied to points of box
Definition at line 83 of file LineSegmentGenerators.h.
References A, B, Transform, UE::Math::TVector< T >::X, UE::Math::TVector< T >::Y, and UE::Math::TVector< T >::Z.
GenerateCircleSegments()
template<typename RealType> void UE::Geometry::GenerateCircleSegments (int32 NumSteps, RealType Radius, const TVector< RealType > & Center, const TVector< RealType > & AxisX, const TVector< RealType > & AxisY, const TTransformSRT3< RealType > & Transform, TFunctionRef< void(const TVector< RealType > &A, const TVector< RealType > &B)> EmitLineFunc)
call EmitLineFunc for the line segments that make up the Circle defined by the given parameters and sampled with NumSteps vertices
Parameters
NumSteps number of vertices used to approximate circle
Radius radius of circle
Center center of circle
AxisX first axis of circle
AxisY second axis of circle
Transform transform applied to each point
Definition at line 123 of file LineSegmentGenerators.h.
References A, Angle, B, TMathUtil< RealType >::Cos(), TMathUtil< RealType >::Sin(), Transform, and UE::Math::TVector< T >::Zero().
GetArrayMesh()
FTriangleMeshAdapterd UE::Geometry::GetArrayMesh (TArray< FVector > & Vertices, TArray< FIntVector > & Triangles) inline
Example function to generate a generic mesh adapter from arrays.
Parameters
Vertices Array of mesh vertices
Triangles Array of int-vectors, one per triangle, indexing into the vertices array
Definition at line 52 of file MeshAdapter.h.
References TArray< InElementType, InAllocatorType >::Num(), and Vertices.
GetBodySetup() [1/2]
MODELINGCOMPONENTS_API const UBodySetup * UE::Geometry::GetBodySetup (const UPrimitiveComponent * SourceComponent)
Returns
BodySetup on the given SourceComponent, or nullptr if no BodySetup was found
GetBodySetup() [2/2]
MODELINGCOMPONENTS_API UBodySetup * UE::Geometry::GetBodySetup (UPrimitiveComponent * SourceComponent)
Returns
BodySetup on the given SourceComponent, or nullptr if no BodySetup was found
GetCollisionSettings()
MODELINGCOMPONENTS_API FComponentCollisionSettings UE::Geometry::GetCollisionSettings (const UPrimitiveComponent * Component)
Returns
current Component collision settings
References Component.
GetCollisionShapes() [1/2]
MODELINGCOMPONENTS_API bool UE::Geometry::GetCollisionShapes (const UPrimitiveComponent * Component, FKAggregateGeom & AggGeomOut)
Get current Component collision shapes.
References Component.
GetCollisionShapes() [2/2]
MODELINGCOMPONENTS_API bool UE::Geometry::GetCollisionShapes (const UPrimitiveComponent * Component, FSimpleShapeSet3d & ShapeSetOut)
Get current Component collision shapes.
References Component.
GetCurrentGeometrySelectionForTarget() [1/2]
MODELINGCOMPONENTS_API bool UE::Geometry::GetCurrentGeometrySelectionForTarget (const FToolBuilderState & SceneState, UToolTarget * Target, FGeometrySelection & SelectionOut)
Given a FToolBuilderState, find an available FGeometrySelection for the given ToolTarget (via the UGeometrySelectionManager in the ContextObjectStore)
Parameters
SelectionOut non-empty selection will be returned here
Returns
true if a non-empty selection was found
References Target.
GetCurrentGeometrySelectionForTarget() [2/2]
MODELINGCOMPONENTS_API bool UE::Geometry::GetCurrentGeometrySelectionForTarget (UInteractiveToolManager * ToolManager, UToolTarget * Target, FGeometrySelection & SelectionOut)
Find an available FGeometrySelection for the given ToolTarget (via the UGeometrySelectionManager in the ContextObjectStore)
Parameters
SelectionOut non-empty selection will be returned here
Returns
true if a non-empty selection was found
References Target.
GetCurrentSelectionWorldFrameBounds()
MODELINGCOMPONENTS_API bool UE::Geometry::GetCurrentSelectionWorldFrameBounds (const FToolBuilderState & SceneState, FFrame3d & OutWorldFrame, FAxisAlignedBox3d & OutWorldBounds, bool & bOutIsElementSelection)
Find the frame and bounds representative of the current selection, if there is one.
Parameters
SceneState Scene state info, including current selection
OutWorldFrame Frame centered on the current selection and (when sensible) aligned to the selected elements
OutWorldBounds Bounds of the current selection
bOutIsElementSelection Whether the selection is a mesh element selection, or a regular editor/actor selection
Returns
true if a selection was found, false otherwise.
GetDefaultRenderCaptureConfig()
FRenderCaptureConfig MODELINGCOMPONENTS_API UE::Geometry::GetDefaultRenderCaptureConfig (ERenderCaptureType CaptureType)
GetDetailMeshTrianglePoint_Nearest()
const void * UE::Geometry::GetDetailMeshTrianglePoint_Nearest (const IMeshBakerDetailSampler * DetailSpatial, const FVector3d & BasePoint, int32 & DetailTriangleOut, FVector3d & DetailTriBaryCoords)
Compute base/detail mesh correspondence by nearest distance.
Returns
a pointer to the nearest mesh, otherwise nullptr.
GetDetailMeshTrianglePoint_Raycast()
const void * UE::Geometry::GetDetailMeshTrianglePoint_Raycast (const IMeshBakerDetailSampler * DetailSpatial, const FVector3d & BasePoint, const FVector3d & BaseNormal, int32 & DetailTriangleOut, FVector3d & DetailTriBaryCoords, double Thickness, bool bFailToNearestPoint)
Compute base/detail mesh correspondence by raycast.
Returns
a pointer to the hit mesh, otherwise nullptr.
GetDynamicMeshViaMeshDescription()
MODELINGCOMPONENTS_API FDynamicMesh3 UE::Geometry::GetDynamicMeshViaMeshDescription (IMeshDescriptionProvider & MeshDescriptionProvider, const FGetMeshParameters & InGetMeshParams = FGetMeshParameters())
References GetDynamicMeshViaMeshDescription().
Referenced by GetDynamicMeshViaMeshDescription(), and UE_DEPRECATED().
GetFKElement() [1/5]
void UE::Geometry::GetFKElement (const FCapsule3d & Capsule, FKSphylElem & CapsuleInOut) inline
Convert FCapsule3d to FKSphylElem.
Definition at line 46 of file CollisionGeometryConversion.h.
References Capsule, float, FVector, UE::Geometry::TFrame3< RealType >::Origin, and UE::Geometry::TFrame3< RealType >::Rotation.
GetFKElement() [2/5]
void UE::Geometry::GetFKElement (const FDynamicMesh3 & Mesh, FKConvexElem & ConvexInOut) inline
Convert FDynamicMesh3 to FKConvexElem.
Definition at line 59 of file CollisionGeometryConversion.h.
References FVector, and Mesh.
GetFKElement() [3/5]
void UE::Geometry::GetFKElement (const FOrientedBox3d & Box, FKBoxElem & BoxInOut) inline
Convert FOrientedBox3d to FKBoxElem.
Definition at line 33 of file CollisionGeometryConversion.h.
References Box, float, and FVector.
GetFKElement() [4/5]
void UE::Geometry::GetFKElement (const FSphere3d & Sphere, FKSphereElem & ElemInOut) inline
Convert FSphere3d to FKSphereElem.
Definition at line 24 of file CollisionGeometryConversion.h.
References float, FVector, and Sphere.
GetFKElement() [5/5]
void UE::Geometry::GetFKElement (const FTransform3d & GridTransform, const FDenseGrid3f & Grid, float CellSize, FKLevelSetElem & LevelSetOut) inline
Create FKLevelSet from the given grid information.
Definition at line 76 of file CollisionGeometryConversion.h.
References UE::Math::TTransform< T >::AddToTranslation(), Grid, TArray< InElementType, InAllocatorType >::Init(), and UE::Math::TVector< double >::One().
GetGroupEdgeRepresentativeVerts() [1/2]
MODELINGCOMPONENTS_API FIndex2i UE::Geometry::GetGroupEdgeRepresentativeVerts (const FGroupTopology & TopologyIn, int GroupEdgeID)
Returns a pair of vertex ID's that are representative of a group edge, to be able to identify a selected group edge independently of a group topology object.
See other overload for more details.
GetGroupEdgeRepresentativeVerts() [2/2]
MODELINGCOMPONENTS_API FIndex2i UE::Geometry::GetGroupEdgeRepresentativeVerts (const FGroupTopology & TopologyIn, int GroupEdgeID, const FCompactMaps & CompactMaps)
Returns a pair of vertex ID's that are representative of a group edge, to be able to identify a selected group edge independently of a group topology object.
For non-loop group edges, this will be the vids of the lower-vid endpoint and its neighbor in the group edge, arranged in increasing vid order. For loop group edges, this will be the lowest vid in the group edge and its lower-vid neighbor in the group edge.
This is basically just identifying the group edge with a specific component edge, but using vids instead of an edge id makes it a bit easier to apply a compact mapping if the mesh was compacted, and helps the representative survive translation to/from a mesh description in cases of compaction.
Parameters
CompactMaps This gets used to remap the vids given in the topology first (i.e., it assumes that the CompactMaps have not yet been applied to the contents of the topology object).
GetRenderCaptureViewMatrices()
FViewMatrices UE::Geometry::GetRenderCaptureViewMatrices (const FFrame3d & ViewFrame, double HorzFOVDegrees, double NearPlaneDist, FImageDimensions ViewRect)
Returns the view matrices corresponding to the given render capture cameara parameters Useful to get the needed information to unproject the DeviceDepth render capture e.g., using the following.
FViewMatrices ViewMatrices = GetRenderCaptureViewMatrices(...); FVector2d DeviceXY = FRenderCaptureCoordinateConverter2D::PixelToDevice(...); FVector4d WorldPoint = ViewMatrices.GetInvViewProjectionMatrix().TransformPosition(FVector3d(DeviceXY, DeviceZ)); WorldPoint /= WorldPoint.W;
GetSceneCaptureConfig()
MODELINGCOMPONENTS_API FSceneCaptureConfig UE::Geometry::GetSceneCaptureConfig (const FSceneCapturePhotoSet & SceneCapture, FSceneCapturePhotoSet::ECaptureTypeStatus QueryStatus = FSceneCapturePhotoSet::ECaptureTypeStatus::Computed)
References UE::Geometry::FSceneCapturePhotoSet::Computed, QueryStatus, and SceneCapture.
GetSelectionBoundaryCorners()
DYNAMICMESH_API bool UE::Geometry::GetSelectionBoundaryCorners (const UE::Geometry::FDynamicMesh3 & Mesh, const UE::Geometry::FGroupTopology * GroupTopology, const UE::Geometry::FGeometrySelection & ReferenceSelection, TSet< int32 > & BorderCornerIDsOut, TSet< int32 > & CurCornerIDsOut)
Given a EGeometryTopologyType::Polygroup selection, return the corner IDs of the polygroup corners on the boundary of the selection.
A selected corner is considered to be on the boundary either if it is on the actual mesh boundary (for an open mesh) or it is connected to an element that is not part of the selection (i.e. if there is a neighbor corner not in the selection for a selection of type EGeometryElementType::Vertex, or an adjoining edge not in the selection for a selection of type EGeometryElementType::Edge, or an adjoining group not in the selection for a selection of type EGeometryElementType::Face).
Selection must be of type EGeometryTopologyType::Polygroup, and GroupTopology must not be null.
Parameters
GroupTopology Must not be null
BorderCornerIDsOut Output corner IDs of border corners
CurCornerIDsOut Output corner IDs of all corners included in the current selection
Returns
true if successful. For instance, could fail if GroupTopology was null
References GetSelectionBoundaryCorners(), and Mesh.
Referenced by GetSelectionBoundaryCorners().
GetSelectionBoundaryVertices()
DYNAMICMESH_API bool UE::Geometry::GetSelectionBoundaryVertices (const UE::Geometry::FDynamicMesh3 & Mesh, const UE::Geometry::FGroupTopology * GroupTopology, const UE::Geometry::FGeometrySelection & ReferenceSelection, TSet< int32 > & BorderVidsOut, TSet< int32 > & CurVerticesOut)
Given a selection, return the vertex IDs of the vertices on the boundary of this selection.
A selected vertex is considered to be on the boundary either if it is on the actual mesh boundary (for an open mesh) or it is connected to a triangle element that is not part of the selection (i.e. if the vertex has a neighbor vertex not in selection for a selection of type EGeometryElementType::Vertex, or an adjacent edge not in selection for a selection of type EGeometryElementType::Edge, an adjacent triangle not in the selection for a selection of type EGeometryElementType::Face).
For selections of type EGeometryTopologyType::Polygroup, the results are equivalent to first converting the selection to corresponding EGeometryTopologyType::Triangle selection and then finding the boundary vertices. This gives the intuitive result for face selections, but may or may not be what is desired for polygroup vertex/edge selections, because vertices/edges that seem to be on the interior of the polygroup selection may be considered border vertices if the tesselation is such that they are adjacent to unselected triangle vertices/edges.
Parameters
GroupTopology Must not be null for selections of type EGeometryTopologyType::Polygroup
BorderVidsOut Output vertex IDs of border vertices
CurVerticesOut Output vertex IDs of all vertices in the current selection
Returns
true if successful. For instance, could fail if GroupTopology was null for a EGeometryTopologyType::Polygroup selection
References GetSelectionBoundaryVertices(), and Mesh.
Referenced by GetSelectionBoundaryVertices().
GetShape() [1/6]
void UE::Geometry::GetShape (const FKBoxElem & BoxElem, FBoxShape3d & BoxShapeOut) inline
Convert FKBoxElem to FBoxShape3d.
Definition at line 115 of file CollisionGeometryConversion.h.
References UE::Geometry::FBoxShape3d::Box, UE::Geometry::TOrientedBox3< RealType >::Extents, UE::Geometry::TOrientedBox3< RealType >::Frame, UE::Geometry::TFrame3< RealType >::Origin, and UE::Geometry::TFrame3< RealType >::Rotation.
GetShape() [2/6]
void UE::Geometry::GetShape (const FKConvexElem & ConvexElem, FConvexShape3d & ConvexShapeOut) inline
Convert FKConvexElem to FConvexShape3d.
Definition at line 155 of file CollisionGeometryConversion.h.
References GetShape(), and UE::Geometry::FConvexShape3d::Mesh.
GetShape() [3/6]
void UE::Geometry::GetShape (const FKConvexElem & ConvexElem, FDynamicMesh3 & MeshOut) inline
Convert FKConvexElem to FDynamicMesh3.
Definition at line 138 of file CollisionGeometryConversion.h.
References UE::Geometry::FDynamicMesh3::AppendTriangle(), UE::Geometry::FDynamicMesh3::AppendVertex(), and UE::Geometry::FDynamicMesh3::Clear().
GetShape() [4/6]
void UE::Geometry::GetShape (const FKLevelSetElem & LevelSetElem, FLevelSetShape3d & LevelSetShapeOut) inline
Convert FKLevelSetElem to FLevelSetShape3d.
Definition at line 163 of file CollisionGeometryConversion.h.
References UE::Math::TTransform< T >::AddToTranslation(), UE::Geometry::FLevelSetShape3d::CellSize, ensure, UE::Geometry::FLevelSetShape3d::Grid, UE::Geometry::FLevelSetShape3d::GridTransform, TArray< InElementType, InAllocatorType >::Num(), UE::Math::TVector< double >::One(), and UE::Geometry::TDenseGrid3< ElemType >::Resize().
GetShape() [5/6]
void UE::Geometry::GetShape (const FKSphereElem & SphereElem, FSphereShape3d & SphereShapeOut) inline
Convert FKSphereElem to FSphereShape3d.
Definition at line 106 of file CollisionGeometryConversion.h.
References UE::Geometry::TSphere3< T >::Center, UE::Geometry::TSphere3< T >::Radius, and UE::Geometry::FSphereShape3d::Sphere.
Referenced by GetShape(), and GetShapeSet().
GetShape() [6/6]
void UE::Geometry::GetShape (const FKSphylElem & CapsuleElem, UE::Geometry::FCapsuleShape3d & CapsuleShapeOut) inline
Convert FKSphylElem to FCapsuleShape3d.
Definition at line 125 of file CollisionGeometryConversion.h.
References UE::Geometry::TQuaternion< RealType >::AxisZ(), UE::Geometry::FCapsuleShape3d::Capsule, UE::Geometry::TSegment3< T >::Center, UE::Geometry::TSegment3< T >::Direction, UE::Geometry::TSegment3< T >::Extent, UE::Geometry::TCapsule3< T >::Radius, and UE::Geometry::TCapsule3< T >::Segment.
GetShapeSet()
void UE::Geometry::GetShapeSet (const FKAggregateGeom & AggGeom, FSimpleShapeSet3d & ShapeSetOut) inline
Convert FKAggregateGeom to FSimpleShapeSet3d.
Definition at line 199 of file CollisionGeometryConversion.h.
References TArray< InElementType, InAllocatorType >::Add(), UE::Geometry::FSimpleShapeSet3d::Boxes, UE::Geometry::FSimpleShapeSet3d::Capsules, UE::Geometry::FSimpleShapeSet3d::Convexes, GetShape(), UE::Geometry::FSimpleShapeSet3d::LevelSets, and UE::Geometry::FSimpleShapeSet3d::Spheres.
GetTargetActorViaIPersistentDynamicMeshSource()
MESHMODELINGTOOLSEXP_API AActor * UE::Geometry::GetTargetActorViaIPersistentDynamicMeshSource (UToolTarget * Target)
Returns
AActor that owns a DynamicMeshComponent from a tool target, or nullptr if there is no such Actor
References Target.
GetTexturesFromRenderCaptureBaker()
MODELINGCOMPONENTS_API void UE::Geometry::GetTexturesFromRenderCaptureBaker (FMeshMapBaker & Baker, FRenderCaptureTextures & TexturesOut)
References PRAGMA_DISABLE_DEPRECATION_WARNINGS, and TexturesOut.
Referenced by UE_DEPRECATED().
GetTriangleSelectionFrame()
DYNAMICMESH_API bool UE::Geometry::GetTriangleSelectionFrame (const FGeometrySelection & MeshSelection, const UE::Geometry::FDynamicMesh3 & Mesh, FFrame3d & SelectionFrameOut)
Compute a 3D Frame suitable for use as a 3D transform gizmo position/orientation for the given MeshSelection.
References Mesh.
GetTypeHash() [1/6]
FORCEINLINE uint32 UE::Geometry::GetTypeHash (const FIndex2i & Index)
Definition at line 141 of file IndexTypes.h.
References FORCEINLINE, and FCrc::MemCrc_DEPRECATED().
GetTypeHash() [2/6]
FORCEINLINE uint32 UE::Geometry::GetTypeHash (const FIndex3i & Index)
Definition at line 280 of file IndexTypes.h.
References FORCEINLINE, and FCrc::MemCrc_DEPRECATED().
GetTypeHash() [3/6]
FORCEINLINE uint32 UE::Geometry::GetTypeHash (const FIndex4i & Index)
Definition at line 388 of file IndexTypes.h.
References FORCEINLINE, and FCrc::MemCrc_DEPRECATED().
GetTypeHash() [4/6]
FORCEINLINE uint32 UE::Geometry::GetTypeHash (const FSceneGeometryID & Identifier)
Definition at line 103 of file SceneGeometrySpatialCache.h.
References FORCEINLINE, and UE::Geometry::FSceneGeometryID::UniqueID.
GetTypeHash() [5/6]
FORCEINLINE uint32 UE::Geometry::GetTypeHash (const FVector2i & Vector)
Definition at line 241 of file IntVectorTypes.h.
References FORCEINLINE, FCrc::MemCrc_DEPRECATED(), and Vector.
GetTypeHash() [6/6]
FORCEINLINE uint32 UE::Geometry::GetTypeHash (const FVector3i & Vector)
Definition at line 507 of file IntVectorTypes.h.
References FORCEINLINE, FCrc::MemCrc_DEPRECATED(), and Vector.
GetXY()
template<typename T> UE::Math::TVector2< T > UE::Geometry::GetXY (const UE::Math::TVector< T > & V) constexpr
Definition at line 262 of file VectorTypes.h.
References UE::Math::TVector< T >::X, and UE::Math::TVector< T >::Y.
Referenced by UE::Geometry::TIntrTriangle3Triangle3< float >::GetCoplanarIntersection(), and UE::Geometry::TIntrTriangle3Triangle3< float >::IntersectTriangleWithCoplanarSegment().
GetXZ()
template<typename T> UE::Math::TVector2< T > UE::Geometry::GetXZ (const UE::Math::TVector< T > & V) constexpr
Definition at line 268 of file VectorTypes.h.
References UE::Math::TVector< T >::X, and UE::Math::TVector< T >::Z.
Referenced by UE::Geometry::TIntrTriangle3Triangle3< float >::GetCoplanarIntersection(), and UE::Geometry::TIntrTriangle3Triangle3< float >::IntersectTriangleWithCoplanarSegment().
GetYZ()
template<typename T> UE::Math::TVector2< T > UE::Geometry::GetYZ (const UE::Math::TVector< T > & V) constexpr
Definition at line 274 of file VectorTypes.h.
References UE::Math::TVector< T >::Y, and UE::Math::TVector< T >::Z.
Referenced by UE::Geometry::TIntrTriangle3Triangle3< float >::GetCoplanarIntersection(), and UE::Geometry::TIntrTriangle3Triangle3< float >::IntersectTriangleWithCoplanarSegment().
HaveAvailableGeometrySelection()
MODELINGCOMPONENTS_API bool UE::Geometry::HaveAvailableGeometrySelection (const FToolBuilderState & SceneState)
Returns
true if there is currently any geometry selection available in the SceneState
InitializeGeometrySelectionVisualization()
void MODELINGCOMPONENTS_API UE::Geometry::InitializeGeometrySelectionVisualization (UPreviewGeometry * PreviewGeom, UGeometrySelectionVisualizationProperties * Settings, const FDynamicMesh3 & SourceMesh, const FGeometrySelection & Selection, const FGroupTopology * GroupTopology = nullptr, const FGeometrySelection * TriangleVertexSelection = nullptr, const TArray< int > * TriangleROI = nullptr, const FTransform * ApplyTransform = nullptr)
Initialize the geometry selection preview geometry.
Call this in your tool Setup function
References ApplyTransform.
InitializeSelectionFromTriangles()
DYNAMICMESH_API bool UE::Geometry::InitializeSelectionFromTriangles (const UE::Geometry::FDynamicMesh3 & Mesh, const FGroupTopology * GroupTopology, TArrayView< const int > Triangles, FGeometrySelection & SelectionOut)
Convert Triangle IDs to target Selection type.
References ConvertSelection(), InitializeSelectionFromTriangles(), Mesh, and UE_DEPRECATED().
Referenced by InitializeSelectionFromTriangles().
IsBoxMesh()
bool DYNAMICMESH_API UE::Geometry::IsBoxMesh (const FDynamicMesh3 & Mesh, FOrientedBox3d & BoxOut, double AngleToleranceDeg = 0.1, double PlaneDistanceTolerance = 1e-2)
Detect if input Mesh is a meshed box, and if so return analytic box in BoxOut.
Clusters face planes, looking to find 6 unique planes with normals grouped into 3 opposite-direction pairs. If this configuraiton is found, computing minimal box is trivial.
Parameters
AngleToleranceDeg normals are allowed to deviate by this amount and still be considered coplanar
PlaneDistanceTolerance planes with the same normal are allowed to be this far apart and still be considered coplanar
Returns
true if mesh is a Box and BoxOut is initialized
References Mesh.
IsCapsuleMesh()
bool DYNAMICMESH_API UE::Geometry::IsCapsuleMesh (const FDynamicMesh3 & Mesh, FCapsule3d & CapsuleOut, double RelativeDeviationTol = 0.025, double MaxAngleRangeDegrees = 72)
Detect if input Mesh is a meshed approximation of an analytic Capsule, and if so return best guess in CapsuleOut.
Fits a capsule to input points, then measures chordal deviation of edge midpoints.
Parameters
RelativeDeviationTol Scaled by capsule diameter. The allowed difference in the distance from edge midpoints to the surface of the capsule vs the ideal distance for an edge of the same length.
MaxAngleRangeDegrees Maximum angle range an edge can cover over the cylinder or the spherical endcaps. Controls how coarsely tessellated a capsule can be before it is not considered a capsule.
Returns
true if mesh is a Capsule and CapsuleOut is initialized
References Mesh.
IsInside() [1/21]
template<typename RealType> GEOMETRYCORE_API bool UE::Geometry::IsInside (const TCapsule3< RealType > & OuterCapsule, const TCapsule3< RealType > & InnerCapsule)
Returns
true if InnerCapsule is fully contained within OuterCapsule
IsInside() [2/21]
template<typename RealType> GEOMETRYCORE_API bool UE::Geometry::IsInside (const TCapsule3< RealType > & OuterCapsule, const TOrientedBox3< RealType > & InnerBox)
Returns
true if InnerBox is fully contained within OuterCapsule
IsInside() [3/21]
template<typename RealType> GEOMETRYCORE_API bool UE::Geometry::IsInside (const TCapsule3< RealType > & OuterCapsule, const TSphere3< RealType > & InnerSphere)
Returns
true if InnerSphere is fully contained within OuterCapsule
IsInside() [4/21]
template<typename RealType, typename GridType> bool UE::Geometry::IsInside (const TCapsule3< RealType > & OuterCapsule, const TTriLinearGridInterpolant< GridType > & InnerGrid)
Returns
true if the AABB of InnerGrid is completely inside OuterCapsule
Definition at line 102 of file ContainmentQueries3.h.
References UE::Geometry::TTriLinearGridInterpolant< GridType, RealType, bScalarCellSize >::Bounds(), and IsInside().
IsInside() [5/21]
template<typename RealType, typename EnumerablePointsType, typename E = decltype(DeclVal<EnumerablePointsType>().begin())> bool UE::Geometry::IsInside (const TCapsule3< RealType > & OuterCapsule, EnumerablePointsType EnumerablePts)
Returns
true if all all points in range-based for over EnumerablePts are inside OuterCapsule
Definition at line 88 of file ContainmentQueries3.h.
References UE::Geometry::TCapsule3< T >::Contains(), and Point.
IsInside() [6/21]
template<typename RealType> GEOMETRYCORE_API bool UE::Geometry::IsInside (const TOrientedBox3< RealType > & OuterBox, const TCapsule3< RealType > & InnerCapsule)
Returns
true if InnerCapsule is fully contained within OuterBox
IsInside() [7/21]
template<typename RealType> GEOMETRYCORE_API bool UE::Geometry::IsInside (const TOrientedBox3< RealType > & OuterBox, const TOrientedBox3< RealType > & InnerBox)
Returns
true if InnerBox is fully contained within OuterBox
IsInside() [8/21]
template<typename RealType> GEOMETRYCORE_API bool UE::Geometry::IsInside (const TOrientedBox3< RealType > & OuterBox, const TSphere3< RealType > & InnerSphere)
Returns
true if InnerSphere is fully contained within OuterBox
IsInside() [9/21]
template<typename RealType, typename GridType> bool UE::Geometry::IsInside (const TOrientedBox3< RealType > & OuterBox, const TTriLinearGridInterpolant< GridType > & InnerGrid)
Returns
true if the AABB of InnerGrid is completely inside OuterBox
Definition at line 141 of file ContainmentQueries3.h.
References UE::Geometry::TTriLinearGridInterpolant< GridType, RealType, bScalarCellSize >::Bounds(), and IsInside().
IsInside() [10/21]
template<typename RealType, typename EnumerablePointsType, typename E = decltype(DeclVal<EnumerablePointsType>().begin())> bool UE::Geometry::IsInside (const TOrientedBox3< RealType > & OuterBox, EnumerablePointsType EnumerablePts)
Returns
true if all all points in range-based for over EnumerablePts are inside OuterBox
Definition at line 127 of file ContainmentQueries3.h.
References UE::Geometry::TOrientedBox3< RealType >::Contains(), and Point.
IsInside() [11/21]
template<typename RealType> GEOMETRYCORE_API bool UE::Geometry::IsInside (const TSphere3< RealType > & OuterSphere, const TCapsule3< RealType > & InnerCapsule)
Returns
true if InnerCapsule is fully contained within OuterSphere
IsInside() [12/21]
template<typename RealType> GEOMETRYCORE_API bool UE::Geometry::IsInside (const TSphere3< RealType > & OuterSphere, const TOrientedBox3< RealType > & InnerBox)
Returns
true if InnerBox is fully contained within OuterSphere
IsInside() [13/21]
template<typename RealType> GEOMETRYCORE_API bool UE::Geometry::IsInside (const TSphere3< RealType > & OuterSphere, const TSphere3< RealType > & InnerSphere)
Returns
true if InnerSphere is fully contained within OuterSphere
Referenced by IsInside(), IsInside(), IsInside(), IsInside(), IsInside(), IsInside(), IsInside(), and IsInside().
IsInside() [14/21]
template<typename RealType, typename GridType> bool UE::Geometry::IsInside (const TSphere3< RealType > & OuterSphere, const TTriLinearGridInterpolant< GridType > & InnerGrid)
Returns
true if the AABB of InnerGrid is completely inside OuterSphere
Definition at line 63 of file ContainmentQueries3.h.
References UE::Geometry::TTriLinearGridInterpolant< GridType, RealType, bScalarCellSize >::Bounds(), and IsInside().
IsInside() [15/21]
template<typename RealType, typename EnumerablePointsType, typename E = decltype(DeclVal<EnumerablePointsType>().begin())> bool UE::Geometry::IsInside (const TSphere3< RealType > & OuterSphere, EnumerablePointsType EnumerablePts)
Returns
true if all all points in range-based for over EnumerablePts are inside OuterSphere
Definition at line 49 of file ContainmentQueries3.h.
References UE::Geometry::TSphere3< T >::Contains(), and Point.
IsInside() [16/21]
template<typename RealType, typename GridType> bool UE::Geometry::IsInside (const TTriLinearGridInterpolant< GridType > & OuterGrid, const TTransform< RealType > & OuterGridTransform, const TCapsule3< RealType > & InnerCapsule)
Test if the axis-aligned bounding box of InnerCapsule is completely inside the negative region of the signed distance field discretized on OuterGrid.
Definition at line 364 of file ContainmentQueries3.h.
References UE::Geometry::TCapsule3< T >::GetBounds(), and IsInside().
IsInside() [17/21]
template<typename RealType, typename GridType> bool UE::Geometry::IsInside (const TTriLinearGridInterpolant< GridType > & OuterGrid, const TTransform< RealType > & OuterGridTransform, const TOrientedBox3< RealType > & InnerBox)
Test if the axis-aligned bounding box of InnerBox is completely inside the negative region of the signed distance field discretized on OuterGrid.
Definition at line 375 of file ContainmentQueries3.h.
References UE::Geometry::TAxisAlignedBox3< RealType >::Contain(), UE::Geometry::TOrientedBox3< RealType >::EnumerateCorners(), UE::Math::TTransform< T >::InverseTransformPosition(), and IsInside().
IsInside() [18/21]
template<typename RealType, typename GridType> bool UE::Geometry::IsInside (const TTriLinearGridInterpolant< GridType > & OuterGrid, const TTransform< RealType > & OuterGridTransform, const TSphere3< RealType > & InnerSphere)
Test if the axis-aligned bounding box of InnerSphere is completely inside the negative region of the signed distance field discretized on OuterGrid.
Definition at line 350 of file ContainmentQueries3.h.
References UE::Geometry::TSphere3< T >::Center, UE::Math::TTransform< T >::InverseTransformPosition(), IsInside(), UE::Math::TVector< T >::OneVector, and UE::Geometry::TSphere3< T >::Radius.
IsInside() [19/21]
template<typename RealType, typename GridType, typename EnumerablePointsType, typename E = decltype(DeclVal<EnumerablePointsType>().begin())> bool UE::Geometry::IsInside (const TTriLinearGridInterpolant< GridType > & OuterGrid, const TTransform< RealType > & OuterGridTransform, EnumerablePointsType EnumerablePts)
Test if all enumerable points are inside the negative region of the signed distance field discretized on OuterGrid.
Definition at line 387 of file ContainmentQueries3.h.
References UE::Geometry::TAxisAlignedBox3< RealType >::Contain(), UE::Math::TTransform< T >::InverseTransformPosition(), IsInside(), and Point.
IsInside() [20/21]
template<typename RealType, typename GridType> bool UE::Geometry::IsInside (const TTriLinearGridInterpolant< GridType > & OuterGrid, const UE::Geometry::TAxisAlignedBox3< RealType > & InnerAABB)
Definition at line 315 of file ContainmentQueries3.h.
References UE::Geometry::TTriLinearGridInterpolant< GridType, RealType, bScalarCellSize >::Cell(), UE::Geometry::TTriLinearGridInterpolant< GridType, RealType, bScalarCellSize >::Dimensions, UE::Geometry::TTriLinearGridInterpolant< GridType, RealType, bScalarCellSize >::Grid, UE::Geometry::TAxisAlignedBox3< RealType >::Max, and UE::Geometry::TAxisAlignedBox3< RealType >::Min.
IsInside() [21/21]
template<typename RealType, typename GridType1, typename GridType2> bool UE::Geometry::IsInside (const TTriLinearGridInterpolant< GridType1 > & OuterGrid, const TTransform< RealType > & OuterGridTransform, const TTriLinearGridInterpolant< GridType2 > & InnerGrid, const TTransform< RealType > & InnerGridTransform)
Test if the axis-aligned bounding box of InnerGrid is completely inside the negative region of the signed distance field discretized on OuterGrid.
Definition at line 222 of file ContainmentQueries3.h.
References UE::Geometry::TTriLinearGridInterpolant< GridType, RealType, bScalarCellSize >::Bounds(), UE::Math::TTransform< T >::Inverse(), and IsInside().
IsInsideHull() [1/5]
template<typename RealType> bool UE::Geometry::IsInsideHull (TArrayView< THalfspace3< RealType > > Halfspaces, const TCapsule3< RealType > & InnerCapsule)
Test if the convex volume defined by a set of Halfspaces contains InnerCapsule.
Each Halfspace normal should point "outwards", ie it defines the outer halfspace that is not inside the Convex Volume.
Returns
false if InnerCapsule intersects any of the Halfspaces
Definition at line 257 of file ContainmentQueries3.h.
References TestIntersection().
IsInsideHull() [2/5]
template<typename RealType> bool UE::Geometry::IsInsideHull (TArrayView< THalfspace3< RealType > > Halfspaces, const TOrientedBox3< RealType > & InnerBox)
Test if the convex volume defined by a set of Halfspaces contains InnerBox.
Each Halfspace normal should point "outwards", ie it defines the outer halfspace that is not inside the Convex Volume.
Returns
false if InnerBox intersects any of the Halfspaces
Definition at line 271 of file ContainmentQueries3.h.
References TestIntersection().
IsInsideHull() [3/5]
template<typename RealType> bool UE::Geometry::IsInsideHull (TArrayView< THalfspace3< RealType > > Halfspaces, const TSphere3< RealType > & InnerSphere)
Test if the convex volume defined by a set of Halfspaces contains InnerSphere.
Each Halfspace normal should point "outwards", ie it defines the outer halfspace that is not inside the Convex Volume.
Returns
false if InnerSphere intersects any of the Halfspaces
Definition at line 243 of file ContainmentQueries3.h.
References TestIntersection().
Referenced by IsInsideHull().
IsInsideHull() [4/5]
template<typename RealType, typename GridType> bool UE::Geometry::IsInsideHull (TArrayView< THalfspace3< RealType > > Halfspaces, const TTriLinearGridInterpolant< GridType > & InnerGrid)
Definition at line 184 of file ContainmentQueries3.h.
References UE::Geometry::TTriLinearGridInterpolant< GridType, RealType, bScalarCellSize >::Bounds(), and IsInsideHull().
IsInsideHull() [5/5]
template<typename RealType, typename EnumerablePointsType, typename E = decltype(DeclVal<EnumerablePointsType>().begin())> bool UE::Geometry::IsInsideHull (TArrayView< THalfspace3< RealType > > Halfspaces, EnumerablePointsType EnumerablePts)
Test if the convex volume defined by a set of Halfspaces contains InnerSphere.
Each Halfspace normal should point "outwards", ie it defines the outer halfspace that is not inside the Convex Volume.
Returns
false any of the Halfspaces contain any of the Points
Definition at line 285 of file ContainmentQueries3.h.
References Point.
IsNormalized() [1/2]
template<typename T> bool UE::Geometry::IsNormalized (const UE::Math::TVector2< T > & Vector, const T Tolerance = TMathUtil<T>::ZeroTolerance) constexpr
Definition at line 40 of file VectorTypes.h.
References TMathUtil< RealType >::Abs(), and Vector.
Referenced by UE::Geometry::TIntrLine2Line2< double >::Find(), UE::Geometry::TIntrLine2Triangle2< float >::Find(), UE::Geometry::TIntrSegment2Segment2< double >::Find(), and UE::Geometry::TIntrSegment2Triangle2< float >::Find().
IsNormalized() [2/2]
template<typename T> bool UE::Geometry::IsNormalized (const UE::Math::TVector< T > & Vector, const T Tolerance = TMathUtil<T>::ZeroTolerance) constexpr
Definition at line 161 of file VectorTypes.h.
References TMathUtil< RealType >::Abs(), and Vector.
IsSphereMesh()
bool DYNAMICMESH_API UE::Geometry::IsSphereMesh (const FDynamicMesh3 & Mesh, FSphere3d & SphereOut, double RelativeDeviationTol = 0.025, double MaxAngleRangeDegrees = 72)
Detect if input Mesh is a meshed approximation of an analytic Sphere, and if so return best guess in SphereOut.
Fits a sphere to input points with several rounds of incremental improvement, then measures chordal deviation of edge midpoints.
Parameters
RelativeDeviationTol Scaled by sphere diameter. The allowed difference in the distance from edge midpoints to the surface of the sphere vs the ideal distance for an edge of the same length.
MaxAngleRangeDegrees Maximum angle difference in vectors from center of sphere to the endpoints of any surface edge. Controls how coarsely tessellated a sphere can be before it is not considered a sphere.
Returns
true if mesh is a Sphere and SphereOut is initialized
References Mesh.
IteratorDistance() [1/2]
template<typename IterT> int64 UE::Geometry::IteratorDistance (IterT Begin, IterT End)
Definition at line 107 of file ParallelTransformReduce.h.
References UE::Count, and End.
Referenced by ParallelTransformReduce(), and ParallelTransformReduce().
IteratorDistance() [2/2]
template<typename ContainerType, typename ElementType, typename SizeType> int64 UE::Geometry::IteratorDistance (TIndexedContainerIterator< ContainerType, ElementType, SizeType > Begin, TIndexedContainerIterator< ContainerType, ElementType, SizeType > End)
Definition at line 131 of file ParallelTransformReduce.h.
References End.
Length()
template<typename T> T UE::Geometry::Length (const UE::Math::TVector< T > & V)
Definition at line 148 of file VectorTypes.h.
References TMathUtil< RealType >::Sqrt(), UE::Math::TVector< T >::X, UE::Math::TVector< T >::Y, and UE::Math::TVector< T >::Z.
Referenced by UE::Geometry::TPlane3< FVector::FReal >::ClipSegment(), MeshDebugDraw::DrawNormals(), UE::Geometry::TMeshQueries< TriangleMeshType >::EdgeLengthStats(), UE::Geometry::TMeshQueries< TriangleMeshType >::EdgeLengthStatsFromEdges(), UE::Geometry::TMeshQueries< TriangleMeshType >::GetAllEdgeLengths(), UE::Geometry::TMeshQueries< TriangleMeshType >::MaxEdgeLength(), and UE::Geometry::TMeshQueries< TriangleMeshType >::MinEdgeLength().
Lerp() [1/4]
template<typename T> TFrame3< T > UE::Geometry::Lerp (const TFrame3< T > & A, const TFrame3< T > & B, T Alpha)
Definition at line 468 of file FrameTypes.h.
References A, Alpha, B, and Lerp().
Referenced by FPinchBrushOp::ApplyStamp(), FSmoothBrushOp::ApplyStamp(), FSmoothFillBrushOp::ApplyStamp(), Lerp(), and UE::Geometry::FIterativeOffsetMeshOp::Offset_Smoothed().
Lerp() [2/4]
template<typename T> UE::Math::TVector2< T > UE::Geometry::Lerp (const UE::Math::TVector2< T > & A, const UE::Math::TVector2< T > & B, T Alpha)
Definition at line 127 of file VectorTypes.h.
References A, Alpha, and B.
Lerp() [3/4]
template<typename T> UE::Math::TVector4< T > UE::Geometry::Lerp (const UE::Math::TVector4< T > & A, const UE::Math::TVector4< T > & B, T Alpha)
Definition at line 409 of file VectorTypes.h.
References A, Alpha, and B.
Lerp() [4/4]
template<typename T> UE::Math::TVector< T > UE::Geometry::Lerp (const UE::Math::TVector< T > & A, const UE::Math::TVector< T > & B, T Alpha)
Definition at line 356 of file VectorTypes.h.
References A, Alpha, and B.
MakeBoundaryConnectedSelection()
DYNAMICMESH_API bool UE::Geometry::MakeBoundaryConnectedSelection (const UE::Geometry::FDynamicMesh3 & Mesh, const FGroupTopology * GroupTopology, const FGeometrySelection & ReferenceSelection, TFunctionRef< bool(FGeoSelectionID)> SelectionIDPredicate, FGeometrySelection & BoundaryConnectedSelection)
Create a selection of the elements adjacent to the "Border" of the given ReferenceSelection and return in BoundaryConnectedSelection.
The type of selected element is defined by ReferenceSelection. Currently "adjacency" is defined as "included in the one-ring of the boundary vertices of the ReferenceSelection", ie first the vertices on boundary edges are found, and then their one-rings are enumerated. Note that this will include "inside" and "outside" adjacent elements, and for vertices, the boundary vertices will still also be included. The main purpose of this function is to implement expand/contract selection operations, which would typically involve first finding the boundary-connected set and then using CombineSelectionInPlace to modify the original selection.
Parameters
GroupTopology precomputed group topology for Mesh, can be passed as null for EGeometryTopologyType::Triangle selections
SelectionIDPredicate only elements that pass this filter will be expanded "to" (but elements of ReferenceSelection that fail the filter will still be included in output)
Returns
true if ReferenceSelection had a known geometry/topology type pair and BoundaryConnectedSelection was populated
References MakeBoundaryConnectedSelection(), and Mesh.
Referenced by MakeBoundaryConnectedSelection().
MakeBoundaryEdgeMidpointsAdapter()
FPointSetAdapterd GEOMETRYCORE_API UE::Geometry::MakeBoundaryEdgeMidpointsAdapter (const FDynamicMesh3 * Mesh)
Returns
Mesh boundary edge midpoints as a point set
References Mesh.
MakeDynamicMeshAdapter()
FTriangleMeshAdapterd GEOMETRYCORE_API UE::Geometry::MakeDynamicMeshAdapter (const FDynamicMesh3 * Mesh)
Returns
1:1 adapter of a FDynamicMesh; can be used as a starting point to create other adapters
References Mesh.
MakeEdgeMidpointsAdapter()
FPointSetAdapterd GEOMETRYCORE_API UE::Geometry::MakeEdgeMidpointsAdapter (const FDynamicMesh3 * Mesh)
Returns
mesh edge midpoints as a point set
References Mesh.
MakePointsAdapter()
FPointSetAdapterd GEOMETRYCORE_API UE::Geometry::MakePointsAdapter (const FDynamicPointSet3d * PointSet)
Returns
PointSet points as a point set
MakeRenderCaptureBaker()
MODELINGCOMPONENTS_API TUniquePtr< FMeshMapBaker > UE::Geometry::MakeRenderCaptureBaker (FDynamicMesh3 * BaseMesh, TSharedPtr< FMeshTangentsd, ESPMode::ThreadSafe > BaseMeshTangents, TSharedPtr< TArray< int32 >, ESPMode::ThreadSafe > BaseMeshUVCharts, FSceneCapturePhotoSet * SceneCapture, FSceneCapturePhotoSetSampler * Sampler, FRenderCaptureTypeFlags PendingBake, int32 TargetUVLayer, EBakeTextureResolution TextureImageSize, EBakeTextureSamplesPerPixel SamplesPerPixel, FRenderCaptureOcclusionHandler * OcclusionHandler)
References BaseMeshTangents, BaseMeshUVCharts, OcclusionHandler, PendingBake, Sampler, SamplesPerPixel, SceneCapture, TargetUVLayer, TextureImageSize, and ThreadSafe.
Referenced by UE_DEPRECATED().
MakeScriptError()
GEOMETRYSCRIPTINGCORE_API FGeometryScriptDebugMessage UE::Geometry::MakeScriptError (EGeometryScriptErrorType ErrorTypeIn, const FText & MessageIn)
References MakeScriptError().
Referenced by MakeScriptError().
MakeScriptWarning()
GEOMETRYSCRIPTINGCORE_API FGeometryScriptDebugMessage UE::Geometry::MakeScriptWarning (EGeometryScriptErrorType WarningTypeIn, const FText & MessageIn)
References MakeScriptWarning().
Referenced by MakeScriptWarning().
MakeSelectAllConnectedSelection()
DYNAMICMESH_API bool UE::Geometry::MakeSelectAllConnectedSelection (const UE::Geometry::FDynamicMesh3 & Mesh, const FGroupTopology * GroupTopology, const FGeometrySelection & ReferenceSelection, TFunctionRef< bool(FGeoSelectionID)> SelectionIDPredicate, TFunctionRef< bool(FGeoSelectionID A, FGeoSelectionID B)> IsConnectedPredicate, FGeometrySelection & AllConnectedSelection)
Expand the input ReferenceSelection to include all "connected" elements and return in AllConnectedSelection.
The type of selected element is defined by ReferenceSelection.
Parameters
GroupTopology precomputed group topology for Mesh, can be passed as null for EGeometryTopologyType::Triangle selections
SelectionIDPredicate only elements that pass this filter will be expanded "to" (but elements of ReferenceSelection that fail the filter will still be included in output)
IsConnectedPredicate this function determines if "A" should be considered connected to "B", ie can "expand" along that connection
Returns
true if ReferenceSelection had a known geometry/topology type pair and AllConnectedSelection was populated
References A, B, MakeSelectAllConnectedSelection(), and Mesh.
Referenced by MakeSelectAllConnectedSelection().
MakeSelectAllSelection()
DYNAMICMESH_API bool UE::Geometry::MakeSelectAllSelection (const UE::Geometry::FDynamicMesh3 & Mesh, const FGroupTopology * GroupTopology, TFunctionRef< bool(FGeoSelectionID)> SelectionIDPredicate, FGeometrySelection & AllSelection)
Select all elements of the provided Mesh and GroupTopology that pass the provided SelectionIDPredicate, and store in the output AllSelection.
The type of elements selected is defined by the existing configured type of the AllSelection parameter.
Parameters
GroupTopology precomputed group topology for Mesh, can be passed as null for EGeometryTopologyType::Triangle selections
Returns
true if AllSelection had a known geometry/topology type pair and was populated
References MakeSelectAllSelection(), and Mesh.
Referenced by MakeSelectAllSelection().
MakeTransformedDynamicMeshAdapter()
FTriangleMeshAdapterd GEOMETRYCORE_API UE::Geometry::MakeTransformedDynamicMeshAdapter (const FDynamicMesh3 * Mesh, FTransform3d Transform)
Returns
Transformed adapter of a FDynamicMesh
References Mesh, and Transform.
MakeTriCentroidsAdapter()
FPointSetAdapterd GEOMETRYCORE_API UE::Geometry::MakeTriCentroidsAdapter (const FDynamicMesh3 * Mesh)
Returns
Mesh triangle centroids as a point set
References Mesh.
MakeUniqueGroupLayerName()
DYNAMICMESH_API FString UE::Geometry::MakeUniqueGroupLayerName (const FDynamicMesh3 & Mesh, FString BaseName)
Returns
unique group layer name derived from BaseName by appending a numeric suffix in the form _0, _1, etc
References Mesh.
MakeUnitVector3()
template<typename T> UE::Math::TVector< T > UE::Geometry::MakeUnitVector3 (int32 Axis) constexpr
Returns
unit vector along axis X=0, Y=1, Z=2
Definition at line 139 of file VectorTypes.h.
References Axis, and FMath::Clamp().
MakeVerticesAdapter()
FPointSetAdapterd GEOMETRYCORE_API UE::Geometry::MakeVerticesAdapter (const FDynamicMesh3 * Mesh)
Returns
Mesh vertices as a point set
References Mesh.
Max() [1/2]
FVector3i UE::Geometry::Max (const FVector3i & V0, const FVector3i & V1) inline
Definition at line 492 of file IntVectorTypes.h.
References TMathUtil< RealType >::Max(), UE::Geometry::FVector3i::X, UE::Geometry::FVector3i::Y, and UE::Geometry::FVector3i::Z.
Referenced by UE::Geometry::FArrangement2d::FArrangement2d(), UE::Geometry::FArrangement2d::FArrangement2d(), UE::Geometry::TBoundsGridIndexer3< float >::TBoundsGridIndexer3(), UE::Geometry::TPointHashGrid3< PointDataType, double >::TPointHashGrid3(), UE::Geometry::TImageBuilder< PixelType >::BilinearSample(), UE::Geometry::TShiftGridIndexer2< float >::BoxFromGrid(), UE::Geometry::CurveUtil::ClipConvexToBounds(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::GetBox(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::GetBoxEps(), UE::Geometry::TShiftGridIndexer2< float >::ToGrid(), UE::Geometry::TShiftGridIndexer2< float >::ToGrid(), and UE::Geometry::FSphereCovering::TransformRange().
Max() [2/2]
template<typename T> UE::Math::TVector< T > UE::Geometry::Max (const UE::Math::TVector< T > & V0, const UE::Math::TVector< T > & V1) constexpr
Definition at line 289 of file VectorTypes.h.
References TMathUtil< RealType >::Max(), UE::Math::TVector< T >::X, UE::Math::TVector< T >::Y, and UE::Math::TVector< T >::Z.
MaxAbsElement()
template<typename T> T UE::Geometry::MaxAbsElement (const UE::Math::TVector< T > & Vector) constexpr
Definition at line 324 of file VectorTypes.h.
References TMathUtil< RealType >::Abs(), TMathUtil< RealType >::Max3(), and Vector.
Referenced by UE::Geometry::FGridBoxMeshGenerator::Generate(), and UE::Geometry::FMinimalBoxMeshGenerator::Generate().
MaxAbsElementIndex()
template<typename T> int32 UE::Geometry::MaxAbsElementIndex (const UE::Math::TVector< T > & Vector) constexpr
Returns
0/1/2 index of maximum absolute-value element
Definition at line 331 of file VectorTypes.h.
References TMathUtil< RealType >::Abs(), TMathUtil< RealType >::Max3Index(), and Vector.
MaxElement()
template<typename T> T UE::Geometry::MaxElement (const UE::Math::TVector< T > & Vector) constexpr
Definition at line 298 of file VectorTypes.h.
References TMathUtil< RealType >::Max3(), and Vector.
Referenced by UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::Compute(), and UE::Geometry::TCachingMeshSDF< TriangleMeshType >::Initialize().
MaxElementIndex()
template<typename T> int32 UE::Geometry::MaxElementIndex (const UE::Math::TVector< T > & Vector) constexpr
Returns
0/1/2 index of maximum element
Definition at line 305 of file VectorTypes.h.
References TMathUtil< RealType >::Max3Index(), and Vector.
Min() [1/2]
FVector3i UE::Geometry::Min (const FVector3i & V0, const FVector3i & V1) inline
Definition at line 485 of file IntVectorTypes.h.
References TMathUtil< RealType >::Min(), UE::Geometry::FVector3i::X, UE::Geometry::FVector3i::Y, and UE::Geometry::FVector3i::Z.
Referenced by UE::Geometry::TBoundsGridIndexer3< float >::TBoundsGridIndexer3(), UE::Geometry::TShiftGridIndexer2< float >::BoxFromGrid(), UE::Geometry::CurveUtil::ClipConvexToBounds(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::GetBox(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::GetBoxEps(), UE::Geometry::TShiftGridIndexer2< float >::ToGrid(), and UE::Geometry::TShiftGridIndexer2< float >::ToGrid().
Min() [2/2]
template<typename T> UE::Math::TVector< T > UE::Geometry::Min (const UE::Math::TVector< T > & V0, const UE::Math::TVector< T > & V1) constexpr
Definition at line 281 of file VectorTypes.h.
References TMathUtil< RealType >::Min(), UE::Math::TVector< T >::X, UE::Math::TVector< T >::Y, and UE::Math::TVector< T >::Z.
MinAbsElement()
template<typename T> T UE::Geometry::MinAbsElement (const UE::Math::TVector< T > & Vector) constexpr
Definition at line 337 of file VectorTypes.h.
References TMathUtil< RealType >::Abs(), TMathUtil< RealType >::Min3(), and Vector.
MinAbsElementIndex()
template<typename T> int32 UE::Geometry::MinAbsElementIndex (const UE::Math::TVector< T > & Vector) constexpr
Returns
0/1/2 index of minimum absolute-value element
Definition at line 344 of file VectorTypes.h.
References TMathUtil< RealType >::Abs(), TMathUtil< RealType >::Min3Index(), and Vector.
MinElement()
template<typename T> T UE::Geometry::MinElement (const UE::Math::TVector< T > & Vector) constexpr
Definition at line 311 of file VectorTypes.h.
References TMathUtil< RealType >::Min3(), and Vector.
MinElementIndex()
template<typename T> int32 UE::Geometry::MinElementIndex (const UE::Math::TVector< T > & Vector) constexpr
Returns
0/1/2 index of minimum element
Definition at line 318 of file VectorTypes.h.
References TMathUtil< RealType >::Min3Index(), and Vector.
Normalize() [1/2]
template<typename T> T UE::Geometry::Normalize (UE::Math::TVector2< T > & Vector, const T Epsilon = 0)
Definition at line 46 of file VectorTypes.h.
References Vector.
Normalize() [2/2]
template<typename T> T UE::Geometry::Normalize (UE::Math::TVector< T > & Vector, const T Epsilon = 0)
Definition at line 168 of file VectorTypes.h.
References Vector.
Normalized() [1/2]
template<typename T> UE::Math::TVector2< T > UE::Geometry::Normalized (const UE::Math::TVector2< T > & Vector, const T Epsilon = 0)
Definition at line 61 of file VectorTypes.h.
References Vector.
Referenced by FMoveBrushOp::ApplyStamp(), MeshAdapterTransforms::ApplyTransform(), and UE::Geometry::TQuaternion< RealType >::SetFromTo().
Normalized() [2/2]
template<typename T> UE::Math::TVector< T > UE::Geometry::Normalized (const UE::Math::TVector< T > & Vector, const T Epsilon = 0) constexpr
Definition at line 184 of file VectorTypes.h.
References Vector.
operator*() [1/8]
template<typename RealType> TQuaternion< RealType > UE::Geometry::operator* (const TQuaternion< RealType > & A, const TQuaternion< RealType > & B)
Definition at line 271 of file Quaternion.h.
References UE::Geometry::TQuaternion< RealType >::TQuaternion(), A, B, UE::Geometry::TQuaternion< RealType >::W, X, Y, and Z.
operator*() [2/8]
template<typename RealType> TVector< RealType > UE::Geometry::operator* (const TQuaternion< RealType > & Q, const UE::Math::TVector< RealType > & V)
Definition at line 308 of file Quaternion.h.
References UE::Geometry::TQuaternion< RealType >::W, UE::Geometry::TQuaternion< RealType >::X, UE::Math::TVector< T >::X, UE::Geometry::TQuaternion< RealType >::Y, UE::Math::TVector< T >::Y, UE::Geometry::TQuaternion< RealType >::Z, and UE::Math::TVector< T >::Z.
operator*() [3/8]
template<typename RealType> TQuaternion< RealType > UE::Geometry::operator* (const TQuaternion< RealType > & Q, RealType Scalar)
Definition at line 288 of file Quaternion.h.
References UE::Geometry::TQuaternion< RealType >::TQuaternion(), UE::Geometry::TQuaternion< RealType >::W, UE::Geometry::TQuaternion< RealType >::X, UE::Geometry::TQuaternion< RealType >::Y, and UE::Geometry::TQuaternion< RealType >::Z.
operator*() [4/8]
FVector2i UE::Geometry::operator* (int32 Scalar, const FVector2i & V) inline
Definition at line 230 of file IntVectorTypes.h.
References UE::Geometry::FVector2i::X, and UE::Geometry::FVector2i::Y.
operator*() [5/8]
FVector3i UE::Geometry::operator* (int32 Scalar, const FVector3i & V) inline
Definition at line 479 of file IntVectorTypes.h.
References UE::Geometry::FVector3i::X, UE::Geometry::FVector3i::Y, and UE::Geometry::FVector3i::Z.
operator*() [6/8]
template<typename RealType> TQuaternion< RealType > UE::Geometry::operator* (RealType Scalar, const TQuaternion< RealType > & Q)
Definition at line 282 of file Quaternion.h.
References UE::Geometry::TQuaternion< RealType >::TQuaternion(), UE::Geometry::TQuaternion< RealType >::W, UE::Geometry::TQuaternion< RealType >::X, UE::Geometry::TQuaternion< RealType >::Y, and UE::Geometry::TQuaternion< RealType >::Z.
operator*() [7/8]
template<typename RealType> TMatrix2< RealType > UE::Geometry::operator* (RealType Scale, const TMatrix2< RealType > & Mat) inline
Definition at line 489 of file MatrixTypes.h.
References UE::Geometry::TMatrix2< RealType >::Row0, UE::Geometry::TMatrix2< RealType >::Row1, Scale, UE::Math::TVector2< T >::X, and UE::Math::TVector2< T >::Y.
operator*() [8/8]
template<typename RealType> TMatrix3< RealType > UE::Geometry::operator* (RealType Scale, const TMatrix3< RealType > & Mat) inline
Definition at line 480 of file MatrixTypes.h.
References UE::Geometry::TMatrix3< RealType >::Row0, UE::Geometry::TMatrix3< RealType >::Row1, UE::Geometry::TMatrix3< RealType >::Row2, Scale, UE::Math::TVector< T >::X, UE::Math::TVector< T >::Y, and UE::Math::TVector< T >::Z.
operator+()
template<typename RealType> TQuaternion< RealType > UE::Geometry::operator+ (const TQuaternion< RealType > & A, const TQuaternion< RealType > & B)
Definition at line 295 of file Quaternion.h.
References UE::Geometry::TQuaternion< RealType >::TQuaternion(), A, and B.
operator-()
template<typename RealType> TQuaternion< RealType > UE::Geometry::operator- (const TQuaternion< RealType > & A, const TQuaternion< RealType > & B)
Definition at line 302 of file Quaternion.h.
References UE::Geometry::TQuaternion< RealType >::TQuaternion(), A, and B.
operator<<() [1/3]
std::ostream & UE::Geometry::operator<< (std::ostream & os, const FVector2i & Vec) inline
Definition at line 235 of file IntVectorTypes.h.
References UE::Geometry::FVector2i::X, and UE::Geometry::FVector2i::Y.
operator<<() [2/3]
std::ostream & UE::Geometry::operator<< (std::ostream & os, const FVector3i & Vec) inline
Definition at line 501 of file IntVectorTypes.h.
References UE::Geometry::FVector3i::X, UE::Geometry::FVector3i::Y, and UE::Geometry::FVector3i::Z.
operator<<() [3/3]
template<typename RealType> std::ostream & UE::Geometry::operator<< (std::ostream & os, const UE::Math::TVector< RealType > & Vec)
Definition at line 375 of file VectorTypes.h.
References UE::Math::TVector< T >::X, UE::Math::TVector< T >::Y, and UE::Math::TVector< T >::Z.
OptimizeOrientedBox3Points()
template<typename RealType> TOrientedBox3< RealType > GEOMETRYCORE_API UE::Geometry::OptimizeOrientedBox3Points (const TOrientedBox3< RealType > & InitialBox, int32 NumIterations, int32 NumPoints, TFunctionRef< TVector< RealType >(int32)> GetPointFunc, TFunctionRef< bool(int32)> Filter, EBox3FitCriteria FitMethod = EBox3FitCriteria::Volume, FProgressCancel * ProgressCancel = nullptr)
Improve an oriented bounding box fit iteratively.
Parameters
InitialBox An initial guess at an oriented bounding box fitting the points
NumIterations How many passes to take to improve the bounding
NumPoints Number of points to consider
GetPointFunc Function providing array-style access into points
Filter Optional filter to include only a subset of the points in the output hull
FitMethod What criteria to optimize
Returns
A best-fit TOrientedBox3 that contains the points
References Filter, and Volume.
Orient()
template<typename T> T UE::Geometry::Orient (const UE::Math::TVector2< T > & A, const UE::Math::TVector2< T > & B, const UE::Math::TVector2< T > & C)
Returns
> 0 if C is to the left of the line from A to B, < 0 if to the right, 0 if on the line
Definition at line 33 of file VectorTypes.h.
References A, B, and DotPerp().
Referenced by UE::Geometry::CurveUtil::Contains2(), UE::Geometry::TTriangle2< float >::IsInside(), UE::Geometry::TTriangle2< float >::IsInsideOrOn_Oriented(), UE::Geometry::CurveUtil::ProjectPointInsideConvexPolygon(), and UE::Geometry::TSegment2< FVector::FReal >::UE_DEPRECATED().
Orientation()
template<typename RealType> int UE::Geometry::Orientation (RealType X1, RealType Y1, RealType X2, RealType Y2, RealType & TwiceSignedArea)
Definition at line 50 of file SDFCalculationUtils.h.
Referenced by UE::Geometry::TPlanarComplex< double >::FindSolidRegions(), UE::Geometry::FMeshPlanarSymmetry::GetMirroredOrientation(), and UE::Geometry::TCachingMeshSDF< TriangleMeshType >::PointInTriangle2d().
ParallelTransformReduce() [1/4]
template<typename IntType, typename T, typename TransformFuncT, typename ReduceFuncT> T UE::Geometry::ParallelTransformReduce (IntType Num, const T & Init, TransformFuncT Transform, ReduceFuncT Reduce, int64 InNumTasks)
Definition at line 17 of file ParallelTransformReduce.h.
References TMathUtil< float >::Ceil(), check, End, Init, MAX_int32, FMath::Min, Num, ParallelFor(), PartialResult, TArray< InElementType, InAllocatorType >::SetNum(), and Transform.
Referenced by FastTriWinding::ComputeCoeffs().
ParallelTransformReduce() [2/4]
template<typename IntType, typename T, typename InitFuncT, typename TransformFuncT, typename ReduceFuncT> void UE::Geometry::ParallelTransformReduce (IntType Num, InitFuncT InitFunc, TransformFuncT Transform, ReduceFuncT Reduce, T & Out, int64 InNumTasks)
Definition at line 63 of file ParallelTransformReduce.h.
References TMathUtil< float >::Ceil(), check, End, MAX_int32, FMath::Min, Num, ParallelFor(), PartialResult, TArray< InElementType, InAllocatorType >::SetNum(), and Transform.
ParallelTransformReduce() [3/4]
template<typename T, typename IterT, typename TransformFuncT, typename ReduceFuncT> T UE::Geometry::ParallelTransformReduce (IterT BeginIterator, IterT EndIterator, const T & Init, TransformFuncT Transform, ReduceFuncT Reduce, int64 InNumTasks)
Definition at line 150 of file ParallelTransformReduce.h.
References AdvanceIterator(), TMathUtil< float >::Ceil(), check, Init, IteratorDistance(), MAX_int32, FMath::Min, Num, ParallelFor(), PartialResult, TArray< InElementType, InAllocatorType >::SetNum(), and Transform.
ParallelTransformReduce() [4/4]
template<typename T, typename IterT, typename InitFuncT, typename TransformFuncT, typename ReduceFuncT> void UE::Geometry::ParallelTransformReduce (IterT BeginIterator, IterT EndIterator, InitFuncT InitFunc, TransformFuncT Transform, ReduceFuncT Reduce, T & Out, int64 InNumTasks)
Definition at line 202 of file ParallelTransformReduce.h.
References AdvanceIterator(), TMathUtil< float >::Ceil(), check, IteratorDistance(), MAX_int32, FMath::Min, Num, ParallelFor(), PartialResult, TArray< InElementType, InAllocatorType >::SetNum(), and Transform.
PerpCW()
template<typename T> UE::Math::TVector2< T > UE::Geometry::PerpCW (const UE::Math::TVector2< T > & V) constexpr
Returns
right-Perpendicular vector to V, ie V rotated 90 degrees clockwise
Definition at line 26 of file VectorTypes.h.
References UE::Math::TVector2< T >::X, and UE::Math::TVector2< T >::Y.
Referenced by UE::Geometry::TIntrSegment2Triangle2< float >::Find(), UE::Geometry::FArrangement2d::find_intersecting_edges(), UE::Geometry::FVerticalCylinderGeneratorBase::GenerateVerticalCircleSweep(), UE::Geometry::TPolygon2< double >::GetNormal(), UE::Geometry::CurveUtil::GetNormal_FaceAvg2(), UE::Geometry::TPolygon2< double >::PolyOffset(), UE::Geometry::CurveUtil::ProjectPointInsideConvexPolygon(), UE::Geometry::TIntrTriangle2AxisAlignedBox2< float >::Test(), and UE::Geometry::VectorUtil::TriGradient().
PointInTriangle2d()
GEOMETRYCORE_API bool UE::Geometry::PointInTriangle2d (double X0, double Y0, double X1, double Y1, double X2, double Y2, double X3, double Y3, double & A, double & B, double & C)
References A, and B.
Referenced by UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::compute_intersections().
PointSegmentDistance()
template<typename RealType> RealType UE::Geometry::PointSegmentDistance (const TVector< RealType > & x0, const TVector< RealType > & x1, const TVector< RealType > & x2)
Definition at line 28 of file SDFCalculationUtils.h.
References Distance, UE::Math::TVector< T >::Dot(), and UE::Math::TVector< T >::SquaredLength().
PointTriangleDistance() [1/2]
GEOMETRYCORE_API double UE::Geometry::PointTriangleDistance (const FVector3d & x0, const FVector3d & x1, const FVector3d & x2, const FVector3d & x3)
PointTriangleDistance() [2/2]
GEOMETRYCORE_API float UE::Geometry::PointTriangleDistance (const FVector3f & x0, const FVector3f & x1, const FVector3f & x2, const FVector3f & x3)
PolygonsDifference()
GEOMETRYALGORITHMS_API bool UE::Geometry::PolygonsDifference (TArrayView< const FGeneralPolygon2d > PosPolygons, TArrayView< const FGeneralPolygon2d > NegPolygons, TArray< FGeneralPolygon2d > & ResultOut)
Populate ResultOut with the difference of PosPolygons minus NegPolygons.
PolygonsExclusiveOr()
GEOMETRYALGORITHMS_API bool UE::Geometry::PolygonsExclusiveOr (TArrayView< const FGeneralPolygon2d > SubjPolygons, TArrayView< const FGeneralPolygon2d > ClipPolygons, TArray< FGeneralPolygon2d > & ResultOut)
Populate ResultOut with the 'exclusive or' of SubjPolygons with ClipPolygons.
PolygonsIntersection()
GEOMETRYALGORITHMS_API bool UE::Geometry::PolygonsIntersection (TArrayView< const FGeneralPolygon2d > SubjPolygons, TArrayView< const FGeneralPolygon2d > ClipPolygons, TArray< FGeneralPolygon2d > & ResultOut)
Populate ResultOut with the intersection of SubjPolygons with ClipPolygons.
PolygonsOffset()
GEOMETRYALGORITHMS_API bool UE::Geometry::PolygonsOffset (double Offset, TArrayView< const FGeneralPolygon2d > Polygons, TArray< FGeneralPolygon2d > & ResultOut, bool bCopyInputOnFailure, double MiterLimit, EPolygonOffsetJoinType JoinType = EPolygonOffsetJoinType::Square, EPolygonOffsetEndType EndType = EPolygonOffsetEndType::Polygon, double MaxStepsPerRadian = -1.0, double DefaultStepsPerRadianScale = 1.0)
References Polygon, and Square.
PolygonsOffsets()
GEOMETRYALGORITHMS_API bool UE::Geometry::PolygonsOffsets (double FirstOffset, double SecondOffset, TArrayView< const FGeneralPolygon2d > Polygons, TArray< FGeneralPolygon2d > & ResultOut, bool bCopyInputOnFailure, double MiterLimit, EPolygonOffsetJoinType JoinType = EPolygonOffsetJoinType::Square, EPolygonOffsetEndType EndType = EPolygonOffsetEndType::Polygon, double MaxStepsPerRadian = -1.0, double DefaultStepsPerRadianScale = 1.0)
References Polygon, and Square.
PolygonsUnion()
GEOMETRYALGORITHMS_API bool UE::Geometry::PolygonsUnion (TArrayView< const FGeneralPolygon2d > Polygons, TArray< FGeneralPolygon2d > & ResultOut, bool bCopyInputOnFailure)
Populate ResultOut with the union of the input Polygons.
Parameters
bCopyInputOnFailure If true, copy the input Polygons to ResultOut if the union is not successfully computed. Otherwise, ResultOut is left empty on failure.
RegisterSceneSnappingManager()
MODELINGCOMPONENTS_API bool UE::Geometry::RegisterSceneSnappingManager (UInteractiveToolsContext * ToolsContext)
If one does not already exist, create a new instance of UModelingSceneSnappingManager and add it to the ToolsContext's ContextObjectStore.
Returns
true if the ContextObjectStore now has a UModelingSceneSnappingManager (whether it already existed, or was created)
References RegisterSceneSnappingManager().
Referenced by RegisterSceneSnappingManager().
SetSimpleCollision()
MODELINGCOMPONENTS_API bool UE::Geometry::SetSimpleCollision (UPrimitiveComponent * Component, const FSimpleShapeSet3d * ShapeSet, FComponentCollisionSettings CollisionSettings = FComponentCollisionSettings())
Replace existing Simple Collision geometry in Component with that defined by ShapeSet, and update the Component/BodySetup collision settings.
References Component.
SetToolOutputGeometrySelectionForTarget()
MODELINGCOMPONENTS_API bool UE::Geometry::SetToolOutputGeometrySelectionForTarget (UInteractiveTool * Tool, UToolTarget * Target, const FGeometrySelection & OutputSelection)
Allow a Tool to return an "output" FGeometrySelection for the given ToolTarget (presumably on Tool Shutdown) Target must be an "active" selection target in the current UGeometrySelectionManager.
This function will emit a selection-change transaction and should in most cases be nested inside a tool-shutdown transaction.
Returns
true if the selection could be set, ie Target was valid
References Target.
SignedAngleR()
template<typename T> T UE::Geometry::SignedAngleR (const UE::Math::TVector2< T > & V1, const UE::Math::TVector2< T > & V2)
Definition at line 110 of file VectorTypes.h.
References TMathUtil< RealType >::ACos(), UE::Math::TVector2< T >::Dot(), and DotPerp().
Referenced by UE::Geometry::CurveUtil::IsConvex2().
SnapToIncrement()
template<typename RealType> RealType UE::Geometry::SnapToIncrement (RealType Value, RealType Increment, RealType Offset = 0)
Snap Value to steps of Increment (centered at 0, ie steps are -Increment, 0, Increment, 2*Increment, ...).
Optional Offset can be used to snap relative value.
Definition at line 634 of file VectorUtil.h.
References Value.
SolveInsetVertexPositionFromLinePair()
DYNAMICMESH_API FVector3d UE::Geometry::SolveInsetVertexPositionFromLinePair (const FVector3d & Position, const FLine3d & InsetEdgeLine1, const FLine3d & InsetEdgeLine2)
Solve for a new inset position by finding the intersection point a pair of inset-lines (or handle parallel-lines case).
Assumption is that Position is the location of the initial vertex on the pre-inset edge-line-pair, ie at their intersection point.
References Position.
SolveInsetVertexPositionsFromInsetLines()
DYNAMICMESH_API void UE::Geometry::SolveInsetVertexPositionsFromInsetLines (const FDynamicMesh3 & Mesh, const TArray< FLine3d > & InsetEdgeLines, const TArray< int32 > & VertexIDs, TArray< FVector3d > & VertexPositionsOut, bool bIsLoop)
For each vertex in VertexIDs, compute inset position based on list of precomputed inset lines and store in VertexPositionsOut.
Assumption is that each vertex position was at the intersection point of the pre-inset lines, ie sequential edge-line-pairs determine each sequential vertex position
Parameters
bIsLoop if true, vertex list is treated as a loop, otherwise as an open span
References Mesh.
SplineDeformDynamicMesh()
void MODELINGCOMPONENTS_API UE::Geometry::SplineDeformDynamicMesh (USplineMeshComponent & SplineMeshComponent, FDynamicMesh3 & Mesh, bool bUpdateTangentSpace = true)
Applies a deformation as defined by the SplineMeshComponent to the dynamic mesh The normal, tangent, and bi-tangent will be updated if bUpdateTangentSpace is selected.
NB: Superior tangents will be obtained by recomputing them after this deformation; while the tangent space update this function does is not ideal, it should be consistent with the SplineMeshComponent GPU computation
References Mesh.
SplitBoundaryVertexTrianglesIntoSubsets()
GEOMETRYCORE_API bool UE::Geometry::SplitBoundaryVertexTrianglesIntoSubsets (const FDynamicMesh3 * Mesh, int32 VertexID, int32 SplitEdgeID, TArray< int32 > & TriangleSet0, TArray< int32 > & TriangleSet1)
Split the triangle one-ring at VertexID into two triangle sets by "cutting" it with edge SplitEdgeID that is connected to VertexID.
VertexID must be a boundary-vertex of the mesh, otherwise one edge is not enough to "split" it. Bowtie vertices are not supported.
Returns
false if the split failed, ie the inputs are invalid or one of the output sets is empty
References Mesh.
SplitInteriorVertexTrianglesIntoSubsets()
GEOMETRYCORE_API bool UE::Geometry::SplitInteriorVertexTrianglesIntoSubsets (const FDynamicMesh3 * Mesh, int32 VertexID, int32 SplitEdgeID0, int32 SplitEdgeID1, TArray< int32 > & TriangleSet0, TArray< int32 > & TriangleSet1)
Split the triangle one-ring at VertexID into two triangle sets by "cutting" it with two edges SplitEdgeID0 and SplitEdgeID1 that are both connected to VertexID.
VertexID must be an "interior" vertex of the mesh (ie not on boundary). Bowtie vertices are not supported.
Returns
false if the split failed, ie the inputs are invalid or one of the output sets is empty
References Mesh.
SquaredDistanceFromLineIntegratedAlongSegment()
template<typename Real> double UE::Geometry::SquaredDistanceFromLineIntegratedAlongSegment (const TLine3< Real > & Line, const TSegment3< Real > & Segment)
Integrates the squared distance to a line along a given segment.
Definition at line 133 of file DistLine3Segment3.h.
References Dot(), UE::Math::TVector< T >::Dot(), Line, and Segment.
SquaredLength()
template<typename T> T UE::Geometry::SquaredLength (const UE::Math::TVector< T > & V)
Definition at line 154 of file VectorTypes.h.
References UE::Math::TVector< T >::X, UE::Math::TVector< T >::Y, and UE::Math::TVector< T >::Z.
Referenced by UE::Geometry::TDistSegment2AxisAlignedBox2< float >::ComputeResult().
SumPathLength()
double UE::Geometry::SumPathLength (const FDeformableEdgePath & DeformableEdgePath)
Returns
the length of the path, computed by suming the path segment lengths. Primarily for testing as the result should match FDeformableEdgePath::GetPathLength()
TestIntersection() [1/4]
template<typename RealType> GEOMETRYCORE_API bool UE::Geometry::TestIntersection (const THalfspace3< RealType > & Halfspace, const TCapsule3< RealType > & Capsule)
Returns
true if Halfspace and Capsule intersect
References Capsule.
TestIntersection() [2/4]
template<typename RealType> GEOMETRYCORE_API bool UE::Geometry::TestIntersection (const THalfspace3< RealType > & Halfspace, const TOrientedBox3< RealType > & Box)
Returns
true if Halfspace and Box intersect
References Box.
TestIntersection() [3/4]
template<typename RealType> GEOMETRYCORE_API bool UE::Geometry::TestIntersection (const THalfspace3< RealType > & Halfspace, const TSphere3< RealType > & Sphere)
Returns
true if Halfspace and Sphere intersect
References Sphere.
TestIntersection() [4/4]
template<typename Real> GEOMETRYCORE_API bool UE::Geometry::TestIntersection (const TSegment2< Real > & Segment, const TAxisAlignedBox2< Real > & Box)
References Box, and Segment.
Referenced by IsInsideHull(), IsInsideHull(), and IsInsideHull().
ToFColor()
template<typename T> FColor UE::Geometry::ToFColor (const UE::Math::TVector4< T > & Vector) constexpr
Definition at line 398 of file VectorTypes.h.
References TMathUtil< float >::Clamp(), and Vector.
ToLinearColor() [1/2]
template<typename T> FLinearColor UE::Geometry::ToLinearColor (const UE::Math::TVector4< T > & V)
Definition at line 386 of file VectorTypes.h.
References UE::Math::TVector4< T >::W, UE::Math::TVector4< T >::X, UE::Math::TVector4< T >::Y, and UE::Math::TVector4< T >::Z.
ToLinearColor() [2/2]
template<typename T> FLinearColor UE::Geometry::ToLinearColor (const UE::Math::TVector< T > & Vector) constexpr
Definition at line 350 of file VectorTypes.h.
References Vector.
ToVector4()
template<typename T> UE::Math::TVector4< T > UE::Geometry::ToVector4 (const FLinearColor & Color)
Definition at line 392 of file VectorTypes.h.
TransformSimpleCollision()
MODELINGCOMPONENTS_API bool UE::Geometry::TransformSimpleCollision (UPrimitiveComponent * Component, const FTransform3d & Transform)
Apply Transform to any Simple Collision geometry owned by Component.
Note that Nonuniform scaling support is very limited and will generally enlarge collision volumes.
References Component, and Transform.
TrianglesToOverlayElements()
template<typename OverlayType, typename EnumeratorType, typename OutputSetType> void UE::Geometry::TrianglesToOverlayElements (const OverlayType * Overlay, EnumeratorType TriangleEnumeration, OutputSetType & ElementsOut)
For a given list/enumeration of Triangles, and an Overlay, find all the Elements in all the Triangles.
Note that if ElementsOut is a TArray, it may include an Element multiple times.
Parameters
Overlay source overlay
TriangleEnumeration list of triangles
ElementsOut list of elements
Definition at line 165 of file MeshIndexUtil.h.
References UE::Geometry::FIndex3i::A, UE::Geometry::FIndex3i::B, and UE::Geometry::FIndex3i::C.
TriangleToVertexIDs()
GEOMETRYCORE_API void UE::Geometry::TriangleToVertexIDs (const FDynamicMesh3 * Mesh, TConstArrayView< int > TriangleIDs, TArray< int > & VertexIDsOut)
Find list of unique vertices that are contained in one or more triangles.
Parameters
Mesh input mesh
TriangleIDs list of triangle IDs of Mesh
VertexIDsOut list of vertices contained by triangles
References Mesh.
UE_DEPRECATED() [1/10]
struct UE::Geometry::UE_DEPRECATED (5. 3, "FRenderCaptureOptions is only used by deprecated functions, see those deprecation notes for more info.")
Definition at line 207 of file RenderCaptureFunctions.h.
UE_DEPRECATED() [2/10]
struct UE::Geometry::UE_DEPRECATED (5. 3, "FRenderCaptureUpdate is only used by deprecated functions, see those deprecation notes for more info.")
Definition at line 207 of file RenderCaptureFunctions.h.
UE_DEPRECATED() [3/10]
UE::Geometry::UE_DEPRECATED (5. 3, "Please use ConfigureSceneCapture and FSceneCapturePhotoSet::Compute instead.") const &
This function computes the SceneCapture for the first time.
References Actors.
UE_DEPRECATED() [4/10]
UE::Geometry::UE_DEPRECATED (5. 3, "Please use GetSceneCaptureConfig instead.") const &
References SceneCapture, and UE_DEPRECATED().
UE_DEPRECATED() [5/10]
UE::Geometry::UE_DEPRECATED (5. 3, "Please use the overload where PendingBake has type FRenderCaptureTypeFlags instead.")
References MakeRenderCaptureBaker(), and UE_DEPRECATED().
UE_DEPRECATED() [6/10]
UE::Geometry::UE_DEPRECATED (5. 3, "Please use UpdateSceneCapture instead.") const &
This function efficiently updates the given SceneCapture and returns a struct indicating which channels were updated.
If the requested Options and Actors have already been captured the call is a no-op
If the given Options disable existing capture channels then the call just clears the corresponding photo sets
If the given Options enable a new capture channel then the new photos set are captured and added to the SceneCapture
If the given Actors are different the ones cached in the SceneCapture, or if the given Options changes a parameter affecting all photo sets (e.g., photo resolution), then all the photo sets are cleared and recomputed
References Actors, bAllowCancel, Options, SceneCapture, and UE_DEPRECATED().
UE_DEPRECATED() [7/10]
UE::Geometry::UE_DEPRECATED (5. 4, "Please use the overload passing Baker by reference. Using smart pointers was an error since ownership semantics were not intended.") const &
References GetTexturesFromRenderCaptureBaker(), and UE_DEPRECATED().
UE_DEPRECATED() [8/10]
UE::Geometry::UE_DEPRECATED (5. 4, "Please use the overload passing SceneCapture by reference. Using smart pointers was an error since ownership semantics were not intended.") const &
References ConfigureSceneCapture(), and SceneCapture.
UE_DEPRECATED() [9/10]
UE::Geometry::UE_DEPRECATED (5. 5, "EnumerateTriangleSelectionVertices with ApplyTransform passed a reference is deprecated. " "Please use the function of the same name which takes ApplyTransform as a pointer instead") const &
Prefer pointer version for ApplyTransform in EnumerateTriangleSelectionVertices.
References EnumerateTriangleSelectionVertices().
Referenced by InitializeSelectionFromTriangles(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
UE_DEPRECATED() [10/10]
UE::Geometry::UE_DEPRECATED (5. 5, "Use GetDynamicMeshViaMeshDescription which takes a FGetMeshParameters instead.") &
References GetDynamicMeshViaMeshDescription().
UnitCross()
template<typename T> UE::Math::TVector< T > UE::Geometry::UnitCross (const UE::Math::TVector< T > & V1, const UE::Math::TVector< T > & V2)
Definition at line 231 of file VectorTypes.h.
References UE::Math::TVector< T >::Cross(), and Normalized.
Referenced by UE::Geometry::TIntrTriangle3Triangle3< float >::Intersects(), and UE::Geometry::TIntrTriangle3Triangle3< float >::Test().
UpdateGeometrySelectionVisualization()
void MODELINGCOMPONENTS_API UE::Geometry::UpdateGeometrySelectionVisualization (UPreviewGeometry * PreviewGeom, UGeometrySelectionVisualizationProperties * Settings)
Update the geometry selection preview geometry according to Settings.
Call this in your tool OnTick function
UpdateGroupSelectionViaRaycast()
DYNAMICMESH_API void UE::Geometry::UpdateGroupSelectionViaRaycast (const FColliderMesh * ColliderMesh, const FGroupTopology * GroupTopology, FGeometrySelectionEditor * Editor, const FRay3d & LocalRay, const FGeometrySelectionUpdateConfig & UpdateConfig, FGeometrySelectionUpdateResult & ResultOut)
Update a FGeometrySelection (via the Editor) of mesh polygroup faces/edges/corners, based on a raycast.
Parameters
UpdateConfig type of update (add/remove/replace) and other update controls
ResultOut selection delta and information on hit/miss are returned here
UpdateSceneCapture()
MODELINGCOMPONENTS_API FRenderCaptureTypeFlags UE::Geometry::UpdateSceneCapture (FSceneCapturePhotoSet & SceneCapture, const TArray< TObjectPtr< AActor > > & Actors, const FSceneCaptureConfig & DesiredConfig, bool bAllowCancel)
References Actors, bAllowCancel, DesiredConfig, and SceneCapture.
UpdateSelectionWithNewElements()
DYNAMICMESH_API bool UE::Geometry::UpdateSelectionWithNewElements (FGeometrySelectionEditor * Editor, EGeometrySelectionChangeType ChangeType, const TArray< uint64 > & NewIDs, FGeometrySelectionDelta * DeltaOut = nullptr)
Update a FGeometrySelection (via the Editor)
Parameters
ChangeType type of change to make (add/remove/replace)
NewIDs set of new IDs to use to update the selection
Delta selection delta will be stored here, if non-nullptr is provided
UpdateSimpleCollision()
MODELINGCOMPONENTS_API void UE::Geometry::UpdateSimpleCollision (UBodySetup * BodySetup, const FKAggregateGeom * NewGeometry, UStaticMesh * StaticMesh, FComponentCollisionSettings NewCollisionSettings = FComponentCollisionSettings())
Replace existing Simple Collision geometry in BodySetup with that defined by NewGeometry, and update the Component/BodySetup collision settings.
StaticMesh argument allows for necessary updates to it and any active UStaticMeshComponent that reference it
References BodySetup, and StaticMesh.
UpdateTriangleSelectionViaRaycast()
DYNAMICMESH_API void UE::Geometry::UpdateTriangleSelectionViaRaycast (const FColliderMesh * ColliderMesh, FGeometrySelectionEditor * Editor, const FRay3d & LocalRay, const FGeometrySelectionUpdateConfig & UpdateConfig, FGeometrySelectionUpdateResult & ResultOut)
Update a FGeometrySelection (via the Editor) of mesh vertices/edges/triangles based on a raycast.
Parameters
UpdateConfig type of update (add/remove/replace) and other update controls
ResultOut selection delta and information on hit/miss are returned here
UpdateUVLayerNames()
MESHMODELINGTOOLSEXP_API void UE::Geometry::UpdateUVLayerNames (FString & UVLayer, TArray< FString > & UVLayerNamesList, const FDynamicMesh3 & Mesh)
Updates a tool property set's UVLayerNamesList from the list of UV layers on a given mesh.
Also updates the UVLayer property if the current UV layer is no longer available.
Parameters
UVLayer Selected UV Layer.
UVLayerNamesList List of available UV layers.
Mesh the mesh to query
References Mesh.
VertexToTriangleOneRing()
GEOMETRYCORE_API void UE::Geometry::VertexToTriangleOneRing (const FDynamicMesh3 * Mesh, TConstArrayView< int > VertexIDs, TSet< int > & TriangleIDsOut)
Find all the triangles in all the one rings of a set of vertices.
Parameters
Mesh input mesh
VertexIDs list of Vertex IDs of Mesh
TriangleIDsOut list of triangle IDs where any vertex of triangle touches an element of VertexIDs
References Mesh.
Variable Documentation
Actors
const TArray< TObjectPtr< AActor > > & UE::Geometry::Actors
Definition at line 184 of file RenderCaptureFunctions.h.
Referenced by ComputeStandardExteriorSpatialPhotoParameters(), ConfigureSceneCapture(), UE::Geometry::FSceneCapturePhotoSet::SetCaptureSceneActors(), UE::Geometry::FSceneCapturePhotoSet::SetCaptureSceneActorsAndComponents(), UE::Geometry::FWorldRenderCapture::SetVisibleActors(), UE_DEPRECATED(), UE_DEPRECATED(), and UpdateSceneCapture().
ApplyTransform
const UE::Geometry::FDynamicMesh3 const FTransform& UE::Geometry::ApplyTransform
Definition at line 113 of file GeometrySelectionUtil.h.
Referenced by EnumeratePolygroupSelectionElements(), EnumeratePolygroupSelectionElements(), EnumeratePolygroupSelectionVertices(), EnumerateTriangleSelectionElements(), EnumerateTriangleSelectionElements(), EnumerateTriangleSelectionVertices(), UE::Geometry::FSelectionRenderHelper::Initialize(), and InitializeGeometrySelectionVisualization().
bAllowCancel
const TArray< TObjectPtr< AActor > > const FRenderCaptureOptions bool UE::Geometry::bAllowCancel
Definition at line 186 of file RenderCaptureFunctions.h.
Referenced by ConfigureSceneCapture(), UE_DEPRECATED(), and UpdateSceneCapture().
BaseMeshTangents
TSharedPtr<FMeshTangentsd, ESPMode::ThreadSafe> UE::Geometry::BaseMeshTangents
Definition at line 293 of file RenderCaptureFunctions.h.
Referenced by MakeRenderCaptureBaker().
BaseMeshUVCharts
TSharedPtr<FMeshTangentsd, ESPMode::ThreadSafe> TSharedPtr<TArray<int32>, ESPMode::ThreadSafe> UE::Geometry::BaseMeshUVCharts
Definition at line 294 of file RenderCaptureFunctions.h.
Referenced by MakeRenderCaptureBaker().
bRequestTangents
bool UE::Geometry::bRequestTangents
Definition at line 22 of file DynamicMeshViaMeshDescriptionUtil.h.
Config
PRAGMA_DISABLE_DEPRECATION_WARNINGS const TArray<TObjectPtr<AActor> > const FSceneCaptureConfig& UE::Geometry::Config
Definition at line 185 of file RenderCaptureFunctions.h.
Referenced by ConfigureSceneCapture(), and UE::Geometry::FSceneCapturePhotoSet::SetCaptureConfig().
DesiredConfig
const TArray<TObjectPtr<AActor> > const FSceneCaptureConfig& UE::Geometry::DesiredConfig
Definition at line 193 of file RenderCaptureFunctions.h.
Referenced by UpdateSceneCapture().
Mesh
const UE::Geometry::FDynamicMesh3& UE::Geometry::Mesh
Definition at line 112 of file GeometrySelectionUtil.h.
Referenced by UE::Geometry::FCotanSmoothingOp::FCotanSmoothingOp(), UE::Geometry::FCotanSmoothingOp::FCotanSmoothingOp(), UE::Geometry::FDynamicMeshAttributeSet::FDynamicMeshAttributeSet(), UE::Geometry::FDynamicMeshAttributeSet::FDynamicMeshAttributeSet(), UE::Geometry::FDetectPerDynamicMeshExteriorVisibility::FDynamicMeshInstance::FDynamicMeshInstance(), UE::Geometry::FIterativeOffsetMeshOp::FIterativeOffsetMeshOp(), UE::Geometry::FIterativeSmoothingOp::FIterativeSmoothingOp(), UE::Geometry::FIterativeSmoothingOp::FIterativeSmoothingOp(), UE::Geometry::FLaplacianOffsetMeshOp::FLaplacianOffsetMeshOp(), UE::Geometry::FMeshOffsetBaseOp::FMeshOffsetBaseOp(), UE::Geometry::FNonManifoldMappingSupport::FNonManifoldMappingSupport(), UE::Geometry::FRestrictedSubRegionRemesher::FRestrictedSubRegionRemesher(), UE::Geometry::FSceneCapturePhotoSetSampler::FSceneCapturePhotoSetSampler(), UE::Geometry::FSimpleMeshProcessingBaseOp::FSimpleMeshProcessingBaseOp(), UE::Geometry::FSmoothingOpBase::FSmoothingOpBase(), UE::Geometry::FSmoothingOpBase::FSmoothingOpBase(), UE::Geometry::GeodesicSingleTriangleUtils::FTangentTri2::FTangentTri2(), UE::Geometry::FVertexLinearization::FVertexLinearization(), UE::Geometry::TMeshUniformSurfaceSampling< FDynamicMesh3, double >::TMeshUniformSurfaceSampling(), UE::Geometry::FMeshBevel::AddBevelEdgeLoop(), UE::Geometry::FMeshBevel::AddBevelGroupEdge(), UE::Geometry::FVertexPositionCache::AddVertex(), UE::Geometry::FMeshBevel::AppendEdgeQuads(), UE::Geometry::FMeshBevel::AppendEdgeQuads_Multi(), UE::Geometry::FMeshBevel::AppendJunctionVertexPolygon(), UE::Geometry::FMeshBevel::AppendJunctionVertexPolygon_Multi(), UE::Geometry::FMeshBevel::AppendLoopQuads(), UE::Geometry::FMeshBevel::AppendLoopQuads_Multi(), UE::Geometry::FMeshBevel::AppendTerminatorVertexPairQuad(), UE::Geometry::FMeshBevel::AppendTerminatorVertexPairQuad_Multi(), UE::Geometry::FMeshBevel::AppendTerminatorVertexTriangle(), UE::Geometry::FMeshBevel::AppendTerminatorVertexTriangles_Multi(), UE::Geometry::FDynamicMeshChange::Apply(), UE::Geometry::FMeshBevel::Apply(), UE::Geometry::FMeshBevel::ApplyProfileShape_Round(), UE::Geometry::FDynamicMeshChange::ApplyReplaceChange(), UE::Geometry::FMeshVertexColorBrushOp::ApplyStamp(), UE::Geometry::FMeshVertexColorBrushOp::ApplyStampToVertexColors(), UE::Geometry::FVertexColorSmoothBrushOp::ApplyStampToVertexColors(), UE::Geometry::FVertexColorSoftenBrushOp::ApplyStampToVertexColors(), UE::Geometry::FVertexPaintBrushOp::ApplyStampToVertexColors(), MeshAdapterTransforms::ApplyTransform(), MeshAdapterTransforms::ApplyTransform(), MeshTransforms::ApplyTransform(), MeshTransforms::ApplyTransform(), MeshTransforms::ApplyTransform(), MeshAdapterTransforms::ApplyTransformInverse(), MeshTransforms::ApplyTransformInverse(), UE::Geometry::FUVToolSelection::AreElementsPresentInMesh(), UE::Geometry::IntrinsicCorrespondenceUtils::AsR3Position(), UE::Geometry::FMeshPlanarSymmetry::AssignMatches(), UE::Geometry::TMeshQueries< TriangleMeshType >::AverageEdgeLength(), UE::Geometry::FMeshVertexCurvatureCache::BuildAll(), UE::Geometry::FMeshRegionGraph::BuildFromComponents(), UE::Geometry::FMeshRegionGraph::BuildFromTriangleSets(), UE::Geometry::FMeshBevel::BuildJunctionVertex(), UE::Geometry::FMeshBevel::BuildTerminatorVertex(), UE::Geometry::FMeshTriInfoCache::BuildTriInfoCache(), UE::Geometry::FMeshBevel::BuildVertexSets(), UE::Geometry::FMeshBoundaryCache::Calculate(), UE::Geometry::FRemeshMeshOp::CalculateTargetEdgeLength(), UE::Geometry::FPolygroupLayer::CheckExists(), UE::Geometry::FLocalPlanarSimplify::CollapseDegenerateEdges(), UE::Geometry::FLocalPlanarSimplify::CollapseWouldChangeShapeOrUVs(), UE::Geometry::FLocalPlanarSimplify::CollapseWouldHurtTriangleQuality(), CollectVertexPositions(), CommitDynamicMeshViaMeshDescription(), CompactAttributeValues(), ComputeArbitraryTrianglePatchUVs(), ComputeAverageUVScaleRatioAlongVertexPath(), ComputeBoundsFromTriangleROI(), ComputeBoundsFromVertexROI(), UE::Geometry::FaceNormalClustering::ComputeClusterCornerVertices(), FastTriWinding::ComputeCoeffs(), FastTriWinding::ComputeCoeffsSerial(), ComputeFaceSelectionFrame(), ComputeGroupIDBound(), UE::Geometry::FFFDLattice::ComputeInitialEmbedding(), ComputeInsetLineSegmentsFromEdges(), ComputeMaterialIDRange(), UE::Geometry::FMeshBevel::ComputeMaterialIDs(), ComputeMaterialIDsForVertexPath(), UE::Geometry::FMeshPlanarSymmetry::ComputeMeshInfo(), UE::Geometry::FaceNormalClustering::ComputeMeshPolyGroupsFromClusters(), ComputeNewGroupIDsAlongEdgeLoop(), UE::Geometry::FMeshBevel::ComputeNormals(), ComputeNormalsForQuadPatch(), UE::Geometry::FExteriorVisibilitySampling::ComputePerTriangleOcclusion(), UE::Geometry::FExteriorVisibilitySampling::ComputePerTriangleOcclusion(), UE::Geometry::FMeshSurfacePointSampling::ComputePoissonSampling(), UE::Geometry::FMeshMapBaker::ComputeUVCharts(), ComputeUVIslandForQuadPatch(), UE::Geometry::FMeshBevel::ComputeUVs(), UE::Geometry::FVertexConnectedComponents::ConnectCloseVertices(), UE::Geometry::FVertexConnectedComponents::ConnectOverlappingComponents(), UE::Geometry::FVertexConnectedComponents::ConnectTriangles(), UE::MeshDeformation::ConstructEdgeCotanWeightsDataArray(), UE::MeshDeformation::ConstructFullCotangentLaplacian(), UE::MeshDeformation::ConstructFullIDTCotangentLaplacian(), UE::MeshDeformation::ConstructUniformLaplacian(), ConvertLoopToTriOrderedEdgeLoop(), ConvertLoopToTriOrderedEdgeLoop(), ConvertPolygroupSelectionToIncidentOverlaySelection(), ConvertPolygroupSelectionToOverlaySelection(), ConvertPolygroupSelectionToTopologySelection(), ConvertSelection(), ConvertSimpleCollisionToDynamicMeshes(), ConvertSimpleCollisionToDynamicMeshes(), ConvertTriangleSelectionToOverlaySelection(), ConvertTriOrderedEdgeLoopToLoop(), CopyVertexNormalsToOverlay(), CopyVertexUVsToOverlay(), UE::Geometry::FMeshWeights::CotanCentroid(), UE::Geometry::FMeshWeights::CotanCentroid(), UE::Geometry::FMeshWeights::CotanCentroidSafe(), UE::Geometry::FMeshWeights::CotanCentroidSafe(), UE::Geometry::FMeshWeights::CotanWeightsBlendSafe(), FaceGroupUtil::CountAllGroups(), UE::Geometry::FMeshBevel::CreateBevelMeshing(), UE::Geometry::FMeshBevel::CreateBevelMeshing_Multi(), UE::Geometry::FMeshIsoCurves::Cut(), UE::Geometry::FMeshIsoCurves::Cut(), UE::Geometry::FDisplaceMesh::DisplaceMeshWithVertexWeights(), UE::Geometry::FMeshBevel::DisplaceVertices(), MeshDebugDraw::DrawTriCentroids(), MeshDebugDraw::DrawVertices(), MeshDebugDraw::DrawVertices(), UE::Geometry::FRestrictedSubRegionRemesher::EdgeIsROIBoundary(), UE::Geometry::TMeshQueries< TriangleMeshType >::EdgeLengthStats(), UE::Geometry::TMeshQueries< TriangleMeshType >::EdgeLengthStatsFromEdges(), UE::Geometry::FRestrictedSubRegionRemesher::EdgeVerticesAreInVertexROI(), EmbedProjectedPath(), EmbedProjectedPaths(), EnumeratePolygroupSelectionEdges(), EnumeratePolygroupSelectionEdges(), EnumeratePolygroupSelectionElements(), EnumeratePolygroupSelectionElements(), EnumeratePolygroupSelectionTriangles(), EnumeratePolygroupSelectionVertices(), EnumerateSelectionEdges(), EnumerateSelectionTriangles(), EnumerateTriangleSelectionEdges(), EnumerateTriangleSelectionElements(), EnumerateTriangleSelectionElements(), EnumerateTriangleSelectionTriangles(), EnumerateTriangleSelectionVertices(), UE::Geometry::TMeshQueries< TriangleMeshType >::ExpandVertexSelectionToNeighbors(), UE::Geometry::FMeshWeights::FilteredUniformCentroid(), UE::Geometry::FMeshBevel::FinalizeTerminatorVertex(), FaceGroupUtil::FindAllGroups(), UE::Geometry::TMeshQueries< TriangleMeshType >::FindHitTriangle_LinearSearch(), UE::Geometry::TMeshQueries< TriangleMeshType >::FindHitTriangles_LinearSearch(), UE::Geometry::TMeshQueries< TriangleMeshType >::FindNearestPoint_LinearSearch(), UE::Geometry::TMeshQueries< TriangleMeshType >::FindNearestTriangle_LinearSearch(), FindNextAdjacentTriangleAroundVtx(), UE::Geometry::FMeshPlanarSymmetry::FindPlaneAndInitialize(), FindPolygroupLayerByName(), FindPolygroupLayerByName(), FindPolygroupLayerIndex(), FindPolygroupLayerIndexByName(), FindSharedEdgeInTriangles(), FaceGroupUtil::FindTrianglesByGroup(), FaceGroupUtil::FindTriangleSetsByGroup(), FindVertexEdgesInTriangle(), UE::WeightMaps::FindVertexWeightMaps(), UE::Geometry::FMeshBevel::FixBowties(), UE::Geometry::FMeshBevel::FixUpUnlinkedBevelEdges(), MeshAdapterTransforms::FrameCoordsToWorld(), MeshTransforms::FrameCoordsToWorld(), UE::MeshCurvature::GaussianCurvature(), UE::MeshCurvature::GaussianCurvature(), UE::Geometry::TMeshQueries< TriangleMeshType >::GetAllEdgeLengths(), UE::Geometry::FMeshBones::GetBoneChildren(), UE::Geometry::FMeshBones::GetBonesInIncreasingOrder(), UE::Geometry::TMeshQueries< TriangleMeshType >::GetBounds(), UE::Geometry::FUVToolSelection::GetConvertedSelection(), UE::Geometry::IMeshBakerDetailSampler::GetCurvature(), UE::Geometry::FMeshEdgesFromTriangleSubIndices::GetEdgeIDs(), GetFKElement(), UE::Geometry::FUVPacker::GetIslandStats(), UE::Geometry::IMeshBakerDetailSampler::GetMaterialID(), UE::Geometry::TMeshQueries< TriangleMeshType >::GetMeshVerticesCentroid(), UE::Geometry::IMeshBakerDetailSampler::GetNormalTextureMap(), UE::Geometry::IMeshBakerDetailSampler::GetPolyGroupID(), UE::Geometry::FQuadGridPatch::GetQuadOpeningAngleDeg(), UE::Geometry::FQuadGridPatch::GetQuadTriMappedToSpanIndices(), GetSelectionBoundaryCorners(), GetSelectionBoundaryVertices(), UE::Geometry::IMeshBakerDetailSampler::GetTextureMap(), UE::Geometry::IMeshBakerDetailSampler::GetTriangle(), UE::Geometry::IMeshBakerDetailSampler::GetTriangleCount(), UE::Geometry::TMeshQueries< TriangleMeshType >::GetTrianglesBounds(), GetTriangleSelectionFrame(), UE::Geometry::TMeshQueries< TriangleMeshType >::GetTriBounds(), UE::Geometry::TMeshQueries< TriangleMeshType >::GetTriCentroid(), UE::Geometry::IMeshBakerDetailSampler::GetTriNormal(), UE::Geometry::TMeshQueries< TriangleMeshType >::GetTriNormalAreaCentroid(), UE::Geometry::IMeshBakerDetailSampler::GetTriUVs(), UE::Geometry::TMeshQueries< TriangleMeshType >::GetVertexSelectedTriangles(), UE::WeightMaps::GetVertexWeightMap(), UE::Geometry::TMeshQueries< TriangleMeshType >::GetVertexWeightsOnTriangle(), UE::Geometry::TMeshQueries< TriangleMeshType >::GetVerticesBounds(), UE::Geometry::TMeshQueries< TriangleMeshType >::GetVolumeArea(), UE::Geometry::TMeshQueries< TriangleMeshType >::GetVolumeArea(), UE::Geometry::TMeshQueries< TriangleMeshType >::GetVolumeAreaCenter(), UE::Geometry::TMeshQueries< TriangleMeshType >::GetVolumeNonWatertight(), UE::Geometry::IMeshBakerDetailSampler::HasColors(), UE::Geometry::FVertexConnectedComponents::HasMultipleComponents(), FaceGroupUtil::HasMultipleGroups(), UE::Geometry::IMeshBakerDetailSampler::HasNormals(), UE::Geometry::IMeshBakerDetailSampler::HasTangents(), UE::Geometry::IMeshBakerDetailSampler::HasUVs(), UE::Geometry::FVertexConnectedComponents::Init(), UE::Geometry::TMeshUniformSurfaceSampling< FDynamicMesh3, double >::Init(), UE::Geometry::TMeshSpatialSort< TriangleMeshType >::InitBounds(), UE::Geometry::FMeshIndexMappings::Initialize(), UE::Geometry::FMeshPlanarSymmetry::Initialize(), UE::Geometry::FMeshPlanarSymmetry::Initialize(), UE::Geometry::FMeshEdgesFromTriangleSubIndices::InitializeFromEdgeIDs(), UE::Geometry::FMeshBevel::InitializeFromGroupTopology(), UE::Geometry::FMeshBevel::InitializeFromGroupTopologyEdges(), UE::Geometry::FMeshBevel::InitializeFromGroupTopologyFaces(), UE::Geometry::FQuadGridPatch::InitializeFromQuadPatch(), UE::Geometry::FQuadGridPatch::InitializeFromQuadStrip(), UE::Geometry::FMeshBevel::InitializeFromTriangleEdges(), UE::Geometry::FMeshBevel::InitializeFromTriangleEdges(), UE::Geometry::FRestrictedSubRegionRemesher::InitializeFromTriangleROI(), UE::Geometry::FMeshBevel::InitializeFromTriangleSet(), InitializeSelectionFromTriangles(), UE::Geometry::FNormalFlowRemesher::InitializeVertexBufferForFacePass(), UE::Geometry::FMeshBevel::InitVertexSet(), UE::Geometry::FMeshDerivatives::InteriorAngleGradient(), UE::Geometry::FUVToolSelection::IsAllSelected(), IsBoxMesh(), IsCapsuleMesh(), UE::Geometry::FLocalPlanarSimplify::IsDevelopableAlongEdge(), UE::Geometry::FLocalPlanarSimplify::IsFlat(), UE::Geometry::FGroupTopologySelection::IsSelectedTriangle(), IsSphereMesh(), UE::Geometry::IMeshBakerDetailSampler::IsTriangle(), MakeBoundaryConnectedSelection(), MakeBoundaryEdgeMidpointsAdapter(), UE::Geometry::FVertexConnectedComponents::MakeComponentMap(), MakeDynamicMeshAdapter(), MakeEdgeMidpointsAdapter(), MakeSelectAllConnectedSelection(), MakeSelectAllSelection(), MakeTransformedDynamicMeshAdapter(), MakeTriCentroidsAdapter(), MakeUniqueGroupLayerName(), MakeVerticesAdapter(), UE::Geometry::TMeshQueries< TriangleMeshType >::MaxEdgeLength(), UE::MeshCurvature::MeanCurvatureNormal(), UE::MeshCurvature::MeanCurvatureNormal(), UE::Geometry::FMeshWeights::MeanValueCentroid(), UE::Geometry::FMeshWeights::MeanValueCentroid(), UE::Geometry::TMeshQueries< TriangleMeshType >::MinEdgeLength(), UE::Geometry::FRecomputeUVsOp::NormalizeUVAreas(), UE::Geometry::FRestrictedSubRegionRemesher::OnEdgeFlip(), UE::Geometry::FRestrictedSubRegionRemesher::OnEdgeSplit(), UE::Geometry::FDynamicMesh3::operator<<, UE::Geometry::FMeshSurfacePoint::Pos(), UE::SculptUtil::PrecalculateNormalsROI(), UE::SculptUtil::PrecalculateNormalsROI(), UE::Geometry::TMeshQueries< TriangleMeshType >::RayTriangleIntersection(), UE::SculptUtil::RecalculateNormals_Overlay(), UE::SculptUtil::RecalculateNormals_Overlay(), UE::SculptUtil::RecalculateNormals_PerVertex(), UE::SculptUtil::RecalculateNormals_PerVertex(), UE::SculptUtil::RecalculateROINormals(), UE::SculptUtil::RecalculateROINormals(), UE::SculptUtil::RecalculateROINormals(), UE::SculptUtil::RecalculateROINormals(), UE::Geometry::FUVMetrics::ReedBeta(), UE::MeshAutoRepair::RemoveInternalTriangles(), UE::Geometry::FNonManifoldMappingSupport::Reset(), UE::Geometry::FVertexLinearization::Reset(), UE::Geometry::FUVToolSelection::RestoreFromStableEdgeIdentifiers(), MeshTransforms::ReverseOrientationIfNeeded(), MeshTransforms::Rotate(), UE::Geometry::FUVMetrics::Sander(), UE::Geometry::FDynamicMeshChange::SaveInitialTriangle(), UE::Geometry::FDynamicMeshChange::SaveInitialVertex(), UE::Geometry::FUVToolSelection::SaveStableEdgeIdentifiers(), MeshTransforms::Scale(), MeshTransforms::Scale(), UE::Geometry::FUVToolSelection::SelectAll(), FaceGroupUtil::SeparateMeshByGroups(), FaceGroupUtil::SeparateMeshByGroups(), UE::Geometry::FMeshImageBakingCache::SetBakeTargetMesh(), UE::Geometry::FMeshImageBakingCache::SetDetailMesh(), FaceGroupUtil::SetGroupID(), FaceGroupUtil::SetGroupID(), FaceGroupUtil::SetGroupToGroup(), UE::Geometry::IMeshBakerDetailSampler::SetNormalTextureMap(), UE::Geometry::FVertexPositionCache::SetPositions(), UE::Geometry::IMeshBakerDetailSampler::SetTangents(), UE::Geometry::FMeshBaseBaker::SetTargetMesh(), UE::Geometry::IMeshBakerDetailSampler::SetTextureMap(), UE::Geometry::FLocalPlanarSimplify::SimplifyAlongEdges(), SolveInsetVertexPositionsFromInsetLines(), SplineDeformDynamicMesh(), SplitBoundaryVertexTrianglesIntoSubsets(), UE::Geometry::FMeshIsoCurves::SplitCrossingEdges(), SplitInteriorVertexTrianglesIntoSubsets(), UE::Geometry::FUVPacker::StackPack(), UE::Geometry::FUVPacker::StackPack(), UE::Geometry::FUVPacker::StandardPack(), UE::Geometry::FUVPacker::StandardPack(), UE::Geometry::Debug::StashDebugMesh(), UE::Geometry::FDynamicMeshChange::StoreFinalTriangle(), UE::Geometry::FDynamicMeshChange::StoreFinalVertex(), UE::Geometry::FUVMetrics::TexelDensity(), UE::Geometry::FUVToolSelection::ToBoundingBox(), UE::Geometry::TMeshQueries< TriangleMeshType >::TotalEdgeLength(), UE::Geometry::GeodesicSingleTriangleUtils::TraceFromVertex(), UE::Geometry::GeodesicSingleTriangleUtils::TraceFromVertex(), UE::Geometry::GeodesicSingleTriangleUtils::TraceFromVertex(), UE::Geometry::GeodesicSingleTriangleUtils::TraceFromVertex(), UE::Geometry::GeodesicSingleTriangleUtils::TraceNextTriangle(), UE::Geometry::GeodesicSingleTriangleUtils::TraceNextTriangle(), UE::Geometry::GeodesicSingleTriangleUtils::TraceTriangleFromBaryPoint(), UE::Geometry::GeodesicSingleTriangleUtils::TraceTriangleFromBaryPoint(), UE::Geometry::GeodesicSingleTriangleUtils::TraceTriangleFromEdge(), UE::Geometry::GeodesicSingleTriangleUtils::TraceTriangleFromEdge(), MeshAdapterTransforms::Translate(), MeshTransforms::Translate(), UE::Geometry::FMeshDerivatives::TriangleAreaScaledNormalGradient(), UE::Geometry::TMeshQueries< TriangleMeshType >::TriangleDistance(), UE::Geometry::FRestrictedSubRegionRemesher::TriangleEdgesAreInEdgeROI(), UE::Geometry::TMeshQueries< TriangleMeshType >::TriangleIntersection(), UE::Geometry::FMeshDerivatives::TriangleNormalGradient(), TriangleToVertexIDs(), UE::Geometry::IMeshBakerDetailSampler::TriBaryInterpolateColor(), UE::Geometry::IMeshBakerDetailSampler::TriBaryInterpolateNormal(), UE::Geometry::IMeshBakerDetailSampler::TriBaryInterpolatePoint(), UE::Geometry::IMeshBakerDetailSampler::TriBaryInterpolateTangents(), UE::Geometry::IMeshBakerDetailSampler::TriBaryInterpolateUV(), UE::Geometry::TMeshQueries< TriangleMeshType >::TriDistanceSqr(), UE::Geometry::FMeshWeights::UniformCentroid(), UE::Geometry::FMeshWeights::UniformCentroid(), UE::Geometry::FMeshBevel::UnlinkBevelEdgeInterior(), UE::Geometry::FMeshBevel::UnlinkBevelLoop(), UE::Geometry::FMeshBevel::UnlinkEdges(), UE::Geometry::FMeshBevel::UnlinkJunctionVertex(), UE::Geometry::FMeshBevel::UnlinkLoops(), UE::Geometry::FMeshBevel::UnlinkTerminatorVertex(), UE::Geometry::FMeshBevel::UnlinkVertices(), UpdateUVLayerNames(), UE::Geometry::FMeshPlanarSymmetry::Validate(), VertexToTriangleOneRing(), UE::Geometry::IntrinsicCorrespondenceUtils::VisitVertexAdjacentElements(), UE::Geometry::FMeshWeights::VoronoiArea(), UE::Geometry::FMeshWeights::VoronoiArea(), MeshAdapterTransforms::WorldToFrameCoords(), and MeshTransforms::WorldToFrameCoords().
OcclusionHandler
TSharedPtr<FMeshTangentsd, ESPMode::ThreadSafe> TSharedPtr<TArray<int32>, ESPMode::ThreadSafe> FSceneCapturePhotoSet FSceneCapturePhotoSetSampler FRenderCaptureOptions int32 EBakeTextureResolution EBakeTextureSamplesPerPixel FRenderCaptureOcclusionHandler* UE::Geometry::OcclusionHandler
Definition at line 301 of file RenderCaptureFunctions.h.
Referenced by MakeRenderCaptureBaker().
Options
const TArray< TObjectPtr< AActor > > const FRenderCaptureOptions & UE::Geometry::Options
Definition at line 262 of file RenderCaptureFunctions.h.
Referenced by UE::Geometry::FConvexDecomposition3::FConvexDecomposition3(), UE::Geometry::FConvexDecomposition3::FConvexPart::FConvexPart(), UE::Geometry::FConvexDecomposition3::FConvexPart::FConvexPart(), UE::Geometry::FApproximateActorsImpl::ApproximateActors(), UE::Geometry::FDynamicMesh3::CanCollapseEdge(), UE::Geometry::FDynamicMesh3::CanCollapseEdgeInternal(), UE::Geometry::FDynamicMesh3::CollapseEdge(), UE::Geometry::FDynamicMesh3::CollapseEdge(), UE::Geometry::TPCA3< float >::Compute(), UE::Geometry::FaceNormalClustering::ComputeClusterCornerVertices(), UE::Geometry::FaceNormalClustering::ComputeMeshPolyGroupsFromClusters(), UE::Geometry::TMeshTangents< float >::ComputeMikkTStyleTangents(), UE::Geometry::TMeshTangents< float >::ComputeSeparatePerTriangleTangents(), UE::Geometry::TMeshTangents< float >::ComputeTriVertexTangents(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::DoTraversal(), UE::Geometry::FApproximateActorsImpl::EmitGeneratedMeshAsset(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::find_any_intersection(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::find_any_intersection(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::find_intersections(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::find_nearest_tri(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::find_nearest_triangles(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::find_nearest_vertex(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::find_self_intersections(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::find_self_intersections_acrossboxes(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::find_tri_tri_intersections(), UE::Geometry::IMeshSpatial::FindAllHitTriangles(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::FindAllHitTriangles(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::FindAllHitTriangles(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::FindAllHitTrianglesImpl(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::FindAllIntersections(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::FindAllSelfIntersections(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::FindHitTriangle(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::FindHitTriangles(), UE::Geometry::FColliderMesh::FindNearestHitTriangle(), UE::Geometry::IMeshBakerDetailSampler::FindNearestHitTriangle(), UE::Geometry::IMeshSpatial::FindNearestHitTriangle(), UE::Geometry::IMeshSpatial::FindNearestHitTriangle(), UE::Geometry::IMeshSpatial::FindNearestHitTriangle(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::FindNearestHitTriangle(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::FindNearestHitTriangle(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::FindNearestHitTriangle(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::FindNearestHitTriangle(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::FindNearestHitTriangleImpl(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::FindNearestPoint(), UE::Geometry::FSegmentTree3::FindNearestSegment(), UE::Geometry::FSegmentTree3::FindNearestSegmentInternal(), UE::Geometry::FColliderMesh::FindNearestTriangle(), UE::Geometry::IMeshBakerDetailSampler::FindNearestTriangle(), UE::Geometry::IMeshSpatial::FindNearestTriangle(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::FindNearestTriangle(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::FindNearestTriangles(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::FindNearestVertex(), UE::Geometry::FSegmentTree3::FindNearestVisibleSegmentHitByRay(), UE::Geometry::FSegmentTree3::FindNearestVisibleSegmentHitByRayInternal(), UE::Geometry::FApproximateActorsImpl::GenerateApproximationForActorSet(), UE::Geometry::FMeshAutoUVImpl::GenerateUVs(), UE::Geometry::FConvexDecomposition3::InitializeFromIndexMesh(), UE::Geometry::FConvexDecomposition3::InitializeFromMesh(), UE::Geometry::FDynamicMesh3::IsSameAs(), UE::Geometry::FDynamicMesh3::IsSameAs(), UE::Geometry::FDynamicMesh3::IsSameAs_Helper(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::IsWithinDistanceSquared(), UE::Geometry::FDynamicMesh3::MergeVertices(), UE::Geometry::FDynamicMeshUVEditor::SetTriangleUVsFromConformal(), UE::Geometry::FDynamicMeshUVEditor::SetTriangleUVsFromExpMap(), UE::Geometry::IMeshBakerDetailSampler::TestAnyHitTriangle(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::TestAnyHitTriangle(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::TestAnyHitTriangle(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::TestIntersection(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::TestIntersection(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::TestIntersection(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::TestSelfIntersection(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::TreeTraversalImpl(), and UE_DEPRECATED().
PendingBake
TSharedPtr<FMeshTangentsd, ESPMode::ThreadSafe> TSharedPtr<TArray<int32>, ESPMode::ThreadSafe> FSceneCapturePhotoSet FSceneCapturePhotoSetSampler FRenderCaptureOptions UE::Geometry::PendingBake
Definition at line 297 of file RenderCaptureFunctions.h.
Referenced by MakeRenderCaptureBaker().
QueryStatus
FSceneCapturePhotoSet::ECaptureTypeStatus UE::Geometry::QueryStatus = FSceneCapturePhotoSet::ECaptureTypeStatus::Computed)
Definition at line 200 of file RenderCaptureFunctions.h.
Referenced by GetSceneCaptureConfig().
Sampler
TSharedPtr<FMeshTangentsd, ESPMode::ThreadSafe> TSharedPtr<TArray<int32>, ESPMode::ThreadSafe> FSceneCapturePhotoSet FSceneCapturePhotoSetSampler* UE::Geometry::Sampler
Definition at line 296 of file RenderCaptureFunctions.h.
Referenced by MakeRenderCaptureBaker(), and UE::Geometry::FMeshBaseBaker::SetDetailSampler().
SamplesPerPixel
TSharedPtr<FMeshTangentsd, ESPMode::ThreadSafe> TSharedPtr<TArray<int32>, ESPMode::ThreadSafe> FSceneCapturePhotoSet FSceneCapturePhotoSetSampler FRenderCaptureOptions int32 EBakeTextureResolution EBakeTextureSamplesPerPixel UE::Geometry::SamplesPerPixel
Definition at line 300 of file RenderCaptureFunctions.h.
Referenced by UE::Geometry::FImageOccupancyMap::Initialize(), UE::Geometry::FImageOccupancyMap::Initialize(), and MakeRenderCaptureBaker().
SceneCapture
TSharedPtr<FMeshTangentsd, ESPMode::ThreadSafe> TSharedPtr<TArray<int32>, ESPMode::ThreadSafe> FSceneCapturePhotoSet* UE::Geometry::SceneCapture
Definition at line 295 of file RenderCaptureFunctions.h.
Referenced by ConfigureSceneCapture(), GetSceneCaptureConfig(), MakeRenderCaptureBaker(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), and UpdateSceneCapture().
TargetUVLayer
TSharedPtr<FMeshTangentsd, ESPMode::ThreadSafe> TSharedPtr<TArray<int32>, ESPMode::ThreadSafe> FSceneCapturePhotoSet FSceneCapturePhotoSetSampler FRenderCaptureOptions int32 UE::Geometry::TargetUVLayer
Definition at line 298 of file RenderCaptureFunctions.h.
Referenced by MakeRenderCaptureBaker().
TextureImageSize
TSharedPtr<FMeshTangentsd, ESPMode::ThreadSafe> TSharedPtr<TArray<int32>, ESPMode::ThreadSafe> FSceneCapturePhotoSet FSceneCapturePhotoSetSampler FRenderCaptureOptions int32 EBakeTextureResolution UE::Geometry::TextureImageSize
Definition at line 299 of file RenderCaptureFunctions.h.
Referenced by MakeRenderCaptureBaker().
TexturesOut
FRenderCaptureTextures& UE::Geometry::TexturesOut
Definition at line 207 of file RenderCaptureFunctions.h.
Referenced by GetTexturesFromRenderCaptureBaker().
Update
const FRenderCaptureOptions FRenderCaptureUpdate& UE::Geometry::Update
Definition at line 263 of file RenderCaptureFunctions.h.
VertexFunc
const UE::Geometry::FDynamicMesh3 const FTransform TFunctionRef<void(uint64, const FVector3d&)> UE::Geometry::VertexFunc
Definition at line 114 of file GeometrySelectionUtil.h.
Referenced by EnumeratePolygroupSelectionElements(), EnumeratePolygroupSelectionElements(), EnumeratePolygroupSelectionVertices(), EnumerateTriangleSelectionElements(), EnumerateTriangleSelectionElements(), EnumerateTriangleSelectionVertices(), and UE::Geometry::FDynamicMesh3::EnumerateVertexVertices().