Unreal Engine 5.6 C++ API: TraceServices Namespace Reference
TraceServices Namespace Reference
Namespaces
namespace FTraceAnalyzerUtils
namespace PagedArrayAlgo
namespace PagedArrayAlgoImpl
Data Structures
class EnumerateAsyncAlgoritm
struct FAnalysisMessage
struct FAnalysisSessionEditScope
struct FAnalysisSessionReadScope
struct FAsyncEnumerateTaskData
struct FBookmark
struct FCallstack
class FCancellationToken
struct FCaptureInfo
struct FChannelEntry
struct FClassInfo
struct FContextSwitch
struct FCpuCoreEvent
struct FCpuCoreInfo
struct FCreateAggregationParams
struct FCreateButterflyParams
struct FDetailLevel
struct FDetailLevelDepthState
struct FDetailLevelInsertionState
class FEnumerateAsyncTask
struct FEventInfoStackEntry
struct FEventScopeEntry
struct FEventScopeEntryPage
struct FEventStackEntry
struct FExportsTableRow
struct FFileActivity
struct FFileInfo
struct FFrame
struct FGpuFenceWrapper
struct FGpuQueueInfo
struct FGpuSignalFence
struct FGpuWaitFence
struct FIntervalTimelineDefaultSettings
struct FLoadRequest
struct FLoadTimeProfilerAggregatedStats
struct FLoadTimeProfilerCpuEvent
struct FLogCategoryInfo
struct FLogMessageInfo
struct FMemoryTagInfo
struct FMemoryTagSample
struct FMemoryTagSetInfo
struct FMemoryTrackerInfo
class FMetadataSchema
struct FMetadataSpec
struct FModule
Represents information about a module (engine/game/system dll or monolithic binary) and how debug information has been loaded.
struct FModuleInfo
struct FModuleInfoEx
struct FMonotonicTimelineDefaultSettings
struct FNetProfilerAggregatedStats
struct FNetProfilerAggregatedStatsCounterStats
union FNetProfilerBunchInfo
struct FNetProfilerConnection
struct FNetProfilerContentEvent
struct FNetProfilerEventType
struct FNetProfilerFrame
struct FNetProfilerGameInstance
struct FNetProfilerLifeTime
struct FNetProfilerName
struct FNetProfilerObjectInstance
struct FNetProfilerPacket
struct FNetProfilerStats
struct FNetProfilerStatsCounterType
struct FPackageData
struct FPackageExportInfo
struct FPackageInfo
struct FPackagesTableRow
struct FPackageSummaryInfo
struct FPointTimelineDefaultSettings
struct FProviderEditScopeLock
class FProviderLock
Utility class to implement the read/write lock for a provider.
struct FProviderReadScopeLock
class FRegionLane
struct FRequestsTableRow
struct FResolvedSymbol
Represent a resolved symbol.
struct FScreenshot
struct FSessionInfo
struct FStackFrame
struct FStackSample
struct FStringDefinition
struct FTableDiffCallbackParams
struct FTableImportCallbackParams
class FTableImportService
class FTableMergeService
struct FTaskInfo
struct FThreadInfo
struct FTimeRegion
struct FTimingProfilerAggregatedStats
struct FTimingProfilerButterflyNode
struct FTimingProfilerEvent
struct FTimingProfilerTimer
struct FTraceSessionMetadata
struct FWaitingForTasks
class IAllocationsProvider
class IAnalysisCache
Analysis cache.
class IAnalysisService
class IAnalysisSession
class IBookmarkProvider
class ICallstacksProvider
class IChannelProvider
class IContextSwitchesProvider
class ICookProfilerProvider
class ICounter
class ICounterProvider
class ICsvProfilerProvider
class IDefinitionProvider
Allows users to publish "definitions", structs representing a definition event.
class IDiagnosticsProvider
class IEditableBookmarkProvider
class IEditableCookProfilerProvider
class IEditableCounter
class IEditableCounterProvider
class IEditableLogProvider
class IEditableMetadataProvider
class IEditableProvider
class IEditableRegionProvider
The interface to a provider that can consume mutations of region events from a session.
class IEditableThreadProvider
class IEditableTimeline
class IEditableTimingProfilerProvider
class IFileActivityProvider
class IFrameProvider
class ILinearAllocator
class ILoadTimeProfilerProvider
class ILogProvider
class IMemoryProvider
class IMetadataProvider
class IModule
class IModuleProvider
class IModuleService
class INetProfilerProvider
class IProvider
class IRegionProvider
class IRegionTimeline
class IResolvedSymbolFilter
class IScreenshotProvider
class IStackSamplesProvider
class IStringStore
class ITable
class ITableImportData
class ITableLayout
class ITableReader
class ITasksProvider
class IThreadProvider
class ITimeline
class ITimingProfilerButterfly
class ITimingProfilerProvider
class ITimingProfilerTimerReader
class IUntypedTable
class IUntypedTableReader
class TCachedPagedArray
A typed paged array allowing persistent storage of the data.
class TCachedStringStore
A deduplicating persistent string store.
class TIntervalTimeline
class TMonotonicTimeline
class TPagedArray
class TPagedArrayIterator
struct TPagedArrayPage
class TPointTimeline
class TVariablePagedArray
class TVariablePagedArrayIterator
struct TVariablePagedArrayPage
struct TVariablePagedArrayPageGroup
Typedefs
typedef TCachedStringStore< WIDECHAR > FCachedStringStore
typedef TCachedStringStore< ANSICHAR > FCachedStringStoreAnsi
typedef uint32 FCacheId
A unique id for a named cache entry.
typedef int64 FMemoryTagId
typedef int32 FMemoryTagSetId
typedef int32 FMemoryTrackerId
typedef uint32 FNetProfilerNameIndexType
typedef double FNetProfilerTimeStamp
typedef TArrayView< FMemoryView > FSegmentIterator
An iterator for segments.
typedef uint32 TagIdType
Enumerations
enum ECacheFlags : uint16 { ECacheFlags_NoGlobalCaching = 1 << 1 }
Flags defining the behaviour of a cache entry.
enum class EContextSwitchEnumerationResult { Continue , Stop }
enum ECounterDisplayHint { CounterDisplayHint_None , CounterDisplayHint_Memory }
enum class ECounterOpType : uint8 { Set = 0 , Add = 1 }
enum class EEnumerateResult { Continue , Stop }
enum class EEventEnumerate { Continue , Stop }
enum class EEventSortOrder { ByStartTime , ByEndTime }
enum EFileActivityType {
FileActivityType_Open , FileActivityType_ReOpen , FileActivityType_Close , FileActivityType_Read ,
FileActivityType_Write , FileActivityType_Count , FileActivityType_Invalid = FileActivityType_Count
}
enum EGpuFenceType : uint8 { SignalFence = 0 , WaitFence = 1 }
enum ELoadTimeProfilerObjectEventType { LoadTimeProfilerObjectEventType_Create , LoadTimeProfilerObjectEventType_Serialize , LoadTimeProfilerObjectEventType_PostLoad , LoadTimeProfilerObjectEventType_None }
enum class EModuleStatus {
Discovered , Pending , Loaded , VersionMismatch ,
NotFound , Failed , StatusNum , FailedStatusStart = VersionMismatch
}
enum class ENetProfilerAggregationMode : uint32 { None , Aggregate , InstanceMax }
enum class ENetProfilerChannelCloseReason : uint8 {
Destroyed = 0 , Dormancy , LevelUnloaded , Relevancy ,
TearOff
}
enum ENetProfilerConnectionMode : uint8 { Outgoing = 0 , Incoming = 1 , Count }
enum class ENetProfilerConnectionState : uint8 { USOCK_Invalid = 0 , USOCK_Closed = 1 , USOCK_Pending = 2 , USOCK_Open = 3 }
enum class ENetProfilerDeliveryStatus : uint8 { Unknown , Delivered , Dropped }
enum class ENetProfilerStatsCounterType : uint8 { Packet = 0 , Frame = 1 }
enum class EResolvedSymbolFilterStatus : uint8 { Unknown = 0 , Filtered , NotFiltered }
enum class ESymbolQueryResult : uint8 {
Pending , OK , NotLoaded , Mismatch ,
NotFound , StatusNum
}
Result of a query.
enum ETableColumnDisplayHint { TableColumnDisplayHint_Time = 1 << 0 , TableColumnDisplayHint_Memory = 1 << 1 , TableColumnDisplayHint_Summable = 1 << 31 }
enum ETableColumnType {
TableColumnType_Invalid , TableColumnType_Bool , TableColumnType_Int , TableColumnType_Float ,
TableColumnType_Double , TableColumnType_CString
}
enum class ETableDiffResult : uint32 { ESuccess = 0 , EFail = 1 }
enum class ETableImportResult : uint32 { ESuccess = 0 , EFail = 1 }
enum class ETaskEnumerationOption {
Alive , Launched , Active , WaitingForPrerequisites ,
Queued , Executing , WaitingForNested , Completed ,
Count
}
enum class ETaskEnumerationResult { Continue , Stop }
Functions
TRACESERVICES_API TSharedPtr< IAnalysisSession > CreateAnalysisSession (uint32 InTraceId, const TCHAR *InSessionName, TUniquePtr< UE::Trace::IInDataStream > &&InDataStream)
TRACESERVICES_API TSharedPtr< UE::Trace::IAnalyzer > CreateBookmarksAnalyzer (IAnalysisSession &InSession, IEditableBookmarkProvider &InEditableBookmarkProvider)
TRACESERVICES_API TSharedPtr< UE::Trace::IAnalyzer > CreateCountersAnalyzer (IAnalysisSession &InSession, IEditableCounterProvider &InEditableCounterProvider)
TRACESERVICES_API TSharedPtr< UE::Trace::IAnalyzer > CreateCpuProfilerAnalyzer (IAnalysisSession &InSession, IEditableTimingProfilerProvider &InEditableTimingProfilerProvider, IEditableThreadProvider &InEditableThreadProvider)
TRACESERVICES_API IEditableBookmarkProvider & EditBookmarkProvider (IAnalysisSession &Session)
TRACESERVICES_API IEditableCookProfilerProvider * EditCookProfilerProvider (IAnalysisSession &Session)
TRACESERVICES_API IEditableCounterProvider & EditCounterProvider (IAnalysisSession &Session)
TRACESERVICES_API IDefinitionProvider * EditDefinitionProvider (IAnalysisSession &Session)
TRACESERVICES_API IEditableLogProvider & EditLogProvider (IAnalysisSession &Session)
TRACESERVICES_API IEditableMetadataProvider * EditMetadataProvider (IAnalysisSession &Session)
TRACESERVICES_API IEditableRegionProvider & EditRegionProvider (IAnalysisSession &Session)
TRACESERVICES_API IEditableThreadProvider & EditThreadProvider (IAnalysisSession &Session)
TRACESERVICES_API IEditableTimingProfilerProvider * EditTimingProfilerProvider (IAnalysisSession &Session)
TRACESERVICES_API void FormatString (TCHAR *OutputString, uint32 OutputStringCount, const TCHAR *FormatString, const uint8 *FormatArgs)
TRACESERVICES_API FName GetAllocationsProviderName ()
TRACESERVICES_API FName GetBookmarkProviderName ()
TRACESERVICES_API FName GetCallstacksProviderName ()
TRACESERVICES_API FName GetChannelProviderName ()
TRACESERVICES_API FName GetContextSwitchesProviderName ()
TRACESERVICES_API FName GetCookProfilerProviderName ()
TRACESERVICES_API FName GetCounterProviderName ()
TRACESERVICES_API FName GetCsvProfilerProviderName ()
template<typename ItemType, typename PageType>
const PageType * GetData (const TPagedArray< ItemType, PageType > &PagedArray)
template<typename ItemType>
const ItemType * GetData (const TPagedArrayPage< ItemType > &Page)
template<typename ItemType>
const ItemType * GetData (const TVariablePagedArrayPage< ItemType > &Page)
TRACESERVICES_API FName GetDefinitionProviderName ()
TRACESERVICES_API FName GetDiagnosticsProviderName ()
template<typename ItemType, typename PageType>
FInt32Interval GetElementRangeOverlappingGivenRange (const TPagedArray< ItemType, PageType > &PagedArray, double StartTime, double EndTime, TFunctionRef< double(const ItemType &)> ItemStartProjection, TFunctionRef< double(const ItemType &)> ItemEndProjection)
Use binary search to find the first and last element inside a TPagedArray that overlaps a given input interval.
TRACESERVICES_API FName GetFileActivityProviderName ()
TRACESERVICES_API const TCHAR * GetFileActivityTypeString (EFileActivityType ActivityType)
template<typename ItemType>
const ItemType * GetFirstItem (const TPagedArrayPage< ItemType > &Page)
template<typename ItemType>
const ItemType * GetFirstItem (const TVariablePagedArrayPage< ItemType > &Page)
TRACESERVICES_API FName GetFrameProviderName ()
template<typename ItemType>
const ItemType * GetLastItem (const TPagedArrayPage< ItemType > &Page)
template<typename ItemType>
const ItemType * GetLastItem (const TVariablePagedArrayPage< ItemType > &Page)
TRACESERVICES_API const TCHAR * GetLoadTimeProfilerObjectEventTypeString (ELoadTimeProfilerObjectEventType EventType)
TRACESERVICES_API FName GetLoadTimeProfilerProviderName ()
TRACESERVICES_API FName GetLogProviderName ()
TRACESERVICES_API FName GetMemoryProviderName ()
TRACESERVICES_API FName GetMetadataProviderName ()
TRACESERVICES_API FName GetModuleProviderName ()
TRACESERVICES_API FName GetNetProfilerProviderName ()
template<typename ItemType, typename PageType>
SIZE_T GetNum (const TPagedArray< ItemType, PageType > &PagedArray)
template<typename ItemType>
SIZE_T GetNum (const TPagedArrayPage< ItemType > &Page)
template<typename ItemType>
SIZE_T GetNum (const TVariablePagedArrayPage< ItemType > &Page)
TRACESERVICES_API FName GetRegionProviderName ()
TRACESERVICES_API FName GetScreenshotProviderName ()
TRACESERVICES_API FName GetStackSamplesProviderName ()
TRACESERVICES_API FName GetTaskProviderName ()
TRACESERVICES_API FName GetThreadProviderName ()
TRACESERVICES_API FName GetTimingProfilerProviderName ()
TRACESERVICES_API const TCHAR * LexToString (const ENetProfilerChannelCloseReason Value)
TRACESERVICES_API const TCHAR * LexToString (const ENetProfilerConnectionState Value)
const TCHAR * ModuleStatusToString (EModuleStatus Result)
const TCHAR * QueryResultToString (ESymbolQueryResult Result)
Helper method to get a string representation of the query result.
TRACESERVICES_API const IAllocationsProvider * ReadAllocationsProvider (const IAnalysisSession &Session)
TRACESERVICES_API const IBookmarkProvider & ReadBookmarkProvider (const IAnalysisSession &Session)
TRACESERVICES_API const ICallstacksProvider * ReadCallstacksProvider (const IAnalysisSession &Session)
TRACESERVICES_API const IChannelProvider * ReadChannelProvider (const IAnalysisSession &Session)
TRACESERVICES_API const IContextSwitchesProvider * ReadContextSwitchesProvider (const IAnalysisSession &Session)
TRACESERVICES_API const ICookProfilerProvider * ReadCookProfilerProvider (const IAnalysisSession &Session)
TRACESERVICES_API const ICounterProvider & ReadCounterProvider (const IAnalysisSession &Session)
TRACESERVICES_API const ICsvProfilerProvider * ReadCsvProfilerProvider (const IAnalysisSession &Session)
TRACESERVICES_API const IDefinitionProvider * ReadDefinitionProvider (const IAnalysisSession &Session)
TRACESERVICES_API const IDiagnosticsProvider * ReadDiagnosticsProvider (const IAnalysisSession &Session)
TRACESERVICES_API const IFileActivityProvider * ReadFileActivityProvider (const IAnalysisSession &Session)
TRACESERVICES_API const IFrameProvider & ReadFrameProvider (const IAnalysisSession &Session)
TRACESERVICES_API const ILoadTimeProfilerProvider * ReadLoadTimeProfilerProvider (const IAnalysisSession &Session)
TRACESERVICES_API const ILogProvider & ReadLogProvider (const IAnalysisSession &Session)
TRACESERVICES_API const IMemoryProvider * ReadMemoryProvider (const IAnalysisSession &Session)
TRACESERVICES_API const IMetadataProvider * ReadMetadataProvider (const IAnalysisSession &Session)
TRACESERVICES_API const IModuleProvider * ReadModuleProvider (const IAnalysisSession &Session)
TRACESERVICES_API const INetProfilerProvider * ReadNetProfilerProvider (const IAnalysisSession &Session)
TRACESERVICES_API const IRegionProvider & ReadRegionProvider (const IAnalysisSession &Session)
TRACESERVICES_API const IScreenshotProvider & ReadScreenshotProvider (const IAnalysisSession &Session)
TRACESERVICES_API const IStackSamplesProvider & ReadStackSamplesProvider (const IAnalysisSession &Session)
TRACESERVICES_API const ITasksProvider * ReadTasksProvider (const IAnalysisSession &Session)
TRACESERVICES_API const IThreadProvider & ReadThreadProvider (const IAnalysisSession &Session)
TRACESERVICES_API const ITimingProfilerProvider * ReadTimingProfilerProvider (const IAnalysisSession &Session)
TRACESERVICES_API void StringFormat (TCHAR *Out, uint64 MaxOut, TCHAR *Temp, uint64 MaxTemp, const TCHAR *FormatString, const uint8 *FormatArgs)
TRACESERVICES_API bool Table2Csv (const IUntypedTable &Table, const TCHAR *Filename)
Variables
TRACESERVICES_API const FName ModuleFeatureName
Typedef Documentation
FCachedStringStore
typedef TCachedStringStore<WIDECHAR> TraceServices::FCachedStringStore
Definition at line 230 of file CachedStringStore.h.
FCachedStringStoreAnsi
typedef TCachedStringStore<ANSICHAR> TraceServices::FCachedStringStoreAnsi
Definition at line 231 of file CachedStringStore.h.
FCacheId
typedef uint32 TraceServices::FCacheId
A unique id for a named cache entry.
Definition at line 27 of file AnalysisCache.h.
FMemoryTagId
typedef int64 TraceServices::FMemoryTagId
Definition at line 17 of file Memory.h.
FMemoryTagSetId
typedef int32 TraceServices::FMemoryTagSetId
Definition at line 16 of file Memory.h.
FMemoryTrackerId
typedef int32 TraceServices::FMemoryTrackerId
Definition at line 15 of file Memory.h.
FNetProfilerNameIndexType
typedef uint32 TraceServices::FNetProfilerNameIndexType
Definition at line 60 of file NetProfiler.h.
FNetProfilerTimeStamp
typedef double TraceServices::FNetProfilerTimeStamp
Definition at line 77 of file NetProfiler.h.
FSegmentIterator
typedef TArrayView<FMemoryView> TraceServices::FSegmentIterator
An iterator for segments.
Definition at line 12 of file AnalysisCache.h.
TagIdType
typedef uint32 TraceServices::TagIdType
Definition at line 18 of file AllocationsProvider.h.
Enumeration Type Documentation
ECacheFlags
enum TraceServices::ECacheFlags : uint16
Flags defining the behaviour of a cache entry.
Enumerator
ECacheFlags_NoGlobalCaching
Definition at line 18 of file AnalysisCache.h.
EContextSwitchEnumerationResult
enum class TraceServices::EContextSwitchEnumerationResult strong
Enumerator
Continue
Stop
Definition at line 32 of file ContextSwitches.h.
ECounterDisplayHint
enum TraceServices::ECounterDisplayHint
Enumerator
CounterDisplayHint_None
CounterDisplayHint_Memory
Definition at line 13 of file Counters.h.
ECounterOpType
enum class TraceServices::ECounterOpType : uint8 strong
Enumerator
Set
Add
Definition at line 19 of file Counters.h.
EEnumerateResult
enum class TraceServices::EEnumerateResult strong
Enumerator
Continue
Stop
Definition at line 223 of file TimingProfiler.h.
EEventEnumerate
enum class TraceServices::EEventEnumerate strong
Enumerator
Continue
Stop
Definition at line 10 of file Timelines.h.
EEventSortOrder
enum class TraceServices::EEventSortOrder strong
Enumerator
ByStartTime
ByEndTime
Definition at line 16 of file Timelines.h.
EFileActivityType
enum TraceServices::EFileActivityType
Enumerator
FileActivityType_Open
FileActivityType_ReOpen
FileActivityType_Close
FileActivityType_Read
FileActivityType_Write
FileActivityType_Count
FileActivityType_Invalid
Definition at line 25 of file LoadTimeProfiler.h.
EGpuFenceType
enum TraceServices::EGpuFenceType : uint8
Enumerator
SignalFence
WaitFence
Definition at line 195 of file TimingProfiler.h.
ELoadTimeProfilerObjectEventType
enum TraceServices::ELoadTimeProfilerObjectEventType
Enumerator
LoadTimeProfilerObjectEventType_Create
LoadTimeProfilerObjectEventType_Serialize
LoadTimeProfilerObjectEventType_PostLoad
LoadTimeProfilerObjectEventType_None
Definition at line 109 of file LoadTimeProfiler.h.
EModuleStatus
enum class TraceServices::EModuleStatus strong
Enumerator
Discovered
Pending
Loaded
VersionMismatch
NotFound
Failed
StatusNum
FailedStatusStart
Definition at line 96 of file Modules.h.
ENetProfilerAggregationMode
enum class TraceServices::ENetProfilerAggregationMode : uint32 strong
Enumerator
None
Aggregate
InstanceMax
Definition at line 16 of file NetProfiler.h.
ENetProfilerChannelCloseReason
enum class TraceServices::ENetProfilerChannelCloseReason : uint8 strong
Enumerator
Destroyed
Dormancy
LevelUnloaded
Relevancy
TearOff
Definition at line 38 of file NetProfiler.h.
ENetProfilerConnectionMode
enum TraceServices::ENetProfilerConnectionMode : uint8
Enumerator
Outgoing
Incoming
Count
Definition at line 30 of file NetProfiler.h.
ENetProfilerConnectionState
enum class TraceServices::ENetProfilerConnectionState : uint8 strong
Enumerator
USOCK_Invalid
USOCK_Closed
USOCK_Pending
USOCK_Open
Definition at line 48 of file NetProfiler.h.
ENetProfilerDeliveryStatus
enum class TraceServices::ENetProfilerDeliveryStatus : uint8 strong
Enumerator
Unknown
Delivered
Dropped
Definition at line 23 of file NetProfiler.h.
ENetProfilerStatsCounterType
enum class TraceServices::ENetProfilerStatsCounterType : uint8 strong
Enumerator
Packet
Frame
Definition at line 145 of file NetProfiler.h.
EResolvedSymbolFilterStatus
enum class TraceServices::EResolvedSymbolFilterStatus : uint8 strong
Enumerator
Unknown
Filtered
NotFiltered
Definition at line 51 of file Modules.h.
ESymbolQueryResult
enum class TraceServices::ESymbolQueryResult : uint8 strong
Result of a query.
Since symbol resolving can be deferred this signals if a symbol has been resolved, waiting to be resolved or wasn't found at all.
Enumerator
Pending
OK
NotLoaded
Mismatch
NotFound
StatusNum
Definition at line 22 of file Modules.h.
ETableColumnDisplayHint
enum TraceServices::ETableColumnDisplayHint
Enumerator
TableColumnDisplayHint_Time
TableColumnDisplayHint_Memory
TableColumnDisplayHint_Summable
Definition at line 20 of file Tables.h.
ETableColumnType
enum TraceServices::ETableColumnType
Enumerator
TableColumnType_Invalid
TableColumnType_Bool
TableColumnType_Int
TableColumnType_Float
TableColumnType_Double
TableColumnType_CString
Definition at line 10 of file Tables.h.
ETableDiffResult
enum class TraceServices::ETableDiffResult : uint32 strong
Enumerator
ESuccess
EFail
Definition at line 12 of file TableMerge.h.
ETableImportResult
enum class TraceServices::ETableImportResult : uint32 strong
Enumerator
ESuccess
EFail
Definition at line 20 of file TableImport.h.
ETaskEnumerationOption
enum class TraceServices::ETaskEnumerationOption strong
Enumerator
Alive
Launched
Active
WaitingForPrerequisites
Queued
Executing
WaitingForNested
Completed
Count
Definition at line 87 of file TasksProfiler.h.
ETaskEnumerationResult
enum class TraceServices::ETaskEnumerationResult strong
Enumerator
Continue
Stop
Definition at line 100 of file TasksProfiler.h.
Function Documentation
CreateAnalysisSession()
TRACESERVICES_API TSharedPtr< IAnalysisSession > TraceServices::CreateAnalysisSession (uint32 InTraceId, const TCHAR * InSessionName, TUniquePtr< UE::Trace::IInDataStream > && InDataStream)
CreateBookmarksAnalyzer()
TRACESERVICES_API TSharedPtr< UE::Trace::IAnalyzer > TraceServices::CreateBookmarksAnalyzer (IAnalysisSession & InSession, IEditableBookmarkProvider & InEditableBookmarkProvider)
CreateCountersAnalyzer()
TRACESERVICES_API TSharedPtr< UE::Trace::IAnalyzer > TraceServices::CreateCountersAnalyzer (IAnalysisSession & InSession, IEditableCounterProvider & InEditableCounterProvider)
CreateCpuProfilerAnalyzer()
TRACESERVICES_API TSharedPtr< UE::Trace::IAnalyzer > TraceServices::CreateCpuProfilerAnalyzer (IAnalysisSession & InSession, IEditableTimingProfilerProvider & InEditableTimingProfilerProvider, IEditableThreadProvider & InEditableThreadProvider)
EditBookmarkProvider()
TRACESERVICES_API IEditableBookmarkProvider & TraceServices::EditBookmarkProvider (IAnalysisSession & Session)
EditCookProfilerProvider()
TRACESERVICES_API IEditableCookProfilerProvider * TraceServices::EditCookProfilerProvider (IAnalysisSession & Session)
EditCounterProvider()
TRACESERVICES_API IEditableCounterProvider & TraceServices::EditCounterProvider (IAnalysisSession & Session)
EditDefinitionProvider()
TRACESERVICES_API IDefinitionProvider * TraceServices::EditDefinitionProvider (IAnalysisSession & Session)
EditLogProvider()
TRACESERVICES_API IEditableLogProvider & TraceServices::EditLogProvider (IAnalysisSession & Session)
EditMetadataProvider()
TRACESERVICES_API IEditableMetadataProvider * TraceServices::EditMetadataProvider (IAnalysisSession & Session)
EditRegionProvider()
TRACESERVICES_API IEditableRegionProvider & TraceServices::EditRegionProvider (IAnalysisSession & Session)
References EditRegionProvider().
Referenced by EditRegionProvider().
EditThreadProvider()
TRACESERVICES_API IEditableThreadProvider & TraceServices::EditThreadProvider (IAnalysisSession & Session)
EditTimingProfilerProvider()
TRACESERVICES_API IEditableTimingProfilerProvider * TraceServices::EditTimingProfilerProvider (IAnalysisSession & Session)
FormatString()
TRACESERVICES_API void TraceServices::FormatString (TCHAR * OutputString, uint32 OutputStringCount, const TCHAR * FormatString, const uint8 * FormatArgs)
References FormatString().
Referenced by FormatString(), StringFormat(), and TraceServices::IEditableBookmarkProvider::UpdateBookmarkSpec().
GetAllocationsProviderName()
TRACESERVICES_API FName TraceServices::GetAllocationsProviderName ()
GetBookmarkProviderName()
TRACESERVICES_API FName TraceServices::GetBookmarkProviderName ()
GetCallstacksProviderName()
TRACESERVICES_API FName TraceServices::GetCallstacksProviderName ()
GetChannelProviderName()
TRACESERVICES_API FName TraceServices::GetChannelProviderName ()
GetContextSwitchesProviderName()
TRACESERVICES_API FName TraceServices::GetContextSwitchesProviderName ()
GetCookProfilerProviderName()
TRACESERVICES_API FName TraceServices::GetCookProfilerProviderName ()
GetCounterProviderName()
TRACESERVICES_API FName TraceServices::GetCounterProviderName ()
GetCsvProfilerProviderName()
TRACESERVICES_API FName TraceServices::GetCsvProfilerProviderName ()
GetData() [1/3]
template<typename ItemType, typename PageType> const PageType * TraceServices::GetData (const TPagedArray< ItemType, PageType > & PagedArray) inline
Definition at line 754 of file PagedArray.h.
References TraceServices::TPagedArray< InItemType, InPageType >::GetPages().
GetData() [2/3]
template<typename ItemType> const ItemType * TraceServices::GetData (const TPagedArrayPage< ItemType > & Page) inline
Definition at line 32 of file PagedArray.h.
References TraceServices::TPagedArrayPage< ItemType >::Items.
Referenced by TraceServices::TCachedPagedArray< InItemType, PageSize >::EvictPages(), and TraceServices::TCachedStringStore< WIDECHAR >::GetStringAtOffset().
GetData() [3/3]
template<typename ItemType> const ItemType * TraceServices::GetData (const TVariablePagedArrayPage< ItemType > & Page) inline
Definition at line 70 of file VariablePagedArray.h.
References TraceServices::TVariablePagedArrayPage< ItemType >::ItemOffset, and TraceServices::TVariablePagedArrayPage< ItemType >::Items.
GetDefinitionProviderName()
TRACESERVICES_API FName TraceServices::GetDefinitionProviderName ()
GetDiagnosticsProviderName()
TRACESERVICES_API FName TraceServices::GetDiagnosticsProviderName ()
GetElementRangeOverlappingGivenRange()
template<typename ItemType, typename PageType> FInt32Interval TraceServices::GetElementRangeOverlappingGivenRange (const TPagedArray< ItemType, PageType > & PagedArray, double StartTime, double EndTime, TFunctionRef< double(const ItemType &)> ItemStartProjection, TFunctionRef< double(const ItemType &)> ItemEndProjection)
Use binary search to find the first and last element inside a TPagedArray that overlaps a given input interval.
This requires the elements in the array to be sorted by the value returned from the Projection. Example usage for Timeline events would require a projection that returns Item.StartTime and the resulting range.Min will point to the last element where Item.End > StartTime and range.Max to the last element where Item.StartTime < EndTime.
Definition at line 773 of file PagedArray.h.
References check, TraceServices::TPagedArray< InItemType, InPageType >::First(), TraceServices::TPagedArray< InItemType, InPageType >::GetPages(), TraceServices::TPagedArray< InItemType, InPageType >::GetPageSize(), TraceServices::TPagedArray< InItemType, InPageType >::Last(), MakeArrayView(), TArrayView< InElementType, InSizeType >::Num(), TraceServices::TPagedArray< InItemType, InPageType >::Num(), TraceServices::TPagedArray< InItemType, InPageType >::NumPages(), and Algo::UpperBoundBy().
GetFileActivityProviderName()
TRACESERVICES_API FName TraceServices::GetFileActivityProviderName ()
GetFileActivityTypeString()
TRACESERVICES_API const TCHAR * TraceServices::GetFileActivityTypeString (EFileActivityType ActivityType)
GetFirstItem() [1/2]
template<typename ItemType> const ItemType * TraceServices::GetFirstItem (const TPagedArrayPage< ItemType > & Page) inline
Definition at line 44 of file PagedArray.h.
References TraceServices::TPagedArrayPage< ItemType >::Items.
GetFirstItem() [2/2]
template<typename ItemType> const ItemType * TraceServices::GetFirstItem (const TVariablePagedArrayPage< ItemType > & Page) inline
Definition at line 82 of file VariablePagedArray.h.
References TraceServices::TVariablePagedArrayPage< ItemType >::ItemOffset, and TraceServices::TVariablePagedArrayPage< ItemType >::Items.
GetFrameProviderName()
TRACESERVICES_API FName TraceServices::GetFrameProviderName ()
GetLastItem() [1/2]
template<typename ItemType> const ItemType * TraceServices::GetLastItem (const TPagedArrayPage< ItemType > & Page) inline
Definition at line 50 of file PagedArray.h.
References TraceServices::TPagedArrayPage< ItemType >::Count, and TraceServices::TPagedArrayPage< ItemType >::Items.
GetLastItem() [2/2]
template<typename ItemType> const ItemType * TraceServices::GetLastItem (const TVariablePagedArrayPage< ItemType > & Page) inline
Definition at line 88 of file VariablePagedArray.h.
References TraceServices::TVariablePagedArrayPage< ItemType >::ItemCount, TraceServices::TVariablePagedArrayPage< ItemType >::ItemOffset, and TraceServices::TVariablePagedArrayPage< ItemType >::Items.
GetLoadTimeProfilerObjectEventTypeString()
TRACESERVICES_API const TCHAR * TraceServices::GetLoadTimeProfilerObjectEventTypeString (ELoadTimeProfilerObjectEventType EventType)
GetLoadTimeProfilerProviderName()
TRACESERVICES_API FName TraceServices::GetLoadTimeProfilerProviderName ()
GetLogProviderName()
TRACESERVICES_API FName TraceServices::GetLogProviderName ()
GetMemoryProviderName()
TRACESERVICES_API FName TraceServices::GetMemoryProviderName ()
GetMetadataProviderName()
TRACESERVICES_API FName TraceServices::GetMetadataProviderName ()
GetModuleProviderName()
TRACESERVICES_API FName TraceServices::GetModuleProviderName ()
GetNetProfilerProviderName()
TRACESERVICES_API FName TraceServices::GetNetProfilerProviderName ()
GetNum() [1/3]
template<typename ItemType, typename PageType> SIZE_T TraceServices::GetNum (const TPagedArray< ItemType, PageType > & PagedArray) inline
Definition at line 760 of file PagedArray.h.
References TraceServices::TPagedArray< InItemType, InPageType >::NumPages().
GetNum() [2/3]
template<typename ItemType> SIZE_T TraceServices::GetNum (const TPagedArrayPage< ItemType > & Page) inline
Definition at line 38 of file PagedArray.h.
References TraceServices::TPagedArrayPage< ItemType >::Count.
Referenced by TraceServices::PagedArrayAlgo::BinarySearchClosest(), TraceServices::PagedArrayAlgo::BinarySearchClosest(), TraceServices::PagedArrayAlgo::BinarySearchClosestBy(), TraceServices::PagedArrayAlgo::BinarySearchClosestBy(), TraceServices::PagedArrayAlgo::LowerBound(), TraceServices::PagedArrayAlgo::LowerBound(), TraceServices::PagedArrayAlgo::LowerBoundBy(), TraceServices::PagedArrayAlgo::LowerBoundBy(), TraceServices::PagedArrayAlgo::UpperBound(), TraceServices::PagedArrayAlgo::UpperBound(), TraceServices::PagedArrayAlgo::UpperBoundBy(), and TraceServices::PagedArrayAlgo::UpperBoundBy().
GetNum() [3/3]
template<typename ItemType> SIZE_T TraceServices::GetNum (const TVariablePagedArrayPage< ItemType > & Page) inline
Definition at line 76 of file VariablePagedArray.h.
References TraceServices::TVariablePagedArrayPage< ItemType >::ItemCount.
GetRegionProviderName()
TRACESERVICES_API FName TraceServices::GetRegionProviderName ()
References GetRegionProviderName().
Referenced by GetRegionProviderName().
GetScreenshotProviderName()
TRACESERVICES_API FName TraceServices::GetScreenshotProviderName ()
GetStackSamplesProviderName()
TRACESERVICES_API FName TraceServices::GetStackSamplesProviderName ()
GetTaskProviderName()
TRACESERVICES_API FName TraceServices::GetTaskProviderName ()
GetThreadProviderName()
TRACESERVICES_API FName TraceServices::GetThreadProviderName ()
GetTimingProfilerProviderName()
TRACESERVICES_API FName TraceServices::GetTimingProfilerProviderName ()
LexToString() [1/2]
TRACESERVICES_API const TCHAR * TraceServices::LexToString (const ENetProfilerChannelCloseReason Value)
References Value.
LexToString() [2/2]
TRACESERVICES_API const TCHAR * TraceServices::LexToString (const ENetProfilerConnectionState Value)
References Value.
ModuleStatusToString()
const TCHAR * TraceServices::ModuleStatusToString (EModuleStatus Result) inline
Definition at line 109 of file Modules.h.
References StatusNum, TEXT, and UE_ARRAY_COUNT.
QueryResultToString()
const TCHAR * TraceServices::QueryResultToString (ESymbolQueryResult Result) inline
Helper method to get a string representation of the query result.
Definition at line 36 of file Modules.h.
References StatusNum, TEXT, and UE_ARRAY_COUNT.
ReadAllocationsProvider()
TRACESERVICES_API const IAllocationsProvider * TraceServices::ReadAllocationsProvider (const IAnalysisSession & Session)
ReadBookmarkProvider()
TRACESERVICES_API const IBookmarkProvider & TraceServices::ReadBookmarkProvider (const IAnalysisSession & Session)
ReadCallstacksProvider()
TRACESERVICES_API const ICallstacksProvider * TraceServices::ReadCallstacksProvider (const IAnalysisSession & Session)
ReadChannelProvider()
TRACESERVICES_API const IChannelProvider * TraceServices::ReadChannelProvider (const IAnalysisSession & Session)
ReadContextSwitchesProvider()
TRACESERVICES_API const IContextSwitchesProvider * TraceServices::ReadContextSwitchesProvider (const IAnalysisSession & Session)
ReadCookProfilerProvider()
TRACESERVICES_API const ICookProfilerProvider * TraceServices::ReadCookProfilerProvider (const IAnalysisSession & Session)
ReadCounterProvider()
TRACESERVICES_API const ICounterProvider & TraceServices::ReadCounterProvider (const IAnalysisSession & Session)
ReadCsvProfilerProvider()
TRACESERVICES_API const ICsvProfilerProvider * TraceServices::ReadCsvProfilerProvider (const IAnalysisSession & Session)
ReadDefinitionProvider()
TRACESERVICES_API const IDefinitionProvider * TraceServices::ReadDefinitionProvider (const IAnalysisSession & Session)
ReadDiagnosticsProvider()
TRACESERVICES_API const IDiagnosticsProvider * TraceServices::ReadDiagnosticsProvider (const IAnalysisSession & Session)
ReadFileActivityProvider()
TRACESERVICES_API const IFileActivityProvider * TraceServices::ReadFileActivityProvider (const IAnalysisSession & Session)
ReadFrameProvider()
TRACESERVICES_API const IFrameProvider & TraceServices::ReadFrameProvider (const IAnalysisSession & Session)
ReadLoadTimeProfilerProvider()
TRACESERVICES_API const ILoadTimeProfilerProvider * TraceServices::ReadLoadTimeProfilerProvider (const IAnalysisSession & Session)
ReadLogProvider()
TRACESERVICES_API const ILogProvider & TraceServices::ReadLogProvider (const IAnalysisSession & Session)
ReadMemoryProvider()
TRACESERVICES_API const IMemoryProvider * TraceServices::ReadMemoryProvider (const IAnalysisSession & Session)
ReadMetadataProvider()
TRACESERVICES_API const IMetadataProvider * TraceServices::ReadMetadataProvider (const IAnalysisSession & Session)
ReadModuleProvider()
TRACESERVICES_API const IModuleProvider * TraceServices::ReadModuleProvider (const IAnalysisSession & Session)
ReadNetProfilerProvider()
TRACESERVICES_API const INetProfilerProvider * TraceServices::ReadNetProfilerProvider (const IAnalysisSession & Session)
ReadRegionProvider()
TRACESERVICES_API const IRegionProvider & TraceServices::ReadRegionProvider (const IAnalysisSession & Session)
References ReadRegionProvider().
Referenced by ReadRegionProvider().
ReadScreenshotProvider()
TRACESERVICES_API const IScreenshotProvider & TraceServices::ReadScreenshotProvider (const IAnalysisSession & Session)
ReadStackSamplesProvider()
TRACESERVICES_API const IStackSamplesProvider & TraceServices::ReadStackSamplesProvider (const IAnalysisSession & Session)
ReadTasksProvider()
TRACESERVICES_API const ITasksProvider * TraceServices::ReadTasksProvider (const IAnalysisSession & Session)
ReadThreadProvider()
TRACESERVICES_API const IThreadProvider & TraceServices::ReadThreadProvider (const IAnalysisSession & Session)
ReadTimingProfilerProvider()
TRACESERVICES_API const ITimingProfilerProvider * TraceServices::ReadTimingProfilerProvider (const IAnalysisSession & Session)
StringFormat()
TRACESERVICES_API void TraceServices::StringFormat (TCHAR * Out, uint64 MaxOut, TCHAR * Temp, uint64 MaxTemp, const TCHAR * FormatString, const uint8 * FormatArgs)
References FormatString().
Table2Csv()
TRACESERVICES_API bool TraceServices::Table2Csv (const IUntypedTable & Table, const TCHAR * Filename)
References Filename.
Variable Documentation
ModuleFeatureName
TRACESERVICES_API const FName TraceServices::ModuleFeatureName extern