Unreal Engine 5.6 C++ API: UE::AssetRegistry Namespace Reference
UE::AssetRegistry Namespace Reference
Namespaces
namespace Impl
namespace Private
Data Structures
struct FDependencyQuery
A struct that is equivalent to EDependencyQuery, but is more useful for performance in filtering operations.
class FFiltering
struct FPackageCustomVersion
Low-memory version of FCustomVersion; holds only Guid and integer version.
class FPackageCustomVersionsHandle
A handle to a deduplicated, sorted array of FPackageCustomVersion.
struct FWritePackageDataArgs
Typedefs
using FChunkArrayRegistryHandle = FSetElementId
Enumerations
enum class EDependencyCategory : uint8 {
Package = 0x01 , Manage = 0x02 , SearchableName = 0x04 , None = 0x0 ,
All = Package | Manage | SearchableName
}
Multiple meanings of dependency are used in the AssetRegistry; the category specifes which meaning is referred to.
enum class EDependencyProperty : uint8 {
None = 0 , PackageMask = 0x7 , Hard = 0x1 , Game = 0x2 ,
Build = 0x4 , SearchableNameMask = 0x0 , ManageMask = 0x8 , Direct = 0x8 ,
AllMask = PackageMask | SearchableNameMask | ManageMask
}
Properties that might be possessed by a dependency.
enum class EDependencyQuery : uint32 {
NoRequirements = 0 , Hard = 0x0001 , NotHard = 0x002 , Soft = NotHard ,
Game = 0x004 , NotGame = 0x008 , EditorOnly = NotGame , Build = 0x010 ,
NotBuild = 0x020 , Propagation = 0x040 , Direct = 0x0400 , NotDirect = 0x0800 ,
Indirect = NotDirect , PackageMask = 0x00ff , SearchableNameMask = 0x0000 , ManageMask = 0x0f00
}
Flags that specify required properties (or required-not-present properties) for a dependency to be returned from a query.
enum class EEnumerateAssetsFlags : uint32 { None = 0 , OnlyOnDiskAssets = (1 << 0) , AllowUnmountedPaths = (1 << 1) , AllowUnfilteredArAssets = (1 << 2) }
enum class EExists { DoesNotExist , Exists , Unknown }
Return values for AssetRegistry functions.
enum class EExtraDependencyFlags : uint32 { None = 0 , Build = 0x1 , PropagateManage = 0x2 }
Bitfield of flags written into a package's AssetRegistry DependencyData section to represent what kind of dependency is stored for each PackageName in ExtraPackageDependencies.
enum class ESerializationTarget : uint8 { ForGame , ForDevelopment }
Options used to read/write the DevelopmentAssetRegistry when serializing, which includes all data.
Functions
ENUM_CLASS_FLAGS (EDependencyCategory)
ENUM_CLASS_FLAGS (EDependencyProperty)
ENUM_CLASS_FLAGS (EDependencyQuery)
ENUM_CLASS_FLAGS (EEnumerateAssetsFlags)
ENUM_CLASS_FLAGS (EExtraDependencyFlags)
FName GetClassNameBlueprint ()
FName GetClassNameBlueprintCore ()
FName GetClassNameBlueprintGeneratedClass ()
FName GetClassNameObject ()
FName GetClassNameObjectRedirector ()
FTopLevelAssetPath GetClassPathBlueprint ()
FTopLevelAssetPath GetClassPathBlueprintCore ()
FTopLevelAssetPath GetClassPathBlueprintGeneratedClass ()
FTopLevelAssetPath GetClassPathObject ()
FTopLevelAssetPath GetClassPathObjectRedirector ()
FName GetScriptPackageNameBlueprintGraph ()
FName GetScriptPackageNameCoreUObject ()
FName GetScriptPackageNameEngine ()
FName GetScriptPackageNameUnrealEd ()
UE_DEPRECATED (5.5, "Use version that takes FWritePackageDataArgs")
void WritePackageData (FStructuredArchiveRecord &ParentRecord, bool bIsCooking, const UPackage *Package, FLinkerSave *Linker, const TSet< TObjectPtr< UObject > > &ImportsUsedInGame, const TSet< FName > &SoftPackagesUsedInGame, const ITargetPlatform *TargetPlatform, TArray< FAssetData > *OutAssetDatas)
void WritePackageData (FStructuredArchiveRecord &ParentRecord, FArchiveCookContext *CookContext, const UPackage *Package, FLinkerSave *Linker, const TSet< TObjectPtr< UObject > > &ImportsUsedInGame, const TSet< FName > &SoftPackagesUsedInGame, TArray< FAssetData > *OutAssetDatas, bool bProceduralSave)
void WritePackageData (FWritePackageDataArgs &Args)
Writes the data used by the AssetRegistry in each package; the format of this data is separate from the format of the data in the asset registry.
Variables
constexpr FStringView CookTagPrefix = TEXTVIEW("Cook_")
We have to store all tags as Name/String pairs, without any extra data for e.g.
Typedef Documentation
FChunkArrayRegistryHandle
using UE::AssetRegistry::FChunkArrayRegistryHandle = FSetElementId
Definition at line 123 of file AssetData.h.
Enumeration Type Documentation
EDependencyCategory
enum class UE::AssetRegistry::EDependencyCategory : uint8 strong
Multiple meanings of dependency are used in the AssetRegistry; the category specifes which meaning is referred to.
During queries for dependencies, the Category variable can be a bitfield combination of Category values, in which case dependencies in any of the specified categories are returned.
Enumerator
Package
Manage
SearchableName
None
All
Definition at line 70 of file AssetRegistryInterface.h.
EDependencyProperty
enum class UE::AssetRegistry::EDependencyProperty : uint8 strong
Properties that might be possessed by a dependency.
Each property is specific to a EDependencyCategory value.
Enumerator
None
PackageMask
Hard
Game
Build
SearchableNameMask
ManageMask
Direct
AllMask
Definition at line 87 of file AssetRegistryInterface.h.
EDependencyQuery
enum class UE::AssetRegistry::EDependencyQuery : uint32 strong
Flags that specify required properties (or required-not-present properties) for a dependency to be returned from a query.
Values in this enum correspond to values in EDependencyProperty; each EDependencyProperty value has a positive and negative equivalent in this enum. This allows a single bitfield to indicate required-present, required-not-present, or dont-care for each property. For any category-specific values, those values apply only to dependencies in the category, and do not impose restrictions on dependencies from other categories.
Enumerator
NoRequirements
Hard
NotHard
Soft
Game
NotGame
EditorOnly
Build
NotBuild
Propagation
Direct
NotDirect
Indirect
PackageMask
SearchableNameMask
ManageMask
Definition at line 116 of file AssetRegistryInterface.h.
EEnumerateAssetsFlags
enum class UE::AssetRegistry::EEnumerateAssetsFlags : uint32 strong
Enumerator
None
OnlyOnDiskAssets
AllowUnmountedPaths
AllowUnfilteredArAssets
Definition at line 167 of file AssetRegistryInterface.h.
EExists
enum class UE::AssetRegistry::EExists strong
Return values for AssetRegistry functions.
Enumerator
DoesNotExist
Exists
Unknown
Definition at line 160 of file AssetRegistryInterface.h.
EExtraDependencyFlags
enum class UE::AssetRegistry::EExtraDependencyFlags : uint32 strong
Bitfield of flags written into a package's AssetRegistry DependencyData section to represent what kind of dependency is stored for each PackageName in ExtraPackageDependencies.
Values are serialized as integers; new bits can be added as necessary, but the integer values for existing enum values may not be changed.
Enumerator
None
Build
PropagateManage
Definition at line 251 of file AssetRegistryInterface.h.
ESerializationTarget
enum class UE::AssetRegistry::ESerializationTarget : uint8 strong
Options used to read/write the DevelopmentAssetRegistry when serializing, which includes all data.
Enumerator
ForGame
ForDevelopment
Definition at line 151 of file AssetRegistryInterface.h.
Function Documentation
ENUM_CLASS_FLAGS() [1/5]
UE::AssetRegistry::ENUM_CLASS_FLAGS (EDependencyCategory)
ENUM_CLASS_FLAGS() [2/5]
UE::AssetRegistry::ENUM_CLASS_FLAGS (EDependencyProperty)
ENUM_CLASS_FLAGS() [3/5]
UE::AssetRegistry::ENUM_CLASS_FLAGS (EDependencyQuery)
ENUM_CLASS_FLAGS() [4/5]
UE::AssetRegistry::ENUM_CLASS_FLAGS (EEnumerateAssetsFlags)
ENUM_CLASS_FLAGS() [5/5]
UE::AssetRegistry::ENUM_CLASS_FLAGS (EExtraDependencyFlags)
GetClassNameBlueprint()
FName UE::AssetRegistry::GetClassNameBlueprint ()
References GetClassNameBlueprint().
Referenced by GetClassNameBlueprint().
GetClassNameBlueprintCore()
FName UE::AssetRegistry::GetClassNameBlueprintCore ()
References GetClassNameBlueprintCore().
Referenced by GetClassNameBlueprintCore().
GetClassNameBlueprintGeneratedClass()
FName UE::AssetRegistry::GetClassNameBlueprintGeneratedClass ()
References GetClassNameBlueprintGeneratedClass().
Referenced by GetClassNameBlueprintGeneratedClass().
GetClassNameObject()
FName UE::AssetRegistry::GetClassNameObject ()
References GetClassNameObject().
Referenced by GetClassNameObject().
GetClassNameObjectRedirector()
FName UE::AssetRegistry::GetClassNameObjectRedirector ()
References GetClassNameObjectRedirector().
Referenced by GetClassNameObjectRedirector().
GetClassPathBlueprint()
FTopLevelAssetPath UE::AssetRegistry::GetClassPathBlueprint ()
References GetClassPathBlueprint().
Referenced by GetClassPathBlueprint().
GetClassPathBlueprintCore()
FTopLevelAssetPath UE::AssetRegistry::GetClassPathBlueprintCore ()
References GetClassPathBlueprintCore().
Referenced by GetClassPathBlueprintCore().
GetClassPathBlueprintGeneratedClass()
FTopLevelAssetPath UE::AssetRegistry::GetClassPathBlueprintGeneratedClass ()
References GetClassPathBlueprintGeneratedClass().
Referenced by GetClassPathBlueprintGeneratedClass().
GetClassPathObject()
FTopLevelAssetPath UE::AssetRegistry::GetClassPathObject ()
References GetClassPathObject().
Referenced by GetClassPathObject().
GetClassPathObjectRedirector()
FTopLevelAssetPath UE::AssetRegistry::GetClassPathObjectRedirector ()
References GetClassPathObjectRedirector().
Referenced by GetClassPathObjectRedirector().
GetScriptPackageNameBlueprintGraph()
FName UE::AssetRegistry::GetScriptPackageNameBlueprintGraph ()
References GetScriptPackageNameBlueprintGraph().
Referenced by GetScriptPackageNameBlueprintGraph().
GetScriptPackageNameCoreUObject()
FName UE::AssetRegistry::GetScriptPackageNameCoreUObject ()
References GetScriptPackageNameCoreUObject().
Referenced by GetScriptPackageNameCoreUObject().
GetScriptPackageNameEngine()
FName UE::AssetRegistry::GetScriptPackageNameEngine ()
References GetScriptPackageNameEngine().
Referenced by GetScriptPackageNameEngine().
GetScriptPackageNameUnrealEd()
FName UE::AssetRegistry::GetScriptPackageNameUnrealEd ()
References GetScriptPackageNameUnrealEd().
Referenced by GetScriptPackageNameUnrealEd().
UE_DEPRECATED()
UE::AssetRegistry::UE_DEPRECATED (5. 5, "Use version that takes FWritePackageDataArgs")
WritePackageData() [1/3]
void UE::AssetRegistry::WritePackageData (FStructuredArchiveRecord & ParentRecord, bool bIsCooking, const UPackage * Package, FLinkerSave * Linker, const TSet< TObjectPtr< UObject > > & ImportsUsedInGame, const TSet< FName > & SoftPackagesUsedInGame, const ITargetPlatform * TargetPlatform, TArray< FAssetData > * OutAssetDatas)
References Package, and WritePackageData().
WritePackageData() [2/3]
void UE::AssetRegistry::WritePackageData (FStructuredArchiveRecord & ParentRecord, FArchiveCookContext * CookContext, const UPackage * Package, FLinkerSave * Linker, const TSet< TObjectPtr< UObject > > & ImportsUsedInGame, const TSet< FName > & SoftPackagesUsedInGame, TArray< FAssetData > * OutAssetDatas, bool bProceduralSave)
References Package, and WritePackageData().
WritePackageData() [3/3]
void UE::AssetRegistry::WritePackageData (FWritePackageDataArgs & Args)
Writes the data used by the AssetRegistry in each package; the format of this data is separate from the format of the data in the asset registry.
The corresponding read functions are ReadPackageDataMain and ReadPackageDataDependencies; they are are declared in IAssetRegistry.h, in the AssetRegistry module, because they depend upon some structures defined in the AssetRegistry module
References WritePackageData().
Referenced by WritePackageData(), WritePackageData(), and WritePackageData().
Variable Documentation
CookTagPrefix
FStringView UE::AssetRegistry::CookTagPrefix = TEXTVIEW("Cook_") inline constexpr
We have to store all tags as Name/String pairs, without any extra data for e.g.
bIsCookTag, so we use a naming convention on the Name. The FAssetRegistryTagsContextData API prepends CookTagPrefix to tags specified as CookTags, and gives a warning and ignores any regular tags starting with CookTagPrefix.
Definition at line 26 of file AssetRegistryTagsContext.h.