Unreal Engine 5.6 C++ API: FOodleCompressedArray Namespace Reference
FOodleCompressedArray Namespace Reference
Represents a compressed buffer prefixed with the compressed and decompressed size.
Functions
bool CompressData (TArray< uint8 > &OutCompressed, const void *InData, int32 InDataSize, FOodleDataCompression::ECompressor InCompressor, FOodleDataCompression::ECompressionLevel InLevel)
Compress an arbitrary data pointer, replacing existing data.
bool CompressData64 (TArray64< uint8 > &OutCompressed, const void *InData, int64 InDataSize, FOodleDataCompression::ECompressor InCompressor, FOodleDataCompression::ECompressionLevel InLevel)
template<class T>
bool CompressTArray (TArray< uint8 > &OutCompressed, const TArray< T > &InBuffer, FOodleDataCompression::ECompressor InCompressor, FOodleDataCompression::ECompressionLevel InLevel)
Compress an arbitrary data pointer, replacing existing data.
template<class T>
bool CompressTArray64 (TArray64< uint8 > &OutCompressed, const TArray64< T > &InBuffer, FOodleDataCompression::ECompressor InCompressor, FOodleDataCompression::ECompressionLevel InLevel)
bool DecompressToAllocatedBuffer (void *&OutDestinationBuffer, int32 &OutDestinationBufferSize, TArray< uint8 > const &InCompressed)
Decompresses a compressed TArray to a buffer that will be allocated by this function.
bool DecompressToAllocatedBuffer64 (void *&OutDestinationBuffer, int64 &OutDestinationBufferSize, TArray64< uint8 > const &InCompressed)
bool DecompressToExistingBuffer (void *InDestinationBuffer, int64 InDestinationBufferSize, TArray< uint8 > const &InCompressed)
Decompresses a compressed TArray to a buffer that has already been allocated.
bool DecompressToExistingBuffer64 (void *InDestinationBuffer, int64 InDestinationBufferSize, TArray64< uint8 > const &InCompressed)
template<class T>
bool DecompressToTArray (TArray< T > &OutDecompressed, TArray< uint8 > const &InCompressed)
Decompress to a TArray.
template<class T>
bool DecompressToTArray64 (TArray64< T > &OutDecompressed, TArray64< uint8 > const &InCompressed)
int32 PeekSizes (TArray< uint8 > const &InCompressed, int32 &OutCompressedSize, int32 &OutDecompressedSize)
Provides access to the compressed and decompressed sizes.
int32 PeekSizes64 (TArray64< uint8 > const &InCompressed, int64 &OutCompressedSize, int64 &OutDecompressedSize)
Detailed Description
Represents a compressed buffer prefixed with the compressed and decompressed size.
The compressed size is technically double-specified, but affords writing the buffer to disk without any further header. This header is variable sized based on need - 32 bits unless the sizes require it, then its 64 bit.
This is distinct from FCompressedBuffer as it has less overhead, is not intended to seamlessly interface with IoStore, and only supports built-in Oodle.
NOTE any data that will be staged to a pak/iostore should NOT be compressed, as that system will compress for you in a manner appropriate for the platform!
If you just want raw pointers, call OodleDataCompress/Decompress directly.
Function Documentation
CompressData()
bool FOodleCompressedArray::CompressData (TArray< uint8 > & OutCompressed, const void * InData, int32 InDataSize, FOodleDataCompression::ECompressor InCompressor, FOodleDataCompression::ECompressionLevel InLevel)
Compress an arbitrary data pointer, replacing existing data.
Parameters
OutCompressed The destination TArray.
InData The memory to compress.
InDataSize The number of bytes in the InData buffer.
InCompressor The Oodle compressor to use. See discussion.
InLevel The compression level to use. See discussion.
Returns
Success or failure. Failure is usually bad parameter or out-of-memory.
Oodle exposes two knobs for compression - the compression type and the compression level. Type more or less trades decompression speed for compression ratio, and level more or less trades compression speed for ratio.
This makes selection very usage case specific, and it's tough to just recommend a one-size-fits-all parameter set. If you have access to Epic Slack, ask in #oodle-dev. Some more detailed explanation exists adjacent to the EOodleDataCompressor and EOodleDataCompressionLevel declarations.
For common use cases, reference GetCompressorAndLevelForCommonUsage()
NOTE any data that will be staged to a pak/iostore should NOT be compressed, as that system will compress for you in a manner appropriate for the platform!
Referenced by CompressTArray().
CompressData64()
bool FOodleCompressedArray::CompressData64 (TArray64< uint8 > & OutCompressed, const void * InData, int64 InDataSize, FOodleDataCompression::ECompressor InCompressor, FOodleDataCompression::ECompressionLevel InLevel)
Referenced by CompressTArray64().
CompressTArray()
template<class T> bool FOodleCompressedArray::CompressTArray (TArray< uint8 > & OutCompressed, const TArray< T > & InBuffer, FOodleDataCompression::ECompressor InCompressor, FOodleDataCompression::ECompressionLevel InLevel)
Compress an arbitrary data pointer, replacing existing data.
This is just a thunk to CompressData, and exists just for type safety so everyone doesn't have to pull out the raw data from their TArrays.
See CompressData for parameter discussion.
Definition at line 178 of file OodleDataCompressionUtil.h.
References CompressData(), TArray< InElementType, InAllocatorType >::GetData(), and TArray< InElementType, InAllocatorType >::Num().
CompressTArray64()
template<class T> bool FOodleCompressedArray::CompressTArray64 (TArray64< uint8 > & OutCompressed, const TArray64< T > & InBuffer, FOodleDataCompression::ECompressor InCompressor, FOodleDataCompression::ECompressionLevel InLevel)
Definition at line 183 of file OodleDataCompressionUtil.h.
References CompressData64().
DecompressToAllocatedBuffer()
bool FOodleCompressedArray::DecompressToAllocatedBuffer (void *& OutDestinationBuffer, int32 & OutDestinationBufferSize, TArray< uint8 > const & InCompressed)
Decompresses a compressed TArray to a buffer that will be allocated by this function.
Parameters
OutDestinationBuffer The pointer to contain the allocated buffer that contains the decompressed data.
OutDestinationBufferSize Will recieve the size of the buffer allocated.
InCompressed A TArray created by one of the FOodleCompressedArray compression functions.
Returns
Success or failure. Failure is usually because the TArray doesn't actually contain any data, but might fail because 64 bit is needed.
DecompressToAllocatedBuffer64()
bool FOodleCompressedArray::DecompressToAllocatedBuffer64 (void *& OutDestinationBuffer, int64 & OutDestinationBufferSize, TArray64< uint8 > const & InCompressed)
DecompressToExistingBuffer()
bool FOodleCompressedArray::DecompressToExistingBuffer (void * InDestinationBuffer, int64 InDestinationBufferSize, TArray< uint8 > const & InCompressed)
Decompresses a compressed TArray to a buffer that has already been allocated.
Parameters
InDestinationBuffer The buffer to contain the decompressed data.
InDestinationBufferSize Allocated size of InDestinationBuffer; if it is not large enough to hold the decompressed data (as reported by PeekSizes), this function will return false.
InCompressed A TArray created by one of the FOodleCompressedArray compression functions.
Returns
Success or failure. Failure is usually because the FCompressedArray doesn't actually contain any data, but might fail because 64 bit is needed.
Referenced by DecompressToTArray().
DecompressToExistingBuffer64()
bool FOodleCompressedArray::DecompressToExistingBuffer64 (void * InDestinationBuffer, int64 InDestinationBufferSize, TArray64< uint8 > const & InCompressed)
Referenced by DecompressToTArray64().
DecompressToTArray()
template<class T> bool FOodleCompressedArray::DecompressToTArray (TArray< T > & OutDecompressed, TArray< uint8 > const & InCompressed)
Decompress to a TArray.
This should be paired with CompressTArray.
Parameters
OutDecompressed The output TArray. Existing contents will be destroyed.
InCompressed A TArray created by one of the FOodleCompressedArray compression functions.
Returns
Success or failure. Note that if the compress/decompress TArray types are mismatched (i.e. have different sizes) this could fail due to granularity concerns.
Definition at line 198 of file OodleDataCompressionUtil.h.
References DecompressToExistingBuffer(), TArray< InElementType, InAllocatorType >::GetData(), PeekSizes(), and TArray< InElementType, InAllocatorType >::SetNum().
DecompressToTArray64()
template<class T> bool FOodleCompressedArray::DecompressToTArray64 (TArray64< T > & OutDecompressed, TArray64< uint8 > const & InCompressed)
Definition at line 216 of file OodleDataCompressionUtil.h.
References DecompressToExistingBuffer64(), and PeekSizes64().
PeekSizes()
int32 FOodleCompressedArray::PeekSizes (TArray< uint8 > const & InCompressed, int32 & OutCompressedSize, int32 & OutDecompressedSize) inline
Provides access to the compressed and decompressed sizes.
Parameters
InCompressed A TArray generated by a call to one of the FOodleCompressedArray compression functions.
OutCompressedSize The amount of compressed data (The array Num() is this plus the header size).
OutDecompressedSize The number of bytes decompressing the data will produce.
Returns
0 if the FCompressedArray isn't valid, or if the compressed array requires PeekSizes64. Otherwise, the offset to the compressed data in the array.
Definition at line 65 of file OodleDataCompressionUtil.h.
References BYTESWAP_ORDER32(), TArray< InElementType, InAllocatorType >::GetData(), and TArray< InElementType, InAllocatorType >::Num().
Referenced by DecompressToTArray().
PeekSizes64()
int32 FOodleCompressedArray::PeekSizes64 (TArray64< uint8 > const & InCompressed, int64 & OutCompressedSize, int64 & OutDecompressedSize) inline
Definition at line 91 of file OodleDataCompressionUtil.h.
References BYTESWAP_ORDER32(), and BYTESWAP_ORDER64().
Referenced by DecompressToTArray64().