Unreal Engine 5.6 C++ API: UE::Cook Namespace Reference
UE::Cook Namespace Reference
Namespaces
namespace BuildResult
BuildResults are groups of data collected during BuildOperations during incremental cooks.
namespace CookPackageSplitter
namespace Dependency
namespace Private
namespace ResultProjection
Data Structures
class FAssetRegistryMPCollector
class FAssetRegistryPackageMessage
class FAssetRegistryReporterLocal
class FAssetRegistryReporterRemote
struct FBuildResultDependenciesMap
A container for BuildResult names and an array of CookDependencies for each BuildResult.
class FCookDependency
TargetDomain dependencies that can be reported from the class instances in a package.
struct FCookDependencyContext
Context passed into UE_COOK_DEPENDENCY_FUNCTION functions to provide calling flags and receive hash output.
class FCookEventContext
Context structure to provide information about the cook and the event being called on an object during UObject::OnCookEvent, and to receive output from those events.
struct FDelegates
UE::Cook::FDelegates: callbacks for cook events.
struct FInstigator
Category and referencer for how a package was discovered by the cooker.
class FMPCollectorClientMessageContext
class FMPCollectorClientTickContext
class FMPCollectorClientTickPackageContext
class FMPCollectorServerMessageContext
class FMPCollectorServerTickContext
class FMPCollectorServerTickPackageContext
struct FPackageCookRule
Specification of whether a package should be cooked, for use in ModifyCook callbacks by systems that want to mark packages cooked/not-cooked independently of the usual asset-driven and config-driven cook specifications.
struct FStatHistoryInt
struct FWorkerId
Identifier for a CookWorker process launched from a Director process, or for the local process.
class IAssetRegistryReporter
class ICookInfo
Engine interface for information provided by UCookOnTheFlyServer in cook callbacks.
struct IDeterminismConstructDiagnosticsContext
Struct to hold input and receive output of IDeterminismHelper::ConstructDiagnostics.
class IDeterminismHelper
Interface implemented by UObjects that want to store diagnostic data for comparison when a package is found to contain indeterminism by a -diffonly cook or is found to have a FalsePositiveIncrementalSkip by a -incrementalvalidate cook.
struct IDeterminismModifiedExportContext
Struct to hold input and receive output of IDeterminismHelper::OnExportModified.
struct IDeterminismModifiedPackageContext
Extended data for IDeterminismModifiedExportContext.
class IMPCollector
Interface used during cooking to send data collected from save/load on a remote CookWorker to the Director for aggregation into files saves at the end of the cook.
class IMPCollectorForMessage
A subinterface of IMPCollector that uses a ICollectorMessage subclass to serialize the message.
class IMPCollectorMessage
Baseclass for messages used by IMPCollectors that want to interpret their messages as c++ structs.
class TMPCollectorClientMessageCallback
An implementation of IMPCollector that uses an ICollectorMessage subclass to serialize the message, and directs messages received on the client to the given callback.
class TMPCollectorServerMessageCallback
An implementation of IMPCollector that uses an IMPCollectorMessage subclass to serialize the message, and directs messages received on the server to the given callback.
Typedefs
using FCookDependencyFunction = void (*)(FCbFieldViewIterator Args, FCookDependencyContext& Context)
Type of functions used in FCookDependency to append the hash values of arbitrary data.
typedef TMap< FName, TMap< FName, TMap< FName, TArray< FString > > > > FIniSettingContainer
Enumerations
enum class ECookDependency : uint8 {
None = 0 , File = 1 , Function = 2 , TransitiveBuild = 3 ,
Package = 4 , ConsoleVariable = 5 , Config = 6 , SettingsObject = 7 ,
NativeClass = 8 , AssetRegistryQuery = 9 , RedirectionTarget = 10 , Count
}
TypeSelector enum for the FCookDependency variable type.
enum class ECookEvent : uint32 { PlatformCookDependencies }
The list of possible events that the cooker can call on UObjects during load/transform/save.
enum class ECookingDLC { Unknown , Yes , No }
enum class ECookResult : uint8 {
NotAttempted , Succeeded , Failed , NeverCookPlaceholder ,
Invalid , Count , NumBits = FPlatformMath::ConstExprCeilLogTwo(ECookResult::Count)
}
enum class ECookType { Unknown , OnTheFly , ByTheBook }
enum class ECookValidationOptions { None = 0 , RunAssetValidation = 1<<0 , RunMapValidation = 1<<1 , ValidationErrorsAreFatal = 1<<2 }
Validation options used when cooking (.
enum class EInstigator : uint8 {
InvalidCategory , NotYetRequested , Unspecified , StartupPackage ,
StartupPackageCookLoadScope , AlwaysCookMap , IniMapSection , IniAllMaps ,
CommandLinePackage , CommandLineDirectory , DirectoryToAlwaysCook , FullDepotSearch ,
GameDefaultObject , InputSettingsIni , StartupSoftObjectPath , PackagingSettingsMapToCook ,
ModifyCookDelegate , AssetManagerModifyCook , AssetManagerModifyDLCCook , TargetPlatformExtraPackagesToCook ,
ConsoleCommand , CookOnTheFly , LegacyIterativeCook , PreviousAssetRegistry ,
RequestPackageFunction , Dependency , HardDependency , HardEditorOnlyDependency ,
SoftDependency , Unsolicited , EditorOnlyLoad , SaveTimeHardDependency ,
SaveTimeSoftDependency , ForceExplorableSaveTimeSoftDependency , GeneratedPackage , BuildDependency ,
Count
}
The different ways a package can be discovered by the cooker.
enum class EMPCookGeneratorSplit : uint8 { AnyWorker , AllOnSameWorker , SomeOnSameWorker , NoneOnSameWorker }
MPCook Behavior set from config/commandline that decides where generatedpackages should be assigned.
enum class EPackageCookRule { None , AddToCook , NeverCook }
Values for whether a package should be cooked, used in ModifyCook callbacks by systems that want to mark packages cooked/not-cooked independently of the usual asset-driven and config-driven cook specifications.
enum class EProcessType { SingleProcess , Director , Worker , AllMPCook }
The cookcommandlet can run in MPCook mode, where it creates worker processes to use more parallelism and reduce wall time of the cook.
Functions
DECLARE_DELEGATE_RetVal_TwoParams (EDataValidationResult, FValidateSourcePackage, UPackage *, FDataValidationContext &)
DECLARE_MULTICAST_DELEGATE_OneParam (FCookInfoEvent, ICookInfo &)
DECLARE_MULTICAST_DELEGATE_TwoParams (FPackageBlockedEvent, const UObject *, FStringBuilderBase &OutDebugInfo) DECLARE_MULTICAST_DELEGATE_TwoParams(FCookInfoModifyCookDelegate
ENUM_CLASS_FLAGS (ECookValidationOptions)
const TCHAR * GetReferencedSetFilename ()
Return the relative path under the cook output MetaData folder to the ReferencedSet file.
const TCHAR * GetReferencedSetOpName ()
Return the name of the op used to store the ReferencedSet in the zenserver oplog.
void InitializeCookGlobals ()
Initialize some globals that are used to track engine activity relevant to the cook before the cooker is created.
const TCHAR * LexToString (EInstigator Value)
Typedef Documentation
FCookDependencyFunction
using UE::Cook::FCookDependencyFunction = void (*)(FCbFieldViewIterator Args, FCookDependencyContext& Context)
Type of functions used in FCookDependency to append the hash values of arbitrary data.
Parameters
Args Variable-length, variable-typed input data (e.g. names of files, configuration flags) that specify which hash data. The function should read this data using FCbFieldViewIterator methods and LoadFromCompactBinary calls that correspond to the FCbWriter methods used at the callsite of FCookDependency::Function.
Context that provides calling flags and receives the hashdata. The function should call Context.Update with the data to be added to the target key (e.g. the hash of the contents of a filename that was specified in Args).
Definition at line 399 of file CookDependency.h.
FIniSettingContainer
typedef TMap<FName, TMap<FName, TMap<FName, TArray<FString> > > > UE::Cook::FIniSettingContainer
Definition at line 250 of file CookOnTheFlyServer.h.
Enumeration Type Documentation
ECookDependency
enum class UE::Cook::ECookDependency : uint8 strong
TypeSelector enum for the FCookDependency variable type.
Values are serialized into the oplog as integers, so do not change them without changing oplog version.
Enumerator
None
File
Function
TransitiveBuild
Package
ConsoleVariable
Config
SettingsObject
NativeClass
AssetRegistryQuery
RedirectionTarget
Count
Definition at line 114 of file CookDependency.h.
ECookEvent
enum class UE::Cook::ECookEvent : uint32 strong
The list of possible events that the cooker can call on UObjects during load/transform/save.
Native UObject classes can respond to these events by overriding UObject::OnCookEvent. All UObject classes should call their Super class's version of the function during their call.
Enumerator
PlatformCookDependencies
Called when saving the package to fetch the list of build and runtime dependencies required by the object that are not automaticallyd detected and need to be manually declared.
For example, a dependency on an AssetRegistry query, or a runtime dependency for platforms that enabled Nanite materials on the nanite material that is declared as editoronly for non-Nanite-enabled platforms. When called for objects in packages being saved for th cook, it is calledfor each object immediately after PreSave on that object.
This event is also called on objects in packages that are transitive build dependencies of other packages but are not cooked themselves. For example, a DataTable can include another DataTable, and needs to depend on all of the dependencies of the DataTable it includes, but the DataTable it includes is not needed at runtime. When called for objects in these build dependency packages, it is called by itself, with no BeginCacheForCookedPlatformData, PreSave, or save-Serialize functions being called on the Object.
This event is also be called when NOT cooking. In that case, it provides the UObject a way to declare build dependencies that are registered with the AssetRegistry and cause propagation of AssetManager chunk assignments without causing the target to be cooked.
See also
UE::Cook::FCookEventContext::AddLoadBuildDependency.
UObjects that need to declare dependencies should call the Add*Dependency functions on the UE::Cook::FCookEventContext passed into UObject::OnCookEvent.
Definition at line 24 of file CookEvents.h.
ECookingDLC
enum class UE::Cook::ECookingDLC strong
Enumerator
Unknown
Yes
No
Definition at line 18 of file CookEnums.h.
ECookResult
enum class UE::Cook::ECookResult : uint8 strong
Enumerator
NotAttempted
Succeeded
Failed
NeverCookPlaceholder
The package is a NeverCook package that needs to be added to cookresults for dependency tracking.
Invalid
No information for this platform (used in CookWorker replication)
Count
NumBits
Definition at line 42 of file CookEnums.h.
ECookType
enum class UE::Cook::ECookType strong
Enumerator
Unknown
OnTheFly
ByTheBook
Definition at line 11 of file CookEnums.h.
ECookValidationOptions
enum class UE::Cook::ECookValidationOptions strong
Validation options used when cooking (.
See also
ECookByTheBookOptions for the validation flags used when initializing the cooker)
Enumerator
None
No flags.
RunAssetValidation
Run asset validation (EditorValidatorSubsystem) on assets loaded during cook.
RunMapValidation
Run map validation (MapCheck) on maps loaded during cook.
ValidationErrorsAreFatal
Consider validation errors (from RunAssetValidation or RunMapValidation) as fatal (preventing the package from being cooked)
Definition at line 59 of file CookEnums.h.
EInstigator
enum class UE::Cook::EInstigator : uint8 strong
The different ways a package can be discovered by the cooker.
Enumerator
InvalidCategory
EINSTIGATOR_VALUE_CALLBACK(CPPToken Name, bool bAllowUnparameterized)
NotYetRequested
Unspecified
StartupPackage
StartupPackageCookLoadScope
AlwaysCookMap
IniMapSection
IniAllMaps
CommandLinePackage
CommandLineDirectory
DirectoryToAlwaysCook
FullDepotSearch
GameDefaultObject
InputSettingsIni
StartupSoftObjectPath
PackagingSettingsMapToCook
ModifyCookDelegate
AssetManagerModifyCook
AssetManagerModifyDLCCook
TargetPlatformExtraPackagesToCook
ConsoleCommand
CookOnTheFly
LegacyIterativeCook
PreviousAssetRegistry
RequestPackageFunction
Dependency
HardDependency
HardEditorOnlyDependency
SoftDependency
Unsolicited
EditorOnlyLoad
SaveTimeHardDependency
SaveTimeSoftDependency
ForceExplorableSaveTimeSoftDependency
GeneratedPackage
BuildDependency
Count
Definition at line 112 of file ICookInfo.h.
EMPCookGeneratorSplit
enum class UE::Cook::EMPCookGeneratorSplit : uint8 strong
MPCook Behavior set from config/commandline that decides where generatedpackages should be assigned.
Enumerator
AnyWorker
AllOnSameWorker
SomeOnSameWorker
NoneOnSameWorker
Definition at line 166 of file CookOnTheFlyServer.h.
EPackageCookRule
enum class UE::Cook::EPackageCookRule strong
Values for whether a package should be cooked, used in ModifyCook callbacks by systems that want to mark packages cooked/not-cooked independently of the usual asset-driven and config-driven cook specifications.
Enumerator
None
AddToCook
The package will be cooked (unless specified as NeverCook or not cooked for the platform elsewhere).
NeverCook
The package will be not be cooked.
Definition at line 141 of file ICookInfo.h.
EProcessType
enum class UE::Cook::EProcessType strong
The cookcommandlet can run in MPCook mode, where it creates worker processes to use more parallelism and reduce wall time of the cook.
This enum is reported or received by some API functions on the cooker, and describes whether the current process the cooker and caller are in is the MPCook director, or an MPCook worker, or a cooker running as a singleprocess without MPCook.
Enumerator
SingleProcess
Director
Worker
AllMPCook
Used only when passed as a filter: matches either Director or Worker.
Definition at line 31 of file CookEnums.h.
Function Documentation
DECLARE_DELEGATE_RetVal_TwoParams()
UE::Cook::DECLARE_DELEGATE_RetVal_TwoParams (EDataValidationResult , FValidateSourcePackage , UPackage * , FDataValidationContext &)
DECLARE_MULTICAST_DELEGATE_OneParam()
UE::Cook::DECLARE_MULTICAST_DELEGATE_OneParam (FCookInfoEvent , ICookInfo &)
DECLARE_MULTICAST_DELEGATE_TwoParams()
UE::Cook::DECLARE_MULTICAST_DELEGATE_TwoParams (FPackageBlockedEvent , const UObject * , FStringBuilderBase & OutDebugInfo)
ENUM_CLASS_FLAGS()
UE::Cook::ENUM_CLASS_FLAGS (ECookValidationOptions)
GetReferencedSetFilename()
const TCHAR * UE::Cook::GetReferencedSetFilename ()
Return the relative path under the cook output MetaData folder to the ReferencedSet file.
The ReferencedSet file is a text file list of package names, one per line, that were referenced from the cook session. It does not include previously cooked files in an incremental cook that are no longer referenced. It does not include packages from the base game for a DLC cook.
References GetReferencedSetFilename().
Referenced by GetReferencedSetFilename().
GetReferencedSetOpName()
const TCHAR * UE::Cook::GetReferencedSetOpName ()
Return the name of the op used to store the ReferencedSet in the zenserver oplog.
References GetReferencedSetOpName().
Referenced by GetReferencedSetOpName().
InitializeCookGlobals()
void UE::Cook::InitializeCookGlobals ()
Initialize some globals that are used to track engine activity relevant to the cook before the cooker is created.
This should only be called when setting IsRunningCookCommandlet=true.
References InitializeCookGlobals().
Referenced by InitializeCookGlobals().
LexToString()
const TCHAR * UE::Cook::LexToString (EInstigator Value)
References Value.