Unreal Engine 5.6 C++ API: UE::Geometry::LinearColors Namespace Reference
UE::Geometry::LinearColors Namespace Reference
Color constants in Linear color space.
Functions
FColor AliceBlue3b ()
FLinearColor AliceBlue3f ()
FColor AntiqueWhite3b ()
FLinearColor AntiqueWhite3f ()
FColor Aqua3b ()
FLinearColor Aqua3f ()
FColor Aquamarine3b ()
FLinearColor Aquamarine3f ()
FColor Azure3b ()
FLinearColor Azure3f ()
FColor Beige3b ()
FLinearColor Beige3f ()
FColor Bisque3b ()
FLinearColor Bisque3f ()
FColor Black3b ()
FLinearColor Black3f ()
FColor BlanchedAlmond3b ()
FLinearColor BlanchedAlmond3f ()
FColor Blue3b ()
FLinearColor Blue3f ()
FColor BlueViolet3b ()
FLinearColor BlueViolet3f ()
FColor Brown3b ()
FLinearColor Brown3f ()
FColor Burlywood3b ()
FLinearColor Burlywood3f ()
FColor CadetBlue3b ()
FLinearColor CadetBlue3f ()
FColor Chartreuse3b ()
FLinearColor Chartreuse3f ()
FColor Chocolate3b ()
FLinearColor Chocolate3f ()
FColor Coral3b ()
FLinearColor Coral3f ()
FColor CornflowerBlue3b ()
FLinearColor CornflowerBlue3f ()
FColor Cornsilk3b ()
FLinearColor Cornsilk3f ()
FColor Crimson3b ()
FLinearColor Crimson3f ()
FColor Cyan3b ()
FLinearColor Cyan3f ()
FColor DarkBlue3b ()
FLinearColor DarkBlue3f ()
FColor DarkCyan3b ()
FLinearColor DarkCyan3f ()
FColor DarkGoldenrod3b ()
FLinearColor DarkGoldenrod3f ()
FColor DarkGray3b ()
FLinearColor DarkGray3f ()
FColor DarkGreen3b ()
FLinearColor DarkGreen3f ()
FColor DarkKhaki3b ()
FLinearColor DarkKhaki3f ()
FColor DarkMagenta3b ()
FLinearColor DarkMagenta3f ()
FColor DarkOliveGreen3b ()
FLinearColor DarkOliveGreen3f ()
FColor DarkOrange3b ()
FLinearColor DarkOrange3f ()
FColor DarkOrchid3b ()
FLinearColor DarkOrchid3f ()
FColor DarkRed3b ()
FLinearColor DarkRed3f ()
FColor DarkSalmon3b ()
FLinearColor DarkSalmon3f ()
FColor DarkSeagreen3b ()
FLinearColor DarkSeagreen3f ()
FColor DarkSlateBlue3b ()
FLinearColor DarkSlateBlue3f ()
FColor DarkSlateGray3b ()
FLinearColor DarkSlateGray3f ()
FColor DarkTurquoise3b ()
FLinearColor DarkTurquoise3f ()
FColor DarkViolet3b ()
FLinearColor DarkViolet3f ()
FColor DeepPink3b ()
FLinearColor DeepPink3f ()
FColor DeepSkyBlue3b ()
FLinearColor DeepSkyBlue3f ()
FColor DimGray3b ()
FLinearColor DimGray3f ()
FColor DodgerBlue3b ()
FLinearColor DodgerBlue3f ()
FColor Firebrick3b ()
FLinearColor Firebrick3f ()
FColor FloralWhite3b ()
FLinearColor FloralWhite3f ()
FColor ForestGreen3b ()
FLinearColor ForestGreen3f ()
FColor Fuchsia3b ()
FLinearColor Fuchsia3f ()
FColor Gainsboro3b ()
FLinearColor Gainsboro3f ()
FColor GhostWhite3b ()
FLinearColor GhostWhite3f ()
FColor Gold3b ()
FLinearColor Gold3f ()
FColor Goldenrod3b ()
FLinearColor Goldenrod3f ()
FColor Gray3b ()
FLinearColor Gray3f ()
FColor Green3b ()
FLinearColor Green3f ()
FColor GreenYellow3b ()
FLinearColor GreenYellow3f ()
FColor HoneyDew3b ()
FLinearColor HoneyDew3f ()
FColor HotPink3b ()
FLinearColor HotPink3f ()
FColor IndianRed3b ()
FLinearColor IndianRed3f ()
FColor Indigo3b ()
FLinearColor Indigo3f ()
FColor Ivory3b ()
FLinearColor Ivory3f ()
FColor Khaki3b ()
FLinearColor Khaki3f ()
FColor Lavender3b ()
FLinearColor Lavender3f ()
FColor LavenderBlush3b ()
FLinearColor LavenderBlush3f ()
FColor LawnGreen3b ()
FLinearColor LawnGreen3f ()
FColor LemonChiffon3b ()
FLinearColor LemonChiffon3f ()
FColor LightBlue3b ()
FLinearColor LightBlue3f ()
FColor LightCoral3b ()
FLinearColor LightCoral3f ()
FColor LightCyan3b ()
FLinearColor LightCyan3f ()
FColor LightGoldenrod3b ()
FLinearColor LightGoldenrod3f ()
FColor LightGray3b ()
FLinearColor LightGray3f ()
FColor LightGreen3b ()
FLinearColor LightGreen3f ()
FColor LightPink3b ()
FLinearColor LightPink3f ()
FColor LightSalmon3b ()
FLinearColor LightSalmon3f ()
FColor LightSeaGreen3b ()
FLinearColor LightSeaGreen3f ()
FColor LightSkyBlue3b ()
FLinearColor LightSkyBlue3f ()
FColor LightSlateGray3b ()
FLinearColor LightSlateGray3f ()
FColor LightSteelBlue3b ()
FLinearColor LightSteelBlue3f ()
FColor LightYellow3b ()
FLinearColor LightYellow3f ()
FColor Lime3b ()
FLinearColor Lime3f ()
FColor LimeGreen3b ()
FLinearColor LimeGreen3f ()
template<typename VectorType>
void LinearToSRGB (VectorType &Color)
Apply a Linear to sRGB color transformation on a given color vector.
FColor Linen3b ()
FLinearColor Linen3f ()
FColor Magenta3b ()
FLinearColor Magenta3f ()
template<typename VectorType>
VectorType MakeColor3f (float R, float G, float B)
template<typename VectorType>
VectorType MakeColor4f (float R, float G, float B, float A)
FColor Maroon3b ()
FLinearColor Maroon3f ()
FColor MediumAquamarine3b ()
FLinearColor MediumAquamarine3f ()
FColor MediumBlue3b ()
FLinearColor MediumBlue3f ()
FColor MediumOrchid3b ()
FLinearColor MediumOrchid3f ()
FColor MediumPurple3b ()
FLinearColor MediumPurple3f ()
FColor MediumSeaGreen3b ()
FLinearColor MediumSeaGreen3f ()
FColor MediumSlateBlue3b ()
FLinearColor MediumSlateBlue3f ()
FColor MediumSpringGreen3b ()
FLinearColor MediumSpringGreen3f ()
FColor MediumTurquoise3b ()
FLinearColor MediumTurquoise3f ()
FColor MediumVioletRed3b ()
FLinearColor MediumVioletRed3f ()
FColor MidnightBlue3b ()
FLinearColor MidnightBlue3f ()
FColor MintCream3b ()
FLinearColor MintCream3f ()
FColor MistyRose3b ()
FLinearColor MistyRose3f ()
FColor Moccasin3b ()
FLinearColor Moccasin3f ()
FColor NavajoWhite3b ()
FLinearColor NavajoWhite3f ()
FColor Navy3b ()
FLinearColor Navy3f ()
FColor OldLace3b ()
FLinearColor OldLace3f ()
FColor Olive3b ()
FLinearColor Olive3f ()
FColor OliveDrab3b ()
FLinearColor OliveDrab3f ()
FColor Orange3b ()
FLinearColor Orange3f ()
FColor OrangeRed3b ()
FLinearColor OrangeRed3f ()
FColor Orchid3b ()
FLinearColor Orchid3f ()
FColor PaleGoldenrod3b ()
FLinearColor PaleGoldenrod3f ()
FColor PaleGreen3b ()
FLinearColor PaleGreen3f ()
FColor PaleTurquoise3b ()
FLinearColor PaleTurquoise3f ()
FColor PaleVioletRed3b ()
FLinearColor PaleVioletRed3f ()
FColor PapayaWhip3b ()
FLinearColor PapayaWhip3f ()
FColor PeachPuff3b ()
FLinearColor PeachPuff3f ()
FColor Peru3b ()
FLinearColor Peru3f ()
FColor Pink3b ()
FLinearColor Pink3f ()
FColor Plum3b ()
FLinearColor Plum3f ()
FColor PowderBlue3b ()
FLinearColor PowderBlue3f ()
FColor Purple3b ()
FLinearColor Purple3f ()
FColor Red3b ()
FLinearColor Red3f ()
FColor RosyBrown3b ()
FLinearColor RosyBrown3f ()
FColor RoyalBlue3b ()
FLinearColor RoyalBlue3f ()
FColor SaddleBrown3b ()
FLinearColor SaddleBrown3f ()
FColor Salmon3b ()
FLinearColor Salmon3f ()
FColor SandyBrown3b ()
FLinearColor SandyBrown3f ()
FColor SeaGreen3b ()
FLinearColor SeaGreen3f ()
FColor Seashell3b ()
FLinearColor Seashell3f ()
template<typename VectorType>
VectorType SelectColor (int32 Index)
Select a Color from a fixed color palette based on given Index.
GEOMETRYCORE_API FColor SelectFColor (int32 Index)
Select a FColor from a fixed color palette based on given Index.
FColor Sienna3b ()
FLinearColor Sienna3f ()
FColor Silver3b ()
FLinearColor Silver3f ()
FColor SkyBlue3b ()
FLinearColor SkyBlue3f ()
FColor SlateBlue3b ()
FLinearColor SlateBlue3f ()
FColor SlateGray3b ()
FLinearColor SlateGray3f ()
FColor Snow3b ()
FLinearColor Snow3f ()
FColor SpringGreen3b ()
FLinearColor SpringGreen3f ()
template<typename VectorType>
void SRGBToLinear (VectorType &Color)
Apply an sRGB to Linear color transformation on a given color vector.
FColor SteelBlue3b ()
FLinearColor SteelBlue3f ()
FColor Tan3b ()
FLinearColor Tan3f ()
FColor Teal3b ()
FLinearColor Teal3f ()
FColor Thistle3b ()
FLinearColor Thistle3f ()
FColor Tomato3b ()
FLinearColor Tomato3f ()
FColor Turquoise3b ()
FLinearColor Turquoise3f ()
FColor VideoBlack3b ()
FLinearColor VideoBlack3f ()
FColor VideoBlue3b ()
FLinearColor VideoBlue3f ()
FColor VideoGreen3b ()
FLinearColor VideoGreen3f ()
FColor VideoRed3b ()
FLinearColor VideoRed3f ()
FColor VideoWhite3b ()
FLinearColor VideoWhite3f ()
FColor Violet3b ()
FLinearColor Violet3f ()
FColor Wheat3b ()
FLinearColor Wheat3f ()
FColor White3b ()
FLinearColor White3f ()
FColor WhiteSmoke3b ()
FLinearColor WhiteSmoke3f ()
FColor Yellow3b ()
FLinearColor Yellow3f ()
FColor YellowGreen3b ()
FLinearColor YellowGreen3f ()
Detailed Description
Color constants in Linear color space.
For a given Color name, Color3f<T> defines templated construction of arbitrary float-vector type, and Color3b() constructs an FColor
Function Documentation
AliceBlue3b()
FColor UE::Geometry::LinearColors::AliceBlue3b () inline
Definition at line 98 of file ColorConstants.h.
AliceBlue3f()
FLinearColor UE::Geometry::LinearColors::AliceBlue3f () inline
Definition at line 98 of file ColorConstants.h.
AntiqueWhite3b()
FColor UE::Geometry::LinearColors::AntiqueWhite3b () inline
Definition at line 99 of file ColorConstants.h.
AntiqueWhite3f()
FLinearColor UE::Geometry::LinearColors::AntiqueWhite3f () inline
Definition at line 99 of file ColorConstants.h.
Aqua3b()
FColor UE::Geometry::LinearColors::Aqua3b () inline
Definition at line 100 of file ColorConstants.h.
Aqua3f()
FLinearColor UE::Geometry::LinearColors::Aqua3f () inline
Definition at line 100 of file ColorConstants.h.
Aquamarine3b()
FColor UE::Geometry::LinearColors::Aquamarine3b () inline
Definition at line 101 of file ColorConstants.h.
Aquamarine3f()
FLinearColor UE::Geometry::LinearColors::Aquamarine3f () inline
Definition at line 101 of file ColorConstants.h.
Referenced by SelectColor().
Azure3b()
FColor UE::Geometry::LinearColors::Azure3b () inline
Definition at line 102 of file ColorConstants.h.
Azure3f()
FLinearColor UE::Geometry::LinearColors::Azure3f () inline
Definition at line 102 of file ColorConstants.h.
Beige3b()
FColor UE::Geometry::LinearColors::Beige3b () inline
Definition at line 103 of file ColorConstants.h.
Beige3f()
FLinearColor UE::Geometry::LinearColors::Beige3f () inline
Definition at line 103 of file ColorConstants.h.
Bisque3b()
FColor UE::Geometry::LinearColors::Bisque3b () inline
Definition at line 104 of file ColorConstants.h.
Bisque3f()
FLinearColor UE::Geometry::LinearColors::Bisque3f () inline
Definition at line 104 of file ColorConstants.h.
Black3b()
FColor UE::Geometry::LinearColors::Black3b () inline
Definition at line 68 of file ColorConstants.h.
Black3f()
FLinearColor UE::Geometry::LinearColors::Black3f () inline
Definition at line 68 of file ColorConstants.h.
BlanchedAlmond3b()
FColor UE::Geometry::LinearColors::BlanchedAlmond3b () inline
Definition at line 105 of file ColorConstants.h.
BlanchedAlmond3f()
FLinearColor UE::Geometry::LinearColors::BlanchedAlmond3f () inline
Definition at line 105 of file ColorConstants.h.
Blue3b()
FColor UE::Geometry::LinearColors::Blue3b () inline
Definition at line 74 of file ColorConstants.h.
References Blue.
Blue3f()
FLinearColor UE::Geometry::LinearColors::Blue3f () inline
Definition at line 74 of file ColorConstants.h.
BlueViolet3b()
FColor UE::Geometry::LinearColors::BlueViolet3b () inline
Definition at line 106 of file ColorConstants.h.
BlueViolet3f()
FLinearColor UE::Geometry::LinearColors::BlueViolet3f () inline
Definition at line 106 of file ColorConstants.h.
Brown3b()
FColor UE::Geometry::LinearColors::Brown3b () inline
Definition at line 107 of file ColorConstants.h.
Brown3f()
FLinearColor UE::Geometry::LinearColors::Brown3f () inline
Definition at line 107 of file ColorConstants.h.
Burlywood3b()
FColor UE::Geometry::LinearColors::Burlywood3b () inline
Definition at line 108 of file ColorConstants.h.
Burlywood3f()
FLinearColor UE::Geometry::LinearColors::Burlywood3f () inline
Definition at line 108 of file ColorConstants.h.
Referenced by SelectColor().
CadetBlue3b()
FColor UE::Geometry::LinearColors::CadetBlue3b () inline
Definition at line 109 of file ColorConstants.h.
CadetBlue3f()
FLinearColor UE::Geometry::LinearColors::CadetBlue3f () inline
Definition at line 109 of file ColorConstants.h.
Chartreuse3b()
FColor UE::Geometry::LinearColors::Chartreuse3b () inline
Definition at line 110 of file ColorConstants.h.
Chartreuse3f()
FLinearColor UE::Geometry::LinearColors::Chartreuse3f () inline
Definition at line 110 of file ColorConstants.h.
Chocolate3b()
FColor UE::Geometry::LinearColors::Chocolate3b () inline
Definition at line 111 of file ColorConstants.h.
Chocolate3f()
FLinearColor UE::Geometry::LinearColors::Chocolate3f () inline
Definition at line 111 of file ColorConstants.h.
Coral3b()
FColor UE::Geometry::LinearColors::Coral3b () inline
Definition at line 112 of file ColorConstants.h.
Coral3f()
FLinearColor UE::Geometry::LinearColors::Coral3f () inline
Definition at line 112 of file ColorConstants.h.
Referenced by SelectColor().
CornflowerBlue3b()
FColor UE::Geometry::LinearColors::CornflowerBlue3b () inline
Definition at line 113 of file ColorConstants.h.
CornflowerBlue3f()
FLinearColor UE::Geometry::LinearColors::CornflowerBlue3f () inline
Definition at line 113 of file ColorConstants.h.
Cornsilk3b()
FColor UE::Geometry::LinearColors::Cornsilk3b () inline
Definition at line 114 of file ColorConstants.h.
Cornsilk3f()
FLinearColor UE::Geometry::LinearColors::Cornsilk3f () inline
Definition at line 114 of file ColorConstants.h.
Crimson3b()
FColor UE::Geometry::LinearColors::Crimson3b () inline
Definition at line 115 of file ColorConstants.h.
Crimson3f()
FLinearColor UE::Geometry::LinearColors::Crimson3f () inline
Definition at line 115 of file ColorConstants.h.
Cyan3b()
FColor UE::Geometry::LinearColors::Cyan3b () inline
Definition at line 76 of file ColorConstants.h.
Cyan3f()
FLinearColor UE::Geometry::LinearColors::Cyan3f () inline
Definition at line 76 of file ColorConstants.h.
DarkBlue3b()
FColor UE::Geometry::LinearColors::DarkBlue3b () inline
Definition at line 116 of file ColorConstants.h.
DarkBlue3f()
FLinearColor UE::Geometry::LinearColors::DarkBlue3f () inline
Definition at line 116 of file ColorConstants.h.
DarkCyan3b()
FColor UE::Geometry::LinearColors::DarkCyan3b () inline
Definition at line 117 of file ColorConstants.h.
DarkCyan3f()
FLinearColor UE::Geometry::LinearColors::DarkCyan3f () inline
Definition at line 117 of file ColorConstants.h.
DarkGoldenrod3b()
FColor UE::Geometry::LinearColors::DarkGoldenrod3b () inline
Definition at line 118 of file ColorConstants.h.
DarkGoldenrod3f()
FLinearColor UE::Geometry::LinearColors::DarkGoldenrod3f () inline
Definition at line 118 of file ColorConstants.h.
DarkGray3b()
FColor UE::Geometry::LinearColors::DarkGray3b () inline
Definition at line 119 of file ColorConstants.h.
DarkGray3f()
FLinearColor UE::Geometry::LinearColors::DarkGray3f () inline
Definition at line 119 of file ColorConstants.h.
DarkGreen3b()
FColor UE::Geometry::LinearColors::DarkGreen3b () inline
Definition at line 120 of file ColorConstants.h.
DarkGreen3f()
FLinearColor UE::Geometry::LinearColors::DarkGreen3f () inline
Definition at line 120 of file ColorConstants.h.
DarkKhaki3b()
FColor UE::Geometry::LinearColors::DarkKhaki3b () inline
Definition at line 121 of file ColorConstants.h.
DarkKhaki3f()
FLinearColor UE::Geometry::LinearColors::DarkKhaki3f () inline
Definition at line 121 of file ColorConstants.h.
DarkMagenta3b()
FColor UE::Geometry::LinearColors::DarkMagenta3b () inline
Definition at line 122 of file ColorConstants.h.
DarkMagenta3f()
FLinearColor UE::Geometry::LinearColors::DarkMagenta3f () inline
Definition at line 122 of file ColorConstants.h.
DarkOliveGreen3b()
FColor UE::Geometry::LinearColors::DarkOliveGreen3b () inline
Definition at line 123 of file ColorConstants.h.
DarkOliveGreen3f()
FLinearColor UE::Geometry::LinearColors::DarkOliveGreen3f () inline
Definition at line 123 of file ColorConstants.h.
DarkOrange3b()
FColor UE::Geometry::LinearColors::DarkOrange3b () inline
Definition at line 124 of file ColorConstants.h.
DarkOrange3f()
FLinearColor UE::Geometry::LinearColors::DarkOrange3f () inline
Definition at line 124 of file ColorConstants.h.
DarkOrchid3b()
FColor UE::Geometry::LinearColors::DarkOrchid3b () inline
Definition at line 125 of file ColorConstants.h.
DarkOrchid3f()
FLinearColor UE::Geometry::LinearColors::DarkOrchid3f () inline
Definition at line 125 of file ColorConstants.h.
DarkRed3b()
FColor UE::Geometry::LinearColors::DarkRed3b () inline
Definition at line 126 of file ColorConstants.h.
DarkRed3f()
FLinearColor UE::Geometry::LinearColors::DarkRed3f () inline
Definition at line 126 of file ColorConstants.h.
DarkSalmon3b()
FColor UE::Geometry::LinearColors::DarkSalmon3b () inline
Definition at line 127 of file ColorConstants.h.
DarkSalmon3f()
FLinearColor UE::Geometry::LinearColors::DarkSalmon3f () inline
Definition at line 127 of file ColorConstants.h.
Referenced by SelectColor().
DarkSeagreen3b()
FColor UE::Geometry::LinearColors::DarkSeagreen3b () inline
Definition at line 128 of file ColorConstants.h.
DarkSeagreen3f()
FLinearColor UE::Geometry::LinearColors::DarkSeagreen3f () inline
Definition at line 128 of file ColorConstants.h.
DarkSlateBlue3b()
FColor UE::Geometry::LinearColors::DarkSlateBlue3b () inline
Definition at line 129 of file ColorConstants.h.
DarkSlateBlue3f()
FLinearColor UE::Geometry::LinearColors::DarkSlateBlue3f () inline
Definition at line 129 of file ColorConstants.h.
DarkSlateGray3b()
FColor UE::Geometry::LinearColors::DarkSlateGray3b () inline
Definition at line 130 of file ColorConstants.h.
DarkSlateGray3f()
FLinearColor UE::Geometry::LinearColors::DarkSlateGray3f () inline
Definition at line 130 of file ColorConstants.h.
DarkTurquoise3b()
FColor UE::Geometry::LinearColors::DarkTurquoise3b () inline
Definition at line 131 of file ColorConstants.h.
DarkTurquoise3f()
FLinearColor UE::Geometry::LinearColors::DarkTurquoise3f () inline
Definition at line 131 of file ColorConstants.h.
DarkViolet3b()
FColor UE::Geometry::LinearColors::DarkViolet3b () inline
Definition at line 132 of file ColorConstants.h.
DarkViolet3f()
FLinearColor UE::Geometry::LinearColors::DarkViolet3f () inline
Definition at line 132 of file ColorConstants.h.
DeepPink3b()
FColor UE::Geometry::LinearColors::DeepPink3b () inline
Definition at line 133 of file ColorConstants.h.
DeepPink3f()
FLinearColor UE::Geometry::LinearColors::DeepPink3f () inline
Definition at line 133 of file ColorConstants.h.
DeepSkyBlue3b()
FColor UE::Geometry::LinearColors::DeepSkyBlue3b () inline
Definition at line 134 of file ColorConstants.h.
DeepSkyBlue3f()
FLinearColor UE::Geometry::LinearColors::DeepSkyBlue3f () inline
Definition at line 134 of file ColorConstants.h.
DimGray3b()
FColor UE::Geometry::LinearColors::DimGray3b () inline
Definition at line 135 of file ColorConstants.h.
DimGray3f()
FLinearColor UE::Geometry::LinearColors::DimGray3f () inline
Definition at line 135 of file ColorConstants.h.
DodgerBlue3b()
FColor UE::Geometry::LinearColors::DodgerBlue3b () inline
Definition at line 136 of file ColorConstants.h.
DodgerBlue3f()
FLinearColor UE::Geometry::LinearColors::DodgerBlue3f () inline
Definition at line 136 of file ColorConstants.h.
Firebrick3b()
FColor UE::Geometry::LinearColors::Firebrick3b () inline
Definition at line 137 of file ColorConstants.h.
Firebrick3f()
FLinearColor UE::Geometry::LinearColors::Firebrick3f () inline
Definition at line 137 of file ColorConstants.h.
FloralWhite3b()
FColor UE::Geometry::LinearColors::FloralWhite3b () inline
Definition at line 138 of file ColorConstants.h.
FloralWhite3f()
FLinearColor UE::Geometry::LinearColors::FloralWhite3f () inline
Definition at line 138 of file ColorConstants.h.
ForestGreen3b()
FColor UE::Geometry::LinearColors::ForestGreen3b () inline
Definition at line 139 of file ColorConstants.h.
ForestGreen3f()
FLinearColor UE::Geometry::LinearColors::ForestGreen3f () inline
Definition at line 139 of file ColorConstants.h.
Fuchsia3b()
FColor UE::Geometry::LinearColors::Fuchsia3b () inline
Definition at line 140 of file ColorConstants.h.
Fuchsia3f()
FLinearColor UE::Geometry::LinearColors::Fuchsia3f () inline
Definition at line 140 of file ColorConstants.h.
Gainsboro3b()
FColor UE::Geometry::LinearColors::Gainsboro3b () inline
Definition at line 141 of file ColorConstants.h.
Gainsboro3f()
FLinearColor UE::Geometry::LinearColors::Gainsboro3f () inline
Definition at line 141 of file ColorConstants.h.
GhostWhite3b()
FColor UE::Geometry::LinearColors::GhostWhite3b () inline
Definition at line 142 of file ColorConstants.h.
GhostWhite3f()
FLinearColor UE::Geometry::LinearColors::GhostWhite3f () inline
Definition at line 142 of file ColorConstants.h.
Gold3b()
FColor UE::Geometry::LinearColors::Gold3b () inline
Definition at line 143 of file ColorConstants.h.
Gold3f()
FLinearColor UE::Geometry::LinearColors::Gold3f () inline
Definition at line 143 of file ColorConstants.h.
Goldenrod3b()
FColor UE::Geometry::LinearColors::Goldenrod3b () inline
Definition at line 144 of file ColorConstants.h.
Goldenrod3f()
FLinearColor UE::Geometry::LinearColors::Goldenrod3f () inline
Definition at line 144 of file ColorConstants.h.
Referenced by SelectColor().
Gray3b()
FColor UE::Geometry::LinearColors::Gray3b () inline
Definition at line 70 of file ColorConstants.h.
Gray3f()
FLinearColor UE::Geometry::LinearColors::Gray3f () inline
Definition at line 70 of file ColorConstants.h.
Green3b()
FColor UE::Geometry::LinearColors::Green3b () inline
Definition at line 73 of file ColorConstants.h.
References Green.
Green3f()
FLinearColor UE::Geometry::LinearColors::Green3f () inline
Definition at line 73 of file ColorConstants.h.
GreenYellow3b()
FColor UE::Geometry::LinearColors::GreenYellow3b () inline
Definition at line 145 of file ColorConstants.h.
GreenYellow3f()
FLinearColor UE::Geometry::LinearColors::GreenYellow3f () inline
Definition at line 145 of file ColorConstants.h.
Referenced by SelectColor().
HoneyDew3b()
FColor UE::Geometry::LinearColors::HoneyDew3b () inline
Definition at line 146 of file ColorConstants.h.
HoneyDew3f()
FLinearColor UE::Geometry::LinearColors::HoneyDew3f () inline
Definition at line 146 of file ColorConstants.h.
HotPink3b()
FColor UE::Geometry::LinearColors::HotPink3b () inline
Definition at line 147 of file ColorConstants.h.
HotPink3f()
FLinearColor UE::Geometry::LinearColors::HotPink3f () inline
Definition at line 147 of file ColorConstants.h.
IndianRed3b()
FColor UE::Geometry::LinearColors::IndianRed3b () inline
Definition at line 148 of file ColorConstants.h.
IndianRed3f()
FLinearColor UE::Geometry::LinearColors::IndianRed3f () inline
Definition at line 148 of file ColorConstants.h.
Referenced by SelectColor().
Indigo3b()
FColor UE::Geometry::LinearColors::Indigo3b () inline
Definition at line 149 of file ColorConstants.h.
Indigo3f()
FLinearColor UE::Geometry::LinearColors::Indigo3f () inline
Definition at line 149 of file ColorConstants.h.
Ivory3b()
FColor UE::Geometry::LinearColors::Ivory3b () inline
Definition at line 150 of file ColorConstants.h.
Ivory3f()
FLinearColor UE::Geometry::LinearColors::Ivory3f () inline
Definition at line 150 of file ColorConstants.h.
Khaki3b()
FColor UE::Geometry::LinearColors::Khaki3b () inline
Definition at line 151 of file ColorConstants.h.
Khaki3f()
FLinearColor UE::Geometry::LinearColors::Khaki3f () inline
Definition at line 151 of file ColorConstants.h.
Referenced by SelectColor().
Lavender3b()
FColor UE::Geometry::LinearColors::Lavender3b () inline
Definition at line 152 of file ColorConstants.h.
Lavender3f()
FLinearColor UE::Geometry::LinearColors::Lavender3f () inline
Definition at line 152 of file ColorConstants.h.
Referenced by SelectColor().
LavenderBlush3b()
FColor UE::Geometry::LinearColors::LavenderBlush3b () inline
Definition at line 153 of file ColorConstants.h.
LavenderBlush3f()
FLinearColor UE::Geometry::LinearColors::LavenderBlush3f () inline
Definition at line 153 of file ColorConstants.h.
LawnGreen3b()
FColor UE::Geometry::LinearColors::LawnGreen3b () inline
Definition at line 154 of file ColorConstants.h.
LawnGreen3f()
FLinearColor UE::Geometry::LinearColors::LawnGreen3f () inline
Definition at line 154 of file ColorConstants.h.
LemonChiffon3b()
FColor UE::Geometry::LinearColors::LemonChiffon3b () inline
Definition at line 155 of file ColorConstants.h.
LemonChiffon3f()
FLinearColor UE::Geometry::LinearColors::LemonChiffon3f () inline
Definition at line 155 of file ColorConstants.h.
LightBlue3b()
FColor UE::Geometry::LinearColors::LightBlue3b () inline
Definition at line 156 of file ColorConstants.h.
LightBlue3f()
FLinearColor UE::Geometry::LinearColors::LightBlue3f () inline
Definition at line 156 of file ColorConstants.h.
LightCoral3b()
FColor UE::Geometry::LinearColors::LightCoral3b () inline
Definition at line 157 of file ColorConstants.h.
LightCoral3f()
FLinearColor UE::Geometry::LinearColors::LightCoral3f () inline
Definition at line 157 of file ColorConstants.h.
LightCyan3b()
FColor UE::Geometry::LinearColors::LightCyan3b () inline
Definition at line 158 of file ColorConstants.h.
LightCyan3f()
FLinearColor UE::Geometry::LinearColors::LightCyan3f () inline
Definition at line 158 of file ColorConstants.h.
LightGoldenrod3b()
FColor UE::Geometry::LinearColors::LightGoldenrod3b () inline
Definition at line 159 of file ColorConstants.h.
LightGoldenrod3f()
FLinearColor UE::Geometry::LinearColors::LightGoldenrod3f () inline
Definition at line 159 of file ColorConstants.h.
LightGray3b()
FColor UE::Geometry::LinearColors::LightGray3b () inline
Definition at line 160 of file ColorConstants.h.
LightGray3f()
FLinearColor UE::Geometry::LinearColors::LightGray3f () inline
Definition at line 160 of file ColorConstants.h.
LightGreen3b()
FColor UE::Geometry::LinearColors::LightGreen3b () inline
Definition at line 161 of file ColorConstants.h.
LightGreen3f()
FLinearColor UE::Geometry::LinearColors::LightGreen3f () inline
Definition at line 161 of file ColorConstants.h.
LightPink3b()
FColor UE::Geometry::LinearColors::LightPink3b () inline
Definition at line 162 of file ColorConstants.h.
LightPink3f()
FLinearColor UE::Geometry::LinearColors::LightPink3f () inline
Definition at line 162 of file ColorConstants.h.
Referenced by SelectColor().
LightSalmon3b()
FColor UE::Geometry::LinearColors::LightSalmon3b () inline
Definition at line 163 of file ColorConstants.h.
LightSalmon3f()
FLinearColor UE::Geometry::LinearColors::LightSalmon3f () inline
Definition at line 163 of file ColorConstants.h.
LightSeaGreen3b()
FColor UE::Geometry::LinearColors::LightSeaGreen3b () inline
Definition at line 164 of file ColorConstants.h.
LightSeaGreen3f()
FLinearColor UE::Geometry::LinearColors::LightSeaGreen3f () inline
Definition at line 164 of file ColorConstants.h.
Referenced by SelectColor().
LightSkyBlue3b()
FColor UE::Geometry::LinearColors::LightSkyBlue3b () inline
Definition at line 165 of file ColorConstants.h.
LightSkyBlue3f()
FLinearColor UE::Geometry::LinearColors::LightSkyBlue3f () inline
Definition at line 165 of file ColorConstants.h.
Referenced by SelectColor().
LightSlateGray3b()
FColor UE::Geometry::LinearColors::LightSlateGray3b () inline
Definition at line 166 of file ColorConstants.h.
LightSlateGray3f()
FLinearColor UE::Geometry::LinearColors::LightSlateGray3f () inline
Definition at line 166 of file ColorConstants.h.
LightSteelBlue3b()
FColor UE::Geometry::LinearColors::LightSteelBlue3b () inline
Definition at line 167 of file ColorConstants.h.
LightSteelBlue3f()
FLinearColor UE::Geometry::LinearColors::LightSteelBlue3f () inline
Definition at line 167 of file ColorConstants.h.
Referenced by SelectColor().
LightYellow3b()
FColor UE::Geometry::LinearColors::LightYellow3b () inline
Definition at line 168 of file ColorConstants.h.
LightYellow3f()
FLinearColor UE::Geometry::LinearColors::LightYellow3f () inline
Definition at line 168 of file ColorConstants.h.
Lime3b()
FColor UE::Geometry::LinearColors::Lime3b () inline
Definition at line 169 of file ColorConstants.h.
Lime3f()
FLinearColor UE::Geometry::LinearColors::Lime3f () inline
Definition at line 169 of file ColorConstants.h.
LimeGreen3b()
FColor UE::Geometry::LinearColors::LimeGreen3b () inline
Definition at line 170 of file ColorConstants.h.
LimeGreen3f()
FLinearColor UE::Geometry::LinearColors::LimeGreen3f () inline
Definition at line 170 of file ColorConstants.h.
LinearToSRGB()
template<typename VectorType> void UE::Geometry::LinearColors::LinearToSRGB (VectorType & Color)
Apply a Linear to sRGB color transformation on a given color vector.
Definition at line 39 of file ColorConstants.h.
References TMathUtil< float >::Pow().
Linen3b()
FColor UE::Geometry::LinearColors::Linen3b () inline
Definition at line 171 of file ColorConstants.h.
Linen3f()
FLinearColor UE::Geometry::LinearColors::Linen3f () inline
Definition at line 171 of file ColorConstants.h.
Magenta3b()
FColor UE::Geometry::LinearColors::Magenta3b () inline
Definition at line 77 of file ColorConstants.h.
Magenta3f()
FLinearColor UE::Geometry::LinearColors::Magenta3f () inline
Definition at line 77 of file ColorConstants.h.
MakeColor3f()
template<typename VectorType> VectorType UE::Geometry::LinearColors::MakeColor3f (float R, float G, float B)
Definition at line 53 of file ColorConstants.h.
References B, G, and R.
MakeColor4f()
template<typename VectorType> VectorType UE::Geometry::LinearColors::MakeColor4f (float R, float G, float B, float A)
Definition at line 59 of file ColorConstants.h.
References A, B, G, and R.
Maroon3b()
FColor UE::Geometry::LinearColors::Maroon3b () inline
Definition at line 172 of file ColorConstants.h.
Maroon3f()
FLinearColor UE::Geometry::LinearColors::Maroon3f () inline
Definition at line 172 of file ColorConstants.h.
MediumAquamarine3b()
FColor UE::Geometry::LinearColors::MediumAquamarine3b () inline
Definition at line 173 of file ColorConstants.h.
MediumAquamarine3f()
FLinearColor UE::Geometry::LinearColors::MediumAquamarine3f () inline
Definition at line 173 of file ColorConstants.h.
Referenced by SelectColor().
MediumBlue3b()
FColor UE::Geometry::LinearColors::MediumBlue3b () inline
Definition at line 174 of file ColorConstants.h.
MediumBlue3f()
FLinearColor UE::Geometry::LinearColors::MediumBlue3f () inline
Definition at line 174 of file ColorConstants.h.
MediumOrchid3b()
FColor UE::Geometry::LinearColors::MediumOrchid3b () inline
Definition at line 175 of file ColorConstants.h.
MediumOrchid3f()
FLinearColor UE::Geometry::LinearColors::MediumOrchid3f () inline
Definition at line 175 of file ColorConstants.h.
MediumPurple3b()
FColor UE::Geometry::LinearColors::MediumPurple3b () inline
Definition at line 176 of file ColorConstants.h.
MediumPurple3f()
FLinearColor UE::Geometry::LinearColors::MediumPurple3f () inline
Definition at line 176 of file ColorConstants.h.
MediumSeaGreen3b()
FColor UE::Geometry::LinearColors::MediumSeaGreen3b () inline
Definition at line 177 of file ColorConstants.h.
MediumSeaGreen3f()
FLinearColor UE::Geometry::LinearColors::MediumSeaGreen3f () inline
Definition at line 177 of file ColorConstants.h.
MediumSlateBlue3b()
FColor UE::Geometry::LinearColors::MediumSlateBlue3b () inline
Definition at line 178 of file ColorConstants.h.
MediumSlateBlue3f()
FLinearColor UE::Geometry::LinearColors::MediumSlateBlue3f () inline
Definition at line 178 of file ColorConstants.h.
MediumSpringGreen3b()
FColor UE::Geometry::LinearColors::MediumSpringGreen3b () inline
Definition at line 179 of file ColorConstants.h.
MediumSpringGreen3f()
FLinearColor UE::Geometry::LinearColors::MediumSpringGreen3f () inline
Definition at line 179 of file ColorConstants.h.
Referenced by SelectColor().
MediumTurquoise3b()
FColor UE::Geometry::LinearColors::MediumTurquoise3b () inline
Definition at line 180 of file ColorConstants.h.
MediumTurquoise3f()
FLinearColor UE::Geometry::LinearColors::MediumTurquoise3f () inline
Definition at line 180 of file ColorConstants.h.
MediumVioletRed3b()
FColor UE::Geometry::LinearColors::MediumVioletRed3b () inline
Definition at line 181 of file ColorConstants.h.
MediumVioletRed3f()
FLinearColor UE::Geometry::LinearColors::MediumVioletRed3f () inline
Definition at line 181 of file ColorConstants.h.
MidnightBlue3b()
FColor UE::Geometry::LinearColors::MidnightBlue3b () inline
Definition at line 182 of file ColorConstants.h.
MidnightBlue3f()
FLinearColor UE::Geometry::LinearColors::MidnightBlue3f () inline
Definition at line 182 of file ColorConstants.h.
MintCream3b()
FColor UE::Geometry::LinearColors::MintCream3b () inline
Definition at line 183 of file ColorConstants.h.
MintCream3f()
FLinearColor UE::Geometry::LinearColors::MintCream3f () inline
Definition at line 183 of file ColorConstants.h.
MistyRose3b()
FColor UE::Geometry::LinearColors::MistyRose3b () inline
Definition at line 184 of file ColorConstants.h.
MistyRose3f()
FLinearColor UE::Geometry::LinearColors::MistyRose3f () inline
Definition at line 184 of file ColorConstants.h.
Moccasin3b()
FColor UE::Geometry::LinearColors::Moccasin3b () inline
Definition at line 185 of file ColorConstants.h.
Moccasin3f()
FLinearColor UE::Geometry::LinearColors::Moccasin3f () inline
Definition at line 185 of file ColorConstants.h.
NavajoWhite3b()
FColor UE::Geometry::LinearColors::NavajoWhite3b () inline
Definition at line 186 of file ColorConstants.h.
NavajoWhite3f()
FLinearColor UE::Geometry::LinearColors::NavajoWhite3f () inline
Definition at line 186 of file ColorConstants.h.
Navy3b()
FColor UE::Geometry::LinearColors::Navy3b () inline
Definition at line 187 of file ColorConstants.h.
Navy3f()
FLinearColor UE::Geometry::LinearColors::Navy3f () inline
Definition at line 187 of file ColorConstants.h.
OldLace3b()
FColor UE::Geometry::LinearColors::OldLace3b () inline
Definition at line 188 of file ColorConstants.h.
OldLace3f()
FLinearColor UE::Geometry::LinearColors::OldLace3f () inline
Definition at line 188 of file ColorConstants.h.
Olive3b()
FColor UE::Geometry::LinearColors::Olive3b () inline
Definition at line 189 of file ColorConstants.h.
Olive3f()
FLinearColor UE::Geometry::LinearColors::Olive3f () inline
Definition at line 189 of file ColorConstants.h.
OliveDrab3b()
FColor UE::Geometry::LinearColors::OliveDrab3b () inline
Definition at line 190 of file ColorConstants.h.
OliveDrab3f()
FLinearColor UE::Geometry::LinearColors::OliveDrab3f () inline
Definition at line 190 of file ColorConstants.h.
Orange3b()
FColor UE::Geometry::LinearColors::Orange3b () inline
Definition at line 191 of file ColorConstants.h.
Orange3f()
FLinearColor UE::Geometry::LinearColors::Orange3f () inline
Definition at line 191 of file ColorConstants.h.
OrangeRed3b()
FColor UE::Geometry::LinearColors::OrangeRed3b () inline
Definition at line 192 of file ColorConstants.h.
OrangeRed3f()
FLinearColor UE::Geometry::LinearColors::OrangeRed3f () inline
Definition at line 192 of file ColorConstants.h.
Orchid3b()
FColor UE::Geometry::LinearColors::Orchid3b () inline
Definition at line 193 of file ColorConstants.h.
Orchid3f()
FLinearColor UE::Geometry::LinearColors::Orchid3f () inline
Definition at line 193 of file ColorConstants.h.
PaleGoldenrod3b()
FColor UE::Geometry::LinearColors::PaleGoldenrod3b () inline
Definition at line 194 of file ColorConstants.h.
PaleGoldenrod3f()
FLinearColor UE::Geometry::LinearColors::PaleGoldenrod3f () inline
Definition at line 194 of file ColorConstants.h.
PaleGreen3b()
FColor UE::Geometry::LinearColors::PaleGreen3b () inline
Definition at line 195 of file ColorConstants.h.
PaleGreen3f()
FLinearColor UE::Geometry::LinearColors::PaleGreen3f () inline
Definition at line 195 of file ColorConstants.h.
Referenced by SelectColor().
PaleTurquoise3b()
FColor UE::Geometry::LinearColors::PaleTurquoise3b () inline
Definition at line 196 of file ColorConstants.h.
PaleTurquoise3f()
FLinearColor UE::Geometry::LinearColors::PaleTurquoise3f () inline
Definition at line 196 of file ColorConstants.h.
PaleVioletRed3b()
FColor UE::Geometry::LinearColors::PaleVioletRed3b () inline
Definition at line 197 of file ColorConstants.h.
PaleVioletRed3f()
FLinearColor UE::Geometry::LinearColors::PaleVioletRed3f () inline
Definition at line 197 of file ColorConstants.h.
PapayaWhip3b()
FColor UE::Geometry::LinearColors::PapayaWhip3b () inline
Definition at line 198 of file ColorConstants.h.
PapayaWhip3f()
FLinearColor UE::Geometry::LinearColors::PapayaWhip3f () inline
Definition at line 198 of file ColorConstants.h.
PeachPuff3b()
FColor UE::Geometry::LinearColors::PeachPuff3b () inline
Definition at line 199 of file ColorConstants.h.
PeachPuff3f()
FLinearColor UE::Geometry::LinearColors::PeachPuff3f () inline
Definition at line 199 of file ColorConstants.h.
Peru3b()
FColor UE::Geometry::LinearColors::Peru3b () inline
Definition at line 200 of file ColorConstants.h.
Peru3f()
FLinearColor UE::Geometry::LinearColors::Peru3f () inline
Definition at line 200 of file ColorConstants.h.
Pink3b()
FColor UE::Geometry::LinearColors::Pink3b () inline
Definition at line 201 of file ColorConstants.h.
Pink3f()
FLinearColor UE::Geometry::LinearColors::Pink3f () inline
Definition at line 201 of file ColorConstants.h.
Plum3b()
FColor UE::Geometry::LinearColors::Plum3b () inline
Definition at line 202 of file ColorConstants.h.
Plum3f()
FLinearColor UE::Geometry::LinearColors::Plum3f () inline
Definition at line 202 of file ColorConstants.h.
Referenced by SelectColor().
PowderBlue3b()
FColor UE::Geometry::LinearColors::PowderBlue3b () inline
Definition at line 203 of file ColorConstants.h.
PowderBlue3f()
FLinearColor UE::Geometry::LinearColors::PowderBlue3f () inline
Definition at line 203 of file ColorConstants.h.
Purple3b()
FColor UE::Geometry::LinearColors::Purple3b () inline
Definition at line 204 of file ColorConstants.h.
Purple3f()
FLinearColor UE::Geometry::LinearColors::Purple3f () inline
Definition at line 204 of file ColorConstants.h.
Red3b()
FColor UE::Geometry::LinearColors::Red3b () inline
Definition at line 72 of file ColorConstants.h.
References Red.
Red3f()
FLinearColor UE::Geometry::LinearColors::Red3f () inline
Definition at line 72 of file ColorConstants.h.
RosyBrown3b()
FColor UE::Geometry::LinearColors::RosyBrown3b () inline
Definition at line 205 of file ColorConstants.h.
RosyBrown3f()
FLinearColor UE::Geometry::LinearColors::RosyBrown3f () inline
Definition at line 205 of file ColorConstants.h.
RoyalBlue3b()
FColor UE::Geometry::LinearColors::RoyalBlue3b () inline
Definition at line 206 of file ColorConstants.h.
RoyalBlue3f()
FLinearColor UE::Geometry::LinearColors::RoyalBlue3f () inline
Definition at line 206 of file ColorConstants.h.
SaddleBrown3b()
FColor UE::Geometry::LinearColors::SaddleBrown3b () inline
Definition at line 207 of file ColorConstants.h.
SaddleBrown3f()
FLinearColor UE::Geometry::LinearColors::SaddleBrown3f () inline
Definition at line 207 of file ColorConstants.h.
Salmon3b()
FColor UE::Geometry::LinearColors::Salmon3b () inline
Definition at line 208 of file ColorConstants.h.
Salmon3f()
FLinearColor UE::Geometry::LinearColors::Salmon3f () inline
Definition at line 208 of file ColorConstants.h.
Referenced by SelectColor().
SandyBrown3b()
FColor UE::Geometry::LinearColors::SandyBrown3b () inline
Definition at line 209 of file ColorConstants.h.
SandyBrown3f()
FLinearColor UE::Geometry::LinearColors::SandyBrown3f () inline
Definition at line 209 of file ColorConstants.h.
SeaGreen3b()
FColor UE::Geometry::LinearColors::SeaGreen3b () inline
Definition at line 210 of file ColorConstants.h.
SeaGreen3f()
FLinearColor UE::Geometry::LinearColors::SeaGreen3f () inline
Definition at line 210 of file ColorConstants.h.
Seashell3b()
FColor UE::Geometry::LinearColors::Seashell3b () inline
Definition at line 211 of file ColorConstants.h.
Seashell3f()
FLinearColor UE::Geometry::LinearColors::Seashell3f () inline
Definition at line 211 of file ColorConstants.h.
SelectColor()
template<typename VectorType> VectorType UE::Geometry::LinearColors::SelectColor (int32 Index)
Select a Color from a fixed color palette based on given Index.
Parameters
Index arbitrary integer
Returns
Color selected from a fixed set, or White if Index < 0
Definition at line 241 of file ColorConstants.h.
References Aquamarine3f(), Burlywood3f(), Coral3f(), DarkSalmon3f(), Goldenrod3f(), GreenYellow3f(), IndianRed3f(), Khaki3f(), Lavender3f(), LightPink3f(), LightSeaGreen3f(), LightSkyBlue3f(), LightSteelBlue3f(), MediumAquamarine3f(), MediumSpringGreen3f(), PaleGreen3f(), Plum3f(), Salmon3f(), SpringGreen3f(), Thistle3f(), Wheat3f(), and White3f().
SelectFColor()
GEOMETRYCORE_API FColor UE::Geometry::LinearColors::SelectFColor (int32 Index)
Select a FColor from a fixed color palette based on given Index.
Parameters
Index arbitrary integer
Returns
Color selected from a fixed set, or White if Index < 0
Sienna3b()
FColor UE::Geometry::LinearColors::Sienna3b () inline
Definition at line 212 of file ColorConstants.h.
Sienna3f()
FLinearColor UE::Geometry::LinearColors::Sienna3f () inline
Definition at line 212 of file ColorConstants.h.
Silver3b()
FColor UE::Geometry::LinearColors::Silver3b () inline
Definition at line 213 of file ColorConstants.h.
Silver3f()
FLinearColor UE::Geometry::LinearColors::Silver3f () inline
Definition at line 213 of file ColorConstants.h.
SkyBlue3b()
FColor UE::Geometry::LinearColors::SkyBlue3b () inline
Definition at line 214 of file ColorConstants.h.
SkyBlue3f()
FLinearColor UE::Geometry::LinearColors::SkyBlue3f () inline
Definition at line 214 of file ColorConstants.h.
SlateBlue3b()
FColor UE::Geometry::LinearColors::SlateBlue3b () inline
Definition at line 215 of file ColorConstants.h.
SlateBlue3f()
FLinearColor UE::Geometry::LinearColors::SlateBlue3f () inline
Definition at line 215 of file ColorConstants.h.
SlateGray3b()
FColor UE::Geometry::LinearColors::SlateGray3b () inline
Definition at line 216 of file ColorConstants.h.
SlateGray3f()
FLinearColor UE::Geometry::LinearColors::SlateGray3f () inline
Definition at line 216 of file ColorConstants.h.
Snow3b()
FColor UE::Geometry::LinearColors::Snow3b () inline
Definition at line 217 of file ColorConstants.h.
Snow3f()
FLinearColor UE::Geometry::LinearColors::Snow3f () inline
Definition at line 217 of file ColorConstants.h.
SpringGreen3b()
FColor UE::Geometry::LinearColors::SpringGreen3b () inline
Definition at line 218 of file ColorConstants.h.
SpringGreen3f()
FLinearColor UE::Geometry::LinearColors::SpringGreen3f () inline
Definition at line 218 of file ColorConstants.h.
Referenced by SelectColor().
SRGBToLinear()
template<typename VectorType> void UE::Geometry::LinearColors::SRGBToLinear (VectorType & Color)
Apply an sRGB to Linear color transformation on a given color vector.
Definition at line 24 of file ColorConstants.h.
References TMathUtil< float >::Pow().
SteelBlue3b()
FColor UE::Geometry::LinearColors::SteelBlue3b () inline
Definition at line 219 of file ColorConstants.h.
SteelBlue3f()
FLinearColor UE::Geometry::LinearColors::SteelBlue3f () inline
Definition at line 219 of file ColorConstants.h.
Tan3b()
FColor UE::Geometry::LinearColors::Tan3b () inline
Definition at line 220 of file ColorConstants.h.
Tan3f()
FLinearColor UE::Geometry::LinearColors::Tan3f () inline
Definition at line 220 of file ColorConstants.h.
Teal3b()
FColor UE::Geometry::LinearColors::Teal3b () inline
Definition at line 221 of file ColorConstants.h.
Teal3f()
FLinearColor UE::Geometry::LinearColors::Teal3f () inline
Definition at line 221 of file ColorConstants.h.
Thistle3b()
FColor UE::Geometry::LinearColors::Thistle3b () inline
Definition at line 222 of file ColorConstants.h.
Thistle3f()
FLinearColor UE::Geometry::LinearColors::Thistle3f () inline
Definition at line 222 of file ColorConstants.h.
Referenced by SelectColor().
Tomato3b()
FColor UE::Geometry::LinearColors::Tomato3b () inline
Definition at line 223 of file ColorConstants.h.
Tomato3f()
FLinearColor UE::Geometry::LinearColors::Tomato3f () inline
Definition at line 223 of file ColorConstants.h.
Turquoise3b()
FColor UE::Geometry::LinearColors::Turquoise3b () inline
Definition at line 224 of file ColorConstants.h.
Turquoise3f()
FLinearColor UE::Geometry::LinearColors::Turquoise3f () inline
Definition at line 224 of file ColorConstants.h.
VideoBlack3b()
FColor UE::Geometry::LinearColors::VideoBlack3b () inline
Definition at line 79 of file ColorConstants.h.
VideoBlack3f()
FLinearColor UE::Geometry::LinearColors::VideoBlack3f () inline
Definition at line 79 of file ColorConstants.h.
VideoBlue3b()
FColor UE::Geometry::LinearColors::VideoBlue3b () inline
Definition at line 83 of file ColorConstants.h.
VideoBlue3f()
FLinearColor UE::Geometry::LinearColors::VideoBlue3f () inline
Definition at line 83 of file ColorConstants.h.
VideoGreen3b()
FColor UE::Geometry::LinearColors::VideoGreen3b () inline
Definition at line 82 of file ColorConstants.h.
VideoGreen3f()
FLinearColor UE::Geometry::LinearColors::VideoGreen3f () inline
Definition at line 82 of file ColorConstants.h.
VideoRed3b()
FColor UE::Geometry::LinearColors::VideoRed3b () inline
Definition at line 81 of file ColorConstants.h.
VideoRed3f()
FLinearColor UE::Geometry::LinearColors::VideoRed3f () inline
Definition at line 81 of file ColorConstants.h.
VideoWhite3b()
FColor UE::Geometry::LinearColors::VideoWhite3b () inline
Definition at line 80 of file ColorConstants.h.
VideoWhite3f()
FLinearColor UE::Geometry::LinearColors::VideoWhite3f () inline
Definition at line 80 of file ColorConstants.h.
Violet3b()
FColor UE::Geometry::LinearColors::Violet3b () inline
Definition at line 225 of file ColorConstants.h.
Violet3f()
FLinearColor UE::Geometry::LinearColors::Violet3f () inline
Definition at line 225 of file ColorConstants.h.
Wheat3b()
FColor UE::Geometry::LinearColors::Wheat3b () inline
Definition at line 226 of file ColorConstants.h.
Wheat3f()
FLinearColor UE::Geometry::LinearColors::Wheat3f () inline
Definition at line 226 of file ColorConstants.h.
Referenced by SelectColor().
White3b()
FColor UE::Geometry::LinearColors::White3b () inline
Definition at line 69 of file ColorConstants.h.
White3f()
FLinearColor UE::Geometry::LinearColors::White3f () inline
Definition at line 69 of file ColorConstants.h.
Referenced by SelectColor().
WhiteSmoke3b()
FColor UE::Geometry::LinearColors::WhiteSmoke3b () inline
Definition at line 227 of file ColorConstants.h.
WhiteSmoke3f()
FLinearColor UE::Geometry::LinearColors::WhiteSmoke3f () inline
Definition at line 227 of file ColorConstants.h.
Yellow3b()
FColor UE::Geometry::LinearColors::Yellow3b () inline
Definition at line 75 of file ColorConstants.h.
References Yellow.
Yellow3f()
FLinearColor UE::Geometry::LinearColors::Yellow3f () inline
Definition at line 75 of file ColorConstants.h.
YellowGreen3b()
FColor UE::Geometry::LinearColors::YellowGreen3b () inline
Definition at line 228 of file ColorConstants.h.
YellowGreen3f()
FLinearColor UE::Geometry::LinearColors::YellowGreen3f () inline
Definition at line 228 of file ColorConstants.h.