Unreal Engine 5.6 C++ API: Algo::Private Namespace Reference
Algo::Private Namespace Reference
Data Structures
struct TTiedTupleAdder
Functions
template<typename InAT, typename InBT, typename ProjectionT, typename PredicateT>
constexpr bool Compare (const InAT &InputA, const InBT &InputB, ProjectionT Projection, PredicateT Predicate)
template<typename DataTypeA, typename SizeTypeA, typename DataTypeB, typename SizeTypeB, typename ProjectionType, typename SortPredicateType>
constexpr bool Includes (const DataTypeA *DataA, SizeTypeA NumA, const DataTypeB *DataB, SizeTypeB NumB, ProjectionType Projection, SortPredicateType SortPredicate)
template<typename InputAType, typename InputBType, typename ProjectionType, typename PredicateType>
constexpr auto Mismatch (const InputAType &InputA, const InputBType &InputB, ProjectionType Projection, PredicateType Predicate)
Function Documentation
Compare()
template<typename InAT, typename InBT, typename ProjectionT, typename PredicateT> bool Algo::Private::Compare (const InAT & InputA, const InBT & InputB, ProjectionT Projection, PredicateT Predicate) constexpr
Definition at line 15 of file Compare.h.
References A, B, Algo::Count(), GetData(), GetNum(), Invoke(), Predicate, and Projection().
Referenced by Algo::Compare(), Algo::Compare(), Algo::CompareBy(), and Algo::CompareBy().
Includes()
template<typename DataTypeA, typename SizeTypeA, typename DataTypeB, typename SizeTypeB, typename ProjectionType, typename SortPredicateType> bool Algo::Private::Includes (const DataTypeA * DataA, SizeTypeA NumA, const DataTypeB * DataB, SizeTypeB NumB, ProjectionType Projection, SortPredicateType SortPredicate) constexpr
Definition at line 14 of file Includes.h.
References Invoke(), and Projection().
Referenced by Algo::Includes(), Algo::Includes(), Algo::IncludesBy(), and Algo::IncludesBy().
Mismatch()
template<typename InputAType, typename InputBType, typename ProjectionType, typename PredicateType> auto Algo::Private::Mismatch (const InputAType & InputA, const InputBType & InputB, ProjectionType Projection, PredicateType Predicate) constexpr
Definition at line 16 of file Mismatch.h.
References A, B, GetData(), GetNum(), Invoke(), Predicate, and Projection().
Referenced by Algo::Mismatch(), Algo::Mismatch(), Algo::MismatchBy(), and Algo::MismatchBy().