Unreal Engine 5.6 C++ API: FutureDetail Namespace Reference
FutureDetail Namespace Reference
Functions
template<typename Func, typename ParamType, typename ResultType>
void SetPromiseValue (TPromise< ResultType > &Promise, Func &Function, TFuture< ParamType > &&Param)
Template for setting a promise value from a continuation.
template<typename Func, typename ParamType>
void SetPromiseValue (TPromise< void > &Promise, Func &Function, TFuture< ParamType > &&Param)
Function Documentation
SetPromiseValue() [1/2]
template<typename Func, typename ParamType, typename ResultType> void FutureDetail::SetPromiseValue (TPromise< ResultType > & Promise, Func & Function, TFuture< ParamType > && Param) inline
Template for setting a promise value from a continuation.
Definition at line 704 of file Future.h.
References Function, MoveTemp(), and TPromise< ResultType >::SetValue().
Referenced by TFutureBase< ResultType >::Then().
SetPromiseValue() [2/2]
template<typename Func, typename ParamType> void FutureDetail::SetPromiseValue (TPromise< void > & Promise, Func & Function, TFuture< ParamType > && Param) inline
Definition at line 709 of file Future.h.
References Function, MoveTemp(), and TPromise< ResultType >::SetValue().