Unreal Engine 5.6 C++ API: FStaticSpatialIndex Namespace Reference
FStaticSpatialIndex Namespace Reference
Data Structures
struct FCone
struct FSpatialIndexProfile2D
struct FSpatialIndexProfile3D
struct FSphere
class TImpl
class TListImpl
class TNodeSorterHilbert
class TNodeSorterMinX
class TNodeSorterMorton
class TNodeSorterNoSort
class TRTreeImpl
Functions
template<typename Profile>
bool FastConeAABBIntersection (const typename Profile::FVector &InCenter, const typename Profile::FReal InRadiusSquared, const typename Profile::FVector &InAxis, const typename Profile::FReal InAngle, const typename Profile::FReal InSinHalfAngle, const typename Profile::FReal InCosHalfAngle, const typename Profile::FBox &InBox)
template<typename Profile>
bool FastSphereAABBIntersection (const typename Profile::FVector &InCenter, const typename Profile::FReal InRadiusSquared, const typename Profile::FBox &InBox)
Function Documentation
FastConeAABBIntersection()
template<typename Profile> bool FStaticSpatialIndex::FastConeAABBIntersection (const typename Profile::FVector & InCenter, const typename Profile::FReal InRadiusSquared, const typename Profile::FVector & InAxis, const typename Profile::FReal InAngle, const typename Profile::FReal InSinHalfAngle, const typename Profile::FReal InCosHalfAngle, const typename Profile::FBox & InBox) inline
Definition at line 63 of file StaticSpatialIndex.h.
References UE::Math::TVector2< double >::CrossProduct(), UE::Math::TVector2< double >::DotProduct(), FastSphereAABBIntersection(), FMath::Square(), and UE_PI.
Referenced by FStaticSpatialIndex::TListImpl< Profile >::ForEachIntersectingElement(), and FStaticSpatialIndex::TRTreeImpl< Profile, MaxNumElementsPerNode, MaxNumElementsPerLeaf >::ForEachIntersectingElementRecursive().
FastSphereAABBIntersection()
template<typename Profile> bool FStaticSpatialIndex::FastSphereAABBIntersection (const typename Profile::FVector & InCenter, const typename Profile::FReal InRadiusSquared, const typename Profile::FBox & InBox) inline
Definition at line 33 of file StaticSpatialIndex.h.
Referenced by FastConeAABBIntersection(), FStaticSpatialIndex::TListImpl< Profile >::ForEachIntersectingElement(), FStaticSpatialIndex::TRTreeImpl< Profile, MaxNumElementsPerNode, MaxNumElementsPerLeaf >::ForEachIntersectingElementRecursive(), and FStaticSpatialIndex::TRTreeImpl< Profile, MaxNumElementsPerNode, MaxNumElementsPerLeaf >::ForEachIntersectingElementRecursive().