Unreal Engine 5.6 C++ API: UE::Net::Private Namespace Reference
UE::Net::Private Namespace Reference
===================== NetSerialize and NetDeltaSerialize customization.
Namespaces
namespace GranularMemoryTracking
Data Structures
struct FActorDormantReplicators
Container that stores all the replicators owned by a given dormant Actor.
class FCoreNetContext
struct FDormantObjectReplicator
Container holding the FObjectReplicator of a dormant replicated object.
struct FDormantReplicatorHolder
Container that stores the object replicators of dormant actors and their subobjects.
class FRefCountedNetGUIDArray
Simple class to manage a reference-counted array of FNetworkGUIDs.
class FScopedRemoteRPCMode
Enumerations
enum class ERemoteFunctionMode { None , Receiving , Sending }
Functions
template<int32 ScaleFactor, int32 MaxBitsPerComponent>
bool LegacyReadPackedVector (FVector3f &Value, FArchive &Ar)
constexpr int32 PingTypeToIdx (EPingType PingType)
Converts an EPingType flag to an array index at compile time.
static int32 PingTypeToIdxRuntime (EPingType PingType)
Converts an EPingType flag to an array index at runtime.
Variables
int32 SerializeNewActorOverrideLevel
Allow other internal systems to check this cvar.
Detailed Description
===================== NetSerialize and NetDeltaSerialize customization.
=====================
The main purpose of this file it to hold custom methods for NetSerialization and NetDeltaSerialization. A longer explanation on how this all works is covered below. For quick reference however, this is how to customize net serialization for structs.
To define your own NetSerialize and NetDeltaSerialize on a structure: (of course you don't need to define both! Usually you only want to define one, but for brevity Im showing both at once) Everything related to Fast TArray Replication has been moved to "Net/Serialization/FastArraySerializer.h" ===================== Vector NetSerialization customization. ===================== Provides custom NetSerilization for FVectors.
There are two types of net quantization available:
Fixed Quantization (SerializeFixedVector) -Fixed number of bits -Max Value specified as template parameter
Serialized value is scaled based on num bits and max value. Precision is determined by MaxValue and NumBits (if 2^NumBits is > MaxValue, you will have room for extra precision).
This format is good for things like normals, where the magnitudes are often similar. For example normal values may often be in the 0.1f - 1.f range. In a packed format, the overhead in serializing num of bits per component would outweigh savings from serializing very small (< 0.1f) values.
It is also good for performance critical sections since you can guarantee byte alignment if that is important.
Packed Quantization (SerializePackedVector) -Scaling factor (usually 10, 100, etc) -Max number of bits per component (this is maximum, not a constant)
The format is <num of bits per component> <N bits for X> <N bits for Y> <N bits for Z>
The advantages to this format are that packed nature. You may support large magnitudes and have as much precision as you want. All while having small magnitudes take less space.
The trade off is that there is overhead in serializing how many bits are used for each component, and byte alignment is almost always thrown off.
Enumeration Type Documentation
ERemoteFunctionMode
enum class UE::Net::Private::ERemoteFunctionMode strong
Enumerator
None
Receiving
Sending
Definition at line 15 of file CoreNetContext.h.
Function Documentation
LegacyReadPackedVector()
template<int32 ScaleFactor, int32 MaxBitsPerComponent> bool UE::Net::Private::LegacyReadPackedVector (FVector3f & Value, FArchive & Ar)
Definition at line 179 of file NetSerialization.h.
References Ar, float, UE::Max, and Value.
Referenced by ReadPackedVector(), ReadPackedVector(), SerializePackedVector(), and SerializePackedVector().
PingTypeToIdx()
int32 UE::Net::Private::PingTypeToIdx (EPingType PingType) constexpr
Converts an EPingType flag to an array index at compile time.
Parameters
PingType The EPingType flag to convert
Returns
The index that the flag represents
Definition at line 27 of file NetPing.h.
References Value.
PingTypeToIdxRuntime()
int32 UE::Net::Private::PingTypeToIdxRuntime (EPingType PingType) static
Converts an EPingType flag to an array index at runtime.
Parameters
PingType The EPingType flag to convert
Returns
The index that the flag represents
Definition at line 48 of file NetPing.h.
Variable Documentation
SerializeNewActorOverrideLevel
int32 UE::Net::Private::SerializeNewActorOverrideLevel extern
Allow other internal systems to check this cvar.