Unreal Engine 5.6 C++ API: RigVMPythonUtils Namespace Reference
RigVMPythonUtils Namespace Reference
Enumerations
enum EPythonizeNameCase : uint8 { Lower , Upper }
How should PythonizeName adjust the final name?
Functions
template<typename T>
FString EnumValueToPythonString (int64 Value)
RIGVMDEVELOPER_API FString EnumValueToPythonString (UEnum *Enum, int64 Value)
RIGVMDEVELOPER_API FString LinearColorToPythonString (const FLinearColor &Color)
RIGVMDEVELOPER_API void Print (const FString &BlueprintTitle, const FString &InMessage)
RIGVMDEVELOPER_API void PrintPythonContext (const FString &InBlueprintName)
RIGVMDEVELOPER_API FString PythonizeName (FStringView InName, const EPythonizeNameCase InNameCase=EPythonizeNameCase::Lower)
RIGVMDEVELOPER_API FString TransformToPythonString (const FTransform &Transform)
RIGVMDEVELOPER_API FString Vector2DToPythonString (const FVector2D &Vector)
Enumeration Type Documentation
EPythonizeNameCase
enum RigVMPythonUtils::EPythonizeNameCase : uint8
How should PythonizeName adjust the final name?
Enumerator
Lower
lower_snake_case
Upper
UPPER_SNAKE_CASE.
Definition at line 19 of file RigVMPythonUtils.h.
Function Documentation
EnumValueToPythonString() [1/2]
template<typename T> FString RigVMPythonUtils::EnumValueToPythonString (int64 Value)
Definition at line 38 of file RigVMPythonUtils.h.
References EnumValueToPythonString(), StaticEnum(), and Value.
EnumValueToPythonString() [2/2]
RIGVMDEVELOPER_API FString RigVMPythonUtils::EnumValueToPythonString (UEnum * Enum, int64 Value)
References Enum, and Value.
Referenced by EnumValueToPythonString().
LinearColorToPythonString()
RIGVMDEVELOPER_API FString RigVMPythonUtils::LinearColorToPythonString (const FLinearColor & Color)
References Color.
Print()
RIGVMDEVELOPER_API void RigVMPythonUtils::Print (const FString & BlueprintTitle, const FString & InMessage)
PrintPythonContext()
RIGVMDEVELOPER_API void RigVMPythonUtils::PrintPythonContext (const FString & InBlueprintName)
PythonizeName()
RIGVMDEVELOPER_API FString RigVMPythonUtils::PythonizeName (FStringView InName, const EPythonizeNameCase InNameCase = EPythonizeNameCase::Lower)
References InName, and Lower.
TransformToPythonString()
RIGVMDEVELOPER_API FString RigVMPythonUtils::TransformToPythonString (const FTransform & Transform)
References Transform.
Vector2DToPythonString()
RIGVMDEVELOPER_API FString RigVMPythonUtils::Vector2DToPythonString (const FVector2D & Vector)
References Vector.