Unreal Engine 5.6 C++ API: UE::DirectoryTree Namespace Reference
UE::DirectoryTree Namespace Reference
Functions
int32 FindInsertionIndex (int32 NumChildNodes, const TUniquePtr< FString[]> &RelPaths, FStringView FirstPathComponent, bool &bOutExists)
void FixupPathSeparator (FStringBuilderBase &InOutPath, int32 StartIndex, TCHAR InSeparatorChar)
Function Documentation
FindInsertionIndex()
int32 UE::DirectoryTree::FindInsertionIndex (int32 NumChildNodes, const TUniquePtr< FString[]> & RelPaths, FStringView FirstPathComponent, bool & bOutExists)
Referenced by TDirectoryTree< ValueType >::FTreeNode::FindInsertionIndex().
FixupPathSeparator()
void UE::DirectoryTree::FixupPathSeparator (FStringBuilderBase & InOutPath, int32 StartIndex, TCHAR InSeparatorChar)
Referenced by TDirectoryTree< ValueType >::FIteratorInternal::IncrementRemainingChildRelPath(), TDirectoryTree< ValueType >::FIteratorInternal::TraverseToValid(), TDirectoryTree< ValueType >::FTreeNode::TryFindClosestPath(), and TDirectoryTree< ValueType >::FTreeNode::TryGetChildren().