Unreal Engine 5.6 C++ API: AnimationEditorUtils Namespace Reference
AnimationEditorUtils Namespace Reference
Functions
UNREALED_API bool ApplyCompressionAlgorithm (TArray< UAnimSequence * > &AnimSequencePtrs, UAnimBoneCompressionSettings *OverrideSettings)
Applies the animation compression codecs to the sequence list with optional override settings.
template<class T>
T * CreateAnimationAsset (UObject *SkeletonOrSkeletalMesh, const FString &AssetPath, const FString &InPrefix)
UNREALED_API void CreateAnimationAssets (const TArray< TSoftObjectPtr< UObject > > &SkeletonsOrSkeletalMeshes, TSubclassOf< UAnimationAsset > AssetClass, const FString &InPrefix, FAnimAssetCreated AssetCreated, UObject *NameBaseObject=nullptr, bool bDoNotShowNameDialog=false, bool bAllowReplaceExisting=false)
UNREALED_API FAssetData CreateModalAnimationCompressionSelectionDialog (const FAnimationCompressionSelectionDialogConfig &InConfig)
UNREALED_API void CreateNewAnimBlueprint (TArray< TSoftObjectPtr< UObject > > SkeletonsOrSkeletalMeshes, FAnimAssetCreated AssetCreated, bool bInContentBrowser)
UNREALED_API void CreateNewAnimBlueprint (TArray< TWeakObjectPtr< UObject > > SkeletonsOrSkeletalMeshes, FAnimAssetCreated AssetCreated, bool bInContentBrowser)
UNREALED_API void CreateUniqueAssetName (const FString &InBasePackageName, const FString &InSuffix, FString &OutPackageName, FString &OutAssetName)
DECLARE_MULTICAST_DELEGATE_TwoParams (FOnPoseWatchesChanged, UAnimBlueprint *, UEdGraphNode *)
template<typename TFactory, typename T>
void ExecuteNewAnimAsset (TArray< TSoftObjectPtr< UObject > > SkeletonsOrSkeletalMeshes, const FString InSuffix, FAnimAssetCreated AssetCreated, bool bInContentBrowser, bool bAllowReplaceExisting)
UNREALED_API void FillCreateAssetMenu (FMenuBuilder &MenuBuilder, const TArray< TSoftObjectPtr< UObject > > &SkeletonsOrSkeletalMeshes, FAnimAssetCreated AssetCreated, bool bInContentBrowser=true)
UNREALED_API void FindChildGraphsFromNodes (UEdGraph *GraphToSearch, TArray< UEdGraph * > &ChildGraphs)
UNREALED_API UPoseWatch * FindPoseWatchForNode (const UEdGraphNode *Node, UAnimBlueprint *AnimBlueprintIfKnown=nullptr)
int32 GetPoseWatchNodeLinkID (UPoseWatch *PoseWatch, OUT UAnimBlueprintGeneratedClass *&AnimBPGenClass)
UNREALED_API bool IsAnimGraph (UEdGraph *Graph)
UNREALED_API UPoseWatch * MakePoseWatchForNode (UAnimBlueprint *AnimBlueprint, UEdGraphNode *Node)
UNREALED_API FOnPoseWatchesChanged & OnPoseWatchesChanged ()
void RegenerateGraphSubGraphs (UAnimBlueprint *OwningBlueprint, UEdGraph *GraphToFix)
UNREALED_API void RegenerateSubGraphArrays (UAnimBlueprint *Blueprint)
void RemoveDuplicateSubGraphs (UEdGraph *GraphToClean)
UNREALED_API void RemovePoseWatch (UPoseWatch *PoseWatch, UAnimBlueprint *AnimBlueprintIfKnown=nullptr)
UNREALED_API void RemovePoseWatchesFromGraph (UAnimBlueprint *AnimBlueprint, class UEdGraph *Graph)
UNREALED_API void RemovePoseWatchFromNode (UEdGraphNode *Node, UAnimBlueprint *AnimBlueprint)
UNREALED_API void SetPoseWatch (UPoseWatch *PoseWatch, UAnimBlueprint *AnimBlueprintIfKnown=nullptr)
UNREALED_API void SetupDebugLinkedAnimInstances (UAnimBlueprint *InAnimBlueprint, UObject *InRootObjectBeingDebugged)
Function Documentation
ApplyCompressionAlgorithm()
UNREALED_API bool AnimationEditorUtils::ApplyCompressionAlgorithm (TArray< UAnimSequence * > & AnimSequencePtrs, UAnimBoneCompressionSettings * OverrideSettings)
Applies the animation compression codecs to the sequence list with optional override settings.
References ApplyCompressionAlgorithm().
Referenced by ApplyCompressionAlgorithm().
CreateAnimationAsset()
template<class T> T * AnimationEditorUtils::CreateAnimationAsset (UObject * SkeletonOrSkeletalMesh, const FString & AssetPath, const FString & InPrefix)
Definition at line 154 of file AnimationEditorUtils.h.
References Cast(), CastChecked(), CreateAnimationAsset(), CreateUniqueAssetName(), FPackageName::GetLongPackagePath(), FModuleManager::GetModuleChecked(), Name, PackageName, SkeletalMesh, and Skeleton.
Referenced by CreateAnimationAsset().
CreateAnimationAssets()
UNREALED_API void AnimationEditorUtils::CreateAnimationAssets (const TArray< TSoftObjectPtr< UObject > > & SkeletonsOrSkeletalMeshes, TSubclassOf< UAnimationAsset > AssetClass, const FString & InPrefix, FAnimAssetCreated AssetCreated, UObject * NameBaseObject = nullptr, bool bDoNotShowNameDialog = false, bool bAllowReplaceExisting = false)
References CreateAnimationAssets().
Referenced by CreateAnimationAssets(), and ExecuteNewAnimAsset().
CreateModalAnimationCompressionSelectionDialog()
UNREALED_API FAssetData AnimationEditorUtils::CreateModalAnimationCompressionSelectionDialog (const FAnimationCompressionSelectionDialogConfig & InConfig)
References CreateModalAnimationCompressionSelectionDialog().
Referenced by CreateModalAnimationCompressionSelectionDialog().
CreateNewAnimBlueprint() [1/2]
UNREALED_API void AnimationEditorUtils::CreateNewAnimBlueprint (TArray< TSoftObjectPtr< UObject > > SkeletonsOrSkeletalMeshes, FAnimAssetCreated AssetCreated, bool bInContentBrowser)
References CreateNewAnimBlueprint().
CreateNewAnimBlueprint() [2/2]
UNREALED_API void AnimationEditorUtils::CreateNewAnimBlueprint (TArray< TWeakObjectPtr< UObject > > SkeletonsOrSkeletalMeshes, FAnimAssetCreated AssetCreated, bool bInContentBrowser)
References CreateNewAnimBlueprint().
Referenced by CreateNewAnimBlueprint(), and CreateNewAnimBlueprint().
CreateUniqueAssetName()
UNREALED_API void AnimationEditorUtils::CreateUniqueAssetName (const FString & InBasePackageName, const FString & InSuffix, FString & OutPackageName, FString & OutAssetName)
References CreateUniqueAssetName().
Referenced by CreateAnimationAsset(), CreateUniqueAssetName(), and ExecuteNewAnimAsset().
DECLARE_MULTICAST_DELEGATE_TwoParams()
AnimationEditorUtils::DECLARE_MULTICAST_DELEGATE_TwoParams (FOnPoseWatchesChanged , UAnimBlueprint * , UEdGraphNode *)
ExecuteNewAnimAsset()
template<typename TFactory, typename T> void AnimationEditorUtils::ExecuteNewAnimAsset (TArray< TSoftObjectPtr< UObject > > SkeletonsOrSkeletalMeshes, const FString InSuffix, FAnimAssetCreated AssetCreated, bool bInContentBrowser, bool bAllowReplaceExisting)
Definition at line 217 of file AnimationEditorUtils.h.
References TArray< InElementType, InAllocatorType >::Add(), Cast(), CastChecked(), CollectGarbage(), CreateAnimationAssets(), CreateUniqueAssetName(), ExecuteNewAnimAsset(), FindPackage(), GARBAGE_COLLECTION_KEEPFLAGS, FPackageName::GetLongPackagePath(), FModuleManager::LoadModuleChecked(), Name, NewObject, PackageName, Parent, RF_Public, RF_Standalone, SkeletalMesh, and Skeleton.
Referenced by ExecuteNewAnimAsset().
FillCreateAssetMenu()
UNREALED_API void AnimationEditorUtils::FillCreateAssetMenu (FMenuBuilder & MenuBuilder, const TArray< TSoftObjectPtr< UObject > > & SkeletonsOrSkeletalMeshes, FAnimAssetCreated AssetCreated, bool bInContentBrowser = true)
References FillCreateAssetMenu().
Referenced by FillCreateAssetMenu().
FindChildGraphsFromNodes()
UNREALED_API void AnimationEditorUtils::FindChildGraphsFromNodes (UEdGraph * GraphToSearch, TArray< UEdGraph * > & ChildGraphs)
References FindChildGraphsFromNodes().
Referenced by FindChildGraphsFromNodes().
FindPoseWatchForNode()
UNREALED_API UPoseWatch * AnimationEditorUtils::FindPoseWatchForNode (const UEdGraphNode * Node, UAnimBlueprint * AnimBlueprintIfKnown = nullptr)
References FindPoseWatchForNode().
Referenced by FindPoseWatchForNode().
GetPoseWatchNodeLinkID()
int32 AnimationEditorUtils::GetPoseWatchNodeLinkID (UPoseWatch * PoseWatch, OUT UAnimBlueprintGeneratedClass *& AnimBPGenClass)
References GetPoseWatchNodeLinkID(), and OUT.
Referenced by GetPoseWatchNodeLinkID().
IsAnimGraph()
UNREALED_API bool AnimationEditorUtils::IsAnimGraph (UEdGraph * Graph)
References IsAnimGraph().
Referenced by IsAnimGraph().
MakePoseWatchForNode()
UNREALED_API UPoseWatch * AnimationEditorUtils::MakePoseWatchForNode (UAnimBlueprint * AnimBlueprint, UEdGraphNode * Node)
References MakePoseWatchForNode().
Referenced by MakePoseWatchForNode().
OnPoseWatchesChanged()
UNREALED_API FOnPoseWatchesChanged & AnimationEditorUtils::OnPoseWatchesChanged ()
References OnPoseWatchesChanged().
Referenced by OnPoseWatchesChanged().
RegenerateGraphSubGraphs()
void AnimationEditorUtils::RegenerateGraphSubGraphs (UAnimBlueprint * OwningBlueprint, UEdGraph * GraphToFix)
References RegenerateGraphSubGraphs().
Referenced by RegenerateGraphSubGraphs().
RegenerateSubGraphArrays()
UNREALED_API void AnimationEditorUtils::RegenerateSubGraphArrays (UAnimBlueprint * Blueprint)
References RegenerateSubGraphArrays().
Referenced by RegenerateSubGraphArrays().
RemoveDuplicateSubGraphs()
void AnimationEditorUtils::RemoveDuplicateSubGraphs (UEdGraph * GraphToClean)
References RemoveDuplicateSubGraphs().
Referenced by RemoveDuplicateSubGraphs().
RemovePoseWatch()
UNREALED_API void AnimationEditorUtils::RemovePoseWatch (UPoseWatch * PoseWatch, UAnimBlueprint * AnimBlueprintIfKnown = nullptr)
References RemovePoseWatch().
Referenced by RemovePoseWatch().
RemovePoseWatchesFromGraph()
UNREALED_API void AnimationEditorUtils::RemovePoseWatchesFromGraph (UAnimBlueprint * AnimBlueprint, class UEdGraph * Graph)
References RemovePoseWatchesFromGraph().
Referenced by RemovePoseWatchesFromGraph().
RemovePoseWatchFromNode()
UNREALED_API void AnimationEditorUtils::RemovePoseWatchFromNode (UEdGraphNode * Node, UAnimBlueprint * AnimBlueprint)
References RemovePoseWatchFromNode().
Referenced by RemovePoseWatchFromNode().
SetPoseWatch()
UNREALED_API void AnimationEditorUtils::SetPoseWatch (UPoseWatch * PoseWatch, UAnimBlueprint * AnimBlueprintIfKnown = nullptr)
References SetPoseWatch().
Referenced by SetPoseWatch().
SetupDebugLinkedAnimInstances()
UNREALED_API void AnimationEditorUtils::SetupDebugLinkedAnimInstances (UAnimBlueprint * InAnimBlueprint, UObject * InRootObjectBeingDebugged)
References SetupDebugLinkedAnimInstances().
Referenced by SetupDebugLinkedAnimInstances().