Unreal Engine 5.6 C++ API: UETypeName_Private Namespace Reference
UETypeName_Private Namespace Reference
Data Structures
struct FSubstr
struct TCharArray
Functions
template<typename T>
constexpr FSubstr GetTypeSubstr ()
template<typename T, uint32... Indices>
constexpr TCharArray< sizeof...(Indices)> TypeSubstrToCharArray (TIntegerSequence< uint32, Indices... >)
Function Documentation
GetTypeSubstr()
template<typename T> FSubstr UETypeName_Private::GetTypeSubstr () constexpr
Definition at line 74 of file GeneratedTypeName.h.
References UETypeName_Private::FSubstr::PopBack(), UETypeName_Private::FSubstr::PopBackAll(), UETypeName_Private::FSubstr::PopBackAllNot(), UETypeName_Private::FSubstr::PopFront(), UETypeName_Private::FSubstr::PopFrontAll(), UETypeName_Private::FSubstr::PopFrontAllNot(), SIG, SIG_ENDCHAR, and SIG_STARTCHAR.
Referenced by GetGeneratedTypeName(), and TypeSubstrToCharArray().
TypeSubstrToCharArray()
template<typename T, uint32... Indices> TCharArray< sizeof...(Indices)> UETypeName_Private::TypeSubstrToCharArray (TIntegerSequence< uint32, Indices... >) constexpr
Definition at line 92 of file GeneratedTypeName.h.
References GetTypeSubstr().
Referenced by GetGeneratedTypeName().