Unreal Engine 5.6 C++ API: Metasound Namespace Reference
Metasound Namespace Reference
standard Midi Controller ID according to the MIDI Association reference: https://www.midi.org/specifications-old/item/table-3-control-change-messages-data-bytes-2
Namespaces
namespace ArrayNodeRandomGetVertexNames
namespace ArrayNodeShuffleVertexNames
Shuffle Node Vertex Names.
namespace ArrayNodeVertexNames
namespace AutoConverterNodePrivate
namespace CoreInterface
namespace DataFactoryPrivate
namespace DirectedGraphAlgo
namespace DynamicGraph
namespace Frontend
namespace LiteralNodeNames
namespace MetasoundArrayNodesPrivate
namespace MetasoundEnvironmentPrivate
namespace MetasoundExecutableOperatorPrivate
namespace MetasoundFacadePrivate
namespace MetasoundInputNodePrivate
namespace MetasoundLiteralIntrinsics
namespace MetasoundTransmissionPrivate
namespace MetasoundVariableNodesPrivate
namespace MetasoundVariablePrivate
namespace NodeCategories
namespace OperatorBuilder
namespace OperatorDataPrivate
namespace OutputNodePrivate
namespace ReceiveNodeInfo
namespace ReceiveNodePrivate
namespace SendNodePrivate
namespace SendVertexNames
namespace VariableNames
namespace VertexDataPrivate
namespace VertexPrivate
Data Structures
struct TDataReferenceTypeInfo< FMetasoundParameterStorageWrapper >
struct TDataReferenceTypeInfo< FMidiEventInfo >
struct TDataReferenceTypeInfo< FMusicLoopConfiguration >
struct TDataReferenceTypeInfo< FMusicSeekRequest >
struct TDataReferenceTypeInfo< FMusicSeekTarget >
struct TDataReferenceTypeInfo< FMusicTimestamp >
struct TDataReferenceTypeInfo< HarmonixMetasound::Analysis::FMidiClockSongPosition >
struct TDataReferenceTypeInfo< HarmonixMetasound::FFusionPatchAsset >
struct TDataReferenceTypeInfo< HarmonixMetasound::FMidiAsset >
struct TDataReferenceTypeInfo< HarmonixMetasound::FMidiClock >
struct TDataReferenceTypeInfo< HarmonixMetasound::FMidiStepSequenceAsset >
struct TDataReferenceTypeInfo< HarmonixMetasound::FMidiStream >
struct TDataReferenceTypeInfo< HarmonixMetasound::FMusicTransportEvent >
struct TDataReferenceTypeInfo< HarmonixMetasound::FMusicTransportEventStream >
struct TDataReferenceTypeInfo< TArray< FMetasoundParameterStorageWrapper > >
struct TDataReferenceTypeInfo< TArray< FMidiEventInfo > >
struct TDataReferenceTypeInfo< TArray< FMusicLoopConfiguration > >
struct TDataReferenceTypeInfo< TArray< FMusicSeekRequest > >
struct TDataReferenceTypeInfo< TArray< FMusicSeekTarget > >
struct TDataReferenceTypeInfo< TArray< FMusicTimestamp > >
struct TDataReferenceTypeInfo< TArray< HarmonixMetasound::Analysis::FMidiClockSongPosition > >
struct TDataReferenceTypeInfo< TArray< HarmonixMetasound::FFusionPatchAsset > >
struct TDataReferenceTypeInfo< TArray< HarmonixMetasound::FMidiAsset > >
struct TDataReferenceTypeInfo< TArray< HarmonixMetasound::FMidiClock > >
struct TDataReferenceTypeInfo< TArray< HarmonixMetasound::FMidiStepSequenceAsset > >
struct TDataReferenceTypeInfo< TArray< HarmonixMetasound::FMidiStream > >
struct TDataReferenceTypeInfo< TArray< HarmonixMetasound::FMusicTransportEvent > >
struct TDataReferenceTypeInfo< TArray< HarmonixMetasound::FMusicTransportEventStream > >
struct TDataReferenceTypeInfo<::Metasound::TVariable< FMetasoundParameterStorageWrapper > >
struct TDataReferenceTypeInfo<::Metasound::TVariable< FMidiEventInfo > >
struct TDataReferenceTypeInfo<::Metasound::TVariable< FMusicLoopConfiguration > >
struct TDataReferenceTypeInfo<::Metasound::TVariable< FMusicSeekRequest > >
struct TDataReferenceTypeInfo<::Metasound::TVariable< FMusicSeekTarget > >
struct TDataReferenceTypeInfo<::Metasound::TVariable< FMusicTimestamp > >
struct TDataReferenceTypeInfo<::Metasound::TVariable< HarmonixMetasound::Analysis::FMidiClockSongPosition > >
struct TDataReferenceTypeInfo<::Metasound::TVariable< HarmonixMetasound::FFusionPatchAsset > >
struct TDataReferenceTypeInfo<::Metasound::TVariable< HarmonixMetasound::FMidiAsset > >
struct TDataReferenceTypeInfo<::Metasound::TVariable< HarmonixMetasound::FMidiClock > >
struct TDataReferenceTypeInfo<::Metasound::TVariable< HarmonixMetasound::FMidiStepSequenceAsset > >
struct TDataReferenceTypeInfo<::Metasound::TVariable< HarmonixMetasound::FMidiStream > >
struct TDataReferenceTypeInfo<::Metasound::TVariable< HarmonixMetasound::FMusicTransportEvent > >
struct TDataReferenceTypeInfo<::Metasound::TVariable< HarmonixMetasound::FMusicTransportEventStream > >
struct TDataReferenceTypeInfo<::Metasound::TVariable< TArray< FMetasoundParameterStorageWrapper > > >
struct TDataReferenceTypeInfo<::Metasound::TVariable< TArray< FMidiEventInfo > > >
struct TDataReferenceTypeInfo<::Metasound::TVariable< TArray< FMusicLoopConfiguration > > >
struct TDataReferenceTypeInfo<::Metasound::TVariable< TArray< FMusicSeekRequest > > >
struct TDataReferenceTypeInfo<::Metasound::TVariable< TArray< FMusicSeekTarget > > >
struct TDataReferenceTypeInfo<::Metasound::TVariable< TArray< FMusicTimestamp > > >
struct TDataReferenceTypeInfo<::Metasound::TVariable< TArray< HarmonixMetasound::Analysis::FMidiClockSongPosition > > >
struct TDataReferenceTypeInfo<::Metasound::TVariable< TArray< HarmonixMetasound::FFusionPatchAsset > > >
struct TDataReferenceTypeInfo<::Metasound::TVariable< TArray< HarmonixMetasound::FMidiAsset > > >
struct TDataReferenceTypeInfo<::Metasound::TVariable< TArray< HarmonixMetasound::FMidiClock > > >
struct TDataReferenceTypeInfo<::Metasound::TVariable< TArray< HarmonixMetasound::FMidiStepSequenceAsset > > >
struct TDataReferenceTypeInfo<::Metasound::TVariable< TArray< HarmonixMetasound::FMidiStream > > >
struct TDataReferenceTypeInfo<::Metasound::TVariable< TArray< HarmonixMetasound::FMusicTransportEvent > > >
struct TDataReferenceTypeInfo<::Metasound::TVariable< TArray< HarmonixMetasound::FMusicTransportEventStream > > >
class FAddressRouter
class FAnyDataReference
Container for any data reference.
class FArrayIndexShuffler
class FArrayRandomGet
class FAudioBuffer
FAudioBuffer.
class FBasicNode
struct FBeginSubInterface
struct FBuildDynamicGraphOperatorParams
class FBuildErrorBase
FBuildErrorBase.
struct FBuildGraphOperatorParams
Parameters for building an operator from a graph.
struct FBuildGraphParams
Parameters for building an operator from a graph.
struct FBuildOperatorParams
FBuildOperatorParams holds the parameters provided to operator factories during the creation of an IOperator.
struct FBuildResults
Structure of all resulting data generated during graph operator build.
class FClassVertexInterface
class FDanglingVertexError
FDanglingVertexError.
struct FDataEdge
FDataEdge.
class FDataReferenceCollection
class FDataTransmissionCenter
class FDataVertex
FDataVertex.
struct FDataVertexMetadata
struct FDefaultLiteralNodeConstructorParams
struct FDefaultNamedVertexNodeConstructorParams
struct FDefaultNamedVertexWithLiteralNodeConstructorParams
struct FDirectedGraphAlgo
class FDuplicateInputError
FDuplicateInputError.
struct FEndSubInterface
class FEnvironmentVertex
FEnvironmentVertex.
class FEnvironmentVertexInterface
Interface representing the environment variables used by a node.
class FExecuter
FExecuter.
class FFilterClassesByClassID
class FFilterClassesByInputVertexDataType
class FFilterClassesByOutputVertexDataType
class FFrontendGraph
FFrontendGraph is a utility graph for use in the frontend.
class FFrontendQuery
FFrontendQuery contains a set of query steps which produce a FFrontendQuerySelectionView.
struct FFrontendQueryEntry
FFrontendQueryEntry represents one value in the query.
struct FFrontendQueryKey
FFrontendQueryKey allows entries to be partitioned by their key.
class FFrontendQueryStep
FFrontendQueryStep wraps all the support IFrontenQueryStep interfaces and supplies unified ExecuteStep(...) member function.
class FGraph
FGraph contains the edges between nodes as well as input and output vertices.
class FGraphBuilder
FGraphBuilder builds a FFrontendGraph from a FMetasoundDocument or FMetasoundFrontendClass.
class FGraphCycleError
FGraphCycleError.
class FGraphLinter
FGraphLinter.
class FGraphOperator
class FGraphRenderCost
FGraphRenderCost represents the accumulated render cost of a graph.
struct FInputDataDestination
FInputDataSource describes the destination of data which produced external to the graph and read internal to the graph.
class FInputDataVertex
FInputDataVertex.
class FInputNode
FInputNode represents an input to a metasound graph.
struct FInputNodeConstructorParams
class FInputReceiverInitializationError
FInputReceiverInitializationError.
class FInputVertexInterface
Interface representing the inputs of a node.
class FInputVertexInterfaceData
An input vertex interface with optionally bound data references.
class FInternalError
FInternalError.
class FInvalidConnectionDataTypeError
FInvalidConnectionDataTypeError.
struct FLiteral
FLiteral represents a constant value in a Metasound graph and is primarily used to invoke the correct constructor of a Metasound data type.
class FLiteralNode
TLiteralNode represents a variable within a metasound graph.
class FMapClassesToClassName
class FMapRegistrationEventsToNodeRegistryKeys
Partitions node registration events by their node registration keys.
class FMapToFullClassName
class FMapToNull
class FMetasoundEnvironment
FMetasoundEnvironment contains a set of TMetasoundEnvironmentVariables requiring that each environment variable has a unique name.
class FMetaSoundParameterTransmitter
FMetaSoundParameterTransmitter provides a communication interface for sending values to a MetaSound instance.
class FMissingInputDataReferenceError
FMissingInputDataReferenceError.
class FMissingOutputDataReferenceError
FMissingOutputDataReferenceError.
class FMissingOutputNodeInputReferenceError
FMissingOutputNodeInputReferenceError.
class FMissingVertexError
FMissingVertexError.
class FNode
struct FNodeClassMetadata
Provides metadata for a given node.
class FNodeClassName
Name of a node class.
class FNodeClassRegistrationEvents
Streams node classes that have been newly registered or unregistered since last call to Stream()
struct FNodeData
Data used to construct a Node.
struct FNodeDisplayStyle
Node style data.
class FNodeFacade
FNodeFacade implements a significant amount of boilerplate code required to build a Metasound INode.
struct FNodeInitData
This struct is used to pass in any arguments required for constructing a single node instance.
class FNodePrunedError
FNodePrunedError.
class FNodeRenderCost
FNodeRenderCost allows individual nodes to report their render cost.
class FNoOpOperator
FNoOpOperator is for IOperators which do not perform any execution.
struct FOperatorAndInputs
class FOperatorBuilder
FOperatorBuilder builds an IOperator from an IGraph.
struct FOperatorBuilderSettings
FOperatorBuilderSettings.
class FOperatorSettings
FOperatorSettings.
struct FOutputDataSource
FOutputDataSource describes the source of data which is produced within a graph and exposed external to the graph.
class FOutputDataVertex
FOutputDataVertex.
class FOutputNode
class FOutputVertexInterface
Interface representing the outputs of a node.
class FOutputVertexInterfaceData
An output vertex interface with optionally bound data references.
struct FReceiverInitParams
class FReduceClassesToHighestVersion
class FReduceRegistrationEventsToCurrentStatus
Reduces registration events mapped to the same key by inspecting their add/remove state in order to determine their final state.
class FSendAddress
FSendAddress is used as a addressing system for MetaSound Send nodes, Recieve nodes and MetaSound script communication.
struct FSenderInitParams
class FSharedStateRandomGetManager
class FSharedStateShuffleManager
class FSortClassesByVersion
struct FStronglyConnectedComponent
A strongly connected component containing Metasound INodes and FDataEdges.
struct FSubInterfaceConfiguration
struct FSubInterfaceDescription
class FTime
class FTransformRegistrationEventsToClasses
Transforms a registration event into a FMetasoundFrontendClass.
class FTransmissionAddress
A FTranmissionAddress acts as a identifier for a data channel shared by one or more senders and or receivers.
struct FTransmissionDataChannelFactory
class FTrigger
FTrigger supports sample accurate triggering, sample accurate internal tracking, and a convenient interface for running trigger-aligned audio signal processing routines on buffers.
struct FVertexDataState
FVertexDataState encapsulates which data reference a vertex is associated with.
class FVertexInterface
FVertexInterface provides access to a collection of input and output vertex interfaces.
class FVertexInterfaceData
A vertex interface with optionally bound data.
class IAudioDataType
class IDataChannel
class IDataReference
A Data Reference Interface.
class IDataTransmissionBase
class IFrontendQueryFilterStep
Interface for a query step which filters entries.
class IFrontendQueryLimitStep
class IFrontendQueryMapStep
Interface for a query step which maps entries to keys.
class IFrontendQueryMultiMapStep
Interface for a query step which maps entries to multiple keys.
class IFrontendQueryReduceStep
Interface for a query step which reduces entries with the same key.
class IFrontendQueryScoreStep
Interface for a query step which scores entries.
class IFrontendQuerySortStep
Interface for a query step which sorts entries.
class IFrontendQueryStep
Interface for an individual step in a query.
class IFrontendQueryStreamStep
Interface for a query step which streams new entries.
class IFrontendQueryTransformStep
Interface for a query step which transforms an entry's value.
class IGraph
Interface for graph of nodes.
class IMetasoundEnvironmentVariable
Interface for a metasound environment variable which supports a name, a runtime type ID, and a clone method.
class IMetasoundGraphCoreModule
struct InitSharedStateArgs
class INode
INode.
class INodeBase
INodeBase.
class IOperator
IOperator.
class IOperatorBuilder
IOperatorBuilder.
class IOperatorBuildError
IOperatorBuildError.
class IOperatorData
Base class for node configurations.
class IOperatorFactory
IOperatorFactory.
class IOutputStorage
class IReceiver
class ISender
class TArrayConcatOperator
TArrayConcatOperator concatenates two arrays on trigger.
class TArrayGetOperator
TArrayGetOperator copies a value from the array to the output when a trigger occurs.
class TArrayLastIndexOperator
TArrayLastIndex gets last index of an array.
class TArrayNumOperator
TArrayNumOperator gets the number of elements in an Array.
class TArrayRandomGetOperator
class TArraySetOperator
TArraySetOperator sets an element in an array to a specific value.
class TArrayShuffleOperator
TArrayShuffleOperator shuffles an array on trigger and outputs values sequentially on "next".
class TArraySubsetOperator
TArraySubsetOperator slices an array on trigger.
class TAudioDataChannel
class TAudioReceiver
class TAudioSender
class TAutoConverterNode
class TCopyableDataChannel
struct TDataFactory
A base factory type for creating objects related to Metasound DataTypes.
struct TDataLiteralFactory
A base factory type for creating objects related to Metasound DataTypes.
class TDataReadReference
TDataReadReference provides read access to a shared parameter reference.
struct TDataReadReferenceFactory
TDataReadReferenceFactory creates TDataReadReferences for the given DataType.
struct TDataReadReferenceLiteralFactory
TDataReadReferenceLiteralFactory creates TDataReadReferences for the given DataType.
class TDataReference
Template class for a paramter reference.
struct TDataReferenceTypeInfo
Info for templated data reference types help perform runtime type verification.
struct TDataReferenceTypeInfo< void >
Specialize void data type for internal use.
struct TDataTypeFactory
TDataTypeFactory creates a DataType.
struct TDataTypeLiteralFactory
TDataTypeLiteralFactory creates a DataType.
class TDataValueReference
TDataValueReference represents a constant value and provides read only access.
struct TDataValueReferenceFactory
TDataValueReferenceFactory creates TDataValueReferences for the given DataType.
struct TDataValueReferenceLiteralFactory
TDataValueReferenceLiteralFactory creates TDataValueReferences for the given DataType.
class TDataWriteReference
TDataWriteReference provides write access to a shared parameter reference.
struct TDataWriteReferenceFactory
TDataWriteReferenceFactory creates TDataWriteReferences for the given DataType.
struct TDataWriteReferenceLiteralFactory
TDataWriteReferenceLiteralFactory creates TDataWriteReferences for the given DataType.
struct TEnableArrayNodes
struct TEnableArrayNodes< TEnum< EnumType, DefaultValue > >
struct TEnableAutoArrayTypeRegistration
Enables or disables automatic registration of array types given a MetaSound data type.
struct TEnableAutoArrayTypeRegistration< TEnum< EnumType, DefaultValue > >
struct TEnableAutoConverterNodeRegistration
Enables or disables automatic registration of auto conversion nodes given a MetaSound data type.
struct TEnableAutoConverterNodeRegistration< FromDataType, TEnum< EnumType, DefaultValue > >
struct TEnableAutoConverterNodeRegistration< TEnum< EnumType, DefaultValue >, ToDataType >
struct TEnableConstructorVertex
Enables or disables using a data type in constructor vertices.
struct TEnableTransmissionNodeRegistration
Enables or disables send and receive node registration for a given MetaSound data type.
struct TEnableTransmissionNodeRegistration< TArray< ElementType > >
struct TEnableTransmissionNodeRegistration< TEnum< EnumType, DefaultValue > >
class TEnum
Metasound Enum Wrapper.
struct TEnumEntry
struct TEnumStringHelper
Metasound Enum String Helper.
struct TEnumStringHelperBase
CRTP base class for Enum String Helper type.
struct TEnumTraits
struct TEnumTraits< TEnum< T, D > >
struct TEnvironmentVariableTypeInfo
struct TExecutableDataType
class TExecutableOperator
Convenience class for supporting the IOperator interface's GetExecuteFunction virtual member function.
struct TFacadeOperatorClass
TFacadeOperatorClass encapsulates an operator type and checks that the required static functions exist to build the facade operator class.
class TInputConstructorVertex
Create a FInputDataVertex with a templated MetaSound data type which only reads data at operator time.
class TInputDataVertex
Create a FInputDataVertex with a templated MetaSound data type.
class TInputNode
TInputNode represents an input to a metasound graph.
struct TIsArrayType
struct TIsArrayType< TArray< DataElementType > >
struct TIsAutoConvertible
struct TIsConstructorVertexSupported
struct TIsCopyable
class TIsCreateNodeClassMetadataDeclared
struct TIsExplicit
struct TIsNodeConstructorSupported
Determines whether the constructor provided by the node is usable in node registration.
struct TIsOnlyDeprecatedNodeConstructorProvided
Determines a node only provides a deprecated constructor.
struct TIsParsable
Determines whether a DataType supports a constructor which accepts and FOperatorSettings with ArgTypes and/or just ArgTypes.
struct TIsParsable< DataType, FLiteral::FNone >
struct TIsParsable< TArray< DataElementType >, TArray< FLiteral::FNone > >
struct TIsTransmittable
struct TIsVariable
Template to determine if data type is a variable.
struct TIsVariable< TVariable< UnderlyingDataType > >
Template specialization to determine if data type is a variable.
class TLiteralNode
TLiteralNode represents a variable within a metasound graph.
class TLiteralOperatorLiteralFactory
TExecutableLiteralOperator is used for executable types.
struct TLiteralTraits
Determines whether a DataType supports construction using the given literal.
struct TLiteralTypeInfo
Provides literal type information for a given type.
struct TLiteralTypeInfo< ArgType >
struct TLiteralTypeInfo<>
Provides literal type information for a given type.
struct TMetasoundDataTypeRegistration
Registration info for a data type.
class TMetasoundEnvironmentVariable
class TNodeFacade
TNodeFacade further reduces boilerplate code by allowing shorthand node implementations.
class TNonOperationalDataChannel
class TNonOperationalReceiver
class TNonOperationalSender
class TOperatorData
Node configuration CRTP.
class TOutputConstructorVertex
Create a FOutputDataVertex with a templated MetaSound data type which is only sets data at operator construction time.
class TOutputDataVertex
Create a FOutputDataVertex with a templated MetaSound data type.
class TOutputNode
Output nodes are used to expose graph data to external entities.
class TOutputStorage
class TParamPackFixedArray
struct TPostExecutableDataType
struct TPostExecutableDataType< FTrigger >
class TReceiveNode
class TReceiver
class TSender
class TSendNode
struct TSpecializationHelper
Helper class to enforce specialization of TDataReferenceTypeInfo.
struct TVariable
A MetaSound Variable contains a data reference's prior and current value.
class TVariableNode
Variable nodes initialize variable values.
class TVertexInterfaceGroupData
class TVertexInterfaceImpl
TVertexInterfaceImpls encapsulates multiple related data vertices.
Typedefs
typedef FManagedArrayCollection DataType
typedef ::Metasound::TDataReadReference< FAudioBuffer > FAudioBufferReadRef
typedef ::Metasound::TDataReferenceTypeInfo< FAudioBuffer > FAudioBufferTypeInfo
typedef ::Metasound::TDataWriteReference< FAudioBuffer > FAudioBufferWriteRef
using FBuildErrorArray = TArray<TUniquePtr<IOperatorBuildError>>
Array of build errors.
using FDataReferenceID = const void*
using FEnumDelayFilterType = Metasound::TEnum<EDelayFilterType, EDelayFilterType::LowPass>
typedef ::Metasound::TDataReferenceTypeInfo< FEnumDelayFilterType > FEnumDelayFilterTypeInfo
typedef ::Metasound::TDataReadReference< FEnumDelayFilterType > FEnumDelayFilterTypeReadReference
typedef ::Metasound::TDataWriteReference< FEnumDelayFilterType > FEnumDelayFilterTypeWriteReference
using FEnumDelayStereoType = Metasound::TEnum<EDelayStereoType, EDelayStereoType::Default>
typedef ::Metasound::TDataReferenceTypeInfo< FEnumDelayStereoType > FEnumDelayStereoTypeInfo
typedef ::Metasound::TDataReadReference< FEnumDelayStereoType > FEnumDelayStereoTypeReadReference
typedef ::Metasound::TDataWriteReference< FEnumDelayStereoType > FEnumDelayStereoTypeWriteReference
typedef ::Metasound::TDataReadReference< FEnumMidiClockSubdivisionQuantizationType > FEnumMidiClockSubdivisionQuantizationReadRef
using FEnumMidiClockSubdivisionQuantizationType = Metasound::TEnum<EMidiClockSubdivisionQuantization, EMidiClockSubdivisionQuantization::None>
typedef ::Metasound::TDataReferenceTypeInfo< FEnumMidiClockSubdivisionQuantizationType > FEnumMidiClockSubdivisionQuantizationTypeInfo
typedef ::Metasound::TDataWriteReference< FEnumMidiClockSubdivisionQuantizationType > FEnumMidiClockSubdivisionQuantizationWriteRef
using FEnumSharedStateBehaviorType = Metasound::TEnum<ESharedStateBehaviorType, ESharedStateBehaviorType::SameNodeInComposition>
typedef ::Metasound::TDataReferenceTypeInfo< FEnumSharedStateBehaviorType > FEnumSharedStateBehaviorTypeInfo
typedef ::Metasound::TDataReadReference< FEnumSharedStateBehaviorType > FEnumSharedStateBehaviorTypeReadRef
using FEnumStdMidiControllerID = Metasound::TEnum<EStdMidiControllerID, EStdMidiControllerID::BankSelection>
typedef ::Metasound::TDataReadReference< FEnumStdMidiControllerID > FEnumStdMidiControllerIDReadRef
typedef ::Metasound::TDataReferenceTypeInfo< FEnumStdMidiControllerID > FEnumStdMidiControllerIDTypeInfo
typedef ::Metasound::TDataWriteReference< FEnumStdMidiControllerID > FEnumStdMidiControllerIDWriteRef
using FEnumTimeSyncOption = Metasound::TEnum<ETimeSyncOption, ETimeSyncOption::None>
typedef ::Metasound::TDataReferenceTypeInfo< FEnumTimeSyncOption > FEnumTimeSyncOptionInfo
typedef ::Metasound::TDataReadReference< FEnumTimeSyncOption > FEnumTimeSyncOptionReadReference
typedef ::Metasound::TDataWriteReference< FEnumTimeSyncOption > FEnumTimeSyncOptionWriteReference
using FFrontendQueryPartition = TArray<FFrontendQueryEntry, TInlineAllocator<1>>
A FFrontendQueryPartition represents a set of entries associated with a single FFrontendQueryKey.
using FFrontendQuerySelection = TSortedMap<FFrontendQueryKey, FFrontendQueryPartition>
A FFrontendQuerySelection holds a map of keys to partitions.
using FFrontendQueryValue = TVariant<FMetasoundFrontendVersion, Frontend::FNodeRegistryTransaction, FMetasoundFrontendClass, Frontend::FInterfaceRegistryTransaction, FMetasoundFrontendInterface>
A FFrontendQueryValue contains data of interest.
typedef TMap< FNodeDataVertexKey, FInputDataDestination > FInputDataDestinationCollection
FInputDataDestinationCollection contains multiple FInputDataDestinations mapped by FNodeDataVertexKeys.
using FIterateMetasoundFrontendClassFunction
using FLiteralNodeConstructorParams = FDefaultLiteralNodeConstructorParams
typedef TTuple< const INode *, FVertexName > FNodeDataVertexKey
Key type for an FOutputDataSource or FInputDataDestination.
typedef TSharedRef< IOperatorFactory, ESPMode::ThreadSafe > FOperatorFactorySharedRef
Shared ref type of operator factory.
typedef TMap< FNodeDataVertexKey, FOutputDataSource > FOutputDataSourceCollection
FOutputDataSourceCollection contains multiple FOutputDataSources mapped by FNodeDataVertexKeys.
using FOutputNodeConstructorParams = FDefaultNamedVertexNodeConstructorParams
using FSampleRate = int32
typedef ::Metasound::TDataWriteReference< FEnumSharedStateBehaviorType > FSharedStateBehaviorTypeWriteRef
using FVariableNodeConstructorParams = FDefaultLiteralNodeConstructorParams
using FVertexName = FName
Name of a given vertex.
template<typename ArrayType>
using TArrayConcatNode = TNodeFacade<TArrayConcatOperator<ArrayType>>
template<typename ArrayType>
using TArrayGetNode = TNodeFacade<TArrayGetOperator<ArrayType>>
template<typename ArrayType>
using TArrayLastIndexNode = TNodeFacade<TArrayLastIndexOperator<ArrayType>>
template<typename ArrayType>
using TArrayNumNode = TNodeFacade<TArrayNumOperator<ArrayType>>
template<typename ArrayType>
using TArrayRandomGetNode = TNodeFacade<TArrayRandomGetOperator<ArrayType>>
template<typename ArrayType>
using TArraySetNode = TNodeFacade<TArraySetOperator<ArrayType>>
template<typename ArrayType>
using TArrayShuffleNode = TNodeFacade<TArrayShuffleOperator<ArrayType>>
template<typename ArrayType>
using TArraySubsetNode = TNodeFacade<TArraySubsetOperator<ArrayType>>
template<typename DataType, EVertexAccessType VertexAccess = EVertexAccessType::Reference>
using TInputOperator
Owning input operator that may need execution.
template<typename DataType, EVertexAccessType VertexAccess = EVertexAccessType::Reference>
using TPassThroughOperator
Choose pass through operator based upon data type and access type.
template<typename TDataType, typename UReceiverType = typename std::conditional<TIsDerivedFrom<TDataType, IAudioDataType>::Value, TAudioReceiver<TDataType>, TReceiver<TDataType>>::type>
using TReceiverPtr = TUniquePtr<UReceiverType>
template<typename TDataType, typename USenderType = typename std::conditional<TIsDerivedFrom<TDataType, IAudioDataType>::Value, TAudioSender<TDataType>, TSender<TDataType>>::type>
using TSenderPtr = TUniquePtr<USenderType>
template<typename ValueType>
using TSortedVertexNameMap = TSortedMap<FVertexName, ValueType, FDefaultAllocator, FNameFastLess>
Convenience for using a TSortedMap with FVertexName Key type.
template<typename DataType>
using TVariableAccessorNode = TNodeFacade<MetasoundVariableNodesPrivate::TVariableAccessorOperator<DataType>>
FGetVariable node provides delay free, cpu free access to a set variable.
template<typename DataType>
using TVariableDeferredAccessorNode = TNodeFacade<MetasoundVariableNodesPrivate::TVariableDeferredAccessorOperator<DataType>>
TVariableDeferredAccessorNode provides access to the prior executions variable value.
template<typename DataType>
using TVariableMutatorNode = TNodeFacade<MetasoundVariableNodesPrivate::TVariableMutatorOperator<DataType>>
TVariableMutatorNode allows variable values to be set.
Enumerations
enum class EDataReferenceAccessType : uint8 { None = 0x00 , Read = 0x01 , Write = 0x02 , Value = 0x04 }
EDataReferenceAccessType describes the underlying data reference access type for a data reference contained in a FAnyDataReference.
enum class EDataRefShouldConstruct { NewObject }
enum class ELiteralType : uint8 {
None , Boolean , Integer , Float ,
String , UObjectProxy , NoneArray , BooleanArray ,
IntegerArray , FloatArray , StringArray , UObjectProxyArray ,
Invalid , COUNT
}
ELiteralType describes the format of the values held in the literal.
enum class EOperatorBuilderNodePruning : uint8 { None , PruneNodesWithoutOutputDependency , PruneNodesWithoutInputDependency , PruneNodesWithoutExternalDependency }
EOperatorBuildNodePruning expresses the desired pruning behavior during the node pruning step.
enum class ESharedStateBehaviorType : int32 { SameNode , SameNodeInComposition , SameData }
enum class EVertexAccessType { Reference , Value }
Describe how the vertex will access connected data.
Functions
template<typename ErrorType, typename... ArgTypes>
void AddBuildError (FBuildErrorArray &OutErrors, ArgTypes &&... Args)
Convenience template for adding build errors.
METASOUNDGRAPHCORE_API bool CanEverExecuteGraph (bool bIsCooking=false)
template<typename DerivedAddressType>
const DerivedAddressType * CastAddressType (const FTransmissionAddress &InOther)
Attempt to cast a FTransmissionAddress to a derived address type.
template<typename Type>
const TMetasoundEnvironmentVariable< Type > & CastMetasoundEnvironmentVariableChecked (const IMetasoundEnvironmentVariable &InVar)
Casts an environment variable to the derived type.
template<typename Type>
TMetasoundEnvironmentVariable< Type > & CastMetasoundEnvironmentVariableChecked (IMetasoundEnvironmentVariable &InVar)
Casts an environment variable to the derived type.
template<typename DesiredOperatorDataType, typename ProvidedOperatorDataType>
std::enable_if_t< std::conjunction_v< std::is_base_of< TOperatorData< std::decay_t< DesiredOperatorDataType > >, DesiredOperatorDataType >, std::is_base_of< IOperatorData, ProvidedOperatorDataType > >, DesiredOperatorDataType * > CastOperatorData (ProvidedOperatorDataType *InOperatorData)
Returns a non-null pointer to a downcast node configuration object if the provided node configuration is non-null and of the same derived type.
METASOUNDGRAPHCORE_API void CompareVertexInterfaceDataToPriorState (const FInputVertexInterfaceData &InCurrentInterface, const TArray< FVertexDataState > &InPriorState, TSortedVertexNameMap< FAnyDataReference > &OutUpdates)
Compares the current data bound to the vertex interface with a prior cached state.
METASOUNDGRAPHCORE_API void CompareVertexInterfaceDataToPriorState (const FOutputVertexInterfaceData &InCurrentInterface, const TArray< FVertexDataState > &InPriorState, TSortedVertexNameMap< FAnyDataReference > &OutUpdates)
Compares the current data bound to the vertex interface with a prior cached state.
METASOUNDGRAPHCORE_API FName CreateArrayTypeNameFromElementTypeName (const FName InTypeName)
Returns array type associated with the base datatype provided(ex.
METASOUNDGRAPHCORE_API FName CreateElementTypeNameFromArrayTypeName (const FName InArrayTypeName)
Returns the base data type with the array extension(ex.
DECLARE_METASOUND_DATA_REFERENCE_TYPES (bool, METASOUNDFRONTEND_API, FBoolTypeInfo, FBoolReadRef, FBoolWriteRef)
DECLARE_METASOUND_DATA_REFERENCE_TYPES (float, METASOUNDFRONTEND_API, FFloatTypeInfo, FFloatReadRef, FFloatWriteRef)
DECLARE_METASOUND_DATA_REFERENCE_TYPES (FString, METASOUNDFRONTEND_API, FStringTypeInfo, FStringReadRef, FStringWriteRef)
DECLARE_METASOUND_DATA_REFERENCE_TYPES (FTime, METASOUNDFRONTEND_API, FTimeTypeInfo, FTimeReadRef, FTimeWriteRef)
DECLARE_METASOUND_DATA_REFERENCE_TYPES (FTrigger, METASOUNDFRONTEND_API, FTriggerTypeInfo, FTriggerReadRef, FTriggerWriteRef)
DECLARE_METASOUND_DATA_REFERENCE_TYPES (int32, METASOUNDFRONTEND_API, FInt32TypeInfo, FInt32ReadRef, FInt32WriteRef)
template<typename TDataType, typename TEnableIf< TIsDerivedFrom< TDataType, IAudioDataType >::Value, bool >::Type = true>
TReceiverPtr< TDataType > Downcast (TUniquePtr< IReceiver > &&InPtr)
template<typename TDataType, typename TEnableIf< TIsDerivedFrom< TDataType, IAudioDataType >::Value, bool >::Type = true>
TSenderPtr< TDataType > Downcast (TUniquePtr< ISender > &&InPtr)
FORCEINLINE FDataReferenceID GetDataReferenceID (const IDataReference &InDataReference)
Return the ID of the data reference.
template<typename DataType>
const FText & GetMetasoundDataTypeDisplayText ()
Return the display text for a registered data type.
template<typename DataType>
const void *const GetMetasoundDataTypeId ()
Return the data type ID for a registered data type.
template<typename DataType>
const FName & GetMetasoundDataTypeName ()
Return the data type FName for a registered data type.
template<typename DataType>
const FString & GetMetasoundDataTypeString ()
Return the data type string for a registered data type.
template<typename Type>
FMetasoundEnvironmentVariableTypeId GetMetasoundEnvironmentVariableTypeId ()
Return the type ID for a environment variable type.
template<typename OperatorDataType>
FName GetStaticOperatorDataTypeName ()
Returns the type name of the node configuration object.
uint32 GetTypeHash (const Metasound::FTransmissionAddress &)
METASOUNDGRAPHCORE_API void GetVertexInterfaceDataState (const FInputVertexInterfaceData &InVertexInterface, TArray< FVertexDataState > &OutState)
Caches a representation of the current data references bound to the vertex interface.
METASOUNDGRAPHCORE_API void GetVertexInterfaceDataState (const FOutputVertexInterfaceData &InVertexInterface, TArray< FVertexDataState > &OutState)
Caches a representation of the current data references bound to the vertex interface.
template<typename DataType>
bool IsDataReferenceOfType (const IDataReference &InReference)
Test if an IDataReference contains the same data type as the template parameter.
template<typename VarType>
bool IsEnvironmentVariableOfType (const IMetasoundEnvironmentVariable &InVar)
Returns true if the environment variable contains the same type as the VarType
template<typename OperatorDataType, typename U = std::enable_if_t<std::is_base_of_v<TOperatorData<std::decay_t<OperatorDataType>>, OperatorDataType>>>
bool IsOperatorDataOfType (const IOperatorData &InNodeConfig)
Returns true if the provided node configuration is of the type T.
template<typename TDataType, typename TEnableIf< std::is_copy_constructible< TDataType >::value &&!TIsDerivedFrom< TDataType, IAudioDataType >::Value, bool >::Type = true>
TSharedRef< IDataChannel, ESPMode::ThreadSafe > MakeDataChannel (const FOperatorSettings &InSettings)
FORCEINLINE FNodeDataVertexKey MakeDestinationDataVertexKey (const FInputDataDestination &InDestination)
template<typename FactoryType, typename... ArgTypes>
TSharedRef< FactoryType, ESPMode::ThreadSafe > MakeOperatorFactoryRef (ArgTypes &&... Args)
Convenience function for making operator factory references.
FORCEINLINE FNodeDataVertexKey MakeSourceDataVertexKey (const FOutputDataSource &InSource)
Make a FNodeDataVertexKey from an FOutputDataSource.
struct UE_DEPRECATED (5.3, "Use the equivalent methods declared in `namespace DirectedGrpahAlgo {...}`") FDirectedGraphAlgo
struct UE_DEPRECATED (5.6, "Use FBuildGraphOperatorParams instead") FBuildGraphParams
template<typename ArrayType>
UE_DEPRECATED (5.6, "Use Frontend::RegisterArrayNodes() instead") bool RegisterArrayNodes()
template<typename TDataType, ELiteralType PreferredArgType = ELiteralType::None, typename UClassToUse = void>
UE_DEPRECATED (5.6, "Use Frontend::RegisterDataType instead") bool RegisterDataTypeWithFrontend()
template<typename T, typename ConfigurationType = void>
UE_DEPRECATED (5.6, "Use Frontend::RegisterNode()") bool RegisterNodeWithFrontend()
template<typename T, typename ConfigurationType = void>
UE_DEPRECATED (5.6, "Use Frontend::RegisterNode(const Metasound::FNodeClassMetadata&)") bool RegisterNodeWithFrontend(const Metasound
template<typename NodeClass>
struct UE_DEPRECATED (5.6, "Use std::is_constructible<T, FNodeInitData> instead") ConstructorTakesNodeInitData
class UE_EXPERIMENTAL (5.6, "FClassVertexInterfaces are experimental") FClassVertexInterface
FClassVertexInterface describes the interface of a node class.
struct UE_EXPERIMENTAL (5.6, "Sub interfaces are experimental") FBeginSubInterface
Declare the beginning of a sub interface in a vertex interface declaration.
template<typename T>
TDataValueReference< T > ValueCast (const TDataReadReference< T > &InRef)
Cast a TDataReadReference to a TDataValueReference.
template<typename T>
TDataValueReference< T > ValueCast (const TDataWriteReference< T > &InRef)
Cast a TDataWriteReference to a TDataValueReference.
template<typename DataType>
TDataWriteReference< DataType > WriteCast (const TDataReadReference< DataType > &InReadableRef)
Cast a TDataReadReference to a TDataWriteReference.
Variables
const FGuid METASOUNDFRONTEND_API FrontendInvalidID
METASOUNDFRONTEND_API int32 MetaSoundParameterEnableWarningOnIgnoredParameterCVar
const FString METASOUNDGRAPHCORE_API PluginAuthor
const FText METASOUNDGRAPHCORE_API PluginNodeMissingPrompt
template<typename EnumType, EnumType DefaultValue>
bool TEnum< EnumType, DefaultValue >::bHasWarnedNameToEnumConversionFailure = false
Detailed Description
standard Midi Controller ID according to the MIDI Association reference: https://www.midi.org/specifications-old/item/table-3-control-change-messages-data-bytes-2
METASOUND TRANSMISSION SYSTEM This allows for transmission of arbitrary data types using transmission addresses.
Metasound Frontend Document Access Pointers provide convenience methods for getting access pointers of FMetasoundFrontendDocument sub-elements.
For instance, to get an input vertex subobject on the root graph of the document, one can call:
FDocumentAccessPtr DocumentAccessPtr = MakeAccessPtr<FDocumentAccessPtr>(AccessPoint, Document);
FClassAccessPtr ClassAccessPtr = DocumentAccessPtr.GetRootGraph().GetNodeWithNodeID(NodeID).GetInputWithVertexID(VertexID);
Typical use case: TSenderPtr<float> FloatSender FDataTransmissionCenter::Get().RegisterNewSender<float>(ExampleAddress, InitSettings); TReceiverPtr<float> FloatReceiver FDataTransmissionCenter::Get().RegisterNewReceiver<float>(ExampleAddress, InitSettings);
//... FloatSender->Push(4.5f);
//... elsewhere on a different thread: float ReceivedFloat = FloatReceiver->Pop();
In general, some performance considerations for this system: 1) Senders and receivers are meant to have long lifecycles, and requesting them from the FDataTransmissionCenter may be expensive if done every tick. 2) Most non-audio data types cannot be mixed, so multiple senders to the same address will cause only one of the senders to be effective. 3) while the overall system is thread safe, individual TSender and TReceiver objects should only be used by a single thread.
Typedef Documentation
DataType
typedef FManagedArrayCollection DataType
Definition at line 26 of file GeometryCollectionSkeletonToCollectionNode.h.
FAudioBufferReadRef
typedef ::Metasound::TDataReadReference<FAudioBuffer> Metasound::FAudioBufferReadRef
Definition at line 147 of file MetasoundAudioBuffer.h.
FAudioBufferTypeInfo
typedef ::Metasound::TDataReferenceTypeInfo<FAudioBuffer> Metasound::FAudioBufferTypeInfo
Definition at line 147 of file MetasoundAudioBuffer.h.
FAudioBufferWriteRef
typedef ::Metasound::TDataWriteReference<FAudioBuffer> Metasound::FAudioBufferWriteRef
Definition at line 147 of file MetasoundAudioBuffer.h.
FBuildErrorArray
using Metasound::FBuildErrorArray = TArray<TUniquePtr<IOperatorBuildError>>
Array of build errors.
Definition at line 50 of file MetasoundBuilderInterface.h.
FDataReferenceID
using Metasound::FDataReferenceID = const void*
Definition at line 37 of file MetasoundDataReference.h.
FEnumDelayFilterType
using Metasound::FEnumDelayFilterType = Metasound::TEnum<EDelayFilterType, EDelayFilterType::LowPass>
Definition at line 17 of file DelayFilterType.h.
FEnumDelayFilterTypeInfo
typedef ::Metasound::TDataReferenceTypeInfo<FEnumDelayFilterType> Metasound::FEnumDelayFilterTypeInfo
Definition at line 17 of file DelayFilterType.h.
FEnumDelayFilterTypeReadReference
typedef ::Metasound::TDataReadReference<FEnumDelayFilterType> Metasound::FEnumDelayFilterTypeReadReference
Definition at line 17 of file DelayFilterType.h.
FEnumDelayFilterTypeWriteReference
typedef ::Metasound::TDataWriteReference<FEnumDelayFilterType> Metasound::FEnumDelayFilterTypeWriteReference
Definition at line 17 of file DelayFilterType.h.
FEnumDelayStereoType
using Metasound::FEnumDelayStereoType = Metasound::TEnum<EDelayStereoType, EDelayStereoType::Default>
Definition at line 17 of file DelayStereoType.h.
FEnumDelayStereoTypeInfo
typedef ::Metasound::TDataReferenceTypeInfo<FEnumDelayStereoType> Metasound::FEnumDelayStereoTypeInfo
Definition at line 17 of file DelayStereoType.h.
FEnumDelayStereoTypeReadReference
typedef ::Metasound::TDataReadReference<FEnumDelayStereoType> Metasound::FEnumDelayStereoTypeReadReference
Definition at line 17 of file DelayStereoType.h.
FEnumDelayStereoTypeWriteReference
typedef ::Metasound::TDataWriteReference<FEnumDelayStereoType> Metasound::FEnumDelayStereoTypeWriteReference
Definition at line 17 of file DelayStereoType.h.
FEnumMidiClockSubdivisionQuantizationReadRef
typedef ::Metasound::TDataReadReference<FEnumMidiClockSubdivisionQuantizationType> Metasound::FEnumMidiClockSubdivisionQuantizationReadRef
Definition at line 32 of file MidiClock.h.
FEnumMidiClockSubdivisionQuantizationType
using Metasound::FEnumMidiClockSubdivisionQuantizationType = Metasound::TEnum<EMidiClockSubdivisionQuantization, EMidiClockSubdivisionQuantization::None>
Definition at line 32 of file MidiClock.h.
FEnumMidiClockSubdivisionQuantizationTypeInfo
typedef ::Metasound::TDataReferenceTypeInfo<FEnumMidiClockSubdivisionQuantizationType> Metasound::FEnumMidiClockSubdivisionQuantizationTypeInfo
Definition at line 32 of file MidiClock.h.
FEnumMidiClockSubdivisionQuantizationWriteRef
typedef ::Metasound::TDataWriteReference<FEnumMidiClockSubdivisionQuantizationType> Metasound::FEnumMidiClockSubdivisionQuantizationWriteRef
Definition at line 32 of file MidiClock.h.
FEnumSharedStateBehaviorType
using Metasound::FEnumSharedStateBehaviorType = Metasound::TEnum<ESharedStateBehaviorType, ESharedStateBehaviorType::SameNodeInComposition>
Definition at line 85 of file MetasoundArrayRandomNode.h.
FEnumSharedStateBehaviorTypeInfo
typedef ::Metasound::TDataReferenceTypeInfo<FEnumSharedStateBehaviorType> Metasound::FEnumSharedStateBehaviorTypeInfo
Definition at line 85 of file MetasoundArrayRandomNode.h.
FEnumSharedStateBehaviorTypeReadRef
typedef ::Metasound::TDataReadReference<FEnumSharedStateBehaviorType> Metasound::FEnumSharedStateBehaviorTypeReadRef
Definition at line 85 of file MetasoundArrayRandomNode.h.
FEnumStdMidiControllerID
using Metasound::FEnumStdMidiControllerID = Metasound::TEnum<EStdMidiControllerID, EStdMidiControllerID::BankSelection>
Definition at line 178 of file MidiControllerID.h.
FEnumStdMidiControllerIDReadRef
typedef ::Metasound::TDataReadReference<FEnumStdMidiControllerID> Metasound::FEnumStdMidiControllerIDReadRef
Definition at line 178 of file MidiControllerID.h.
FEnumStdMidiControllerIDTypeInfo
typedef ::Metasound::TDataReferenceTypeInfo<FEnumStdMidiControllerID> Metasound::FEnumStdMidiControllerIDTypeInfo
Definition at line 178 of file MidiControllerID.h.
FEnumStdMidiControllerIDWriteRef
typedef ::Metasound::TDataWriteReference<FEnumStdMidiControllerID> Metasound::FEnumStdMidiControllerIDWriteRef
Definition at line 178 of file MidiControllerID.h.
FEnumTimeSyncOption
using Metasound::FEnumTimeSyncOption = Metasound::TEnum<ETimeSyncOption, ETimeSyncOption::None>
Definition at line 17 of file TimeSyncOption.h.
FEnumTimeSyncOptionInfo
typedef ::Metasound::TDataReferenceTypeInfo<FEnumTimeSyncOption> Metasound::FEnumTimeSyncOptionInfo
Definition at line 17 of file TimeSyncOption.h.
FEnumTimeSyncOptionReadReference
typedef ::Metasound::TDataReadReference<FEnumTimeSyncOption> Metasound::FEnumTimeSyncOptionReadReference
Definition at line 17 of file TimeSyncOption.h.
FEnumTimeSyncOptionWriteReference
typedef ::Metasound::TDataWriteReference<FEnumTimeSyncOption> Metasound::FEnumTimeSyncOptionWriteReference
Definition at line 17 of file TimeSyncOption.h.
FFrontendQueryPartition
using Metasound::FFrontendQueryPartition = TArray<FFrontendQueryEntry, TInlineAllocator<1>>
A FFrontendQueryPartition represents a set of entries associated with a single FFrontendQueryKey.
Definition at line 254 of file MetasoundFrontendQuery.h.
FFrontendQuerySelection
using Metasound::FFrontendQuerySelection = TSortedMap<FFrontendQueryKey, FFrontendQueryPartition>
A FFrontendQuerySelection holds a map of keys to partitions.
Definition at line 257 of file MetasoundFrontendQuery.h.
FFrontendQueryValue
using Metasound::FFrontendQueryValue = TVariant<FMetasoundFrontendVersion, Frontend::FNodeRegistryTransaction, FMetasoundFrontendClass, Frontend::FInterfaceRegistryTransaction, FMetasoundFrontendInterface>
A FFrontendQueryValue contains data of interest.
Definition at line 235 of file MetasoundFrontendQuery.h.
FInputDataDestinationCollection
typedef TMap<FNodeDataVertexKey, FInputDataDestination> Metasound::FInputDataDestinationCollection
FInputDataDestinationCollection contains multiple FInputDataDestinations mapped by FNodeDataVertexKeys.
Definition at line 317 of file MetasoundNodeInterface.h.
FIterateMetasoundFrontendClassFunction
using Metasound::Frontend::FIterateMetasoundFrontendClassFunction
Definition at line 25 of file MetasoundFrontendNodeClassRegistry.h.
FLiteralNodeConstructorParams
using Metasound::FLiteralNodeConstructorParams = FDefaultLiteralNodeConstructorParams
Definition at line 48 of file MetasoundNodeConstructorParams.h.
FNodeDataVertexKey
typedef TTuple<const INode*, FVertexName> Metasound::FNodeDataVertexKey
Key type for an FOutputDataSource or FInputDataDestination.
Definition at line 307 of file MetasoundNodeInterface.h.
FOperatorFactorySharedRef
typedef TSharedRef<IOperatorFactory, ESPMode::ThreadSafe> Metasound::FOperatorFactorySharedRef
Shared ref type of operator factory.
Definition at line 229 of file MetasoundNodeInterface.h.
FOutputDataSourceCollection
typedef TMap<FNodeDataVertexKey, FOutputDataSource> Metasound::FOutputDataSourceCollection
FOutputDataSourceCollection contains multiple FOutputDataSources mapped by FNodeDataVertexKeys.
Definition at line 312 of file MetasoundNodeInterface.h.
FOutputNodeConstructorParams
using Metasound::FOutputNodeConstructorParams = FDefaultNamedVertexNodeConstructorParams
Definition at line 47 of file MetasoundNodeConstructorParams.h.
FSampleRate
using Metasound::FSampleRate = int32
Definition at line 11 of file MetasoundOperatorSettings.h.
FSharedStateBehaviorTypeWriteRef
typedef ::Metasound::TDataWriteReference<FEnumSharedStateBehaviorType> Metasound::FSharedStateBehaviorTypeWriteRef
Definition at line 85 of file MetasoundArrayRandomNode.h.
FVariableNodeConstructorParams
using Metasound::FVariableNodeConstructorParams = FDefaultLiteralNodeConstructorParams
Definition at line 49 of file MetasoundNodeConstructorParams.h.
FVertexName
using Metasound::FVertexName = FName
Name of a given vertex.
Only unique for a given node interface.
Definition at line 18 of file MetasoundVertex.h.
TArrayConcatNode
template<typename ArrayType> using Metasound::TArrayConcatNode = TNodeFacade<TArrayConcatOperator<ArrayType>>
Definition at line 693 of file MetasoundArrayNodes.h.
TArrayGetNode
template<typename ArrayType> using Metasound::TArrayGetNode = TNodeFacade<TArrayGetOperator<ArrayType>>
Definition at line 383 of file MetasoundArrayNodes.h.
TArrayLastIndexNode
template<typename ArrayType> using Metasound::TArrayLastIndexNode = TNodeFacade<TArrayLastIndexOperator<ArrayType>>
Definition at line 936 of file MetasoundArrayNodes.h.
TArrayNumNode
template<typename ArrayType> using Metasound::TArrayNumNode = TNodeFacade<TArrayNumOperator<ArrayType>>
Definition at line 189 of file MetasoundArrayNodes.h.
TArrayRandomGetNode
template<typename ArrayType> using Metasound::TArrayRandomGetNode = TNodeFacade<TArrayRandomGetOperator<ArrayType>>
Definition at line 564 of file MetasoundArrayRandomNode.h.
TArraySetNode
template<typename ArrayType> using Metasound::TArraySetNode = TNodeFacade<TArraySetOperator<ArrayType>>
Definition at line 565 of file MetasoundArrayNodes.h.
TArrayShuffleNode
template<typename ArrayType> using Metasound::TArrayShuffleNode = TNodeFacade<TArrayShuffleOperator<ArrayType>>
Definition at line 456 of file MetasoundArrayShuffleNode.h.
TArraySubsetNode
template<typename ArrayType> using Metasound::TArraySubsetNode = TNodeFacade<TArraySubsetOperator<ArrayType>>
Definition at line 839 of file MetasoundArrayNodes.h.
TInputOperator
template<typename DataType, EVertexAccessType VertexAccess = EVertexAccessType::Reference> using Metasound::TInputOperator
Initial value:
 std::conditional_t<
        VertexAccess == EVertexAccessType::Value || !TPostExecutableDataType<DataType>::bIsPostExecutable,
        MetasoundInputNodePrivate::TInputValueOperator<DataType>,
        MetasoundInputNodePrivate::TResetablePostExecutableInputOperator<DataType>
    >
Owning input operator that may need execution.
Definition at line 235 of file MetasoundInputNode.h.
TPassThroughOperator
template<typename DataType, EVertexAccessType VertexAccess = EVertexAccessType::Reference> using Metasound::TPassThroughOperator
Initial value:
 std::conditional_t<
        VertexAccess == EVertexAccessType::Value,
        MetasoundInputNodePrivate::TInputValueOperator<DataType>,
        MetasoundInputNodePrivate::FNonExecutableInputPassThroughOperator
    >
Choose pass through operator based upon data type and access type.
Definition at line 243 of file MetasoundInputNode.h.
TReceiverPtr
template<typename TDataType, typename UReceiverType = typename std::conditional<TIsDerivedFrom<TDataType, IAudioDataType>::Value, TAudioReceiver<TDataType>, TReceiver<TDataType>>::type> using Metasound::TReceiverPtr = TUniquePtr<UReceiverType>
Definition at line 936 of file MetasoundRouter.h.
TSenderPtr
template<typename TDataType, typename USenderType = typename std::conditional<TIsDerivedFrom<TDataType, IAudioDataType>::Value, TAudioSender<TDataType>, TSender<TDataType>>::type> using Metasound::TSenderPtr = TUniquePtr<USenderType>
Definition at line 933 of file MetasoundRouter.h.
TSortedVertexNameMap
template<typename ValueType> using Metasound::TSortedVertexNameMap = TSortedMap<FVertexName, ValueType, FDefaultAllocator, FNameFastLess>
Convenience for using a TSortedMap with FVertexName Key type.
This template makes it convenient to create a TSortedMap with an FVertexName while also avoiding compilation errors incurred from using the FName default "less than" operator in the TSortedMap implementation.
FVertexName is an alias to FName.
TSortedMap<FName, ValueType> fails to compile since the "less than" operator specific implementation needs to be chosen (FastLess vs LexicalLess)
Due to the template argument order of TSortedMap this also forces you to choose the allocator.
This is all a bit of an annoyance to do every time we use a TSortedMap with an FVertexName as the key.
Definition at line 487 of file MetasoundVertexData.h.
TVariableAccessorNode
template<typename DataType> using Metasound::TVariableAccessorNode = TNodeFacade<MetasoundVariableNodesPrivate::TVariableAccessorOperator<DataType>>
FGetVariable node provides delay free, cpu free access to a set variable.
Definition at line 581 of file MetasoundVariableNodes.h.
TVariableDeferredAccessorNode
template<typename DataType> using Metasound::TVariableDeferredAccessorNode = TNodeFacade<MetasoundVariableNodesPrivate::TVariableDeferredAccessorOperator<DataType>>
TVariableDeferredAccessorNode provides access to the prior executions variable value.
TVariableDeferredAccessorNodes must always be before TVariableMutatorNodes in the dependency order.
Definition at line 577 of file MetasoundVariableNodes.h.
TVariableMutatorNode
template<typename DataType> using Metasound::TVariableMutatorNode = TNodeFacade<MetasoundVariableNodesPrivate::TVariableMutatorOperator<DataType>>
TVariableMutatorNode allows variable values to be set.
Definition at line 569 of file MetasoundVariableNodes.h.
Enumeration Type Documentation
EDataReferenceAccessType
enum class Metasound::EDataReferenceAccessType : uint8 strong
EDataReferenceAccessType describes the underlying data reference access type for a data reference contained in a FAnyDataReference.
This value can be used to determine which methods are supported for accessing a data reference using GetDataReadReference<>() or GetDataWriteReference<>()
Enumerator
None
Read
Write
Value
Definition at line 528 of file MetasoundDataReference.h.
EDataRefShouldConstruct
enum class Metasound::EDataRefShouldConstruct strong
Enumerator
NewObject
Definition at line 161 of file MetasoundDataReference.h.
ELiteralType
enum class Metasound::ELiteralType : uint8 strong
ELiteralType describes the format of the values held in the literal.
Enumerator
None
Boolean
Integer
Float
String
UObjectProxy
NoneArray
BooleanArray
IntegerArray
FloatArray
StringArray
UObjectProxyArray
Invalid
COUNT
Definition at line 23 of file MetasoundLiteral.h.
EOperatorBuilderNodePruning
enum class Metasound::EOperatorBuilderNodePruning : uint8 strong
EOperatorBuildNodePruning expresses the desired pruning behavior during the node pruning step.
Some nodes are unreachable in the graph either by traversing from the input nodes to from the output nodes. Because they are not dependent, they have no impact on the produced output and can be pruned without causing any change to the declared behavior of the graph.
Enumerator
None
Do not prune any nodes.
PruneNodesWithoutOutputDependency
Prune nodes which cannot be reached from the output nodes.
PruneNodesWithoutInputDependency
Prune nodes which cannot be reached from the input nodes.
PruneNodesWithoutExternalDependency
Prune nodes which cannot be reached from the input nodes or output nodes.
Definition at line 19 of file MetasoundOperatorBuilderSettings.h.
ESharedStateBehaviorType
enum class Metasound::ESharedStateBehaviorType : int32 strong
Enumerator
SameNode
SameNodeInComposition
SameData
Definition at line 77 of file MetasoundArrayRandomNode.h.
EVertexAccessType
enum class Metasound::EVertexAccessType strong
Describe how the vertex will access connected data.
Enumerator
Reference
Value
Definition at line 81 of file MetasoundVertex.h.
Function Documentation
AddBuildError()
template<typename ErrorType, typename... ArgTypes> void Metasound::AddBuildError (FBuildErrorArray & OutErrors, ArgTypes &&... Args)
Convenience template for adding build errors.
The function can be used in the following way:
FBuildErrorArray MyErrorArray; AddBuildError<FMyBuildErrorType>(MyErrorArray, MyBuildErrorConstructorArgs...);
Parameters
OutErrors - Array which holds the errors.
Args - Constructor arguments for the error.
Definition at line 168 of file MetasoundBuilderInterface.h.
References TArray< InElementType, InAllocatorType >::Add(), Forward(), and MakeUnique().
CanEverExecuteGraph()
METASOUNDGRAPHCORE_API bool Metasound::CanEverExecuteGraph (bool bIsCooking = false)
CastAddressType()
template<typename DerivedAddressType> const DerivedAddressType * Metasound::CastAddressType (const FTransmissionAddress & InOther)
Attempt to cast a FTransmissionAddress to a derived address type.
This function uses the FTransmissionAddress::GetAddressType() method to determine whether the cast is legal. Each subclass of FTransmissionAddress MUST provide a unique address type to protect against invalid casts.
Definition at line 126 of file MetasoundRouter.h.
CastMetasoundEnvironmentVariableChecked() [1/2]
template<typename Type> const TMetasoundEnvironmentVariable< Type > & Metasound::CastMetasoundEnvironmentVariableChecked (const IMetasoundEnvironmentVariable & InVar)
Casts an environment variable to the derived type.
Definition at line 176 of file MetasoundEnvironment.h.
References check, and IsEnvironmentVariableOfType().
CastMetasoundEnvironmentVariableChecked() [2/2]
template<typename Type> TMetasoundEnvironmentVariable< Type > & Metasound::CastMetasoundEnvironmentVariableChecked (IMetasoundEnvironmentVariable & InVar)
Casts an environment variable to the derived type.
Definition at line 166 of file MetasoundEnvironment.h.
References check, and IsEnvironmentVariableOfType().
Referenced by Metasound::FMetasoundEnvironment::GetValue().
CastOperatorData()
template<typename DesiredOperatorDataType, typename ProvidedOperatorDataType> std::enable_if_t< std::conjunction_v< std::is_base_of< TOperatorData< std::decay_t< DesiredOperatorDataType > >, DesiredOperatorDataType >, std::is_base_of< IOperatorData, ProvidedOperatorDataType > >, DesiredOperatorDataType * > Metasound::CastOperatorData (ProvidedOperatorDataType * InOperatorData)
Returns a non-null pointer to a downcast node configuration object if the provided node configuration is non-null and of the same derived type.
Definition at line 104 of file MetasoundOperatorData.h.
References IsOperatorDataOfType().
CompareVertexInterfaceDataToPriorState() [1/2]
METASOUNDGRAPHCORE_API void Metasound::CompareVertexInterfaceDataToPriorState (const FInputVertexInterfaceData & InCurrentInterface, const TArray< FVertexDataState > & InPriorState, TSortedVertexNameMap< FAnyDataReference > & OutUpdates)
Compares the current data bound to the vertex interface with a prior cached state.
CompareVertexInterfaceDataToPriorState() [2/2]
METASOUNDGRAPHCORE_API void Metasound::CompareVertexInterfaceDataToPriorState (const FOutputVertexInterfaceData & InCurrentInterface, const TArray< FVertexDataState > & InPriorState, TSortedVertexNameMap< FAnyDataReference > & OutUpdates)
Compares the current data bound to the vertex interface with a prior cached state.
CreateArrayTypeNameFromElementTypeName()
METASOUNDGRAPHCORE_API FName Metasound::CreateArrayTypeNameFromElementTypeName (const FName InTypeName)
Returns array type associated with the base datatype provided(ex.
'Float:Array' if 'Float' is provided)
CreateElementTypeNameFromArrayTypeName()
METASOUNDGRAPHCORE_API FName Metasound::CreateElementTypeNameFromArrayTypeName (const FName InArrayTypeName)
Returns the base data type with the array extension(ex.
'Float' if 'Float:Array' is provided)
DECLARE_METASOUND_DATA_REFERENCE_TYPES() [1/6]
Metasound::DECLARE_METASOUND_DATA_REFERENCE_TYPES (bool , METASOUNDFRONTEND_API , FBoolTypeInfo , FBoolReadRef , FBoolWriteRef)
Referenced by Metasound::FDataTransmissionCenter::FDataTransmissionCenter(), Metasound::TDataReferenceTypeInfo< FMidiEventInfo >::GetTypeDisplayText(), Metasound::TDataReferenceTypeInfo< FMusicSeekTarget >::GetTypeDisplayText(), and Metasound::TDataReferenceTypeInfo< FMusicTimestamp >::GetTypeDisplayText().
DECLARE_METASOUND_DATA_REFERENCE_TYPES() [2/6]
Metasound::DECLARE_METASOUND_DATA_REFERENCE_TYPES (float , METASOUNDFRONTEND_API , FFloatTypeInfo , FFloatReadRef , FFloatWriteRef)
DECLARE_METASOUND_DATA_REFERENCE_TYPES() [3/6]
Metasound::DECLARE_METASOUND_DATA_REFERENCE_TYPES (FString , METASOUNDFRONTEND_API , FStringTypeInfo , FStringReadRef , FStringWriteRef)
DECLARE_METASOUND_DATA_REFERENCE_TYPES() [4/6]
Metasound::DECLARE_METASOUND_DATA_REFERENCE_TYPES (FTime , METASOUNDFRONTEND_API , FTimeTypeInfo , FTimeReadRef , FTimeWriteRef)
DECLARE_METASOUND_DATA_REFERENCE_TYPES() [5/6]
Metasound::DECLARE_METASOUND_DATA_REFERENCE_TYPES (FTrigger , METASOUNDFRONTEND_API , FTriggerTypeInfo , FTriggerReadRef , FTriggerWriteRef)
DECLARE_METASOUND_DATA_REFERENCE_TYPES() [6/6]
Metasound::DECLARE_METASOUND_DATA_REFERENCE_TYPES (int32 , METASOUNDFRONTEND_API , FInt32TypeInfo , FInt32ReadRef , FInt32WriteRef)
Downcast() [1/2]
template<typename TDataType, typename TEnableIf< TIsDerivedFrom< TDataType, IAudioDataType >::Value, bool >::Type = true> TReceiverPtr< TDataType > Metasound::Downcast (TUniquePtr< IReceiver > && InPtr)
Definition at line 985 of file MetasoundRouter.h.
References checkf, Metasound::TAudioReceiver< TDataType >::GetDataTypeName(), and TEXT.
Downcast() [2/2]
template<typename TDataType, typename TEnableIf< TIsDerivedFrom< TDataType, IAudioDataType >::Value, bool >::Type = true> TSenderPtr< TDataType > Metasound::Downcast (TUniquePtr< ISender > && InPtr)
Definition at line 962 of file MetasoundRouter.h.
References checkf, Metasound::TAudioSender< TDataType >::GetDataTypeName(), and TEXT.
Referenced by Metasound::FAddressRouter::RegisterNewReceiver(), Metasound::FDataTransmissionCenter::RegisterNewReceiver(), Metasound::FAddressRouter::RegisterNewSender(), and Metasound::FDataTransmissionCenter::RegisterNewSender().
GetDataReferenceID()
FORCEINLINE FDataReferenceID Metasound::GetDataReferenceID (const IDataReference & InDataReference)
Return the ID of the data reference.
Definition at line 137 of file MetasoundDataReference.h.
References FORCEINLINE, and Metasound::IDataReference::GetRaw().
Referenced by Metasound::Frontend::FVertexAnalyzerBase::GetDataReferenceId().
GetMetasoundDataTypeDisplayText()
template<typename DataType> const FText & Metasound::GetMetasoundDataTypeDisplayText ()
Return the display text for a registered data type.
Definition at line 77 of file MetasoundDataReference.h.
Referenced by Metasound::Frontend::MetasoundDataTypeRegistrationPrivate::CreateDataTypeInfo(), Metasound::TAutoConverterNode< FromDataType, ToDataType >::FConverterOperator::Execute(), Metasound::TAutoConverterNode< FromDataType, ToDataType >::GetConverterDataTypeInfo(), Metasound::ReceiveNodePrivate::TReceiverOperator< TDataType >::GetNodeInfo(), Metasound::SendNodePrivate::TSendOperator< TDataType >::GetNodeInfo(), Metasound::TArrayConcatOperator< ArrayType >::GetNodeInfo(), Metasound::TArrayGetOperator< ArrayType >::GetNodeInfo(), Metasound::TArrayLastIndexOperator< ArrayType >::GetNodeInfo(), Metasound::TArrayNumOperator< ArrayType >::GetNodeInfo(), Metasound::TArrayRandomGetOperator< ArrayType >::GetNodeInfo(), Metasound::TArraySetOperator< ArrayType >::GetNodeInfo(), Metasound::TArrayShuffleOperator< ArrayType >::GetNodeInfo(), and Metasound::TArraySubsetOperator< ArrayType >::GetNodeInfo().
GetMetasoundDataTypeId()
template<typename DataType> const void *const Metasound::GetMetasoundDataTypeId ()
Return the data type ID for a registered data type.
This ID is runtime constant but may change between executions and builds.
Definition at line 87 of file MetasoundDataReference.h.
Referenced by Metasound::TDataReference< DataType >::GetDataTypeId(), and IsDataReferenceOfType().
GetMetasoundDataTypeName()
template<typename DataType> const FName & Metasound::GetMetasoundDataTypeName ()
Return the data type FName for a registered data type.
Definition at line 59 of file MetasoundDataReference.h.
References FName.
Referenced by Metasound::FFilterClassesByInputVertexDataType::FFilterClassesByInputVertexDataType(), Metasound::FFilterClassesByOutputVertexDataType::FFilterClassesByOutputVertexDataType(), Metasound::TInputConstructorVertex< DataType >::TInputConstructorVertex(), Metasound::TInputDataVertex< DataType >::TInputDataVertex(), Metasound::TInputNode< DataType, VertexAccess >::TInputNode(), Metasound::TLiteralNode< DataType >::TLiteralNode(), Metasound::TOutputConstructorVertex< DataType >::TOutputConstructorVertex(), Metasound::TOutputDataVertex< DataType >::TOutputDataVertex(), Metasound::TOutputNode< DataType, VertexAccess >::TOutputNode(), Metasound::Frontend::FVertexAnalyzerBase::BindOutputData(), Metasound::Frontend::MetasoundDataTypeRegistrationPrivate::CreateDataTypeInfo(), Metasound::ReceiveNodePrivate::TReceiverOperator< TDataType >::CreateNewReceiver(), Metasound::SendNodePrivate::TSendOperator< TDataType >::CreateNewSender(), Metasound::TInputNode< DataType, VertexAccess >::CreateNodeClassMetadata(), MetasoundArrayHashPrivate::GetArrayContentHashGuid(), HarmonixMetasound::Nodes::MorphingLFO::GetClassName(), Metasound::TAutoConverterNode< FromDataType, ToDataType >::GetConverterDataTypeInfo(), Metasound::Frontend::FGraphAnalyzerAddress::GetDataType(), Metasound::Frontend::TVertexAnalyzerForwardValue< ChildClass, DataType >::GetDataType(), Metasound::TAudioDataChannel< TDataType >::GetDataTypeName(), Metasound::TAudioReceiver< TDataType >::GetDataTypeName(), Metasound::TAudioSender< TDataType >::GetDataTypeName(), Metasound::TCopyableDataChannel< TDataType >::GetDataTypeName(), Metasound::TDataReference< DataType >::GetDataTypeName(), Metasound::TNonOperationalDataChannel< TDataType >::GetDataTypeName(), Metasound::TOutputStorage< DataType >::GetDataTypeName(), Metasound::TReceiver< TDataType >::GetDataTypeName(), Metasound::TSender< TDataType >::GetDataTypeName(), Metasound::TAutoConverterNode< FromDataType, ToDataType >::GetInputName(), Metasound::ReceiveNodePrivate::TReceiverOperator< TDataType >::GetNodeInfo(), Metasound::SendNodePrivate::TSendOperator< TDataType >::GetNodeInfo(), Metasound::TArrayConcatOperator< ArrayType >::GetNodeInfo(), Metasound::TArrayGetOperator< ArrayType >::GetNodeInfo(), Metasound::TArrayLastIndexOperator< ArrayType >::GetNodeInfo(), Metasound::TArrayNumOperator< ArrayType >::GetNodeInfo(), Metasound::TArrayRandomGetOperator< ArrayType >::GetNodeInfo(), Metasound::TArraySetOperator< ArrayType >::GetNodeInfo(), Metasound::TArrayShuffleOperator< ArrayType >::GetNodeInfo(), Metasound::TArraySubsetOperator< ArrayType >::GetNodeInfo(), Metasound::TLiteralNode< DataType >::GetNodeInfo(), Metasound::TAutoConverterNode< FromDataType, ToDataType >::GetOutputName(), Metasound::ReceiveNodePrivate::TReceiverOperator< TDataType >::GetSendAddressWithDataType(), Metasound::SendNodePrivate::TSendOperator< TDataType >::GetSendAddressWithDataType(), Metasound::SendNodePrivate::TSendOperator< TDataType >::GetSendInputName(), Metasound::Frontend::TVertexAnalyzerForwardValue< ChildClass, DataType >::FOutputs::GetValue(), Metasound::VariableNames::GetVariableAccessorNodeClassName(), Metasound::VariableNames::GetVariableDeferredAccessorNodeClassName(), Metasound::VariableNames::GetVariableMutatorNodeClassName(), Metasound::VariableNames::GetVariableNodeClassName(), IsDataReferenceOfType(), Metasound::Frontend::MetasoundDataTypeRegistrationPrivate::RegisterDataTypeWithFrontendInternal(), Metasound::FInputVertexInterfaceData::SetValue(), Metasound::FOutputVertexInterfaceData::SetValue(), Metasound::VertexDataPrivate::FInputBinding::SetValue(), Metasound::TInputNode< DataType, VertexAccess >::UE_DEPRECATED(), and Metasound::TLiteralNode< DataType >::UE_DEPRECATED().
GetMetasoundDataTypeString()
template<typename DataType> const FString & Metasound::GetMetasoundDataTypeString ()
Return the data type string for a registered data type.
Definition at line 68 of file MetasoundDataReference.h.
Referenced by Metasound::TArrayRandomGetOperator< ArrayType >::ExecuteTriggerNext(), Metasound::FAnyDataReference::TGetAs< TDataWriteReference< DataType > >::Get(), MetasoundArrayHashPrivate::GetArrayContentHashGuid(), Metasound::TSender< TDataType >::PushLiteral(), Metasound::Frontend::MetasoundDataTypeRegistrationPrivate::RegisterDataTypeWithFrontendInternal(), and Metasound::Frontend::MetasoundDataTypeRegistrationPrivate::TExecutableDataTypeDeprecation< DataType >::TriggerDeprecationMessage().
GetMetasoundEnvironmentVariableTypeId()
template<typename Type> FMetasoundEnvironmentVariableTypeId Metasound::GetMetasoundEnvironmentVariableTypeId ()
Return the type ID for a environment variable type.
Definition at line 64 of file MetasoundEnvironment.h.
Referenced by Metasound::TMetasoundEnvironmentVariable< Type >::GetTypeId(), and IsEnvironmentVariableOfType().
GetStaticOperatorDataTypeName()
template<typename OperatorDataType> FName Metasound::GetStaticOperatorDataTypeName ()
Returns the type name of the node configuration object.
Definition at line 80 of file MetasoundOperatorData.h.
Referenced by IsOperatorDataOfType().
GetTypeHash()
FORCEINLINE uint32 Metasound::GetTypeHash (const Metasound::FTransmissionAddress & InAddress)
Definition at line 178 of file MetasoundRouter.h.
References FORCEINLINE, and Metasound::FTransmissionAddress::GetHash().
Referenced by Metasound::Frontend::FNodeClassRegistryKey::GetTypeHash.
GetVertexInterfaceDataState() [1/2]
METASOUNDGRAPHCORE_API void Metasound::GetVertexInterfaceDataState (const FInputVertexInterfaceData & InVertexInterface, TArray< FVertexDataState > & OutState)
Caches a representation of the current data references bound to the vertex interface.
GetVertexInterfaceDataState() [2/2]
METASOUNDGRAPHCORE_API void Metasound::GetVertexInterfaceDataState (const FOutputVertexInterfaceData & InVertexInterface, TArray< FVertexDataState > & OutState)
Caches a representation of the current data references bound to the vertex interface.
IsDataReferenceOfType()
template<typename DataType> bool Metasound::IsDataReferenceOfType (const IDataReference & InReference)
Test if an IDataReference contains the same data type as the template parameter.
Returns
True if the IDataReference contains the DataType. False otherwise.
Definition at line 148 of file MetasoundDataReference.h.
References Metasound::IDataReference::GetDataTypeId(), Metasound::IDataReference::GetDataTypeName(), GetMetasoundDataTypeId(), and GetMetasoundDataTypeName().
Referenced by Metasound::FDataReferenceCollection::ContainsDataReadReference(), Metasound::FDataReferenceCollection::ContainsDataWriteReference(), Metasound::FAnyDataReference::TGetAs< ResultType >::Get(), Metasound::FAnyDataReference::TGetAs< TDataReadReference< DataType > >::Get(), Metasound::FAnyDataReference::TGetAs< TDataValueReference< DataType > >::Get(), Metasound::FAnyDataReference::TGetAs< TDataWriteReference< DataType > >::Get(), and Metasound::FAnyDataReference::GetWritableValue().
IsEnvironmentVariableOfType()
template<typename VarType> bool Metasound::IsEnvironmentVariableOfType (const IMetasoundEnvironmentVariable & InVar)
Returns true if the environment variable contains the same type as the VarType
Definition at line 159 of file MetasoundEnvironment.h.
References GetMetasoundEnvironmentVariableTypeId(), and Metasound::IMetasoundEnvironmentVariable::GetTypeId().
Referenced by CastMetasoundEnvironmentVariableChecked(), CastMetasoundEnvironmentVariableChecked(), and Metasound::FMetasoundEnvironment::IsType().
IsOperatorDataOfType()
template<typename OperatorDataType, typename U = std::enable_if_t<std::is_base_of_v<TOperatorData<std::decay_t<OperatorDataType>>, OperatorDataType>>> bool Metasound::IsOperatorDataOfType (const IOperatorData & InNodeConfig)
Returns true if the provided node configuration is of the type T.
Definition at line 90 of file MetasoundOperatorData.h.
References Metasound::IOperatorData::GetOperatorDataTypeName(), and GetStaticOperatorDataTypeName().
Referenced by CastOperatorData().
MakeDataChannel()
template<typename TDataType, typename TEnableIf< std::is_copy_constructible< TDataType >::value &&!TIsDerivedFrom< TDataType, IAudioDataType >::Value, bool >::Type = true> TSharedRef< IDataChannel, ESPMode::ThreadSafe > Metasound::MakeDataChannel (const FOperatorSettings & InSettings)
Definition at line 941 of file MetasoundRouter.h.
References MakeShareable().
Referenced by Metasound::FTransmissionDataChannelFactory::CreateDataChannel().
MakeDestinationDataVertexKey()
FORCEINLINE FNodeDataVertexKey Metasound::MakeDestinationDataVertexKey (const FInputDataDestination & InDestination)
Definition at line 325 of file MetasoundNodeInterface.h.
References FORCEINLINE, Metasound::FInputDataDestination::Node, Metasound::FInputDataDestination::Vertex, and Metasound::FDataVertex::VertexName.
MakeOperatorFactoryRef()
template<typename FactoryType, typename... ArgTypes> TSharedRef< FactoryType, ESPMode::ThreadSafe > Metasound::MakeOperatorFactoryRef (ArgTypes &&... Args)
Convenience function for making operator factory references.
Definition at line 233 of file MetasoundNodeInterface.h.
References Forward(), and MakeShared().
Referenced by Metasound::TAutoConverterNode< FromDataType, ToDataType >::TAutoConverterNode(), and Metasound::TLiteralNode< DataType >::TLiteralNode().
MakeSourceDataVertexKey()
FORCEINLINE FNodeDataVertexKey Metasound::MakeSourceDataVertexKey (const FOutputDataSource & InSource)
Make a FNodeDataVertexKey from an FOutputDataSource.
Definition at line 320 of file MetasoundNodeInterface.h.
References FORCEINLINE, Metasound::FOutputDataSource::Node, Metasound::FOutputDataSource::Vertex, and Metasound::FDataVertex::VertexName.
UE_DEPRECATED() [1/7]
struct Metasound::UE_DEPRECATED (5. 3, "Use the equivalent methods declared in `namespace DirectedGrpahAlgo {...}`")
UE_DEPRECATED() [2/7]
struct Metasound::UE_DEPRECATED (5. 6, "Use FBuildGraphOperatorParams instead")
UE_DEPRECATED() [3/7]
template<typename ArrayType> Metasound::UE_DEPRECATED (5. 6, "Use Frontend::RegisterArrayNodes() instead")
Definition at line 207 of file MetasoundArrayNodesRegistration.h.
References bool, and Metasound::Frontend::RegisterArrayNodes().
UE_DEPRECATED() [4/7]
template<typename TDataType, ELiteralType PreferredArgType = ELiteralType::None, typename UClassToUse = void> Metasound::UE_DEPRECATED (5. 6, "Use Frontend::RegisterDataType instead")
Definition at line 873 of file MetasoundDataTypeRegistrationMacro.h.
References bool, and Metasound::Frontend::RegisterDataType().
UE_DEPRECATED() [5/7]
template<typename T, typename ConfigurationType = void> Metasound::UE_DEPRECATED (5. 6, "Use Frontend::RegisterNode()")
Definition at line 275 of file MetasoundNodeRegistrationMacro.h.
References bool, and Metasound::Frontend::RegisterNode().
UE_DEPRECATED() [6/7]
template<typename T, typename ConfigurationType = void> Metasound::UE_DEPRECATED (5. 6, "Use Frontend::RegisterNode(const Metasound::FNodeClassMetadata&)") const
Definition at line 282 of file MetasoundNodeRegistrationMacro.h.
References bool, and Metasound::Frontend::RegisterNode().
UE_DEPRECATED() [7/7]
template<typename NodeClass> struct Metasound::UE_DEPRECATED (5. 6, "Use std::is_constructible<T, FNodeInitData> instead")
Definition at line 239 of file MetasoundNodeRegistrationMacro.h.
UE_EXPERIMENTAL() [1/2]
class Metasound::UE_EXPERIMENTAL (5. 6, "FClassVertexInterfaces are experimental")
FClassVertexInterface describes the interface of a node class.
It is an immutable factory for FVertexInterfaces.
UE_EXPERIMENTAL() [2/2]
struct Metasound::UE_EXPERIMENTAL (5. 6, "Sub interfaces are experimental")
Declare the beginning of a sub interface in a vertex interface declaration.
A sub interface configuration is used to create a FVertexInterface from a FClassVertexInterface.
A description of a sub interface which is used when declaring a FClassVertexInterface.
Declare the ending of a sub interface in a vertex interface declaration.
ValueCast() [1/2]
template<typename T> TDataValueReference< T > Metasound::ValueCast (const TDataReadReference< T > & InRef)
Cast a TDataReadReference to a TDataValueReference.
In general TDataReadReferences should not be converted into TDataValueReferences unless the caller can be certain that no other TDataWriteReference exists for the underlying parameter. Having a TDataWriteReferences to an existing TDataValueReference can cause confusing behavior as values references are not expected to change value.
Definition at line 332 of file MetasoundDataReference.h.
ValueCast() [2/2]
template<typename T> TDataValueReference< T > Metasound::ValueCast (const TDataWriteReference< T > & InRef)
Cast a TDataWriteReference to a TDataValueReference.
In general TDataWriteReferences should never beconverted into TDataValueReferences unless the caller can be certain that no other TDataWriteReference exists for the underlying parameter. Having a TDataWriteReferences to an existing TDataValueReference can cause confusing behavior as values references are not expected to change value.
Definition at line 345 of file MetasoundDataReference.h.
WriteCast()
template<typename DataType> TDataWriteReference< DataType > Metasound::WriteCast (const TDataReadReference< DataType > & InReadableRef)
Cast a TDataReadReference to a TDataWriteReference.
In general TDataReadReferences should not be converted into TDataWriteReferences unless the caller can be certain that no other TDataWriteReference exists for the underlying parameter. Having multiple TDataWriteReferences to the same parameter can cause confusion behavior as values are overwritten in an underterministic fashion.
Definition at line 439 of file MetasoundDataReference.h.
Variable Documentation
FrontendInvalidID
const FGuid METASOUNDFRONTEND_API Metasound::FrontendInvalidID extern
MetaSoundParameterEnableWarningOnIgnoredParameterCVar
METASOUNDFRONTEND_API int32 Metasound::MetaSoundParameterEnableWarningOnIgnoredParameterCVar extern
PluginAuthor
const FString METASOUNDGRAPHCORE_API Metasound::PluginAuthor extern
Referenced by Metasound::TVariableNode< DataType >::CreateNodeClassMetadata(), Metasound::MetasoundVariableNodesPrivate::TVariableAccessorOperator< DataType >::GetNodeInfo(), Metasound::MetasoundVariableNodesPrivate::TVariableDeferredAccessorOperator< DataType >::GetNodeInfo(), Metasound::MetasoundVariableNodesPrivate::TVariableMutatorOperator< DataType >::GetNodeInfo(), Metasound::ReceiveNodePrivate::TReceiverOperator< TDataType >::GetNodeInfo(), and Metasound::SendNodePrivate::TSendOperator< TDataType >::GetNodeInfo().
PluginNodeMissingPrompt
const FText METASOUNDGRAPHCORE_API Metasound::PluginNodeMissingPrompt extern
Referenced by Metasound::TVariableNode< DataType >::CreateNodeClassMetadata(), Metasound::MetasoundVariableNodesPrivate::TVariableAccessorOperator< DataType >::GetNodeInfo(), Metasound::MetasoundVariableNodesPrivate::TVariableDeferredAccessorOperator< DataType >::GetNodeInfo(), Metasound::MetasoundVariableNodesPrivate::TVariableMutatorOperator< DataType >::GetNodeInfo(), Metasound::ReceiveNodePrivate::TReceiverOperator< TDataType >::GetNodeInfo(), and Metasound::SendNodePrivate::TSendOperator< TDataType >::GetNodeInfo().
TEnum< EnumType, DefaultValue >::bHasWarnedNameToEnumConversionFailure
template<typename EnumType, EnumType DefaultValue> bool Metasound::TEnum< EnumType, DefaultValue >::bHasWarnedNameToEnumConversionFailure = false
Definition at line 265 of file MetasoundEnum.h.