Unreal Engine 5.6 C++ API: UE::StructUtils Namespace Reference
UE::StructUtils Namespace Reference
Namespaces
namespace Private
Typedefs
template<typename T>
using EnableIfNotSharedInstancedOrViewStruct
template<typename T>
using EnableIfSharedInstancedOrViewStruct
Functions
void CalcMidIndexAndCount (int32 ArrayNum, int32 &InOutIndex, int32 &InOutCount)
Returns the middle part of an array or view by taking up to the given number of elements from the given position.
template<typename T>
void CheckStructType ()
template<typename T>
void CheckWrapperType ()
template<typename T>
TEnableIf<!TIsDerivedFrom< T, UObject >::IsDerived, UScriptStruct * >::Type GetAsUStruct ()
template<typename T>
TEnableIf< TIsDerivedFrom< T, UObject >::IsDerived, UClass * >::Type GetAsUStruct ()
uint32 GetStructCrc32 (const FConstSharedStruct &SharedView, const uint32 CRC=0)
uint32 GetStructCrc32 (const FConstStructView &StructView, const uint32 CRC=0)
uint32 GetStructCrc32 (const FSharedStruct &SharedView, const uint32 CRC=0)
uint32 GetStructCrc32 (const FStructView &StructView, const uint32 CRC=0)
uint32 GetStructCrc32 (const UScriptStruct &ScriptStruct, const uint8 *StructMemory, const uint32 CRC=0)
uint64 GetStructHash64 (const FConstSharedStruct &SharedView)
uint64 GetStructHash64 (const FConstStructView &StructView)
uint64 GetStructHash64 (const FSharedStruct &SharedView)
uint64 GetStructHash64 (const FStructView &StructView)
uint64 GetStructHash64 (const UScriptStruct &ScriptStruct, const uint8 *StructMemory)
CityHash64-based struct hashing functions.
template<typename T>
const T * GetStructPtr (const UScriptStruct *ScriptStruct, const void *StructMemory)
Returns const pointer to the struct, or nullptr if cast is not valid.
template<typename T>
T * GetStructPtr (const UScriptStruct *ScriptStruct, void *StructMemory)
Returns pointer to the struct, or nullptr if cast is not valid.
template<typename T>
const T & GetStructRef (const UScriptStruct *ScriptStruct, const void *StructMemory)
Returns const reference to the struct, this assumes that all data is valid.
template<typename T>
T & GetStructRef (const UScriptStruct *ScriptStruct, void *StructMemory)
Returns reference to the struct, this assumes that all data is valid.
Typedef Documentation
EnableIfNotSharedInstancedOrViewStruct
template<typename T> using UE::StructUtils::EnableIfNotSharedInstancedOrViewStruct
Initial value:
 std::enable_if_t<!(std::is_same<FStructView, T>::value
        || std::is_same<FConstStructView, T>::value
        || std::is_same<FSharedStruct, T>::value
        || std::is_same<FConstSharedStruct, T>::value
        || std::is_same<FInstancedStruct, T>::value), T>
Definition at line 61 of file StructUtilsTypes.h.
EnableIfSharedInstancedOrViewStruct
template<typename T> using UE::StructUtils::EnableIfSharedInstancedOrViewStruct
Initial value:
 std::enable_if_t<std::is_same<FStructView, T>::value
        || std::is_same<FConstStructView, T>::value
        || std::is_same<FSharedStruct, T>::value
        || std::is_same<FConstSharedStruct, T>::value
        || std::is_same<FInstancedStruct, T>::value, T>
Definition at line 54 of file StructUtilsTypes.h.
Function Documentation
CalcMidIndexAndCount()
void UE::StructUtils::CalcMidIndexAndCount (int32 ArrayNum, int32 & InOutIndex, int32 & InOutCount) inline
Returns the middle part of an array or view by taking up to the given number of elements from the given position.
Based on TArrayView::Mid().
Definition at line 75 of file StructUtils.h.
References FMath::Clamp().
Referenced by FConstStructArrayView::Mid(), and FStructArrayView::Mid().
CheckStructType()
template<typename T> void UE::StructUtils::CheckStructType ()
Definition at line 11 of file StructUtils.h.
References TIsDerivedFrom< DerivedType, BaseType >::IsDerived.
Referenced by FStructSharedMemory::CreateArgs(), FConstStructView::Make(), FStructView::Make(), USTRUCT(), and USTRUCT().
CheckWrapperType()
template<typename T> void UE::StructUtils::CheckWrapperType ()
Definition at line 21 of file StructUtils.h.
References TIsDerivedFrom< DerivedType, BaseType >::IsDerived.
Referenced by USTRUCT().
GetAsUStruct() [1/2]
template<typename T> TEnableIf<!TIsDerivedFrom< T, UObject >::IsDerived, UScriptStruct * >::Type UE::StructUtils::GetAsUStruct ()
Definition at line 42 of file StructUtilsTypes.h.
Referenced by TTypeBitSetBase< TStructTypeBitSet, TBaseStruct, TUStructType, FStructTypeBitSet::FBitSetContainer >::GetBaseUStruct(), and TStructTypeBitSet< TBaseStruct, TStructTrackerWrapper, TUStructType >::GetTypeIndex().
GetAsUStruct() [2/2]
template<typename T> TEnableIf< TIsDerivedFrom< T, UObject >::IsDerived, UClass * >::Type UE::StructUtils::GetAsUStruct ()
Definition at line 48 of file StructUtilsTypes.h.
GetStructCrc32() [1/5]
uint32 UE::StructUtils::GetStructCrc32 (const FConstSharedStruct & SharedView, const uint32 CRC = 0) extern
GetStructCrc32() [2/5]
uint32 UE::StructUtils::GetStructCrc32 (const FConstStructView & StructView, const uint32 CRC = 0) extern
GetStructCrc32() [3/5]
uint32 UE::StructUtils::GetStructCrc32 (const FSharedStruct & SharedView, const uint32 CRC = 0) extern
GetStructCrc32() [4/5]
uint32 UE::StructUtils::GetStructCrc32 (const FStructView & StructView, const uint32 CRC = 0) extern
GetStructCrc32() [5/5]
uint32 UE::StructUtils::GetStructCrc32 (const UScriptStruct & ScriptStruct, const uint8 * StructMemory, const uint32 CRC = 0) extern
References ScriptStruct.
GetStructHash64() [1/5]
uint64 UE::StructUtils::GetStructHash64 (const FConstSharedStruct & SharedView) extern
GetStructHash64() [2/5]
uint64 UE::StructUtils::GetStructHash64 (const FConstStructView & StructView) extern
GetStructHash64() [3/5]
uint64 UE::StructUtils::GetStructHash64 (const FSharedStruct & SharedView) extern
GetStructHash64() [4/5]
uint64 UE::StructUtils::GetStructHash64 (const FStructView & StructView) extern
GetStructHash64() [5/5]
uint64 UE::StructUtils::GetStructHash64 (const UScriptStruct & ScriptStruct, const uint8 * StructMemory) extern
CityHash64-based struct hashing functions.
Note that these are relatively slow due to using either UScriptStruct.GetStructTypeHash (if implemented) or a serialization path.
References ScriptStruct.
GetStructPtr() [1/2]
template<typename T> const T * UE::StructUtils::GetStructPtr (const UScriptStruct * ScriptStruct, const void * StructMemory)
Returns const pointer to the struct, or nullptr if cast is not valid.
Definition at line 66 of file StructUtils.h.
References GetStructPtr(), and ScriptStruct.
GetStructPtr() [2/2]
template<typename T> T * UE::StructUtils::GetStructPtr (const UScriptStruct * ScriptStruct, void * StructMemory)
Returns pointer to the struct, or nullptr if cast is not valid.
Definition at line 45 of file StructUtils.h.
References TBaseStructureBase< T, bHasStaticStruct >::Get(), and ScriptStruct.
Referenced by FConstStructView::GetPtr(), FStructView::GetPtr(), TConstStructView< BaseStructT >::GetPtr(), TStructView< BaseStructT >::GetPtr(), FConstStructArrayView::GetPtrAt(), FStructArrayView::GetPtrAt(), GetStructPtr(), USTRUCT(), and USTRUCT().
GetStructRef() [1/2]
template<typename T> const T & UE::StructUtils::GetStructRef (const UScriptStruct * ScriptStruct, const void * StructMemory)
Returns const reference to the struct, this assumes that all data is valid.
Definition at line 59 of file StructUtils.h.
References GetStructRef(), and ScriptStruct.
GetStructRef() [2/2]
template<typename T> T & UE::StructUtils::GetStructRef (const UScriptStruct * ScriptStruct, void * StructMemory)
Returns reference to the struct, this assumes that all data is valid.
Definition at line 32 of file StructUtils.h.
References check, checkf, TBaseStructureBase< T, bHasStaticStruct >::Get(), ScriptStruct, and TEXT.
Referenced by FConstStructView::Get(), FStructView::Get(), TConstStructView< BaseStructT >::Get(), TStructView< BaseStructT >::Get(), FConstStructArrayView::GetAt(), FStructArrayView::GetAt(), GetStructRef(), USTRUCT(), and USTRUCT().