Unreal Engine 5.6 C++ API: LowLevelTasks Namespace Reference
LowLevelTasks Namespace Reference
Namespaces
namespace LocalQueue_Impl
namespace Private
namespace Tasks_Impl
namespace TTaskDelegate_Impl
Data Structures
struct FLowLevelTasksBlockAllocationTag
class FOversubscriptionScope
class FScheduler
class FSchedulerTls
class FTask
class TTaskDelegate
class TTaskDelegate< ReturnType(ParamTypes...), TotalSize >
Typedefs
template<typename NodeType>
using TAlignedArray = TArray<NodeType, TAlignedHeapAllocator<alignof(NodeType)>>
Enumerations
enum class ECancellationFlags : int8 { None = 0 << 0 , TryLaunchOnSuccess = 1 << 0 , PrelaunchCancellation = 1 << 1 , DefaultFlags = TryLaunchOnSuccess | PrelaunchCancellation }
enum class EQueuePreference { GlobalQueuePreference , LocalQueuePreference , DefaultPreference = LocalQueuePreference }
enum class ETaskPriority : int8 {
High , Normal , Default = Normal , ForegroundCount ,
BackgroundHigh = ForegroundCount , BackgroundNormal , BackgroundLow , Count ,
Inherit
}
Functions
DECLARE_LOG_CATEGORY_EXTERN (LowLevelTasks, Log, All)
DECLARE_TS_MULTICAST_DELEGATE (FOversubscriptionLimitReached)
FORCEINLINE_DEBUGGABLE bool DoReserveWorkUntil (FReserveScheduler::FConditional &&Condition)
ENUM_CLASS_FLAGS(ECancellationFlags) enum class ETaskFlags ENUM_CLASS_FLAGS(ETaskFlags) enum class ETaskState ENUM_CLASS_FLAGS (ETaskState) template< typename Type
const TCHAR * ToString (ETaskPriority Priority)
bool ToTaskPriority (const TCHAR *PriorityStr, ETaskPriority &OutPriority)
FORCEINLINE_DEBUGGABLE bool TryLaunch (FTask &Task, EQueuePreference QueuePreference=EQueuePreference::DefaultPreference, bool bWakeUpWorker=true)
template<typename NodeType>
class UE_DEPRECATED (5.5, "This class will be removed.") TEventStack
UE_DEPRECATED (5.5, "This method will be removed.") FORCEINLINE_DEBUGGABLE void BusyWaitForTask(const FTask &Task
Variables
ENUM_CLASS_FLAGS(ECancellationFlags) enum class ETaskFlags ENUM_CLASS_FLAGS(ETaskFlags) enum class ETaskState void(Type::* DeleteFunction)()> class TDeleter
Typedef Documentation
TAlignedArray
template<typename NodeType> using LowLevelTasks::TAlignedArray = TArray<NodeType, TAlignedHeapAllocator<alignof(NodeType)>>
Definition at line 15 of file TaskShared.h.
Enumeration Type Documentation
ECancellationFlags
enum class LowLevelTasks::ECancellationFlags : int8 strong
Enumerator
None
TryLaunchOnSuccess
PrelaunchCancellation
DefaultFlags
Definition at line 83 of file Task.h.
EQueuePreference
enum class LowLevelTasks::EQueuePreference strong
Enumerator
GlobalQueuePreference
LocalQueuePreference
DefaultPreference
Definition at line 31 of file Scheduler.h.
ETaskPriority
enum class LowLevelTasks::ETaskPriority : int8 strong
Enumerator
High
Normal
Default
ForegroundCount
BackgroundHigh
BackgroundNormal
BackgroundLow
Count
Inherit
Definition at line 17 of file Task.h.
Function Documentation
DECLARE_LOG_CATEGORY_EXTERN()
LowLevelTasks::DECLARE_LOG_CATEGORY_EXTERN (LowLevelTasks , Log , All)
References All, and Log.
DECLARE_TS_MULTICAST_DELEGATE()
LowLevelTasks::DECLARE_TS_MULTICAST_DELEGATE (FOversubscriptionLimitReached)
DoReserveWorkUntil()
FORCEINLINE_DEBUGGABLE bool LowLevelTasks::DoReserveWorkUntil (FReserveScheduler::FConditional && Condition)
Definition at line 66 of file ReserveScheduler.h.
References FORCEINLINE_DEBUGGABLE, and MoveTemp().
ENUM_CLASS_FLAGS()
ENUM_CLASS_FLAGS(ECancellationFlags) enum class ETaskFlags ENUM_CLASS_FLAGS(ETaskFlags) enum class ETaskState LowLevelTasks::ENUM_CLASS_FLAGS (ETaskState)
ToString()
const TCHAR * LowLevelTasks::ToString (ETaskPriority Priority) inline
Definition at line 30 of file Task.h.
References Count, and TEXT.
Referenced by ToTaskPriority().
ToTaskPriority()
bool LowLevelTasks::ToTaskPriority (const TCHAR * PriorityStr, ETaskPriority & OutPriority) inline
Definition at line 48 of file Task.h.
References BackgroundHigh, BackgroundLow, BackgroundNormal, High, Normal, TCString< TCHAR >::Stricmp(), and ToString().
TryLaunch()
FORCEINLINE_DEBUGGABLE bool LowLevelTasks::TryLaunch (FTask & Task, EQueuePreference QueuePreference = EQueuePreference::DefaultPreference, bool bWakeUpWorker = true)
Definition at line 353 of file Scheduler.h.
References DefaultPreference, FORCEINLINE_DEBUGGABLE, LowLevelTasks::FScheduler::Get(), and LowLevelTasks::FScheduler::TryLaunch().
Referenced by ENUM_CLASS_FLAGS(), and AwaitableTask_Detail::TPromise< ReturnType, CallableType >::TryLaunch().
UE_DEPRECATED() [1/2]
template<typename NodeType> class LowLevelTasks::UE_DEPRECATED (5. 5, "This class will be removed.")
Definition at line 1 of file Scheduler.h.
UE_DEPRECATED() [2/2]
LowLevelTasks::UE_DEPRECATED (5. 5, "This method will be removed.") const &
References FORCEINLINE_DEBUGGABLE, LowLevelTasks::FScheduler::Get(), PRAGMA_DISABLE_DEPRECATION_WARNINGS, and PRAGMA_ENABLE_DEPRECATION_WARNINGS.
Variable Documentation
DeleteFunction
ENUM_CLASS_FLAGS(ECancellationFlags) enum class ETaskFlags ENUM_CLASS_FLAGS(ETaskFlags) enum class ETaskState void(Type::* LowLevelTasks::DeleteFunction) ()> class TDeleter ()
Definition at line 151 of file Task.h.