Unreal Engine 5.6 C++ API: AnimationMath Namespace Reference
AnimationMath Namespace Reference
Functions
FORCEINLINE FQuat Damper (const FQuat &CurrentRotation, const FQuat &TargetRotation, float HalfLife, float DeltaTime, float Eps=1e-5f)
FORCEINLINE FQuat QuatFromScaledAngleAxis (FVector V)
FORCEINLINE FVector QuatToScaledAngleAxis (const FQuat &Q)
template<typename T>
FORCEINLINE void SimpleSpringDamper (T &x, T &v, T x_goal, float halflife, float dt)
FORCEINLINE void SimpleSpringDamperQuat (FQuat &InOutRotation, FVector &InOutAngularVelocity, const FQuat &TargetRotation, float HalfLife, float DeltaTime)
FORCEINLINE float SpringHalfLifeToDamping (float HalfLife, float eps=1e-5f)
Function Documentation
Damper()
FORCEINLINE FQuat AnimationMath::Damper (const FQuat & CurrentRotation, const FQuat & TargetRotation, float HalfLife, float DeltaTime, float Eps = 1e-5f)
Definition at line 71 of file AnimationMath.h.
References DeltaTime, FORCEINLINE, FMath::InvExpApprox(), and UE::Math::TQuat< double >::Slerp().
QuatFromScaledAngleAxis()
FORCEINLINE FQuat AnimationMath::QuatFromScaledAngleAxis (FVector V)
Definition at line 24 of file AnimationMath.h.
References UE::Math::TQuat< T >::Exp(), FORCEINLINE, FVector, UE::Math::TVector< T >::X, UE::Math::TVector< T >::Y, and UE::Math::TVector< T >::Z.
Referenced by SimpleSpringDamperQuat().
QuatToScaledAngleAxis()
FORCEINLINE FVector AnimationMath::QuatToScaledAngleAxis (const FQuat & Q)
Definition at line 18 of file AnimationMath.h.
References FORCEINLINE, FVector, UE::Math::TQuat< T >::Log(), UE::Math::TQuat< T >::X, UE::Math::TQuat< T >::Y, and UE::Math::TQuat< T >::Z.
Referenced by SimpleSpringDamperQuat().
SimpleSpringDamper()
template<typename T> FORCEINLINE void AnimationMath::SimpleSpringDamper (T & x, T & v, T x_goal, float halflife, float dt)
Definition at line 33 of file AnimationMath.h.
References FORCEINLINE, FMath::InvExpApprox(), and SpringHalfLifeToDamping().
SimpleSpringDamperQuat()
FORCEINLINE void AnimationMath::SimpleSpringDamperQuat (FQuat & InOutRotation, FVector & InOutAngularVelocity, const FQuat & TargetRotation, float HalfLife, float DeltaTime)
Definition at line 50 of file AnimationMath.h.
References DeltaTime, UE::Math::TQuat< T >::EnforceShortestArcWith(), FORCEINLINE, FVector, UE::Math::TQuat< double >::Identity, UE::Math::TQuat< T >::Inverse(), FMath::InvExpApprox(), QuatFromScaledAngleAxis(), QuatToScaledAngleAxis(), and SpringHalfLifeToDamping().
SpringHalfLifeToDamping()
FORCEINLINE float AnimationMath::SpringHalfLifeToDamping (float HalfLife, float eps = 1e-5f)
Definition at line 13 of file AnimationMath.h.
References FORCEINLINE.
Referenced by SimpleSpringDamper(), and SimpleSpringDamperQuat().