Unreal Engine 5.6 C++ API: Metasound::MetasoundVariableNodesPrivate Namespace Reference
Metasound::MetasoundVariableNodesPrivate Namespace Reference
Data Structures
class TVariableAccessorOperator
Operator for providing inline access to a variable.
class TVariableDeferredAccessorOperator
Operator for providing delayed access to a variable.
class TVariableMutatorOperator
Operator for providing setting a variable.
class TVariableOperator
Functions
METASOUNDGRAPHCORE_API bool IsSupportedVertexData (const IDataReference &InCurrentVariableRef, const FInputVertexInterfaceData &InNew)
Function Documentation
IsSupportedVertexData()
METASOUNDGRAPHCORE_API bool Metasound::MetasoundVariableNodesPrivate::IsSupportedVertexData (const IDataReference & InCurrentVariableRef, const FInputVertexInterfaceData & InNew)
Referenced by Metasound::MetasoundVariableNodesPrivate::TVariableAccessorOperator< DataType >::BindInputs(), Metasound::MetasoundVariableNodesPrivate::TVariableDeferredAccessorOperator< DataType >::BindInputs(), and Metasound::MetasoundVariableNodesPrivate::TVariableMutatorOperator< DataType >::BindInputs().