Unreal Engine 5.6 C++ API: MeshTransforms Namespace Reference
MeshTransforms Namespace Reference
Utility functions for applying transformations to meshes.
Enumerations
enum class ETransformAttributes {
Positions = 1 << 0 , VertexNormals = 1 << 1 , Normals = 1 << 2 , Tangents = 1 << 3 ,
SculptLayers = 1 << 4 , All = Positions | VertexNormals | Normals | Tangents | SculptLayers
}
Functions
GEOMETRYCORE_API void ApplyTransform (FDynamicMesh3 &Mesh, const FTransformSRT3d &Transform, bool bReverseOrientationIfNeeded=false, ETransformAttributes TransformAttributes=ETransformAttributes::All)
Apply given Transform to a Mesh.
GEOMETRYCORE_API void ApplyTransform (FDynamicMesh3 &Mesh, TFunctionRef< FVector3d(const FVector3d &)> PositionTransform, TFunctionRef< FVector3f(const FVector3f &)> NormalTransform)
Apply given Transform to a Mesh.
GEOMETRYCORE_API void ApplyTransform (FDynamicMesh3 &Mesh, TFunctionRef< FVector3d(const FVector3d &)> PositionTransform, TFunctionRef< FVector3f(const FVector3f &)> NormalTransform, TFunctionRef< FVector3f(const FVector3f &)> TangentTransform, ETransformAttributes TransformAttributes=ETransformAttributes::All)
Apply given Transform to a Mesh.
GEOMETRYCORE_API void ApplyTransformInverse (FDynamicMesh3 &Mesh, const FTransformSRT3d &Transform, bool bReverseOrientationIfNeeded=false, ETransformAttributes TransformAttributes=ETransformAttributes::All)
Apply inverse of given Transform to a Mesh.
ENUM_CLASS_FLAGS (ETransformAttributes)
GEOMETRYCORE_API void FrameCoordsToWorld (FDynamicMesh3 &Mesh, const FFrame3d &Frame, ETransformAttributes TransformAttributes=ETransformAttributes::All)
Transform Mesh out of local coordinates of Frame.
GEOMETRYCORE_API void ReverseOrientationIfNeeded (FDynamicMesh3 &Mesh, const FTransformSRT3d &Transform)
If applying Transform would invert Mesh w/ a negative scale, then invert Mesh's triangle orientations.
GEOMETRYCORE_API void Rotate (FDynamicMesh3 &Mesh, const FRotator &Rotation, const FVector3d &RotationOrigin, ETransformAttributes TransformAttributes=ETransformAttributes::All)
Apply Rotation to the Mesh, relative to the given RotationOrigin.
GEOMETRYCORE_API void Scale (FDynamicMesh3 &Mesh, const FVector3d &Scale, const FVector3d &Origin, bool bReverseOrientationIfNeeded, ETransformAttributes TransformAttributes)
Apply Scale to Mesh, relative to given Origin.
GEOMETRYCORE_API void Scale (FDynamicMesh3 &Mesh, const FVector3d &Scale, const FVector3d &Origin, bool bReverseOrientationIfNeeded=false, bool bOnlyPositions=false)
Apply Scale to Mesh, relative to given Origin.
GEOMETRYCORE_API void Translate (FDynamicMesh3 &Mesh, const FVector3d &Translation, ETransformAttributes TransformAttributes=ETransformAttributes::All)
Apply Translation to the Mesh.
GEOMETRYCORE_API void WorldToFrameCoords (FDynamicMesh3 &Mesh, const FFrame3d &Frame, ETransformAttributes TransformAttributes=ETransformAttributes::All)
Transform Mesh into local coordinates of Frame.
Detailed Description
Utility functions for applying transformations to meshes.
Enumeration Type Documentation
ETransformAttributes
enum class MeshTransforms::ETransformAttributes strong
Enumerator
Positions
VertexNormals
Normals
Tangents
SculptLayers
All
Definition at line 25 of file MeshTransforms.h.
Function Documentation
ApplyTransform() [1/3]
GEOMETRYCORE_API void MeshTransforms::ApplyTransform (FDynamicMesh3 & Mesh, const FTransformSRT3d & Transform, bool bReverseOrientationIfNeeded = false, ETransformAttributes TransformAttributes = ETransformAttributes::All)
Apply given Transform to a Mesh.
Parameters
bReverseOrientationIfNeeded If the Transform inverts the mesh with negative scale, also invert the triangle orientations
TransformAttributes Bitflag enum specifying which attributes to transform
References All, UE::Geometry::Mesh, and UE::Geometry::Transform.
ApplyTransform() [2/3]
GEOMETRYCORE_API void MeshTransforms::ApplyTransform (FDynamicMesh3 & Mesh, TFunctionRef< FVector3d(const FVector3d &)> PositionTransform, TFunctionRef< FVector3f(const FVector3f &)> NormalTransform)
Apply given Transform to a Mesh.
Modifies Vertex Positions and Normals, and any Per-Triangle Normal Overlays
References UE::Geometry::Mesh.
ApplyTransform() [3/3]
GEOMETRYCORE_API void MeshTransforms::ApplyTransform (FDynamicMesh3 & Mesh, TFunctionRef< FVector3d(const FVector3d &)> PositionTransform, TFunctionRef< FVector3f(const FVector3f &)> NormalTransform, TFunctionRef< FVector3f(const FVector3f &)> TangentTransform, ETransformAttributes TransformAttributes = ETransformAttributes::All)
Apply given Transform to a Mesh.
Parameters
TransformAttributes Bitflag enum specifying which attributes to transform
References All, and UE::Geometry::Mesh.
ApplyTransformInverse()
GEOMETRYCORE_API void MeshTransforms::ApplyTransformInverse (FDynamicMesh3 & Mesh, const FTransformSRT3d & Transform, bool bReverseOrientationIfNeeded = false, ETransformAttributes TransformAttributes = ETransformAttributes::All)
Apply inverse of given Transform to a Mesh.
Modifies Vertex Positions and Normals, and any Per-Triangle Normal Overlays
Parameters
bReverseOrientationIfNeeded If the Transform inverts the mesh with negative scale, also invert the triangle orientations
TransformAttributes Bitflag enum specifying which attributes to transform
References All, UE::Geometry::Mesh, and UE::Geometry::Transform.
ENUM_CLASS_FLAGS()
MeshTransforms::ENUM_CLASS_FLAGS (ETransformAttributes)
FrameCoordsToWorld()
GEOMETRYCORE_API void MeshTransforms::FrameCoordsToWorld (FDynamicMesh3 & Mesh, const FFrame3d & Frame, ETransformAttributes TransformAttributes = ETransformAttributes::All)
Transform Mesh out of local coordinates of Frame.
Parameters
TransformAttributes Bitflag enum specifying which attributes to transform
References All, and UE::Geometry::Mesh.
ReverseOrientationIfNeeded()
GEOMETRYCORE_API void MeshTransforms::ReverseOrientationIfNeeded (FDynamicMesh3 & Mesh, const FTransformSRT3d & Transform)
If applying Transform would invert Mesh w/ a negative scale, then invert Mesh's triangle orientations.
Note: Does not apply the transform.
References UE::Geometry::Mesh, and UE::Geometry::Transform.
Rotate()
GEOMETRYCORE_API void MeshTransforms::Rotate (FDynamicMesh3 & Mesh, const FRotator & Rotation, const FVector3d & RotationOrigin, ETransformAttributes TransformAttributes = ETransformAttributes::All)
Apply Rotation to the Mesh, relative to the given RotationOrigin.
Parameters
TransformAttributes Bitflag enum specifying which attributes to transform
References All, UE::Geometry::Mesh, and Rotation.
Scale() [1/2]
GEOMETRYCORE_API void MeshTransforms::Scale (FDynamicMesh3 & Mesh, const FVector3d & Scale, const FVector3d & Origin, bool bReverseOrientationIfNeeded, ETransformAttributes TransformAttributes)
Apply Scale to Mesh, relative to given Origin.
Correctly updates normals/tangents as needed (unless TransformAttributes flags are set not to update them).
Parameters
bReverseOrientationIfNeeded If negative scaling inverts the mesh, also invert the triangle orientations
TransformAttributes Bitflag enum specifying which attributes to transform
References UE::Geometry::Mesh, UE::Geometry::Origin, and Scale().
Scale() [2/2]
GEOMETRYCORE_API void MeshTransforms::Scale (FDynamicMesh3 & Mesh, const FVector3d & Scale, const FVector3d & Origin, bool bReverseOrientationIfNeeded = false, bool bOnlyPositions = false)
Apply Scale to Mesh, relative to given Origin.
Correctly updates normals/tangents as needed (unless bOnlyPositions is true).
Parameters
bReverseOrientationIfNeeded If negative scaling inverts the mesh, also invert the triangle orientations
bOnlyPositions If true, only apply scale positions and do not affect normals/tangents
References UE::Geometry::Mesh, UE::Geometry::Origin, and Scale().
Referenced by Scale(), and Scale().
Translate()
GEOMETRYCORE_API void MeshTransforms::Translate (FDynamicMesh3 & Mesh, const FVector3d & Translation, ETransformAttributes TransformAttributes = ETransformAttributes::All)
Apply Translation to the Mesh.
Parameters
TransformAttributes Bitflag enum specifying which attributes to transform
References All, UE::Geometry::Mesh, and Translation.
WorldToFrameCoords()
GEOMETRYCORE_API void MeshTransforms::WorldToFrameCoords (FDynamicMesh3 & Mesh, const FFrame3d & Frame, ETransformAttributes TransformAttributes = ETransformAttributes::All)
Transform Mesh into local coordinates of Frame.
Parameters
TransformAttributes Bitflag enum specifying which attributes to transform
References All, and UE::Geometry::Mesh.