Unreal Engine 5.6 C++ API: PhysicsAssetRender Namespace Reference
PhysicsAssetRender Namespace Reference
Factory class for FPhysicsAssetRenderSettings.
Typedefs
using COMAccessorFunctionFn = TFunctionRef< TPair< bool, FVector >(const int32) >
using CreateBodyHitProxyFn = TFunctionRef< HHitProxy* (const int32 BodyIndex, const EAggCollisionShape::Type PrimitiveType, const int32 PrimitiveIndex) >
using CreateCoMHitProxyFn = TFunctionRef< HHitProxy* (const int32 InBodyIndex) >
using CreateConstraintHitProxyFn = TFunctionRef< HHitProxy* (const int32 InConstraintIndex) >
template<typename TReturnType>
using GetPrimitiveRef = TFunctionRef< TReturnType (const int32 BodyIndex, const EAggCollisionShape::Type PrimitiveType, const int32 PrimitiveIndex, const FPhysicsAssetRenderSettings& Settings) >
using GetPrimitiveTransformRef = TFunctionRef< FTransform (const UPhysicsAsset* PhysicsAsset, const FTransform& BoneTM, const int32 BodyIndex, const EAggCollisionShape::Type PrimType, const int32 PrimIndex, const float Scale) >
using IsSelectedFn = TFunction< bool(const uint32) >
Functions
PERSONA_API void DebugDraw (class USkeletalMeshComponent *const SkeletalMeshComponent, class UPhysicsAsset *const PhysicsAsset, FPrimitiveDrawInterface *PDI)
Debug draw Physics Asset bodies and constraints using the default callbacks.
PERSONA_API void DebugDrawBodies (class USkeletalMeshComponent *const SkeletalMeshComponent, class UPhysicsAsset *const PhysicsAsset, FPrimitiveDrawInterface *PDI, GetPrimitiveRef< FColor > GetPrimitiveColor, GetPrimitiveRef< class UMaterialInterface * > GetPrimitiveMaterial, GetPrimitiveTransformRef GetPrimitiveTransform, CreateBodyHitProxyFn CreateHitProxy)
Debug draw Physics Asset bodies using the supplied custom callbacks.
PERSONA_API void DebugDrawCenterOfMass (USkeletalMeshComponent *const SkeletalMeshComponent, class UPhysicsAsset *const PhysicsAsset, FPrimitiveDrawInterface *PDI, TFunctionRef< FVector(const uint32) > GetCoMPosition, TFunctionRef< bool(const uint32) > IsSelected, TFunctionRef< bool(const uint32) > IsHidden, CreateCoMHitProxyFn CreateHitProxy)
Debug draw the Center of Masses for all bodies in the supplied Skeletal Mesh.
PERSONA_API void DebugDrawConstraints (class USkeletalMeshComponent *const SkeletalMeshComponent, class UPhysicsAsset *const PhysicsAsset, FPrimitiveDrawInterface *PDI, IsSelectedFn IsSelected, const bool bRunningSimulation, CreateConstraintHitProxyFn CreateHitProxy)
Debug draw Physics Asset constraints using the supplied custom callbacks.
PERSONA_API FColor GetPrimitiveColor (const int32 BodyIndex, const EAggCollisionShape::Type PrimitiveType, const int32 PrimitiveIndex, const FPhysicsAssetRenderSettings &Settings)
PERSONA_API class UMaterialInterface * GetPrimitiveMaterial (const int32 BodyIndex, const EAggCollisionShape::Type PrimitiveType, const int32 PrimitiveIndex, const FPhysicsAssetRenderSettings &Settings)
PERSONA_API FTransform GetPrimitiveTransform (const UPhysicsAsset *PhysicsAsset, const FTransform &BoneTM, const int32 BodyIndex, const EAggCollisionShape::Type PrimType, const int32 PrimIndex, const float Scale)
Default callbacks used by DebugDraw.
Detailed Description
Factory class for FPhysicsAssetRenderSettings.
Namespace containing functions for debug draw of Physics Assets in the editor viewport.
Typedef Documentation
COMAccessorFunctionFn
using PhysicsAssetRender::COMAccessorFunctionFn = TFunctionRef< TPair< bool, FVector >(const int32) >
Definition at line 222 of file PhysicsAssetRenderUtils.h.
CreateBodyHitProxyFn
using PhysicsAssetRender::CreateBodyHitProxyFn = TFunctionRef< HHitProxy* (const int32 BodyIndex, const EAggCollisionShape::Type PrimitiveType, const int32 PrimitiveIndex) >
Definition at line 219 of file PhysicsAssetRenderUtils.h.
CreateCoMHitProxyFn
using PhysicsAssetRender::CreateCoMHitProxyFn = TFunctionRef< HHitProxy* (const int32 InBodyIndex) >
Definition at line 221 of file PhysicsAssetRenderUtils.h.
CreateConstraintHitProxyFn
using PhysicsAssetRender::CreateConstraintHitProxyFn = TFunctionRef< HHitProxy* (const int32 InConstraintIndex) >
Definition at line 220 of file PhysicsAssetRenderUtils.h.
GetPrimitiveRef
template<typename TReturnType> using PhysicsAssetRender::GetPrimitiveRef = TFunctionRef< TReturnType (const int32 BodyIndex, const EAggCollisionShape::Type PrimitiveType, const int32 PrimitiveIndex, const FPhysicsAssetRenderSettings& Settings) >
Definition at line 217 of file PhysicsAssetRenderUtils.h.
GetPrimitiveTransformRef
using PhysicsAssetRender::GetPrimitiveTransformRef = TFunctionRef< FTransform (const UPhysicsAsset* PhysicsAsset, const FTransform& BoneTM, const int32 BodyIndex, const EAggCollisionShape::Type PrimType, const int32 PrimIndex, const float Scale) >
Definition at line 218 of file PhysicsAssetRenderUtils.h.
IsSelectedFn
using PhysicsAssetRender::IsSelectedFn = TFunction< bool(const uint32) >
Definition at line 223 of file PhysicsAssetRenderUtils.h.
Function Documentation
DebugDraw()
PERSONA_API void PhysicsAssetRender::DebugDraw (class USkeletalMeshComponent *const SkeletalMeshComponent, class UPhysicsAsset *const PhysicsAsset, FPrimitiveDrawInterface * PDI)
Debug draw Physics Asset bodies and constraints using the default callbacks.
References DebugDraw().
Referenced by DebugDraw().
DebugDrawBodies()
PERSONA_API void PhysicsAssetRender::DebugDrawBodies (class USkeletalMeshComponent *const SkeletalMeshComponent, class UPhysicsAsset *const PhysicsAsset, FPrimitiveDrawInterface * PDI, GetPrimitiveRef< FColor > GetPrimitiveColor, GetPrimitiveRef< class UMaterialInterface * > GetPrimitiveMaterial, GetPrimitiveTransformRef GetPrimitiveTransform, CreateBodyHitProxyFn CreateHitProxy)
Debug draw Physics Asset bodies using the supplied custom callbacks.
References DebugDrawBodies(), GetPrimitiveColor(), GetPrimitiveMaterial(), and GetPrimitiveTransform().
Referenced by DebugDrawBodies().
DebugDrawCenterOfMass()
PERSONA_API void PhysicsAssetRender::DebugDrawCenterOfMass (USkeletalMeshComponent *const SkeletalMeshComponent, class UPhysicsAsset *const PhysicsAsset, FPrimitiveDrawInterface * PDI, TFunctionRef< FVector(const uint32) > GetCoMPosition, TFunctionRef< bool(const uint32) > IsSelected, TFunctionRef< bool(const uint32) > IsHidden, CreateCoMHitProxyFn CreateHitProxy)
Debug draw the Center of Masses for all bodies in the supplied Skeletal Mesh.
References DebugDrawCenterOfMass().
Referenced by DebugDrawCenterOfMass().
DebugDrawConstraints()
PERSONA_API void PhysicsAssetRender::DebugDrawConstraints (class USkeletalMeshComponent *const SkeletalMeshComponent, class UPhysicsAsset *const PhysicsAsset, FPrimitiveDrawInterface * PDI, IsSelectedFn IsSelected, const bool bRunningSimulation, CreateConstraintHitProxyFn CreateHitProxy)
Debug draw Physics Asset constraints using the supplied custom callbacks.
References DebugDrawConstraints().
Referenced by DebugDrawConstraints().
GetPrimitiveColor()
PERSONA_API FColor PhysicsAssetRender::GetPrimitiveColor (const int32 BodyIndex, const EAggCollisionShape::Type PrimitiveType, const int32 PrimitiveIndex, const FPhysicsAssetRenderSettings & Settings)
References GetPrimitiveColor().
Referenced by DebugDrawBodies(), and GetPrimitiveColor().
GetPrimitiveMaterial()
PERSONA_API class UMaterialInterface * PhysicsAssetRender::GetPrimitiveMaterial (const int32 BodyIndex, const EAggCollisionShape::Type PrimitiveType, const int32 PrimitiveIndex, const FPhysicsAssetRenderSettings & Settings)
References GetPrimitiveMaterial().
Referenced by DebugDrawBodies(), and GetPrimitiveMaterial().
GetPrimitiveTransform()
PERSONA_API FTransform PhysicsAssetRender::GetPrimitiveTransform (const UPhysicsAsset * PhysicsAsset, const FTransform & BoneTM, const int32 BodyIndex, const EAggCollisionShape::Type PrimType, const int32 PrimIndex, const float Scale)
Default callbacks used by DebugDraw.
References GetPrimitiveTransform(), and Scale.
Referenced by DebugDrawBodies(), and GetPrimitiveTransform().