Unreal Engine 5.6 C++ API: UE::Core::Private::FormatStringSan Namespace Reference
UE::Core::Private::FormatStringSan Namespace Reference
Data Structures
struct FResult
struct TAtArgPos
struct TCheckedFormatStringPrivate
struct TCheckFormatString
struct TCheckFormatString< CharType >
struct TCheckFormatString< CharType, Arg, Args... >
Enumerations
enum class EFormatStringSanStatus {
Ok , SNeedsDereferencedNarrowString , SNeedsDereferencedWideString , SNeedsPtrButGotChar ,
SNeedsNarrowCharPtrArg , SNeedsWideCharPtrArg , SNeedsNarrowCharPtrArgButGotWide , SNeedsWideCharPtrArgButGotNarrow ,
CapitalSNeedsDereferencedNarrowString , CapitalSNeedsDereferencedWideString , CapitalSNeedsPtrButGotChar , CapitalSNeedsNarrowCharPtrArg ,
CapitalSNeedsWideCharPtrArg , CapitalSNeedsNarrowCharPtrArgButGotWide , CapitalSNeedsWideCharPtrArgButGotNarrow , HSNeedsDereferencedNarrowString ,
HSNeedsPtrButGotChar , HSNeedsNarrowCharPtrArg , HSNeedsNarrowCharPtrArgButGotWideOnNarrowString , HSNeedsNarrowCharPtrArgButGotWideOnWideString ,
LSNeedsDereferencedWideString , LSNeedsPtrButGotChar , LSNeedsWideCharPtrArg , LSNeedsWideCharPtrArgButGotNarrowOnNarrowString ,
LSNeedsWideCharPtrArgButGotNarrowOnWideString , IncompleteFormatSpecifierOrUnescapedPercent , CNeedsCharArgOnNarrowString , CNeedsCharArgOnWideString ,
PNeedsPointerArg , FNeedsFloatOrDoubleArg , InvalidFormatSpec , NotEnoughArguments ,
NotEnoughSpecifiers , DNeedsIntegerArg , ZNeedsIntegerArg , ZNeedsIntegerSpec ,
LNeedsIntegerArg , HNeedsIntegerArg , HHNeedsIntegerSpec , HHNeedsIntegerArg ,
LLNeedsIntegerSpec , LLNeedsIntegerArg , I64BadSpec , I64NeedsIntegerArg ,
DynamicLengthSpecNeedsIntegerArg
}
Functions
template<EFormatStringSanStatus Err, typename T>
constexpr void AssertFormatStatus ()
template<typename CharType>
constexpr bool CharIsDigit (CharType Char)
template<typename CharType>
constexpr bool CharIsIntegerFormatSpecifier (CharType Char)
template<typename CharType, typename... Ts>
constexpr TCheckFormatString< CharType, std::decay_t< Ts >... > GetFmtArgCheckerType (const CharType *, Ts...)
template<typename CharType>
constexpr const CharType * SkipInteger (const CharType *Fmt)
Variables
template<typename T>
constexpr bool bIsAConstString
template<typename T>
constexpr bool TIsFloatOrDouble_V = std::is_same_v<float, T> || std::is_same_v<double, T>
template<typename T>
constexpr bool TIsIntegralEnum_V = std::is_enum_v<T> || TIsTEnumAsByte_V<T>
Enumeration Type Documentation
EFormatStringSanStatus
enum class UE::Core::Private::FormatStringSan::EFormatStringSanStatus strong
Enumerator
Ok
SNeedsDereferencedNarrowString
SNeedsDereferencedWideString
SNeedsPtrButGotChar
SNeedsNarrowCharPtrArg
SNeedsWideCharPtrArg
SNeedsNarrowCharPtrArgButGotWide
SNeedsWideCharPtrArgButGotNarrow
CapitalSNeedsDereferencedNarrowString
CapitalSNeedsDereferencedWideString
CapitalSNeedsPtrButGotChar
CapitalSNeedsNarrowCharPtrArg
CapitalSNeedsWideCharPtrArg
CapitalSNeedsNarrowCharPtrArgButGotWide
CapitalSNeedsWideCharPtrArgButGotNarrow
HSNeedsDereferencedNarrowString
HSNeedsPtrButGotChar
HSNeedsNarrowCharPtrArg
HSNeedsNarrowCharPtrArgButGotWideOnNarrowString
HSNeedsNarrowCharPtrArgButGotWideOnWideString
LSNeedsDereferencedWideString
LSNeedsPtrButGotChar
LSNeedsWideCharPtrArg
LSNeedsWideCharPtrArgButGotNarrowOnNarrowString
LSNeedsWideCharPtrArgButGotNarrowOnWideString
IncompleteFormatSpecifierOrUnescapedPercent
CNeedsCharArgOnNarrowString
CNeedsCharArgOnWideString
PNeedsPointerArg
FNeedsFloatOrDoubleArg
InvalidFormatSpec
NotEnoughArguments
NotEnoughSpecifiers
DNeedsIntegerArg
ZNeedsIntegerArg
ZNeedsIntegerSpec
LNeedsIntegerArg
HNeedsIntegerArg
HHNeedsIntegerSpec
HHNeedsIntegerArg
LLNeedsIntegerSpec
LLNeedsIntegerArg
I64BadSpec
I64NeedsIntegerArg
DynamicLengthSpecNeedsIntegerArg
Definition at line 43 of file FormatStringSan.h.
Function Documentation
AssertFormatStatus()
template<EFormatStringSanStatus Err, typename T> void UE::Core::Private::FormatStringSan::AssertFormatStatus () constexpr
Definition at line 53 of file FormatStringSan.h.
CharIsDigit()
template<typename CharType> bool UE::Core::Private::FormatStringSan::CharIsDigit (CharType Char) constexpr
Definition at line 88 of file FormatStringSan.h.
Referenced by UE::Core::Private::FormatStringSan::TCheckFormatString< CharType, Arg, Args... >::Check().
CharIsIntegerFormatSpecifier()
template<typename CharType> bool UE::Core::Private::FormatStringSan::CharIsIntegerFormatSpecifier (CharType Char) constexpr
Definition at line 104 of file FormatStringSan.h.
Referenced by UE::Core::Private::FormatStringSan::TCheckFormatString< CharType, Arg, Args... >::Check().
GetFmtArgCheckerType()
template<typename CharType, typename... Ts> TCheckFormatString< CharType, std::decay_t< Ts >... > UE::Core::Private::FormatStringSan::GetFmtArgCheckerType (const CharType * , Ts...) constexpr
SkipInteger()
template<typename CharType> const CharType * UE::Core::Private::FormatStringSan::SkipInteger (const CharType * Fmt) constexpr
Definition at line 94 of file FormatStringSan.h.
Referenced by UE::Core::Private::FormatStringSan::TCheckFormatString< CharType, Arg, Args... >::Check().
Variable Documentation
bIsAConstString
template<typename T> bool UE::Core::Private::FormatStringSan::bIsAConstString inline constexpr
Initial value:
=
               !(std::is_convertible_v<T, char*> || std::is_convertible_v<T, TCHAR*>)
            && (std::is_convertible_v<T, const char*> || std::is_convertible_v<T, const TCHAR*>)
Definition at line 39 of file FormatStringSan.h.
TIsFloatOrDouble_V
template<typename T> bool UE::Core::Private::FormatStringSan::TIsFloatOrDouble_V = std::is_same_v<float, T> || std::is_same_v<double, T> inline constexpr
Definition at line 76 of file FormatStringSan.h.
Referenced by UE::Core::Private::FormatStringSan::TCheckFormatString< CharType, Arg, Args... >::Check().
TIsIntegralEnum_V
template<typename T> bool UE::Core::Private::FormatStringSan::TIsIntegralEnum_V = std::is_enum_v<T> || TIsTEnumAsByte_V<T> inline constexpr
Definition at line 79 of file FormatStringSan.h.
Referenced by UE::Core::Private::FormatStringSan::TCheckFormatString< CharType, Arg, Args... >::Check(), and UE::Core::Private::FormatStringSan::TCheckFormatString< CharType, Arg, Args... >::HandleDynamicLengthSpecifier().