Unreal Engine 5.6 C++ API: Freeze Namespace Reference
Freeze Namespace Reference
Functions
uint32 AppendHash (const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams, FSHA1 &Hasher)
uint32 AppendHashForNameAndSize (const TCHAR *Name, uint32 Size, FSHA1 &Hasher)
uint32 AppendHashPair (const FTypeLayoutDesc &KeyTypeDesc, const FTypeLayoutDesc &ValueTypeDesc, const FPlatformTypeLayoutParameters &LayoutParams, FSHA1 &Hasher)
void ApplyMemoryImageNamePatch (void *NameDst, const FMemoryImageName &Name, const FPlatformTypeLayoutParameters &LayoutParams)
uint32 DefaultAppendHash (const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams, FSHA1 &Hasher)
uint32 DefaultGetTargetAlignment (const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams)
void DefaultToString (const void *Object, const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams, FMemoryToStringContext &OutContext)
uint32 DefaultUnfrozenCopy (const FMemoryUnfreezeContent &Context, const void *Object, const FTypeLayoutDesc &TypeDesc, void *OutDst)
void DefaultWriteMemoryImage (FMemoryImageWriter &Writer, const void *Object, const FTypeLayoutDesc &TypeDesc, const FTypeLayoutDesc &DerivedTypeDesc)
void DefaultWriteMemoryImageField (FMemoryImageWriter &Writer, const void *Object, const void *FieldObject, const FTypeLayoutDesc &TypeDesc, const FTypeLayoutDesc &DerivedTypeDesc)
template<typename T>
FORCEINLINE void DestroyObject (T *Object, const FPointerTableBase *PtrTable, bool bIsFrozen)
void ExtractBitFieldValue (const void *Value, uint32 SrcBitOffset, uint32 DestBitOffset, uint32 NumBits, uint64 &InOutValue)
uint8 FindFieldNameLength (const TCHAR *Name)
uint32 GetTargetAlignment (const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams)
FSHAHash HashLayout (const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams)
uint32 HashLayout (const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams, FSHAHash &OutHash)
uint32 HashLayouts (const TArray< const FTypeLayoutDesc * > &TypeLayouts, const FPlatformTypeLayoutParameters &LayoutParams, FSHAHash &OutHash)
bool IncludeField (const FFieldLayoutDesc *FieldDesc, const FPlatformTypeLayoutParameters &LayoutParams)
template<typename T>
FORCEINLINE uint32 IntrinsicAppendHash (const T *DummyObject, const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams, FSHA1 &Hasher)
template<typename T, typename AllocatorType>
UE_NODEBUG uint32 IntrinsicAppendHash (const TArray< T, AllocatorType > *DummyObject, const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams, FSHA1 &Hasher)
template<typename InAllocator>
uint32 IntrinsicAppendHash (const THashTable< InAllocator > *DummyObject, const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams, FSHA1 &Hasher)
template<typename T, typename PtrType>
uint32 IntrinsicAppendHash (const TIndexedPtrBase< T, PtrType > *DummyObject, const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams, FSHA1 &Hasher)
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs>
uint32 IntrinsicAppendHash (const TMap< KeyType, ValueType, SetAllocator, KeyFuncs > *DummyObject, const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams, FSHA1 &Hasher)
template<typename T>
uint32 IntrinsicAppendHash (const TMemoryImagePtr< T > *DummyObject, const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams, FSHA1 &Hasher)
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs>
uint32 IntrinsicAppendHash (const TMultiMap< KeyType, ValueType, SetAllocator, KeyFuncs > *DummyObject, const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams, FSHA1 &Hasher)
template<typename ElementType, typename KeyFuncs, typename Allocator>
uint32 IntrinsicAppendHash (const TSet< ElementType, KeyFuncs, Allocator > *DummyObject, const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams, FSHA1 &Hasher)
template<typename ElementType, typename Allocator>
uint32 IntrinsicAppendHash (const TSparseArray< ElementType, Allocator > *DummyObject, const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams, FSHA1 &Hasher)
template<typename KeyType, typename ValueType>
uint32 IntrinsicAppendHash (const TTuple< KeyType, ValueType > *DummyObject, const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams, FSHA1 &Hasher)
uint32 IntrinsicAppendHash (void *const *DummyObject, const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams, FSHA1 &Hasher)
template<typename T>
FORCEINLINE uint32 IntrinsicGetTargetAlignment (const T *DummyObject, const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams)
template<typename T, typename AllocatorType>
UE_NODEBUG uint32 IntrinsicGetTargetAlignment (const TArray< T, AllocatorType > *DummyObject, const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams)
template<typename InAllocator>
uint32 IntrinsicGetTargetAlignment (const THashTable< InAllocator > *DummyObject, const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams)
template<typename T, typename PtrType>
uint32 IntrinsicGetTargetAlignment (const TIndexedPtrBase< T, PtrType > *DummyObject, const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams)
template<typename T>
uint32 IntrinsicGetTargetAlignment (const TMemoryImagePtr< T > *DummyObject, const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams)
template<typename KeyType, typename ValueType>
uint32 IntrinsicGetTargetAlignment (const TTuple< KeyType, ValueType > *DummyObject, const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams)
uint32 IntrinsicGetTargetAlignment (void *const *DummyObject, const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams)
void IntrinsicToString (char Object, const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams, FMemoryToStringContext &OutContext)
void IntrinsicToString (char16_t Object, const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams, FMemoryToStringContext &OutContext)
void IntrinsicToString (const FHashedName &Object, const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams, FMemoryToStringContext &OutContext)
void IntrinsicToString (const FSHAHash &Object, const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams, FMemoryToStringContext &OutContext)
template<typename T>
void IntrinsicToString (const T &Object, const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams, FMemoryToStringContext &OutContext)
template<typename T, typename AllocatorType>
UE_NODEBUG void IntrinsicToString (const TArray< T, AllocatorType > &Object, const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams, FMemoryToStringContext &OutContext)
RENDERCORE_API void IntrinsicToString (const TIndexedPtr< FShaderType > &Object, const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams, FMemoryToStringContext &OutContext)
RENDERCORE_API void IntrinsicToString (const TIndexedPtr< FVertexFactoryType > &Object, const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams, FMemoryToStringContext &OutContext)
template<typename T>
void IntrinsicToString (const TMemoryImagePtr< T > &Object, const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams, FMemoryToStringContext &OutContext)
void IntrinsicToString (double Object, const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams, FMemoryToStringContext &OutContext)
void IntrinsicToString (float Object, const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams, FMemoryToStringContext &OutContext)
void IntrinsicToString (int Object, const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams, FMemoryToStringContext &OutContext)
void IntrinsicToString (int8 Object, const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams, FMemoryToStringContext &OutContext)
void IntrinsicToString (long long Object, const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams, FMemoryToStringContext &OutContext)
void IntrinsicToString (long Object, const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams, FMemoryToStringContext &OutContext)
void IntrinsicToString (short Object, const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams, FMemoryToStringContext &OutContext)
void IntrinsicToString (unsigned char Object, const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams, FMemoryToStringContext &OutContext)
void IntrinsicToString (unsigned int Object, const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams, FMemoryToStringContext &OutContext)
void IntrinsicToString (unsigned long long Object, const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams, FMemoryToStringContext &OutContext)
void IntrinsicToString (unsigned long Object, const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams, FMemoryToStringContext &OutContext)
void IntrinsicToString (unsigned short Object, const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams, FMemoryToStringContext &OutContext)
void IntrinsicToString (void *Object, const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams, FMemoryToStringContext &OutContext)
void IntrinsicToString (wchar_t Object, const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams, FMemoryToStringContext &OutContext)
uint32 IntrinsicUnfrozenCopy (const FMemoryUnfreezeContent &Context, const FMemoryImageName &Object, void *OutDst)
template<typename T>
FORCEINLINE uint32 IntrinsicUnfrozenCopy (const FMemoryUnfreezeContent &Context, const T &Object, void *OutDst)
template<typename T, typename AllocatorType>
UE_NODEBUG uint32 IntrinsicUnfrozenCopy (const FMemoryUnfreezeContent &Context, const TArray< T, AllocatorType > &Object, void *OutDst)
template<typename InAllocator>
uint32 IntrinsicUnfrozenCopy (const FMemoryUnfreezeContent &Context, const THashTable< InAllocator > &Object, void *OutDst)
template<typename T, typename PtrType>
uint32 IntrinsicUnfrozenCopy (const FMemoryUnfreezeContent &Context, const TIndexedPtrBase< T, PtrType > &Object, void *OutDst)
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs>
uint32 IntrinsicUnfrozenCopy (const FMemoryUnfreezeContent &Context, const TMap< KeyType, ValueType, SetAllocator, KeyFuncs > &Object, void *OutDst)
template<typename T>
uint32 IntrinsicUnfrozenCopy (const FMemoryUnfreezeContent &Context, const TMemoryImagePtr< T > &Object, void *OutDst)
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs>
uint32 IntrinsicUnfrozenCopy (const FMemoryUnfreezeContent &Context, const TMultiMap< KeyType, ValueType, SetAllocator, KeyFuncs > &Object, void *OutDst)
template<typename ElementType, typename KeyFuncs, typename Allocator>
uint32 IntrinsicUnfrozenCopy (const FMemoryUnfreezeContent &Context, const TSet< ElementType, KeyFuncs, Allocator > &Object, void *OutDst)
template<typename ElementType, typename Allocator>
uint32 IntrinsicUnfrozenCopy (const FMemoryUnfreezeContent &Context, const TSparseArray< ElementType, Allocator > &Object, void *OutDst)
template<typename KeyType, typename ValueType>
uint32 IntrinsicUnfrozenCopy (const FMemoryUnfreezeContent &Context, const TTuple< KeyType, ValueType > &Object, void *OutDst)
void IntrinsicWriteMemoryImage (FMemoryImageWriter &Writer, const FMemoryImageName &Object, const FTypeLayoutDesc &)
template<typename T>
FORCEINLINE void IntrinsicWriteMemoryImage (FMemoryImageWriter &Writer, const T &Object, const FTypeLayoutDesc &TypeDesc)
template<typename T, typename AllocatorType>
UE_NODEBUG void IntrinsicWriteMemoryImage (FMemoryImageWriter &Writer, const TArray< T, AllocatorType > &Object, const FTypeLayoutDesc &)
template<typename Allocator>
void IntrinsicWriteMemoryImage (FMemoryImageWriter &Writer, const TBitArray< Allocator > &Object, const FTypeLayoutDesc &)
template<typename InAllocator>
void IntrinsicWriteMemoryImage (FMemoryImageWriter &Writer, const THashTable< InAllocator > &Object, const FTypeLayoutDesc &)
template<typename T, typename PtrType>
void IntrinsicWriteMemoryImage (FMemoryImageWriter &Writer, const TIndexedPtrBase< T, PtrType > &Object, const FTypeLayoutDesc &TypeDesc)
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs>
void IntrinsicWriteMemoryImage (FMemoryImageWriter &Writer, const TMap< KeyType, ValueType, SetAllocator, KeyFuncs > &Object, const FTypeLayoutDesc &)
template<typename T>
void IntrinsicWriteMemoryImage (FMemoryImageWriter &Writer, const TMemoryImagePtr< T > &Object, const FTypeLayoutDesc &)
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs>
void IntrinsicWriteMemoryImage (FMemoryImageWriter &Writer, const TMultiMap< KeyType, ValueType, SetAllocator, KeyFuncs > &Object, const FTypeLayoutDesc &)
template<typename ElementType, typename KeyFuncs, typename Allocator>
void IntrinsicWriteMemoryImage (FMemoryImageWriter &Writer, const TSet< ElementType, KeyFuncs, Allocator > &Object, const FTypeLayoutDesc &)
template<class ObjectType, ESPMode Mode>
void IntrinsicWriteMemoryImage (FMemoryImageWriter &Writer, const TSharedPtr< ObjectType, Mode > &Object, const FTypeLayoutDesc &)
template<typename ElementType, typename Allocator>
void IntrinsicWriteMemoryImage (FMemoryImageWriter &Writer, const TSparseArray< ElementType, Allocator > &Object, const FTypeLayoutDesc &)
template<typename KeyType, typename ValueType>
void IntrinsicWriteMemoryImage (FMemoryImageWriter &Writer, const TTuple< KeyType, ValueType > &Object, const FTypeLayoutDesc &)
void IntrinsicWriteMemoryImage (FMemoryImageWriter &Writer, const void *Object, uint32 Size)
void IntrinsicWriteMemoryImage (FMemoryImageWriter &Writer, void *, const FTypeLayoutDesc &)
Function Documentation
AppendHash()
uint32 Freeze::AppendHash (const FTypeLayoutDesc & TypeDesc, const FPlatformTypeLayoutParameters & LayoutParams, FSHA1 & Hasher)
Referenced by RangedForIteratorType< FAnimNextTraitEventPtr >::AppendHash(), and TSparseArray< SetElementType, typename Allocator::SparseArrayAllocator >::AppendHash().
AppendHashForNameAndSize()
uint32 Freeze::AppendHashForNameAndSize (const TCHAR * Name, uint32 Size, FSHA1 & Hasher)
References Name, and TSequenceHistory< HistorySize >::Size.
Referenced by IntrinsicAppendHash(), IntrinsicAppendHash(), IntrinsicAppendHash(), and IntrinsicAppendHash().
AppendHashPair()
uint32 Freeze::AppendHashPair (const FTypeLayoutDesc & KeyTypeDesc, const FTypeLayoutDesc & ValueTypeDesc, const FPlatformTypeLayoutParameters & LayoutParams, FSHA1 & Hasher)
Referenced by IntrinsicAppendHash().
ApplyMemoryImageNamePatch()
void Freeze::ApplyMemoryImageNamePatch (void * NameDst, const FMemoryImageName & Name, const FPlatformTypeLayoutParameters & LayoutParams)
References Name.
Referenced by Expose_TNameOf().
DefaultAppendHash()
uint32 Freeze::DefaultAppendHash (const FTypeLayoutDesc & TypeDesc, const FPlatformTypeLayoutParameters & LayoutParams, FSHA1 & Hasher)
Referenced by IntrinsicAppendHash(), IntrinsicAppendHash(), IntrinsicAppendHash(), IntrinsicAppendHash(), and IntrinsicAppendHash().
DefaultGetTargetAlignment()
uint32 Freeze::DefaultGetTargetAlignment (const FTypeLayoutDesc & TypeDesc, const FPlatformTypeLayoutParameters & LayoutParams)
DefaultToString()
void Freeze::DefaultToString (const void * Object, const FTypeLayoutDesc & TypeDesc, const FPlatformTypeLayoutParameters & LayoutParams, FMemoryToStringContext & OutContext)
References Object.
Referenced by IntrinsicToString().
DefaultUnfrozenCopy()
uint32 Freeze::DefaultUnfrozenCopy (const FMemoryUnfreezeContent & Context, const void * Object, const FTypeLayoutDesc & TypeDesc, void * OutDst)
References Object.
DefaultWriteMemoryImage()
void Freeze::DefaultWriteMemoryImage (FMemoryImageWriter & Writer, const void * Object, const FTypeLayoutDesc & TypeDesc, const FTypeLayoutDesc & DerivedTypeDesc)
References Object.
Referenced by TGetFreezeImageHelper< T, bUsePropertyFreezing >::Do().
DefaultWriteMemoryImageField()
void Freeze::DefaultWriteMemoryImageField (FMemoryImageWriter & Writer, const void * Object, const void * FieldObject, const FTypeLayoutDesc & TypeDesc, const FTypeLayoutDesc & DerivedTypeDesc)
References Object.
Referenced by TGetFreezeImageFieldHelper< T, bProvidesStaticStruct >::Do().
DestroyObject()
template<typename T> FORCEINLINE void Freeze::DestroyObject (T * Object, const FPointerTableBase * PtrTable, bool bIsFrozen)
Definition at line 252 of file MemoryLayout.h.
References FORCEINLINE, FMemory::Memset(), and Object.
ExtractBitFieldValue()
void Freeze::ExtractBitFieldValue (const void * Value, uint32 SrcBitOffset, uint32 DestBitOffset, uint32 NumBits, uint64 & InOutValue)
References Value.
FindFieldNameLength()
uint8 Freeze::FindFieldNameLength (const TCHAR * Name)
References Name.
GetTargetAlignment()
uint32 Freeze::GetTargetAlignment (const FTypeLayoutDesc & TypeDesc, const FPlatformTypeLayoutParameters & LayoutParams)
Referenced by IntrinsicGetTargetAlignment().
HashLayout() [1/2]
FSHAHash Freeze::HashLayout (const FTypeLayoutDesc & TypeDesc, const FPlatformTypeLayoutParameters & LayoutParams)
HashLayout() [2/2]
uint32 Freeze::HashLayout (const FTypeLayoutDesc & TypeDesc, const FPlatformTypeLayoutParameters & LayoutParams, FSHAHash & OutHash)
HashLayouts()
uint32 Freeze::HashLayouts (const TArray< const FTypeLayoutDesc * > & TypeLayouts, const FPlatformTypeLayoutParameters & LayoutParams, FSHAHash & OutHash)
IncludeField()
bool Freeze::IncludeField (const FFieldLayoutDesc * FieldDesc, const FPlatformTypeLayoutParameters & LayoutParams)
IntrinsicAppendHash() [1/11]
template<typename T> FORCEINLINE uint32 Freeze::IntrinsicAppendHash (const T * DummyObject, const FTypeLayoutDesc & TypeDesc, const FPlatformTypeLayoutParameters & LayoutParams, FSHA1 & Hasher)
Definition at line 277 of file MemoryLayout.h.
References DefaultAppendHash(), and FORCEINLINE.
IntrinsicAppendHash() [2/11]
template<typename T, typename AllocatorType> UE_NODEBUG uint32 Freeze::IntrinsicAppendHash (const TArray< T, AllocatorType > * DummyObject, const FTypeLayoutDesc & TypeDesc, const FPlatformTypeLayoutParameters & LayoutParams, FSHA1 & Hasher) nodiscard
Definition at line 3974 of file Array.h.
References AppendHashForNameAndSize(), FTypeLayoutDesc::Name, and UE_NODEBUG.
Referenced by Expose_TNameOf().
IntrinsicAppendHash() [3/11]
template<typename InAllocator> uint32 Freeze::IntrinsicAppendHash (const THashTable< InAllocator > * DummyObject, const FTypeLayoutDesc & TypeDesc, const FPlatformTypeLayoutParameters & LayoutParams, FSHA1 & Hasher)
Definition at line 675 of file HashTable.h.
References AppendHashForNameAndSize(), and FTypeLayoutDesc::Name.
IntrinsicAppendHash() [4/11]
template<typename T, typename PtrType> uint32 Freeze::IntrinsicAppendHash (const TIndexedPtrBase< T, PtrType > * DummyObject, const FTypeLayoutDesc & TypeDesc, const FPlatformTypeLayoutParameters & LayoutParams, FSHA1 & Hasher)
Definition at line 1200 of file MemoryImage.h.
References AppendHashForNameAndSize(), and FTypeLayoutDesc::Name.
IntrinsicAppendHash() [5/11]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> uint32 Freeze::IntrinsicAppendHash (const TMap< KeyType, ValueType, SetAllocator, KeyFuncs > * DummyObject, const FTypeLayoutDesc & TypeDesc, const FPlatformTypeLayoutParameters & LayoutParams, FSHA1 & Hasher)
Definition at line 1495 of file Map.h.
References TMapBase< InKeyType, InValueType, SetAllocator, KeyFuncs >::AppendHash(), and DefaultAppendHash().
IntrinsicAppendHash() [6/11]
template<typename T> uint32 Freeze::IntrinsicAppendHash (const TMemoryImagePtr< T > * DummyObject, const FTypeLayoutDesc & TypeDesc, const FPlatformTypeLayoutParameters & LayoutParams, FSHA1 & Hasher)
Definition at line 514 of file MemoryImage.h.
References AppendHashForNameAndSize(), and FTypeLayoutDesc::Name.
IntrinsicAppendHash() [7/11]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> uint32 Freeze::IntrinsicAppendHash (const TMultiMap< KeyType, ValueType, SetAllocator, KeyFuncs > * DummyObject, const FTypeLayoutDesc & TypeDesc, const FPlatformTypeLayoutParameters & LayoutParams, FSHA1 & Hasher)
Definition at line 1846 of file Map.h.
References TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::AppendHash(), and DefaultAppendHash().
IntrinsicAppendHash() [8/11]
template<typename ElementType, typename KeyFuncs, typename Allocator> uint32 Freeze::IntrinsicAppendHash (const TSet< ElementType, KeyFuncs, Allocator > * DummyObject, const FTypeLayoutDesc & TypeDesc, const FPlatformTypeLayoutParameters & LayoutParams, FSHA1 & Hasher)
Definition at line 1732 of file Set.h.
References TSet< InElementType, KeyFuncs, Allocator >::AppendHash(), and DefaultAppendHash().
IntrinsicAppendHash() [9/11]
template<typename ElementType, typename Allocator> uint32 Freeze::IntrinsicAppendHash (const TSparseArray< ElementType, Allocator > * DummyObject, const FTypeLayoutDesc & TypeDesc, const FPlatformTypeLayoutParameters & LayoutParams, FSHA1 & Hasher)
Definition at line 1336 of file SparseArray.h.
References TSparseArray< InElementType, Allocator >::AppendHash(), and DefaultAppendHash().
IntrinsicAppendHash() [10/11]
template<typename KeyType, typename ValueType> uint32 Freeze::IntrinsicAppendHash (const TTuple< KeyType, ValueType > * DummyObject, const FTypeLayoutDesc & TypeDesc, const FPlatformTypeLayoutParameters & LayoutParams, FSHA1 & Hasher)
Definition at line 776 of file Tuple.h.
References AppendHashPair(), and StaticGetTypeLayoutDesc().
IntrinsicAppendHash() [11/11]
uint32 Freeze::IntrinsicAppendHash (void *const * DummyObject, const FTypeLayoutDesc & TypeDesc, const FPlatformTypeLayoutParameters & LayoutParams, FSHA1 & Hasher)
IntrinsicGetTargetAlignment() [1/7]
template<typename T> FORCEINLINE uint32 Freeze::IntrinsicGetTargetAlignment (const T * DummyObject, const FTypeLayoutDesc & TypeDesc, const FPlatformTypeLayoutParameters & LayoutParams)
Definition at line 283 of file MemoryLayout.h.
References FTypeLayoutDesc::Alignment, and FORCEINLINE.
IntrinsicGetTargetAlignment() [2/7]
template<typename T, typename AllocatorType> UE_NODEBUG uint32 Freeze::IntrinsicGetTargetAlignment (const TArray< T, AllocatorType > * DummyObject, const FTypeLayoutDesc & TypeDesc, const FPlatformTypeLayoutParameters & LayoutParams) nodiscard
Definition at line 3980 of file Array.h.
References FMath::Min, and UE_NODEBUG.
IntrinsicGetTargetAlignment() [3/7]
template<typename InAllocator> uint32 Freeze::IntrinsicGetTargetAlignment (const THashTable< InAllocator > * DummyObject, const FTypeLayoutDesc & TypeDesc, const FPlatformTypeLayoutParameters & LayoutParams)
Definition at line 681 of file HashTable.h.
References FMath::Min.
IntrinsicGetTargetAlignment() [4/7]
template<typename T, typename PtrType> uint32 Freeze::IntrinsicGetTargetAlignment (const TIndexedPtrBase< T, PtrType > * DummyObject, const FTypeLayoutDesc & TypeDesc, const FPlatformTypeLayoutParameters & LayoutParams) inline
Definition at line 1206 of file MemoryImage.h.
References FMath::Min.
IntrinsicGetTargetAlignment() [5/7]
template<typename T> uint32 Freeze::IntrinsicGetTargetAlignment (const TMemoryImagePtr< T > * DummyObject, const FTypeLayoutDesc & TypeDesc, const FPlatformTypeLayoutParameters & LayoutParams) inline
Definition at line 520 of file MemoryImage.h.
References FMath::Min.
IntrinsicGetTargetAlignment() [6/7]
template<typename KeyType, typename ValueType> uint32 Freeze::IntrinsicGetTargetAlignment (const TTuple< KeyType, ValueType > * DummyObject, const FTypeLayoutDesc & TypeDesc, const FPlatformTypeLayoutParameters & LayoutParams)
Definition at line 782 of file Tuple.h.
References GetTargetAlignment(), FMath::Max, FMath::Min, and StaticGetTypeLayoutDesc().
IntrinsicGetTargetAlignment() [7/7]
uint32 Freeze::IntrinsicGetTargetAlignment (void *const * DummyObject, const FTypeLayoutDesc & TypeDesc, const FPlatformTypeLayoutParameters & LayoutParams)
IntrinsicToString() [1/23]
void Freeze::IntrinsicToString (char Object, const FTypeLayoutDesc & TypeDesc, const FPlatformTypeLayoutParameters & LayoutParams, FMemoryToStringContext & OutContext)
References Object.
IntrinsicToString() [2/23]
void Freeze::IntrinsicToString (char16_t Object, const FTypeLayoutDesc & TypeDesc, const FPlatformTypeLayoutParameters & LayoutParams, FMemoryToStringContext & OutContext)
References Object.
IntrinsicToString() [3/23]
void Freeze::IntrinsicToString (const FHashedName & Object, const FTypeLayoutDesc & TypeDesc, const FPlatformTypeLayoutParameters & LayoutParams, FMemoryToStringContext & OutContext)
References Object.
IntrinsicToString() [4/23]
void Freeze::IntrinsicToString (const FSHAHash & Object, const FTypeLayoutDesc & TypeDesc, const FPlatformTypeLayoutParameters & LayoutParams, FMemoryToStringContext & OutContext)
References Object.
IntrinsicToString() [5/23]
template<typename T> void Freeze::IntrinsicToString (const T & Object, const FTypeLayoutDesc & TypeDesc, const FPlatformTypeLayoutParameters & LayoutParams, FMemoryToStringContext & OutContext) inline
Definition at line 289 of file MemoryLayout.h.
References DefaultToString(), and Object.
IntrinsicToString() [6/23]
template<typename T, typename AllocatorType> UE_NODEBUG void Freeze::IntrinsicToString (const TArray< T, AllocatorType > & Object, const FTypeLayoutDesc & TypeDesc, const FPlatformTypeLayoutParameters & LayoutParams, FMemoryToStringContext & OutContext)
Definition at line 3987 of file Array.h.
References Object, and UE_NODEBUG.
IntrinsicToString() [7/23]
RENDERCORE_API void Freeze::IntrinsicToString (const TIndexedPtr< FShaderType > & Object, const FTypeLayoutDesc & TypeDesc, const FPlatformTypeLayoutParameters & LayoutParams, FMemoryToStringContext & OutContext)
References Object.
IntrinsicToString() [8/23]
RENDERCORE_API void Freeze::IntrinsicToString (const TIndexedPtr< FVertexFactoryType > & Object, const FTypeLayoutDesc & TypeDesc, const FPlatformTypeLayoutParameters & LayoutParams, FMemoryToStringContext & OutContext)
References Object.
IntrinsicToString() [9/23]
template<typename T> void Freeze::IntrinsicToString (const TMemoryImagePtr< T > & Object, const FTypeLayoutDesc & TypeDesc, const FPlatformTypeLayoutParameters & LayoutParams, FMemoryToStringContext & OutContext)
Definition at line 526 of file MemoryImage.h.
References FMemoryToStringContext::AppendFrozenPointer(), FMemoryToStringContext::AppendNullptr(), FMemoryToStringContext::AppendUnfrozenPointer(), FTypeLayoutDesc::GetOffsetToBase(), GetTypeLayoutDesc(), Object, StaticGetTypeLayoutDesc(), FTypeLayoutDesc::ToStringFunc, and FMemoryToStringContext::TryGetPrevPointerTable().
IntrinsicToString() [10/23]
void Freeze::IntrinsicToString (double Object, const FTypeLayoutDesc & TypeDesc, const FPlatformTypeLayoutParameters & LayoutParams, FMemoryToStringContext & OutContext)
References Object.
IntrinsicToString() [11/23]
void Freeze::IntrinsicToString (float Object, const FTypeLayoutDesc & TypeDesc, const FPlatformTypeLayoutParameters & LayoutParams, FMemoryToStringContext & OutContext)
References Object.
IntrinsicToString() [12/23]
void Freeze::IntrinsicToString (int Object, const FTypeLayoutDesc & TypeDesc, const FPlatformTypeLayoutParameters & LayoutParams, FMemoryToStringContext & OutContext)
References Object.
IntrinsicToString() [13/23]
void Freeze::IntrinsicToString (int8 Object, const FTypeLayoutDesc & TypeDesc, const FPlatformTypeLayoutParameters & LayoutParams, FMemoryToStringContext & OutContext)
References Object.
IntrinsicToString() [14/23]
void Freeze::IntrinsicToString (long long Object, const FTypeLayoutDesc & TypeDesc, const FPlatformTypeLayoutParameters & LayoutParams, FMemoryToStringContext & OutContext)
References Object.
IntrinsicToString() [15/23]
void Freeze::IntrinsicToString (long Object, const FTypeLayoutDesc & TypeDesc, const FPlatformTypeLayoutParameters & LayoutParams, FMemoryToStringContext & OutContext)
References Object.
IntrinsicToString() [16/23]
void Freeze::IntrinsicToString (short Object, const FTypeLayoutDesc & TypeDesc, const FPlatformTypeLayoutParameters & LayoutParams, FMemoryToStringContext & OutContext)
References Object.
IntrinsicToString() [17/23]
void Freeze::IntrinsicToString (unsigned char Object, const FTypeLayoutDesc & TypeDesc, const FPlatformTypeLayoutParameters & LayoutParams, FMemoryToStringContext & OutContext)
References Object.
IntrinsicToString() [18/23]
void Freeze::IntrinsicToString (unsigned int Object, const FTypeLayoutDesc & TypeDesc, const FPlatformTypeLayoutParameters & LayoutParams, FMemoryToStringContext & OutContext)
References Object.
IntrinsicToString() [19/23]
void Freeze::IntrinsicToString (unsigned long long Object, const FTypeLayoutDesc & TypeDesc, const FPlatformTypeLayoutParameters & LayoutParams, FMemoryToStringContext & OutContext)
References Object.
IntrinsicToString() [20/23]
void Freeze::IntrinsicToString (unsigned long Object, const FTypeLayoutDesc & TypeDesc, const FPlatformTypeLayoutParameters & LayoutParams, FMemoryToStringContext & OutContext)
References Object.
IntrinsicToString() [21/23]
void Freeze::IntrinsicToString (unsigned short Object, const FTypeLayoutDesc & TypeDesc, const FPlatformTypeLayoutParameters & LayoutParams, FMemoryToStringContext & OutContext)
References Object.
IntrinsicToString() [22/23]
void Freeze::IntrinsicToString (void * Object, const FTypeLayoutDesc & TypeDesc, const FPlatformTypeLayoutParameters & LayoutParams, FMemoryToStringContext & OutContext)
References Object.
IntrinsicToString() [23/23]
void Freeze::IntrinsicToString (wchar_t Object, const FTypeLayoutDesc & TypeDesc, const FPlatformTypeLayoutParameters & LayoutParams, FMemoryToStringContext & OutContext)
References Object.
IntrinsicUnfrozenCopy() [1/11]
uint32 Freeze::IntrinsicUnfrozenCopy (const FMemoryUnfreezeContent & Context, const FMemoryImageName & Object, void * OutDst)
References Object.
IntrinsicUnfrozenCopy() [2/11]
template<typename T> FORCEINLINE uint32 Freeze::IntrinsicUnfrozenCopy (const FMemoryUnfreezeContent & Context, const T & Object, void * OutDst)
Definition at line 270 of file MemoryLayout.h.
References FORCEINLINE, and Object.
IntrinsicUnfrozenCopy() [3/11]
template<typename T, typename AllocatorType> UE_NODEBUG uint32 Freeze::IntrinsicUnfrozenCopy (const FMemoryUnfreezeContent & Context, const TArray< T, AllocatorType > & Object, void * OutDst) nodiscard
Definition at line 3967 of file Array.h.
References Object, and UE_NODEBUG.
Referenced by Expose_TNameOf().
IntrinsicUnfrozenCopy() [4/11]
template<typename InAllocator> uint32 Freeze::IntrinsicUnfrozenCopy (const FMemoryUnfreezeContent & Context, const THashTable< InAllocator > & Object, void * OutDst)
Definition at line 668 of file HashTable.h.
References Object.
IntrinsicUnfrozenCopy() [5/11]
template<typename T, typename PtrType> uint32 Freeze::IntrinsicUnfrozenCopy (const FMemoryUnfreezeContent & Context, const TIndexedPtrBase< T, PtrType > & Object, void * OutDst)
Definition at line 1193 of file MemoryImage.h.
References Object.
IntrinsicUnfrozenCopy() [6/11]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> uint32 Freeze::IntrinsicUnfrozenCopy (const FMemoryUnfreezeContent & Context, const TMap< KeyType, ValueType, SetAllocator, KeyFuncs > & Object, void * OutDst)
Definition at line 1488 of file Map.h.
References Object.
IntrinsicUnfrozenCopy() [7/11]
template<typename T> uint32 Freeze::IntrinsicUnfrozenCopy (const FMemoryUnfreezeContent & Context, const TMemoryImagePtr< T > & Object, void * OutDst)
Definition at line 474 of file MemoryImage.h.
References FTypeLayoutDesc::GetOffsetToBase(), GetTypeLayoutDesc(), Object, FTypeLayoutDesc::Size, and StaticGetTypeLayoutDesc().
IntrinsicUnfrozenCopy() [8/11]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> uint32 Freeze::IntrinsicUnfrozenCopy (const FMemoryUnfreezeContent & Context, const TMultiMap< KeyType, ValueType, SetAllocator, KeyFuncs > & Object, void * OutDst)
Definition at line 1839 of file Map.h.
References Object.
IntrinsicUnfrozenCopy() [9/11]
template<typename ElementType, typename KeyFuncs, typename Allocator> uint32 Freeze::IntrinsicUnfrozenCopy (const FMemoryUnfreezeContent & Context, const TSet< ElementType, KeyFuncs, Allocator > & Object, void * OutDst)
Definition at line 1725 of file Set.h.
References Object.
IntrinsicUnfrozenCopy() [10/11]
template<typename ElementType, typename Allocator> uint32 Freeze::IntrinsicUnfrozenCopy (const FMemoryUnfreezeContent & Context, const TSparseArray< ElementType, Allocator > & Object, void * OutDst)
Definition at line 1329 of file SparseArray.h.
References Object.
IntrinsicUnfrozenCopy() [11/11]
template<typename KeyType, typename ValueType> uint32 Freeze::IntrinsicUnfrozenCopy (const FMemoryUnfreezeContent & Context, const TTuple< KeyType, ValueType > & Object, void * OutDst)
Definition at line 767 of file Tuple.h.
References Object.
IntrinsicWriteMemoryImage() [1/15]
void Freeze::IntrinsicWriteMemoryImage (FMemoryImageWriter & Writer, const FMemoryImageName & Object, const FTypeLayoutDesc &)
References Object.
IntrinsicWriteMemoryImage() [2/15]
template<typename T> FORCEINLINE void Freeze::IntrinsicWriteMemoryImage (FMemoryImageWriter & Writer, const T & Object, const FTypeLayoutDesc & TypeDesc)
Definition at line 264 of file MemoryLayout.h.
References FORCEINLINE, IntrinsicWriteMemoryImage(), and Object.
IntrinsicWriteMemoryImage() [3/15]
template<typename T, typename AllocatorType> UE_NODEBUG void Freeze::IntrinsicWriteMemoryImage (FMemoryImageWriter & Writer, const TArray< T, AllocatorType > & Object, const FTypeLayoutDesc &)
Definition at line 3961 of file Array.h.
References Object, and UE_NODEBUG.
Referenced by Expose_TNameOf(), and IntrinsicWriteMemoryImage().
IntrinsicWriteMemoryImage() [4/15]
template<typename Allocator> void Freeze::IntrinsicWriteMemoryImage (FMemoryImageWriter & Writer, const TBitArray< Allocator > & Object, const FTypeLayoutDesc &)
Definition at line 1891 of file BitArray.h.
References Object.
IntrinsicWriteMemoryImage() [5/15]
template<typename InAllocator> void Freeze::IntrinsicWriteMemoryImage (FMemoryImageWriter & Writer, const THashTable< InAllocator > & Object, const FTypeLayoutDesc &)
Definition at line 662 of file HashTable.h.
References Object.
IntrinsicWriteMemoryImage() [6/15]
template<typename T, typename PtrType> void Freeze::IntrinsicWriteMemoryImage (FMemoryImageWriter & Writer, const TIndexedPtrBase< T, PtrType > & Object, const FTypeLayoutDesc & TypeDesc)
Definition at line 1176 of file MemoryImage.h.
References FPointerTableBase::AddIndexedPointer(), check, FMemoryImageWriter::GetPointerTable(), INDEX_NONE, Object, FMemoryImageWriter::TryGetPrevPointerTable(), and FMemoryImageWriter::WriteBytes().
IntrinsicWriteMemoryImage() [7/15]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> void Freeze::IntrinsicWriteMemoryImage (FMemoryImageWriter & Writer, const TMap< KeyType, ValueType, SetAllocator, KeyFuncs > & Object, const FTypeLayoutDesc &)
Definition at line 1482 of file Map.h.
References Object.
IntrinsicWriteMemoryImage() [8/15]
template<typename T> void Freeze::IntrinsicWriteMemoryImage (FMemoryImageWriter & Writer, const TMemoryImagePtr< T > & Object, const FTypeLayoutDesc &)
Definition at line 456 of file MemoryImage.h.
References GetTypeLayoutDesc(), Object, StaticGetTypeLayoutDesc(), FMemoryImageWriter::TryGetPrevPointerTable(), FMemoryImageWriter::WriteNullPointer(), FMemoryImageWriter::WriteObject(), and FMemoryImageWriter::WritePointer().
IntrinsicWriteMemoryImage() [9/15]
template<typename KeyType, typename ValueType, typename SetAllocator, typename KeyFuncs> void Freeze::IntrinsicWriteMemoryImage (FMemoryImageWriter & Writer, const TMultiMap< KeyType, ValueType, SetAllocator, KeyFuncs > & Object, const FTypeLayoutDesc &)
Definition at line 1833 of file Map.h.
References Object.
IntrinsicWriteMemoryImage() [10/15]
template<typename ElementType, typename KeyFuncs, typename Allocator> void Freeze::IntrinsicWriteMemoryImage (FMemoryImageWriter & Writer, const TSet< ElementType, KeyFuncs, Allocator > & Object, const FTypeLayoutDesc &)
Definition at line 1719 of file Set.h.
References Object.
IntrinsicWriteMemoryImage() [11/15]
template<class ObjectType, ESPMode Mode> void Freeze::IntrinsicWriteMemoryImage (FMemoryImageWriter & Writer, const TSharedPtr< ObjectType, Mode > & Object, const FTypeLayoutDesc &)
Definition at line 1218 of file SharedPointer.h.
References Object, and FMemoryImageWriter::WriteBytes().
IntrinsicWriteMemoryImage() [12/15]
template<typename ElementType, typename Allocator> void Freeze::IntrinsicWriteMemoryImage (FMemoryImageWriter & Writer, const TSparseArray< ElementType, Allocator > & Object, const FTypeLayoutDesc &)
Definition at line 1323 of file SparseArray.h.
References Object.
IntrinsicWriteMemoryImage() [13/15]
template<typename KeyType, typename ValueType> void Freeze::IntrinsicWriteMemoryImage (FMemoryImageWriter & Writer, const TTuple< KeyType, ValueType > & Object, const FTypeLayoutDesc &)
Definition at line 760 of file Tuple.h.
References Object, and FMemoryImageWriter::WriteObject().
IntrinsicWriteMemoryImage() [14/15]
void Freeze::IntrinsicWriteMemoryImage (FMemoryImageWriter & Writer, const void * Object, uint32 Size)
References Object, and TSequenceHistory< HistorySize >::Size.
IntrinsicWriteMemoryImage() [15/15]
void Freeze::IntrinsicWriteMemoryImage (FMemoryImageWriter & Writer, void * , const FTypeLayoutDesc &)