Unreal Engine 5.6 C++ API: EBuildTargets Namespace Reference
EBuildTargets Namespace Reference
Functions
UE_DEPRECATED (4.24, "EBuildTargets::Editor is deprecated. Use EBuildTargetType::Unknown instead.") static const expr EBuildTargetType Editor
UE_DEPRECATED (4.24, "EBuildTargets::FromString is deprecated. Use LexFromString() instead.") 1 const TCHAR *ToString(EBuildTargetType Target)
UE_DEPRECATED (4.24, "EBuildTargets::FromString is deprecated. Use LexFromString() instead.") 1 EBuildTargetType FromString(const FString &Target)
UE_DEPRECATED (4.24, "EBuildTargets::Game is deprecated. Use EBuildTargetType::Unknown instead.") static const expr EBuildTargetType Game
UE_DEPRECATED (4.24, "EBuildTargets::Server is deprecated. Use EBuildTargetType::Unknown instead.") static const expr EBuildTargetType Server
UE_DEPRECATED (4.24, "EBuildTargets::Type is deprecated. Use EBuildTargetType instead.") typedef EBuildTargetType Type
UE_DEPRECATED (4.24, "EBuildTargets::Unknown is deprecated. Use EBuildTargetType::Unknown instead.") static const expr EBuildTargetType Unknown
Function Documentation
UE_DEPRECATED() [1/7]
EBuildTargets::UE_DEPRECATED (4. 24, "EBuildTargets::Editor is deprecated. Use EBuildTargetType::Unknown instead.") const
References Editor, and UE_DEPRECATED().
UE_DEPRECATED() [2/7]
EBuildTargets::UE_DEPRECATED (4. 24, "EBuildTargets::FromString is deprecated. Use LexFromString() instead.") const
References Target, ToString(), and UE_DEPRECATED().
UE_DEPRECATED() [3/7]
EBuildTargets::UE_DEPRECATED (4. 24, "EBuildTargets::FromString is deprecated. Use LexFromString() instead.") const &
References Target, and UE_DEPRECATED().
UE_DEPRECATED() [4/7]
EBuildTargets::UE_DEPRECATED (4. 24, "EBuildTargets::Game is deprecated. Use EBuildTargetType::Unknown instead.") const
References Game, and UE_DEPRECATED().
UE_DEPRECATED() [5/7]
EBuildTargets::UE_DEPRECATED (4. 24, "EBuildTargets::Server is deprecated. Use EBuildTargetType::Unknown instead.") const
References Server, and UE_DEPRECATED().
UE_DEPRECATED() [6/7]
EBuildTargets::UE_DEPRECATED (4. 24, "EBuildTargets::Type is deprecated. Use EBuildTargetType instead.")
Referenced by UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
UE_DEPRECATED() [7/7]
EBuildTargets::UE_DEPRECATED (4. 24, "EBuildTargets::Unknown is deprecated. Use EBuildTargetType::Unknown instead.") const
References UE_DEPRECATED(), and Unknown.