Unreal Engine 5.6 C++ API: TraceServices::PagedArrayAlgoImpl Namespace Reference
TraceServices::PagedArrayAlgoImpl Namespace Reference
Functions
template<typename SizeType, typename ItemType, typename PageType, typename ValueType, typename ProjectionType, typename SortPredicateType = TLess<>() UE_REQUIRES(TIsArithmetic<ValueType>::Value)>
FORCEINLINE SizeType BinarySearchClosestInternal (const TPagedArray< ItemType, PageType > &PagedArray, ValueType Value, ProjectionType Projection, SortPredicateType SortPredicate)
Performs binary search, resulting in position of the first element with projected value closest to Value.
template<typename SizeType, typename ItemType, typename PageType, typename ValueType, typename ProjectionType, typename SortPredicateType = TLess<>()>
FORCEINLINE SizeType LowerBoundInternal (const TPagedArray< ItemType, PageType > &PagedArray, const ValueType &Value, ProjectionType Projection, SortPredicateType SortPredicate)
Performs binary search, resulting in position of the first element with projected value >= Value.
template<typename SizeType, typename ItemType, typename PageType, typename ValueType, typename ProjectionType, typename SortPredicateType = TLess<>()>
FORCEINLINE SizeType UpperBoundInternal (const TPagedArray< ItemType, PageType > &PagedArray, const ValueType &Value, ProjectionType Projection, SortPredicateType SortPredicate)
Performs binary search, resulting in position of the first element with projected value > Value.
Function Documentation
BinarySearchClosestInternal()
template<typename SizeType, typename ItemType, typename PageType, typename ValueType, typename ProjectionType, typename SortPredicateType = TLess<>() UE_REQUIRES(TIsArithmetic<ValueType>::Value)> FORCEINLINE SizeType TraceServices::PagedArrayAlgoImpl::BinarySearchClosestInternal (const TPagedArray< ItemType, PageType > & PagedArray, ValueType Value, ProjectionType Projection, SortPredicateType SortPredicate)
Performs binary search, resulting in position of the first element with projected value closest to Value.
Parameters
PagedArray The paged array to search through; must be already sorted by SortPredicate.
Value The value to look for
Projection The functor or data member pointer; called via Invoke to compare to Value.
SortPredicate The predicate for sort comparison; defaults to <.
Returns
The position of the first element with projected value closest to Value; == 0 if Num == 0, otherwise is a value in range [0 .. Num-1].
Definition at line 956 of file PagedArray.h.
References BinarySearchClosestInternal(), FORCEINLINE, Invoke(), Algo::LowerBoundBy(), MakeArrayView(), TArray< InElementType, InAllocatorType >::Num(), Projection(), and Value.
Referenced by TraceServices::PagedArrayAlgo::BinarySearchClosest(), TraceServices::PagedArrayAlgo::BinarySearchClosest(), TraceServices::PagedArrayAlgo::BinarySearchClosestBy(), TraceServices::PagedArrayAlgo::BinarySearchClosestBy(), and BinarySearchClosestInternal().
LowerBoundInternal()
template<typename SizeType, typename ItemType, typename PageType, typename ValueType, typename ProjectionType, typename SortPredicateType = TLess<>()> FORCEINLINE SizeType TraceServices::PagedArrayAlgoImpl::LowerBoundInternal (const TPagedArray< ItemType, PageType > & PagedArray, const ValueType & Value, ProjectionType Projection, SortPredicateType SortPredicate)
Performs binary search, resulting in position of the first element with projected value >= Value.
Parameters
PagedArray The paged array to search through; must be already sorted by SortPredicate.
Value The value to look for
Projection The functor or data member pointer; called via Invoke to compare to Value.
SortPredicate The predicate for sort comparison; defaults to <.
Returns
The position of the first element with projected value >= Value; may be == Num.
Definition at line 873 of file PagedArray.h.
References check, FORCEINLINE, TraceServices::TPagedArray< InItemType, InPageType >::GetIteratorFromItem(), TraceServices::TPagedArray< InItemType, InPageType >::GetPages(), TraceServices::TPagedArray< InItemType, InPageType >::GetPageSize(), Invoke(), Algo::LowerBoundBy(), MakeArrayView(), TraceServices::TPagedArray< InItemType, InPageType >::Num(), TraceServices::TPagedArray< InItemType, InPageType >::NumPages(), TraceServices::TPagedArrayIterator< ItemType, PageType >::PrevItem(), Projection(), and Value.
Referenced by TraceServices::PagedArrayAlgo::LowerBound(), TraceServices::PagedArrayAlgo::LowerBound(), TraceServices::PagedArrayAlgo::LowerBoundBy(), and TraceServices::PagedArrayAlgo::LowerBoundBy().
UpperBoundInternal()
template<typename SizeType, typename ItemType, typename PageType, typename ValueType, typename ProjectionType, typename SortPredicateType = TLess<>()> FORCEINLINE SizeType TraceServices::PagedArrayAlgoImpl::UpperBoundInternal (const TPagedArray< ItemType, PageType > & PagedArray, const ValueType & Value, ProjectionType Projection, SortPredicateType SortPredicate)
Performs binary search, resulting in position of the first element with projected value > Value.
Parameters
PagedArray The paged array to search through; must be already sorted by SortPredicate.
Value The value to look for
Projection The functor or data member pointer; called via Invoke to compare to Value.
SortPredicate The predicate for sort comparison; defaults to <.
Returns
The position of the first element with projected value > Value; may be == Num.
Definition at line 914 of file PagedArray.h.
References check, FORCEINLINE, TraceServices::TPagedArray< InItemType, InPageType >::GetIteratorFromItem(), TraceServices::TPagedArray< InItemType, InPageType >::GetPages(), TraceServices::TPagedArray< InItemType, InPageType >::GetPageSize(), Invoke(), MakeArrayView(), TraceServices::TPagedArray< InItemType, InPageType >::Num(), TraceServices::TPagedArray< InItemType, InPageType >::NumPages(), TraceServices::TPagedArrayIterator< ItemType, PageType >::PrevItem(), Projection(), Algo::UpperBoundBy(), and Value.
Referenced by TraceServices::PagedArrayAlgo::UpperBound(), TraceServices::PagedArrayAlgo::UpperBound(), TraceServices::PagedArrayAlgo::UpperBoundBy(), and TraceServices::PagedArrayAlgo::UpperBoundBy().