Unreal Engine 5.6 C++ API: PropertyTemplate Namespace Reference
PropertyTemplate Namespace Reference
Data Structures
struct FSectionData
Persistent section data for a property section.
struct FTokenProducer
struct TCachedState
Cached preanimated state for a given property.
struct TTemporarySetterType
Functions
template<typename PropertyValueType, typename IntermediateType = PropertyValueType>
static IMovieScenePreAnimatedTokenPtr CacheExistingState (UObject &Object, FTrackInstancePropertyBindings &PropertyBindings)
template<typename PropertyValueType, typename IntermediateType = PropertyValueType>
TTemporarySetterType< PropertyValueType, IntermediateType >::Type ConvertFromIntermediateType (const IntermediateType &InIntermediateType, const FMovieSceneEvaluationOperand &Operand, FPersistentEvaluationData &PersistentData, IMovieScenePlayer &Player)
Convert from an intermediate type to the type used for setting a property value.
template<typename PropertyValueType, typename IntermediateType = PropertyValueType>
TTemporarySetterType< PropertyValueType, IntermediateType >::Type ConvertFromIntermediateType (const IntermediateType &InIntermediateType, IMovieScenePlayer &Player)
Convert from an intermediate type to the type used for setting a property value.
template<typename PropertyValueType, typename IntermediateType = PropertyValueType>
IntermediateType ConvertToIntermediateType (PropertyValueType &&NewValue)
template<typename T>
bool IsValueValid (const T &InValue)
Function Documentation
CacheExistingState()
template<typename PropertyValueType, typename IntermediateType = PropertyValueType> IMovieScenePreAnimatedTokenPtr PropertyTemplate::CacheExistingState (UObject & Object, FTrackInstancePropertyBindings & PropertyBindings) static
Definition at line 107 of file MovieScenePropertyTemplate.h.
References ConvertToIntermediateType(), FTrackInstancePropertyBindings::GetCurrentValue(), and Object.
Referenced by PropertyTemplate::FTokenProducer< PropertyValueType >::CacheExistingState().
ConvertFromIntermediateType() [1/2]
template<typename PropertyValueType, typename IntermediateType = PropertyValueType> TTemporarySetterType< PropertyValueType, IntermediateType >::Type PropertyTemplate::ConvertFromIntermediateType (const IntermediateType & InIntermediateType, const FMovieSceneEvaluationOperand & Operand, FPersistentEvaluationData & PersistentData, IMovieScenePlayer & Player)
Convert from an intermediate type to the type used for setting a property value.
Called during token execution.
Definition at line 60 of file MovieScenePropertyTemplate.h.
ConvertFromIntermediateType() [2/2]
template<typename PropertyValueType, typename IntermediateType = PropertyValueType> TTemporarySetterType< PropertyValueType, IntermediateType >::Type PropertyTemplate::ConvertFromIntermediateType (const IntermediateType & InIntermediateType, IMovieScenePlayer & Player)
Convert from an intermediate type to the type used for setting a property value.
Called when resetting pre animated state
Definition at line 52 of file MovieScenePropertyTemplate.h.
Referenced by TPropertyTrackExecutionToken< PropertyValueType, IntermediateType >::Execute(), and PropertyTemplate::TCachedState< PropertyValueType, IntermediateType >::RestoreState().
ConvertToIntermediateType()
template<typename PropertyValueType, typename IntermediateType = PropertyValueType> IntermediateType PropertyTemplate::ConvertToIntermediateType (PropertyValueType && NewValue)
Definition at line 66 of file MovieScenePropertyTemplate.h.
References Forward().
Referenced by CacheExistingState().
IsValueValid()
template<typename T> bool PropertyTemplate::IsValueValid (const T & InValue)
Definition at line 72 of file MovieScenePropertyTemplate.h.
Referenced by TPropertyTrackExecutionToken< PropertyValueType, IntermediateType >::Execute(), and PropertyTemplate::TCachedState< PropertyValueType, IntermediateType >::RestoreState().