Unreal Engine 5.6 C++ API: RenderingSpatialHash Namespace Reference
RenderingSpatialHash Namespace Reference
Data Structures
struct TLocation
Describes an object location in the rendering hierarchical spatial hash grid.
Typedefs
using FLocation32 = TLocation<int32>
using FLocation64 = TLocation<int64>
using FLocation8 = TLocation<int8>
Functions
int32 CalcLevel (double Size)
int32 CalcLevel (float Size)
FLocation64 CalcLevelAndLocation (const FBoxSphereBounds &BoxSphereBounds)
FLocation64 CalcLevelAndLocation (const FVector4d &Sphere)
FLocation64 CalcLevelAndLocationClamped (const FVector3d &Center, double Radius, int32 FirstLevel)
int32 CalcLevelFromRadius (double Radius)
FVector3d CalcWorldPosition (const FLocation64 &Loc)
double GetCellSize (int32 Level)
double GetRecCellSize (int32 Level)
FLocation64 ToCellLoc (int32 Level, const FVector &WorldPos)
FLocation64 ToLevel (const FLocation64 &Loc, int32 Level)
Typedef Documentation
FLocation32
using RenderingSpatialHash::FLocation32 = TLocation<int32>
Definition at line 74 of file RenderingSpatialHash.h.
FLocation64
using RenderingSpatialHash::FLocation64 = TLocation<int64>
Definition at line 73 of file RenderingSpatialHash.h.
FLocation8
using RenderingSpatialHash::FLocation8 = TLocation<int8>
Definition at line 75 of file RenderingSpatialHash.h.
Function Documentation
CalcLevel() [1/2]
int32 RenderingSpatialHash::CalcLevel (double Size) inline
Definition at line 77 of file RenderingSpatialHash.h.
References TSequenceHistory< HistorySize >::Size.
Referenced by CalcLevelFromRadius().
CalcLevel() [2/2]
int32 RenderingSpatialHash::CalcLevel (float Size) inline
Definition at line 83 of file RenderingSpatialHash.h.
References TSequenceHistory< HistorySize >::Size.
CalcLevelAndLocation() [1/2]
FLocation64 RenderingSpatialHash::CalcLevelAndLocation (const FBoxSphereBounds & BoxSphereBounds) inline
Definition at line 115 of file RenderingSpatialHash.h.
References BoxSphereBounds, CalcLevelFromRadius(), and ToCellLoc().
CalcLevelAndLocation() [2/2]
FLocation64 RenderingSpatialHash::CalcLevelAndLocation (const FVector4d & Sphere) inline
Definition at line 122 of file RenderingSpatialHash.h.
References CalcLevelFromRadius(), FVector, Sphere, and ToCellLoc().
CalcLevelAndLocationClamped()
FLocation64 RenderingSpatialHash::CalcLevelAndLocationClamped (const FVector3d & Center, double Radius, int32 FirstLevel) inline
Definition at line 129 of file RenderingSpatialHash.h.
References CalcLevelFromRadius(), FMath::Max, and ToCellLoc().
CalcLevelFromRadius()
int32 RenderingSpatialHash::CalcLevelFromRadius (double Radius) inline
Definition at line 89 of file RenderingSpatialHash.h.
References CalcLevel().
Referenced by CalcLevelAndLocation(), CalcLevelAndLocation(), and CalcLevelAndLocationClamped().
CalcWorldPosition()
FVector3d RenderingSpatialHash::CalcWorldPosition (const FLocation64 & Loc) inline
Definition at line 137 of file RenderingSpatialHash.h.
References RenderingSpatialHash::TLocation< ScalarType >::Coord, GetCellSize(), and RenderingSpatialHash::TLocation< ScalarType >::Level.
GetCellSize()
double RenderingSpatialHash::GetCellSize (int32 Level) inline
Definition at line 94 of file RenderingSpatialHash.h.
References checkSlow.
Referenced by CalcWorldPosition(), and GetRecCellSize().
GetRecCellSize()
double RenderingSpatialHash::GetRecCellSize (int32 Level) inline
Definition at line 100 of file RenderingSpatialHash.h.
References GetCellSize().
Referenced by ToCellLoc().
ToCellLoc()
FLocation64 RenderingSpatialHash::ToCellLoc (int32 Level, const FVector & WorldPos) inline
Definition at line 105 of file RenderingSpatialHash.h.
References FVector, GetRecCellSize(), UE::Math::TVector< T >::X, UE::Math::TVector< T >::Y, and UE::Math::TVector< T >::Z.
Referenced by CalcLevelAndLocation(), CalcLevelAndLocation(), and CalcLevelAndLocationClamped().
ToLevel()
FLocation64 RenderingSpatialHash::ToLevel (const FLocation64 & Loc, int32 Level) inline
Definition at line 142 of file RenderingSpatialHash.h.
References RenderingSpatialHash::TLocation< ScalarType >::Coord, and RenderingSpatialHash::TLocation< ScalarType >::Level.