Unreal Engine 5.6 C++ API: UE::Tasks Namespace Reference
UE::Tasks Namespace Reference
Namespaces
namespace Private
namespace TaskConcurrencyLimiter_Private
Data Structures
class FCancellationToken
class FCancellationTokenScope
class FPipe
class FTaskConcurrencyLimiter
A lightweight construct that limits the concurrency of tasks pushed into it.
class FTaskEvent
class FTaskPriorityCVar
class TTask
class TTask< void >
Typedefs
using FTask = Private::FTaskHandle
Enumerations
enum class EExtendedTaskPriority : int8 {
None , Inline , TaskEvent , GameThreadNormalPri ,
GameThreadHiPri , GameThreadNormalPriLocalQueue , GameThreadHiPriLocalQueue , RenderThreadNormalPri ,
RenderThreadHiPri , RenderThreadNormalPriLocalQueue , RenderThreadHiPriLocalQueue , RHIThreadNormalPri ,
RHIThreadHiPri , RHIThreadNormalPriLocalQueue , RHIThreadHiPriLocalQueue , Count
}
enum class ETaskFlags { None , DoNotRunInsideBusyWait }
enum class ETaskPriority
Functions
template<typename TaskType>
void AddNested (const TaskType &Nested)
template<typename TaskCollectionType>
FTask Any (const TaskCollectionType &Tasks)
for (auto &Task :Tasks)
template<typename TaskBodyType>
TTask< TInvokeResult_T< TaskBodyType > > Launch (const TCHAR *DebugName, TaskBodyType &&TaskBody, ETaskPriority Priority=ETaskPriority::Normal, EExtendedTaskPriority ExtendedPriority=EExtendedTaskPriority::None, ETaskFlags Flags=ETaskFlags::None)
template<typename TaskBodyType, typename PrerequisitesCollectionType>
TTask< TInvokeResult_T< TaskBodyType > > Launch (const TCHAR *DebugName, TaskBodyType &&TaskBody, PrerequisitesCollectionType &&Prerequisites, ETaskPriority Priority=ETaskPriority::Normal, EExtendedTaskPriority ExtendedPriority=EExtendedTaskPriority::None, ETaskFlags Flags=ETaskFlags::None)
template<typename ResultType, typename... ArgTypes>
TTask< ResultType > MakeCompletedTask (ArgTypes &&... Args)
template<typename TaskCollectionType>
const TaskCollectionType & Prerequisites (const TaskCollectionType &Tasks)
template<typename... TaskTypes, typename std::decay_t< decltype(std::declval< TTuple< TaskTypes... > >().template Get< 0 >())>::FTaskHandleId * = nullptr>
TStaticArray< Private::FTaskBase *, sizeof...(TaskTypes)> Prerequisites (TaskTypes &... Tasks)
bool ToExtendedTaskPriority (const TCHAR *ExtendedPriorityStr, EExtendedTaskPriority &OutExtendedPriority)
const TCHAR * ToString (EExtendedTaskPriority ExtendedPriority)
const TCHAR * ToString (ETaskPriority Priority)
bool ToTaskPriority (const TCHAR *PriorityStr, ETaskPriority &OutPriority)
TRACE_CPUPROFILER_EVENT_SCOPE (Tasks::BusyWait)
template<typename TaskCollectionType>
UE_DEPRECATED (5.5, "Use Wait instead.") bool BusyWait(const TaskCollectionType &Tasks
template<typename TaskCollectionType>
bool Wait (const TaskCollectionType &Tasks, FTimespan InTimeout=FTimespan::MaxValue())
void Wait (Private::FTaskHandle &Task)
template<typename TaskCollectionType>
int32 WaitAny (const TaskCollectionType &Tasks, FTimespan Timeout=FTimespan::MaxValue())
Variables
FTimespan InTimeout = FTimespan::MaxValue())
FTimeout Timeout { InTimeout }
return true
Typedef Documentation
FTask
using UE::Tasks::FTask = Private::FTaskHandle
Definition at line 392 of file Task.h.
Enumeration Type Documentation
EExtendedTaskPriority
enum class UE::Tasks::EExtendedTaskPriority : int8 strong
Enumerator
None
Inline
TaskEvent
GameThreadNormalPri
GameThreadHiPri
GameThreadNormalPriLocalQueue
GameThreadHiPriLocalQueue
RenderThreadNormalPri
RenderThreadHiPri
RenderThreadNormalPriLocalQueue
RenderThreadHiPriLocalQueue
RHIThreadNormalPri
RHIThreadHiPri
RHIThreadNormalPriLocalQueue
RHIThreadHiPriLocalQueue
Count
Definition at line 59 of file TaskPrivate.h.
ETaskFlags
enum class UE::Tasks::ETaskFlags strong
Enumerator
None
DoNotRunInsideBusyWait
Definition at line 88 of file TaskPrivate.h.
ETaskPriority
enum class LowLevelTasks::ETaskPriority : int8 strong
Definition at line 17 of file Task.h.
Function Documentation
AddNested()
template<typename TaskType> void UE::Tasks::AddNested (const TaskType & Nested)
Definition at line 567 of file Task.h.
References AddNested(), check, UE::Tasks::Private::GetCurrentTask(), and Parent.
Referenced by AddNested().
Any()
template<typename TaskCollectionType> FTask UE::Tasks::Any (const TaskCollectionType & Tasks)
Definition at line 513 of file Task.h.
References Event, Inline, Launch(), Num, Prerequisites(), UE_SOURCE_LOCATION, and UNLIKELY.
for()
UE::Tasks::for (auto &Task :Tasks)
Definition at line 380 of file Task.h.
References Timeout.
Launch() [1/2]
template<typename TaskBodyType> TTask< TInvokeResult_T< TaskBodyType > > UE::Tasks::Launch (const TCHAR * DebugName, TaskBodyType && TaskBody, ETaskPriority Priority = ETaskPriority::Normal, EExtendedTaskPriority ExtendedPriority = EExtendedTaskPriority::None, ETaskFlags Flags = ETaskFlags::None)
Definition at line 299 of file Task.h.
References Flags, Forward(), UE::Tasks::Private::FTaskHandle::Launch(), and None.
Referenced by Any(), UE::MeshDeformation::ConstructFullCotangentLaplacian(), UE::MeshDeformation::ConstructTriangleDataArray(), FAsyncAddPrimitiveQueue::FAddPrimitivesTask::Launch(), TAsyncComponentDataComputeQueue< DataType >::LaunchJob(), MakeCompletedTask(), Wait(), and WaitAny().
Launch() [2/2]
template<typename TaskBodyType, typename PrerequisitesCollectionType> TTask< TInvokeResult_T< TaskBodyType > > UE::Tasks::Launch (const TCHAR * DebugName, TaskBodyType && TaskBody, PrerequisitesCollectionType && Prerequisites, ETaskPriority Priority = ETaskPriority::Normal, EExtendedTaskPriority ExtendedPriority = EExtendedTaskPriority::None, ETaskFlags Flags = ETaskFlags::None)
Definition at line 322 of file Task.h.
References Flags, Forward(), UE::Tasks::Private::FTaskHandle::Launch(), None, and Prerequisites().
MakeCompletedTask()
template<typename ResultType, typename... ArgTypes> TTask< ResultType > UE::Tasks::MakeCompletedTask (ArgTypes &&... Args)
Definition at line 615 of file Task.h.
References Forward(), Inline, Launch(), MakeCompletedTask(), and UE_SOURCE_LOCATION.
Referenced by MakeCompletedTask().
Prerequisites() [1/2]
template<typename TaskCollectionType> const TaskCollectionType & UE::Tasks::Prerequisites (const TaskCollectionType & Tasks)
Definition at line 432 of file Task.h.
Prerequisites() [2/2]
template<typename... TaskTypes, typename std::decay_t< decltype(std::declval< TTuple< TaskTypes... > >().template Get< 0 >())>::FTaskHandleId * = nullptr> TStaticArray< Private::FTaskBase *, sizeof...(TaskTypes)> UE::Tasks::Prerequisites (TaskTypes &... Tasks)
Definition at line 424 of file Task.h.
References UE::Tasks::Private::PrerequisitesUnpacker().
Referenced by UE::Tasks::FTaskEvent::AddPrerequisites(), Any(), UE::Tasks::FPipe::Launch(), Launch(), UE::Tasks::Private::FTaskHandle::Launch(), Wait(), and WaitAny().
ToExtendedTaskPriority()
bool UE::Tasks::ToExtendedTaskPriority (const TCHAR * ExtendedPriorityStr, EExtendedTaskPriority & OutExtendedPriority)
ToString() [1/2]
const TCHAR * UE::Tasks::ToString (EExtendedTaskPriority ExtendedPriority)
ToString() [2/2]
const TCHAR * LowLevelTasks::ToString (ETaskPriority Priority) inline
Definition at line 30 of file Task.h.
ToTaskPriority()
bool LowLevelTasks::ToTaskPriority (const TCHAR * PriorityStr, ETaskPriority & OutPriority) inline
Definition at line 48 of file Task.h.
TRACE_CPUPROFILER_EVENT_SCOPE()
UE::Tasks::TRACE_CPUPROFILER_EVENT_SCOPE (Tasks::BusyWait)
UE_DEPRECATED()
template<typename TaskCollectionType> UE::Tasks::UE_DEPRECATED (5. 5, "Use Wait instead.") const &
Wait() [1/2]
template<typename TaskCollectionType> bool UE::Tasks::Wait (const TaskCollectionType & Tasks, FTimespan InTimeout = FTimespan::MaxValue())
Definition at line 440 of file Task.h.
References UE::Tasks::Private::GetTraceIds(), Inline, InTimeout, Launch(), Prerequisites(), TEXT, TRACE_CPUPROFILER_EVENT_SCOPE, and Wait().
Referenced by UE::MeshDeformation::ConstructFullCotangentLaplacian(), UE::MeshDeformation::ConstructTriangleDataArray(), UE::Tasks::Private::FTaskBase::UE_DEPRECATED(), Wait(), and TAsyncComponentDataComputeQueue< DataType >::WaitForAllJobsDuringShutdown().
Wait() [2/2]
void UE::Tasks::Wait (Private::FTaskHandle & Task) inline
Definition at line 361 of file Task.h.
References UE::Tasks::Private::FTaskHandle::Wait().
WaitAny()
template<typename TaskCollectionType> int32 UE::Tasks::WaitAny (const TaskCollectionType & Tasks, FTimespan Timeout = FTimespan::MaxValue())
Definition at line 462 of file Task.h.
References Event, UE::FMonotonicTimeSpan::FromMilliseconds(), INDEX_NONE, Inline, UE::Tasks::Private::IsCompleted(), Launch(), MakeShared(), FTimespan::MaxValue(), Prerequisites(), Timeout, UE_SOURCE_LOCATION, and UNLIKELY.
Variable Documentation
InTimeout
FTimespan UE::Tasks::InTimeout = FTimespan::MaxValue())
Definition at line 23 of file Task.h.
Referenced by UE::Tasks::Private::FTaskHandle::UE::Tasks::BusyWait, UE::Tasks::Private::FTaskHandle::UE::Tasks::Wait, and Wait().
Timeout
FTimeout UE::Tasks::Timeout { InTimeout }
Definition at line 375 of file Task.h.
Referenced by for(), UE::Tasks::Private::FTaskBase::TryRetractAndExecute(), UE::Tasks::Private::FTaskHandle::TryRetractAndExecute, UE::Tasks::Private::FTaskBase::UE_DEPRECATED(), UE::Tasks::Private::FTaskHandle::UE_DEPRECATED(), UE::Tasks::FTaskConcurrencyLimiter::Wait(), UE::Tasks::Private::FTaskBase::Wait(), UE::Tasks::Private::FTaskHandle::Wait(), UE::Tasks::TaskConcurrencyLimiter_Private::FPimpl::Wait(), WaitAny(), UE::Tasks::Private::FTaskBase::WaitImpl(), and UE::Tasks::FPipe::WaitUntilEmpty().
true
return UE::Tasks::true
Definition at line 388 of file Task.h.