Unreal Engine 5.6 C++ API: Metasound::ArrayNodeVertexNames Namespace Reference
Metasound::ArrayNodeVertexNames Namespace Reference
Functions
METASOUND_PARAM (InputArray, "Array", "Input Array.") METASOUND_PARAM(InputLeftArray
Left Input Left Array METASOUND_PARAM (InputRightArray, "Right Array", "Input Right Array.") METASOUND_PARAM(InputTriggerGet
Left Input Left Array Trigger to get value Index in Array METASOUND_PARAM (InputStartIndex, "Start Index", "First index to include.") METASOUND_PARAM(InputEndIndex
Left Input Left Array Trigger to get value METASOUND_PARAM (InputTriggerSet, "Trigger", "Trigger to set value.") METASOUND_PARAM(InputIndex
Left Input Left Array Trigger to get value Index in Array End Last index to include METASOUND_PARAM (InputValue, "Value", "Value to set.") METASOUND_PARAM(OutputNum
Left Input Left Array Trigger to get value Index in Array End Last index to include Number of elements in the array Array after concatenation METASOUND_PARAM (OutputArraySet, "Array", "Array after setting.") METASOUND_PARAM(OutputArraySubset
Left Input Left Array Trigger to get value Index in Array End Last index to include Number of elements in the array METASOUND_PARAM (OutputValue, "Element", "Value of element at array index.") METASOUND_PARAM(OutputArrayConcat
Variables
Left Array
Left Input Left Array Trigger to get value Index
static const FText InputInitialArrayDisplayName = LOCTEXT("InitialArrayDisplayName", "Init Array")
static const FLazyName InputInitialArrayName = TEXT("Array")
static const FText InputInitialArrayTooltip = LOCTEXT("InitialArrayTooltip", "Initial Array")
Left Input Left Array Trigger to get value Index in Array End Last index to include Num
Left Input Left Array Trigger
Function Documentation
METASOUND_PARAM() [1/7]
Metasound::ArrayNodeVertexNames::METASOUND_PARAM (InputArray , "Array" , "Input Array.")
Referenced by METASOUND_PARAM(), METASOUND_PARAM(), METASOUND_PARAM(), METASOUND_PARAM(), METASOUND_PARAM(), and METASOUND_PARAM().
METASOUND_PARAM() [2/7]
Left Input Left Array Metasound::ArrayNodeVertexNames::METASOUND_PARAM (InputRightArray , "Right Array" , "Input Right Array.")
References METASOUND_PARAM().
METASOUND_PARAM() [3/7]
Left Input Left Array Trigger to get value Index in Array Metasound::ArrayNodeVertexNames::METASOUND_PARAM (InputStartIndex , "Start Index" , "First index to include.")
References METASOUND_PARAM().
METASOUND_PARAM() [4/7]
Left Input Left Array Trigger to get value Metasound::ArrayNodeVertexNames::METASOUND_PARAM (InputTriggerSet , "Trigger" , "Trigger to set value.")
References METASOUND_PARAM().
METASOUND_PARAM() [5/7]
Left Input Left Array Trigger to get value Index in Array End Last index to include Metasound::ArrayNodeVertexNames::METASOUND_PARAM (InputValue , "Value" , "Value to set.")
References METASOUND_PARAM().
METASOUND_PARAM() [6/7]
Left Input Left Array Trigger to get value Index in Array End Last index to include Number of elements in the array Array after concatenation Metasound::ArrayNodeVertexNames::METASOUND_PARAM (OutputArraySet , "Array" , "Array after setting.")
References METASOUND_PARAM().
METASOUND_PARAM() [7/7]
Left Input Left Array Trigger to get value Index in Array End Last index to include Number of elements in the array Metasound::ArrayNodeVertexNames::METASOUND_PARAM (OutputValue , "Element" , "Value of element at array index.")
References METASOUND_PARAM().
Variable Documentation
Array
Left Input Left Array Trigger to get value Index in Array End Last index to include Number of elements in the array Array after concatenation Metasound::ArrayNodeVertexNames::Array
Definition at line 58 of file MetasoundArrayNodes.h.
Index
Left Input Left Array Trigger to get value Index in Array End Metasound::ArrayNodeVertexNames::Index
Definition at line 62 of file MetasoundArrayNodes.h.
InputInitialArrayDisplayName
const FText Metasound::ArrayNodeVertexNames::InputInitialArrayDisplayName = LOCTEXT("InitialArrayDisplayName", "Init Array") static
Definition at line 51 of file MetasoundArrayNodes.h.
InputInitialArrayName
const FLazyName Metasound::ArrayNodeVertexNames::InputInitialArrayName = TEXT("Array") static
Definition at line 48 of file MetasoundArrayNodes.h.
InputInitialArrayTooltip
const FText Metasound::ArrayNodeVertexNames::InputInitialArrayTooltip = LOCTEXT("InitialArrayTooltip", "Initial Array") static
Definition at line 50 of file MetasoundArrayNodes.h.
Num
Left Input Left Array Trigger to get value Index in Array End Last index to include Metasound::ArrayNodeVertexNames::Num
Definition at line 67 of file MetasoundArrayNodes.h.
Trigger
Left Input Left Array Metasound::ArrayNodeVertexNames::Trigger
Definition at line 60 of file MetasoundArrayNodes.h.