Unreal Engine 5.6 C++ API: UE::Dataflow::Private Namespace Reference
UE::Dataflow::Private Namespace Reference
Selects all the bones for the Collection.
Functions
FName GetAttributeFromEnumAsName (const ESelectionByAttrGroup Value)
Detailed Description
Selects all the bones for the Collection.
Runs boolean operation on TransformSelections Deprecated (5.6) : use the generic CollectionSelectionSetOperation node instead Generates a formatted string of the bones and the selection Generates an empty bone selection for the Collection Inverts selection of bones Selects bones randomly in the Collection Selects the root bones in the Collection Selects specified bones in the GeometryCollection by using a space separated list, e.g. "0 1 2 12 23" Selects specified bones in the GeometryCollection by using a comma separated list, e.g. "0, 2, 5-10, 12-15" Convert index array to a transform selection Selects the parents of the currently selected bones Outputs the specified percentage of the selected bones Selects the children of the selected bones Selects the siblings of the selected bones Expand the selection to include all nodes with the same level as the selected nodes Selects the root bones in the Collection Selects the contact(s) of the selected bones Selects the leaves in the Collection Selects the clusters in the Collection Deprecated : this node had the wrong behavior and select the leaves instead Replace it by CollectionTransformSelectLeaf or use the second version of CollectionTransformSelectCluster Selects the clusters in the Collection this version works properly and address the issues found in the deprecated version 1 Selects indices of a float array by range Selects pieces based on their size Selects pieces based on their volume Selects bones if their Vertices/BoundingBox/Centroid in a box Selects bones if their Vertices/BoundingBox/Centroid in a sphere Selects bones by a float attribute Selects bones by an int attribute Selects specified vertices in the GeometryCollection by using a space separated list Selects specified faces in the GeometryCollection by using a space separated list Converts Vertex/Face/Transform selection into Vertex/Face/Transform selection Inverts selection of faces Outputs the specified percentage of the selected vertices Runs boolean operation on VertexSelections Deprecated (5.6) : use the generic CollectionSelectionSetOperation node instead
Function Documentation
GetAttributeFromEnumAsName()
FName UE::Dataflow::Private::GetAttributeFromEnumAsName (const ESelectionByAttrGroup Value) inline
Definition at line 1449 of file GeometryCollectionSelectionNodes.h.
References GetAttributeFromEnumAsName(), StaticEnum(), and Value.
Referenced by GetAttributeFromEnumAsName().