Unreal Engine 5.6 C++ API: EBuildConfigurations Namespace Reference
EBuildConfigurations Namespace Reference
Functions
FText ToText (EBuildConfiguration Configuration)
Returns the localized text representation of the specified EBuildConfiguration value.
UE_DEPRECATED (4.24, "EBuildConfigurations::Debug is deprecated. Use EBuildConfiguration::Debug instead.") static const expr EBuildConfiguration Debug
UE_DEPRECATED (4.24, "EBuildConfigurations::DebugGame is deprecated. Use EBuildConfiguration::DebugGame instead.") static const expr EBuildConfiguration DebugGame
UE_DEPRECATED (4.24, "EBuildConfigurations::Development is deprecated. Use EBuildConfiguration::Development instead.") static const expr EBuildConfiguration Development
UE_DEPRECATED (4.24, "EBuildConfigurations::FromString() is deprecated. Use LexFromString() instead.") 1 EBuildConfiguration FromString(const FString &Configuration)
Returns the string representation of the specified EBuildConfiguration value.
UE_DEPRECATED (4.24, "EBuildConfigurations::Shipping is deprecated. Use EBuildConfiguration::Shipping instead.") static const expr EBuildConfiguration Shipping
UE_DEPRECATED (4.24, "EBuildConfigurations::Test is deprecated. Use EBuildConfiguration::Test instead.") static const expr EBuildConfiguration Test
UE_DEPRECATED (4.24, "EBuildConfigurations::ToString() is deprecated. Use LexToString() instead.") 1 const TCHAR *ToString(EBuildConfiguration Configuration)
Returns the string representation of the specified EBuildConfiguration value.
UE_DEPRECATED (4.24, "EBuildConfigurations::Type is deprecated. Use EBuildConfiguration instead.") typedef EBuildConfiguration Type
UE_DEPRECATED (4.24, "EBuildConfigurations::Unknown is deprecated. Use EBuildConfiguration::Unknown instead.") static const expr EBuildConfiguration Unknown
Function Documentation
ToText()
FText EBuildConfigurations::ToText (EBuildConfiguration Configuration)
Returns the localized text representation of the specified EBuildConfiguration value.
Parameters
Configuration The value to get the text for.
Returns
The localized Build configuration text
References Configuration, and ToText().
Referenced by ToText().
UE_DEPRECATED() [1/9]
EBuildConfigurations::UE_DEPRECATED (4. 24, "EBuildConfigurations::Debug is deprecated. Use EBuildConfiguration::Debug instead.") const
References Debug, and UE_DEPRECATED().
UE_DEPRECATED() [2/9]
EBuildConfigurations::UE_DEPRECATED (4. 24, "EBuildConfigurations::DebugGame is deprecated. Use EBuildConfiguration::DebugGame instead.") const
References DebugGame, and UE_DEPRECATED().
UE_DEPRECATED() [3/9]
EBuildConfigurations::UE_DEPRECATED (4. 24, "EBuildConfigurations::Development is deprecated. Use EBuildConfiguration::Development instead.") const
References Development, and UE_DEPRECATED().
UE_DEPRECATED() [4/9]
EBuildConfigurations::UE_DEPRECATED (4. 24, "EBuildConfigurations::FromString() is deprecated. Use LexFromString() instead.") const &
Returns the string representation of the specified EBuildConfiguration value.
Parameters
Configuration The string to get the EBuildConfiguration for.
Returns
An EBuildConfiguration value.
References Configuration, and UE_DEPRECATED().
UE_DEPRECATED() [5/9]
EBuildConfigurations::UE_DEPRECATED (4. 24, "EBuildConfigurations::Shipping is deprecated. Use EBuildConfiguration::Shipping instead.") const
References Shipping, and UE_DEPRECATED().
UE_DEPRECATED() [6/9]
EBuildConfigurations::UE_DEPRECATED (4. 24, "EBuildConfigurations::Test is deprecated. Use EBuildConfiguration::Test instead.") const
References Test, and UE_DEPRECATED().
UE_DEPRECATED() [7/9]
EBuildConfigurations::UE_DEPRECATED (4. 24, "EBuildConfigurations::ToString() is deprecated. Use LexToString() instead.") const
Returns the string representation of the specified EBuildConfiguration value.
Parameters
Configuration The value to get the string for.
Returns
The string representation.
References Configuration, ToString(), and UE_DEPRECATED().
UE_DEPRECATED() [8/9]
EBuildConfigurations::UE_DEPRECATED (4. 24, "EBuildConfigurations::Type is deprecated. Use EBuildConfiguration instead.")
Referenced by UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
UE_DEPRECATED() [9/9]
EBuildConfigurations::UE_DEPRECATED (4. 24, "EBuildConfigurations::Unknown is deprecated. Use EBuildConfiguration::Unknown instead.") const
References UE_DEPRECATED(), and Unknown.