Unreal Engine 5.6 C++ API: Metasound::ArrayNodeShuffleVertexNames Namespace Reference
Metasound::ArrayNodeShuffleVertexNames Namespace Reference
Shuffle Node Vertex Names.
Functions
Trigger to shuffle the array manually In Input Array Auto Set to true to automatically shuffle when the array has been read METASOUND_PARAM (InputShuffleEnableSharedState, "Enable Shared State", "Set to enabled shared state across instances of this metasound.") METASOUND_PARAM(OutputTriggerOnNext
Trigger to shuffle the array manually In Input Array METASOUND_PARAM (InputShuffleSeed, "Seed", "Seed to use for the the random shuffle.") METASOUND_PARAM(InputAutoShuffle
METASOUND_PARAM (InputTriggerNext, "Next", "Trigger to get the next value in the shuffled array.") METASOUND_PARAM(InputTriggerShuffle
Trigger to shuffle the array manually METASOUND_PARAM (InputTriggerReset, "Reset Seed", "Trigger to reset the random seed stream of the shuffle node.") METASOUND_PARAM(InputShuffleArray
Trigger to shuffle the array manually In Input Array Auto Set to true to automatically shuffle when the array has been read On Triggers when the Next input is triggered METASOUND_PARAM (OutputTriggerOnShuffle, "On Shuffle", "Triggers when the \"Shuffle\" input is triggered or if the array is auto-shuffled.") METASOUND_PARAM(OutputTriggerOnResetSeed
Variables
Trigger to shuffle the array manually In Array
Trigger to shuffle the array manually In Input Array Auto Set to true to automatically shuffle when the array has been read On Next
Trigger to shuffle the array manually In Input Array Auto Set to true to automatically shuffle when the array has been read On Triggers when the Next input is triggered On Reset Seed
Shuffle
Detailed Description
Shuffle Node Vertex Names.
Function Documentation
METASOUND_PARAM() [1/5]
Trigger to shuffle the array manually In Input Array Auto Set to true to automatically shuffle when the array has been read Metasound::ArrayNodeShuffleVertexNames::METASOUND_PARAM (InputShuffleEnableSharedState , "Enable Shared State" , "Set to enabled shared state across instances of this metasound.")
References METASOUND_PARAM().
METASOUND_PARAM() [2/5]
Trigger to shuffle the array manually In Input Array Metasound::ArrayNodeShuffleVertexNames::METASOUND_PARAM (InputShuffleSeed , "Seed" , "Seed to use for the the random shuffle.")
References METASOUND_PARAM().
METASOUND_PARAM() [3/5]
Metasound::ArrayNodeShuffleVertexNames::METASOUND_PARAM (InputTriggerNext , "Next" , "Trigger to get the next value in the shuffled array.")
Referenced by METASOUND_PARAM(), METASOUND_PARAM(), METASOUND_PARAM(), and METASOUND_PARAM().
METASOUND_PARAM() [4/5]
Trigger to shuffle the array manually Metasound::ArrayNodeShuffleVertexNames::METASOUND_PARAM (InputTriggerReset , "Reset Seed" , "Trigger to reset the random seed stream of the shuffle node.")
References METASOUND_PARAM().
METASOUND_PARAM() [5/5]
Trigger to shuffle the array manually In Input Array Auto Set to true to automatically shuffle when the array has been read On Triggers when the Next input is triggered Metasound::ArrayNodeShuffleVertexNames::METASOUND_PARAM (OutputTriggerOnShuffle , "On Shuffle" , "Triggers when the \"Shuffle\" input is triggered or if the array is auto-shuffled.")
References METASOUND_PARAM().
Variable Documentation
Array
Trigger to shuffle the array manually In Metasound::ArrayNodeShuffleVertexNames::Array
Definition at line 36 of file MetasoundArrayShuffleNode.h.
Next
Trigger to shuffle the array manually In Input Array Auto Set to true to automatically shuffle when the array has been read On Metasound::ArrayNodeShuffleVertexNames::Next
Definition at line 41 of file MetasoundArrayShuffleNode.h.
Seed
Trigger to shuffle the array manually In Input Array Auto Set to true to automatically shuffle when the array has been read On Triggers when the Next input is triggered On Reset Metasound::ArrayNodeShuffleVertexNames::Seed
Definition at line 43 of file MetasoundArrayShuffleNode.h.
Shuffle
Trigger to shuffle the array manually In Input Array Auto Metasound::ArrayNodeShuffleVertexNames::Shuffle
Definition at line 34 of file MetasoundArrayShuffleNode.h.