Unreal Engine 5.6 C++ API: UE::Shader Namespace Reference
UE::Shader Namespace Reference
Data Structures
struct FComponentBounds
struct FMemoryImageValue
class FPreshaderData
struct FPreshaderLabel
class FPreshaderStack
struct FPreshaderStructType
struct FPreshaderType
Mirrors Shader::FType, but stores StructType as a hash rather than a pointer to facilitate serialization Struct's flattened component types are stored directly, as that is the primary thing needed at runtime.
struct FPreshaderValue
Mirrors Shader::FValue, except 'Component' array references memory owned by stack, rather than inline storage.
struct FStructField
struct FStructFieldInitializer
struct FStructType
struct FStructTypeInitializer
class FStructTypeRegistry
struct FType
struct FValue
Can store a numeric/struct shader value of any type Values are represented as a flat list of components.
union FValueComponent
The value of a single component within FValue.
struct FValueComponentTypeDescription
struct FValueTypeDescription
struct TValue
Typedefs
using FBoolValue = TValue<bool>
using FDoubleValue = TValue<double>
using FFloatValue = TValue<float>
using FIntValue = TValue<int32>
Enumerations
enum class EComponentBound : uint8 {
NegDoubleMax , NegFloatMax , IntMin , NegOne ,
Zero , One , IntMax , FloatMax ,
DoubleMax
}
enum class EPreshaderOpcode : uint8 {
Nop , ConstantZero , Constant , Parameter ,
Add , Sub , Mul , Div ,
Fmod , Modulo , Min , Max ,
Clamp , Sin , Cos , Tan ,
Asin , Acos , Atan , Atan2 ,
Dot , Cross , Sqrt , Rcp ,
Length , Normalize , Saturate , Abs ,
Floor , Ceil , Round , Trunc ,
Sign , Frac , Fractional , Log2 ,
Log10 , ComponentSwizzle , AppendVector , TextureSize ,
TexelSize , ExternalTextureCoordinateScaleRotation , ExternalTextureCoordinateOffset , RuntimeVirtualTextureUniform ,
SparseVolumeTextureUniform , GetField , SetField , Neg ,
Jump , JumpIfFalse , PushValue , Less ,
Assign , Greater , LessEqual , GreaterEqual ,
Exp , Exp2 , Log
}
enum class EValueComponentType : uint8 {
Void , Float , Double , Int ,
Bool , Numeric , Num
}
enum class EValueStringFormat { Description , HLSL }
enum class EValueType : uint8 {
Void , Float1 , Float2 , Float3 ,
Float4 , Double1 , Double2 , Double3 ,
Double4 , Int1 , Int2 , Int3 ,
Int4 , Bool1 , Bool2 , Bool3 ,
Bool4 , Numeric1 , Numeric2 , Numeric3 ,
Numeric4 , Float4x4 , Double4x4 , DoubleInverse4x4 ,
Numeric4x4 , Struct , Object , Any ,
Num
}
Functions
FValue Abs (const FValue &Value)
EValueType AbsInPlace (EValueType Type, TArrayView< FValueComponent > Component)
FValue Acos (const FValue &Value)
EValueType AcosInPlace (EValueType Type, TArrayView< FValueComponent > Component)
FValue Add (const FValue &Lhs, const FValue &Rhs)
EValueType AddInPlace (EValueType LhsType, EValueType RhsType, TArrayView< FValueComponent > Component, int32 &OutComponentsConsumed)
FValue Append (const FValue &Lhs, const FValue &Rhs)
EValueType AppendInPlace (EValueType LhsType, EValueType RhsType, TArrayView< FValueComponent > Component, int32 &OutComponentsConsumed)
FValue Asin (const FValue &Value)
EValueType AsinInPlace (EValueType Type, TArrayView< FValueComponent > Component)
FValue Atan (const FValue &Value)
FValue Atan2 (const FValue &Lhs, const FValue &Rhs)
EValueType Atan2InPlace (EValueType LhsType, EValueType RhsType, TArrayView< FValueComponent > Component, int32 &OutComponentsConsumed)
EValueType AtanInPlace (EValueType Type, TArrayView< FValueComponent > Component)
FValue Cast (const FValue &Value, EValueType Type)
FValue Ceil (const FValue &Value)
EValueType CeilInPlace (EValueType Type, TArrayView< FValueComponent > Component)
FValue Clamp (const FValue &Value, const FValue &Low, const FValue &High)
EValueComponentType CombineComponentTypes (EValueComponentType Lhs, EValueComponentType Rhs)
FType CombineTypes (const FType &Lhs, const FType &Rhs, bool bMergeMatrixTypes=false)
FValue Cos (const FValue &Value)
EValueType CosInPlace (EValueType Type, TArrayView< FValueComponent > Component)
FValue Cross (const FValue &Lhs, const FValue &Rhs)
FValue Div (const FValue &Lhs, const FValue &Rhs)
EValueType DivInPlace (EValueType LhsType, EValueType RhsType, TArrayView< FValueComponent > Component, int32 &OutComponentsConsumed)
FValue Dot (const FValue &Lhs, const FValue &Rhs)
FValue Exp (const FValue &Value)
FValue Exp2 (const FValue &Value)
EValueType Exp2InPlace (EValueType Type, TArrayView< FValueComponent > Component)
EValueType ExpInPlace (EValueType Type, TArrayView< FValueComponent > Component)
EValueType FindValueType (FName Name)
FValue Floor (const FValue &Value)
EValueType FloorInPlace (EValueType Type, TArrayView< FValueComponent > Component)
FValue Fmod (const FValue &Lhs, const FValue &Rhs)
EValueType FmodInPlace (EValueType LhsType, EValueType RhsType, TArrayView< FValueComponent > Component, int32 &OutComponentsConsumed)
FValue Frac (const FValue &Value)
EValueType FracInPlace (EValueType Type, TArrayView< FValueComponent > Component)
FValue Fractional (const FValue &Value)
EValueType FractionalInPlace (EValueType Type, TArrayView< FValueComponent > Component)
const TCHAR * GetComponentTypeName (EValueComponentType Type)
uint32 GetComponentTypeSizeInBytes (EValueComponentType Type)
uint32 GetTypeHash (const FType &Type)
uint32 GetTypeHash (const FValue &Value)
FValueComponentTypeDescription GetValueComponentTypeDescription (EValueComponentType Type)
const FValueTypeDescription & GetValueTypeDescription (EValueType Type)
FValue Greater (const FValue &Lhs, const FValue &Rhs)
FValue GreaterEqual (const FValue &Lhs, const FValue &Rhs)
bool IsComponentTypeWithinBounds (EValueComponentType Type, FComponentBounds Bounds)
bool IsGenericType (EValueComponentType Type)
bool IsGenericType (EValueType Type)
bool IsLWCType (EValueComponentType Type)
bool IsLWCType (EValueType Type)
bool IsNumericMatrixType (EValueType Type)
bool IsNumericScalarType (EValueType Type)
bool IsNumericType (EValueComponentType Type)
bool IsNumericType (EValueType Type)
bool IsNumericVectorType (EValueType Type)
bool IsWithinBounds (FComponentBounds Lhs, FComponentBounds Rhs)
FValue Less (const FValue &Lhs, const FValue &Rhs)
FValue LessEqual (const FValue &Lhs, const FValue &Rhs)
FValue Log (const FValue &Value)
FValue Log10 (const FValue &Value)
EValueType Log10InPlace (EValueType Type, TArrayView< FValueComponent > Component)
FValue Log2 (const FValue &Value)
EValueType Log2InPlace (EValueType Type, TArrayView< FValueComponent > Component)
EValueType LogInPlace (EValueType Type, TArrayView< FValueComponent > Component)
EValueComponentType MakeConcreteType (EValueComponentType Type)
EValueType MakeConcreteType (EValueType Type)
EValueType MakeDerivativeType (EValueType Type)
EValueComponentType MakeNonLWCType (EValueComponentType Type)
EValueType MakeNonLWCType (EValueType Type)
EValueType MakeValueType (EValueComponentType ComponentType, int32 NumComponents)
EValueType MakeValueType (EValueType BaseType, int32 NumComponents)
EValueType MakeValueTypeWithRequestedNumComponents (EValueType BaseType, int8 RequestedNumComponents)
FValue Max (const FValue &Lhs, const FValue &Rhs)
EComponentBound MaxBound (EComponentBound Lhs, EComponentBound Rhs)
FComponentBounds MaxBound (FComponentBounds Lhs, FComponentBounds Rhs)
EValueType MaxInPlace (EValueType LhsType, EValueType RhsType, TArrayView< FValueComponent > Component, int32 &OutComponentsConsumed)
FValue Min (const FValue &Lhs, const FValue &Rhs)
EComponentBound MinBound (EComponentBound Lhs, EComponentBound Rhs)
FComponentBounds MinBound (FComponentBounds Lhs, FComponentBounds Rhs)
EValueType MinInPlace (EValueType LhsType, EValueType RhsType, TArrayView< FValueComponent > Component, int32 &OutComponentsConsumed)
FValue Modulo (const FValue &Lhs, const FValue &Rhs)
EValueType ModuloInPlace (EValueType LhsType, EValueType RhsType, TArrayView< FValueComponent > Component, int32 &OutComponentsConsumed)
FValue Mul (const FValue &Lhs, const FValue &Rhs)
EValueType MulInPlace (EValueType LhsType, EValueType RhsType, TArrayView< FValueComponent > Component, int32 &OutComponentsConsumed)
FValue Neg (const FValue &Value)
EValueType NegInPlace (EValueType Type, TArrayView< FValueComponent > Component)
bool operator!= (const EValueType &Lhs, const FType &Rhs)
bool operator!= (const FComponentBounds &Lhs, const FComponentBounds &Rhs)
bool operator!= (const FType &Lhs, const EValueType &Rhs)
bool operator!= (const FType &Lhs, const FType &Rhs)
bool operator!= (const FValue &Lhs, const FValue &Rhs)
bool operator== (const EValueType &Lhs, const FType &Rhs)
bool operator== (const FComponentBounds &Lhs, const FComponentBounds &Rhs)
bool operator== (const FType &Lhs, const EValueType &Rhs)
bool operator== (const FType &Lhs, const FType &Rhs)
bool operator== (const FValue &Lhs, const FValue &Rhs)
FValue Rcp (const FValue &Value)
EValueType RcpInPlace (EValueType Type, TArrayView< FValueComponent > Component)
FValue Round (const FValue &Value)
EValueType RoundInPlace (EValueType Type, TArrayView< FValueComponent > Component)
FValue Saturate (const FValue &Value)
EValueType SaturateInPlace (EValueType Type, TArrayView< FValueComponent > Component)
FValue Sign (const FValue &Value)
EValueType SignInPlace (EValueType Type, TArrayView< FValueComponent > Component)
FValue Sin (const FValue &Value)
EValueType SinInPlace (EValueType Type, TArrayView< FValueComponent > Component)
FValue Sqrt (const FValue &Value)
EValueType SqrtInPlace (EValueType Type, TArrayView< FValueComponent > Component)
FValue Sub (const FValue &Lhs, const FValue &Rhs)
EValueType SubInPlace (EValueType LhsType, EValueType RhsType, TArrayView< FValueComponent > Component, int32 &OutComponentsConsumed)
FValue Tan (const FValue &Value)
EValueType TanInPlace (EValueType Type, TArrayView< FValueComponent > Component)
FValue Trunc (const FValue &Value)
EValueType TruncInPlace (EValueType Type, TArrayView< FValueComponent > Component)
Variables
static constexpr int32 NumValueComponentTypes = (int32)EValueComponentType::Num
constexpr int32 NumValueTypes = (int32)EValueType::Num
Typedef Documentation
FBoolValue
using UE::Shader::FBoolValue = TValue<bool>
Definition at line 326 of file ShaderTypes.h.
FDoubleValue
using UE::Shader::FDoubleValue = TValue<double>
Definition at line 324 of file ShaderTypes.h.
FFloatValue
using UE::Shader::FFloatValue = TValue<float>
Definition at line 323 of file ShaderTypes.h.
FIntValue
using UE::Shader::FIntValue = TValue<int32>
Definition at line 325 of file ShaderTypes.h.
Enumeration Type Documentation
EComponentBound
enum class UE::Shader::EComponentBound : uint8 strong
Enumerator
NegDoubleMax
NegFloatMax
IntMin
NegOne
Zero
One
IntMax
FloatMax
DoubleMax
Definition at line 18 of file ShaderTypes.h.
EPreshaderOpcode
enum class UE::Shader::EPreshaderOpcode : uint8 strong
Enumerator
Nop
ConstantZero
Constant
Parameter
Add
Sub
Mul
Div
Fmod
Modulo
Min
Max
Clamp
Sin
Cos
Tan
Asin
Acos
Atan
Atan2
Dot
Cross
Sqrt
Rcp
Length
Normalize
Saturate
Abs
Floor
Ceil
Round
Trunc
Sign
Frac
Fractional
Log2
Log10
ComponentSwizzle
AppendVector
TextureSize
TexelSize
ExternalTextureCoordinateScaleRotation
ExternalTextureCoordinateOffset
RuntimeVirtualTextureUniform
SparseVolumeTextureUniform
GetField
SetField
Neg
Jump
JumpIfFalse
PushValue
Less
Assign
Greater
LessEqual
GreaterEqual
Exp
Exp2
Log
Definition at line 19 of file Preshader.h.
EValueComponentType
enum class UE::Shader::EValueComponentType : uint8 strong
Enumerator
Void
Float
Double
Int
Bool
Numeric
Num
Definition at line 55 of file ShaderTypes.h.
EValueStringFormat
enum class UE::Shader::EValueStringFormat strong
Enumerator
Description
HLSL
Definition at line 328 of file ShaderTypes.h.
EValueType
enum class UE::Shader::EValueType : uint8 strong
Enumerator
Void
Float1
Float2
Float3
Float4
Double1
Double2
Double3
Double4
Int1
Int2
Int3
Int4
Bool1
Bool2
Bool3
Bool4
Numeric1
Numeric2
Numeric3
Numeric4
Float4x4
Double4x4
DoubleInverse4x4
Numeric4x4
Struct
Object
Any
Num
Definition at line 93 of file ShaderTypes.h.
Function Documentation
Abs()
FValue UE::Shader::Abs (const FValue & Value)
References Value.
AbsInPlace()
EValueType UE::Shader::AbsInPlace (EValueType Type, TArrayView< FValueComponent > Component)
References Component.
Acos()
FValue UE::Shader::Acos (const FValue & Value)
References Value.
AcosInPlace()
EValueType UE::Shader::AcosInPlace (EValueType Type, TArrayView< FValueComponent > Component)
References Component.
Add()
FValue UE::Shader::Add (const FValue & Lhs, const FValue & Rhs)
AddInPlace()
EValueType UE::Shader::AddInPlace (EValueType LhsType, EValueType RhsType, TArrayView< FValueComponent > Component, int32 & OutComponentsConsumed)
References Component.
Append()
FValue UE::Shader::Append (const FValue & Lhs, const FValue & Rhs)
AppendInPlace()
EValueType UE::Shader::AppendInPlace (EValueType LhsType, EValueType RhsType, TArrayView< FValueComponent > Component, int32 & OutComponentsConsumed)
References Component.
Asin()
FValue UE::Shader::Asin (const FValue & Value)
References Value.
AsinInPlace()
EValueType UE::Shader::AsinInPlace (EValueType Type, TArrayView< FValueComponent > Component)
References Component.
Atan()
FValue UE::Shader::Atan (const FValue & Value)
References Value.
Atan2()
FValue UE::Shader::Atan2 (const FValue & Lhs, const FValue & Rhs)
Atan2InPlace()
EValueType UE::Shader::Atan2InPlace (EValueType LhsType, EValueType RhsType, TArrayView< FValueComponent > Component, int32 & OutComponentsConsumed)
References Component.
AtanInPlace()
EValueType UE::Shader::AtanInPlace (EValueType Type, TArrayView< FValueComponent > Component)
References Component.
Cast()
FValue UE::Shader::Cast (const FValue & Value, EValueType Type)
References Value.
Ceil()
FValue UE::Shader::Ceil (const FValue & Value)
References Value.
CeilInPlace()
EValueType UE::Shader::CeilInPlace (EValueType Type, TArrayView< FValueComponent > Component)
References Component.
Clamp()
FValue UE::Shader::Clamp (const FValue & Value, const FValue & Low, const FValue & High)
References UE::High, UE::Low, and Value.
CombineComponentTypes()
EValueComponentType UE::Shader::CombineComponentTypes (EValueComponentType Lhs, EValueComponentType Rhs)
CombineTypes()
FType UE::Shader::CombineTypes (const FType & Lhs, const FType & Rhs, bool bMergeMatrixTypes = false)
Cos()
FValue UE::Shader::Cos (const FValue & Value)
References Value.
CosInPlace()
EValueType UE::Shader::CosInPlace (EValueType Type, TArrayView< FValueComponent > Component)
References Component.
Cross()
FValue UE::Shader::Cross (const FValue & Lhs, const FValue & Rhs)
Div()
FValue UE::Shader::Div (const FValue & Lhs, const FValue & Rhs)
DivInPlace()
EValueType UE::Shader::DivInPlace (EValueType LhsType, EValueType RhsType, TArrayView< FValueComponent > Component, int32 & OutComponentsConsumed)
References Component.
Dot()
FValue UE::Shader::Dot (const FValue & Lhs, const FValue & Rhs)
Exp()
FValue UE::Shader::Exp (const FValue & Value)
References Value.
Exp2()
FValue UE::Shader::Exp2 (const FValue & Value)
References Value.
Exp2InPlace()
EValueType UE::Shader::Exp2InPlace (EValueType Type, TArrayView< FValueComponent > Component)
References Component.
ExpInPlace()
EValueType UE::Shader::ExpInPlace (EValueType Type, TArrayView< FValueComponent > Component)
References Component.
FindValueType()
EValueType UE::Shader::FindValueType (FName Name)
References Name.
Floor()
FValue UE::Shader::Floor (const FValue & Value)
References Value.
FloorInPlace()
EValueType UE::Shader::FloorInPlace (EValueType Type, TArrayView< FValueComponent > Component)
References Component.
Fmod()
FValue UE::Shader::Fmod (const FValue & Lhs, const FValue & Rhs)
FmodInPlace()
EValueType UE::Shader::FmodInPlace (EValueType LhsType, EValueType RhsType, TArrayView< FValueComponent > Component, int32 & OutComponentsConsumed)
References Component.
Frac()
FValue UE::Shader::Frac (const FValue & Value)
References Value.
FracInPlace()
EValueType UE::Shader::FracInPlace (EValueType Type, TArrayView< FValueComponent > Component)
References Component.
Fractional()
FValue UE::Shader::Fractional (const FValue & Value)
References Value.
FractionalInPlace()
EValueType UE::Shader::FractionalInPlace (EValueType Type, TArrayView< FValueComponent > Component)
References Component.
GetComponentTypeName()
const TCHAR * UE::Shader::GetComponentTypeName (EValueComponentType Type) inline
Definition at line 81 of file ShaderTypes.h.
References GetValueComponentTypeDescription(), and UE::Shader::FValueComponentTypeDescription::Name.
GetComponentTypeSizeInBytes()
uint32 UE::Shader::GetComponentTypeSizeInBytes (EValueComponentType Type) inline
Definition at line 82 of file ShaderTypes.h.
References GetValueComponentTypeDescription(), and UE::Shader::FValueComponentTypeDescription::SizeInBytes.
GetTypeHash() [1/2]
uint32 UE::Shader::GetTypeHash (const FType & Type)
GetTypeHash() [2/2]
uint32 UE::Shader::GetTypeHash (const FValue & Value)
References Value.
GetValueComponentTypeDescription()
FValueComponentTypeDescription UE::Shader::GetValueComponentTypeDescription (EValueComponentType Type)
Referenced by GetComponentTypeName(), GetComponentTypeSizeInBytes(), and IsComponentTypeWithinBounds().
GetValueTypeDescription()
const FValueTypeDescription & UE::Shader::GetValueTypeDescription (EValueType Type)
Referenced by UE::Shader::FPreshaderType::GetNumComponents(), IsGenericType(), IsLWCType(), IsNumericMatrixType(), IsNumericScalarType(), IsNumericType(), and IsNumericVectorType().
Greater()
FValue UE::Shader::Greater (const FValue & Lhs, const FValue & Rhs)
GreaterEqual()
FValue UE::Shader::GreaterEqual (const FValue & Lhs, const FValue & Rhs)
IsComponentTypeWithinBounds()
bool UE::Shader::IsComponentTypeWithinBounds (EValueComponentType Type, FComponentBounds Bounds) inline
Definition at line 84 of file ShaderTypes.h.
References GetValueComponentTypeDescription(), and IsWithinBounds().
IsGenericType() [1/2]
bool UE::Shader::IsGenericType (EValueComponentType Type) inline
Definition at line 90 of file ShaderTypes.h.
References Numeric.
Referenced by UE::Shader::FType::IsGeneric(), and IsGenericType().
IsGenericType() [2/2]
bool UE::Shader::IsGenericType (EValueType Type) inline
Definition at line 154 of file ShaderTypes.h.
References Any, GetValueTypeDescription(), and IsGenericType().
IsLWCType() [1/2]
bool UE::Shader::IsLWCType (EValueComponentType Type) inline
Definition at line 91 of file ShaderTypes.h.
References Double.
Referenced by IsLWCType(), and UE::Shader::FType::IsNumericLWC().
IsLWCType() [2/2]
bool UE::Shader::IsLWCType (EValueType Type) inline
Definition at line 153 of file ShaderTypes.h.
References GetValueTypeDescription(), and IsLWCType().
IsNumericMatrixType()
bool UE::Shader::IsNumericMatrixType (EValueType Type) inline
Definition at line 174 of file ShaderTypes.h.
References UE::Shader::FValueTypeDescription::ComponentType, GetValueTypeDescription(), IsNumericType(), and UE::Shader::FValueTypeDescription::NumComponents.
Referenced by UE::Shader::FType::IsNumericMatrix().
IsNumericScalarType()
bool UE::Shader::IsNumericScalarType (EValueType Type) inline
Definition at line 164 of file ShaderTypes.h.
References UE::Shader::FValueTypeDescription::ComponentType, GetValueTypeDescription(), IsNumericType(), and UE::Shader::FValueTypeDescription::NumComponents.
Referenced by UE::Shader::FType::IsNumericScalar().
IsNumericType() [1/2]
bool UE::Shader::IsNumericType (EValueComponentType Type) inline
Definition at line 83 of file ShaderTypes.h.
References Void.
Referenced by UE::Shader::FType::IsNumeric(), IsNumericMatrixType(), IsNumericScalarType(), IsNumericType(), and IsNumericVectorType().
IsNumericType() [2/2]
bool UE::Shader::IsNumericType (EValueType Type) inline
Definition at line 162 of file ShaderTypes.h.
References GetValueTypeDescription(), and IsNumericType().
IsNumericVectorType()
bool UE::Shader::IsNumericVectorType (EValueType Type) inline
Definition at line 169 of file ShaderTypes.h.
References UE::Shader::FValueTypeDescription::ComponentType, GetValueTypeDescription(), IsNumericType(), and UE::Shader::FValueTypeDescription::NumComponents.
Referenced by UE::Shader::FType::IsNumericVector().
IsWithinBounds()
bool UE::Shader::IsWithinBounds (FComponentBounds Lhs, FComponentBounds Rhs) inline
Definition at line 53 of file ShaderTypes.h.
References UE::Shader::FComponentBounds::Max, and UE::Shader::FComponentBounds::Min.
Referenced by IsComponentTypeWithinBounds().
Less()
FValue UE::Shader::Less (const FValue & Lhs, const FValue & Rhs)
LessEqual()
FValue UE::Shader::LessEqual (const FValue & Lhs, const FValue & Rhs)
Log()
FValue UE::Shader::Log (const FValue & Value)
References Value.
Log10()
FValue UE::Shader::Log10 (const FValue & Value)
References Value.
Log10InPlace()
EValueType UE::Shader::Log10InPlace (EValueType Type, TArrayView< FValueComponent > Component)
References Component.
Log2()
FValue UE::Shader::Log2 (const FValue & Value)
References Value.
Log2InPlace()
EValueType UE::Shader::Log2InPlace (EValueType Type, TArrayView< FValueComponent > Component)
References Component.
LogInPlace()
EValueType UE::Shader::LogInPlace (EValueType Type, TArrayView< FValueComponent > Component)
References Component.
MakeConcreteType() [1/2]
EValueComponentType UE::Shader::MakeConcreteType (EValueComponentType Type) inline
Definition at line 89 of file ShaderTypes.h.
References Float, and Numeric.
Referenced by UE::Shader::FType::GetConcreteType().
MakeConcreteType() [2/2]
EValueType UE::Shader::MakeConcreteType (EValueType Type)
MakeDerivativeType()
EValueType UE::Shader::MakeDerivativeType (EValueType Type)
MakeNonLWCType() [1/2]
EValueComponentType UE::Shader::MakeNonLWCType (EValueComponentType Type) inline
Definition at line 88 of file ShaderTypes.h.
References Double, and Float.
Referenced by UE::Shader::FType::GetNonLWCType().
MakeNonLWCType() [2/2]
EValueType UE::Shader::MakeNonLWCType (EValueType Type)
MakeValueType() [1/2]
EValueType UE::Shader::MakeValueType (EValueComponentType ComponentType, int32 NumComponents)
Referenced by UE::Shader::FValue::FValue().
MakeValueType() [2/2]
EValueType UE::Shader::MakeValueType (EValueType BaseType, int32 NumComponents)
MakeValueTypeWithRequestedNumComponents()
EValueType UE::Shader::MakeValueTypeWithRequestedNumComponents (EValueType BaseType, int8 RequestedNumComponents)
Max()
FValue UE::Shader::Max (const FValue & Lhs, const FValue & Rhs)
MaxBound() [1/2]
EComponentBound UE::Shader::MaxBound (EComponentBound Lhs, EComponentBound Rhs) inline
Definition at line 32 of file ShaderTypes.h.
References FMath::Max.
Referenced by MaxBound().
MaxBound() [2/2]
FComponentBounds UE::Shader::MaxBound (FComponentBounds Lhs, FComponentBounds Rhs) inline
Definition at line 52 of file ShaderTypes.h.
References UE::Shader::FComponentBounds::Max, MaxBound(), and UE::Shader::FComponentBounds::Min.
MaxInPlace()
EValueType UE::Shader::MaxInPlace (EValueType LhsType, EValueType RhsType, TArrayView< FValueComponent > Component, int32 & OutComponentsConsumed)
References Component.
Min()
FValue UE::Shader::Min (const FValue & Lhs, const FValue & Rhs)
MinBound() [1/2]
EComponentBound UE::Shader::MinBound (EComponentBound Lhs, EComponentBound Rhs) inline
Definition at line 31 of file ShaderTypes.h.
References FMath::Min.
Referenced by MinBound().
MinBound() [2/2]
FComponentBounds UE::Shader::MinBound (FComponentBounds Lhs, FComponentBounds Rhs) inline
Definition at line 51 of file ShaderTypes.h.
References UE::Shader::FComponentBounds::Max, UE::Shader::FComponentBounds::Min, and MinBound().
MinInPlace()
EValueType UE::Shader::MinInPlace (EValueType LhsType, EValueType RhsType, TArrayView< FValueComponent > Component, int32 & OutComponentsConsumed)
References Component.
Modulo()
FValue UE::Shader::Modulo (const FValue & Lhs, const FValue & Rhs)
ModuloInPlace()
EValueType UE::Shader::ModuloInPlace (EValueType LhsType, EValueType RhsType, TArrayView< FValueComponent > Component, int32 & OutComponentsConsumed)
References Component.
Mul()
FValue UE::Shader::Mul (const FValue & Lhs, const FValue & Rhs)
MulInPlace()
EValueType UE::Shader::MulInPlace (EValueType LhsType, EValueType RhsType, TArrayView< FValueComponent > Component, int32 & OutComponentsConsumed)
References Component.
Neg()
FValue UE::Shader::Neg (const FValue & Value)
References Value.
NegInPlace()
EValueType UE::Shader::NegInPlace (EValueType Type, TArrayView< FValueComponent > Component)
References Component.
operator!=() [1/5]
bool UE::Shader::operator!= (const EValueType & Lhs, const FType & Rhs) inline
Definition at line 240 of file ShaderTypes.h.
References operator==().
operator!=() [2/5]
bool UE::Shader::operator!= (const FComponentBounds & Lhs, const FComponentBounds & Rhs) inline
Definition at line 46 of file ShaderTypes.h.
References operator==().
operator!=() [3/5]
bool UE::Shader::operator!= (const FType & Lhs, const EValueType & Rhs) inline
Definition at line 231 of file ShaderTypes.h.
References operator==().
operator!=() [4/5]
bool UE::Shader::operator!= (const FType & Lhs, const FType & Rhs) inline
Definition at line 222 of file ShaderTypes.h.
References operator==().
operator!=() [5/5]
bool UE::Shader::operator!= (const FValue & Lhs, const FValue & Rhs) inline
Definition at line 531 of file ShaderTypes.h.
References operator==().
operator==() [1/5]
bool UE::Shader::operator== (const EValueType & Lhs, const FType & Rhs) inline
Definition at line 236 of file ShaderTypes.h.
References UE::Shader::FType::IsStruct(), and UE::Shader::FType::ValueType.
operator==() [2/5]
bool UE::Shader::operator== (const FComponentBounds & Lhs, const FComponentBounds & Rhs) inline
Definition at line 42 of file ShaderTypes.h.
References UE::Shader::FComponentBounds::Max, and UE::Shader::FComponentBounds::Min.
Referenced by operator!=(), operator!=(), operator!=(), operator!=(), and operator!=().
operator==() [3/5]
bool UE::Shader::operator== (const FType & Lhs, const EValueType & Rhs) inline
Definition at line 227 of file ShaderTypes.h.
References UE::Shader::FType::IsStruct(), and UE::Shader::FType::ValueType.
operator==() [4/5]
bool UE::Shader::operator== (const FType & Lhs, const FType & Rhs) inline
Definition at line 215 of file ShaderTypes.h.
References Object, UE::Shader::FType::ObjectType, Struct, UE::Shader::FType::StructType, and UE::Shader::FType::ValueType.
operator==() [5/5]
bool UE::Shader::operator== (const FValue & Lhs, const FValue & Rhs)
Rcp()
FValue UE::Shader::Rcp (const FValue & Value)
References Value.
RcpInPlace()
EValueType UE::Shader::RcpInPlace (EValueType Type, TArrayView< FValueComponent > Component)
References Component.
Round()
FValue UE::Shader::Round (const FValue & Value)
References Value.
RoundInPlace()
EValueType UE::Shader::RoundInPlace (EValueType Type, TArrayView< FValueComponent > Component)
References Component.
Saturate()
FValue UE::Shader::Saturate (const FValue & Value)
References Value.
SaturateInPlace()
EValueType UE::Shader::SaturateInPlace (EValueType Type, TArrayView< FValueComponent > Component)
References Component.
Sign()
FValue UE::Shader::Sign (const FValue & Value)
References Value.
SignInPlace()
EValueType UE::Shader::SignInPlace (EValueType Type, TArrayView< FValueComponent > Component)
References Component.
Sin()
FValue UE::Shader::Sin (const FValue & Value)
References Value.
SinInPlace()
EValueType UE::Shader::SinInPlace (EValueType Type, TArrayView< FValueComponent > Component)
References Component.
Sqrt()
FValue UE::Shader::Sqrt (const FValue & Value)
References Value.
SqrtInPlace()
EValueType UE::Shader::SqrtInPlace (EValueType Type, TArrayView< FValueComponent > Component)
References Component.
Sub()
FValue UE::Shader::Sub (const FValue & Lhs, const FValue & Rhs)
SubInPlace()
EValueType UE::Shader::SubInPlace (EValueType LhsType, EValueType RhsType, TArrayView< FValueComponent > Component, int32 & OutComponentsConsumed)
References Component.
Tan()
FValue UE::Shader::Tan (const FValue & Value)
References Value.
TanInPlace()
EValueType UE::Shader::TanInPlace (EValueType Type, TArrayView< FValueComponent > Component)
References Component.
Trunc()
FValue UE::Shader::Trunc (const FValue & Value)
References Value.
TruncInPlace()
EValueType UE::Shader::TruncInPlace (EValueType Type, TArrayView< FValueComponent > Component)
References Component.
Variable Documentation
NumValueComponentTypes
int32 UE::Shader::NumValueComponentTypes = (int32)EValueComponentType::Num static constexpr
Definition at line 68 of file ShaderTypes.h.
NumValueTypes
int32 UE::Shader::NumValueTypes = (int32)EValueType::Num inline constexpr
Definition at line 140 of file ShaderTypes.h.