Unreal Engine 5.6 C++ API: BufferUtil Namespace Reference
BufferUtil Namespace Reference
Utility functions for processing arrays of objects.
Functions
template<typename T, typename EnumerableType>
void AppendElements (TArray< T > &AppendTo, EnumerableType Enumerable)
Append enumerable elements to an array.
template<typename T>
int CountValid (const TArray< T > &Data, const TFunction< bool(T)> &Predicate, int MaxIndex=-1, int StartIndex=0)
Count number of elements in array (or within requested range) that pass Predicate test.
template<typename T>
int FilterInPlace (TArray< T > &Data, const TFunction< bool(T)> &Predicate, int MaxIndex=-1, int StartIndex=0)
Removes elements of array (or within requested range) that do not pass Predicate, by shifting forward.
Detailed Description
Utility functions for processing arrays of objects.
Todo
possibly these functions should go in Algo:: or somewhere else in Core?
Function Documentation
AppendElements()
template<typename T, typename EnumerableType> void BufferUtil::AppendElements (TArray< T > & AppendTo, EnumerableType Enumerable)
Append enumerable elements to an array.
Parameters
Data array to append to
Enumerable object that can be iterated over with a range-based for loop
Definition at line 71 of file BufferUtil.h.
References TArray< InElementType, InAllocatorType >::Add().
CountValid()
template<typename T> int BufferUtil::CountValid (const TArray< T > & Data, const TFunction< bool(T)> & Predicate, int MaxIndex = -1, int StartIndex = 0)
Count number of elements in array (or within requested range) that pass Predicate test.
Parameters
Data Array to process
Predicate filtering function, return true indicates valid
MaxIndex optional maximum index in array (exclusive, default is to use array size)
StartIndex optional start index in array (default 0)
Returns
number of values in array that returned true for Predicate
Definition at line 24 of file BufferUtil.h.
References TArray< InElementType, InAllocatorType >::Num(), and Predicate.
FilterInPlace()
template<typename T> int BufferUtil::FilterInPlace (TArray< T > & Data, const TFunction< bool(T)> & Predicate, int MaxIndex = -1, int StartIndex = 0)
Removes elements of array (or within requested range) that do not pass Predicate, by shifting forward.
Does not remove remaining elements
Parameters
Data Array to process
Predicate filtering function, return true indicates valid
MaxIndex optional maximum index in array (exclusive, default is to use array size)
StartIndex optional start index in array (default 0)
Returns
Number of valid elements in Data after filtering
Definition at line 49 of file BufferUtil.h.
References TArray< InElementType, InAllocatorType >::Num(), and Predicate.