Unreal Engine 5.6 C++ API: Nanite::Private Namespace Reference
Nanite::Private Namespace Reference
Data Structures
struct FAuditMaterialSlotInfo
Functions
template<class T>
FString GetMaterialMeshName (const T &Object)
template<>
FString GetMaterialMeshName< FInstancedSkinnedMeshSceneProxyDesc > (const FInstancedSkinnedMeshSceneProxyDesc &Object)
template<>
FString GetMaterialMeshName< FSkinnedMeshSceneProxyDesc > (const FSkinnedMeshSceneProxyDesc &Object)
template<>
FString GetMaterialMeshName< USkinnedMeshComponent > (const USkinnedMeshComponent &Object)
template<class T>
TArray< FAuditMaterialSlotInfo, TInlineAllocator< 32 > > GetMaterialSlotInfos (const T &Object)
template<>
TArray< FAuditMaterialSlotInfo, TInlineAllocator< 32 > > GetMaterialSlotInfos< FInstancedSkinnedMeshSceneProxyDesc > (const FInstancedSkinnedMeshSceneProxyDesc &Object)
template<>
TArray< FAuditMaterialSlotInfo, TInlineAllocator< 32 > > GetMaterialSlotInfos< FSkinnedMeshSceneProxyDesc > (const FSkinnedMeshSceneProxyDesc &Object)
template<>
TArray< FAuditMaterialSlotInfo, TInlineAllocator< 32 > > GetMaterialSlotInfos< USkinnedMeshComponent > (const USkinnedMeshComponent &Object)
template<class T>
bool IsMaterialSkeletalMesh (const T &Object)
template<>
bool IsMaterialSkeletalMesh< FInstancedSkinnedMeshSceneProxyDesc > (const FInstancedSkinnedMeshSceneProxyDesc &Object)
template<>
bool IsMaterialSkeletalMesh< FSkinnedMeshSceneProxyDesc > (const FSkinnedMeshSceneProxyDesc &Object)
template<>
bool IsMaterialSkeletalMesh< USkinnedMeshComponent > (const USkinnedMeshComponent &Object)
Function Documentation
GetMaterialMeshName()
template<class T> FString Nanite::Private::GetMaterialMeshName (const T & Object)
Definition at line 53 of file NaniteResourcesHelper.h.
References Object.
Referenced by Nanite::FNaniteResourcesHelper::AuditMaterials().
GetMaterialMeshName< FInstancedSkinnedMeshSceneProxyDesc >()
template<> FString Nanite::Private::GetMaterialMeshName< FInstancedSkinnedMeshSceneProxyDesc > (const FInstancedSkinnedMeshSceneProxyDesc & Object)
References Object.
GetMaterialMeshName< FSkinnedMeshSceneProxyDesc >()
template<> FString Nanite::Private::GetMaterialMeshName< FSkinnedMeshSceneProxyDesc > (const FSkinnedMeshSceneProxyDesc & Object)
References Object.
GetMaterialMeshName< USkinnedMeshComponent >()
template<> FString Nanite::Private::GetMaterialMeshName< USkinnedMeshComponent > (const USkinnedMeshComponent & Object)
References Object.
GetMaterialSlotInfos()
template<class T> TArray< FAuditMaterialSlotInfo, TInlineAllocator< 32 > > Nanite::Private::GetMaterialSlotInfos (const T & Object)
Definition at line 65 of file NaniteResourcesHelper.h.
References TArray< InElementType, InAllocatorType >::Add(), Material, Object, StaticMaterials, and Nanite::StaticMesh.
Referenced by Nanite::FNaniteResourcesHelper::AuditMaterials().
GetMaterialSlotInfos< FInstancedSkinnedMeshSceneProxyDesc >()
template<> TArray< FAuditMaterialSlotInfo, TInlineAllocator< 32 > > Nanite::Private::GetMaterialSlotInfos< FInstancedSkinnedMeshSceneProxyDesc > (const FInstancedSkinnedMeshSceneProxyDesc & Object)
References Object.
GetMaterialSlotInfos< FSkinnedMeshSceneProxyDesc >()
template<> TArray< FAuditMaterialSlotInfo, TInlineAllocator< 32 > > Nanite::Private::GetMaterialSlotInfos< FSkinnedMeshSceneProxyDesc > (const FSkinnedMeshSceneProxyDesc & Object)
GetMaterialSlotInfos< USkinnedMeshComponent >()
template<> TArray< FAuditMaterialSlotInfo, TInlineAllocator< 32 > > Nanite::Private::GetMaterialSlotInfos< USkinnedMeshComponent > (const USkinnedMeshComponent & Object)
IsMaterialSkeletalMesh()
template<class T> bool Nanite::Private::IsMaterialSkeletalMesh (const T & Object)
Definition at line 59 of file NaniteResourcesHelper.h.
References Object.
Referenced by Nanite::FNaniteResourcesHelper::AuditMaterials().
IsMaterialSkeletalMesh< FInstancedSkinnedMeshSceneProxyDesc >()
template<> bool Nanite::Private::IsMaterialSkeletalMesh< FInstancedSkinnedMeshSceneProxyDesc > (const FInstancedSkinnedMeshSceneProxyDesc & Object)
IsMaterialSkeletalMesh< FSkinnedMeshSceneProxyDesc >()
template<> bool Nanite::Private::IsMaterialSkeletalMesh< FSkinnedMeshSceneProxyDesc > (const FSkinnedMeshSceneProxyDesc & Object)
References Object.
IsMaterialSkeletalMesh< USkinnedMeshComponent >()
template<> bool Nanite::Private::IsMaterialSkeletalMesh< USkinnedMeshComponent > (const USkinnedMeshComponent & Object)
References Object.