Unreal Engine 5.6 C++ API: TaskTrace Namespace Reference
TaskTrace Namespace Reference
Data Structures
struct FTaskTimingEventScope
struct FWaitingScope
Typedefs
using FId = uint64
Functions
void Completed (FId TaskId)
void Created (FId TaskId, uint64 TaskSize)
void Destroyed (FId TaskId)
void Finished (FId TaskId)
FId GenerateTaskId ()
void Init ()
void Launched (FId TaskId, const TCHAR *DebugName, bool bTracked, ENamedThreads::Type ThreadToExecuteOn, uint64 TaskSize)
void Scheduled (FId TaskId)
void Started (FId TaskId)
void SubsequentAdded (FId TaskId, FId SubsequentId)
UE_TRACE_CHANNEL_EXTERN (TaskChannel, 1)
Variables
const FId InvalidId = ~FId(0)
constexpr uint32 TaskTraceVersion = 1
Typedef Documentation
FId
using TaskTrace::FId = uint64
Definition at line 37 of file TaskTrace.h.
Function Documentation
Completed()
void TaskTrace::Completed (FId TaskId) inline
Definition at line 82 of file TaskTrace.h.
Referenced by UE::Tasks::Private::FTaskBase::Close(), and ENUM_CLASS_FLAGS().
Created()
void TaskTrace::Created (FId TaskId, uint64 TaskSize) inline
Definition at line 76 of file TaskTrace.h.
Referenced by FGraphEventImpl::FGraphEventImpl(), UE::Tasks::Private::FTaskEventBase::FTaskEventBase(), and TGraphTask< TTask >::FConstructor::ConstructAndHold().
Destroyed()
void TaskTrace::Destroyed (FId TaskId) inline
Definition at line 83 of file TaskTrace.h.
Referenced by UE::Tasks::Private::FTaskBase::~FTaskBase(), and ENUM_CLASS_FLAGS().
Finished()
void TaskTrace::Finished (FId TaskId) inline
Definition at line 81 of file TaskTrace.h.
GenerateTaskId()
FId TaskTrace::GenerateTaskId () inline
Definition at line 74 of file TaskTrace.h.
References InvalidId.
Referenced by ENUM_CLASS_FLAGS().
Init()
void TaskTrace::Init () inline
Definition at line 75 of file TaskTrace.h.
Launched()
void TaskTrace::Launched (FId TaskId, const TCHAR * DebugName, bool bTracked, ENamedThreads::Type ThreadToExecuteOn, uint64 TaskSize) inline
Definition at line 77 of file TaskTrace.h.
Referenced by ENUM_CLASS_FLAGS(), and UE::Tasks::Private::FTaskBase::TryLaunch().
Scheduled()
void TaskTrace::Scheduled (FId TaskId) inline
Definition at line 78 of file TaskTrace.h.
Started()
void TaskTrace::Started (FId TaskId) inline
Definition at line 80 of file TaskTrace.h.
Referenced by ENUM_CLASS_FLAGS().
SubsequentAdded()
void TaskTrace::SubsequentAdded (FId TaskId, FId SubsequentId) inline
Definition at line 79 of file TaskTrace.h.
Referenced by UE::Tasks::Private::FTaskBase::AddSubsequent().
UE_TRACE_CHANNEL_EXTERN()
TaskTrace::UE_TRACE_CHANNEL_EXTERN (TaskChannel , 1)
Variable Documentation
InvalidId
const FId TaskTrace::InvalidId = ~FId(0) inline
Definition at line 39 of file TaskTrace.h.
Referenced by ENUM_CLASS_FLAGS(), GenerateTaskId(), and UE::Tasks::Private::FTaskBase::GetTraceId().
TaskTraceVersion
uint32 TaskTrace::TaskTraceVersion = 1 inline constexpr
Definition at line 41 of file TaskTrace.h.