Unreal Engine 5.6 C++ API: SpecularProfile Namespace Reference
SpecularProfile Namespace Reference
Specular profile asset, can be specified at a material.
Functions
int32 AddOrUpdateProfile (const USpecularProfile *InProfile, const FGuid &InGuid, const FSpecularProfileStruct InSettings, const FTextureReference *InTexture)
FName CreateSpecularProfileParameterName (USpecularProfile *InProfile)
float GetSpecularProfileId (const USpecularProfile *In)
FName GetSpecularProfileParameterName (const USpecularProfile *InProfile)
FRHITexture * GetSpecularProfileTextureAtlas ()
FRHITexture * GetSpecularProfileTextureAtlasWithFallback ()
void UpdateSpecularProfileTextureAtlas (FRDGBuilder &GraphBuilder, EShaderPlatform ShaderPlatform)
Detailed Description
Specular profile asset, can be specified at a material.
Don't change at runtime. All properties in here are per material.
Function Documentation
AddOrUpdateProfile()
int32 SpecularProfile::AddOrUpdateProfile (const USpecularProfile * InProfile, const FGuid & InGuid, const FSpecularProfileStruct InSettings, const FTextureReference * InTexture)
References AddOrUpdateProfile().
Referenced by AddOrUpdateProfile().
CreateSpecularProfileParameterName()
FName SpecularProfile::CreateSpecularProfileParameterName (USpecularProfile * InProfile)
References CreateSpecularProfileParameterName().
Referenced by CreateSpecularProfileParameterName().
GetSpecularProfileId()
float SpecularProfile::GetSpecularProfileId (const USpecularProfile * In)
References GetSpecularProfileId().
Referenced by GetSpecularProfileId().
GetSpecularProfileParameterName()
FName SpecularProfile::GetSpecularProfileParameterName (const USpecularProfile * InProfile)
References GetSpecularProfileParameterName().
Referenced by GetSpecularProfileParameterName().
GetSpecularProfileTextureAtlas()
FRHITexture * SpecularProfile::GetSpecularProfileTextureAtlas ()
References GetSpecularProfileTextureAtlas().
Referenced by GetSpecularProfileTextureAtlas().
GetSpecularProfileTextureAtlasWithFallback()
FRHITexture * SpecularProfile::GetSpecularProfileTextureAtlasWithFallback ()
References GetSpecularProfileTextureAtlasWithFallback().
Referenced by GetSpecularProfileTextureAtlasWithFallback().
UpdateSpecularProfileTextureAtlas()
void SpecularProfile::UpdateSpecularProfileTextureAtlas (FRDGBuilder & GraphBuilder, EShaderPlatform ShaderPlatform)
References ShaderPlatform, and UpdateSpecularProfileTextureAtlas().
Referenced by UpdateSpecularProfileTextureAtlas().