Unreal Engine 5.6 C++ API: UE::Core::Private::Tuple Namespace Reference
UE::Core::Private::Tuple Namespace Reference
Data Structures
struct FEqualityHelper
struct FEqualityHelper< ArgCount, ArgCount >
struct TCVTupleArity
struct TCVTupleArity< const volatile TTuple< Types... > >
struct TCVTupleElement
struct TCVTupleElement< Index, const volatile TTuple< TupleTypes... > >
struct TCVTupleIndex
struct TCVTupleIndex< Type, const volatile TTuple< TupleTypes... > >
struct TGetTupleHashHelper
struct TGetTupleHashHelper< ArgIndex, ArgIndex >
struct TLessThanHelper
struct TLessThanHelper< NumArgs, ArgToCompare, true >
struct TLessThanHelper< NumArgs, NumArgs, false >
struct TTransformTuple_Impl
struct TTransformTuple_Impl< TIntegerSequence< uint32, Indices... > >
struct TTupleBase
struct TTupleBase< TIntegerSequence< uint32, Indices... >, Types... >
struct TTupleBaseElement
struct TTupleBaseElement< T, 0, 2 >
struct TTupleElementGetterByIndex
struct TTupleElementGetterByIndex< 0, 2 >
struct TTupleElementGetterByType
struct TVisitTupleElements_Impl
struct TVisitTupleElements_Impl< TIntegerSequence< uint32, Indices... > >
Enumerations
enum EForwardingConstructor { ForwardingConstructor }
enum EOtherTupleConstructor { OtherTupleConstructor }
Functions
template<typename LhsType, typename RhsType, uint32... Indices, decltype(ConceptCheckingHelper((DeclVal< LhsType & >().template Get< Indices >()=DeclVal< RhsType && >().template Get< Indices >(), 0)...)) * = nullptr>
static void Assign (LhsType &Lhs, RhsType &&Rhs, TIntegerSequence< uint32, Indices... >)
template<typename... Given, typename... Deduced>
decltype(ConceptCheckingHelper((DeclVal< Given >()=DeclVal< Deduced && >(), 0)...)) AssignableConceptCheck (Deduced &&...)
template<typename... ArgTypes>
void ConceptCheckingHelper (ArgTypes &&...)
template<typename... Given, typename... Deduced>
std::enable_if_t< std::conjunction_v< std::is_constructible< Given, Deduced && >... > > ConstructibleConceptCheck (Deduced &&...)
template<typename... ElementTypes, typename... Types>
FORCEINLINE TTuple< ElementTypes... > MakeTupleImpl (Types &&... Args)
Variables
template<typename T, typename... Types>
constexpr uint32 TTypeCountInParameterPack_V = 0
template<typename T, typename U, typename... Types>
constexpr uint32 TTypeCountInParameterPack_V< T, U, Types... > = TTypeCountInParameterPack_V<T, Types...> + (std::is_same_v<T, U> ? 1 : 0)
Enumeration Type Documentation
EForwardingConstructor
enum UE::Core::Private::Tuple::EForwardingConstructor
Enumerator
ForwardingConstructor
Definition at line 53 of file Tuple.h.
EOtherTupleConstructor
enum UE::Core::Private::Tuple::EOtherTupleConstructor
Enumerator
OtherTupleConstructor
Definition at line 54 of file Tuple.h.
Function Documentation
Assign()
template<typename LhsType, typename RhsType, uint32... Indices, decltype(ConceptCheckingHelper((DeclVal< LhsType & >().template Get< Indices >()=DeclVal< RhsType && >().template Get< Indices >(), 0)...)) * = nullptr> void UE::Core::Private::Tuple::Assign (LhsType & Lhs, RhsType && Rhs, TIntegerSequence< uint32, Indices... >) static
Definition at line 509 of file Tuple.h.
References Forward().
Referenced by TTuple< const UFleshAsset *, const UFleshComponent *, FTransform >::operator=(), and TTuple< const UFleshAsset *, const UFleshComponent *, FTransform >::operator=().
AssignableConceptCheck()
template<typename... Given, typename... Deduced> decltype(ConceptCheckingHelper((DeclVal< Given >()=DeclVal< Deduced && >(), 0)...)) UE::Core::Private::Tuple::AssignableConceptCheck (Deduced && ...)
References DeclVal().
Referenced by TTuple< const UFleshAsset *, const UFleshComponent *, FTransform >::operator=().
ConceptCheckingHelper()
template<typename... ArgTypes> void UE::Core::Private::Tuple::ConceptCheckingHelper (ArgTypes && ...)
ConstructibleConceptCheck()
template<typename... Given, typename... Deduced> std::enable_if_t< std::conjunction_v< std::is_constructible< Given, Deduced && >... > > UE::Core::Private::Tuple::ConstructibleConceptCheck (Deduced && ...)
MakeTupleImpl()
template<typename... ElementTypes, typename... Types> FORCEINLINE TTuple< ElementTypes... > UE::Core::Private::Tuple::MakeTupleImpl (Types &&... Args)
Definition at line 517 of file Tuple.h.
References FORCEINLINE, and Forward().
Referenced by ForwardAsTuple(), and MakeTuple().
Variable Documentation
TTypeCountInParameterPack_V
template<typename T, typename... Types> uint32 UE::Core::Private::Tuple::TTypeCountInParameterPack_V = 0 constexpr
Definition at line 61 of file Tuple.h.
Referenced by UE::Core::Private::Tuple::TTupleBase< TIntegerSequence< uint32, Indices... >, Types... >::Get(), UE::Core::Private::Tuple::TTupleBase< TIntegerSequence< uint32, Indices... >, Types... >::Get(), UE::Core::Private::Tuple::TTupleBase< TIntegerSequence< uint32, Indices... >, Types... >::Get(), UE::Core::Private::Tuple::TTupleBase< TIntegerSequence< uint32, Indices... >, Types... >::Get(), UE::Core::Private::Tuple::TTupleBase< TIntegerSequence< uint32, Indices... >, Types... >::Get(), UE::Core::Private::Tuple::TTupleBase< TIntegerSequence< uint32, Indices... >, Types... >::Get(), UE::Core::Private::Tuple::TTupleBase< TIntegerSequence< uint32, Indices... >, Types... >::Get(), and UE::Core::Private::Tuple::TTupleBase< TIntegerSequence< uint32, Indices... >, Types... >::Get().
TTypeCountInParameterPack_V< T, U, Types... >
template<typename T, typename U, typename... Types> uint32 UE::Core::Private::Tuple::TTypeCountInParameterPack_V< T, U, Types... > = TTypeCountInParameterPack_V<T, Types...> + (std::is_same_v<T, U> ? 1 : 0) constexpr
Definition at line 64 of file Tuple.h.