Unreal Engine 5.6 C++ API: UE::GizmoUtil Namespace Reference
UE::GizmoUtil Namespace Reference
Gizmo builder that simply calls a particular lambda when building a gizmo.
Data Structures
struct FInitMeshSubGizmoParams
struct FTransformSubGizmoCommonParams
Common parameters needed for initializing a sub gizmo.
struct FTransformSubGizmoSharedState
A struct to hold some objects that can be reused across multiple sub gizmos that operate on the same compound gizmo, to avoid creating redundant objects.
Functions
template<typename GizmoClass>
GizmoClass * CreateGizmoViaSimpleBuilder (UInteractiveGizmoManager *GizmoManager, const FString &InstanceIdentifier, void *GizmoOwner)
Template version of CreateGizmoViaSimpleBuilder that does a cast on return.
INTERACTIVETOOLSFRAMEWORK_API UInteractiveGizmo * CreateGizmoViaSimpleBuilder (UInteractiveGizmoManager *GizmoManager, TSubclassOf< UInteractiveGizmo > GizmoClass, const FString &InstanceIdentifier, void *Owner)
Uses the gizmo manager to create a gizmo of the given class (assuming that the gizmo type does not need any special setup beyond instantiation) without having to register a custom builder for that class ahead of time.
INTERACTIVETOOLSFRAMEWORK_API FTransform GetRotatedBasisTransform (const FTransform &TransformIn, EAxis::Type AxisToBeX)
Rotates a transform such that its basis still lies along the cardinal axes but rotated in such a way that the given axis is in the X direction.
INTERACTIVETOOLSFRAMEWORK_API void InitializeSubGizmoElementsWithMesh (const FInitMeshSubGizmoParams &Params, TArray< TPair< ETransformGizmoSubElements, UViewAdjustedStaticMeshGizmoComponent * > > *ElementComponentsOut=nullptr)
Given a UCombinedTransformGizmo, swaps selected elements with custom meshes.
Detailed Description
Gizmo builder that simply calls a particular lambda when building a gizmo.
This file is meant for utilities that are specific to allowing gizmos to act as sub gizmos inside a UCombinedTransformGizmo.
Makes it easy to register gizmo build behavior without writing a new class.
Function Documentation
CreateGizmoViaSimpleBuilder() [1/2]
template<typename GizmoClass> GizmoClass * UE::GizmoUtil::CreateGizmoViaSimpleBuilder (UInteractiveGizmoManager * GizmoManager, const FString & InstanceIdentifier, void * GizmoOwner)
Template version of CreateGizmoViaSimpleBuilder that does a cast on return.
Definition at line 55 of file GizmoUtil.h.
References Cast(), and CreateGizmoViaSimpleBuilder().
CreateGizmoViaSimpleBuilder() [2/2]
INTERACTIVETOOLSFRAMEWORK_API UInteractiveGizmo * UE::GizmoUtil::CreateGizmoViaSimpleBuilder (UInteractiveGizmoManager * GizmoManager, TSubclassOf< UInteractiveGizmo > GizmoClass, const FString & InstanceIdentifier, void * Owner)
Uses the gizmo manager to create a gizmo of the given class (assuming that the gizmo type does not need any special setup beyond instantiation) without having to register a custom builder for that class ahead of time.
This function lets the user bypass the need to define, register, and use a builder class, while still registering the gizmo properly with the gizmo manager. Under the hood, it creates and registers a temporary generic builder, uses it to make the gizmo, and then immediately deregisters the builder.
References Owner.
Referenced by CreateGizmoViaSimpleBuilder().
GetRotatedBasisTransform()
INTERACTIVETOOLSFRAMEWORK_API FTransform UE::GizmoUtil::GetRotatedBasisTransform (const FTransform & TransformIn, EAxis::Type AxisToBeX)
Rotates a transform such that its basis still lies along the cardinal axes but rotated in such a way that the given axis is in the X direction.
For example, if you have a transform that makes a component work well as an X axis in a TRS gizmo, using this function with AxisToBeX set to Y will rotate the transform to work well as the Y axis, because the basis will have been rotated to be YZX.
InitializeSubGizmoElementsWithMesh()
INTERACTIVETOOLSFRAMEWORK_API void UE::GizmoUtil::InitializeSubGizmoElementsWithMesh (const FInitMeshSubGizmoParams & Params, TArray< TPair< ETransformGizmoSubElements, UViewAdjustedStaticMeshGizmoComponent * > > * ElementComponentsOut = nullptr)
Given a UCombinedTransformGizmo, swaps selected elements with custom meshes.
Parameters
ComponentsOut Optional output array of newly created gizmo components, as pairs with the single element that they were created for.
References Params.