Unreal Engine 5.6 C++ API: FNavigationSystem Namespace Reference
FNavigationSystem Namespace Reference
Enumerations
enum class ECleanupMode : uint8 { CleanupWithWorld , CleanupUnsafe }
Functions
FNavigationElementHandle AddNavigationElement (UWorld *World, FNavigationElement &&Element)
void AddNavigationSystemToWorld (UWorld &WorldOwner, const FNavigationSystemRunMode RunMode=FNavigationSystemRunMode::InvalidMode, UNavigationSystemConfig *NavigationSystemConfig=nullptr, const bool bInitializeForWorld=true, const bool bOverridePreviousNavSys=false)
Creates an instance of NavigationSystem (class being specified by WorldSetting's NavigationSystemConfig) A new instance will be created only if given WorldOwner doesn't have one yet.
FORCEINLINE bool BoxesAreSame (const FBox &A, const FBox &B)
void Build (UWorld &World)
AActor & DECLARE_DELEGATE_OneParam (FActorComponentBasedSignature, UActorComponent &)
DECLARE_DELEGATE_OneParam (FControllerBasedSignature, const AController &)
DECLARE_DELEGATE_OneParam (FLevelBasedSignature, ULevel &)
UWorld const FBox TConstArrayView< FBox > DECLARE_DELEGATE_OneParam (FObjectBasedSignature, UObject &)
DECLARE_DELEGATE_OneParam (FSceneComponentBasedSignature, USceneComponent &)
DECLARE_DELEGATE_OneParam (FWorldBasedSignature, UWorld &)
DECLARE_DELEGATE_RetVal (const FNavDataConfig &, FNavDataConfigBasedSignature)
DECLARE_DELEGATE_RetVal (TSubclassOf< AActor >, FNavDataClassFetchSignature)
DECLARE_DELEGATE_RetVal (TSubclassOf< UNavAreaBase >, FNavAreaBasedSignature)
DECLARE_DELEGATE_RetVal_OneParam (bool, FBoolActorComponentBasedSignature, UActorComponent &)
DECLARE_DELEGATE_RetVal_OneParam (bool, FBoolControllerBasedSignature, const AController &)
DECLARE_DELEGATE_RetVal_OneParam (bool, FSupportsDynamicChangesSignature, UWorld *)
DECLARE_DELEGATE_RetVal_OneParam (const FNavDataConfig &, FNavDataConfigAndWorldSignature, const UWorld *)
DECLARE_DELEGATE_RetVal_OneParam (double, FDoubleWorldBasedSignature, const UWorld &)
DECLARE_DELEGATE_RetVal_OneParam (INavigationDataInterface *, FNavDataForActorSignature, const AActor &)
DECLARE_DELEGATE_RetVal_OneParam (INavigationDataInterface *, FNavDataForPropsSignature, const FNavAgentProperties &)
DECLARE_DELEGATE_RetVal_TwoParams (FNavigationElementHandle, FAddNavigationElementSignature, UWorld *, FNavigationElement &&)
DECLARE_DELEGATE_ThreeParams (FObjectBoundsChangedSignature, UObject &, const FBox &, TConstArrayView< FBox >) DECLARE_DELEGATE_OneParam(FActorBasedSignature
DECLARE_DELEGATE_ThreeParams (FUpdateNavigationElementSignature, UWorld *, FNavigationElementHandle, FNavigationElement &&) DECLARE_DELEGATE_FourParams(FUpdateNavigationElementBoundsSignature
DECLARE_DELEGATE_TwoParams (FActorBooleBasedSignature, AActor &, bool)
DECLARE_DELEGATE_TwoParams (FNavigationAutoUpdateEnableSignature, const bool, UNavigationSystemBase *)
DECLARE_DELEGATE_TwoParams (FRemoveNavigationElementSignature, UWorld *, FNavigationElementHandle)
DECLARE_DELEGATE_TwoParams (FWorldBoolBasedSignature, UWorld &, const bool)
DECLARE_DELEGATE_TwoParams (FWorldByteBasedSignature, UWorld &, uint8)
DECLARE_MULTICAST_DELEGATE_OneParam (FOnNavigationInitSignature, const UNavigationSystemBase &)
DECLARE_MULTICAST_DELEGATE_TwoParams (FOnNavAreaGenericEvent, const UWorld &, const UClass *)
void DiscardNavigationDataChunks (UWorld &InWorld)
Discards all navigation data chunks in all sub-levels.
IPathFollowingAgentInterface * FindPathFollowingAgentForActor (const AActor &Actor)
const FNavDataConfig & GetBiggestSupportedAgent (const UWorld *World)
const FTransform & GetCoordTransform (const ENavigationCoordSystem::Type FromCoordType, const ENavigationCoordSystem::Type ToCoordType)
Retrieves the transform the Navigation System is using to convert coords from FromCoordType to ToCoordType.
template<typename TNavSys>
FORCEINLINE const TNavSys * GetCurrent (const UWorld *World)
template<typename TNavSys>
TNavSys * GetCurrent (UObject *WorldContextObject)
template<typename TNavSys>
FORCEINLINE TNavSys * GetCurrent (UWorld *World)
TSubclassOf< AActor > GetDefaultNavDataClass ()
TSubclassOf< UNavAreaBase > GetDefaultObstacleArea ()
const FNavDataConfig & GetDefaultSupportedAgent ()
TSubclassOf< UNavAreaBase > GetDefaultWalkableArea ()
INavigationDataInterface * GetNavDataForActor (const AActor &Actor)
UWorld * GetWorldFromContextObject (UObject *WorldContextObject)
double GetWorldPartitionNavigationDataBuilderOverlap (const UWorld &World)
bool HasComponentData (UActorComponent &Comp)
constexpr FBox InvalidBoundingBox (ForceInit, UE::Math::TBoxConstInit{})
bool IsEditorRunMode (const FNavigationSystemRunMode Mode)
bool IsFollowingAPath (const AController &Controller)
bool IsInBaseNavmesh (const UObject *Object)
Objects placed directly in the level and objects placed in the base navmesh data layers are in the base navmesh.
bool IsLevelVisibilityChanging (const UObject *Object)
Returns true if the visibility of the owning level is currently changing (loading/unloading).
FORCEINLINE bool IsValidLocation (const FVector &TestLocation)
void OnActorBoundsChanged (AActor &Actor)
void OnActorRegistered (AActor &Actor)
void OnActorUnregistered (AActor &Actor)
void OnComponentRegistered (UActorComponent &Comp)
void OnComponentTransformChanged (USceneComponent &Comp)
void OnComponentUnregistered (UActorComponent &Comp)
void OnNavigationElementBoundsChanged (UWorld *World, FNavigationElementHandle ElementHandle, const FBox &NewBounds, TConstArrayView< FBox > DirtyAreas)
void OnObjectBoundsChanged (UObject &Object, const FBox &NewBounds, TConstArrayView< FBox > DirtyAreas)
void OnPIEEnd (UWorld &World)
void OnPIEStart (UWorld &World)
void OnPostEditActorMove (AActor &Actor)
void RegisterComponent (UActorComponent &Comp)
void RegisterNavRelevantObject (UObject &Object)
void RemoveActorData (AActor &Actor)
void RemoveNavigationElement (UWorld *World, FNavigationElementHandle ElementHandle)
void SetNavigationAutoUpdateEnabled (const bool bNewEnable, UNavigationSystemBase *InNavigationSystem)
void StopMovement (const AController &Controller)
bool SupportsDynamicChanges (UWorld *World)
UE_DEPRECATED (5.4, "Use FObjectBoundsChangedSignature delegate taking UObject and list of dirty areas as parameters instead.") DECLARE_DELEGATE_ThreeParams(FComponentBoundsChangeSignature
UE_DEPRECATED (5.4, "Use OnObjectBoundsChanged taking UObject and list of dirty areas as parameters instead.") 1 void OnComponentBoundsChanged(UActorComponent &Comp
void UnregisterComponent (UActorComponent &Comp)
void UnregisterNavRelevantObject (UObject &Object)
void UpdateActorAndComponentData (AActor &Actor, bool bUpdateAttachedActors=true)
void UpdateActorData (AActor &Actor)
void UpdateComponentData (UActorComponent &Comp)
void UpdateComponentDataAfterMove (USceneComponent &Comp)
void UpdateLevelCollision (ULevel &Level)
void UpdateNavigationElement (UWorld *World, FNavigationElementHandle ElementHandle, FNavigationElement &&Element)
void UpdateNavRelevantObject (UObject &Object)
void VerifyNavigationRenderingComponents (UWorld &World, const bool bShow)
bool WantsComponentChangeNotifies ()
Variables
const FBox const FBox & DirtyArea
const float FallbackAgentHeight
used as a fallback value for navigation agent height, when none specified via UNavigationSystemV1::SupportedAgents
const float FallbackAgentRadius
used as a fallback value for navigation agent radius, when none specified via UNavigationSystemV1::SupportedAgents
UWorld FNavigationElementHandle
constexpr FVector InvalidLocation = FVector(TNumericLimits<FVector::FReal>::Max(), UE::Math::TVectorConstInit{})
const FBox & NewBounds
Enumeration Type Documentation
ECleanupMode
enum class FNavigationSystem::ECleanupMode : uint8 strong
Enumerator
CleanupWithWorld
CleanupUnsafe
Definition at line 197 of file NavigationSystemBase.h.
Function Documentation
AddNavigationElement()
FNavigationElementHandle FNavigationSystem::AddNavigationElement (UWorld * World, FNavigationElement && Element)
References AddNavigationElement(), and FNavigationElementHandle.
Referenced by AddNavigationElement().
AddNavigationSystemToWorld()
void FNavigationSystem::AddNavigationSystemToWorld (UWorld & WorldOwner, const FNavigationSystemRunMode RunMode = FNavigationSystemRunMode::InvalidMode, UNavigationSystemConfig * NavigationSystemConfig = nullptr, const bool bInitializeForWorld = true, const bool bOverridePreviousNavSys = false)
Creates an instance of NavigationSystem (class being specified by WorldSetting's NavigationSystemConfig) A new instance will be created only if given WorldOwner doesn't have one yet.
The new instance will be assigned to the given WorldOwner (via SetNavigationSystem call) and depending on value of bInitializeForWorld the InitializeForWorld function will be called on the new NavigationSystem instance. (
See also
UWorld.NavigationSystem)
Parameters
RunMode if set to a valid value (other than FNavigationSystemRunMode::InvalidMode) will also configure the created NavigationSystem instance for that mode
NavigationSystemConfig is used to pick the navigation system's class and set it up. If null then WorldOwner.WorldSettings.NavigationSystemConfig will be used
BoxesAreSame()
FORCEINLINE bool FNavigationSystem::BoxesAreSame (const FBox & A, const FBox & B)
Definition at line 54 of file NavigationTypes.h.
References A, B, FORCEINLINE, and UE::Math::TVector< double >::PointsAreSame().
Build()
void FNavigationSystem::Build (UWorld & World)
References Build().
Referenced by Build().
DECLARE_DELEGATE_OneParam() [1/6]
AActor & FNavigationSystem::DECLARE_DELEGATE_OneParam (FActorComponentBasedSignature , UActorComponent &)
References DECLARE_DELEGATE_OneParam().
DECLARE_DELEGATE_OneParam() [2/6]
FNavigationSystem::DECLARE_DELEGATE_OneParam (FControllerBasedSignature , const AController &)
References DECLARE_DELEGATE_OneParam().
DECLARE_DELEGATE_OneParam() [3/6]
FNavigationSystem::DECLARE_DELEGATE_OneParam (FLevelBasedSignature , ULevel &)
References DECLARE_DELEGATE_OneParam().
DECLARE_DELEGATE_OneParam() [4/6]
UWorld const FBox TConstArrayView< FBox > FNavigationSystem::DECLARE_DELEGATE_OneParam (FObjectBasedSignature , UObject &)
References DECLARE_DELEGATE_OneParam().
Referenced by DECLARE_DELEGATE_OneParam(), DECLARE_DELEGATE_OneParam(), DECLARE_DELEGATE_OneParam(), DECLARE_DELEGATE_OneParam(), DECLARE_DELEGATE_OneParam(), DECLARE_DELEGATE_OneParam(), and DECLARE_DELEGATE_ThreeParams().
DECLARE_DELEGATE_OneParam() [5/6]
FNavigationSystem::DECLARE_DELEGATE_OneParam (FSceneComponentBasedSignature , USceneComponent &)
References DECLARE_DELEGATE_OneParam().
DECLARE_DELEGATE_OneParam() [6/6]
FNavigationSystem::DECLARE_DELEGATE_OneParam (FWorldBasedSignature , UWorld &)
References DECLARE_DELEGATE_OneParam().
DECLARE_DELEGATE_RetVal() [1/3]
FNavigationSystem::DECLARE_DELEGATE_RetVal (const FNavDataConfig & , FNavDataConfigBasedSignature)
References DECLARE_DELEGATE_RetVal().
DECLARE_DELEGATE_RetVal() [2/3]
FNavigationSystem::DECLARE_DELEGATE_RetVal (TSubclassOf< AActor > , FNavDataClassFetchSignature)
References DECLARE_DELEGATE_RetVal().
DECLARE_DELEGATE_RetVal() [3/3]
FNavigationSystem::DECLARE_DELEGATE_RetVal (TSubclassOf< UNavAreaBase > , FNavAreaBasedSignature)
References DECLARE_DELEGATE_RetVal().
Referenced by DECLARE_DELEGATE_RetVal(), DECLARE_DELEGATE_RetVal(), and DECLARE_DELEGATE_RetVal().
DECLARE_DELEGATE_RetVal_OneParam() [1/7]
FNavigationSystem::DECLARE_DELEGATE_RetVal_OneParam (bool , FBoolActorComponentBasedSignature , UActorComponent &)
References DECLARE_DELEGATE_RetVal_OneParam().
DECLARE_DELEGATE_RetVal_OneParam() [2/7]
FNavigationSystem::DECLARE_DELEGATE_RetVal_OneParam (bool , FBoolControllerBasedSignature , const AController &)
References DECLARE_DELEGATE_RetVal_OneParam().
DECLARE_DELEGATE_RetVal_OneParam() [3/7]
FNavigationSystem::DECLARE_DELEGATE_RetVal_OneParam (bool , FSupportsDynamicChangesSignature , UWorld *)
Referenced by DECLARE_DELEGATE_RetVal_OneParam(), DECLARE_DELEGATE_RetVal_OneParam(), DECLARE_DELEGATE_RetVal_OneParam(), DECLARE_DELEGATE_RetVal_OneParam(), DECLARE_DELEGATE_RetVal_OneParam(), and DECLARE_DELEGATE_RetVal_OneParam().
DECLARE_DELEGATE_RetVal_OneParam() [4/7]
FNavigationSystem::DECLARE_DELEGATE_RetVal_OneParam (const FNavDataConfig & , FNavDataConfigAndWorldSignature , const UWorld *)
References DECLARE_DELEGATE_RetVal_OneParam().
DECLARE_DELEGATE_RetVal_OneParam() [5/7]
FNavigationSystem::DECLARE_DELEGATE_RetVal_OneParam (double , FDoubleWorldBasedSignature , const UWorld &)
References DECLARE_DELEGATE_RetVal_OneParam().
DECLARE_DELEGATE_RetVal_OneParam() [6/7]
FNavigationSystem::DECLARE_DELEGATE_RetVal_OneParam (INavigationDataInterface * , FNavDataForActorSignature , const AActor &)
References DECLARE_DELEGATE_RetVal_OneParam().
DECLARE_DELEGATE_RetVal_OneParam() [7/7]
FNavigationSystem::DECLARE_DELEGATE_RetVal_OneParam (INavigationDataInterface * , FNavDataForPropsSignature , const FNavAgentProperties &)
References DECLARE_DELEGATE_RetVal_OneParam().
DECLARE_DELEGATE_RetVal_TwoParams()
FNavigationSystem::DECLARE_DELEGATE_RetVal_TwoParams (FNavigationElementHandle , FAddNavigationElementSignature , UWorld * , FNavigationElement &&)
References FNavigationElementHandle.
DECLARE_DELEGATE_ThreeParams() [1/2]
FNavigationSystem::DECLARE_DELEGATE_ThreeParams (FObjectBoundsChangedSignature , UObject & , const FBox & , TConstArrayView< FBox >)
References DECLARE_DELEGATE_OneParam(), and DECLARE_DELEGATE_ThreeParams().
DECLARE_DELEGATE_ThreeParams() [2/2]
FNavigationSystem::DECLARE_DELEGATE_ThreeParams (FUpdateNavigationElementSignature , UWorld * , FNavigationElementHandle , FNavigationElement &&)
References FNavigationElementHandle.
Referenced by DECLARE_DELEGATE_ThreeParams(), and UE_DEPRECATED().
DECLARE_DELEGATE_TwoParams() [1/5]
FNavigationSystem::DECLARE_DELEGATE_TwoParams (FActorBooleBasedSignature , AActor & , bool)
References DECLARE_DELEGATE_TwoParams().
DECLARE_DELEGATE_TwoParams() [2/5]
FNavigationSystem::DECLARE_DELEGATE_TwoParams (FNavigationAutoUpdateEnableSignature , const bool , UNavigationSystemBase *)
References DECLARE_DELEGATE_TwoParams().
DECLARE_DELEGATE_TwoParams() [3/5]
FNavigationSystem::DECLARE_DELEGATE_TwoParams (FRemoveNavigationElementSignature , UWorld * , FNavigationElementHandle)
References FNavigationElementHandle.
Referenced by DECLARE_DELEGATE_TwoParams(), DECLARE_DELEGATE_TwoParams(), DECLARE_DELEGATE_TwoParams(), and DECLARE_DELEGATE_TwoParams().
DECLARE_DELEGATE_TwoParams() [4/5]
FNavigationSystem::DECLARE_DELEGATE_TwoParams (FWorldBoolBasedSignature , UWorld & , const bool)
References DECLARE_DELEGATE_TwoParams().
DECLARE_DELEGATE_TwoParams() [5/5]
FNavigationSystem::DECLARE_DELEGATE_TwoParams (FWorldByteBasedSignature , UWorld & , uint8)
References DECLARE_DELEGATE_TwoParams().
DECLARE_MULTICAST_DELEGATE_OneParam()
FNavigationSystem::DECLARE_MULTICAST_DELEGATE_OneParam (FOnNavigationInitSignature , const UNavigationSystemBase &)
References DECLARE_MULTICAST_DELEGATE_OneParam().
Referenced by DECLARE_MULTICAST_DELEGATE_OneParam().
DECLARE_MULTICAST_DELEGATE_TwoParams()
FNavigationSystem::DECLARE_MULTICAST_DELEGATE_TwoParams (FOnNavAreaGenericEvent , const UWorld & , const UClass *)
References DECLARE_MULTICAST_DELEGATE_TwoParams().
Referenced by DECLARE_MULTICAST_DELEGATE_TwoParams().
DiscardNavigationDataChunks()
void FNavigationSystem::DiscardNavigationDataChunks (UWorld & InWorld)
Discards all navigation data chunks in all sub-levels.
FindPathFollowingAgentForActor()
IPathFollowingAgentInterface * FNavigationSystem::FindPathFollowingAgentForActor (const AActor & Actor)
References Actor.
GetBiggestSupportedAgent()
const FNavDataConfig & FNavigationSystem::GetBiggestSupportedAgent (const UWorld * World)
References GetBiggestSupportedAgent().
Referenced by GetBiggestSupportedAgent().
GetCoordTransform()
const FTransform & FNavigationSystem::GetCoordTransform (const ENavigationCoordSystem::Type FromCoordType, const ENavigationCoordSystem::Type ToCoordType)
Retrieves the transform the Navigation System is using to convert coords from FromCoordType to ToCoordType.
References GetCoordTransform().
Referenced by GetCoordTransform().
GetCurrent() [1/3]
template<typename TNavSys> FORCEINLINE const TNavSys * FNavigationSystem::GetCurrent (const UWorld * World)
Definition at line 121 of file NavigationSystemBase.h.
References Cast(), and FORCEINLINE.
GetCurrent() [2/3]
template<typename TNavSys> TNavSys * FNavigationSystem::GetCurrent (UObject * WorldContextObject)
Definition at line 129 of file NavigationSystemBase.h.
References GetCurrent(), and GetWorldFromContextObject().
GetCurrent() [3/3]
template<typename TNavSys> FORCEINLINE TNavSys * FNavigationSystem::GetCurrent (UWorld * World)
Definition at line 115 of file NavigationSystemBase.h.
References Cast(), and FORCEINLINE.
Referenced by GetCurrent().
GetDefaultNavDataClass()
TSubclassOf< AActor > FNavigationSystem::GetDefaultNavDataClass ()
References GetDefaultNavDataClass().
Referenced by GetDefaultNavDataClass().
GetDefaultObstacleArea()
TSubclassOf< UNavAreaBase > FNavigationSystem::GetDefaultObstacleArea ()
References GetDefaultObstacleArea().
Referenced by GetDefaultObstacleArea().
GetDefaultSupportedAgent()
const FNavDataConfig & FNavigationSystem::GetDefaultSupportedAgent ()
References GetDefaultSupportedAgent().
Referenced by GetDefaultSupportedAgent().
GetDefaultWalkableArea()
TSubclassOf< UNavAreaBase > FNavigationSystem::GetDefaultWalkableArea ()
References GetDefaultWalkableArea().
Referenced by GetDefaultWalkableArea().
GetNavDataForActor()
INavigationDataInterface * FNavigationSystem::GetNavDataForActor (const AActor & Actor)
References Actor, and GetNavDataForActor().
Referenced by GetNavDataForActor().
GetWorldFromContextObject()
UWorld * FNavigationSystem::GetWorldFromContextObject (UObject * WorldContextObject)
Referenced by GetCurrent().
GetWorldPartitionNavigationDataBuilderOverlap()
double FNavigationSystem::GetWorldPartitionNavigationDataBuilderOverlap (const UWorld & World)
References GetWorldPartitionNavigationDataBuilderOverlap().
Referenced by GetWorldPartitionNavigationDataBuilderOverlap().
HasComponentData()
bool FNavigationSystem::HasComponentData (UActorComponent & Comp)
References HasComponentData().
Referenced by HasComponentData().
InvalidBoundingBox()
FBox FNavigationSystem::InvalidBoundingBox (ForceInit , UE::Math::TBoxConstInit{}) inline constexpr
References ForceInit.
IsEditorRunMode()
bool FNavigationSystem::IsEditorRunMode (const FNavigationSystemRunMode Mode)
IsFollowingAPath()
bool FNavigationSystem::IsFollowingAPath (const AController & Controller)
IsInBaseNavmesh()
bool FNavigationSystem::IsInBaseNavmesh (const UObject * Object)
Objects placed directly in the level and objects placed in the base navmesh data layers are in the base navmesh.
References Object.
IsLevelVisibilityChanging()
bool FNavigationSystem::IsLevelVisibilityChanging (const UObject * Object)
Returns true if the visibility of the owning level is currently changing (loading/unloading).
References Object.
IsValidLocation()
FORCEINLINE bool FNavigationSystem::IsValidLocation (const FVector & TestLocation)
Definition at line 49 of file NavigationTypes.h.
References FORCEINLINE, FVector, and InvalidLocation.
OnActorBoundsChanged()
void FNavigationSystem::OnActorBoundsChanged (AActor & Actor)
References Actor.
OnActorRegistered()
void FNavigationSystem::OnActorRegistered (AActor & Actor)
References Actor, and OnActorRegistered().
Referenced by OnActorRegistered().
OnActorUnregistered()
void FNavigationSystem::OnActorUnregistered (AActor & Actor)
References Actor, and OnActorUnregistered().
Referenced by OnActorUnregistered().
OnComponentRegistered()
void FNavigationSystem::OnComponentRegistered (UActorComponent & Comp)
References OnComponentRegistered().
Referenced by OnComponentRegistered().
OnComponentTransformChanged()
void FNavigationSystem::OnComponentTransformChanged (USceneComponent & Comp)
References OnComponentTransformChanged().
Referenced by OnComponentTransformChanged().
OnComponentUnregistered()
void FNavigationSystem::OnComponentUnregistered (UActorComponent & Comp)
References OnComponentUnregistered().
Referenced by OnComponentUnregistered().
OnNavigationElementBoundsChanged()
void FNavigationSystem::OnNavigationElementBoundsChanged (UWorld * World, FNavigationElementHandle ElementHandle, const FBox & NewBounds, TConstArrayView< FBox > DirtyAreas)
References FNavigationElementHandle, NewBounds, and OnNavigationElementBoundsChanged().
Referenced by OnNavigationElementBoundsChanged().
OnObjectBoundsChanged()
void FNavigationSystem::OnObjectBoundsChanged (UObject & Object, const FBox & NewBounds, TConstArrayView< FBox > DirtyAreas)
References NewBounds, Object, and OnObjectBoundsChanged().
Referenced by OnObjectBoundsChanged().
OnPIEEnd()
void FNavigationSystem::OnPIEEnd (UWorld & World)
OnPIEStart()
void FNavigationSystem::OnPIEStart (UWorld & World)
OnPostEditActorMove()
void FNavigationSystem::OnPostEditActorMove (AActor & Actor)
References Actor.
RegisterComponent()
void FNavigationSystem::RegisterComponent (UActorComponent & Comp)
References RegisterComponent().
Referenced by RegisterComponent().
RegisterNavRelevantObject()
void FNavigationSystem::RegisterNavRelevantObject (UObject & Object)
References Object, and RegisterNavRelevantObject().
Referenced by RegisterNavRelevantObject().
RemoveActorData()
void FNavigationSystem::RemoveActorData (AActor & Actor)
References Actor, and RemoveActorData().
Referenced by RemoveActorData().
RemoveNavigationElement()
void FNavigationSystem::RemoveNavigationElement (UWorld * World, FNavigationElementHandle ElementHandle)
References FNavigationElementHandle, and RemoveNavigationElement().
Referenced by RemoveNavigationElement().
SetNavigationAutoUpdateEnabled()
void FNavigationSystem::SetNavigationAutoUpdateEnabled (const bool bNewEnable, UNavigationSystemBase * InNavigationSystem)
StopMovement()
void FNavigationSystem::StopMovement (const AController & Controller)
SupportsDynamicChanges()
bool FNavigationSystem::SupportsDynamicChanges (UWorld * World)
References SupportsDynamicChanges().
Referenced by SupportsDynamicChanges().
UE_DEPRECATED() [1/2]
FNavigationSystem::UE_DEPRECATED (5. 4, "Use FObjectBoundsChangedSignature delegate taking UObject and list of dirty areas as parameters instead.")
References config, DECLARE_DELEGATE_ThreeParams(), defaultconfig, Engine, ForceInit, FVector, GENERATED_BODY, MinimalAPI, PRAGMA_DISABLE_DEPRECATION_WARNINGS, PRAGMA_ENABLE_DEPRECATION_WARNINGS, PURE_VIRTUAL, Transform, Transient, UCLASS, and UE_DEPRECATED().
UE_DEPRECATED() [2/2]
FNavigationSystem::UE_DEPRECATED (5. 4, "Use OnObjectBoundsChanged taking UObject and list of dirty areas as parameters instead.") &
Referenced by UE_DEPRECATED().
UnregisterComponent()
void FNavigationSystem::UnregisterComponent (UActorComponent & Comp)
References UnregisterComponent().
Referenced by UnregisterComponent().
UnregisterNavRelevantObject()
void FNavigationSystem::UnregisterNavRelevantObject (UObject & Object)
References Object, and UnregisterNavRelevantObject().
Referenced by UnregisterNavRelevantObject().
UpdateActorAndComponentData()
void FNavigationSystem::UpdateActorAndComponentData (AActor & Actor, bool bUpdateAttachedActors = true)
References Actor.
UpdateActorData()
void FNavigationSystem::UpdateActorData (AActor & Actor)
References Actor.
UpdateComponentData()
void FNavigationSystem::UpdateComponentData (UActorComponent & Comp)
Referenced by FAlphamapAccessor< bInUseInterp, bInUseTotalNormalize >::~FAlphamapAccessor(), and FHeightmapAccessor< bInUseInterp >::~FHeightmapAccessor().
UpdateComponentDataAfterMove()
void FNavigationSystem::UpdateComponentDataAfterMove (USceneComponent & Comp)
UpdateLevelCollision()
void FNavigationSystem::UpdateLevelCollision (ULevel & Level)
UpdateNavigationElement()
void FNavigationSystem::UpdateNavigationElement (UWorld * World, FNavigationElementHandle ElementHandle, FNavigationElement && Element)
References FNavigationElementHandle, and UpdateNavigationElement().
Referenced by UpdateNavigationElement().
UpdateNavRelevantObject()
void FNavigationSystem::UpdateNavRelevantObject (UObject & Object)
References Object, and UpdateNavRelevantObject().
Referenced by UpdateNavRelevantObject().
VerifyNavigationRenderingComponents()
void FNavigationSystem::VerifyNavigationRenderingComponents (UWorld & World, const bool bShow)
References VerifyNavigationRenderingComponents().
Referenced by VerifyNavigationRenderingComponents().
WantsComponentChangeNotifies()
bool FNavigationSystem::WantsComponentChangeNotifies ()
References WantsComponentChangeNotifies().
Referenced by WantsComponentChangeNotifies().
Variable Documentation
DirtyArea
const FBox const FBox& FNavigationSystem::DirtyArea
Definition at line 144 of file NavigationSystemBase.h.
FallbackAgentHeight
const float FNavigationSystem::FallbackAgentHeight extern
used as a fallback value for navigation agent height, when none specified via UNavigationSystemV1::SupportedAgents
FallbackAgentRadius
const float FNavigationSystem::FallbackAgentRadius extern
used as a fallback value for navigation agent radius, when none specified via UNavigationSystemV1::SupportedAgents
FNavigationElementHandle
UWorld FNavigationSystem::FNavigationElementHandle
Definition at line 212 of file NavigationSystemBase.h.
Referenced by AddNavigationElement(), DECLARE_DELEGATE_RetVal_TwoParams(), DECLARE_DELEGATE_ThreeParams(), DECLARE_DELEGATE_TwoParams(), OnNavigationElementBoundsChanged(), RemoveNavigationElement(), and UpdateNavigationElement().
InvalidLocation
FVector FNavigationSystem::InvalidLocation = FVector(TNumericLimits<FVector::FReal>::Max(), UE::Math::TVectorConstInit{}) inline constexpr
Definition at line 47 of file NavigationTypes.h.
Referenced by FRayStartEnd::FRayStartEnd(), and IsValidLocation().
NewBounds
const FBox& FNavigationSystem::NewBounds
Definition at line 144 of file NavigationSystemBase.h.
Referenced by OnNavigationElementBoundsChanged(), and OnObjectBoundsChanged().