Unreal Engine 5.6 C++ API: Metasound::ReceiveNodeInfo Namespace Reference
Metasound::ReceiveNodeInfo Namespace Reference
Functions
METASOUNDFRONTEND_API int32 GetCurrentMajorVersion ()
METASOUNDFRONTEND_API int32 GetCurrentMinorVersion ()
METASOUND_PARAM (AddressInput, "Address", "Address") METASOUND_PARAM(DefaultDataInput
Default METASOUND_PARAM (Output, "Out", "Out") METASOUNDFRONTEND_API FNodeClassName GetClassNameForDataType(const FName &InDataTypeName)
Variables
Default
Function Documentation
GetCurrentMajorVersion()
METASOUNDFRONTEND_API int32 Metasound::ReceiveNodeInfo::GetCurrentMajorVersion ()
References GetCurrentMajorVersion().
Referenced by GetCurrentMajorVersion(), and Metasound::ReceiveNodePrivate::TReceiverOperator< TDataType >::GetNodeInfo().
GetCurrentMinorVersion()
METASOUNDFRONTEND_API int32 Metasound::ReceiveNodeInfo::GetCurrentMinorVersion ()
References GetCurrentMinorVersion().
Referenced by GetCurrentMinorVersion(), and Metasound::ReceiveNodePrivate::TReceiverOperator< TDataType >::GetNodeInfo().
METASOUND_PARAM() [1/2]
Metasound::ReceiveNodeInfo::METASOUND_PARAM (AddressInput , "Address" , "Address")
Referenced by METASOUND_PARAM().
METASOUND_PARAM() [2/2]
Default Metasound::ReceiveNodeInfo::METASOUND_PARAM (Output , "Out" , "Out") const &
References METASOUND_PARAM().
Variable Documentation
Default
Metasound::ReceiveNodeInfo::Default
Definition at line 26 of file MetasoundReceiveNode.h.