Unreal Engine 5.6 C++ API: DiffUtils Namespace Reference
DiffUtils Namespace Reference
Functions
UNREALED_API void CompareUnrelatedObjects (const UObject *A, const UObject *B, TArray< FSingleObjectDiffEntry > &OutDifferingProperties)
UNREALED_API void CompareUnrelatedSCS (const UBlueprint *Old, const TArray< FSCSResolvedIdentifier > &OldHierarchy, const UBlueprint *New, const TArray< FSCSResolvedIdentifier > &NewHierarchy, FSCSDiffRoot &OutDifferingEntries)
UNREALED_API void CompareUnrelatedStructs (const UStruct *StructA, const void *A, const UObject *OwningOuterA, const UStruct *StructB, const void *B, const UObject *OwningOuterB, TArray< FSingleObjectDiffEntry > &OutDifferingProperties)
const FSingleObjectDiffEntry FText & DECLARE_DELEGATE_FourParams (FOnOrganizeDiffEntries, TArray< TSharedPtr< FBlueprintDifferenceTreeEntry > > &, const TArray< FSingleObjectDiffEntry > &, TFunctionRef< TSharedPtr< FBlueprintDifferenceTreeEntry >(const FSingleObjectDiffEntry &)>, TFunctionRef< TSharedPtr< FBlueprintDifferenceTreeEntry >(FText &)>) struct FDiffParameters
DECLARE_DELEGATE_OneParam (FOnGenerateCustomDiffEntries, TArray< FSingleObjectDiffEntry > &) DECLARE_DELEGATE_RetVal_TwoParams(TSharedRef< SWidget >
UNREALED_API const UObject * GetCDO (const UBlueprint *ForBlueprint)
UNREALED_API TArray< FPropertySoftPath > GetVisiblePropertiesInOrderDeclared (const UStruct *ForStruct, const FPropertySoftPath &Scope=FPropertySoftPath())
UNREALED_API bool Identical (const FResolvedProperty &AProp, const FResolvedProperty &BProp, const UObject *OwningOuterA, const UObject *OwningOuterB)
DiffUtils now requires root objects so that object topology can be meaningfully compared.
UNREALED_API bool Identical (const FResolvedProperty &AProp, const FResolvedProperty &BProp, const UObject *OwningOuterA, const UObject *OwningOuterB, FDiffParameters DiffParameters, TArray< FPropertySoftPath > &DifferingProperties)
UNREALED_API bool Identical (const TSharedPtr< IPropertyHandle > &PropertyHandleA, const TSharedPtr< IPropertyHandle > &PropertyHandleB, const TArray< TWeakObjectPtr< UObject > > &OwningOutersA={}, const TArray< TWeakObjectPtr< UObject > > &OwningOutersB={})
UNREALED_API bool Identical (TArray< FPropertySoftPath > &OutDifferingProperties, const TSharedPtr< IPropertyHandle > &PropertyHandleA, const TSharedPtr< IPropertyHandle > &PropertyHandleB, const TArray< TWeakObjectPtr< UObject > > &OwningOutersA={}, const TArray< TWeakObjectPtr< UObject > > &OwningOutersB={})
UNREALED_API UPackage * LoadPackageForDiff (const FPackagePath &InTempPackagePath, const FPackagePath &InOriginalPackagePath)
UNREALED_API UPackage * LoadPackageForDiff (TSharedPtr< ISourceControlRevision > Revision)
UNREALED_API TArray< FPropertyPath > ResolveAll (const UObject *Object, const TArray< FPropertySoftPath > &InSoftProperties)
UNREALED_API TArray< FPropertyPath > ResolveAll (const UObject *Object, const TArray< FSingleObjectDiffEntry > &InDifferences)
UE_DEPRECATED (5.3, "DiffUtils now requires root objects so that object topology can be meaningfully compared.") UNREALED_API bool Identical(const FResolvedProperty &AProp
UE_DEPRECATED (5.3, "DiffUtils now requires root objects so that object topology can be meaningfully compared.") UNREALED_API void CompareUnrelatedStructs(const UStruct *StructA
UE_DEPRECATED (5.5, "Use version with FDiffParameters instead.") UNREALED_API bool Identical(const FResolvedProperty &AProp
Variables
const void * A
const void const UStruct const void * B
const FResolvedProperty & BProp
const FResolvedProperty const FPropertySoftPath TArray< FPropertySoftPath > & DifferingProperties
FOnGenerateCustomDiffEntryWidget
const void const UStruct const void TArray< FSingleObjectDiffEntry > & OutDifferingProperties
const FResolvedProperty const UObject * OwningOuterA
const FResolvedProperty const UObject const UObject * OwningOuterB
const FResolvedProperty const FPropertySoftPath & RootPath
const void const UStruct * StructB
Function Documentation
CompareUnrelatedObjects()
UNREALED_API void DiffUtils::CompareUnrelatedObjects (const UObject * A, const UObject * B, TArray< FSingleObjectDiffEntry > & OutDifferingProperties)
References A, B, CompareUnrelatedObjects(), and OutDifferingProperties.
Referenced by CompareUnrelatedObjects().
CompareUnrelatedSCS()
UNREALED_API void DiffUtils::CompareUnrelatedSCS (const UBlueprint * Old, const TArray< FSCSResolvedIdentifier > & OldHierarchy, const UBlueprint * New, const TArray< FSCSResolvedIdentifier > & NewHierarchy, FSCSDiffRoot & OutDifferingEntries)
References CompareUnrelatedSCS(), and New().
Referenced by CompareUnrelatedSCS().
CompareUnrelatedStructs()
UNREALED_API void DiffUtils::CompareUnrelatedStructs (const UStruct * StructA, const void * A, const UObject * OwningOuterA, const UStruct * StructB, const void * B, const UObject * OwningOuterB, TArray< FSingleObjectDiffEntry > & OutDifferingProperties)
References A, B, CompareUnrelatedStructs(), OutDifferingProperties, OwningOuterA, OwningOuterB, and StructB.
Referenced by CompareUnrelatedStructs().
DECLARE_DELEGATE_FourParams()
const FSingleObjectDiffEntry FText & DiffUtils::DECLARE_DELEGATE_FourParams (FOnOrganizeDiffEntries , TArray< TSharedPtr< FBlueprintDifferenceTreeEntry > > & , const TArray< FSingleObjectDiffEntry > & , TFunctionRef< TSharedPtr< FBlueprintDifferenceTreeEntry >(const FSingleObjectDiffEntry &)> , TFunctionRef< TSharedPtr< FBlueprintDifferenceTreeEntry >(FText &)>)
Predicate evaluated on visited properties to determine if they should be part of the comparison.
Indicates if the elements of a static array should be compared. Otherwise, only the size is compared.
Definition at line 313 of file DiffUtils.h.
References bool, DECLARE_DELEGATE_FourParams(), and RootPath.
Referenced by DECLARE_DELEGATE_FourParams().
DECLARE_DELEGATE_OneParam()
DiffUtils::DECLARE_DELEGATE_OneParam (FOnGenerateCustomDiffEntries , TArray< FSingleObjectDiffEntry > &)
GetCDO()
UNREALED_API const UObject * DiffUtils::GetCDO (const UBlueprint * ForBlueprint)
GetVisiblePropertiesInOrderDeclared()
UNREALED_API TArray< FPropertySoftPath > DiffUtils::GetVisiblePropertiesInOrderDeclared (const UStruct * ForStruct, const FPropertySoftPath & Scope = FPropertySoftPath())
Identical() [1/4]
UNREALED_API bool DiffUtils::Identical (const FResolvedProperty & AProp, const FResolvedProperty & BProp, const UObject * OwningOuterA, const UObject * OwningOuterB)
DiffUtils now requires root objects so that object topology can be meaningfully compared.
DiffUtils::Identical works similar to FProperty::Identical except when a UObject is found, that is in OwningOuter*, it's compared by topology instead. This allows sub-objects to diff correctly.
References BProp, Identical(), OwningOuterA, and OwningOuterB.
Referenced by Identical(), Identical(), and Identical().
Identical() [2/4]
UNREALED_API bool DiffUtils::Identical (const FResolvedProperty & AProp, const FResolvedProperty & BProp, const UObject * OwningOuterA, const UObject * OwningOuterB, FDiffParameters DiffParameters, TArray< FPropertySoftPath > & DifferingProperties)
References BProp, DifferingProperties, Identical(), OwningOuterA, and OwningOuterB.
Identical() [3/4]
UNREALED_API bool DiffUtils::Identical (const TSharedPtr< IPropertyHandle > & PropertyHandleA, const TSharedPtr< IPropertyHandle > & PropertyHandleB, const TArray< TWeakObjectPtr< UObject > > & OwningOutersA = {}, const TArray< TWeakObjectPtr< UObject > > & OwningOutersB = {})
References Identical().
Identical() [4/4]
UNREALED_API bool DiffUtils::Identical (TArray< FPropertySoftPath > & OutDifferingProperties, const TSharedPtr< IPropertyHandle > & PropertyHandleA, const TSharedPtr< IPropertyHandle > & PropertyHandleB, const TArray< TWeakObjectPtr< UObject > > & OwningOutersA = {}, const TArray< TWeakObjectPtr< UObject > > & OwningOutersB = {})
References OutDifferingProperties.
LoadPackageForDiff() [1/2]
UNREALED_API UPackage * DiffUtils::LoadPackageForDiff (const FPackagePath & InTempPackagePath, const FPackagePath & InOriginalPackagePath)
Parameters
InTempPackagePath - filepath of the temporary uasset version (likely in /Saved/Temp/SourceControl)
InOriginalPackagePath - filepath of the original uasset in the content directory. Strictly speaking most assets don't need this parameter set but it's needed to instantiate OFPA Actors properly.
LoadPackageForDiff() [2/2]
UNREALED_API UPackage * DiffUtils::LoadPackageForDiff (TSharedPtr< ISourceControlRevision > Revision)
ResolveAll() [1/2]
UNREALED_API TArray< FPropertyPath > DiffUtils::ResolveAll (const UObject * Object, const TArray< FPropertySoftPath > & InSoftProperties)
References Object.
ResolveAll() [2/2]
UNREALED_API TArray< FPropertyPath > DiffUtils::ResolveAll (const UObject * Object, const TArray< FSingleObjectDiffEntry > & InDifferences)
References Object.
UE_DEPRECATED() [1/3]
DiffUtils::UE_DEPRECATED (5. 3, "DiffUtils now requires root objects so that object topology can be meaningfully compared.") const &
References UE_DEPRECATED().
UE_DEPRECATED() [2/3]
DiffUtils::UE_DEPRECATED (5. 3, "DiffUtils now requires root objects so that object topology can be meaningfully compared.") const
Referenced by UE_DEPRECATED(), and UE_DEPRECATED().
UE_DEPRECATED() [3/3]
DiffUtils::UE_DEPRECATED (5. 5, "Use version with FDiffParameters instead.") const &
References UE_DEPRECATED().
Variable Documentation
A
const void* DiffUtils::A
Definition at line 338 of file DiffUtils.h.
Referenced by CompareUnrelatedObjects(), and CompareUnrelatedStructs().
B
const void const UStruct const void* DiffUtils::B
Definition at line 338 of file DiffUtils.h.
Referenced by CompareUnrelatedObjects(), and CompareUnrelatedStructs().
BProp
const FResolvedProperty & DiffUtils::BProp
Definition at line 345 of file DiffUtils.h.
Referenced by Identical(), and Identical().
DifferingProperties
const FResolvedProperty const UObject const UObject const FPropertySoftPath TArray< FPropertySoftPath > & DiffUtils::DifferingProperties
Definition at line 345 of file DiffUtils.h.
Referenced by Identical().
FOnGenerateCustomDiffEntryWidget
DiffUtils::FOnGenerateCustomDiffEntryWidget
Definition at line 312 of file DiffUtils.h.
OutDifferingProperties
const void const UStruct const void TArray<FSingleObjectDiffEntry>& DiffUtils::OutDifferingProperties
Definition at line 338 of file DiffUtils.h.
Referenced by CompareUnrelatedObjects(), CompareUnrelatedStructs(), and Identical().
OwningOuterA
const FResolvedProperty const UObject* DiffUtils::OwningOuterA
Definition at line 348 of file DiffUtils.h.
Referenced by CompareUnrelatedStructs(), Identical(), and Identical().
OwningOuterB
const FResolvedProperty const UObject const UObject* DiffUtils::OwningOuterB
Definition at line 348 of file DiffUtils.h.
Referenced by CompareUnrelatedStructs(), Identical(), and Identical().
RootPath
const FResolvedProperty const UObject const UObject const FPropertySoftPath & DiffUtils::RootPath
Definition at line 345 of file DiffUtils.h.
Referenced by DECLARE_DELEGATE_FourParams().
StructB
const void const UStruct* DiffUtils::StructB
Definition at line 338 of file DiffUtils.h.
Referenced by CompareUnrelatedStructs().