Unreal Engine 5.6 C++ API: UE::ToolTarget Namespace Reference
UE::ToolTarget Namespace Reference
Namespaces
namespace Internal
Enumerations
enum class EDynamicMeshUpdateResult { Ok = 0 , Failed = 1 , Ok_ForcedFullUpdate = 2 }
EDynamicMeshUpdateResult is returned by functions below that update a ToolTarget with a new Mesh.
Functions
MODELINGCOMPONENTS_API bool ApplyIncrementalMeshEditChange (UToolTarget *Target, TFunctionRef< bool(UE::Geometry::FDynamicMesh3 &EditMesh, UObject *TransactionTarget)> MeshEditingFunc)
Apply an incremental mesh edit (MeshEditingFunc) to the ToolTarget.
MODELINGCOMPONENTS_API EDynamicMeshUpdateResult CommitDynamicMeshNormalsUpdate (UToolTarget *Target, const UE::Geometry::FDynamicMesh3 *UpdatedMesh, bool bUpdateTangents=false)
Update the Normals/Tangents of the ToolTarget's mesh (assuming it has one) based on the provided UpdatedMesh.
MODELINGCOMPONENTS_API EDynamicMeshUpdateResult CommitDynamicMeshUpdate (UToolTarget *Target, const UE::Geometry::FDynamicMesh3 &UpdatedMesh, bool bHaveModifiedTopology, const FConversionToMeshDescriptionOptions &ConversionOptions=FConversionToMeshDescriptionOptions(), const FComponentMaterialSet *UpdatedMaterials=nullptr)
Update the Mesh in a ToolTarget based on the provided DynamicMesh, and optional material set.
MODELINGCOMPONENTS_API EDynamicMeshUpdateResult CommitDynamicMeshUVUpdate (UToolTarget *Target, const UE::Geometry::FDynamicMesh3 *UpdatedMesh)
Update the UV sets of the ToolTarget's mesh (assuming it has one) based on the provided UpdatedMesh.
MODELINGCOMPONENTS_API bool CommitMaterialSetUpdate (UToolTarget *Target, const FComponentMaterialSet &UpdatedMaterials, bool bApplyToAsset=true)
Update the material set of the Target.
MODELINGCOMPONENTS_API EDynamicMeshUpdateResult CommitMeshDescriptionUpdate (UToolTarget *Target, const FMeshDescription *UpdatedMesh, const FComponentMaterialSet *UpdatedMaterials=nullptr, const FCommitMeshParameters &CommitParams=FCommitMeshParameters())
Update the Mesh in a ToolTarget based on the provided MeshDescription, and optional material set.
MODELINGCOMPONENTS_API EDynamicMeshUpdateResult CommitMeshDescriptionUpdate (UToolTarget *Target, FMeshDescription &&UpdatedMesh, const FCommitMeshParameters &CommitParams=FCommitMeshParameters())
Update the Mesh in a ToolTarget based on the provided MeshDescription, and optional material set.
MODELINGCOMPONENTS_API EDynamicMeshUpdateResult CommitMeshDescriptionUpdateViaDynamicMesh (UToolTarget *Target, const UE::Geometry::FDynamicMesh3 &UpdatedMesh, bool bHaveModifiedTopology, const FCommitMeshParameters &CommitParams=FCommitMeshParameters())
Update the Mesh in a ToolTarget based on the provided MeshDescription, and optional material set.
MODELINGCOMPONENTS_API bool ConfigureCreateMeshObjectParams (UToolTarget *SourceTarget, FCreateMeshObjectParams &DerivedParamsOut)
FCreateMeshObjectParams::TypeHint is used by the ModelingObjectsCreationAPI to suggest what type of mesh object to create inside various Tools.
UE_DEPRECATED(5.5, "Use GetDynamicMeshCopy which takes a FGetMeshParameters instead.") MODELINGCOMPONENTS_API UE MODELINGCOMPONENTS_API UE::Geometry::FDynamicMesh3 GetDynamicMeshCopy (UToolTarget *Target, const FGetMeshParameters &InGetMeshParams=FGetMeshParameters())
Fetch a DynamicMesh3 representing the given ToolTarget.
MODELINGCOMPONENTS_API FMeshDescription GetEmptyMeshDescription (UToolTarget *Target)
MODELINGCOMPONENTS_API FString GetHumanReadableName (UToolTarget *Target)
MODELINGCOMPONENTS_API FTransform3d GetLocalToWorldTransform (UToolTarget *Target)
MODELINGCOMPONENTS_API FComponentMaterialSet GetMaterialSet (UToolTarget *Target, bool bPreferAssetMaterials=false)
Fetch the Material Set on the object underlying a ToolTarget.
MODELINGCOMPONENTS_API const FMeshDescription * GetMeshDescription (UToolTarget *Target, const FGetMeshParameters &GetMeshParams=FGetMeshParameters())
MODELINGCOMPONENTS_API FMeshDescription GetMeshDescriptionCopy (UToolTarget *Target, const FGetMeshParameters &GetMeshParams=FGetMeshParameters())
Return a copy of the MeshDescription underlying a ToolTarget.
MODELINGCOMPONENTS_API TArray< EMeshLODIdentifier > GetMeshDescriptionLODs (UToolTarget *Target, bool &bOutTargetSupportsLODs, bool bOnlyReturnDefaultLOD=false, bool bExcludeAutoGeneratedLODs=true)
MODELINGCOMPONENTS_API UBodySetup * GetPhysicsBodySetup (UToolTarget *Target)
MODELINGCOMPONENTS_API IInterface_CollisionDataProvider * GetPhysicsCollisionDataProvider (UToolTarget *Target)
MODELINGCOMPONENTS_API USkeletalMesh * GetSkeletalMeshFromTargetIfAvailable (UToolTarget *Target)
MODELINGCOMPONENTS_API UStaticMesh * GetStaticMeshFromTargetIfAvailable (UToolTarget *Target)
MODELINGCOMPONENTS_API AActor * GetTargetActor (UToolTarget *Target)
MODELINGCOMPONENTS_API UPrimitiveComponent * GetTargetComponent (UToolTarget *Target)
MODELINGCOMPONENTS_API EMeshLODIdentifier GetTargetMeshDescriptionLOD (UToolTarget *Target, bool &bOutTargetSupportsLODs)
Return identifier for the mesh LOD that a ToolTarget represents, if defined for the given ToolTarget.
MODELINGCOMPONENTS_API USceneComponent * GetTargetSceneComponent (UToolTarget *Target)
MODELINGCOMPONENTS_API int32 GetTriangleCount (UToolTarget *Target)
MODELINGCOMPONENTS_API bool HideSourceObject (UToolTarget *Target)
Hide the "Source Object" (eg PrimitiveComponent, Actor, etc) backing a ToolTarget.
MODELINGCOMPONENTS_API bool SetSourceObjectVisible (UToolTarget *Target, bool bVisible)
Show or Hide the "Source Object" (eg PrimitiveComponent, Actor, etc) backing a ToolTarget.
MODELINGCOMPONENTS_API bool ShowSourceObject (UToolTarget *Target)
Show the "Source Object" (eg PrimitiveComponent, Actor, etc) backing a ToolTarget.
MODELINGCOMPONENTS_API bool SupportsIncrementalMeshChanges (UToolTarget *Target)
Enumeration Type Documentation
EDynamicMeshUpdateResult
enum class UE::ToolTarget::EDynamicMeshUpdateResult strong
EDynamicMeshUpdateResult is returned by functions below that update a ToolTarget with a new Mesh.
Enumerator
Ok
Update was successful.
Failed
Update failed.
Ok_ForcedFullUpdate
Update was successful, but required that the entire target mesh be replaced, instead of a (requested) partial update.
Definition at line 170 of file ModelingToolTargetUtil.h.
Function Documentation
ApplyIncrementalMeshEditChange()
MODELINGCOMPONENTS_API bool UE::ToolTarget::ApplyIncrementalMeshEditChange (UToolTarget * Target, TFunctionRef< bool(UE::Geometry::FDynamicMesh3 &EditMesh, UObject *TransactionTarget)> MeshEditingFunc)
Apply an incremental mesh edit (MeshEditingFunc) to the ToolTarget.
Tools/etc can use this to directly modify the ToolTarget's internal DynamicMesh, while (presumably) also emitting a FChange transaction that represents that Edit. This allows for undoable edits directly to a DynamicMeshComponent/etc in the level.
Returns
true if the incremental edit succeeds
References Target.
CommitDynamicMeshNormalsUpdate()
MODELINGCOMPONENTS_API EDynamicMeshUpdateResult UE::ToolTarget::CommitDynamicMeshNormalsUpdate (UToolTarget * Target, const UE::Geometry::FDynamicMesh3 * UpdatedMesh, bool bUpdateTangents = false)
Update the Normals/Tangents of the ToolTarget's mesh (assuming it has one) based on the provided UpdatedMesh.
Returns
EDynamicMeshUpdateResult::Ok on success, or Ok_ForcedFullUpdate if any dependent mesh topology was modified
References Target.
CommitDynamicMeshUpdate()
MODELINGCOMPONENTS_API EDynamicMeshUpdateResult UE::ToolTarget::CommitDynamicMeshUpdate (UToolTarget * Target, const UE::Geometry::FDynamicMesh3 & UpdatedMesh, bool bHaveModifiedTopology, const FConversionToMeshDescriptionOptions & ConversionOptions = FConversionToMeshDescriptionOptions(), const FComponentMaterialSet * UpdatedMaterials = nullptr)
Update the Mesh in a ToolTarget based on the provided DynamicMesh, and optional material set.
Parameters
bHaveModifiedTopology If the update only changes vertex or attribute values (but not counts), then in some cases a more efficient and/or less destructive update can be applied to the Target
ConversionOptions if the commit to the Target involves conversion to MeshDescription, these options can configure that conversion
UpdatedMaterials optional new material set that will be applied to the updated Target, and the Target Asset if available. If more control is needed use CommitMaterialSetUpdate()
Returns
EDynamicMeshUpdateResult::Ok on success
References Target.
CommitDynamicMeshUVUpdate()
MODELINGCOMPONENTS_API EDynamicMeshUpdateResult UE::ToolTarget::CommitDynamicMeshUVUpdate (UToolTarget * Target, const UE::Geometry::FDynamicMesh3 * UpdatedMesh)
Update the UV sets of the ToolTarget's mesh (assuming it has one) based on the provided UpdatedMesh.
Todo
: support updating a specific UV set/index, rather than all sets
Returns
EDynamicMeshUpdateResult::Ok on success, or Ok_ForcedFullUpdate if any dependent mesh topology was modified
References Target.
CommitMaterialSetUpdate()
MODELINGCOMPONENTS_API bool UE::ToolTarget::CommitMaterialSetUpdate (UToolTarget * Target, const FComponentMaterialSet & UpdatedMaterials, bool bApplyToAsset = true)
Update the material set of the Target.
Parameters
bApplyToAsset In situations where the Target has both Component-level and Asset-level materials, this specifies which should be updated (this flag is passed to the IMaterialProvider, which may or may not respect it)
References Target.
CommitMeshDescriptionUpdate() [1/2]
MODELINGCOMPONENTS_API EDynamicMeshUpdateResult UE::ToolTarget::CommitMeshDescriptionUpdate (UToolTarget * Target, const FMeshDescription * UpdatedMesh, const FComponentMaterialSet * UpdatedMaterials = nullptr, const FCommitMeshParameters & CommitParams = FCommitMeshParameters())
Update the Mesh in a ToolTarget based on the provided MeshDescription, and optional material set.
Returns
EDynamicMeshUpdateResult::Ok on success
References Target.
CommitMeshDescriptionUpdate() [2/2]
MODELINGCOMPONENTS_API EDynamicMeshUpdateResult UE::ToolTarget::CommitMeshDescriptionUpdate (UToolTarget * Target, FMeshDescription && UpdatedMesh, const FCommitMeshParameters & CommitParams = FCommitMeshParameters())
Update the Mesh in a ToolTarget based on the provided MeshDescription, and optional material set.
Returns
EDynamicMeshUpdateResult::Ok on success
References Target.
CommitMeshDescriptionUpdateViaDynamicMesh()
MODELINGCOMPONENTS_API EDynamicMeshUpdateResult UE::ToolTarget::CommitMeshDescriptionUpdateViaDynamicMesh (UToolTarget * Target, const UE::Geometry::FDynamicMesh3 & UpdatedMesh, bool bHaveModifiedTopology, const FCommitMeshParameters & CommitParams = FCommitMeshParameters())
Update the Mesh in a ToolTarget based on the provided MeshDescription, and optional material set.
Returns
EDynamicMeshUpdateResult::Ok on success
References Target.
ConfigureCreateMeshObjectParams()
MODELINGCOMPONENTS_API bool UE::ToolTarget::ConfigureCreateMeshObjectParams (UToolTarget * SourceTarget, FCreateMeshObjectParams & DerivedParamsOut)
FCreateMeshObjectParams::TypeHint is used by the ModelingObjectsCreationAPI to suggest what type of mesh object to create inside various Tools.
This should often be derived from the input mesh object type (eg if you plane-cut a Volume, the output should be Volumes). This function interrogates the ToolTarget to try to determine this information
Returns
true if a known type was detected and configured in FCreateMeshObjectParams::TypeHint (and possibly FCreateMeshObjectParams::TypeHintClass)
GetDynamicMeshCopy()
UE_DEPRECATED(5.5, "Use GetDynamicMeshCopy which takes a FGetMeshParameters instead.") MODELINGCOMPONENTS_API UE MODELINGCOMPONENTS_API UE::Geometry::FDynamicMesh3 UE::ToolTarget::GetDynamicMeshCopy (UToolTarget * Target, const FGetMeshParameters & InGetMeshParams = FGetMeshParameters())
Fetch a DynamicMesh3 representing the given ToolTarget.
This may be a conversion of the output of GetMeshDescription(). This function returns a copy, so the caller can take ownership of this Mesh.
Parameters
bWantMeshTangents if true, tangents will be returned if the target has them available. This may require that they be auto-calculated in some cases (which may be expensive)
Returns
a created DynamicMesh3, which may be empty if the Target doesn't have a mesh Fetch a DynamicMesh3 representing the given ToolTarget. This may be a conversion of the output of GetMeshDescription(). This function returns a copy, so the caller can take ownership of this Mesh.
Parameters
InGetMeshParams to specify various options like specific LOD and/or tangents on the returned mesh. if InGetMeshParams.bWantMeshTangents is true, tangents will be returned if the target has them available. This may require that they be auto-calculated in some cases (which may be expensive)
Returns
a created DynamicMesh3, which may be empty if the Target doesn't have a mesh
References GetDynamicMeshCopy(), and Target.
Referenced by GetDynamicMeshCopy(), and GetMeshDescriptionCopy().
GetEmptyMeshDescription()
MODELINGCOMPONENTS_API FMeshDescription UE::ToolTarget::GetEmptyMeshDescription (UToolTarget * Target)
Returns
an empty MeshDescription with attributes already registered appropriate to the target.
References Target.
GetHumanReadableName()
MODELINGCOMPONENTS_API FString UE::ToolTarget::GetHumanReadableName (UToolTarget * Target)
Returns
a human readable identifier for a ToolTarget, based on the underlying nature of it.
References Target.
GetLocalToWorldTransform()
MODELINGCOMPONENTS_API FTransform3d UE::ToolTarget::GetLocalToWorldTransform (UToolTarget * Target)
Returns
the local-to-world Transform underlying a ToolTarget, eg the Component or Actor transform
References Target.
GetMaterialSet()
MODELINGCOMPONENTS_API FComponentMaterialSet UE::ToolTarget::GetMaterialSet (UToolTarget * Target, bool bPreferAssetMaterials = false)
Fetch the Material Set on the object underlying a ToolTarget.
In cases where there are (eg) separate Component and Asset material sets, prefers the Component material set
Parameters
bPreferAssetMaterials if true, prefer an Asset material set, if available
Returns
a valid MaterialSet
References Target.
GetMeshDescription()
MODELINGCOMPONENTS_API const FMeshDescription * UE::ToolTarget::GetMeshDescription (UToolTarget * Target, const FGetMeshParameters & GetMeshParams = FGetMeshParameters())
Returns
the MeshDescription underlying a ToolTarget, if it has such a mesh. May be generated internally by the ToolTarget. May be nullptr if the Target does not have a mesh.
References Target.
GetMeshDescriptionCopy()
MODELINGCOMPONENTS_API FMeshDescription UE::ToolTarget::GetMeshDescriptionCopy (UToolTarget * Target, const FGetMeshParameters & GetMeshParams = FGetMeshParameters())
Return a copy of the MeshDescription underlying a ToolTarget.
Returns
a new MeshDescription, which may be empty if the Target doesn't have a mesh
References GetDynamicMeshCopy(), and Target.
GetMeshDescriptionLODs()
MODELINGCOMPONENTS_API TArray< EMeshLODIdentifier > UE::ToolTarget::GetMeshDescriptionLODs (UToolTarget * Target, bool & bOutTargetSupportsLODs, bool bOnlyReturnDefaultLOD = false, bool bExcludeAutoGeneratedLODs = true)
Parameters
Target The tool target to query for LODs
bOutTargetSupportsLODs Will be set to 'false' if the target does not support querying MeshDescriptions with LODs
bOnlyReturnDefaultLOD If true, always return an array of just the Default LOD
bExcludeAutoGeneratedLODs If true, exclude any auto-generated LODs (which have no associated Mesh Description) from the LOD list
Returns
An array of valid LODs for the mesh data underlying the ToolTarget, or just the Default LOD if the target doesn't support LODs or bOnlyReturnDefaultLOD is true
References Target.
GetPhysicsBodySetup()
MODELINGCOMPONENTS_API UBodySetup * UE::ToolTarget::GetPhysicsBodySetup (UToolTarget * Target)
Returns
the Physics UBodySetup for the given ToolTarget, or nullptr if it does not exist
References Target.
GetPhysicsCollisionDataProvider()
MODELINGCOMPONENTS_API IInterface_CollisionDataProvider * UE::ToolTarget::GetPhysicsCollisionDataProvider (UToolTarget * Target)
Returns
the Physics CollisionDataProvider (ie Complex Collision source) for the given ToolTarget, or nullptr if it does not exist
References Target.
GetSkeletalMeshFromTargetIfAvailable()
MODELINGCOMPONENTS_API USkeletalMesh * UE::ToolTarget::GetSkeletalMeshFromTargetIfAvailable (UToolTarget * Target)
Returns
SkeletalMesh from a tool target
References Target.
GetStaticMeshFromTargetIfAvailable()
MODELINGCOMPONENTS_API UStaticMesh * UE::ToolTarget::GetStaticMeshFromTargetIfAvailable (UToolTarget * Target)
Returns
StaticMesh from a tool target
References Target.
GetTargetActor()
MODELINGCOMPONENTS_API AActor * UE::ToolTarget::GetTargetActor (UToolTarget * Target)
Returns
the AActor backing a ToolTarget, or nullptr if there is no such Actor
References Target.
GetTargetComponent()
MODELINGCOMPONENTS_API UPrimitiveComponent * UE::ToolTarget::GetTargetComponent (UToolTarget * Target)
Returns
the UPrimitiveComponent backing a ToolTarget, or nullptr if there is no such Component
References Target.
GetTargetMeshDescriptionLOD()
MODELINGCOMPONENTS_API EMeshLODIdentifier UE::ToolTarget::GetTargetMeshDescriptionLOD (UToolTarget * Target, bool & bOutTargetSupportsLODs)
Return identifier for the mesh LOD that a ToolTarget represents, if defined for the given ToolTarget.
Parameters
Target The tool target to query for LODs
bOutTargetSupportsLODs Will be set to 'false' if the target does not support querying MeshDescriptions with LODs
Returns
LODIdentifier for current LOD that would be provided/edited by the ToolTarget, or the Default LODIdentifier if the target doesn't support LODs or bOnlyReturnDefaultLOD is true
References Target.
GetTargetSceneComponent()
MODELINGCOMPONENTS_API USceneComponent * UE::ToolTarget::GetTargetSceneComponent (UToolTarget * Target)
Returns
the UActorComponent backing a ToolTarget, or nullptr if there is no such Component
References Target.
GetTriangleCount()
MODELINGCOMPONENTS_API int32 UE::ToolTarget::GetTriangleCount (UToolTarget * Target)
Returns
The triangle count of Target's persistent dynamic mesh or its mesh description, if available, or 0 otherwise
References GetTriangleCount(), and Target.
Referenced by GetTriangleCount().
HideSourceObject()
MODELINGCOMPONENTS_API bool UE::ToolTarget::HideSourceObject (UToolTarget * Target)
Hide the "Source Object" (eg PrimitiveComponent, Actor, etc) backing a ToolTarget.
Returns
true on success
References Target.
SetSourceObjectVisible()
MODELINGCOMPONENTS_API bool UE::ToolTarget::SetSourceObjectVisible (UToolTarget * Target, bool bVisible)
Show or Hide the "Source Object" (eg PrimitiveComponent, Actor, etc) backing a ToolTarget.
Returns
true on success
References Target.
ShowSourceObject()
MODELINGCOMPONENTS_API bool UE::ToolTarget::ShowSourceObject (UToolTarget * Target)
Show the "Source Object" (eg PrimitiveComponent, Actor, etc) backing a ToolTarget.
Returns
true on success
References Target.
SupportsIncrementalMeshChanges()
MODELINGCOMPONENTS_API bool UE::ToolTarget::SupportsIncrementalMeshChanges (UToolTarget * Target)
Returns
true if ToolTarget can be directly updated via an incremental edits, ie if it is acceptable to call ApplyIncrementalMeshEditChange() on the target
References Target.