Unreal Engine 5.6 C++ API: AnimationCompressionUtils Namespace Reference
AnimationCompressionUtils Namespace Reference
Functions
template<typename T>
FORCEINLINE T Interpolate (const T &A, const T &B, float Alpha)
Helper template function to interpolate between two data types.
template<>
FORCEINLINE FQuat4d Interpolate< FQuat4d > (const FQuat4d &A, const FQuat4d &B, float Alpha)
custom instantiation of Interpolate for FQuats
template<>
FORCEINLINE FQuat4f Interpolate< FQuat4f > (const FQuat4f &A, const FQuat4f &B, float Alpha)
template<>
FORCEINLINE FVector3d Interpolate< FVector3d > (const FVector3d &A, const FVector3d &B, float Alpha)
template<>
FORCEINLINE FVector3f Interpolate< FVector3f > (const FVector3f &A, const FVector3f &B, float Alpha)
custom instantiation of Interpolate for FVectors
template<typename ValueType>
ValueType UnalignedRead (const void *Ptr)
Variables
static constexpr int32 LogScale = 7
Function Documentation
Interpolate()
template<typename T> FORCEINLINE T AnimationCompressionUtils::Interpolate (const T & A, const T & B, float Alpha)
Helper template function to interpolate between two data types.
Used in the FilterLinearKeysTemplate function below
Definition at line 63 of file AnimationCompression.h.
References A, Alpha, B, check, and FORCEINLINE.
Interpolate< FQuat4d >()
template<> FORCEINLINE FQuat4d AnimationCompressionUtils::Interpolate< FQuat4d > (const FQuat4d & A, const FQuat4d & B, float Alpha)
custom instantiation of Interpolate for FQuats
Definition at line 81 of file AnimationCompression.h.
References A, Alpha, B, UE::Math::TQuat< double >::FastLerp(), FORCEINLINE, and UE::Math::TQuat< T >::Normalize().
Interpolate< FQuat4f >()
template<> FORCEINLINE FQuat4f AnimationCompressionUtils::Interpolate< FQuat4f > (const FQuat4f & A, const FQuat4f & B, float Alpha)
Definition at line 88 of file AnimationCompression.h.
References A, Alpha, B, UE::Math::TQuat< float >::FastLerp(), FORCEINLINE, and UE::Math::TQuat< T >::Normalize().
Interpolate< FVector3d >()
template<> FORCEINLINE FVector3d AnimationCompressionUtils::Interpolate< FVector3d > (const FVector3d & A, const FVector3d & B, float Alpha)
Definition at line 75 of file AnimationCompression.h.
References A, Alpha, B, FORCEINLINE, and FMath::Lerp().
Interpolate< FVector3f >()
template<> FORCEINLINE FVector3f AnimationCompressionUtils::Interpolate< FVector3f > (const FVector3f & A, const FVector3f & B, float Alpha)
custom instantiation of Interpolate for FVectors
Definition at line 71 of file AnimationCompression.h.
References A, Alpha, B, FORCEINLINE, and FMath::Lerp().
UnalignedRead()
template<typename ValueType> ValueType AnimationCompressionUtils::UnalignedRead (const void * Ptr) inline
Definition at line 44 of file AnimationCompression.h.
Referenced by DecompressRotation(), FAnimationCompression_PerTrackUtils::DecompressRotation(), DecompressScale(), FAnimationCompression_PerTrackUtils::DecompressScale(), DecompressTranslation(), FAnimationCompression_PerTrackUtils::DecompressTranslation(), FQuatFixed32NoW::ToQuat(), FQuatFloat32NoW::ToQuat(), FQuatFloat96NoW::ToQuat(), FQuatIntervalFixed32NoW::ToQuat(), and FVectorIntervalFixed32NoW::ToVector().
Variable Documentation
LogScale
int32 AnimationCompressionUtils::LogScale = 7 inline static constexpr
Definition at line 41 of file AnimationCompression.h.