Unreal Engine 5.6 C++ API: UE::SavePackageUtilities Namespace Reference
UE::SavePackageUtilities Namespace Reference
Namespaces
namespace Private
Data Structures
struct FPreloadDependency
A dependency in a runtime cook package from the load phase (create or serialize) of one object to the load phase of another object.
Typedefs
using FEDLLogRecordCallback = TFunction<void(UE::FLogRecord&& Record)>
using FEDLMessageCallback = TFunction<void(ELogVerbosity::Type, FStringView)>
Functions
void CallCookEventPlatformCookDependencies (UObject *Object, FObjectSaveContextData &ObjectSaveContext)
Call the CookEvent UE::Cook::ECookEvent::PlatformCookDependencies on the given object.
void CallPostSaveRoot (UObject *Object, FObjectSaveContextData &ObjectSaveContext, bool bCleanupRequired)
Call the PostSaveRoot function on the given object.
void CallPreSave (UObject *Object, FObjectSaveContextData &ObjectSaveContext)
Call the PreSave function on the given object and log a warning if there is an incorrect override.
void CallPreSaveRoot (UObject *Object, FObjectSaveContextData &ObjectSaveContext)
Call the PreSaveRoot function on the given object.
DECLARE_DELEGATE_TwoParams (FAddResaveOnDemandPackage, FName, FName)
void FAddResaveOnDemandPackage(FName SystemName, FName PackageName);
void DecrementOutstandingAsyncWrites ()
int32 GetNumPackagesSaved ()
void IncrementOutstandingAsyncWrites ()
bool IsProceduralSave (bool bIsCooking, const FPackagePath &TargetPackagePath, uint32 SaveFlags)
Return whether the given save parameters indicate the package is a procedural save.
bool IsUpdatingLoadedPath (bool bIsCooking, const FPackagePath &TargetPackagePath, uint32 SaveFlags)
Return whether the given save parameters indicate the LoadedPath of the package being saved should be updated.
EObjectFlags NormalizeTopLevelFlags (EObjectFlags TopLevelFlags, bool bIsCooking)
Add any required TopLevelFlags based on the save parameters.
void ResetCookStats ()
UE_DEPRECATED (5.5, "Functionality has moved into private cooker implementation; contact Epic if you need this functionality.") 1 void VerifyEDLCookInfo(const FEDLMessageCallback &MessageCallback
UE_DEPRECATED (5.5, "No longer used; skiponlyeditoronly is used instead and tracks editoronly references via savepackage results.") inline bool CanSkipEditorReferencedPackagesWhenCooking()
UE_DEPRECATED (5.6, "Functionality has moved into private cooker implementation; contact Epic if you need this functionality.") 1 void StartSavingEDLCookInfoForVerification() = true)
Variables
bool bFullReferencesExpected = true)
bool & bOutHasData
FAddResaveOnDemandPackage OnAddResaveOnDemandPackage
Low-level systems execute this delegate during automated resave-on-demand to request that a package be resaved.
bool FName PackageName
Typedef Documentation
FEDLLogRecordCallback
using UE::SavePackageUtilities::FEDLLogRecordCallback = TFunction<void(UE::FLogRecord&& Record)>
Definition at line 325 of file SavePackage.h.
FEDLMessageCallback
using UE::SavePackageUtilities::FEDLMessageCallback = TFunction<void(ELogVerbosity::Type, FStringView)>
Definition at line 324 of file SavePackage.h.
Function Documentation
CallCookEventPlatformCookDependencies()
void UE::SavePackageUtilities::CallCookEventPlatformCookDependencies (UObject * Object, FObjectSaveContextData & ObjectSaveContext)
Call the CookEvent UE::Cook::ECookEvent::PlatformCookDependencies on the given object.
References CallCookEventPlatformCookDependencies().
Referenced by CallCookEventPlatformCookDependencies().
CallPostSaveRoot()
void UE::SavePackageUtilities::CallPostSaveRoot (UObject * Object, FObjectSaveContextData & ObjectSaveContext, bool bCleanupRequired)
Call the PostSaveRoot function on the given object.
References CallPostSaveRoot().
Referenced by CallPostSaveRoot().
CallPreSave()
void UE::SavePackageUtilities::CallPreSave (UObject * Object, FObjectSaveContextData & ObjectSaveContext)
Call the PreSave function on the given object and log a warning if there is an incorrect override.
References CallPreSave().
Referenced by CallPreSave().
CallPreSaveRoot()
void UE::SavePackageUtilities::CallPreSaveRoot (UObject * Object, FObjectSaveContextData & ObjectSaveContext)
Call the PreSaveRoot function on the given object.
References CallPreSaveRoot().
Referenced by CallPreSaveRoot().
DECLARE_DELEGATE_TwoParams()
UE::SavePackageUtilities::DECLARE_DELEGATE_TwoParams (FAddResaveOnDemandPackage , FName , FName)
void FAddResaveOnDemandPackage(FName SystemName, FName PackageName);
References OnAddResaveOnDemandPackage.
DecrementOutstandingAsyncWrites()
void UE::SavePackageUtilities::DecrementOutstandingAsyncWrites ()
References DecrementOutstandingAsyncWrites().
Referenced by DecrementOutstandingAsyncWrites().
GetNumPackagesSaved()
int32 UE::SavePackageUtilities::GetNumPackagesSaved ()
References GetNumPackagesSaved().
Referenced by GetNumPackagesSaved().
IncrementOutstandingAsyncWrites()
void UE::SavePackageUtilities::IncrementOutstandingAsyncWrites ()
References IncrementOutstandingAsyncWrites().
Referenced by IncrementOutstandingAsyncWrites().
IsProceduralSave()
bool UE::SavePackageUtilities::IsProceduralSave (bool bIsCooking, const FPackagePath & TargetPackagePath, uint32 SaveFlags)
Return whether the given save parameters indicate the package is a procedural save.
Any save without the the possibility of user-generated edits to the package is a procedural save (Cooking, EditorDomain). This allows us to execute transforms that only need to be executed in response to new user data.
References IsProceduralSave(), and SaveFlags.
Referenced by IsProceduralSave().
IsUpdatingLoadedPath()
bool UE::SavePackageUtilities::IsUpdatingLoadedPath (bool bIsCooking, const FPackagePath & TargetPackagePath, uint32 SaveFlags)
Return whether the given save parameters indicate the LoadedPath of the package being saved should be updated.
This allows us to update the in-memory package when it is saved in editor to match its new save file.
References IsUpdatingLoadedPath(), and SaveFlags.
Referenced by IsUpdatingLoadedPath().
NormalizeTopLevelFlags()
EObjectFlags UE::SavePackageUtilities::NormalizeTopLevelFlags (EObjectFlags TopLevelFlags, bool bIsCooking)
Add any required TopLevelFlags based on the save parameters.
References NormalizeTopLevelFlags().
Referenced by NormalizeTopLevelFlags().
ResetCookStats()
void UE::SavePackageUtilities::ResetCookStats ()
References ResetCookStats().
Referenced by ResetCookStats().
UE_DEPRECATED() [1/3]
UE::SavePackageUtilities::UE_DEPRECATED (5. 5, "Functionality has moved into private cooker implementation; contact Epic if you need this functionality.") const &
References UE_DEPRECATED().
UE_DEPRECATED() [2/3]
UE::SavePackageUtilities::UE_DEPRECATED (5. 5, "No longer used; skiponlyeditoronly is used instead and tracks editoronly references via savepackage results.")
Definition at line 341 of file SavePackage.h.
References UE_DEPRECATED().
UE_DEPRECATED() [3/3]
UE::SavePackageUtilities::UE_DEPRECATED (5. 6, "Functionality has moved into private cooker implementation; contact Epic if you need this functionality.") = true)
Referenced by UE_DEPRECATED(), and UE_DEPRECATED().
Variable Documentation
bFullReferencesExpected
bool UE::SavePackageUtilities::bFullReferencesExpected = true)
Definition at line 329 of file SavePackage.h.
bOutHasData
bool & UE::SavePackageUtilities::bOutHasData
Definition at line 335 of file SavePackage.h.
OnAddResaveOnDemandPackage
FAddResaveOnDemandPackage UE::SavePackageUtilities::OnAddResaveOnDemandPackage extern
Low-level systems execute this delegate during automated resave-on-demand to request that a package be resaved.
Automated resave managers like the ResavePackagesCommandlet subscribe to it to know which packages to save.
Referenced by DECLARE_DELEGATE_TwoParams().
PackageName
bool FName UE::SavePackageUtilities::PackageName
Definition at line 337 of file SavePackage.h.