Unreal Engine 5.6 C++ API: UE::GC Namespace Reference
UE::GC Namespace Reference
Namespaces
namespace Private
Data Structures
struct FDebugSchemaStackNode
Maintains a stack of schemas currently processed by reachability analysis for debugging referencing property names.
struct FDebugSchemaStackNoOpScope
struct FDebugSchemaStackScope
struct FMemberDeclaration
class FMemberId
Debug identifier for a schema index or a memberless reference.
struct FMemberInfo
struct FMemberPacked
union FMemberWord
class FPrefetchingObjectIterator
struct FProcessorStats
class FPropertyStack
Helps generate debug property paths for GC schemas and to resolve them back to FProperties.
class FPropertyStackScope
class FSchemaBuilder
struct FSchemaHeader
class FSchemaOwner
Type-erasing owner of a ref-counted FSchemaView.
class FSchemaView
Describes all strong GC references in a class or struct.
struct FSlowARO
struct FStridedLayout
struct FStructArray
struct FSuspendedStructBatch
union FUnreachableObject
Entry in GUnreachableObjects array that can either be an FUObjectItem (initially) or an UObject after unreachable objects had their InternalIndex freed.
struct FWeakReferenceInfo
struct FWorkBlock
Fixed block of reachable objects waiting to be processed.
class FWorkBlockifier
Reachable objects waiting to be processed.
struct FWorkerContext
Thread-local context containing initial objects and references to collect.
class TDefaultCollector
Default reference collector for CollectReferences()
struct TDirectDispatcher
Forwards references directly to ProcessorType::HandleTokenStreamObjectReference(), unlike TBatchDispatcher.
class TFastReferenceCollector
Helper class that looks for UObject references by traversing UClass token stream and calls AddReferencedObjects.
struct TGetDispatcherType
struct TMemberDeclaration
class TSchemaBuilder
Typedefs
using ETokenlessId = EMemberlessId
using FTokenId = FMemberId
using ObjectAROFn = void (*)(UObject*, FReferenceCollector&)
using StructAROFn = void (*)(void*, FReferenceCollector&)
Enumerations
enum class EAROFlags { None = 0 , Unbalanced = 1 << 0 , ExtraSlow = 2 << 0 }
enum class ELoot { Nothing , Block , ARO , Context }
enum class EMemberlessId {
Collector = 1 , Class , Outer , ExternalPackage ,
ClassOuter , InitialReference , Max = InitialReference
}
enum class EMemberType : uint8 {
Stop , Jump , Reference , ReferenceArray ,
StructArray , StridedArray , SparseStructArray , FieldPath ,
FieldPathArray , FreezableReferenceArray , FreezableStructArray , Optional ,
DynamicallyTypedValue , ARO , SlowARO , MemberARO ,
Count
}
Describes member variable types, AddReferencedObject calls and stop/jump instructions used by VisitMembers.
enum class EOrigin : uint8 { Other , Blueprint }
Declares if a schema represents a blueprint generated type.
Functions
uint32 CountSchemas (uint32 &OutNumWords)
template<class T>
void DeclareIntrinsicMembers (UClass *Class, std::initializer_list< TMemberDeclaration< T > > Members)
void DeclareIntrinsicSchema (UClass *Class, FSchemaView IntrinsicSchema)
template<typename NameType>
FMemberDeclaration DeclareMember (NameType &&Name, uint32 Offset, EMemberType Type)
template<typename NameType, typename ExtraWordType>
FMemberDeclaration DeclareMember (NameType &&Name, uint32 Offset, EMemberType Type, ExtraWordType Extra)
ENUM_CLASS_FLAGS (EAROFlags)
template<class CollectorType, class ProcessorType>
TDirectDispatcher< ProcessorType > GetDispatcher (CollectorType &Collector, ProcessorType &Processor, FWorkerContext &Context)
FSchemaView GetIntrinsicSchema (UClass *Class)
FMemberInfo GetMemberDebugInfo (FSchemaView Schema, FMemberId Id)
void MarkAsReachable (const UObject *Obj)
Marks the object as Reachable if it's currently marked as MaybeUnreachable by incremental GC.
void PadObjectArray (TArray< UObject * > &Objects)
void ProcessAsync (void(*ProcessSync)(void *, FWorkerContext &), void *Processor, FWorkerContext &InitialContext)
Allocates contexts and coordinator, kicks worker tasks that also call ProcessSync.
void RegisterSlowImplementation (void(*AddReferencedObjects)(UObject *, FReferenceCollector &), EAROFlags Flags=EAROFlags::None)
ELoot StealWork (FWorkerContext &Context, FReferenceCollector &Collector, FWorkBlock *&OutBlock, EGCOptions Options)
void SuspendWork (FWorkerContext &Context)
FName ToName (const char *Name)
FName ToName (EMemberType Type)
FName ToName (FPropertyStack &Stack)
FMemberWord ToWord (FSchemaView In)
FMemberWord ToWord (StructAROFn In)
UE_DEPRECATED (5.5, "GMaybeUnreachableObjectFlag should no longer be used.") extern 1 EInternalObjectFlags GMaybeUnreachableObjectFlag
Current EInternalObjectFlags value representing a maybe unreachable object.
UE_DEPRECATED (5.5, "GUnreachableObjectFlag should no longer be used. Use Object->IsUnreachable() instead.") extern 1 EInternalObjectFlags GUnreachableObjectFlag
Current EInternalObjectFlags value representing an unreachable object.
UE_DEPRECATED (5.5, "GUnreachableObjectFlag should no longer be used.") extern 1 EInternalObjectFlags GReachableObjectFlag
Current EInternalObjectFlags value representing a reachable object.
Variables
constexpr EGCOptions DefaultOptions = EGCOptions::AutogenerateSchemas
bool GIsIncrementalReachabilityPending
true if incremental reachability analysis is in progress (global for faster access in low level structs and functions otherwise use IsIncrementalReachabilityAnalisysPending())
static constexpr uint32 ObjectLookahead = 16
Typedef Documentation
ETokenlessId
using UE::GC::ETokenlessId = EMemberlessId
Definition at line 1175 of file FastReferenceCollector.h.
FTokenId
using UE::GC::FTokenId = FMemberId
Definition at line 1174 of file FastReferenceCollector.h.
ObjectAROFn
using UE::GC::ObjectAROFn = void (*)(UObject*, FReferenceCollector&)
Definition at line 203 of file GarbageCollectionSchema.h.
StructAROFn
using UE::GC::StructAROFn = void (*)(void*, FReferenceCollector&)
Definition at line 204 of file GarbageCollectionSchema.h.
Enumeration Type Documentation
EAROFlags
enum class UE::GC::EAROFlags strong
Enumerator
None
Unbalanced
ExtraSlow
Definition at line 50 of file GarbageCollection.h.
ELoot
enum class UE::GC::ELoot strong
Enumerator
Nothing
Block
ARO
Context
Definition at line 863 of file FastReferenceCollector.h.
EMemberlessId
enum class UE::GC::EMemberlessId strong
Enumerator
Collector
Class
Outer
ExternalPackage
ClassOuter
InitialReference
Max
Definition at line 143 of file GarbageCollectionSchema.h.
EMemberType
enum class UE::GC::EMemberType : uint8 strong
Describes member variable types, AddReferencedObject calls and stop/jump instructions used by VisitMembers.
Enumerator
Stop
Jump
Reference
ReferenceArray
StructArray
StridedArray
SparseStructArray
FieldPath
FieldPathArray
FreezableReferenceArray
FreezableStructArray
Optional
DynamicallyTypedValue
ARO
SlowARO
MemberARO
Count
Definition at line 24 of file GarbageCollectionSchema.h.
EOrigin
enum class UE::GC::EOrigin : uint8 strong
Declares if a schema represents a blueprint generated type.
Enumerator
Other
Blueprint
Definition at line 52 of file GarbageCollectionSchema.h.
Function Documentation
CountSchemas()
uint32 UE::GC::CountSchemas (uint32 & OutNumWords)
DeclareIntrinsicMembers()
template<class T> void UE::GC::DeclareIntrinsicMembers (UClass * Class, std::initializer_list< TMemberDeclaration< T > > Members)
Definition at line 391 of file GarbageCollectionSchema.h.
References Class, and DeclareIntrinsicSchema().
DeclareIntrinsicSchema()
void UE::GC::DeclareIntrinsicSchema (UClass * Class, FSchemaView IntrinsicSchema)
References Class.
Referenced by DeclareIntrinsicMembers().
DeclareMember() [1/2]
template<typename NameType> FMemberDeclaration UE::GC::DeclareMember (NameType && Name, uint32 Offset, EMemberType Type)
Definition at line 250 of file GarbageCollectionSchema.h.
References Forward(), Name, ToName(), and UE_GC_DEBUGNAMES.
Referenced by UE::GC::TMemberDeclaration< T >::TMemberDeclaration().
DeclareMember() [2/2]
template<typename NameType, typename ExtraWordType> FMemberDeclaration UE::GC::DeclareMember (NameType && Name, uint32 Offset, EMemberType Type, ExtraWordType Extra)
Definition at line 257 of file GarbageCollectionSchema.h.
References Forward(), Name, ToName(), ToWord(), and UE_GC_DEBUGNAMES.
ENUM_CLASS_FLAGS()
UE::GC::ENUM_CLASS_FLAGS (EAROFlags)
GetDispatcher()
template<class CollectorType, class ProcessorType> TDirectDispatcher< ProcessorType > UE::GC::GetDispatcher (CollectorType & Collector, ProcessorType & Processor, FWorkerContext & Context)
Definition at line 849 of file FastReferenceCollector.h.
References Collector, Context, and GetDispatcher().
Referenced by GetDispatcher(), and UE::GC::TFastReferenceCollector< ProcessorType, CollectorType >::ProcessObjectArray().
GetIntrinsicSchema()
FSchemaView UE::GC::GetIntrinsicSchema (UClass * Class)
References Class.
GetMemberDebugInfo()
FMemberInfo UE::GC::GetMemberDebugInfo (FSchemaView Schema, FMemberId Id)
MarkAsReachable()
void UE::GC::MarkAsReachable (const UObject * Obj)
Marks the object as Reachable if it's currently marked as MaybeUnreachable by incremental GC.
Referenced by UE::Core::Private::TMutableViewTraits< TArray< TObjectPtr< T > >, ViewType >::Close(), UE::Core::Private::TMutableViewTraits< TMap< K, V >, ViewType >::Close(), UE::Core::Private::TMutableViewTraits< TObjectPtr< T >, ViewType >::Close(), UE::Core::Private::TMutableViewTraits< TSet< TObjectPtr< V > >, ViewType >::Close(), FFieldVariant::ConditionallyMarkAsReachable(), FObjectPtr::ConditionallyMarkAsReachable(), FObjectPtr::ConditionallyMarkAsReachable(), UE::Core::Private::TMaybeObjectPtr< T >::ConditionallyMarkAsReachable(), and UE::FDynamicallyTypedValue::MarkTypeReachableIfIncrementalReachabilityPending().
PadObjectArray()
void UE::GC::PadObjectArray (TArray< UObject * > & Objects)
Referenced by UE::GC::FWorkerContext::SetInitialObjectsUnpadded().
ProcessAsync()
void UE::GC::ProcessAsync (void(* ProcessSync)(void *, FWorkerContext &), void * Processor, FWorkerContext & InitialContext)
Allocates contexts and coordinator, kicks worker tasks that also call ProcessSync.
Processor is type-erased to void* to avoid templated code.
References ProcessAsync().
Referenced by CollectReferences(), and ProcessAsync().
RegisterSlowImplementation()
void UE::GC::RegisterSlowImplementation (void(* AddReferencedObjects)(UObject *, FReferenceCollector &), EAROFlags Flags = EAROFlags::None)
References Flags, and None.
StealWork()
ELoot UE::GC::StealWork (FWorkerContext & Context, FReferenceCollector & Collector, FWorkBlock *& OutBlock, EGCOptions Options)
References Collector, Context, UE::Options, and StealWork().
Referenced by UE::GC::TFastReferenceCollector< ProcessorType, CollectorType >::ProcessObjectArray(), and StealWork().
SuspendWork()
void UE::GC::SuspendWork (FWorkerContext & Context)
References Context, and SuspendWork().
Referenced by UE::GC::TFastReferenceCollector< ProcessorType, CollectorType >::ProcessObjectArray(), and SuspendWork().
ToName() [1/3]
FName UE::GC::ToName (const char * Name) inline
Definition at line 245 of file GarbageCollectionSchema.h.
References FName, and Name.
ToName() [2/3]
FName UE::GC::ToName (EMemberType Type)
Referenced by DeclareMember(), and DeclareMember().
ToName() [3/3]
FName UE::GC::ToName (FPropertyStack & Stack) inline
Definition at line 246 of file GarbageCollectionSchema.h.
References FName, and UE::GC::FPropertyStack::GetPropertyPath().
ToWord() [1/2]
FMemberWord UE::GC::ToWord (FSchemaView In) inline
Definition at line 221 of file GarbageCollectionSchema.h.
References UE::GC::FMemberWord::InnerSchema.
Referenced by DeclareMember().
ToWord() [2/2]
FMemberWord UE::GC::ToWord (StructAROFn In) inline
Definition at line 228 of file GarbageCollectionSchema.h.
References UE::GC::FMemberWord::StructARO.
UE_DEPRECATED() [1/3]
UE::GC::UE_DEPRECATED (5. 5, "GMaybeUnreachableObjectFlag should no longer be used.")
Current EInternalObjectFlags value representing a maybe unreachable object.
References GIsIncrementalReachabilityPending, and UE_DEPRECATED().
UE_DEPRECATED() [2/3]
UE::GC::UE_DEPRECATED (5. 5, "GUnreachableObjectFlag should no longer be used. Use Object->IsUnreachable() instead.")
Current EInternalObjectFlags value representing an unreachable object.
References UE_DEPRECATED().
UE_DEPRECATED() [3/3]
UE::GC::UE_DEPRECATED (5. 5, "GUnreachableObjectFlag should no longer be used.")
Current EInternalObjectFlags value representing a reachable object.
Referenced by UE_DEPRECATED(), and UE_DEPRECATED().
Variable Documentation
DefaultOptions
EGCOptions UE::GC::DefaultOptions = EGCOptions::AutogenerateSchemas inline constexpr
Definition at line 1110 of file FastReferenceCollector.h.
GIsIncrementalReachabilityPending
bool UE::GC::GIsIncrementalReachabilityPending extern
true if incremental reachability analysis is in progress (global for faster access in low level structs and functions otherwise use IsIncrementalReachabilityAnalisysPending())
Referenced by UE::Core::Private::TMutableViewTraits< TArray< TObjectPtr< T > >, ViewType >::Close(), UE::Core::Private::TMutableViewTraits< TMap< K, V >, ViewType >::Close(), UE::Core::Private::TMutableViewTraits< TObjectPtr< T >, ViewType >::Close(), UE::Core::Private::TMutableViewTraits< TSet< TObjectPtr< V > >, ViewType >::Close(), CollectReferences(), FFieldVariant::ConditionallyMarkAsReachable(), FObjectPtr::ConditionallyMarkAsReachable(), FObjectPtr::ConditionallyMarkAsReachable(), UE::Core::Private::TMaybeObjectPtr< T >::ConditionallyMarkAsReachable(), UE::FDynamicallyTypedValue::MarkTypeReachableIfIncrementalReachabilityPending(), and UE_DEPRECATED().
ObjectLookahead
uint32 UE::GC::ObjectLookahead = 16 static constexpr
Definition at line 86 of file FastReferenceCollector.h.
Referenced by UE::GC::FPrefetchingObjectIterator::Advance(), UE::GC::FWorkBlock::GetPadding(), and UE::GC::FWorkerContext::SetInitialObjectsPrepadded().