Unreal Engine 5.6 C++ API: UE::Anim::AnimationData Namespace Reference
UE::Anim::AnimationData Namespace Reference
Functions
bool AddLoopingInterpolation (UAnimSequence *InSequence)
Adds an additional animated frame to match with the first animated frame, attempting to make it loop.
void DuplicateKeys (UAnimSequence *InSequence, int32 StartKeyIndex, int32 NumDuplicates, int32 SourceKeyIndex=INDEX_NONE)
Insert duplicate key(s) for all tracks for the provided Animation Sequence.
FName FindFirstChildTrackName (const UAnimSequence *InSequence, const USkeleton *Skeleton, const FName &BoneName)
Finds the name of the first child track (bone) for the provided bone name.
void RemoveKeys (UAnimSequence *InSequence, int32 StartKeyIndex, int32 NumKeysToRemove)
Remove a number of keys for all tracks for the provided Animation Sequence.
bool Trim (UAnimSequence *InSequence, TRange< FFrameNumber > TrimRange)
Trim a specific window from the animation data.
UE_DEPRECATED (5.2, "FindFirstChildTrackIndex has been deprecated, use FindFirstChildTrackName instead") static int32 FindFirstChildTrackIndex(const UAnimSequence *InSequence
UE_DEPRECATED (5.6, "Trimming operation using time values has been deprecated use Trim with FFrameNumbers instead") 1 bool Trim(UAnimSequence *InSequence
Variables
float float bool bInclusiveEnd =false)
const USkeleton const FName & BoneName { return INDEX_NONE
const USkeleton * Skeleton
float float TrimEnd
float TrimStart
Function Documentation
AddLoopingInterpolation()
bool UE::Anim::AnimationData::AddLoopingInterpolation (UAnimSequence * InSequence)
Adds an additional animated frame to match with the first animated frame, attempting to make it loop.
Parameters
InSequence Animation Sequence to add the animated frame to
Returns
Whether or not the operation was succesful
References AddLoopingInterpolation().
Referenced by AddLoopingInterpolation().
DuplicateKeys()
void UE::Anim::AnimationData::DuplicateKeys (UAnimSequence * InSequence, int32 StartKeyIndex, int32 NumDuplicates, int32 SourceKeyIndex = INDEX_NONE)
Insert duplicate key(s) for all tracks for the provided Animation Sequence.
Parameters
InSequence Animation Sequence to add the duplicated animation frames
StartKeyIndex Key index after which the duplicate keys should be inserted
NumDuplicates Number of duplicated keys to insert
SourceKeyIndex Specific key index to use as a source for the duplicated keys, otherwise uses key at StartKeyIndex
References DuplicateKeys(), and INDEX_NONE.
Referenced by DuplicateKeys().
FindFirstChildTrackName()
FName UE::Anim::AnimationData::FindFirstChildTrackName (const UAnimSequence * InSequence, const USkeleton * Skeleton, const FName & BoneName)
Finds the name of the first child track (bone) for the provided bone name.
Parameters
InSequence Animation Sequence to remove the animated frames from
Skeleton Skeleton to use for retrieving child bone names
BoneName Name of the bone to find the child track index for
Returns
The first child track name for the provided bone name, if none found will return NAME_None
References BoneName, FindFirstChildTrackName(), and Skeleton.
Referenced by FindFirstChildTrackName().
RemoveKeys()
void UE::Anim::AnimationData::RemoveKeys (UAnimSequence * InSequence, int32 StartKeyIndex, int32 NumKeysToRemove)
Remove a number of keys for all tracks for the provided Animation Sequence.
Parameters
InSequence Animation Sequence to remove the animated frames from
StartKeyIndex Key index at which the key removal should start
NumKeysToRemove Number of keys to remove
References RemoveKeys().
Referenced by RemoveKeys().
Trim()
bool UE::Anim::AnimationData::Trim (UAnimSequence * InSequence, TRange< FFrameNumber > TrimRange)
Trim a specific window from the animation data.
Parameters
InSequence Animation Sequence to add the animated frame to
TrimRange Range of frame numbers to remove
Returns
Whether or not the operation was succesful
References Trim().
Referenced by Trim().
UE_DEPRECATED() [1/2]
UE::Anim::AnimationData::UE_DEPRECATED (5. 2, "FindFirstChildTrackIndex has been deprecated , use FindFirstChildTrackName instead") const
References UE_DEPRECATED().
UE_DEPRECATED() [2/2]
UE::Anim::AnimationData::UE_DEPRECATED (5. 6, "Trimming operation using time values has been deprecated use Trim with FFrameNumbers instead")
Referenced by UE_DEPRECATED().
Variable Documentation
bInclusiveEnd
float float bool UE::Anim::AnimationData::bInclusiveEnd =false)
Definition at line 142 of file AnimSequenceHelpers.h.
BoneName
const USkeleton const FName& UE::Anim::AnimationData::BoneName { return INDEX_NONE
Definition at line 175 of file AnimSequenceHelpers.h.
Referenced by FindFirstChildTrackName().
Skeleton
const USkeleton* UE::Anim::AnimationData::Skeleton
Definition at line 175 of file AnimSequenceHelpers.h.
Referenced by FindFirstChildTrackName().
TrimEnd
float float UE::Anim::AnimationData::TrimEnd
Definition at line 142 of file AnimSequenceHelpers.h.
TrimStart
float UE::Anim::AnimationData::TrimStart
Definition at line 142 of file AnimSequenceHelpers.h.