Unreal Engine 5.6 C++ API: UE Namespace Reference
UE Namespace Reference
Utility functions for applying transformations to meshes.
Namespaces
namespace AccessDetection
namespace AI
namespace Analytics
namespace Anim
namespace Animation
namespace AnimBank
namespace AnimNext
Synchronization Role.
namespace ArchiveStackTrace
namespace AssetAccessRestrictions
namespace AssetPlacementUtil
namespace AssetRegistry
namespace AssetUtils
namespace AudioEditor
namespace BulkData
namespace BulkDataRegistry
namespace CaptureCardMediaSource
namespace Chaos
namespace ChaosDeformable
namespace ChaosMover
namespace Color
namespace CompactBinary
namespace ComparisonUtility
namespace CompressedBuffer
namespace ConfigAccessTracking
namespace ConfigUtilities
namespace Conversion
namespace Cook
namespace Core
namespace CoreRedirects
namespace CoreUObject
namespace CubicBezier
namespace Cursor
namespace CurveEditor
namespace Curves
namespace Dataflow
Extract a named integer from the results of an ImportGEO node.
namespace DataflowAssetDefinitionHelpers
namespace DataflowSimulationGeometryCache
namespace DataValidation
namespace DebugDrawHelper
namespace Delegates
namespace Deque
namespace DerivedData
namespace DiffCook
namespace DirectoryTree
namespace DisplayClusterConfiguratorClusterUtils
namespace DisplayClusterProjectionHelpers
namespace DisplayClusterViewportHelpers
Helper functions for the DisplayClusterViewport.
namespace DisplayClusterWarpStrings
namespace DynamicConfig
namespace Editor
namespace EditorPixelStreaming
namespace EditorPixelStreaming2
namespace EnumFlags
namespace FieldNotification
namespace FloorQueryUtility
namespace GameplayTags
namespace GC
namespace Geometry
namespace GizmoRenderingUtil
Utility functions for standard GizmoComponent rendering.
namespace GizmoUtil
Gizmo builder that simply calls a particular lambda when building a gizmo.
namespace GPUTextureTransfer
namespace Graph
namespace Groom
namespace Insights
namespace InstanceAttributeTracker
namespace Interchange
namespace Kismet
namespace Landscape
namespace LinkerLoad
namespace LiveLink
namespace LLMPrivate
namespace Logging
namespace LWC
namespace MaterialInterface
namespace Math
Implements an axis-aligned box.
namespace MediaCapture
namespace MediaCaptureData
namespace MediaIO
Timecode formats.
namespace MediaIOCore
namespace MemStack
namespace MeshAutoRepair
namespace MeshCurvature
Implementations of various mesh curvatures and curvature-related metrics.
namespace MeshDeformation
namespace MeshDescription
namespace MeshFileUtils
namespace MeshUVTransforms
namespace Modeling
namespace Mover
namespace MoverUtils
namespace MoveSceneTools
namespace MovieScene
namespace MovieSceneTools
namespace Net
Responsible for creating headers allowing remote factories to spawn replicated actors.
namespace Object
namespace Package
namespace ParkingLot
ParkingLot is a global table of queues of waiting threads keyed by memory address.
namespace PhysicsTools
namespace PipelineCacheUtilities
namespace PixelFormat
namespace PixelStreaming
Helpers for creating webrtc buffers.
namespace PixelStreaming2
namespace PixelStreaming2Input
namespace PixelStreaming2Servers
namespace PixelStreamingServers
namespace PoseSearch
namespace Positioning
namespace Private
The global memory allocator.
namespace Profiling
namespace ProjectUtilities
namespace PropertyEditor
Utilities related to copy/paste.
namespace Reflection
namespace RemoteExecutor
namespace RemoteObject
Remote objects are unique UObjects that are referenced by a local server instance but their memory is actually owned by (exists on) another server.
namespace RenderCommandPipe
namespace RenderCore
namespace Renderer
namespace ReplaySubsystem
namespace RigVM
namespace SavePackageUtilities
namespace SculptFalloffs
namespace SculptUtil
namespace SequenceNavigator
namespace Sequencer
namespace Serialization
namespace Shader
namespace ShaderCompiler
namespace ShaderParameters
namespace ShaderPermutationUtils
namespace ShaderUtils
namespace SharedBuffer
namespace SharedMemoryMedia
namespace SkeletalRender
namespace Slate
namespace SmartObject
namespace SoftObjectPath
namespace Solvers
namespace SoundWaveLoadingUtil
namespace SourceLocation
namespace SplineMesh
namespace StateTree
Data type the FStateTreeDataHandle is pointing at.
namespace Stats
namespace StereoRenderUtils
namespace StreamableManager
namespace String
namespace StringTable
namespace StructuredArchive
namespace StructUtils
namespace SVT
namespace Tasks
namespace Text
namespace Text3D
namespace TextureAssetActions
namespace TextureDefines
namespace Tick
namespace ToolTarget
namespace Trace
namespace Transaction
namespace TransactionUtil
namespace TransformGizmoUtil
namespace UMG
namespace UnifiedError
namespace UniversalObjectLocator
namespace UnrealEd
namespace UObjectArrayPrivate
namespace Virtualization
namespace VisualLogger
namespace VPUtilities
namespace WaterInfo
namespace WeightMaps
Data Structures
struct CSerializableForLog
Describes a type that can be serialized for use in a log message.
struct FAcquireLock
Use to acquire a lock on construction.
class FAssetLog
struct FChangeTransactor
Helper structure used for inserting FChange based undo/redo operations inside of the GUndo (ITransaction) instance.
class FConditionVariable
A one-byte portable condition variable.
struct FDeferLock
Use with dynamic locks to defer locking on construction.
class FDerivedData
Derived Data Reference.
class FDerivedDataIoBatch
Batch of requests to access Derived Data References.
class FDerivedDataIoOptions
Options for operations on a Derived Data Reference.
struct FDerivedDataIoPriority
Priority for scheduling an operation on a Derived Data Reference.
class FDerivedDataIoRequest
Request on a Derived Data Reference that may be used to query the associated response.
class FDerivedDataIoResponse
Tracks one or more associated requests dispatched by FDerivedDataIoBatch.
struct FDynamicallyTypedValue
struct FDynamicallyTypedValueType
class FEncryptionKeyManager
Manages a set of registered encryption key(s).
class FExternalMutex
A mutex which takes it state from an external source and uses only its 2 LSBs.
class FGenericPlatformIoDispatcher
class FGenericPlatformIoDispatcherFactory
class FInheritedContextBase
class FInheritedContextScope
struct FIoBlockKey
struct FIoBufferHandle
class FIoChunkBlockMemoryPool
struct FIoDirectReadRequestParams
Parameters for reading directly from file on disk to the destination buffer.
class FIoDispatcherFilesystemStats
struct FIoEncodedBlockRequest
class FIoFileBlockCache
struct FIoFileBlockLink
class FIoFileBlockMemoryPool
struct FIoFileBlockRequest
class FIoFileBlockRequestQueue
struct FIoFileHandle
Handle to a file on disk.
struct FIoFileProperties
File properties are used to determine whether it's possible to use direct-read, i.e.
struct FIoFileReadRequest
Handle to a platform file read request.
struct FIoFileReadResult
File read result.
struct FIoFileStat
File stats returned when opening a file for reading.
struct FIoPlatformFileInfo
struct FIoPlatformReadRequest
class FIoScatterGatherRequestParams
The scatter-gather parameters specifies the I/O store encoded block boundaries, whether the block is compressed and or encrypted, whether to check the block signature hash and from where in the uncompressed block to copy the block data to the destination buffer.
class FLogRecord
Record of a log event.
struct FLogTemplateOptions
Options to control how log templates are parsed and perform formatting.
class FLogTime
Time that a log event occurred.
class FMacSystemWideMutex
A system-wide mutex for Mac.
class FManualResetEvent
A type of event that remains notified until manually reset.
struct FMonotonicTimePoint
A point in time measured in seconds since an arbitrary epoch.
struct FMonotonicTimeSpan
A span of time measured in seconds between two time points.
struct FMountPaksExArgs
struct FMultiprocessCreatedContext
struct FMultiprocessDetachedContext
class FMutex
A one-byte mutex that is not fair and does not support recursive locking.
class FPackageTrailer
The package trailer should only ever stored the payloads in the workspace domain.
class FPackageTrailerBuilder
This class is used to build a FPackageTrailer and write it disk.
struct FPayloadInfo
class FPlatformIoDispatcher
class FPlatformIoDispatcherBase
This is a base class for platform specific I/O dispatcher implementations.
struct FPlatformIoDispatcherCreateParams
Parameters passed to the platform specific I/O dispatcher.
class FPlatformIoDispatcherRequestMgr
class FPlatformIoDispatcherStats
class FPlatformRWLock
Adapter for FPlatformSharedMutex to the API expected for FRWLock.
class FPlatformSystemWideMutexNotImplemented
Platforms that don't need a working FPlatformSystemWideMutex can alias this one.
class FPropertyPathName
Represents the path to a property, by name, including the property type and the container index.
struct FPropertyPathNameSegment
Represents one segment of a property path including the property type and the container index.
class FPropertyPathNameTree
A tree of property path names and their associated types.
class FPropertyTypeName
Represents the type name of a property, including any containers and underlying types.
class FPropertyTypeNameBuilder
Builder for FPropertyTypeName.
struct FPropertyTypeNameNode
struct FPropertyValueInContainer
A reference to a single property value in a container.
class FRecursiveMutex
An eight-byte mutex that is not fair and supports recursive locking.
struct FScopedCompoundTransaction
struct FScopedObjectSerializeContext
An object that configures the FUObjectSerializeContext for serialization of the object with the archive.
class FScriptTimeLimiter
class FSharedMutex
A four-byte shared mutex that is not fair and does not support recursive locking.
class FSharedRecursiveMutex
An eight-byte shared mutex that is not fair and supports recursive locking.
class FSourceLocation
class FSpinLock
class FTimeout
Utility class to create a timeout that will expire at a point in the future.
class FUnixSystemWideMutex
A system-wide mutex for Unix.
class FWindowsRecursiveMutex
A mutex that supports recursive locking.
class FWindowsSharedMutex
A shared (read/write) mutex that does not support recursive locking.
class FWindowsSystemWideMutex
A system-wide mutex for Windows.
class FWordMutex
A mutex that is the size of a pointer and does not depend on ParkingLot.
class IInteractiveToolCommandsInterface
Interface for functions that get called on command objects on tool start/end.
class IPlatformIoDispatcher
Interface for platform specific I/O dispatcher.
class T
class TConditionalScopeLock
class TConsumeAllMpmcQueue
Multi-producer/multi-consumer unbounded concurrent queue (implemented as a Stack) that is atomically consumed and is reset to its default empty state.
class TDynamicSharedLock
A shared mutex ownership wrapper that allows dynamic locking, unlocking, and deferred locking.
class TDynamicSharedLock< FSharedRecursiveMutex >
class TDynamicUniqueLock
A mutex ownership wrapper that allows dynamic locking, unlocking, and deferred locking.
class TEventCount
A type of event that avoids missed notifications by maintaining a notification count.
class TEventCountToken
A token used to wait on TEventCount.
class TGenericPlatformSharedMutex
TGenericPlatformSharedMutex - Read/Write Mutex.
class TLogTemplate
A log template that is templated on its storage.
class TMultiUniqueLock
class TReadScopeLock
class TRWScopeLock
class TRWSpinLock
class TScopeLock
class TScopeTryLock
RAII-style scope locking of a synchronization primitive using TryLock.
class TScopeUnlock
class TSharedLock
A basic shared mutex ownership wrapper that locks on construction and unlocks on destruction.
class TSharedLock< FSharedRecursiveMutex >
class TSharedString
A reference to an immutable, shared, reference-counted string.
class TUniqueLock
A basic mutex ownership wrapper that locks on construction and unlocks on destruction.
class TWriteScopeLock
Typedefs
using FAnsiSharedString = TSharedString<ANSICHAR>
using FDerivedDataIoComplete = TUniqueFunction<void ()>
using FEventCount = TEventCount<uint32>
using FEventCountToken = TEventCountToken<uint32>
using FInlineLogTemplate = TLogTemplate<Logging::Private::FInlineLogTemplateStorage>
A log template that stores its data inline.
using FIoEncodedBlockRequestAllocator = TSingleThreadedSlabAllocator<FIoEncodedBlockRequest>
using FIoEncodedBlockRequestList = TIntrusiveList<FIoEncodedBlockRequest>
using FIoFileBlockLinkAllocator = TSingleThreadedSlabAllocator<FIoFileBlockLink>
using FIoFileBlockRequestAllocator = TSingleThreadedSlabAllocator<FIoFileBlockRequest>
using FIoFileBlockRequestList = TIntrusiveList<FIoFileBlockRequest>
using FIoFileReadRequestCompleted = TUniqueFunction<void(FIoFileReadResult&&)>
using FIoPlatformReadRequestAllocator = TSingleThreadedSlabAllocator<FIoPlatformReadRequest>
using FIoPlatformReadRequestList = TIntrusiveList<FIoPlatformReadRequest>
using FPlatformIoDispatcherFactory = FGenericPlatformIoDispatcherFactory
using FPlatformRecursiveMutex = FPThreadsRecursiveMutex
using FPlatformSharedMutex = FPThreadsSharedMutex
using FPlatformSystemWideMutex = FPlatformSystemWideMutexNotImplemented
using FRWSpinLock = TRWSpinLock<uint32>
using FSharedString = TSharedString<TCHAR>
template<typename T, SIZE_T Size = 8>
using FTempArray = TArray<T, TInlineAllocator<Size>>
using FTransactionallySafeMutex = FMutex
using FTransactionallySafeRecursiveMutex = ::UE::FRecursiveMutex
using FUniqueLogTemplate = TLogTemplate<Logging::Private::FUniqueLogTemplateStorage>
A log template that stores its data on the heap.
using FUtf8SharedString = TSharedString<UTF8CHAR>
using FWideSharedString = TSharedString<WIDECHAR>
Enumerations
enum class EConsumeAllMpmcQueueResult { HadItems , WasEmpty }
enum class EDerivedDataFlags : uint32 { None = 0 , Required = 1 << 0 , Optional = 1 << 1 , MemoryMapped = 1 << 2 }
Flags that modify how this derived data is saved and how it may be loaded.
enum class EDerivedDataIoStatus : uint8 { Ok , Error , Canceled , Unknown }
Status of an operation on a Derived Data Reference.
enum class EIoFilePropertyFlags : uint8 { None = 0 , Encrypted = (1 << 0) , Signed = (1 << 1) }
Specifies whether a file contains encrypted or signed I/O store chunks.
enum class EIoFileReadPriority : uint8 {
Min , Low , Medium , High ,
Max , Count
}
Priority levels when reading encoded I/O store chunks from file.
enum ELoadConfigPropagationFlags {
LCPF_None = 0x0 , LCPF_ReadParentSections = 0x1 , LCPF_PropagateToChildDefaultObjects = 0x2 , LCPF_PropagateToInstances = 0x4 ,
LCPF_ReloadingConfigData = 0x8 , LCPF_PersistentFlags = LCPF_ReloadingConfigData
}
Controls how calls to LoadConfig() should be propagated.
enum class EPayloadAccessMode : uint8 { Local = 0 , Referenced , Virtualized }
Lists the various methods of payload access that the trailer supports.
enum class EPayloadFilter { CanVirtualize }
Used to filter requests based on how a payload can function.
enum class EPayloadFlags : uint16 { None = 0 }
Flags that can be set on payloads in a payload trailer.
enum class EPayloadStatus { NotFound = 0 , StoredLocally , StoredAsReference , StoredVirtualized }
Used to show the status of a payload.
enum class EPayloadStorageType : uint8 { Any , Local , Referenced , Virtualized }
Trailer Format The FPackageTrailer is a container that will commonly be appended to the end of a package file.
enum class EPrintObjectFlag : uint32 { None = 0 , Verbose = (1 << 0) , PropertyInitializationState = (1 << 1) , FullArchetypeChain = (1 << 2) }
Flags for specifying optional behaviors.
Functions
template<typename ValueType UE_REQUIRES>
void CallSerializeForLog (FCbWriter &Writer, ValueType &&Value)
Wrapper to support calling SerializeForLog with ADL from within an overload of SerializeForLog.
void DispatchDynamicLogRecord (const FLogRecord &Record)
Advanced function to dispatch a log record to active output devices.
ENUM_CLASS_FLAGS (EDerivedDataFlags)
ENUM_CLASS_FLAGS (EIoFilePropertyFlags)
ENUM_CLASS_FLAGS (EPayloadFlags)
ENUM_CLASS_FLAGS (EPrintObjectFlag)
bool FindPayloadsInPackageFile (const FPackagePath &PackagePath, EPayloadStorageType Filter, TArray< FIoHash > &OutPayloadIds)
Used to find the identifiers of the payload in a given package.
FProperty * FindPropertyByNameAndTypeName (const UStruct *Struct, FName Name, FPropertyTypeName TypeName)
Find a property in Struct that matches both the name and the type.
void FormatLogTo (FUtf8StringBuilderBase &Out, const FLogTemplate *Template, const FCbFieldViewIterator &Fields)
void FormatLogTo (FWideStringBuilderBase &Out, const FLogTemplate *Template, const FCbFieldViewIterator &Fields)
FText FormatLogToText (const FLogTemplate *Template, const FCbFieldViewIterator &Fields)
EInternalObjectFlags GetAsyncLoadingInternalFlagsExclusion ()
bool GetIsEditorLoadingPackage ()
int32 GetMultiprocessId ()
If multiple copies of the process are running and communicating together, the director process has MultiprocessId 0 and the worker processes have MultiprocessId > 0.
int32 GetPlayInEditorID ()
template<typename HashType, typename CharType, int32 Len>
UE_CONSTEVAL HashType HashStringFNV1a (const CharType(&StringLiteral)[Len])
template<typename HashType, typename CharType>
constexpr HashType HashStringFNV1a (TStringView< CharType > String)
Implements a constexpr usable version of FNV1a for strings.
template<typename CharType, int32 Len>
UE_CONSTEVAL uint32 HashStringFNV1a32 (const CharType(&StringLiteral)[Len])
template<typename CharType>
constexpr uint32 HashStringFNV1a32 (TStringView< CharType > String)
template<typename CharType, int32 Len>
UE_CONSTEVAL uint64 HashStringFNV1a64 (const CharType(&StringLiteral)[Len])
template<typename CharType>
constexpr uint64 HashStringFNV1a64 (TStringView< CharType > String)
static EIoFileReadPriority IoFileReadPriorityFromDispatcherPriority (int32 Priority)
Narrows an I/O dispatcher priorty to file read priority.
template<typename... Args>
bool IsIoErrorAnyOf (EIoErrorCode ErrorCode, Args... Expected)
bool IsSavingPackage (UObject *InOuter=nullptr)
Return if the passed in package is currently saving, or if any packages are saving if no parameter is passed.
bool IsUsingZenPakFileStreaming ()
TUniquePtr< IPlatformIoDispatcher > MakeGenericPlatformIoDispatcher (FPlatformIoDispatcherCreateParams &&Params)
template<typename CharType>
TStringBuilderBase< CharType > & operator<< (TStringBuilderBase< CharType > &Builder, EPayloadAccessMode Mode)
Allow EPayloadAccessMode to work with string builder.
UE_INTERNAL void PrintClassDefaultObject (UClass *Class, EPrintObjectFlag Flags=EPrintObjectFlag::None, FOutputDevice *OutputDevice=nullptr)
Outputs a class' Class Default Object.
UE_INTERNAL void PrintObjectArchetype (UObject *Object, EPrintObjectFlag Flags=EPrintObjectFlag::None, FOutputDevice *OutputDevice=nullptr)
Outputs an object's archetype.
UE_INTERNAL void PrintObjectIDO (UObject *Object, EPrintObjectFlag Flags=EPrintObjectFlag::None, FOutputDevice *OutputDevice=nullptr)
Outputs an object's IDO (Instance Data Object).
UE_INTERNAL void PrintObjectProperties (UObject *Object, EPrintObjectFlag Flags=EPrintObjectFlag::None, FOutputDevice *OutputDevice=nullptr)
Lists the property values of an object.
UE_INTERNAL void PrintObjectsInOuter (UObject *Object, EPrintObjectFlag Flags=EPrintObjectFlag::None, FOutputDevice *OutputDevice=nullptr)
Lists all objects under a specified parent.
UE_INTERNAL void PrintObjectsWithName (const TCHAR *ObjectName, EPrintObjectFlag Flags=EPrintObjectFlag::None, FOutputDevice *OutputDevice=nullptr)
Lists all objects with a given name.
UE_INTERNAL void PrintStructProperties (UStruct *Struct, void *StructData, EPrintObjectFlag Flags=EPrintObjectFlag::None, FOutputDevice *OutputDevice=nullptr)
Lists the properties of a UStruct instance.
void SendClearOverriddenPropertyEvent (TNotNull< UObject * > Object, const FPropertyChangedEvent &PropertyEvent, const FEditPropertyChain &PropertyChain)
void SendClearOverriddenPropertyEvent (TNotNull< UObject * > Object, const FPropertyVisitorPath &PropertyPath)
Helper method that calls the pre and post change notification responsible for clearing a property override.
void SendClearOverridesEvent (TNotNull< UObject * > Object)
Helper method that calls the pre and post change notification responsible for clearing the overrides of an object.
void SendOverrideObjectEvent (TNotNull< UObject * > Object)
Helper method that calls the pre and post change notification responsible for overriding an object.
void SendOverridePropertyEvent (TNotNull< UObject * > Object, const FPropertyChangedEvent &PropertyEvent, const FEditPropertyChain &PropertyChain)
void SendOverridePropertyEvent (TNotNull< UObject * > Object, const FPropertyVisitorPath &PropertyPath, EPropertyChangeType::Type ChangeType=EPropertyChangeType::Unspecified)
Helper method that calls the pre and post change notification responsible for overriding an object property.
void SendPostOverridePropertyEvent (TNotNull< UObject * > Object, const FPropertyChangedEvent &PropertyEvent, const FEditPropertyChain &PropertyChain)
void SendPostOverridePropertyEvent (TNotNull< UObject * > Object, const FPropertyVisitorPath &PropertyPath, EPropertyChangeType::Type ChangeType=EPropertyChangeType::Unspecified)
Helper method that calls the post-change notification responsible for overriding an object property.
void SendPreOverridePropertyEvent (TNotNull< UObject * > Object, const FEditPropertyChain &PropertyChain)
void SendPreOverridePropertyEvent (TNotNull< UObject * > Object, const FPropertyVisitorPath &PropertyPath)
Helper method that calls the pre-change notification responsible for overriding an object property.
template<typename ValueType UE_REQUIRES>
void SerializeForLog (FCbWriter &Writer, ValueType &&Value)
Serializes the value to be used in a log message.
void SetIsEditorLoadingPackage (bool InValue)
void SetPlayInEditorID (int32 InPlayInEditorID)
FPropertyValueInContainer TryResolvePropertyPath (const FPropertyPathName &Path, UObject *Object)
Try to resolve the property path to a property value within the object.
template<typename T, typename AllocatorType = FMemory>
class UE_DEPRECATED (5.3, "This concurrent queue was deprecated because it uses spin-waiting that can cause priority inversion and subsequently deadlocks on some platforms. Please use TConsumeAllMpmcQueue.") TDepletableMpmcQueue final
WARNING: this queue can cause priority inversion or a livelock due to spinlocking in Deplete() method, though we haven't seen this happened in practice.
UE_DEPRECATED (5.6, "Use FInlineLogTemplate or FUniqueLogTemplate.") inline FLogTemplate *CreateLogTemplate(const TCHAR *Format
void VisitLogContext (TFunctionRef< void(const FCbField &)> Visitor)
Advanced function to visit the log contexts for the calling thread.
Variables
constexpr struct UE::FAcquireLock AcquireLock
constexpr struct UE::FDeferLock DeferLock
UENUM() enum class EAudioFaderCurve FAudioComponentParam has been deprecated
TUniquePtr< IPlatformIoDispatcher > GPlatformIoDispatcher
const FName NAME_Key
const FName NAME_Value
const FLogTemplateOptions & Options
template<typename CharType>
const TSharedString< CharType > TSharedString< CharType >::Empty
Detailed Description
Utility functions for applying transformations to meshes.
Code for reading .shk files and using that information to map shader hashes back to human-readable identifies.
~ Generic multi-channel blending support for sequencer.
Implementation of custom blend logic should be as follows (using doubles as an example).
This object contains a map of actual channel overrides, where each override is a channel identifier and a channel container.
Utility functions for manipulating DynamicMesh attribute sets.
Utility functions for constructing various PointSetAdapter and MeshAdapter instances from dynamic meshes.
Utility functions and console commands that print UObject state information.
Configuration class for FNetFaultState state escalation configuration.
List of (advanced) texture source encodings, matching the list in ColorManagementDefines.h.
A vector in 2-D space composed of components (X, Y) with floating point precision.
Implements a basic sphere.
3D Ray represented by Origin and (normalized) Direction
Structure for three dimensional planes.
4x4 matrix of floating point values.
Dual quaternion class.
Structure for capsules.
Structure for a combined axis aligned bounding box and bounding sphere with the same origin.
Implements a rectangular 2D Box.
Morphology operation types.
CSG operation types.
Remeshing modes.
UModelingSceneSnappingManager is an implementation of snapping suitable for use in Modeling Tools/Gizmos (and potentially other places).
UModelingObjectsCreationAPI is a base interface for functions that can be used to create various types of objects from Modeling Tools, or other sources.
The "type" is very generic here - "Mesh", "Texture", etc - because this API is meant to provide an abstraction for Tools to emit different types of objects in different situations. For example an Tool might emit StaticMesh Asset/Actors in-Editor, but ProceduralMeshComponents at Runtime.
The creation inputs are specified via the structs above (eg FCreateMeshObjectParams, FCreateTextureObjectParams), which are very extensive, kitchen-sink sort of structs. Generally "New Mesh Object" creation behavior will be very complex and so this API is really just a way to route the data, and very few guarantees can be made about any specific implementation.
The assumed (but not really required) usage of instances of this type are that they will be registered with an InteractiveToolsContext's ContextObjectStore, and then fetched from there by Tools/Algorithms/etc that need to use these capabilities can use the UE::Modeling::CreateXObject() helper functions below. However the interface does not have any dependencies on this usage model.
See UEditorModelingObjectsCreationAPI for an example implementation suitable for in-Editor use.
Currently Supports:
snap to position/rotation grid
snap to mesh vertex position
snap to mesh edge position
Snapping to mesh vertex/edge positions currently works for Volume (BrushComponent), StaticMeshComponent, and DynamicMeshComponent.
Currently the StaticMesh vertex/edge snapping is dependent on the Physics system, and may fail or return nonsense results in some cases, due to the physics complex-collision mesh deviating from the source-model mesh.
Smoothing modes
(28 bytes).
A capsule consists of two sphere connected by a cylinder.
Note that, like with FTransform, Matrix-Matrix multiplication is applied such that C = A * B will yield a transform C that logically first applies A then B, so (A*B).TransformPosition(Pt) == B.TransformPosition(A.TransformPosition(Pt))
Matrix elements are accessed with M[RowIndex][ColumnIndex].
Stores the coeffecients as Xx+Yy+Zz=W. Note that this is different from many other Plane classes that use Xx+Yy+Zz+W=0.
List of (source) texture color spaces, matching the list in ColorManagementDefines.h. List of chromatic adaptation methods, matching the list in ColorManagementDefines.h.
Can be used in a debugger as well.
Specializing TBlendableTokenTraits for a particular input data type causes WorkingDataType to be used during the blending operation. Where WorkingDataType belongs to a namespace, ADL will be employed to discover any relevant overloads for BlendValue that match the necessary types. This allows blending of any arbitrary type into the WorkingDataType.
namespace MovieScene { Define a custom namespaced type that will be used to calculate blends between doubles struct FBlendableDouble { FBlendableDouble() : AbsoluteTotal(0.0), AdditiveTotal(0.0) {}
double AbsoluteTotal; double AdditiveTotal;
TOptional<float> TotalWeight;
double Resolve(TMovieSceneInitialValueStore<int32>& InitialValueStore) { if (TotalWeight.IsSet()) { if (TotalWeight.GetValue() == 0.f) { AbsoluteTotal = InitialValueStore.GetInitialValue(); } else { AbsoluteTotal /= TotalWeight.GetValue(); } }
return AbsoluteTotal + AdditiveTotal; } };
void BlendValue(FBlendableDouble& OutBlend, double InValue, float Weight, EMovieSceneBlendType BlendType, TMovieSceneInitialValueStore<double>& InitialValueStore) { if (BlendType == EMovieSceneBlendType::Absolute || BlendType == EMovieSceneBlendType::Relative) { if (BlendType == EMovieSceneBlendType::Relative) { OutBlend.AbsoluteTotal += (InitialValueStore.GetInitialValue() + InValue) * Weight; } else { OutBlend.AbsoluteTotal += InValue * Weight; }
OutBlend.TotalWeight = OutBlend.TotalWeight.Get(0.f) + Weight; } else if (BlendType == EMovieSceneBlendType::Additive) { OutBlend.AdditiveTotal += InValue * Weight; } } } template<> struct TBlendableTokenTraits<double> { typedef UE::MovieScene::FBlendableDouble WorkingDataType; };
Works in conjunction with TMovieSceneBlendingActuator<Type> where Type has been set up with the correct traits to allow multi-channel blending: Example:
// My struct contains 3 floats, so is represented as a TMultiChannelValue<float, 3> struct FMyStruct { float X, Y, Z; ... };
namespace MovieScene { // Marshall my struct into a multi-channel value inline void MultiChannelFromData(FMyStruct In, TMultiChannelValue<float, 3>& Out) { Out = { In.X, In.Y, In.Z }; } // Marshall my struct out of a static float array inline void ResolveChannelsToData(float (&Channels)[3], FMyStruct& Out) { Out = FMyStruct(Channels[0], Channels[1], Channels[2]); } }
// Access a unique runtime type identifier for FMyStruct. Implemented in cpp to ensure there is only ever 1. This is required to support actuators operating on FMyStructs. template<> MYMODULE_API FMovieSceneAnimTypeID GetBlendingDataType<FMyStruct>();
// Inform the blending code to use a maksed blendable of 3 floats for my struct template<> struct TBlendableTokenTraits<FMyStruct> { typedef UE::MovieScene::TMaskedBlendable<float, 3> WorkingDataType; };
// To inject a blendable token into the accumulator for an FMyStruct: UE::MovieScene::TMultiChannelValue<float, 3> AnimatedData;
// Set the X and Z channels AnimatedData.Set(0, 100.f); AnimatedData.Set(2, 250.f);
// Ensure the accumulator knows how to apply an FMyStruct (usually this will be on a property, and happen through EnsureActuator<>) FMovieSceneBlendingActuatorID ActuatorTypeID = FMyActuatorType::GetActuatorTypeID(); if (!ExecutionTokens.GetAccumulator().FindActuator<FMyStruct>(ActuatorTypeID)) { ExecutionTokens.GetAccumulator().DefineActuator(ActuatorTypeID, MakeShared<FMyActuatorType>()); }
// Add the blendable to the accumulator float Weight = EvaluateEasing(Context.GetTime()); // Constructing a TBlendableToken from any type other than TMultiChannelValue<float, 3> requires a supporting BlendValue function ExecutionTokens.BlendToken(ActuatorTypeID, TBlendableToken<FMyStruct>(AnimatedData, EMovieSceneBlendType::Absolute, Weight));
Typedef Documentation
FAnsiSharedString
using UE::FAnsiSharedString = TSharedString<ANSICHAR>
Definition at line 54 of file StringFwd.h.
FDerivedDataIoComplete
using UE::FDerivedDataIoComplete = TUniqueFunction<void ()>
Definition at line 351 of file DerivedData.h.
FEventCount
using UE::FEventCount = TEventCount<uint32>
Definition at line 174 of file EventCount.h.
FEventCountToken
using UE::FEventCountToken = TEventCountToken<uint32>
Definition at line 175 of file EventCount.h.
FInlineLogTemplate
using UE::FInlineLogTemplate = TLogTemplate<Logging::Private::FInlineLogTemplateStorage>
A log template that stores its data inline.
Best choice for a stack-based temporary.
Definition at line 190 of file StructuredLogFormat.h.
FIoEncodedBlockRequestAllocator
using UE::FIoEncodedBlockRequestAllocator = TSingleThreadedSlabAllocator<FIoEncodedBlockRequest>
Definition at line 121 of file PlatformIoDispatcherBase.h.
FIoEncodedBlockRequestList
using UE::FIoEncodedBlockRequestList = TIntrusiveList<FIoEncodedBlockRequest>
Definition at line 122 of file PlatformIoDispatcherBase.h.
FIoFileBlockLinkAllocator
using UE::FIoFileBlockLinkAllocator = TSingleThreadedSlabAllocator<FIoFileBlockLink>
Definition at line 133 of file PlatformIoDispatcherBase.h.
FIoFileBlockRequestAllocator
using UE::FIoFileBlockRequestAllocator = TSingleThreadedSlabAllocator<FIoFileBlockRequest>
Definition at line 244 of file PlatformIoDispatcherBase.h.
FIoFileBlockRequestList
using UE::FIoFileBlockRequestList = TIntrusiveList<FIoFileBlockRequest>
Definition at line 245 of file PlatformIoDispatcherBase.h.
FIoFileReadRequestCompleted
using UE::FIoFileReadRequestCompleted = TUniqueFunction<void(FIoFileReadResult&&)>
Definition at line 222 of file PlatformIoDispatcher.h.
FIoPlatformReadRequestAllocator
using UE::FIoPlatformReadRequestAllocator = TSingleThreadedSlabAllocator<FIoPlatformReadRequest>
Definition at line 209 of file PlatformIoDispatcherBase.h.
FIoPlatformReadRequestList
using UE::FIoPlatformReadRequestList = TIntrusiveList<FIoPlatformReadRequest>
Definition at line 210 of file PlatformIoDispatcherBase.h.
FPlatformIoDispatcherFactory
using UE::FPlatformIoDispatcherFactory = FGenericPlatformIoDispatcherFactory
Definition at line 16 of file GenericPlatformIoDispatcher.h.
FPlatformRecursiveMutex
typedef FWindowsRecursiveMutex UE::FPlatformRecursiveMutex = FPThreadsRecursiveMutex
Definition at line 12 of file AndroidPlatformMutex.h.
FPlatformSharedMutex
typedef FWindowsSharedMutex UE::FPlatformSharedMutex = FPThreadsSharedMutex
Definition at line 13 of file AndroidPlatformMutex.h.
FPlatformSystemWideMutex
typedef FWindowsSystemWideMutex UE::FPlatformSystemWideMutex = FPlatformSystemWideMutexNotImplemented
Definition at line 14 of file AndroidPlatformMutex.h.
FRWSpinLock
using UE::FRWSpinLock = TRWSpinLock<uint32>
Definition at line 79 of file RWSpinLock.h.
FSharedString
using UE::FSharedString = TSharedString<TCHAR>
Definition at line 53 of file StringFwd.h.
FTempArray
template<typename T, SIZE_T Size = 8> using UE::FTempArray = TArray<T, TInlineAllocator<Size>>
Definition at line 28 of file PlatformIoDispatcherBase.h.
FTransactionallySafeMutex
using UE::FTransactionallySafeMutex = FMutex
Definition at line 275 of file TransactionallySafeMutex.h.
FTransactionallySafeRecursiveMutex
using UE::FTransactionallySafeRecursiveMutex = ::UE::FRecursiveMutex
Definition at line 18 of file TransactionallySafeRecursiveMutex.h.
FUniqueLogTemplate
using UE::FUniqueLogTemplate = TLogTemplate<Logging::Private::FUniqueLogTemplateStorage>
A log template that stores its data on the heap.
A reasonable default when for non-temporary templates.
Definition at line 193 of file StructuredLogFormat.h.
FUtf8SharedString
using UE::FUtf8SharedString = TSharedString<UTF8CHAR>
Definition at line 56 of file StringFwd.h.
FWideSharedString
using UE::FWideSharedString = TSharedString<WIDECHAR>
Definition at line 55 of file StringFwd.h.
Enumeration Type Documentation
EConsumeAllMpmcQueueResult
enum class UE::EConsumeAllMpmcQueueResult strong
Enumerator
HadItems
WasEmpty
Definition at line 14 of file ConsumeAllMpmcQueue.h.
EDerivedDataFlags
enum class UE::EDerivedDataFlags : uint32 strong
Flags that modify how this derived data is saved and how it may be loaded.
Enumerator
None
Required
Stage the referenced data with required content.
May combine with Optional to stage into both locations.
Optional
Stage the referenced data with optional content.
MemoryMapped
Stage the referenced data with alignment padding to allow memory-mapped access on supported platforms.
Definition at line 31 of file DerivedData.h.
EDerivedDataIoStatus
enum class UE::EDerivedDataIoStatus : uint8 strong
Status of an operation on a Derived Data Reference.
Enumerator
Ok
The operation completed successfully.
Error
The operation completed unsuccessfully.
Canceled
The operation was canceled before it completed.
Unknown
The operation has not completed or is otherwise in an unknown state.
Definition at line 201 of file DerivedData.h.
EIoFilePropertyFlags
enum class UE::EIoFilePropertyFlags : uint8 strong
Specifies whether a file contains encrypted or signed I/O store chunks.
Enumerator
None
Encrypted
Signed
Definition at line 81 of file PlatformIoDispatcher.h.
EIoFileReadPriority
enum class UE::EIoFileReadPriority : uint8 strong
Priority levels when reading encoded I/O store chunks from file.
Enumerator
Min
Low
Medium
High
Max
Count
Definition at line 25 of file PlatformIoDispatcher.h.
ELoadConfigPropagationFlags
enum UE::ELoadConfigPropagationFlags
Controls how calls to LoadConfig() should be propagated.
Enumerator
LCPF_None
LCPF_ReadParentSections
Indicates that the object should read ini values from each section up its class's hierarchy chain; Useful when calling LoadConfig on an object after it has already been initialized against its archetype.
LCPF_PropagateToChildDefaultObjects
Indicates that LoadConfig() should be also be called on the class default objects for all children of the original class.
LCPF_PropagateToInstances
Indicates that LoadConfig() should be called on all instances of the original class.
LCPF_ReloadingConfigData
Indicates that this object is reloading its config data.
LCPF_PersistentFlags
All flags that should be persisted to propagated recursive calls.
Definition at line 2231 of file ObjectMacros.h.
EPayloadAccessMode
enum class UE::EPayloadAccessMode : uint8 strong
Lists the various methods of payload access that the trailer supports.
Enumerator
Local
The payload is stored in the Payload Data segment of the trailer and the offsets in FLookupTableEntry will be relative to the start of this segment.
Referenced
The payload is stored in another package trailer (most likely the workspace domain package file) and the offsets in FLookupTableEntry are absolute offsets in that external file.
Virtualized
The payload is virtualized and needs to be accessed via IVirtualizationSystem.
Definition at line 108 of file PackageTrailer.h.
EPayloadFilter
enum class UE::EPayloadFilter strong
Used to filter requests based on how a payload can function.
Enumerator
CanVirtualize
All payloads that are stored locally and do not have virtualization disabled.
Definition at line 86 of file PackageTrailer.h.
EPayloadFlags
enum class UE::EPayloadFlags : uint16 strong
Flags that can be set on payloads in a payload trailer.
Enumerator
None
No flags are set.
Definition at line 119 of file PackageTrailer.h.
EPayloadStatus
enum class UE::EPayloadStatus strong
Used to show the status of a payload.
Enumerator
NotFound
The payload is not registered in the package trailer.
StoredLocally
The payload is stored locally inside the current package trailer where ever that is written to disk.
StoredAsReference
The payload is stored in the workspace domain trailer.
StoredVirtualized
The payload is virtualized and needs to be accessed via the IVirtualizationSystem.
Definition at line 95 of file PackageTrailer.h.
EPayloadStorageType
enum class UE::EPayloadStorageType : uint8 strong
Trailer Format The FPackageTrailer is a container that will commonly be appended to the end of a package file.
The main purpose of the trailer is to store the bulkdata payloads contained by the package until they are virtualized or moved to an additional storage location.
By storing the payloads in a data format adjacent to the rest of the package we can perform the virtualization process without needing to re-save the package itself which in turn should allow for external tools to be able to perform the virtualization process themselves rather than needing to force it through engine code.
The package trailer is intended to an easy format for external code/script to be able to manipulate. To make things clearer we do not serialize containers directly but write out each data structure one at a time so that it should be easy to see how to manipulate the file.
The file is split into three parts:
[Header] The header contains the useful info about the trailer and the payloads in general. @See UE::FLookupTableEntry for details about the look up table's data.
[Payload Data] If the trailer is in the workspace domain package then we will store all non-virtualized payloads here. If the trailer is in the editor domain then there will be no payload data section and the header will be referencing the trailer in the workspace domain instead.
[Footer] The footer allows for us to load the trailer in reverse and replicates the end of package file tag (PACKAGE_FILE_TAG), it should only be used for finding the start of the trailer or validation.
CurrentVersion UE::EPackageTrailerVersion::INITIAL
| [Header] | | Tag | uint64 | Should match FHeader::HeaderTag, used to identify that the data being read is an FPackageTrailer | | Version | uint32 | Version number of the format
See also
UE::EPackageTrailerVersion | | HeaderLength | uint32 | The total size of the header on disk in bytes. | | PayloadsDataLength | uint64 | The total size of the payload data on disk in bytes | | NumPayloads | int32 | The number of payloads in LookupTableArray | | LookupTableArray | FLookupTableEntry | An array of FLookupTableEntry
UE::Private::FLookupTableEntry | |____________________________________________________________________________________________________________________________________________| | [Payload Data] | | Array | FCompressedBuffer | A binary blob containing all of the payloads. Individual payloads can be found via | | the LookupTableArray found in the header. | |____________________________________________________________________________________________________________________________________________| | [Footer] | | Tag | uint64 | Should match FFooter::FooterTag, used to identify that the data being read is an FPackageTrailer | | TrailerLength | uint64 | The total size of the trailer on disk in bytes. Can be used to find the start of the trailer when | | reading backwards. | | PackageTag | uint32 | The end of package tag, PACKAGE_FILE_TAG. This is used to validate that a package file on disk is | | not corrupt. By ending the trailer with this tag we allow that validation code to work. | |____________________________________________________________________________________________________________________________________________| Used to filter requests based on how a payload is stored
Enumerator
Any
All payload regardless of type.
Local
All payloads stored locally in the package trailer.
Referenced
All payloads that are a reference to payloads stored in the workspace domain trailer.
Virtualized
All payloads stored in a virtualized backend.
Definition at line 73 of file PackageTrailer.h.
EPrintObjectFlag
enum class UE::EPrintObjectFlag : uint32 strong
Flags for specifying optional behaviors.
Enumerator
None
No optional behaviors.
Verbose
Include verbose information.
PropertyInitializationState
Include the initialization state for properties (only relevant for functions that print properties).
FullArchetypeChain
Show the full archetype hierarchy (only relevant for functions that print archetypes).
Definition at line 26 of file PrintObjectUtils.h.
Function Documentation
CallSerializeForLog()
template<typename ValueType UE_REQUIRES> void UE::CallSerializeForLog (FCbWriter & Writer, ValueType && Value) inline
Wrapper to support calling SerializeForLog with ADL from within an overload of SerializeForLog.
Definition at line 306 of file StructuredLog.h.
References SerializeForLog(), and Value.
Referenced by SerializeForLog().
DispatchDynamicLogRecord()
void UE::DispatchDynamicLogRecord (const FLogRecord & Record)
Advanced function to dispatch a log record to active output devices.
Always use UE_LOGFMT or its variants when possible. Dynamic dispatch bypasses many optimizations provided by the macros. Anything pointed to by the record MUST remain valid until threaded logs have been flushed. Filtering by category or verbosity is the responsibility of the caller. Active log contexts will not be added to this record. If they are needed that is the responsibility of the caller.
References Record, and UE_API.
ENUM_CLASS_FLAGS() [1/4]
UE::ENUM_CLASS_FLAGS (EDerivedDataFlags)
ENUM_CLASS_FLAGS() [2/4]
UE::ENUM_CLASS_FLAGS (EIoFilePropertyFlags)
ENUM_CLASS_FLAGS() [3/4]
UE::ENUM_CLASS_FLAGS (EPayloadFlags)
ENUM_CLASS_FLAGS() [4/4]
UE::ENUM_CLASS_FLAGS (EPrintObjectFlag)
FindPayloadsInPackageFile()
bool UE::FindPayloadsInPackageFile (const FPackagePath & PackagePath, EPayloadStorageType Filter, TArray< FIoHash > & OutPayloadIds) nodiscard
Used to find the identifiers of the payload in a given package.
Note that this will return the payloads included in the package on disk and will not take into account any edits to the package if they are in memory and unsaved.
Parameters
PackagePath The package to look in.
Filter What sort of payloads should be returned.
See also
EPayloadType
Parameters
OutPayloadIds This array will be filled with the FPayloadId values found in the package that passed the filter. Note that existing content in the array will be preserved. It is up to the caller to empty it.
Returns
True if the package was parsed successfully (although it might not have contained any payloads) and false if opening or parsing the package file failed.
References Filter, Local, PackagePath, Referenced, and Virtualized.
FindPropertyByNameAndTypeName()
FProperty * UE::FindPropertyByNameAndTypeName (const UStruct * Struct, FName Name, FPropertyTypeName TypeName)
Find a property in Struct that matches both the name and the type.
Type matching uses FProperty::CanSerializeFromTypeName.
Returns
A matching property if found, otherwise null.
References Name, Struct, and UE_API.
FormatLogTo() [1/2]
void UE::FormatLogTo (FUtf8StringBuilderBase & Out, const FLogTemplate * Template, const FCbFieldViewIterator & Fields)
References UE_API.
Referenced by UE::TLogTemplate< Logging::Private::FInlineLogTemplateStorage >::FormatTo(), and UE::TLogTemplate< Logging::Private::FInlineLogTemplateStorage >::FormatTo().
FormatLogTo() [2/2]
void UE::FormatLogTo (FWideStringBuilderBase & Out, const FLogTemplate * Template, const FCbFieldViewIterator & Fields)
References UE_API.
FormatLogToText()
FText UE::FormatLogToText (const FLogTemplate * Template, const FCbFieldViewIterator & Fields)
References UE_API.
Referenced by UE::TLogTemplate< Logging::Private::FInlineLogTemplateStorage >::FormatToText().
GetAsyncLoadingInternalFlagsExclusion()
EInternalObjectFlags UE::GetAsyncLoadingInternalFlagsExclusion ()
Referenced by GetObjectIteratorDefaultInternalExclusionFlags().
GetIsEditorLoadingPackage()
bool UE::GetIsEditorLoadingPackage ()
References GetIsEditorLoadingPackage().
Referenced by GetIsEditorLoadingPackage().
GetMultiprocessId()
int32 UE::GetMultiprocessId ()
If multiple copies of the process are running and communicating together, the director process has MultiprocessId 0 and the worker processes have MultiprocessId > 0.
When only a single process is running, GetMultiprocessId returns 0. Based on commandline. Primary example is cookworkers in multiprocess cook. Systems that need to write a separate file per running process should use this id as part of their file descriptor.
GetPlayInEditorID()
int32 UE::GetPlayInEditorID ()
References GetPlayInEditorID().
Referenced by FUniqueObjectGuid::FixupForPIE(), FSoftObjectPtr::Get(), and GetPlayInEditorID().
HashStringFNV1a() [1/2]
template<typename HashType, typename CharType, int32 Len> UE_CONSTEVAL HashType UE::HashStringFNV1a (const CharType(&) StringLiteral[Len])
Definition at line 70 of file Fnv.h.
References HashStringFNV1a(), MakeStringView(), and UE_CONSTEVAL.
HashStringFNV1a() [2/2]
template<typename HashType, typename CharType> HashType UE::HashStringFNV1a (TStringView< CharType > String) constexpr
Implements a constexpr usable version of FNV1a for strings.
Note: This implementation is 'stable' such that the same string of different character widths will hash to the same value (eg. HashStringFNV1a("Hello") == HashStringFNV1a(L"Hello")). This behavior is appropriate here as we're operating on strings specifically rather than raw buffers and we want consistent hashes between different platforms.
Definition at line 19 of file Fnv.h.
Referenced by HashStringFNV1a(), HashStringFNV1a32(), HashStringFNV1a32(), HashStringFNV1a64(), HashStringFNV1a64(), UE::AnimNext::FTraitInterfaceUID::MakeUID(), and UE::AnimNext::FTraitUID::MakeUID().
HashStringFNV1a32() [1/2]
template<typename CharType, int32 Len> UE_CONSTEVAL uint32 UE::HashStringFNV1a32 (const CharType(&) StringLiteral[Len])
Definition at line 83 of file Fnv.h.
References HashStringFNV1a(), and UE_CONSTEVAL.
HashStringFNV1a32() [2/2]
template<typename CharType> uint32 UE::HashStringFNV1a32 (TStringView< CharType > String) constexpr
Definition at line 77 of file Fnv.h.
References HashStringFNV1a().
Referenced by UE::AnimNext::FConstExprUID::MakeFromString().
HashStringFNV1a64() [1/2]
template<typename CharType, int32 Len> UE_CONSTEVAL uint64 UE::HashStringFNV1a64 (const CharType(&) StringLiteral[Len])
Definition at line 96 of file Fnv.h.
References HashStringFNV1a(), and UE_CONSTEVAL.
HashStringFNV1a64() [2/2]
template<typename CharType> uint64 UE::HashStringFNV1a64 (TStringView< CharType > String) constexpr
Definition at line 90 of file Fnv.h.
References HashStringFNV1a().
IoFileReadPriorityFromDispatcherPriority()
EIoFileReadPriority UE::IoFileReadPriorityFromDispatcherPriority (int32 Priority) inline static
Narrows an I/O dispatcher priorty to file read priority.
Definition at line 36 of file PlatformIoDispatcher.h.
References High, IoDispatcherPriority_High, IoDispatcherPriority_Low, IoDispatcherPriority_Medium, Low, Max, Medium, and Min.
IsIoErrorAnyOf()
template<typename... Args> bool UE::IsIoErrorAnyOf (EIoErrorCode ErrorCode, Args... Expected)
Definition at line 22 of file PlatformIoDispatcherBase.cpp.
Referenced by UE::FPlatformIoDispatcherBase::ProcessCompletedFileBlock().
IsSavingPackage()
bool UE::IsSavingPackage (UObject * InOuter = nullptr)
Return if the passed in package is currently saving, or if any packages are saving if no parameter is passed.
Parameters
InOuter The object which we want to check if its package is saving
Returns
true if the package is saving, or if any packages are saving if no parameter is passed in.
References InOuter.
IsUsingZenPakFileStreaming()
bool UE::IsUsingZenPakFileStreaming ()
MakeGenericPlatformIoDispatcher()
TUniquePtr< IPlatformIoDispatcher > UE::MakeGenericPlatformIoDispatcher (FPlatformIoDispatcherCreateParams && Params)
Definition at line 264 of file GenericPlatformIoDispatcher.cpp.
References MakeUnique(), MoveTemp(), and Params.
Referenced by UE::FPlatformIoDispatcher::Create().
operator<<()
template<typename CharType> TStringBuilderBase< CharType > & UE::operator<< (TStringBuilderBase< CharType > & Builder, EPayloadAccessMode Mode) inline
Allow EPayloadAccessMode to work with string builder.
Definition at line 595 of file PackageTrailer.h.
PrintClassDefaultObject()
UE_INTERNAL void UE::PrintClassDefaultObject (UClass * Class, EPrintObjectFlag Flags = EPrintObjectFlag::None, FOutputDevice * OutputDevice = nullptr)
Outputs a class' Class Default Object.
Parameters
Class The class to use.
Flags For specifying optional behaviors.
OutputDevice The output device to print to (can be NULL).
References Class, Flags, None, and UE_INTERNAL.
PrintObjectArchetype()
UE_INTERNAL void UE::PrintObjectArchetype (UObject * Object, EPrintObjectFlag Flags = EPrintObjectFlag::None, FOutputDevice * OutputDevice = nullptr)
Outputs an object's archetype.
Parameters
Object The object to use.
Flags For specifying optional behaviors.
OutputDevice The output device to print to (can be NULL).
References Flags, None, and UE_INTERNAL.
PrintObjectIDO()
UE_INTERNAL void UE::PrintObjectIDO (UObject * Object, EPrintObjectFlag Flags = EPrintObjectFlag::None, FOutputDevice * OutputDevice = nullptr)
Outputs an object's IDO (Instance Data Object).
Parameters
Object The object to use.
Flags For specifying optional behaviors.
OutputDevice The output device to print to (can be NULL).
References Flags, None, and UE_INTERNAL.
PrintObjectProperties()
UE_INTERNAL void UE::PrintObjectProperties (UObject * Object, EPrintObjectFlag Flags = EPrintObjectFlag::None, FOutputDevice * OutputDevice = nullptr)
Lists the property values of an object.
Parameters
Object The object to use.
Flags For specifying optional behaviors.
OutputDevice The output device to print to (can be NULL).
References Flags, None, and UE_INTERNAL.
PrintObjectsInOuter()
UE_INTERNAL void UE::PrintObjectsInOuter (UObject * Object, EPrintObjectFlag Flags = EPrintObjectFlag::None, FOutputDevice * OutputDevice = nullptr)
Lists all objects under a specified parent.
Parameters
Object The outer object to use.
OutputDevice The output device to print to (can be NULL).
References Flags, None, and UE_INTERNAL.
PrintObjectsWithName()
UE_INTERNAL void UE::PrintObjectsWithName (const TCHAR * ObjectName, EPrintObjectFlag Flags = EPrintObjectFlag::None, FOutputDevice * OutputDevice = nullptr)
Lists all objects with a given name.
Parameters
ObjectName The name to search for.
Flags For specifying optional behaviors.
OutputDevice The output device to print to (can be NULL).
References Flags, None, and UE_INTERNAL.
PrintStructProperties()
UE_INTERNAL void UE::PrintStructProperties (UStruct * Struct, void * StructData, EPrintObjectFlag Flags = EPrintObjectFlag::None, FOutputDevice * OutputDevice = nullptr)
Lists the properties of a UStruct instance.
Parameters
Struct The type of the UStruct instance.
StructData The data of the UStruct instance.
Flags For specifying optional behaviors.
OutputDevice The output device to print to (can be NULL).
References Flags, None, Struct, and UE_INTERNAL.
SendClearOverriddenPropertyEvent() [1/2]
void UE::SendClearOverriddenPropertyEvent (TNotNull< UObject * > Object, const FPropertyChangedEvent & PropertyEvent, const FEditPropertyChain & PropertyChain)
SendClearOverriddenPropertyEvent() [2/2]
void UE::SendClearOverriddenPropertyEvent (TNotNull< UObject * > Object, const FPropertyVisitorPath & PropertyPath)
Helper method that calls the pre and post change notification responsible for clearing a property override.
This is the preferred way to clear property overrides because it will notify listeners
Parameters
Object owning the property to clear
PropertyPath to the property to clear from the root of the specified object
Returns
true if the property was successfully cleared.
SendClearOverridesEvent()
void UE::SendClearOverridesEvent (TNotNull< UObject * > Object)
Helper method that calls the pre and post change notification responsible for clearing the overrides of an object.
This is the preferred way to clear overrides because it will notify listeners
Parameters
Object to clear overrides on
SendOverrideObjectEvent()
void UE::SendOverrideObjectEvent (TNotNull< UObject * > Object)
Helper method that calls the pre and post change notification responsible for overriding an object.
This is the preferred way to override because it will notify listeners
Parameters
Object to override all it's properties
SendOverridePropertyEvent() [1/2]
void UE::SendOverridePropertyEvent (TNotNull< UObject * > Object, const FPropertyChangedEvent & PropertyEvent, const FEditPropertyChain & PropertyChain)
SendOverridePropertyEvent() [2/2]
void UE::SendOverridePropertyEvent (TNotNull< UObject * > Object, const FPropertyVisitorPath & PropertyPath, EPropertyChangeType::Type ChangeType = EPropertyChangeType::Unspecified)
Helper method that calls the pre and post change notification responsible for overriding an object property.
This is the preferred way to override properties because it will notify listeners Note: If you're also changing property values (especially if it's in a container) use SendPreOverridePropertyEvent and SendPostOverridePropertyEvent instead!
Parameters
Object owning the property
PropertyPath leading to the property that is about to be overridden
ChangeType of the current operation
References EPropertyChangeType::Unspecified.
SendPostOverridePropertyEvent() [1/2]
void UE::SendPostOverridePropertyEvent (TNotNull< UObject * > Object, const FPropertyChangedEvent & PropertyEvent, const FEditPropertyChain & PropertyChain)
SendPostOverridePropertyEvent() [2/2]
void UE::SendPostOverridePropertyEvent (TNotNull< UObject * > Object, const FPropertyVisitorPath & PropertyPath, EPropertyChangeType::Type ChangeType = EPropertyChangeType::Unspecified)
Helper method that calls the post-change notification responsible for overriding an object property.
This is the preferred way to override properties because it will notify listeners
Parameters
Object owning the property
PropertyPath leading to the property that was overridden
ChangeType of the current operation
References EPropertyChangeType::Unspecified.
SendPreOverridePropertyEvent() [1/2]
void UE::SendPreOverridePropertyEvent (TNotNull< UObject * > Object, const FEditPropertyChain & PropertyChain)
SendPreOverridePropertyEvent() [2/2]
void UE::SendPreOverridePropertyEvent (TNotNull< UObject * > Object, const FPropertyVisitorPath & PropertyPath)
Helper method that calls the pre-change notification responsible for overriding an object property.
This is the preferred way to override properties because it will notify listeners
Parameters
Object owning the property
PropertyPath leading to the property about to be overridden
SerializeForLog()
template<typename ValueType UE_REQUIRES> void UE::SerializeForLog (FCbWriter & Writer, ValueType && Value) inline
Serializes the value to be used in a log message.
Overload this when the log behavior needs to differ from general serialization to compact binary.
There are three ways to perform custom formatting for values that are serialized as an object:
Add a $text field that is a string with the exact text to display.
Add a $format field that is a format string that may reference fields of the object and their sub-objects.
Add a $locformat field that is a localized format string that may reference fields of the object and their sub-objects. The namespace and key must be included in $locns and $lockey string fields. Serialize FText to the writer using SerializeLogFormat().
Arrays and objects without custom formatting are converted to JSON.
Definition at line 290 of file StructuredLog.h.
References Value.
Referenced by CallSerializeForLog(), and UE::Logging::Private::FLogField::Write().
SetIsEditorLoadingPackage()
void UE::SetIsEditorLoadingPackage (bool InValue)
References SetIsEditorLoadingPackage().
Referenced by SetIsEditorLoadingPackage().
SetPlayInEditorID()
void UE::SetPlayInEditorID (int32 InPlayInEditorID)
References SetPlayInEditorID().
Referenced by SetPlayInEditorID().
TryResolvePropertyPath()
FPropertyValueInContainer UE::TryResolvePropertyPath (const FPropertyPathName & Path, UObject * Object)
Try to resolve the property path to a property value within the object.
Parameters
Path The non-empty property path to resolve.
Object The object representing the root of the property path to resolve.
Returns
A valid property value reference if resolved, otherwise an invalid reference.
References Path, and UE_API.
UE_DEPRECATED() [1/2]
template<typename T, typename AllocatorType = FMemory> class UE::UE_DEPRECATED (5. 3, "This concurrent queue was deprecated because it uses spin-waiting that can cause priority inversion and subsequently deadlocks on some platforms. Please use TConsumeAllMpmcQueue.") final
WARNING: this queue can cause priority inversion or a livelock due to spinlocking in Deplete() method, though we haven't seen this happened in practice.
Prefer TConsumeAllMpmcQueue which is equally fast in LIFO mode, and only slightly slower in FIFO mode.
Multi-producer/multi-consumer unbounded concurrent queue that is atomically consumed and is reset to its default empty state. A typical use case is when the consumer doesn't stop until the queue is depleted. Is faster than traditional MPSC and MPMC queues, especially for consumer. Consumes elements in FIFO order.
Takes all items from the queue atomically and then consumes them.
Parameters
Consumer a functor with signature AnyReturnType (T Value)
Definition at line 1 of file DepletableMpmcQueue.h.
References check, DestructItem(), First, Forward(), Last, MoveTemp(), New(), PRAGMA_DISABLE_DEPRECATION_WARNINGS, PRAGMA_ENABLE_DEPRECATION_WARNINGS, UE_DEPRECATED, UE_NONCOPYABLE, and Value.
UE_DEPRECATED() [2/2]
UE::UE_DEPRECATED (5. 6, "Use FInlineLogTemplate or FUniqueLogTemplate.") const
VisitLogContext()
void UE::VisitLogContext (TFunctionRef< void(const FCbField &)> Visitor)
Advanced function to visit the log contexts for the calling thread.
Invokes the visitor once for each context, in order from the oldest context added on this thread to the newest. If there are multiple contexts with the same name, only the newest will be visited.
References UE_API.
Variable Documentation
AcquireLock
struct UE::FAcquireLock UE::AcquireLock
DeferLock
struct UE::FDeferLock UE::DeferLock
deprecated
FLandscapeProxyMaterialOverride is deprecated
Definition at line 133 of file AudioComponent.h.
GPlatformIoDispatcher
TUniquePtr<IPlatformIoDispatcher> UE::GPlatformIoDispatcher
Definition at line 17 of file PlatformIoDispatcher.cpp.
Referenced by UE::FPlatformIoDispatcher::Create(), UE::FPlatformIoDispatcher::Get(), UE::FPlatformIoDispatcher::Initialize(), UE::FPlatformIoDispatcher::Shutdown(), and UE::FPlatformIoDispatcher::TryGet().
NAME_Key
const FName UE::NAME_Key extern
NAME_Value
const FName UE::NAME_Value extern
Options
const FLogTemplateOptions& UE::Options
Initial value:
= {})
{
    return TLogTemplate<Logging::Private::FMemoryLogTemplateStorage>(Format, Options).Detach();
}
UE_DEPRECATED(5.6, "Use FInlineLogTemplate or FUniqueLogTemplate.")
inline FLogTemplate* CreateLogTemplate(const FText& Format, const FLogTemplateOptions& Options = {})
{
    return TLogTemplate<Logging::Private::FMemoryLogTemplateStorage>(Format, Options).Detach();
}
UE_DEPRECATED(5.6, "Use FInlineLogTemplate or FUniqueLogTemplate.")
inline FLogTemplate* CreateLogTemplate(const TCHAR* TextNamespace, const TCHAR* TextKey, const TCHAR* Format, const FLogTemplateOptions& Options = {})
{
    return TLogTemplate<Logging::Private::FMemoryLogTemplateStorage>(TextNamespace, TextKey, Format, Options).Detach();
}
UE_DEPRECATED(5.6, "Use FInlineLogTemplate or FUniqueLogTemplate.")
inline void DestroyLogTemplate(FLogTemplate* Template)
{
    Logging::Private::DestroyLogTemplate(Template);
    Logging::Private::FMemoryLogTemplateStorage::Free(Template);
}
 1 void SerializeLogFormat(FCbWriter& Writer, const FText& Format)
Definition at line 196 of file StructuredLogFormat.h.
Referenced by UE::TLogTemplate< Logging::Private::FInlineLogTemplateStorage >::TLogTemplate(), UE::TLogTemplate< Logging::Private::FInlineLogTemplateStorage >::TLogTemplate(), UE::TLogTemplate< Logging::Private::FInlineLogTemplateStorage >::TLogTemplate(), UE::GC::FWorkBlockifier::Add(), UE::Conversion::BrushComponentToDynamicMesh(), UE::Conversion::BrushToDynamicMesh(), UE::FDerivedDataIoBatch::Cache(), UE::Graph::ConstructTransposeGraph(), UE::Graph::ConvertToGraph(), UE::Graph::ConvertToSingleBufferGraph(), UE::Graph::ConvertToSingleBufferGraph(), UE::Logging::Private::CreateLocalizedLogTemplate(), UE::Logging::Private::CreateLocalizedLogTemplate(), UE::Logging::Private::CreateLogTemplate(), UE::FDerivedDataIoBatch::Exists(), UE::Conversion::GeometryCacheToDynamicMesh(), UE::Transaction::DiffUtil::FDiffableObjectArchetypeCache::GetArchetypeDiffableObject(), UE::Transaction::DiffUtil::GetDiffableObject(), UE::String::ParseLines(), UE::String::ParseLines(), UE::String::ParseLines(), UE::String::ParseTokens(), UE::String::ParseTokens(), UE::String::ParseTokens(), UE::String::ParseTokens(), UE::String::ParseTokens(), UE::String::ParseTokens(), UE::String::ParseTokens(), UE::String::ParseTokens(), UE::String::ParseTokens(), UE::String::ParseTokens(), UE::String::ParseTokens(), UE::String::ParseTokens(), UE::String::ParseTokensMultiple(), UE::String::ParseTokensMultiple(), UE::String::ParseTokensMultiple(), UE::String::ParseTokensMultiple(), UE::String::ParseTokensMultiple(), UE::String::ParseTokensMultiple(), UE::String::ParseTokensMultiple(), UE::String::ParseTokensMultiple(), UE::String::ParseTokensMultiple(), UE::String::ParseTokensMultiple(), UE::String::ParseTokensMultiple(), UE::String::ParseTokensMultiple(), UE::GC::FWorkBlockifier::PopFullBlock(), UE::FDerivedDataIoBatch::Read(), UE::GC::StealWork(), UE::Graph::TryConstructCondensationGraph(), UE::Virtualization::IVirtualizationSystem::TryRehydratePackages(), UE::Virtualization::IVirtualizationSystem::TryVirtualizePackages(), and UE::Conversion::VolumeToDynamicMesh().
TSharedString< CharType >::Empty
template<typename CharType> const TSharedString<CharType> UE::TSharedString< CharType >::Empty inline
Definition at line 113 of file SharedString.h.
Referenced by UE::Geometry::TDynamicVector< Type, BlockSize >::~TDynamicVector(), UE::Geometry::TDynamicVector< Type, BlockSize >::operator=(), UE::Geometry::TDynamicVector< Type, BlockSize >::operator=(), UE::PixelStreaming2::TThreadSafeMap< InKeyType, InValueType, SetAllocator, KeyFuncs >::operator=(), and UE::Geometry::TDynamicVector< Type, BlockSize >::Serialize().