Unreal Engine 5.6 C++ API: Runtime/Engine/Classes/Engine/NetSerialization.h File Reference
NetSerialization.h File Reference
#include "Stats/Stats.h"
#include "UObject/ObjectMacros.h"
#include "UObject/Class.h"
#include "Misc/NetworkVersion.h"
#include "UObject/CoreNet.h"
#include "EngineLogs.h"
#include "Net/Core/Serialization/QuantizedVectorSerialization.h"
#include <type_traits>
#include "NetSerialization.generated.h"
Data Structures
struct TFixedCompressedFloatDetails< MaxValue, NumBits >
struct TStructOpsTypeTraits< FVector_NetQuantize >
FVector_NetQuantize.
struct TStructOpsTypeTraits< FVector_NetQuantize10 >
FVector_NetQuantize10.
struct TStructOpsTypeTraits< FVector_NetQuantize100 >
FVector_NetQuantize100.
struct TStructOpsTypeTraits< FVector_NetQuantizeNormal >
FVector_NetQuantizeNormal.
Namespaces
namespace UE
Utility functions for applying transformations to meshes.
namespace UE::Net
Responsible for creating headers allowing remote factories to spawn replicated actors.
namespace UE::Net::Private
===================== NetSerialize and NetDeltaSerialize customization.
Functions
template<int32 ScaleFactor, int32 MaxBitsPerComponent>
bool UE::Net::Private::LegacyReadPackedVector (FVector3f &Value, FArchive &Ar)
template<typename ValueType>
bool NetSerializeOptionalValue (const bool bIsSaving, FArchive &Ar, ValueType &Value, const ValueType &DefaultValue, class UPackageMap *PackageMap)
Helper to optionally serialize a value (using the NetSerialize function).
template<int32 MaxValue, uint32 NumBits, typename T UE_REQUIRES>
bool ReadFixedCompressedFloat (T &Value, FArchive &Ar)
template<int32 ScaleFactor, int32 MaxBitsPerComponent>
bool ReadPackedVector (FVector3d &Value, FArchive &Ar)
template<int32 ScaleFactor, int32 MaxBitsPerComponent>
bool ReadPackedVector (FVector3f &Value, FArchive &Ar)
template<int32 MaxNum, typename T, typename A>
bool SafeNetSerializeTArray_Default (FArchive &Ar, TArray< T, A > &Array)
template<int32 MaxNum, typename T, typename A>
int32 SafeNetSerializeTArray_HeaderOnly (FArchive &Ar, TArray< T, A > &Array, bool &bOutSuccess)
===================== Safe TArray Serialization =====================
template<int32 MaxNum, typename T, typename A>
bool SafeNetSerializeTArray_WithNetSerialize (FArchive &Ar, TArray< T, A > &Array, class UPackageMap *PackageMap)
template<int32 MaxValue, uint32 NumBits>
bool SerializeFixedVector (FVector3d &Vector, FArchive &Ar)
template<int32 MaxValue, uint32 NumBits>
bool SerializeFixedVector (FVector3f &Vector, FArchive &Ar)
template<typename ValueType>
bool SerializeOptionalValue (const bool bIsSaving, FArchive &Ar, ValueType &Value, const ValueType &DefaultValue)
Helper to optionally serialize a value (using operator<< on Archive).
template<int32 ScaleFactor, int32 MaxBitsPerComponent>
bool SerializePackedVector (FVector3d &Value, FArchive &Ar)
template<int32 ScaleFactor, int32 MaxBitsPerComponent>
bool SerializePackedVector (FVector3f &Value, FArchive &Ar)
template<int32 MaxValue, uint32 NumBits, typename T UE_REQUIRES>
bool WriteFixedCompressedFloat (const T Value, FArchive &Ar)
template<int32 ScaleFactor, int32 MaxBitsPerComponent>
bool WritePackedVector (FVector3d Vector, FArchive &Ar)
template<int32 ScaleFactor, int32 MaxBitsPerComponent>
bool WritePackedVector (FVector3f Value, FArchive &Ar)
Function Documentation
NetSerializeOptionalValue()
template<typename ValueType> bool NetSerializeOptionalValue (const bool bIsSaving, FArchive & Ar, ValueType & Value, const ValueType & DefaultValue, class UPackageMap * PackageMap)
Helper to optionally serialize a value (using the NetSerialize function).
A single signal bit indicates whether to serialize, or whether to just use the default value. Returns true if the value was not the default and needed to be serialized.
Definition at line 52 of file NetSerialization.h.
References Ar, and Value.
ReadFixedCompressedFloat()
template<int32 MaxValue, uint32 NumBits, typename T UE_REQUIRES> bool ReadFixedCompressedFloat (T & Value, FArchive & Ar)
Definition at line 329 of file NetSerialization.h.
References Value.
Referenced by SerializeFixedVector(), and SerializeFixedVector().
ReadPackedVector() [1/2]
template<int32 ScaleFactor, int32 MaxBitsPerComponent> bool ReadPackedVector (FVector3d & Value, FArchive & Ar)
Definition at line 233 of file NetSerialization.h.
References Ar, UE::Net::Private::LegacyReadPackedVector(), FEngineNetworkCustomVersion::PackedVectorLWCSupport, Value, and FEngineNetworkCustomVersion::Ver21AndViewPitchOnly_DONOTUSE.
ReadPackedVector() [2/2]
template<int32 ScaleFactor, int32 MaxBitsPerComponent> bool ReadPackedVector (FVector3f & Value, FArchive & Ar)
Definition at line 220 of file NetSerialization.h.
References Ar, UE::Net::Private::LegacyReadPackedVector(), FEngineNetworkCustomVersion::PackedVectorLWCSupport, Value, and FEngineNetworkCustomVersion::Ver21AndViewPitchOnly_DONOTUSE.
SafeNetSerializeTArray_Default()
template<int32 MaxNum, typename T, typename A> bool SafeNetSerializeTArray_Default (FArchive & Ar, TArray< T, A > & Array)
Definition at line 656 of file NetSerialization.h.
References Ar, Array, and SafeNetSerializeTArray_HeaderOnly().
SafeNetSerializeTArray_HeaderOnly()
template<int32 MaxNum, typename T, typename A> int32 SafeNetSerializeTArray_HeaderOnly (FArchive & Ar, TArray< T, A > & Array, bool & bOutSuccess)
===================== Safe TArray Serialization =====================
These are helper methods intended to make serializing TArrays safer in custom ::NetSerialize functions. These enforce max limits on array size, so that a malformed packet is not able to allocate an arbitrary amount of memory (E.g., a hacker serilizes a packet where a TArray size is of size MAX_int32, causing gigs of memory to be allocated for the TArray).
These should only need to be used when you are overriding ::NetSerialize on a UStruct via struct traits. When using default replication, TArray properties already have this built in security.
SafeNetSerializeTArray_Default - calls << operator to serialize the items in the array. SafeNetSerializeTArray_WithNetSerialize - calls NetSerialize to serialize the items in the array.
When saving, bOutSuccess will be set to false if the passed in array size exceeds to MaxNum template parameter.
Example:
FMyStruct {
TArray<float>                       MyFloats;       // We want to call << to serialize floats
TArray<FVector_NetQuantizeNormal>   MyVectors;      // We want to call NetSeriailze on these *
bool NetSerialize(FArchive& Ar, class UPackageMap* Map, bool& bOutSuccess)
{
    // Don't do this:
    Ar << MyFloats;
    Ar << MyVectors;
    // Do this instead:
    SafeNetSerializeTArray_Default<31>(Ar, MyFloats);
    SafeNetSerializeTArray_WithNetSerialize<31>(Ar, MyVectors, Map);
}
}
Definition at line 618 of file NetSerialization.h.
References Ar, and Array.
Referenced by SafeNetSerializeTArray_Default(), and SafeNetSerializeTArray_WithNetSerialize().
SafeNetSerializeTArray_WithNetSerialize()
template<int32 MaxNum, typename T, typename A> bool SafeNetSerializeTArray_WithNetSerialize (FArchive & Ar, TArray< T, A > & Array, class UPackageMap * PackageMap)
Definition at line 673 of file NetSerialization.h.
References Ar, Array, and SafeNetSerializeTArray_HeaderOnly().
SerializeFixedVector() [1/2]
template<int32 MaxValue, uint32 NumBits> bool SerializeFixedVector (FVector3d & Vector, FArchive & Ar)
Definition at line 378 of file NetSerialization.h.
References Ar, ReadFixedCompressedFloat(), Vector, and WriteFixedCompressedFloat().
SerializeFixedVector() [2/2]
template<int32 MaxValue, uint32 NumBits> bool SerializeFixedVector (FVector3f & Vector, FArchive & Ar)
Definition at line 360 of file NetSerialization.h.
References Ar, ReadFixedCompressedFloat(), Vector, and WriteFixedCompressedFloat().
SerializeOptionalValue()
template<typename ValueType> bool SerializeOptionalValue (const bool bIsSaving, FArchive & Ar, ValueType & Value, const ValueType & DefaultValue)
Helper to optionally serialize a value (using operator<< on Archive).
A single signal bit is indicates whether to serialize, or whether to just use the default value. Returns true if the value was not the default and needed to be serialized.
Definition at line 28 of file NetSerialization.h.
References Ar, and Value.
SerializePackedVector() [1/2]
template<int32 ScaleFactor, int32 MaxBitsPerComponent> bool SerializePackedVector (FVector3d & Value, FArchive & Ar)
Definition at line 265 of file NetSerialization.h.
References Ar, check, FEngineNetworkCustomVersion::Guid, UE::Net::Private::LegacyReadPackedVector(), FEngineNetworkCustomVersion::PackedVectorLWCSupport, Value, and FEngineNetworkCustomVersion::Ver21AndViewPitchOnly_DONOTUSE.
SerializePackedVector() [2/2]
template<int32 ScaleFactor, int32 MaxBitsPerComponent> bool SerializePackedVector (FVector3f & Value, FArchive & Ar)
Definition at line 249 of file NetSerialization.h.
References Ar, check, FEngineNetworkCustomVersion::Guid, UE::Net::Private::LegacyReadPackedVector(), FEngineNetworkCustomVersion::PackedVectorLWCSupport, Value, and FEngineNetworkCustomVersion::Ver21AndViewPitchOnly_DONOTUSE.
Referenced by FNetworkPredictionPhysicsState::NetRecv().
WriteFixedCompressedFloat()
template<int32 MaxValue, uint32 NumBits, typename T UE_REQUIRES> bool WriteFixedCompressedFloat (const T Value, FArchive & Ar)
Definition at line 296 of file NetSerialization.h.
References Scale, and Value.
Referenced by SerializeFixedVector(), and SerializeFixedVector().
WritePackedVector() [1/2]
template<int32 ScaleFactor, int32 MaxBitsPerComponent> bool WritePackedVector (FVector3d Vector, FArchive & Ar)
Definition at line 214 of file NetSerialization.h.
References Ar, and Vector.
WritePackedVector() [2/2]
template<int32 ScaleFactor, int32 MaxBitsPerComponent> bool WritePackedVector (FVector3f Value, FArchive & Ar)
Definition at line 208 of file NetSerialization.h.
References Ar, and Value.