Unreal Engine 5.6 C++ API: Runtime/CoreUObject/Public/UObject/Object.h File Reference
Object.h File Reference
#include "UObject/Script.h"
#include "UObject/ObjectMacros.h"
#include "UObject/UObjectBaseUtility.h"
#include "UObject/ObjectCompileContext.h"
#include "ProfilingDebugging/ResourceSize.h"
#include "UObject/PrimaryAssetId.h"
#include "Containers/VersePathFwd.h"
Data Structures
struct FInternalUObjectBaseUtilityIsValidFlagsChecker
struct FObjectNetPushIdHelper
class UObject
The base class of all UE objects.
struct UObject::FAssetRegistryTag
Struct used by GetAssetRegistryTags() to return tag info.
struct UObject::FAssetRegistryTagMetadata
Additional data pertaining to asset registry tags used by the editor.
struct UObject::Object_eventExecuteUbergraph_Parms
Wrapper struct to hold the entrypoint in the right memory address.
Namespaces
namespace ECastCheckedType
Parameter enum for CastChecked() function, defines when it will check/assert.
namespace UE
Utility functions for applying transformations to meshes.
namespace UE::AssetRegistry
namespace UE::ConfigAccessTracking
namespace UE::Cook
Enumerations
enum class EEditChangePropagationFlags : uint8 { None = 0 , OnlyMarkRealignedInstancesAsDirty = (1 << 0) }
Flags to control how editor change events get propagated.
enum ECastCheckedType::Type { ECastCheckedType::NullAllowed , ECastCheckedType::NullChecked }
Functions
DECLARE_LOG_CATEGORY_EXTERN (LogObj, Log, All)
ENUM_CLASS_FLAGS (EEditChangePropagationFlags)
template<typename T>
const T * GetValid (const T *Test)
Returns a pointer to a valid object if the Test object passes IsValid() tests, otherwise null.
template<typename T>
T * GetValid (T *Test)
Returns a pointer to a valid object if the Test object passes IsValid() tests, otherwise null.
FORCEINLINE bool IsValid (const UObject *Test)
Test validity of object.
FORCEINLINE bool IsValidChecked (const UObject *Test)
Test validity of object similar to IsValid(Test) however the null pointer test is skipped.
Variables
TFunction< bool(const UObject *)> GIsObjectSelectedInEditor
Callback for editor object selection.
Enumeration Type Documentation
EEditChangePropagationFlags
enum class EEditChangePropagationFlags : uint8 strong
Flags to control how editor change events get propagated.
Enumerator
None
No flags; use default change event propagation behavior.
OnlyMarkRealignedInstancesAsDirty
If set, only the subset of affected instances that realign with their archetype will be marked dirty.
If not set, affected instances will always be marked dirty, even if they already match the archetype.
Definition at line 70 of file Object.h.
Function Documentation
DECLARE_LOG_CATEGORY_EXTERN()
DECLARE_LOG_CATEGORY_EXTERN (LogObj , Log , All)
References All, and Log.
ENUM_CLASS_FLAGS()
ENUM_CLASS_FLAGS (EEditChangePropagationFlags)
GetValid() [1/2]
template<typename T> const T * GetValid (const T * Test)
Returns a pointer to a valid object if the Test object passes IsValid() tests, otherwise null.
Parameters
Test The object to test
Returns
Pointer to a valid object if the Test object passes IsValid() tests, otherwise null
Definition at line 1893 of file Object.h.
References IsValid(), and Test.
GetValid() [2/2]
template<typename T> T * GetValid (T * Test)
Returns a pointer to a valid object if the Test object passes IsValid() tests, otherwise null.
Parameters
Test The object to test
Returns
Pointer to a valid object if the Test object passes IsValid() tests, otherwise null
Definition at line 1880 of file Object.h.
References IsValid(), and Test.
IsValid()
FORCEINLINE bool IsValid (const UObject * Test)
Test validity of object.
Parameters
Test The object to test
Returns
Return true if the object is usable: non-null and not pending kill or garbage
Definition at line 1856 of file Object.h.
References FInternalUObjectBaseUtilityIsValidFlagsChecker::CheckObjectValidBasedOnItsFlags(), FORCEINLINE, and Test.
Referenced by DECLARE_LOG_CATEGORY_EXTERN(), ENUM_CLASS_FLAGS(), UE::Net::TStructNetTokenDataStoreHelper< T >::SerializeHelper(), UCLASS(), TBaseBlendedCurve< InAllocatorType, InElementType >::UE_DEPRECATED(), and UAbilitySystemBlueprintLibrary::UFUNCTION().
IsValidChecked()
FORCEINLINE bool IsValidChecked (const UObject * Test)
Test validity of object similar to IsValid(Test) however the null pointer test is skipped.
Parameters
Test The object to test
Returns
Return true if the object is usable: not pending kill or garbage
Definition at line 1867 of file Object.h.
References check, FInternalUObjectBaseUtilityIsValidFlagsChecker::CheckObjectValidBasedOnItsFlags(), FORCEINLINE, and Test.
Referenced by UE::MovieScene::FBuiltInComponentTypes::IsBoundObjectGarbage(), FArchiveReferenceMarker::operator<<(), and UCLASS().
Variable Documentation
GIsObjectSelectedInEditor
TFunction<bool(const UObject*)> GIsObjectSelectedInEditor extern
Callback for editor object selection.
This must be in core instead of editor for UObject::IsSelectedInEditor to work