Unreal Engine 5.6 C++ API: Runtime/CoreUObject/Public/UObject/OverriddenPropertySet.h File Reference
OverriddenPropertySet.h File Reference
#include "UObject/Object.h"
#include "OverriddenPropertySet.generated.h"
Data Structures
struct FEnableOverridableSerializationScope
struct FOverridableSerializationLogic
struct FOverridableTextPortPropertyPathScope
Macros
#define UE_API COREUOBJECT_API
Enumerations
enum class EPropertyNotificationType : uint8 { PreEdit , PostEdit }
Functions
DECLARE_LOG_CATEGORY_EXTERN (LogOverridableObject, Warning, All)
TOptional< EOverriddenPropertyOperation > GetOverriddenOperationFromName (const FName OverriddenOperationName)
UENUM() enum class EOverriddenPropertyOperation TOptional< EOverriddenPropertyOperation > GetOverriddenOperationFromString (const FString &OverriddenOperationString)
FString GetOverriddenOperationString (EOverriddenPropertyOperation Operation)
USTRUCT () struct FOverriddenPropertyNodeID
Macro Definition Documentation
UE_API
#define UE_API COREUOBJECT_API
Definition at line 9 of file OverriddenPropertySet.h.
Enumeration Type Documentation
EPropertyNotificationType
enum class EPropertyNotificationType : uint8 strong
Enumerator
PreEdit
PostEdit
Definition at line 311 of file OverriddenPropertySet.h.
Function Documentation
DECLARE_LOG_CATEGORY_EXTERN()
DECLARE_LOG_CATEGORY_EXTERN (LogOverridableObject , Warning , All)
References All, and Warning.
GetOverriddenOperationFromName()
TOptional< EOverriddenPropertyOperation > GetOverriddenOperationFromName (const FName OverriddenOperationName) inline
Definition at line 197 of file OverriddenPropertySet.h.
References GetOverriddenOperationFromString(), and FName::ToString().
GetOverriddenOperationFromString()
UENUM() enum class EOverriddenPropertyOperation TOptional< EOverriddenPropertyOperation > GetOverriddenOperationFromString (const FString & OverriddenOperationString) inline
Definition at line 186 of file OverriddenPropertySet.h.
References INDEX_NONE, StaticEnum(), and TEXT.
Referenced by GetOverriddenOperationFromName().
GetOverriddenOperationString()
FString GetOverriddenOperationString (EOverriddenPropertyOperation Operation) inline
Definition at line 202 of file OverriddenPropertySet.h.
References StaticEnum().
USTRUCT()
USTRUCT ()
Retrieve the overridable operation from the specified the edit property chain node
Parameters
PropertyIterator leading to the property interested in, invalid iterator will return the operation of the object itself
bOutInheritedOperation optional parameter to know if the state returned was inherited from a parent property
Returns
the current type of override operation on the property
Clear any properties from the serialized property chain node
Parameters
PropertyIterator leading to the property to clear, invalid iterator will clear the overrides on the object itself
Returns
if the operation was successful
Utility methods that call NotifyPropertyChange(Pre/PostEdit)
Parameters
PropertyIterator leading to the property that is changing, invalid iterator means it is the object itself that is changing
Data memory of the current property
Handling and storing modification on a property of an object
Parameters
Notification type either pre/post property overridden
PropertyIterator leading to the property that is changing, null means it is the object itself that is changing
ChangeType of the current operation
Data memory of the current property
Retrieve the overridable operation from the specified the serialized property chain and the specified property
Parameters
CurrentPropertyChain leading to the property being serialized if any, null or empty it will return the node of the object itself
Property being serialized if any, if null it will fallback on the last property of the chain
Returns
the current type of override operation on the property
Setup the overridable operation of the current property from the serialized property chain and the specified property
Parameters
Operation to set for this property
CurrentPropertyChain leading to the property being serialized if any, null or empty it will return the node of the object itself
Property being serialized if any, if null it will fallback on the last property of the chain
Returns
the node containing the information of the overridden property
Restore the overridable operation of the current property from the serialized property chain and the specified property
Note
: This will not restore modified state, has restoring sub properties will do it anyway.
Parameters
Operation to set for this property
CurrentPropertyChain leading to the property being serialized if any, null or empty it will return the node of the object itself
Property being serialized if any, if null it will fallback on the last property of the chain
Returns
the node containing the information of the overridden property
Retrieve the overridden property node from the serialized property chain
Parameters
CurrentPropertyChain leading to the property being serialized if any, null or empty it will return the node of the object itself
Returns
the node containing the information of the overridden property
Retrieve the overridable operation given the property key
Parameters
NodeID that uniquely identify the property within the object
Returns
the current type of override operation on the property
Set the overridable operation of a sub property of the specified node.
Parameters
Operation to set for this property
Node from where the sub property is owned by
NodeID the ID of the sub property
Returns
the node to the sub property
Set the overridable operation of a sub object of the specified node.
Parameters
Operation to set for this property
Node from where the sub property is owned by
SubObject of the operation
Returns
the node to the sub property
Check if this is an overridden property set of a CDO and that this property is owned by the class of this CDO NOTE: this is used to know if a property should be serialized to keep its default CDO value.
Parameters
Property
Returns
Resets all overrides of the object
Restore some of the overridden state that is not necessarily restored by the CPFUO (ex: bWasAdded come from the owner of the object and reinstantiating the object does not preserve it)
Parameters
FromOverriddenProperties overridable properties to restore from
Definition at line 207 of file OverriddenPropertySet.h.
References GENERATED_BODY, GetTypeHash(), GUObjectArray, IsValid(), Map, Object, operator==(), Other, Owner, Path, Property, TEXT, ToString(), and UPROPERTY.