Unreal Engine 5.6 C++ API: Runtime/Core/Public/Async/ParallelFor.h File Reference
ParallelFor.h File Reference
#include "AutoRTFM.h"
#include "Async/Fundamental/Scheduler.h"
#include "Async/Fundamental/Task.h"
#include "Async/TaskGraphInterfaces.h"
#include "Containers/Array.h"
#include "Containers/ArrayView.h"
#include "CoreGlobals.h"
#include "CoreTypes.h"
#include "Experimental/ConcurrentLinearAllocator.h"
#include "HAL/Event.h"
#include "HAL/LowLevelMemTracker.h"
#include "HAL/PlatformMisc.h"
#include "HAL/PlatformTime.h"
#include "HAL/ThreadSafeCounter.h"
#include "Math/UnrealMathUtility.h"
#include "Misc/App.h"
#include "Misc/AssertionMacros.h"
#include "Misc/EnumClassFlags.h"
#include "Misc/Fork.h"
#include "Misc/MemStack.h"
#include "Misc/Timespan.h"
#include "ProfilingDebugging/CpuProfilerTrace.h"
#include "ProfilingDebugging/TagTrace.h"
#include "Stats/Stats.h"
#include "Templates/Function.h"
#include "Templates/RefCounting.h"
#include "Templates/SharedPointer.h"
#include "Templates/UnrealTemplate.h"
#include <atomic>
Namespaces
namespace UE
Utility functions for applying transformations to meshes.
namespace UE::LLMPrivate
Enumerations
enum class EParallelForFlags {
None , ForceSingleThread = 1 , Unbalanced = 2 , PumpRenderingThread = 4 ,
BackgroundPriority = 8
}
Functions
ENUM_CLASS_FLAGS (EParallelForFlags) namespace ParallelForImpl
void ParallelFor (const TCHAR *DebugName, int32 Num, int32 MinBatchSize, TFunctionRef< void(int32)> Body, EParallelForFlags Flags=EParallelForFlags::None)
General purpose parallel for that uses the taskgraph for unbalanced tasks Offers better work distribution among threads at the cost of a little bit more synchronization.
void ParallelFor (int32 Num, TFunctionRef< void(int32)> Body, bool bForceSingleThread, bool bPumpRenderingThread=false)
General purpose parallel for that uses the taskgraph.
void ParallelFor (int32 Num, TFunctionRef< void(int32)> Body, EParallelForFlags Flags=EParallelForFlags::None)
General purpose parallel for that uses the taskgraph for unbalanced tasks Offers better work distribution among threads at the cost of a little bit more synchronization.
template<typename FunctionType>
void ParallelForTemplate (const TCHAR *DebugName, int32 Num, int32 MinBatchSize, const FunctionType &Body, EParallelForFlags Flags=EParallelForFlags::None)
General purpose parallel for that uses the taskgraph.
template<typename FunctionType>
void ParallelForTemplate (int32 Num, const FunctionType &Body, EParallelForFlags Flags=EParallelForFlags::None)
General purpose parallel for that uses the taskgraph.
template<typename ContextType, typename FunctionType>
void ParallelForWithExistingTaskContext (const TCHAR *DebugName, TArrayView< ContextType > Contexts, int32 Num, int32 MinBatchSize, const FunctionType &Body, EParallelForFlags Flags=EParallelForFlags::None)
General purpose parallel for that uses the taskgraph.
template<typename ContextType, typename FunctionType>
void ParallelForWithExistingTaskContext (TArrayView< ContextType > Contexts, int32 Num, int32 MinBatchSize, const FunctionType &Body, EParallelForFlags Flags=EParallelForFlags::None)
General purpose parallel for that uses the taskgraph.
void ParallelForWithPreWork (const TCHAR *DebugName, int32 Num, int32 MinBatchSize, TFunctionRef< void(int32)> Body, TFunctionRef< void()> CurrentThreadWorkToDoBeforeHelping, EParallelForFlags Flags=EParallelForFlags::None)
General purpose parallel for that uses the taskgraph.
void ParallelForWithPreWork (int32 Num, TFunctionRef< void(int32)> Body, TFunctionRef< void()> CurrentThreadWorkToDoBeforeHelping, bool bForceSingleThread, bool bPumpRenderingThread=false)
General purpose parallel for that uses the taskgraph.
void ParallelForWithPreWork (int32 Num, TFunctionRef< void(int32)> Body, TFunctionRef< void()> CurrentThreadWorkToDoBeforeHelping, EParallelForFlags Flags=EParallelForFlags::None)
General purpose parallel for that uses the taskgraph.
template<typename ContextType, typename BodyType, typename PreWorkType>
void ParallelForWithPreWorkWithExistingTaskContext (const TCHAR *DebugName, TArrayView< ContextType > Contexts, int32 Num, int32 MinBatchSize, BodyType &&Body, PreWorkType &&CurrentThreadWorkToDoBeforeHelping, EParallelForFlags Flags=EParallelForFlags::None)
General purpose parallel for that uses the taskgraph.
template<typename ContextType, typename ContextAllocatorType, typename BodyType, typename PreWorkType>
void ParallelForWithPreWorkWithTaskContext (const TCHAR *DebugName, TArray< ContextType, ContextAllocatorType > &OutContexts, int32 Num, int32 MinBatchSize, BodyType &&Body, PreWorkType &&CurrentThreadWorkToDoBeforeHelping, EParallelForFlags Flags=EParallelForFlags::None)
General purpose parallel for that uses the taskgraph.
template<typename ContextType, typename ContextAllocatorType, typename ContextConstructorType, typename BodyType, typename PreWorkType>
void ParallelForWithPreWorkWithTaskContext (const TCHAR *DebugName, TArray< ContextType, ContextAllocatorType > &OutContexts, int32 Num, int32 MinBatchSize, ContextConstructorType &&ContextConstructor, BodyType &&Body, PreWorkType &&CurrentThreadWorkToDoBeforeHelping, EParallelForFlags Flags=EParallelForFlags::None)
General purpose parallel for that uses the taskgraph.
template<typename ContextType, typename ContextAllocatorType, typename ContextConstructorType, typename FunctionType>
void ParallelForWithTaskContext (const TCHAR *DebugName, TArray< ContextType, ContextAllocatorType > &OutContexts, int32 Num, const ContextConstructorType &ContextConstructor, const FunctionType &Body, EParallelForFlags Flags=EParallelForFlags::None)
General purpose parallel for that uses the taskgraph.
template<typename ContextType, typename ContextAllocatorType, typename ContextConstructorType, typename FunctionType>
void ParallelForWithTaskContext (const TCHAR *DebugName, TArray< ContextType, ContextAllocatorType > &OutContexts, int32 Num, int32 MinBatchSize, const ContextConstructorType &ContextConstructor, const FunctionType &Body, EParallelForFlags Flags=EParallelForFlags::None)
General purpose parallel for that uses the taskgraph.
template<typename ContextType, typename ContextAllocatorType, typename FunctionType>
void ParallelForWithTaskContext (const TCHAR *DebugName, TArray< ContextType, ContextAllocatorType > &OutContexts, int32 Num, int32 MinBatchSize, const FunctionType &Body, EParallelForFlags Flags=EParallelForFlags::None)
General purpose parallel for that uses the taskgraph.
template<typename ContextType, typename ContextAllocatorType, typename ContextConstructorType, typename FunctionType>
void ParallelForWithTaskContext (TArray< ContextType, ContextAllocatorType > &OutContexts, int32 Num, const ContextConstructorType &ContextConstructor, const FunctionType &Body, EParallelForFlags Flags=EParallelForFlags::None)
General purpose parallel for that uses the taskgraph.
template<typename ContextType, typename ContextAllocatorType, typename FunctionType>
void ParallelForWithTaskContext (TArray< ContextType, ContextAllocatorType > &OutContexts, int32 Num, const FunctionType &Body, EParallelForFlags Flags=EParallelForFlags::None)
General purpose parallel for that uses the taskgraph.
Variables
int32 GParallelForBackgroundYieldingTimeoutMs
bool GParallelForDisableOversubscription
Enumeration Type Documentation
EParallelForFlags
enum class EParallelForFlags strong
Enumerator
None
ForceSingleThread
Unbalanced
PumpRenderingThread
BackgroundPriority
Definition at line 46 of file ParallelFor.h.
Function Documentation
ENUM_CLASS_FLAGS()
ENUM_CLASS_FLAGS (EParallelForFlags)
General purpose parallel for that uses the taskgraph
Parameters
DebugName; Debugname and Profiling TraceTag
Num; number of calls of Body; Body(0), Body(1)....Body(Num - 1)
MinBatchSize; Minimum size a Batch should have
Body; Function to call from multiple threads
CurrentThreadWorkToDoBeforeHelping; The work is performed on the main thread before it starts helping with the ParallelFor proper
Flags; Used to customize the behavior of the ParallelFor if needed.
Contexts; Optional per thread contexts to accumulate data concurrently. Notes: Please add stats around to calls to parallel for and within your lambda as appropriate. Do not clog the task graph with long running tasks or tasks that block.
Definition at line 65 of file ParallelFor.h.
References ENamedThreads::AnyThread, LowLevelTasks::BackgroundNormal, BackgroundPriority, check, checkSlow, TaskTrace::Completed(), TaskTrace::Destroyed(), FMath::DivideAndRoundUp(), EGameThread, ENone, ERenderingThread, ERhiThread, ESlateThread, EStaticInit, Flags, ForceSingleThread, FTimespan::FromMilliseconds(), FTimespan::FromSeconds(), TaskTrace::GenerateTaskId(), FTaskGraphInterface::Get(), LowLevelTasks::FScheduler::Get(), FTaskTagScope::GetCurrentTag(), GetData(), ENamedThreads::GetRenderThread_Local(), LowLevelTasks::GlobalQueuePreference, GParallelForBackgroundYieldingTimeoutMs, GParallelForDisableOversubscription, LowLevelTasks::High, LowLevelTasks::Inherit, TaskTrace::InvalidId, TArrayView< InElementType, InSizeType >::IsEmpty(), FForkProcessHelper::IsForkedMultithreadInstance(), IsInActualRenderingThread(), TaskTrace::Launched(), ManualReset, FMath::Max, FMath::Min, FTimespan::MinValue(), MoveTemp(), None, Num, TArrayView< InElementType, InSizeType >::Num(), FAndroidMisc::NumberOfCoresIncludingHyperthreads(), ON_SCOPE_EXIT, Other, ParallelFor(), FTaskGraphInterface::ProcessThreadUntilIdle(), PumpRenderingThread, UE::FInheritedContextBase::RestoreInheritedContext(), SCOPE_CYCLE_COUNTER, FAndroidTime::Seconds(), FApp::ShouldUseThreadingForPerformance(), TaskTrace::Started(), TRACE_CPUPROFILER_EVENT_SCOPE, TRACE_CPUPROFILER_EVENT_SCOPE_TEXT, LowLevelTasks::TryLaunch(), Unbalanced, verify, and FEvent::Wait().
ParallelFor() [1/3]
void ParallelFor (const TCHAR * DebugName, int32 Num, int32 MinBatchSize, TFunctionRef< void(int32)> Body, EParallelForFlags Flags = EParallelForFlags::None) inline
General purpose parallel for that uses the taskgraph for unbalanced tasks Offers better work distribution among threads at the cost of a little bit more synchronization.
This should be used for tasks with highly variable computational time.
Parameters
DebugName; ProfilingScope and Debugname
Num; number of calls of Body; Body(0), Body(1)....Body(Num - 1)
MinBatchSize; Minimum Size of a Batch (will only launch DivUp(Num, MinBatchSize) Workers
Body; Function to call from multiple threads
Flags; Used to customize the behavior of the ParallelFor if needed. Notes: Please add stats around to calls to parallel for and within your lambda as appropriate. Do not clog the task graph with long running tasks or tasks that block.
Definition at line 543 of file ParallelFor.h.
References Flags, None, and Num.
ParallelFor() [2/3]
void ParallelFor (int32 Num, TFunctionRef< void(int32)> Body, bool bForceSingleThread, bool bPumpRenderingThread = false) inline
General purpose parallel for that uses the taskgraph.
Parameters
Num; number of calls of Body; Body(0), Body(1)....Body(Num - 1)
Body; Function to call from multiple threads
bForceSingleThread; Mostly used for testing, if true, run single threaded instead. Notes: Please add stats around to calls to parallel for and within your lambda as appropriate. Do not clog the task graph with long running tasks or tasks that block.
Definition at line 481 of file ParallelFor.h.
References ForceSingleThread, None, Num, PumpRenderingThread, and TEXT.
Referenced by UE::Geometry::FOccupancyGrid3::FOccupancyGrid3(), UE::Geometry::TSparseNarrowBandMeshSDF< TriangleMeshType >::FScatterCounter::FScatterCounter(), UE::Geometry::TSparseNarrowBandMeshSDF< TriangleMeshType >::FTriIDBlockGrid::FTriIDBlockGrid(), FBaseKelvinletBrushOp::ApplyFalloff(), FEraseSculptLayerBrushOp::ApplyStamp(), FEraseToBaseMeshBrushOp::ApplyStamp(), FFlattenBrushOp::ApplyStamp(), FInflateBrushOp::ApplyStamp(), FMoveBrushOp::ApplyStamp(), FPinchBrushOp::ApplyStamp(), FPlaneBrushOp::ApplyStamp(), FSmoothBrushOp::ApplyStamp(), FSmoothFillBrushOp::ApplyStamp(), FSurfaceMaxSculptBrushOp::ApplyStamp(), FSurfaceSculptBrushOp::ApplyStamp(), FViewAlignedSculptBrushOp::ApplyStamp(), UE::Geometry::FVertexColorSmoothBrushOp::ApplyStampToVertexColors(), UE::Geometry::FVertexPaintBrushOp::ApplyStampToVertexColors(), MeshAdapterTransforms::ApplyTransform(), MeshAdapterTransforms::ApplyTransform(), MeshAdapterTransforms::ApplyTransformInverse(), UE::Geometry::FMeshTriInfoCache::BuildTriInfoCache(), UE::Geometry::TCachingMeshSDF< TriangleMeshType >::compute_intersections(), UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::compute_intersections(), UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::compute_intersections(), UE::Geometry::TCachingMeshSDF< TriangleMeshType >::compute_signs(), UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::compute_signs(), UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::compute_signs(), UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::compute_tri_bboxes(), UE::Geometry::FClusterKMeans::ComputeClusters(), UE::Geometry::FImageOccupancyMap::ComputeGutterTexelsFromGutterSamples(), UE::Geometry::TImplicitBlend< TriangleMeshType >::ComputeLazySDFs(), UE::CurveEditor::TUniformMirrorSolver< TNumeric >::ComputeMirroringParallel(), UE::Geometry::TImplicitBlend< TriangleMeshType >::ComputeSpatials(), FBaseKelvinletBrushOp::DisplaceKelvinlet(), FKelvinletBrushOp::DisplaceKelvinlet(), UE::Geometry::FDisplaceMesh::DisplaceMeshWithVertexWeights(), ENUM_CLASS_FLAGS(), FAsyncAddPrimitiveQueue::FAddPrimitivesTask::Execute(), UE::Geometry::TImageBuilder< PixelType >::FastDownsample(), UE::Geometry::TMeshWindingNumberGrid< TriangleMeshType >::fill_spans(), MeshAdapterTransforms::FrameCoordsToWorld(), UE::Geometry::FSubRegionRemesher::FullSmoothPass_Buffer(), UE::Geometry::FMarchingCubes::generate_continuation_parallel(), UE::Geometry::FMarchingCubes::generate_parallel(), FMeshRenderBufferSetConversionUtil::InitializeBuffersFromOverlays(), FBaseKelvinletBrushOp::IntegrateKelvinlet(), FKelvinletBrushOp::IntegrateKelvinlet(), UE::Geometry::TMeshWindingNumberGrid< TriangleMeshType >::make_grid(), UE::Geometry::TMeshWindingNumberGrid< TriangleMeshType >::make_grid_dense(), UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::make_level_set3_parallel(), UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::make_level_set3_parallel(), UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::make_level_set3_parallel_floodfill(), UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::make_level_set3_parallel_floodfill(), UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::make_level_set3_parallel_spatial(), UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::make_level_set3_parallel_spatial(), UE::Geometry::FIterativeOffsetMeshOp::Offset_Smoothed(), UE::Geometry::FGeometrySet3::ParallelFindAllCurvesSatisfying(), UE::Geometry::FGeometrySet3::ParallelFindAllPointsSatisfying(), UE::Geometry::FSparseDynamicPointOctree3::ParallelInsertDensePointSet(), UE::Geometry::FImageOccupancyMap::ParallelProcessingPass(), UE::Geometry::FSparseDynamicPointOctree3::ParallelRangeQuery(), UE::Geometry::ParallelTransformReduce(), UE::Geometry::ParallelTransformReduce(), UE::Geometry::ParallelTransformReduce(), UE::Geometry::ParallelTransformReduce(), UE::Geometry::FDynamicMeshOctree3::ReinsertTrianglesParallel(), UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::scatter_tris(), UE::Geometry::TRemoveOccludedTriangles< OccluderTriangleMeshType >::Select(), MeshAdapterTransforms::Translate(), UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::update_signs(), UE::Geometry::TMeshQueries< TriangleMeshType >::VertexToSurfaceDistances(), and MeshAdapterTransforms::WorldToFrameCoords().
ParallelFor() [3/3]
void ParallelFor (int32 Num, TFunctionRef< void(int32)> Body, EParallelForFlags Flags = EParallelForFlags::None) inline
General purpose parallel for that uses the taskgraph for unbalanced tasks Offers better work distribution among threads at the cost of a little bit more synchronization.
This should be used for tasks with highly variable computational time.
Parameters
Num; number of calls of Body; Body(0), Body(1)....Body(Num - 1)
Body; Function to call from multiple threads
Flags; Used to customize the behavior of the ParallelFor if needed. Notes: Please add stats around to calls to parallel for and within your lambda as appropriate. Do not clog the task graph with long running tasks or tasks that block.
Definition at line 526 of file ParallelFor.h.
References Flags, None, Num, and TEXT.
ParallelForTemplate() [1/2]
template<typename FunctionType> void ParallelForTemplate (const TCHAR * DebugName, int32 Num, int32 MinBatchSize, const FunctionType & Body, EParallelForFlags Flags = EParallelForFlags::None) inline
General purpose parallel for that uses the taskgraph.
Parameters
DebugName; ProfilingScope and Debugname
Num; number of calls of Body; Body(0), Body(1)....Body(Num - 1)
MinBatchSize; Minimum Size of a Batch (will only launch DivUp(Num, MinBatchSize) Workers
Body; Function to call from multiple threads
bForceSingleThread; Mostly used for testing, if true, run single threaded instead. Notes: Please add stats around to calls to parallel for and within your lambda as appropriate. Do not clog the task graph with long running tasks or tasks that block.
Definition at line 511 of file ParallelFor.h.
References Flags, None, and Num.
ParallelForTemplate() [2/2]
template<typename FunctionType> void ParallelForTemplate (int32 Num, const FunctionType & Body, EParallelForFlags Flags = EParallelForFlags::None) inline
General purpose parallel for that uses the taskgraph.
Parameters
Num; number of calls of Body; Body(0), Body(1)....Body(Num - 1)
Body; Function to call from multiple threads
bForceSingleThread; Mostly used for testing, if true, run single threaded instead. Notes: Please add stats around to calls to parallel for and within your lambda as appropriate. Do not clog the task graph with long running tasks or tasks that block.
Definition at line 496 of file ParallelFor.h.
References Flags, None, Num, and TEXT.
ParallelForWithExistingTaskContext() [1/2]
template<typename ContextType, typename FunctionType> void ParallelForWithExistingTaskContext (const TCHAR * DebugName, TArrayView< ContextType > Contexts, int32 Num, int32 MinBatchSize, const FunctionType & Body, EParallelForFlags Flags = EParallelForFlags::None) inline
General purpose parallel for that uses the taskgraph.
This variant takes an array of user-defined context objects for each task that may get spawned to do work (one task per context at most), and passes them to the loop body to give it a task-local "workspace" that can be mutated without need for synchronization primitives.
Parameters
DebugName; ProfilingScope and Debugname
Contexts; User-privided array of user-defined task-level context objects
Num; number of calls of Body; Body(0), Body(1)....Body(Num - 1)
MinBatchSize; Minimum Size of a Batch (will only launch DivUp(Num, MinBatchSize) Workers
Body; Function to call from multiple threads
Flags; Used to customize the behavior of the ParallelFor if needed. Notes: Please add stats around to calls to parallel for and within your lambda as appropriate. Do not clog the task graph with long running tasks or tasks that block.
Definition at line 833 of file ParallelFor.h.
References Flags, None, and Num.
ParallelForWithExistingTaskContext() [2/2]
template<typename ContextType, typename FunctionType> void ParallelForWithExistingTaskContext (TArrayView< ContextType > Contexts, int32 Num, int32 MinBatchSize, const FunctionType & Body, EParallelForFlags Flags = EParallelForFlags::None) inline
General purpose parallel for that uses the taskgraph.
This variant takes an array of user-defined context objects for each task that may get spawned to do work (one task per context at most), and passes them to the loop body to give it a task-local "workspace" that can be mutated without need for synchronization primitives.
Parameters
Contexts; User-privided array of user-defined task-level context objects
Num; number of calls of Body; Body(0), Body(1)....Body(Num - 1)
MinBatchSize; Minimum Size of a Batch (will only launch DivUp(Num, MinBatchSize) Workers
Body; Function to call from multiple threads
Flags; Used to customize the behavior of the ParallelFor if needed. Notes: Please add stats around to calls to parallel for and within your lambda as appropriate. Do not clog the task graph with long running tasks or tasks that block.
Definition at line 815 of file ParallelFor.h.
References Flags, None, Num, and TEXT.
ParallelForWithPreWork() [1/3]
void ParallelForWithPreWork (const TCHAR * DebugName, int32 Num, int32 MinBatchSize, TFunctionRef< void(int32)> Body, TFunctionRef< void()> CurrentThreadWorkToDoBeforeHelping, EParallelForFlags Flags = EParallelForFlags::None) inline
General purpose parallel for that uses the taskgraph.
Parameters
DebugName; ProfilingScope and Debugname
Num; number of calls of Body; Body(0), Body(1)....Body(Num - 1)
MinBatchSize; Minimum Size of a Batch (will only launch DivUp(Num, MinBatchSize) Workers
Body; Function to call from multiple threads
CurrentThreadWorkToDoBeforeHelping; The work is performed on the main thread before it starts helping with the ParallelFor proper
Flags; Used to customize the behavior of the ParallelFor if needed. Notes: Please add stats around to calls to parallel for and within your lambda as appropriate. Do not clog the task graph with long running tasks or tasks that block.
Definition at line 586 of file ParallelFor.h.
References Flags, None, and Num.
ParallelForWithPreWork() [2/3]
void ParallelForWithPreWork (int32 Num, TFunctionRef< void(int32)> Body, TFunctionRef< void()> CurrentThreadWorkToDoBeforeHelping, bool bForceSingleThread, bool bPumpRenderingThread = false) inline
General purpose parallel for that uses the taskgraph.
Parameters
Num; number of calls of Body; Body(0), Body(1)....Body(Num - 1)
Body; Function to call from multiple threads
CurrentThreadWorkToDoBeforeHelping; The work is performed on the main thread before it starts helping with the ParallelFor proper
bForceSingleThread; Mostly used for testing, if true, run single threaded instead. Notes: Please add stats around to calls to parallel for and within your lambda as appropriate. Do not clog the task graph with long running tasks or tasks that block.
Definition at line 556 of file ParallelFor.h.
References ForceSingleThread, None, Num, PumpRenderingThread, and TEXT.
ParallelForWithPreWork() [3/3]
void ParallelForWithPreWork (int32 Num, TFunctionRef< void(int32)> Body, TFunctionRef< void()> CurrentThreadWorkToDoBeforeHelping, EParallelForFlags Flags = EParallelForFlags::None) inline
General purpose parallel for that uses the taskgraph.
Parameters
Num; number of calls of Body; Body(0), Body(1)....Body(Num - 1)
Body; Function to call from multiple threads
CurrentThreadWorkToDoBeforeHelping; The work is performed on the main thread before it starts helping with the ParallelFor proper
Flags; Used to customize the behavior of the ParallelFor if needed. Notes: Please add stats around to calls to parallel for and within your lambda as appropriate. Do not clog the task graph with long running tasks or tasks that block.
Definition at line 571 of file ParallelFor.h.
References Flags, None, Num, and TEXT.
ParallelForWithPreWorkWithExistingTaskContext()
template<typename ContextType, typename BodyType, typename PreWorkType> void ParallelForWithPreWorkWithExistingTaskContext (const TCHAR * DebugName, TArrayView< ContextType > Contexts, int32 Num, int32 MinBatchSize, BodyType && Body, PreWorkType && CurrentThreadWorkToDoBeforeHelping, EParallelForFlags Flags = EParallelForFlags::None) inline
General purpose parallel for that uses the taskgraph.
Parameters
DebugName; ProfilingScope and DebugName
Contexts; User-privided array of user-defined task-level context objects
Num; number of calls of Body; Body(0), Body(1), ..., Body(Num - 1)
MinBatchSize; Minimum Size of a Batch (will only launch DivUp(Num, MinBatchSize) Workers
Body; Function to call from multiple threads
CurrentThreadWorkToDoBeforeHelping; The work is performed on the main thread before it starts helping with the ParallelFor proper
Flags; Used to customize the behavior of the ParallelFor if needed. Notes: Please add stats around to calls to parallel for and within your lambda as appropriate. Do not clog the task graph with long running tasks or tasks that block.
Definition at line 668 of file ParallelFor.h.
References Flags, Forward(), None, and Num.
ParallelForWithPreWorkWithTaskContext() [1/2]
template<typename ContextType, typename ContextAllocatorType, typename BodyType, typename PreWorkType> void ParallelForWithPreWorkWithTaskContext (const TCHAR * DebugName, TArray< ContextType, ContextAllocatorType > & OutContexts, int32 Num, int32 MinBatchSize, BodyType && Body, PreWorkType && CurrentThreadWorkToDoBeforeHelping, EParallelForFlags Flags = EParallelForFlags::None) inline
General purpose parallel for that uses the taskgraph.
Parameters
DebugName; ProfilingScope and DebugName
OutContexts; Array that will hold the user-defined, task-level context objects (allocated per parallel task)
Num; number of calls of Body; Body(0), Body(1), ..., Body(Num - 1)
MinBatchSize; Minimum Size of a Batch (will only launch DivUp(Num, MinBatchSize) Workers
Body; Function to call from multiple threads
CurrentThreadWorkToDoBeforeHelping; The work is performed on the main thread before it starts helping with the ParallelFor proper
Flags; Used to customize the behavior of the ParallelFor if needed. Notes: Please add stats around to calls to parallel for and within your lambda as appropriate. Do not clog the task graph with long running tasks or tasks that block.
Definition at line 638 of file ParallelFor.h.
References TArray< InElementType, InAllocatorType >::AddDefaulted(), Flags, Forward(), None, Num, and TArray< InElementType, InAllocatorType >::Reset().
ParallelForWithPreWorkWithTaskContext() [2/2]
template<typename ContextType, typename ContextAllocatorType, typename ContextConstructorType, typename BodyType, typename PreWorkType> void ParallelForWithPreWorkWithTaskContext (const TCHAR * DebugName, TArray< ContextType, ContextAllocatorType > & OutContexts, int32 Num, int32 MinBatchSize, ContextConstructorType && ContextConstructor, BodyType && Body, PreWorkType && CurrentThreadWorkToDoBeforeHelping, EParallelForFlags Flags = EParallelForFlags::None) inline
General purpose parallel for that uses the taskgraph.
Parameters
DebugName; ProfilingScope and DebugName
OutContexts; Array that will hold the user-defined, task-level context objects (allocated per parallel task)
Num; number of calls of Body; Body(0), Body(1), ..., Body(Num - 1)
MinBatchSize; Minimum Size of a Batch (will only launch DivUp(Num, MinBatchSize) Workers
ContextConstructor; Function to call to initialize each task context allocated for the operation
Body; Function to call from multiple threads
CurrentThreadWorkToDoBeforeHelping; The work is performed on the main thread before it starts helping with the ParallelFor proper
Flags; Used to customize the behavior of the ParallelFor if needed. Notes: Please add stats around to calls to parallel for and within your lambda as appropriate. Do not clog the task graph with long running tasks or tasks that block.
Definition at line 604 of file ParallelFor.h.
References TArray< InElementType, InAllocatorType >::Emplace(), Flags, Forward(), None, Num, and TArray< InElementType, InAllocatorType >::Reset().
ParallelForWithTaskContext() [1/5]
template<typename ContextType, typename ContextAllocatorType, typename ContextConstructorType, typename FunctionType> void ParallelForWithTaskContext (const TCHAR * DebugName, TArray< ContextType, ContextAllocatorType > & OutContexts, int32 Num, const ContextConstructorType & ContextConstructor, const FunctionType & Body, EParallelForFlags Flags = EParallelForFlags::None) inline
General purpose parallel for that uses the taskgraph.
This variant constructs for the caller a user-defined context object for each task that may get spawned to do work, and passes it on to the loop body to give it a task-local "workspace" that can be mutated without need for synchronization primitives. For this variant, the user provides a callable to construct each context element.
Parameters
OutContexts; Array that will hold the user-defined, task-level context objects (allocated per parallel task)
DebugName; ProfilingScope and Debugname
Num; number of calls of Body; Body(0), Body(1)....Body(Num - 1)
ContextConstructor; Function to call to initialize each task context allocated for the operation
Body; Function to call from multiple threads
Flags; Used to customize the behavior of the ParallelFor if needed. Notes: Please add stats around to calls to parallel for and within your lambda as appropriate. Do not clog the task graph with long running tasks or tasks that block.
Definition at line 694 of file ParallelFor.h.
References TArray< InElementType, InAllocatorType >::AddUninitialized(), Flags, None, Num, and TArray< InElementType, InAllocatorType >::Reset().
Referenced by ParallelForWithTaskContext().
ParallelForWithTaskContext() [2/5]
template<typename ContextType, typename ContextAllocatorType, typename ContextConstructorType, typename FunctionType> void ParallelForWithTaskContext (const TCHAR * DebugName, TArray< ContextType, ContextAllocatorType > & OutContexts, int32 Num, int32 MinBatchSize, const ContextConstructorType & ContextConstructor, const FunctionType & Body, EParallelForFlags Flags = EParallelForFlags::None) inline
General purpose parallel for that uses the taskgraph.
This variant constructs for the caller a user-defined context object for each task that may get spawned to do work, and passes it on to the loop body to give it a task-local "workspace" that can be mutated without need for synchronization primitives. For this variant, the user provides a callable to construct each context element.
Parameters
OutContexts; Array that will hold the user-defined, task-level context objects (allocated per parallel task)
DebugName; ProfilingScope and Debugname
Num; number of calls of Body; Body(0), Body(1)....Body(Num - 1)
MinBatchSize; Minimum Size of a Batch (will only launch DivUp(Num, MinBatchSize) Workers
ContextConstructor; Function to call to initialize each task context allocated for the operation
Body; Function to call from multiple threads
Flags; Used to customize the behavior of the ParallelFor if needed. Notes: Please add stats around to calls to parallel for and within your lambda as appropriate. Do not clog the task graph with long running tasks or tasks that block.
Definition at line 764 of file ParallelFor.h.
References TArray< InElementType, InAllocatorType >::AddUninitialized(), Flags, None, Num, and TArray< InElementType, InAllocatorType >::Reset().
ParallelForWithTaskContext() [3/5]
template<typename ContextType, typename ContextAllocatorType, typename FunctionType> void ParallelForWithTaskContext (const TCHAR * DebugName, TArray< ContextType, ContextAllocatorType > & OutContexts, int32 Num, int32 MinBatchSize, const FunctionType & Body, EParallelForFlags Flags = EParallelForFlags::None) inline
General purpose parallel for that uses the taskgraph.
This variant constructs for the caller a user-defined context object for each task that may get spawned to do work, and passes it on to the loop body to give it a task-local "workspace" that can be mutated without need for synchronization primitives.
Parameters
OutContexts; Array that will hold the user-defined, task-level context objects (allocated per parallel task)
DebugName; ProfilingScope and Debugname
Num; number of calls of Body; Body(0), Body(1)....Body(Num - 1)
MinBatchSize; Minimum Size of a Batch (will only launch DivUp(Num, MinBatchSize) Workers
Body; Function to call from multiple threads
Flags; Used to customize the behavior of the ParallelFor if needed. Notes: Please add stats around to calls to parallel for and within your lambda as appropriate. Do not clog the task graph with long running tasks or tasks that block.
Definition at line 792 of file ParallelFor.h.
References TArray< InElementType, InAllocatorType >::AddDefaulted(), Flags, None, Num, and TArray< InElementType, InAllocatorType >::Reset().
ParallelForWithTaskContext() [4/5]
template<typename ContextType, typename ContextAllocatorType, typename ContextConstructorType, typename FunctionType> void ParallelForWithTaskContext (TArray< ContextType, ContextAllocatorType > & OutContexts, int32 Num, const ContextConstructorType & ContextConstructor, const FunctionType & Body, EParallelForFlags Flags = EParallelForFlags::None) inline
General purpose parallel for that uses the taskgraph.
This variant constructs for the caller a user-defined context object for each task that may get spawned to do work, and passes it on to the loop body to give it a task-local "workspace" that can be mutated without need for synchronization primitives. For this variant, the user provides a callable to construct each context element.
Parameters
OutContexts; Array that will hold the user-defined, task-level context objects (allocated per parallel task)
Num; number of calls of Body; Body(0), Body(1)....Body(Num - 1)
ContextConstructor; Function to call to initialize each task context allocated for the operation
Body; Function to call from multiple threads
Flags; Used to customize the behavior of the ParallelFor if needed. Notes: Please add stats around to calls to parallel for and within your lambda as appropriate. Do not clog the task graph with long running tasks or tasks that block.
Definition at line 722 of file ParallelFor.h.
References Flags, None, Num, ParallelForWithTaskContext(), and TEXT.
ParallelForWithTaskContext() [5/5]
template<typename ContextType, typename ContextAllocatorType, typename FunctionType> void ParallelForWithTaskContext (TArray< ContextType, ContextAllocatorType > & OutContexts, int32 Num, const FunctionType & Body, EParallelForFlags Flags = EParallelForFlags::None) inline
General purpose parallel for that uses the taskgraph.
This variant constructs for the caller a user-defined context object for each task that may get spawned to do work, and passes it on to the loop body to give it a task-local "workspace" that can be mutated without need for synchronization primitives.
Parameters
OutContexts; Array that will hold the user-defined, task-level context objects (allocated per parallel task)
Num; number of calls of Body; Body(0), Body(1)....Body(Num - 1)
Body; Function to call from multiple threads
Flags; Used to customize the behavior of the ParallelFor if needed. Notes: Please add stats around to calls to parallel for and within your lambda as appropriate. Do not clog the task graph with long running tasks or tasks that block.
Definition at line 738 of file ParallelFor.h.
References TArray< InElementType, InAllocatorType >::AddDefaulted(), Flags, None, Num, TArray< InElementType, InAllocatorType >::Reset(), and TEXT.
Variable Documentation
GParallelForBackgroundYieldingTimeoutMs
int32 GParallelForBackgroundYieldingTimeoutMs extern
Referenced by ENUM_CLASS_FLAGS().
GParallelForDisableOversubscription
bool GParallelForDisableOversubscription extern
Referenced by ENUM_CLASS_FLAGS().