Unreal Engine 5.6 C++ API: S:/Development/U_E/UE_5.6/Engine/Plugins/Experimental/AnimNext/Source/AnimNext/Public/Param/ParamType.h File Reference
ParamType.h File Reference
#include "CoreMinimal.h"
#include "StructUtils/PropertyBag.h"
#include "Templates/SubclassOf.h"
#include "UObject/ObjectPtr.h"
#include "UObject/SoftObjectPtr.h"
#include "UObject/ReflectedTypeAccessors.h"
#include "Concepts/BaseStructureProvider.h"
#include "RigVMCore/RigVMTemplate.h"
#include "ParamType.generated.h"
Data Structures
struct UE::AnimNext::Private::TIsSoftClassPtr< T >
struct UE::AnimNext::Private::TIsSoftClassPtr< const TSoftClassPtr< T > >
struct UE::AnimNext::Private::TIsSoftClassPtr< const volatile TSoftClassPtr< T > >
struct UE::AnimNext::Private::TIsSoftClassPtr< TSoftClassPtr< T > >
struct UE::AnimNext::Private::TIsSoftClassPtr< volatile TSoftClassPtr< T > >
struct UE::AnimNext::Private::TIsSoftObjectPtr< T >
struct UE::AnimNext::Private::TIsSoftObjectPtr< const TSoftObjectPtr< T > >
struct UE::AnimNext::Private::TIsSoftObjectPtr< const volatile TSoftObjectPtr< T > >
struct UE::AnimNext::Private::TIsSoftObjectPtr< TSoftObjectPtr< T > >
struct UE::AnimNext::Private::TIsSoftObjectPtr< volatile TSoftObjectPtr< T > >
Namespaces
namespace UE
Utility functions for applying transformations to meshes.
namespace UE::AnimNext
Synchronization Role.
namespace UE::AnimNext::Private
namespace UE::AnimNext::UncookedOnly
Macros
#define UE_API ANIMNEXT_API
Functions
USTRUCT () struct FAnimNextParamType
Representation of a parameter's type.
Macro Definition Documentation
UE_API
#define UE_API ANIMNEXT_API
Definition at line 15 of file ParamType.h.
Function Documentation
USTRUCT()
USTRUCT ()
Representation of a parameter's type.
Serializable, but fairly heavyweight to pass around and compare. Faster comparisons and other operations can be performed on UE::AnimNext::FParamTypeHandle, but they cannot be serialized as they are not stable across runs.
Construct a parameter type from the passed in value, container and object type.
Pointer to object that defines the Enum, Struct, or Class.
Type of the value described by this parameter.
Type of the container described by this parameter.
Helper function for GetType
Helper function for IsValid
Get a parameter type based on the passed-in built-in type
Get the pointer to the object that defines the Enum, Struct, or Class.
Get the type of the value described by this parameter.
Get the type of the container described by this parameter.
Helper function returning the size of the type.
Returns
Size in bytes of the type.
Helper function returning the size of the value type. This is identical to GetSize for non containers
Returns
Size in bytes of the value type.
Helper function returning the alignment of the type.
Returns
Alignment of the type.
Helper function returning the alignment of the value type. This is identical to GetAlignment for non containers
Returns
Alignment of the value type.
Append a string representing this type to the supplied string builder
Get a string representing this type
Get a type from a string
Get a FRigVMTemplateArgumentType from this type
Construct a parameter type from the passed in FRigVMTemplateArgumentType.
Construct a parameter type from the passed in FProperty.
Equality operator
Inequality operator
Type hash for TMap storage
Returns
whether this type is explicitly none
whether this type actually describes a type
whether this type represents an object (object/class/softobject/softclass)
Definition at line 57 of file ParamType.h.
References GENERATED_BODY, TBaseStructureBase< T, bHasStaticStruct >::Get(), GetTypeHash(), HashCombineFast(), IsValid(), operator!=(), operator==(), StaticEnum(), ToString(), UE_API, UPROPERTY, TIsTArray< T >::Value, TIsTObjectPtr< T >::Value, TIsTSubclassOf< T >::Value, TIsUEnumClass< T >::Value, TModels< Concept, Args >::Value, UE::AnimNext::Private::TIsSoftClassPtr< T >::Value, and UE::AnimNext::Private::TIsSoftObjectPtr< T >::Value.