Unreal Engine 5.6 C++ API: S:/Development/U_E/UE_5.6/Engine/Plugins/Experimental/Mover/Source/Mover/Public/PhysicsMover/PathedMovement/PathedMovementTypes.h File Reference
PathedMovementTypes.h File Reference
#include "CoreMinimal.h"
#include "MoverTypes.h"
#include "Chaos/Core.h"
#include "PathedMovementTypes.generated.h"
Namespaces
namespace PathBlackboard
Functions
UENUM() enum class EPathedPhysicsPlaybackBehavior USTRUCT () struct FMutablePathedMovementProperties
Properties that can change during game-time and affect path movement calculations.
Variables
const FName PathBlackboard::TargetRelativeTransform = TEXT("TargetRelativeTransform")
Function Documentation
USTRUCT()
UENUM() enum class EPathedPhysicsPlaybackBehavior USTRUCT ()
Properties that can change during game-time and affect path movement calculations.
Split into its own struct because both the input and sync state structs want to hold onto these.
The server frame of the simulation when movement should/did actually begin Tracked this way so that we can set a future frame as the actual movement start frame to account for network latency, allowing clients and server to start at the same time irl. A value < 0 indicates that no movement is happening along the path.
Definition at line 33 of file PathedMovementTypes.h.
References Ar, GENERATED_BODY, INDEX_NONE, operator!=(), operator==(), Other, ToString(), and UPROPERTY.