Unreal Engine 5.6 C++ API: Runtime/Engine/Classes/GameFramework/Pawn.h File Reference
Pawn.h File Reference
#include "CoreMinimal.h"
#include "UObject/ObjectMacros.h"
#include "UObject/UObjectGlobals.h"
#include "Templates/SubclassOf.h"
#include "UObject/CoreNet.h"
#include "Engine/EngineTypes.h"
#include "GameFramework/Actor.h"
#include "AI/Navigation/NavAgentInterface.h"
#include "Pawn.generated.h"
Data Structures
class APawn
Functions
DECLARE_DYNAMIC_MULTICAST_SPARSE_DELEGATE_OneParam (FPawnRestartedSignature, APawn, ReceiveRestartedDelegate, APawn *, Pawn)
DECLARE_DYNAMIC_MULTICAST_SPARSE_DELEGATE_ThreeParams (FPawnControllerChangedSignature, APawn, ReceiveControllerChangedDelegate, APawn *, Pawn, AController *, OldController, AController *, NewController)
DECLARE_LOG_CATEGORY_EXTERN (LogDamage, Warning, All)
DECLARE_MULTICAST_DELEGATE_OneParam (FOnPawnBeginPlay, APawn *)
UCLASS ()
Pawn is the base class of all actors that can be possessed by players or AI.
Variables
meta =(ShortTooltip="A Pawn is an actor that can be 'possessed' and receive input from a controller.")
Function Documentation
DECLARE_DYNAMIC_MULTICAST_SPARSE_DELEGATE_OneParam()
DECLARE_DYNAMIC_MULTICAST_SPARSE_DELEGATE_OneParam (FPawnRestartedSignature , APawn , ReceiveRestartedDelegate , APawn * , Pawn)
References Pawn.
DECLARE_DYNAMIC_MULTICAST_SPARSE_DELEGATE_ThreeParams()
DECLARE_DYNAMIC_MULTICAST_SPARSE_DELEGATE_ThreeParams (FPawnControllerChangedSignature , APawn , ReceiveControllerChangedDelegate , APawn * , Pawn , AController * , OldController , AController * , NewController)
References Pawn.
DECLARE_LOG_CATEGORY_EXTERN()
DECLARE_LOG_CATEGORY_EXTERN (LogDamage , Warning , All)
References All, and Warning.
DECLARE_MULTICAST_DELEGATE_OneParam()
DECLARE_MULTICAST_DELEGATE_OneParam (FOnPawnBeginPlay , APawn *)
UCLASS()
UCLASS ()
Pawn is the base class of all actors that can be possessed by players or AI.
They are the physical representations of players and creatures in a level.
See also
https://docs.unrealengine.com/latest/INT/Gameplay/Framework/Pawn/
Variable Documentation
meta
meta =(ShortTooltip="A Pawn is an actor that can be 'possessed' and receive input from a controller.")
Definition at line 41 of file Pawn.h.
Referenced by APawn::UFUNCTION(), APawn::UFUNCTION(), APawn::UFUNCTION(), APawn::UFUNCTION(), APawn::UFUNCTION(), APawn::UFUNCTION(), APawn::UFUNCTION(), APawn::UFUNCTION(), APawn::UFUNCTION(), APawn::UFUNCTION(), APawn::UFUNCTION(), APawn::UPROPERTY(), and APawn::UPROPERTY().