Unreal Engine 5.6 C++ API: Runtime/Engine/Public/PhysicsPublic.h File Reference
PhysicsPublic.h File Reference
#include "CoreMinimal.h"
#include "Stats/Stats.h"
#include "Engine/EngineTypes.h"
#include "Misc/CoreMisc.h"
#include "Misc/App.h"
#include "EngineDefines.h"
#include "PhysicsInterfaceDeclaresCore.h"
#include "PhysicsPublicCore.h"
Data Structures
struct FCollisionNotifyInfo
One entry in the array of collision notifications pending execution at the end of the physics engine run.
class FKCachedConvexData
class FKCachedConvexDataElement
struct FKCachedPerTriData
class FKConvexGeomRenderInfo
class FPhysCommandHandler
Container used for physics tasks that need to be deferred from GameThread.
struct FPhysCommandHandler::FPhysPendingCommand
Command to execute when physics simulation is done.
class FPhysicsDelegates
Set of delegates to allowing hooking different parts of the physics engine.
struct FRigidBodyCollisionInfo
Information about a specific object involved in a rigid body collision.
Namespaces
namespace PhysCommand
Enumerations
enum PhysCommand::Type {
PhysCommand::Release , PhysCommand::ReleasePScene , PhysCommand::DeleteCPUDispatcher , PhysCommand::DeleteSimEventCallback ,
PhysCommand::DeleteContactModifyCallback , PhysCommand::DeleteCCDContactModifyCallback , PhysCommand::DeleteMbpBroadphaseCallback , PhysCommand::Max
}
Functions
void ClearForces_AssumesLocked (FBodyInstance *BodyInstance, bool bAllowSubstepping)
Clears all linear forces on the body.
void ClearTorques_AssumesLocked (FBodyInstance *BodyInstance, bool bAllowSubstepping)
Clears all torques on the body.
DECLARE_CYCLE_STAT_EXTERN (TEXT("FetchAndStart Time (all)"), STAT_TotalPhysicsTime, STATGROUP_Physics,)
Physics stats.
DECLARE_DELEGATE_TwoParams (FCalculateCustomPhysics, float, FBodyInstance *)
Delegate for applying custom physics forces upon the body.
DECLARE_DELEGATE_TwoParams (FCalculateCustomProjection, const FBodyInstance *, FTransform &)
Delegate for applying custom physics projection upon the body.
DECLARE_DWORD_COUNTER_STAT_EXTERN (TEXT("Cloth Actor Count"), STAT_NumCloths, STATGROUP_Physics, 1)
DECLARE_DWORD_COUNTER_STAT_EXTERN (TEXT("Simulated Cloth Verts"), STAT_NumClothVerts, STATGROUP_Physics, 1)
DECLARE_MULTICAST_DELEGATE_OneParam (FRecalculatedMassProperties, FBodyInstance *)
Delegate for when the mass properties of a body instance have been re-calculated.
void DeferredPhysResourceCleanup ()
Perform any deferred cleanup of resources (GPhysXPendingKillConvex etc)
FBox FindBodyBox (AActor *Actor, FName BoneName)
FTransform FindBodyTransform (AActor *Actor, FName BoneName)
bool InitGamePhys ()
FORCEINLINE bool PhysSingleThreadedMode ()
Return true if we should be running in single threaded mode, ala dedicated server.
void TermGamePhys ()
Variables
class FPhysCommandHandler * GPhysCommandHandler
Pointer to PhysX Command Handler.
Function Documentation
ClearForces_AssumesLocked()
void ClearForces_AssumesLocked (FBodyInstance * BodyInstance, bool bAllowSubstepping)
Clears all linear forces on the body.
ClearTorques_AssumesLocked()
void ClearTorques_AssumesLocked (FBodyInstance * BodyInstance, bool bAllowSubstepping)
Clears all torques on the body.
DECLARE_CYCLE_STAT_EXTERN()
DECLARE_CYCLE_STAT_EXTERN (TEXT("FetchAndStart Time (all)") , STAT_TotalPhysicsTime , STATGROUP_Physics)
Physics stats.
DECLARE_DELEGATE_TwoParams() [1/2]
DECLARE_DELEGATE_TwoParams (FCalculateCustomPhysics , float , FBodyInstance *)
Delegate for applying custom physics forces upon the body.
Can be passed to "AddCustomPhysics" so custom forces and torques can be calculated individually for every physics substep. The function provides delta time for a physics step and pointer to body instance upon which forces must be added.
Do not expect this callback to be called from the main game thread! It may get called from a physics simulation thread.
DECLARE_DELEGATE_TwoParams() [2/2]
DECLARE_DELEGATE_TwoParams (FCalculateCustomProjection , const FBodyInstance * , FTransform &)
Delegate for applying custom physics projection upon the body.
When this is set for the body instance, it will be called whenever component transformation is requested from the physics engine. If projection is required (for example, visual position of an object must be different to the one in physics engine, e.g. the box should not penetrate the wall visually) the transformation of body must be updated to account for it. Since this could be called many times by GetWorldTransform any expensive computations should be cached if possible.
DECLARE_DWORD_COUNTER_STAT_EXTERN() [1/2]
DECLARE_DWORD_COUNTER_STAT_EXTERN (TEXT("Cloth Actor Count") , STAT_NumCloths , STATGROUP_Physics , 1)
DECLARE_DWORD_COUNTER_STAT_EXTERN() [2/2]
DECLARE_DWORD_COUNTER_STAT_EXTERN (TEXT("Simulated Cloth Verts") , STAT_NumClothVerts , STATGROUP_Physics , 1)
References GPhysCommandHandler.
DECLARE_MULTICAST_DELEGATE_OneParam()
DECLARE_MULTICAST_DELEGATE_OneParam (FRecalculatedMassProperties , FBodyInstance *)
Delegate for when the mass properties of a body instance have been re-calculated.
This can be useful for systems that need to set specific physx settings on actors, or systems that rely on the mass information in some way
DeferredPhysResourceCleanup()
void DeferredPhysResourceCleanup ()
Perform any deferred cleanup of resources (GPhysXPendingKillConvex etc)
FindBodyBox()
FBox FindBodyBox (AActor * Actor, FName BoneName)
References Actor.
FindBodyTransform()
FTransform FindBodyTransform (AActor * Actor, FName BoneName)
References Actor.
InitGamePhys()
bool InitGamePhys ()
PhysSingleThreadedMode()
FORCEINLINE bool PhysSingleThreadedMode ()
Return true if we should be running in single threaded mode, ala dedicated server.
Definition at line 177 of file PhysicsPublic.h.
References FORCEINLINE, IsRunningDedicatedServer(), FAndroidMisc::NumberOfCores(), FParse::Param(), FApp::ShouldUseThreadingForPerformance(), FGenericPlatformProcess::SupportsMultithreading(), and TEXT.
TermGamePhys()
void TermGamePhys ()
Variable Documentation
GPhysCommandHandler
class FPhysCommandHandler* GPhysCommandHandler extern
Pointer to PhysX Command Handler.
Referenced by DECLARE_DWORD_COUNTER_STAT_EXTERN().