Unreal Engine 5.6 C++ API: Runtime/Engine/Public/Physics/PhysicsFiltering.h File Reference
PhysicsFiltering.h File Reference
#include "CoreMinimal.h"
#include "EngineDefines.h"
#include "PhysicsPublic.h"
#include "Physics/PhysicsInterfaceTypes.h"
#include "Chaos/ChaosEngineInterface.h"
Data Structures
struct FPhysicsFilterBuilder
Enumerations
enum { NumCollisionChannelBits = 5 }
enum { NumFilterDataFlagBits = 32 - NumExtraFilterBits - NumCollisionChannelBits }
enum EPhysXFilterDataFlags {
EPDF_SimpleCollision = 0x0001 , EPDF_ComplexCollision = 0x0002 , EPDF_CCD = 0x0004 , EPDF_ContactNotify = 0x0008 ,
EPDF_StaticShape = 0x0010 , EPDF_ModifyContacts = 0x0020 , EPDF_KinematicKinematicPairs = 0x0040
}
Set of flags stored in the PhysX FilterData.
Functions
uint32 CreateChannelAndFilter (ECollisionChannel CollisionChannel, FMaskFilter MaskFilter)
void CreateShapeFilterData (const uint8 MyChannel, const FMaskFilter MaskFilter, const int32 SourceObjectID, const FCollisionResponseContainer &ResponseToChannels, uint32 ComponentID, uint16 BodyIndex, FCollisionFilterData &OutQueryData, FCollisionFilterData &OutSimData, bool bEnableCCD, bool bEnableContactNotify, bool bStaticShape, bool bModifyContacts=false)
Utility for creating a FCollisionFilterData for filtering query (trace) and sim (physics) from the Unreal filtering info.
FCollisionResponseContainer ExtractQueryCollisionResponseContainer (const FCollisionFilterData &InQueryFilterData)
FCollisionResponseContainer ExtractSimCollisionResponseContainer (const FCollisionFilterData &InSimFilterData)
ECollisionChannel GetCollisionChannel (uint32 Word3)
ECollisionChannel GetCollisionChannelAndExtraFilter (uint32 Word3, FMaskFilter &OutMaskFilter)
void UpdateMaskFilter (uint32 &Word3, FMaskFilter NewMaskFilter)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
NumCollisionChannelBits
Definition at line 34 of file PhysicsFiltering.h.
anonymous enum
anonymous enum
Enumerator
NumFilterDataFlagBits
Definition at line 35 of file PhysicsFiltering.h.
EPhysXFilterDataFlags
enum EPhysXFilterDataFlags
Set of flags stored in the PhysX FilterData.
When this flag is saved in CreateShapeFilterData or CreateQueryFilterData, we only use 23 bits If you plan to use more than 23 bits, you'll also need to change the format of ShapeFilterData,QueryFilterData Make sure you also change preFilter/SimFilterShader where it's used
Enumerator
EPDF_SimpleCollision
EPDF_ComplexCollision
EPDF_CCD
EPDF_ContactNotify
EPDF_StaticShape
EPDF_ModifyContacts
EPDF_KinematicKinematicPairs
Definition at line 18 of file PhysicsFiltering.h.
Function Documentation
CreateChannelAndFilter()
uint32 CreateChannelAndFilter (ECollisionChannel CollisionChannel, FMaskFilter MaskFilter) inline
Definition at line 133 of file PhysicsFiltering.h.
References NumCollisionChannelBits, and NumFilterDataFlagBits.
CreateShapeFilterData()
void CreateShapeFilterData (const uint8 MyChannel, const FMaskFilter MaskFilter, const int32 SourceObjectID, const FCollisionResponseContainer & ResponseToChannels, uint32 ComponentID, uint16 BodyIndex, FCollisionFilterData & OutQueryData, FCollisionFilterData & OutSimData, bool bEnableCCD, bool bEnableContactNotify, bool bStaticShape, bool bModifyContacts = false) inline
Utility for creating a FCollisionFilterData for filtering query (trace) and sim (physics) from the Unreal filtering info.
Definition at line 94 of file PhysicsFiltering.h.
References FPhysicsFilterBuilder::ConditionalSetFlags(), EPDF_CCD, EPDF_ContactNotify, EPDF_ModifyContacts, EPDF_StaticShape, FPhysicsFilterBuilder::GetQueryData(), and FPhysicsFilterBuilder::GetSimData().
ExtractQueryCollisionResponseContainer()
FCollisionResponseContainer ExtractQueryCollisionResponseContainer (const FCollisionFilterData & InQueryFilterData) inline
Definition at line 165 of file PhysicsFiltering.h.
References UE_ARRAY_COUNT.
ExtractSimCollisionResponseContainer()
FCollisionResponseContainer ExtractSimCollisionResponseContainer (const FCollisionFilterData & InSimFilterData) inline
Definition at line 146 of file PhysicsFiltering.h.
References UE_ARRAY_COUNT.
GetCollisionChannel()
ECollisionChannel GetCollisionChannel (uint32 Word3) inline
Definition at line 120 of file PhysicsFiltering.h.
References NumCollisionChannelBits.
Referenced by GetCollisionChannelAndExtraFilter().
GetCollisionChannelAndExtraFilter()
ECollisionChannel GetCollisionChannelAndExtraFilter (uint32 Word3, FMaskFilter & OutMaskFilter) inline
Definition at line 126 of file PhysicsFiltering.h.
References GetCollisionChannel(), and NumExtraFilterBits.
UpdateMaskFilter()
void UpdateMaskFilter (uint32 & Word3, FMaskFilter NewMaskFilter) inline
Definition at line 139 of file PhysicsFiltering.h.
References NumExtraFilterBits.