Unreal Engine 5.6 C++ API: Runtime/Engine/Public/PrecomputedVolumetricLightmap.h File Reference
PrecomputedVolumetricLightmap.h File Reference
#include "UObject/WeakObjectPtr.h"
#include "CoreMinimal.h"
#include "Misc/Guid.h"
#include "Math/SHMath.h"
#include "Containers/DynamicRHIResourceArray.h"
#include "PixelFormat.h"
#include "Math/PackedVector.h"
#include "RHI.h"
#include "RenderResource.h"
#include "ShaderParameterStruct.h"
#include "GlobalShader.h"
Data Structures
class FCopyResidentBricksCS
class FCopyResidentBrickSHCoefficientsCS
class FMoveWholeIndirectionTextureCS
class FPatchIndirectionTextureCS
class FPrecomputedVolumetricLightmap
Represents the Volumetric Lightmap for a specific ULevel.
class FPrecomputedVolumetricLightmapData
Data for a Volumetric Lightmap, built during import from Lightmass.
class FRemoveSubLevelBricksCS
struct FVolumetricLightmapBasicBrickDataLayers
class FVolumetricLightmapBrickAtlas
struct FVolumetricLightmapBrickAtlas::Allocation
class FVolumetricLightmapBrickData
struct FVolumetricLightmapBrickTextureSet
class FVolumetricLightmapDataLayer
Functions
FVector ComputeBrickTextureCoordinate (FVector IndirectionDataSourceCoordinate, FIntVector IndirectionBrickOffset, int32 IndirectionBrickSize, int32 BrickSize)
FVector ComputeIndirectionCoordinate (FVector LookupPosition, const FBox &VolumeBounds, FIntVector IndirectionTextureDimensions)
template<typename T>
T ConvertFromLinearColor (const FLinearColor &InColor)
template<>
FColor ConvertFromLinearColor< FColor > (const FLinearColor &InColor)
template<>
FFixedRGBASigned8 ConvertFromLinearColor< FFixedRGBASigned8 > (const FLinearColor &InColor)
template<>
FFloat3Packed ConvertFromLinearColor< FFloat3Packed > (const FLinearColor &InColor)
template<>
uint8 ConvertFromLinearColor< uint8 > (const FLinearColor &InColor)
template<typename T>
FLinearColor ConvertToLinearColor (T InColor)
template<>
FLinearColor ConvertToLinearColor< FColor > (FColor InColor)
template<>
FLinearColor ConvertToLinearColor< FFixedRGBASigned8 > (FFixedRGBASigned8 InColor)
template<>
FLinearColor ConvertToLinearColor< FFloat3Packed > (FFloat3Packed InColor)
template<>
FLinearColor ConvertToLinearColor< uint8 > (uint8 InColor)
template<typename VoxelDataType>
FLinearColor FilteredVolumeLookup (FVector Coordinate, FIntVector DataDimensions, const VoxelDataType *Data)
template<typename VoxelDataType>
VoxelDataType FilteredVolumeLookupReconverted (FVector Coordinate, FIntVector DataDimensions, const VoxelDataType *Data)
template<typename VoxelDataType>
VoxelDataType NearestVolumeLookup (FVector Coordinate, FIntVector DataDimensions, const VoxelDataType *Data)
void SampleIndirectionTexture (FVector IndirectionDataSourceCoordinate, FIntVector IndirectionTextureDimensions, const uint8 *IndirectionTextureData, FIntVector &OutIndirectionBrickOffset, int32 &OutIndirectionBrickSize)
void SampleIndirectionTextureWithSubLevel (FVector IndirectionDataSourceCoordinate, FIntVector IndirectionTextureDimensions, const uint8 *IndirectionTextureData, const TArray< uint8 > &CPUSubLevelIndirectionTable, FIntVector &OutIndirectionBrickOffset, int32 &OutIndirectionBrickSize, int32 &OutSubLevelIndex)
Variables
static const float GPointFilteringThreshold = .001f
TGlobalResource< FVolumetricLightmapBrickAtlas > GVolumetricLightmapBrickAtlas
Function Documentation
ComputeBrickTextureCoordinate()
FVector ComputeBrickTextureCoordinate (FVector IndirectionDataSourceCoordinate, FIntVector IndirectionBrickOffset, int32 IndirectionBrickSize, int32 BrickSize) extern
References FVector.
ComputeIndirectionCoordinate()
FVector ComputeIndirectionCoordinate (FVector LookupPosition, const FBox & VolumeBounds, FIntVector IndirectionTextureDimensions) extern
References FVector.
ConvertFromLinearColor()
template<typename T> T ConvertFromLinearColor (const FLinearColor & InColor) inline
Definition at line 260 of file PrecomputedVolumetricLightmap.h.
Referenced by FilteredVolumeLookupReconverted().
ConvertFromLinearColor< FColor >()
template<> FColor ConvertFromLinearColor< FColor > (const FLinearColor & InColor) inline
Definition at line 272 of file PrecomputedVolumetricLightmap.h.
References FLinearColor::QuantizeRound().
ConvertFromLinearColor< FFixedRGBASigned8 >()
template<> FFixedRGBASigned8 ConvertFromLinearColor< FFixedRGBASigned8 > (const FLinearColor & InColor) inline
Definition at line 296 of file PrecomputedVolumetricLightmap.h.
ConvertFromLinearColor< FFloat3Packed >()
template<> FFloat3Packed ConvertFromLinearColor< FFloat3Packed > (const FLinearColor & InColor) inline
Definition at line 284 of file PrecomputedVolumetricLightmap.h.
ConvertFromLinearColor< uint8 >()
template<> uint8 ConvertFromLinearColor< uint8 > (const FLinearColor & InColor) inline
Definition at line 302 of file PrecomputedVolumetricLightmap.h.
References FMath::Clamp(), MAX_uint8, and FLinearColor::R.
ConvertToLinearColor()
template<typename T> FLinearColor ConvertToLinearColor (T InColor) inline
Definition at line 254 of file PrecomputedVolumetricLightmap.h.
Referenced by FilteredVolumeLookup().
ConvertToLinearColor< FColor >()
template<> FLinearColor ConvertToLinearColor< FColor > (FColor InColor) inline
Definition at line 266 of file PrecomputedVolumetricLightmap.h.
References FColor::ReinterpretAsLinear().
ConvertToLinearColor< FFixedRGBASigned8 >()
template<> FLinearColor ConvertToLinearColor< FFixedRGBASigned8 > (FFixedRGBASigned8 InColor) inline
Definition at line 290 of file PrecomputedVolumetricLightmap.h.
References FFixedRGBASigned8::ToLinearColor().
ConvertToLinearColor< FFloat3Packed >()
template<> FLinearColor ConvertToLinearColor< FFloat3Packed > (FFloat3Packed InColor) inline
Definition at line 278 of file PrecomputedVolumetricLightmap.h.
References FFloat3Packed::ToLinearColor().
ConvertToLinearColor< uint8 >()
template<> FLinearColor ConvertToLinearColor< uint8 > (uint8 InColor) inline
Definition at line 308 of file PrecomputedVolumetricLightmap.h.
References MAX_uint8, and Scale.
FilteredVolumeLookup()
template<typename VoxelDataType> FLinearColor FilteredVolumeLookup (FVector Coordinate, FIntVector DataDimensions, const VoxelDataType * Data)
Definition at line 317 of file PrecomputedVolumetricLightmap.h.
References FMath::Clamp(), ConvertToLinearColor(), FVolumetricLightmapDataLayer::Data, FVector, GPointFilteringThreshold, UE::Math::TIntVector3< InIntType >::X, UE::Math::TVector< T >::X, X, Y, UE::Math::TIntVector3< InIntType >::Y, UE::Math::TVector< T >::Y, Z, UE::Math::TIntVector3< InIntType >::Z, and UE::Math::TVector< T >::Z.
Referenced by FilteredVolumeLookupReconverted().
FilteredVolumeLookupReconverted()
template<typename VoxelDataType> VoxelDataType FilteredVolumeLookupReconverted (FVector Coordinate, FIntVector DataDimensions, const VoxelDataType * Data)
Definition at line 362 of file PrecomputedVolumetricLightmap.h.
References ConvertFromLinearColor(), FVolumetricLightmapDataLayer::Data, FilteredVolumeLookup(), FVector, GPointFilteringThreshold, UE::Math::TIntVector3< InIntType >::X, UE::Math::TVector< T >::X, UE::Math::TIntVector3< InIntType >::Y, UE::Math::TVector< T >::Y, UE::Math::TIntVector3< InIntType >::Z, and UE::Math::TVector< T >::Z.
NearestVolumeLookup()
template<typename VoxelDataType> VoxelDataType NearestVolumeLookup (FVector Coordinate, FIntVector DataDimensions, const VoxelDataType * Data)
Definition at line 381 of file PrecomputedVolumetricLightmap.h.
References FVolumetricLightmapDataLayer::Data, FVector, UE::Math::TIntVector3< InIntType >::X, UE::Math::TVector< T >::X, UE::Math::TIntVector3< InIntType >::Y, UE::Math::TVector< T >::Y, UE::Math::TIntVector3< InIntType >::Z, and UE::Math::TVector< T >::Z.
SampleIndirectionTexture()
void SampleIndirectionTexture (FVector IndirectionDataSourceCoordinate, FIntVector IndirectionTextureDimensions, const uint8 * IndirectionTextureData, FIntVector & OutIndirectionBrickOffset, int32 & OutIndirectionBrickSize) extern
References FVector.
SampleIndirectionTextureWithSubLevel()
void SampleIndirectionTextureWithSubLevel (FVector IndirectionDataSourceCoordinate, FIntVector IndirectionTextureDimensions, const uint8 * IndirectionTextureData, const TArray< uint8 > & CPUSubLevelIndirectionTable, FIntVector & OutIndirectionBrickOffset, int32 & OutIndirectionBrickSize, int32 & OutSubLevelIndex) extern
References FVector.
Variable Documentation
GPointFilteringThreshold
const float GPointFilteringThreshold = .001f inline static
Definition at line 314 of file PrecomputedVolumetricLightmap.h.
Referenced by FilteredVolumeLookup(), and FilteredVolumeLookupReconverted().
GVolumetricLightmapBrickAtlas
TGlobalResource<FVolumetricLightmapBrickAtlas> GVolumetricLightmapBrickAtlas extern