Unreal Engine 5.6 C++ API: Runtime/Core/Public/Templates/Projection.h File Reference
Projection.h File Reference
#include <type_traits>
Data Structures
struct UE::Core::Private::TProjectionMemberData< MemberType ClassType::* >
struct UE::Core::Private::TProjectionMemberFunction< FunctionType ClassType::* >
Namespaces
namespace UE
Utility functions for applying transformations to meshes.
namespace UE::Core
namespace UE::Core::Private
TAdderRef and TAdderReserverRef are type-erasing adapters that allow a function to add to (and reserve) a container without the function knowing about the specific type of the container.
Functions
template<typename Invocable0Type, typename... InvocableTypes>
constexpr auto Projection (Invocable0Type &&Invocable0, InvocableTypes &&... Invocables)
Projection() is a related function to Invoke(), in that it can be used to invoke an object with a set of arguments.
template<typename Class, typename MemberType>
constexpr bool UE::Core::Private::TIsMemberPointerToFunction (MemberType Class::*)
Function Documentation
Projection()
template<typename Invocable0Type, typename... InvocableTypes> auto Projection (Invocable0Type && Invocable0, InvocableTypes &&... Invocables) nodiscard constexpr
Projection() is a related function to Invoke(), in that it can be used to invoke an object with a set of arguments.
However, it works by transforming something invocable into something callable, i.e. can be called with a normal parenthesized set of arguments.
// These are equivalent: Projection(I)(Args...) Invoke(I, Args...).
... with the same advantages:
// Can accept member function pointers Invoke(&FObjType::Member, Obj); // equivalent to Obj.Member Invoke(&FObjType::Func, Obj, Args...); // equivalent to Obj.Func(Args...) Projection(&FObjType::Member)(Obj); // equivalent to Obj.Member Projection(&FObjType::Func)(Obj, Args...); // equivalent to Obj.Func(Args...)
// Can operate on pointers, including smart pointers Invoke(&FObjType::Member, ObjPtr); // equivalent to ObjPtr->Member Invoke(&FObjType::Func, ObjPtr, Args...); // equivalent to ObjPtr->Func(Args...) Projection(&FObjType::Member)(ObjPtr); // equivalent to ObjPtr->Member Projection(&FObjType::Func)(ObjPtr, Args...); // equivalent to ObjPtr->Func(Args...)
However, Projection() has some additional advantages:
Projection(I) returns I unchanged if it is already callable, meaning no redundant stepping in and out of many Invoke() calls in the debugger.
Projection(...) is variadic and can transform a sequence of invocables into a callable that invokes them one by one:
Projection(A, B, C)(Args...) Invoke(C, Invoke(B, Invoke(A, Args...)))
This allows users to pass a sequence of projections to an algorithm that takes a single projection:
struct FInner { FString Name; }; struct FOuter { FInner Inner; };
// Sort array of outers by the names of inner, Algo::SortBy(ArrayOfOuters, Projection(&FOuter::Inner, &FInner::Name));
Definition at line 107 of file Projection.h.
References Projection(), and UE::Core::Private::TIsMemberPointerToFunction().
Referenced by Algo::AllOf(), Algo::AnyOf(), Algo::AnyOf(), Algo::BinarySearchBy(), Algo::BinarySearchBy(), TraceServices::PagedArrayAlgo::BinarySearchClosestBy(), TraceServices::PagedArrayAlgo::BinarySearchClosestBy(), TraceServices::PagedArrayAlgoImpl::BinarySearchClosestInternal(), Algo::Private::Compare(), Algo::CompareBy(), Algo::CompareBy(), Algo::HeapifyBy(), Algo::HeapifyBy(), AlgoImpl::HeapSiftDown(), AlgoImpl::HeapSiftUp(), Algo::HeapSortBy(), Algo::HeapSortBy(), Algo::Private::Includes(), Algo::IncludesBy(), Algo::IncludesBy(), Algo::IntroSortBy(), Algo::IntroSortBy(), Algo::IsHeapBy(), Algo::IsHeapBy(), AlgoImpl::IsHeapInternal(), UE::Math::TCapsuleShape< T >::IsInside(), Algo::IsSortedBy(), Algo::IsSortedBy(), UE::String::JoinBy(), UE::String::JoinByTo(), UE::String::JoinQuotedBy(), UE::String::JoinQuotedByTo(), UE::String::JoinTupleBy(), UE::String::JoinTupleByTo(), UE::String::JoinTupleQuotedBy(), UE::String::JoinTupleQuotedByTo(), AlgoImpl::LegacySortInternal(), Algo::LowerBoundBy(), Algo::LowerBoundBy(), TraceServices::PagedArrayAlgo::LowerBoundBy(), TraceServices::PagedArrayAlgo::LowerBoundBy(), AlgoImpl::LowerBoundInternal(), TraceServices::PagedArrayAlgoImpl::LowerBoundInternal(), AlgoImpl::Merge(), Algo::Private::Mismatch(), Algo::MismatchBy(), Algo::MismatchBy(), Algo::NoneOf(), Algo::NoneOf(), Projection(), AlgoImpl::StableSortInternal(), Algo::UpperBoundBy(), Algo::UpperBoundBy(), TraceServices::PagedArrayAlgo::UpperBoundBy(), TraceServices::PagedArrayAlgo::UpperBoundBy(), AlgoImpl::UpperBoundInternal(), TraceServices::PagedArrayAlgoImpl::UpperBoundInternal(), and USTRUCT().