Unreal Engine 5.6 C++ API: Runtime/CoreUObject/Public/UObject/ReflectedTypeAccessors.h File Reference
ReflectedTypeAccessors.h File Reference
Functions
template<typename ClassType>
UClass * StaticClass ()
template<typename EnumType>
UEnum * StaticEnum ()
template<typename StructType>
UScriptStruct * StaticStruct ()
Function Documentation
StaticClass()
template<typename ClassType> UClass * StaticClass () inline
Definition at line 13 of file ReflectedTypeAccessors.h.
Referenced by FActorIterator::FActorIterator(), FObjectSubsystemCollection< TBaseType >::FObjectSubsystemCollection(), FSelectedActorIterator::FSelectedActorIterator(), FSubsystemCollection< TBaseType >::FSubsystemCollection(), TActorDescList< DescType >::TConstIterator< ActorType >::TConstIterator(), TFieldIterator< T >::TFieldIterator(), TActorDescList< DescType >::TIterator< ActorType >::TIterator(), TObjectIterator< UObject >::TObjectIterator(), TObjectIterator< UObject >::TObjectIterator(), TPropertyValueIterator< T >::TPropertyValueIterator(), UClassProperty::UClassProperty(), UClassProperty::UClassProperty(), USoftClassProperty::USoftClassProperty(), USoftClassProperty::USoftClassProperty(), FGraphActionListBuilderBase::CreateTemplateNode(), UMovieSceneEasingExternalCurve::GetDisplayName(), SClassPropertyEntryBox::SLATE_BEGIN_ARGS(), SObjectPropertyEntryBox::SLATE_BEGIN_ARGS(), and UGameplayAbilitiesDeveloperSettings::UPROPERTY().
StaticEnum()
template<typename EnumType> UEnum * StaticEnum ()
Referenced by FPropertyBagSetRef::AddValueEnum(), UE::Geometry::UVEditorAnalytics::AnalyticsEventAttributeEnum(), RigVMPythonUtils::EnumValueToPythonString(), FRigVMUnitNodeCreatedContext::FindFirstVariableOfType(), FLiveLinkProvider::GetAnnotations(), UE::Dataflow::Private::GetAttributeFromEnumAsName(), UE::PixelStreaming2::GetCVarStringFromEnum(), UMovieSceneBuiltInEasingFunction::GetDisplayName(), UE::PixelStreaming2::GetEnumFromCVar(), GetOverriddenOperationFromString(), GetOverriddenOperationString(), GetStaticMaterialParameterTypeEnum(), FRigVMRegistry_NoLock::GetTypeIndex_NoLock(), FPropertyBagArrayRef::GetValueEnum(), FRigVMMemoryHandle::IsEnum(), FRigVMMemoryHandle::IsEnumArray(), UE::StateTree::PropertyRefHelpers::Validator< T, typename TEnableIf< TIsEnum< T >::Value >::Type >::IsValid(), FMovieSceneBlendTypeFieldIterator::MaxValidOffset(), FPropertyBagArrayRef::SetValueEnum(), UE::CoreUObject::TestEqual(), UE::CoreUObject::TestNotEqual(), and USTRUCT().
StaticStruct()
template<typename StructType> UScriptStruct * StaticStruct () inline
Definition at line 18 of file ReflectedTypeAccessors.h.
Referenced by FConstStructArrayView::FConstStructArrayView(), FConstStructArrayView::FConstStructArrayView(), FStructArrayView::FStructArrayView(), FStructArrayView::FStructArrayView(), TConstStructView< BaseStructT >::TConstStructView(), TConstStructView< BaseStructT >::TConstStructView(), TMovieSceneChannelHandle< ChannelType >::TMovieSceneChannelHandle(), UE::MovieScene::TNamedChannelOverrideProviderTraits< OverrideChannelTypes >::TNamedChannelOverrideProviderTraits(), TStructView< BaseStructT >::TStructView(), TStructView< BaseStructT >::TStructView(), UE::Net::TStructNetTokenDataStoreHelper< T >::SerializeHelper(), and USTRUCT().