Unreal Engine 5.6 C++ API: Runtime/RenderCore/Public/RenderGraphUtils.h File Reference
RenderGraphUtils.h File Reference
#include "Containers/Array.h"
#include "Containers/ArrayView.h"
#include "Containers/ContainersFwd.h"
#include "Containers/UnrealString.h"
#include "HAL/UnrealMemory.h"
#include "Math/Color.h"
#include "Math/IntPoint.h"
#include "Math/IntRect.h"
#include "Math/IntVector.h"
#include "Math/UnrealMathSSE.h"
#include "Math/Vector2D.h"
#include "Math/Vector4.h"
#include "Misc/AssertionMacros.h"
#include "Misc/EnumClassFlags.h"
#include "Misc/Optional.h"
#include "RHI.h"
#include "RHICommandList.h"
#include "RHIDefinitions.h"
#include "RenderGraphAllocator.h"
#include "RenderGraphBuilder.h"
#include "RenderGraphDefinitions.h"
#include "RenderGraphEvent.h"
#include "RenderGraphResources.h"
#include "RendererInterface.h"
#include "Shader.h"
#include "ShaderParameterMacros.h"
#include "ShaderParameterStruct.h"
#include "Stats/Stats.h"
#include "Templates/Function.h"
#include "Templates/Invoke.h"
#include "Templates/RefCounting.h"
#include "Templates/UnrealTemplate.h"
#include "Templates/UnrealTypeTraits.h"
#include "PipelineStateCache.h"
#include <initializer_list>
Data Structures
struct FRDGDrawTextureInfo
class FRDGExternalAccessQueue
Batches up RDG external resource access mode requests and submits them all at once to RDG.
struct FRDGExternalAccessQueue::FResource
struct FRDGTextureClearInfo
struct FRDGTextureMSAA
Simple pair of RDG textures used for MSAA.
struct FRDGUploadData< InElementType >
Helper class to allocate data from a GraphBuilder in order to upload said data to an RDG resource.
class FReadbackBufferParameters
struct FReadbackBufferParameters::FTypeInfo
struct FReadbackBufferParameters::zzFirstMemberId
struct FReadbackBufferParameters::zzNextMemberIdBuffer
class FReadbackTextureParameters
struct FReadbackTextureParameters::FTypeInfo
struct FReadbackTextureParameters::zzFirstMemberId
struct FReadbackTextureParameters::zzNextMemberIdTexture
struct FTextureRenderTargetBinding
Namespaces
namespace FComputeShaderUtils
All utils for compute shaders.
namespace FComputeShaderUtils::Private
Typedefs
using FRDGDispatchLateParamCallback = TFunction<void()>
Functions
RENDERCORE_API void AddClearDepthStencilPass (FRDGBuilder &GraphBuilder, FRDGTextureRef Texture, bool bClearDepth, float Depth, bool bClearStencil, uint8 Stencil)
Adds a render graph pass to clear a depth stencil target.
RENDERCORE_API void AddClearDepthStencilPass (FRDGBuilder &GraphBuilder, FRDGTextureRef Texture, ERenderTargetLoadAction DepthLoadAction=ERenderTargetLoadAction::EClear, ERenderTargetLoadAction StencilLoadAction=ERenderTargetLoadAction::EClear)
Adds a render graph pass to clear a depth stencil target to its optimized clear value using a raster pass.
RENDERCORE_API void AddClearRenderTargetPass (FRDGBuilder &GraphBuilder, FRDGTextureRef Texture)
Adds a render graph pass to clear a render target to its clear value (single mip, single slice)
RENDERCORE_API void AddClearRenderTargetPass (FRDGBuilder &GraphBuilder, FRDGTextureRef Texture, const FLinearColor &ClearColor)
Adds a render graph pass to clear a render target (single mip, single slice).
RENDERCORE_API void AddClearRenderTargetPass (FRDGBuilder &GraphBuilder, FRDGTextureRef Texture, const FLinearColor &ClearColor, FIntRect Viewport)
Adds a render graph pass to clear a part of a render target (single mip, single slice).
RENDERCORE_API void AddClearRenderTargetPass (FRDGBuilder &GraphBuilder, FRDGTextureRef Texture, const FRDGTextureClearInfo &TextureClearInfo)
Adds a render graph pass to clear a render target to its clear value.
RENDERCORE_API void AddClearStencilPass (FRDGBuilder &GraphBuilder, FRDGTextureRef Texture)
Adds a render graph pass to clear the stencil portion of a depth / stencil target to its fast clear value.
RENDERCORE_API void AddClearUAVFloatPass (FRDGBuilder &GraphBuilder, FRDGBufferUAVRef BufferUAV, float Value, ERDGPassFlags ComputePassFlags=ERDGPassFlags::Compute)
RENDERCORE_API void AddClearUAVPass (FRDGBuilder &GraphBuilder, ERHIFeatureLevel::Type FeatureLevel, FRDGTextureUAVRef TextureUAV, const uint32(&ClearValues)[4], FRDGBufferSRVRef RectMinMaxBufferSRV, uint32 NumRects)
Clears parts of UAV specified by an array of screen rects.
RENDERCORE_API void AddClearUAVPass (FRDGBuilder &GraphBuilder, FRDGBufferUAVRef BufferUAV, uint32 Value, ERDGPassFlags ComputePassFlags=ERDGPassFlags::Compute)
Adds a render graph pass to clear a texture or buffer UAV with a single typed value.
RENDERCORE_API void AddClearUAVPass (FRDGBuilder &GraphBuilder, FRDGTextureUAVRef TextureUAV, const FIntPoint &ClearValue, ERDGPassFlags ComputePassFlags=ERDGPassFlags::Compute)
RENDERCORE_API void AddClearUAVPass (FRDGBuilder &GraphBuilder, FRDGTextureUAVRef TextureUAV, const FLinearColor &ClearColor, ERDGPassFlags ComputePassFlags=ERDGPassFlags::Compute)
RENDERCORE_API void AddClearUAVPass (FRDGBuilder &GraphBuilder, FRDGTextureUAVRef TextureUAV, const float(&ClearValues)[4], ERDGPassFlags ComputePassFlags=ERDGPassFlags::Compute)
RENDERCORE_API void AddClearUAVPass (FRDGBuilder &GraphBuilder, FRDGTextureUAVRef TextureUAV, const FUintVector4 &ClearValues, ERDGPassFlags ComputePassFlags=ERDGPassFlags::Compute)
RENDERCORE_API void AddClearUAVPass (FRDGBuilder &GraphBuilder, FRDGTextureUAVRef TextureUAV, const FVector &ClearValue, ERDGPassFlags ComputePassFlags=ERDGPassFlags::Compute)
RENDERCORE_API void AddClearUAVPass (FRDGBuilder &GraphBuilder, FRDGTextureUAVRef TextureUAV, const FVector2D &ClearValue, ERDGPassFlags ComputePassFlags=ERDGPassFlags::Compute)
RENDERCORE_API void AddClearUAVPass (FRDGBuilder &GraphBuilder, FRDGTextureUAVRef TextureUAV, const FVector4 &ClearValues, ERDGPassFlags ComputePassFlags=ERDGPassFlags::Compute)
RENDERCORE_API void AddClearUAVPass (FRDGBuilder &GraphBuilder, FRDGTextureUAVRef TextureUAV, const uint32(&ClearValues)[4], ERDGPassFlags ComputePassFlags=ERDGPassFlags::Compute)
RENDERCORE_API void AddClearUAVPass (FRDGBuilder &GraphBuilder, FRDGTextureUAVRef TextureUAV, float ClearValue, ERDGPassFlags ComputePassFlags=ERDGPassFlags::Compute)
RENDERCORE_API void AddClearUAVPass (FRDGBuilder &GraphBuilder, FRDGTextureUAVRef TextureUAV, uint32 ClearValue, ERDGPassFlags ComputePassFlags=ERDGPassFlags::Compute)
RENDERCORE_API void AddCopyBufferPass (FRDGBuilder &GraphBuilder, FRDGBufferRef DstBuffer, FRDGBufferRef SrcBuffer)
RENDERCORE_API void AddCopyBufferPass (FRDGBuilder &GraphBuilder, FRDGBufferRef DstBuffer, uint64 DstOffset, FRDGBufferRef SrcBuffer, uint64 SrcOffset, uint64 NumBytes)
Adds a render graph pass to copy SrcBuffer content into DstBuffer.
RENDERCORE_API void AddCopyTexturePass (FRDGBuilder &GraphBuilder, FRDGTextureRef InputTexture, FRDGTextureRef OutputTexture, const FRHICopyTextureInfo &CopyInfo)
Adds a render graph pass to copy a region from one texture to another.
void AddCopyTexturePass (FRDGBuilder &GraphBuilder, FRDGTextureRef InputTexture, FRDGTextureRef OutputTexture, FIntPoint InputPosition=FIntPoint::ZeroValue, FIntPoint OutputPosition=FIntPoint::ZeroValue, FIntPoint Size=FIntPoint::ZeroValue)
Simpler variant of the above function for 2D textures.
void AddDispatchToRHIThreadPass (FRDGBuilder &GraphBuilder)
RENDERCORE_API void AddDrawTexturePass (FRDGBuilder &GraphBuilder, const FGlobalShaderMap *ShaderMap, FRDGTextureRef InputTexture, FRDGTextureRef OutputTexture, const FRDGDrawTextureInfo &DrawInfo)
RENDERCORE_API void AddEnqueueCopyPass (FRDGBuilder &GraphBuilder, FRHIGPUBufferReadback *Readback, FRDGBufferRef SourceBuffer, uint32 NumBytes)
Adds a pass to readback contents of an RDG buffer.
RENDERCORE_API void AddEnqueueCopyPass (FRDGBuilder &GraphBuilder, FRHIGPUTextureReadback *Readback, FRDGTextureRef SourceTexture, FResolveRect Rect=FResolveRect())
Adds a pass to readback contents of an RDG texture.
RENDERCORE_API FRDGBufferRef FComputeShaderUtils::AddIndirectArgsSetupCsPass1D (FRDGBuilder &GraphBuilder, ERHIFeatureLevel::Type FeatureLevel, FRDGBuffer *InputCountBuffer, const TCHAR *OutputBufferName, uint32 Divisor, uint32 InputCountOffset=0U, uint32 Multiplier=1U)
Create and set up an 1D indirect dispatch argument from some GPU-side integer in a buffer (InputCountBuffer).
template<typename ExecuteLambdaType>
void AddPass (FRDGBuilder &GraphBuilder, FRDGEventName &&Name, ExecuteLambdaType &&ExecuteLambda)
Helper functions to add parameterless passes to the graph.
template<typename TShaderClass>
FRDGPassRef FComputeShaderUtils::AddPass (FRDGBuilder &GraphBuilder, FRDGEventName &&PassName, const TShaderRef< TShaderClass > &ComputeShader, typename TShaderClass::FParameters *Parameters, FIntVector GroupCount)
template<typename TShaderClass>
FRDGPassRef FComputeShaderUtils::AddPass (FRDGBuilder &GraphBuilder, FRDGEventName &&PassName, const TShaderRef< TShaderClass > &ComputeShader, typename TShaderClass::FParameters *Parameters, FRDGBufferRef IndirectArgsBuffer, uint32 IndirectArgsOffset, FRDGDispatchLateParamCallback &&DispatchLateParamCallback=FRDGDispatchLateParamCallback())
template<typename TShaderClass>
FRDGPassRef FComputeShaderUtils::AddPass (FRDGBuilder &GraphBuilder, FRDGEventName &&PassName, const TShaderRef< TShaderClass > &ComputeShader, typename TShaderClass::FParameters *Parameters, FRDGDispatchGroupCountCallback &&GroupCountCallback)
template<typename TShaderClass>
FRDGPassRef FComputeShaderUtils::AddPass (FRDGBuilder &GraphBuilder, FRDGEventName &&PassName, ERDGPassFlags PassFlags, const TShaderRef< TShaderClass > &ComputeShader, const FShaderParametersMetadata *ParametersMetadata, typename TShaderClass::FParameters *Parameters, FIntVector GroupCount)
Dispatch a compute shader to render graph builder with its parameters.
template<typename TShaderClass>
FRDGPassRef FComputeShaderUtils::AddPass (FRDGBuilder &GraphBuilder, FRDGEventName &&PassName, ERDGPassFlags PassFlags, const TShaderRef< TShaderClass > &ComputeShader, const FShaderParametersMetadata *ParametersMetadata, typename TShaderClass::FParameters *Parameters, FRDGDispatchGroupCountCallback &&GroupCountCallback)
Dispatch a compute shader to render graph builder with its parameters.
template<typename TShaderClass>
FRDGPassRef FComputeShaderUtils::AddPass (FRDGBuilder &GraphBuilder, FRDGEventName &&PassName, ERDGPassFlags PassFlags, const TShaderRef< TShaderClass > &ComputeShader, typename TShaderClass::FParameters *Parameters, FIntVector GroupCount)
template<typename TShaderClass>
FRDGPassRef FComputeShaderUtils::AddPass (FRDGBuilder &GraphBuilder, FRDGEventName &&PassName, ERDGPassFlags PassFlags, const TShaderRef< TShaderClass > &ComputeShader, typename TShaderClass::FParameters *Parameters, FRDGBufferRef IndirectArgsBuffer, uint32 IndirectArgsOffset, FRDGDispatchLateParamCallback &&DispatchLateParamCallback=FRDGDispatchLateParamCallback())
Dispatch a compute shader to render graph builder with its parameters.
template<typename ExecuteLambdaType>
void AddPassIfDebug (FRDGBuilder &GraphBuilder, FRDGEventName &&Name, ExecuteLambdaType &&ExecuteLambda)
template<typename ExecuteLambdaType>
void AddReadbackBufferPass (FRDGBuilder &GraphBuilder, FRDGEventName &&Name, FRDGBufferRef Buffer, ExecuteLambdaType &&ExecuteLambda)
template<typename ExecuteLambdaType>
void AddReadbackTexturePass (FRDGBuilder &GraphBuilder, FRDGEventName &&Name, FRDGTextureRef Texture, ExecuteLambdaType &&ExecuteLambda)
RENDERCORE_API void AddResummarizeHTilePass (FRDGBuilder &GraphBuilder, FRDGTextureRef DepthTexture)
Adds a render graph pass to resummarize the htile plane.
template<typename TShaderClass>
void FComputeShaderUtils::Private::AfterDispatch (FRHIComputeCommandList &RHICmdList, const TShaderRef< TShaderClass > &ComputeShader)
RENDERCORE_API TRefCountPtr< FRDGPooledBuffer > AllocatePooledBuffer (const FRDGBufferDesc &Desc, const TCHAR *Name, ERDGPooledBufferAlignment Alignment=ERDGPooledBufferAlignment::Page)
RENDERCORE_API bool AllocatePooledBuffer (const FRDGBufferDesc &Desc, TRefCountPtr< FRDGPooledBuffer > &Out, const TCHAR *Name, ERDGPooledBufferAlignment Alignment=ERDGPooledBufferAlignment::Page)
TRefCountPtr< FRDGPooledBuffer > AllocatePooledBufferCurrentLLMTag (FRHICommandListBase &RHICmdList, const FRDGBufferDesc &Desc, const TCHAR *Name, ERDGPooledBufferAlignment Alignment=ERDGPooledBufferAlignment::Page)
RENDERCORE_API TRefCountPtr< IPooledRenderTarget > AllocatePooledTexture (const FRDGTextureDesc &Desc, const TCHAR *Name)
RENDERCORE_API bool AllocatePooledTexture (const FRDGTextureDesc &Desc, TRefCountPtr< IPooledRenderTarget > &Out, const TCHAR *Name)
template<typename TShaderClass>
void ClearUnusedGraphResources (const TShaderRef< TShaderClass > &Shader, const FShaderParametersMetadata *ParametersMetadata, typename TShaderClass::FParameters *InoutParameters, std::initializer_list< FRDGResourceRef > ExcludeList={})
template<typename TShaderClass>
void ClearUnusedGraphResources (const TShaderRef< TShaderClass > &Shader, typename TShaderClass::FParameters *InoutParameters, std::initializer_list< FRDGResourceRef > ExcludeList={})
template<typename TShaderClassA, typename TShaderClassB, typename TPassParameterStruct>
void ClearUnusedGraphResources (const TShaderRef< TShaderClassA > &ShaderA, const TShaderRef< TShaderClassB > &ShaderB, TPassParameterStruct *InoutParameters, std::initializer_list< FRDGResourceRef > ExcludeList={})
RENDERCORE_API void ClearUnusedGraphResourcesImpl (const FShaderParameterBindings &ShaderBindings, const FShaderParametersMetadata *ParametersMetadata, void *InoutParameters, std::initializer_list< FRDGResourceRef > ExcludeList)
Clears all render graph tracked resources that are not bound by a shader.
RENDERCORE_API void ClearUnusedGraphResourcesImpl (TArrayView< const FShaderParameterBindings * > ShaderBindingsList, const FShaderParametersMetadata *ParametersMetadata, void *InoutParameters, std::initializer_list< FRDGResourceRef > ExcludeList)
Similar to the function above, but takes a list of shader bindings and only clears if none of the shaders contain the resource.
const TRefCountPtr< FRDGPooledBuffer > & ConvertToExternalAccessBuffer (FRDGBuilder &GraphBuilder, FRDGBuffer *Buffer, ERHIAccess Access=ERHIAccess::SRVMask, ERHIPipeline Pipelines=ERHIPipeline::Graphics)
const TRefCountPtr< FRDGPooledBuffer > & ConvertToExternalAccessBuffer (FRDGBuilder &GraphBuilder, FRDGExternalAccessQueue &ExternalAccessQueue, FRDGBuffer *Buffer, ERHIAccess Access=ERHIAccess::SRVMask, ERHIPipeline Pipelines=ERHIPipeline::Graphics)
const TRefCountPtr< IPooledRenderTarget > & ConvertToExternalAccessTexture (FRDGBuilder &GraphBuilder, FRDGExternalAccessQueue &ExternalAccessQueue, FRDGTexture *Texture, ERHIAccess Access=ERHIAccess::SRVMask, ERHIPipeline Pipelines=ERHIPipeline::Graphics)
const TRefCountPtr< IPooledRenderTarget > & ConvertToExternalAccessTexture (FRDGBuilder &GraphBuilder, FRDGTexture *Texture, ERHIAccess Access=ERHIAccess::SRVMask, ERHIPipeline Pipelines=ERHIPipeline::Graphics)
template<typename ElementType>
FRDGBufferRef CreateByteAddressBuffer (FRDGBuilder &GraphBuilder, const TCHAR *Name, const FRDGUploadData< ElementType > &InitialData)
RENDERCORE_API FRDGBufferRef CreateByteAddressBuffer (FRDGBuilder &GraphBuilder, const TCHAR *Name, FRDGBufferNumElementsCallback &&NumElementsCallback, FRDGBufferInitialDataCallback &&InitialDataCallback, FRDGBufferInitialDataSizeCallback &&InitialDataSizeCallback)
A variant where NumElements, InitialData, and InitialDataSize are supplied through callbacks.
template<typename GetArrayRefCallback, typename Type = TInvokeResult_T<GetArrayRefCallback>>
FRDGBufferRef CreateByteAddressBuffer (FRDGBuilder &GraphBuilder, const TCHAR *Name, GetArrayRefCallback &&ArrayCallback)
Same as the previous function but where the type of the array is automatically inferred, so we can do : TArray<FSomeType> Array = GraphBuilder.AllocArray<...>(); CreateByteAddressBuffer(..., [&]() -> auto&{ return Array; });.
template<typename ElementType, typename AllocatorType>
FRDGBufferRef CreateByteAddressBuffer (FRDGBuilder &GraphBuilder, const TCHAR *Name, TArray< ElementType, AllocatorType > &&InitialData)
Helper to create a byte address buffer with initial data from a TArray with move semantics, this can be cheaper as it guarantees the lifetimes of the data & permits copy-free upload.
template<typename ElementType>
FRDGBufferRef CreateByteAddressBuffer (FRDGBuilder &GraphBuilder, const TCHAR *Name, TConstArrayView< ElementType > InitialData, ERDGInitialDataFlags InitialDataFlags=ERDGInitialDataFlags::None)
Helper to create a byte address buffer with initial data from a TConstArrayView.
RENDERCORE_API FRDGBufferRef CreateByteAddressBuffer (FRDGBuilder &GraphBuilder, const TCHAR *Name, uint32 NumBytes, const void *InitialData, uint64 InitialDataSize, ERDGInitialDataFlags InitialDataFlags=ERDGInitialDataFlags::None)
Creates a byte address buffer with initial data by creating an upload pass.
template<typename ArrayType>
FRDGBufferRef CreateByteAddressBuffer_Impl (FRDGBuilder &GraphBuilder, const TCHAR *Name, TRDGBufferArrayCallback< ArrayType > &&ArrayCallback)
A variant where the TArray is supplied through callbacks.
template<typename ElementType, typename AllocatorType>
FRDGBufferRef CreateByteAddressUploadBuffer (FRDGBuilder &GraphBuilder, const TCHAR *Name, const TArray< ElementType, AllocatorType > &InitialData, ERDGInitialDataFlags InitialDataFlags=ERDGInitialDataFlags::None)
Helper to create a byte address upload buffer with initial data from a TArray.
FRDGBufferRef CreateByteAddressUploadBuffer (FRDGBuilder &GraphBuilder, const TCHAR *Name, FRDGBufferNumElementsCallback &&NumElementsCallback, FRDGBufferInitialDataCallback &&InitialDataCallback, FRDGBufferInitialDataSizeCallback &&InitialDataSizeCallback)
A variant where NumElements, InitialData, and InitialDataSize are supplied through callbacks.
template<typename GetArrayRefCallback, typename Type = TInvokeResult_T<GetArrayRefCallback>>
FRDGBufferRef CreateByteAddressUploadBuffer (FRDGBuilder &GraphBuilder, const TCHAR *Name, GetArrayRefCallback &&ArrayCallback)
Same as the previous function but where the type of the array is automatically inferred, so we can do : TArray<FSomeType> Array = GraphBuilder.AllocArray<...>(); CreateByteAddressBuffer(..., [&]() -> auto&{ return Array; });.
template<typename ArrayType>
FRDGBufferRef CreateByteAddressUploadBuffer_Impl (FRDGBuilder &GraphBuilder, const TCHAR *Name, TRDGBufferArrayCallback< ArrayType > &&ArrayCallback)
A variant where the TArray is supplied through callbacks.
template<typename ElementType>
FRDGBufferRef CreateStructuredBuffer (FRDGBuilder &GraphBuilder, const TCHAR *Name, const FRDGUploadData< ElementType > &InitialData)
template<typename ElementType, typename AllocatorType>
FRDGBufferRef CreateStructuredBuffer (FRDGBuilder &GraphBuilder, const TCHAR *Name, const TArray< ElementType, AllocatorType > &InitialData, ERDGInitialDataFlags InitialDataFlags=ERDGInitialDataFlags::None)
Helper to create a structured buffer with initial data from a TArray.
template<typename GetArrayRefCallback, typename Type = TInvokeResult_T<GetArrayRefCallback>>
FRDGBufferRef CreateStructuredBuffer (FRDGBuilder &GraphBuilder, const TCHAR *Name, GetArrayRefCallback &&ArrayCallback)
Same as the previous function but where the type of the array is automatically inferred, so we can do : TArray<FSomeType>& Array = GraphBuilder.AllocArray<...>(); CreateStructuredBuffer(..., [&]() -> auto&{ return Array; });.
template<typename ElementType, typename AllocatorType>
FRDGBufferRef CreateStructuredBuffer (FRDGBuilder &GraphBuilder, const TCHAR *Name, TArray< ElementType, AllocatorType > &&InitialData)
Helper to create a structured buffer with initial data from a TArray with move semantics, this can be cheaper as it guarantees the lifetimes of the data & permits copy-free upload.
template<typename ElementType>
FRDGBufferRef CreateStructuredBuffer (FRDGBuilder &GraphBuilder, const TCHAR *Name, TConstArrayView< ElementType > InitialData, ERDGInitialDataFlags InitialDataFlags=ERDGInitialDataFlags::None)
Helper to create a structured buffer with initial data from a TConstArrayView.
RENDERCORE_API FRDGBufferRef CreateStructuredBuffer (FRDGBuilder &GraphBuilder, const TCHAR *Name, uint32 BytesPerElement, FRDGBufferNumElementsCallback &&NumElementsCallback, FRDGBufferInitialDataCallback &&InitialDataCallback, FRDGBufferInitialDataSizeCallback &&InitialDataSizeCallback)
A variant where NumElements, InitialData, and InitialDataSize are supplied through callbacks.
RENDERCORE_API FRDGBufferRef CreateStructuredBuffer (FRDGBuilder &GraphBuilder, const TCHAR *Name, uint32 BytesPerElement, uint32 NumElements, const void *InitialData, uint64 InitialDataSize, ERDGInitialDataFlags InitialDataFlags=ERDGInitialDataFlags::None)
Creates a structured buffer with initial data by creating an upload pass.
template<typename ArrayType>
FRDGBufferRef CreateStructuredBuffer_Impl (FRDGBuilder &GraphBuilder, const TCHAR *Name, TRDGBufferArrayCallback< ArrayType > &&ArrayCallback)
A variant where the TArray is supplied through callbacks.
template<typename ElementType, typename AllocatorType>
FRDGBufferRef CreateStructuredUploadBuffer (FRDGBuilder &GraphBuilder, const TCHAR *Name, const TArray< ElementType, AllocatorType > &InitialData, ERDGInitialDataFlags InitialDataFlags=ERDGInitialDataFlags::None)
Helper to create a structured upload buffer with initial data from a TArray.
FRDGTextureMSAA CreateTextureMSAA (FRDGBuilder &GraphBuilder, FRDGTextureDesc Desc, const TCHAR *Name, ETextureCreateFlags ResolveFlagsToAdd=TexCreate_None)
RENDERCORE_API FRDGTextureMSAA CreateTextureMSAA (FRDGBuilder &GraphBuilder, FRDGTextureDesc Desc, const TCHAR *NameMultisampled, const TCHAR *NameResolved, ETextureCreateFlags ResolveFlagsToAdd=TexCreate_None)
template<typename ElementType>
FRDGBufferRef CreateUploadBuffer (FRDGBuilder &GraphBuilder, const TCHAR *Name, const FRDGUploadData< ElementType > &InitialData)
template<typename ElementType>
FRDGBufferRef CreateUploadBuffer (FRDGBuilder &GraphBuilder, const TCHAR *Name, TConstArrayView< ElementType > InitialData, ERDGInitialDataFlags InitialDataFlags=ERDGInitialDataFlags::None)
template<typename ElementType>
FRDGBufferRef CreateUploadBuffer (FRDGBuilder &GraphBuilder, const TCHAR *Name, uint32 BytesPerElement, uint32 NumElements, const FRDGUploadData< ElementType > &InitialData)
RENDERCORE_API FRDGBufferRef CreateUploadBuffer (FRDGBuilder &GraphBuilder, const TCHAR *Name, uint32 BytesPerElement, uint32 NumElements, const void *InitialData, uint64 InitialDataSize, ERDGInitialDataFlags InitialDataFlags=ERDGInitialDataFlags::None)
RENDERCORE_API FRDGBufferRef CreateVertexBuffer (FRDGBuilder &GraphBuilder, const TCHAR *Name, const FRDGBufferDesc &Desc, const void *InitialData, uint64 InitialDataSize, ERDGInitialDataFlags InitialDataFlags=ERDGInitialDataFlags::None)
Creates a vertex buffer with initial data by creating an upload pass.
template<typename TShaderClass>
void FComputeShaderUtils::Dispatch (FRHIComputeCommandList &RHICmdList, const TShaderRef< TShaderClass > &ComputeShader, const FShaderParametersMetadata *ParametersMetadata, const typename TShaderClass::FParameters &Parameters, FIntVector GroupCount)
Dispatch a compute shader to rhi command list with its parameters.
template<typename TShaderClass>
void FComputeShaderUtils::Dispatch (FRHIComputeCommandList &RHICmdList, const TShaderRef< TShaderClass > &ComputeShader, const typename TShaderClass::FParameters &Parameters, FIntVector GroupCount)
template<typename TShaderClass>
void FComputeShaderUtils::DispatchIndirect (FRHIComputeCommandList &RHICmdList, const TShaderRef< TShaderClass > &ComputeShader, const typename TShaderClass::FParameters &Parameters, FRDGBufferRef IndirectArgsBuffer, uint32 IndirectArgOffset)
Dispatch a compute shader to rhi command list with its parameters and indirect args.
template<typename TShaderClass>
void FComputeShaderUtils::DispatchIndirect (FRHIComputeCommandList &RHICmdList, const TShaderRef< TShaderClass > &ComputeShader, const typename TShaderClass::FParameters &Parameters, FRHIBuffer *IndirectArgsBuffer, uint32 IndirectArgOffset)
Indirect dispatch a compute shader to rhi command list with its parameters.
FIntVector FComputeShaderUtils::GetGroupCount (const FIntPoint &ThreadCount, const FIntPoint &GroupSize)
FIntVector FComputeShaderUtils::GetGroupCount (const FIntPoint &ThreadCount, const int32 GroupSize)
FIntVector FComputeShaderUtils::GetGroupCount (const FIntVector &ThreadCount, const FIntVector &GroupSize)
FIntVector FComputeShaderUtils::GetGroupCount (const FIntVector &ThreadCount, const int32 GroupSize)
FIntVector FComputeShaderUtils::GetGroupCount (const int32 ThreadCount, const int32 GroupSize)
Compute the number of groups to dispatch.
FIntVector FComputeShaderUtils::GetGroupCountWrapped (const int32 TargetGroupCount)
Wrapping number of groups to Y and Z dimension if X group count overflows GRHIMaxDispatchThreadGroupsPerDimension.
FIntVector FComputeShaderUtils::GetGroupCountWrapped (const int32 ThreadCount, const int32 GroupSize)
Compute the number of groups to dispatch and allow wrapping to Y and Z dimension if X group count overflows.
FRDGBufferRef GetIfProduced (FRDGBufferRef Buffer, FRDGBufferRef FallbackBuffer=nullptr)
Returns the buffer if has been produced by a prior pass, or null otherwise.
FRDGTextureRef GetIfProduced (FRDGTextureRef Texture, FRDGTextureRef FallbackTexture=nullptr)
Returns the texture if it was produced by a prior pass, or null otherwise.
ERenderTargetLoadAction GetLoadActionIfProduced (FRDGTextureRef Texture, ERenderTargetLoadAction ActionIfNotProduced)
Returns 'Load' if the texture has already been produced by a prior pass, or the requested initial action.
FRenderTargetBinding GetLoadBindingIfProduced (FRDGTextureRef Texture, ERenderTargetLoadAction ActionIfNotProduced)
Returns a binding with the requested initial action, or a load action if the resource has been produced by a prior pass.
FRenderTargetBindingSlots GetRenderTargetBindings (ERenderTargetLoadAction ColorLoadAction, TArrayView< FRDGTextureRef > ColorTextures)
FRenderTargetBindingSlots GetRenderTargetBindings (ERenderTargetLoadAction ColorLoadAction, TArrayView< FTextureRenderTargetBinding > ColorTextures)
bool HasBeenProduced (FRDGViewableResource *Resource)
Returns whether the resource was produced by a prior pass.
bool IsRegistered (FRDGBuilder &GraphBuilder, const TRefCountPtr< FRDGPooledBuffer > &Buffer)
bool IsRegistered (FRDGBuilder &GraphBuilder, const TRefCountPtr< IPooledRenderTarget > &RenderTarget)
template<typename TShaderClass>
void FComputeShaderUtils::Private::PrepareDispatch (FRHIComputeCommandList &RHICmdList, const TShaderRef< TShaderClass > &ComputeShader, const FShaderParametersMetadata *ParametersMetadata, const typename TShaderClass::FParameters &Parameters)
template<typename TShaderClass>
void FComputeShaderUtils::Private::PrepareDispatch (FRHIComputeCommandList &RHICmdList, const TShaderRef< TShaderClass > &ComputeShader, const typename TShaderClass::FParameters &Parameters)
FRDGTextureRef RegisterExternalTexture (FRDGBuilder &GraphBuilder, FRHITexture *Texture, const TCHAR *NameIfUnregistered)
FRDGTextureRef RegisterExternalTexture (FRDGBuilder &GraphBuilder, FRHITexture *Texture, const TCHAR *NameIfUnregistered, ERDGTextureFlags Flags)
RENDERCORE_API FRDGTextureRef RegisterExternalTextureWithFallback (FRDGBuilder &GraphBuilder, const TRefCountPtr< IPooledRenderTarget > &ExternalPooledTexture, const TRefCountPtr< IPooledRenderTarget > &FallbackPooledTexture)
Register external texture with fallback if the resource is invalid.
FRHIBuffer * TryGetRHI (FRDGBuffer *Buffer)
FRHIBuffer * TryGetRHI (FRDGPooledBuffer *Buffer)
FRHITexture * TryGetRHI (FRDGTextureRef Texture)
Returns the RHI texture from an RDG texture if it exists, or null otherwise.
uint64 TryGetSize (const FRDGBuffer *Buffer)
uint64 TryGetSize (const FRDGPooledBuffer *Buffer)
FRHIShaderResourceView * TryGetSRV (FRDGPooledBuffer *Buffer)
FRDGBufferRef TryRegisterExternalBuffer (FRDGBuilder &GraphBuilder, const TRefCountPtr< FRDGPooledBuffer > &ExternalPooledBuffer, ERDGBufferFlags Flags=ERDGBufferFlags::None)
Variants of RegisterExternalBuffer which will return null (rather than assert) if the external buffer is null.
FRDGTextureRef TryRegisterExternalTexture (FRDGBuilder &GraphBuilder, const TRefCountPtr< IPooledRenderTarget > &ExternalPooledTexture, ERDGTextureFlags Flags=ERDGTextureFlags::None)
Variants of RegisterExternalTexture which will returns null (rather than assert) if the external texture is null.
void FComputeShaderUtils::ValidateGroupCount (const FIntVector &GroupCount)
void FComputeShaderUtils::ValidateIndirectArgsBuffer (const FRDGBufferRef IndirectArgsBuffer, uint32 IndirectArgOffset)
void FComputeShaderUtils::ValidateIndirectArgsBuffer (uint32 IndirectArgsBufferSize, uint32 IndirectArgOffset)
Variables
static constexpr int32 FComputeShaderUtils::kGolden2DGroupSize = 8
Ideal size of group size 8x8 to occupy at least an entire wave on GCN, two warp on Nvidia.
static constexpr int32 FComputeShaderUtils::WrappedGroupStride = 128
Constant stride used when wrapping too large 1D dispatches using GetGroupCountWrapped, selected as 128 appears to be the lowest common denominator for mobile (GLES 3.1).
Typedef Documentation
FRDGDispatchLateParamCallback
using FRDGDispatchLateParamCallback = TFunction<void()>
Definition at line 48 of file RenderGraphUtils.h.
Function Documentation
AddClearDepthStencilPass() [1/2]
RENDERCORE_API void AddClearDepthStencilPass (FRDGBuilder & GraphBuilder, FRDGTextureRef Texture, bool bClearDepth, float Depth, bool bClearStencil, uint8 Stencil)
Adds a render graph pass to clear a depth stencil target.
Prefer to use clear actions if possible.
References Depth, Stencil, and Texture.
AddClearDepthStencilPass() [2/2]
RENDERCORE_API void AddClearDepthStencilPass (FRDGBuilder & GraphBuilder, FRDGTextureRef Texture, ERenderTargetLoadAction DepthLoadAction = ERenderTargetLoadAction::EClear, ERenderTargetLoadAction StencilLoadAction = ERenderTargetLoadAction::EClear)
Adds a render graph pass to clear a depth stencil target to its optimized clear value using a raster pass.
References Texture.
AddClearRenderTargetPass() [1/4]
RENDERCORE_API void AddClearRenderTargetPass (FRDGBuilder & GraphBuilder, FRDGTextureRef Texture)
Adds a render graph pass to clear a render target to its clear value (single mip, single slice)
References Texture.
AddClearRenderTargetPass() [2/4]
RENDERCORE_API void AddClearRenderTargetPass (FRDGBuilder & GraphBuilder, FRDGTextureRef Texture, const FLinearColor & ClearColor)
Adds a render graph pass to clear a render target (single mip, single slice).
Uses render pass clear actions if the clear color matches the fast clear color.
References Texture.
AddClearRenderTargetPass() [3/4]
RENDERCORE_API void AddClearRenderTargetPass (FRDGBuilder & GraphBuilder, FRDGTextureRef Texture, const FLinearColor & ClearColor, FIntRect Viewport)
Adds a render graph pass to clear a part of a render target (single mip, single slice).
Draws a quad to the requested viewport.
References Texture.
AddClearRenderTargetPass() [4/4]
RENDERCORE_API void AddClearRenderTargetPass (FRDGBuilder & GraphBuilder, FRDGTextureRef Texture, const FRDGTextureClearInfo & TextureClearInfo)
Adds a render graph pass to clear a render target to its clear value.
References Texture.
AddClearStencilPass()
RENDERCORE_API void AddClearStencilPass (FRDGBuilder & GraphBuilder, FRDGTextureRef Texture)
Adds a render graph pass to clear the stencil portion of a depth / stencil target to its fast clear value.
References Texture.
AddClearUAVFloatPass()
RENDERCORE_API void AddClearUAVFloatPass (FRDGBuilder & GraphBuilder, FRDGBufferUAVRef BufferUAV, float Value, ERDGPassFlags ComputePassFlags = ERDGPassFlags::Compute)
References BufferUAV, Compute, and Value.
AddClearUAVPass() [1/12]
RENDERCORE_API void AddClearUAVPass (FRDGBuilder & GraphBuilder, ERHIFeatureLevel::Type FeatureLevel, FRDGTextureUAVRef TextureUAV, const uint32(&) ClearValues[4], FRDGBufferSRVRef RectMinMaxBufferSRV, uint32 NumRects)
Clears parts of UAV specified by an array of screen rects.
If no rects are specific, then it falls back to a standard UAV clear.
References TextureUAV.
AddClearUAVPass() [2/12]
RENDERCORE_API void AddClearUAVPass (FRDGBuilder & GraphBuilder, FRDGBufferUAVRef BufferUAV, uint32 Value, ERDGPassFlags ComputePassFlags = ERDGPassFlags::Compute)
Adds a render graph pass to clear a texture or buffer UAV with a single typed value.
References BufferUAV, Compute, and Value.
AddClearUAVPass() [3/12]
RENDERCORE_API void AddClearUAVPass (FRDGBuilder & GraphBuilder, FRDGTextureUAVRef TextureUAV, const FIntPoint & ClearValue, ERDGPassFlags ComputePassFlags = ERDGPassFlags::Compute)
References Compute, and TextureUAV.
AddClearUAVPass() [4/12]
RENDERCORE_API void AddClearUAVPass (FRDGBuilder & GraphBuilder, FRDGTextureUAVRef TextureUAV, const FLinearColor & ClearColor, ERDGPassFlags ComputePassFlags = ERDGPassFlags::Compute)
References Compute, and TextureUAV.
AddClearUAVPass() [5/12]
RENDERCORE_API void AddClearUAVPass (FRDGBuilder & GraphBuilder, FRDGTextureUAVRef TextureUAV, const float(&) ClearValues[4], ERDGPassFlags ComputePassFlags = ERDGPassFlags::Compute)
References Compute, and TextureUAV.
AddClearUAVPass() [6/12]
RENDERCORE_API void AddClearUAVPass (FRDGBuilder & GraphBuilder, FRDGTextureUAVRef TextureUAV, const FUintVector4 & ClearValues, ERDGPassFlags ComputePassFlags = ERDGPassFlags::Compute)
References Compute, and TextureUAV.
AddClearUAVPass() [7/12]
RENDERCORE_API void AddClearUAVPass (FRDGBuilder & GraphBuilder, FRDGTextureUAVRef TextureUAV, const FVector & ClearValue, ERDGPassFlags ComputePassFlags = ERDGPassFlags::Compute)
References Compute, FVector, and TextureUAV.
AddClearUAVPass() [8/12]
RENDERCORE_API void AddClearUAVPass (FRDGBuilder & GraphBuilder, FRDGTextureUAVRef TextureUAV, const FVector2D & ClearValue, ERDGPassFlags ComputePassFlags = ERDGPassFlags::Compute)
References Compute, and TextureUAV.
AddClearUAVPass() [9/12]
RENDERCORE_API void AddClearUAVPass (FRDGBuilder & GraphBuilder, FRDGTextureUAVRef TextureUAV, const FVector4 & ClearValues, ERDGPassFlags ComputePassFlags = ERDGPassFlags::Compute)
References Compute, and TextureUAV.
AddClearUAVPass() [10/12]
RENDERCORE_API void AddClearUAVPass (FRDGBuilder & GraphBuilder, FRDGTextureUAVRef TextureUAV, const uint32(&) ClearValues[4], ERDGPassFlags ComputePassFlags = ERDGPassFlags::Compute)
References Compute, and TextureUAV.
AddClearUAVPass() [11/12]
RENDERCORE_API void AddClearUAVPass (FRDGBuilder & GraphBuilder, FRDGTextureUAVRef TextureUAV, float ClearValue, ERDGPassFlags ComputePassFlags = ERDGPassFlags::Compute)
References Compute, and TextureUAV.
AddClearUAVPass() [12/12]
RENDERCORE_API void AddClearUAVPass (FRDGBuilder & GraphBuilder, FRDGTextureUAVRef TextureUAV, uint32 ClearValue, ERDGPassFlags ComputePassFlags = ERDGPassFlags::Compute)
References Compute, and TextureUAV.
AddCopyBufferPass() [1/2]
RENDERCORE_API void AddCopyBufferPass (FRDGBuilder & GraphBuilder, FRDGBufferRef DstBuffer, FRDGBufferRef SrcBuffer)
AddCopyBufferPass() [2/2]
RENDERCORE_API void AddCopyBufferPass (FRDGBuilder & GraphBuilder, FRDGBufferRef DstBuffer, uint64 DstOffset, FRDGBufferRef SrcBuffer, uint64 SrcOffset, uint64 NumBytes)
Adds a render graph pass to copy SrcBuffer content into DstBuffer.
AddCopyTexturePass() [1/2]
RENDERCORE_API void AddCopyTexturePass (FRDGBuilder & GraphBuilder, FRDGTextureRef InputTexture, FRDGTextureRef OutputTexture, const FRHICopyTextureInfo & CopyInfo)
Adds a render graph pass to copy a region from one texture to another.
Uses RHICopyTexture under the hood. Formats of the two textures must match. The output and output texture regions be within the respective extents.
Referenced by AddCopyTexturePass().
AddCopyTexturePass() [2/2]
void AddCopyTexturePass (FRDGBuilder & GraphBuilder, FRDGTextureRef InputTexture, FRDGTextureRef OutputTexture, FIntPoint InputPosition = FIntPoint::ZeroValue, FIntPoint OutputPosition = FIntPoint::ZeroValue, FIntPoint Size = FIntPoint::ZeroValue) inline
Simpler variant of the above function for 2D textures.
Parameters
InputPosition The pixel position within the input texture of the top-left corner of the box.
OutputPosition The pixel position within the output texture of the top-left corner of the box.
Size The size in pixels of the region to copy from input to output. If zero, the full extent of the input texture is copied.
Definition at line 721 of file RenderGraphUtils.h.
References AddCopyTexturePass(), TSequenceHistory< HistorySize >::Size, and UE::Math::TIntPoint< int32 >::ZeroValue.
AddDispatchToRHIThreadPass()
void AddDispatchToRHIThreadPass (FRDGBuilder & GraphBuilder)
Definition at line 1241 of file RenderGraphUtils.h.
References FRDGBuilder::AddDispatchHint(), and FORCEINLINE.
AddDrawTexturePass()
RENDERCORE_API void AddDrawTexturePass (FRDGBuilder & GraphBuilder, const FGlobalShaderMap * ShaderMap, FRDGTextureRef InputTexture, FRDGTextureRef OutputTexture, const FRDGDrawTextureInfo & DrawInfo)
AddEnqueueCopyPass() [1/2]
RENDERCORE_API void AddEnqueueCopyPass (FRDGBuilder & GraphBuilder, FRHIGPUBufferReadback * Readback, FRDGBufferRef SourceBuffer, uint32 NumBytes)
Adds a pass to readback contents of an RDG buffer.
References Readback.
AddEnqueueCopyPass() [2/2]
RENDERCORE_API void AddEnqueueCopyPass (FRDGBuilder & GraphBuilder, FRHIGPUTextureReadback * Readback, FRDGTextureRef SourceTexture, FResolveRect Rect = FResolveRect())
Adds a pass to readback contents of an RDG texture.
References Readback.
AddPass()
template<typename ExecuteLambdaType> void AddPass (FRDGBuilder & GraphBuilder, FRDGEventName && Name, ExecuteLambdaType && ExecuteLambda)
Helper functions to add parameterless passes to the graph.
Definition at line 1228 of file RenderGraphUtils.h.
References FRDGBuilder::AddPass(), FORCEINLINE, MoveTemp(), Name, and None.
Referenced by AddPassIfDebug().
AddPassIfDebug()
template<typename ExecuteLambdaType> void AddPassIfDebug (FRDGBuilder & GraphBuilder, FRDGEventName && Name, ExecuteLambdaType && ExecuteLambda)
Definition at line 1234 of file RenderGraphUtils.h.
References AddPass(), FORCEINLINE, MoveTemp(), and Name.
AddReadbackBufferPass()
template<typename ExecuteLambdaType> void AddReadbackBufferPass (FRDGBuilder & GraphBuilder, FRDGEventName && Name, FRDGBufferRef Buffer, ExecuteLambdaType && ExecuteLambda)
Definition at line 1263 of file RenderGraphUtils.h.
References AddReadbackBufferPass(), Buffer, FReadbackBufferParameters::Buffer, MoveTemp(), Name, and Readback.
Referenced by AddReadbackBufferPass().
AddReadbackTexturePass()
template<typename ExecuteLambdaType> void AddReadbackTexturePass (FRDGBuilder & GraphBuilder, FRDGEventName && Name, FRDGTextureRef Texture, ExecuteLambdaType && ExecuteLambda)
Definition at line 1251 of file RenderGraphUtils.h.
References AddReadbackTexturePass(), MoveTemp(), Name, Readback, Texture, and FReadbackTextureParameters::Texture.
Referenced by AddReadbackTexturePass().
AddResummarizeHTilePass()
RENDERCORE_API void AddResummarizeHTilePass (FRDGBuilder & GraphBuilder, FRDGTextureRef DepthTexture)
Adds a render graph pass to resummarize the htile plane.
AllocatePooledBuffer() [1/2]
RENDERCORE_API TRefCountPtr< FRDGPooledBuffer > AllocatePooledBuffer (const FRDGBufferDesc & Desc, const TCHAR * Name, ERDGPooledBufferAlignment Alignment = ERDGPooledBufferAlignment::Page)
References Name.
AllocatePooledBuffer() [2/2]
RENDERCORE_API bool AllocatePooledBuffer (const FRDGBufferDesc & Desc, TRefCountPtr< FRDGPooledBuffer > & Out, const TCHAR * Name, ERDGPooledBufferAlignment Alignment = ERDGPooledBufferAlignment::Page)
References Name.
Referenced by AllocatePooledBufferCurrentLLMTag().
AllocatePooledBufferCurrentLLMTag()
TRefCountPtr< FRDGPooledBuffer > AllocatePooledBufferCurrentLLMTag (FRHICommandListBase & RHICmdList, const FRDGBufferDesc & Desc, const TCHAR * Name, ERDGPooledBufferAlignment Alignment = ERDGPooledBufferAlignment::Page) inline
Definition at line 1415 of file RenderGraphUtils.h.
References AllocatePooledBuffer(), and Name.
AllocatePooledTexture() [1/2]
RENDERCORE_API TRefCountPtr< IPooledRenderTarget > AllocatePooledTexture (const FRDGTextureDesc & Desc, const TCHAR * Name)
References Name.
AllocatePooledTexture() [2/2]
RENDERCORE_API bool AllocatePooledTexture (const FRDGTextureDesc & Desc, TRefCountPtr< IPooledRenderTarget > & Out, const TCHAR * Name)
References Name.
ClearUnusedGraphResources() [1/3]
template<typename TShaderClass> void ClearUnusedGraphResources (const TShaderRef< TShaderClass > & Shader, const FShaderParametersMetadata * ParametersMetadata, typename TShaderClass::FParameters * InoutParameters, std::initializer_list< FRDGResourceRef > ExcludeList = {})
Definition at line 195 of file RenderGraphUtils.h.
Referenced by FPixelShaderUtils::AddFullscreenInstancedMultiViewportPass(), FPixelShaderUtils::AddFullscreenPass(), FComputeShaderUtils::AddPass(), FComputeShaderUtils::AddPass(), FComputeShaderUtils::AddPass(), and FPixelShaderUtils::AddRasterizeToRectsPass().
ClearUnusedGraphResources() [2/3]
template<typename TShaderClass> void ClearUnusedGraphResources (const TShaderRef< TShaderClass > & Shader, typename TShaderClass::FParameters * InoutParameters, std::initializer_list< FRDGResourceRef > ExcludeList = {})
Definition at line 211 of file RenderGraphUtils.h.
ClearUnusedGraphResources() [3/3]
template<typename TShaderClassA, typename TShaderClassB, typename TPassParameterStruct> void ClearUnusedGraphResources (const TShaderRef< TShaderClassA > & ShaderA, const TShaderRef< TShaderClassB > & ShaderB, TPassParameterStruct * InoutParameters, std::initializer_list< FRDGResourceRef > ExcludeList = {})
Definition at line 221 of file RenderGraphUtils.h.
ClearUnusedGraphResourcesImpl() [1/2]
RENDERCORE_API void ClearUnusedGraphResourcesImpl (const FShaderParameterBindings & ShaderBindings, const FShaderParametersMetadata * ParametersMetadata, void * InoutParameters, std::initializer_list< FRDGResourceRef > ExcludeList) extern
Clears all render graph tracked resources that are not bound by a shader.
Excludes any resources on the ExcludeList from being cleared regardless of whether the shader binds them or not. This is needed for resources that are used outside of shader bindings such as indirect arguments buffers.
ClearUnusedGraphResourcesImpl() [2/2]
RENDERCORE_API void ClearUnusedGraphResourcesImpl (TArrayView< const FShaderParameterBindings * > ShaderBindingsList, const FShaderParametersMetadata * ParametersMetadata, void * InoutParameters, std::initializer_list< FRDGResourceRef > ExcludeList) extern
Similar to the function above, but takes a list of shader bindings and only clears if none of the shaders contain the resource.
ConvertToExternalAccessBuffer() [1/2]
const TRefCountPtr< FRDGPooledBuffer > & ConvertToExternalAccessBuffer (FRDGBuilder & GraphBuilder, FRDGBuffer * Buffer, ERHIAccess Access = ERHIAccess::SRVMask, ERHIPipeline Pipelines = ERHIPipeline::Graphics) inline
Definition at line 1362 of file RenderGraphUtils.h.
References Access, Buffer, FRDGBuilder::ConvertToExternalBuffer(), and FRDGBuilder::UseExternalAccessMode().
ConvertToExternalAccessBuffer() [2/2]
const TRefCountPtr< FRDGPooledBuffer > & ConvertToExternalAccessBuffer (FRDGBuilder & GraphBuilder, FRDGExternalAccessQueue & ExternalAccessQueue, FRDGBuffer * Buffer, ERHIAccess Access = ERHIAccess::SRVMask, ERHIPipeline Pipelines = ERHIPipeline::Graphics) inline
Definition at line 1384 of file RenderGraphUtils.h.
References Access, FRDGExternalAccessQueue::Add(), Buffer, and FRDGBuilder::ConvertToExternalBuffer().
ConvertToExternalAccessTexture() [1/2]
const TRefCountPtr< IPooledRenderTarget > & ConvertToExternalAccessTexture (FRDGBuilder & GraphBuilder, FRDGExternalAccessQueue & ExternalAccessQueue, FRDGTexture * Texture, ERHIAccess Access = ERHIAccess::SRVMask, ERHIPipeline Pipelines = ERHIPipeline::Graphics) inline
Definition at line 1373 of file RenderGraphUtils.h.
References Access, FRDGExternalAccessQueue::Add(), FRDGBuilder::ConvertToExternalTexture(), and Texture.
ConvertToExternalAccessTexture() [2/2]
const TRefCountPtr< IPooledRenderTarget > & ConvertToExternalAccessTexture (FRDGBuilder & GraphBuilder, FRDGTexture * Texture, ERHIAccess Access = ERHIAccess::SRVMask, ERHIPipeline Pipelines = ERHIPipeline::Graphics) inline
Definition at line 1351 of file RenderGraphUtils.h.
References Access, FRDGBuilder::ConvertToExternalTexture(), Texture, and FRDGBuilder::UseExternalAccessMode().
CreateByteAddressBuffer() [1/6]
template<typename ElementType> FRDGBufferRef CreateByteAddressBuffer (FRDGBuilder & GraphBuilder, const TCHAR * Name, const FRDGUploadData< ElementType > & InitialData)
Definition at line 1083 of file RenderGraphUtils.h.
References CreateByteAddressBuffer(), FORCEINLINE, TArrayView< InElementType, InSizeType >::GetData(), FRDGUploadData< InElementType >::GetTotalSize(), TArrayView< InElementType, InSizeType >::GetTypeSize(), Name, NoCopy, and TArrayView< InElementType, InSizeType >::Num().
CreateByteAddressBuffer() [2/6]
RENDERCORE_API FRDGBufferRef CreateByteAddressBuffer (FRDGBuilder & GraphBuilder, const TCHAR * Name, FRDGBufferNumElementsCallback && NumElementsCallback, FRDGBufferInitialDataCallback && InitialDataCallback, FRDGBufferInitialDataSizeCallback && InitialDataSizeCallback)
A variant where NumElements, InitialData, and InitialDataSize are supplied through callbacks.
This allows creating a buffer with information unknown at creation time. Though, data must be ready before the most recent RDG pass that references the buffer is executed. For byte address buffers, NumElements must be Size / 4.
References Name.
CreateByteAddressBuffer() [3/6]
template<typename GetArrayRefCallback, typename Type = TInvokeResult_T<GetArrayRefCallback>> FRDGBufferRef CreateByteAddressBuffer (FRDGBuilder & GraphBuilder, const TCHAR * Name, GetArrayRefCallback && ArrayCallback)
Same as the previous function but where the type of the array is automatically inferred, so we can do : TArray<FSomeType> Array = GraphBuilder.AllocArray<...>(); CreateByteAddressBuffer(..., [&]() -> auto&{ return Array; });.
Definition at line 1074 of file RenderGraphUtils.h.
References CreateByteAddressBuffer_Impl(), FORCEINLINE, MoveTemp(), and Name.
CreateByteAddressBuffer() [4/6]
template<typename ElementType, typename AllocatorType> FRDGBufferRef CreateByteAddressBuffer (FRDGBuilder & GraphBuilder, const TCHAR * Name, TArray< ElementType, AllocatorType > && InitialData)
Helper to create a byte address buffer with initial data from a TArray with move semantics, this can be cheaper as it guarantees the lifetimes of the data & permits copy-free upload.
Definition at line 1019 of file RenderGraphUtils.h.
References FRDGBuilder::AllocObject(), CreateByteAddressBuffer(), FORCEINLINE, TArray< InElementType, InAllocatorType >::GetData(), TArray< InElementType, InAllocatorType >::GetTypeSize(), MoveTemp(), Name, NoCopy, and TArray< InElementType, InAllocatorType >::Num().
CreateByteAddressBuffer() [5/6]
template<typename ElementType> FRDGBufferRef CreateByteAddressBuffer (FRDGBuilder & GraphBuilder, const TCHAR * Name, TConstArrayView< ElementType > InitialData, ERDGInitialDataFlags InitialDataFlags = ERDGInitialDataFlags::None)
Helper to create a byte address buffer with initial data from a TConstArrayView.
Definition at line 1039 of file RenderGraphUtils.h.
References CreateByteAddressBuffer(), FORCEINLINE, Name, NoCopy, and None.
CreateByteAddressBuffer() [6/6]
RENDERCORE_API FRDGBufferRef CreateByteAddressBuffer (FRDGBuilder & GraphBuilder, const TCHAR * Name, uint32 NumBytes, const void * InitialData, uint64 InitialDataSize, ERDGInitialDataFlags InitialDataFlags = ERDGInitialDataFlags::None)
Creates a byte address buffer with initial data by creating an upload pass.
References Name, and None.
Referenced by CreateByteAddressBuffer(), CreateByteAddressBuffer(), CreateByteAddressBuffer(), and CreateByteAddressBuffer_Impl().
CreateByteAddressBuffer_Impl()
template<typename ArrayType> FRDGBufferRef CreateByteAddressBuffer_Impl (FRDGBuilder & GraphBuilder, const TCHAR * Name, TRDGBufferArrayCallback< ArrayType > && ArrayCallback)
A variant where the TArray is supplied through callbacks.
This allows creating a buffer with information unknown at creation time. Though, data must be ready before the most recent RDG pass that references the buffer is executed.
Definition at line 1058 of file RenderGraphUtils.h.
References Array, CreateByteAddressBuffer(), FORCEINLINE, and Name.
Referenced by CreateByteAddressBuffer().
CreateByteAddressUploadBuffer() [1/3]
template<typename ElementType, typename AllocatorType> FRDGBufferRef CreateByteAddressUploadBuffer (FRDGBuilder & GraphBuilder, const TCHAR * Name, const TArray< ElementType, AllocatorType > & InitialData, ERDGInitialDataFlags InitialDataFlags = ERDGInitialDataFlags::None)
Helper to create a byte address upload buffer with initial data from a TArray.
NOTE: does not provide a 1-size fallback for empty initial data.
Definition at line 1161 of file RenderGraphUtils.h.
References Buffer, FRDGBuilder::CreateBuffer(), FRDGBufferDesc::CreateByteAddressUploadDesc(), FORCEINLINE, Name, None, TArray< InElementType, InAllocatorType >::Num(), and FRDGBuilder::QueueBufferUpload().
Referenced by CreateByteAddressUploadBuffer_Impl().
CreateByteAddressUploadBuffer() [2/3]
FRDGBufferRef CreateByteAddressUploadBuffer (FRDGBuilder & GraphBuilder, const TCHAR * Name, FRDGBufferNumElementsCallback && NumElementsCallback, FRDGBufferInitialDataCallback && InitialDataCallback, FRDGBufferInitialDataSizeCallback && InitialDataSizeCallback)
A variant where NumElements, InitialData, and InitialDataSize are supplied through callbacks.
This allows creating a buffer with information unknown at creation time. Though, data must be ready before the most recent RDG pass that references the buffer is executed. For byte address buffers, NumElements must be Size / 4.
Definition at line 1176 of file RenderGraphUtils.h.
References Buffer, FRDGBuilder::CreateBuffer(), FRDGBufferDesc::CreateByteAddressUploadDesc(), FORCEINLINE, MoveTemp(), Name, and FRDGBuilder::QueueBufferUpload().
CreateByteAddressUploadBuffer() [3/3]
template<typename GetArrayRefCallback, typename Type = TInvokeResult_T<GetArrayRefCallback>> FRDGBufferRef CreateByteAddressUploadBuffer (FRDGBuilder & GraphBuilder, const TCHAR * Name, GetArrayRefCallback && ArrayCallback)
Same as the previous function but where the type of the array is automatically inferred, so we can do : TArray<FSomeType> Array = GraphBuilder.AllocArray<...>(); CreateByteAddressBuffer(..., [&]() -> auto&{ return Array; });.
Definition at line 1209 of file RenderGraphUtils.h.
References CreateByteAddressUploadBuffer_Impl(), FORCEINLINE, MoveTemp(), and Name.
CreateByteAddressUploadBuffer_Impl()
template<typename ArrayType> FRDGBufferRef CreateByteAddressUploadBuffer_Impl (FRDGBuilder & GraphBuilder, const TCHAR * Name, TRDGBufferArrayCallback< ArrayType > && ArrayCallback)
A variant where the TArray is supplied through callbacks.
This allows creating a buffer with information unknown at creation time. Though, data must be ready before the most recent RDG pass that references the buffer is executed.
Definition at line 1193 of file RenderGraphUtils.h.
References Array, CreateByteAddressUploadBuffer(), FORCEINLINE, and Name.
Referenced by CreateByteAddressUploadBuffer().
CreateStructuredBuffer() [1/7]
template<typename ElementType> FRDGBufferRef CreateStructuredBuffer (FRDGBuilder & GraphBuilder, const TCHAR * Name, const FRDGUploadData< ElementType > & InitialData)
Definition at line 982 of file RenderGraphUtils.h.
References CreateStructuredBuffer(), FORCEINLINE, TArrayView< InElementType, InSizeType >::GetData(), FRDGUploadData< InElementType >::GetTotalSize(), TArrayView< InElementType, InSizeType >::GetTypeSize(), Name, NoCopy, and TArrayView< InElementType, InSizeType >::Num().
CreateStructuredBuffer() [2/7]
template<typename ElementType, typename AllocatorType> FRDGBufferRef CreateStructuredBuffer (FRDGBuilder & GraphBuilder, const TCHAR * Name, const TArray< ElementType, AllocatorType > & InitialData, ERDGInitialDataFlags InitialDataFlags = ERDGInitialDataFlags::None)
Helper to create a structured buffer with initial data from a TArray.
Definition at line 900 of file RenderGraphUtils.h.
References CreateStructuredBuffer(), FORCEINLINE, TArray< InElementType, InAllocatorType >::GetData(), TArray< InElementType, InAllocatorType >::GetTypeSize(), Name, NoCopy, None, and TArray< InElementType, InAllocatorType >::Num().
CreateStructuredBuffer() [3/7]
template<typename GetArrayRefCallback, typename Type = TInvokeResult_T<GetArrayRefCallback>> FRDGBufferRef CreateStructuredBuffer (FRDGBuilder & GraphBuilder, const TCHAR * Name, GetArrayRefCallback && ArrayCallback)
Same as the previous function but where the type of the array is automatically inferred, so we can do : TArray<FSomeType>& Array = GraphBuilder.AllocArray<...>(); CreateStructuredBuffer(..., [&]() -> auto&{ return Array; });.
Definition at line 973 of file RenderGraphUtils.h.
References CreateStructuredBuffer_Impl(), FORCEINLINE, MoveTemp(), and Name.
CreateStructuredBuffer() [4/7]
template<typename ElementType, typename AllocatorType> FRDGBufferRef CreateStructuredBuffer (FRDGBuilder & GraphBuilder, const TCHAR * Name, TArray< ElementType, AllocatorType > && InitialData)
Helper to create a structured buffer with initial data from a TArray with move semantics, this can be cheaper as it guarantees the lifetimes of the data & permits copy-free upload.
Definition at line 918 of file RenderGraphUtils.h.
References FRDGBuilder::AllocObject(), CreateStructuredBuffer(), FORCEINLINE, TArray< InElementType, InAllocatorType >::GetData(), TArray< InElementType, InAllocatorType >::GetTypeSize(), MoveTemp(), Name, NoCopy, and TArray< InElementType, InAllocatorType >::Num().
CreateStructuredBuffer() [5/7]
template<typename ElementType> FRDGBufferRef CreateStructuredBuffer (FRDGBuilder & GraphBuilder, const TCHAR * Name, TConstArrayView< ElementType > InitialData, ERDGInitialDataFlags InitialDataFlags = ERDGInitialDataFlags::None)
Helper to create a structured buffer with initial data from a TConstArrayView.
Definition at line 938 of file RenderGraphUtils.h.
References CreateStructuredBuffer(), FORCEINLINE, Name, NoCopy, and None.
CreateStructuredBuffer() [6/7]
RENDERCORE_API FRDGBufferRef CreateStructuredBuffer (FRDGBuilder & GraphBuilder, const TCHAR * Name, uint32 BytesPerElement, FRDGBufferNumElementsCallback && NumElementsCallback, FRDGBufferInitialDataCallback && InitialDataCallback, FRDGBufferInitialDataSizeCallback && InitialDataSizeCallback)
A variant where NumElements, InitialData, and InitialDataSize are supplied through callbacks.
This allows creating a buffer with information unknown at creation time. Though, data must be ready before the most recent RDG pass that references the buffer is executed.
References Name.
CreateStructuredBuffer() [7/7]
RENDERCORE_API FRDGBufferRef CreateStructuredBuffer (FRDGBuilder & GraphBuilder, const TCHAR * Name, uint32 BytesPerElement, uint32 NumElements, const void * InitialData, uint64 InitialDataSize, ERDGInitialDataFlags InitialDataFlags = ERDGInitialDataFlags::None)
Creates a structured buffer with initial data by creating an upload pass.
References Name, and None.
Referenced by CreateStructuredBuffer(), CreateStructuredBuffer(), CreateStructuredBuffer(), CreateStructuredBuffer(), and CreateStructuredBuffer_Impl().
CreateStructuredBuffer_Impl()
template<typename ArrayType> FRDGBufferRef CreateStructuredBuffer_Impl (FRDGBuilder & GraphBuilder, const TCHAR * Name, TRDGBufferArrayCallback< ArrayType > && ArrayCallback)
A variant where the TArray is supplied through callbacks.
This allows creating a buffer with information unknown at creation time. Though, data must be ready before the most recent RDG pass that references the buffer is executed.
Definition at line 957 of file RenderGraphUtils.h.
References CreateStructuredBuffer(), FORCEINLINE, and Name.
Referenced by CreateStructuredBuffer().
CreateStructuredUploadBuffer()
template<typename ElementType, typename AllocatorType> FRDGBufferRef CreateStructuredUploadBuffer (FRDGBuilder & GraphBuilder, const TCHAR * Name, const TArray< ElementType, AllocatorType > & InitialData, ERDGInitialDataFlags InitialDataFlags = ERDGInitialDataFlags::None)
Helper to create a structured upload buffer with initial data from a TArray.
NOTE: does not provide a 1-size fallback for empty initial data.
Definition at line 1145 of file RenderGraphUtils.h.
References Buffer, FRDGBuilder::CreateBuffer(), FRDGBufferDesc::CreateStructuredUploadDesc(), FORCEINLINE, Name, None, TArray< InElementType, InAllocatorType >::Num(), and FRDGBuilder::QueueBufferUpload().
CreateTextureMSAA() [1/2]
FRDGTextureMSAA CreateTextureMSAA (FRDGBuilder & GraphBuilder, FRDGTextureDesc Desc, const TCHAR * Name, ETextureCreateFlags ResolveFlagsToAdd = TexCreate_None) inline
Definition at line 332 of file RenderGraphUtils.h.
References CreateTextureMSAA(), and Name.
CreateTextureMSAA() [2/2]
RENDERCORE_API FRDGTextureMSAA CreateTextureMSAA (FRDGBuilder & GraphBuilder, FRDGTextureDesc Desc, const TCHAR * NameMultisampled, const TCHAR * NameResolved, ETextureCreateFlags ResolveFlagsToAdd = TexCreate_None)
Referenced by CreateTextureMSAA().
CreateUploadBuffer() [1/4]
template<typename ElementType> FRDGBufferRef CreateUploadBuffer (FRDGBuilder & GraphBuilder, const TCHAR * Name, const FRDGUploadData< ElementType > & InitialData)
Definition at line 1117 of file RenderGraphUtils.h.
References CreateUploadBuffer(), FORCEINLINE, Name, and TArrayView< InElementType, InSizeType >::Num().
CreateUploadBuffer() [2/4]
template<typename ElementType> FRDGBufferRef CreateUploadBuffer (FRDGBuilder & GraphBuilder, const TCHAR * Name, TConstArrayView< ElementType > InitialData, ERDGInitialDataFlags InitialDataFlags = ERDGInitialDataFlags::None)
Definition at line 1126 of file RenderGraphUtils.h.
References CreateUploadBuffer(), FORCEINLINE, Name, NoCopy, and None.
CreateUploadBuffer() [3/4]
template<typename ElementType> FRDGBufferRef CreateUploadBuffer (FRDGBuilder & GraphBuilder, const TCHAR * Name, uint32 BytesPerElement, uint32 NumElements, const FRDGUploadData< ElementType > & InitialData)
Definition at line 1106 of file RenderGraphUtils.h.
References CreateUploadBuffer(), FORCEINLINE, TArrayView< InElementType, InSizeType >::GetData(), FRDGUploadData< InElementType >::GetTotalSize(), Name, and NoCopy.
CreateUploadBuffer() [4/4]
RENDERCORE_API FRDGBufferRef CreateUploadBuffer (FRDGBuilder & GraphBuilder, const TCHAR * Name, uint32 BytesPerElement, uint32 NumElements, const void * InitialData, uint64 InitialDataSize, ERDGInitialDataFlags InitialDataFlags = ERDGInitialDataFlags::None)
References Name, and None.
Referenced by CreateUploadBuffer(), CreateUploadBuffer(), and CreateUploadBuffer().
CreateVertexBuffer()
RENDERCORE_API FRDGBufferRef CreateVertexBuffer (FRDGBuilder & GraphBuilder, const TCHAR * Name, const FRDGBufferDesc & Desc, const void * InitialData, uint64 InitialDataSize, ERDGInitialDataFlags InitialDataFlags = ERDGInitialDataFlags::None)
Creates a vertex buffer with initial data by creating an upload pass.
References Name, and None.
GetIfProduced() [1/2]
FRDGBufferRef GetIfProduced (FRDGBufferRef Buffer, FRDGBufferRef FallbackBuffer = nullptr) inline
Returns the buffer if has been produced by a prior pass, or null otherwise.
Definition at line 63 of file RenderGraphUtils.h.
References Buffer, and HasBeenProduced().
GetIfProduced() [2/2]
FRDGTextureRef GetIfProduced (FRDGTextureRef Texture, FRDGTextureRef FallbackTexture = nullptr) inline
Returns the texture if it was produced by a prior pass, or null otherwise.
Definition at line 57 of file RenderGraphUtils.h.
References HasBeenProduced(), and Texture.
GetLoadActionIfProduced()
ERenderTargetLoadAction GetLoadActionIfProduced (FRDGTextureRef Texture, ERenderTargetLoadAction ActionIfNotProduced) inline
Returns 'Load' if the texture has already been produced by a prior pass, or the requested initial action.
Definition at line 69 of file RenderGraphUtils.h.
References HasBeenProduced(), and Texture.
Referenced by GetLoadBindingIfProduced().
GetLoadBindingIfProduced()
FRenderTargetBinding GetLoadBindingIfProduced (FRDGTextureRef Texture, ERenderTargetLoadAction ActionIfNotProduced) inline
Returns a binding with the requested initial action, or a load action if the resource has been produced by a prior pass.
Definition at line 75 of file RenderGraphUtils.h.
References GetLoadActionIfProduced(), and Texture.
GetRenderTargetBindings() [1/2]
FRenderTargetBindingSlots GetRenderTargetBindings (ERenderTargetLoadAction ColorLoadAction, TArrayView< FRDGTextureRef > ColorTextures) inline
Definition at line 121 of file RenderGraphUtils.h.
References check, Count, and TArrayView< InElementType, InSizeType >::Num().
GetRenderTargetBindings() [2/2]
FRenderTargetBindingSlots GetRenderTargetBindings (ERenderTargetLoadAction ColorLoadAction, TArrayView< FTextureRenderTargetBinding > ColorTextures) inline
Definition at line 158 of file RenderGraphUtils.h.
References check, Count, TArrayView< InElementType, InSizeType >::Num(), and Texture.
HasBeenProduced()
bool HasBeenProduced (FRDGViewableResource * Resource) inline
Returns whether the resource was produced by a prior pass.
Definition at line 51 of file RenderGraphUtils.h.
References FRDGViewableResource::HasBeenProduced().
Referenced by GetIfProduced(), GetIfProduced(), and GetLoadActionIfProduced().
IsRegistered() [1/2]
bool IsRegistered (FRDGBuilder & GraphBuilder, const TRefCountPtr< FRDGPooledBuffer > & Buffer) inline
Definition at line 116 of file RenderGraphUtils.h.
References Buffer, and FRDGBuilder::FindExternalBuffer().
IsRegistered() [2/2]
bool IsRegistered (FRDGBuilder & GraphBuilder, const TRefCountPtr< IPooledRenderTarget > & RenderTarget) inline
Definition at line 111 of file RenderGraphUtils.h.
References FRDGBuilder::FindExternalTexture(), and RenderTarget.
Referenced by USceneComponent::AreDynamicDataChangesAllowed().
RegisterExternalTexture() [1/2]
FRDGTextureRef RegisterExternalTexture (FRDGBuilder & GraphBuilder, FRHITexture * Texture, const TCHAR * NameIfUnregistered) inline
Definition at line 281 of file RenderGraphUtils.h.
References None, RegisterExternalTexture(), and Texture.
RegisterExternalTexture() [2/2]
FRDGTextureRef RegisterExternalTexture (FRDGBuilder & GraphBuilder, FRHITexture * Texture, const TCHAR * NameIfUnregistered, ERDGTextureFlags Flags) inline
Definition at line 271 of file RenderGraphUtils.h.
References CreateRenderTarget(), FRDGBuilder::FindExternalTexture(), Flags, FRDGBuilder::RegisterExternalTexture(), and Texture.
Referenced by RegisterExternalTexture().
RegisterExternalTextureWithFallback()
RENDERCORE_API FRDGTextureRef RegisterExternalTextureWithFallback (FRDGBuilder & GraphBuilder, const TRefCountPtr< IPooledRenderTarget > & ExternalPooledTexture, const TRefCountPtr< IPooledRenderTarget > & FallbackPooledTexture)
Register external texture with fallback if the resource is invalid.
CAUTION: use this function very wisely. It may actually remove shader parameter validation failure when a pass is actually trying to access a resource not yet or no longer available.
TryGetRHI() [1/3]
FRHIBuffer * TryGetRHI (FRDGBuffer * Buffer) inline
Definition at line 86 of file RenderGraphUtils.h.
References Buffer.
TryGetRHI() [2/3]
FRHIBuffer * TryGetRHI (FRDGPooledBuffer * Buffer) inline
Definition at line 91 of file RenderGraphUtils.h.
References Buffer.
TryGetRHI() [3/3]
FRHITexture * TryGetRHI (FRDGTextureRef Texture) inline
Returns the RHI texture from an RDG texture if it exists, or null otherwise.
Definition at line 81 of file RenderGraphUtils.h.
References Texture.
TryGetSize() [1/2]
uint64 TryGetSize (const FRDGBuffer * Buffer) inline
Definition at line 101 of file RenderGraphUtils.h.
References Buffer.
TryGetSize() [2/2]
uint64 TryGetSize (const FRDGPooledBuffer * Buffer) inline
Definition at line 106 of file RenderGraphUtils.h.
References Buffer.
TryGetSRV()
FRHIShaderResourceView * TryGetSRV (FRDGPooledBuffer * Buffer) inline
Definition at line 96 of file RenderGraphUtils.h.
References Buffer.
TryRegisterExternalBuffer()
FRDGBufferRef TryRegisterExternalBuffer (FRDGBuilder & GraphBuilder, const TRefCountPtr< FRDGPooledBuffer > & ExternalPooledBuffer, ERDGBufferFlags Flags = ERDGBufferFlags::None) inline
Variants of RegisterExternalBuffer which will return null (rather than assert) if the external buffer is null.
Definition at line 263 of file RenderGraphUtils.h.
References Flags, None, and FRDGBuilder::RegisterExternalBuffer().
TryRegisterExternalTexture()
FRDGTextureRef TryRegisterExternalTexture (FRDGBuilder & GraphBuilder, const TRefCountPtr< IPooledRenderTarget > & ExternalPooledTexture, ERDGTextureFlags Flags = ERDGTextureFlags::None) inline
Variants of RegisterExternalTexture which will returns null (rather than assert) if the external texture is null.
Definition at line 254 of file RenderGraphUtils.h.
References Flags, None, and FRDGBuilder::RegisterExternalTexture().