Unreal Engine 5.6 C++ API: Runtime/RenderCore/Public/RenderGraphParameter.h File Reference
RenderGraphParameter.h File Reference
#include "RenderGraphDefinitions.h"
#include "ShaderParameterMacros.h"
Data Structures
class FRDGParameter
A helper class for identifying and accessing a render graph pass parameter.
class FRDGParameterStruct
Wraps a pass parameter struct payload and provides helpers for traversing members.
class TRDGParameterStruct< ParameterStructType >
Functions
template<typename TParameterStruct>
static FORCEINLINE FRHIRenderPassInfo GetRenderPassInfo (TParameterStruct *Parameters)
Helper function to get RHI render pass info from a pass parameter struct.
template<typename TParameterStruct>
static FORCEINLINE FUniformBufferStaticBindings GetStaticUniformBuffers (TParameterStruct *Parameters)
Helper function to get RHI global uniform buffers out of a pass parameters struct.
template<typename TParameterStruct>
static FORCEINLINE bool HasRenderPassInfo (TParameterStruct *Parameters)
Function Documentation
GetRenderPassInfo()
template<typename TParameterStruct> FORCEINLINE FRHIRenderPassInfo GetRenderPassInfo (TParameterStruct * Parameters) static
Helper function to get RHI render pass info from a pass parameter struct.
Must be called within an RDG pass with the pass parameters; otherwise, the RHI access checks will assert. This helper is useful when you want to control the mechanics of render passes within an RDG raster pass by specifying 'SkipRenderPass'.
Definition at line 330 of file RenderGraphParameter.h.
References FORCEINLINE, and FRDGParameterStruct::GetRenderPassInfo().
GetStaticUniformBuffers()
template<typename TParameterStruct> FORCEINLINE FUniformBufferStaticBindings GetStaticUniformBuffers (TParameterStruct * Parameters) static
Helper function to get RHI global uniform buffers out of a pass parameters struct.
Definition at line 343 of file RenderGraphParameter.h.
References FORCEINLINE, and FRDGParameterStruct::GetStaticUniformBuffers().
Referenced by FRDGDispatchPassBuilder::FRDGDispatchPassBuilder().
HasRenderPassInfo()
template<typename TParameterStruct> FORCEINLINE bool HasRenderPassInfo (TParameterStruct * Parameters) static
Definition at line 336 of file RenderGraphParameter.h.
References FORCEINLINE, and FRDGParameterStruct::HasRenderTargets().