Unreal Engine 5.6 C++ API: Runtime/RenderCore/Public/RenderGraphTextureSubresource.h File Reference
RenderGraphTextureSubresource.h File Reference
#include "RHI.h"
Data Structures
struct FRDGTextureSubresource
struct FRDGTextureSubresourceLayout
struct FRDGTextureSubresourceRange
Typedefs
template<typename InElementType, typename InAllocatorType = FDefaultAllocator>
using TRDGTextureSubresourceArray = TArray<InElementType, InAllocatorType>
Functions
template<typename ElementType, typename AllocatorType, typename FunctionType>
void EnumerateSubresourceRange (const TRDGTextureSubresourceArray< ElementType, AllocatorType > &SubresourceArray, const FRDGTextureSubresourceLayout &Layout, const FRDGTextureSubresourceRange &Range, FunctionType Function)
template<typename ElementType, typename AllocatorType, typename FunctionType>
void EnumerateSubresourceRange (TRDGTextureSubresourceArray< ElementType, AllocatorType > &SubresourceArray, const FRDGTextureSubresourceLayout &Layout, const FRDGTextureSubresourceRange &Range, FunctionType Function)
template<typename ElementType, typename AllocatorType>
FORCEINLINE const ElementType & GetSubresource (const TRDGTextureSubresourceArray< ElementType, AllocatorType > &SubresourceArray, const FRDGTextureSubresourceLayout &Layout, FRDGTextureSubresource Subresource)
template<typename ElementType, typename AllocatorType>
FORCEINLINE ElementType & GetSubresource (TRDGTextureSubresourceArray< ElementType, AllocatorType > &SubresourceArray, const FRDGTextureSubresourceLayout &Layout, FRDGTextureSubresource Subresource)
template<typename ElementType, typename AllocatorType>
void InitTextureSubresources (TRDGTextureSubresourceArray< ElementType, AllocatorType > &SubresourceArray, const FRDGTextureSubresourceLayout &Layout, const ElementType &Element={})
template<typename ElementType, typename AllocatorType>
FORCEINLINE void VerifyLayout (const TRDGTextureSubresourceArray< ElementType, AllocatorType > &SubresourceArray, const FRDGTextureSubresourceLayout &Layout)
Typedef Documentation
TRDGTextureSubresourceArray
template<typename InElementType, typename InAllocatorType = FDefaultAllocator> using TRDGTextureSubresourceArray = TArray<InElementType, InAllocatorType>
Definition at line 8 of file RenderGraphTextureSubresource.h.
Function Documentation
EnumerateSubresourceRange() [1/2]
template<typename ElementType, typename AllocatorType, typename FunctionType> void EnumerateSubresourceRange (const TRDGTextureSubresourceArray< ElementType, AllocatorType > & SubresourceArray, const FRDGTextureSubresourceLayout & Layout, const FRDGTextureSubresourceRange & Range, FunctionType Function) inline
Definition at line 265 of file RenderGraphTextureSubresource.h.
References FRDGTextureSubresourceRange::EnumerateSubresources(), Function, GetSubresource(), Layout, and VerifyLayout().
EnumerateSubresourceRange() [2/2]
template<typename ElementType, typename AllocatorType, typename FunctionType> void EnumerateSubresourceRange (TRDGTextureSubresourceArray< ElementType, AllocatorType > & SubresourceArray, const FRDGTextureSubresourceLayout & Layout, const FRDGTextureSubresourceRange & Range, FunctionType Function) inline
Definition at line 255 of file RenderGraphTextureSubresource.h.
References FRDGTextureSubresourceRange::EnumerateSubresources(), Function, GetSubresource(), Layout, and VerifyLayout().
GetSubresource() [1/2]
template<typename ElementType, typename AllocatorType> FORCEINLINE const ElementType & GetSubresource (const TRDGTextureSubresourceArray< ElementType, AllocatorType > & SubresourceArray, const FRDGTextureSubresourceLayout & Layout, FRDGTextureSubresource Subresource)
Definition at line 241 of file RenderGraphTextureSubresource.h.
References FORCEINLINE, Layout, and VerifyLayout().
Referenced by EnumerateSubresourceRange(), and EnumerateSubresourceRange().
GetSubresource() [2/2]
template<typename ElementType, typename AllocatorType> FORCEINLINE ElementType & GetSubresource (TRDGTextureSubresourceArray< ElementType, AllocatorType > & SubresourceArray, const FRDGTextureSubresourceLayout & Layout, FRDGTextureSubresource Subresource)
Definition at line 248 of file RenderGraphTextureSubresource.h.
References FORCEINLINE, Layout, and VerifyLayout().
InitTextureSubresources()
template<typename ElementType, typename AllocatorType> void InitTextureSubresources (TRDGTextureSubresourceArray< ElementType, AllocatorType > & SubresourceArray, const FRDGTextureSubresourceLayout & Layout, const ElementType & Element = {}) inline
Definition at line 230 of file RenderGraphTextureSubresource.h.
References Layout.
VerifyLayout()
template<typename ElementType, typename AllocatorType> FORCEINLINE void VerifyLayout (const TRDGTextureSubresourceArray< ElementType, AllocatorType > & SubresourceArray, const FRDGTextureSubresourceLayout & Layout)
Definition at line 223 of file RenderGraphTextureSubresource.h.
References checkf, FORCEINLINE, Layout, TArray< InElementType, InAllocatorType >::Num(), and TEXT.
Referenced by EnumerateSubresourceRange(), EnumerateSubresourceRange(), GetSubresource(), and GetSubresource().