Unreal Engine 5.6 C++ API: S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/RigVM/Source/RigVM/Public/RigVMCore/RigVMMemoryStorage.h File Reference
RigVMMemoryStorage.h File Reference
#include "Containers/Array.h"
#include "Containers/UnrealString.h"
#include "CoreMinimal.h"
#include "CoreTypes.h"
#include "EdGraph/EdGraphNode.h"
#include "Misc/AssertionMacros.h"
#include "RigVMMemoryCommon.h"
#include "RigVMDefines.h"
#include "RigVMPropertyPath.h"
#include "RigVMStatistics.h"
#include "RigVMTraits.h"
#include "Templates/Casts.h"
#include "Templates/EnableIf.h"
#include "Templates/IsEnum.h"
#include "Templates/Models.h"
#include "UObject/Class.h"
#include "UObject/EnumProperty.h"
#include "UObject/Field.h"
#include "UObject/NameTypes.h"
#include "UObject/Object.h"
#include "UObject/ObjectMacros.h"
#include "UObject/PropertyPortFlags.h"
#include "UObject/ReflectedTypeAccessors.h"
#include "UObject/UObjectGlobals.h"
#include "UObject/UnrealNames.h"
#include "UObject/UnrealType.h"
#include "RigVMStringUtils.h"
#include "RigVMMemoryStorage.generated.h"
Data Structures
struct FRigVMLazyBranch
A branch which can be lazily executed.
struct FRigVMMemoryHandle
Memory handle.
struct FRigVMPropertyDescription
Property Management.
struct TRigVMLazyValue< ComputedType >
A template container for a lazily computed value.
struct TRigVMLazyValueBase
A template container for a lazily computed value.
Enumerations
enum class ERigVMExecuteResult : uint8 { Failed , Succeeded , Halted }
Functions
USTRUCT () struct FRigVMBranchInfo
Lazy execution.
Enumeration Type Documentation
ERigVMExecuteResult
enum class ERigVMExecuteResult : uint8 strong
Enumerator
Failed
Succeeded
Halted
Definition at line 44 of file RigVMMemoryStorage.h.
Function Documentation
USTRUCT()
USTRUCT ()
Lazy execution.
Definition at line 58 of file RigVMMemoryStorage.h.
References Ar, GENERATED_USTRUCT_BODY, GetTypeHash(), Hash, HashCombine(), INDEX_NONE, IsValid(), RigVMStringUtils::JoinStrings(), operator<<(), FArchive::Serialize(), TEXT, FName::ToString(), and UPROPERTY.