Unreal Engine 5.6 C++ API: S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/RigVM/Source/RigVM/Public/RigVMCore/RigVMMemoryDeprecated.h File Reference
RigVMMemoryDeprecated.h File Reference
#include "Containers/Array.h"
#include "Containers/Map.h"
#include "Containers/UnrealString.h"
#include "CoreMinimal.h"
#include "CoreTypes.h"
#include "Misc/AssertionMacros.h"
#include "RigVMMemoryCommon.h"
#include "RigVMStatistics.h"
#include "RigVMTraits.h"
#include "UObject/NameTypes.h"
#include "UObject/ObjectMacros.h"
#include "UObject/ObjectPtr.h"
#include "UObject/UnrealNames.h"
#include "RigVMMemoryDeprecated.generated.h"
Macros
#define UE_API RIGVM_API
Typedefs
typedef TArray< uint8 > FRigVMByteArray
typedef TArray< FRigVMByteArray > FRigVMNestedByteArray
Functions
UENUM() enum class ERigVMRegisterType USTRUCT () struct FRigVMRegister
The type of register within the memory.
Macro Definition Documentation
UE_API
#define UE_API RIGVM_API
Definition at line 21 of file RigVMMemoryDeprecated.h.
Typedef Documentation
FRigVMByteArray
typedef TArray<uint8> FRigVMByteArray
Definition at line 27 of file RigVMMemoryDeprecated.h.
FRigVMNestedByteArray
typedef TArray<FRigVMByteArray> FRigVMNestedByteArray
Definition at line 28 of file RigVMMemoryDeprecated.h.
Function Documentation
USTRUCT()
UENUM() enum class ERigVMRegisterType USTRUCT ()
The type of register within the memory.
The FRigVMMemoryContainer provides a heterogeneous memory container to store arbitrary data.
Each element stored can be referred to using a FRigVMRegister. Elements can be accessed by index (index of the register), FRigVMOperand or by name. Name access is optional and is specified upon construction of the container. The memory container provides a series of templated functions to add and get data.
For example: int32 Index = Container.Add<float>(4.f); float& ValueRef = Container.GetRef<float>(Index);
This can also be done with arrays: TArray<float> MyArray = {3.f, 4.f, 5.f}; int32 Index = Container.AddFixedArray<float>(MyArray); FRigVMFixedArray<float> ArrayView = Container.GetFixedArray<float>(Index);
Registers can store dynamically resizable memory as well by reyling on indirection.
Arrays with a single slice are going to be stored as a FRigVMByteArray, [unit8], so for example for a float array in C++ it would be (TArray<float> Param). Single values with multiple slices are also going to be stored as a FRigVMByteArray, [unit8], so for example for a float array in C++ it would be (float Param). Arrays with multiple slices are going to be stored as a FRigVMNestedByteArray, [[unit8]], so for example for a float array in C++ it would be (TArray<float> Param).
Definition at line 53 of file RigVMMemoryDeprecated.h.
References Ar, ensure, GENERATED_BODY, INDEX_NONE, Load, Name, operator<<(), Save, FArchive::Serialize(), UScriptStruct::Serialize(), transient, UE_API, and UPROPERTY.