Unreal Engine 5.6 C++ API: S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/RigVM/Source/RigVMDeveloper/Public/RigVMModel/RigVMClient.h File Reference
RigVMClient.h File Reference
#include "RigVMGraph.h"
#include "RigVMSchema.h"
#include "RigVMFunctionLibrary.h"
#include "RigVMController.h"
#include "UObject/WeakInterfacePtr.h"
#include "RigVMClient.generated.h"
Data Structures
class IRigVMClientExternalModelHost
class IRigVMClientHost
class IRigVMEditorSideObject
Enumerations
enum class ERigVMLoadType : uint8 { PostLoad , CheckUserDefinedStructs }
Functions
DECLARE_DELEGATE_RetVal (URigVMGraph *, FRigVMGetFocusedGraph)
USTRUCT () struct RIGVMDEVELOPER_API FRigVMClient
Enumeration Type Documentation
ERigVMLoadType
enum class ERigVMLoadType : uint8 strong
Enumerator
PostLoad
CheckUserDefinedStructs
Definition at line 20 of file RigVMClient.h.
Function Documentation
DECLARE_DELEGATE_RetVal()
DECLARE_DELEGATE_RetVal (URigVMGraph * , FRigVMGetFocusedGraph)
USTRUCT()
USTRUCT ()
Definition at line 204 of file RigVMClient.h.
References begin(), TArray< InElementType, InAllocatorType >::begin(), end(), TArray< InElementType, InAllocatorType >::end(), GENERATED_BODY, InName, InOuter, EPropertyChangeType::Interactive, Name, Num, PreSave, Reset, TEXT, transient, UE_DEPRECATED, and UPROPERTY.