Unreal Engine 5.6 C++ API: S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/RigVM/Source/RigVM/Public/RigVMCore/RigVMExecuteContext.h File Reference
RigVMExecuteContext.h File Reference
#include "Containers/Array.h"
#include "Containers/ArrayView.h"
#include "Containers/UnrealString.h"
#include "CoreMinimal.h"
#include "Components/SceneComponent.h"
#include "GameFramework/Actor.h"
#include "Logging/LogCategory.h"
#include "Logging/LogMacros.h"
#include "Logging/TokenizedMessage.h"
#include "Math/UnrealMathSSE.h"
#include "Misc/AssertionMacros.h"
#include "RigVMDefines.h"
#include "RigVMModule.h"
#include "RigVMCore/RigVMDebugInfo.h"
#include "RigVMCore/RigVMProfilingInfo.h"
#include "RigVMCore/RigVMNameCache.h"
#include "RigVMCore/RigVMMemoryStorageStruct.h"
#include "RigVMCore/RigVMTraitScope.h"
#include "RigVMLog.h"
#include "RigVMDrawInterface.h"
#include "RigVMDrawContainer.h"
#include "RigVMMemoryStorage.h"
#include "Templates/SharedPointer.h"
#include "Trace/Detail/Channel.h"
#include "UObject/NameTypes.h"
#include "UObject/ObjectMacros.h"
#include "UObject/StructOnScope.h"
#include "UObject/UnrealNames.h"
#include "UObject/UnrealType.h"
#include "RigVMExecuteContext.generated.h"
Data Structures
struct FRigVMExecuteContextFixLayout
struct FRigVMExternalVariableRuntimeData
struct TStructOpsTypeTraits< FRigVMExecuteContext >
The execute context is used for mutable nodes to indicate execution order.
Macros
#define UE_API RIGVM_API
Functions
USTRUCT () struct FRigVMExtendedExecuteContext
The execute context is used for mutable nodes to indicate execution order.
Variables
RIGVM_API TAutoConsoleVariable< bool > CVarRigVMReportAllMessages
Macro Definition Documentation
UE_API
#define UE_API RIGVM_API
Definition at line 37 of file RigVMExecuteContext.h.
Function Documentation
USTRUCT()
USTRUCT ()
The execute context is used for mutable nodes to indicate execution order.
The largest allowed size for arrays within the RigVM. Accessing or creating larger arrays will cause runtime errors in the rig.
Full context reset
Resets VM execution state
Bindable event for external objects to be notified when the VM reaches an Exit Operation
Definition at line 47 of file RigVMExecuteContext.h.
References bool, float, GENERATED_BODY, GetTypeHash(), HashCombine(), INDEX_NONE, IsValid(), FMath::Max, Num, operator!(), operator++(), and Reset.
Variable Documentation
CVarRigVMReportAllMessages
RIGVM_API TAutoConsoleVariable<bool> CVarRigVMReportAllMessages extern