Unreal Engine 5.6 C++ API: Runtime/Engine/Public/SceneManagement.h File Reference
SceneManagement.h File Reference
#include "CoreMinimal.h"
#include "Containers/ChunkedArray.h"
#include "Stats/Stats.h"
#include "Misc/Guid.h"
#include "Misc/MemStack.h"
#include "Misc/IQueuedWork.h"
#include "RHI.h"
#include "RenderResource.h"
#include "EngineDefines.h"
#include "HitProxies.h"
#include "SceneTypes.h"
#include "ConvexVolume.h"
#include "PrimitiveDrawingUtils.h"
#include "PrimitiveUniformShaderParameters.h"
#include "RendererInterface.h"
#include "BatchedElements.h"
#include "MeshBatch.h"
#include "MeshElementCollector.h"
#include "SceneUtils.h"
#include "LightmapUniformShaderParameters.h"
#include "DynamicBufferAllocator.h"
#include "Math/SHMath.h"
#include "GlobalRenderResources.h"
Data Structures
class FAsyncEncode< TPendingTextureType >
class FDefaultLightmapResourceClusterUniformBuffer
class FDynamicPrimitiveResource
An interface implemented by dynamic resources which need to be initialized and cleaned up by the rendering thread.
class FDynamicPrimitiveUniformBuffer
class FFrozenSceneViewMatricesGuard
class FLightCacheInterface
An interface to cached lighting for a specific mesh.
class FLightInteraction
Information about an interaction between a light and a mesh.
class FLightMapInteraction
Make sure at least one is defined.
struct FLODMask
Contains LODs to render.
struct FMeshBatchAndRelevance
A reference to a mesh batch that is added to the collector, together with some cached relevance flags.
class FOneFrameResource
Base class for a resource allocated from a FMeshElementCollector with AllocateOneFrameResource, which the collector releases.
class FPerObjectProjectedShadowInitializer
Information needed to create a per-object projected shadow.
class FProjectedShadowInitializer
A projected shadow transform.
class FSceneViewStateInterface
The scene manager's persistent view state.
class FShadowCascadeSettings
class FShadowMapInteraction
Information about the static shadowing information for a primitive.
class FSharedSamplerState
class FSimpleElementCollector
Primitive draw interface implementation used to store primitives requested to be drawn when gathering dynamic mesh elements.
class FSimpleElementCollector::FAllocationInfo
class FStaticPrimitiveDrawInterface
An interface used to query a primitive for its static elements.
struct FTemporalLODState
struct to hold the temporal LOD state within a view state
class FViewElementDrawer
An interface to a scene interaction.
class FWholeSceneProjectedShadowInitializer
Information needed to create a whole scene projected shadow.
Namespaces
namespace RayTracing
namespace UE
Utility functions for applying transformations to meshes.
namespace UE::Color
Macros
#define ALLOW_HQ_LIGHTMAPS 1
Compile out high quality lightmaps to save memory.
#define ALLOW_LQ_LIGHTMAPS (PLATFORM_DESKTOP || PLATFORM_IOS || PLATFORM_ANDROID)
Compile out low quality lightmaps to save memory.
#define RayTracing::UE_DEPRECATED(Version, Message)
Macro for marking up deprecated code, functions and types.
Typedefs
using RayTracing::FGeometryGroupHandle = int32
using RayTracing::FGeometryGroupHandle
using RayTracing::FGeometryGroupHandle
Enumerations
enum ELightInteractionType {
LIT_CachedIrrelevant , LIT_CachedLightMap , LIT_Dynamic , LIT_CachedSignedDistanceFieldShadowMap2D ,
LIT_MAX
}
The types of interactions between a light and a primitive.
enum ESequencerState { ESS_None , ESS_Paused , ESS_Playing }
Functions
void ApplyViewModeOverrides (int32 ViewIndex, const FEngineShowFlags &EngineShowFlags, ERHIFeatureLevel::Type FeatureLevel, const FPrimitiveSceneProxy *PrimitiveSceneProxy, bool bSelected, struct FMeshBatch &Mesh, FMeshElementCollector &Collector)
BEGIN_GLOBAL_SHADER_PARAMETER_STRUCT (FLightmapResourceClusterShaderParameters, 1) SHADER_PARAMETER_TEXTURE(Texture2D
BEGIN_GLOBAL_SHADER_PARAMETER_STRUCT (FMobileReflectionCaptureShaderParameters, 1) SHADER_PARAMETER(FVector4f
BEGIN_GLOBAL_SHADER_PARAMETER_STRUCT (FWorkingColorSpaceShaderParameters, 1) SHADER_PARAMETER(FMatrix44f
Global working color space shader parameters (color space conversion matrices).
BEGIN_SHADER_PARAMETER_STRUCT (FLightShaderParameters, 1) SHADER_PARAMETER(FVector3f
Shader paraneter structure for rendering lights.
void BuildConeVerts (float Angle1, float Angle2, float Scale, float XOffset, uint32 NumSides, TArray< FDynamicMeshVertex > &OutVerts, TArray< uint32 > &OutIndices)
void BuildCylinderVerts (const FVector &Base, const FVector &XAxis, const FVector &YAxis, const FVector &ZAxis, double Radius, double HalfHeight, uint32 Sides, TArray< FDynamicMeshVertex > &OutVerts, TArray< uint32 > &OutIndices)
FVector CalcConeVert (float Angle1, float Angle2, float AzimuthAngle)
float ComputeBoundsDrawDistance (const float ScreenSize, const float SphereRadius, const FMatrix &ProjMatrix)
Computes the draw distance of a given sphere bounds in the given view with the specified screen size.
float ComputeBoundsScreenRadiusSquared (const FVector4 &BoundsOrigin, const float SphereRadius, const FVector4 &ViewOrigin, const FMatrix &ProjMatrix)
Computes the screen radius squared of a given sphere bounds in the given view.
float ComputeBoundsScreenRadiusSquared (const FVector4 &Origin, const float SphereRadius, const FSceneView &View)
Computes the screen radius squared of a given sphere bounds in the given view.
float ComputeBoundsScreenSize (const FVector4 &BoundsOrigin, const float SphereRadius, const FVector4 &ViewOrigin, const FMatrix &ProjMatrix)
Computes the screen size of a given sphere bounds in the given view.
float ComputeBoundsScreenSize (const FVector4 &Origin, const float SphereRadius, const FSceneView &View)
Computes the screen size of a given sphere bounds in the given view.
FLODMask ComputeLODForMeshes (const TArray< class FStaticMeshBatchRelevance > &StaticMeshRelevances, const FSceneView &View, const FVector4 &Origin, float SphereRadius, float InstanceSphereRadius, int32 ForcedLODLevel, float &OutScreenRadiusSquared, int8 CurFirstLODIdx, float ScreenSizeScale=1.0f)
Computes the LOD to render for the list of static meshes in the given view.
FLODMask ComputeLODForMeshes (const TArray< class FStaticMeshBatchRelevance > &StaticMeshRelevances, const FSceneView &View, const FVector4 &Origin, float SphereRadius, int32 ForcedLODLevel, float &OutScreenRadiusSquared, int8 CurFirstLODIdx, float ScreenSizeScale=1.0f, bool bDitheredLODTransition=true)
Computes the LOD to render for the list of static meshes in the given view.
void ComputeShadowCullingVolume (bool bReverseCulling, const FVector *CascadeFrustumVerts, const FVector &LightDirection, FConvexVolume &ConvexVolumeOut, FPlane &NearPlaneOut, FPlane &FarPlaneOut)
int8 ComputeStaticMeshLOD (const FStaticMeshRenderData *RenderData, const FVector4 &Origin, const float SphereRadius, const FSceneView &View, int32 MinLOD, float FactorScale=1.0f)
Computes the LOD level for the given static meshes render data in the given view.
int8 ComputeTemporalStaticMeshLOD (const FStaticMeshRenderData *RenderData, const FVector4 &Origin, const float SphereRadius, const FSceneView &View, int32 MinLOD, float FactorScale, int32 SampleIndex)
Computes the LOD level for the given static meshes render data in the given view, for one of the two temporal LOD samples.
DECLARE_LOG_CATEGORY_EXTERN (LogBufferVisualization, Log, All)
DECLARE_LOG_CATEGORY_EXTERN (LogLumenVisualization, Log, All)
DECLARE_LOG_CATEGORY_EXTERN (LogMultiView, Log, All)
DECLARE_LOG_CATEGORY_EXTERN (LogNaniteVisualization, Log, All)
DECLARE_LOG_CATEGORY_EXTERN (LogVirtualShadowMapVisualization, Log, All)
bool DoesPlatformSupportDistanceFieldAO (EShaderPlatform Platform)
bool DoesPlatformSupportDistanceFields (const FStaticShaderPlatform Platform)
bool DoesPlatformSupportDistanceFieldShadowing (EShaderPlatform Platform)
bool DoesProjectSupportDistanceFields ()
void DrawUVs (FViewport *InViewport, FCanvas *InCanvas, int32 InTextYPos, const int32 LODLevel, int32 UVChannel, TArray< FVector2D > SelectedEdgeTexCoords, class FStaticMeshRenderData *StaticMeshRenderData, class FSkeletalMeshLODRenderData *SkeletalMeshRenderData)
Draws the UV layout of the supplied asset (either StaticMeshRenderData OR SkeletalMeshRenderData, not both!)
TranslatedWorldPosition Color Direction DiffuseScale SourceRadius SoftSourceRadius RectLightBarnCosAngle RectLightAtlasUVOffset RectLightAtlasMaxLevel LightFunctionAtlasLightIndex SpotLightShadowmapMinMax LocalLightShadowBufferSize LocalLightShadowSampler END_GLOBAL_SHADER_PARAMETER_STRUCT () struct FLightRenderParameters
Generic parameters used to render a light Has a 1:1 mapping with FLightShaderParameters, but can also be used in other contexts Primary difference is position is stored as FVector3d in absolute world space, which is not appropriate for sending directly to GPU.
void GetLightmapClusterResourceParameters (ERHIFeatureLevel::Type FeatureLevel, const FLightmapClusterResourceInput &Input, const IAllocatedVirtualTexture *AllocatedVT, FLightmapResourceClusterShaderParameters &Parameters)
const FSceneView & GetLODView (const FSceneView &InView)
Will return the view to use taking into account VR which has 2 views.
FLinearColor GetSelectionColor (const FLinearColor &BaseColor, bool bSelected, bool bHovered, bool bUseOverlayIntensity=true)
Given a base color and a selection state, returns a color which accounts for the selection state.
FLinearColor GetViewSelectionColor (const FLinearColor &BaseColor, const FSceneView &View, bool bSelected, bool bHovered, bool bUseOverlayIntensity, bool bIndividuallySelected)
void InitializeSharedSamplerStates ()
Initializes the shared sampler states.
bool IsRichView (const FSceneViewFamily &ViewFamily)
Returns true if the given view is "rich", and all primitives should be forced down the dynamic drawing path so that ApplyViewModeOverrides can implement the rich view feature.
bool PrimitiveNeedsDistanceFieldSceneData (bool bTrackAllPrimitives, bool bCastsDynamicIndirectShadow, bool bAffectsDistanceFieldLighting, bool bIsDrawnInGame, bool bCastsHiddenShadow, bool bCastsDynamicShadow, bool bAffectsDynamicIndirectLighting, bool bAffectIndirectLightingWhileHidden)
Centralized decision function to avoid diverging logic.
TranslatedWorldPosition Color SHADER_PARAMETER (float, FalloffExponent) SHADER_PARAMETER(FVector3f
TranslatedWorldPosition Color Direction DiffuseScale SourceRadius SoftSourceRadius RectLightBarnCosAngle RectLightAtlasUVOffset RectLightAtlasMaxLevel SHADER_PARAMETER (float, IESAtlasIndex) SHADER_PARAMETER(uint32
TranslatedWorldPosition SHADER_PARAMETER (float, InvRadius) SHADER_PARAMETER(FVector3f
TranslatedWorldPosition Color Direction DiffuseScale SourceRadius SoftSourceRadius RectLightBarnCosAngle SHADER_PARAMETER (float, RectLightBarnLength) SHADER_PARAMETER(FVector2f
TranslatedWorldPosition Color Direction DiffuseScale SourceRadius SoftSourceRadius SHADER_PARAMETER (float, SourceLength) SHADER_PARAMETER(float
TranslatedWorldPosition Color Direction SHADER_PARAMETER (float, SpecularScale) SHADER_PARAMETER(float
ToXYZ ToAP1 ToAP0 SHADER_PARAMETER (FMatrix44f, FromAP0) SHADER_PARAMETER(uint32
ToXYZ ToAP1 SHADER_PARAMETER (FMatrix44f, FromAP1) SHADER_PARAMETER(FMatrix44f
ToXYZ SHADER_PARAMETER (FMatrix44f, FromXYZ) SHADER_PARAMETER(FMatrix44f
TranslatedWorldPosition Color Direction DiffuseScale SourceRadius SoftSourceRadius RectLightBarnCosAngle RectLightAtlasUVOffset RectLightAtlasMaxLevel LightFunctionAtlasLightIndex SpotLightShadowmapMinMax SHADER_PARAMETER (FMatrix44f, SpotLightShadowWorldToShadowMatrix) SHADER_PARAMETER(FVector4f
TranslatedWorldPosition Color Direction DiffuseScale SourceRadius SoftSourceRadius RectLightBarnCosAngle RectLightAtlasUVOffset SHADER_PARAMETER (FVector2f, RectLightAtlasUVScale) SHADER_PARAMETER(float
TranslatedWorldPosition Color Direction DiffuseScale SourceRadius SHADER_PARAMETER (FVector2f, SpotAngles) SHADER_PARAMETER(float
TranslatedWorldPosition Color Direction DiffuseScale SHADER_PARAMETER (FVector3f, Tangent) SHADER_PARAMETER(float
TranslatedWorldPosition Color Direction DiffuseScale SourceRadius SoftSourceRadius RectLightBarnCosAngle RectLightAtlasUVOffset RectLightAtlasMaxLevel LightFunctionAtlasLightIndex SHADER_PARAMETER (FVector4f, SpotLightShadowSharpenAndFadeFractionAndReceiverDepthBiasAndSoftTransitionScale) SHADER_PARAMETER(FVector4f
TranslatedWorldPosition Color Direction DiffuseScale SourceRadius SoftSourceRadius RectLightBarnCosAngle RectLightAtlasUVOffset RectLightAtlasMaxLevel LightFunctionAtlasLightIndex SHADER_PARAMETER (uint32, bAffectsTranslucentLighting) END_SHADER_PARAMETER_STRUCT() BEGIN_SHADER_PARAMETER_STRUCT(FMobileMovableLocalLightShadowParameters
LightMapTexture AOMaterialMaskTexture VTLightMapTexture VTSkyOcclusionTexture VTStaticShadowTexture SHADER_PARAMETER_SAMPLER (SamplerState, LightMapSampler) SHADER_PARAMETER_SAMPLER(SamplerState
LightMapTexture AOMaterialMaskTexture VTLightMapTexture VTSkyOcclusionTexture VTStaticShadowTexture LightMapSampler_1 SHADER_PARAMETER_SAMPLER (SamplerState, SkyOcclusionSampler) SHADER_PARAMETER_SAMPLER(SamplerState
LightMapTexture AOMaterialMaskTexture VTLightMapTexture VTSkyOcclusionTexture VTStaticShadowTexture LightMapSampler_1 AOMaterialMaskSampler SHADER_PARAMETER_SAMPLER (SamplerState, StaticShadowTextureSampler) SHADER_PARAMETER_TEXTURE(Texture2D< uint4 >
LightMapTexture AOMaterialMaskTexture VTLightMapTexture VTSkyOcclusionTexture SHADER_PARAMETER_SRV (Texture2D< float4 >, VTAOMaterialMaskTexture) SHADER_PARAMETER_SRV(Texture2D< float4 >
LightMapTexture AOMaterialMaskTexture VTLightMapTexture SHADER_PARAMETER_SRV (Texture2D< float4 >, VTLightMapTexture_1) SHADER_PARAMETER_SRV(Texture2D< float4 >
TranslatedWorldPosition Color Direction DiffuseScale SourceRadius SoftSourceRadius RectLightBarnCosAngle RectLightAtlasUVOffset RectLightAtlasMaxLevel LightFunctionAtlasLightIndex SpotLightShadowmapMinMax LocalLightShadowBufferSize SHADER_PARAMETER_TEXTURE (Texture2D, LocalLightShadowTexture) SHADER_PARAMETER_SAMPLER(SamplerState
LightMapTexture SHADER_PARAMETER_TEXTURE (Texture2D, SkyOcclusionTexture) SHADER_PARAMETER_TEXTURE(Texture2D
LightMapTexture AOMaterialMaskTexture SHADER_PARAMETER_TEXTURE (Texture2D, StaticShadowTexture) SHADER_PARAMETER_SRV(Texture2D< float4 >
LightMapTexture AOMaterialMaskTexture VTLightMapTexture VTSkyOcclusionTexture VTStaticShadowTexture LightMapSampler_1 AOMaterialMaskSampler LightmapVirtualTexturePageTable0 SHADER_PARAMETER_TEXTURE (Texture2D< uint4 >, LightmapVirtualTexturePageTable1) END_GLOBAL_SHADER_PARAMETER_STRUCT() class FLightmapClusterResourceInput
Params SHADER_PARAMETER_TEXTURE (TextureCube, Texture) SHADER_PARAMETER_SAMPLER(SamplerState
Params TextureSampler SHADER_PARAMETER_TEXTURE (TextureCube, TextureBlend) SHADER_PARAMETER_SAMPLER(SamplerState
bool ShouldAllPrimitivesHaveDistanceField (EShaderPlatform ShaderPlatform)
bool ShouldCompileDistanceFieldShaders (EShaderPlatform ShaderPlatform)
Variables
FSharedSamplerState * Clamp_WorldGroupSettings
Sampler state using Clamp addressing and taking filter mode from the world texture group.
TGlobalResource< FDefaultLightmapResourceClusterUniformBuffer > GDefaultLightmapResourceClusterUniformBuffer
Params TextureSampler TextureBlendSampler END_GLOBAL_SHADER_PARAMETER_STRUCT() class FDefaultMobileReflectionCaptureUniformBuffer TGlobalResource< FDefaultMobileReflectionCaptureUniformBuffer > GDefaultMobileReflectionCaptureUniformBuffer
ToXYZ ToAP1 ToAP0 bIsSRGB END_SHADER_PARAMETER_STRUCT() class FDefaultWorkingColorSpaceUniformBuffer TGlobalResource< FDefaultWorkingColorSpaceUniformBuffer > GDefaultWorkingColorSpaceUniformBuffer
constexpr int32 LQ_LIGHTMAP_COEF_INDEX = 2
The index at which simple coefficients are stored in any array containing all NUM_STORED_LIGHTMAP_COEF coefficients.
constexpr int32 NUM_HQ_LIGHTMAP_COEF = 2
The number of directional coefficients which the lightmap stores for each light sample.
constexpr int32 NUM_LQ_LIGHTMAP_COEF = 2
The number of simple coefficients which the lightmap stores for each light sample.
constexpr int32 NUM_STORED_LIGHTMAP_COEF = 4
The number of coefficients that are stored for each light sample.
FSharedSamplerState * Wrap_WorldGroupSettings
Sampler state using Wrap addressing and taking filter mode from the world texture group.
Macro Definition Documentation
ALLOW_HQ_LIGHTMAPS
#define ALLOW_HQ_LIGHTMAPS 1
Compile out high quality lightmaps to save memory.
Definition at line 388 of file SceneManagement.h.
Referenced by FLightMapInteraction::FLightMapInteraction().
ALLOW_LQ_LIGHTMAPS
#define ALLOW_LQ_LIGHTMAPS (PLATFORM_DESKTOP || PLATFORM_IOS || PLATFORM_ANDROID)
Compile out low quality lightmaps to save memory.
Definition at line 384 of file SceneManagement.h.
Referenced by FLightMapInteraction::FLightMapInteraction().
Enumeration Type Documentation
ELightInteractionType
enum ELightInteractionType
The types of interactions between a light and a primitive.
Enumerator
LIT_CachedIrrelevant
LIT_CachedLightMap
LIT_Dynamic
LIT_CachedSignedDistanceFieldShadowMap2D
LIT_MAX
Definition at line 328 of file SceneManagement.h.
ESequencerState
enum ESequencerState
Enumerator
ESS_None
ESS_Paused
ESS_Playing
Definition at line 117 of file SceneManagement.h.
Function Documentation
ApplyViewModeOverrides()
void ApplyViewModeOverrides (int32 ViewIndex, const FEngineShowFlags & EngineShowFlags, ERHIFeatureLevel::Type FeatureLevel, const FPrimitiveSceneProxy * PrimitiveSceneProxy, bool bSelected, struct FMeshBatch & Mesh, FMeshElementCollector & Collector) extern
References ApplyViewModeOverrides(), and Mesh.
Referenced by ApplyViewModeOverrides().
BEGIN_GLOBAL_SHADER_PARAMETER_STRUCT() [1/3]
BEGIN_GLOBAL_SHADER_PARAMETER_STRUCT (FLightmapResourceClusterShaderParameters , 1)
References Texture2D.
BEGIN_GLOBAL_SHADER_PARAMETER_STRUCT() [2/3]
BEGIN_GLOBAL_SHADER_PARAMETER_STRUCT (FMobileReflectionCaptureShaderParameters , 1)
References Params.
BEGIN_GLOBAL_SHADER_PARAMETER_STRUCT() [3/3]
BEGIN_GLOBAL_SHADER_PARAMETER_STRUCT (FWorkingColorSpaceShaderParameters , 1)
Global working color space shader parameters (color space conversion matrices).
BEGIN_SHADER_PARAMETER_STRUCT()
BEGIN_SHADER_PARAMETER_STRUCT (FLightShaderParameters , 1)
Shader paraneter structure for rendering lights.
BuildConeVerts()
void BuildConeVerts (float Angle1, float Angle2, float Scale, float XOffset, uint32 NumSides, TArray< FDynamicMeshVertex > & OutVerts, TArray< uint32 > & OutIndices) extern
References BuildConeVerts(), and Scale.
Referenced by BuildConeVerts().
BuildCylinderVerts()
void BuildCylinderVerts (const FVector & Base, const FVector & XAxis, const FVector & YAxis, const FVector & ZAxis, double Radius, double HalfHeight, uint32 Sides, TArray< FDynamicMeshVertex > & OutVerts, TArray< uint32 > & OutIndices)
References BuildCylinderVerts(), and FVector.
Referenced by BuildCylinderVerts().
CalcConeVert()
FVector CalcConeVert (float Angle1, float Angle2, float AzimuthAngle) extern
References CalcConeVert(), and FVector.
Referenced by CalcConeVert().
ComputeBoundsDrawDistance()
float ComputeBoundsDrawDistance (const float ScreenSize, const float SphereRadius, const FMatrix & ProjMatrix)
Computes the draw distance of a given sphere bounds in the given view with the specified screen size.
Parameters
ScreenSize - The screen size (as computed by ComputeBoundsScreenSize)
SphereRadius - Radius of the sphere to use to calculate screen coverage
ProjMatrix - The projection matrix used to scale screen size bounds
Returns
float - The draw distance calculated
References ComputeBoundsDrawDistance().
Referenced by ComputeBoundsDrawDistance().
ComputeBoundsScreenRadiusSquared() [1/2]
float ComputeBoundsScreenRadiusSquared (const FVector4 & BoundsOrigin, const float SphereRadius, const FVector4 & ViewOrigin, const FMatrix & ProjMatrix)
Computes the screen radius squared of a given sphere bounds in the given view.
This is used at runtime instead of ComputeBoundsScreenSize to avoid a square root.
Parameters
Origin - Origin of the bounds in world space
SphereRadius - Radius of the sphere to use to calculate screen coverage
ViewOrigin - The view origin involved in the calculation
ProjMatrix - The projection matrix of the view involved in the calculation
Returns
float - The screen size calculated
References ComputeBoundsScreenRadiusSquared().
ComputeBoundsScreenRadiusSquared() [2/2]
float ComputeBoundsScreenRadiusSquared (const FVector4 & Origin, const float SphereRadius, const FSceneView & View)
Computes the screen radius squared of a given sphere bounds in the given view.
This is used at runtime instead of ComputeBoundsScreenSize to avoid a square root. It is a wrapper for the version below that does not take a FSceneView reference but parameters directly
Parameters
Origin - Origin of the bounds in world space
SphereRadius - Radius of the sphere to use to calculate screen coverage
View - The view to calculate the display factor for
Returns
float - The screen size calculated
References ComputeBoundsScreenRadiusSquared(), and Origin.
Referenced by ComputeBoundsScreenRadiusSquared(), and ComputeBoundsScreenRadiusSquared().
ComputeBoundsScreenSize() [1/2]
float ComputeBoundsScreenSize (const FVector4 & BoundsOrigin, const float SphereRadius, const FVector4 & ViewOrigin, const FMatrix & ProjMatrix)
Computes the screen size of a given sphere bounds in the given view.
The screen size is the projected diameter of the bounding sphere of the model. i.e. 0.5 means half the screen's maximum dimension.
Parameters
BoundsOrigin - Origin of the bounds in world space
SphereRadius - Radius of the sphere to use to calculate screen coverage
ViewOrigin - The origin of the view to calculate the display factor for
ProjMatrix - The projection matrix used to scale screen size bounds
Returns
float - The screen size calculated
References ComputeBoundsScreenSize().
ComputeBoundsScreenSize() [2/2]
float ComputeBoundsScreenSize (const FVector4 & Origin, const float SphereRadius, const FSceneView & View)
Computes the screen size of a given sphere bounds in the given view.
The screen size is the projected diameter of the bounding sphere of the model. i.e. 0.5 means half the screen's maximum dimension.
Parameters
Origin - Origin of the bounds in world space
SphereRadius - Radius of the sphere to use to calculate screen coverage
View - The view to calculate the display factor for
Returns
float - The screen size calculated
References ComputeBoundsScreenSize(), and Origin.
Referenced by ComputeBoundsScreenSize(), and ComputeBoundsScreenSize().
ComputeLODForMeshes() [1/2]
FLODMask ComputeLODForMeshes (const TArray< class FStaticMeshBatchRelevance > & StaticMeshRelevances, const FSceneView & View, const FVector4 & Origin, float SphereRadius, float InstanceSphereRadius, int32 ForcedLODLevel, float & OutScreenRadiusSquared, int8 CurFirstLODIdx, float ScreenSizeScale = 1.0f)
Computes the LOD to render for the list of static meshes in the given view.
Parameters
StaticMeshes - List of static meshes.
View - The view to render the LOD level for
Origin - Origin of the bounds of the primitive in world space
SphereRadius - Radius of the sphere bounds of the primitive in world space
InstanceSphereRadius - Radius of the sphere bounds for a single mesh instance in the primitive. If not 0.f then the return FLODMask will contain a range of LODs ready for LOD selection on the GPU
References Origin.
ComputeLODForMeshes() [2/2]
FLODMask ComputeLODForMeshes (const TArray< class FStaticMeshBatchRelevance > & StaticMeshRelevances, const FSceneView & View, const FVector4 & Origin, float SphereRadius, int32 ForcedLODLevel, float & OutScreenRadiusSquared, int8 CurFirstLODIdx, float ScreenSizeScale = 1.0f, bool bDitheredLODTransition = true)
Computes the LOD to render for the list of static meshes in the given view.
Parameters
StaticMeshes - List of static meshes.
View - The view to render the LOD level for
Origin - Origin of the bounds of the primitive in world space
SphereRadius - Radius of the sphere bounds of the primitive in world space
References Origin.
ComputeShadowCullingVolume()
void ComputeShadowCullingVolume (bool bReverseCulling, const FVector * CascadeFrustumVerts, const FVector & LightDirection, FConvexVolume & ConvexVolumeOut, FPlane & NearPlaneOut, FPlane & FarPlaneOut) extern
References FVector.
ComputeStaticMeshLOD()
int8 ComputeStaticMeshLOD (const FStaticMeshRenderData * RenderData, const FVector4 & Origin, const float SphereRadius, const FSceneView & View, int32 MinLOD, float FactorScale = 1.0f)
Computes the LOD level for the given static meshes render data in the given view.
Parameters
RenderData - Render data for the mesh
Origin - Origin of the bounds of the mesh in world space
SphereRadius - Radius of the sphere to use to calculate screen coverage
View - The view to calculate the LOD level for
FactorScale - multiplied by the computed screen size before computing LOD
References ComputeStaticMeshLOD(), MinLOD, Origin, and RenderData.
Referenced by ComputeStaticMeshLOD().
ComputeTemporalStaticMeshLOD()
int8 ComputeTemporalStaticMeshLOD (const FStaticMeshRenderData * RenderData, const FVector4 & Origin, const float SphereRadius, const FSceneView & View, int32 MinLOD, float FactorScale, int32 SampleIndex)
Computes the LOD level for the given static meshes render data in the given view, for one of the two temporal LOD samples.
Parameters
RenderData - Render data for the mesh
Origin - Origin of the bounds of the mesh in world space
SphereRadius - Radius of the sphere to use to calculate screen coverage
View - The view to calculate the LOD level for
FactorScale - multiplied by the computed screen size before computing LOD
SampleIndex - index (0 or 1) of the temporal sample to use
References ComputeTemporalStaticMeshLOD(), MinLOD, Origin, and RenderData.
Referenced by ComputeTemporalStaticMeshLOD().
DECLARE_LOG_CATEGORY_EXTERN() [1/5]
DECLARE_LOG_CATEGORY_EXTERN (LogBufferVisualization , Log , All)
References All, and Log.
DECLARE_LOG_CATEGORY_EXTERN() [2/5]
DECLARE_LOG_CATEGORY_EXTERN (LogLumenVisualization , Log , All)
References All, and Log.
DECLARE_LOG_CATEGORY_EXTERN() [3/5]
DECLARE_LOG_CATEGORY_EXTERN (LogMultiView , Log , All)
References All, and Log.
DECLARE_LOG_CATEGORY_EXTERN() [4/5]
DECLARE_LOG_CATEGORY_EXTERN (LogNaniteVisualization , Log , All)
References All, and Log.
DECLARE_LOG_CATEGORY_EXTERN() [5/5]
DECLARE_LOG_CATEGORY_EXTERN (LogVirtualShadowMapVisualization , Log , All)
References All, and Log.
DoesPlatformSupportDistanceFieldAO()
bool DoesPlatformSupportDistanceFieldAO (EShaderPlatform Platform)
References Platform.
DoesPlatformSupportDistanceFields()
bool DoesPlatformSupportDistanceFields (const FStaticShaderPlatform Platform)
References Platform.
DoesPlatformSupportDistanceFieldShadowing()
bool DoesPlatformSupportDistanceFieldShadowing (EShaderPlatform Platform)
References Platform.
DoesProjectSupportDistanceFields()
bool DoesProjectSupportDistanceFields ()
DrawUVs()
void DrawUVs (FViewport * InViewport, FCanvas * InCanvas, int32 InTextYPos, const int32 LODLevel, int32 UVChannel, TArray< FVector2D > SelectedEdgeTexCoords, class FStaticMeshRenderData * StaticMeshRenderData, class FSkeletalMeshLODRenderData * SkeletalMeshRenderData) extern
Draws the UV layout of the supplied asset (either StaticMeshRenderData OR SkeletalMeshRenderData, not both!)
References DrawUVs().
Referenced by DrawUVs().
END_GLOBAL_SHADER_PARAMETER_STRUCT()
TranslatedWorldPosition Color Direction DiffuseScale SourceRadius SoftSourceRadius RectLightBarnCosAngle RectLightAtlasUVOffset RectLightAtlasMaxLevel LightFunctionAtlasLightIndex SpotLightShadowmapMinMax LocalLightShadowBufferSize LocalLightShadowSampler END_GLOBAL_SHADER_PARAMETER_STRUCT ()
Generic parameters used to render a light Has a 1:1 mapping with FLightShaderParameters, but can also be used in other contexts Primary difference is position is stored as FVector3d in absolute world space, which is not appropriate for sending directly to GPU.
Definition at line 1192 of file SceneManagement.h.
GetLightmapClusterResourceParameters()
void GetLightmapClusterResourceParameters (ERHIFeatureLevel::Type FeatureLevel, const FLightmapClusterResourceInput & Input, const IAllocatedVirtualTexture * AllocatedVT, FLightmapResourceClusterShaderParameters & Parameters)
References Input.
GetLODView()
const FSceneView & GetLODView (const FSceneView & InView)
Will return the view to use taking into account VR which has 2 views.
References GetLODView().
Referenced by GetLODView().
GetSelectionColor()
FLinearColor GetSelectionColor (const FLinearColor & BaseColor, bool bSelected, bool bHovered, bool bUseOverlayIntensity = true) extern
Given a base color and a selection state, returns a color which accounts for the selection state.
Parameters
BaseColor - The base color of the object.
bSelected - The selection state of the object.
bHovered - True if the object has hover focus
bUseOverlayIntensity - True if the selection color should be modified by the selection intensity
Returns
The color to draw the object with, accounting for the selection state
References BaseColor, and GetSelectionColor().
Referenced by GetSelectionColor().
GetViewSelectionColor()
FLinearColor GetViewSelectionColor (const FLinearColor & BaseColor, const FSceneView & View, bool bSelected, bool bHovered, bool bUseOverlayIntensity, bool bIndividuallySelected) extern
References BaseColor, and GetViewSelectionColor().
Referenced by GetViewSelectionColor().
InitializeSharedSamplerStates()
void InitializeSharedSamplerStates () extern
Initializes the shared sampler states.
IsRichView()
bool IsRichView (const FSceneViewFamily & ViewFamily) extern
Returns true if the given view is "rich", and all primitives should be forced down the dynamic drawing path so that ApplyViewModeOverrides can implement the rich view feature.
A view is rich if is missing the EngineShowFlags.Materials showflag, or has any of the render mode affecting showflags.
References IsRichView().
Referenced by IsRichView().
PrimitiveNeedsDistanceFieldSceneData()
bool PrimitiveNeedsDistanceFieldSceneData (bool bTrackAllPrimitives, bool bCastsDynamicIndirectShadow, bool bAffectsDistanceFieldLighting, bool bIsDrawnInGame, bool bCastsHiddenShadow, bool bCastsDynamicShadow, bool bAffectsDynamicIndirectLighting, bool bAffectIndirectLightingWhileHidden) inline
Centralized decision function to avoid diverging logic.
Definition at line 1090 of file SceneManagement.h.
SHADER_PARAMETER() [1/15]
TranslatedWorldPosition Color SHADER_PARAMETER (float , FalloffExponent)
References SHADER_PARAMETER.
SHADER_PARAMETER() [2/15]
TranslatedWorldPosition Color Direction DiffuseScale SourceRadius SoftSourceRadius RectLightBarnCosAngle RectLightAtlasUVOffset RectLightAtlasMaxLevel SHADER_PARAMETER (float , IESAtlasIndex)
References SHADER_PARAMETER.
SHADER_PARAMETER() [3/15]
TranslatedWorldPosition SHADER_PARAMETER (float , InvRadius)
References Color, and SHADER_PARAMETER.
SHADER_PARAMETER() [4/15]
TranslatedWorldPosition Color Direction DiffuseScale SourceRadius SoftSourceRadius RectLightBarnCosAngle SHADER_PARAMETER (float , RectLightBarnLength)
References SHADER_PARAMETER.
SHADER_PARAMETER() [5/15]
TranslatedWorldPosition Color Direction DiffuseScale SourceRadius SoftSourceRadius SHADER_PARAMETER (float , SourceLength)
References SHADER_PARAMETER.
SHADER_PARAMETER() [6/15]
TranslatedWorldPosition Color Direction SHADER_PARAMETER (float , SpecularScale)
References SHADER_PARAMETER.
SHADER_PARAMETER() [7/15]
ToXYZ ToAP1 ToAP0 SHADER_PARAMETER (FMatrix44f , FromAP0)
References END_SHADER_PARAMETER_STRUCT, SHADER_PARAMETER, and Super.
SHADER_PARAMETER() [8/15]
ToXYZ ToAP1 SHADER_PARAMETER (FMatrix44f , FromAP1)
References SHADER_PARAMETER.
SHADER_PARAMETER() [9/15]
ToXYZ SHADER_PARAMETER (FMatrix44f , FromXYZ)
References SHADER_PARAMETER.
SHADER_PARAMETER() [10/15]
TranslatedWorldPosition Color Direction DiffuseScale SourceRadius SoftSourceRadius RectLightBarnCosAngle RectLightAtlasUVOffset RectLightAtlasMaxLevel LightFunctionAtlasLightIndex SpotLightShadowmapMinMax SHADER_PARAMETER (FMatrix44f , SpotLightShadowWorldToShadowMatrix)
References SHADER_PARAMETER.
SHADER_PARAMETER() [11/15]
TranslatedWorldPosition Color Direction DiffuseScale SourceRadius SoftSourceRadius RectLightBarnCosAngle RectLightAtlasUVOffset SHADER_PARAMETER (FVector2f , RectLightAtlasUVScale)
References SHADER_PARAMETER.
SHADER_PARAMETER() [12/15]
TranslatedWorldPosition Color Direction DiffuseScale SourceRadius SHADER_PARAMETER (FVector2f , SpotAngles)
References SHADER_PARAMETER.
SHADER_PARAMETER() [13/15]
TranslatedWorldPosition Color Direction DiffuseScale SHADER_PARAMETER (FVector3f , Tangent)
References SHADER_PARAMETER, and Tangent.
SHADER_PARAMETER() [14/15]
TranslatedWorldPosition Color Direction DiffuseScale SourceRadius SoftSourceRadius RectLightBarnCosAngle RectLightAtlasUVOffset RectLightAtlasMaxLevel LightFunctionAtlasLightIndex SHADER_PARAMETER (FVector4f , SpotLightShadowSharpenAndFadeFractionAndReceiverDepthBiasAndSoftTransitionScale)
References SHADER_PARAMETER.
SHADER_PARAMETER() [15/15]
TranslatedWorldPosition Color Direction DiffuseScale SourceRadius SoftSourceRadius RectLightBarnCosAngle RectLightAtlasUVOffset RectLightAtlasMaxLevel LightFunctionAtlasLightIndex SHADER_PARAMETER (uint32 , bAffectsTranslucentLighting)
References BEGIN_SHADER_PARAMETER_STRUCT, END_SHADER_PARAMETER_STRUCT, and SHADER_PARAMETER.
SHADER_PARAMETER_SAMPLER() [1/3]
LightMapTexture AOMaterialMaskTexture VTLightMapTexture VTSkyOcclusionTexture VTStaticShadowTexture SHADER_PARAMETER_SAMPLER (SamplerState , LightMapSampler)
References SHADER_PARAMETER_SAMPLER.
SHADER_PARAMETER_SAMPLER() [2/3]
LightMapTexture AOMaterialMaskTexture VTLightMapTexture VTSkyOcclusionTexture VTStaticShadowTexture LightMapSampler_1 SHADER_PARAMETER_SAMPLER (SamplerState , SkyOcclusionSampler)
References SHADER_PARAMETER_SAMPLER.
SHADER_PARAMETER_SAMPLER() [3/3]
LightMapTexture AOMaterialMaskTexture VTLightMapTexture VTSkyOcclusionTexture VTStaticShadowTexture LightMapSampler_1 AOMaterialMaskSampler SHADER_PARAMETER_SAMPLER (SamplerState , StaticShadowTextureSampler)
References SHADER_PARAMETER_SAMPLER, SHADER_PARAMETER_TEXTURE, and Texture2D.
SHADER_PARAMETER_SRV() [1/2]
LightMapTexture AOMaterialMaskTexture VTLightMapTexture VTSkyOcclusionTexture SHADER_PARAMETER_SRV (Texture2D< float4 > , VTAOMaterialMaskTexture)
References SHADER_PARAMETER_SRV, and Texture2D.
SHADER_PARAMETER_SRV() [2/2]
LightMapTexture AOMaterialMaskTexture VTLightMapTexture SHADER_PARAMETER_SRV (Texture2D< float4 > , VTLightMapTexture_1)
References SHADER_PARAMETER_SRV, and Texture2D.
SHADER_PARAMETER_TEXTURE() [1/6]
TranslatedWorldPosition Color Direction DiffuseScale SourceRadius SoftSourceRadius RectLightBarnCosAngle RectLightAtlasUVOffset RectLightAtlasMaxLevel LightFunctionAtlasLightIndex SpotLightShadowmapMinMax LocalLightShadowBufferSize SHADER_PARAMETER_TEXTURE (Texture2D , LocalLightShadowTexture)
References SHADER_PARAMETER_SAMPLER, SHADER_PARAMETER_TEXTURE, and Texture2D.
SHADER_PARAMETER_TEXTURE() [2/6]
LightMapTexture SHADER_PARAMETER_TEXTURE (Texture2D , SkyOcclusionTexture)
References SHADER_PARAMETER_TEXTURE, and Texture2D.
SHADER_PARAMETER_TEXTURE() [3/6]
LightMapTexture AOMaterialMaskTexture SHADER_PARAMETER_TEXTURE (Texture2D , StaticShadowTexture)
References SHADER_PARAMETER_SRV, SHADER_PARAMETER_TEXTURE, and Texture2D.
SHADER_PARAMETER_TEXTURE() [4/6]
LightMapTexture AOMaterialMaskTexture VTLightMapTexture VTSkyOcclusionTexture VTStaticShadowTexture LightMapSampler_1 AOMaterialMaskSampler LightmapVirtualTexturePageTable0 SHADER_PARAMETER_TEXTURE (Texture2D< uint4 > , LightmapVirtualTexturePageTable1)
Definition at line 763 of file SceneManagement.h.
References Cluster, END_GLOBAL_SHADER_PARAMETER_STRUCT, GetTypeHash(), operator==(), PointerHash(), SHADER_PARAMETER_TEXTURE, and Texture2D.
SHADER_PARAMETER_TEXTURE() [5/6]
Params SHADER_PARAMETER_TEXTURE (TextureCube , Texture)
References SHADER_PARAMETER_SAMPLER, SHADER_PARAMETER_TEXTURE, Texture, and TextureCube.
SHADER_PARAMETER_TEXTURE() [6/6]
Params TextureSampler SHADER_PARAMETER_TEXTURE (TextureCube , TextureBlend)
References END_GLOBAL_SHADER_PARAMETER_STRUCT, SHADER_PARAMETER_SAMPLER, SHADER_PARAMETER_TEXTURE, Super, and TextureCube.
ShouldAllPrimitivesHaveDistanceField()
bool ShouldAllPrimitivesHaveDistanceField (EShaderPlatform ShaderPlatform)
References ShaderPlatform.
ShouldCompileDistanceFieldShaders()
bool ShouldCompileDistanceFieldShaders (EShaderPlatform ShaderPlatform)
References ShaderPlatform.
Variable Documentation
Clamp_WorldGroupSettings
FSharedSamplerState* Clamp_WorldGroupSettings extern
Sampler state using Clamp addressing and taking filter mode from the world texture group.
GDefaultLightmapResourceClusterUniformBuffer
TGlobalResource< FDefaultLightmapResourceClusterUniformBuffer > GDefaultLightmapResourceClusterUniformBuffer extern
GDefaultMobileReflectionCaptureUniformBuffer
Params TextureSampler TextureBlendSampler END_GLOBAL_SHADER_PARAMETER_STRUCT () class FDefaultMobileReflectionCaptureUniformBuffer TGlobalResource<FDefaultMobileReflectionCaptureUniformBuffer> GDefaultMobileReflectionCaptureUniformBuffer () extern
GDefaultWorkingColorSpaceUniformBuffer
ToXYZ ToAP1 ToAP0 bIsSRGB END_SHADER_PARAMETER_STRUCT () class FDefaultWorkingColorSpaceUniformBuffer TGlobalResource<FDefaultWorkingColorSpaceUniformBuffer> GDefaultWorkingColorSpaceUniformBuffer () extern
LQ_LIGHTMAP_COEF_INDEX
int32 LQ_LIGHTMAP_COEF_INDEX = 2 inline constexpr
The index at which simple coefficients are stored in any array containing all NUM_STORED_LIGHTMAP_COEF coefficients.
Definition at line 379 of file SceneManagement.h.
NUM_HQ_LIGHTMAP_COEF
int32 NUM_HQ_LIGHTMAP_COEF = 2 inline constexpr
The number of directional coefficients which the lightmap stores for each light sample.
Definition at line 373 of file SceneManagement.h.
Referenced by FLightMapInteraction::GetNumLightmapCoefficients().
NUM_LQ_LIGHTMAP_COEF
int32 NUM_LQ_LIGHTMAP_COEF = 2 inline constexpr
The number of simple coefficients which the lightmap stores for each light sample.
Definition at line 376 of file SceneManagement.h.
Referenced by FLightMapInteraction::GetNumLightmapCoefficients().
NUM_STORED_LIGHTMAP_COEF
int32 NUM_STORED_LIGHTMAP_COEF = 4 inline constexpr
The number of coefficients that are stored for each light sample.
Definition at line 370 of file SceneManagement.h.
Wrap_WorldGroupSettings
FSharedSamplerState* Wrap_WorldGroupSettings extern
Sampler state using Wrap addressing and taking filter mode from the world texture group.