Unreal Engine 5.6 C++ API: Runtime/Engine/Public/SceneTexturesConfig.h File Reference
SceneTexturesConfig.h File Reference
#include "RenderGraphDefinitions.h"
#include "ShaderParameterMacros.h"
#include "GBufferInfo.h"
#include "SceneUtils.h"
Data Structures
struct FSceneTexturesConfig
Struct containing the scene texture configuration used to create scene textures.
struct FSceneTexturesConfigInitSettings
Enumerations
enum class ESceneTextureExtracts : uint32 { None = 0 , Depth = 1 << 0 , CustomDepth = 1 << 1 , All = Depth | CustomDepth }
Functions
BEGIN_GLOBAL_SHADER_PARAMETER_STRUCT (FSceneTextureUniformParameters, 1) SHADER_PARAMETER_RDG_TEXTURE(Texture2D
A uniform buffer containing common scene textures used by materials or global shaders.
SceneColorTexture ScenePartialDepthTexture GBufferBTexture GBufferDTexture GBufferFTexture ScreenSpaceAOTexture CustomStencilTexture SceneColorTextureSampler SceneDepthTextureArray ScenePartialDepthTexture CustomDepthTexture CustomDepthTextureSampler CustomStencilTextureArray SceneVelocityTextureSampler GBufferBTexture GBufferDTexture SceneDepthAuxTextureArray LocalLightTextureB GBufferBTextureSampler GBufferDTextureSampler MobileSceneTextures END_SHADER_PARAMETER_STRUCT () extern 1 FSceneTextureShaderParameters GetSceneTextureShaderParameters(TRDGUniformBufferRef< FSceneTextureUniformParameters > UniformBuffer)
void GetSceneColorFormatAndCreateFlags (ERHIFeatureLevel::Type FeatureLevel, bool bRequiresAlphaChannel, ETextureCreateFlags ExtraSceneColorCreateFlags, uint32 NumSamples, bool bMemorylessMSAA, EPixelFormat &SceneColorFormat, ETextureCreateFlags &SceneColorCreateFlags)
FSceneTextureShaderParameters GetSceneTextureShaderParameters (TRDGUniformBufferRef< FMobileSceneTextureUniformParameters > UniformBuffer)
SceneColorTexture ScenePartialDepthTexture GBufferBTexture GBufferDTexture GBufferFTexture ScreenSpaceAOTexture SHADER_PARAMETER_RDG_TEXTURE (Texture2D, CustomDepthTexture) SHADER_PARAMETER_RDG_TEXTURE_SRV(Texture2D< uint2 >
SceneColorTexture ScenePartialDepthTexture SHADER_PARAMETER_RDG_TEXTURE (Texture2D, GBufferATexture) SHADER_PARAMETER_RDG_TEXTURE(Texture2D
SceneColorTexture ScenePartialDepthTexture GBufferBTexture SHADER_PARAMETER_RDG_TEXTURE (Texture2D, GBufferCTexture) SHADER_PARAMETER_RDG_TEXTURE(Texture2D
SceneColorTexture ScenePartialDepthTexture GBufferBTexture GBufferDTexture SHADER_PARAMETER_RDG_TEXTURE (Texture2D, GBufferETexture) SHADER_PARAMETER_RDG_TEXTURE(Texture2D
SceneColorTexture ScenePartialDepthTexture GBufferBTexture GBufferDTexture GBufferFTexture SHADER_PARAMETER_RDG_TEXTURE (Texture2D, GBufferVelocityTexture) SHADER_PARAMETER_RDG_TEXTURE(Texture2D
SceneColorTexture ScenePartialDepthTexture GBufferBTexture GBufferDTexture GBufferFTexture ScreenSpaceAOTexture CustomStencilTexture SceneColorTextureSampler SceneDepthTextureArray ScenePartialDepthTexture CustomDepthTexture CustomDepthTextureSampler CustomStencilTextureArray SceneVelocityTextureSampler GBufferBTexture GBufferDTexture SceneDepthAuxTextureArray SHADER_PARAMETER_RDG_TEXTURE (Texture2D, LocalLightTextureA) SHADER_PARAMETER_RDG_TEXTURE(Texture2D
SceneColorTexture ScenePartialDepthTexture GBufferBTexture GBufferDTexture GBufferFTexture ScreenSpaceAOTexture CustomStencilTexture SHADER_PARAMETER_RDG_TEXTURE (Texture2D, SceneColorTexture) SHADER_PARAMETER_SAMPLER(SamplerState
SceneColorTexture ScenePartialDepthTexture GBufferBTexture GBufferDTexture GBufferFTexture ScreenSpaceAOTexture CustomStencilTexture SceneColorTextureSampler SceneDepthTextureArray ScenePartialDepthTexture CustomDepthTexture CustomDepthTextureSampler CustomStencilTextureArray SceneVelocityTextureSampler GBufferBTexture GBufferDTexture SHADER_PARAMETER_RDG_TEXTURE (Texture2D, SceneDepthAuxTexture) SHADER_PARAMETER_RDG_TEXTURE(Texture2DArray
SceneColorTexture SHADER_PARAMETER_RDG_TEXTURE (Texture2D, SceneDepthTexture) SHADER_PARAMETER_RDG_TEXTURE(Texture2D
SceneColorTexture ScenePartialDepthTexture GBufferBTexture GBufferDTexture GBufferFTexture ScreenSpaceAOTexture CustomStencilTexture SceneColorTextureSampler SceneDepthTextureArray ScenePartialDepthTexture CustomDepthTexture CustomDepthTextureSampler CustomStencilTextureArray SHADER_PARAMETER_RDG_TEXTURE (Texture2D, SceneVelocityTexture) SHADER_PARAMETER_SAMPLER(SamplerState
SceneColorTexture ScenePartialDepthTexture GBufferBTexture GBufferDTexture GBufferFTexture ScreenSpaceAOTexture CustomStencilTexture SceneColorTextureSampler SceneDepthTextureArray ScenePartialDepthTexture CustomDepthTexture SHADER_PARAMETER_RDG_TEXTURE (Texture2DArray, CustomDepthTextureArray) SHADER_PARAMETER_SAMPLER(SamplerState
SceneColorTexture ScenePartialDepthTexture GBufferBTexture GBufferDTexture GBufferFTexture ScreenSpaceAOTexture CustomStencilTexture SceneColorTextureSampler SceneDepthTextureArray ScenePartialDepthTexture CustomDepthTexture CustomDepthTextureSampler SHADER_PARAMETER_RDG_TEXTURE_SRV (Texture2D< uint2 >, CustomStencilTexture) SHADER_PARAMETER_RDG_TEXTURE_SRV(Texture2DArray< uint2 >
SceneColorTexture ScenePartialDepthTexture GBufferBTexture GBufferDTexture GBufferFTexture ScreenSpaceAOTexture CustomStencilTexture SceneColorTextureSampler SceneDepthTextureArray ScenePartialDepthTexture CustomDepthTexture CustomDepthTextureSampler CustomStencilTextureArray SceneVelocityTextureSampler GBufferBTexture GBufferDTexture SceneDepthAuxTextureArray LocalLightTextureB GBufferBTextureSampler GBufferDTextureSampler SHADER_PARAMETER_RDG_UNIFORM_BUFFER (FSceneTextureUniformParameters, SceneTextures) SHADER_PARAMETER_RDG_UNIFORM_BUFFER(FMobileSceneTextureUniformParameters
SceneColorTexture ScenePartialDepthTexture GBufferBTexture GBufferDTexture GBufferFTexture ScreenSpaceAOTexture CustomStencilTexture SceneColorTextureSampler SceneDepthTextureArray ScenePartialDepthTexture CustomDepthTexture CustomDepthTextureSampler CustomStencilTextureArray SceneVelocityTextureSampler GBufferBTexture GBufferDTexture SceneDepthAuxTextureArray LocalLightTextureB SHADER_PARAMETER_SAMPLER (SamplerState, GBufferATextureSampler) SHADER_PARAMETER_SAMPLER(SamplerState
SceneColorTexture ScenePartialDepthTexture GBufferBTexture GBufferDTexture GBufferFTexture ScreenSpaceAOTexture CustomStencilTexture SceneColorTextureSampler SceneDepthTextureArray ScenePartialDepthTexture CustomDepthTexture CustomDepthTextureSampler CustomStencilTextureArray SceneVelocityTextureSampler GBufferBTexture GBufferDTexture SceneDepthAuxTextureArray LocalLightTextureB GBufferBTextureSampler SHADER_PARAMETER_SAMPLER (SamplerState, GBufferCTextureSampler) SHADER_PARAMETER_SAMPLER(SamplerState
SceneColorTexture ScenePartialDepthTexture GBufferBTexture GBufferDTexture GBufferFTexture ScreenSpaceAOTexture CustomStencilTexture SHADER_PARAMETER_SAMPLER (SamplerState, PointClampSampler) END_GLOBAL_SHADER_PARAMETER_STRUCT() BEGIN_GLOBAL_SHADER_PARAMETER_STRUCT(FMobileSceneTextureUniformParameters
SceneColorTexture ScenePartialDepthTexture GBufferBTexture GBufferDTexture GBufferFTexture ScreenSpaceAOTexture CustomStencilTexture SceneColorTextureSampler SceneDepthTextureArray ScenePartialDepthTexture CustomDepthTexture CustomDepthTextureSampler CustomStencilTextureArray SceneVelocityTextureSampler GBufferBTexture GBufferDTexture SceneDepthAuxTextureArray LocalLightTextureB GBufferBTextureSampler GBufferDTextureSampler SHADER_PARAMETER_SAMPLER (SamplerState, SceneDepthAuxTextureSampler) END_GLOBAL_SHADER_PARAMETER_STRUCT() BEGIN_SHADER_PARAMETER_STRUCT(FSceneTextureShaderParameters
SceneColorTexture ScenePartialDepthTexture GBufferBTexture GBufferDTexture GBufferFTexture ScreenSpaceAOTexture CustomStencilTexture SceneColorTextureSampler SceneDepthTextureArray SHADER_PARAMETER_SAMPLER (SamplerState, SceneDepthTextureSampler) SHADER_PARAMETER_RDG_TEXTURE(Texture2D
SceneColorTexture ScenePartialDepthTexture GBufferBTexture GBufferDTexture GBufferFTexture ScreenSpaceAOTexture CustomStencilTexture SceneColorTextureSampler SceneDepthTextureArray ScenePartialDepthTexture SHADER_PARAMETER_SAMPLER (SamplerState, ScenePartialDepthTextureSampler) SHADER_PARAMETER_RDG_TEXTURE(Texture2D
Enumeration Type Documentation
ESceneTextureExtracts
enum class ESceneTextureExtracts : uint32 strong
Enumerator
None
No textures are extracted from the render graph after execution.
Depth
Extracts scene depth after execution.
CustomDepth
Extracts custom depth after execution.
All
Extracts all available textures after execution.
Definition at line 82 of file SceneTexturesConfig.h.
Function Documentation
BEGIN_GLOBAL_SHADER_PARAMETER_STRUCT()
BEGIN_GLOBAL_SHADER_PARAMETER_STRUCT (FSceneTextureUniformParameters , 1)
A uniform buffer containing common scene textures used by materials or global shaders.
References Texture2D.
END_SHADER_PARAMETER_STRUCT()
SceneColorTexture ScenePartialDepthTexture GBufferBTexture GBufferDTexture GBufferFTexture ScreenSpaceAOTexture CustomStencilTexture SceneColorTextureSampler SceneDepthTextureArray ScenePartialDepthTexture CustomDepthTexture CustomDepthTextureSampler CustomStencilTextureArray SceneVelocityTextureSampler GBufferBTexture GBufferDTexture SceneDepthAuxTextureArray LocalLightTextureB GBufferBTextureSampler GBufferDTextureSampler MobileSceneTextures END_SHADER_PARAMETER_STRUCT ()
References END_SHADER_PARAMETER_STRUCT, GetSceneTextureShaderParameters(), and UniformBuffer.
GetSceneColorFormatAndCreateFlags()
void GetSceneColorFormatAndCreateFlags (ERHIFeatureLevel::Type FeatureLevel, bool bRequiresAlphaChannel, ETextureCreateFlags ExtraSceneColorCreateFlags, uint32 NumSamples, bool bMemorylessMSAA, EPixelFormat & SceneColorFormat, ETextureCreateFlags & SceneColorCreateFlags) extern
References GetSceneColorFormatAndCreateFlags().
Referenced by GetSceneColorFormatAndCreateFlags().
GetSceneTextureShaderParameters()
FSceneTextureShaderParameters GetSceneTextureShaderParameters (TRDGUniformBufferRef< FMobileSceneTextureUniformParameters > UniformBuffer) extern
References GetSceneTextureShaderParameters(), and UniformBuffer.
Referenced by END_SHADER_PARAMETER_STRUCT(), and GetSceneTextureShaderParameters().
SHADER_PARAMETER_RDG_TEXTURE() [1/11]
SceneColorTexture ScenePartialDepthTexture GBufferBTexture GBufferDTexture GBufferFTexture ScreenSpaceAOTexture SHADER_PARAMETER_RDG_TEXTURE (Texture2D , CustomDepthTexture)
References SHADER_PARAMETER_RDG_TEXTURE, SHADER_PARAMETER_RDG_TEXTURE_SRV, and Texture2D.
SHADER_PARAMETER_RDG_TEXTURE() [2/11]
SceneColorTexture ScenePartialDepthTexture GBufferBTexture GBufferDTexture GBufferFTexture ScreenSpaceAOTexture CustomStencilTexture SceneColorTextureSampler SceneDepthTextureArray ScenePartialDepthTexture CustomDepthTexture CustomDepthTextureSampler CustomStencilTextureArray SceneVelocityTextureSampler SHADER_PARAMETER_RDG_TEXTURE (Texture2D , GBufferATexture)
References SHADER_PARAMETER_RDG_TEXTURE, and Texture2D.
SHADER_PARAMETER_RDG_TEXTURE() [3/11]
SceneColorTexture ScenePartialDepthTexture GBufferBTexture GBufferDTexture GBufferFTexture ScreenSpaceAOTexture CustomStencilTexture SceneColorTextureSampler SceneDepthTextureArray ScenePartialDepthTexture CustomDepthTexture CustomDepthTextureSampler CustomStencilTextureArray SceneVelocityTextureSampler GBufferBTexture SHADER_PARAMETER_RDG_TEXTURE (Texture2D , GBufferCTexture)
References SHADER_PARAMETER_RDG_TEXTURE, and Texture2D.
SHADER_PARAMETER_RDG_TEXTURE() [4/11]
SceneColorTexture ScenePartialDepthTexture GBufferBTexture GBufferDTexture SHADER_PARAMETER_RDG_TEXTURE (Texture2D , GBufferETexture)
References SHADER_PARAMETER_RDG_TEXTURE, and Texture2D.
SHADER_PARAMETER_RDG_TEXTURE() [5/11]
SceneColorTexture ScenePartialDepthTexture GBufferBTexture GBufferDTexture GBufferFTexture SHADER_PARAMETER_RDG_TEXTURE (Texture2D , GBufferVelocityTexture)
References SHADER_PARAMETER_RDG_TEXTURE, and Texture2D.
SHADER_PARAMETER_RDG_TEXTURE() [6/11]
SceneColorTexture ScenePartialDepthTexture GBufferBTexture GBufferDTexture GBufferFTexture ScreenSpaceAOTexture CustomStencilTexture SceneColorTextureSampler SceneDepthTextureArray ScenePartialDepthTexture CustomDepthTexture CustomDepthTextureSampler CustomStencilTextureArray SceneVelocityTextureSampler GBufferBTexture GBufferDTexture SceneDepthAuxTextureArray SHADER_PARAMETER_RDG_TEXTURE (Texture2D , LocalLightTextureA)
References SHADER_PARAMETER_RDG_TEXTURE, and Texture2D.
SHADER_PARAMETER_RDG_TEXTURE() [7/11]
SceneColorTexture ScenePartialDepthTexture GBufferBTexture GBufferDTexture GBufferFTexture ScreenSpaceAOTexture CustomStencilTexture SHADER_PARAMETER_RDG_TEXTURE (Texture2D , SceneColorTexture)
References SHADER_PARAMETER_RDG_TEXTURE, SHADER_PARAMETER_SAMPLER, Texture2D, and Texture2DArray.
SHADER_PARAMETER_RDG_TEXTURE() [8/11]
SceneColorTexture ScenePartialDepthTexture GBufferBTexture GBufferDTexture GBufferFTexture ScreenSpaceAOTexture CustomStencilTexture SceneColorTextureSampler SceneDepthTextureArray ScenePartialDepthTexture CustomDepthTexture CustomDepthTextureSampler CustomStencilTextureArray SceneVelocityTextureSampler GBufferBTexture GBufferDTexture SHADER_PARAMETER_RDG_TEXTURE (Texture2D , SceneDepthAuxTexture)
References SHADER_PARAMETER_RDG_TEXTURE, Texture2D, and Texture2DArray.
SHADER_PARAMETER_RDG_TEXTURE() [9/11]
SceneColorTexture ScenePartialDepthTexture GBufferBTexture GBufferDTexture GBufferFTexture ScreenSpaceAOTexture CustomStencilTexture SceneColorTextureSampler SHADER_PARAMETER_RDG_TEXTURE (Texture2D , SceneDepthTexture)
References SHADER_PARAMETER_RDG_TEXTURE, and Texture2D.
SHADER_PARAMETER_RDG_TEXTURE() [10/11]
SceneColorTexture ScenePartialDepthTexture GBufferBTexture GBufferDTexture GBufferFTexture ScreenSpaceAOTexture CustomStencilTexture SceneColorTextureSampler SceneDepthTextureArray ScenePartialDepthTexture CustomDepthTexture CustomDepthTextureSampler CustomStencilTextureArray SHADER_PARAMETER_RDG_TEXTURE (Texture2D , SceneVelocityTexture)
References SHADER_PARAMETER_RDG_TEXTURE, SHADER_PARAMETER_SAMPLER, and Texture2D.
SHADER_PARAMETER_RDG_TEXTURE() [11/11]
SceneColorTexture ScenePartialDepthTexture GBufferBTexture GBufferDTexture GBufferFTexture ScreenSpaceAOTexture CustomStencilTexture SceneColorTextureSampler SceneDepthTextureArray ScenePartialDepthTexture CustomDepthTexture SHADER_PARAMETER_RDG_TEXTURE (Texture2DArray , CustomDepthTextureArray)
References SHADER_PARAMETER_RDG_TEXTURE, SHADER_PARAMETER_SAMPLER, and Texture2DArray.
SHADER_PARAMETER_RDG_TEXTURE_SRV()
SceneColorTexture ScenePartialDepthTexture GBufferBTexture GBufferDTexture GBufferFTexture ScreenSpaceAOTexture CustomStencilTexture SceneColorTextureSampler SceneDepthTextureArray ScenePartialDepthTexture CustomDepthTexture CustomDepthTextureSampler SHADER_PARAMETER_RDG_TEXTURE_SRV (Texture2D< uint2 > , CustomStencilTexture)
References SHADER_PARAMETER_RDG_TEXTURE_SRV, Texture2D, and Texture2DArray.
SHADER_PARAMETER_RDG_UNIFORM_BUFFER()
SceneColorTexture ScenePartialDepthTexture GBufferBTexture GBufferDTexture GBufferFTexture ScreenSpaceAOTexture CustomStencilTexture SceneColorTextureSampler SceneDepthTextureArray ScenePartialDepthTexture CustomDepthTexture CustomDepthTextureSampler CustomStencilTextureArray SceneVelocityTextureSampler GBufferBTexture GBufferDTexture SceneDepthAuxTextureArray LocalLightTextureB GBufferBTextureSampler GBufferDTextureSampler SHADER_PARAMETER_RDG_UNIFORM_BUFFER (FSceneTextureUniformParameters , SceneTextures)
References SHADER_PARAMETER_RDG_UNIFORM_BUFFER.
SHADER_PARAMETER_SAMPLER() [1/6]
SceneColorTexture ScenePartialDepthTexture GBufferBTexture GBufferDTexture GBufferFTexture ScreenSpaceAOTexture CustomStencilTexture SceneColorTextureSampler SceneDepthTextureArray ScenePartialDepthTexture CustomDepthTexture CustomDepthTextureSampler CustomStencilTextureArray SceneVelocityTextureSampler GBufferBTexture GBufferDTexture SceneDepthAuxTextureArray LocalLightTextureB SHADER_PARAMETER_SAMPLER (SamplerState , GBufferATextureSampler)
References SHADER_PARAMETER_SAMPLER.
SHADER_PARAMETER_SAMPLER() [2/6]
SceneColorTexture ScenePartialDepthTexture GBufferBTexture GBufferDTexture GBufferFTexture ScreenSpaceAOTexture CustomStencilTexture SceneColorTextureSampler SceneDepthTextureArray ScenePartialDepthTexture CustomDepthTexture CustomDepthTextureSampler CustomStencilTextureArray SceneVelocityTextureSampler GBufferBTexture GBufferDTexture SceneDepthAuxTextureArray LocalLightTextureB GBufferBTextureSampler SHADER_PARAMETER_SAMPLER (SamplerState , GBufferCTextureSampler)
References SHADER_PARAMETER_SAMPLER.
SHADER_PARAMETER_SAMPLER() [3/6]
SceneColorTexture ScenePartialDepthTexture GBufferBTexture GBufferDTexture GBufferFTexture ScreenSpaceAOTexture CustomStencilTexture SHADER_PARAMETER_SAMPLER (SamplerState , PointClampSampler)
References BEGIN_GLOBAL_SHADER_PARAMETER_STRUCT, END_GLOBAL_SHADER_PARAMETER_STRUCT, and SHADER_PARAMETER_SAMPLER.
SHADER_PARAMETER_SAMPLER() [4/6]
SceneColorTexture ScenePartialDepthTexture GBufferBTexture GBufferDTexture GBufferFTexture ScreenSpaceAOTexture CustomStencilTexture SceneColorTextureSampler SceneDepthTextureArray ScenePartialDepthTexture CustomDepthTexture CustomDepthTextureSampler CustomStencilTextureArray SceneVelocityTextureSampler GBufferBTexture GBufferDTexture SceneDepthAuxTextureArray LocalLightTextureB GBufferBTextureSampler GBufferDTextureSampler SHADER_PARAMETER_SAMPLER (SamplerState , SceneDepthAuxTextureSampler)
References BEGIN_SHADER_PARAMETER_STRUCT, END_GLOBAL_SHADER_PARAMETER_STRUCT, and SHADER_PARAMETER_SAMPLER.
SHADER_PARAMETER_SAMPLER() [5/6]
SceneColorTexture ScenePartialDepthTexture GBufferBTexture GBufferDTexture GBufferFTexture ScreenSpaceAOTexture CustomStencilTexture SceneColorTextureSampler SceneDepthTextureArray SHADER_PARAMETER_SAMPLER (SamplerState , SceneDepthTextureSampler)
References SHADER_PARAMETER_RDG_TEXTURE, SHADER_PARAMETER_SAMPLER, and Texture2D.
SHADER_PARAMETER_SAMPLER() [6/6]
SceneColorTexture ScenePartialDepthTexture GBufferBTexture GBufferDTexture GBufferFTexture ScreenSpaceAOTexture CustomStencilTexture SceneColorTextureSampler SceneDepthTextureArray ScenePartialDepthTexture SHADER_PARAMETER_SAMPLER (SamplerState , ScenePartialDepthTextureSampler)
References SHADER_PARAMETER_RDG_TEXTURE, SHADER_PARAMETER_SAMPLER, and Texture2D.