Unreal Engine 5.6 C++ API: Runtime/RenderCore/Public/ShaderParameterUtils.h File Reference
ShaderParameterUtils.h File Reference
#include "CoreMinimal.h"
#include "RHI.h"
#include "RHIUtilities.h"
#include "ShaderParameters.h"
#include "ShaderCore.h"
#include "Misc/App.h"
Macros
#define GUARD_SETSHADERVALUE(_TYPE)
Typedefs
template<typename ShaderType>
using TShaderRef = TShaderRefBase<ShaderType, FShaderMapPointerTable>
Functions
template<typename TShaderType, typename... TArguments>
void SetBatchedShaderParametersMixed (FRHIBatchedShaderParameters &BatchedParameters, const TShaderRef< TShaderType > &InShader, const typename TShaderType::FParameters &Parameters, TArguments &&... InArguments)
Utility to set all legacy and non-legacy parameters for a shader. Requires the shader type to implement SetParameters(FRHIBatchedShaderParameters& BatchedParameters, ...)
template<typename TShaderType, typename TShaderTypeRHI, typename... TArguments>
void SetBatchedShaderParametersMixed (FRHIBatchedShaderParameters &BatchedParameters, const TShaderRef< TShaderType > &InShader, TShaderTypeRHI *InShaderRHI, const typename TShaderType::FParameters &Parameters, TArguments &&... InArguments)
void SetSamplerParameter (FRHIBatchedShaderParameters &BatchedParameters, const FShaderResourceParameter &Parameter, FRHISamplerState *SamplerStateRHI)
template<typename TRHICmdList, typename TShaderType, typename TShaderTypeRHI, typename... TArguments>
void SetShaderParametersLegacy (TRHICmdList &RHICmdList, const TShaderRef< TShaderType > &InShader, TShaderTypeRHI *InShaderRHI, TArguments &&... InArguments)
Utility to set all legacy parameters for a shader. Requires the shader type to implement SetParameters(FRHIBatchedShaderParameters& BatchedParameters, ...)
template<typename TRHICmdList, typename TShaderType, typename... TArguments>
void SetShaderParametersLegacyAS (TRHICmdList &RHICmdList, const TShaderRef< TShaderType > &InShader, TArguments &&... InArguments)
Utility to set all legacy parameters for an Amplification shader. Requires the shader type to implement SetParameters(FRHIBatchedShaderParameters& BatchedParameters, ...)
template<typename TRHICmdList, typename TShaderType, typename... TArguments>
void SetShaderParametersLegacyCS (TRHICmdList &RHICmdList, const TShaderRef< TShaderType > &InShader, TArguments &&... InArguments)
Utility to set all legacy parameters for a Compute shader. Requires the shader type to implement SetParameters(FRHIBatchedShaderParameters& BatchedParameters, ...)
template<typename TRHICmdList, typename TShaderType, typename... TArguments>
void SetShaderParametersLegacyGS (TRHICmdList &RHICmdList, const TShaderRef< TShaderType > &InShader, TArguments &&... InArguments)
Utility to set all legacy parameters for a Geometry shader. Requires the shader type to implement SetParameters(FRHIBatchedShaderParameters& BatchedParameters, ...)
template<typename TRHICmdList, typename TShaderType, typename... TArguments>
void SetShaderParametersLegacyMS (TRHICmdList &RHICmdList, const TShaderRef< TShaderType > &InShader, TArguments &&... InArguments)
Utility to set all legacy parameters for a Mesh shader. Requires the shader type to implement SetParameters(FRHIBatchedShaderParameters& BatchedParameters, ...)
template<typename TRHICmdList, typename TShaderType, typename... TArguments>
void SetShaderParametersLegacyPS (TRHICmdList &RHICmdList, const TShaderRef< TShaderType > &InShader, TArguments &&... InArguments)
Utility to set all legacy parameters for a Pixel shader. Requires the shader type to implement SetParameters(FRHIBatchedShaderParameters& BatchedParameters, ...)
template<typename TRHICmdList, typename TShaderType, typename... TArguments>
void SetShaderParametersLegacyVS (TRHICmdList &RHICmdList, const TShaderRef< TShaderType > &InShader, TArguments &&... InArguments)
Utility to set all legacy parameters for a Vertex shader. Requires the shader type to implement SetParameters(FRHIBatchedShaderParameters& BatchedParameters, ...)
template<typename TRHICmdList, typename TShaderType, typename TShaderTypeRHI, typename... TArguments>
void SetShaderParametersMixed (TRHICmdList &RHICmdList, const TShaderRef< TShaderType > &InShader, TShaderTypeRHI *InShaderRHI, const typename TShaderType::FParameters &Parameters, TArguments &&... InArguments)
Utility to set all legacy and non-legacy parameters for a shader. Requires the shader type to implement SetParameters(FRHIBatchedShaderParameters& BatchedParameters, ...)
template<typename TShaderType, typename... TArguments>
void SetShaderParametersMixedAS (FRHIBatchedShaderParameters &BatchedParameters, const TShaderRef< TShaderType > &InShader, const typename TShaderType::FParameters &Parameters, TArguments &&... InArguments)
Utility to set all legacy and non-legacy parameters for an Amplification shader. Requires the shader type to implement SetParameters(FRHIBatchedShaderParameters& BatchedParameters, ...)
template<typename TRHICmdList, typename TShaderType, typename... TArguments>
void SetShaderParametersMixedAS (TRHICmdList &RHICmdList, const TShaderRef< TShaderType > &InShader, const typename TShaderType::FParameters &Parameters, TArguments &&... InArguments)
Utility to set all legacy and non-legacy parameters for an Amplification shader. Requires the shader type to implement SetParameters(FRHIBatchedShaderParameters& BatchedParameters, ...)
template<typename TShaderType, typename... TArguments>
void SetShaderParametersMixedCS (FRHIBatchedShaderParameters &BatchedParameters, const TShaderRef< TShaderType > &InShader, const typename TShaderType::FParameters &Parameters, TArguments &&... InArguments)
Utility to set all legacy and non-legacy parameters for a Compute shader. Requires the shader type to implement SetParameters(FRHIBatchedShaderParameters& BatchedParameters, ...)
template<typename TRHICmdList, typename TShaderType, typename... TArguments>
void SetShaderParametersMixedCS (TRHICmdList &RHICmdList, const TShaderRef< TShaderType > &InShader, const typename TShaderType::FParameters &Parameters, TArguments &&... InArguments)
Utility to set all legacy and non-legacy parameters for a Compute shader. Requires the shader type to implement SetParameters(FRHIBatchedShaderParameters& BatchedParameters, ...)
template<typename TShaderType, typename... TArguments>
void SetShaderParametersMixedGS (FRHIBatchedShaderParameters &BatchedParameters, const TShaderRef< TShaderType > &InShader, const typename TShaderType::FParameters &Parameters, TArguments &&... InArguments)
Utility to set all legacy and non-legacy parameters for a Geometry shader. Requires the shader type to implement SetParameters(FRHIBatchedShaderParameters& BatchedParameters, ...)
template<typename TRHICmdList, typename TShaderType, typename... TArguments>
void SetShaderParametersMixedGS (TRHICmdList &RHICmdList, const TShaderRef< TShaderType > &InShader, const typename TShaderType::FParameters &Parameters, TArguments &&... InArguments)
Utility to set all legacy and non-legacy parameters for a Geometry shader. Requires the shader type to implement SetParameters(FRHIBatchedShaderParameters& BatchedParameters, ...)
template<typename TShaderType, typename... TArguments>
void SetShaderParametersMixedMS (FRHIBatchedShaderParameters &BatchedParameters, const TShaderRef< TShaderType > &InShader, const typename TShaderType::FParameters &Parameters, TArguments &&... InArguments)
Utility to set all legacy and non-legacy parameters for a Mesh shader. Requires the shader type to implement SetParameters(FRHIBatchedShaderParameters& BatchedParameters, ...)
template<typename TRHICmdList, typename TShaderType, typename... TArguments>
void SetShaderParametersMixedMS (TRHICmdList &RHICmdList, const TShaderRef< TShaderType > &InShader, const typename TShaderType::FParameters &Parameters, TArguments &&... InArguments)
Utility to set all legacy and non-legacy parameters for a Mesh shader. Requires the shader type to implement SetParameters(FRHIBatchedShaderParameters& BatchedParameters, ...)
template<typename TShaderType, typename... TArguments>
void SetShaderParametersMixedPS (FRHIBatchedShaderParameters &BatchedParameters, const TShaderRef< TShaderType > &InShader, const typename TShaderType::FParameters &Parameters, TArguments &&... InArguments)
Utility to set all legacy and non-legacy parameters for a Pixel shader. Requires the shader type to implement SetParameters(FRHIBatchedShaderParameters& BatchedParameters, ...)
template<typename TRHICmdList, typename TShaderType, typename... TArguments>
void SetShaderParametersMixedPS (TRHICmdList &RHICmdList, const TShaderRef< TShaderType > &InShader, const typename TShaderType::FParameters &Parameters, TArguments &&... InArguments)
Utility to set all legacy and non-legacy parameters for a Pixel shader. Requires the shader type to implement SetParameters(FRHIBatchedShaderParameters& BatchedParameters, ...)
template<typename TShaderType, typename... TArguments>
void SetShaderParametersMixedVS (FRHIBatchedShaderParameters &BatchedParameters, const TShaderRef< TShaderType > &InShader, const typename TShaderType::FParameters &Parameters, TArguments &&... InArguments)
Utility to set all legacy and non-legacy parameters for a Vertex shader. Requires the shader type to implement SetParameters(FRHIBatchedShaderParameters& BatchedParameters, ...)
template<typename TRHICmdList, typename TShaderType, typename... TArguments>
void SetShaderParametersMixedVS (TRHICmdList &RHICmdList, const TShaderRef< TShaderType > &InShader, const typename TShaderType::FParameters &Parameters, TArguments &&... InArguments)
Utility to set all legacy and non-legacy parameters for a Vertex shader. Requires the shader type to implement SetParameters(FRHIBatchedShaderParameters& BatchedParameters, ...)
template<typename TShaderType, typename... TArguments>
void SetShaderParametersMixedWS (FRHIBatchedShaderParameters &BatchedParameters, const TShaderRef< TShaderType > &InShader, const typename TShaderType::FParameters &Parameters, TArguments &&... InArguments)
Utility to set all legacy and non-legacy parameters for a WorkGraph shader. Requires the shader type to implement SetParameters(FRHIBatchedShaderParameters& BatchedParameters, ...)
template<class ParameterType>
void SetShaderValue (FRHIBatchedShaderParameters &BatchedParameters, const FShaderParameter &Parameter, const ParameterType &Value, uint32 ElementIndex=0)
template<typename ShaderRHIParamRef, typename TRHICmdList>
void SetShaderValue (TRHICmdList &RHICmdList, const ShaderRHIParamRef &Shader, const FShaderParameter &Parameter, const ::FSphere3d &Value, uint32 ElementIndex=0)
template<typename ShaderRHIParamRef, typename TRHICmdList>
void SetShaderValue (TRHICmdList &RHICmdList, const ShaderRHIParamRef &Shader, const FShaderParameter &Parameter, const FBox3d &Value, uint32 ElementIndex=0)
template<typename ShaderRHIParamRef, typename TRHICmdList>
void SetShaderValue (TRHICmdList &RHICmdList, const ShaderRHIParamRef &Shader, const FShaderParameter &Parameter, const FMatrix44d &Value, uint32 ElementIndex=0)
template<typename ShaderRHIParamRef, typename TRHICmdList>
void SetShaderValue (TRHICmdList &RHICmdList, const ShaderRHIParamRef &Shader, const FShaderParameter &Parameter, const FPlane4d &Value, uint32 ElementIndex=0)
template<typename ShaderRHIParamRef, typename TRHICmdList>
void SetShaderValue (TRHICmdList &RHICmdList, const ShaderRHIParamRef &Shader, const FShaderParameter &Parameter, const FQuat4d &Value, uint32 ElementIndex=0)
template<typename ShaderRHIParamRef, typename TRHICmdList>
void SetShaderValue (TRHICmdList &RHICmdList, const ShaderRHIParamRef &Shader, const FShaderParameter &Parameter, const FVector2d &Value, uint32 ElementIndex=0)
template<typename ShaderRHIParamRef, typename TRHICmdList>
void SetShaderValue (TRHICmdList &RHICmdList, const ShaderRHIParamRef &Shader, const FShaderParameter &Parameter, const FVector3d &Value, uint32 ElementIndex=0)
template<typename ShaderRHIParamRef, typename TRHICmdList>
void SetShaderValue (TRHICmdList &RHICmdList, const ShaderRHIParamRef &Shader, const FShaderParameter &Parameter, const FVector4d &Value, uint32 ElementIndex=0)
template<class ParameterType>
void SetShaderValueArray (FRHIBatchedShaderParameters &BatchedParameters, const FShaderParameter &Parameter, const ParameterType *Values, uint32 NumElements, uint32 ElementIndex=0)
template<typename ShaderRHIParamRef, typename TRHICmdList>
void SetShaderValueArray (TRHICmdList &RHICmdList, const ShaderRHIParamRef &Shader, const FShaderParameter &Parameter, const ::FSphere3d *Values, uint32 NumElements, uint32 BaseElementIndex=0)
template<typename ShaderRHIParamRef, typename TRHICmdList>
void SetShaderValueArray (TRHICmdList &RHICmdList, const ShaderRHIParamRef &Shader, const FShaderParameter &Parameter, const FBox3d *Values, uint32 NumElements, uint32 BaseElementIndex=0)
template<typename ShaderRHIParamRef, typename TRHICmdList>
void SetShaderValueArray (TRHICmdList &RHICmdList, const ShaderRHIParamRef &Shader, const FShaderParameter &Parameter, const FMatrix44d *Values, uint32 NumElements, uint32 BaseElementIndex=0)
template<typename ShaderRHIParamRef, typename TRHICmdList>
void SetShaderValueArray (TRHICmdList &RHICmdList, const ShaderRHIParamRef &Shader, const FShaderParameter &Parameter, const FPlane4d *Values, uint32 NumElements, uint32 BaseElementIndex=0)
template<typename ShaderRHIParamRef, typename TRHICmdList>
void SetShaderValueArray (TRHICmdList &RHICmdList, const ShaderRHIParamRef &Shader, const FShaderParameter &Parameter, const FQuat4d *Values, uint32 NumElements, uint32 BaseElementIndex=0)
template<typename ShaderRHIParamRef, typename TRHICmdList>
void SetShaderValueArray (TRHICmdList &RHICmdList, const ShaderRHIParamRef &Shader, const FShaderParameter &Parameter, const FVector2d *Values, uint32 NumElements, uint32 BaseElementIndex=0)
template<typename ShaderRHIParamRef, typename TRHICmdList>
void SetShaderValueArray (TRHICmdList &RHICmdList, const ShaderRHIParamRef &Shader, const FShaderParameter &Parameter, const FVector3d *Values, uint32 NumElements, uint32 BaseElementIndex=0)
template<typename ShaderRHIParamRef, typename TRHICmdList>
void SetShaderValueArray (TRHICmdList &RHICmdList, const ShaderRHIParamRef &Shader, const FShaderParameter &Parameter, const FVector4d *Values, uint32 NumElements, uint32 BaseElementIndex=0)
template<typename ShaderRHIParamRef>
void SetShaderValueOnContext (IRHICommandContext &RHICmdListContext, const ShaderRHIParamRef &Shader, const FShaderParameter &Parameter, const ::FSphere3d &Value, uint32 ElementIndex=0)
template<typename ShaderRHIParamRef>
void SetShaderValueOnContext (IRHICommandContext &RHICmdListContext, const ShaderRHIParamRef &Shader, const FShaderParameter &Parameter, const FBox3d &Value, uint32 ElementIndex=0)
template<typename ShaderRHIParamRef>
void SetShaderValueOnContext (IRHICommandContext &RHICmdListContext, const ShaderRHIParamRef &Shader, const FShaderParameter &Parameter, const FMatrix44d &Value, uint32 ElementIndex=0)
template<typename ShaderRHIParamRef>
void SetShaderValueOnContext (IRHICommandContext &RHICmdListContext, const ShaderRHIParamRef &Shader, const FShaderParameter &Parameter, const FPlane4d &Value, uint32 ElementIndex=0)
template<typename ShaderRHIParamRef>
void SetShaderValueOnContext (IRHICommandContext &RHICmdListContext, const ShaderRHIParamRef &Shader, const FShaderParameter &Parameter, const FQuat4d &Value, uint32 ElementIndex=0)
template<typename ShaderRHIParamRef>
void SetShaderValueOnContext (IRHICommandContext &RHICmdListContext, const ShaderRHIParamRef &Shader, const FShaderParameter &Parameter, const FVector2d &Value, uint32 ElementIndex=0)
template<typename ShaderRHIParamRef>
void SetShaderValueOnContext (IRHICommandContext &RHICmdListContext, const ShaderRHIParamRef &Shader, const FShaderParameter &Parameter, const FVector3d &Value, uint32 ElementIndex=0)
template<typename ShaderRHIParamRef>
void SetShaderValueOnContext (IRHICommandContext &RHICmdListContext, const ShaderRHIParamRef &Shader, const FShaderParameter &Parameter, const FVector4d &Value, uint32 ElementIndex=0)
template<typename TRHICmdList, typename TShaderTypeRHI, class ParameterType>
void SetSingleShaderValue (TRHICmdList &RHICmdList, TShaderTypeRHI *InShaderRHI, const FShaderParameter &Parameter, const ParameterType &Value)
void SetSRVParameter (FRHIBatchedShaderParameters &BatchedParameters, const FShaderResourceParameter &Parameter, FRHIShaderResourceView *SRV)
void SetTextureParameter (FRHIBatchedShaderParameters &BatchedParameters, const FShaderResourceParameter &Parameter, FRHITexture *TextureRHI)
void SetTextureParameter (FRHIBatchedShaderParameters &BatchedParameters, const FShaderResourceParameter &TextureParameter, const FShaderResourceParameter &SamplerParameter, const FTexture *Texture)
void SetTextureParameter (FRHIBatchedShaderParameters &BatchedParameters, const FShaderResourceParameter &TextureParameter, const FShaderResourceParameter &SamplerParameter, FRHISamplerState *SamplerStateRHI, FRHITexture *TextureRHI)
template<typename TRHIShader, typename TRHICmdList>
void SetTextureParameter (TRHICmdList &RHICmdList, TRHIShader *Shader, const FShaderResourceParameter &TextureParameter, const FShaderResourceParameter &SamplerParameter, FRHISamplerState *SamplerStateRHI, FRHITexture *TextureRHI)
Sets the value of a shader texture parameter.
void SetUAVParameter (FRHIBatchedShaderParameters &BatchedParameters, const FShaderResourceParameter &Parameter, FRHIUnorderedAccessView *UAV)
void SetUniformBufferParameter (FRHIBatchedShaderParameters &BatchedParameters, const FShaderUniformBufferParameter &Parameter, FRHIUniformBuffer *UniformBufferRHI)
template<typename TBufferStruct>
void SetUniformBufferParameter (FRHIBatchedShaderParameters &BatchedParameters, const TShaderUniformBufferParameter< TBufferStruct > &Parameter, const TUniformBuffer< TBufferStruct > &UniformBuffer)
template<typename TBufferStruct>
void SetUniformBufferParameter (FRHIBatchedShaderParameters &BatchedParameters, const TShaderUniformBufferParameter< TBufferStruct > &Parameter, const TUniformBufferRef< TBufferStruct > &UniformBufferRef)
template<typename TBufferStruct>
void SetUniformBufferParameterImmediate (FRHIBatchedShaderParameters &BatchedParameters, const TShaderUniformBufferParameter< TBufferStruct > &Parameter, const TBufferStruct &UniformBufferValue)
template<typename TRHICmdList, typename TShaderType>
void UnsetShaderParametersLegacyCS (TRHICmdList &RHICmdList, const TShaderRef< TShaderType > &InShader)
Utility to unset all legacy parameters for a Compute shader. Requires the shader type to implement UnsetParameters(FRHIBatchedShaderUnbinds& BatchedUnbinds)
template<typename TRHICmdList, typename TShaderType>
void UnsetShaderParametersLegacyPS (TRHICmdList &RHICmdList, const TShaderRef< TShaderType > &InShader)
Utility to unset all legacy parameters for a Pixel shader. Requires the shader type to implement UnsetParameters(FRHIBatchedShaderUnbinds& BatchedUnbinds)
void UnsetSRVParameter (FRHIBatchedShaderUnbinds &BatchedUnbinds, const FShaderResourceParameter &Parameter)
void UnsetUAVParameter (FRHIBatchedShaderUnbinds &BatchedUnbinds, const FShaderResourceParameter &Parameter)
Macro Definition Documentation
GUARD_SETSHADERVALUE
#define GUARD_SETSHADERVALUE (_TYPE)
Value:
template<typename ShaderRHIParamRef, typename TRHICmdList>                                                                                                                              \
void SetShaderValue(TRHICmdList& RHICmdList,    const ShaderRHIParamRef& Shader, const FShaderParameter& Parameter,                                                                     \
    const _TYPE##d& Value, uint32 ElementIndex = 0) { static_assert(sizeof(ShaderRHIParamRef) == 0, "Passing unsupported "#_TYPE"d. Requires "#_TYPE"f"); }                              \
template<typename ShaderRHIParamRef>                                                                                                                                                    \
void SetShaderValueOnContext(IRHICommandContext& RHICmdListContext,  const ShaderRHIParamRef& Shader, const FShaderParameter& Parameter,                                                 \
    const _TYPE##d& Value, uint32 ElementIndex = 0) { static_assert(sizeof(ShaderRHIParamRef) == 0, "Passing unsupported "#_TYPE"d. Requires "#_TYPE"f"); }                              \
template<typename ShaderRHIParamRef, typename TRHICmdList>                                                                                                                              \
void SetShaderValueArray(TRHICmdList& RHICmdList, const ShaderRHIParamRef& Shader, const FShaderParameter& Parameter,                                                                    \
    const _TYPE##d* Values, uint32 NumElements, uint32 BaseElementIndex = 0) { static_assert(sizeof(ShaderRHIParamRef) == 0, "Passing unsupported "#_TYPE"d*. Requires "#_TYPE"f*"); }  \
Definition at line 490 of file ShaderParameterUtils.h.
Referenced by SetShaderValue(), SetShaderValue(), SetShaderValue(), SetShaderValue(), SetShaderValue(), SetShaderValue(), and SetShaderValue().
Typedef Documentation
TShaderRef
template<typename ShaderType> using TShaderRef = TShaderRefBase<ShaderType, FShaderMapPointerTable>
Definition at line 21 of file ShaderParameterUtils.h.
Function Documentation
SetBatchedShaderParametersMixed() [1/2]
template<typename TShaderType, typename... TArguments> void SetBatchedShaderParametersMixed (FRHIBatchedShaderParameters & BatchedParameters, const TShaderRef< TShaderType > & InShader, const typename TShaderType::FParameters & Parameters, TArguments &&... InArguments) inline
Utility to set all legacy and non-legacy parameters for a shader. Requires the shader type to implement SetParameters(FRHIBatchedShaderParameters& BatchedParameters, ...)
Definition at line 275 of file ShaderParameterUtils.h.
References Forward(), and SetShaderParameters().
Referenced by SetBatchedShaderParametersMixed(), SetShaderParametersMixed(), SetShaderParametersMixedAS(), SetShaderParametersMixedCS(), SetShaderParametersMixedGS(), SetShaderParametersMixedMS(), SetShaderParametersMixedPS(), SetShaderParametersMixedVS(), and SetShaderParametersMixedWS().
SetBatchedShaderParametersMixed() [2/2]
template<typename TShaderType, typename TShaderTypeRHI, typename... TArguments> void SetBatchedShaderParametersMixed (FRHIBatchedShaderParameters & BatchedParameters, const TShaderRef< TShaderType > & InShader, TShaderTypeRHI * InShaderRHI, const typename TShaderType::FParameters & Parameters, TArguments &&... InArguments) inline
Definition at line 290 of file ShaderParameterUtils.h.
References Forward(), and SetBatchedShaderParametersMixed().
SetSamplerParameter()
void SetSamplerParameter (FRHIBatchedShaderParameters & BatchedParameters, const FShaderResourceParameter & Parameter, FRHISamplerState * SamplerStateRHI) inline
Definition at line 94 of file ShaderParameterUtils.h.
References BindlessSampler.
Referenced by SetTextureParameter(), and SetTextureParameter().
SetShaderParametersLegacy()
template<typename TRHICmdList, typename TShaderType, typename TShaderTypeRHI, typename... TArguments> void SetShaderParametersLegacy (TRHICmdList & RHICmdList, const TShaderRef< TShaderType > & InShader, TShaderTypeRHI * InShaderRHI, TArguments &&... InArguments) inline
Utility to set all legacy parameters for a shader. Requires the shader type to implement SetParameters(FRHIBatchedShaderParameters& BatchedParameters, ...)
Definition at line 416 of file ShaderParameterUtils.h.
References Forward().
Referenced by SetShaderParametersLegacyAS(), SetShaderParametersLegacyCS(), SetShaderParametersLegacyGS(), SetShaderParametersLegacyMS(), SetShaderParametersLegacyPS(), and SetShaderParametersLegacyVS().
SetShaderParametersLegacyAS()
template<typename TRHICmdList, typename TShaderType, typename... TArguments> void SetShaderParametersLegacyAS (TRHICmdList & RHICmdList, const TShaderRef< TShaderType > & InShader, TArguments &&... InArguments) inline
Utility to set all legacy parameters for an Amplification shader. Requires the shader type to implement SetParameters(FRHIBatchedShaderParameters& BatchedParameters, ...)
Definition at line 439 of file ShaderParameterUtils.h.
References Forward(), TShaderRefBase< ShaderType, PointerTableType >::GetAmplificationShader(), and SetShaderParametersLegacy().
SetShaderParametersLegacyCS()
template<typename TRHICmdList, typename TShaderType, typename... TArguments> void SetShaderParametersLegacyCS (TRHICmdList & RHICmdList, const TShaderRef< TShaderType > & InShader, TArguments &&... InArguments) inline
Utility to set all legacy parameters for a Compute shader. Requires the shader type to implement SetParameters(FRHIBatchedShaderParameters& BatchedParameters, ...)
Definition at line 460 of file ShaderParameterUtils.h.
References Forward(), TShaderRefBase< ShaderType, PointerTableType >::GetComputeShader(), and SetShaderParametersLegacy().
SetShaderParametersLegacyGS()
template<typename TRHICmdList, typename TShaderType, typename... TArguments> void SetShaderParametersLegacyGS (TRHICmdList & RHICmdList, const TShaderRef< TShaderType > & InShader, TArguments &&... InArguments) inline
Utility to set all legacy parameters for a Geometry shader. Requires the shader type to implement SetParameters(FRHIBatchedShaderParameters& BatchedParameters, ...)
Definition at line 453 of file ShaderParameterUtils.h.
References Forward(), TShaderRefBase< ShaderType, PointerTableType >::GetGeometryShader(), and SetShaderParametersLegacy().
SetShaderParametersLegacyMS()
template<typename TRHICmdList, typename TShaderType, typename... TArguments> void SetShaderParametersLegacyMS (TRHICmdList & RHICmdList, const TShaderRef< TShaderType > & InShader, TArguments &&... InArguments) inline
Utility to set all legacy parameters for a Mesh shader. Requires the shader type to implement SetParameters(FRHIBatchedShaderParameters& BatchedParameters, ...)
Definition at line 432 of file ShaderParameterUtils.h.
References Forward(), TShaderRefBase< ShaderType, PointerTableType >::GetMeshShader(), and SetShaderParametersLegacy().
SetShaderParametersLegacyPS()
template<typename TRHICmdList, typename TShaderType, typename... TArguments> void SetShaderParametersLegacyPS (TRHICmdList & RHICmdList, const TShaderRef< TShaderType > & InShader, TArguments &&... InArguments) inline
Utility to set all legacy parameters for a Pixel shader. Requires the shader type to implement SetParameters(FRHIBatchedShaderParameters& BatchedParameters, ...)
Definition at line 446 of file ShaderParameterUtils.h.
References Forward(), TShaderRefBase< ShaderType, PointerTableType >::GetPixelShader(), and SetShaderParametersLegacy().
SetShaderParametersLegacyVS()
template<typename TRHICmdList, typename TShaderType, typename... TArguments> void SetShaderParametersLegacyVS (TRHICmdList & RHICmdList, const TShaderRef< TShaderType > & InShader, TArguments &&... InArguments) inline
Utility to set all legacy parameters for a Vertex shader. Requires the shader type to implement SetParameters(FRHIBatchedShaderParameters& BatchedParameters, ...)
Definition at line 425 of file ShaderParameterUtils.h.
References Forward(), TShaderRefBase< ShaderType, PointerTableType >::GetVertexShader(), and SetShaderParametersLegacy().
SetShaderParametersMixed()
template<typename TRHICmdList, typename TShaderType, typename TShaderTypeRHI, typename... TArguments> void SetShaderParametersMixed (TRHICmdList & RHICmdList, const TShaderRef< TShaderType > & InShader, TShaderTypeRHI * InShaderRHI, const typename TShaderType::FParameters & Parameters, TArguments &&... InArguments) inline
Utility to set all legacy and non-legacy parameters for a shader. Requires the shader type to implement SetParameters(FRHIBatchedShaderParameters& BatchedParameters, ...)
Definition at line 302 of file ShaderParameterUtils.h.
References Forward(), and SetBatchedShaderParametersMixed().
Referenced by SetShaderParametersMixedAS(), SetShaderParametersMixedCS(), SetShaderParametersMixedGS(), SetShaderParametersMixedMS(), SetShaderParametersMixedPS(), and SetShaderParametersMixedVS().
SetShaderParametersMixedAS() [1/2]
template<typename TShaderType, typename... TArguments> void SetShaderParametersMixedAS (FRHIBatchedShaderParameters & BatchedParameters, const TShaderRef< TShaderType > & InShader, const typename TShaderType::FParameters & Parameters, TArguments &&... InArguments) inline
Utility to set all legacy and non-legacy parameters for an Amplification shader. Requires the shader type to implement SetParameters(FRHIBatchedShaderParameters& BatchedParameters, ...)
Definition at line 333 of file ShaderParameterUtils.h.
References Forward(), SetBatchedShaderParametersMixed(), and SetShaderParametersMixedAS().
Referenced by SetShaderParametersMixedAS().
SetShaderParametersMixedAS() [2/2]
template<typename TRHICmdList, typename TShaderType, typename... TArguments> void SetShaderParametersMixedAS (TRHICmdList & RHICmdList, const TShaderRef< TShaderType > & InShader, const typename TShaderType::FParameters & Parameters, TArguments &&... InArguments) inline
Utility to set all legacy and non-legacy parameters for an Amplification shader. Requires the shader type to implement SetParameters(FRHIBatchedShaderParameters& BatchedParameters, ...)
Definition at line 386 of file ShaderParameterUtils.h.
References Forward(), TShaderRefBase< ShaderType, PointerTableType >::GetAmplificationShader(), and SetShaderParametersMixed().
SetShaderParametersMixedCS() [1/2]
template<typename TShaderType, typename... TArguments> void SetShaderParametersMixedCS (FRHIBatchedShaderParameters & BatchedParameters, const TShaderRef< TShaderType > & InShader, const typename TShaderType::FParameters & Parameters, TArguments &&... InArguments) inline
Utility to set all legacy and non-legacy parameters for a Compute shader. Requires the shader type to implement SetParameters(FRHIBatchedShaderParameters& BatchedParameters, ...)
Definition at line 357 of file ShaderParameterUtils.h.
References Forward(), SetBatchedShaderParametersMixed(), and SetShaderParametersMixedCS().
Referenced by SetShaderParametersMixedCS().
SetShaderParametersMixedCS() [2/2]
template<typename TRHICmdList, typename TShaderType, typename... TArguments> void SetShaderParametersMixedCS (TRHICmdList & RHICmdList, const TShaderRef< TShaderType > & InShader, const typename TShaderType::FParameters & Parameters, TArguments &&... InArguments) inline
Utility to set all legacy and non-legacy parameters for a Compute shader. Requires the shader type to implement SetParameters(FRHIBatchedShaderParameters& BatchedParameters, ...)
Definition at line 407 of file ShaderParameterUtils.h.
References Forward(), TShaderRefBase< ShaderType, PointerTableType >::GetComputeShader(), and SetShaderParametersMixed().
SetShaderParametersMixedGS() [1/2]
template<typename TShaderType, typename... TArguments> void SetShaderParametersMixedGS (FRHIBatchedShaderParameters & BatchedParameters, const TShaderRef< TShaderType > & InShader, const typename TShaderType::FParameters & Parameters, TArguments &&... InArguments) inline
Utility to set all legacy and non-legacy parameters for a Geometry shader. Requires the shader type to implement SetParameters(FRHIBatchedShaderParameters& BatchedParameters, ...)
Definition at line 349 of file ShaderParameterUtils.h.
References Forward(), SetBatchedShaderParametersMixed(), and SetShaderParametersMixedGS().
Referenced by SetShaderParametersMixedGS().
SetShaderParametersMixedGS() [2/2]
template<typename TRHICmdList, typename TShaderType, typename... TArguments> void SetShaderParametersMixedGS (TRHICmdList & RHICmdList, const TShaderRef< TShaderType > & InShader, const typename TShaderType::FParameters & Parameters, TArguments &&... InArguments) inline
Utility to set all legacy and non-legacy parameters for a Geometry shader. Requires the shader type to implement SetParameters(FRHIBatchedShaderParameters& BatchedParameters, ...)
Definition at line 400 of file ShaderParameterUtils.h.
References Forward(), TShaderRefBase< ShaderType, PointerTableType >::GetGeometryShader(), and SetShaderParametersMixed().
SetShaderParametersMixedMS() [1/2]
template<typename TShaderType, typename... TArguments> void SetShaderParametersMixedMS (FRHIBatchedShaderParameters & BatchedParameters, const TShaderRef< TShaderType > & InShader, const typename TShaderType::FParameters & Parameters, TArguments &&... InArguments) inline
Utility to set all legacy and non-legacy parameters for a Mesh shader. Requires the shader type to implement SetParameters(FRHIBatchedShaderParameters& BatchedParameters, ...)
Definition at line 325 of file ShaderParameterUtils.h.
References Forward(), SetBatchedShaderParametersMixed(), and SetShaderParametersMixedMS().
Referenced by SetShaderParametersMixedMS().
SetShaderParametersMixedMS() [2/2]
template<typename TRHICmdList, typename TShaderType, typename... TArguments> void SetShaderParametersMixedMS (TRHICmdList & RHICmdList, const TShaderRef< TShaderType > & InShader, const typename TShaderType::FParameters & Parameters, TArguments &&... InArguments) inline
Utility to set all legacy and non-legacy parameters for a Mesh shader. Requires the shader type to implement SetParameters(FRHIBatchedShaderParameters& BatchedParameters, ...)
Definition at line 379 of file ShaderParameterUtils.h.
References Forward(), TShaderRefBase< ShaderType, PointerTableType >::GetMeshShader(), and SetShaderParametersMixed().
SetShaderParametersMixedPS() [1/2]
template<typename TShaderType, typename... TArguments> void SetShaderParametersMixedPS (FRHIBatchedShaderParameters & BatchedParameters, const TShaderRef< TShaderType > & InShader, const typename TShaderType::FParameters & Parameters, TArguments &&... InArguments) inline
Utility to set all legacy and non-legacy parameters for a Pixel shader. Requires the shader type to implement SetParameters(FRHIBatchedShaderParameters& BatchedParameters, ...)
Definition at line 341 of file ShaderParameterUtils.h.
References Forward(), SetBatchedShaderParametersMixed(), and SetShaderParametersMixedPS().
Referenced by SetShaderParametersMixedPS().
SetShaderParametersMixedPS() [2/2]
template<typename TRHICmdList, typename TShaderType, typename... TArguments> void SetShaderParametersMixedPS (TRHICmdList & RHICmdList, const TShaderRef< TShaderType > & InShader, const typename TShaderType::FParameters & Parameters, TArguments &&... InArguments) inline
Utility to set all legacy and non-legacy parameters for a Pixel shader. Requires the shader type to implement SetParameters(FRHIBatchedShaderParameters& BatchedParameters, ...)
Definition at line 393 of file ShaderParameterUtils.h.
References Forward(), TShaderRefBase< ShaderType, PointerTableType >::GetPixelShader(), and SetShaderParametersMixed().
SetShaderParametersMixedVS() [1/2]
template<typename TShaderType, typename... TArguments> void SetShaderParametersMixedVS (FRHIBatchedShaderParameters & BatchedParameters, const TShaderRef< TShaderType > & InShader, const typename TShaderType::FParameters & Parameters, TArguments &&... InArguments) inline
Utility to set all legacy and non-legacy parameters for a Vertex shader. Requires the shader type to implement SetParameters(FRHIBatchedShaderParameters& BatchedParameters, ...)
Definition at line 317 of file ShaderParameterUtils.h.
References Forward(), SetBatchedShaderParametersMixed(), and SetShaderParametersMixedVS().
Referenced by SetShaderParametersMixedVS().
SetShaderParametersMixedVS() [2/2]
template<typename TRHICmdList, typename TShaderType, typename... TArguments> void SetShaderParametersMixedVS (TRHICmdList & RHICmdList, const TShaderRef< TShaderType > & InShader, const typename TShaderType::FParameters & Parameters, TArguments &&... InArguments) inline
Utility to set all legacy and non-legacy parameters for a Vertex shader. Requires the shader type to implement SetParameters(FRHIBatchedShaderParameters& BatchedParameters, ...)
Definition at line 372 of file ShaderParameterUtils.h.
References Forward(), TShaderRefBase< ShaderType, PointerTableType >::GetVertexShader(), and SetShaderParametersMixed().
SetShaderParametersMixedWS()
template<typename TShaderType, typename... TArguments> void SetShaderParametersMixedWS (FRHIBatchedShaderParameters & BatchedParameters, const TShaderRef< TShaderType > & InShader, const typename TShaderType::FParameters & Parameters, TArguments &&... InArguments) inline
Utility to set all legacy and non-legacy parameters for a WorkGraph shader. Requires the shader type to implement SetParameters(FRHIBatchedShaderParameters& BatchedParameters, ...)
Definition at line 365 of file ShaderParameterUtils.h.
References Forward(), SetBatchedShaderParametersMixed(), and SetShaderParametersMixedWS().
Referenced by SetShaderParametersMixedWS().
SetShaderValue() [1/9]
template<class ParameterType> void SetShaderValue (FRHIBatchedShaderParameters & BatchedParameters, const FShaderParameter & Parameter, const ParameterType & Value, uint32 ElementIndex = 0)
Definition at line 24 of file ShaderParameterUtils.h.
References Align, checkSlow, FMath::Min, TIsPointer< T >::Value, and Value.
Referenced by ClearUAVShader_T(), ClearUAVShader_T(), FCopyTextureCS::Dispatch(), FOculusCubemapPS::SetParameters(), FOculusCubemapPS::SetParameters(), FScreenPSArraySlice::SetParameters(), FScreenPSArraySlice::SetParameters(), FScreenPSMipLevel::SetParameters(), FScreenPSMipLevel::SetParameters(), FScreenPSsRGBSourceMipLevel::SetParameters(), FScreenPSsRGBSourceMipLevel::SetParameters(), FStereoLayerPS_Base::SetParameters(), FStereoLayerVS::SetParameters(), FUpdateTexture2DSubresourceCS::SetParameters(), TOneColorVS< bUsingNDCPositions, bUsingVertexLayers >::SetParameters(), and SetSingleShaderValue().
SetShaderValue() [2/9]
template<typename ShaderRHIParamRef, typename TRHICmdList> void SetShaderValue (TRHICmdList & RHICmdList, const ShaderRHIParamRef & Shader, const FShaderParameter & Parameter, const ::FSphere3d & Value, uint32 ElementIndex = 0)
Definition at line 509 of file ShaderParameterUtils.h.
References GUARD_SETSHADERVALUE.
SetShaderValue() [3/9]
template<typename ShaderRHIParamRef, typename TRHICmdList> void SetShaderValue (TRHICmdList & RHICmdList, const ShaderRHIParamRef & Shader, const FShaderParameter & Parameter, const FBox3d & Value, uint32 ElementIndex = 0)
Definition at line 510 of file ShaderParameterUtils.h.
References GUARD_SETSHADERVALUE.
SetShaderValue() [4/9]
template<typename ShaderRHIParamRef, typename TRHICmdList> void SetShaderValue (TRHICmdList & RHICmdList, const ShaderRHIParamRef & Shader, const FShaderParameter & Parameter, const FMatrix44d & Value, uint32 ElementIndex = 0)
Definition at line 502 of file ShaderParameterUtils.h.
SetShaderValue() [5/9]
template<typename ShaderRHIParamRef, typename TRHICmdList> void SetShaderValue (TRHICmdList & RHICmdList, const ShaderRHIParamRef & Shader, const FShaderParameter & Parameter, const FPlane4d & Value, uint32 ElementIndex = 0)
Definition at line 506 of file ShaderParameterUtils.h.
References GUARD_SETSHADERVALUE.
SetShaderValue() [6/9]
template<typename ShaderRHIParamRef, typename TRHICmdList> void SetShaderValue (TRHICmdList & RHICmdList, const ShaderRHIParamRef & Shader, const FShaderParameter & Parameter, const FQuat4d & Value, uint32 ElementIndex = 0)
Definition at line 507 of file ShaderParameterUtils.h.
References GUARD_SETSHADERVALUE.
SetShaderValue() [7/9]
template<typename ShaderRHIParamRef, typename TRHICmdList> void SetShaderValue (TRHICmdList & RHICmdList, const ShaderRHIParamRef & Shader, const FShaderParameter & Parameter, const FVector2d & Value, uint32 ElementIndex = 0)
Definition at line 503 of file ShaderParameterUtils.h.
References GUARD_SETSHADERVALUE.
SetShaderValue() [8/9]
template<typename ShaderRHIParamRef, typename TRHICmdList> void SetShaderValue (TRHICmdList & RHICmdList, const ShaderRHIParamRef & Shader, const FShaderParameter & Parameter, const FVector3d & Value, uint32 ElementIndex = 0)
Definition at line 504 of file ShaderParameterUtils.h.
References GUARD_SETSHADERVALUE.
SetShaderValue() [9/9]
template<typename ShaderRHIParamRef, typename TRHICmdList> void SetShaderValue (TRHICmdList & RHICmdList, const ShaderRHIParamRef & Shader, const FShaderParameter & Parameter, const FVector4d & Value, uint32 ElementIndex = 0)
Definition at line 505 of file ShaderParameterUtils.h.
References GUARD_SETSHADERVALUE.
SetShaderValueArray() [1/9]
template<class ParameterType> void SetShaderValueArray (FRHIBatchedShaderParameters & BatchedParameters, const FShaderParameter & Parameter, const ParameterType * Values, uint32 NumElements, uint32 ElementIndex = 0)
Definition at line 51 of file ShaderParameterUtils.h.
References Align, checkSlow, and FMath::Min.
SetShaderValueArray() [2/9]
template<typename ShaderRHIParamRef, typename TRHICmdList> void SetShaderValueArray (TRHICmdList & RHICmdList, const ShaderRHIParamRef & Shader, const FShaderParameter & Parameter, const ::FSphere3d * Values, uint32 NumElements, uint32 BaseElementIndex = 0)
Definition at line 509 of file ShaderParameterUtils.h.
SetShaderValueArray() [3/9]
template<typename ShaderRHIParamRef, typename TRHICmdList> void SetShaderValueArray (TRHICmdList & RHICmdList, const ShaderRHIParamRef & Shader, const FShaderParameter & Parameter, const FBox3d * Values, uint32 NumElements, uint32 BaseElementIndex = 0)
Definition at line 510 of file ShaderParameterUtils.h.
SetShaderValueArray() [4/9]
template<typename ShaderRHIParamRef, typename TRHICmdList> void SetShaderValueArray (TRHICmdList & RHICmdList, const ShaderRHIParamRef & Shader, const FShaderParameter & Parameter, const FMatrix44d * Values, uint32 NumElements, uint32 BaseElementIndex = 0)
Definition at line 502 of file ShaderParameterUtils.h.
SetShaderValueArray() [5/9]
template<typename ShaderRHIParamRef, typename TRHICmdList> void SetShaderValueArray (TRHICmdList & RHICmdList, const ShaderRHIParamRef & Shader, const FShaderParameter & Parameter, const FPlane4d * Values, uint32 NumElements, uint32 BaseElementIndex = 0)
Definition at line 506 of file ShaderParameterUtils.h.
SetShaderValueArray() [6/9]
template<typename ShaderRHIParamRef, typename TRHICmdList> void SetShaderValueArray (TRHICmdList & RHICmdList, const ShaderRHIParamRef & Shader, const FShaderParameter & Parameter, const FQuat4d * Values, uint32 NumElements, uint32 BaseElementIndex = 0)
Definition at line 507 of file ShaderParameterUtils.h.
SetShaderValueArray() [7/9]
template<typename ShaderRHIParamRef, typename TRHICmdList> void SetShaderValueArray (TRHICmdList & RHICmdList, const ShaderRHIParamRef & Shader, const FShaderParameter & Parameter, const FVector2d * Values, uint32 NumElements, uint32 BaseElementIndex = 0)
Definition at line 503 of file ShaderParameterUtils.h.
SetShaderValueArray() [8/9]
template<typename ShaderRHIParamRef, typename TRHICmdList> void SetShaderValueArray (TRHICmdList & RHICmdList, const ShaderRHIParamRef & Shader, const FShaderParameter & Parameter, const FVector3d * Values, uint32 NumElements, uint32 BaseElementIndex = 0)
Definition at line 504 of file ShaderParameterUtils.h.
SetShaderValueArray() [9/9]
template<typename ShaderRHIParamRef, typename TRHICmdList> void SetShaderValueArray (TRHICmdList & RHICmdList, const ShaderRHIParamRef & Shader, const FShaderParameter & Parameter, const FVector4d * Values, uint32 NumElements, uint32 BaseElementIndex = 0)
Definition at line 505 of file ShaderParameterUtils.h.
SetShaderValueOnContext() [1/8]
template<typename ShaderRHIParamRef> void SetShaderValueOnContext (IRHICommandContext & RHICmdListContext, const ShaderRHIParamRef & Shader, const FShaderParameter & Parameter, const ::FSphere3d & Value, uint32 ElementIndex = 0)
Definition at line 509 of file ShaderParameterUtils.h.
SetShaderValueOnContext() [2/8]
template<typename ShaderRHIParamRef> void SetShaderValueOnContext (IRHICommandContext & RHICmdListContext, const ShaderRHIParamRef & Shader, const FShaderParameter & Parameter, const FBox3d & Value, uint32 ElementIndex = 0)
Definition at line 510 of file ShaderParameterUtils.h.
SetShaderValueOnContext() [3/8]
template<typename ShaderRHIParamRef> void SetShaderValueOnContext (IRHICommandContext & RHICmdListContext, const ShaderRHIParamRef & Shader, const FShaderParameter & Parameter, const FMatrix44d & Value, uint32 ElementIndex = 0)
Definition at line 502 of file ShaderParameterUtils.h.
SetShaderValueOnContext() [4/8]
template<typename ShaderRHIParamRef> void SetShaderValueOnContext (IRHICommandContext & RHICmdListContext, const ShaderRHIParamRef & Shader, const FShaderParameter & Parameter, const FPlane4d & Value, uint32 ElementIndex = 0)
Definition at line 506 of file ShaderParameterUtils.h.
SetShaderValueOnContext() [5/8]
template<typename ShaderRHIParamRef> void SetShaderValueOnContext (IRHICommandContext & RHICmdListContext, const ShaderRHIParamRef & Shader, const FShaderParameter & Parameter, const FQuat4d & Value, uint32 ElementIndex = 0)
Definition at line 507 of file ShaderParameterUtils.h.
SetShaderValueOnContext() [6/8]
template<typename ShaderRHIParamRef> void SetShaderValueOnContext (IRHICommandContext & RHICmdListContext, const ShaderRHIParamRef & Shader, const FShaderParameter & Parameter, const FVector2d & Value, uint32 ElementIndex = 0)
Definition at line 503 of file ShaderParameterUtils.h.
SetShaderValueOnContext() [7/8]
template<typename ShaderRHIParamRef> void SetShaderValueOnContext (IRHICommandContext & RHICmdListContext, const ShaderRHIParamRef & Shader, const FShaderParameter & Parameter, const FVector3d & Value, uint32 ElementIndex = 0)
Definition at line 504 of file ShaderParameterUtils.h.
SetShaderValueOnContext() [8/8]
template<typename ShaderRHIParamRef> void SetShaderValueOnContext (IRHICommandContext & RHICmdListContext, const ShaderRHIParamRef & Shader, const FShaderParameter & Parameter, const FVector4d & Value, uint32 ElementIndex = 0)
Definition at line 505 of file ShaderParameterUtils.h.
SetSingleShaderValue()
template<typename TRHICmdList, typename TShaderTypeRHI, class ParameterType> void SetSingleShaderValue (TRHICmdList & RHICmdList, TShaderTypeRHI * InShaderRHI, const FShaderParameter & Parameter, const ParameterType & Value)
Definition at line 259 of file ShaderParameterUtils.h.
References SetShaderValue(), and Value.
SetSRVParameter()
void SetSRVParameter (FRHIBatchedShaderParameters & BatchedParameters, const FShaderResourceParameter & Parameter, FRHIShaderResourceView * SRV) inline
Definition at line 139 of file ShaderParameterUtils.h.
References BindlessSRV, and SRV.
SetTextureParameter() [1/4]
void SetTextureParameter (FRHIBatchedShaderParameters & BatchedParameters, const FShaderResourceParameter & Parameter, FRHITexture * TextureRHI) inline
Definition at line 77 of file ShaderParameterUtils.h.
References BindlessSRV.
Referenced by FOculusAlphaInverseShader::SetParameters(), FOculusAlphaInverseShader::SetParameters(), FOculusCubemapPS::SetParameters(), FOculusCubemapPS::SetParameters(), FScreenPS::SetParameters(), FScreenPS::SetParameters(), FScreenPS_OSE::SetParameters(), FScreenPS_OSE::SetParameters(), FScreenPSArraySlice::SetParameters(), FScreenPSArraySlice::SetParameters(), FScreenPSInvertAlpha::SetParameters(), FScreenPSInvertAlpha::SetParameters(), FScreenPSMipLevel::SetParameters(), FScreenPSMipLevel::SetParameters(), FScreenPSsRGBSource::SetParameters(), FScreenPSsRGBSource::SetParameters(), FScreenPSsRGBSourceMipLevel::SetParameters(), FScreenPSsRGBSourceMipLevel::SetParameters(), FStereoLayerPS_Base::SetParameters(), SetTextureParameter(), SetTextureParameter(), and SetTextureParameter().
SetTextureParameter() [2/4]
void SetTextureParameter (FRHIBatchedShaderParameters & BatchedParameters, const FShaderResourceParameter & TextureParameter, const FShaderResourceParameter & SamplerParameter, const FTexture * Texture) inline
Definition at line 123 of file ShaderParameterUtils.h.
References FApp::GetCurrentTime(), FShaderResourceParameter::IsBound(), SetSamplerParameter(), SetTextureParameter(), and Texture.
SetTextureParameter() [3/4]
void SetTextureParameter (FRHIBatchedShaderParameters & BatchedParameters, const FShaderResourceParameter & TextureParameter, const FShaderResourceParameter & SamplerParameter, FRHISamplerState * SamplerStateRHI, FRHITexture * TextureRHI) inline
Definition at line 111 of file ShaderParameterUtils.h.
References SetSamplerParameter(), and SetTextureParameter().
SetTextureParameter() [4/4]
template<typename TRHIShader, typename TRHICmdList> void SetTextureParameter (TRHICmdList & RHICmdList, TRHIShader * Shader, const FShaderResourceParameter & TextureParameter, const FShaderResourceParameter & SamplerParameter, FRHISamplerState * SamplerStateRHI, FRHITexture * TextureRHI)
Sets the value of a shader texture parameter.
Template'd on shader type.
Definition at line 516 of file ShaderParameterUtils.h.
References FORCEINLINE, and SetTextureParameter().
SetUAVParameter()
void SetUAVParameter (FRHIBatchedShaderParameters & BatchedParameters, const FShaderResourceParameter & Parameter, FRHIUnorderedAccessView * UAV) inline
Definition at line 156 of file ShaderParameterUtils.h.
References BindlessUAV, and UAV.
Referenced by ClearUAVShader_T().
SetUniformBufferParameter() [1/3]
void SetUniformBufferParameter (FRHIBatchedShaderParameters & BatchedParameters, const FShaderUniformBufferParameter & Parameter, FRHIUniformBuffer * UniformBufferRHI) inline
Definition at line 207 of file ShaderParameterUtils.h.
References checkSlow.
Referenced by FGlobalShader::SetParameters(), SetUniformBufferParameter(), SetUniformBufferParameter(), and SetUniformBufferParameterImmediate().
SetUniformBufferParameter() [2/3]
template<typename TBufferStruct> void SetUniformBufferParameter (FRHIBatchedShaderParameters & BatchedParameters, const TShaderUniformBufferParameter< TBufferStruct > & Parameter, const TUniformBuffer< TBufferStruct > & UniformBuffer) inline
Definition at line 233 of file ShaderParameterUtils.h.
References checkSlow, SetUniformBufferParameter(), and UniformBuffer.
SetUniformBufferParameter() [3/3]
template<typename TBufferStruct> void SetUniformBufferParameter (FRHIBatchedShaderParameters & BatchedParameters, const TShaderUniformBufferParameter< TBufferStruct > & Parameter, const TUniformBufferRef< TBufferStruct > & UniformBufferRef) inline
Definition at line 220 of file ShaderParameterUtils.h.
References checkSlow, IsValidRef(), and SetUniformBufferParameter().
SetUniformBufferParameterImmediate()
template<typename TBufferStruct> void SetUniformBufferParameterImmediate (FRHIBatchedShaderParameters & BatchedParameters, const TShaderUniformBufferParameter< TBufferStruct > & Parameter, const TBufferStruct & UniformBufferValue) inline
Definition at line 246 of file ShaderParameterUtils.h.
References checkSlow, and SetUniformBufferParameter().
UnsetShaderParametersLegacyCS()
template<typename TRHICmdList, typename TShaderType> void UnsetShaderParametersLegacyCS (TRHICmdList & RHICmdList, const TShaderRef< TShaderType > & InShader) inline
Utility to unset all legacy parameters for a Compute shader. Requires the shader type to implement UnsetParameters(FRHIBatchedShaderUnbinds& BatchedUnbinds)
Definition at line 479 of file ShaderParameterUtils.h.
References TShaderRefBase< ShaderType, PointerTableType >::GetComputeShader().
UnsetShaderParametersLegacyPS()
template<typename TRHICmdList, typename TShaderType> void UnsetShaderParametersLegacyPS (TRHICmdList & RHICmdList, const TShaderRef< TShaderType > & InShader) inline
Utility to unset all legacy parameters for a Pixel shader. Requires the shader type to implement UnsetParameters(FRHIBatchedShaderUnbinds& BatchedUnbinds)
Definition at line 467 of file ShaderParameterUtils.h.
References TShaderRefBase< ShaderType, PointerTableType >::GetPixelShader().
UnsetSRVParameter()
void UnsetSRVParameter (FRHIBatchedShaderUnbinds & BatchedUnbinds, const FShaderResourceParameter & Parameter) inline
Definition at line 173 of file ShaderParameterUtils.h.
References BindlessSRV.
UnsetUAVParameter()
void UnsetUAVParameter (FRHIBatchedShaderUnbinds & BatchedUnbinds, const FShaderResourceParameter & Parameter) inline
Definition at line 190 of file ShaderParameterUtils.h.
References BindlessSRV.
Referenced by ClearUAVShader_T().