Unreal Engine 5.6 C++ API: Runtime/Engine/Public/ShaderCompiler.h File Reference
ShaderCompiler.h File Reference
#include "Templates/RefCounting.h"
#include "HAL/PlatformProcess.h"
#include "ShaderCore.h"
#include "ShaderCompilerCore.h"
#include "ShaderCompilerJobTypes.h"
#include "Shader.h"
#include "HAL/RunnableThread.h"
#include "HAL/Runnable.h"
#include "Templates/Atomic.h"
#include "Templates/UniquePtr.h"
#include "HAL/ThreadSafeCounter.h"
#include "RHIDefinitions.h"
#include "GBufferInfo.h"
#include "ShaderMaterial.h"
#include "Misc/ScopeRWLock.h"
#include "IAssetCompilingManager.h"
#include "Containers/HashTable.h"
#include "Containers/List.h"
#include "Containers/Deque.h"
#include "Hash/Blake3.h"
#include "Hash/CityHash.h"
#include "SceneTypes.h"
#include "UObject/StrongObjectPtr.h"
#include "ShaderCompiler.generated.h"
Data Structures
class FGlobalShaderTypeCompiler
struct FODSCRequestPayload
class FShaderCompileDistributedThreadRunnable_Interface
class FShaderCompileJobCollection
struct FShaderCompileMemoryUsage
struct FShaderCompilerStats
struct FShaderCompilerStats::FWorkerDiagnosticsInfo
class FShaderCompileThreadRunnable
Shader compiling thread This runs in the background while UE is running, launches shader compile worker processes when necessary, and feeds them inputs and reads back the outputs.
struct FShaderCompileThreadRunnable::FMemoryMonitoringState
class FShaderCompileThreadRunnableBase
class FShaderCompileUtilities
class FShaderCompilingManager
Manager of asynchronous and parallel shader compilation.
struct FShaderRecompileData
Macros
#define DEBUG_INFINITESHADERCOMPILE 0
Typedefs
using FShaderMapFinalizeResults = FShaderMapCompileResults
Results for a single compiled and finalized shader map.
Enumerations
enum class ODSCRecompileCommand {
None , Changed , Global , Material ,
SingleShader , ResetMaterialCache
}
Functions
bool AreShaderErrorsFatal ()
void BeginRecompileGlobalShaders (const TArray< const FShaderType * > &OutdatedShaderTypes, const TArray< const FShaderPipelineType * > &OutdatedShaderPipelineTypes, EShaderPlatform ShaderPlatform, const ITargetPlatform *TargetPlatform=nullptr, const FShaderCompilerFlags &InExtraCompilerFlags={})
Begins recompiling the specified global shader types, and flushes their bound shader states.
void CompileGlobalShaderMap (bool bRefreshShaderMap=false)
void CompileGlobalShaderMap (ERHIFeatureLevel::Type InFeatureLevel, bool bRefreshShaderMap=false)
void CompileGlobalShaderMap (EShaderPlatform Platform, bool bRefreshShaderMap=false)
void CompileGlobalShaderMap (EShaderPlatform Platform, const ITargetPlatform *TargetPlatform, bool bRefreshShaderMap)
bool CreateShadersOnLoad ()
DECLARE_LOG_CATEGORY_EXTERN (LogShaderCompilers, Log, All)
void DumpShaderDDCKeyToFile (const EShaderPlatform InPlatform, bool bWithEditor, const TCHAR *DebugGroupName, const FString &DDCKey)
void FinishRecompileGlobalShaders ()
Finishes recompiling global shaders.
const FGuid & GetGlobalShaderMapDDCGuid ()
const FGuid & GetMaterialShaderMapDDCGuid ()
void GetOutdatedShaderTypes (TArray< const FShaderType * > &OutdatedShaderTypes, TArray< const FShaderPipelineType * > &OutdatedShaderPipelineTypes, TArray< const FVertexFactoryType * > &OutdatedFactoryTypes)
void GlobalBeginCompileShader (const FString &DebugGroupName, const class FVertexFactoryType *VFType, const class FShaderType *ShaderType, const class FShaderPipelineType *ShaderPipelineType, int32 PermutationId, const TCHAR *SourceFilename, const TCHAR *FunctionName, FShaderTarget Target, FShaderCompilerInput &Input, bool bAllowDevelopmentShaderCompile, const FString &DebugDescription, const FString &DebugExtension)
Enqueues a shader compile job with GShaderCompilingManager.
void GlobalBeginCompileShader (const FString &DebugGroupName, const class FVertexFactoryType *VFType, const class FShaderType *ShaderType, const class FShaderPipelineType *ShaderPipelineType, int32 PermutationId, const TCHAR *SourceFilename, const TCHAR *FunctionName, FShaderTarget Target, FShaderCompilerInput &Input, bool bAllowDevelopmentShaderCompile=true, const TCHAR *DebugDescription=nullptr, const TCHAR *DebugExtension=nullptr)
Enqueues a shader compile job with GShaderCompilingManager.
bool IsGlobalShaderMapComplete (const TCHAR *TypeNameSubstring=nullptr)
Returns whether all global shader types containing the substring are complete and ready for rendering.
bool IsMaterialMapDDCEnabled ()
bool IsShaderJobCacheDDCEnabled ()
void LoadGlobalShadersForRemoteRecompile (FArchive &Ar, EShaderPlatform ShaderPlatform)
Serializes a global shader map to an archive (used with recompiling shaders for a remote console)
const TCHAR * ODSCCmdEnumToString (ODSCRecompileCommand Cmd)
void PrecacheComputePipelineStatesForGlobalShaders (ERHIFeatureLevel::Type FeatureLevel, const ITargetPlatform *TargetPlatform)
Precreates compute PSOs for global shaders.
void ProcessCompiledGlobalShaders (const TArray< FShaderCommonCompileJobPtr > &CompilationResults)
Called by the shader compiler to process completed global shader jobs.
void ProcessCookOnTheFlyShaders (bool bReloadGlobalShaders, const TArray< uint8 > &MeshMaterialMaps, const TArray< FString > &MaterialsToLoad, const TArray< uint8 > &GlobalShaderMap)
Handles serializing in MeshMaterialMaps or GlobalShaderMap from a CookOnTheFly command and applying them to the in-memory shadermaps.
bool RecompileChangedShadersForPlatform (const FString &PlatformName)
Recompiles global shaders and material shaders rebuilds global shaders and also clears the cooked platform data for all materials if there is a global shader change detected can be slow.
void RecompileGlobalShaders ()
Forces a recompile of the global shaders.
bool RecompileShaders (const TCHAR *Cmd, FOutputDevice &Ar)
Implementation of the 'recompileshaders' console command.
void RecompileShadersForRemote (FShaderRecompileData &Args, const FString &OutputDirectory)
Recompiles global shaders.
FString SaveGlobalShaderFile (EShaderPlatform Platform, FString SavePath, class ITargetPlatform *TargetPlatform=nullptr)
Saves the global shader map as a file for the target platform.
void SaveGlobalShadersForRemoteRecompile (FArchive &Ar, EShaderPlatform ShaderPlatform)
Serializes a global shader map to an archive (used with recompiling shaders for a remote console)
bool ShouldCompileODSCOnlyShaders ()
Returns true if we should compile shaders that are only compiled in on demand shader compilation modes and not stored in cooked shader maps.
bool ShouldDumpShaderDDCKeys ()
void ShutdownGlobalShaderMap ()
void ShutdownShaderCompilers (TConstArrayView< const ITargetPlatform * > TargetPlatforms)
Frees resources and finalizes artifacts created during the cook of the given platforms.
UE_DEPRECATED (5.5, "Use GetGlobalShaderMapDDCGuid") extern 1 const FString &GetGlobalShaderMapDDCKey()
UE_DEPRECATED (5.5, "Use GetMaterialShaderMapDDCGuid") extern 1 const FString &GetMaterialShaderMapDDCKey()
USTRUCT () struct FShaderTimings
Structure used to describe compiling time of a shader type (for all the instances of it that we have seen).
void VerifyGlobalShaders (EShaderPlatform Platform, bool bLoadedFromCacheFile, const TArray< const FShaderType * > *OutdatedShaderTypes=nullptr, const TArray< const FShaderPipelineType * > *OutdatedShaderPipelineTypes=nullptr)
Makes sure all global shaders are loaded and/or compiled for the passed in platform.
void VerifyGlobalShaders (EShaderPlatform Platform, const ITargetPlatform *TargetPlatform, bool bLoadedFromCacheFile, const TArray< const FShaderType * > *OutdatedShaderTypes=nullptr, const TArray< const FShaderPipelineType * > *OutdatedShaderPipelineTypes=nullptr, const FShaderCompilerFlags &InExtraCompilerFlags={})
Variables
FShaderCompilerStats * GShaderCompilerStats
The global shader compiling stats.
FShaderCompilingManager * GShaderCompilingManager
The global shader compiling thread manager.
Macro Definition Documentation
DEBUG_INFINITESHADERCOMPILE
#define DEBUG_INFINITESHADERCOMPILE 0
Definition at line 51 of file ShaderCompiler.h.
Typedef Documentation
FShaderMapFinalizeResults
using FShaderMapFinalizeResults = FShaderMapCompileResults
Results for a single compiled and finalized shader map.
Definition at line 401 of file ShaderCompiler.h.
Enumeration Type Documentation
ODSCRecompileCommand
enum class ODSCRecompileCommand strong
Enumerator
None
Changed
Global
Material
SingleShader
ResetMaterialCache
Definition at line 1444 of file ShaderCompiler.h.
Function Documentation
AreShaderErrorsFatal()
bool AreShaderErrorsFatal ()
BeginRecompileGlobalShaders()
void BeginRecompileGlobalShaders (const TArray< const FShaderType * > & OutdatedShaderTypes, const TArray< const FShaderPipelineType * > & OutdatedShaderPipelineTypes, EShaderPlatform ShaderPlatform, const ITargetPlatform * TargetPlatform = nullptr, const FShaderCompilerFlags & InExtraCompilerFlags = {}) extern
Begins recompiling the specified global shader types, and flushes their bound shader states.
FinishRecompileGlobalShaders must be called after this and before using the global shaders for anything.
References ShaderPlatform.
CompileGlobalShaderMap() [1/4]
void CompileGlobalShaderMap (bool bRefreshShaderMap = false) extern
CompileGlobalShaderMap() [2/4]
void CompileGlobalShaderMap (ERHIFeatureLevel::Type InFeatureLevel, bool bRefreshShaderMap = false) extern
CompileGlobalShaderMap() [3/4]
void CompileGlobalShaderMap (EShaderPlatform Platform, bool bRefreshShaderMap = false) extern
References Platform.
CompileGlobalShaderMap() [4/4]
void CompileGlobalShaderMap (EShaderPlatform Platform, const ITargetPlatform * TargetPlatform, bool bRefreshShaderMap) extern
References Platform.
CreateShadersOnLoad()
bool CreateShadersOnLoad ()
DECLARE_LOG_CATEGORY_EXTERN()
DECLARE_LOG_CATEGORY_EXTERN (LogShaderCompilers , Log , All)
References All, and Log.
DumpShaderDDCKeyToFile()
void DumpShaderDDCKeyToFile (const EShaderPlatform InPlatform, bool bWithEditor, const TCHAR * DebugGroupName, const FString & DDCKey) extern
References DumpShaderDDCKeyToFile().
Referenced by DumpShaderDDCKeyToFile().
FinishRecompileGlobalShaders()
void FinishRecompileGlobalShaders () extern
Finishes recompiling global shaders.
Must be called after BeginRecompileGlobalShaders.
GetGlobalShaderMapDDCGuid()
const FGuid & GetGlobalShaderMapDDCGuid () extern
References GetGlobalShaderMapDDCGuid().
Referenced by GetGlobalShaderMapDDCGuid().
GetMaterialShaderMapDDCGuid()
const FGuid & GetMaterialShaderMapDDCGuid () extern
References GetMaterialShaderMapDDCGuid().
Referenced by GetMaterialShaderMapDDCGuid().
GetOutdatedShaderTypes()
void GetOutdatedShaderTypes (TArray< const FShaderType * > & OutdatedShaderTypes, TArray< const FShaderPipelineType * > & OutdatedShaderPipelineTypes, TArray< const FVertexFactoryType * > & OutdatedFactoryTypes) extern
GlobalBeginCompileShader() [1/2]
void GlobalBeginCompileShader (const FString & DebugGroupName, const class FVertexFactoryType * VFType, const class FShaderType * ShaderType, const class FShaderPipelineType * ShaderPipelineType, int32 PermutationId, const TCHAR * SourceFilename, const TCHAR * FunctionName, FShaderTarget Target, FShaderCompilerInput & Input, bool bAllowDevelopmentShaderCompile, const FString & DebugDescription, const FString & DebugExtension) extern
Enqueues a shader compile job with GShaderCompilingManager.
References Input, and Target.
GlobalBeginCompileShader() [2/2]
void GlobalBeginCompileShader (const FString & DebugGroupName, const class FVertexFactoryType * VFType, const class FShaderType * ShaderType, const class FShaderPipelineType * ShaderPipelineType, int32 PermutationId, const TCHAR * SourceFilename, const TCHAR * FunctionName, FShaderTarget Target, FShaderCompilerInput & Input, bool bAllowDevelopmentShaderCompile = true, const TCHAR * DebugDescription = nullptr, const TCHAR * DebugExtension = nullptr) extern
Enqueues a shader compile job with GShaderCompilingManager.
References Input, and Target.
IsGlobalShaderMapComplete()
bool IsGlobalShaderMapComplete (const TCHAR * TypeNameSubstring = nullptr) extern
Returns whether all global shader types containing the substring are complete and ready for rendering.
if type name is null, check everything
IsMaterialMapDDCEnabled()
bool IsMaterialMapDDCEnabled () extern
IsShaderJobCacheDDCEnabled()
bool IsShaderJobCacheDDCEnabled () extern
LoadGlobalShadersForRemoteRecompile()
void LoadGlobalShadersForRemoteRecompile (FArchive & Ar, EShaderPlatform ShaderPlatform) extern
Serializes a global shader map to an archive (used with recompiling shaders for a remote console)
References Ar, and ShaderPlatform.
ODSCCmdEnumToString()
const TCHAR * ODSCCmdEnumToString (ODSCRecompileCommand Cmd) extern
References Cmd.
PrecacheComputePipelineStatesForGlobalShaders()
void PrecacheComputePipelineStatesForGlobalShaders (ERHIFeatureLevel::Type FeatureLevel, const ITargetPlatform * TargetPlatform) extern
Precreates compute PSOs for global shaders.
Separate from Compile/VerifyGlobalShaders to avoid blocking loads.
ProcessCompiledGlobalShaders()
void ProcessCompiledGlobalShaders (const TArray< FShaderCommonCompileJobPtr > & CompilationResults) extern
Called by the shader compiler to process completed global shader jobs.
ProcessCookOnTheFlyShaders()
void ProcessCookOnTheFlyShaders (bool bReloadGlobalShaders, const TArray< uint8 > & MeshMaterialMaps, const TArray< FString > & MaterialsToLoad, const TArray< uint8 > & GlobalShaderMap) extern
Handles serializing in MeshMaterialMaps or GlobalShaderMap from a CookOnTheFly command and applying them to the in-memory shadermaps.
Parameters
MeshMaterialMaps Byte array that contains the serialized material shadermap from across the network.
MaterialsToLoad The materials contained in the MeshMaterialMaps
GlobalShaderMap Byte array that contains the serialized global shadermap from across the network.
References ProcessCookOnTheFlyShaders().
Referenced by ProcessCookOnTheFlyShaders().
RecompileChangedShadersForPlatform()
bool RecompileChangedShadersForPlatform (const FString & PlatformName) extern
Recompiles global shaders and material shaders rebuilds global shaders and also clears the cooked platform data for all materials if there is a global shader change detected can be slow.
RecompileGlobalShaders()
void RecompileGlobalShaders () extern
Forces a recompile of the global shaders.
RecompileShaders()
bool RecompileShaders (const TCHAR * Cmd, FOutputDevice & Ar) extern
Implementation of the 'recompileshaders' console command.
Recompiles shaders at runtime based on various criteria.
References Ar, and Cmd.
RecompileShadersForRemote()
void RecompileShadersForRemote (FShaderRecompileData & Args, const FString & OutputDirectory) extern
Recompiles global shaders.
Parameters
Args Arguments and configuration for issuing recompiles.
OutputDirectory The directory the compiled data will be stored to
SaveGlobalShaderFile()
FString SaveGlobalShaderFile (EShaderPlatform Platform, FString SavePath, class ITargetPlatform * TargetPlatform = nullptr) extern
Saves the global shader map as a file for the target platform.
Returns
the name of the file written
References Platform.
SaveGlobalShadersForRemoteRecompile()
void SaveGlobalShadersForRemoteRecompile (FArchive & Ar, EShaderPlatform ShaderPlatform) extern
Serializes a global shader map to an archive (used with recompiling shaders for a remote console)
References Ar, and ShaderPlatform.
ShouldCompileODSCOnlyShaders()
bool ShouldCompileODSCOnlyShaders () extern
Returns true if we should compile shaders that are only compiled in on demand shader compilation modes and not stored in cooked shader maps.
This can be useful for debug shaders.
ShouldDumpShaderDDCKeys()
bool ShouldDumpShaderDDCKeys () extern
References ShouldDumpShaderDDCKeys().
Referenced by ShouldDumpShaderDDCKeys().
ShutdownGlobalShaderMap()
void ShutdownGlobalShaderMap () extern
ShutdownShaderCompilers()
void ShutdownShaderCompilers (TConstArrayView< const ITargetPlatform * > TargetPlatforms) extern
Frees resources and finalizes artifacts created during the cook of the given platforms.
UE_DEPRECATED() [1/2]
UE_DEPRECATED (5. 5, "Use GetGlobalShaderMapDDCGuid") const &
UE_DEPRECATED() [2/2]
UE_DEPRECATED (5. 5, "Use GetMaterialShaderMapDDCGuid") const &
References UE_DEPRECATED.
USTRUCT()
USTRUCT ()
Structure used to describe compiling time of a shader type (for all the instances of it that we have seen).
Can be dumped to CSV file via 'r.ShaderCompiler.DumpShaderTimeStats' CVar.
This tracks accumulated wait time from local workers during the lifetime of the stats.
Wait time is only counted for local workers that are alive and not between their invocations
How many times we registered idle time?
Number of jobs assigned to workers, no matter if they completed or not - used to average pending time.
Total number jobs completed.
Amount of time a job had to spent in pending queue (i.e. waiting to be assigned to a worker).
Max amount of time any single job was pending (waiting to be assigned to a worker).
Amount of time job spent being processed by the worker.
Max amount of time any single job spent being processed by the worker.
Amount of time job spent being processed overall.
Max amount of time any single job spent being processed overall.
Time spent in tasks generated in FShaderJobCache::SubmitJobs, plus stall time on mutex locks in those tasks
Number of local job batches seen.
Total jobs in local job batches.
Number of distributed job batches seen.
Total jobs in local job batches.
Size of the smallest output shader code.
Size of the largest output shader code.
Total accumulated size of all output shader codes.
Number of accumulated output shader codes.
Total number of DDC misses on shader maps.
Total number of DDC hits on shader maps.
Total number of job cache query attempts.
Total number of hits in the job cache (i.e. input hashes seen >1 time)
Total number of duplicate jobs (input hash matches an in-flight job, processed when in-flight job completes)
Total number of DDC queries in the job cache (per-shader DDC).
Total number of DDC hits in the job cache (per shader DDC, as opposed to shader map DDC stats above).
Total number of unique input hashes seen in job cache queries
Total number of unique job outputs stored in the cache. Outputs are deduplicated based on a content hash so this number is in practice smaller than UniqueCacheInputHashes.
Total amount of memory currently used by the job cache
Memory budget allocated for the job cache
Maximum number of remote agents used during compilation.
Maximum number of CPU cores active across all remote agents.
The total number of materials cooked. This corresponds to UMaterialInterface::Presave()
The total number of materials that have been translated.
The total time in seconds to translate all materials.
The total time spent actually translating materials (rather than for instance accessing the DDC cache).
The total time spent serializing DDC results.
The total number times a material translation was skipped because the the results were in the DDC.
Definition at line 405 of file ShaderCompiler.h.
References GENERATED_BODY, FMath::Max, FMath::Min, operator+=(), Other, and UPROPERTY.
VerifyGlobalShaders() [1/2]
void VerifyGlobalShaders (EShaderPlatform Platform, bool bLoadedFromCacheFile, const TArray< const FShaderType * > * OutdatedShaderTypes = nullptr, const TArray< const FShaderPipelineType * > * OutdatedShaderPipelineTypes = nullptr) extern
Makes sure all global shaders are loaded and/or compiled for the passed in platform.
Note: if compilation is needed, this only kicks off the compile.
Parameters
Platform Platform to verify global shaders for
bLoadedFromCacheFile Load the shaders from cache, will error out and not compile shaders if missing
OutdatedShaderTypes Optional list of shader types, will trigger compilation job for shader types found in this list even if the map already has the shader.
OutdatedShaderPipelineTypes Optional list of shader pipeline types, will trigger compilation job for shader pipeline types found in this list even if the map already has the pipeline.
References Platform.
VerifyGlobalShaders() [2/2]
void VerifyGlobalShaders (EShaderPlatform Platform, const ITargetPlatform * TargetPlatform, bool bLoadedFromCacheFile, const TArray< const FShaderType * > * OutdatedShaderTypes = nullptr, const TArray< const FShaderPipelineType * > * OutdatedShaderPipelineTypes = nullptr, const FShaderCompilerFlags & InExtraCompilerFlags = {}) extern
References Platform.
Variable Documentation
GShaderCompilerStats
FShaderCompilerStats* GShaderCompilerStats extern
The global shader compiling stats.
GShaderCompilingManager
FShaderCompilingManager* GShaderCompilingManager extern
The global shader compiling thread manager.