Unreal Engine 5.6 C++ API: Runtime/RenderCore/Public/ShaderCore.h File Reference
ShaderCore.h File Reference
#include "Compression/OodleDataCompression.h"
#include "Compression/CompressedBuffer.h"
#include "Containers/Array.h"
#include "Containers/ArrayView.h"
#include "Containers/ContainerAllocationPolicies.h"
#include "Containers/Map.h"
#include "Containers/SortedMap.h"
#include "Containers/UnrealString.h"
#include "CoreMinimal.h"
#include "HAL/Platform.h"
#include "HAL/UnrealMemory.h"
#include "Logging/LogMacros.h"
#include "Memory/CompositeBuffer.h"
#include "Memory/SharedBuffer.h"
#include "Misc/AssertionMacros.h"
#include "Misc/CString.h"
#include "Misc/CoreStats.h"
#include "Misc/EnumClassFlags.h"
#include "Misc/Optional.h"
#include "Misc/Paths.h"
#include "Misc/SecureHash.h"
#include "Misc/TVariant.h"
#include "PixelFormat.h"
#include "RHIDefinitions.h"
#include "RHIShaderBindingLayout.h"
#include "Serialization/Archive.h"
#include "Serialization/MemoryLayout.h"
#include "ShaderParameterMetadata.h"
#include "Stats/Stats.h"
#include "Templates/Function.h"
#include "Templates/PimplPtr.h"
#include "Templates/RefCounting.h"
#include "Templates/SharedPointer.h"
#include "Templates/UnrealTemplate.h"
#include "UObject/NameTypes.h"
#include "UObject/UnrealNames.h"
#include "UniformBuffer.h"
Data Structures
struct FGenericShaderStat
struct FParameterAllocation
class FShaderBindingLayout
RenderCore wrapper around FRHIShaderBindingLayout which can also cache the uniform buffer declarations used during shader code generation.
class FShaderBindingLayoutContainer
Static shader binding layout object managing all possible binding type versions of the FShaderBindingLayout.
class FShaderCode
struct FShaderCodeFeatures
struct FShaderCodeName
class FShaderCodeReader
class FShaderCodeResource
struct FShaderCodeResource::FHeader
struct FShaderCodeResourceMasks
struct FShaderCodeShaderResourceTableDataDesc
struct FShaderCodeUniformBuffers
struct FShaderCodeValidationExtension
struct FShaderCodeVendorExtension
class FShaderCompilerDefineNameCache
struct FShaderCompilerEnvironment
The environment used to compile a shader.
class FShaderCompilerFlags
struct FShaderDiagnosticData
struct FShaderDiagnosticExtension
class FShaderParameterMap
A map of shader parameter names to registers allocated to that parameter.
struct FShaderResourceTableMap
struct FShaderTarget
struct FSharedShaderCompilerEnvironment
struct FUniformBufferNameSortOrder
Namespaces
namespace FShaderStatTagNames
Macros
#define HLSL_LINE_TERMINATOR TEXT("\n")
#define RENDERCORE_ATTRIBUTE_UNALIGNED
#define SET_SHADER_DEFINE(ENVIRONMENT, NAME, VALUE)
Optimized define setting macros that cache the FName lookup, and potentially the map index.
#define SET_SHADER_DEFINE_AND_COMPILE_ARGUMENT(ENVIRONMENT, NAME, VALUE)
Typedefs
using FShaderStatVariant = TVariant<bool, float, int32, uint32, FString>
using FThreadSafeNameBufferPtr = TSharedPtr<TArray<TCHAR>, ESPMode::ThreadSafe>
using FThreadSafeSharedStringPtr = TSharedPtr<FString, ESPMode::ThreadSafe>
typedef int32 unaligned_int32
typedef uint32 unaligned_uint32
Enumerations
enum class EShaderCodeFeatures : uint16 {
None = 0 , WaveOps = 1 << 0 , SixteenBitTypes = 1 << 1 , TypedUAVLoadsExtended = 1 << 2 ,
Atomic64 = 1 << 3 , UE_DEPRECATED =(5.5, "EShaderCodeFeatures::DiagnosticBuffer is superseded by EShaderResourceUsageFlags::DiagnosticBuffer") = 1 << 4 , BindlessResources = 1 << 5 , BindlessSamplers = 1 << 6 ,
StencilRef = 1 << 7 , BarycentricsSemantic = 1 << 8
}
enum class EShaderCompileJobPriority : uint8 {
None = 0xff , Low = 0u , Normal , High ,
ExtraHigh , ForceLocal , Num
}
enum class EShaderOptionalDataKey : uint8 {
AttributeInputs = uint8('i') , AttributeOutputs = uint8('o') , CompressedDebugCode = uint8('z') , Diagnostic = uint8('D') ,
Features = uint8('x') , Name = uint8('n') , NativePath = uint8('P') , ObjectFile = uint8('O') ,
PackedResourceCounts = uint8('p') , ResourceMasks = uint8('m') , ShaderModel6 = uint8('6') , SourceCode = uint8('c') ,
UncompressedSize = uint8('U') , UniformBuffers = uint8('u') , Validation = uint8('V') , VendorExtension = uint8('v') ,
ShaderBindingLayout = uint8('s') , EntryPoint = uint8('e')
}
enum class EShaderParameterType : uint8 {
LooseData , UniformBuffer , Sampler , SRV ,
UAV , BindlessSampler , BindlessSRV , BindlessUAV ,
Num
}
enum class EShaderParameterTypeMask : uint16 {
LooseDataMask = 1 << uint16(EShaderParameterType::LooseData) , UniformBufferMask = 1 << uint16(EShaderParameterType::UniformBuffer) , SamplerMask = 1 << uint16(EShaderParameterType::Sampler) , SRVMask = 1 << uint16(EShaderParameterType::SRV) ,
UAVMask = 1 << uint16(EShaderParameterType::UAV) , BindlessSamplerMask = 1 << uint16(EShaderParameterType::BindlessSampler) , BindlessSRVMask = 1 << uint16(EShaderParameterType::BindlessSRV) , BindlessUAVMask = 1 << uint16(EShaderParameterType::BindlessUAV)
}
enum class EShaderResourceUsageFlags : uint8 {
GlobalUniformBuffer = 1 << 0 , BindlessResources = 1 << 1 , BindlessSamplers = 1 << 2 , RootConstants = 1 << 3 ,
NoDerivativeOps = 1 << 4 , ShaderBundle = 1 << 5 , DiagnosticBuffer = 1 << 6
}
Functions
RENDERCORE_API void AddShaderSourceDirectoryMapping (const FString &VirtualShaderDirectory, const FString &RealShaderDirectory)
Maps a real shader directory existing on disk to a virtual shader directory.
RENDERCORE_API void AddShaderSourceFileEntry (TArray< FString > &OutVirtualFilePaths, FString VirtualFilePath, EShaderPlatform ShaderPlatform, const FName *ShaderPlatformName=nullptr)
RENDERCORE_API void AddShaderSourceSharedVirtualDirectory (const FString &VirtualShaderDirectory)
Specifies that the virtual shader directory and all subdirectories should contain only .h files that are shared between C++ / shader.
RENDERCORE_API bool AllowDebugViewmodes ()
Returns true if debug viewmodes are allowed for the current platform.
RENDERCORE_API bool AllowDebugViewmodes (EShaderPlatform Platform)
Returns true if debug viewmodes are allowed for the given platform.
RENDERCORE_API const TMap< FString, FString > & AllShaderSourceDirectoryMappings ()
Returns the map virtual shader directory path -> real shader directory path.
RENDERCORE_API void AppendKeyStringShaderDependencies (TConstArrayView< FShaderTypeDependency > ShaderTypeDependencies, FPlatformTypeLayoutParameters LayoutParams, FString &OutKeyString, bool bIncludeSourceHashes=true)
Appends information to a KeyString for a given shader to reflect its dependencies.
RENDERCORE_API void AppendKeyStringShaderDependencies (TConstArrayView< FShaderTypeDependency > ShaderTypeDependencies, TConstArrayView< FShaderPipelineTypeDependency > ShaderPipelineTypeDependencies, TConstArrayView< FVertexFactoryTypeDependency > VertexFactoryTypeDependencies, FPlatformTypeLayoutParameters LayoutParams, FString &OutKeyString, bool bIncludeSourceHashes=true)
RENDERCORE_API void AppendShaderDependencies (FShaderKeyGenerator &KeyGen, TConstArrayView< FShaderTypeDependency > ShaderTypeDependencies, TConstArrayView< FShaderPipelineTypeDependency > ShaderPipelineTypeDependencies, TConstArrayView< FVertexFactoryTypeDependency > VertexFactoryTypeDependencies, FPlatformTypeLayoutParameters LayoutParams, bool bIncludeSourceHashes=true)
RENDERCORE_API void CheckShaderHashCacheInclude (const FString &VirtualFilePath, EShaderPlatform ShaderPlatform, const FString &ShaderFormatName)
Checks if shader include isn't skipped by a shader hash cache.
CSV_DECLARE_CATEGORY_MODULE_EXTERN (RENDERCORE_API, Shaders)
DECLARE_CYCLE_STAT_EXTERN (TEXT("RT Shader Load Time"), STAT_Shaders_RTShaderLoadTime, STATGROUP_Shaders, RENDERCORE_API)
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN (TEXT("Num Lit Material Shaders"), STAT_ShaderCompiling_NumLitMaterialShaders, STATGROUP_ShaderCompiling, RENDERCORE_API)
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN (TEXT("Num Masked Material Shaders"), STAT_ShaderCompiling_NumMaskedMaterialShaders, STATGROUP_ShaderCompiling, RENDERCORE_API)
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN (TEXT("Num Opaque Material Shaders"), STAT_ShaderCompiling_NumOpaqueMaterialShaders, STATGROUP_ShaderCompiling, RENDERCORE_API)
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN (TEXT("Num Particle Material Shaders"), STAT_ShaderCompiling_NumParticleMaterialShaders, STATGROUP_ShaderCompiling, RENDERCORE_API)
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN (TEXT("Num ShaderMaps Loaded"), STAT_Shaders_NumShaderMaps, STATGROUP_Shaders, RENDERCORE_API)
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN (TEXT("Num ShaderMaps Used"), STAT_Shaders_NumShaderMapsUsedForRendering, STATGROUP_Shaders, RENDERCORE_API)
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN (TEXT("Num Shaders Created"), STAT_Shaders_NumShadersCreated, STATGROUP_Shaders, RENDERCORE_API)
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN (TEXT("Num Shaders Loaded"), STAT_Shaders_NumShadersLoaded, STATGROUP_Shaders, RENDERCORE_API)
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN (TEXT("Num Skinned Material Shaders"), STAT_ShaderCompiling_NumSkinnedMaterialShaders, STATGROUP_ShaderCompiling, RENDERCORE_API)
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN (TEXT("Num Special Material Shaders"), STAT_ShaderCompiling_NumSpecialMaterialShaders, STATGROUP_ShaderCompiling, RENDERCORE_API)
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN (TEXT("Num Total Material Shaders"), STAT_ShaderCompiling_NumTotalMaterialShaders, STATGROUP_ShaderCompiling, RENDERCORE_API)
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN (TEXT("Num Total Niagara Shaders"), STAT_ShaderCompiling_NumTotalNiagaraShaders, STATGROUP_ShaderCompiling, RENDERCORE_API)
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN (TEXT("Num Total OpenColorIO Shaders"), STAT_ShaderCompiling_NumTotalOpenColorIOShaders, STATGROUP_ShaderCompiling, RENDERCORE_API)
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN (TEXT("Num Transparent Material Shaders"), STAT_ShaderCompiling_NumTransparentMaterialShaders, STATGROUP_ShaderCompiling, RENDERCORE_API)
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN (TEXT("Num Unlit Material Shaders"), STAT_ShaderCompiling_NumUnlitMaterialShaders, STATGROUP_ShaderCompiling, RENDERCORE_API)
DECLARE_FLOAT_ACCUMULATOR_STAT_EXTERN (TEXT("CRCing Shader Files"), STAT_ShaderCompiling_HashingShaderFiles, STATGROUP_ShaderCompiling, RENDERCORE_API)
DECLARE_FLOAT_ACCUMULATOR_STAT_EXTERN (TEXT("DDC Loading"), STAT_ShaderCompiling_DDCLoading, STATGROUP_ShaderCompiling, RENDERCORE_API)
DECLARE_FLOAT_ACCUMULATOR_STAT_EXTERN (TEXT("HLSL Translation"), STAT_ShaderCompiling_HLSLTranslation, STATGROUP_ShaderCompiling, RENDERCORE_API)
DECLARE_FLOAT_ACCUMULATOR_STAT_EXTERN (TEXT("Loading Shader Files"), STAT_ShaderCompiling_LoadingShaderFiles, STATGROUP_ShaderCompiling, RENDERCORE_API)
DECLARE_FLOAT_ACCUMULATOR_STAT_EXTERN (TEXT("Material Compiling"), STAT_ShaderCompiling_MaterialCompiling, STATGROUP_ShaderCompiling, RENDERCORE_API)
DECLARE_FLOAT_ACCUMULATOR_STAT_EXTERN (TEXT("Material Loading"), STAT_ShaderCompiling_MaterialLoading, STATGROUP_ShaderCompiling, RENDERCORE_API)
DECLARE_FLOAT_ACCUMULATOR_STAT_EXTERN (TEXT("RHI Compile Time"), STAT_ShaderCompiling_RHI, STATGROUP_ShaderCompiling, RENDERCORE_API)
DECLARE_FLOAT_ACCUMULATOR_STAT_EXTERN (TEXT("Total Global Shader Compiling Time"), STAT_ShaderCompiling_GlobalShaders, STATGROUP_ShaderCompiling, RENDERCORE_API)
DECLARE_FLOAT_ACCUMULATOR_STAT_EXTERN (TEXT("Total Material Shader Compiling Time"), STAT_ShaderCompiling_MaterialShaders, STATGROUP_ShaderCompiling, RENDERCORE_API)
DECLARE_FLOAT_ACCUMULATOR_STAT_EXTERN (TEXT("Total Niagara Shader Compiling Time"), STAT_ShaderCompiling_NiagaraShaders, STATGROUP_ShaderCompiling, RENDERCORE_API)
DECLARE_FLOAT_ACCUMULATOR_STAT_EXTERN (TEXT("Total OpenColorIO Shader Compiling Time"), STAT_ShaderCompiling_OpenColorIOShaders, STATGROUP_ShaderCompiling, RENDERCORE_API)
DECLARE_INTRINSIC_TYPE_LAYOUT (FShaderTarget)
RENDERCORE_API DECLARE_LOG_CATEGORY_EXTERN (LogShaders, Error, All)
Controls whether shader related logs are visible.
DECLARE_MEMORY_STAT_EXTERN (TEXT("Shader Memory"), STAT_Shaders_ShaderMemory, STATGROUP_Shaders, RENDERCORE_API)
DECLARE_MEMORY_STAT_EXTERN (TEXT("Shader Preload Mem"), STAT_Shaders_ShaderPreloadMemory, STATGROUP_Shaders, RENDERCORE_API)
DECLARE_MEMORY_STAT_EXTERN (TEXT("Shader Resource Mem"), STAT_Shaders_ShaderResourceMemory, STATGROUP_Shaders, RENDERCORE_API)
ENUM_CLASS_FLAGS (EShaderCodeFeatures)
ENUM_CLASS_FLAGS (EShaderParameterTypeMask)
ENUM_CLASS_FLAGS (EShaderResourceUsageFlags) struct FShaderCodePackedResourceCounts
RENDERCORE_API void FlushShaderFileCache ()
Flushes the shader file and CRC cache, and regenerates the binary shader files if necessary.
void GenerateReferencedUniformBuffers (const TCHAR *SourceFilename, const TCHAR *ShaderTypeName, const TMap< FString, TArray< const TCHAR * > > &ShaderFileToUniformBufferVariables, TSet< const FShaderParametersMetadata * > &UniformBuffers)
Parses the given source file and its includes for references of uniform buffers.
RENDERCORE_API void GetAllVirtualShaderSourcePaths (TArray< FString > &OutVirtualFilePaths, EShaderPlatform ShaderPlatform, const FName *ShaderPlatformName=nullptr)
TStatId GetMemoryStatType (EShaderFrequency ShaderFrequency)
RENDERCORE_API FName GetShaderCompressionFormat ()
Returns the shader compression format.
RENDERCORE_API void GetShaderCompressionOodleSettings (FOodleDataCompression::ECompressor &OutCompressor, FOodleDataCompression::ECompressionLevel &OutLevel, const FName &ShaderFormat=NAME_None)
Returns Oodle-specific shader compression format settings (passing ShaderFormat for future proofing, but as of now the setting is global for all formats).
RENDERCORE_API const class FSHAHash & GetShaderFileHash (const TCHAR *VirtualFilePath, EShaderPlatform ShaderPlatform)
Calculates a Hash for the given filename if it does not already exist in the Hash cache.
RENDERCORE_API const class FSHAHash & GetShaderFilesHash (const TArray< FString > &VirtualFilePaths, EShaderPlatform ShaderPlatform)
Calculates a Hash for the list of filenames if it does not already exist in the Hash cache.
RENDERCORE_API void GetShaderIncludes (const TCHAR *EntryPointVirtualFilePath, const TCHAR *VirtualFilePath, const FString &FileContents, TArray< FString > &IncludeVirtualFilePaths, EShaderPlatform ShaderPlatform, uint32 DepthLimit=100, const FName *ShaderPlatformName=nullptr)
RENDERCORE_API void GetShaderIncludes (const TCHAR *EntryPointVirtualFilePath, const TCHAR *VirtualFilePath, TArray< FString > &IncludeVirtualFilePaths, EShaderPlatform ShaderPlatform, uint32 DepthLimit=100, const FName *ShaderPlatformName=nullptr)
Recursively populates IncludeFilenames with the include filenames from Filename.
RENDERCORE_API FString GetShaderSourceFilePath (const FString &VirtualFilePath, TArray< struct FShaderCompilerError > *CompileErrors=nullptr)
Convert the virtual shader path to an actual file system path.
RENDERCORE_API FSHAHash GetShaderTypeLayoutHash (const FTypeLayoutDesc &TypeDesc, FPlatformTypeLayoutParameters LayoutParameters)
Return the hash of the given type layout for a partical platform type layout.
RENDERCORE_API void InitializeShaderHashCache ()
Initializes shader hash cache from IShaderFormatModules.
RENDERCORE_API void InitializeShaderTypes ()
Initializes cached shader type data.
RENDERCORE_API void InvalidateShaderFileCacheEntry (const TCHAR *InVirtualFilePath, EShaderPlatform InShaderPlatform, const FName *InShaderPlatformName=nullptr)
Invalidates a single entry in the shader file and CRC caches.
bool IsParameterBindless (EShaderParameterType ParameterType)
RENDERCORE_API void LoadShaderSourceFileChecked (const TCHAR *VirtualFilePath, EShaderPlatform ShaderPlatform, FString &OutFileContents, const FName *ShaderPlatformName=nullptr)
Loads the shader file with the given name.
FString RENDERCORE_API MakeInjectedShaderCodeBlock (const TCHAR *BlockName, const FString &CodeToInject)
Create a block of source code to be injected in the preprocessed shader code.
FArchive & operator<< (FArchive &Ar, FShaderCodeValidationStride &ShaderCodeValidationStride)
FArchive & operator<< (FArchive &Ar, FShaderCodeValidationType &ShaderCodeValidationType)
FArchive & operator<< (FArchive &Ar, FShaderCodeValidationUBSize &ShaderCodeValidationSize)
FArchive & operator<< (FArchive &Ar, FShaderDiagnosticData &ShaderCodeDiagnosticData)
RENDERCORE_API FArchive & operator<< (FArchive &Ar, FSharedBuffer &Buffer)
FArchive & operator<< (FArchive &Ar, FUniformBufferEntry &Entry)
FArchive & operator<< (FArchive &Ar, FUniformResourceEntry &Entry)
bool operator== (const FShaderStatVariant LHS, const FShaderStatVariant RHS)
RENDERCORE_API FString ParseVirtualShaderFilename (const FString &InFilename)
Converts an absolute or relative shader filename to a filename relative to the shader directory.
RENDERCORE_API bool ReplaceVirtualFilePathForShaderAutogen (FString &InOutVirtualFilePath, EShaderPlatform ShaderPlatform, const FName *InShaderPlatformName=nullptr)
Replaces virtual platform path with appropriate autogen path for a given ShaderPlatform.
RENDERCORE_API bool ReplaceVirtualFilePathForShaderPlatform (FString &InOutVirtualFilePath, EShaderPlatform ShaderPlatform)
Replaces virtual platform path with appropriate path for a given ShaderPlatform.
RENDERCORE_API void ResetAllShaderSourceDirectoryMappings ()
Hook for shader compile worker to reset the directory mappings.
const TCHAR * ShaderCompileJobPriorityToString (EShaderCompileJobPriority InPriority)
RENDERCORE_API const FSHAHash * TryGetShaderFileHash (const TCHAR *VirtualFilePath, EShaderPlatform ShaderPlatform, FString *OutErrorMessage=nullptr)
Calculates a Hash for the given filename if it does not already exist in the Hash cache.
UE_DEPRECATED (5.5, "HashShaderFileWithIncludes is no longer used by the shader compilation system and so no longer supported.") extern RENDERCORE_API void HashShaderFileWithIncludes(FArchive &HashingArchive
RENDERCORE_API void UpdateIncludeDirectoryForPreviewPlatform (EShaderPlatform PreviewPlatform, EShaderPlatform ActualPlatform)
Updates the PreviewPlatform's IncludeDirectory to match that of the Parent Platform.
RENDERCORE_API void UpdateReferencedUniformBufferNames (TArrayView< const FShaderType * > OutdatedShaderTypes, TArrayView< const FVertexFactoryType * > OutdatedFactoryTypes, TArrayView< const FShaderPipelineType * > OutdatedShaderPipelineTypes)
Force updates each shader/pipeline type provided to update their list of referenced uniform buffers.
RENDERCORE_API void VerifyShaderSourceFiles (EShaderPlatform ShaderPlatform)
Variables
RENDERCORE_API const FName FShaderStatTagNames::AnalysisArtifactsName
Tag name for shader analysis artifacts.
const TCHAR const FString EShaderPlatform bool bOnlyHashIncludedFiles
const TCHAR const FString & FileContents
constexpr int32 NumShaderCompileJobPriorities = (int32)EShaderCompileJobPriority::Num
const TCHAR const FString EShaderPlatform ShaderPlatform
const TCHAR * VirtualFilePath
Macro Definition Documentation
HLSL_LINE_TERMINATOR
#define HLSL_LINE_TERMINATOR TEXT("\n")
Definition at line 1575 of file ShaderCore.h.
RENDERCORE_ATTRIBUTE_UNALIGNED
#define RENDERCORE_ATTRIBUTE_UNALIGNED
Definition at line 973 of file ShaderCore.h.
SET_SHADER_DEFINE
#define SET_SHADER_DEFINE (ENVIRONMENT, NAME, VALUE)
Value:
    do {                                                                    \
        static FShaderCompilerDefineNameCache Cache_##NAME(TEXT(#NAME));  \
        (ENVIRONMENT).SetDefine(Cache_##NAME, VALUE);                       \
    } while(0)
Optimized define setting macros that cache the FName lookup, and potentially the map index.
Definition at line 724 of file ShaderCore.h.
SET_SHADER_DEFINE_AND_COMPILE_ARGUMENT
#define SET_SHADER_DEFINE_AND_COMPILE_ARGUMENT (ENVIRONMENT, NAME, VALUE)
Value:
    do {                                                                    \
        static FShaderCompilerDefineNameCache Cache_##NAME(TEXT(#NAME));  \
        (ENVIRONMENT).SetDefine(Cache_##NAME, VALUE);                       \
        (ENVIRONMENT).SetCompileArgument(TEXT(#NAME), VALUE);               \
    } while(0)
Definition at line 730 of file ShaderCore.h.
Typedef Documentation
FShaderStatVariant
using FShaderStatVariant = TVariant<bool, float, int32, uint32, FString>
Definition at line 58 of file ShaderCore.h.
FThreadSafeNameBufferPtr
using FThreadSafeNameBufferPtr = TSharedPtr<TArray<TCHAR>, ESPMode::ThreadSafe>
Definition at line 395 of file ShaderCore.h.
FThreadSafeSharedStringPtr
using FThreadSafeSharedStringPtr = TSharedPtr<FString, ESPMode::ThreadSafe>
Definition at line 394 of file ShaderCore.h.
unaligned_int32
typedef int32 unaligned_int32
Definition at line 975 of file ShaderCore.h.
unaligned_uint32
typedef uint32 unaligned_uint32
Definition at line 976 of file ShaderCore.h.
Enumeration Type Documentation
EShaderCodeFeatures
enum class EShaderCodeFeatures : uint16 strong
Enumerator
None
WaveOps
SixteenBitTypes
TypedUAVLoadsExtended
Atomic64
UE_DEPRECATED
BindlessResources
BindlessSamplers
StencilRef
BarycentricsSemantic
Definition at line 828 of file ShaderCore.h.
EShaderCompileJobPriority
enum class EShaderCompileJobPriority : uint8 strong
Enumerator
None
Low
Normal
High
ExtraHigh
ForceLocal
Num
Definition at line 799 of file ShaderCore.h.
EShaderOptionalDataKey
enum class EShaderOptionalDataKey : uint8 strong
Enumerator
AttributeInputs
AttributeOutputs
CompressedDebugCode
Diagnostic
Features
Name
NativePath
ObjectFile
PackedResourceCounts
ResourceMasks
ShaderModel6
SourceCode
UncompressedSize
UniformBuffers
Validation
VendorExtension
ShaderBindingLayout
EntryPoint
Definition at line 743 of file ShaderCore.h.
EShaderParameterType
enum class EShaderParameterType : uint8 strong
Enumerator
LooseData
UniformBuffer
Sampler
SRV
UAV
BindlessSampler
BindlessSRV
BindlessUAV
Num
Definition at line 244 of file ShaderCore.h.
EShaderParameterTypeMask
enum class EShaderParameterTypeMask : uint16 strong
Enumerator
LooseDataMask
UniformBufferMask
SamplerMask
SRVMask
UAVMask
BindlessSamplerMask
BindlessSRVMask
BindlessUAVMask
Definition at line 259 of file ShaderCore.h.
EShaderResourceUsageFlags
enum class EShaderResourceUsageFlags : uint8 strong
Enumerator
GlobalUniformBuffer
BindlessResources
BindlessSamplers
RootConstants
NoDerivativeOps
ShaderBundle
DiagnosticBuffer
Definition at line 765 of file ShaderCore.h.
Function Documentation
AddShaderSourceDirectoryMapping()
RENDERCORE_API void AddShaderSourceDirectoryMapping (const FString & VirtualShaderDirectory, const FString & RealShaderDirectory) extern
Maps a real shader directory existing on disk to a virtual shader directory.
Parameters
VirtualShaderDirectory Unique absolute path of the virtual shader directory (ex: /Project).
RealShaderDirectory FPlatformProcess::BaseDir() relative path of the directory map.
AddShaderSourceFileEntry()
RENDERCORE_API void AddShaderSourceFileEntry (TArray< FString > & OutVirtualFilePaths, FString VirtualFilePath, EShaderPlatform ShaderPlatform, const FName * ShaderPlatformName = nullptr) extern
References ShaderPlatform, and VirtualFilePath.
AddShaderSourceSharedVirtualDirectory()
RENDERCORE_API void AddShaderSourceSharedVirtualDirectory (const FString & VirtualShaderDirectory) extern
Specifies that the virtual shader directory and all subdirectories should contain only .h files that are shared between C++ / shader.
Parameters
VirtualShaderDirectory Unique absolute path of the virtual shader directory (ex: /Project/Shared/).
AllowDebugViewmodes() [1/2]
RENDERCORE_API bool AllowDebugViewmodes () extern
Returns true if debug viewmodes are allowed for the current platform.
AllowDebugViewmodes() [2/2]
RENDERCORE_API bool AllowDebugViewmodes (EShaderPlatform Platform) extern
Returns true if debug viewmodes are allowed for the given platform.
References Platform.
AllShaderSourceDirectoryMappings()
RENDERCORE_API const TMap< FString, FString > & AllShaderSourceDirectoryMappings () extern
Returns the map virtual shader directory path -> real shader directory path.
AppendKeyStringShaderDependencies() [1/2]
RENDERCORE_API void AppendKeyStringShaderDependencies (TConstArrayView< FShaderTypeDependency > ShaderTypeDependencies, FPlatformTypeLayoutParameters LayoutParams, FString & OutKeyString, bool bIncludeSourceHashes = true) extern
Appends information to a KeyString for a given shader to reflect its dependencies.
AppendKeyStringShaderDependencies() [2/2]
RENDERCORE_API void AppendKeyStringShaderDependencies (TConstArrayView< FShaderTypeDependency > ShaderTypeDependencies, TConstArrayView< FShaderPipelineTypeDependency > ShaderPipelineTypeDependencies, TConstArrayView< FVertexFactoryTypeDependency > VertexFactoryTypeDependencies, FPlatformTypeLayoutParameters LayoutParams, FString & OutKeyString, bool bIncludeSourceHashes = true) extern
AppendShaderDependencies()
RENDERCORE_API void AppendShaderDependencies (FShaderKeyGenerator & KeyGen, TConstArrayView< FShaderTypeDependency > ShaderTypeDependencies, TConstArrayView< FShaderPipelineTypeDependency > ShaderPipelineTypeDependencies, TConstArrayView< FVertexFactoryTypeDependency > VertexFactoryTypeDependencies, FPlatformTypeLayoutParameters LayoutParams, bool bIncludeSourceHashes = true) extern
CheckShaderHashCacheInclude()
RENDERCORE_API void CheckShaderHashCacheInclude (const FString & VirtualFilePath, EShaderPlatform ShaderPlatform, const FString & ShaderFormatName) extern
Checks if shader include isn't skipped by a shader hash cache.
References ShaderPlatform, and VirtualFilePath.
CSV_DECLARE_CATEGORY_MODULE_EXTERN()
CSV_DECLARE_CATEGORY_MODULE_EXTERN (RENDERCORE_API , Shaders)
References All, and Log.
DECLARE_CYCLE_STAT_EXTERN()
DECLARE_CYCLE_STAT_EXTERN (TEXT("RT Shader Load Time") , STAT_Shaders_RTShaderLoadTime , STATGROUP_Shaders , RENDERCORE_API)
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN() [1/15]
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN (TEXT("Num Lit Material Shaders") , STAT_ShaderCompiling_NumLitMaterialShaders , STATGROUP_ShaderCompiling , RENDERCORE_API)
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN() [2/15]
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN (TEXT("Num Masked Material Shaders") , STAT_ShaderCompiling_NumMaskedMaterialShaders , STATGROUP_ShaderCompiling , RENDERCORE_API)
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN() [3/15]
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN (TEXT("Num Opaque Material Shaders") , STAT_ShaderCompiling_NumOpaqueMaterialShaders , STATGROUP_ShaderCompiling , RENDERCORE_API)
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN() [4/15]
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN (TEXT("Num Particle Material Shaders") , STAT_ShaderCompiling_NumParticleMaterialShaders , STATGROUP_ShaderCompiling , RENDERCORE_API)
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN() [5/15]
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN (TEXT("Num ShaderMaps Loaded") , STAT_Shaders_NumShaderMaps , STATGROUP_Shaders , RENDERCORE_API)
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN() [6/15]
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN (TEXT("Num ShaderMaps Used") , STAT_Shaders_NumShaderMapsUsedForRendering , STATGROUP_Shaders , RENDERCORE_API)
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN() [7/15]
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN (TEXT("Num Shaders Created") , STAT_Shaders_NumShadersCreated , STATGROUP_Shaders , RENDERCORE_API)
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN() [8/15]
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN (TEXT("Num Shaders Loaded") , STAT_Shaders_NumShadersLoaded , STATGROUP_Shaders , RENDERCORE_API)
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN() [9/15]
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN (TEXT("Num Skinned Material Shaders") , STAT_ShaderCompiling_NumSkinnedMaterialShaders , STATGROUP_ShaderCompiling , RENDERCORE_API)
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN() [10/15]
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN (TEXT("Num Special Material Shaders") , STAT_ShaderCompiling_NumSpecialMaterialShaders , STATGROUP_ShaderCompiling , RENDERCORE_API)
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN() [11/15]
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN (TEXT("Num Total Material Shaders") , STAT_ShaderCompiling_NumTotalMaterialShaders , STATGROUP_ShaderCompiling , RENDERCORE_API)
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN() [12/15]
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN (TEXT("Num Total Niagara Shaders") , STAT_ShaderCompiling_NumTotalNiagaraShaders , STATGROUP_ShaderCompiling , RENDERCORE_API)
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN() [13/15]
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN (TEXT("Num Total OpenColorIO Shaders") , STAT_ShaderCompiling_NumTotalOpenColorIOShaders , STATGROUP_ShaderCompiling , RENDERCORE_API)
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN() [14/15]
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN (TEXT("Num Transparent Material Shaders") , STAT_ShaderCompiling_NumTransparentMaterialShaders , STATGROUP_ShaderCompiling , RENDERCORE_API)
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN() [15/15]
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN (TEXT("Num Unlit Material Shaders") , STAT_ShaderCompiling_NumUnlitMaterialShaders , STATGROUP_ShaderCompiling , RENDERCORE_API)
DECLARE_FLOAT_ACCUMULATOR_STAT_EXTERN() [1/11]
DECLARE_FLOAT_ACCUMULATOR_STAT_EXTERN (TEXT("CRCing Shader Files") , STAT_ShaderCompiling_HashingShaderFiles , STATGROUP_ShaderCompiling , RENDERCORE_API)
DECLARE_FLOAT_ACCUMULATOR_STAT_EXTERN() [2/11]
DECLARE_FLOAT_ACCUMULATOR_STAT_EXTERN (TEXT("DDC Loading") , STAT_ShaderCompiling_DDCLoading , STATGROUP_ShaderCompiling , RENDERCORE_API)
DECLARE_FLOAT_ACCUMULATOR_STAT_EXTERN() [3/11]
DECLARE_FLOAT_ACCUMULATOR_STAT_EXTERN (TEXT("HLSL Translation") , STAT_ShaderCompiling_HLSLTranslation , STATGROUP_ShaderCompiling , RENDERCORE_API)
DECLARE_FLOAT_ACCUMULATOR_STAT_EXTERN() [4/11]
DECLARE_FLOAT_ACCUMULATOR_STAT_EXTERN (TEXT("Loading Shader Files") , STAT_ShaderCompiling_LoadingShaderFiles , STATGROUP_ShaderCompiling , RENDERCORE_API)
DECLARE_FLOAT_ACCUMULATOR_STAT_EXTERN() [5/11]
DECLARE_FLOAT_ACCUMULATOR_STAT_EXTERN (TEXT("Material Compiling") , STAT_ShaderCompiling_MaterialCompiling , STATGROUP_ShaderCompiling , RENDERCORE_API)
DECLARE_FLOAT_ACCUMULATOR_STAT_EXTERN() [6/11]
DECLARE_FLOAT_ACCUMULATOR_STAT_EXTERN (TEXT("Material Loading") , STAT_ShaderCompiling_MaterialLoading , STATGROUP_ShaderCompiling , RENDERCORE_API)
DECLARE_FLOAT_ACCUMULATOR_STAT_EXTERN() [7/11]
DECLARE_FLOAT_ACCUMULATOR_STAT_EXTERN (TEXT("RHI Compile Time") , STAT_ShaderCompiling_RHI , STATGROUP_ShaderCompiling , RENDERCORE_API)
DECLARE_FLOAT_ACCUMULATOR_STAT_EXTERN() [8/11]
DECLARE_FLOAT_ACCUMULATOR_STAT_EXTERN (TEXT("Total Global Shader Compiling Time") , STAT_ShaderCompiling_GlobalShaders , STATGROUP_ShaderCompiling , RENDERCORE_API)
DECLARE_FLOAT_ACCUMULATOR_STAT_EXTERN() [9/11]
DECLARE_FLOAT_ACCUMULATOR_STAT_EXTERN (TEXT("Total Material Shader Compiling Time") , STAT_ShaderCompiling_MaterialShaders , STATGROUP_ShaderCompiling , RENDERCORE_API)
DECLARE_FLOAT_ACCUMULATOR_STAT_EXTERN() [10/11]
DECLARE_FLOAT_ACCUMULATOR_STAT_EXTERN (TEXT("Total Niagara Shader Compiling Time") , STAT_ShaderCompiling_NiagaraShaders , STATGROUP_ShaderCompiling , RENDERCORE_API)
DECLARE_FLOAT_ACCUMULATOR_STAT_EXTERN() [11/11]
DECLARE_FLOAT_ACCUMULATOR_STAT_EXTERN (TEXT("Total OpenColorIO Shader Compiling Time") , STAT_ShaderCompiling_OpenColorIOShaders , STATGROUP_ShaderCompiling , RENDERCORE_API)
DECLARE_INTRINSIC_TYPE_LAYOUT()
DECLARE_INTRINSIC_TYPE_LAYOUT (FShaderTarget)
DECLARE_LOG_CATEGORY_EXTERN()
RENDERCORE_API DECLARE_LOG_CATEGORY_EXTERN (LogShaders , Error , All)
Controls whether shader related logs are visible.
Note: The runtime verbosity is driven by the console variable 'r.ShaderDevelopmentMode'
References All, and Error.
DECLARE_MEMORY_STAT_EXTERN() [1/3]
DECLARE_MEMORY_STAT_EXTERN (TEXT("Shader Memory") , STAT_Shaders_ShaderMemory , STATGROUP_Shaders , RENDERCORE_API)
DECLARE_MEMORY_STAT_EXTERN() [2/3]
DECLARE_MEMORY_STAT_EXTERN (TEXT("Shader Preload Mem") , STAT_Shaders_ShaderPreloadMemory , STATGROUP_Shaders , RENDERCORE_API)
DECLARE_MEMORY_STAT_EXTERN() [3/3]
DECLARE_MEMORY_STAT_EXTERN (TEXT("Shader Resource Mem") , STAT_Shaders_ShaderResourceMemory , STATGROUP_Shaders , RENDERCORE_API)
ENUM_CLASS_FLAGS() [1/3]
ENUM_CLASS_FLAGS (EShaderCodeFeatures)
ENUM_CLASS_FLAGS() [2/3]
ENUM_CLASS_FLAGS (EShaderParameterTypeMask)
ENUM_CLASS_FLAGS() [3/3]
ENUM_CLASS_FLAGS (EShaderResourceUsageFlags)
Definition at line 775 of file ShaderCore.h.
References Key, and PackedResourceCounts.
FlushShaderFileCache()
RENDERCORE_API void FlushShaderFileCache () extern
Flushes the shader file and CRC cache, and regenerates the binary shader files if necessary.
Allows shader source files to be re-read properly even if they've been modified since startup.
References FlushShaderFileCache().
Referenced by FlushShaderFileCache().
GenerateReferencedUniformBuffers()
void GenerateReferencedUniformBuffers (const TCHAR * SourceFilename, const TCHAR * ShaderTypeName, const TMap< FString, TArray< const TCHAR * > > & ShaderFileToUniformBufferVariables, TSet< const FShaderParametersMetadata * > & UniformBuffers) extern
Parses the given source file and its includes for references of uniform buffers.
References UniformBuffers.
GetAllVirtualShaderSourcePaths()
RENDERCORE_API void GetAllVirtualShaderSourcePaths (TArray< FString > & OutVirtualFilePaths, EShaderPlatform ShaderPlatform, const FName * ShaderPlatformName = nullptr) extern
References ShaderPlatform.
GetMemoryStatType()
TStatId GetMemoryStatType (EShaderFrequency ShaderFrequency) inline
Definition at line 140 of file ShaderCore.h.
References GET_STATID.
GetShaderCompressionFormat()
RENDERCORE_API FName GetShaderCompressionFormat () extern
Returns the shader compression format.
Oodle is used exclusively now. r.Shaders.SkipCompression configures Oodle to be uncompressed instead of returning NAME_None.
Referenced by FShaderCode::GetFinalizedResource(), and FShaderCode::SetFromResource().
GetShaderCompressionOodleSettings()
RENDERCORE_API void GetShaderCompressionOodleSettings (FOodleDataCompression::ECompressor & OutCompressor, FOodleDataCompression::ECompressionLevel & OutLevel, const FName & ShaderFormat = NAME_None) extern
Returns Oodle-specific shader compression format settings (passing ShaderFormat for future proofing, but as of now the setting is global for all formats).
Referenced by FShaderCode::GetFinalizedResource(), and FShaderCode::SetFromResource().
GetShaderFileHash()
RENDERCORE_API const class FSHAHash & GetShaderFileHash (const TCHAR * VirtualFilePath, EShaderPlatform ShaderPlatform) extern
Calculates a Hash for the given filename if it does not already exist in the Hash cache.
Parameters
Filename - shader file to Hash
ShaderPlatform - shader platform to Hash
Returns
Reference to the Hash created and stored for the file, or to an empty FSHAHash if not found. Logs an error if the file is not loadable.
References ShaderPlatform, and VirtualFilePath.
GetShaderFilesHash()
RENDERCORE_API const class FSHAHash & GetShaderFilesHash (const TArray< FString > & VirtualFilePaths, EShaderPlatform ShaderPlatform) extern
Calculates a Hash for the list of filenames if it does not already exist in the Hash cache.
References GetShaderFilesHash(), and ShaderPlatform.
Referenced by GetShaderFilesHash().
GetShaderIncludes() [1/2]
RENDERCORE_API void GetShaderIncludes (const TCHAR * EntryPointVirtualFilePath, const TCHAR * VirtualFilePath, const FString & FileContents, TArray< FString > & IncludeVirtualFilePaths, EShaderPlatform ShaderPlatform, uint32 DepthLimit = 100, const FName * ShaderPlatformName = nullptr) extern
References FileContents, ShaderPlatform, and VirtualFilePath.
GetShaderIncludes() [2/2]
RENDERCORE_API void GetShaderIncludes (const TCHAR * EntryPointVirtualFilePath, const TCHAR * VirtualFilePath, TArray< FString > & IncludeVirtualFilePaths, EShaderPlatform ShaderPlatform, uint32 DepthLimit = 100, const FName * ShaderPlatformName = nullptr) extern
Recursively populates IncludeFilenames with the include filenames from Filename.
References ShaderPlatform, and VirtualFilePath.
GetShaderSourceFilePath()
RENDERCORE_API FString GetShaderSourceFilePath (const FString & VirtualFilePath, TArray< struct FShaderCompilerError > * CompileErrors = nullptr) extern
Convert the virtual shader path to an actual file system path.
CompileErrors output array is optional.
References VirtualFilePath.
GetShaderTypeLayoutHash()
RENDERCORE_API FSHAHash GetShaderTypeLayoutHash (const FTypeLayoutDesc & TypeDesc, FPlatformTypeLayoutParameters LayoutParameters) extern
Return the hash of the given type layout for a partical platform type layout.
This function employs caching to avoid re-hashing the same parameters several times.
InitializeShaderHashCache()
RENDERCORE_API void InitializeShaderHashCache () extern
Initializes shader hash cache from IShaderFormatModules.
This must be called before reading any shader include.
InitializeShaderTypes()
RENDERCORE_API void InitializeShaderTypes () extern
Initializes cached shader type data.
This must be called before creating any FShaderType.
InvalidateShaderFileCacheEntry()
RENDERCORE_API void InvalidateShaderFileCacheEntry (const TCHAR * InVirtualFilePath, EShaderPlatform InShaderPlatform, const FName * InShaderPlatformName = nullptr) extern
Invalidates a single entry in the shader file and CRC caches.
References InvalidateShaderFileCacheEntry().
Referenced by InvalidateShaderFileCacheEntry().
IsParameterBindless()
bool IsParameterBindless (EShaderParameterType ParameterType) inline
Definition at line 272 of file ShaderCore.h.
References BindlessSampler, BindlessSRV, and BindlessUAV.
LoadShaderSourceFileChecked()
RENDERCORE_API void LoadShaderSourceFileChecked (const TCHAR * VirtualFilePath, EShaderPlatform ShaderPlatform, FString & OutFileContents, const FName * ShaderPlatformName = nullptr) extern
Loads the shader file with the given name.
If the shader file couldn't be loaded, throws a fatal error.
References ShaderPlatform, and VirtualFilePath.
MakeInjectedShaderCodeBlock()
FString RENDERCORE_API MakeInjectedShaderCodeBlock (const TCHAR * BlockName, const FString & CodeToInject)
Create a block of source code to be injected in the preprocessed shader code.
The Block will be put into a #line directive to show up in case shader compilation failures happen in this code block.
operator<<() [1/7]
FArchive & operator<< (FArchive & Ar, FShaderCodeValidationStride & ShaderCodeValidationStride) inline
Definition at line 905 of file ShaderCore.h.
References Ar.
operator<<() [2/7]
FArchive & operator<< (FArchive & Ar, FShaderCodeValidationType & ShaderCodeValidationType) inline
Definition at line 910 of file ShaderCore.h.
References Ar.
operator<<() [3/7]
FArchive & operator<< (FArchive & Ar, FShaderCodeValidationUBSize & ShaderCodeValidationSize) inline
Definition at line 915 of file ShaderCore.h.
References Ar.
operator<<() [4/7]
FArchive & operator<< (FArchive & Ar, FShaderDiagnosticData & ShaderCodeDiagnosticData) inline
Definition at line 949 of file ShaderCore.h.
References Ar, FShaderDiagnosticData::Hash, and FShaderDiagnosticData::Message.
operator<<() [5/7]
RENDERCORE_API FArchive & operator<< (FArchive & Ar, FSharedBuffer & Buffer)
References Ar, and Buffer.
operator<<() [6/7]
FArchive & operator<< (FArchive & Ar, FUniformBufferEntry & Entry) inline
Definition at line 380 of file ShaderCore.h.
References Ar, FUniformBufferEntry::BindingFlags, FUniformBufferEntry::Flags, TSharedPtr< ObjectType, InMode >::Get(), FUniformBufferEntry::LayoutHash, MakeShareable(), FUniformBufferEntry::MemberNameBuffer, and FUniformBufferEntry::StaticSlotName.
operator<<() [7/7]
FArchive & operator<< (FArchive & Ar, FUniformResourceEntry & Entry) inline
Definition at line 367 of file ShaderCore.h.
References Ar, FUniformResourceEntry::ResourceIndex, FUniformResourceEntry::Type, FUniformResourceEntry::UniformBufferMemberName, and FUniformResourceEntry::UniformBufferNameLength.
operator==()
bool operator== (const FShaderStatVariant LHS, const FShaderStatVariant RHS)
ParseVirtualShaderFilename()
RENDERCORE_API FString ParseVirtualShaderFilename (const FString & InFilename) extern
Converts an absolute or relative shader filename to a filename relative to the shader directory.
Parameters
InFilename - The shader filename.
Returns
a filename relative to the shaders directory.
ReplaceVirtualFilePathForShaderAutogen()
RENDERCORE_API bool ReplaceVirtualFilePathForShaderAutogen (FString & InOutVirtualFilePath, EShaderPlatform ShaderPlatform, const FName * InShaderPlatformName = nullptr) extern
Replaces virtual platform path with appropriate autogen path for a given ShaderPlatform.
Returns true if path was changed.
References ShaderPlatform.
ReplaceVirtualFilePathForShaderPlatform()
RENDERCORE_API bool ReplaceVirtualFilePathForShaderPlatform (FString & InOutVirtualFilePath, EShaderPlatform ShaderPlatform) extern
Replaces virtual platform path with appropriate path for a given ShaderPlatform.
Returns true if path was changed.
References ShaderPlatform.
ResetAllShaderSourceDirectoryMappings()
RENDERCORE_API void ResetAllShaderSourceDirectoryMappings () extern
Hook for shader compile worker to reset the directory mappings.
ShaderCompileJobPriorityToString()
const TCHAR * ShaderCompileJobPriorityToString (EShaderCompileJobPriority InPriority) inline
Definition at line 812 of file ShaderCore.h.
References checkNoEntry, ExtraHigh, ForceLocal, High, Low, None, Normal, and TEXT.
TryGetShaderFileHash()
RENDERCORE_API const FSHAHash * TryGetShaderFileHash (const TCHAR * VirtualFilePath, EShaderPlatform ShaderPlatform, FString * OutErrorMessage = nullptr) extern
Calculates a Hash for the given filename if it does not already exist in the Hash cache.
Parameters
Filename - shader file to Hash
ShaderPlatform - shader platform to Hash
OutErrorMessage - If non-null, receives the errormessage if nullptr is returned.
Returns
Pointer to the Hash created and stored for the file, or nullptr if not found.
References ShaderPlatform, and VirtualFilePath.
UE_DEPRECATED()
UE_DEPRECATED (5. 5, "HashShaderFileWithIncludes is no longer used by the shader compilation system and so no longer supported.") &
UpdateIncludeDirectoryForPreviewPlatform()
RENDERCORE_API void UpdateIncludeDirectoryForPreviewPlatform (EShaderPlatform PreviewPlatform, EShaderPlatform ActualPlatform) extern
Updates the PreviewPlatform's IncludeDirectory to match that of the Parent Platform.
UpdateReferencedUniformBufferNames()
RENDERCORE_API void UpdateReferencedUniformBufferNames (TArrayView< const FShaderType * > OutdatedShaderTypes, TArrayView< const FVertexFactoryType * > OutdatedFactoryTypes, TArrayView< const FShaderPipelineType * > OutdatedShaderPipelineTypes)
Force updates each shader/pipeline type provided to update their list of referenced uniform buffers.
VerifyShaderSourceFiles()
RENDERCORE_API void VerifyShaderSourceFiles (EShaderPlatform ShaderPlatform) extern
References ShaderPlatform, and VerifyShaderSourceFiles().
Referenced by VerifyShaderSourceFiles().
Variable Documentation
bOnlyHashIncludedFiles
const TCHAR const FString EShaderPlatform bool bOnlyHashIncludedFiles
Definition at line 1550 of file ShaderCore.h.
FileContents
const TCHAR const FString& FileContents
Definition at line 1550 of file ShaderCore.h.
Referenced by GetShaderIncludes().
NumShaderCompileJobPriorities
int32 NumShaderCompileJobPriorities = (int32)EShaderCompileJobPriority::Num inline constexpr
Definition at line 810 of file ShaderCore.h.
ShaderPlatform
const TCHAR const FString EShaderPlatform ShaderPlatform
Definition at line 1550 of file ShaderCore.h.
VirtualFilePath
const TCHAR* VirtualFilePath
Definition at line 1550 of file ShaderCore.h.
Referenced by AddShaderSourceFileEntry(), CheckShaderHashCacheInclude(), FixupShaderFilePath(), GetShaderFileHash(), GetShaderIncludes(), GetShaderIncludes(), GetShaderPreprocessDependencies(), GetShaderSourceFilePath(), LoadShaderSourceFile(), LoadShaderSourceFileChecked(), and TryGetShaderFileHash().