Unreal Engine 5.6 C++ API: Runtime/SlateCore/Public/Types/SlateConstants.h File Reference
SlateConstants.h File Reference
#include "CoreMinimal.h"
#include "HAL/IConsoleManager.h"
Functions
float GetGlobalGamepadScrollMultiplier ()
float GetGlobalScrollAmount ()
Variables
TAutoConsoleVariable< float > GlobalGamepadScrollMultiplier
How much to multiply scroll amount when using gamepad.
TAutoConsoleVariable< float > GlobalScrollAmount
How much to scroll for each click of the mouse wheel (in Slate Screen Units).
float GSlateContrast
Function Documentation
GetGlobalGamepadScrollMultiplier()
float GetGlobalGamepadScrollMultiplier () inline
Definition at line 14 of file SlateConstants.h.
References GlobalGamepadScrollMultiplier.
GetGlobalScrollAmount()
float GetGlobalScrollAmount () inline
Definition at line 10 of file SlateConstants.h.
References GlobalScrollAmount.
Referenced by SListView< TSharedPtr< FString > >::SLATE_BEGIN_ARGS(), STileView< ItemType >::SLATE_BEGIN_ARGS(), and STreeView< FRigVMSearchResult >::SLATE_BEGIN_ARGS().
Variable Documentation
GlobalGamepadScrollMultiplier
TAutoConsoleVariable<float> GlobalGamepadScrollMultiplier extern
How much to multiply scroll amount when using gamepad.
Referenced by GetGlobalGamepadScrollMultiplier().
GlobalScrollAmount
TAutoConsoleVariable<float> GlobalScrollAmount extern
How much to scroll for each click of the mouse wheel (in Slate Screen Units).
Referenced by GetGlobalScrollAmount().
GSlateContrast
float GSlateContrast extern