Unreal Engine 5.6 C++ API: Runtime/SlateCore/Public/Types/SlateVector2.h File Reference
SlateVector2.h File Reference
#include "CoreTypes.h"
#include "Math/Vector2D.h"
#include "Math/IntPoint.h"
#include "Math/UnrealMathUtility.h"
#include "Misc/Optional.h"
#include "SlateVector2.generated.h"
Data Structures
struct TStructOpsTypeTraits< FDeprecateSlateVector2D >
struct UE::Slate::FDeprecateOptionalVector2DParameter
Defines an optional Slate vector parameter in a similar vein to FDeprecateVector2DParameter NOTE: DO NOT USE THIS TYPE DIRECTLY IN CLIENT CODE - ALL USAGES SHOULD USE FVector2f or float.
struct UE::Slate::FDeprecateSlateVectorPtrVariant
struct UE::Slate::FDeprecateVector2DParameter
Defines a Slate vector used as a function parameter that was previously an FVector2D but is in the process of being deprecated in favor of FVector2f.
Namespaces
namespace UE
Utility functions for applying transformations to meshes.
namespace UE::Slate
Macros
#define UE_ENABLE_SLATE_VECTOR_DEPRECATION_MECHANISMS 1
When disabled, all deprecation mechanisms will be disabled, and public slate APIs will only compile with single-precision.
#define UE_INCLUDETOOL_IGNORE_INCONSISTENT_STATE
The subsequent deprecation macros can be enabled or disabled per-module Tell the IncludeTool static analyzer to ignore that divergence.
#define UE_REPORT_SLATE_VECTOR_DEPRECATION 0
When a module enables UE_REPORT_SLATE_VECTOR_DEPRECATION through PrivateDefines.Add("UE_REPORT_SLATE_VECTOR_DEPRECATION=1"), deprecation mechanisms will be enabled on that module for Slate double/single vector APIs.
#define UE_REPORT_SLATE_VECTOR_DEPRECATION_VERSION all
#define UE_SLATE_BINARY_ASSIGNMENT_VECTOR_OPERATORS_A(Type, ...)
#define UE_SLATE_BINARY_ASSIGNMENT_VECTOR_OPERATORS_B(Type, ...)
#define UE_SLATE_BINARY_VECTOR_OPERATORS_A(Type, ...)
#define UE_SLATE_BINARY_VECTOR_OPERATORS_B(Type, ...)
#define UE_SLATE_DEPRECATED_VECTOR_VIRTUAL_FUNCTION
#define UE_SLATE_VECTOR_DEPRECATED(Text)
#define UE_SLATE_VECTOR_DEPRECATED_DEFAULT()
Typedefs
using UE::Slate::FDeprecateVector2DResult = FDeprecateSlateVector2D
Defines a return value or persistent member variable that was previously an FVector2D but is in the process of being deprecated in favor of FVector2f.
Functions
const FVector2f & UE::Slate::CastToVector2f (const FDeprecateSlateVector2D &InValue)
const FVector2f & UE::Slate::CastToVector2f (const FDeprecateVector2DParameter &InValue)
FVector2f UE::Slate::CastToVector2f (const FIntPoint &InValue)
FVector2f UE::Slate::CastToVector2f (const FVector2d &InValue)
const FVector2f & UE::Slate::CastToVector2f (const FVector2f &InValue)
CastToVector2f allows supported types to be explicitly coerced to an FVector2f or const FVector2f& This allows generic programming patterns that must operate on FVector2f given many input types.
template<typename TransformType>
UE::Slate::FDeprecateVector2DResult TransformPoint (const TransformType &Transform, const UE::Slate::FDeprecateVector2DResult &Point)
UE::Slate::FDeprecateVector2DResult TransformPoint (float Transform, const UE::Slate::FDeprecateVector2DResult &Point)
template<typename TransformType>
UE::Slate::FDeprecateVector2DResult TransformVector (const TransformType &Transform, const UE::Slate::FDeprecateVector2DResult &Point)
UE::Slate::FDeprecateVector2DResult TransformVector (float Transform, const UE::Slate::FDeprecateVector2DResult &Vector)
USTRUCT () "
Defines a return value or persistent member variable that was previously an FVector2D but is in the process of being deprecated in favor of FVector2f.
Variables
HasNativeBreak
HasNativeMake ="/Script/Engine.KismetMathLibrary.MakeVector2D"
ScriptDefaultBreak
ScriptDefaultMake
ToolTip ="Vector2D (single-precision)"
Macro Definition Documentation
UE_ENABLE_SLATE_VECTOR_DEPRECATION_MECHANISMS
#define UE_ENABLE_SLATE_VECTOR_DEPRECATION_MECHANISMS 1
When disabled, all deprecation mechanisms will be disabled, and public slate APIs will only compile with single-precision.
Definition at line 17 of file SlateVector2.h.
UE_INCLUDETOOL_IGNORE_INCONSISTENT_STATE
#define UE_INCLUDETOOL_IGNORE_INCONSISTENT_STATE
The subsequent deprecation macros can be enabled or disabled per-module Tell the IncludeTool static analyzer to ignore that divergence.
Definition at line 25 of file SlateVector2.h.
UE_REPORT_SLATE_VECTOR_DEPRECATION
#define UE_REPORT_SLATE_VECTOR_DEPRECATION 0
When a module enables UE_REPORT_SLATE_VECTOR_DEPRECATION through PrivateDefines.Add("UE_REPORT_SLATE_VECTOR_DEPRECATION=1"), deprecation mechanisms will be enabled on that module for Slate double/single vector APIs.
Definition at line 33 of file SlateVector2.h.
UE_REPORT_SLATE_VECTOR_DEPRECATION_VERSION
#define UE_REPORT_SLATE_VECTOR_DEPRECATION_VERSION all
Definition at line 39 of file SlateVector2.h.
UE_SLATE_BINARY_ASSIGNMENT_VECTOR_OPERATORS_A
#define UE_SLATE_BINARY_ASSIGNMENT_VECTOR_OPERATORS_A (Type, ...)
Value:
        __VA_ARGS__\
        friend Type& operator+=(Type& A, const FDeprecateSlateVector2D& B)\
        {\
            A = Type(FDeprecateSlateVector2D(UE::Slate::CastToVector2f(A) + UE::Slate::CastToVector2f(B)));\
            return A;\
        }\
        __VA_ARGS__\
        friend Type& operator-=(Type& A, const FDeprecateSlateVector2D& B)\
        {\
            A = Type(FDeprecateSlateVector2D(UE::Slate::CastToVector2f(A) - UE::Slate::CastToVector2f(B)));\
            return A;\
        }\
        __VA_ARGS__\
        friend Type& operator*=(Type& A, const FDeprecateSlateVector2D& B)\
        {\
            A = Type(FDeprecateSlateVector2D(UE::Slate::CastToVector2f(A) * UE::Slate::CastToVector2f(B)));\
            return A;\
        }\
        __VA_ARGS__\
        friend Type& operator/=(Type& A, const FDeprecateSlateVector2D& B)\
        {\
            A = Type(FDeprecateSlateVector2D(UE::Slate::CastToVector2f(A) / UE::Slate::CastToVector2f(B)));\
            return A;\
        }
UE_SLATE_BINARY_ASSIGNMENT_VECTOR_OPERATORS_B
#define UE_SLATE_BINARY_ASSIGNMENT_VECTOR_OPERATORS_B (Type, ...)
Value:
        __VA_ARGS__\
        friend FDeprecateSlateVector2D& operator+=(FDeprecateSlateVector2D& A, const Type& B)\
        {\
            static_cast<FVector2f&>(A) += UE::Slate::CastToVector2f(B);\
            return A;\
        }\
        __VA_ARGS__\
        friend FDeprecateSlateVector2D& operator-=(FDeprecateSlateVector2D& A, const Type& B)\
        {\
            static_cast<FVector2f&>(A) -= UE::Slate::CastToVector2f(B);\
            return A;\
        }\
        __VA_ARGS__\
        friend FDeprecateSlateVector2D& operator*=(FDeprecateSlateVector2D& A, const Type& B)\
        {\
            static_cast<FVector2f&>(A) *= UE::Slate::CastToVector2f(B);\
            return A;\
        }\
        __VA_ARGS__\
        friend FDeprecateSlateVector2D& operator/=(FDeprecateSlateVector2D& A, const Type& B)\
        {\
            static_cast<FVector2f&>(A) /= UE::Slate::CastToVector2f(B);\
            return A;\
        }
UE_SLATE_BINARY_VECTOR_OPERATORS_A
#define UE_SLATE_BINARY_VECTOR_OPERATORS_A (Type, ...)
Value:
        __VA_ARGS__\
        friend FDeprecateSlateVector2D operator+(const Type& A, const FDeprecateSlateVector2D& B)\
        {\
            return FDeprecateSlateVector2D(UE::Slate::CastToVector2f(A) + UE::Slate::CastToVector2f(B));\
        }\
        __VA_ARGS__\
        friend FDeprecateSlateVector2D operator-(const Type& A, const FDeprecateSlateVector2D& B)\
        {\
            return FDeprecateSlateVector2D(UE::Slate::CastToVector2f(A) - UE::Slate::CastToVector2f(B));\
        }\
        __VA_ARGS__\
        friend FDeprecateSlateVector2D operator*(const Type& A, const FDeprecateSlateVector2D& B)\
        {\
            return FDeprecateSlateVector2D(UE::Slate::CastToVector2f(A) * UE::Slate::CastToVector2f(B));\
        }\
        __VA_ARGS__\
        friend FDeprecateSlateVector2D operator/(const Type& A, const FDeprecateSlateVector2D& B)\
        {\
            return FDeprecateSlateVector2D(UE::Slate::CastToVector2f(A) / UE::Slate::CastToVector2f(B));\
        }\
        __VA_ARGS__\
        friend bool operator==(const Type& A, const FDeprecateSlateVector2D& B)\
        {\
            return UE::Slate::CastToVector2f(A) == UE::Slate::CastToVector2f(B);\
        }\
        __VA_ARGS__\
        friend bool operator!=(const Type& A, const FDeprecateSlateVector2D& B)\
        {\
            return UE::Slate::CastToVector2f(A) != UE::Slate::CastToVector2f(B);\
        }
UE_SLATE_BINARY_VECTOR_OPERATORS_B
#define UE_SLATE_BINARY_VECTOR_OPERATORS_B (Type, ...)
Value:
        __VA_ARGS__\
        friend FDeprecateSlateVector2D operator+(const FDeprecateSlateVector2D& A, const Type& B)\
        {\
            return FDeprecateSlateVector2D(UE::Slate::CastToVector2f(A) + UE::Slate::CastToVector2f(B));\
        }\
        __VA_ARGS__\
        friend FDeprecateSlateVector2D operator-(const FDeprecateSlateVector2D& A, const Type& B)\
        {\
            return FDeprecateSlateVector2D(UE::Slate::CastToVector2f(A) - UE::Slate::CastToVector2f(B));\
        }\
        __VA_ARGS__\
        friend FDeprecateSlateVector2D operator*(const FDeprecateSlateVector2D& A, const Type& B)\
        {\
            return FDeprecateSlateVector2D(UE::Slate::CastToVector2f(A) * UE::Slate::CastToVector2f(B));\
        }\
        __VA_ARGS__\
        friend FDeprecateSlateVector2D operator/(const FDeprecateSlateVector2D& A, const Type& B)\
        {\
            return FDeprecateSlateVector2D(UE::Slate::CastToVector2f(A) / UE::Slate::CastToVector2f(B));\
        }\
        __VA_ARGS__\
        friend bool operator==(const FDeprecateSlateVector2D& A, const Type& B)\
        {\
            return UE::Slate::CastToVector2f(A) == UE::Slate::CastToVector2f(B);\
        }\
        __VA_ARGS__\
        friend bool operator!=(const FDeprecateSlateVector2D& A, const Type& B)\
        {\
            return UE::Slate::CastToVector2f(A) != UE::Slate::CastToVector2f(B);\
        }
UE_SLATE_DEPRECATED_VECTOR_VIRTUAL_FUNCTION
#define UE_SLATE_DEPRECATED_VECTOR_VIRTUAL_FUNCTION
Definition at line 54 of file SlateVector2.h.
Referenced by SNodePanel::OnBeginNodeInteraction(), SGraphEditor::UE_DEPRECATED(), and USTRUCT().
UE_SLATE_VECTOR_DEPRECATED
#define UE_SLATE_VECTOR_DEPRECATED (Text)
Definition at line 47 of file SlateVector2.h.
UE_SLATE_VECTOR_DEPRECATED_DEFAULT
#define UE_SLATE_VECTOR_DEPRECATED_DEFAULT ()
Definition at line 48 of file SlateVector2.h.
Function Documentation
TransformPoint() [1/2]
template<typename TransformType> UE::Slate::FDeprecateVector2DResult TransformPoint (const TransformType & Transform, const UE::Slate::FDeprecateVector2DResult & Point) inline
Definition at line 575 of file SlateVector2.h.
References Point, and Transform.
TransformPoint() [2/2]
UE::Slate::FDeprecateVector2DResult TransformPoint (float Transform, const UE::Slate::FDeprecateVector2DResult & Point) inline
Definition at line 564 of file SlateVector2.h.
References Point, and Transform.
TransformVector() [1/2]
template<typename TransformType> UE::Slate::FDeprecateVector2DResult TransformVector (const TransformType & Transform, const UE::Slate::FDeprecateVector2DResult & Point) inline
Definition at line 581 of file SlateVector2.h.
References Point, and Transform.
TransformVector() [2/2]
UE::Slate::FDeprecateVector2DResult TransformVector (float Transform, const UE::Slate::FDeprecateVector2DResult & Vector) inline
Definition at line 569 of file SlateVector2.h.
References Transform, and Vector.
USTRUCT()
USTRUCT ()
Defines a return value or persistent member variable that was previously an FVector2D but is in the process of being deprecated in favor of FVector2f.
Once deprecated completely, usages will be converted to using FVector2f directly. It is not (and will never be) constructible from double precision types.
This type is implicitly convertible to FVector2D, and can be operated on as if it were an FVector2D, but will emit deprecation warnings under these situations where UE_REPORT_SLATE_VECTOR_DEPRECATION is enabled.
This type should not be used as a parameter, where FDeprecateVector2DParameter is preferred due to its implicit conversion from many types, and separate deprecation mechanisms.
NOTE: DO NOT USE THIS TYPE DIRECTLY IN CLIENT CODE - ALL USAGES SHOULD USE FVector2f or float
Variable Documentation
HasNativeBreak
HasNativeBreak
Definition at line 123 of file SlateVector2.h.
Referenced by USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), and USTRUCT().
HasNativeMake
HasNativeMake ="/Script/Engine.KismetMathLibrary.MakeVector2D"
Definition at line 123 of file SlateVector2.h.
Referenced by USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), and USTRUCT().
ScriptDefaultBreak
ScriptDefaultBreak
Definition at line 123 of file SlateVector2.h.
ScriptDefaultMake
ScriptDefaultMake
Definition at line 123 of file SlateVector2.h.
ToolTip
ToolTip ="Vector2D (single-precision)"
Definition at line 123 of file SlateVector2.h.
Referenced by UAnimNotifyState_TimedParticleEffect::GENERATED_UCLASS_BODY(), IDetailCategoryBuilder::SetToolTip(), IDetailGroup::SetToolTip(), IPropertyHandle::SetToolTipText(), SSegmentedControl< OptionType >::FSlot::SLATE_ATTRIBUTE(), UCLASS(), UGroomAsset::UE_DEPRECATED(), UGroomAsset::UE_DEPRECATED(), UENUM(), UENUM(), UENUM(), UENUM(), UENUM(), UENUM(), UENUM(), UAnimNotifyState_TimedParticleEffect::UPROPERTY(), UAnimNotifyState_TimedParticleEffect::UPROPERTY(), UAnimNotifyState_TimedParticleEffect::UPROPERTY(), UAnimNotifyState_TimedParticleEffect::UPROPERTY(), UBrushBuilder::UPROPERTY(), UDataLayerInstancePrivate::UPROPERTY(), UDataLayerInstanceWithAsset::UPROPERTY(), UEditorProjectAssetSettings::UPROPERTY(), UFbxStaticMeshImportData::UPROPERTY(), UGroomAsset::UPROPERTY(), UGroomAsset::UPROPERTY(), UGroomComponent::UPROPERTY(), USoundWave::UPROPERTY(), UStaticMeshComponent::UPROPERTY(), FScopedSkeletalMeshRenderData::USkeletalMesh, USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), and USTRUCT().