Unreal Engine 5.6 C++ API: S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/SmartObjects/Source/SmartObjectsModule/Public/SmartObjectRuntime.h File Reference
SmartObjectRuntime.h File Reference
#include "SmartObjectTypes.h"
#include "SmartObjectDefinition.h"
#include "SmartObjectRuntime.generated.h"
Namespaces
namespace UE
Utility functions for applying transformations to meshes.
namespace UE::SmartObject
Macros
#define UE_API SMARTOBJECTSMODULE_API
Functions
DECLARE_DELEGATE_TwoParams (FOnSlotInvalidated, const FSmartObjectClaimHandle &, ESmartObjectSlotState)
Delegate to notify when a given slot gets invalidated and the interaction must be aborted.
uint16 UE::SmartObject::GetMaskForEnabledReasonTag (const FGameplayTag Tag)
FTransform & GetMutableTransform ()
void SetTransform (const FTransform &InTransform)
UPROPERTY () FTransform Transform
UENUM() enum class ESmartObjectSlotState UENUM() enum class ETrySpawnActorIfDehydrated USTRUCT () struct FSmartObjectClaimHandle
Enumeration to represent the runtime state of a slot.
Variables
Transform is moved to FSmartObjectRuntimeSlot SMARTOBJECTSMODULE_API FSmartObjectSlotTransform
Macro Definition Documentation
UE_API
#define UE_API SMARTOBJECTSMODULE_API
Definition at line 9 of file SmartObjectRuntime.h.
Function Documentation
DECLARE_DELEGATE_TwoParams()
DECLARE_DELEGATE_TwoParams (FOnSlotInvalidated , const FSmartObjectClaimHandle & , ESmartObjectSlotState) protected
Delegate to notify when a given slot gets invalidated and the interaction must be aborted.
GetMutableTransform()
FTransform & GetMutableTransform ()
Definition at line 116 of file SmartObjectRuntime.h.
References Transform.
SetTransform()
void SetTransform (const FTransform & InTransform)
Definition at line 118 of file SmartObjectRuntime.h.
References Transform.
Referenced by UCLASS(), IGizmoTransformSource::UFUNCTION(), and USTRUCT().
UPROPERTY()
UPROPERTY () protected
References Transform, and Transient.
USTRUCT()
UENUM() enum class ESmartObjectSlotState UENUM() enum class ETrySpawnActorIfDehydrated USTRUCT ()
Enumeration to represent the runtime state of a slot.
Struct to store and manage state of a runtime instance associated to a given smart object definition.
Struct to store and manage state of a runtime instance associated to a given slot definition.
Runtime data holding the final slot transform (i.e.
Indicates if the subsystem should try to spawn the actor associated to the smartobject if it is currently owned by an instanced actor. Struct describing a reservation between a user and a smart object slot.
parent transform applied on slot local offset and rotation)
Indicates that the handle was properly assigned by a call to 'Claim' but doesn't guarantee that the associated object and slot are still registered in the simulation. This information requires a call to USmartObjectSubsystem::IsClaimedObjectValid using the handle.
Handle to the Smart Object where the claimed slot belongs to.
Handle of the claimed slot.
Handle describing the user which claimed the slot.
Returns
Current claim state of the slot.
Sets the slot claimed.
Parameters
ClaimPriority Claim priority, a slot claimed at lower priority can be claimed by higher priority (unless already in use).
Returns
True if the slot can be claimed.
the runtime gameplay tags of the slot.
true if both the slot and its parent smart object are enabled.
User data struct that can be associated to the slot when claimed or used.
Indicates if preconditions were successfully initialized.
Struct could have been nested inside the subsystem but not possible with USTRUCT
Offset of the slot relative to the Smart Object.
Rotation of the slot relative to the Smart Object.
Runtime tags associated with this slot.
Struct used to store contextual data of the user when claiming or using a slot.
Slot state data that can be added at runtime.
Delegate used to notify when a slot gets invalidated. See RegisterSlotInvalidationCallback
Handle to the user that reserves or uses the slot
World condition runtime state.
Current availability state of the slot
True if the slot is enabled
True if the parent smart object is enabled
Returns all tags assigned to the smart object instance
Returns
reference to the Smart Object event delegate.
mutable reference to the Smart Object event delegate.
Indicates if the Smart Object is enabled regardless of the reason.
Returns
True of the Smart Object is enabled.
Indicates if the Smart Object is enabled based on a specific reason.
Parameters
ReasonTag Valid Tag to specify the reason for changing the enabled state of the object. Method will ensure if not valid (i.e. None).
Returns
True of the Smart Object is enabled.
Enables or disables the entire smart object.
Parameters
ReasonTag Valid Tag to specify the reason for changing the enabled state of the object. Method will ensure if not valid (i.e. None).
bEnabled Flag indicating if the object should be enabled or not.
Returns the actor associated to the smart object instance.
Parameters
TrySpawnActorIfDehydrated Indicates if the instance should try to spawn the actor/component associated to the smartobject if it is currently owned by an instanced actor.
Returns
Pointer to owner actor if present.
Returns the actor associated to the smart object instance.
Parameters
TrySpawnActorIfDehydrated Indicates if the instance should try to spawn the actor/component associated to the smartobject if it is currently owned by an instanced actor.
Returns
Pointer to owning component if present.
handle of the specified slot.
Indicates if preconditions were successfully initialized.
Struct could have been nested inside the subsystem but not possible with USTRUCT
Enables or disables the entire smart object using the bit mask from a reason tag.
Parameters
bEnabled Flag indicating if the object should be enabled or not.
ReasonMask Bit mask associated to the reason for disabling the object.
Creates full actor from instanced actor owner, if any. That actor will register its SmartObjectComponents that will then update OwnerComponent.
World condition runtime state.
Runtime slots
Associated smart object definition
Component that owns the Smart Object. May be empty if the parent Actor is not loaded.
Struct used to store contextual data of the owner of that SmartObject.
Instance specific transform
Tags applied to the current instance
Delegate that is fired when the Smart Object changes.
RegisteredHandle != FSmartObjectHandle::Invalid when registered with SmartObjectSubsystem
Spatial representation data associated to the current instance
Each slot has its own enabled state but the parent instance also have a more high level state that could be split into different reasons. Note: The enabled state is stored as disable bits to make it easier to check for "is the object disabled for a given or any reason".
Returns a reference to the slot state data of the specified type. Method will fail a check if the slot doesn't have the given type.
Returns a pointer to the slot state data of the specified type. Method will return null if the slot doesn't have the given type.
Returns a reference to the definition of the slot's parent object. Method will fail a check if called on an invalid SlotView.
Note
The definition fragment is always created and assigned when creating an entity associated to a slot so a valid SlotView is guaranteed to be able to provide it.
Returns a reference to the main definition of the slot. Method will fail a check if called on an invalid SlotView.
Fills the provided GameplayTagContainer with the activity tags associated to the slot according to the tag filtering policy. Method will fail a check if called on an invalid SlotView.
Returns a reference to the definition data of the specified type from the main slot definition. Method will fail a check if the slot definition doesn't contain the given type.
Returns a pointer to the definition data of the specified type from the main slot definition. Method will return null if the slot doesn't contain the given type.
Returns
the claim state of the slot.
true of the slot can be claimed.
true if the slot and the object is enabled.
runtime gameplay tags of the slot.
handle to the owning Smart Object.
Definition at line 49 of file SmartObjectRuntime.h.
References BlueprintType, Category, GENERATED_BODY, Handle, IsValid(), LexToString(), operator!=(), operator==(), Other, TEXT, Transient, UE_API, and UPROPERTY.
Variable Documentation
FSmartObjectSlotTransform
Transform is moved to FSmartObjectRuntimeSlot SMARTOBJECTSMODULE_API FSmartObjectSlotTransform
Definition at line 111 of file SmartObjectRuntime.h.