Unreal Engine 5.6 C++ API: Runtime/Engine/Classes/Sound/SoundWave.h File Reference
SoundWave.h File Reference
#include "CoreMinimal.h"
#include "Containers/IndirectArray.h"
#include "Sound/AudioSettings.h"
#include "Sound/SoundModulationDestination.h"
#include "UObject/ObjectMacros.h"
#include "Misc/Guid.h"
#include "Async/AsyncWork.h"
#include "Async/Mutex.h"
#include "Async/UniqueLock.h"
#include "Sound/SoundBase.h"
#include "Sound/SoundWaveTimecodeInfo.h"
#include "Interfaces/Interface_AsyncCompilation.h"
#include "Serialization/BulkData.h"
#include "Serialization/BulkDataBuffer.h"
#include "Serialization/EditorBulkData.h"
#include "Sound/SoundGroups.h"
#include "Sound/SoundWaveLoadingBehavior.h"
#include "UObject/ObjectKey.h"
#include "AudioMixerTypes.h"
#include "AudioCompressionSettings.h"
#include "UObject/PerPlatformProperties.h"
#include "ContentStreaming.h"
#include "IAudioProxyInitializer.h"
#include "IWaveformTransformation.h"
#include "ISoundWaveCloudStreaming.h"
#include "Templates/DontCopy.h"
#include "SoundWave.generated.h"
Data Structures
struct FCompareSpectralDataByFrequencyHz
class FSoundWaveData
class FSoundWaveProxy
struct FStreamedAudioChunk
A chunk of streamed audio.
struct ISoundWaveClient
class USoundWave
Namespaces
namespace Audio
Defines how a sound changes volume with distance to the listener.
Macros
#define CASE_TO_STRING(X)
Typedefs
using FSoundWaveProxyPtr = TSharedPtr<FSoundWaveProxy, ESPMode::ThreadSafe>
Enumerations
enum class ESoundWavePrecacheState { NotStarted , InProgress , Done }
Dictates whether to use the CuePoints and Loop Regions from the .wav file or from the waveform editor Marker transformations during playback.
Functions
UENUM() enum EDecompressionType const TCHAR * LexToString (const EDecompressionType InType)
FName Audio::ToName (ESoundAssetCompressionType InDecoderType)
ESoundAssetCompressionType Audio::ToSoundAssetCompressionType (EDefaultAudioCompressionType InDefaultCompressionType)
UCLASS ()
USTRUCT () struct FStreamedAudioPlatformData
Platform-specific data used streaming audio at runtime.
Variables
constexpr uint64 InvalidAudioStreamCacheLookupID = TNumericLimits<uint64>::Max()
Macro Definition Documentation
CASE_TO_STRING
#define CASE_TO_STRING (X)
Value:
case X: return TEXT(#X);
Referenced by LexToString().
Typedef Documentation
FSoundWaveProxyPtr
using FSoundWaveProxyPtr = TSharedPtr<FSoundWaveProxy, ESPMode::ThreadSafe>
Definition at line 1719 of file SoundWave.h.
Enumeration Type Documentation
ESoundWavePrecacheState
enum class ESoundWavePrecacheState strong
Dictates whether to use the CuePoints and Loop Regions from the .wav file or from the waveform editor Marker transformations during playback.
Precache states
Enumerator
NotStarted
InProgress
Done
Definition at line 80 of file SoundWave.h.
Function Documentation
LexToString()
UENUM() enum EDecompressionType const TCHAR * LexToString (const EDecompressionType InType) inline
Definition at line 56 of file SoundWave.h.
References CASE_TO_STRING, and TEXT.
UCLASS()
UCLASS ()
References BlueprintType, editinlinenew, hidecategories, meta, MinimalAPI, and Object.
USTRUCT()
USTRUCT ()
Platform-specific data used streaming audio at runtime.
Format in which audio chunks are stored.
audio data.
Default constructor.
Destructor.
Try to load audio chunk from the derived data cache or build it if it isn't there.
Parameters
ChunkIndex The Chunk index to load.
OutChunkData Address of pointer that will store chunk data - should either be NULL or have enough space for the chunk
Returns
if > 0, the size of the chunk in bytes. If 0, the chunk failed to load.
Get the chunks while making sure any async task are finished before returning.
Get the number of chunks while making sure any async task are finished before returning.
Get the audio format making sure any async task are finished before returning.
Serialization.
Takes the results of a DDC operation and deserializes it into an FStreamedAudioChunk struct.
Parameters
SerializedData Serialized data resulting from DDC.GetAsynchronousResults or DDC.GetSynchronous.
ChunkToDeserializeInto is the chunk to fill with the deserialized data.
ChunkIndex is the index of the chunk in this instance of FStreamedAudioPlatformData.
OutChunkData is a pointer to a pointer to populate with the chunk itself, or if pointing to nullptr, returns an allocated buffer.
Returns
the size of the chunk loaded in bytes, or zero if the chunk didn't load.
Definition at line 141 of file SoundWave.h.
References Ar, AsyncTask(), GENERATED_USTRUCT_BODY, Owner, USoundWave::RescheduleAsyncTask(), UE_DEPRECATED, and USoundWave::WaitAsyncTaskWithTimeout().
Variable Documentation
InvalidAudioStreamCacheLookupID
uint64 InvalidAudioStreamCacheLookupID = TNumericLimits<uint64>::Max() inline constexpr
Definition at line 87 of file SoundWave.h.