Unreal Engine 5.6 C++ API: Runtime/Core/Public/Containers/SparseArray.h File Reference
SparseArray.h File Reference
#include "CoreTypes.h"
#include "Misc/AssertionMacros.h"
#include "HAL/UnrealMemory.h"
#include "Templates/UnrealTypeTraits.h"
#include "Templates/UnrealTemplate.h"
#include "Containers/ContainerAllocationPolicies.h"
#include "Templates/Less.h"
#include "Containers/Array.h"
#include "Math/UnrealMathUtility.h"
#include "Containers/ScriptArray.h"
#include "Containers/BitArray.h"
#include "Serialization/StructuredArchive.h"
#include "Serialization/MemoryImageWriter.h"
#include "Containers/UnrealString.h"
#include "Misc/IntrusiveUnsetOptionalState.h"
Data Structures
class FScriptSparseArray
struct FScriptSparseArrayLayout
struct FSparseArrayAllocationInfo
The result of a sparse array allocation.
struct TIsZeroConstructType< TScriptSparseArray< AllocatorType, InDerivedType > >
class TScriptSparseArray< AllocatorType, InDerivedType >
struct TScriptSparseArray< AllocatorType, InDerivedType >::FFreeListLink
class TSparseArray< InElementType, Allocator >
A dynamically sized array where element indices aren't necessarily contiguous.
class TSparseArray< InElementType, Allocator >::FElementCompareClass< PREDICATE_CLASS >
Extracts the element value from the array's element structure and passes it to the user provided comparison class.
class TSparseArray< InElementType, Allocator >::TBaseIterator< bConst >
The base class of sparse array iterators.
class TSparseArray< InElementType, Allocator >::TConstIterator
Iterates over all allocated elements in a const sparse array.
class TSparseArray< InElementType, Allocator >::TConstSubsetIterator< SubsetAllocator >
An iterator which only iterates over the elements of the array which correspond to set bits in a separate bit array.
class TSparseArray< InElementType, Allocator >::TIterator
Iterates over all allocated elements in a sparse array.
class TSparseArray< InElementType, Allocator >::TRangedForConstIterator
class TSparseArray< InElementType, Allocator >::TRangedForIterator
union TSparseArrayElementOrFreeListLink< ElementType >
Allocated elements are overlapped with free element info in the element list.
Namespaces
namespace Freeze
Macros
#define TSPARSEARRAY_RANGED_FOR_CHECKS 1
Functions
DECLARE_TEMPLATE_INTRINSIC_TYPE_LAYOUT ((template< typename ElementType, typename Allocator >),(TSparseArray< ElementType, Allocator >))
DECLARE_TEMPLATE_INTRINSIC_TYPE_LAYOUT (template< typename ElementType >, TSparseArrayElementOrFreeListLink< ElementType >)
template<typename ElementType, typename Allocator>
uint32 Freeze::IntrinsicAppendHash (const TSparseArray< ElementType, Allocator > *DummyObject, const FTypeLayoutDesc &TypeDesc, const FPlatformTypeLayoutParameters &LayoutParams, FSHA1 &Hasher)
template<typename ElementType, typename Allocator>
uint32 Freeze::IntrinsicUnfrozenCopy (const FMemoryUnfreezeContent &Context, const TSparseArray< ElementType, Allocator > &Object, void *OutDst)
template<typename ElementType, typename Allocator>
void Freeze::IntrinsicWriteMemoryImage (FMemoryImageWriter &Writer, const TSparseArray< ElementType, Allocator > &Object, const FTypeLayoutDesc &)
void operator delete (void *, const FSparseArrayAllocationInfo &Allocation)
void * operator new (size_t Size, const FSparseArrayAllocationInfo &Allocation)
A placement new operator which constructs an element in a sparse array allocation.
template<typename T, typename Allocator>
void * operator new (size_t Size, TSparseArray< T, Allocator > &Array)
template<typename T, typename Allocator>
void * operator new (size_t Size, TSparseArray< T, Allocator > &Array, int32 Index)
template<typename ElementType, typename Allocator>
FArchive & operator<< (FArchive &Ar, TSparseArray< ElementType, Allocator > &Array)
Serializer.
template<typename ElementType, typename Allocator>
void operator<< (FStructuredArchive::FSlot Slot, TSparseArray< ElementType, Allocator > &InArray)
Structured archive serializer.
Macro Definition Documentation
TSPARSEARRAY_RANGED_FOR_CHECKS
#define TSPARSEARRAY_RANGED_FOR_CHECKS 1
Definition at line 25 of file SparseArray.h.
Function Documentation
DECLARE_TEMPLATE_INTRINSIC_TYPE_LAYOUT() [1/2]
DECLARE_TEMPLATE_INTRINSIC_TYPE_LAYOUT ((template< typename ElementType, typename Allocator >) , (TSparseArray< ElementType, Allocator >))
DECLARE_TEMPLATE_INTRINSIC_TYPE_LAYOUT() [2/2]
DECLARE_TEMPLATE_INTRINSIC_TYPE_LAYOUT (template< typename ElementType > , TSparseArrayElementOrFreeListLink< ElementType >)
References Allocator.
operator delete()
void operator delete (void * , const FSparseArrayAllocationInfo & Allocation) inline
Definition at line 1613 of file SparseArray.h.
operator new() [1/3]
void * operator new (size_t Size, const FSparseArrayAllocationInfo & Allocation) inline
A placement new operator which constructs an element in a sparse array allocation.
Definition at line 1608 of file SparseArray.h.
References TSequenceHistory< HistorySize >::Size, and UE_ASSUME.
operator new() [2/3]
template<typename T, typename Allocator> void * operator new (size_t Size, TSparseArray< T, Allocator > & Array)
Definition at line 1348 of file SparseArray.h.
References Array, check, and TSequenceHistory< HistorySize >::Size.
operator new() [3/3]
template<typename T, typename Allocator> void * operator new (size_t Size, TSparseArray< T, Allocator > & Array, int32 Index)
Definition at line 1354 of file SparseArray.h.
References Array, check, and TSequenceHistory< HistorySize >::Size.
operator<<() [1/2]
template<typename ElementType, typename Allocator> FArchive & operator<< (FArchive & Ar, TSparseArray< ElementType, Allocator > & Array)
Serializer.
Definition at line 1619 of file SparseArray.h.
References Ar, and Array.
operator<<() [2/2]
template<typename ElementType, typename Allocator> void operator<< (FStructuredArchive::FSlot Slot, TSparseArray< ElementType, Allocator > & InArray)
Structured archive serializer.
Definition at line 1648 of file SparseArray.h.
References TSparseArray< InElementType, Allocator >::AddUninitialized(), Array, TSparseArray< InElementType, Allocator >::Empty(), FStructuredArchiveSlot::EnterArray(), UE::StructuredArchive::Private::FSlotBase::GetUnderlyingArchive(), FArchive::IsLoading(), and TSparseArray< InElementType, Allocator >::Num().