Unreal Engine 5.6 C++ API: S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/StateTree/Source/StateTreeModule/Public/StateTreeTypes.h File Reference
StateTreeTypes.h File Reference
#include "PropertyBindingDataView.h"
#include "StructUtils/PropertyBag.h"
#include "GameplayTagContainer.h"
#include "StateTreeDelegate.h"
#include "StateTreeIndexTypes.h"
#include "StateTreeTasksStatus.h"
#include "StateTreeTypes.generated.h"
Data Structures
struct FStateTreeDataView
Helper struct to facilitate transition to FPropertyBindingDataView in the StateTree module.
struct TStructOpsTypeTraits< FStateTreeStateLink >
Namespaces
namespace UE
Utility functions for applying transformations to meshes.
namespace UE::StateTree
Data type the FStateTreeDataHandle is pointing at.
namespace UE::StateTree::Colors
Macros
#define UE_DEPRECATED(Version, Message)
Macro for marking up deprecated code, functions and types.
#define WITH_STATETREE_DEBUG (!(UE_BUILD_SHIPPING || UE_BUILD_SHIPPING_WITH_EDITOR || UE_BUILD_TEST) && 1)
Functions
static EStateTreeDataSourceType UE::StateTree::CastToDataSourceType (EStateTreeParameterDataType Value)
STATETREEMODULE_API DECLARE_LOG_CATEGORY_EXTERN (LogStateTree, Warning, All)
bool operator!= (const EStateTreeTransitionPriority Lhs, const EStateTreeTransitionPriority Rhs)
UENUM() enum class EStateTreeStateType UENUM() enum class EStateTreeStateSelectionBehavior UENUM() enum class EStateTreeTransitionTrigger ENUM_CLASS_FLAGS(EStateTreeTransitionTrigger) UENUM() enum class EStateTreeTransitionPriority bool operator< (const EStateTreeTransitionPriority Lhs, const EStateTreeTransitionPriority Rhs)
Transitions trigger.
bool operator<= (const EStateTreeTransitionPriority Lhs, const EStateTreeTransitionPriority Rhs)
bool operator== (const EStateTreeTransitionPriority Lhs, const EStateTreeTransitionPriority Rhs)
bool operator> (const EStateTreeTransitionPriority Lhs, const EStateTreeTransitionPriority Rhs)
bool operator>= (const EStateTreeTransitionPriority Lhs, const EStateTreeTransitionPriority Rhs)
const FName UE::StateTree::SchemaCanBeOverridenTag (TEXT("SchemaCanBeOverriden"))
const FName UE::StateTree::SchemaTag (TEXT("Schema"))
UE::StateTree::UE_DEPRECATED (5.5, "Use MaxExpressionIndent instead.") inline const expr int32 MaxConditionIndent
USTRUCT () struct FStateTreeStateHandle
Handle to a StateTree state.
Variables
const STATETREEMODULE_API FColor UE::StateTree::Colors::Blue
const STATETREEMODULE_API FColor UE::StateTree::Colors::Bronze
const STATETREEMODULE_API FColor UE::StateTree::Colors::Cyan
const STATETREEMODULE_API FColor UE::StateTree::Colors::DarkBlue
const STATETREEMODULE_API FColor UE::StateTree::Colors::DarkBronze
const STATETREEMODULE_API FColor UE::StateTree::Colors::DarkCyan
const STATETREEMODULE_API FColor UE::StateTree::Colors::DarkGreen
const STATETREEMODULE_API FColor UE::StateTree::Colors::DarkGrey
const STATETREEMODULE_API FColor UE::StateTree::Colors::DarkMagenta
const STATETREEMODULE_API FColor UE::StateTree::Colors::DarkOrange
const STATETREEMODULE_API FColor UE::StateTree::Colors::DarkPurple
const STATETREEMODULE_API FColor UE::StateTree::Colors::DarkRed
const STATETREEMODULE_API FColor UE::StateTree::Colors::DarkYellow
const STATETREEMODULE_API FColor UE::StateTree::Colors::Green
const STATETREEMODULE_API FColor UE::StateTree::Colors::Grey
const STATETREEMODULE_API FColor UE::StateTree::Colors::Magenta
constexpr int32 UE::StateTree::MaxExpressionIndent = 4
const STATETREEMODULE_API FColor UE::StateTree::Colors::Orange
const STATETREEMODULE_API FColor UE::StateTree::Colors::Purple
const STATETREEMODULE_API FColor UE::StateTree::Colors::Red
const STATETREEMODULE_API FColor UE::StateTree::Colors::Yellow
Macro Definition Documentation
UE_DEPRECATED
#define UE_DEPRECATED (Version, Message)
Macro for marking up deprecated code, functions and types.
This should be used as syntactic replacement for the [[deprecated]] attribute which provides a UE version number like the old DEPRECATED macro.
Features that are marked as deprecated are scheduled to be removed from the code base in a future release. If you are using a deprecated feature in your code, you should replace it before upgrading to the next release. See the Upgrade Notes in the release notes for the release in which the feature was marked deprecated.
Sample usage (note the slightly different syntax for classes and structures):
UE_DEPRECATED(5.xx, "MyFunction has been deprecated, please use MyNewFunction instead.")
void MyFunction();
UE_DEPRECATED(5.xx, "FMyType has been deprecated, please use MyNewType instead.")
typedef FThing FMyType;
using FMyAlias UE_DEPRECATED(5.xx, "FMyAlias has been deprecated, please use MyNewAlias instead.") = FThing;
UE_DEPRECATED(5.xx, "MyVariable has been deprecated and serves no purpose anymore")
int32 MyVariable;
namespace UE_DEPRECATED(5.xx, "MyNamespace has been renamed MyNewNamespace, please use this instead.") MyNamespace
{
}
Unfortunately, clang will complain that [the] "declaration of [an] anonymous class must
be a definition" for API types.  To work around this, first forward declare the type as
deprecated, then declare the type with the visibility macro.  Note that macros like
USTRUCT must immediately precede the the type declaration, not the forward declaration.
struct UE_DEPRECATED(5.xx, "FMyStruct has been deprecated and shall not be used anymore.") FMyStruct;
USTRUCT()
struct MODULE_API FMyStruct
{
};
class UE_DEPRECATED(5.xx, "FMyClass has been deprecated and shall not be used anymore.") FMyClass;
class MODULE_API FMyClass
{
};
enum class UE_DEPRECATED(5.xx, "EMyEnumeration has been deprecated, use EMyEnumeration instead.") EMyEnumeration
{
    Zero = 0,
    One UE_DEPRECATED(5.xx, "EMyEnumeration::One is not a valid enum entry anymore, please use another one.") = 1,
    Two = 2
};
Unfortunately, VC++ will complain about using member functions and fields from deprecated
class/structs even for class/struct implementation e.g.:
class UE_DEPRECATED(5.xx, "DeprecatedClass has been deprecated and shall not be used anymore.") DeprecatedClass
{
public:
    DeprecatedClass() {}
    float GetMyFloat()
    {
        return MyFloat; // This line will cause warning that deprecated field is used.
    }
private:
    float MyFloat;
};
To get rid of this warning, place all code not called in class implementation in non-deprecated
base class and deprecate only derived one. This may force you to change some access specifiers
from private to protected, e.g.:
class DeprecatedClass_Base_DEPRECATED
{
protected: // MyFloat is protected now, so DeprecatedClass has access to it.
    float MyFloat;
};
class UE_DEPRECATED(5.xx, "DeprecatedClass has been deprecated and shall not be used anymore.") DeprecatedClass : DeprecatedClass_Base_DEPRECATED
{
public:
    DeprecatedClass() {}
    float GetMyFloat()
    {
        return MyFloat;
    }
};
template <typename T>
class UE_DEPRECATED(5.xx, "DeprecatedClassTemplate has been deprecated and shall not be used anymore.") DeprecatedClassTemplate
{
};
template <typename T>
UE_DEPRECATED(5.xx, "DeprecatedFunctionTemplate has been deprecated and shall not be used anymore.")
void DeprecatedFunctionTemplate()
{
}
Parameters
Version The release number in which the feature was marked deprecated. Note: 'all', as in UE_DEPRECATED(all, ...), can be used for reflected code which has to stick around forever and is marked with meta-data like DeprecatedFunction or DeprecatedProperty. It indicates that the deprecation grace period is now over but that this property/function will remain deprecated for all time.
Message A message containing upgrade notes.
Definition at line 299 of file CoreMiscDefines.h.
WITH_STATETREE_DEBUG
#define WITH_STATETREE_DEBUG (!(UE_BUILD_SHIPPING || UE_BUILD_SHIPPING_WITH_EDITOR || UE_BUILD_TEST) && 1)
Definition at line 20 of file StateTreeTypes.h.
Function Documentation
DECLARE_LOG_CATEGORY_EXTERN()
STATETREEMODULE_API DECLARE_LOG_CATEGORY_EXTERN (LogStateTree , Warning , All)
References All, and Warning.
operator!=()
bool operator!= (const EStateTreeTransitionPriority Lhs, const EStateTreeTransitionPriority Rhs) inline
Definition at line 216 of file StateTreeTypes.h.
Referenced by DECLARE_DYNAMIC_DELEGATE_TwoParams(), DECLARE_STATS_GROUP(), ENUM_CLASS_FLAGS(), MS_ALIGN(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), and USTRUCT().
operator<()
UENUM() enum class EStateTreeStateType UENUM() enum class EStateTreeStateSelectionBehavior UENUM() enum class EStateTreeTransitionTrigger ENUM_CLASS_FLAGS(EStateTreeTransitionTrigger) UENUM() enum class EStateTreeTransitionPriority bool operator< (const EStateTreeTransitionPriority Lhs, const EStateTreeTransitionPriority Rhs) inline
Transitions trigger.
Transition priority. When multiple transitions trigger at the same time, the first transition of highest priority is selected.
Definition at line 211 of file StateTreeTypes.h.
Referenced by DECLARE_MULTICAST_DELEGATE_OneParam(), DECLARE_STATS_GROUP(), UE_DEPRECATED(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), and USTRUCT().
operator<=()
bool operator<= (const EStateTreeTransitionPriority Lhs, const EStateTreeTransitionPriority Rhs) inline
Definition at line 213 of file StateTreeTypes.h.
operator==()
bool operator== (const EStateTreeTransitionPriority Lhs, const EStateTreeTransitionPriority Rhs) inline
Definition at line 215 of file StateTreeTypes.h.
operator>()
bool operator> (const EStateTreeTransitionPriority Lhs, const EStateTreeTransitionPriority Rhs) inline
Definition at line 212 of file StateTreeTypes.h.
Referenced by USTRUCT(), and USTRUCT().
operator>=()
bool operator>= (const EStateTreeTransitionPriority Lhs, const EStateTreeTransitionPriority Rhs) inline
Definition at line 214 of file StateTreeTypes.h.
USTRUCT()
USTRUCT ()
Handle to a StateTree state.
Link to another state in StateTree.
StateTree struct ref allows to get a reference/pointer to a specified type via property binding.
Pair of transition id and its associated compact transition index created at compilation.
Pair of node id and its associated node index created at compilation.
Pair of state guid and its associated state handle created at compilation.
Runtime representation of a StateTree state.
Runtime representation of a StateTree frame.
Runtime representation of a StateTree transition.
Fallback behavior indicating what to do after failing to select a state.
Time duration with random variance.
Handle to a StateTree data.
Stored compactly as two uint16s, which gives time range of about 650 seconds. The variance is symmetric (+-) around the specified duration.
Runtime representation of an event description.
It is useful for referencing larger properties to avoid copies of the data, or to be able to write to a bounds property.
The expected type of the reference should be set in "BaseStruct" meta tag.
Example:
USTRUCT() struct FAwesomeTaskInstanceData { GENERATED_BODY()
UPROPERTY(VisibleAnywhere, Category = Input, meta = (BaseStruct = "/Script/AwesomeModule.AwesomeData")) FStateTreeStructRef Data; };
if (const FAwesomeData* Awesome = InstanceData.Data.GetPtr<FAwesomeData>()) { ... }
Returns
true if the given index can be represented by the type.
Reset duration to empty.
Sets the time duration with random variance.
Returns
the fixed duration.
the maximum random variance.
True of the duration is empty (always returns 0).
Returns random duration around Duration, varied by +-RandomVariation.
Event Payload Struct.
Event Tag.
Returns true if describes an event correctly.
Returns true if described events is a subset of events described by another EventDesc.
Returns true provided event matches description.
Returns
True if the transition has delay.
Event Description
Delegate dispatcher the transition is waiting for.
Index to first condition to test
Target state of the transition
Transition delay.
Fallback of the transition if it fails to select the target state
Number of conditions to test.
Indicates if the transition is enabled and should be considered.
If set to true, the required event is consumed (later state selection cannot react to it) if state selection can be made.
The root state of the frame (e.g. Root state or a subtree).
The max number of masks needed by the frame. It is the worst case of all the possible active state combinations for the frame. It includes the global tasks.
Returns
Index to the next sibling state.
True if the state has any child states
True if the state has any tasks that need ticking.
True if the state has any tasks that ticks.
True if the state has any transitions that need ticking.
A state can complete with Stopped, Succeeded, and Failed. The state can contain transitions that trigger on any completes, or only if the state succeeded, or only if the state failed.
Parameters
bSucceeded Whenever the state completion succeeded.
bFailed Whenever the state completion failed.
Returns
True if the state has any transitions that tick on completion.
Description of an event required to enter the state.
Name of the State
GameplayTag describing the State
Linked state handle if the state type is linked state.
Parent state handle, invalid if root state.
Index to first child state
Index one past the last child state.
Index to first state enter condition
Index to first state utility consideration
Index to first transition
Index to first task
Index to state instance data.
Weight used to scale the normalized final utility score for this state
Tick rate in seconds the state tasks and transitions should tick If set the state cannot sleep. Must be greater than or equal to 0.
Mask used to test the tasks completion.
Index in the mask buffer used by the state. CompletionTasksMaskBufferIndex = (Final Task Bit) / (size of mask:32)
Offset, in bits, of the first flag inside the mask. Used to access the bit from the state task index. CompletionTasksMaskBitsOffset = (Final Task Bit) % (size of mask:32)
How the tasks control the completion of the state.
Number of enter conditions
Number of utility considerations
Number of transitions
Number of tasks
Number of enabled tasks todo: this should be removed once we finished only compiling enabled elements for StateTree Compiler
Number of instance data
Distance to root state.
Type of the state
What to do when the state is considered for selection.
True if the state contains tasks that should be called during transition handling.
True if the state contains conditions which require call to enter/completed/exit state.
True if any task has bShouldCallTick.
True if any task has bShouldCallTickOnlyOnEvents. No effect if bHasTickTasks is true.
True if any state tasks request a tick every frame.
True if any state tasks request a tick every frame but only if there are events. No effect if bCachedRequestTick is true.
True if the state contains transitions with tick trigger.
True if the state contains transitions with event trigger.
True if the state contains transitions with delegate trigger.
True if the state contains transitions with completed trigger.
True if the state contains transitions with Succeeded trigger.
True if the state contains transitions with Succeeded trigger.
Should state's required event and enter conditions be evaluated when transition leads directly to it's child.
True if the state is Enabled (i.e. not explicitly marked as disabled).
If set to true, the required event is consumed (later state selection cannot react to it) if state selection can be made.
If set to true, the state has a custom tick rate.
Returns
true if the reference is valid (safe to use the reference getters).
Sets the struct ref (used by property copy)
Returns const reference to the struct, this getter assumes that all data is valid.
Returns const pointer to the struct, or nullptr if cast is not valid.
Returns mutable reference to the struct, this getter assumes that all data is valid.
Returns mutable pointer to the struct, or nullptr if cast is not valid.
Returns
Struct describing the data type.
Handle of the linked state.
Fallback of the transition if it fails to select the target state
Definition at line 219 of file StateTreeTypes.h.
References BlueprintType, check, Failed, FORCEINLINE, GENERATED_BODY, GetTypeHash(), Handle, INDEX_NONE, Invalid, IsValid(), MAX_uint16, operator!=(), operator==(), Root, Succeeded, and UPROPERTY.