Unreal Engine 5.6 C++ API: Runtime/Core/Public/Containers/StringConv.h File Reference
StringConv.h File Reference
#include "CoreTypes.h"
#include "Misc/AssertionMacros.h"
#include "Containers/ContainerAllocationPolicies.h"
#include "Containers/Array.h"
#include "Misc/CString.h"
#include "Templates/IsArray.h"
#include "Templates/UnrealTemplate.h"
#include "Templates/UnrealTypeTraits.h"
#include "Traits/ElementType.h"
#include "Traits/IsCharEncodingCompatibleWith.h"
#include "Traits/IsContiguousContainer.h"
#include <type_traits>
Data Structures
class FTCHARToUTF8_Convert
class FUTF8ToTCHAR_Convert
struct TElementType< TStringConversion< Converter, DefaultConversionSize > >
struct TElementType< TStringPointer< FromType, ToType > >
struct TIsContiguousContainer< TStringConversion< Converter, DefaultConversionSize > >
struct TIsContiguousContainer< TStringPointer< FromType, ToType > >
class TPassthruPointer< T >
class TStringConversion< Converter, DefaultConversionSize >
Class takes one type of string and converts it to another.
class TStringConvert< From, To >
class TStringPassthru< ToType, FromType, DefaultConversionSize >
This class is returned by StringPassthru and is not intended to be used directly.
class TStringPointer< InFromType, InToType >
Class takes one type of string and and stores it as-is.
class TUTF16ToUTF32_Convert< InFromType, InToType >
class TUTF32ToUTF16_Convert< InFromType, InToType >
struct UE::Core::Private::FCountingOutputIterator
This is a basic object which counts how many times it has been incremented.
struct UE::Core::Private::FFromStrCast
class UE::Core::Private::FTCHARToUTF8_Convert
Namespaces
namespace StringConv
namespace UE
Utility functions for applying transformations to meshes.
namespace UE::Core
namespace UE::Core::Private
TAdderRef and TAdderReserverRef are type-erasing adapters that allow a function to add to (and reserve) a container without the function knowing about the specific type of the container.
Macros
#define ANSI_TO_TCHAR(str)
#define DEFAULT_STRING_CONVERSION_SIZE 128u
#define TCHAR_TO_ANSI(str)
#define TCHAR_TO_UTF16(str)
#define TCHAR_TO_UTF32(str)
#define TCHAR_TO_UTF8(str)
#define TCHAR_TO_WCHAR(str)
#define UTF16_TO_TCHAR(str)
#define UTF32_TO_TCHAR(str)
#define UTF8_TO_TCHAR(str)
#define WCHAR_TO_TCHAR(str)
Typedefs
typedef TStringPointer< TCHAR, UTF16CHAR > FTCHARToUTF16
typedef TStringConversion< TUTF16ToUTF32_Convert< TCHAR, UTF32CHAR > > FTCHARToUTF32
typedef TStringPointer< TCHAR, wchar_t > FTCHARToWChar
typedef TStringPointer< UTF16CHAR, TCHAR > FUTF16ToTCHAR
typedef TStringConversion< TUTF32ToUTF16_Convert< UTF32CHAR, TCHAR > > FUTF32ToTCHAR
typedef TStringPointer< wchar_t, TCHAR > FWCharToTCHAR
Enumerations
enum class UE::Core::Private::ENullTerminatedString { UE::Core::Private::No = 0 , UE::Core::Private::Yes = 1 }
Functions
template<typename To, typename From>
FORCEINLINE To CharCast (From Ch)
Casts one fixed-width char type into another.
FORCEINLINE void StringConv::DecodeSurrogate (const uint32 Codepoint, uint16 &OutHighSurrogate, uint16 &OutLowSurrogate)
FORCEINLINE uint32 StringConv::EncodeSurrogate (const uint16 HighSurrogate, const uint16 LowSurrogate)
template<typename Converter, int32 DefaultConversionSize>
auto GetData (const TStringConversion< Converter, DefaultConversionSize > &Conversion) -> decltype(Conversion.Get())
template<typename FromType, typename ToType>
auto GetData (const TStringPointer< FromType, ToType > &Pointer) -> decltype(Pointer.Get())
template<typename ConverterType>
FUnused StringConv::GetLegacyFromType (...)
template<typename ConverterType>
ConverterType::LegacyFromType StringConv::GetLegacyFromType (typename ConverterType::LegacyFromType *)
template<typename Converter, int32 DefaultConversionSize>
auto GetNum (const TStringConversion< Converter, DefaultConversionSize > &Conversion) -> decltype(Conversion.Length())
template<typename FromType, typename ToType>
auto GetNum (const TStringPointer< FromType, ToType > &Pointer) -> decltype(Pointer.Length())
template<typename AllocatorType>
FORCEINLINE void StringConv::InlineCombineSurrogates_Array (TArray< TCHAR, AllocatorType > &StrBuffer)
Inline combine any UTF-16 surrogate pairs in the given null-terminated TCHAR array.
template<typename CharType>
FORCEINLINE int32 StringConv::InlineCombineSurrogates_Buffer (CharType *StrBuffer, int32 StrLen)
Inline combine any UTF-16 surrogate pairs in the given null-terminated character buffer, returning the updated length.
FORCEINLINE bool StringConv::IsEncodedSurrogate (const uint32 Codepoint)
Is the provided Codepoint outside of the range of the basic multilingual plane, but within the valid range of UTF8/16?
FORCEINLINE bool StringConv::IsHighSurrogate (const uint32 Codepoint)
Is the provided Codepoint within the range of the high-surrogates?
FORCEINLINE bool StringConv::IsLowSurrogate (const uint32 Codepoint)
Is the provided Codepoint within the range of the low-surrogates?
FORCEINLINE bool StringConv::IsValidCodepoint (const uint32 Codepoint)
Is the provided Codepoint within the range of valid codepoints?
template<typename To, int32 DefaultConversionSize = 128u, typename From>
FORCEINLINE auto StrCast (const From *Str, int32 Len)
Creates an object which acts as a source of a given string type.
template<typename To, int32 DefaultConversionSize = 128u, typename From>
FORCEINLINE auto StringCast (const From *Str)
StringCast example usage:
template<typename To, int32 DefaultConversionSize = 128u, typename From>
FORCEINLINE auto StringCast (const From *Str, int32 Len)
Creates an object which acts as a source of a given string type.
template<typename From, typename To, int32 DefaultConversionSize = 128u>
FORCEINLINE auto StringMemoryPassthru (To *Buffer, int32 BufferSize, int32 SourceLength)
Allows the efficient conversion of strings by means of a temporary memory buffer only when necessary.
template<typename ToType, typename FromType>
FORCEINLINE TArray< ToType > StringToArray (const FromType *Src, int32 SrcLen)
template<typename ToType, typename FromType>
FORCEINLINE TArray< ToType > StringToArray (const FromType *Str)
Macro Definition Documentation
ANSI_TO_TCHAR
#define ANSI_TO_TCHAR (str)
Value:
/*UE_DEPRECATED_MACRO(5.xx, "ANSI_TO_TCHAR(Ptr) is deprecated, please use StringCast<TCHAR>(PtrToAnsiChar) instead.")*/ (TCHAR*)StringCast<TCHAR>(static_cast<const ANSICHAR*>(str)).Get()
Definition at line 1020 of file StringConv.h.
Referenced by FGPUDriverHelper::GetVendorSectionName(), and FPixelStreamingCreateSessionDescriptionObserver::OnFailure().
DEFAULT_STRING_CONVERSION_SIZE
#define DEFAULT_STRING_CONVERSION_SIZE 128u
Definition at line 21 of file StringConv.h.
TCHAR_TO_ANSI
#define TCHAR_TO_ANSI (str)
Value:
/*UE_DEPRECATED_MACRO(5.xx, "TCHAR_TO_ANSI(Ptr) is deprecated, please use StringCast<ANSICHAR>(PtrToTChar) instead.")*/ (ANSICHAR*)StringCast<ANSICHAR>(static_cast<const TCHAR*>(str)).Get()
Definition at line 1019 of file StringConv.h.
Referenced by FMD5::HashAnsiString(), FRunnableThreadApple::PreRun(), TInteractiveToolCommands< CommandContextType >::RegisterUIToolCommand(), and WriteCustomReport().
TCHAR_TO_UTF16
#define TCHAR_TO_UTF16 (str)
Value:
(UTF16CHAR*)(str)
Definition at line 1063 of file StringConv.h.
TCHAR_TO_UTF32
#define TCHAR_TO_UTF32 (str)
Value:
(UTF32CHAR*)FTCHARToUTF32((const TCHAR*)str).Get()
Definition at line 1068 of file StringConv.h.
TCHAR_TO_UTF8
#define TCHAR_TO_UTF8 (str)
Value:
/*UE_DEPRECATED_MACRO(5.xx, "TCHAR_TO_UTF8(Ptr) is deprecated, please use StringCast<UTF8CHAR>(PtrToTChar) instead.")*/ (ANSICHAR*)FTCHARToUTF8((const TCHAR*)str).Get()
Definition at line 1021 of file StringConv.h.
Referenced by CaptureExpressionsAndValues(), and FIOSCommandLineHelper::TryReadCommandLineFile().
TCHAR_TO_WCHAR
#define TCHAR_TO_WCHAR (str)
Value:
(wchar_t*)(str)
Definition at line 1092 of file StringConv.h.
UTF16_TO_TCHAR
#define UTF16_TO_TCHAR (str)
Value:
(TCHAR*)(str)
Definition at line 1064 of file StringConv.h.
UTF32_TO_TCHAR
#define UTF32_TO_TCHAR (str)
Value:
(TCHAR*)FUTF32ToTCHAR((const UTF32CHAR*)str).Get()
Definition at line 1069 of file StringConv.h.
UTF8_TO_TCHAR
#define UTF8_TO_TCHAR (str)
Value:
/*UE_DEPRECATED_MACRO(5.xx, "UTF8_TO_TCHAR(Ptr) is deprecated, please use StringCast<TCHAR>(PtrToUTF8Char) instead.")*/ (TCHAR*)FUTF8ToTCHAR((const ANSICHAR*)str).Get()
Definition at line 1022 of file StringConv.h.
Referenced by UE::UnifiedError::FTextFormatArgsPropertyExtractor::AddProperty(), UE::UnifiedError::FTextFormatArgsPropertyExtractor::AddProperty(), UE::UnifiedError::FTextFormatArgsPropertyExtractor::AddProperty(), UE::UnifiedError::FTextFormatArgsPropertyExtractor::AddProperty(), UE::UnifiedError::FTextFormatArgsPropertyExtractor::AddProperty(), UE::UnifiedError::FTextFormatArgsPropertyExtractor::AddProperty(), UE::UnifiedError::FTextFormatArgsPropertyExtractor::AddProperty(), UnFbx::FFbxImporter::GetFileUnitSystem(), UnFbx::FFbxImporter::FFbxMaterial::GetName(), FPixelStreamingSetSessionDescriptionObserver::OnFailure(), and FIOSCommandLineHelper::TryReadCommandLineFile().
WCHAR_TO_TCHAR
#define WCHAR_TO_TCHAR (str)
Value:
(TCHAR*)(str)
Definition at line 1093 of file StringConv.h.
Typedef Documentation
FTCHARToUTF16
typedef TStringPointer<TCHAR, UTF16CHAR> FTCHARToUTF16
Definition at line 1061 of file StringConv.h.
FTCHARToUTF32
typedef TStringConversion<TUTF16ToUTF32_Convert<TCHAR, UTF32CHAR> > FTCHARToUTF32
Definition at line 1066 of file StringConv.h.
FTCHARToWChar
typedef TStringPointer<TCHAR, wchar_t> FTCHARToWChar
Definition at line 1090 of file StringConv.h.
FUTF16ToTCHAR
typedef TStringPointer<UTF16CHAR, TCHAR> FUTF16ToTCHAR
Definition at line 1062 of file StringConv.h.
FUTF32ToTCHAR
typedef TStringConversion<TUTF32ToUTF16_Convert<UTF32CHAR, TCHAR> > FUTF32ToTCHAR
Definition at line 1067 of file StringConv.h.
FWCharToTCHAR
typedef TStringPointer<wchar_t, TCHAR> FWCharToTCHAR
Definition at line 1091 of file StringConv.h.
Function Documentation
CharCast()
template<typename To, typename From> FORCEINLINE To CharCast (From Ch) nodiscard
Casts one fixed-width char type into another.
Parameters
Ch The character to convert.
Returns
The converted character.
Definition at line 1227 of file StringConv.h.
References FGenericPlatformString::Convert(), and FORCEINLINE.
GetData() [1/2]
template<typename Converter, int32 DefaultConversionSize> auto GetData (const TStringConversion< Converter, DefaultConversionSize > & Conversion) -> decltype(Conversion.Get()) inline nodiscard
Definition at line 802 of file StringConv.h.
Referenced by FAnimSequenceDecompressionContext::FAnimSequenceDecompressionContext(), FCbFieldView::FCbFieldView(), Audio::FConstantQFrame::FConstantQFrame(), UE::MovieScene::FCustomAccessorView::FCustomAccessorView(), UE::FDerivedDataIoOptions::FDerivedDataIoOptions(), FFrame::FFrame(), UE::MovieScene::FPropertyComponentArrayView::FPropertyComponentArrayView(), FResourceArrayUploadArrayView::FResourceArrayUploadArrayView(), FResourceBulkDataArrayView::FResourceBulkDataArrayView(), UE::Sequencer::FViewModelVariantIterator::FViewModelVariantIterator(), UE::Sequencer::FViewModelVariantIterator::FViewModelVariantIterator(), TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::TConstReverseIterator::TConstReverseIterator(), TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::TReverseIterator::TReverseIterator(), TStringConversion< TUTF16ToUTF32_Convert< TCHAR, UTF32CHAR > >::TStringConversion(), TStringPointer< TCHAR, UTF16CHAR >::TStringPointer(), TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::Append(), TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::Assign(), Algo::BinarySearch(), Algo::BinarySearchBy(), Algo::Private::Compare(), TStringView< CharType >::Compare(), UE::Graph::ConvertToSingleBufferGraph(), ENUM_CLASS_FLAGS(), Algo::FindLast(), Algo::FindLastBy(), Algo::FindLastByPredicate(), Algo::FindSequence(), UE::SharedBuffer::Private::TBufferOwnerDeleteFunction< DeleteFunctionType >::FreeBuffer(), TStaticArray< int32, MAX_PHYSICS_FIELD_TARGETS, 16 >::GetData(), UE::Core::ArrayView::Private::GetDataHelper(), UE::Core::Private::GetDataHelper(), UE::AnimNext::TReferencePose< FDefaultAllocator, FDefaultSetAllocator >::GetLODBoneIndexToMeshBoneIndexMap(), UE::AnimNext::TReferencePose< FDefaultAllocator, FDefaultSetAllocator >::GetLODBoneIndexToParentLODBoneIndexMap(), UE::AnimNext::TReferencePose< FDefaultAllocator, FDefaultSetAllocator >::GetLODBoneIndexToSkeletonBoneIndexMap(), UE::Core::ArrayView::Private::GetReinterpretedDataHelper(), FSharedBuffer::GetView(), FAsciiSet::HasOnly(), Algo::Heapify(), Algo::Heapify(), Algo::HeapifyBy(), Algo::HeapifyBy(), Algo::HeapSort(), Algo::HeapSort(), Algo::HeapSortBy(), Algo::HeapSortBy(), Algo::Includes(), Algo::Includes(), Algo::IncludesBy(), Algo::IncludesBy(), AlgoImpl::IndexOfBy(), AlgoImpl::IndexOfByPredicate(), Algo::IntroSort(), Algo::IntroSort(), Algo::IntroSortBy(), Algo::IntroSortBy(), Algo::IsHeap(), Algo::IsHeap(), Algo::IsHeapBy(), Algo::IsHeapBy(), Algo::IsSorted(), Algo::IsSorted(), Algo::IsSortedBy(), Algo::IsSortedBy(), Algo::LegacySort(), Algo::LegacySort(), Algo::LegacySortBy(), Algo::LegacySortBy(), Algo::LevenshteinDistance(), Algo::LowerBound(), Algo::LowerBound(), Algo::LowerBoundBy(), Algo::LowerBoundBy(), MakeConstStridedView(), MakeConstStridedView(), MakeConstStridedView(), MakeConstStridedViewOfBase(), MakeMemoryView(), MakeMemoryView(), MakeStridedView(), MakeStridedView(), MakeStridedView(), MakeStridedViewOfBase(), TStringView< CharType >::Mid(), Algo::Private::Mismatch(), RangedForIteratorType< FAnimNextTraitEventPtr >::operator=(), operator==(), Algo::Partition(), TStringView< CharType >::PrivateCompare(), TStringView< CharType >::PrivateEquals(), Algo::RandomShuffle(), FAnimSequenceDecompressionContext::RefPoses(), Algo::RemoveIf(), Algo::Rotate(), FAsciiSet::Scan(), Algo::StableRemoveIf(), Algo::StableSort(), Algo::StableSort(), Algo::StableSortBy(), Algo::StableSortBy(), UE::Core::Private::StringViewGetData(), FAsyncAddPrimitiveQueue::Tick(), FScopedSkeletalMeshRenderData::UE_DEPRECATED(), TMeshAttributeArrayBase< AttributeType >::UE_DEPRECATED(), Algo::UpperBound(), Algo::UpperBound(), Algo::UpperBoundBy(), Algo::UpperBoundBy(), and USTRUCT().
GetData() [2/2]
template<typename FromType, typename ToType> auto GetData (const TStringPointer< FromType, ToType > & Pointer) -> decltype(Pointer.Get()) inline nodiscard
Definition at line 943 of file StringConv.h.
References Pointer.
GetNum() [1/2]
template<typename Converter, int32 DefaultConversionSize> auto GetNum (const TStringConversion< Converter, DefaultConversionSize > & Conversion) -> decltype(Conversion.Length()) inline nodiscard
Definition at line 808 of file StringConv.h.
Referenced by TArrayView< FTransform >::TArrayView(), TArrayView< FTransform >::TArrayView(), TArrayView< FTransform >::TArrayView(), TStringConversion< TUTF16ToUTF32_Convert< TCHAR, UTF32CHAR > >::TStringConversion(), TStringPointer< TCHAR, UTF16CHAR >::TStringPointer(), UE::Tasks::Private::FTaskBase::AddPrerequisites(), RangedForIteratorType< FAnimNextTraitEventPtr >::Append(), TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::Append(), TPagedArray< InElementType, InPageSizeInBytes, InAllocatorType >::Assign(), Algo::BinarySearch(), Algo::BinarySearchBy(), Algo::Private::Compare(), UE::Graph::ConvertToGraph(), UE::Graph::ConvertToSingleBufferGraph(), Algo::FindLast(), Algo::FindLastBy(), Algo::FindLastByPredicate(), Algo::FindSequence(), FCompositeBuffer::GetBufferCount(), UE::Core::ArrayView::Private::GetReinterpretedDataHelper(), FAsciiSet::HasOnly(), Algo::Heapify(), Algo::Heapify(), Algo::HeapifyBy(), Algo::HeapifyBy(), Algo::HeapSort(), Algo::HeapSort(), Algo::HeapSortBy(), Algo::HeapSortBy(), Algo::Includes(), Algo::Includes(), Algo::IncludesBy(), Algo::IncludesBy(), AlgoImpl::IndexOfBy(), AlgoImpl::IndexOfByPredicate(), Algo::IntroSort(), Algo::IntroSort(), Algo::IntroSortBy(), Algo::IntroSortBy(), Algo::IsHeap(), Algo::IsHeap(), Algo::IsHeapBy(), Algo::IsHeapBy(), Algo::IsSorted(), Algo::IsSorted(), Algo::IsSortedBy(), Algo::IsSortedBy(), AlgoImpl::KahnTopologicalSort_CreateWorkingGraph(), Algo::LegacySort(), Algo::LegacySort(), Algo::LegacySortBy(), Algo::LegacySortBy(), Algo::LevenshteinDistance(), Algo::LowerBound(), Algo::LowerBound(), Algo::LowerBoundBy(), Algo::LowerBoundBy(), MakeConstStridedView(), MakeConstStridedView(), MakeConstStridedView(), MakeConstStridedViewOfBase(), MakeMemoryView(), MakeMemoryView(), MakeStridedView(), MakeStridedView(), MakeStridedView(), MakeStridedViewOfBase(), Algo::Private::Mismatch(), operator==(), Algo::Partition(), Algo::RandomShuffle(), Algo::RemoveIf(), Algo::Rotate(), FAsciiSet::Scan(), Algo::StableRemoveIf(), Algo::StableSort(), Algo::StableSort(), Algo::StableSortBy(), Algo::StableSortBy(), Algo::UpperBound(), Algo::UpperBound(), Algo::UpperBoundBy(), Algo::UpperBoundBy(), and USTRUCT().
GetNum() [2/2]
template<typename FromType, typename ToType> auto GetNum (const TStringPointer< FromType, ToType > & Pointer) -> decltype(Pointer.Length()) inline nodiscard
Definition at line 949 of file StringConv.h.
References Pointer.
StrCast()
template<typename To, int32 DefaultConversionSize = 128u, typename From> FORCEINLINE auto StrCast (const From * Str, int32 Len) nodiscard
Creates an object which acts as a source of a given string type.
See example above.
This is intended as the long-term replacement for StringCast, which doesn't cope well with zeros mid-string, which it can interpret as a null-terminators and give surprising behavior.
StrCast expects correctly-typed strings. If a cast is attempted with a char* or ANSICHAR*, and the string contains characters that are non-ASCII, including UTF-8 code units outside of the 7-bit ASCII range, then those values will fail to convert and a bogus char will be written in their place.
If a conversion from UTF-8 is desired, the pointer should be cast to UTF8CHAR* before being passed to StrCast.
Similarly, doing a StrCast<char> or StrCast<ANSICHAR> on a Unicode string will only successfully convert Unicode characters which already lie in the ASCII range. For converting to UTF-8, StrCast<UTF8CHAR> should be used.
The source string must not be modified or destroyed until after the result of this function has been destroyed.
Parameters
Str A pointer to the start of the string to convert. Must be non-null if Len is non-zero.
Len The number of From elements in Str. Must be non-negative.
Definition at line 1207 of file StringConv.h.
References FORCEINLINE, and TIsCharEncodingCompatibleWith_V.
StringCast() [1/2]
template<typename To, int32 DefaultConversionSize = 128u, typename From> FORCEINLINE auto StringCast (const From * Str) nodiscard
StringCast example usage:
void Func(const FString& Str, const TCHAR* MediumLong, FStringView MediumLongSV) { // Basic version auto Src = StringCast<ANSICHAR>(<em>Str); const ANSICHAR Ptr = Src.Get(); // Ptr is a pointer to an ANSICHAR representing the potentially-converted string data. // Avoid calling strlen auto NoStrlenString = StringCast<ANSICHAR>(MediumLongSV.GetData(), MediumLongSV.Len()); // Specify the static allocation size when maximum length is known auto NoAllocSrc = StringCast<ANSICHAR, 1024>(MediumLong); // Avoid calling strlen and also specify the allocation size auto NoAllocNoStrlenSrc = StringCast<ANSICHAR, 1024>(MediumLongSV.GetData(), MediumLongSV.Len()); } Creates an object which acts as a source of a given string type. See example above.
StringCast expects correctly-typed strings. If a cast is attempted with a char* or ANSICHAR*, and the string contains characters that are non-ASCII, including UTF-8 code units outside of the 7-bit ASCII range, then those values will fail to convert and a bogus char will be written in their place.
If a conversion from UTF-8 is desired, the pointer should be cast to UTF8CHAR* before being passed to StringCast.
Similarly, doing a StringCast<char> or StringCast<ANSICHAR> on a Unicode string will only successfully convert Unicode characters which already lie in the ASCII range. For converting to UTF-8, StringCast<UTF8CHAR> should be used.
The source string must not be modified or destroyed until after the result of this function has been destroyed.
Parameters
Str The null-terminated source string to convert.
Definition at line 1136 of file StringConv.h.
References FORCEINLINE, and TIsCharEncodingCompatibleWith_V.
Referenced by FPlatformFileOpenLog::AddLabelToOpenLog(), FPlatformFileOpenLog::AddToOpenLog(), UE::MovieScene::FPropertyRegistry::DefinePropertyImpl(), FNetworkPredictionDriverBase< ModelDef >::LogPhysicsState(), FNetworkPredictionDriverBase< ModelDef >::LogPhysicsState(), FNetworkPredictionDriverBase< ModelDef >::LogUserState(), and FNetworkPredictionDriverBase< ModelDef >::LogUserStates().
StringCast() [2/2]
template<typename To, int32 DefaultConversionSize = 128u, typename From> FORCEINLINE auto StringCast (const From * Str, int32 Len) nodiscard
Creates an object which acts as a source of a given string type.
See example above.
StringCast expects correctly-typed strings. If a cast is attempted with a char* or ANSICHAR*, and the string contains characters that are non-ASCII, including UTF-8 code units outside of the 7-bit ASCII range, then those values will fail to convert and a bogus char will be written in their place.
If a conversion from UTF-8 is desired, the pointer should be cast to UTF8CHAR* before being passed to StringCast.
Similarly, doing a StringCast<char> or StringCast<ANSICHAR> on a Unicode string will only successfully convert Unicode characters which already lie in the ASCII range. For converting to UTF-8, StringCast<UTF8CHAR> should be used.
The source string must not be modified or destroyed until after the result of this function has been destroyed.
Parameters
Str The source string to convert, not necessarily null-terminated.
Len The number of From elements in Str.
Definition at line 1170 of file StringConv.h.
References FORCEINLINE, and TIsCharEncodingCompatibleWith_V.
StringMemoryPassthru()
template<typename From, typename To, int32 DefaultConversionSize = 128u> FORCEINLINE auto StringMemoryPassthru (To * Buffer, int32 BufferSize, int32 SourceLength) nodiscard
Allows the efficient conversion of strings by means of a temporary memory buffer only when necessary.
Intended to be used when you have an API which populates a buffer with some string representation which is ultimately going to be stored in another representation, but where you don't want to do a conversion or create a temporary buffer for that string if it's not necessary.
Intended use:
// Populates the buffer Str with StrLen characters. void SomeAPI(APICharType* Str, int32 StrLen);
void Func(DestChar* Buffer, int32 BufferSize) { // Create a passthru. This takes the buffer (and its size) which will ultimately hold the string, as well as the length of the // string that's being converted, which must be known in advance. // An explicit template argument is also passed to indicate the character type of the source string. // Buffer must be correctly typed for the destination string type. auto Passthru = StringMemoryPassthru<APICharType>(Buffer, BufferSize, SourceLength);
// Passthru.Get() returns an APICharType buffer pointer which is guaranteed to be SourceLength characters in size. // It's possible, and in fact intended, for Get() to return the same pointer as Buffer if DestChar and APICharType are // compatible string types. If this is the case, SomeAPI will write directly into Buffer. If the string types are not // compatible, Get() will return a pointer to some temporary memory which allocated by and owned by the passthru. SomeAPI(Passthru.Get(), SourceLength);
// If the string types were not compatible, then the passthru used temporary storage, and we need to write that back to Buffer. // We do that with the Apply call. If the string types were compatible, then the data was already written to Buffer directly // and so Apply is a no-op. Passthru.Apply();
// Now Buffer holds the data output by SomeAPI, already converted if necessary. }
Definition at line 1336 of file StringConv.h.
References Buffer, check, FORCEINLINE, and TIsCharEncodingCompatibleWith_V.
StringToArray() [1/2]
template<typename ToType, typename FromType> FORCEINLINE TArray< ToType > StringToArray (const FromType * Src, int32 SrcLen) nodiscard
Definition at line 1350 of file StringConv.h.
References FGenericPlatformString::Convert(), FGenericPlatformString::ConvertedLength(), and FORCEINLINE.
Referenced by StringToArray().
StringToArray() [2/2]
template<typename ToType, typename FromType> FORCEINLINE TArray< ToType > StringToArray (const FromType * Str) nodiscard
Definition at line 1362 of file StringConv.h.
References FORCEINLINE, StringToArray(), and TCString< T >::Strlen().