Unreal Engine 5.6 C++ API: Runtime/Core/Public/Containers/StringView.h File Reference
StringView.h File Reference
#include "CoreTypes.h"
#include "Containers/StringFwd.h"
#include "HAL/UnrealMemory.h"
#include "Math/NumericLimits.h"
#include "Math/UnrealMathUtility.h"
#include "Misc/Crc.h"
#include "Misc/CString.h"
#include "Misc/ReverseIterate.h"
#include "String/Find.h"
#include "Templates/Requires.h"
#include "Templates/UnrealTemplate.h"
#include "Traits/ElementType.h"
#include "Traits/IsCharEncodingCompatibleWith.h"
#include "Traits/IsCharType.h"
#include "Traits/IsContiguousContainer.h"
#include <type_traits>
Data Structures
class TStringView< CharType >
A string view is a non-owning view of a range of characters.
Namespaces
namespace UE
Utility functions for applying transformations to meshes.
namespace UE::Core
namespace UE::Core::Private
TAdderRef and TAdderReserverRef are type-erasing adapters that allow a function to add to (and reserve) a container without the function knowing about the specific type of the container.
Macros
#define ANSITEXTVIEW(str)
#define TEXTVIEW(str)
#define UTF8TEXTVIEW(str)
#define WIDETEXTVIEW(str)
Functions
template<typename CharPtrOrRangeType, std::enable_if_t<!std::is_pointer_v< CharPtrOrRangeType >||TIsCharType_V< std::remove_pointer_t< CharPtrOrRangeType > > > * = nullptr>
constexpr auto MakeStringView (const CharPtrOrRangeType &CharPtrOrRange UE_LIFETIMEBOUND) -> decltype(TStringView(CharPtrOrRange))
template<typename CharType UE_REQUIRES>
constexpr auto MakeStringView (const CharType *CharPtr UE_LIFETIMEBOUND, int32 Size) -> decltype(TStringView(CharPtr, Size))
constexpr FAnsiStringView operator""_PrivateASV (const ANSICHAR *String, size_t Size)
constexpr FStringView operator""_PrivateSV (const TCHAR *String, size_t Size)
FUtf8StringView operator""_PrivateU8SV (const ANSICHAR *String, size_t Size)
constexpr FWideStringView operator""_PrivateWSV (const WIDECHAR *String, size_t Size)
template<typename CharType>
constexpr int32 UE::Core::Private::StringLength (const CharType *InString)
template<typename... ArgTypes>
constexpr auto UE::Core::Private::StringViewGetData (ArgTypes &&... Args) -> decltype(GetData(Forward< ArgTypes >(Args)...))
Allow GetData to called unqualified from a scope with its own overload of GetData.
template<typename CharRangeType>
TStringView (CharRangeType &&Range) -> TStringView< TElementType_T< CharRangeType > >
Macro Definition Documentation
ANSITEXTVIEW
#define ANSITEXTVIEW (str)
Value:
(str##_PrivateASV)
Definition at line 625 of file StringView.h.
Referenced by FShaderPreprocessOutput::ForEachLine(), UE::UnifiedError::StreamableManager::GatherPropertiesForError(), TErrorStructFeatures< T >::GetErrorContextTypeNameAsString(), TErrorStructFeatures< T >::GetErrorDetailsTypeNameAsString(), and SerializeForLog().
TEXTVIEW
#define TEXTVIEW (str)
Value:
TEXT(str##_PrivateSV)
Definition at line 623 of file StringView.h.
UTF8TEXTVIEW
#define UTF8TEXTVIEW (str)
Value:
(str##_PrivateU8SV)
Definition at line 627 of file StringView.h.
Referenced by UE::UnifiedError::StreamableManager::FStreamableManagerErrorDetails::GetErrorProperties().
WIDETEXTVIEW
#define WIDETEXTVIEW (str)
Value:
PREPROCESSOR_JOIN(WIDETEXT(str), _PrivateWSV)
Definition at line 626 of file StringView.h.
Function Documentation
MakeStringView() [1/2]
template<typename CharPtrOrRangeType, std::enable_if_t<!std::is_pointer_v< CharPtrOrRangeType >||TIsCharType_V< std::remove_pointer_t< CharPtrOrRangeType > > > * = nullptr> auto MakeStringView (const CharPtrOrRangeType &CharPtrOrRange UE_LIFETIMEBOUND) -> decltype(TStringView(CharPtrOrRange)) inline nodiscard constexpr
Definition at line 577 of file StringView.h.
References TStringView(), and UE_LIFETIMEBOUND.
Referenced by TStringBuilderBase< TCHAR >::Append(), TStringView< TCHAR >::Compare(), TStringView< TCHAR >::Equals(), UE::TSharedString< TCHAR >::GetTypeHash, UE::HashStringFNV1a(), UE::AnimNext::FConstExprUID::MakeFromString(), UE::AnimNext::FTraitInterfaceUID::MakeUID(), UE::AnimNext::FTraitUID::MakeUID(), UE::TSharedString< TCHAR >::operator<, operator<<(), and UE::TSharedString< TCHAR >::operator==.
MakeStringView() [2/2]
template<typename CharType UE_REQUIRES> auto MakeStringView (const CharType *CharPtr UE_LIFETIMEBOUND, int32 Size) -> decltype(TStringView(CharPtr, Size)) inline nodiscard constexpr
Definition at line 584 of file StringView.h.
References TSequenceHistory< HistorySize >::Size, TStringView(), and UE_LIFETIMEBOUND.
operator""_PrivateASV()
FAnsiStringView operator""_PrivateASV (const ANSICHAR * String, size_t Size) inline nodiscard constexpr
Definition at line 603 of file StringView.h.
References String, and TSequenceHistory< HistorySize >::Size.
operator""_PrivateSV()
FStringView operator""_PrivateSV (const TCHAR * String, size_t Size) inline nodiscard constexpr
Definition at line 597 of file StringView.h.
References String, and TSequenceHistory< HistorySize >::Size.
operator""_PrivateU8SV()
FUtf8StringView operator""_PrivateU8SV (const ANSICHAR * String, size_t Size) inline nodiscard
Definition at line 613 of file StringView.h.
References String, and TSequenceHistory< HistorySize >::Size.
operator""_PrivateWSV()
FWideStringView operator""_PrivateWSV (const WIDECHAR * String, size_t Size) inline nodiscard constexpr
Definition at line 608 of file StringView.h.
References String, and TSequenceHistory< HistorySize >::Size.
TStringView()
template<typename CharRangeType> TStringView (CharRangeType && Range) -> TStringView< TElementType_T< CharRangeType > >
References TIsCharType_V.
Referenced by MakeStringView(), and MakeStringView().