Unreal Engine 5.6 C++ API: FSlateFontKey Struct Reference
FSlateFontKey Struct Reference
#include "FontTypes.h"
Public Member Functions
FSlateFontKey (const FSlateFontInfo &InInfo, const FFontOutlineSettings &InFontOutlineSettings, const float InScale)
FORCEINLINE const FSlateFontInfo & GetFontInfo () const
FORCEINLINE const FFontOutlineSettings & GetFontOutlineSettings () const
FORCEINLINE float GetScale () const
bool IsIdenticalToForCaching (const FSlateFontKey &Other) const
Private Attributes
FSlateFontInfo FontInfo
uint32 KeyHash
FFontOutlineSettings OutlineSettings
float Scale
Friends
uint32 GetTypeHash (const FSlateFontKey &Key)
Detailed Description
Definition at line 21 of file FontTypes.h.
Constructor & Destructor Documentation
FSlateFontKey()
FSlateFontKey::FSlateFontKey (const FSlateFontInfo & InInfo, const FFontOutlineSettings & InFontOutlineSettings, const float InScale) inline
Definition at line 24 of file FontTypes.h.
References FontInfo, GetTypeHash, HashCombine(), KeyHash, OutlineSettings, and Scale.
Referenced by GetTypeHash, and IsIdenticalToForCaching().
Member Function Documentation
GetFontInfo()
FORCEINLINE const FSlateFontInfo & FSlateFontKey::GetFontInfo () const inline
Definition at line 35 of file FontTypes.h.
References FontInfo, and FORCEINLINE.
GetFontOutlineSettings()
FORCEINLINE const FFontOutlineSettings & FSlateFontKey::GetFontOutlineSettings () const inline
Definition at line 45 of file FontTypes.h.
References FORCEINLINE, and OutlineSettings.
GetScale()
FORCEINLINE float FSlateFontKey::GetScale () const inline
Definition at line 40 of file FontTypes.h.
References FORCEINLINE, and Scale.
IsIdenticalToForCaching()
bool FSlateFontKey::IsIdenticalToForCaching (const FSlateFontKey & Other) const inline
Definition at line 50 of file FontTypes.h.
References FSlateFontKey(), FontInfo, Other, OutlineSettings, and Scale.
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FSlateFontKey & Key) friend
Definition at line 57 of file FontTypes.h.
References FSlateFontKey(), and Key.
Referenced by FSlateFontKey().
Field Documentation
FontInfo
FSlateFontInfo FSlateFontKey::FontInfo private
Definition at line 63 of file FontTypes.h.
Referenced by FSlateFontKey(), GetFontInfo(), and IsIdenticalToForCaching().
KeyHash
uint32 FSlateFontKey::KeyHash private
Definition at line 66 of file FontTypes.h.
Referenced by FSlateFontKey().
OutlineSettings
FFontOutlineSettings FSlateFontKey::OutlineSettings private
Definition at line 64 of file FontTypes.h.
Referenced by FSlateFontKey(), GetFontOutlineSettings(), and IsIdenticalToForCaching().
Scale
float FSlateFontKey::Scale private
Definition at line 65 of file FontTypes.h.
Referenced by FSlateFontKey(), GetScale(), and IsIdenticalToForCaching().
The documentation for this struct was generated from the following file:
Runtime/SlateCore/Public/Fonts/FontTypes.h