Unreal Engine 5.6 C++ API: UE::AnimNext::FEvaluationVMStack Struct Reference
UE::AnimNext::FEvaluationVMStack Struct Reference final
#include "EvaluationVM.h"
Public Member Functions
FEvaluationVMStack ()=default
FEvaluationVMStack (const FEvaluationVMStack &)=delete
FEvaluationVMStack (FEvaluationVMStack &&)=default
ANIMNEXTANIMGRAPH_API ~FEvaluationVMStack ()
FEvaluationVMStack & operator= (const FEvaluationVMStack &)=delete
FEvaluationVMStack & operator= (FEvaluationVMStack &&)=default
Data Fields
FName Name
FEvaluationVMStackEntry * Top = nullptr
TFunction< void(void *)> TypeDestructor
uint32 TypeID = 0
Detailed Description
Definition at line 111 of file EvaluationVM.h.
Constructor & Destructor Documentation
FEvaluationVMStack() [1/3]
UE::AnimNext::FEvaluationVMStack::FEvaluationVMStack () default
Referenced by FEvaluationVMStack(), FEvaluationVMStack(), operator=(), and operator=().
FEvaluationVMStack() [2/3]
UE::AnimNext::FEvaluationVMStack::FEvaluationVMStack (const FEvaluationVMStack &) delete
References FEvaluationVMStack().
FEvaluationVMStack() [3/3]
UE::AnimNext::FEvaluationVMStack::FEvaluationVMStack (FEvaluationVMStack &&) default
References FEvaluationVMStack().
~FEvaluationVMStack()
ANIMNEXTANIMGRAPH_API UE::AnimNext::FEvaluationVMStack::~FEvaluationVMStack ()
References UE_API.
Member Function Documentation
operator=() [1/2]
FEvaluationVMStack & UE::AnimNext::FEvaluationVMStack::operator= (const FEvaluationVMStack &) delete
References FEvaluationVMStack().
operator=() [2/2]
FEvaluationVMStack & UE::AnimNext::FEvaluationVMStack::operator= (FEvaluationVMStack &&) default
References FEvaluationVMStack().
Field Documentation
Name
FName UE::AnimNext::FEvaluationVMStack::Name
Definition at line 114 of file EvaluationVM.h.
Top
FEvaluationVMStackEntry* UE::AnimNext::FEvaluationVMStack::Top = nullptr
Definition at line 121 of file EvaluationVM.h.
Referenced by UE::AnimNext::FEvaluationVM::PopValue(), and UE::AnimNext::FEvaluationVM::PushValue().
TypeDestructor
TFunction<void(void*)> UE::AnimNext::FEvaluationVMStack::TypeDestructor
Definition at line 125 of file EvaluationVM.h.
Referenced by UE::AnimNext::FEvaluationVM::PushValue().
TypeID
uint32 UE::AnimNext::FEvaluationVMStack::TypeID = 0
Definition at line 118 of file EvaluationVM.h.
Referenced by UE::AnimNext::FEvaluationVM::PushValue().
The documentation for this struct was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Experimental/AnimNextAnimGraph/Source/AnimNextAnimGraph/Public/EvaluationVM/EvaluationVM.h