Unreal Engine 5.6 C++ API: FNetworkVersion Struct Reference
FNetworkVersion Struct Reference
#include "NetworkVersion.h"
Public Member Functions
DECLARE_DELEGATE_RetVal (uint32, FGetLocalNetworkVersionOverride)
Called in GetLocalNetworkVersion if bound.
DECLARE_DELEGATE_RetVal (uint32, FGetReplayCompatibleChangeListOverride)
Called in GetReplayCompatibleChangelist if bound.
DECLARE_DELEGATE_RetVal_TwoParams (bool, FIsNetworkCompatibleOverride, uint32, uint32)
Called in IsNetworkCompatible if bound.
UE_DEPRECATED (5.2, "Please use GetCompatibleNetworkProtocolVersion instead.") static 1 uint32 GetEngineCompatibleNetworkProtocolVersion()
UE_DEPRECATED (5.2, "Please use GetCompatibleNetworkProtocolVersion instead.") static 1 uint32 GetGameCompatibleNetworkProtocolVersion()
UE_DEPRECATED (5.2, "Please use GetNetworkProtocolVersion instead.") static 1 uint32 GetEngineNetworkProtocolVersion()
UE_DEPRECATED (5.2, "Please use GetNetworkProtocolVersion instead.") static 1 uint32 GetGameNetworkProtocolVersion()
Static Public Member Functions
static bool AreNetworkRuntimeFeaturesCompatible (EEngineNetworkRuntimeFeatures LocalFeatures, EEngineNetworkRuntimeFeatures RemoteFeatures)
Compares if the connection's runtime features are compatible with each other.
static void DescribeNetworkRuntimeFeaturesBitset (EEngineNetworkRuntimeFeatures FeaturesBitflag, FStringBuilderBase &OutVerboseDescription)
Build and return a string describing the status of the the network runtime features bitflag.
static uint32 GetCompatibleNetworkProtocolVersion (const FGuid &VersionGuid)
static uint32 GetLocalNetworkVersion (bool AllowOverrideDelegate=true)
Generates a version number, that by default, is based on a checksum of the engine version + project name + project version string Game/project code can completely override what this value returns through the GetLocalNetworkVersionOverride delegate If called with AllowOverrideDelegate=false, we will not call the game project override.
static uint32 GetNetworkCompatibleChangelist ()
static const FCustomVersionContainer & GetNetworkCustomVersions ()
static uint32 GetNetworkProtocolVersion (const FGuid &VersionGuid)
static const FString & GetProjectVersion ()
Returns the project version used by networking.
static uint32 GetReplayCompatibleChangelist ()
static FNetworkReplayVersion GetReplayVersion ()
Generates a special struct that contains information to send to replay server.
static void InvalidateNetworkChecksum ()
Invalidates any cached network checksum and forces it to be recalculated on next request.
static bool IsNetworkCompatible (const uint32 LocalNetworkVersion, const uint32 RemoteNetworkVersion)
Determine if a connection is compatible with this instance.
static void RegisterNetworkCustomVersion (const FGuid &VersionGuid, int32 Version, int32 CompatibleVersion, const FName &FriendlyName)
static void SetGameCompatibleNetworkProtocolVersion (uint32 GameCompatibleNetworkProtocolVersion)
Sets the game compatible network protocol version used for networking and invalidate cached values.
static void SetGameNetworkProtocolVersion (uint32 GameNetworkProtocolVersion)
Sets the game network protocol version used for networking and invalidate cached values.
static void SetProjectVersion (const TCHAR *InVersion)
Sets the project version used for networking.
Static Public Attributes
static FGetLocalNetworkVersionOverride GetLocalNetworkVersionOverride
static FGetReplayCompatibleChangeListOverride GetReplayCompatibleChangeListOverride
static FIsNetworkCompatibleOverride IsNetworkCompatibleOverride
Protected Member Functions
UE_DEPRECATED (5.2, "Now storing this value in CompatibleNetworkCustomVersions, do not use directly.") static 1 uint32 EngineCompatibleNetworkProtocolVersion
UE_DEPRECATED (5.2, "Now storing this value in CompatibleNetworkCustomVersions, do not use directly.") static 1 uint32 GameCompatibleNetworkProtocolVersion
UE_DEPRECATED (5.2, "Now storing this value in NetworkCustomVersions, do not use directly.") static 1 uint32 EngineNetworkProtocolVersion
UE_DEPRECATED (5.2, "Now storing this value in NetworkCustomVersions, do not use directly.") static 1 uint32 GameNetworkProtocolVersion
Static Protected Member Functions
static FString & GetProjectVersion_Internal ()
Used to allow BP only projects to override network versions.
Static Protected Attributes
static bool bHasCachedNetworkChecksum
static bool bHasCachedReplayChecksum
static uint32 CachedNetworkChecksum
static uint32 CachedReplayChecksum
Detailed Description
Definition at line 52 of file NetworkVersion.h.
Member Function Documentation
AreNetworkRuntimeFeaturesCompatible()
bool FNetworkVersion::AreNetworkRuntimeFeaturesCompatible (EEngineNetworkRuntimeFeatures LocalFeatures, EEngineNetworkRuntimeFeatures RemoteFeatures) static
Compares if the connection's runtime features are compatible with each other.
References AreNetworkRuntimeFeaturesCompatible().
Referenced by AreNetworkRuntimeFeaturesCompatible().
DECLARE_DELEGATE_RetVal() [1/2]
FNetworkVersion::DECLARE_DELEGATE_RetVal (uint32 , FGetLocalNetworkVersionOverride)
Called in GetLocalNetworkVersion if bound.
DECLARE_DELEGATE_RetVal() [2/2]
FNetworkVersion::DECLARE_DELEGATE_RetVal (uint32 , FGetReplayCompatibleChangeListOverride)
Called in GetReplayCompatibleChangelist if bound.
DECLARE_DELEGATE_RetVal_TwoParams()
FNetworkVersion::DECLARE_DELEGATE_RetVal_TwoParams (bool , FIsNetworkCompatibleOverride , uint32 , uint32)
Called in IsNetworkCompatible if bound.
DescribeNetworkRuntimeFeaturesBitset()
void FNetworkVersion::DescribeNetworkRuntimeFeaturesBitset (EEngineNetworkRuntimeFeatures FeaturesBitflag, FStringBuilderBase & OutVerboseDescription) static
Build and return a string describing the status of the the network runtime features bitflag.
References DescribeNetworkRuntimeFeaturesBitset().
Referenced by DescribeNetworkRuntimeFeaturesBitset().
GetCompatibleNetworkProtocolVersion()
uint32 FNetworkVersion::GetCompatibleNetworkProtocolVersion (const FGuid & VersionGuid) static
References GetCompatibleNetworkProtocolVersion().
Referenced by GetCompatibleNetworkProtocolVersion().
GetLocalNetworkVersion()
uint32 FNetworkVersion::GetLocalNetworkVersion (bool AllowOverrideDelegate = true) static
Generates a version number, that by default, is based on a checksum of the engine version + project name + project version string Game/project code can completely override what this value returns through the GetLocalNetworkVersionOverride delegate If called with AllowOverrideDelegate=false, we will not call the game project override.
(This allows projects to call base implementation in their project implementation)
References GetLocalNetworkVersion().
Referenced by GetLocalNetworkVersion().
GetNetworkCompatibleChangelist()
uint32 FNetworkVersion::GetNetworkCompatibleChangelist () static
GetNetworkCustomVersions()
const FCustomVersionContainer & FNetworkVersion::GetNetworkCustomVersions () static
References GetNetworkCustomVersions().
Referenced by GetNetworkCustomVersions().
GetNetworkProtocolVersion()
uint32 FNetworkVersion::GetNetworkProtocolVersion (const FGuid & VersionGuid) static
References GetNetworkProtocolVersion().
Referenced by GetNetworkProtocolVersion().
GetProjectVersion()
const FString & FNetworkVersion::GetProjectVersion () inline static
Returns the project version used by networking.
Returns
FString
Definition at line 143 of file NetworkVersion.h.
References GetProjectVersion(), and GetProjectVersion_Internal().
Referenced by GetProjectVersion().
GetProjectVersion_Internal()
FString & FNetworkVersion::GetProjectVersion_Internal () static protected
Used to allow BP only projects to override network versions.
Referenced by GetProjectVersion().
GetReplayCompatibleChangelist()
uint32 FNetworkVersion::GetReplayCompatibleChangelist () static
GetReplayVersion()
FNetworkReplayVersion FNetworkVersion::GetReplayVersion () static
Generates a special struct that contains information to send to replay server.
References GetReplayVersion().
Referenced by GetReplayVersion().
InvalidateNetworkChecksum()
void FNetworkVersion::InvalidateNetworkChecksum () inline static
Invalidates any cached network checksum and forces it to be recalculated on next request.
Definition at line 148 of file NetworkVersion.h.
References bHasCachedNetworkChecksum.
IsNetworkCompatible()
bool FNetworkVersion::IsNetworkCompatible (const uint32 LocalNetworkVersion, const uint32 RemoteNetworkVersion) static
Determine if a connection is compatible with this instance.
Parameters
bRequireEngineVersionMatch should the engine versions match exactly
LocalNetworkVersion current version of the local machine
RemoteNetworkVersion current version of the remote machine
Returns
true if the two instances can communicate, false otherwise
References IsNetworkCompatible().
Referenced by IsNetworkCompatible().
RegisterNetworkCustomVersion()
void FNetworkVersion::RegisterNetworkCustomVersion (const FGuid & VersionGuid, int32 Version, int32 CompatibleVersion, const FName & FriendlyName) static
References RegisterNetworkCustomVersion().
Referenced by RegisterNetworkCustomVersion().
SetGameCompatibleNetworkProtocolVersion()
void FNetworkVersion::SetGameCompatibleNetworkProtocolVersion (uint32 GameCompatibleNetworkProtocolVersion) static
Sets the game compatible network protocol version used for networking and invalidate cached values.
References SetGameCompatibleNetworkProtocolVersion().
Referenced by SetGameCompatibleNetworkProtocolVersion().
SetGameNetworkProtocolVersion()
void FNetworkVersion::SetGameNetworkProtocolVersion (uint32 GameNetworkProtocolVersion) static
Sets the game network protocol version used for networking and invalidate cached values.
References SetGameNetworkProtocolVersion().
Referenced by SetGameNetworkProtocolVersion().
SetProjectVersion()
void FNetworkVersion::SetProjectVersion (const TCHAR * InVersion) static
Sets the project version used for networking.
Needs to be a function to verify string and correctly invalidate cached values
Parameters
InVersion
Returns
void
References SetProjectVersion().
Referenced by SetProjectVersion().
UE_DEPRECATED() [1/8]
FNetworkVersion::UE_DEPRECATED (5. 2, "Now storing this value in CompatibleNetworkCustomVersions, do not use directly.") protected
References UE_DEPRECATED().
UE_DEPRECATED() [2/8]
FNetworkVersion::UE_DEPRECATED (5. 2, "Now storing this value in CompatibleNetworkCustomVersions, do not use directly.") protected
References UE_DEPRECATED().
UE_DEPRECATED() [3/8]
FNetworkVersion::UE_DEPRECATED (5. 2, "Now storing this value in NetworkCustomVersions, do not use directly.") protected
UE_DEPRECATED() [4/8]
FNetworkVersion::UE_DEPRECATED (5. 2, "Now storing this value in NetworkCustomVersions, do not use directly.") protected
References UE_DEPRECATED().
UE_DEPRECATED() [5/8]
FNetworkVersion::UE_DEPRECATED (5. 2, "Please use GetCompatibleNetworkProtocolVersion instead.")
References UE_DEPRECATED().
UE_DEPRECATED() [6/8]
FNetworkVersion::UE_DEPRECATED (5. 2, "Please use GetCompatibleNetworkProtocolVersion instead.")
References UE_DEPRECATED().
UE_DEPRECATED() [7/8]
FNetworkVersion::UE_DEPRECATED (5. 2, "Please use GetNetworkProtocolVersion instead.")
Referenced by UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
UE_DEPRECATED() [8/8]
FNetworkVersion::UE_DEPRECATED (5. 2, "Please use GetNetworkProtocolVersion instead.")
References UE_DEPRECATED().
Field Documentation
bHasCachedNetworkChecksum
bool FNetworkVersion::bHasCachedNetworkChecksum static protected
Definition at line 157 of file NetworkVersion.h.
Referenced by InvalidateNetworkChecksum().
bHasCachedReplayChecksum
bool FNetworkVersion::bHasCachedReplayChecksum static protected
Definition at line 160 of file NetworkVersion.h.
CachedNetworkChecksum
uint32 FNetworkVersion::CachedNetworkChecksum static protected
Definition at line 158 of file NetworkVersion.h.
CachedReplayChecksum
uint32 FNetworkVersion::CachedReplayChecksum static protected
Definition at line 161 of file NetworkVersion.h.
GetLocalNetworkVersionOverride
FGetLocalNetworkVersionOverride FNetworkVersion::GetLocalNetworkVersionOverride static
Definition at line 56 of file NetworkVersion.h.
GetReplayCompatibleChangeListOverride
FGetReplayCompatibleChangeListOverride FNetworkVersion::GetReplayCompatibleChangeListOverride static
Definition at line 64 of file NetworkVersion.h.
IsNetworkCompatibleOverride
FIsNetworkCompatibleOverride FNetworkVersion::IsNetworkCompatibleOverride static
Definition at line 60 of file NetworkVersion.h.
The documentation for this struct was generated from the following file:
Runtime/Core/Public/Misc/NetworkVersion.h