Unreal Engine 5.6 C++ API: UE::MovieScene::FTaskID Struct Reference
UE::MovieScene::FTaskID Struct Reference
#include "IMovieSceneTaskScheduler.h"
Public Member Functions
FTaskID ()
FTaskID (int32 InIndex)
operator bool () const
Static Public Member Functions
static FTaskID None ()
Data Fields
int32 Index
Detailed Description
Definition at line 20 of file IMovieSceneTaskScheduler.h.
Constructor & Destructor Documentation
FTaskID() [1/2]
UE::MovieScene::FTaskID::FTaskID () inline explicit
Definition at line 24 of file IMovieSceneTaskScheduler.h.
References Index, and INDEX_NONE.
Referenced by None().
FTaskID() [2/2]
UE::MovieScene::FTaskID::FTaskID (int32 InIndex) inline explicit
Definition at line 28 of file IMovieSceneTaskScheduler.h.
References Index.
Member Function Documentation
None()
FTaskID UE::MovieScene::FTaskID::None () inline static
Definition at line 32 of file IMovieSceneTaskScheduler.h.
References FTaskID(), and INDEX_NONE.
Referenced by UE::MovieScene::TEntityTaskComponents< T >::ScheduleImpl(), UE::MovieScene::TFilteredEntityTask< T >::ScheduleImpl(), UE::MovieScene::SchedulePostTask(), and UE::MovieScene::SchedulePreTask().
operator bool()
UE::MovieScene::FTaskID::operator bool () const inline explicit
Definition at line 37 of file IMovieSceneTaskScheduler.h.
References Index, and INDEX_NONE.
Field Documentation
Index
int32 UE::MovieScene::FTaskID::Index
Definition at line 22 of file IMovieSceneTaskScheduler.h.
Referenced by FTaskID(), FTaskID(), and operator bool().
The documentation for this struct was generated from the following file:
Runtime/MovieScene/Public/EntitySystem/IMovieSceneTaskScheduler.h