Unreal Engine 5.6 C++ API: UE::FPropertyPathName::FSegment Struct Reference
UE::FPropertyPathName::FSegment Struct Reference
Public Member Functions
int32 Compare (const FSegment &Segment) const
bool operator< (const FSegment &Segment) const
bool operator== (const FSegment &Segment) const
FPropertyPathNameSegment Unpack () const
Static Public Member Functions
static FSegment Pack (const FPropertyPathNameSegment &Segment)
Data Fields
FName NameWithIndex
FPropertyTypeName Type
Detailed Description
Definition at line 53 of file PropertyPathName.h.
Member Function Documentation
Compare()
int32 UE::FPropertyPathName::FSegment::Compare (const FSegment & Segment) const
References Segment.
operator<()
bool UE::FPropertyPathName::FSegment::operator< (const FSegment & Segment) const
References Segment.
operator==()
bool UE::FPropertyPathName::FSegment::operator== (const FSegment & Segment) const
References Segment.
Pack()
FSegment UE::FPropertyPathName::FSegment::Pack (const FPropertyPathNameSegment & Segment) inline static
Definition at line 63 of file PropertyPathName.h.
References Segment.
Referenced by UE::FPropertyPathName::Push(), and UE::FPropertyPathName::SetSegment().
Unpack()
FPropertyPathNameSegment UE::FPropertyPathName::FSegment::Unpack () const inline
Definition at line 58 of file PropertyPathName.h.
References NameWithIndex, UE::FPropertyPathNameSegment::SetNameWithIndex(), UE::FPropertyPathNameSegment::SetType(), and Type.
Field Documentation
NameWithIndex
FName UE::FPropertyPathName::FSegment::NameWithIndex
Definition at line 55 of file PropertyPathName.h.
Referenced by Unpack().
Type
FPropertyTypeName UE::FPropertyPathName::FSegment::Type
Definition at line 56 of file PropertyPathName.h.
Referenced by Unpack().
The documentation for this struct was generated from the following file:
Runtime/CoreUObject/Public/UObject/PropertyPathName.h