Unreal Engine 5.6 C++ API: UE::Anim::FAnimSync Struct Reference
UE::Anim::FAnimSync Struct Reference
#include "AnimSync.h"
Public Types
using FSyncGroupMap = TMap<FName, FAnimGroupInstance>
Public Member Functions
void AddReferencedObjects (UAnimInstance *InAnimInstance, FReferenceCollector &Collector)
void AddTickRecord (const FAnimTickRecord &InTickRecord, const FAnimSyncParams &InSyncParams=FAnimSyncParams())
const FSyncGroupMap & GetSyncGroupMapRead () const
Get the sync group we are currently reading from.
FMarkerSyncAnimPosition GetSyncGroupPosition (FName InSyncGroupName) const
int32 GetSyncGroupReadIndex () const
int32 GetSyncGroupWriteIndex () const
bool GetTimeToClosestMarker (FName SyncGroup, FName MarkerName, float &OutMarkerTime) const
const TArray< FAnimTickRecord > & GetUngroupedActivePlayersRead ()
Get the ungrouped active player we are currently reading from.
bool HasMarkerBeenHitThisFrame (FName SyncGroup, FName MarkerName) const
bool IsSyncGroupBetweenMarkers (FName InSyncGroupName, FName PreviousMarker, FName NextMarker, bool bRespectMarkerOrder=true) const
bool IsSyncGroupValid (FName InSyncGroupName) const
void Reset ()
void ResetAll ()
void SetMirror (const UMirrorDataTable *MirrorTable)
void TickAssetPlayerInstances (FAnimInstanceProxy &InProxy, float InDeltaSeconds)
void TickSyncGroupWriteIndex ()
UE_DEPRECATED (5.0, "Legacy API support - do not use") 1 FAnimTickRecord &CreateUninitializedTickRecord(FAnimGroupInstance *&OutSyncGroupPtr
UE_DEPRECATED (5.0, "Legacy API support - do not use") 1 FAnimTickRecord &CreateUninitializedTickRecordInScope(FAnimInstanceProxy &InProxy
Data Fields
FName GroupName
FAnimGroupInstance FName GroupName
FAnimGroupInstance *& OutSyncGroupPtr
FAnimGroupInstance FName EAnimSyncGroupScope Scope
Static Public Attributes
static const FName Attribute
Private Attributes
const UMirrorDataTable * MirrorDataTable = nullptr
If not null, the sync markers will be mirrored based on the data in the table.
FSyncGroupMap SyncGroupMaps [2]
The set of tick groups for this anim instance.
int32 SyncGroupWriteIndex = 0
Current sync group buffer index.
TArray< FAnimTickRecord > UngroupedActivePlayerArrays [2]
The list of animation assets which are going to be evaluated this frame and need to be ticked (ungrouped)
Detailed Description
Definition at line 33 of file AnimSync.h.
Member Typedef Documentation
FSyncGroupMap
using UE::Anim::FAnimSync::FSyncGroupMap = TMap<FName, FAnimGroupInstance>
Definition at line 37 of file AnimSync.h.
Member Function Documentation
AddReferencedObjects()
void UE::Anim::FAnimSync::AddReferencedObjects (UAnimInstance * InAnimInstance, FReferenceCollector & Collector)
References AddReferencedObjects().
Referenced by AddReferencedObjects().
AddTickRecord()
void UE::Anim::FAnimSync::AddTickRecord (const FAnimTickRecord & InTickRecord, const FAnimSyncParams & InSyncParams = FAnimSyncParams())
GetSyncGroupMapRead()
const FSyncGroupMap & UE::Anim::FAnimSync::GetSyncGroupMapRead () const inline
Get the sync group we are currently reading from.
Definition at line 82 of file AnimSync.h.
References GetSyncGroupReadIndex(), and SyncGroupMaps.
GetSyncGroupPosition()
FMarkerSyncAnimPosition UE::Anim::FAnimSync::GetSyncGroupPosition (FName InSyncGroupName) const
GetSyncGroupReadIndex()
int32 UE::Anim::FAnimSync::GetSyncGroupReadIndex () const inline
Definition at line 70 of file AnimSync.h.
References SyncGroupWriteIndex.
Referenced by GetSyncGroupMapRead(), GetUngroupedActivePlayersRead(), and TickSyncGroupWriteIndex().
GetSyncGroupWriteIndex()
int32 UE::Anim::FAnimSync::GetSyncGroupWriteIndex () const inline
Definition at line 76 of file AnimSync.h.
References SyncGroupWriteIndex.
GetTimeToClosestMarker()
bool UE::Anim::FAnimSync::GetTimeToClosestMarker (FName SyncGroup, FName MarkerName, float & OutMarkerTime) const
GetUngroupedActivePlayersRead()
const TArray< FAnimTickRecord > & UE::Anim::FAnimSync::GetUngroupedActivePlayersRead () inline
Get the ungrouped active player we are currently reading from.
Definition at line 88 of file AnimSync.h.
References GetSyncGroupReadIndex(), and UngroupedActivePlayerArrays.
HasMarkerBeenHitThisFrame()
bool UE::Anim::FAnimSync::HasMarkerBeenHitThisFrame (FName SyncGroup, FName MarkerName) const
IsSyncGroupBetweenMarkers()
bool UE::Anim::FAnimSync::IsSyncGroupBetweenMarkers (FName InSyncGroupName, FName PreviousMarker, FName NextMarker, bool bRespectMarkerOrder = true) const
IsSyncGroupValid()
bool UE::Anim::FAnimSync::IsSyncGroupValid (FName InSyncGroupName) const
Reset()
void UE::Anim::FAnimSync::Reset ()
ResetAll()
void UE::Anim::FAnimSync::ResetAll ()
SetMirror()
void UE::Anim::FAnimSync::SetMirror (const UMirrorDataTable * MirrorTable)
TickAssetPlayerInstances()
void UE::Anim::FAnimSync::TickAssetPlayerInstances (FAnimInstanceProxy & InProxy, float InDeltaSeconds)
TickSyncGroupWriteIndex()
void UE::Anim::FAnimSync::TickSyncGroupWriteIndex () inline
Definition at line 64 of file AnimSync.h.
References GetSyncGroupReadIndex(), and SyncGroupWriteIndex.
UE_DEPRECATED() [1/2]
UE::Anim::FAnimSync::UE_DEPRECATED (5. 0, "Legacy API support - do not use") &
Referenced by UE_DEPRECATED().
UE_DEPRECATED() [2/2]
UE::Anim::FAnimSync::UE_DEPRECATED (5. 0, "Legacy API support - do not use") &
References UE_DEPRECATED().
Field Documentation
Attribute
const FName UE::Anim::FAnimSync::Attribute static
Definition at line 35 of file AnimSync.h.
GroupName [1/2]
FName UE::Anim::FAnimSync::GroupName
Definition at line 94 of file AnimSync.h.
GroupName [2/2]
FAnimGroupInstance FName UE::Anim::FAnimSync::GroupName
Definition at line 97 of file AnimSync.h.
MirrorDataTable
const UMirrorDataTable* UE::Anim::FAnimSync::MirrorDataTable = nullptr private
If not null, the sync markers will be mirrored based on the data in the table.
Definition at line 110 of file AnimSync.h.
OutSyncGroupPtr
FAnimGroupInstance*& UE::Anim::FAnimSync::OutSyncGroupPtr
Definition at line 97 of file AnimSync.h.
Scope
FAnimGroupInstance FName EAnimSyncGroupScope UE::Anim::FAnimSync::Scope
Definition at line 97 of file AnimSync.h.
SyncGroupMaps
FSyncGroupMap UE::Anim::FAnimSync::SyncGroupMaps[2] private
The set of tick groups for this anim instance.
Definition at line 107 of file AnimSync.h.
Referenced by GetSyncGroupMapRead().
SyncGroupWriteIndex
int32 UE::Anim::FAnimSync::SyncGroupWriteIndex = 0 private
Current sync group buffer index.
Definition at line 113 of file AnimSync.h.
Referenced by GetSyncGroupReadIndex(), GetSyncGroupWriteIndex(), and TickSyncGroupWriteIndex().
UngroupedActivePlayerArrays
TArray<FAnimTickRecord> UE::Anim::FAnimSync::UngroupedActivePlayerArrays[2] private
The list of animation assets which are going to be evaluated this frame and need to be ticked (ungrouped)
Definition at line 104 of file AnimSync.h.
Referenced by GetUngroupedActivePlayersRead().
The documentation for this struct was generated from the following file:
Runtime/Engine/Public/Animation/AnimSync.h