Unreal Engine 5.6 C++ API: FNavigationQueryFilter Struct Reference
FNavigationQueryFilter Struct Reference
#include "NavQueryFilter.h"
Public Member Functions
FNavigationQueryFilter ()
FVector GetAdjustedEndLocation (const FVector &EndPoint) const
post processing for pathfinding's end point
void GetAllAreaCosts (float *CostArray, float *FixedCostArray, const int32 Count) const
get travel & entering costs for all areas
FSharedNavQueryFilter GetCopy () const
uint16 GetExcludeFlags () const
get forbidden flags of navigation nodes
float GetHeuristicScale () const
get heuristic scaling factor
FORCEINLINE INavigationQueryFilterInterface * GetImplementation ()
FORCEINLINE const INavigationQueryFilterInterface * GetImplementation () const
uint16 GetIncludeFlags () const
get required flags of navigation nodes
FORCEINLINE uint32 GetMaxSearchNodes () const
get node limit for A* loop
bool IsBacktrackingEnabled () const
get backtracking status
FORCEINLINE bool operator== (const FNavigationQueryFilter &Other) const
void Reset ()
void SetAllAreaCosts (const float *CostArray, const int32 Count)
void SetAllAreaCosts (const TArray< float > &CostArray)
set travel cost for all areas
void SetAreaCost (uint8 AreaType, float Cost)
set travel cost for area
void SetBacktrackingEnabled (const bool bBacktracking)
mark filter as backtracking - parse directional links in opposite direction (find path from End to Start, but all links works like on path from Start to End)
void SetExcludedArea (uint8 AreaType)
mark area as excluded from path finding
void SetExcludeFlags (uint16 Flags)
set forbidden flags of navigation nodes
FORCEINLINE_DEBUGGABLE void SetFilterImplementation (const INavigationQueryFilterInterface *InQueryFilterImpl)
template<typename FilterType>
void SetFilterType ()
void SetFixedAreaEnteringCost (uint8 AreaType, float Cost)
set entering cost for area
void SetIncludeFlags (uint16 Flags)
set required flags of navigation nodes
void SetMaxSearchNodes (const uint32 MaxNodes)
set node limit for A* loop
Public Member Functions inherited from TSharedFromThis< FNavigationQueryFilter, ESPMode::ThreadSafe >
TSharedRef< FNavigationQueryFilter, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FNavigationQueryFilter, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Static Public Attributes
static const uint32 DefaultMaxSearchNodes
Protected Member Functions
void Assign (const FNavigationQueryFilter &Source)
Protected Member Functions inherited from TSharedFromThis< FNavigationQueryFilter, ESPMode::ThreadSafe >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Protected Attributes
uint32 MaxSearchNodes
TSharedPtr< INavigationQueryFilterInterface, ESPMode::ThreadSafe > QueryFilterImpl
Private Member Functions
FNavigationQueryFilter (const FNavigationQueryFilter &Source)
FNavigationQueryFilter (const FNavigationQueryFilter *Source)
FNavigationQueryFilter (const FSharedNavQueryFilter Source)
FNavigationQueryFilter & operator= (const FNavigationQueryFilter &Source)
Additional Inherited Members
Static Protected Member Functions inherited from TSharedFromThis< FNavigationQueryFilter, ESPMode::ThreadSafe >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
Definition at line 38 of file NavQueryFilter.h.
Constructor & Destructor Documentation
FNavigationQueryFilter() [1/4]
FNavigationQueryFilter::FNavigationQueryFilter () inline
Definition at line 40 of file NavQueryFilter.h.
References DefaultMaxSearchNodes, MaxSearchNodes, and QueryFilterImpl.
Referenced by FNavigationQueryFilter(), FNavigationQueryFilter(), Assign(), operator=(), and operator==().
FNavigationQueryFilter() [2/4]
FNavigationQueryFilter::FNavigationQueryFilter (const FNavigationQueryFilter & Source) private
References FNavigationQueryFilter(), and Source.
FNavigationQueryFilter() [3/4]
FNavigationQueryFilter::FNavigationQueryFilter (const FNavigationQueryFilter * Source) private
References FNavigationQueryFilter(), and Source.
FNavigationQueryFilter() [4/4]
FNavigationQueryFilter::FNavigationQueryFilter (const FSharedNavQueryFilter Source) private
References Source.
Member Function Documentation
Assign()
void FNavigationQueryFilter::Assign (const FNavigationQueryFilter & Source) protected
References FNavigationQueryFilter(), and Source.
GetAdjustedEndLocation()
FVector FNavigationQueryFilter::GetAdjustedEndLocation (const FVector & EndPoint) const inline
post processing for pathfinding's end point
Definition at line 93 of file NavQueryFilter.h.
References FVector, and QueryFilterImpl.
GetAllAreaCosts()
void FNavigationQueryFilter::GetAllAreaCosts (float * CostArray, float * FixedCostArray, const int32 Count) const
get travel & entering costs for all areas
References Count.
GetCopy()
FSharedNavQueryFilter FNavigationQueryFilter::GetCopy () const
GetExcludeFlags()
uint16 FNavigationQueryFilter::GetExcludeFlags () const
get forbidden flags of navigation nodes
GetHeuristicScale()
float FNavigationQueryFilter::GetHeuristicScale () const inline
get heuristic scaling factor
Definition at line 83 of file NavQueryFilter.h.
References QueryFilterImpl.
GetImplementation() [1/2]
FORCEINLINE INavigationQueryFilterInterface * FNavigationQueryFilter::GetImplementation () inline
Definition at line 107 of file NavQueryFilter.h.
References FORCEINLINE, and QueryFilterImpl.
GetImplementation() [2/2]
FORCEINLINE const INavigationQueryFilterInterface * FNavigationQueryFilter::GetImplementation () const inline
Definition at line 106 of file NavQueryFilter.h.
References FORCEINLINE, and QueryFilterImpl.
Referenced by operator==(), and Reset().
GetIncludeFlags()
uint16 FNavigationQueryFilter::GetIncludeFlags () const
get required flags of navigation nodes
GetMaxSearchNodes()
FORCEINLINE uint32 FNavigationQueryFilter::GetMaxSearchNodes () const inline
get node limit for A* loop
Definition at line 80 of file NavQueryFilter.h.
References FORCEINLINE, and MaxSearchNodes.
IsBacktrackingEnabled()
bool FNavigationQueryFilter::IsBacktrackingEnabled () const inline
get backtracking status
Definition at line 90 of file NavQueryFilter.h.
References QueryFilterImpl.
operator=()
FNavigationQueryFilter & FNavigationQueryFilter::operator= (const FNavigationQueryFilter & Source) private
References FNavigationQueryFilter(), and Source.
operator==()
FORCEINLINE bool FNavigationQueryFilter::operator== (const FNavigationQueryFilter & Other) const inline
Definition at line 112 of file NavQueryFilter.h.
References FNavigationQueryFilter(), FORCEINLINE, GetImplementation(), INavigationQueryFilterInterface::IsEqual(), and Other.
Reset()
void FNavigationQueryFilter::Reset () inline
Definition at line 108 of file NavQueryFilter.h.
References GetImplementation(), and INavigationQueryFilterInterface::Reset().
SetAllAreaCosts() [1/2]
void FNavigationQueryFilter::SetAllAreaCosts (const float * CostArray, const int32 Count)
References Count.
SetAllAreaCosts() [2/2]
void FNavigationQueryFilter::SetAllAreaCosts (const TArray< float > & CostArray)
set travel cost for all areas
SetAreaCost()
void FNavigationQueryFilter::SetAreaCost (uint8 AreaType, float Cost)
set travel cost for area
SetBacktrackingEnabled()
void FNavigationQueryFilter::SetBacktrackingEnabled (const bool bBacktracking) inline
mark filter as backtracking - parse directional links in opposite direction (find path from End to Start, but all links works like on path from Start to End)
Definition at line 87 of file NavQueryFilter.h.
References QueryFilterImpl.
SetExcludedArea()
void FNavigationQueryFilter::SetExcludedArea (uint8 AreaType)
mark area as excluded from path finding
SetExcludeFlags()
void FNavigationQueryFilter::SetExcludeFlags (uint16 Flags)
set forbidden flags of navigation nodes
References Flags.
SetFilterImplementation()
FORCEINLINE_DEBUGGABLE void FNavigationQueryFilter::SetFilterImplementation (const INavigationQueryFilterInterface * InQueryFilterImpl) inline
Definition at line 101 of file NavQueryFilter.h.
References INavigationQueryFilterInterface::CreateCopy(), FORCEINLINE_DEBUGGABLE, MakeShareable(), and QueryFilterImpl.
SetFilterType()
template<typename FilterType> void FNavigationQueryFilter::SetFilterType () inline
Definition at line 96 of file NavQueryFilter.h.
References MakeShareable(), and QueryFilterImpl.
SetFixedAreaEnteringCost()
void FNavigationQueryFilter::SetFixedAreaEnteringCost (uint8 AreaType, float Cost)
set entering cost for area
SetIncludeFlags()
void FNavigationQueryFilter::SetIncludeFlags (uint16 Flags)
set required flags of navigation nodes
References Flags.
SetMaxSearchNodes()
void FNavigationQueryFilter::SetMaxSearchNodes (const uint32 MaxNodes) inline
set node limit for A* loop
Definition at line 77 of file NavQueryFilter.h.
References MaxSearchNodes.
Field Documentation
DefaultMaxSearchNodes
const uint32 FNavigationQueryFilter::DefaultMaxSearchNodes static
Definition at line 119 of file NavQueryFilter.h.
Referenced by FNavigationQueryFilter().
MaxSearchNodes
uint32 FNavigationQueryFilter::MaxSearchNodes protected
Definition at line 125 of file NavQueryFilter.h.
Referenced by FNavigationQueryFilter(), GetMaxSearchNodes(), and SetMaxSearchNodes().
QueryFilterImpl
TSharedPtr<INavigationQueryFilterInterface, ESPMode::ThreadSafe> FNavigationQueryFilter::QueryFilterImpl protected
Definition at line 124 of file NavQueryFilter.h.
Referenced by FNavigationQueryFilter(), GetAdjustedEndLocation(), GetHeuristicScale(), GetImplementation(), GetImplementation(), IsBacktrackingEnabled(), SetBacktrackingEnabled(), SetFilterImplementation(), and SetFilterType().
The documentation for this struct was generated from the following file:
Runtime/Engine/Public/AI/Navigation/NavQueryFilter.h