Unreal Engine 5.6 C++ API: TBounds< T > Struct Template Reference
TBounds< T > Struct Template Reference
#include "Bounds.h"
Public Types
using FReal = T
template<typename U>
using TVector = UE::Math::TVector<U>
template<typename U>
using TVector4 = UE::Math::TVector4<U>
Public Member Functions
FORCEINLINE bool Contains (const TBounds< T > &Other) const
FORCEINLINE T DistSqr (const TVector< T > &Point) const
FORCEINLINE TVector< T > GetCenter () const
FORCEINLINE TVector< T > GetExtent () const
FORCEINLINE TVector< T > GetSize () const
FORCEINLINE T GetSurfaceArea () const
FORCEINLINE bool Intersect (const TBounds< T > &Other) const
FORCEINLINE TBounds< T > operator+ (const TBounds< T > &Other) const
FORCEINLINE TBounds< T > & operator+= (const TBounds< T > &Other)
FORCEINLINE TBounds< T > & operator+= (const TVector< T > &Other)
FORCEINLINE TBounds< T > & operator= (const TVector< T > &Other)
template<typename U>
FORCEINLINE auto ToAbsolute (const TVector< U > &Offset) const
template<typename U>
FORCEINLINE TBounds< float > ToRelative (const TVector< U > &Offset) const
Data Fields
TVector4< T > Max = TVector4<T>(-TNumericLimits<T>::Max(), -TNumericLimits<T>::Max(), -TNumericLimits<T>::Max())
TVector4< T > Min = TVector4<T>(TNumericLimits<T>::Max(), TNumericLimits<T>::Max(), TNumericLimits<T>::Max())
Friends
FORCEINLINE friend FArchive & operator<< (FArchive &Ar, TBounds< T > &Bounds)
Detailed Description
template<typename T>
struct TBounds< T >
Definition at line 11 of file Bounds.h.
Member Typedef Documentation
FReal
template<typename T> using TBounds< T >::FReal = T
Definition at line 15 of file Bounds.h.
TVector
template<typename T> template<typename U> using TBounds< T >::TVector = UE::Math::TVector<U>
Definition at line 13 of file Bounds.h.
TVector4
template<typename T> template<typename U> using TBounds< T >::TVector4 = UE::Math::TVector4<U>
Definition at line 14 of file Bounds.h.
Member Function Documentation
Contains()
template<typename T> FORCEINLINE bool TBounds< T >::Contains (const TBounds< T > & Other) const inline nodiscard
Definition at line 55 of file Bounds.h.
DistSqr()
template<typename T> FORCEINLINE T TBounds< T >::DistSqr (const TVector< T > & Point) const inline nodiscard
Definition at line 62 of file Bounds.h.
GetCenter()
template<typename T> FORCEINLINE TVector< T > TBounds< T >::GetCenter () const inline nodiscard
Definition at line 71 of file Bounds.h.
GetExtent()
template<typename T> FORCEINLINE TVector< T > TBounds< T >::GetExtent () const inline nodiscard
Definition at line 76 of file Bounds.h.
GetSize()
template<typename T> FORCEINLINE TVector< T > TBounds< T >::GetSize () const inline nodiscard
Definition at line 81 of file Bounds.h.
GetSurfaceArea()
template<typename T> FORCEINLINE T TBounds< T >::GetSurfaceArea () const inline nodiscard
Definition at line 86 of file Bounds.h.
Intersect()
template<typename T> FORCEINLINE bool TBounds< T >::Intersect (const TBounds< T > & Other) const inline nodiscard
Definition at line 46 of file Bounds.h.
operator+()
template<typename T> FORCEINLINE TBounds< T > TBounds< T >::operator+ (const TBounds< T > & Other) const inline nodiscard
Definition at line 41 of file Bounds.h.
operator+=() [1/2]
template<typename T> FORCEINLINE TBounds< T > & TBounds< T >::operator+= (const TBounds< T > & Other) inline
Definition at line 34 of file Bounds.h.
operator+=() [2/2]
template<typename T> FORCEINLINE TBounds< T > & TBounds< T >::operator+= (const TVector< T > & Other) inline
Definition at line 27 of file Bounds.h.
operator=()
template<typename T> FORCEINLINE TBounds< T > & TBounds< T >::operator= (const TVector< T > & Other) inline
Definition at line 20 of file Bounds.h.
ToAbsolute()
template<typename T> template<typename U> FORCEINLINE auto TBounds< T >::ToAbsolute (const TVector< U > & Offset) const inline nodiscard
Definition at line 93 of file Bounds.h.
ToRelative()
template<typename T> template<typename U> FORCEINLINE TBounds< float > TBounds< T >::ToRelative (const TVector< U > & Offset) const inline nodiscard
Definition at line 104 of file Bounds.h.
Friends And Related Symbol Documentation
operator<<
template<typename T> FORCEINLINE friend FArchive & operator<< (FArchive & Ar, TBounds< T > & Bounds) friend
Definition at line 114 of file Bounds.h.
Field Documentation
Max
template<typename T> TVector4<T> TBounds< T >::Max = TVector4<T>(-TNumericLimits<T>::Max(), -TNumericLimits<T>::Max(), -TNumericLimits<T>::Max())
Definition at line 18 of file Bounds.h.
Referenced by TBounds< float >::operator<<, TBounds< float >::ToAbsolute(), and TBounds< float >::ToRelative().
Min
template<typename T> TVector4<T> TBounds< T >::Min = TVector4<T>(TNumericLimits<T>::Max(), TNumericLimits<T>::Max(), TNumericLimits<T>::Max())
Definition at line 17 of file Bounds.h.
Referenced by TBounds< float >::operator<<, TBounds< float >::ToAbsolute(), and TBounds< float >::ToRelative().
The documentation for this struct was generated from the following file:
Runtime/Core/Public/Math/Bounds.h