Unreal Engine 5.6 C++ API: FMovieSceneSpawnRegister::FMovieSceneSpawnRegisterKey Struct Reference
FMovieSceneSpawnRegister::FMovieSceneSpawnRegisterKey Struct Reference
Helper key type for mapping a guid and sequence instance to a specific value.
#include "MovieSceneSpawnRegister.h"
Public Member Functions
FMovieSceneSpawnRegisterKey (FMovieSceneSequenceIDRef InTemplateID, const FGuid &InBindingId, int32 InBindingIndex)
bool operator== (const FMovieSceneSpawnRegisterKey &Other) const
Data Fields
FGuid BindingId
BindingId of the object binding.
int32 BindingIndex = 0
FMovieSceneSequenceID TemplateID
Movie Scene template identifier that spawned the object.
Friends
uint32 GetTypeHash (const FMovieSceneSpawnRegisterKey &Key)
Detailed Description
Helper key type for mapping a guid and sequence instance to a specific value.
Definition at line 279 of file MovieSceneSpawnRegister.h.
Constructor & Destructor Documentation
FMovieSceneSpawnRegisterKey()
FMovieSceneSpawnRegister::FMovieSceneSpawnRegisterKey::FMovieSceneSpawnRegisterKey (FMovieSceneSequenceIDRef InTemplateID, const FGuid & InBindingId, int32 InBindingIndex) inline
Definition at line 281 of file MovieSceneSpawnRegister.h.
References BindingId, BindingIndex, and TemplateID.
Referenced by GetTypeHash, and operator==().
Member Function Documentation
operator==()
bool FMovieSceneSpawnRegister::FMovieSceneSpawnRegisterKey::operator== (const FMovieSceneSpawnRegisterKey & Other) const inline
Definition at line 288 of file MovieSceneSpawnRegister.h.
References FMovieSceneSpawnRegisterKey(), BindingId, BindingIndex, Other, and TemplateID.
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FMovieSceneSpawnRegisterKey & Key) friend
Definition at line 293 of file MovieSceneSpawnRegister.h.
References FMovieSceneSpawnRegisterKey(), GetTypeHash, HashCombine(), and Key.
Referenced by GetTypeHash.
Field Documentation
BindingId
FGuid FMovieSceneSpawnRegister::FMovieSceneSpawnRegisterKey::BindingId
BindingId of the object binding.
Definition at line 299 of file MovieSceneSpawnRegister.h.
Referenced by FMovieSceneSpawnRegisterKey(), and operator==().
BindingIndex
int32 FMovieSceneSpawnRegister::FMovieSceneSpawnRegisterKey::BindingIndex = 0
Definition at line 305 of file MovieSceneSpawnRegister.h.
Referenced by FMovieSceneSpawnRegisterKey(), and operator==().
TemplateID
FMovieSceneSequenceID FMovieSceneSpawnRegister::FMovieSceneSpawnRegisterKey::TemplateID
Movie Scene template identifier that spawned the object.
Definition at line 302 of file MovieSceneSpawnRegister.h.
Referenced by FMovieSceneSpawnRegisterKey(), and operator==().
The documentation for this struct was generated from the following file:
Runtime/MovieScene/Public/MovieSceneSpawnRegister.h