Unreal Engine 5.6 C++ API: TDeltaSetup< ElementType, DeltaType >::FReader Struct Reference
TDeltaSetup< ElementType, DeltaType >::FReader Struct Reference
Binds a specific delta type to an array for writing.
#include "InstanceUpdateChangeSet.h"
Public Member Functions
template<typename IndexRemapType>
void Scatter (TArray< ElementType > &OutDataArray, const IndexRemapType &IndexRemap)
template<typename ElementTransformFuncType, typename IndexRemapType>
void Scatter (TArray< ElementType > &OutDataArray, ElementTransformFuncType ElementTransformFunc, const IndexRemapType &IndexRemap)
Data Fields
TDeltaSetup Setup
Detailed Description
template<typename ElementType, typename DeltaType>
struct TDeltaSetup< ElementType, DeltaType >::FReader
Binds a specific delta type to an array for writing.
Definition at line 153 of file InstanceUpdateChangeSet.h.
Member Function Documentation
Scatter() [1/2]
template<typename ElementType, typename DeltaType> template<typename IndexRemapType> void TDeltaSetup< ElementType, DeltaType >::FReader::Scatter (TArray< ElementType > & OutDataArray, const IndexRemapType & IndexRemap) inline
Definition at line 158 of file InstanceUpdateChangeSet.h.
References check, FMemory::Memcpy(), MoveTemp(), TArray< InElementType, InAllocatorType >::Reset(), TArray< InElementType, InAllocatorType >::SetNumUninitialized(), and Setup.
Scatter() [2/2]
template<typename ElementType, typename DeltaType> template<typename ElementTransformFuncType, typename IndexRemapType> void TDeltaSetup< ElementType, DeltaType >::FReader::Scatter (TArray< ElementType > & OutDataArray, ElementTransformFuncType ElementTransformFunc, const IndexRemapType & IndexRemap) inline
Definition at line 190 of file InstanceUpdateChangeSet.h.
References check, MoveTemp(), TArray< InElementType, InAllocatorType >::Reset(), TArray< InElementType, InAllocatorType >::SetNumUninitialized(), and Setup.
Field Documentation
Setup
template<typename ElementType, typename DeltaType> TDeltaSetup TDeltaSetup< ElementType, DeltaType >::FReader::Setup
Definition at line 155 of file InstanceUpdateChangeSet.h.
Referenced by Scatter(), and Scatter().
The documentation for this struct was generated from the following file:
Runtime/Engine/Public/InstanceData/InstanceUpdateChangeSet.h