Unreal Engine 5.6 C++ API: FTimecode Struct Reference
FTimecode Struct Reference
A timecode that stores time in HH:MM:SS format with the remainder of time represented by an integer frame count.
#include "Timecode.h"
Public Member Functions
FTimecode ()
Default construction for UObject purposes.
FTimecode (double InSeconds, const FFrameRate &InFrameRate, bool InbDropFrame, bool InbRollover)
User construction from a time in seconds.
FTimecode (double InSeconds, const FFrameRate &InFrameRate, bool InbRollover)
User construction from a time in seconds.
FTimecode (int32 InHours, int32 InMinutes, int32 InSeconds, int32 InFrames, bool InbDropFrame)
User construction from a number of hours minutes seconds and frames.
FTimecode (int32 InHours, int32 InMinutes, int32 InSeconds, int32 InFrames, float InSubframe, bool InbDropFrame)
User construction from a number of hours minutes seconds frames, and subframes.
bool IsValid () const
Will return true if the timecode represents a valid timecode value where.
FFrameNumber ToFrameNumber (const FFrameRate &InFrameRate) const
Converts this Timecode back into a Frame Number at the given framerate, taking into account if this is a drop-frame format timecode.
FString ToString (bool bForceSignDisplay=false, bool bDisplaySubframe=false) const
Get the Qualified Timecode formatted in HH:MM:SS:FF or HH:MM:SS;FF depending on if this represents drop-frame timecode or not.
FTimespan ToTimespan (const FFrameRate &InFrameRate) const
Converts this Timecode back into a timespan at the given framerate, taking into account if this is a drop-frame format timecode.
Static Public Member Functions
static FTimecode FromFrameNumber (const FFrameNumber &InFrameNumber, const FFrameRate &InFrameRate)
Create a FTimecode from a specific frame number at the given frame rate.
static FTimecode FromFrameNumber (const FFrameNumber &InFrameNumber, const FFrameRate &InFrameRate, bool InbDropFrame)
Create a FTimecode from a specific frame number at the given frame rate.
static FTimecode FromFrameTime (const FFrameTime &InFrameTime, const FFrameRate &InFrameRate, TOptional< bool > bDropFrame={})
Create a FTimecode from a specific frame time at the given frame rate.
static FTimecode FromTimespan (const FTimespan &InTimespan, const FFrameRate &InFrameRate, bool InbDropFrame, bool InbRollover)
Create a FTimecode from a timespan at the given frame rate.
static FTimecode FromTimespan (const FTimespan &InTimespan, const FFrameRate &InFrameRate, bool InbRollover)
Create a FTimecode from a timespan at the given frame rate.
static bool IsDropFormatTimecodeSupported (const double InRate)
Drop frame is only support for frame rate of 29.97 or 59.94.
static bool IsDropFormatTimecodeSupported (const FFrameRate &InFrameRate)
Drop frame is only support for frame rate of 29.97 or 59.94.
static bool IsValidDropFormatTimecodeRate (const FString &InRateString)
Returns true if the given frame rate string represents a supported drop frame timecode frame rate, or false otherwise.
static TOptional< FTimecode > ParseTimecode (const FStringView InTimecodeString)
Parses a string representation of a timecode.
static bool UseDropFormatTimecode (const FFrameRate &InFrameRate)
If the frame rate support drop frame format and the app wish to use drop frame format by default.
static bool UseDropFormatTimecodeByDefaultWhenSupported ()
By default, should we generate a timecode in drop frame format when the frame rate does support it.
Data Fields
bool bDropFrameFormat
If true, this Timecode represents a Drop Frame timecode used to account for fractional frame rates in NTSC play rates.
int32 Frames
How many frames does this timecode represent.
int32 Hours
IMPORTANT: If you change the struct data, ensure that you also update the version in NoExportTypes.h.
int32 Minutes
How many minutes does this timecode represent.
int32 Seconds
How many seconds does this timecode represent.
float Subframe = 0
The subframe value provided when converting to FFrameTime.
Friends
bool operator!= (const FFrameRate &A, const FFrameRate &B)
bool operator!= (const FTimecode &A, const FTimecode &B)
bool operator== (const FFrameRate &A, const FFrameRate &B)
bool operator== (const FTimecode &A, const FTimecode &B)
Detailed Description
A timecode that stores time in HH:MM:SS format with the remainder of time represented by an integer frame count.
Definition at line 18 of file Timecode.h.
Constructor & Destructor Documentation
FTimecode() [1/5]
FTimecode::FTimecode () inline
Default construction for UObject purposes.
Definition at line 23 of file Timecode.h.
References bDropFrameFormat, Frames, Hours, Minutes, Seconds, and Subframe.
Referenced by FTimecode(), FromFrameNumber(), FromFrameNumber(), FromFrameTime(), FromTimespan(), FromTimespan(), operator!=, and operator==.
FTimecode() [2/5]
FTimecode::FTimecode (int32 InHours, int32 InMinutes, int32 InSeconds, int32 InFrames, bool InbDropFrame) inline explicit
User construction from a number of hours minutes seconds and frames.
Parameters
InbDropFrame - If true, this Timecode represents a "Drop Frame Timecode" format which skips the first frames of every minute (except those ending in multiples of 10) to account for drift when using a fractional NTSC framerate.
Definition at line 38 of file Timecode.h.
References bDropFrameFormat, checkSlow, Frames, Hours, IsValid(), Minutes, and Seconds.
FTimecode() [3/5]
FTimecode::FTimecode (int32 InHours, int32 InMinutes, int32 InSeconds, int32 InFrames, float InSubframe, bool InbDropFrame) inline explicit
User construction from a number of hours minutes seconds frames, and subframes.
Parameters
InbDropFrame - If true, this Timecode represents a "Drop Frame Timecode" format which skips the first frames of every minute (except those ending in multiples of 10) to account for drift when using a fractional NTSC framerate.
Definition at line 54 of file Timecode.h.
References bDropFrameFormat, checkSlow, Frames, Hours, IsValid(), Minutes, Seconds, and Subframe.
FTimecode() [4/5]
FTimecode::FTimecode (double InSeconds, const FFrameRate & InFrameRate, bool InbDropFrame, bool InbRollover) inline explicit
User construction from a time in seconds.
Parameters
InbDropFrame - If true, this Timecode represents a "Drop Frame Timecode" format which skips the first frames of every minute (except those ending in multiples of 10) to account for drift when using a fractional NTSC framerate.
InbRollover - If true, the hours will be the modulo of 24.
Note
Be aware that the Cycles may not correspond to the System Time. See FDateTime and "leap seconds".
Definition at line 73 of file Timecode.h.
References FFrameRate::AsDecimal(), and FromFrameNumber().
FTimecode() [5/5]
FTimecode::FTimecode (double InSeconds, const FFrameRate & InFrameRate, bool InbRollover) inline explicit
User construction from a time in seconds.
Parameters
InbRollover - If true, the hours will be the modulo of 24.
Note
Be aware that the Cycles may not correspond to the System Time. See FDateTime and "leap seconds".
Definition at line 93 of file Timecode.h.
References FTimecode(), and UseDropFormatTimecode().
Member Function Documentation
FromFrameNumber() [1/2]
FTimecode FTimecode::FromFrameNumber (const FFrameNumber & InFrameNumber, const FFrameRate & InFrameRate) inline static
Create a FTimecode from a specific frame number at the given frame rate.
Parameters
InFrameNumber - The frame number to convert into a timecode. This should already be converted to InFrameRate's resolution.
InFrameRate - The framerate that this timecode is based in. This should be the playback framerate as it is used to determine when the Frame value wraps over.
Definition at line 246 of file Timecode.h.
References FTimecode(), FromFrameNumber(), and UseDropFormatTimecode().
FromFrameNumber() [2/2]
FTimecode FTimecode::FromFrameNumber (const FFrameNumber & InFrameNumber, const FFrameRate & InFrameRate, bool InbDropFrame) inline static
Create a FTimecode from a specific frame number at the given frame rate.
Optionally supports creating a drop frame timecode, which drops certain timecode display numbers to help account for NTSC frame rates which are fractional.
Parameters
InFrameNumber - The frame number to convert into a timecode. This should already be converted to InFrameRate's resolution.
InFrameRate - The framerate that this timecode is based in. This should be the playback framerate as it is used to determine when the Frame value wraps over.
InbDropFrame - If true, the returned timecode will drop the first two frames on every minute (except when Minute % 10 == 0) This is only valid for NTSC framerates (29.97, 59.94) and will assert if you try to create a drop-frame format from a non-valid framerate. All framerates can be represented when in non-drop frame format.
Definition at line 161 of file Timecode.h.
References FTimecode(), FFrameRate::AsDecimal(), Frames, Hours, Minutes, FMath::RoundToZero(), Seconds, and FFrameNumber::Value.
Referenced by FTimecode(), and FromFrameNumber().
FromFrameTime()
FTimecode FTimecode::FromFrameTime (const FFrameTime & InFrameTime, const FFrameRate & InFrameRate, TOptional< bool > bDropFrame = {}) inline static
Create a FTimecode from a specific frame time at the given frame rate.
Parameters
InFrameTime - The frame time to convert into a timecode. This should already be converted to InFrameTimes's resolution.
InFrameRate - The framerate that this timecode is based in. This should be the playback framerate as it is used to determine when the Frame value wraps over.
bDropFrame - Optional parameter to indicate if we are in drop frame format.
Definition at line 259 of file Timecode.h.
References FTimecode().
Referenced by FQualifiedFrameTime::ToTimecode(), and FQualifiedFrameTime::ToTimecode().
FromTimespan() [1/2]
FTimecode FTimecode::FromTimespan (const FTimespan & InTimespan, const FFrameRate & InFrameRate, bool InbDropFrame, bool InbRollover) inline static
Create a FTimecode from a timespan at the given frame rate.
Optionally supports creating a drop frame timecode, which drops certain timecode display numbers to help account for NTSC frame rates which are fractional.
Parameters
InTimespan - The timespan to convert into a timecode.
InFrameRate - The framerate that this timecode is based in. This should be the playback framerate as it is used to determine when the Frame value wraps over.
InbDropFrame - If true, the returned timecode will drop the first two frames on every minute (except when Minute % 10 == 0) This is only valid for NTSC framerates (29.97, 59.94) and will assert if you try to create a drop-frame format from a non-valid framerate. All framerates can be represented when in non-drop frame format.
InbRollover - If true, the hours will be the modulo of 24.
Definition at line 289 of file Timecode.h.
References FTimecode(), and FTimespan::GetTotalSeconds().
FromTimespan() [2/2]
FTimecode FTimecode::FromTimespan (const FTimespan & InTimespan, const FFrameRate & InFrameRate, bool InbRollover) inline static
Create a FTimecode from a timespan at the given frame rate.
Parameters
InTimespan - The timespan to convert into a timecode.
InFrameRate - The framerate that this timecode is based in. This should be the playback framerate as it is used to determine when the Frame value wraps over.
InbRollover - If true, the hours will be the modulo of 24.
Definition at line 302 of file Timecode.h.
References FTimecode(), FTimespan::GetTotalSeconds(), and UseDropFormatTimecode().
IsDropFormatTimecodeSupported() [1/2]
bool FTimecode::IsDropFormatTimecodeSupported (const double InRate) inline static
Drop frame is only support for frame rate of 29.97 or 59.94.
Definition at line 308 of file Timecode.h.
References FMath::IsNearlyEqual().
Referenced by IsDropFormatTimecodeSupported(), and UseDropFormatTimecode().
IsDropFormatTimecodeSupported() [2/2]
bool FTimecode::IsDropFormatTimecodeSupported (const FFrameRate & InFrameRate) inline static
Drop frame is only support for frame rate of 29.97 or 59.94.
Definition at line 315 of file Timecode.h.
References FFrameRate::AsDecimal(), and IsDropFormatTimecodeSupported().
IsValid()
bool FTimecode::IsValid () const inline
Will return true if the timecode represents a valid timecode value where.
Minutes is +/- [0, 59] Seconds is +/- [0, 59] Frames [INT_MIN, INT_MAX] Subframes >= 0
Definition at line 382 of file Timecode.h.
References Minutes, Seconds, and Subframe.
Referenced by FTimecode(), and FTimecode().
IsValidDropFormatTimecodeRate()
bool FTimecode::IsValidDropFormatTimecodeRate (const FString & InRateString) inline static
Returns true if the given frame rate string represents a supported drop frame timecode frame rate, or false otherwise.
Drop frame timecode is only supported for NTSC_30 (29.97 FPS) or NTSC_60 (59.94 FPS) frame rates.
Definition at line 336 of file Timecode.h.
ParseTimecode()
TOptional< FTimecode > FTimecode::ParseTimecode (const FStringView InTimecodeString) static
Parses a string representation of a timecode.
Supported SMPTE drop frame (DF) and non-drop frame (NDF) formats variations:
NDF: HH:MM:SS:FF
DF: HH:MM:SS;FF or HH:MM:SS.FF or HH;MM;SS;FF or HH.MM.SS.FF.
The 2 digits per number is not enforced. It is possible to parse high frame numbers (above 60), such as for audio timecodes. Full SMPTE compliance is not ensured by the parser (i.e. greater than 24h, negative time and any number of frames per second).
Sub-frame variation: Supports the sub-frame variation where the frame number is a decimal number: HH:MM:SS:FF.ZZ.
Side effect of supporting sub-frame is that this function can't unambiguously parse partial timecodes.
Parameters
InTimecodeString A string representation of a timecode
Returns
Parsed timecode if valid.
ToFrameNumber()
FFrameNumber FTimecode::ToFrameNumber (const FFrameRate & InFrameRate) const inline
Converts this Timecode back into a Frame Number at the given framerate, taking into account if this is a drop-frame format timecode.
Definition at line 108 of file Timecode.h.
References FFrameRate::AsDecimal(), bDropFrameFormat, Frames, Hours, Minutes, FMath::RoundToZero(), and Seconds.
Referenced by ToTimespan().
ToString()
FString FTimecode::ToString (bool bForceSignDisplay = false, bool bDisplaySubframe = false) const
Get the Qualified Timecode formatted in HH:MM:SS:FF or HH:MM:SS;FF depending on if this represents drop-frame timecode or not.
Parameters
bForceSignDisplay - Forces the timecode to be prepended with a positive or negative sign. Standard behavior is to only show the sign when the value is negative.
bDisplaySubframe - If subframe decimal digits are desired.
ToTimespan()
FTimespan FTimecode::ToTimespan (const FFrameRate & InFrameRate) const inline
Converts this Timecode back into a timespan at the given framerate, taking into account if this is a drop-frame format timecode.
Definition at line 270 of file Timecode.h.
References FFrameRate::AsInterval(), FTimespan::FromSeconds(), ToFrameNumber(), and FFrameNumber::Value.
UseDropFormatTimecode()
bool FTimecode::UseDropFormatTimecode (const FFrameRate & InFrameRate) inline static
If the frame rate support drop frame format and the app wish to use drop frame format by default.
Definition at line 323 of file Timecode.h.
References IsDropFormatTimecodeSupported(), and UseDropFormatTimecodeByDefaultWhenSupported().
Referenced by FTimecode(), FromFrameNumber(), and FromTimespan().
UseDropFormatTimecodeByDefaultWhenSupported()
bool FTimecode::UseDropFormatTimecodeByDefaultWhenSupported () static
By default, should we generate a timecode in drop frame format when the frame rate does support it.
Referenced by UseDropFormatTimecode().
Friends And Related Symbol Documentation
operator!= [1/2]
bool operator!= (const FFrameRate & A, const FFrameRate & B) friend
References A, and B.
operator!= [2/2]
bool operator!= (const FTimecode & A, const FTimecode & B) friend
Definition at line 417 of file Timecode.h.
References FTimecode(), A, and B.
operator== [1/2]
bool operator== (const FFrameRate & A, const FFrameRate & B) friend
References A, and B.
operator== [2/2]
bool operator== (const FTimecode & A, const FTimecode & B) friend
Definition at line 412 of file Timecode.h.
References FTimecode(), A, and B.
Field Documentation
bDropFrameFormat
bool FTimecode::bDropFrameFormat
If true, this Timecode represents a Drop Frame timecode used to account for fractional frame rates in NTSC play rates.
Definition at line 410 of file Timecode.h.
Referenced by FTimecode(), FTimecode(), FTimecode(), DisplayClusterTypesConverter::FromString(), ToFrameNumber(), and DisplayClusterTypesConverter::ToString().
Frames
int32 FTimecode::Frames
How many frames does this timecode represent.
Definition at line 404 of file Timecode.h.
Referenced by FTimecode(), FTimecode(), FTimecode(), FromFrameNumber(), DisplayClusterTypesConverter::FromString(), ToFrameNumber(), and DisplayClusterTypesConverter::ToString().
Hours
int32 FTimecode::Hours
IMPORTANT: If you change the struct data, ensure that you also update the version in NoExportTypes.h.
How many hours does this timecode represent
Definition at line 395 of file Timecode.h.
Referenced by FTimecode(), FTimecode(), FTimecode(), FromFrameNumber(), DisplayClusterTypesConverter::FromString(), ToFrameNumber(), and DisplayClusterTypesConverter::ToString().
Minutes
int32 FTimecode::Minutes
How many minutes does this timecode represent.
Definition at line 398 of file Timecode.h.
Referenced by FTimecode(), FTimecode(), FTimecode(), FromFrameNumber(), DisplayClusterTypesConverter::FromString(), IsValid(), ToFrameNumber(), and DisplayClusterTypesConverter::ToString().
Seconds
int32 FTimecode::Seconds
How many seconds does this timecode represent.
Definition at line 401 of file Timecode.h.
Referenced by FTimecode(), FTimecode(), FTimecode(), FromFrameNumber(), DisplayClusterTypesConverter::FromString(), IsValid(), ToFrameNumber(), and DisplayClusterTypesConverter::ToString().
Subframe
float FTimecode::Subframe = 0
The subframe value provided when converting to FFrameTime.
Definition at line 407 of file Timecode.h.
Referenced by FTimecode(), FTimecode(), and IsValid().
The documentation for this struct was generated from the following file:
Runtime/Core/Public/Misc/Timecode.h