Unreal Engine 5.6 C++ API: FDynamicSpriteEmitterReplayDataBase Struct Reference
FDynamicSpriteEmitterReplayDataBase Struct Reference
Source data base class for Sprite emitters.
#include "ParticleHelper.h"
Public Member Functions
FDynamicSpriteEmitterReplayDataBase ()
Constructor.
~FDynamicSpriteEmitterReplayDataBase ()
virtual void Serialize (FArchive &Ar)
Serialization.
Public Member Functions inherited from FDynamicEmitterReplayDataBase
FDynamicEmitterReplayDataBase ()
Constructor.
virtual ~FDynamicEmitterReplayDataBase ()
Data Fields
bool bLockAxis
bool bRemoveHMDRoll
bool bUseLocalSpace
bool bUseVelocityForMotionBlur
int32 CameraPayloadOffset
int32 DynamicParameterDataOffset
uint8 EmitterNormalsMode
uint8 EmitterRenderMode
float InvDeltaSeconds
int32 LightDataOffset
float LightVolumetricScatteringIntensity
uint8 LockAxisFlag
FVector3f LWCTile
UMaterialInterface * MaterialInterface
int32 MaxDrawCount
float MaxFacingCameraBlendDistance
float MinFacingCameraBlendDistance
FVector3f NormalsCylinderDirection
FVector3f NormalsSphereCenter
int32 OrbitModuleOffset
FVector2f PivotOffset
struct FParticleRequiredModule * RequiredModule
uint8 ScreenAlignment
int32 SubImages_Horizontal
int32 SubImages_Vertical
int32 SubUVDataOffset
Data Fields inherited from FDynamicEmitterReplayDataBase
int32 ActiveParticleCount
The number of particles currently active in this emitter.
FParticleDataContainer DataContainer
EDynamicEmitterType eEmitterType
The type of emitter.
FMacroUVOverride MacroUVOverride
MacroUV (override) data.
int32 ParticleStride
FVector3f Scale
int32 SortMode
Whether this emitter requires sorting as specified by artist.
Detailed Description
Source data base class for Sprite emitters.
Definition at line 1325 of file ParticleHelper.h.
Constructor & Destructor Documentation
FDynamicSpriteEmitterReplayDataBase()
FDynamicSpriteEmitterReplayDataBase::FDynamicSpriteEmitterReplayDataBase ()
Constructor.
~FDynamicSpriteEmitterReplayDataBase()
FDynamicSpriteEmitterReplayDataBase::~FDynamicSpriteEmitterReplayDataBase ()
Member Function Documentation
Serialize()
virtual void FDynamicSpriteEmitterReplayDataBase::Serialize (FArchive & Ar) virtual
Serialization.
Reimplemented from FDynamicEmitterReplayDataBase.
Reimplemented in FDynamicBeam2EmitterReplayData, FDynamicMeshEmitterReplayData, FDynamicRibbonEmitterReplayData, FDynamicSpriteEmitterReplayData, and FDynamicTrailsEmitterReplayData.
References Ar.
Referenced by FDynamicBeam2EmitterReplayData::Serialize(), FDynamicMeshEmitterReplayData::Serialize(), FDynamicSpriteEmitterReplayData::Serialize(), and FDynamicTrailsEmitterReplayData::Serialize().
Field Documentation
bLockAxis
bool FDynamicSpriteEmitterReplayDataBase::bLockAxis
Definition at line 1344 of file ParticleHelper.h.
bRemoveHMDRoll
bool FDynamicSpriteEmitterReplayDataBase::bRemoveHMDRoll
Definition at line 1351 of file ParticleHelper.h.
bUseLocalSpace
bool FDynamicSpriteEmitterReplayDataBase::bUseLocalSpace
Definition at line 1343 of file ParticleHelper.h.
bUseVelocityForMotionBlur
bool FDynamicSpriteEmitterReplayDataBase::bUseVelocityForMotionBlur
Definition at line 1350 of file ParticleHelper.h.
CameraPayloadOffset
int32 FDynamicSpriteEmitterReplayDataBase::CameraPayloadOffset
Definition at line 1339 of file ParticleHelper.h.
DynamicParameterDataOffset
int32 FDynamicSpriteEmitterReplayDataBase::DynamicParameterDataOffset
Definition at line 1336 of file ParticleHelper.h.
EmitterNormalsMode
uint8 FDynamicSpriteEmitterReplayDataBase::EmitterNormalsMode
Definition at line 1348 of file ParticleHelper.h.
EmitterRenderMode
uint8 FDynamicSpriteEmitterReplayDataBase::EmitterRenderMode
Definition at line 1347 of file ParticleHelper.h.
InvDeltaSeconds
float FDynamicSpriteEmitterReplayDataBase::InvDeltaSeconds
Definition at line 1332 of file ParticleHelper.h.
LightDataOffset
int32 FDynamicSpriteEmitterReplayDataBase::LightDataOffset
Definition at line 1337 of file ParticleHelper.h.
LightVolumetricScatteringIntensity
float FDynamicSpriteEmitterReplayDataBase::LightVolumetricScatteringIntensity
Definition at line 1338 of file ParticleHelper.h.
LockAxisFlag
uint8 FDynamicSpriteEmitterReplayDataBase::LockAxisFlag
Definition at line 1346 of file ParticleHelper.h.
LWCTile
FVector3f FDynamicSpriteEmitterReplayDataBase::LWCTile
Definition at line 1333 of file ParticleHelper.h.
MaterialInterface
UMaterialInterface* FDynamicSpriteEmitterReplayDataBase::MaterialInterface
Definition at line 1328 of file ParticleHelper.h.
MaxDrawCount
int32 FDynamicSpriteEmitterReplayDataBase::MaxDrawCount
Definition at line 1334 of file ParticleHelper.h.
MaxFacingCameraBlendDistance
float FDynamicSpriteEmitterReplayDataBase::MaxFacingCameraBlendDistance
Definition at line 1353 of file ParticleHelper.h.
MinFacingCameraBlendDistance
float FDynamicSpriteEmitterReplayDataBase::MinFacingCameraBlendDistance
Definition at line 1352 of file ParticleHelper.h.
NormalsCylinderDirection
FVector3f FDynamicSpriteEmitterReplayDataBase::NormalsCylinderDirection
Definition at line 1331 of file ParticleHelper.h.
NormalsSphereCenter
FVector3f FDynamicSpriteEmitterReplayDataBase::NormalsSphereCenter
Definition at line 1330 of file ParticleHelper.h.
OrbitModuleOffset
int32 FDynamicSpriteEmitterReplayDataBase::OrbitModuleOffset
Definition at line 1335 of file ParticleHelper.h.
PivotOffset
FVector2f FDynamicSpriteEmitterReplayDataBase::PivotOffset
Definition at line 1349 of file ParticleHelper.h.
RequiredModule
struct FParticleRequiredModule* FDynamicSpriteEmitterReplayDataBase::RequiredModule
Definition at line 1329 of file ParticleHelper.h.
ScreenAlignment
uint8 FDynamicSpriteEmitterReplayDataBase::ScreenAlignment
Definition at line 1345 of file ParticleHelper.h.
SubImages_Horizontal
int32 FDynamicSpriteEmitterReplayDataBase::SubImages_Horizontal
Definition at line 1341 of file ParticleHelper.h.
SubImages_Vertical
int32 FDynamicSpriteEmitterReplayDataBase::SubImages_Vertical
Definition at line 1342 of file ParticleHelper.h.
SubUVDataOffset
int32 FDynamicSpriteEmitterReplayDataBase::SubUVDataOffset
Definition at line 1340 of file ParticleHelper.h.
The documentation for this struct was generated from the following file:
Runtime/Engine/Public/ParticleHelper.h