Unreal Engine 5.6 C++ API: UE::MovieScene::TDuplicateChildEntityInitializer< ComponentType > Struct Template Reference
UE::MovieScene::TDuplicateChildEntityInitializer< ComponentType > Struct Template Reference
#include "MovieSceneEntityFactoryTemplates.h"
Public Member Functions
TDuplicateChildEntityInitializer (TComponentTypeID< ComponentType > InComponent)
TComponentTypeID< ComponentType > GetComponent () const
virtual void Run (const FEntityRange &ChildRange, const FEntityAllocation *ParentAllocation, TArrayView< const int32 > ParentAllocationOffsets)
Public Member Functions inherited from UE::MovieScene::FChildEntityInitializer
virtual ~FChildEntityInitializer ()
FComponentTypeID GetChildComponent () const
FComponentTypeID GetParentComponent () const
virtual bool IsRelevant (const FComponentMask &InParentType, const FComponentMask &InChildType) const
Additional Inherited Members
Protected Member Functions inherited from UE::MovieScene::FChildEntityInitializer
FChildEntityInitializer (FComponentTypeID InParentComponent, FComponentTypeID InChildComponent)
Protected Attributes inherited from UE::MovieScene::FChildEntityInitializer
FComponentTypeID ChildComponent
FComponentTypeID ParentComponent
Detailed Description
template<typename ComponentType>
struct UE::MovieScene::TDuplicateChildEntityInitializer< ComponentType >
Definition at line 86 of file MovieSceneEntityFactoryTemplates.h.
Constructor & Destructor Documentation
TDuplicateChildEntityInitializer()
template<typename ComponentType> UE::MovieScene::TDuplicateChildEntityInitializer< ComponentType >::TDuplicateChildEntityInitializer (TComponentTypeID< ComponentType > InComponent) inline explicit
Definition at line 88 of file MovieSceneEntityFactoryTemplates.h.
References UE::MovieScene::FChildEntityInitializer::FChildEntityInitializer().
Referenced by UE::MovieScene::TConditionalDuplicateChildEntityInitializer< ComponentType >::TConditionalDuplicateChildEntityInitializer().
Member Function Documentation
GetComponent()
template<typename ComponentType> TComponentTypeID< ComponentType > UE::MovieScene::TDuplicateChildEntityInitializer< ComponentType >::GetComponent () const inline
Definition at line 92 of file MovieSceneEntityFactoryTemplates.h.
References UE::MovieScene::FChildEntityInitializer::ParentComponent.
Referenced by Run().
Run()
template<typename ComponentType> virtual void UE::MovieScene::TDuplicateChildEntityInitializer< ComponentType >::Run (const FEntityRange & ChildRange, const FEntityAllocation * ParentAllocation, TArrayView< const int32 > ParentAllocationOffsets) inline virtual
Implements UE::MovieScene::FChildEntityInitializer.
Definition at line 97 of file MovieSceneEntityFactoryTemplates.h.
References GetComponent(), and TArrayView< InElementType, InSizeType >::Num().
The documentation for this struct was generated from the following file:
Runtime/MovieScene/Public/EntitySystem/MovieSceneEntityFactoryTemplates.h