Unreal Engine 5.6 C++ API: FRemoteObjectReference Struct Reference
FRemoteObjectReference Struct Reference
#include "RemoteObjectTransfer.h"
Public Member Functions
FRemoteObjectReference ()=default
FRemoteObjectReference (const FObjectPtr &Ptr)
FRemoteObjectReference (const FRemoteObjectReference &)=default
FRemoteObjectReference (const FWeakObjectPtr &WeakPtr)
template<typename T>
FRemoteObjectReference (const TObjectPtr< T > &Ptr)
template<typename T>
FRemoteObjectReference (const TWeakObjectPtr< T > &WeakPtr)
FORCEINLINE FRemoteObjectId GetRemoteId () const
FORCEINLINE FRemoteServerId GetSharingServerId () const
FORCEINLINE bool IsRemote () const
bool NetSerialize (FArchive &Ar, class UPackageMap *Map, bool &bOutSuccess)
FRemoteObjectReference & operator= (const FRemoteObjectReference &)=default
FORCEINLINE bool operator== (const FRemoteObjectReference &Other) const
UObject * Resolve () const
bool Serialize (FArchive &Ar)
FObjectPtr ToObjectPtr () const
FWeakObjectPtr ToWeakPtr () const
Private Member Functions
void NetDequantize (FRemoteObjectId InObjectId, FRemoteServerId InServerId, const FRemoteObjectPathName &InPath)
Private Attributes
FRemoteObjectId ObjectId
Object id being shared with another server.
FRemoteServerId ServerId
Id of a server that shared the object (last owner of the object)
Friends
FArchive & operator<< (FArchive &Ar, FRemoteObjectReference &Ref)
struct UE::Net::FRemoteObjectReferenceNetSerializer
Detailed Description
Definition at line 178 of file RemoteObjectTransfer.h.
Constructor & Destructor Documentation
FRemoteObjectReference() [1/6]
FRemoteObjectReference::FRemoteObjectReference () default
Referenced by FRemoteObjectReference(), FRemoteObjectReference(), FRemoteObjectReference(), operator<<, operator=(), and operator==().
FRemoteObjectReference() [2/6]
FRemoteObjectReference::FRemoteObjectReference (const FRemoteObjectReference &) default
References FRemoteObjectReference().
FRemoteObjectReference() [3/6]
FRemoteObjectReference::FRemoteObjectReference (const FObjectPtr & Ptr) explicit
FRemoteObjectReference() [4/6]
template<typename T> FRemoteObjectReference::FRemoteObjectReference (const TObjectPtr< T > & Ptr) inline explicit
Definition at line 195 of file RemoteObjectTransfer.h.
References FRemoteObjectReference().
FRemoteObjectReference() [5/6]
FRemoteObjectReference::FRemoteObjectReference (const FWeakObjectPtr & WeakPtr) explicit
FRemoteObjectReference() [6/6]
template<typename T> FRemoteObjectReference::FRemoteObjectReference (const TWeakObjectPtr< T > & WeakPtr) inline explicit
Definition at line 203 of file RemoteObjectTransfer.h.
References FRemoteObjectReference().
Member Function Documentation
GetRemoteId()
FORCEINLINE FRemoteObjectId FRemoteObjectReference::GetRemoteId () const inline
Definition at line 217 of file RemoteObjectTransfer.h.
References FORCEINLINE, and ObjectId.
GetSharingServerId()
FORCEINLINE FRemoteServerId FRemoteObjectReference::GetSharingServerId () const inline
Definition at line 221 of file RemoteObjectTransfer.h.
References FORCEINLINE, and ServerId.
IsRemote()
FORCEINLINE bool FRemoteObjectReference::IsRemote () const inline
Definition at line 225 of file RemoteObjectTransfer.h.
References FORCEINLINE, UE::RemoteObject::Handle::IsRemote(), and ObjectId.
NetDequantize()
void FRemoteObjectReference::NetDequantize (FRemoteObjectId InObjectId, FRemoteServerId InServerId, const FRemoteObjectPathName & InPath) private
NetSerialize()
bool FRemoteObjectReference::NetSerialize (FArchive & Ar, class UPackageMap * Map, bool & bOutSuccess)
References Ar, and Map.
operator=()
FRemoteObjectReference & FRemoteObjectReference::operator= (const FRemoteObjectReference &) default
References FRemoteObjectReference().
operator==()
FORCEINLINE bool FRemoteObjectReference::operator== (const FRemoteObjectReference & Other) const inline
Definition at line 208 of file RemoteObjectTransfer.h.
References FRemoteObjectReference(), FORCEINLINE, ObjectId, and Other.
Resolve()
UObject * FRemoteObjectReference::Resolve () const
Serialize()
bool FRemoteObjectReference::Serialize (FArchive & Ar) inline
Definition at line 230 of file RemoteObjectTransfer.h.
References Ar.
ToObjectPtr()
FObjectPtr FRemoteObjectReference::ToObjectPtr () const
ToWeakPtr()
FWeakObjectPtr FRemoteObjectReference::ToWeakPtr () const
Friends And Related Symbol Documentation
operator<<
FArchive & operator<< (FArchive & Ar, FRemoteObjectReference & Ref) friend
References FRemoteObjectReference(), and Ar.
UE::Net::FRemoteObjectReferenceNetSerializer
friend struct UE::Net::FRemoteObjectReferenceNetSerializer friend
Definition at line 241 of file RemoteObjectTransfer.h.
References UE::Net::FRemoteObjectReferenceNetSerializer.
Referenced by UE::Net::FRemoteObjectReferenceNetSerializer.
Field Documentation
ObjectId
FRemoteObjectId FRemoteObjectReference::ObjectId private
Object id being shared with another server.
Definition at line 182 of file RemoteObjectTransfer.h.
Referenced by GetRemoteId(), IsRemote(), and operator==().
ServerId
FRemoteServerId FRemoteObjectReference::ServerId private
Id of a server that shared the object (last owner of the object)
Definition at line 184 of file RemoteObjectTransfer.h.
Referenced by GetSharingServerId().
The documentation for this struct was generated from the following file:
Runtime/CoreUObject/Public/UObject/RemoteObjectTransfer.h