Unreal Engine 5.6 C++ API: FRDGBarrierBatchBeginId Struct Reference
FRDGBarrierBatchBeginId Struct Reference
#include "RenderGraphPass.h"
Public Member Functions
FRDGBarrierBatchBeginId ()=default
bool operator!= (FRDGBarrierBatchBeginId Other) const
bool operator== (FRDGBarrierBatchBeginId Other) const
Data Fields
FRDGPassHandlesByPipeline Passes
ERHIPipeline PipelinesAfter = ERHIPipeline::None
Friends
uint32 GetTypeHash (FRDGBarrierBatchBeginId Id)
Detailed Description
Definition at line 32 of file RenderGraphPass.h.
Constructor & Destructor Documentation
FRDGBarrierBatchBeginId()
FRDGBarrierBatchBeginId::FRDGBarrierBatchBeginId () default
Referenced by GetTypeHash, operator!=(), and operator==().
Member Function Documentation
operator!=()
bool FRDGBarrierBatchBeginId::operator!= (FRDGBarrierBatchBeginId Other) const inline
Definition at line 41 of file RenderGraphPass.h.
References FRDGBarrierBatchBeginId(), and Other.
operator==()
bool FRDGBarrierBatchBeginId::operator== (FRDGBarrierBatchBeginId Other) const inline
Definition at line 36 of file RenderGraphPass.h.
References FRDGBarrierBatchBeginId(), Other, Passes, and PipelinesAfter.
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (FRDGBarrierBatchBeginId Id) friend
Definition at line 46 of file RenderGraphPass.h.
References FRDGBarrierBatchBeginId(), GetTypeHash, Hash, HashCombineFast(), Passes, and PipelinesAfter.
Referenced by GetTypeHash.
Field Documentation
Passes
FRDGPassHandlesByPipeline FRDGBarrierBatchBeginId::Passes
Definition at line 53 of file RenderGraphPass.h.
Referenced by GetTypeHash, and operator==().
PipelinesAfter
ERHIPipeline FRDGBarrierBatchBeginId::PipelinesAfter = ERHIPipeline::None
Definition at line 54 of file RenderGraphPass.h.
Referenced by GetTypeHash, and operator==().
The documentation for this struct was generated from the following file:
Runtime/RenderCore/Public/RenderGraphPass.h