Unreal Engine 5.6 C++ API: UE::MovieScene::TPreAnimatedStateStorage_ObjectTraits< ObjectTraits > Struct Template Reference
UE::MovieScene::TPreAnimatedStateStorage_ObjectTraits< ObjectTraits > Struct Template Reference
#include "MovieScenePreAnimatedObjectStorage.h"
Public Types
using KeyType = typename ObjectTraits::KeyType
using StorageType = typename ObjectTraits::StorageType
Public Types inherited from UE::MovieScene::TPreAnimatedStateStorage< ObjectTraits >
using KeyType
The key type to use as a key in the map that associates pre-animated state values to owners (ie, an object and property name)
using StorageType
The value type this storage should store (ie, the actual property type)
Public Member Functions
TPreAnimatedStateStorage_ObjectTraits ()
IPreAnimatedObjectEntityStorage * AsObjectStorage () override
void BeginTrackingEntities (const FPreAnimatedTrackerParams &Params, TRead< FMovieSceneEntityID > EntityIDs, TRead< FRootInstanceHandle > InstanceHandles, TRead< UObject * > BoundObjects) override
void BeginTrackingEntity (FMovieSceneEntityID EntityID, bool bWantsRestoreState, FRootInstanceHandle RootInstanceHandle, UObject *BoundObject) override
void CachePreAnimatedValue (const FCachePreAnimatedValueParams &Params, const FPreAnimatedStateEntry &Entry, UObject *BoundObject)
void CachePreAnimatedValue (const FCachePreAnimatedValueParams &Params, UObject *BoundObject, EPreAnimatedCaptureSourceTracking TrackingMode=EPreAnimatedCaptureSourceTracking::CacheIfTracked)
template<typename OnCacheValue>
void CachePreAnimatedValue (const FCachePreAnimatedValueParams &Params, UObject *BoundObject, OnCacheValue &&CacheCallback, EPreAnimatedCaptureSourceTracking TrackingMode=EPreAnimatedCaptureSourceTracking::CacheIfTracked)
void CachePreAnimatedValues (const FCachePreAnimatedValueParams &Params, TArrayView< UObject *const > BoundObjects) override
FPreAnimatedStateEntry MakeEntry (UObject *BoundObject)
Public Member Functions inherited from UE::MovieScene::TPreAnimatedStateStorage< ObjectTraits >
TPreAnimatedStateStorage ()
void AddReferencedObjects (FReferenceCollector &ReferenceCollector) override
Called by the owning extension to add reference collection tracking for pre-animated state.
void AssignPreAnimatedValue (FPreAnimatedStorageIndex StorageIndex, EPreAnimatedStorageRequirement StorageRequirement, StorageType &&InNewValue)
Assign the value for a specific storage index.
void BeginTrackingAndCachePreAnimatedValues (UMovieSceneEntitySystemLinker *Linker, TComponentTypeID< ContributorTypes >... InComponentTypes)
Look at any entity with the specified component types, and set up new associations with storage indices for those entities, whilst also caching pre-animated values at the same time.
void BeginTrackingAndCachePreAnimatedValuesTask (UMovieSceneEntitySystemLinker *Linker, const TaskType &InParams, TComponentTypeID< ContributorTypes >... InComponentTypes)
Look at any entity with the specified component types, and set up new associations with storage indices for those entities, whilst also caching pre-animated values at the same time.
void BeginTrackingEntities (UMovieSceneEntitySystemLinker *Linker, TComponentTypeID< ContributorTypes >... InComponentTypes)
Look at any entity with the specified component types, and set up new associations with storage indices for those entities The provided component values are put together to make up the storage key WARNING: Does not cache actual pre-animated values.
void BeginTrackingEntitiesTask (UMovieSceneEntitySystemLinker *Linker, const TaskType &InParams, TComponentTypeID< ContributorTypes >... InComponentTypes)
Look at any entity with the specified component types, and set up new associations with storage indices for those entities The provided component values are put together to make up the storage key WARNING: Does not cache actual pre-animated values.
void BeginTrackingEntity (FMovieSceneEntityID EntityID, const bool bWantsRestoreState, FRootInstanceHandle RootInstanceHandle, ContributorTypes... InComponents)
Set up a new associations with a storage index for the given entity The provided component values are put together to make up the storage key WARNING: Does not cache actual pre-animated values.
void CachePreAnimatedValue (ContributorTypes... Values)
Save pre-animated state for the specified values, using CacheIfTracked tracking Requires that the traits class implements CachePreAnimatedValue(ContributorTypes...)
void CachePreAnimatedValues (UMovieSceneEntitySystemLinker *Linker, TComponentTypeID< ContributorTypes >... InComponentTypes)
Cache pre-animated values for entities with the specified component types.
void CachePreAnimatedValuesTask (UMovieSceneEntitySystemLinker *Linker, const TaskType &InParams, TComponentTypeID< ContributorTypes >... InComponentTypes)
Cache pre-animated values for entities with the specified component types.
void CacheTrackedPreAnimatedValue (EPreAnimatedCaptureSourceTracking TrackingMode, ContributorTypes... Values)
Save pre-animated state for the specified values Requires that the traits class implements CachePreAnimatedValue(ContributorTypes...)
EPreAnimatedStorageRequirement DiscardPreAnimatedStateStorage (FPreAnimatedStorageIndex StorageIndex, EPreAnimatedStorageRequirement SourceRequirement) override
Discard a specified index within this storage container.
FPreAnimatedStateEntry FindEntry (KeyArgs &&... InKeyArgs)
Given a list of arguments suitable for building a storage key, builds that key, and then tries to find an existing pre-animated state entry for that key if it already exists.
FPreAnimatedStorageIndex FindStorageIndex (const KeyType &InKey) const
Attempt to find a storage index for the specified key.
void ForciblyPersistStorage (FPreAnimatedStorageIndex StorageIndex)
Cause a previously cached value to always outlive any actively animating sources.
const StorageType & GetCachedValue (FPreAnimatedStorageIndex StorageIndex) const
Get the cached value associated with a particular storage index.
const KeyType & GetKey (FPreAnimatedStorageIndex StorageIndex) const
Get the key associated with a particular storage index.
FPreAnimatedStorageIndex GetOrCreateStorageIndex (const KeyType &InKey)
Attempt to find a storage index for the specified key, creating a new one if it doesn't exist.
FPreAnimatedStorageID GetStorageType () const override
Retrieve the ID that uniquely identifies this storage container.
bool HasEverAnimated (FPreAnimatedStorageIndex StorageIndex) const
Check whether we have ever animated the specified storage index.
void Initialize (FPreAnimatedStorageID InStorageID, FPreAnimatedStateExtension *InParentExtension) override
Called when this storage is created inside the pre-animated state extension on a UMovieSceneEntitySystemLinker.
bool IsCapturingGlobalState () const
bool IsStorageInitialized (FPreAnimatedStorageIndex StorageIndex) const
Check whether a piece of cached storage has been initialized yet.
bool IsStorageRequirementSatisfied (FPreAnimatedStorageIndex StorageIndex, EPreAnimatedStorageRequirement StorageRequirement) const
Check whether the storage for a given index and requirement has already been initialized.
FPreAnimatedStateEntry MakeEntry (KeyArgs &&... InKeyArgs)
Creates a new pre-animated state entry from a list of arguments suitable for building the storage key.
void OnObjectReplaced (FPreAnimatedStorageIndex StorageIndex, const FObjectKey &OldObject, const FObjectKey &NewObject) override
TPreAnimatedStateStorage & operator= (const TPreAnimatedStateStorage &)=delete
void ReplaceKey (FPreAnimatedStorageIndex StorageIndex, const KeyType &NewKey)
Replace the key associated with a particular storage index.
EPreAnimatedStorageRequirement RestorePreAnimatedStateStorage (FPreAnimatedStorageIndex StorageIndex, EPreAnimatedStorageRequirement SourceRequirement, EPreAnimatedStorageRequirement TargetRequirement, const FRestoreStateParams &Params) override
Restore a specified index within this storage container.
void SetRestoreMask (const IRestoreMask *InRestoreMask)
Called prior to restoring pre-animated state to control whether this storage should restore state or not.
Public Member Functions inherited from UE::MovieScene::IPreAnimatedStorage
virtual ~IPreAnimatedStorage ()
virtual IPreAnimatedObjectPropertyStorage * AsPropertyStorage ()
Public Member Functions inherited from TSharedFromThis< IPreAnimatedStorage >
TSharedRef< IPreAnimatedStorage, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< IPreAnimatedStorage, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Additional Inherited Members
Data Fields inherited from UE::MovieScene::TPreAnimatedStateStorage< ObjectTraits >
ObjectTraits Traits
Traits instance - normally not required but some traits require state.
Protected Member Functions inherited from UE::MovieScene::TPreAnimatedStateStorage< ObjectTraits >
bool ShouldTrackCaptureSource (EPreAnimatedCaptureSourceTracking TrackingMode, KeyArgs &&... InKeyArgs)
void TrackCaptureSource (const FPreAnimatedStateEntry &Entry, EPreAnimatedCaptureSourceTracking TrackingMode)
Begins tracking the current entry with the currently set tracking source, if necessary/desirable.
Protected Member Functions inherited from TSharedFromThis< IPreAnimatedStorage >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions inherited from TSharedFromThis< IPreAnimatedStorage >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Protected Attributes inherited from UE::MovieScene::TPreAnimatedStateStorage< ObjectTraits >
TMap< KeyType, FPreAnimatedStorageIndex > KeyToStorageIndex
Map that associates a storage index with a key.
FPreAnimatedStateExtension * ParentExtension
Pointer to our parent extension.
TSparseArray< FCachedData > PreAnimatedStorage
Sparse array of cached data that represents persistent, or both persistent and transient storage (but never exclusively transient storage).
const IRestoreMask * RestoreMask
Temporary restoration mask.
FPreAnimatedStorageID StorageID
Our storage ID.
TSortedMap< FPreAnimatedStorageIndex, StorageType > TransientPreAnimatedStorage
Storage that holds values that need to be kept transiently (for evaluation).
Detailed Description
template<typename ObjectTraits>
struct UE::MovieScene::TPreAnimatedStateStorage_ObjectTraits< ObjectTraits >
Definition at line 97 of file MovieScenePreAnimatedObjectStorage.h.
Member Typedef Documentation
KeyType
template<typename ObjectTraits> using UE::MovieScene::TPreAnimatedStateStorage_ObjectTraits< ObjectTraits >::KeyType = typename ObjectTraits::KeyType
Definition at line 101 of file MovieScenePreAnimatedObjectStorage.h.
StorageType
template<typename ObjectTraits> using UE::MovieScene::TPreAnimatedStateStorage_ObjectTraits< ObjectTraits >::StorageType = typename ObjectTraits::StorageType
Definition at line 102 of file MovieScenePreAnimatedObjectStorage.h.
Constructor & Destructor Documentation
TPreAnimatedStateStorage_ObjectTraits()
template<typename ObjectTraits> UE::MovieScene::TPreAnimatedStateStorage_ObjectTraits< ObjectTraits >::TPreAnimatedStateStorage_ObjectTraits () inline
Definition at line 106 of file MovieScenePreAnimatedObjectStorage.h.
Member Function Documentation
AsObjectStorage()
template<typename ObjectTraits> IPreAnimatedObjectEntityStorage * UE::MovieScene::TPreAnimatedStateStorage_ObjectTraits< ObjectTraits >::AsObjectStorage () inline override virtual
Reimplemented from UE::MovieScene::IPreAnimatedStorage.
Definition at line 111 of file MovieScenePreAnimatedObjectStorage.h.
BeginTrackingEntities()
template<typename ObjectTraits> void UE::MovieScene::TPreAnimatedStateStorage_ObjectTraits< ObjectTraits >::BeginTrackingEntities (const FPreAnimatedTrackerParams & Params, TRead< FMovieSceneEntityID > EntityIDs, TRead< FRootInstanceHandle > InstanceHandles, TRead< UObject * > BoundObjects) inline override virtual
Implements UE::MovieScene::IPreAnimatedObjectEntityStorage.
Definition at line 116 of file MovieScenePreAnimatedObjectStorage.h.
References UE::MovieScene::FPreAnimatedEntityCaptureSource::BeginTrackingEntity(), UE::MovieScene::TPreAnimatedStateStorage< ObjectTraits >::GetOrCreateStorageIndex(), Key, Num, Params, UE::MovieScene::TPreAnimatedStateStorage< ObjectTraits >::ParentExtension, UE::MovieScene::TPreAnimatedStateStorage< ObjectTraits >::StorageID, and UE::MovieScene::TPreAnimatedStateStorage< ObjectTraits >::Traits.
BeginTrackingEntity()
template<typename ObjectTraits> void UE::MovieScene::TPreAnimatedStateStorage_ObjectTraits< ObjectTraits >::BeginTrackingEntity (FMovieSceneEntityID EntityID, bool bWantsRestoreState, FRootInstanceHandle RootInstanceHandle, UObject * BoundObject) inline override virtual
Implements UE::MovieScene::IPreAnimatedObjectEntityStorage.
Definition at line 149 of file MovieScenePreAnimatedObjectStorage.h.
References UE::MovieScene::FPreAnimatedEntityCaptureSource::BeginTrackingEntity(), MakeEntry(), and UE::MovieScene::TPreAnimatedStateStorage< ObjectTraits >::ParentExtension.
CachePreAnimatedValue() [1/3]
template<typename ObjectTraits> void UE::MovieScene::TPreAnimatedStateStorage_ObjectTraits< ObjectTraits >::CachePreAnimatedValue (const FCachePreAnimatedValueParams & Params, const FPreAnimatedStateEntry & Entry, UObject * BoundObject) inline
Definition at line 185 of file MovieScenePreAnimatedObjectStorage.h.
References UE::MovieScene::TPreAnimatedStateStorage< ObjectTraits >::AssignPreAnimatedValue(), UE::MovieScene::TPreAnimatedStateStorage< ObjectTraits >::ForciblyPersistStorage(), UE::MovieScene::TPreAnimatedStateStorage< ObjectTraits >::IsStorageRequirementSatisfied(), MoveTemp(), Params, UE::MovieScene::TPreAnimatedStateStorage< ObjectTraits >::ParentExtension, UE::MovieScene::FPreAnimatedStateCachedValueHandle::StorageIndex, UE::MovieScene::TPreAnimatedStateStorage< ObjectTraits >::Traits, and UE::MovieScene::FPreAnimatedStateEntry::ValueHandle.
CachePreAnimatedValue() [2/3]
template<typename ObjectTraits> void UE::MovieScene::TPreAnimatedStateStorage_ObjectTraits< ObjectTraits >::CachePreAnimatedValue (const FCachePreAnimatedValueParams & Params, UObject * BoundObject, EPreAnimatedCaptureSourceTracking TrackingMode = EPreAnimatedCaptureSourceTracking::CacheIfTracked) inline
Definition at line 173 of file MovieScenePreAnimatedObjectStorage.h.
References UE::MovieScene::CacheIfTracked, CachePreAnimatedValue(), MakeEntry(), Params, UE::MovieScene::TPreAnimatedStateStorage< ObjectTraits >::ShouldTrackCaptureSource(), and UE::MovieScene::TPreAnimatedStateStorage< ObjectTraits >::TrackCaptureSource().
Referenced by CachePreAnimatedValue(), and CachePreAnimatedValues().
CachePreAnimatedValue() [3/3]
template<typename ObjectTraits> template<typename OnCacheValue> void UE::MovieScene::TPreAnimatedStateStorage_ObjectTraits< ObjectTraits >::CachePreAnimatedValue (const FCachePreAnimatedValueParams & Params, UObject * BoundObject, OnCacheValue && CacheCallback, EPreAnimatedCaptureSourceTracking TrackingMode = EPreAnimatedCaptureSourceTracking::CacheIfTracked) inline
Definition at line 203 of file MovieScenePreAnimatedObjectStorage.h.
References UE::MovieScene::TPreAnimatedStateStorage< ObjectTraits >::AssignPreAnimatedValue(), UE::MovieScene::CacheIfTracked, UE::MovieScene::TPreAnimatedStateStorage< ObjectTraits >::ForciblyPersistStorage(), UE::MovieScene::TPreAnimatedStateStorage< ObjectTraits >::IsStorageRequirementSatisfied(), Key, MakeEntry(), MoveTemp(), Params, UE::MovieScene::TPreAnimatedStateStorage< ObjectTraits >::ParentExtension, UE::MovieScene::TPreAnimatedStateStorage< ObjectTraits >::ShouldTrackCaptureSource(), UE::MovieScene::FPreAnimatedStateCachedValueHandle::StorageIndex, UE::MovieScene::TPreAnimatedStateStorage< ObjectTraits >::TrackCaptureSource(), and UE::MovieScene::FPreAnimatedStateEntry::ValueHandle.
CachePreAnimatedValues()
template<typename ObjectTraits> void UE::MovieScene::TPreAnimatedStateStorage_ObjectTraits< ObjectTraits >::CachePreAnimatedValues (const FCachePreAnimatedValueParams & Params, TArrayView< UObject *const > BoundObjects) inline override virtual
Implements UE::MovieScene::IPreAnimatedObjectEntityStorage.
Definition at line 162 of file MovieScenePreAnimatedObjectStorage.h.
References CachePreAnimatedValue(), and Params.
MakeEntry()
template<typename ObjectTraits> FPreAnimatedStateEntry UE::MovieScene::TPreAnimatedStateStorage_ObjectTraits< ObjectTraits >::MakeEntry (UObject * BoundObject) inline
Definition at line 140 of file MovieScenePreAnimatedObjectStorage.h.
References UE::MovieScene::TPreAnimatedStateStorage< ObjectTraits >::GetOrCreateStorageIndex(), Key, UE::MovieScene::TPreAnimatedStateStorage< ObjectTraits >::StorageID, and UE::MovieScene::TPreAnimatedStateStorage< ObjectTraits >::Traits.
Referenced by BeginTrackingEntity(), CachePreAnimatedValue(), and CachePreAnimatedValue().
The documentation for this struct was generated from the following file:
Runtime/MovieScene/Public/Evaluation/PreAnimatedState/MovieScenePreAnimatedObjectStorage.h