Unreal Engine 5.6 C++ API: UE::Sequencer::FParentFirstChildIterator Struct Reference
UE::Sequencer::FParentFirstChildIterator Struct Reference
A depth-first iterator into a hierarchy of data models.
#include "ViewModelIterators.h"
Public Member Functions
SEQUENCERCORE_API FParentFirstChildIterator (const TSharedPtr< FViewModel > &StartAt, bool bIncludeThis=false, EViewModelListType InFilter=EViewModelListType::Everything)
FParentFirstChildIterator (EViewModelListType InFilter=EViewModelListType::Everything)
FORCEINLINE FParentFirstChildIterator begin () const
FORCEINLINE FParentFirstChildIterator end () const
FORCEINLINE int32 GetCurrentDepth () const
FORCEINLINE const FViewModelPtr & GetCurrentItem () const
FORCEINLINE void IgnoreCurrentChildren ()
Request that this iterator ignore any and all children of the current model.
FORCEINLINE operator bool () const
FORCEINLINE const FViewModelPtr & operator* () const
FORCEINLINE void operator++ ()
FORCEINLINE FViewModel * operator-> () const
FORCEINLINE void SetMaxDepth ()
FORCEINLINE void SetMaxDepth (int32 InDepthLimit)
Protected Member Functions
SEQUENCERCORE_API void IterateToNext ()
SEQUENCERCORE_API bool IterateToNextChild ()
SEQUENCERCORE_API void IterateToNextSibling ()
Protected Attributes
bool bIgnoreCurrentChildren
Flag that signals this iterator to skip all children of the current item and iterate directly to its sibling.
FViewModelPtr CurrentItem
The model currently pointed to by this iterator.
int32 DepthLimit
Maximum depth that this iterator is allowed to recurse to.
EViewModelListType Filter
List type filter to allow skipping of different child lists.
TArray< FViewModelListIterator, TInlineAllocator< 8 > > IterStack
Stack of parent's that have been visited in the current branch.
Friends
FORCEINLINE friend bool operator!= (const FParentFirstChildIterator &A, const FParentFirstChildIterator &B)
Detailed Description
A depth-first iterator into a hierarchy of data models.
It iterates over all registered children lists of each model.
Definition at line 338 of file ViewModelIterators.h.
Constructor & Destructor Documentation
FParentFirstChildIterator() [1/2]
UE::Sequencer::FParentFirstChildIterator::FParentFirstChildIterator (EViewModelListType InFilter = EViewModelListType::Everything) inline
Definition at line 340 of file ViewModelIterators.h.
References bIgnoreCurrentChildren, DepthLimit, UE::Sequencer::Everything, and Filter.
Referenced by begin(), end(), and operator!=.
FParentFirstChildIterator() [2/2]
SEQUENCERCORE_API UE::Sequencer::FParentFirstChildIterator::FParentFirstChildIterator (const TSharedPtr< FViewModel > & StartAt, bool bIncludeThis = false, EViewModelListType InFilter = EViewModelListType::Everything)
References UE::Sequencer::Everything.
Member Function Documentation
begin()
FORCEINLINE FParentFirstChildIterator UE::Sequencer::FParentFirstChildIterator::begin () const inline
Definition at line 403 of file ViewModelIterators.h.
References FParentFirstChildIterator(), and FORCEINLINE.
end()
FORCEINLINE FParentFirstChildIterator UE::Sequencer::FParentFirstChildIterator::end () const inline
Definition at line 404 of file ViewModelIterators.h.
References FParentFirstChildIterator(), and FORCEINLINE.
GetCurrentDepth()
FORCEINLINE int32 UE::Sequencer::FParentFirstChildIterator::GetCurrentDepth () const inline
Definition at line 348 of file ViewModelIterators.h.
References FORCEINLINE, and IterStack.
GetCurrentItem()
FORCEINLINE const FViewModelPtr & UE::Sequencer::FParentFirstChildIterator::GetCurrentItem () const inline
Definition at line 352 of file ViewModelIterators.h.
References CurrentItem, and FORCEINLINE.
IgnoreCurrentChildren()
FORCEINLINE void UE::Sequencer::FParentFirstChildIterator::IgnoreCurrentChildren () inline
Request that this iterator ignore any and all children of the current model.
Note
: Does not change the state of this iterator until it is incremented
Definition at line 398 of file ViewModelIterators.h.
References bIgnoreCurrentChildren, and FORCEINLINE.
IterateToNext()
SEQUENCERCORE_API void UE::Sequencer::FParentFirstChildIterator::IterateToNext () protected
Referenced by operator++().
IterateToNextChild()
SEQUENCERCORE_API bool UE::Sequencer::FParentFirstChildIterator::IterateToNextChild () protected
IterateToNextSibling()
SEQUENCERCORE_API void UE::Sequencer::FParentFirstChildIterator::IterateToNextSibling () protected
Referenced by operator++().
operator bool()
FORCEINLINE UE::Sequencer::FParentFirstChildIterator::operator bool () const inline explicit
Definition at line 364 of file ViewModelIterators.h.
References CurrentItem, and FORCEINLINE.
operator*()
FORCEINLINE const FViewModelPtr & UE::Sequencer::FParentFirstChildIterator::operator* () const inline
Definition at line 356 of file ViewModelIterators.h.
References CurrentItem, and FORCEINLINE.
operator++()
FORCEINLINE void UE::Sequencer::FParentFirstChildIterator::operator++ () inline
Definition at line 368 of file ViewModelIterators.h.
References bIgnoreCurrentChildren, FORCEINLINE, IterateToNext(), and IterateToNextSibling().
operator->()
FORCEINLINE FViewModel * UE::Sequencer::FParentFirstChildIterator::operator-> () const inline
Definition at line 360 of file ViewModelIterators.h.
References CurrentItem, and FORCEINLINE.
SetMaxDepth() [1/2]
FORCEINLINE void UE::Sequencer::FParentFirstChildIterator::SetMaxDepth () inline
Definition at line 381 of file ViewModelIterators.h.
References DepthLimit, FORCEINLINE, and IterStack.
SetMaxDepth() [2/2]
FORCEINLINE void UE::Sequencer::FParentFirstChildIterator::SetMaxDepth (int32 InDepthLimit) inline
Definition at line 385 of file ViewModelIterators.h.
References DepthLimit, and FORCEINLINE.
Friends And Related Symbol Documentation
operator!=
FORCEINLINE friend bool operator!= (const FParentFirstChildIterator & A, const FParentFirstChildIterator & B) friend
Definition at line 389 of file ViewModelIterators.h.
References FParentFirstChildIterator(), A, B, and FORCEINLINE.
Field Documentation
bIgnoreCurrentChildren
bool UE::Sequencer::FParentFirstChildIterator::bIgnoreCurrentChildren protected
Flag that signals this iterator to skip all children of the current item and iterate directly to its sibling.
Definition at line 429 of file ViewModelIterators.h.
Referenced by FParentFirstChildIterator(), IgnoreCurrentChildren(), and operator++().
CurrentItem
FViewModelPtr UE::Sequencer::FParentFirstChildIterator::CurrentItem protected
The model currently pointed to by this iterator.
Definition at line 417 of file ViewModelIterators.h.
Referenced by GetCurrentItem(), operator bool(), operator*(), and operator->().
DepthLimit
int32 UE::Sequencer::FParentFirstChildIterator::DepthLimit protected
Maximum depth that this iterator is allowed to recurse to.
Definition at line 426 of file ViewModelIterators.h.
Referenced by FParentFirstChildIterator(), SetMaxDepth(), and SetMaxDepth().
Filter
EViewModelListType UE::Sequencer::FParentFirstChildIterator::Filter protected
List type filter to allow skipping of different child lists.
Definition at line 423 of file ViewModelIterators.h.
Referenced by FParentFirstChildIterator().
IterStack
TArray<FViewModelListIterator, TInlineAllocator<8> > UE::Sequencer::FParentFirstChildIterator::IterStack protected
Stack of parent's that have been visited in the current branch.
Definition at line 420 of file ViewModelIterators.h.
Referenced by GetCurrentDepth(), and SetMaxDepth().
The documentation for this struct was generated from the following file:
Editor/SequencerCore/Public/MVVM/ViewModels/ViewModelIterators.h