Unreal Engine 5.6 C++ API: FCurveEditorScreenSpace Struct Reference
FCurveEditorScreenSpace Struct Reference
Utility struct used for converting to/from curve editor screen space.
#include "CurveEditorScreenSpace.h"
Public Member Functions
FCurveEditorScreenSpace (FVector2D InPixelSize, double InInputMin, double InInputMax, double InOutputMin, double InOutputMax)
Construction from a physical size, and input/output range.
FORCEINLINE FVector2D GetPhysicalSize () const
Get the physical size of the screen.
bool operator!= (const FCurveEditorScreenSpace &Other)
bool operator== (const FCurveEditorScreenSpace &Other) const
FCurveEditorScreenSpace ToCurveSpace (const FTransform2d &CurveTransform) const
Transform this screen space into a curve space using the specified transform.
Public Member Functions inherited from FCurveEditorScreenSpaceH
FCurveEditorScreenSpaceH (double InPixelWidth, double InInputMin, double InInputMax)
Construction from a physical size, and input/output range.
FORCEINLINE double GetInputMax () const
Get the maximum input value displayed on the screen.
FORCEINLINE double GetInputMin () const
Get the minimum input value displayed on the screen.
FORCEINLINE double GetPhysicalWidth () const
Get the physical width of the screen.
FORCEINLINE double PixelsPerInput () const
Retrieve the number of slate units per input value.
FORCEINLINE double ScreenToSeconds (double ScreenPosition) const
Convert a horizontal screen position in slate units to a value in seconds.
FORCEINLINE double SecondsToScreen (double InSeconds) const
Convert a value in seconds to a horizontal screen position in slate units.
FCurveEditorScreenSpaceH ToCurveSpace (const FTransform2d &CurveTransform) const
Transform this screen space into a curve space using the specified transform.
Public Member Functions inherited from FCurveEditorScreenSpaceV
FCurveEditorScreenSpaceV (double InPixelHeight, double InOutputMin, double InOutputMax)
Construction from a physical size, and input/output range.
FORCEINLINE double GetOutputMax () const
Get the maximum output value displayed on the screen.
FORCEINLINE double GetOutputMin () const
Get the minimum output value displayed on the screen.
FORCEINLINE double GetPhysicalHeight () const
Get the physical height of the screen.
FORCEINLINE double PixelsPerOutput () const
Retrieve the number of slate units per output value.
FORCEINLINE double ScreenToValue (double ScreenPosition) const
Convert a vertical screen position in slate units to a value.
FCurveEditorScreenSpaceV ToCurveSpace (const FTransform2d &CurveTransform) const
Transform this screen space into a curve space using the specified transform.
double ValueToScreen (double InValue) const
Convert a value to a vertical screen position in slate units.
Detailed Description
Utility struct used for converting to/from curve editor screen space.
Definition at line 166 of file CurveEditorScreenSpace.h.
Constructor & Destructor Documentation
FCurveEditorScreenSpace()
FCurveEditorScreenSpace::FCurveEditorScreenSpace (FVector2D InPixelSize, double InInputMin, double InInputMax, double InOutputMin, double InOutputMax) inline
Construction from a physical size, and input/output range.
Definition at line 171 of file CurveEditorScreenSpace.h.
References FCurveEditorScreenSpaceH::FCurveEditorScreenSpaceH(), FCurveEditorScreenSpaceV::FCurveEditorScreenSpaceV(), X, and Y.
Referenced by operator!=(), operator==(), and ToCurveSpace().
Member Function Documentation
GetPhysicalSize()
FORCEINLINE FVector2D FCurveEditorScreenSpace::GetPhysicalSize () const inline
Get the physical size of the screen.
Definition at line 179 of file CurveEditorScreenSpace.h.
References FORCEINLINE, FCurveEditorScreenSpaceV::GetPhysicalHeight(), and FCurveEditorScreenSpaceH::GetPhysicalWidth().
operator!=()
bool FCurveEditorScreenSpace::operator!= (const FCurveEditorScreenSpace & Other) inline
Definition at line 209 of file CurveEditorScreenSpace.h.
References FCurveEditorScreenSpace(), and Other.
operator==()
bool FCurveEditorScreenSpace::operator== (const FCurveEditorScreenSpace & Other) const inline
Definition at line 198 of file CurveEditorScreenSpace.h.
References FCurveEditorScreenSpace(), FCurveEditorScreenSpaceH::GetInputMax(), FCurveEditorScreenSpaceV::GetOutputMax(), FCurveEditorScreenSpaceV::GetOutputMin(), FCurveEditorScreenSpaceV::GetPhysicalHeight(), FCurveEditorScreenSpaceH::GetPhysicalWidth(), and Other.
ToCurveSpace()
FCurveEditorScreenSpace FCurveEditorScreenSpace::ToCurveSpace (const FTransform2d & CurveTransform) const inline
Transform this screen space into a curve space using the specified transform.
Definition at line 186 of file CurveEditorScreenSpace.h.
References FCurveEditorScreenSpace(), FCurveEditorScreenSpaceH::FCurveEditorScreenSpaceH(), FCurveEditorScreenSpaceV::FCurveEditorScreenSpaceV(), New(), FCurveEditorScreenSpaceH::ToCurveSpace(), and FCurveEditorScreenSpaceV::ToCurveSpace().
The documentation for this struct was generated from the following file:
Editor/CurveEditor/Public/CurveEditorScreenSpace.h