Unreal Engine 5.6 C++ API: FMovieSceneKeyStructHelper Struct Reference
FMovieSceneKeyStructHelper Struct Reference
Helper class that marshals user-facing data from an edit UI into particluar keys on various underlying channels.
#include "MovieSceneKeyStructHelper.h"
Public Member Functions
FMovieSceneKeyStructHelper ()=default
Default construction.
FMovieSceneKeyStructHelper (const FMovieSceneKeyStructHelper &)=delete
Non-copyable.
MOVIESCENE_API void Add (FMovieSceneChannelValueHelper &&InHelper)
Add a particular key value to this helper that should be applied when the edit UI is committed.
MOVIESCENE_API void Apply (FFrameNumber InUnifiedTime)
Propagate the user-facing UI values to the keys that are being represented in this class.
MOVIESCENE_API TOptional< FFrameNumber > GetUnifiedKeyTime () const
Get unified starting time that should be shown on the UI.
FMovieSceneKeyStructHelper & operator= (const FMovieSceneKeyStructHelper &)=delete
MOVIESCENE_API void SetStartingValues ()
Set the user facing values on the UI based on the unified starting time.
Private Attributes
TArray< FMovieSceneChannelValueHelper > Helpers
Array of value accessors that are being shown on the edit UI.
TOptional< FFrameNumber > UnifiedKeyTime
Unified key time that represents all the keys.
Detailed Description
Helper class that marshals user-facing data from an edit UI into particluar keys on various underlying channels.
Definition at line 23 of file MovieSceneKeyStructHelper.h.
Constructor & Destructor Documentation
FMovieSceneKeyStructHelper() [1/2]
FMovieSceneKeyStructHelper::FMovieSceneKeyStructHelper () default
Default construction.
Referenced by FMovieSceneKeyStructHelper(), and operator=().
FMovieSceneKeyStructHelper() [2/2]
FMovieSceneKeyStructHelper::FMovieSceneKeyStructHelper (const FMovieSceneKeyStructHelper &) delete
Non-copyable.
References FMovieSceneKeyStructHelper().
Member Function Documentation
Add()
MOVIESCENE_API void FMovieSceneKeyStructHelper::Add (FMovieSceneChannelValueHelper && InHelper)
Add a particular key value to this helper that should be applied when the edit UI is committed.
Parameters
InHelper The utility class to add, bound to the key handle it wants to edit
Apply()
MOVIESCENE_API void FMovieSceneKeyStructHelper::Apply (FFrameNumber InUnifiedTime)
Propagate the user-facing UI values to the keys that are being represented in this class.
Parameters
InUnifiedTime A time to set all keys to
GetUnifiedKeyTime()
MOVIESCENE_API TOptional< FFrameNumber > FMovieSceneKeyStructHelper::GetUnifiedKeyTime () const
Get unified starting time that should be shown on the UI.
operator=()
FMovieSceneKeyStructHelper & FMovieSceneKeyStructHelper::operator= (const FMovieSceneKeyStructHelper &) delete
References FMovieSceneKeyStructHelper().
SetStartingValues()
MOVIESCENE_API void FMovieSceneKeyStructHelper::SetStartingValues ()
Set the user facing values on the UI based on the unified starting time.
Field Documentation
Helpers
TArray<FMovieSceneChannelValueHelper> FMovieSceneKeyStructHelper::Helpers private
Array of value accessors that are being shown on the edit UI.
Definition at line 65 of file MovieSceneKeyStructHelper.h.
UnifiedKeyTime
TOptional<FFrameNumber> FMovieSceneKeyStructHelper::UnifiedKeyTime private
Unified key time that represents all the keys.
Definition at line 62 of file MovieSceneKeyStructHelper.h.
The documentation for this struct was generated from the following file:
Runtime/MovieScene/Public/MovieSceneKeyStructHelper.h