Unreal Engine 5.6 C++ API: FPrimaryAssetType Struct Reference
FPrimaryAssetType Struct Reference
A primary asset type, represented as an FName internally and implicitly convertible back and forth This exists so the blueprint API can understand it's not a normal FName.
#include "PrimaryAssetId.h"
Public Member Functions
FPrimaryAssetType ()=default
Convert from FName.
FPrimaryAssetType (const ANSICHAR *InName)
FPrimaryAssetType (const FPrimaryAssetType &)=default
FPrimaryAssetType (const WIDECHAR *InName)
FPrimaryAssetType (EName InName)
FPrimaryAssetType (FName InName)
FPrimaryAssetType (FPrimaryAssetType &&)=default
void AppendString (FStringBuilderBase &Builder) const
Appends to the given builder the string version of this Type.
bool ExportTextItem (FString &ValueStr, FPrimaryAssetType const &DefaultValue, UObject *Parent, int32 PortFlags, UObject *ExportRootScope) const
UStruct Overrides.
bool FastLess (const FPrimaryAssetType &Other) const
FName GetName () const
Returns internal Name explicitly, not normally needed.
bool ImportTextItem (const TCHAR *&Buffer, int32 PortFlags, UObject *Parent, FOutputDevice *ErrorText)
bool IsValid () const
Returns true if this is a valid Type.
bool LexicalLess (const FPrimaryAssetType &Other) const
operator const FName & () const
operator FName & ()
Convert to FName.
bool operator!= (const FPrimaryAssetType &Other) const
FPrimaryAssetType & operator= (const FPrimaryAssetType &)=default
FPrimaryAssetType & operator= (FPrimaryAssetType &&)=default
bool operator== (const FPrimaryAssetType &Other) const
bool SerializeFromMismatchedTag (struct FPropertyTag const &Tag, FStructuredArchive::FSlot Slot)
FString ToString () const
Returns string version of this Type.
Private Attributes
FName Name
The FName representing this type.
Friends
uint32 GetTypeHash (const FPrimaryAssetType &Key)
struct Z_Construct_UScriptStruct_FPrimaryAssetType_Statics
Detailed Description
A primary asset type, represented as an FName internally and implicitly convertible back and forth This exists so the blueprint API can understand it's not a normal FName.
Definition at line 23 of file PrimaryAssetId.h.
Constructor & Destructor Documentation
FPrimaryAssetType() [1/7]
FPrimaryAssetType::FPrimaryAssetType () default
Convert from FName.
Referenced by FPrimaryAssetType(), FPrimaryAssetType(), ExportTextItem(), FastLess(), GetTypeHash, LexicalLess(), operator!=(), operator=(), operator=(), and operator==().
FPrimaryAssetType() [2/7]
FPrimaryAssetType::FPrimaryAssetType (FName InName) inline
Definition at line 27 of file PrimaryAssetId.h.
References InName, and Name.
FPrimaryAssetType() [3/7]
FPrimaryAssetType::FPrimaryAssetType (EName InName) inline
Definition at line 28 of file PrimaryAssetId.h.
References InName, and Name.
FPrimaryAssetType() [4/7]
FPrimaryAssetType::FPrimaryAssetType (const WIDECHAR * InName) inline
Definition at line 29 of file PrimaryAssetId.h.
References InName, and Name.
FPrimaryAssetType() [5/7]
FPrimaryAssetType::FPrimaryAssetType (const ANSICHAR * InName) inline
Definition at line 30 of file PrimaryAssetId.h.
References InName, and Name.
FPrimaryAssetType() [6/7]
FPrimaryAssetType::FPrimaryAssetType (const FPrimaryAssetType &) default
References FPrimaryAssetType().
FPrimaryAssetType() [7/7]
FPrimaryAssetType::FPrimaryAssetType (FPrimaryAssetType &&) default
References FPrimaryAssetType().
Member Function Documentation
AppendString()
void FPrimaryAssetType::AppendString (FStringBuilderBase & Builder) const inline
Appends to the given builder the string version of this Type.
Definition at line 70 of file PrimaryAssetId.h.
References Name.
ExportTextItem()
bool FPrimaryAssetType::ExportTextItem (FString & ValueStr, FPrimaryAssetType const & DefaultValue, UObject * Parent, int32 PortFlags, UObject * ExportRootScope) const
UStruct Overrides.
References FPrimaryAssetType(), and Parent.
FastLess()
bool FPrimaryAssetType::FastLess (const FPrimaryAssetType & Other) const inline
Definition at line 90 of file PrimaryAssetId.h.
References FPrimaryAssetType(), Name, and Other.
GetName()
FName FPrimaryAssetType::GetName () const inline
Returns internal Name explicitly, not normally needed.
Definition at line 42 of file PrimaryAssetId.h.
References Name.
Referenced by FAssetIdentifier::operator<<.
ImportTextItem()
bool FPrimaryAssetType::ImportTextItem (const TCHAR *& Buffer, int32 PortFlags, UObject * Parent, FOutputDevice * ErrorText)
References Buffer, and Parent.
IsValid()
bool FPrimaryAssetType::IsValid () const inline
Returns true if this is a valid Type.
Definition at line 58 of file PrimaryAssetId.h.
References Name.
Referenced by FAssetIdentifier::operator<<.
LexicalLess()
bool FPrimaryAssetType::LexicalLess (const FPrimaryAssetType & Other) const inline
Definition at line 85 of file PrimaryAssetId.h.
References FPrimaryAssetType(), Name, and Other.
operator const FName &()
FPrimaryAssetType::operator const FName & () const inline
Definition at line 39 of file PrimaryAssetId.h.
References Name.
operator FName &()
FPrimaryAssetType::operator FName & () inline
Convert to FName.
Definition at line 38 of file PrimaryAssetId.h.
References Name.
operator!=()
bool FPrimaryAssetType::operator!= (const FPrimaryAssetType & Other) const inline
Definition at line 52 of file PrimaryAssetId.h.
References FPrimaryAssetType(), Name, and Other.
operator=() [1/2]
FPrimaryAssetType & FPrimaryAssetType::operator= (const FPrimaryAssetType &) default
References FPrimaryAssetType().
operator=() [2/2]
FPrimaryAssetType & FPrimaryAssetType::operator= (FPrimaryAssetType &&) default
References FPrimaryAssetType().
operator==()
bool FPrimaryAssetType::operator== (const FPrimaryAssetType & Other) const inline
Definition at line 47 of file PrimaryAssetId.h.
References FPrimaryAssetType(), Name, and Other.
SerializeFromMismatchedTag()
bool FPrimaryAssetType::SerializeFromMismatchedTag (struct FPropertyTag const & Tag, FStructuredArchive::FSlot Slot)
ToString()
FString FPrimaryAssetType::ToString () const inline
Returns string version of this Type.
Definition at line 64 of file PrimaryAssetId.h.
References Name.
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FPrimaryAssetType & Key) friend
Definition at line 80 of file PrimaryAssetId.h.
References FPrimaryAssetType(), GetTypeHash, and Key.
Referenced by GetTypeHash.
Z_Construct_UScriptStruct_FPrimaryAssetType_Statics
friend struct Z_Construct_UScriptStruct_FPrimaryAssetType_Statics friend
Definition at line 96 of file PrimaryAssetId.h.
References Z_Construct_UScriptStruct_FPrimaryAssetType_Statics.
Referenced by Z_Construct_UScriptStruct_FPrimaryAssetType_Statics.
Field Documentation
Name
FName FPrimaryAssetType::Name private
The FName representing this type.
Definition at line 99 of file PrimaryAssetId.h.
Referenced by FPrimaryAssetType(), FPrimaryAssetType(), FPrimaryAssetType(), FPrimaryAssetType(), AppendString(), FastLess(), GetName(), IsValid(), LexicalLess(), operator const FName &(), operator FName &(), operator!=(), operator==(), and ToString().
The documentation for this struct was generated from the following file:
Runtime/CoreUObject/Public/UObject/PrimaryAssetId.h