Unreal Engine 5.6 C++ API: UE::MovieScene::TComponentTypeID< T > Struct Template Reference
UE::MovieScene::TComponentTypeID< T > Struct Template Reference
#include "MovieSceneEntityIDs.h"
Public Types
typedef T Type
Public Member Functions
TComponentTypeID ()
Public Member Functions inherited from UE::MovieScene::FComponentTypeID
FComponentTypeID ()
int32 BitIndex () const
operator bool () const
template<typename T>
TComponentTypeID< T > ReinterpretCast () const
Static Public Member Functions
static TComponentTypeID FromBitIndex (int32 BitIndex)
Static Public Member Functions inherited from UE::MovieScene::FComponentTypeID
static FComponentTypeID FromBitIndex (int32 BitIndex)
static FComponentTypeID Invalid ()
Private Member Functions
TComponentTypeID (uint16 InValue)
Additional Inherited Members
Protected Member Functions inherited from UE::MovieScene::FComponentTypeID
FComponentTypeID (uint16 InValue)
Protected Attributes inherited from UE::MovieScene::FComponentTypeID
uint16 Value
Static Protected Attributes inherited from UE::MovieScene::FComponentTypeID
static const uint16 INVALID = uint16(-1)
Detailed Description
template<typename T>
struct UE::MovieScene::TComponentTypeID< T >
Definition at line 282 of file MovieSceneEntityIDs.h.
Member Typedef Documentation
Type
template<typename T> typedef T UE::MovieScene::TComponentTypeID< T >::Type
Definition at line 284 of file MovieSceneEntityIDs.h.
Constructor & Destructor Documentation
TComponentTypeID() [1/2]
template<typename T> UE::MovieScene::TComponentTypeID< T >::TComponentTypeID () inline
Definition at line 286 of file MovieSceneEntityIDs.h.
Referenced by FromBitIndex().
TComponentTypeID() [2/2]
template<typename T> UE::MovieScene::TComponentTypeID< T >::TComponentTypeID (uint16 InValue) inline explicit private
Definition at line 296 of file MovieSceneEntityIDs.h.
References UE::MovieScene::FComponentTypeID::FComponentTypeID().
Member Function Documentation
FromBitIndex()
template<typename T> TComponentTypeID UE::MovieScene::TComponentTypeID< T >::FromBitIndex (int32 BitIndex) inline static
Definition at line 289 of file MovieSceneEntityIDs.h.
References TComponentTypeID(), UE::MovieScene::FComponentTypeID::BitIndex(), and check.
Referenced by UE::MovieScene::FComponentTypeID::ReinterpretCast().
The documentation for this struct was generated from the following file:
Runtime/MovieScene/Public/EntitySystem/MovieSceneEntityIDs.h