Unreal Engine 5.6 C++ API: UE::Cook::Dependency::Private::FCookDependencyFunctionRegistration Struct Reference
UE::Cook::Dependency::Private::FCookDependencyFunctionRegistration Struct Reference
Implementation struct of UE_COOK_DEPENDENCY_FUNCTION.
#include "CookDependency.h"
Public Member Functions
template<int N>
FCookDependencyFunctionRegistration (const TCHAR(&InName)[N], FCookDependencyFunction InFunction)
~FCookDependencyFunctionRegistration ()
void Construct ()
FName GetFName ()
Data Fields
FCookDependencyFunction Function
FLazyName Name
FCookDependencyFunctionRegistration * Next
Detailed Description
Implementation struct of UE_COOK_DEPENDENCY_FUNCTION.
Instances of this class are stored in global or namespace scope and add themselves to a list during c++ pre-main static initialization. This list is read later to create a map from FName to c++ function.
Definition at line 411 of file CookDependency.h.
Constructor & Destructor Documentation
FCookDependencyFunctionRegistration()
template<int N> UE::Cook::Dependency::Private::FCookDependencyFunctionRegistration::FCookDependencyFunctionRegistration (const TCHAR(&) InName[N], FCookDependencyFunction InFunction) inline
Definition at line 414 of file CookDependency.h.
References check, Construct(), Function, InName, Name, and Next.
~FCookDependencyFunctionRegistration()
UE::Cook::Dependency::Private::FCookDependencyFunctionRegistration::~FCookDependencyFunctionRegistration ()
Member Function Documentation
Construct()
void UE::Cook::Dependency::Private::FCookDependencyFunctionRegistration::Construct ()
Referenced by FCookDependencyFunctionRegistration().
GetFName()
FName UE::Cook::Dependency::Private::FCookDependencyFunctionRegistration::GetFName () inline
Definition at line 709 of file CookDependency.h.
References GetFName(), and Name.
Referenced by GetFName().
Field Documentation
Function
FCookDependencyFunction UE::Cook::Dependency::Private::FCookDependencyFunctionRegistration::Function
Definition at line 426 of file CookDependency.h.
Referenced by FCookDependencyFunctionRegistration().
Name
FLazyName UE::Cook::Dependency::Private::FCookDependencyFunctionRegistration::Name
Definition at line 425 of file CookDependency.h.
Referenced by FCookDependencyFunctionRegistration(), and GetFName().
Next
FCookDependencyFunctionRegistration* UE::Cook::Dependency::Private::FCookDependencyFunctionRegistration::Next
Definition at line 427 of file CookDependency.h.
Referenced by FCookDependencyFunctionRegistration().
The documentation for this struct was generated from the following file:
Runtime/CoreUObject/Public/Cooker/CookDependency.h