Unreal Engine 5.6 C++ API: FAnimationUpdateContext Struct Reference
FAnimationUpdateContext Struct Reference
Update context passed around during animation tree update.
#include "AnimNodeBase.h"
Public Member Functions
FAnimationUpdateContext (const FAnimationUpdateContext &Copy, FAnimInstanceProxy *InAnimInstanceProxy)
FAnimationUpdateContext (FAnimInstanceProxy *InAnimInstanceProxy, float InDeltaTime, FAnimationUpdateSharedContext *InSharedContext=nullptr)
FAnimationUpdateContext (FAnimInstanceProxy *InAnimInstanceProxy=nullptr)
FAnimationUpdateContext AsInactive () const
FAnimationUpdateContext FractionalWeight (float WeightMultiplier) const
FAnimationUpdateContext FractionalWeightAndRootMotion (float WeightMultiplier, float RootMotionMultiplier) const
FAnimationUpdateContext FractionalWeightAndTime (float WeightMultiplier, float TimeMultiplier) const
FAnimationUpdateContext FractionalWeightTimeAndRootMotion (float WeightMultiplier, float TimeMultiplier, float RootMotionMultiplier) const
float GetDeltaTime () const
float GetFinalBlendWeight () const
float GetRootMotionWeightModifier () const
FAnimationUpdateSharedContext * GetSharedContext () const
void LogMessage (const TSharedRef< FTokenizedMessage > &InMessage) const
void LogMessage (EMessageSeverity::Type InSeverity, FText InMessage) const
FAnimationUpdateContext WithNodeId (int32 InNodeId) const
FAnimationUpdateContext WithOtherProxy (FAnimInstanceProxy *InAnimInstanceProxy) const
FAnimationUpdateContext WithOtherSharedContext (FAnimationUpdateSharedContext *InSharedContext) const
Public Member Functions inherited from FAnimationBaseContext
FAnimationBaseContext ()
FAnimationBaseContext (const FAnimationBaseContext &)=default
PRAGMA_DISABLE_DEPRECATION_WARNINGS FAnimationBaseContext (FAnimationBaseContext &&)=default
template<typename TGraphMessageType>
TGraphMessageType * FindMessage (TFunctionRef< bool(TGraphMessageType &)> InFunction) const
IAnimClassInterface * GetAnimClass () const
UObject * GetAnimInstanceObject () const
int32 GetCurrentNodeId () const
template<typename TGraphMessageType>
TGraphMessageType * GetMessage () const
template<typename TGraphMessageType>
TGraphMessageType & GetMessageChecked () const
int32 GetPreviousNodeId () const
bool IsActive () const
FAnimationBaseContext & operator= (const FAnimationBaseContext &)=default
FAnimationBaseContext & operator= (FAnimationBaseContext &&)=default
void SetNodeId (int32 InNodeId)
void SetNodeIds (const FAnimationBaseContext &InContext)
template<typename NodeType>
UE_DEPRECATED (5.0, "Please use the message & tagging system in UE::Anim::FMessageStack") FScopedAnimNodeTracker TrackAncestor(NodeType *Node) const
template<typename NodeType>
UE_DEPRECATED (5.0, "Please use the message & tagging system in UE::Anim::FMessageStack") NodeType *GetAncestor() const
Private Attributes
float CurrentWeight
float DeltaTime
float RootMotionWeightModifier
Additional Inherited Members
Data Fields inherited from FAnimationBaseContext
FAnimInstanceProxy * AnimInstanceProxy
FAnimationUpdateSharedContext * SharedContext
Protected Member Functions inherited from FAnimationBaseContext
FAnimationBaseContext (FAnimInstanceProxy *InAnimInstanceProxy, FAnimationUpdateSharedContext *InSharedContext=nullptr)
FAnimationBaseContext (UAnimInstance *InAnimInstance)
void LogMessageInternal (FName InLogType, const TSharedRef< FTokenizedMessage > &InMessage) const
Interface for node contexts to register log messages with the proxy.
Protected Attributes inherited from FAnimationBaseContext
bool bIsActive = true
int32 CurrentNodeId
int32 PreviousNodeId
Detailed Description
Update context passed around during animation tree update.
Definition at line 353 of file AnimNodeBase.h.
Constructor & Destructor Documentation
FAnimationUpdateContext() [1/3]
FAnimationUpdateContext::FAnimationUpdateContext (FAnimInstanceProxy * InAnimInstanceProxy = nullptr) inline
Definition at line 362 of file AnimNodeBase.h.
References FAnimationBaseContext::FAnimationBaseContext(), CurrentWeight, DeltaTime, and RootMotionWeightModifier.
Referenced by FAnimationUpdateContext(), AsInactive(), FractionalWeight(), FractionalWeightAndRootMotion(), FractionalWeightAndTime(), FractionalWeightTimeAndRootMotion(), WithNodeId(), WithOtherProxy(), and WithOtherSharedContext().
FAnimationUpdateContext() [2/3]
FAnimationUpdateContext::FAnimationUpdateContext (FAnimInstanceProxy * InAnimInstanceProxy, float InDeltaTime, FAnimationUpdateSharedContext * InSharedContext = nullptr) inline
Definition at line 370 of file AnimNodeBase.h.
References FAnimationBaseContext::FAnimationBaseContext(), CurrentWeight, DeltaTime, and RootMotionWeightModifier.
FAnimationUpdateContext() [3/3]
FAnimationUpdateContext::FAnimationUpdateContext (const FAnimationUpdateContext & Copy, FAnimInstanceProxy * InAnimInstanceProxy) inline
Definition at line 379 of file AnimNodeBase.h.
References FAnimationBaseContext::FAnimationBaseContext(), FAnimationUpdateContext(), Copy, FAnimationBaseContext::CurrentNodeId, CurrentWeight, DeltaTime, FAnimationBaseContext::PreviousNodeId, RootMotionWeightModifier, and FAnimationBaseContext::SharedContext.
Member Function Documentation
AsInactive()
FAnimationUpdateContext FAnimationUpdateContext::AsInactive () const inline
Definition at line 406 of file AnimNodeBase.h.
References FAnimationUpdateContext().
FractionalWeight()
FAnimationUpdateContext FAnimationUpdateContext::FractionalWeight (float WeightMultiplier) const inline
Definition at line 414 of file AnimNodeBase.h.
References FAnimationUpdateContext(), and CurrentWeight.
FractionalWeightAndRootMotion()
FAnimationUpdateContext FAnimationUpdateContext::FractionalWeightAndRootMotion (float WeightMultiplier, float RootMotionMultiplier) const inline
Definition at line 422 of file AnimNodeBase.h.
References FAnimationUpdateContext(), CurrentWeight, and RootMotionWeightModifier.
FractionalWeightAndTime()
FAnimationUpdateContext FAnimationUpdateContext::FractionalWeightAndTime (float WeightMultiplier, float TimeMultiplier) const inline
Definition at line 431 of file AnimNodeBase.h.
References FAnimationUpdateContext(), CurrentWeight, and DeltaTime.
FractionalWeightTimeAndRootMotion()
FAnimationUpdateContext FAnimationUpdateContext::FractionalWeightTimeAndRootMotion (float WeightMultiplier, float TimeMultiplier, float RootMotionMultiplier) const inline
Definition at line 439 of file AnimNodeBase.h.
References FAnimationUpdateContext(), CurrentWeight, DeltaTime, and RootMotionWeightModifier.
GetDeltaTime()
float FAnimationUpdateContext::GetDeltaTime () const inline
Definition at line 469 of file AnimNodeBase.h.
References DeltaTime.
Referenced by FAnimNodeAlphaOptions::Update().
GetFinalBlendWeight()
float FAnimationUpdateContext::GetFinalBlendWeight () const inline
Definition at line 463 of file AnimNodeBase.h.
References CurrentWeight.
GetRootMotionWeightModifier()
float FAnimationUpdateContext::GetRootMotionWeightModifier () const inline
Definition at line 466 of file AnimNodeBase.h.
References RootMotionWeightModifier.
GetSharedContext()
FAnimationUpdateSharedContext * FAnimationUpdateContext::GetSharedContext () const inline
Definition at line 457 of file AnimNodeBase.h.
References FAnimationBaseContext::SharedContext.
LogMessage() [1/2]
void FAnimationUpdateContext::LogMessage (const TSharedRef< FTokenizedMessage > & InMessage) const inline
Definition at line 472 of file AnimNodeBase.h.
References FAnimationBaseContext::LogMessageInternal().
LogMessage() [2/2]
void FAnimationUpdateContext::LogMessage (EMessageSeverity::Type InSeverity, FText InMessage) const inline
Definition at line 473 of file AnimNodeBase.h.
References FTokenizedMessage::Create(), and LogMessage().
Referenced by LogMessage().
WithNodeId()
FAnimationUpdateContext FAnimationUpdateContext::WithNodeId (int32 InNodeId) const inline
Definition at line 449 of file AnimNodeBase.h.
References FAnimationUpdateContext().
WithOtherProxy()
FAnimationUpdateContext FAnimationUpdateContext::WithOtherProxy (FAnimInstanceProxy * InAnimInstanceProxy) const inline
Definition at line 390 of file AnimNodeBase.h.
References FAnimationUpdateContext().
WithOtherSharedContext()
FAnimationUpdateContext FAnimationUpdateContext::WithOtherSharedContext (FAnimationUpdateSharedContext * InSharedContext) const inline
Definition at line 395 of file AnimNodeBase.h.
References FAnimationUpdateContext().
Field Documentation
CurrentWeight
float FAnimationUpdateContext::CurrentWeight private
Definition at line 356 of file AnimNodeBase.h.
Referenced by FAnimationUpdateContext(), FAnimationUpdateContext(), FAnimationUpdateContext(), FractionalWeight(), FractionalWeightAndRootMotion(), FractionalWeightAndTime(), FractionalWeightTimeAndRootMotion(), and GetFinalBlendWeight().
DeltaTime
float FAnimationUpdateContext::DeltaTime private
Definition at line 359 of file AnimNodeBase.h.
Referenced by FAnimationUpdateContext(), FAnimationUpdateContext(), FAnimationUpdateContext(), FractionalWeightAndTime(), FractionalWeightTimeAndRootMotion(), and GetDeltaTime().
RootMotionWeightModifier
float FAnimationUpdateContext::RootMotionWeightModifier private
Definition at line 357 of file AnimNodeBase.h.
Referenced by FAnimationUpdateContext(), FAnimationUpdateContext(), FAnimationUpdateContext(), FractionalWeightAndRootMotion(), FractionalWeightTimeAndRootMotion(), and GetRootMotionWeightModifier().
The documentation for this struct was generated from the following file:
Runtime/Engine/Classes/Animation/AnimNodeBase.h