Unreal Engine 5.6 C++ API: FLevelInstanceID Struct Reference
FLevelInstanceID Struct Reference
#include "LevelInstanceTypes.h"
Public Member Functions
FLevelInstanceID ()
FLevelInstanceID (class ULevelInstanceSubsystem *LevelInstanceSubsystem, class ILevelInstanceInterface *LevelInstance)
const FActorContainerID & GetContainerID () const
uint64 GetHash () const
bool IsValid () const
bool operator!= (const FLevelInstanceID &Other) const
bool operator== (const FLevelInstanceID &Other) const
Private Attributes
FName ActorName
FActorContainerID ContainerID
uint64 Hash = 0
FString PackageShortName
Friends
uint32 GetTypeHash (const FLevelInstanceID &Key)
Detailed Description
Definition at line 13 of file LevelInstanceTypes.h.
Constructor & Destructor Documentation
FLevelInstanceID() [1/2]
FLevelInstanceID::FLevelInstanceID () inline
Definition at line 15 of file LevelInstanceTypes.h.
Referenced by GetTypeHash, operator!=(), and operator==().
FLevelInstanceID() [2/2]
FLevelInstanceID::FLevelInstanceID (class ULevelInstanceSubsystem * LevelInstanceSubsystem, class ILevelInstanceInterface * LevelInstance)
Member Function Documentation
GetContainerID()
const FActorContainerID & FLevelInstanceID::GetContainerID () const inline
Definition at line 37 of file LevelInstanceTypes.h.
References ContainerID.
GetHash()
uint64 FLevelInstanceID::GetHash () const inline
Definition at line 35 of file LevelInstanceTypes.h.
References Hash.
IsValid()
bool FLevelInstanceID::IsValid () const inline
Definition at line 33 of file LevelInstanceTypes.h.
References ContainerID.
operator!=()
bool FLevelInstanceID::operator!= (const FLevelInstanceID & Other) const inline
Definition at line 23 of file LevelInstanceTypes.h.
References FLevelInstanceID(), and Other.
operator==()
bool FLevelInstanceID::operator== (const FLevelInstanceID & Other) const inline
Definition at line 28 of file LevelInstanceTypes.h.
References FLevelInstanceID(), ActorName, ContainerID, Hash, Other, and PackageShortName.
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FLevelInstanceID & Key) friend
Definition at line 18 of file LevelInstanceTypes.h.
References FLevelInstanceID(), and Key.
Field Documentation
ActorName
FName FLevelInstanceID::ActorName private
Definition at line 47 of file LevelInstanceTypes.h.
Referenced by operator==().
ContainerID
FActorContainerID FLevelInstanceID::ContainerID private
Definition at line 41 of file LevelInstanceTypes.h.
Referenced by GetContainerID(), IsValid(), and operator==().
Hash
uint64 FLevelInstanceID::Hash = 0 private
Definition at line 40 of file LevelInstanceTypes.h.
Referenced by GetHash(), and operator==().
PackageShortName
FString FLevelInstanceID::PackageShortName private
Definition at line 52 of file LevelInstanceTypes.h.
Referenced by operator==().
The documentation for this struct was generated from the following file:
Runtime/Engine/Public/LevelInstance/LevelInstanceTypes.h