Unreal Engine 5.6 C++ API: UE::SequenceNavigator::FNavigationToolFilterData Struct Reference
UE::SequenceNavigator::FNavigationToolFilterData Struct Reference
Represents a cache between nodes for a filter operation.
#include "NavigationToolFilterData.h"
Public Member Functions
FNavigationToolFilterData (const FString &InRawFilterText)
bool ContainsFilterInNodes (const FNavigationToolFilterData &InOtherData) const
void FilterInNode (const FNavigationToolItemPtr &InNode)
void FilterInNodeWithAncestors (const FNavigationToolItemPtr &InNode)
void FilterInParentChildNodes (const FNavigationToolItemPtr &InNode, const bool bInIncludeSelf, const bool bInIncludeParents, const bool bInIncludeChildren=false)
void FilterOutNode (const FNavigationToolItemPtr &InNode)
uint32 GetDisplayNodeCount () const
uint32 GetFilterInCount () const
uint32 GetFilterOutCount () const
FString GetRawFilterText () const
uint32 GetTotalNodeCount () const
void IncrementTotalNodeCount ()
bool IsFilteredIn (const FNavigationToolItemPtr &InNode) const
bool IsFilteredOut (const FNavigationToolItemPtr &InNode) const
bool operator!= (const FNavigationToolFilterData &InRhs) const
bool operator== (const FNavigationToolFilterData &InRhs) const
void Reset ()
Protected Attributes
TSet< FNavigationToolItemWeakPtr > FilterInNodes
Nodes to be displayed in the UI.
FString RawFilterText
uint32 TotalNodeCount = 0
Detailed Description
Represents a cache between nodes for a filter operation.
Definition at line 14 of file NavigationToolFilterData.h.
Constructor & Destructor Documentation
FNavigationToolFilterData()
UE::SequenceNavigator::FNavigationToolFilterData::FNavigationToolFilterData (const FString & InRawFilterText)
Referenced by ContainsFilterInNodes(), operator!=(), and operator==().
Member Function Documentation
ContainsFilterInNodes()
bool UE::SequenceNavigator::FNavigationToolFilterData::ContainsFilterInNodes (const FNavigationToolFilterData & InOtherData) const
References FNavigationToolFilterData().
FilterInNode()
void UE::SequenceNavigator::FNavigationToolFilterData::FilterInNode (const FNavigationToolItemPtr & InNode)
FilterInNodeWithAncestors()
void UE::SequenceNavigator::FNavigationToolFilterData::FilterInNodeWithAncestors (const FNavigationToolItemPtr & InNode)
FilterInParentChildNodes()
void UE::SequenceNavigator::FNavigationToolFilterData::FilterInParentChildNodes (const FNavigationToolItemPtr & InNode, const bool bInIncludeSelf, const bool bInIncludeParents, const bool bInIncludeChildren = false)
FilterOutNode()
void UE::SequenceNavigator::FNavigationToolFilterData::FilterOutNode (const FNavigationToolItemPtr & InNode)
GetDisplayNodeCount()
uint32 UE::SequenceNavigator::FNavigationToolFilterData::GetDisplayNodeCount () const
GetFilterInCount()
uint32 UE::SequenceNavigator::FNavigationToolFilterData::GetFilterInCount () const
GetFilterOutCount()
uint32 UE::SequenceNavigator::FNavigationToolFilterData::GetFilterOutCount () const
GetRawFilterText()
FString UE::SequenceNavigator::FNavigationToolFilterData::GetRawFilterText () const
GetTotalNodeCount()
uint32 UE::SequenceNavigator::FNavigationToolFilterData::GetTotalNodeCount () const
IncrementTotalNodeCount()
void UE::SequenceNavigator::FNavigationToolFilterData::IncrementTotalNodeCount ()
IsFilteredIn()
bool UE::SequenceNavigator::FNavigationToolFilterData::IsFilteredIn (const FNavigationToolItemPtr & InNode) const
IsFilteredOut()
bool UE::SequenceNavigator::FNavigationToolFilterData::IsFilteredOut (const FNavigationToolItemPtr & InNode) const
operator!=()
bool UE::SequenceNavigator::FNavigationToolFilterData::operator!= (const FNavigationToolFilterData & InRhs) const
References FNavigationToolFilterData().
operator==()
bool UE::SequenceNavigator::FNavigationToolFilterData::operator== (const FNavigationToolFilterData & InRhs) const
References FNavigationToolFilterData().
Reset()
void UE::SequenceNavigator::FNavigationToolFilterData::Reset ()
Field Documentation
FilterInNodes
TSet<FNavigationToolItemWeakPtr> UE::SequenceNavigator::FNavigationToolFilterData::FilterInNodes protected
Nodes to be displayed in the UI.
Definition at line 52 of file NavigationToolFilterData.h.
RawFilterText
FString UE::SequenceNavigator::FNavigationToolFilterData::RawFilterText protected
Definition at line 47 of file NavigationToolFilterData.h.
TotalNodeCount
uint32 UE::SequenceNavigator::FNavigationToolFilterData::TotalNodeCount = 0 protected
Definition at line 49 of file NavigationToolFilterData.h.
The documentation for this struct was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Experimental/SequenceNavigator/Source/SequenceNavigator/Public/Filters/NavigationToolFilterData.h