Unreal Engine 5.6 C++ API: FInGameCycleHistory Struct Reference
FInGameCycleHistory Struct Reference
#include "InGamePerformanceTracker.h"
Public Member Functions
FInGameCycleHistory ()
FInGameCycleHistory (int32 InNumSamples)
FORCEINLINE void AddCycles (uint64 NewCycles)
Adds a number of cycles for the current frame.
FORCEINLINE uint64 GetAverageCycles () const
void NextFrame ()
Places the current data on the history and advances to the next frame index.
void Reset ()
Data Fields
TAtomic< uint64 > CachedAverageCycles
Current average cycles for access by others, possibly on other threads.
TAtomic< uint64 > CurrFrameCycles
Current number of cycles for this frame.
TArray< uint64 > FrameCycles
int32 FrameIdx = 0
uint64 TotalCycles = 0
Detailed Description
Definition at line 8 of file InGamePerformanceTracker.h.
Constructor & Destructor Documentation
FInGameCycleHistory() [1/2]
FInGameCycleHistory::FInGameCycleHistory () inline
Definition at line 10 of file InGamePerformanceTracker.h.
References Reset().
FInGameCycleHistory() [2/2]
FInGameCycleHistory::FInGameCycleHistory (int32 InNumSamples) inline
Definition at line 15 of file InGamePerformanceTracker.h.
References FrameCycles, and Reset().
Member Function Documentation
AddCycles()
FORCEINLINE void FInGameCycleHistory::AddCycles (uint64 NewCycles) inline
Adds a number of cycles for the current frame.
Thread safe.
Definition at line 46 of file InGamePerformanceTracker.h.
References CurrFrameCycles, and FORCEINLINE.
GetAverageCycles()
FORCEINLINE uint64 FInGameCycleHistory::GetAverageCycles () const inline
Definition at line 51 of file InGamePerformanceTracker.h.
References CachedAverageCycles, and FORCEINLINE.
NextFrame()
void FInGameCycleHistory::NextFrame ()
Places the current data on the history and advances to the next frame index.
Not thread safe.
Reset()
void FInGameCycleHistory::Reset () inline
Definition at line 21 of file InGamePerformanceTracker.h.
References CachedAverageCycles, CurrFrameCycles, FrameCycles, FrameIdx, and TotalCycles.
Referenced by FInGameCycleHistory(), and FInGameCycleHistory().
Field Documentation
CachedAverageCycles
TAtomic<uint64> FInGameCycleHistory::CachedAverageCycles
Current average cycles for access by others, possibly on other threads.
Definition at line 40 of file InGamePerformanceTracker.h.
Referenced by GetAverageCycles(), and Reset().
CurrFrameCycles
TAtomic<uint64> FInGameCycleHistory::CurrFrameCycles
Current number of cycles for this frame.
Definition at line 33 of file InGamePerformanceTracker.h.
Referenced by AddCycles(), and Reset().
FrameCycles
TArray<uint64> FInGameCycleHistory::FrameCycles
Definition at line 35 of file InGamePerformanceTracker.h.
Referenced by FInGameCycleHistory(), and Reset().
FrameIdx
int32 FInGameCycleHistory::FrameIdx = 0
Definition at line 43 of file InGamePerformanceTracker.h.
Referenced by Reset().
TotalCycles
uint64 FInGameCycleHistory::TotalCycles = 0
Definition at line 38 of file InGamePerformanceTracker.h.
Referenced by Reset().
The documentation for this struct was generated from the following file:
Runtime/Engine/Public/InGamePerformanceTracker.h