Unreal Engine 5.6 C++ API: FCoreUObjectDelegates Struct Reference
FCoreUObjectDelegates Struct Reference
Global CoreUObject delegates.
#include "UObjectGlobals.h"
Public Types
using FReplacementObjectMap = TMap<UObject*, UObject*>
Called when UObjects have been replaced to allow others a chance to fix their references Note that this is called after properties are copied from old to new instances but before references to replacement objects are fixed up in other objects (i.e.
Public Member Functions
DECLARE_DELEGATE_OneParam (FNetworkFileRequestPackageReload, const TArray< FString > &)
Called when a package reload request is received from a network file server.
DECLARE_DELEGATE_RetVal_OneParam (bool, FAutoPackageBackupDelegate, const UPackage &)
Delegate used by SavePackage() to create the package backup.
DECLARE_DELEGATE_RetVal_OneParam (bool, FOnLoadObjectsOnTop, const FString &)
Queries whether an object should be loaded on top (replace) an already existing one.
DECLARE_DELEGATE_RetVal_OneParam (FPrimaryAssetId, FGetPrimaryAssetIdForObject, const UObject *)
Called when trying to figure out if a UObject is a primary asset, if it doesn't implement GetPrimaryAssetId itself.
DECLARE_DELEGATE_RetVal_ThreeParams (bool, FIsPackageOKToSaveDelegate, UPackage *, const FString &, FOutputDevice *)
Delegate used by SavePackage() to check whether a package should be saved.
DECLARE_DELEGATE_RetVal_TwoParams (bool, FShouldCookPackageForPlatform, const UPackage *, const ITargetPlatform *)
Called during cooking to see if a specific package should be cooked for a given target platform.
DECLARE_MULTICAST_DELEGATE (FReinstanceHotReloadedClassesDelegate)
Delegate for reinstancing hot-reloaded classes.
DECLARE_MULTICAST_DELEGATE (FReloadReinstancingCompleteDelegate)
Delegate for reload re-instancing complete.
DECLARE_MULTICAST_DELEGATE_OneParam (FOnAssetLoaded, UObject *)
Callback for when an asset is loaded.
DECLARE_MULTICAST_DELEGATE_OneParam (FOnEndLoadPackage, const FEndLoadPackageContext &)
Callback when packages end loading in LoadPackage or AsyncLoadPackage.
DECLARE_MULTICAST_DELEGATE_OneParam (FOnObjectModified, UObject *)
Called when an object is registered for change with UObject::Modify.
DECLARE_MULTICAST_DELEGATE_OneParam (FOnObjectSaved, UObject *)
DECLARE_MULTICAST_DELEGATE_OneParam (FOnObjectsReinstanced, const FReplacementObjectMap &)
Called when UObjects have been re-instanced to allow others a chance to fix their references Note that this is called after references to replacement objects are fixed up in other objects (i.e.
DECLARE_MULTICAST_DELEGATE_OneParam (FOnObjectsReplaced, const FReplacementObjectMap &)
DECLARE_MULTICAST_DELEGATE_OneParam (FOnReportGarbageReferencers, TConstArrayView< struct FGarbageReferenceInfo >)
Called when garbage collection detects references to objects that are marked for explicit destruction by MarkAsGarbage.
DECLARE_MULTICAST_DELEGATE_OneParam (FPackageCreatedForLoad, class UPackage *)
Called when path to world root is changed.
DECLARE_MULTICAST_DELEGATE_OneParam (FPostLoadMapDelegate, UWorld *)
Sent at the end of LoadMap.
DECLARE_MULTICAST_DELEGATE_OneParam (FPreLoadMapDelegate, const FString &)
Sent at the very beginning of LoadMap.
DECLARE_MULTICAST_DELEGATE_OneParam (FRegisterHotReloadAddedClassesDelegate, const TArray< UClass * > &)
Delegate for registering hot-reloaded classes that have been added.
DECLARE_MULTICAST_DELEGATE_OneParam (FReloadAddedClassesDelegate, const TArray< UClass * > &)
Delegate for reloaded classes that have been added.
DECLARE_MULTICAST_DELEGATE_OneParam (FReloadCompleteDelegate, EReloadCompleteReason)
Delegate for reload re-instancing complete.
DECLARE_MULTICAST_DELEGATE_ThreeParams (FOnObjectRenamed, UObject *, UObject *, FName)
Called when an object is renamed this gets called in both the editor and standalone game editor builds, for every object renamed.
DECLARE_MULTICAST_DELEGATE_ThreeParams (FOnPostInitSparseClassData, UClass *, UScriptStruct *, void *)
Called when new sparse class data has been created (and the base data initialized) for the given class.
DECLARE_MULTICAST_DELEGATE_ThreeParams (FOnVerseDeadReferences, const TSet< UClass * > &, const TSet< UObject * > &, const TSet< UObject * > &)
Called when verse found instances of object that their classes is now dead (renamed or deleted)
DECLARE_MULTICAST_DELEGATE_ThreeParams (FRegisterClassForHotReloadReinstancingDelegate, UClass *, UClass *, EHotReloadedClassFlags)
Delegate for registering hot-reloaded classes that changed after hot-reload for reinstancing.
DECLARE_MULTICAST_DELEGATE_ThreeParams (FTraceExternalRootsForReachabilityAnalysisDelegate, FGarbageCollectionTracer &, EObjectFlags, bool)
Delegate type for reachability analysis external roots callback.
DECLARE_MULTICAST_DELEGATE_TwoParams (FCompiledInUObjectsRegisteredDelegate, FName, ECompiledInUObjectsRegisteredStatus Status)
Delegate invoked when requests are made to process pending UObject registrations.
DECLARE_MULTICAST_DELEGATE_TwoParams (FOnObjectPostCDOCompiled, UObject *, const FObjectPostCDOCompiledContext &)
Called after the Blueprint compiler has finished generating the Class Default Object (CDO) for a class.
DECLARE_MULTICAST_DELEGATE_TwoParams (FOnObjectPreSave, UObject *, FObjectPreSaveContext)
Callback for when an asset is saved.
DECLARE_MULTICAST_DELEGATE_TwoParams (FOnObjectPropertyChanged, UObject *, struct FPropertyChangedEvent &)
Callback for object property modifications, called by UObject::PostEditChangeProperty with a single property event.
DECLARE_MULTICAST_DELEGATE_TwoParams (FOnObjectTransacted, UObject *, const class FTransactionObjectEvent &)
Callback for an object being transacted.
DECLARE_MULTICAST_DELEGATE_TwoParams (FOnPackageReloaded, EPackageReloadPhase, FPackageReloadedEvent *)
Called by ReloadPackage during package reloading.
DECLARE_MULTICAST_DELEGATE_TwoParams (FOnPreObjectPropertyChanged, UObject *, const class FEditPropertyChain &)
Callback for object property modifications, called by UObject::PreEditChange with a full property chain.
DECLARE_MULTICAST_DELEGATE_TwoParams (FPreLoadMapWithContextDelegate, const FWorldContext &, const FString &)
Sent at the very beginning of LoadMap.
DECLARE_TS_MULTICAST_DELEGATE_OneParam (FOnObjectConstructed, UObject *)
UE_DEPRECATED (5.0, "RegisterClassForHotReloadReinstancingDelegate has been deprecated, use FReload for class re-instancing.") static 1 FRegisterClassForHotReloadReinstancingDelegate RegisterClassForHotReloadReinstancingDelegate
UE_DEPRECATED (5.0, "RegisterHotReloadAddedClassesDelegate has been deprecated, use ReloadAddedClassesDelegate.") static 1 FRegisterHotReloadAddedClassesDelegate RegisterHotReloadAddedClassesDelegate
UE_DEPRECATED (5.0, "ReinstanceHotReloadedClassesDelegate has been deprecated, use FReload for class re-instancing or ReloadReinstancingCompleteDelegate for notification") static 1 FReinstanceHotReloadedClassesDelegate ReinstanceHotReloadedClassesDelegate
UE_DEPRECATED (5.0, "Use OnObjectPreSave instead.") static 1 FOnObjectSaved OnObjectSaved
UE_DEPRECATED (5.1, "Backups are no longer used in Unreal Package Saves") static 1 FAutoPackageBackupDelegate AutoPackageBackupDelegate
UE_DEPRECATED (5.2, "Ability to inject extra root objects will be removed to reduce GC complexity") static 1 FTraceExternalRootsForReachabilityAnalysisDelegate TraceExternalRootsForReachabilityAnalysis
Called as last phase of reachability analysis.
Static Public Member Functions
static void BroadcastOnObjectModified (UObject *Object)
Broadcast OnObjectModified if the broadcast hasn't occurred for this object in this frame.
static void BroadcastOnObjectRenamed (UObject *Object, UObject *OldOuter, FName OldName)
Broadcast OnObjectRenamed event.
static FOnReportGarbageReferencers & GetGarbageCollectReportGarbageReferencers ()
static FSimpleMulticastDelegate & GetGarbageCollectStartedDelegate ()
Called at the very beginning of garbage collection, once the GC lock is held.
static FSimpleMulticastDelegate & GetPostGarbageCollect ()
Called after garbage collection (before purge phase if incremental purge is enabled and after purge phase if incremental purge is disabled)
static FSimpleMulticastDelegate & GetPostPurgeGarbageDelegate ()
Called after purging unreachable objects during garbage collection.
static FSimpleMulticastDelegate & GetPreGarbageCollectDelegate ()
Called before garbage collection, before the GC lock is acquired.
Static Public Attributes
static FCompiledInUObjectsRegisteredDelegate CompiledInUObjectsRegisteredDelegate
static FSimpleMulticastDelegate GarbageCollectComplete
Called after garbage collection is complete, all objects have been purged (regardless of whether incremental purge is enabled or not), memory has been trimmed and all other GC callbacks have been fired.
static FGetPrimaryAssetIdForObject GetPrimaryAssetIdForObject
static FIsPackageOKToSaveDelegate IsPackageOKToSaveDelegate
static FNetworkFileRequestPackageReload NetworkFileRequestPackageReload
static TSet< UObject * > ObjectsModifiedThisFrame
Set of objects modified this frame, to prevent multiple triggerings of the OnObjectModified delegate.
static FOnAssetLoaded OnAssetLoaded
static FOnEndLoadPackage OnEndLoadPackage
static FOnObjectConstructed OnObjectConstructed
static FOnObjectModified OnObjectModified
static FOnObjectPostCDOCompiled OnObjectPostCDOCompiled
static FOnObjectPreSave OnObjectPreSave
static FOnObjectPropertyChanged OnObjectPropertyChanged
static FOnObjectRenamed OnObjectRenamed
static FOnObjectsReinstanced OnObjectsReinstanced
static FOnObjectsReplaced OnObjectsReplaced
static FOnObjectTransacted OnObjectTransacted
static FOnPackageReloaded OnPackageReloaded
static FOnPostInitSparseClassData OnPostInitSparseClassData
static FOnPreObjectPropertyChanged OnPreObjectPropertyChanged
static FOnVerseDeadReferences OnVerseDeadObjectReferences
static FPackageCreatedForLoad PackageCreatedForLoad
static FSimpleMulticastDelegate PostDemoPlay
Sent when a network replay has started.
static FSimpleMulticastDelegate PostGarbageCollectConditionalBeginDestroy
Called after ConditionalBeginDestroy phase of garbage collection.
static FPostLoadMapDelegate PostLoadMapWithWorld
static FSimpleMulticastDelegate PostReachabilityAnalysis
Called after reachability analysis, before any purging.
static FSimpleMulticastDelegate PreGarbageCollectConditionalBeginDestroy
Called before ConditionalBeginDestroy phase of garbage collection.
static FPreLoadMapDelegate PreLoadMap
static FPreLoadMapWithContextDelegate PreLoadMapWithContext
static FReloadAddedClassesDelegate ReloadAddedClassesDelegate
static FReloadCompleteDelegate ReloadCompleteDelegate
static FReloadReinstancingCompleteDelegate ReloadReinstancingCompleteDelegate
static FShouldCookPackageForPlatform ShouldCookPackageForPlatform
static FOnLoadObjectsOnTop ShouldLoadOnTop
Detailed Description
Global CoreUObject delegates.
Definition at line 3176 of file UObjectGlobals.h.
Member Typedef Documentation
FReplacementObjectMap
using FCoreUObjectDelegates::FReplacementObjectMap = TMap<UObject*, UObject*>
Called when UObjects have been replaced to allow others a chance to fix their references Note that this is called after properties are copied from old to new instances but before references to replacement objects are fixed up in other objects (i.e.
other objects can still be pointing to old data)
Definition at line 3223 of file UObjectGlobals.h.
Member Function Documentation
BroadcastOnObjectModified()
void FCoreUObjectDelegates::BroadcastOnObjectModified (UObject * Object) inline static
Broadcast OnObjectModified if the broadcast hasn't occurred for this object in this frame.
Definition at line 3195 of file UObjectGlobals.h.
References Object, ObjectsModifiedThisFrame, and OnObjectModified.
BroadcastOnObjectRenamed()
void FCoreUObjectDelegates::BroadcastOnObjectRenamed (UObject * Object, UObject * OldOuter, FName OldName) inline static
Broadcast OnObjectRenamed event.
Definition at line 3209 of file UObjectGlobals.h.
References Object, and OnObjectRenamed.
DECLARE_DELEGATE_OneParam()
FCoreUObjectDelegates::DECLARE_DELEGATE_OneParam (FNetworkFileRequestPackageReload , const TArray< FString > &)
Called when a package reload request is received from a network file server.
DECLARE_DELEGATE_RetVal_OneParam() [1/3]
FCoreUObjectDelegates::DECLARE_DELEGATE_RetVal_OneParam (bool , FAutoPackageBackupDelegate , const UPackage &)
Delegate used by SavePackage() to create the package backup.
References DECLARE_DELEGATE_RetVal_OneParam().
Referenced by DECLARE_DELEGATE_RetVal_OneParam().
DECLARE_DELEGATE_RetVal_OneParam() [2/3]
FCoreUObjectDelegates::DECLARE_DELEGATE_RetVal_OneParam (bool , FOnLoadObjectsOnTop , const FString &)
Queries whether an object should be loaded on top (replace) an already existing one.
DECLARE_DELEGATE_RetVal_OneParam() [3/3]
FCoreUObjectDelegates::DECLARE_DELEGATE_RetVal_OneParam (FPrimaryAssetId , FGetPrimaryAssetIdForObject , const UObject *)
Called when trying to figure out if a UObject is a primary asset, if it doesn't implement GetPrimaryAssetId itself.
DECLARE_DELEGATE_RetVal_ThreeParams()
FCoreUObjectDelegates::DECLARE_DELEGATE_RetVal_ThreeParams (bool , FIsPackageOKToSaveDelegate , UPackage * , const FString & , FOutputDevice *)
Delegate used by SavePackage() to check whether a package should be saved.
DECLARE_DELEGATE_RetVal_TwoParams()
FCoreUObjectDelegates::DECLARE_DELEGATE_RetVal_TwoParams (bool , FShouldCookPackageForPlatform , const UPackage * , const ITargetPlatform *)
Called during cooking to see if a specific package should be cooked for a given target platform.
DECLARE_MULTICAST_DELEGATE() [1/2]
FCoreUObjectDelegates::DECLARE_MULTICAST_DELEGATE (FReinstanceHotReloadedClassesDelegate)
Delegate for reinstancing hot-reloaded classes.
References DECLARE_MULTICAST_DELEGATE().
DECLARE_MULTICAST_DELEGATE() [2/2]
FCoreUObjectDelegates::DECLARE_MULTICAST_DELEGATE (FReloadReinstancingCompleteDelegate)
Delegate for reload re-instancing complete.
Referenced by DECLARE_MULTICAST_DELEGATE().
DECLARE_MULTICAST_DELEGATE_OneParam() [1/13]
FCoreUObjectDelegates::DECLARE_MULTICAST_DELEGATE_OneParam (FOnAssetLoaded , UObject *)
Callback for when an asset is loaded.
This gets called in both the editor and standalone game editor builds, but only for objects that return true for IsAsset()
References DECLARE_MULTICAST_DELEGATE_OneParam().
DECLARE_MULTICAST_DELEGATE_OneParam() [2/13]
FCoreUObjectDelegates::DECLARE_MULTICAST_DELEGATE_OneParam (FOnEndLoadPackage , const FEndLoadPackageContext &)
Callback when packages end loading in LoadPackage or AsyncLoadPackage.
All packages loaded recursively due to imports are included in the single call of the explicitly-loaded package. It is called in all WITH_EDITOR cases, including -game. But it is not called in the runtime game compiled without WITH_EDITOR. This difference in behavior between the two game configurations is necessary because WITH_EDITOR uses a different loading mechanism than runtime game.
References DECLARE_MULTICAST_DELEGATE_OneParam().
DECLARE_MULTICAST_DELEGATE_OneParam() [3/13]
FCoreUObjectDelegates::DECLARE_MULTICAST_DELEGATE_OneParam (FOnObjectModified , UObject *)
Called when an object is registered for change with UObject::Modify.
This gets called in both the editor and standalone game editor builds, for every object modified
Referenced by DECLARE_MULTICAST_DELEGATE_OneParam(), DECLARE_MULTICAST_DELEGATE_OneParam(), DECLARE_MULTICAST_DELEGATE_OneParam(), and DECLARE_MULTICAST_DELEGATE_OneParam().
DECLARE_MULTICAST_DELEGATE_OneParam() [4/13]
FCoreUObjectDelegates::DECLARE_MULTICAST_DELEGATE_OneParam (FOnObjectSaved , UObject *)
DECLARE_MULTICAST_DELEGATE_OneParam() [5/13]
FCoreUObjectDelegates::DECLARE_MULTICAST_DELEGATE_OneParam (FOnObjectsReinstanced , const FReplacementObjectMap &)
Called when UObjects have been re-instanced to allow others a chance to fix their references Note that this is called after references to replacement objects are fixed up in other objects (i.e.
all object references should be self-consistent).
DECLARE_MULTICAST_DELEGATE_OneParam() [6/13]
FCoreUObjectDelegates::DECLARE_MULTICAST_DELEGATE_OneParam (FOnObjectsReplaced , const FReplacementObjectMap &)
DECLARE_MULTICAST_DELEGATE_OneParam() [7/13]
FCoreUObjectDelegates::DECLARE_MULTICAST_DELEGATE_OneParam (FOnReportGarbageReferencers , TConstArrayView< struct FGarbageReferenceInfo >)
Called when garbage collection detects references to objects that are marked for explicit destruction by MarkAsGarbage.
DECLARE_MULTICAST_DELEGATE_OneParam() [8/13]
FCoreUObjectDelegates::DECLARE_MULTICAST_DELEGATE_OneParam (FPackageCreatedForLoad , class UPackage *)
Called when path to world root is changed.
DECLARE_MULTICAST_DELEGATE_OneParam() [9/13]
FCoreUObjectDelegates::DECLARE_MULTICAST_DELEGATE_OneParam (FPostLoadMapDelegate , UWorld *)
Sent at the end of LoadMap.
References DECLARE_MULTICAST_DELEGATE_OneParam().
DECLARE_MULTICAST_DELEGATE_OneParam() [10/13]
FCoreUObjectDelegates::DECLARE_MULTICAST_DELEGATE_OneParam (FPreLoadMapDelegate , const FString &)
Sent at the very beginning of LoadMap.
References DECLARE_MULTICAST_DELEGATE_OneParam().
DECLARE_MULTICAST_DELEGATE_OneParam() [11/13]
FCoreUObjectDelegates::DECLARE_MULTICAST_DELEGATE_OneParam (FRegisterHotReloadAddedClassesDelegate , const TArray< UClass * > &)
Delegate for registering hot-reloaded classes that have been added.
DECLARE_MULTICAST_DELEGATE_OneParam() [12/13]
FCoreUObjectDelegates::DECLARE_MULTICAST_DELEGATE_OneParam (FReloadAddedClassesDelegate , const TArray< UClass * > &)
Delegate for reloaded classes that have been added.
DECLARE_MULTICAST_DELEGATE_OneParam() [13/13]
FCoreUObjectDelegates::DECLARE_MULTICAST_DELEGATE_OneParam (FReloadCompleteDelegate , EReloadCompleteReason)
Delegate for reload re-instancing complete.
DECLARE_MULTICAST_DELEGATE_ThreeParams() [1/5]
FCoreUObjectDelegates::DECLARE_MULTICAST_DELEGATE_ThreeParams (FOnObjectRenamed , UObject * , UObject * , FName)
Called when an object is renamed this gets called in both the editor and standalone game editor builds, for every object renamed.
Referenced by DECLARE_MULTICAST_DELEGATE_ThreeParams(), and DECLARE_MULTICAST_DELEGATE_ThreeParams().
DECLARE_MULTICAST_DELEGATE_ThreeParams() [2/5]
FCoreUObjectDelegates::DECLARE_MULTICAST_DELEGATE_ThreeParams (FOnPostInitSparseClassData , UClass * , UScriptStruct * , void *)
Called when new sparse class data has been created (and the base data initialized) for the given class.
DECLARE_MULTICAST_DELEGATE_ThreeParams() [3/5]
FCoreUObjectDelegates::DECLARE_MULTICAST_DELEGATE_ThreeParams (FOnVerseDeadReferences , const TSet< UClass * > & , const TSet< UObject * > & , const TSet< UObject * > &)
Called when verse found instances of object that their classes is now dead (renamed or deleted)
DECLARE_MULTICAST_DELEGATE_ThreeParams() [4/5]
FCoreUObjectDelegates::DECLARE_MULTICAST_DELEGATE_ThreeParams (FRegisterClassForHotReloadReinstancingDelegate , UClass * , UClass * , EHotReloadedClassFlags)
Delegate for registering hot-reloaded classes that changed after hot-reload for reinstancing.
References DECLARE_MULTICAST_DELEGATE_ThreeParams().
DECLARE_MULTICAST_DELEGATE_ThreeParams() [5/5]
FCoreUObjectDelegates::DECLARE_MULTICAST_DELEGATE_ThreeParams (FTraceExternalRootsForReachabilityAnalysisDelegate , FGarbageCollectionTracer & , EObjectFlags , bool)
Delegate type for reachability analysis external roots callback.
First parameter is FGarbageCollectionTracer to use for tracing, second is flags with which objects should be kept alive regardless, third is whether to force single threading
References DECLARE_MULTICAST_DELEGATE_ThreeParams().
DECLARE_MULTICAST_DELEGATE_TwoParams() [1/8]
FCoreUObjectDelegates::DECLARE_MULTICAST_DELEGATE_TwoParams (FCompiledInUObjectsRegisteredDelegate , FName , ECompiledInUObjectsRegisteredStatus Status)
Delegate invoked when requests are made to process pending UObject registrations.
This will be invoked during the loading of modules and outside of module load to register any delayed registrations. This callback will be invoked regardless of if the module contained any UObject definitions. The callback will also be invoked during module load in monolithic builds.
See ECompiledInUObjectsRegisteredStatus for more detailed information about the notifications.
References DECLARE_MULTICAST_DELEGATE_TwoParams().
DECLARE_MULTICAST_DELEGATE_TwoParams() [2/8]
FCoreUObjectDelegates::DECLARE_MULTICAST_DELEGATE_TwoParams (FOnObjectPostCDOCompiled , UObject * , const FObjectPostCDOCompiledContext &)
Called after the Blueprint compiler has finished generating the Class Default Object (CDO) for a class.
This can only happen in the editor. This is called when the CDO and its associated class structure have been fully generated and populated, and allows the assignment of cached/derived data, eg) caching the name/count of properties of a certain type, or inspecting the properties on the class and using their meta-data and CDO default values to derive game data.
DECLARE_MULTICAST_DELEGATE_TwoParams() [3/8]
FCoreUObjectDelegates::DECLARE_MULTICAST_DELEGATE_TwoParams (FOnObjectPreSave , UObject * , FObjectPreSaveContext)
Callback for when an asset is saved.
This is called from UObject::PreSave before it is actually written to disk, for every object saved
References DECLARE_MULTICAST_DELEGATE_TwoParams().
DECLARE_MULTICAST_DELEGATE_TwoParams() [4/8]
FCoreUObjectDelegates::DECLARE_MULTICAST_DELEGATE_TwoParams (FOnObjectPropertyChanged , UObject * , struct FPropertyChangedEvent &)
Callback for object property modifications, called by UObject::PostEditChangeProperty with a single property event.
Referenced by DECLARE_MULTICAST_DELEGATE_TwoParams(), DECLARE_MULTICAST_DELEGATE_TwoParams(), and DECLARE_MULTICAST_DELEGATE_TwoParams().
DECLARE_MULTICAST_DELEGATE_TwoParams() [5/8]
FCoreUObjectDelegates::DECLARE_MULTICAST_DELEGATE_TwoParams (FOnObjectTransacted , UObject * , const class FTransactionObjectEvent &)
Callback for an object being transacted.
DECLARE_MULTICAST_DELEGATE_TwoParams() [6/8]
FCoreUObjectDelegates::DECLARE_MULTICAST_DELEGATE_TwoParams (FOnPackageReloaded , EPackageReloadPhase , FPackageReloadedEvent *)
Called by ReloadPackage during package reloading.
It will be called several times for different phases of fix-up to allow custom code to handle updating objects as needed
DECLARE_MULTICAST_DELEGATE_TwoParams() [7/8]
FCoreUObjectDelegates::DECLARE_MULTICAST_DELEGATE_TwoParams (FOnPreObjectPropertyChanged , UObject * , const class FEditPropertyChain &)
Callback for object property modifications, called by UObject::PreEditChange with a full property chain.
DECLARE_MULTICAST_DELEGATE_TwoParams() [8/8]
FCoreUObjectDelegates::DECLARE_MULTICAST_DELEGATE_TwoParams (FPreLoadMapWithContextDelegate , const FWorldContext & , const FString &)
Sent at the very beginning of LoadMap.
References DECLARE_MULTICAST_DELEGATE_TwoParams().
DECLARE_TS_MULTICAST_DELEGATE_OneParam()
FCoreUObjectDelegates::DECLARE_TS_MULTICAST_DELEGATE_OneParam (FOnObjectConstructed , UObject *)
References DECLARE_TS_MULTICAST_DELEGATE_OneParam().
Referenced by DECLARE_TS_MULTICAST_DELEGATE_OneParam().
GetGarbageCollectReportGarbageReferencers()
FOnReportGarbageReferencers & FCoreUObjectDelegates::GetGarbageCollectReportGarbageReferencers () static
GetGarbageCollectStartedDelegate()
FSimpleMulticastDelegate & FCoreUObjectDelegates::GetGarbageCollectStartedDelegate () static
Called at the very beginning of garbage collection, once the GC lock is held.
References GetGarbageCollectStartedDelegate().
Referenced by GetGarbageCollectStartedDelegate().
GetPostGarbageCollect()
FSimpleMulticastDelegate & FCoreUObjectDelegates::GetPostGarbageCollect () static
Called after garbage collection (before purge phase if incremental purge is enabled and after purge phase if incremental purge is disabled)
References GetPostGarbageCollect().
Referenced by GetPostGarbageCollect().
GetPostPurgeGarbageDelegate()
FSimpleMulticastDelegate & FCoreUObjectDelegates::GetPostPurgeGarbageDelegate () static
Called after purging unreachable objects during garbage collection.
References GetPostPurgeGarbageDelegate().
Referenced by GetPostPurgeGarbageDelegate().
GetPreGarbageCollectDelegate()
FSimpleMulticastDelegate & FCoreUObjectDelegates::GetPreGarbageCollectDelegate () static
Called before garbage collection, before the GC lock is acquired.
References GetPreGarbageCollectDelegate().
Referenced by GetPreGarbageCollectDelegate().
UE_DEPRECATED() [1/6]
FCoreUObjectDelegates::UE_DEPRECATED (5. 0, "RegisterClassForHotReloadReinstancingDelegate has been deprecated, use FReload for class re-instancing.")
References UE_DEPRECATED().
UE_DEPRECATED() [2/6]
FCoreUObjectDelegates::UE_DEPRECATED (5. 0, "RegisterHotReloadAddedClassesDelegate has been deprecated, use ReloadAddedClassesDelegate.")
UE_DEPRECATED() [3/6]
FCoreUObjectDelegates::UE_DEPRECATED (5. 0, "ReinstanceHotReloadedClassesDelegate has been deprecated, use FReload for class re-instancing or ReloadReinstancingCompleteDelegate for notification")
References UE_DEPRECATED().
UE_DEPRECATED() [4/6]
FCoreUObjectDelegates::UE_DEPRECATED (5. 0, "Use OnObjectPreSave instead.")
Referenced by UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
UE_DEPRECATED() [5/6]
FCoreUObjectDelegates::UE_DEPRECATED (5. 1, "Backups are no longer used in Unreal Package Saves")
References UE_DEPRECATED().
UE_DEPRECATED() [6/6]
FCoreUObjectDelegates::UE_DEPRECATED (5. 2, "Ability to inject extra root objects will be removed to reduce GC complexity")
Called as last phase of reachability analysis.
Allow external systems to add UObject roots after first reachability pass has been done
References UE_DEPRECATED().
Field Documentation
CompiledInUObjectsRegisteredDelegate
FCompiledInUObjectsRegisteredDelegate FCoreUObjectDelegates::CompiledInUObjectsRegisteredDelegate static
Definition at line 3325 of file UObjectGlobals.h.
GarbageCollectComplete
FSimpleMulticastDelegate FCoreUObjectDelegates::GarbageCollectComplete static
Called after garbage collection is complete, all objects have been purged (regardless of whether incremental purge is enabled or not), memory has been trimmed and all other GC callbacks have been fired.
Definition at line 3377 of file UObjectGlobals.h.
GetPrimaryAssetIdForObject
FGetPrimaryAssetIdForObject FCoreUObjectDelegates::GetPrimaryAssetIdForObject static
Definition at line 3389 of file UObjectGlobals.h.
IsPackageOKToSaveDelegate
FIsPackageOKToSaveDelegate FCoreUObjectDelegates::IsPackageOKToSaveDelegate static
Definition at line 3288 of file UObjectGlobals.h.
NetworkFileRequestPackageReload
FNetworkFileRequestPackageReload FCoreUObjectDelegates::NetworkFileRequestPackageReload static
Definition at line 3284 of file UObjectGlobals.h.
ObjectsModifiedThisFrame
TSet<UObject*> FCoreUObjectDelegates::ObjectsModifiedThisFrame static
Set of objects modified this frame, to prevent multiple triggerings of the OnObjectModified delegate.
Definition at line 3192 of file UObjectGlobals.h.
Referenced by BroadcastOnObjectModified().
OnAssetLoaded
FOnAssetLoaded FCoreUObjectDelegates::OnAssetLoaded static
Definition at line 3259 of file UObjectGlobals.h.
OnEndLoadPackage
FOnEndLoadPackage FCoreUObjectDelegates::OnEndLoadPackage static
Definition at line 3266 of file UObjectGlobals.h.
OnObjectConstructed
FOnObjectConstructed FCoreUObjectDelegates::OnObjectConstructed static
Definition at line 3262 of file UObjectGlobals.h.
OnObjectModified
FOnObjectModified FCoreUObjectDelegates::OnObjectModified static
Definition at line 3189 of file UObjectGlobals.h.
Referenced by BroadcastOnObjectModified().
OnObjectPostCDOCompiled
FOnObjectPostCDOCompiled FCoreUObjectDelegates::OnObjectPostCDOCompiled static
Definition at line 3247 of file UObjectGlobals.h.
OnObjectPreSave
FOnObjectPreSave FCoreUObjectDelegates::OnObjectPreSave static
Definition at line 3255 of file UObjectGlobals.h.
OnObjectPropertyChanged
FOnObjectPropertyChanged FCoreUObjectDelegates::OnObjectPropertyChanged static
Definition at line 3181 of file UObjectGlobals.h.
OnObjectRenamed
FOnObjectRenamed FCoreUObjectDelegates::OnObjectRenamed static
Definition at line 3206 of file UObjectGlobals.h.
Referenced by BroadcastOnObjectRenamed().
OnObjectsReinstanced
FOnObjectsReinstanced FCoreUObjectDelegates::OnObjectsReinstanced static
Definition at line 3233 of file UObjectGlobals.h.
OnObjectsReplaced
FOnObjectsReplaced FCoreUObjectDelegates::OnObjectsReplaced static
Definition at line 3225 of file UObjectGlobals.h.
Referenced by TExternalDirtyActorsTracker< StoreType >::TExternalDirtyActorsTracker(), and TExternalDirtyActorsTracker< StoreType >::~TExternalDirtyActorsTracker().
OnObjectTransacted
FOnObjectTransacted FCoreUObjectDelegates::OnObjectTransacted static
Definition at line 3216 of file UObjectGlobals.h.
OnPackageReloaded
FOnPackageReloaded FCoreUObjectDelegates::OnPackageReloaded static
Definition at line 3280 of file UObjectGlobals.h.
OnPostInitSparseClassData
FOnPostInitSparseClassData FCoreUObjectDelegates::OnPostInitSparseClassData static
Definition at line 3276 of file UObjectGlobals.h.
OnPreObjectPropertyChanged
FOnPreObjectPropertyChanged FCoreUObjectDelegates::OnPreObjectPropertyChanged static
Definition at line 3185 of file UObjectGlobals.h.
OnVerseDeadObjectReferences
FOnVerseDeadReferences FCoreUObjectDelegates::OnVerseDeadObjectReferences static
Definition at line 3239 of file UObjectGlobals.h.
PackageCreatedForLoad
FPackageCreatedForLoad FCoreUObjectDelegates::PackageCreatedForLoad static
Definition at line 3385 of file UObjectGlobals.h.
PostDemoPlay
FSimpleMulticastDelegate FCoreUObjectDelegates::PostDemoPlay static
Sent when a network replay has started.
Definition at line 3340 of file UObjectGlobals.h.
PostGarbageCollectConditionalBeginDestroy
FSimpleMulticastDelegate FCoreUObjectDelegates::PostGarbageCollectConditionalBeginDestroy static
Called after ConditionalBeginDestroy phase of garbage collection.
Definition at line 3374 of file UObjectGlobals.h.
PostLoadMapWithWorld
FPostLoadMapDelegate FCoreUObjectDelegates::PostLoadMapWithWorld static
Definition at line 3337 of file UObjectGlobals.h.
PostReachabilityAnalysis
FSimpleMulticastDelegate FCoreUObjectDelegates::PostReachabilityAnalysis static
Called after reachability analysis, before any purging.
Definition at line 3356 of file UObjectGlobals.h.
PreGarbageCollectConditionalBeginDestroy
FSimpleMulticastDelegate FCoreUObjectDelegates::PreGarbageCollectConditionalBeginDestroy static
Called before ConditionalBeginDestroy phase of garbage collection.
Definition at line 3371 of file UObjectGlobals.h.
PreLoadMap
FPreLoadMapDelegate FCoreUObjectDelegates::PreLoadMap static
Definition at line 3329 of file UObjectGlobals.h.
PreLoadMapWithContext
FPreLoadMapWithContextDelegate FCoreUObjectDelegates::PreLoadMapWithContext static
Definition at line 3333 of file UObjectGlobals.h.
ReloadAddedClassesDelegate
FReloadAddedClassesDelegate FCoreUObjectDelegates::ReloadAddedClassesDelegate static
Definition at line 3292 of file UObjectGlobals.h.
ReloadCompleteDelegate
FReloadCompleteDelegate FCoreUObjectDelegates::ReloadCompleteDelegate static
Definition at line 3300 of file UObjectGlobals.h.
ReloadReinstancingCompleteDelegate
FReloadReinstancingCompleteDelegate FCoreUObjectDelegates::ReloadReinstancingCompleteDelegate static
Definition at line 3296 of file UObjectGlobals.h.
ShouldCookPackageForPlatform
FShouldCookPackageForPlatform FCoreUObjectDelegates::ShouldCookPackageForPlatform static
Definition at line 3393 of file UObjectGlobals.h.
ShouldLoadOnTop
FOnLoadObjectsOnTop FCoreUObjectDelegates::ShouldLoadOnTop static
Definition at line 3381 of file UObjectGlobals.h.
The documentation for this struct was generated from the following file:
Runtime/CoreUObject/Public/UObject/UObjectGlobals.h