Unreal Engine 5.6 C++ API: Metasound::TDataLiteralFactory< DataType, CreatorType > Struct Template Reference
Metasound::TDataLiteralFactory< DataType, CreatorType > Struct Template Reference
A base factory type for creating objects related to Metasound DataTypes.
#include "MetasoundDataFactory.h"
Public Types
using FInternalFactory = DataFactoryPrivate::TDataVariantFactoryInternal<DataType, CreatorType>
Static Public Member Functions
template<typename FirstVariantType, typename... AdditionalVariantTypes>
static auto CreateAny (const FOperatorSettings &InSettings, const TVariant< FirstVariantType, AdditionalVariantTypes... > &InVariant)
Create the object using any supported constructor.
static auto CreateExplicitArgs (const FOperatorSettings &InSettings, const FLiteral &InLiteral)
Create the object using only constructors which utilize the InLiteral.
template<typename DesiredArgType, typename FirstVariantType, typename... AdditionalVariantTypes>
static auto CreateExplicitArgs (const FOperatorSettings &InSettings, const TVariant< FirstVariantType, AdditionalVariantTypes... > &InVariant)
Create the object using only constructors which utilize the InVariant.
Detailed Description
template<typename DataType, typename CreatorType>
struct Metasound::TDataLiteralFactory< DataType, CreatorType >
A base factory type for creating objects related to Metasound DataTypes.
TDataLiteralFactory provides a unified interface for constructing objects using a FOperatorSettings and FLiteral. The various factory methods determine how strictly the DataType constructors must match the arguments to the factory method.
Template Parameters
DataType - The registered metasound data type which defines the supported constructors.
CreatorType - A class providing a static "CreateNew(...)" function which accepts the forwarded arguments and returns an object.
Definition at line 1013 of file MetasoundDataFactory.h.
Member Typedef Documentation
FInternalFactory
template<typename DataType, typename CreatorType> using Metasound::TDataLiteralFactory< DataType, CreatorType >::FInternalFactory = DataFactoryPrivate::TDataVariantFactoryInternal<DataType, CreatorType>
Definition at line 1015 of file MetasoundDataFactory.h.
Member Function Documentation
CreateAny()
template<typename DataType, typename CreatorType> template<typename FirstVariantType, typename... AdditionalVariantTypes> auto Metasound::TDataLiteralFactory< DataType, CreatorType >::CreateAny (const FOperatorSettings & InSettings, const TVariant< FirstVariantType, AdditionalVariantTypes... > & InVariant) inline static
Create the object using any supported constructor.
Definition at line 1019 of file MetasoundDataFactory.h.
Referenced by CreateExplicitArgs().
CreateExplicitArgs() [1/2]
template<typename DataType, typename CreatorType> auto Metasound::TDataLiteralFactory< DataType, CreatorType >::CreateExplicitArgs (const FOperatorSettings & InSettings, const FLiteral & InLiteral) inline static
Create the object using only constructors which utilize the InLiteral.
Parameters
InSettings - The FOperatorSettings to be passed to the DataType constructor if an appropriate constructor exists.
InLiteral - The literal to be passed to the constructor.
Returns
An object related to the DataType. The exact type determined by the CreatorType class template parameter.
Definition at line 1044 of file MetasoundDataFactory.h.
References Metasound::Boolean, Metasound::BooleanArray, checkNoEntry, CreateAny(), CreateExplicitArgs(), TArray< InElementType, InAllocatorType >::Emplace(), Metasound::Float, Metasound::FloatArray, TSharedPtr< ObjectType, InMode >::Get(), TVariant< T, Ts >::Get(), Metasound::FLiteral::GetType(), Metasound::Integer, Metasound::IntegerArray, Metasound::Invalid, Metasound::None, Metasound::NoneArray, PRAGMA_DISABLE_DEPRECATION_WARNINGS, PRAGMA_ENABLE_DEPRECATION_WARNINGS, TUniquePtr< T, Deleter >::Release(), Metasound::String, Metasound::StringArray, Metasound::UObjectProxy, Metasound::UObjectProxyArray, Metasound::Value, Metasound::FLiteral::Value, and Metasound::TIsParsable< DataType, ArgTypes >::Value.
CreateExplicitArgs() [2/2]
template<typename DataType, typename CreatorType> template<typename DesiredArgType, typename FirstVariantType, typename... AdditionalVariantTypes> auto Metasound::TDataLiteralFactory< DataType, CreatorType >::CreateExplicitArgs (const FOperatorSettings & InSettings, const TVariant< FirstVariantType, AdditionalVariantTypes... > & InVariant) inline static
Create the object using only constructors which utilize the InVariant.
Definition at line 1028 of file MetasoundDataFactory.h.
Referenced by CreateExplicitArgs().
The documentation for this struct was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/Metasound/Source/MetasoundGraphCore/Public/MetasoundDataFactory.h