Unreal Engine 5.6 C++ API: FSlateRotatedRect Struct Reference
FSlateRotatedRect Struct Reference
Stores a rectangle that has been transformed by an arbitrary render transform.
#include "SlateRotatedRect.h"
Public Member Functions
FSlateRotatedRect ()
Default ctor.
FSlateRotatedRect (const FSlateRect &AlignedRect)
Construct a rotated rect from a given aligned rect.
FSlateRotatedRect (const UE::Slate::FDeprecateVector2DParameter &InTopLeft, const UE::Slate::FDeprecateVector2DParameter &InExtentX, const UE::Slate::FDeprecateVector2DParameter &InExtentY)
Per-element constructor.
bool IsUnderLocation (const UE::Slate::FDeprecateVector2DParameter Location) const
Point-in-rect test.
bool operator== (const FSlateRotatedRect &Other) const
FSlateRect ToBoundingRect () const
Convert to a bounding, aligned rect.
Static Public Member Functions
static FSlateRotatedRect MakeRotatedRect (const FSlateRect &ClipRectInLayoutWindowSpace, const FSlateLayoutTransform &InverseLayoutTransform, const FSlateRenderTransform &RenderTransform)
static FSlateRotatedRect MakeRotatedRect (const FSlateRect &ClipRectInLayoutWindowSpace, const FTransform2f &LayoutToRenderTransform)
static FSlateRotatedRect MakeSnappedRotatedRect (const FSlateRect &ClipRectInLayoutWindowSpace, const FSlateLayoutTransform &InverseLayoutTransform, const FSlateRenderTransform &RenderTransform)
static FSlateRotatedRect MakeSnappedRotatedRect (const FSlateRect &ClipRectInLayoutWindowSpace, const FTransform2f &LayoutToRenderTransform)
Used to construct a rotated rect from an aligned clip rect and a set of layout and render transforms from the geometry, snapped to pixel boundaries.
Data Fields
FVector2f ExtentX
transformed X extent (right-left).
FVector2f ExtentY
transformed Y extent (bottom-top).
FVector2f TopLeft
transformed Top-left corner.
Detailed Description
Stores a rectangle that has been transformed by an arbitrary render transform.
We provide a ctor that does the work common to slate drawing, but you could technically create this any way you want.
Definition at line 19 of file SlateRotatedRect.h.
Constructor & Destructor Documentation
FSlateRotatedRect() [1/3]
FSlateRotatedRect::FSlateRotatedRect () inline
Default ctor.
Definition at line 23 of file SlateRotatedRect.h.
Referenced by MakeRotatedRect(), MakeRotatedRect(), MakeSnappedRotatedRect(), MakeSnappedRotatedRect(), and operator==().
FSlateRotatedRect() [2/3]
FSlateRotatedRect::FSlateRotatedRect (const FSlateRect & AlignedRect) inline explicit
Construct a rotated rect from a given aligned rect.
Definition at line 26 of file SlateRotatedRect.h.
References Bottom, ExtentX, ExtentY, Left, Right, Top, and TopLeft.
FSlateRotatedRect() [3/3]
FSlateRotatedRect::FSlateRotatedRect (const UE::Slate::FDeprecateVector2DParameter & InTopLeft, const UE::Slate::FDeprecateVector2DParameter & InExtentX, const UE::Slate::FDeprecateVector2DParameter & InExtentY) inline
Per-element constructor.
Definition at line 34 of file SlateRotatedRect.h.
References ExtentX, ExtentY, and TopLeft.
Member Function Documentation
IsUnderLocation()
bool FSlateRotatedRect::IsUnderLocation (const UE::Slate::FDeprecateVector2DParameter Location) const
Point-in-rect test.
References Location.
Referenced by USTRUCT().
MakeRotatedRect() [1/2]
FSlateRotatedRect FSlateRotatedRect::MakeRotatedRect (const FSlateRect & ClipRectInLayoutWindowSpace, const FSlateLayoutTransform & InverseLayoutTransform, const FSlateRenderTransform & RenderTransform) inline static
Definition at line 67 of file SlateRotatedRect.h.
References FSlateRotatedRect(), Concatenate(), MakeRotatedRect(), and RenderTransform.
Referenced by MakeRotatedRect().
MakeRotatedRect() [2/2]
FSlateRotatedRect FSlateRotatedRect::MakeRotatedRect (const FSlateRect & ClipRectInLayoutWindowSpace, const FTransform2f & LayoutToRenderTransform) static
References FSlateRotatedRect().
MakeSnappedRotatedRect() [1/2]
FSlateRotatedRect FSlateRotatedRect::MakeSnappedRotatedRect (const FSlateRect & ClipRectInLayoutWindowSpace, const FSlateLayoutTransform & InverseLayoutTransform, const FSlateRenderTransform & RenderTransform) inline static
Definition at line 74 of file SlateRotatedRect.h.
References FSlateRotatedRect(), Concatenate(), MakeSnappedRotatedRect(), and RenderTransform.
Referenced by MakeSnappedRotatedRect().
MakeSnappedRotatedRect() [2/2]
FSlateRotatedRect FSlateRotatedRect::MakeSnappedRotatedRect (const FSlateRect & ClipRectInLayoutWindowSpace, const FTransform2f & LayoutToRenderTransform) static
Used to construct a rotated rect from an aligned clip rect and a set of layout and render transforms from the geometry, snapped to pixel boundaries.
Returns a float or float16 version of the rect based on the typedef.
References FSlateRotatedRect().
operator==()
bool FSlateRotatedRect::operator== (const FSlateRotatedRect & Other) const inline
Definition at line 51 of file SlateRotatedRect.h.
References FSlateRotatedRect(), ExtentX, ExtentY, Other, and TopLeft.
ToBoundingRect()
FSlateRect FSlateRotatedRect::ToBoundingRect () const
Convert to a bounding, aligned rect.
Field Documentation
ExtentX
FVector2f FSlateRotatedRect::ExtentX
transformed X extent (right-left).
Definition at line 46 of file SlateRotatedRect.h.
Referenced by FSlateRotatedRect(), FSlateRotatedRect(), operator==(), and TransformRect().
ExtentY
FVector2f FSlateRotatedRect::ExtentY
transformed Y extent (bottom-top).
Definition at line 48 of file SlateRotatedRect.h.
Referenced by FSlateRotatedRect(), FSlateRotatedRect(), operator==(), and TransformRect().
TopLeft
FVector2f FSlateRotatedRect::TopLeft
transformed Top-left corner.
Definition at line 44 of file SlateRotatedRect.h.
Referenced by FSlateRotatedRect(), FSlateRotatedRect(), operator==(), and TransformRect().
The documentation for this struct was generated from the following file:
Runtime/SlateCore/Public/Layout/SlateRotatedRect.h