Unreal Engine 5.6 C++ API: FDisplayClusterShadersTextureUtilsSettings Struct Reference
FDisplayClusterShadersTextureUtilsSettings Struct Reference
#include "DisplayClusterShaderContainers_TextureUtils.h"
Public Member Functions
FDisplayClusterShadersTextureUtilsSettings ()=default
FDisplayClusterShadersTextureUtilsSettings (const EColorWriteMask InColorMask)
FDisplayClusterShadersTextureUtilsSettings (const EColorWriteMask InColorMask, const EDisplayClusterShaderTextureUtilsFlags InFlags, const uint32 InDestSliceIndex=0)
FDisplayClusterShadersTextureUtilsSettings (const EDisplayClusterShaderTextureUtilsFlags InFlags, const uint32 InDestSliceIndex=0)
FDisplayClusterShadersTextureUtilsSettings (const EDisplayClusterShaderTextureUtilsOverrideAlpha InOverrideAlpha)
FDisplayClusterShadersTextureUtilsSettings (const FDisplayClusterShadersTextureUtilsSettings &InSettigns, const EColorWriteMask InColorMask)
FDisplayClusterShadersTextureUtilsSettings (const FDisplayClusterShadersTextureUtilsSettings &InSettigns, const EDisplayClusterShaderTextureUtilsFlags InFlags, const uint32 InDestSliceIndex=0)
void AddFlags (const EDisplayClusterShaderTextureUtilsFlags InFlags)
bool HasAnyFlags (const EDisplayClusterShaderTextureUtilsFlags InFlags) const
Data Fields
EColorWriteMask ColorMask = EColorWriteMask::CW_RGBA
Color mask.
uint32 DestSliceIndex = 0
EDisplayClusterShaderTextureUtilsFlags Flags = EDisplayClusterShaderTextureUtilsFlags::None
Additional flags.
EDisplayClusterShaderTextureUtilsOverrideAlpha OverrideAlpha = EDisplayClusterShaderTextureUtilsOverrideAlpha::None
Override alpha channel.
uint32 SourceSliceIndex = 0
Additional parameters for the FRHICopyTextureInfo.
Detailed Description
Definition at line 149 of file DisplayClusterShaderContainers_TextureUtils.h.
Constructor & Destructor Documentation
FDisplayClusterShadersTextureUtilsSettings() [1/7]
FDisplayClusterShadersTextureUtilsSettings::FDisplayClusterShadersTextureUtilsSettings () default
Referenced by FDisplayClusterShadersTextureUtilsSettings(), and FDisplayClusterShadersTextureUtilsSettings().
FDisplayClusterShadersTextureUtilsSettings() [2/7]
FDisplayClusterShadersTextureUtilsSettings::FDisplayClusterShadersTextureUtilsSettings (const FDisplayClusterShadersTextureUtilsSettings & InSettigns, const EDisplayClusterShaderTextureUtilsFlags InFlags, const uint32 InDestSliceIndex = 0) inline
Definition at line 153 of file DisplayClusterShaderContainers_TextureUtils.h.
References FDisplayClusterShadersTextureUtilsSettings(), DestSliceIndex, and Flags.
FDisplayClusterShadersTextureUtilsSettings() [3/7]
FDisplayClusterShadersTextureUtilsSettings::FDisplayClusterShadersTextureUtilsSettings (const EColorWriteMask InColorMask) inline
Definition at line 163 of file DisplayClusterShaderContainers_TextureUtils.h.
References ColorMask.
FDisplayClusterShadersTextureUtilsSettings() [4/7]
FDisplayClusterShadersTextureUtilsSettings::FDisplayClusterShadersTextureUtilsSettings (const FDisplayClusterShadersTextureUtilsSettings & InSettigns, const EColorWriteMask InColorMask) inline
Definition at line 166 of file DisplayClusterShaderContainers_TextureUtils.h.
References FDisplayClusterShadersTextureUtilsSettings(), and ColorMask.
FDisplayClusterShadersTextureUtilsSettings() [5/7]
FDisplayClusterShadersTextureUtilsSettings::FDisplayClusterShadersTextureUtilsSettings (const EDisplayClusterShaderTextureUtilsOverrideAlpha InOverrideAlpha) inline
Definition at line 174 of file DisplayClusterShaderContainers_TextureUtils.h.
References OverrideAlpha.
FDisplayClusterShadersTextureUtilsSettings() [6/7]
FDisplayClusterShadersTextureUtilsSettings::FDisplayClusterShadersTextureUtilsSettings (const EColorWriteMask InColorMask, const EDisplayClusterShaderTextureUtilsFlags InFlags, const uint32 InDestSliceIndex = 0) inline
Definition at line 177 of file DisplayClusterShaderContainers_TextureUtils.h.
References ColorMask, DestSliceIndex, and Flags.
FDisplayClusterShadersTextureUtilsSettings() [7/7]
FDisplayClusterShadersTextureUtilsSettings::FDisplayClusterShadersTextureUtilsSettings (const EDisplayClusterShaderTextureUtilsFlags InFlags, const uint32 InDestSliceIndex = 0) inline
Definition at line 183 of file DisplayClusterShaderContainers_TextureUtils.h.
References DestSliceIndex, and Flags.
Member Function Documentation
AddFlags()
void FDisplayClusterShadersTextureUtilsSettings::AddFlags (const EDisplayClusterShaderTextureUtilsFlags InFlags) inline
Definition at line 193 of file DisplayClusterShaderContainers_TextureUtils.h.
References EnumAddFlags(), and Flags.
HasAnyFlags()
bool FDisplayClusterShadersTextureUtilsSettings::HasAnyFlags (const EDisplayClusterShaderTextureUtilsFlags InFlags) const inline
Definition at line 188 of file DisplayClusterShaderContainers_TextureUtils.h.
References EnumHasAnyFlags(), and Flags.
Field Documentation
ColorMask
EColorWriteMask FDisplayClusterShadersTextureUtilsSettings::ColorMask = EColorWriteMask::CW_RGBA
Color mask.
Definition at line 200 of file DisplayClusterShaderContainers_TextureUtils.h.
Referenced by FDisplayClusterShadersTextureUtilsSettings(), FDisplayClusterShadersTextureUtilsSettings(), and FDisplayClusterShadersTextureUtilsSettings().
DestSliceIndex
uint32 FDisplayClusterShadersTextureUtilsSettings::DestSliceIndex = 0
Definition at line 210 of file DisplayClusterShaderContainers_TextureUtils.h.
Referenced by FDisplayClusterShadersTextureUtilsSettings(), FDisplayClusterShadersTextureUtilsSettings(), and FDisplayClusterShadersTextureUtilsSettings().
Flags
EDisplayClusterShaderTextureUtilsFlags FDisplayClusterShadersTextureUtilsSettings::Flags = EDisplayClusterShaderTextureUtilsFlags::None
Additional flags.
Definition at line 203 of file DisplayClusterShaderContainers_TextureUtils.h.
Referenced by FDisplayClusterShadersTextureUtilsSettings(), FDisplayClusterShadersTextureUtilsSettings(), FDisplayClusterShadersTextureUtilsSettings(), AddFlags(), and HasAnyFlags().
OverrideAlpha
EDisplayClusterShaderTextureUtilsOverrideAlpha FDisplayClusterShadersTextureUtilsSettings::OverrideAlpha = EDisplayClusterShaderTextureUtilsOverrideAlpha::None
Override alpha channel.
Definition at line 206 of file DisplayClusterShaderContainers_TextureUtils.h.
Referenced by FDisplayClusterShadersTextureUtilsSettings().
SourceSliceIndex
uint32 FDisplayClusterShadersTextureUtilsSettings::SourceSliceIndex = 0
Additional parameters for the FRHICopyTextureInfo.
Definition at line 209 of file DisplayClusterShaderContainers_TextureUtils.h.
The documentation for this struct was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/nDisplay/Source/DisplayClusterShaders/Public/Containers/DisplayClusterShaderContainers_TextureUtils.h