Unreal Engine 5.6 C++ API: FVTProduceTargetLayer Struct Reference
FVTProduceTargetLayer Struct Reference
Describes a location to write a single layer of a VT tile.
#include "VirtualTexturing.h"
Public Member Functions
PRAGMA_DISABLE_DEPRECATION_WARNINGS FVTProduceTargetLayer ()=default
FVTProduceTargetLayer (const FVTProduceTargetLayer &)=default
FVTProduceTargetLayer & operator= (const FVTProduceTargetLayer &)=default
UE_DEPRECATED (5.6, "Use PooledRenderTarget instead.") FRHITexture *TextureRHI
Data Fields
IPooledRenderTarget * PooledRenderTarget = nullptr
Pooled render target to write to.
FIntVector pPageLocation = FIntVector::ZeroValue
Location within the target texture to write.
Detailed Description
Describes a location to write a single layer of a VT tile.
Definition at line 263 of file VirtualTexturing.h.
Constructor & Destructor Documentation
FVTProduceTargetLayer() [1/2]
PRAGMA_DISABLE_DEPRECATION_WARNINGS FVTProduceTargetLayer::FVTProduceTargetLayer () default
References FVTProduceTargetLayer().
Referenced by FVTProduceTargetLayer(), FVTProduceTargetLayer(), and operator=().
FVTProduceTargetLayer() [2/2]
FVTProduceTargetLayer::FVTProduceTargetLayer (const FVTProduceTargetLayer &) default
References FVTProduceTargetLayer().
Member Function Documentation
operator=()
FVTProduceTargetLayer & FVTProduceTargetLayer::operator= (const FVTProduceTargetLayer &) default
References FVTProduceTargetLayer(), and PRAGMA_ENABLE_DEPRECATION_WARNINGS.
UE_DEPRECATED()
FVTProduceTargetLayer::UE_DEPRECATED (5. 6, "Use PooledRenderTarget instead.")
References PRAGMA_DISABLE_DEPRECATION_WARNINGS.
Field Documentation
PooledRenderTarget
IPooledRenderTarget* FVTProduceTargetLayer::PooledRenderTarget = nullptr
Pooled render target to write to.
Definition at line 266 of file VirtualTexturing.h.
pPageLocation
FIntVector FVTProduceTargetLayer::pPageLocation = FIntVector::ZeroValue
Location within the target texture to write.
Definition at line 268 of file VirtualTexturing.h.
The documentation for this struct was generated from the following file:
Runtime/RenderCore/Public/VirtualTexturing.h