Unreal Engine 5.6 C++ API: FSlateWindowElementList::FDeferredPaint Struct Reference
FSlateWindowElementList::FDeferredPaint Struct Reference
Some widgets may want to paint their children after after another, loosely-related widget finished painting.
#include "DrawElements.h"
Public Member Functions
FDeferredPaint (const TSharedRef< const SWidget > &InWidgetToPaint, const FPaintArgs &InArgs, const FGeometry InAllottedGeometry, const FWidgetStyle &InWidgetStyle, bool InParentEnabled)
FDeferredPaint Copy (const FPaintArgs &InArgs)
int32 ExecutePaint (int32 LayerId, FSlateWindowElementList &OutDrawElements, const FSlateRect &MyCullingRect) const
Private Member Functions
FDeferredPaint (const FDeferredPaint &Copy, const FPaintArgs &InArgs)
Private Attributes
const FGeometry AllottedGeometry
const FPaintArgs Args
const bool bParentEnabled
const FWidgetStyle WidgetStyle
const TWeakPtr< const SWidget > WidgetToPaintPtr
Detailed Description
Some widgets may want to paint their children after after another, loosely-related widget finished painting.
Or they may want to paint "after everyone".
Definition at line 329 of file DrawElements.h.
Constructor & Destructor Documentation
FDeferredPaint() [1/2]
FSlateWindowElementList::FDeferredPaint::FDeferredPaint (const TSharedRef< const SWidget > & InWidgetToPaint, const FPaintArgs & InArgs, const FGeometry InAllottedGeometry, const FWidgetStyle & InWidgetStyle, bool InParentEnabled)
Referenced by FDeferredPaint(), and Copy().
FDeferredPaint() [2/2]
FSlateWindowElementList::FDeferredPaint::FDeferredPaint (const FDeferredPaint & Copy, const FPaintArgs & InArgs) private
References FDeferredPaint(), and Copy().
Member Function Documentation
Copy()
FDeferredPaint FSlateWindowElementList::FDeferredPaint::Copy (const FPaintArgs & InArgs)
References FDeferredPaint().
Referenced by FDeferredPaint().
ExecutePaint()
int32 FSlateWindowElementList::FDeferredPaint::ExecutePaint (int32 LayerId, FSlateWindowElementList & OutDrawElements, const FSlateRect & MyCullingRect) const
References FSlateWindowElementList::FSlateWindowElementList().
Field Documentation
AllottedGeometry
const FGeometry FSlateWindowElementList::FDeferredPaint::AllottedGeometry private
Definition at line 344 of file DrawElements.h.
Args
const FPaintArgs FSlateWindowElementList::FDeferredPaint::Args private
Definition at line 343 of file DrawElements.h.
bParentEnabled
const bool FSlateWindowElementList::FDeferredPaint::bParentEnabled private
Definition at line 346 of file DrawElements.h.
WidgetStyle
const FWidgetStyle FSlateWindowElementList::FDeferredPaint::WidgetStyle private
Definition at line 345 of file DrawElements.h.
WidgetToPaintPtr
const TWeakPtr<const SWidget> FSlateWindowElementList::FDeferredPaint::WidgetToPaintPtr private
Definition at line 342 of file DrawElements.h.
The documentation for this struct was generated from the following file:
Runtime/SlateCore/Public/Rendering/DrawElements.h