Unreal Engine 5.6 C++ API: TMovieSceneChannelHandle< ChannelType > Struct Template Reference
TMovieSceneChannelHandle< ChannelType > Struct Template Reference
Forward declaration of a typed channel handle.
#include "MovieSceneChannelHandle.h"
Public Member Functions
TMovieSceneChannelHandle ()
TMovieSceneChannelHandle (TWeakPtr< FMovieSceneChannelProxy > InWeakChannelProxy, int32 InChannelIndex)
Construction from a weak channel proxy, and the channel's index.
ChannelType * Get () const
Get the channel pointer this handle represents.
const TMovieSceneChannelTraits< ChannelType >::ExtendedEditorDataType * GetExtendedEditorData () const
Get the extended editor data associated with this channel.
Protected Member Functions
TMovieSceneChannelHandle (TWeakPtr< FMovieSceneChannelProxy > InWeakChannelProxy, FName InChannelTypeName, int32 InChannelIndex)
Protected Attributes
friend FMovieSceneChannelHandle
Detailed Description
template<typename ChannelType>
struct TMovieSceneChannelHandle< ChannelType >
Forward declaration of a typed channel handle.
Handle to a specific channel in a UMovieSceneSection.
Typed channel handles replicate the inheritance hierarchy of their channels in order that overload resolution on them can happen without user-conversion or templating
Will become nullptr when the FMovieSceneChannelProxy it was created with is reallocated. The handle class hierarchy matches that of the channel itself so that functions can be overloaded for any given base/derived handle type
Definition at line 166 of file MovieSceneChannelHandle.h.
Constructor & Destructor Documentation
TMovieSceneChannelHandle() [1/3]
template<typename ChannelType> TMovieSceneChannelHandle< ChannelType >::TMovieSceneChannelHandle () inline
Definition at line 168 of file MovieSceneChannelHandle.h.
Referenced by TMovieSceneChannelHandle(), and TMovieSceneChannelHandle().
TMovieSceneChannelHandle() [2/3]
template<typename ChannelType> TMovieSceneChannelHandle< ChannelType >::TMovieSceneChannelHandle (TWeakPtr< FMovieSceneChannelProxy > InWeakChannelProxy, int32 InChannelIndex) inline
Construction from a weak channel proxy, and the channel's index.
Definition at line 174 of file MovieSceneChannelHandle.h.
References TMovieSceneChannelHandle(), StaticStruct(), and Super.
TMovieSceneChannelHandle() [3/3]
template<typename ChannelType> TMovieSceneChannelHandle< ChannelType >::TMovieSceneChannelHandle (TWeakPtr< FMovieSceneChannelProxy > InWeakChannelProxy, FName InChannelTypeName, int32 InChannelIndex) inline protected
Definition at line 204 of file MovieSceneChannelHandle.h.
References TMovieSceneChannelHandle(), and Super.
Member Function Documentation
Get()
template<typename ChannelType> ChannelType * TMovieSceneChannelHandle< ChannelType >::Get () const inline
Get the channel pointer this handle represents.
Returns
the channel's pointer, or nullptr if the proxy it was created with is no longer alive.
Definition at line 183 of file MovieSceneChannelHandle.h.
References FMovieSceneChannelHandle::Get().
Referenced by FMovieSceneChannelValueHelper::FMovieSceneChannelValueHelper(), FSequencerKeyStructGenerator::CopyInstanceToKey(), FSequencerKeyStructGenerator::CreateKeyStructInstance(), PostConstructKeyInstance(), and IMovieSceneKeyProxy::RefreshCurrentValue().
GetExtendedEditorData()
template<typename ChannelType> const TMovieSceneChannelTraits< ChannelType >::ExtendedEditorDataType * TMovieSceneChannelHandle< ChannelType >::GetExtendedEditorData () const inline
Get the extended editor data associated with this channel.
Returns
the channel's extended editor data, or nullptr if the proxy it was created with is no longer alive.
Definition at line 195 of file MovieSceneChannelHandle.h.
References FMovieSceneChannelHandle::GetExtendedEditorData().
Field Documentation
FMovieSceneChannelHandle
template<typename ChannelType> friend TMovieSceneChannelHandle< ChannelType >::FMovieSceneChannelHandle protected
Definition at line 208 of file MovieSceneChannelHandle.h.
The documentation for this struct was generated from the following files:
Editor/MovieSceneTools/Public/Channels/BoolChannelCurveModel.h
Runtime/MovieScene/Public/Channels/MovieSceneChannelHandle.h