Unreal Engine 5.6 C++ API: UE::Geometry::FZOrderCurvePoints Struct Reference
UE::Geometry::FZOrderCurvePoints Struct Reference
Generate a "z-order curve" ordering for a point set by distributing the points to a quad- or octree and then reading the points indices back in tree traversal order This is useful for giving the points spatial locality – so points that are close together in the ordering tend to be close together spatially, also.
#include "ZOrderCurvePoints.h"
Public Member Functions
FZOrderCurvePoints (int32 MaxTreeDepth=10)
GEOMETRYCORE_API void Compute (TArrayView< const FVector2d > Points, const FAxisAlignedBox2d &Bounds=FAxisAlignedBox2d::Empty())
Compute an ordering for the input points that attempts to order points so adjacent points are close together spatially Supports both 2D and 3D points.
GEOMETRYCORE_API void Compute (TArrayView< const FVector2f > Points, const FAxisAlignedBox2f &Bounds=FAxisAlignedBox2f::Empty())
GEOMETRYCORE_API void Compute (TArrayView< const FVector3d > Points, const FAxisAlignedBox3d &Bounds=FAxisAlignedBox3d::Empty())
GEOMETRYCORE_API void Compute (TArrayView< const FVector3f > Points, const FAxisAlignedBox3f &Bounds=FAxisAlignedBox3f::Empty())
Data Fields
int32 MaxTreeDepth = 10
Inputs.
TArray< int32 > Order
Outputs.
Detailed Description
Generate a "z-order curve" ordering for a point set by distributing the points to a quad- or octree and then reading the points indices back in tree traversal order This is useful for giving the points spatial locality – so points that are close together in the ordering tend to be close together spatially, also.
Definition at line 24 of file ZOrderCurvePoints.h.
Constructor & Destructor Documentation
FZOrderCurvePoints()
UE::Geometry::FZOrderCurvePoints::FZOrderCurvePoints (int32 MaxTreeDepth = 10) inline
Definition at line 38 of file ZOrderCurvePoints.h.
References MaxTreeDepth.
Member Function Documentation
Compute() [1/4]
GEOMETRYCORE_API void UE::Geometry::FZOrderCurvePoints::Compute (TArrayView< const FVector2d > Points, const FAxisAlignedBox2d & Bounds = FAxisAlignedBox2d::Empty())
Compute an ordering for the input points that attempts to order points so adjacent points are close together spatially Supports both 2D and 3D points.
Parameters
Points Points to re-order
Bounds Optional bounding box of the points; if an empty box is passed in, it will be computed for you
References UE::Geometry::TAxisAlignedBox2< double >::Empty(), and Points.
Compute() [2/4]
GEOMETRYCORE_API void UE::Geometry::FZOrderCurvePoints::Compute (TArrayView< const FVector2f > Points, const FAxisAlignedBox2f & Bounds = FAxisAlignedBox2f::Empty())
References UE::Geometry::TAxisAlignedBox2< float >::Empty(), and Points.
Compute() [3/4]
GEOMETRYCORE_API void UE::Geometry::FZOrderCurvePoints::Compute (TArrayView< const FVector3d > Points, const FAxisAlignedBox3d & Bounds = FAxisAlignedBox3d::Empty())
References UE::Geometry::TAxisAlignedBox3< double >::Empty(), and Points.
Compute() [4/4]
GEOMETRYCORE_API void UE::Geometry::FZOrderCurvePoints::Compute (TArrayView< const FVector3f > Points, const FAxisAlignedBox3f & Bounds = FAxisAlignedBox3f::Empty())
References UE::Geometry::TAxisAlignedBox3< float >::Empty(), and Points.
Field Documentation
MaxTreeDepth
int32 UE::Geometry::FZOrderCurvePoints::MaxTreeDepth = 10
Inputs.
Definition at line 29 of file ZOrderCurvePoints.h.
Referenced by FZOrderCurvePoints().
Order
TArray<int32> UE::Geometry::FZOrderCurvePoints::Order
Outputs.
Definition at line 34 of file ZOrderCurvePoints.h.
The documentation for this struct was generated from the following file:
Runtime/GeometryCore/Public/Spatial/ZOrderCurvePoints.h