Unreal Engine 5.6 C++ API: FDisplayClusterSceneViewExtensionContext Struct Reference
FDisplayClusterSceneViewExtensionContext Struct Reference
Contains information about the context in which this scene view extension will be used.
#include "DisplayClusterSceneViewExtensions.h"
Public Member Functions
FDisplayClusterSceneViewExtensionContext ()
FDisplayClusterSceneViewExtensionContext (FSceneInterface *InScene, const TSharedRef< const IDisplayClusterViewport, ESPMode::ThreadSafe > &InDisplayClusterViewport)
FDisplayClusterSceneViewExtensionContext (FViewport *InViewport, const TSharedRef< const IDisplayClusterViewport, ESPMode::ThreadSafe > &InDisplayClusterViewport)
bool IsSameDisplayClusterViewportConfiguration (const TSharedRef< const IDisplayClusterViewportConfiguration, ESPMode::ThreadSafe > InConfigurationRef) const
Returns true if this viewport context refers to the same configuration.
Public Member Functions inherited from FSceneViewExtensionContext
FSceneViewExtensionContext ()
FSceneViewExtensionContext (FSceneInterface *InScene)
FSceneViewExtensionContext (FViewport *InViewport)
virtual ~FSceneViewExtensionContext ()
UWorld * GetWorld () const
Retrieve the world pointer for this context.
bool IsA (const FSceneViewExtensionContext &&Other) const
bool IsStereoSupported () const
Data Fields
const TSharedPtr< const IDisplayClusterViewport, ESPMode::ThreadSafe > DisplayClusterViewport
Data Fields inherited from FSceneViewExtensionContext
bool bStereoEnabled = false
FSceneInterface * Scene = nullptr
FViewport * Viewport = nullptr
Private Member Functions
virtual FName GetRTTI () const override
virtual bool IsHMDSupported () const override
Detailed Description
Contains information about the context in which this scene view extension will be used.
Definition at line 12 of file DisplayClusterSceneViewExtensions.h.
Constructor & Destructor Documentation
FDisplayClusterSceneViewExtensionContext() [1/3]
FDisplayClusterSceneViewExtensionContext::FDisplayClusterSceneViewExtensionContext () inline
Definition at line 25 of file DisplayClusterSceneViewExtensions.h.
References FSceneViewExtensionContext::FSceneViewExtensionContext().
FDisplayClusterSceneViewExtensionContext() [2/3]
FDisplayClusterSceneViewExtensionContext::FDisplayClusterSceneViewExtensionContext (FViewport * InViewport, const TSharedRef< const IDisplayClusterViewport, ESPMode::ThreadSafe > & InDisplayClusterViewport) inline
Definition at line 29 of file DisplayClusterSceneViewExtensions.h.
References FSceneViewExtensionContext::FSceneViewExtensionContext(), and DisplayClusterViewport.
FDisplayClusterSceneViewExtensionContext() [3/3]
FDisplayClusterSceneViewExtensionContext::FDisplayClusterSceneViewExtensionContext (FSceneInterface * InScene, const TSharedRef< const IDisplayClusterViewport, ESPMode::ThreadSafe > & InDisplayClusterViewport) inline
Definition at line 36 of file DisplayClusterSceneViewExtensions.h.
References FSceneViewExtensionContext::FSceneViewExtensionContext(), and DisplayClusterViewport.
Member Function Documentation
GetRTTI()
virtual FName FDisplayClusterSceneViewExtensionContext::GetRTTI () const inline override private virtual
Reimplemented from FSceneViewExtensionContext.
Definition at line 16 of file DisplayClusterSceneViewExtensions.h.
References TEXT.
IsHMDSupported()
virtual bool FDisplayClusterSceneViewExtensionContext::IsHMDSupported () const inline override private virtual
Reimplemented from FSceneViewExtensionContext.
Definition at line 18 of file DisplayClusterSceneViewExtensions.h.
IsSameDisplayClusterViewportConfiguration()
bool FDisplayClusterSceneViewExtensionContext::IsSameDisplayClusterViewportConfiguration (const TSharedRef< const IDisplayClusterViewportConfiguration, ESPMode::ThreadSafe > InConfigurationRef) const inline
Returns true if this viewport context refers to the same configuration.
Definition at line 44 of file DisplayClusterSceneViewExtensions.h.
References DisplayClusterViewport.
Field Documentation
DisplayClusterViewport
const TSharedPtr<const IDisplayClusterViewport, ESPMode::ThreadSafe> FDisplayClusterSceneViewExtensionContext::DisplayClusterViewport
Definition at line 57 of file DisplayClusterSceneViewExtensions.h.
Referenced by FDisplayClusterSceneViewExtensionContext(), FDisplayClusterSceneViewExtensionContext(), and IsSameDisplayClusterViewportConfiguration().
The documentation for this struct was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/nDisplay/Source/DisplayCluster/Public/DisplayClusterSceneViewExtensions.h