Unreal Engine 5.6 C++ API: UE::Geometry::FPolygroupSet Struct Reference
UE::Geometry::FPolygroupSet Struct Reference
Polygroup sets can be stored in multiple places.
#include "PolygroupSet.h"
Public Member Functions
DYNAMICMESH_API FPolygroupSet (const FDynamicMesh3 *MeshIn)
Initialize a PolygroupSet for the given Mesh, and standard triangle group layer.
DYNAMICMESH_API FPolygroupSet (const FDynamicMesh3 *MeshIn, const FDynamicMeshPolygroupAttribute *PolygroupAttribIn)
Initialize a PolygroupSet for given Mesh and specific Polygroup attribute layer.
DYNAMICMESH_API FPolygroupSet (const FDynamicMesh3 *MeshIn, FName AttribName)
Initialize a PolygroupSet for given Mesh and specific Polygroup attribute layer, found by name.
DYNAMICMESH_API FPolygroupSet (const FDynamicMesh3 *MeshIn, FPolygroupLayer GroupLayer)
Initialize a PolygroupSet for the given Mesh, and standard triangle group layer.
DYNAMICMESH_API FPolygroupSet (const FDynamicMesh3 *MeshIn, int32 PolygroupLayerIndex)
Initialize a PolygroupSet for given Mesh and specific Polygroup attribute layer, found by index.
DYNAMICMESH_API FPolygroupSet (const FPolygroupSet *CopyIn)
Initialize a PolygroupSet by copying an existing PolygroupSet.
int32 AllocateNewGroupID ()
Allocate a new unused PolygroupID by incrementing the MaxGroupID member.
int32 GetGroup (int32 TriangleID) const
const FDynamicMesh3 * GetMesh ()
const FDynamicMeshPolygroupAttribute * GetPolygroup ()
int32 GetPolygroupIndex () const
int32 GetTriangleGroup (int32 TriangleID) const
DYNAMICMESH_API void RecalculateMaxGroupID ()
Calculate the current maximum PolygroupID used in the active set and store in MaxGroupID member.
void SetGroup (int32 TriangleID, int32 NewGroupID, FDynamicMesh3 &WritableMesh)
Set the PolygroupID for a TriangleID.
Data Fields
int32 GroupLayerIndex = -1
int32 MaxGroupID = 0
const FDynamicMesh3 * Mesh = nullptr
const FDynamicMeshPolygroupAttribute * PolygroupAttrib = nullptr
Detailed Description
Polygroup sets can be stored in multiple places.
The default location is in the per-triangle group integer stored directly on a FDynamicMesh3. Additional layers may be stored in the FDynamicMeshAttributeSet. Future iterations could store packed polygroups in other places, store them in separate arrays, and so on. FPolygroupSet can be used to abstract these different cases, by providing a standard Polygroup Get/Set API.
To support unique Polygroup ID allocation, FPolygroupSet calculates the maximum GroupID on creation, and updates this maximum across SetGroup() calls. AllocateNewGroupID() can be used to provide new unused GroupIDs. For consistency with FDynamicMesh3, MaxGroupID is set such that all GroupIDs are less than MaxGroupID
Definition at line 62 of file PolygroupSet.h.
Constructor & Destructor Documentation
FPolygroupSet() [1/6]
DYNAMICMESH_API UE::Geometry::FPolygroupSet::FPolygroupSet (const FDynamicMesh3 * MeshIn) explicit
Initialize a PolygroupSet for the given Mesh, and standard triangle group layer.
References UE_API.
Referenced by FPolygroupSet().
FPolygroupSet() [2/6]
DYNAMICMESH_API UE::Geometry::FPolygroupSet::FPolygroupSet (const FDynamicMesh3 * MeshIn, FPolygroupLayer GroupLayer) explicit
Initialize a PolygroupSet for the given Mesh, and standard triangle group layer.
References UE_API.
FPolygroupSet() [3/6]
DYNAMICMESH_API UE::Geometry::FPolygroupSet::FPolygroupSet (const FDynamicMesh3 * MeshIn, const FDynamicMeshPolygroupAttribute * PolygroupAttribIn) explicit
Initialize a PolygroupSet for given Mesh and specific Polygroup attribute layer.
References UE_API.
FPolygroupSet() [4/6]
DYNAMICMESH_API UE::Geometry::FPolygroupSet::FPolygroupSet (const FDynamicMesh3 * MeshIn, int32 PolygroupLayerIndex) explicit
Initialize a PolygroupSet for given Mesh and specific Polygroup attribute layer, found by index.
If not valid, fall back to standard triangle group layer.
References UE_API.
FPolygroupSet() [5/6]
DYNAMICMESH_API UE::Geometry::FPolygroupSet::FPolygroupSet (const FDynamicMesh3 * MeshIn, FName AttribName) explicit
Initialize a PolygroupSet for given Mesh and specific Polygroup attribute layer, found by name.
If not valid, fall back to standard triangle group layer.
References UE_API.
FPolygroupSet() [6/6]
DYNAMICMESH_API UE::Geometry::FPolygroupSet::FPolygroupSet (const FPolygroupSet * CopyIn) explicit
Initialize a PolygroupSet by copying an existing PolygroupSet.
References FPolygroupSet(), and UE_API.
Member Function Documentation
AllocateNewGroupID()
int32 UE::Geometry::FPolygroupSet::AllocateNewGroupID () inline
Allocate a new unused PolygroupID by incrementing the MaxGroupID member.
Definition at line 144 of file PolygroupSet.h.
References MaxGroupID.
GetGroup()
int32 UE::Geometry::FPolygroupSet::GetGroup (int32 TriangleID) const inline
Returns
PolygroupID for a TriangleID
Definition at line 101 of file PolygroupSet.h.
References Mesh, and PolygroupAttrib.
GetMesh()
const FDynamicMesh3 * UE::Geometry::FPolygroupSet::GetMesh () inline
Returns
Mesh this PolygroupSet references
Definition at line 89 of file PolygroupSet.h.
References Mesh.
GetPolygroup()
const FDynamicMeshPolygroupAttribute * UE::Geometry::FPolygroupSet::GetPolygroup () inline
Returns
PolygroupAttribute this PolygroupSet references, or null if no PolygroupAttribute is in use
Definition at line 92 of file PolygroupSet.h.
References PolygroupAttrib.
GetPolygroupIndex()
int32 UE::Geometry::FPolygroupSet::GetPolygroupIndex () const inline
Returns
index of current PolygroupAttribute into Mesh AttributeSet, or -1 if this information does not exist
Definition at line 95 of file PolygroupSet.h.
References GroupLayerIndex.
GetTriangleGroup()
int32 UE::Geometry::FPolygroupSet::GetTriangleGroup (int32 TriangleID) const inline
Returns
PolygroupID for a TriangleID
Definition at line 109 of file PolygroupSet.h.
References Mesh, and PolygroupAttrib.
RecalculateMaxGroupID()
DYNAMICMESH_API void UE::Geometry::FPolygroupSet::RecalculateMaxGroupID ()
Calculate the current maximum PolygroupID used in the active set and store in MaxGroupID member.
References UE_API.
SetGroup()
void UE::Geometry::FPolygroupSet::SetGroup (int32 TriangleID, int32 NewGroupID, FDynamicMesh3 & WritableMesh) inline
Set the PolygroupID for a TriangleID.
Definition at line 117 of file PolygroupSet.h.
References UE::Geometry::FDynamicMesh3::Attributes(), checkSlow, UE::Geometry::FDynamicMeshAttributeSet::GetPolygroupLayer(), GroupLayerIndex, UE::Geometry::FDynamicMesh3::IsTriangle(), FMath::Max, MaxGroupID, PolygroupAttrib, UE::Geometry::FDynamicMesh3::SetTriangleGroup(), and UE::Geometry::TDynamicMeshScalarTriangleAttribute< RealType >::SetValue().
Field Documentation
GroupLayerIndex
int32 UE::Geometry::FPolygroupSet::GroupLayerIndex = -1
Definition at line 66 of file PolygroupSet.h.
Referenced by GetPolygroupIndex(), and SetGroup().
MaxGroupID
int32 UE::Geometry::FPolygroupSet::MaxGroupID = 0
Definition at line 67 of file PolygroupSet.h.
Referenced by AllocateNewGroupID(), and SetGroup().
Mesh
const FDynamicMesh3* UE::Geometry::FPolygroupSet::Mesh = nullptr
Definition at line 64 of file PolygroupSet.h.
Referenced by GetGroup(), GetMesh(), and GetTriangleGroup().
PolygroupAttrib
const FDynamicMeshPolygroupAttribute* UE::Geometry::FPolygroupSet::PolygroupAttrib = nullptr
Definition at line 65 of file PolygroupSet.h.
Referenced by GetGroup(), GetPolygroup(), GetTriangleGroup(), and SetGroup().
The documentation for this struct was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/GeometryProcessing/Source/DynamicMesh/Public/Polygroups/PolygroupSet.h