Unreal Engine 5.6 C++ API: FWorldPartitionActorDescInitData Struct Reference
FWorldPartitionActorDescInitData Struct Reference
#include "WorldPartitionActorDesc.h"
Public Member Functions
FWorldPartitionActorDescInitData ()
FWorldPartitionActorDescInitData (FActorDescArchive *InArchive)
FActorDescArchive * GetArchive () const
TArray< uint8 > & GetSerializedData ()
const TArray< uint8 > & GetSerializedData () const
bool IsUsingArchive () const
FWorldPartitionActorDescInitData & SetActorPath (const FSoftObjectPath &InActorPath)
FWorldPartitionActorDescInitData & SetNativeClass (UClass *InNativeClass)
FWorldPartitionActorDescInitData & SetPackageName (FName InPackageName)
Data Fields
FSoftObjectPath ActorPath
UClass * NativeClass
FName PackageName
Private Attributes
TVariant< TArray< uint8 >, FActorDescArchive * > DataSource
Detailed Description
Definition at line 23 of file WorldPartitionActorDesc.h.
Constructor & Destructor Documentation
FWorldPartitionActorDescInitData() [1/2]
FWorldPartitionActorDescInitData::FWorldPartitionActorDescInitData () inline
Definition at line 25 of file WorldPartitionActorDesc.h.
References DataSource.
Referenced by SetActorPath(), SetNativeClass(), and SetPackageName().
FWorldPartitionActorDescInitData() [2/2]
FWorldPartitionActorDescInitData::FWorldPartitionActorDescInitData (FActorDescArchive * InArchive) inline
Definition at line 29 of file WorldPartitionActorDesc.h.
References DataSource.
Member Function Documentation
GetArchive()
FActorDescArchive * FWorldPartitionActorDescInitData::GetArchive () const inline
Definition at line 49 of file WorldPartitionActorDesc.h.
References check, and DataSource.
GetSerializedData() [1/2]
TArray< uint8 > & FWorldPartitionActorDescInitData::GetSerializedData () inline
Definition at line 37 of file WorldPartitionActorDesc.h.
References check, and DataSource.
GetSerializedData() [2/2]
const TArray< uint8 > & FWorldPartitionActorDescInitData::GetSerializedData () const inline
Definition at line 43 of file WorldPartitionActorDesc.h.
References check, and DataSource.
IsUsingArchive()
bool FWorldPartitionActorDescInitData::IsUsingArchive () const inline
Definition at line 55 of file WorldPartitionActorDesc.h.
References DataSource.
SetActorPath()
FWorldPartitionActorDescInitData & FWorldPartitionActorDescInitData::SetActorPath (const FSoftObjectPath & InActorPath) inline
Definition at line 62 of file WorldPartitionActorDesc.h.
References FWorldPartitionActorDescInitData(), and ActorPath.
SetNativeClass()
FWorldPartitionActorDescInitData & FWorldPartitionActorDescInitData::SetNativeClass (UClass * InNativeClass) inline
Definition at line 60 of file WorldPartitionActorDesc.h.
References FWorldPartitionActorDescInitData(), and NativeClass.
SetPackageName()
FWorldPartitionActorDescInitData & FWorldPartitionActorDescInitData::SetPackageName (FName InPackageName) inline
Definition at line 61 of file WorldPartitionActorDesc.h.
References FWorldPartitionActorDescInitData(), and PackageName.
Field Documentation
ActorPath
FSoftObjectPath FWorldPartitionActorDescInitData::ActorPath
Definition at line 35 of file WorldPartitionActorDesc.h.
Referenced by SetActorPath().
DataSource
TVariant<TArray<uint8>, FActorDescArchive*> FWorldPartitionActorDescInitData::DataSource private
Definition at line 66 of file WorldPartitionActorDesc.h.
Referenced by FWorldPartitionActorDescInitData(), FWorldPartitionActorDescInitData(), GetArchive(), GetSerializedData(), GetSerializedData(), and IsUsingArchive().
NativeClass
UClass* FWorldPartitionActorDescInitData::NativeClass
Definition at line 33 of file WorldPartitionActorDesc.h.
Referenced by SetNativeClass().
PackageName
FName FWorldPartitionActorDescInitData::PackageName
Definition at line 34 of file WorldPartitionActorDesc.h.
Referenced by SetPackageName().
The documentation for this struct was generated from the following file:
Runtime/Engine/Public/WorldPartition/WorldPartitionActorDesc.h