Unreal Engine 5.6 C++ API: UE::MovieScene::TPropertyTrackEntityImportHelperImpl< T > Struct Template Reference
UE::MovieScene::TPropertyTrackEntityImportHelperImpl< T > Struct Template Reference
Utility class for importing a customizable property track entity in a way that automatically supports being inside a bound property track or not, and being hooked up to a property with an edit condition or not.
#include "MovieScenePropertyTrack.h"
Public Member Functions
TPropertyTrackEntityImportHelperImpl (TEntityBuilder< T... > &&InBuilder, FComponentTypeID InPropertyTag={})
template<typename U, typename PayloadType>
TPropertyTrackEntityImportHelperImpl< T..., TAdd< U > > Add (TComponentTypeID< U > ComponentType, PayloadType &&InPayload)
template<typename U, typename PayloadType>
TPropertyTrackEntityImportHelperImpl< T..., TAddConditional< U > > AddConditional (TComponentTypeID< U > ComponentType, PayloadType &&InPayload, bool bCondition)
void Commit (const UMovieSceneSection *InSection, const UE::MovieScene::FEntityImportParams &Params, UE::MovieScene::FImportedEntity *OutImportedEntity)
Protected Attributes
TEntityBuilder< T... > Builder
FComponentTypeID PropertyTag
Detailed Description
template<typename... T>
struct UE::MovieScene::TPropertyTrackEntityImportHelperImpl< T >
Utility class for importing a customizable property track entity in a way that automatically supports being inside a bound property track or not, and being hooked up to a property with an edit condition or not.
Definition at line 181 of file MovieScenePropertyTrack.h.
Constructor & Destructor Documentation
TPropertyTrackEntityImportHelperImpl()
template<typename... T> UE::MovieScene::TPropertyTrackEntityImportHelperImpl< T >::TPropertyTrackEntityImportHelperImpl (TEntityBuilder< T... > && InBuilder, FComponentTypeID InPropertyTag = {}) inline
Definition at line 183 of file MovieScenePropertyTrack.h.
Referenced by Add(), and AddConditional().
Member Function Documentation
Add()
template<typename... T> template<typename U, typename PayloadType> TPropertyTrackEntityImportHelperImpl< T..., TAdd< U > > UE::MovieScene::TPropertyTrackEntityImportHelperImpl< T >::Add (TComponentTypeID< U > ComponentType, PayloadType && InPayload) inline
Definition at line 190 of file MovieScenePropertyTrack.h.
References TPropertyTrackEntityImportHelperImpl(), Builder, and PropertyTag.
AddConditional()
template<typename... T> template<typename U, typename PayloadType> TPropertyTrackEntityImportHelperImpl< T..., TAddConditional< U > > UE::MovieScene::TPropertyTrackEntityImportHelperImpl< T >::AddConditional (TComponentTypeID< U > ComponentType, PayloadType && InPayload, bool bCondition) inline
Definition at line 196 of file MovieScenePropertyTrack.h.
References TPropertyTrackEntityImportHelperImpl(), Builder, and PropertyTag.
Referenced by Commit().
Commit()
template<typename... T> void UE::MovieScene::TPropertyTrackEntityImportHelperImpl< T >::Commit (const UMovieSceneSection * InSection, const UE::MovieScene::FEntityImportParams & Params, UE::MovieScene::FImportedEntity * OutImportedEntity) inline
Definition at line 201 of file MovieScenePropertyTrack.h.
References Add, UE::MovieScene::FImportedEntity::AddBuilder(), AddConditional(), Builder, Cast(), ensure, UE::MovieScene::FBuiltInComponentTypes::GenericObjectBinding, UE::MovieScene::FBuiltInComponentTypes::Get(), UE::MovieScene::FMovieSceneTracksComponentTypes::Get(), FMovieScenePropertyTrackEntityImportHelper::ImportEditConditionToggleEntity(), FMovieScenePropertyTrackEntityImportHelper::IsEditConditionToggleID(), FMovieScenePropertyTrackEntityImportHelper::IsPropertyValueID(), FGuid::IsValid(), Params, and UE::MovieScene::FBuiltInComponentTypes::PropertyBinding.
Field Documentation
Builder
template<typename... T> TEntityBuilder<T...> UE::MovieScene::TPropertyTrackEntityImportHelperImpl< T >::Builder protected
Definition at line 233 of file MovieScenePropertyTrack.h.
Referenced by Add(), AddConditional(), and Commit().
PropertyTag
template<typename... T> FComponentTypeID UE::MovieScene::TPropertyTrackEntityImportHelperImpl< T >::PropertyTag protected
Definition at line 234 of file MovieScenePropertyTrack.h.
Referenced by Add(), and AddConditional().
The documentation for this struct was generated from the following file:
Runtime/MovieSceneTracks/Public/Tracks/MovieScenePropertyTrack.h