Unreal Engine 5.6 C++ API: UE::Anim::TWrappedAttribute< InAllocator > Struct Template Reference
UE::Anim::TWrappedAttribute< InAllocator > Struct Template Reference
Helper struct to wrap and templated operate raw memory.
#include "WrappedAttribute.h"
Public Member Functions
TWrappedAttribute ()
TWrappedAttribute (const UScriptStruct *InStruct)
Construct with allocates memory buffer according to type size.
template<typename AttributeType>
FORCEINLINE void Allocate ()
Allocated memory buffer according to type size.
FORCEINLINE void Allocate (const UScriptStruct *InStruct)
Allocated memory buffer according to type size.
template<typename Type>
FORCEINLINE TEnableIf< TIsFundamentalType< Type >::Value, Type * >::Type GetPtr ()
Returns typed ptr to memory.
template<typename Type>
FORCEINLINE TEnableIf<!TIsFundamentalType< Type >::Value, Type * >::Type GetPtr ()
template<typename Type>
FORCEINLINE TEnableIf< TIsFundamentalType< Type >::Value, constType * >::Type GetPtr () const
Returns typed const ptr to memory.
template<typename Type>
FORCEINLINE TEnableIf<!TIsFundamentalType< Type >::Value, constType * >::Type GetPtr () const
template<typename Type>
FORCEINLINE Type & GetRef ()
template<typename Type>
FORCEINLINE const Type & GetRef () const
Returns typed const reference to memory.
Protected Attributes
TArray< uint8, InAllocator > StructMemory
Detailed Description
template<typename InAllocator>
struct UE::Anim::TWrappedAttribute< InAllocator >
Helper struct to wrap and templated operate raw memory.
Definition at line 15 of file WrappedAttribute.h.
Constructor & Destructor Documentation
TWrappedAttribute() [1/2]
template<typename InAllocator> UE::Anim::TWrappedAttribute< InAllocator >::TWrappedAttribute () inline
Definition at line 17 of file WrappedAttribute.h.
TWrappedAttribute() [2/2]
template<typename InAllocator> UE::Anim::TWrappedAttribute< InAllocator >::TWrappedAttribute (const UScriptStruct * InStruct) inline
Construct with allocates memory buffer according to type size.
Definition at line 20 of file WrappedAttribute.h.
Member Function Documentation
Allocate() [1/2]
template<typename InAllocator> template<typename AttributeType> FORCEINLINE void UE::Anim::TWrappedAttribute< InAllocator >::Allocate () inline
Allocated memory buffer according to type size.
Definition at line 64 of file WrappedAttribute.h.
Referenced by UE::Anim::TWrappedAttribute< FDefaultAllocator >::TWrappedAttribute(), and UE::Anim::TWrappedAttribute< FDefaultAllocator >::Allocate().
Allocate() [2/2]
template<typename InAllocator> FORCEINLINE void UE::Anim::TWrappedAttribute< InAllocator >::Allocate (const UScriptStruct * InStruct) inline
Allocated memory buffer according to type size.
Definition at line 70 of file WrappedAttribute.h.
GetPtr() [1/4]
template<typename InAllocator> template<typename Type> FORCEINLINE TEnableIf< TIsFundamentalType< Type >::Value, Type * >::Type UE::Anim::TWrappedAttribute< InAllocator >::GetPtr () inline
Returns typed ptr to memory.
Definition at line 27 of file WrappedAttribute.h.
Referenced by UE::Anim::TWrappedAttribute< FDefaultAllocator >::GetRef(), and UE::Anim::TWrappedAttribute< FDefaultAllocator >::GetRef().
GetPtr() [2/4]
template<typename InAllocator> template<typename Type> FORCEINLINE TEnableIf<!TIsFundamentalType< Type >::Value, Type * >::Type UE::Anim::TWrappedAttribute< InAllocator >::GetPtr () inline
Definition at line 33 of file WrappedAttribute.h.
GetPtr() [3/4]
template<typename InAllocator> template<typename Type> FORCEINLINE TEnableIf< TIsFundamentalType< Type >::Value, constType * >::Type UE::Anim::TWrappedAttribute< InAllocator >::GetPtr () const inline
Returns typed const ptr to memory.
Definition at line 45 of file WrappedAttribute.h.
GetPtr() [4/4]
template<typename InAllocator> template<typename Type> FORCEINLINE TEnableIf<!TIsFundamentalType< Type >::Value, constType * >::Type UE::Anim::TWrappedAttribute< InAllocator >::GetPtr () const inline
Definition at line 51 of file WrappedAttribute.h.
GetRef() [1/2]
template<typename InAllocator> template<typename Type> FORCEINLINE Type & UE::Anim::TWrappedAttribute< InAllocator >::GetRef () inline
Definition at line 41 of file WrappedAttribute.h.
GetRef() [2/2]
template<typename InAllocator> template<typename Type> FORCEINLINE const Type & UE::Anim::TWrappedAttribute< InAllocator >::GetRef () const inline
Returns typed const reference to memory.
Definition at line 60 of file WrappedAttribute.h.
Field Documentation
StructMemory
template<typename InAllocator> TArray<uint8, InAllocator> UE::Anim::TWrappedAttribute< InAllocator >::StructMemory protected
Definition at line 83 of file WrappedAttribute.h.
The documentation for this struct was generated from the following file:
Runtime/Engine/Classes/Animation/WrappedAttribute.h