Unreal Engine 5.6 C++ API: UE::MovieScene::TStaticChildEntityInitializer< ParentComponentType, ChildComponentType, InitializerType > Struct Template Reference
UE::MovieScene::TStaticChildEntityInitializer< ParentComponentType, ChildComponentType, InitializerType > Struct Template Reference
#include "MovieSceneEntityFactoryTemplates.h"
Public Member Functions
TStaticChildEntityInitializer (TComponentTypeID< ParentComponentType > InParentComponent, TComponentTypeID< ChildComponentType > InChildComponent, InitializerType InCallback)
virtual void Run (const FEntityRange &ChildRange, const FEntityAllocation *ParentAllocation, TArrayView< const int32 > ParentAllocationOffsets)
Public Member Functions inherited from UE::MovieScene::TChildEntityInitializer< ParentComponentType, ChildComponentType >
TChildEntityInitializer (TComponentTypeID< ParentComponentType > InParentComponent, TComponentTypeID< ChildComponentType > InChildComponent)
TComponentTypeID< ChildComponentType > GetChildComponent () const
TComponentLock< TWrite< ChildComponentType > > GetChildComponents (const FEntityAllocation *Allocation) const
TComponentTypeID< ParentComponentType > GetParentComponent () const
TComponentLock< TRead< ParentComponentType > > GetParentComponents (const FEntityAllocation *Allocation) const
Public Member Functions inherited from UE::MovieScene::FChildEntityInitializer
virtual ~FChildEntityInitializer ()
FComponentTypeID GetChildComponent () const
FComponentTypeID GetParentComponent () const
virtual bool IsRelevant (const FComponentMask &InParentType, const FComponentMask &InChildType) const
Data Fields
InitializerType Callback
Additional Inherited Members
Protected Member Functions inherited from UE::MovieScene::FChildEntityInitializer
FChildEntityInitializer (FComponentTypeID InParentComponent, FComponentTypeID InChildComponent)
Protected Attributes inherited from UE::MovieScene::FChildEntityInitializer
FComponentTypeID ChildComponent
FComponentTypeID ParentComponent
Detailed Description
template<typename ParentComponentType, typename ChildComponentType, typename InitializerType>
struct UE::MovieScene::TStaticChildEntityInitializer< ParentComponentType, ChildComponentType, InitializerType >
Definition at line 61 of file MovieSceneEntityFactoryTemplates.h.
Constructor & Destructor Documentation
TStaticChildEntityInitializer()
template<typename ParentComponentType, typename ChildComponentType, typename InitializerType> UE::MovieScene::TStaticChildEntityInitializer< ParentComponentType, ChildComponentType, InitializerType >::TStaticChildEntityInitializer (TComponentTypeID< ParentComponentType > InParentComponent, TComponentTypeID< ChildComponentType > InChildComponent, InitializerType InCallback) inline explicit
Definition at line 65 of file MovieSceneEntityFactoryTemplates.h.
References UE::MovieScene::TChildEntityInitializer< ParentComponentType, ChildComponentType >::TChildEntityInitializer(), and Callback.
Member Function Documentation
Run()
template<typename ParentComponentType, typename ChildComponentType, typename InitializerType> virtual void UE::MovieScene::TStaticChildEntityInitializer< ParentComponentType, ChildComponentType, InitializerType >::Run (const FEntityRange & ChildRange, const FEntityAllocation * ParentAllocation, TArrayView< const int32 > ParentAllocationOffsets) inline virtual
Implements UE::MovieScene::FChildEntityInitializer.
Definition at line 70 of file MovieSceneEntityFactoryTemplates.h.
References Callback, UE::MovieScene::TChildEntityInitializer< ParentComponentType, ChildComponentType >::GetChildComponent(), and UE::MovieScene::TChildEntityInitializer< ParentComponentType, ChildComponentType >::GetParentComponent().
Field Documentation
Callback
template<typename ParentComponentType, typename ChildComponentType, typename InitializerType> InitializerType UE::MovieScene::TStaticChildEntityInitializer< ParentComponentType, ChildComponentType, InitializerType >::Callback
Definition at line 63 of file MovieSceneEntityFactoryTemplates.h.
Referenced by TStaticChildEntityInitializer(), and Run().
The documentation for this struct was generated from the following file:
Runtime/MovieScene/Public/EntitySystem/MovieSceneEntityFactoryTemplates.h