Unreal Engine 5.6 C++ API: FSparseDelegate Struct Reference
FSparseDelegate Struct Reference
Base implementation for all sparse delegate types.
#include "SparseDelegate.h"
Public Member Functions
FSparseDelegate ()
void __Internal_AddUnique (const UObject *DelegateOwner, FName DelegateName, FScriptDelegate InDelegate)
Adds a function delegate to this multi-cast delegate's invocation list if a delegate with the same signature doesn't already exist in the invocation list.
void __Internal_Clear (const UObject *DelegateOwner, FName DelegateName)
Removes all functions from this delegate's invocation list.
void __Internal_Remove (const UObject *DelegateOwner, FName DelegateName, const FScriptDelegate &InDelegate)
Removes a function from this multi-cast delegate's invocation list (performance is O(N)).
bool IsBound () const
Checks to see if any functions are bound to this multi-cast delegate.
Protected Attributes
bool bIsBound
Friends
class FMulticastSparseDelegateProperty
Detailed Description
Base implementation for all sparse delegate types.
Definition at line 118 of file SparseDelegate.h.
Constructor & Destructor Documentation
FSparseDelegate()
FSparseDelegate::FSparseDelegate () inline
Definition at line 121 of file SparseDelegate.h.
References bIsBound.
Member Function Documentation
__Internal_AddUnique()
void FSparseDelegate::__Internal_AddUnique (const UObject * DelegateOwner, FName DelegateName, FScriptDelegate InDelegate) inline
Adds a function delegate to this multi-cast delegate's invocation list if a delegate with the same signature doesn't already exist in the invocation list.
Parameters
DelegateOwner UObject that owns the resolved sparse delegate
DelegateName Name of the resolved sparse delegate
InDelegate Delegate to bind to the sparse delegate
NOTE: Only call this function from blueprint sparse delegate infrastructure on a resolved generic FScriptDelegate pointer. Generally from C++ you should call AddUnique() directly.
Definition at line 147 of file SparseDelegate.h.
References FSparseDelegateStorage::AddUnique(), bIsBound, and MoveTemp().
Referenced by TSparseDynamicDelegate< MulticastDelegate, OwningClass, DelegateInfoClass >::AddUnique().
__Internal_Clear()
void FSparseDelegate::__Internal_Clear (const UObject * DelegateOwner, FName DelegateName) inline
Removes all functions from this delegate's invocation list.
Parameters
DelegateOwner UObject that owns the resolved sparse delegate
DelegateName Name of the resolved sparse delegate
NOTE: Only call this function from blueprint sparse delegate infrastructure on a resolved generic FScriptDelegate pointer. Generally from C++ you should call Clear() directly.
Definition at line 180 of file SparseDelegate.h.
References bIsBound, and FSparseDelegateStorage::Clear().
Referenced by TSparseDynamicDelegate< MulticastDelegate, OwningClass, DelegateInfoClass >::Clear().
__Internal_Remove()
void FSparseDelegate::__Internal_Remove (const UObject * DelegateOwner, FName DelegateName, const FScriptDelegate & InDelegate) inline
Removes a function from this multi-cast delegate's invocation list (performance is O(N)).
Note that the order of the delegates may not be preserved!
Parameters
DelegateOwner UObject that owns the resolved sparse delegate
DelegateName Name of the resolved sparse delegate
InDelegate Delegate to remove from the sparse delegate
NOTE: Only call this function from blueprint sparse delegate infrastructure on a resolved generic FScriptDelegate pointer. Generally from C++ you should call Remove() directly.
Definition at line 163 of file SparseDelegate.h.
References bIsBound, and FSparseDelegateStorage::Remove().
Referenced by TSparseDynamicDelegate< MulticastDelegate, OwningClass, DelegateInfoClass >::Remove().
IsBound()
bool FSparseDelegate::IsBound () const inline
Checks to see if any functions are bound to this multi-cast delegate.
Returns
True if any functions are bound
Definition at line 131 of file SparseDelegate.h.
References bIsBound.
Friends And Related Symbol Documentation
FMulticastSparseDelegateProperty
friend class FMulticastSparseDelegateProperty friend
Definition at line 191 of file SparseDelegate.h.
References FMulticastSparseDelegateProperty.
Referenced by FMulticastSparseDelegateProperty.
Field Documentation
bIsBound
bool FSparseDelegate::bIsBound protected
Definition at line 192 of file SparseDelegate.h.
Referenced by FSparseDelegate(), __Internal_AddUnique(), __Internal_Clear(), __Internal_Remove(), TSparseDynamicDelegate< MulticastDelegate, OwningClass, DelegateInfoClass >::Add(), TSparseDynamicDelegate< MulticastDelegate, OwningClass, DelegateInfoClass >::Contains(), TSparseDynamicDelegate< MulticastDelegate, OwningClass, DelegateInfoClass >::Contains(), TSparseDynamicDelegate< MulticastDelegate, OwningClass, DelegateInfoClass >::GetShared(), IsBound(), TSparseDynamicDelegate< MulticastDelegate, OwningClass, DelegateInfoClass >::Remove(), and TSparseDynamicDelegate< MulticastDelegate, OwningClass, DelegateInfoClass >::RemoveAll().
The documentation for this struct was generated from the following file:
Runtime/CoreUObject/Public/UObject/SparseDelegate.h