Unreal Engine 5.6 C++ API: TRigVMLazyValue< ComputedType > Struct Template Reference
TRigVMLazyValue< ComputedType > Struct Template Reference
A template container for a lazily computed value.
#include "RigVMMemoryStorage.h"
Public Member Functions
TRigVMLazyValue (ComputedType InConstValue)
const ComputedType & Get (const FRigVMExecuteContext &ExecuteContext) const
Public Member Functions inherited from TRigVMLazyValueBase
TRigVMLazyValueBase ()
RIGVM_API const uint8 * GetData (const FRigVMExecuteContext &Context) const
const FRigVMMemoryHandle & GetMemoryHandle () const
Protected Member Functions
TRigVMLazyValue (const TRigVMLazyValue< ComputedType > &InOther)=delete
TRigVMLazyValue (const TRigVMLazyValueBase &InOther)
Protected Attributes
ComputedType ConstValue
Protected Attributes inherited from TRigVMLazyValueBase
bool bFollowPropertyPath
FRigVMMemoryHandle * MemoryHandle
uint32 SliceHash
Friends
struct FRigVMMemoryHandle
Detailed Description
template<typename ComputedType>
struct TRigVMLazyValue< ComputedType >
A template container for a lazily computed value.
Definition at line 192 of file RigVMMemoryStorage.h.
Constructor & Destructor Documentation
TRigVMLazyValue() [1/3]
template<typename ComputedType> TRigVMLazyValue< ComputedType >::TRigVMLazyValue (ComputedType InConstValue) inline
Definition at line 196 of file RigVMMemoryStorage.h.
References TRigVMLazyValueBase::TRigVMLazyValueBase(), and ConstValue.
Referenced by TRigVMLazyValue().
TRigVMLazyValue() [2/3]
template<typename ComputedType> TRigVMLazyValue< ComputedType >::TRigVMLazyValue (const TRigVMLazyValue< ComputedType > & InOther) protected delete
References TRigVMLazyValue().
TRigVMLazyValue() [3/3]
template<typename ComputedType> TRigVMLazyValue< ComputedType >::TRigVMLazyValue (const TRigVMLazyValueBase & InOther) inline protected
Definition at line 214 of file RigVMMemoryStorage.h.
References TRigVMLazyValueBase::TRigVMLazyValueBase().
Member Function Documentation
Get()
template<typename ComputedType> const ComputedType & TRigVMLazyValue< ComputedType >::Get (const FRigVMExecuteContext & ExecuteContext) const inline
Definition at line 201 of file RigVMMemoryStorage.h.
References ConstValue, TRigVMLazyValueBase::GetData(), and TRigVMLazyValueBase::MemoryHandle.
Friends And Related Symbol Documentation
FRigVMMemoryHandle
template<typename ComputedType> friend struct FRigVMMemoryHandle friend
Definition at line 220 of file RigVMMemoryStorage.h.
References FRigVMMemoryHandle.
Referenced by FRigVMMemoryHandle.
Field Documentation
ConstValue
template<typename ComputedType> ComputedType TRigVMLazyValue< ComputedType >::ConstValue protected
Definition at line 218 of file RigVMMemoryStorage.h.
Referenced by TRigVMLazyValue(), and Get().
The documentation for this struct was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/RigVM/Source/RigVM/Public/RigVMCore/RigVMMemoryStorage.h