Unreal Engine 5.6 C++ API: TBijectionMaps< DomainType, RangeType > Struct Template Reference
TBijectionMaps< DomainType, RangeType > Struct Template Reference
#include "TwoWayMap.h"
Data Structures
struct FPairValue
Public Member Functions
TBijectionMaps ()=delete
constexpr TBijectionMaps (const std::initializer_list< FPairValue > &InitList)
constexpr const RangeType * Find (const DomainType &InValue) const
constexpr const DomainType * Find (const RangeType &InValue) const
constexpr const RangeType & FindChecked (const DomainType &InValue) const
constexpr const DomainType & FindChecked (const RangeType &InValue) const
Private Attributes
TMap< DomainType, RangeType > Image = TMap<DomainType, RangeType>()
TMap< RangeType, DomainType > PreImage = TMap<RangeType, DomainType>()
Detailed Description
template<typename DomainType, typename RangeType>
struct TBijectionMaps< DomainType, RangeType >
Definition at line 47 of file TwoWayMap.h.
Constructor & Destructor Documentation
TBijectionMaps() [1/2]
template<typename DomainType, typename RangeType> TBijectionMaps< DomainType, RangeType >::TBijectionMaps () delete
TBijectionMaps() [2/2]
template<typename DomainType, typename RangeType> TBijectionMaps< DomainType, RangeType >::TBijectionMaps (const std::initializer_list< FPairValue > & InitList) inline constexpr
Definition at line 59 of file TwoWayMap.h.
References ensureAlwaysMsgf, Image, PreImage, and TEXT.
Member Function Documentation
Find() [1/2]
template<typename DomainType, typename RangeType> const RangeType * TBijectionMaps< DomainType, RangeType >::Find (const DomainType & InValue) const inline constexpr
Definition at line 85 of file TwoWayMap.h.
References Image.
Find() [2/2]
template<typename DomainType, typename RangeType> const DomainType * TBijectionMaps< DomainType, RangeType >::Find (const RangeType & InValue) const inline constexpr
Definition at line 75 of file TwoWayMap.h.
References PreImage.
FindChecked() [1/2]
template<typename DomainType, typename RangeType> const RangeType & TBijectionMaps< DomainType, RangeType >::FindChecked (const DomainType & InValue) const inline constexpr
Definition at line 90 of file TwoWayMap.h.
References Image.
FindChecked() [2/2]
template<typename DomainType, typename RangeType> const DomainType & TBijectionMaps< DomainType, RangeType >::FindChecked (const RangeType & InValue) const inline constexpr
Definition at line 80 of file TwoWayMap.h.
References PreImage.
Field Documentation
Image
template<typename DomainType, typename RangeType> TMap<DomainType, RangeType> TBijectionMaps< DomainType, RangeType >::Image = TMap<DomainType, RangeType>() private
Definition at line 96 of file TwoWayMap.h.
Referenced by TBijectionMaps(), Find(), and FindChecked().
PreImage
template<typename DomainType, typename RangeType> TMap<RangeType, DomainType> TBijectionMaps< DomainType, RangeType >::PreImage = TMap<RangeType, DomainType>() private
Definition at line 97 of file TwoWayMap.h.
Referenced by TBijectionMaps(), Find(), and FindChecked().
The documentation for this struct was generated from the following file:
Runtime/Core/Public/Experimental/Containers/TwoWayMap.h