Unreal Engine 5.6 C++ API: FMovieSceneBlendingActuatorID Struct Reference
FMovieSceneBlendingActuatorID Struct Reference
#include "MovieSceneBlendingActuatorID.h"
Public Member Functions
FMovieSceneBlendingActuatorID (FMovieSceneAnimTypeID InTypeID)
Friends
uint32 GetTypeHash (FMovieSceneBlendingActuatorID In)
bool operator!= (FMovieSceneBlendingActuatorID A, FMovieSceneBlendingActuatorID B)
bool operator== (FMovieSceneBlendingActuatorID A, FMovieSceneBlendingActuatorID B)
Additional Inherited Members
Static Public Member Functions inherited from FMovieSceneAnimTypeID
static MOVIESCENE_API FMovieSceneAnimTypeID Combine (FMovieSceneAnimTypeID A, FMovieSceneAnimTypeID B)
static MOVIESCENE_API FMovieSceneAnimTypeID Unique ()
Protected Member Functions inherited from FMovieSceneAnimTypeID
FMovieSceneAnimTypeID ()
FMovieSceneAnimTypeID (uint64 *StaticPtr, uint32 Seed=0)
Static Protected Member Functions inherited from FMovieSceneAnimTypeID
static MOVIESCENE_API uint64 GenerateHash (void *StaticPtr, uint32 Seed)
Generate a hash from the specified static ptr.
static MOVIESCENE_API uint64 Initialize (uint64 *StaticPtr, uint32 Seed)
Initialize this structure by storing the hash result in the static ptr itself This ensures subsequent constructions with the same pointer are fast.
Protected Attributes inherited from FMovieSceneAnimTypeID
uint64 ID
Detailed Description
Definition at line 7 of file MovieSceneBlendingActuatorID.h.
Constructor & Destructor Documentation
FMovieSceneBlendingActuatorID()
FMovieSceneBlendingActuatorID::FMovieSceneBlendingActuatorID (FMovieSceneAnimTypeID InTypeID) inline explicit
Definition at line 9 of file MovieSceneBlendingActuatorID.h.
References FMovieSceneAnimTypeID::FMovieSceneAnimTypeID().
Referenced by GetTypeHash, operator!=, and operator==.
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (FMovieSceneBlendingActuatorID In) friend
Definition at line 21 of file MovieSceneBlendingActuatorID.h.
References FMovieSceneBlendingActuatorID(), GetTypeHash, and FMovieSceneAnimTypeID::ID.
Referenced by GetTypeHash.
operator!=
bool operator!= (FMovieSceneBlendingActuatorID A, FMovieSceneBlendingActuatorID B) friend
Definition at line 16 of file MovieSceneBlendingActuatorID.h.
References FMovieSceneBlendingActuatorID(), A, and B.
operator==
bool operator== (FMovieSceneBlendingActuatorID A, FMovieSceneBlendingActuatorID B) friend
Definition at line 11 of file MovieSceneBlendingActuatorID.h.
References FMovieSceneBlendingActuatorID(), A, and B.
The documentation for this struct was generated from the following file:
Runtime/MovieScene/Public/Evaluation/Blending/MovieSceneBlendingActuatorID.h