Unreal Engine 5.6 C++ API: UE::MovieScene::FColorPropertyTraits Struct Reference
UE::MovieScene::FColorPropertyTraits Struct Reference
#include "MovieSceneTracksComponentTypes.h"
Public Types
using MetaDataType = TPropertyMetaData<EColorPropertyType>
using StorageType = FIntermediateColor
Static Public Member Functions
static FIntermediateColor CombineComposites (EColorPropertyType InType, double InR, double InG, double InB, double InA)
static void GetObjectPropertyValue (const UObject *InObject, EColorPropertyType ColorType, const FCustomPropertyAccessor &BaseCustomAccessor, FIntermediateColor &OutValue)
static void GetObjectPropertyValue (const UObject *InObject, EColorPropertyType ColorType, const FName &PropertyPath, StorageType &OutValue)
static void GetObjectPropertyValue (const UObject *InObject, EColorPropertyType ColorType, FTrackInstancePropertyBindings *PropertyBindings, FIntermediateColor &OutValue)
static void GetObjectPropertyValue (const UObject *InObject, EColorPropertyType ColorType, uint16 PropertyOffset, FIntermediateColor &OutValue)
static void SetObjectPropertyValue (UObject *InObject, EColorPropertyType ColorType, const FCustomPropertyAccessor &BaseCustomAccessor, const FIntermediateColor &InValue)
static void SetObjectPropertyValue (UObject *InObject, EColorPropertyType ColorType, FTrackInstancePropertyBindings *PropertyBindings, const FIntermediateColor &InValue)
static void SetObjectPropertyValue (UObject *InObject, EColorPropertyType ColorType, uint16 PropertyOffset, const FIntermediateColor &InValue)
Detailed Description
Definition at line 290 of file MovieSceneTracksComponentTypes.h.
Member Typedef Documentation
MetaDataType
using UE::MovieScene::FColorPropertyTraits::MetaDataType = TPropertyMetaData<EColorPropertyType>
Definition at line 293 of file MovieSceneTracksComponentTypes.h.
StorageType
using UE::MovieScene::FColorPropertyTraits::StorageType = FIntermediateColor
Definition at line 292 of file MovieSceneTracksComponentTypes.h.
Member Function Documentation
CombineComposites()
FIntermediateColor UE::MovieScene::FColorPropertyTraits::CombineComposites (EColorPropertyType InType, double InR, double InG, double InB, double InA) inline static
Definition at line 352 of file MovieSceneTracksComponentTypes.h.
GetObjectPropertyValue() [1/4]
void UE::MovieScene::FColorPropertyTraits::GetObjectPropertyValue (const UObject * InObject, EColorPropertyType ColorType, const FCustomPropertyAccessor & BaseCustomAccessor, FIntermediateColor & OutValue) inline static
Definition at line 295 of file MovieSceneTracksComponentTypes.h.
References UE::MovieScene::TCustomPropertyAccessor< PropertyTraits >::Functions.
GetObjectPropertyValue() [2/4]
void UE::MovieScene::FColorPropertyTraits::GetObjectPropertyValue (const UObject * InObject, EColorPropertyType ColorType, const FName & PropertyPath, StorageType & OutValue) inline static
Definition at line 318 of file MovieSceneTracksComponentTypes.h.
References UE::MovieScene::Color, UE::MovieScene::TIndirectPropertyTraits< UObjectPropertyType, InMemoryType, bInIsComposite >::GetObjectPropertyValue(), UE::MovieScene::Linear, and UE::MovieScene::Slate.
GetObjectPropertyValue() [3/4]
void UE::MovieScene::FColorPropertyTraits::GetObjectPropertyValue (const UObject * InObject, EColorPropertyType ColorType, FTrackInstancePropertyBindings * PropertyBindings, FIntermediateColor & OutValue) inline static
Definition at line 309 of file MovieSceneTracksComponentTypes.h.
References UE::MovieScene::Color, UE::MovieScene::TIndirectPropertyTraits< UObjectPropertyType, InMemoryType, bInIsComposite >::GetObjectPropertyValue(), UE::MovieScene::Linear, and UE::MovieScene::Slate.
GetObjectPropertyValue() [4/4]
void UE::MovieScene::FColorPropertyTraits::GetObjectPropertyValue (const UObject * InObject, EColorPropertyType ColorType, uint16 PropertyOffset, FIntermediateColor & OutValue) inline static
Definition at line 300 of file MovieSceneTracksComponentTypes.h.
References UE::MovieScene::Color, UE::MovieScene::TIndirectPropertyTraits< UObjectPropertyType, InMemoryType, bInIsComposite >::GetObjectPropertyValue(), UE::MovieScene::Linear, and UE::MovieScene::Slate.
SetObjectPropertyValue() [1/3]
void UE::MovieScene::FColorPropertyTraits::SetObjectPropertyValue (UObject * InObject, EColorPropertyType ColorType, const FCustomPropertyAccessor & BaseCustomAccessor, const FIntermediateColor & InValue) inline static
Definition at line 328 of file MovieSceneTracksComponentTypes.h.
References UE::MovieScene::TCustomPropertyAccessor< PropertyTraits >::Functions.
SetObjectPropertyValue() [2/3]
void UE::MovieScene::FColorPropertyTraits::SetObjectPropertyValue (UObject * InObject, EColorPropertyType ColorType, FTrackInstancePropertyBindings * PropertyBindings, const FIntermediateColor & InValue) inline static
Definition at line 342 of file MovieSceneTracksComponentTypes.h.
References UE::MovieScene::Color, UE::MovieScene::Linear, UE::MovieScene::TIndirectPropertyTraits< UObjectPropertyType, InMemoryType, bInIsComposite >::SetObjectPropertyValue(), and UE::MovieScene::Slate.
SetObjectPropertyValue() [3/3]
void UE::MovieScene::FColorPropertyTraits::SetObjectPropertyValue (UObject * InObject, EColorPropertyType ColorType, uint16 PropertyOffset, const FIntermediateColor & InValue) inline static
Definition at line 333 of file MovieSceneTracksComponentTypes.h.
References UE::MovieScene::Color, UE::MovieScene::Linear, UE::MovieScene::TIndirectPropertyTraits< UObjectPropertyType, InMemoryType, bInIsComposite >::SetObjectPropertyValue(), and UE::MovieScene::Slate.
The documentation for this struct was generated from the following file:
Runtime/MovieSceneTracks/Public/MovieSceneTracksComponentTypes.h