Unreal Engine 5.6 C++ API: TSingleWidgetChildrenWithSlot< SlotType >::FSlotArguments Struct Reference
TSingleWidgetChildrenWithSlot< SlotType >::FSlotArguments Struct Reference
#include "Children.h"
Public Member Functions
FSlotArguments ()
SlotType::FSlotArguments & operator[] (const TSharedRef< SWidget > &InChildWidget)
Data Fields
friend TSingleWidgetChildrenWithSlot
Additional Inherited Members
Protected Member Functions inherited from TSlotBase< SlotType >::FSlotArguments
FSlotArguments (const FSlotArguments &)=delete
FSlotArguments (EConstructSlotIsFChildren)
FSlotArguments (FSlotArguments &&)=default
FSlotArguments (TUniquePtr< SlotType > InSlot)
void AttachWidget (const TSharedRef< SWidget > &InChildWidget)
Attach the child widget the slot will own.
SlotType::FSlotArguments & Expose (SlotType *&OutVarToInit)
Initialize OutVarToInit with the slot that is being constructed.
const TSharedPtr< SWidget > & GetAttachedWidget () const
SlotType * GetSlot () const
SlotType::FSlotArguments & Me ()
Used by the named argument pattern as a safe way to 'return *this' for call-chaining purposes.
FSlotArguments & operator= (const FSlotArguments &)=delete
FSlotArguments & operator= (FSlotArguments &&)=default
SlotType::FSlotArguments & operator[] (const TSharedRef< SWidget > &InChildWidget)
SlotType::FSlotArguments & operator[] (TSharedRef< SWidget > &&InChildWidget)
Attach the child widget the slot will own.
TUniquePtr< SlotType > StealSlot ()
Steal the slot that is being constructed from the FSlotArguments.
Detailed Description
template<typename SlotType>
struct TSingleWidgetChildrenWithSlot< SlotType >::FSlotArguments
Definition at line 334 of file Children.h.
Constructor & Destructor Documentation
FSlotArguments()
template<typename SlotType> TSingleWidgetChildrenWithSlot< SlotType >::FSlotArguments::FSlotArguments () inline
Definition at line 336 of file Children.h.
References FSlotArguments(), and TSlotBase< SlotType >::ConstructSlotIsFChildren.
Referenced by FSlotArguments().
Member Function Documentation
operator[]()
template<typename SlotType> SlotType::FSlotArguments & TSingleWidgetChildrenWithSlot< SlotType >::FSlotArguments::operator[] (const TSharedRef< SWidget > & InChildWidget) inline
Definition at line 343 of file Children.h.
References TSlotBase< SlotType >::FSlotArguments::AttachWidget().
Field Documentation
TSingleWidgetChildrenWithSlot
template<typename SlotType> friend TSingleWidgetChildrenWithSlot< SlotType >::FSlotArguments::TSingleWidgetChildrenWithSlot
Definition at line 341 of file Children.h.
The documentation for this struct was generated from the following file:
Runtime/SlateCore/Public/Layout/Children.h