Unreal Engine 5.6 C++ API: FNodeTextCache Struct Reference
FNodeTextCache Struct Reference
Constructing FText strings every frame can be costly, so this struct provides a way to easily cache those strings (node title, tooptip, etc.) for reuse.
#include "EdGraphNodeUtils.h"
Public Member Functions
FNodeTextCache ()
FORCEINLINE void Clear () const
FORCEINLINE FText & GetCachedText () const
FORCEINLINE bool IsOutOfDate (const UEdGraphNode *InOwningNode) const
Checks if the title is out of date.
FORCEINLINE bool IsOutOfDate (const UEdGraphSchema *InSchema) const
Checks if the title is out of date.
FORCEINLINE void MarkDirty () const
FORCEINLINE operator FText & () const
FORCEINLINE void SetCachedText (FText const &InText, const UEdGraphNode *InOwningNode) const
Checks if the title is out of date.
FORCEINLINE void SetCachedText (FText const &InText, const UEdGraphSchema *InSchema) const
Checks if the title is out of date.
Private Member Functions
FORCEINLINE void UpdateCacheIternal (FText const &InText) const
Helper to lookup from the GConfig the correct ini setting for displaying node and pin titles localized and updates the cache accordingly.
Private Attributes
FText CachedText
Mutable so that SetCachedText() can remain const (callable by the node's GetNodeTitle() method)
int32 CacheRefreshID
ID to check if the title should be considered dirty due to outside conditions that may require the title to refresh.
Detailed Description
Constructing FText strings every frame can be costly, so this struct provides a way to easily cache those strings (node title, tooptip, etc.) for reuse.
Definition at line 19 of file EdGraphNodeUtils.h.
Constructor & Destructor Documentation
FNodeTextCache()
FNodeTextCache::FNodeTextCache () inline
Definition at line 22 of file EdGraphNodeUtils.h.
References CacheRefreshID.
Member Function Documentation
Clear()
FORCEINLINE void FNodeTextCache::Clear () const inline
Definition at line 94 of file EdGraphNodeUtils.h.
References CachedText, FORCEINLINE, and FText::GetEmpty().
Referenced by MarkDirty().
GetCachedText()
FORCEINLINE FText & FNodeTextCache::GetCachedText () const inline
Definition at line 81 of file EdGraphNodeUtils.h.
References CachedText, and FORCEINLINE.
Referenced by operator FText &().
IsOutOfDate() [1/2]
FORCEINLINE bool FNodeTextCache::IsOutOfDate (const UEdGraphNode * InOwningNode) const inline
Checks if the title is out of date.
Parameters
InOwningNode Node that owns this title
Definition at line 31 of file EdGraphNodeUtils.h.
References CachedText, CacheRefreshID, and FORCEINLINE.
IsOutOfDate() [2/2]
FORCEINLINE bool FNodeTextCache::IsOutOfDate (const UEdGraphSchema * InSchema) const inline
Checks if the title is out of date.
Parameters
InSchema Schema to use for checking if externally made out of date
Definition at line 41 of file EdGraphNodeUtils.h.
References CachedText, CacheRefreshID, and FORCEINLINE.
MarkDirty()
FORCEINLINE void FNodeTextCache::MarkDirty () const inline
Definition at line 87 of file EdGraphNodeUtils.h.
References CacheRefreshID, Clear(), and FORCEINLINE.
operator FText &()
FORCEINLINE FNodeTextCache::operator FText & () const inline
Definition at line 100 of file EdGraphNodeUtils.h.
References FORCEINLINE, and GetCachedText().
SetCachedText() [1/2]
FORCEINLINE void FNodeTextCache::SetCachedText (FText const & InText, const UEdGraphNode * InOwningNode) const inline
Checks if the title is out of date.
Parameters
InText Text to cache
InOwningNode Node that owns this title
Definition at line 52 of file EdGraphNodeUtils.h.
References CacheRefreshID, FORCEINLINE, and UpdateCacheIternal().
SetCachedText() [2/2]
FORCEINLINE void FNodeTextCache::SetCachedText (FText const & InText, const UEdGraphSchema * InSchema) const inline
Checks if the title is out of date.
Parameters
InText Text to cache
InSchema Schema to use for checking if externally made out of date
Definition at line 69 of file EdGraphNodeUtils.h.
References CacheRefreshID, FORCEINLINE, and UpdateCacheIternal().
UpdateCacheIternal()
FORCEINLINE void FNodeTextCache::UpdateCacheIternal (FText const & InText) const inline private
Helper to lookup from the GConfig the correct ini setting for displaying node and pin titles localized and updates the cache accordingly.
Definition at line 108 of file EdGraphNodeUtils.h.
References FText::BuildSourceString(), CachedText, FORCEINLINE, FText::FromString(), GConfig, GEditorSettingsIni, and TEXT.
Referenced by SetCachedText(), and SetCachedText().
Field Documentation
CachedText
FText FNodeTextCache::CachedText mutable private
Mutable so that SetCachedText() can remain const (callable by the node's GetNodeTitle() method)
Definition at line 125 of file EdGraphNodeUtils.h.
Referenced by Clear(), GetCachedText(), IsOutOfDate(), IsOutOfDate(), and UpdateCacheIternal().
CacheRefreshID
int32 FNodeTextCache::CacheRefreshID mutable private
ID to check if the title should be considered dirty due to outside conditions that may require the title to refresh.
Definition at line 128 of file EdGraphNodeUtils.h.
Referenced by FNodeTextCache(), IsOutOfDate(), IsOutOfDate(), MarkDirty(), SetCachedText(), and SetCachedText().
The documentation for this struct was generated from the following file:
Runtime/Engine/Public/EdGraph/EdGraphNodeUtils.h