Unreal Engine 5.6 C++ API: TCharBase< CharType, Size > Struct Template Reference
TCharBase< CharType, Size > Struct Template Reference
#include "Char.h"
Static Public Member Functions
static bool IsLinebreak (CharType Char)
Static Public Attributes
static constexpr CharType CarriageReturn = (CharType)0xd
static constexpr CharType FormFeed = (CharType)0xc
static constexpr CharType LineFeed = (CharType)0xa
static constexpr CharType LineSeparator = (CharType)0x2028
static constexpr CharType NextLine = (CharType)0x85
static constexpr CharType ParagraphSeparator = (CharType)0x2029
static constexpr CharType VerticalTab = (CharType)0xb
Detailed Description
template<typename CharType, const unsigned int Size>
struct TCharBase< CharType, Size >
Definition at line 35 of file Char.h.
Member Function Documentation
IsLinebreak()
template<typename CharType, const unsigned int Size> bool TCharBase< CharType, Size >::IsLinebreak (CharType Char) inline static
Definition at line 45 of file Char.h.
References CarriageReturn, LineFeed, LineSeparator, NextLine, and ParagraphSeparator.
Field Documentation
CarriageReturn
template<typename CharType, const unsigned int Size> CharType TCharBase< CharType, Size >::CarriageReturn = (CharType)0xd static constexpr
Definition at line 40 of file Char.h.
Referenced by IsLinebreak().
FormFeed
template<typename CharType, const unsigned int Size> CharType TCharBase< CharType, Size >::FormFeed = (CharType)0xc static constexpr
Definition at line 39 of file Char.h.
LineFeed
template<typename CharType, const unsigned int Size> CharType TCharBase< CharType, Size >::LineFeed = (CharType)0xa static constexpr
Definition at line 37 of file Char.h.
Referenced by IsLinebreak().
LineSeparator
template<typename CharType, const unsigned int Size> CharType TCharBase< CharType, Size >::LineSeparator = (CharType)0x2028 static constexpr
Definition at line 42 of file Char.h.
Referenced by IsLinebreak().
NextLine
template<typename CharType, const unsigned int Size> CharType TCharBase< CharType, Size >::NextLine = (CharType)0x85 static constexpr
Definition at line 41 of file Char.h.
Referenced by IsLinebreak().
ParagraphSeparator
template<typename CharType, const unsigned int Size> CharType TCharBase< CharType, Size >::ParagraphSeparator = (CharType)0x2029 static constexpr
Definition at line 43 of file Char.h.
Referenced by IsLinebreak().
VerticalTab
template<typename CharType, const unsigned int Size> CharType TCharBase< CharType, Size >::VerticalTab = (CharType)0xb static constexpr
Definition at line 38 of file Char.h.
The documentation for this struct was generated from the following file:
Runtime/Core/Public/Misc/Char.h