Unreal Engine 5.6 C++ API: FResolvedProperty Struct Reference
FResolvedProperty Struct Reference
#include "DiffUtils.h"
Public Member Functions
FResolvedProperty ()
FResolvedProperty (const void *InObject, const FProperty *InProperty)
bool operator!= (const FResolvedProperty &RHS) const
bool operator== (const FResolvedProperty &RHS) const
Data Fields
const void * Object
const FProperty * Property
Detailed Description
Definition at line 37 of file DiffUtils.h.
Constructor & Destructor Documentation
FResolvedProperty() [1/2]
FResolvedProperty::FResolvedProperty () inline explicit
Definition at line 39 of file DiffUtils.h.
References Object, and Property.
Referenced by operator!=(), and operator==().
FResolvedProperty() [2/2]
FResolvedProperty::FResolvedProperty (const void * InObject, const FProperty * InProperty) inline
Definition at line 45 of file DiffUtils.h.
References Object, and Property.
Member Function Documentation
operator!=()
bool FResolvedProperty::operator!= (const FResolvedProperty & RHS) const inline
Definition at line 56 of file DiffUtils.h.
References FResolvedProperty().
operator==()
bool FResolvedProperty::operator== (const FResolvedProperty & RHS) const inline
Definition at line 51 of file DiffUtils.h.
References FResolvedProperty(), Object, and Property.
Field Documentation
Object
const void* FResolvedProperty::Object
Definition at line 58 of file DiffUtils.h.
Referenced by FResolvedProperty(), FResolvedProperty(), and operator==().
Property
const FProperty* FResolvedProperty::Property
Definition at line 59 of file DiffUtils.h.
Referenced by FResolvedProperty(), FResolvedProperty(), and operator==().
The documentation for this struct was generated from the following file:
Editor/UnrealEd/Public/DiffUtils.h