Unreal Engine 5.6 C++ API: TTraversalHistory< KDOP_IDX_TYPE > Struct Template Reference
TTraversalHistory< KDOP_IDX_TYPE > Struct Template Reference
Tracks information about a traversal through the kDOP tree.
#include "kDOP.h"
Public Types
enum { NodeHistoryLength = 1 }
Number of parent nodes to track information for.
Public Member Functions
TTraversalHistory ()
TTraversalHistory AddNode (KDOP_IDX_TYPE NewNodeIndex) const
KDOP_IDX_TYPE GetOldestNode () const
Data Fields
KDOP_IDX_TYPE Nodes [NodeHistoryLength]
Detailed Description
template<typename KDOP_IDX_TYPE>
struct TTraversalHistory< KDOP_IDX_TYPE >
Tracks information about a traversal through the kDOP tree.
Definition at line 74 of file kDOP.h.
Member Enumeration Documentation
anonymous enum
template<typename KDOP_IDX_TYPE> anonymous enum
Number of parent nodes to track information for.
This has been tweaked for optimal boolean shadow ray performance.
Enumerator
NodeHistoryLength
Definition at line 80 of file kDOP.h.
Constructor & Destructor Documentation
TTraversalHistory()
template<typename KDOP_IDX_TYPE> TTraversalHistory< KDOP_IDX_TYPE >::TTraversalHistory () inline
Definition at line 83 of file kDOP.h.
References NodeHistoryLength, and Nodes.
Referenced by AddNode().
Member Function Documentation
AddNode()
template<typename KDOP_IDX_TYPE> TTraversalHistory TTraversalHistory< KDOP_IDX_TYPE >::AddNode (KDOP_IDX_TYPE NewNodeIndex) const inline
Definition at line 92 of file kDOP.h.
References TTraversalHistory(), CopyAssignItems(), NodeHistoryLength, and Nodes.
Referenced by TkDOPNode< DataProviderType, KDOP_IDX_TYPE >::LineCheck(), TkDOPTree< DataProviderType, KDOP_IDX_TYPE >::LineCheck(), and TkDOPNode< DataProviderType, KDOP_IDX_TYPE >::LineCheckPreCalculated().
GetOldestNode()
template<typename KDOP_IDX_TYPE> KDOP_IDX_TYPE TTraversalHistory< KDOP_IDX_TYPE >::GetOldestNode () const inline
Definition at line 102 of file kDOP.h.
References NodeHistoryLength, and Nodes.
Referenced by TkDOPNode< DataProviderType, KDOP_IDX_TYPE >::LineCheckTriangles().
Field Documentation
Nodes
template<typename KDOP_IDX_TYPE> KDOP_IDX_TYPE TTraversalHistory< KDOP_IDX_TYPE >::Nodes[NodeHistoryLength]
Definition at line 81 of file kDOP.h.
Referenced by TTraversalHistory(), AddNode(), and GetOldestNode().
The documentation for this struct was generated from the following file:
Runtime/Engine/Public/kDOP.h