Unreal Engine 5.6 C++ API: FLocalPlayerContext Struct Reference
FLocalPlayerContext Struct Reference
A context object that binds to a LocalPlayer.
#include "LocalPlayer.h"
Public Member Functions
FLocalPlayerContext ()
FLocalPlayerContext (const class APlayerController *InPlayerController)
FLocalPlayerContext (const class ULocalPlayer *InLocalPlayer, UWorld *InWorld=nullptr)
UGameInstance * GetGameInstance () const
Returns the game instance.
class AGameStateBase * GetGameState () const
Getter for the Game State Base.
template<class T>
FORCEINLINE T * GetGameState (bool bCastChecked=false) const
Templated Getter for the Game State.
class AHUD * GetHUD () const
Getter for this player's HUD.
template<class T>
FORCEINLINE T * GetHUD (bool bCastChecked=false) const
Templated Getter for the HUD.
class ULocalPlayer * GetLocalPlayer () const
Returns the local player.
class APawn * GetPawn () const
Getter for the base pawn of this player.
template<class T>
FORCEINLINE T * GetPawn (bool bCastChecked=false) const
Templated getter for the player's pawn.
class APlayerController * GetPlayerController () const
Returns the player controller.
template<class T>
FORCEINLINE T * GetPlayerController (bool bCastChecked=false) const
Templated version of GetPlayerController()
class APlayerState * GetPlayerState () const
Getter for the Player State.
template<class T>
FORCEINLINE T * GetPlayerState (bool bCastChecked=false) const
Templated Getter for the Player State.
UWorld * GetWorld () const
Returns the world context.
bool IsFromLocalPlayer (const AActor *ActorToTest) const
This function tests if the given Actor is connected to the Local Player in any way.
bool IsInitialized () const
Is this context initialized.
bool IsValid () const
Is this context initialized and still valid?
Private Member Functions
void SetLocalPlayer (const class ULocalPlayer *InLocalPlayer)
void SetPlayerController (const class APlayerController *InPlayerController)
Private Attributes
TWeakObjectPtr< class ULocalPlayer > LocalPlayer
TWeakObjectPtr< UWorld > World
Detailed Description
A context object that binds to a LocalPlayer.
Useful for UI or other things that need to pass around player references
Definition at line 39 of file LocalPlayer.h.
Constructor & Destructor Documentation
FLocalPlayerContext() [1/3]
FLocalPlayerContext::FLocalPlayerContext ()
FLocalPlayerContext() [2/3]
FLocalPlayerContext::FLocalPlayerContext (const class ULocalPlayer * InLocalPlayer, UWorld * InWorld = nullptr)
FLocalPlayerContext() [3/3]
FLocalPlayerContext::FLocalPlayerContext (const class APlayerController * InPlayerController)
Member Function Documentation
GetGameInstance()
UGameInstance * FLocalPlayerContext::GetGameInstance () const
Returns the game instance.
GetGameState() [1/2]
class AGameStateBase * FLocalPlayerContext::GetGameState () const
Getter for the Game State Base.
Referenced by GetGameState().
GetGameState() [2/2]
template<class T> FORCEINLINE T * FLocalPlayerContext::GetGameState (bool bCastChecked = false) const inline
Templated Getter for the Game State.
Definition at line 86 of file LocalPlayer.h.
References Cast(), CastChecked(), FORCEINLINE, GetGameState(), and ECastCheckedType::NullAllowed.
GetHUD() [1/2]
class AHUD * FLocalPlayerContext::GetHUD () const
Getter for this player's HUD.
Referenced by GetHUD().
GetHUD() [2/2]
template<class T> FORCEINLINE T * FLocalPlayerContext::GetHUD (bool bCastChecked = false) const inline
Templated Getter for the HUD.
Definition at line 120 of file LocalPlayer.h.
References Cast(), CastChecked(), FORCEINLINE, GetHUD(), and ECastCheckedType::NullAllowed.
GetLocalPlayer()
class ULocalPlayer * FLocalPlayerContext::GetLocalPlayer () const
Returns the local player.
GetPawn() [1/2]
class APawn * FLocalPlayerContext::GetPawn () const
Getter for the base pawn of this player.
Referenced by GetPawn().
GetPawn() [2/2]
template<class T> FORCEINLINE T * FLocalPlayerContext::GetPawn (bool bCastChecked = false) const inline
Templated getter for the player's pawn.
Definition at line 137 of file LocalPlayer.h.
References Cast(), CastChecked(), FORCEINLINE, GetPawn(), and ECastCheckedType::NullAllowed.
GetPlayerController() [1/2]
class APlayerController * FLocalPlayerContext::GetPlayerController () const
Returns the player controller.
Referenced by GetPlayerController().
GetPlayerController() [2/2]
template<class T> FORCEINLINE T * FLocalPlayerContext::GetPlayerController (bool bCastChecked = false) const inline
Templated version of GetPlayerController()
Definition at line 69 of file LocalPlayer.h.
References Cast(), CastChecked(), FORCEINLINE, GetPlayerController(), and ECastCheckedType::NullAllowed.
GetPlayerState() [1/2]
class APlayerState * FLocalPlayerContext::GetPlayerState () const
Getter for the Player State.
Referenced by GetPlayerState().
GetPlayerState() [2/2]
template<class T> FORCEINLINE T * FLocalPlayerContext::GetPlayerState (bool bCastChecked = false) const inline
Templated Getter for the Player State.
Definition at line 103 of file LocalPlayer.h.
References Cast(), CastChecked(), FORCEINLINE, GetPlayerState(), and ECastCheckedType::NullAllowed.
GetWorld()
UWorld * FLocalPlayerContext::GetWorld () const
Returns the world context.
IsFromLocalPlayer()
bool FLocalPlayerContext::IsFromLocalPlayer (const AActor * ActorToTest) const
This function tests if the given Actor is connected to the Local Player in any way.
It tests against the APlayerController, APlayerState, and APawn.
IsInitialized()
bool FLocalPlayerContext::IsInitialized () const
Is this context initialized.
IsValid()
bool FLocalPlayerContext::IsValid () const
Is this context initialized and still valid?
SetLocalPlayer()
void FLocalPlayerContext::SetLocalPlayer (const class ULocalPlayer * InLocalPlayer) private
SetPlayerController()
void FLocalPlayerContext::SetPlayerController (const class APlayerController * InPlayerController) private
Field Documentation
LocalPlayer
TWeakObjectPtr<class ULocalPlayer> FLocalPlayerContext::LocalPlayer private
Definition at line 157 of file LocalPlayer.h.
World
TWeakObjectPtr<UWorld> FLocalPlayerContext::World private
Definition at line 159 of file LocalPlayer.h.
The documentation for this struct was generated from the following file:
Runtime/Engine/Classes/Engine/LocalPlayer.h