Unreal Engine 5.6 C++ API: FNiagaraDIChaosDestruction_InstanceDataToPassToRT Struct Reference
FNiagaraDIChaosDestruction_InstanceDataToPassToRT Struct Reference
#include "NiagaraDataInterfaceChaosDestruction.h"
Public Member Functions
FNiagaraDIChaosDestruction_InstanceDataToPassToRT ()
Data Fields
TArray< FVector3f > BoundsArray
TArray< FLinearColor > ColorArray
TArray< float > DensityArray
TArray< float > ExtentMaxArray
TArray< float > ExtentMinArray
TArray< float > FrictionArray
TArray< FVector3f > IncomingAccumulatedImpulseArray
TArray< FVector3f > IncomingAngularVelocity1Array
TArray< FVector3f > IncomingAngularVelocity2Array
TArray< FVector3f > IncomingLocationArray
TArray< float > IncomingMass1Array
TArray< float > IncomingMass2Array
TArray< FVector3f > IncomingNormalArray
TArray< float > IncomingTimeArray
TArray< FVector3f > IncomingVelocity1Array
TArray< FVector3f > IncomingVelocity2Array
int32 LastSpawnedPointID
TArray< FVector3f > PositionArray
TArray< float > RestitutionArray
TArray< int32 > SolverIDArray
float SolverTime
TArray< int32 > SurfaceTypeArray
TArray< FQuat4f > TransformRotationArray
TArray< FVector3f > TransformScaleArray
TArray< FVector3f > TransformTranslationArray
TArray< FVector3f > VelocityArray
TArray< float > VolumeArray
Detailed Description
Definition at line 220 of file NiagaraDataInterfaceChaosDestruction.h.
Constructor & Destructor Documentation
FNiagaraDIChaosDestruction_InstanceDataToPassToRT()
FNiagaraDIChaosDestruction_InstanceDataToPassToRT::FNiagaraDIChaosDestruction_InstanceDataToPassToRT () inline
Definition at line 253 of file NiagaraDataInterfaceChaosDestruction.h.
References FNiagaraDIChaosDestruction_InstanceDataToPassToRT(), and FMemory::Memzero().
Referenced by FNiagaraDIChaosDestruction_InstanceDataToPassToRT().
Field Documentation
BoundsArray
TArray<FVector3f> FNiagaraDIChaosDestruction_InstanceDataToPassToRT::BoundsArray
Definition at line 248 of file NiagaraDataInterfaceChaosDestruction.h.
ColorArray
TArray<FLinearColor> FNiagaraDIChaosDestruction_InstanceDataToPassToRT::ColorArray
Definition at line 232 of file NiagaraDataInterfaceChaosDestruction.h.
DensityArray
TArray<float> FNiagaraDIChaosDestruction_InstanceDataToPassToRT::DensityArray
Definition at line 228 of file NiagaraDataInterfaceChaosDestruction.h.
ExtentMaxArray
TArray<float> FNiagaraDIChaosDestruction_InstanceDataToPassToRT::ExtentMaxArray
Definition at line 225 of file NiagaraDataInterfaceChaosDestruction.h.
ExtentMinArray
TArray<float> FNiagaraDIChaosDestruction_InstanceDataToPassToRT::ExtentMinArray
Definition at line 224 of file NiagaraDataInterfaceChaosDestruction.h.
FrictionArray
TArray<float> FNiagaraDIChaosDestruction_InstanceDataToPassToRT::FrictionArray
Definition at line 229 of file NiagaraDataInterfaceChaosDestruction.h.
IncomingAccumulatedImpulseArray
TArray<FVector3f> FNiagaraDIChaosDestruction_InstanceDataToPassToRT::IncomingAccumulatedImpulseArray
Definition at line 235 of file NiagaraDataInterfaceChaosDestruction.h.
IncomingAngularVelocity1Array
TArray<FVector3f> FNiagaraDIChaosDestruction_InstanceDataToPassToRT::IncomingAngularVelocity1Array
Definition at line 239 of file NiagaraDataInterfaceChaosDestruction.h.
IncomingAngularVelocity2Array
TArray<FVector3f> FNiagaraDIChaosDestruction_InstanceDataToPassToRT::IncomingAngularVelocity2Array
Definition at line 240 of file NiagaraDataInterfaceChaosDestruction.h.
IncomingLocationArray
TArray<FVector3f> FNiagaraDIChaosDestruction_InstanceDataToPassToRT::IncomingLocationArray
Definition at line 234 of file NiagaraDataInterfaceChaosDestruction.h.
IncomingMass1Array
TArray<float> FNiagaraDIChaosDestruction_InstanceDataToPassToRT::IncomingMass1Array
Definition at line 241 of file NiagaraDataInterfaceChaosDestruction.h.
IncomingMass2Array
TArray<float> FNiagaraDIChaosDestruction_InstanceDataToPassToRT::IncomingMass2Array
Definition at line 242 of file NiagaraDataInterfaceChaosDestruction.h.
IncomingNormalArray
TArray<FVector3f> FNiagaraDIChaosDestruction_InstanceDataToPassToRT::IncomingNormalArray
Definition at line 236 of file NiagaraDataInterfaceChaosDestruction.h.
IncomingTimeArray
TArray<float> FNiagaraDIChaosDestruction_InstanceDataToPassToRT::IncomingTimeArray
Definition at line 243 of file NiagaraDataInterfaceChaosDestruction.h.
IncomingVelocity1Array
TArray<FVector3f> FNiagaraDIChaosDestruction_InstanceDataToPassToRT::IncomingVelocity1Array
Definition at line 237 of file NiagaraDataInterfaceChaosDestruction.h.
IncomingVelocity2Array
TArray<FVector3f> FNiagaraDIChaosDestruction_InstanceDataToPassToRT::IncomingVelocity2Array
Definition at line 238 of file NiagaraDataInterfaceChaosDestruction.h.
LastSpawnedPointID
int32 FNiagaraDIChaosDestruction_InstanceDataToPassToRT::LastSpawnedPointID
Definition at line 251 of file NiagaraDataInterfaceChaosDestruction.h.
PositionArray
TArray<FVector3f> FNiagaraDIChaosDestruction_InstanceDataToPassToRT::PositionArray
Definition at line 222 of file NiagaraDataInterfaceChaosDestruction.h.
RestitutionArray
TArray<float> FNiagaraDIChaosDestruction_InstanceDataToPassToRT::RestitutionArray
Definition at line 230 of file NiagaraDataInterfaceChaosDestruction.h.
SolverIDArray
TArray<int32> FNiagaraDIChaosDestruction_InstanceDataToPassToRT::SolverIDArray
Definition at line 227 of file NiagaraDataInterfaceChaosDestruction.h.
SolverTime
float FNiagaraDIChaosDestruction_InstanceDataToPassToRT::SolverTime
Definition at line 250 of file NiagaraDataInterfaceChaosDestruction.h.
SurfaceTypeArray
TArray<int32> FNiagaraDIChaosDestruction_InstanceDataToPassToRT::SurfaceTypeArray
Definition at line 231 of file NiagaraDataInterfaceChaosDestruction.h.
TransformRotationArray
TArray<FQuat4f> FNiagaraDIChaosDestruction_InstanceDataToPassToRT::TransformRotationArray
Definition at line 246 of file NiagaraDataInterfaceChaosDestruction.h.
TransformScaleArray
TArray<FVector3f> FNiagaraDIChaosDestruction_InstanceDataToPassToRT::TransformScaleArray
Definition at line 247 of file NiagaraDataInterfaceChaosDestruction.h.
TransformTranslationArray
TArray<FVector3f> FNiagaraDIChaosDestruction_InstanceDataToPassToRT::TransformTranslationArray
Definition at line 245 of file NiagaraDataInterfaceChaosDestruction.h.
VelocityArray
TArray<FVector3f> FNiagaraDIChaosDestruction_InstanceDataToPassToRT::VelocityArray
Definition at line 223 of file NiagaraDataInterfaceChaosDestruction.h.
VolumeArray
TArray<float> FNiagaraDIChaosDestruction_InstanceDataToPassToRT::VolumeArray
Definition at line 226 of file NiagaraDataInterfaceChaosDestruction.h.
The documentation for this struct was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Experimental/ChaosNiagara/Source/ChaosNiagara/Classes/NiagaraDataInterfaceChaosDestruction.h