Unreal Engine 5.6 C++ API: FNavLocalGridData Struct Reference
FNavLocalGridData Struct Reference
Local navigation grid - simple 2D grid used for navigation.
#include "NavLocalGridData.h"
Public Types
typedef int32 FNodeRef
Public Types inherited from TSimpleCellGrid< uint8, MAX_uint8 >
typedef uint8 FCellType
Public Member Functions
FNavLocalGridData ()
AIMODULE_API FNavLocalGridData (const FVector &Center, const FVector2D &Extent2D)
AIMODULE_API FNavLocalGridData (const FVector &Center, float Extent2D)
AIMODULE_API FNavLocalGridData (const TArray< FNavLocalGridData > &SourceGrids)
AIMODULE_API bool FindPath (const FIntVector &StartCoords, const FIntVector &EndCoords, TArray< FIntVector > &PathCoords) const
create path points from StartCoords to EndCoord, returns false when failed
AIMODULE_API void FindPathForMovingAgent (const FNavigationPath &SourcePath, const FVector &EntryLocation, int32 EntrySegmentStart, TArray< FVector > &PathPointsInside, int32 &NextSegmentStart) const
creates path points from navigation path going through grid
AIMODULE_API int32 GetCellIndexFromGlobalCoords2D (const FIntVector &WorldCoords) const
convert global world coords to cell index, return -1 if outside
FIntVector GetGlobalCoords (int32 CellIdx) const
convert cell index to global world coords with origin in (0,0,0)
const int32 GetGridId () const
get unique Id of grid
AIMODULE_API FNodeRef GetNeighbour (const FNodeRef NodeRef, const int32 NeiIndex) const
int32 GetNeighbourCount (FNodeRef NodeRef) const
FVector GetProjectedCellCenter (int32 CellIdx) const
convert cell index to world location using projected heights
FVector GetProjectedCellCenter (int32 LocationX, int32 LocationY) const
convert cell coords on grid to world location using projected heights
bool HasObstacleUnsafe (int32 LocationX, int32 LocationY) const
check if there's an obstacle at cell coords
bool IsValidRef (FNodeRef NodeRef) const
AIMODULE_API void MarkBoxObstacle (const FVector &Center, const FVector &Extent, const FQuat &Quat=FQuat::Identity)
mark box (AABB or rotated) shape as obstacle
AIMODULE_API void MarkCapsuleObstacle (const FVector &Center, float Radius, float HalfHeight)
mark capsule shape as obstacle
AIMODULE_API void MarkPointObstacle (const FVector &Center)
mark single cell as obstacle
AIMODULE_API void ProjectCells (const ANavigationData &NavData)
project cells on navigation data and marks failed ones as obstacles
AIMODULE_API void SetHeight (float ExtentZ)
set height of bounds, if not set: ProjectCells will use height of default query box
Public Member Functions inherited from TSimpleCellGrid< uint8, MAX_uint8 >
TSimpleCellGrid ()
void AllocateMemory ()
void CleanUp ()
void FreeMemory ()
FORCEINLINE uint32 GetAllocatedSize () const
FCellType & GetCellAtCoordsUnsafe (int32 LocationX, int32 LocationY)
FORCEINLINE FCellType & GetCellAtIndexUnsafe (int32 CellIndex)
const FCellType & GetCellAtWorldLocation (const FVector &WorldLocation) const
const FCellType & GetCellAtWorldLocationUnsafe (const FVector &WorldLocation) const
FIntVector GetCellCoords (const FVector &WorldLocation) const
Convert world location to (X,Y) coords on grid, result is clamped to grid.
FORCEINLINE FIntVector GetCellCoordsUnsafe (const FVector &WorldLocation) const
Convert world location to (X,Y) coords on grid, result can be outside grid.
FORCEINLINE int32 GetCellCoordX (int32 CellIndex) const
Convert cell index to coord X on grid, result can be invalid.
FORCEINLINE int32 GetCellCoordY (int32 CellIndex) const
Convert cell index to coord Y on grid, result can be invalid.
FORCEINLINE int32 GetCellIndex (int32 LocationX, int32 LocationY) const
Convert (X,Y) coords on grid to cell index, returns -1 for position outside grid.
int32 GetCellIndexUnsafe (const FVector &WorldLocation) const
Convert world location to cell index, result can be invalid.
FORCEINLINE FIntRect GetCellRectangleFromBox (const FBox &WorldBox) const
Compute a rectangle of cells overlapping the given WorldBox.
FORCEINLINE int32 GetCellsCount () const
FORCEINLINE FIntRect GetGridRectangle () const
Return an IntRect that includes all the cells of the grid.
FORCEINLINE FBox GetWorldCellBox (int32 CellIndex) const
Return the bounding box of a cell.
FORCEINLINE FBox2D GetWorldCellBox2D (int32 CellIndex) const
Return the 2D bounding box of a cell.
FORCEINLINE FVector GetWorldCellCenter (int32 CellIndex) const
FORCEINLINE FBox GetWorldCellRectangleBox (const FIntRect &CellRect) const
Return the world bounding box of all cells included in the given rectangle.
bool Init (const float InCellSize, const FBox &Bounds)
Initialize the grid from a bounding box.
FORCEINLINE bool IsValid () const
FORCEINLINE bool IsValidCoord (int32 LocationX, int32 LocationY) const
FORCEINLINE bool IsValidIndex (const int32 CellIndex) const
FORCEINLINE int32 Num () const
FORCEINLINE FCellType & operator[] (int32 CellIndex)
void Serialize (FArchive &Ar)
void SetVerticalInterval (const FFloatInterval &VerticalInterval)
Change the vertical position of the grid by providing an interval.
void UpdateWorldBounds ()
void Zero ()
Protected Member Functions
AIMODULE_API bool IsLineObstructed (const FIntVector &StartCoords, const FIntVector &EndCoords) const
check if line trace between local coords on grid hits any obstacles, doesn't validate coords!
AIMODULE_API void PostProcessPath (const FIntVector &StartCoords, const FIntVector &EndCoords, const TArray< int32 > &PathIndices, TArray< FIntVector > &PathCoords) const
convert PathIndices into pruned PathCoords
AIMODULE_API void SetGridId (int32 NewId)
set unique Id of grid
Protected Attributes
TArray< FVector::FReal > CellZ
double LastAccessTime
Protected Attributes inherited from TSimpleCellGrid< uint8, MAX_uint8 >
TArray< FCellType > Cells
Private Attributes
int32 GridId
FIntVector OriginWorldCoord
Friends
class UNavLocalGridManager
Additional Inherited Members
Data Fields inherited from TSimpleCellGrid< uint8, MAX_uint8 >
FVector BoundsSize
float GridCellSize
FGridSize2D GridSize
FVector Origin
FBox WorldBounds
Detailed Description
Local navigation grid - simple 2D grid used for navigation.
Cell can be either free or marked as obstacle, connected with 8 neighbors (no walls in between)
When used as source for UNavLocalGridManager, each obstacle should define its own grid data. Corresponding category in gameplay debugger is hidden by default, please adjust project configs to change that.
TODO: helpers for marking different basic shapes TODO: serialization (with maps?) TODO: FNavigationPath support?
Definition at line 23 of file NavLocalGridData.h.
Member Typedef Documentation
FNodeRef
typedef int32 FNavLocalGridData::FNodeRef
Definition at line 93 of file NavLocalGridData.h.
Constructor & Destructor Documentation
FNavLocalGridData() [1/4]
FNavLocalGridData::FNavLocalGridData () inline
Definition at line 25 of file NavLocalGridData.h.
References GridId.
Referenced by FCombinedNavGridData::FCombinedNavGridData().
FNavLocalGridData() [2/4]
AIMODULE_API FNavLocalGridData::FNavLocalGridData (const FVector & Center, float Extent2D)
References FVector.
FNavLocalGridData() [3/4]
AIMODULE_API FNavLocalGridData::FNavLocalGridData (const FVector & Center, const FVector2D & Extent2D)
References FVector.
FNavLocalGridData() [4/4]
AIMODULE_API FNavLocalGridData::FNavLocalGridData (const TArray< FNavLocalGridData > & SourceGrids)
Member Function Documentation
FindPath()
AIMODULE_API bool FNavLocalGridData::FindPath (const FIntVector & StartCoords, const FIntVector & EndCoords, TArray< FIntVector > & PathCoords) const
create path points from StartCoords to EndCoord, returns false when failed
FindPathForMovingAgent()
AIMODULE_API void FNavLocalGridData::FindPathForMovingAgent (const FNavigationPath & SourcePath, const FVector & EntryLocation, int32 EntrySegmentStart, TArray< FVector > & PathPointsInside, int32 & NextSegmentStart) const
creates path points from navigation path going through grid
Parameters
SourcePath - [in] full navigation path
EntryLocation - [in] location of agent
EntrySegmentStart - [in] current move segment on path
PathPointsInside - [out] points inside grid
NextSegmentStart - [out] next move segment on path after leaving grid or -1 if path ends inside
References FVector.
GetCellIndexFromGlobalCoords2D()
AIMODULE_API int32 FNavLocalGridData::GetCellIndexFromGlobalCoords2D (const FIntVector & WorldCoords) const
convert global world coords to cell index, return -1 if outside
GetGlobalCoords()
FIntVector FNavLocalGridData::GetGlobalCoords (int32 CellIdx) const inline
convert cell index to global world coords with origin in (0,0,0)
Definition at line 55 of file NavLocalGridData.h.
References TSimpleCellGrid< uint8, MAX_uint8 >::GetCellCoordX(), TSimpleCellGrid< uint8, MAX_uint8 >::GetCellCoordY(), and OriginWorldCoord.
GetGridId()
const int32 FNavLocalGridData::GetGridId () const inline
get unique Id of grid
Definition at line 43 of file NavLocalGridData.h.
References GridId.
GetNeighbour()
AIMODULE_API FNodeRef FNavLocalGridData::GetNeighbour (const FNodeRef NodeRef, const int32 NeiIndex) const
GetNeighbourCount()
int32 FNavLocalGridData::GetNeighbourCount (FNodeRef NodeRef) const inline
Definition at line 95 of file NavLocalGridData.h.
GetProjectedCellCenter() [1/2]
FVector FNavLocalGridData::GetProjectedCellCenter (int32 CellIdx) const inline
convert cell index to world location using projected heights
Definition at line 64 of file NavLocalGridData.h.
References FVector, TSimpleCellGrid< uint8, MAX_uint8 >::GetCellCoordX(), TSimpleCellGrid< uint8, MAX_uint8 >::GetCellCoordY(), and GetProjectedCellCenter().
Referenced by GetProjectedCellCenter().
GetProjectedCellCenter() [2/2]
FVector FNavLocalGridData::GetProjectedCellCenter (int32 LocationX, int32 LocationY) const inline
convert cell coords on grid to world location using projected heights
Definition at line 70 of file NavLocalGridData.h.
References CellZ, FVector, TSimpleCellGrid< uint8, MAX_uint8 >::GetCellIndexUnsafe(), TSimpleCellGrid< uint8, MAX_uint8 >::GetWorldCellCenter(), UE::Math::TVector< T >::X, and UE::Math::TVector< T >::Y.
HasObstacleUnsafe()
bool FNavLocalGridData::HasObstacleUnsafe (int32 LocationX, int32 LocationY) const inline
check if there's an obstacle at cell coords
Definition at line 49 of file NavLocalGridData.h.
References TSimpleCellGrid< uint8, MAX_uint8 >::GetCellAtIndexUnsafe(), and TSimpleCellGrid< uint8, MAX_uint8 >::GetCellIndexUnsafe().
IsLineObstructed()
AIMODULE_API bool FNavLocalGridData::IsLineObstructed (const FIntVector & StartCoords, const FIntVector & EndCoords) const protected
check if line trace between local coords on grid hits any obstacles, doesn't validate coords!
IsValidRef()
bool FNavLocalGridData::IsValidRef (FNodeRef NodeRef) const inline
Definition at line 96 of file NavLocalGridData.h.
References TSimpleCellGrid< uint8, MAX_uint8 >::IsValidIndex().
MarkBoxObstacle()
AIMODULE_API void FNavLocalGridData::MarkBoxObstacle (const FVector & Center, const FVector & Extent, const FQuat & Quat = FQuat::Identity)
mark box (AABB or rotated) shape as obstacle
References FVector, UE::Math::TQuat< double >::Identity, and Quat.
MarkCapsuleObstacle()
AIMODULE_API void FNavLocalGridData::MarkCapsuleObstacle (const FVector & Center, float Radius, float HalfHeight)
mark capsule shape as obstacle
References FVector.
MarkPointObstacle()
AIMODULE_API void FNavLocalGridData::MarkPointObstacle (const FVector & Center)
mark single cell as obstacle
References FVector.
PostProcessPath()
AIMODULE_API void FNavLocalGridData::PostProcessPath (const FIntVector & StartCoords, const FIntVector & EndCoords, const TArray< int32 > & PathIndices, TArray< FIntVector > & PathCoords) const protected
convert PathIndices into pruned PathCoords
ProjectCells()
AIMODULE_API void FNavLocalGridData::ProjectCells (const ANavigationData & NavData)
project cells on navigation data and marks failed ones as obstacles
SetGridId()
AIMODULE_API void FNavLocalGridData::SetGridId (int32 NewId) protected
set unique Id of grid
SetHeight()
AIMODULE_API void FNavLocalGridData::SetHeight (float ExtentZ)
set height of bounds, if not set: ProjectCells will use height of default query box
Friends And Related Symbol Documentation
UNavLocalGridManager
friend class UNavLocalGridManager friend
Definition at line 101 of file NavLocalGridData.h.
References UNavLocalGridManager.
Referenced by UNavLocalGridManager.
Field Documentation
CellZ
TArray<FVector::FReal> FNavLocalGridData::CellZ protected
Definition at line 102 of file NavLocalGridData.h.
Referenced by GetProjectedCellCenter().
GridId
int32 FNavLocalGridData::GridId private
Definition at line 115 of file NavLocalGridData.h.
Referenced by FNavLocalGridData(), and GetGridId().
LastAccessTime
double FNavLocalGridData::LastAccessTime protected
Definition at line 103 of file NavLocalGridData.h.
OriginWorldCoord
FIntVector FNavLocalGridData::OriginWorldCoord private
Definition at line 116 of file NavLocalGridData.h.
Referenced by GetGlobalCoords().
The documentation for this struct was generated from the following file:
Runtime/AIModule/Classes/Navigation/NavLocalGridData.h