Unreal Engine 5.6 C++ API: FApplePlatformTime Struct Reference
FApplePlatformTime Struct Reference
Please see following UDN post about using rdtsc on processors that support result being invariant across cores.
#include "ApplePlatformTime.h"
Static Public Member Functions
static FORCEINLINE uint32 Cycles ()
static FORCEINLINE uint64 Cycles64 ()
static FCPUTime GetCPUTime ()
static double InitTiming ()
static FORCEINLINE double Seconds ()
Static Public Member Functions inherited from FGenericPlatformTime
static void AutoUpdateGameThreadCPUTime (double UpdateInterval)
Registers automatic updates of Game Thread CPU utilization.
static FCPUTime GetCPUTime ()
static double GetLastIntervalCPUTimeInSeconds ()
static double GetLastIntervalThreadCPUTimeInSeconds ()
Gets the per-thread CPU processing time (kernel + user) from the last update.
static double GetSecondsPerCycle ()
Each platform implements these two functions, which return the current time in platform-specific cpu cycles.
static double GetSecondsPerCycle64 ()
Returns seconds per cycle, to pair with Cycles64().
static FCPUTime GetThreadCPUTime ()
Gets current threads CPU Utilization.
static FString PrettyTime (double Seconds)
Returns a pretty-string for a time given in seconds.
static uint64 SecondsToCycles64 (double Seconds)
Convert seconds to cycles, can be added to Cycles64 to set a high resolution timeout.
static TCHAR * StrDate (TCHAR *Dest, SIZE_T DestSize)
Get the system date.
static TCHAR * StrTime (TCHAR *Dest, SIZE_T DestSize)
Get the system time.
static const TCHAR * StrTimestamp ()
Returns a timestamp string built from the current date and time.
static float ToMilliseconds (const uint32 Cycles)
Converts cycles to milliseconds.
static double ToMilliseconds64 (const uint64 Cycles)
Converts 64 bit cycles to milliseconds.
static float ToSeconds (const uint32 Cycles)
Converts cycles to seconds.
static double ToSeconds64 (const uint64 Cycles)
Converts 64 bit cycles to seconds.
static bool UpdateCPUTime (float DeltaTime)
Updates CPU utilization, called through a delegate from the Core ticker.
static bool UpdateThreadCPUTime (float=0.0)
Updates current thread CPU utilization, calling is user defined per-thread (unused float parameter, is for FTicker compatibility).
Additional Inherited Members
Static Protected Attributes inherited from FGenericPlatformTime
static double LastIntervalCPUTimeInSeconds
static double SecondsPerCycle
static double SecondsPerCycle64
Detailed Description
Please see following UDN post about using rdtsc on processors that support result being invariant across cores.
https://udn.epicgames.com/lists/showpost.php?id=46794&list=unprog3 Apple platform implementation of the Time OS functions
Definition at line 28 of file ApplePlatformTime.h.
Member Function Documentation
Cycles()
FORCEINLINE uint32 FApplePlatformTime::Cycles () inline static
Definition at line 39 of file ApplePlatformTime.h.
References Cycles(), and FORCEINLINE.
Referenced by Cycles(), Cycles64(), and Seconds().
Cycles64()
FORCEINLINE uint64 FApplePlatformTime::Cycles64 () inline static
Definition at line 45 of file ApplePlatformTime.h.
References Cycles(), and FORCEINLINE.
GetCPUTime()
FCPUTime FApplePlatformTime::GetCPUTime () static
InitTiming()
double FApplePlatformTime::InitTiming () static
Seconds()
FORCEINLINE double FApplePlatformTime::Seconds () inline static
Definition at line 32 of file ApplePlatformTime.h.
References Cycles(), FORCEINLINE, and FGenericPlatformTime::GetSecondsPerCycle().
The documentation for this struct was generated from the following file:
Runtime/Core/Public/Apple/ApplePlatformTime.h