Unreal Engine 5.6 C++ API: TStateTreeInstanceDataStructRef< T > Struct Template Reference
TStateTreeInstanceDataStructRef< T > Struct Template Reference
Stores indexed reference to a instance data struct.
#include "StateTreeInstanceData.h"
Public Member Functions
PRAGMA_DISABLE_DEPRECATION_WARNINGS TStateTreeInstanceDataStructRef (const TStateTreeInstanceDataStructRef &Other)=default
TStateTreeInstanceDataStructRef (FStateTreeInstanceData &InInstanceData, const FStateTreeExecutionFrame &CurrentFrame, const FStateTreeDataHandle InDataHandle)
TStateTreeInstanceDataStructRef (TStateTreeInstanceDataStructRef &&Other)=default
T * GetPtr () const
PRAGMA_ENABLE_DEPRECATION_WARNINGS bool IsValid () const
TStateTreeInstanceDataStructRef & operator= (TStateTreeInstanceDataStructRef &&Other)=default
TStateTreeInstanceDataStructRef & operator= (TStateTreeInstanceDataStructRef const &Other)=default
Protected Member Functions
FStructView GetDataView (FStateTreeInstanceStorage &Storage, const FStateTreeExecutionFrame &CurrentFrame, const FStateTreeDataHandle Handle) const
bool IsHandleSourceValid (FStateTreeInstanceStorage &Storage, const FStateTreeExecutionFrame &CurrentFrame, const FStateTreeDataHandle Handle) const
Protected Attributes
FStateTreeDataHandle DataHandle = FStateTreeDataHandle::Invalid
UE::StateTree::FActiveFrameID FrameID
TWeakPtr< FStateTreeInstanceStorage > WeakStorage = nullptr
Detailed Description
template<typename T>
struct TStateTreeInstanceDataStructRef< T >
Stores indexed reference to a instance data struct.
The instance data structs may be relocated when the instance data composition changed. For that reason you cannot store pointers to the instance data. This is often needed for example when dealing with delegate lambda's. This helper struct stores data to be able to find the instance data in the instance data array. That way we can access the instance data even of the array changes, and the instance data moves in memory.
Note that the reference is valid only during the lifetime of a task (between a call EnterState() and ExitState()).
You generally do not use this directly, but via FStateTreeExecutionContext.
EStateTreeRunStatus FTestTask::EnterState(FStateTreeExecutionContext& Context, const FStateTreeTransitionResult& Transition) const { FInstanceDataType& InstanceData = Context.GetInstanceData(*this);
Context.GetWorld()->GetTimerManager().SetTimer(InstanceData.TimerHandle, [InstanceDataRef = Context.GetInstanceDataStructRef(<em>this)]() { if (FInstanceDataType InstanceData = InstanceDataRef.GetPtr()) { ... } }, Delay, true);
return EStateTreeRunStatus::Running; }
Definition at line 627 of file StateTreeInstanceData.h.
Constructor & Destructor Documentation
TStateTreeInstanceDataStructRef() [1/3]
template<typename T> TStateTreeInstanceDataStructRef< T >::TStateTreeInstanceDataStructRef (FStateTreeInstanceData & InInstanceData, const FStateTreeExecutionFrame & CurrentFrame, const FStateTreeDataHandle InDataHandle) inline
Definition at line 629 of file StateTreeInstanceData.h.
References checkf, DataHandle, FrameID, TEXT, and WeakStorage.
Referenced by TStateTreeInstanceDataStructRef(), TStateTreeInstanceDataStructRef(), operator=(), and operator=().
TStateTreeInstanceDataStructRef() [2/3]
template<typename T> PRAGMA_DISABLE_DEPRECATION_WARNINGS TStateTreeInstanceDataStructRef< T >::TStateTreeInstanceDataStructRef (const TStateTreeInstanceDataStructRef< T > & Other) default
References TStateTreeInstanceDataStructRef(), and Other.
TStateTreeInstanceDataStructRef() [3/3]
template<typename T> TStateTreeInstanceDataStructRef< T >::TStateTreeInstanceDataStructRef (TStateTreeInstanceDataStructRef< T > && Other) default
References TStateTreeInstanceDataStructRef(), and Other.
Member Function Documentation
GetDataView()
template<typename T> FStructView TStateTreeInstanceDataStructRef< T >::GetDataView (FStateTreeInstanceStorage & Storage, const FStateTreeExecutionFrame & CurrentFrame, const FStateTreeDataHandle Handle) const inline protected
Definition at line 695 of file StateTreeInstanceData.h.
References checkf, DataHandle, Handle, and TEXT.
Referenced by GetPtr().
GetPtr()
template<typename T> T * TStateTreeInstanceDataStructRef< T >::GetPtr () const inline
Definition at line 651 of file StateTreeInstanceData.h.
References check, DataHandle, FrameID, TBaseStructureBase< T, bHasStaticStruct >::Get(), TSharedPtr< ObjectType, InMode >::Get(), GetDataView(), IsHandleSourceValid(), Struct, and WeakStorage.
IsHandleSourceValid()
template<typename T> bool TStateTreeInstanceDataStructRef< T >::IsHandleSourceValid (FStateTreeInstanceStorage & Storage, const FStateTreeExecutionFrame & CurrentFrame, const FStateTreeDataHandle Handle) const inline protected
Definition at line 709 of file StateTreeInstanceData.h.
References checkf, Handle, and TEXT.
Referenced by GetPtr().
IsValid()
template<typename T> PRAGMA_ENABLE_DEPRECATION_WARNINGS bool TStateTreeInstanceDataStructRef< T >::IsValid () const inline
Definition at line 646 of file StateTreeInstanceData.h.
References DataHandle, and FrameID.
operator=() [1/2]
template<typename T> TStateTreeInstanceDataStructRef & TStateTreeInstanceDataStructRef< T >::operator= (TStateTreeInstanceDataStructRef< T > && Other) default
References TStateTreeInstanceDataStructRef(), Other, and PRAGMA_ENABLE_DEPRECATION_WARNINGS.
operator=() [2/2]
template<typename T> TStateTreeInstanceDataStructRef & TStateTreeInstanceDataStructRef< T >::operator= (TStateTreeInstanceDataStructRef< T > const & Other) default
References TStateTreeInstanceDataStructRef(), and Other.
Field Documentation
DataHandle
template<typename T> FStateTreeDataHandle TStateTreeInstanceDataStructRef< T >::DataHandle = FStateTreeDataHandle::Invalid protected
Definition at line 729 of file StateTreeInstanceData.h.
Referenced by TStateTreeInstanceDataStructRef(), GetDataView(), GetPtr(), and IsValid().
FrameID
template<typename T> UE::StateTree::FActiveFrameID TStateTreeInstanceDataStructRef< T >::FrameID protected
Definition at line 728 of file StateTreeInstanceData.h.
Referenced by TStateTreeInstanceDataStructRef(), GetPtr(), and IsValid().
WeakStorage
template<typename T> TWeakPtr<FStateTreeInstanceStorage> TStateTreeInstanceDataStructRef< T >::WeakStorage = nullptr protected
Definition at line 727 of file StateTreeInstanceData.h.
Referenced by TStateTreeInstanceDataStructRef(), and GetPtr().
The documentation for this struct was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/StateTree/Source/StateTreeModule/Public/StateTreeInstanceData.h