Unreal Engine 5.6 C++ API: UE::Math::TDualQuat< T > Struct Template Reference
UE::Math::TDualQuat< T > Struct Template Reference
#include "DualQuat.h"
Public Types
using FReal = T
Public Member Functions
template<typename FArg UE_REQUIRES>
TDualQuat (const TDualQuat< FArg > &From)
TDualQuat (const TQuat< T > &InR, const TQuat< T > &InD)
TDualQuat (const TTransform< T > &Transform)
TTransform< T > AsFTransform (TVector< T > Scale=TVector< T >(1.0f, 1.0f, 1.0f)) const
Convert dual quat to transform.
TDualQuat< T > Normalized () const
Return normalized dual quat.
TDualQuat< T > operator* (const T S) const
Scale dual quat.
TDualQuat< T > operator* (const TDualQuat< T > &B) const
Dual quat product.
TDualQuat< T > operator+ (const TDualQuat< T > &B) const
Dual quat addition.
Data Fields
TQuat< T > D
half trans or dual part
TQuat< T > R
rotation or real part
Detailed Description
template<typename T>
struct UE::Math::TDualQuat< T >
Definition at line 18 of file DualQuat.h.
Member Typedef Documentation
FReal
template<typename T> using UE::Math::TDualQuat< T >::FReal = T
Definition at line 21 of file DualQuat.h.
Constructor & Destructor Documentation
TDualQuat() [1/3]
template<typename T> UE::Math::TDualQuat< T >::TDualQuat (const TQuat< T > & InR, const TQuat< T > & InD) inline nodiscard
Definition at line 29 of file DualQuat.h.
References D, and R.
Referenced by TDualQuat(), TDualQuat(), Normalized(), operator*(), operator*(), and operator+().
TDualQuat() [2/3]
template<typename T> UE::Math::TDualQuat< T >::TDualQuat (const TTransform< T > & Transform) inline nodiscard
Definition at line 34 of file DualQuat.h.
References TDualQuat(), Transform, UE::Math::TVector< T >::X, UE::Math::TVector< T >::Y, and UE::Math::TVector< T >::Z.
TDualQuat() [3/3]
template<typename T> template<typename FArg UE_REQUIRES> UE::Math::TDualQuat< T >::TDualQuat (const TDualQuat< FArg > & From) inline explicit nodiscard
Definition at line 42 of file DualQuat.h.
References TDualQuat(), D, and R.
Member Function Documentation
AsFTransform()
template<typename T> TTransform< T > UE::Math::TDualQuat< T >::AsFTransform (TVector< T > Scale = TVector<T>(1.0f, 1.0f, 1.0f)) const inline nodiscard
Convert dual quat to transform.
Definition at line 73 of file DualQuat.h.
References D, R, Scale, UE::Math::TQuat< T >::X, UE::Math::TQuat< T >::Y, and UE::Math::TQuat< T >::Z.
Normalized()
template<typename T> TDualQuat< T > UE::Math::TDualQuat< T >::Normalized () const inline nodiscard
Return normalized dual quat.
Definition at line 66 of file DualQuat.h.
References TDualQuat(), D, and R.
operator*() [1/2]
template<typename T> TDualQuat< T > UE::Math::TDualQuat< T >::operator* (const T S) const inline nodiscard
Scale dual quat.
Definition at line 60 of file DualQuat.h.
References TDualQuat(), D, and R.
operator*() [2/2]
template<typename T> TDualQuat< T > UE::Math::TDualQuat< T >::operator* (const TDualQuat< T > & B) const inline nodiscard
Dual quat product.
Definition at line 54 of file DualQuat.h.
References TDualQuat(), B, D, and R.
operator+()
template<typename T> TDualQuat< T > UE::Math::TDualQuat< T >::operator+ (const TDualQuat< T > & B) const inline nodiscard
Dual quat addition.
Definition at line 48 of file DualQuat.h.
References TDualQuat(), B, D, and R.
Field Documentation
D
template<typename T> TQuat<T> UE::Math::TDualQuat< T >::D
half trans or dual part
Definition at line 26 of file DualQuat.h.
Referenced by TDualQuat(), TDualQuat(), AsFTransform(), Normalized(), operator*(), operator*(), and operator+().
R
template<typename T> TQuat<T> UE::Math::TDualQuat< T >::R
rotation or real part
Definition at line 24 of file DualQuat.h.
Referenced by TDualQuat(), TDualQuat(), AsFTransform(), Normalized(), operator*(), operator*(), and operator+().
The documentation for this struct was generated from the following file:
Runtime/Core/Public/Math/DualQuat.h