Unreal Engine 5.6 C++ API: UE::Core::Private::TReverseIterationAdapter< RangeType > Struct Template Reference
UE::Core::Private::TReverseIterationAdapter< RangeType > Struct Template Reference
#include "ReverseIterate.h"
Public Member Functions
TReverseIterationAdapter (const TReverseIterationAdapter &)=delete
constexpr TReverseIterationAdapter (RangeType &InRange UE_LIFETIMEBOUND)
TReverseIterationAdapter (TReverseIterationAdapter &&)=delete
~TReverseIterationAdapter ()=default
FORCEINLINE constexpr auto begin () const UE_LIFETIMEBOUND
FORCEINLINE constexpr auto end () const UE_LIFETIMEBOUND
TReverseIterationAdapter & operator= (const TReverseIterationAdapter &)=delete
TReverseIterationAdapter & operator= (TReverseIterationAdapter &&)=delete
Private Attributes
RangeType & Range
Detailed Description
template<typename RangeType>
struct UE::Core::Private::TReverseIterationAdapter< RangeType >
Definition at line 54 of file ReverseIterate.h.
Constructor & Destructor Documentation
TReverseIterationAdapter() [1/3]
template<typename RangeType> UE::Core::Private::TReverseIterationAdapter< RangeType >::TReverseIterationAdapter (RangeType &InRange UE_LIFETIMEBOUND) inline explicit constexpr
Definition at line 56 of file ReverseIterate.h.
References Range, and UE_LIFETIMEBOUND.
Referenced by TReverseIterationAdapter(), TReverseIterationAdapter(), operator=(), and operator=().
TReverseIterationAdapter() [2/3]
template<typename RangeType> UE::Core::Private::TReverseIterationAdapter< RangeType >::TReverseIterationAdapter (TReverseIterationAdapter< RangeType > &&) delete
References TReverseIterationAdapter().
TReverseIterationAdapter() [3/3]
template<typename RangeType> UE::Core::Private::TReverseIterationAdapter< RangeType >::TReverseIterationAdapter (const TReverseIterationAdapter< RangeType > &) delete
References TReverseIterationAdapter().
~TReverseIterationAdapter()
template<typename RangeType> UE::Core::Private::TReverseIterationAdapter< RangeType >::~TReverseIterationAdapter () default
Member Function Documentation
begin()
template<typename RangeType> FORCEINLINE constexpr auto UE::Core::Private::TReverseIterationAdapter< RangeType >::begin () const inline constexpr
Definition at line 67 of file ReverseIterate.h.
References FORCEINLINE, Range, and UE_LIFETIMEBOUND.
end()
template<typename RangeType> FORCEINLINE constexpr auto UE::Core::Private::TReverseIterationAdapter< RangeType >::end () const inline constexpr
Definition at line 73 of file ReverseIterate.h.
References FORCEINLINE, Range, and UE_LIFETIMEBOUND.
operator=() [1/2]
template<typename RangeType> TReverseIterationAdapter & UE::Core::Private::TReverseIterationAdapter< RangeType >::operator= (const TReverseIterationAdapter< RangeType > &) delete
References TReverseIterationAdapter().
operator=() [2/2]
template<typename RangeType> TReverseIterationAdapter & UE::Core::Private::TReverseIterationAdapter< RangeType >::operator= (TReverseIterationAdapter< RangeType > &&) delete
References TReverseIterationAdapter().
Field Documentation
Range
template<typename RangeType> RangeType& UE::Core::Private::TReverseIterationAdapter< RangeType >::Range private
Definition at line 80 of file ReverseIterate.h.
Referenced by TReverseIterationAdapter(), begin(), and end().
The documentation for this struct was generated from the following file:
Runtime/Core/Public/Misc/ReverseIterate.h