Unreal Engine 5.6 C++ API: Metasound::TVariable< DataType > Struct Template Reference
Metasound::TVariable< DataType > Struct Template Reference
A MetaSound Variable contains a data reference's prior and current value.
#include "MetasoundVariable.h"
Public Types
using FReadReference = TDataReadReference<DataType>
using FWriteReference = TDataWriteReference<DataType>
Public Member Functions
TVariable ()=delete
TVariable (const FLiteral &InInitialValue, MetasoundVariablePrivate::FConstructWithLiteral)
Create a delayed variable.
TVariable (const TVariable &)=default
TVariable (TVariable &&)=default
void BindDataReference (FOutputVertexInterfaceData &InVertexData, const FVertexName &InVertexName)
void BindDelayedDataReference (FOutputVertexInterfaceData &InVertexData, const FVertexName &InVertexName)
void CopyReferencedData ()
FReadReference GetDataReference () const
Get the current data reference.
FReadReference GetDelayedDataReference () const
Get the delayed data reference.
void InitDataReference (const FOperatorSettings &InOperatorSettings)
void InitDelayedDataReference (const FOperatorSettings &InOperatorSettings)
bool RequiresDelayedDataCopy () const
void Reset (const FOperatorSettings &InOperatorSettings)
void SetDataReference (FReadReference InDataReference)
Private Attributes
TOptional< FReadReference > DataReference
TOptional< FWriteReference > DelayedDataReference
FLiteral Literal
Detailed Description
template<typename DataType>
struct Metasound::TVariable< DataType >
A MetaSound Variable contains a data reference's prior and current value.
Template Parameters
DataType - Underlying data type of data reference.
Definition at line 26 of file MetasoundVariable.h.
Member Typedef Documentation
FReadReference
template<typename DataType> using Metasound::TVariable< DataType >::FReadReference = TDataReadReference<DataType>
Definition at line 29 of file MetasoundVariable.h.
FWriteReference
template<typename DataType> using Metasound::TVariable< DataType >::FWriteReference = TDataWriteReference<DataType>
Definition at line 28 of file MetasoundVariable.h.
Constructor & Destructor Documentation
TVariable() [1/4]
template<typename DataType> Metasound::TVariable< DataType >::TVariable () delete
Referenced by TVariable(), and TVariable().
TVariable() [2/4]
template<typename DataType> Metasound::TVariable< DataType >::TVariable (TVariable< DataType > &&) default
References TVariable().
TVariable() [3/4]
template<typename DataType> Metasound::TVariable< DataType >::TVariable (const TVariable< DataType > &) default
References TVariable().
TVariable() [4/4]
template<typename DataType> Metasound::TVariable< DataType >::TVariable (const FLiteral & InInitialValue, MetasoundVariablePrivate::FConstructWithLiteral) inline
Create a delayed variable.
Parameters
InInitialValue - A literal used to construct the initial value.
Definition at line 40 of file MetasoundVariable.h.
References Literal.
Member Function Documentation
BindDataReference()
template<typename DataType> void Metasound::TVariable< DataType >::BindDataReference (FOutputVertexInterfaceData & InVertexData, const FVertexName & InVertexName) inline
Definition at line 77 of file MetasoundVariable.h.
References Metasound::FOutputVertexInterfaceData::BindReadVertex(), checkf, DataReference, and TEXT.
BindDelayedDataReference()
template<typename DataType> void Metasound::TVariable< DataType >::BindDelayedDataReference (FOutputVertexInterfaceData & InVertexData, const FVertexName & InVertexName) inline
Definition at line 83 of file MetasoundVariable.h.
References Metasound::FOutputVertexInterfaceData::BindReadVertex(), checkf, DelayedDataReference, and TEXT.
CopyReferencedData()
template<typename DataType> void Metasound::TVariable< DataType >::CopyReferencedData () inline
Definition at line 50 of file MetasoundVariable.h.
References check, and RequiresDelayedDataCopy().
GetDataReference()
template<typename DataType> FReadReference Metasound::TVariable< DataType >::GetDataReference () const inline
Get the current data reference.
Definition at line 71 of file MetasoundVariable.h.
References checkf, DataReference, and TEXT.
GetDelayedDataReference()
template<typename DataType> FReadReference Metasound::TVariable< DataType >::GetDelayedDataReference () const inline
Get the delayed data reference.
Definition at line 98 of file MetasoundVariable.h.
References checkf, DelayedDataReference, and TEXT.
Referenced by InitDataReference().
InitDataReference()
template<typename DataType> void Metasound::TVariable< DataType >::InitDataReference (const FOperatorSettings & InOperatorSettings) inline
Definition at line 61 of file MetasoundVariable.h.
References DataReference, GetDelayedDataReference(), and InitDelayedDataReference().
InitDelayedDataReference()
template<typename DataType> void Metasound::TVariable< DataType >::InitDelayedDataReference (const FOperatorSettings & InOperatorSettings) inline
Definition at line 89 of file MetasoundVariable.h.
References Metasound::TDataLiteralFactory< DataType, TDataWriteReference< DataType > >::CreateExplicitArgs(), DelayedDataReference, and Literal.
Referenced by InitDataReference().
RequiresDelayedDataCopy()
template<typename DataType> bool Metasound::TVariable< DataType >::RequiresDelayedDataCopy () const inline
Definition at line 45 of file MetasoundVariable.h.
References DataReference, and DelayedDataReference.
Referenced by CopyReferencedData().
Reset()
template<typename DataType> void Metasound::TVariable< DataType >::Reset (const FOperatorSettings & InOperatorSettings) inline
Definition at line 104 of file MetasoundVariable.h.
References Metasound::TDataLiteralFactory< DataType, DataFactoryPrivate::TDataTypeCreator< DataType > >::CreateExplicitArgs(), DelayedDataReference, and Literal.
SetDataReference()
template<typename DataType> void Metasound::TVariable< DataType >::SetDataReference (FReadReference InDataReference) inline
Definition at line 56 of file MetasoundVariable.h.
References DataReference.
Field Documentation
DataReference
template<typename DataType> TOptional<FReadReference> Metasound::TVariable< DataType >::DataReference private
Definition at line 117 of file MetasoundVariable.h.
Referenced by BindDataReference(), GetDataReference(), InitDataReference(), RequiresDelayedDataCopy(), and SetDataReference().
DelayedDataReference
template<typename DataType> TOptional<FWriteReference> Metasound::TVariable< DataType >::DelayedDataReference private
Definition at line 116 of file MetasoundVariable.h.
Referenced by BindDelayedDataReference(), GetDelayedDataReference(), InitDelayedDataReference(), RequiresDelayedDataCopy(), and Reset().
Literal
template<typename DataType> FLiteral Metasound::TVariable< DataType >::Literal private
Definition at line 115 of file MetasoundVariable.h.
Referenced by TVariable(), InitDelayedDataReference(), and Reset().
The documentation for this struct was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/Metasound/Source/MetasoundGraphCore/Public/MetasoundVariable.h