Unreal Engine 5.6 C++ API: UE::Sequencer::FTimeDomainOverride Struct Reference
UE::Sequencer::FTimeDomainOverride Struct Reference
RAII struct that temporarily overrides time operations within Sequencer to operate in warped or unwarped space.
#include "SequencerTimeDomainOverride.h"
Public Member Functions
FTimeDomainOverride (const FTimeDomainOverride &Other)=delete
FTimeDomainOverride (ETimeDomain *Ptr, ETimeDomain NewValue)
FTimeDomainOverride (FTimeDomainOverride &&Other)
~FTimeDomainOverride ()
FTimeDomainOverride & operator= (const FTimeDomainOverride &Other)=delete
Private Attributes
ETimeDomain OriginalValue
ETimeDomain * ValuePtr
Detailed Description
RAII struct that temporarily overrides time operations within Sequencer to operate in warped or unwarped space.
By default all SetLocalTime behavior is in warped space, since this comprises the majority of tracks. This class is very similar to TGuardValue<ETimeDomain>, except that it is moveable.
Definition at line 22 of file SequencerTimeDomainOverride.h.
Constructor & Destructor Documentation
FTimeDomainOverride() [1/3]
UE::Sequencer::FTimeDomainOverride::FTimeDomainOverride (ETimeDomain * Ptr, ETimeDomain NewValue) inline
Definition at line 26 of file SequencerTimeDomainOverride.h.
References OriginalValue, and ValuePtr.
Referenced by FTimeDomainOverride(), FTimeDomainOverride(), and operator=().
FTimeDomainOverride() [2/3]
UE::Sequencer::FTimeDomainOverride::FTimeDomainOverride (const FTimeDomainOverride & Other) delete
References FTimeDomainOverride(), and Other.
FTimeDomainOverride() [3/3]
UE::Sequencer::FTimeDomainOverride::FTimeDomainOverride (FTimeDomainOverride && Other) inline
Definition at line 39 of file SequencerTimeDomainOverride.h.
References FTimeDomainOverride(), OriginalValue, Other, and ValuePtr.
~FTimeDomainOverride()
UE::Sequencer::FTimeDomainOverride::~FTimeDomainOverride () inline
Definition at line 46 of file SequencerTimeDomainOverride.h.
References OriginalValue, and ValuePtr.
Member Function Documentation
operator=()
FTimeDomainOverride & UE::Sequencer::FTimeDomainOverride::operator= (const FTimeDomainOverride & Other) delete
References FTimeDomainOverride(), and Other.
Field Documentation
OriginalValue
ETimeDomain UE::Sequencer::FTimeDomainOverride::OriginalValue private
Definition at line 57 of file SequencerTimeDomainOverride.h.
Referenced by FTimeDomainOverride(), FTimeDomainOverride(), and ~FTimeDomainOverride().
ValuePtr
ETimeDomain* UE::Sequencer::FTimeDomainOverride::ValuePtr private
Definition at line 56 of file SequencerTimeDomainOverride.h.
Referenced by FTimeDomainOverride(), FTimeDomainOverride(), and ~FTimeDomainOverride().
The documentation for this struct was generated from the following file:
Editor/Sequencer/Public/SequencerTimeDomainOverride.h