Unreal Engine 5.6 C++ API: FTimerData Struct Reference
FTimerData Struct Reference
#include "TimerManager.h"
Public Member Functions
FTimerData ()
FTimerData (const FTimerData &)=delete
FTimerData (FTimerData &&)=default
FTimerData & operator= (const FTimerData &)=delete
FTimerData & operator= (FTimerData &&)=default
Data Fields
uint8 bLoop: 1
If true, this timer will loop indefinitely.
uint8 bMaxOncePerFrame: 1
If true for a looping timer, it will run a maximum of once per frame when it expires.
uint8 bRequiresDelegate: 1
If true, this timer was created with a delegate to call (which means if the delegate becomes invalid, we should invalidate the timer too).
double ExpireTime
Time (on the FTimerManager's clock) that this timer should expire and fire its delegate.
FTimerHandle Handle
Handle representing this timer.
ELevelCollectionType LevelCollection
The level collection that was active when this timer was created.
float Rate
Time between set and fire, or repeat frequency if looping.
ETimerStatus Status
Timer Status.
FTimerUnifiedDelegate TimerDelegate
Holds the delegate to call.
const void * TimerIndicesByObjectKey = nullptr
This is the key to the TimerIndicesByObject map - this is kept so that we can look up even if the referenced object is expired.
Detailed Description
Definition at line 72 of file TimerManager.h.
Constructor & Destructor Documentation
FTimerData() [1/3]
FTimerData::FTimerData ()
Referenced by FTimerData(), FTimerData(), operator=(), and operator=().
FTimerData() [2/3]
FTimerData::FTimerData (FTimerData &&) default
References FTimerData().
FTimerData() [3/3]
FTimerData::FTimerData (const FTimerData &) delete
References FTimerData().
Member Function Documentation
operator=() [1/2]
FTimerData & FTimerData::operator= (const FTimerData &) delete
References FTimerData().
operator=() [2/2]
FTimerData & FTimerData::operator= (FTimerData &&) default
References FTimerData().
Field Documentation
bLoop
uint8 FTimerData::bLoop
If true, this timer will loop indefinitely.
Otherwise, it will be destroyed when it expires.
Definition at line 75 of file TimerManager.h.
bMaxOncePerFrame
uint8 FTimerData::bMaxOncePerFrame
If true for a looping timer, it will run a maximum of once per frame when it expires.
Otherwise, it will run as many times as can fit in the current frame's delta time (rounding down).
Definition at line 80 of file TimerManager.h.
bRequiresDelegate
uint8 FTimerData::bRequiresDelegate
If true, this timer was created with a delegate to call (which means if the delegate becomes invalid, we should invalidate the timer too).
Definition at line 83 of file TimerManager.h.
ExpireTime
double FTimerData::ExpireTime
Time (on the FTimerManager's clock) that this timer should expire and fire its delegate.
Note when a timer is paused, we re-base ExpireTime to be relative to 0 instead of the running clock, meaning ExpireTime contains the remaining time until fire.
Definition at line 99 of file TimerManager.h.
Handle
FTimerHandle FTimerData::Handle
Handle representing this timer.
Definition at line 105 of file TimerManager.h.
LevelCollection
ELevelCollectionType FTimerData::LevelCollection
The level collection that was active when this timer was created.
Used to set the correct context before executing the timer's delegate.
Definition at line 89 of file TimerManager.h.
Rate
float FTimerData::Rate
Time between set and fire, or repeat frequency if looping.
Definition at line 92 of file TimerManager.h.
Status
ETimerStatus FTimerData::Status
Timer Status.
Definition at line 86 of file TimerManager.h.
Referenced by FTimerManager::IsTimerActive(), FTimerManager::IsTimerPaused(), and FTimerManager::IsTimerPending().
TimerDelegate
FTimerUnifiedDelegate FTimerData::TimerDelegate
Holds the delegate to call.
Definition at line 102 of file TimerManager.h.
TimerIndicesByObjectKey
const void* FTimerData::TimerIndicesByObjectKey = nullptr
This is the key to the TimerIndicesByObject map - this is kept so that we can look up even if the referenced object is expired.
Definition at line 108 of file TimerManager.h.
The documentation for this struct was generated from the following file:
Runtime/Engine/Public/TimerManager.h