Unreal Engine 5.6 C++ API: TSequencerChannelInterfaceCommon< ChannelType > Struct Template Reference
TSequencerChannelInterfaceCommon< ChannelType > Struct Template Reference
Templated channel interface that calls overloaded functions matching the necessary channel types.
#include "SequencerChannelInterface.h"
Public Member Functions
virtual bool CanCreateKeyEditor_Raw (const FMovieSceneChannel *InChannel) const override
Check whether an editor on the sequencer node tree can be created for the specified channel.
virtual void CopyKeys_Raw (FMovieSceneChannel *InChannel, const UMovieSceneSection *Section, FName KeyAreaName, FMovieSceneClipboardBuilder &ClipboardBuilder, TArrayView< const FKeyHandle > KeyMask) const override
Copy all the keys specified in KeyMask to the specified clipboard.
virtual TSharedPtr< UE::Sequencer::FChannelModel > CreateChannelModel_Raw (const FMovieSceneChannelHandle &InChannelHandle, const UE::Sequencer::FSectionModel &InSection, FName InChannelName) const override
Create a new channel model for this type of channel.
virtual TSharedPtr< UE::Sequencer::STrackAreaLaneView > CreateChannelView_Raw (const FMovieSceneChannelHandle &InChannelHandle, TWeakPtr< UE::Sequencer::FChannelModel > InWeakModel, const UE::Sequencer::FCreateTrackLaneViewParams &Parameters) const override
Create a new channel view for this type of channel.
virtual TUniquePtr< FCurveModel > CreateCurveEditorModel_Raw (const FMovieSceneChannelHandle &InChannel, const UE::Sequencer::FCreateCurveEditorModelParams &Params) const override
Create a new model for this channel that can be used on the curve editor interface.
virtual TSharedRef< SWidget > CreateKeyEditor_Raw (const FMovieSceneChannelHandle &Channel, const UE::Sequencer::FCreateKeyEditorParams &Params) const override
Create an editor on the sequencer node tree.
virtual void DeleteKeys_Raw (FMovieSceneChannel *InChannel, TArrayView< const FKeyHandle > InHandles, FFrameNumber InTime) const override
Delete the specified keys.
virtual int32 DrawExtra_Raw (FMovieSceneChannel *InChannel, const UMovieSceneSection *InOwner, const FSequencerChannelPaintArgs &PaintArgs, int32 LayerId) const override
Draw additional content in addition to keys for a particular channel.
virtual void DrawKeys_Raw (FMovieSceneChannel *InChannel, TArrayView< const FKeyHandle > InKeyHandles, const UMovieSceneSection *InOwner, TArrayView< FKeyDrawParams > OutKeyDrawParams) const override
Gather information on how to draw the specified keys.
virtual void ExtendKeyMenu_Raw (FMenuBuilder &MenuBuilder, TSharedPtr< FExtender > MenuExtender, TArrayView< const FExtendKeyMenuParams > ChannelsAndHandles, TWeakPtr< ISequencer > InSequencer) const override
Extend the key context menu.
virtual void ExtendSectionMenu_Raw (FMenuBuilder &MenuBuilder, TSharedPtr< FExtender > InMenuExtender, TArrayView< const FMovieSceneChannelHandle > InChannels, const TArray< TWeakObjectPtr< UMovieSceneSection > > &InWeakSections, TWeakPtr< ISequencer > InWeakSequencer) const override
Extend the section context menu.
virtual TSharedPtr< ISidebarChannelExtension > ExtendSidebarMenu_Raw (FMenuBuilder &MenuBuilder, TSharedPtr< FExtender > InMenuExtender, TArrayView< const FMovieSceneChannelHandle > InChannels, const TArray< TWeakObjectPtr< UMovieSceneSection > > &InWeakSections, TWeakPtr< ISequencer > InWeakSequencer) const override
Extend the section sidebar menu.
virtual TSharedPtr< FStructOnScope > GetKeyStruct_Raw (FMovieSceneChannelHandle InChannel, FKeyHandle KeyHandle) const override
Get an editable key struct for the specified key.
virtual void PasteKeys_Raw (FMovieSceneChannel *InChannel, UMovieSceneSection *Section, const FMovieSceneClipboardKeyTrack &KeyTrack, const FMovieSceneClipboardEnvironment &SrcEnvironment, const FSequencerPasteEnvironment &DstEnvironment, TArray< FKeyHandle > &OutPastedKeys) const override
Paste the specified key track into the specified channel.
virtual bool ShouldShowCurve_Raw (const FMovieSceneChannel *Channel, UMovieSceneSection *InSection) const override
Whether this channel should draw a curve on its editor UI.
virtual bool SupportsCurveEditorModels_Raw (const FMovieSceneChannelHandle &InChannel) const override
Whether this channel supports curve models.
Public Member Functions inherited from ISequencerChannelInterface
virtual ~ISequencerChannelInterface ()
virtual FKeyHandle AddOrUpdateKey_Raw (FMovieSceneChannel *Channel, UMovieSceneSection *SectionToKey, const void *ExtendedEditorData, FFrameNumber InTime, ISequencer &InSequencer, const FGuid &ObjectBindingID, FTrackInstancePropertyBindings *PropertyBindings) const =0
Add (or update) a key to the specified channel using it's current value at that time, or some external value specified by the extended editor data.
Detailed Description
template<typename ChannelType>
struct TSequencerChannelInterfaceCommon< ChannelType >
Templated channel interface that calls overloaded functions matching the necessary channel types.
Designed this way to allow for specific customization of key-channel behavior without having to reimplement swathes of boilerplate. This base interface implements common functions that do not require extended editor data.
Behavior can be overridden for any channel type by declaring an overloaded function for the relevant channel type in the same namespace as the channel. For instance, to implement how to retrieve key times from a channel, implement the following function:
void GetKeyTimes(FMyChannelType* InChannel, TArrayView<const FKeyHandle> InHandles, TArrayView<FFrameNumber> OutKeyTimes);
Definition at line 60 of file SequencerChannelInterface.h.
Member Function Documentation
CanCreateKeyEditor_Raw()
template<typename ChannelType> virtual bool TSequencerChannelInterfaceCommon< ChannelType >::CanCreateKeyEditor_Raw (const FMovieSceneChannel * InChannel) const inline override virtual
Check whether an editor on the sequencer node tree can be created for the specified channel.
Parameters
Channel The channel to check
Returns
true if a key editor should be constructed, false otherwise
Implements ISequencerChannelInterface.
Definition at line 125 of file SequencerChannelInterface.h.
References CanCreateKeyEditor().
CopyKeys_Raw()
template<typename ChannelType> virtual void TSequencerChannelInterfaceCommon< ChannelType >::CopyKeys_Raw (FMovieSceneChannel * InChannel, const UMovieSceneSection * Section, FName KeyAreaName, FMovieSceneClipboardBuilder & ClipboardBuilder, TArrayView< const FKeyHandle > KeyMask) const inline override virtual
Copy all the keys specified in KeyMask to the specified clipboard.
Parameters
Channel The channel to copy from
Section The section that owns the channel
KeyAreaName The name of the key area
ClipboardBuilder The structure responsible for building clipboard information for each key
KeyMask A specific set of keys to copy
Implements ISequencerChannelInterface.
Definition at line 84 of file SequencerChannelInterface.h.
References Sequencer::CopyKeys().
CreateChannelModel_Raw()
template<typename ChannelType> virtual TSharedPtr< UE::Sequencer::FChannelModel > TSequencerChannelInterfaceCommon< ChannelType >::CreateChannelModel_Raw (const FMovieSceneChannelHandle & InChannelHandle, const UE::Sequencer::FSectionModel & InSection, FName InChannelName) const inline override virtual
Create a new channel model for this type of channel.
Parameters
InChannelHandle The channel handle to create a model for
InSectionModel The section that owns this channel model
InChannelName The identifying name of this channel
Returns
(Optional) A new model to be added to a curve editor
Implements ISequencerChannelInterface.
Definition at line 294 of file SequencerChannelInterface.h.
References FMovieSceneChannelHandle::Cast(), and CreateChannelModel().
CreateChannelView_Raw()
template<typename ChannelType> virtual TSharedPtr< UE::Sequencer::STrackAreaLaneView > TSequencerChannelInterfaceCommon< ChannelType >::CreateChannelView_Raw (const FMovieSceneChannelHandle & InChannelHandle, TWeakPtr< UE::Sequencer::FChannelModel > InWeakModel, const UE::Sequencer::FCreateTrackLaneViewParams & Parameters) const inline override virtual
Create a new channel view for this type of channel.
Parameters
InChannelHandle The channel handle to create a model for
InWeakModel The model that is creating the view. Should not be Pinned persistently.
Parameters View construction parameters
Returns
(Optional) A new model to be added to a curve editor
Implements ISequencerChannelInterface.
Definition at line 308 of file SequencerChannelInterface.h.
References FMovieSceneChannelHandle::Cast(), and Sequencer::CreateChannelView().
CreateCurveEditorModel_Raw()
template<typename ChannelType> virtual TUniquePtr< FCurveModel > TSequencerChannelInterfaceCommon< ChannelType >::CreateCurveEditorModel_Raw (const FMovieSceneChannelHandle & InChannel, const UE::Sequencer::FCreateCurveEditorModelParams & Params) const inline override virtual
Create a new model for this channel that can be used on the curve editor interface.
Returns
(Optional) A new model to be added to a curve editor
Implements ISequencerChannelInterface.
Definition at line 268 of file SequencerChannelInterface.h.
References FMovieSceneChannelHandle::Cast(), CreateCurveEditorModel(), Params, and TModels_V.
CreateKeyEditor_Raw()
template<typename ChannelType> virtual TSharedRef< SWidget > TSequencerChannelInterfaceCommon< ChannelType >::CreateKeyEditor_Raw (const FMovieSceneChannelHandle & Channel, const UE::Sequencer::FCreateKeyEditorParams & Params) const inline override virtual
Create an editor on the sequencer node tree.
Parameters
Channel The channel to check
Params Creation parameters containing all the necessary structures for creating the key editor
Returns
The editor widget to display on the node tree
Implements ISequencerChannelInterface.
Definition at line 321 of file SequencerChannelInterface.h.
References FMovieSceneChannelHandle::Cast(), CreateKeyEditor(), Params, and TModels_V.
DeleteKeys_Raw()
template<typename ChannelType> virtual void TSequencerChannelInterfaceCommon< ChannelType >::DeleteKeys_Raw (FMovieSceneChannel * InChannel, TArrayView< const FKeyHandle > InHandles, FFrameNumber InTime) const inline override virtual
Delete the specified keys.
If all keys are removed, the current value at that time will be set as the default value for the channel
Parameters
Channel The channel to remove the keys from
InHandles The key handles to delete
InTime The time at which to evaluate for the default value if there are no keys remaining
Implements ISequencerChannelInterface.
Definition at line 69 of file SequencerChannelInterface.h.
References Sequencer::DeleteKeys(), and InTime.
DrawExtra_Raw()
template<typename ChannelType> virtual int32 TSequencerChannelInterfaceCommon< ChannelType >::DrawExtra_Raw (FMovieSceneChannel * InChannel, const UMovieSceneSection * InOwner, const FSequencerChannelPaintArgs & PaintArgs, int32 LayerId) const inline override virtual
Draw additional content in addition to keys for a particular channel.
Parameters
InChannel The channel to draw extra display information for
InOwner The owning movie scene section for this channel
PaintArgs Paint arguments containing the draw element list, time-to-pixel converter and other structures
LayerId The slate layer to paint onto
Returns
The new slate layer ID for subsequent elements to paint onto
Implements ISequencerChannelInterface.
Definition at line 234 of file SequencerChannelInterface.h.
References Sequencer::DrawExtra().
DrawKeys_Raw()
template<typename ChannelType> virtual void TSequencerChannelInterfaceCommon< ChannelType >::DrawKeys_Raw (FMovieSceneChannel * InChannel, TArrayView< const FKeyHandle > InKeyHandles, const UMovieSceneSection * InOwner, TArrayView< FKeyDrawParams > OutKeyDrawParams) const inline override virtual
Gather information on how to draw the specified keys.
Parameters
Channel The channel to query
InKeyHandles Array of handles to duplicate
InOwner The section that owns the channel
OutKeyDrawParams Pre-sized array to receive key draw parameters. Invalid key handles will not be assigned to this array. Must match size of InKeyHandles.
Implements ISequencerChannelInterface.
Definition at line 217 of file SequencerChannelInterface.h.
References check, DrawKeys(), and TArrayView< InElementType, InSizeType >::Num().
ExtendKeyMenu_Raw()
template<typename ChannelType> virtual void TSequencerChannelInterfaceCommon< ChannelType >::ExtendKeyMenu_Raw (FMenuBuilder & MenuBuilder, TSharedPtr< FExtender > MenuExtender, TArrayView< const FExtendKeyMenuParams > ChannelsAndHandles, TWeakPtr< ISequencer > InSequencer) const inline override virtual
Extend the key context menu.
Parameters
MenuBuilder The menu builder used to create this context menu
Channels Array of channels and handles that are being shown in the context menu
InSequencer The currently active sequencer
Implements ISequencerChannelInterface.
Definition at line 138 of file SequencerChannelInterface.h.
References TArray< InElementType, InAllocatorType >::Add(), TExtendKeyMenuParams< ChannelType >::Channel, ExtendKeyMenu(), TExtendKeyMenuParams< ChannelType >::Handles, MoveTemp(), TExtendKeyMenuParams< ChannelType >::Section, and TExtendKeyMenuParams< ChannelType >::WeakOwner.
ExtendSectionMenu_Raw()
template<typename ChannelType> virtual void TSequencerChannelInterfaceCommon< ChannelType >::ExtendSectionMenu_Raw (FMenuBuilder & MenuBuilder, TSharedPtr< FExtender > InMenuExtender, TArrayView< const FMovieSceneChannelHandle > InChannels, const TArray< TWeakObjectPtr< UMovieSceneSection > > & InWeakSections, TWeakPtr< ISequencer > InWeakSequencer) const inline override virtual
Extend the section context menu.
Parameters
MenuBuilder The menu builder used to create this context menu
InMenuExtender The menu extender to use
InChannels Array of type specific channels that exist in the selected sections
InWeakSections Array of sections being shown on the context menu
InWeakSequencer The currently active sequencer
Implements ISequencerChannelInterface.
Definition at line 166 of file SequencerChannelInterface.h.
References TArray< InElementType, InAllocatorType >::Add(), ExtendSectionMenu(), and MoveTemp().
ExtendSidebarMenu_Raw()
template<typename ChannelType> virtual TSharedPtr< ISidebarChannelExtension > TSequencerChannelInterfaceCommon< ChannelType >::ExtendSidebarMenu_Raw (FMenuBuilder & MenuBuilder, TSharedPtr< FExtender > InMenuExtender, TArrayView< const FMovieSceneChannelHandle > InChannels, const TArray< TWeakObjectPtr< UMovieSceneSection > > & InWeakSections, TWeakPtr< ISequencer > InWeakSequencer) const inline override virtual
Extend the section sidebar menu.
Parameters
MenuBuilder The menu builder used to create this context menu
InMenuExtender The menu extender to use
InChannels Array of type specific channels that exist in the selected sections
InWeakSections Array of sections being shown on the context menu
InWeakSequencer The currently active sequencer
Implements ISequencerChannelInterface.
Definition at line 192 of file SequencerChannelInterface.h.
References TArray< InElementType, InAllocatorType >::Add(), ExtendSidebarMenu(), and MoveTemp().
GetKeyStruct_Raw()
template<typename ChannelType> virtual TSharedPtr< FStructOnScope > TSequencerChannelInterfaceCommon< ChannelType >::GetKeyStruct_Raw (FMovieSceneChannelHandle InChannel, FKeyHandle KeyHandle) const inline override virtual
Get an editable key struct for the specified key.
Parameters
Channel The channel on which the key resides
KeyHandle Handle of the key to get
Returns
A shared editable key struct
Implements ISequencerChannelInterface.
Definition at line 113 of file SequencerChannelInterface.h.
References FMovieSceneChannelHandle::Cast(), and Sequencer::GetKeyStruct().
PasteKeys_Raw()
template<typename ChannelType> virtual void TSequencerChannelInterfaceCommon< ChannelType >::PasteKeys_Raw (FMovieSceneChannel * InChannel, UMovieSceneSection * Section, const FMovieSceneClipboardKeyTrack & KeyTrack, const FMovieSceneClipboardEnvironment & SrcEnvironment, const FSequencerPasteEnvironment & DstEnvironment, TArray< FKeyHandle > & OutPastedKeys) const inline override virtual
Paste the specified key track into the specified channel.
Parameters
Channel The channel to copy from
Section The section that owns the channel
KeyTrack The source clipboard data to paste
SrcEnvironment The environment the source data was copied from
DstEnvironment The environment we're pasting into
OutPastedKeys Array to receive key handles for any pasted keys
Implements ISequencerChannelInterface.
Definition at line 100 of file SequencerChannelInterface.h.
References Sequencer::PasteKeys().
ShouldShowCurve_Raw()
template<typename ChannelType> virtual bool TSequencerChannelInterfaceCommon< ChannelType >::ShouldShowCurve_Raw (const FMovieSceneChannel * Channel, UMovieSceneSection * InSection) const inline override virtual
Whether this channel should draw a curve on its editor UI.
Parameters
Channel The channel to query
InSection The section that owns the channel
Returns
true to show the curve on the UI, false otherwise
Implements ISequencerChannelInterface.
Definition at line 257 of file SequencerChannelInterface.h.
References ShouldShowCurve().
SupportsCurveEditorModels_Raw()
template<typename ChannelType> virtual bool TSequencerChannelInterfaceCommon< ChannelType >::SupportsCurveEditorModels_Raw (const FMovieSceneChannelHandle & InChannel) const inline override virtual
Whether this channel supports curve models.
Implements ISequencerChannelInterface.
Definition at line 244 of file SequencerChannelInterface.h.
References FMovieSceneChannelHandle::Cast(), and SupportsCurveEditorModels().
The documentation for this struct was generated from the following file:
Editor/Sequencer/Public/SequencerChannelInterface.h