Unreal Engine 5.6 C++ API: FMovieSceneTrackEvaluationData Struct Reference
FMovieSceneTrackEvaluationData Struct Reference
#include "MovieSceneTrackEvaluationField.h"
Public Member Functions
FMovieSceneTrackEvaluationData ()
FMovieSceneTrackEvaluationData & SetFlags (ESectionEvaluationFlags InFlags)
FMovieSceneTrackEvaluationData & Sort (int16 InSortOrder)
Static Public Member Functions
static MOVIESCENE_API FMovieSceneTrackEvaluationData FromSection (UMovieSceneSection *InSection)
static MOVIESCENE_API FMovieSceneTrackEvaluationData FromTrack (UMovieSceneTrack *InTrack)
Data Fields
ESectionEvaluationFlags Flags
FFrameNumber ForcedTime
TWeakObjectPtr< UMovieSceneSection > Section
int16 SortOrder
TWeakObjectPtr< UMovieSceneTrack > Track
Detailed Description
Definition at line 59 of file MovieSceneTrackEvaluationField.h.
Constructor & Destructor Documentation
FMovieSceneTrackEvaluationData()
FMovieSceneTrackEvaluationData::FMovieSceneTrackEvaluationData () inline
Definition at line 61 of file MovieSceneTrackEvaluationField.h.
References Flags, ForcedTime, Lowest, None, and SortOrder.
Referenced by FromSection(), FromTrack(), SetFlags(), and Sort().
Member Function Documentation
FromSection()
MOVIESCENE_API FMovieSceneTrackEvaluationData FMovieSceneTrackEvaluationData::FromSection (UMovieSceneSection * InSection) static
References FMovieSceneTrackEvaluationData().
FromTrack()
MOVIESCENE_API FMovieSceneTrackEvaluationData FMovieSceneTrackEvaluationData::FromTrack (UMovieSceneTrack * InTrack) static
References FMovieSceneTrackEvaluationData().
SetFlags()
FMovieSceneTrackEvaluationData & FMovieSceneTrackEvaluationData::SetFlags (ESectionEvaluationFlags InFlags) inline
Definition at line 71 of file MovieSceneTrackEvaluationField.h.
References FMovieSceneTrackEvaluationData(), and Flags.
Sort()
FMovieSceneTrackEvaluationData & FMovieSceneTrackEvaluationData::Sort (int16 InSortOrder) inline
Definition at line 77 of file MovieSceneTrackEvaluationField.h.
References FMovieSceneTrackEvaluationData(), and SortOrder.
Field Documentation
Flags
ESectionEvaluationFlags FMovieSceneTrackEvaluationData::Flags
Definition at line 91 of file MovieSceneTrackEvaluationField.h.
Referenced by FMovieSceneTrackEvaluationData(), and SetFlags().
ForcedTime
FFrameNumber FMovieSceneTrackEvaluationData::ForcedTime
Definition at line 87 of file MovieSceneTrackEvaluationField.h.
Referenced by FMovieSceneTrackEvaluationData().
Section
TWeakObjectPtr<UMovieSceneSection> FMovieSceneTrackEvaluationData::Section
Definition at line 85 of file MovieSceneTrackEvaluationField.h.
SortOrder
int16 FMovieSceneTrackEvaluationData::SortOrder
Definition at line 89 of file MovieSceneTrackEvaluationField.h.
Referenced by FMovieSceneTrackEvaluationData(), and Sort().
Track
TWeakObjectPtr<UMovieSceneTrack> FMovieSceneTrackEvaluationData::Track
Definition at line 83 of file MovieSceneTrackEvaluationField.h.
The documentation for this struct was generated from the following file:
Runtime/MovieScene/Public/MovieSceneTrackEvaluationField.h