Unreal Engine 5.6 C++ API: IPackageWriter::FCommitPackageInfo Struct Reference
IPackageWriter::FCommitPackageInfo Struct Reference
#include "PackageWriter.h"
Public Member Functions
FCommitPackageInfo ()=default
FCommitPackageInfo (const FCommitPackageInfo &)=default
FCommitPackageInfo (FCommitPackageInfo &&)=default
FCommitPackageInfo & operator= (FCommitPackageInfo &&)=default
FCommitPackageInfo & operator= (FCommitPackageInfo &)=default
UE_DEPRECATED (5.4, "Use PackageHash instead") FGuid PackageGuid
Data Fields
TArray< FCommitAttachmentInfo > Attachments
FIoHash PackageHash
FName PackageName
PRAGMA_DISABLE_DEPRECATION_WARNINGS
PRAGMA_ENABLE_DEPRECATION_WARNINGS
ECommitStatus Status
EWriteOptions WriteOptions
Detailed Description
Definition at line 108 of file PackageWriter.h.
Constructor & Destructor Documentation
FCommitPackageInfo() [1/3]
IPackageWriter::FCommitPackageInfo::FCommitPackageInfo () inline default
References FCommitPackageInfo().
Referenced by FCommitPackageInfo(), FCommitPackageInfo(), FCommitPackageInfo(), operator=(), and operator=().
FCommitPackageInfo() [2/3]
IPackageWriter::FCommitPackageInfo::FCommitPackageInfo (const FCommitPackageInfo &) inline default
References FCommitPackageInfo().
FCommitPackageInfo() [3/3]
IPackageWriter::FCommitPackageInfo::FCommitPackageInfo (FCommitPackageInfo &&) inline default
References FCommitPackageInfo().
Member Function Documentation
operator=() [1/2]
FCommitPackageInfo & IPackageWriter::FCommitPackageInfo::operator= (FCommitPackageInfo &&) inline default
References FCommitPackageInfo().
operator=() [2/2]
FCommitPackageInfo & IPackageWriter::FCommitPackageInfo::operator= (FCommitPackageInfo &) inline default
References FCommitPackageInfo().
UE_DEPRECATED()
IPackageWriter::FCommitPackageInfo::UE_DEPRECATED (5. 4, "Use PackageHash instead")
Field Documentation
Attachments
TArray<FCommitAttachmentInfo> IPackageWriter::FCommitPackageInfo::Attachments
Definition at line 114 of file PackageWriter.h.
PackageHash
FIoHash IPackageWriter::FCommitPackageInfo::PackageHash
Definition at line 111 of file PackageWriter.h.
PackageName
FName IPackageWriter::FCommitPackageInfo::PackageName
Definition at line 110 of file PackageWriter.h.
PRAGMA_DISABLE_DEPRECATION_WARNINGS
IPackageWriter::FCommitPackageInfo::PRAGMA_DISABLE_DEPRECATION_WARNINGS
Definition at line 118 of file PackageWriter.h.
PRAGMA_ENABLE_DEPRECATION_WARNINGS
IPackageWriter::FCommitPackageInfo::PRAGMA_ENABLE_DEPRECATION_WARNINGS
Definition at line 124 of file PackageWriter.h.
Status
ECommitStatus IPackageWriter::FCommitPackageInfo::Status
Definition at line 115 of file PackageWriter.h.
WriteOptions
EWriteOptions IPackageWriter::FCommitPackageInfo::WriteOptions
Definition at line 116 of file PackageWriter.h.
The documentation for this struct was generated from the following file:
Runtime/Core/Public/Serialization/PackageWriter.h