Unreal Engine 5.6 C++ API: UE::Sequencer::TTypedIteratorBase< T, IteratorType > Struct Template Reference
UE::Sequencer::TTypedIteratorBase< T, IteratorType > Struct Template Reference
Utility class to wrap an untyped iterator (one that only returns FViewModel pointers) so that it can be used as a typed iterator.
#include "ViewModelIterators.h"
Public Member Functions
template<typename ... ArgTypes>
TTypedIteratorBase (ArgTypes &&... InArgs)
FORCEINLINE TTypedIterator< T, IteratorType > begin () const
FORCEINLINE TTypedIterator< T, IteratorType > end () const
template<typename ValueType, typename ProjectionType>
TViewModelPtr< T > FindBy (const ValueType &Value, ProjectionType Proj) const
Linearly search through this iterator to find a predicate using a projection For example: UMovieSceneTrack* TrackToFind = ...; Model->GetChildrenOfType<FTrackModel>().FindBy(TrackToFind, &FTrackModel::GetTrack)
FORCEINLINE const TViewModelPtr< T > & operator* () const
void operator++ ()
FORCEINLINE T * operator-> () const
TArray< TViewModelPtr< T > > ToArray () const
Return the remaining items in this iterator as an array The state of this iterator remains unchanged.
void ToArray (TArray< TViewModelPtr< T > > &OutArray) const
Populate the specified array with the remaining items in this iterator The state of this iterator remains unchanged.
Protected Member Functions
void GetCastResultOrContinue ()
Protected Attributes
TViewModelPtr< T > TypedValue
Detailed Description
template<typename T, typename IteratorType>
struct UE::Sequencer::TTypedIteratorBase< T, IteratorType >
Utility class to wrap an untyped iterator (one that only returns FViewModel pointers) so that it can be used as a typed iterator.
Definition at line 487 of file ViewModelIterators.h.
Constructor & Destructor Documentation
TTypedIteratorBase()
template<typename T, typename IteratorType> template<typename ... ArgTypes> UE::Sequencer::TTypedIteratorBase< T, IteratorType >::TTypedIteratorBase (ArgTypes &&... InArgs) inline
Definition at line 490 of file ViewModelIterators.h.
References Forward(), and GetCastResultOrContinue().
Referenced by UE::Sequencer::TTypedIterator< T, FParentModelIterator >::TTypedIterator(), FindBy(), and ToArray().
Member Function Documentation
begin()
template<typename T, typename IteratorType> FORCEINLINE TTypedIterator< T, IteratorType > UE::Sequencer::TTypedIteratorBase< T, IteratorType >::begin () const inline
Definition at line 548 of file ViewModelIterators.h.
References FORCEINLINE.
end()
template<typename T, typename IteratorType> FORCEINLINE TTypedIterator< T, IteratorType > UE::Sequencer::TTypedIteratorBase< T, IteratorType >::end () const inline
Definition at line 549 of file ViewModelIterators.h.
References FORCEINLINE.
FindBy()
template<typename T, typename IteratorType> template<typename ValueType, typename ProjectionType> TViewModelPtr< T > UE::Sequencer::TTypedIteratorBase< T, IteratorType >::FindBy (const ValueType & Value, ProjectionType Proj) const inline
Linearly search through this iterator to find a predicate using a projection For example: UMovieSceneTrack* TrackToFind = ...; Model->GetChildrenOfType<FTrackModel>().FindBy(TrackToFind, &FTrackModel::GetTrack)
Definition at line 535 of file ViewModelIterators.h.
References TTypedIteratorBase(), Invoke(), Item, and Value.
GetCastResultOrContinue()
template<typename T, typename IteratorType> void UE::Sequencer::TTypedIteratorBase< T, IteratorType >::GetCastResultOrContinue () inline protected
Definition at line 553 of file ViewModelIterators.h.
References TypedValue.
Referenced by TTypedIteratorBase(), and operator++().
operator*()
template<typename T, typename IteratorType> FORCEINLINE const TViewModelPtr< T > & UE::Sequencer::TTypedIteratorBase< T, IteratorType >::operator* () const inline
Definition at line 497 of file ViewModelIterators.h.
References check, FORCEINLINE, and TypedValue.
operator++()
template<typename T, typename IteratorType> void UE::Sequencer::TTypedIteratorBase< T, IteratorType >::operator++ () inline
Definition at line 499 of file ViewModelIterators.h.
References GetCastResultOrContinue().
operator->()
template<typename T, typename IteratorType> FORCEINLINE T * UE::Sequencer::TTypedIteratorBase< T, IteratorType >::operator-> () const inline
Definition at line 496 of file ViewModelIterators.h.
References check, FORCEINLINE, and TypedValue.
ToArray() [1/2]
template<typename T, typename IteratorType> TArray< TViewModelPtr< T > > UE::Sequencer::TTypedIteratorBase< T, IteratorType >::ToArray () const inline
Return the remaining items in this iterator as an array The state of this iterator remains unchanged.
Definition at line 521 of file ViewModelIterators.h.
References ToArray().
Referenced by ToArray().
ToArray() [2/2]
template<typename T, typename IteratorType> void UE::Sequencer::TTypedIteratorBase< T, IteratorType >::ToArray (TArray< TViewModelPtr< T > > & OutArray) const inline
Populate the specified array with the remaining items in this iterator The state of this iterator remains unchanged.
Definition at line 509 of file ViewModelIterators.h.
References TTypedIteratorBase().
Field Documentation
TypedValue
template<typename T, typename IteratorType> TViewModelPtr<T> UE::Sequencer::TTypedIteratorBase< T, IteratorType >::TypedValue protected
Definition at line 568 of file ViewModelIterators.h.
Referenced by GetCastResultOrContinue(), operator*(), and operator->().
The documentation for this struct was generated from the following file:
Editor/SequencerCore/Public/MVVM/ViewModels/ViewModelIterators.h