Unreal Engine 5.6 C++ API: FARFilter Struct Reference
FARFilter Struct Reference
A struct to serve as a filter for Asset Registry queries.
#include "ARFilter.h"
Public Member Functions
PRAGMA_DISABLE_DEPRECATION_WARNINGS FARFilter ()=default
FARFilter (const FARFilter &)=default
FARFilter (FARFilter &&)=default
void Append (const FARFilter &Other)
Appends the other filter to this one.
void Clear ()
Clears this filter of all entries.
bool IsEmpty () const
Returns true if this filter has no entries.
bool IsRecursive () const
Returns true if this filter is recursive.
bool operator< (const FARFilter &Other) const
FARFilter & operator= (const FARFilter &)=default
FARFilter & operator= (FARFilter &&)=default
bool operator== (const FARFilter &Other) const
void PostSerialize (const FArchive &Ar)
void SortForSaving ()
Sort the structures (e.g.
UE_DEPRECATED (5.1, "Class names are now represented by path names. Please use ClassPaths.") TArray< FName > ClassNames
Deprecated.
UE_DEPRECATED (5.1, "Class names are now represented by path names. Please use RecursiveClassPathsExclusionSet.") TSet< FName > RecursiveClassesExclusionSet
Deprecated.
Data Fields
bool bIncludeOnlyOnDiskAssets = false
If true, use only DiskGatheredData, do not calculate from UObjects.
bool bRecursiveClasses = false
If true, subclasses of ClassPaths will also be included and RecursiveClassPathsExclusionSet will be excluded.
bool bRecursivePaths = false
If true, PackagePath components will be recursive.
TArray< FTopLevelAssetPath > ClassPaths
The filter component for class path names.
PRAGMA_ENABLE_DEPRECATION_WARNINGS TArray< FName > PackageNames
The filter component for package names.
TArray< FName > PackagePaths
The filter component for package paths.
TSet< FTopLevelAssetPath > RecursiveClassPathsExclusionSet
Only if bRecursiveClasses is true, the results will exclude classes (and subclasses) in this list.
TArray< FSoftObjectPath > SoftObjectPaths
The filter component containing the paths of specific assets to match.
TMultiMap< FName, TOptional< FString > > TagsAndValues
The filter component for properties marked with the AssetRegistrySearchable flag.
uint32 WithoutPackageFlags = 0
The exclusive filter component for package flags.
uint32 WithPackageFlags = 0
The inclusive filter component for package flags.
Private Member Functions
void Save (FCbWriter &Writer) const
bool TryLoad (const FCbFieldView &Field)
Friends
bool LoadFromCompactBinary (const FCbFieldView &Field, FARFilter &Filter)
FCbWriter & operator<< (FCbWriter &Writer, const FARFilter &Filter)
Detailed Description
A struct to serve as a filter for Asset Registry queries.
Each component element is processed as an 'OR' operation while all the components are processed together as an 'AND' operation. This type is mirrored in NoExportTypes.h
Definition at line 19 of file ARFilter.h.
Constructor & Destructor Documentation
FARFilter() [1/3]
PRAGMA_DISABLE_DEPRECATION_WARNINGS FARFilter::FARFilter () default
Referenced by FARFilter(), FARFilter(), Append(), LoadFromCompactBinary, operator<(), operator<<, operator=(), operator=(), and operator==().
FARFilter() [2/3]
FARFilter::FARFilter (FARFilter &&) default
References FARFilter().
FARFilter() [3/3]
FARFilter::FARFilter (const FARFilter &) default
References FARFilter().
Member Function Documentation
Append()
void FARFilter::Append (const FARFilter & Other) inline
Appends the other filter to this one.
Definition at line 84 of file ARFilter.h.
References FARFilter(), Append(), bIncludeOnlyOnDiskAssets, bRecursiveClasses, bRecursivePaths, ClassPaths, Other, PackageNames, PackagePaths, RecursiveClassPathsExclusionSet, SoftObjectPaths, WithoutPackageFlags, and WithPackageFlags.
Referenced by Append().
Clear()
void FARFilter::Clear () inline
Clears this filter of all entries.
Definition at line 118 of file ARFilter.h.
References bIncludeOnlyOnDiskAssets, bRecursiveClasses, bRecursivePaths, ClassPaths, ensure, IsEmpty(), PackageNames, PackagePaths, RecursiveClassPathsExclusionSet, SoftObjectPaths, TagsAndValues, WithoutPackageFlags, and WithPackageFlags.
IsEmpty()
bool FARFilter::IsEmpty () const inline
Returns true if this filter has no entries.
Definition at line 106 of file ARFilter.h.
References ClassPaths, PackageNames, PackagePaths, SoftObjectPaths, TagsAndValues, WithoutPackageFlags, and WithPackageFlags.
Referenced by Clear().
IsRecursive()
bool FARFilter::IsRecursive () const inline
Returns true if this filter is recursive.
Definition at line 112 of file ARFilter.h.
References bRecursiveClasses, and bRecursivePaths.
operator<()
bool FARFilter::operator< (const FARFilter & Other) const
References FARFilter(), and Other.
operator=() [1/2]
FARFilter & FARFilter::operator= (const FARFilter &) default
References FARFilter(), and PRAGMA_ENABLE_DEPRECATION_WARNINGS.
operator=() [2/2]
FARFilter & FARFilter::operator= (FARFilter &&) default
References FARFilter().
operator==()
bool FARFilter::operator== (const FARFilter & Other) const
References FARFilter(), and Other.
PostSerialize()
void FARFilter::PostSerialize (const FArchive & Ar)
References Ar.
Save()
void FARFilter::Save (FCbWriter & Writer) const private
SortForSaving()
void FARFilter::SortForSaving ()
Sort the structures (e.g.
PackageNames) on this filter to be deterministic for saving the structure during cooking. This is also required for correctness of operator== when comparing the order-independent arrays.
TryLoad()
bool FARFilter::TryLoad (const FCbFieldView & Field) private
UE_DEPRECATED() [1/2]
FARFilter::UE_DEPRECATED (5. 1, "Class names are now represented by path names. Please use ClassPaths.")
Deprecated.
The filter component for class names. Instances of the specified classes, but not subclasses (by default), will be included. Derived classes will be included only if bRecursiveClasses is true.
Referenced by UE_DEPRECATED().
UE_DEPRECATED() [2/2]
FARFilter::UE_DEPRECATED (5. 1, "Class names are now represented by path names. Please use RecursiveClassPathsExclusionSet.")
Deprecated.
Only if bRecursiveClasses is true, the results will exclude classes (and subclasses) in this list
References UE_DEPRECATED().
Friends And Related Symbol Documentation
LoadFromCompactBinary
bool LoadFromCompactBinary (const FCbFieldView & Field, FARFilter & Filter) friend
Definition at line 156 of file ARFilter.h.
References FARFilter(), and Filter.
operator<<
FCbWriter & operator<< (FCbWriter & Writer, const FARFilter & Filter) friend
Definition at line 151 of file ARFilter.h.
References FARFilter(), and Filter.
Field Documentation
bIncludeOnlyOnDiskAssets
bool FARFilter::bIncludeOnlyOnDiskAssets = false
If true, use only DiskGatheredData, do not calculate from UObjects.
See also
IAssetRegistry class header for bIncludeOnlyOnDiskAssets.
Definition at line 75 of file ARFilter.h.
Referenced by Append(), and Clear().
bRecursiveClasses
bool FARFilter::bRecursiveClasses = false
If true, subclasses of ClassPaths will also be included and RecursiveClassPathsExclusionSet will be excluded.
Definition at line 69 of file ARFilter.h.
Referenced by Append(), Clear(), and IsRecursive().
bRecursivePaths
bool FARFilter::bRecursivePaths = false
If true, PackagePath components will be recursive.
Definition at line 66 of file ARFilter.h.
Referenced by Append(), Clear(), and IsRecursive().
ClassPaths
TArray<FTopLevelAssetPath> FARFilter::ClassPaths
The filter component for class path names.
Instances of the specified classes, but not subclasses (by default), will be included. Derived classes will be included only if bRecursiveClasses is true.
Definition at line 53 of file ARFilter.h.
Referenced by Append(), Clear(), FSoundWaveLoadingBehaviorUtil::CollectAllRelevantSoundClassAssetData(), and IsEmpty().
PackageNames
PRAGMA_ENABLE_DEPRECATION_WARNINGS TArray<FName> FARFilter::PackageNames
The filter component for package names.
Definition at line 30 of file ARFilter.h.
Referenced by Append(), Clear(), FSoundWaveLoadingBehaviorUtil::CollectAllRelevantSoundClassAssetData(), and IsEmpty().
PackagePaths
TArray<FName> FARFilter::PackagePaths
The filter component for package paths.
Definition at line 33 of file ARFilter.h.
Referenced by Append(), Clear(), and IsEmpty().
RecursiveClassPathsExclusionSet
TSet<FTopLevelAssetPath> FARFilter::RecursiveClassPathsExclusionSet
Only if bRecursiveClasses is true, the results will exclude classes (and subclasses) in this list.
Definition at line 63 of file ARFilter.h.
Referenced by Append(), and Clear().
SoftObjectPaths
TArray<FSoftObjectPath> FARFilter::SoftObjectPaths
The filter component containing the paths of specific assets to match.
Matches against FAssetData::ToSoftObjectPath(). This is a top level asset path for most assets and a subobject path for assets such as world partition external actors.
Definition at line 46 of file ARFilter.h.
Referenced by Append(), Clear(), and IsEmpty().
TagsAndValues
TMultiMap<FName, TOptional<FString> > FARFilter::TagsAndValues
The filter component for properties marked with the AssetRegistrySearchable flag.
Definition at line 56 of file ARFilter.h.
Referenced by Clear(), and IsEmpty().
WithoutPackageFlags
uint32 FARFilter::WithoutPackageFlags = 0
The exclusive filter component for package flags.
Only assets without any of the specified flags will be returned.
Definition at line 78 of file ARFilter.h.
Referenced by Append(), Clear(), and IsEmpty().
WithPackageFlags
uint32 FARFilter::WithPackageFlags = 0
The inclusive filter component for package flags.
Only assets with all of the specified flags will be returned.
Definition at line 81 of file ARFilter.h.
Referenced by Append(), Clear(), and IsEmpty().
The documentation for this struct was generated from the following file:
Runtime/CoreUObject/Public/AssetRegistry/ARFilter.h