Unreal Engine 5.6 C++ API: FMessageDialog Struct Reference
FMessageDialog Struct Reference
FMessageDialog These functions open a message dialog and display the specified informations there.
#include "MessageDialog.h"
Public Member Functions
UE_DEPRECATED (5.3, "Use the overload of Debugf that takes the Title by-value.") static 1 void Debugf(const FText &Message
Static Public Member Functions
static void Debugf (const FText &Message)
Pops up a message dialog box containing the input string.
static void Debugf (const FText &Message, const FText &Title)
static EAppReturnType::Type Open (EAppMsgCategory MessageCategory, EAppMsgType::Type MessageType, const FText &Message)
static EAppReturnType::Type Open (EAppMsgCategory MessageCategory, EAppMsgType::Type MessageType, const FText &Message, const FText &Title)
static EAppReturnType::Type Open (EAppMsgCategory MessageCategory, EAppMsgType::Type MessageType, EAppReturnType::Type DefaultValue, const FText &Message)
static EAppReturnType::Type Open (EAppMsgCategory MessageCategory, EAppMsgType::Type MessageType, EAppReturnType::Type DefaultValue, const FText &Message, const FText &Title)
static EAppReturnType::Type Open (EAppMsgType::Type MessageType, const FText &Message)
Open a modal message box dialog.
static EAppReturnType::Type Open (EAppMsgType::Type MessageType, const FText &Message, const FText &Title)
static UE_DEPRECATED(5.3, "Use the overload of Open that takes the Title by-value.") static 1 EAppReturnType EAppReturnType::Type Open (EAppMsgType::Type MessageType, EAppReturnType::Type DefaultValue, const FText &Message)
Open a modal message box dialog.
static EAppReturnType::Type Open (EAppMsgType::Type MessageType, EAppReturnType::Type DefaultValue, const FText &Message, const FText &Title)
static void ShowLastError ()
Pops up a message dialog box containing the last system error code in string form.
Data Fields
const FText * OptTitle
Detailed Description
FMessageDialog These functions open a message dialog and display the specified informations there.
Definition at line 16 of file MessageDialog.h.
Member Function Documentation
Debugf() [1/2]
void FMessageDialog::Debugf (const FText & Message) static
Pops up a message dialog box containing the input string.
Parameters
Message Text of message to show
Title Optional title to use (defaults to "Message")
Debugf() [2/2]
void FMessageDialog::Debugf (const FText & Message, const FText & Title) static
References Title.
Open() [1/8]
EAppReturnType::Type FMessageDialog::Open (EAppMsgCategory MessageCategory, EAppMsgType::Type MessageType, const FText & Message) static
References Open().
Open() [2/8]
EAppReturnType::Type FMessageDialog::Open (EAppMsgCategory MessageCategory, EAppMsgType::Type MessageType, const FText & Message, const FText & Title) static
References Open(), OptTitle, Title, and UE_DEPRECATED().
Open() [3/8]
EAppReturnType::Type FMessageDialog::Open (EAppMsgCategory MessageCategory, EAppMsgType::Type MessageType, EAppReturnType::Type DefaultValue, const FText & Message) static
References Open().
Open() [4/8]
EAppReturnType::Type FMessageDialog::Open (EAppMsgCategory MessageCategory, EAppMsgType::Type MessageType, EAppReturnType::Type DefaultValue, const FText & Message, const FText & Title) static
References Open(), OptTitle, Title, and UE_DEPRECATED().
Open() [5/8]
EAppReturnType::Type FMessageDialog::Open (EAppMsgType::Type MessageType, const FText & Message) static
Open a modal message box dialog.
Parameters
MessageCategory Controls the icon used for the dialog
MessageType Controls buttons dialog should have
Message Text of message to show
Title Optional title to use (defaults to "Message")
References Open().
Referenced by UE::PixelStreaming2::IsPlatformSupported(), Open(), Open(), Open(), Open(), Open(), Open(), Open(), Open(), and FFeedbackContextEditor::YesNof().
Open() [6/8]
EAppReturnType::Type FMessageDialog::Open (EAppMsgType::Type MessageType, const FText & Message, const FText & Title) static
References Open(), and Title.
Open() [7/8]
UE_DEPRECATED(5.3, "Use the overload of Open that takes the Title by-value.") static 1 EAppReturnType EAppReturnType::Type FMessageDialog::Open (EAppMsgType::Type MessageType, EAppReturnType::Type DefaultValue, const FText & Message) static
Open a modal message box dialog.
Parameters
MessageCategory Controls the icon used for the dialog
MessageType Controls buttons dialog should have
DefaultValue If the application is Unattended, the function will log and return DefaultValue
Message Text of message to show
Title Optional title to use (defaults to "Message")
References Open().
Open() [8/8]
EAppReturnType::Type FMessageDialog::Open (EAppMsgType::Type MessageType, EAppReturnType::Type DefaultValue, const FText & Message, const FText & Title) static
References Open(), and Title.
ShowLastError()
void FMessageDialog::ShowLastError () static
Pops up a message dialog box containing the last system error code in string form.
References ShowLastError().
Referenced by ShowLastError().
UE_DEPRECATED()
FMessageDialog::UE_DEPRECATED (5. 3, "Use the overload of Debugf that takes the Title by-value.") const &
Referenced by Open(), and Open().
Field Documentation
OptTitle
const FText* FMessageDialog::OptTitle
Definition at line 25 of file MessageDialog.h.
Referenced by Open(), and Open().
The documentation for this struct was generated from the following file:
Runtime/Core/Public/Misc/MessageDialog.h