Unreal Engine 5.6 C++ API: UE::MovieScene::TEntityTaskComponents< T > Struct Template Reference
UE::MovieScene::TEntityTaskComponents< T > Struct Template Reference
Defines the accessors for each desired component of an entity task.
#include "MovieSceneEntitySystemTask.h"
Public Types
using Super = TEntityTaskComponentsImpl<TMakeIntegerSequence<int, sizeof...(T)>, T...>
Public Member Functions
TEntityTaskComponents ()
template<typename... ConstructionTypes>
TEntityTaskComponents (const FCommonEntityTaskParams &InCommonParams, ConstructionTypes &&... InTypes)
TFilteredEntityTask< T... > CombineFilter (const FEntityComponentFilter &InFilter)
Combine this task's filter with the specified filter.
template<typename TaskImpl, typename... TaskConstructionArgs>
FGraphEventRef Dispatch (FEntityManager *EntityManager, const FSystemTaskPrerequisites &Prerequisites, FSystemSubsequentTasks *Subsequents, TaskConstructionArgs &&... InArgs) const
Dispatch a custom task that runs non-structured logic.
template<typename TaskImpl, typename... TaskConstructionArgs>
FGraphEventRef Dispatch_PerAllocation (FEntityManager *EntityManager, const FSystemTaskPrerequisites &Prerequisites, FSystemSubsequentTasks *Subsequents, TaskConstructionArgs &&... InArgs) const
Dispatch a task for every allocation that matches the filters and component types.
template<typename TaskImpl, typename... TaskConstructionArgs>
FGraphEventRef Dispatch_PerEntity (FEntityManager *EntityManager, const FSystemTaskPrerequisites &Prerequisites, FSystemSubsequentTasks *Subsequents, TaskConstructionArgs &&... InArgs) const
Dispatch a task for every entity that matches the filters and component types.
TFilteredEntityTask< T... > FilterAll (const FComponentMask &InComponentMask)
Constrain this task to only run for entities that have all the specified components or tags.
TFilteredEntityTask< T... > FilterAll (std::initializer_list< FComponentTypeID > InComponentTypes)
Constrain this task to only run for entities that have all the specified components or tags.
TFilteredEntityTask< T... > FilterAny (const FComponentMask &InComponentMask)
Constrain this task to only run for entities that have at least one of the specified components or tags.
TFilteredEntityTask< T... > FilterAny (std::initializer_list< FComponentTypeID > InComponentTypes)
Constrain this task to only run for entities that have at least one of the specified components or tags.
TFilteredEntityTask< T... > FilterNone (const FComponentMask &InComponentMask)
Constrain this task to only run for entities that have none the specified components or tags.
TFilteredEntityTask< T... > FilterNone (std::initializer_list< FComponentTypeID > InComponentTypes)
Constrain this task to only run for entities that have none the specified components or tags.
TFilteredEntityTask< T... > FilterOut (const FComponentMask &InComponentMask)
Constrain this task to only run for entities that do not have the specific combination of components or tags.
TFilteredEntityTask< T... > FilterOut (std::initializer_list< FComponentTypeID > InComponentTypes)
Constrain this task to only run for entities that do not have the specific combination of components or tags.
template<typename TaskImpl, typename... TaskConstructionArgs>
FTaskID Fork_PerAllocation (FEntityManager *EntityManager, IEntitySystemScheduler *InScheduler, TaskConstructionArgs &&... InArgs) const
template<typename TaskImpl, typename... TaskConstructionArgs>
FTaskID Fork_PerEntity (FEntityManager *EntityManager, IEntitySystemScheduler *InScheduler, TaskConstructionArgs &&... InArgs) const
template<typename TaskImpl>
void RunInline_PerAllocation (FEntityManager *EntityManager, TaskImpl &Task) const
template<typename TaskImpl>
void RunInline_PerEntity (FEntityManager *EntityManager, TaskImpl &Task) const
template<typename TaskImpl, typename... TaskConstructionArgs>
FTaskID Schedule_PerAllocation (FEntityManager *EntityManager, IEntitySystemScheduler *InScheduler, TaskConstructionArgs &&... InArgs) const
template<typename TaskImpl, typename... TaskConstructionArgs>
FTaskID Schedule_PerEntity (FEntityManager *EntityManager, IEntitySystemScheduler *InScheduler, TaskConstructionArgs &&... InArgs) const
TEntityTaskComponents< T... > & SetDesiredThread (ENamedThreads::Type InDesiredThread)
Assign a desired thread for this task to run on.
TEntityTaskComponents< T... > & SetParams (const FTaskParams &InOtherParams)
Assign the scheduled task parameters for this task.
TEntityTaskComponents< T... > & SetStat (TStatId InStatId)
Assign a stat ID for this task.
Private Member Functions
template<typename TaskImpl, typename... TaskConstructionArgs>
FTaskID ScheduleImpl (FEntityManager *EntityManager, IEntitySystemScheduler *InScheduler, const FTaskParams &TaskParams, TaskFunctionPtr InFunction, TaskConstructionArgs &&... InArgs) const
Detailed Description
template<typename... T>
struct UE::MovieScene::TEntityTaskComponents< T >
Defines the accessors for each desired component of an entity task.
Definition at line 173 of file MovieSceneEntitySystemTask.h.
Member Typedef Documentation
Super
template<typename... T> using UE::MovieScene::TEntityTaskComponents< T >::Super = TEntityTaskComponentsImpl<TMakeIntegerSequence<int, sizeof...(T)>, T...>
Definition at line 175 of file MovieSceneEntitySystemTask.h.
Constructor & Destructor Documentation
TEntityTaskComponents() [1/2]
template<typename... T> UE::MovieScene::TEntityTaskComponents< T >::TEntityTaskComponents () inline
Definition at line 571 of file MovieSceneEntitySystemTask.h.
Referenced by SetDesiredThread(), SetParams(), and SetStat().
TEntityTaskComponents() [2/2]
template<typename... T> template<typename... ConstructionTypes> UE::MovieScene::TEntityTaskComponents< T >::TEntityTaskComponents (const FCommonEntityTaskParams & InCommonParams, ConstructionTypes &&... InTypes) inline explicit
Definition at line 577 of file MovieSceneEntitySystemTask.h.
References Forward().
Member Function Documentation
CombineFilter()
template<typename... T> TFilteredEntityTask< T... > UE::MovieScene::TEntityTaskComponents< T >::CombineFilter (const FEntityComponentFilter & InFilter) inline
Combine this task's filter with the specified filter.
Definition at line 261 of file MovieSceneEntitySystemTask.h.
Referenced by UE::MovieScene::TPreAnimatedStateStorage< TPreAnimatedMaterialTraits< AccessorType, RequiredComponents... > >::BeginTrackingAndCachePreAnimatedValuesTask(), UE::MovieScene::TPreAnimatedStateStorage< TPreAnimatedMaterialTraits< AccessorType, RequiredComponents... > >::CachePreAnimatedValuesTask(), and UE::MovieScene::TOverlappingEntityTrackerImpl< OutputType, InputTypes... >::UpdateFromComponents().
Dispatch()
template<typename... T> template<typename TaskImpl, typename... TaskConstructionArgs> FGraphEventRef UE::MovieScene::TEntityTaskComponents< T >::Dispatch (FEntityManager * EntityManager, const FSystemTaskPrerequisites & Prerequisites, FSystemSubsequentTasks * Subsequents, TaskConstructionArgs &&... InArgs) const inline
Dispatch a custom task that runs non-structured logic.
Tasks must implement a Run function that doesn't take any argument.
Parameters
EntityManager The entity manager to run the task on
Prerequisites Prerequisite tasks that must run before this one, or nullptr if there are no prerequisites
Subsequents (Optional) Subsequent task tracking that this task should be added to for each writable component type
InArgs Optional arguments that are forwarded to the constructor of TaskImpl
Returns
A pointer to the graph event for the task, or nullptr if this task is not valid (ie contains invalid component types that would be necessary for the task to run), or threading is disabled
Definition at line 305 of file MovieSceneEntitySystemTask.h.
References ENamedThreads::AnyThread, checkfSlow, checkSlow, ensure, Forward(), IsInGameThread(), UE::MovieScene::NoThreading, TArray< InElementType, InAllocatorType >::Num(), UE::MovieScene::PopulatePrerequisites(), UE::MovieScene::PopulateSubsequents(), and TEXT.
Dispatch_PerAllocation()
template<typename... T> template<typename TaskImpl, typename... TaskConstructionArgs> FGraphEventRef UE::MovieScene::TEntityTaskComponents< T >::Dispatch_PerAllocation (FEntityManager * EntityManager, const FSystemTaskPrerequisites & Prerequisites, FSystemSubsequentTasks * Subsequents, TaskConstructionArgs &&... InArgs) const inline
Dispatch a task for every allocation that matches the filters and component types.
Must be explicitly instantiated with the task type to dispatch. Construction arguments are deduced. Tasks must implement a ForEachAllocation function that matches this task's component accessor types.
For example: struct FForEachAllocation { void ForEachAllocation(FEntityAllocation* InAllocation, const TFilteredEntityTask< FEntityIDAccess, TRead<FMovieSceneFloatChannel> >& InputTask); };
TComponentTypeID<FMovieSceneFloatChannel> FloatChannelComponent = ...;
FGraphEventRef Task = FEntityTaskBuilder() .ReadEntityIDs() .Read(FloatChannelComponent) .SetStat(GET_STATID(MyStatName)) .SetDesiredThread(ENamedThreads::AnyThread) .Dispatch_PerAllocation<FForEachAllocation>(EntityManager, Prerequisites);
Parameters
EntityManager The entity manager to run the task on. All component types must relate to this entity manager.
Prerequisites Prerequisite tasks that must run before this one
Subsequents (Optional) Subsequent task tracking that this task should be added to for each writable component type
InArgs Optional arguments that are forwarded to the constructor of TaskImpl
Returns
A pointer to the graph event for the task, or nullptr if this task is not valid (ie contains invalid component types that would be necessary for the task to run), or threading is disabled
Definition at line 364 of file MovieSceneEntitySystemTask.h.
References ENamedThreads::AnyThread, checkfSlow, checkSlow, ensure, Forward(), IsInGameThread(), IsValid(), UE::MovieScene::NoThreading, TArray< InElementType, InAllocatorType >::Num(), UE::MovieScene::PopulatePrerequisites(), UE::MovieScene::PopulateSubsequents(), and TEXT.
Dispatch_PerEntity()
template<typename... T> template<typename TaskImpl, typename... TaskConstructionArgs> FGraphEventRef UE::MovieScene::TEntityTaskComponents< T >::Dispatch_PerEntity (FEntityManager * EntityManager, const FSystemTaskPrerequisites & Prerequisites, FSystemSubsequentTasks * Subsequents, TaskConstructionArgs &&... InArgs) const inline
Dispatch a task for every entity that matches the filters and component types.
Must be explicitly instantiated with the task type to dispatch. Construction arguments are deduced. Tasks must implement a ForEachEntity function that matches this task's component accessor types.
For example: struct FForEachEntity { void ForEachEntity(FMovieSceneEntityID InEntityID, const FMovieSceneFloatChannel& Channel); };
TComponentTypeID<FMovieSceneFloatChannel> FloatChannelComponent = ...;
FGraphEventRef Task = FEntityTaskBuilder() .ReadEntityIDs() .Read(FloatChannelComponent) .SetStat(GET_STATID(MyStatName)) .SetDesiredThread(ENamedThreads::AnyThread) .Dispatch_PerEntity<FForEachEntity>(EntityManager, nullptr);
Parameters
EntityManager The entity manager to run the task on. All component types must relate to this entity manager.
Prerequisites Prerequisite tasks that must run before this one, or nullptr if there are no prerequisites
Subsequents (Optional) Subsequent task tracking that this task should be added to for each writable component type
InArgs Optional arguments that are forwarded to the constructor of TaskImpl
Returns
A pointer to the graph event for the task, or nullptr if this task is not valid (ie contains invalid component types that would be necessary for the task to run), or threading is disabled
Definition at line 444 of file MovieSceneEntitySystemTask.h.
References UE::MovieScene::FSystemSubsequentTasks::AddRootTask(), ENamedThreads::AnyThread, checkfSlow, checkSlow, ensure, Forward(), IsInGameThread(), IsValid(), UE::MovieScene::NoThreading, TArray< InElementType, InAllocatorType >::Num(), UE::MovieScene::PopulatePrerequisites(), UE::MovieScene::PopulateSubsequents(), and TEXT.
FilterAll() [1/2]
template<typename... T> TFilteredEntityTask< T... > UE::MovieScene::TEntityTaskComponents< T >::FilterAll (const FComponentMask & InComponentMask) inline
Constrain this task to only run for entities that have all the specified components or tags.
Definition at line 181 of file MovieSceneEntitySystemTask.h.
Referenced by UE::MovieScene::TPropertyComponentHandlerImpl< PropertyTraits, TPropertyMetaData< MetaDataTypes... >, TIntegerSequence< int, MetaDataIndices... >, TIntegerSequence< int, CompositeIndices... >, CompositeTypes... >::DispatchSetterTasks(), UE::MovieScene::TMovieSceneMaterialSystem< AccessorType, RequiredComponents >::OnRun(), UE::MovieScene::TSimpleBlenderSystemImpl< PropertyType, ResultTraits >::Run(), UE::MovieScene::TSimpleBlenderSystemImpl< PropertyType, ResultTraits >::Schedule(), and UE::MovieScene::TPropertyComponentHandlerImpl< PropertyTraits, TPropertyMetaData< MetaDataTypes... >, TIntegerSequence< int, MetaDataIndices... >, TIntegerSequence< int, CompositeIndices... >, CompositeTypes... >::ScheduleSetterTasks().
FilterAll() [2/2]
template<typename... T> TFilteredEntityTask< T... > UE::MovieScene::TEntityTaskComponents< T >::FilterAll (std::initializer_list< FComponentTypeID > InComponentTypes) inline
Constrain this task to only run for entities that have all the specified components or tags.
Definition at line 191 of file MovieSceneEntitySystemTask.h.
FilterAny() [1/2]
template<typename... T> TFilteredEntityTask< T... > UE::MovieScene::TEntityTaskComponents< T >::FilterAny (const FComponentMask & InComponentMask) inline
Constrain this task to only run for entities that have at least one of the specified components or tags.
Definition at line 221 of file MovieSceneEntitySystemTask.h.
Referenced by UE::MovieScene::TPropertyComponentHandlerImpl< PropertyTraits, TPropertyMetaData< MetaDataTypes... >, TIntegerSequence< int, MetaDataIndices... >, TIntegerSequence< int, CompositeIndices... >, CompositeTypes... >::DispatchSetterTasks(), and UE::MovieScene::TPropertyComponentHandlerImpl< PropertyTraits, TPropertyMetaData< MetaDataTypes... >, TIntegerSequence< int, MetaDataIndices... >, TIntegerSequence< int, CompositeIndices... >, CompositeTypes... >::ScheduleSetterTasks().
FilterAny() [2/2]
template<typename... T> TFilteredEntityTask< T... > UE::MovieScene::TEntityTaskComponents< T >::FilterAny (std::initializer_list< FComponentTypeID > InComponentTypes) inline
Constrain this task to only run for entities that have at least one of the specified components or tags.
Definition at line 231 of file MovieSceneEntitySystemTask.h.
FilterNone() [1/2]
template<typename... T> TFilteredEntityTask< T... > UE::MovieScene::TEntityTaskComponents< T >::FilterNone (const FComponentMask & InComponentMask) inline
Constrain this task to only run for entities that have none the specified components or tags.
Definition at line 201 of file MovieSceneEntitySystemTask.h.
Referenced by UE::MovieScene::TPreAnimatedStateStorage< TPreAnimatedMaterialTraits< AccessorType, RequiredComponents... > >::BeginTrackingEntitiesTask().
FilterNone() [2/2]
template<typename... T> TFilteredEntityTask< T... > UE::MovieScene::TEntityTaskComponents< T >::FilterNone (std::initializer_list< FComponentTypeID > InComponentTypes) inline
Constrain this task to only run for entities that have none the specified components or tags.
Definition at line 211 of file MovieSceneEntitySystemTask.h.
FilterOut() [1/2]
template<typename... T> TFilteredEntityTask< T... > UE::MovieScene::TEntityTaskComponents< T >::FilterOut (const FComponentMask & InComponentMask) inline
Constrain this task to only run for entities that do not have the specific combination of components or tags.
Definition at line 241 of file MovieSceneEntitySystemTask.h.
FilterOut() [2/2]
template<typename... T> TFilteredEntityTask< T... > UE::MovieScene::TEntityTaskComponents< T >::FilterOut (std::initializer_list< FComponentTypeID > InComponentTypes) inline
Constrain this task to only run for entities that do not have the specific combination of components or tags.
Definition at line 251 of file MovieSceneEntitySystemTask.h.
Fork_PerAllocation()
template<typename... T> template<typename TaskImpl, typename... TaskConstructionArgs> FTaskID UE::MovieScene::TEntityTaskComponents< T >::Fork_PerAllocation (FEntityManager * EntityManager, IEntitySystemScheduler * InScheduler, TaskConstructionArgs &&... InArgs) const inline
Definition at line 507 of file MovieSceneEntitySystemTask.h.
References UE::MovieScene::FTaskParams::bSerialTasks, UE::MovieScene::FTaskParams::DebugName, Forward(), GetGeneratedTypeName(), UE::MovieScene::TScheduledEntityTask< TaskImpl, ComponentTypes >::ScheduledRun_PerAllocation(), and ScheduleImpl().
Fork_PerEntity()
template<typename... T> template<typename TaskImpl, typename... TaskConstructionArgs> FTaskID UE::MovieScene::TEntityTaskComponents< T >::Fork_PerEntity (FEntityManager * EntityManager, IEntitySystemScheduler * InScheduler, TaskConstructionArgs &&... InArgs) const inline
Definition at line 489 of file MovieSceneEntitySystemTask.h.
References UE::MovieScene::FTaskParams::bSerialTasks, UE::MovieScene::FTaskParams::DebugName, Forward(), GetGeneratedTypeName(), UE::MovieScene::TScheduledEntityTask< TaskImpl, ComponentTypes >::ScheduledRun_PerEntity(), and ScheduleImpl().
RunInline_PerAllocation()
template<typename... T> template<typename TaskImpl> void UE::MovieScene::TEntityTaskComponents< T >::RunInline_PerAllocation (FEntityManager * EntityManager, TaskImpl & Task) const inline
Definition at line 410 of file MovieSceneEntitySystemTask.h.
References IsValid().
RunInline_PerEntity()
template<typename... T> template<typename TaskImpl> void UE::MovieScene::TEntityTaskComponents< T >::RunInline_PerEntity (FEntityManager * EntityManager, TaskImpl & Task) const inline
Definition at line 561 of file MovieSceneEntitySystemTask.h.
References IsValid().
Schedule_PerAllocation()
template<typename... T> template<typename TaskImpl, typename... TaskConstructionArgs> FTaskID UE::MovieScene::TEntityTaskComponents< T >::Schedule_PerAllocation (FEntityManager * EntityManager, IEntitySystemScheduler * InScheduler, TaskConstructionArgs &&... InArgs) const inline
Definition at line 543 of file MovieSceneEntitySystemTask.h.
References UE::MovieScene::FTaskParams::bSerialTasks, UE::MovieScene::FTaskParams::DebugName, Forward(), GetGeneratedTypeName(), UE::MovieScene::TScheduledEntityTask< TaskImpl, ComponentTypes >::ScheduledRun_PerAllocation(), and ScheduleImpl().
Schedule_PerEntity()
template<typename... T> template<typename TaskImpl, typename... TaskConstructionArgs> FTaskID UE::MovieScene::TEntityTaskComponents< T >::Schedule_PerEntity (FEntityManager * EntityManager, IEntitySystemScheduler * InScheduler, TaskConstructionArgs &&... InArgs) const inline
Definition at line 525 of file MovieSceneEntitySystemTask.h.
References UE::MovieScene::FTaskParams::bSerialTasks, UE::MovieScene::FTaskParams::DebugName, Forward(), GetGeneratedTypeName(), UE::MovieScene::TScheduledEntityTask< TaskImpl, ComponentTypes >::ScheduledRun_PerEntity(), and ScheduleImpl().
ScheduleImpl()
template<typename... T> template<typename TaskImpl, typename... TaskConstructionArgs> FTaskID UE::MovieScene::TEntityTaskComponents< T >::ScheduleImpl (FEntityManager * EntityManager, IEntitySystemScheduler * InScheduler, const FTaskParams & TaskParams, TaskFunctionPtr InFunction, TaskConstructionArgs &&... InArgs) const inline private
Definition at line 584 of file MovieSceneEntitySystemTask.h.
References UE::MovieScene::IEntitySystemScheduler::AddChildBack(), UE::MovieScene::IEntitySystemScheduler::AddChildFront(), UE::MovieScene::IEntitySystemScheduler::AddNullTask(), UE::MovieScene::FTaskParams::bForcePrePostTask, UE::MovieScene::IEntitySystemScheduler::CreateForkedAllocationTask(), Filter, Forward(), IsValid(), MakeShared(), UE::MovieScene::FTaskID::None(), UE::MovieScene::PopulateReadWriteDependencies(), UE::MovieScene::SchedulePostTask(), and UE::MovieScene::SchedulePreTask().
Referenced by Fork_PerAllocation(), Fork_PerEntity(), Schedule_PerAllocation(), and Schedule_PerEntity().
SetDesiredThread()
template<typename... T> TEntityTaskComponents< T... > & UE::MovieScene::TEntityTaskComponents< T >::SetDesiredThread (ENamedThreads::Type InDesiredThread) inline
Assign a desired thread for this task to run on.
Definition at line 269 of file MovieSceneEntitySystemTask.h.
References TEntityTaskComponents(), ENamedThreads::GameThread, and ENamedThreads::GameThread_Local.
SetParams()
template<typename... T> TEntityTaskComponents< T... > & UE::MovieScene::TEntityTaskComponents< T >::SetParams (const FTaskParams & InOtherParams) inline
Assign the scheduled task parameters for this task.
Definition at line 288 of file MovieSceneEntitySystemTask.h.
References TEntityTaskComponents().
SetStat()
template<typename... T> TEntityTaskComponents< T... > & UE::MovieScene::TEntityTaskComponents< T >::SetStat (TStatId InStatId) inline
Assign a stat ID for this task.
Definition at line 279 of file MovieSceneEntitySystemTask.h.
References TEntityTaskComponents().
The documentation for this struct was generated from the following file:
Runtime/MovieScene/Public/EntitySystem/MovieSceneEntitySystemTask.h