Unreal Engine 5.6 C++ API: UE::Geometry::TLine2< T > Struct Template Reference
UE::Geometry::TLine2< T > Struct Template Reference
TLine2 is a two-dimensional infinite line.
#include "LineTypes.h"
Public Member Functions
TLine2 ()
Construct default line along X axis.
TLine2 (const TVector2< T > &OriginIn, const TVector2< T > &DirectionIn)
Construct line with given Origin and Direction.
T DistanceSquared (const TVector2< T > &QueryPoint) const
bool IntersectionPoint (const TLine2< T > &OtherLine, TVector2< T > &IntersectionPointOut, T ParallelDotTolerance=TMathUtil< T >::ZeroTolerance) const
Calculate intersection point between this line and another one.
TVector2< T > NearestPoint (const TVector2< T > &QueryPoint) const
TVector2< T > PointAt (T LineParameter) const
T Project (const TVector2< T > &QueryPoint) const
int WhichSide (const TVector2< T > &QueryPoint, T OnLineTolerance=0) const
Static Public Member Functions
static TLine2< T > FromPoints (const TVector2< T > &Point0, const TVector2< T > &Point1)
Data Fields
TVector2< T > Direction
Direction of Line, Normalized.
TVector2< T > Origin
Origin / Center Point of Line.
Detailed Description
template<typename T>
struct UE::Geometry::TLine2< T >
TLine2 is a two-dimensional infinite line.
The line is stored in (Center,Direction) form.
Definition at line 22 of file LineTypes.h.
Constructor & Destructor Documentation
TLine2() [1/2]
template<typename T> UE::Geometry::TLine2< T >::TLine2 () inline
Construct default line along X axis.
Definition at line 33 of file LineTypes.h.
Referenced by UE::Geometry::TLine2< double >::FromPoints().
TLine2() [2/2]
template<typename T> UE::Geometry::TLine2< T >::TLine2 (const TVector2< T > & OriginIn, const TVector2< T > & DirectionIn) inline
Construct line with given Origin and Direction.
Definition at line 42 of file LineTypes.h.
Member Function Documentation
DistanceSquared()
template<typename T> T UE::Geometry::TLine2< T >::DistanceSquared (const TVector2< T > & QueryPoint) const inline
Returns
smallest squared distance from line to QueryPoint
Definition at line 77 of file LineTypes.h.
FromPoints()
template<typename T> TLine2< T > UE::Geometry::TLine2< T >::FromPoints (const TVector2< T > & Point0, const TVector2< T > & Point1) inline static
Returns
line between two points
Definition at line 51 of file LineTypes.h.
Referenced by UE::Geometry::TConvexHull2< float >::GetLine().
IntersectionPoint()
template<typename T> bool UE::Geometry::TLine2< T >::IntersectionPoint (const TLine2< T > & OtherLine, TVector2< T > & IntersectionPointOut, T ParallelDotTolerance = TMathUtil<T>::ZeroTolerance) const inline
Calculate intersection point between this line and another one.
Parameters
OtherLine line to test against
IntersectionPointOut intersection point is stored here, if found
ParallelDotTolerance tolerance used to determine if lines are parallel (and hence cannot intersect)
Returns
true if lines intersect and IntersectionPointOut was computed
Definition at line 115 of file LineTypes.h.
Referenced by UE::Geometry::TPolygon2< double >::PolyOffset().
NearestPoint()
template<typename T> TVector2< T > UE::Geometry::TLine2< T >::NearestPoint (const TVector2< T > & QueryPoint) const inline
Returns
nearest point on line to QueryPoint
Definition at line 87 of file LineTypes.h.
PointAt()
template<typename T> TVector2< T > UE::Geometry::TLine2< T >::PointAt (T LineParameter) const inline
Returns
point on line at given line parameter value (distance along line from origin)
Definition at line 60 of file LineTypes.h.
Project()
template<typename T> T UE::Geometry::TLine2< T >::Project (const TVector2< T > & QueryPoint) const inline
Returns
line parameter (ie distance from Origin) at nearest point on line to QueryPoint
Definition at line 69 of file LineTypes.h.
WhichSide()
template<typename T> int UE::Geometry::TLine2< T >::WhichSide (const TVector2< T > & QueryPoint, T OnLineTolerance = 0) const inline
Returns
+1 if QueryPoint is "right" of line, -1 if "left" or 0 if "on" line (up to given tolerance)
Definition at line 97 of file LineTypes.h.
Field Documentation
Direction
template<typename T> TVector2<T> UE::Geometry::TLine2< T >::Direction
Direction of Line, Normalized.
Definition at line 28 of file LineTypes.h.
Referenced by UE::Geometry::TLine2< double >::IntersectionPoint().
Origin
template<typename T> TVector2<T> UE::Geometry::TLine2< T >::Origin
Origin / Center Point of Line.
Definition at line 25 of file LineTypes.h.
Referenced by UE::Geometry::TLine2< double >::IntersectionPoint().
The documentation for this struct was generated from the following file:
Runtime/GeometryCore/Public/LineTypes.h