Unreal Engine 5.6 C++ API: FTickableObjectBase::FTickableStatics Struct Reference
FTickableObjectBase::FTickableStatics Struct Reference
Implementation struct for internals of ticking, there should be one instance of this for each direct subclass.
#include "Tickable.h"
Public Member Functions
void FinishTicking ()
Finishes ticking and handle cleanup for entries that were invalidated.
void QueueTickableObjectForAdd (FTickableObjectBase *InTickable)
Call from anywhere to lock and add to the new objects list.
void SetTickTypeForTickableObject (FTickableObjectBase *TickableObject, ETickableTickType NewTickType)
Call from anywhere to lock critical sections and set the tick type for an object which could modify both arrays.
void StartTicking ()
Call after locking TickableObjectsCritical to process the NewTickableObjects array and prepare for tick.
Data Fields
bool bIsTickingObjects = false
True if any of the tick arrays are being iterated.
bool bNeedsCleanup = false
True if any objects were deleted and this needs cleanup after tick.
TMap< FTickableObjectBase *, ETickableTickType > NewTickableObjects
Set of objects that have not yet been queried for tick type.
FTransactionallySafeCriticalSection NewTickableObjectsCritical
Lock for modifying new list, this is automatically acquired by functions below.
TArray< FTickableObjectBase::FTickableObjectEntry > TickableObjects
List of objects that are fully ticking.
FTransactionallySafeCriticalSection TickableObjectsCritical
This critical section should be locked during entire tick process.
Detailed Description
Implementation struct for internals of ticking, there should be one instance of this for each direct subclass.
Definition at line 50 of file Tickable.h.
Member Function Documentation
FinishTicking()
void FTickableObjectBase::FTickableStatics::FinishTicking ()
Finishes ticking and handle cleanup for entries that were invalidated.
QueueTickableObjectForAdd()
void FTickableObjectBase::FTickableStatics::QueueTickableObjectForAdd (FTickableObjectBase * InTickable)
Call from anywhere to lock and add to the new objects list.
Referenced by FTickableCookObject::FTickableCookObject(), and FTickableEditorObject::FTickableEditorObject().
SetTickTypeForTickableObject()
void FTickableObjectBase::FTickableStatics::SetTickTypeForTickableObject (FTickableObjectBase * TickableObject, ETickableTickType NewTickType)
Call from anywhere to lock critical sections and set the tick type for an object which could modify both arrays.
Referenced by FTickableCookObject::~FTickableCookObject(), and FTickableEditorObject::~FTickableEditorObject().
StartTicking()
void FTickableObjectBase::FTickableStatics::StartTicking ()
Call after locking TickableObjectsCritical to process the NewTickableObjects array and prepare for tick.
Field Documentation
bIsTickingObjects
bool FTickableObjectBase::FTickableStatics::bIsTickingObjects = false
True if any of the tick arrays are being iterated.
Definition at line 65 of file Tickable.h.
bNeedsCleanup
bool FTickableObjectBase::FTickableStatics::bNeedsCleanup = false
True if any objects were deleted and this needs cleanup after tick.
Definition at line 68 of file Tickable.h.
NewTickableObjects
TMap<FTickableObjectBase*, ETickableTickType> FTickableObjectBase::FTickableStatics::NewTickableObjects
Set of objects that have not yet been queried for tick type.
Definition at line 62 of file Tickable.h.
NewTickableObjectsCritical
FTransactionallySafeCriticalSection FTickableObjectBase::FTickableStatics::NewTickableObjectsCritical
Lock for modifying new list, this is automatically acquired by functions below.
Definition at line 59 of file Tickable.h.
TickableObjects
TArray<FTickableObjectBase::FTickableObjectEntry> FTickableObjectBase::FTickableStatics::TickableObjects
List of objects that are fully ticking.
Definition at line 56 of file Tickable.h.
TickableObjectsCritical
FTransactionallySafeCriticalSection FTickableObjectBase::FTickableStatics::TickableObjectsCritical
This critical section should be locked during entire tick process.
Definition at line 53 of file Tickable.h.
The documentation for this struct was generated from the following file:
Runtime/Engine/Public/Tickable.h