Unreal Engine 5.6 C++ API: FDriverDenyListEntry Struct Reference
FDriverDenyListEntry Struct Reference
#include "GenericPlatformDriver.h"
Data Structures
struct FDriverDateDenyListEntry
struct FDriverVersionDenyListEntry
Public Member Functions
FDriverDenyListEntry ()=default
FDriverDenyListEntry (const TCHAR *Entry)
bool AppliesToDriver (const FGPUDriverInfo &Info, uint32 &OutNumSatisfiedConstraints) const
bool AppliesToLatestDrivers ()
bool IsValid () const
Public Member Functions inherited from FDriverConfigEntryConstraints
FDriverConfigEntryConstraints ()=default
FDriverConfigEntryConstraints (const TCHAR *Entry)
bool AreConstraintsSatisfied (const FGPUDriverInfo &Info, uint32 &OutNumSatisfiedConstraints) const
bool HasConstraints ()
Data Fields
FString DenylistReason
TOptional< FDriverDateDenyListEntry > DriverDate
TOptional< FDriverVersionDenyListEntry > DriverVersion
Data Fields inherited from FDriverConfigEntryConstraints
TOptional< FRegexPattern > AdapterNameRegexConstraint
TOptional< FString > RHINameConstraint
Detailed Description
Definition at line 332 of file GenericPlatformDriver.h.
Constructor & Destructor Documentation
FDriverDenyListEntry() [1/2]
FDriverDenyListEntry::FDriverDenyListEntry () default
FDriverDenyListEntry() [2/2]
FDriverDenyListEntry::FDriverDenyListEntry (const TCHAR * Entry) inline
Definition at line 364 of file GenericPlatformDriver.h.
References FDriverConfigEntryConstraints::FDriverConfigEntryConstraints(), DenylistReason, DriverDate, DriverVersion, ensure, ensureMsgf, FDriverDenyListEntry::FDriverDateDenyListEntry::FromString(), FDriverDenyListEntry::FDriverVersionDenyListEntry::FromString(), IsValid(), TEXT, and FParse::Value().
Member Function Documentation
AppliesToDriver()
bool FDriverDenyListEntry::AppliesToDriver (const FGPUDriverInfo & Info, uint32 & OutNumSatisfiedConstraints) const inline
Definition at line 389 of file GenericPlatformDriver.h.
References FDriverConfigEntryConstraints::AreConstraintsSatisfied(), CompareWithOp(), DriverDate, DriverVersion, Info, IsValid(), and ParseMonthDayYearDate().
AppliesToLatestDrivers()
bool FDriverDenyListEntry::AppliesToLatestDrivers () inline
Definition at line 422 of file GenericPlatformDriver.h.
References DriverDate, DriverVersion, ECO_Greater, and ECO_GreaterOrEqual.
IsValid()
bool FDriverDenyListEntry::IsValid () const inline
Definition at line 435 of file GenericPlatformDriver.h.
References DriverDate, and DriverVersion.
Referenced by FDriverDenyListEntry(), and AppliesToDriver().
Field Documentation
DenylistReason
FString FDriverDenyListEntry::DenylistReason
Definition at line 443 of file GenericPlatformDriver.h.
Referenced by FDriverDenyListEntry().
DriverDate
TOptional<FDriverDateDenyListEntry> FDriverDenyListEntry::DriverDate
Definition at line 441 of file GenericPlatformDriver.h.
Referenced by FDriverDenyListEntry(), AppliesToDriver(), AppliesToLatestDrivers(), and IsValid().
DriverVersion
TOptional<FDriverVersionDenyListEntry> FDriverDenyListEntry::DriverVersion
Definition at line 440 of file GenericPlatformDriver.h.
Referenced by FDriverDenyListEntry(), AppliesToDriver(), AppliesToLatestDrivers(), and IsValid().
The documentation for this struct was generated from the following file:
Runtime/Core/Public/GenericPlatform/GenericPlatformDriver.h