Unreal Engine 5.6 C++ API: FBookmarkUI Struct Reference
FBookmarkUI Struct Reference
#include "BookmarkUI.h"
Static Public Member Functions
static FORCEINLINE FName GetClearCommandName (const int32 BookmarkIndex)
static FORCEINLINE FText GetClearLabel (const int32 BookmarkIndex)
static FORCEINLINE FText GetClearTooltip (const int32 BookmarkIndex)
static FORCEINLINE FSlateIcon GetDefaultIcon ()
static FORCEINLINE FName GetJumpToCommandName (const int32 BookmarkIndex)
static FORCEINLINE FText GetJumpToLabel (const int32 BookmarkIndex)
static FORCEINLINE FText GetJumpToTooltip (const int32 BookmarkIndex)
static FORCEINLINE FText GetPlainLabel (const int32 BookmarkIndex)
static FORCEINLINE FName GetSetCommandName (const int32 BookmarkIndex)
static FORCEINLINE FText GetSetLabel (const int32 BookmarkIndex)
static FORCEINLINE FText GetSetTooltip (const int32 BookmarkIndex)
Detailed Description
Definition at line 9 of file BookmarkUI.h.
Member Function Documentation
GetClearCommandName()
FORCEINLINE FName FBookmarkUI::GetClearCommandName (const int32 BookmarkIndex) inline static
Definition at line 51 of file BookmarkUI.h.
References FName, FORCEINLINE, and TEXT.
GetClearLabel()
FORCEINLINE FText FBookmarkUI::GetClearLabel (const int32 BookmarkIndex) inline static
Definition at line 61 of file BookmarkUI.h.
References FText::AsNumber(), FORCEINLINE, FText::Format(), and NSLOCTEXT.
GetClearTooltip()
FORCEINLINE FText FBookmarkUI::GetClearTooltip (const int32 BookmarkIndex) inline static
Definition at line 56 of file BookmarkUI.h.
References FText::AsNumber(), FORCEINLINE, FText::Format(), and NSLOCTEXT.
GetDefaultIcon()
FORCEINLINE FSlateIcon FBookmarkUI::GetDefaultIcon () inline static
Definition at line 11 of file BookmarkUI.h.
References FORCEINLINE.
GetJumpToCommandName()
FORCEINLINE FName FBookmarkUI::GetJumpToCommandName (const int32 BookmarkIndex) inline static
Definition at line 16 of file BookmarkUI.h.
References FName, FORCEINLINE, and TEXT.
GetJumpToLabel()
FORCEINLINE FText FBookmarkUI::GetJumpToLabel (const int32 BookmarkIndex) inline static
Definition at line 26 of file BookmarkUI.h.
References FText::AsNumber(), FORCEINLINE, FText::Format(), and NSLOCTEXT.
GetJumpToTooltip()
FORCEINLINE FText FBookmarkUI::GetJumpToTooltip (const int32 BookmarkIndex) inline static
Definition at line 21 of file BookmarkUI.h.
References FText::AsNumber(), FORCEINLINE, FText::Format(), and NSLOCTEXT.
GetPlainLabel()
FORCEINLINE FText FBookmarkUI::GetPlainLabel (const int32 BookmarkIndex) inline static
Definition at line 31 of file BookmarkUI.h.
References FText::AsNumber(), FORCEINLINE, FText::Format(), and NSLOCTEXT.
GetSetCommandName()
FORCEINLINE FName FBookmarkUI::GetSetCommandName (const int32 BookmarkIndex) inline static
Definition at line 36 of file BookmarkUI.h.
References FName, FORCEINLINE, and TEXT.
GetSetLabel()
FORCEINLINE FText FBookmarkUI::GetSetLabel (const int32 BookmarkIndex) inline static
Definition at line 46 of file BookmarkUI.h.
References FText::AsNumber(), FORCEINLINE, FText::Format(), and NSLOCTEXT.
GetSetTooltip()
FORCEINLINE FText FBookmarkUI::GetSetTooltip (const int32 BookmarkIndex) inline static
Definition at line 41 of file BookmarkUI.h.
References FText::AsNumber(), FORCEINLINE, FText::Format(), and NSLOCTEXT.
The documentation for this struct was generated from the following file:
Editor/UnrealEd/Public/Bookmarks/BookmarkUI.h