Unreal Engine 5.6 C++ API: FMaterialShaderTypes Struct Reference
FMaterialShaderTypes Struct Reference
#include "MaterialShaderType.h"
Public Member Functions
FMaterialShaderTypes ()
const FShaderType * AddShaderType (const FShaderType *InType, int32 InPermutationId=0)
template<typename ShaderType>
const FShaderType * AddShaderType (int32 InPermutationId=0)
Data Fields
int32 PermutationId [SF_NumFrequencies]
const FShaderPipelineType * PipelineType
const FShaderType * ShaderType [SF_NumFrequencies]
Detailed Description
Definition at line 204 of file MaterialShaderType.h.
Constructor & Destructor Documentation
FMaterialShaderTypes()
FMaterialShaderTypes::FMaterialShaderTypes () inline
Definition at line 210 of file MaterialShaderType.h.
References FMemory::Memzero(), PermutationId, PipelineType, and ShaderType.
Member Function Documentation
AddShaderType() [1/2]
const FShaderType * FMaterialShaderTypes::AddShaderType (const FShaderType * InType, int32 InPermutationId = 0) inline
Definition at line 212 of file MaterialShaderType.h.
References check, Frequency, FShaderType::GetFrequency(), PermutationId, and ShaderType.
Referenced by AddShaderType().
AddShaderType() [2/2]
template<typename ShaderType> const FShaderType * FMaterialShaderTypes::AddShaderType (int32 InPermutationId = 0) inline
Definition at line 222 of file MaterialShaderType.h.
References AddShaderType().
Field Documentation
PermutationId
int32 FMaterialShaderTypes::PermutationId[SF_NumFrequencies]
Definition at line 208 of file MaterialShaderType.h.
Referenced by FMaterialShaderTypes(), and AddShaderType().
PipelineType
const FShaderPipelineType* FMaterialShaderTypes::PipelineType
Definition at line 206 of file MaterialShaderType.h.
Referenced by FMaterialShaderTypes().
ShaderType
const FShaderType* FMaterialShaderTypes::ShaderType[SF_NumFrequencies]
Definition at line 207 of file MaterialShaderType.h.
Referenced by FMaterialShaderTypes(), and AddShaderType().
The documentation for this struct was generated from the following file:
Runtime/Engine/Public/MaterialShaderType.h