Unreal Engine 5.6 C++ API: FRemoteObjectId Struct Reference
FRemoteObjectId Struct Reference
#include "RemoteObjectTypes.h"
Public Member Functions
FRemoteObjectId ()=default
FRemoteObjectId (const UObjectBase *InObject)
FRemoteObjectId (FRemoteServerId InServerId, uint64 InSerialNumber)
FORCEINLINE uint64 GetIdNumber () const
FORCEINLINE FRemoteServerId GetServerId () const
FORCEINLINE uint32 GetTypeHash () const
FORCEINLINE bool IsAsset () const
FORCEINLINE bool IsValid () const
FORCEINLINE bool operator!= (const FRemoteObjectId &Other) const
FORCEINLINE bool operator< (const FRemoteObjectId &Other) const
FORCEINLINE bool operator<= (const FRemoteObjectId &Other) const
FORCEINLINE bool operator== (const FRemoteObjectId &Other) const
FORCEINLINE bool operator> (const FRemoteObjectId &Other) const
FORCEINLINE bool operator>= (const FRemoteObjectId &Other) const
FString ToString () const
Static Public Member Functions
static FRemoteObjectId Generate (UObjectBase *InObject, EInternalObjectFlags InInitialFlags=EInternalObjectFlags::None)
Private Attributes
union {
struct {
uint64 SerialNumber: 54
uint64 ServerId: 10
}
uint64 Id = 0
};
Friends
FArchive & operator<< (FArchive &Ar, FRemoteObjectId &Id)
Detailed Description
Definition at line 99 of file RemoteObjectTypes.h.
Constructor & Destructor Documentation
FRemoteObjectId() [1/3]
FRemoteObjectId::FRemoteObjectId () default
Referenced by Generate(), IsValid(), operator!=(), operator<(), operator<<, operator<=(), operator==(), operator>(), and operator>=().
FRemoteObjectId() [2/3]
FRemoteObjectId::FRemoteObjectId (FRemoteServerId InServerId, uint64 InSerialNumber) inline
Definition at line 116 of file RemoteObjectTypes.h.
References Id, SerialNumber, and ServerId.
FRemoteObjectId() [3/3]
FRemoteObjectId::FRemoteObjectId (const UObjectBase * InObject) explicit
Member Function Documentation
Generate()
FRemoteObjectId FRemoteObjectId::Generate (UObjectBase * InObject, EInternalObjectFlags InInitialFlags = EInternalObjectFlags::None) static
References FRemoteObjectId(), and None.
GetIdNumber()
FORCEINLINE uint64 FRemoteObjectId::GetIdNumber () const inline
Definition at line 158 of file RemoteObjectTypes.h.
References FORCEINLINE, and Id.
GetServerId()
FORCEINLINE FRemoteServerId FRemoteObjectId::GetServerId () const inline
Definition at line 163 of file RemoteObjectTypes.h.
References FORCEINLINE, Invalid, and ServerId.
Referenced by IsAsset().
GetTypeHash()
FORCEINLINE uint32 FRemoteObjectId::GetTypeHash () const inline
Definition at line 124 of file RemoteObjectTypes.h.
References FORCEINLINE, and Id.
IsAsset()
FORCEINLINE bool FRemoteObjectId::IsAsset () const inline
Definition at line 168 of file RemoteObjectTypes.h.
References FORCEINLINE, GetServerId(), and FRemoteServerId::IsAsset().
IsValid()
FORCEINLINE bool FRemoteObjectId::IsValid () const inline
Definition at line 153 of file RemoteObjectTypes.h.
References FRemoteObjectId(), and FORCEINLINE.
operator!=()
FORCEINLINE bool FRemoteObjectId::operator!= (const FRemoteObjectId & Other) const inline
Definition at line 133 of file RemoteObjectTypes.h.
References FRemoteObjectId(), FORCEINLINE, Id, and Other.
operator<()
FORCEINLINE bool FRemoteObjectId::operator< (const FRemoteObjectId & Other) const inline
Definition at line 137 of file RemoteObjectTypes.h.
References FRemoteObjectId(), FORCEINLINE, Id, and Other.
operator<=()
FORCEINLINE bool FRemoteObjectId::operator<= (const FRemoteObjectId & Other) const inline
Definition at line 141 of file RemoteObjectTypes.h.
References FRemoteObjectId(), FORCEINLINE, Id, and Other.
operator==()
FORCEINLINE bool FRemoteObjectId::operator== (const FRemoteObjectId & Other) const inline
Definition at line 129 of file RemoteObjectTypes.h.
References FRemoteObjectId(), FORCEINLINE, Id, and Other.
operator>()
FORCEINLINE bool FRemoteObjectId::operator> (const FRemoteObjectId & Other) const inline
Definition at line 145 of file RemoteObjectTypes.h.
References FRemoteObjectId(), FORCEINLINE, Id, and Other.
operator>=()
FORCEINLINE bool FRemoteObjectId::operator>= (const FRemoteObjectId & Other) const inline
Definition at line 149 of file RemoteObjectTypes.h.
References FRemoteObjectId(), FORCEINLINE, Id, and Other.
ToString()
FString FRemoteObjectId::ToString () const
Friends And Related Symbol Documentation
operator<<
FArchive & operator<< (FArchive & Ar, FRemoteObjectId & Id) friend
References FRemoteObjectId(), Ar, and Id.
Field Documentation
[union]
union { ... } FRemoteObjectId
Id
uint64 FRemoteObjectId::Id = 0
Definition at line 109 of file RemoteObjectTypes.h.
Referenced by FRemoteObjectId(), GetIdNumber(), GetTypeHash(), operator!=(), operator<(), operator<<, operator<=(), operator==(), operator>(), and operator>=().
SerialNumber
uint64 FRemoteObjectId::SerialNumber
Definition at line 106 of file RemoteObjectTypes.h.
Referenced by FRemoteObjectId().
ServerId
uint64 FRemoteObjectId::ServerId
Definition at line 107 of file RemoteObjectTypes.h.
Referenced by FRemoteObjectId(), and GetServerId().
The documentation for this struct was generated from the following file:
Runtime/CoreUObject/Public/UObject/RemoteObjectTypes.h