Unreal Engine 5.6 C++ API: UE::Transaction::FSerializedObject Struct Reference
UE::Transaction::FSerializedObject Struct Reference
#include "TransactionCommon.h"
Public Member Functions
void Reset ()
void Swap (FSerializedObject &Other)
Data Fields
TArray< FName > ReferencedNames
Names referenced by the transacted object.
TArray< FPersistentObjectRef > ReferencedObjects
External objects referenced by the transacted object.
FSerializedObjectData SerializedData
The serialized data for the transacted object.
Detailed Description
Definition at line 223 of file TransactionCommon.h.
Member Function Documentation
Reset()
void UE::Transaction::FSerializedObject::Reset () inline
Definition at line 226 of file TransactionCommon.h.
References ReferencedNames, ReferencedObjects, and SerializedData.
Referenced by FTransaction::FObjectRecord::FSerializedObject::Reset().
Swap()
void UE::Transaction::FSerializedObject::Swap (FSerializedObject & Other) inline
Definition at line 233 of file TransactionCommon.h.
References Exchange(), Other, ReferencedNames, ReferencedObjects, and SerializedData.
Referenced by FTransaction::FObjectRecord::FSerializedObject::Swap().
Field Documentation
ReferencedNames
TArray<FName> UE::Transaction::FSerializedObject::ReferencedNames
Names referenced by the transacted object.
Definition at line 247 of file TransactionCommon.h.
Referenced by Reset(), and Swap().
ReferencedObjects
TArray<FPersistentObjectRef> UE::Transaction::FSerializedObject::ReferencedObjects
External objects referenced by the transacted object.
Definition at line 244 of file TransactionCommon.h.
Referenced by Reset(), and Swap().
SerializedData
FSerializedObjectData UE::Transaction::FSerializedObject::SerializedData
The serialized data for the transacted object.
Definition at line 241 of file TransactionCommon.h.
Referenced by Reset(), and Swap().
The documentation for this struct was generated from the following file:
Runtime/Engine/Public/TransactionCommon.h