Unreal Engine 5.6 C++ API: UE::Anim::FNamedValueArrayUtils Struct Reference
UE::Anim::FNamedValueArrayUtils Struct Reference
#include "NamedValueArray.h"
Static Public Member Functions
template<typename AllocatorType0, typename ElementType0, typename AllocatorType1, typename ElementType1, typename ValuePredicateType>
static void Intersection (const TNamedValueArray< AllocatorType0, ElementType0 > &InNamedValues0, const TNamedValueArray< AllocatorType1, ElementType1 > &InNamedValues1, ValuePredicateType InValuePredicate)
Calls predicate on all matching elements in the two passed-in value arrays.
template<typename AllocatorType0, typename ElementType0, typename AllocatorType1, typename ElementType1, typename PredicateType>
static void RemoveByPredicate (TNamedValueArray< AllocatorType0, ElementType0 > &InOutValueArray0, const TNamedValueArray< AllocatorType1, ElementType1 > &InValueArray1, PredicateType InPredicate)
Removes elements in InOutValueArray0 that match InValueArray1 if predicate returns false.
template<typename PredicateType, typename AllocatorType0, typename ElementType0, typename AllocatorType1, typename ElementType1>
static void Union (const TNamedValueArray< AllocatorType0, ElementType0 > &InValueArray0, const TNamedValueArray< AllocatorType1, ElementType1 > &InValueArray1, PredicateType InPredicate)
template<typename AllocatorTypeResult, typename ElementType, typename AllocatorTypeParam>
static void Union (TNamedValueArray< AllocatorTypeResult, ElementType > &InOutValueArray0, const TNamedValueArray< AllocatorTypeParam, ElementType > &InValueArray1)
template<typename PredicateType, typename AllocatorTypeResult, typename ElementTypeResult, typename AllocatorTypeParam, typename ElementTypeParam>
static void Union (TNamedValueArray< AllocatorTypeResult, ElementTypeResult > &InOutValueArray0, const TNamedValueArray< AllocatorTypeParam, ElementTypeParam > &InValueArray1, PredicateType InPredicate)
template<typename PredicateType, typename AllocatorTypeResult, typename ElementTypeResult, typename AllocatorType0, typename ElementType0, typename AllocatorType1, typename ElementType1>
static void Union (TNamedValueArray< AllocatorTypeResult, ElementTypeResult > &OutResultValueArray, const TNamedValueArray< AllocatorType0, ElementType0 > &InValueArray0, const TNamedValueArray< AllocatorType1, ElementType1 > &InValueArray1, PredicateType InPredicate)
Detailed Description
Definition at line 251 of file NamedValueArray.h.
Member Function Documentation
Intersection()
template<typename AllocatorType0, typename ElementType0, typename AllocatorType1, typename ElementType1, typename ValuePredicateType> void UE::Anim::FNamedValueArrayUtils::Intersection (const TNamedValueArray< AllocatorType0, ElementType0 > & InNamedValues0, const TNamedValueArray< AllocatorType1, ElementType1 > & InNamedValues1, ValuePredicateType InValuePredicate) inline static
Calls predicate on all matching elements in the two passed-in value arrays.
ValuePredicateType is a function of signature: (const ElementType0& InElement0, const ElementType1& InElement1) -> void
Definition at line 642 of file NamedValueArray.h.
References checkSlow, CURVE_PROFILE_CYCLE_COUNTER, UE::Anim::TNamedValueArray< InAllocatorType, InElementType >::Elements, UE::Anim::TNamedValueArray< InAllocatorType, InElementType >::Num(), RESTRICT, and UE::Anim::TNamedValueArray< InAllocatorType, InElementType >::SortElementsIfRequired().
Referenced by UE::Anim::FCurveUtils::BulkGet().
RemoveByPredicate()
template<typename AllocatorType0, typename ElementType0, typename AllocatorType1, typename ElementType1, typename PredicateType> void UE::Anim::FNamedValueArrayUtils::RemoveByPredicate (TNamedValueArray< AllocatorType0, ElementType0 > & InOutValueArray0, const TNamedValueArray< AllocatorType1, ElementType1 > & InValueArray1, PredicateType InPredicate) inline static
Removes elements in InOutValueArray0 that match InValueArray1 if predicate returns false.
Definition at line 705 of file NamedValueArray.h.
References checkSlow, UE::Anim::TNamedValueArray< InAllocatorType, InElementType >::CheckSorted(), CURVE_PROFILE_CYCLE_COUNTER, UE::Anim::TNamedValueArray< InAllocatorType, InElementType >::Elements, No, UE::Anim::TNamedValueArray< InAllocatorType, InElementType >::Num(), TArray< InElementType, InAllocatorType >::RemoveAt(), RESTRICT, and UE::Anim::TNamedValueArray< InAllocatorType, InElementType >::SortElementsIfRequired().
Union() [1/4]
template<typename PredicateType, typename AllocatorType0, typename ElementType0, typename AllocatorType1, typename ElementType1> void UE::Anim::FNamedValueArrayUtils::Union (const TNamedValueArray< AllocatorType0, ElementType0 > & InValueArray0, const TNamedValueArray< AllocatorType1, ElementType1 > & InValueArray1, PredicateType InPredicate) inline static
Definition at line 556 of file NamedValueArray.h.
References UE::Anim::BothArgsValid, checkSlow, CURVE_PROFILE_CYCLE_COUNTER, UE::Anim::TNamedValueArray< InAllocatorType, InElementType >::Elements, UE::Anim::TNamedValueArray< InAllocatorType, InElementType >::Num(), RESTRICT, UE::Anim::TNamedValueArray< InAllocatorType, InElementType >::SortElementsIfRequired(), UE::Anim::ValidArg0, and UE::Anim::ValidArg1.
Union() [2/4]
template<typename AllocatorTypeResult, typename ElementType, typename AllocatorTypeParam> void UE::Anim::FNamedValueArrayUtils::Union (TNamedValueArray< AllocatorTypeResult, ElementType > & InOutValueArray0, const TNamedValueArray< AllocatorTypeParam, ElementType > & InValueArray1) inline static
Definition at line 382 of file NamedValueArray.h.
References UE::Anim::TNamedValueArray< InAllocatorType, InElementType >::bSorted, UE::Anim::TNamedValueArray< InAllocatorType, InElementType >::Elements, EnumHasAnyFlags(), UE::Anim::TNamedValueArray< InAllocatorType, InElementType >::Num(), Union(), and UE::Anim::ValidArg1.
Union() [3/4]
template<typename PredicateType, typename AllocatorTypeResult, typename ElementTypeResult, typename AllocatorTypeParam, typename ElementTypeParam> void UE::Anim::FNamedValueArrayUtils::Union (TNamedValueArray< AllocatorTypeResult, ElementTypeResult > & InOutValueArray0, const TNamedValueArray< AllocatorTypeParam, ElementTypeParam > & InValueArray1, PredicateType InPredicate) inline static
Definition at line 261 of file NamedValueArray.h.
References TArray< InElementType, InAllocatorType >::AddUninitialized(), UE::Anim::BothArgsValid, check, UE::Anim::TNamedValueArray< InAllocatorType, InElementType >::CheckSorted(), CURVE_PROFILE_CYCLE_COUNTER, UE::Anim::TNamedValueArray< InAllocatorType, InElementType >::Elements, TArray< InElementType, InAllocatorType >::GetData(), TArray< InElementType, InAllocatorType >::InsertUninitialized(), FMath::Max, TArray< InElementType, InAllocatorType >::Num(), UE::Anim::TNamedValueArray< InAllocatorType, InElementType >::Num(), TArray< InElementType, InAllocatorType >::Reserve(), UE::Anim::TNamedValueArray< InAllocatorType, InElementType >::Reserve(), RESTRICT, UE::Anim::TNamedValueArray< InAllocatorType, InElementType >::SortElementsIfRequired(), UE_PTRDIFF_TO_INT32, UE::Anim::ValidArg0, and UE::Anim::ValidArg1.
Referenced by TBaseBlendedCurve< InAllocatorType, InElementType >::Accumulate(), UE::Anim::FCurveUtils::BulkSet(), TBaseBlendedCurve< InAllocatorType, InElementType >::Combine(), TBaseBlendedCurve< InAllocatorType, InElementType >::CombinePreserved(), TBaseBlendedCurve< InAllocatorType, InElementType >::ConvertToAdditive(), TBaseBlendedCurve< InAllocatorType, InElementType >::CopyFrom(), TBaseBlendedCurve< InAllocatorType, InElementType >::Lerp(), TBaseBlendedCurve< InAllocatorType, InElementType >::LerpTo(), TBaseBlendedCurve< InAllocatorType, InElementType >::LerpToValid(), TBaseBlendedCurve< InAllocatorType, InElementType >::LerpValid(), Union(), TBaseBlendedCurve< InAllocatorType, InElementType >::UseMaxValue(), and TBaseBlendedCurve< InAllocatorType, InElementType >::UseMinValue().
Union() [4/4]
template<typename PredicateType, typename AllocatorTypeResult, typename ElementTypeResult, typename AllocatorType0, typename ElementType0, typename AllocatorType1, typename ElementType1> void UE::Anim::FNamedValueArrayUtils::Union (TNamedValueArray< AllocatorTypeResult, ElementTypeResult > & OutResultValueArray, const TNamedValueArray< AllocatorType0, ElementType0 > & InValueArray0, const TNamedValueArray< AllocatorType1, ElementType1 > & InValueArray1, PredicateType InPredicate) inline static
Definition at line 407 of file NamedValueArray.h.
References TArray< InElementType, InAllocatorType >::Add(), TArray< InElementType, InAllocatorType >::AddUninitialized(), UE::Anim::BothArgsValid, UE::Anim::TNamedValueArray< InAllocatorType, InElementType >::bSorted, check, UE::Anim::TNamedValueArray< InAllocatorType, InElementType >::CheckSorted(), CURVE_PROFILE_CYCLE_COUNTER, UE::Anim::TNamedValueArray< InAllocatorType, InElementType >::Elements, TArray< InElementType, InAllocatorType >::GetData(), FMath::Max, MoveTemp(), TArray< InElementType, InAllocatorType >::Num(), UE::Anim::TNamedValueArray< InAllocatorType, InElementType >::Num(), TArray< InElementType, InAllocatorType >::Reserve(), UE::Anim::TNamedValueArray< InAllocatorType, InElementType >::Reserve(), TArray< InElementType, InAllocatorType >::Reset(), RESTRICT, UE::Anim::TNamedValueArray< InAllocatorType, InElementType >::SortElementsIfRequired(), UE::Anim::ValidArg0, and UE::Anim::ValidArg1.
The documentation for this struct was generated from the following file:
Runtime/Engine/Public/Animation/NamedValueArray.h