Unreal Engine 5.6 C++ API: FConstStructView Struct Reference
FConstStructView Struct Reference
FConstStructView is "typed" struct pointer, it contains const pointer to struct plus UScriptStruct pointer.
#include "StructView.h"
Public Member Functions
FConstStructView ()=default
FConstStructView (const FConstSharedStruct &SharedStruct)
FConstStructView (const FInstancedStruct &InstancedStruct)
FConstStructView (const FSharedStruct &SharedStruct)
FConstStructView (const FStructView StructView)
FConstStructView (const UScriptStruct *InScriptStruct, const uint8 *InStructMemory=nullptr)
template<typename T>
constexpr TEnableIf< TIsConst< T >::Value, T & >::Type Get () const
Returns const reference to the struct, this getter assumes that all data is valid.
const uint8 * GetMemory () const
Returns const pointer to struct memory.
template<typename T>
constexpr TEnableIf< TIsConst< T >::Value, T * >::Type GetPtr () const
Returns const pointer to the struct, or nullptr if cast is not valid.
const UScriptStruct * GetScriptStruct () const
Returns struct type.
bool IsValid () const
Returns True if the struct is valid.
template<typename OtherType>
bool operator!= (const OtherType &Other) const
template<typename OtherType>
bool operator== (const OtherType &Other) const
Comparison operators.
void Reset ()
Reset to empty.
void SetStructData (const UScriptStruct *InScriptStruct, const uint8 *InStructMemory)
Static Public Member Functions
template<typename T>
static FConstStructView Make (const T &Struct)
Creates a new FConstStructView from the templated struct.
Protected Attributes
const UScriptStruct * ScriptStruct = nullptr
const uint8 * StructMemory = nullptr
Detailed Description
FConstStructView is "typed" struct pointer, it contains const pointer to struct plus UScriptStruct pointer.
FConstStructView does not own the memory and will not free it when of scope. It should be only used to pass struct pointer in a limited scope, or when the user controls the lifetime of the struct being stored. E.g. instead of passing ref or pointer to a FInstancedStruct, you should use FConstStructView or FStructView to pass around a view to the contents. FConstStructView is passed by value. FConstStructView is similar to FStructOnScope, but FConstStructView is a view only (FStructOnScope can either own the memory or be a view) FConstStructView prevents mutation of the actual struct data however the struct being pointed at can be changed to point at a different instance of a struct. To also prevent this use const FConstStructView. e.g. FStructView A; FConstStructView B = A; // compiles e.g. FStructView A; FConstStructView B; B = A; // compiles as B can be made to point at any other StructView e.g. FConstStructView A; FStructView B = A; // doesn't compile as the struct data for A is immutable (but mutable for B) e.g. FStructView A; A.Foo = NewVal; // compiles as the struct data for A is mutable. e.g. FConstStructView A; A.Foo = NewVal; // doesn't compile as the struct data for A is immutable. e.g. FStructView A; const FStructView B; A = B; // compiles as the struct B is pointing to can't be made to point at something else but A isn't const. e.g. const FStructView A; FStructView B; A = B; // doesn't compile as attempting to make const view point at something else
Definition at line 202 of file StructView.h.
Constructor & Destructor Documentation
FConstStructView() [1/6]
FConstStructView::FConstStructView () default
Referenced by FConstStructView(), FConstStructView(), FConstStructView(), FConstStructView(), TConstStructView< BaseStructT >::TConstStructView(), TConstStructView< BaseStructT >::TConstStructView(), TConstStructView< BaseStructT >::TConstStructView(), TConstStructView< BaseStructT >::TConstStructView(), TConstStructView< BaseStructT >::TConstStructView(), TConstStructView< BaseStructT >::TConstStructView(), and Make().
FConstStructView() [2/6]
FConstStructView::FConstStructView (const UScriptStruct * InScriptStruct, const uint8 * InStructMemory = nullptr) inline
Definition at line 208 of file StructView.h.
References ScriptStruct, and StructMemory.
FConstStructView() [3/6]
FConstStructView::FConstStructView (const FInstancedStruct & InstancedStruct) inline
Definition at line 213 of file StructView.h.
References FConstStructView(), GetMemory(), and GetScriptStruct().
FConstStructView() [4/6]
FConstStructView::FConstStructView (const FSharedStruct & SharedStruct) inline
Definition at line 217 of file StructView.h.
References FConstStructView(), GetMemory(), and GetScriptStruct().
FConstStructView() [5/6]
FConstStructView::FConstStructView (const FConstSharedStruct & SharedStruct) inline
Definition at line 221 of file StructView.h.
References FConstStructView(), GetMemory(), and GetScriptStruct().
FConstStructView() [6/6]
FConstStructView::FConstStructView (const FStructView StructView) inline
Definition at line 225 of file StructView.h.
References FConstStructView(), GetMemory(), and GetScriptStruct().
Member Function Documentation
Get()
template<typename T> TEnableIf< TIsConst< T >::Value, T & >::Type FConstStructView::Get () const inline constexpr
Returns const reference to the struct, this getter assumes that all data is valid.
Definition at line 240 of file StructView.h.
References UE::StructUtils::GetStructRef(), ScriptStruct, and StructMemory.
GetMemory()
const uint8 * FConstStructView::GetMemory () const inline
Returns const pointer to struct memory.
Definition at line 259 of file StructView.h.
References StructMemory.
Referenced by FConstStructView(), FConstStructView(), FConstStructView(), FConstStructView(), TConstStructView< BaseStructT >::TConstStructView(), TConstStructView< BaseStructT >::TConstStructView(), TConstStructView< BaseStructT >::TConstStructView(), TConstStructView< BaseStructT >::TConstStructView(), and TInstancedStruct< BaseStructT >::TInstancedStruct().
GetPtr()
template<typename T> TEnableIf< TIsConst< T >::Value, T * >::Type FConstStructView::GetPtr () const inline constexpr
Returns const pointer to the struct, or nullptr if cast is not valid.
Definition at line 247 of file StructView.h.
References UE::StructUtils::GetStructPtr(), ScriptStruct, and StructMemory.
GetScriptStruct()
const UScriptStruct * FConstStructView::GetScriptStruct () const inline
Returns struct type.
Definition at line 253 of file StructView.h.
References ScriptStruct.
Referenced by FConstStructView(), FConstStructView(), FConstStructView(), FConstStructView(), TConstStructView< BaseStructT >::TConstStructView(), TConstStructView< BaseStructT >::TConstStructView(), TConstStructView< BaseStructT >::TConstStructView(), TConstStructView< BaseStructT >::TConstStructView(), TInstancedStruct< BaseStructT >::TInstancedStruct(), and USTRUCT().
IsValid()
bool FConstStructView::IsValid () const inline
Returns True if the struct is valid.
Definition at line 272 of file StructView.h.
References ScriptStruct, and StructMemory.
Make()
template<typename T> FConstStructView FConstStructView::Make (const T & Struct) inline static
Creates a new FConstStructView from the templated struct.
Definition at line 232 of file StructView.h.
References FConstStructView(), UE::StructUtils::CheckStructType(), TBaseStructureBase< T, bHasStaticStruct >::Get(), and Struct.
Referenced by FPropertyBagSetRef::AddValueStruct(), and FPropertyBagArrayRef::SetValueStruct().
operator!=()
template<typename OtherType> bool FConstStructView::operator!= (const OtherType & Other) const inline
Definition at line 285 of file StructView.h.
References operator==(), and Other.
operator==()
template<typename OtherType> bool FConstStructView::operator== (const OtherType & Other) const inline
Comparison operators.
Note: it does not compare the internal structure itself
Definition at line 279 of file StructView.h.
References Other, ScriptStruct, and StructMemory.
Reset()
void FConstStructView::Reset () inline
Reset to empty.
Definition at line 265 of file StructView.h.
References ScriptStruct, and StructMemory.
SetStructData()
void FConstStructView::SetStructData (const UScriptStruct * InScriptStruct, const uint8 * InStructMemory) inline
Definition at line 290 of file StructView.h.
References ScriptStruct, and StructMemory.
Referenced by USTRUCT().
Field Documentation
ScriptStruct
const UScriptStruct* FConstStructView::ScriptStruct = nullptr protected
Definition at line 297 of file StructView.h.
Referenced by FConstStructView(), Get(), TConstStructView< BaseStructT >::Get(), GetPtr(), TConstStructView< BaseStructT >::GetPtr(), GetScriptStruct(), IsValid(), operator==(), TConstStructView< BaseStructT >::operator==(), Reset(), and SetStructData().
StructMemory
const uint8* FConstStructView::StructMemory = nullptr protected
Definition at line 298 of file StructView.h.
Referenced by FConstStructView(), Get(), TConstStructView< BaseStructT >::Get(), GetMemory(), GetPtr(), TConstStructView< BaseStructT >::GetPtr(), IsValid(), operator==(), TConstStructView< BaseStructT >::operator==(), Reset(), and SetStructData().
The documentation for this struct was generated from the following file:
Runtime/CoreUObject/Public/StructUtils/StructView.h