Unreal Engine 5.6 C++ API: FOverridableReplayVersionData Struct Reference
FOverridableReplayVersionData Struct Reference
#include "ReplayTypes.h"
Public Member Functions
FOverridableReplayVersionData (const FNetworkDemoHeader &DemoHeader)
FOverridableReplayVersionData (const FOverridableReplayVersionData &)=default
PRAGMA_DISABLE_DEPRECATION_WARNINGS FOverridableReplayVersionData (FOverridableReplayVersionData &&)=default
void ApplyVersionDataToDemoHeader (FNetworkDemoHeader &DemoHeader)
PRAGMA_ENABLE_DEPRECATION_WARNINGS uint32 GetCustomVersion (const FGuid &VersionGuid) const
FOverridableReplayVersionData & operator= (const FOverridableReplayVersionData &)=default
FOverridableReplayVersionData & operator= (FOverridableReplayVersionData &&)=default
UE_DEPRECATED (5.2, "No longer used in favor of CustomVersions") uint32 EngineNetworkProtocolVersion
UE_DEPRECATED (5.2, "No longer used in favor of CustomVersions") uint32 GameNetworkProtocolVersion
UE_DEPRECATED (5.2, "No longer used in favor of CustomVersions") uint32 Version
Data Fields
FCustomVersionContainer CustomVersions
FEngineVersion EngineVersion
int32 PackageVersionLicenseeUE
FPackageFileVersion PackageVersionUE
Detailed Description
Definition at line 510 of file ReplayTypes.h.
Constructor & Destructor Documentation
FOverridableReplayVersionData() [1/3]
PRAGMA_DISABLE_DEPRECATION_WARNINGS FOverridableReplayVersionData::FOverridableReplayVersionData (FOverridableReplayVersionData &&) default
References FOverridableReplayVersionData().
Referenced by FOverridableReplayVersionData(), FOverridableReplayVersionData(), FOverridableReplayVersionData(), operator=(), and operator=().
FOverridableReplayVersionData() [2/3]
FOverridableReplayVersionData::FOverridableReplayVersionData (const FOverridableReplayVersionData &) default
References FOverridableReplayVersionData().
FOverridableReplayVersionData() [3/3]
FOverridableReplayVersionData::FOverridableReplayVersionData (const FNetworkDemoHeader & DemoHeader) inline
Definition at line 532 of file ReplayTypes.h.
References FOverridableReplayVersionData(), CustomVersions, EngineVersion, PackageVersionLicenseeUE, and PackageVersionUE.
Member Function Documentation
ApplyVersionDataToDemoHeader()
void FOverridableReplayVersionData::ApplyVersionDataToDemoHeader (FNetworkDemoHeader & DemoHeader) inline
Definition at line 544 of file ReplayTypes.h.
References FNetworkDemoHeader::CustomVersions, CustomVersions, FNetworkDemoHeader::EngineVersion, EngineVersion, FNetworkDemoHeader::PackageVersionLicenseeUE, PackageVersionLicenseeUE, FNetworkDemoHeader::PackageVersionUE, and PackageVersionUE.
GetCustomVersion()
PRAGMA_ENABLE_DEPRECATION_WARNINGS uint32 FOverridableReplayVersionData::GetCustomVersion (const FGuid & VersionGuid) const
operator=() [1/2]
FOverridableReplayVersionData & FOverridableReplayVersionData::operator= (const FOverridableReplayVersionData &) default
References FOverridableReplayVersionData().
operator=() [2/2]
FOverridableReplayVersionData & FOverridableReplayVersionData::operator= (FOverridableReplayVersionData &&) default
References FOverridableReplayVersionData().
UE_DEPRECATED() [1/3]
FOverridableReplayVersionData::UE_DEPRECATED (5. 2, "No longer used in favor of CustomVersions")
References UE_DEPRECATED().
UE_DEPRECATED() [2/3]
FOverridableReplayVersionData::UE_DEPRECATED (5. 2, "No longer used in favor of CustomVersions")
References UE_DEPRECATED().
UE_DEPRECATED() [3/3]
FOverridableReplayVersionData::UE_DEPRECATED (5. 2, "No longer used in favor of CustomVersions")
Referenced by UE_DEPRECATED(), and UE_DEPRECATED().
Field Documentation
CustomVersions
FCustomVersionContainer FOverridableReplayVersionData::CustomVersions
Definition at line 520 of file ReplayTypes.h.
Referenced by FOverridableReplayVersionData(), and ApplyVersionDataToDemoHeader().
EngineVersion
FEngineVersion FOverridableReplayVersionData::EngineVersion
Definition at line 521 of file ReplayTypes.h.
Referenced by FOverridableReplayVersionData(), and ApplyVersionDataToDemoHeader().
PackageVersionLicenseeUE
int32 FOverridableReplayVersionData::PackageVersionLicenseeUE
Definition at line 523 of file ReplayTypes.h.
Referenced by FOverridableReplayVersionData(), and ApplyVersionDataToDemoHeader().
PackageVersionUE
FPackageFileVersion FOverridableReplayVersionData::PackageVersionUE
Definition at line 522 of file ReplayTypes.h.
Referenced by FOverridableReplayVersionData(), and ApplyVersionDataToDemoHeader().
The documentation for this struct was generated from the following file:
Runtime/Engine/Public/ReplayTypes.h