Unreal Engine 5.6 C++ API: FRigVMCompilerWorkData::FFunctionRegisterData Struct Reference
FRigVMCompilerWorkData::FFunctionRegisterData Struct Reference
#include "RigVMCompiler.h"
Public Member Functions
bool operator== (const FFunctionRegisterData &Other) const
Data Fields
ERigVMMemoryType MemoryType = ERigVMMemoryType::Invalid
TSoftObjectPtr< URigVMFunctionReferenceNode > ReferenceNode
int32 RegisterIndex = 0
Friends
uint32 GetTypeHash (const FFunctionRegisterData &Data)
Detailed Description
Definition at line 165 of file RigVMCompiler.h.
Member Function Documentation
operator==()
bool FRigVMCompilerWorkData::FFunctionRegisterData::operator== (const FFunctionRegisterData & Other) const inline
Definition at line 177 of file RigVMCompiler.h.
References MemoryType, Other, ReferenceNode, and RegisterIndex.
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FFunctionRegisterData & Data) friend
Definition at line 171 of file RigVMCompiler.h.
References GetTypeHash, GetTypeHash(), HashCombine(), MemoryType, ReferenceNode, RegisterIndex, TSoftObjectPtr< T >::ToSoftObjectPath(), and FSoftObjectPath::ToString().
Referenced by GetTypeHash.
Field Documentation
MemoryType
ERigVMMemoryType FRigVMCompilerWorkData::FFunctionRegisterData::MemoryType = ERigVMMemoryType::Invalid
Definition at line 168 of file RigVMCompiler.h.
Referenced by GetTypeHash, and operator==().
ReferenceNode
TSoftObjectPtr<URigVMFunctionReferenceNode> FRigVMCompilerWorkData::FFunctionRegisterData::ReferenceNode
Definition at line 167 of file RigVMCompiler.h.
Referenced by GetTypeHash, and operator==().
RegisterIndex
int32 FRigVMCompilerWorkData::FFunctionRegisterData::RegisterIndex = 0
Definition at line 169 of file RigVMCompiler.h.
Referenced by GetTypeHash, and operator==().
The documentation for this struct was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/RigVM/Source/RigVMDeveloper/Public/RigVMCompiler/RigVMCompiler.h