Unreal Engine 5.6 C++ API: FEdGraphSchemaAction_Dummy Struct Reference
FEdGraphSchemaAction_Dummy Struct Reference
Action to add a node to the graph.
#include "EdGraphSchema.h"
Public Member Functions
FEdGraphSchemaAction_Dummy ()
FEdGraphSchemaAction_Dummy (FText InNodeCategory, FText InMenuDesc, FText InToolTip, const int32 InGrouping)
virtual FName GetTypeId () const override
Static Public Member Functions
static FName StaticGetTypeId ()
Detailed Description
Action to add a node to the graph.
Dummy action, useful for putting messages in the menu
Definition at line 399 of file EdGraphSchema.h.
Constructor & Destructor Documentation
FEdGraphSchemaAction_Dummy() [1/2]
FEdGraphSchemaAction_Dummy::FEdGraphSchemaAction_Dummy () inline
Definition at line 404 of file EdGraphSchema.h.
FEdGraphSchemaAction_Dummy() [2/2]
FEdGraphSchemaAction_Dummy::FEdGraphSchemaAction_Dummy (FText InNodeCategory, FText InMenuDesc, FText InToolTip, const int32 InGrouping) inline
Definition at line 408 of file EdGraphSchema.h.
References MoveTemp().
Member Function Documentation
GetTypeId()
virtual FName FEdGraphSchemaAction_Dummy::GetTypeId () const inline override virtual
Definition at line 402 of file EdGraphSchema.h.
References StaticGetTypeId().
StaticGetTypeId()
FName FEdGraphSchemaAction_Dummy::StaticGetTypeId () inline static
Definition at line 401 of file EdGraphSchema.h.
Referenced by GetTypeId(), and SRigVMActionMenu::OnActionSelected().
The documentation for this struct was generated from the following file:
Runtime/Engine/Classes/EdGraph/EdGraphSchema.h