Unreal Engine 5.6 C++ API: FAnimatedPropertyKey Struct Reference
FAnimatedPropertyKey Struct Reference
#include "AnimatedPropertyKey.h"
Static Public Member Functions
static FAnimatedPropertyKey FromObjectType (const UClass *Class)
static FAnimatedPropertyKey FromProperty (const FProperty *Property)
static FAnimatedPropertyKey FromPropertyType (TSubclassOfField< FProperty > PropertyType)
static FAnimatedPropertyKey FromPropertyTypeName (FName PropertyTypeName)
static FAnimatedPropertyKey FromStructType (const UStruct *Struct)
static FAnimatedPropertyKey FromStructType (FName StructName)
Data Fields
FName ObjectTypeName
The name of the type of object that can be animated inside the property (i.e.
FName PropertyTypeName
The name of the type of property that can be animated (i.e.
Private Member Functions
FAnimatedPropertyKey ()
Friends
uint32 GetTypeHash (FAnimatedPropertyKey InKey)
bool operator== (FAnimatedPropertyKey A, FAnimatedPropertyKey B)
Detailed Description
Definition at line 9 of file AnimatedPropertyKey.h.
Constructor & Destructor Documentation
FAnimatedPropertyKey()
FAnimatedPropertyKey::FAnimatedPropertyKey () inline private
Definition at line 96 of file AnimatedPropertyKey.h.
References ObjectTypeName, and PropertyTypeName.
Referenced by FromObjectType(), FromProperty(), FromPropertyType(), FromPropertyTypeName(), FromStructType(), FromStructType(), GetTypeHash, and operator==.
Member Function Documentation
FromObjectType()
FAnimatedPropertyKey FAnimatedPropertyKey::FromObjectType (const UClass * Class) inline static
Definition at line 58 of file AnimatedPropertyKey.h.
References FAnimatedPropertyKey(), Class, ObjectTypeName, and PropertyTypeName.
FromProperty()
FAnimatedPropertyKey FAnimatedPropertyKey::FromProperty (const FProperty * Property) inline static
Definition at line 31 of file AnimatedPropertyKey.h.
References FAnimatedPropertyKey(), ArrayProperty, CastField(), ObjectProperty, ObjectTypeName, Property, PropertyTypeName, and StructProperty.
FromPropertyType()
FAnimatedPropertyKey FAnimatedPropertyKey::FromPropertyType (TSubclassOfField< FProperty > PropertyType) inline static
Definition at line 87 of file AnimatedPropertyKey.h.
References FAnimatedPropertyKey(), FFieldClass::GetFName(), and PropertyTypeName.
FromPropertyTypeName()
FAnimatedPropertyKey FAnimatedPropertyKey::FromPropertyTypeName (FName PropertyTypeName) inline static
Definition at line 80 of file AnimatedPropertyKey.h.
References FAnimatedPropertyKey(), and PropertyTypeName.
Referenced by FPropertyTrackEditor< TrackType >::AddWatchedPropertyType(), and FBoolPropertyTrackEditor::GetAnimatedPropertyTypes().
FromStructType() [1/2]
FAnimatedPropertyKey FAnimatedPropertyKey::FromStructType (const UStruct * Struct) inline static
Definition at line 66 of file AnimatedPropertyKey.h.
References FAnimatedPropertyKey(), check, FromStructType(), and Struct.
Referenced by FromStructType().
FromStructType() [2/2]
FAnimatedPropertyKey FAnimatedPropertyKey::FromStructType (FName StructName) inline static
Definition at line 72 of file AnimatedPropertyKey.h.
References FAnimatedPropertyKey(), ObjectTypeName, and PropertyTypeName.
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (FAnimatedPropertyKey InKey) friend
Definition at line 21 of file AnimatedPropertyKey.h.
References FAnimatedPropertyKey(), GetTypeHash, ObjectTypeName, and PropertyTypeName.
Referenced by GetTypeHash.
operator==
bool operator== (FAnimatedPropertyKey A, FAnimatedPropertyKey B) friend
Definition at line 26 of file AnimatedPropertyKey.h.
References FAnimatedPropertyKey(), A, and B.
Field Documentation
ObjectTypeName
FName FAnimatedPropertyKey::ObjectTypeName
The name of the type of object that can be animated inside the property (i.e.
the name of the struct or object for FStructProperty or FObjectProperty). NAME_None for any properties.
Definition at line 19 of file AnimatedPropertyKey.h.
Referenced by FAnimatedPropertyKey(), FromObjectType(), FromProperty(), FromStructType(), and GetTypeHash.
PropertyTypeName
FName FAnimatedPropertyKey::PropertyTypeName
The name of the type of property that can be animated (i.e.
FBoolProperty)
Definition at line 14 of file AnimatedPropertyKey.h.
Referenced by FAnimatedPropertyKey(), FromObjectType(), FromProperty(), FromPropertyType(), FromPropertyTypeName(), FromStructType(), and GetTypeHash.
The documentation for this struct was generated from the following file:
Editor/Sequencer/Public/AnimatedPropertyKey.h