Unreal Engine 5.6 C++ API: TSlateDecl< WidgetType, RequiredArgsPayloadType > Struct Template Reference
TSlateDecl< WidgetType, RequiredArgsPayloadType > Struct Template Reference
Utility class used during widget instantiation.
#include "DeclarativeSyntaxSupport.h"
Public Member Functions
TSlateDecl (const ANSICHAR *InType, const ANSICHAR *InFile, int32 OnLine, RequiredArgsPayloadType &&InRequiredArgs)
template<class ExposeAsWidgetType>
TSlateDecl && Expose (TSharedPtr< ExposeAsWidgetType > &OutVarToInit) &&
Initialize OutVarToInit with the widget that is being constructed.
template<class ExposeAsWidgetType>
TSlateDecl && Expose (TSharedRef< ExposeAsWidgetType > &OutVarToInit) &&
Initialize OutVarToInit with the widget that is being constructed.
template<class ExposeAsWidgetType>
TSlateDecl && Expose (TWeakPtr< ExposeAsWidgetType > &OutVarToInit) &&
Initialize a WEAK OutVarToInit with the widget that is being constructed.
TSharedRef< WidgetType > operator<<= (const typename WidgetType::FArguments &InArgs) &&
Complete widget construction from InArgs.
Data Fields
RequiredArgsPayloadType & _RequiredArgs
TSharedPtr< WidgetType > _Widget
Detailed Description
template<class WidgetType, typename RequiredArgsPayloadType>
struct TSlateDecl< WidgetType, RequiredArgsPayloadType >
Utility class used during widget instantiation.
Performs widget allocation and construction. Ensures that debug info is set correctly. Returns TSharedRef to widget.
See also
SNew
SAssignNew
Definition at line 903 of file DeclarativeSyntaxSupport.h.
Constructor & Destructor Documentation
TSlateDecl()
template<class WidgetType, typename RequiredArgsPayloadType> TSlateDecl< WidgetType, RequiredArgsPayloadType >::TSlateDecl (const ANSICHAR * InType, const ANSICHAR * InFile, int32 OnLine, RequiredArgsPayloadType && InRequiredArgs) inline
SUserWidgets are allocated in the corresponding CPP file, so that the implementer can return an implementation that differs from the public interface.
See also
SUserWidgetExample
Normal widgets are allocated directly by the TSlateDecl.
Definition at line 905 of file DeclarativeSyntaxSupport.h.
References TSlateDecl(), _RequiredArgs, _Widget, and MakeShared().
Referenced by TSlateDecl(), Expose(), Expose(), and Expose().
Member Function Documentation
Expose() [1/3]
template<class WidgetType, typename RequiredArgsPayloadType> template<class ExposeAsWidgetType> TSlateDecl && TSlateDecl< WidgetType, RequiredArgsPayloadType >::Expose (TSharedPtr< ExposeAsWidgetType > & OutVarToInit) && inline
Initialize OutVarToInit with the widget that is being constructed.
See also
SAssignNew
Definition at line 931 of file DeclarativeSyntaxSupport.h.
References TSlateDecl(), _Widget, and MoveTemp().
Expose() [2/3]
template<class WidgetType, typename RequiredArgsPayloadType> template<class ExposeAsWidgetType> TSlateDecl && TSlateDecl< WidgetType, RequiredArgsPayloadType >::Expose (TSharedRef< ExposeAsWidgetType > & OutVarToInit) && inline
Initialize OutVarToInit with the widget that is being constructed.
See also
SAssignNew
Definition at line 943 of file DeclarativeSyntaxSupport.h.
References TSlateDecl(), _Widget, and MoveTemp().
Expose() [3/3]
template<class WidgetType, typename RequiredArgsPayloadType> template<class ExposeAsWidgetType> TSlateDecl && TSlateDecl< WidgetType, RequiredArgsPayloadType >::Expose (TWeakPtr< ExposeAsWidgetType > & OutVarToInit) && inline
Initialize a WEAK OutVarToInit with the widget that is being constructed.
See also
SAssignNew
Definition at line 955 of file DeclarativeSyntaxSupport.h.
References TSlateDecl(), _Widget, and MoveTemp().
operator<<=()
template<class WidgetType, typename RequiredArgsPayloadType> TSharedRef< WidgetType > TSlateDecl< WidgetType, RequiredArgsPayloadType >::operator<<= (const typename WidgetType::FArguments & InArgs) && inline
Complete widget construction from InArgs.
Parameters
InArgs NamedArguments from which to construct the widget.
Returns
A reference to the widget that we constructed.
Definition at line 955 of file DeclarativeSyntaxSupport.h.
Field Documentation
_RequiredArgs
template<class WidgetType, typename RequiredArgsPayloadType> RequiredArgsPayloadType& TSlateDecl< WidgetType, RequiredArgsPayloadType >::_RequiredArgs
Definition at line 980 of file DeclarativeSyntaxSupport.h.
Referenced by TSlateDecl().
_Widget
template<class WidgetType, typename RequiredArgsPayloadType> TSharedPtr<WidgetType> TSlateDecl< WidgetType, RequiredArgsPayloadType >::_Widget
Definition at line 979 of file DeclarativeSyntaxSupport.h.
Referenced by TSlateDecl(), Expose(), Expose(), and Expose().
The documentation for this struct was generated from the following file:
Runtime/SlateCore/Public/Widgets/DeclarativeSyntaxSupport.h