Unreal Engine 5.6 C++ API: FFrameNumber Struct Reference
FFrameNumber Struct Reference
Typesafe 32-bit signed frame number.
#include "FrameNumber.h"
Public Member Functions
constexpr FFrameNumber ()
template<typename T, typename U = typename TEnableIf<std::is_same_v<T, int32>>::Type>
constexpr FFrameNumber (T InValue)
Implicit construction from a signed integer frame number, whilst disallowing any construction from other types.
FFrameNumber & operator%= (FFrameNumber RHS)
FFrameNumber & operator++ ()
FFrameNumber operator++ (int32)
FFrameNumber & operator+= (FFrameNumber RHS)
FFrameNumber & operator-- ()
FFrameNumber operator-- (int32)
FFrameNumber & operator-= (FFrameNumber RHS)
bool Serialize (FArchive &Ar)
Data Fields
int32 Value
The value of the frame number.
Friends
uint32 GetTypeHash (FFrameNumber A)
bool operator!= (FFrameNumber A, FFrameNumber B)
FFrameNumber operator% (FFrameNumber A, FFrameNumber B)
FFrameNumber operator* (FFrameNumber A, float Scalar)
FFrameNumber operator+ (FFrameNumber A, FFrameNumber B)
FFrameNumber operator- (FFrameNumber A)
FFrameNumber operator- (FFrameNumber A, FFrameNumber B)
FFrameNumber operator/ (FFrameNumber A, float Scalar)
bool operator< (FFrameNumber A, FFrameNumber B)
FArchive & operator<< (FArchive &Ar, FFrameNumber &FrameNumber)
Serializes the given FrameNumber from or into the specified archive.
bool operator<= (FFrameNumber A, FFrameNumber B)
bool operator== (FFrameNumber A, FFrameNumber B)
bool operator> (FFrameNumber A, FFrameNumber B)
bool operator>= (FFrameNumber A, FFrameNumber B)
Detailed Description
Typesafe 32-bit signed frame number.
Defined in this way to prevent erroneous float->int conversions and afford type-safe operator overloading.
Definition at line 17 of file FrameNumber.h.
Constructor & Destructor Documentation
FFrameNumber() [1/2]
FFrameNumber::FFrameNumber () inline constexpr
Definition at line 19 of file FrameNumber.h.
References Value.
Referenced by GetTypeHash, operator!=, operator%, operator%=(), operator*, operator+, operator++(), operator++(), operator+=(), operator-, operator-, operator--(), operator--(), operator-=(), operator/, operator<, operator<<, operator<=, operator==, operator>, and operator>=.
FFrameNumber() [2/2]
template<typename T, typename U = typename TEnableIf<std::is_same_v<T, int32>>::Type> FFrameNumber::FFrameNumber (T InValue) inline constexpr
Implicit construction from a signed integer frame number, whilst disallowing any construction from other types.
Definition at line 27 of file FrameNumber.h.
References Value.
Member Function Documentation
operator%=()
FFrameNumber & FFrameNumber::operator%= (FFrameNumber RHS) inline
Definition at line 44 of file FrameNumber.h.
References FFrameNumber(), and Value.
operator++() [1/2]
FFrameNumber & FFrameNumber::operator++ () inline
Definition at line 46 of file FrameNumber.h.
References FFrameNumber(), and Value.
operator++() [2/2]
FFrameNumber FFrameNumber::operator++ (int32) inline
Definition at line 49 of file FrameNumber.h.
References FFrameNumber(), and Value.
operator+=()
FFrameNumber & FFrameNumber::operator+= (FFrameNumber RHS) inline
Definition at line 42 of file FrameNumber.h.
References FFrameNumber(), and Value.
operator--() [1/2]
FFrameNumber & FFrameNumber::operator-- () inline
Definition at line 47 of file FrameNumber.h.
References FFrameNumber(), and Value.
operator--() [2/2]
FFrameNumber FFrameNumber::operator-- (int32) inline
Definition at line 50 of file FrameNumber.h.
References FFrameNumber(), and Value.
operator-=()
FFrameNumber & FFrameNumber::operator-= (FFrameNumber RHS) inline
Definition at line 43 of file FrameNumber.h.
References FFrameNumber(), and Value.
Serialize()
bool FFrameNumber::Serialize (FArchive & Ar)
References Ar.
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (FFrameNumber A) friend
Definition at line 69 of file FrameNumber.h.
References FFrameNumber(), and A.
operator!=
bool operator!= (FFrameNumber A, FFrameNumber B) friend
Definition at line 53 of file FrameNumber.h.
References FFrameNumber(), A, and B.
operator%
FFrameNumber operator% (FFrameNumber A, FFrameNumber B) friend
Definition at line 62 of file FrameNumber.h.
References FFrameNumber(), A, and B.
operator*
FFrameNumber operator* (FFrameNumber A, float Scalar) friend
Definition at line 66 of file FrameNumber.h.
References FFrameNumber(), A, and FMath::Clamp().
operator+
FFrameNumber operator+ (FFrameNumber A, FFrameNumber B) friend
Definition at line 60 of file FrameNumber.h.
References FFrameNumber(), A, and B.
operator- [1/2]
FFrameNumber operator- (FFrameNumber A) friend
Definition at line 64 of file FrameNumber.h.
References FFrameNumber(), and A.
operator- [2/2]
FFrameNumber operator- (FFrameNumber A, FFrameNumber B) friend
Definition at line 61 of file FrameNumber.h.
References FFrameNumber(), A, and B.
operator/
FFrameNumber operator/ (FFrameNumber A, float Scalar) friend
Definition at line 67 of file FrameNumber.h.
References FFrameNumber(), A, and FMath::Clamp().
operator<
bool operator< (FFrameNumber A, FFrameNumber B) friend
Definition at line 55 of file FrameNumber.h.
References FFrameNumber(), A, and B.
operator<<
FArchive & operator<< (FArchive & Ar, FFrameNumber & FrameNumber) friend
Serializes the given FrameNumber from or into the specified archive.
Parameters
Ar The archive to serialize from or into.
FrameNumber The bound to serialize.
Returns
The archive used for serialization.
References FFrameNumber(), and Ar.
operator<=
bool operator<= (FFrameNumber A, FFrameNumber B) friend
Definition at line 57 of file FrameNumber.h.
References FFrameNumber(), A, and B.
operator==
bool operator== (FFrameNumber A, FFrameNumber B) friend
Definition at line 52 of file FrameNumber.h.
References FFrameNumber(), A, and B.
operator>
bool operator> (FFrameNumber A, FFrameNumber B) friend
Definition at line 56 of file FrameNumber.h.
References FFrameNumber(), A, and B.
operator>=
bool operator>= (FFrameNumber A, FFrameNumber B) friend
Definition at line 58 of file FrameNumber.h.
References FFrameNumber(), A, and B.
Field Documentation
Value
int32 FFrameNumber::Value
The value of the frame number.
Definition at line 77 of file FrameNumber.h.
Referenced by FFrameNumber(), FFrameNumber(), FFrameRate::AsFrameTime(), FFrameRate::AsSeconds(), UE::MovieScene::Interpolation::FCachedInterpolationRange::Clamp(), ConvertFrameTime(), UE::MovieScene::DiscreteSize(), FTimecode::FromFrameNumber(), TSubSectionMixin< ParentSectionClass >::GetSectionToolTip(), operator%=(), operator++(), operator++(), operator+=(), FFrameTime::operator+=, operator--(), operator--(), operator-=(), FFrameTime::operator-=, DisplayClusterTypesConverter::ToString(), and FTimecode::ToTimespan().
The documentation for this struct was generated from the following file:
Runtime/Core/Public/Misc/FrameNumber.h