Unreal Engine 5.6 C++ API: UE::AnimNext::IHierarchy Struct Reference
UE::AnimNext::IHierarchy Struct Reference
IHierarchy.
#include "IHierarchy.h"
Public Member Functions
DECLARE_ANIM_TRAIT_INTERFACE (IHierarchy) ANIMNEXTANIMGRAPH_API virtual uint32 GetNumChildren(const FExecutionContext &Context
virtual ANIMNEXTANIMGRAPH_API void GetChildren (const FExecutionContext &Context, const TTraitBinding< IHierarchy > &Binding, FChildrenArray &Children) const
virtual ANIMNEXTANIMGRAPH_API const FText & GetDisplayName () const override
virtual ANIMNEXTANIMGRAPH_API const FText & GetDisplayShortName () const override
Public Member Functions inherited from UE::AnimNext::ITraitInterface
virtual ~ITraitInterface ()
virtual FTraitInterfaceUID GetInterfaceUID () const
virtual bool IsInternal () const
Static Public Member Functions
template<class TraitInterface>
static bool GetForwardedStackInterface (const FExecutionContext &Context, const FTraitBinding &Binding, FTraitStackBinding &OutStackBinding, TTraitBinding< TraitInterface > &OutBinding)
template<class TraitInterface>
static bool GetForwardedStackInterface (const FExecutionContext &Context, const FTraitStackBinding &StackBinding, FTraitStackBinding &OutStackBinding, TTraitBinding< TraitInterface > &OutBinding)
static uint32 GetNumStackChildren (const FExecutionContext &Context, const FTraitBinding &Binding)
static ANIMNEXTANIMGRAPH_API uint32 GetNumStackChildren (const FExecutionContext &Context, const FTraitStackBinding &Binding)
static void GetStackChildren (const FExecutionContext &Context, const FTraitBinding &Binding, FChildrenArray &Children)
static ANIMNEXTANIMGRAPH_API void GetStackChildren (const FExecutionContext &Context, const FTraitStackBinding &Binding, FChildrenArray &Children)
Data Fields
const TTraitBinding< IHierarchy > &Binding const
Static Private Member Functions
static ANIMNEXTANIMGRAPH_API FWeakTraitPtr GetStackForwardingChild (const FExecutionContext &Context, const FTraitStackBinding &Binding)
Additional Inherited Members
Static Public Attributes inherited from UE::AnimNext::ITraitInterface
static constexpr FTraitInterfaceUID InterfaceUID = FTraitInterfaceUID::MakeUID(TEXT("ITraitInterface"))
Detailed Description
IHierarchy.
This interface exposes hierarchy traversal information to navigate the graph.
Definition at line 22 of file IHierarchy.h.
Member Function Documentation
DECLARE_ANIM_TRAIT_INTERFACE()
UE::AnimNext::IHierarchy::DECLARE_ANIM_TRAIT_INTERFACE (IHierarchy) const &
GetChildren()
virtual ANIMNEXTANIMGRAPH_API void UE::AnimNext::IHierarchy::GetChildren (const FExecutionContext & Context, const TTraitBinding< IHierarchy > & Binding, FChildrenArray & Children) const virtual
Reimplemented in UE::AnimNext::FBlendStackCoreTrait, and UE::AnimNext::FRigLogicTrait.
References const, and GetChildren().
Referenced by GetChildren().
GetDisplayName()
virtual ANIMNEXTANIMGRAPH_API const FText & UE::AnimNext::IHierarchy::GetDisplayName () const override virtual
Reimplemented from UE::AnimNext::ITraitInterface.
GetDisplayShortName()
virtual ANIMNEXTANIMGRAPH_API const FText & UE::AnimNext::IHierarchy::GetDisplayShortName () const override virtual
Reimplemented from UE::AnimNext::ITraitInterface.
GetForwardedStackInterface() [1/2]
template<class TraitInterface> bool UE::AnimNext::IHierarchy::GetForwardedStackInterface (const FExecutionContext & Context, const FTraitBinding & Binding, FTraitStackBinding & OutStackBinding, TTraitBinding< TraitInterface > & OutBinding) inline static
Definition at line 74 of file IHierarchy.h.
References GetForwardedStackInterface(), UE::AnimNext::FTraitBinding::GetStack(), and UE::AnimNext::FTraitBinding::IsValid().
GetForwardedStackInterface() [2/2]
template<class TraitInterface> bool UE::AnimNext::IHierarchy::GetForwardedStackInterface (const FExecutionContext & Context, const FTraitStackBinding & StackBinding, FTraitStackBinding & OutStackBinding, TTraitBinding< TraitInterface > & OutBinding) inline static
Definition at line 50 of file IHierarchy.h.
References const, ensure, GetForwardedStackInterface(), GetStackForwardingChild(), and UE::AnimNext::FWeakTraitPtr::IsValid().
Referenced by GetForwardedStackInterface(), and GetForwardedStackInterface().
GetNumStackChildren() [1/2]
uint32 UE::AnimNext::IHierarchy::GetNumStackChildren (const FExecutionContext & Context, const FTraitBinding & Binding) inline static
Definition at line 124 of file IHierarchy.h.
References GetNumStackChildren(), UE::AnimNext::FTraitBinding::GetStack(), and UE::AnimNext::FTraitBinding::IsValid().
GetNumStackChildren() [2/2]
ANIMNEXTANIMGRAPH_API uint32 UE::AnimNext::IHierarchy::GetNumStackChildren (const FExecutionContext & Context, const FTraitStackBinding & Binding) static
References const, and GetNumStackChildren().
Referenced by GetNumStackChildren(), and GetNumStackChildren().
GetStackChildren() [1/2]
void UE::AnimNext::IHierarchy::GetStackChildren (const FExecutionContext & Context, const FTraitBinding & Binding, FChildrenArray & Children) inline static
Definition at line 116 of file IHierarchy.h.
References UE::AnimNext::FTraitBinding::GetStack(), GetStackChildren(), and UE::AnimNext::FTraitBinding::IsValid().
GetStackChildren() [2/2]
ANIMNEXTANIMGRAPH_API void UE::AnimNext::IHierarchy::GetStackChildren (const FExecutionContext & Context, const FTraitStackBinding & Binding, FChildrenArray & Children) static
References const, and GetStackChildren().
Referenced by GetStackChildren(), and GetStackChildren().
GetStackForwardingChild()
ANIMNEXTANIMGRAPH_API FWeakTraitPtr UE::AnimNext::IHierarchy::GetStackForwardingChild (const FExecutionContext & Context, const FTraitStackBinding & Binding) static private
Referenced by GetForwardedStackInterface().
Field Documentation
const
const TTraitBinding<IHierarchy>& Binding UE::AnimNext::IHierarchy::const
Definition at line 28 of file IHierarchy.h.
Referenced by GetChildren(), GetForwardedStackInterface(), GetNumStackChildren(), and GetStackChildren().
The documentation for this struct was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Experimental/AnimNextAnimGraph/Source/AnimNextAnimGraph/Public/TraitInterfaces/IHierarchy.h