Unreal Engine 5.6 C++ API: FSlateVectorGraphicsCache::FVectorCacheKey Struct Reference
FSlateVectorGraphicsCache::FVectorCacheKey Struct Reference
Public Member Functions
FVectorCacheKey (FName InBrushName, FVector2f LocalSize, float DrawScale)
bool operator== (const FVectorCacheKey &Other) const
Data Fields
FName BrushName
FIntPoint PixelSize
Private Attributes
uint32 KeyHash
Friends
uint32 GetTypeHash (const FVectorCacheKey &Key)
Detailed Description
Definition at line 43 of file SlateVectorGraphicsCache.h.
Constructor & Destructor Documentation
FVectorCacheKey()
FSlateVectorGraphicsCache::FVectorCacheKey::FVectorCacheKey (FName InBrushName, FVector2f LocalSize, float DrawScale) inline
Definition at line 48 of file SlateVectorGraphicsCache.h.
References BrushName, GetTypeHash, HashCombine(), IntPoint, KeyHash, and PixelSize.
Referenced by GetTypeHash, and operator==().
Member Function Documentation
operator==()
bool FSlateVectorGraphicsCache::FVectorCacheKey::operator== (const FVectorCacheKey & Other) const inline
Definition at line 55 of file SlateVectorGraphicsCache.h.
References FVectorCacheKey(), BrushName, Other, and PixelSize.
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FVectorCacheKey & Key) friend
Definition at line 61 of file SlateVectorGraphicsCache.h.
References FVectorCacheKey(), and Key.
Referenced by FVectorCacheKey().
Field Documentation
BrushName
FName FSlateVectorGraphicsCache::FVectorCacheKey::BrushName
Definition at line 45 of file SlateVectorGraphicsCache.h.
Referenced by FVectorCacheKey(), and operator==().
KeyHash
uint32 FSlateVectorGraphicsCache::FVectorCacheKey::KeyHash private
Definition at line 67 of file SlateVectorGraphicsCache.h.
Referenced by FVectorCacheKey().
PixelSize
FIntPoint FSlateVectorGraphicsCache::FVectorCacheKey::PixelSize
Definition at line 46 of file SlateVectorGraphicsCache.h.
Referenced by FVectorCacheKey(), and operator==().
The documentation for this struct was generated from the following file:
Runtime/SlateCore/Public/Rendering/SlateVectorGraphicsCache.h