Unreal Engine 5.6 C++ API: Audio::FQuartzClockTickRate Struct Reference
Audio::FQuartzClockTickRate Struct Reference
#include "QuartzQuantizationUtilities.h"
Public Member Functions
FQuartzClockTickRate ()
double GetBeatsPerMinute () const
double GetFramesPerDuration (EQuartzCommandQuantization InDuration) const
double GetFramesPerDuration (EQuartzTimeSignatureQuantization InDuration) const
double GetFramesPerTick () const
double GetMillisecondsPerTick () const
double GetSampleRate () const
double GetSecondsPerTick () const
double GetThirtySecondNotesPerMinute () const
bool IsSameTickRate (const FQuartzClockTickRate &Other, bool bAccountForDifferentSampleRates=true) const
bool IsValid (int32 InEventResolutionThreshold=1) const
void SetBeatsPerMinute (double InNewBeatsPerMinute)
void SetFramesPerTick (int32 InNewFramesPerTick)
void SetMillisecondsPerTick (double InNewMillisecondsPerTick)
void SetSampleRate (double InNewSampleRate)
void SetSecondsPerTick (double InNewSecondsPerTick)
void SetThirtySecondNotesPerMinute (double InNewThirtySecondNotesPerMinute)
Private Member Functions
void RecalculateDurationsBasedOnFramesPerTick ()
Private Attributes
double BeatsPerMinute { 0.0 }
double FramesPerTick { 1.0 }
double MillisecondsPerTick { 1.0 }
double SampleRate { 44100.0 }
double SecondsPerTick { 1.0 }
double ThirtySecondNotesPerMinute { 1.0 }
Detailed Description
Definition at line 282 of file QuartzQuantizationUtilities.h.
Constructor & Destructor Documentation
FQuartzClockTickRate()
Audio::FQuartzClockTickRate::FQuartzClockTickRate ()
Definition at line 239 of file QuartzQuantizationUtilities.cpp.
References SetBeatsPerMinute().
Referenced by IsSameTickRate().
Member Function Documentation
GetBeatsPerMinute()
double Audio::FQuartzClockTickRate::GetBeatsPerMinute () const inline
Definition at line 311 of file QuartzQuantizationUtilities.h.
References BeatsPerMinute.
GetFramesPerDuration() [1/2]
double Audio::FQuartzClockTickRate::GetFramesPerDuration (EQuartzCommandQuantization InDuration) const
Definition at line 293 of file QuartzQuantizationUtilities.cpp.
References checkf, FramesPerTick, INVALID_DURATION, and TEXT.
Referenced by GetFramesPerDuration(), and Audio::FQuartzOffset::GetOffsetInAudioFrames().
GetFramesPerDuration() [2/2]
double Audio::FQuartzClockTickRate::GetFramesPerDuration (EQuartzTimeSignatureQuantization InDuration) const
Definition at line 364 of file QuartzQuantizationUtilities.cpp.
References checkf, GetFramesPerDuration(), INVALID_DURATION, and TEXT.
GetFramesPerTick()
double Audio::FQuartzClockTickRate::GetFramesPerTick () const inline
Definition at line 303 of file QuartzQuantizationUtilities.h.
References FramesPerTick.
GetMillisecondsPerTick()
double Audio::FQuartzClockTickRate::GetMillisecondsPerTick () const inline
Definition at line 305 of file QuartzQuantizationUtilities.h.
References MillisecondsPerTick.
GetSampleRate()
double Audio::FQuartzClockTickRate::GetSampleRate () const inline
Definition at line 313 of file QuartzQuantizationUtilities.h.
References SampleRate.
Referenced by Audio::FQuartzOffset::GetOffsetInAudioFrames().
GetSecondsPerTick()
double Audio::FQuartzClockTickRate::GetSecondsPerTick () const inline
Definition at line 307 of file QuartzQuantizationUtilities.h.
References SecondsPerTick.
GetThirtySecondNotesPerMinute()
double Audio::FQuartzClockTickRate::GetThirtySecondNotesPerMinute () const inline
Definition at line 309 of file QuartzQuantizationUtilities.h.
References ThirtySecondNotesPerMinute.
IsSameTickRate()
bool Audio::FQuartzClockTickRate::IsSameTickRate (const FQuartzClockTickRate & Other, bool bAccountForDifferentSampleRates = true) const
Definition at line 405 of file QuartzQuantizationUtilities.cpp.
References FQuartzClockTickRate(), BeatsPerMinute, checkSlow, FramesPerTick, FMath::IsNearlyEqual(), MillisecondsPerTick, Other, SampleRate, SetSampleRate(), and ThirtySecondNotesPerMinute.
IsValid()
bool Audio::FQuartzClockTickRate::IsValid (int32 InEventResolutionThreshold = 1) const
Definition at line 391 of file QuartzQuantizationUtilities.cpp.
References ensureMsgf, FramesPerTick, and TEXT.
RecalculateDurationsBasedOnFramesPerTick()
void Audio::FQuartzClockTickRate::RecalculateDurationsBasedOnFramesPerTick () private
Definition at line 439 of file QuartzQuantizationUtilities.cpp.
References BeatsPerMinute, check, FramesPerTick, MillisecondsPerTick, SampleRate, SecondsPerTick, and ThirtySecondNotesPerMinute.
Referenced by SetBeatsPerMinute(), SetFramesPerTick(), SetMillisecondsPerTick(), SetSampleRate(), and SetThirtySecondNotesPerMinute().
SetBeatsPerMinute()
void Audio::FQuartzClockTickRate::SetBeatsPerMinute (double InNewBeatsPerMinute)
Definition at line 270 of file QuartzQuantizationUtilities.cpp.
References FramesPerTick, FMath::Max, RecalculateDurationsBasedOnFramesPerTick(), and SampleRate.
Referenced by FQuartzClockTickRate().
SetFramesPerTick()
void Audio::FQuartzClockTickRate::SetFramesPerTick (int32 InNewFramesPerTick)
Definition at line 244 of file QuartzQuantizationUtilities.cpp.
References FramesPerTick, RecalculateDurationsBasedOnFramesPerTick(), TEXT, UE_LOG, and Warning.
SetMillisecondsPerTick()
void Audio::FQuartzClockTickRate::SetMillisecondsPerTick (double InNewMillisecondsPerTick)
Definition at line 256 of file QuartzQuantizationUtilities.cpp.
References FramesPerTick, FMath::Max, RecalculateDurationsBasedOnFramesPerTick(), and SampleRate.
Referenced by SetSecondsPerTick().
SetSampleRate()
void Audio::FQuartzClockTickRate::SetSampleRate (double InNewSampleRate)
Definition at line 283 of file QuartzQuantizationUtilities.cpp.
References check, FramesPerTick, FMath::Max, RecalculateDurationsBasedOnFramesPerTick(), and SampleRate.
Referenced by IsSameTickRate().
SetSecondsPerTick()
void Audio::FQuartzClockTickRate::SetSecondsPerTick (double InNewSecondsPerTick)
Definition at line 451 of file QuartzQuantizationUtilities.cpp.
References SetMillisecondsPerTick().
SetThirtySecondNotesPerMinute()
void Audio::FQuartzClockTickRate::SetThirtySecondNotesPerMinute (double InNewThirtySecondNotesPerMinute)
Definition at line 262 of file QuartzQuantizationUtilities.cpp.
References check, FramesPerTick, FMath::Max, RecalculateDurationsBasedOnFramesPerTick(), and SampleRate.
Field Documentation
BeatsPerMinute
double Audio::FQuartzClockTickRate::BeatsPerMinute { 0.0 } private
Definition at line 332 of file QuartzQuantizationUtilities.h.
Referenced by GetBeatsPerMinute(), IsSameTickRate(), and RecalculateDurationsBasedOnFramesPerTick().
FramesPerTick
double Audio::FQuartzClockTickRate::FramesPerTick { 1.0 } private
Definition at line 328 of file QuartzQuantizationUtilities.h.
Referenced by GetFramesPerDuration(), GetFramesPerTick(), IsSameTickRate(), IsValid(), RecalculateDurationsBasedOnFramesPerTick(), SetBeatsPerMinute(), SetFramesPerTick(), SetMillisecondsPerTick(), SetSampleRate(), and SetThirtySecondNotesPerMinute().
MillisecondsPerTick
double Audio::FQuartzClockTickRate::MillisecondsPerTick { 1.0 } private
Definition at line 329 of file QuartzQuantizationUtilities.h.
Referenced by GetMillisecondsPerTick(), IsSameTickRate(), and RecalculateDurationsBasedOnFramesPerTick().
SampleRate
double Audio::FQuartzClockTickRate::SampleRate { 44100.0 } private
Definition at line 333 of file QuartzQuantizationUtilities.h.
Referenced by GetSampleRate(), IsSameTickRate(), RecalculateDurationsBasedOnFramesPerTick(), SetBeatsPerMinute(), SetMillisecondsPerTick(), SetSampleRate(), and SetThirtySecondNotesPerMinute().
SecondsPerTick
double Audio::FQuartzClockTickRate::SecondsPerTick { 1.0 } private
Definition at line 330 of file QuartzQuantizationUtilities.h.
Referenced by GetSecondsPerTick(), and RecalculateDurationsBasedOnFramesPerTick().
ThirtySecondNotesPerMinute
double Audio::FQuartzClockTickRate::ThirtySecondNotesPerMinute { 1.0 } private
Definition at line 331 of file QuartzQuantizationUtilities.h.
Referenced by GetThirtySecondNotesPerMinute(), IsSameTickRate(), and RecalculateDurationsBasedOnFramesPerTick().
The documentation for this struct was generated from the following files:
Runtime/Engine/Classes/Sound/QuartzQuantizationUtilities.h
Runtime/Engine/Classes/Sound/QuartzQuantizationUtilities.cpp