Unreal Engine 5.6 C++ API: FMovieSceneEvaluationTree Struct Reference
FMovieSceneEvaluationTree Struct Reference
A tree structure used to efficiently reference overlapping time ranges hierarchically.
#include "MovieSceneEvaluationTree.h"
Public Member Functions
FMovieSceneEvaluationTree ()
FMovieSceneEvaluationTree (const FMovieSceneEvaluationTree &RHS)=default
FMovieSceneEvaluationTree (FMovieSceneEvaluationTree &&RHS)
Move construction must ensure that the root node is correctly restored to its default to ensure that invariant.
MOVIESCENE_API void AddTimeRange (TRange< FFrameNumber > InTimeRange)
Insert the specified time range into this tree.
MOVIESCENE_API TArrayView< FMovieSceneEvaluationTreeNode > GetChildren (const FMovieSceneEvaluationTreeNode &InNode)
Get the children associated with the specified node.
MOVIESCENE_API TArrayView< const FMovieSceneEvaluationTreeNode > GetChildren (const FMovieSceneEvaluationTreeNode &InNode) const
Get the children associated with the specified node.
FMovieSceneEvaluationTreeNode & GetNode (FMovieSceneEvaluationTreeNodeHandle Handle)
Non-const access to a node from its handle.
const FMovieSceneEvaluationTreeNode & GetNode (FMovieSceneEvaluationTreeNodeHandle Handle) const
Const access to a node from its handle.
const FMovieSceneEvaluationTreeNode & GetRootNode () const
Access this tree's root node (infinite range)
bool IsValid (FMovieSceneEvaluationTreeNodeHandle Handle) const
Check whether the specified handle corresponds to a node within this tree.
MOVIESCENE_API FMovieSceneEvaluationTreeRangeIterator IterateFromLowerBound (TRangeBound< FFrameNumber > InStartingLowerBound) const
Start iterating this tree from the specified lower boundary.
MOVIESCENE_API FMovieSceneEvaluationTreeRangeIterator IterateFromTime (FFrameNumber Time) const
Start iterating this tree from the specified time.
FMovieSceneEvaluationTree & operator= (const FMovieSceneEvaluationTree &RHS)=default
FMovieSceneEvaluationTree & operator= (FMovieSceneEvaluationTree &&RHS)
Move assignment must ensure that the root node is correctly restored to its default to ensure that invariant.
void Reset ()
Protected Member Functions
MOVIESCENE_API void AddTimeRange (TRange< FFrameNumber > InTimeRange, const IMovieSceneEvaluationTreeNodeOperator &InOperator, FMovieSceneEvaluationTreeNodeHandle InParent, const TFunctionRef< bool(FMovieSceneEvaluationTreeNodeHandle)> *Predicate)
Insert the specified time range into this tree.
FMovieSceneEvaluationTreeNode & GetNode (FEvaluationTreeEntryHandle ChildrenID, int32 Index)
Non-const access to a node from its parent's ChildrenID and this node's index.
const FMovieSceneEvaluationTreeNode & GetNode (FEvaluationTreeEntryHandle ChildrenID, int32 Index) const
Const access to a node from its parent's ChildrenID and this node's index.
MOVIESCENE_API void InsertNewChild (TRange< FFrameNumber > InEffectiveRange, const IMovieSceneEvaluationTreeNodeOperator &InOperator, int32 InsertIndex, FMovieSceneEvaluationTreeNodeHandle InParent)
Helper function that creates a new child for the specified parent node.
Protected Attributes
TEvaluationTreeEntryContainer< FMovieSceneEvaluationTreeNode > ChildNodes
Segmented array of all child nodes within this tree (in no particular order)
FMovieSceneEvaluationTreeNode RootNode
This tree's root node.
Friends
FArchive & operator<< (FArchive &Ar, FMovieSceneEvaluationTree &In)
Serialize this evaluation tree.
Detailed Description
A tree structure used to efficiently reference overlapping time ranges hierarchically.
Each node represents a unique combination of 'entities' overlapping for a given range. Example structure (dependent on order of addition): Time -inf 10 20 25 30 inf [============= 0 ===========] [============= 1 ==================] [========================== 2 ==================================] [================== 3 ==========================] [================== 4 ==========================]
[===== 5 ======]
Where each time range is added in order, this is represented as: [======== 3 =======][========== 0,2,3 ==========][============= 1,2 ================][============ 4 ===========] | \
[===== 5 ====] [======== 4 ========]
Unique Ranges [ 3 | 0,2,3 | 0,2,3,5 | 0,2,3 | 1,2 | 1,2,4 | 4 ]
Definition at line 328 of file MovieSceneEvaluationTree.h.
Constructor & Destructor Documentation
FMovieSceneEvaluationTree() [1/3]
FMovieSceneEvaluationTree::FMovieSceneEvaluationTree () inline
Definition at line 330 of file MovieSceneEvaluationTree.h.
References All, Invalid, and RootNode.
Referenced by FMovieSceneEvaluationTree(), FMovieSceneEvaluationTree(), operator<<, TMovieSceneEvaluationTree< DataType >::operator<<, operator=(), and operator=().
FMovieSceneEvaluationTree() [2/3]
FMovieSceneEvaluationTree::FMovieSceneEvaluationTree (const FMovieSceneEvaluationTree & RHS) default
References FMovieSceneEvaluationTree().
FMovieSceneEvaluationTree() [3/3]
FMovieSceneEvaluationTree::FMovieSceneEvaluationTree (FMovieSceneEvaluationTree && RHS) inline
Move construction must ensure that the root node is correctly restored to its default to ensure that invariant.
Definition at line 339 of file MovieSceneEvaluationTree.h.
References FMovieSceneEvaluationTree(), TRange< ElementType >::All(), ChildNodes, FMovieSceneEvaluationTreeNodeHandle::Invalid(), MoveTemp(), and RootNode.
Member Function Documentation
AddTimeRange() [1/2]
MOVIESCENE_API void FMovieSceneEvaluationTree::AddTimeRange (TRange< FFrameNumber > InTimeRange)
Insert the specified time range into this tree.
Parameters
InTimeRange The time range to add to the tree
Referenced by TMovieSceneEvaluationTree< DataType >::Add(), TMovieSceneEvaluationTree< DataType >::Add(), TMovieSceneEvaluationTree< DataType >::AddSelective(), and TMovieSceneEvaluationTree< DataType >::AddUnique().
AddTimeRange() [2/2]
MOVIESCENE_API void FMovieSceneEvaluationTree::AddTimeRange (TRange< FFrameNumber > InTimeRange, const IMovieSceneEvaluationTreeNodeOperator & InOperator, FMovieSceneEvaluationTreeNodeHandle InParent, const TFunctionRef< bool(FMovieSceneEvaluationTreeNodeHandle)> * Predicate) protected
Insert the specified time range into this tree.
Parameters
InTimeRange The time range to add to the tree
InOperator Operator implementation to call for each node that is relevant to the time range
InParent The current parent node
InPredicate (Optional) Predicate that determines whether the time should be added for a particular point
References Predicate.
GetChildren() [1/2]
MOVIESCENE_API TArrayView< FMovieSceneEvaluationTreeNode > FMovieSceneEvaluationTree::GetChildren (const FMovieSceneEvaluationTreeNode & InNode)
Get the children associated with the specified node.
Parameters
InNode The node to get children for
Returns
Array view of the node's children
GetChildren() [2/2]
MOVIESCENE_API TArrayView< const FMovieSceneEvaluationTreeNode > FMovieSceneEvaluationTree::GetChildren (const FMovieSceneEvaluationTreeNode & InNode) const
Get the children associated with the specified node.
Parameters
InNode The node to get children for
Returns
Array view of the node's children
Referenced by TMovieSceneEvaluationTree< DataType >::IsEmpty().
GetNode() [1/4]
FMovieSceneEvaluationTreeNode & FMovieSceneEvaluationTree::GetNode (FEvaluationTreeEntryHandle ChildrenID, int32 Index) inline protected
Non-const access to a node from its parent's ChildrenID and this node's index.
Returns
A reference to the node that is valid as long as the tree remains unmodified
Definition at line 455 of file MovieSceneEvaluationTree.h.
References ChildNodes, FEvaluationTreeEntryHandle::IsValid(), and RootNode.
GetNode() [2/4]
const FMovieSceneEvaluationTreeNode & FMovieSceneEvaluationTree::GetNode (FEvaluationTreeEntryHandle ChildrenID, int32 Index) const inline protected
Const access to a node from its parent's ChildrenID and this node's index.
Returns
A reference to the node that is valid as long as the tree remains unmodified
Definition at line 464 of file MovieSceneEvaluationTree.h.
References ChildNodes, FEvaluationTreeEntryHandle::IsValid(), and RootNode.
GetNode() [3/4]
FMovieSceneEvaluationTreeNode & FMovieSceneEvaluationTree::GetNode (FMovieSceneEvaluationTreeNodeHandle Handle) inline
Non-const access to a node from its handle.
Handle must be valid.
Returns
A reference to the node that is valid as long as the tree remains unmodified
Definition at line 385 of file MovieSceneEvaluationTree.h.
References check, GetNode(), Handle, and IsValid().
Referenced by GetNode(), and GetNode().
GetNode() [4/4]
const FMovieSceneEvaluationTreeNode & FMovieSceneEvaluationTree::GetNode (FMovieSceneEvaluationTreeNodeHandle Handle) const inline
Const access to a node from its handle.
Handle must be valid.
Returns
A reference to the node that is valid as long as the tree remains unmodified
Definition at line 395 of file MovieSceneEvaluationTree.h.
References check, GetNode(), Handle, and IsValid().
GetRootNode()
const FMovieSceneEvaluationTreeNode & FMovieSceneEvaluationTree::GetRootNode () const inline
Access this tree's root node (infinite range)
Returns
The root node
Definition at line 376 of file MovieSceneEvaluationTree.h.
References RootNode.
Referenced by TMovieSceneEvaluationTree< DataType >::IsEmpty().
InsertNewChild()
MOVIESCENE_API void FMovieSceneEvaluationTree::InsertNewChild (TRange< FFrameNumber > InEffectiveRange, const IMovieSceneEvaluationTreeNodeOperator & InOperator, int32 InsertIndex, FMovieSceneEvaluationTreeNodeHandle InParent) protected
Helper function that creates a new child for the specified parent node.
Parameters
InEffectiveRange The time range that this child should represent. Must not overlap any other child's time range.
InOperator Operator implementation to call for the new child node
InsertIndex The index at which to insert the new child (children must be sorted)
InParent The node to add the child to
IsValid()
bool FMovieSceneEvaluationTree::IsValid (FMovieSceneEvaluationTreeNodeHandle Handle) const inline
Check whether the specified handle corresponds to a node within this tree.
Parameters
InHandle Node handle to test
Returns
true if the handle is valid, false otherwise
Definition at line 423 of file MovieSceneEvaluationTree.h.
References ChildNodes, and Handle.
IterateFromLowerBound()
MOVIESCENE_API FMovieSceneEvaluationTreeRangeIterator FMovieSceneEvaluationTree::IterateFromLowerBound (TRangeBound< FFrameNumber > InStartingLowerBound) const
Start iterating this tree from the specified lower boundary.
Parameters
InStartingLowerBound The lowerbound at which we should start iterating
Returns
A bi-directional iterator that is set to the unique range that overlaps the specified lowerbound
IterateFromTime()
MOVIESCENE_API FMovieSceneEvaluationTreeRangeIterator FMovieSceneEvaluationTree::IterateFromTime (FFrameNumber Time) const
Start iterating this tree from the specified time.
Parameters
Time The time at which we should start iterating
Returns
A bi-directional iterator that is set to the unique range that overlaps the current time
References Time.
operator=() [1/2]
FMovieSceneEvaluationTree & FMovieSceneEvaluationTree::operator= (const FMovieSceneEvaluationTree & RHS) default
References FMovieSceneEvaluationTree().
operator=() [2/2]
FMovieSceneEvaluationTree & FMovieSceneEvaluationTree::operator= (FMovieSceneEvaluationTree && RHS) inline
Move assignment must ensure that the root node is correctly restored to its default to ensure that invariant.
Definition at line 347 of file MovieSceneEvaluationTree.h.
References FMovieSceneEvaluationTree(), TRange< ElementType >::All(), ChildNodes, FMovieSceneEvaluationTreeNodeHandle::Invalid(), MoveTemp(), and RootNode.
Reset()
void FMovieSceneEvaluationTree::Reset () inline
Definition at line 428 of file MovieSceneEvaluationTree.h.
References ChildNodes, and RootNode.
Referenced by TMovieSceneEvaluationTree< DataType >::Reset().
Friends And Related Symbol Documentation
operator<<
FArchive & operator<< (FArchive & Ar, FMovieSceneEvaluationTree & In) friend
Serialize this evaluation tree.
Definition at line 444 of file MovieSceneEvaluationTree.h.
References FMovieSceneEvaluationTree(), Ar, ChildNodes, and RootNode.
Field Documentation
ChildNodes
TEvaluationTreeEntryContainer<FMovieSceneEvaluationTreeNode> FMovieSceneEvaluationTree::ChildNodes protected
Segmented array of all child nodes within this tree (in no particular order)
Definition at line 493 of file MovieSceneEvaluationTree.h.
Referenced by FMovieSceneEvaluationTree(), TMovieSceneEvaluationTree< DataType >::Compact(), GetNode(), GetNode(), IsValid(), operator<<, operator=(), and Reset().
RootNode
FMovieSceneEvaluationTreeNode FMovieSceneEvaluationTree::RootNode protected
This tree's root node.
Definition at line 490 of file MovieSceneEvaluationTree.h.
Referenced by FMovieSceneEvaluationTree(), FMovieSceneEvaluationTree(), GetNode(), GetNode(), GetRootNode(), operator<<, operator=(), and Reset().
The documentation for this struct was generated from the following file:
Runtime/MovieScene/Public/Evaluation/MovieSceneEvaluationTree.h