Unreal Engine 5.6 C++ API: UE::Geometry::TAxisAlignedBox2< RealType > Struct Template Reference
UE::Geometry::TAxisAlignedBox2< RealType > Struct Template Reference
#include "BoxTypes.h"
Public Member Functions
TAxisAlignedBox2 ()
TAxisAlignedBox2 (const TArray< TVector2< RealType > > &Pts)
template<typename OtherRealType>
TAxisAlignedBox2 (const TAxisAlignedBox2< OtherRealType > &OtherBox)
template<typename InRealType>
TAxisAlignedBox2 (const TBox2< InRealType > &Box)
TAxisAlignedBox2 (const TVector2< RealType > &Center, RealType HalfWidth)
TAxisAlignedBox2 (const TVector2< RealType > &Min, const TVector2< RealType > &Max)
TAxisAlignedBox2 (RealType SquareSize)
TAxisAlignedBox2 (RealType Width, RealType Height)
TAxisAlignedBox2 (TArrayView< const TVector2< RealType > > Pts)
RealType Area () const
TVector2< RealType > Center () const
TVector< RealType > Clamp (const TVector2< RealType > &V)
void Contain (const TArray< TVector2< RealType > > &Pts)
void Contain (const TAxisAlignedBox2< RealType > &Other)
void Contain (const TVector2< RealType > &V)
void Contain (TArrayView< const TVector2< RealType > > Pts)
bool Contains (const TAxisAlignedBox2< RealType > &Box) const
bool Contains (const TVector2< RealType > &V) const
RealType DiagonalLength () const
RealType DistanceSquared (const TVector2< RealType > &V) const
void Expand (RealType Radius)
TVector2< RealType > Extents () const
TVector2< RealType > GetCorner (int Index) const
Corners are ordered to follow the perimeter of the bounding rectangle, starting from the (Min.X, Min.Y) corner and ending at (Min.X, Max.Y)
RealType Height () const
TAxisAlignedBox2< RealType > Intersect (const TAxisAlignedBox2< RealType > &Box) const
bool Intersects (const TAxisAlignedBox2< RealType > &Box) const
bool IsEmpty () const
RealType MaxDim () const
RealType MinDim () const
template<typename OutRealType>
operator TBox2< OutRealType > () const
RealType Perimeter () const
RealType Width () const
Static Public Member Functions
static TAxisAlignedBox2< RealType > Empty ()
Data Fields
TVector2< RealType > Max
TVector2< RealType > Min
Detailed Description
template<typename RealType>
struct UE::Geometry::TAxisAlignedBox2< RealType >
Definition at line 619 of file BoxTypes.h.
Constructor & Destructor Documentation
TAxisAlignedBox2() [1/9]
template<typename RealType> UE::Geometry::TAxisAlignedBox2< RealType >::TAxisAlignedBox2 () inline
Definition at line 624 of file BoxTypes.h.
Referenced by UE::Geometry::TAxisAlignedBox2< FVector::FReal >::Empty().
TAxisAlignedBox2() [2/9]
template<typename RealType> UE::Geometry::TAxisAlignedBox2< RealType >::TAxisAlignedBox2 (const TVector2< RealType > & Min, const TVector2< RealType > & Max) inline
Definition at line 629 of file BoxTypes.h.
TAxisAlignedBox2() [3/9]
template<typename RealType> template<typename OtherRealType> UE::Geometry::TAxisAlignedBox2< RealType >::TAxisAlignedBox2 (const TAxisAlignedBox2< OtherRealType > & OtherBox) inline explicit
Definition at line 635 of file BoxTypes.h.
TAxisAlignedBox2() [4/9]
template<typename RealType> UE::Geometry::TAxisAlignedBox2< RealType >::TAxisAlignedBox2 (RealType SquareSize) inline
Definition at line 641 of file BoxTypes.h.
TAxisAlignedBox2() [5/9]
template<typename RealType> UE::Geometry::TAxisAlignedBox2< RealType >::TAxisAlignedBox2 (RealType Width, RealType Height) inline
Definition at line 645 of file BoxTypes.h.
TAxisAlignedBox2() [6/9]
template<typename RealType> UE::Geometry::TAxisAlignedBox2< RealType >::TAxisAlignedBox2 (const TArray< TVector2< RealType > > & Pts) inline
Definition at line 650 of file BoxTypes.h.
TAxisAlignedBox2() [7/9]
template<typename RealType> UE::Geometry::TAxisAlignedBox2< RealType >::TAxisAlignedBox2 (TArrayView< const TVector2< RealType > > Pts) inline
Definition at line 656 of file BoxTypes.h.
TAxisAlignedBox2() [8/9]
template<typename RealType> UE::Geometry::TAxisAlignedBox2< RealType >::TAxisAlignedBox2 (const TVector2< RealType > & Center, RealType HalfWidth) inline
Definition at line 662 of file BoxTypes.h.
TAxisAlignedBox2() [9/9]
template<typename RealType> template<typename InRealType> UE::Geometry::TAxisAlignedBox2< RealType >::TAxisAlignedBox2 (const TBox2< InRealType > & Box) inline
Definition at line 676 of file BoxTypes.h.
Member Function Documentation
Area()
template<typename RealType> RealType UE::Geometry::TAxisAlignedBox2< RealType >::Area () const inline
Definition at line 820 of file BoxTypes.h.
Center()
template<typename RealType> TVector2< RealType > UE::Geometry::TAxisAlignedBox2< RealType >::Center () const inline
Definition at line 696 of file BoxTypes.h.
Referenced by UE::Geometry::FGeneralizedCylinderGenerator::Generate().
Clamp()
template<typename RealType> TVector< RealType > UE::Geometry::TAxisAlignedBox2< RealType >::Clamp (const TVector2< RealType > & V) inline
Definition at line 775 of file BoxTypes.h.
Contain() [1/4]
template<typename RealType> void UE::Geometry::TAxisAlignedBox2< RealType >::Contain (const TArray< TVector2< RealType > > & Pts) inline
Definition at line 749 of file BoxTypes.h.
Contain() [2/4]
template<typename RealType> void UE::Geometry::TAxisAlignedBox2< RealType >::Contain (const TAxisAlignedBox2< RealType > & Other) inline
Definition at line 741 of file BoxTypes.h.
Contain() [3/4]
template<typename RealType> void UE::Geometry::TAxisAlignedBox2< RealType >::Contain (const TVector2< RealType > & V) inline
Definition at line 721 of file BoxTypes.h.
Referenced by UE::Geometry::TAxisAlignedBox2< FVector::FReal >::TAxisAlignedBox2(), UE::Geometry::TAxisAlignedBox2< FVector::FReal >::TAxisAlignedBox2(), UE::Geometry::TAxisAlignedBox2< FVector::FReal >::Contain(), UE::Geometry::TAxisAlignedBox2< FVector::FReal >::Contain(), UE::Geometry::TMeshLocalParam< PointSetType >::GetUVBounds(), and UE::Geometry::TIntrTriangle2AxisAlignedBox2< float >::Test().
Contain() [4/4]
template<typename RealType> void UE::Geometry::TAxisAlignedBox2< RealType >::Contain (TArrayView< const TVector2< RealType > > Pts) inline
Definition at line 757 of file BoxTypes.h.
Contains() [1/2]
template<typename RealType> bool UE::Geometry::TAxisAlignedBox2< RealType >::Contains (const TAxisAlignedBox2< RealType > & Box) const inline
Definition at line 770 of file BoxTypes.h.
Contains() [2/2]
template<typename RealType> bool UE::Geometry::TAxisAlignedBox2< RealType >::Contains (const TVector2< RealType > & V) const inline
Definition at line 765 of file BoxTypes.h.
Referenced by UE::Geometry::TAxisAlignedBox2< FVector::FReal >::Contains().
DiagonalLength()
template<typename RealType> RealType UE::Geometry::TAxisAlignedBox2< RealType >::DiagonalLength () const inline
Definition at line 830 of file BoxTypes.h.
DistanceSquared()
template<typename RealType> RealType UE::Geometry::TAxisAlignedBox2< RealType >::DistanceSquared (const TVector2< RealType > & V) const inline
Definition at line 803 of file BoxTypes.h.
Empty()
template<typename RealType> TAxisAlignedBox2< RealType > UE::Geometry::TAxisAlignedBox2< RealType >::Empty () inline static
Definition at line 689 of file BoxTypes.h.
Referenced by UE::Geometry::TAxisAlignedBox2< FVector::FReal >::TAxisAlignedBox2(), and UE::Geometry::TAxisAlignedBox2< FVector::FReal >::Intersect().
Expand()
template<typename RealType> void UE::Geometry::TAxisAlignedBox2< RealType >::Expand (RealType Radius) inline
Definition at line 850 of file BoxTypes.h.
Extents()
template<typename RealType> TVector2< RealType > UE::Geometry::TAxisAlignedBox2< RealType >::Extents () const inline
Definition at line 703 of file BoxTypes.h.
GetCorner()
template<typename RealType> TVector2< RealType > UE::Geometry::TAxisAlignedBox2< RealType >::GetCorner (int Index) const inline
Corners are ordered to follow the perimeter of the bounding rectangle, starting from the (Min.X, Min.Y) corner and ending at (Min.X, Max.Y)
Parameters
Index which corner to return, must be in range [0,3]
Returns
Corner of the bounding rectangle
Definition at line 713 of file BoxTypes.h.
Height()
template<typename RealType> RealType UE::Geometry::TAxisAlignedBox2< RealType >::Height () const inline
Definition at line 815 of file BoxTypes.h.
Referenced by UE::Geometry::TAxisAlignedBox2< FVector::FReal >::Area(), UE::Geometry::TAxisAlignedBox2< FVector::FReal >::MaxDim(), UE::Geometry::TAxisAlignedBox2< FVector::FReal >::MinDim(), and UE::Geometry::TAxisAlignedBox2< FVector::FReal >::Perimeter().
Intersect()
template<typename RealType> TAxisAlignedBox2< RealType > UE::Geometry::TAxisAlignedBox2< RealType >::Intersect (const TAxisAlignedBox2< RealType > & Box) const inline
Definition at line 788 of file BoxTypes.h.
Intersects()
template<typename RealType> bool UE::Geometry::TAxisAlignedBox2< RealType >::Intersects (const TAxisAlignedBox2< RealType > & Box) const inline
Definition at line 783 of file BoxTypes.h.
Referenced by UE::Geometry::TIntrTriangle2AxisAlignedBox2< float >::Test().
IsEmpty()
template<typename RealType> bool UE::Geometry::TAxisAlignedBox2< RealType >::IsEmpty () const inline
Definition at line 845 of file BoxTypes.h.
Referenced by UE::Geometry::TAxisAlignedBox2< FVector::FReal >::operator TBox2< OutRealType >().
MaxDim()
template<typename RealType> RealType UE::Geometry::TAxisAlignedBox2< RealType >::MaxDim () const inline
Definition at line 835 of file BoxTypes.h.
Referenced by UE::Geometry::FGeneralizedCylinderGenerator::Generate().
MinDim()
template<typename RealType> RealType UE::Geometry::TAxisAlignedBox2< RealType >::MinDim () const inline
Definition at line 840 of file BoxTypes.h.
operator TBox2< OutRealType >()
template<typename RealType> template<typename OutRealType> UE::Geometry::TAxisAlignedBox2< RealType >::operator TBox2< OutRealType > () const inline explicit
Definition at line 669 of file BoxTypes.h.
Perimeter()
template<typename RealType> RealType UE::Geometry::TAxisAlignedBox2< RealType >::Perimeter () const inline
Definition at line 825 of file BoxTypes.h.
Width()
template<typename RealType> RealType UE::Geometry::TAxisAlignedBox2< RealType >::Width () const inline
Definition at line 810 of file BoxTypes.h.
Referenced by UE::Geometry::TAxisAlignedBox2< FVector::FReal >::Area(), UE::Geometry::TAxisAlignedBox2< FVector::FReal >::MaxDim(), UE::Geometry::TAxisAlignedBox2< FVector::FReal >::MinDim(), and UE::Geometry::TAxisAlignedBox2< FVector::FReal >::Perimeter().
Field Documentation
Max
template<typename RealType> TVector2<RealType> UE::Geometry::TAxisAlignedBox2< RealType >::Max
Definition at line 622 of file BoxTypes.h.
Referenced by UE::Geometry::TAxisAlignedBox2< FVector::FReal >::TAxisAlignedBox2().
Min
template<typename RealType> TVector2<RealType> UE::Geometry::TAxisAlignedBox2< RealType >::Min
Definition at line 621 of file BoxTypes.h.
Referenced by UE::Geometry::TAxisAlignedBox2< FVector::FReal >::TAxisAlignedBox2().
The documentation for this struct was generated from the following file:
Runtime/GeometryCore/Public/BoxTypes.h