Unreal Engine 5.6 C++ API: FTabSpawnerEntry Struct Reference
FTabSpawnerEntry Struct Reference
#include "TabManager.h"
Public Member Functions
FTabSpawnerEntry (const FName &InTabType, const FOnSpawnTab &InSpawnTabMethod, const FCanSpawnTab &InCanSpawnTab)
virtual TSharedPtr< FTabSpawnerEntry > AsSpawnerEntry () override
bool CanSidebarTab () const
const FName GetTabType () const
const bool IsHidden () const
FTabSpawnerEntry & SetAutoGenerateMenuEntry (bool bInAutoGenerateMenuEntry)
FTabSpawnerEntry & SetCanSidebarTab (bool bInCanSidebarTab)
FTabSpawnerEntry & SetDisplayName (const FText &InLegibleName)
FTabSpawnerEntry & SetDisplayNameAttribute (const TAttribute< FText > &InLegibleName)
FTabSpawnerEntry & SetGroup (const TSharedRef< FWorkspaceItem > &InGroup)
FTabSpawnerEntry & SetIcon (const FSlateIcon &InIcon)
FTabSpawnerEntry & SetMenuType (const TAttribute< ETabSpawnerMenuType::Type > &InMenuType)
FTabSpawnerEntry & SetReadOnlyBehavior (const ETabReadOnlyBehavior &InReadOnlyBehavior)
FTabSpawnerEntry & SetReuseTabMethod (const FOnFindTabToReuse &InReuseTabMethod)
FTabSpawnerEntry & SetTooltipText (const FText &InTooltipText)
FTabSpawnerEntry & SetTooltipTextAttribute (const TAttribute< FText > &InTooltipText)
Public Member Functions inherited from FWorkspaceItem
virtual PRAGMA_DISABLE_DEPRECATION_WARNINGS ~FWorkspaceItem ()
TSharedRef< FWorkspaceItem > AddGroup (const FName &InName, const FText &InDisplayName, const FSlateIcon &InIcon=FSlateIcon(), const bool InSortChildren=false)
TSharedRef< FWorkspaceItem > AddGroup (const FName &InName, const FText &InDisplayName, const FText &InTooltipText, const FSlateIcon &InIcon=FSlateIcon(), const bool InSortChildren=false)
TSharedRef< FWorkspaceItem > AddGroup (const FText &InDisplayName, const FSlateIcon &InIcon=FSlateIcon(), const bool InSortChildren=false)
TSharedRef< FWorkspaceItem > AddGroup (const FText &InDisplayName, const FText &InTooltipText, const FSlateIcon &InIcon=FSlateIcon(), const bool InSortChildren=false)
void AddItem (const TSharedRef< FWorkspaceItem > &ItemToAdd)
void ClearItems ()
const TArray< TSharedRef< FWorkspaceItem > > & GetChildItems () const
const FText & GetDisplayName () const
const FName GetFName () const
const FSlateIcon & GetIcon () const
TSharedPtr< FWorkspaceItem > GetParent () const
const FText & GetTooltipText () const
bool HasChildrenIn (const TArray< TWeakPtr< FTabSpawnerEntry > > &AllowedSpawners)
void RemoveItem (const TSharedRef< FWorkspaceItem > &ItemToRemove)
void SortChildren ()
Public Member Functions inherited from TSharedFromThis< FWorkspaceItem >
TSharedRef< FWorkspaceItem, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FWorkspaceItem, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Private Member Functions
FORCENOINLINE bool IsSoleTabInstanceSpawned () const
Private Attributes
bool bAutoGenerateMenuEntry
Whether to automatically generate a menu entry for this tab spawner.
bool bCanSidebarTab
Whether or not this tab can ever be in a sidebar.
FCanSpawnTab CanSpawnTab
TAttribute< ETabSpawnerMenuType::Type > MenuType
Whether this menu item should be enabled, disabled, or hidden.
FOnFindTabToReuse OnFindTabToReuse
When this method is not provided, we assume that the tab should only allow 0 or 1 instances.
FOnSpawnTab OnSpawnTab
ETabReadOnlyBehavior ReadOnlyBehavior
How this tab behaves when the tab manager is in a read only mode.
TWeakPtr< SDockTab > SpawnedTabPtr
FName TabType
Friends
class FTabManager
Additional Inherited Members
Static Public Member Functions inherited from FWorkspaceItem
static TSharedRef< FWorkspaceItem > NewGroup (const FName &Name, const FText &DisplayName, const FSlateIcon &Icon=FSlateIcon(), const bool bSortChildren=false)
static TSharedRef< FWorkspaceItem > NewGroup (const FName &Name, const FText &DisplayName, const FText &TooltipText, const FSlateIcon &Icon=FSlateIcon(), const bool bSortChildren=false)
static TSharedRef< FWorkspaceItem > NewGroup (const FText &DisplayName, const FSlateIcon &Icon=FSlateIcon(), const bool bSortChildren=false)
static TSharedRef< FWorkspaceItem > NewGroup (const FText &DisplayName, const FText &TooltipText, const FSlateIcon &Icon=FSlateIcon(), const bool bSortChildren=false)
Protected Member Functions inherited from FWorkspaceItem
FWorkspaceItem (const FName &InName, const FText &InDisplayName, const FSlateIcon &InIcon, const bool bInSortChildren)
FWorkspaceItem (const FName &InName, const FText &InDisplayName, const FText &InTooltipText, const FSlateIcon &InIcon, const bool bInSortChildren)
FWorkspaceItem (const FText &InDisplayName, const FSlateIcon &InIcon, const bool bInSortChildren)
FWorkspaceItem (const FText &InDisplayName, const FText &InTooltipText, const FSlateIcon &InIcon, const bool bInSortChildren)
UE_DEPRECATED (5.0, "Use DisplayNameAttribute instead.") FText DisplayName
UE_DEPRECATED (5.0, "Use TooltipTextAttribute instead.") FText TooltipText
Protected Member Functions inherited from TSharedFromThis< FWorkspaceItem >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions inherited from TSharedFromThis< FWorkspaceItem >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Protected Attributes inherited from FWorkspaceItem
bool bSortChildren
TArray< TSharedRef< FWorkspaceItem > > ChildItems
TAttribute< FText > DisplayNameAttribute
FSlateIcon Icon
TAttribute< FName > NameAttribute
TWeakPtr< FWorkspaceItem > ParentItem
TAttribute< FText > TooltipTextAttribute
Detailed Description
Definition at line 216 of file TabManager.h.
Constructor & Destructor Documentation
FTabSpawnerEntry()
FTabSpawnerEntry::FTabSpawnerEntry (const FName & InTabType, const FOnSpawnTab & InSpawnTabMethod, const FCanSpawnTab & InCanSpawnTab) inline
Definition at line 218 of file TabManager.h.
References FWorkspaceItem::FWorkspaceItem(), bAutoGenerateMenuEntry, bCanSidebarTab, CanSpawnTab, Disabled, Enabled, MenuType, OnFindTabToReuse, OnSpawnTab, ReadOnlyBehavior, SpawnedTabPtr, and TabType.
Referenced by SetAutoGenerateMenuEntry(), SetCanSidebarTab(), SetDisplayName(), SetDisplayNameAttribute(), SetGroup(), SetIcon(), SetMenuType(), SetReadOnlyBehavior(), SetReuseTabMethod(), SetTooltipText(), and SetTooltipTextAttribute().
Member Function Documentation
AsSpawnerEntry()
virtual TSharedPtr< FTabSpawnerEntry > FTabSpawnerEntry::AsSpawnerEntry () inline override virtual
Reimplemented from FWorkspaceItem.
Definition at line 304 of file TabManager.h.
References TSharedFromThis< FWorkspaceItem >::SharedThis().
CanSidebarTab()
bool FTabSpawnerEntry::CanSidebarTab () const inline
Definition at line 299 of file TabManager.h.
References bCanSidebarTab.
GetTabType()
const FName FTabSpawnerEntry::GetTabType () const inline
Definition at line 309 of file TabManager.h.
References TabType.
IsHidden()
const bool FTabSpawnerEntry::IsHidden () const inline
Definition at line 314 of file TabManager.h.
References ETabSpawnerMenuType::Hidden, and MenuType.
IsSoleTabInstanceSpawned()
FORCENOINLINE bool FTabSpawnerEntry::IsSoleTabInstanceSpawned () const inline private
Definition at line 337 of file TabManager.h.
References FORCENOINLINE, and SpawnedTabPtr.
SetAutoGenerateMenuEntry()
FTabSpawnerEntry & FTabSpawnerEntry::SetAutoGenerateMenuEntry (bool bInAutoGenerateMenuEntry) inline
Definition at line 287 of file TabManager.h.
References FTabSpawnerEntry(), and bAutoGenerateMenuEntry.
SetCanSidebarTab()
FTabSpawnerEntry & FTabSpawnerEntry::SetCanSidebarTab (bool bInCanSidebarTab) inline
Definition at line 293 of file TabManager.h.
References FTabSpawnerEntry(), and bCanSidebarTab.
SetDisplayName()
FTabSpawnerEntry & FTabSpawnerEntry::SetDisplayName (const FText & InLegibleName) inline
Definition at line 257 of file TabManager.h.
References FTabSpawnerEntry(), and FWorkspaceItem::DisplayNameAttribute.
SetDisplayNameAttribute()
FTabSpawnerEntry & FTabSpawnerEntry::SetDisplayNameAttribute (const TAttribute< FText > & InLegibleName) inline
Definition at line 245 of file TabManager.h.
References FTabSpawnerEntry(), and FWorkspaceItem::DisplayNameAttribute.
SetGroup()
FTabSpawnerEntry & FTabSpawnerEntry::SetGroup (const TSharedRef< FWorkspaceItem > & InGroup) inline
Definition at line 269 of file TabManager.h.
References FTabSpawnerEntry(), and TSharedFromThis< FWorkspaceItem >::SharedThis().
SetIcon()
FTabSpawnerEntry & FTabSpawnerEntry::SetIcon (const FSlateIcon & InIcon) inline
Definition at line 239 of file TabManager.h.
References FTabSpawnerEntry(), and FWorkspaceItem::Icon.
SetMenuType()
FTabSpawnerEntry & FTabSpawnerEntry::SetMenuType (const TAttribute< ETabSpawnerMenuType::Type > & InMenuType) inline
Definition at line 281 of file TabManager.h.
References FTabSpawnerEntry(), and MenuType.
SetReadOnlyBehavior()
FTabSpawnerEntry & FTabSpawnerEntry::SetReadOnlyBehavior (const ETabReadOnlyBehavior & InReadOnlyBehavior) inline
Definition at line 233 of file TabManager.h.
References FTabSpawnerEntry(), and ReadOnlyBehavior.
SetReuseTabMethod()
FTabSpawnerEntry & FTabSpawnerEntry::SetReuseTabMethod (const FOnFindTabToReuse & InReuseTabMethod) inline
Definition at line 275 of file TabManager.h.
References FTabSpawnerEntry(), and OnFindTabToReuse.
SetTooltipText()
FTabSpawnerEntry & FTabSpawnerEntry::SetTooltipText (const FText & InTooltipText) inline
Definition at line 263 of file TabManager.h.
References FTabSpawnerEntry(), and FWorkspaceItem::TooltipTextAttribute.
SetTooltipTextAttribute()
FTabSpawnerEntry & FTabSpawnerEntry::SetTooltipTextAttribute (const TAttribute< FText > & InTooltipText) inline
Definition at line 251 of file TabManager.h.
References FTabSpawnerEntry(), and FWorkspaceItem::TooltipTextAttribute.
Friends And Related Symbol Documentation
FTabManager
friend class FTabManager friend
Definition at line 343 of file TabManager.h.
References FTabManager.
Referenced by FTabManager.
Field Documentation
bAutoGenerateMenuEntry
bool FTabSpawnerEntry::bAutoGenerateMenuEntry private
Whether to automatically generate a menu entry for this tab spawner.
Definition at line 328 of file TabManager.h.
Referenced by FTabSpawnerEntry(), and SetAutoGenerateMenuEntry().
bCanSidebarTab
bool FTabSpawnerEntry::bCanSidebarTab private
Whether or not this tab can ever be in a sidebar.
Definition at line 330 of file TabManager.h.
Referenced by FTabSpawnerEntry(), CanSidebarTab(), and SetCanSidebarTab().
CanSpawnTab
FCanSpawnTab FTabSpawnerEntry::CanSpawnTab private
Definition at line 322 of file TabManager.h.
Referenced by FTabSpawnerEntry().
MenuType
TAttribute<ETabSpawnerMenuType::Type> FTabSpawnerEntry::MenuType private
Whether this menu item should be enabled, disabled, or hidden.
Definition at line 326 of file TabManager.h.
Referenced by FTabSpawnerEntry(), IsHidden(), and SetMenuType().
OnFindTabToReuse
FOnFindTabToReuse FTabSpawnerEntry::OnFindTabToReuse private
When this method is not provided, we assume that the tab should only allow 0 or 1 instances.
Definition at line 324 of file TabManager.h.
Referenced by FTabSpawnerEntry(), and SetReuseTabMethod().
OnSpawnTab
FOnSpawnTab FTabSpawnerEntry::OnSpawnTab private
Definition at line 321 of file TabManager.h.
Referenced by FTabSpawnerEntry().
ReadOnlyBehavior
ETabReadOnlyBehavior FTabSpawnerEntry::ReadOnlyBehavior private
How this tab behaves when the tab manager is in a read only mode.
Definition at line 335 of file TabManager.h.
Referenced by FTabSpawnerEntry(), and SetReadOnlyBehavior().
SpawnedTabPtr
TWeakPtr<SDockTab> FTabSpawnerEntry::SpawnedTabPtr private
Definition at line 332 of file TabManager.h.
Referenced by FTabSpawnerEntry(), and IsSoleTabInstanceSpawned().
TabType
FName FTabSpawnerEntry::TabType private
Definition at line 320 of file TabManager.h.
Referenced by FTabSpawnerEntry(), and GetTabType().
The documentation for this struct was generated from the following file:
Runtime/Slate/Public/Framework/Docking/TabManager.h