Unreal Engine 5.6 C++ API: UE::MovieScene::FObjectComponent Struct Reference
UE::MovieScene::FObjectComponent Struct Reference
A component that represents a UObject* either as a strong or weak reference.
#include "BuiltInComponentTypes.h"
Public Member Functions
FObjectComponent ()
MOVIESCENE_API UObject * GetObject () const
operator bool () const
Check whether this object component is valid.
bool operator!= (UObject *InObject) const
Compare this component with another object ptr.
UObject * operator-> () const
bool operator== (UObject *InObject) const
Compare this component with another object ptr.
Static Public Member Functions
static FObjectComponent Null ()
Construct a new null component.
static FObjectComponent Strong (UObject *InObject)
Construct a new strongly-referenced component from an object ptr.
static FObjectComponent Weak (UObject *InObject)
Construct a new weakly-referenced component from an object ptr.
Private Member Functions
FObjectComponent (UObject *InObject, const FObjectKey &InObjectKey)
bool IsStrongReference () const
Private Attributes
FObjectKey ObjectKey
Default constructed for strong pointers.
TObjectPtr< UObject > ObjectPtr
Raw pointer to the object.
Friends
MOVIESCENE_API friend void AddReferencedObjectForComponent (FReferenceCollector *ReferenceCollector, FObjectComponent *ComponentData)
Conditionally add a reference for the specified component data based on whether it is strongly referenced or not.
uint32 GetTypeHash (const FObjectComponent &In)
Generate a type has from this component.
bool operator== (const FObjectComponent &A, const FObjectComponent &B)
Equality operator.
Detailed Description
A component that represents a UObject* either as a strong or weak reference.
Definition at line 237 of file BuiltInComponentTypes.h.
Constructor & Destructor Documentation
FObjectComponent() [1/2]
UE::MovieScene::FObjectComponent::FObjectComponent () inline
Definition at line 239 of file BuiltInComponentTypes.h.
References ObjectPtr.
Referenced by AddReferencedObjectForComponent, GetTypeHash, Null(), operator==, Strong(), and Weak().
FObjectComponent() [2/2]
UE::MovieScene::FObjectComponent::FObjectComponent (UObject * InObject, const FObjectKey & InObjectKey) inline private
Definition at line 315 of file BuiltInComponentTypes.h.
References ObjectKey, and ObjectPtr.
Member Function Documentation
GetObject()
MOVIESCENE_API UObject * UE::MovieScene::FObjectComponent::GetObject () const
Referenced by UE::MovieScene::TApplyMaterialSwitchers< AccessorType, RequiredComponents >::ForEachEntity(), UE::MovieScene::TInitializeBoundMaterials< AccessorType, RequiredComponents >::InitializeBoundMaterial(), UE::MovieScene::FGarbageTraits::IsGarbage(), operator->(), UE::MovieScene::FObjectPropertyTraits::SetObjectPropertyValue(), and UE::MovieScene::FObjectPropertyTraits::SetObjectPropertyValue().
IsStrongReference()
bool UE::MovieScene::FObjectComponent::IsStrongReference () const private
Null()
FObjectComponent UE::MovieScene::FObjectComponent::Null () inline static
Construct a new null component.
Definition at line 244 of file BuiltInComponentTypes.h.
References FObjectComponent().
Referenced by UE::MovieScene::TAddBoundMaterialMutationImpl< AccessorType, TIntegerSequence< int, Indices... >, RequiredComponents... >::InitializeAllocation(), and UE::MovieScene::TInitializeBoundMaterials< AccessorType, RequiredComponents >::InitializeBoundMaterial().
operator bool()
UE::MovieScene::FObjectComponent::operator bool () const inline explicit
Check whether this object component is valid.
Definition at line 262 of file BuiltInComponentTypes.h.
References ObjectPtr.
operator!=()
bool UE::MovieScene::FObjectComponent::operator!= (UObject * InObject) const inline
Compare this component with another object ptr.
Definition at line 274 of file BuiltInComponentTypes.h.
References ObjectPtr.
operator->()
UObject * UE::MovieScene::FObjectComponent::operator-> () const inline
Definition at line 301 of file BuiltInComponentTypes.h.
References checkSlow, and GetObject().
operator==()
bool UE::MovieScene::FObjectComponent::operator== (UObject * InObject) const inline
Compare this component with another object ptr.
Definition at line 268 of file BuiltInComponentTypes.h.
References ObjectPtr.
Strong()
FObjectComponent UE::MovieScene::FObjectComponent::Strong (UObject * InObject) inline static
Construct a new strongly-referenced component from an object ptr.
Definition at line 250 of file BuiltInComponentTypes.h.
References FObjectComponent().
Weak()
FObjectComponent UE::MovieScene::FObjectComponent::Weak (UObject * InObject) inline static
Construct a new weakly-referenced component from an object ptr.
Definition at line 256 of file BuiltInComponentTypes.h.
References FObjectComponent().
Referenced by UE::MovieScene::TInitializeBoundMaterials< AccessorType, RequiredComponents >::InitializeBoundMaterial().
Friends And Related Symbol Documentation
AddReferencedObjectForComponent
MOVIESCENE_API friend void AddReferencedObjectForComponent (FReferenceCollector * ReferenceCollector, FObjectComponent * ComponentData) friend
Conditionally add a reference for the specified component data based on whether it is strongly referenced or not.
References FObjectComponent().
GetTypeHash
uint32 GetTypeHash (const FObjectComponent & In) friend
Generate a type has from this component.
Definition at line 291 of file BuiltInComponentTypes.h.
References FObjectComponent(), GetTypeHash(), ObjectKey, and ObjectPtr.
operator==
bool operator== (const FObjectComponent & A, const FObjectComponent & B) friend
Equality operator.
Definition at line 280 of file BuiltInComponentTypes.h.
References FObjectComponent(), A, and B.
Field Documentation
ObjectKey
FObjectKey UE::MovieScene::FObjectComponent::ObjectKey private
Default constructed for strong pointers.
Assigned on construction for weak ptrs.
Definition at line 326 of file BuiltInComponentTypes.h.
Referenced by FObjectComponent(), and GetTypeHash.
ObjectPtr
TObjectPtr<UObject> UE::MovieScene::FObjectComponent::ObjectPtr private
Raw pointer to the object.
This is explicitly assigned for both strong and weak ptrs, but is only added to the reference graph when FObjectKey() is default constructed.
Definition at line 323 of file BuiltInComponentTypes.h.
Referenced by FObjectComponent(), FObjectComponent(), GetTypeHash, operator bool(), operator!=(), and operator==().
The documentation for this struct was generated from the following file:
Runtime/MovieScene/Public/EntitySystem/BuiltInComponentTypes.h