Unreal Engine 5.6 C++ API: FDynamicStats Struct Reference
FDynamicStats Struct Reference
Helper class used to generate dynamic stat ids.
#include "DynamicStats.h"
Static Public Member Functions
template<typename TStatGroup>
static TStatId CreateMemoryStatId (const FName StatNameOrDescription, FPlatformMemory::EMemoryCounterRegion MemRegion=FPlatformMemory::MCR_Physical)
template<typename TStatGroup>
static TStatId CreateMemoryStatId (const FString &StatNameOrDescription, FPlatformMemory::EMemoryCounterRegion MemRegion=FPlatformMemory::MCR_Physical)
template<typename TStatGroup>
static TStatId CreateStatId (const FName StatNameOrDescription, bool IsTimer=true)
template<typename TStatGroup>
static TStatId CreateStatId (const FString &StatNameOrDescription)
Create a new stat id and registers it with the stats system.
template<typename TStatGroup>
static TStatId CreateStatIdDouble (const FString &StatNameOrDescription, bool bIsAccumulator=false)
template<typename TStatGroup>
static TStatId CreateStatIdInt64 (const FString &StatNameOrDescription, bool bIsAccumulator=false)
Detailed Description
Helper class used to generate dynamic stat ids.
Definition at line 9 of file DynamicStats.h.
Member Function Documentation
CreateMemoryStatId() [1/2]
template<typename TStatGroup> TStatId FDynamicStats::CreateMemoryStatId (const FName StatNameOrDescription, FPlatformMemory::EMemoryCounterRegion MemRegion = FPlatformMemory::MCR_Physical) inline static
Definition at line 73 of file DynamicStats.h.
References FGenericPlatformMemory::MCR_Physical, and FName::ToString().
CreateMemoryStatId() [2/2]
template<typename TStatGroup> TStatId FDynamicStats::CreateMemoryStatId (const FString & StatNameOrDescription, FPlatformMemory::EMemoryCounterRegion MemRegion = FPlatformMemory::MCR_Physical) inline static
Definition at line 63 of file DynamicStats.h.
References CreateMemoryStatId(), FName, and FGenericPlatformMemory::MCR_Physical.
Referenced by CreateMemoryStatId().
CreateStatId() [1/2]
template<typename TStatGroup> TStatId FDynamicStats::CreateStatId (const FName StatNameOrDescription, bool IsTimer = true) inline static
Definition at line 53 of file DynamicStats.h.
CreateStatId() [2/2]
template<typename TStatGroup> TStatId FDynamicStats::CreateStatId (const FString & StatNameOrDescription) inline static
Create a new stat id and registers it with the stats system.
This is the only way to create dynamic stat ids at runtime. Can be used only with FScopeCycleCounters.
Store the created stat id. Expensive method, avoid calling that method every frame.
Example: FDynamicStats::CreateStatId<STAT_GROUP_TO_FStatGroup(STATGROUP_UObjects)>(FString::Printf(TEXT("MyDynamicStat_%i"),Index))
Definition at line 23 of file DynamicStats.h.
References FName.
Referenced by UE::MovieScene::FPropertyRegistry::DefinePropertyImpl().
CreateStatIdDouble()
template<typename TStatGroup> TStatId FDynamicStats::CreateStatIdDouble (const FString & StatNameOrDescription, bool bIsAccumulator = false) inline static
Definition at line 43 of file DynamicStats.h.
References FName.
CreateStatIdInt64()
template<typename TStatGroup> TStatId FDynamicStats::CreateStatIdInt64 (const FString & StatNameOrDescription, bool bIsAccumulator = false) inline static
Definition at line 33 of file DynamicStats.h.
References FName.
The documentation for this struct was generated from the following file:
Runtime/Core/Public/Stats/DynamicStats.h