Unreal Engine 5.6 C++ API: FCanLoadMap Struct Reference
FCanLoadMap Struct Reference
Helper struct for the FOnLoadMap delegate.
#include "Editor.h"
Public Member Functions
FCanLoadMap ()
FCanLoadMap (const FCanLoadMap &)=delete
FCanLoadMap (FCanLoadMap &&)=delete
bool Get () const
void SetFalse ()
Private Attributes
bool bResult
Detailed Description
Helper struct for the FOnLoadMap delegate.
Definition at line 62 of file Editor.h.
Constructor & Destructor Documentation
FCanLoadMap() [1/3]
FCanLoadMap::FCanLoadMap () inline
Definition at line 65 of file Editor.h.
References bResult.
Referenced by FCanLoadMap(), and FCanLoadMap().
FCanLoadMap() [2/3]
FCanLoadMap::FCanLoadMap (const FCanLoadMap &) delete
References FCanLoadMap().
FCanLoadMap() [3/3]
FCanLoadMap::FCanLoadMap (FCanLoadMap &&) delete
References FCanLoadMap().
Member Function Documentation
Get()
bool FCanLoadMap::Get () const inline
Definition at line 70 of file Editor.h.
References bResult.
SetFalse()
void FCanLoadMap::SetFalse () inline
Definition at line 69 of file Editor.h.
References bResult.
Field Documentation
bResult
bool FCanLoadMap::bResult private
Definition at line 72 of file Editor.h.
Referenced by FCanLoadMap(), Get(), and SetFalse().
The documentation for this struct was generated from the following file:
Editor/UnrealEd/Public/Editor.h