Unreal Engine 5.6 C++ API: FUnixPlatformProcess Struct Reference
FUnixPlatformProcess Struct Reference
Unix implementation of the Process OS functions.
#include "UnixPlatformProcess.h"
Data Structures
class FProcEnumerator
Process enumerator.
struct FProcEnumInfo
Process enumeration info structure.
Static Public Member Functions
static const TCHAR * ApplicationSettingsDir ()
static bool CanLaunchURL (const TCHAR *URL)
static void CeaseBeingFirstInstance ()
Releases locks that we held for IsFirstInstance check.
static void ClosePipe (void *ReadPipe, void *WritePipe)
static void CloseProc (FProcHandle &ProcessHandle)
static const TCHAR * ComputerName ()
static bool CreatePipe (void *&ReadPipe, void *&WritePipe, bool bWritePipeLocal=false)
static FProcHandle CreateProc (const TCHAR *URL, const TCHAR *Parms, bool bLaunchDetached, bool bLaunchHidden, bool bLaunchReallyHidden, uint32 *OutProcessID, int32 PriorityModifier, const TCHAR *OptionalWorkingDirectory, void *PipeWriteChild, void *PipeReadChild, void *PipeStdErrChild)
static FProcHandle CreateProc (const TCHAR *URL, const TCHAR *Parms, bool bLaunchDetached, bool bLaunchHidden, bool bLaunchReallyHidden, uint32 *OutProcessID, int32 PriorityModifier, const TCHAR *OptionalWorkingDirectory, void *PipeWriteChild, void *PipeReadChild=nullptr)
static class FRunnableThread * CreateRunnableThread ()
static bool Daemonize ()
static bool ExecProcess (const TCHAR *URL, const TCHAR *Params, int32 *OutReturnCode, FString *OutStdOut, FString *OutStdErr, const TCHAR *OptionalWorkingDirectory=NULL, bool bShouldEndWithParentProcess=false)
static const TCHAR * ExecutableName (bool bRemoveExtension=true)
static const TCHAR * ExecutablePath ()
static void ExploreFolder (const TCHAR *FilePath)
static void FreeDllHandle (void *DllHandle)
static FString GenerateApplicationPath (const FString &AppName, EBuildConfiguration BuildConfiguration)
static FString GetApplicationName (uint32 ProcessId)
static FString GetApplicationSettingsDir (const ApplicationSettingsContext &Settings)
static uint32 GetCurrentCoreNumber ()
static uint32 GetCurrentProcessId ()
static FString GetCurrentWorkingDirectory ()
static void * GetDllExport (void *DllHandle, const TCHAR *ProcName)
static void * GetDllHandle (const TCHAR *Filename)
static const TCHAR * GetModuleExtension ()
static const TCHAR * GetModulePrefix ()
static const FString GetModulesDirectory ()
static bool GetPerFrameProcessorUsage (uint32 ProcessId, float &ProcessUsageFraction, float &IdleUsageFraction)
static bool GetProcReturnCode (FProcHandle &ProcHandle, int32 *ReturnCode)
static bool IsApplicationRunning (const TCHAR *ProcName)
static bool IsApplicationRunning (uint32 ProcessId)
static bool IsFirstInstance ()
static bool IsProcRunning (FProcHandle &ProcessHandle)
static bool LaunchFileInDefaultExternalApplication (const TCHAR *FileName, const TCHAR *Parms=NULL, ELaunchVerb::Type Verb=ELaunchVerb::Open, bool bPromptToOpenOnFailure=true)
static void LaunchURL (const TCHAR *URL, const TCHAR *Parms, FString *Error)
static void OnChildEndFramePostFork ()
static FProcHandle OpenProcess (uint32 ProcessID)
static FString ReadPipe (void *ReadPipe)
static bool ReadPipeToArray (void *ReadPipe, TArray< uint8 > &Output)
static void SetCurrentWorkingDirectoryToBaseDir ()
static bool SetProcessLimits (EProcessResource::Type Resource, uint64 Limit)
static void SetThreadNiceValue (uint32_t ThreadId, int32 NiceValue)
static void SetThreadPriority (EThreadPriority NewPriority)
static void TerminateProc (FProcHandle &ProcessHandle, bool KillTree=false)
static int32 TranslateThreadPriority (EThreadPriority Priority)
static const TCHAR * UserDir ()
static const TCHAR * UserHomeDir ()
Returns user home directory (i.e.
static const TCHAR * UserName (bool bOnlyAlphaNumeric=true)
static const TCHAR * UserSettingsDir ()
static const TCHAR * UserTempDir ()
static EWaitAndForkResult WaitAndFork ()
static void WaitForProc (FProcHandle &ProcessHandle)
static bool WritePipe (void *WritePipe, const FString &Message, FString *OutWritten=nullptr)
static bool WritePipe (void *WritePipe, const uint8 *Data, const int32 DataLength, int32 *OutDataLength=nullptr)
Static Public Member Functions inherited from FGenericPlatformProcess
static FORCEINLINE void AddDllDirectory (const TCHAR *Directory)
Adds a directory to search in when resolving implicitly loaded or filename-only DLLs.
static const TCHAR * ApplicationSettingsDir ()
Get application settings directory.
static const TCHAR * BaseDir ()
Get startup directory.
static bool CanLaunchURL (const TCHAR *URL)
Checks if the platform can launch a uniform resource locator (i.e.
static void CleanShaderWorkingDir ()
Clean the shader working directory.
static void ClosePipe (void *ReadPipe, void *WritePipe)
Closes an anonymous pipe.
static void CloseProc (FProcHandle &ProcessHandle)
Cleans up FProcHandle after we're done with it.
static const TCHAR * ComputerName ()
Get computer name.
static void ConditionalSleep (TFunctionRef< bool()> Condition, float SleepTime=0.0f)
Sleep thread until condition is satisfied.
static bool CreatePipe (void *&ReadPipe, void *&WritePipe, bool bWritePipeLocal=false)
Creates a writable anonymous pipe.
static FProcHandle CreateProc (const TCHAR *URL, const TCHAR *Parms, bool bLaunchDetached, bool bLaunchHidden, bool bLaunchReallyHidden, uint32 *OutProcessID, int32 PriorityModifier, const TCHAR *OptionalWorkingDirectory, void *PipeWriteChild, void *PipeReadChild, void *PipeStdErrChild)
Creates a new process and its primary thread, with separate std pipes.
static FProcHandle CreateProc (const TCHAR *URL, const TCHAR *Parms, bool bLaunchDetached, bool bLaunchHidden, bool bLaunchReallyHidden, uint32 *OutProcessID, int32 PriorityModifier, const TCHAR *OptionalWorkingDirectory, void *PipeWriteChild, void *PipeReadChild=nullptr)
Creates a new process and its primary thread.
static class FRunnableThread * CreateRunnableThread ()
Creates the platform-specific runnable thread.
static bool Daemonize ()
Makes process run as a system service (daemon), i.e.
static bool DeleteInterprocessSynchObject (FSemaphore *Object)
Deletes an interprocess synchronization object.
static void DumpThreadInfo (const TCHAR *MarkerName)
Output information about the currently active thread.
static bool ExecElevatedProcess (const TCHAR *URL, const TCHAR *Params, int32 *OutReturnCode)
Executes a process as administrator, requesting elevation as necessary.
static bool ExecProcess (const TCHAR *URL, const TCHAR *Params, int32 *OutReturnCode, FString *OutStdOut, FString *OutStdErr, const TCHAR *OptionalWorkingDirectory=NULL, bool bShouldEndWithParentProcess=false)
Executes a process, returning the return code, stdout, and stderr.
static const TCHAR * ExecutableName (bool bRemoveExtension=true)
Return the name of the currently running executable.
static const TCHAR * ExecutablePath ()
Return the path to the currently running executable.
static void ExploreFolder (const TCHAR *FilePath)
Attempt to "explore" the folder specified by the provided file path.
static void FlushPoolSyncEvents ()
Deletes all the recycled sync events contained by the pools.
static void FreeDllHandle (void *DllHandle)
Free a DLL.
static FString GenerateApplicationPath (const FString &AppName, EBuildConfiguration BuildConfiguration)
Generates the path to the specified application or game.
static bool GetApplicationMemoryUsage (uint32 ProcessId, SIZE_T *OutMemoryUsage)
Outputs the virtual memory usage, of the process with the specified PID.
static FString GetApplicationName (uint32 ProcessId)
Returns the Name of process given by the PID.
static FString GetApplicationSettingsDir (const ApplicationSettingsContext &Settings)
Get application settings directory for a given context.
static const TCHAR * GetArchitectureSuffix ()
Get the architecture suffix, if any.
static const TCHAR * GetBinariesSubdirectory ()
Used only by platforms with DLLs, this gives the subdirectory from binaries to find the executables.
static uint32 GetCurrentCoreNumber ()
Retrieves the current hardware CPU core.
static uint32 GetCurrentProcessId ()
Retrieves the ProcessId of this process.
static FString GetCurrentWorkingDirectory ()
Get the current working directory (only really makes sense on desktop platforms)
static ENamedThreads::Type GetDesiredThreadForUObjectReferenceCollector ()
specifies the thread to use for UObject reference collection
static FORCEINLINE void GetDllDirectories (TArray< FString > &OutDllDirectories)
Get the list of registered directories to search in when resolving implicitly loaded or filename-only DLLs.
static void * GetDllExport (void *DllHandle, const TCHAR *ProcName)
Lookup the address of a DLL function.
static void * GetDllHandle (const TCHAR *Filename)
Load a DLL.
static FString GetGameBundleId ()
Retrieves the platform-specific bundle identifier or package name of the game.
static const TCHAR * GetModuleExtension ()
Return the extension of dynamic library.
static const TCHAR * GetModulePrefix ()
Return the prefix of dynamic library (e.g.
static const FString GetModulesDirectory ()
Used only by platforms with DLLs, this gives the full path to the main directory containing modules.
static bool GetPerFrameProcessorUsage (uint32 ProcessId, float &ProcessUsageFraction, float &IdleUsageFraction)
Retrieves the current CPU Utilization for the current process in terms of percentage of all capacity.
static bool GetProcReturnCode (FProcHandle &ProcHandle, int32 *ReturnCode)
Retrieves the termination status of the specified process.
static uint32 GetStackSize ()
Get the active stack size for the currently running thread.
static class FEvent * GetSynchEventFromPool (bool bIsManualReset=false)
Gets an event from the pool or creates a new one if necessary.
static bool IsApplicationRunning (const TCHAR *ProcName)
Returns true if the specified application is running.
static bool IsApplicationRunning (uint32 ProcessId)
Returns true if the specified application is running.
static bool IsFirstInstance ()
Checks if we're the first instance.
static bool IsProcRunning (FProcHandle &ProcessHandle)
Returns true if the specified process is running.
static bool LaunchFileInDefaultExternalApplication (const TCHAR *FileName, const TCHAR *Parms=NULL, ELaunchVerb::Type Verb=ELaunchVerb::Open, bool bPromptToOpenOnFailure=true)
Attempt to launch the provided file name in its default external application.
static void LaunchURL (const TCHAR *URL, const TCHAR *Parms, FString *Error)
Launch a uniform resource locator (i.e.
static bool LaunchURLFiltered (const TCHAR *URL, const TCHAR *Parms, FString *Error, const UE::Core::FURLRequestFilter &Filter)
Launch a uniform resource locator (i.e.
static void ModifyThreadAssignmentForUObjectReferenceCollector (int32 &NumThreads, int32 &NumBackgroundThreads, ENamedThreads::Type &NormalThreadName, ENamedThreads::Type &BackgroundThreadName)
allows a platform to override the threading configuration for reference collection
static bool ModuleExists (const FString &Filename)
Used only by platforms with DLLs, this confirms the existence of a given module.
static FSemaphore * NewInterprocessSynchObject (const FString &Name, bool bCreate, uint32 MaxLocks=1)
Creates or opens an interprocess synchronization object.
static FSemaphore * NewInterprocessSynchObject (const TCHAR *Name, bool bCreate, uint32 MaxLocks=1)
Creates or opens an interprocess synchronization object.
static FProcHandle OpenProcess (uint32 ProcessID)
Opens an existing process.
static FORCEINLINE void PopDllDirectory (const TCHAR *Directory)
Unsets a directory to look for DLL files.
static FORCEINLINE void PushDllDirectory (const TCHAR *Directory)
Set a directory to look for DLL files.
static FString ReadPipe (void *ReadPipe)
Reads all pending data from an anonymous pipe, such as STDOUT or STDERROR of a process.
static bool ReadPipeToArray (void *ReadPipe, TArray< uint8 > &Output)
Reads all pending data from an anonymous pipe, such as STDOUT or STDERROR of a process.
static void ReturnSynchEventToPool (FEvent *Event)
Returns an event to the pool.
static void SetCurrentWorkingDirectoryToBaseDir ()
static bool SetProcessLimits (EProcessResource::Type Resource, uint64 Limit)
Sets the process limits.
static void SetShaderDir (const TCHAR *Where)
static void SetThreadAffinityMask (uint64 AffinityMask)
Change the thread processor affinity.
static void SetThreadName (const TCHAR *ThreadName)
Helper function to set thread name of the current thread.
static void SetThreadPriority (EThreadPriority NewPriority)
Change the thread processor priority.
static void SetupAudioThread ()
Allow the platform to do anything it needs for audio thread.
static void SetupGameThread ()
Allow the platform to do anything it needs for game thread.
static void SetupRenderThread ()
Allow the platform to do anything it needs for render thread.
static const TCHAR * ShaderDir ()
static const FString ShaderWorkingDir ()
Get the shader working directory.
static bool ShouldSaveToUserDir ()
Content saved to the game or engine directories should be rerouted to user directories instead.
static bool SkipWaitForStats ()
force skip calling FThreadStats::WaitForStats()
static bool SupportsMultithreading ()
Gets whether this platform can use multiple threads.
static void TearDown ()
Tears down allocated process resources.
static void TeardownAudioThread ()
Allow the platform to tear down the audio thread.
static void TerminateProc (FProcHandle &ProcessHandle, bool KillTree=false)
Terminates a process.
static void TerminateProcTreeWithPredicate (FProcHandle &ProcessHandle, TFunctionRef< bool(uint32 ProcessId, const TCHAR *ApplicationName)> Predicate)
Terminates a process tree.
static bool TryGetMemoryUsage (FProcHandle &ProcessHandle, FPlatformProcessMemoryStats &OutStats)
Queries the memory usage of the process.
static const TCHAR * UserDir ()
Get user directory.
static const TCHAR * UserHomeDir ()
Get the user home directory.
static const TCHAR * UserName (bool bOnlyAlphaNumeric=true)
Get user name.
static const TCHAR * UserSettingsDir ()
Get the user settings directory.
static const TCHAR * UserTempDir ()
Get the user temporary directory.
static EWaitAndForkResult WaitAndFork ()
Waits for process signals and forks child processes.
static void WaitForProc (FProcHandle &ProcessHandle)
Waits for a process to stop.
static bool WritePipe (void *WritePipe, const FString &Message, FString *OutWritten=nullptr)
Sends the message to process through pipe.
static bool WritePipe (void *WritePipe, const uint8 *Data, const int32 DataLength, int32 *OutDataLength=nullptr)
Sends data to process through pipe.
static FORCEINLINE void Yield ()
Tells the processor to pause for implementation-specific amount of time.
static FORCEINLINE void YieldCycles (uint64 Cycles)
Tells the processor to pause for at least the amount of cycles given.
Additional Inherited Members
Public Types inherited from FGenericPlatformProcess
enum class EWaitAndForkResult : uint8 { Error , Parent , Child }
Public Member Functions inherited from FGenericPlatformProcess
UE_DEPRECATED (5.0, "Please use GetSynchEventFromPool to create a new event, and ReturnSynchEventToPool to release the event.") static 1 class FEvent *CreateSynchEvent(bool bIsManualReset
Creates a new event.
Detailed Description
Unix implementation of the Process OS functions.
Definition at line 208 of file UnixPlatformProcess.h.
Member Function Documentation
ApplicationSettingsDir()
const TCHAR * FUnixPlatformProcess::ApplicationSettingsDir () static
CanLaunchURL()
bool FUnixPlatformProcess::CanLaunchURL (const TCHAR * URL) static
CeaseBeingFirstInstance()
void FUnixPlatformProcess::CeaseBeingFirstInstance () static
Releases locks that we held for IsFirstInstance check.
ClosePipe()
void FUnixPlatformProcess::ClosePipe (void * ReadPipe, void * WritePipe) static
References ReadPipe(), and WritePipe().
CloseProc()
void FUnixPlatformProcess::CloseProc (FProcHandle & ProcessHandle) static
ComputerName()
const TCHAR * FUnixPlatformProcess::ComputerName () static
CreatePipe()
bool FUnixPlatformProcess::CreatePipe (void *& ReadPipe, void *& WritePipe, bool bWritePipeLocal = false) static
References ReadPipe(), and WritePipe().
CreateProc() [1/2]
FProcHandle FUnixPlatformProcess::CreateProc (const TCHAR * URL, const TCHAR * Parms, bool bLaunchDetached, bool bLaunchHidden, bool bLaunchReallyHidden, uint32 * OutProcessID, int32 PriorityModifier, const TCHAR * OptionalWorkingDirectory, void * PipeWriteChild, void * PipeReadChild, void * PipeStdErrChild) static
CreateProc() [2/2]
FProcHandle FUnixPlatformProcess::CreateProc (const TCHAR * URL, const TCHAR * Parms, bool bLaunchDetached, bool bLaunchHidden, bool bLaunchReallyHidden, uint32 * OutProcessID, int32 PriorityModifier, const TCHAR * OptionalWorkingDirectory, void * PipeWriteChild, void * PipeReadChild = nullptr) static
CreateRunnableThread()
class FRunnableThread * FUnixPlatformProcess::CreateRunnableThread () static
Daemonize()
bool FUnixPlatformProcess::Daemonize () static
ExecProcess()
bool FUnixPlatformProcess::ExecProcess (const TCHAR * URL, const TCHAR * Params, int32 * OutReturnCode, FString * OutStdOut, FString * OutStdErr, const TCHAR * OptionalWorkingDirectory = NULL, bool bShouldEndWithParentProcess = false) static
References Params.
ExecutableName()
const TCHAR * FUnixPlatformProcess::ExecutableName (bool bRemoveExtension = true) static
ExecutablePath()
const TCHAR * FUnixPlatformProcess::ExecutablePath () static
ExploreFolder()
void FUnixPlatformProcess::ExploreFolder (const TCHAR * FilePath) static
FreeDllHandle()
void FUnixPlatformProcess::FreeDllHandle (void * DllHandle) static
GenerateApplicationPath()
FString FUnixPlatformProcess::GenerateApplicationPath (const FString & AppName, EBuildConfiguration BuildConfiguration) static
GetApplicationName()
FString FUnixPlatformProcess::GetApplicationName (uint32 ProcessId) static
GetApplicationSettingsDir()
FString FUnixPlatformProcess::GetApplicationSettingsDir (const ApplicationSettingsContext & Settings) static
GetCurrentCoreNumber()
uint32 FUnixPlatformProcess::GetCurrentCoreNumber () static
GetCurrentProcessId()
uint32 FUnixPlatformProcess::GetCurrentProcessId () static
GetCurrentWorkingDirectory()
FString FUnixPlatformProcess::GetCurrentWorkingDirectory () static
GetDllExport()
void * FUnixPlatformProcess::GetDllExport (void * DllHandle, const TCHAR * ProcName) static
GetDllHandle()
void * FUnixPlatformProcess::GetDllHandle (const TCHAR * Filename) static
References Filename.
GetModuleExtension()
const TCHAR * FUnixPlatformProcess::GetModuleExtension () static
GetModulePrefix()
const TCHAR * FUnixPlatformProcess::GetModulePrefix () static
GetModulesDirectory()
const FString FUnixPlatformProcess::GetModulesDirectory () static
GetPerFrameProcessorUsage()
bool FUnixPlatformProcess::GetPerFrameProcessorUsage (uint32 ProcessId, float & ProcessUsageFraction, float & IdleUsageFraction) static
GetProcReturnCode()
bool FUnixPlatformProcess::GetProcReturnCode (FProcHandle & ProcHandle, int32 * ReturnCode) static
IsApplicationRunning() [1/2]
bool FUnixPlatformProcess::IsApplicationRunning (const TCHAR * ProcName) static
IsApplicationRunning() [2/2]
bool FUnixPlatformProcess::IsApplicationRunning (uint32 ProcessId) static
IsFirstInstance()
bool FUnixPlatformProcess::IsFirstInstance () static
IsProcRunning()
bool FUnixPlatformProcess::IsProcRunning (FProcHandle & ProcessHandle) static
LaunchFileInDefaultExternalApplication()
bool FUnixPlatformProcess::LaunchFileInDefaultExternalApplication (const TCHAR * FileName, const TCHAR * Parms = NULL, ELaunchVerb::Type Verb = ELaunchVerb::Open, bool bPromptToOpenOnFailure = true) static
References ELaunchVerb::Open.
LaunchURL()
void FUnixPlatformProcess::LaunchURL (const TCHAR * URL, const TCHAR * Parms, FString * Error) static
References FGenericPlatformProcess::Error.
OnChildEndFramePostFork()
void FUnixPlatformProcess::OnChildEndFramePostFork () static
OpenProcess()
FProcHandle FUnixPlatformProcess::OpenProcess (uint32 ProcessID) static
ReadPipe()
FString FUnixPlatformProcess::ReadPipe (void * ReadPipe) static
References ReadPipe().
Referenced by ClosePipe(), CreatePipe(), ReadPipe(), and ReadPipeToArray().
ReadPipeToArray()
bool FUnixPlatformProcess::ReadPipeToArray (void * ReadPipe, TArray< uint8 > & Output) static
References ReadPipe().
SetCurrentWorkingDirectoryToBaseDir()
void FUnixPlatformProcess::SetCurrentWorkingDirectoryToBaseDir () static
SetProcessLimits()
bool FUnixPlatformProcess::SetProcessLimits (EProcessResource::Type Resource, uint64 Limit) static
SetThreadNiceValue()
void FUnixPlatformProcess::SetThreadNiceValue (uint32_t ThreadId, int32 NiceValue) static
SetThreadPriority()
void FUnixPlatformProcess::SetThreadPriority (EThreadPriority NewPriority) static
TerminateProc()
void FUnixPlatformProcess::TerminateProc (FProcHandle & ProcessHandle, bool KillTree = false) static
TranslateThreadPriority()
int32 FUnixPlatformProcess::TranslateThreadPriority (EThreadPriority Priority) static
UserDir()
const TCHAR * FUnixPlatformProcess::UserDir () static
UserHomeDir()
const TCHAR * FUnixPlatformProcess::UserHomeDir () static
Returns user home directory (i.e.
$HOME).
Like other directory functions, cannot return nullptr!
UserName()
const TCHAR * FUnixPlatformProcess::UserName (bool bOnlyAlphaNumeric = true) static
UserSettingsDir()
const TCHAR * FUnixPlatformProcess::UserSettingsDir () static
UserTempDir()
const TCHAR * FUnixPlatformProcess::UserTempDir () static
WaitAndFork()
EWaitAndForkResult FUnixPlatformProcess::WaitAndFork () static
WaitForProc()
void FUnixPlatformProcess::WaitForProc (FProcHandle & ProcessHandle) static
WritePipe() [1/2]
bool FUnixPlatformProcess::WritePipe (void * WritePipe, const FString & Message, FString * OutWritten = nullptr) static
References WritePipe().
Referenced by ClosePipe(), CreatePipe(), WritePipe(), and WritePipe().
WritePipe() [2/2]
bool FUnixPlatformProcess::WritePipe (void * WritePipe, const uint8 * Data, const int32 DataLength, int32 * OutDataLength = nullptr) static
References WritePipe().
The documentation for this struct was generated from the following file:
Runtime/Core/Public/Unix/UnixPlatformProcess.h