Unreal Engine 5.6 C++ API: UE::GC::TDirectDispatcher< ProcessorType > Struct Template Reference
UE::GC::TDirectDispatcher< ProcessorType > Struct Template Reference
Forwards references directly to ProcessorType::HandleTokenStreamObjectReference(), unlike TBatchDispatcher.
#include "FastReferenceCollector.h"
Public Types
typedef FDebugSchemaStackScope SchemaStackScopeType
Public Member Functions
FORCEINLINE void HandleImmutableReference (UObject *Object, FMemberId MemberId, EOrigin Origin) const
FORCEINLINE void HandleKillableArray (Private::FStridedReferenceArray Array, FMemberId MemberId, EOrigin Origin) const
FORCEINLINE void HandleKillableArray (TArray< UObject * > &Array, FMemberId MemberId, EOrigin Origin) const
FORCEINLINE void HandleKillableReference (UObject *&Object, FMemberId MemberId, EOrigin Origin) const
template<class ArrayType>
FORCEINLINE void HandleKillableReferences (ArrayType &&Objects, FMemberId MemberId, EOrigin Origin) const
FORCEINLINE void HandleReferenceDirectly (UObject *ReferencingObject, UObject *&Object, FMemberId MemberId, EOrigin Origin, bool bAllowReferenceElimination) const
void SetDebugSchemaStackMemberId (FMemberId Member)
void Suspend ()
Data Fields
FReferenceCollector & Collector
FWorkerContext & Context
ProcessorType & Processor
Static Public Attributes
static constexpr bool bBatching = false
static constexpr bool bParallel = IsParallel(ProcessorType::Options)
Detailed Description
template<class ProcessorType>
struct UE::GC::TDirectDispatcher< ProcessorType >
Forwards references directly to ProcessorType::HandleTokenStreamObjectReference(), unlike TBatchDispatcher.
Definition at line 753 of file FastReferenceCollector.h.
Member Typedef Documentation
SchemaStackScopeType
template<class ProcessorType> typedef FDebugSchemaStackScope UE::GC::TDirectDispatcher< ProcessorType >::SchemaStackScopeType
Definition at line 758 of file FastReferenceCollector.h.
Member Function Documentation
HandleImmutableReference()
template<class ProcessorType> FORCEINLINE void UE::GC::TDirectDispatcher< ProcessorType >::HandleImmutableReference (UObject * Object, FMemberId MemberId, EOrigin Origin) const inline
Definition at line 777 of file FastReferenceCollector.h.
References Context, FORCEINLINE, HandleReferenceDirectly(), and Origin.
HandleKillableArray() [1/2]
template<class ProcessorType> FORCEINLINE void UE::GC::TDirectDispatcher< ProcessorType >::HandleKillableArray (Private::FStridedReferenceArray Array, FMemberId MemberId, EOrigin Origin) const inline
Definition at line 796 of file FastReferenceCollector.h.
References Array, FORCEINLINE, HandleKillableReferences(), and Origin.
HandleKillableArray() [2/2]
template<class ProcessorType> FORCEINLINE void UE::GC::TDirectDispatcher< ProcessorType >::HandleKillableArray (TArray< UObject * > & Array, FMemberId MemberId, EOrigin Origin) const inline
Definition at line 791 of file FastReferenceCollector.h.
References Array, FORCEINLINE, HandleKillableReferences(), and Origin.
HandleKillableReference()
template<class ProcessorType> FORCEINLINE void UE::GC::TDirectDispatcher< ProcessorType >::HandleKillableReference (UObject *& Object, FMemberId MemberId, EOrigin Origin) const inline
Definition at line 772 of file FastReferenceCollector.h.
References Context, FORCEINLINE, HandleReferenceDirectly(), and Origin.
HandleKillableReferences()
template<class ProcessorType> template<class ArrayType> FORCEINLINE void UE::GC::TDirectDispatcher< ProcessorType >::HandleKillableReferences (ArrayType && Objects, FMemberId MemberId, EOrigin Origin) const inline
Definition at line 783 of file FastReferenceCollector.h.
References Context, FORCEINLINE, HandleReferenceDirectly(), and Origin.
Referenced by HandleKillableArray(), and HandleKillableArray().
HandleReferenceDirectly()
template<class ProcessorType> FORCEINLINE void UE::GC::TDirectDispatcher< ProcessorType >::HandleReferenceDirectly (UObject * ReferencingObject, UObject *& Object, FMemberId MemberId, EOrigin Origin, bool bAllowReferenceElimination) const inline
Definition at line 763 of file FastReferenceCollector.h.
References Context, FORCEINLINE, IsObjectHandleResolved_ForGC(), Origin, and Processor.
Referenced by HandleImmutableReference(), HandleKillableReference(), and HandleKillableReferences().
SetDebugSchemaStackMemberId()
template<class ProcessorType> void UE::GC::TDirectDispatcher< ProcessorType >::SetDebugSchemaStackMemberId (FMemberId Member) inline
Definition at line 841 of file FastReferenceCollector.h.
References Context.
Suspend()
template<class ProcessorType> void UE::GC::TDirectDispatcher< ProcessorType >::Suspend () inline
Definition at line 837 of file FastReferenceCollector.h.
Field Documentation
bBatching
template<class ProcessorType> bool UE::GC::TDirectDispatcher< ProcessorType >::bBatching = false static constexpr
Definition at line 755 of file FastReferenceCollector.h.
bParallel
template<class ProcessorType> bool UE::GC::TDirectDispatcher< ProcessorType >::bParallel = IsParallel(ProcessorType::Options) static constexpr
Definition at line 756 of file FastReferenceCollector.h.
Collector
template<class ProcessorType> FReferenceCollector& UE::GC::TDirectDispatcher< ProcessorType >::Collector
Definition at line 761 of file FastReferenceCollector.h.
Context
template<class ProcessorType> FWorkerContext& UE::GC::TDirectDispatcher< ProcessorType >::Context
Definition at line 760 of file FastReferenceCollector.h.
Referenced by HandleImmutableReference(), HandleKillableReference(), HandleKillableReferences(), HandleReferenceDirectly(), and SetDebugSchemaStackMemberId().
Processor
template<class ProcessorType> ProcessorType& UE::GC::TDirectDispatcher< ProcessorType >::Processor
Definition at line 759 of file FastReferenceCollector.h.
Referenced by HandleReferenceDirectly().
The documentation for this struct was generated from the following file:
Runtime/CoreUObject/Public/UObject/FastReferenceCollector.h