Unreal Engine 5.6 C++ API: FSimpleStreamableAssetManager::FUnregister Struct Reference
FSimpleStreamableAssetManager::FUnregister Struct Reference
#include "SimpleStreamableAssetManager.h"
Public Member Functions
FUnregister ()=default
FUnregister (const FUnregister &)=default
template<typename TObject>
FUnregister (const TObject *Object)
FUnregister (FUnregister &&)=default
FUnregister & operator= (const FUnregister &)=default
FUnregister & operator= (FUnregister &&)=default
Data Fields
union {
UPTRINT ObjectKey = 0
const FPrimitiveSceneProxy * SceneProxy_ForDebug
};
TSharedPtr< int32, ESPMode::ThreadSafe > ObjectRegistrationIndex {}
Detailed Description
Definition at line 154 of file SimpleStreamableAssetManager.h.
Constructor & Destructor Documentation
FUnregister() [1/4]
FSimpleStreamableAssetManager::FUnregister::FUnregister () default
Referenced by FUnregister(), FUnregister(), operator=(), and operator=().
FUnregister() [2/4]
FSimpleStreamableAssetManager::FUnregister::FUnregister (const FUnregister &) default
References FUnregister().
FUnregister() [3/4]
FSimpleStreamableAssetManager::FUnregister::FUnregister (FUnregister &&) default
References FUnregister().
FUnregister() [4/4]
template<typename TObject> FSimpleStreamableAssetManager::FUnregister::FUnregister (const TObject * Object) inline
Definition at line 173 of file SimpleStreamableAssetManager.h.
References Object, ObjectKey, ObjectRegistrationIndex, and SIMPLE_STREAMABLE_ASSET_MANAGER_ALLOW_DEBUG_POINTER.
Member Function Documentation
operator=() [1/2]
FUnregister & FSimpleStreamableAssetManager::FUnregister::operator= (const FUnregister &) default
References FUnregister().
operator=() [2/2]
FUnregister & FSimpleStreamableAssetManager::FUnregister::operator= (FUnregister &&) default
References FUnregister().
Field Documentation
[union]
union { ... } FSimpleStreamableAssetManager::FUnregister
ObjectKey
UPTRINT FSimpleStreamableAssetManager::FUnregister::ObjectKey = 0
Definition at line 161 of file SimpleStreamableAssetManager.h.
Referenced by FUnregister().
ObjectRegistrationIndex
TSharedPtr<int32, ESPMode::ThreadSafe> FSimpleStreamableAssetManager::FUnregister::ObjectRegistrationIndex {}
Definition at line 156 of file SimpleStreamableAssetManager.h.
Referenced by FUnregister().
SceneProxy_ForDebug
const FPrimitiveSceneProxy* FSimpleStreamableAssetManager::FUnregister::SceneProxy_ForDebug
Definition at line 162 of file SimpleStreamableAssetManager.h.
The documentation for this struct was generated from the following file:
Runtime/Engine/Public/Streaming/SimpleStreamableAssetManager.h