Unreal Engine 5.6 C++ API: FSceneViewFamily::ConstructionValues Struct Reference
FSceneViewFamily::ConstructionValues Struct Reference
Helper struct for creating FSceneViewFamily instances If created with specifying a time it will retrieve them from the world in the given scene.
#include "SceneView.h"
Public Member Functions
ConstructionValues (const ConstructionValues &Other)=default
PRAGMA_ENABLE_DEPRECATION_WARNINGS ConstructionValues (const FRenderTarget *InRenderTarget, FSceneInterface *InScene, const FEngineShowFlags &InEngineShowFlags)
PRAGMA_DISABLE_DEPRECATION_WARNINGS ConstructionValues (ConstructionValues &&)=default
ConstructionValues & operator= (const ConstructionValues &Other)=default
ConstructionValues & operator= (ConstructionValues &&)=default
ConstructionValues & SetAdditionalViewFamily (const bool Value)
Set whether the view family is additional.
ConstructionValues & SetDeferClear (const bool Value)
Set whether to defer the back buffer clearing to just before the back buffer is drawn to.
ConstructionValues & SetRealtimeUpdate (const bool Value)
Set whether the view family is updated in real-time.
ConstructionValues & SetRenderTargetDepth (const FRenderTarget *InRenderTargetDepth)
ConstructionValues & SetRequireMobileMultiView (const bool Value)
Setting to true results in scene color and depth being multiview-allocated.
ConstructionValues & SetResolveScene (const bool Value)
Setting to if true then results of scene rendering are copied/resolved to the RenderTarget.
ConstructionValues & SetTime (const FGameTime &InTime)
Set the world time and real time independently to handle time dilation.
ConstructionValues & SetViewModeParam (const int InViewModeParam, const FName &InViewModeParamName)
Set the view param.
Data Fields
uint32 bAdditionalViewFamily: 1
Indicates whether the view family is additional.
uint32 bDeferClear:1
Used to defer the back buffer clearing to just before the back buffer is drawn to.
uint32 bRealtimeUpdate:1
Indicates whether the view family is updated in real-time.
uint32 bRequireMultiView:1
True if scene color and depth should be multiview-allocated.
uint32 bResolveScene:1
If true then results of scene rendering are copied/resolved to the RenderTarget.
uint32 bTimesSet:1
Safety check to ensure valid times are set either from a valid world/scene pointer or via the SetWorldTimes function.
FEngineShowFlags EngineShowFlags
The engine show flags for the views.
const FRenderTarget * RenderTarget
The views which make up the family.
const FRenderTarget * RenderTargetDepth
FSceneInterface * Scene
The render target which the views are being rendered to.
FGameTime Time
The current time.
int32 ViewModeParam
Additional view params related to the current viewmode (example : texcoord index)
FName ViewModeParamName
An name bound to the current viewmode param.
Detailed Description
Helper struct for creating FSceneViewFamily instances If created with specifying a time it will retrieve them from the world in the given scene.
Parameters
InRenderTarget The render target which the views are being rendered to.
InScene The scene being viewed.
InShowFlags The show flags for the views.
Definition at line 2173 of file SceneView.h.
Constructor & Destructor Documentation
ConstructionValues() [1/3]
PRAGMA_DISABLE_DEPRECATION_WARNINGS FSceneViewFamily::ConstructionValues::ConstructionValues (ConstructionValues &&) default
References ConstructionValues().
Referenced by ConstructionValues(), ConstructionValues(), operator=(), operator=(), SetAdditionalViewFamily(), SetDeferClear(), SetRealtimeUpdate(), SetRenderTargetDepth(), SetRequireMobileMultiView(), SetResolveScene(), SetTime(), and SetViewModeParam().
ConstructionValues() [2/3]
FSceneViewFamily::ConstructionValues::ConstructionValues (const ConstructionValues & Other) default
References ConstructionValues(), and Other.
ConstructionValues() [3/3]
PRAGMA_ENABLE_DEPRECATION_WARNINGS FSceneViewFamily::ConstructionValues::ConstructionValues (const FRenderTarget * InRenderTarget, FSceneInterface * InScene, const FEngineShowFlags & InEngineShowFlags)
Member Function Documentation
operator=() [1/2]
ConstructionValues & FSceneViewFamily::ConstructionValues::operator= (const ConstructionValues & Other) default
References ConstructionValues(), Other, and PRAGMA_ENABLE_DEPRECATION_WARNINGS.
operator=() [2/2]
ConstructionValues & FSceneViewFamily::ConstructionValues::operator= (ConstructionValues &&) default
References ConstructionValues().
SetAdditionalViewFamily()
ConstructionValues & FSceneViewFamily::ConstructionValues::SetAdditionalViewFamily (const bool Value) inline
Set whether the view family is additional.
Definition at line 2239 of file SceneView.h.
References ConstructionValues(), bAdditionalViewFamily, and Value.
SetDeferClear()
ConstructionValues & FSceneViewFamily::ConstructionValues::SetDeferClear (const bool Value) inline
Set whether to defer the back buffer clearing to just before the back buffer is drawn to.
Definition at line 2245 of file SceneView.h.
References ConstructionValues(), bDeferClear, and Value.
SetRealtimeUpdate()
ConstructionValues & FSceneViewFamily::ConstructionValues::SetRealtimeUpdate (const bool Value) inline
Set whether the view family is updated in real-time.
Definition at line 2242 of file SceneView.h.
References ConstructionValues(), bRealtimeUpdate, and Value.
SetRenderTargetDepth()
ConstructionValues & FSceneViewFamily::ConstructionValues::SetRenderTargetDepth (const FRenderTarget * InRenderTargetDepth) inline
Definition at line 2224 of file SceneView.h.
References ConstructionValues(), and RenderTargetDepth.
SetRequireMobileMultiView()
ConstructionValues & FSceneViewFamily::ConstructionValues::SetRequireMobileMultiView (const bool Value) inline
Setting to true results in scene color and depth being multiview-allocated.
Definition at line 2251 of file SceneView.h.
References ConstructionValues(), bRequireMultiView, and Value.
SetResolveScene()
ConstructionValues & FSceneViewFamily::ConstructionValues::SetResolveScene (const bool Value) inline
Setting to if true then results of scene rendering are copied/resolved to the RenderTarget.
Definition at line 2248 of file SceneView.h.
References ConstructionValues(), bResolveScene, and Value.
SetTime()
ConstructionValues & FSceneViewFamily::ConstructionValues::SetTime (const FGameTime & InTime) inline
Set the world time and real time independently to handle time dilation.
Definition at line 2231 of file SceneView.h.
References ConstructionValues(), bTimesSet, InTime, and Time.
SetViewModeParam()
ConstructionValues & FSceneViewFamily::ConstructionValues::SetViewModeParam (const int InViewModeParam, const FName & InViewModeParamName) inline
Set the view param.
Definition at line 2254 of file SceneView.h.
References ConstructionValues(), ViewModeParam, and ViewModeParamName.
Field Documentation
bAdditionalViewFamily
uint32 FSceneViewFamily::ConstructionValues::bAdditionalViewFamily
Indicates whether the view family is additional.
Definition at line 2207 of file SceneView.h.
Referenced by SetAdditionalViewFamily().
bDeferClear
uint32 FSceneViewFamily::ConstructionValues::bDeferClear
Used to defer the back buffer clearing to just before the back buffer is drawn to.
Definition at line 2213 of file SceneView.h.
Referenced by SetDeferClear().
bRealtimeUpdate
uint32 FSceneViewFamily::ConstructionValues::bRealtimeUpdate
Indicates whether the view family is updated in real-time.
Definition at line 2210 of file SceneView.h.
Referenced by SetRealtimeUpdate().
bRequireMultiView
uint32 FSceneViewFamily::ConstructionValues::bRequireMultiView
True if scene color and depth should be multiview-allocated.
Definition at line 2222 of file SceneView.h.
Referenced by SetRequireMobileMultiView().
bResolveScene
uint32 FSceneViewFamily::ConstructionValues::bResolveScene
If true then results of scene rendering are copied/resolved to the RenderTarget.
Definition at line 2216 of file SceneView.h.
Referenced by SetResolveScene().
bTimesSet
uint32 FSceneViewFamily::ConstructionValues::bTimesSet
Safety check to ensure valid times are set either from a valid world/scene pointer or via the SetWorldTimes function.
Definition at line 2219 of file SceneView.h.
Referenced by SetTime().
EngineShowFlags
FEngineShowFlags FSceneViewFamily::ConstructionValues::EngineShowFlags
The engine show flags for the views.
Definition at line 2196 of file SceneView.h.
RenderTarget
const FRenderTarget* FSceneViewFamily::ConstructionValues::RenderTarget
The views which make up the family.
Definition at line 2189 of file SceneView.h.
RenderTargetDepth
const FRenderTarget* FSceneViewFamily::ConstructionValues::RenderTargetDepth
Definition at line 2190 of file SceneView.h.
Referenced by SetRenderTargetDepth().
Scene
FSceneInterface* FSceneViewFamily::ConstructionValues::Scene
The render target which the views are being rendered to.
Definition at line 2193 of file SceneView.h.
Time
FGameTime FSceneViewFamily::ConstructionValues::Time
The current time.
Definition at line 2204 of file SceneView.h.
Referenced by SetTime().
ViewModeParam
int32 FSceneViewFamily::ConstructionValues::ViewModeParam
Additional view params related to the current viewmode (example : texcoord index)
Definition at line 2199 of file SceneView.h.
Referenced by SetViewModeParam().
ViewModeParamName
FName FSceneViewFamily::ConstructionValues::ViewModeParamName
An name bound to the current viewmode param.
(example : texture name)
Definition at line 2201 of file SceneView.h.
Referenced by SetViewModeParam().
The documentation for this struct was generated from the following file:
Runtime/Engine/Public/SceneView.h