Unreal Engine 5.6 C++ API: UE::MovieScene::TEntityBuilderImpl< TIntegerSequence< int > > Struct Reference
UE::MovieScene::TEntityBuilderImpl< TIntegerSequence< int > > Struct Reference
#include "MovieSceneEntityBuilder.h"
Public Member Functions
template<typename U, typename PayloadType>
TEntityBuilder< TAdd< U > > Add (TComponentTypeID< U > ComponentType, PayloadType &&InPayload)
Add a component to the entity with a specific value.
template<typename U, typename PayloadType>
TEntityBuilder< TAddConditional< U > > AddConditional (TComponentTypeID< U > ComponentType, PayloadType &&InPayload, bool bCondition)
Conditionally add a component to the entity with a specific value.
TEntityBuilder< FAdd > AddDefaulted (FComponentTypeID ComponentType)
Add the specified default-constructed component type to the entity.
TEntityBuilder< FAddConditional > AddDefaultedConditional (FComponentTypeID ComponentType, bool bCondition)
Add the specified default-constructed component to the entity if a condition is met.
TEntityBuilder< FAddMany > AddMany (const FComponentMask &InComponentsToAdd)
Add all the specified default-constructed component type to the entity.
TEntityBuilder< FAdd > AddTag (FComponentTypeID TagType)
Add the specified tag to the entity.
TEntityBuilder< FAddConditional > AddTagConditional (FComponentTypeID TagType, bool bCondition)
Add the specified tag to the entity if a condition is met.
template<typename U>
TEntityBuilder< U > Append (U &&InOther)
Append another component type to this builder.
Detailed Description
Definition at line 129 of file MovieSceneEntityBuilder.h.
Member Function Documentation
Add()
template<typename U, typename PayloadType> TEntityBuilder< TAdd< U > > UE::MovieScene::TEntityBuilderImpl< TIntegerSequence< int > >::Add (TComponentTypeID< U > ComponentType, PayloadType && InPayload) inline
Add a component to the entity with a specific value.
Parameters
ComponentType The component type ID to add to the entity. Must be valid.
InPayload User-specified data to forward into the component
Returns
A new builder that includes the new component and payload
Definition at line 591 of file MovieSceneEntityBuilder.h.
References Forward().
AddConditional()
template<typename U, typename PayloadType> TEntityBuilder< TAddConditional< U > > UE::MovieScene::TEntityBuilderImpl< TIntegerSequence< int > >::AddConditional (TComponentTypeID< U > ComponentType, PayloadType && InPayload, bool bCondition) inline
Conditionally add a component to the entity with a specific value.
Parameters
ComponentType The component type ID to add to the entity. Must be valid if bCondition is true.
InPayload User-specified data to forward into the component
bCondition Condition specifying whether this component should be added or not
Returns
A new builder that includes the new component and payload
Definition at line 597 of file MovieSceneEntityBuilder.h.
References AddConditional(), and Forward().
Referenced by AddConditional().
AddDefaulted()
TEntityBuilder< FAdd > UE::MovieScene::TEntityBuilderImpl< TIntegerSequence< int > >::AddDefaulted (FComponentTypeID ComponentType) inline
Add the specified default-constructed component type to the entity.
Parameters
ComponentType A valid component type or tag ID to add. Must be valid.
Returns
A new builder that includes the new component
Definition at line 565 of file MovieSceneEntityBuilder.h.
References AddDefaulted().
Referenced by AddDefaulted().
AddDefaultedConditional()
TEntityBuilder< FAddConditional > UE::MovieScene::TEntityBuilderImpl< TIntegerSequence< int > >::AddDefaultedConditional (FComponentTypeID ComponentType, bool bCondition) inline
Add the specified default-constructed component to the entity if a condition is met.
Parameters
ComponentType A valid component type ID to add. Must be valid.
bCondition Condition specifying whether this tag should be added or not
Returns
A new builder that includes the new component
Definition at line 580 of file MovieSceneEntityBuilder.h.
References AddDefaultedConditional().
Referenced by AddDefaultedConditional().
AddMany()
TEntityBuilder< FAddMany > UE::MovieScene::TEntityBuilderImpl< TIntegerSequence< int > >::AddMany (const FComponentMask & InComponentsToAdd) inline
Add all the specified default-constructed component type to the entity.
Parameters
InComponentsToAdd A (possibly empty) component mask that defines all the components to add
Returns
A new builder that includes the new component
Definition at line 570 of file MovieSceneEntityBuilder.h.
References AddMany().
Referenced by AddMany().
AddTag()
TEntityBuilder< FAdd > UE::MovieScene::TEntityBuilderImpl< TIntegerSequence< int > >::AddTag (FComponentTypeID TagType) inline
Add the specified tag to the entity.
Equivalent to AddDefaulted.
Parameters
Tag A valid component tag ID to add. Must be valid.
Returns
A new builder that includes the new component
Definition at line 575 of file MovieSceneEntityBuilder.h.
References AddTag().
Referenced by AddTag().
AddTagConditional()
TEntityBuilder< FAddConditional > UE::MovieScene::TEntityBuilderImpl< TIntegerSequence< int > >::AddTagConditional (FComponentTypeID TagType, bool bCondition) inline
Add the specified tag to the entity if a condition is met.
Parameters
Tag A valid component tag ID to add. Must be valid.
bCondition Condition specifying whether this tag should be added or not
Returns
A new builder that includes the new component
Definition at line 585 of file MovieSceneEntityBuilder.h.
References AddTagConditional().
Referenced by AddTagConditional().
Append()
template<typename U> TEntityBuilder< U > UE::MovieScene::TEntityBuilderImpl< TIntegerSequence< int > >::Append (U && InOther)
Append another component type to this builder.
Returns
A new builder that includes the new component
Definition at line 603 of file MovieSceneEntityBuilder.h.
References MoveTemp().
The documentation for this struct was generated from the following file:
Runtime/MovieScene/Public/EntitySystem/MovieSceneEntityBuilder.h