Unreal Engine 5.6 C++ API: UE::MovieScene::FComponentTypeInfo::TComplexComponentOpsBase< T > Struct Template Reference
UE::MovieScene::FComponentTypeInfo::TComplexComponentOpsBase< T > Struct Template Reference
Public Member Functions
virtual void AddReferencedObjects (FReferenceCollector &ReferenceCollector, void *ComponentStart, int32 Num)
virtual void ConstructItems (void *Components, int32 Num) const
virtual void CopyItems (void *Dest, const void *Source, int32 Num) const
virtual void DestructItems (void *Components, int32 Num) const
virtual void RelocateConstructItems (void *Dest, void *Source, int32 Num) const
Public Member Functions inherited from UE::MovieScene::IComplexComponentOps
virtual ~IComplexComponentOps ()
Detailed Description
template<typename T>
struct UE::MovieScene::FComponentTypeInfo::TComplexComponentOpsBase< T >
Definition at line 229 of file MovieSceneComponentTypeInfo.h.
Member Function Documentation
AddReferencedObjects()
template<typename T> virtual void UE::MovieScene::FComponentTypeInfo::TComplexComponentOpsBase< T >::AddReferencedObjects (FReferenceCollector & ReferenceCollector, void * ComponentStart, int32 Num) inline virtual
Implements UE::MovieScene::IComplexComponentOps.
Reimplemented in UE::MovieScene::FComponentTypeInfo::TComplexComponentOps< T >, and UE::MovieScene::FComponentTypeInfo::TComplexComponentOpsCustomRefCollection< T >.
Definition at line 267 of file MovieSceneComponentTypeInfo.h.
References Num.
ConstructItems()
template<typename T> virtual void UE::MovieScene::FComponentTypeInfo::TComplexComponentOpsBase< T >::ConstructItems (void * Components, int32 Num) const inline virtual
Implements UE::MovieScene::IComplexComponentOps.
Definition at line 231 of file MovieSceneComponentTypeInfo.h.
References Components, DefaultConstructItems(), and Num.
CopyItems()
template<typename T> virtual void UE::MovieScene::FComponentTypeInfo::TComplexComponentOpsBase< T >::CopyItems (void * Dest, const void * Source, int32 Num) const inline virtual
Implements UE::MovieScene::IComplexComponentOps.
Definition at line 241 of file MovieSceneComponentTypeInfo.h.
References Num, and Source.
DestructItems()
template<typename T> virtual void UE::MovieScene::FComponentTypeInfo::TComplexComponentOpsBase< T >::DestructItems (void * Components, int32 Num) const inline virtual
Implements UE::MovieScene::IComplexComponentOps.
Definition at line 236 of file MovieSceneComponentTypeInfo.h.
References Components, DestructItems(), and Num.
Referenced by DestructItems().
RelocateConstructItems()
template<typename T> virtual void UE::MovieScene::FComponentTypeInfo::TComplexComponentOpsBase< T >::RelocateConstructItems (void * Dest, void * Source, int32 Num) const inline virtual
Implements UE::MovieScene::IComplexComponentOps.
Definition at line 251 of file MovieSceneComponentTypeInfo.h.
References MoveTemp(), Num, and Source.
The documentation for this struct was generated from the following file:
Runtime/MovieScene/Public/EntitySystem/MovieSceneComponentTypeInfo.h