Unreal Engine 5.6 C++ API: TSparseDynamicDelegate< MulticastDelegate, OwningClass, DelegateInfoClass > Struct Template Reference
TSparseDynamicDelegate< MulticastDelegate, OwningClass, DelegateInfoClass > Struct Template Reference
Sparse version of TBaseDynamicDelegate.
#include "SparseDelegate.h"
Public Types
typedef MulticastDelegate::FDelegate FDelegate
Public Member Functions
template<class UserClass>
void __Internal_AddDynamic (UserClass *InUserObject, typename FDelegate::template TMethodPtrResolver< UserClass >::FMethodPtr InMethodPtr, FName InFunctionName)
Binds a UObject instance and a UObject method address to this multi-cast delegate.
template<class UserClass>
void __Internal_AddUniqueDynamic (UserClass *InUserObject, typename FDelegate::template TMethodPtrResolver< UserClass >::FMethodPtr InMethodPtr, FName InFunctionName)
Binds a UObject instance and a UObject method address to this multi-cast delegate, but only if it hasn't been bound before.
template<class UserClass>
bool __Internal_IsAlreadyBound (UserClass *InUserObject, typename FDelegate::template TMethodPtrResolver< UserClass >::FMethodPtr InMethodPtr, FName InFunctionName) const
Tests if a UObject instance and a UObject method address pair are already bound to this multi-cast delegate.
template<class UserClass>
void __Internal_RemoveDynamic (UserClass *InUserObject, typename FDelegate::template TMethodPtrResolver< UserClass >::FMethodPtr InMethodPtr, FName InFunctionName)
Unbinds a UObject instance and a UObject method address from this multi-cast delegate.
void Add (FScriptDelegate InDelegate)
Adds a function delegate to this multi-cast delegate's invocation list.
void AddUnique (FScriptDelegate InDelegate)
Adds a function delegate to this multi-cast delegate's invocation list if a delegate with the same signature doesn't already exist in the invocation list.
template<typename... ParamTypes>
void Broadcast (ParamTypes... Params)
Broadcasts this delegate to all bound objects, except to those that may have expired.
void Clear ()
Removes all functions from this delegate's invocation list.
bool Contains (const FScriptDelegate &InDelegate) const
Checks whether a function delegate is already a member of this multi-cast delegate's invocation list.
bool Contains (const UObject *InObject, FName InFunctionName) const
Checks whether a function delegate is already a member of this multi-cast delegate's invocation list.
TSharedPtr< MulticastDelegate > GetShared () const
Returns the multicast delegate if any delegates are bound to the sparse delegate.
void Remove (const FScriptDelegate &InDelegate)
Removes a function from this multi-cast delegate's invocation list (performance is O(N)).
void Remove (const UObject *InObject, FName InFunctionName)
Removes a function from this multi-cast delegate's invocation list (performance is O(N)).
void RemoveAll (const UObject *Object)
Removes all delegate bindings from this multicast delegate's invocation list that are bound to the specified object.
Public Member Functions inherited from FSparseDelegate
FSparseDelegate ()
void __Internal_AddUnique (const UObject *DelegateOwner, FName DelegateName, FScriptDelegate InDelegate)
Adds a function delegate to this multi-cast delegate's invocation list if a delegate with the same signature doesn't already exist in the invocation list.
void __Internal_Clear (const UObject *DelegateOwner, FName DelegateName)
Removes all functions from this delegate's invocation list.
void __Internal_Remove (const UObject *DelegateOwner, FName DelegateName, const FScriptDelegate &InDelegate)
Removes a function from this multi-cast delegate's invocation list (performance is O(N)).
bool IsBound () const
Checks to see if any functions are bound to this multi-cast delegate.
Protected Member Functions
FName GetDelegateName () const
Private Member Functions
void __Internal_AddUnique (const UObject *, FName, FScriptDelegate)
void __Internal_Clear (const UObject *, FName)
void __Internal_Remove (const UObject *, FName, const FScriptDelegate &)
UObject * GetDelegateOwner () const
Additional Inherited Members
Protected Attributes inherited from FSparseDelegate
bool bIsBound
Detailed Description
template<typename MulticastDelegate, typename OwningClass, typename DelegateInfoClass>
struct TSparseDynamicDelegate< MulticastDelegate, OwningClass, DelegateInfoClass >
Sparse version of TBaseDynamicDelegate.
Definition at line 197 of file SparseDelegate.h.
Member Typedef Documentation
FDelegate
template<typename MulticastDelegate, typename OwningClass, typename DelegateInfoClass> typedef MulticastDelegate::FDelegate TSparseDynamicDelegate< MulticastDelegate, OwningClass, DelegateInfoClass >::FDelegate
Definition at line 200 of file SparseDelegate.h.
Member Function Documentation
__Internal_AddDynamic()
template<typename MulticastDelegate, typename OwningClass, typename DelegateInfoClass> template<class UserClass> void TSparseDynamicDelegate< MulticastDelegate, OwningClass, DelegateInfoClass >::__Internal_AddDynamic (UserClass * InUserObject, typename FDelegate::template TMethodPtrResolver< UserClass >::FMethodPtr InMethodPtr, FName InFunctionName) inline
Binds a UObject instance and a UObject method address to this multi-cast delegate.
Parameters
InUserObject UObject instance
InMethodPtr Member function address pointer
InFunctionName Name of member function, without class name
NOTE: Do not call this function directly. Instead, call AddDynamic() which is a macro proxy function that automatically sets the function name string for the caller.
Definition at line 369 of file SparseDelegate.h.
References Add, and check.
__Internal_AddUnique()
template<typename MulticastDelegate, typename OwningClass, typename DelegateInfoClass> void TSparseDynamicDelegate< MulticastDelegate, OwningClass, DelegateInfoClass >::__Internal_AddUnique (const UObject * , FName , FScriptDelegate) private
__Internal_AddUniqueDynamic()
template<typename MulticastDelegate, typename OwningClass, typename DelegateInfoClass> template<class UserClass> void TSparseDynamicDelegate< MulticastDelegate, OwningClass, DelegateInfoClass >::__Internal_AddUniqueDynamic (UserClass * InUserObject, typename FDelegate::template TMethodPtrResolver< UserClass >::FMethodPtr InMethodPtr, FName InFunctionName) inline
Binds a UObject instance and a UObject method address to this multi-cast delegate, but only if it hasn't been bound before.
Parameters
InUserObject UObject instance
InMethodPtr Member function address pointer
InFunctionName Name of member function, without class name
NOTE: Do not call this function directly. Instead, call AddUniqueDynamic() which is a macro proxy function that automatically sets the function name string for the caller.
Definition at line 392 of file SparseDelegate.h.
References AddUnique(), and check.
__Internal_Clear()
template<typename MulticastDelegate, typename OwningClass, typename DelegateInfoClass> void TSparseDynamicDelegate< MulticastDelegate, OwningClass, DelegateInfoClass >::__Internal_Clear (const UObject * , FName) private
__Internal_IsAlreadyBound()
template<typename MulticastDelegate, typename OwningClass, typename DelegateInfoClass> template<class UserClass> bool TSparseDynamicDelegate< MulticastDelegate, OwningClass, DelegateInfoClass >::__Internal_IsAlreadyBound (UserClass * InUserObject, typename FDelegate::template TMethodPtrResolver< UserClass >::FMethodPtr InMethodPtr, FName InFunctionName) const inline
Tests if a UObject instance and a UObject method address pair are already bound to this multi-cast delegate.
Parameters
InUserObject UObject instance
InMethodPtr Member function address pointer
InFunctionName Name of member function, without class name
Returns
True if the instance/method is already bound.
NOTE: Do not call this function directly. Instead, call IsAlreadyBound() which is a macro proxy function that automatically sets the function name string for the caller.
Definition at line 349 of file SparseDelegate.h.
References check, and Contains().
__Internal_Remove()
template<typename MulticastDelegate, typename OwningClass, typename DelegateInfoClass> void TSparseDynamicDelegate< MulticastDelegate, OwningClass, DelegateInfoClass >::__Internal_Remove (const UObject * , FName , const FScriptDelegate &) private
__Internal_RemoveDynamic()
template<typename MulticastDelegate, typename OwningClass, typename DelegateInfoClass> template<class UserClass> void TSparseDynamicDelegate< MulticastDelegate, OwningClass, DelegateInfoClass >::__Internal_RemoveDynamic (UserClass * InUserObject, typename FDelegate::template TMethodPtrResolver< UserClass >::FMethodPtr InMethodPtr, FName InFunctionName) inline
Unbinds a UObject instance and a UObject method address from this multi-cast delegate.
Parameters
InUserObject UObject instance
InMethodPtr Member function address pointer
InFunctionName Name of member function, without class name
NOTE: Do not call this function directly. Instead, call RemoveDynamic() which is a macro proxy function that automatically sets the function name string for the caller.
Definition at line 415 of file SparseDelegate.h.
References check, and Remove.
Add()
template<typename MulticastDelegate, typename OwningClass, typename DelegateInfoClass> void TSparseDynamicDelegate< MulticastDelegate, OwningClass, DelegateInfoClass >::Add (FScriptDelegate InDelegate) inline
Adds a function delegate to this multi-cast delegate's invocation list.
Parameters
InDelegate Delegate to add
Definition at line 259 of file SparseDelegate.h.
References FSparseDelegateStorage::Add(), FSparseDelegate::bIsBound, GetDelegateName(), GetDelegateOwner(), and MoveTemp().
AddUnique()
template<typename MulticastDelegate, typename OwningClass, typename DelegateInfoClass> void TSparseDynamicDelegate< MulticastDelegate, OwningClass, DelegateInfoClass >::AddUnique (FScriptDelegate InDelegate) inline
Adds a function delegate to this multi-cast delegate's invocation list if a delegate with the same signature doesn't already exist in the invocation list.
Parameters
InDelegate Delegate to add
Definition at line 270 of file SparseDelegate.h.
References FSparseDelegate::__Internal_AddUnique(), GetDelegateName(), GetDelegateOwner(), and MoveTemp().
Referenced by __Internal_AddUniqueDynamic().
Broadcast()
template<typename MulticastDelegate, typename OwningClass, typename DelegateInfoClass> template<typename... ParamTypes> void TSparseDynamicDelegate< MulticastDelegate, OwningClass, DelegateInfoClass >::Broadcast (ParamTypes... Params) inline
Broadcasts this delegate to all bound objects, except to those that may have expired.
Definition at line 329 of file SparseDelegate.h.
References GetShared(), and Params.
Clear()
template<typename MulticastDelegate, typename OwningClass, typename DelegateInfoClass> void TSparseDynamicDelegate< MulticastDelegate, OwningClass, DelegateInfoClass >::Clear () inline
Removes all functions from this delegate's invocation list.
Definition at line 320 of file SparseDelegate.h.
References FSparseDelegate::__Internal_Clear(), GetDelegateName(), and GetDelegateOwner().
Contains() [1/2]
template<typename MulticastDelegate, typename OwningClass, typename DelegateInfoClass> bool TSparseDynamicDelegate< MulticastDelegate, OwningClass, DelegateInfoClass >::Contains (const FScriptDelegate & InDelegate) const inline
Checks whether a function delegate is already a member of this multi-cast delegate's invocation list.
Parameters
InDelegate Delegate to check
Returns
True if the delegate is already in the list.
Definition at line 237 of file SparseDelegate.h.
References FSparseDelegate::bIsBound, FSparseDelegateStorage::Contains(), GetDelegateName(), and GetDelegateOwner().
Referenced by __Internal_IsAlreadyBound().
Contains() [2/2]
template<typename MulticastDelegate, typename OwningClass, typename DelegateInfoClass> bool TSparseDynamicDelegate< MulticastDelegate, OwningClass, DelegateInfoClass >::Contains (const UObject * InObject, FName InFunctionName) const inline
Checks whether a function delegate is already a member of this multi-cast delegate's invocation list.
Parameters
InObject Object of the delegate to check
InFunctionName Function name of the delegate to check
Returns
True if the delegate is already in the list.
Definition at line 249 of file SparseDelegate.h.
References FSparseDelegate::bIsBound, FSparseDelegateStorage::Contains(), GetDelegateName(), and GetDelegateOwner().
GetDelegateName()
template<typename MulticastDelegate, typename OwningClass, typename DelegateInfoClass> FName TSparseDynamicDelegate< MulticastDelegate, OwningClass, DelegateInfoClass >::GetDelegateName () const inline protected
Definition at line 203 of file SparseDelegate.h.
Referenced by Add(), AddUnique(), Clear(), Contains(), Contains(), GetShared(), Remove(), Remove(), and RemoveAll().
GetDelegateOwner()
template<typename MulticastDelegate, typename OwningClass, typename DelegateInfoClass> UObject * TSparseDynamicDelegate< MulticastDelegate, OwningClass, DelegateInfoClass >::GetDelegateOwner () const inline private
Definition at line 210 of file SparseDelegate.h.
References check, and UObjectBase::IsValidLowLevelFast().
Referenced by Add(), AddUnique(), Clear(), Contains(), Contains(), GetShared(), Remove(), Remove(), and RemoveAll().
GetShared()
template<typename MulticastDelegate, typename OwningClass, typename DelegateInfoClass> TSharedPtr< MulticastDelegate > TSparseDynamicDelegate< MulticastDelegate, OwningClass, DelegateInfoClass >::GetShared () const inline
Returns the multicast delegate if any delegates are bound to the sparse delegate.
Definition at line 221 of file SparseDelegate.h.
References FSparseDelegate::bIsBound, GetDelegateName(), GetDelegateOwner(), FSparseDelegateStorage::GetSharedMulticastDelegate(), and StaticCastSharedPtr().
Referenced by Broadcast().
Remove() [1/2]
template<typename MulticastDelegate, typename OwningClass, typename DelegateInfoClass> void TSparseDynamicDelegate< MulticastDelegate, OwningClass, DelegateInfoClass >::Remove (const FScriptDelegate & InDelegate) inline
Removes a function from this multi-cast delegate's invocation list (performance is O(N)).
Note that the order of the delegates may not be preserved!
Parameters
InDelegate Delegate to remove
Definition at line 281 of file SparseDelegate.h.
References FSparseDelegate::__Internal_Remove(), GetDelegateName(), and GetDelegateOwner().
Remove() [2/2]
template<typename MulticastDelegate, typename OwningClass, typename DelegateInfoClass> void TSparseDynamicDelegate< MulticastDelegate, OwningClass, DelegateInfoClass >::Remove (const UObject * InObject, FName InFunctionName) inline
Removes a function from this multi-cast delegate's invocation list (performance is O(N)).
Note that the order of the delegates may not be preserved!
Parameters
InObject Object of the delegate to remove
InFunctionName Function name of the delegate to remove
Definition at line 293 of file SparseDelegate.h.
References FSparseDelegate::bIsBound, GetDelegateName(), GetDelegateOwner(), and FSparseDelegateStorage::Remove().
RemoveAll()
template<typename MulticastDelegate, typename OwningClass, typename DelegateInfoClass> void TSparseDynamicDelegate< MulticastDelegate, OwningClass, DelegateInfoClass >::RemoveAll (const UObject * Object) inline
Removes all delegate bindings from this multicast delegate's invocation list that are bound to the specified object.
This method also compacts the invocation list.
Parameters
InObject The object to remove bindings for.
Definition at line 309 of file SparseDelegate.h.
References FSparseDelegate::bIsBound, GetDelegateName(), GetDelegateOwner(), Object, and FSparseDelegateStorage::RemoveAll().
The documentation for this struct was generated from the following file:
Runtime/CoreUObject/Public/UObject/SparseDelegate.h