Unreal Engine 5.6 C++ API: FRDGBufferUAVDesc Struct Reference
FRDGBufferUAVDesc Struct Reference final
#include "RenderGraphResources.h"
Public Member Functions
FRDGBufferUAVDesc ()=default
FRDGBufferUAVDesc (FRDGBufferRef InBuffer)
FRDGBufferUAVDesc (FRDGBufferRef InBuffer, EPixelFormat InFormat)
bool operator!= (const FRDGBufferUAVDesc &Other) const
bool operator== (const FRDGBufferUAVDesc &Other) const
Data Fields
FRDGBufferRef Buffer = nullptr
Friends
uint32 GetTypeHash (const FRDGBufferUAVDesc &Desc)
Detailed Description
Definition at line 1161 of file RenderGraphResources.h.
Constructor & Destructor Documentation
FRDGBufferUAVDesc() [1/3]
FRDGBufferUAVDesc::FRDGBufferUAVDesc () default
Referenced by GetTypeHash, operator!=(), and operator==().
FRDGBufferUAVDesc() [2/3]
FRDGBufferUAVDesc::FRDGBufferUAVDesc (FRDGBufferRef InBuffer)
FRDGBufferUAVDesc() [3/3]
FRDGBufferUAVDesc::FRDGBufferUAVDesc (FRDGBufferRef InBuffer, EPixelFormat InFormat) inline
Definition at line 1168 of file RenderGraphResources.h.
References Buffer.
Member Function Documentation
operator!=()
bool FRDGBufferUAVDesc::operator!= (const FRDGBufferUAVDesc & Other) const inline
Definition at line 1178 of file RenderGraphResources.h.
References FRDGBufferUAVDesc(), and Other.
operator==()
bool FRDGBufferUAVDesc::operator== (const FRDGBufferUAVDesc & Other) const inline
Definition at line 1173 of file RenderGraphResources.h.
References FRDGBufferUAVDesc(), Buffer, and Other.
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FRDGBufferUAVDesc & Desc) friend
Definition at line 1183 of file RenderGraphResources.h.
References FRDGBufferUAVDesc(), Buffer, GetTypeHash, and HashCombine().
Referenced by GetTypeHash.
Field Documentation
Buffer
FRDGBufferRef FRDGBufferUAVDesc::Buffer = nullptr
Definition at line 1188 of file RenderGraphResources.h.
Referenced by FRDGBufferUAVDesc(), GetTypeHash, and operator==().
The documentation for this struct was generated from the following file:
Runtime/RenderCore/Public/RenderGraphResources.h