Unreal Engine 5.6 C++ API: UE::Geometry::TShiftGridIndexer2< RealType > Struct Template Reference
UE::Geometry::TShiftGridIndexer2< RealType > Struct Template Reference
Convert between integer grid coordinates and scaled+translated real-valued coordinates.
#include "GridIndexing2.h"
Public Member Functions
TShiftGridIndexer2 (const TVector2< RealType > &origin, RealType cellSize)
TBox2< RealType > BoxFromGrid (const FVector2i &GridPoint) const
Compute the real-valued 2D box of an integer grid coordinates.
TVector2< RealType > FromGrid (const FVector2i &GridPoint) const
Convert integer grid coordinates to real-valued point.
TVector2< RealType > FromGrid (const TVector2< RealType > &RealGridPoint) const
Convert real-valued grid coordinates to real-valued point.
FIntRect ToGrid (const TBox2< RealType > &Box) const
Convert real-valued 2D box to a rectangle using integer grid coordinates.
FIntRect ToGrid (const TBox< RealType > &Box) const
Convert real-valued 3D box to a rectangle using integer grid coordinates.
FVector2i ToGrid (const TVector2< RealType > &Point) const
Convert real-valued point to integer grid coordinates.
Data Fields
RealType CellSize
Real-valued size of an integer grid cell.
TVector2< RealType > Origin
Real-valued origin of grid, position of integer grid origin.
Detailed Description
template<typename RealType>
struct UE::Geometry::TShiftGridIndexer2< RealType >
Convert between integer grid coordinates and scaled+translated real-valued coordinates.
Definition at line 59 of file GridIndexing2.h.
Constructor & Destructor Documentation
TShiftGridIndexer2()
template<typename RealType> UE::Geometry::TShiftGridIndexer2< RealType >::TShiftGridIndexer2 (const TVector2< RealType > & origin, RealType cellSize) inline
Definition at line 66 of file GridIndexing2.h.
Member Function Documentation
BoxFromGrid()
template<typename RealType> TBox2< RealType > UE::Geometry::TShiftGridIndexer2< RealType >::BoxFromGrid (const FVector2i & GridPoint) const inline
Compute the real-valued 2D box of an integer grid coordinates.
Definition at line 114 of file GridIndexing2.h.
FromGrid() [1/2]
template<typename RealType> TVector2< RealType > UE::Geometry::TShiftGridIndexer2< RealType >::FromGrid (const FVector2i & GridPoint) const inline
Convert integer grid coordinates to real-valued point.
Definition at line 98 of file GridIndexing2.h.
Referenced by UE::Geometry::TShiftGridIndexer2< float >::BoxFromGrid().
FromGrid() [2/2]
template<typename RealType> TVector2< RealType > UE::Geometry::TShiftGridIndexer2< RealType >::FromGrid (const TVector2< RealType > & RealGridPoint) const inline
Convert real-valued grid coordinates to real-valued point.
Definition at line 106 of file GridIndexing2.h.
ToGrid() [1/3]
template<typename RealType> FIntRect UE::Geometry::TShiftGridIndexer2< RealType >::ToGrid (const TBox2< RealType > & Box) const inline
Convert real-valued 2D box to a rectangle using integer grid coordinates.
Definition at line 82 of file GridIndexing2.h.
ToGrid() [2/3]
template<typename RealType> FIntRect UE::Geometry::TShiftGridIndexer2< RealType >::ToGrid (const TBox< RealType > & Box) const inline
Convert real-valued 3D box to a rectangle using integer grid coordinates.
Definition at line 90 of file GridIndexing2.h.
ToGrid() [3/3]
template<typename RealType> FVector2i UE::Geometry::TShiftGridIndexer2< RealType >::ToGrid (const TVector2< RealType > & Point) const inline
Convert real-valued point to integer grid coordinates.
Definition at line 74 of file GridIndexing2.h.
Referenced by UE::Geometry::TShiftGridIndexer2< float >::ToGrid(), and UE::Geometry::TShiftGridIndexer2< float >::ToGrid().
Field Documentation
CellSize
template<typename RealType> RealType UE::Geometry::TShiftGridIndexer2< RealType >::CellSize
Real-valued size of an integer grid cell.
Definition at line 62 of file GridIndexing2.h.
Origin
template<typename RealType> TVector2<RealType> UE::Geometry::TShiftGridIndexer2< RealType >::Origin
Real-valued origin of grid, position of integer grid origin.
Definition at line 64 of file GridIndexing2.h.
The documentation for this struct was generated from the following file:
Runtime/GeometryCore/Public/Util/GridIndexing2.h