Unreal Engine 5.6 C++ API: FGraphActionNode Struct Reference
FGraphActionNode Struct Reference
#include "GraphActionNode.h"
Public Member Functions
PRAGMA_DISABLE_DEPRECATION_WARNINGS FGraphActionNode (const FGraphActionNode &Node)=delete
FGraphActionNode (FGraphActionNode &&Node)=delete
~FGraphActionNode ()=default
TSharedPtr< FGraphActionNode > AddChild (const TSharedPtr< FEdGraphSchemaAction > &Action)
Inserts a new action node (and any accompanying category nodes) based off the provided Action.
PRAGMA_DISABLE_DEPRECATION_WARNINGS UE_DEPRECATED(5.5, "FGraphActionListBuilderBase::ActionGroup has been deprecated, use TSharedPtr<FEdGraphSchemaAction> directly") TSharedPtr< FGraphActionNode > AddChild(FGraphActionListBuilderBase PRAGMA_ENABLE_DEPRECATION_WARNINGS TSharedPtr< FGraphActionNode > AddChildAlphabetical (const TSharedPtr< FEdGraphSchemaAction > &Action)
Inserts a new action node (and any required category nodes) based off the provided Action.
PRAGMA_DISABLE_DEPRECATION_WARNINGS UE_DEPRECATED(5.5, "FGraphActionListBuilderBase::ActionGroup has been deprecated, use TSharedPtr<FEdGraphSchemaAction> directly") TSharedPtr< FGraphActionNode > AddChildAlphabetical(FGraphActionListBuilderBase PRAGMA_ENABLE_DEPRECATION_WARNINGS TSharedPtr< FGraphActionNode > AddSection (int32 Grouping, int32 InSectionID)
bool BroadcastRenameRequest ()
Executes the node's RenameRequestEvent if it is bound.
void ClearChildren ()
Clears all children (not recursively... the TSharedPtrs should clean up appropriately).
void ExpandAllChildren (TSharedPtr< STreeView< TSharedPtr< FGraphActionNode > > > TreeView, bool bRecursive=true)
Takes the tree view and expands its elements for each child.
void GetAllActionNodes (TArray< TSharedPtr< FGraphActionNode > > &OutNodeArray) const
Recursively collects all child/grandchild/decendent action nodes.
void GetAllNodes (TArray< TSharedPtr< FGraphActionNode > > &OutNodeArray) const
Recursively collects all child/grandchild/decendent nodes.
FText GetCategoryPath () const
Walks the node chain backwards, constructing a category path (delimited by '|' characters).
FText const & GetDisplayName () const
Retrieves this node's display name (for category and action nodes).
void GetLeafNodes (TArray< TSharedPtr< FGraphActionNode > > &OutLeafArray) const
Recursively collects all decendent action/separator nodes (leaves out branching category-nodes).
int32 GetLinearizedIndex (TSharedPtr< FGraphActionNode > Node) const
Returns the 'linearized' index of the node, including category nodes, useful for getting displayed position.
TWeakPtr< FGraphActionNode > GetParentNode () const
Returns a WeakPtr to the Parent Node.
TSharedPtr< FEdGraphSchemaAction > GetPrimaryAction () const
Looks through this node's Actions array, and returns the first valid action it finds.
int32 GetTotalLeafNodes () const
Returns the number of leaf nodes.
bool HasValidAction () const
Checks to see if this node contains at least one valid action.
bool IsActionNode () const
bool IsCategoryNode () const
bool IsGroupDividerNode () const
bool IsRenameRequestPending () const
Sometimes a call to BroadcastRenameRequest() is made before the RenameRequestEvent has been bound.
bool IsRootNode () const
Query to determine this node's type (there are five distinguishable node types: root, section heading, category, action, & group-divider).
bool IsSectionHeadingNode () const
bool IsSeparator () const
Determines if this node is a menu separator of some kind (either a "group-divider" or a "section heading").
FOnRenameRequestActionNode & OnRenameRequest ()
Accessor to the node's RenameRequestEvent (for binding purposes).
FGraphActionNode & operator= (const FGraphActionNode &Node)=delete
FGraphActionNode & operator= (FGraphActionNode &&Node)=delete
void SortChildren (bool bAlphabetically=true, bool bRecursive=true)
Sorts all child nodes by section, group, and type (additionally, can sort alphabetically if wanted).
UE_DEPRECATED (5.5, "!! WARNING: This array is no longer populated!! FGraphActionNode::Actions array only functioned with a single Action (GetPrimaryAction), access via Action") TArray< TSharedPtr< FEdGraphSchemaAction > > const Actions
Public Member Functions inherited from TSharedFromThis< FGraphActionNode >
TSharedRef< FGraphActionNode, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FGraphActionNode, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Static Public Member Functions
static TSharedPtr< FGraphActionNode > NewRootNode ()
Static allocator for a new root node (so external users have a starting point to build graph action trees from).
Data Fields
TSharedPtr< FEdGraphSchemaAction > const Action
An action to execute when this node is picked from a menu.
TMap< FString, TSharedPtr< FGraphActionNode > > CategoryNodes
Lookup table for category nodes, used to speed up menu construction.
TArray< TSharedPtr< FGraphActionNode > > Children
int32 const Grouping
Identifies the menu group that this node belongs to (defaults to zero)
int32 const SectionID
Identifies the named section that this node belongs to, if any (defaults to INVALID_SECTION_ID)
Static Public Attributes
static PRAGMA_ENABLE_DEPRECATION_WARNINGS const int32 INVALID_SECTION_ID = 0
Private Member Functions
FGraphActionNode (const TSharedPtr< FEdGraphSchemaAction > &InAction, int32 InGrouping, int32 InSectionID)
Constructor for action nodes.
FGraphActionNode (int32 Grouping, int32 SectionID)
void AddChildGrouping (TSharedPtr< FGraphActionNode > ActionNode, TWeakPtr< FGraphActionNode > Parent, bool bInsertAlphabetically)
void AddChildRecursively (const TArray< FString > &CategoryStack, int32 Idx, TSharedPtr< FGraphActionNode > NodeToAdd)
Iterates the CategoryStack, adding category-nodes as needed.
TSharedPtr< FGraphActionNode > FindMatchingParent (FString const &ParentName, TSharedPtr< FGraphActionNode > NodeToAdd)
Looks through this node's children to see if a there already exists a node matching one we'd have to spawn (to parent the supplied NodeToAdd).
int32 GetLinearizedIndex (TSharedPtr< FGraphActionNode > Node, int32 &Iter) const
Recursive implementation helper for GetLinearizedIndex.
void InsertChild (TSharedPtr< FGraphActionNode > NodeToAdd)
Adds the specified node directly to this node's Children array.
void InsertChildAlphabetical (TSharedPtr< FGraphActionNode > NodeToAdd)
Static Private Member Functions
static TSharedPtr< FGraphActionNode > NewActionNode (TSharedPtr< FEdGraphSchemaAction > const &ActionNode)
static TSharedPtr< FGraphActionNode > NewCategoryNode (FString const &Category, int32 Grouping, int32 SectionID)
static TSharedPtr< FGraphActionNode > NewGroupDividerNode (TWeakPtr< FGraphActionNode > Parent, int32 Grouping)
static TSharedPtr< FGraphActionNode > NewSectionHeadingNode (TWeakPtr< FGraphActionNode > Parent, int32 Grouping, int32 SectionID)
Private Attributes
bool bPendingRenameRequest
When the item is first created, a rename request may occur before everything is setup for it.
TSet< int32 > ChildGroupings
Tracks what groups have already been added (so we can easily determine what group-dividers we need)
TSet< int32 > ChildSections
Tracks what sections have already been added (so we can easily determine what heading we need)
FText DisplayText
The category or action name (depends on what type of node this is)
int32 InsertOrder
For sorting, when we don't alphabetically sort (so menu items don't jump around).
TWeakPtr< FGraphActionNode > ParentNode
The node that this is a direct child of (empty if this is a root node)
FOnRenameRequestActionNode RenameRequestEvent
Delegate to trigger when a rename was requested on this node.
int32 TotalLeafs
Root entry only, counts the total leaf entries in this tree.
Friends
struct FGraphActionNodeImpl
Additional Inherited Members
Protected Member Functions inherited from TSharedFromThis< FGraphActionNode >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions inherited from TSharedFromThis< FGraphActionNode >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
Definition at line 19 of file GraphActionNode.h.
Constructor & Destructor Documentation
FGraphActionNode() [1/4]
PRAGMA_DISABLE_DEPRECATION_WARNINGS FGraphActionNode::FGraphActionNode (const FGraphActionNode & Node) delete
References FGraphActionNode().
Referenced by FGraphActionNode(), FGraphActionNode(), AddChild(), AddChildAlphabetical(), AddSection(), GetParentNode(), NewRootNode(), operator=(), and operator=().
FGraphActionNode() [2/4]
FGraphActionNode::FGraphActionNode (FGraphActionNode && Node) delete
References FGraphActionNode().
~FGraphActionNode()
FGraphActionNode::~FGraphActionNode () default
References PRAGMA_ENABLE_DEPRECATION_WARNINGS.
FGraphActionNode() [3/4]
FGraphActionNode::FGraphActionNode (int32 Grouping, int32 SectionID) private
Parameters
Grouping
SectionID
References Grouping, and SectionID.
FGraphActionNode() [4/4]
FGraphActionNode::FGraphActionNode (const TSharedPtr< FEdGraphSchemaAction > & InAction, int32 InGrouping, int32 InSectionID) private
Constructor for action nodes.
Private so that users go through AddChild().
Parameters
InAction
Grouping
SectionID
Member Function Documentation
AddChild()
TSharedPtr< FGraphActionNode > FGraphActionNode::AddChild (const TSharedPtr< FEdGraphSchemaAction > & Action)
Inserts a new action node (and any accompanying category nodes) based off the provided Action.
NOTE: This does NOT insert the node in a sorted manner. Call SortChildren() separately or use AddChildAlphabetical
Parameters
Action An action that you want the node to execute when picked.
Returns
The new action node.
References FGraphActionNode(), Action, AddChild(), PRAGMA_DISABLE_DEPRECATION_WARNINGS, PRAGMA_ENABLE_DEPRECATION_WARNINGS, and UE_DEPRECATED().
Referenced by AddChild().
AddChildAlphabetical()
PRAGMA_DISABLE_DEPRECATION_WARNINGS UE_DEPRECATED(5.5, "FGraphActionListBuilderBase::ActionGroup has been deprecated, use TSharedPtr<FEdGraphSchemaAction> directly") TSharedPtr< FGraphActionNode > AddChild(FGraphActionListBuilderBase PRAGMA_ENABLE_DEPRECATION_WARNINGS TSharedPtr< FGraphActionNode > FGraphActionNode::AddChildAlphabetical (const TSharedPtr< FEdGraphSchemaAction > & Action)
Inserts a new action node (and any required category nodes) based off the provided Action.
Inserts in alphabetical order.
Parameters
Action An action that you want the node to execute when picked.
Returns
The new action node.
References FGraphActionNode(), Action, AddChildAlphabetical(), PRAGMA_DISABLE_DEPRECATION_WARNINGS, PRAGMA_ENABLE_DEPRECATION_WARNINGS, and UE_DEPRECATED().
Referenced by AddChildAlphabetical().
AddChildGrouping()
void FGraphActionNode::AddChildGrouping (TSharedPtr< FGraphActionNode > ActionNode, TWeakPtr< FGraphActionNode > Parent, bool bInsertAlphabetically) private
References Parent.
AddChildRecursively()
void FGraphActionNode::AddChildRecursively (const TArray< FString > & CategoryStack, int32 Idx, TSharedPtr< FGraphActionNode > NodeToAdd) private
Iterates the CategoryStack, adding category-nodes as needed.
The last category is what the node will be inserted under.
Parameters
CategoryStack A list of categories denoting where to nest the new node (the first element is the highest category)
Idx Current point in the category stack that we have iterated to
NodeToAdd The node you want inserted.
AddSection()
PRAGMA_DISABLE_DEPRECATION_WARNINGS UE_DEPRECATED(5.5, "FGraphActionListBuilderBase::ActionGroup has been deprecated, use TSharedPtr<FEdGraphSchemaAction> directly") TSharedPtr< FGraphActionNode > AddChildAlphabetical(FGraphActionListBuilderBase PRAGMA_ENABLE_DEPRECATION_WARNINGS TSharedPtr< FGraphActionNode > FGraphActionNode::AddSection (int32 Grouping, int32 InSectionID)
References FGraphActionNode(), AddSection(), and Grouping.
Referenced by AddSection().
BroadcastRenameRequest()
bool FGraphActionNode::BroadcastRenameRequest ()
Executes the node's RenameRequestEvent if it is bound.
Otherwise, it will mark the node as having a pending rename request.
Returns
True if the broadcast went through, false if the "pending rename request" flag was set.
ClearChildren()
void FGraphActionNode::ClearChildren ()
Clears all children (not recursively... the TSharedPtrs should clean up appropriately).
ExpandAllChildren()
void FGraphActionNode::ExpandAllChildren (TSharedPtr< STreeView< TSharedPtr< FGraphActionNode > > > TreeView, bool bRecursive = true)
Takes the tree view and expands its elements for each child.
Parameters
TreeView The tree responsible for visualizing this node hierarchy.
bRecursive Determines if you want children/decendents to expand their children as well.
FindMatchingParent()
TSharedPtr< FGraphActionNode > FGraphActionNode::FindMatchingParent (FString const & ParentName, TSharedPtr< FGraphActionNode > NodeToAdd) private
Looks through this node's children to see if a there already exists a node matching one we'd have to spawn (to parent the supplied NodeToAdd).
Parameters
ParentName The name of the category NodeToAdd wants to nest under.
NodeToAdd The node that we'll be adding to this child.
Returns
A child node matching the supplied parameters (will be empty if no match was found).
GetAllActionNodes()
void FGraphActionNode::GetAllActionNodes (TArray< TSharedPtr< FGraphActionNode > > & OutNodeArray) const
Recursively collects all child/grandchild/decendent action nodes.
Parameters
OutNodeArray The array to fill out with decendent nodes.
GetAllNodes()
void FGraphActionNode::GetAllNodes (TArray< TSharedPtr< FGraphActionNode > > & OutNodeArray) const
Recursively collects all child/grandchild/decendent nodes.
Parameters
OutNodeArray The array to fill out with decendent nodes.
GetCategoryPath()
FText FGraphActionNode::GetCategoryPath () const
Walks the node chain backwards, constructing a category path (delimited by '|' characters).
This includes this node's category (if it is a category node).
Returns
A category path string, denoting the category hierarchy up to this node.
GetDisplayName()
FText const & FGraphActionNode::GetDisplayName () const
Retrieves this node's display name (for category and action nodes).
The text string will be empty for separator and root nodes.
Returns
The name to present this node with in the tree view (will be an empty text string if this is a separator node)
GetLeafNodes()
void FGraphActionNode::GetLeafNodes (TArray< TSharedPtr< FGraphActionNode > > & OutLeafArray) const
Recursively collects all decendent action/separator nodes (leaves out branching category-nodes).
Parameters
OutLeafArray The array to fill out with decendent leaf nodes.
GetLinearizedIndex() [1/2]
int32 FGraphActionNode::GetLinearizedIndex (TSharedPtr< FGraphActionNode > Node) const
Returns the 'linearized' index of the node, including category nodes, useful for getting displayed position.
GetLinearizedIndex() [2/2]
int32 FGraphActionNode::GetLinearizedIndex (TSharedPtr< FGraphActionNode > Node, int32 & Iter) const private
Recursive implementation helper for GetLinearizedIndex.
GetParentNode()
TWeakPtr< FGraphActionNode > FGraphActionNode::GetParentNode () const inline
Returns a WeakPtr to the Parent Node.
Definition at line 103 of file GraphActionNode.h.
References FGraphActionNode(), GetParentNode(), and ParentNode.
Referenced by GetParentNode().
GetPrimaryAction()
TSharedPtr< FEdGraphSchemaAction > FGraphActionNode::GetPrimaryAction () const
Looks through this node's Actions array, and returns the first valid action it finds.
Returns
This node's first valid action (will be an empty pointer if this is not an action node).
GetTotalLeafNodes()
int32 FGraphActionNode::GetTotalLeafNodes () const
Returns the number of leaf nodes.
HasValidAction()
bool FGraphActionNode::HasValidAction () const
Checks to see if this node contains at least one valid action.
Returns
True is the Actions array contains a valid entry, otherwise false.
InsertChild()
void FGraphActionNode::InsertChild (TSharedPtr< FGraphActionNode > NodeToAdd) private
Adds the specified node directly to this node's Children array.
Will create and insert separators if needed (if the node has a new group or section).
Parameters
NodeToAdd The node you want inserted.
InsertChildAlphabetical()
void FGraphActionNode::InsertChildAlphabetical (TSharedPtr< FGraphActionNode > NodeToAdd) private
IsActionNode()
bool FGraphActionNode::IsActionNode () const
IsCategoryNode()
bool FGraphActionNode::IsCategoryNode () const
IsGroupDividerNode()
bool FGraphActionNode::IsGroupDividerNode () const
IsRenameRequestPending()
bool FGraphActionNode::IsRenameRequestPending () const
Sometimes a call to BroadcastRenameRequest() is made before the RenameRequestEvent has been bound.
When that happens, this node is marked with a pending rename request. This method determines if that is the case for this node.
Returns
True if a call to BroadcastRenameRequest() was made without a valid RenameRequestEvent.
IsRootNode()
bool FGraphActionNode::IsRootNode () const
Query to determine this node's type (there are five distinguishable node types: root, section heading, category, action, & group-divider).
Returns
True if this is the type your queried about, otherwise false.
IsSectionHeadingNode()
bool FGraphActionNode::IsSectionHeadingNode () const
IsSeparator()
bool FGraphActionNode::IsSeparator () const
Determines if this node is a menu separator of some kind (either a "group-divider" or a "section heading").
Returns
True if this is a menu divider, otherwise false.
NewActionNode()
TSharedPtr< FGraphActionNode > FGraphActionNode::NewActionNode (TSharedPtr< FEdGraphSchemaAction > const & ActionNode) static private
Parameters
ActionNode
Returns
NewCategoryNode()
TSharedPtr< FGraphActionNode > FGraphActionNode::NewCategoryNode (FString const & Category, int32 Grouping, int32 SectionID) static private
Parameters
Category
Grouping
SectionID
Returns
References Category, Grouping, and SectionID.
NewGroupDividerNode()
TSharedPtr< FGraphActionNode > FGraphActionNode::NewGroupDividerNode (TWeakPtr< FGraphActionNode > Parent, int32 Grouping) static private
Parameters
Parent
Grouping
Returns
References Grouping, and Parent.
NewRootNode()
TSharedPtr< FGraphActionNode > FGraphActionNode::NewRootNode () static
Static allocator for a new root node (so external users have a starting point to build graph action trees from).
Returns
A newly allocated root node (should not be displayed in the tree view).
References FGraphActionNode(), and NewRootNode().
Referenced by NewRootNode().
NewSectionHeadingNode()
TSharedPtr< FGraphActionNode > FGraphActionNode::NewSectionHeadingNode (TWeakPtr< FGraphActionNode > Parent, int32 Grouping, int32 SectionID) static private
Parameters
Parent
Grouping
SectionID
Returns
References Grouping, Parent, and SectionID.
OnRenameRequest()
FOnRenameRequestActionNode & FGraphActionNode::OnRenameRequest () inline
Accessor to the node's RenameRequestEvent (for binding purposes).
Do not Execute() the delegate from this function, instead call BroadcastRenameRequest() on the node.
Returns
The node's internal RenameRequestEvent.
Definition at line 202 of file GraphActionNode.h.
References RenameRequestEvent.
operator=() [1/2]
FGraphActionNode & FGraphActionNode::operator= (const FGraphActionNode & Node) delete
References FGraphActionNode().
operator=() [2/2]
FGraphActionNode & FGraphActionNode::operator= (FGraphActionNode && Node) delete
References FGraphActionNode().
SortChildren()
void FGraphActionNode::SortChildren (bool bAlphabetically = true, bool bRecursive = true)
Sorts all child nodes by section, group, and type (additionally, can sort alphabetically if wanted).
Parameters
bAlphabetically Determines if we sort alphabetically on top of section/group/type.
bRecursive Determines if we should sort all decendent nodes' children ass well.
References SortChildren().
Referenced by SortChildren().
UE_DEPRECATED()
FGraphActionNode::UE_DEPRECATED (5. 5, "!! WARNING: This array is no longer populated!! FGraphActionNode::Actions array only functioned with a single Action GetPrimaryAction, access via Action") const
Referenced by AddChild(), and AddChildAlphabetical().
Friends And Related Symbol Documentation
FGraphActionNodeImpl
friend struct FGraphActionNodeImpl friend
Definition at line 329 of file GraphActionNode.h.
References FGraphActionNodeImpl.
Referenced by FGraphActionNodeImpl.
Field Documentation
Action
TSharedPtr<FEdGraphSchemaAction> const FGraphActionNode::Action
An action to execute when this node is picked from a menu.
Definition at line 41 of file GraphActionNode.h.
Referenced by AddChild(), and AddChildAlphabetical().
bPendingRenameRequest
bool FGraphActionNode::bPendingRenameRequest private
When the item is first created, a rename request may occur before everything is setup for it.
This toggles to true in those cases
Definition at line 325 of file GraphActionNode.h.
CategoryNodes
TMap< FString, TSharedPtr<FGraphActionNode> > FGraphActionNode::CategoryNodes
Lookup table for category nodes, used to speed up menu construction.
Definition at line 49 of file GraphActionNode.h.
ChildGroupings
TSet<int32> FGraphActionNode::ChildGroupings private
Tracks what groups have already been added (so we can easily determine what group-dividers we need)
Definition at line 320 of file GraphActionNode.h.
Children
TArray< TSharedPtr<FGraphActionNode> > FGraphActionNode::Children
Definition at line 46 of file GraphActionNode.h.
ChildSections
TSet<int32> FGraphActionNode::ChildSections private
Tracks what sections have already been added (so we can easily determine what heading we need)
Definition at line 322 of file GraphActionNode.h.
DisplayText
FText FGraphActionNode::DisplayText private
The category or action name (depends on what type of node this is)
Definition at line 315 of file GraphActionNode.h.
Grouping
int32 const FGraphActionNode::Grouping
Identifies the menu group that this node belongs to (defaults to zero)
Definition at line 39 of file GraphActionNode.h.
Referenced by FGraphActionNode(), AddSection(), NewCategoryNode(), NewGroupDividerNode(), and NewSectionHeadingNode().
InsertOrder
int32 FGraphActionNode::InsertOrder private
For sorting, when we don't alphabetically sort (so menu items don't jump around).
Definition at line 331 of file GraphActionNode.h.
INVALID_SECTION_ID
PRAGMA_ENABLE_DEPRECATION_WARNINGS const int32 FGraphActionNode::INVALID_SECTION_ID = 0 static
Definition at line 34 of file GraphActionNode.h.
ParentNode
TWeakPtr<FGraphActionNode> FGraphActionNode::ParentNode private
The node that this is a direct child of (empty if this is a root node)
Definition at line 317 of file GraphActionNode.h.
Referenced by GetParentNode().
RenameRequestEvent
FOnRenameRequestActionNode FGraphActionNode::RenameRequestEvent private
Delegate to trigger when a rename was requested on this node.
Definition at line 327 of file GraphActionNode.h.
Referenced by OnRenameRequest().
SectionID
int32 const FGraphActionNode::SectionID
Identifies the named section that this node belongs to, if any (defaults to INVALID_SECTION_ID)
Definition at line 37 of file GraphActionNode.h.
Referenced by FGraphActionNode(), NewCategoryNode(), and NewSectionHeadingNode().
TotalLeafs
int32 FGraphActionNode::TotalLeafs private
Root entry only, counts the total leaf entries in this tree.
Definition at line 333 of file GraphActionNode.h.
The documentation for this struct was generated from the following file:
Editor/GraphEditor/Public/GraphActionNode.h