Unreal Engine 5.6 C++ API: FScopedSkeletalMeshRenderData Struct Reference
FScopedSkeletalMeshRenderData Struct Reference
#include "SkeletalMesh.h"
Public Member Functions
~FScopedSkeletalMeshRenderData ()
UE_DEPRECATED (5.4, "This class is deprecated, there is no replacement because this is not a safe async design.") 1 const FSkeletalMeshRenderData *GetData() const
UE_DEPRECATED (5.4, "This class is deprecated, there is no replacement because this is not a safe async design.") 1 FScopedSkeletalMeshRenderData(USkeletalMesh *Mesh)
Private Attributes
FSkeletalMeshRenderData * Data = nullptr
FEvent * Lock = nullptr
USkeletalMesh * Mesh = nullptr
Friends
class USkeletalMesh
Detailed Description
Definition at line 413 of file SkeletalMesh.h.
Constructor & Destructor Documentation
~FScopedSkeletalMeshRenderData()
FScopedSkeletalMeshRenderData::~FScopedSkeletalMeshRenderData ()
References UE_API.
Member Function Documentation
UE_DEPRECATED() [1/2]
FScopedSkeletalMeshRenderData::UE_DEPRECATED (5. 4, "This class is deprecated, there is no replacement because this is not a safe async design.") const
References GetData(), UE_API, and UE_DEPRECATED().
UE_DEPRECATED() [2/2]
FScopedSkeletalMeshRenderData::UE_DEPRECATED (5. 4, "This class is deprecated, there is no replacement because this is not a safe async design.")
References Mesh, UE_API, and USkeletalMesh.
Referenced by UE_DEPRECATED().
Friends And Related Symbol Documentation
USkeletalMesh
friend class USkeletalMesh friend
Definition at line 428 of file SkeletalMesh.h.
References Animation, Ar, BeginCacheForCookedPlatformData, BlueprintType, BodySetup, Category, QualityLevelProperty::ConvertQualityLevelData(), DECLARE_MULTICAST_DELEGATE, Default, ensure, ExtendedBounds, FVector, GENERATED_UCLASS_BODY, TSharedPtr< ObjectType, InMode >::Get(), GET_MEMBER_NAME_CHECKED, hidecategories, INDEX_NONE, Keywords, Mesh, Meta, meta, MinimalAPI, MoveTemp(), NegativeBoundsExtension, Object, Physics, Platform, PositiveBoundsExtension, PostLoad, PRAGMA_DISABLE_DEPRECATION_WARNINGS, PRAGMA_ENABLE_DEPRECATION_WARNINGS, PreSave, Property, ReadOnly, ReadWrite, RenderData, SkeletalMesh, Skeleton, SourceModels, StaticMesh, TEXT, ToolTip, transient, UCLASS, UE_DEPRECATED, UFUNCTION, UPROPERTY, USkeletalMesh, WriteOnly, and EAxis::Y.
Referenced by UE_DEPRECATED(), and USkeletalMesh.
Field Documentation
Data
FSkeletalMeshRenderData* FScopedSkeletalMeshRenderData::Data = nullptr private
Definition at line 426 of file SkeletalMesh.h.
Lock
FEvent* FScopedSkeletalMeshRenderData::Lock = nullptr private
Definition at line 424 of file SkeletalMesh.h.
Mesh
USkeletalMesh* FScopedSkeletalMeshRenderData::Mesh = nullptr private
Definition at line 425 of file SkeletalMesh.h.
Referenced by UE_DEPRECATED(), and USkeletalMesh.
The documentation for this struct was generated from the following file:
Runtime/Engine/Classes/Engine/SkeletalMesh.h