Unreal Engine 5.6 C++ API: FCacheUserToken Struct Reference
FCacheUserToken Struct Reference
#include "ChaosCache.h"
Public Member Functions
FCacheUserToken (FCacheUserToken &&Other)
bool IsOpen () const
Private Member Functions
FCacheUserToken ()=delete
FCacheUserToken (bool bInOpen, bool bInRecord, const UChaosCache *InOwner)
FCacheUserToken (const FCacheUserToken &)=delete
FCacheUserToken & operator= (const FCacheUserToken &)=delete
FCacheUserToken & operator= (FCacheUserToken &&)=delete
Private Attributes
bool bIsOpen
bool bIsRecord
const UChaosCache * Owner
friend UChaosCache
Detailed Description
Definition at line 260 of file ChaosCache.h.
Constructor & Destructor Documentation
FCacheUserToken() [1/4]
FCacheUserToken::FCacheUserToken (FCacheUserToken && Other) inline
Definition at line 268 of file ChaosCache.h.
References FCacheUserToken(), bIsOpen, bIsRecord, Other, and Owner.
Referenced by FCacheUserToken(), FCacheUserToken(), operator=(), and operator=().
FCacheUserToken() [2/4]
FCacheUserToken::FCacheUserToken (bool bInOpen, bool bInRecord, const UChaosCache * InOwner) inline explicit private
Definition at line 286 of file ChaosCache.h.
References bIsOpen, bIsRecord, Owner, and UChaosCache.
FCacheUserToken() [3/4]
FCacheUserToken::FCacheUserToken () private delete
FCacheUserToken() [4/4]
FCacheUserToken::FCacheUserToken (const FCacheUserToken &) private delete
References FCacheUserToken().
Member Function Documentation
IsOpen()
bool FCacheUserToken::IsOpen () const inline
Definition at line 262 of file ChaosCache.h.
References bIsOpen, and Owner.
operator=() [1/2]
FCacheUserToken & FCacheUserToken::operator= (const FCacheUserToken &) private delete
References FCacheUserToken().
operator=() [2/2]
FCacheUserToken & FCacheUserToken::operator= (FCacheUserToken &&) private delete
References FCacheUserToken().
Field Documentation
bIsOpen
bool FCacheUserToken::bIsOpen private
Definition at line 282 of file ChaosCache.h.
Referenced by FCacheUserToken(), FCacheUserToken(), and IsOpen().
bIsRecord
bool FCacheUserToken::bIsRecord private
Definition at line 283 of file ChaosCache.h.
Referenced by FCacheUserToken(), and FCacheUserToken().
Owner
const UChaosCache* FCacheUserToken::Owner private
Definition at line 284 of file ChaosCache.h.
Referenced by FCacheUserToken(), FCacheUserToken(), and IsOpen().
UChaosCache
friend FCacheUserToken::UChaosCache private
Definition at line 280 of file ChaosCache.h.
Referenced by FCacheUserToken().
The documentation for this struct was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Experimental/ChaosCaching/Source/ChaosCaching/Public/Chaos/ChaosCache.h