Unreal Engine 5.6 C++ API: FGenericPlatformApplicationMisc Struct Reference
FGenericPlatformApplicationMisc Struct Reference
#include "GenericPlatformApplicationMisc.h"
Public Types
enum EScreenSaverAction { Disable , Enable }
Static Public Member Functions
static bool AnchorWindowWindowPositionTopLeft ()
static APPLICATIONCORE_API void ClipboardCopy (const TCHAR *Str)
Copies text to the operating system clipboard.
static APPLICATIONCORE_API void ClipboardPaste (class FString &Dest)
Pastes in text from the operating system clipboard.
static APPLICATIONCORE_API EScreenPhysicalAccuracy ComputePhysicalScreenDensity (int32 &OutScreenDensity)
Gets the physical size of the screen if possible.
static bool ControlScreensaver (EScreenSaverAction Action)
Disables screensaver (if platform supports such an API)
template<typename T, typename T2 UE_REQUIRES>
static EScreenPhysicalAccuracy ConvertInchesToPixels (T Inches, T2 &OutPixels)
If we know or can approximate the pixel density of the screen we will convert the incoming inches to pixels on the device.
template<typename T, typename T2 UE_REQUIRES>
static EScreenPhysicalAccuracy ConvertPixelsToInches (T Pixels, T2 &OutInches)
If we know or can approximate the pixel density of the screen we will convert the incoming pixels to inches on the device.
static APPLICATIONCORE_API class GenericApplication * CreateApplication ()
Creates an application instance.
static APPLICATIONCORE_API FOutputDeviceConsole * CreateConsoleOutputDevice ()
Creates a console output device for this platform.
static APPLICATIONCORE_API IPlatformInputDeviceMapper * CreatePlatformInputDeviceManager ()
Gets a pointer to the default platform input device manager.
static void EnableMotionData (bool bEnable)
static float GetDPIScaleFactorAtPoint (float X, float Y)
Returns monitor's DPI scale factor at given screen coordinates (expressed in pixels)
static APPLICATIONCORE_API FOutputDeviceError * GetErrorOutputDevice ()
Gets a pointer to the platform error output device singleton.
static APPLICATIONCORE_API FFeedbackContext * GetFeedbackContext ()
Gets a pointer to the default platform feedback context implementation.
static class UTexture2D * GetGamepadButtonGlyph (const FGamepadKeyNames::Type &ButtonKey, uint32 ControllerIndex)
static FString GetGamepadControllerName (int32 ControllerId)
static APPLICATIONCORE_API EScreenPhysicalAccuracy GetPhysicalScreenDensity (int32 &OutScreenDensity)
Gets the physical size of the screen if possible.
static APPLICATIONCORE_API struct FLinearColor GetScreenPixelColor (const FVector2D &InScreenPos, float InGamma=1.0f)
Sample the displayed pixel color from anywhere on the screen using the OS.
static bool GetWindowTitleMatchingText (const TCHAR *TitleStartsWith, FString &OutTitle)
Searches for a window that matches the window name or the title starts with a particular text.
static APPLICATIONCORE_API void Init ()
static bool IsControllerAssignedToGamepad (int32 ControllerId)
static APPLICATIONCORE_API bool IsHighDPIAwarenessEnabled ()
static bool IsMotionDataEnabled ()
static bool IsScreensaverEnabled ()
Returns state of screensaver (if platform supports it)
static APPLICATIONCORE_API bool IsThisApplicationForeground ()
Returns true if the specified application has a visible window, and that window is active/has focus/is selected.
static void LoadPreInitModules ()
Load the preinit modules required by this platform, typically they are the renderer modules.
static void LoadStartupModules ()
Load the platform-specific startup modules.
static APPLICATIONCORE_API void PostInit ()
static APPLICATIONCORE_API void PreInit ()
static void PreventScreenSaver ()
Prevents screen-saver from kicking in by moving the mouse by 0 pixels.
static FORCEINLINE void PumpMessages (bool bFromMainLoop)
Pumps Windows messages.
static APPLICATIONCORE_API void RequestMinimize ()
Request application to minimize (goto background).
static APPLICATIONCORE_API bool RequiresVirtualKeyboard ()
Returns whether the platform wants to use a touch screen for a virtual keyboard.
static void ResetGamepadAssignments ()
static void ResetGamepadAssignmentToController (int32 ControllerId)
static void SetGamepadsAllowed (bool bAllowed)
static void SetGamepadsBlockDeviceFeedback (bool bAllowed)
static void SetHighDPIMode ()
Allows the OS to enable high DPI mode.
static bool ShowInputDeviceSelector (FPlatformUserId InitiatingUserId, FShowInputDeviceSelectorComplete OnShowInputDeviceSelectorComplete)
Asyncronously display the platform-specific input device selection UI, if supported.
static bool ShowPlatformUserSelector (FInputDeviceId InitiatingInputDeviceId, EPlatformUserSelectorFlags Flags, FPlatformUserSelectionComplete OnUserSelectionComplete)
Asyncronously display the platform-specific user selection UI, if supported.
static APPLICATIONCORE_API void TearDown ()
Static Protected Attributes
static APPLICATIONCORE_API EScreenPhysicalAccuracy CachedPhysicalScreenAccuracy
static APPLICATIONCORE_API bool CachedPhysicalScreenData
static APPLICATIONCORE_API int32 CachedPhysicalScreenDensity
static APPLICATIONCORE_API FAutoConsoleVariableRef CVarAllowVirtualKeyboard
static APPLICATIONCORE_API FAutoConsoleVariableRef CVarEnableHighDPIAwareness
Detailed Description
Definition at line 69 of file GenericPlatformApplicationMisc.h.
Member Enumeration Documentation
EScreenSaverAction
enum FGenericPlatformApplicationMisc::EScreenSaverAction
Enumerator
Disable
Enable
Definition at line 145 of file GenericPlatformApplicationMisc.h.
Member Function Documentation
AnchorWindowWindowPositionTopLeft()
bool FGenericPlatformApplicationMisc::AnchorWindowWindowPositionTopLeft () inline static
Definition at line 222 of file GenericPlatformApplicationMisc.h.
ClipboardCopy()
APPLICATIONCORE_API void FGenericPlatformApplicationMisc::ClipboardCopy (const TCHAR * Str) static
Copies text to the operating system clipboard.
ClipboardPaste()
APPLICATIONCORE_API void FGenericPlatformApplicationMisc::ClipboardPaste (class FString & Dest) static
Pastes in text from the operating system clipboard.
ComputePhysicalScreenDensity()
APPLICATIONCORE_API EScreenPhysicalAccuracy FGenericPlatformApplicationMisc::ComputePhysicalScreenDensity (int32 & OutScreenDensity) static
Gets the physical size of the screen if possible.
Some platforms lie, some platforms don't know.
ControlScreensaver()
bool FGenericPlatformApplicationMisc::ControlScreensaver (EScreenSaverAction Action) inline static
Disables screensaver (if platform supports such an API)
Parameters
Action enable or disable
Returns
true if succeeded, false if platform does not have this API and PreventScreenSaver() hack is needed
Definition at line 168 of file GenericPlatformApplicationMisc.h.
ConvertInchesToPixels()
template<typename T, typename T2 UE_REQUIRES> EScreenPhysicalAccuracy FGenericPlatformApplicationMisc::ConvertInchesToPixels (T Inches, T2 & OutPixels) inline static
If we know or can approximate the pixel density of the screen we will convert the incoming inches to pixels on the device.
If the accuracy is unknown OutPixels will be set to 0.
Definition at line 315 of file GenericPlatformApplicationMisc.h.
References GetPhysicalScreenDensity(), and Inches.
ConvertPixelsToInches()
template<typename T, typename T2 UE_REQUIRES> EScreenPhysicalAccuracy FGenericPlatformApplicationMisc::ConvertPixelsToInches (T Pixels, T2 & OutInches) inline static
If we know or can approximate the pixel density of the screen we will convert the incoming pixels to inches on the device.
If the accuracy is unknown OutInches will be set to 0.
Definition at line 337 of file GenericPlatformApplicationMisc.h.
References GetPhysicalScreenDensity(), and Pixels.
CreateApplication()
APPLICATIONCORE_API class GenericApplication * FGenericPlatformApplicationMisc::CreateApplication () static
Creates an application instance.
CreateConsoleOutputDevice()
APPLICATIONCORE_API FOutputDeviceConsole * FGenericPlatformApplicationMisc::CreateConsoleOutputDevice () static
Creates a console output device for this platform.
Should only be called once.
CreatePlatformInputDeviceManager()
APPLICATIONCORE_API IPlatformInputDeviceMapper * FGenericPlatformApplicationMisc::CreatePlatformInputDeviceManager () static
Gets a pointer to the default platform input device manager.
EnableMotionData()
void FGenericPlatformApplicationMisc::EnableMotionData (bool bEnable) inline static
Definition at line 283 of file GenericPlatformApplicationMisc.h.
GetDPIScaleFactorAtPoint()
float FGenericPlatformApplicationMisc::GetDPIScaleFactorAtPoint (float X, float Y) inline static
Returns monitor's DPI scale factor at given screen coordinates (expressed in pixels)
Returns
Monitor's DPI scale factor at given point
Definition at line 208 of file GenericPlatformApplicationMisc.h.
References X, and Y.
GetErrorOutputDevice()
APPLICATIONCORE_API FOutputDeviceError * FGenericPlatformApplicationMisc::GetErrorOutputDevice () static
Gets a pointer to the platform error output device singleton.
GetFeedbackContext()
APPLICATIONCORE_API FFeedbackContext * FGenericPlatformApplicationMisc::GetFeedbackContext () static
Gets a pointer to the default platform feedback context implementation.
GetGamepadButtonGlyph()
class UTexture2D * FGenericPlatformApplicationMisc::GetGamepadButtonGlyph (const FGamepadKeyNames::Type & ButtonKey, uint32 ControllerIndex) inline static
Definition at line 274 of file GenericPlatformApplicationMisc.h.
GetGamepadControllerName()
FString FGenericPlatformApplicationMisc::GetGamepadControllerName (int32 ControllerId) inline static
Definition at line 262 of file GenericPlatformApplicationMisc.h.
References IsControllerAssignedToGamepad(), and TEXT.
GetPhysicalScreenDensity()
APPLICATIONCORE_API EScreenPhysicalAccuracy FGenericPlatformApplicationMisc::GetPhysicalScreenDensity (int32 & OutScreenDensity) static
Gets the physical size of the screen if possible.
Some platforms lie, some platforms don't know.
Referenced by ConvertInchesToPixels(), and ConvertPixelsToInches().
GetScreenPixelColor()
APPLICATIONCORE_API struct FLinearColor FGenericPlatformApplicationMisc::GetScreenPixelColor (const FVector2D & InScreenPos, float InGamma = 1.0f) static
Sample the displayed pixel color from anywhere on the screen using the OS.
Parameters
InScreenPos The screen coords to sample for current pixel color
InGamma Optional gamma correction to apply to the screen color
Returns
The color of the pixel displayed at the chosen location
References GetScreenPixelColor().
Referenced by GetScreenPixelColor().
GetWindowTitleMatchingText()
bool FGenericPlatformApplicationMisc::GetWindowTitleMatchingText (const TCHAR * TitleStartsWith, FString & OutTitle) inline static
Searches for a window that matches the window name or the title starts with a particular text.
When found, it returns the title text for that window
Parameters
TitleStartsWith an alternative search method that knows part of the title text
OutTitle the string the data is copied into
Returns
whether the window was found and the text copied or not
Definition at line 191 of file GenericPlatformApplicationMisc.h.
Init()
APPLICATIONCORE_API void FGenericPlatformApplicationMisc::Init () static
IsControllerAssignedToGamepad()
bool FGenericPlatformApplicationMisc::IsControllerAssignedToGamepad (int32 ControllerId) inline static
Definition at line 254 of file GenericPlatformApplicationMisc.h.
Referenced by GetGamepadControllerName().
IsHighDPIAwarenessEnabled()
APPLICATIONCORE_API bool FGenericPlatformApplicationMisc::IsHighDPIAwarenessEnabled () static
Returns
true if the application is high dpi aware
Referenced by FMacPlatformApplicationMisc::IsHighDPIModeEnabled().
IsMotionDataEnabled()
bool FGenericPlatformApplicationMisc::IsMotionDataEnabled () inline static
Definition at line 289 of file GenericPlatformApplicationMisc.h.
IsScreensaverEnabled()
bool FGenericPlatformApplicationMisc::IsScreensaverEnabled () inline static
Returns state of screensaver (if platform supports it)
Returns
true if screensaver enabled (returns false if platform does not support it)
Definition at line 157 of file GenericPlatformApplicationMisc.h.
IsThisApplicationForeground()
APPLICATIONCORE_API bool FGenericPlatformApplicationMisc::IsThisApplicationForeground () static
Returns true if the specified application has a visible window, and that window is active/has focus/is selected.
LoadPreInitModules()
void FGenericPlatformApplicationMisc::LoadPreInitModules () inline static
Load the preinit modules required by this platform, typically they are the renderer modules.
Definition at line 82 of file GenericPlatformApplicationMisc.h.
LoadStartupModules()
void FGenericPlatformApplicationMisc::LoadStartupModules () inline static
Load the platform-specific startup modules.
Definition at line 89 of file GenericPlatformApplicationMisc.h.
PostInit()
APPLICATIONCORE_API void FGenericPlatformApplicationMisc::PostInit () static
PreInit()
APPLICATIONCORE_API void FGenericPlatformApplicationMisc::PreInit () static
PreventScreenSaver()
void FGenericPlatformApplicationMisc::PreventScreenSaver () inline static
Prevents screen-saver from kicking in by moving the mouse by 0 pixels.
This works even in the presence of a group policy for password protected screen saver.
Definition at line 141 of file GenericPlatformApplicationMisc.h.
PumpMessages()
FORCEINLINE void FGenericPlatformApplicationMisc::PumpMessages (bool bFromMainLoop) inline static
Pumps Windows messages.
Parameters
bFromMainLoop if true, this is from the main loop, otherwise we are spinning waiting for the render thread
Definition at line 133 of file GenericPlatformApplicationMisc.h.
References FORCEINLINE.
RequestMinimize()
APPLICATIONCORE_API void FGenericPlatformApplicationMisc::RequestMinimize () static
Request application to minimize (goto background).
RequiresVirtualKeyboard()
APPLICATIONCORE_API bool FGenericPlatformApplicationMisc::RequiresVirtualKeyboard () static
Returns whether the platform wants to use a touch screen for a virtual keyboard.
ResetGamepadAssignments()
void FGenericPlatformApplicationMisc::ResetGamepadAssignments () inline static
Definition at line 242 of file GenericPlatformApplicationMisc.h.
ResetGamepadAssignmentToController()
void FGenericPlatformApplicationMisc::ResetGamepadAssignmentToController (int32 ControllerId) inline static
Definition at line 248 of file GenericPlatformApplicationMisc.h.
SetGamepadsAllowed()
void FGenericPlatformApplicationMisc::SetGamepadsAllowed (bool bAllowed) inline static
Definition at line 230 of file GenericPlatformApplicationMisc.h.
SetGamepadsBlockDeviceFeedback()
void FGenericPlatformApplicationMisc::SetGamepadsBlockDeviceFeedback (bool bAllowed) inline static
Definition at line 236 of file GenericPlatformApplicationMisc.h.
SetHighDPIMode()
void FGenericPlatformApplicationMisc::SetHighDPIMode () inline static
Allows the OS to enable high DPI mode.
Definition at line 199 of file GenericPlatformApplicationMisc.h.
ShowInputDeviceSelector()
bool FGenericPlatformApplicationMisc::ShowInputDeviceSelector (FPlatformUserId InitiatingUserId, FShowInputDeviceSelectorComplete OnShowInputDeviceSelectorComplete) inline static
Asyncronously display the platform-specific input device selection UI, if supported.
Parameters
InitiatingUserId The platform user to find an input device for.
OnShowInputDeviceSelectorComplete Callback for when the input device selection operation has completed
Returns
true if the UI will be shown and the callback will be called
false if the platform does not support an input device selection API, or it is not currently available (the callback will not be called)
Definition at line 362 of file GenericPlatformApplicationMisc.h.
ShowPlatformUserSelector()
bool FGenericPlatformApplicationMisc::ShowPlatformUserSelector (FInputDeviceId InitiatingInputDeviceId, EPlatformUserSelectorFlags Flags, FPlatformUserSelectionComplete OnUserSelectionComplete) inline static
Asyncronously display the platform-specific user selection UI, if supported.
Parameters
InitiatingInputDeviceId The input device that prompted showing the UI, if applicable. The input device may be re-paired with the newly-selected user, depending on the platform
Flags customization options for the user selection UI.
OnUserSelectionComplete callback for when the user selection operation has completed
Returns
true if the UI will be shown and the callback will be called
false if the platform does not support a user-selection API, or it is not currently available (the callback will not be called)
Definition at line 377 of file GenericPlatformApplicationMisc.h.
References Flags.
TearDown()
APPLICATIONCORE_API void FGenericPlatformApplicationMisc::TearDown () static
Field Documentation
CachedPhysicalScreenAccuracy
APPLICATIONCORE_API EScreenPhysicalAccuracy FGenericPlatformApplicationMisc::CachedPhysicalScreenAccuracy static protected
Definition at line 386 of file GenericPlatformApplicationMisc.h.
CachedPhysicalScreenData
APPLICATIONCORE_API bool FGenericPlatformApplicationMisc::CachedPhysicalScreenData static protected
Definition at line 385 of file GenericPlatformApplicationMisc.h.
CachedPhysicalScreenDensity
APPLICATIONCORE_API int32 FGenericPlatformApplicationMisc::CachedPhysicalScreenDensity static protected
Definition at line 387 of file GenericPlatformApplicationMisc.h.
CVarAllowVirtualKeyboard
APPLICATIONCORE_API FAutoConsoleVariableRef FGenericPlatformApplicationMisc::CVarAllowVirtualKeyboard static protected
Definition at line 389 of file GenericPlatformApplicationMisc.h.
CVarEnableHighDPIAwareness
APPLICATIONCORE_API FAutoConsoleVariableRef FGenericPlatformApplicationMisc::CVarEnableHighDPIAwareness static protected
Definition at line 388 of file GenericPlatformApplicationMisc.h.
The documentation for this struct was generated from the following file:
Runtime/ApplicationCore/Public/GenericPlatform/GenericPlatformApplicationMisc.h