Unreal Engine 5.6 C++ API: FGenericPlatformTime Struct Reference
FGenericPlatformTime Struct Reference
Generic implementation for most platforms.
#include "GenericPlatformTime.h"
Static Public Member Functions
static void AutoUpdateGameThreadCPUTime (double UpdateInterval)
Registers automatic updates of Game Thread CPU utilization.
static FCPUTime GetCPUTime ()
static double GetLastIntervalCPUTimeInSeconds ()
static double GetLastIntervalThreadCPUTimeInSeconds ()
Gets the per-thread CPU processing time (kernel + user) from the last update.
static double GetSecondsPerCycle ()
Each platform implements these two functions, which return the current time in platform-specific cpu cycles.
static double GetSecondsPerCycle64 ()
Returns seconds per cycle, to pair with Cycles64().
static FCPUTime GetThreadCPUTime ()
Gets current threads CPU Utilization.
static FString PrettyTime (double Seconds)
Returns a pretty-string for a time given in seconds.
static uint64 SecondsToCycles64 (double Seconds)
Convert seconds to cycles, can be added to Cycles64 to set a high resolution timeout.
static TCHAR * StrDate (TCHAR *Dest, SIZE_T DestSize)
Get the system date.
static TCHAR * StrTime (TCHAR *Dest, SIZE_T DestSize)
Get the system time.
static const TCHAR * StrTimestamp ()
Returns a timestamp string built from the current date and time.
static float ToMilliseconds (const uint32 Cycles)
Converts cycles to milliseconds.
static double ToMilliseconds64 (const uint64 Cycles)
Converts 64 bit cycles to milliseconds.
static float ToSeconds (const uint32 Cycles)
Converts cycles to seconds.
static double ToSeconds64 (const uint64 Cycles)
Converts 64 bit cycles to seconds.
static bool UpdateCPUTime (float DeltaTime)
Updates CPU utilization, called through a delegate from the Core ticker.
static bool UpdateThreadCPUTime (float=0.0)
Updates current thread CPU utilization, calling is user defined per-thread (unused float parameter, is for FTicker compatibility).
Static Protected Attributes
static double LastIntervalCPUTimeInSeconds
static double SecondsPerCycle
static double SecondsPerCycle64
Detailed Description
Generic implementation for most platforms.
Definition at line 42 of file GenericPlatformTime.h.
Member Function Documentation
AutoUpdateGameThreadCPUTime()
void FGenericPlatformTime::AutoUpdateGameThreadCPUTime (double UpdateInterval) inline static
Registers automatic updates of Game Thread CPU utilization.
Definition at line 128 of file GenericPlatformTime.h.
GetCPUTime()
FCPUTime FGenericPlatformTime::GetCPUTime () inline static
Returns
structure that contains CPU utilization data.
Definition at line 135 of file GenericPlatformTime.h.
GetLastIntervalCPUTimeInSeconds()
double FGenericPlatformTime::GetLastIntervalCPUTimeInSeconds () inline static
Returns
the cpu processing time (kernel + user time of all threads) from the last update
Definition at line 153 of file GenericPlatformTime.h.
References LastIntervalCPUTimeInSeconds.
GetLastIntervalThreadCPUTimeInSeconds()
double FGenericPlatformTime::GetLastIntervalThreadCPUTimeInSeconds () inline static
Gets the per-thread CPU processing time (kernel + user) from the last update.
Returns
The per-thread CPU processing time from the last update
Definition at line 163 of file GenericPlatformTime.h.
GetSecondsPerCycle()
double FGenericPlatformTime::GetSecondsPerCycle () inline static
Each platform implements these two functions, which return the current time in platform-specific cpu cycles.
Cycles64 should be used for most purposes as it may be higher resolution and will not roll over during execution:
static uint32 Cycles(); static uint64 Cycles64(); Returns seconds per cycle, to pair with Cycles().
Definition at line 177 of file GenericPlatformTime.h.
References SecondsPerCycle.
Referenced by FCookStats::CallStats::LogStats(), FApplePlatformTime::Seconds(), and FWindowsPlatformTime::Seconds().
GetSecondsPerCycle64()
double FGenericPlatformTime::GetSecondsPerCycle64 () inline static
Returns seconds per cycle, to pair with Cycles64().
Definition at line 196 of file GenericPlatformTime.h.
References SecondsPerCycle64.
Referenced by UE::Insights::FStopwatch::Cycles64ToMilliseconds(), UE::Insights::FStopwatch::Cycles64ToSeconds(), UE::FIoFileBlockRequestQueue::GetByOffset(), SecondsToCycles64(), and ToSeconds64().
GetThreadCPUTime()
FCPUTime FGenericPlatformTime::GetThreadCPUTime () inline static
Gets current threads CPU Utilization.
Returns
Current threads CPU Utilization
Definition at line 145 of file GenericPlatformTime.h.
PrettyTime()
FString FGenericPlatformTime::PrettyTime (double Seconds) static
Returns a pretty-string for a time given in seconds.
(I.e. "4:31 min", "2:16:30 hours", etc)
Parameters
Seconds Time in seconds
Returns
Time in a pretty formatted string
References Seconds.
Referenced by FScopedDurationTimeCustomLogger< Func >::~FScopedDurationTimeCustomLogger().
SecondsToCycles64()
uint64 FGenericPlatformTime::SecondsToCycles64 (double Seconds) inline static
Convert seconds to cycles, can be added to Cycles64 to set a high resolution timeout.
Definition at line 214 of file GenericPlatformTime.h.
References GetSecondsPerCycle64(), and Seconds.
Referenced by UE::FTimeout::ModifyTimeoutSeconds(), and UE::FTimeout::SetTimeoutSeconds().
StrDate()
TCHAR * FGenericPlatformTime::StrDate (TCHAR * Dest, SIZE_T DestSize) static
Get the system date.
Parameters
Dest Destination buffer to copy to
DestSize Size of destination buffer in characters
Returns
Date string in the format "MM/DD/YY"
StrTime()
TCHAR * FGenericPlatformTime::StrTime (TCHAR * Dest, SIZE_T DestSize) static
Get the system time.
Parameters
Dest Destination buffer to copy to
DestSize Size of destination buffer in characters
Returns
Time string in the format "HH::mm::ss"
StrTimestamp()
const TCHAR * FGenericPlatformTime::StrTimestamp () static
Returns a timestamp string built from the current date and time.
NOTE: Only one return value is valid at a time!
Returns
timestamp string in the format "MM/DD/YY HH::mm::ss"
ToMilliseconds()
float FGenericPlatformTime::ToMilliseconds (const uint32 Cycles) inline static
Converts cycles to milliseconds.
Definition at line 183 of file GenericPlatformTime.h.
References SecondsPerCycle.
ToMilliseconds64()
double FGenericPlatformTime::ToMilliseconds64 (const uint64 Cycles) inline static
Converts 64 bit cycles to milliseconds.
Definition at line 202 of file GenericPlatformTime.h.
References ToSeconds64().
Referenced by Audio::FQuartzLatencyTimer::GetCurrentTimePassedMs(), and Audio::FQuartzLatencyTimer::GetResultsMilliseconds().
ToSeconds()
float FGenericPlatformTime::ToSeconds (const uint32 Cycles) inline static
Converts cycles to seconds.
Definition at line 189 of file GenericPlatformTime.h.
References SecondsPerCycle.
Referenced by FInputLatencyTimer::GetDeltaSeconds().
ToSeconds64()
double FGenericPlatformTime::ToSeconds64 (const uint64 Cycles) inline static
Converts 64 bit cycles to seconds.
Definition at line 208 of file GenericPlatformTime.h.
References GetSecondsPerCycle64().
Referenced by FInGamePerformanceTracker::GetAverageTimeSeconds(), UE::FTimeout::GetElapsedSeconds(), UE::FTimeout::GetTimeoutSeconds(), and ToMilliseconds64().
UpdateCPUTime()
bool FGenericPlatformTime::UpdateCPUTime (float DeltaTime) inline static
Updates CPU utilization, called through a delegate from the Core ticker.
Definition at line 116 of file GenericPlatformTime.h.
References DeltaTime.
UpdateThreadCPUTime()
bool FGenericPlatformTime::UpdateThreadCPUTime (float = 0.0) inline static
Updates current thread CPU utilization, calling is user defined per-thread (unused float parameter, is for FTicker compatibility).
Definition at line 122 of file GenericPlatformTime.h.
Field Documentation
LastIntervalCPUTimeInSeconds
double FGenericPlatformTime::LastIntervalCPUTimeInSeconds static protected
Definition at line 223 of file GenericPlatformTime.h.
Referenced by GetLastIntervalCPUTimeInSeconds().
SecondsPerCycle
double FGenericPlatformTime::SecondsPerCycle static protected
Definition at line 221 of file GenericPlatformTime.h.
Referenced by GetSecondsPerCycle(), ToMilliseconds(), and ToSeconds().
SecondsPerCycle64
double FGenericPlatformTime::SecondsPerCycle64 static protected
Definition at line 222 of file GenericPlatformTime.h.
Referenced by GetSecondsPerCycle64().
The documentation for this struct was generated from the following file:
Runtime/Core/Public/GenericPlatform/GenericPlatformTime.h