Unreal Engine 5.6 C++ API: UE::Slate::FDeprecateOptionalVector2DParameter Struct Reference
UE::Slate::FDeprecateOptionalVector2DParameter Struct Reference
Defines an optional Slate vector parameter in a similar vein to FDeprecateVector2DParameter NOTE: DO NOT USE THIS TYPE DIRECTLY IN CLIENT CODE - ALL USAGES SHOULD USE FVector2f or float.
#include "SlateVector2.h"
Public Member Functions
FDeprecateOptionalVector2DParameter ()
FDeprecateOptionalVector2DParameter (const FVector2d &In)
FDeprecateOptionalVector2DParameter (const FVector2f &In)
FDeprecateOptionalVector2DParameter (const TOptional< FVector2d > &In)
FDeprecateOptionalVector2DParameter (const TOptional< FVector2f > &In)
Public Member Functions inherited from TOptional< FVector2f >
TOptional (const FVector2f &InValue)
Construct an OptionalType with a valid value.
~TOptional ()
FVector2f & Emplace (ArgsType &&... Args)
const FVector2f & Get (const FVector2f &DefaultValue UE_LIFETIMEBOUND) const UE_LIFETIMEBOUND
FVector2f * GetPtrOrNull ()
FVector2f & GetValue ()
bool IsSet () const
FORCEINLINE operator bool () const
FVector2f & operator* ()
FVector2f * operator-> ()
TOptional & operator= (const TOptional &Other)
void Reset ()
void Serialize (FArchive &Ar)
Additional Inherited Members
Public Types inherited from TOptional< FVector2f >
using ElementType
Detailed Description
Defines an optional Slate vector parameter in a similar vein to FDeprecateVector2DParameter NOTE: DO NOT USE THIS TYPE DIRECTLY IN CLIENT CODE - ALL USAGES SHOULD USE FVector2f or float.
Definition at line 518 of file SlateVector2.h.
Constructor & Destructor Documentation
FDeprecateOptionalVector2DParameter() [1/5]
UE::Slate::FDeprecateOptionalVector2DParameter::FDeprecateOptionalVector2DParameter () inline
Definition at line 520 of file SlateVector2.h.
Referenced by FDeprecateOptionalVector2DParameter(), and FDeprecateOptionalVector2DParameter().
FDeprecateOptionalVector2DParameter() [2/5]
UE::Slate::FDeprecateOptionalVector2DParameter::FDeprecateOptionalVector2DParameter (const FVector2f & In) inline
Definition at line 523 of file SlateVector2.h.
References TOptional< FVector2f >::TOptional().
FDeprecateOptionalVector2DParameter() [3/5]
UE::Slate::FDeprecateOptionalVector2DParameter::FDeprecateOptionalVector2DParameter (const TOptional< FVector2f > & In) inline
Definition at line 527 of file SlateVector2.h.
References TOptional< FVector2f >::TOptional().
FDeprecateOptionalVector2DParameter() [4/5]
UE::Slate::FDeprecateOptionalVector2DParameter::FDeprecateOptionalVector2DParameter (const FVector2d & In) inline
Definition at line 532 of file SlateVector2.h.
References FDeprecateOptionalVector2DParameter(), TOptional< FVector2f >::TOptional(), and UE::Slate::CastToVector2f().
FDeprecateOptionalVector2DParameter() [5/5]
UE::Slate::FDeprecateOptionalVector2DParameter::FDeprecateOptionalVector2DParameter (const TOptional< FVector2d > & In) inline
Definition at line 538 of file SlateVector2.h.
References FDeprecateOptionalVector2DParameter(), and TOptional< FVector2f >::TOptional().
The documentation for this struct was generated from the following file:
Runtime/SlateCore/Public/Types/SlateVector2.h