Unreal Engine 5.6 C++ API: TDirectoryTree< ValueType >::FIteratorInternal Struct Reference
TDirectoryTree< ValueType >::FIteratorInternal Struct Reference
Data Structures
struct FStackData
Public Member Functions
FIteratorInternal (const FIteratorInternal &Other)=delete
FIteratorInternal (FIteratorInternal &&Other)=delete
FIteratorInternal (FTreeNode &Root, EDirectoryTreeGetFlags InFlags, TCHAR InPathSeparator)
operator bool () const
bool operator!= (const FIterationSentinel &) const
TPair< FStringView, ValueType * > operator* () const
FIteratorInternal & operator++ ()
FIteratorInternal & operator= (const FIteratorInternal &Other)=delete
FIteratorInternal & operator= (FIteratorInternal &&Other)=delete
Private Member Functions
void IncrementRemainingChildRelPath (FStackData *Data)
void TraverseToValid ()
Private Attributes
EDirectoryTreeGetFlags Flags
TStringBuilder< 256 > Path
TCHAR PathSeparator
TArray< FStackData, TInlineAllocator< 10 > > Stack
Detailed Description
template<typename ValueType>
struct TDirectoryTree< ValueType >::FIteratorInternal
Definition at line 374 of file DirectoryTree.h.
Constructor & Destructor Documentation
FIteratorInternal() [1/3]
template<typename ValueType> TDirectoryTree< ValueType >::FIteratorInternal::FIteratorInternal (FTreeNode & Root, EDirectoryTreeGetFlags InFlags, TCHAR InPathSeparator) inline
Definition at line 1641 of file DirectoryTree.h.
References Flags, TDirectoryTree< ValueType >::FTreeNode::HasValue(), TDirectoryTree< ValueType >::FIteratorInternal::FStackData::Node, PathSeparator, TDirectoryTree< ValueType >::Root, Stack, and TraverseToValid().
Referenced by FIteratorInternal(), FIteratorInternal(), operator=(), and operator=().
FIteratorInternal() [2/3]
template<typename ValueType> TDirectoryTree< ValueType >::FIteratorInternal::FIteratorInternal (FIteratorInternal && Other) delete
References FIteratorInternal(), and Other.
FIteratorInternal() [3/3]
template<typename ValueType> TDirectoryTree< ValueType >::FIteratorInternal::FIteratorInternal (const FIteratorInternal & Other) delete
References FIteratorInternal(), and Other.
Member Function Documentation
IncrementRemainingChildRelPath()
template<typename ValueType> void TDirectoryTree< ValueType >::FIteratorInternal::IncrementRemainingChildRelPath (FStackData * Data) inline private
Definition at line 1797 of file DirectoryTree.h.
References FPathViews::Append(), UE::DirectoryTree::FixupPathSeparator(), Path, PathSeparator, TDirectoryTree< ValueType >::FIteratorInternal::FStackData::RemainingChildRelPath, and FPathViews::SplitFirstComponent().
Referenced by operator++(), and TraverseToValid().
operator bool()
template<typename ValueType> TDirectoryTree< ValueType >::FIteratorInternal::operator bool () const inline explicit
Definition at line 1668 of file DirectoryTree.h.
References TDirectoryTree< ValueType >::TDirectoryTree(), and Stack.
operator!=()
template<typename ValueType> bool TDirectoryTree< ValueType >::FIteratorInternal::operator!= (const FIterationSentinel &) const inline
Definition at line 1674 of file DirectoryTree.h.
operator*()
template<typename ValueType> TPair< FStringView, ValueType * > TDirectoryTree< ValueType >::FIteratorInternal::operator* () const inline
Definition at line 1659 of file DirectoryTree.h.
References check, TDirectoryTree< ValueType >::FIteratorInternal::FStackData::ClosestValue, TDirectoryTree< ValueType >::FIteratorInternal::FStackData::Node, Path, and Stack.
operator++()
template<typename ValueType> TDirectoryTree< ValueType >::FIteratorInternal & TDirectoryTree< ValueType >::FIteratorInternal::operator++ ()
Definition at line 1680 of file DirectoryTree.h.
References TDirectoryTree< ValueType >::FIteratorInternal::FStackData::bChildRelPathInitialized, check, TDirectoryTree< ValueType >::FIteratorInternal::FStackData::ChildIndex, TDirectoryTree< ValueType >::FTreeNode::GetNumChildNodes(), IncrementRemainingChildRelPath(), TStringView< CharType >::IsEmpty(), TDirectoryTree< ValueType >::FIteratorInternal::FStackData::Node, TDirectoryTree< ValueType >::FIteratorInternal::FStackData::RemainingChildRelPath, Stack, and TraverseToValid().
operator=() [1/2]
template<typename ValueType> FIteratorInternal & TDirectoryTree< ValueType >::FIteratorInternal::operator= (const FIteratorInternal & Other) delete
References FIteratorInternal(), and Other.
operator=() [2/2]
template<typename ValueType> FIteratorInternal & TDirectoryTree< ValueType >::FIteratorInternal::operator= (FIteratorInternal && Other) delete
References FIteratorInternal(), and Other.
TraverseToValid()
template<typename ValueType> void TDirectoryTree< ValueType >::FIteratorInternal::TraverseToValid () private
Definition at line 1710 of file DirectoryTree.h.
References FPathViews::Append(), TDirectoryTree< ValueType >::FIteratorInternal::FStackData::bChildNodeInitialized, TDirectoryTree< ValueType >::FIteratorInternal::FStackData::bChildRelPathInitialized, TDirectoryTree< ValueType >::FIteratorInternal::FStackData::ChildIndex, TDirectoryTree< ValueType >::FTreeNode::ChildNodes, TDirectoryTree< ValueType >::FIteratorInternal::FStackData::ClosestValue, EnumHasAnyFlags(), UE::DirectoryTree::FixupPathSeparator(), Flags, TDirectoryTree< ValueType >::FTreeNode::GetNumChildNodes(), TDirectoryTree< ValueType >::FTreeNode::HasValue(), ImpliedChildren, IncrementRemainingChildRelPath(), TStringView< CharType >::IsEmpty(), No, TDirectoryTree< ValueType >::FIteratorInternal::FStackData::Node, Path, TDirectoryTree< ValueType >::FIteratorInternal::FStackData::PathLenBeforeChildNode, PathSeparator, Recursive, TDirectoryTree< ValueType >::FTreeNode::RelPaths, TDirectoryTree< ValueType >::FIteratorInternal::FStackData::RemainingChildRelPath, and Stack.
Referenced by FIteratorInternal(), and operator++().
Field Documentation
Flags
template<typename ValueType> EDirectoryTreeGetFlags TDirectoryTree< ValueType >::FIteratorInternal::Flags private
Definition at line 414 of file DirectoryTree.h.
Referenced by FIteratorInternal(), and TraverseToValid().
Path
template<typename ValueType> TStringBuilder<256> TDirectoryTree< ValueType >::FIteratorInternal::Path private
Definition at line 413 of file DirectoryTree.h.
Referenced by IncrementRemainingChildRelPath(), operator*(), and TraverseToValid().
PathSeparator
template<typename ValueType> TCHAR TDirectoryTree< ValueType >::FIteratorInternal::PathSeparator private
Definition at line 415 of file DirectoryTree.h.
Referenced by FIteratorInternal(), IncrementRemainingChildRelPath(), and TraverseToValid().
Stack
template<typename ValueType> TArray<FStackData, TInlineAllocator<10> > TDirectoryTree< ValueType >::FIteratorInternal::Stack private
Definition at line 412 of file DirectoryTree.h.
Referenced by FIteratorInternal(), operator bool(), operator*(), operator++(), and TraverseToValid().
The documentation for this struct was generated from the following file:
Runtime/Core/Public/Containers/DirectoryTree.h