Unreal Engine 5.6 C++ API: UE::MovieScene::TPropertyTrackWithOverridableChannelsEntityImportHelperImpl< T > Struct Template Reference
UE::MovieScene::TPropertyTrackWithOverridableChannelsEntityImportHelperImpl< T > Struct Template Reference
Same as TPropertyTrackEntityImportHelperImpl but with support for overridable channels.
#include "MovieScenePropertyTrack.h"
Public Member Functions
TPropertyTrackWithOverridableChannelsEntityImportHelperImpl (TEntityBuilder< T... > &&InBuilder, FPropertyTrackEntityImportHelperParamsImpl &InOverrideInfo, FComponentTypeID InPropertyTag={})
template<typename U, typename PayloadType>
TPropertyTrackEntityImportHelperImpl< T..., TAddConditional< U > > Add (TComponentTypeID< U > ComponentType, PayloadType &&InPayload, FChannelOverrideEntityImportParams OverrideParams)
template<typename U, typename PayloadType>
TPropertyTrackEntityImportHelperImpl< T..., TAddConditional< U > > AddConditional (TComponentTypeID< U > ComponentType, PayloadType &&InPayload, bool bCondition, FChannelOverrideEntityImportParams OverrideParams)
void Commit (const UMovieSceneSection *InSection, const UE::MovieScene::FEntityImportParams &Params, UE::MovieScene::FImportedEntity *OutImportedEntity)
Protected Attributes
TEntityBuilder< T... > Builder
FPropertyTrackEntityImportHelperParamsImpl OverrideInfo
FComponentTypeID PropertyTag
Detailed Description
template<typename... T>
struct UE::MovieScene::TPropertyTrackWithOverridableChannelsEntityImportHelperImpl< T >
Same as TPropertyTrackEntityImportHelperImpl but with support for overridable channels.
Definition at line 295 of file MovieScenePropertyTrack.h.
Constructor & Destructor Documentation
TPropertyTrackWithOverridableChannelsEntityImportHelperImpl()
template<typename... T> UE::MovieScene::TPropertyTrackWithOverridableChannelsEntityImportHelperImpl< T >::TPropertyTrackWithOverridableChannelsEntityImportHelperImpl (TEntityBuilder< T... > && InBuilder, FPropertyTrackEntityImportHelperParamsImpl & InOverrideInfo, FComponentTypeID InPropertyTag = {}) inline
Definition at line 297 of file MovieScenePropertyTrack.h.
Member Function Documentation
Add()
template<typename... T> template<typename U, typename PayloadType> TPropertyTrackEntityImportHelperImpl< T..., TAddConditional< U > > UE::MovieScene::TPropertyTrackWithOverridableChannelsEntityImportHelperImpl< T >::Add (TComponentTypeID< U > ComponentType, PayloadType && InPayload, FChannelOverrideEntityImportParams OverrideParams) inline
Definition at line 305 of file MovieScenePropertyTrack.h.
References Builder, UE::MovieScene::FChannelOverrideEntityImportParams::ChannelName, MoveTemp(), OverrideInfo, and PropertyTag.
AddConditional()
template<typename... T> template<typename U, typename PayloadType> TPropertyTrackEntityImportHelperImpl< T..., TAddConditional< U > > UE::MovieScene::TPropertyTrackWithOverridableChannelsEntityImportHelperImpl< T >::AddConditional (TComponentTypeID< U > ComponentType, PayloadType && InPayload, bool bCondition, FChannelOverrideEntityImportParams OverrideParams) inline
Definition at line 316 of file MovieScenePropertyTrack.h.
References Builder, UE::MovieScene::FChannelOverrideEntityImportParams::ChannelName, MoveTemp(), OverrideInfo, and PropertyTag.
Referenced by Commit().
Commit()
template<typename... T> void UE::MovieScene::TPropertyTrackWithOverridableChannelsEntityImportHelperImpl< T >::Commit (const UMovieSceneSection * InSection, const UE::MovieScene::FEntityImportParams & Params, UE::MovieScene::FImportedEntity * OutImportedEntity) inline
Definition at line 326 of file MovieScenePropertyTrack.h.
References Add, UE::MovieScene::FImportedEntity::AddBuilder(), AddConditional(), Builder, Cast(), UE::MovieScene::FChannelOverrideEntityImportParams::ChannelName, check, ensure, UE::MovieScene::FBuiltInComponentTypes::GenericObjectBinding, UE::MovieScene::FBuiltInComponentTypes::Get(), UE::MovieScene::FMovieSceneTracksComponentTypes::Get(), FMovieScenePropertyTrackEntityImportHelper::ImportEditConditionToggleEntity(), FMovieScenePropertyTrackEntityImportHelper::IsEditConditionToggleID(), FMovieScenePropertyTrackEntityImportHelper::IsPropertyValueID(), FGuid::IsValid(), TInlineValue< BaseType, DesiredMaxInlineSize, DefaultAlignment >::IsValid(), OverrideInfo, Params, UE::MovieScene::FBuiltInComponentTypes::PropertyBinding, and PropertyTag.
Field Documentation
Builder
template<typename... T> TEntityBuilder<T...> UE::MovieScene::TPropertyTrackWithOverridableChannelsEntityImportHelperImpl< T >::Builder protected
Definition at line 383 of file MovieScenePropertyTrack.h.
Referenced by Add(), AddConditional(), and Commit().
OverrideInfo
template<typename... T> FPropertyTrackEntityImportHelperParamsImpl UE::MovieScene::TPropertyTrackWithOverridableChannelsEntityImportHelperImpl< T >::OverrideInfo protected
Definition at line 384 of file MovieScenePropertyTrack.h.
Referenced by Add(), AddConditional(), and Commit().
PropertyTag
template<typename... T> FComponentTypeID UE::MovieScene::TPropertyTrackWithOverridableChannelsEntityImportHelperImpl< T >::PropertyTag protected
Definition at line 385 of file MovieScenePropertyTrack.h.
Referenced by Add(), AddConditional(), and Commit().
The documentation for this struct was generated from the following file:
Runtime/MovieSceneTracks/Public/Tracks/MovieScenePropertyTrack.h