Unreal Engine 5.6 C++ API: TTypeBitSetBase< TImplementation, TBaseStruct, TStructType, TBitSetContainer, bTestInheritanceAtRuntime > Struct Template Reference
TTypeBitSetBase< TImplementation, TBaseStruct, TStructType, TBitSetContainer, bTestInheritanceAtRuntime > Struct Template Reference
Base class for managing bitsets associated with specific struct types.
#include "StructTypeBitSet.h"
Data Structures
struct FIndexIterator
Iterator for traversing indices of bits with a specified value (true or false).
Public Types
using FBaseStruct = TBaseStruct
using FContainer = TBitSetContainer
using FUStructType = TStructType
Public Member Functions
void Add (const FUStructType &InStructType)
Adds a struct type to the bitset.
bool Contains (const FUStructType &InStructType) const
Checks if the bitset contains a specific struct type.
int32 CountStoredTypes () const
Counts the number of set bits in the bitset.
template<typename TOutStructType, typename Allocator>
void ExportTypes (TArray< const TOutStructType *, Allocator > &OutTypes) const
Exports types stored in the bitset to an output array.
SIZE_T GetAllocatedSize () const
Gets the allocated size of the bitset.
TImplementation & GetImplementation ()
Retrieves the derived implementation of this base class.
const TImplementation & GetImplementation () const
Retrieves the derived implementation of this base class (const version).
FIndexIterator GetIndexIterator (const bool bValueToCheck=true) const
Creates an index iterator for bits with the specified value.
FORCEINLINE TImplementation GetOverlap (const TImplementation &Other) const
FORCEINLINE bool HasAll (const TImplementation &Other) const
FORCEINLINE bool HasAny (const TImplementation &Other) const
FORCEINLINE bool HasNone (const TImplementation &Other) const
FORCEINLINE bool IsBitSet (const int32 BitIndex) const
Checks if a specific bit is set in the bitset.
bool IsEmpty () const
Checks if the bitset is empty (no bits are set).
FORCEINLINE bool IsEquivalent (const TImplementation &Other) const
Checks if the current bitset is equivalent to another, i.e., whether both contain same "true" bits and ignoring the trailing "false" bits.
FORCEINLINE TImplementation operator& (const TImplementation &Other) const
Performs a bitwise AND operation with another bitset.
FORCEINLINE TImplementation operator+ (const FUStructType &NewElement) const
Adds a struct type to the bitset, returning a new bitset.
FORCEINLINE void operator+= (const TImplementation &Other)
Adds the bits from another bitset to this one (union).
FORCEINLINE TImplementation operator- (const FUStructType &NewElement) const
Removes a struct type from the bitset, returning a new bitset.
FORCEINLINE void operator-= (const TImplementation &Other)
Removes the bits from another bitset from this one (difference).
FORCEINLINE TImplementation operator| (const TImplementation &Other) const
Performs a bitwise OR operation with another bitset.
void Remove (const FUStructType &InStructType)
Removes a struct type from the bitset.
void Reset ()
Resets all bits in the bitset.
void SetAll (const bool bValue=true)
Sets all bits in the bitset to the specified value.
Static Public Member Functions
static FORCEINLINE_DEBUGGABLE const UStruct * GetBaseUStruct ()
Retrieves the base UStruct type used for validation.
Protected Member Functions
TTypeBitSetBase ()=default
Default constructor.
TTypeBitSetBase (FContainer &InContainer)
Constructor accepting a container.
Protected Attributes
FContainer StructTypesBitArray
The bitset container storing the bits representing struct types.
Detailed Description
template<typename TImplementation, typename TBaseStruct, typename TStructType, typename TBitSetContainer, bool bTestInheritanceAtRuntime = WITH_STRUCTUTILS_DEBUG>
struct TTypeBitSetBase< TImplementation, TBaseStruct, TStructType, TBitSetContainer, bTestInheritanceAtRuntime >
Base class for managing bitsets associated with specific struct types.
Provides a foundation for derived classes to handle operations like adding, removing, and checking for struct types.
Parameters
TImplementation - The derived type implementing this base class.
TBaseStruct - The base struct type for type validation.
TStructType - Unreal's struct type, typically UScriptStruct or UClass.
TBitSetContainer - The container type for storing bitsets.
bTestInheritanceAtRuntime - Flag to enable runtime inheritance checks.
Definition at line 401 of file StructTypeBitSet.h.
Member Typedef Documentation
FBaseStruct
template<typename TImplementation, typename TBaseStruct, typename TStructType, typename TBitSetContainer, bool bTestInheritanceAtRuntime = WITH_STRUCTUTILS_DEBUG> using TTypeBitSetBase< TImplementation, TBaseStruct, TStructType, TBitSetContainer, bTestInheritanceAtRuntime >::FBaseStruct = TBaseStruct
Definition at line 404 of file StructTypeBitSet.h.
FContainer
template<typename TImplementation, typename TBaseStruct, typename TStructType, typename TBitSetContainer, bool bTestInheritanceAtRuntime = WITH_STRUCTUTILS_DEBUG> using TTypeBitSetBase< TImplementation, TBaseStruct, TStructType, TBitSetContainer, bTestInheritanceAtRuntime >::FContainer = TBitSetContainer
Definition at line 405 of file StructTypeBitSet.h.
FUStructType
template<typename TImplementation, typename TBaseStruct, typename TStructType, typename TBitSetContainer, bool bTestInheritanceAtRuntime = WITH_STRUCTUTILS_DEBUG> using TTypeBitSetBase< TImplementation, TBaseStruct, TStructType, TBitSetContainer, bTestInheritanceAtRuntime >::FUStructType = TStructType
Definition at line 403 of file StructTypeBitSet.h.
Constructor & Destructor Documentation
TTypeBitSetBase() [1/2]
template<typename TImplementation, typename TBaseStruct, typename TStructType, typename TBitSetContainer, bool bTestInheritanceAtRuntime = WITH_STRUCTUTILS_DEBUG> TTypeBitSetBase< TImplementation, TBaseStruct, TStructType, TBitSetContainer, bTestInheritanceAtRuntime >::TTypeBitSetBase () protected default
Default constructor.
TTypeBitSetBase() [2/2]
template<typename TImplementation, typename TBaseStruct, typename TStructType, typename TBitSetContainer, bool bTestInheritanceAtRuntime = WITH_STRUCTUTILS_DEBUG> TTypeBitSetBase< TImplementation, TBaseStruct, TStructType, TBitSetContainer, bTestInheritanceAtRuntime >::TTypeBitSetBase (FContainer & InContainer) inline protected
Constructor accepting a container.
Parameters
InContainer - The bitset container to use.
Definition at line 765 of file StructTypeBitSet.h.
Member Function Documentation
Add()
template<typename TImplementation, typename TBaseStruct, typename TStructType, typename TBitSetContainer, bool bTestInheritanceAtRuntime = WITH_STRUCTUTILS_DEBUG> void TTypeBitSetBase< TImplementation, TBaseStruct, TStructType, TBitSetContainer, bTestInheritanceAtRuntime >::Add (const FUStructType & InStructType) inline
Adds a struct type to the bitset.
Parameters
InStructType - The struct type to add.
Definition at line 509 of file StructTypeBitSet.h.
Contains()
template<typename TImplementation, typename TBaseStruct, typename TStructType, typename TBitSetContainer, bool bTestInheritanceAtRuntime = WITH_STRUCTUTILS_DEBUG> bool TTypeBitSetBase< TImplementation, TBaseStruct, TStructType, TBitSetContainer, bTestInheritanceAtRuntime >::Contains (const FUStructType & InStructType) const inline
Checks if the bitset contains a specific struct type.
Parameters
InStructType - The struct type to check for.
Returns
True if the struct type is in the bitset; false otherwise.
Definition at line 558 of file StructTypeBitSet.h.
CountStoredTypes()
template<typename TImplementation, typename TBaseStruct, typename TStructType, typename TBitSetContainer, bool bTestInheritanceAtRuntime = WITH_STRUCTUTILS_DEBUG> int32 TTypeBitSetBase< TImplementation, TBaseStruct, TStructType, TBitSetContainer, bTestInheritanceAtRuntime >::CountStoredTypes () const inline
Counts the number of set bits in the bitset.
Returns
The number of set bits.
Definition at line 690 of file StructTypeBitSet.h.
ExportTypes()
template<typename TImplementation, typename TBaseStruct, typename TStructType, typename TBitSetContainer, bool bTestInheritanceAtRuntime = WITH_STRUCTUTILS_DEBUG> template<typename TOutStructType, typename Allocator> void TTypeBitSetBase< TImplementation, TBaseStruct, TStructType, TBitSetContainer, bTestInheritanceAtRuntime >::ExportTypes (TArray< const TOutStructType *, Allocator > & OutTypes) const inline
Exports types stored in the bitset to an output array.
Note: This method can be slow due to the use of weak pointers in the struct tracker.
Todo
To be improved.
Parameters
OutTypes - The array to populate with struct types.
Definition at line 702 of file StructTypeBitSet.h.
GetAllocatedSize()
template<typename TImplementation, typename TBaseStruct, typename TStructType, typename TBitSetContainer, bool bTestInheritanceAtRuntime = WITH_STRUCTUTILS_DEBUG> SIZE_T TTypeBitSetBase< TImplementation, TBaseStruct, TStructType, TBitSetContainer, bTestInheritanceAtRuntime >::GetAllocatedSize () const inline
Gets the allocated size of the bitset.
Returns
The allocated memory size in bytes.
Definition at line 750 of file StructTypeBitSet.h.
GetBaseUStruct()
template<typename TImplementation, typename TBaseStruct, typename TStructType, typename TBitSetContainer, bool bTestInheritanceAtRuntime = WITH_STRUCTUTILS_DEBUG> FORCEINLINE_DEBUGGABLE const UStruct * TTypeBitSetBase< TImplementation, TBaseStruct, TStructType, TBitSetContainer, bTestInheritanceAtRuntime >::GetBaseUStruct () inline static
Retrieves the base UStruct type used for validation.
Returns
Pointer to the base UStruct.
Definition at line 483 of file StructTypeBitSet.h.
GetImplementation() [1/2]
template<typename TImplementation, typename TBaseStruct, typename TStructType, typename TBitSetContainer, bool bTestInheritanceAtRuntime = WITH_STRUCTUTILS_DEBUG> TImplementation & TTypeBitSetBase< TImplementation, TBaseStruct, TStructType, TBitSetContainer, bTestInheritanceAtRuntime >::GetImplementation () inline
Retrieves the derived implementation of this base class.
Returns
Reference to the derived implementation.
Definition at line 465 of file StructTypeBitSet.h.
Referenced by TTypeBitSetBase< TStructTypeBitSet, TBaseStruct, TUStructType, FStructTypeBitSet::FBitSetContainer >::Add(), TTypeBitSetBase< TStructTypeBitSet, TBaseStruct, TUStructType, FStructTypeBitSet::FBitSetContainer >::Contains(), TTypeBitSetBase< TStructTypeBitSet, TBaseStruct, TUStructType, FStructTypeBitSet::FBitSetContainer >::ExportTypes(), TTypeBitSetBase< TStructTypeBitSet, TBaseStruct, TUStructType, FStructTypeBitSet::FBitSetContainer >::GetOverlap(), TTypeBitSetBase< TStructTypeBitSet, TBaseStruct, TUStructType, FStructTypeBitSet::FBitSetContainer >::operator+(), TTypeBitSetBase< TStructTypeBitSet, TBaseStruct, TUStructType, FStructTypeBitSet::FBitSetContainer >::operator-(), TTypeBitSetBase< TStructTypeBitSet, TBaseStruct, TUStructType, FStructTypeBitSet::FBitSetContainer >::Remove(), and TTypeBitSetBase< TStructTypeBitSet, TBaseStruct, TUStructType, FStructTypeBitSet::FBitSetContainer >::SetAll().
GetImplementation() [2/2]
template<typename TImplementation, typename TBaseStruct, typename TStructType, typename TBitSetContainer, bool bTestInheritanceAtRuntime = WITH_STRUCTUTILS_DEBUG> const TImplementation & TTypeBitSetBase< TImplementation, TBaseStruct, TStructType, TBitSetContainer, bTestInheritanceAtRuntime >::GetImplementation () const inline
Retrieves the derived implementation of this base class (const version).
Returns
Const reference to the derived implementation.
Definition at line 474 of file StructTypeBitSet.h.
GetIndexIterator()
template<typename TImplementation, typename TBaseStruct, typename TStructType, typename TBitSetContainer, bool bTestInheritanceAtRuntime = WITH_STRUCTUTILS_DEBUG> FIndexIterator TTypeBitSetBase< TImplementation, TBaseStruct, TStructType, TBitSetContainer, bTestInheritanceAtRuntime >::GetIndexIterator (const bool bValueToCheck = true) const inline
Creates an index iterator for bits with the specified value.
Parameters
bValueToCheck - The bit value to search for (true or false).
Returns
An iterator to traverse indices of matching bits.
Definition at line 456 of file StructTypeBitSet.h.
GetOverlap()
template<typename TImplementation, typename TBaseStruct, typename TStructType, typename TBitSetContainer, bool bTestInheritanceAtRuntime = WITH_STRUCTUTILS_DEBUG> FORCEINLINE TImplementation TTypeBitSetBase< TImplementation, TBaseStruct, TStructType, TBitSetContainer, bTestInheritanceAtRuntime >::GetOverlap (const TImplementation & Other) const inline
Definition at line 594 of file StructTypeBitSet.h.
HasAll()
template<typename TImplementation, typename TBaseStruct, typename TStructType, typename TBitSetContainer, bool bTestInheritanceAtRuntime = WITH_STRUCTUTILS_DEBUG> FORCEINLINE bool TTypeBitSetBase< TImplementation, TBaseStruct, TStructType, TBitSetContainer, bTestInheritanceAtRuntime >::HasAll (const TImplementation & Other) const inline
Definition at line 610 of file StructTypeBitSet.h.
HasAny()
template<typename TImplementation, typename TBaseStruct, typename TStructType, typename TBitSetContainer, bool bTestInheritanceAtRuntime = WITH_STRUCTUTILS_DEBUG> FORCEINLINE bool TTypeBitSetBase< TImplementation, TBaseStruct, TStructType, TBitSetContainer, bTestInheritanceAtRuntime >::HasAny (const TImplementation & Other) const inline
Definition at line 615 of file StructTypeBitSet.h.
HasNone()
template<typename TImplementation, typename TBaseStruct, typename TStructType, typename TBitSetContainer, bool bTestInheritanceAtRuntime = WITH_STRUCTUTILS_DEBUG> FORCEINLINE bool TTypeBitSetBase< TImplementation, TBaseStruct, TStructType, TBitSetContainer, bTestInheritanceAtRuntime >::HasNone (const TImplementation & Other) const inline
Definition at line 620 of file StructTypeBitSet.h.
IsBitSet()
template<typename TImplementation, typename TBaseStruct, typename TStructType, typename TBitSetContainer, bool bTestInheritanceAtRuntime = WITH_STRUCTUTILS_DEBUG> FORCEINLINE bool TTypeBitSetBase< TImplementation, TBaseStruct, TStructType, TBitSetContainer, bTestInheritanceAtRuntime >::IsBitSet (const int32 BitIndex) const inline
Checks if a specific bit is set in the bitset.
Parameters
BitIndex - The index of the bit to check.
Returns
True if the bit is set; false otherwise.
Definition at line 639 of file StructTypeBitSet.h.
IsEmpty()
template<typename TImplementation, typename TBaseStruct, typename TStructType, typename TBitSetContainer, bool bTestInheritanceAtRuntime = WITH_STRUCTUTILS_DEBUG> bool TTypeBitSetBase< TImplementation, TBaseStruct, TStructType, TBitSetContainer, bTestInheritanceAtRuntime >::IsEmpty () const inline
Checks if the bitset is empty (no bits are set).
Returns
True if the bitset is empty.
Definition at line 629 of file StructTypeBitSet.h.
IsEquivalent()
template<typename TImplementation, typename TBaseStruct, typename TStructType, typename TBitSetContainer, bool bTestInheritanceAtRuntime = WITH_STRUCTUTILS_DEBUG> FORCEINLINE bool TTypeBitSetBase< TImplementation, TBaseStruct, TStructType, TBitSetContainer, bTestInheritanceAtRuntime >::IsEquivalent (const TImplementation & Other) const inline
Checks if the current bitset is equivalent to another, i.e., whether both contain same "true" bits and ignoring the trailing "false" bits.
Parameters
Other - The other bitset to compare.
Returns
True if both bitsets are equivalent; false otherwise.
Definition at line 605 of file StructTypeBitSet.h.
operator&()
template<typename TImplementation, typename TBaseStruct, typename TStructType, typename TBitSetContainer, bool bTestInheritanceAtRuntime = WITH_STRUCTUTILS_DEBUG> FORCEINLINE TImplementation TTypeBitSetBase< TImplementation, TBaseStruct, TStructType, TBitSetContainer, bTestInheritanceAtRuntime >::operator& (const TImplementation & Other) const inline
Performs a bitwise AND operation with another bitset.
Parameters
Other - The other bitset to intersect with.
Returns
A new bitset representing the intersection.
Definition at line 579 of file StructTypeBitSet.h.
operator+()
template<typename TImplementation, typename TBaseStruct, typename TStructType, typename TBitSetContainer, bool bTestInheritanceAtRuntime = WITH_STRUCTUTILS_DEBUG> FORCEINLINE TImplementation TTypeBitSetBase< TImplementation, TBaseStruct, TStructType, TBitSetContainer, bTestInheritanceAtRuntime >::operator+ (const FUStructType & NewElement) const inline
Adds a struct type to the bitset, returning a new bitset.
Parameters
NewElement - The struct type to add.
Returns
A new bitset with the added struct type.
Definition at line 667 of file StructTypeBitSet.h.
operator+=()
template<typename TImplementation, typename TBaseStruct, typename TStructType, typename TBitSetContainer, bool bTestInheritanceAtRuntime = WITH_STRUCTUTILS_DEBUG> FORCEINLINE void TTypeBitSetBase< TImplementation, TBaseStruct, TStructType, TBitSetContainer, bTestInheritanceAtRuntime >::operator+= (const TImplementation & Other) inline
Adds the bits from another bitset to this one (union).
Parameters
Other - The other bitset to add.
Definition at line 648 of file StructTypeBitSet.h.
operator-()
template<typename TImplementation, typename TBaseStruct, typename TStructType, typename TBitSetContainer, bool bTestInheritanceAtRuntime = WITH_STRUCTUTILS_DEBUG> FORCEINLINE TImplementation TTypeBitSetBase< TImplementation, TBaseStruct, TStructType, TBitSetContainer, bTestInheritanceAtRuntime >::operator- (const FUStructType & NewElement) const inline
Removes a struct type from the bitset, returning a new bitset.
Parameters
NewElement - The struct type to remove.
Returns
A new bitset with the struct type removed.
Definition at line 679 of file StructTypeBitSet.h.
operator-=()
template<typename TImplementation, typename TBaseStruct, typename TStructType, typename TBitSetContainer, bool bTestInheritanceAtRuntime = WITH_STRUCTUTILS_DEBUG> FORCEINLINE void TTypeBitSetBase< TImplementation, TBaseStruct, TStructType, TBitSetContainer, bTestInheritanceAtRuntime >::operator-= (const TImplementation & Other) inline
Removes the bits from another bitset from this one (difference).
Parameters
Other - The other bitset to subtract.
Definition at line 657 of file StructTypeBitSet.h.
operator|()
template<typename TImplementation, typename TBaseStruct, typename TStructType, typename TBitSetContainer, bool bTestInheritanceAtRuntime = WITH_STRUCTUTILS_DEBUG> FORCEINLINE TImplementation TTypeBitSetBase< TImplementation, TBaseStruct, TStructType, TBitSetContainer, bTestInheritanceAtRuntime >::operator| (const TImplementation & Other) const inline
Performs a bitwise OR operation with another bitset.
Parameters
Other - The other bitset to union with.
Returns
A new bitset representing the union.
Definition at line 589 of file StructTypeBitSet.h.
Remove()
template<typename TImplementation, typename TBaseStruct, typename TStructType, typename TBitSetContainer, bool bTestInheritanceAtRuntime = WITH_STRUCTUTILS_DEBUG> void TTypeBitSetBase< TImplementation, TBaseStruct, TStructType, TBitSetContainer, bTestInheritanceAtRuntime >::Remove (const FUStructType & InStructType) inline
Removes a struct type from the bitset.
Parameters
InStructType - The struct type to remove.
Definition at line 529 of file StructTypeBitSet.h.
Reset()
template<typename TImplementation, typename TBaseStruct, typename TStructType, typename TBitSetContainer, bool bTestInheritanceAtRuntime = WITH_STRUCTUTILS_DEBUG> void TTypeBitSetBase< TImplementation, TBaseStruct, TStructType, TBitSetContainer, bTestInheritanceAtRuntime >::Reset () inline
Resets all bits in the bitset.
Definition at line 548 of file StructTypeBitSet.h.
SetAll()
template<typename TImplementation, typename TBaseStruct, typename TStructType, typename TBitSetContainer, bool bTestInheritanceAtRuntime = WITH_STRUCTUTILS_DEBUG> void TTypeBitSetBase< TImplementation, TBaseStruct, TStructType, TBitSetContainer, bTestInheritanceAtRuntime >::SetAll (const bool bValue = true) inline
Sets all bits in the bitset to the specified value.
Parameters
bValue - The value to set for all bits (default is true).
Definition at line 500 of file StructTypeBitSet.h.
Field Documentation
StructTypesBitArray
template<typename TImplementation, typename TBaseStruct, typename TStructType, typename TBitSetContainer, bool bTestInheritanceAtRuntime = WITH_STRUCTUTILS_DEBUG> FContainer TTypeBitSetBase< TImplementation, TBaseStruct, TStructType, TBitSetContainer, bTestInheritanceAtRuntime >::StructTypesBitArray protected
The bitset container storing the bits representing struct types.
Definition at line 777 of file StructTypeBitSet.h.
The documentation for this struct was generated from the following file:
Runtime/CoreUObject/Public/StructUtils/StructTypeBitSet.h