Unreal Engine 5.6 C++ API: FInputCapturePriority Struct Reference
FInputCapturePriority Struct Reference
Each UInputBehavior provides a priority that is used to help resolve situations when multiple Behaviors want to capture based on the same input event.
#include "InputBehavior.h"
Public Member Functions
FInputCapturePriority (int priority=DEFAULT_TOOL_PRIORITY)
FInputCapturePriority MakeHigher (int DeltaAmount=1) const
FInputCapturePriority MakeLower (int DeltaAmount=1) const
Data Fields
int Priority
Constant priority value.
Static Public Attributes
static constexpr int DEFAULT_GIZMO_PRIORITY = 50
static constexpr int DEFAULT_TOOL_PRIORITY = 100
Friends
bool operator< (const FInputCapturePriority &l, const FInputCapturePriority &r)
bool operator== (const FInputCapturePriority &l, const FInputCapturePriority &r)
Detailed Description
Each UInputBehavior provides a priority that is used to help resolve situations when multiple Behaviors want to capture based on the same input event.
Definition at line 188 of file InputBehavior.h.
Constructor & Destructor Documentation
FInputCapturePriority()
FInputCapturePriority::FInputCapturePriority (int priority = DEFAULT_TOOL_PRIORITY) inline
Definition at line 196 of file InputBehavior.h.
References DEFAULT_TOOL_PRIORITY, and Priority.
Referenced by MakeHigher(), MakeLower(), operator<, and operator==.
Member Function Documentation
MakeHigher()
FInputCapturePriority FInputCapturePriority::MakeHigher (int DeltaAmount = 1) const inline
Returns
a priority higher than this priority
Definition at line 208 of file InputBehavior.h.
References FInputCapturePriority(), and Priority.
MakeLower()
FInputCapturePriority FInputCapturePriority::MakeLower (int DeltaAmount = 1) const inline
Returns
a priority lower than this priority
Definition at line 202 of file InputBehavior.h.
References FInputCapturePriority(), and Priority.
Friends And Related Symbol Documentation
operator<
bool operator< (const FInputCapturePriority & l, const FInputCapturePriority & r) friend
Definition at line 213 of file InputBehavior.h.
References FInputCapturePriority(), and Priority.
operator==
bool operator== (const FInputCapturePriority & l, const FInputCapturePriority & r) friend
Definition at line 217 of file InputBehavior.h.
References FInputCapturePriority(), and Priority.
Field Documentation
DEFAULT_GIZMO_PRIORITY
int FInputCapturePriority::DEFAULT_GIZMO_PRIORITY = 50 static constexpr
Definition at line 190 of file InputBehavior.h.
DEFAULT_TOOL_PRIORITY
int FInputCapturePriority::DEFAULT_TOOL_PRIORITY = 100 static constexpr
Definition at line 191 of file InputBehavior.h.
Referenced by FInputCapturePriority().
Priority
int FInputCapturePriority::Priority
Constant priority value.
Definition at line 194 of file InputBehavior.h.
Referenced by FInputCapturePriority(), MakeHigher(), MakeLower(), operator<, and operator==.
The documentation for this struct was generated from the following file:
Runtime/InteractiveToolsFramework/Public/InputBehavior.h