Unreal Engine 5.6 C++ API: UE::MovieScene::FPlaybackCapabilityPtr Struct Reference
UE::MovieScene::FPlaybackCapabilityPtr Struct Reference
Return value for accessing raw capabalities.
#include "MovieScenePlaybackCapabilities.h"
Public Member Functions
template<typename T>
T & ResolveChecked () const
template<typename T>
T * ResolveOptional () const
Data Fields
void * Ptr = 0
EPlaybackCapabilityStorageMode StorageMode
Detailed Description
Return value for accessing raw capabalities.
Definition at line 29 of file MovieScenePlaybackCapabilities.h.
Member Function Documentation
ResolveChecked()
template<typename T> T & UE::MovieScene::FPlaybackCapabilityPtr::ResolveChecked () const inline
Definition at line 56 of file MovieScenePlaybackCapabilities.h.
References check, checkf, UE::MovieScene::Inline, Ptr, UE::MovieScene::RawPointer, UE::MovieScene::SharedPointer, StorageMode, and TEXT.
Referenced by UE::MovieScene::FPlaybackCapabilities::DoAddCapability(), and UE::MovieScene::FPlaybackCapabilities::GetCapabilityChecked().
ResolveOptional()
template<typename T> T * UE::MovieScene::FPlaybackCapabilityPtr::ResolveOptional () const inline
Definition at line 35 of file MovieScenePlaybackCapabilities.h.
References checkf, UE::MovieScene::Inline, Ptr, UE::MovieScene::RawPointer, UE::MovieScene::SharedPointer, StorageMode, and TEXT.
Referenced by UE::MovieScene::FPlaybackCapabilities::FindCapability().
Field Documentation
Ptr
void* UE::MovieScene::FPlaybackCapabilityPtr::Ptr = 0
Definition at line 31 of file MovieScenePlaybackCapabilities.h.
Referenced by ResolveChecked(), and ResolveOptional().
StorageMode
EPlaybackCapabilityStorageMode UE::MovieScene::FPlaybackCapabilityPtr::StorageMode
Definition at line 32 of file MovieScenePlaybackCapabilities.h.
Referenced by ResolveChecked(), and ResolveOptional().
The documentation for this struct was generated from the following file:
Runtime/MovieScene/Public/Evaluation/MovieScenePlaybackCapabilities.h