Unreal Engine 5.6 C++ API: FShaderTarget Struct Reference
FShaderTarget Struct Reference
#include "ShaderCore.h"
Public Member Functions
FShaderTarget ()
FShaderTarget (EShaderFrequency InFrequency, EShaderPlatform InPlatform)
EShaderFrequency GetFrequency () const
EShaderPlatform GetPlatform () const
Data Fields
union {
struct {
uint32 Frequency: SF_NumBits
uint32 Platform: SP_NumBits
}
uint32 Packed
};
Friends
uint32 GetTypeHash (FShaderTarget Target)
FArchive & operator<< (FArchive &Ar, FShaderTarget &Target)
bool operator== (const FShaderTarget &X, const FShaderTarget &Y)
Detailed Description
Definition at line 182 of file ShaderCore.h.
Constructor & Destructor Documentation
FShaderTarget() [1/2]
FShaderTarget::FShaderTarget () inline
Definition at line 195 of file ShaderCore.h.
References Packed.
Referenced by GetTypeHash, operator<<, and operator==.
FShaderTarget() [2/2]
FShaderTarget::FShaderTarget (EShaderFrequency InFrequency, EShaderPlatform InPlatform) inline
Definition at line 199 of file ShaderCore.h.
References Frequency, Packed, and Platform.
Member Function Documentation
GetFrequency()
EShaderFrequency FShaderTarget::GetFrequency () const inline
Definition at line 230 of file ShaderCore.h.
References Frequency.
GetPlatform()
EShaderPlatform FShaderTarget::GetPlatform () const inline
Definition at line 225 of file ShaderCore.h.
References Platform.
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (FShaderTarget Target) friend
Definition at line 235 of file ShaderCore.h.
References FShaderTarget(), and Target.
operator<<
FArchive & operator<< (FArchive & Ar, FShaderTarget & Target) friend
Definition at line 211 of file ShaderCore.h.
References FShaderTarget(), Ar, and Target.
operator==
bool operator== (const FShaderTarget & X, const FShaderTarget & Y) friend
Definition at line 206 of file ShaderCore.h.
References FShaderTarget(), X, and Y.
Field Documentation
[union]
union { ... } FShaderTarget
Frequency
uint32 FShaderTarget::Frequency
Definition at line 190 of file ShaderCore.h.
Referenced by FShaderTarget(), and GetFrequency().
Packed
uint32 FShaderTarget::Packed
Definition at line 187 of file ShaderCore.h.
Referenced by FShaderTarget(), and FShaderTarget().
Platform
uint32 FShaderTarget::Platform
Definition at line 191 of file ShaderCore.h.
Referenced by FShaderTarget(), and GetPlatform().
The documentation for this struct was generated from the following file:
Runtime/RenderCore/Public/ShaderCore.h