Unreal Engine 5.6 C++ API: UE::MovieScene::FPlayerIndexPlaybackCapability Struct Reference
UE::MovieScene::FPlayerIndexPlaybackCapability Struct Reference
Playback capability for storing an IMovieScenePlayer unique index.
#include "IMovieScenePlayer.h"
Public Member Functions
FPlayerIndexPlaybackCapability (uint16 InPlayerIndex)
Static Public Member Functions
static MOVIESCENE_API UE::MovieScene::TPlaybackCapabilityID< FPlayerIndexPlaybackCapability > GetPlaybackCapabilityID ()
static MOVIESCENE_API IMovieScenePlayer * GetPlayer (TSharedRef< const FSharedPlaybackState > Owner)
static MOVIESCENE_API uint16 GetPlayerIndex (TSharedRef< const FSharedPlaybackState > Owner)
Data Fields
uint16 PlayerIndex = (uint16)-1
Detailed Description
Playback capability for storing an IMovieScenePlayer unique index.
Definition at line 40 of file IMovieScenePlayer.h.
Constructor & Destructor Documentation
FPlayerIndexPlaybackCapability()
UE::MovieScene::FPlayerIndexPlaybackCapability::FPlayerIndexPlaybackCapability (uint16 InPlayerIndex) inline
Definition at line 47 of file IMovieScenePlayer.h.
References FPlayerIndexPlaybackCapability(), and PlayerIndex.
Referenced by FPlayerIndexPlaybackCapability(), and GetPlaybackCapabilityID().
Member Function Documentation
GetPlaybackCapabilityID()
MOVIESCENE_API UE::MovieScene::TPlaybackCapabilityID< FPlayerIndexPlaybackCapability > UE::MovieScene::FPlayerIndexPlaybackCapability::GetPlaybackCapabilityID () static
References FPlayerIndexPlaybackCapability().
GetPlayer()
MOVIESCENE_API IMovieScenePlayer * UE::MovieScene::FPlayerIndexPlaybackCapability::GetPlayer (TSharedRef< const FSharedPlaybackState > Owner) static
References GetPlayer(), and Owner.
Referenced by GetPlayer().
GetPlayerIndex()
MOVIESCENE_API uint16 UE::MovieScene::FPlayerIndexPlaybackCapability::GetPlayerIndex (TSharedRef< const FSharedPlaybackState > Owner) static
References GetPlayerIndex(), and Owner.
Referenced by GetPlayerIndex().
Field Documentation
PlayerIndex
uint16 UE::MovieScene::FPlayerIndexPlaybackCapability::PlayerIndex = (uint16)-1
Definition at line 51 of file IMovieScenePlayer.h.
Referenced by FPlayerIndexPlaybackCapability().
The documentation for this struct was generated from the following file:
Runtime/MovieScene/Public/IMovieScenePlayer.h