Unreal Engine 5.6 C++ API: FPrimitiveLODStats Struct Reference
FPrimitiveLODStats Struct Reference
#include "ComponentInterfaces.h"
Public Member Functions
FPrimitiveLODStats (const FPrimitiveLODStats &Other)=default
FPrimitiveLODStats (FPrimitiveLODStats &&Other)=default
FPrimitiveLODStats (int32 InLOD)
FORCEINLINE int32 GetDrawCount () const
FPrimitiveLODStats & operator= (const FPrimitiveLODStats &RHS)=default
FPrimitiveLODStats & operator= (FPrimitiveLODStats &&RHS)=default
Data Fields
bool bIsAvailable = true
bool bIsOptionalLOD = false
int32 LODIndex = 0
TArray< uint16 > MaterialIndices
uint32 Sections = 1
SIZE_T TotalResourceSize = 0
uint32 Triangles = 0
Detailed Description
Definition at line 17 of file ComponentInterfaces.h.
Constructor & Destructor Documentation
FPrimitiveLODStats() [1/3]
FPrimitiveLODStats::FPrimitiveLODStats (int32 InLOD) inline
Definition at line 27 of file ComponentInterfaces.h.
References LODIndex.
Referenced by FPrimitiveLODStats(), FPrimitiveLODStats(), operator=(), and operator=().
FPrimitiveLODStats() [2/3]
FPrimitiveLODStats::FPrimitiveLODStats (const FPrimitiveLODStats & Other) default
References FPrimitiveLODStats(), and Other.
FPrimitiveLODStats() [3/3]
FPrimitiveLODStats::FPrimitiveLODStats (FPrimitiveLODStats && Other) default
References FPrimitiveLODStats(), and Other.
Member Function Documentation
GetDrawCount()
FORCEINLINE int32 FPrimitiveLODStats::GetDrawCount () const inline
Definition at line 38 of file ComponentInterfaces.h.
References FORCEINLINE, MaterialIndices, and Sections.
operator=() [1/2]
FPrimitiveLODStats & FPrimitiveLODStats::operator= (const FPrimitiveLODStats & RHS) default
References FPrimitiveLODStats().
operator=() [2/2]
FPrimitiveLODStats & FPrimitiveLODStats::operator= (FPrimitiveLODStats && RHS) default
References FPrimitiveLODStats().
Field Documentation
bIsAvailable
bool FPrimitiveLODStats::bIsAvailable = true
Definition at line 23 of file ComponentInterfaces.h.
bIsOptionalLOD
bool FPrimitiveLODStats::bIsOptionalLOD = false
Definition at line 22 of file ComponentInterfaces.h.
LODIndex
int32 FPrimitiveLODStats::LODIndex = 0
Definition at line 19 of file ComponentInterfaces.h.
Referenced by FPrimitiveLODStats().
MaterialIndices
TArray<uint16> FPrimitiveLODStats::MaterialIndices
Definition at line 25 of file ComponentInterfaces.h.
Referenced by GetDrawCount().
Sections
uint32 FPrimitiveLODStats::Sections = 1
Definition at line 20 of file ComponentInterfaces.h.
Referenced by GetDrawCount().
TotalResourceSize
SIZE_T FPrimitiveLODStats::TotalResourceSize = 0
Definition at line 24 of file ComponentInterfaces.h.
Triangles
uint32 FPrimitiveLODStats::Triangles = 0
Definition at line 21 of file ComponentInterfaces.h.
The documentation for this struct was generated from the following file:
Runtime/Engine/Classes/Components/ComponentInterfaces.h