Unreal Engine 5.6 C++ API: UE::Slate::Private::FDefaultStyleCache Struct Reference
UE::Slate::Private::FDefaultStyleCache Struct Reference
Single point of access for various default styles used in UMG for runtime and editor with each style already having it's colors unlinked for reuse.
#include "DefaultStyleCache.h"
Data Structures
struct FStyles
Internal style default holder struct, used so that one can get a bundle of defaults relevant for runtime or editor.
Static Public Member Functions
static const FStyles & GetEditor ()
Gets singleton and returns editor styles from singleton.
static const FStyles & GetRuntime ()
Gets singleton and returns runtime styles from singleton.
Private Member Functions
FDefaultStyleCache ()
Static Private Member Functions
static FDefaultStyleCache & Get ()
Singleton getter, however private used since GetRuntime & GetEditor is preferred for styles.
Private Attributes
FStyles Editor
FStyles Runtime
Detailed Description
Single point of access for various default styles used in UMG for runtime and editor with each style already having it's colors unlinked for reuse.
Definition at line 17 of file DefaultStyleCache.h.
Constructor & Destructor Documentation
FDefaultStyleCache()
UE::Slate::Private::FDefaultStyleCache::FDefaultStyleCache () private
Referenced by Get().
Member Function Documentation
Get()
FDefaultStyleCache & UE::Slate::Private::FDefaultStyleCache::Get () static private
Singleton getter, however private used since GetRuntime & GetEditor is preferred for styles.
References FDefaultStyleCache().
Referenced by GetEditor(), and GetRuntime().
GetEditor()
const FStyles & UE::Slate::Private::FDefaultStyleCache::GetEditor () inline static
Gets singleton and returns editor styles from singleton.
Definition at line 104 of file DefaultStyleCache.h.
References Editor, and Get().
GetRuntime()
const FStyles & UE::Slate::Private::FDefaultStyleCache::GetRuntime () inline static
Gets singleton and returns runtime styles from singleton.
Definition at line 101 of file DefaultStyleCache.h.
References Get(), and Runtime.
Field Documentation
Editor
FStyles UE::Slate::Private::FDefaultStyleCache::Editor private
Definition at line 119 of file DefaultStyleCache.h.
Referenced by GetEditor().
Runtime
FStyles UE::Slate::Private::FDefaultStyleCache::Runtime private
Definition at line 116 of file DefaultStyleCache.h.
Referenced by GetRuntime().
The documentation for this struct was generated from the following file:
Runtime/SlateCore/Public/Styling/DefaultStyleCache.h