Unreal Engine 5.6 C++ API: FARCompiledFilter Struct Reference
FARCompiledFilter Struct Reference
A struct to serve as a filter for Asset Registry queries.
#include "ARFilter.h"
Public Member Functions
PRAGMA_DISABLE_DEPRECATION_WARNINGS FARCompiledFilter ()=default
FARCompiledFilter (const FARCompiledFilter &)=default
FARCompiledFilter (FARCompiledFilter &&)=default
void Clear ()
Clears this filter of all entries.
bool IsEmpty () const
Returns true if this filter has no entries.
FARCompiledFilter & operator= (const FARCompiledFilter &)=default
FARCompiledFilter & operator= (FARCompiledFilter &&)=default
UE_DEPRECATED (5.1, "Class names are now represented by path names. Please use ClassPaths.") TSet< FName > ClassNames
Deprecated.
UE_DEPRECATED (5.1, "Object path FNames have been deprecated, use FSoftObjectPath instead.") TSet< FName > ObjectPaths
The filter component containing specific object paths.
Data Fields
bool bIncludeOnlyOnDiskAssets = false
If true, only on-disk assets will be returned.
TSet< FTopLevelAssetPath > ClassPaths
The filter component for class names.
PRAGMA_ENABLE_DEPRECATION_WARNINGS TSet< FName > PackageNames
The filter component for package names.
TSet< FName > PackagePaths
The filter component for package paths.
TSet< FSoftObjectPath > SoftObjectPaths
The filter component containing specific object paths.
TMultiMap< FName, TOptional< FString > > TagsAndValues
The filter component for properties marked with the AssetRegistrySearchable flag.
uint32 WithoutPackageFlags = 0
The exclusive filter component for package flags.
uint32 WithPackageFlags = 0
The inclusive filter component for package flags.
Detailed Description
A struct to serve as a filter for Asset Registry queries.
Each component element is processed as an 'OR' operation while all the components are processed together as an 'AND' operation. This is a version of FARFilter optimized for querying, and can be generated from an FARFilter by calling IAssetRegistry::CompileFilter to resolve any recursion.
Definition at line 176 of file ARFilter.h.
Constructor & Destructor Documentation
FARCompiledFilter() [1/3]
PRAGMA_DISABLE_DEPRECATION_WARNINGS FARCompiledFilter::FARCompiledFilter () default
Referenced by FARCompiledFilter(), FARCompiledFilter(), operator=(), and operator=().
FARCompiledFilter() [2/3]
FARCompiledFilter::FARCompiledFilter (FARCompiledFilter &&) default
References FARCompiledFilter().
FARCompiledFilter() [3/3]
FARCompiledFilter::FARCompiledFilter (const FARCompiledFilter &) default
References FARCompiledFilter().
Member Function Documentation
Clear()
void FARCompiledFilter::Clear () inline
Clears this filter of all entries.
Definition at line 225 of file ARFilter.h.
References bIncludeOnlyOnDiskAssets, ClassPaths, ensure, IsEmpty(), PackageNames, PackagePaths, SoftObjectPaths, TagsAndValues, WithoutPackageFlags, and WithPackageFlags.
IsEmpty()
bool FARCompiledFilter::IsEmpty () const inline
Returns true if this filter has no entries.
Definition at line 219 of file ARFilter.h.
References ClassPaths, IsEmpty(), PackageNames, PackagePaths, SoftObjectPaths, and TagsAndValues.
Referenced by Clear(), and IsEmpty().
operator=() [1/2]
FARCompiledFilter & FARCompiledFilter::operator= (const FARCompiledFilter &) default
References FARCompiledFilter(), and PRAGMA_ENABLE_DEPRECATION_WARNINGS.
operator=() [2/2]
FARCompiledFilter & FARCompiledFilter::operator= (FARCompiledFilter &&) default
References FARCompiledFilter().
UE_DEPRECATED() [1/2]
FARCompiledFilter::UE_DEPRECATED (5. 1, "Class names are now represented by path names. Please use ClassPaths.")
Deprecated.
The filter component for class names. Instances of the specified classes, but not subclasses (by default), will be included. Derived classes will be included only if bRecursiveClasses is true.
References UE_DEPRECATED().
UE_DEPRECATED() [2/2]
FARCompiledFilter::UE_DEPRECATED (5. 1, "Object path FNames have been deprecated, use FSoftObjectPath instead.")
The filter component containing specific object paths.
Referenced by UE_DEPRECATED().
Field Documentation
bIncludeOnlyOnDiskAssets
bool FARCompiledFilter::bIncludeOnlyOnDiskAssets = false
If true, only on-disk assets will be returned.
Be warned that this is rarely what you want and should only be used for performance reasons
Definition at line 216 of file ARFilter.h.
Referenced by Clear().
ClassPaths
TSet<FTopLevelAssetPath> FARCompiledFilter::ClassPaths
The filter component for class names.
Instances of the specified classes, but not subclasses (by default), will be included. Derived classes will be included only if bRecursiveClasses is true.
Definition at line 204 of file ARFilter.h.
Referenced by Clear(), and IsEmpty().
PackageNames
PRAGMA_ENABLE_DEPRECATION_WARNINGS TSet<FName> FARCompiledFilter::PackageNames
The filter component for package names.
Definition at line 187 of file ARFilter.h.
Referenced by Clear(), and IsEmpty().
PackagePaths
TSet<FName> FARCompiledFilter::PackagePaths
The filter component for package paths.
Definition at line 190 of file ARFilter.h.
Referenced by Clear(), and IsEmpty().
SoftObjectPaths
TSet<FSoftObjectPath> FARCompiledFilter::SoftObjectPaths
The filter component containing specific object paths.
Definition at line 197 of file ARFilter.h.
Referenced by Clear(), and IsEmpty().
TagsAndValues
TMultiMap<FName, TOptional<FString> > FARCompiledFilter::TagsAndValues
The filter component for properties marked with the AssetRegistrySearchable flag.
Definition at line 207 of file ARFilter.h.
Referenced by Clear(), and IsEmpty().
WithoutPackageFlags
uint32 FARCompiledFilter::WithoutPackageFlags = 0
The exclusive filter component for package flags.
Only assets without any of the specified flags will be returned.
Definition at line 210 of file ARFilter.h.
Referenced by Clear().
WithPackageFlags
uint32 FARCompiledFilter::WithPackageFlags = 0
The inclusive filter component for package flags.
Only assets with all of the specified flags will be returned.
Definition at line 213 of file ARFilter.h.
Referenced by Clear().
The documentation for this struct was generated from the following file:
Runtime/CoreUObject/Public/AssetRegistry/ARFilter.h