Unreal Engine 5.6 C++ API: TCString< T > Struct Template Reference
TCString< T > Struct Template Reference
Set of basic string utility functions operating on plain C strings.
#include "CString.h"
Public Types
typedef T CharType
Public Member Functions
template<typename T>
FORCEINLINE TCString< T >::CharType * Strcat (CharType *Dest, SIZE_T DestCount, const CharType *Src)
template<typename T>
FORCEINLINE TCString< T >::CharType * Strcpy (CharType *Dest, SIZE_T DestCount, const CharType *Src)
UE_DEPRECATED (5.6, "Use StrncatTruncateDest instead.") static FORCEINLINE CharType *Strcat(CharType *Dest
UE_DEPRECATED (5.6, "Use StrncatTruncateDest instead.") static inline CharType *Strncat(CharType *Dest
UE_DEPRECATED (5.6, "Use Strncpy instead. Note that Strncpy has a behavior difference from Strcpy: it memzeroes the entire DestCount-sized buffer after the end of string.") static FORCEINLINE CharType *Strcpy(CharType *Dest
Static Public Member Functions
static FORCEINLINE double Atod (const CharType *String)
atod wrapper
static FORCEINLINE float Atof (const CharType *String)
atof wrapper
static FORCEINLINE int32 Atoi (const CharType *String)
atoi wrapper
static FORCEINLINE int64 Atoi64 (const CharType *String)
atoi64 wrapper
static FORCEINLINE int32 GetVarArgs (CharType *Dest, SIZE_T DestSize, const CharType *&Fmt, va_list ArgPtr)
Helper function to write formatted output using an argument list.
static bool IsNumeric (const CharType *Str)
Returns whether this string contains only numeric characters.
static bool IsPureAnsi (const CharType *Str)
Returns whether this string contains only pure ansi characters.
static bool IsPureAnsi (const CharType *Str, const SIZE_T StrLen)
template<typename FmtType, typename... Types>
static int32 Snprintf (CharType *Dest, int32 DestSize, const FmtType &Fmt, Types... Args)
Safe string formatted print.
static const CharType * Spc (int32 NumSpaces)
Returns a static string that is filled with a variable number of spaces.
template<typename FmtType, typename... Types>
static int32 Sprintf (CharType *Dest, const FmtType &Fmt, Types... Args)
Standard string formatted print.
static FORCEINLINE CharType * Strcat (CharType *Dest, const CharType *Src)
strcat wrapper
template<SIZE_T DestCount>
static FORCEINLINE CharType * Strcat (CharType(&Dest)[DestCount], const CharType *Src)
strcat wrapper (templated version to automatically handle static destination array case)
static FORCEINLINE CharType * Strchr (CharType *String, CharType c)
static FORCEINLINE const CharType * Strchr (const CharType *String, CharType c)
strchr wrapper
static FORCEINLINE int32 Strcmp (const CharType *String1, const CharType *String2)
strcmp wrapper
static FORCEINLINE CharType * Strcpy (CharType *Dest, const CharType *Src)
strcpy wrapper
template<SIZE_T DestCount>
static FORCEINLINE CharType * Strcpy (CharType(&Dest)[DestCount], const CharType *Src)
strcpy wrapper (templated version to automatically handle static destination array case)
static FORCEINLINE int32 Strcspn (const CharType *String, const CharType *Mask)
strcspn wrapper
static const CharType * Strfind (const CharType *Str, const CharType *Find, bool bSkipQuotedChars=false)
Find string in string, case sensitive, requires non-alphanumeric lead-in.
static const CharType * StrfindDelim (const CharType *Str, const CharType *Find, const CharType *Delim=LITERAL(CharType, " \t,"))
Finds string in string, case insensitive, requires the string be surrounded by one the specified delimiters, or the start or end of the string.
static FORCEINLINE int32 Stricmp (const CharType *String1, const CharType *String2)
stricmp wrapper
static const CharType * Strifind (const CharType *Str, const CharType *Find, bool bSkipQuotedChars=false)
Find string in string, case insensitive, requires non-alphanumeric lead-in.
static CharType * Stristr (CharType *Str, const CharType *Find)
Finds string in string, case insensitive (non-const version)
static const CharType * Stristr (const CharType *Str, const CharType *Find)
Finds string in string, case insensitive.
static FORCEINLINE int32 Strlen (const CharType *String)
strlen wrapper
static CharType * StrncatTruncateDest (CharType *Dest, int32 DestSize, const CharType *Src)
Concatenate a string with length checking.
static CharType * StrncatTruncateSrc (CharType *Dest, const CharType *Src, int32 SrcLen)
Append at most SrcLen characters from Src to Dest.
static FORCEINLINE int32 Strncmp (const CharType *String1, const CharType *String2, SIZE_T Count)
strncmp wrapper
static FORCEINLINE CharType * Strncpy (CharType *Dest, const CharType *Src, SIZE_T MaxLen)
Copy a string with length checking.
static FORCEINLINE int32 Strnicmp (const CharType *String1, const CharType *String2, SIZE_T Count)
strnicmp wrapper
static CharType * Strnistr (CharType *Str, int32 InStrLen, const CharType *Find, int32 FindLen)
Finds string in string, case insensitive (non-const version)
static const CharType * Strnistr (const CharType *Str, int32 InStrLen, const CharType *Find, int32 FindLen)
Finds string in string, case insensitive.
static FORCEINLINE int32 Strnlen (const CharType *String, SIZE_T StringSize)
Calculate the length of the string up to the given size.
static CharType * Strnstr (CharType *Str, int32 InStrLen, const CharType *Find, int32 FindLen)
Finds string in string, case sensitive (non-const version)
static const CharType * Strnstr (const CharType *Str, int32 InStrLen, const CharType *Find, int32 FindLen)
Finds string in string, case sensitive.
static FORCEINLINE CharType * Strrchr (CharType *String, CharType c)
static FORCEINLINE const CharType * Strrchr (const CharType *String, CharType c)
strrchr wrapper
static FORCEINLINE CharType * Strrstr (CharType *String, const CharType *Find)
static FORCEINLINE const CharType * Strrstr (const CharType *String, const CharType *Find)
strrstr wrapper
static FORCEINLINE int32 Strspn (const CharType *String, const CharType *Mask)
strspn wrapper
static FORCEINLINE CharType * Strstr (CharType *String, const CharType *Find)
static FORCEINLINE const CharType * Strstr (const CharType *String, const CharType *Find)
strstr wrapper
static FORCEINLINE int32 Strtoi (const CharType *Start, CharType **End, int32 Base)
strtoi wrapper
static FORCEINLINE int64 Strtoi64 (const CharType *Start, CharType **End, int32 Base)
strtoi wrapper
static FORCEINLINE CharType * Strtok (CharType *TokenString, const CharType *Delim, CharType **Context)
strtok wrapper
static FORCEINLINE uint64 Strtoui64 (const CharType *Start, CharType **End, int32 Base)
strtoui wrapper
static FORCEINLINE CharType * Strupr (CharType *Dest, SIZE_T DestCount)
strupr wrapper
template<SIZE_T DestCount>
static FORCEINLINE CharType * Strupr (CharType(&Dest)[DestCount])
strupr wrapper (templated version to automatically handle static destination array case)
static const CharType * Tab (int32 NumTabs)
Returns a static string that is filled with a variable number of tabs.
static bool ToBool (const CharType *String)
Converts a string into a boolean value 1, "True", "Yes", FCoreTexts::True, FCoreTexts::Yes, and non-zero integers become true 0, "False", "No", FCoreTexts::False, FCoreTexts::No, and unparsable values become false.
Data Fields
SIZE_T DestCount
SIZE_T DestSize
const CharType int32 DestSize
SIZE_T const CharType * Src
const CharType * Src
Private Types
template<typename SrcEncoding>
using TIsCharEncodingCompatibleWithCharType = TIsCharEncodingCompatibleWith<SrcEncoding, CharType>
Static Private Member Functions
static int32 VARARGS SnprintfImpl (CharType *Dest, int32 DestSize, const CharType *Fmt,...)
static int32 VARARGS SprintfImpl (CharType *Dest, const CharType *Fmt,...)
Detailed Description
template<typename T>
struct TCString< T >
Set of basic string utility functions operating on plain C strings.
In addition to the wrapped C string API,this struct also contains a set of widely used utility functions that operate on c strings. There is a specialized implementation for ANSICHAR and WIDECHAR strings provided. To access these functionality, the convenience typedefs FCString and FCStringAnsi are provided.
Definition at line 59 of file CString.h.
Member Typedef Documentation
CharType
template<typename T> typedef T TCString< T >::CharType
Definition at line 61 of file CString.h.
TIsCharEncodingCompatibleWithCharType
template<typename T> template<typename SrcEncoding> using TCString< T >::TIsCharEncodingCompatibleWithCharType = TIsCharEncodingCompatibleWith<SrcEncoding, CharType> private
Definition at line 561 of file CString.h.
Member Function Documentation
Atod()
template<typename T> FORCEINLINE double TCString< T >::Atod (const CharType * String) static
atod wrapper
Definition at line 1192 of file CString.h.
References FAndroidPlatformString::Atod(), and String.
Atof()
template<typename T> FORCEINLINE float TCString< T >::Atof (const CharType * String) static
atof wrapper
Definition at line 1186 of file CString.h.
References FAndroidPlatformString::Atof(), and String.
Atoi()
template<typename T> FORCEINLINE int32 TCString< T >::Atoi (const CharType * String) static
atoi wrapper
Definition at line 1174 of file CString.h.
References FAndroidPlatformString::Atoi(), and String.
Atoi64()
template<typename T> FORCEINLINE int64 TCString< T >::Atoi64 (const CharType * String) static
atoi64 wrapper
Definition at line 1180 of file CString.h.
References FAndroidPlatformString::Atoi64(), and String.
GetVarArgs()
template<typename T> FORCEINLINE int32 TCString< T >::GetVarArgs (CharType * Dest, SIZE_T DestSize, const CharType *& Fmt, va_list ArgPtr) static
Helper function to write formatted output using an argument list.
Parameters
Dest - destination string buffer
DestSize - size of destination buffer
Fmt - string to print
Args - argument list
Returns
number of characters written or -1 if truncated
Definition at line 1223 of file CString.h.
References DestSize, and FAndroidPlatformString::GetVarArgs().
IsNumeric()
template<typename T> bool TCString< T >::IsNumeric (const CharType * Str) inline static
Returns whether this string contains only numeric characters.
Parameters
Str - string that will be checked
Definition at line 139 of file CString.h.
IsPureAnsi() [1/2]
template<typename T> bool TCString< T >::IsPureAnsi (const CharType * Str) inline static
Returns whether this string contains only pure ansi characters.
Parameters
Str - string that will be checked
Definition at line 67 of file CString.h.
IsPureAnsi() [2/2]
template<typename T> bool TCString< T >::IsPureAnsi (const CharType * Str, const SIZE_T StrLen) inline static
Definition at line 101 of file CString.h.
Snprintf()
template<typename T> template<typename FmtType, typename... Types> int32 TCString< T >::Snprintf (CharType * Dest, int32 DestSize, const FmtType & Fmt, Types... Args) inline static
Safe string formatted print.
Definition at line 581 of file CString.h.
SnprintfImpl()
template<typename T> int32 TCString< T >::SnprintfImpl (CharType * Dest, int32 DestSize, const CharType * Fmt, ...) static private
Definition at line 1239 of file CString.h.
References DestSize, and GET_TYPED_VARARGS_RESULT.
Referenced by TCString< TCHAR >::Snprintf().
Spc()
template<typename T> const TCString< T >::CharType * TCString< T >::Spc (int32 NumSpaces) static
Returns a static string that is filled with a variable number of spaces.
Parameters
NumSpaces Number of spaces to put into the string, max of 255
Returns
The string of NumSpaces spaces.
Definition at line 624 of file CString.h.
References check, TCStringSpcHelper< CharType >::MAX_SPACES, and TCStringSpcHelper< CharType >::SpcArray.
Sprintf()
template<typename T> template<typename FmtType, typename... Types> int32 TCString< T >::Sprintf (CharType * Dest, const FmtType & Fmt, Types... Args) inline static
Standard string formatted print.
Warning
: make sure code using FCString::Sprintf allocates enough (>= MAX_SPRINTF) memory for the destination buffer
Definition at line 569 of file CString.h.
SprintfImpl()
template<typename T> int32 TCString< T >::SprintfImpl (CharType * Dest, const CharType * Fmt, ...) static private
Definition at line 1229 of file CString.h.
References GET_TYPED_VARARGS_RESULT, and MAX_SPRINTF.
Referenced by TCString< TCHAR >::Sprintf().
Strcat() [1/3]
template<typename T> FORCEINLINE TCString< T >::CharType * TCString< T >::Strcat (CharType * Dest, const CharType * Src) static
strcat wrapper
Parameters
Dest - destination string to copy to
Destcount - size of Dest in characters
Src - source string
Returns
destination string
Definition at line 999 of file CString.h.
References Src, and FAndroidPlatformString::Strcat().
Strcat() [2/3]
template<typename T> template<typename T> FORCEINLINE TCString< T >::CharType * TCString< T >::Strcat (CharType * Dest, SIZE_T DestCount, const CharType * Src)
Definition at line 1005 of file CString.h.
Strcat() [3/3]
template<typename T> template<SIZE_T DestCount> FORCEINLINE CharType * TCString< T >::Strcat (CharType(&) Dest[DestCount], const CharType * Src) inline static
strcat wrapper (templated version to automatically handle static destination array case)
Parameters
Dest - destination string to copy to
Src - source string
Returns
destination string
Definition at line 230 of file CString.h.
Strchr() [1/2]
template<typename T> FORCEINLINE TCString< T >::CharType * TCString< T >::Strchr (CharType * String, CharType c) static
Definition at line 1085 of file CString.h.
References FAndroidPlatformString::Strchr(), and String.
Strchr() [2/2]
template<typename T> FORCEINLINE const TCString< T >::CharType * TCString< T >::Strchr (const CharType * String, CharType c) static
strchr wrapper
Definition at line 1079 of file CString.h.
References FAndroidPlatformString::Strchr(), and String.
Referenced by StrfindDelim().
Strcmp()
template<typename T> FORCEINLINE int32 TCString< T >::Strcmp (const CharType * String1, const CharType * String2) static
strcmp wrapper
Definition at line 1019 of file CString.h.
References FAndroidPlatformString::Strcmp().
Strcpy() [1/3]
template<typename T> FORCEINLINE TCString< T >::CharType * TCString< T >::Strcpy (CharType * Dest, const CharType * Src) static
strcpy wrapper
Parameters
Dest - destination string to copy to
Destcount - size of Dest in characters
Src - source string
Returns
destination string
Definition at line 978 of file CString.h.
References Src, and FAndroidPlatformString::Strcpy().
Strcpy() [2/3]
template<typename T> template<typename T> FORCEINLINE TCString< T >::CharType * TCString< T >::Strcpy (CharType * Dest, SIZE_T DestCount, const CharType * Src)
Definition at line 984 of file CString.h.
Strcpy() [3/3]
template<typename T> template<SIZE_T DestCount> FORCEINLINE CharType * TCString< T >::Strcpy (CharType(&) Dest[DestCount], const CharType * Src) inline static
strcpy wrapper (templated version to automatically handle static destination array case)
Parameters
Dest - destination string to copy to
Src - source string
Returns
destination string
Definition at line 202 of file CString.h.
Strcspn()
template<typename T> FORCEINLINE int32 TCString< T >::Strcspn (const CharType * String, const CharType * Mask) static
strcspn wrapper
Definition at line 1154 of file CString.h.
References Mask, String, and UE_PTRDIFF_TO_INT32.
Strfind()
template<typename T> const TCString< T >::CharType * TCString< T >::Strfind (const CharType * Str, const CharType * Find, bool bSkipQuotedChars = false) static
Find string in string, case sensitive, requires non-alphanumeric lead-in.
Definition at line 641 of file CString.h.
References Find, LITERAL, Strlen(), and Strncmp().
StrfindDelim()
template<typename T> const TCString< T >::CharType * TCString< T >::StrfindDelim (const CharType * Str, const CharType * Find, const CharType * Delim = LITERAL(CharType, " \t,")) static
Finds string in string, case insensitive, requires the string be surrounded by one the specified delimiters, or the start or end of the string.
Definition at line 751 of file CString.h.
References Find, Found, LITERAL, Strchr(), Stristr(), and Strlen().
Stricmp()
template<typename T> FORCEINLINE int32 TCString< T >::Stricmp (const CharType * String1, const CharType * String2) static
stricmp wrapper
Definition at line 1031 of file CString.h.
References FGenericPlatformStricmp::Stricmp().
Strifind()
template<typename T> const TCString< T >::CharType * TCString< T >::Strifind (const CharType * Str, const CharType * Find, bool bSkipQuotedChars = false) static
Find string in string, case insensitive, requires non-alphanumeric lead-in.
Definition at line 692 of file CString.h.
References Find, LITERAL, Strlen(), and Strnicmp().
Stristr() [1/2]
template<typename T> CharType * TCString< T >::Stristr (CharType * Str, const CharType * Find) inline static
Finds string in string, case insensitive (non-const version)
Parameters
Str The string to look through
Find The string to find inside Str
Returns
Position in Str if Find was found, otherwise, nullptr. If Find is non-null but empty, returns Str.
Definition at line 393 of file CString.h.
Referenced by TCString< TCHAR >::Stristr().
Stristr() [2/2]
template<typename T> const TCString< T >::CharType * TCString< T >::Stristr (const CharType * Str, const CharType * Find) static
Finds string in string, case insensitive.
Parameters
Str The string to look through
Find The string to find inside Str
Returns
Position in Str if Find was found, otherwise, nullptr. If Find is non-null but empty, returns Str.
Parameters
Str The string to look through
Find The string to find inside Str
Returns
Position in Str if Find was found, otherwise, NULL. If Find is non-null but empty, returns Str.
Definition at line 799 of file CString.h.
References Find, Strlen(), Strnicmp(), and TChar< CharType >::ToUpper().
Referenced by StrfindDelim().
Strlen()
template<typename T> UE_NODEBUG FORCEINLINE int32 TCString< T >::Strlen (const CharType * String) static
strlen wrapper
Definition at line 1048 of file CString.h.
References FORCEINLINE, String, FAndroidPlatformString::Strlen(), UE::Core::Private::Strlen32(), and UE_NODEBUG.
Referenced by FMemoryImageString::FMemoryImageString(), TraceServices::TCachedStringStore< WIDECHAR >::TCachedStringStore(), TStringConversion< TUTF16ToUTF32_Convert< TCHAR, UTF32CHAR > >::TStringConversion(), FFormatArgsTrace::EncodeArgumentInternal(), FFormatArgsTrace::GetArgumentEncodedSize(), TStringPointer< TCHAR, UTF16CHAR >::Length(), Strfind(), StrfindDelim(), Strifind(), StringToArray(), Stristr(), TCString< TCHAR >::StrncatTruncateDest(), TCString< TCHAR >::StrncatTruncateSrc(), and Strrstr().
StrncatTruncateDest()
template<typename T> CharType * TCString< T >::StrncatTruncateDest (CharType * Dest, int32 DestSize, const CharType * Src) inline static
Concatenate a string with length checking.
Unlike the CRT strncat, the size argument is interpreted as the size of the Dest buffer (which must include space for the null terminator) rather than the max number of Src characters to append.
Parameters
Dest - destination buffer to append to
Src - source buffer to copy from
DestSize - max size of the dest buffer, including null terminator. Max number of non-terminating characters written into Dest is DestSize - 1.
Returns
pointer to resulting string buffer
Definition at line 281 of file CString.h.
Referenced by TCString< TCHAR >::Strcat().
StrncatTruncateSrc()
template<typename T> CharType * TCString< T >::StrncatTruncateSrc (CharType * Dest, const CharType * Src, int32 SrcLen) inline static
Append at most SrcLen characters from Src to Dest.
Append a null terminator after the last character from Src. This version matches the behavior of CRT strncat: the size given is the maximum number to append from the Src str. If you instead want to specify the length of the destination buffer, call StrncatTruncateDest.
Parameters
Dest - destination buffer to append to
Src - source buffer to copy from
SrcLen - maximum number of characters to copy from Src. If Src length is less than SrcLen, all characters up to the null terminator, and the null terminator, will be copied into Dest.
Returns
pointer to resulting string buffer
Definition at line 253 of file CString.h.
Strncmp()
template<typename T> FORCEINLINE int32 TCString< T >::Strncmp (const CharType * String1, const CharType * String2, SIZE_T Count) static
strncmp wrapper
Definition at line 1025 of file CString.h.
References Count, and FAndroidPlatformString::Strncmp().
Referenced by Strfind(), and Strnstr().
Strncpy()
template<typename T> FORCEINLINE TCString< T >::CharType * TCString< T >::Strncpy (CharType * Dest, const CharType * Src, SIZE_T MaxLen) static
Copy a string with length checking.
Behavior differs from strncpy in that last character is zeroed.
Parameters
Dest - destination buffer to copy to
Src - source buffer to copy from
MaxLen - max length of the buffer (including null-terminator)
Returns
pointer to resulting string buffer
Definition at line 992 of file CString.h.
References Src, and FAndroidPlatformString::Strncpy().
Referenced by TextFilterUtils::IntToStringBuffer(), and TCString< TCHAR >::Strcpy().
Strnicmp()
template<typename T> FORCEINLINE int32 TCString< T >::Strnicmp (const CharType * String1, const CharType * String2, SIZE_T Count) static
strnicmp wrapper
Definition at line 1037 of file CString.h.
References Count, and FGenericPlatformStricmp::Strnicmp().
Referenced by Strifind(), Stristr(), and Strnistr().
Strnistr() [1/2]
template<typename T> CharType * TCString< T >::Strnistr (CharType * Str, int32 InStrLen, const CharType * Find, int32 FindLen) inline static
Finds string in string, case insensitive (non-const version)
Parameters
Str The character array to look through
InStrLen The length of the Str array
Find The character array to find inside Str
FindLen The length of the Find array
Returns
Position in Str if Find was found, otherwise, nullptr. If FindLen is 0, returns Str.
Definition at line 413 of file CString.h.
Strnistr() [2/2]
template<typename T> const TCString< T >::CharType * TCString< T >::Strnistr (const CharType * Str, int32 InStrLen, const CharType * Find, int32 FindLen) static
Finds string in string, case insensitive.
Parameters
Str The character array to look through
InStrLen The length of the Str array
Find The character array to find inside Str
FindLen The length of the Find array
Returns
Position in Str if Find was found, otherwise, nullptr. If FindLen is 0, returns Str.
Definition at line 841 of file CString.h.
References checkf, Find, Strnicmp(), TEXT, and TChar< CharType >::ToUpper().
Referenced by TCString< TCHAR >::Strnistr().
Strnlen()
template<typename T> FORCEINLINE int32 TCString< T >::Strnlen (const CharType * String, SIZE_T StringSize) static
Calculate the length of the string up to the given size.
Parameters
String A possibly-null-terminated string in a character array with a size of at least StringSize.
StringSize The maximum number of characters to read from String.
Returns
Length The smaller of StringSize and the number of characters in String before a null character.
Definition at line 1061 of file CString.h.
References String, StringSize(), and FAndroidPlatformString::Strnlen().
Strnstr() [1/2]
template<typename T> CharType * TCString< T >::Strnstr (CharType * Str, int32 InStrLen, const CharType * Find, int32 FindLen) inline static
Finds string in string, case sensitive (non-const version)
Parameters
Str The character array to look through
InStrLen The length of the Str array
Find The character array to find inside Str
FindLen The length of the Find array
Returns
Position in Str if Find was found, otherwise, nullptr. If FindLen is 0, returns Str.
Definition at line 436 of file CString.h.
Strnstr() [2/2]
template<typename T> const TCString< T >::CharType * TCString< T >::Strnstr (const CharType * Str, int32 InStrLen, const CharType * Find, int32 FindLen) static
Finds string in string, case sensitive.
Parameters
Str The character array to look through
InStrLen The length of the Str array
Find The character array to find inside Str
FindLen The length of the Find array
Returns
Position in Str if Find was found, otherwise, nullptr. If FindLen is 0, returns Str.
Definition at line 881 of file CString.h.
References checkf, Find, Mask, Strncmp(), and TEXT.
Referenced by TCString< TCHAR >::Strnstr().
Strrchr() [1/2]
template<typename T> FORCEINLINE TCString< T >::CharType * TCString< T >::Strrchr (CharType * String, CharType c) static
Definition at line 1097 of file CString.h.
References String, and FAndroidPlatformString::Strrchr().
Strrchr() [2/2]
template<typename T> FORCEINLINE const TCString< T >::CharType * TCString< T >::Strrchr (const CharType * String, CharType c) static
strrchr wrapper
Definition at line 1091 of file CString.h.
References String, and FAndroidPlatformString::Strrchr().
Strrstr() [1/2]
template<typename T> FORCEINLINE TCString< T >::CharType * TCString< T >::Strrstr (CharType * String, const CharType * Find) static
Definition at line 1109 of file CString.h.
References Find, Found, String, Strlen(), and Strstr().
Strrstr() [2/2]
template<typename T> FORCEINLINE const TCString< T >::CharType * TCString< T >::Strrstr (const CharType * String, const CharType * Find) static
strrstr wrapper
Definition at line 1103 of file CString.h.
References Find, String, and Strrstr().
Referenced by Strrstr().
Strspn()
template<typename T> FORCEINLINE int32 TCString< T >::Strspn (const CharType * String, const CharType * Mask) static
strspn wrapper
Definition at line 1131 of file CString.h.
References Mask, String, and UE_PTRDIFF_TO_INT32.
Strstr() [1/2]
template<typename T> FORCEINLINE TCString< T >::CharType * TCString< T >::Strstr (CharType * String, const CharType * Find) static
Definition at line 1073 of file CString.h.
References Find, String, and FAndroidPlatformString::Strstr().
Strstr() [2/2]
template<typename T> FORCEINLINE const TCString< T >::CharType * TCString< T >::Strstr (const CharType * String, const CharType * Find) static
strstr wrapper
Definition at line 1067 of file CString.h.
References Find, String, and FAndroidPlatformString::Strstr().
Referenced by Strrstr().
Strtoi()
template<typename T> FORCEINLINE int32 TCString< T >::Strtoi (const CharType * Start, CharType ** End, int32 Base) static
strtoi wrapper
Definition at line 1198 of file CString.h.
References End, and FAndroidPlatformString::Strtoi().
Strtoi64()
template<typename T> FORCEINLINE int64 TCString< T >::Strtoi64 (const CharType * Start, CharType ** End, int32 Base) static
strtoi wrapper
Definition at line 1204 of file CString.h.
References End, and FAndroidPlatformString::Strtoi64().
Strtok()
template<typename T> FORCEINLINE TCString< T >::CharType * TCString< T >::Strtok (CharType * TokenString, const CharType * Delim, CharType ** Context) static
strtok wrapper
Definition at line 1217 of file CString.h.
References FAndroidPlatformString::Strtok().
Strtoui64()
template<typename T> FORCEINLINE uint64 TCString< T >::Strtoui64 (const CharType * Start, CharType ** End, int32 Base) static
strtoui wrapper
Definition at line 1210 of file CString.h.
References End, and FAndroidPlatformString::Strtoui64().
Strupr() [1/2]
template<typename T> FORCEINLINE TCString< T >::CharType * TCString< T >::Strupr (CharType * Dest, SIZE_T DestCount) static
strupr wrapper
Parameters
Dest - destination string to convert
Destcount - size of Dest in characters
Returns
destination string
Definition at line 1013 of file CString.h.
References DestCount, and FAndroidPlatformString::Strupr().
Referenced by TCString< TCHAR >::Strupr().
Strupr() [2/2]
template<typename T> template<SIZE_T DestCount> FORCEINLINE CharType * TCString< T >::Strupr (CharType(&) Dest[DestCount]) inline static
strupr wrapper (templated version to automatically handle static destination array case)
Parameters
Dest - destination string to convert
Returns
destination string
Definition at line 320 of file CString.h.
Tab()
template<typename T> const TCString< T >::CharType * TCString< T >::Tab (int32 NumTabs) static
Returns a static string that is filled with a variable number of tabs.
Parameters
NumTabs Number of tabs to put into the string, max of 255
Returns
The string of NumTabs tabs.
Definition at line 631 of file CString.h.
References check, TCStringSpcHelper< CharType >::MAX_TABS, and TCStringSpcHelper< CharType >::TabArray.
ToBool()
template<typename T> bool TCString< T >::ToBool (const CharType * String) inline static
Converts a string into a boolean value 1, "True", "Yes", FCoreTexts::True, FCoreTexts::Yes, and non-zero integers become true 0, "False", "No", FCoreTexts::False, FCoreTexts::No, and unparsable values become false.
Returns
The boolean value
Definition at line 515 of file CString.h.
UE_DEPRECATED() [1/3]
template<typename T> TCString< T >::UE_DEPRECATED (5. 6, "Use StrncatTruncateDest instead.")
UE_DEPRECATED() [2/3]
template<typename T> TCString< T >::UE_DEPRECATED (5. 6, "Use StrncatTruncateDest instead.")
UE_DEPRECATED() [3/3]
template<typename T> TCString< T >::UE_DEPRECATED (5. 6, "Use Strncpy instead. Note that Strncpy has a behavior difference from Strcpy: it memzeroes the entire DestCount-sized buffer after the end of string.")
Field Documentation
DestCount
template<typename T> SIZE_T TCString< T >::DestCount
Definition at line 181 of file CString.h.
Referenced by Strupr().
DestSize [1/2]
template<typename T> SIZE_T TCString< T >::DestSize
Definition at line 219 of file CString.h.
Referenced by GetVarArgs(), and SnprintfImpl().
DestSize [2/2]
template<typename T> const CharType int32 TCString< T >::DestSize
Initial value:
{
        return StrncatTruncateDest(Dest, DestSize, Src)
Definition at line 237 of file CString.h.
Src [1/2]
template<typename T> SIZE_T const CharType * TCString< T >::Src
Definition at line 181 of file CString.h.
Referenced by Strcat(), Strcpy(), and Strncpy().
Src [2/2]
template<typename T> const CharType* TCString< T >::Src
Definition at line 237 of file CString.h.
The documentation for this struct was generated from the following file:
Runtime/Core/Public/Misc/CString.h