Unreal Engine 5.6 C++ API: UE::AnimNext::FTraitRegistry Struct Reference
UE::AnimNext::FTraitRegistry Struct Reference final
FTraitRegistry.
#include "TraitRegistry.h"
Data Structures
struct FRegistryEntry
Public Member Functions
ANIMNEXTANIMGRAPH_API const FTrait * Find (const UScriptStruct *TraitSharedDataStruct) const
ANIMNEXTANIMGRAPH_API const FTrait * Find (FName TraitTypeName) const
ANIMNEXTANIMGRAPH_API const FTrait * Find (FTraitRegistryHandle TraitHandle) const
ANIMNEXTANIMGRAPH_API const FTrait * Find (FTraitUID TraitUID) const
ANIMNEXTANIMGRAPH_API FTraitRegistryHandle FindHandle (FTraitUID TraitUID) const
ANIMNEXTANIMGRAPH_API uint32 GetNum () const
ANIMNEXTANIMGRAPH_API TArray< const FTrait * > GetTraits () const
ANIMNEXTANIMGRAPH_API void Register (FTrait *Trait)
ANIMNEXTANIMGRAPH_API void Unregister (FTrait *Trait)
Static Public Member Functions
static ANIMNEXTANIMGRAPH_API FTraitRegistry & Get ()
Private Member Functions
FTraitRegistry ()=default
FTraitRegistry (const FTraitRegistry &)=delete
FTraitRegistry (FTraitRegistry &&)=default
ANIMNEXTANIMGRAPH_API void AutoRegisterImpl (TraitConstructorFunc TraitConstructor)
ANIMNEXTANIMGRAPH_API void AutoUnregisterImpl (TraitConstructorFunc TraitConstructor)
FTraitRegistry & operator= (const FTraitRegistry &)=delete
FTraitRegistry & operator= (FTraitRegistry &&)=default
Static Private Member Functions
static ANIMNEXTANIMGRAPH_API void Destroy ()
static ANIMNEXTANIMGRAPH_API void Init ()
static ANIMNEXTANIMGRAPH_API void StaticRegister (TraitConstructorFunc TraitConstructor)
static ANIMNEXTANIMGRAPH_API void StaticUnregister (TraitConstructorFunc TraitConstructor)
Private Attributes
int32 DynamicTraitFreeIndexHead = INDEX_NONE
TArray< uintptr_t > DynamicTraits
uint8 StaticTraitBuffer [STATIC_TRAIT_BUFFER_SIZE] = { 0 }
int32 StaticTraitBufferOffset = 0
TMap< FName, FTraitUIDRaw > TraitNameToUIDMap
TMap< FTraitUIDRaw, FRegistryEntry > TraitUIDToEntryMap
Static Private Attributes
static constexpr uint32 STATIC_TRAIT_BUFFER_SIZE = 8 * 1024
Friends
struct FTraitStaticInitHook
class UE::AnimNext::AnimGraph::FAnimNextAnimGraphModule
Detailed Description
FTraitRegistry.
A global registry of all existing traits that can be used in animation graphs.
See also
FTrait
Definition at line 26 of file TraitRegistry.h.
Constructor & Destructor Documentation
FTraitRegistry() [1/3]
UE::AnimNext::FTraitRegistry::FTraitRegistry () private default
Referenced by FTraitRegistry(), FTraitRegistry(), Get(), operator=(), and operator=().
FTraitRegistry() [2/3]
UE::AnimNext::FTraitRegistry::FTraitRegistry (const FTraitRegistry &) private delete
References FTraitRegistry().
FTraitRegistry() [3/3]
UE::AnimNext::FTraitRegistry::FTraitRegistry (FTraitRegistry &&) private default
References FTraitRegistry().
Member Function Documentation
AutoRegisterImpl()
ANIMNEXTANIMGRAPH_API void UE::AnimNext::FTraitRegistry::AutoRegisterImpl (TraitConstructorFunc TraitConstructor) private
References UE_API.
AutoUnregisterImpl()
ANIMNEXTANIMGRAPH_API void UE::AnimNext::FTraitRegistry::AutoUnregisterImpl (TraitConstructorFunc TraitConstructor) private
References UE_API.
Destroy()
ANIMNEXTANIMGRAPH_API void UE::AnimNext::FTraitRegistry::Destroy () static private
References UE_API.
Find() [1/4]
ANIMNEXTANIMGRAPH_API const FTrait * UE::AnimNext::FTraitRegistry::Find (const UScriptStruct * TraitSharedDataStruct) const
References UE_API.
Find() [2/4]
ANIMNEXTANIMGRAPH_API const FTrait * UE::AnimNext::FTraitRegistry::Find (FName TraitTypeName) const
References UE_API.
Find() [3/4]
ANIMNEXTANIMGRAPH_API const FTrait * UE::AnimNext::FTraitRegistry::Find (FTraitRegistryHandle TraitHandle) const
References UE_API.
Find() [4/4]
ANIMNEXTANIMGRAPH_API const FTrait * UE::AnimNext::FTraitRegistry::Find (FTraitUID TraitUID) const
References UE_API.
FindHandle()
ANIMNEXTANIMGRAPH_API FTraitRegistryHandle UE::AnimNext::FTraitRegistry::FindHandle (FTraitUID TraitUID) const
References UE_API.
Get()
ANIMNEXTANIMGRAPH_API FTraitRegistry & UE::AnimNext::FTraitRegistry::Get () static
References FTraitRegistry(), and UE_API.
GetNum()
ANIMNEXTANIMGRAPH_API uint32 UE::AnimNext::FTraitRegistry::GetNum () const
References UE_API.
GetTraits()
ANIMNEXTANIMGRAPH_API TArray< const FTrait * > UE::AnimNext::FTraitRegistry::GetTraits () const
References UE_API.
Init()
ANIMNEXTANIMGRAPH_API void UE::AnimNext::FTraitRegistry::Init () static private
References UE_API.
operator=() [1/2]
FTraitRegistry & UE::AnimNext::FTraitRegistry::operator= (const FTraitRegistry &) private delete
References FTraitRegistry().
operator=() [2/2]
FTraitRegistry & UE::AnimNext::FTraitRegistry::operator= (FTraitRegistry &&) private default
References FTraitRegistry().
Register()
ANIMNEXTANIMGRAPH_API void UE::AnimNext::FTraitRegistry::Register (FTrait * Trait)
References UE_API.
StaticRegister()
ANIMNEXTANIMGRAPH_API void UE::AnimNext::FTraitRegistry::StaticRegister (TraitConstructorFunc TraitConstructor) static private
References UE_API.
StaticUnregister()
ANIMNEXTANIMGRAPH_API void UE::AnimNext::FTraitRegistry::StaticUnregister (TraitConstructorFunc TraitConstructor) static private
References UE_API.
Unregister()
ANIMNEXTANIMGRAPH_API void UE::AnimNext::FTraitRegistry::Unregister (FTrait * Trait)
References UE_API.
Friends And Related Symbol Documentation
FTraitStaticInitHook
friend struct FTraitStaticInitHook friend
Definition at line 116 of file TraitRegistry.h.
References FTraitStaticInitHook.
Referenced by FTraitStaticInitHook.
UE::AnimNext::AnimGraph::FAnimNextAnimGraphModule
friend class UE::AnimNext::AnimGraph::FAnimNextAnimGraphModule friend
Definition at line 115 of file TraitRegistry.h.
References UE::AnimNext::AnimGraph::FAnimNextAnimGraphModule.
Referenced by UE::AnimNext::AnimGraph::FAnimNextAnimGraphModule.
Field Documentation
DynamicTraitFreeIndexHead
int32 UE::AnimNext::FTraitRegistry::DynamicTraitFreeIndexHead = INDEX_NONE private
Definition at line 110 of file TraitRegistry.h.
DynamicTraits
TArray<uintptr_t> UE::AnimNext::FTraitRegistry::DynamicTraits private
Definition at line 109 of file TraitRegistry.h.
STATIC_TRAIT_BUFFER_SIZE
uint32 UE::AnimNext::FTraitRegistry::STATIC_TRAIT_BUFFER_SIZE = 8 * 1024 static constexpr private
Definition at line 104 of file TraitRegistry.h.
StaticTraitBuffer
uint8 UE::AnimNext::FTraitRegistry::StaticTraitBuffer[STATIC_TRAIT_BUFFER_SIZE] = { 0 } private
Definition at line 106 of file TraitRegistry.h.
StaticTraitBufferOffset
int32 UE::AnimNext::FTraitRegistry::StaticTraitBufferOffset = 0 private
Definition at line 107 of file TraitRegistry.h.
TraitNameToUIDMap
TMap<FName, FTraitUIDRaw> UE::AnimNext::FTraitRegistry::TraitNameToUIDMap private
Definition at line 113 of file TraitRegistry.h.
TraitUIDToEntryMap
TMap<FTraitUIDRaw, FRegistryEntry> UE::AnimNext::FTraitRegistry::TraitUIDToEntryMap private
Definition at line 112 of file TraitRegistry.h.
The documentation for this struct was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Experimental/AnimNextAnimGraph/Source/AnimNextAnimGraph/Internal/TraitCore/TraitRegistry.h