Unreal Engine 5.6 C++ API: FLandscapeTextureDataInfo Struct Reference
FLandscapeTextureDataInfo Struct Reference
#include "LandscapeEdit.h"
Data Structures
struct FMipInfo
Public Member Functions
FLandscapeTextureDataInfo (UTexture2D *InTexture, bool bShouldDirtyPackage, ELandscapeTextureUsage TextureUsage=ELandscapeTextureUsage::Unknown, ELandscapeTextureType TextureType=ELandscapeTextureType::Unknown)
virtual ~FLandscapeTextureDataInfo ()
void AddMipUpdateRegion (int32 MipNum, int32 InX1, int32 InY1, int32 InX2, int32 InY2)
void * GetMipData (int32 MipNum)
int32 GetMipSizeX (int32 MipNum) const
int32 GetMipSizeY (int32 MipNum) const
int32 NumMips ()
bool UpdateTextureData ()
Private Attributes
TArray< FMipInfo > MipInfo
UTexture2D * Texture
ELandscapeTextureType TextureType = ELandscapeTextureType::Unknown
ELandscapeTextureUsage TextureUsage = ELandscapeTextureUsage::Unknown
Detailed Description
Definition at line 49 of file LandscapeEdit.h.
Constructor & Destructor Documentation
FLandscapeTextureDataInfo()
FLandscapeTextureDataInfo::FLandscapeTextureDataInfo (UTexture2D * InTexture, bool bShouldDirtyPackage, ELandscapeTextureUsage TextureUsage = ELandscapeTextureUsage::Unknown, ELandscapeTextureType TextureType = ELandscapeTextureType::Unknown)
References TextureType, and TextureUsage.
~FLandscapeTextureDataInfo()
virtual FLandscapeTextureDataInfo::~FLandscapeTextureDataInfo () virtual
Member Function Documentation
AddMipUpdateRegion()
void FLandscapeTextureDataInfo::AddMipUpdateRegion (int32 MipNum, int32 InX1, int32 InY1, int32 InX2, int32 InY2) inline
Definition at line 66 of file LandscapeEdit.h.
References check, GetMipSizeX(), GetMipSizeY(), MipInfo, and Width.
GetMipData()
void * FLandscapeTextureDataInfo::GetMipData (int32 MipNum) inline
Definition at line 89 of file LandscapeEdit.h.
References check, MipInfo, and Texture.
GetMipSizeX()
int32 FLandscapeTextureDataInfo::GetMipSizeX (int32 MipNum) const inline
Definition at line 104 of file LandscapeEdit.h.
References FMath::Max, and Texture.
Referenced by AddMipUpdateRegion().
GetMipSizeY()
int32 FLandscapeTextureDataInfo::GetMipSizeY (int32 MipNum) const inline
Definition at line 109 of file LandscapeEdit.h.
References FMath::Max, and Texture.
Referenced by AddMipUpdateRegion().
NumMips()
int32 FLandscapeTextureDataInfo::NumMips () inline
Definition at line 64 of file LandscapeEdit.h.
References MipInfo.
UpdateTextureData()
bool FLandscapeTextureDataInfo::UpdateTextureData ()
Field Documentation
MipInfo
TArray<FMipInfo> FLandscapeTextureDataInfo::MipInfo private
Definition at line 116 of file LandscapeEdit.h.
Referenced by AddMipUpdateRegion(), GetMipData(), and NumMips().
Texture
UTexture2D* FLandscapeTextureDataInfo::Texture private
Definition at line 115 of file LandscapeEdit.h.
Referenced by GetMipData(), GetMipSizeX(), and GetMipSizeY().
TextureType
ELandscapeTextureType FLandscapeTextureDataInfo::TextureType = ELandscapeTextureType::Unknown private
Definition at line 118 of file LandscapeEdit.h.
Referenced by FLandscapeTextureDataInfo().
TextureUsage
ELandscapeTextureUsage FLandscapeTextureDataInfo::TextureUsage = ELandscapeTextureUsage::Unknown private
Definition at line 117 of file LandscapeEdit.h.
Referenced by FLandscapeTextureDataInfo().
The documentation for this struct was generated from the following file:
Runtime/Landscape/Public/LandscapeEdit.h