Unreal Engine 5.6 C++ API: FBasePose< BoneIndexType, InAllocator > Struct Template Reference
FBasePose< BoneIndexType, InAllocator > Struct Template Reference
#include "BonePose.h"
Data Structures
struct FRangedForReverseSupport
struct FRangedForSupport
Public Member Functions
const TArray< FTransform, InAllocator > & GetBones () const
FORCEINLINE TArrayView< FTransform > GetMutableBones ()
FORCEINLINE int32 GetNumBones () const
FORCEINLINE void InitBones (int32 NumBones)
FORCEINLINE bool IsValidIndex (const BoneIndexType &BoneIndex) const
TArray< FTransform, InAllocator > && MoveBones ()
FORCEINLINE FTransform & operator[] (const BoneIndexType &BoneIndex)
FORCEINLINE const FTransform & operator[] (const BoneIndexType &BoneIndex) const
Protected Attributes
TArray< FTransform, InAllocator > Bones
Detailed Description
template<class BoneIndexType, typename InAllocator>
struct FBasePose< BoneIndexType, InAllocator >
Definition at line 44 of file BonePose.h.
Member Function Documentation
GetBones()
template<class BoneIndexType, typename InAllocator> const TArray< FTransform, InAllocator > & FBasePose< BoneIndexType, InAllocator >::GetBones () const inline
Definition at line 94 of file BonePose.h.
Referenced by FBaseCompactPose< InAllocator >::CopyBonesFrom(), and FBaseCompactPose< InAllocator >::CopyBonesFrom().
GetMutableBones()
template<class BoneIndexType, typename InAllocator> FORCEINLINE TArrayView< FTransform > FBasePose< BoneIndexType, InAllocator >::GetMutableBones () inline
Definition at line 66 of file BonePose.h.
GetNumBones()
template<class BoneIndexType, typename InAllocator> FORCEINLINE int32 FBasePose< BoneIndexType, InAllocator >::GetNumBones () const inline
Definition at line 49 of file BonePose.h.
InitBones()
template<class BoneIndexType, typename InAllocator> FORCEINLINE void FBasePose< BoneIndexType, InAllocator >::InitBones (int32 NumBones) inline
Definition at line 47 of file BonePose.h.
IsValidIndex()
template<class BoneIndexType, typename InAllocator> FORCEINLINE bool FBasePose< BoneIndexType, InAllocator >::IsValidIndex (const BoneIndexType & BoneIndex) const inline
Definition at line 51 of file BonePose.h.
MoveBones()
template<class BoneIndexType, typename InAllocator> TArray< FTransform, InAllocator > && FBasePose< BoneIndexType, InAllocator >::MoveBones () inline
Definition at line 96 of file BonePose.h.
Referenced by FBaseCompactPose< InAllocator >::MoveBonesFrom().
operator[]() [1/2]
template<class BoneIndexType, typename InAllocator> FORCEINLINE FTransform & FBasePose< BoneIndexType, InAllocator >::operator[] (const BoneIndexType & BoneIndex) inline
Definition at line 56 of file BonePose.h.
operator[]() [2/2]
template<class BoneIndexType, typename InAllocator> FORCEINLINE const FTransform & FBasePose< BoneIndexType, InAllocator >::operator[] (const BoneIndexType & BoneIndex) const inline
Definition at line 61 of file BonePose.h.
Field Documentation
Bones
template<class BoneIndexType, typename InAllocator> TArray<FTransform, InAllocator> FBasePose< BoneIndexType, InAllocator >::Bones protected
Definition at line 99 of file BonePose.h.
Referenced by FBaseCompactPose< InAllocator >::InitFrom().
The documentation for this struct was generated from the following file:
Runtime/Engine/Public/BonePose.h