Unreal Engine 5.6 C++ API: UE::MovieScene::TCustomPropertyRegistration< PropertyTraits, InlineSize > Struct Template Reference
UE::MovieScene::TCustomPropertyRegistration< PropertyTraits, InlineSize > Struct Template Reference
Generally static collection of accessors for a given type of property.
#include "MovieScenePropertySystemTypes.h"
Public Types
using GetterFunc = typename TCustomPropertyAccessorFunctions<PropertyTraits>::GetterFunc
using SetterFunc = typename TCustomPropertyAccessorFunctions<PropertyTraits>::SetterFunc
Public Member Functions
void Add (UClass *ClassType, FName PropertyName, GetterFunc Getter, SetterFunc Setter)
virtual FCustomAccessorView GetAccessors () const override
void Remove (UClass *ClassType, FName PropertyName)
void RemoveAll (UClass *ClassType)
Public Member Functions inherited from UE::MovieScene::ICustomPropertyRegistration
virtual ~ICustomPropertyRegistration ()
Protected Attributes
TArray< TCustomPropertyAccessor< PropertyTraits >, TInlineAllocator< InlineSize > > CustomAccessors
Detailed Description
template<typename PropertyTraits, int InlineSize = 8>
struct UE::MovieScene::TCustomPropertyRegistration< PropertyTraits, InlineSize >
Generally static collection of accessors for a given type of property.
Definition at line 230 of file MovieScenePropertySystemTypes.h.
Member Typedef Documentation
GetterFunc
template<typename PropertyTraits, int InlineSize = 8> using UE::MovieScene::TCustomPropertyRegistration< PropertyTraits, InlineSize >::GetterFunc = typename TCustomPropertyAccessorFunctions<PropertyTraits>::GetterFunc
Definition at line 232 of file MovieScenePropertySystemTypes.h.
SetterFunc
template<typename PropertyTraits, int InlineSize = 8> using UE::MovieScene::TCustomPropertyRegistration< PropertyTraits, InlineSize >::SetterFunc = typename TCustomPropertyAccessorFunctions<PropertyTraits>::SetterFunc
Definition at line 233 of file MovieScenePropertySystemTypes.h.
Member Function Documentation
Add()
template<typename PropertyTraits, int InlineSize = 8> void UE::MovieScene::TCustomPropertyRegistration< PropertyTraits, InlineSize >::Add (UClass * ClassType, FName PropertyName, GetterFunc Getter, SetterFunc Setter) inline
Definition at line 240 of file MovieScenePropertySystemTypes.h.
References UE::MovieScene::AddGlobalCustomAccessor(), CustomAccessors, and PropertyName.
Referenced by UE::MovieScene::FMovieSceneTracksComponentTypes::FObjectPropertyRegistration::Add(), and UE::MovieScene::FMovieSceneTracksComponentTypes::FObjectPropertyRegistration::Add().
GetAccessors()
template<typename PropertyTraits, int InlineSize = 8> virtual FCustomAccessorView UE::MovieScene::TCustomPropertyRegistration< PropertyTraits, InlineSize >::GetAccessors () const inline override virtual
Implements UE::MovieScene::ICustomPropertyRegistration.
Definition at line 235 of file MovieScenePropertySystemTypes.h.
References CustomAccessors.
Remove()
template<typename PropertyTraits, int InlineSize = 8> void UE::MovieScene::TCustomPropertyRegistration< PropertyTraits, InlineSize >::Remove (UClass * ClassType, FName PropertyName) inline
Definition at line 248 of file MovieScenePropertySystemTypes.h.
References UE::MovieScene::FCustomPropertyAccessor::Class, CustomAccessors, PropertyName, UE::MovieScene::FCustomPropertyAccessor::PropertyPath, and UE::MovieScene::RemoveGlobalCustomAccessor().
RemoveAll()
template<typename PropertyTraits, int InlineSize = 8> void UE::MovieScene::TCustomPropertyRegistration< PropertyTraits, InlineSize >::RemoveAll (UClass * ClassType) inline
Definition at line 265 of file MovieScenePropertySystemTypes.h.
References UE::MovieScene::FCustomPropertyAccessor::Class, CustomAccessors, UE::MovieScene::FCustomPropertyAccessor::PropertyPath, and UE::MovieScene::RemoveGlobalCustomAccessor().
Field Documentation
CustomAccessors
template<typename PropertyTraits, int InlineSize = 8> TArray<TCustomPropertyAccessor<PropertyTraits>, TInlineAllocator<InlineSize> > UE::MovieScene::TCustomPropertyRegistration< PropertyTraits, InlineSize >::CustomAccessors protected
Definition at line 285 of file MovieScenePropertySystemTypes.h.
Referenced by Add(), GetAccessors(), Remove(), and RemoveAll().
The documentation for this struct was generated from the following file:
Runtime/MovieScene/Public/EntitySystem/MovieScenePropertySystemTypes.h