Unreal Engine 5.6 C++ API: FCollisionQueryFlag Struct Reference
FCollisionQueryFlag Struct Reference
#include "CollisionQueryParams.h"
Public Member Functions
void AddToAllObjectsQueryFlag (ECollisionChannel NewChannel)
void AddToAllStaticObjectsQueryFlag (ECollisionChannel NewChannel)
int32 GetAllDynamicObjectsQueryFlag ()
int32 GetAllObjectsQueryFlag ()
int32 GetAllStaticObjectsQueryFlag ()
void RemoveFromAllObjectsQueryFlag (ECollisionChannel NewChannel)
void RemoveFromAllStaticObjectsQueryFlag (ECollisionChannel NewChannel)
void SetAllDynamicObjectsQueryFlag (int32 NewQueryFlag)
void SetAllObjectsQueryFlag (int32 NewQueryFlag)
void SetAllStaticObjectsQueryFlag (int32 NewQueryFlag)
Static Public Member Functions
static FCollisionQueryFlag & Get ()
Private Member Functions
FCollisionQueryFlag ()
Private Attributes
int32 AllObjectQueryFlag
int32 AllStaticObjectQueryFlag
Detailed Description
Definition at line 347 of file CollisionQueryParams.h.
Constructor & Destructor Documentation
FCollisionQueryFlag()
FCollisionQueryFlag::FCollisionQueryFlag () inline private
Definition at line 353 of file CollisionQueryParams.h.
References AllObjectQueryFlag, AllStaticObjectQueryFlag, and ECC_TO_BITFIELD.
Referenced by Get().
Member Function Documentation
AddToAllObjectsQueryFlag()
void FCollisionQueryFlag::AddToAllObjectsQueryFlag (ECollisionChannel NewChannel) inline
Definition at line 378 of file CollisionQueryParams.h.
References AllObjectQueryFlag, ECC_TO_BITFIELD, ensure, and SetAllObjectsQueryFlag().
AddToAllStaticObjectsQueryFlag()
void FCollisionQueryFlag::AddToAllStaticObjectsQueryFlag (ECollisionChannel NewChannel) inline
Definition at line 386 of file CollisionQueryParams.h.
References AllStaticObjectQueryFlag, ECC_TO_BITFIELD, ensure, and SetAllStaticObjectsQueryFlag().
Get()
FCollisionQueryFlag & FCollisionQueryFlag::Get () static
References FCollisionQueryFlag().
Referenced by FCollisionObjectQueryParams::FCollisionObjectQueryParams(), FCollisionObjectQueryParams::DoVerify(), and FCollisionObjectQueryParams::IsValidObjectQuery().
GetAllDynamicObjectsQueryFlag()
int32 FCollisionQueryFlag::GetAllDynamicObjectsQueryFlag () inline
Definition at line 373 of file CollisionQueryParams.h.
References AllObjectQueryFlag, and AllStaticObjectQueryFlag.
Referenced by FCollisionObjectQueryParams::FCollisionObjectQueryParams().
GetAllObjectsQueryFlag()
int32 FCollisionQueryFlag::GetAllObjectsQueryFlag () inline
Definition at line 362 of file CollisionQueryParams.h.
References AllObjectQueryFlag.
Referenced by FCollisionObjectQueryParams::FCollisionObjectQueryParams().
GetAllStaticObjectsQueryFlag()
int32 FCollisionQueryFlag::GetAllStaticObjectsQueryFlag () inline
Definition at line 368 of file CollisionQueryParams.h.
References AllStaticObjectQueryFlag.
Referenced by FCollisionObjectQueryParams::FCollisionObjectQueryParams().
RemoveFromAllObjectsQueryFlag()
void FCollisionQueryFlag::RemoveFromAllObjectsQueryFlag (ECollisionChannel NewChannel) inline
Definition at line 394 of file CollisionQueryParams.h.
References AllObjectQueryFlag, ECC_TO_BITFIELD, ensure, and SetAllObjectsQueryFlag().
RemoveFromAllStaticObjectsQueryFlag()
void FCollisionQueryFlag::RemoveFromAllStaticObjectsQueryFlag (ECollisionChannel NewChannel) inline
Definition at line 402 of file CollisionQueryParams.h.
References AllObjectQueryFlag, ECC_TO_BITFIELD, ensure, and SetAllStaticObjectsQueryFlag().
SetAllDynamicObjectsQueryFlag()
void FCollisionQueryFlag::SetAllDynamicObjectsQueryFlag (int32 NewQueryFlag) inline
Definition at line 422 of file CollisionQueryParams.h.
References AllObjectQueryFlag, and AllStaticObjectQueryFlag.
SetAllObjectsQueryFlag()
void FCollisionQueryFlag::SetAllObjectsQueryFlag (int32 NewQueryFlag) inline
Definition at line 410 of file CollisionQueryParams.h.
References AllObjectQueryFlag, and AllStaticObjectQueryFlag.
Referenced by AddToAllObjectsQueryFlag(), and RemoveFromAllObjectsQueryFlag().
SetAllStaticObjectsQueryFlag()
void FCollisionQueryFlag::SetAllStaticObjectsQueryFlag (int32 NewQueryFlag) inline
Definition at line 417 of file CollisionQueryParams.h.
References AllStaticObjectQueryFlag.
Referenced by AddToAllStaticObjectsQueryFlag(), and RemoveFromAllStaticObjectsQueryFlag().
Field Documentation
AllObjectQueryFlag
int32 FCollisionQueryFlag::AllObjectQueryFlag private
Definition at line 350 of file CollisionQueryParams.h.
Referenced by FCollisionQueryFlag(), AddToAllObjectsQueryFlag(), GetAllDynamicObjectsQueryFlag(), GetAllObjectsQueryFlag(), RemoveFromAllObjectsQueryFlag(), RemoveFromAllStaticObjectsQueryFlag(), SetAllDynamicObjectsQueryFlag(), and SetAllObjectsQueryFlag().
AllStaticObjectQueryFlag
int32 FCollisionQueryFlag::AllStaticObjectQueryFlag private
Definition at line 351 of file CollisionQueryParams.h.
Referenced by FCollisionQueryFlag(), AddToAllStaticObjectsQueryFlag(), GetAllDynamicObjectsQueryFlag(), GetAllStaticObjectsQueryFlag(), SetAllDynamicObjectsQueryFlag(), SetAllObjectsQueryFlag(), and SetAllStaticObjectsQueryFlag().
The documentation for this struct was generated from the following file:
Runtime/Engine/Public/CollisionQueryParams.h