Unreal Engine 5.6 C++ API: FNameEntry Struct Reference
FNameEntry Struct Reference
A global deduplicated name stored in the global name table.
#include "NameTypes.h"
Data Structures
struct FNumberedData
Public Member Functions
void AppendAnsiNameToString (FAnsiStringBuilderBase &OutString) const
Appends name to string builder.
void AppendNameToPathString (FString &OutString) const
Appends name to string with path separator using FString::PathAppend().
void AppendNameToString (FUtf8String &OutString) const
void AppendNameToString (FUtf8StringBuilderBase &OutString) const
void AppendNameToString (FWideString &OutString) const
Appends name to string.
void AppendNameToString (FWideStringBuilderBase &OutString) const
Appends name to string builder.
void DebugDump (FOutputDevice &Out) const
void GetAnsiName (ANSICHAR(&OutName)[NAME_SIZE]) const
Copy null-terminated name to ANSICHAR buffer without allocating.
void GetName (TCHAR(&OutName)[NAME_SIZE]) const
Copy null-terminated name to TCHAR buffer without allocating.
FORCEINLINE int32 GetNameLength () const
int32 GetNameLengthUtf8 () const
FString GetPlainNameString () const
Copy name to a dynamically allocated FString.
FUtf8String GetPlainNameUtf8String () const
Copy name to a dynamically allocated FString.
int32 GetSizeInBytes () const
void GetUnterminatedName (TCHAR *OutName, uint32 OutSize) const
Copy unterminated name to TCHAR buffer without allocating.
void GetWideName (WIDECHAR(&OutName)[NAME_SIZE]) const
Copy null-terminated name to WIDECHAR buffer without allocating.
FORCEINLINE bool IsNumbered () const
FORCEINLINE bool IsWide () const
Returns whether this name entry is represented via WIDECHAR or ANSICHAR.
struct FNameStringView MakeView (union FNameBuffer &OptionalDecodeBuffer) const
void Write (FArchive &Ar) const
Static Public Member Functions
static constexpr int32 GetDataOffset ()
Private Member Functions
FNameEntry (const FNameEntry &)=delete
FNameEntry (FClangKeepDebugInfo)
FNameEntry (FNameEntry &&)=delete
void CopyAndConvertUnterminatedName (TCHAR *OutName, uint32 Len) const
void CopyUnterminatedName (ANSICHAR *OutName, uint32 Len) const
void CopyUnterminatedName (WIDECHAR *OutName, uint32 Len) const
const ANSICHAR * GetUnterminatedName (ANSICHAR(&OptionalDecodeBuffer)[NAME_SIZE]) const
const WIDECHAR * GetUnterminatedName (WIDECHAR(&OptionalDecodeBuffer)[NAME_SIZE]) const
FNameEntry & operator= (const FNameEntry &)=delete
FNameEntry & operator= (FNameEntry &&)=delete
Private Attributes
union {
ANSICHAR AnsiName [NAME_SIZE]
uint8 NameData [0]
FNumberedData NumberedName
WIDECHAR WideName [NAME_SIZE]
};
FNameEntryHeader Header
Friends
class FName
class FNameEntryAllocator
struct FNameHelper
class FNamePool
class FNamePoolShardBase
Detailed Description
A global deduplicated name stored in the global name table.
Definition at line 227 of file NameTypes.h.
Constructor & Destructor Documentation
FNameEntry() [1/3]
FNameEntry::FNameEntry (FClangKeepDebugInfo) private
Referenced by FNameEntry(), FNameEntry(), GetDataOffset(), operator=(), and operator=().
FNameEntry() [2/3]
FNameEntry::FNameEntry (const FNameEntry &) private delete
References FNameEntry().
FNameEntry() [3/3]
FNameEntry::FNameEntry (FNameEntry &&) private delete
References FNameEntry().
Member Function Documentation
AppendAnsiNameToString()
void FNameEntry::AppendAnsiNameToString (FAnsiStringBuilderBase & OutString) const
Appends name to string builder.
Entry must not be wide.
AppendNameToPathString()
void FNameEntry::AppendNameToPathString (FString & OutString) const
Appends name to string with path separator using FString::PathAppend().
AppendNameToString() [1/4]
void FNameEntry::AppendNameToString (FUtf8String & OutString) const
AppendNameToString() [2/4]
void FNameEntry::AppendNameToString (FUtf8StringBuilderBase & OutString) const
AppendNameToString() [3/4]
void FNameEntry::AppendNameToString (FWideString & OutString) const
Appends name to string.
May allocate.
AppendNameToString() [4/4]
void FNameEntry::AppendNameToString (FWideStringBuilderBase & OutString) const
Appends name to string builder.
CopyAndConvertUnterminatedName()
void FNameEntry::CopyAndConvertUnterminatedName (TCHAR * OutName, uint32 Len) const private
CopyUnterminatedName() [1/2]
void FNameEntry::CopyUnterminatedName (ANSICHAR * OutName, uint32 Len) const private
CopyUnterminatedName() [2/2]
void FNameEntry::CopyUnterminatedName (WIDECHAR * OutName, uint32 Len) const private
DebugDump()
void FNameEntry::DebugDump (FOutputDevice & Out) const
GetAnsiName()
void FNameEntry::GetAnsiName (ANSICHAR(&) OutName[NAME_SIZE]) const
Copy null-terminated name to ANSICHAR buffer without allocating.
Entry must not be wide.
References NAME_SIZE.
Referenced by TextFilterUtils::FNameBufferWithNumber::Init().
GetDataOffset()
constexpr int32 FNameEntry::GetDataOffset () inline static constexpr
Definition at line 311 of file NameTypes.h.
References FNameEntry(), and NameData.
GetName()
void FNameEntry::GetName (TCHAR(&) OutName[NAME_SIZE]) const
Copy null-terminated name to TCHAR buffer without allocating.
References NAME_SIZE.
GetNameLength()
FORCEINLINE int32 FNameEntry::GetNameLength () const inline
Definition at line 265 of file NameTypes.h.
References FORCEINLINE, and Header.
GetNameLengthUtf8()
int32 FNameEntry::GetNameLengthUtf8 () const
References FORCEINLINE, and Header.
GetPlainNameString()
FString FNameEntry::GetPlainNameString () const
Copy name to a dynamically allocated FString.
GetPlainNameUtf8String()
FUtf8String FNameEntry::GetPlainNameUtf8String () const
Copy name to a dynamically allocated FString.
GetSizeInBytes()
int32 FNameEntry::GetSizeInBytes () const
GetUnterminatedName() [1/3]
const ANSICHAR * FNameEntry::GetUnterminatedName (ANSICHAR(&) OptionalDecodeBuffer[NAME_SIZE]) const private
References NAME_SIZE.
GetUnterminatedName() [2/3]
void FNameEntry::GetUnterminatedName (TCHAR * OutName, uint32 OutSize) const
Copy unterminated name to TCHAR buffer without allocating.
GetUnterminatedName() [3/3]
const WIDECHAR * FNameEntry::GetUnterminatedName (WIDECHAR(&) OptionalDecodeBuffer[NAME_SIZE]) const private
References FORCEINLINE, NAME_SIZE, and NumberedName.
GetWideName()
void FNameEntry::GetWideName (WIDECHAR(&) OutName[NAME_SIZE]) const
Copy null-terminated name to WIDECHAR buffer without allocating.
Entry must be wide.
References NAME_SIZE.
Referenced by TextFilterUtils::FNameBufferWithNumber::Init().
IsNumbered()
FORCEINLINE bool FNameEntry::IsNumbered () const inline
Definition at line 270 of file NameTypes.h.
References FORCEINLINE.
IsWide()
FORCEINLINE bool FNameEntry::IsWide () const inline
Returns whether this name entry is represented via WIDECHAR or ANSICHAR.
Definition at line 264 of file NameTypes.h.
References FORCEINLINE, and Header.
Referenced by TextFilterUtils::FNameBufferWithNumber::Init().
MakeView()
struct FNameStringView FNameEntry::MakeView (union FNameBuffer & OptionalDecodeBuffer) const
References MakeView().
Referenced by MakeView().
operator=() [1/2]
FNameEntry & FNameEntry::operator= (const FNameEntry &) private delete
References FNameEntry().
operator=() [2/2]
FNameEntry & FNameEntry::operator= (FNameEntry &&) private delete
References FNameEntry().
Write()
void FNameEntry::Write (FArchive & Ar) const
References Ar.
Friends And Related Symbol Documentation
FName
friend class FName friend
Definition at line 314 of file NameTypes.h.
References FName.
Referenced by FName.
FNameEntryAllocator
friend class FNameEntryAllocator friend
Definition at line 316 of file NameTypes.h.
References FNameEntryAllocator.
Referenced by FNameEntryAllocator.
FNameHelper
friend struct FNameHelper friend
Definition at line 315 of file NameTypes.h.
References FNameHelper.
Referenced by FNameHelper.
FNamePool
friend class FNamePool friend
Definition at line 318 of file NameTypes.h.
References FNamePool.
Referenced by FNamePool.
FNamePoolShardBase
friend class FNamePoolShardBase friend
Definition at line 317 of file NameTypes.h.
References FNamePoolShardBase.
Referenced by FNamePoolShardBase.
Field Documentation
[union]
union { ... } FNameEntry
AnsiName
ANSICHAR FNameEntry::AnsiName[NAME_SIZE]
Definition at line 249 of file NameTypes.h.
Header
FNameEntryHeader FNameEntry::Header private
Definition at line 233 of file NameTypes.h.
Referenced by GetNameLength(), GetNameLengthUtf8(), and IsWide().
NameData
uint8 FNameEntry::NameData[0]
Definition at line 251 of file NameTypes.h.
Referenced by GetDataOffset().
NumberedName
FNumberedData FNameEntry::NumberedName
Definition at line 252 of file NameTypes.h.
Referenced by GetUnterminatedName().
WideName
WIDECHAR FNameEntry::WideName[NAME_SIZE]
Definition at line 250 of file NameTypes.h.
The documentation for this struct was generated from the following file:
Runtime/Core/Public/UObject/NameTypes.h