Unreal Engine 5.6 C++ API: FPackedRGBA16N Struct Reference
FPackedRGBA16N Struct Reference
A vector, quantized and packed into 32-bits.
#include "PackedNormal.h"
Public Member Functions
FPackedRGBA16N ()
FPackedRGBA16N (const FVector3d &InVector)
FPackedRGBA16N (const FVector3f &InVector)
FPackedRGBA16N (const FVector4f &InVector)
VectorRegister4Float GetVectorRegister () const
bool operator!= (const FPackedRGBA16N &B) const
void operator= (const FVector3d &InVector)
void operator= (const FVector3f &InVector)
void operator= (const FVector4d &InVector)
void operator= (const FVector4f &InVector)
bool operator== (const FPackedRGBA16N &B) const
void Set (const FVector3d &InVector)
void Set (const FVector3f &InVector)
void Set (const FVector4f &InVector)
FVector ToFVector () const
FVector3f ToFVector3f () const
FVector4 ToFVector4 () const
FVector4f ToFVector4f () const
FString ToString () const
Data Fields
struct {
int16 W
int16 X
int16 Y
int16 Z
};
Friends
RENDERCORE_API FArchive & operator<< (FArchive &Ar, FPackedRGBA16N &N)
Detailed Description
A vector, quantized and packed into 32-bits.
Definition at line 308 of file PackedNormal.h.
Constructor & Destructor Documentation
FPackedRGBA16N() [1/4]
FPackedRGBA16N::FPackedRGBA16N () inline
Definition at line 320 of file PackedNormal.h.
References W, X, Y, and Z.
Referenced by operator!=(), operator<<, and operator==().
FPackedRGBA16N() [2/4]
FPackedRGBA16N::FPackedRGBA16N (const FVector3d & InVector) inline
Definition at line 321 of file PackedNormal.h.
FPackedRGBA16N() [3/4]
FPackedRGBA16N::FPackedRGBA16N (const FVector3f & InVector) inline
Definition at line 322 of file PackedNormal.h.
FPackedRGBA16N() [4/4]
FPackedRGBA16N::FPackedRGBA16N (const FVector4f & InVector) inline
Definition at line 323 of file PackedNormal.h.
Member Function Documentation
GetVectorRegister()
FORCEINLINE VectorRegister4Float FPackedRGBA16N::GetVectorRegister () const
Definition at line 436 of file PackedNormal.h.
References FORCEINLINE, VectorLoadSRGBA16N(), VectorMultiply(), and VectorSetFloat1().
Referenced by ToFVector3f(), and ToFVector4f().
operator!=()
FORCEINLINE bool FPackedRGBA16N::operator!= (const FPackedRGBA16N & B) const
Definition at line 401 of file PackedNormal.h.
References FPackedRGBA16N(), B, and FORCEINLINE.
operator=() [1/4]
FORCEINLINE void FPackedRGBA16N::operator= (const FVector3d & InVector)
Definition at line 369 of file PackedNormal.h.
References FMath::Clamp(), FORCEINLINE, MAX_int16, MIN_int16, Scale, W, X, UE::Math::TVector< T >::X, Y, UE::Math::TVector< T >::Y, Z, and UE::Math::TVector< T >::Z.
operator=() [2/4]
FORCEINLINE void FPackedRGBA16N::operator= (const FVector3f & InVector)
Definition at line 360 of file PackedNormal.h.
References FMath::Clamp(), FORCEINLINE, MAX_int16, MIN_int16, Scale, W, X, UE::Math::TVector< T >::X, Y, UE::Math::TVector< T >::Y, Z, and UE::Math::TVector< T >::Z.
operator=() [3/4]
FORCEINLINE void FPackedRGBA16N::operator= (const FVector4d & InVector)
Definition at line 387 of file PackedNormal.h.
References FMath::Clamp(), FORCEINLINE, MAX_int16, MIN_int16, Scale, W, UE::Math::TVector4< T >::W, X, UE::Math::TVector4< T >::X, Y, UE::Math::TVector4< T >::Y, Z, and UE::Math::TVector4< T >::Z.
operator=() [4/4]
FORCEINLINE void FPackedRGBA16N::operator= (const FVector4f & InVector)
Definition at line 378 of file PackedNormal.h.
References FMath::Clamp(), FORCEINLINE, MAX_int16, MIN_int16, Scale, W, UE::Math::TVector4< T >::W, X, UE::Math::TVector4< T >::X, Y, UE::Math::TVector4< T >::Y, Z, and UE::Math::TVector4< T >::Z.
operator==()
FORCEINLINE bool FPackedRGBA16N::operator== (const FPackedRGBA16N & B) const
Definition at line 396 of file PackedNormal.h.
References FPackedRGBA16N(), B, FORCEINLINE, W, X, Y, and Z.
Set() [1/3]
void FPackedRGBA16N::Set (const FVector3d & InVector) inline
Definition at line 341 of file PackedNormal.h.
Set() [2/3]
void FPackedRGBA16N::Set (const FVector3f & InVector) inline
Definition at line 342 of file PackedNormal.h.
Set() [3/3]
void FPackedRGBA16N::Set (const FVector4f & InVector) inline
Definition at line 343 of file PackedNormal.h.
ToFVector()
FORCEINLINE FVector FPackedRGBA16N::ToFVector () const
Definition at line 406 of file PackedNormal.h.
References FORCEINLINE, FVector, and ToFVector3f().
ToFVector3f()
FORCEINLINE FVector3f FPackedRGBA16N::ToFVector3f () const
Definition at line 412 of file PackedNormal.h.
References FORCEINLINE, GetVectorRegister(), and VectorStoreFloat3().
Referenced by ToFVector().
ToFVector4()
FORCEINLINE FVector4 FPackedRGBA16N::ToFVector4 () const
Definition at line 421 of file PackedNormal.h.
References FORCEINLINE, and ToFVector4f().
ToFVector4f()
FORCEINLINE FVector4f FPackedRGBA16N::ToFVector4f () const
Definition at line 427 of file PackedNormal.h.
References FORCEINLINE, GetVectorRegister(), and VectorStore().
Referenced by ToFVector4().
ToString()
FString FPackedRGBA16N::ToString () const inline
Definition at line 350 of file PackedNormal.h.
References TEXT, W, X, Y, and Z.
Friends And Related Symbol Documentation
operator<<
RENDERCORE_API FArchive & operator<< (FArchive & Ar, FPackedRGBA16N & N) friend
References FPackedRGBA16N(), and Ar.
Field Documentation
[struct]
struct { ... } FPackedRGBA16N
W
int16 FPackedRGBA16N::W
Definition at line 315 of file PackedNormal.h.
Referenced by FPackedRGBA16N(), operator=(), operator=(), operator=(), operator=(), operator==(), and ToString().
X
int16 FPackedRGBA16N::X
Definition at line 312 of file PackedNormal.h.
Referenced by FPackedRGBA16N(), operator=(), operator=(), operator=(), operator=(), operator==(), and ToString().
Y
int16 FPackedRGBA16N::Y
Definition at line 313 of file PackedNormal.h.
Referenced by FPackedRGBA16N(), operator=(), operator=(), operator=(), operator=(), operator==(), and ToString().
Z
int16 FPackedRGBA16N::Z
Definition at line 314 of file PackedNormal.h.
Referenced by FPackedRGBA16N(), operator=(), operator=(), operator=(), operator=(), operator==(), and ToString().
The documentation for this struct was generated from the following file:
Runtime/RenderCore/Public/PackedNormal.h