Unreal Engine 5.6 C++ API: FGameplayTagCountContainer Struct Reference
FGameplayTagCountContainer Struct Reference
Struct that tracks the number/count of tag applications within it.
#include "GameplayEffectTypes.h"
Data Structures
struct FDelegateInfo
Public Member Functions
FGameplayTagCountContainer ()
void FillParentTags ()
Fills in ParentTags from GameplayTags.
const FGameplayTagContainer & GetExplicitGameplayTags () const
Simple accessor to the explicit gameplay tag list.
FORCEINLINE int32 GetExplicitTagCount (const FGameplayTag &Tag) const
return how many times the exact specified tag has been added to the container (ignores the tag hierarchy) e.g.
FORCEINLINE int32 GetTagCount (const FGameplayTag &Tag) const
return the hierarchical count for a specified tag e.g.
FORCEINLINE bool HasAllMatchingGameplayTags (const FGameplayTagContainer &TagContainer) const
Check if the count container has gameplay tags that matches against all of the specified tags (expands to include parents of asset tags)
FORCEINLINE bool HasAnyMatchingGameplayTags (const FGameplayTagContainer &TagContainer) const
Check if the count container has gameplay tags that matches against any of the specified tags (expands to include parents of asset tags)
FORCEINLINE bool HasMatchingGameplayTag (FGameplayTag TagToCheck) const
Check if the count container has a gameplay tag that matches against the specified tag (expands to include parents of asset tags)
GAMEPLAYABILITIES_API void Notify_StackCountChange (const FGameplayTag &Tag)
Broadcasts the AnyChange event for this tag.
GAMEPLAYABILITIES_API FOnGameplayEffectTagCountChanged & RegisterGameplayTagEvent (const FGameplayTag &Tag, EGameplayTagEventType::Type EventType=EGameplayTagEventType::NewOrRemoved)
Return delegate that can be bound to for when the specific tag's count changes to or off of zero.
FOnGameplayEffectTagCountChanged & RegisterGenericGameplayEvent ()
Return delegate that can be bound to for when the any tag's count changes to or off of zero.
GAMEPLAYABILITIES_API void Reset (bool bResetCallbacks=true)
Removes all of the tags.
FORCEINLINE bool SetTagCount (const FGameplayTag &Tag, int32 NewCount)
Set the specified tag count to a specific value.
FORCEINLINE bool UpdateTagCount (const FGameplayTag &Tag, int32 CountDelta)
Update the specified tag by the specified delta, potentially causing an additional or removal from the explicit tag list.
FORCEINLINE void UpdateTagCount (const FGameplayTagContainer &Container, int32 CountDelta)
Update the specified container of tags by the specified delta, potentially causing an additional or removal from the explicit tag list.
FORCEINLINE bool UpdateTagCount_DeferredParentRemoval (const FGameplayTag &Tag, int32 CountDelta, TArray< FDeferredTagChangeDelegate > &DeferredTagChangeDelegates)
Update the specified tag by the specified delta, potentially causing an additional or removal from the explicit tag list.
Private Member Functions
GAMEPLAYABILITIES_API bool GatherTagChangeDelegates (const FGameplayTag &Tag, int32 CountDelta, TArray< FDeferredTagChangeDelegate > &TagChangeDelegates)
Internal helper function to collect the delegates that need to be called when Tag has its count changed by CountDelta.
GAMEPLAYABILITIES_API bool UpdateExplicitTags (const FGameplayTag &Tag, int32 CountDelta, bool bDeferParentTagsOnRemove)
Internal helper function to adjust the explicit tag list & corresponding map.
GAMEPLAYABILITIES_API bool UpdateTagMap_Internal (const FGameplayTag &Tag, int32 CountDelta)
Internal helper function to adjust the explicit tag list & corresponding maps/delegates/etc.
GAMEPLAYABILITIES_API bool UpdateTagMapDeferredParentRemoval_Internal (const FGameplayTag &Tag, int32 CountDelta, TArray< FDeferredTagChangeDelegate > &DeferredTagChangeDelegates)
Internal helper function to adjust the explicit tag list & corresponding maps/delegates/etc.
Private Attributes
TMap< FGameplayTag, int32 > ExplicitTagCountMap
Map of tag to explicit count of that tag.
FGameplayTagContainer ExplicitTags
Container of tags that were explicitly added.
TMap< FGameplayTag, int32 > GameplayTagCountMap
Map of tag to active count of that tag.
TMap< FGameplayTag, FDelegateInfo > GameplayTagEventMap
Map of tag to delegate that will be fired when the count for the key tag changes to or away from zero.
FOnGameplayEffectTagCountChanged OnAnyTagChangeDelegate
Delegate fired whenever any tag's count changes to or away from zero.
Detailed Description
Struct that tracks the number/count of tag applications within it.
Explicitly tracks the tags added or removed, while simultaneously tracking the count of parent tags as well. Events/delegates are fired whenever the tag counts of any tag (explicit or parent) are modified.
Definition at line 1043 of file GameplayEffectTypes.h.
Constructor & Destructor Documentation
FGameplayTagCountContainer()
FGameplayTagCountContainer::FGameplayTagCountContainer () inline
Definition at line 1045 of file GameplayEffectTypes.h.
Member Function Documentation
FillParentTags()
void FGameplayTagCountContainer::FillParentTags () inline
Fills in ParentTags from GameplayTags.
Definition at line 1285 of file GameplayEffectTypes.h.
References ExplicitTags.
GatherTagChangeDelegates()
GAMEPLAYABILITIES_API bool FGameplayTagCountContainer::GatherTagChangeDelegates (const FGameplayTag & Tag, int32 CountDelta, TArray< FDeferredTagChangeDelegate > & TagChangeDelegates) private
Internal helper function to collect the delegates that need to be called when Tag has its count changed by CountDelta.
References UE_API.
GetExplicitGameplayTags()
const FGameplayTagContainer & FGameplayTagCountContainer::GetExplicitGameplayTags () const inline
Simple accessor to the explicit gameplay tag list.
Definition at line 1272 of file GameplayEffectTypes.h.
References ExplicitTags.
GetExplicitTagCount()
FORCEINLINE int32 FGameplayTagCountContainer::GetExplicitTagCount (const FGameplayTag & Tag) const inline
return how many times the exact specified tag has been added to the container (ignores the tag hierarchy) e.g.
if A.B & A.C were added, GetExplicitTagCount("A") would return 0, and GetExplicitTagCount("A.B") would return 1.
Parameters
Tag Tag to update
Returns
the count of the passed in tag
Definition at line 1236 of file GameplayEffectTypes.h.
References ExplicitTagCountMap, and FORCEINLINE.
GetTagCount()
FORCEINLINE int32 FGameplayTagCountContainer::GetTagCount (const FGameplayTag & Tag) const inline
return the hierarchical count for a specified tag e.g.
if A.B & A.C were added, GetTagCount("A") would return 2.
Parameters
Tag Tag to update
Returns
the count of the passed in tag
Definition at line 1218 of file GameplayEffectTypes.h.
References FORCEINLINE, and GameplayTagCountMap.
HasAllMatchingGameplayTags()
FORCEINLINE bool FGameplayTagCountContainer::HasAllMatchingGameplayTags (const FGameplayTagContainer & TagContainer) const inline
Check if the count container has gameplay tags that matches against all of the specified tags (expands to include parents of asset tags)
Parameters
TagContainer Tag container to check for a match. If empty will return true
Returns
True if the count container matches all of the gameplay tags
Definition at line 1067 of file GameplayEffectTypes.h.
References FORCEINLINE, and GameplayTagCountMap.
HasAnyMatchingGameplayTags()
FORCEINLINE bool FGameplayTagCountContainer::HasAnyMatchingGameplayTags (const FGameplayTagContainer & TagContainer) const inline
Check if the count container has gameplay tags that matches against any of the specified tags (expands to include parents of asset tags)
Parameters
TagContainer Tag container to check for a match. If empty will return false
Returns
True if the count container matches any of the gameplay tags
Definition at line 1094 of file GameplayEffectTypes.h.
References FORCEINLINE, and GameplayTagCountMap.
HasMatchingGameplayTag()
FORCEINLINE bool FGameplayTagCountContainer::HasMatchingGameplayTag (FGameplayTag TagToCheck) const inline
Check if the count container has a gameplay tag that matches against the specified tag (expands to include parents of asset tags)
Parameters
TagToCheck Tag to check for a match
Returns
True if the count container has a gameplay tag that matches, false if not
Definition at line 1055 of file GameplayEffectTypes.h.
References FORCEINLINE, and GameplayTagCountMap.
Notify_StackCountChange()
GAMEPLAYABILITIES_API void FGameplayTagCountContainer::Notify_StackCountChange (const FGameplayTag & Tag)
Broadcasts the AnyChange event for this tag.
This is called when the stack count of the backing gameplay effect change. It is up to the receiver of the broadcasted delegate to decide what to do with this.
References UE_API.
RegisterGameplayTagEvent()
GAMEPLAYABILITIES_API FOnGameplayEffectTagCountChanged & FGameplayTagCountContainer::RegisterGameplayTagEvent (const FGameplayTag & Tag, EGameplayTagEventType::Type EventType = EGameplayTagEventType::NewOrRemoved)
Return delegate that can be bound to for when the specific tag's count changes to or off of zero.
Parameters
Tag Tag to get a delegate for
Returns
Delegate for when the specified tag's count changes to or off of zero
References UE_API.
RegisterGenericGameplayEvent()
FOnGameplayEffectTagCountChanged & FGameplayTagCountContainer::RegisterGenericGameplayEvent () inline
Return delegate that can be bound to for when the any tag's count changes to or off of zero.
Returns
Delegate for when any tag's count changes to or off of zero
Definition at line 1266 of file GameplayEffectTypes.h.
References OnAnyTagChangeDelegate.
Reset()
GAMEPLAYABILITIES_API void FGameplayTagCountContainer::Reset (bool bResetCallbacks = true)
Removes all of the tags.
Does not notify any delegates.
Parameters
bResetCallbacks If true, also remove all of the registered tag count change delegates
References UE_API.
SetTagCount()
FORCEINLINE bool FGameplayTagCountContainer::SetTagCount (const FGameplayTag & Tag, int32 NewCount) inline
Set the specified tag count to a specific value.
Parameters
Tag Tag to update
Count New count of the tag
Returns
True if tag was either added or removed. (E.g., we had the tag and now dont. or didnt have the tag and now we do. We didn't just change the count (1 count -> 2 count would return false).
Definition at line 1188 of file GameplayEffectTypes.h.
References ExplicitTagCountMap, FORCEINLINE, and UpdateTagMap_Internal().
UpdateExplicitTags()
GAMEPLAYABILITIES_API bool FGameplayTagCountContainer::UpdateExplicitTags (const FGameplayTag & Tag, int32 CountDelta, bool bDeferParentTagsOnRemove) private
Internal helper function to adjust the explicit tag list & corresponding map.
References UE_API.
UpdateTagCount() [1/2]
FORCEINLINE bool FGameplayTagCountContainer::UpdateTagCount (const FGameplayTag & Tag, int32 CountDelta) inline
Update the specified tag by the specified delta, potentially causing an additional or removal from the explicit tag list.
Parameters
Tag Tag to update
CountDelta Delta of the tag count to apply
Returns
True if tag was either added or removed. (E.g., we had the tag and now dont. or didnt have the tag and now we do. We didn't just change the count (1 count -> 2 count would return false).
Definition at line 1150 of file GameplayEffectTypes.h.
References FORCEINLINE, and UpdateTagMap_Internal().
UpdateTagCount() [2/2]
FORCEINLINE void FGameplayTagCountContainer::UpdateTagCount (const FGameplayTagContainer & Container, int32 CountDelta) inline
Update the specified container of tags by the specified delta, potentially causing an additional or removal from the explicit tag list.
Parameters
Container Container of tags to update
CountDelta Delta of the tag count to apply
Definition at line 1119 of file GameplayEffectTypes.h.
References Container, ExplicitTags, FORCEINLINE, and UpdateTagMapDeferredParentRemoval_Internal().
UpdateTagCount_DeferredParentRemoval()
FORCEINLINE bool FGameplayTagCountContainer::UpdateTagCount_DeferredParentRemoval (const FGameplayTag & Tag, int32 CountDelta, TArray< FDeferredTagChangeDelegate > & DeferredTagChangeDelegates) inline
Update the specified tag by the specified delta, potentially causing an additional or removal from the explicit tag list.
Calling code MUST call FillParentTags followed by executing the returned delegates.
Parameters
Tag Tag to update
CountDelta Delta of the tag count to apply
DeferredTagChangeDelegates Delegates to be called after this code runs
Returns
True if tag was either added or removed. (E.g., we had the tag and now dont. or didnt have the tag and now we do. We didn't just change the count (1 count -> 2 count would return false).
Definition at line 1170 of file GameplayEffectTypes.h.
References FORCEINLINE, and UpdateTagMapDeferredParentRemoval_Internal().
UpdateTagMap_Internal()
GAMEPLAYABILITIES_API bool FGameplayTagCountContainer::UpdateTagMap_Internal (const FGameplayTag & Tag, int32 CountDelta) private
Internal helper function to adjust the explicit tag list & corresponding maps/delegates/etc.
as necessary
References UE_API.
Referenced by SetTagCount(), and UpdateTagCount().
UpdateTagMapDeferredParentRemoval_Internal()
GAMEPLAYABILITIES_API bool FGameplayTagCountContainer::UpdateTagMapDeferredParentRemoval_Internal (const FGameplayTag & Tag, int32 CountDelta, TArray< FDeferredTagChangeDelegate > & DeferredTagChangeDelegates) private
Internal helper function to adjust the explicit tag list & corresponding maps/delegates/etc.
as necessary. This does not call FillParentTags or any of the tag change delegates. These delegates are returned and must be executed by the caller.
References UE_API.
Referenced by UpdateTagCount(), and UpdateTagCount_DeferredParentRemoval().
Field Documentation
ExplicitTagCountMap
TMap<FGameplayTag, int32> FGameplayTagCountContainer::ExplicitTagCountMap private
Map of tag to explicit count of that tag.
Cannot share with above map because it's not safe to merge explicit and generic counts
Definition at line 1305 of file GameplayEffectTypes.h.
Referenced by GetExplicitTagCount(), and SetTagCount().
ExplicitTags
FGameplayTagContainer FGameplayTagCountContainer::ExplicitTags private
Container of tags that were explicitly added.
Definition at line 1311 of file GameplayEffectTypes.h.
Referenced by FillParentTags(), GetExplicitGameplayTags(), and UpdateTagCount().
GameplayTagCountMap
TMap<FGameplayTag, int32> FGameplayTagCountContainer::GameplayTagCountMap private
Map of tag to active count of that tag.
Definition at line 1302 of file GameplayEffectTypes.h.
Referenced by GetTagCount(), HasAllMatchingGameplayTags(), HasAnyMatchingGameplayTags(), and HasMatchingGameplayTag().
GameplayTagEventMap
TMap<FGameplayTag, FDelegateInfo> FGameplayTagCountContainer::GameplayTagEventMap private
Map of tag to delegate that will be fired when the count for the key tag changes to or away from zero.
Definition at line 1299 of file GameplayEffectTypes.h.
OnAnyTagChangeDelegate
FOnGameplayEffectTagCountChanged FGameplayTagCountContainer::OnAnyTagChangeDelegate private
Delegate fired whenever any tag's count changes to or away from zero.
Definition at line 1308 of file GameplayEffectTypes.h.
Referenced by RegisterGenericGameplayEvent().
The documentation for this struct was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/GameplayAbilities/Source/GameplayAbilities/Public/GameplayEffectTypes.h