Unreal Engine 5.6 C++ API: FShaderCodeVendorExtension Struct Reference
FShaderCodeVendorExtension Struct Reference
#include "ShaderCore.h"
Public Member Functions
FShaderCodeVendorExtension ()=default
FShaderCodeVendorExtension (EGpuVendorId InVendorId, uint16 InBufferIndex, uint16 InBaseIndex, uint16 InSize, EShaderParameterType InType)
Data Fields
FParameterAllocation Parameter
EGpuVendorId VendorId = EGpuVendorId::NotQueried
Static Public Attributes
static const EShaderOptionalDataKey Key = EShaderOptionalDataKey::VendorExtension
Friends
bool operator!= (const FShaderCodeVendorExtension &A, const FShaderCodeVendorExtension &B)
FArchive & operator<< (FArchive &Ar, FShaderCodeVendorExtension &Extension)
bool operator== (const FShaderCodeVendorExtension &A, const FShaderCodeVendorExtension &B)
Detailed Description
Definition at line 872 of file ShaderCore.h.
Constructor & Destructor Documentation
FShaderCodeVendorExtension() [1/2]
FShaderCodeVendorExtension::FShaderCodeVendorExtension () default
Referenced by operator!=, operator<<, and operator==.
FShaderCodeVendorExtension() [2/2]
FShaderCodeVendorExtension::FShaderCodeVendorExtension (EGpuVendorId InVendorId, uint16 InBufferIndex, uint16 InBaseIndex, uint16 InSize, EShaderParameterType InType) inline
Definition at line 881 of file ShaderCore.h.
References Parameter, and VendorId.
Friends And Related Symbol Documentation
operator!=
bool operator!= (const FShaderCodeVendorExtension & A, const FShaderCodeVendorExtension & B) friend
Definition at line 897 of file ShaderCore.h.
References FShaderCodeVendorExtension(), A, and B.
operator<<
FArchive & operator<< (FArchive & Ar, FShaderCodeVendorExtension & Extension) friend
Definition at line 887 of file ShaderCore.h.
References FShaderCodeVendorExtension(), Ar, Parameter, and VendorId.
operator==
bool operator== (const FShaderCodeVendorExtension & A, const FShaderCodeVendorExtension & B) friend
Definition at line 892 of file ShaderCore.h.
References FShaderCodeVendorExtension(), A, and B.
Field Documentation
Key
const EShaderOptionalDataKey FShaderCodeVendorExtension::Key = EShaderOptionalDataKey::VendorExtension static
Definition at line 875 of file ShaderCore.h.
Parameter
FParameterAllocation FShaderCodeVendorExtension::Parameter
Definition at line 878 of file ShaderCore.h.
Referenced by FShaderCodeVendorExtension(), and operator<<.
VendorId
EGpuVendorId FShaderCodeVendorExtension::VendorId = EGpuVendorId::NotQueried
Definition at line 877 of file ShaderCore.h.
Referenced by FShaderCodeVendorExtension(), and operator<<.
The documentation for this struct was generated from the following file:
Runtime/RenderCore/Public/ShaderCore.h