Unreal Engine 5.6 C++ API: UE::Geometry::TMatrix3< RealType > Struct Template Reference
UE::Geometry::TMatrix3< RealType > Struct Template Reference
#include "MatrixTypes.h"
Public Member Functions
TMatrix3 ()
template<typename RealType2>
constexpr TMatrix3 (const TMatrix3< RealType2 > &Mat)
TMatrix3 (const UE::Math::TVector< RealType > &U, const UE::Math::TVector< RealType > &V)
Construct outer-product of U*transpose(V) of U and V result is that Mij = u_i * v_j.
TMatrix3 (const UE::Math::TVector< RealType > &V1, const UE::Math::TVector< RealType > &V2, const UE::Math::TVector< RealType > &V3, bool bRows)
TMatrix3 (RealType ConstantValue)
TMatrix3 (RealType Diag0, RealType Diag1, RealType Diag2)
TMatrix3 (RealType M00, RealType M01, RealType M02, RealType M10, RealType M11, RealType M12, RealType M20, RealType M21, RealType M22)
RealType Determinant () const
TMatrix3< RealType > DeterminantTimesInverseTranspose () const
bool EpsilonEqual (const TMatrix3< RealType > &Mat2, RealType Epsilon) const
RealType InnerProduct (const TMatrix3< RealType > &Mat2) const
TMatrix3< RealType > Inverse () const
RealType operator() (int Row, int Col) const
TMatrix3< RealType > operator* (const TMatrix3< RealType > &Mat2) const
TVector< RealType > operator* (const UE::Math::TVector< RealType > &V) const
TMatrix3< RealType > operator* (RealType Scale) const
TMatrix3< RealType > & operator*= (const RealType &Scalar)
TMatrix3< RealType > operator+ (const TMatrix3< RealType > &Mat2) const
TMatrix3< RealType > & operator+= (const TMatrix3< RealType > &Mat2)
TMatrix3< RealType > operator- (const TMatrix3< RealType > &Mat2) const
RealType Trace () const
UE::Math::TVector< RealType > TransformByTranspose (const UE::Math::TVector< RealType > &V) const
TMatrix3< RealType > Transpose () const
Static Public Member Functions
static TMatrix3< RealType > AxisAngleD (const UE::Math::TVector< RealType > &Axis, RealType AngleDeg)
static TMatrix3< RealType > AxisAngleR (const UE::Math::TVector< RealType > &Axis, RealType AngleRad)
static TMatrix3< RealType > Identity ()
static TMatrix3< RealType > Zero ()
Data Fields
TVector< RealType > Row0
TVector< RealType > Row1
TVector< RealType > Row2
Detailed Description
template<typename RealType>
struct UE::Geometry::TMatrix3< RealType >
Definition at line 16 of file MatrixTypes.h.
Constructor & Destructor Documentation
TMatrix3() [1/7]
template<typename RealType> UE::Geometry::TMatrix3< RealType >::TMatrix3 () inline
Definition at line 22 of file MatrixTypes.h.
Referenced by UE::Geometry::TMatrix3< float >::AxisAngleR(), UE::Geometry::TMatrix3< float >::DeterminantTimesInverseTranspose(), UE::Geometry::TMatrix3< float >::Identity(), UE::Geometry::TMatrix3< float >::Inverse(), UE::Geometry::TMatrix3< float >::operator*(), UE::Geometry::TMatrix3< float >::operator*(), UE::Geometry::TMatrix3< float >::operator+(), UE::Geometry::TMatrix3< float >::operator-(), UE::Geometry::TMatrix3< float >::Transpose(), and UE::Geometry::TMatrix3< float >::Zero().
TMatrix3() [2/7]
template<typename RealType> UE::Geometry::TMatrix3< RealType >::TMatrix3 (RealType ConstantValue) inline
Definition at line 26 of file MatrixTypes.h.
TMatrix3() [3/7]
template<typename RealType> UE::Geometry::TMatrix3< RealType >::TMatrix3 (RealType Diag0, RealType Diag1, RealType Diag2) inline
Definition at line 33 of file MatrixTypes.h.
TMatrix3() [4/7]
template<typename RealType> UE::Geometry::TMatrix3< RealType >::TMatrix3 (const UE::Math::TVector< RealType > & U, const UE::Math::TVector< RealType > & V) inline
Construct outer-product of U*transpose(V) of U and V result is that Mij = u_i * v_j.
Definition at line 33 of file MatrixTypes.h.
TMatrix3() [5/7]
template<typename RealType> UE::Geometry::TMatrix3< RealType >::TMatrix3 (RealType M00, RealType M01, RealType M02, RealType M10, RealType M11, RealType M12, RealType M20, RealType M21, RealType M22) inline
Definition at line 51 of file MatrixTypes.h.
TMatrix3() [6/7]
template<typename RealType> UE::Geometry::TMatrix3< RealType >::TMatrix3 (const UE::Math::TVector< RealType > & V1, const UE::Math::TVector< RealType > & V2, const UE::Math::TVector< RealType > & V3, bool bRows) inline
Definition at line 58 of file MatrixTypes.h.
TMatrix3() [7/7]
template<typename RealType> template<typename RealType2> UE::Geometry::TMatrix3< RealType >::TMatrix3 (const TMatrix3< RealType2 > & Mat) inline explicit constexpr
Definition at line 75 of file MatrixTypes.h.
Member Function Documentation
AxisAngleD()
template<typename RealType> TMatrix3< RealType > UE::Geometry::TMatrix3< RealType >::AxisAngleD (const UE::Math::TVector< RealType > & Axis, RealType AngleDeg) inline static
Definition at line 274 of file MatrixTypes.h.
AxisAngleR()
template<typename RealType> TMatrix3< RealType > UE::Geometry::TMatrix3< RealType >::AxisAngleR (const UE::Math::TVector< RealType > & Axis, RealType AngleRad) inline static
Definition at line 254 of file MatrixTypes.h.
Referenced by UE::Geometry::TMatrix3< float >::AxisAngleD().
Determinant()
template<typename RealType> RealType UE::Geometry::TMatrix3< RealType >::Determinant () const inline
Definition at line 177 of file MatrixTypes.h.
Referenced by UE::Geometry::TAttrBasedQuadricError< float >::TAttrBasedQuadricError().
DeterminantTimesInverseTranspose()
template<typename RealType> TMatrix3< RealType > UE::Geometry::TMatrix3< RealType >::DeterminantTimesInverseTranspose () const inline
Definition at line 227 of file MatrixTypes.h.
EpsilonEqual()
template<typename RealType> bool UE::Geometry::TMatrix3< RealType >::EpsilonEqual (const TMatrix3< RealType > & Mat2, RealType Epsilon) const inline
Definition at line 247 of file MatrixTypes.h.
Identity()
template<typename RealType> TMatrix3< RealType > UE::Geometry::TMatrix3< RealType >::Identity () inline static
Definition at line 86 of file MatrixTypes.h.
InnerProduct()
template<typename RealType> RealType UE::Geometry::TMatrix3< RealType >::InnerProduct (const TMatrix3< RealType > & Mat2) const inline
Definition at line 167 of file MatrixTypes.h.
Referenced by FastTriWinding::EvaluateOrder2Approx(), and FastTriWinding::Order2Approx().
Inverse()
template<typename RealType> TMatrix3< RealType > UE::Geometry::TMatrix3< RealType >::Inverse () const inline
Definition at line 186 of file MatrixTypes.h.
Referenced by UE::Geometry::TAttrBasedQuadricError< float >::TAttrBasedQuadricError().
operator()()
template<typename RealType> RealType UE::Geometry::TMatrix3< RealType >::operator() (int Row, int Col) const inline
Definition at line 91 of file MatrixTypes.h.
operator*() [1/3]
template<typename RealType> TMatrix3< RealType > UE::Geometry::TMatrix3< RealType >::operator* (const TMatrix3< RealType > & Mat2) const inline
Definition at line 124 of file MatrixTypes.h.
operator*() [2/3]
template<typename RealType> TVector< RealType > UE::Geometry::TMatrix3< RealType >::operator* (const UE::Math::TVector< RealType > & V) const inline
Definition at line 116 of file MatrixTypes.h.
operator*() [3/3]
template<typename RealType> TMatrix3< RealType > UE::Geometry::TMatrix3< RealType >::operator* (RealType Scale) const inline
Definition at line 108 of file MatrixTypes.h.
operator*=()
template<typename RealType> TMatrix3< RealType > & UE::Geometry::TMatrix3< RealType >::operator*= (const RealType & Scalar) inline
Definition at line 151 of file MatrixTypes.h.
operator+()
template<typename RealType> TMatrix3< RealType > UE::Geometry::TMatrix3< RealType >::operator+ (const TMatrix3< RealType > & Mat2) const inline
Definition at line 141 of file MatrixTypes.h.
operator+=()
template<typename RealType> TMatrix3< RealType > & UE::Geometry::TMatrix3< RealType >::operator+= (const TMatrix3< RealType > & Mat2) inline
Definition at line 159 of file MatrixTypes.h.
operator-()
template<typename RealType> TMatrix3< RealType > UE::Geometry::TMatrix3< RealType >::operator- (const TMatrix3< RealType > & Mat2) const inline
Definition at line 146 of file MatrixTypes.h.
Trace()
template<typename RealType> RealType UE::Geometry::TMatrix3< RealType >::Trace () const inline
Definition at line 172 of file MatrixTypes.h.
Referenced by UE::Geometry::FPinchKelvinlet::PinchMatrix().
TransformByTranspose()
template<typename RealType> UE::Math::TVector< RealType > UE::Geometry::TMatrix3< RealType >::TransformByTranspose (const UE::Math::TVector< RealType > & V) const inline
Definition at line 215 of file MatrixTypes.h.
Referenced by UE::Geometry::TOrientedBox3< float >::ClosestPoint().
Transpose()
template<typename RealType> TMatrix3< RealType > UE::Geometry::TMatrix3< RealType >::Transpose () const inline
Definition at line 207 of file MatrixTypes.h.
Referenced by UE::Geometry::FPinchKelvinlet::PinchMatrix().
Zero()
template<typename RealType> TMatrix3< RealType > UE::Geometry::TMatrix3< RealType >::Zero () inline static
Definition at line 82 of file MatrixTypes.h.
Referenced by UE::Geometry::TQuaternion< RealType >::ToRotationMatrix().
Field Documentation
Row0
template<typename RealType> TVector<RealType> UE::Geometry::TMatrix3< RealType >::Row0
Definition at line 18 of file MatrixTypes.h.
Referenced by UE::Geometry::TMatrix3< float >::TMatrix3(), FKelvinletBrushOp::ApplyBrush(), FPinchKelvinletBrushOp::ApplyStamp(), UE::Geometry::TMatrix3< float >::EpsilonEqual(), UE::Geometry::TMatrix3< float >::InnerProduct(), UE::Geometry::operator*(), UE::Geometry::TMatrix3< float >::operator*(), UE::Geometry::TMatrix3< float >::operator+(), UE::Geometry::TMatrix3< float >::operator+=(), UE::Geometry::TMatrix3< float >::operator-(), and UE::Geometry::TQuaternion< RealType >::ToRotationMatrix().
Row1
template<typename RealType> TVector<RealType> UE::Geometry::TMatrix3< RealType >::Row1
Definition at line 19 of file MatrixTypes.h.
Referenced by FKelvinletBrushOp::ApplyBrush(), FPinchKelvinletBrushOp::ApplyStamp(), UE::Geometry::TMatrix3< float >::EpsilonEqual(), UE::Geometry::TMatrix3< float >::InnerProduct(), UE::Geometry::operator*(), UE::Geometry::TMatrix3< float >::operator*(), UE::Geometry::TMatrix3< float >::operator+(), UE::Geometry::TMatrix3< float >::operator+=(), UE::Geometry::TMatrix3< float >::operator-(), and UE::Geometry::TQuaternion< RealType >::ToRotationMatrix().
Row2
template<typename RealType> TVector<RealType> UE::Geometry::TMatrix3< RealType >::Row2
Definition at line 20 of file MatrixTypes.h.
Referenced by UE::Geometry::TMatrix3< float >::EpsilonEqual(), UE::Geometry::TMatrix3< float >::InnerProduct(), UE::Geometry::operator*(), UE::Geometry::TMatrix3< float >::operator*(), UE::Geometry::TMatrix3< float >::operator+(), UE::Geometry::TMatrix3< float >::operator+=(), UE::Geometry::TMatrix3< float >::operator-(), and UE::Geometry::TQuaternion< RealType >::ToRotationMatrix().
The documentation for this struct was generated from the following file:
Runtime/GeometryCore/Public/MatrixTypes.h