Unreal Engine 5.6 C++ API: FNetConnAnalyticsVars Struct Reference
FNetConnAnalyticsVars Struct Reference
Container class for separating analytics variables and processing, from the main NetConnection code.
#include "EngineNetAnalytics.h"
Data Structures
struct FPerNetConnData
Aggregation variables.
Public Types
using FNetResult = UE::Net::FNetResult
Public Member Functions
FNetConnAnalyticsVars ()
Default constructor.
void AddFailedPingAddressICMP (FString PingAddress)
void AddFailedPingAddressUDP (FString PingAddress)
void CommitAnalytics (FNetConnAnalyticsVars &AggregatedData)
void IncreaseOutOfOrderPacketsDuplicateCount (int32 Count=1)
void IncreaseOutOfOrderPacketsLostCount (int32 Count=1)
Accessors.
void IncreaseOutOfOrderPacketsRecoveredCount (int32 Count=1)
bool operator== (const FNetConnAnalyticsVars &A) const
Data Fields
TArray< FString > ClientCloseReasons
The remotely-communicated result/reason for triggering NetConnection Close (remote, server only)
TUniquePtr< FNetResult > CloseReason
The result/reason for triggering NetConnection Close (local)
uint64 OutAckOnlyCount
The number of packets that were exclusively ack packets.
uint64 OutKeepAliveCount
The number of packets that were just keep-alive packets.
TArray< FPerNetConnData > PerConnectionData
(Not filled until final commit) Contains Per-NetConnection data which can't be aggregated until final commit
TMap< FString, int32 > RecoveredFaults
NetConnection faults that were recovered from, and the number of times they were recovered from.
Private Attributes
TArray< FString > FailedPingAddressesICMP
List of IP addresses a client failed to ping with ICMP.
TArray< FString > FailedPingAddressesUDP
List of IP addresses a client failed to ping with UDP.
uint64 OutOfOrderPacketsDuplicateCount = 0
The number of out of order packets that were duplicates.
uint64 OutOfOrderPacketsLostCount = 0
The number of out of order packets lost.
uint64 OutOfOrderPacketsRecoveredCount = 0
The number of out of order packets recovered.
Friends
struct FNetConnAnalyticsData
Detailed Description
Container class for separating analytics variables and processing, from the main NetConnection code.
Definition at line 13 of file EngineNetAnalytics.h.
Member Typedef Documentation
FNetResult
using FNetConnAnalyticsVars::FNetResult = UE::Net::FNetResult
Definition at line 17 of file EngineNetAnalytics.h.
Constructor & Destructor Documentation
FNetConnAnalyticsVars()
FNetConnAnalyticsVars::FNetConnAnalyticsVars ()
Default constructor.
Referenced by CommitAnalytics(), and operator==().
Member Function Documentation
AddFailedPingAddressICMP()
void FNetConnAnalyticsVars::AddFailedPingAddressICMP (FString PingAddress) inline
Definition at line 45 of file EngineNetAnalytics.h.
References FailedPingAddressesICMP.
AddFailedPingAddressUDP()
void FNetConnAnalyticsVars::AddFailedPingAddressUDP (FString PingAddress) inline
Definition at line 53 of file EngineNetAnalytics.h.
References FailedPingAddressesICMP, and FailedPingAddressesUDP.
CommitAnalytics()
void FNetConnAnalyticsVars::CommitAnalytics (FNetConnAnalyticsVars & AggregatedData)
References FNetConnAnalyticsVars().
IncreaseOutOfOrderPacketsDuplicateCount()
void FNetConnAnalyticsVars::IncreaseOutOfOrderPacketsDuplicateCount (int32 Count = 1) inline
Definition at line 40 of file EngineNetAnalytics.h.
References Count, and OutOfOrderPacketsDuplicateCount.
IncreaseOutOfOrderPacketsLostCount()
void FNetConnAnalyticsVars::IncreaseOutOfOrderPacketsLostCount (int32 Count = 1) inline
Accessors.
Definition at line 30 of file EngineNetAnalytics.h.
References Count, and OutOfOrderPacketsLostCount.
IncreaseOutOfOrderPacketsRecoveredCount()
void FNetConnAnalyticsVars::IncreaseOutOfOrderPacketsRecoveredCount (int32 Count = 1) inline
Definition at line 35 of file EngineNetAnalytics.h.
References Count, and OutOfOrderPacketsRecoveredCount.
operator==()
bool FNetConnAnalyticsVars::operator== (const FNetConnAnalyticsVars & A) const
References FNetConnAnalyticsVars(), and A.
Friends And Related Symbol Documentation
FNetConnAnalyticsData
friend struct FNetConnAnalyticsData friend
Definition at line 15 of file EngineNetAnalytics.h.
References FNetConnAnalyticsData.
Referenced by FNetConnAnalyticsData.
Field Documentation
ClientCloseReasons
TArray<FString> FNetConnAnalyticsVars::ClientCloseReasons
The remotely-communicated result/reason for triggering NetConnection Close (remote, server only)
Definition at line 84 of file EngineNetAnalytics.h.
CloseReason
TUniquePtr<FNetResult> FNetConnAnalyticsVars::CloseReason
The result/reason for triggering NetConnection Close (local)
Definition at line 81 of file EngineNetAnalytics.h.
FailedPingAddressesICMP
TArray<FString> FNetConnAnalyticsVars::FailedPingAddressesICMP private
List of IP addresses a client failed to ping with ICMP.
Should correlate against NetConnection count, to determine overall percent.
Definition at line 91 of file EngineNetAnalytics.h.
Referenced by AddFailedPingAddressICMP(), and AddFailedPingAddressUDP().
FailedPingAddressesUDP
TArray<FString> FNetConnAnalyticsVars::FailedPingAddressesUDP private
List of IP addresses a client failed to ping with UDP.
Should correlate against NetConnection count, to determine overall percent.
Definition at line 94 of file EngineNetAnalytics.h.
Referenced by AddFailedPingAddressUDP().
OutAckOnlyCount
uint64 FNetConnAnalyticsVars::OutAckOnlyCount
The number of packets that were exclusively ack packets.
Definition at line 64 of file EngineNetAnalytics.h.
OutKeepAliveCount
uint64 FNetConnAnalyticsVars::OutKeepAliveCount
The number of packets that were just keep-alive packets.
Definition at line 67 of file EngineNetAnalytics.h.
OutOfOrderPacketsDuplicateCount
uint64 FNetConnAnalyticsVars::OutOfOrderPacketsDuplicateCount = 0 private
The number of out of order packets that were duplicates.
Definition at line 77 of file EngineNetAnalytics.h.
Referenced by IncreaseOutOfOrderPacketsDuplicateCount().
OutOfOrderPacketsLostCount
uint64 FNetConnAnalyticsVars::OutOfOrderPacketsLostCount = 0 private
The number of out of order packets lost.
Definition at line 71 of file EngineNetAnalytics.h.
Referenced by IncreaseOutOfOrderPacketsLostCount().
OutOfOrderPacketsRecoveredCount
uint64 FNetConnAnalyticsVars::OutOfOrderPacketsRecoveredCount = 0 private
The number of out of order packets recovered.
Definition at line 74 of file EngineNetAnalytics.h.
Referenced by IncreaseOutOfOrderPacketsRecoveredCount().
PerConnectionData
TArray<FPerNetConnData> FNetConnAnalyticsVars::PerConnectionData
(Not filled until final commit) Contains Per-NetConnection data which can't be aggregated until final commit
Definition at line 106 of file EngineNetAnalytics.h.
RecoveredFaults
TMap<FString, int32> FNetConnAnalyticsVars::RecoveredFaults
NetConnection faults that were recovered from, and the number of times they were recovered from.
Definition at line 87 of file EngineNetAnalytics.h.
The documentation for this struct was generated from the following file:
Runtime/Engine/Public/Analytics/EngineNetAnalytics.h