Unreal Engine 5.6 C++ API: UE::MovieScene::FFloatVectorPropertyTraits Struct Reference
UE::MovieScene::FFloatVectorPropertyTraits Struct Reference
#include "MovieSceneTracksComponentTypes.h"
Public Types
using MetaDataType = TPropertyMetaData<FVectorPropertyMetaData>
using StorageType = FFloatIntermediateVector
Static Public Member Functions
static FFloatIntermediateVector CombineComposites (FVectorPropertyMetaData MetaData, float InX, float InY, float InZ, float InW)
static void GetObjectPropertyValue (const UObject *InObject, FVectorPropertyMetaData MetaData, const FCustomPropertyAccessor &BaseCustomAccessor, FFloatIntermediateVector &OutValue)
static void GetObjectPropertyValue (const UObject *InObject, FVectorPropertyMetaData MetaData, const FName &PropertyPath, StorageType &OutValue)
static void GetObjectPropertyValue (const UObject *InObject, FVectorPropertyMetaData MetaData, FTrackInstancePropertyBindings *PropertyBindings, FFloatIntermediateVector &OutValue)
static void GetObjectPropertyValue (const UObject *InObject, FVectorPropertyMetaData MetaData, uint16 PropertyOffset, FFloatIntermediateVector &OutValue)
static void SetObjectPropertyValue (UObject *InObject, FVectorPropertyMetaData MetaData, const FCustomPropertyAccessor &BaseCustomAccessor, const FFloatIntermediateVector &InValue)
static void SetObjectPropertyValue (UObject *InObject, FVectorPropertyMetaData MetaData, FTrackInstancePropertyBindings *PropertyBindings, const FFloatIntermediateVector &InValue)
static void SetObjectPropertyValue (UObject *InObject, FVectorPropertyMetaData MetaData, uint16 PropertyOffset, const FFloatIntermediateVector &InValue)
Detailed Description
Definition at line 430 of file MovieSceneTracksComponentTypes.h.
Member Typedef Documentation
MetaDataType
using UE::MovieScene::FFloatVectorPropertyTraits::MetaDataType = TPropertyMetaData<FVectorPropertyMetaData>
Definition at line 433 of file MovieSceneTracksComponentTypes.h.
StorageType
using UE::MovieScene::FFloatVectorPropertyTraits::StorageType = FFloatIntermediateVector
Definition at line 432 of file MovieSceneTracksComponentTypes.h.
Member Function Documentation
CombineComposites()
FFloatIntermediateVector UE::MovieScene::FFloatVectorPropertyTraits::CombineComposites (FVectorPropertyMetaData MetaData, float InX, float InY, float InZ, float InW) inline static
Definition at line 496 of file MovieSceneTracksComponentTypes.h.
References MetaData.
GetObjectPropertyValue() [1/4]
void UE::MovieScene::FFloatVectorPropertyTraits::GetObjectPropertyValue (const UObject * InObject, FVectorPropertyMetaData MetaData, const FCustomPropertyAccessor & BaseCustomAccessor, FFloatIntermediateVector & OutValue) inline static
Definition at line 435 of file MovieSceneTracksComponentTypes.h.
References UE::MovieScene::TCustomPropertyAccessor< PropertyTraits >::Functions, and MetaData.
GetObjectPropertyValue() [2/4]
void UE::MovieScene::FFloatVectorPropertyTraits::GetObjectPropertyValue (const UObject * InObject, FVectorPropertyMetaData MetaData, const FName & PropertyPath, StorageType & OutValue) inline static
Definition at line 458 of file MovieSceneTracksComponentTypes.h.
References UE::MovieScene::TIndirectPropertyTraits< UObjectPropertyType, InMemoryType, bInIsComposite >::GetObjectPropertyValue(), and MetaData.
GetObjectPropertyValue() [3/4]
void UE::MovieScene::FFloatVectorPropertyTraits::GetObjectPropertyValue (const UObject * InObject, FVectorPropertyMetaData MetaData, FTrackInstancePropertyBindings * PropertyBindings, FFloatIntermediateVector & OutValue) inline static
Definition at line 449 of file MovieSceneTracksComponentTypes.h.
References UE::MovieScene::TIndirectPropertyTraits< UObjectPropertyType, InMemoryType, bInIsComposite >::GetObjectPropertyValue(), and MetaData.
GetObjectPropertyValue() [4/4]
void UE::MovieScene::FFloatVectorPropertyTraits::GetObjectPropertyValue (const UObject * InObject, FVectorPropertyMetaData MetaData, uint16 PropertyOffset, FFloatIntermediateVector & OutValue) inline static
Definition at line 440 of file MovieSceneTracksComponentTypes.h.
References UE::MovieScene::TIndirectPropertyTraits< UObjectPropertyType, InMemoryType, bInIsComposite >::GetObjectPropertyValue(), and MetaData.
SetObjectPropertyValue() [1/3]
void UE::MovieScene::FFloatVectorPropertyTraits::SetObjectPropertyValue (UObject * InObject, FVectorPropertyMetaData MetaData, const FCustomPropertyAccessor & BaseCustomAccessor, const FFloatIntermediateVector & InValue) inline static
Definition at line 468 of file MovieSceneTracksComponentTypes.h.
References UE::MovieScene::TCustomPropertyAccessor< PropertyTraits >::Functions, and MetaData.
SetObjectPropertyValue() [2/3]
void UE::MovieScene::FFloatVectorPropertyTraits::SetObjectPropertyValue (UObject * InObject, FVectorPropertyMetaData MetaData, FTrackInstancePropertyBindings * PropertyBindings, const FFloatIntermediateVector & InValue) inline static
Definition at line 484 of file MovieSceneTracksComponentTypes.h.
References checkf, MetaData, UE::MovieScene::TIndirectPropertyTraits< UObjectPropertyType, InMemoryType, bInIsComposite >::SetObjectPropertyValue(), and TEXT.
SetObjectPropertyValue() [3/3]
void UE::MovieScene::FFloatVectorPropertyTraits::SetObjectPropertyValue (UObject * InObject, FVectorPropertyMetaData MetaData, uint16 PropertyOffset, const FFloatIntermediateVector & InValue) inline static
Definition at line 473 of file MovieSceneTracksComponentTypes.h.
References checkf, MetaData, UE::MovieScene::TIndirectPropertyTraits< UObjectPropertyType, InMemoryType, bInIsComposite >::SetObjectPropertyValue(), and TEXT.
The documentation for this struct was generated from the following file:
Runtime/MovieSceneTracks/Public/MovieSceneTracksComponentTypes.h