Unreal Engine 5.6 C++ API: FLandscapeNotification Struct Reference
FLandscapeNotification Struct Reference
#include "LandscapeNotification.h"
Public Types
using FConditionCallback = TFunction<bool(void)>
using FUpdateTextCallback = TFunction<void(FText&)>
Public Member Functions
FLandscapeNotification (const TWeakObjectPtr< ALandscape > &InLandscape, ELandscapeNotificationType InNotificationType, FConditionCallback InConditionCallback=FConditionCallback([]() { return true;}), FUpdateTextCallback InUpdateTextCallback=[](FText &InText) {})
Constructs a notification which is expected to have a longer lifetime and behave in a dynamic way.
~FLandscapeNotification ()=default
TWeakObjectPtr< ALandscape > GetLandscape () const
ELandscapeNotificationType GetNotificationType () const
bool operator< (const FLandscapeNotification &Other) const
bool operator== (const FLandscapeNotification &Other) const
void SetNotificationText ()
bool ShouldShowNotification () const
Data Fields
double NotificationStartTime = -1.0
Determines when a notification should be displayed, ignored if less than 0.
FText NotificationText
The text to be displayed.Can either be set by user directly or by setting SetTextCallback at notification construction.
Private Member Functions
FLandscapeNotification ()=delete
Private Attributes
FConditionCallback ConditionCallback
Determines whether or not a notification should be shown.
TWeakObjectPtr< ALandscape > Landscape
ELandscapeNotificationType NotificationType
FUpdateTextCallback UpdateTextCallback
Sets the notification text per frame by manipulating InText&.
Detailed Description
Definition at line 18 of file LandscapeNotification.h.
Member Typedef Documentation
FConditionCallback
using FLandscapeNotification::FConditionCallback = TFunction<bool(void)> strong
Definition at line 28 of file LandscapeNotification.h.
FUpdateTextCallback
using FLandscapeNotification::FUpdateTextCallback = TFunction<void(FText&)>
Definition at line 29 of file LandscapeNotification.h.
Constructor & Destructor Documentation
FLandscapeNotification() [1/2]
FLandscapeNotification::FLandscapeNotification (const TWeakObjectPtr< ALandscape > & InLandscape, ELandscapeNotificationType InNotificationType, FConditionCallback InConditionCallback = FConditionCallback([]() { return true;}), FUpdateTextCallback InUpdateTextCallback = [](FText &InText) {})
Constructs a notification which is expected to have a longer lifetime and behave in a dynamic way.
Parameters
InLandscape - The landscape actor associated with this notification.
InNotificationType - The type of notification which determines its display priority.
InConditionCallback - Lambda used to conditionally determine whether this notification should be displayed per tick.
InUpdateTextCallback - Lambda used to construct notification text when the text can change (e.g. displaying the value of a variable).
Referenced by operator<(), and operator==().
~FLandscapeNotification()
FLandscapeNotification::~FLandscapeNotification () default
FLandscapeNotification() [2/2]
FLandscapeNotification::FLandscapeNotification () private delete
Member Function Documentation
GetLandscape()
TWeakObjectPtr< ALandscape > FLandscapeNotification::GetLandscape () const inline
Definition at line 45 of file LandscapeNotification.h.
References Landscape.
GetNotificationType()
ELandscapeNotificationType FLandscapeNotification::GetNotificationType () const inline
Definition at line 46 of file LandscapeNotification.h.
References NotificationType.
operator<()
bool FLandscapeNotification::operator< (const FLandscapeNotification & Other) const
References FLandscapeNotification(), and Other.
operator==()
bool FLandscapeNotification::operator== (const FLandscapeNotification & Other) const
References FLandscapeNotification(), and Other.
SetNotificationText()
void FLandscapeNotification::SetNotificationText ()
ShouldShowNotification()
bool FLandscapeNotification::ShouldShowNotification () const
Field Documentation
ConditionCallback
FConditionCallback FLandscapeNotification::ConditionCallback private
Determines whether or not a notification should be shown.
Defaults to return true.
Definition at line 67 of file LandscapeNotification.h.
Landscape
TWeakObjectPtr<ALandscape> FLandscapeNotification::Landscape private
Definition at line 63 of file LandscapeNotification.h.
Referenced by GetLandscape().
NotificationStartTime
double FLandscapeNotification::NotificationStartTime = -1.0
Determines when a notification should be displayed, ignored if less than 0.
Definition at line 60 of file LandscapeNotification.h.
NotificationText
FText FLandscapeNotification::NotificationText
The text to be displayed.Can either be set by user directly or by setting SetTextCallback at notification construction.
Definition at line 57 of file LandscapeNotification.h.
NotificationType
ELandscapeNotificationType FLandscapeNotification::NotificationType private
Definition at line 64 of file LandscapeNotification.h.
Referenced by GetNotificationType().
UpdateTextCallback
FUpdateTextCallback FLandscapeNotification::UpdateTextCallback private
Sets the notification text per frame by manipulating InText&.
Defaults to do nothing, allowing direct manipulation of NotificationText.
Definition at line 70 of file LandscapeNotification.h.
The documentation for this struct was generated from the following file:
Runtime/Landscape/Public/LandscapeNotification.h