Unreal Engine 5.6 C++ API: UE::Core::Private::Function::TFunction_OwnedObject< T, bUnique, bOnHeap > Struct Template Reference
UE::Core::Private::Function::TFunction_OwnedObject< T, bUnique, bOnHeap > Struct Template Reference
#include "Function.h"
Public Member Functions
template<typename ArgType>
TFunction_OwnedObject (ArgType &&Arg)
~TFunction_OwnedObject () override
void * CloneToEmptyStorage (void *UntypedStorage) const override
Creates a copy of itself into the storage and returns a pointer to the new object within it.
virtual void Destroy () override
Destructor.
virtual void * GetAddress () override
Returns the address of the object.
Public Member Functions inherited from UE::Core::Private::Function::IFunction_OwnedObject
virtual ~IFunction_OwnedObject ()=default
Destructor.
Data Fields
T Obj
Detailed Description
template<typename T, bool bUnique, bool bOnHeap>
struct UE::Core::Private::Function::TFunction_OwnedObject< T, bUnique, bOnHeap >
Definition at line 76 of file Function.h.
Constructor & Destructor Documentation
TFunction_OwnedObject()
template<typename T, bool bUnique, bool bOnHeap> template<typename ArgType> UE::Core::Private::Function::TFunction_OwnedObject< T, bUnique, bOnHeap >::TFunction_OwnedObject (ArgType && Arg) inline explicit
Definition at line 79 of file Function.h.
References Forward(), and Obj.
Referenced by CloneToEmptyStorage().
~TFunction_OwnedObject()
template<typename T, bool bUnique, bool bOnHeap> UE::Core::Private::Function::TFunction_OwnedObject< T, bUnique, bOnHeap >::~TFunction_OwnedObject () inline override
Definition at line 105 of file Function.h.
Referenced by Destroy().
Member Function Documentation
CloneToEmptyStorage()
template<typename T, bool bUnique, bool bOnHeap> void * UE::Core::Private::Function::TFunction_OwnedObject< T, bUnique, bOnHeap >::CloneToEmptyStorage (void * Storage) const override virtual
Creates a copy of itself into the storage and returns a pointer to the new object within it.
Implements UE::Core::Private::Function::IFunction_OwnedObject.
Definition at line 254 of file Function.h.
References TFunction_OwnedObject(), CA_ASSUME, check, UE::Core::Private::Function::FFunctionStorage::HeapAllocation, and Obj.
Destroy()
template<typename T, bool bUnique, bool bOnHeap> virtual void UE::Core::Private::Function::TFunction_OwnedObject< T, bUnique, bOnHeap >::Destroy () inline override virtual
Destructor.
Implements UE::Core::Private::Function::IFunction_OwnedObject.
Definition at line 91 of file Function.h.
References ~TFunction_OwnedObject(), and FMemory::Free().
GetAddress()
template<typename T, bool bUnique, bool bOnHeap> virtual void * UE::Core::Private::Function::TFunction_OwnedObject< T, bUnique, bOnHeap >::GetAddress () inline override virtual
Returns the address of the object.
Implements UE::Core::Private::Function::IFunction_OwnedObject.
Definition at line 84 of file Function.h.
References Obj.
Field Documentation
Obj
template<typename T, bool bUnique, bool bOnHeap> T UE::Core::Private::Function::TFunction_OwnedObject< T, bUnique, bOnHeap >::Obj
Definition at line 111 of file Function.h.
Referenced by TFunction_OwnedObject(), CloneToEmptyStorage(), and GetAddress().
The documentation for this struct was generated from the following file:
Runtime/Core/Public/Templates/Function.h