Unreal Engine 5.6 C++ API: UE::MovieScene::TFixedSparseBitSetBucketStorage< T > Struct Template Reference
UE::MovieScene::TFixedSparseBitSetBucketStorage< T > Struct Template Reference
#include "SparseBitSet.h"
Public Types
using BucketType = T
Public Member Functions
TFixedSparseBitSetBucketStorage ()
TFixedSparseBitSetBucketStorage (BucketType *StoragePtr)
TFixedSparseBitSetBucketStorage (const TFixedSparseBitSetBucketStorage &)=delete
TFixedSparseBitSetBucketStorage (TFixedSparseBitSetBucketStorage &&)=delete
BucketType & Get (int32 Index)
BucketType Get (int32 Index) const
BucketType * GetData ()
void operator= (const TFixedSparseBitSetBucketStorage &)=delete
void operator= (TFixedSparseBitSetBucketStorage &&)=delete
Data Fields
BucketType * Storage
Detailed Description
template<typename T>
struct UE::MovieScene::TFixedSparseBitSetBucketStorage< T >
Definition at line 454 of file SparseBitSet.h.
Member Typedef Documentation
BucketType
template<typename T> using UE::MovieScene::TFixedSparseBitSetBucketStorage< T >::BucketType = T
Definition at line 456 of file SparseBitSet.h.
Constructor & Destructor Documentation
TFixedSparseBitSetBucketStorage() [1/4]
template<typename T> UE::MovieScene::TFixedSparseBitSetBucketStorage< T >::TFixedSparseBitSetBucketStorage () inline explicit
Definition at line 458 of file SparseBitSet.h.
References Storage.
Referenced by TFixedSparseBitSetBucketStorage(), TFixedSparseBitSetBucketStorage(), operator=(), and operator=().
TFixedSparseBitSetBucketStorage() [2/4]
template<typename T> UE::MovieScene::TFixedSparseBitSetBucketStorage< T >::TFixedSparseBitSetBucketStorage (BucketType * StoragePtr) inline explicit
Definition at line 462 of file SparseBitSet.h.
References Storage.
TFixedSparseBitSetBucketStorage() [3/4]
template<typename T> UE::MovieScene::TFixedSparseBitSetBucketStorage< T >::TFixedSparseBitSetBucketStorage (const TFixedSparseBitSetBucketStorage< T > &) delete
References TFixedSparseBitSetBucketStorage().
TFixedSparseBitSetBucketStorage() [4/4]
template<typename T> UE::MovieScene::TFixedSparseBitSetBucketStorage< T >::TFixedSparseBitSetBucketStorage (TFixedSparseBitSetBucketStorage< T > &&) delete
References TFixedSparseBitSetBucketStorage().
Member Function Documentation
Get() [1/2]
template<typename T> BucketType & UE::MovieScene::TFixedSparseBitSetBucketStorage< T >::Get (int32 Index) inline
Definition at line 476 of file SparseBitSet.h.
References Storage.
Get() [2/2]
template<typename T> BucketType UE::MovieScene::TFixedSparseBitSetBucketStorage< T >::Get (int32 Index) const inline
Definition at line 477 of file SparseBitSet.h.
References Storage.
GetData()
template<typename T> BucketType * UE::MovieScene::TFixedSparseBitSetBucketStorage< T >::GetData () inline
Definition at line 474 of file SparseBitSet.h.
References Storage.
operator=() [1/2]
template<typename T> void UE::MovieScene::TFixedSparseBitSetBucketStorage< T >::operator= (const TFixedSparseBitSetBucketStorage< T > &) delete
References TFixedSparseBitSetBucketStorage().
operator=() [2/2]
template<typename T> void UE::MovieScene::TFixedSparseBitSetBucketStorage< T >::operator= (TFixedSparseBitSetBucketStorage< T > &&) delete
References TFixedSparseBitSetBucketStorage().
Field Documentation
Storage
template<typename T> BucketType* UE::MovieScene::TFixedSparseBitSetBucketStorage< T >::Storage
Definition at line 472 of file SparseBitSet.h.
Referenced by TFixedSparseBitSetBucketStorage(), TFixedSparseBitSetBucketStorage(), Get(), Get(), and GetData().
The documentation for this struct was generated from the following file:
Runtime/MovieScene/Public/Containers/SparseBitSet.h