Unreal Engine 5.6 C++ API: FMsg Struct Reference
FMsg Struct Reference
FMsg This struct contains functions for messaging with tools or debug logs.
#include "LogMacros.h"
Static Public Member Functions
template<typename FmtType, typename... Types>
static void Logf (const ANSICHAR *File, int32 Line, const FLogCategoryName &Category, ELogVerbosity::Type Verbosity, const FmtType &Fmt, Types... Args)
Log function.
template<typename FmtType, typename... Types>
static void Logf_Internal (const ANSICHAR *File, int32 Line, const FLogCategoryName &Category, ELogVerbosity::Type Verbosity, const FmtType &Fmt, Types... Args)
Internal version of log function.
static void LogV (const ANSICHAR *File, int32 Line, const FLogCategoryName &Category, ELogVerbosity::Type Verbosity, const TCHAR *Fmt, va_list Args)
static void SendNotificationString (const TCHAR *Message)
Sends a message to a remote tool.
template<typename FmtType, typename... Types>
static void SendNotificationStringf (const FmtType &Fmt, Types... Args)
Sends a formatted message to a remote tool.
Static Private Member Functions
static void VARARGS Logf_InternalImpl (const ANSICHAR *File, int32 Line, const FLogCategoryName &Category, ELogVerbosity::Type Verbosity, const TCHAR *Fmt,...)
static void VARARGS LogfImpl (const ANSICHAR *File, int32 Line, const FLogCategoryName &Category, ELogVerbosity::Type Verbosity, const TCHAR *Fmt,...)
static void VARARGS LogfImplV (const ANSICHAR *File, int32 Line, const FLogCategoryName &Category, ELogVerbosity::Type Verbosity, void *ReturnAddress, const TCHAR *Fmt, va_list Args)
static void VARARGS SendNotificationStringfImpl (const TCHAR *Fmt,...)
Detailed Description
FMsg This struct contains functions for messaging with tools or debug logs.
Definition at line 33 of file LogMacros.h.
Member Function Documentation
Logf()
template<typename FmtType, typename... Types> void FMsg::Logf (const ANSICHAR * File, int32 Line, const FLogCategoryName & Category, ELogVerbosity::Type Verbosity, const FmtType & Fmt, Types... Args) inline static
Log function.
Definition at line 50 of file LogMacros.h.
References Category, Line, LogfImpl(), TIsArrayOrRefOfTypeByPredicate< T, Predicate >::Value, and TIsValidVariadicFunctionArg< T >::Value.
Logf_Internal()
template<typename FmtType, typename... Types> void FMsg::Logf_Internal (const ANSICHAR * File, int32 Line, const FLogCategoryName & Category, ELogVerbosity::Type Verbosity, const FmtType & Fmt, Types... Args) inline static
Internal version of log function.
Should be used only in logging macros, as it relies on caller to call assert on fatal error
Definition at line 60 of file LogMacros.h.
References Category, Line, Logf_InternalImpl(), TIsArrayOrRefOfTypeByPredicate< T, Predicate >::Value, and TIsValidVariadicFunctionArg< T >::Value.
Logf_InternalImpl()
void VARARGS FMsg::Logf_InternalImpl (const ANSICHAR * File, int32 Line, const FLogCategoryName & Category, ELogVerbosity::Type Verbosity, const TCHAR * Fmt, ...) static private
References Category, Line, and VARARGS.
Referenced by Logf_Internal().
LogfImpl()
void VARARGS FMsg::LogfImpl (const ANSICHAR * File, int32 Line, const FLogCategoryName & Category, ELogVerbosity::Type Verbosity, const TCHAR * Fmt, ...) static private
References Category, Line, and VARARGS.
Referenced by Logf().
LogfImplV()
void VARARGS FMsg::LogfImplV (const ANSICHAR * File, int32 Line, const FLogCategoryName & Category, ELogVerbosity::Type Verbosity, void * ReturnAddress, const TCHAR * Fmt, va_list Args) static private
References Category, Line, and VARARGS.
LogV()
void FMsg::LogV (const ANSICHAR * File, int32 Line, const FLogCategoryName & Category, ELogVerbosity::Type Verbosity, const TCHAR * Fmt, va_list Args) static
References Category, and Line.
SendNotificationString()
void FMsg::SendNotificationString (const TCHAR * Message) static
Sends a message to a remote tool.
SendNotificationStringf()
template<typename FmtType, typename... Types> void FMsg::SendNotificationStringf (const FmtType & Fmt, Types... Args) inline static
Sends a formatted message to a remote tool.
Definition at line 40 of file LogMacros.h.
References SendNotificationStringfImpl(), TIsArrayOrRefOfTypeByPredicate< T, Predicate >::Value, and TIsValidVariadicFunctionArg< T >::Value.
SendNotificationStringfImpl()
void VARARGS FMsg::SendNotificationStringfImpl (const TCHAR * Fmt, ...) static private
References VARARGS.
Referenced by SendNotificationStringf().
The documentation for this struct was generated from the following file:
Runtime/Core/Public/Logging/LogMacros.h