Unreal Engine 5.6 C++ API: FSceneViewProjectionData Struct Reference
FSceneViewProjectionData Struct Reference
#include "SceneView.h"
Public Member Functions
FMatrix ComputeViewProjectionMatrix () const
const FIntRect & GetConstrainedViewRect () const
float GetNearPlaneFromProjectionMatrix () const
const FIntRect & GetViewRect () const
bool IsPerspectiveProjection () const
bool IsValidViewRectangle () const
void SetConstrainedViewRectangle (const FIntRect &InViewRect)
void SetViewRectangle (const FIntRect &InViewRect)
bool UpdateOrthoPlanes (bool bUseCameraHeightAsViewTarget)
bool UpdateOrthoPlanes (float &NearPlane, float &FarPlane, float HalfOrthoWidth, bool bUseCameraHeightAsViewTarget)
bool UpdateOrthoPlanes (FMinimalViewInfo &MinimalViewInfo)
Static Public Member Functions
static float GetNearPlaneFromProjectionMatrix (const FMatrix &ProjectionMatrix)
static bool UpdateOrthoPlanes (FSceneViewProjectionData *InOutProjectionData, float &NearPlane, float &FarPlane, float HalfOrthoWidth, bool bUseCameraHeightAsViewTarget)
Data Fields
FVector CameraToViewTarget = FVector::ZeroVector
FMatrix ProjectionMatrix = FMatrix::Identity
UE projection matrix projects such that clip space Z=1 is the near plane, and Z=0 is the infinite far plane.
FVector ViewOrigin = FVector::ZeroVector
The view origin.
FIntRect ViewRect = FIntRect(0,0,0,0)
FMatrix ViewRotationMatrix = FMatrix::Identity
Rotation matrix transforming from world space to view space.
Protected Attributes
FIntRect ConstrainedViewRect = FIntRect(0,0,0,0)
Detailed Description
Definition at line 45 of file SceneView.h.
Member Function Documentation
ComputeViewProjectionMatrix()
FMatrix FSceneViewProjectionData::ComputeViewProjectionMatrix () const inline
Definition at line 94 of file SceneView.h.
References ProjectionMatrix, ViewOrigin, and ViewRotationMatrix.
GetConstrainedViewRect()
const FIntRect & FSceneViewProjectionData::GetConstrainedViewRect () const inline
Definition at line 92 of file SceneView.h.
References ConstrainedViewRect.
GetNearPlaneFromProjectionMatrix() [1/2]
float FSceneViewProjectionData::GetNearPlaneFromProjectionMatrix () const inline
Definition at line 114 of file SceneView.h.
References GetNearPlaneFromProjectionMatrix(), and ProjectionMatrix.
Referenced by GetNearPlaneFromProjectionMatrix().
GetNearPlaneFromProjectionMatrix() [2/2]
float FSceneViewProjectionData::GetNearPlaneFromProjectionMatrix (const FMatrix & ProjectionMatrix) inline static
Definition at line 100 of file SceneView.h.
References ProjectionMatrix, and UE_DELTA.
GetViewRect()
const FIntRect & FSceneViewProjectionData::GetViewRect () const inline
Definition at line 91 of file SceneView.h.
References ViewRect.
IsPerspectiveProjection()
bool FSceneViewProjectionData::IsPerspectiveProjection () const inline
Definition at line 86 of file SceneView.h.
References ProjectionMatrix.
IsValidViewRectangle()
bool FSceneViewProjectionData::IsValidViewRectangle () const inline
Definition at line 78 of file SceneView.h.
References ConstrainedViewRect.
SetConstrainedViewRectangle()
void FSceneViewProjectionData::SetConstrainedViewRectangle (const FIntRect & InViewRect) inline
Definition at line 73 of file SceneView.h.
References ConstrainedViewRect.
SetViewRectangle()
void FSceneViewProjectionData::SetViewRectangle (const FIntRect & InViewRect) inline
Definition at line 67 of file SceneView.h.
References ConstrainedViewRect, and ViewRect.
UpdateOrthoPlanes() [1/4]
bool FSceneViewProjectionData::UpdateOrthoPlanes (bool bUseCameraHeightAsViewTarget)
UpdateOrthoPlanes() [2/4]
bool FSceneViewProjectionData::UpdateOrthoPlanes (float & NearPlane, float & FarPlane, float HalfOrthoWidth, bool bUseCameraHeightAsViewTarget) inline
Definition at line 121 of file SceneView.h.
References NearPlane, and UpdateOrthoPlanes().
UpdateOrthoPlanes() [3/4]
bool FSceneViewProjectionData::UpdateOrthoPlanes (FMinimalViewInfo & MinimalViewInfo)
UpdateOrthoPlanes() [4/4]
bool FSceneViewProjectionData::UpdateOrthoPlanes (FSceneViewProjectionData * InOutProjectionData, float & NearPlane, float & FarPlane, float HalfOrthoWidth, bool bUseCameraHeightAsViewTarget) static
References NearPlane.
Referenced by UpdateOrthoPlanes().
Field Documentation
CameraToViewTarget
FVector FSceneViewProjectionData::CameraToViewTarget = FVector::ZeroVector
Definition at line 60 of file SceneView.h.
ConstrainedViewRect
FIntRect FSceneViewProjectionData::ConstrainedViewRect = FIntRect(0,0,0,0) protected
Definition at line 64 of file SceneView.h.
Referenced by GetConstrainedViewRect(), IsValidViewRectangle(), SetConstrainedViewRectangle(), and SetViewRectangle().
ProjectionMatrix
FMatrix FSceneViewProjectionData::ProjectionMatrix = FMatrix::Identity
UE projection matrix projects such that clip space Z=1 is the near plane, and Z=0 is the infinite far plane.
Definition at line 54 of file SceneView.h.
Referenced by ComputeViewProjectionMatrix(), GetNearPlaneFromProjectionMatrix(), GetNearPlaneFromProjectionMatrix(), and IsPerspectiveProjection().
ViewOrigin
FVector FSceneViewProjectionData::ViewOrigin = FVector::ZeroVector
The view origin.
Definition at line 48 of file SceneView.h.
Referenced by ComputeViewProjectionMatrix().
ViewRect
FIntRect FSceneViewProjectionData::ViewRect = FIntRect(0,0,0,0)
Definition at line 57 of file SceneView.h.
Referenced by GetViewRect(), and SetViewRectangle().
ViewRotationMatrix
FMatrix FSceneViewProjectionData::ViewRotationMatrix = FMatrix::Identity
Rotation matrix transforming from world space to view space.
Definition at line 51 of file SceneView.h.
Referenced by ComputeViewProjectionMatrix().
The documentation for this struct was generated from the following file:
Runtime/Engine/Public/SceneView.h