Unreal Engine 5.6 C++ API: UE::Sequencer::FDynamicExtensionContainerIterator Struct Reference
UE::Sequencer::FDynamicExtensionContainerIterator Struct Reference
#include "DynamicExtensionContainer.h"
Public Member Functions
operator bool () const
SEQUENCERCORE_API FDynamicExtensionContainerIterator & operator++ ()
Protected Types
using IteratorType = TArray<FDynamicExtensionContainer::FDynamicExtensionInfo>::TConstIterator
Protected Member Functions
SEQUENCERCORE_API FDynamicExtensionContainerIterator (IteratorType &&InIterator, FViewModelTypeID InType)
Protected Attributes
void * CurrentExtension = nullptr
friend FDynamicExtensionContainer
IteratorType Iterator
FViewModelTypeID Type
Friends
SEQUENCERCORE_API friend bool operator!= (const FDynamicExtensionContainerIterator &A, const FDynamicExtensionContainerIterator &B)
Detailed Description
Definition at line 201 of file DynamicExtensionContainer.h.
Member Typedef Documentation
IteratorType
using UE::Sequencer::FDynamicExtensionContainerIterator::IteratorType = TArray<FDynamicExtensionContainer::FDynamicExtensionInfo>::TConstIterator protected
Definition at line 213 of file DynamicExtensionContainer.h.
Constructor & Destructor Documentation
FDynamicExtensionContainerIterator()
SEQUENCERCORE_API UE::Sequencer::FDynamicExtensionContainerIterator::FDynamicExtensionContainerIterator (IteratorType && InIterator, FViewModelTypeID InType) explicit protected
Referenced by UE::Sequencer::TDynamicExtensionContainerIterator< T >::TDynamicExtensionContainerIterator(), operator!=, and operator++().
Member Function Documentation
operator bool()
UE::Sequencer::FDynamicExtensionContainerIterator::operator bool () const inline explicit
Definition at line 203 of file DynamicExtensionContainer.h.
References Iterator.
operator++()
SEQUENCERCORE_API FDynamicExtensionContainerIterator & UE::Sequencer::FDynamicExtensionContainerIterator::operator++ ()
References FDynamicExtensionContainerIterator().
Friends And Related Symbol Documentation
operator!=
SEQUENCERCORE_API friend bool operator!= (const FDynamicExtensionContainerIterator & A, const FDynamicExtensionContainerIterator & B) friend
References FDynamicExtensionContainerIterator(), A, and B.
Field Documentation
CurrentExtension
void* UE::Sequencer::FDynamicExtensionContainerIterator::CurrentExtension = nullptr protected
Definition at line 219 of file DynamicExtensionContainer.h.
Referenced by UE::Sequencer::TDynamicExtensionContainerIterator< T >::operator*().
FDynamicExtensionContainer
friend UE::Sequencer::FDynamicExtensionContainerIterator::FDynamicExtensionContainer protected
Definition at line 215 of file DynamicExtensionContainer.h.
Iterator
IteratorType UE::Sequencer::FDynamicExtensionContainerIterator::Iterator protected
Definition at line 220 of file DynamicExtensionContainer.h.
Referenced by operator bool().
Type
FViewModelTypeID UE::Sequencer::FDynamicExtensionContainerIterator::Type protected
Definition at line 221 of file DynamicExtensionContainer.h.
The documentation for this struct was generated from the following file:
Editor/SequencerCore/Public/MVVM/Extensions/DynamicExtensionContainer.h