Unreal Engine 5.6 C++ API: FMicrosoftPlatformString Struct Reference
FMicrosoftPlatformString Struct Reference
Microsoft specific implementation.
#include "MicrosoftPlatformString.h"
Public Types
using Super = FGenericPlatformString
Public Member Functions
UE_DEPRECATED (5.6, "Use Strncat instead. !!NOTE THAT STRNCAT takes SrcLen rather than DestCount. You must call Strncat(Dest, Src, DestCount - Strlen(Dest) - 1).") static FORCEINLINE WIDECHAR *Strcat(WIDECHAR *Dest
UE_DEPRECATED (5.6, "Use Strncat instead. !!NOTE THAT STRNCAT takes SrcLen rather than DestSize. You must call Strncat(Dest, Src, DestCount - Strlen(Dest) - 1).") static FORCEINLINE ANSICHAR *Strcat(ANSICHAR *Dest
UE_DEPRECATED (5.6, "Use Strncat instead. !!NOTE THAT STRNCAT takes SrcLen rather than DestSize. You must call Strncat(Dest, Src, DestCount - Strlen(Dest) - 1).") static FORCEINLINE UTF8CHAR *Strcat(UTF8CHAR *Dest
UE_DEPRECATED (5.6, "Use Strncpy instead. Note that Strncpy has a behavior difference from Strcpy: it memzeroes the entire DestCount-sized buffer after the end of string.") static FORCEINLINE ANSICHAR *Strcpy(ANSICHAR *Dest
UE_DEPRECATED (5.6, "Use Strncpy instead. Note that Strncpy has a behavior difference from Strcpy: it memzeroes the entire DestCount-sized buffer after the end of string.") static FORCEINLINE UTF8CHAR *Strcpy(UTF8CHAR *Dest
UE_DEPRECATED (5.6, "Use Strncpy instead. Note that Strncpy has a behavior difference from Strcpy: it memzeroes the entire DestCount-sized buffer after the end of string.") static FORCEINLINE WIDECHAR *Strcpy(WIDECHAR *Dest
Static Public Member Functions
static FORCEINLINE double Atod (const ANSICHAR *String)
static FORCEINLINE double Atod (const UTF8CHAR *String)
static FORCEINLINE double Atod (const WIDECHAR *String)
static FORCEINLINE float Atof (const ANSICHAR *String)
static FORCEINLINE float Atof (const UTF8CHAR *String)
static FORCEINLINE float Atof (const WIDECHAR *String)
static FORCEINLINE int32 Atoi (const ANSICHAR *String)
static FORCEINLINE int32 Atoi (const UTF8CHAR *String)
static FORCEINLINE int32 Atoi (const WIDECHAR *String)
static FORCEINLINE int64 Atoi64 (const ANSICHAR *String)
static FORCEINLINE int64 Atoi64 (const UTF8CHAR *String)
static FORCEINLINE int64 Atoi64 (const WIDECHAR *String)
static FORCEINLINE int32 GetVarArgs (ANSICHAR *Dest, SIZE_T DestSize, const ANSICHAR *&Fmt, va_list ArgPtr)
static FORCEINLINE int32 GetVarArgs (UTF8CHAR *Dest, SIZE_T DestSize, const UTF8CHAR *&Fmt, va_list ArgPtr)
static FORCEINLINE int32 GetVarArgs (WIDECHAR *Dest, SIZE_T DestSize, const WIDECHAR *&Fmt, va_list ArgPtr)
static FORCEINLINE ANSICHAR * Strcat (ANSICHAR *Dest, const ANSICHAR *Src)
static FORCEINLINE UTF8CHAR * Strcat (UTF8CHAR *Dest, const UTF8CHAR *Src)
static FORCEINLINE WIDECHAR * Strcat (WIDECHAR *Dest, const WIDECHAR *Src)
static FORCEINLINE const ANSICHAR * Strchr (const ANSICHAR *String, ANSICHAR C)
static FORCEINLINE const UTF8CHAR * Strchr (const UTF8CHAR *String, UTF8CHAR C)
static FORCEINLINE const WIDECHAR * Strchr (const WIDECHAR *String, WIDECHAR C)
static FORCEINLINE int32 Strcmp (const ANSICHAR *String1, const ANSICHAR *String2)
static FORCEINLINE int32 Strcmp (const UTF8CHAR *String1, const UTF8CHAR *String2)
static FORCEINLINE int32 Strcmp (const WIDECHAR *String1, const WIDECHAR *String2)
static FORCEINLINE ANSICHAR * Strcpy (ANSICHAR *Dest, const ANSICHAR *Src)
Ansi implementation.
static FORCEINLINE UTF8CHAR * Strcpy (UTF8CHAR *Dest, const UTF8CHAR *Src)
UTF8CHAR implementation.
static FORCEINLINE WIDECHAR * Strcpy (WIDECHAR *Dest, const WIDECHAR *Src)
Wide character implementation.
static FORCEINLINE int32 Strlen (const ANSICHAR *String)
static FORCEINLINE int32 Strlen (const UCS2CHAR *String)
UCS2CHAR implementation - this is identical to WIDECHAR for Windows platforms.
static FORCEINLINE int32 Strlen (const UTF8CHAR *String)
static FORCEINLINE int32 Strlen (const WIDECHAR *String)
static FORCEINLINE ANSICHAR * Strncat (ANSICHAR *Dest, const ANSICHAR *Src, SIZE_T SrcLen)
static PRAGMA_ENABLE_DEPRECATION_WARNINGS FORCEINLINE UTF8CHAR * Strncat (UTF8CHAR *Dest, const UTF8CHAR *Src, SIZE_T SrcLen)
static FORCEINLINE WIDECHAR * Strncat (WIDECHAR *Dest, const WIDECHAR *Src, SIZE_T SrcLen)
static FORCEINLINE int32 Strncmp (const ANSICHAR *String1, const ANSICHAR *String2, SIZE_T Count)
static int32 Strncmp (const ANSICHAR *String1, const UTF8CHAR *String2, SIZE_T Count)
static int32 Strncmp (const ANSICHAR *String1, const WIDECHAR *String2, SIZE_T Count)
static int32 Strncmp (const UTF8CHAR *String1, const ANSICHAR *String2, SIZE_T Count)
static FORCEINLINE int32 Strncmp (const UTF8CHAR *String1, const UTF8CHAR *String2, SIZE_T Count)
static int32 Strncmp (const UTF8CHAR *String1, const WIDECHAR *String2, SIZE_T Count)
static int32 Strncmp (const WIDECHAR *String1, const ANSICHAR *String2, SIZE_T Count)
static int32 Strncmp (const WIDECHAR *String1, const UTF8CHAR *String2, SIZE_T Count)
static FORCEINLINE int32 Strncmp (const WIDECHAR *String1, const WIDECHAR *String2, SIZE_T Count)
static FORCEINLINE ANSICHAR * Strncpy (ANSICHAR *Dest, const ANSICHAR *Src, SIZE_T MaxLen)
static PRAGMA_ENABLE_DEPRECATION_WARNINGS FORCEINLINE UTF8CHAR * Strncpy (UTF8CHAR *Dest, const UTF8CHAR *Src, SIZE_T MaxLen)
static FORCEINLINE WIDECHAR * Strncpy (WIDECHAR *Dest, const WIDECHAR *Src, SIZE_T MaxLen)
static FORCEINLINE int32 Strnlen (const ANSICHAR *String, SIZE_T StringSize)
static FORCEINLINE int32 Strnlen (const UCS2CHAR *String, SIZE_T StringSize)
static FORCEINLINE int32 Strnlen (const UTF8CHAR *String, SIZE_T StringSize)
static FORCEINLINE int32 Strnlen (const WIDECHAR *String, SIZE_T StringSize)
static FORCEINLINE const ANSICHAR * Strrchr (const ANSICHAR *String, ANSICHAR C)
static FORCEINLINE const UTF8CHAR * Strrchr (const UTF8CHAR *String, UTF8CHAR C)
static FORCEINLINE const WIDECHAR * Strrchr (const WIDECHAR *String, WIDECHAR C)
static FORCEINLINE const ANSICHAR * Strstr (const ANSICHAR *String, const ANSICHAR *Find)
static FORCEINLINE const UTF8CHAR * Strstr (const UTF8CHAR *String, const UTF8CHAR *Find)
static FORCEINLINE const WIDECHAR * Strstr (const WIDECHAR *String, const WIDECHAR *Find)
static FORCEINLINE int32 Strtoi (const ANSICHAR *Start, ANSICHAR **End, int32 Base)
static FORCEINLINE int32 Strtoi (const UTF8CHAR *Start, UTF8CHAR **End, int32 Base)
static FORCEINLINE int32 Strtoi (const WIDECHAR *Start, WIDECHAR **End, int32 Base)
static FORCEINLINE int64 Strtoi64 (const ANSICHAR *Start, ANSICHAR **End, int32 Base)
static FORCEINLINE int64 Strtoi64 (const UTF8CHAR *Start, UTF8CHAR **End, int32 Base)
static FORCEINLINE int64 Strtoi64 (const WIDECHAR *Start, WIDECHAR **End, int32 Base)
static FORCEINLINE ANSICHAR * Strtok (ANSICHAR *StrToken, const ANSICHAR *Delim, ANSICHAR **Context)
static FORCEINLINE UTF8CHAR * Strtok (UTF8CHAR *StrToken, const UTF8CHAR *Delim, UTF8CHAR **Context)
static FORCEINLINE WIDECHAR * Strtok (WIDECHAR *StrToken, const WIDECHAR *Delim, WIDECHAR **Context)
static FORCEINLINE uint64 Strtoui64 (const ANSICHAR *Start, ANSICHAR **End, int32 Base)
static FORCEINLINE uint64 Strtoui64 (const UTF8CHAR *Start, UTF8CHAR **End, int32 Base)
static FORCEINLINE uint64 Strtoui64 (const WIDECHAR *Start, WIDECHAR **End, int32 Base)
template<typename CharType>
static CharType * Strupr (CharType *Dest, SIZE_T DestCount)
Static Public Member Functions inherited from FGenericPlatformString
template<typename DestEncoding, typename SourceEncoding>
static constexpr bool CanConvertCodepoint (SourceEncoding Codepoint)
Tests whether a particular codepoint can be converted to the destination encoding.
template<typename SourceEncoding, typename DestEncoding>
static FORCEINLINE DestEncoding * Convert (DestEncoding *Dest, int32 DestSize, const SourceEncoding *Src)
Converts the null-terminated Src string range from SourceEncoding to DestEncoding and writes it to the [Dest, Dest+DestSize) range, including a null terminator.
template<typename SourceEncoding, typename DestEncoding>
static FORCEINLINE DestEncoding * Convert (DestEncoding *Dest, int32 DestSize, const SourceEncoding *Src, int32 SrcSize)
Converts the [Src, Src+SrcSize) string range from SourceEncoding to DestEncoding and writes it to the [Dest, Dest+DestSize) range.
template<typename DestEncoding, typename SourceEncoding>
static int32 ConvertedLength (const SourceEncoding *Src)
Returns the required buffer length for the null-terminated Src string when converted to the DestChar encoding.
template<typename DestEncoding, typename SourceEncoding>
static int32 ConvertedLength (const SourceEncoding *Src, int32 SrcSize)
Returns the required buffer length for the [Src, Src+SrcSize) string when converted to the DestChar encoding.
static const ANSICHAR * GetEncodingName ()
template<typename Encoding>
static const TCHAR * GetEncodingTypeName ()
Returns the string representing the name of the given encoding type.
static int32 Strncmp (const ANSICHAR *String1, const ANSICHAR *String2, SIZE_T Count)
static int32 Strncmp (const ANSICHAR *String1, const UTF8CHAR *String2, SIZE_T Count)
static int32 Strncmp (const ANSICHAR *String1, const WIDECHAR *String2, SIZE_T Count)
static int32 Strncmp (const UTF8CHAR *String1, const ANSICHAR *String2, SIZE_T Count)
static int32 Strncmp (const UTF8CHAR *String1, const UTF8CHAR *String2, SIZE_T Count)
static int32 Strncmp (const UTF8CHAR *String1, const WIDECHAR *String2, SIZE_T Count)
static int32 Strncmp (const WIDECHAR *String1, const ANSICHAR *String2, SIZE_T Count)
static int32 Strncmp (const WIDECHAR *String1, const UTF8CHAR *String2, SIZE_T Count)
static int32 Strncmp (const WIDECHAR *String1, const WIDECHAR *String2, SIZE_T Count)
Static Public Member Functions inherited from FGenericPlatformStricmp
static int32 Stricmp (const ANSICHAR *String1, const ANSICHAR *String2)
static int32 Stricmp (const ANSICHAR *String1, const UTF16CHAR *String2)
static int32 Stricmp (const ANSICHAR *String1, const UTF32CHAR *String2)
static int32 Stricmp (const ANSICHAR *String1, const UTF8CHAR *String2)
static int32 Stricmp (const ANSICHAR *String1, const WIDECHAR *String2)
static int32 Stricmp (const UTF16CHAR *String1, const ANSICHAR *String2)
static int32 Stricmp (const UTF16CHAR *String1, const UTF16CHAR *String2)
static int32 Stricmp (const UTF32CHAR *String1, const ANSICHAR *String2)
static int32 Stricmp (const UTF32CHAR *String1, const UTF32CHAR *String2)
static int32 Stricmp (const UTF8CHAR *String1, const ANSICHAR *String2)
static int32 Stricmp (const UTF8CHAR *String1, const UTF8CHAR *String2)
static int32 Stricmp (const WIDECHAR *String1, const ANSICHAR *String2)
static int32 Stricmp (const WIDECHAR *String1, const WIDECHAR *String2)
static int32 Strnicmp (const ANSICHAR *String1, const ANSICHAR *String2, SIZE_T Count)
static int32 Strnicmp (const ANSICHAR *String1, const UTF16CHAR *String2, SIZE_T Count)
static int32 Strnicmp (const ANSICHAR *String1, const UTF32CHAR *String2, SIZE_T Count)
static int32 Strnicmp (const ANSICHAR *String1, const UTF8CHAR *String2, SIZE_T Count)
static int32 Strnicmp (const ANSICHAR *String1, const WIDECHAR *String2, SIZE_T Count)
static int32 Strnicmp (const UTF16CHAR *String1, const ANSICHAR *String2, SIZE_T Count)
static int32 Strnicmp (const UTF16CHAR *String1, const UTF16CHAR *String2, SIZE_T Count)
static int32 Strnicmp (const UTF32CHAR *String1, const ANSICHAR *String2, SIZE_T Count)
static int32 Strnicmp (const UTF32CHAR *String1, const UTF32CHAR *String2, SIZE_T Count)
static int32 Strnicmp (const UTF8CHAR *String1, const ANSICHAR *String2, SIZE_T Count)
static int32 Strnicmp (const UTF8CHAR *String1, const UTF8CHAR *String2, SIZE_T Count)
static int32 Strnicmp (const WIDECHAR *String1, const ANSICHAR *String2, SIZE_T Count)
static int32 Strnicmp (const WIDECHAR *String1, const WIDECHAR *String2, SIZE_T Count)
Data Fields
SIZE_T DestCount
SIZE_T const WIDECHAR * Src
SIZE_T const ANSICHAR * Src
SIZE_T const UTF8CHAR * Src
Additional Inherited Members
Static Public Attributes inherited from FGenericPlatformString
static constexpr bool IsUnicodeEncoded = true
True if the encoding type of the string is some form of unicode.
Detailed Description
Microsoft specific implementation.
Definition at line 28 of file MicrosoftPlatformString.h.
Member Typedef Documentation
Super
using FMicrosoftPlatformString::Super = FGenericPlatformString
Definition at line 38 of file MicrosoftPlatformString.h.
Member Function Documentation
Atod() [1/3]
FORCEINLINE double FMicrosoftPlatformString::Atod (const ANSICHAR * String) inline static
Definition at line 288 of file MicrosoftPlatformString.h.
References FORCEINLINE, and String.
Atod() [2/3]
FORCEINLINE double FMicrosoftPlatformString::Atod (const UTF8CHAR * String) inline static
Definition at line 425 of file MicrosoftPlatformString.h.
References Atod(), FORCEINLINE, and String.
Atod() [3/3]
FORCEINLINE double FMicrosoftPlatformString::Atod (const WIDECHAR * String) inline static
Definition at line 162 of file MicrosoftPlatformString.h.
References FORCEINLINE, and String.
Referenced by Atod().
Atof() [1/3]
FORCEINLINE float FMicrosoftPlatformString::Atof (const ANSICHAR * String) inline static
Definition at line 283 of file MicrosoftPlatformString.h.
References FORCEINLINE, and String.
Atof() [2/3]
FORCEINLINE float FMicrosoftPlatformString::Atof (const UTF8CHAR * String) inline static
Definition at line 420 of file MicrosoftPlatformString.h.
References Atof(), FORCEINLINE, and String.
Atof() [3/3]
FORCEINLINE float FMicrosoftPlatformString::Atof (const WIDECHAR * String) inline static
Definition at line 157 of file MicrosoftPlatformString.h.
References FORCEINLINE, and String.
Referenced by Atof().
Atoi() [1/3]
FORCEINLINE int32 FMicrosoftPlatformString::Atoi (const ANSICHAR * String) inline static
Definition at line 273 of file MicrosoftPlatformString.h.
References FORCEINLINE, and String.
Atoi() [2/3]
FORCEINLINE int32 FMicrosoftPlatformString::Atoi (const UTF8CHAR * String) inline static
Definition at line 410 of file MicrosoftPlatformString.h.
References Atoi(), FORCEINLINE, and String.
Atoi() [3/3]
FORCEINLINE int32 FMicrosoftPlatformString::Atoi (const WIDECHAR * String) inline static
Definition at line 147 of file MicrosoftPlatformString.h.
References FORCEINLINE, and String.
Referenced by Atoi().
Atoi64() [1/3]
FORCEINLINE int64 FMicrosoftPlatformString::Atoi64 (const ANSICHAR * String) inline static
Definition at line 278 of file MicrosoftPlatformString.h.
References FORCEINLINE, and String.
Atoi64() [2/3]
FORCEINLINE int64 FMicrosoftPlatformString::Atoi64 (const UTF8CHAR * String) inline static
Definition at line 415 of file MicrosoftPlatformString.h.
References Atoi64(), FORCEINLINE, and String.
Atoi64() [3/3]
FORCEINLINE int64 FMicrosoftPlatformString::Atoi64 (const WIDECHAR * String) inline static
Definition at line 152 of file MicrosoftPlatformString.h.
References FORCEINLINE, and String.
Referenced by Atoi64().
GetVarArgs() [1/3]
FORCEINLINE int32 FMicrosoftPlatformString::GetVarArgs (ANSICHAR * Dest, SIZE_T DestSize, const ANSICHAR *& Fmt, va_list ArgPtr) inline static
Definition at line 313 of file MicrosoftPlatformString.h.
References FORCEINLINE.
GetVarArgs() [2/3]
FORCEINLINE int32 FMicrosoftPlatformString::GetVarArgs (UTF8CHAR * Dest, SIZE_T DestSize, const UTF8CHAR *& Fmt, va_list ArgPtr) inline static
Definition at line 450 of file MicrosoftPlatformString.h.
References FORCEINLINE, and GetVarArgs().
GetVarArgs() [3/3]
FORCEINLINE int32 FMicrosoftPlatformString::GetVarArgs (WIDECHAR * Dest, SIZE_T DestSize, const WIDECHAR *& Fmt, va_list ArgPtr) inline static
Definition at line 191 of file MicrosoftPlatformString.h.
References FORCEINLINE, and vswprintf().
Referenced by GetVarArgs().
Strcat() [1/3]
FORCEINLINE ANSICHAR * FMicrosoftPlatformString::Strcat (ANSICHAR * Dest, const ANSICHAR * Src) inline static
Definition at line 221 of file MicrosoftPlatformString.h.
References FORCEINLINE, and Src.
Strcat() [2/3]
FORCEINLINE UTF8CHAR * FMicrosoftPlatformString::Strcat (UTF8CHAR * Dest, const UTF8CHAR * Src) inline static
Definition at line 356 of file MicrosoftPlatformString.h.
References FORCEINLINE, Src, and Strcat().
Strcat() [3/3]
FORCEINLINE WIDECHAR * FMicrosoftPlatformString::Strcat (WIDECHAR * Dest, const WIDECHAR * Src) inline static
Definition at line 80 of file MicrosoftPlatformString.h.
References FORCEINLINE, and Src.
Referenced by Strcat(), UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
Strchr() [1/3]
FORCEINLINE const ANSICHAR * FMicrosoftPlatformString::Strchr (const ANSICHAR * String, ANSICHAR C) inline static
Definition at line 263 of file MicrosoftPlatformString.h.
References FORCEINLINE, and String.
Strchr() [2/3]
FORCEINLINE const UTF8CHAR * FMicrosoftPlatformString::Strchr (const UTF8CHAR * String, UTF8CHAR C) inline static
Definition at line 400 of file MicrosoftPlatformString.h.
References FORCEINLINE, Strchr(), and String.
Strchr() [3/3]
FORCEINLINE const WIDECHAR * FMicrosoftPlatformString::Strchr (const WIDECHAR * String, WIDECHAR C) inline static
Definition at line 137 of file MicrosoftPlatformString.h.
References FORCEINLINE, and String.
Referenced by Strchr().
Strcmp() [1/3]
FORCEINLINE int32 FMicrosoftPlatformString::Strcmp (const ANSICHAR * String1, const ANSICHAR * String2) inline static
Definition at line 238 of file MicrosoftPlatformString.h.
References FORCEINLINE.
Strcmp() [2/3]
FORCEINLINE int32 FMicrosoftPlatformString::Strcmp (const UTF8CHAR * String1, const UTF8CHAR * String2) inline static
Definition at line 375 of file MicrosoftPlatformString.h.
References FORCEINLINE, and Strcmp().
Strcmp() [3/3]
FORCEINLINE int32 FMicrosoftPlatformString::Strcmp (const WIDECHAR * String1, const WIDECHAR * String2) inline static
Definition at line 112 of file MicrosoftPlatformString.h.
References FORCEINLINE.
Referenced by Strcmp().
Strcpy() [1/3]
FORCEINLINE ANSICHAR * FMicrosoftPlatformString::Strcpy (ANSICHAR * Dest, const ANSICHAR * Src) inline static
Ansi implementation.
Definition at line 201 of file MicrosoftPlatformString.h.
References FORCEINLINE, and Src.
Strcpy() [2/3]
FORCEINLINE UTF8CHAR * FMicrosoftPlatformString::Strcpy (UTF8CHAR * Dest, const UTF8CHAR * Src) inline static
UTF8CHAR implementation.
Definition at line 336 of file MicrosoftPlatformString.h.
References FORCEINLINE, Src, and Strcpy().
Strcpy() [3/3]
FORCEINLINE WIDECHAR * FMicrosoftPlatformString::Strcpy (WIDECHAR * Dest, const WIDECHAR * Src) inline static
Wide character implementation.
Definition at line 60 of file MicrosoftPlatformString.h.
References FORCEINLINE, and Src.
Referenced by Strcpy().
Strlen() [1/4]
FORCEINLINE int32 FMicrosoftPlatformString::Strlen (const ANSICHAR * String) inline static
Definition at line 248 of file MicrosoftPlatformString.h.
References FORCEINLINE, and String.
Strlen() [2/4]
FORCEINLINE int32 FMicrosoftPlatformString::Strlen (const UCS2CHAR * String) inline static
UCS2CHAR implementation - this is identical to WIDECHAR for Windows platforms.
Definition at line 323 of file MicrosoftPlatformString.h.
References FORCEINLINE, and String.
Strlen() [3/4]
FORCEINLINE int32 FMicrosoftPlatformString::Strlen (const UTF8CHAR * String) inline static
Definition at line 385 of file MicrosoftPlatformString.h.
References FORCEINLINE, String, and Strlen().
Strlen() [4/4]
FORCEINLINE int32 FMicrosoftPlatformString::Strlen (const WIDECHAR * String) inline static
Definition at line 122 of file MicrosoftPlatformString.h.
References FORCEINLINE, and String.
Referenced by Strlen(), and Strncat().
Strncat() [1/3]
FORCEINLINE ANSICHAR * FMicrosoftPlatformString::Strncat (ANSICHAR * Dest, const ANSICHAR * Src, SIZE_T SrcLen) inline static
Definition at line 233 of file MicrosoftPlatformString.h.
References FORCEINLINE, and Src.
Strncat() [2/3]
PRAGMA_ENABLE_DEPRECATION_WARNINGS FORCEINLINE UTF8CHAR * FMicrosoftPlatformString::Strncat (UTF8CHAR * Dest, const UTF8CHAR * Src, SIZE_T SrcLen) inline static
Definition at line 370 of file MicrosoftPlatformString.h.
References FORCEINLINE, Src, and Strncat().
Strncat() [3/3]
FORCEINLINE WIDECHAR * FMicrosoftPlatformString::Strncat (WIDECHAR * Dest, const WIDECHAR * Src, SIZE_T SrcLen) inline static
Definition at line 92 of file MicrosoftPlatformString.h.
References FORCEINLINE, Src, and Strlen().
Referenced by Strncat().
Strncmp() [1/9]
FORCEINLINE int32 FMicrosoftPlatformString::Strncmp (const ANSICHAR * String1, const ANSICHAR * String2, SIZE_T Count) inline static
Definition at line 243 of file MicrosoftPlatformString.h.
References Count, and FORCEINLINE.
Strncmp() [2/9]
int32 FGenericPlatformString::Strncmp (const ANSICHAR * String1, const UTF8CHAR * String2, SIZE_T Count) static
Strncmp() [3/9]
int32 FGenericPlatformString::Strncmp (const ANSICHAR * String1, const WIDECHAR * String2, SIZE_T Count) static
Strncmp() [4/9]
int32 FGenericPlatformString::Strncmp (const UTF8CHAR * String1, const ANSICHAR * String2, SIZE_T Count) static
Strncmp() [5/9]
FORCEINLINE int32 FMicrosoftPlatformString::Strncmp (const UTF8CHAR * String1, const UTF8CHAR * String2, SIZE_T Count) inline static
Definition at line 380 of file MicrosoftPlatformString.h.
References Count, FORCEINLINE, and Strncmp().
Strncmp() [6/9]
int32 FGenericPlatformString::Strncmp (const UTF8CHAR * String1, const WIDECHAR * String2, SIZE_T Count) static
Strncmp() [7/9]
int32 FGenericPlatformString::Strncmp (const WIDECHAR * String1, const ANSICHAR * String2, SIZE_T Count) static
Strncmp() [8/9]
int32 FGenericPlatformString::Strncmp (const WIDECHAR * String1, const UTF8CHAR * String2, SIZE_T Count) static
Strncmp() [9/9]
FORCEINLINE int32 FMicrosoftPlatformString::Strncmp (const WIDECHAR * String1, const WIDECHAR * String2, SIZE_T Count) inline static
Definition at line 117 of file MicrosoftPlatformString.h.
References Count, and FORCEINLINE.
Referenced by Strncmp().
Strncpy() [1/3]
FORCEINLINE ANSICHAR * FMicrosoftPlatformString::Strncpy (ANSICHAR * Dest, const ANSICHAR * Src, SIZE_T MaxLen) inline static
Definition at line 214 of file MicrosoftPlatformString.h.
References FORCEINLINE, and Src.
Strncpy() [2/3]
PRAGMA_ENABLE_DEPRECATION_WARNINGS FORCEINLINE UTF8CHAR * FMicrosoftPlatformString::Strncpy (UTF8CHAR * Dest, const UTF8CHAR * Src, SIZE_T MaxLen) inline static
Definition at line 351 of file MicrosoftPlatformString.h.
References FORCEINLINE, Src, and Strncpy().
Strncpy() [3/3]
FORCEINLINE WIDECHAR * FMicrosoftPlatformString::Strncpy (WIDECHAR * Dest, const WIDECHAR * Src, SIZE_T MaxLen) inline static
Definition at line 73 of file MicrosoftPlatformString.h.
References FORCEINLINE, and Src.
Referenced by Strncpy().
Strnlen() [1/4]
FORCEINLINE int32 FMicrosoftPlatformString::Strnlen (const ANSICHAR * String, SIZE_T StringSize) inline static
Definition at line 253 of file MicrosoftPlatformString.h.
References FORCEINLINE, String, and StringSize().
Strnlen() [2/4]
FORCEINLINE int32 FMicrosoftPlatformString::Strnlen (const UCS2CHAR * String, SIZE_T StringSize) inline static
Definition at line 328 of file MicrosoftPlatformString.h.
References FORCEINLINE, String, and StringSize().
Strnlen() [3/4]
FORCEINLINE int32 FMicrosoftPlatformString::Strnlen (const UTF8CHAR * String, SIZE_T StringSize) inline static
Definition at line 390 of file MicrosoftPlatformString.h.
References FORCEINLINE, String, StringSize(), and Strnlen().
Strnlen() [4/4]
FORCEINLINE int32 FMicrosoftPlatformString::Strnlen (const WIDECHAR * String, SIZE_T StringSize) inline static
Definition at line 127 of file MicrosoftPlatformString.h.
References FORCEINLINE, String, and StringSize().
Referenced by Strnlen().
Strrchr() [1/3]
FORCEINLINE const ANSICHAR * FMicrosoftPlatformString::Strrchr (const ANSICHAR * String, ANSICHAR C) inline static
Definition at line 268 of file MicrosoftPlatformString.h.
References FORCEINLINE, and String.
Strrchr() [2/3]
FORCEINLINE const UTF8CHAR * FMicrosoftPlatformString::Strrchr (const UTF8CHAR * String, UTF8CHAR C) inline static
Definition at line 405 of file MicrosoftPlatformString.h.
References FORCEINLINE, String, and Strrchr().
Strrchr() [3/3]
FORCEINLINE const WIDECHAR * FMicrosoftPlatformString::Strrchr (const WIDECHAR * String, WIDECHAR C) inline static
Definition at line 142 of file MicrosoftPlatformString.h.
References FORCEINLINE, and String.
Referenced by Strrchr().
Strstr() [1/3]
FORCEINLINE const ANSICHAR * FMicrosoftPlatformString::Strstr (const ANSICHAR * String, const ANSICHAR * Find) inline static
Definition at line 258 of file MicrosoftPlatformString.h.
References Find, FORCEINLINE, and String.
Strstr() [2/3]
FORCEINLINE const UTF8CHAR * FMicrosoftPlatformString::Strstr (const UTF8CHAR * String, const UTF8CHAR * Find) inline static
Definition at line 395 of file MicrosoftPlatformString.h.
References Find, FORCEINLINE, String, and Strstr().
Strstr() [3/3]
FORCEINLINE const WIDECHAR * FMicrosoftPlatformString::Strstr (const WIDECHAR * String, const WIDECHAR * Find) inline static
Definition at line 132 of file MicrosoftPlatformString.h.
References Find, FORCEINLINE, and String.
Referenced by Strstr().
Strtoi() [1/3]
FORCEINLINE int32 FMicrosoftPlatformString::Strtoi (const ANSICHAR * Start, ANSICHAR ** End, int32 Base) inline static
Definition at line 293 of file MicrosoftPlatformString.h.
References End, and FORCEINLINE.
Strtoi() [2/3]
FORCEINLINE int32 FMicrosoftPlatformString::Strtoi (const UTF8CHAR * Start, UTF8CHAR ** End, int32 Base) inline static
Definition at line 430 of file MicrosoftPlatformString.h.
References End, FORCEINLINE, and Strtoi().
Strtoi() [3/3]
FORCEINLINE int32 FMicrosoftPlatformString::Strtoi (const WIDECHAR * Start, WIDECHAR ** End, int32 Base) inline static
Definition at line 167 of file MicrosoftPlatformString.h.
References End, and FORCEINLINE.
Referenced by Strtoi().
Strtoi64() [1/3]
FORCEINLINE int64 FMicrosoftPlatformString::Strtoi64 (const ANSICHAR * Start, ANSICHAR ** End, int32 Base) inline static
Definition at line 298 of file MicrosoftPlatformString.h.
References End, and FORCEINLINE.
Strtoi64() [2/3]
FORCEINLINE int64 FMicrosoftPlatformString::Strtoi64 (const UTF8CHAR * Start, UTF8CHAR ** End, int32 Base) inline static
Definition at line 435 of file MicrosoftPlatformString.h.
References End, FORCEINLINE, and Strtoi64().
Strtoi64() [3/3]
FORCEINLINE int64 FMicrosoftPlatformString::Strtoi64 (const WIDECHAR * Start, WIDECHAR ** End, int32 Base) inline static
Definition at line 172 of file MicrosoftPlatformString.h.
References End, and FORCEINLINE.
Referenced by Strtoi64().
Strtok() [1/3]
FORCEINLINE ANSICHAR * FMicrosoftPlatformString::Strtok (ANSICHAR * StrToken, const ANSICHAR * Delim, ANSICHAR ** Context) inline static
Definition at line 308 of file MicrosoftPlatformString.h.
References FORCEINLINE.
Strtok() [2/3]
FORCEINLINE UTF8CHAR * FMicrosoftPlatformString::Strtok (UTF8CHAR * StrToken, const UTF8CHAR * Delim, UTF8CHAR ** Context) inline static
Definition at line 445 of file MicrosoftPlatformString.h.
References FORCEINLINE, and Strtok().
Strtok() [3/3]
FORCEINLINE WIDECHAR * FMicrosoftPlatformString::Strtok (WIDECHAR * StrToken, const WIDECHAR * Delim, WIDECHAR ** Context) inline static
Definition at line 182 of file MicrosoftPlatformString.h.
References FORCEINLINE.
Referenced by Strtok().
Strtoui64() [1/3]
FORCEINLINE uint64 FMicrosoftPlatformString::Strtoui64 (const ANSICHAR * Start, ANSICHAR ** End, int32 Base) inline static
Definition at line 303 of file MicrosoftPlatformString.h.
References End, and FORCEINLINE.
Strtoui64() [2/3]
FORCEINLINE uint64 FMicrosoftPlatformString::Strtoui64 (const UTF8CHAR * Start, UTF8CHAR ** End, int32 Base) inline static
Definition at line 440 of file MicrosoftPlatformString.h.
References End, FORCEINLINE, and Strtoui64().
Strtoui64() [3/3]
FORCEINLINE uint64 FMicrosoftPlatformString::Strtoui64 (const WIDECHAR * Start, WIDECHAR ** End, int32 Base) inline static
Definition at line 177 of file MicrosoftPlatformString.h.
References End, and FORCEINLINE.
Referenced by Strtoui64().
Strupr()
template<typename CharType> CharType * FMicrosoftPlatformString::Strupr (CharType * Dest, SIZE_T DestCount) inline static
Definition at line 47 of file MicrosoftPlatformString.h.
References DestCount, and TChar< CharType >::ToUpper().
UE_DEPRECATED() [1/6]
FMicrosoftPlatformString::UE_DEPRECATED (5. 6, "Use Strncat instead. !!NOTE THAT STRNCAT takes SrcLen rather than DestCount. You must call Strncat(Dest, Src, DestCount - Strlen(Dest) - 1).")
References DestCount, FORCEINLINE, Src, and Strcat().
UE_DEPRECATED() [2/6]
FMicrosoftPlatformString::UE_DEPRECATED (5. 6, "Use Strncat instead. !!NOTE THAT STRNCAT takes SrcLen rather than DestSize. You must call Strncat(Dest, Src, DestCount - Strlen(Dest) - 1).")
References DestCount, FORCEINLINE, Src, and Strcat().
UE_DEPRECATED() [3/6]
FMicrosoftPlatformString::UE_DEPRECATED (5. 6, "Use Strncat instead. !!NOTE THAT STRNCAT takes SrcLen rather than DestSize. You must call Strncat(Dest, Src, DestCount - Strlen(Dest) - 1).")
References DestCount, FORCEINLINE, PRAGMA_DISABLE_DEPRECATION_WARNINGS, PRAGMA_ENABLE_DEPRECATION_WARNINGS, Src, and Strcat().
UE_DEPRECATED() [4/6]
FMicrosoftPlatformString::UE_DEPRECATED (5. 6, "Use Strncpy instead. Note that Strncpy has a behavior difference from Strcpy: it memzeroes the entire DestCount-sized buffer after the end of string.")
UE_DEPRECATED() [5/6]
FMicrosoftPlatformString::UE_DEPRECATED (5. 6, "Use Strncpy instead. Note that Strncpy has a behavior difference from Strcpy: it memzeroes the entire DestCount-sized buffer after the end of string.")
UE_DEPRECATED() [6/6]
FMicrosoftPlatformString::UE_DEPRECATED (5. 6, "Use Strncpy instead. Note that Strncpy has a behavior difference from Strcpy: it memzeroes the entire DestCount-sized buffer after the end of string.")
Field Documentation
DestCount
SIZE_T FMicrosoftPlatformString::DestCount
Definition at line 68 of file MicrosoftPlatformString.h.
Referenced by Strupr(), UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
Src [1/3]
SIZE_T const UTF8CHAR * FMicrosoftPlatformString::Src
Initial value:
{
        return (WIDECHAR*)_tcscpy(Dest, Src)
Definition at line 68 of file MicrosoftPlatformString.h.
Referenced by Strcat(), Strcat(), Strcat(), Strcpy(), Strcpy(), Strcpy(), Strncat(), Strncat(), Strncat(), Strncpy(), Strncpy(), Strncpy(), UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
Src [2/3]
SIZE_T const ANSICHAR* FMicrosoftPlatformString::Src
Initial value:
{
        return (ANSICHAR*)strcpy(Dest, Src)
Definition at line 209 of file MicrosoftPlatformString.h.
Src [3/3]
SIZE_T const UTF8CHAR* FMicrosoftPlatformString::Src
Initial value:
{
        PRAGMA_DISABLE_DEPRECATION_WARNINGS
        return (UTF8CHAR*)Strcpy((ANSICHAR*)Dest, DestCount, (const ANSICHAR*)Src)
Definition at line 344 of file MicrosoftPlatformString.h.
The documentation for this struct was generated from the following file:
Runtime/Core/Public/GenericPlatform/MicrosoftPlatformString.h