Unreal Engine 5.6 C++ API: Runtime/CoreUObject/Public/StructUtils/SharedStruct.h File Reference
SharedStruct.h File Reference
#include "StructUtils.h"
#include "StructUtils/InstancedStruct.h"
#include "StructUtils/StructUtilsTypes.h"
#include "SharedStruct.generated.h"
Data Structures
struct FStructSharedMemory
Holds the information and memory about a UStruct.
struct FStructSharedMemory::FStructSharedMemoryDeleter
struct TConstSharedStruct< BaseStructT >
TConstSharedStruct is a type-safe FConstSharedStruct wrapper against the given BaseStruct type.
struct TSharedStruct< BaseStructT >
TSharedStruct is a type-safe FSharedStruct wrapper against the given BaseStruct type.
struct TStructOpsTypeTraits< FConstSharedStruct >
struct TStructOpsTypeTraits< FSharedStruct >
Macros
#define UE_API COREUOBJECT_API
Functions
USTRUCT () struct FSharedStruct
FSharedStruct works similarly as a TSharedPtr<FInstancedStruct> but avoids the double pointer indirection.
Macro Definition Documentation
UE_API
#define UE_API COREUOBJECT_API
Definition at line 11 of file SharedStruct.h.
Function Documentation
USTRUCT()
USTRUCT () nodiscard
FSharedStruct works similarly as a TSharedPtr<FInstancedStruct> but avoids the double pointer indirection.
FConstSharedStruct is the same as the FSharedStruct but restricts the API to return a const struct type.
(One pointer for the FInstancedStruct and one pointer for the struct memory it is wrapping). Also note that because of its implementation, it is not possible for now to go from a struct reference or struct view back to a shared struct.
This struct type is also convertible to a FStructView / FConstStructView, and like FInstancedStruct, it is the preferable way of passing it as a parameter. If the calling code would like to keep a shared pointer to the struct, you may pass the FSharedStruct as a parameter, but it is recommended to pass it as a "const FSharedStruct&" to limit the unnecessary recounting.
A 'const FSharedStruct' cannot be made to point at another instance of a struct, whilst a vanilla FSharedStruct can. In either case, the shared struct memory /data is mutable.
A 'const FConstSharedStruct' cannot be made to point at another instance of a struct, whilst a vanilla FConstSharedStruct can. In either case, the struct data is immutable.
See FSharedStruct for more information.
Copy constructors
Assignment operators
For StructOpsTypeTraits
Returns struct type.
Returns a mutable pointer to struct memory.
Reset to empty.
Initializes from a templated struct type. This will create a new instance of the shared struct memory.
Initializes from templated struct instance. This will create a new instance of the shared struct memory.
Initializes from other related struct types. This will create a new instance of the shared struct memory.
Initializes from a struct type and optional data. This will create a new instance of the shared struct memory.
Initializes from struct type and emplace args. This will create a new instance of the shared struct memory.
Creates a new FSharedStruct from a templated struct type. This will create a new instance of the shared struct memory.
Creates a new FSharedStruct from templated struct instance. This will create a new instance of the shared struct memory.
Creates a new FSharedStruct from struct type and optional instance memory. This will create a new instance of the shared struct memory.
Creates a new FSharedStruct from the templated type and forward all arguments to constructor. This will create a new instance of the shared struct memory.
Returns reference to the struct, this getter assumes that all data is valid.
Returns pointer to the struct, or nullptr if cast is not valid.
Returns True if the struct is valid.
Comparison operators. Note: it does not compare the internal structure itself
Determines whether Other contains the same values as this
Returns
whether the values stored are equal
For StructOpsTypeTraits
Returns struct type.
Returns const pointer to struct memory.
Reset to empty.
Initializes from a templated struct type.
Initializes from templated struct instance. This will create a new instance of the shared struct memory.
Initializes from other related struct types. This will create a new instance of the shared struct memory.
Initializes from a struct type and optional data. This will create a new instance of the shared struct memory.
Initializes from struct type and emplace args. This will create a new instance of the shared struct memory.
Creates a new FSharedStruct from a templated struct type. This will create a new instance of the shared struct memory.
Creates a new FSharedStruct from templated struct instance. This will create a new instance of the shared struct memory.
Creates a new FSharedStruct from a struct type and optional data. This will create a new instance of the shared struct memory.
Creates a new FSharedStruct from the templated type and forward all arguments to constructor. This will create a new instance of the shared struct memory.
Returns const reference to the struct, this getter assumes that all data is valid.
Returns const pointer to the struct, or nullptr if cast is not valid.
Returns True if the struct is valid.
Comparison operators. Note: it does not compare the internal structure itself
Determines whether Other contains the same values as this
Returns
whether the values stored are equal
Definition at line 156 of file SharedStruct.h.
References UE::StructUtils::CheckStructType(), UE::StructUtils::CheckWrapperType(), FStructSharedMemory::Create(), FStructSharedMemory::CreateArgs(), Forward(), GENERATED_BODY, TBaseStructureBase< T, bHasStaticStruct >::Get(), TObjectPtr< T >::Get(), UE::StructUtils::GetStructPtr(), UE::StructUtils::GetStructRef(), Identical, IsValid(), operator!=(), operator=(), operator==(), Other, Reset, ScriptStruct, Struct, and UE_API.