Unreal Engine 5.6 C++ API: FCurveEditorScreenSpaceV Struct Reference
FCurveEditorScreenSpaceV Struct Reference
Utility struct used for converting to/from curve editor screen space.
#include "CurveEditorScreenSpace.h"
Public Member Functions
FCurveEditorScreenSpaceV (double InPixelHeight, double InOutputMin, double InOutputMax)
Construction from a physical size, and input/output range.
FORCEINLINE double GetOutputMax () const
Get the maximum output value displayed on the screen.
FORCEINLINE double GetOutputMin () const
Get the minimum output value displayed on the screen.
FORCEINLINE double GetPhysicalHeight () const
Get the physical height of the screen.
FORCEINLINE double PixelsPerOutput () const
Retrieve the number of slate units per output value.
FORCEINLINE double ScreenToValue (double ScreenPosition) const
Convert a vertical screen position in slate units to a value.
FCurveEditorScreenSpaceV ToCurveSpace (const FTransform2d &CurveTransform) const
Transform this screen space into a curve space using the specified transform.
double ValueToScreen (double InValue) const
Convert a value to a vertical screen position in slate units.
Private Attributes
double OutputMax
double OutputMin
double PixelHeight
Detailed Description
Utility struct used for converting to/from curve editor screen space.
Definition at line 92 of file CurveEditorScreenSpace.h.
Constructor & Destructor Documentation
FCurveEditorScreenSpaceV()
FCurveEditorScreenSpaceV::FCurveEditorScreenSpaceV (double InPixelHeight, double InOutputMin, double InOutputMax) inline
Construction from a physical size, and input/output range.
Definition at line 97 of file CurveEditorScreenSpace.h.
References ensure, Max, OutputMax, OutputMin, and PixelHeight.
Referenced by FCurveEditorScreenSpace::FCurveEditorScreenSpace(), FCurveEditorScreenSpace::ToCurveSpace(), and ToCurveSpace().
Member Function Documentation
GetOutputMax()
FORCEINLINE double FCurveEditorScreenSpaceV::GetOutputMax () const inline
Get the maximum output value displayed on the screen.
Definition at line 135 of file CurveEditorScreenSpace.h.
References FORCEINLINE, and OutputMax.
Referenced by FCurveEditorScreenSpace::operator==().
GetOutputMin()
FORCEINLINE double FCurveEditorScreenSpaceV::GetOutputMin () const inline
Get the minimum output value displayed on the screen.
Definition at line 133 of file CurveEditorScreenSpace.h.
References FORCEINLINE, and OutputMin.
Referenced by FCurveEditorScreenSpace::operator==().
GetPhysicalHeight()
FORCEINLINE double FCurveEditorScreenSpaceV::GetPhysicalHeight () const inline
Get the physical height of the screen.
Definition at line 137 of file CurveEditorScreenSpace.h.
References FORCEINLINE, and PixelHeight.
Referenced by FCurveEditorScreenSpace::GetPhysicalSize(), and FCurveEditorScreenSpace::operator==().
PixelsPerOutput()
FORCEINLINE double FCurveEditorScreenSpaceV::PixelsPerOutput () const inline
Retrieve the number of slate units per output value.
Definition at line 124 of file CurveEditorScreenSpace.h.
References FORCEINLINE, FMath::Max, OutputMax, OutputMin, and PixelHeight.
Referenced by ScreenToValue(), and ValueToScreen().
ScreenToValue()
FORCEINLINE double FCurveEditorScreenSpaceV::ScreenToValue (double ScreenPosition) const inline
Convert a vertical screen position in slate units to a value.
Definition at line 110 of file CurveEditorScreenSpace.h.
References FORCEINLINE, OutputMin, PixelHeight, PixelsPerOutput(), and ScreenPosition.
ToCurveSpace()
FCurveEditorScreenSpaceV FCurveEditorScreenSpaceV::ToCurveSpace (const FTransform2d & CurveTransform) const inline
Transform this screen space into a curve space using the specified transform.
Definition at line 144 of file CurveEditorScreenSpace.h.
References FCurveEditorScreenSpaceV(), TMatrix2x2< T >::GetMatrix(), TTransform2< T >::GetMatrix(), TTransform2< T >::GetTranslation(), OutputMax, OutputMin, and PixelHeight.
Referenced by FCurveEditorScreenSpace::ToCurveSpace().
ValueToScreen()
double FCurveEditorScreenSpaceV::ValueToScreen (double InValue) const inline
Convert a value to a vertical screen position in slate units.
Definition at line 116 of file CurveEditorScreenSpace.h.
References OutputMin, PixelHeight, and PixelsPerOutput().
Field Documentation
OutputMax
double FCurveEditorScreenSpaceV::OutputMax private
Definition at line 160 of file CurveEditorScreenSpace.h.
Referenced by FCurveEditorScreenSpaceV(), GetOutputMax(), PixelsPerOutput(), and ToCurveSpace().
OutputMin
double FCurveEditorScreenSpaceV::OutputMin private
Definition at line 160 of file CurveEditorScreenSpace.h.
Referenced by FCurveEditorScreenSpaceV(), GetOutputMin(), PixelsPerOutput(), ScreenToValue(), ToCurveSpace(), and ValueToScreen().
PixelHeight
double FCurveEditorScreenSpaceV::PixelHeight private
Definition at line 159 of file CurveEditorScreenSpace.h.
Referenced by FCurveEditorScreenSpaceV(), GetPhysicalHeight(), PixelsPerOutput(), ScreenToValue(), ToCurveSpace(), and ValueToScreen().
The documentation for this struct was generated from the following file:
Editor/CurveEditor/Public/CurveEditorScreenSpace.h