Unreal Engine 5.6 C++ API: FAINamedID< TCounter > Struct Template Reference
FAINamedID< TCounter > Struct Template Reference
TCounter needs to supply following functions: default constructor typedef X Type; where X is an integer type to be used as ID's internal type TCounter::Type GetNextAvailableID() - returns next available ID and advances the internal counter uint32 GetSize() const - returns number of unique IDs created so far OnIndexForced(TCounter::Type Index) - called when given Index has been force-used.
#include "AITypes.h"
Public Member Functions
FAINamedID ()
FAINamedID (const FAINamedID &Other)
FAINamedID (const FName &InName)
bool IsValid () const
operator typename TCounter::Type () const
FAINamedID & operator= (const FAINamedID &Other)
Static Public Member Functions
static uint32 GetSize ()
static FAINamedID< TCounter > InvalidID ()
Data Fields
const TCounter::Type Index
const FName Name
Protected Member Functions
FAINamedID (const FName &InName, typename TCounter::Type InIndex)
Static Protected Member Functions
static TCounter & GetCounter ()
Static Private Attributes
static AIMODULE_API TCounter Counter
Friends
FORCEINLINE uint32 GetTypeHash (const FAINamedID &ID)
Detailed Description
template<typename TCounter>
struct FAINamedID< TCounter >
TCounter needs to supply following functions: default constructor typedef X Type; where X is an integer type to be used as ID's internal type TCounter::Type GetNextAvailableID() - returns next available ID and advances the internal counter uint32 GetSize() const - returns number of unique IDs created so far OnIndexForced(TCounter::Type Index) - called when given Index has been force-used.
Counter may need to update "next available ID"
Definition at line 171 of file AITypes.h.
Constructor & Destructor Documentation
FAINamedID() [1/4]
template<typename TCounter> FAINamedID< TCounter >::FAINamedID (const FName & InName, typename TCounter::Type InIndex) inline protected
Definition at line 184 of file AITypes.h.
FAINamedID() [2/4]
template<typename TCounter> FAINamedID< TCounter >::FAINamedID (const FName & InName) inline
Definition at line 191 of file AITypes.h.
FAINamedID() [3/4]
template<typename TCounter> FAINamedID< TCounter >::FAINamedID (const FAINamedID< TCounter > & Other) inline
Definition at line 195 of file AITypes.h.
FAINamedID() [4/4]
template<typename TCounter> FAINamedID< TCounter >::FAINamedID () inline
Definition at line 205 of file AITypes.h.
Referenced by FAINamedID< FAIResCounter >::operator=().
Member Function Documentation
GetCounter()
template<typename TCounter> TCounter & FAINamedID< TCounter >::GetCounter () inline static protected
Definition at line 178 of file AITypes.h.
Referenced by FAINamedID< FAIResCounter >::FAINamedID(), and FAINamedID< FAIResCounter >::GetSize().
GetSize()
template<typename TCounter> uint32 FAINamedID< TCounter >::GetSize () inline static
Definition at line 212 of file AITypes.h.
InvalidID()
template<typename TCounter> FAINamedID< TCounter > FAINamedID< TCounter >::InvalidID () inline static
Definition at line 214 of file AITypes.h.
Referenced by FAINamedID< FAIResCounter >::IsValid().
IsValid()
template<typename TCounter> bool FAINamedID< TCounter >::IsValid () const inline
Definition at line 210 of file AITypes.h.
operator typename TCounter::Type()
template<typename TCounter> FAINamedID< TCounter >::operator typename TCounter::Type () const inline
Definition at line 209 of file AITypes.h.
operator=()
template<typename TCounter> FAINamedID & FAINamedID< TCounter >::operator= (const FAINamedID< TCounter > & Other) inline
Definition at line 199 of file AITypes.h.
Friends And Related Symbol Documentation
GetTypeHash
template<typename TCounter> FORCEINLINE uint32 GetTypeHash (const FAINamedID< TCounter > & ID) friend
Definition at line 220 of file AITypes.h.
Referenced by FAINamedID< FAIResCounter >::GetTypeHash.
Field Documentation
Counter
template<typename TCounter> AIMODULE_API TCounter FAINamedID< TCounter >::Counter static private
Definition at line 176 of file AITypes.h.
Index
template<typename TCounter> const TCounter::Type FAINamedID< TCounter >::Index
Definition at line 173 of file AITypes.h.
Referenced by FAIResourcesSet::AddResource(), FAIResourcesSet::ContainsResource(), and FAIResourcesSet::RemoveResource().
Name
template<typename TCounter> const FName FAINamedID< TCounter >::Name
Definition at line 174 of file AITypes.h.
The documentation for this struct was generated from the following file:
Runtime/AIModule/Classes/AITypes.h