Unreal Engine 5.6 C++ API: FUObjectItem Struct Reference
FUObjectItem Struct Reference
Single item in the UObject array.
#include "UObjectArray.h"
Public Member Functions
FUObjectItem ()
FUObjectItem (const FUObjectItem &)=delete
FUObjectItem (FUObjectItem &&)=delete
~FUObjectItem ()
void AddRef ()
FORCEINLINE void ClearFlags (EInternalObjectFlags FlagsToClear)
FORCEINLINE void ClearGarbage ()
FORCEINLINE void ClearRootSet ()
FORCEINLINE int32 GetClusterIndex () const
Decodes the cluster index from the ClusterRootIndex variable.
FORCEINLINE EInternalObjectFlags GetFlags () const
FORCEINLINE class UObjectBase * GetObject () const
FORCEINLINE int32 GetOwnerIndex () const
FORCEINLINE int32 GetRefCount () const
FORCEINLINE int32 GetSerialNumber () const
FORCEINLINE bool HasAllFlags (EInternalObjectFlags InFlags) const
FORCEINLINE bool HasAnyFlags (EInternalObjectFlags InFlags) const
FORCEINLINE bool IsGarbage () const
FORCEINLINE bool IsRootSet () const
FORCEINLINE bool IsUnreachable () const
FUObjectItem & operator= (const FUObjectItem &)=delete
FUObjectItem & operator= (FUObjectItem &&)=delete
void ReleaseRef ()
FORCEINLINE void SetClusterIndex (int32 ClusterIndex)
Encodes the cluster index in the ClusterRootIndex variable.
FORCEINLINE void SetFlags (EInternalObjectFlags FlagsToSet)
FORCEINLINE void SetGarbage ()
FORCEINLINE void SetObject (class UObjectBase *InObject)
FORCEINLINE void SetOwnerIndex (int32 OwnerIndex)
FORCEINLINE void SetRootSet ()
FORCEINLINE bool ThisThreadAtomicallyClearedFlag (EInternalObjectFlags FlagToClear)
Uses atomics to clear the specified flag(s).
FORCEINLINE bool ThisThreadAtomicallySetFlag (EInternalObjectFlags FlagToSet)
Uses atomics to set the specified flag(s)
UE_DEPRECATED (5.4, "ClearPendingKill() should no longer be used. Use ClearGarbage() instead.") FORCEINLINE void ClearPendingKill()
UE_DEPRECATED (5.4, "IsPendingKill() should no longer be used. Use IsGarbage() instead.") FORCEINLINE bool IsPendingKill() const
UE_DEPRECATED (5.4, "SetPendingKill() should no longer be used. Use SetGarbage() instead.") FORCEINLINE void SetPendingKill()
UE_DEPRECATED (5.5, "ClearUnreachable() can only be used by the garbage collector.") FORCEINLINE void ClearUnreachable()
UE_DEPRECATED (5.5, "FastMarkAsReachableAndClearReachaleInClusterInterlocked_ForGC() can only be used by the garbage collector.") 1 void FastMarkAsReachableAndClearReachaleInClusterInterlocked_ForGC()
UE_DEPRECATED (5.5, "FastMarkAsReachableInterlocked_ForGC() can only be used by the garbage collector.") 1 void FastMarkAsReachableInterlocked_ForGC()
UE_DEPRECATED (5.5, "IsMaybeUnreachable() can only be used by the garbage collector.") 1 bool IsMaybeUnreachable() const
UE_DEPRECATED (5.5, "MarkAsReachableInterlocked_ForGC() can only be used by the garbage collector.") 1 bool MarkAsReachableInterlocked_ForGC()
Mark this object item as Reachable and clear MaybeUnreachable flag.
UE_DEPRECATED (5.5, "OffsetOfFlags() can only be used by the garbage collector.") FORCEINLINE static const expr
UE_DEPRECATED (5.5, "SetMaybeUnreachable() can only be used by the garbage collector.") 1 void SetMaybeUnreachable()
UE_DEPRECATED (5.5, "SetUnreachable() can only be used by the garbage collector.") FORCEINLINE void SetUnreachable()
UE_DEPRECATED (5.5, "ThisThreadAtomicallyClearedFlag_ForGC() can only be used by the garbage collector. Use ThisThreadAtomicallyClearedFlag instead.") FORCEINLINE bool ThisThreadAtomicallyClearedFlag_ForGC(EInternalObjectFlags FlagToClear)
Uses atomics to clear the specified flag(s).
UE_DEPRECATED (5.5, "ThisThreadAtomicallyClearedRFUnreachable() can only be used by the garbage collector.") FORCEINLINE bool ThisThreadAtomicallyClearedRFUnreachable()
UE_DEPRECATED (5.5, "ThisThreadAtomicallySetFlag_ForGC() can only be used by the garbage collector. Use ThisThreadAtomicallySetFlag instead.") FORCEINLINE bool ThisThreadAtomicallySetFlag_ForGC(EInternalObjectFlags FlagToSet)
Uses atomics to set the specified flag(s).
Data Fields
union {
uint32 ObjectPtrLow
};
int32 ClusterRootIndex
int32 RefCount
int32 SerialNumber
Private Member Functions
FORCEINLINE bool AtomicallyClearFlag_ForGC (EInternalObjectFlags FlagToClear)
Uses atomics to clear the specified flag(s).
FORCEINLINE bool AtomicallySetFlag_ForGC (EInternalObjectFlags FlagToSet)
Uses atomics to set the specified flag(s).
bool ClearRootFlags (EInternalObjectFlags FlagsToClear)
FORCEINLINE int32 GetFlagsInternal () const
FORCEINLINE int32 GetRefCountInternal () const
bool SetRootFlags (EInternalObjectFlags FlagsToSet)
Private Attributes
int32 Flags
Static Private Attributes
static constexpr int32 FlagsMask = 0xFFFFFFFF << int(EInternalObjectFlags_MinFlagBitIndex)
static constexpr int32 PtrMask = ~FlagsMask
static constexpr int32 UObjectAlignment = 8
static constexpr int32 UObjectPtrTrailingZeroes = FMath::CountTrailingZerosConstExpr(UObjectAlignment)
Friends
class FUObjectArray
class UE::GC::Private::FGCFlags
Detailed Description
Single item in the UObject array.
Definition at line 49 of file UObjectArray.h.
Constructor & Destructor Documentation
FUObjectItem() [1/3]
FUObjectItem::FUObjectItem () inline
Definition at line 110 of file UObjectArray.h.
References ClusterRootIndex, ENABLE_STATNAMEDEVENTS_UOBJECT, Flags, RefCount, and SerialNumber.
Referenced by FUObjectItem(), FUObjectItem(), operator=(), operator=(), and UE_DEPRECATED().
~FUObjectItem()
FUObjectItem::~FUObjectItem () inline
Definition at line 120 of file UObjectArray.h.
FUObjectItem() [2/3]
FUObjectItem::FUObjectItem (FUObjectItem &&) delete
References FUObjectItem().
FUObjectItem() [3/3]
FUObjectItem::FUObjectItem (const FUObjectItem &) delete
References FUObjectItem().
Member Function Documentation
AddRef()
void FUObjectItem::AddRef () inline
Definition at line 372 of file UObjectArray.h.
References GetFlags(), RefCount, RefCounted, ReleaseRef(), and SetRootFlags().
Referenced by ReleaseRef().
AtomicallyClearFlag_ForGC()
FORCEINLINE bool FUObjectItem::AtomicallyClearFlag_ForGC (EInternalObjectFlags FlagToClear) inline private
Uses atomics to clear the specified flag(s).
GC internal version
Parameters
FlagsToClear
Returns
True if this call cleared the flag, false if it has been cleared by another thread.
Definition at line 488 of file UObjectArray.h.
References Flags, FORCEINLINE, and GetFlagsInternal().
Referenced by ClearGarbage(), ThisThreadAtomicallyClearedFlag(), UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
AtomicallySetFlag_ForGC()
FORCEINLINE bool FUObjectItem::AtomicallySetFlag_ForGC (EInternalObjectFlags FlagToSet) inline private
Uses atomics to set the specified flag(s).
GC internal version.
Parameters
FlagToSet
Returns
True if this call set the flag, false if it has been set by another thread.
Definition at line 462 of file UObjectArray.h.
References Flags, FORCEINLINE, and GetFlagsInternal().
Referenced by SetGarbage(), ThisThreadAtomicallySetFlag(), UE_DEPRECATED(), and UE_DEPRECATED().
ClearFlags()
FORCEINLINE void FUObjectItem::ClearFlags (EInternalObjectFlags FlagsToClear) inline
Definition at line 211 of file UObjectArray.h.
References FORCEINLINE, and ThisThreadAtomicallyClearedFlag().
Referenced by UObjectBaseUtility::ClearInternalFlags().
ClearGarbage()
FORCEINLINE void FUObjectItem::ClearGarbage () inline
Definition at line 329 of file UObjectArray.h.
References AtomicallyClearFlag_ForGC(), FORCEINLINE, and Garbage.
Referenced by UE_DEPRECATED().
ClearRootFlags()
bool FUObjectItem::ClearRootFlags (EInternalObjectFlags FlagsToClear) private
Referenced by ReleaseRef(), and ThisThreadAtomicallyClearedFlag().
ClearRootSet()
FORCEINLINE void FUObjectItem::ClearRootSet () inline
Definition at line 358 of file UObjectArray.h.
References FORCEINLINE, RootSet, and ThisThreadAtomicallyClearedFlag().
GetClusterIndex()
FORCEINLINE int32 FUObjectItem::GetClusterIndex () const inline
Decodes the cluster index from the ClusterRootIndex variable.
Definition at line 179 of file UObjectArray.h.
References checkSlow, ClusterRootIndex, and FORCEINLINE.
GetFlags()
FORCEINLINE EInternalObjectFlags FUObjectItem::GetFlags () const inline
Definition at line 202 of file UObjectArray.h.
References FlagsMask, FORCEINLINE, and GetFlagsInternal().
Referenced by AddRef(), UObjectBaseUtility::AtomicallyClearInternalFlags(), UObjectBaseUtility::ClearInternalFlags(), and UObjectBaseUtility::SetInternalFlags().
GetFlagsInternal()
FORCEINLINE int32 FUObjectItem::GetFlagsInternal () const inline private
Definition at line 444 of file UObjectArray.h.
References Flags, and FORCEINLINE.
Referenced by AtomicallyClearFlag_ForGC(), AtomicallySetFlag_ForGC(), GetFlags(), HasAllFlags(), HasAnyFlags(), IsGarbage(), IsRootSet(), and IsUnreachable().
GetObject()
FORCEINLINE class UObjectBase * FUObjectItem::GetObject () const inline
Definition at line 137 of file UObjectArray.h.
References Flags, FORCEINLINE, Object, ObjectPtrLow, PRAGMA_DISABLE_DEPRECATION_WARNINGS, PRAGMA_ENABLE_DEPRECATION_WARNINGS, PtrMask, and UObjectPtrTrailingZeroes.
Referenced by FUObjectArray::TIterator::Advance(), FIndexToObject::IndexToObject(), FUObjectArray::IndexToObject(), FWeakObjectPtr::Internal_Get(), TObjectIteratorBase< EObjectIteratorThreadSafetyOptions::None >::operator*(), and TObjectIteratorBase< EObjectIteratorThreadSafetyOptions::None >::operator->().
GetOwnerIndex()
FORCEINLINE int32 FUObjectItem::GetOwnerIndex () const inline
Definition at line 167 of file UObjectArray.h.
References ClusterRootIndex, and FORCEINLINE.
GetRefCount()
FORCEINLINE int32 FUObjectItem::GetRefCount () const inline
Definition at line 367 of file UObjectArray.h.
References FORCEINLINE, and RefCount.
GetRefCountInternal()
FORCEINLINE int32 FUObjectItem::GetRefCountInternal () const inline private
Definition at line 449 of file UObjectArray.h.
References FORCEINLINE, and RefCount.
GetSerialNumber()
FORCEINLINE int32 FUObjectItem::GetSerialNumber () const inline
Definition at line 185 of file UObjectArray.h.
References FORCEINLINE, and SerialNumber.
Referenced by FUObjectArray::GetSerialNumber(), and FWeakObjectPtr::SerialNumbersMatch().
HasAllFlags()
FORCEINLINE bool FUObjectItem::HasAllFlags (EInternalObjectFlags InFlags) const inline
Definition at line 294 of file UObjectArray.h.
References FORCEINLINE, and GetFlagsInternal().
HasAnyFlags()
FORCEINLINE bool FUObjectItem::HasAnyFlags (EInternalObjectFlags InFlags) const inline
Definition at line 289 of file UObjectArray.h.
References FORCEINLINE, and GetFlagsInternal().
Referenced by FUObjectArray::IndexToObject(), FWeakObjectPtr::Internal_GetObjectItem(), FUObjectArray::IsStale(), and FUObjectArray::IsValid().
IsGarbage()
FORCEINLINE bool FUObjectItem::IsGarbage () const inline
Definition at line 333 of file UObjectArray.h.
References FORCEINLINE, Garbage, and GetFlagsInternal().
Referenced by UE_DEPRECATED().
IsRootSet()
FORCEINLINE bool FUObjectItem::IsRootSet () const inline
Definition at line 362 of file UObjectArray.h.
References FORCEINLINE, GetFlagsInternal(), and RootSet.
IsUnreachable()
FORCEINLINE bool FUObjectItem::IsUnreachable () const inline
Definition at line 312 of file UObjectArray.h.
References FORCEINLINE, GetFlagsInternal(), and Unreachable.
Referenced by FUObjectArray::IsStale(), and FUObjectArray::IsValid().
operator=() [1/2]
FUObjectItem & FUObjectItem::operator= (const FUObjectItem &) delete
References FUObjectItem().
operator=() [2/2]
FUObjectItem & FUObjectItem::operator= (FUObjectItem &&) delete
References FUObjectItem().
ReleaseRef()
void FUObjectItem::ReleaseRef () inline
Definition at line 390 of file UObjectArray.h.
References AddRef(), check, ClearRootFlags(), RefCount, and RefCounted.
Referenced by AddRef().
SetClusterIndex()
FORCEINLINE void FUObjectItem::SetClusterIndex (int32 ClusterIndex) inline
Encodes the cluster index in the ClusterRootIndex variable.
Definition at line 173 of file UObjectArray.h.
References ClusterRootIndex, and FORCEINLINE.
SetFlags()
FORCEINLINE void FUObjectItem::SetFlags (EInternalObjectFlags FlagsToSet) inline
Definition at line 197 of file UObjectArray.h.
References FORCEINLINE, and ThisThreadAtomicallySetFlag().
Referenced by UObjectBaseUtility::SetInternalFlags().
SetGarbage()
FORCEINLINE void FUObjectItem::SetGarbage () inline
Definition at line 325 of file UObjectArray.h.
References AtomicallySetFlag_ForGC(), FORCEINLINE, and Garbage.
Referenced by UE_DEPRECATED().
SetObject()
FORCEINLINE void FUObjectItem::SetObject (class UObjectBase * InObject) inline
Definition at line 149 of file UObjectArray.h.
References Flags, FORCEINLINE, Object, ObjectPtrLow, PRAGMA_DISABLE_DEPRECATION_WARNINGS, PRAGMA_ENABLE_DEPRECATION_WARNINGS, and UObjectPtrTrailingZeroes.
SetOwnerIndex()
FORCEINLINE void FUObjectItem::SetOwnerIndex (int32 OwnerIndex) inline
Definition at line 162 of file UObjectArray.h.
References ClusterRootIndex, and FORCEINLINE.
SetRootFlags()
bool FUObjectItem::SetRootFlags (EInternalObjectFlags FlagsToSet) private
Referenced by AddRef(), and ThisThreadAtomicallySetFlag().
SetRootSet()
FORCEINLINE void FUObjectItem::SetRootSet () inline
Definition at line 354 of file UObjectArray.h.
References FORCEINLINE, RootSet, and ThisThreadAtomicallySetFlag().
ThisThreadAtomicallyClearedFlag()
FORCEINLINE bool FUObjectItem::ThisThreadAtomicallyClearedFlag (EInternalObjectFlags FlagToClear) inline
Uses atomics to clear the specified flag(s).
Parameters
FlagsToClear
Returns
True if this call cleared the flag, false if it has been cleared by another thread.
Definition at line 232 of file UObjectArray.h.
References AtomicallyClearFlag_ForGC(), checkf, ClearRootFlags(), EInternalObjectFlags_AllFlags, EInternalObjectFlags_ReachabilityFlags, EInternalObjectFlags_RootFlags, FORCEINLINE, RefCounted, and TEXT.
Referenced by UObjectBaseUtility::AtomicallyClearInternalFlags(), ClearFlags(), and ClearRootSet().
ThisThreadAtomicallySetFlag()
FORCEINLINE bool FUObjectItem::ThisThreadAtomicallySetFlag (EInternalObjectFlags FlagToSet) inline
Uses atomics to set the specified flag(s)
Parameters
FlagToSet
Returns
True if this call set the flag, false if it has been set by another thread.
Definition at line 269 of file UObjectArray.h.
References AtomicallySetFlag_ForGC(), checkf, EInternalObjectFlags_AllFlags, EInternalObjectFlags_ReachabilityFlags, EInternalObjectFlags_RootFlags, FORCEINLINE, RefCounted, SetRootFlags(), and TEXT.
Referenced by SetFlags(), and SetRootSet().
UE_DEPRECATED() [1/14]
FUObjectItem::UE_DEPRECATED (5. 4, "ClearPendingKill() should no longer be used. Use ClearGarbage() instead.") inline
Definition at line 343 of file UObjectArray.h.
References ClearGarbage(), and FORCEINLINE.
UE_DEPRECATED() [2/14]
FUObjectItem::UE_DEPRECATED (5. 4, "IsPendingKill() should no longer be used. Use IsGarbage() instead.") const inline
Definition at line 348 of file UObjectArray.h.
References FORCEINLINE, and IsGarbage().
UE_DEPRECATED() [3/14]
FUObjectItem::UE_DEPRECATED (5. 4, "SetPendingKill() should no longer be used. Use SetGarbage() instead.") inline
Definition at line 338 of file UObjectArray.h.
References FORCEINLINE, and SetGarbage().
UE_DEPRECATED() [4/14]
FUObjectItem::UE_DEPRECATED (5. 5, "ClearUnreachable() can only be used by the garbage collector.") inline
Definition at line 307 of file UObjectArray.h.
References AtomicallyClearFlag_ForGC(), FORCEINLINE, UE_DEPRECATED(), and Unreachable.
UE_DEPRECATED() [5/14]
FUObjectItem::UE_DEPRECATED (5. 5, "FastMarkAsReachableAndClearReachaleInClusterInterlocked_ForGC() can only be used by the garbage collector.")
References UE_DEPRECATED().
UE_DEPRECATED() [6/14]
FUObjectItem::UE_DEPRECATED (5. 5, "FastMarkAsReachableInterlocked_ForGC() can only be used by the garbage collector.")
UE_DEPRECATED() [7/14]
FUObjectItem::UE_DEPRECATED (5. 5, "IsMaybeUnreachable() can only be used by the garbage collector.") const
UE_DEPRECATED() [8/14]
FUObjectItem::UE_DEPRECATED (5. 5, "MarkAsReachableInterlocked_ForGC() can only be used by the garbage collector.")
Mark this object item as Reachable and clear MaybeUnreachable flag.
Only thread-safe for concurrent clear, not concurrent set+clear. Don't use during mark phase. For GC use only.
Returns
True if this call cleared MaybeUnreachable flag, false if it has been cleared by another thread.
References UE_DEPRECATED().
UE_DEPRECATED() [9/14]
FUObjectItem::UE_DEPRECATED (5. 5, "OffsetOfFlags() can only be used by the garbage collector.") const inline
Definition at line 437 of file UObjectArray.h.
References FUObjectItem(), Flags, FORCEINLINE, and UE_DEPRECATED().
UE_DEPRECATED() [10/14]
FUObjectItem::UE_DEPRECATED (5. 5, "SetMaybeUnreachable() can only be used by the garbage collector.")
UE_DEPRECATED() [11/14]
FUObjectItem::UE_DEPRECATED (5. 5, "SetUnreachable() can only be used by the garbage collector.") inline
Definition at line 299 of file UObjectArray.h.
References AtomicallySetFlag_ForGC(), FORCEINLINE, and Unreachable.
UE_DEPRECATED() [12/14]
FUObjectItem::UE_DEPRECATED (5. 5, "ThisThreadAtomicallyClearedFlag_ForGC() can only be used by the garbage collector. Use ThisThreadAtomicallyClearedFlag instead.") inline
Uses atomics to clear the specified flag(s).
GC internal version
Parameters
FlagsToClear
Returns
True if this call cleared the flag, false if it has been cleared by another thread.
Definition at line 221 of file UObjectArray.h.
References AtomicallyClearFlag_ForGC(), and FORCEINLINE.
Referenced by UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
UE_DEPRECATED() [13/14]
FUObjectItem::UE_DEPRECATED (5. 5, "ThisThreadAtomicallyClearedRFUnreachable() can only be used by the garbage collector.") inline
Definition at line 320 of file UObjectArray.h.
References AtomicallyClearFlag_ForGC(), FORCEINLINE, UE_DEPRECATED(), and Unreachable.
UE_DEPRECATED() [14/14]
FUObjectItem::UE_DEPRECATED (5. 5, "ThisThreadAtomicallySetFlag_ForGC() can only be used by the garbage collector. Use ThisThreadAtomicallySetFlag instead.") inline
Uses atomics to set the specified flag(s).
GC internal version.
Parameters
FlagToSet
Returns
True if this call set the flag, false if it has been set by another thread.
Definition at line 258 of file UObjectArray.h.
References AtomicallySetFlag_ForGC(), and FORCEINLINE.
Friends And Related Symbol Documentation
FUObjectArray
friend class FUObjectArray friend
Definition at line 51 of file UObjectArray.h.
References FUObjectArray.
Referenced by FUObjectArray.
UE::GC::Private::FGCFlags
friend class UE::GC::Private::FGCFlags friend
Definition at line 52 of file UObjectArray.h.
References Object, and UE::GC::Private::FGCFlags.
Referenced by UE::GC::Private::FGCFlags.
Field Documentation
[union]
union { ... } FUObjectItem
ClusterRootIndex
int32 FUObjectItem::ClusterRootIndex
Definition at line 90 of file UObjectArray.h.
Referenced by FUObjectItem(), GetClusterIndex(), GetOwnerIndex(), SetClusterIndex(), and SetOwnerIndex().
Flags
int32 FUObjectItem::Flags private
Definition at line 86 of file UObjectArray.h.
Referenced by FUObjectItem(), AtomicallyClearFlag_ForGC(), AtomicallySetFlag_ForGC(), GetFlagsInternal(), GetObject(), SetObject(), and UE_DEPRECATED().
FlagsMask
int32 FUObjectItem::FlagsMask = 0xFFFFFFFF << int(EInternalObjectFlags_MinFlagBitIndex) static constexpr private
Definition at line 81 of file UObjectArray.h.
Referenced by GetFlags().
ObjectPtrLow
uint32 FUObjectItem::ObjectPtrLow
Definition at line 61 of file UObjectArray.h.
Referenced by GetObject(), and SetObject().
PtrMask
int32 FUObjectItem::PtrMask = ~FlagsMask static constexpr private
Definition at line 82 of file UObjectArray.h.
Referenced by GetObject().
RefCount
int32 FUObjectItem::RefCount
Definition at line 94 of file UObjectArray.h.
Referenced by FUObjectItem(), AddRef(), GetRefCount(), GetRefCountInternal(), and ReleaseRef().
SerialNumber
int32 FUObjectItem::SerialNumber
Definition at line 92 of file UObjectArray.h.
Referenced by FUObjectItem(), and GetSerialNumber().
UObjectAlignment
int32 FUObjectItem::UObjectAlignment = 8 static constexpr private
Definition at line 78 of file UObjectArray.h.
UObjectPtrTrailingZeroes
int32 FUObjectItem::UObjectPtrTrailingZeroes = FMath::CountTrailingZerosConstExpr(UObjectAlignment) static constexpr private
Definition at line 79 of file UObjectArray.h.
Referenced by GetObject(), and SetObject().
The documentation for this struct was generated from the following file:
Runtime/CoreUObject/Public/UObject/UObjectArray.h