Unreal Engine 5.6 C++ API: FNetworkDemoHeader Struct Reference
FNetworkDemoHeader Struct Reference
#include "ReplayTypes.h"
Public Member Functions
FNetworkDemoHeader ()
PRAGMA_DISABLE_DEPRECATION_WARNINGS FNetworkDemoHeader (const FNetworkDemoHeader &)=default
FNetworkDemoHeader (FNetworkDemoHeader &&)=default
void CountBytes (FArchive &Ar) const
uint32 GetCustomVersion (const FGuid &VersionGuid) const
FNetworkDemoHeader & operator= (const FNetworkDemoHeader &)=default
FNetworkDemoHeader & operator= (FNetworkDemoHeader &&)=default
void SetDefaultNetworkVersions ()
UE_DEPRECATED (5.2, "No longer used in favor of custom versions, kept for backwards compatibility.") uint32 EngineNetworkProtocolVersion
UE_DEPRECATED (5.2, "No longer used in favor of custom versions, kept for backwards compatibility.") uint32 GameNetworkProtocolVersion
UE_DEPRECATED (5.2, "No longer used in favor of custom versions, kept for backwards compatibility.") uint32 Version
UE_DEPRECATED (5.2, "No longer used.") uint32 NetworkChecksum
Data Fields
EBuildConfiguration BuildConfig
EBuildTargetType BuildTarget
float CheckpointLimitInMS
FCustomVersionContainer CustomVersions
FEngineVersion EngineVersion
float FrameLimitInMS
TArray< FString > GameSpecificData
FGuid Guid
EReplayHeaderFlags HeaderFlags
TArray< FLevelNameAndTime > LevelNamesAndTimes
uint32 Magic
float MaxRecordHz
float MinRecordHz
int32 PackageVersionLicenseeUE
FPackageFileVersion PackageVersionUE
FString Platform
Friends
PRAGMA_ENABLE_DEPRECATION_WARNINGS friend FArchive & operator<< (FArchive &Ar, FNetworkDemoHeader &Header)
Detailed Description
Definition at line 177 of file ReplayTypes.h.
Constructor & Destructor Documentation
FNetworkDemoHeader() [1/3]
FNetworkDemoHeader::FNetworkDemoHeader ()
References FNetworkDemoHeader().
Referenced by FNetworkDemoHeader(), FNetworkDemoHeader(), FNetworkDemoHeader(), operator<<, operator=(), and operator=().
FNetworkDemoHeader() [2/3]
PRAGMA_DISABLE_DEPRECATION_WARNINGS FNetworkDemoHeader::FNetworkDemoHeader (const FNetworkDemoHeader &) default
References FNetworkDemoHeader().
FNetworkDemoHeader() [3/3]
FNetworkDemoHeader::FNetworkDemoHeader (FNetworkDemoHeader &&) default
References FNetworkDemoHeader().
Member Function Documentation
CountBytes()
void FNetworkDemoHeader::CountBytes (FArchive & Ar) const
References Ar, and CountBytes().
Referenced by CountBytes().
GetCustomVersion()
uint32 FNetworkDemoHeader::GetCustomVersion (const FGuid & VersionGuid) const
References GetCustomVersion().
Referenced by GetCustomVersion().
operator=() [1/2]
FNetworkDemoHeader & FNetworkDemoHeader::operator= (const FNetworkDemoHeader &) default
References FNetworkDemoHeader().
operator=() [2/2]
FNetworkDemoHeader & FNetworkDemoHeader::operator= (FNetworkDemoHeader &&) default
References FNetworkDemoHeader(), and PRAGMA_ENABLE_DEPRECATION_WARNINGS.
SetDefaultNetworkVersions()
void FNetworkDemoHeader::SetDefaultNetworkVersions ()
References PRAGMA_DISABLE_DEPRECATION_WARNINGS, and SetDefaultNetworkVersions().
Referenced by SetDefaultNetworkVersions().
UE_DEPRECATED() [1/4]
FNetworkDemoHeader::UE_DEPRECATED (5. 2, "No longer used in favor of custom versions, kept for backwards compatibility.")
References UE_DEPRECATED().
UE_DEPRECATED() [2/4]
FNetworkDemoHeader::UE_DEPRECATED (5. 2, "No longer used in favor of custom versions, kept for backwards compatibility.")
References UE_DEPRECATED().
UE_DEPRECATED() [3/4]
FNetworkDemoHeader::UE_DEPRECATED (5. 2, "No longer used in favor of custom versions, kept for backwards compatibility.")
Referenced by UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
UE_DEPRECATED() [4/4]
FNetworkDemoHeader::UE_DEPRECATED (5. 2, "No longer used.")
References UE_DEPRECATED().
Friends And Related Symbol Documentation
operator<<
PRAGMA_ENABLE_DEPRECATION_WARNINGS friend FArchive & operator<< (FArchive & Ar, FNetworkDemoHeader & Header) friend
References FNetworkDemoHeader(), Ar, and Header.
Field Documentation
BuildConfig
EBuildConfiguration FNetworkDemoHeader::BuildConfig
Definition at line 203 of file ReplayTypes.h.
BuildTarget
EBuildTargetType FNetworkDemoHeader::BuildTarget
Definition at line 204 of file ReplayTypes.h.
CheckpointLimitInMS
float FNetworkDemoHeader::CheckpointLimitInMS
Definition at line 200 of file ReplayTypes.h.
CustomVersions
FCustomVersionContainer FNetworkDemoHeader::CustomVersions
Definition at line 193 of file ReplayTypes.h.
Referenced by FOverridableReplayVersionData::ApplyVersionDataToDemoHeader().
EngineVersion
FEngineVersion FNetworkDemoHeader::EngineVersion
Definition at line 206 of file ReplayTypes.h.
Referenced by FOverridableReplayVersionData::ApplyVersionDataToDemoHeader().
FrameLimitInMS
float FNetworkDemoHeader::FrameLimitInMS
Definition at line 199 of file ReplayTypes.h.
GameSpecificData
TArray<FString> FNetworkDemoHeader::GameSpecificData
Definition at line 209 of file ReplayTypes.h.
Guid
FGuid FNetworkDemoHeader::Guid
Definition at line 195 of file ReplayTypes.h.
HeaderFlags
EReplayHeaderFlags FNetworkDemoHeader::HeaderFlags
Definition at line 207 of file ReplayTypes.h.
LevelNamesAndTimes
TArray<FLevelNameAndTime> FNetworkDemoHeader::LevelNamesAndTimes
Definition at line 208 of file ReplayTypes.h.
Magic
uint32 FNetworkDemoHeader::Magic
Definition at line 179 of file ReplayTypes.h.
MaxRecordHz
float FNetworkDemoHeader::MaxRecordHz
Definition at line 198 of file ReplayTypes.h.
MinRecordHz
float FNetworkDemoHeader::MinRecordHz
Definition at line 197 of file ReplayTypes.h.
PackageVersionLicenseeUE
int32 FNetworkDemoHeader::PackageVersionLicenseeUE
Definition at line 211 of file ReplayTypes.h.
Referenced by FOverridableReplayVersionData::ApplyVersionDataToDemoHeader().
PackageVersionUE
FPackageFileVersion FNetworkDemoHeader::PackageVersionUE
Definition at line 210 of file ReplayTypes.h.
Referenced by FOverridableReplayVersionData::ApplyVersionDataToDemoHeader().
Platform
FString FNetworkDemoHeader::Platform
Definition at line 202 of file ReplayTypes.h.
The documentation for this struct was generated from the following file:
Runtime/Engine/Public/ReplayTypes.h