Unreal Engine 5.6 C++ API: FPrimitiveViewRelevance Struct Reference
FPrimitiveViewRelevance Struct Reference
The different types of relevance a primitive scene proxy can declare towards a particular scene view.
#include "PrimitiveViewRelevance.h"
Public Member Functions
FPrimitiveViewRelevance ()
Default constructor.
bool HasTranslucency () const
bool HasVelocity () const
FPrimitiveViewRelevance & operator|= (const FPrimitiveViewRelevance &B)
Bitwise OR operator.
UE_DEPRECATED (4.25, "ShadingModelMaskRelevance has been renamed ShadingModelMask") uint16 ShadingModelMaskRelevance
Public Member Functions inherited from FMaterialRelevance
FMaterialRelevance ()
Default constructor.
FMaterialRelevance & operator|= (const FMaterialRelevance &B)
Bitwise OR operator.
void SetPrimitiveViewRelevance (FPrimitiveViewRelevance &OutViewRelevance) const
Copies the material's relevance flags to a primitive's view relevance flags.
Data Fields
uint32 bDrawRelevance: 1
The primitive is drawn.
uint32 bDynamicRelevance: 1
The primitive's dynamic elements are rendered for the view.
uint32 bEditorNoDepthTestPrimitiveRelevance: 1
The primitive is drawn only in the editor and composited onto the scene after post processing using no depth testing.
uint32 bEditorPrimitiveRelevance: 1
The primitive is drawn only in the editor and composited onto the scene after post processing.
uint32 bEditorStaticSelectionRelevance: 1
The primitive's static elements are selected and rendered again in the selection outline pass.
uint32 bEditorVisualizeLevelInstanceRelevance: 1
The primitive's elements belong to a LevelInstance which is being edited and rendered again in the visualize LevelInstance pass.
uint32 bHasSimpleLights: 1
The primitive should have GatherSimpleLights called on the proxy when gathering simple lights.
uint32 bInitializedThisFrame: 1
Whether this primitive view relevance has been initialized this frame.
uint32 bRenderCustomDepth: 1
The primitive should render to the custom depth pass.
uint32 bRenderInDepthPass: 1
The primitive should render to the depth prepass even if it's not rendered in the main pass.
uint32 bRenderInMainPass: 1
The primitive should render to the base pass / normal depth / velocity rendering.
uint32 bRenderInSecondStageDepthPass: 1
Whether the primitive should be rendered in the second stage depth only pass.
uint32 bShadowRelevance: 1
The primitive is casting a shadow.
UE_DEPRECATED(4.25, "bOpaqueRelevance has been renamed bOpaque") uint32 bOpaqueRelevance UE_DEPRECATED(4.25, "bMaskedRelevance has been renamed bMasked") uint32 bMaskedRelevance UE_DEPRECATED(4.25, "bTranslucentVelocityRelevance has been renamed bOutputsTranslucentVelocity") uint32 bTranslucentVelocityRelevance UE_DEPRECATED(4.25, "bDistortionRelevance has been renamed bDistortion") uint32 bDistortionRelevance UE_DEPRECATED(4.25, "bSeparateTranslucencyRelevance has been renamed bSeparateTranslucency") uint32 bSeparateTranslucencyRelevance UE_DEPRECATED(4.25, "bNormalTranslucencyRelevance has been renamed bNormalTranslucency") uint32 bNormalTranslucencyRelevance UE_DEPRECATED(4.25, "bHairStrandsRelevance has been renamed bHairStrands") uint32 bHairStrandsRelevance uint32 bStaticRelevance: 1
The primitive's static elements are rendered for the view.
uint32 bTranslucentSelfShadow: 1
Whether the primitive has materials that use volumetric translucent self shadow.
uint32 bUsesLightingChannels: 1
Whether the primitive uses non-default lighting channels.
uint32 bVelocityRelevance: 1
The primitive should render velocity.
Data Fields inherited from FMaterialRelevance
union {
struct {
uint8 bDecal: 1
uint8 bDisableDepthTest: 1
uint8 bDistortion: 1
uint8 bHairStrands: 1
uint8 bHasVolumeMaterialDomain: 1
uint8 bIsLightFunctionAtlasCompatible: 1
uint8 bMasked: 1
uint8 bNormalTranslucency: 1
uint8 bOpaque: 1
uint8 bOutputsTranslucentVelocity: 1
uint8 bPostMotionBlurTranslucency: 1
uint8 bSeparateTranslucency: 1
uint8 bSupportsMaterialCache: 1
uint8 bTranslucencyModulate: 1
uint8 bTranslucentSurfaceLighting: 1
uint8 bTwoSided: 1
uint8 bUsesAnisotropy: 1
uint8 bUsesComplexSpecialRenderPath: 1
uint8 bUsesCustomizedUVs: 1
uint8 bUsesDisplacement: 1
uint8 bUsesDistanceCullFade: 1
uint8 bUsesGlobalDistanceField: 1
uint8 bUsesPixelDepthOffset: 1
uint8 bUsesSceneColorCopy: 1
uint8 bUsesSceneDepth: 1
uint8 bUsesSingleLayerWaterMaterial: 1
uint8 bUsesSkyMaterial: 1
uint8 bUsesVertexInterpolator: 1
uint8 bUsesWorldPositionOffset: 1
uint8 CustomDepthStencilUsageMask: 2
uint16 ShadingModelMask
uint8 SubstrateClosureCountMask
uint8 SubstrateUintPerPixel
}
uint64 Raw
};
Detailed Description
The different types of relevance a primitive scene proxy can declare towards a particular scene view.
the class is only storing bits, and has an |= operator
Definition at line 13 of file PrimitiveViewRelevance.h.
Constructor & Destructor Documentation
FPrimitiveViewRelevance()
FPrimitiveViewRelevance::FPrimitiveViewRelevance () inline
Default constructor.
Definition at line 90 of file PrimitiveViewRelevance.h.
References FMaterialRelevance::bOpaque, bRenderInMainPass, and RESTRICT.
Referenced by operator|=().
Member Function Documentation
HasTranslucency()
bool FPrimitiveViewRelevance::HasTranslucency () const inline
Definition at line 79 of file PrimitiveViewRelevance.h.
References FMaterialRelevance::bNormalTranslucency, FMaterialRelevance::bPostMotionBlurTranslucency, FMaterialRelevance::bSeparateTranslucency, and FMaterialRelevance::bTranslucencyModulate.
HasVelocity()
bool FPrimitiveViewRelevance::HasVelocity () const inline
Definition at line 84 of file PrimitiveViewRelevance.h.
References FMaterialRelevance::bOutputsTranslucentVelocity, and bVelocityRelevance.
operator|=()
FPrimitiveViewRelevance & FPrimitiveViewRelevance::operator|= (const FPrimitiveViewRelevance & B) inline
Bitwise OR operator.
Sets any relevance bits which are present in either.
Definition at line 107 of file PrimitiveViewRelevance.h.
References FPrimitiveViewRelevance(), B, and RESTRICT.
UE_DEPRECATED()
FPrimitiveViewRelevance::UE_DEPRECATED (4. 25, "ShadingModelMaskRelevance has been renamed ShadingModelMask")
References UE_DEPRECATED().
Referenced by UE_DEPRECATED().
Field Documentation
bDrawRelevance
uint32 FPrimitiveViewRelevance::bDrawRelevance
The primitive is drawn.
Definition at line 44 of file PrimitiveViewRelevance.h.
bDynamicRelevance
uint32 FPrimitiveViewRelevance::bDynamicRelevance
The primitive's dynamic elements are rendered for the view.
Definition at line 42 of file PrimitiveViewRelevance.h.
bEditorNoDepthTestPrimitiveRelevance
uint32 FPrimitiveViewRelevance::bEditorNoDepthTestPrimitiveRelevance
The primitive is drawn only in the editor and composited onto the scene after post processing using no depth testing.
Definition at line 62 of file PrimitiveViewRelevance.h.
bEditorPrimitiveRelevance
uint32 FPrimitiveViewRelevance::bEditorPrimitiveRelevance
The primitive is drawn only in the editor and composited onto the scene after post processing.
Definition at line 56 of file PrimitiveViewRelevance.h.
bEditorStaticSelectionRelevance
uint32 FPrimitiveViewRelevance::bEditorStaticSelectionRelevance
The primitive's static elements are selected and rendered again in the selection outline pass.
Definition at line 60 of file PrimitiveViewRelevance.h.
bEditorVisualizeLevelInstanceRelevance
uint32 FPrimitiveViewRelevance::bEditorVisualizeLevelInstanceRelevance
The primitive's elements belong to a LevelInstance which is being edited and rendered again in the visualize LevelInstance pass.
Definition at line 58 of file PrimitiveViewRelevance.h.
bHasSimpleLights
uint32 FPrimitiveViewRelevance::bHasSimpleLights
The primitive should have GatherSimpleLights called on the proxy when gathering simple lights.
Definition at line 64 of file PrimitiveViewRelevance.h.
bInitializedThisFrame
uint32 FPrimitiveViewRelevance::bInitializedThisFrame
Whether this primitive view relevance has been initialized this frame.
Primitives that have not had ComputeRelevanceForView called on them (because they were culled) will not be initialized, But we may still need to render them from other views like shadow passes, so this tracks whether we can reuse the cached relevance or not.
Definition at line 77 of file PrimitiveViewRelevance.h.
bRenderCustomDepth
uint32 FPrimitiveViewRelevance::bRenderCustomDepth
The primitive should render to the custom depth pass.
Definition at line 50 of file PrimitiveViewRelevance.h.
bRenderInDepthPass
uint32 FPrimitiveViewRelevance::bRenderInDepthPass
The primitive should render to the depth prepass even if it's not rendered in the main pass.
Definition at line 52 of file PrimitiveViewRelevance.h.
bRenderInMainPass
uint32 FPrimitiveViewRelevance::bRenderInMainPass
The primitive should render to the base pass / normal depth / velocity rendering.
Definition at line 54 of file PrimitiveViewRelevance.h.
Referenced by FPrimitiveViewRelevance().
bRenderInSecondStageDepthPass
uint32 FPrimitiveViewRelevance::bRenderInSecondStageDepthPass
Whether the primitive should be rendered in the second stage depth only pass.
Definition at line 70 of file PrimitiveViewRelevance.h.
bShadowRelevance
uint32 FPrimitiveViewRelevance::bShadowRelevance
The primitive is casting a shadow.
Definition at line 46 of file PrimitiveViewRelevance.h.
bStaticRelevance
UE_DEPRECATED (4.25, "bOpaqueRelevance has been renamed bOpaque") uint32 bOpaqueRelevance UE_DEPRECATED (4.25, "bMaskedRelevance has been renamed bMasked") uint32 bMaskedRelevance UE_DEPRECATED (4.25, "bTranslucentVelocityRelevance has been renamed bOutputsTranslucentVelocity") uint32 bTranslucentVelocityRelevance UE_DEPRECATED (4.25, "bDistortionRelevance has been renamed bDistortion") uint32 bDistortionRelevance UE_DEPRECATED (4.25, "bSeparateTranslucencyRelevance has been renamed bSeparateTranslucency") uint32 bSeparateTranslucencyRelevance UE_DEPRECATED (4.25, "bNormalTranslucencyRelevance has been renamed bNormalTranslucency") uint32 bNormalTranslucencyRelevance UE_DEPRECATED (4.25, "bHairStrandsRelevance has been renamed bHairStrands") uint32 bHairStrandsRelevance uint32 FPrimitiveViewRelevance::bStaticRelevance
The primitive's static elements are rendered for the view.
Definition at line 40 of file PrimitiveViewRelevance.h.
bTranslucentSelfShadow
uint32 FPrimitiveViewRelevance::bTranslucentSelfShadow
Whether the primitive has materials that use volumetric translucent self shadow.
Definition at line 68 of file PrimitiveViewRelevance.h.
bUsesLightingChannels
uint32 FPrimitiveViewRelevance::bUsesLightingChannels
Whether the primitive uses non-default lighting channels.
Definition at line 66 of file PrimitiveViewRelevance.h.
bVelocityRelevance
uint32 FPrimitiveViewRelevance::bVelocityRelevance
The primitive should render velocity.
Definition at line 48 of file PrimitiveViewRelevance.h.
Referenced by HasVelocity().
The documentation for this struct was generated from the following file:
Runtime/Engine/Public/PrimitiveViewRelevance.h