Unreal Engine 5.6 C++ API: UE::Geometry::FActorAdapter Struct Reference
UE::Geometry::FActorAdapter Struct Reference
FActorAdapter is used by FMeshSceneAdapter to represent all the child info for an AActor.
#include "MeshSceneAdapter.h"
Public Member Functions
FActorAdapter ()
FActorAdapter (const FActorAdapter &)=delete
FActorAdapter (FActorAdapter &&)=delete
Data Fields
TArray< TUniquePtr< FActorChildMesh > > ChildMeshes
AActor * SourceActor = nullptr
FAxisAlignedBox3d WorldBounds
Detailed Description
FActorAdapter is used by FMeshSceneAdapter to represent all the child info for an AActor.
This is primarily a list of FActorChildMesh, which represent the spatially-positioned meshes of any child StaticMeshComponents or other mesh Components that can be identified and represented. Note that ChildActorComponents will be flatted into the parent Actor.
Definition at line 242 of file MeshSceneAdapter.h.
Constructor & Destructor Documentation
FActorAdapter() [1/3]
UE::Geometry::FActorAdapter::FActorAdapter () inline
Definition at line 245 of file MeshSceneAdapter.h.
Referenced by FActorAdapter(), and FActorAdapter().
FActorAdapter() [2/3]
UE::Geometry::FActorAdapter::FActorAdapter (const FActorAdapter &) delete
References FActorAdapter().
FActorAdapter() [3/3]
UE::Geometry::FActorAdapter::FActorAdapter (FActorAdapter &&) delete
References FActorAdapter().
Field Documentation
ChildMeshes
TArray<TUniquePtr<FActorChildMesh> > UE::Geometry::FActorAdapter::ChildMeshes
Definition at line 252 of file MeshSceneAdapter.h.
SourceActor
AActor* UE::Geometry::FActorAdapter::SourceActor = nullptr
Definition at line 250 of file MeshSceneAdapter.h.
WorldBounds
FAxisAlignedBox3d UE::Geometry::FActorAdapter::WorldBounds
Definition at line 254 of file MeshSceneAdapter.h.
The documentation for this struct was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/MeshModelingToolset/Source/ModelingComponents/Public/Scene/MeshSceneAdapter.h