Unreal Engine 5.6 C++ API: FReferenceSkeleton Struct Reference
FReferenceSkeleton Struct Reference
Reference Skeleton.
#include "ReferenceSkeleton.h"
Public Member Functions
FReferenceSkeleton (bool bInOnlyOneRootAllowed=true)
bool BoneIsChildOf (const int32 ChildBoneIndex, const int32 ParentBoneIndex) const
void Empty (int32 Size=0)
void EnsureParentsExist (TArray< FBoneIndexType > &InOutBoneSortedArray) const
Ensure parent exists in the given input sorted array.
void EnsureParentsExistAndSort (TArray< FBoneIndexType > &InOutBoneUnsortedArray) const
Ensure parent exists in the given input array.
int32 FindBoneIndex (const FName &BoneName) const
Find Bone Index from BoneName.
int32 FindRawBoneIndex (const FName &BoneName) const
Find Bone Index from BoneName.
FTransform GetBoneAbsoluteTransform (const int32 InBoneIndex) const
Return a single bone's pose as absolute transform (i.e.
void GetBoneAbsoluteTransforms (TArray< FTransform > &OutAbsoluteTransforms) const
Return all the bone poses as absolute transforms (i.e.
FName GetBoneName (const int32 BoneIndex) const
SIZE_T GetDataSize () const
int32 GetDepthBetweenBones (const int32 BoneIndex, const int32 ParentBoneIndex) const
Returns # of Depth from BoneIndex to ParentBoneIndex This will return 0 if BoneIndex == ParentBoneIndex; This will return -1 if BoneIndex isn't child of ParentBoneIndex.
int32 GetDirectChildBones (int32 ParentBoneIndex, TArray< int32 > &Children) const
int32 GetNum () const
Returns number of bones in Skeleton.
int32 GetParentIndex (const int32 BoneIndex) const
FTransform GetRawBoneAbsoluteTransform (const int32 InRawBoneIndex) const
Return a single non-virtual bone's pose as absolute transform (i.e.
void GetRawBoneAbsoluteTransforms (TArray< FTransform > &OutAbsoluteTransforms) const
Return all the non-virtual bone poses as absolute transforms (i.e.
int32 GetRawBoneNum () const
Returns number of raw bones in Skeleton.
void GetRawChildrenIndicesCached (const int32 BoneIndex, TArray< int32 > &OutChildren) const
void GetRawChildrenIndicesRecursiveCached (const int32 BoneIndex, TArray< int32 > &OutChildren) const
int32 GetRawDirectChildBones (int32 ParentBoneIndex, TArray< int32 > &Children) const
const TMap< FName, int32 > & GetRawNameToIndexMap () const
int32 GetRawParentIndex (const int32 BoneIndex) const
const TArray< FMeshBoneInfo > & GetRawRefBoneInfo () const
Accessor to private data.
TArray< FName > GetRawRefBoneNames () const
Returns an array of raw bone names.
const TArray< FTransform > & GetRawRefBonePose () const
Accessor to private data.
const TArray< FMeshBoneInfo > & GetRefBoneInfo () const
Accessor to private data.
const TArray< FTransform > & GetRefBonePose () const
Accessor to private data.
const TArray< FBoneIndexType > & GetRequiredVirtualBones () const
const TArray< FVirtualBoneRefData > & GetVirtualBoneRefData () const
bool IsValidIndex (int32 Index) const
bool IsValidRawIndex (int32 Index) const
void RebuildNameToIndexMap ()
void RebuildRefSkeleton (const USkeleton *Skeleton, bool bRebuildNameMap)
TArray< int32 > RemoveBonesByName (USkeleton *Skeleton, const TArray< FName > &BonesToRemove)
Removes the supplied bones from the skeleton, unless they have children that aren't also going to be removed.
void RemoveDuplicateBones (const UObject *Requester, TArray< FBoneIndexType > &DuplicateBones)
Data Fields
friend FReferenceSkeletonModifier
Private Member Functions
void Add (const FMeshBoneInfo &BoneInfo, const FTransform &BonePose)
Add a new bone.
int32 GetCachedEndOfBranchIndex (const int32 InBoneIndex) const
int32 GetChildrenInternal (int32 InParentBoneIndex, TArray< int32 > &OutChildren, const bool bRaw) const
int32 GetParentIndexInternal (const int32 BoneIndex, const TArray< FMeshBoneInfo > &BoneInfo) const
int32 GetRawSourceBoneIndex (const USkeleton *Skeleton, const FName &SourceBoneName) const
void InvalidateEndOfBranchCache () const
void Remove (const FName InBoneName, const bool bRemoveChildren)
Remove InBoneName and its children if bRemoveChildren == true.
bool RemoveIndividualBone (int32 BoneIndex, TArray< int32 > &OutBonesRemoved)
Removes the specified bone, so long as it has no children.
void Rename (const FName InBoneName, const FName InNewName)
Rename InBoneName with InNewName.
int32 SetParent (const FName InBoneName, const FName InParentName)
Set InParentName as InBoneName's parent.
void UpdateRefPoseTransform (const int32 BoneIndex, const FTransform &BonePose)
Private Attributes
bool bOnlyOneRootAllowed
Whether this skeleton is limited to one root or not Multi root is not supported in general Skeleton/SkeletalMesh But there are other components that can use this and support multi root - i.e.
TArray< int32 > CachedEndOfBranchIndicesRaw
One index per-bone.
TMap< FName, int32 > FinalNameToIndexMap
TArray< FMeshBoneInfo > FinalRefBoneInfo
Reference bone related info to be serialized.
TArray< FTransform > FinalRefBonePose
Reference bone transform.
TMap< FName, int32 > RawNameToIndexMap
TMap to look up bone index from bone name.
TArray< FMeshBoneInfo > RawRefBoneInfo
Reference bone related info to be serialized.
TArray< FTransform > RawRefBonePose
Reference bone transform.
TArray< FBoneIndexType > RequiredVirtualBones
TArray< FVirtualBoneRefData > UsedVirtualBoneData
Static Private Attributes
static constexpr int32 BRANCH_CACHE_INVALID_INDEX = -2
Friends
FArchive & operator<< (FArchive &Ar, FReferenceSkeleton &F)
Detailed Description
Reference Skeleton.
Definition at line 99 of file ReferenceSkeleton.h.
Constructor & Destructor Documentation
FReferenceSkeleton()
FReferenceSkeleton::FReferenceSkeleton (bool bInOnlyOneRootAllowed = true) inline
Definition at line 101 of file ReferenceSkeleton.h.
References bOnlyOneRootAllowed.
Referenced by operator<<.
Member Function Documentation
Add()
void FReferenceSkeleton::Add (const FMeshBoneInfo & BoneInfo, const FTransform & BonePose) inline private
Add a new bone.
BoneName must not already exist! ParentIndex must be valid.
Definition at line 198 of file ReferenceSkeleton.h.
References bOnlyOneRootAllowed, check, checkSlow, FindRawBoneIndex(), INDEX_NONE, FMeshBoneInfo::Name, FMeshBoneInfo::ParentIndex, RawNameToIndexMap, RawRefBoneInfo, and RawRefBonePose.
BoneIsChildOf()
bool FReferenceSkeleton::BoneIsChildOf (const int32 ChildBoneIndex, const int32 ParentBoneIndex) const inline
Definition at line 396 of file ReferenceSkeleton.h.
References GetParentIndex(), and INDEX_NONE.
Empty()
void FReferenceSkeleton::Empty (int32 Size = 0) inline
Definition at line 296 of file ReferenceSkeleton.h.
References CachedEndOfBranchIndicesRaw, FinalNameToIndexMap, FinalRefBoneInfo, FinalRefBonePose, RawNameToIndexMap, RawRefBoneInfo, RawRefBonePose, and TSequenceHistory< HistorySize >::Size.
EnsureParentsExist()
void FReferenceSkeleton::EnsureParentsExist (TArray< FBoneIndexType > & InOutBoneSortedArray) const
Ensure parent exists in the given input sorted array.
Insert parent to the array. The result should be sorted.
EnsureParentsExistAndSort()
void FReferenceSkeleton::EnsureParentsExistAndSort (TArray< FBoneIndexType > & InOutBoneUnsortedArray) const
Ensure parent exists in the given input array.
Insert parent to the array. The result should be sorted.
FindBoneIndex()
int32 FReferenceSkeleton::FindBoneIndex (const FName & BoneName) const inline
Find Bone Index from BoneName.
Precache as much as possible in speed critical sections!
Definition at line 311 of file ReferenceSkeleton.h.
References checkSlow, FinalNameToIndexMap, FinalRefBoneInfo, and INDEX_NONE.
FindRawBoneIndex()
int32 FReferenceSkeleton::FindRawBoneIndex (const FName & BoneName) const inline
Find Bone Index from BoneName.
Precache as much as possible in speed critical sections!
Definition at line 327 of file ReferenceSkeleton.h.
References checkSlow, INDEX_NONE, RawNameToIndexMap, and RawRefBoneInfo.
Referenced by Add().
GetBoneAbsoluteTransform()
FTransform FReferenceSkeleton::GetBoneAbsoluteTransform (const int32 InBoneIndex) const
Return a single bone's pose as absolute transform (i.e.
relative to the origin, rather than the parent bone).
GetBoneAbsoluteTransforms()
void FReferenceSkeleton::GetBoneAbsoluteTransforms (TArray< FTransform > & OutAbsoluteTransforms) const
Return all the bone poses as absolute transforms (i.e.
relative to the origin, rather than the parent bone). This function will resize the array to store the transforms, with no re-allocation if shrinking
GetBoneName()
FName FReferenceSkeleton::GetBoneName (const int32 BoneIndex) const inline
Definition at line 342 of file ReferenceSkeleton.h.
References FinalRefBoneInfo.
GetCachedEndOfBranchIndex()
int32 FReferenceSkeleton::GetCachedEndOfBranchIndex (const int32 InBoneIndex) const private
GetChildrenInternal()
int32 FReferenceSkeleton::GetChildrenInternal (int32 InParentBoneIndex, TArray< int32 > & OutChildren, const bool bRaw) const private
GetDataSize()
SIZE_T FReferenceSkeleton::GetDataSize () const
GetDepthBetweenBones()
int32 FReferenceSkeleton::GetDepthBetweenBones (const int32 BoneIndex, const int32 ParentBoneIndex) const inline
Returns # of Depth from BoneIndex to ParentBoneIndex This will return 0 if BoneIndex == ParentBoneIndex; This will return -1 if BoneIndex isn't child of ParentBoneIndex.
Definition at line 372 of file ReferenceSkeleton.h.
References Depth, FinalRefBoneInfo, and INDEX_NONE.
GetDirectChildBones()
int32 FReferenceSkeleton::GetDirectChildBones (int32 ParentBoneIndex, TArray< int32 > & Children) const
GetNum()
int32 FReferenceSkeleton::GetNum () const inline
Returns number of bones in Skeleton.
Definition at line 241 of file ReferenceSkeleton.h.
References FinalRefBoneInfo.
GetParentIndex()
int32 FReferenceSkeleton::GetParentIndex (const int32 BoneIndex) const inline
Definition at line 347 of file ReferenceSkeleton.h.
References FinalRefBoneInfo, and GetParentIndexInternal().
Referenced by BoneIsChildOf().
GetParentIndexInternal()
int32 FReferenceSkeleton::GetParentIndexInternal (const int32 BoneIndex, const TArray< FMeshBoneInfo > & BoneInfo) const inline private
Definition at line 179 of file ReferenceSkeleton.h.
References bOnlyOneRootAllowed, checkSlow, INDEX_NONE, and TArray< InElementType, InAllocatorType >::IsValidIndex().
Referenced by GetParentIndex(), and GetRawParentIndex().
GetRawBoneAbsoluteTransform()
FTransform FReferenceSkeleton::GetRawBoneAbsoluteTransform (const int32 InRawBoneIndex) const
Return a single non-virtual bone's pose as absolute transform (i.e.
relative to the origin, rather than the parent bone).
GetRawBoneAbsoluteTransforms()
void FReferenceSkeleton::GetRawBoneAbsoluteTransforms (TArray< FTransform > & OutAbsoluteTransforms) const
Return all the non-virtual bone poses as absolute transforms (i.e.
relative to the origin, rather than the parent bone). This function will resize the array to store the transforms, with no re-allocation if shrinking
GetRawBoneNum()
int32 FReferenceSkeleton::GetRawBoneNum () const inline
Returns number of raw bones in Skeleton.
These are the original bones of the asset
Definition at line 247 of file ReferenceSkeleton.h.
References RawRefBoneInfo.
Referenced by FInstancedSkinnedMeshComponentHelper::GetComponentDesc(), RemoveBonesByName(), and RemoveIndividualBone().
GetRawChildrenIndicesCached()
void FReferenceSkeleton::GetRawChildrenIndicesCached (const int32 BoneIndex, TArray< int32 > & OutChildren) const
GetRawChildrenIndicesRecursiveCached()
void FReferenceSkeleton::GetRawChildrenIndicesRecursiveCached (const int32 BoneIndex, TArray< int32 > & OutChildren) const
GetRawDirectChildBones()
int32 FReferenceSkeleton::GetRawDirectChildBones (int32 ParentBoneIndex, TArray< int32 > & Children) const
GetRawNameToIndexMap()
const TMap< FName, int32 > & FReferenceSkeleton::GetRawNameToIndexMap () const inline
Definition at line 280 of file ReferenceSkeleton.h.
References RawNameToIndexMap.
GetRawParentIndex()
int32 FReferenceSkeleton::GetRawParentIndex (const int32 BoneIndex) const inline
Definition at line 352 of file ReferenceSkeleton.h.
References GetParentIndexInternal(), and RawRefBoneInfo.
GetRawRefBoneInfo()
const TArray< FMeshBoneInfo > & FReferenceSkeleton::GetRawRefBoneInfo () const inline
Accessor to private data.
Raw relates to original asset. Const so it can't be changed recklessly.
Definition at line 269 of file ReferenceSkeleton.h.
References RawRefBoneInfo.
GetRawRefBoneNames()
TArray< FName > FReferenceSkeleton::GetRawRefBoneNames () const inline
Returns an array of raw bone names.
Definition at line 283 of file ReferenceSkeleton.h.
References TArray< InElementType, InAllocatorType >::Add(), RawRefBoneInfo, and TArray< InElementType, InAllocatorType >::Reserve().
GetRawRefBonePose()
const TArray< FTransform > & FReferenceSkeleton::GetRawRefBonePose () const inline
Accessor to private data.
Raw relates to original asset. Const so it can't be changed recklessly.
Definition at line 275 of file ReferenceSkeleton.h.
References RawRefBonePose.
GetRawSourceBoneIndex()
int32 FReferenceSkeleton::GetRawSourceBoneIndex (const USkeleton * Skeleton, const FName & SourceBoneName) const private
References Skeleton.
GetRefBoneInfo()
const TArray< FMeshBoneInfo > & FReferenceSkeleton::GetRefBoneInfo () const inline
Accessor to private data.
These include the USkeletons virtual bones. Const so it can't be changed recklessly.
Definition at line 257 of file ReferenceSkeleton.h.
References FinalRefBoneInfo.
Referenced by UE::AnimNext::TReferencePose< FDefaultAllocator, FDefaultSetAllocator >::Initialize().
GetRefBonePose()
const TArray< FTransform > & FReferenceSkeleton::GetRefBonePose () const inline
Accessor to private data.
These include the USkeletons virtual bones. Const so it can't be changed recklessly.
Definition at line 263 of file ReferenceSkeleton.h.
References FinalRefBonePose.
Referenced by UE::AnimNext::TReferencePose< FDefaultAllocator, FDefaultSetAllocator >::Initialize().
GetRequiredVirtualBones()
const TArray< FBoneIndexType > & FReferenceSkeleton::GetRequiredVirtualBones () const inline
Definition at line 252 of file ReferenceSkeleton.h.
References RequiredVirtualBones.
GetVirtualBoneRefData()
const TArray< FVirtualBoneRefData > & FReferenceSkeleton::GetVirtualBoneRefData () const inline
Definition at line 254 of file ReferenceSkeleton.h.
References UsedVirtualBoneData.
InvalidateEndOfBranchCache()
void FReferenceSkeleton::InvalidateEndOfBranchCache () const inline private
Definition at line 138 of file ReferenceSkeleton.h.
References BRANCH_CACHE_INVALID_INDEX, CachedEndOfBranchIndicesRaw, and RawRefBonePose.
Referenced by RemoveIndividualBone().
IsValidIndex()
bool FReferenceSkeleton::IsValidIndex (int32 Index) const inline
Definition at line 357 of file ReferenceSkeleton.h.
References FinalRefBoneInfo.
IsValidRawIndex()
bool FReferenceSkeleton::IsValidRawIndex (int32 Index) const inline
Definition at line 362 of file ReferenceSkeleton.h.
References RawRefBoneInfo.
RebuildNameToIndexMap()
void FReferenceSkeleton::RebuildNameToIndexMap ()
RebuildRefSkeleton()
void FReferenceSkeleton::RebuildRefSkeleton (const USkeleton * Skeleton, bool bRebuildNameMap)
References Skeleton.
Referenced by RemoveBonesByName().
Remove()
void FReferenceSkeleton::Remove (const FName InBoneName, const bool bRemoveChildren) private
Remove InBoneName and its children if bRemoveChildren == true.
RemoveBonesByName()
TArray< int32 > FReferenceSkeleton::RemoveBonesByName (USkeleton * Skeleton, const TArray< FName > & BonesToRemove) inline
Removes the supplied bones from the skeleton, unless they have children that aren't also going to be removed.
Definition at line 423 of file ReferenceSkeleton.h.
References TArray< InElementType, InAllocatorType >::Contains(), GetRawBoneNum(), FMeshBoneInfo::Name, RawRefBoneInfo, RebuildRefSkeleton(), RemoveIndividualBone(), and Skeleton.
RemoveDuplicateBones()
void FReferenceSkeleton::RemoveDuplicateBones (const UObject * Requester, TArray< FBoneIndexType > & DuplicateBones)
RemoveIndividualBone()
bool FReferenceSkeleton::RemoveIndividualBone (int32 BoneIndex, TArray< int32 > & OutBonesRemoved) inline private
Removes the specified bone, so long as it has no children.
Returns whether we removed the bone or not
Definition at line 144 of file ReferenceSkeleton.h.
References TArray< InElementType, InAllocatorType >::Add(), GetRawBoneNum(), InvalidateEndOfBranchCache(), FMeshBoneInfo::ParentIndex, RawRefBoneInfo, and RawRefBonePose.
Referenced by RemoveBonesByName().
Rename()
void FReferenceSkeleton::Rename (const FName InBoneName, const FName InNewName) private
Rename InBoneName with InNewName.
SetParent()
int32 FReferenceSkeleton::SetParent (const FName InBoneName, const FName InParentName) private
Set InParentName as InBoneName's parent.
UpdateRefPoseTransform()
void FReferenceSkeleton::UpdateRefPoseTransform (const int32 BoneIndex, const FTransform & BonePose) inline private
Definition at line 191 of file ReferenceSkeleton.h.
References RawRefBonePose.
Friends And Related Symbol Documentation
operator<<
FArchive & operator<< (FArchive & Ar, FReferenceSkeleton & F) friend
References FReferenceSkeleton(), and Ar.
Field Documentation
bOnlyOneRootAllowed
bool FReferenceSkeleton::bOnlyOneRootAllowed private
Whether this skeleton is limited to one root or not Multi root is not supported in general Skeleton/SkeletalMesh But there are other components that can use this and support multi root - i.e.
ControlRig This sturct is used in draw code, the long term plan may be detach this from draw code and use interface struct
Definition at line 132 of file ReferenceSkeleton.h.
Referenced by FReferenceSkeleton(), Add(), and GetParentIndexInternal().
BRANCH_CACHE_INVALID_INDEX
int32 FReferenceSkeleton::BRANCH_CACHE_INVALID_INDEX = -2 static constexpr private
Definition at line 137 of file ReferenceSkeleton.h.
Referenced by InvalidateEndOfBranchCache().
CachedEndOfBranchIndicesRaw
TArray<int32> FReferenceSkeleton::CachedEndOfBranchIndicesRaw mutable private
One index per-bone.
Lazy-filled on request. Stores the last element of the branch below the bone. You can iterate between in the indices stored here and the bone in question to iterate over all children recursively
Definition at line 136 of file ReferenceSkeleton.h.
Referenced by Empty(), and InvalidateEndOfBranchCache().
FinalNameToIndexMap
TMap<FName, int32> FReferenceSkeleton::FinalNameToIndexMap private
Definition at line 120 of file ReferenceSkeleton.h.
Referenced by Empty(), and FindBoneIndex().
FinalRefBoneInfo
TArray<FMeshBoneInfo> FReferenceSkeleton::FinalRefBoneInfo private
Reference bone related info to be serialized.
Definition at line 114 of file ReferenceSkeleton.h.
Referenced by Empty(), FindBoneIndex(), GetBoneName(), GetDepthBetweenBones(), GetNum(), GetParentIndex(), GetRefBoneInfo(), and IsValidIndex().
FinalRefBonePose
TArray<FTransform> FReferenceSkeleton::FinalRefBonePose private
Reference bone transform.
Definition at line 116 of file ReferenceSkeleton.h.
Referenced by Empty(), and GetRefBonePose().
FReferenceSkeletonModifier
friend FReferenceSkeleton::FReferenceSkeletonModifier
Definition at line 475 of file ReferenceSkeleton.h.
RawNameToIndexMap
TMap<FName, int32> FReferenceSkeleton::RawNameToIndexMap private
TMap to look up bone index from bone name.
Definition at line 119 of file ReferenceSkeleton.h.
Referenced by Add(), Empty(), FindRawBoneIndex(), and GetRawNameToIndexMap().
RawRefBoneInfo
TArray<FMeshBoneInfo> FReferenceSkeleton::RawRefBoneInfo private
Reference bone related info to be serialized.
Definition at line 108 of file ReferenceSkeleton.h.
Referenced by Add(), Empty(), FindRawBoneIndex(), GetRawBoneNum(), GetRawParentIndex(), GetRawRefBoneInfo(), GetRawRefBoneNames(), IsValidRawIndex(), RemoveBonesByName(), and RemoveIndividualBone().
RawRefBonePose
TArray<FTransform> FReferenceSkeleton::RawRefBonePose private
Reference bone transform.
Definition at line 110 of file ReferenceSkeleton.h.
Referenced by Add(), Empty(), GetRawRefBonePose(), InvalidateEndOfBranchCache(), RemoveIndividualBone(), and UpdateRefPoseTransform().
RequiredVirtualBones
TArray<FBoneIndexType> FReferenceSkeleton::RequiredVirtualBones private
Definition at line 123 of file ReferenceSkeleton.h.
Referenced by GetRequiredVirtualBones().
UsedVirtualBoneData
TArray<FVirtualBoneRefData> FReferenceSkeleton::UsedVirtualBoneData private
Definition at line 124 of file ReferenceSkeleton.h.
Referenced by GetVirtualBoneRefData().
The documentation for this struct was generated from the following file:
Runtime/Engine/Public/ReferenceSkeleton.h