Unreal Engine 5.6 C++ API: UE::AnimNext::FWeakTraitPtr Struct Reference
UE::AnimNext::FWeakTraitPtr Struct Reference
Weak Trait Pointer Same as a FTraitPtr but is strongly typed to be weak.
#include "TraitPtr.h"
Public Member Functions
constexpr FWeakTraitPtr () noexcept=default
FWeakTraitPtr (const FTraitPtr &TraitPtr) noexcept
ANIMNEXTANIMGRAPH_API FWeakTraitPtr (FNodeInstance *InNodeInstance, uint32 InTraitIndex)
ANIMNEXTANIMGRAPH_API constexpr FNodeInstance * GetNodeInstance () const noexcept
ANIMNEXTANIMGRAPH_API constexpr uint32 GetTraitIndex () const noexcept
ANIMNEXTANIMGRAPH_API constexpr bool IsValid () const noexcept
bool operator!= (const FTraitPtr &RHS) const
bool operator!= (const FWeakTraitPtr &RHS) const
bool operator== (const FTraitPtr &RHS) const
bool operator== (const FWeakTraitPtr &RHS) const
ANIMNEXTANIMGRAPH_API void Reset ()
Private Attributes
FNodeInstance * NodeInstance = nullptr
uint32 TraitIndex = 0
Detailed Description
Weak Trait Pointer Same as a FTraitPtr but is strongly typed to be weak.
Weak trait pointers should be used carefully!
See also
FTraitPtr
Definition at line 96 of file TraitPtr.h.
Constructor & Destructor Documentation
FWeakTraitPtr() [1/3]
UE::AnimNext::FWeakTraitPtr::FWeakTraitPtr () constexpr default noexcept
Referenced by FWeakTraitPtr(), operator!=(), and operator==().
FWeakTraitPtr() [2/3]
UE::AnimNext::FWeakTraitPtr::FWeakTraitPtr (const FTraitPtr & TraitPtr) inline noexcept
Definition at line 102 of file TraitPtr.h.
References FWeakTraitPtr(), GetNodeInstance(), NodeInstance, and TraitIndex.
FWeakTraitPtr() [3/3]
ANIMNEXTANIMGRAPH_API UE::AnimNext::FWeakTraitPtr::FWeakTraitPtr (FNodeInstance * InNodeInstance, uint32 InTraitIndex)
References UE_API.
Member Function Documentation
GetNodeInstance()
ANIMNEXTANIMGRAPH_API constexpr FNodeInstance * UE::AnimNext::FWeakTraitPtr::GetNodeInstance () const inline constexpr noexcept
Definition at line 111 of file TraitPtr.h.
References NodeInstance, and UE_API.
Referenced by FWeakTraitPtr(), UE::AnimNext::FTraitPtr::operator!=(), and UE::AnimNext::FTraitPtr::operator==().
GetTraitIndex()
ANIMNEXTANIMGRAPH_API constexpr uint32 UE::AnimNext::FWeakTraitPtr::GetTraitIndex () const inline constexpr noexcept
Definition at line 114 of file TraitPtr.h.
References TraitIndex, and UE_API.
Referenced by UE::AnimNext::FTraitPtr::operator!=(), and UE::AnimNext::FTraitPtr::operator==().
IsValid()
ANIMNEXTANIMGRAPH_API constexpr bool UE::AnimNext::FWeakTraitPtr::IsValid () const inline constexpr noexcept
Definition at line 117 of file TraitPtr.h.
References NodeInstance, and UE_API.
Referenced by UE::AnimNext::IHierarchy::GetForwardedStackInterface().
operator!=() [1/2]
bool UE::AnimNext::FWeakTraitPtr::operator!= (const FTraitPtr & RHS) const inline
Definition at line 126 of file TraitPtr.h.
References UE::AnimNext::FTraitPtr::GetNodeInstance(), UE::AnimNext::FTraitPtr::GetTraitIndex(), NodeInstance, and TraitIndex.
operator!=() [2/2]
bool UE::AnimNext::FWeakTraitPtr::operator!= (const FWeakTraitPtr & RHS) const inline
Definition at line 124 of file TraitPtr.h.
References FWeakTraitPtr(), NodeInstance, and TraitIndex.
operator==() [1/2]
bool UE::AnimNext::FWeakTraitPtr::operator== (const FTraitPtr & RHS) const inline
Definition at line 125 of file TraitPtr.h.
References UE::AnimNext::FTraitPtr::GetNodeInstance(), UE::AnimNext::FTraitPtr::GetTraitIndex(), NodeInstance, and TraitIndex.
operator==() [2/2]
bool UE::AnimNext::FWeakTraitPtr::operator== (const FWeakTraitPtr & RHS) const inline
Definition at line 123 of file TraitPtr.h.
References FWeakTraitPtr(), NodeInstance, and TraitIndex.
Reset()
ANIMNEXTANIMGRAPH_API void UE::AnimNext::FWeakTraitPtr::Reset ()
References UE_API.
Field Documentation
NodeInstance
FNodeInstance* UE::AnimNext::FWeakTraitPtr::NodeInstance = nullptr private
Definition at line 129 of file TraitPtr.h.
Referenced by FWeakTraitPtr(), GetNodeInstance(), IsValid(), operator!=(), operator!=(), operator==(), and operator==().
TraitIndex
uint32 UE::AnimNext::FWeakTraitPtr::TraitIndex = 0 private
Definition at line 130 of file TraitPtr.h.
Referenced by FWeakTraitPtr(), GetTraitIndex(), operator!=(), operator!=(), operator==(), and operator==().
The documentation for this struct was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Experimental/AnimNextAnimGraph/Source/AnimNextAnimGraph/Public/TraitCore/TraitPtr.h