Unreal Engine 5.6 C++ API: FAddPropertyParams Struct Reference
FAddPropertyParams Struct Reference
Parameters required for specifying behavior when adding external properties from detail customizations.
#include "DetailBuilderTypes.h"
Public Member Functions
FAddPropertyParams ()
FAddPropertyParams & AllowChildren (bool bAllowChildren)
Override whether the property node should allow children or not.
FAddPropertyParams & CreateCategoryNodes (bool bCreateCategoryNodes)
Override whether the property node should create category nodes or not.
FAddPropertyParams & ForceShowProperty ()
Forcibly show the property, even if it does not have CPF_Edit.
FName GetUniqueId () const
Get this property's unique ID name.
FAddPropertyParams & HideRootObjectNode (bool bInHideRootObjectNode)
Override whether the root object node should be shown for external object properties.
void OverrideAllowChildren (bool &OutAllowChildren) const
Conditionally overwrites the specified boolean with a value specifying whether to allow child properties or not.
void OverrideCreateCategoryNodes (bool &OutCreateCategoryNodes) const
Conditionally overwrites the specified boolean with a value specifying whether to create category nodes or not Only overrides the value if the calling code specified an override.
bool ShouldForcePropertyVisible () const
Check whether to forcibly show the property, even if it does not have CPF_Edit.
bool ShouldHideRootObjectNode () const
FAddPropertyParams & UniqueId (FName InUniqueId)
Set a unique name for this property, allowing it to correctly save expansion states and other persistent UI state.
Private Attributes
TOptional< bool > bAllowChildrenOverride
Tristate override for allowing children - if value is true: Allow Children, false: Disallow Children, unset: no override.
TOptional< bool > bCreateCategoryNodesOverride
Tristate override for allowing children - if value is true: create category nodes, false: do not create category nodes, unset: no override.
bool bForceShowProperty: 1
When true, the property will be forcefully shown, even if it does not have CPF_Edit.
bool bHideRootObjectNode: 1
When true any root ObjectPropertyNode generated from an external UObject being added will be hidden from view and only its children are shown.
FName UniqueIdName
Unique ID name that is used for saving persistent UI state such as expansion.
Detailed Description
Parameters required for specifying behavior when adding external properties from detail customizations.
Definition at line 12 of file DetailBuilderTypes.h.
Constructor & Destructor Documentation
FAddPropertyParams()
FAddPropertyParams::FAddPropertyParams () inline
Definition at line 14 of file DetailBuilderTypes.h.
References bForceShowProperty, and bHideRootObjectNode.
Referenced by AllowChildren(), CreateCategoryNodes(), ForceShowProperty(), HideRootObjectNode(), and UniqueId().
Member Function Documentation
AllowChildren()
FAddPropertyParams & FAddPropertyParams::AllowChildren (bool bAllowChildren) inline
Override whether the property node should allow children or not.
If not overridden the default is implementation defined.
Definition at line 33 of file DetailBuilderTypes.h.
References FAddPropertyParams(), and bAllowChildrenOverride.
CreateCategoryNodes()
FAddPropertyParams & FAddPropertyParams::CreateCategoryNodes (bool bCreateCategoryNodes) inline
Override whether the property node should create category nodes or not.
If not overridden the default is implementation defined.
Definition at line 43 of file DetailBuilderTypes.h.
References FAddPropertyParams(), and bCreateCategoryNodesOverride.
ForceShowProperty()
FAddPropertyParams & FAddPropertyParams::ForceShowProperty () inline
Forcibly show the property, even if it does not have CPF_Edit.
Definition at line 23 of file DetailBuilderTypes.h.
References FAddPropertyParams(), and bForceShowProperty.
GetUniqueId()
FName FAddPropertyParams::GetUniqueId () const inline
Get this property's unique ID name.
Definition at line 108 of file DetailBuilderTypes.h.
References UniqueIdName.
HideRootObjectNode()
FAddPropertyParams & FAddPropertyParams::HideRootObjectNode (bool bInHideRootObjectNode) inline
Override whether the root object node should be shown for external object properties.
This only applies when adding an entire uobject's properties to the details panel rather than an individual row or struct
Definition at line 63 of file DetailBuilderTypes.h.
References FAddPropertyParams(), and bHideRootObjectNode.
OverrideAllowChildren()
void FAddPropertyParams::OverrideAllowChildren (bool & OutAllowChildren) const inline
Conditionally overwrites the specified boolean with a value specifying whether to allow child properties or not.
Only overrides the value if the calling code specified an override
Definition at line 83 of file DetailBuilderTypes.h.
References bAllowChildrenOverride.
OverrideCreateCategoryNodes()
void FAddPropertyParams::OverrideCreateCategoryNodes (bool & OutCreateCategoryNodes) const inline
Conditionally overwrites the specified boolean with a value specifying whether to create category nodes or not Only overrides the value if the calling code specified an override.
Definition at line 96 of file DetailBuilderTypes.h.
References bCreateCategoryNodesOverride.
ShouldForcePropertyVisible()
bool FAddPropertyParams::ShouldForcePropertyVisible () const inline
Check whether to forcibly show the property, even if it does not have CPF_Edit.
Definition at line 72 of file DetailBuilderTypes.h.
References bForceShowProperty.
ShouldHideRootObjectNode()
bool FAddPropertyParams::ShouldHideRootObjectNode () const inline
Definition at line 77 of file DetailBuilderTypes.h.
References bHideRootObjectNode.
UniqueId()
FAddPropertyParams & FAddPropertyParams::UniqueId (FName InUniqueId) inline
Set a unique name for this property, allowing it to correctly save expansion states and other persistent UI state.
Definition at line 53 of file DetailBuilderTypes.h.
References FAddPropertyParams(), and UniqueIdName.
Field Documentation
bAllowChildrenOverride
TOptional<bool> FAddPropertyParams::bAllowChildrenOverride private
Tristate override for allowing children - if value is true: Allow Children, false: Disallow Children, unset: no override.
Definition at line 122 of file DetailBuilderTypes.h.
Referenced by AllowChildren(), and OverrideAllowChildren().
bCreateCategoryNodesOverride
TOptional<bool> FAddPropertyParams::bCreateCategoryNodesOverride private
Tristate override for allowing children - if value is true: create category nodes, false: do not create category nodes, unset: no override.
Definition at line 125 of file DetailBuilderTypes.h.
Referenced by CreateCategoryNodes(), and OverrideCreateCategoryNodes().
bForceShowProperty
bool FAddPropertyParams::bForceShowProperty private
When true, the property will be forcefully shown, even if it does not have CPF_Edit.
When false the property will only be created if it has CPF_Edit.
Definition at line 116 of file DetailBuilderTypes.h.
Referenced by FAddPropertyParams(), ForceShowProperty(), and ShouldForcePropertyVisible().
bHideRootObjectNode
bool FAddPropertyParams::bHideRootObjectNode private
When true any root ObjectPropertyNode generated from an external UObject being added will be hidden from view and only its children are shown.
Definition at line 119 of file DetailBuilderTypes.h.
Referenced by FAddPropertyParams(), HideRootObjectNode(), and ShouldHideRootObjectNode().
UniqueIdName
FName FAddPropertyParams::UniqueIdName private
Unique ID name that is used for saving persistent UI state such as expansion.
Definition at line 128 of file DetailBuilderTypes.h.
Referenced by GetUniqueId(), and UniqueId().
The documentation for this struct was generated from the following file:
Editor/PropertyEditor/Public/DetailBuilderTypes.h