Unreal Engine 5.6 C++ API: FStateTreeMinimalExecutionContext Struct Reference
FStateTreeMinimalExecutionContext Struct Reference
Minimal execution context to interact with the state tree instance data.
#include "StateTreeExecutionContext.h"
Public Member Functions
STATETREEMODULE_API FStateTreeMinimalExecutionContext (TNotNull< UObject * > Owner, TNotNull< const UStateTree * > StateTree, FStateTreeInstanceData &InInstanceData)
STATETREEMODULE_API FStateTreeMinimalExecutionContext (TNotNull< UObject * > Owner, TNotNull< const UStateTree * > StateTree, FStateTreeInstanceStorage &Storage)
virtual STATETREEMODULE_API ~FStateTreeMinimalExecutionContext ()
STATETREEMODULE_API UE::StateTree::FScheduledTickHandle AddScheduledTickRequest (FStateTreeScheduledTick ScheduledTick)
Adds a scheduled tick request.
STATETREEMODULE_API void RemoveScheduledTickRequest (UE::StateTree::FScheduledTickHandle Handle)
Removes a scheduled tick request.
STATETREEMODULE_API void SendEvent (const FGameplayTag Tag, const FConstStructView Payload=FConstStructView(), const FName Origin=FName())
Sends event for the StateTree.
UE_DEPRECATED (5.6, "Use FStateTreeMinimalExecutionContext with the not null pointer.") STATETREEMODULE_API explicit FStateTreeMinimalExecutionContext(UObject &Owner
UE_DEPRECATED (5.6, "Use FStateTreeMinimalExecutionContext with the not null pointer.") STATETREEMODULE_API explicit FStateTreeMinimalExecutionContext(UObject &Owner
STATETREEMODULE_API void UpdateScheduledTickRequest (UE::StateTree::FScheduledTickHandle Handle, FStateTreeScheduledTick ScheduledTick)
Updates the scheduled tick of a previous request.
Public Member Functions inherited from FStateTreeReadOnlyExecutionContext
STATETREEMODULE_API FStateTreeReadOnlyExecutionContext (TNotNull< UObject * > Owner, TNotNull< const UStateTree * > StateTree, FStateTreeInstanceData &InInstanceData)
STATETREEMODULE_API FStateTreeReadOnlyExecutionContext (TNotNull< UObject * > Owner, TNotNull< const UStateTree * > StateTree, FStateTreeInstanceStorage &Storage)
virtual STATETREEMODULE_API ~FStateTreeReadOnlyExecutionContext ()
STATETREEMODULE_API void DebugPrintInternalLayout ()
STATETREEMODULE_API TConstArrayView< FStateTreeExecutionFrame > GetActiveFrames () const
STATETREEMODULE_API FString GetActiveStateName () const
STATETREEMODULE_API TArray< FName > GetActiveStateNames () const
STATETREEMODULE_API EStateTreeRunStatus GetLastTickStatus () const
STATETREEMODULE_API FStateTreeScheduledTick GetNextScheduledTick () const
UObject * GetOwner () const
STATETREEMODULE_API int32 GetStateChangeCount () const
const FCompactStateTreeState * GetStateFromHandle (const FStateTreeStateHandle StateHandle) const
const UStateTree * GetStateTree () const
STATETREEMODULE_API EStateTreeRunStatus GetStateTreeRunStatus () const
UWorld * GetWorld () const
bool HasEventToProcess (const FGameplayTag Tag) const
bool IsValid () const
Indicates if the instance is valid and would be able to run the instance of the associated StateTree asset with a regular execution context.
Data Fields
const UStateTree FStateTreeInstanceData & InInstanceData
const UStateTree & StateTree
const UStateTree FStateTreeInstanceStorage & Storage
Protected Member Functions
STATETREEMODULE_API void ScheduleNextTick ()
Informs the owner when the instance of the tree must woke up from a scheduled tick sleep.
Protected Member Functions inherited from FStateTreeReadOnlyExecutionContext
STATETREEMODULE_API FString GetInstanceDescriptionInternal () const
Protected Attributes
bool bAllowedToScheduleNextTick = true
The context is processing the tree.
Protected Attributes inherited from FStateTreeReadOnlyExecutionContext
UObject & Owner
Owner of the instance data.
const UStateTree & RootStateTree
The StateTree asset the context is initialized for.
FStateTreeInstanceStorage & Storage
Data storage of the instance data.
Private Member Functions
FStateTreeMinimalExecutionContext (const FStateTreeMinimalExecutionContext &)=delete
FStateTreeMinimalExecutionContext & operator= (const FStateTreeMinimalExecutionContext &)=delete
Detailed Description
Minimal execution context to interact with the state tree instance data.
A regular execution context requires the context data and external data to be valid to execute all possible operations. The minimal execution context doesn't requires those data but supports only a subset of operations.
Definition at line 171 of file StateTreeExecutionContext.h.
Constructor & Destructor Documentation
FStateTreeMinimalExecutionContext() [1/3]
STATETREEMODULE_API FStateTreeMinimalExecutionContext::FStateTreeMinimalExecutionContext (TNotNull< UObject * > Owner, TNotNull< const UStateTree * > StateTree, FStateTreeInstanceData & InInstanceData) explicit
References FStateTreeMinimalExecutionContext(), InInstanceData, FStateTreeReadOnlyExecutionContext::Owner, StateTree, and UE_API.
Referenced by FStateTreeMinimalExecutionContext(), FStateTreeMinimalExecutionContext(), FStateTreeMinimalExecutionContext(), ~FStateTreeMinimalExecutionContext(), and operator=().
FStateTreeMinimalExecutionContext() [2/3]
STATETREEMODULE_API FStateTreeMinimalExecutionContext::FStateTreeMinimalExecutionContext (TNotNull< UObject * > Owner, TNotNull< const UStateTree * > StateTree, FStateTreeInstanceStorage & Storage) explicit
References FStateTreeMinimalExecutionContext(), FStateTreeReadOnlyExecutionContext::Owner, StateTree, Storage, and UE_API.
~FStateTreeMinimalExecutionContext()
virtual STATETREEMODULE_API FStateTreeMinimalExecutionContext::~FStateTreeMinimalExecutionContext () virtual
References FStateTreeMinimalExecutionContext(), and UE_API.
FStateTreeMinimalExecutionContext() [3/3]
FStateTreeMinimalExecutionContext::FStateTreeMinimalExecutionContext (const FStateTreeMinimalExecutionContext &) private delete
References FStateTreeMinimalExecutionContext().
Member Function Documentation
AddScheduledTickRequest()
STATETREEMODULE_API UE::StateTree::FScheduledTickHandle FStateTreeMinimalExecutionContext::AddScheduledTickRequest (FStateTreeScheduledTick ScheduledTick)
Adds a scheduled tick request.
The result of GetNextScheduledTick is affected by the request. This allows a specific task to control when the tree ticks.
Note
A request with a higher priority will supersede all other requests. ex: Task A request a custom time of 1FPS and Task B request a custom time of 2FPS. Both tasks will tick at 1FPS.
References AddScheduledTickRequest(), StateTree, and UE_API.
Referenced by AddScheduledTickRequest().
operator=()
FStateTreeMinimalExecutionContext & FStateTreeMinimalExecutionContext::operator= (const FStateTreeMinimalExecutionContext &) private delete
References FStateTreeMinimalExecutionContext().
RemoveScheduledTickRequest()
STATETREEMODULE_API void FStateTreeMinimalExecutionContext::RemoveScheduledTickRequest (UE::StateTree::FScheduledTickHandle Handle)
Removes a scheduled tick request.
References Handle, RemoveScheduledTickRequest(), StateTree, and UE_API.
Referenced by RemoveScheduledTickRequest().
ScheduleNextTick()
STATETREEMODULE_API void FStateTreeMinimalExecutionContext::ScheduleNextTick () protected
Informs the owner when the instance of the tree must woke up from a scheduled tick sleep.
References UE_API.
SendEvent()
STATETREEMODULE_API void FStateTreeMinimalExecutionContext::SendEvent (const FGameplayTag Tag, const FConstStructView Payload = FConstStructView(), const FName Origin = FName())
Sends event for the StateTree.
References ensureMsgf, MoveTemp(), Origin, SendEvent(), TEXT, and UE_API.
Referenced by SendEvent().
UE_DEPRECATED() [1/2]
FStateTreeMinimalExecutionContext::UE_DEPRECATED (5. 6, "Use FStateTreeMinimalExecutionContext with the not null pointer.") &
Referenced by UE_DEPRECATED().
UE_DEPRECATED() [2/2]
FStateTreeMinimalExecutionContext::UE_DEPRECATED (5. 6, "Use FStateTreeMinimalExecutionContext with the not null pointer.") &
References UE_DEPRECATED().
UpdateScheduledTickRequest()
STATETREEMODULE_API void FStateTreeMinimalExecutionContext::UpdateScheduledTickRequest (UE::StateTree::FScheduledTickHandle Handle, FStateTreeScheduledTick ScheduledTick)
Updates the scheduled tick of a previous request.
References Handle, StateTree, UE_API, and UpdateScheduledTickRequest().
Referenced by UpdateScheduledTickRequest().
Field Documentation
bAllowedToScheduleNextTick
bool FStateTreeMinimalExecutionContext::bAllowedToScheduleNextTick = true protected
The context is processing the tree.
We do not need to inform the owner that something changed.
Definition at line 230 of file StateTreeExecutionContext.h.
InInstanceData
const UStateTree FStateTreeInstanceData& FStateTreeMinimalExecutionContext::InInstanceData
Definition at line 175 of file StateTreeExecutionContext.h.
Referenced by FStateTreeExecutionContext::FStateTreeExecutionContext(), FStateTreeExecutionContext::FStateTreeExecutionContext(), FStateTreeExecutionContext::FStateTreeExecutionContext(), FStateTreeExecutionContext::FStateTreeExecutionContext(), FStateTreeMinimalExecutionContext(), FStateTreeExecutionContext::UE_DEPRECATED(), and FStateTreeExecutionContext::UE_DEPRECATED().
StateTree
const UStateTree & FStateTreeMinimalExecutionContext::StateTree
Definition at line 175 of file StateTreeExecutionContext.h.
Referenced by FStateTreeExecutionContext::FStateTreeExecutionContext(), FStateTreeExecutionContext::FStateTreeExecutionContext(), FStateTreeMinimalExecutionContext(), FStateTreeMinimalExecutionContext(), AddScheduledTickRequest(), FStateTreeExecutionContext::CollectExternalData(), FStateTreeExecutionContext::FindFrame(), FStateTreeExecutionContext::FinishTask(), FStateTreeExecutionContext::MakeRecordedTransitionResult(), RemoveScheduledTickRequest(), FStateTreeExecutionContext::UE_DEPRECATED(), and UpdateScheduledTickRequest().
Storage
const UStateTree FStateTreeInstanceStorage& FStateTreeMinimalExecutionContext::Storage
Definition at line 177 of file StateTreeExecutionContext.h.
Referenced by FStateTreeMinimalExecutionContext(), FStateTreeExecutionContext::GetExecState(), and FStateTreeExecutionContext::GetExecState().
The documentation for this struct was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/StateTree/Source/StateTreeModule/Public/StateTreeExecutionContext.h