Unreal Engine 5.6 C++ API: FRigVMStringTag Struct Reference
FRigVMStringTag Struct Reference
#include "RigVMEdGraph.h"
Public Member Functions
FRigVMStringTag ()
FRigVMStringTag (const FName &InName, const FLinearColor &InColor)
bool Equals (const FName &InOther) const
bool Equals (const FRigVMStringTag &InOther) const
const FLinearColor & GetColor () const
const FName & GetName () const
bool IsValid () const
Private Attributes
FLinearColor Color
FName Name
Detailed Description
Definition at line 16 of file RigVMEdGraph.h.
Constructor & Destructor Documentation
FRigVMStringTag() [1/2]
FRigVMStringTag::FRigVMStringTag () inline
Definition at line 20 of file RigVMEdGraph.h.
References Color, Name, and Red.
Referenced by Equals().
FRigVMStringTag() [2/2]
FRigVMStringTag::FRigVMStringTag (const FName & InName, const FLinearColor & InColor) inline explicit
Definition at line 25 of file RigVMEdGraph.h.
References Color, InName, and Name.
Member Function Documentation
Equals() [1/2]
bool FRigVMStringTag::Equals (const FName & InOther) const inline
Definition at line 46 of file RigVMEdGraph.h.
References CaseSensitive, GetName(), and FName::IsEqual().
Referenced by Equals().
Equals() [2/2]
bool FRigVMStringTag::Equals (const FRigVMStringTag & InOther) const inline
Definition at line 51 of file RigVMEdGraph.h.
References FRigVMStringTag(), Equals(), and GetName().
GetColor()
const FLinearColor & FRigVMStringTag::GetColor () const inline
Definition at line 36 of file RigVMEdGraph.h.
References Color.
GetName()
const FName & FRigVMStringTag::GetName () const inline
Definition at line 31 of file RigVMEdGraph.h.
References Name.
Referenced by Equals(), and Equals().
IsValid()
bool FRigVMStringTag::IsValid () const inline
Definition at line 41 of file RigVMEdGraph.h.
References Name.
Field Documentation
Color
FLinearColor FRigVMStringTag::Color private
Definition at line 58 of file RigVMEdGraph.h.
Referenced by FRigVMStringTag(), FRigVMStringTag(), and GetColor().
Name
FName FRigVMStringTag::Name private
Definition at line 57 of file RigVMEdGraph.h.
Referenced by FRigVMStringTag(), FRigVMStringTag(), GetName(), and IsValid().
The documentation for this struct was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/RigVM/Source/RigVMDeveloper/Public/EdGraph/RigVMEdGraph.h