Unreal Engine 5.6 C++ API: UE::Sequencer::FViewModelSubListIterator Struct Reference
UE::Sequencer::FViewModelSubListIterator Struct Reference
Iterates all models that exist in a single list from the start model.
#include "ViewModelIterators.h"
Public Member Functions
FViewModelSubListIterator ()=default
FViewModelSubListIterator (const FViewModelListHead *List)
FViewModelSubListIterator (TSharedPtr< FViewModel > InStart)
FORCEINLINE FViewModelSubListIterator begin () const
FORCEINLINE FViewModelSubListIterator end () const
FORCEINLINE FViewModelPtr GetCurrentItem () const
Gets the pointed-to data model.
FORCEINLINE operator bool () const
Returns whether the iterator is pointing to a valid data model.
FORCEINLINE const FViewModelPtr & operator* () const
Dereferences the iterator to the pointed-to data model.
FORCEINLINE void operator++ ()
Moves to the next sibling of the pointed-to data model.
FORCEINLINE FViewModel * operator-> () const
Dereferences the iterator to the pointed-to data model.
TArray< FViewModelPtr > ToArray () const
Return the remaining items in this iterator as an array The state of this iterator remains unchanged.
void ToArray (TArray< FViewModelPtr > &OutArray) const
Populate the specified array with the remaining items in this iterator The state of this iterator remains unchanged.
Private Attributes
FViewModelIterationState State
The pointed-to data model.
Friends
FORCEINLINE friend bool operator!= (const FViewModelSubListIterator &A, const FViewModelSubListIterator &B)
Returns whether iterators point to the same data models.
Detailed Description
Iterates all models that exist in a single list from the start model.
Definition at line 54 of file ViewModelIterators.h.
Constructor & Destructor Documentation
FViewModelSubListIterator() [1/3]
UE::Sequencer::FViewModelSubListIterator::FViewModelSubListIterator () default
Referenced by begin(), end(), operator!=, and ToArray().
FViewModelSubListIterator() [2/3]
UE::Sequencer::FViewModelSubListIterator::FViewModelSubListIterator (const FViewModelListHead * List) inline explicit
Definition at line 58 of file ViewModelIterators.h.
References State.
FViewModelSubListIterator() [3/3]
UE::Sequencer::FViewModelSubListIterator::FViewModelSubListIterator (TSharedPtr< FViewModel > InStart) inline explicit
Definition at line 62 of file ViewModelIterators.h.
References State.
Member Function Documentation
begin()
FORCEINLINE FViewModelSubListIterator UE::Sequencer::FViewModelSubListIterator::begin () const inline
Definition at line 83 of file ViewModelIterators.h.
References FViewModelSubListIterator(), and FORCEINLINE.
end()
FORCEINLINE FViewModelSubListIterator UE::Sequencer::FViewModelSubListIterator::end () const inline
Definition at line 84 of file ViewModelIterators.h.
References FViewModelSubListIterator(), and FORCEINLINE.
GetCurrentItem()
FORCEINLINE FViewModelPtr UE::Sequencer::FViewModelSubListIterator::GetCurrentItem () const inline
Gets the pointed-to data model.
Definition at line 81 of file ViewModelIterators.h.
References FORCEINLINE, and State.
operator bool()
FORCEINLINE UE::Sequencer::FViewModelSubListIterator::operator bool () const inline explicit
Returns whether the iterator is pointing to a valid data model.
Definition at line 70 of file ViewModelIterators.h.
References FORCEINLINE, and State.
operator*()
FORCEINLINE const FViewModelPtr & UE::Sequencer::FViewModelSubListIterator::operator* () const inline
Dereferences the iterator to the pointed-to data model.
Definition at line 75 of file ViewModelIterators.h.
References FORCEINLINE, and State.
operator++()
FORCEINLINE void UE::Sequencer::FViewModelSubListIterator::operator++ () inline
Moves to the next sibling of the pointed-to data model.
Definition at line 78 of file ViewModelIterators.h.
References check, FORCEINLINE, and State.
operator->()
FORCEINLINE FViewModel * UE::Sequencer::FViewModelSubListIterator::operator-> () const inline
Dereferences the iterator to the pointed-to data model.
Definition at line 73 of file ViewModelIterators.h.
References check, FORCEINLINE, and State.
ToArray() [1/2]
TArray< FViewModelPtr > UE::Sequencer::FViewModelSubListIterator::ToArray () const inline
Return the remaining items in this iterator as an array The state of this iterator remains unchanged.
Definition at line 102 of file ViewModelIterators.h.
References ToArray().
Referenced by ToArray().
ToArray() [2/2]
void UE::Sequencer::FViewModelSubListIterator::ToArray (TArray< FViewModelPtr > & OutArray) const inline
Populate the specified array with the remaining items in this iterator The state of this iterator remains unchanged.
Definition at line 90 of file ViewModelIterators.h.
References FViewModelSubListIterator(), and TArray< InElementType, InAllocatorType >::Add().
Friends And Related Symbol Documentation
operator!=
FORCEINLINE friend bool operator!= (const FViewModelSubListIterator & A, const FViewModelSubListIterator & B) friend
Returns whether iterators point to the same data models.
Definition at line 67 of file ViewModelIterators.h.
References FViewModelSubListIterator(), A, B, and FORCEINLINE.
Field Documentation
State
FViewModelIterationState UE::Sequencer::FViewModelSubListIterator::State private
The pointed-to data model.
Definition at line 112 of file ViewModelIterators.h.
Referenced by FViewModelSubListIterator(), FViewModelSubListIterator(), GetCurrentItem(), operator bool(), operator*(), operator++(), and operator->().
The documentation for this struct was generated from the following file:
Editor/SequencerCore/Public/MVVM/ViewModels/ViewModelIterators.h