Unreal Engine 5.6 C++ API: UE::MovieScene::FEntityHandle Struct Reference
UE::MovieScene::FEntityHandle Struct Reference
#include "MovieSceneEntityIDs.h"
Public Member Functions
FEntityHandle ()
FMovieSceneEntityID GetEntityID () const
bool IsEmpty () const
MOVIESCENE_API bool IsValid (const FEntityManager &) const
Private Member Functions
FEntityHandle (FMovieSceneEntityID InEntityID, uint32 InHandleGeneration)
Private Attributes
friend FEntityManager
uint32 HandleGeneration
FMovieSceneEntityID ID
Friends
uint32 GetTypeHash (FEntityHandle In)
bool operator< (FEntityHandle A, FEntityHandle B)
bool operator== (FEntityHandle A, FEntityHandle B)
Detailed Description
Definition at line 370 of file MovieSceneEntityIDs.h.
Constructor & Destructor Documentation
FEntityHandle() [1/2]
UE::MovieScene::FEntityHandle::FEntityHandle () inline
Definition at line 372 of file MovieSceneEntityIDs.h.
References HandleGeneration.
Referenced by GetTypeHash, operator<, and operator==.
FEntityHandle() [2/2]
UE::MovieScene::FEntityHandle::FEntityHandle (FMovieSceneEntityID InEntityID, uint32 InHandleGeneration) inline explicit private
Definition at line 409 of file MovieSceneEntityIDs.h.
References HandleGeneration, and ID.
Member Function Documentation
GetEntityID()
FMovieSceneEntityID UE::MovieScene::FEntityHandle::GetEntityID () const inline
Definition at line 402 of file MovieSceneEntityIDs.h.
References ID.
IsEmpty()
bool UE::MovieScene::FEntityHandle::IsEmpty () const inline
Definition at line 376 of file MovieSceneEntityIDs.h.
References ID.
IsValid()
MOVIESCENE_API bool UE::MovieScene::FEntityHandle::IsValid (const FEntityManager &) const
References FEntityManager.
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (FEntityHandle In) friend
Definition at line 397 of file MovieSceneEntityIDs.h.
References FEntityHandle(), GetTypeHash, and ID.
Referenced by GetTypeHash.
operator<
bool operator< (FEntityHandle A, FEntityHandle B) friend
Definition at line 383 of file MovieSceneEntityIDs.h.
References FEntityHandle(), A, and B.
operator==
bool operator== (FEntityHandle A, FEntityHandle B) friend
Definition at line 392 of file MovieSceneEntityIDs.h.
References FEntityHandle(), A, and B.
Field Documentation
FEntityManager
friend UE::MovieScene::FEntityHandle::FEntityManager private
Definition at line 413 of file MovieSceneEntityIDs.h.
Referenced by IsValid().
HandleGeneration
uint32 UE::MovieScene::FEntityHandle::HandleGeneration private
Definition at line 414 of file MovieSceneEntityIDs.h.
Referenced by FEntityHandle(), and FEntityHandle().
ID
FMovieSceneEntityID UE::MovieScene::FEntityHandle::ID private
Definition at line 415 of file MovieSceneEntityIDs.h.
Referenced by FEntityHandle(), GetEntityID(), GetTypeHash, and IsEmpty().
The documentation for this struct was generated from the following file:
Runtime/MovieScene/Public/EntitySystem/MovieSceneEntityIDs.h