Unreal Engine 5.6 C++ API: FStructArrayView Struct Reference
FStructArrayView Struct Reference
A generic, transient view of a homogeneously-typed array of instances of a specific UScriptStruct FStructArrayView supplies mutable access to the elements of the Array.
#include "StructArrayView.h"
Data Structures
struct FIterator
Public Member Functions
FStructArrayView ()=default
FStructArrayView (const UScriptStruct &InScriptStruct, void *InData, const int32 InCount)
FStructArrayView (const UScriptStruct *InScriptStruct, void *InData, const uint32 InElementSize, const int32 InCount)
template<typename T>
FStructArrayView (TArray< T > &InArray)
template<typename T>
FStructArrayView (TArrayView< T > InArrayView)
void const int32 ArrayNum (InCount)
FORCEINLINE FIterator begin () const
Ranged iteration support.
void CheckInvariants () const
Checks array invariants: if array size is greater than or equal to zero.
void const int32 ElementSize (InScriptStruct->GetStructureSize())
FORCEINLINE FIterator end () const
template<typename T>
T & GetAt (const int32 Index) const
Returns reference to element at given index.
void * GetData () const
Helper function for returning a pointer to the first array element.
void * GetDataAt (const int32 Index) const
Helper function for returning a pointer to an element in the array.
template<typename T>
T * GetPtrAt (const int32 Index) const
Returns pointer to element at given index.
const UScriptStruct * GetScriptStruct () const
Returns struct type.
FORCEINLINE_DEBUGGABLE uint32 GetTypeSize () const
Helper function returning the size of the inner type.
bool IsEmpty () const
Returns true if the array is empty and contains no elements.
bool IsValidIndex (const int32 Index) const
Tests if index is valid, i.e.
template<typename T>
T & Last (const int32 IndexFromTheEnd=0) const
Returns n-th last element from the array.
FStructArrayView Left (const int32 Count) const
Returns the left-most part of the view by taking the given number of elements from the left.
FStructArrayView LeftChop (const int32 Count) const
Returns the left-most part of the view by chopping the given number of elements from the right.
void LeftChopInline (const int32 Count)
Modifies the view by chopping the given number of elements from the right.
void LeftInline (const int32 Count)
Modifies the view to be the given number of elements from the left.
FStructArrayView Mid (int32 Index, int32 Count=TNumericLimits< int32 >::Max()) const
Returns the middle part of the view by taking up to the given number of elements from the given position.
void MidInline (const int32 Position, const int32 Count=TNumericLimits< int32 >::Max())
Modifies the view to be the middle part by taking up to the given number of elements from the given position.
int32 Num () const
Returns number of elements in array.
FStructView operator[] (const int32 Index) const
Array bracket operator.
void RangeCheck (int32 Index) const
Checks if index is in array range.
FStructArrayView Right (const int32 Count) const
Returns the right-most part of the view by taking the given number of elements from the right.
FStructArrayView RightChop (const int32 Count) const
Returns the right-most part of the view by chopping the given number of elements from the left.
void RightChopInline (const int32 Count)
Modifies the view by chopping the given number of elements from the left.
void RightInline (const int32 Count)
Modifies the view to be the given number of elements from the right.
void const int32 ScriptStruct (InScriptStruct)
FStructArrayView Slice (const int32 Index, const int32 InNum) const
Returns a sliced view This is similar to Mid(), but with a narrow contract, i.e.
void SliceRangeCheck (const int32 Index, const int32 InNum) const
Checks if a slice range [Index, Index+InNum) is in array range.
FORCEINLINE void Swap (const int32 Index1, const int32 Index2)
Swaps the elements at the specified Indicies.
UE_DEPRECATED (5.3, "Removed to bring in to line with ArrayView, use GetTypeSize() instead") SIZE_T GetElementSize() const
UE_DEPRECATED (5.3, "Use constructor that takes a reference instead") FStructArrayView(const UScriptStruct *InScriptStruct
template<typename T>
UE_DEPRECATED (5.3, "Use GetAt() instead!") const T &GetElementAt(const int32 Index) const
template<typename T>
UE_DEPRECATED (5.3, "Use GetAt() instead!") const T &GetElementAtChecked(const int32 Index) const
template<typename T>
UE_DEPRECATED (5.3, "Use GetAt() instead!") T &GetMutableElementAt(const int32 Index) const
template<typename T>
UE_DEPRECATED (5.3, "Use GetAt() instead!") T &GetMutableElementAtChecked(const int32 Index) const
UE_DEPRECATED (5.3, "Use GetDataAt() instead") void *GetMutableDataAt(const int32 Index) const
UE_DEPRECATED (5.3, "Use GetScriptStruct() instead") const UScriptStruct &GetElementType() const
UE_DEPRECATED (5.3, "Use GetScriptStruct() instead") const UScriptStruct &GetFragmentType() const
Data Fields
void const int32 InCount: DataPtr(InData)
void * InData
Private Attributes
int32 ArrayNum = 0
void * DataPtr = nullptr
uint32 ElementSize = 0
const UScriptStruct * ScriptStruct = nullptr
Detailed Description
A generic, transient view of a homogeneously-typed array of instances of a specific UScriptStruct FStructArrayView supplies mutable access to the elements of the Array.
Note const FStructArrayView only what the view is pointing to can not be modified the actual struct data is still mutable. For a more indepth overview of the constness of views see FConstStructView
Definition at line 17 of file StructArrayView.h.
Constructor & Destructor Documentation
FStructArrayView() [1/5]
FStructArrayView::FStructArrayView () default
Referenced by FStructArrayView::FIterator::FIterator(), Left(), LeftChop(), Mid(), Right(), RightChop(), and Slice().
FStructArrayView() [2/5]
template<typename T> FStructArrayView::FStructArrayView (TArray< T > & InArray) inline explicit
Definition at line 22 of file StructArrayView.h.
References ArrayNum, DataPtr, ElementSize, GetData(), Num(), ScriptStruct, and StaticStruct().
FStructArrayView() [3/5]
template<typename T> FStructArrayView::FStructArrayView (TArrayView< T > InArrayView) inline explicit
Definition at line 30 of file StructArrayView.h.
References ArrayNum, DataPtr, ElementSize, GetData(), Num(), ScriptStruct, and StaticStruct().
FStructArrayView() [4/5]
FStructArrayView::FStructArrayView (const UScriptStruct * InScriptStruct, void * InData, const uint32 InElementSize, const int32 InCount) inline
Definition at line 37 of file StructArrayView.h.
References ArrayNum, check, DataPtr, ElementSize, InCount, InData, and ScriptStruct.
FStructArrayView() [5/5]
FStructArrayView::FStructArrayView (const UScriptStruct & InScriptStruct, void * InData, const int32 InCount) inline
Definition at line 47 of file StructArrayView.h.
References ArrayNum, check, DataPtr, ElementSize, InCount, InData, and ScriptStruct.
Member Function Documentation
ArrayNum()
void const int32 FStructArrayView::ArrayNum (InCount) inline
Definition at line 62 of file StructArrayView.h.
References ArrayNum, check, InCount, and InData.
begin()
FORCEINLINE FIterator FStructArrayView::begin () const inline
Ranged iteration support.
DO NOT USE DIRECTLY.
Definition at line 373 of file StructArrayView.h.
References FORCEINLINE.
CheckInvariants()
void FStructArrayView::CheckInvariants () const inline
Checks array invariants: if array size is greater than or equal to zero.
Definition at line 72 of file StructArrayView.h.
References ArrayNum, and checkSlow.
ElementSize()
void const int32 FStructArrayView::ElementSize (InScriptStruct-> GetStructureSize())
References ElementSize.
end()
FORCEINLINE FIterator FStructArrayView::end () const inline
Definition at line 374 of file StructArrayView.h.
References FORCEINLINE, and Num().
GetAt()
template<typename T> T & FStructArrayView::GetAt (const int32 Index) const inline
Returns reference to element at given index.
Index and template param T must be must be valid.
Parameters
Index Index of element
T Type of stuct, this must either be the type or a parent type of the struct type in the array.
Returns
Reference to indexed element.
Definition at line 200 of file StructArrayView.h.
References GetDataAt(), UE::StructUtils::GetStructRef(), and ScriptStruct.
Referenced by Last().
GetData()
void * FStructArrayView::GetData () const inline
Helper function for returning a pointer to the first array element.
Returns
Pointer to first array entry.
Definition at line 129 of file StructArrayView.h.
References DataPtr.
Referenced by FStructArrayView(), and FStructArrayView().
GetDataAt()
void * FStructArrayView::GetDataAt (const int32 Index) const inline
Helper function for returning a pointer to an element in the array.
Parameters
Index Index of element, this MUST be a valid element.
Returns
Pointer to array entry at index.
Definition at line 140 of file StructArrayView.h.
References DataPtr, ElementSize, and RangeCheck().
Referenced by GetAt(), GetPtrAt(), Mid(), operator[](), Right(), RightChop(), Slice(), Swap(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
GetPtrAt()
template<typename T> T * FStructArrayView::GetPtrAt (const int32 Index) const inline
Returns pointer to element at given index.
The index MUST be valid. If parametre T is invalid then nullptr will be returned.
Parameters
Index Index of element
T Type of stuct, this must either be the type or a parent type of the struct type in the array.
Returns
Pointer to indexed element.
Definition at line 187 of file StructArrayView.h.
References GetDataAt(), UE::StructUtils::GetStructPtr(), and ScriptStruct.
GetScriptStruct()
const UScriptStruct * FStructArrayView::GetScriptStruct () const inline
Returns struct type.
Definition at line 176 of file StructArrayView.h.
References ScriptStruct.
GetTypeSize()
FORCEINLINE_DEBUGGABLE uint32 FStructArrayView::GetTypeSize () const inline
Helper function returning the size of the inner type.
Returns
Size in bytes of array type.
Definition at line 154 of file StructArrayView.h.
References ElementSize, and FORCEINLINE_DEBUGGABLE.
IsEmpty()
bool FStructArrayView::IsEmpty () const inline
Returns true if the array is empty and contains no elements.
Returns
True if array is empty.
See also
Num
Definition at line 119 of file StructArrayView.h.
References ArrayNum.
IsValidIndex()
bool FStructArrayView::IsValidIndex (const int32 Index) const inline
Tests if index is valid, i.e.
greater than or equal to zero, and less than the number of elements in the array.
Parameters
Index Index to test.
Returns
True if index is valid. False otherwise.
Definition at line 108 of file StructArrayView.h.
References ArrayNum.
Last()
template<typename T> T & FStructArrayView::Last (const int32 IndexFromTheEnd = 0) const inline
Returns n-th last element from the array.
Parameters
IndexFromTheEnd (Optional) Index from the end of array. This MUST index a valid element. Default is 0.
Returns
Reference to n-th last element from the array.
Definition at line 254 of file StructArrayView.h.
References ArrayNum, and GetAt().
Left()
FStructArrayView FStructArrayView::Left (const int32 Count) const inline nodiscard
Returns the left-most part of the view by taking the given number of elements from the left.
Definition at line 276 of file StructArrayView.h.
References FStructArrayView(), ArrayNum, FMath::Clamp(), Count, DataPtr, ElementSize, and ScriptStruct.
LeftChop()
FStructArrayView FStructArrayView::LeftChop (const int32 Count) const inline nodiscard
Returns the left-most part of the view by chopping the given number of elements from the right.
Definition at line 282 of file StructArrayView.h.
References FStructArrayView(), ArrayNum, FMath::Clamp(), Count, DataPtr, ElementSize, and ScriptStruct.
LeftChopInline()
void FStructArrayView::LeftChopInline (const int32 Count) inline
Modifies the view by chopping the given number of elements from the right.
Definition at line 315 of file StructArrayView.h.
References Count, and LeftChop.
LeftInline()
void FStructArrayView::LeftInline (const int32 Count) inline
Modifies the view to be the given number of elements from the left.
Definition at line 309 of file StructArrayView.h.
References Count, and Left.
Mid()
FStructArrayView FStructArrayView::Mid (int32 Index, int32 Count = TNumericLimits<int32>::Max()) const inline nodiscard
Returns the middle part of the view by taking up to the given number of elements from the given position.
Definition at line 302 of file StructArrayView.h.
References FStructArrayView(), ArrayNum, UE::StructUtils::CalcMidIndexAndCount(), Count, ElementSize, GetDataAt(), and ScriptStruct.
Referenced by MidInline().
MidInline()
void FStructArrayView::MidInline (const int32 Position, const int32 Count = TNumericLimits<int32>::Max()) inline
Modifies the view to be the middle part by taking up to the given number of elements from the given position.
Definition at line 333 of file StructArrayView.h.
References Count, Mid(), and Position.
Num()
int32 FStructArrayView::Num () const inline
Returns number of elements in array.
Returns
Number of elements in array.
Definition at line 167 of file StructArrayView.h.
References ArrayNum.
Referenced by FStructArrayView(), FStructArrayView(), and end().
operator[]()
FStructView FStructArrayView::operator[] (const int32 Index) const inline
Array bracket operator.
Returns FStructView to element at given index. Index must be valid.
Returns
FStructView to indexed element.
Definition at line 240 of file StructArrayView.h.
References GetDataAt(), and ScriptStruct.
RangeCheck()
void FStructArrayView::RangeCheck (int32 Index) const inline
Checks if index is in array range.
Parameters
Index Index to check.
Definition at line 82 of file StructArrayView.h.
References ArrayNum, checkf, and TEXT.
Referenced by GetDataAt().
Right()
FStructArrayView FStructArrayView::Right (const int32 Count) const inline nodiscard
Returns the right-most part of the view by taking the given number of elements from the right.
Definition at line 288 of file StructArrayView.h.
References FStructArrayView(), ArrayNum, FMath::Clamp(), Count, ElementSize, GetDataAt(), and ScriptStruct.
RightChop()
FStructArrayView FStructArrayView::RightChop (const int32 Count) const inline nodiscard
Returns the right-most part of the view by chopping the given number of elements from the left.
Definition at line 295 of file StructArrayView.h.
References FStructArrayView(), ArrayNum, FMath::Clamp(), Count, ElementSize, GetDataAt(), and ScriptStruct.
RightChopInline()
void FStructArrayView::RightChopInline (const int32 Count) inline
Modifies the view by chopping the given number of elements from the left.
Definition at line 327 of file StructArrayView.h.
References Count, and RightChop.
RightInline()
void FStructArrayView::RightInline (const int32 Count) inline
Modifies the view to be the given number of elements from the right.
Definition at line 321 of file StructArrayView.h.
References Count, and Right.
ScriptStruct()
void const int32 FStructArrayView::ScriptStruct (InScriptStruct)
References ScriptStruct.
Slice()
FStructArrayView FStructArrayView::Slice (const int32 Index, const int32 InNum) const inline nodiscard
Returns a sliced view This is similar to Mid(), but with a narrow contract, i.e.
slicing outside of the range of the view is illegal.
Parameters
Index starting index of the new view
InNum number of elements in the new view
Returns
Sliced view
See also
Mid
Definition at line 269 of file StructArrayView.h.
References FStructArrayView(), ElementSize, GetDataAt(), ScriptStruct, and SliceRangeCheck().
SliceRangeCheck()
void FStructArrayView::SliceRangeCheck (const int32 Index, const int32 InNum) const inline
Checks if a slice range [Index, Index+InNum) is in array range.
Length is 0 is allowed on empty arrays; Index must be 0 in that case.
Parameters
Index Starting index of the slice.
InNum Length of the slice.
Definition at line 94 of file StructArrayView.h.
References ArrayNum, checkf, and TEXT.
Referenced by Slice().
Swap()
FORCEINLINE void FStructArrayView::Swap (const int32 Index1, const int32 Index2) inline
Swaps the elements at the specified Indicies.
The indicies must be valid!
Definition at line 377 of file StructArrayView.h.
References ElementSize, FORCEINLINE, GetDataAt(), and FMemory::Memswap().
UE_DEPRECATED() [1/9]
FStructArrayView::UE_DEPRECATED (5. 3, "Removed to bring in to line with ArrayView, use GetTypeSize() instead") const inline
Definition at line 159 of file StructArrayView.h.
References ElementSize.
UE_DEPRECATED() [2/9]
FStructArrayView::UE_DEPRECATED (5. 3, "Use constructor that takes a reference instead") const
UE_DEPRECATED() [3/9]
template<typename T> FStructArrayView::UE_DEPRECATED (5. 3, "Use GetAt() instead!") const & inline
Definition at line 206 of file StructArrayView.h.
References GetDataAt().
UE_DEPRECATED() [4/9]
template<typename T> FStructArrayView::UE_DEPRECATED (5. 3, "Use GetAt() instead!") const & inline
Definition at line 213 of file StructArrayView.h.
References check, TBaseStructureBase< T, bHasStaticStruct >::Get(), GetDataAt(), and ScriptStruct.
UE_DEPRECATED() [5/9]
template<typename T> FStructArrayView::UE_DEPRECATED (5. 3, "Use GetAt() instead!") const & inline
Definition at line 221 of file StructArrayView.h.
References GetDataAt().
UE_DEPRECATED() [6/9]
template<typename T> FStructArrayView::UE_DEPRECATED (5. 3, "Use GetAt() instead!") const & inline
Definition at line 228 of file StructArrayView.h.
References check, TBaseStructureBase< T, bHasStaticStruct >::Get(), GetDataAt(), and ScriptStruct.
UE_DEPRECATED() [7/9]
FStructArrayView::UE_DEPRECATED (5. 3, "Use GetDataAt() instead") const inline
Definition at line 146 of file StructArrayView.h.
References GetDataAt().
UE_DEPRECATED() [8/9]
FStructArrayView::UE_DEPRECATED (5. 3, "Use GetScriptStruct() instead") const & inline
Definition at line 169 of file StructArrayView.h.
References check, and ScriptStruct.
UE_DEPRECATED() [9/9]
FStructArrayView::UE_DEPRECATED (5. 3, "Use GetScriptStruct() instead") const & inline
Definition at line 172 of file StructArrayView.h.
References check, and ScriptStruct.
Field Documentation
ArrayNum
int32 FStructArrayView::ArrayNum = 0 private
Definition at line 386 of file StructArrayView.h.
Referenced by FStructArrayView(), FStructArrayView(), FStructArrayView(), FStructArrayView(), ArrayNum(), CheckInvariants(), IsEmpty(), IsValidIndex(), Last(), Left(), LeftChop(), Mid(), Num(), RangeCheck(), Right(), RightChop(), and SliceRangeCheck().
DataPtr
void* FStructArrayView::DataPtr = nullptr private
Definition at line 383 of file StructArrayView.h.
Referenced by FStructArrayView(), FStructArrayView(), FStructArrayView(), FStructArrayView(), GetData(), GetDataAt(), Left(), and LeftChop().
ElementSize
uint32 FStructArrayView::ElementSize = 0 private
Definition at line 385 of file StructArrayView.h.
Referenced by FStructArrayView(), FStructArrayView(), FStructArrayView(), FStructArrayView(), ElementSize(), GetDataAt(), GetTypeSize(), Left(), LeftChop(), Mid(), Right(), RightChop(), Slice(), Swap(), and UE_DEPRECATED().
InCount
void const int32 FStructArrayView::InCount
Definition at line 58 of file StructArrayView.h.
Referenced by FStructArrayView(), FStructArrayView(), and ArrayNum().
InData
void* FStructArrayView::InData
Definition at line 58 of file StructArrayView.h.
Referenced by FStructArrayView(), FStructArrayView(), and ArrayNum().
ScriptStruct
const UScriptStruct* FStructArrayView::ScriptStruct = nullptr private
Definition at line 384 of file StructArrayView.h.
Referenced by FStructArrayView(), FStructArrayView(), FStructArrayView(), FStructArrayView(), GetAt(), GetPtrAt(), GetScriptStruct(), Left(), LeftChop(), Mid(), operator[](), Right(), RightChop(), ScriptStruct(), Slice(), UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
The documentation for this struct was generated from the following file:
Runtime/CoreUObject/Public/StructUtils/StructArrayView.h