Unreal Engine 5.6 C++ API: FUObjectMigrationContext Struct Reference
FUObjectMigrationContext Struct Reference final
Structure that holds context for what we're intending to do during migration.
#include "UObjectMigrationContext.h"
Public Member Functions
EObjectMigrationRecvType GetObjectMigrationRecvType (const UObjectBase *Object) const
During migration, figure out the role of the object being received.
EObjectMigrationRecvType GetObjectMigrationRecvType (FRemoteObjectId ObjectId) const
EObjectMigrationSendType GetObjectMigrationSendType (const UObjectBase *Object) const
During migration, figure out the role of the object being sent.
EObjectMigrationSendType GetObjectMigrationSendType (FRemoteObjectId ObjectId) const
bool IsValid () const
Are the values of this context valid?
Static Public Member Functions
static const FUObjectMigrationContext *const GetCurrentMigrationContext ()
Gets the current Migration Context if it exists (only exists during actual object migrations)
Data Fields
EObjectMigrationSide MigrationSide = EObjectMigrationSide::Receive
Which side of the migration does this context apply to?
FRemoteTransactionId MultiServerCommitRequestId
If valid, the request id of the multi-server commit.
FRemoteObjectId ObjectId
The Object that is being migrated, it may not be the top-level UObject.
FRemoteServerId OwnerServerId
The (New) Owner of the ObjectId as a result of this migration.
FRemoteServerId PhysicsServerId
The Server that this Object's Physics reside on.
FRemoteServerId RemoteServerId
The ServerId on the other side of the migration.
Static Private Member Functions
static void SetCurrentMigrationContext (const FUObjectMigrationContext *NewMigrationContext)
Static Private Attributes
static const FUObjectMigrationContext * CurrentMigrationContext = nullptr
Friends
struct FScopedObjectMigrationContext
Detailed Description
Structure that holds context for what we're intending to do during migration.
Definition at line 57 of file UObjectMigrationContext.h.
Member Function Documentation
GetCurrentMigrationContext()
const FUObjectMigrationContext *const FUObjectMigrationContext::GetCurrentMigrationContext () inline static
Gets the current Migration Context if it exists (only exists during actual object migrations)
Definition at line 93 of file UObjectMigrationContext.h.
References checkf, CurrentMigrationContext, IsInGameThread(), and TEXT.
GetObjectMigrationRecvType() [1/2]
EObjectMigrationRecvType FUObjectMigrationContext::GetObjectMigrationRecvType (const UObjectBase * Object) const
During migration, figure out the role of the object being received.
References Object, and UE_API.
GetObjectMigrationRecvType() [2/2]
EObjectMigrationRecvType FUObjectMigrationContext::GetObjectMigrationRecvType (FRemoteObjectId ObjectId) const
References ObjectId, and UE_API.
GetObjectMigrationSendType() [1/2]
EObjectMigrationSendType FUObjectMigrationContext::GetObjectMigrationSendType (const UObjectBase * Object) const
During migration, figure out the role of the object being sent.
References Object, and UE_API.
GetObjectMigrationSendType() [2/2]
EObjectMigrationSendType FUObjectMigrationContext::GetObjectMigrationSendType (FRemoteObjectId ObjectId) const
References ObjectId, and UE_API.
IsValid()
bool FUObjectMigrationContext::IsValid () const
Are the values of this context valid?
References UE_API.
SetCurrentMigrationContext()
void FUObjectMigrationContext::SetCurrentMigrationContext (const FUObjectMigrationContext * NewMigrationContext) inline static private
Definition at line 104 of file UObjectMigrationContext.h.
References checkf, CurrentMigrationContext, IsInGameThread(), and TEXT.
Referenced by FScopedObjectMigrationContext::FScopedObjectMigrationContext(), and FScopedObjectMigrationContext::~FScopedObjectMigrationContext().
Friends And Related Symbol Documentation
FScopedObjectMigrationContext
friend struct FScopedObjectMigrationContext friend
Definition at line 101 of file UObjectMigrationContext.h.
References FScopedObjectMigrationContext.
Referenced by FScopedObjectMigrationContext.
Field Documentation
CurrentMigrationContext
const FUObjectMigrationContext* FUObjectMigrationContext::CurrentMigrationContext = nullptr inline static private
Definition at line 103 of file UObjectMigrationContext.h.
Referenced by GetCurrentMigrationContext(), and SetCurrentMigrationContext().
MigrationSide
EObjectMigrationSide FUObjectMigrationContext::MigrationSide = EObjectMigrationSide::Receive
Which side of the migration does this context apply to?
Sending or Receiving?
Definition at line 72 of file UObjectMigrationContext.h.
MultiServerCommitRequestId
FRemoteTransactionId FUObjectMigrationContext::MultiServerCommitRequestId
If valid, the request id of the multi-server commit.
Definition at line 75 of file UObjectMigrationContext.h.
ObjectId
FRemoteObjectId FUObjectMigrationContext::ObjectId
The Object that is being migrated, it may not be the top-level UObject.
Definition at line 60 of file UObjectMigrationContext.h.
Referenced by GetObjectMigrationRecvType(), and GetObjectMigrationSendType().
OwnerServerId
FRemoteServerId FUObjectMigrationContext::OwnerServerId
The (New) Owner of the ObjectId as a result of this migration.
Definition at line 66 of file UObjectMigrationContext.h.
PhysicsServerId
FRemoteServerId FUObjectMigrationContext::PhysicsServerId
The Server that this Object's Physics reside on.
Definition at line 69 of file UObjectMigrationContext.h.
RemoteServerId
FRemoteServerId FUObjectMigrationContext::RemoteServerId
The ServerId on the other side of the migration.
Definition at line 63 of file UObjectMigrationContext.h.
The documentation for this struct was generated from the following file:
Runtime/CoreUObject/Internal/UObject/UObjectMigrationContext.h