Unreal Engine 5.6 C++ API: UE::Slate::Containers::TObservableArrayChangedArgs< InElementType > Struct Template Reference
UE::Slate::Containers::TObservableArrayChangedArgs< InElementType > Struct Template Reference
#include "ObservableArray.h"
Data Structures
struct FRemoveSwapIndex
struct FSwapIndex
Public Member Functions
EObservableArrayChangedAction GetAction () const
SizeType GetActionIndex () const
Valid for the Add, Remove, RemoveSwap action.
ArrayViewType GetItems () const
FRemoveSwapIndex GetRemovedSwapIndexes () const
Valid for the RemoveSwap action.
FSwapIndex GetSwapIndex () const
Valid for the Swap action.
Private Types
using ArrayViewType = TArrayView<InElementType>
using ElementType = typename ArrayViewType::ElementType
using SizeType = typename ArrayViewType::SizeType
Static Private Member Functions
static TObservableArrayChangedArgs MakeAddAction (const ArrayViewType InAddedItems, int32 InNewIndex)
static TObservableArrayChangedArgs MakeRemoveAction (const ArrayViewType InRemovedItems, int32 InRemoveStartedIndex)
static TObservableArrayChangedArgs MakeRemoveSwapAction (const ArrayViewType InRemovedItems, int32 InRemoveStartedIndex, int32 InPreviousMovedItemLocation)
static TObservableArrayChangedArgs MakeResetAction ()
static TObservableArrayChangedArgs MakeSwapAction (int32 InFirstIndex, int32 InSecondIndex)
Private Attributes
EObservableArrayChangedAction Action = EObservableArrayChangedAction::Reset
ArrayViewType Array
SizeType MoveIndex = INDEX_NONE
SizeType StartIndex = INDEX_NONE
friend TObservableArray< InElementType >
Detailed Description
template<typename InElementType>
struct UE::Slate::Containers::TObservableArrayChangedArgs< InElementType >
Definition at line 38 of file ObservableArray.h.
Member Typedef Documentation
ArrayViewType
template<typename InElementType> using UE::Slate::Containers::TObservableArrayChangedArgs< InElementType >::ArrayViewType = TArrayView<InElementType> private
Definition at line 41 of file ObservableArray.h.
ElementType
template<typename InElementType> using UE::Slate::Containers::TObservableArrayChangedArgs< InElementType >::ElementType = typename ArrayViewType::ElementType private
Definition at line 43 of file ObservableArray.h.
SizeType
template<typename InElementType> using UE::Slate::Containers::TObservableArrayChangedArgs< InElementType >::SizeType = typename ArrayViewType::SizeType private
Definition at line 42 of file ObservableArray.h.
Member Function Documentation
GetAction()
template<typename InElementType> EObservableArrayChangedAction UE::Slate::Containers::TObservableArrayChangedArgs< InElementType >::GetAction () const inline
Returns
The action that caused the event.
Definition at line 98 of file ObservableArray.h.
References Action.
GetActionIndex()
template<typename InElementType> SizeType UE::Slate::Containers::TObservableArrayChangedArgs< InElementType >::GetActionIndex () const inline
Valid for the Add, Remove, RemoveSwap action.
Use GetItems.Num() to know how many elements were added/removed. Add: The array index where we added the elements. Remove: The old array index before it removed the elements. The index is not valid anymore. RemoveSwap: The old array index before it removed the elements. The index is valid if the array is not empty.
Returns
The index the action started.
Definition at line 111 of file ObservableArray.h.
References StartIndex.
GetItems()
template<typename InElementType> ArrayViewType UE::Slate::Containers::TObservableArrayChangedArgs< InElementType >::GetItems () const inline
Returns
The items added to the array or removed from the array. Valid for the Add, Remove and RemoveSwap action.
Definition at line 168 of file ObservableArray.h.
References Array.
GetRemovedSwapIndexes()
template<typename InElementType> FRemoveSwapIndex UE::Slate::Containers::TObservableArrayChangedArgs< InElementType >::GetRemovedSwapIndexes () const inline
Valid for the RemoveSwap action.
Returns
The index of the removed elements and the index of the moved elements.
Definition at line 142 of file ObservableArray.h.
References Action, INDEX_NONE, MoveIndex, UE::Slate::Containers::RemoveSwap, and StartIndex.
GetSwapIndex()
template<typename InElementType> FSwapIndex UE::Slate::Containers::TObservableArrayChangedArgs< InElementType >::GetSwapIndex () const inline
Valid for the Swap action.
Returns
The indexes of the 2 swapped elements.
Definition at line 162 of file ObservableArray.h.
References Action, INDEX_NONE, MoveIndex, StartIndex, and UE::Slate::Containers::Swap.
MakeAddAction()
template<typename InElementType> TObservableArrayChangedArgs UE::Slate::Containers::TObservableArrayChangedArgs< InElementType >::MakeAddAction (const ArrayViewType InAddedItems, int32 InNewIndex) inline static private
Definition at line 54 of file ObservableArray.h.
References UE::Slate::Containers::Add, and check.
Referenced by UE::Slate::Containers::TObservableArray< InElementType >::Add(), UE::Slate::Containers::TObservableArray< InElementType >::Add(), UE::Slate::Containers::TObservableArray< InElementType >::Append(), UE::Slate::Containers::TObservableArray< InElementType >::Append(), UE::Slate::Containers::TObservableArray< InElementType >::Emplace(), and UE::Slate::Containers::TObservableArray< InElementType >::EmplaceAt().
MakeRemoveAction()
template<typename InElementType> TObservableArrayChangedArgs UE::Slate::Containers::TObservableArrayChangedArgs< InElementType >::MakeRemoveAction (const ArrayViewType InRemovedItems, int32 InRemoveStartedIndex) inline static private
Definition at line 64 of file ObservableArray.h.
References check, and UE::Slate::Containers::Remove.
Referenced by UE::Slate::Containers::TObservableArray< InElementType >::RemoveAt(), and UE::Slate::Containers::TObservableArray< InElementType >::RemoveAt().
MakeRemoveSwapAction()
template<typename InElementType> TObservableArrayChangedArgs UE::Slate::Containers::TObservableArrayChangedArgs< InElementType >::MakeRemoveSwapAction (const ArrayViewType InRemovedItems, int32 InRemoveStartedIndex, int32 InPreviousMovedItemLocation) inline static private
Definition at line 74 of file ObservableArray.h.
References check, INDEX_NONE, and UE::Slate::Containers::RemoveSwap.
Referenced by UE::Slate::Containers::TObservableArray< InElementType >::RemoveAtSwap(), and UE::Slate::Containers::TObservableArray< InElementType >::RemoveAtSwap().
MakeResetAction()
template<typename InElementType> TObservableArrayChangedArgs UE::Slate::Containers::TObservableArrayChangedArgs< InElementType >::MakeResetAction () inline static private
Definition at line 47 of file ObservableArray.h.
References UE::Slate::Containers::Reset.
Referenced by UE::Slate::Containers::TObservableArray< InElementType >::Reset().
MakeSwapAction()
template<typename InElementType> TObservableArrayChangedArgs UE::Slate::Containers::TObservableArrayChangedArgs< InElementType >::MakeSwapAction (int32 InFirstIndex, int32 InSecondIndex) inline static private
Definition at line 86 of file ObservableArray.h.
References check, and UE::Slate::Containers::Swap.
Referenced by UE::Slate::Containers::TObservableArray< InElementType >::Swap().
Field Documentation
Action
template<typename InElementType> EObservableArrayChangedAction UE::Slate::Containers::TObservableArrayChangedArgs< InElementType >::Action = EObservableArrayChangedAction::Reset private
Definition at line 177 of file ObservableArray.h.
Referenced by GetAction(), GetRemovedSwapIndexes(), and GetSwapIndex().
Array
template<typename InElementType> ArrayViewType UE::Slate::Containers::TObservableArrayChangedArgs< InElementType >::Array private
Definition at line 174 of file ObservableArray.h.
Referenced by GetItems().
MoveIndex
template<typename InElementType> SizeType UE::Slate::Containers::TObservableArrayChangedArgs< InElementType >::MoveIndex = INDEX_NONE private
Definition at line 176 of file ObservableArray.h.
Referenced by GetRemovedSwapIndexes(), and GetSwapIndex().
StartIndex
template<typename InElementType> SizeType UE::Slate::Containers::TObservableArrayChangedArgs< InElementType >::StartIndex = INDEX_NONE private
Definition at line 175 of file ObservableArray.h.
Referenced by GetActionIndex(), GetRemovedSwapIndexes(), and GetSwapIndex().
TObservableArray< InElementType >
template<typename InElementType> friend UE::Slate::Containers::TObservableArrayChangedArgs< InElementType >::TObservableArray< InElementType > private
Definition at line 44 of file ObservableArray.h.
The documentation for this struct was generated from the following file:
Runtime/SlateCore/Public/Containers/ObservableArray.h