Unreal Engine 5.6 C++ API: FPixelShaderUtils Struct Reference
FPixelShaderUtils Struct Reference
All utils for pixel shaders.
#include "PixelShaderUtils.h"
Data Structures
class FRasterizeToRectsVS
Utility vertex shader for rect array based operations.
Static Public Member Functions
template<typename TShaderClass>
static void AddFullscreenInstancedMultiViewportPass (FRDGBuilder &GraphBuilder, const FGlobalShaderMap *GlobalShaderMap, FRDGEventName &&PassName, const TShaderRef< TShaderClass > &PixelShader, typename TShaderClass::FParameters *Parameters, TArray< FIntRect > &&Viewports, FRHIBlendState *BlendState=nullptr, FRHIRasterizerState *RasterizerState=nullptr, FRHIDepthStencilState *DepthStencilState=nullptr, uint32 StencilRef=0, ERDGPassFlags AdditionalPassFlags=ERDGPassFlags::None)
Dispatch a pixel shader to render graph builder with its parameters.
template<typename TShaderClass>
static void AddFullscreenPass (FRDGBuilder &GraphBuilder, const FGlobalShaderMap *GlobalShaderMap, FRDGEventName &&PassName, const TShaderRef< TShaderClass > &PixelShader, typename TShaderClass::FParameters *Parameters, const FIntRect &Viewport, FRHIBlendState *BlendState=nullptr, FRHIRasterizerState *RasterizerState=nullptr, FRHIDepthStencilState *DepthStencilState=nullptr, uint32 StencilRef=0, ERDGPassFlags AdditionalPassFlags=ERDGPassFlags::None)
Dispatch a pixel shader to render graph builder with its parameters.
template<typename TPixelShaderClass, typename TPassParameters>
static void AddRasterizeToRectsPass (FRDGBuilder &GraphBuilder, const FGlobalShaderMap *GlobalShaderMap, FRDGEventName &&PassName, const TShaderRef< TPixelShaderClass > &PixelShader, TPassParameters *Parameters, FIntPoint ViewportSize, FRDGBufferSRVRef RectCoordBufferSRV, uint32 NumRects, FRHIBlendState *BlendState, FRHIRasterizerState *RasterizerState, FRHIDepthStencilState *DepthStencilState, uint32 StencilRef, FIntPoint TextureSize, FRDGBufferSRVRef RectUVBufferSRV, uint32 DownsampleFactor, const bool bSkipRenderPass)
Rect based pixel shader pass.
template<typename TPixelShaderClass, typename TPassParameters>
static void AddRasterizeToRectsPass (FRDGBuilder &GraphBuilder, const FGlobalShaderMap *GlobalShaderMap, FRDGEventName &&PassName, const TShaderRef< TPixelShaderClass > &PixelShader, TPassParameters *Parameters, FIntPoint ViewportSize, FRDGBufferSRVRef RectCoordBufferSRV, uint32 NumRects, FRHIBlendState *BlendState=nullptr, FRHIRasterizerState *RasterizerState=nullptr, FRHIDepthStencilState *DepthStencilState=nullptr, uint32 StencilRef=0, FIntPoint TextureSize=FIntPoint(1, 1), FRDGBufferSRVRef RectUVBufferSRV=nullptr, uint32 DownsampleFactor=1, ERDGPassFlags AdditionalPassFlags=ERDGPassFlags::None)
Rect based pixel shader pass.
template<typename TShaderClass>
static void DrawFullscreenInstancedMultiViewportPixelShader (FRHICommandList &RHICmdList, const FGlobalShaderMap *GlobalShaderMap, const TShaderRef< TShaderClass > &PixelShader, const typename TShaderClass::FParameters &Parameters, TArrayView< FIntRect const > Viewports, FRHIBlendState *BlendState=nullptr, FRHIRasterizerState *RasterizerState=nullptr, FRHIDepthStencilState *DepthStencilState=nullptr, uint32 StencilRef=0)
Dispatch a full screen pixel shader to rhi command list with its parameters, covering several views at once.
template<typename TShaderClass>
static void DrawFullscreenPixelShader (FRHICommandList &RHICmdList, const FGlobalShaderMap *GlobalShaderMap, const TShaderRef< TShaderClass > &PixelShader, const typename TShaderClass::FParameters &Parameters, const FIntRect &Viewport, FRHIBlendState *BlendState=nullptr, FRHIRasterizerState *RasterizerState=nullptr, FRHIDepthStencilState *DepthStencilState=nullptr, uint32 StencilRef=0)
Dispatch a full screen pixel shader to rhi command list with its parameters.
static RENDERCORE_API void DrawFullscreenQuad (FRHICommandList &RHICmdList, uint32 InstanceCount=1)
Draw a two triangle on the entire viewport.
static RENDERCORE_API void DrawFullscreenTriangle (FRHICommandList &RHICmdList, uint32 InstanceCount=1)
Draw a single triangle on the entire viewport.
static RENDERCORE_API void InitFullscreenMultiviewportPipelineState (FRHICommandList &RHICmdList, const FGlobalShaderMap *GlobalShaderMap, const TShaderRef< FShader > &PixelShader, FGraphicsPipelineStateInitializer &GraphicsPSOInit)
Initialize a pipeline state object initializer with almost all the basics required to do a full multi-viewport pass.
static RENDERCORE_API void InitFullscreenPipelineState (FRHICommandList &RHICmdList, const FGlobalShaderMap *GlobalShaderMap, const TShaderRef< FShader > &PixelShader, FGraphicsPipelineStateInitializer &GraphicsPSOInit)
Initialize a pipeline state object initializer with almost all the basics required to do a full viewport pass.
Detailed Description
All utils for pixel shaders.
Definition at line 40 of file PixelShaderUtils.h.
Member Function Documentation
AddFullscreenInstancedMultiViewportPass()
template<typename TShaderClass> void FPixelShaderUtils::AddFullscreenInstancedMultiViewportPass (FRDGBuilder & GraphBuilder, const FGlobalShaderMap * GlobalShaderMap, FRDGEventName && PassName, const TShaderRef< TShaderClass > & PixelShader, typename TShaderClass::FParameters * Parameters, TArray< FIntRect > && Viewports, FRHIBlendState * BlendState = nullptr, FRHIRasterizerState * RasterizerState = nullptr, FRHIDepthStencilState * DepthStencilState = nullptr, uint32 StencilRef = 0, ERDGPassFlags AdditionalPassFlags = ERDGPassFlags::None) inline static
Dispatch a pixel shader to render graph builder with its parameters.
Definition at line 187 of file PixelShaderUtils.h.
References FRDGBuilder::AddPass(), check, ClearUnusedGraphResources(), DrawFullscreenInstancedMultiViewportPixelShader(), Forward(), TShaderRefBase< ShaderType, PointerTableType >::IsValid(), None, Raster, and StencilRef.
AddFullscreenPass()
template<typename TShaderClass> void FPixelShaderUtils::AddFullscreenPass (FRDGBuilder & GraphBuilder, const FGlobalShaderMap * GlobalShaderMap, FRDGEventName && PassName, const TShaderRef< TShaderClass > & PixelShader, typename TShaderClass::FParameters * Parameters, const FIntRect & Viewport, FRHIBlendState * BlendState = nullptr, FRHIRasterizerState * RasterizerState = nullptr, FRHIDepthStencilState * DepthStencilState = nullptr, uint32 StencilRef = 0, ERDGPassFlags AdditionalPassFlags = ERDGPassFlags::None) inline static
Dispatch a pixel shader to render graph builder with its parameters.
Definition at line 155 of file PixelShaderUtils.h.
References FRDGBuilder::AddPass(), check, ClearUnusedGraphResources(), DrawFullscreenPixelShader(), Forward(), TShaderRefBase< ShaderType, PointerTableType >::IsValid(), None, Raster, and StencilRef.
AddRasterizeToRectsPass() [1/2]
template<typename TPixelShaderClass, typename TPassParameters> void FPixelShaderUtils::AddRasterizeToRectsPass (FRDGBuilder & GraphBuilder, const FGlobalShaderMap * GlobalShaderMap, FRDGEventName && PassName, const TShaderRef< TPixelShaderClass > & PixelShader, TPassParameters * Parameters, FIntPoint ViewportSize, FRDGBufferSRVRef RectCoordBufferSRV, uint32 NumRects, FRHIBlendState * BlendState, FRHIRasterizerState * RasterizerState, FRHIDepthStencilState * DepthStencilState, uint32 StencilRef, FIntPoint TextureSize, FRDGBufferSRVRef RectUVBufferSRV, uint32 DownsampleFactor, const bool bSkipRenderPass) inline static
Rect based pixel shader pass.
Definition at line 221 of file PixelShaderUtils.h.
References AddRasterizeToRectsPass(), None, SkipRenderPass, and StencilRef.
Referenced by AddRasterizeToRectsPass().
AddRasterizeToRectsPass() [2/2]
template<typename TPixelShaderClass, typename TPassParameters> void FPixelShaderUtils::AddRasterizeToRectsPass (FRDGBuilder & GraphBuilder, const FGlobalShaderMap * GlobalShaderMap, FRDGEventName && PassName, const TShaderRef< TPixelShaderClass > & PixelShader, TPassParameters * Parameters, FIntPoint ViewportSize, FRDGBufferSRVRef RectCoordBufferSRV, uint32 NumRects, FRHIBlendState * BlendState = nullptr, FRHIRasterizerState * RasterizerState = nullptr, FRHIDepthStencilState * DepthStencilState = nullptr, uint32 StencilRef = 0, FIntPoint TextureSize = FIntPoint(1, 1), FRDGBufferSRVRef RectUVBufferSRV = nullptr, uint32 DownsampleFactor = 1, ERDGPassFlags AdditionalPassFlags = ERDGPassFlags::None) inline static
Rect based pixel shader pass.
Definition at line 245 of file PixelShaderUtils.h.
References FRDGBuilder::AddPass(), ClearUnusedGraphResources(), EnumHasAnyFlags(), Forward(), TShaderRefBase< ShaderType, PointerTableType >::GetPixelShader(), TStaticStateRHI< TStaticBlendState< CW_RGBA, BO_Add, BF_One, BF_Zero, BO_Add, BF_One, BF_Zero, CW_RGBA, BO_Add, BF_One, BF_Zero, BO_Add, BF_One, BF_Zero, CW_RGBA, BO_Add, BF_One, BF_Zero, BO_Add, BF_One, BF_Zero, CW_RGBA, BO_Add, BF_One, BF_Zero, BO_Add, BF_One, BF_Zero, CW_RGBA, BO_Add, BF_One, BF_Zero, BO_Add, BF_One, BF_Zero, CW_RGBA, BO_Add, BF_One, BF_Zero, BO_Add, BF_One, BF_Zero, CW_RGBA, BO_Add, BF_One, BF_Zero, BO_Add, BF_One, BF_Zero, CW_RGBA, BO_Add, BF_One, BF_Zero, BO_Add, BF_One, BF_Zero, false >, FBlendStateRHIRef, FRHIBlendState * >::GetRHI(), TStaticStateRHI< TStaticDepthStencilState< true, CF_DepthNearOrEqual, false, CF_Always, SO_Keep, SO_Keep, SO_Keep, false, CF_Always, SO_Keep, SO_Keep, SO_Keep, 0xFF, 0xFF >, FDepthStencilStateRHIRef, FRHIDepthStencilState * >::GetRHI(), TStaticStateRHI< TStaticRasterizerState< FM_Solid, CM_None, ERasterizerDepthClipMode::DepthClip, true >, FRasterizerStateRHIRef, FRHIRasterizerState * >::GetRHI(), FGlobalShaderMap::GetShader(), GTileVertexDeclaration, None, Raster, TShaderPermutationDomain< Ts >::Set(), SetShaderParameters(), SkipRenderPass, StencilRef, TEXT, UE::Math::TIntPoint< InIntType >::X, and UE::Math::TIntPoint< InIntType >::Y.
DrawFullscreenInstancedMultiViewportPixelShader()
template<typename TShaderClass> void FPixelShaderUtils::DrawFullscreenInstancedMultiViewportPixelShader (FRHICommandList & RHICmdList, const FGlobalShaderMap * GlobalShaderMap, const TShaderRef< TShaderClass > & PixelShader, const typename TShaderClass::FParameters & Parameters, TArrayView< FIntRect const > Viewports, FRHIBlendState * BlendState = nullptr, FRHIRasterizerState * RasterizerState = nullptr, FRHIDepthStencilState * DepthStencilState = nullptr, uint32 StencilRef = 0) inline static
Dispatch a full screen pixel shader to rhi command list with its parameters, covering several views at once.
Definition at line 114 of file PixelShaderUtils.h.
References check, checkf, DrawFullscreenTriangle(), TShaderRefBase< ShaderType, PointerTableType >::GetPixelShader(), InitFullscreenMultiviewportPipelineState(), TShaderRefBase< ShaderType, PointerTableType >::IsValid(), UE::Math::TIntRect< InIntType >::Max, UE::Math::TIntRect< InIntType >::Min, TArrayView< InElementType, InSizeType >::Num(), SetShaderParameters(), StencilRef, TEXT, UE::Math::TIntPoint< InIntType >::X, and UE::Math::TIntPoint< InIntType >::Y.
Referenced by AddFullscreenInstancedMultiViewportPass().
DrawFullscreenPixelShader()
template<typename TShaderClass> void FPixelShaderUtils::DrawFullscreenPixelShader (FRHICommandList & RHICmdList, const FGlobalShaderMap * GlobalShaderMap, const TShaderRef< TShaderClass > & PixelShader, const typename TShaderClass::FParameters & Parameters, const FIntRect & Viewport, FRHIBlendState * BlendState = nullptr, FRHIRasterizerState * RasterizerState = nullptr, FRHIDepthStencilState * DepthStencilState = nullptr, uint32 StencilRef = 0) inline static
Dispatch a full screen pixel shader to rhi command list with its parameters.
Definition at line 85 of file PixelShaderUtils.h.
References check, DrawFullscreenPixelShader(), DrawFullscreenTriangle(), InitFullscreenPipelineState(), SetShaderParameters(), and StencilRef.
Referenced by AddFullscreenPass(), and DrawFullscreenPixelShader().
DrawFullscreenQuad()
RENDERCORE_API void FPixelShaderUtils::DrawFullscreenQuad (FRHICommandList & RHICmdList, uint32 InstanceCount = 1) static
Draw a two triangle on the entire viewport.
References DrawFullscreenQuad().
Referenced by DrawFullscreenQuad().
DrawFullscreenTriangle()
RENDERCORE_API void FPixelShaderUtils::DrawFullscreenTriangle (FRHICommandList & RHICmdList, uint32 InstanceCount = 1) static
Draw a single triangle on the entire viewport.
References DrawFullscreenTriangle().
Referenced by DrawFullscreenInstancedMultiViewportPixelShader(), DrawFullscreenPixelShader(), and DrawFullscreenTriangle().
InitFullscreenMultiviewportPipelineState()
RENDERCORE_API void FPixelShaderUtils::InitFullscreenMultiviewportPipelineState (FRHICommandList & RHICmdList, const FGlobalShaderMap * GlobalShaderMap, const TShaderRef< FShader > & PixelShader, FGraphicsPipelineStateInitializer & GraphicsPSOInit) static
Initialize a pipeline state object initializer with almost all the basics required to do a full multi-viewport pass.
References InitFullscreenMultiviewportPipelineState().
Referenced by DrawFullscreenInstancedMultiViewportPixelShader(), and InitFullscreenMultiviewportPipelineState().
InitFullscreenPipelineState()
RENDERCORE_API void FPixelShaderUtils::InitFullscreenPipelineState (FRHICommandList & RHICmdList, const FGlobalShaderMap * GlobalShaderMap, const TShaderRef< FShader > & PixelShader, FGraphicsPipelineStateInitializer & GraphicsPSOInit) static
Initialize a pipeline state object initializer with almost all the basics required to do a full viewport pass.
References InitFullscreenPipelineState().
Referenced by DrawFullscreenPixelShader(), and InitFullscreenPipelineState().
The documentation for this struct was generated from the following file:
Runtime/RenderCore/Public/PixelShaderUtils.h