Unreal Engine 5.6 C++ API: FBlackboard::FKey Struct Reference
FBlackboard::FKey Struct Reference
#include "BlackboardKey.h"
Public Member Functions
constexpr FKey ()=default
FKey (int32 InKey)
constexpr FKey (uint16 InKey)
constexpr FKey (uint8 InKey)=delete
constexpr operator int32 () const
constexpr operator uint16 () const
constexpr operator uint8 () const =delete
constexpr bool operator!= (const FKey &Other) const
constexpr bool operator== (const FKey &Other) const
Private Attributes
uint16 Key = static_cast<uint16>(-1)
Friends
uint32 GetTypeHash (const FKey &Key)
Detailed Description
Definition at line 17 of file BlackboardKey.h.
Constructor & Destructor Documentation
FKey() [1/4]
FBlackboard::FKey::FKey () constexpr default
Referenced by GetTypeHash, operator!=(), and operator==().
FKey() [2/4]
FBlackboard::FKey::FKey (int32 InKey) inline
Definition at line 20 of file BlackboardKey.h.
References IntCastChecked(), and Key.
FKey() [3/4]
FBlackboard::FKey::FKey (uint16 InKey) inline constexpr
Definition at line 21 of file BlackboardKey.h.
References Key.
FKey() [4/4]
FBlackboard::FKey::FKey (uint8 InKey) constexpr delete
Member Function Documentation
operator int32()
FBlackboard::FKey::operator int32 () const inline constexpr
Definition at line 23 of file BlackboardKey.h.
References Key.
operator uint16()
FBlackboard::FKey::operator uint16 () const inline constexpr
Definition at line 24 of file BlackboardKey.h.
References Key.
operator uint8()
FBlackboard::FKey::operator uint8 () const constexpr delete
operator!=()
bool FBlackboard::FKey::operator!= (const FKey & Other) const inline constexpr
Definition at line 27 of file BlackboardKey.h.
References FKey(), Key, and Other.
operator==()
bool FBlackboard::FKey::operator== (const FKey & Other) const inline constexpr
Definition at line 26 of file BlackboardKey.h.
References FKey(), Key, and Other.
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FKey & Key) friend
Definition at line 35 of file BlackboardKey.h.
References FKey(), and Key.
Field Documentation
Key
uint16 FBlackboard::FKey::Key = static_cast<uint16>(-1) private
Definition at line 30 of file BlackboardKey.h.
Referenced by FKey(), FKey(), GetTypeHash, operator int32(), operator uint16(), operator!=(), and operator==().
The documentation for this struct was generated from the following file:
Runtime/AIModule/Classes/BehaviorTree/Blackboard/BlackboardKey.h