Unreal Engine 5.6 C++ API: TMemoryImageObject< T > Struct Template Reference
TMemoryImageObject< T > Struct Template Reference
#include "MemoryImage.h"
Public Member Functions
TMemoryImageObject ()
TMemoryImageObject (const FTypeLayoutDesc &InTypeDesc, T *InObject, uint32 InFrozenSize)
template<typename TOther>
TMemoryImageObject (const TMemoryImageObject< TOther > &Rhs)
template<typename TOther>
TMemoryImageObject (TOther *InObject)
void Destroy (const FPointerTableBase *PointerTable)
bool Freeze (FPointerTableBase *PointerTable)
bool Unfreeze (const FPointerTableBase *PointerTable)
Data Fields
uint32 FrozenSize
T * Object
const FTypeLayoutDesc * TypeDesc
Detailed Description
template<typename T>
struct TMemoryImageObject< T >
Definition at line 70 of file MemoryImage.h.
Constructor & Destructor Documentation
TMemoryImageObject() [1/4]
template<typename T> TMemoryImageObject< T >::TMemoryImageObject () inline
Definition at line 72 of file MemoryImage.h.
TMemoryImageObject() [2/4]
template<typename T> TMemoryImageObject< T >::TMemoryImageObject (const FTypeLayoutDesc & InTypeDesc, T * InObject, uint32 InFrozenSize) inline
Definition at line 74 of file MemoryImage.h.
TMemoryImageObject() [3/4]
template<typename T> template<typename TOther> TMemoryImageObject< T >::TMemoryImageObject (TOther * InObject) inline
Definition at line 81 of file MemoryImage.h.
TMemoryImageObject() [4/4]
template<typename T> template<typename TOther> TMemoryImageObject< T >::TMemoryImageObject (const TMemoryImageObject< TOther > & Rhs) inline explicit
Definition at line 88 of file MemoryImage.h.
Member Function Documentation
Destroy()
template<typename T> void TMemoryImageObject< T >::Destroy (const FPointerTableBase * PointerTable) inline
Definition at line 110 of file MemoryImage.h.
References FMemory::Free(), FrozenSize, InternalDeleteObjectFromLayout(), Object, and TypeDesc.
Referenced by Freeze(), and Unfreeze().
Freeze()
template<typename T> bool TMemoryImageObject< T >::Freeze (FPointerTableBase * PointerTable) inline
Definition at line 129 of file MemoryImage.h.
References Destroy(), FreezeMemoryImageObject(), FrozenSize, Object, and TypeDesc.
Unfreeze()
template<typename T> bool TMemoryImageObject< T >::Unfreeze (const FPointerTableBase * PointerTable) inline
Definition at line 143 of file MemoryImage.h.
References Destroy(), FrozenSize, Object, TypeDesc, and UnfreezeMemoryImageObject().
Field Documentation
FrozenSize
template<typename T> uint32 TMemoryImageObject< T >::FrozenSize
Definition at line 102 of file MemoryImage.h.
Referenced by Destroy(), Freeze(), and Unfreeze().
Object
template<typename T> T* TMemoryImageObject< T >::Object
Definition at line 101 of file MemoryImage.h.
Referenced by Destroy(), Freeze(), and Unfreeze().
TypeDesc
template<typename T> const FTypeLayoutDesc* TMemoryImageObject< T >::TypeDesc
Definition at line 100 of file MemoryImage.h.
Referenced by Destroy(), Freeze(), and Unfreeze().
The documentation for this struct was generated from the following file:
Runtime/Core/Public/Serialization/MemoryImage.h