Unreal Engine 5.6 C++ API: UE::AnimNext::FTraitEventLifetime Struct Reference
UE::AnimNext::FTraitEventLifetime Struct Reference final
Trait Event Lifetime.
#include "TraitEventLifetime.h"
Public Member Functions
constexpr FTraitEventLifetime () noexcept
ANIMNEXT_API bool Decrement ()
constexpr bool IsExpired () const
constexpr bool IsInfinite () const
constexpr bool IsTransient () const
Static Public Member Functions
static constexpr FTraitEventLifetime MakeInfinite () noexcept
static constexpr FTraitEventLifetime MakeTransient () noexcept
static constexpr FTraitEventLifetime MakeUntil (uint32 LifetimeCount) noexcept
Private Member Functions
constexpr FTraitEventLifetime (uint32 InLifetimeCount) noexcept
Private Attributes
uint32 LifetimeCount
Static Private Attributes
static constexpr uint32 EXPIRED_LIFETIME = 0
static constexpr uint32 INFINITE_LIFETIME = ~0
static constexpr uint32 TRANSIENT_LIFETIME = 1
Detailed Description
Trait Event Lifetime.
This encapsulates a specific lifetime duration.
Definition at line 14 of file TraitEventLifetime.h.
Constructor & Destructor Documentation
FTraitEventLifetime() [1/2]
UE::AnimNext::FTraitEventLifetime::FTraitEventLifetime () inline constexpr noexcept
Definition at line 35 of file TraitEventLifetime.h.
References EXPIRED_LIFETIME, and LifetimeCount.
Referenced by MakeInfinite(), MakeTransient(), and MakeUntil().
FTraitEventLifetime() [2/2]
UE::AnimNext::FTraitEventLifetime::FTraitEventLifetime (uint32 InLifetimeCount) inline explicit constexpr private noexcept
Definition at line 62 of file TraitEventLifetime.h.
Member Function Documentation
Decrement()
ANIMNEXT_API bool UE::AnimNext::FTraitEventLifetime::Decrement ()
IsExpired()
bool UE::AnimNext::FTraitEventLifetime::IsExpired () const inline constexpr
Definition at line 41 of file TraitEventLifetime.h.
References EXPIRED_LIFETIME, and LifetimeCount.
Referenced by USTRUCT().
IsInfinite()
bool UE::AnimNext::FTraitEventLifetime::IsInfinite () const inline constexpr
Definition at line 44 of file TraitEventLifetime.h.
References INFINITE_LIFETIME, and LifetimeCount.
IsTransient()
bool UE::AnimNext::FTraitEventLifetime::IsTransient () const inline constexpr
Definition at line 47 of file TraitEventLifetime.h.
References LifetimeCount, and TRANSIENT_LIFETIME.
MakeInfinite()
constexpr FTraitEventLifetime UE::AnimNext::FTraitEventLifetime::MakeInfinite () inline static constexpr noexcept
Definition at line 29 of file TraitEventLifetime.h.
References FTraitEventLifetime(), and INFINITE_LIFETIME.
MakeTransient()
constexpr FTraitEventLifetime UE::AnimNext::FTraitEventLifetime::MakeTransient () inline static constexpr noexcept
Definition at line 17 of file TraitEventLifetime.h.
References FTraitEventLifetime(), and TRANSIENT_LIFETIME.
Referenced by USTRUCT().
MakeUntil()
constexpr FTraitEventLifetime UE::AnimNext::FTraitEventLifetime::MakeUntil (uint32 LifetimeCount) inline static constexpr noexcept
Definition at line 23 of file TraitEventLifetime.h.
References FTraitEventLifetime(), and LifetimeCount.
Field Documentation
EXPIRED_LIFETIME
uint32 UE::AnimNext::FTraitEventLifetime::EXPIRED_LIFETIME = 0 static constexpr private
Definition at line 60 of file TraitEventLifetime.h.
Referenced by FTraitEventLifetime(), and IsExpired().
INFINITE_LIFETIME
uint32 UE::AnimNext::FTraitEventLifetime::INFINITE_LIFETIME = ~0 static constexpr private
Definition at line 54 of file TraitEventLifetime.h.
Referenced by IsInfinite(), and MakeInfinite().
LifetimeCount
uint32 UE::AnimNext::FTraitEventLifetime::LifetimeCount private
Definition at line 67 of file TraitEventLifetime.h.
Referenced by FTraitEventLifetime(), IsExpired(), IsInfinite(), IsTransient(), and MakeUntil().
TRANSIENT_LIFETIME
uint32 UE::AnimNext::FTraitEventLifetime::TRANSIENT_LIFETIME = 1 static constexpr private
Definition at line 57 of file TraitEventLifetime.h.
Referenced by IsTransient(), and MakeTransient().
The documentation for this struct was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Experimental/AnimNext/Source/AnimNext/Public/TraitCore/TraitEventLifetime.h