Unreal Engine 5.6 C++ API: UE::Tick::FSyncPointId Struct Reference
UE::Tick::FSyncPointId Struct Reference final
Identifies a specific registered sync point and batch, this can be safely passed around threads.
#include "TaskSyncManager.h"
Public Types
typedef int32 FInternalId
Public Member Functions
FSyncPointId ()
Construct an invalid context.
FSyncPointId (FInternalId InSyncId, FBatchContextId InBatchContext)
Construct from explicit ids TODO: May make private.
FBatchContextId GetBatchContext () const
Returns the batch context this was initialized with.
bool IsValid () const
Returns true if this has been initialized to a registered sync point.
bool operator!= (const FSyncPointId &Other) const
bool operator== (const FSyncPointId &Other) const
Data Fields
FBatchContextId BatchContext
FInternalId SyncId
Static Public Attributes
static constexpr FInternalId InvalidSyncPoint = -1
Friends
uint32 GetTypeHash (const FSyncPointId &SyncPoint)
Detailed Description
Identifies a specific registered sync point and batch, this can be safely passed around threads.
Definition at line 337 of file TaskSyncManager.h.
Member Typedef Documentation
FInternalId
typedef int32 UE::Tick::FSyncPointId::FInternalId
Definition at line 340 of file TaskSyncManager.h.
Constructor & Destructor Documentation
FSyncPointId() [1/2]
UE::Tick::FSyncPointId::FSyncPointId () inline
Construct an invalid context.
Definition at line 345 of file TaskSyncManager.h.
References InvalidSyncPoint, and SyncId.
Referenced by GetTypeHash, operator!=(), and operator==().
FSyncPointId() [2/2]
UE::Tick::FSyncPointId::FSyncPointId (FInternalId InSyncId, FBatchContextId InBatchContext) inline explicit
Construct from explicit ids TODO: May make private.
Definition at line 350 of file TaskSyncManager.h.
References BatchContext, and SyncId.
Member Function Documentation
GetBatchContext()
FBatchContextId UE::Tick::FSyncPointId::GetBatchContext () const inline
Returns the batch context this was initialized with.
Definition at line 362 of file TaskSyncManager.h.
References BatchContext.
IsValid()
bool UE::Tick::FSyncPointId::IsValid () const inline
Returns true if this has been initialized to a registered sync point.
Definition at line 356 of file TaskSyncManager.h.
References InvalidSyncPoint, and SyncId.
operator!=()
bool UE::Tick::FSyncPointId::operator!= (const FSyncPointId & Other) const inline
Definition at line 372 of file TaskSyncManager.h.
References FSyncPointId(), and Other.
operator==()
bool UE::Tick::FSyncPointId::operator== (const FSyncPointId & Other) const inline
Definition at line 367 of file TaskSyncManager.h.
References FSyncPointId(), BatchContext, Other, and SyncId.
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FSyncPointId & SyncPoint) friend
Definition at line 377 of file TaskSyncManager.h.
References FSyncPointId(), BatchContext, GetTypeHash(), and SyncId.
Field Documentation
BatchContext
FBatchContextId UE::Tick::FSyncPointId::BatchContext
Definition at line 383 of file TaskSyncManager.h.
Referenced by FSyncPointId(), GetBatchContext(), GetTypeHash, and operator==().
InvalidSyncPoint
FInternalId UE::Tick::FSyncPointId::InvalidSyncPoint = -1 static constexpr
Definition at line 342 of file TaskSyncManager.h.
Referenced by FSyncPointId(), and IsValid().
SyncId
FInternalId UE::Tick::FSyncPointId::SyncId
Definition at line 382 of file TaskSyncManager.h.
Referenced by FSyncPointId(), FSyncPointId(), GetTypeHash, IsValid(), and operator==().
The documentation for this struct was generated from the following file:
Runtime/Engine/Public/TaskSyncManager.h