Unreal Engine 5.6 C++ API: FSimpleStreamableAssetManager::FRegister Struct Reference
FSimpleStreamableAssetManager::FRegister Struct Reference
#include "SimpleStreamableAssetManager.h"
Public Member Functions
FRegister ()=default
FRegister (const FRegister &)=default
template<typename TObject, typename TPrimitive>
FRegister (const TObject *InObject, const TPrimitive *InPrimitive)
FRegister (FRegister &&)=default
FRegister & operator= (const FRegister &)=default
FRegister & operator= (FRegister &&)=default
Public Member Functions inherited from FSimpleStreamableAssetManager::FUpdate
FUpdate ()=default
FUpdate (const FUpdate &)=default
FUpdate (const void *InObject, const TSharedPtr< int32, ESPMode::ThreadSafe > &InObjectRegistrationIndex, const FBoxSphereBounds &InBounds, const float InMinDistance, const float InMaxDistance, const float InLastRenderedTime, bool InForceMipStreaming)
FUpdate (FUpdate &&)=default
FUpdate & operator= (const FUpdate &)=default
FUpdate & operator= (FUpdate &&)=default
Data Fields
TArray< FStreamingRenderAssetPrimitiveInfo > Assets {}
Data Fields inherited from FSimpleStreamableAssetManager::FUpdate
union {
UPTRINT ObjectKey = 0
const FPrimitiveSceneProxy * SceneProxy_ForDebug
};
uint8 bForceMipStreaming: 1 = false
float LastRenderedTime = -1000.0f
float MaxDistance = FLT_MAX
float MinDistance = 0.0f
FBoxSphereBounds ObjectBounds {}
TSharedPtr< int32, ESPMode::ThreadSafe > ObjectRegistrationIndex {}
Detailed Description
Definition at line 221 of file SimpleStreamableAssetManager.h.
Constructor & Destructor Documentation
FRegister() [1/4]
FSimpleStreamableAssetManager::FRegister::FRegister () default
Referenced by FRegister(), FRegister(), operator=(), and operator=().
FRegister() [2/4]
FSimpleStreamableAssetManager::FRegister::FRegister (const FRegister &) default
References FRegister().
FRegister() [3/4]
FSimpleStreamableAssetManager::FRegister::FRegister (FRegister &&) default
References FRegister().
FRegister() [4/4]
template<typename TObject, typename TPrimitive> FSimpleStreamableAssetManager::FRegister::FRegister (const TObject * InObject, const TPrimitive * InPrimitive)
Definition at line 421 of file SimpleStreamableAssetManager.h.
References FSimpleStreamableAssetManager::FUpdate::FUpdate(), and Interface.
Member Function Documentation
operator=() [1/2]
FRegister & FSimpleStreamableAssetManager::FRegister::operator= (const FRegister &) default
References FRegister().
operator=() [2/2]
FRegister & FSimpleStreamableAssetManager::FRegister::operator= (FRegister &&) default
References FRegister().
Field Documentation
Assets
TArray<FStreamingRenderAssetPrimitiveInfo> FSimpleStreamableAssetManager::FRegister::Assets {}
Definition at line 223 of file SimpleStreamableAssetManager.h.
The documentation for this struct was generated from the following file:
Runtime/Engine/Public/Streaming/SimpleStreamableAssetManager.h