Unreal Engine 5.6 C++ API: TBaseStructureBase< T, bHasStaticStruct > Struct Template Reference
TBaseStructureBase< T, bHasStaticStruct > Struct Template Reference
#include "Class.h"
Static Public Member Functions
static UScriptStruct * Get ()
Detailed Description
template<typename T, bool bHasStaticStruct = TModels_V<CStaticStructProvider, T>>
struct TBaseStructureBase< T, bHasStaticStruct >
Definition at line 4355 of file Class.h.
Member Function Documentation
Get()
template<typename T, bool bHasStaticStruct = TModels_V<CStaticStructProvider, T>> UScriptStruct * TBaseStructureBase< T, bHasStaticStruct >::Get () inline static
Definition at line 4357 of file Class.h.
Referenced by TStructOnScope< T >::Cast(), TStructOnScope< T >::CastChecked(), FStructSharedMemory::CreateArgs(), FRigVMUnitNodeCreatedContext::FindFirstVariableOfType(), SGraphPinVector4< NumericType >::GetDefaultValueWidget(), SGraphPinVector4Slider< NumericType >::GetDefaultValueWidget(), SGraphPinVector< NumericType >::GetDefaultValueWidget(), SGraphPinVectorSlider< NumericType >::GetDefaultValueWidget(), TStateTreeInstanceDataStructRef< T >::GetPtr(), UE::StructUtils::GetStructPtr(), UE::StructUtils::GetStructRef(), FRigVMRegistry_NoLock::GetTypeIndex_NoLock(), FPropertyBagArrayRef::GetValueStruct(), TSharedStruct< BaseStructT >::Initialize(), TStructOnScope< T >::InitializeAs(), TInstancedStruct< BaseStructT >::InitializeAsScriptStruct(), TStructOnScope< T >::InitializeFrom(), TStructOnScope< T >::InitializeFrom(), TStructOnScope< T >::InitializeFromChecked(), TStructOnScope< T >::InitializeFromChecked(), FRigVMMemoryHandle::IsStruct(), FRigVMMemoryHandle::IsStructArray(), UE::StateTree::PropertyRefHelpers::Validator< T, decltype(TBaseStructure< T >::Get, void())>::IsValid(), FConstStructView::Make(), FStructView::Make(), TInstancedStruct< BaseStructT >::Make(), TInstancedStruct< BaseStructT >::Make(), FLiveLinkBaseDataStruct< FLiveLinkBaseStaticData >::operator<<, TStructOnScope< T >::Serialize(), FStructArrayView::UE_DEPRECATED(), FStructArrayView::UE_DEPRECATED(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), and USTRUCT().
The documentation for this struct was generated from the following file:
Runtime/CoreUObject/Public/UObject/Class.h