Unreal Engine 5.6 C++ API: UE::AnimNext::IGarbageCollection Struct Reference
UE::AnimNext::IGarbageCollection Struct Reference
IGarbageCollection.
#include "IGarbageCollection.h"
Public Member Functions
virtual ANIMNEXTANIMGRAPH_API void AddReferencedObjects (const FExecutionContext &Context, const TTraitBinding< IGarbageCollection > &Binding, FReferenceCollector &Collector) const
DECLARE_ANIM_TRAIT_INTERFACE (IGarbageCollection) static ANIMNEXTANIMGRAPH_API void RegisterWithGC(const FExecutionContext &Context
virtual ANIMNEXTANIMGRAPH_API const FText & GetDisplayName () const override
virtual ANIMNEXTANIMGRAPH_API const FText & GetDisplayShortName () const override
virtual bool IsInternal () const override
Public Member Functions inherited from UE::AnimNext::ITraitInterface
virtual ~ITraitInterface ()
virtual FTraitInterfaceUID GetInterfaceUID () const
Static Public Member Functions
static ANIMNEXTANIMGRAPH_API void UnregisterWithGC (const FExecutionContext &Context, const FTraitBinding &Binding)
Data Fields
const FTraitBinding & Binding
Additional Inherited Members
Static Public Attributes inherited from UE::AnimNext::ITraitInterface
static constexpr FTraitInterfaceUID InterfaceUID = FTraitInterfaceUID::MakeUID(TEXT("ITraitInterface"))
Detailed Description
IGarbageCollection.
This interface exposes garbage collection reference tracking.
Definition at line 20 of file IGarbageCollection.h.
Member Function Documentation
AddReferencedObjects()
virtual ANIMNEXTANIMGRAPH_API void UE::AnimNext::IGarbageCollection::AddReferencedObjects (const FExecutionContext & Context, const TTraitBinding< IGarbageCollection > & Binding, FReferenceCollector & Collector) const virtual
Reimplemented in UE::AnimNext::FBlendStackCoreTrait.
References AddReferencedObjects(), Binding, and UE_API.
Referenced by AddReferencedObjects().
DECLARE_ANIM_TRAIT_INTERFACE()
UE::AnimNext::IGarbageCollection::DECLARE_ANIM_TRAIT_INTERFACE (IGarbageCollection) const &
GetDisplayName()
virtual ANIMNEXTANIMGRAPH_API const FText & UE::AnimNext::IGarbageCollection::GetDisplayName () const override virtual
Reimplemented from UE::AnimNext::ITraitInterface.
References UE_API.
GetDisplayShortName()
virtual ANIMNEXTANIMGRAPH_API const FText & UE::AnimNext::IGarbageCollection::GetDisplayShortName () const override virtual
Reimplemented from UE::AnimNext::ITraitInterface.
References UE_API.
IsInternal()
virtual bool UE::AnimNext::IGarbageCollection::IsInternal () const inline override virtual
Reimplemented from UE::AnimNext::ITraitInterface.
Definition at line 37 of file IGarbageCollection.h.
UnregisterWithGC()
ANIMNEXTANIMGRAPH_API void UE::AnimNext::IGarbageCollection::UnregisterWithGC (const FExecutionContext & Context, const FTraitBinding & Binding) static
References Binding, UE_API, and UnregisterWithGC().
Referenced by UnregisterWithGC().
Field Documentation
Binding
const FTraitBinding& UE::AnimNext::IGarbageCollection::Binding
Definition at line 27 of file IGarbageCollection.h.
Referenced by AddReferencedObjects(), and UnregisterWithGC().
The documentation for this struct was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Experimental/AnimNextAnimGraph/Source/AnimNextAnimGraph/Public/TraitInterfaces/IGarbageCollection.h