Unreal Engine 5.6 C++ API: FGuid Struct Reference
FGuid Struct Reference
Implements a globally unique identifier.
#include "Guid.h"
Public Member Functions
constexpr FGuid ()
Default constructor.
FGuid (const FString &InGuidStr)
constexpr FGuid (uint32 InA, uint32 InB, uint32 InC, uint32 InD)
Creates and initializes a new GUID from the specified components.
void AppendString (FAnsiStringBuilderBase &Builder, EGuidFormats Format=EGuidFormats::DigitsWithHyphensLower) const
Appends this GUID to the string builder using the specified format.
void AppendString (FString &Out, EGuidFormats Format=EGuidFormats::Digits) const
Converts this GUID to its string representation using the specified format.
void AppendString (FUtf8StringBuilderBase &Builder, EGuidFormats Format=EGuidFormats::DigitsWithHyphensLower) const
void AppendString (FWideStringBuilderBase &Builder, EGuidFormats Format=EGuidFormats::DigitsWithHyphensLower) const
bool ExportTextItem (FString &ValueStr, FGuid const &DefaultValue, UObject *Parent, int32 PortFlags, class UObject *ExportRootScope) const
Exports the GUIDs value to a string.
bool ImportTextItem (const TCHAR *&Buffer, int32 PortFlags, UObject *Parent, FOutputDevice *ErrorText)
Imports the GUIDs value from a text buffer.
void Invalidate ()
Invalidates the GUID.
bool IsValid () const
Checks whether this GUID is valid or not.
uint32 & operator[] (int32 Index)
Provides access to the GUIDs components.
const uint32 & operator[] (int32 Index) const
Provides read-only access to the GUIDs components.
bool Serialize (FArchive &Ar)
bool Serialize (FStructuredArchive::FSlot Slot)
FString ToString (EGuidFormats Format=EGuidFormats::Digits) const
Converts this GUID to its string representation.
Static Public Member Functions
static void AutoRTFMAssignFromOpenToClosed (FGuid &Closed, FGuid Open)
static FGuid Combine (const FGuid &GuidA, const FGuid &GuidB)
Returns a GUID which is a combinationof the two provided ones.
static FGuid NewDeterministicGuid (FStringView ObjectPath, uint64 Seed=0)
Create a guid by hashing the given path; this guid will be deterministic when called in multiple cook processes and will thus avoid cook indeterminism caused by FGuid::NewGuid.
static FGuid NewGuid ()
Returns a new GUID.
static FGuid NewGuidFromHash (const FBlake3Hash &Hash)
Create a guid from a calculated Blake3 Hash.
static bool Parse (const FString &GuidString, FGuid &OutGuid)
static bool Parse (const TCHAR *GuidString, FGuid &OutGuid)
Converts a string to a GUID.
static bool Parse (FStringView GuidString, FGuid &OutGuid)
static bool ParseExact (const FString &GuidString, EGuidFormats Format, FGuid &OutGuid)
static bool ParseExact (const TCHAR *GuidString, EGuidFormats Format, FGuid &OutGuid)
Converts a string with the specified format to a GUID.
static bool ParseExact (FStringView GuidString, EGuidFormats Format, FGuid &OutGuid)
Data Fields
uint32 A
Holds the first component.
uint32 B
Holds the second component.
uint32 C
Holds the third component.
uint32 D
Holds the fourth component.
Friends
uint32 GetTypeHash (const FGuid &Guid)
Calculates the hash for a GUID.
void LexFromString (FGuid &Result, const TCHAR *String)
FString LexToString (const FGuid &Value)
Guid default string conversion.
bool operator!= (const FGuid &X, const FGuid &Y)
Compares two GUIDs for inequality.
bool operator< (const FGuid &X, const FGuid &Y)
Compares two GUIDs.
FArchive & operator<< (FArchive &Ar, FGuid &G)
Serializes a GUID from or into an archive.
void operator<< (FStructuredArchive::FSlot Slot, FGuid &G)
Serializes a GUID from or into a structured archive slot.
bool operator== (const FGuid &X, const FGuid &Y)
Compares two GUIDs for equality.
Detailed Description
Implements a globally unique identifier.
Definition at line 108 of file Guid.h.
Constructor & Destructor Documentation
FGuid() [1/3]
FGuid::FGuid () inline constexpr
Default constructor.
Definition at line 113 of file Guid.h.
References A, B, C, and D.
Referenced by AutoRTFMAssignFromOpenToClosed(), Combine(), ExportTextItem(), GetTypeHash, LexFromString, LexToString, NewDeterministicGuid(), NewGuid(), NewGuidFromHash(), operator!=, operator<, operator<<, operator<<, operator==, Parse(), Parse(), Parse(), ParseExact(), ParseExact(), and ParseExact().
FGuid() [2/3]
FGuid::FGuid (uint32 InA, uint32 InB, uint32 InC, uint32 InD) inline explicit constexpr
Creates and initializes a new GUID from the specified components.
Parameters
InA The first component.
InB The second component.
InC The third component.
InD The fourth component.
Definition at line 128 of file Guid.h.
References A, B, C, and D.
FGuid() [3/3]
FGuid::FGuid (const FString & InGuidStr) inline explicit
Definition at line 132 of file Guid.h.
References Invalidate(), and Parse().
Member Function Documentation
AppendString() [1/4]
void FGuid::AppendString (FAnsiStringBuilderBase & Builder, EGuidFormats Format = EGuidFormats::DigitsWithHyphensLower) const
Appends this GUID to the string builder using the specified format.
References DigitsWithHyphensLower, and Format.
AppendString() [2/4]
void FGuid::AppendString (FString & Out, EGuidFormats Format = EGuidFormats::Digits) const
Converts this GUID to its string representation using the specified format.
Parameters
Format The string format to use.
References Digits, and Format.
Referenced by ToString().
AppendString() [3/4]
void FGuid::AppendString (FUtf8StringBuilderBase & Builder, EGuidFormats Format = EGuidFormats::DigitsWithHyphensLower) const
References DigitsWithHyphensLower, and Format.
AppendString() [4/4]
void FGuid::AppendString (FWideStringBuilderBase & Builder, EGuidFormats Format = EGuidFormats::DigitsWithHyphensLower) const
References DigitsWithHyphensLower, and Format.
AutoRTFMAssignFromOpenToClosed()
void FGuid::AutoRTFMAssignFromOpenToClosed (FGuid & Closed, FGuid Open) inline static
Definition at line 268 of file Guid.h.
References FGuid().
Combine()
FGuid FGuid::Combine (const FGuid & GuidA, const FGuid & GuidB) static
Returns a GUID which is a combinationof the two provided ones.
Returns
The combined GUID.
References FGuid().
Referenced by USTRUCT().
ExportTextItem()
bool FGuid::ExportTextItem (FString & ValueStr, FGuid const & DefaultValue, UObject * Parent, int32 PortFlags, class UObject * ExportRootScope) const
Exports the GUIDs value to a string.
Parameters
ValueStr Will hold the string value.
DefaultValue The default value.
Parent Not used.
PortFlags Not used.
ExportRootScope Not used.
Returns
true on success, false otherwise.
See also
ImportTextItem
References FGuid(), and Parent.
ImportTextItem()
bool FGuid::ImportTextItem (const TCHAR *& Buffer, int32 PortFlags, UObject * Parent, FOutputDevice * ErrorText)
Imports the GUIDs value from a text buffer.
Parameters
Buffer The text buffer to import from.
PortFlags Not used.
Parent Not used.
ErrorText The output device for error logging.
Returns
true on success, false otherwise.
See also
ExportTextItem
References Buffer, and Parent.
Invalidate()
void FGuid::Invalidate () inline
Invalidates the GUID.
See also
IsValid
Definition at line 305 of file Guid.h.
References A, B, C, and D.
Referenced by FGuid(), USTRUCT(), and USTRUCT().
IsValid()
bool FGuid::IsValid () const inline
Checks whether this GUID is valid or not.
A GUID that has all its components set to zero is considered invalid.
Returns
true if valid, false otherwise.
See also
Invalidate
Definition at line 318 of file Guid.h.
References A, B, C, and D.
Referenced by Sequencer::AddKeyForExternalValue(), FKeyframeTrackEditor< TrackType >::AddKeysToObjects(), UE::MovieScene::TPropertyTrackEntityImportHelperImpl< T >::Commit(), UE::MovieScene::TPropertyTrackWithOverridableChannelsEntityImportHelperImpl< T >::Commit(), FEdGraphPinHandle::GetTypeHash, UCLASS(), and USTRUCT().
NewDeterministicGuid()
FGuid FGuid::NewDeterministicGuid (FStringView ObjectPath, uint64 Seed = 0) static
Create a guid by hashing the given path; this guid will be deterministic when called in multiple cook processes and will thus avoid cook indeterminism caused by FGuid::NewGuid.
ObjectPath and Seed must be deterministic.
References FGuid(), and Seed.
NewGuid()
FGuid FGuid::NewGuid () static
Returns a new GUID.
Returns
A new GUID.
References FGuid().
Referenced by Metasound::Frontend::IGraphController::AddNode(), Metasound::Frontend::IGraphController::AddNode(), Metasound::Frontend::IGraphController::AddTemplateNode(), AWorldDataLayers::CreateDataLayer(), FSmartObjectHandleFactory::CreateHandleForDynamicObject(), DECLARE_MULTICAST_DELEGATE_OneParam(), FFeedbackContext::StartSlowTask(), UCLASS(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), USTRUCT(), and USTRUCT().
NewGuidFromHash()
FGuid FGuid::NewGuidFromHash (const FBlake3Hash & Hash) static
Create a guid from a calculated Blake3 Hash.
References FGuid(), and Hash.
operator[]() [1/2]
uint32 & FGuid::operator[] (int32 Index) inline
Provides access to the GUIDs components.
Parameters
Index The index of the component to return (0...3).
Returns
The component.
Definition at line 187 of file Guid.h.
References A, B, C, checkSlow, and D.
operator[]() [2/2]
const uint32 & FGuid::operator[] (int32 Index) const inline
Provides read-only access to the GUIDs components.
Parameters
Index The index of the component to return (0...3).
Returns
The component.
Definition at line 209 of file Guid.h.
References A, B, C, checkSlow, and D.
Parse() [1/3]
bool FGuid::Parse (const FString & GuidString, FGuid & OutGuid) static
References FGuid().
Parse() [2/3]
bool FGuid::Parse (const TCHAR * GuidString, FGuid & OutGuid) static
Converts a string to a GUID.
Parameters
GuidString The string to convert.
OutGuid Will contain the parsed GUID.
Returns
true if the string was converted successfully, false otherwise.
See also
ParseExact, ToString
References FGuid().
Referenced by FGuid(), LexFromString, and KeyChainUtilities::LoadKeyChainFromFile().
Parse() [3/3]
bool FGuid::Parse (FStringView GuidString, FGuid & OutGuid) static
References FGuid().
ParseExact() [1/3]
bool FGuid::ParseExact (const FString & GuidString, EGuidFormats Format, FGuid & OutGuid) static
References FGuid(), and Format.
ParseExact() [2/3]
bool FGuid::ParseExact (const TCHAR * GuidString, EGuidFormats Format, FGuid & OutGuid) static
Converts a string with the specified format to a GUID.
Parameters
GuidString The string to convert.
Format The string format to parse.
OutGuid Will contain the parsed GUID.
Returns
true if the string was converted successfully, false otherwise.
See also
Parse, ToString
References FGuid(), and Format.
ParseExact() [3/3]
bool FGuid::ParseExact (FStringView GuidString, EGuidFormats Format, FGuid & OutGuid) static
References FGuid(), and Format.
Serialize() [1/2]
bool FGuid::Serialize (FArchive & Ar) inline
Definition at line 241 of file Guid.h.
References Ar.
Serialize() [2/2]
bool FGuid::Serialize (FStructuredArchive::FSlot Slot) inline
Definition at line 260 of file Guid.h.
ToString()
FString FGuid::ToString (EGuidFormats Format = EGuidFormats::Digits) const inline
Converts this GUID to its string representation.
Parameters
Format The string format to use.
Returns
The string representation.
Definition at line 329 of file Guid.h.
References AppendString(), Digits, and Format.
Referenced by FSkeletalMeshLODModel::FSkeletalMeshLODModel(), AWorldDataLayers::CreateDataLayer(), RigVMTypeUtils::GetUniqueStructTypeName(), and USTRUCT().
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FGuid & Guid) friend
Calculates the hash for a GUID.
Parameters
Guid The GUID to calculate the hash for.
Returns
The hash.
Definition at line 358 of file Guid.h.
References FGuid(), CityHash64(), and Guid.
LexFromString
void LexFromString (FGuid & Result, const TCHAR * String) friend
Definition at line 255 of file Guid.h.
References FGuid(), Parse(), and String.
LexToString
FString LexToString (const FGuid & Value) friend
Guid default string conversion.
Definition at line 250 of file Guid.h.
References FGuid(), and Value.
operator!=
bool operator!= (const FGuid & X, const FGuid & Y) friend
Compares two GUIDs for inequality.
Parameters
X The first GUID to compare.
Y The second GUID to compare.
Returns
true if the GUIDs are not equal, false otherwise.
Definition at line 161 of file Guid.h.
References FGuid(), X, and Y.
operator<
bool operator< (const FGuid & X, const FGuid & Y) friend
Compares two GUIDs.
Parameters
X The first GUID to compare.
Y The second GUID to compare.
Returns
true if the first GUID is less than the second one.
Definition at line 173 of file Guid.h.
References FGuid(), X, and Y.
operator<< [1/2]
FArchive & operator<< (FArchive & Ar, FGuid & G) friend
Serializes a GUID from or into an archive.
Parameters
Ar The archive to serialize from or into.
G The GUID to serialize.
References FGuid(), Ar, and G.
operator<< [2/2]
void operator<< (FStructuredArchive::FSlot Slot, FGuid & G) friend
Serializes a GUID from or into a structured archive slot.
Parameters
Slot The structured archive slot to serialize from or into
G The GUID to serialize.
References FGuid(), and G.
operator==
bool operator== (const FGuid & X, const FGuid & Y) friend
Compares two GUIDs for equality.
Parameters
X The first GUID to compare.
Y The second GUID to compare.
Returns
true if the GUIDs are equal, false otherwise.
Definition at line 149 of file Guid.h.
References FGuid(), X, and Y.
Field Documentation
A
uint32 FGuid::A
Holds the first component.
Definition at line 417 of file Guid.h.
Referenced by FGuid(), FGuid(), Metasound::TArrayRandomGetOperator< ArrayType >::GetSameNodeInCompositionId(), Metasound::TArrayRandomGetOperator< ArrayType >::GetSameNodeSharedStateId(), Invalidate(), IsValid(), operator[](), and operator[]().
B
uint32 FGuid::B
Holds the second component.
Definition at line 420 of file Guid.h.
Referenced by FGuid(), FGuid(), Metasound::TArrayRandomGetOperator< ArrayType >::GetSameNodeInCompositionId(), Metasound::TArrayRandomGetOperator< ArrayType >::GetSameNodeSharedStateId(), Invalidate(), IsValid(), operator[](), and operator[]().
C
uint32 FGuid::C
Holds the third component.
Definition at line 423 of file Guid.h.
Referenced by FGuid(), FGuid(), Metasound::TArrayRandomGetOperator< ArrayType >::GetSameNodeInCompositionId(), Metasound::TArrayRandomGetOperator< ArrayType >::GetSameNodeSharedStateId(), Invalidate(), IsValid(), operator[](), and operator[]().
D
uint32 FGuid::D
Holds the fourth component.
Definition at line 426 of file Guid.h.
Referenced by FGuid(), FGuid(), Metasound::TArrayRandomGetOperator< ArrayType >::GetSameNodeInCompositionId(), Metasound::TArrayRandomGetOperator< ArrayType >::GetSameNodeSharedStateId(), Invalidate(), IsValid(), operator[](), and operator[]().
The documentation for this struct was generated from the following file:
Runtime/Core/Public/Misc/Guid.h