Unreal Engine 5.6 C++ API: FPredictMatch8 Struct Reference
FPredictMatch8 Struct Reference
Predict Match (pm-k) is a fuzzy matching algorithm that enables looking for a potential match across multiple substrings at the same time.
#include "PM-k.h"
Public Member Functions
FPredictMatch8 ()
void AddPredictionWord (const uint8 *Data, const uint16 DataLen)
uint16 GetMinimumWordLength () const
bool MatchApproximate (const uint8 *Data, const uint32 DataLen) const
void Reset ()
Static Public Attributes
static constexpr uint16 ALPHABET_SIZE = 256
static constexpr uint16 TABLE_SIZE = 256
Static Private Member Functions
static uint16 HashFn (const uint16 A, const uint8 B)
static bool PredictMatch (const uint16 *RESTRICT PredictMatchTable, const uint8 *RESTRICT Data, const uint32 DataLen)
Private Attributes
uint16 BitApproxTable [ALPHABET_SIZE]
uint16 MinimumWordLength
uint16 PredictMatchTable [TABLE_SIZE]
Detailed Description
Predict Match (pm-k) is a fuzzy matching algorithm that enables looking for a potential match across multiple substrings at the same time.
We take two approaches, one is Bitap (Bit Approximation) which uses a sliding window of the size of the smallest substring (small substrings will create more false positives). Bitap is very quick for scanning potential matches. We then use pm-8, a sliding window of a fixed size (in our case 8 bytes), to further look for potential matches. If we find a hit, we must defer to slower substring matching approaches to confirm the match. PredictMatch relies on hashing to distribute the mapping of characters in substrings at specific offsets. This hashing helps reduce overlaps between similar substrings which reduces false positives, however this does mean that if your hash is poor, or the table size is too small, you may have more false positives than preferred.
This implementation is written by Epic but based on the licensed pm4-bitap.c implementation found at https://www.genivia.com/ugrep.html
Definition at line 53 of file PM-k.h.
Constructor & Destructor Documentation
FPredictMatch8()
FPredictMatch8::FPredictMatch8 () inline
Definition at line 58 of file PM-k.h.
References Reset.
Member Function Documentation
AddPredictionWord()
void FPredictMatch8::AddPredictionWord (const uint8 * Data, const uint16 DataLen) inline
Definition at line 68 of file PM-k.h.
References BitApproxTable, Bytes, check, HashFn(), MinimumWordLength, and PredictMatchTable.
GetMinimumWordLength()
uint16 FPredictMatch8::GetMinimumWordLength () const inline
Definition at line 63 of file PM-k.h.
References MinimumWordLength.
HashFn()
uint16 FPredictMatch8::HashFn (const uint16 A, const uint8 B) inline static private
Definition at line 183 of file PM-k.h.
References A, B, and TABLE_SIZE.
Referenced by AddPredictionWord(), and PredictMatch().
MatchApproximate()
bool FPredictMatch8::MatchApproximate (const uint8 * Data, const uint32 DataLen) const inline
Definition at line 132 of file PM-k.h.
References BitApproxTable, check, MinimumWordLength, PredictMatch(), and PredictMatchTable.
PredictMatch()
bool FPredictMatch8::PredictMatch (const uint16 *RESTRICT PredictMatchTable, const uint8 *RESTRICT Data, const uint32 DataLen) inline static private
Definition at line 188 of file PM-k.h.
References Bytes, check, HashFn(), PredictMatchTable, and RESTRICT.
Referenced by MatchApproximate().
Reset()
void FPredictMatch8::Reset () inline
Definition at line 173 of file PM-k.h.
References BitApproxTable, FMemory::Memset(), MinimumWordLength, and PredictMatchTable.
Field Documentation
ALPHABET_SIZE
uint16 FPredictMatch8::ALPHABET_SIZE = 256 static constexpr
Definition at line 56 of file PM-k.h.
BitApproxTable
uint16 FPredictMatch8::BitApproxTable[ALPHABET_SIZE] private
Definition at line 257 of file PM-k.h.
Referenced by AddPredictionWord(), MatchApproximate(), and Reset().
MinimumWordLength
uint16 FPredictMatch8::MinimumWordLength private
Definition at line 252 of file PM-k.h.
Referenced by AddPredictionWord(), GetMinimumWordLength(), MatchApproximate(), and Reset().
PredictMatchTable
uint16 FPredictMatch8::PredictMatchTable[TABLE_SIZE] private
Definition at line 270 of file PM-k.h.
Referenced by AddPredictionWord(), MatchApproximate(), PredictMatch(), and Reset().
TABLE_SIZE
uint16 FPredictMatch8::TABLE_SIZE = 256 static constexpr
Definition at line 55 of file PM-k.h.
Referenced by HashFn().
The documentation for this struct was generated from the following file:
Runtime/CoreUObject/Internal/UObject/CoreRedirects/PM-k.h