Unreal Engine 5.6 C++ API: UE::Math::TVector< T > Struct Template Reference
UE::Math::TVector< T > Struct Template Reference
A vector in 3-D space composed of components (X, Y, Z) with floating point precision.
#include "Vector.h"
Public Types
using FReal = T
Public Member Functions
TVector ()=default
Default constructor (no initialization).
TVector (const FLinearColor &InColor)
Constructs a vector from an FLinearColor.
FORCEINLINE TVector (const TVector2< T > V, T InZ)
Constructs a vector from an TVector2<T> and Z value.
template<typename FArg UE_REQUIRES>
TVector (const TVector< FArg > &From)
FORCEINLINE TVector (const UE::Math::TVector4< T > &V)
Constructor using the XYZ components from a 4D vector.
FORCEINLINE TVector (EForceInit)
Constructor which initializes all components to zero.
FORCEINLINE TVector (T InF)
Constructor initializing all components to a single T value.
FORCEINLINE constexpr TVector (T InF, TVectorConstInit)
FORCEINLINE TVector (T InX, T InY, T InZ)
Constructor using initial values for each component.
template<typename IntType>
TVector (TIntPoint< IntType > A)
Constructs a vector from an FIntPoint.
template<typename IntType>
FORCEINLINE TVector (TIntPoint< IntType > A)
template<typename IntType>
TVector (TIntVector3< IntType > InVector)
Constructs a vector from an FIntVector.
template<typename IntType>
FORCEINLINE TVector (TIntVector3< IntType > InVector)
void AddBounded (const TVector< T > &V, T Radius=MAX_int16)
Add a vector to this and clamp the result in a cube.
bool AllComponentsEqual (T Tolerance=UE_KINDA_SMALL_NUMBER) const
Checks whether all components of this vector are the same, within a tolerance.
TVector< T > BoundToBox (const TVector< T > &Min, const TVector< T > &Max) const
Get a copy of this vector, clamped inside of a cube.
TVector< T > BoundToCube (T Radius) const
Get a copy of this vector, clamped inside of a cube.
T & Component (int32 Index)
Gets a specific component of the vector.
T Component (int32 Index) const
Gets a specific component of the vector.
TVector< T > ComponentMax (const TVector< T > &Other) const
Gets the component-wise max of two vectors.
TVector< T > ComponentMin (const TVector< T > &Other) const
Gets the component-wise min of two vectors.
bool ContainsNaN () const
Utility to check if there are any non-finite values (NaN or Inf) in this vector.
FORCEINLINE T CosineAngle2D (TVector< T > B) const
Returns the cosine of the angle between this vector and another projected onto the XY plane (no Z).
FORCEINLINE TVector< T > Cross (const TVector< T > &V2) const
Calculate cross product between this and another vector.
FORCEINLINE void DiagnosticCheckNaN () const
FORCEINLINE void DiagnosticCheckNaN (const TCHAR *Message) const
FORCEINLINE T Dot (const TVector< T > &V) const
Calculate the dot product between this and another vector.
bool Equals (const TVector< T > &V, T Tolerance=UE_KINDA_SMALL_NUMBER) const
Check against another vector for equality, within specified error limits.
void FindBestAxisVectors (TVector< T > &Axis1, TVector< T > &Axis2) const
Find good arbitrary axis vectors to represent U and V axes of a plane, using this vector as the normal of the plane.
TVector< T > GetAbs () const
Get a copy of this vector with absolute value of each component.
T GetAbsMax () const
Get the maximum absolute value of the vector's components.
T GetAbsMin () const
Get the minimum absolute value of the vector's components.
TVector< T > GetClampedToMaxSize (T MaxSize) const
Create a copy of this vector, with its maximum magnitude clamped to MaxSize.
TVector< T > GetClampedToMaxSize2D (T MaxSize) const
Create a copy of this vector, with the maximum 2D magnitude clamped to MaxSize.
TVector< T > GetClampedToSize (T Min, T Max) const
Create a copy of this vector, with its magnitude clamped between Min and Max.
TVector< T > GetClampedToSize2D (T Min, T Max) const
Create a copy of this vector, with the 2D magnitude clamped between Min and Max.
T GetComponentForAxis (EAxis::Type Axis) const
Get a specific component of the vector, given a specific axis by enum.
T GetMax () const
Get the maximum value of the vector's components.
T GetMin () const
Get the minimum value of the vector's components.
TVector< T > GetSafeNormal (T Tolerance=UE_SMALL_NUMBER, const TVector< T > &ResultIfZero=ZeroVector) const
Gets a normalized copy of the vector, checking it is safe to do so based on the length.
TVector< T > GetSafeNormal2D (T Tolerance=UE_SMALL_NUMBER, const TVector< T > &ResultIfZero=ZeroVector) const
Gets a normalized copy of the 2D components of the vector, checking it is safe to do so.
FORCEINLINE TVector< T > GetSignVector () const
Get a copy of the vector as sign only.
FORCEINLINE TVector< T > GetUnsafeNormal () const
Calculates normalized version of vector without checking for zero length.
FORCEINLINE TVector< T > GetUnsafeNormal2D () const
Calculates normalized 2D version of vector without checking for zero length.
TVector< T > GridSnap (const T &GridSz) const
Gets a copy of this vector snapped to a grid.
T HeadingAngle () const
Convert a direction vector into a 'heading' angle.
bool InitFromCompactString (const FString &InSourceString)
Initialize this Vector based on an FString.
bool InitFromString (const FString &InSourceString)
Initialize this Vector based on an FString.
bool IsNearlyZero (T Tolerance=UE_KINDA_SMALL_NUMBER) const
Checks whether vector is near to zero within a specified tolerance.
bool IsNormalized () const
Checks whether vector is normalized.
bool IsUniform (T Tolerance=UE_KINDA_SMALL_NUMBER) const
Check whether X, Y and Z are nearly equal.
FORCEINLINE bool IsUnit (T LengthSquaredTolerance=UE_KINDA_SMALL_NUMBER) const
Check if the vector is of unit length, with specified tolerance.
bool IsValidIndex (int32 Index) const
Tests if index is valid, i.e.
bool IsZero () const
Checks whether all components of the vector are exactly zero.
T Length () const
Get the length (magnitude) of this vector.
TVector< T > MirrorByPlane (const TPlane< T > &Plane) const
Mirrors a vector about a plane.
TVector< T > MirrorByVector (const TVector< T > &MirrorNormal) const
Mirror a vector about a normal vector.
bool NetSerialize (FArchive &Ar, class UPackageMap *Map, bool &bOutSuccess)
Network serialization function.
bool Normalize (T Tolerance=UE_SMALL_NUMBER)
Normalize this vector in-place if it is larger than a given tolerance.
bool operator!= (const TVector< T > &V) const
Check against another vector for inequality.
FORCEINLINE TVector< T > operator* (const TVector< T > &V) const
Gets the result of component-wise multiplication of this vector by another.
template<typename FArg UE_REQUIRES>
FORCEINLINE TVector< T > operator* (FArg Scale) const
Gets the result of scaling the vector (multiplying each component by a value).
TVector< T > operator*= (const TVector< T > &V)
Multiplies the vector with another vector, using component-wise multiplication.
template<typename FArg UE_REQUIRES>
FORCEINLINE TVector< T > operator*= (FArg Scale)
Scales the vector.
FORCEINLINE TVector< T > operator+ (const TVector< T > &V) const
Gets the result of component-wise addition of this and another vector.
template<typename FArg UE_REQUIRES>
FORCEINLINE TVector< T > operator+ (FArg Bias) const
Gets the result of adding to each component of the vector.
FORCEINLINE TVector< T > operator+= (const TVector< T > &V)
Adds another vector to this.
FORCEINLINE TVector< T > operator- () const
Get a negated copy of the vector.
FORCEINLINE TVector< T > operator- (const TVector< T > &V) const
Gets the result of component-wise subtraction of this by another vector.
template<typename FArg UE_REQUIRES>
FORCEINLINE TVector< T > operator- (FArg Bias) const
Gets the result of subtracting from each component of the vector.
FORCEINLINE TVector< T > operator-= (const TVector< T > &V)
Subtracts another vector from this.
FORCEINLINE TVector< T > operator/ (const TVector< T > &V) const
Gets the result of component-wise division of this vector by another.
template<typename FArg UE_REQUIRES>
TVector< T > operator/ (FArg Scale) const
Gets the result of dividing each component of the vector by a value.
TVector< T > operator/= (const TVector< T > &V)
Divides the vector by another vector, using component-wise division.
template<typename FArg UE_REQUIRES>
TVector< T > operator/= (FArg Scale)
Divides the vector by a number.
bool operator== (const TVector< T > &V) const
Check against another vector for equality.
T & operator[] (int32 Index)
Gets specific component of the vector.
T operator[] (int32 Index) const
Gets specific component of the vector.
FORCEINLINE TVector< T > operator^ (const TVector< T > &V) const
Calculate cross product between this and another vector.
FORCEINLINE T operator| (const TVector< T > &V) const
Calculate the dot product between this and another vector.
TVector< T > Projection () const
Projects 2D components of vector based on Z.
FORCEINLINE TVector< T > ProjectOnTo (const TVector< T > &A) const
Gets a copy of this vector projected onto the input vector.
FORCEINLINE TVector< T > ProjectOnToNormal (const TVector< T > &Normal) const
Gets a copy of this vector projected onto the input vector, which is assumed to be unit length.
TVector< T > Reciprocal () const
Gets the reciprocal of this vector, avoiding division by zero.
TVector< T > RotateAngleAxis (const T AngleDeg, const TVector< T > &Axis) const
Rotates around Axis (assumes Axis.Size() == 1).
TVector< T > RotateAngleAxisRad (const T AngleRad, const TVector< T > &Axis) const
Rotates around Axis (assumes Axis.Size() == 1).
FORCEINLINE UE::Math::TRotator< T > Rotation () const
Return the UE::Math::TRotator<T> orientation corresponding to the direction in which the vector points.
bool Serialize (FArchive &Ar)
bool Serialize (FStructuredArchive::FSlot Slot)
bool SerializeFromMismatchedTag (FName StructTag, FStructuredArchive::FSlot Slot)
void Set (T InX, T InY, T InZ)
Set the values of the vector directly.
void SetComponentForAxis (EAxis::Type Axis, T Component)
Set a specified componet of the vector, given a specific axis by enum.
T Size () const
Get the length (magnitude) of this vector.
T Size2D () const
Get the length of the 2D components of this vector.
T SizeSquared () const
Get the squared length of this vector.
T SizeSquared2D () const
Get the squared length of the 2D components of this vector.
T SquaredLength () const
Get the squared length of this vector.
FString ToCompactString () const
Get a short textural representation of this vector, for compact readable logging.
FText ToCompactText () const
Get a short locale aware textural representation of this vector, for compact readable logging.
void ToDirectionAndLength (TVector< T > &OutDir, double &OutLength) const
Util to convert this vector into a unit direction vector and its original length.
void ToDirectionAndLength (TVector< T > &OutDir, float &OutLength) const
TQuat< T > ToOrientationQuat () const
Return the Quaternion orientation corresponding to the direction in which the vector points.
TRotator< T > ToOrientationRotator () const
Return the TRotator orientation corresponding to the direction in which the vector points.
FString ToString () const
Get a textual representation of this vector.
FText ToText () const
Get a locale aware textual representation of this vector.
TVector2< T > UnitCartesianToSpherical () const
Converts a Cartesian unit vector into spherical coordinates on the unit sphere.
void UnwindEuler ()
When this vector contains Euler angles (degrees), ensure that angles are between +/-180.
Static Public Member Functions
static FORCEINLINE T BoxPushOut (const TVector< T > &Normal, const TVector< T > &Size)
Compute pushout of a box from a plane.
static bool Coincident (const TVector< T > &Normal1, const TVector< T > &Normal2, T ParallelCosineThreshold=UE_THRESH_NORMALS_ARE_PARALLEL)
See if two normal vectors are coincident (nearly parallel and point in the same direction).
static bool Coplanar (const TVector< T > &Base1, const TVector< T > &Normal1, const TVector< T > &Base2, const TVector< T > &Normal2, T ParallelCosineThreshold=UE_THRESH_NORMALS_ARE_PARALLEL)
See if two planes are coplanar.
static void CreateOrthonormalBasis (TVector< T > &XAxis, TVector< T > &YAxis, TVector< T > &ZAxis)
Create an orthonormal basis from a basis with at least two orthogonal vectors.
static FORCEINLINE TVector< T > CrossProduct (const TVector< T > &A, const TVector< T > &B)
Calculate the cross product of two vectors.
static TVector< T > DegreesToRadians (const TVector< T > &DegVector)
Converts a vector containing degree values to a vector containing radian values.
static FORCEINLINE T Dist (const TVector< T > &V1, const TVector< T > &V2)
Euclidean distance between two points.
static FORCEINLINE T Dist2D (const TVector< T > &V1, const TVector< T > &V2)
static FORCEINLINE T Distance (const TVector< T > &V1, const TVector< T > &V2)
static FORCEINLINE T DistSquared (const TVector< T > &V1, const TVector< T > &V2)
Squared distance between two points.
static FORCEINLINE T DistSquared2D (const TVector< T > &V1, const TVector< T > &V2)
static FORCEINLINE T DistSquaredXY (const TVector< T > &V1, const TVector< T > &V2)
Squared distance between two points in the XY plane only.
static FORCEINLINE T DistXY (const TVector< T > &V1, const TVector< T > &V2)
Euclidean distance between two points in the XY plane (ignoring Z).
static FORCEINLINE T DotProduct (const TVector< T > &A, const TVector< T > &B)
Calculate the dot product of two vectors.
static T EvaluateBezier (const TVector< T > *ControlPoints, int32 NumPoints, TArray< TVector< T > > &OutPoints)
Generates a list of sample points on a Bezier curve defined by 2 points.
static void GenerateClusterCenters (TArray< TVector< T > > &Clusters, const TArray< TVector< T > > &Points, int32 NumIterations, int32 NumConnectionsToBeValid)
Given a current set of cluster centers, a set of points, iterate N times to move clusters to be central.
static FORCEINLINE TVector< T > Max (const TVector< T > &A, const TVector< T > &B)
static FORCEINLINE TVector< T > Max3 (const TVector< T > &A, const TVector< T > &B, const TVector< T > &C)
static FORCEINLINE TVector< T > Min (const TVector< T > &A, const TVector< T > &B)
Min, Max, Min3, Max3 like FMath.
static FORCEINLINE TVector< T > Min3 (const TVector< T > &A, const TVector< T > &B, const TVector< T > &C)
static TVector< T > One ()
static bool Orthogonal (const TVector< T > &Normal1, const TVector< T > &Normal2, T OrthogonalCosineThreshold=UE_THRESH_NORMALS_ARE_ORTHOGONAL)
See if two normal vectors are nearly orthogonal (perpendicular), meaning the angle between them is close to 90 degrees.
static bool Parallel (const TVector< T > &Normal1, const TVector< T > &Normal2, T ParallelCosineThreshold=UE_THRESH_NORMALS_ARE_PARALLEL)
See if two normal vectors are nearly parallel, meaning the angle between them is close to 0 degrees.
static T PointPlaneDist (const TVector< T > &Point, const TVector< T > &PlaneBase, const TVector< T > &PlaneNormal)
Calculate the signed distance (in the direction of the normal) between a point and a plane.
static TVector< T > PointPlaneProject (const TVector< T > &Point, const TPlane< T > &Plane)
Calculate the projection of a point on the given plane.
static TVector< T > PointPlaneProject (const TVector< T > &Point, const TVector< T > &A, const TVector< T > &B, const TVector< T > &C)
Calculate the projection of a point on the plane defined by counter-clockwise (CCW) points A,B,C.
static TVector< T > PointPlaneProject (const TVector< T > &Point, const TVector< T > &PlaneBase, const TVector< T > &PlaneNormal)
Calculate the projection of a point on the plane defined by PlaneBase and PlaneNormal.
static bool PointsAreNear (const TVector< T > &Point1, const TVector< T > &Point2, T Dist)
Compare two points and see if they're within specified distance.
static bool PointsAreSame (const TVector< T > &P, const TVector< T > &Q)
Compare two points and see if they're the same, using a threshold.
static TVector< T > RadiansToDegrees (const TVector< T > &RadVector)
Converts a vector containing radian values to a vector containing degree values.
static TVector< T > SlerpNormals (const TVector< T > &NormalA, const TVector< T > &NormalB, T Alpha)
Interpolate from normalized vector A to normalized vector B along a spherical path.
static TVector< T > SlerpVectorToDirection (const TVector< T > &V, const TVector< T > &Direction, T Alpha)
Interpolate from a vector to the direction of another vector along a spherical path.
static T Triple (const TVector< T > &X, const TVector< T > &Y, const TVector< T > &Z)
Triple product of three vectors: X dot (Y cross Z).
static TVector< T > UnitX ()
static TVector< T > UnitY ()
static TVector< T > UnitZ ()
static TVector< T > VectorPlaneProject (const TVector< T > &V, const TVector< T > &PlaneNormal)
Calculate the projection of a vector on the plane defined by PlaneNormal.
static TVector< T > Zero ()
Data Fields
union {
struct {
T X
Vector's X component.
T Y
Vector's Y component.
T Z
Vector's Z component.
}
};
Static Public Attributes
static const TVector< T > BackwardVector
Unreal backward vector (-1,0,0)
static const TVector< T > DownVector
Unreal down vector (0,0,-1)
static const TVector< T > ForwardVector
Unreal forward vector (1,0,0)
static const TVector< T > LeftVector
Unreal left vector (0,-1,0)
static constexpr int32 NumComponents = 3
The number of components this vector type has.
static const TVector< T > OneVector
One vector (1,1,1)
static const TVector< T > RightVector
Unreal right vector (0,1,0)
static const TVector< T > UpVector
Unreal up vector (0,0,1)
static const TVector< T > XAxisVector
Unit X axis vector (1,0,0)
static const TVector< T > YAxisVector
Unit Y axis vector (0,1,0)
static const TVector< T > ZAxisVector
Unit Z axis vector (0,0,1)
static const TVector< T > ZeroVector
A zero vector (0,0,0)
Detailed Description
template<typename T>
struct UE::Math::TVector< T >
A vector in 3-D space composed of components (X, Y, Z) with floating point precision.
Definition at line 50 of file Vector.h.
Member Typedef Documentation
FReal
template<typename T> using UE::Math::TVector< T >::FReal = T
Definition at line 55 of file Vector.h.
Constructor & Destructor Documentation
TVector() [1/13]
template<typename T> UE::Math::TVector< T >::TVector () nodiscard default
Default constructor (no initialization).
Referenced by UE::Math::TPlane< T >::TPlane(), UE::Math::TPlane< T >::TPlane(), UE::Math::TPlane< T >::TPlane(), UE::Math::TPlane< T >::TPlane(), UE::Math::TPlane< T >::TPlane(), UE::Math::TPlane< T >::TPlane(), AddBounded(), BoundToBox(), BoundToCube(), BoxPushOut(), Coincident(), ComponentMax(), ComponentMin(), Coplanar(), CosineAngle2D(), CreateOrthonormalBasis(), Cross(), CrossProduct(), DegreesToRadians(), Dist(), DistSquared(), DistSquaredXY(), DistXY(), Dot(), DotProduct(), Equals(), EvaluateBezier(), FindBestAxisVectors(), GenerateClusterCenters(), GetAbs(), GetClampedToMaxSize(), GetClampedToMaxSize2D(), GetClampedToSize(), GetClampedToSize2D(), UE::Math::TPlane< T >::GetNormal(), UE::Math::TPlane< T >::GetOrigin(), GetSafeNormal(), GetSafeNormal2D(), GetSignVector(), GetUnsafeNormal(), GetUnsafeNormal2D(), GridSnap(), HeadingAngle(), Max(), Max3(), Min(), Min3(), MirrorByPlane(), MirrorByVector(), operator!=(), operator*(), UE::Math::TVector< NumericType >::operator*(), operator*=(), operator+(), UE::Math::TVector< NumericType >::operator+(), operator+=(), operator-(), operator-(), UE::Math::TVector< NumericType >::operator-(), operator-=(), operator/(), UE::Math::TVector< NumericType >::operator/(), operator/=(), operator==(), operator^(), operator|(), Orthogonal(), Parallel(), UE::Math::TPlane< T >::PlaneDot(), PointPlaneDist(), PointPlaneProject(), PointPlaneProject(), PointPlaneProject(), PointsAreNear(), PointsAreSame(), Projection(), ProjectOnTo(), ProjectOnToNormal(), RadiansToDegrees(), Reciprocal(), RotateAngleAxis(), RotateAngleAxisRad(), ToDirectionAndLength(), ToDirectionAndLength(), UE::Math::TPlane< T >::TranslateBy(), Triple(), and VectorPlaneProject().
TVector() [2/13]
template<typename T> FORCEINLINE UE::Math::TVector< T >::TVector (T InF) explicit nodiscard
Constructor initializing all components to a single T value.
Parameters
InF Value to set all components to.
Definition at line 1474 of file Vector.h.
References DiagnosticCheckNaN(), FORCEINLINE, X, Y, and Z.
TVector() [3/13]
template<typename T> FORCEINLINE constexpr UE::Math::TVector< T >::TVector (T InF, TVectorConstInit) nodiscard constexpr
Definition at line 1481 of file Vector.h.
References FORCEINLINE, X, Y, and Z.
TVector() [4/13]
template<typename T> FORCEINLINE UE::Math::TVector< T >::TVector (T InX, T InY, T InZ) nodiscard
Constructor using initial values for each component.
Parameters
InX X Coordinate.
InY Y Coordinate.
InZ Z Coordinate.
Definition at line 1487 of file Vector.h.
References DiagnosticCheckNaN(), FORCEINLINE, X, Y, and Z.
TVector() [5/13]
template<typename T> FORCEINLINE UE::Math::TVector< T >::TVector (const TVector2< T > V, T InZ) explicit nodiscard
Constructs a vector from an TVector2<T> and Z value.
Parameters
V Vector to copy from.
InZ Z Coordinate.
Definition at line 1326 of file Vector.h.
References DiagnosticCheckNaN(), FORCEINLINE, X, Y, and Z.
TVector() [6/13]
template<typename T> FORCEINLINE UE::Math::TVector< T >::TVector (const UE::Math::TVector4< T > & V) nodiscard
Constructor using the XYZ components from a 4D vector.
Parameters
V 4D Vector to copy from.
Definition at line 1102 of file Vector4.h.
References DiagnosticCheckNaN(), FORCEINLINE, X, Y, and Z.
TVector() [7/13]
template<typename T> FORCEINLINE UE::Math::TVector< T >::TVector (const FLinearColor & InColor) explicit nodiscard
Constructs a vector from an FLinearColor.
Parameters
InColor Color to copy from.
Definition at line 1494 of file Vector.h.
References B, DiagnosticCheckNaN(), FORCEINLINE, G, R, X, Y, and Z.
TVector() [8/13]
template<typename T> template<typename IntType> UE::Math::TVector< T >::TVector (TIntVector3< IntType > InVector) explicit nodiscard
Constructs a vector from an FIntVector.
Parameters
InVector FIntVector to copy from.
TVector() [9/13]
template<typename T> template<typename IntType> UE::Math::TVector< T >::TVector (TIntPoint< IntType > A) explicit nodiscard
Constructs a vector from an FIntPoint.
Parameters
A Int Point used to set X and Y coordinates, Z is set to zero.
TVector() [10/13]
template<typename T> FORCEINLINE UE::Math::TVector< T >::TVector (EForceInit) explicit nodiscard
Constructor which initializes all components to zero.
Parameters
EForceInit Force init enum
Definition at line 1517 of file Vector.h.
References DiagnosticCheckNaN(), FORCEINLINE, X, Y, and Z.
TVector() [11/13]
template<typename T> template<typename FArg UE_REQUIRES> UE::Math::TVector< T >::TVector (const TVector< FArg > & From) inline explicit
Definition at line 1218 of file Vector.h.
TVector() [12/13]
template<typename T> template<typename IntType> FORCEINLINE UE::Math::TVector< T >::TVector (TIntVector3< IntType > InVector)
Definition at line 1502 of file Vector.h.
TVector() [13/13]
template<typename T> template<typename IntType> FORCEINLINE UE::Math::TVector< T >::TVector (TIntPoint< IntType > A)
Definition at line 1510 of file Vector.h.
Member Function Documentation
AddBounded()
template<typename T> FORCEINLINE void UE::Math::TVector< T >::AddBounded (const TVector< T > & V, T Radius = MAX_int16)
Add a vector to this and clamp the result in a cube.
Parameters
V Vector to add.
Radius Half size of the cube.
Definition at line 1946 of file Vector.h.
References TVector(), BoundToCube(), and FORCEINLINE.
AllComponentsEqual()
template<typename T> FORCEINLINE bool UE::Math::TVector< T >::AllComponentsEqual (T Tolerance = UE_KINDA_SMALL_NUMBER) const nodiscard
Checks whether all components of this vector are the same, within a tolerance.
Parameters
Tolerance Error tolerance.
Returns
true if the vectors are equal within tolerance limits, false otherwise.
Definition at line 1607 of file Vector.h.
References FORCEINLINE, X, Y, and Z.
Referenced by IsUniform().
BoundToBox()
template<typename T> FORCEINLINE TVector< T > UE::Math::TVector< T >::BoundToBox (const TVector< T > & Min, const TVector< T > & Max) const nodiscard
Get a copy of this vector, clamped inside of a cube.
Definition at line 1872 of file Vector.h.
References TVector(), FMath::Clamp(), FORCEINLINE, Max(), Min(), X, Y, and Z.
BoundToCube()
template<typename T> FORCEINLINE TVector< T > UE::Math::TVector< T >::BoundToCube (T Radius) const nodiscard
Get a copy of this vector, clamped inside of a cube.
Parameters
Radius Half size of the cube.
Returns
A copy of this vector, bound by cube.
Definition at line 1861 of file Vector.h.
References TVector(), FMath::Clamp(), FORCEINLINE, X, Y, and Z.
Referenced by AddBounded().
BoxPushOut()
template<typename T> FORCEINLINE T UE::Math::TVector< T >::BoxPushOut (const TVector< T > & Normal, const TVector< T > & Size) static nodiscard
Compute pushout of a box from a plane.
Parameters
Normal The plane normal.
Size The size of the box.
Returns
Pushout required.
Definition at line 2490 of file Vector.h.
References TVector(), FORCEINLINE, Normal, and Size().
Coincident()
template<typename T> bool UE::Math::TVector< T >::Coincident (const TVector< T > & Normal1, const TVector< T > & Normal2, T ParallelCosineThreshold = UE_THRESH_NORMALS_ARE_PARALLEL) inline static nodiscard
See if two normal vectors are coincident (nearly parallel and point in the same direction).
Parameters
Normal1 First normalized vector.
Normal2 Second normalized vector.
ParallelCosineThreshold Normals are coincident if dot product (cosine of angle between them) is greater than or equal to this. For example: cos(1.0 degrees).
Returns
true if vectors are coincident (nearly parallel and point in the same direction), false otherwise.
Definition at line 1431 of file Vector.h.
References TVector().
Component() [1/2]
template<typename T> FORCEINLINE T & UE::Math::TVector< T >::Component (int32 Index) nodiscard
Gets a specific component of the vector.
Parameters
Index The index of the component required.
Returns
Reference to the specified component.
Definition at line 1952 of file Vector.h.
References check, FORCEINLINE, IsValidIndex(), PRAGMA_DISABLE_DEPRECATION_WARNINGS, and PRAGMA_ENABLE_DEPRECATION_WARNINGS.
Referenced by SetComponentForAxis().
Component() [2/2]
template<typename T> FORCEINLINE T UE::Math::TVector< T >::Component (int32 Index) const nodiscard
Gets a specific component of the vector.
Parameters
Index The index of the component required.
Returns
Copy of the specified component.
Definition at line 1961 of file Vector.h.
References check, FORCEINLINE, IsValidIndex(), PRAGMA_DISABLE_DEPRECATION_WARNINGS, and PRAGMA_ENABLE_DEPRECATION_WARNINGS.
ComponentMax()
template<typename T> FORCEINLINE TVector< T > UE::Math::TVector< T >::ComponentMax (const TVector< T > & Other) const nodiscard
Gets the component-wise max of two vectors.
Definition at line 1704 of file Vector.h.
References TVector(), FORCEINLINE, FMath::Max, Other, X, Y, and Z.
ComponentMin()
template<typename T> FORCEINLINE TVector< T > UE::Math::TVector< T >::ComponentMin (const TVector< T > & Other) const nodiscard
Gets the component-wise min of two vectors.
Definition at line 1698 of file Vector.h.
References TVector(), FORCEINLINE, FMath::Min, Other, X, Y, and Z.
ContainsNaN()
template<typename T> FORCEINLINE bool UE::Math::TVector< T >::ContainsNaN () const
Utility to check if there are any non-finite values (NaN or Inf) in this vector.
Returns
true if there are any non-finite values in this vector, false otherwise.
Definition at line 2296 of file Vector.h.
References FORCEINLINE, X, Y, and Z.
Referenced by FBuoyancyComponentSim::AddForceAtPositionWorld(), FBuoyancyComponentSim::AddTorque(), and UE::AnimNext::TTransformArraySoA< FDefaultAllocator >::ContainsNaN().
Coplanar()
template<typename T> bool UE::Math::TVector< T >::Coplanar (const TVector< T > & Base1, const TVector< T > & Normal1, const TVector< T > & Base2, const TVector< T > & Normal2, T ParallelCosineThreshold = UE_THRESH_NORMALS_ARE_PARALLEL) inline static nodiscard
See if two planes are coplanar.
They are coplanar if the normals are nearly parallel and the planes include the same set of points.
Parameters
Base1 The base point in the first plane.
Normal1 The normal of the first plane.
Base2 The base point in the second plane.
Normal2 The normal of the second plane.
ParallelCosineThreshold Normals are parallel if absolute value of dot product is greater than or equal to this.
Returns
true if the planes are coplanar, false otherwise.
Definition at line 1445 of file Vector.h.
References TVector(), Parallel(), PointPlaneDist(), and UE_THRESH_POINT_ON_PLANE.
CosineAngle2D()
template<typename T> FORCEINLINE T UE::Math::TVector< T >::CosineAngle2D (TVector< T > B) const nodiscard
Returns the cosine of the angle between this vector and another projected onto the XY plane (no Z).
Parameters
B the other vector to find the 2D cosine of the angle with.
Returns
The cosine.
Definition at line 2104 of file Vector.h.
References TVector(), A, B, and FORCEINLINE.
CreateOrthonormalBasis()
template<typename T> void UE::Math::TVector< T >::CreateOrthonormalBasis (TVector< T > & XAxis, TVector< T > & YAxis, TVector< T > & ZAxis) static
Create an orthonormal basis from a basis with at least two orthogonal vectors.
It may change the directions of the X and Y axes to make the basis orthogonal, but it won'T change the direction of the Z axis. All axes will be normalized.
Parameters
XAxis The input basis' XAxis, and upon return the orthonormal basis' XAxis.
YAxis The input basis' YAxis, and upon return the orthonormal basis' YAxis.
ZAxis The input basis' ZAxis, and upon return the orthonormal basis' ZAxis.
Definition at line 2247 of file Vector.h.
References TVector(), Normalize(), SizeSquared(), and UE_DELTA.
Referenced by TLumenCardOBB< float >::Transform().
Cross()
template<typename T> FORCEINLINE TVector< T > UE::Math::TVector< T >::Cross (const TVector< T > & V2) const nodiscard
Calculate cross product between this and another vector.
Parameters
V The other vector.
Returns
The cross product.
Definition at line 1535 of file Vector.h.
References TVector(), and FORCEINLINE.
Referenced by UE::Geometry::VectorUtil::Area(), UE::Geometry::VectorUtil::BitangentFromTangent(), UE::Geometry::TDistLine3Triangle3< float >::ComputeResult(), UE::Geometry::TIntrRay3Triangle3< float >::FindIntersection(), UE::Geometry::TMeshQueries< TriangleMeshType >::GetVolumeArea(), UE::Geometry::TMeshQueries< TriangleMeshType >::GetVolumeArea(), UE::Geometry::TMeshQueries< TriangleMeshType >::GetVolumeAreaCenter(), UE::Geometry::TMeshQueries< TriangleMeshType >::GetVolumeNonWatertight(), UE::Geometry::TOrientedBox3< float >::Merge(), UE::Geometry::VectorUtil::Normal(), UE::Geometry::VectorUtil::NormalArea(), UE::Geometry::VectorUtil::NormalDirection(), UE::Geometry::VectorUtil::PlaneAngleSignedD(), UE::Geometry::VectorUtil::PlaneAngleSignedR(), UE::Geometry::TMeshLocalParam< PointSetType >::PropagateUV(), IntersectionUtil::RayTriangleTest(), UE::Geometry::TQuaternion< RealType >::SetFromTo(), UE::Geometry::VectorUtil::TangentFromBitangent(), UE::Geometry::TIntrRay3Triangle3< float >::TestIntersection(), and UE::Geometry::UnitCross().
CrossProduct()
template<typename T> FORCEINLINE TVector< T > UE::Math::TVector< T >::CrossProduct (const TVector< T > & A, const TVector< T > & B) static nodiscard
Calculate the cross product of two vectors.
Parameters
A The first vector.
B The second vector.
Returns
The cross product.
Definition at line 1541 of file Vector.h.
References TVector(), A, B, and FORCEINLINE.
Referenced by UE::Math::TQuat< T >::RotateVector(), TLumenCardOBB< float >::Transform(), and UE::Math::TQuat< T >::UnrotateVector().
DegreesToRadians()
template<typename T> TVector< T > UE::Math::TVector< T >::DegreesToRadians (const TVector< T > & DegVector) inline static nodiscard
Converts a vector containing degree values to a vector containing radian values.
Parameters
DegVector Vector containing degree values
Returns
Vector containing radian values
Definition at line 1468 of file Vector.h.
References TVector(), and UE_PI.
DiagnosticCheckNaN() [1/2]
template<typename T> FORCEINLINE void UE::Math::TVector< T >::DiagnosticCheckNaN () const inline
Definition at line 147 of file Vector.h.
Referenced by TVector(), TVector(), TVector(), TVector(), TVector(), TVector(), UE::Math::TVector< NumericType >::TVector(), UE::Math::TVector< NumericType >::TVector(), operator*=(), UE::Math::TVector< NumericType >::operator*=(), operator+=(), operator-=(), operator/=(), UE::Math::TVector< NumericType >::operator/=(), UE::Math::operator<<(), UE::Math::operator<<(), UE::Math::operator<<(), UE::Math::operator<<(), and Set().
DiagnosticCheckNaN() [2/2]
template<typename T> FORCEINLINE void UE::Math::TVector< T >::DiagnosticCheckNaN (const TCHAR * Message) const inline
Definition at line 148 of file Vector.h.
Dist()
template<typename T> FORCEINLINE T UE::Math::TVector< T >::Dist (const TVector< T > & V1, const TVector< T > & V2) static nodiscard
Euclidean distance between two points.
Parameters
V1 The first point.
V2 The second point.
Returns
The distance between two points.
Definition at line 2466 of file Vector.h.
References TVector(), DistSquared(), and FORCEINLINE.
Referenced by UE::Math::TVector< NumericType >::Distance(), EvaluateBezier(), and PointsAreNear().
Dist2D()
template<typename T> FORCEINLINE T UE::Math::TVector< T >::Dist2D (const TVector< T > & V1, const TVector< T > & V2) inline static nodiscard
Definition at line 1031 of file Vector.h.
Distance()
template<typename T> FORCEINLINE T UE::Math::TVector< T >::Distance (const TVector< T > & V1, const TVector< T > & V2) inline static nodiscard
Definition at line 1018 of file Vector.h.
DistSquared()
template<typename T> FORCEINLINE T UE::Math::TVector< T >::DistSquared (const TVector< T > & V1, const TVector< T > & V2) static nodiscard
Squared distance between two points.
Parameters
V1 The first point.
V2 The second point.
Returns
The squared distance between two points.
Definition at line 2478 of file Vector.h.
References TVector(), FORCEINLINE, FMath::Square(), X, Y, and Z.
Referenced by Dist(), and UE::Math::TRay< double >::DistSquared().
DistSquared2D()
template<typename T> FORCEINLINE T UE::Math::TVector< T >::DistSquared2D (const TVector< T > & V1, const TVector< T > & V2) inline static nodiscard
Definition at line 1053 of file Vector.h.
DistSquaredXY()
template<typename T> FORCEINLINE T UE::Math::TVector< T >::DistSquaredXY (const TVector< T > & V1, const TVector< T > & V2) static nodiscard
Squared distance between two points in the XY plane only.
Parameters
V1 The first point.
V2 The second point.
Returns
The squared distance between two points in the XY plane
Definition at line 2484 of file Vector.h.
References TVector(), FORCEINLINE, FMath::Square(), X, and Y.
Referenced by UE::Math::TVector< NumericType >::DistSquared2D(), and DistXY().
DistXY()
template<typename T> FORCEINLINE T UE::Math::TVector< T >::DistXY (const TVector< T > & V1, const TVector< T > & V2) static nodiscard
Euclidean distance between two points in the XY plane (ignoring Z).
Parameters
V1 The first point.
V2 The second point.
Returns
The distance between two points in the XY plane.
Definition at line 2472 of file Vector.h.
References TVector(), DistSquaredXY(), and FORCEINLINE.
Referenced by UE::Math::TVector< NumericType >::Dist2D().
Dot()
template<typename T> FORCEINLINE T UE::Math::TVector< T >::Dot (const TVector< T > & V) const nodiscard
Calculate the dot product between this and another vector.
Parameters
V The other vector.
Returns
The dot product.
Definition at line 1553 of file Vector.h.
References TVector(), and FORCEINLINE.
Referenced by UE::Geometry::TAttrBasedQuadricError< float >::TAttrBasedQuadricError(), UE::Geometry::AngleD(), UE::Geometry::AngleR(), UE::Geometry::VectorUtil::BarycentricCoords(), UE::Geometry::TPlane3< FVector::FReal >::ClipSegment(), UE::Geometry::FMeshRefinerBase::ComputeEdgeFlipMetric(), UE::Geometry::TDistLine3Line3< float >::ComputeResult(), UE::Geometry::TDistLine3Ray3< float >::ComputeResult(), UE::Geometry::TDistLine3Segment3< float >::ComputeResult(), UE::Geometry::TDistLine3Triangle3< float >::ComputeResult(), UE::Geometry::TDistPoint3Triangle3< float >::ComputeResult(), UE::Geometry::TDistRay3Segment3< float >::ComputeResult(), UE::Geometry::TSpatialPhotoSet< PixelType, RealType >::ComputeSampleLocation(), UE::Geometry::TFrame3< float >::ConstrainedAlignPerpAxes(), UE::Geometry::TIntrTriangle3Triangle3< float >::ContainsPoint(), UE::Geometry::FAffineKelvinlet::Evaluate(), UE::Geometry::FPinchKelvinlet::Evaluate(), UE::Geometry::TAttrBasedQuadricError< float >::Evaluate(), FastTriWinding::EvaluateOrder1Approx(), FastTriWinding::EvaluateOrder2Approx(), UE::Geometry::TIntrRay3Triangle3< float >::FindIntersection(), UE::Geometry::TPlane3< FVector::FReal >::FindLineIntersection(), UE::Geometry::TExactIntrTriangle3Triangle3< float >::FindOrTestWithoutCoplanar(), UE::Geometry::FBoxSphereGenerator::Generate(), UE::Geometry::FGeneralizedCylinderGenerator::Generate(), UE::Geometry::TIntrTriangle3Triangle3< float >::Intersects(), IntersectionUtil::LineSphereIntersection(), IntersectionUtil::LineSphereTest(), UE::Geometry::TOrientedBox3< float >::Merge(), UE::Geometry::TVolPresQuadricError< float >::OptimalPoint(), FastTriWinding::Order1Approx(), FastTriWinding::Order2Approx(), UE::Geometry::VectorUtil::PlaneAngleSignedD(), UE::Geometry::VectorUtil::PlaneAngleSignedR(), UE::Geometry::PointSegmentDistance(), UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::PointSegmentDistance(), UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::PointSegmentDistance(), UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::PointTriangleDistance(), UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::PointTriangleDistance(), UE::Geometry::TIntrTriangle3Triangle3< float >::ProjectOntoAxis(), UE::Geometry::TMeshLocalParam< PointSetType >::PropagateUV(), UE::Geometry::TFrame3< float >::RayPlaneIntersection(), IntersectionUtil::RaySphereTest(), IntersectionUtil::RayTriangleTest(), UE::Geometry::TQuaternion< RealType >::SetFromTo(), UE::Geometry::TDistRay3Segment3< float >::SquaredDistance(), UE::Geometry::SquaredDistanceFromLineIntegratedAlongSegment(), UE::Geometry::TIntrTriangle3Triangle3< float >::Test(), UE::Geometry::TIntrRay3Triangle3< float >::TestIntersection(), UE::Geometry::TFrame3< float >::ToPlane(), UE::Geometry::TFrame3< float >::ToPlaneUV(), UE::Geometry::VectorUtil::TriGradient(), and UE::Geometry::VectorUtil::VectorCot().
DotProduct()
template<typename T> FORCEINLINE T UE::Math::TVector< T >::DotProduct (const TVector< T > & A, const TVector< T > & B) static nodiscard
Calculate the dot product of two vectors.
Parameters
A The first vector.
B The second vector.
Returns
The dot product.
Definition at line 1559 of file Vector.h.
References TVector(), A, B, and FORCEINLINE.
Referenced by UE::Math::TRay< double >::ClosestPoint(), UE::Math::TBox< double >::ComputeSquaredDistanceToBox(), UE::Math::TRay< double >::DistSquared(), UE::Geometry::TIntrRay3OrientedBox3< float >::FindIntersection(), UE::Math::TRay< double >::GetParameter(), IntersectionUtil::RayCircleIntersection(), and TLumenCardOBB< float >::Transform().
Equals()
template<typename T> FORCEINLINE bool UE::Math::TVector< T >::Equals (const TVector< T > & V, T Tolerance = UE_KINDA_SMALL_NUMBER) const nodiscard
Check against another vector for equality, within specified error limits.
Parameters
V The vector to check against.
Tolerance Error tolerance.
Returns
true if the vectors are equal within tolerance limits, false otherwise.
Definition at line 1601 of file Vector.h.
References TVector(), FORCEINLINE, X, Y, and Z.
Referenced by FPoly::GetOutsideWindings().
EvaluateBezier()
template<typename T> T UE::Math::TVector< T >::EvaluateBezier (const TVector< T > * ControlPoints, int32 NumPoints, TArray< TVector< T > > & OutPoints) static
Generates a list of sample points on a Bezier curve defined by 2 points.
Parameters
ControlPoints Array of 4 FVectors (vert1, controlpoint1, controlpoint2, vert2).
NumPoints Number of samples.
OutPoints Receives the output samples.
Returns
The path length.
Definition at line 2195 of file Vector.h.
References TVector(), check, ControlPoints, Dist(), and Length().
FindBestAxisVectors()
template<typename T> void UE::Math::TVector< T >::FindBestAxisVectors (TVector< T > & Axis1, TVector< T > & Axis2) const
Find good arbitrary axis vectors to represent U and V axes of a plane, using this vector as the normal of the plane.
Parameters
Axis1 Reference to first axis.
Axis2 Reference to second axis.
Definition at line 2280 of file Vector.h.
References TVector(), GetSafeNormal(), X, Y, and Z.
GenerateClusterCenters()
template<typename T> void UE::Math::TVector< T >::GenerateClusterCenters (TArray< TVector< T > > & Clusters, const TArray< TVector< T > > & Points, int32 NumIterations, int32 NumConnectionsToBeValid) static
Given a current set of cluster centers, a set of points, iterate N times to move clusters to be central.
Parameters
Clusters Reference to array of Clusters.
Points Set of points.
NumIterations Number of iterations.
NumConnectionsToBeValid Sometimes you will have long strings that come off the mass of points which happen to have been chosen as Cluster starting points. You want to be able to disregard those.
Definition at line 2128 of file Vector.h.
References TVector(), TArray< InElementType, InAllocatorType >::AddZeroed(), INDEX_NONE, TArray< InElementType, InAllocatorType >::Num(), Points, SizeSquared(), and UE_BIG_NUMBER.
GetAbs()
template<typename T> FORCEINLINE TVector< T > UE::Math::TVector< T >::GetAbs () const nodiscard
Get a copy of this vector with absolute value of each component.
Returns
A copy of this vector with absolute value of each component.
Definition at line 1710 of file Vector.h.
References TVector(), FORCEINLINE, X, Y, and Z.
Referenced by UE::Geometry::TWatertightRay3< float >::Init().
GetAbsMax()
template<typename T> FORCEINLINE T UE::Math::TVector< T >::GetAbsMax () const nodiscard
Get the maximum absolute value of the vector's components.
Returns
The maximum absolute value of the vector's components.
Definition at line 1680 of file Vector.h.
References FORCEINLINE, FMath::Max, X, Y, and Z.
GetAbsMin()
template<typename T> FORCEINLINE T UE::Math::TVector< T >::GetAbsMin () const nodiscard
Get the minimum absolute value of the vector's components.
Returns
The minimum absolute value of the vector's components.
Definition at line 1692 of file Vector.h.
References FORCEINLINE, FMath::Min, X, Y, and Z.
GetClampedToMaxSize()
template<typename T> FORCEINLINE TVector< T > UE::Math::TVector< T >::GetClampedToMaxSize (T MaxSize) const nodiscard
Create a copy of this vector, with its maximum magnitude clamped to MaxSize.
Definition at line 1906 of file Vector.h.
References TVector(), FORCEINLINE, MaxSize, Scale, SizeSquared(), FMath::Square(), UE_KINDA_SMALL_NUMBER, X, Y, Z, and ZeroVector.
GetClampedToMaxSize2D()
template<typename T> FORCEINLINE TVector< T > UE::Math::TVector< T >::GetClampedToMaxSize2D (T MaxSize) const nodiscard
Create a copy of this vector, with the maximum 2D magnitude clamped to MaxSize.
Z is unchanged.
Definition at line 1926 of file Vector.h.
References TVector(), FORCEINLINE, MaxSize, Scale, SizeSquared2D(), FMath::Square(), UE_KINDA_SMALL_NUMBER, X, Y, and Z.
GetClampedToSize()
template<typename T> FORCEINLINE TVector< T > UE::Math::TVector< T >::GetClampedToSize (T Min, T Max) const nodiscard
Create a copy of this vector, with its magnitude clamped between Min and Max.
Definition at line 1884 of file Vector.h.
References TVector(), FMath::Clamp(), FORCEINLINE, Max(), Min(), TSequenceHistory< HistorySize >::Size, UE_SMALL_NUMBER, and ZeroVector.
Referenced by FBuoyancyComponentSim::ComputeWaterForce().
GetClampedToSize2D()
template<typename T> FORCEINLINE TVector< T > UE::Math::TVector< T >::GetClampedToSize2D (T Min, T Max) const nodiscard
Create a copy of this vector, with the 2D magnitude clamped between Min and Max.
Z is unchanged.
Definition at line 1895 of file Vector.h.
References TVector(), FMath::Clamp(), FORCEINLINE, Max(), Min(), Size2D(), UE_SMALL_NUMBER, X, Y, Z, and ZeroVector.
GetComponentForAxis()
template<typename T> FORCEINLINE T UE::Math::TVector< T >::GetComponentForAxis (EAxis::Type Axis) const nodiscard
Get a specific component of the vector, given a specific axis by enum.
Definition at line 1976 of file Vector.h.
References Axis, FORCEINLINE, EAxis::None, EAxis::X, X, EAxis::Y, Y, EAxis::Z, and Z.
Referenced by SGraphPinVector< NumericType >::SetNewValueHelper(), and SGraphPinVectorSlider< NumericType >::SetNewValueHelper().
GetMax()
template<typename T> FORCEINLINE T UE::Math::TVector< T >::GetMax () const nodiscard
Get the maximum value of the vector's components.
Returns
The maximum value of the vector's components.
Definition at line 1674 of file Vector.h.
References FORCEINLINE, FMath::Max, X, Y, and Z.
Referenced by UE::Geometry::TOrientedBox3< float >::SignedDistance().
GetMin()
template<typename T> FORCEINLINE T UE::Math::TVector< T >::GetMin () const nodiscard
Get the minimum value of the vector's components.
Returns
The minimum value of the vector's components.
Definition at line 1686 of file Vector.h.
References FORCEINLINE, FMath::Min, X, Y, and Z.
GetSafeNormal()
template<typename T> FORCEINLINE TVector< T > UE::Math::TVector< T >::GetSafeNormal (T Tolerance = UE_SMALL_NUMBER, const TVector< T > & ResultIfZero = ZeroVector) const nodiscard
Gets a normalized copy of the vector, checking it is safe to do so based on the length.
Returns zero vector by default if vector length is too small to safely normalize.
Parameters
Tolerance Minimum squared vector length. Must be positive.
Returns
A normalized copy if safe, ResultIfZero otherwise.
Definition at line 2060 of file Vector.h.
References TVector(), FORCEINLINE, Scale, X, Y, and Z.
Referenced by UE::Math::TPlane< T >::TPlane(), FBuoyancyComponentSim::ApplyLinearDrag(), FBuoyancyComponentSim::ComputeWaterForce(), FindBestAxisVectors(), HeadingAngle(), UE::Math::TRotationMatrix< T >::MakeFromX(), UE::Math::TRotationMatrix< T >::MakeFromXY(), UE::Math::TRotationMatrix< T >::MakeFromXZ(), UE::Math::TRotationMatrix< T >::MakeFromY(), UE::Math::TRotationMatrix< T >::MakeFromYX(), UE::Math::TRotationMatrix< T >::MakeFromYZ(), UE::Math::TRotationMatrix< T >::MakeFromZ(), UE::Math::TRotationMatrix< T >::MakeFromZX(), UE::Math::TRotationMatrix< T >::MakeFromZY(), UE::Geometry::TOrientedBox3< float >::Merge(), FSphericalSector::SetAxis(), UE::Landscape::FHeightmapTexel::SetNormal(), FRandomStream::VRandCone(), and FRandomStream::VRandCone().
GetSafeNormal2D()
template<typename T> FORCEINLINE TVector< T > UE::Math::TVector< T >::GetSafeNormal2D (T Tolerance = UE_SMALL_NUMBER, const TVector< T > & ResultIfZero = ZeroVector) const nodiscard
Gets a normalized copy of the 2D components of the vector, checking it is safe to do so.
Z is set to zero. Returns zero vector by default if vector length is too small to normalize.
Parameters
Tolerance Minimum squared vector length. Must be positive.
Returns
Normalized copy if safe, otherwise returns ResultIfZero.
Definition at line 2078 of file Vector.h.
References TVector(), FORCEINLINE, Scale, X, Y, and Z.
GetSignVector()
template<typename T> FORCEINLINE TVector< T > UE::Math::TVector< T >::GetSignVector () const nodiscard
Get a copy of the vector as sign only.
Each component is set to +1 or -1, with the sign of zero treated as +1.
Parameters
A copy of the vector with each component set to +1 or -1
Definition at line 1823 of file Vector.h.
References TVector(), FORCEINLINE, X, Y, and Z.
Referenced by UE::Math::TTransform< T >::ConstructTransformFromMatrixWithDesiredScale().
GetUnsafeNormal()
template<typename T> FORCEINLINE TVector< T > UE::Math::TVector< T >::GetUnsafeNormal () const nodiscard
Calculates normalized version of vector without checking for zero length.
Returns
Normalized version of vector.
See also
GetSafeNormal()
Definition at line 1841 of file Vector.h.
References TVector(), FORCEINLINE, Scale, X, Y, and Z.
Referenced by HemiOctahedronToUnitVector().
GetUnsafeNormal2D()
template<typename T> FORCEINLINE TVector< T > UE::Math::TVector< T >::GetUnsafeNormal2D () const nodiscard
Calculates normalized 2D version of vector without checking for zero length.
Returns
Normalized version of vector.
See also
GetSafeNormal2D()
Definition at line 1848 of file Vector.h.
References TVector(), FORCEINLINE, Scale, X, and Y.
GridSnap()
template<typename T> FORCEINLINE TVector< T > UE::Math::TVector< T >::GridSnap (const T & GridSz) const nodiscard
Gets a copy of this vector snapped to a grid.
Parameters
GridSz Grid dimension.
Returns
A copy of this vector snapped to a grid.
See also
FMath::GridSnap()
Definition at line 1855 of file Vector.h.
References TVector(), FORCEINLINE, FMath::GridSnap(), X, Y, and Z.
HeadingAngle()
template<typename T> FORCEINLINE T UE::Math::TVector< T >::HeadingAngle () const nodiscard
Convert a direction vector into a 'heading' angle.
Returns
'Heading' angle between +/-PI. 0 is pointing down +X.
Definition at line 2446 of file Vector.h.
References TVector(), Angle, FORCEINLINE, GetSafeNormal(), X, Y, and Z.
InitFromCompactString()
template<typename T> FORCEINLINE bool UE::Math::TVector< T >::InitFromCompactString (const FString & InSourceString)
Initialize this Vector based on an FString.
The String is expected to contain V(0) or at least one value X=, Y=, Z=, previously produced by ToCompactString() The TVector<T> will be bogus when InitFromString returns false.
Parameters
InSourceString FString containing the vector values.
Returns
true if any of the X,Y,Z values were read successfully; false otherwise.
Definition at line 2411 of file Vector.h.
References FORCEINLINE, TCString< TCHAR >::Strifind(), TEXT, FParse::Value(), X, Y, and Z.
InitFromString()
template<typename T> FORCEINLINE bool UE::Math::TVector< T >::InitFromString (const FString & InSourceString)
Initialize this Vector based on an FString.
The String is expected to contain X=, Y=, Z=. The TVector<T> will be bogus when InitFromString returns false.
Parameters
InSourceString FString containing the vector values.
Returns
true if the X,Y,Z values were read successfully; false otherwise.
Definition at line 2426 of file Vector.h.
References FORCEINLINE, TEXT, FParse::Value(), X, Y, and Z.
Referenced by DisplayClusterTypesConverter::FromString().
IsNearlyZero()
template<typename T> FORCEINLINE bool UE::Math::TVector< T >::IsNearlyZero (T Tolerance = UE_KINDA_SMALL_NUMBER) const nodiscard
Checks whether vector is near to zero within a specified tolerance.
Parameters
Tolerance Error tolerance.
Returns
true if the vector is near to zero, false otherwise.
Definition at line 1752 of file Vector.h.
References FORCEINLINE, X, Y, and Z.
Referenced by UE::Math::TPlane< T >::IsValid(), ToCompactString(), and ToCompactText().
IsNormalized()
template<typename T> FORCEINLINE bool UE::Math::TVector< T >::IsNormalized () const nodiscard
Checks whether vector is normalized.
Returns
true if normalized, false otherwise.
Definition at line 1786 of file Vector.h.
References FORCEINLINE, SizeSquared(), and UE_THRESH_VECTOR_NORMALIZED.
Referenced by FSphericalSector::FSphericalSector().
IsUniform()
template<typename T> FORCEINLINE bool UE::Math::TVector< T >::IsUniform (T Tolerance = UE_KINDA_SMALL_NUMBER) const nodiscard
Check whether X, Y and Z are nearly equal.
Parameters
Tolerance Specified Tolerance.
Returns
true if X == Y == Z within the specified tolerance.
Definition at line 2048 of file Vector.h.
References AllComponentsEqual(), and FORCEINLINE.
IsUnit()
template<typename T> FORCEINLINE bool UE::Math::TVector< T >::IsUnit (T LengthSquaredTolerance = UE_KINDA_SMALL_NUMBER) const nodiscard
Check if the vector is of unit length, with specified tolerance.
Parameters
LengthSquaredTolerance Tolerance against squared length.
Returns
true if the vector is a unit vector within the specified tolerance.
Definition at line 1780 of file Vector.h.
References FORCEINLINE, and SizeSquared().
Referenced by UnitCartesianToSpherical().
IsValidIndex()
template<typename T> bool UE::Math::TVector< T >::IsValidIndex (int32 Index) const
Tests if index is valid, i.e.
greater than or equal to zero, and less than the number of components in the vector.
Parameters
Index Index to test.
Returns
True if index is valid. False otherwise.
Definition at line 1970 of file Vector.h.
References NumComponents.
Referenced by Component(), and Component().
IsZero()
template<typename T> FORCEINLINE bool UE::Math::TVector< T >::IsZero () const nodiscard
Checks whether all components of the vector are exactly zero.
Returns
true if the vector is exactly zero, false otherwise.
Definition at line 1761 of file Vector.h.
References FORCEINLINE, X, Y, and Z.
Referenced by FStaticMeshComponentHelper::DoCustomNavigableGeometryExport(), UE::Geometry::FGeneralizedCylinderGenerator::Generate(), FStaticMeshComponentHelper::GetNavigationData(), FInstancedStaticMeshComponentHelper::GetNavigationPerInstanceTransforms(), and FAISystem::IsValidDirection().
Length()
template<typename T> FORCEINLINE T UE::Math::TVector< T >::Length () const nodiscard
Get the length (magnitude) of this vector.
Returns
The length of this vector.
Definition at line 1722 of file Vector.h.
References FORCEINLINE, and TSequenceHistory< HistorySize >::Size.
Referenced by FMoveBrushOp::ApplyStamp(), FPinchBrushOp::ApplyStamp(), UE::Geometry::TCircle3< float >::ClosestPoint(), EvaluateBezier(), FastTriWinding::EvaluateOrder1Approx(), FastTriWinding::EvaluateOrder2Approx(), UE::Geometry::TMeshQueries< TriangleMeshType >::GetVolumeArea(), UE::Geometry::TMeshQueries< TriangleMeshType >::GetVolumeArea(), UE::Geometry::TMeshQueries< TriangleMeshType >::GetVolumeAreaCenter(), FastTriWinding::Order1Approx(), FastTriWinding::Order2Approx(), and UE::Geometry::TOrientedBox3< float >::SignedDistance().
Max()
template<typename T> FORCEINLINE TVector< T > UE::Math::TVector< T >::Max (const TVector< T > & A, const TVector< T > & B) static nodiscard
Definition at line 2506 of file Vector.h.
References TVector(), A, B, FORCEINLINE, and FMath::Max.
Referenced by BoundToBox(), UE::Math::TBox< double >::ComputeSquaredDistanceToBox(), GetClampedToSize(), and GetClampedToSize2D().
Max3()
template<typename T> FORCEINLINE TVector< T > UE::Math::TVector< T >::Max3 (const TVector< T > & A, const TVector< T > & B, const TVector< T > & C) static nodiscard
Definition at line 2526 of file Vector.h.
References TVector(), A, B, FORCEINLINE, and FMath::Max3().
Min()
template<typename T> FORCEINLINE TVector< T > UE::Math::TVector< T >::Min (const TVector< T > & A, const TVector< T > & B) static nodiscard
Min, Max, Min3, Max3 like FMath.
Definition at line 2496 of file Vector.h.
References TVector(), A, B, FORCEINLINE, and FMath::Min.
Referenced by BoundToBox(), GetClampedToSize(), and GetClampedToSize2D().
Min3()
template<typename T> FORCEINLINE TVector< T > UE::Math::TVector< T >::Min3 (const TVector< T > & A, const TVector< T > & B, const TVector< T > & C) static nodiscard
Definition at line 2516 of file Vector.h.
References TVector(), A, B, FORCEINLINE, and FMath::Min3().
MirrorByPlane()
template<typename T> TVector< T > UE::Math::TVector< T >::MirrorByPlane (const TPlane< T > & Plane) const inline nodiscard
Mirrors a vector about a plane.
Parameters
Plane Plane to mirror about.
Returns
Mirrored vector.
Definition at line 613 of file Plane.h.
References TVector(), and Plane.
MirrorByVector()
template<typename T> FORCEINLINE TVector< T > UE::Math::TVector< T >::MirrorByVector (const TVector< T > & MirrorNormal) const nodiscard
Mirror a vector about a normal vector.
Parameters
MirrorNormal Normal vector to mirror about.
Returns
Mirrored vector.
Definition at line 2054 of file Vector.h.
References TVector(), and FORCEINLINE.
NetSerialize()
template<typename T> bool UE::Math::TVector< T >::NetSerialize (FArchive & Ar, class UPackageMap * Map, bool & bOutSuccess) inline
Network serialization function.
FVectors NetSerialize without quantization (ie exact values are serialized). se the FVectors_NetQuantize etc (NetSerialization.h) instead.
See also
FVector_NetQuantize, FVector_NetQuantize10, FVector_NetQuantize100, FVector_NetQuantizeNormal
Definition at line 1195 of file Vector.h.
Normalize()
template<typename T> FORCEINLINE bool UE::Math::TVector< T >::Normalize (T Tolerance = UE_SMALL_NUMBER)
Normalize this vector in-place if it is larger than a given tolerance.
Leaves it unchanged if not.
Parameters
Tolerance Minimum squared length of vector for normalization.
Returns
true if the vector was normalized correctly, false otherwise.
Definition at line 1767 of file Vector.h.
References FORCEINLINE, Scale, X, Y, and Z.
Referenced by UE::Math::TRay< double >::TRay(), FViewMatrices::ComputeHalfFieldOfViewPerAxis(), and CreateOrthonormalBasis().
One()
template<typename T> TVector< T > UE::Math::TVector< T >::One () inline static nodiscard
Returns
One Vector (1,1,1)
Definition at line 115 of file Vector.h.
Referenced by UE::Geometry::TTransformSRT3< float >::TTransformSRT3(), UE::Geometry::TTransformSRT3< float >::TTransformSRT3(), UE::Geometry::TTransformSRT3< float >::TTransformSRT3(), UE::Geometry::TTransformSequence3< float >::AppendInverse(), UE::Geometry::TTransformSequence3< float >::ClearScales(), UE::Geometry::TPointHashGrid3< PointDataType, double >::FindInRadiusHelper(), UE::Geometry::TTransformSequence3< float >::GetAccumulatedScale(), UE::Geometry::TTransformSRT3< float >::Identity(), UE::Geometry::TOrientedBox3< float >::UnitPositive(), and UE::Geometry::TOrientedBox3< float >::UnitZeroCentered().
operator!=()
template<typename T> FORCEINLINE bool UE::Math::TVector< T >::operator!= (const TVector< T > & V) const nodiscard
Check against another vector for inequality.
Parameters
V The vector to check against.
Returns
true if the vectors are not equal, false otherwise.
Definition at line 1595 of file Vector.h.
References TVector(), FORCEINLINE, X, Y, and Z.
operator*() [1/2]
template<typename T> FORCEINLINE TVector< T > UE::Math::TVector< T >::operator* (const TVector< T > & V) const nodiscard
Gets the result of component-wise multiplication of this vector by another.
Parameters
V The vector to multiply with.
Returns
The result of multiplication.
Definition at line 1577 of file Vector.h.
References TVector(), FORCEINLINE, X, Y, and Z.
operator*() [2/2]
template<typename T> template<typename FArg UE_REQUIRES> FORCEINLINE TVector< T > UE::Math::TVector< T >::operator* (FArg Scale) const inline nodiscard
Gets the result of scaling the vector (multiplying each component by a value).
Parameters
Scale What to multiply each component by.
Returns
The result of multiplication.
Definition at line 314 of file Vector.h.
operator*=() [1/2]
template<typename T> FORCEINLINE TVector< T > UE::Math::TVector< T >::operator*= (const TVector< T > & V)
Multiplies the vector with another vector, using component-wise multiplication.
Parameters
V What to multiply this vector with.
Returns
Copy of the vector after multiplication.
Definition at line 1637 of file Vector.h.
References TVector(), DiagnosticCheckNaN(), FORCEINLINE, X, Y, and Z.
operator*=() [2/2]
template<typename T> template<typename FArg UE_REQUIRES> FORCEINLINE TVector< T > UE::Math::TVector< T >::operator*= (FArg Scale) inline
Scales the vector.
Parameters
Scale Amount to scale this vector by.
Returns
Copy of the vector after scaling.
Definition at line 415 of file Vector.h.
operator+() [1/2]
template<typename T> FORCEINLINE TVector< T > UE::Math::TVector< T >::operator+ (const TVector< T > & V) const nodiscard
Gets the result of component-wise addition of this and another vector.
Parameters
V The vector to add to this.
Returns
The result of vector addition.
Definition at line 1565 of file Vector.h.
References TVector(), FORCEINLINE, X, Y, and Z.
operator+() [2/2]
template<typename T> template<typename FArg UE_REQUIRES> FORCEINLINE TVector< T > UE::Math::TVector< T >::operator+ (FArg Bias) const inline nodiscard
Gets the result of adding to each component of the vector.
Parameters
Bias How much to add to each component.
Returns
The result of addition.
Definition at line 302 of file Vector.h.
operator+=()
template<typename T> FORCEINLINE TVector< T > UE::Math::TVector< T >::operator+= (const TVector< T > & V)
Adds another vector to this.
Uses component-wise addition.
Parameters
V Vector to add to this.
Returns
Copy of the vector after addition.
Definition at line 1621 of file Vector.h.
References TVector(), DiagnosticCheckNaN(), FORCEINLINE, X, Y, and Z.
operator-() [1/3]
template<typename T> FORCEINLINE TVector< T > UE::Math::TVector< T >::operator- () const nodiscard
Get a negated copy of the vector.
Returns
A negated copy of the vector.
Definition at line 1614 of file Vector.h.
References TVector(), FORCEINLINE, X, Y, and Z.
operator-() [2/3]
template<typename T> FORCEINLINE TVector< T > UE::Math::TVector< T >::operator- (const TVector< T > & V) const nodiscard
Gets the result of component-wise subtraction of this by another vector.
Parameters
V The vector to subtract from this.
Returns
The result of vector subtraction.
Definition at line 1571 of file Vector.h.
References TVector(), FORCEINLINE, X, Y, and Z.
operator-() [3/3]
template<typename T> template<typename FArg UE_REQUIRES> FORCEINLINE TVector< T > UE::Math::TVector< T >::operator- (FArg Bias) const inline nodiscard
Gets the result of subtracting from each component of the vector.
Parameters
Bias How much to subtract from each component.
Returns
The result of subtraction.
Definition at line 290 of file Vector.h.
operator-=()
template<typename T> FORCEINLINE TVector< T > UE::Math::TVector< T >::operator-= (const TVector< T > & V)
Subtracts another vector from this.
Uses component-wise subtraction.
Parameters
V Vector to subtract from this.
Returns
Copy of the vector after subtraction.
Definition at line 1629 of file Vector.h.
References TVector(), DiagnosticCheckNaN(), FORCEINLINE, X, Y, and Z.
operator/() [1/2]
template<typename T> FORCEINLINE TVector< T > UE::Math::TVector< T >::operator/ (const TVector< T > & V) const nodiscard
Gets the result of component-wise division of this vector by another.
Parameters
V The vector to divide by.
Returns
The result of division.
Definition at line 1583 of file Vector.h.
References TVector(), FORCEINLINE, X, Y, and Z.
operator/() [2/2]
template<typename T> template<typename FArg UE_REQUIRES> TVector< T > UE::Math::TVector< T >::operator/ (FArg Scale) const inline nodiscard
Gets the result of dividing each component of the vector by a value.
Parameters
Scale What to divide each component by.
Returns
The result of division.
Definition at line 326 of file Vector.h.
operator/=() [1/2]
template<typename T> FORCEINLINE TVector< T > UE::Math::TVector< T >::operator/= (const TVector< T > & V)
Divides the vector by another vector, using component-wise division.
Parameters
V What to divide vector by.
Returns
Copy of the vector after division.
Definition at line 1645 of file Vector.h.
References TVector(), DiagnosticCheckNaN(), FORCEINLINE, X, Y, and Z.
operator/=() [2/2]
template<typename T> template<typename FArg UE_REQUIRES> TVector< T > UE::Math::TVector< T >::operator/= (FArg Scale) inline
Divides the vector by a number.
Parameters
V What to divide this vector by.
Returns
Copy of the vector after division.
Definition at line 429 of file Vector.h.
operator==()
template<typename T> FORCEINLINE bool UE::Math::TVector< T >::operator== (const TVector< T > & V) const nodiscard
Check against another vector for equality.
Parameters
V The vector to check against.
Returns
true if the vectors are equal, false otherwise.
Definition at line 1589 of file Vector.h.
References TVector(), FORCEINLINE, X, Y, and Z.
operator[]() [1/2]
template<typename T> FORCEINLINE T & UE::Math::TVector< T >::operator[] (int32 Index) nodiscard
Gets specific component of the vector.
Parameters
Index the index of vector component
Returns
reference to component.
Definition at line 1653 of file Vector.h.
References Component, and FORCEINLINE.
operator[]() [2/2]
template<typename T> FORCEINLINE T UE::Math::TVector< T >::operator[] (int32 Index) const nodiscard
Gets specific component of the vector.
Parameters
Index the index of vector component
Returns
Copy of the component.
Definition at line 1659 of file Vector.h.
References Component, and FORCEINLINE.
operator^()
template<typename T> FORCEINLINE TVector< T > UE::Math::TVector< T >::operator^ (const TVector< T > & V) const nodiscard
Calculate cross product between this and another vector.
Parameters
V The other vector.
Returns
The cross product.
Definition at line 1524 of file Vector.h.
References TVector(), FORCEINLINE, X, Y, and Z.
operator|()
template<typename T> FORCEINLINE T UE::Math::TVector< T >::operator| (const TVector< T > & V) const nodiscard
Calculate the dot product between this and another vector.
Parameters
V The other vector.
Returns
The dot product.
Definition at line 1547 of file Vector.h.
References TVector(), FORCEINLINE, X, Y, and Z.
Orthogonal()
template<typename T> bool UE::Math::TVector< T >::Orthogonal (const TVector< T > & Normal1, const TVector< T > & Normal2, T OrthogonalCosineThreshold = UE_THRESH_NORMALS_ARE_ORTHOGONAL) inline static nodiscard
See if two normal vectors are nearly orthogonal (perpendicular), meaning the angle between them is close to 90 degrees.
Parameters
Normal1 First normalized vector.
Normal2 Second normalized vector.
OrthogonalCosineThreshold Normals are orthogonal if absolute value of dot product (cosine of angle between them) is less than or equal to this. For example: cos(89.0 degrees).
Returns
true if vectors are orthogonal (perpendicular), false otherwise.
Definition at line 1438 of file Vector.h.
References TVector().
Parallel()
template<typename T> bool UE::Math::TVector< T >::Parallel (const TVector< T > & Normal1, const TVector< T > & Normal2, T ParallelCosineThreshold = UE_THRESH_NORMALS_ARE_PARALLEL) inline static nodiscard
See if two normal vectors are nearly parallel, meaning the angle between them is close to 0 degrees.
Parameters
Normal1 First normalized vector.
Normal1 Second normalized vector.
ParallelCosineThreshold Normals are parallel if absolute value of dot product (cosine of angle between them) is greater than or equal to this. For example: cos(1.0 degrees).
Returns
true if vectors are nearly parallel, false otherwise.
Definition at line 1424 of file Vector.h.
References TVector().
Referenced by Coplanar().
PointPlaneDist()
template<typename T> T UE::Math::TVector< T >::PointPlaneDist (const TVector< T > & Point, const TVector< T > & PlaneBase, const TVector< T > & PlaneNormal) inline static nodiscard
Calculate the signed distance (in the direction of the normal) between a point and a plane.
Parameters
Point The Point we are checking.
PlaneBase The Base Point in the plane.
PlaneNormal The Normal of the plane (assumed to be unit length).
Returns
Signed distance between point and plane.
Definition at line 1398 of file Vector.h.
References TVector(), and Point.
Referenced by Coplanar(), and PointPlaneProject().
PointPlaneProject() [1/3]
template<typename T> TVector< T > UE::Math::TVector< T >::PointPlaneProject (const TVector< T > & Point, const TPlane< T > & Plane) inline static nodiscard
Calculate the projection of a point on the given plane.
Parameters
Point The point to project onto the plane
Plane The plane
Returns
Projection of Point onto Plane
Definition at line 619 of file Plane.h.
References TVector(), Plane, and Point.
PointPlaneProject() [2/3]
template<typename T> TVector< T > UE::Math::TVector< T >::PointPlaneProject (const TVector< T > & Point, const TVector< T > & A, const TVector< T > & B, const TVector< T > & C) inline static nodiscard
Calculate the projection of a point on the plane defined by counter-clockwise (CCW) points A,B,C.
Parameters
Point The point to project onto the plane
A 1st of three points in CCW order defining the plane
B 2nd of three points in CCW order defining the plane
C 3rd of three points in CCW order defining the plane
Returns
Projection of Point onto plane ABC
Definition at line 627 of file Plane.h.
References TVector(), A, B, Plane, and Point.
PointPlaneProject() [3/3]
template<typename T> TVector< T > UE::Math::TVector< T >::PointPlaneProject (const TVector< T > & Point, const TVector< T > & PlaneBase, const TVector< T > & PlaneNormal) inline static nodiscard
Calculate the projection of a point on the plane defined by PlaneBase and PlaneNormal.
Parameters
Point The point to project onto the plane
PlaneBase Point on the plane
PlaneNorm Normal of the plane (assumed to be unit length).
Returns
Projection of Point onto plane
Definition at line 1410 of file Vector.h.
References TVector(), Point, and PointPlaneDist().
PointsAreNear()
template<typename T> bool UE::Math::TVector< T >::PointsAreNear (const TVector< T > & Point1, const TVector< T > & Point2, T Dist) inline static nodiscard
Compare two points and see if they're within specified distance.
Parameters
Point1 First vector.
Point2 Second vector.
Dist Specified distance.
Returns
Whether two points are within the specified distance. Uses fast distance approximation (linear per-component distance).
Definition at line 1388 of file Vector.h.
References TVector(), Dist(), X, Y, and Z.
PointsAreSame()
template<typename T> bool UE::Math::TVector< T >::PointsAreSame (const TVector< T > & P, const TVector< T > & Q) inline static nodiscard
Compare two points and see if they're the same, using a threshold.
Parameters
P First vector.
Q Second vector.
Returns
Whether points are the same within a threshold. Uses fast distance approximation (linear per-component distance).
Definition at line 1368 of file Vector.h.
References TVector(), UE_THRESH_POINTS_ARE_SAME, X, Y, and Z.
Projection()
template<typename T> FORCEINLINE TVector< T > UE::Math::TVector< T >::Projection () const nodiscard
Projects 2D components of vector based on Z.
Returns
Projected version of vector based on Z.
Definition at line 1834 of file Vector.h.
References TVector(), FORCEINLINE, X, Y, and Z.
ProjectOnTo()
template<typename T> FORCEINLINE TVector< T > UE::Math::TVector< T >::ProjectOnTo (const TVector< T > & A) const nodiscard
Gets a copy of this vector projected onto the input vector.
Parameters
A Vector to project onto, does not assume it is normalized.
Returns
Projected vector.
Definition at line 2115 of file Vector.h.
References TVector(), A, and FORCEINLINE.
ProjectOnToNormal()
template<typename T> FORCEINLINE TVector< T > UE::Math::TVector< T >::ProjectOnToNormal (const TVector< T > & Normal) const nodiscard
Gets a copy of this vector projected onto the input vector, which is assumed to be unit length.
Parameters
Normal Vector to project onto (assumed to be unit length).
Returns
Projected vector.
Definition at line 2121 of file Vector.h.
References TVector(), FORCEINLINE, and Normal.
Referenced by VectorPlaneProject().
RadiansToDegrees()
template<typename T> TVector< T > UE::Math::TVector< T >::RadiansToDegrees (const TVector< T > & RadVector) inline static nodiscard
Converts a vector containing radian values to a vector containing degree values.
Parameters
RadVector Vector containing radian values
Returns
Vector containing degree values
Definition at line 1462 of file Vector.h.
References TVector(), and UE_PI.
Reciprocal()
template<typename T> FORCEINLINE TVector< T > UE::Math::TVector< T >::Reciprocal () const nodiscard
Gets the reciprocal of this vector, avoiding division by zero.
Zero components are set to BIG_NUMBER.
Returns
Reciprocal of this vector.
Definition at line 2013 of file Vector.h.
References TVector(), FORCEINLINE, UE_BIG_NUMBER, X, Y, and Z.
Referenced by FMath::LineBoxIntersection().
RotateAngleAxis()
template<typename T> TVector< T > UE::Math::TVector< T >::RotateAngleAxis (const T AngleDeg, const TVector< T > & Axis) const inline nodiscard
Rotates around Axis (assumes Axis.Size() == 1).
Parameters
AngleDeg Angle to rotate (in degrees).
Axis Axis to rotate around.
Returns
Rotated Vector.
Definition at line 1335 of file Vector.h.
References TVector(), Axis, FMath::DegreesToRadians(), and RotateAngleAxisRad().
Referenced by FRandomStream::VRandCone(), and FRandomStream::VRandCone().
RotateAngleAxisRad()
template<typename T> TVector< T > UE::Math::TVector< T >::RotateAngleAxisRad (const T AngleRad, const TVector< T > & Axis) const inline nodiscard
Rotates around Axis (assumes Axis.Size() == 1).
Parameters
AngleRad Angle to rotate (in radians).
Axis Axis to rotate around.
Returns
Rotated Vector.
Definition at line 1341 of file Vector.h.
References TVector(), Axis, FMath::SinCos(), X, Y, and Z.
Referenced by RotateAngleAxis().
Rotation()
template<typename T> FORCEINLINE UE::Math::TRotator< T > UE::Math::TVector< T >::Rotation () const inline nodiscard
Return the UE::Math::TRotator<T> orientation corresponding to the direction in which the vector points.
Sets Yaw and Pitch to the proper numbers, and sets Roll to zero because the roll can't be determined from a vector.
Note
Identical to 'ToOrientationRotator()' and preserved for legacy reasons.
Returns
UE::Math::TRotator<T> from the Vector's direction.
See also
ToOrientationRotator(), ToOrientationQuat()
Definition at line 834 of file Vector.h.
Referenced by FBookMarkTypeActions::InitFromViewport(), FRandomStream::VRandCone(), and FRandomStream::VRandCone().
Serialize() [1/2]
template<typename T> bool UE::Math::TVector< T >::Serialize (FArchive & Ar) inline
Definition at line 1165 of file Vector.h.
Serialize() [2/2]
template<typename T> bool UE::Math::TVector< T >::Serialize (FStructuredArchive::FSlot Slot) inline
Definition at line 1171 of file Vector.h.
SerializeFromMismatchedTag()
template<typename T> bool UE::Math::TVector< T >::SerializeFromMismatchedTag (FName StructTag, FStructuredArchive::FSlot Slot) inline
Definition at line 1177 of file Vector.h.
Set()
template<typename T> FORCEINLINE void UE::Math::TVector< T >::Set (T InX, T InY, T InZ)
Set the values of the vector directly.
Parameters
InX New X coordinate.
InY New Y coordinate.
InZ New Z coordinate.
Definition at line 1665 of file Vector.h.
References DiagnosticCheckNaN(), FORCEINLINE, X, Y, and Z.
SetComponentForAxis()
template<typename T> FORCEINLINE void UE::Math::TVector< T >::SetComponentForAxis (EAxis::Type Axis, T Component)
Set a specified componet of the vector, given a specific axis by enum.
Definition at line 1993 of file Vector.h.
References Axis, Component(), FORCEINLINE, EAxis::None, EAxis::X, X, EAxis::Y, Y, EAxis::Z, and Z.
Referenced by SGraphPinVector< NumericType >::SetNewValueHelper(), and SGraphPinVectorSlider< NumericType >::SetNewValueHelper().
Size()
template<typename T> FORCEINLINE T UE::Math::TVector< T >::Size () const nodiscard
Get the length (magnitude) of this vector.
Returns
The length of this vector.
Definition at line 1716 of file Vector.h.
References FORCEINLINE, X, Y, and Z.
Referenced by UE::Math::TBoxSphereBounds< float, float >::TBoxSphereBounds(), FBuoyancyComponentSim::ApplyLinearDrag(), BoxPushOut(), FPrimitiveUniformShaderParametersBuilder::Build(), FAtmosphereSetup::ComputeViewData(), TLumenCardOBB< float >::Transform(), and FPlanarReflectionSceneProxy::UpdateTransform().
Size2D()
template<typename T> FORCEINLINE T UE::Math::TVector< T >::Size2D () const nodiscard
Get the length of the 2D components of this vector.
Returns
The 2D length of this vector.
Definition at line 1740 of file Vector.h.
References FORCEINLINE, X, and Y.
Referenced by GetClampedToSize2D().
SizeSquared()
template<typename T> FORCEINLINE T UE::Math::TVector< T >::SizeSquared () const nodiscard
Get the squared length of this vector.
Returns
The squared length of this vector.
Definition at line 1728 of file Vector.h.
References FORCEINLINE, X, Y, and Z.
Referenced by CreateOrthonormalBasis(), GenerateClusterCenters(), GetClampedToMaxSize(), IsNormalized(), IsUnit(), UE::Geometry::TOrientedBox3< float >::Merge(), UE::Math::TSphere< T >::operator+=(), IntersectionUtil::RayCircleIntersection(), and SquaredLength().
SizeSquared2D()
template<typename T> FORCEINLINE T UE::Math::TVector< T >::SizeSquared2D () const nodiscard
Get the squared length of the 2D components of this vector.
Returns
The squared 2D length of this vector.
Definition at line 1746 of file Vector.h.
References FORCEINLINE, X, and Y.
Referenced by GetClampedToMaxSize2D().
SlerpNormals()
template<typename T> TVector< T > UE::Math::TVector< T >::SlerpNormals (const TVector< T > & NormalA, const TVector< T > & NormalB, T Alpha) static nodiscard
Interpolate from normalized vector A to normalized vector B along a spherical path.
Parameters
NormalA Start direction of interpolation, must be normalized.
NormalB End target direction of interpolation, must be normalized.
Alpha interpolation amount, usually between 0-1
Returns
Normalized vector after interpolating between NormalA and NormalB along a spherical path.
SlerpVectorToDirection()
template<typename T> TVector< T > UE::Math::TVector< T >::SlerpVectorToDirection (const TVector< T > & V, const TVector< T > & Direction, T Alpha) static nodiscard
Interpolate from a vector to the direction of another vector along a spherical path.
Parameters
V Vector we interpolate from
Direction Target direction we interpolate to
Alpha interpolation amount, usually between 0-1
Returns
Vector after interpolating between Vector and Direction along a spherical path. The magnitude will remain the length of the starting vector.
SquaredLength()
template<typename T> FORCEINLINE T UE::Math::TVector< T >::SquaredLength () const nodiscard
Get the squared length of this vector.
Returns
The squared length of this vector.
Definition at line 1734 of file Vector.h.
References FORCEINLINE, and SizeSquared().
Referenced by UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::BuildTopDown(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::BuildTopDown(), UE::Geometry::TDistLine3Line3< float >::ComputeResult(), UE::Geometry::TDistLine3Ray3< float >::ComputeResult(), UE::Geometry::TDistLine3Segment3< float >::ComputeResult(), UE::Geometry::TDistPoint3Triangle3< float >::ComputeResult(), UE::Geometry::TDistRay3Segment3< float >::ComputeResult(), UE::Geometry::CreateSeamQuadric(), UE::Geometry::TOrientedBox3< float >::DistanceSquared(), UE::Geometry::FBiLaplacianPullKelvinlet::Divergence(), UE::Geometry::FLaplacianPullKelvinlet::Divergence(), UE::Geometry::FPullKelvinlet::Divergence(), UE::Geometry::FScaleKelvinlet::Divergence(), UE::Geometry::FAffineKelvinlet::Evaluate(), UE::Geometry::FBiLaplacianPullKelvinlet::Evaluate(), UE::Geometry::FLaplacianPullKelvinlet::Evaluate(), UE::Geometry::FPinchKelvinlet::Evaluate(), UE::Geometry::FPullKelvinlet::Evaluate(), UE::Geometry::FScaleKelvinlet::Evaluate(), UE::Geometry::FSharpBiLaplacianPullKelvinlet::Evaluate(), UE::Geometry::FSharpLaplacianPullKelvinlet::Evaluate(), UE::Geometry::FTwistKelvinlet::Evaluate(), IntersectionUtil::LineSphereIntersection(), IntersectionUtil::LineSphereTest(), UE::Geometry::PointSegmentDistance(), UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::PointSegmentDistance(), UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::PointSegmentDistance(), UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::PointTriangleDistance(), UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::PointTriangleDistance(), IntersectionUtil::RaySphereTest(), UE::Geometry::TDistRay3Segment3< float >::SquaredDistance(), and UE::Geometry::VectorUtil::VectorCot().
ToCompactString()
template<typename T> FORCEINLINE FString UE::Math::TVector< T >::ToCompactString () const nodiscard
Get a short textural representation of this vector, for compact readable logging.
Definition at line 2374 of file Vector.h.
References FORCEINLINE, FMath::IsNearlyZero(), IsNearlyZero(), TEXT, X, Y, and Z.
ToCompactText()
template<typename T> FORCEINLINE FText UE::Math::TVector< T >::ToCompactText () const nodiscard
Get a short locale aware textural representation of this vector, for compact readable logging.
Definition at line 2321 of file Vector.h.
References TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::Add(), FText::AsNumber(), FORCEINLINE, FText::Format(), FMath::IsNearlyZero(), IsNearlyZero(), FNumberFormattingOptions::MinimumFractionalDigits, FNumberFormattingOptions::MinimumIntegralDigits, NSLOCTEXT, TEXT, X, Y, and Z.
ToDirectionAndLength() [1/2]
template<typename T> FORCEINLINE void UE::Math::TVector< T >::ToDirectionAndLength (TVector< T > & OutDir, double & OutLength) const
Util to convert this vector into a unit direction vector and its original length.
Parameters
OutDir Reference passed in to store unit direction vector.
OutLength Reference passed in to store length of the vector.
Definition at line 1792 of file Vector.h.
References TVector(), FORCEINLINE, TSequenceHistory< HistorySize >::Size, UE_SMALL_NUMBER, X, Y, Z, and ZeroVector.
ToDirectionAndLength() [2/2]
template<typename T> FORCEINLINE void UE::Math::TVector< T >::ToDirectionAndLength (TVector< T > & OutDir, float & OutLength) const
Definition at line 1807 of file Vector.h.
References TVector(), float, FORCEINLINE, TSequenceHistory< HistorySize >::Size, UE_SMALL_NUMBER, X, Y, Z, and ZeroVector.
ToOrientationQuat()
template<typename T> TQuat< T > UE::Math::TVector< T >::ToOrientationQuat () const nodiscard
Return the Quaternion orientation corresponding to the direction in which the vector points.
Similar to the UE::Math::TRotator<T> version, returns a result without roll such that it preserves the up vector.
Note
If you don'T care about preserving the up vector and just want the most direct rotation, you can use the faster 'FQuat::FindBetweenVectors(FVector::ForwardVector, YourVector)' or 'FQuat::FindBetweenNormals(...)' if you know the vector is of unit length.
Returns
Quaternion from the Vector's direction, without any roll.
See also
ToOrientationRotator(), FQuat::FindBetweenVectors()
ToOrientationRotator()
template<typename T> TRotator< T > UE::Math::TVector< T >::ToOrientationRotator () const nodiscard
Return the TRotator orientation corresponding to the direction in which the vector points.
Sets Yaw and Pitch to the proper numbers, and sets Roll to zero because the roll can'T be determined from a vector.
Returns
TRotator from the Vector's direction, without any roll.
See also
ToOrientationQuat()
Referenced by UE::Math::TVector< NumericType >::Rotation().
ToString()
template<typename T> FORCEINLINE FString UE::Math::TVector< T >::ToString () const nodiscard
Get a textual representation of this vector.
Returns
A string describing the vector.
Definition at line 2304 of file Vector.h.
References FORCEINLINE, TEXT, X, Y, and Z.
ToText()
template<typename T> FORCEINLINE FText UE::Math::TVector< T >::ToText () const nodiscard
Get a locale aware textual representation of this vector.
Returns
A string describing the vector.
Definition at line 2310 of file Vector.h.
References TSortedMap< InKeyType, InValueType, ArrayAllocator, SortPredicate >::Add(), FORCEINLINE, FText::Format(), NSLOCTEXT, TEXT, X, Y, and Z.
Triple()
template<typename T> T UE::Math::TVector< T >::Triple (const TVector< T > & X, const TVector< T > & Y, const TVector< T > & Z) inline static nodiscard
Triple product of three vectors: X dot (Y cross Z).
Parameters
X The first vector.
Y The second vector.
Z The third vector.
Returns
The triple product: X dot (Y cross Z).
Definition at line 1453 of file Vector.h.
References TVector(), X, Y, and Z.
UnitCartesianToSpherical()
template<typename T> FORCEINLINE TVector2< T > UE::Math::TVector< T >::UnitCartesianToSpherical () const nodiscard
Converts a Cartesian unit vector into spherical coordinates on the unit sphere.
Returns
Output Theta will be in the range [0, PI], and output Phi will be in the range [-PI, PI].
Definition at line 2437 of file Vector.h.
References checkSlow, FORCEINLINE, IsUnit(), TSequenceHistory< HistorySize >::Size, X, Y, and Z.
UnitX()
template<typename T> TVector< T > UE::Math::TVector< T >::UnitX () inline static nodiscard
Returns
Unit X Vector (1,0,0)
Definition at line 118 of file Vector.h.
Referenced by UE::Geometry::TLine3< double >::TLine3(), UE::Geometry::TFrame3< float >::ConstrainedAlignPerpAxes(), and UE::Geometry::TMeshTangents< float >::GetInterpolatedTriangleTangent().
UnitY()
template<typename T> TVector< T > UE::Math::TVector< T >::UnitY () inline static nodiscard
Returns
Unit Y Vector (0,1,0)
Definition at line 121 of file Vector.h.
Referenced by UE::Geometry::TMeshTangents< float >::GetInterpolatedTriangleTangent().
UnitZ()
template<typename T> TVector< T > UE::Math::TVector< T >::UnitZ () inline static nodiscard
Returns
Unit Z Vector (0,0,1)
Definition at line 124 of file Vector.h.
Referenced by UE::Geometry::TFrame3< float >::TFrame3(), UE::Geometry::TFrame3< float >::TFrame3(), and UE::Geometry::TFrame3< float >::ConstrainedAlignPerpAxes().
UnwindEuler()
template<typename T> void UE::Math::TVector< T >::UnwindEuler ()
When this vector contains Euler angles (degrees), ensure that angles are between +/-180.
Definition at line 2272 of file Vector.h.
References FMath::UnwindDegrees(), X, Y, and Z.
VectorPlaneProject()
template<typename T> TVector< T > UE::Math::TVector< T >::VectorPlaneProject (const TVector< T > & V, const TVector< T > & PlaneNormal) inline static nodiscard
Calculate the projection of a vector on the plane defined by PlaneNormal.
Parameters
V The vector to project onto the plane.
PlaneNormal Normal of the plane (assumed to be unit length).
Returns
Projection of V onto plane.
Definition at line 1418 of file Vector.h.
References TVector(), and ProjectOnToNormal().
Zero()
template<typename T> TVector< T > UE::Math::TVector< T >::Zero () inline static nodiscard
Returns
Zero Vector (0,0,0)
Definition at line 112 of file Vector.h.
Referenced by UE::Geometry::FMarchingCubes::FMarchingCubes(), UE::Geometry::TVolPresQuadricError< RealType >::FPlaneData::FPlaneData(), UE::Geometry::TAttrBasedQuadricError< float >::TAttrBasedQuadricError(), UE::Geometry::TAttrBasedQuadricError< float >::TAttrBasedQuadricError(), UE::Geometry::TFrame3< float >::TFrame3(), UE::Geometry::TLine3< double >::TLine3(), UE::Geometry::TTransformSRT3< float >::TTransformSRT3(), UE::Geometry::FMarchingCubes::edge_vertex_id(), UE::Geometry::TIntrTriangle3Triangle3< float >::Find(), UE::Geometry::TIntrRay3AxisAlignedBox3< float >::FindIntersection(), UE::Geometry::GenerateArcSegments(), UE::Geometry::GenerateCircleSegments(), UE::Geometry::TFrame3< float >::GetAxis(), UE::Geometry::TTriLinearGridInterpolant< GridType, RealType, bScalarCellSize >::Gradient(), UE::Geometry::TTransformSRT3< float >::Identity(), UE::Geometry::TQuaternion< RealType >::InverseMultiply(), UE::Geometry::FMarchingCubes::polygonize_cell(), UE::Geometry::TIntrRay3AxisAlignedBox3< float >::TestIntersection(), UE::Geometry::FTransferBoneWeights::TransferWeightsToPoint(), and UE::Geometry::TOrientedBox3< float >::UnitZeroCentered().
Field Documentation
[union]
union { ... } UE::Math::TVector< T >
BackwardVector
template<typename T> const TVector<T> UE::Math::TVector< T >::BackwardVector static
Unreal backward vector (-1,0,0)
Definition at line 94 of file Vector.h.
DownVector
template<typename T> const TVector<T> UE::Math::TVector< T >::DownVector static
Unreal down vector (0,0,-1)
Definition at line 88 of file Vector.h.
ForwardVector
template<typename T> const TVector<T> UE::Math::TVector< T >::ForwardVector static
Unreal forward vector (1,0,0)
Definition at line 91 of file Vector.h.
Referenced by UE::Math::TQuat< T >::MakeFromLUFEuler().
LeftVector
template<typename T> const TVector<T> UE::Math::TVector< T >::LeftVector static
Unreal left vector (0,-1,0)
Definition at line 100 of file Vector.h.
Referenced by UE::Math::TQuat< T >::MakeFromLUFEuler().
NumComponents
template<typename T> int32 UE::Math::TVector< T >::NumComponents = 3 static constexpr
The number of components this vector type has.
Definition at line 76 of file Vector.h.
Referenced by IsValidIndex().
OneVector
template<typename T> const TVector<T> UE::Math::TVector< T >::OneVector static
One vector (1,1,1)
Definition at line 82 of file Vector.h.
Referenced by UE::Math::TTransform< double >::TTransform(), UE::Math::TTransform< double >::TTransform(), UE::Math::TTransform< double >::AccumulateWithAdditiveScale(), UE::Math::TTransform< double >::BlendFromIdentityAndAccumulate(), UE::Geometry::IsInside(), UE::Math::TTransform< T >::operator*(), and UE::Math::TTransform< T >::operator*=().
RightVector
template<typename T> const TVector<T> UE::Math::TVector< T >::RightVector static
Unreal right vector (0,1,0)
Definition at line 97 of file Vector.h.
UpVector
template<typename T> const TVector<T> UE::Math::TVector< T >::UpVector static
Unreal up vector (0,0,1)
Definition at line 85 of file Vector.h.
Referenced by UE::Math::TQuat< T >::MakeFromLUFEuler().
X
template<typename T> T UE::Math::TVector< T >::X
Vector's X component.
Definition at line 62 of file Vector.h.
Referenced by FDFVector3::FDFVector3(), FDFVector4::FDFVector4(), FDynamicMeshVertex::FDynamicMeshVertex(), FWedgePositionHelper::FIndexAndZ::FIndexAndZ(), FMaterialParameterValue::FMaterialParameterValue(), UE::Math::TClipProjectionMatrix< T >::TClipProjectionMatrix(), UE::Math::TDualQuat< T >::TDualQuat(), UE::Math::TIntVector3< InIntType >::TIntVector3(), TLargeWorldRenderPosition< double >::TLargeWorldRenderPosition(), TLargeWorldRenderPosition< double >::TLargeWorldRenderPosition(), UE::Geometry::TMatrix3< float >::TMatrix3(), UE::Geometry::TQuadricError< float >::TQuadricError(), TVector(), TVector(), TVector(), TVector(), TVector(), TVector(), TVector(), AdjustParticleBaseSizeForUVFlipping(), AllComponentsEqual(), UE::Math::TTransform< T >::AnyHasNegativeScale(), UE::Geometry::FDynamicGraph3< double >::AppendVertex(), FKelvinletBrushOp::ApplyBrush(), FMoveBrushOp::ApplyStamp(), UE::Geometry::VectorUtil::Bitangent(), UE::Geometry::VectorUtil::BitangentSign(), BoundToBox(), BoundToCube(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::BoxDistanceSqr(), THierarchicalHashGrid2D< 2, 4, FSmartObjectHandle >::CalcCellLocation(), THierarchicalHashGrid2D< 2, 4, FSmartObjectHandle >::CalcQueryBounds(), UE::Geometry::TTriLinearGridInterpolant< GridType, RealType, bScalarCellSize >::Cell(), UE::Geometry::FMarchingCubes::cell_index(), UE::Geometry::TAxisAlignedBox3< float >::Clamp(), ClampVector(), ComponentMax(), ComponentMin(), UE::Geometry::TMeshWindingNumberGrid< TriangleMeshType >::Compute(), UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::Compute(), UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::Compute(), UE::Geometry::TCachingMeshSDF< TriangleMeshType >::compute_intersections(), UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::compute_intersections(), UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::compute_intersections(), UE::Geometry::TAttrBasedQuadricError< float >::ComputeAttributes(), ComputeSquaredDistanceFromBoxToPoint(), FBuoyancyComponentSim::ComputeWaterForce(), UE::Math::TTransform< T >::ConstructTransformFromMatrixWithDesiredScale(), UE::Geometry::TAxisAlignedBox3< float >::Contain(), UE::Geometry::TAxisAlignedBox3< float >::Contains(), UE::Geometry::TOrientedBox3< float >::Contains(), ContainsNaN(), SGraphPinVector< NumericType >::ConvertDefaultValueStringToVector(), SGraphPinVectorSlider< NumericType >::ConvertDefaultValueStringToVector(), UE::Geometry::FMarchingCubes::corner_pos(), UE::Geometry::Cross(), FAnimationCompression_PerTrackUtils::DecompressScale(), FAnimationCompression_PerTrackUtils::DecompressTranslation(), UE::Geometry::Distance(), UE::Geometry::DistanceSquared(), UE::Geometry::TAxisAlignedBox3< float >::DistanceSquared(), UE::Geometry::TOrientedBox3< float >::DistanceSquared(), DistSquared(), DistSquaredXY(), UE::Geometry::TIntrRay3AxisAlignedBox3< float >::DoClipping(), UE::Geometry::Dot(), Dot3(), Dot3(), UE::Geometry::VectorUtil::EpsilonEqual(), UE::Math::TPlane< T >::Equals(), Equals(), UE::Geometry::TAttrBasedQuadricError< float >::Evaluate(), UE::Geometry::TQuadricError< float >::Evaluate(), FastTriWinding::EvaluateOrder2Approx(), UE::Geometry::ExactPredicates::Facing3(), FilteredVolumeLookup(), FilteredVolumeLookupReconverted(), UE::Geometry::FMarchingCubes::find_iso(), FindBestAxisVectors(), UE::Geometry::TSphericalFibonacci< RealType >::FindIndex(), UE::Geometry::TIntrRay3Triangle3< float >::FindIntersection(), UE::Geometry::TIntrRay3Triangle3< float >::FindWatertightIntersectionInternal(), UE::Math::TPlane< T >::Flip(), UE::Geometry::TShiftGridIndexer3< float >::FromGrid(), FVectorFixed48::FromVector(), FVectorIntervalFixed32NoW::FromVector(), UE::Geometry::GenerateBoxSegments(), GetAbs(), GetAbsMax(), GetAbsMin(), USplineMeshComponent::GetAxisValueRef(), USplineMeshComponent::GetAxisValueRef(), USplineMeshComponent::GetAxisValueRef(), FLightVolumeOctreeSemantics::GetBoundingBox(), UE::Geometry::FSegmentTree3::GetBoxDistanceSqr(), TSimpleCellGrid< CellType, InvalidCellValue >::GetCellCoordsUnsafe(), FSquare2DGridHelper::FGrid2D::GetCellIndex(), UE::Geometry::FOccupancyGrid3::GetCellIndexFromPoint(), GetClampedToMaxSize(), GetClampedToMaxSize2D(), GetClampedToSize2D(), UE::Math::TBox< T >::GetClosestPointTo(), GetComponentForAxis(), UE::Geometry::TIntrTriangle3Triangle3< float >::GetCoplanarIntersection(), GetHemiOrthoBasis(), UE::Geometry::TMeshTangents< float >::GetInterpolatedTriangleTangent(), UE::Geometry::TIndexedWeightMap< float >::GetInterpValue(), UE::Geometry::TIndexedWeightMap< float >::GetInterpValueUnsafe(), FLandscapeComponentDataInterface::GetLocalTangentVectors(), FLandscapeComponentDataInterfaceBase::GetLocalTangentVectors(), TBVTree< InElementType, InAllocator >::GetLongestAxis(), GetMax(), GetMin(), GetParticleBaseSize(), GetParticleSizeWithUVFlipInSign(), FNavLocalGridData::GetProjectedCellCenter(), GetSafeNormal(), GetSafeNormal2D(), UE::Geometry::TTransformSRT3< float >::GetSafeScaleReciprocal(), UE::Math::TTransform< T >::GetSafeScaleReciprocal(), GetSignVector(), FAtmosphereSetup::GetTransmittanceAtGroundLevel(), UE::Geometry::TMeshQueries< TriangleMeshType >::GetTriBounds(), GetUnsafeNormal(), GetUnsafeNormal2D(), UE::Geometry::TMeshQueries< TriangleMeshType >::GetVolumeArea(), UE::Geometry::TMeshQueries< TriangleMeshType >::GetVolumeArea(), UE::Geometry::TMeshQueries< TriangleMeshType >::GetVolumeAreaCenter(), UE::Geometry::GetXY(), UE::Geometry::GetXZ(), UE::Geometry::TTriLinearGridInterpolant< GridType, RealType, bScalarCellSize >::Gradient(), GridSnap(), HeadingAngle(), HemiOctahedronToUnitVector(), TSimpleCellGrid< CellType, InvalidCellValue >::Init(), InitFromCompactString(), InitFromString(), UE::Geometry::TCachingMeshSDF< TriangleMeshType >::Initialize(), UE::Geometry::FDynamicGraph3< double >::InsertVertex(), UE::Geometry::ExactPredicates::InSphere3(), INTEL_ORDER_VECTOR(), UE::Geometry::TIntrTriangle3Triangle3< float >::IntersectTriangleWithCoplanarSegment(), Inverse(), UE::Geometry::TQuaternion< RealType >::InverseMultiply(), UE::Geometry::VectorUtil::IsFinite(), UE::Math::TBox< double >::IsInside(), UE::Math::TBox< double >::IsInsideOrOn(), UE::Math::TBox< double >::IsInsideOrOnXY(), UE::Math::TBox< double >::IsInsideXY(), IsNearlyZero(), FAISystem::IsValidLocation(), IsZero(), UE::Geometry::Length(), UE::Geometry::FMeshShapeGenerator::LinearInterp(), FMath::LineBoxIntersection(), UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::make_level_set3_parallel_floodfill(), UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::make_level_set3_parallel_floodfill(), UE::Math::TQuat< T >::MakeFromRotationVector(), UE::Geometry::VectorUtil::MakePerpVector(), UE::Geometry::VectorUtil::MakePerpVectors(), TLargeWorldRenderScalar< double >::MakeQuantizedTile(), TLargeWorldRenderScalar< double >::MakeTile(), UE::Geometry::Max(), UE::Geometry::TOrientedBox3< float >::Merge(), UE::Geometry::Min(), UE::MovieScene::MultiChannelFromData(), UE::Geometry::TQuadricError< float >::MultiplyA(), UE::Geometry::TQuadricError< float >::MultiplySymmetricMatrix(), UE::LWC::NarrowWorldPositionChecked(), UE::LWC::NarrowWorldPositionChecked(), NearestVolumeLookup(), UE::Math::TPlane< T >::Normalize(), Normalize(), NormalsEqual(), NormalsEqual(), FPrimitiveUniformShaderParametersBuilder::ObjectBounds(), UE::Math::TPlane< T >::operator!=(), operator!=(), UE::Geometry::operator*(), UE::Geometry::operator*(), UE::Geometry::TMatrix3< float >::operator*(), UE::Geometry::TMatrix3< float >::operator*(), UE::Math::TPlane< T >::operator*(), UE::Math::TPlane< T >::operator*(), operator*(), UE::Math::TPlane< T >::operator*=(), UE::Math::TPlane< T >::operator*=(), operator*=(), UE::Math::TPlane< T >::operator+(), operator+(), UE::Math::TPlane< T >::operator+=(), operator+=(), UE::Math::TPlane< T >::operator-(), operator-(), operator-(), UE::Math::TPlane< T >::operator-=(), operator-=(), UE::Math::TPlane< T >::operator/(), operator/(), UE::Math::TPlane< T >::operator/=(), operator/=(), UE::Geometry::operator<<(), UE::Math::operator<<(), UE::Math::operator<<(), UE::Math::operator<<(), UE::Math::operator<<(), FPackedNormal::operator=(), FPackedNormal::operator=(), FPackedRGB10A2N::operator=(), FPackedRGB10A2N::operator=(), FPackedRGBA16N::operator=(), FPackedRGBA16N::operator=(), UE::Math::TPlane< T >::operator==(), operator==(), operator^(), UE::Math::TPlane< T >::operator|(), operator|(), UE::Geometry::TVolPresQuadricError< float >::OptimalPoint(), UE::Math::TBox< T >::Overlap(), Particle_SetColorFromVector(), UE::Math::TPlane< T >::PlaneDot(), PointsAreNear(), PointsAreSame(), FWedgePositionHelper::PointsEqual(), PointsEqual(), PointsEqual(), UE::Geometry::FMeshPropertyMapEvaluator::PositionToColor(), Projection(), AnimationMath::QuatFromScaledAngleAxis(), Reciprocal(), RotateAngleAxisRad(), TLumenCardOBB< float >::RotateCardToLocal(), UE::Geometry::TMeshSurfaceUVSampler< SampleType >::SampleUV(), UE::Geometry::TRemoveOccludedTriangles< OccluderTriangleMeshType >::Select(), UE::Math::TVector4< T >::SerializeFromVector3(), Set(), UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, FDynamicMesh3 >::SetAttributeFromBary(), UE::Geometry::TDynamicVertexSkinWeightsAttribute< FDynamicMesh3 >::SetBoneWeightsFromBary(), SetComponentForAxis(), UE::Geometry::TQuaternion< RealType >::SetFromRotationMatrix(), UE::Geometry::TQuaternion< RealType >::SetFromTo(), SGraphPinVector< NumericType >::SetNewValueHelper(), SGraphPinVectorSlider< NumericType >::SetNewValueHelper(), TVolumeLightingSample< 3 >::SetPackedSkyBentNormal(), UE::Geometry::FNegativeSpaceSampleSettings::SetResultTransform(), UE::Geometry::TDynamicVectorN< float, 3 >::SetVector3(), UE::Geometry::TDynamicPointSet3< float >::SetVertex(), UE::Geometry::TOrientedBox3< float >::SignedDistance(), Size(), Size2D(), SizeSquared(), SizeSquared2D(), FMath::SphereAABBIntersection(), UE::Geometry::SquaredLength(), UE::Geometry::TOrientedBox3< float >::SurfaceArea(), UE::Geometry::TIntrRay3AxisAlignedBox3< float >::TestIntersection(), RenderingSpatialHash::ToCellLoc(), ToCompactString(), ToCompactText(), ToDirectionAndLength(), ToDirectionAndLength(), UE::Geometry::TScaleGridIndexer3< float >::ToGrid(), UE::Geometry::TShiftGridIndexer3< float >::ToGrid(), DisplayClusterTypesConverter::ToHexString(), DisplayClusterTypesConverter::ToString(), ToString(), ToText(), FVectorFixed48::ToVector(), UE::Geometry::TMatrix3< float >::TransformByTranspose(), TLumenCardOBB< float >::TransformCardToLocal(), FToolDataVisualizer::TransformN(), UE::Geometry::TTransformSRT3< float >::TransformNormal(), UE::Geometry::VectorUtil::TransformNormal(), FAnimPhysPose::TransformPlane(), UE::AI::TriArea2D(), Triple(), UnitCartesianToSpherical(), UnitVectorToHemiOctahedron(), UnwindEuler(), FDisplayClusterWarpAABB::UpdateAABB(), USTRUCT(), UE::Geometry::TTriLinearGridInterpolant< GridType, RealType, bScalarCellSize >::Value(), FPrimitiveUniformShaderParametersBuilder::WorldBounds(), and UE::Geometry::FMeshMapEvaluator::WriteToBuffer().
XAxisVector
template<typename T> const TVector<T> UE::Math::TVector< T >::XAxisVector static
Unit X axis vector (1,0,0)
Definition at line 103 of file Vector.h.
Referenced by UE::Math::TQuat< T >::GetRotationAxis().
Y
template<typename T> T UE::Math::TVector< T >::Y
Vector's Y component.
Definition at line 65 of file Vector.h.
Referenced by FDFVector3::FDFVector3(), FDFVector4::FDFVector4(), FDynamicMeshVertex::FDynamicMeshVertex(), FWedgePositionHelper::FIndexAndZ::FIndexAndZ(), FMaterialParameterValue::FMaterialParameterValue(), UE::Math::TClipProjectionMatrix< T >::TClipProjectionMatrix(), UE::Math::TDualQuat< T >::TDualQuat(), UE::Math::TIntVector3< InIntType >::TIntVector3(), TLargeWorldRenderPosition< double >::TLargeWorldRenderPosition(), TLargeWorldRenderPosition< double >::TLargeWorldRenderPosition(), UE::Geometry::TMatrix3< float >::TMatrix3(), UE::Geometry::TQuadricError< float >::TQuadricError(), TVector(), TVector(), TVector(), TVector(), TVector(), TVector(), TVector(), AdjustParticleBaseSizeForUVFlipping(), AllComponentsEqual(), UE::Math::TTransform< T >::AnyHasNegativeScale(), UE::Geometry::FDynamicGraph3< double >::AppendVertex(), FKelvinletBrushOp::ApplyBrush(), FMoveBrushOp::ApplyStamp(), UE::Geometry::VectorUtil::Bitangent(), UE::Geometry::VectorUtil::BitangentSign(), BoundToBox(), BoundToCube(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::BoxDistanceSqr(), THierarchicalHashGrid2D< 2, 4, FSmartObjectHandle >::CalcCellLocation(), THierarchicalHashGrid2D< 2, 4, FSmartObjectHandle >::CalcQueryBounds(), UE::Geometry::TTriLinearGridInterpolant< GridType, RealType, bScalarCellSize >::Cell(), UE::Geometry::FMarchingCubes::cell_index(), UE::Geometry::TAxisAlignedBox3< float >::Clamp(), ClampVector(), ComponentMax(), ComponentMin(), UE::Geometry::TMeshWindingNumberGrid< TriangleMeshType >::Compute(), UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::Compute(), UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::Compute(), UE::Geometry::TAttrBasedQuadricError< float >::ComputeAttributes(), ComputeSquaredDistanceFromBoxToPoint(), FBuoyancyComponentSim::ComputeWaterForce(), UE::Math::TTransform< T >::ConstructTransformFromMatrixWithDesiredScale(), UE::Geometry::TAxisAlignedBox3< float >::Contain(), UE::Geometry::TAxisAlignedBox3< float >::Contains(), UE::Geometry::TOrientedBox3< float >::Contains(), ContainsNaN(), SGraphPinVector< NumericType >::ConvertDefaultValueStringToVector(), SGraphPinVectorSlider< NumericType >::ConvertDefaultValueStringToVector(), UE::Geometry::FMarchingCubes::corner_pos(), UE::Geometry::Cross(), FAnimationCompression_PerTrackUtils::DecompressScale(), FAnimationCompression_PerTrackUtils::DecompressTranslation(), UE::Geometry::Distance(), UE::Geometry::DistanceSquared(), UE::Geometry::TAxisAlignedBox3< float >::DistanceSquared(), UE::Geometry::TOrientedBox3< float >::DistanceSquared(), DistSquared(), DistSquaredXY(), UE::Geometry::TIntrRay3AxisAlignedBox3< float >::DoClipping(), UE::Geometry::Dot(), Dot3(), Dot3(), UE::Geometry::VectorUtil::EpsilonEqual(), UE::Math::TPlane< T >::Equals(), Equals(), UE::Geometry::TAttrBasedQuadricError< float >::Evaluate(), UE::Geometry::TQuadricError< float >::Evaluate(), FastTriWinding::EvaluateOrder2Approx(), UE::Geometry::ExactPredicates::Facing3(), FilteredVolumeLookup(), FilteredVolumeLookupReconverted(), UE::Geometry::FMarchingCubes::find_iso(), FindBestAxisVectors(), UE::Geometry::TSphericalFibonacci< RealType >::FindIndex(), UE::Geometry::TIntrRay3Triangle3< float >::FindIntersection(), UE::Geometry::TIntrRay3Triangle3< float >::FindWatertightIntersectionInternal(), UE::Math::TPlane< T >::Flip(), UE::Geometry::TShiftGridIndexer3< float >::FromGrid(), FVectorFixed48::FromVector(), FVectorIntervalFixed32NoW::FromVector(), UE::Geometry::GenerateBoxSegments(), GetAbs(), GetAbsMax(), GetAbsMin(), USplineMeshComponent::GetAxisValueRef(), USplineMeshComponent::GetAxisValueRef(), USplineMeshComponent::GetAxisValueRef(), UE::Geometry::FSegmentTree3::GetBoxDistanceSqr(), TSimpleCellGrid< CellType, InvalidCellValue >::GetCellCoordsUnsafe(), FSquare2DGridHelper::FGrid2D::GetCellIndex(), UE::Geometry::FOccupancyGrid3::GetCellIndexFromPoint(), GetClampedToMaxSize(), GetClampedToMaxSize2D(), GetClampedToSize2D(), UE::Math::TBox< T >::GetClosestPointTo(), GetComponentForAxis(), UE::Geometry::TIntrTriangle3Triangle3< float >::GetCoplanarIntersection(), GetHemiOrthoBasis(), UE::Geometry::TMeshTangents< float >::GetInterpolatedTriangleTangent(), UE::Geometry::TIndexedWeightMap< float >::GetInterpValue(), UE::Geometry::TIndexedWeightMap< float >::GetInterpValueUnsafe(), FLandscapeComponentDataInterface::GetLocalTangentVectors(), FLandscapeComponentDataInterfaceBase::GetLocalTangentVectors(), TBVTree< InElementType, InAllocator >::GetLongestAxis(), GetMax(), GetMin(), GetParticleBaseSize(), GetParticleSizeWithUVFlipInSign(), FNavLocalGridData::GetProjectedCellCenter(), GetSafeNormal(), GetSafeNormal2D(), UE::Geometry::TTransformSRT3< float >::GetSafeScaleReciprocal(), UE::Math::TTransform< T >::GetSafeScaleReciprocal(), GetSignVector(), FAtmosphereSetup::GetTransmittanceAtGroundLevel(), UE::Geometry::TMeshQueries< TriangleMeshType >::GetTriBounds(), GetUnsafeNormal(), GetUnsafeNormal2D(), UE::Geometry::TMeshQueries< TriangleMeshType >::GetVolumeAreaCenter(), UE::Geometry::GetXY(), UE::Geometry::GetYZ(), UE::Geometry::TTriLinearGridInterpolant< GridType, RealType, bScalarCellSize >::Gradient(), GridSnap(), HeadingAngle(), HemiOctahedronToUnitVector(), TSimpleCellGrid< CellType, InvalidCellValue >::Init(), InitFromCompactString(), InitFromString(), UE::Geometry::TCachingMeshSDF< TriangleMeshType >::Initialize(), UE::Geometry::FDynamicGraph3< double >::InsertVertex(), UE::Geometry::ExactPredicates::InSphere3(), INTEL_ORDER_VECTOR(), UE::Geometry::TIntrTriangle3Triangle3< float >::IntersectTriangleWithCoplanarSegment(), Inverse(), UE::Geometry::TQuaternion< RealType >::InverseMultiply(), UE::Geometry::VectorUtil::IsFinite(), UE::Math::TBox< double >::IsInside(), UE::Math::TBox< double >::IsInsideOrOn(), UE::Math::TBox< double >::IsInsideOrOnXY(), UE::Math::TBox< double >::IsInsideXY(), IsNearlyZero(), FAISystem::IsValidLocation(), IsZero(), UE::Geometry::Length(), UE::Geometry::FMeshShapeGenerator::LinearInterp(), FMath::LineBoxIntersection(), UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::make_level_set3_parallel_floodfill(), UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::make_level_set3_parallel_floodfill(), UE::Math::TQuat< T >::MakeFromRotationVector(), UE::Geometry::VectorUtil::MakePerpVector(), UE::Geometry::VectorUtil::MakePerpVectors(), TLargeWorldRenderScalar< double >::MakeQuantizedTile(), TLargeWorldRenderScalar< double >::MakeTile(), UE::Geometry::Max(), UE::Geometry::TOrientedBox3< float >::Merge(), UE::Geometry::Min(), UE::MovieScene::MultiChannelFromData(), UE::Geometry::TQuadricError< float >::MultiplyA(), UE::Geometry::TQuadricError< float >::MultiplySymmetricMatrix(), UE::LWC::NarrowWorldPositionChecked(), UE::LWC::NarrowWorldPositionChecked(), NearestVolumeLookup(), UE::Math::TPlane< T >::Normalize(), Normalize(), NormalsEqual(), NormalsEqual(), FPrimitiveUniformShaderParametersBuilder::ObjectBounds(), UE::Math::TPlane< T >::operator!=(), operator!=(), UE::Geometry::operator*(), UE::Geometry::operator*(), UE::Geometry::TMatrix3< float >::operator*(), UE::Geometry::TMatrix3< float >::operator*(), UE::Math::TPlane< T >::operator*(), UE::Math::TPlane< T >::operator*(), operator*(), UE::Math::TPlane< T >::operator*=(), UE::Math::TPlane< T >::operator*=(), operator*=(), UE::Math::TPlane< T >::operator+(), operator+(), UE::Math::TPlane< T >::operator+=(), operator+=(), UE::Math::TPlane< T >::operator-(), operator-(), operator-(), UE::Math::TPlane< T >::operator-=(), operator-=(), UE::Math::TPlane< T >::operator/(), operator/(), UE::Math::TPlane< T >::operator/=(), operator/=(), UE::Geometry::operator<<(), UE::Math::operator<<(), UE::Math::operator<<(), UE::Math::operator<<(), UE::Math::operator<<(), FPackedNormal::operator=(), FPackedNormal::operator=(), FPackedRGB10A2N::operator=(), FPackedRGB10A2N::operator=(), FPackedRGBA16N::operator=(), FPackedRGBA16N::operator=(), UE::Math::TPlane< T >::operator==(), operator==(), operator^(), UE::Math::TPlane< T >::operator|(), operator|(), UE::Geometry::TVolPresQuadricError< float >::OptimalPoint(), UE::Math::TBox< T >::Overlap(), Particle_SetColorFromVector(), UE::Math::TPlane< T >::PlaneDot(), PointsAreNear(), PointsAreSame(), FWedgePositionHelper::PointsEqual(), PointsEqual(), PointsEqual(), UE::Geometry::FMeshPropertyMapEvaluator::PositionToColor(), Projection(), AnimationMath::QuatFromScaledAngleAxis(), Reciprocal(), RotateAngleAxisRad(), TLumenCardOBB< float >::RotateCardToLocal(), UE::Geometry::TMeshSurfaceUVSampler< SampleType >::SampleUV(), UE::Geometry::TRemoveOccludedTriangles< OccluderTriangleMeshType >::Select(), UE::Math::TVector4< T >::SerializeFromVector3(), Set(), UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, FDynamicMesh3 >::SetAttributeFromBary(), UE::Geometry::TDynamicVertexSkinWeightsAttribute< FDynamicMesh3 >::SetBoneWeightsFromBary(), SetComponentForAxis(), UE::Geometry::TQuaternion< RealType >::SetFromRotationMatrix(), UE::Geometry::TQuaternion< RealType >::SetFromTo(), SGraphPinVector< NumericType >::SetNewValueHelper(), SGraphPinVectorSlider< NumericType >::SetNewValueHelper(), TVolumeLightingSample< 3 >::SetPackedSkyBentNormal(), UE::Geometry::TDynamicVectorN< float, 3 >::SetVector3(), UE::Geometry::TDynamicPointSet3< float >::SetVertex(), UE::Geometry::TOrientedBox3< float >::SignedDistance(), Size(), Size2D(), SizeSquared(), SizeSquared2D(), FMath::SphereAABBIntersection(), UE::Geometry::SquaredLength(), UE::Geometry::TOrientedBox3< float >::SurfaceArea(), UE::Geometry::TIntrRay3AxisAlignedBox3< float >::TestIntersection(), RenderingSpatialHash::ToCellLoc(), ToCompactString(), ToCompactText(), ToDirectionAndLength(), ToDirectionAndLength(), UE::Geometry::TScaleGridIndexer3< float >::ToGrid(), UE::Geometry::TShiftGridIndexer3< float >::ToGrid(), DisplayClusterTypesConverter::ToHexString(), DisplayClusterTypesConverter::ToString(), ToString(), ToText(), FVectorFixed48::ToVector(), UE::Geometry::TMatrix3< float >::TransformByTranspose(), TLumenCardOBB< float >::TransformCardToLocal(), FToolDataVisualizer::TransformN(), UE::Geometry::TTransformSRT3< float >::TransformNormal(), UE::Geometry::VectorUtil::TransformNormal(), FAnimPhysPose::TransformPlane(), UE::AI::TriArea2D(), Triple(), UnitCartesianToSpherical(), UnitVectorToHemiOctahedron(), UnwindEuler(), FDisplayClusterWarpAABB::UpdateAABB(), USTRUCT(), UE::Geometry::TTriLinearGridInterpolant< GridType, RealType, bScalarCellSize >::Value(), FPrimitiveUniformShaderParametersBuilder::WorldBounds(), and UE::Geometry::FMeshMapEvaluator::WriteToBuffer().
YAxisVector
template<typename T> const TVector<T> UE::Math::TVector< T >::YAxisVector static
Unit Y axis vector (0,1,0)
Definition at line 106 of file Vector.h.
Z
template<typename T> T UE::Math::TVector< T >::Z
Vector's Z component.
Definition at line 68 of file Vector.h.
Referenced by FDFVector3::FDFVector3(), FDFVector4::FDFVector4(), FWedgePositionHelper::FIndexAndZ::FIndexAndZ(), FMaterialParameterValue::FMaterialParameterValue(), UE::Math::TClipProjectionMatrix< T >::TClipProjectionMatrix(), UE::Math::TDualQuat< T >::TDualQuat(), UE::Math::TIntVector3< InIntType >::TIntVector3(), TLargeWorldRenderPosition< double >::TLargeWorldRenderPosition(), TLargeWorldRenderPosition< double >::TLargeWorldRenderPosition(), UE::Geometry::TMatrix3< float >::TMatrix3(), UE::Geometry::TQuadricError< float >::TQuadricError(), TVector(), TVector(), TVector(), TVector(), TVector(), TVector(), TVector(), AllComponentsEqual(), UE::Math::TTransform< T >::AnyHasNegativeScale(), UE::Geometry::FDynamicGraph3< double >::AppendVertex(), FKelvinletBrushOp::ApplyBrush(), FBuoyancyComponentSim::ApplyLinearDrag(), FMoveBrushOp::ApplyStamp(), UE::Geometry::VectorUtil::Bitangent(), UE::Geometry::VectorUtil::BitangentSign(), BoundToBox(), BoundToCube(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::BoxDistanceSqr(), UE::Geometry::TTriLinearGridInterpolant< GridType, RealType, bScalarCellSize >::Cell(), UE::Geometry::FMarchingCubes::cell_index(), UE::Geometry::TAxisAlignedBox3< float >::Clamp(), ClampVector(), ComponentMax(), ComponentMin(), UE::Geometry::TMeshWindingNumberGrid< TriangleMeshType >::Compute(), UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::Compute(), UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::Compute(), UE::Geometry::TAttrBasedQuadricError< float >::ComputeAttributes(), FBuoyancyComponentSim::ComputeBuoyancy(), ComputeSquaredDistanceFromBoxToPoint(), UE::Math::TTransform< T >::ConstructTransformFromMatrixWithDesiredScale(), UE::Geometry::TAxisAlignedBox3< float >::Contain(), UE::Geometry::TAxisAlignedBox3< float >::Contains(), UE::Geometry::TOrientedBox3< float >::Contains(), ContainsNaN(), SGraphPinVector< NumericType >::ConvertDefaultValueStringToVector(), SGraphPinVectorSlider< NumericType >::ConvertDefaultValueStringToVector(), UE::Geometry::FMarchingCubes::corner_pos(), UE::Geometry::Cross(), FAnimationCompression_PerTrackUtils::DecompressScale(), FAnimationCompression_PerTrackUtils::DecompressTranslation(), UE::Geometry::Distance(), UE::Geometry::DistanceSquared(), UE::Geometry::TAxisAlignedBox3< float >::DistanceSquared(), UE::Geometry::TOrientedBox3< float >::DistanceSquared(), DistSquared(), UE::Geometry::TIntrRay3AxisAlignedBox3< float >::DoClipping(), UE::Geometry::Dot(), Dot3(), Dot3(), UE::Geometry::VectorUtil::EpsilonEqual(), UE::Math::TPlane< T >::Equals(), Equals(), UE::Geometry::TAttrBasedQuadricError< float >::Evaluate(), UE::Geometry::TQuadricError< float >::Evaluate(), FastTriWinding::EvaluateOrder2Approx(), UE::Geometry::ExactPredicates::Facing3(), FilteredVolumeLookup(), FilteredVolumeLookupReconverted(), UE::Geometry::FMarchingCubes::find_iso(), FindBestAxisVectors(), UE::Geometry::TSphericalFibonacci< RealType >::FindIndex(), UE::Geometry::TIntrRay3Triangle3< float >::FindIntersection(), UE::Geometry::TIntrRay3Triangle3< float >::FindWatertightIntersectionInternal(), UE::Math::TPlane< T >::Flip(), UE::Geometry::TShiftGridIndexer3< float >::FromGrid(), FVectorFixed48::FromVector(), FVectorIntervalFixed32NoW::FromVector(), UE::Geometry::GenerateBoxSegments(), GetAbs(), GetAbsMax(), GetAbsMin(), USplineMeshComponent::GetAxisValueRef(), USplineMeshComponent::GetAxisValueRef(), USplineMeshComponent::GetAxisValueRef(), UE::Geometry::FSegmentTree3::GetBoxDistanceSqr(), UE::Geometry::FOccupancyGrid3::GetCellIndexFromPoint(), GetClampedToMaxSize(), GetClampedToMaxSize2D(), GetClampedToSize2D(), UE::Math::TBox< T >::GetClosestPointTo(), GetComponentForAxis(), UE::Geometry::TIntrTriangle3Triangle3< float >::GetCoplanarIntersection(), GetHemiOrthoBasis(), UE::Geometry::TMeshTangents< float >::GetInterpolatedTriangleTangent(), UE::Geometry::TIndexedWeightMap< float >::GetInterpValue(), UE::Geometry::TIndexedWeightMap< float >::GetInterpValueUnsafe(), FLandscapeComponentDataInterface::GetLocalTangentVectors(), FLandscapeComponentDataInterfaceBase::GetLocalTangentVectors(), TBVTree< InElementType, InAllocator >::GetLongestAxis(), GetMax(), GetMin(), GetParticleBaseSize(), GetSafeNormal(), GetSafeNormal2D(), UE::Geometry::TTransformSRT3< float >::GetSafeScaleReciprocal(), UE::Math::TTransform< T >::GetSafeScaleReciprocal(), GetSignVector(), FAtmosphereSetup::GetTransmittanceAtGroundLevel(), UE::Geometry::TMeshQueries< TriangleMeshType >::GetTriBounds(), GetUnsafeNormal(), UE::Geometry::TMeshQueries< TriangleMeshType >::GetVolumeAreaCenter(), UE::Geometry::GetXZ(), UE::Geometry::GetYZ(), UE::Geometry::TTriLinearGridInterpolant< GridType, RealType, bScalarCellSize >::Gradient(), GridSnap(), HeadingAngle(), HemiOctahedronToUnitVector(), TSimpleCellGrid< CellType, InvalidCellValue >::Init(), InitFromCompactString(), InitFromString(), UE::Geometry::TCachingMeshSDF< TriangleMeshType >::Initialize(), UE::Geometry::FDynamicGraph3< double >::InsertVertex(), UE::Geometry::ExactPredicates::InSphere3(), INTEL_ORDER_VECTOR(), UE::Geometry::TIntrTriangle3Triangle3< float >::IntersectTriangleWithCoplanarSegment(), Inverse(), UE::Geometry::TQuaternion< RealType >::InverseMultiply(), UE::Geometry::VectorUtil::IsFinite(), UE::Math::TBox< double >::IsInside(), UE::Math::TBox< double >::IsInsideOrOn(), IsNearlyZero(), FAISystem::IsValidLocation(), IsZero(), UE::Geometry::Length(), UE::Geometry::FMeshShapeGenerator::LinearInterp(), FMath::LineBoxIntersection(), UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::make_level_set3_parallel_floodfill(), UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::make_level_set3_parallel_floodfill(), UE::Math::TQuat< T >::MakeFromRotationVector(), UE::Math::TRotationMatrix< T >::MakeFromX(), UE::Math::TRotationMatrix< T >::MakeFromXY(), UE::Math::TRotationMatrix< T >::MakeFromXZ(), UE::Math::TRotationMatrix< T >::MakeFromY(), UE::Math::TRotationMatrix< T >::MakeFromYX(), UE::Math::TRotationMatrix< T >::MakeFromYZ(), UE::Math::TRotationMatrix< T >::MakeFromZ(), UE::Math::TRotationMatrix< T >::MakeFromZX(), UE::Math::TRotationMatrix< T >::MakeFromZY(), UE::Geometry::VectorUtil::MakePerpVector(), UE::Geometry::VectorUtil::MakePerpVectors(), TLargeWorldRenderScalar< double >::MakeQuantizedTile(), TLargeWorldRenderScalar< double >::MakeTile(), UE::Geometry::Max(), UE::Geometry::TOrientedBox3< float >::Merge(), UE::Geometry::Min(), UE::MovieScene::MultiChannelFromData(), UE::Geometry::TQuadricError< float >::MultiplyA(), UE::Geometry::TQuadricError< float >::MultiplySymmetricMatrix(), UE::LWC::NarrowWorldPositionChecked(), UE::LWC::NarrowWorldPositionChecked(), NearestVolumeLookup(), UE::Math::TPlane< T >::Normalize(), Normalize(), NormalsEqual(), NormalsEqual(), FPrimitiveUniformShaderParametersBuilder::ObjectBounds(), UE::Math::TPlane< T >::operator!=(), operator!=(), UE::Geometry::operator*(), UE::Geometry::operator*(), UE::Geometry::TMatrix3< float >::operator*(), UE::Geometry::TMatrix3< float >::operator*(), UE::Math::TPlane< T >::operator*(), UE::Math::TPlane< T >::operator*(), operator*(), UE::Math::TPlane< T >::operator*=(), UE::Math::TPlane< T >::operator*=(), operator*=(), UE::Math::TPlane< T >::operator+(), operator+(), UE::Math::TPlane< T >::operator+=(), operator+=(), UE::Math::TPlane< T >::operator-(), operator-(), operator-(), UE::Math::TPlane< T >::operator-=(), operator-=(), UE::Math::TPlane< T >::operator/(), operator/(), UE::Math::TPlane< T >::operator/=(), operator/=(), UE::Geometry::operator<<(), UE::Math::operator<<(), UE::Math::operator<<(), UE::Math::operator<<(), UE::Math::operator<<(), FPackedNormal::operator=(), FPackedNormal::operator=(), FPackedRGB10A2N::operator=(), FPackedRGB10A2N::operator=(), FPackedRGBA16N::operator=(), FPackedRGBA16N::operator=(), UE::Math::TPlane< T >::operator==(), operator==(), operator^(), UE::Math::TPlane< T >::operator|(), operator|(), UE::Geometry::TVolPresQuadricError< float >::OptimalPoint(), UE::Math::TBox< T >::Overlap(), Particle_SetColorFromVector(), UE::Math::TPlane< T >::PlaneDot(), PointsAreNear(), PointsAreSame(), FWedgePositionHelper::PointsEqual(), PointsEqual(), PointsEqual(), UE::Geometry::FMeshPropertyMapEvaluator::PositionToColor(), Projection(), AnimationMath::QuatFromScaledAngleAxis(), Reciprocal(), RotateAngleAxisRad(), TLumenCardOBB< float >::RotateCardToLocal(), UE::Geometry::TMeshSurfaceUVSampler< SampleType >::SampleUV(), UE::Geometry::TRemoveOccludedTriangles< OccluderTriangleMeshType >::Select(), UE::Math::TVector4< T >::SerializeFromVector3(), Set(), UE::Geometry::TDynamicVertexAttribute< AttribValueType, AttribDimension, FDynamicMesh3 >::SetAttributeFromBary(), UE::Geometry::TDynamicVertexSkinWeightsAttribute< FDynamicMesh3 >::SetBoneWeightsFromBary(), SetComponentForAxis(), UE::Geometry::TQuaternion< RealType >::SetFromRotationMatrix(), UE::Geometry::TQuaternion< RealType >::SetFromTo(), SGraphPinVector< NumericType >::SetNewValueHelper(), SGraphPinVectorSlider< NumericType >::SetNewValueHelper(), TVolumeLightingSample< 3 >::SetPackedSkyBentNormal(), UE::Geometry::TDynamicVectorN< float, 3 >::SetVector3(), UE::Geometry::TDynamicPointSet3< float >::SetVertex(), UE::Geometry::TOrientedBox3< float >::SignedDistance(), Size(), SizeSquared(), FMath::SphereAABBIntersection(), UE::Geometry::SquaredLength(), UE::Geometry::TOrientedBox3< float >::SurfaceArea(), UE::Geometry::TIntrRay3AxisAlignedBox3< float >::TestIntersection(), RenderingSpatialHash::ToCellLoc(), ToCompactString(), ToCompactText(), ToDirectionAndLength(), ToDirectionAndLength(), UE::Geometry::TScaleGridIndexer3< float >::ToGrid(), UE::Geometry::TShiftGridIndexer3< float >::ToGrid(), DisplayClusterTypesConverter::ToHexString(), DisplayClusterTypesConverter::ToString(), ToString(), ToText(), FVectorFixed48::ToVector(), UE::Geometry::TMatrix3< float >::TransformByTranspose(), TLumenCardOBB< float >::TransformCardToLocal(), FToolDataVisualizer::TransformN(), UE::Geometry::TTransformSRT3< float >::TransformNormal(), UE::Geometry::VectorUtil::TransformNormal(), FAnimPhysPose::TransformPlane(), Triple(), UnitCartesianToSpherical(), UnitVectorToHemiOctahedron(), UnwindEuler(), FDisplayClusterWarpAABB::UpdateAABB(), FBuoyancyComponentSim::UpdateBuoyancy(), UE::Geometry::TTriLinearGridInterpolant< GridType, RealType, bScalarCellSize >::Value(), FPrimitiveUniformShaderParametersBuilder::WorldBounds(), and UE::Geometry::FMeshMapEvaluator::WriteToBuffer().
ZAxisVector
template<typename T> const TVector<T> UE::Math::TVector< T >::ZAxisVector static
Unit Z axis vector (0,0,1)
Definition at line 109 of file Vector.h.
ZeroVector
template<typename T> const TVector<T> UE::Math::TVector< T >::ZeroVector static
A zero vector (0,0,0)
Definition at line 79 of file Vector.h.
Referenced by UE::Math::TTransform< double >::BlendFromIdentityAndAccumulate(), GetClampedToMaxSize(), GetClampedToSize(), GetClampedToSize2D(), UE::Math::TBox< double >::Init(), UE::Math::TRay< double >::Init(), FMath::IntersectPlanes2(), FMath::IntersectPlanes3(), UE::Math::TRotationMatrix< T >::Make(), UE::Math::TRotationMatrix< T >::MakeFromX(), UE::Math::TRotationMatrix< T >::MakeFromXY(), UE::Math::TRotationMatrix< T >::MakeFromXZ(), UE::Math::TRotationMatrix< T >::MakeFromY(), UE::Math::TRotationMatrix< T >::MakeFromYX(), UE::Math::TRotationMatrix< T >::MakeFromYZ(), UE::Math::TRotationMatrix< T >::MakeFromZ(), UE::Math::TRotationMatrix< T >::MakeFromZX(), UE::Math::TRotationMatrix< T >::MakeFromZY(), UE::Math::TTransform< T >::operator*(), UE::Math::TTransform< T >::operator*=(), UE::Math::TBoxSphereBounds< T, TExtent >::Builder::operator+=(), TLumenCardOBB< float >::Reset(), UE::Math::TTransform< double >::SetIdentity(), UE::Math::TTransform< double >::SetIdentityZeroScale(), ToDirectionAndLength(), and ToDirectionAndLength().
The documentation for this struct was generated from the following files:
Runtime/Core/Public/Math/MathFwd.h
Runtime/Core/Public/Math/Vector.h
Runtime/Core/Public/Math/Plane.h
Runtime/Core/Public/Math/Vector4.h