Unreal Engine 5.6 C++ API: UE::MovieScene::TPreAnimatedStateStorage< StorageTraits > Struct Template Reference
UE::MovieScene::TPreAnimatedStateStorage< StorageTraits > Struct Template Reference
Storage container for a specific type of pre-animated state as defined by the specified traits.
#include "MovieScenePreAnimatedStateStorage.h"
Data Structures
struct FCachedData
struct IRestoreMask
Interface used for restoring pre-animated state that allows an external system to control whether state should be restored or not.
Public Types
using KeyType = typename StorageTraits::KeyType
The key type to use as a key in the map that associates pre-animated state values to owners (ie, an object and property name)
using StorageType = typename StorageTraits::StorageType
The value type this storage should store (ie, the actual property type)
Public Member Functions
TPreAnimatedStateStorage ()
TPreAnimatedStateStorage (const TPreAnimatedStateStorage &)=delete
Pre-Animated storage is not copyable.
TPreAnimatedStateStorage (StorageTraits &&InTraits)
void AddReferencedObjects (FReferenceCollector &ReferenceCollector) override
Called by the owning extension to add reference collection tracking for pre-animated state.
void AssignPreAnimatedValue (FPreAnimatedStorageIndex StorageIndex, EPreAnimatedStorageRequirement StorageRequirement, StorageType &&InNewValue)
Assign the value for a specific storage index.
template<typename... ContributorTypes>
void BeginTrackingAndCachePreAnimatedValues (UMovieSceneEntitySystemLinker *Linker, TComponentTypeID< ContributorTypes >... InComponentTypes)
Look at any entity with the specified component types, and set up new associations with storage indices for those entities, whilst also caching pre-animated values at the same time.
template<typename TaskType, typename... ContributorTypes>
void BeginTrackingAndCachePreAnimatedValuesTask (UMovieSceneEntitySystemLinker *Linker, const TaskType &InParams, TComponentTypeID< ContributorTypes >... InComponentTypes)
Look at any entity with the specified component types, and set up new associations with storage indices for those entities, whilst also caching pre-animated values at the same time.
template<typename... ContributorTypes>
void BeginTrackingEntities (UMovieSceneEntitySystemLinker *Linker, TComponentTypeID< ContributorTypes >... InComponentTypes)
Look at any entity with the specified component types, and set up new associations with storage indices for those entities The provided component values are put together to make up the storage key WARNING: Does not cache actual pre-animated values.
template<typename TaskType, typename... ContributorTypes>
void BeginTrackingEntitiesTask (UMovieSceneEntitySystemLinker *Linker, const TaskType &InParams, TComponentTypeID< ContributorTypes >... InComponentTypes)
Look at any entity with the specified component types, and set up new associations with storage indices for those entities The provided component values are put together to make up the storage key WARNING: Does not cache actual pre-animated values.
template<typename... ContributorTypes>
void BeginTrackingEntity (FMovieSceneEntityID EntityID, const bool bWantsRestoreState, FRootInstanceHandle RootInstanceHandle, ContributorTypes... InComponents)
Set up a new associations with a storage index for the given entity The provided component values are put together to make up the storage key WARNING: Does not cache actual pre-animated values.
template<typename OnCacheValue>
void CachePreAnimatedValue (const KeyType &InKey, OnCacheValue &&CacheCallback, EPreAnimatedCaptureSourceTracking TrackingMode=EPreAnimatedCaptureSourceTracking::CacheIfTracked)
Save pre-animated state for the specified group and key using a callback.
template<typename... ContributorTypes>
void CachePreAnimatedValue (ContributorTypes... Values)
Save pre-animated state for the specified values, using CacheIfTracked tracking Requires that the traits class implements CachePreAnimatedValue(ContributorTypes...)
template<typename OnCacheValue>
void CachePreAnimatedValue (FPreAnimatedStorageGroupHandle GroupHandle, const KeyType &InKey, OnCacheValue &&CacheCallback, EPreAnimatedCaptureSourceTracking TrackingMode=EPreAnimatedCaptureSourceTracking::CacheIfTracked)
Save pre-animated state for the specified group and key using a callback.
template<typename... ContributorTypes>
void CachePreAnimatedValues (UMovieSceneEntitySystemLinker *Linker, TComponentTypeID< ContributorTypes >... InComponentTypes)
Cache pre-animated values for entities with the specified component types.
template<typename TaskType, typename... ContributorTypes>
void CachePreAnimatedValuesTask (UMovieSceneEntitySystemLinker *Linker, const TaskType &InParams, TComponentTypeID< ContributorTypes >... InComponentTypes)
Cache pre-animated values for entities with the specified component types.
template<typename... ContributorTypes>
void CacheTrackedPreAnimatedValue (EPreAnimatedCaptureSourceTracking TrackingMode, ContributorTypes... Values)
Save pre-animated state for the specified values Requires that the traits class implements CachePreAnimatedValue(ContributorTypes...)
EPreAnimatedStorageRequirement DiscardPreAnimatedStateStorage (FPreAnimatedStorageIndex StorageIndex, EPreAnimatedStorageRequirement SourceRequirement) override
Discard a specified index within this storage container.
template<typename... KeyArgs>
FPreAnimatedStateEntry FindEntry (KeyArgs &&... InKeyArgs)
Given a list of arguments suitable for building a storage key, builds that key, and then tries to find an existing pre-animated state entry for that key if it already exists.
FPreAnimatedStorageIndex FindStorageIndex (const KeyType &InKey) const
Attempt to find a storage index for the specified key.
void ForciblyPersistStorage (FPreAnimatedStorageIndex StorageIndex)
Cause a previously cached value to always outlive any actively animating sources.
const StorageType & GetCachedValue (FPreAnimatedStorageIndex StorageIndex) const
Get the cached value associated with a particular storage index.
const KeyType & GetKey (FPreAnimatedStorageIndex StorageIndex) const
Get the key associated with a particular storage index.
FPreAnimatedStorageIndex GetOrCreateStorageIndex (const KeyType &InKey)
Attempt to find a storage index for the specified key, creating a new one if it doesn't exist.
FPreAnimatedStorageID GetStorageType () const override
Retrieve the ID that uniquely identifies this storage container.
bool HasEverAnimated (FPreAnimatedStorageIndex StorageIndex) const
Check whether we have ever animated the specified storage index.
void Initialize (FPreAnimatedStorageID InStorageID, FPreAnimatedStateExtension *InParentExtension) override
Called when this storage is created inside the pre-animated state extension on a UMovieSceneEntitySystemLinker.
bool IsCapturingGlobalState () const
bool IsStorageInitialized (FPreAnimatedStorageIndex StorageIndex) const
Check whether a piece of cached storage has been initialized yet.
bool IsStorageRequirementSatisfied (FPreAnimatedStorageIndex StorageIndex, EPreAnimatedStorageRequirement StorageRequirement) const
Check whether the storage for a given index and requirement has already been initialized.
template<typename... KeyArgs>
FPreAnimatedStateEntry MakeEntry (KeyArgs &&... InKeyArgs)
Creates a new pre-animated state entry from a list of arguments suitable for building the storage key.
void OnObjectReplaced (FPreAnimatedStorageIndex StorageIndex, const FObjectKey &OldObject, const FObjectKey &NewObject) override
TPreAnimatedStateStorage & operator= (const TPreAnimatedStateStorage &)=delete
void ReplaceKey (FPreAnimatedStorageIndex StorageIndex, const KeyType &NewKey)
Replace the key associated with a particular storage index.
EPreAnimatedStorageRequirement RestorePreAnimatedStateStorage (FPreAnimatedStorageIndex StorageIndex, EPreAnimatedStorageRequirement SourceRequirement, EPreAnimatedStorageRequirement TargetRequirement, const FRestoreStateParams &Params) override
Restore a specified index within this storage container.
void SetRestoreMask (const IRestoreMask *InRestoreMask)
Called prior to restoring pre-animated state to control whether this storage should restore state or not.
Public Member Functions inherited from UE::MovieScene::IPreAnimatedStorage
virtual ~IPreAnimatedStorage ()
virtual IPreAnimatedObjectEntityStorage * AsObjectStorage ()
virtual IPreAnimatedObjectPropertyStorage * AsPropertyStorage ()
Public Member Functions inherited from TSharedFromThis< IPreAnimatedStorage >
TSharedRef< IPreAnimatedStorage, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< IPreAnimatedStorage, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Data Fields
StorageTraits Traits
Traits instance - normally not required but some traits require state.
Protected Member Functions
template<typename... KeyArgs>
bool ShouldTrackCaptureSource (EPreAnimatedCaptureSourceTracking TrackingMode, KeyArgs &&... InKeyArgs)
void TrackCaptureSource (const FPreAnimatedStateEntry &Entry, EPreAnimatedCaptureSourceTracking TrackingMode)
Begins tracking the current entry with the currently set tracking source, if necessary/desirable.
Protected Member Functions inherited from TSharedFromThis< IPreAnimatedStorage >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Protected Attributes
TMap< KeyType, FPreAnimatedStorageIndex > KeyToStorageIndex
Map that associates a storage index with a key.
FPreAnimatedStateExtension * ParentExtension = nullptr
Pointer to our parent extension.
TSparseArray< FCachedData > PreAnimatedStorage
Sparse array of cached data that represents persistent, or both persistent and transient storage (but never exclusively transient storage).
const IRestoreMask * RestoreMask = nullptr
Temporary restoration mask.
FPreAnimatedStorageID StorageID
Our storage ID.
TSortedMap< FPreAnimatedStorageIndex, StorageType > TransientPreAnimatedStorage
Storage that holds values that need to be kept transiently (for evaluation).
Additional Inherited Members
Static Protected Member Functions inherited from TSharedFromThis< IPreAnimatedStorage >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
template<typename StorageTraits>
struct UE::MovieScene::TPreAnimatedStateStorage< StorageTraits >
Storage container for a specific type of pre-animated state as defined by the specified traits.
Reference collection for KeyType and StorageType is automatically provided by way of an optional AddReferencedObjectForComponent override
Traits must include a type definition or using alias for its KeyType and StorageType, defining the type of key to use for associating the pre-animated value and the storage value type respectively.
Additionally, traits must define a RestorePreAnimatedValue function that will be used by the storage container to restore data back to its previous value.
An example trait that maps an object and a name identifier to a string would look like this: struct FExampleTraits { using KeyType = TTuple<FObjectKey, FName>; using StorageType = FString;
static void RestorePreAnimatedValue(const KeyType& InKey, const FString& PreviousString, const FRestoreStateParams& Params) { if (UMyObjectType* Object = Cast<UMyObjectType>(InKey.Get<0>().ResolveObjectPtr())) { Object->SetStringValue(InKey.Get<1>(), PreviousString); } } }
Furthermore, if the CachePreAnimatedValuesTask is used, traits must implement a CachePreAnimatedValue function that receives the contributor component types, and returns the cached value:
static FString CachePreAnimatedValue(UObject* InObject, const FName& StringName) { UMyObjectType* Object = CastChecked<UMyObjectType>(InObject); return Object->GetStringValue(StringName); }
Traits may be stateful if desired. Stateful traits must be provided to the constructor in order to be valid.
Definition at line 142 of file MovieScenePreAnimatedStateStorage.h.
Member Typedef Documentation
KeyType
template<typename StorageTraits> using UE::MovieScene::TPreAnimatedStateStorage< StorageTraits >::KeyType = typename StorageTraits::KeyType
The key type to use as a key in the map that associates pre-animated state values to owners (ie, an object and property name)
Definition at line 145 of file MovieScenePreAnimatedStateStorage.h.
StorageType
template<typename StorageTraits> using UE::MovieScene::TPreAnimatedStateStorage< StorageTraits >::StorageType = typename StorageTraits::StorageType
The value type this storage should store (ie, the actual property type)
Definition at line 147 of file MovieScenePreAnimatedStateStorage.h.
Constructor & Destructor Documentation
TPreAnimatedStateStorage() [1/3]
template<typename StorageTraits> UE::MovieScene::TPreAnimatedStateStorage< StorageTraits >::TPreAnimatedStateStorage () inline
Definition at line 157 of file MovieScenePreAnimatedStateStorage.h.
TPreAnimatedStateStorage() [2/3]
template<typename StorageTraits> UE::MovieScene::TPreAnimatedStateStorage< StorageTraits >::TPreAnimatedStateStorage (StorageTraits && InTraits) inline
Definition at line 160 of file MovieScenePreAnimatedStateStorage.h.
TPreAnimatedStateStorage() [3/3]
template<typename StorageTraits> UE::MovieScene::TPreAnimatedStateStorage< StorageTraits >::TPreAnimatedStateStorage (const TPreAnimatedStateStorage< StorageTraits > &) delete
Pre-Animated storage is not copyable.
Member Function Documentation
AddReferencedObjects()
template<typename StorageTraits> void UE::MovieScene::TPreAnimatedStateStorage< StorageTraits >::AddReferencedObjects (FReferenceCollector & ReferenceCollector) inline override virtual
Called by the owning extension to add reference collection tracking for pre-animated state.
Reimplemented from UE::MovieScene::IPreAnimatedStorage.
Definition at line 346 of file MovieScenePreAnimatedStateStorage.h.
AssignPreAnimatedValue()
template<typename StorageTraits> void UE::MovieScene::TPreAnimatedStateStorage< StorageTraits >::AssignPreAnimatedValue (FPreAnimatedStorageIndex StorageIndex, EPreAnimatedStorageRequirement StorageRequirement, StorageType && InNewValue) inline
Assign the value for a specific storage index.
It is an error to re-assign an already cached value.
Parameters
StorageIndex The storage index to assign a value for
StorageRequirement Whether to assign the value to this index's persistent, or transient value. Transient should be used when this value is directly associated with a track evaluating.
InNewValue The value to assign
Definition at line 403 of file MovieScenePreAnimatedStateStorage.h.
Referenced by UE::MovieScene::TPreAnimatedStateStorage< TPreAnimatedMaterialTraits< AccessorType, RequiredComponents... > >::BeginTrackingAndCachePreAnimatedValuesTask(), UE::MovieScene::TPreAnimatedStateStorage< TPreAnimatedMaterialTraits< AccessorType, RequiredComponents... > >::CachePreAnimatedValue(), UE::MovieScene::TPreAnimatedStateStorage< TPreAnimatedMaterialTraits< AccessorType, RequiredComponents... > >::CachePreAnimatedValuesTask(), and UE::MovieScene::TPreAnimatedStateStorage< TPreAnimatedMaterialTraits< AccessorType, RequiredComponents... > >::CacheTrackedPreAnimatedValue().
BeginTrackingAndCachePreAnimatedValues()
template<typename StorageTraits> template<typename... ContributorTypes> void UE::MovieScene::TPreAnimatedStateStorage< StorageTraits >::BeginTrackingAndCachePreAnimatedValues (UMovieSceneEntitySystemLinker * Linker, TComponentTypeID< ContributorTypes >... InComponentTypes) inline
Look at any entity with the specified component types, and set up new associations with storage indices for those entities, whilst also caching pre-animated values at the same time.
Definition at line 760 of file MovieScenePreAnimatedStateStorage.h.
BeginTrackingAndCachePreAnimatedValuesTask()
template<typename StorageTraits> template<typename TaskType, typename... ContributorTypes> void UE::MovieScene::TPreAnimatedStateStorage< StorageTraits >::BeginTrackingAndCachePreAnimatedValuesTask (UMovieSceneEntitySystemLinker * Linker, const TaskType & InParams, TComponentTypeID< ContributorTypes >... InComponentTypes) inline
Look at any entity with the specified component types, and set up new associations with storage indices for those entities, whilst also caching pre-animated values at the same time.
Definition at line 769 of file MovieScenePreAnimatedStateStorage.h.
Referenced by UE::MovieScene::TPreAnimatedStateStorage< TPreAnimatedMaterialTraits< AccessorType, RequiredComponents... > >::BeginTrackingAndCachePreAnimatedValues().
BeginTrackingEntities()
template<typename StorageTraits> template<typename... ContributorTypes> void UE::MovieScene::TPreAnimatedStateStorage< StorageTraits >::BeginTrackingEntities (UMovieSceneEntitySystemLinker * Linker, TComponentTypeID< ContributorTypes >... InComponentTypes) inline
Look at any entity with the specified component types, and set up new associations with storage indices for those entities The provided component values are put together to make up the storage key WARNING: Does not cache actual pre-animated values.
Definition at line 578 of file MovieScenePreAnimatedStateStorage.h.
BeginTrackingEntitiesTask()
template<typename StorageTraits> template<typename TaskType, typename... ContributorTypes> void UE::MovieScene::TPreAnimatedStateStorage< StorageTraits >::BeginTrackingEntitiesTask (UMovieSceneEntitySystemLinker * Linker, const TaskType & InParams, TComponentTypeID< ContributorTypes >... InComponentTypes) inline
Look at any entity with the specified component types, and set up new associations with storage indices for those entities The provided component values are put together to make up the storage key WARNING: Does not cache actual pre-animated values.
Definition at line 589 of file MovieScenePreAnimatedStateStorage.h.
Referenced by UE::MovieScene::TPreAnimatedStateStorage< TPreAnimatedMaterialTraits< AccessorType, RequiredComponents... > >::BeginTrackingEntities().
BeginTrackingEntity()
template<typename StorageTraits> template<typename... ContributorTypes> void UE::MovieScene::TPreAnimatedStateStorage< StorageTraits >::BeginTrackingEntity (FMovieSceneEntityID EntityID, const bool bWantsRestoreState, FRootInstanceHandle RootInstanceHandle, ContributorTypes... InComponents) inline
Set up a new associations with a storage index for the given entity The provided component values are put together to make up the storage key WARNING: Does not cache actual pre-animated values.
Definition at line 630 of file MovieScenePreAnimatedStateStorage.h.
CachePreAnimatedValue() [1/3]
template<typename StorageTraits> template<typename OnCacheValue> void UE::MovieScene::TPreAnimatedStateStorage< StorageTraits >::CachePreAnimatedValue (const KeyType & InKey, OnCacheValue && CacheCallback, EPreAnimatedCaptureSourceTracking TrackingMode = EPreAnimatedCaptureSourceTracking::CacheIfTracked) inline
Save pre-animated state for the specified group and key using a callback.
Callback will only be invoked if state has not already been saved.
Definition at line 724 of file MovieScenePreAnimatedStateStorage.h.
CachePreAnimatedValue() [2/3]
template<typename StorageTraits> template<typename... ContributorTypes> void UE::MovieScene::TPreAnimatedStateStorage< StorageTraits >::CachePreAnimatedValue (ContributorTypes... Values) inline
Save pre-animated state for the specified values, using CacheIfTracked tracking Requires that the traits class implements CachePreAnimatedValue(ContributorTypes...)
Definition at line 692 of file MovieScenePreAnimatedStateStorage.h.
Referenced by UE::MovieScene::TPreAnimatedStateStorage< TPreAnimatedMaterialTraits< AccessorType, RequiredComponents... > >::CachePreAnimatedValue().
CachePreAnimatedValue() [3/3]
template<typename StorageTraits> template<typename OnCacheValue> void UE::MovieScene::TPreAnimatedStateStorage< StorageTraits >::CachePreAnimatedValue (FPreAnimatedStorageGroupHandle GroupHandle, const KeyType & InKey, OnCacheValue && CacheCallback, EPreAnimatedCaptureSourceTracking TrackingMode = EPreAnimatedCaptureSourceTracking::CacheIfTracked) inline
Save pre-animated state for the specified group and key using a callback.
Callback will only be invoked if state has not already been saved.
Definition at line 735 of file MovieScenePreAnimatedStateStorage.h.
CachePreAnimatedValues()
template<typename StorageTraits> template<typename... ContributorTypes> void UE::MovieScene::TPreAnimatedStateStorage< StorageTraits >::CachePreAnimatedValues (UMovieSceneEntitySystemLinker * Linker, TComponentTypeID< ContributorTypes >... InComponentTypes) inline
Cache pre-animated values for entities with the specified component types.
Definition at line 648 of file MovieScenePreAnimatedStateStorage.h.
CachePreAnimatedValuesTask()
template<typename StorageTraits> template<typename TaskType, typename... ContributorTypes> void UE::MovieScene::TPreAnimatedStateStorage< StorageTraits >::CachePreAnimatedValuesTask (UMovieSceneEntitySystemLinker * Linker, const TaskType & InParams, TComponentTypeID< ContributorTypes >... InComponentTypes) inline
Cache pre-animated values for entities with the specified component types.
Definition at line 657 of file MovieScenePreAnimatedStateStorage.h.
Referenced by UE::MovieScene::TPreAnimatedStateStorage< TPreAnimatedMaterialTraits< AccessorType, RequiredComponents... > >::CachePreAnimatedValues().
CacheTrackedPreAnimatedValue()
template<typename StorageTraits> template<typename... ContributorTypes> void UE::MovieScene::TPreAnimatedStateStorage< StorageTraits >::CacheTrackedPreAnimatedValue (EPreAnimatedCaptureSourceTracking TrackingMode, ContributorTypes... Values) inline
Save pre-animated state for the specified values Requires that the traits class implements CachePreAnimatedValue(ContributorTypes...)
Definition at line 702 of file MovieScenePreAnimatedStateStorage.h.
Referenced by UE::MovieScene::TPreAnimatedStateStorage< TPreAnimatedMaterialTraits< AccessorType, RequiredComponents... > >::CachePreAnimatedValue().
DiscardPreAnimatedStateStorage()
template<typename StorageTraits> EPreAnimatedStorageRequirement UE::MovieScene::TPreAnimatedStateStorage< StorageTraits >::DiscardPreAnimatedStateStorage (FPreAnimatedStorageIndex StorageIndex, EPreAnimatedStorageRequirement SourceRequirement) inline override virtual
Discard a specified index within this storage container.
Parameters
StorageIndex The unique index for the stored state - either an index within PreAnimatedStorage or TransientPreAnimatedStorage.
SourceRequirement The storage requirement to discard - Persistent will discard all cached state for the object, Transient may leave persistent storage around, if possible.
Returns
The resulting storage requirement for the supplied index
Implements UE::MovieScene::IPreAnimatedStorage.
Definition at line 303 of file MovieScenePreAnimatedStateStorage.h.
FindEntry()
template<typename StorageTraits> template<typename... KeyArgs> FPreAnimatedStateEntry UE::MovieScene::TPreAnimatedStateStorage< StorageTraits >::FindEntry (KeyArgs &&... InKeyArgs) inline
Given a list of arguments suitable for building a storage key, builds that key, and then tries to find an existing pre-animated state entry for that key if it already exists.
If it doesn't exist, it returns an empty FPreAnimatedStateEntry.
Note that the arguments are also used for find the group handle, if the storage traits required grouping.
Definition at line 463 of file MovieScenePreAnimatedStateStorage.h.
Referenced by UE::MovieScene::TPreAnimatedStateStorage< TPreAnimatedMaterialTraits< AccessorType, RequiredComponents... > >::ShouldTrackCaptureSource().
FindStorageIndex()
template<typename StorageTraits> FPreAnimatedStorageIndex UE::MovieScene::TPreAnimatedStateStorage< StorageTraits >::FindStorageIndex (const KeyType & InKey) const inline
Attempt to find a storage index for the specified key.
Definition at line 391 of file MovieScenePreAnimatedStateStorage.h.
Referenced by UE::MovieScene::TPreAnimatedStateStorage< TPreAnimatedMaterialTraits< AccessorType, RequiredComponents... > >::FindEntry().
ForciblyPersistStorage()
template<typename StorageTraits> void UE::MovieScene::TPreAnimatedStateStorage< StorageTraits >::ForciblyPersistStorage (FPreAnimatedStorageIndex StorageIndex) inline
Cause a previously cached value to always outlive any actively animating sources.
This is called when a Restore State track overlaps a Keep State track. The Restore State track will initially save state using the Transient requirement, but the Keep State track may need to keep this cached state alive if it is capturing global state. As such, we take the previously cached state and make it persistent.
Definition at line 510 of file MovieScenePreAnimatedStateStorage.h.
GetCachedValue()
template<typename StorageTraits> const StorageType & UE::MovieScene::TPreAnimatedStateStorage< StorageTraits >::GetCachedValue (FPreAnimatedStorageIndex StorageIndex) const inline
Get the cached value associated with a particular storage index.
Definition at line 557 of file MovieScenePreAnimatedStateStorage.h.
GetKey()
template<typename StorageTraits> const KeyType & UE::MovieScene::TPreAnimatedStateStorage< StorageTraits >::GetKey (FPreAnimatedStorageIndex StorageIndex) const inline
Get the key associated with a particular storage index.
Definition at line 537 of file MovieScenePreAnimatedStateStorage.h.
Referenced by UE::MovieScene::TPreAnimatedStateStorage< TPreAnimatedMaterialTraits< AccessorType, RequiredComponents... > >::OnObjectReplaced().
GetOrCreateStorageIndex()
template<typename StorageTraits> FPreAnimatedStorageIndex UE::MovieScene::TPreAnimatedStateStorage< StorageTraits >::GetOrCreateStorageIndex (const KeyType & InKey) inline
Attempt to find a storage index for the specified key, creating a new one if it doesn't exist.
Definition at line 376 of file MovieScenePreAnimatedStateStorage.h.
Referenced by UE::MovieScene::TPreAnimatedStateStorage< TPreAnimatedMaterialTraits< AccessorType, RequiredComponents... > >::CachePreAnimatedValue(), and UE::MovieScene::TPreAnimatedStateStorage< TPreAnimatedMaterialTraits< AccessorType, RequiredComponents... > >::MakeEntry().
GetStorageType()
template<typename StorageTraits> FPreAnimatedStorageID UE::MovieScene::TPreAnimatedStateStorage< StorageTraits >::GetStorageType () const inline override virtual
Retrieve the ID that uniquely identifies this storage container.
Implements UE::MovieScene::IPreAnimatedStorage.
Definition at line 183 of file MovieScenePreAnimatedStateStorage.h.
HasEverAnimated()
template<typename StorageTraits> bool UE::MovieScene::TPreAnimatedStateStorage< StorageTraits >::HasEverAnimated (FPreAnimatedStorageIndex StorageIndex) const inline
Check whether we have ever animated the specified storage index.
Definition at line 529 of file MovieScenePreAnimatedStateStorage.h.
Initialize()
template<typename StorageTraits> void UE::MovieScene::TPreAnimatedStateStorage< StorageTraits >::Initialize (FPreAnimatedStorageID InStorageID, FPreAnimatedStateExtension * InParentExtension) inline override virtual
Called when this storage is created inside the pre-animated state extension on a UMovieSceneEntitySystemLinker.
Reimplemented from UE::MovieScene::IPreAnimatedStorage.
Definition at line 171 of file MovieScenePreAnimatedStateStorage.h.
IsCapturingGlobalState()
template<typename StorageTraits> bool UE::MovieScene::TPreAnimatedStateStorage< StorageTraits >::IsCapturingGlobalState () const inline
Definition at line 499 of file MovieScenePreAnimatedStateStorage.h.
IsStorageInitialized()
template<typename StorageTraits> bool UE::MovieScene::TPreAnimatedStateStorage< StorageTraits >::IsStorageInitialized (FPreAnimatedStorageIndex StorageIndex) const inline
Check whether a piece of cached storage has been initialized yet.
This will be false where multiple entities contribute to an object's state but a different entity actually assigns the value (eg multiple blended entiies). Saving state for these requires 2 passes: firstly we gather all the entities that contribute to the state (which may not be able to even know how to cache the state), then we capture the actual value.
Definition at line 521 of file MovieScenePreAnimatedStateStorage.h.
IsStorageRequirementSatisfied()
template<typename StorageTraits> bool UE::MovieScene::TPreAnimatedStateStorage< StorageTraits >::IsStorageRequirementSatisfied (FPreAnimatedStorageIndex StorageIndex, EPreAnimatedStorageRequirement StorageRequirement) const inline
Check whether the storage for a given index and requirement has already been initialized.
Definition at line 436 of file MovieScenePreAnimatedStateStorage.h.
Referenced by UE::MovieScene::TPreAnimatedStateStorage< TPreAnimatedMaterialTraits< AccessorType, RequiredComponents... > >::BeginTrackingAndCachePreAnimatedValuesTask(), UE::MovieScene::TPreAnimatedStateStorage< TPreAnimatedMaterialTraits< AccessorType, RequiredComponents... > >::CachePreAnimatedValue(), UE::MovieScene::TPreAnimatedStateStorage< TPreAnimatedMaterialTraits< AccessorType, RequiredComponents... > >::CachePreAnimatedValuesTask(), and UE::MovieScene::TPreAnimatedStateStorage< TPreAnimatedMaterialTraits< AccessorType, RequiredComponents... > >::CacheTrackedPreAnimatedValue().
MakeEntry()
template<typename StorageTraits> template<typename... KeyArgs> FPreAnimatedStateEntry UE::MovieScene::TPreAnimatedStateStorage< StorageTraits >::MakeEntry (KeyArgs &&... InKeyArgs) inline
Creates a new pre-animated state entry from a list of arguments suitable for building the storage key.
Note that the arguments are also used for getting the group handle, if the storage traits required grouping.
Definition at line 484 of file MovieScenePreAnimatedStateStorage.h.
Referenced by UE::MovieScene::TPreAnimatedStateStorage< TPreAnimatedMaterialTraits< AccessorType, RequiredComponents... > >::BeginTrackingAndCachePreAnimatedValuesTask(), UE::MovieScene::TPreAnimatedStateStorage< TPreAnimatedMaterialTraits< AccessorType, RequiredComponents... > >::BeginTrackingEntitiesTask(), UE::MovieScene::TPreAnimatedStateStorage< TPreAnimatedMaterialTraits< AccessorType, RequiredComponents... > >::BeginTrackingEntity(), UE::MovieScene::TPreAnimatedStateStorage< TPreAnimatedMaterialTraits< AccessorType, RequiredComponents... > >::CachePreAnimatedValuesTask(), and UE::MovieScene::TPreAnimatedStateStorage< TPreAnimatedMaterialTraits< AccessorType, RequiredComponents... > >::CacheTrackedPreAnimatedValue().
OnObjectReplaced()
template<typename StorageTraits> void UE::MovieScene::TPreAnimatedStateStorage< StorageTraits >::OnObjectReplaced (FPreAnimatedStorageIndex StorageIndex, const FObjectKey & OldObject, const FObjectKey & NewObject) inline override virtual
Reimplemented from UE::MovieScene::IPreAnimatedStorage.
Definition at line 809 of file MovieScenePreAnimatedStateStorage.h.
operator=()
template<typename StorageTraits> TPreAnimatedStateStorage & UE::MovieScene::TPreAnimatedStateStorage< StorageTraits >::operator= (const TPreAnimatedStateStorage< StorageTraits > &) delete
ReplaceKey()
template<typename StorageTraits> void UE::MovieScene::TPreAnimatedStateStorage< StorageTraits >::ReplaceKey (FPreAnimatedStorageIndex StorageIndex, const KeyType & NewKey) inline
Replace the key associated with a particular storage index.
Definition at line 545 of file MovieScenePreAnimatedStateStorage.h.
Referenced by UE::MovieScene::TPreAnimatedStateStorage< TPreAnimatedMaterialTraits< AccessorType, RequiredComponents... > >::OnObjectReplaced().
RestorePreAnimatedStateStorage()
template<typename StorageTraits> EPreAnimatedStorageRequirement UE::MovieScene::TPreAnimatedStateStorage< StorageTraits >::RestorePreAnimatedStateStorage (FPreAnimatedStorageIndex StorageIndex, EPreAnimatedStorageRequirement SourceRequirement, EPreAnimatedStorageRequirement TargetRequirement, const FRestoreStateParams & Params) inline override virtual
Restore a specified index within this storage container.
Usually called when all the things contributing to this storage index have finished evaluating.
Parameters
StorageIndex The unique index for the stored state - either an index within PreAnimatedStorage or TransientPreAnimatedStorage.
SourceRequirement The source requirement that is requesting to restore state: Persistent - indicates that the storage should be completely restored as a result of a sequence finishing or explicitly restoring state Transient - indicates that all 'Restore State' tracks have finished evaluating for this index, but persistent state may still be cached
TargetRequirement The target requirement for storage - None implies that no state needs to remain cached for this index, Persistent implies that keep state entities have finished, but the state still needs to be cached.
Params Additional restore parameters defining the instigator context
Returns
The resulting storage requirement for the supplied index
Implements UE::MovieScene::IPreAnimatedStorage.
Definition at line 201 of file MovieScenePreAnimatedStateStorage.h.
SetRestoreMask()
template<typename StorageTraits> void UE::MovieScene::TPreAnimatedStateStorage< StorageTraits >::SetRestoreMask (const IRestoreMask * InRestoreMask) inline
Called prior to restoring pre-animated state to control whether this storage should restore state or not.
Definition at line 338 of file MovieScenePreAnimatedStateStorage.h.
ShouldTrackCaptureSource()
template<typename StorageTraits> template<typename... KeyArgs> bool UE::MovieScene::TPreAnimatedStateStorage< StorageTraits >::ShouldTrackCaptureSource (EPreAnimatedCaptureSourceTracking TrackingMode, KeyArgs &&... InKeyArgs) inline protected
Definition at line 822 of file MovieScenePreAnimatedStateStorage.h.
Referenced by UE::MovieScene::TPreAnimatedStateStorage< TPreAnimatedMaterialTraits< AccessorType, RequiredComponents... > >::CachePreAnimatedValue(), UE::MovieScene::TPreAnimatedStateStorage< TPreAnimatedMaterialTraits< AccessorType, RequiredComponents... > >::CachePreAnimatedValuesTask(), and UE::MovieScene::TPreAnimatedStateStorage< TPreAnimatedMaterialTraits< AccessorType, RequiredComponents... > >::CacheTrackedPreAnimatedValue().
TrackCaptureSource()
template<typename StorageTraits> void UE::MovieScene::TPreAnimatedStateStorage< StorageTraits >::TrackCaptureSource (const FPreAnimatedStateEntry & Entry, EPreAnimatedCaptureSourceTracking TrackingMode) inline protected
Begins tracking the current entry with the currently set tracking source, if necessary/desirable.
If the entry is valid, we assume the metadata must already exist.
Definition at line 861 of file MovieScenePreAnimatedStateStorage.h.
Referenced by UE::MovieScene::TPreAnimatedStateStorage< TPreAnimatedMaterialTraits< AccessorType, RequiredComponents... > >::CachePreAnimatedValue(), UE::MovieScene::TPreAnimatedStateStorage< TPreAnimatedMaterialTraits< AccessorType, RequiredComponents... > >::CachePreAnimatedValuesTask(), and UE::MovieScene::TPreAnimatedStateStorage< TPreAnimatedMaterialTraits< AccessorType, RequiredComponents... > >::CacheTrackedPreAnimatedValue().
Field Documentation
KeyToStorageIndex
template<typename StorageTraits> TMap<KeyType, FPreAnimatedStorageIndex> UE::MovieScene::TPreAnimatedStateStorage< StorageTraits >::KeyToStorageIndex protected
Map that associates a storage index with a key.
This indirection allows common code to deal with indices without knowing concrete templated types.
Definition at line 920 of file MovieScenePreAnimatedStateStorage.h.
ParentExtension
template<typename StorageTraits> FPreAnimatedStateExtension* UE::MovieScene::TPreAnimatedStateStorage< StorageTraits >::ParentExtension = nullptr protected
Pointer to our parent extension.
Definition at line 936 of file MovieScenePreAnimatedStateStorage.h.
PreAnimatedStorage
template<typename StorageTraits> TSparseArray<FCachedData> UE::MovieScene::TPreAnimatedStateStorage< StorageTraits >::PreAnimatedStorage protected
Sparse array of cached data that represents persistent, or both persistent and transient storage (but never exclusively transient storage).
FPreAnimatedStorageIndex defines an index into this array (or into the rarely used TransientPreAnimatedStorage map)
Definition at line 924 of file MovieScenePreAnimatedStateStorage.h.
RestoreMask
template<typename StorageTraits> const IRestoreMask* UE::MovieScene::TPreAnimatedStateStorage< StorageTraits >::RestoreMask = nullptr protected
Temporary restoration mask.
Definition at line 939 of file MovieScenePreAnimatedStateStorage.h.
StorageID
template<typename StorageTraits> FPreAnimatedStorageID UE::MovieScene::TPreAnimatedStateStorage< StorageTraits >::StorageID protected
Our storage ID.
Definition at line 942 of file MovieScenePreAnimatedStateStorage.h.
Traits
template<typename StorageTraits> StorageTraits UE::MovieScene::TPreAnimatedStateStorage< StorageTraits >::Traits
Traits instance - normally not required but some traits require state.
Definition at line 947 of file MovieScenePreAnimatedStateStorage.h.
TransientPreAnimatedStorage
template<typename StorageTraits> TSortedMap<FPreAnimatedStorageIndex, StorageType> UE::MovieScene::TPreAnimatedStateStorage< StorageTraits >::TransientPreAnimatedStorage protected
Storage that holds values that need to be kept transiently (for evaluation).
This map is only used if a Keep State section previously captured a value (because it is evaluating in a 'Capture Global State' context) and we end up animating the same value using a Restore State section. The Restore State section has to re-capture its starting value whilst also keeping the previously captured value alive to ensure that the section can restore to its starting value in addition to the sequence itself restoring to the global starting value
Definition at line 933 of file MovieScenePreAnimatedStateStorage.h.
The documentation for this struct was generated from the following file:
Runtime/MovieScene/Public/Evaluation/PreAnimatedState/MovieScenePreAnimatedStateStorage.h