Unreal Engine 5.6 C++ API: FSlateAttributeDescriptor::FInvalidateWidgetReasonAttribute Struct Reference
FSlateAttributeDescriptor::FInvalidateWidgetReasonAttribute Struct Reference
A EInvalidationWidgetReason Attribute It can be explicitly initialize or can be a callback static function or lambda that returns the EInvalidationReason.
#include "SlateAttributeDescriptor.h"
Public Types
using Arg1Type = const class SWidget&
using FGetter = TDelegate<EInvalidateWidgetReason(Arg1Type), FNotThreadSafeNotCheckedDelegateUserPolicy>
Public Member Functions
FInvalidateWidgetReasonAttribute (const FInvalidateWidgetReasonAttribute &)=default
FInvalidateWidgetReasonAttribute (EInvalidateWidgetReason InReason)
Default constructor.
FInvalidateWidgetReasonAttribute (FInvalidateWidgetReasonAttribute &&)=default
template<typename LambdaType, typename... PayloadTypes>
FInvalidateWidgetReasonAttribute (LambdaType &&InCallable, PayloadTypes &&... InputPayload)
template<typename... PayloadTypes>
FInvalidateWidgetReasonAttribute (TIdentity_T< typename FGetter::template TFuncPtr< PayloadTypes... > > InFuncPtr, PayloadTypes &&... InputPayload)
EInvalidateWidgetReason Get (const SWidget &Widget) const
bool IsBound () const
FInvalidateWidgetReasonAttribute & operator= (const FInvalidateWidgetReasonAttribute &)=default
FInvalidateWidgetReasonAttribute & operator= (FInvalidateWidgetReasonAttribute &&)=default
Data Fields
friend FSlateAttributeDescriptor
Private Attributes
FGetter Getter
EInvalidateWidgetReason Reason
Detailed Description
A EInvalidationWidgetReason Attribute It can be explicitly initialize or can be a callback static function or lambda that returns the EInvalidationReason.
The signature of the function takes a const SWidget& as argument.
Definition at line 39 of file SlateAttributeDescriptor.h.
Member Typedef Documentation
Arg1Type
using FSlateAttributeDescriptor::FInvalidateWidgetReasonAttribute::Arg1Type = const class SWidget&
Definition at line 43 of file SlateAttributeDescriptor.h.
FGetter
using FSlateAttributeDescriptor::FInvalidateWidgetReasonAttribute::FGetter = TDelegate<EInvalidateWidgetReason(Arg1Type), FNotThreadSafeNotCheckedDelegateUserPolicy>
Definition at line 45 of file SlateAttributeDescriptor.h.
Constructor & Destructor Documentation
FInvalidateWidgetReasonAttribute() [1/5]
FSlateAttributeDescriptor::FInvalidateWidgetReasonAttribute::FInvalidateWidgetReasonAttribute (const FInvalidateWidgetReasonAttribute &) default
References FInvalidateWidgetReasonAttribute().
Referenced by FInvalidateWidgetReasonAttribute(), FInvalidateWidgetReasonAttribute(), operator=(), and operator=().
FInvalidateWidgetReasonAttribute() [2/5]
FSlateAttributeDescriptor::FInvalidateWidgetReasonAttribute::FInvalidateWidgetReasonAttribute (FInvalidateWidgetReasonAttribute &&) default
References FInvalidateWidgetReasonAttribute().
FInvalidateWidgetReasonAttribute() [3/5]
FSlateAttributeDescriptor::FInvalidateWidgetReasonAttribute::FInvalidateWidgetReasonAttribute (EInvalidateWidgetReason InReason) inline explicit
Default constructor.
Definition at line 54 of file SlateAttributeDescriptor.h.
References Getter, and Reason.
FInvalidateWidgetReasonAttribute() [4/5]
template<typename... PayloadTypes> FSlateAttributeDescriptor::FInvalidateWidgetReasonAttribute::FInvalidateWidgetReasonAttribute (TIdentity_T< typename FGetter::template TFuncPtr< PayloadTypes... > > InFuncPtr, PayloadTypes &&... InputPayload) inline explicit
Definition at line 61 of file SlateAttributeDescriptor.h.
References Forward(), Getter, None, and Reason.
FInvalidateWidgetReasonAttribute() [5/5]
template<typename LambdaType, typename... PayloadTypes> FSlateAttributeDescriptor::FInvalidateWidgetReasonAttribute::FInvalidateWidgetReasonAttribute (LambdaType && InCallable, PayloadTypes &&... InputPayload) inline explicit
Definition at line 68 of file SlateAttributeDescriptor.h.
References Forward(), Getter, None, and Reason.
Member Function Documentation
Get()
EInvalidateWidgetReason FSlateAttributeDescriptor::FInvalidateWidgetReasonAttribute::Get (const SWidget & Widget) const inline
Definition at line 79 of file SlateAttributeDescriptor.h.
References Getter, IsBound(), and Reason.
IsBound()
bool FSlateAttributeDescriptor::FInvalidateWidgetReasonAttribute::IsBound () const inline
Definition at line 74 of file SlateAttributeDescriptor.h.
References Getter.
Referenced by Get().
operator=() [1/2]
FInvalidateWidgetReasonAttribute & FSlateAttributeDescriptor::FInvalidateWidgetReasonAttribute::operator= (const FInvalidateWidgetReasonAttribute &) default
References FInvalidateWidgetReasonAttribute().
operator=() [2/2]
FInvalidateWidgetReasonAttribute & FSlateAttributeDescriptor::FInvalidateWidgetReasonAttribute::operator= (FInvalidateWidgetReasonAttribute &&) default
References FInvalidateWidgetReasonAttribute().
Field Documentation
FSlateAttributeDescriptor
friend FSlateAttributeDescriptor::FInvalidateWidgetReasonAttribute::FSlateAttributeDescriptor
Definition at line 41 of file SlateAttributeDescriptor.h.
Getter
FGetter FSlateAttributeDescriptor::FInvalidateWidgetReasonAttribute::Getter private
Definition at line 86 of file SlateAttributeDescriptor.h.
Referenced by FInvalidateWidgetReasonAttribute(), FInvalidateWidgetReasonAttribute(), FInvalidateWidgetReasonAttribute(), Get(), and IsBound().
Reason
EInvalidateWidgetReason FSlateAttributeDescriptor::FInvalidateWidgetReasonAttribute::Reason private
Definition at line 85 of file SlateAttributeDescriptor.h.
Referenced by FInvalidateWidgetReasonAttribute(), FInvalidateWidgetReasonAttribute(), FInvalidateWidgetReasonAttribute(), and Get().
The documentation for this struct was generated from the following file:
Runtime/SlateCore/Public/Types/SlateAttributeDescriptor.h