Unreal Engine 5.6 C++ API: FGenericCrashContext Struct Reference
FGenericCrashContext Struct Reference
Contains a runtime crash's properties that are common for all platforms.
#include "GenericPlatformCrashContext.h"
Public Member Functions
FGenericCrashContext (ECrashContextType InType, const TCHAR *ErrorMessage)
Default constructor.
virtual ~FGenericCrashContext ()
template<typename Type>
void AddCrashProperty (const TCHAR *PropertyName, const Type &Value) const
virtual void AddPortableThreadCallStack (uint32 ThreadId, const TCHAR *ThreadName, const uint64 *StackFrames, int32 NumStackFrames)
virtual void AddPortableThreadCallStacks (TConstArrayView< FThreadCallStack > Threads)
Adds a portable callstack for a thread.
virtual void CaptureModules ()
Store info about loaded modules.
void CapturePortableCallStack (void *ErrorProgramCounter, void *Context)
Generate raw call stack for crash report (image base + offset) for the calling thread.
void CaptureThreadPortableCallStack (const uint64 ThreadId, void *Context)
Generate raw call stack for crash report (image base + offset) for a different thread.
virtual void CopyPlatformSpecificFiles (const TCHAR *OutputDirectory, void *Context)
Allows platform implementations to copy files to report directory.
const FString & GetBuffer () const
virtual void GetModules (TArray< FStackWalkModuleInfo > &OutModules) const
Gets info about loaded modules and stores it in the given array.
virtual void GetPortableCallStack (const uint64 *StackFrames, int32 NumStackFrames, TArray< FCrashStackFrame > &OutCallStack) const
Gets the portable callstack to a specified stack and puts it into OutCallStack.
ECrashContextType GetType () const
void GetUniqueCrashName (TCHAR *GUIDBuffer, int32 BufferSize) const
const bool IsFullCrashDump () const
virtual void SerializeAsXML (const TCHAR *Filename) const
Serializes crash's informations to the specified filename.
void SerializeContentToBuffer () const
Serializes all data to the buffer.
void SetCrashedProcess (const FProcHandle &Process)
Sets the process id to that has crashed.
void SetCrashedThreadId (uint32 InId)
Stores crashing thread id.
void SetNumMinidumpFramesToIgnore (int32 InNumMinidumpFramesToIgnore)
Sets the number of stack frames to ignore when symbolicating from a minidump.
virtual void SetPortableCallStack (const uint64 *StackFrames, int32 NumStackFrames)
Sets the portable callstack to a specified stack.
UE_DEPRECATED (5.0, "") 1 void CapturePortableCallStack(int32 NumStackFramesToIgnore
Static Public Member Functions
template<typename Type>
static void AddCrashProperty (FString &Buffer, const TCHAR *PropertyName, const Type &Value)
static void AddFile (const FString &AbsoluteSourcePath)
Adds a file to bundle with the crash report.
static void AddFooter (FString &Buffer)
Writes footer to the buffer.
static void AddHeader (FString &Buffer)
Writes header information to the buffer.
static void AddPlugin (const FString &PluginDesc)
Adds a plugin descriptor string to the enabled plugins list in the crash context.
static void AddSection (FString &Buffer, const TCHAR *SectionName, const FString &SectionContent)
static void AppendEscapedXMLString (FString &OutBuffer, FStringView Text)
Escapes and appends specified text to XML string.
static void AppendEscapedXMLString (FStringBuilderBase &OutBuffer, FStringView Text)
static void AppendPortableCallstack (FString &OutBuffer, TConstArrayView< FCrashStackFrame > StackFrames)
static void BeginSection (FString &Buffer, const TCHAR *SectionName)
static void CleanupPlatformSpecificFiles ()
Cleanup platform specific files - called on startup, implemented per platform.
static void CleanupTempSessionContextFiles (const FTimespan &ExpirationAge)
Clean up expired context files that were left-over on the user disks (because the consumer crashed and/or failed to delete it).
static void CopySharedCrashContext (FSharedCrashContext &Dst)
Initializes a shared crash context from current state.
static bool CreateCrashReportDirectory (const TCHAR *CrashGUIDRoot, int32 CrashIndex, FString &OutCrashDirectoryAbsolute)
Attempts to create the output report directory.
static void DumpAdditionalContext (const TCHAR *CrashFolderAbsolute)
Collects additional crash context providers.
static FString DumpLog (const FString &CrashFolderAbsolute)
Flushes the logs.
static void EndSection (FString &Buffer, const TCHAR *SectionName)
static const FSessionContext & GetCachedSessionContext ()
Get the current cached session context.
static const TCHAR * GetCrashConfigFilePath ()
Helper to get the crash report client config filepath saved by this instance and copied to each crash report folder.
static const TCHAR * GetCrashConfigFolder ()
Helper to get the crash report client config folder used by GetCrashConfigFilePath().
static FString GetCrashGameName ()
Get the Game Name of the crash.
static const TCHAR * GetCrashTypeString (ECrashContextType Type)
Helper to get the standard string for the crash type based on crash event bool values.
static const TCHAR * GetDeploymentName ()
Get the current deployment name (ie.
static const TMap< FString, FString > & GetEngineData ()
Get the engine data dictionary.
static const TMap< FString, FString > & GetGameData ()
Get the game data dictionary.
static FString GetGameName ()
Gets the current standardized game name for use in a Crash Reporter report.
static TOptional< int32 > GetOutOfProcessCrashReporterExitCode ()
Return the out-of-process crash reporter exit code if available.
static uint32 GetOutOfProcessCrashReporterProcessId ()
static FString GetTempSessionContextFilePath (uint64 ProcessID)
Get the file path to the temporary session context file that we create for the given process.
static void Initialize ()
Initializes crash context related platform specific data that can be impossible to obtain after a crash.
static void InitializeFromContext (const FSessionContext &Context, const TCHAR *EnabledPlugins, const TCHAR *EngineData, const TCHAR *GameData, const TCHAR *FilePathData, const FGPUBreadcrumbsSharedContext *GPUBreadcrumbs)
Initialized crash context, using a crash context (e.g.
static bool IsInitalized ()
static bool IsOutOfProcessCrashReporter ()
static bool IsTypeContinuable (ECrashContextType Type)
static FAdditionalCrashContextDelegate & OnAdditionalCrashContextDelegate ()
Delegate for additional crash context.
static FEngineDataResetDelegate & OnEngineDataResetDelegate ()
Accessor for engine data reset callback delegate.
static FEngineDataSetDelegate & OnEngineDataSetDelegate ()
Accessor for engine data change callback delegate.
static FGameDataResetDelegate & OnGameDataResetDelegate ()
Accessor for game data reset callback delegate.
static FGameDataSetDelegate & OnGameDataSetDelegate ()
Accessor for game data change callback delegate.
static void OnThreadStuck (uint32 ThreadId)
Sets a flag that one of the threads is stuck.
static void OnThreadUnstuck (uint32 ThreadId)
Clears the stuck flag.
static void PurgeOldCrashConfig ()
Helper to clean out old files in the crash report client config folder.
static void ResetEngineData ()
Clears the engine data dictionary.
static void ResetGameData ()
Clears the game data dictionary.
static void SerializeSessionContext (FString &Buffer)
Serializes session context to the given buffer.
static void SetAnticheatProvider (const FString &AnticheatProvider)
Sets the Anticheat client provider.
static void SetCrashTrigger (ECrashTrigger Type)
Sets the type of crash triggered.
static void SetDeploymentName (const FString &EpicApp)
Set the current deployment name (ie.
static void SetEngineData (const FString &Key, const FString &Value)
Updates (or adds if not already present) arbitrary engine data to the crash context (will remove the key if passed an empty string)
static void SetEngineExit (bool bIsRequestExit)
Notify the crash context exit has been requested.
static void SetEpicAccountId (const FString &EpicAccountId)
Set or change the epic account id associated with the crash session.
static void SetGameData (const FString &Key, const FString &Value)
Updates (or adds if not already present) arbitrary game data to the crash context (will remove the key if passed an empty string)
static void SetGPUBreadcrumbs (FGPUBreadcrumbCrashData &&Data)
Updates (or adds if not already present) GPU breadcrumb data.
static void SetMemoryStats (const FPlatformMemoryStats &MemoryStats)
We can't gather memory stats in crash handling function, so we gather them just before raising exception and use in crash reporting.
static void SetOutOfProcessCrashReporterExitCode (int32 ExitCode)
Set the out of process crash reporter exit code if known.
static void SetOutOfProcessCrashReporterPid (uint32 ProcessId)
Set whether or not the out-of-process crash reporter is running.
static FString UnescapeXMLString (const FString &Text)
Unescapes a specified XML string, naive implementation.
Data Fields
void * Context
Static Public Attributes
static const TCHAR *const AttendedStatusTag
static const TCHAR *const BuildVersionTag
static const TCHAR *const CallStackTag
static const TCHAR *const ConfigSectionName
static const TCHAR *const CrashConfigExtension
static const ANSICHAR *const CrashConfigFileNameA
static const TCHAR *const CrashConfigFileNameW
static const TCHAR *const CrashConfigPurgeDays
static const TCHAR *const CrashContextExtension
static const ANSICHAR *const CrashContextRuntimeXMLNameA
static const TCHAR *const CrashContextRuntimeXMLNameW
static constexpr int32 CrashGUIDLength = 128
static const TCHAR *const CrashGUIDRootPrefix
static const TCHAR *const CrashGuidTag
static const TCHAR *const CrashReporterMessageTag
static const TCHAR *const CrashReportOptionalAttachmentsDirName
static const TCHAR *const CrashTypeAbnormalShutdown
static const TCHAR *const CrashTypeAssert
static const TCHAR *const CrashTypeCrash
static const TCHAR *const CrashTypeEnsure
static const TCHAR *const CrashTypeGPU
static const TCHAR *const CrashTypeHang
static const TCHAR *const CrashTypeOutOfMemory
static const TCHAR *const CrashTypeStall
static const TCHAR *const CrashTypeTag
static const TCHAR *const CrashTypeVerseRuntimeError
static const TCHAR *const CrashVersionTag
static const TCHAR *const DeploymentNameTag
static const TCHAR *const EnabledPluginsTag
static const TCHAR *const EngineDataTag
static const TCHAR *const EngineModeExDirty
static const TCHAR *const EngineModeExUnknown
static const TCHAR *const EngineModeExVanilla
static const TCHAR *const ErrorMessageTag
static const FGuid ExecutionGuid
static const TCHAR *const ExecutionGuidTag
static const TCHAR *const GameDataTag
static const TCHAR *const GameNameTag
static const TCHAR *const IsAssertTag
static const TCHAR *const IsEnsureTag
static const TCHAR *const IsInternalBuildTag
static const TCHAR *const IsPerforceBuildTag
static const TCHAR *const IsRequestingExitTag
static const TCHAR *const IsSourceDistributionTag
static const TCHAR *const IsStallTag
static const TCHAR *const IsWithDebugInfoTag
static const TCHAR *const LogFilePathTag
static const TCHAR *const NewLineTag
static const TCHAR *const PlatformPropertiesTag
static const TCHAR *const PortableCallStackHashTag
static const TCHAR *const PortableCallStackTag
static const TCHAR *const ProcessIdTag
static const TCHAR *const RequestDataTag
static const TCHAR *const RuntimePropertiesTag
static const TCHAR *const SecondsSinceStartTag
static const TCHAR *const UEMinidumpName
Protected Member Functions
virtual const TCHAR * GetCallstackProperty () const
Allow platform implementations to provide a callstack property.
virtual bool GetPlatformAllThreadContextsString (FString &OutStr) const
@OutStr - a stream of Thread XML elements containing info (e.g.
Static Protected Member Functions
static FString GenerateNewCrashGuidBase ()
Generate a new crash guid base string.
static const FString * GetEngineData (const FString &Key)
Get arbitrary engine data from the crash context.
static const FString * GetGameData (const FString &Key)
Get arbitrary game data from the crash context.
Protected Attributes
TArray< FCrashStackFrame > CallStack
uint32 CrashedThreadId
const TCHAR * ErrorMessage
TArray< FStackWalkModuleInfo > ModulesInfo
int NumMinidumpFramesToIgnore
FProcHandle ProcessHandle
TArray< FThreadStackFrames > ThreadCallStacks
ECrashContextType Type
Private Member Functions
FGenericCrashContext (const FGenericCrashContext &)=delete
void AddGPUBreadcrumbs () const
Add GPU breadcrumbs information to the crash report xml.
void AddModules () const
Add module/pdb information to the crash report xml.
virtual void AddPlatformSpecificProperties () const
Serializes platform specific properties to the buffer.
void AddPortableCallStack () const
Add callstack information to the crash report xml.
void AddPortableCallStackHash () const
Produces a hash based on the offsets of the portable callstack and adds it to the xml.
FGenericCrashContext & operator= (const FGenericCrashContext &)=delete
Static Private Member Functions
template<typename Type>
static void AddCrashPropertyInternal (FString &Buffer, FStringView PropertyName, const Type &Value)
Writes a common property to the buffer.
static void AddCrashPropertyInternal (FString &Buffer, FStringView PropertyName, FStringView PropertyValue)
Writes a common property to the buffer.
static void InitializeFromConfig ()
Called once when GConfig is initialized.
static void SerializeTempCrashContextToFile ()
Serializes the session context section of the crash context to a temporary file.
static void SerializeUserSettings (FString &Buffer)
Serializes the current user setting struct to a buffer.
static void UpdateLocalizedStrings ()
Called to update any localized strings in the crash context.
Private Attributes
FString CommonBuffer
The buffer used to store the crash's properties.
int32 CrashContextIndex
Records which crash context we were using the StaticCrashContextIndex counter.
Static Private Attributes
static FAdditionalCrashContextDelegate AdditionalCrashContextDelegate
Delegate for additional crash context.
static bool bIsInitialized
Whether the Initialize() has been called.
static FEngineDataResetDelegate OnEngineDataReset
Engine and game data set / reset delegates.
static FEngineDataSetDelegate OnEngineDataSet
static FGameDataResetDelegate OnGameDataReset
static FGameDataSetDelegate OnGameDataSet
static volatile int64 OutOfProcessCrashReporterExitCode
The out of process crash reporter exit code, if available.
static uint32 OutOfProcessCrashReporterPid
The ID of the external process reporting crashes if the platform supports it and was configured to use it, zero otherwise (0 is a reserved system process ID, invalid for the out of process reporter).
static int32 StaticCrashContextIndex
Static counter records how many crash contexts have been constructed.
Detailed Description
Contains a runtime crash's properties that are common for all platforms.
This may change in the future.
Definition at line 390 of file GenericPlatformCrashContext.h.
Constructor & Destructor Documentation
FGenericCrashContext() [1/2]
FGenericCrashContext::FGenericCrashContext (ECrashContextType InType, const TCHAR * ErrorMessage)
Default constructor.
Optionally pass a process handle if building a crash context for a process other then current.
References ErrorMessage.
Referenced by FGenericCrashContext(), FMicrosoftPlatformCrashContext::FMicrosoftPlatformCrashContext(), FUnixCrashContext::FUnixCrashContext(), and operator=().
~FGenericCrashContext()
virtual FGenericCrashContext::~FGenericCrashContext () inline virtual
Definition at line 525 of file GenericPlatformCrashContext.h.
FGenericCrashContext() [2/2]
FGenericCrashContext::FGenericCrashContext (const FGenericCrashContext &) private delete
References FGenericCrashContext().
Member Function Documentation
AddCrashProperty() [1/2]
template<typename Type> void FGenericCrashContext::AddCrashProperty (const TCHAR * PropertyName, const Type & Value) const inline
Definition at line 564 of file GenericPlatformCrashContext.h.
References AddCrashPropertyInternal(), CommonBuffer, PropertyName, Type, and Value.
AddCrashProperty() [2/2]
template<typename Type> void FGenericCrashContext::AddCrashProperty (FString & Buffer, const TCHAR * PropertyName, const Type & Value) inline static
Definition at line 570 of file GenericPlatformCrashContext.h.
References AddCrashPropertyInternal(), Buffer, PropertyName, Type, and Value.
AddCrashPropertyInternal() [1/2]
template<typename Type> void FGenericCrashContext::AddCrashPropertyInternal (FString & Buffer, FStringView PropertyName, const Type & Value) inline static private
Writes a common property to the buffer.
Definition at line 821 of file GenericPlatformCrashContext.h.
References AddCrashPropertyInternal(), Buffer, PropertyName, TTypeToString< T >::ToString(), Type, and Value.
AddCrashPropertyInternal() [2/2]
void FGenericCrashContext::AddCrashPropertyInternal (FString & Buffer, FStringView PropertyName, FStringView PropertyValue) static private
Writes a common property to the buffer.
References Buffer, and PropertyName.
Referenced by AddCrashProperty(), AddCrashProperty(), and AddCrashPropertyInternal().
AddFile()
void FGenericCrashContext::AddFile (const FString & AbsoluteSourcePath) static
Adds a file to bundle with the crash report.
AddFooter()
void FGenericCrashContext::AddFooter (FString & Buffer) static
Writes footer to the buffer.
References Buffer.
AddGPUBreadcrumbs()
void FGenericCrashContext::AddGPUBreadcrumbs () const private
Add GPU breadcrumbs information to the crash report xml.
AddHeader()
void FGenericCrashContext::AddHeader (FString & Buffer) static
Writes header information to the buffer.
References Buffer.
AddModules()
void FGenericCrashContext::AddModules () const private
Add module/pdb information to the crash report xml.
AddPlatformSpecificProperties()
virtual void FGenericCrashContext::AddPlatformSpecificProperties () const private virtual
Serializes platform specific properties to the buffer.
Reimplemented in FAndroidCrashContext, FIOSCrashContext, FUnixCrashContext, and FWindowsPlatformCrashContext.
AddPlugin()
void FGenericCrashContext::AddPlugin (const FString & PluginDesc) static
Adds a plugin descriptor string to the enabled plugins list in the crash context.
AddPortableCallStack()
void FGenericCrashContext::AddPortableCallStack () const private
Add callstack information to the crash report xml.
AddPortableCallStackHash()
void FGenericCrashContext::AddPortableCallStackHash () const private
Produces a hash based on the offsets of the portable callstack and adds it to the xml.
AddPortableThreadCallStack()
virtual void FGenericCrashContext::AddPortableThreadCallStack (uint32 ThreadId, const TCHAR * ThreadName, const uint64 * StackFrames, int32 NumStackFrames) virtual
Reimplemented in FMicrosoftPlatformCrashContext.
References AddPortableThreadCallStack().
Referenced by AddPortableThreadCallStack().
AddPortableThreadCallStacks()
virtual void FGenericCrashContext::AddPortableThreadCallStacks (TConstArrayView< FThreadCallStack > Threads) virtual
Adds a portable callstack for a thread.
Reimplemented in FMicrosoftPlatformCrashContext.
References AddPortableThreadCallStacks().
Referenced by AddPortableThreadCallStacks().
AddSection()
void FGenericCrashContext::AddSection (FString & Buffer, const TCHAR * SectionName, const FString & SectionContent) static
References Buffer.
AppendEscapedXMLString() [1/2]
void FGenericCrashContext::AppendEscapedXMLString (FString & OutBuffer, FStringView Text) static
Escapes and appends specified text to XML string.
References Text.
AppendEscapedXMLString() [2/2]
void FGenericCrashContext::AppendEscapedXMLString (FStringBuilderBase & OutBuffer, FStringView Text) static
References Text.
AppendPortableCallstack()
void FGenericCrashContext::AppendPortableCallstack (FString & OutBuffer, TConstArrayView< FCrashStackFrame > StackFrames) static
BeginSection()
void FGenericCrashContext::BeginSection (FString & Buffer, const TCHAR * SectionName) static
References Buffer.
CaptureModules()
virtual void FGenericCrashContext::CaptureModules () virtual
Store info about loaded modules.
References CaptureModules().
Referenced by CaptureModules().
CapturePortableCallStack()
void FGenericCrashContext::CapturePortableCallStack (void * ErrorProgramCounter, void * Context)
Generate raw call stack for crash report (image base + offset) for the calling thread.
Parameters
ErrorProgramCounter The program counter of where the occur occurred in the callstack being captured
Context Optional thread context information
References Context.
CaptureThreadPortableCallStack()
void FGenericCrashContext::CaptureThreadPortableCallStack (const uint64 ThreadId, void * Context)
Generate raw call stack for crash report (image base + offset) for a different thread.
Parameters
InThreadId The thread id of the thread to capture the callstack for
Context Optional thread context information
References Context.
CleanupPlatformSpecificFiles()
void FGenericCrashContext::CleanupPlatformSpecificFiles () static
Cleanup platform specific files - called on startup, implemented per platform.
References CleanupPlatformSpecificFiles().
Referenced by CleanupPlatformSpecificFiles().
CleanupTempSessionContextFiles()
void FGenericCrashContext::CleanupTempSessionContextFiles (const FTimespan & ExpirationAge) static
Clean up expired context files that were left-over on the user disks (because the consumer crashed and/or failed to delete it).
CopyPlatformSpecificFiles()
virtual void FGenericCrashContext::CopyPlatformSpecificFiles (const TCHAR * OutputDirectory, void * Context) virtual
Allows platform implementations to copy files to report directory.
Reimplemented in FWindowsPlatformCrashContext.
References Context, and CopyPlatformSpecificFiles().
Referenced by CopyPlatformSpecificFiles().
CopySharedCrashContext()
void FGenericCrashContext::CopySharedCrashContext (FSharedCrashContext & Dst) static
Initializes a shared crash context from current state.
Will not set all fields in Dst.
CreateCrashReportDirectory()
bool FGenericCrashContext::CreateCrashReportDirectory (const TCHAR * CrashGUIDRoot, int32 CrashIndex, FString & OutCrashDirectoryAbsolute) static
Attempts to create the output report directory.
DumpAdditionalContext()
void FGenericCrashContext::DumpAdditionalContext (const TCHAR * CrashFolderAbsolute) static
Collects additional crash context providers.
See FAdditionalCrashContextStack.
DumpLog()
FString FGenericCrashContext::DumpLog (const FString & CrashFolderAbsolute) static
Flushes the logs.
In the case of in memory logs is used on this configuration, dumps them to file. Returns the name of the file
EndSection()
void FGenericCrashContext::EndSection (FString & Buffer, const TCHAR * SectionName) static
References Buffer.
GenerateNewCrashGuidBase()
FString FGenericCrashContext::GenerateNewCrashGuidBase () static protected
Generate a new crash guid base string.
GetBuffer()
const FString & FGenericCrashContext::GetBuffer () const inline
Returns
the buffer containing serialized data.
Definition at line 539 of file GenericPlatformCrashContext.h.
References CommonBuffer.
GetCachedSessionContext()
const FSessionContext & FGenericCrashContext::GetCachedSessionContext () static
Get the current cached session context.
GetCallstackProperty()
virtual const TCHAR * FGenericCrashContext::GetCallstackProperty () const protected virtual
Allow platform implementations to provide a callstack property.
Primarily used when non-native code triggers a crash.
Reimplemented in FAndroidCrashContext, and FApplePlatformCrashContext.
GetCrashConfigFilePath()
const TCHAR * FGenericCrashContext::GetCrashConfigFilePath () static
Helper to get the crash report client config filepath saved by this instance and copied to each crash report folder.
GetCrashConfigFolder()
const TCHAR * FGenericCrashContext::GetCrashConfigFolder () static
Helper to get the crash report client config folder used by GetCrashConfigFilePath().
GetCrashGameName()
FString FGenericCrashContext::GetCrashGameName () static
Get the Game Name of the crash.
GetCrashTypeString()
const TCHAR * FGenericCrashContext::GetCrashTypeString (ECrashContextType Type) static
Helper to get the standard string for the crash type based on crash event bool values.
References Type.
GetDeploymentName()
const TCHAR * FGenericCrashContext::GetDeploymentName () static
Get the current deployment name (ie.
EpicApp)
GetEngineData() [1/2]
const TMap< FString, FString > & FGenericCrashContext::GetEngineData () static
Get the engine data dictionary.
GetEngineData() [2/2]
const FString * FGenericCrashContext::GetEngineData (const FString & Key) static protected
Get arbitrary engine data from the crash context.
References Key.
GetGameData() [1/2]
const TMap< FString, FString > & FGenericCrashContext::GetGameData () static
Get the game data dictionary.
GetGameData() [2/2]
const FString * FGenericCrashContext::GetGameData (const FString & Key) static protected
Get arbitrary game data from the crash context.
References Key.
GetGameName()
FString FGenericCrashContext::GetGameName () static
Gets the current standardized game name for use in a Crash Reporter report.
GetModules()
virtual void FGenericCrashContext::GetModules (TArray< FStackWalkModuleInfo > & OutModules) const virtual
Gets info about loaded modules and stores it in the given array.
References GetModules().
Referenced by GetModules().
GetOutOfProcessCrashReporterExitCode()
TOptional< int32 > FGenericCrashContext::GetOutOfProcessCrashReporterExitCode () static
Return the out-of-process crash reporter exit code if available.
The exit code is available if crash reporter process died while the application it monitors was still running. Then engine periodically poll the health of the crash reporter process and try to read its exit code if it unexpectedly died.
Note
This function is useful to try diagnose why the crash reporter died (crashed/killed/asserted) and gather data for the analytics.
GetOutOfProcessCrashReporterProcessId()
uint32 FGenericCrashContext::GetOutOfProcessCrashReporterProcessId () inline static
Returns
a non-zero value if crash reporter process is used to monitor the session, capture the call stack and write the minidump, otherwise, this is done inside the crashing process.
Definition at line 491 of file GenericPlatformCrashContext.h.
References OutOfProcessCrashReporterPid.
GetPlatformAllThreadContextsString()
virtual bool FGenericCrashContext::GetPlatformAllThreadContextsString (FString & OutStr) const inline protected virtual
@OutStr - a stream of Thread XML elements containing info (e.g.
callstack) specific to an active thread
Returns
- whether the operation was successful
Reimplemented in FMacCrashContext, and FMicrosoftPlatformCrashContext.
Definition at line 785 of file GenericPlatformCrashContext.h.
GetPortableCallStack()
virtual void FGenericCrashContext::GetPortableCallStack (const uint64 * StackFrames, int32 NumStackFrames, TArray< FCrashStackFrame > & OutCallStack) const virtual
Gets the portable callstack to a specified stack and puts it into OutCallStack.
Reimplemented in FAndroidCrashContext, and FUnixCrashContext.
References GetPortableCallStack().
Referenced by GetPortableCallStack().
GetTempSessionContextFilePath()
FString FGenericCrashContext::GetTempSessionContextFilePath (uint64 ProcessID) static
Get the file path to the temporary session context file that we create for the given process.
GetType()
ECrashContextType FGenericCrashContext::GetType () const inline
Returns
the type of this crash
Definition at line 737 of file GenericPlatformCrashContext.h.
References GetType(), and Type.
Referenced by GetType().
GetUniqueCrashName()
void FGenericCrashContext::GetUniqueCrashName (TCHAR * GUIDBuffer, int32 BufferSize) const
Returns
a globally unique crash name.
Initialize()
void FGenericCrashContext::Initialize () static
Initializes crash context related platform specific data that can be impossible to obtain after a crash.
InitializeFromConfig()
void FGenericCrashContext::InitializeFromConfig () static private
Called once when GConfig is initialized.
Opportunity to cache values from config.
InitializeFromContext()
void FGenericCrashContext::InitializeFromContext (const FSessionContext & Context, const TCHAR * EnabledPlugins, const TCHAR * EngineData, const TCHAR * GameData, const TCHAR * FilePathData, const FGPUBreadcrumbsSharedContext * GPUBreadcrumbs) static
Initialized crash context, using a crash context (e.g.
shared from another process).
References Context.
IsFullCrashDump()
const bool FGenericCrashContext::IsFullCrashDump () const
Returns
whether this crash is a full memory minidump
IsInitalized()
bool FGenericCrashContext::IsInitalized () inline static
Returns
true, if the generic crash context has been initialized.
Definition at line 474 of file GenericPlatformCrashContext.h.
References bIsInitialized.
IsOutOfProcessCrashReporter()
bool FGenericCrashContext::IsOutOfProcessCrashReporter () inline static
Returns
true if walking the crashed call stack and writing the minidump is being handled out-of-process.
Note
The reporting itself (showing the crash UI and sending the report is always done out of process)
Definition at line 483 of file GenericPlatformCrashContext.h.
References OutOfProcessCrashReporterPid.
IsTypeContinuable()
bool FGenericCrashContext::IsTypeContinuable (ECrashContextType Type) inline static
Returns
whether a crash context type is continable
Definition at line 742 of file GenericPlatformCrashContext.h.
References AbnormalShutdown, Assert, Crash, Ensure, GPUCrash, Hang, Max, OutOfMemory, Stall, Type, and VerseRuntimeError.
OnAdditionalCrashContextDelegate()
FAdditionalCrashContextDelegate & FGenericCrashContext::OnAdditionalCrashContextDelegate () inline static
Delegate for additional crash context.
Definition at line 674 of file GenericPlatformCrashContext.h.
References AdditionalCrashContextDelegate.
OnEngineDataResetDelegate()
FEngineDataResetDelegate & FGenericCrashContext::OnEngineDataResetDelegate () inline static
Accessor for engine data reset callback delegate.
Definition at line 606 of file GenericPlatformCrashContext.h.
References OnEngineDataReset.
OnEngineDataSetDelegate()
FEngineDataSetDelegate & FGenericCrashContext::OnEngineDataSetDelegate () inline static
Accessor for engine data change callback delegate.
Definition at line 615 of file GenericPlatformCrashContext.h.
References OnEngineDataSet.
OnGameDataResetDelegate()
FGameDataResetDelegate & FGenericCrashContext::OnGameDataResetDelegate () inline static
Accessor for game data reset callback delegate.
Definition at line 624 of file GenericPlatformCrashContext.h.
References OnGameDataReset.
OnGameDataSetDelegate()
FGameDataSetDelegate & FGenericCrashContext::OnGameDataSetDelegate () inline static
Accessor for game data change callback delegate.
Definition at line 630 of file GenericPlatformCrashContext.h.
References OnGameDataSet.
OnThreadStuck()
void FGenericCrashContext::OnThreadStuck (uint32 ThreadId) static
Sets a flag that one of the threads is stuck.
This is meant to be bound to the ThreadHeartBeat::OnThreadStuck delegate. Not all platforms register to save this flag.
OnThreadUnstuck()
void FGenericCrashContext::OnThreadUnstuck (uint32 ThreadId) static
Clears the stuck flag.
This is meant to be bound to the ThreadHeartBeat::OnThreadUnstuck delegate. Not all platforms register to save this flag.
operator=()
FGenericCrashContext & FGenericCrashContext::operator= (const FGenericCrashContext &) private delete
References FGenericCrashContext().
PurgeOldCrashConfig()
void FGenericCrashContext::PurgeOldCrashConfig () static
Helper to clean out old files in the crash report client config folder.
ResetEngineData()
void FGenericCrashContext::ResetEngineData () static
Clears the engine data dictionary.
ResetGameData()
void FGenericCrashContext::ResetGameData () static
Clears the game data dictionary.
SerializeAsXML()
virtual void FGenericCrashContext::SerializeAsXML (const TCHAR * Filename) const virtual
Serializes crash's informations to the specified filename.
Should be overridden for platforms where using FFileHelper is not safe, all POSIX platforms.
References Filename.
SerializeContentToBuffer()
void FGenericCrashContext::SerializeContentToBuffer () const
Serializes all data to the buffer.
SerializeSessionContext()
void FGenericCrashContext::SerializeSessionContext (FString & Buffer) static
Serializes session context to the given buffer.
NOTE: Assumes that the buffer already has a header and section open.
References Buffer.
SerializeTempCrashContextToFile()
void FGenericCrashContext::SerializeTempCrashContextToFile () static private
Serializes the session context section of the crash context to a temporary file.
SerializeUserSettings()
void FGenericCrashContext::SerializeUserSettings (FString & Buffer) static private
Serializes the current user setting struct to a buffer.
References Buffer.
SetAnticheatProvider()
void FGenericCrashContext::SetAnticheatProvider (const FString & AnticheatProvider) static
Sets the Anticheat client provider.
SetCrashedProcess()
void FGenericCrashContext::SetCrashedProcess (const FProcHandle & Process) inline
Sets the process id to that has crashed.
On supported platforms this will analyze the given process rather than current. Default is current process.
Definition at line 681 of file GenericPlatformCrashContext.h.
References Process, and ProcessHandle.
SetCrashedThreadId()
void FGenericCrashContext::SetCrashedThreadId (uint32 InId) inline
Stores crashing thread id.
Definition at line 687 of file GenericPlatformCrashContext.h.
References CrashedThreadId.
SetCrashTrigger()
void FGenericCrashContext::SetCrashTrigger (ECrashTrigger Type) static
Sets the type of crash triggered.
Used to distinguish crashes caused for debugging purposes.
References Type.
SetDeploymentName()
void FGenericCrashContext::SetDeploymentName (const FString & EpicApp) static
Set the current deployment name (ie.
EpicApp)
SetEngineData()
void FGenericCrashContext::SetEngineData (const FString & Key, const FString & Value) static
Updates (or adds if not already present) arbitrary engine data to the crash context (will remove the key if passed an empty string)
References Key, and Value.
SetEngineExit()
void FGenericCrashContext::SetEngineExit (bool bIsRequestExit) static
Notify the crash context exit has been requested.
SetEpicAccountId()
void FGenericCrashContext::SetEpicAccountId (const FString & EpicAccountId) static
Set or change the epic account id associated with the crash session.
Will override the epic account id stored in the registry for reporting when present.
SetGameData()
void FGenericCrashContext::SetGameData (const FString & Key, const FString & Value) static
Updates (or adds if not already present) arbitrary game data to the crash context (will remove the key if passed an empty string)
References Key, and Value.
SetGPUBreadcrumbs()
void FGenericCrashContext::SetGPUBreadcrumbs (FGPUBreadcrumbCrashData && Data) static
Updates (or adds if not already present) GPU breadcrumb data.
SetMemoryStats()
void FGenericCrashContext::SetMemoryStats (const FPlatformMemoryStats & MemoryStats) static
We can't gather memory stats in crash handling function, so we gather them just before raising exception and use in crash reporting.
SetNumMinidumpFramesToIgnore()
void FGenericCrashContext::SetNumMinidumpFramesToIgnore (int32 InNumMinidumpFramesToIgnore)
Sets the number of stack frames to ignore when symbolicating from a minidump.
SetOutOfProcessCrashReporterExitCode()
void FGenericCrashContext::SetOutOfProcessCrashReporterExitCode (int32 ExitCode) static
Set the out of process crash reporter exit code if known.
The out of process reporter is expected to run in background, waiting for a signal to handle a crashes/ensures/assert, but sometimes it crashes. If the engine detects that its associated out of process crash reporter died and if the child process exit code can be retrieved, it can be exposed through this function.
See also
GetOutOfProcessCrashReporterExitCode
SetOutOfProcessCrashReporterPid()
void FGenericCrashContext::SetOutOfProcessCrashReporterPid (uint32 ProcessId) inline static
Set whether or not the out-of-process crash reporter is running.
A non-zero process id means that crash artifacts like the call stack and then minidump are built in a separated background process. The reporting itself, i.e. packaging and sending the crash artifacts is always done out of process.
Note
CrashReportClient (CrashReportClientEditor for the Editor) can be configured to wait for crash, capture the crashed process callstack, write the minidump, collect all crash artifacts and send them (out-of-process reporting) or just collect and send them (in-process reporting because the crashing process creates all crash artifacts itself).
Definition at line 502 of file GenericPlatformCrashContext.h.
References OutOfProcessCrashReporterPid.
SetPortableCallStack()
virtual void FGenericCrashContext::SetPortableCallStack (const uint64 * StackFrames, int32 NumStackFrames) virtual
Sets the portable callstack to a specified stack.
Reimplemented in FMicrosoftPlatformCrashContext.
References SetPortableCallStack().
Referenced by SetPortableCallStack().
UE_DEPRECATED()
FGenericCrashContext::UE_DEPRECATED (5. 0, "")
UnescapeXMLString()
FString FGenericCrashContext::UnescapeXMLString (const FString & Text) static
Unescapes a specified XML string, naive implementation.
References Text.
UpdateLocalizedStrings()
void FGenericCrashContext::UpdateLocalizedStrings () static private
Called to update any localized strings in the crash context.
Field Documentation
AdditionalCrashContextDelegate
FAdditionalCrashContextDelegate FGenericCrashContext::AdditionalCrashContextDelegate static private
Delegate for additional crash context.
Definition at line 873 of file GenericPlatformCrashContext.h.
Referenced by OnAdditionalCrashContextDelegate().
AttendedStatusTag
const TCHAR* const FGenericCrashContext::AttendedStatusTag static
Definition at line 426 of file GenericPlatformCrashContext.h.
bIsInitialized
bool FGenericCrashContext::bIsInitialized static private
Whether the Initialize() has been called.
Definition at line 860 of file GenericPlatformCrashContext.h.
Referenced by IsInitalized().
BuildVersionTag
const TCHAR* const FGenericCrashContext::BuildVersionTag static
Definition at line 428 of file GenericPlatformCrashContext.h.
CallStack
TArray<FCrashStackFrame> FGenericCrashContext::CallStack protected
Definition at line 792 of file GenericPlatformCrashContext.h.
Referenced by FAndroidCrashContext::GetPortableCallstack_TEMP().
CallStackTag
const TCHAR* const FGenericCrashContext::CallStackTag static
Definition at line 429 of file GenericPlatformCrashContext.h.
CommonBuffer
FString FGenericCrashContext::CommonBuffer mutable private
The buffer used to store the crash's properties.
Definition at line 877 of file GenericPlatformCrashContext.h.
Referenced by AddCrashProperty(), and GetBuffer().
ConfigSectionName
const TCHAR* const FGenericCrashContext::ConfigSectionName static
Definition at line 400 of file GenericPlatformCrashContext.h.
Context
void* FGenericCrashContext::Context
Definition at line 710 of file GenericPlatformCrashContext.h.
Referenced by CapturePortableCallStack(), CaptureThreadPortableCallStack(), CopyPlatformSpecificFiles(), FWindowsPlatformCrashContext::CopyPlatformSpecificFiles(), and InitializeFromContext().
CrashConfigExtension
const TCHAR* const FGenericCrashContext::CrashConfigExtension static
Definition at line 399 of file GenericPlatformCrashContext.h.
CrashConfigFileNameA
const ANSICHAR* const FGenericCrashContext::CrashConfigFileNameA static
Definition at line 397 of file GenericPlatformCrashContext.h.
CrashConfigFileNameW
const TCHAR* const FGenericCrashContext::CrashConfigFileNameW static
Definition at line 398 of file GenericPlatformCrashContext.h.
CrashConfigPurgeDays
const TCHAR* const FGenericCrashContext::CrashConfigPurgeDays static
Definition at line 401 of file GenericPlatformCrashContext.h.
CrashContextExtension
const TCHAR* const FGenericCrashContext::CrashContextExtension static
Definition at line 406 of file GenericPlatformCrashContext.h.
CrashContextIndex
int32 FGenericCrashContext::CrashContextIndex private
Records which crash context we were using the StaticCrashContextIndex counter.
Definition at line 880 of file GenericPlatformCrashContext.h.
CrashContextRuntimeXMLNameA
const ANSICHAR* const FGenericCrashContext::CrashContextRuntimeXMLNameA static
Definition at line 394 of file GenericPlatformCrashContext.h.
CrashContextRuntimeXMLNameW
const TCHAR* const FGenericCrashContext::CrashContextRuntimeXMLNameW static
Definition at line 395 of file GenericPlatformCrashContext.h.
CrashedThreadId
uint32 FGenericCrashContext::CrashedThreadId protected
Definition at line 789 of file GenericPlatformCrashContext.h.
Referenced by FMicrosoftPlatformCrashContext::AddThreadContextString(), and SetCrashedThreadId().
CrashGUIDLength
int32 FGenericCrashContext::CrashGUIDLength = 128 inline static constexpr
Definition at line 440 of file GenericPlatformCrashContext.h.
CrashGUIDRootPrefix
const TCHAR* const FGenericCrashContext::CrashGUIDRootPrefix static
Definition at line 402 of file GenericPlatformCrashContext.h.
CrashGuidTag
const TCHAR* const FGenericCrashContext::CrashGuidTag static
Definition at line 419 of file GenericPlatformCrashContext.h.
CrashReporterMessageTag
const TCHAR* const FGenericCrashContext::CrashReporterMessageTag static
Definition at line 425 of file GenericPlatformCrashContext.h.
CrashReportOptionalAttachmentsDirName
const TCHAR* const FGenericCrashContext::CrashReportOptionalAttachmentsDirName static
Definition at line 404 of file GenericPlatformCrashContext.h.
CrashTypeAbnormalShutdown
const TCHAR* const FGenericCrashContext::CrashTypeAbnormalShutdown static
Definition at line 448 of file GenericPlatformCrashContext.h.
CrashTypeAssert
const TCHAR* const FGenericCrashContext::CrashTypeAssert static
Definition at line 443 of file GenericPlatformCrashContext.h.
CrashTypeCrash
const TCHAR* const FGenericCrashContext::CrashTypeCrash static
Definition at line 442 of file GenericPlatformCrashContext.h.
CrashTypeEnsure
const TCHAR* const FGenericCrashContext::CrashTypeEnsure static
Definition at line 444 of file GenericPlatformCrashContext.h.
CrashTypeGPU
const TCHAR* const FGenericCrashContext::CrashTypeGPU static
Definition at line 446 of file GenericPlatformCrashContext.h.
CrashTypeHang
const TCHAR* const FGenericCrashContext::CrashTypeHang static
Definition at line 447 of file GenericPlatformCrashContext.h.
CrashTypeOutOfMemory
const TCHAR* const FGenericCrashContext::CrashTypeOutOfMemory static
Definition at line 449 of file GenericPlatformCrashContext.h.
CrashTypeStall
const TCHAR* const FGenericCrashContext::CrashTypeStall static
Definition at line 445 of file GenericPlatformCrashContext.h.
CrashTypeTag
const TCHAR* const FGenericCrashContext::CrashTypeTag static
Definition at line 423 of file GenericPlatformCrashContext.h.
CrashTypeVerseRuntimeError
const TCHAR* const FGenericCrashContext::CrashTypeVerseRuntimeError static
Definition at line 450 of file GenericPlatformCrashContext.h.
CrashVersionTag
const TCHAR* const FGenericCrashContext::CrashVersionTag static
Definition at line 417 of file GenericPlatformCrashContext.h.
DeploymentNameTag
const TCHAR* const FGenericCrashContext::DeploymentNameTag static
Definition at line 408 of file GenericPlatformCrashContext.h.
EnabledPluginsTag
const TCHAR* const FGenericCrashContext::EnabledPluginsTag static
Definition at line 414 of file GenericPlatformCrashContext.h.
EngineDataTag
const TCHAR* const FGenericCrashContext::EngineDataTag static
Definition at line 410 of file GenericPlatformCrashContext.h.
EngineModeExDirty
const TCHAR* const FGenericCrashContext::EngineModeExDirty static
Definition at line 453 of file GenericPlatformCrashContext.h.
EngineModeExUnknown
const TCHAR* const FGenericCrashContext::EngineModeExUnknown static
Definition at line 452 of file GenericPlatformCrashContext.h.
EngineModeExVanilla
const TCHAR* const FGenericCrashContext::EngineModeExVanilla static
Definition at line 454 of file GenericPlatformCrashContext.h.
ErrorMessage
const TCHAR* FGenericCrashContext::ErrorMessage protected
Definition at line 790 of file GenericPlatformCrashContext.h.
Referenced by FGenericCrashContext().
ErrorMessageTag
const TCHAR* const FGenericCrashContext::ErrorMessageTag static
Definition at line 424 of file GenericPlatformCrashContext.h.
ExecutionGuid
const FGuid FGenericCrashContext::ExecutionGuid static
Definition at line 457 of file GenericPlatformCrashContext.h.
ExecutionGuidTag
const TCHAR* const FGenericCrashContext::ExecutionGuidTag static
Definition at line 418 of file GenericPlatformCrashContext.h.
GameDataTag
const TCHAR* const FGenericCrashContext::GameDataTag static
Definition at line 411 of file GenericPlatformCrashContext.h.
GameNameTag
const TCHAR* const FGenericCrashContext::GameNameTag static
Definition at line 413 of file GenericPlatformCrashContext.h.
IsAssertTag
const TCHAR* const FGenericCrashContext::IsAssertTag static
Definition at line 422 of file GenericPlatformCrashContext.h.
IsEnsureTag
const TCHAR* const FGenericCrashContext::IsEnsureTag static
Definition at line 420 of file GenericPlatformCrashContext.h.
IsInternalBuildTag
const TCHAR* const FGenericCrashContext::IsInternalBuildTag static
Definition at line 435 of file GenericPlatformCrashContext.h.
IsPerforceBuildTag
const TCHAR* const FGenericCrashContext::IsPerforceBuildTag static
Definition at line 436 of file GenericPlatformCrashContext.h.
IsRequestingExitTag
const TCHAR* const FGenericCrashContext::IsRequestingExitTag static
Definition at line 432 of file GenericPlatformCrashContext.h.
IsSourceDistributionTag
const TCHAR* const FGenericCrashContext::IsSourceDistributionTag static
Definition at line 438 of file GenericPlatformCrashContext.h.
IsStallTag
const TCHAR* const FGenericCrashContext::IsStallTag static
Definition at line 421 of file GenericPlatformCrashContext.h.
IsWithDebugInfoTag
const TCHAR* const FGenericCrashContext::IsWithDebugInfoTag static
Definition at line 437 of file GenericPlatformCrashContext.h.
LogFilePathTag
const TCHAR* const FGenericCrashContext::LogFilePathTag static
Definition at line 433 of file GenericPlatformCrashContext.h.
ModulesInfo
TArray<FStackWalkModuleInfo> FGenericCrashContext::ModulesInfo protected
Definition at line 794 of file GenericPlatformCrashContext.h.
NewLineTag
const TCHAR* const FGenericCrashContext::NewLineTag static
Definition at line 416 of file GenericPlatformCrashContext.h.
NumMinidumpFramesToIgnore
int FGenericCrashContext::NumMinidumpFramesToIgnore protected
Definition at line 791 of file GenericPlatformCrashContext.h.
OnEngineDataReset
FEngineDataResetDelegate FGenericCrashContext::OnEngineDataReset static private
Engine and game data set / reset delegates.
Definition at line 883 of file GenericPlatformCrashContext.h.
Referenced by OnEngineDataResetDelegate().
OnEngineDataSet
FEngineDataSetDelegate FGenericCrashContext::OnEngineDataSet static private
Definition at line 884 of file GenericPlatformCrashContext.h.
Referenced by OnEngineDataSetDelegate().
OnGameDataReset
FGameDataResetDelegate FGenericCrashContext::OnGameDataReset static private
Definition at line 886 of file GenericPlatformCrashContext.h.
Referenced by OnGameDataResetDelegate().
OnGameDataSet
FGameDataSetDelegate FGenericCrashContext::OnGameDataSet static private
Definition at line 887 of file GenericPlatformCrashContext.h.
Referenced by OnGameDataSetDelegate().
OutOfProcessCrashReporterExitCode
volatile int64 FGenericCrashContext::OutOfProcessCrashReporterExitCode static private
The out of process crash reporter exit code, if available.
The 32 MSB indicates if the exit code is set and the 32 LSB contains the exit code. The value can be read/write from different threads.
Definition at line 866 of file GenericPlatformCrashContext.h.
OutOfProcessCrashReporterPid
uint32 FGenericCrashContext::OutOfProcessCrashReporterPid static private
The ID of the external process reporting crashes if the platform supports it and was configured to use it, zero otherwise (0 is a reserved system process ID, invalid for the out of process reporter).
Definition at line 863 of file GenericPlatformCrashContext.h.
Referenced by GetOutOfProcessCrashReporterProcessId(), IsOutOfProcessCrashReporter(), and SetOutOfProcessCrashReporterPid().
PlatformPropertiesTag
const TCHAR* const FGenericCrashContext::PlatformPropertiesTag static
Definition at line 409 of file GenericPlatformCrashContext.h.
PortableCallStackHashTag
const TCHAR* const FGenericCrashContext::PortableCallStackHashTag static
Definition at line 431 of file GenericPlatformCrashContext.h.
PortableCallStackTag
const TCHAR* const FGenericCrashContext::PortableCallStackTag static
Definition at line 430 of file GenericPlatformCrashContext.h.
ProcessHandle
FProcHandle FGenericCrashContext::ProcessHandle protected
Definition at line 787 of file GenericPlatformCrashContext.h.
Referenced by SetCrashedProcess().
ProcessIdTag
const TCHAR* const FGenericCrashContext::ProcessIdTag static
Definition at line 434 of file GenericPlatformCrashContext.h.
RequestDataTag
const TCHAR* const FGenericCrashContext::RequestDataTag static
Definition at line 412 of file GenericPlatformCrashContext.h.
RuntimePropertiesTag
const TCHAR* const FGenericCrashContext::RuntimePropertiesTag static
Definition at line 407 of file GenericPlatformCrashContext.h.
SecondsSinceStartTag
const TCHAR* const FGenericCrashContext::SecondsSinceStartTag static
Definition at line 427 of file GenericPlatformCrashContext.h.
StaticCrashContextIndex
int32 FGenericCrashContext::StaticCrashContextIndex static private
Static counter records how many crash contexts have been constructed.
Definition at line 869 of file GenericPlatformCrashContext.h.
ThreadCallStacks
TArray<FThreadStackFrames> FGenericCrashContext::ThreadCallStacks protected
Definition at line 793 of file GenericPlatformCrashContext.h.
Type
ECrashContextType FGenericCrashContext::Type protected
Definition at line 788 of file GenericPlatformCrashContext.h.
Referenced by AddCrashProperty(), AddCrashProperty(), AddCrashPropertyInternal(), GetCrashTypeString(), GetType(), IsTypeContinuable(), SetCrashTrigger(), and FUnixCrashContext::SetType().
UEMinidumpName
const TCHAR* const FGenericCrashContext::UEMinidumpName static
Definition at line 415 of file GenericPlatformCrashContext.h.
The documentation for this struct was generated from the following file:
Runtime/Core/Public/GenericPlatform/GenericPlatformCrashContext.h