Unreal Engine 5.6 C++ API: UE::MovieScene::TEntityGroupingHandlerImpl< GroupingPolicy, TIntegerSequence< int, ComponentIndices... >, ComponentTypes... > Struct Template Reference
UE::MovieScene::TEntityGroupingHandlerImpl< GroupingPolicy, TIntegerSequence< int, ComponentIndices... >, ComponentTypes... > Struct Template Reference
#include "MovieSceneEntityGroupingSystem.h"
Public Types
using GroupKeyType = typename GroupingPolicy::GroupKeyType
Public Types inherited from UE::MovieScene::TEntityGroupingHandlerBase< GroupingPolicy >
using GroupKeyType = typename GroupingPolicy::GroupKeyType
Public Member Functions
TEntityGroupingHandlerImpl (GroupingPolicy &&InPolicy, TComponentTypeID< ComponentTypes >... InComponents)
virtual void OnGroupIndexFreed (int32 GroupIndex) override
virtual void OnObjectsReplaced (const TMap< UObject *, UObject * > &ReplacementMap) override
virtual void ProcessAllocation (FEntityAllocationIteratorItem Item, FReadEntityIDs EntityIDs, TWrite< FEntityGroupID > GroupIDs, FEntityGroupBuilder *Builder) override
Process an allocation and group the entities found therein.
void VisitLinkedEntities (FEntityAllocationIteratorItem Item, FReadEntityIDs EntityIDs, TWrite< FEntityGroupID > GroupIDs, FEntityGroupBuilder *Builder)
void VisitUnlinkedEntities (FEntityAllocationIteratorItem Item, FReadEntityIDs EntityIDs, TWrite< FEntityGroupID > GroupIDs, FEntityGroupBuilder *Builder)
Public Member Functions inherited from UE::MovieScene::TEntityGroupingHandlerBase< GroupingPolicy >
int32 GetOrAllocateGroupIndex (typename TCallTraits< GroupKeyType >::ParamType InGroupKey, FEntityGroupBuilder *Builder)
Public Member Functions inherited from UE::MovieScene::IEntityGroupingHandler
virtual ~IEntityGroupingHandler ()
Data Fields
TTuple< TComponentTypeID< ComponentTypes >... > Components
The components that are required for making up a group key.
GroupingPolicy Policy
The grouping policy.
Additional Inherited Members
Protected Attributes inherited from UE::MovieScene::TEntityGroupingHandlerBase< GroupingPolicy >
TMap< GroupKeyType, int32 > GroupKeyToIndex
The group keys that we know about, mapped to their corresponding group index.
TMap< int32, GroupKeyType > IndexToGroupKey
Detailed Description
template<typename GroupingPolicy, int ... ComponentIndices, typename ... ComponentTypes>
struct UE::MovieScene::TEntityGroupingHandlerImpl< GroupingPolicy, TIntegerSequence< int, ComponentIndices... >, ComponentTypes... >
Definition at line 132 of file MovieSceneEntityGroupingSystem.h.
Member Typedef Documentation
GroupKeyType
template<typename GroupingPolicy, int ... ComponentIndices, typename ... ComponentTypes> using UE::MovieScene::TEntityGroupingHandlerImpl< GroupingPolicy, TIntegerSequence< int, ComponentIndices... >, ComponentTypes... >::GroupKeyType = typename GroupingPolicy::GroupKeyType
Definition at line 134 of file MovieSceneEntityGroupingSystem.h.
Constructor & Destructor Documentation
TEntityGroupingHandlerImpl()
template<typename GroupingPolicy, int ... ComponentIndices, typename ... ComponentTypes> UE::MovieScene::TEntityGroupingHandlerImpl< GroupingPolicy, TIntegerSequence< int, ComponentIndices... >, ComponentTypes... >::TEntityGroupingHandlerImpl (GroupingPolicy && InPolicy, TComponentTypeID< ComponentTypes >... InComponents) inline
Definition at line 142 of file MovieSceneEntityGroupingSystem.h.
References Components, MoveTemp(), and Policy.
Member Function Documentation
OnGroupIndexFreed()
template<typename GroupingPolicy, int ... ComponentIndices, typename ... ComponentTypes> virtual void UE::MovieScene::TEntityGroupingHandlerImpl< GroupingPolicy, TIntegerSequence< int, ComponentIndices... >, ComponentTypes... >::OnGroupIndexFreed (int32 GroupIndex) inline override virtual
Reimplemented from UE::MovieScene::IEntityGroupingHandler.
Definition at line 232 of file MovieSceneEntityGroupingSystem.h.
References ensure, UE::MovieScene::TEntityGroupingHandlerBase< GroupingPolicy >::GroupKeyToIndex, UE::MovieScene::TEntityGroupingHandlerBase< GroupingPolicy >::IndexToGroupKey, and Key.
OnObjectsReplaced()
template<typename GroupingPolicy, int ... ComponentIndices, typename ... ComponentTypes> virtual void UE::MovieScene::TEntityGroupingHandlerImpl< GroupingPolicy, TIntegerSequence< int, ComponentIndices... >, ComponentTypes... >::OnObjectsReplaced (const TMap< UObject *, UObject * > & ReplacementMap) inline override virtual
Implements UE::MovieScene::IEntityGroupingHandler.
Definition at line 240 of file MovieSceneEntityGroupingSystem.h.
References TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Add(), ensure, UE::MovieScene::TEntityGroupingHandlerBase< GroupingPolicy >::GroupKeyToIndex, UE::MovieScene::TEntityGroupingHandlerBase< GroupingPolicy >::IndexToGroupKey, and Policy.
ProcessAllocation()
template<typename GroupingPolicy, int ... ComponentIndices, typename ... ComponentTypes> virtual void UE::MovieScene::TEntityGroupingHandlerImpl< GroupingPolicy, TIntegerSequence< int, ComponentIndices... >, ComponentTypes... >::ProcessAllocation (FEntityAllocationIteratorItem Item, FReadEntityIDs EntityIDs, TWrite< FEntityGroupID > GroupIDs, FEntityGroupBuilder * Builder) inline override virtual
Process an allocation and group the entities found therein.
Implements UE::MovieScene::IEntityGroupingHandler.
Definition at line 149 of file MovieSceneEntityGroupingSystem.h.
References UE::MovieScene::FComponentMask::Contains(), ensure, UE::MovieScene::FBuiltInComponentTypes::Get(), Item, UE::MovieScene::FBuiltInComponentTypes::NeedsLink, UE::MovieScene::FBuiltInComponentTypes::NeedsUnlink, UE::MovieScene::FBuiltInComponentTypes::Tags, VisitLinkedEntities(), and VisitUnlinkedEntities().
VisitLinkedEntities()
template<typename GroupingPolicy, int ... ComponentIndices, typename ... ComponentTypes> void UE::MovieScene::TEntityGroupingHandlerImpl< GroupingPolicy, TIntegerSequence< int, ComponentIndices... >, ComponentTypes... >::VisitLinkedEntities (FEntityAllocationIteratorItem Item, FReadEntityIDs EntityIDs, TWrite< FEntityGroupID > GroupIDs, FEntityGroupBuilder * Builder) inline
Definition at line 167 of file MovieSceneEntityGroupingSystem.h.
References UE::MovieScene::FEntityGroupBuilder::AddEntityToGroup(), Components, UE::MovieScene::TEntityGroupingHandlerBase< GroupingPolicy >::GetOrAllocateGroupIndex(), Item, UE::MovieScene::FEntityGroupBuilder::MakeGroupID(), UE::MovieScene::FEntityGroupBuilder::MakeInvalidGroupID(), Num, Policy, and TModels_V.
Referenced by ProcessAllocation().
VisitUnlinkedEntities()
template<typename GroupingPolicy, int ... ComponentIndices, typename ... ComponentTypes> void UE::MovieScene::TEntityGroupingHandlerImpl< GroupingPolicy, TIntegerSequence< int, ComponentIndices... >, ComponentTypes... >::VisitUnlinkedEntities (FEntityAllocationIteratorItem Item, FReadEntityIDs EntityIDs, TWrite< FEntityGroupID > GroupIDs, FEntityGroupBuilder * Builder) inline
Definition at line 211 of file MovieSceneEntityGroupingSystem.h.
References ensure, EnumHasAllFlags(), Item, Num, UE::MovieScene::RemovedFromGroup, and UE::MovieScene::FEntityGroupBuilder::RemoveEntityFromGroup().
Referenced by ProcessAllocation().
Field Documentation
Components
template<typename GroupingPolicy, int ... ComponentIndices, typename ... ComponentTypes> TTuple<TComponentTypeID<ComponentTypes>...> UE::MovieScene::TEntityGroupingHandlerImpl< GroupingPolicy, TIntegerSequence< int, ComponentIndices... >, ComponentTypes... >::Components
The components that are required for making up a group key.
Definition at line 140 of file MovieSceneEntityGroupingSystem.h.
Referenced by TEntityGroupingHandlerImpl(), and VisitLinkedEntities().
Policy
template<typename GroupingPolicy, int ... ComponentIndices, typename ... ComponentTypes> GroupingPolicy UE::MovieScene::TEntityGroupingHandlerImpl< GroupingPolicy, TIntegerSequence< int, ComponentIndices... >, ComponentTypes... >::Policy
The grouping policy.
Definition at line 137 of file MovieSceneEntityGroupingSystem.h.
Referenced by TEntityGroupingHandlerImpl(), OnObjectsReplaced(), and VisitLinkedEntities().
The documentation for this struct was generated from the following file:
Runtime/MovieScene/Public/EntitySystem/MovieSceneEntityGroupingSystem.h