Unreal Engine 5.6 C++ API: UE::Math::TMatrix< T > Struct Template Reference
UE::Math::TMatrix< T > Struct Template Reference
#include "Matrix.h"
Public Types
using FReal = T
Public Member Functions
TMatrix ()=default
template<typename FArg UE_REQUIRES>
TMatrix (const TMatrix< FArg > &From)
FORCEINLINE TMatrix (const TPlane< T > &InX, const TPlane< T > &InY, const TPlane< T > &InZ, const TPlane< T > &InW)
Constructor.
FORCEINLINE TMatrix (const TVector< T > &InX, const TVector< T > &InY, const TVector< T > &InZ, const TVector< T > &InW)
Constructor.
FORCEINLINE TMatrix (EForceInit)
Constructor.
TMatrix< T > ApplyScale (T Scale) const
Apply Scale to this matrix.
uint32 ComputeHash () const
For debugging purpose, could be changed.
TMatrix< T > ConcatTranslation (const TVector< T > &Translation) const
Returns a matrix with an additional translation concatenated.
bool ContainsNaN () const
Returns true if any element of this matrix is NaN.
void DebugPrint () const
Output ToString.
T Determinant () const
FORCEINLINE void DiagnosticCheckNaN () const
bool Equals (const TMatrix< T > &Other, T Tolerance=UE_KINDA_SMALL_NUMBER) const
Checks whether another Matrix is equal to this, within specified tolerance.
TVector< T > ExtractScaling (T Tolerance=UE_SMALL_NUMBER)
Remove any scaling from this matrix (ie magnitude of each row is 1) and return the 3D scale vector that was initially present with error Tolerance.
TVector< T > GetColumn (int32 i) const
get a column of this matrix
FORCEINLINE bool GetFrustumBottomPlane (TPlane< T > &OuTPln) const
FORCEINLINE bool GetFrustumFarPlane (TPlane< T > &OuTPln) const
FORCEINLINE bool GetFrustumLeftPlane (TPlane< T > &OuTPln) const
FORCEINLINE bool GetFrustumNearPlane (TPlane< T > &OuTPln) const
FORCEINLINE bool GetFrustumRightPlane (TPlane< T > &OuTPln) const
FORCEINLINE bool GetFrustumTopPlane (TPlane< T > &OuTPln) const
TMatrix< T > GetMatrixWithoutScale (T Tolerance=UE_SMALL_NUMBER) const
T GetMaximumAxisScale () const
T GetMinimumAxisScale () const
TVector< T > GetOrigin () const
void GetScaledAxes (TVector< T > &X, TVector< T > &Y, TVector< T > &Z) const
get axes of this matrix scaled by the scale of the matrix
TVector< T > GetScaledAxis (EAxis::Type Axis) const
get axis of this matrix scaled by the scale of the matrix
TVector< T > GetScaleVector (T Tolerance=UE_SMALL_NUMBER) const
return a 3D scale vector calculated from this matrix (where each component is the magnitude of a row vector) with error Tolerance.
FORCEINLINE TMatrix< T > GetTransposed () const
void GetUnitAxes (TVector< T > &X, TVector< T > &Y, TVector< T > &Z) const
get unit length axes of this matrix
TVector< T > GetUnitAxis (EAxis::Type Axis) const
get unit length axis of this matrix
TMatrix< T > Inverse () const
Get the inverse of this matrix.
TMatrix< T > InverseFast () const
Get the inverse of this matrix.
FORCEINLINE TVector< T > InverseTransformPosition (const TVector< T > &V) const
Inverts the matrix and then transforms V - correctly handles scaling in this matrix.
FORCEINLINE TVector< T > InverseTransformVector (const TVector< T > &V) const
Transform a direction vector by the inverse of this matrix - will not take into account translation part.
void Mirror (EAxis::Type MirrorAxis, EAxis::Type FlipAxis)
Utility for mirroring this transform across a certain plane, and flipping one of the axis as well.
bool operator!= (const TMatrix< T > &Other) const
Checks whether another Matrix is not equal to this, within specified tolerance.
FORCEINLINE TMatrix< T > operator* (const TMatrix< T > &Other) const
Gets the result of multiplying a Matrix to this.
FORCEINLINE TMatrix< T > operator* (T Other) const
This isn't applying SCALE, just multiplying the value to all members - i.e.
FORCEINLINE void operator*= (const TMatrix< T > &Other)
Multiply this by a matrix.
FORCEINLINE void operator*= (T Other)
Multiply this matrix by a weighting factor.
FORCEINLINE TMatrix< T > operator+ (const TMatrix< T > &Other) const
Gets the result of adding a matrix to this.
FORCEINLINE void operator+= (const TMatrix< T > &Other)
Adds to this matrix.
bool operator== (const TMatrix< T > &Other) const
Checks whether two matrix are identical.
void RemoveScaling (T Tolerance=UE_SMALL_NUMBER)
TMatrix< T > RemoveTranslation () const
UE::Math::TRotator< T > Rotator () const
T RotDeterminant () const
void ScaleTranslation (const TVector< T > &Scale3D)
Scale the translation part of the matrix by the supplied vector.
bool Serialize (FArchive &Ar)
bool SerializeFromMismatchedTag (FName StructTag, FArchive &Ar)
void SetAxes (const TVector< T > *Axis0=NULL, const TVector< T > *Axis1=NULL, const TVector< T > *Axis2=NULL, const TVector< T > *Origin=NULL)
Update the axes of the matrix if any value is NULL do not update that axis.
void SetAxis (int32 i, const TVector< T > &Axis)
set an axis of this matrix
void SetColumn (int32 i, TVector< T > Value)
Set a column of this matrix.
void SetIdentity ()
void SetOrigin (const TVector< T > &NewOrigin)
FORCEINLINE void To3x4MatrixTranspose (T *Out) const
Convert this Atom to the 3x4 transpose of the transformation matrix.
UE::Math::TQuat< T > ToQuat () const
Transform a rotation matrix into a quaternion.
FString ToString () const
Get a textual representation of the vector.
FORCEINLINE TVector4< T > TransformFVector4 (const TVector4< T > &V) const
FORCEINLINE TVector4< T > TransformPosition (const TVector< T > &V) const
Transform a location - will take into account translation part of the TMatrix<T>.
FORCEINLINE TVector4< T > TransformVector (const TVector< T > &V) const
Transform a direction vector - will not take into account translation part of the TMatrix<T>.
TMatrix< T > TransposeAdjoint () const
Data Fields
T M [4][4]
Static Public Attributes
static const TMatrix Identity
Static Private Member Functions
static void ErrorEnsure (const TCHAR *Message)
Output an error message and trigger an ensure.
Detailed Description
template<typename T>
struct UE::Math::TMatrix< T >
Definition at line 42 of file Matrix.h.
Member Typedef Documentation
FReal
template<typename T> using UE::Math::TMatrix< T >::FReal = T
Definition at line 47 of file Matrix.h.
Constructor & Destructor Documentation
TMatrix() [1/5]
template<typename T> UE::Math::TMatrix< T >::TMatrix () nodiscard default
Referenced by UE::Math::TBasisVectorMatrix< T >::TBasisVectorMatrix(), UE::Math::TClipProjectionMatrix< T >::TClipProjectionMatrix(), UE::Math::TClipProjectionMatrix< T >::TClipProjectionMatrix(), UE::Math::TInverseRotationMatrix< T >::TInverseRotationMatrix(), UE::Math::TInverseRotationMatrix< T >::TInverseRotationMatrix(), UE::Math::TLookFromMatrix< T >::TLookFromMatrix(), UE::Math::TMirrorMatrix< T >::TMirrorMatrix(), UE::Math::TOrthoMatrix< T >::TOrthoMatrix(), UE::Math::TOrthoMatrix< T >::TOrthoMatrix(), UE::Math::TPerspectiveMatrix< T >::TPerspectiveMatrix(), UE::Math::TPerspectiveMatrix< T >::TPerspectiveMatrix(), UE::Math::TPerspectiveMatrix< T >::TPerspectiveMatrix(), UE::Math::TPerspectiveMatrix< T >::TPerspectiveMatrix(), UE::Math::TQuatRotationTranslationMatrix< T >::TQuatRotationTranslationMatrix(), UE::Math::TReversedZOrthoMatrix< T >::TReversedZOrthoMatrix(), UE::Math::TReversedZOrthoMatrix< T >::TReversedZOrthoMatrix(), UE::Math::TReversedZOrthoMatrix< T >::TReversedZOrthoMatrix(), UE::Math::TReversedZPerspectiveMatrix< T >::TReversedZPerspectiveMatrix(), UE::Math::TReversedZPerspectiveMatrix< T >::TReversedZPerspectiveMatrix(), UE::Math::TReversedZPerspectiveMatrix< T >::TReversedZPerspectiveMatrix(), UE::Math::TReversedZPerspectiveMatrix< T >::TReversedZPerspectiveMatrix(), UE::Math::TRotationTranslationMatrix< T >::TRotationTranslationMatrix(), UE::Math::TScaleMatrix< T >::TScaleMatrix(), UE::Math::TScaleMatrix< T >::TScaleMatrix(), UE::Math::TScaleMatrix< T >::TScaleMatrix(), UE::Math::TScaleRotationTranslationMatrix< T >::TScaleRotationTranslationMatrix(), UE::Math::TTranslationMatrix< T >::TTranslationMatrix(), UE::Math::TTranslationMatrix< T >::TTranslationMatrix(), UE::Math::TQuatRotationTranslationMatrix< T >::Make(), UE::Math::TRotationTranslationMatrix< T >::Make(), UE::Math::TScaleMatrix< T >::Make(), UE::Math::TScaleMatrix< T >::Make(), and UE::Math::TTranslationMatrix< T >::Make().
TMatrix() [2/5]
template<typename T> FORCEINLINE UE::Math::TMatrix< T >::TMatrix (EForceInit) inline explicit nodiscard
Constructor.
Parameters
EForceInit Force Init Enum.
Definition at line 77 of file Matrix.h.
TMatrix() [3/5]
template<typename T> FORCEINLINE UE::Math::TMatrix< T >::TMatrix (const TPlane< T > & InX, const TPlane< T > & InY, const TPlane< T > & InZ, const TPlane< T > & InW) nodiscard
Constructor.
Parameters
InX X plane
InY Y plane
InZ Z plane
InW W plane
TMatrix() [4/5]
template<typename T> FORCEINLINE UE::Math::TMatrix< T >::TMatrix (const TVector< T > & InX, const TVector< T > & InY, const TVector< T > & InZ, const TVector< T > & InW) nodiscard
Constructor.
Parameters
InX X vector
InY Y vector
InZ Z vector
InW W vector
TMatrix() [5/5]
template<typename T> template<typename FArg UE_REQUIRES> UE::Math::TMatrix< T >::TMatrix (const TMatrix< FArg > & From) inline explicit
Definition at line 424 of file Matrix.h.
Member Function Documentation
ApplyScale()
template<typename T> TMatrix< T > UE::Math::TMatrix< T >::ApplyScale (T Scale) const inline nodiscard
Apply Scale to this matrix.
ComputeHash()
template<typename T> uint32 UE::Math::TMatrix< T >::ComputeHash () const inline nodiscard
For debugging purpose, could be changed.
Definition at line 386 of file Matrix.h.
ConcatTranslation()
template<typename T> TMatrix< T > UE::Math::TMatrix< T >::ConcatTranslation (const TVector< T > & Translation) const inline nodiscard
Returns a matrix with an additional translation concatenated.
ContainsNaN()
template<typename T> bool UE::Math::TMatrix< T >::ContainsNaN () const inline nodiscard
Returns true if any element of this matrix is NaN.
Referenced by UE::Math::TBoxSphereBounds< T, TExtent >::TransformBy().
DebugPrint()
template<typename T> void UE::Math::TMatrix< T >::DebugPrint () const inline
Output ToString.
Definition at line 380 of file Matrix.h.
Determinant()
template<typename T> T UE::Math::TMatrix< T >::Determinant () const inline nodiscard
Referenced by FKelvinletBrushOp::ExtractTransform(), and UE::Math::TTransform< double >::SetFromMatrix().
DiagnosticCheckNaN()
template<typename T> FORCEINLINE void UE::Math::TMatrix< T >::DiagnosticCheckNaN () const inline
Definition at line 65 of file Matrix.h.
Referenced by UE::Math::TMatrix< double >::TMatrix(), UE::Math::operator<<(), and UE::Math::operator<<().
Equals()
template<typename T> bool UE::Math::TMatrix< T >::Equals (const TMatrix< T > & Other, T Tolerance = UE_KINDA_SMALL_NUMBER) const inline nodiscard
Checks whether another Matrix is equal to this, within specified tolerance.
Parameters
Other The other Matrix.
Tolerance Error Tolerance.
Returns
true if two Matrix are equal, within specified tolerance, otherwise false.
ErrorEnsure()
template<typename T> void UE::Math::TMatrix< T >::ErrorEnsure (const TCHAR * Message) inline static private
Output an error message and trigger an ensure.
Definition at line 466 of file Matrix.h.
ExtractScaling()
template<typename T> TVector< T > UE::Math::TMatrix< T >::ExtractScaling (T Tolerance = UE_SMALL_NUMBER) inline
Remove any scaling from this matrix (ie magnitude of each row is 1) and return the 3D scale vector that was initially present with error Tolerance.
Referenced by UE::Math::TTransform< double >::SetFromMatrix().
GetColumn()
template<typename T> TVector< T > UE::Math::TMatrix< T >::GetColumn (int32 i) const inline nodiscard
get a column of this matrix
Parameters
i index into the column of the matrix
Returns
vector of the column
GetFrustumBottomPlane()
template<typename T> FORCEINLINE bool UE::Math::TMatrix< T >::GetFrustumBottomPlane (TPlane< T > & OuTPln) const
Parameters
OuTPln the bottom plane of the Frustum of this matrix
GetFrustumFarPlane()
template<typename T> FORCEINLINE bool UE::Math::TMatrix< T >::GetFrustumFarPlane (TPlane< T > & OuTPln) const
Parameters
OuTPln the far plane of the Frustum of this matrix
GetFrustumLeftPlane()
template<typename T> FORCEINLINE bool UE::Math::TMatrix< T >::GetFrustumLeftPlane (TPlane< T > & OuTPln) const
Parameters
OuTPln the left plane of the Frustum of this matrix
GetFrustumNearPlane()
template<typename T> FORCEINLINE bool UE::Math::TMatrix< T >::GetFrustumNearPlane (TPlane< T > & OuTPln) const
Parameters
OuTPln the near plane of the Frustum of this matrix
GetFrustumRightPlane()
template<typename T> FORCEINLINE bool UE::Math::TMatrix< T >::GetFrustumRightPlane (TPlane< T > & OuTPln) const
Parameters
OuTPln the right plane of the Frustum of this matrix
GetFrustumTopPlane()
template<typename T> FORCEINLINE bool UE::Math::TMatrix< T >::GetFrustumTopPlane (TPlane< T > & OuTPln) const
Parameters
OuTPln the top plane of the Frustum of this matrix
GetMatrixWithoutScale()
template<typename T> TMatrix< T > UE::Math::TMatrix< T >::GetMatrixWithoutScale (T Tolerance = UE_SMALL_NUMBER) const inline nodiscard
GetMaximumAxisScale()
template<typename T> T UE::Math::TMatrix< T >::GetMaximumAxisScale () const inline nodiscard
Returns
the maximum magnitude of any row of the matrix.
GetMinimumAxisScale()
template<typename T> T UE::Math::TMatrix< T >::GetMinimumAxisScale () const inline nodiscard
Returns
the minimum magnitude of any row of the matrix.
GetOrigin()
template<typename T> TVector< T > UE::Math::TMatrix< T >::GetOrigin () const inline nodiscard
Referenced by UE::Math::TTransform< T >::ConstructTransformFromMatrixWithDesiredScale(), UE::Math::TTransform< double >::SetFromMatrix(), and FEditorViewportClient::SetLookAtLocation().
GetScaledAxes()
template<typename T> void UE::Math::TMatrix< T >::GetScaledAxes (TVector< T > & X, TVector< T > & Y, TVector< T > & Z) const inline
get axes of this matrix scaled by the scale of the matrix
Parameters
X axes returned to this param
Y axes returned to this param
Z axes returned to this param
GetScaledAxis()
template<typename T> TVector< T > UE::Math::TMatrix< T >::GetScaledAxis (EAxis::Type Axis) const inline nodiscard
get axis of this matrix scaled by the scale of the matrix
Parameters
i index into the axis of the matrix @ return vector of the axis
Referenced by UE::Math::TQuat< T >::TQuat(), UE::Math::TTransform< T >::ConstructTransformFromMatrixWithDesiredScale(), and UE::Math::TTransform< double >::SetFromMatrix().
GetScaleVector()
template<typename T> TVector< T > UE::Math::TMatrix< T >::GetScaleVector (T Tolerance = UE_SMALL_NUMBER) const inline nodiscard
return a 3D scale vector calculated from this matrix (where each component is the magnitude of a row vector) with error Tolerance.
GetTransposed()
template<typename T> FORCEINLINE TMatrix< T > UE::Math::TMatrix< T >::GetTransposed () const nodiscard
Referenced by FAtmosphereSetup::ComputeViewData(), and UE::Color::Transpose().
GetUnitAxes()
template<typename T> void UE::Math::TMatrix< T >::GetUnitAxes (TVector< T > & X, TVector< T > & Y, TVector< T > & Z) const inline
get unit length axes of this matrix
Parameters
X axes returned to this param
Y axes returned to this param
Z axes returned to this param
GetUnitAxis()
template<typename T> TVector< T > UE::Math::TMatrix< T >::GetUnitAxis (EAxis::Type Axis) const inline nodiscard
get unit length axis of this matrix
Parameters
i index into the axis of the matrix
Returns
vector of the axis
Referenced by FRandomStream::VRandCone(), and FRandomStream::VRandCone().
Inverse()
template<typename T> TMatrix< T > UE::Math::TMatrix< T >::Inverse () const inline nodiscard
Get the inverse of this matrix.
Will silently change nil/nan matrices to identity.
Referenced by FPrimitiveUniformShaderParametersBuilder::Build(), FParticleSystemSceneProxy::GetWorldToLocal(), FRenderTransform::Inverse(), FViewMatrices::InvertProjectionMatrix(), and UE::Math::TTransform< double >::ToInverseMatrixWithScale().
InverseFast()
template<typename T> TMatrix< T > UE::Math::TMatrix< T >::InverseFast () const inline nodiscard
Get the inverse of this matrix.
Will ensure on nil matrices in non-final builds. Not faster than Inverse.
Referenced by FRenderTransform::InverseFast(), and FEditorViewportClient::SetLookAtLocation().
InverseTransformPosition()
template<typename T> FORCEINLINE TVector< T > UE::Math::TMatrix< T >::InverseTransformPosition (const TVector< T > & V) const nodiscard
Inverts the matrix and then transforms V - correctly handles scaling in this matrix.
InverseTransformVector()
template<typename T> FORCEINLINE TVector< T > UE::Math::TMatrix< T >::InverseTransformVector (const TVector< T > & V) const nodiscard
Transform a direction vector by the inverse of this matrix - will not take into account translation part.
If you want to transform a surface normal (or plane) and correctly account for non-uniform scaling you should use TransformByUsingAdjointT with adjoint of matrix inverse.
Mirror()
template<typename T> void UE::Math::TMatrix< T >::Mirror (EAxis::Type MirrorAxis, EAxis::Type FlipAxis) inline
Utility for mirroring this transform across a certain plane, and flipping one of the axis as well.
Referenced by UE::Math::TTransform< T >::Mirror().
operator!=()
template<typename T> bool UE::Math::TMatrix< T >::operator!= (const TMatrix< T > & Other) const inline nodiscard
Checks whether another Matrix is not equal to this, within specified tolerance.
Parameters
Other The other Matrix.
Returns
true if two Matrix are not equal, within specified tolerance, otherwise false.
operator*() [1/2]
template<typename T> FORCEINLINE TMatrix< T > UE::Math::TMatrix< T >::operator* (const TMatrix< T > & Other) const nodiscard
Gets the result of multiplying a Matrix to this.
Parameters
Other The matrix to multiply this by.
Returns
The result of multiplication.
operator*() [2/2]
template<typename T> FORCEINLINE TMatrix< T > UE::Math::TMatrix< T >::operator* (T Other) const nodiscard
This isn't applying SCALE, just multiplying the value to all members - i.e.
weighting
operator*=() [1/2]
template<typename T> FORCEINLINE void UE::Math::TMatrix< T >::operator*= (const TMatrix< T > & Other)
Multiply this by a matrix.
Parameters
Other the matrix to multiply by this.
Returns
reference to this after multiply.
operator*=() [2/2]
template<typename T> FORCEINLINE void UE::Math::TMatrix< T >::operator*= (T Other)
Multiply this matrix by a weighting factor.
Parameters
other The weight.
Returns
a reference to this after weighting.
operator+()
template<typename T> FORCEINLINE TMatrix< T > UE::Math::TMatrix< T >::operator+ (const TMatrix< T > & Other) const nodiscard
Gets the result of adding a matrix to this.
Parameters
Other The Matrix to add.
Returns
The result of addition.
operator+=()
template<typename T> FORCEINLINE void UE::Math::TMatrix< T >::operator+= (const TMatrix< T > & Other)
Adds to this matrix.
Parameters
Other The matrix to add to this.
Returns
Reference to this after addition.
operator==()
template<typename T> bool UE::Math::TMatrix< T >::operator== (const TMatrix< T > & Other) const inline nodiscard
Checks whether two matrix are identical.
Parameters
Other The other matrix.
Returns
true if two matrix are identical, otherwise false.
RemoveScaling()
template<typename T> void UE::Math::TMatrix< T >::RemoveScaling (T Tolerance = UE_SMALL_NUMBER) inline
Referenced by UE::Math::TTransform< T >::ConstructTransformFromMatrixWithDesiredScale().
RemoveTranslation()
template<typename T> TMatrix< T > UE::Math::TMatrix< T >::RemoveTranslation () const inline nodiscard
Rotator()
template<typename T> UE::Math::TRotator< T > UE::Math::TMatrix< T >::Rotator () const nodiscard
Returns
rotator representation of this matrix
Referenced by FEditorViewportClient::SetLookAtLocation().
RotDeterminant()
template<typename T> T UE::Math::TMatrix< T >::RotDeterminant () const inline nodiscard
Returns
the determinant of rotation 3x3 matrix
Referenced by GetBasisDeterminantSign().
ScaleTranslation()
template<typename T> void UE::Math::TMatrix< T >::ScaleTranslation (const TVector< T > & Scale3D) inline
Scale the translation part of the matrix by the supplied vector.
Serialize()
template<typename T> bool UE::Math::TMatrix< T >::Serialize (FArchive & Ar) inline
Definition at line 400 of file Matrix.h.
SerializeFromMismatchedTag()
template<typename T> bool UE::Math::TMatrix< T >::SerializeFromMismatchedTag (FName StructTag, FArchive & Ar) inline
Definition at line 410 of file Matrix.h.
SetAxes()
template<typename T> void UE::Math::TMatrix< T >::SetAxes (const TVector< T > * Axis0 = NULL, const TVector< T > * Axis1 = NULL, const TVector< T > * Axis2 = NULL, const TVector< T > * Origin = NULL) inline
Update the axes of the matrix if any value is NULL do not update that axis.
Parameters
Axis0 set matrix row 0
Axis1 set matrix row 1
Axis2 set matrix row 2
Origin set matrix row 3
Referenced by TLumenCardOBB< float >::GetCardToLocal().
SetAxis()
template<typename T> void UE::Math::TMatrix< T >::SetAxis (int32 i, const TVector< T > & Axis) inline
set an axis of this matrix
Parameters
i index into the axis of the matrix
Axis vector of the axis
Referenced by UE::Math::TTransform< T >::ConstructTransformFromMatrixWithDesiredScale(), and UE::Math::TTransform< double >::SetFromMatrix().
SetColumn()
template<typename T> void UE::Math::TMatrix< T >::SetColumn (int32 i, TVector< T > Value) inline
Set a column of this matrix.
Parameters
i index of the matrix column
Value new value of the column
Referenced by FAtmosphereSetup::ComputeViewData().
SetIdentity()
template<typename T> void UE::Math::TMatrix< T >::SetIdentity () inline
Referenced by TLumenCardOBB< float >::GetCardToLocal().
SetOrigin()
template<typename T> void UE::Math::TMatrix< T >::SetOrigin (const TVector< T > & NewOrigin) inline
To3x4MatrixTranspose()
template<typename T> FORCEINLINE void UE::Math::TMatrix< T >::To3x4MatrixTranspose (T * Out) const
Convert this Atom to the 3x4 transpose of the transformation matrix.
ToQuat()
template<typename T> UE::Math::TQuat< T > UE::Math::TMatrix< T >::ToQuat () const nodiscard
Transform a rotation matrix into a quaternion.
Warning
rotation part will need to be unit length for this to be right!
ToString()
template<typename T> FString UE::Math::TMatrix< T >::ToString () const inline nodiscard
Get a textual representation of the vector.
Returns
Text describing the vector.
Definition at line 367 of file Matrix.h.
Referenced by UE::Math::TMatrix< double >::DebugPrint(), DisplayClusterTypesConverter::ToString(), and UE::Math::TBoxSphereBounds< T, TExtent >::TransformBy().
TransformFVector4()
template<typename T> FORCEINLINE TVector4< T > UE::Math::TMatrix< T >::TransformFVector4 (const TVector4< T > & V) const nodiscard
TransformPosition()
template<typename T> FORCEINLINE TVector4< T > UE::Math::TMatrix< T >::TransformPosition (const TVector< T > & V) const nodiscard
Transform a location - will take into account translation part of the TMatrix<T>.
Referenced by TkDOPLineCollisionCheck< COLL_DATA_PROVIDER, KDOP_IDX_TYPE >::TkDOPLineCollisionCheck(), FViewMatrices::ComputeHalfFieldOfViewPerAxis(), TLumenCardOBB< float >::Transform(), UE::Math::TSphere< T >::TransformBy(), UE::Math::TBox< T >::TransformProjectBy(), and FPlanarReflectionSceneProxy::UpdateTransform().
TransformVector()
template<typename T> FORCEINLINE TVector4< T > UE::Math::TMatrix< T >::TransformVector (const TVector< T > & V) const nodiscard
Transform a direction vector - will not take into account translation part of the TMatrix<T>.
If you want to transform a surface normal (or plane) and correctly account for non-uniform scaling you should use TransformByUsingAdjointT.
Referenced by TLumenCardOBB< float >::Transform(), and FPlanarReflectionSceneProxy::UpdateTransform().
TransposeAdjoint()
template<typename T> TMatrix< T > UE::Math::TMatrix< T >::TransposeAdjoint () const inline nodiscard
Field Documentation
Identity
template<typename T> const TMatrix UE::Math::TMatrix< T >::Identity static
Definition at line 52 of file Matrix.h.
M
template<typename T> T UE::Math::TMatrix< T >::M[4][4]
Definition at line 49 of file Matrix.h.
Referenced by FRenderTransform::FRenderTransform(), FRenderTransform::FRenderTransform(), UE::Math::TClipProjectionMatrix< T >::TClipProjectionMatrix(), UE::Math::TMatrix< double >::TMatrix(), UE::Math::TQuat< T >::TQuat(), UE::Math::TQuatRotationTranslationMatrix< T >::TQuatRotationTranslationMatrix(), UE::Math::TRotationAboutPointMatrix< T >::TRotationAboutPointMatrix(), UE::Math::TRotationTranslationMatrix< T >::TRotationTranslationMatrix(), UE::Math::TScaleRotationTranslationMatrix< T >::TScaleRotationTranslationMatrix(), FViewMatrices::ComputeProjectionNoAAMatrix(), FKelvinletBrushOp::ExtractTransform(), FViewMatrices::InvertProjectionMatrix(), MS_ALIGN(), UE::Math::operator<<(), UE::Math::operator<<(), FRenderTransform::operator=(), FRenderTransform::operator=(), DisplayClusterTypesConverter::ToHexString(), UE::Math::TTransform< double >::ToMatrixNoScale(), UE::Math::TTransform< double >::ToMatrixWithScale(), UE::Math::TBox< T >::TransformBy(), UE::Math::TBoxSphereBounds< T, TExtent >::TransformBy(), and UE::Math::TSphere< T >::TransformBy().
The documentation for this struct was generated from the following files:
Runtime/Core/Public/Math/MathFwd.h
Runtime/Core/Public/Math/Matrix.h