Unreal Engine 5.6 C++ API: FTransactionObjectId Struct Reference
FTransactionObjectId Struct Reference
ID for an object that was transacted.
#include "TransactionObjectEvent.h"
Public Member Functions
FTransactionObjectId ()=default
FTransactionObjectId (const FName InObjectPackageName, const FName InObjectName, const FName InObjectPathName, const FName InObjectOuterPathName, const FName InObjectExternalPackageName, const FName InObjectClassPathName)
FTransactionObjectId (const UObject *Object)
void Reset ()
void SetObject (const UObject *Object)
void Swap (FTransactionObjectId &Other)
Data Fields
FName ObjectClassPathName
The path name of the object's class.
FName ObjectExternalPackageName
The external package name of the object, if any.
FName ObjectName
The name of the object.
FName ObjectOuterPathName
The outer path name of the object.
FName ObjectPackageName
The package name of the object, can be dictated either by outer chain or external package.
FName ObjectPathName
The path name of the object.
Friends
uint32 GetTypeHash (const FTransactionObjectId &Id)
bool operator!= (const FTransactionObjectId &LHS, const FTransactionObjectId &RHS)
bool operator== (const FTransactionObjectId &LHS, const FTransactionObjectId &RHS)
Detailed Description
ID for an object that was transacted.
Definition at line 61 of file TransactionObjectEvent.h.
Constructor & Destructor Documentation
FTransactionObjectId() [1/3]
FTransactionObjectId::FTransactionObjectId () default
Referenced by GetTypeHash, operator!=, operator==, and Swap().
FTransactionObjectId() [2/3]
FTransactionObjectId::FTransactionObjectId (const UObject * Object) inline explicit
Definition at line 66 of file TransactionObjectEvent.h.
References Object, and SetObject().
FTransactionObjectId() [3/3]
FTransactionObjectId::FTransactionObjectId (const FName InObjectPackageName, const FName InObjectName, const FName InObjectPathName, const FName InObjectOuterPathName, const FName InObjectExternalPackageName, const FName InObjectClassPathName) inline
Definition at line 71 of file TransactionObjectEvent.h.
References ObjectClassPathName, ObjectExternalPackageName, ObjectName, ObjectOuterPathName, ObjectPackageName, and ObjectPathName.
Member Function Documentation
Reset()
void FTransactionObjectId::Reset () inline
Definition at line 83 of file TransactionObjectEvent.h.
References FName, ObjectClassPathName, ObjectExternalPackageName, ObjectName, ObjectOuterPathName, ObjectPackageName, and ObjectPathName.
Referenced by UE::Transaction::FSerializedObjectInfo::Reset().
SetObject()
void FTransactionObjectId::SetObject (const UObject * Object)
References Object.
Referenced by FTransactionObjectId(), and UE::Transaction::FSerializedObjectInfo::SetObject().
Swap()
void FTransactionObjectId::Swap (FTransactionObjectId & Other) inline
Definition at line 93 of file TransactionObjectEvent.h.
References FTransactionObjectId(), Exchange(), ObjectClassPathName, ObjectExternalPackageName, ObjectName, ObjectOuterPathName, ObjectPackageName, ObjectPathName, and Other.
Referenced by UE::Transaction::FSerializedObjectInfo::Swap().
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FTransactionObjectId & Id) friend
Definition at line 116 of file TransactionObjectEvent.h.
References FTransactionObjectId(), GetTypeHash, and ObjectPathName.
Referenced by GetTypeHash.
operator!=
bool operator!= (const FTransactionObjectId & LHS, const FTransactionObjectId & RHS) friend
Definition at line 111 of file TransactionObjectEvent.h.
References FTransactionObjectId().
operator==
bool operator== (const FTransactionObjectId & LHS, const FTransactionObjectId & RHS) friend
Definition at line 103 of file TransactionObjectEvent.h.
References FTransactionObjectId(), ObjectClassPathName, ObjectExternalPackageName, and ObjectPathName.
Field Documentation
ObjectClassPathName
FName FTransactionObjectId::ObjectClassPathName
The path name of the object's class.
Definition at line 137 of file TransactionObjectEvent.h.
Referenced by FTransactionObjectId(), operator==, Reset(), and Swap().
ObjectExternalPackageName
FName FTransactionObjectId::ObjectExternalPackageName
The external package name of the object, if any.
Definition at line 134 of file TransactionObjectEvent.h.
Referenced by FTransactionObjectId(), operator==, Reset(), and Swap().
ObjectName
FName FTransactionObjectId::ObjectName
The name of the object.
Definition at line 125 of file TransactionObjectEvent.h.
Referenced by FTransactionObjectId(), Reset(), and Swap().
ObjectOuterPathName
FName FTransactionObjectId::ObjectOuterPathName
The outer path name of the object.
Definition at line 131 of file TransactionObjectEvent.h.
Referenced by FTransactionObjectId(), Reset(), and Swap().
ObjectPackageName
FName FTransactionObjectId::ObjectPackageName
The package name of the object, can be dictated either by outer chain or external package.
Definition at line 122 of file TransactionObjectEvent.h.
Referenced by FTransactionObjectId(), Reset(), and Swap().
ObjectPathName
FName FTransactionObjectId::ObjectPathName
The path name of the object.
Definition at line 128 of file TransactionObjectEvent.h.
Referenced by FTransactionObjectId(), GetTypeHash, operator==, Reset(), and Swap().
The documentation for this struct was generated from the following file:
Runtime/CoreUObject/Public/Misc/TransactionObjectEvent.h