Unreal Engine 5.6 C++ API: UE::MovieScene::FPropertyRecomposerPropertyInfo Struct Reference
UE::MovieScene::FPropertyRecomposerPropertyInfo Struct Reference
#include "MovieScenePropertyComponentHandler.h"
Static Public Member Functions
static FPropertyRecomposerPropertyInfo Invalid ()
Data Fields
uint16 BlendChannel = INVALID_BLEND_CHANNEL
UMovieSceneBlenderSystem * BlenderSystem = nullptr
FMovieSceneEntityID PropertyEntityID
Static Public Attributes
static constexpr uint16 INVALID_BLEND_CHANNEL = uint16(-1)
Detailed Description
Definition at line 797 of file MovieScenePropertyComponentHandler.h.
Member Function Documentation
Invalid()
FPropertyRecomposerPropertyInfo UE::MovieScene::FPropertyRecomposerPropertyInfo::Invalid () inline static
Definition at line 805 of file MovieScenePropertyComponentHandler.h.
References UE::MovieScene::FMovieSceneEntityID::Invalid(), and INVALID_BLEND_CHANNEL.
Field Documentation
BlendChannel
uint16 UE::MovieScene::FPropertyRecomposerPropertyInfo::BlendChannel = INVALID_BLEND_CHANNEL
Definition at line 801 of file MovieScenePropertyComponentHandler.h.
BlenderSystem
UMovieSceneBlenderSystem* UE::MovieScene::FPropertyRecomposerPropertyInfo::BlenderSystem = nullptr
Definition at line 802 of file MovieScenePropertyComponentHandler.h.
INVALID_BLEND_CHANNEL
uint16 UE::MovieScene::FPropertyRecomposerPropertyInfo::INVALID_BLEND_CHANNEL = uint16(-1) static constexpr
Definition at line 799 of file MovieScenePropertyComponentHandler.h.
Referenced by Invalid(), and UE::MovieScene::FPropertyRecomposerImpl::RecomposeBlendOperational().
PropertyEntityID
FMovieSceneEntityID UE::MovieScene::FPropertyRecomposerPropertyInfo::PropertyEntityID
Definition at line 803 of file MovieScenePropertyComponentHandler.h.
The documentation for this struct was generated from the following file:
Runtime/MovieScene/Public/EntitySystem/MovieScenePropertyComponentHandler.h