Unreal Engine 5.6 C++ API: FRDGBuilder::FCollectResourceOp Struct Reference
FRDGBuilder::FCollectResourceOp Struct Reference
Public Types
enum class EOp : uint8 { Allocate , Deallocate }
Public Member Functions
FCollectResourceOp ()=default
FCollectResourceOp (uint32 InResourceIndex, ERDGViewableResourceType InResourceType, EOp InOp)
FRDGBufferHandle GetBufferHandle () const
EOp GetOp () const
ERDGViewableResourceType GetResourceType () const
FRDGTextureHandle GetTextureHandle () const
Static Public Member Functions
static FCollectResourceOp Allocate (FRDGBufferHandle BufferHandle)
static FCollectResourceOp Allocate (FRDGTextureHandle TextureHandle)
static FCollectResourceOp Deallocate (FRDGBufferHandle BufferHandle)
static FCollectResourceOp Deallocate (FRDGTextureHandle TextureHandle)
Data Fields
uint32 Op: 1
uint32 ResourceIndex: 30
uint32 ResourceType: 1
Detailed Description
Definition at line 600 of file RenderGraphBuilder.h.
Member Enumeration Documentation
EOp
enum class FRDGBuilder::FCollectResourceOp::EOp : uint8 strong
Enumerator
Allocate
Deallocate
Definition at line 602 of file RenderGraphBuilder.h.
Constructor & Destructor Documentation
FCollectResourceOp() [1/2]
FRDGBuilder::FCollectResourceOp::FCollectResourceOp () default
Referenced by Allocate(), Allocate(), Deallocate(), and Deallocate().
FCollectResourceOp() [2/2]
FRDGBuilder::FCollectResourceOp::FCollectResourceOp (uint32 InResourceIndex, ERDGViewableResourceType InResourceType, EOp InOp) inline
Definition at line 629 of file RenderGraphBuilder.h.
References Op, ResourceIndex, and ResourceType.
Member Function Documentation
Allocate() [1/2]
FCollectResourceOp FRDGBuilder::FCollectResourceOp::Allocate (FRDGBufferHandle BufferHandle) inline static
Definition at line 608 of file RenderGraphBuilder.h.
References FCollectResourceOp(), Allocate, Buffer, and TRDGHandle< LocalObjectType, LocalIndexType >::GetIndex().
Allocate() [2/2]
FCollectResourceOp FRDGBuilder::FCollectResourceOp::Allocate (FRDGTextureHandle TextureHandle) inline static
Definition at line 613 of file RenderGraphBuilder.h.
References FCollectResourceOp(), Allocate, TRDGHandle< LocalObjectType, LocalIndexType >::GetIndex(), and Texture.
Deallocate() [1/2]
FCollectResourceOp FRDGBuilder::FCollectResourceOp::Deallocate (FRDGBufferHandle BufferHandle) inline static
Definition at line 618 of file RenderGraphBuilder.h.
References FCollectResourceOp(), Buffer, Deallocate, and TRDGHandle< LocalObjectType, LocalIndexType >::GetIndex().
Deallocate() [2/2]
FCollectResourceOp FRDGBuilder::FCollectResourceOp::Deallocate (FRDGTextureHandle TextureHandle) inline static
Definition at line 623 of file RenderGraphBuilder.h.
References FCollectResourceOp(), Deallocate, TRDGHandle< LocalObjectType, LocalIndexType >::GetIndex(), and Texture.
GetBufferHandle()
FRDGBufferHandle FRDGBuilder::FCollectResourceOp::GetBufferHandle () const inline
Definition at line 651 of file RenderGraphBuilder.h.
References Buffer, check, GetResourceType(), and ResourceIndex.
GetOp()
EOp FRDGBuilder::FCollectResourceOp::GetOp () const inline
Definition at line 635 of file RenderGraphBuilder.h.
References Op.
GetResourceType()
ERDGViewableResourceType FRDGBuilder::FCollectResourceOp::GetResourceType () const inline
Definition at line 640 of file RenderGraphBuilder.h.
References ResourceType.
Referenced by GetBufferHandle(), and GetTextureHandle().
GetTextureHandle()
FRDGTextureHandle FRDGBuilder::FCollectResourceOp::GetTextureHandle () const inline
Definition at line 645 of file RenderGraphBuilder.h.
References check, GetResourceType(), ResourceIndex, and Texture.
Field Documentation
Op
uint32 FRDGBuilder::FCollectResourceOp::Op
Definition at line 659 of file RenderGraphBuilder.h.
Referenced by FCollectResourceOp(), and GetOp().
ResourceIndex
uint32 FRDGBuilder::FCollectResourceOp::ResourceIndex
Definition at line 657 of file RenderGraphBuilder.h.
Referenced by FCollectResourceOp(), GetBufferHandle(), and GetTextureHandle().
ResourceType
uint32 FRDGBuilder::FCollectResourceOp::ResourceType
Definition at line 658 of file RenderGraphBuilder.h.
Referenced by FCollectResourceOp(), and GetResourceType().
The documentation for this struct was generated from the following file:
Runtime/RenderCore/Public/RenderGraphBuilder.h