Unreal Engine 5.6 C++ API: FBase64 Struct Reference
FBase64 Struct Reference
Class for encoding/decoding Base64 data (RFC 4648)
#include "Base64.h"
Static Public Member Functions
template<typename CharType>
static bool Decode (const CharType *Source, uint32 Length, uint8 *Dest, EBase64Mode Mode=EBase64Mode::Standard)
Decodes a Base64 string into a preallocated buffer.
static bool Decode (const FString &Source, FString &OutDest, EBase64Mode Mode=EBase64Mode::Standard)
Decodes a Base64 string into a FString.
static bool Decode (const FString &Source, TArray< uint8 > &Dest, EBase64Mode Mode=EBase64Mode::Standard)
Decodes a Base64 string into an array of bytes.
static FString Encode (const FString &Source, EBase64Mode Mode=EBase64Mode::Standard)
Encodes a FString into a Base64 string.
static FString Encode (const TArray< uint8 > &Source, EBase64Mode Mode=EBase64Mode::Standard)
Encodes a binary uint8 array into a Base64 string.
template<typename CharType>
static uint32 Encode (const uint8 *Source, uint32 Length, CharType *Dest, EBase64Mode Mode=EBase64Mode::Standard)
Encodes the source into a Base64 string, storing it in a preallocated buffer.
static FString Encode (const uint8 *Source, uint32 Length, EBase64Mode Mode=EBase64Mode::Standard)
Encodes the source into a Base64 string.
template<typename CharType>
static uint32 GetDecodedDataSize (const CharType *Source, uint32 Length)
Determine the decoded data size for the incoming base64 encoded string.
static uint32 GetDecodedDataSize (const FString &Source)
Determine the decoded data size for the incoming base64 encoded string.
static constexpr uint32 GetEncodedDataSize (uint32 NumBytes)
Get the encoded data size for the given number of bytes.
static constexpr uint32 GetMaxDecodedDataSize (uint32 NumChars)
Get the maximum decoded data size for the given number of input characters.
Detailed Description
Class for encoding/decoding Base64 data (RFC 4648)
Definition at line 22 of file Base64.h.
Member Function Documentation
Decode() [1/3]
template<typename CharType> bool FBase64::Decode (const CharType * Source, uint32 Length, uint8 * Dest, EBase64Mode Mode = EBase64Mode::Standard) static
Decodes a Base64 string into a preallocated buffer.
Parameters
Source The Base64 encoded string
Length Length of the Base64 encoded string
Dest Buffer to receive the decoded data. Must be large enough to contain the entire output data (see GetDecodedDataSize()). Can point to the same buffer as Source
Mode The mode to use for decoding. Default is EBase64Mode::Standard
Returns
true if the buffer was decoded, false if it was invalid.
References Source, and Standard.
Decode() [2/3]
bool FBase64::Decode (const FString & Source, FString & OutDest, EBase64Mode Mode = EBase64Mode::Standard) static
Decodes a Base64 string into a FString.
Parameters
Source The Base64 encoded string
OutDest Receives the decoded string data
Mode The mode to use for decoding. Default is EBase64Mode::Standard
Returns
true if the buffer was decoded, false if it was invalid.
References Source, and Standard.
Referenced by KeyChainUtilities::LoadKeyChainFromFile(), and KeyChainUtilities::ParseRSAKeyFromJson().
Decode() [3/3]
bool FBase64::Decode (const FString & Source, TArray< uint8 > & Dest, EBase64Mode Mode = EBase64Mode::Standard) static
Decodes a Base64 string into an array of bytes.
Parameters
Source The Base64 encoded string
Dest Array to receive the decoded data
Mode The mode to use for decoding. Default is EBase64Mode::Standard
Returns
true if the buffer was decoded, false if it was invalid.
References Source, and Standard.
Encode() [1/4]
FString FBase64::Encode (const FString & Source, EBase64Mode Mode = EBase64Mode::Standard) static
Encodes a FString into a Base64 string.
Parameters
Source The string data to convert
Mode The mode to use for encoding. Default is EBase64Mode::Standard
Returns
A string that encodes the binary data in a way that can be safely transmitted via various Internet protocols
References Source, and Standard.
Referenced by FCSPose< PoseType >::CalculateComponentSpaceTransform().
Encode() [2/4]
FString FBase64::Encode (const TArray< uint8 > & Source, EBase64Mode Mode = EBase64Mode::Standard) static
Encodes a binary uint8 array into a Base64 string.
Parameters
Source The binary data to convert
Mode The mode to use for encoding. Default is EBase64Mode::Standard
Returns
A string that encodes the binary data in a way that can be safely transmitted via various Internet protocols
References Source, and Standard.
Encode() [3/4]
template<typename CharType> uint32 FBase64::Encode (const uint8 * Source, uint32 Length, CharType * Dest, EBase64Mode Mode = EBase64Mode::Standard) static
Encodes the source into a Base64 string, storing it in a preallocated buffer.
Parameters
Source The binary data to encode
Length Length of the binary data to be encoded
Dest Buffer to receive the encoded data. Must be large enough to contain the entire output data (see GetEncodedDataSize()). Can point to the same buffer as Source
Mode The mode to use for encoding. Default is EBase64Mode::Standard
Returns
The length of the encoded data
References Source, and Standard.
Encode() [4/4]
FString FBase64::Encode (const uint8 * Source, uint32 Length, EBase64Mode Mode = EBase64Mode::Standard) static
Encodes the source into a Base64 string.
Parameters
Source The binary data to encode
Length Length of the binary data to be encoded
Mode The mode to use for encoding. Default is EBase64Mode::Standard
Returns
Base64 encoded string containing the binary data.
References Source, and Standard.
GetDecodedDataSize() [1/2]
template<typename CharType> uint32 FBase64::GetDecodedDataSize (const CharType * Source, uint32 Length) static
Determine the decoded data size for the incoming base64 encoded string.
Parameters
Source The Base64 encoded string
Length Length of the Base64 encoded string
Returns
The size in bytes of the decoded data
References Source.
GetDecodedDataSize() [2/2]
uint32 FBase64::GetDecodedDataSize (const FString & Source) static
Determine the decoded data size for the incoming base64 encoded string.
Parameters
Source The Base64 encoded string
Returns
The size in bytes of the decoded data
References Source.
GetEncodedDataSize()
constexpr uint32 FBase64::GetEncodedDataSize (uint32 NumBytes) inline static constexpr
Get the encoded data size for the given number of bytes.
Parameters
NumBytes The number of bytes of input
Returns
The number of characters in the encoded data.
Definition at line 75 of file Base64.h.
GetMaxDecodedDataSize()
constexpr uint32 FBase64::GetMaxDecodedDataSize (uint32 NumChars) inline static constexpr
Get the maximum decoded data size for the given number of input characters.
Parameters
Length The number of input characters.
Returns
The maximum number of bytes that can be decoded from this input stream. The actual number of characters decoded may be less if the data contains padding characters. Call GetDecodedDataSize() with the input data to find the exact length.
Definition at line 142 of file Base64.h.
The documentation for this struct was generated from the following file:
Runtime/Core/Public/Misc/Base64.h