Unreal Engine 5.6 C++ API: FFrameRate Struct Reference
FFrameRate Struct Reference
A frame rate represented as a fraction comprising 2 integers: a numerator (number of frames), and a denominator (per second)
#include "FrameRate.h"
Public Member Functions
FFrameRate ()
Default construction to a frame rate of 60000 frames per second (0.0166 ms)
FFrameRate (uint32 InNumerator, uint32 InDenominator)
double AsDecimal () const
Get the decimal representation of this framerate.
FFrameNumber AsFrameNumber (double InTimeSeconds) const
Convert the specified time in seconds to a frame number by rounding down to the nearest integer.
FFrameTime AsFrameTime (double InTimeSeconds) const
Convert the specified time in seconds to a frame number by rounding down to the nearest integer.
double AsInterval () const
Get the decimal representation of this framerate's interval.
double AsSeconds (FFrameTime FrameNumber) const
Convert the specified frame number to a floating-point number of seconds based on this framerate.
bool ComputeGridSpacing (const float PixelsPerSecond, double &OutMajorInterval, int32 &OutMinorDivisions, float MinTickPx=30.f, float DesiredMajorTickPx=120.f) const
Compute a desirable grid spacing for the specified screen units.
bool IsFactorOf (FFrameRate Other) const
Check whether this frame rate is a factor of another.
bool IsMultipleOf (FFrameRate Other) const
Check whether this frame rate is a multiple of another.
bool IsValid () const
Verify that this frame rate is valid to use.
double MaxSeconds () const
Get the maximum number of seconds representable with this framerate.
FFrameRate Reciprocal () const
Get the reciprocal of this frame rate.
bool Serialize (FArchive &Ar)
FText ToPrettyText () const
Convert this frame rate to a prettified text string.
Static Public Member Functions
static FFrameTime Snap (FFrameTime SourceTime, FFrameRate SourceRate, FFrameRate SnapToRate)
Snap a time specified in one framerate, to another.
static FFrameTime TransformTime (FFrameTime SourceTime, FFrameRate SourceRate, FFrameRate DestinationRate)
Convert the specified time from one framerate to another framerate.
Data Fields
int32 Denominator
The denominator of the framerate represented as a number of frames per second (e.g.
int32 Numerator
IMPORTANT: If you change the struct data, ensure that you also update the version in NoExportTypes.h.
Friends
uint32 GetTypeHash (const FFrameRate &Rate)
bool operator!= (const FFrameRate &A, const FFrameRate &B)
FFrameTime operator* (double TimeInSeconds, FFrameRate Rate)
FFrameRate operator* (FFrameRate A, FFrameRate B)
FFrameTime operator* (float TimeInSeconds, FFrameRate Rate)
TRange< double > operator/ (const TRange< FFrameNumber > &FrameRange, FFrameRate Rate)
double operator/ (FFrameNumber Frame, FFrameRate Rate)
FFrameRate operator/ (FFrameRate A, FFrameRate B)
double operator/ (FFrameTime FrameTime, FFrameRate Rate)
FArchive & operator<< (FArchive &Ar, FFrameRate &FrameRate)
bool operator== (const FFrameRate &A, const FFrameRate &B)
Detailed Description
A frame rate represented as a fraction comprising 2 integers: a numerator (number of frames), and a denominator (per second)
Definition at line 20 of file FrameRate.h.
Constructor & Destructor Documentation
FFrameRate() [1/2]
FFrameRate::FFrameRate () inline
Default construction to a frame rate of 60000 frames per second (0.0166 ms)
Definition at line 25 of file FrameRate.h.
References Denominator, and Numerator.
Referenced by GetTypeHash, IsFactorOf(), IsMultipleOf(), operator!=, operator*, operator*, operator*, operator/, operator/, operator/, operator/, operator<<, operator==, Reciprocal(), Snap(), and TransformTime().
FFrameRate() [2/2]
FFrameRate::FFrameRate (uint32 InNumerator, uint32 InDenominator) inline
Definition at line 29 of file FrameRate.h.
References Denominator, and Numerator.
Member Function Documentation
AsDecimal()
double FFrameRate::AsDecimal () const inline
Get the decimal representation of this framerate.
Returns
The number of frames per second
Definition at line 227 of file FrameRate.h.
References Denominator, and Numerator.
Referenced by FTimecode::FTimecode(), FTimecode::FromFrameNumber(), FTimecode::IsDropFormatTimecodeSupported(), operator=(), and FTimecode::ToFrameNumber().
AsFrameNumber()
FFrameNumber FFrameRate::AsFrameNumber (double InTimeSeconds) const inline
Convert the specified time in seconds to a frame number by rounding down to the nearest integer.
Parameters
InTimeSeconds The time to convert in seconds
Returns
A frame number that represents the supplied time. Rounded down to the nearest integer.
Definition at line 258 of file FrameRate.h.
References FMath::Clamp(), Denominator, and Numerator.
AsFrameTime()
FFrameTime FFrameRate::AsFrameTime (double InTimeSeconds) const inline
Convert the specified time in seconds to a frame number by rounding down to the nearest integer.
Parameters
InTimeSeconds The time to convert in seconds
Returns
A frame number that represents the supplied time. Rounded down to the nearest integer.
Definition at line 240 of file FrameRate.h.
References FMath::Clamp(), Denominator, FFrameTime::MaxSubframe, FMath::Min, Numerator, and FFrameNumber::Value.
Referenced by IAnimationDataController::ConvertSecondsToFrameNumber(), operator*, and operator*.
AsInterval()
double FFrameRate::AsInterval () const inline
Get the decimal representation of this framerate's interval.
Returns
The time in seconds for a single frame under this frame rate
Definition at line 222 of file FrameRate.h.
References Denominator, and Numerator.
Referenced by FTimecode::ToTimespan().
AsSeconds()
double FFrameRate::AsSeconds (FFrameTime FrameNumber) const inline
Convert the specified frame number to a floating-point number of seconds based on this framerate.
Parameters
FrameNumber The frame number to convert
Returns
The number of seconds that the specified frame number represents
Definition at line 232 of file FrameRate.h.
References Denominator, FFrameTime::GetFrame(), FFrameTime::GetSubFrame(), Numerator, and FFrameNumber::Value.
Referenced by IAnimationDataController::ConvertSecondsToFrameNumber(), operator/, operator/, and operator/.
ComputeGridSpacing()
bool FFrameRate::ComputeGridSpacing (const float PixelsPerSecond, double & OutMajorInterval, int32 & OutMinorDivisions, float MinTickPx = 30.f, float DesiredMajorTickPx = 120.f) const
Compute a desirable grid spacing for the specified screen units.
Parameters
PixelsPerSecond The number of pixels representing a second of time
OutMajorInterval (Out) The interval in seconds at which to draw major grid lines
OutMinorDivisions (Out) The number of divisions to draw between major tick lines
MinTickPx (Optional) The smallest size in pixels that is desirable between ticks
DesiredMajorTickPx (Optional) The desired size to compute major tick lines from
Returns
True if a valid grid spacing was computed, false otherwise.
IsFactorOf()
bool FFrameRate::IsFactorOf (FFrameRate Other) const inline
Check whether this frame rate is a factor of another.
Definition at line 320 of file FrameRate.h.
References FFrameRate(), and Other.
IsMultipleOf()
bool FFrameRate::IsMultipleOf (FFrameRate Other) const inline
Check whether this frame rate is a multiple of another.
Definition at line 312 of file FrameRate.h.
References FFrameRate(), Denominator, Numerator, and Other.
IsValid()
bool FFrameRate::IsValid () const inline
Verify that this frame rate is valid to use.
Definition at line 48 of file FrameRate.h.
References Denominator.
MaxSeconds()
double FFrameRate::MaxSeconds () const
Get the maximum number of seconds representable with this framerate.
Reciprocal()
FFrameRate FFrameRate::Reciprocal () const inline
Get the reciprocal of this frame rate.
Definition at line 147 of file FrameRate.h.
References FFrameRate(), Denominator, and Numerator.
Serialize()
bool FFrameRate::Serialize (FArchive & Ar)
References Ar.
Snap()
FFrameTime FFrameRate::Snap (FFrameTime SourceTime, FFrameRate SourceRate, FFrameRate SnapToRate) inline static
Snap a time specified in one framerate, to another.
Parameters
SourceTime The frame number to convert
SourceRate The source frame rate
SnapToRate The destination frame rate
Returns
A frame time in the destination frame rate
Definition at line 307 of file FrameRate.h.
References FFrameRate(), and ConvertFrameTime().
ToPrettyText()
FText FFrameRate::ToPrettyText () const
Convert this frame rate to a prettified text string.
Note
: Does not check against decorated frame rate names in FCommonFrameRates
Referenced by IAnimationDataController::ConvertSecondsToFrameNumber().
TransformTime()
FFrameTime FFrameRate::TransformTime (FFrameTime SourceTime, FFrameRate SourceRate, FFrameRate DestinationRate) inline static
Convert the specified time from one framerate to another framerate.
Parameters
SourceTime The frame number to convert
SourceRate The source frame rate
DestinationRate The destination frame rate
Returns
A frame time in the destination frame rate
Definition at line 302 of file FrameRate.h.
References FFrameRate(), and ConvertFrameTime().
Referenced by FQualifiedFrameTime::ConvertTo(), and Sequencer::PasteKeys().
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FFrameRate & Rate) friend
Definition at line 212 of file FrameRate.h.
References FFrameRate(), Denominator, GetTypeHash, HashCombine(), and Numerator.
Referenced by GetTypeHash.
operator!=
bool operator!= (const FFrameRate & A, const FFrameRate & B) friend
Definition at line 157 of file FrameRate.h.
References FFrameRate(), A, and B.
operator* [1/3]
FFrameTime operator* (double TimeInSeconds, FFrameRate Rate) friend
Definition at line 202 of file FrameRate.h.
References FFrameRate(), and AsFrameTime().
operator* [2/3]
FFrameRate operator* (FFrameRate A, FFrameRate B) friend
Definition at line 162 of file FrameRate.h.
References FFrameRate(), A, and B.
operator* [3/3]
FFrameTime operator* (float TimeInSeconds, FFrameRate Rate) friend
Definition at line 207 of file FrameRate.h.
References FFrameRate(), and AsFrameTime().
operator/ [1/4]
TRange< double > operator/ (const TRange< FFrameNumber > & FrameRange, FFrameRate Rate) friend
Definition at line 177 of file FrameRate.h.
References FFrameRate(), AsSeconds(), TRangeBound< ElementType >::Exclusive(), TRange< ElementType >::GetLowerBound(), TRange< ElementType >::GetUpperBound(), TRangeBound< ElementType >::Inclusive(), and TRangeBound< ElementType >::Open().
operator/ [2/4]
double operator/ (FFrameNumber Frame, FFrameRate Rate) friend
Definition at line 172 of file FrameRate.h.
References FFrameRate(), and AsSeconds().
operator/ [3/4]
FFrameRate operator/ (FFrameRate A, FFrameRate B) friend
Definition at line 167 of file FrameRate.h.
References FFrameRate(), A, and B.
operator/ [4/4]
double operator/ (FFrameTime FrameTime, FFrameRate Rate) friend
Definition at line 197 of file FrameRate.h.
References FFrameRate(), and AsSeconds().
operator<<
FArchive & operator<< (FArchive & Ar, FFrameRate & FrameRate) friend
References FFrameRate(), Ar, and FrameRate.
operator==
bool operator== (const FFrameRate & A, const FFrameRate & B) friend
Definition at line 152 of file FrameRate.h.
References FFrameRate(), A, and B.
Field Documentation
Denominator
int32 FFrameRate::Denominator
The denominator of the framerate represented as a number of frames per second (e.g.
1 for 60 fps)
Definition at line 43 of file FrameRate.h.
Referenced by FFrameRate(), FFrameRate(), AsDecimal(), AsFrameNumber(), AsFrameTime(), AsInterval(), AsSeconds(), ConvertFrameTime(), DisplayClusterTypesConverter::FromString(), GetTypeHash, IsMultipleOf(), IsValid(), operator=(), Reciprocal(), DisplayClusterTypesConverter::ToString(), and DisplayClusterTypesConverter::ToString().
Numerator
int32 FFrameRate::Numerator
IMPORTANT: If you change the struct data, ensure that you also update the version in NoExportTypes.h.
The numerator of the framerate represented as a number of frames per second (e.g. 60 for 60 fps)
Definition at line 38 of file FrameRate.h.
Referenced by FFrameRate(), FFrameRate(), AsDecimal(), AsFrameNumber(), AsFrameTime(), AsInterval(), AsSeconds(), ConvertFrameTime(), DisplayClusterTypesConverter::FromString(), GetTypeHash, IsMultipleOf(), operator=(), Reciprocal(), DisplayClusterTypesConverter::ToString(), and DisplayClusterTypesConverter::ToString().
The documentation for this struct was generated from the following file:
Runtime/Core/Public/Misc/FrameRate.h