Unreal Engine 5.6 C++ API: FRDGSubresourceState Struct Reference
FRDGSubresourceState Struct Reference
Used for tracking the state of an individual subresource during execution.
#include "RenderGraphResources.h"
Public Member Functions
FRDGSubresourceState ()=default
FRDGSubresourceState (ERHIAccess InAccess)
FRDGSubresourceState (ERHIPipeline Pipeline, FRDGPassHandle PassHandle)
FRDGPassHandle GetFirstPass () const
Returns the first pass across either pipe.
FRDGPassHandle GetLastPass () const
Returns the last pass across either pipe.
ERHIPipeline GetPipelines () const
Returns the pipeline mask this state is used on.
bool IsUsedBy (ERHIPipeline Pipeline) const
Returns whether the state is used by the pipeline.
void SetPass (ERHIPipeline Pipeline, FRDGPassHandle PassHandle)
Initializes the first and last pass and the pipeline.
void Validate ()
Validates that the state is in a correct configuration for use.
Static Public Member Functions
static bool IsMergeAllowed (ERDGViewableResourceType ResourceType, const FRDGSubresourceState &Previous, const FRDGSubresourceState &Next)
Given a before and after state, returns whether they can be merged into a single state.
static bool IsTransitionRequired (const FRDGSubresourceState &Previous, const FRDGSubresourceState &Next)
Given a before and after state, returns whether a resource barrier is required.
Data Fields
ERHIAccess Access = ERHIAccess::Unknown
The last used access on the pass.
ERDGBarrierLocation BarrierLocation = ERDGBarrierLocation::Prologue
Used to specify whether the state is applied during the prologue or epilogue of the pass.
FRDGPassHandlesByPipeline FirstPass
The first pass in this state.
EResourceTransitionFlags Flags = EResourceTransitionFlags::None
The last used transition flags on the pass.
FRDGPassHandlesByPipeline LastPass
The last pass in this state.
FRDGViewUniqueFilter NoUAVBarrierFilter
The last no-UAV barrier to be used by this subresource.
FRDGBufferReservedCommitHandle ReservedCommitHandle
Whether this subresource state represents a commit operation for a reserved resource.
Detailed Description
Used for tracking the state of an individual subresource during execution.
Definition at line 68 of file RenderGraphResources.h.
Constructor & Destructor Documentation
FRDGSubresourceState() [1/3]
FRDGSubresourceState::FRDGSubresourceState () default
Referenced by IsMergeAllowed(), and IsTransitionRequired().
FRDGSubresourceState() [2/3]
FRDGSubresourceState::FRDGSubresourceState (ERHIAccess InAccess) inline explicit
Definition at line 78 of file RenderGraphResources.h.
References Access.
FRDGSubresourceState() [3/3]
FRDGSubresourceState::FRDGSubresourceState (ERHIPipeline Pipeline, FRDGPassHandle PassHandle) inline explicit
Definition at line 82 of file RenderGraphResources.h.
References Pipeline, and SetPass().
Member Function Documentation
GetFirstPass()
FRDGPassHandle FRDGSubresourceState::GetFirstPass () const
Returns the first pass across either pipe.
GetLastPass()
FRDGPassHandle FRDGSubresourceState::GetLastPass () const
Returns the last pass across either pipe.
GetPipelines()
ERHIPipeline FRDGSubresourceState::GetPipelines () const
Returns the pipeline mask this state is used on.
IsMergeAllowed()
bool FRDGSubresourceState::IsMergeAllowed (ERDGViewableResourceType ResourceType, const FRDGSubresourceState & Previous, const FRDGSubresourceState & Next) static
Given a before and after state, returns whether they can be merged into a single state.
References FRDGSubresourceState().
IsTransitionRequired()
bool FRDGSubresourceState::IsTransitionRequired (const FRDGSubresourceState & Previous, const FRDGSubresourceState & Next) static
Given a before and after state, returns whether a resource barrier is required.
References FRDGSubresourceState().
IsUsedBy()
bool FRDGSubresourceState::IsUsedBy (ERHIPipeline Pipeline) const
Returns whether the state is used by the pipeline.
References Pipeline.
SetPass()
void FRDGSubresourceState::SetPass (ERHIPipeline Pipeline, FRDGPassHandle PassHandle)
Initializes the first and last pass and the pipeline.
Clears any other pass state.
References Pipeline.
Referenced by FRDGSubresourceState().
Validate()
void FRDGSubresourceState::Validate ()
Validates that the state is in a correct configuration for use.
Field Documentation
Access
ERHIAccess FRDGSubresourceState::Access = ERHIAccess::Unknown
The last used access on the pass.
Definition at line 106 of file RenderGraphResources.h.
Referenced by FRDGSubresourceState().
BarrierLocation
ERDGBarrierLocation FRDGSubresourceState::BarrierLocation = ERDGBarrierLocation::Prologue
Used to specify whether the state is applied during the prologue or epilogue of the pass.
This is only used when transitioning on the same pass / pipe.
Definition at line 124 of file RenderGraphResources.h.
FirstPass
FRDGPassHandlesByPipeline FRDGSubresourceState::FirstPass
The first pass in this state.
Definition at line 109 of file RenderGraphResources.h.
Flags
EResourceTransitionFlags FRDGSubresourceState::Flags = EResourceTransitionFlags::None
The last used transition flags on the pass.
Definition at line 121 of file RenderGraphResources.h.
LastPass
FRDGPassHandlesByPipeline FRDGSubresourceState::LastPass
The last pass in this state.
Definition at line 112 of file RenderGraphResources.h.
NoUAVBarrierFilter
FRDGViewUniqueFilter FRDGSubresourceState::NoUAVBarrierFilter
The last no-UAV barrier to be used by this subresource.
Definition at line 115 of file RenderGraphResources.h.
ReservedCommitHandle
FRDGBufferReservedCommitHandle FRDGSubresourceState::ReservedCommitHandle
Whether this subresource state represents a commit operation for a reserved resource.
Definition at line 118 of file RenderGraphResources.h.
The documentation for this struct was generated from the following file:
Runtime/RenderCore/Public/RenderGraphResources.h