Unreal Engine 5.6 C++ API: FWorldPartitionHandleImpl Struct Reference
FWorldPartitionHandleImpl Struct Reference
#include "WorldPartitionHandle.h"
Public Member Functions
UE_DEPRECATED (5.4, "Use FWorldPartitionActorDescInstance") static void DecRefCount(FWorldPartitionActorDesc *ActorDesc)
UE_DEPRECATED (5.4, "Use FWorldPartitionActorDescInstance") static void IncRefCount(FWorldPartitionActorDesc *ActorDesc)
Public Member Functions inherited from FWorldPartitionImplBase
UE_DEPRECATED (5.4, "Use FWorldPartitionActorDescInstance") static AActor *GetActorDescActor(FWorldPartitionActorDesc *ActorDesc)
UE_DEPRECATED (5.4, "Use FWorldPartitionActorDescInstance") static bool IsActorDescLoaded(FWorldPartitionActorDesc *ActorDesc)
UE_DEPRECATED (5.4, "Use FWorldPartitionActorDescInstance") static TUniquePtr< FWorldPartitionActorDesc > *GetActorDesc(UActorDescContainer *Container
UE_DEPRECATED (5.4, "Use FWorldPartitionActorDescInstance") static UActorDescContainer *GetActorDescContainer(TUniquePtr< FWorldPartitionActorDesc > *ActorDesc)
Static Public Member Functions
static void DecRefCount (FWorldPartitionActorDescInstance *InActorDescInstance)
static void IncRefCount (FWorldPartitionActorDescInstance *InActorDescInstance)
static TWorldPartitionHandle< FWorldPartitionReferenceImpl > ToReference (const TWorldPartitionHandle< FWorldPartitionHandleImpl > &Source)
Static Public Member Functions inherited from FWorldPartitionImplBase
static AActor * GetActor (FWorldPartitionActorDescInstance *InActorDescInstance)
static FWorldPartitionActorDesc * GetActorDesc (FWorldPartitionActorDescInstance *InActorDescInstance)
template<class U>
static UActorDescContainer * GetActorDescContainer (TActorDescContainerCollection< U > *ContainerCollection, const FGuid &ActorGuid)
static UActorDescContainerInstance * GetActorDescContainerInstance (FWorldPartitionActorDescInstance *InActorDescInstance)
template<class U>
static UActorDescContainerInstance * GetActorDescContainerInstance (TActorDescContainerInstanceCollection< U > *ContainerCollection, const FGuid &ActorGuid)
static UActorDescContainerInstance * GetActorDescContainerInstance (TUniquePtr< FWorldPartitionActorDescInstance > *InActorDescInstance)
static TUniquePtr< FWorldPartitionActorDescInstance > * GetActorDescInstance (UActorDescContainerInstance *InContainerInstance, const FGuid &InActorGuid)
static FGuid GetActorDescInstanceGuid (const FWorldPartitionActorDescInstance *InActorDescInstance)
static bool IsLoaded (FWorldPartitionActorDescInstance *InActorDescInstance)
Additional Inherited Members
Data Fields inherited from FWorldPartitionImplBase
const FGuid & ActorGuid { return nullptr
Detailed Description
Definition at line 449 of file WorldPartitionHandle.h.
Member Function Documentation
DecRefCount()
void FWorldPartitionHandleImpl::DecRefCount (FWorldPartitionActorDescInstance * InActorDescInstance) static
Referenced by UE_DEPRECATED().
IncRefCount()
void FWorldPartitionHandleImpl::IncRefCount (FWorldPartitionActorDescInstance * InActorDescInstance) static
Referenced by UE_DEPRECATED().
ToReference()
TWorldPartitionHandle< FWorldPartitionReferenceImpl > FWorldPartitionHandleImpl::ToReference (const TWorldPartitionHandle< FWorldPartitionHandleImpl > & Source) static
References Source.
UE_DEPRECATED() [1/2]
FWorldPartitionHandleImpl::UE_DEPRECATED (5. 4, "Use FWorldPartitionActorDescInstance") inline
Definition at line 453 of file WorldPartitionHandle.h.
References DecRefCount().
UE_DEPRECATED() [2/2]
FWorldPartitionHandleImpl::UE_DEPRECATED (5. 4, "Use FWorldPartitionActorDescInstance") inline
Definition at line 451 of file WorldPartitionHandle.h.
References IncRefCount().
The documentation for this struct was generated from the following file:
Runtime/Engine/Public/WorldPartition/WorldPartitionHandle.h