Unreal Engine 5.6 C++ API: FAssetData Struct Reference
FAssetData Struct Reference
A struct to hold important information about an assets found by the Asset Registry This struct is transient and should never be serialized.
#include "AssetData.h"
Public Types
enum class ECreationFlags { None = 0 , SkipAssetRegistryTagsGathering = 1 << 0 , AllowBlueprintClass = 1 << 1 }
using FChunkArray = TArray<int32, TInlineAllocator<2>>
using FChunkArrayView = TConstArrayView<int32>
Public Member Functions
PRAGMA_DISABLE_DEPRECATION_WARNINGS FAssetData ()
Default constructors.
FAssetData (const FAssetData &)=default
FAssetData (const FString &InLongPackageName, const FString &InObjectPath, FTopLevelAssetPath InAssetClassPathName, FAssetDataTagMap InTags=FAssetDataTagMap(), TArrayView< const int32 > InChunkIDs=TArrayView< const int32 >(), uint32 InPackageFlags=0)
Constructor with a long package name and a full object path which might not be part of the package this asset is in.
FAssetData (const UObject *InAsset, bool bAllowBlueprintClass)
Constructor taking a UObject.
FAssetData (const UObject *InAsset, FAssetData::ECreationFlags InCreationFlags, EAssetRegistryTagsCaller Caller)
FAssetData (const UObject *InAsset, FAssetData::ECreationFlags InCreationFlags=ECreationFlags::None)
Constructor taking a UObject.
FAssetData (FAssetData &&)=default
FAssetData (FName InPackageName, FName InPackagePath, FName InAssetName, FTopLevelAssetPath InAssetClassPathName, FAssetDataTagMap InTags=FAssetDataTagMap(), TArrayView< const int32 > InChunkIDs=TArrayView< const int32 >(), uint32 InPackageFlags=0)
Constructor building the ObjectPath in the form of InPackageName.InAssetName.
void AddChunkID (int32 ChunkID)
void AppendObjectPath (FString &String) const
Append the object path to the given string.
void AppendObjectPath (FStringBuilderBase &Builder) const
Append the object path to the given string builder.
void ClearChunkIDs ()
template<typename Func>
void EnumerateTags (Func Fn) const
Call the given function for each tag on the asset.
UObject * FastGetAsset (bool bLoad=false, TSet< FName > LoadTags={}) const
Returns the asset UObject if it is loaded or loads the asset if it is unloaded then returns the result.
bool FindTag (const FName InTagName) const
Try to find the given tag.
UObject * GetAsset (TSet< FName > LoadTags={}) const
Returns the asset UObject if it is loaded or loads the asset if it is unloaded then returns the result.
EAssetAccessSpecifier GetAssetAccessSpecifier () const
Returns how package can be referenced from other plugins and mount points.
FChunkArrayView GetChunkIDs () const
UClass * GetClass (EResolveClass ResolveClass=EResolveClass::No) const
Returns the class UClass if it is loaded.
FString GetExportTextName () const
Returns the name for the asset in the form: Class'FullPath'.
void GetExportTextName (FString &OutExportTextName) const
Populates OutExportTextName with the name for the asset in the form: Class'FullPath'.
void GetExportTextName (FStringBuilderBase &OutExportTextNameBuilder) const
Populates OutExportTextNameBuilder with the name for the asset in the form: Class'FullPath'.
FString GetFullName () const
Returns the full name for the asset in the form: Class FullPath.
void GetFullName (FString &OutFullName) const
Populates OutFullName with the full name for the asset in the form: Class FullPath.
void GetFullName (FStringBuilderBase &OutFullNameBuilder) const
Populates OutFullNameBuilder with the full name for the asset in the form: Class ObjectPath.
FString GetObjectPathString () const
Return the object path as a string.
UPackage * GetPackage () const
Tries to find the package in memory if it is loaded, otherwise loads it.
FPrimaryAssetId GetPrimaryAssetId () const
Gets primary asset id of this data.
FSoftObjectPath GetSoftObjectPath () const
Convert to a SoftObjectPath.
template<>
bool GetTagValue (FName Tag, FName &OutValue) const
template<>
bool GetTagValue (FName Tag, FString &OutValue) const
template<>
bool GetTagValue (FName Tag, FText &OutValue) const
template<typename ValueType>
bool GetTagValue (FName Tag, ValueType &OutValue) const
Try and get the value associated with the given tag as a type converted value.
template<typename ValueType>
ValueType GetTagValueRef (const FName Tag) const
Try and get the value associated with the given tag as a type converted value, or an empty value if it doesn't exist.
template<>
FString GetTagValueRef (FName Tag) const
template<>
FText GetTagValueRef (FName Tag) const
template<>
FName GetTagValueRef (FName Tag) const
template<>
FAssetRegistryExportPath GetTagValueRef (FName Tag) const
UE::Core::FVersePath GetVersePath () const
Gets the versepath of the asset.
bool HasAllPackageFlags (uint32 FlagsToCheck) const
Used to check whether all of the passed flags are set in the cached asset package flags.
bool HasAnyPackageFlags (uint32 FlagsToCheck) const
Used to check whether the any of the passed flags are set in the cached asset package flags.
bool HasSameChunkIDs (const FAssetData &OtherAssetData) const
bool IsAssetLoaded () const
Returns true if the asset is loaded.
bool IsInstanceOf (const UClass *BaseClass, EResolveClass ResolveClass=EResolveClass::No) const
Returns whether the Asset's class is equal to or a child class of the given class.
template<typename BaseClass>
bool IsInstanceOf (EResolveClass ResolveClass=EResolveClass::No) const
bool IsRedirector () const
Returns true if the this asset is a redirector.
bool IsTopLevelAsset () const
Returns true iff the Asset is a TopLevelAsset (not a subobject, its outer is a UPackage).
bool IsUAsset () const
Returns true if this is the main asset in a package, true for maps and assets but false for secondary objects like class redirectors Every UAsset is also a TopLevelAsset.
bool IsValid () const
Checks to see if this AssetData refers to an asset or is NULL.
void NetworkWrite (FCbWriter &Writer, bool bWritePackageName) const
bool operator!= (const FAssetData &Other) const
bool operator< (const FAssetData &Other) const
Perform a lexical less-than operation on the PackageName and AssetName that uniquely identify two FAssetData.
FAssetData & operator= (const FAssetData &)=default
FAssetData & operator= (FAssetData &&)=default
bool operator== (const FAssetData &Other) const
FAssetDatas are uniquely identified by PackageName and AssetName.
bool operator> (const FAssetData &Other) const
Perform a lexical greater-than operation on the PackageName and AssetName that uniquely identify two FAssetData.
void PrintAssetData () const
Prints the details of the asset to the log.
template<class Archive>
FORCEINLINE void SerializeForCache (Archive &&Ar)
Serialize as part of the registry cache.
template<class Archive>
FORCEINLINE void SerializeForCacheOldVersion (Archive &&Ar, FAssetRegistryVersion::Type Version=FAssetRegistryVersion::LatestVersion)
Serialize as part of the registry cache using legacy paths (versioned)
void SetChunkIDs (const FChunkArrayView &InChunkIDs)
void SetChunkIDs (FChunkArray &&InChunkIDs)
void SetTagsAndAssetBundles (FAssetDataTagMap &&Tags)
void Shrink ()
FSoftObjectPath ToSoftObjectPath () const
bool TryNetworkRead (FCbFieldView Field, bool bReadPackageName, FName InPackageName)
UE_DEPRECATED (5.1, "Class names are now represented by path names. Please use a version of FAssetData constructor that uses FTopLevelAssetPath.") 1 FAssetData(const FString &InLongPackageName
PRAGMA_ENABLE_DEPRECATION_WARNINGS UE_DEPRECATED (5.1, "Class names are now represented by path names. Please use a version of FAssetData constructor that uses FTopLevelAssetPath.") 1 FAssetData(FName InPackageName
UE_DEPRECATED (5.1, "Class names are now represented by path names. Please use AssetClassPath.") FName AssetClass
The name of the asset's class.
UE_DEPRECATED (5.1, "Use SetChunkIDs/GetChunkIDs/AddChunkID instead.") TArray< int32
The IDs of the pakchunks this asset is located in for streaming install.
Static Public Member Functions
static SIZE_T GetChunkArrayRegistryAllocatedSize ()
Returns overhead of the chunk array registry that's used to manage chunk ID arrays.
static const TCHAR * GetCollectionTagPrefix ()
The prefix used for collection entries inside TagsAndValues.
template<class T>
static T * GetFirstAsset (const TArray< FAssetData > &Assets)
Convenience template for finding first asset of a class.
static FAssetData GetFirstAssetDataOfClass (const TArray< FAssetData > &Assets, const UClass *DesiredClass)
Get the first FAssetData of a particular class from an Array of FAssetData.
static bool IsRedirector (UObject *Object)
static bool IsRedirectorClassName (FTopLevelAssetPath ClassPathName)
static bool IsTopLevelAsset (UObject *Object)
Returns true iff the given Object, assumed to be an Asset, is a TopLevelAsset (not a subobject, its outer is a UPackage).
static bool IsUAsset (UObject *Object)
Returns true if the given UObject is the main asset in a package, true for maps and assets but false for secondary objects like class redirectors Every UAsset is also a TopLevelAsset.
static FTopLevelAssetPath TryConvertShortClassNameToPathName (FName InClassName, ELogVerbosity::Type FailureMessageVerbosity=ELogVerbosity::Warning)
Helper function that tries to convert short class name to path name.
Data Fields
FTopLevelAssetPath AssetClassPath
The path of the asset's class, e.g.
FName AssetName
The name of the asset without the package.
TInlineAllocator< 2 > ChunkIDs
PRAGMA_ENABLE_DEPRECATION_WARNINGS FName FName FName InAssetClassName
const FString FName InAssetClassName
PRAGMA_ENABLE_DEPRECATION_WARNINGS FName FName InAssetName
PRAGMA_ENABLE_DEPRECATION_WARNINGS FName FName FName FAssetDataTagMap TArrayView< const int32 > InChunkIDs = TArrayView<const int32>()
const FString FName FAssetDataTagMap TArrayView< const int32 > InChunkIDs = TArrayView<const int32>()
const FString & InObjectPath
PRAGMA_ENABLE_DEPRECATION_WARNINGS FName FName FName FAssetDataTagMap TArrayView< const int32 > uint32 InPackageFlags = 0)
const FString FName FAssetDataTagMap TArrayView< const int32 > uint32 InPackageFlags = 0)
PRAGMA_ENABLE_DEPRECATION_WARNINGS FName InPackagePath
PRAGMA_ENABLE_DEPRECATION_WARNINGS FName FName FName FAssetDataTagMap InTags = FAssetDataTagMap()
const FString FName FAssetDataTagMap InTags = FAssetDataTagMap()
uint32 PackageFlags = 0
Asset package flags.
FName PackageName
The name of the package in which the asset is found, this is the full long package name such as /Game/Path/Package.
FName PackagePath
The path to the package in which the asset is found, this is /Game/Path with the Package stripped off.
TSharedPtr< FAssetBundleData, ESPMode::ThreadSafe > TaggedAssetBundles
The 'AssetBundles' tag key is separated from TagsAndValues and typed for performance reasons.
FAssetDataTagMapSharedView TagsAndValues
The map of values for properties that were marked AssetRegistrySearchable or added by GetAssetRegistryTags.
Private Member Functions
FORCEINLINE void SerializeForCacheInternal (FArchive &Ar, FAssetRegistryVersion::Type Version, void(*SerializeTagsAndBundles)(FArchive &, FAssetData &, FAssetRegistryVersion::Type))
The actual implementation of SerializeForCache.
void SerializeForCacheOldVersionWithTagsAndBundles (FArchive &Ar, FAssetRegistryVersion::Type Version, void(*SerializeTagsAndBundles)(FArchive &, FAssetData &, FAssetRegistryVersion::Type))
void SerializeForCacheWithTagsAndBundles (FArchive &Ar, void(*SerializeTagsAndBundles)(FArchive &, FAssetData &, FAssetRegistryVersion::Type))
Static Private Member Functions
static bool DetectIsUAssetByNames (FStringView PackageName, FStringView ObjectPathName)
Private Attributes
UE::AssetRegistry::FChunkArrayRegistryHandle ChunkArrayRegistryHandle
Friends
FORCEINLINE uint32 GetTypeHash (const FAssetData &AssetData)
Detailed Description
A struct to hold important information about an assets found by the Asset Registry This struct is transient and should never be serialized.
Definition at line 157 of file AssetData.h.
Member Typedef Documentation
FChunkArray
using FAssetData::FChunkArray = TArray<int32, TInlineAllocator<2>>
Definition at line 230 of file AssetData.h.
FChunkArrayView
using FAssetData::FChunkArrayView = TConstArrayView<int32>
Definition at line 231 of file AssetData.h.
Member Enumeration Documentation
ECreationFlags
enum class FAssetData::ECreationFlags strong
Enumerator
None
SkipAssetRegistryTagsGathering
AllowBlueprintClass
Definition at line 166 of file AssetData.h.
Constructor & Destructor Documentation
FAssetData() [1/8]
PRAGMA_DISABLE_DEPRECATION_WARNINGS FAssetData::FAssetData () inline
Default constructors.
Definition at line 246 of file AssetData.h.
Referenced by FAssetData(), FAssetData(), FAssetData(), FAssetData(), FAssetData(), FAssetData(), FAssetData(), GetFirstAssetDataOfClass(), GetTypeHash, HasSameChunkIDs(), operator!=(), operator<(), operator=(), operator=(), operator==(), operator>(), SerializeForCache(), SerializeForCacheInternal(), SerializeForCacheOldVersion(), SerializeForCacheOldVersionWithTagsAndBundles(), and SerializeForCacheWithTagsAndBundles().
FAssetData() [2/8]
FAssetData::FAssetData (FAssetData &&) default
References FAssetData().
FAssetData() [3/8]
FAssetData::FAssetData (const FAssetData &) default
References FAssetData().
FAssetData() [4/8]
FAssetData::FAssetData (FName InPackageName, FName InPackagePath, FName InAssetName, FTopLevelAssetPath InAssetClassPathName, FAssetDataTagMap InTags = FAssetDataTagMap(), TArrayView< const int32 > InChunkIDs = TArrayView< const int32 >(), uint32 InPackageFlags = 0)
Constructor building the ObjectPath in the form of InPackageName.InAssetName.
does not work for object outer-ed to a different package.
References FAssetData(), InAssetName, InChunkIDs, InPackageFlags, InPackagePath, and InTags.
FAssetData() [5/8]
FAssetData::FAssetData (const FString & InLongPackageName, const FString & InObjectPath, FTopLevelAssetPath InAssetClassPathName, FAssetDataTagMap InTags = FAssetDataTagMap(), TArrayView< const int32 > InChunkIDs = TArrayView< const int32 >(), uint32 InPackageFlags = 0)
Constructor with a long package name and a full object path which might not be part of the package this asset is in.
References FAssetData(), InChunkIDs, InObjectPath, InPackageFlags, and InTags.
FAssetData() [6/8]
FAssetData::FAssetData (const UObject * InAsset, FAssetData::ECreationFlags InCreationFlags = ECreationFlags::None)
Constructor taking a UObject.
By default trying to create one for a blueprint class will create one for the UBlueprint instead, but this can be overridden
References FAssetData(), and None.
FAssetData() [7/8]
FAssetData::FAssetData (const UObject * InAsset, FAssetData::ECreationFlags InCreationFlags, EAssetRegistryTagsCaller Caller)
References FAssetData().
FAssetData() [8/8]
FAssetData::FAssetData (const UObject * InAsset, bool bAllowBlueprintClass) inline
Constructor taking a UObject.
By default trying to create one for a blueprint class will create one for the UBlueprint instead, but this can be overridden
Definition at line 270 of file AssetData.h.
References FAssetData(), AllowBlueprintClass, and None.
Member Function Documentation
AddChunkID()
void FAssetData::AddChunkID (int32 ChunkID)
AppendObjectPath() [1/2]
void FAssetData::AppendObjectPath (FString & String) const inline
Append the object path to the given string.
Definition at line 496 of file AssetData.h.
References AppendObjectPath(), and String.
AppendObjectPath() [2/2]
void FAssetData::AppendObjectPath (FStringBuilderBase & Builder) const inline
Append the object path to the given string builder.
Definition at line 476 of file AssetData.h.
References AssetName, UE::AssetRegistry::Private::ConcatenateOuterPathAndObjectName(), FName::IsNone(), IsValid(), and PackageName.
Referenced by AppendObjectPath(), GetExportTextName(), GetExportTextName(), GetFullName(), GetFullName(), and GetObjectPathString().
ClearChunkIDs()
void FAssetData::ClearChunkIDs ()
DetectIsUAssetByNames()
bool FAssetData::DetectIsUAssetByNames (FStringView PackageName, FStringView ObjectPathName) inline static private
Definition at line 742 of file AssetData.h.
References TStringView< CharType >::Equals(), ESearchCase::IgnoreCase, INDEX_NONE, PackageName, and TEXT.
Referenced by IsUAsset().
EnumerateTags()
template<typename Func> void FAssetData::EnumerateTags (Func Fn) const inline
Call the given function for each tag on the asset.
Function signature is: void Fn(TPair<FName, FAssetTagValueRef>);
Definition at line 640 of file AssetData.h.
References TagsAndValues.
FastGetAsset()
UObject * FAssetData::FastGetAsset (bool bLoad = false, TSet< FName > LoadTags = {}) const inline
Returns the asset UObject if it is loaded or loads the asset if it is unloaded then returns the result.
Note this can return nullptr even if it looks like the asset exists because it doesn't handle redirects.
Parameters
bLoad (optional) loads the asset if it is unloaded.
LoadTags (optional) allows passing specific tags to the linker when loading the asset (
See also
ULevel::LoadAllExternalObjectsTag for an example usage)
Definition at line 514 of file AssetData.h.
Referenced by IsAssetLoaded().
FindTag()
bool FAssetData::FindTag (const FName InTagName) const inline
Try to find the given tag.
Definition at line 629 of file AssetData.h.
References TagsAndValues.
GetAsset()
UObject * FAssetData::GetAsset (TSet< FName > LoadTags = {}) const inline
Returns the asset UObject if it is loaded or loads the asset if it is unloaded then returns the result.
Note this can return nullptr even if it looks like the asset exists because it doesn't handle redirects.
Parameters
LoadTags (optional) allows passing specific tags to the linker when loading the asset (
See also
ULevel::LoadAllExternalObjectsTag for an example usage)
Definition at line 564 of file AssetData.h.
Referenced by GetFirstAsset(), and FSoundWaveLoadingBehaviorUtil::LoadAndCacheClass().
GetAssetAccessSpecifier()
EAssetAccessSpecifier FAssetData::GetAssetAccessSpecifier () const inline
Returns how package can be referenced from other plugins and mount points.
Definition at line 593 of file AssetData.h.
References EpicInternal, PackageFlags, PKG_AccessSpecifierEpicInternal, PKG_NotExternallyReferenceable, Private, and Public.
GetChunkArrayRegistryAllocatedSize()
SIZE_T FAssetData::GetChunkArrayRegistryAllocatedSize () static
Returns overhead of the chunk array registry that's used to manage chunk ID arrays.
References PRAGMA_DISABLE_DEPRECATION_WARNINGS.
GetChunkIDs()
FChunkArrayView FAssetData::GetChunkIDs () const
Referenced by PrintAssetData().
GetClass()
UClass * FAssetData::GetClass (EResolveClass ResolveClass = EResolveClass::No) const
Returns the class UClass if it is loaded.
If you choose to override ResolveClass, to EResolveClass::Yes it will attempt to load the class if unloaded.
References No.
Referenced by IsInstanceOf().
GetCollectionTagPrefix()
const TCHAR * FAssetData::GetCollectionTagPrefix () inline static
The prefix used for collection entries inside TagsAndValues.
Definition at line 161 of file AssetData.h.
References TEXT.
GetExportTextName() [1/3]
FString FAssetData::GetExportTextName () const inline
Returns the name for the asset in the form: Class'FullPath'.
Definition at line 408 of file AssetData.h.
References GetExportTextName().
Referenced by GetExportTextName().
GetExportTextName() [2/3]
void FAssetData::GetExportTextName (FString & OutExportTextName) const inline
Populates OutExportTextName with the name for the asset in the form: Class'FullPath'.
Definition at line 416 of file AssetData.h.
References AppendObjectPath(), AssetClassPath, and TEXT.
GetExportTextName() [3/3]
void FAssetData::GetExportTextName (FStringBuilderBase & OutExportTextNameBuilder) const inline
Populates OutExportTextNameBuilder with the name for the asset in the form: Class'FullPath'.
Definition at line 426 of file AssetData.h.
References TStringBuilderBase< CharType >::AppendChar(), AppendObjectPath(), AssetClassPath, TStringBuilderBase< CharType >::Reset(), and TEXT.
GetFirstAsset()
template<class T> T * FAssetData::GetFirstAsset (const TArray< FAssetData > & Assets) inline static
Convenience template for finding first asset of a class.
Definition at line 698 of file AssetData.h.
References Asset, check, GetAsset(), and GetFirstAssetDataOfClass().
GetFirstAssetDataOfClass()
FAssetData FAssetData::GetFirstAssetDataOfClass (const TArray< FAssetData > & Assets, const UClass * DesiredClass) inline static
Get the first FAssetData of a particular class from an Array of FAssetData.
Definition at line 683 of file AssetData.h.
References FAssetData(), IsInstanceOf(), and TArray< InElementType, InAllocatorType >::Num().
Referenced by GetFirstAsset().
GetFullName() [1/3]
FString FAssetData::GetFullName () const inline
Returns the full name for the asset in the form: Class FullPath.
Definition at line 382 of file AssetData.h.
References GetFullName().
Referenced by GetFullName().
GetFullName() [2/3]
void FAssetData::GetFullName (FString & OutFullName) const inline
Populates OutFullName with the full name for the asset in the form: Class FullPath.
Definition at line 390 of file AssetData.h.
References AppendObjectPath(), AssetClassPath, and TEXT.
GetFullName() [3/3]
void FAssetData::GetFullName (FStringBuilderBase & OutFullNameBuilder) const inline
Populates OutFullNameBuilder with the full name for the asset in the form: Class ObjectPath.
Definition at line 399 of file AssetData.h.
References TStringBuilderBase< CharType >::AppendChar(), AppendObjectPath(), AssetClassPath, TStringBuilderBase< CharType >::Reset(), and TEXT.
GetObjectPathString()
FString FAssetData::GetObjectPathString () const inline
Return the object path as a string.
Definition at line 343 of file AssetData.h.
References AppendObjectPath().
Referenced by PrintAssetData().
GetPackage()
UPackage * FAssetData::GetPackage () const inline
Tries to find the package in memory if it is loaded, otherwise loads it.
Definition at line 608 of file AssetData.h.
References FindPackage(), LOAD_None, LoadPackage, Package, and PackageName.
GetPrimaryAssetId()
FPrimaryAssetId FAssetData::GetPrimaryAssetId () const
Gets primary asset id of this data.
GetSoftObjectPath()
FSoftObjectPath FAssetData::GetSoftObjectPath () const
Convert to a SoftObjectPath.
PackageName.AssetName for ToplevelAssets. OptionalOuterName and AssetName joined by : or . for sub-object assets
Referenced by ToSoftObjectPath().
GetTagValue() [1/4]
template<> bool FAssetData::GetTagValue (FName Tag, FName & OutValue) const inline
Definition at line 819 of file AssetData.h.
References FAssetTagValueRef::AsName(), FAssetTagValueRef::IsSet(), and TagsAndValues.
GetTagValue() [2/4]
template<> bool FAssetData::GetTagValue (FName Tag, FString & OutValue) const inline
Definition at line 793 of file AssetData.h.
References FAssetTagValueRef::AsString(), FAssetTagValueRef::IsSet(), and TagsAndValues.
GetTagValue() [3/4]
template<> bool FAssetData::GetTagValue (FName Tag, FText & OutValue) const inline
Definition at line 806 of file AssetData.h.
References FAssetTagValueRef::AsText(), FAssetTagValueRef::IsSet(), and TagsAndValues.
GetTagValue() [4/4]
template<typename ValueType> bool FAssetData::GetTagValue (FName Tag, ValueType & OutValue) const inline
Try and get the value associated with the given tag as a type converted value.
Definition at line 780 of file AssetData.h.
References FAssetTagValueRef::GetValue(), FAssetTagValueRef::IsSet(), LexFromString(), FMemory::Memzero(), and TagsAndValues.
Referenced by GetTagValueRef().
GetTagValueRef() [1/5]
template<typename ValueType> ValueType FAssetData::GetTagValueRef (const FName Tag) const inline
Try and get the value associated with the given tag as a type converted value, or an empty value if it doesn't exist.
Definition at line 831 of file AssetData.h.
References FAssetTagValueRef::GetValue(), FAssetTagValueRef::IsSet(), LexFromString(), FMemory::Memzero(), and TagsAndValues.
GetTagValueRef() [2/5]
template<> FString FAssetData::GetTagValueRef (FName Tag) const inline
Definition at line 844 of file AssetData.h.
References FAssetTagValueRef::AsString(), FAssetTagValueRef::IsSet(), and TagsAndValues.
GetTagValueRef() [3/5]
template<> FText FAssetData::GetTagValueRef (FName Tag) const inline
Definition at line 851 of file AssetData.h.
References GetTagValue().
GetTagValueRef() [4/5]
template<> FName FAssetData::GetTagValueRef (FName Tag) const inline
Definition at line 859 of file AssetData.h.
References FAssetTagValueRef::AsName(), FName, FAssetTagValueRef::IsSet(), and TagsAndValues.
GetTagValueRef() [5/5]
template<> FAssetRegistryExportPath FAssetData::GetTagValueRef (FName Tag) const inline
Definition at line 866 of file AssetData.h.
References FAssetTagValueRef::AsExportPath(), FAssetTagValueRef::IsSet(), and TagsAndValues.
GetVersePath()
UE::Core::FVersePath FAssetData::GetVersePath () const
Gets the versepath of the asset.
Returns
The VersePath of the asset
HasAllPackageFlags()
bool FAssetData::HasAllPackageFlags (uint32 FlagsToCheck) const inline
Used to check whether all of the passed flags are set in the cached asset package flags.
Parameters
FlagsToCheck Package flags to check for
Returns
true if all of the passed in flags are set (including no flags passed in), false otherwise
See also
UPackage::HasAllPackagesFlags
Definition at line 587 of file AssetData.h.
References PackageFlags.
HasAnyPackageFlags()
bool FAssetData::HasAnyPackageFlags (uint32 FlagsToCheck) const inline
Used to check whether the any of the passed flags are set in the cached asset package flags.
Parameters
FlagsToCheck Package flags to check for
Returns
true if any of the passed in flag are set, false otherwise
See also
UPackage::HasAnyPackageFlags
Definition at line 576 of file AssetData.h.
References PackageFlags.
HasSameChunkIDs()
bool FAssetData::HasSameChunkIDs (const FAssetData & OtherAssetData) const
References FAssetData().
IsAssetLoaded()
bool FAssetData::IsAssetLoaded () const inline
Returns true if the asset is loaded.
Definition at line 650 of file AssetData.h.
References FastGetAsset().
IsInstanceOf() [1/2]
bool FAssetData::IsInstanceOf (const UClass * BaseClass, EResolveClass ResolveClass = EResolveClass::No) const inline
Returns whether the Asset's class is equal to or a child class of the given class.
Returns false if the Asset's class can not be loaded. If you choose to override ResolveClass, to EResolveClass::Yes it will attempt to load the class if unloaded.
Definition at line 463 of file AssetData.h.
References GetClass(), UStruct::IsChildOf(), and No.
Referenced by GetFirstAssetDataOfClass(), and IsInstanceOf().
IsInstanceOf() [2/2]
template<typename BaseClass> bool FAssetData::IsInstanceOf (EResolveClass ResolveClass = EResolveClass::No) const inline
Definition at line 470 of file AssetData.h.
References IsInstanceOf(), and No.
IsRedirector() [1/2]
bool FAssetData::IsRedirector () const inline
Returns true if the this asset is a redirector.
Definition at line 443 of file AssetData.h.
References AssetClassPath, and IsRedirectorClassName().
IsRedirector() [2/2]
bool FAssetData::IsRedirector (UObject * Object) inline static
Definition at line 448 of file AssetData.h.
References IsRedirectorClassName(), and Object.
IsRedirectorClassName()
bool FAssetData::IsRedirectorClassName (FTopLevelAssetPath ClassPathName) static
Referenced by IsRedirector(), and IsRedirector().
IsTopLevelAsset() [1/2]
bool FAssetData::IsTopLevelAsset () const
Returns true iff the Asset is a TopLevelAsset (not a subobject, its outer is a UPackage).
Only TopLevelAssets can be PrimaryAssets in the AssetManager. A TopLevelAsset is not necessarily the main asset in a package; see IsUAsset. Note that this is distinct from UObject::IsAsset because IsAsset can be overloaded (see e.g. AActor::IsAsset)
IsTopLevelAsset() [2/2]
bool FAssetData::IsTopLevelAsset (UObject * Object) static
Returns true iff the given Object, assumed to be an Asset, is a TopLevelAsset (not a subobject, its outer is a UPackage).
Only TopLevelAssets can be PrimaryAssets in the AssetManager. A TopLevelAsset is not necessarily the main asset in a package; see IsUAsset.
References Object.
IsUAsset() [1/2]
bool FAssetData::IsUAsset () const inline
Returns true if this is the main asset in a package, true for maps and assets but false for secondary objects like class redirectors Every UAsset is also a TopLevelAsset.
Specifically, this is just testing whether the asset name matches the package name, and it is possible for legacy content to not return true for any asset in a package.
Definition at line 318 of file AssetData.h.
References AssetName, DetectIsUAssetByNames(), IsValid(), and PackageName.
IsUAsset() [2/2]
bool FAssetData::IsUAsset (UObject * Object) static
Returns true if the given UObject is the main asset in a package, true for maps and assets but false for secondary objects like class redirectors Every UAsset is also a TopLevelAsset.
References Object.
IsValid()
bool FAssetData::IsValid () const inline
Checks to see if this AssetData refers to an asset or is NULL.
Definition at line 307 of file AssetData.h.
References AssetName, and PackageName.
Referenced by AppendObjectPath(), and IsUAsset().
NetworkWrite()
void FAssetData::NetworkWrite (FCbWriter & Writer, bool bWritePackageName) const
operator!=()
bool FAssetData::operator!= (const FAssetData & Other) const inline
Definition at line 281 of file AssetData.h.
References FAssetData(), AssetName, Other, and PackageName.
operator<()
bool FAssetData::operator< (const FAssetData & Other) const inline
Perform a lexical less-than operation on the PackageName and AssetName that uniquely identify two FAssetData.
Definition at line 297 of file AssetData.h.
References FAssetData(), AssetName, Other, and PackageName.
operator=() [1/2]
FAssetData & FAssetData::operator= (const FAssetData &) default
References FAssetData(), and PRAGMA_ENABLE_DEPRECATION_WARNINGS.
operator=() [2/2]
FAssetData & FAssetData::operator= (FAssetData &&) default
References FAssetData().
operator==()
bool FAssetData::operator== (const FAssetData & Other) const inline
FAssetDatas are uniquely identified by PackageName and AssetName.
Definition at line 276 of file AssetData.h.
References FAssetData(), AssetName, Other, and PackageName.
operator>()
bool FAssetData::operator> (const FAssetData & Other) const inline
Perform a lexical greater-than operation on the PackageName and AssetName that uniquely identify two FAssetData.
Definition at line 287 of file AssetData.h.
References FAssetData(), AssetName, Other, and PackageName.
PrintAssetData()
void FAssetData::PrintAssetData () const inline
Prints the details of the asset to the log.
Definition at line 656 of file AssetData.h.
References AssetClassPath, AssetName, GetChunkIDs(), GetObjectPathString(), Log, PackageFlags, PackageName, PackagePath, TagsAndValues, TEXT, and UE_LOG.
SerializeForCache()
template<class Archive> FORCEINLINE void FAssetData::SerializeForCache (Archive && Ar) inline
Serialize as part of the registry cache.
This is not meant to be serialized as part of a package so it does not handle versions normally To version this data change FAssetRegistryVersion
Definition at line 711 of file AssetData.h.
References FAssetData(), Ar, FORCEINLINE, and SerializeForCacheWithTagsAndBundles().
SerializeForCacheInternal()
FORCEINLINE void FAssetData::SerializeForCacheInternal (FArchive & Ar, FAssetRegistryVersion::Type Version, void(* SerializeTagsAndBundles)(FArchive &, FAssetData &, FAssetRegistryVersion::Type)) private
The actual implementation of SerializeForCache.
Note that this function is force-inlined but defined in AssetData.cpp which is fine as functions will get inlined as long as they're defined before they are used for the first time by other functions (SerializeForCacheWithTagsAndBundles in this case)
References FAssetData(), Ar, and FORCEINLINE.
SerializeForCacheOldVersion()
template<class Archive> FORCEINLINE void FAssetData::SerializeForCacheOldVersion (Archive && Ar, FAssetRegistryVersion::Type Version = FAssetRegistryVersion::LatestVersion) inline
Serialize as part of the registry cache using legacy paths (versioned)
Definition at line 721 of file AssetData.h.
References FAssetData(), Ar, FORCEINLINE, FAssetRegistryVersion::LatestVersion, and SerializeForCacheOldVersionWithTagsAndBundles().
SerializeForCacheOldVersionWithTagsAndBundles()
void FAssetData::SerializeForCacheOldVersionWithTagsAndBundles (FArchive & Ar, FAssetRegistryVersion::Type Version, void(* SerializeTagsAndBundles)(FArchive &, FAssetData &, FAssetRegistryVersion::Type)) private
References FAssetData(), and Ar.
Referenced by SerializeForCacheOldVersion().
SerializeForCacheWithTagsAndBundles()
void FAssetData::SerializeForCacheWithTagsAndBundles (FArchive & Ar, void(* SerializeTagsAndBundles)(FArchive &, FAssetData &, FAssetRegistryVersion::Type)) private
References FAssetData(), and Ar.
Referenced by SerializeForCache().
SetChunkIDs() [1/2]
void FAssetData::SetChunkIDs (const FChunkArrayView & InChunkIDs)
References InChunkIDs.
SetChunkIDs() [2/2]
void FAssetData::SetChunkIDs (FChunkArray && InChunkIDs)
References InChunkIDs.
SetTagsAndAssetBundles()
void FAssetData::SetTagsAndAssetBundles (FAssetDataTagMap && Tags)
References Tags.
Shrink()
void FAssetData::Shrink () inline
Definition at line 371 of file AssetData.h.
References TagsAndValues.
ToSoftObjectPath()
FSoftObjectPath FAssetData::ToSoftObjectPath () const inline
Definition at line 337 of file AssetData.h.
References GetSoftObjectPath().
TryConvertShortClassNameToPathName()
FTopLevelAssetPath FAssetData::TryConvertShortClassNameToPathName (FName InClassName, ELogVerbosity::Type FailureMessageVerbosity = ELogVerbosity::Warning) static
Helper function that tries to convert short class name to path name.
References ELogVerbosity::Warning.
TryNetworkRead()
bool FAssetData::TryNetworkRead (FCbFieldView Field, bool bReadPackageName, FName InPackageName)
UE_DEPRECATED() [1/4]
FAssetData::UE_DEPRECATED (5. 1, "Class names are now represented by path names. Please use a version of FAssetData constructor that uses FTopLevelAssetPath.") const &
References UE_DEPRECATED().
UE_DEPRECATED() [2/4]
PRAGMA_ENABLE_DEPRECATION_WARNINGS FAssetData::UE_DEPRECATED (5. 1, "Class names are now represented by path names. Please use a version of FAssetData constructor that uses FTopLevelAssetPath.")
UE_DEPRECATED() [3/4]
FAssetData::UE_DEPRECATED (5. 1, "Class names are now represented by path names. Please use AssetClassPath.")
The name of the asset's class.
Referenced by UE_DEPRECATED().
UE_DEPRECATED() [4/4]
FAssetData::UE_DEPRECATED (5. 1, "Use SetChunkIDs/GetChunkIDs/AddChunkID instead.")
The IDs of the pakchunks this asset is located in for streaming install.
Empty if not assigned to a chunk
Friends And Related Symbol Documentation
GetTypeHash
FORCEINLINE uint32 GetTypeHash (const FAssetData & AssetData) friend
Definition at line 761 of file AssetData.h.
References FAssetData(), FORCEINLINE, GetTypeHash, and HashCombine().
Referenced by GetTypeHash.
Field Documentation
AssetClassPath
FTopLevelAssetPath FAssetData::AssetClassPath
The path of the asset's class, e.g.
/Script/Engine.StaticMesh
Definition at line 190 of file AssetData.h.
Referenced by GetExportTextName(), GetExportTextName(), GetFullName(), GetFullName(), IsRedirector(), and PrintAssetData().
AssetName
FName FAssetData::AssetName
The name of the asset without the package.
Definition at line 185 of file AssetData.h.
Referenced by AppendObjectPath(), IsUAsset(), IsValid(), operator!=(), operator<(), operator==(), operator>(), and PrintAssetData().
ChunkArrayRegistryHandle
UE::AssetRegistry::FChunkArrayRegistryHandle FAssetData::ChunkArrayRegistryHandle private
Definition at line 193 of file AssetData.h.
ChunkIDs
TInlineAllocator<2> FAssetData::ChunkIDs
Definition at line 224 of file AssetData.h.
InAssetClassName [1/2]
PRAGMA_ENABLE_DEPRECATION_WARNINGS FName FName FName FAssetData::InAssetClassName
Definition at line 256 of file AssetData.h.
InAssetClassName [2/2]
const FString FName FAssetData::InAssetClassName
Definition at line 258 of file AssetData.h.
InAssetName
PRAGMA_ENABLE_DEPRECATION_WARNINGS FName FName FAssetData::InAssetName
Definition at line 256 of file AssetData.h.
Referenced by FAssetData().
InChunkIDs [1/2]
PRAGMA_ENABLE_DEPRECATION_WARNINGS FName FName FName FAssetDataTagMap TArrayView<const int32> FAssetData::InChunkIDs = TArrayView<const int32>()
Definition at line 256 of file AssetData.h.
Referenced by FAssetData(), FAssetData(), SetChunkIDs(), and SetChunkIDs().
InChunkIDs [2/2]
const FString FName FAssetDataTagMap TArrayView<const int32> FAssetData::InChunkIDs = TArrayView<const int32>()
Definition at line 258 of file AssetData.h.
InObjectPath
const FString& FAssetData::InObjectPath
Definition at line 258 of file AssetData.h.
Referenced by FAssetData().
InPackageFlags [1/2]
PRAGMA_ENABLE_DEPRECATION_WARNINGS FName FName FName FAssetDataTagMap TArrayView<const int32> uint32 FAssetData::InPackageFlags = 0)
Definition at line 256 of file AssetData.h.
Referenced by FAssetData(), and FAssetData().
InPackageFlags [2/2]
const FString FName FAssetDataTagMap TArrayView<const int32> uint32 FAssetData::InPackageFlags = 0)
Definition at line 258 of file AssetData.h.
InPackagePath
PRAGMA_ENABLE_DEPRECATION_WARNINGS FName FAssetData::InPackagePath
Definition at line 256 of file AssetData.h.
Referenced by FAssetData().
InTags [1/2]
PRAGMA_ENABLE_DEPRECATION_WARNINGS FName FName FName FAssetDataTagMap FAssetData::InTags = FAssetDataTagMap()
Definition at line 256 of file AssetData.h.
Referenced by FAssetData(), and FAssetData().
InTags [2/2]
const FString FName FAssetDataTagMap FAssetData::InTags = FAssetDataTagMap()
Definition at line 258 of file AssetData.h.
PackageFlags
uint32 FAssetData::PackageFlags = 0
Asset package flags.
Definition at line 197 of file AssetData.h.
Referenced by GetAssetAccessSpecifier(), HasAllPackageFlags(), HasAnyPackageFlags(), and PrintAssetData().
PackageName
FName FAssetData::PackageName
The name of the package in which the asset is found, this is the full long package name such as /Game/Path/Package.
Definition at line 181 of file AssetData.h.
Referenced by AppendObjectPath(), DetectIsUAssetByNames(), GetPackage(), IsUAsset(), IsValid(), FSoundWaveLoadingBehaviorUtil::LoadAndCacheClass(), operator!=(), operator<(), operator==(), operator>(), and PrintAssetData().
PackagePath
FName FAssetData::PackagePath
The path to the package in which the asset is found, this is /Game/Path with the Package stripped off.
Definition at line 183 of file AssetData.h.
Referenced by PrintAssetData().
TaggedAssetBundles
TSharedPtr<FAssetBundleData, ESPMode::ThreadSafe> FAssetData::TaggedAssetBundles
The 'AssetBundles' tag key is separated from TagsAndValues and typed for performance reasons.
This is likely a temporary solution that will be generalized in some other fashion.
Definition at line 219 of file AssetData.h.
TagsAndValues
FAssetDataTagMapSharedView FAssetData::TagsAndValues
The map of values for properties that were marked AssetRegistrySearchable or added by GetAssetRegistryTags.
Definition at line 214 of file AssetData.h.
Referenced by EnumerateTags(), FindTag(), GetTagValue(), GetTagValue(), GetTagValue(), GetTagValue(), GetTagValueRef(), GetTagValueRef(), PrintAssetData(), and Shrink().
The documentation for this struct was generated from the following file:
Runtime/CoreUObject/Public/AssetRegistry/AssetData.h