Unreal Engine 5.6 C++ API: FCoreRedirects Struct Reference
FCoreRedirects Struct Reference
A container for all of the registered core-level redirects.
#include "CoreRedirects.h"
Data Structures
struct FRedirectNameMap
There is one of these for each registered set of redirect flags.
struct FRedirectTypeMap
Map from name of thing being mapped to full list.
struct FWildcardData
Container for managing Wildcard redirects (substrings, prefixes, suffixes)
Public Member Functions
UE_DEPRECATED (5.6, "Use GetHashOfRedirectsAffectingPackages(const TConstArrayView<FName> PackageNames, TArray<FBlake3Hash>& Hashes) instead.") static 1 void AppendHashOfRedirectsAffectingPackages(FBlake3 &Hasher
Iterate the list of PackageNames and append the hash of all redirects that affect the package, either redirecting from or to the package.
Static Public Member Functions
static void AddAssetRedirects (const TMap< FSoftObjectPath, FSoftObjectPath > &InRedirects)
Adds a collection of redirects as Type_Asset.
static bool AddKnownMissing (ECoreRedirectFlags Type, const FCoreRedirectObjectName &ObjectName, ECoreRedirectFlags Channel=ECoreRedirectFlags::Option_MissingLoad)
Adds the given combination of (Type, ObjectName, Channel) as a missing name; IsKnownMissing queries will now find it.
static bool AddRedirectList (TArrayView< const FCoreRedirect > Redirects, const FString &SourceString)
Adds an array of redirects to global list.
static void AppendHashOfGlobalRedirects (FBlake3 &Hasher)
Append the hash of all redirects that can affect multiple packages, or for which the affected packages are unknown.
static void ClearKnownMissing (ECoreRedirectFlags Type, ECoreRedirectFlags Channel=ECoreRedirectFlags::Option_MissingLoad)
static bool FindPreviousNames (ECoreRedirectFlags Type, const FCoreRedirectObjectName &NewObjectName, TArray< FCoreRedirectObjectName > &PreviousNames)
Returns list of names it may have been before.
static const TMap< FName, ECoreRedirectFlags > & GetConfigKeyMap ()
Gets map from config key -> Flags.
static ECoreRedirectFlags GetFlagsForTypeClass (UClass *TypeClass)
Goes from UClass Type to the type flag.
static ECoreRedirectFlags GetFlagsForTypeName (FName PackageName, FName TypeName)
Goes from the containing package and name of the type to the type flag.
static void GetHashOfRedirectsAffectingPackages (const TConstArrayView< FName > &PackageNames, TArray< FBlake3Hash > &Hashes)
For each package in PackageNames, compute the hash of all redirects that affect the package, either redirecting from or to the package.
static bool GetMatchingRedirects (ECoreRedirectFlags Type, const FCoreRedirectObjectName &OldObjectName, TArray< const FCoreRedirect * > &FoundRedirects, ECoreRedirectMatchFlags MatchFlags=ECoreRedirectMatchFlags::None)
Returns list of all core redirects that match requirements.
static FCoreRedirectObjectName GetRedirectedName (ECoreRedirectFlags Type, const FCoreRedirectObjectName &OldObjectName, ECoreRedirectMatchFlags MatchFlags=ECoreRedirectMatchFlags::None)
Returns a redirected version of the object name.
static const TMap< FString, FString > * GetValueRedirects (ECoreRedirectFlags Type, const FCoreRedirectObjectName &OldObjectName, ECoreRedirectMatchFlags MatchFlags=ECoreRedirectMatchFlags::None)
Returns map of String->String value redirects for the object name, or nullptr if none found.
static void Initialize ()
Run initialization steps that are needed before any data can be stored in FCoreRedirects.
static bool IsInDebugMode ()
Returns true if this is in debug mode that slows loading and adds additional warnings.
static bool IsInitialized ()
Returns true if this has ever been initialized.
static bool IsKnownMissing (ECoreRedirectFlags Type, const FCoreRedirectObjectName &ObjectName)
Returns true if this name has been registered as explicitly missing.
static bool ReadRedirectsFromIni (const FString &IniName)
Parse all redirects out of a given ini file.
static void RecordAddedObjectRedirector (const FSoftObjectPath &Source, const FSoftObjectPath &Dest)
Add the given Source->Path redirector to the summary used for AppendHashOfRedirectsAffectingPackages.
static void RecordRemovedObjectRedirector (const FSoftObjectPath &Source, const FSoftObjectPath &Dest)
Remove the given Source->Path redirector to the summary used for AppendHashOfRedirectsAffectingPackages.
static bool RedirectNameAndValues (ECoreRedirectFlags Type, const FCoreRedirectObjectName &OldObjectName, FCoreRedirectObjectName &NewObjectName, const FCoreRedirect **FoundValueRedirect, ECoreRedirectMatchFlags MatchFlags=ECoreRedirectMatchFlags::None)
Performs both a name redirect and gets a value redirect struct if it exists.
static void RemoveAllAssetRedirects ()
Clears all redirects added via AddAssetRedirects.
static bool RemoveKnownMissing (ECoreRedirectFlags Type, const FCoreRedirectObjectName &ObjectName, ECoreRedirectFlags Channel=ECoreRedirectFlags::Option_MissingLoad)
Removes the given combination of (Type, ObjectName, Channel) as a missing name.
static bool RemoveRedirectList (TArrayView< const FCoreRedirect > Redirects, const FString &SourceString)
Removes an array of redirects from global list.
static bool RunTests ()
Runs set of redirector tests, returns false on failure.
static void ValidateAllRedirects ()
Validates all known redirects and warn if they seem to point to missing things or violate other constraints.
static bool ValidateAssetRedirects ()
Validates asset redirects and warns if chains are detected.
static void ValidateRedirectList (TArrayView< const FCoreRedirect > Redirects, const FString &SourceString)
Validate a named list of redirects.
Data Fields
TConstArrayView< FName > PackageNames
Private Member Functions
FCoreRedirects ()
Static only class, never constructed.
Static Private Member Functions
static bool AddRedirectListUnderWriteLock (TArrayView< const FCoreRedirect > Redirects, const FString &SourceString, FScopeCoreRedirectsWriteLockedContext &LockedContext)
Internal implementation for AddRedirectList that requires a write lock to already have been acquired.
static bool AddSingleRedirectUnderWriteLock (const FCoreRedirect &NewRedirect, const FString &SourceString, FScopeCoreRedirectsWriteLockedContext &LockedContext)
Internal implementation for AddSingleRedirect that requires a write lock to already have been acquired.
static bool GetMatchingRedirectsUnderReadLock (ECoreRedirectFlags Type, const FCoreRedirectObjectName &OldObjectName, TArray< const FCoreRedirect * > &FoundRedirects, ECoreRedirectMatchFlags MatchFlags, FScopeCoreRedirectsReadLockedContext &LockedContext)
Internal implementation for GetMatchingRedirects that requires a read lock to already have been acquired.
static bool RedirectNameAndValuesUnderReadLock (ECoreRedirectFlags Type, const FCoreRedirectObjectName &OldObjectName, FCoreRedirectObjectName &NewObjectName, const FCoreRedirect **FoundValueRedirect, ECoreRedirectMatchFlags MatchFlags, FScopeCoreRedirectsReadLockedContext &LockedContext)
Internal implementation for RedirectNameAndValues that requires a read lock to already have been acquired.
static void RegisterNativeRedirectsUnderWriteLock (FScopeCoreRedirectsWriteLockedContext &LockedContext)
Add native redirects, called before ini is parsed for the first time.
static bool RemoveSingleRedirectUnderWriteLock (const FCoreRedirect &OldRedirect, const FString &SourceString, FScopeCoreRedirectsWriteLockedContext &LockedContext)
Internal implementation for RemoveSingleRedirect that requires a write lock to already have been acquired.
static bool ValidateAssetRedirectsUnderReadLock (FScopeCoreRedirectsReadLockedContext &LockedContext)
Internal implementation for ValidateAssetRedirects that requires a read lock to already have been acquired.
Friends
struct FCoreRedirectsContext
Detailed Description
A container for all of the registered core-level redirects.
Definition at line 315 of file CoreRedirects.h.
Constructor & Destructor Documentation
FCoreRedirects()
FCoreRedirects::FCoreRedirects () private
Static only class, never constructed.
Member Function Documentation
AddAssetRedirects()
void FCoreRedirects::AddAssetRedirects (const TMap< FSoftObjectPath, FSoftObjectPath > & InRedirects) static
Adds a collection of redirects as Type_Asset.
These allow FCoreRedirects to support the functions of UObjectRedirector. Any duplicate sources are logged and discarded (only the first redirect from a path is used) Package redirects corresponding to the soft object paths are implicitly created.
AddKnownMissing()
bool FCoreRedirects::AddKnownMissing (ECoreRedirectFlags Type, const FCoreRedirectObjectName & ObjectName, ECoreRedirectFlags Channel = ECoreRedirectFlags::Option_MissingLoad) static
Adds the given combination of (Type, ObjectName, Channel) as a missing name; IsKnownMissing queries will now find it.
Parameters
Type Combination of the ECoreRedirectFlags::Type_* flags specifying the type of the object now known to be missing
ObjectName The name of the object now known to be missing
Channel may be Option_MissingLoad or Option_None; used to distinguish between detected-at-runtime and specified-by-ini
References Option_MissingLoad.
AddRedirectList()
bool FCoreRedirects::AddRedirectList (TArrayView< const FCoreRedirect > Redirects, const FString & SourceString) static
Adds an array of redirects to global list.
AddRedirectListUnderWriteLock()
bool FCoreRedirects::AddRedirectListUnderWriteLock (TArrayView< const FCoreRedirect > Redirects, const FString & SourceString, FScopeCoreRedirectsWriteLockedContext & LockedContext) static private
Internal implementation for AddRedirectList that requires a write lock to already have been acquired.
AddSingleRedirectUnderWriteLock()
bool FCoreRedirects::AddSingleRedirectUnderWriteLock (const FCoreRedirect & NewRedirect, const FString & SourceString, FScopeCoreRedirectsWriteLockedContext & LockedContext) static private
Internal implementation for AddSingleRedirect that requires a write lock to already have been acquired.
AppendHashOfGlobalRedirects()
void FCoreRedirects::AppendHashOfGlobalRedirects (FBlake3 & Hasher) static
Append the hash of all redirects that can affect multiple packages, or for which the affected packages are unknown.
Used in Incremental cooking to invalidate the cooked version of packages when CoreRedirects change.
References AppendHashOfGlobalRedirects().
Referenced by AppendHashOfGlobalRedirects().
ClearKnownMissing()
void FCoreRedirects::ClearKnownMissing (ECoreRedirectFlags Type, ECoreRedirectFlags Channel = ECoreRedirectFlags::Option_MissingLoad) static
References Option_MissingLoad.
FindPreviousNames()
bool FCoreRedirects::FindPreviousNames (ECoreRedirectFlags Type, const FCoreRedirectObjectName & NewObjectName, TArray< FCoreRedirectObjectName > & PreviousNames) static
Returns list of names it may have been before.
Referenced by FExternalPackageHelper::LoadObjectsFromExternalPackages().
GetConfigKeyMap()
const TMap< FName, ECoreRedirectFlags > & FCoreRedirects::GetConfigKeyMap () static
Gets map from config key -> Flags.
It may only be accessed once it becomes constant data after the system is initialized
GetFlagsForTypeClass()
ECoreRedirectFlags FCoreRedirects::GetFlagsForTypeClass (UClass * TypeClass) static
Goes from UClass Type to the type flag.
GetFlagsForTypeName()
ECoreRedirectFlags FCoreRedirects::GetFlagsForTypeName (FName PackageName, FName TypeName) static
Goes from the containing package and name of the type to the type flag.
References PackageName.
GetHashOfRedirectsAffectingPackages()
void FCoreRedirects::GetHashOfRedirectsAffectingPackages (const TConstArrayView< FName > & PackageNames, TArray< FBlake3Hash > & Hashes) static
For each package in PackageNames, compute the hash of all redirects that affect the package, either redirecting from or to the package.
It doesn't include the GlobalRedirects. Used in Incremental cooking to invalidate the cooked version of packages when CoreRedirects change.
References GetHashOfRedirectsAffectingPackages(), and PackageNames.
Referenced by GetHashOfRedirectsAffectingPackages().
GetMatchingRedirects()
bool FCoreRedirects::GetMatchingRedirects (ECoreRedirectFlags Type, const FCoreRedirectObjectName & OldObjectName, TArray< const FCoreRedirect * > & FoundRedirects, ECoreRedirectMatchFlags MatchFlags = ECoreRedirectMatchFlags::None) static
Returns list of all core redirects that match requirements.
References None.
GetMatchingRedirectsUnderReadLock()
bool FCoreRedirects::GetMatchingRedirectsUnderReadLock (ECoreRedirectFlags Type, const FCoreRedirectObjectName & OldObjectName, TArray< const FCoreRedirect * > & FoundRedirects, ECoreRedirectMatchFlags MatchFlags, FScopeCoreRedirectsReadLockedContext & LockedContext) static private
Internal implementation for GetMatchingRedirects that requires a read lock to already have been acquired.
GetRedirectedName()
FCoreRedirectObjectName FCoreRedirects::GetRedirectedName (ECoreRedirectFlags Type, const FCoreRedirectObjectName & OldObjectName, ECoreRedirectMatchFlags MatchFlags = ECoreRedirectMatchFlags::None) static
Returns a redirected version of the object name.
If there are no valid redirects, it will return the original name
References None.
Referenced by RigVMTypeUtils::FindObjectFromCPPTypeObjectPath().
GetValueRedirects()
const TMap< FString, FString > * FCoreRedirects::GetValueRedirects (ECoreRedirectFlags Type, const FCoreRedirectObjectName & OldObjectName, ECoreRedirectMatchFlags MatchFlags = ECoreRedirectMatchFlags::None) static
Returns map of String->String value redirects for the object name, or nullptr if none found.
References None.
Initialize()
void FCoreRedirects::Initialize () static
Run initialization steps that are needed before any data can be stored in FCoreRedirects.
Reads can occur before this, but no redirects will exist and redirect queries will all return empty.
IsInDebugMode()
bool FCoreRedirects::IsInDebugMode () static
Returns true if this is in debug mode that slows loading and adds additional warnings.
IsInitialized()
bool FCoreRedirects::IsInitialized () static
Returns true if this has ever been initialized.
IsKnownMissing()
bool FCoreRedirects::IsKnownMissing (ECoreRedirectFlags Type, const FCoreRedirectObjectName & ObjectName) static
Returns true if this name has been registered as explicitly missing.
ReadRedirectsFromIni()
bool FCoreRedirects::ReadRedirectsFromIni (const FString & IniName) static
Parse all redirects out of a given ini file.
RecordAddedObjectRedirector()
void FCoreRedirects::RecordAddedObjectRedirector (const FSoftObjectPath & Source, const FSoftObjectPath & Dest) static
Add the given Source->Path redirector to the summary used for AppendHashOfRedirectsAffectingPackages.
References RecordAddedObjectRedirector(), and Source.
Referenced by RecordAddedObjectRedirector().
RecordRemovedObjectRedirector()
void FCoreRedirects::RecordRemovedObjectRedirector (const FSoftObjectPath & Source, const FSoftObjectPath & Dest) static
Remove the given Source->Path redirector to the summary used for AppendHashOfRedirectsAffectingPackages.
References RecordRemovedObjectRedirector(), and Source.
Referenced by RecordRemovedObjectRedirector().
RedirectNameAndValues()
bool FCoreRedirects::RedirectNameAndValues (ECoreRedirectFlags Type, const FCoreRedirectObjectName & OldObjectName, FCoreRedirectObjectName & NewObjectName, const FCoreRedirect ** FoundValueRedirect, ECoreRedirectMatchFlags MatchFlags = ECoreRedirectMatchFlags::None) static
Performs both a name redirect and gets a value redirect struct if it exists.
Returns true if either redirect found
References None.
Referenced by RigVMTypeUtils::FindObjectGlobally().
RedirectNameAndValuesUnderReadLock()
bool FCoreRedirects::RedirectNameAndValuesUnderReadLock (ECoreRedirectFlags Type, const FCoreRedirectObjectName & OldObjectName, FCoreRedirectObjectName & NewObjectName, const FCoreRedirect ** FoundValueRedirect, ECoreRedirectMatchFlags MatchFlags, FScopeCoreRedirectsReadLockedContext & LockedContext) static private
Internal implementation for RedirectNameAndValues that requires a read lock to already have been acquired.
RegisterNativeRedirectsUnderWriteLock()
void FCoreRedirects::RegisterNativeRedirectsUnderWriteLock (FScopeCoreRedirectsWriteLockedContext & LockedContext) static private
Add native redirects, called before ini is parsed for the first time.
RemoveAllAssetRedirects()
void FCoreRedirects::RemoveAllAssetRedirects () static
Clears all redirects added via AddAssetRedirects.
RemoveKnownMissing()
bool FCoreRedirects::RemoveKnownMissing (ECoreRedirectFlags Type, const FCoreRedirectObjectName & ObjectName, ECoreRedirectFlags Channel = ECoreRedirectFlags::Option_MissingLoad) static
Removes the given combination of (Type, ObjectName, Channel) as a missing name.
Parameters
Type Combination of the ECoreRedirectFlags::Type_* flags specifying the type of the object that has just been loaded.
ObjectName The name of the object that has just been loaded.
Channel may be Option_MissingLoad or Option_None; used to distinguish between detected-at-runtime and specified-by-ini
References Option_MissingLoad.
RemoveRedirectList()
bool FCoreRedirects::RemoveRedirectList (TArrayView< const FCoreRedirect > Redirects, const FString & SourceString) static
Removes an array of redirects from global list.
RemoveSingleRedirectUnderWriteLock()
bool FCoreRedirects::RemoveSingleRedirectUnderWriteLock (const FCoreRedirect & OldRedirect, const FString & SourceString, FScopeCoreRedirectsWriteLockedContext & LockedContext) static private
Internal implementation for RemoveSingleRedirect that requires a write lock to already have been acquired.
RunTests()
bool FCoreRedirects::RunTests () static
Runs set of redirector tests, returns false on failure.
UE_DEPRECATED()
FCoreRedirects::UE_DEPRECATED (5. 6, "Use GetHashOfRedirectsAffectingPackages(const TConstArrayView<FName> PackageNames, TArray<FBlake3Hash>& Hashes) instead.") &
Iterate the list of PackageNames and append the hash of all redirects that affect the package, either redirecting from or to the package.
Used in Incremental cooking to invalidate the cooked version of packages when CoreRedirects change.
ValidateAllRedirects()
void FCoreRedirects::ValidateAllRedirects () static
Validates all known redirects and warn if they seem to point to missing things or violate other constraints.
ValidateAssetRedirects()
bool FCoreRedirects::ValidateAssetRedirects () static
Validates asset redirects and warns if chains are detected.
Chains should be resolved before adding asset redirects.
ValidateAssetRedirectsUnderReadLock()
bool FCoreRedirects::ValidateAssetRedirectsUnderReadLock (FScopeCoreRedirectsReadLockedContext & LockedContext) static private
Internal implementation for ValidateAssetRedirects that requires a read lock to already have been acquired.
ValidateRedirectList()
void FCoreRedirects::ValidateRedirectList (TArrayView< const FCoreRedirect > Redirects, const FString & SourceString) static
Validate a named list of redirects.
Friends And Related Symbol Documentation
FCoreRedirectsContext
friend struct FCoreRedirectsContext friend
Definition at line 521 of file CoreRedirects.h.
References FCoreRedirectsContext.
Referenced by FCoreRedirectsContext.
Field Documentation
PackageNames
TConstArrayView<FName> FCoreRedirects::PackageNames
Definition at line 406 of file CoreRedirects.h.
Referenced by GetHashOfRedirectsAffectingPackages().
The documentation for this struct was generated from the following file:
Runtime/CoreUObject/Public/UObject/CoreRedirects.h