Unreal Engine 5.6 C++ API: FCbAttachment::FBinaryValue Struct Reference
FCbAttachment::FBinaryValue Struct Reference
Public Member Functions
template<typename BufferType, decltype(FCompositeBuffer(DeclVal< BufferType >().MakeOwned())) * = nullptr>
FBinaryValue (BufferType &&InBuffer)
template<typename BufferType, decltype(FCompositeBuffer(DeclVal< BufferType >().MakeOwned())) * = nullptr>
FBinaryValue (BufferType &&InBuffer, const FIoHash &InHash)
Data Fields
FCompositeBuffer Buffer
FIoHash Hash
Detailed Description
Definition at line 47 of file CompactBinaryPackage.h.
Constructor & Destructor Documentation
FBinaryValue() [1/2]
template<typename BufferType, decltype(FCompositeBuffer(DeclVal< BufferType >().MakeOwned())) * = nullptr> FCbAttachment::FBinaryValue::FBinaryValue (BufferType && InBuffer) inline explicit
Definition at line 53 of file CompactBinaryPackage.h.
References Buffer, Forward(), and Hash.
FBinaryValue() [2/2]
template<typename BufferType, decltype(FCompositeBuffer(DeclVal< BufferType >().MakeOwned())) * = nullptr> FCbAttachment::FBinaryValue::FBinaryValue (BufferType && InBuffer, const FIoHash & InHash) inline explicit
Definition at line 60 of file CompactBinaryPackage.h.
References Buffer, checkSlow, Forward(), Hash, and FIoHash::HashBuffer().
Field Documentation
Buffer
FCompositeBuffer FCbAttachment::FBinaryValue::Buffer
Definition at line 49 of file CompactBinaryPackage.h.
Referenced by FBinaryValue(), FBinaryValue(), and FCbAttachment::FCbAttachment().
Hash
FIoHash FCbAttachment::FBinaryValue::Hash
Definition at line 50 of file CompactBinaryPackage.h.
Referenced by FBinaryValue(), and FBinaryValue().
The documentation for this struct was generated from the following file:
Runtime/Core/Public/Serialization/CompactBinaryPackage.h