Unreal Engine 5.6 C++ API: FNodeDebugData Struct Reference
FNodeDebugData Struct Reference
#include "AnimNodeBase.h"
Data Structures
struct DebugItem
struct FFlattenedDebugData
Public Member Functions
FNodeDebugData (const class UAnimInstance *InAnimInstance)
FNodeDebugData (const class UAnimInstance *InAnimInstance, const float AbsWeight, FString InNodeDescription, FNodeDebugData *InRootNodePtr)
void AddDebugItem (FString DebugData, bool bPoseSource=false)
FNodeDebugData & BranchFlow (float BranchWeight, FString InNodeDescription=FString())
FNodeDebugData * GetCachePoseDebugData (float GlobalWeight)
TArray< FFlattenedDebugData > GetFlattenedDebugData ()
void GetFlattenedDebugData (TArray< FFlattenedDebugData > &FlattenedDebugData, int32 Indent, int32 &ChainID)
template<class Type>
FString GetNodeName (Type *Node)
Data Fields
const UAnimInstance * AnimInstance
Private Attributes
float AbsoluteWeight
This nodes final contribution weight (based on its own weight and the weight of its parents).
TArray< DebugItem > NodeChain
Nodes that we are dependent on.
FString NodeDescription
Additional info provided, used in GetNodeName.
FNodeDebugData * RootNodePtr
Pointer to RootNode.
TArray< FNodeDebugData > SaveCachePoseNodes
SaveCachePose Nodes.
Detailed Description
Definition at line 641 of file AnimNodeBase.h.
Constructor & Destructor Documentation
FNodeDebugData() [1/2]
FNodeDebugData::FNodeDebugData (const class UAnimInstance * InAnimInstance) inline
Definition at line 686 of file AnimNodeBase.h.
References AbsoluteWeight, ANIM_NODE_DEBUG_MAX_CACHEPOSE, AnimInstance, RootNodePtr, and SaveCachePoseNodes.
Referenced by FNodeDebugData(), BranchFlow(), and GetCachePoseDebugData().
FNodeDebugData() [2/2]
FNodeDebugData::FNodeDebugData (const class UAnimInstance * InAnimInstance, const float AbsWeight, FString InNodeDescription, FNodeDebugData * InRootNodePtr) inline
Definition at line 692 of file AnimNodeBase.h.
References FNodeDebugData(), AbsoluteWeight, AnimInstance, NodeDescription, and RootNodePtr.
Member Function Documentation
AddDebugItem()
void FNodeDebugData::AddDebugItem (FString DebugData, bool bPoseSource = false)
BranchFlow()
FNodeDebugData & FNodeDebugData::BranchFlow (float BranchWeight, FString InNodeDescription = FString())
References FNodeDebugData().
GetCachePoseDebugData()
FNodeDebugData * FNodeDebugData::GetCachePoseDebugData (float GlobalWeight)
References FNodeDebugData().
GetFlattenedDebugData() [1/2]
TArray< FFlattenedDebugData > FNodeDebugData::GetFlattenedDebugData () inline
Definition at line 713 of file AnimNodeBase.h.
References GetFlattenedDebugData().
Referenced by GetFlattenedDebugData().
GetFlattenedDebugData() [2/2]
void FNodeDebugData::GetFlattenedDebugData (TArray< FFlattenedDebugData > & FlattenedDebugData, int32 Indent, int32 & ChainID)
GetNodeName()
template<class Type> FString FNodeDebugData::GetNodeName (Type * Node) inline
Definition at line 704 of file AnimNodeBase.h.
References AbsoluteWeight, NodeDescription, and TEXT.
Field Documentation
AbsoluteWeight
float FNodeDebugData::AbsoluteWeight private
This nodes final contribution weight (based on its own weight and the weight of its parents).
Definition at line 659 of file AnimNodeBase.h.
Referenced by FNodeDebugData(), FNodeDebugData(), and GetNodeName().
AnimInstance
const UAnimInstance* FNodeDebugData::AnimInstance
Definition at line 722 of file AnimNodeBase.h.
Referenced by FNodeDebugData(), and FNodeDebugData().
NodeChain
TArray<DebugItem> FNodeDebugData::NodeChain private
Nodes that we are dependent on.
Definition at line 662 of file AnimNodeBase.h.
NodeDescription
FString FNodeDebugData::NodeDescription private
Additional info provided, used in GetNodeName.
States machines can provide the state names for the Root Nodes to use for example.
Definition at line 665 of file AnimNodeBase.h.
Referenced by FNodeDebugData(), and GetNodeName().
RootNodePtr
FNodeDebugData* FNodeDebugData::RootNodePtr private
Pointer to RootNode.
Definition at line 668 of file AnimNodeBase.h.
Referenced by FNodeDebugData(), and FNodeDebugData().
SaveCachePoseNodes
TArray<FNodeDebugData> FNodeDebugData::SaveCachePoseNodes private
SaveCachePose Nodes.
Definition at line 671 of file AnimNodeBase.h.
Referenced by FNodeDebugData().
The documentation for this struct was generated from the following file:
Runtime/Engine/Classes/Animation/AnimNodeBase.h