Unreal Engine 5.6 C++ API: UE::Geometry::TFrame3< RealType > Struct Template Reference
UE::Geometry::TFrame3< RealType > Struct Template Reference
TFrame3 is an object that represents an oriented 3D coordinate frame, ie orthogonal X/Y/Z axes at a point in space.
#include "FrameTypes.h"
Public Member Functions
TFrame3 ()
Construct a frame positioned at (0,0,0) aligned to the unit axes.
TFrame3 (const FPlane &Plane)
Construct a Frame from an FPlane.
TFrame3 (const FTransform &Transform)
Construct a Frame from an FTransform.
TFrame3 (const FVector &OriginIn, const FQuat &RotationIn)
Construct a Frame from an FVector and FQuat.
template<typename RealType2>
TFrame3 (const TFrame3< RealType2 > &OtherFrame)
Convert between TFrame of different types.
TFrame3 (const TVector< RealType > &OriginIn)
Construct a frame at the given Origin aligned to the unit axes.
TFrame3 (const TVector< RealType > &OriginIn, const TQuaternion< RealType > RotationIn)
Construct a Frame from the given Origin and Rotation.
TFrame3 (const TVector< RealType > &OriginIn, const TVector< RealType > &SetZ)
Construct a frame with the Z axis aligned to a target axis.
TFrame3 (const TVector< RealType > &OriginIn, const TVector< RealType > &X, const TVector< RealType > &Y, const TVector< RealType > &Z)
Construct Frame from X/Y/Z axis vectors.
void AlignAxis (int AxisIndex, const TVector< RealType > &ToDirection)
Align an axis of this frame with a target direction.
void ConstrainedAlignAxis (int AxisIndex, const TVector< RealType > &ToDirection, const TVector< RealType > &AroundVector)
Compute rotation around vector that best-aligns axis of frame with target direction.
void ConstrainedAlignPerpAxes (int PerpAxis1=0, int PerpAxis2=1, int NormalAxis=2, const TVector< RealType > &UpAxis=TVector< RealType >::UnitZ(), const TVector< RealType > &FallbackAxis=TVector< RealType >::UnitX(), RealType UpDotTolerance=(RealType) 0.707)
Compute rotation around NormalAxis that best-aligns one of the other two frame axes with either given UpAxis or FallbackAxis (FallbackAxis is required if Dot(NormalAxis,UpAxis) > UpDotTolerance, ie if the Normal and Up directions are too closely aligned.
TFrame3< RealType > FromFrame (const TFrame3< RealType > &Frame) const
TQuaternion< RealType > FromFrame (const TQuaternion< RealType > &Quat) const
TRay< RealType > FromFrame (const TRay< RealType > &Ray) const
TVector< RealType > FromFramePoint (const TVector< RealType > &Point) const
TVector< RealType > FromFrameVector (const TVector< RealType > &Vector) const
TVector< RealType > FromPlaneUV (const TVector2< RealType > &PosUV, int PlaneNormalAxis=2) const
Map a point from local UV plane coordinates to the corresponding 3D point in one of the planes of the frame.
void GetAxes (TVector< RealType > &X, TVector< RealType > &Y, TVector< RealType > &Z) const
TVector< RealType > GetAxis (int AxisIndex) const
TVector< RealType > PointAt (const TVector< RealType > &Point) const
TVector< RealType > PointAt (RealType X, RealType Y, RealType Z) const
bool RayPlaneIntersection (const TVector< RealType > &RayOrigin, const TVector< RealType > &RayDirection, int PlaneNormalAxis, UE::Math::TVector< RealType > &HitPointOut) const
Compute intersection of ray with plane defined by frame origin and axis as normal.
void Rotate (const TQuaternion< RealType > &Quat)
Rotate this frame by given quaternion.
FPlane ToFPlane () const
TFrame3< RealType > ToFrame (const TFrame3< RealType > &Frame) const
TQuaternion< RealType > ToFrame (const TQuaternion< RealType > &Quat) const
TRay< RealType > ToFrame (const TRay< RealType > &Ray) const
TVector< RealType > ToFramePoint (const TVector< RealType > &Point) const
TVector< RealType > ToFrameVector (const TVector< RealType > &Vector) const
FTransform ToFTransform () const
FTransform ToInverseFTransform () const
TTransformSRT3< RealType > ToInverseTransform () const
TVector< RealType > ToPlane (const TVector< RealType > &Pos, int PlaneNormalAxis=2) const
Project a point onto one of the planes of the frame.
TVector2< RealType > ToPlaneUV (const TVector< RealType > &Pos, int PlaneNormalAxis=2) const
Project 3D point into plane and convert to UV coordinates in that plane.
TTransformSRT3< RealType > ToTransform () const
void Transform (const FTransform &XForm)
transform this frame by the given transform.
void Transform (const TTransformSRT3< RealType > &XForm)
transform this frame by the given transform.
TVector< RealType > X () const
TVector< RealType > Y () const
TVector< RealType > Z () const
Data Fields
TVector< RealType > Origin
Origin of the frame.
TQuaternion< RealType > Rotation
Rotation of the frame.
Detailed Description
template<typename RealType>
struct UE::Geometry::TFrame3< RealType >
TFrame3 is an object that represents an oriented 3D coordinate frame, ie orthogonal X/Y/Z axes at a point in space.
One can think of this Frame as a local coordinate space measured along these axes. Functions are provided to map geometric objects to/from the Frame coordinate space.
Internally the representation is the same as an FTransform, except a Frame has no Scale.
Definition at line 26 of file FrameTypes.h.
Constructor & Destructor Documentation
TFrame3() [1/9]
template<typename RealType> UE::Geometry::TFrame3< RealType >::TFrame3 () inline
Construct a frame positioned at (0,0,0) aligned to the unit axes.
Definition at line 41 of file FrameTypes.h.
Referenced by UE::Geometry::TFrame3< float >::FromFrame(), and UE::Geometry::TFrame3< float >::ToFrame().
TFrame3() [2/9]
template<typename RealType> UE::Geometry::TFrame3< RealType >::TFrame3 (const TVector< RealType > & OriginIn) inline explicit
Construct a frame at the given Origin aligned to the unit axes.
Definition at line 50 of file FrameTypes.h.
TFrame3() [3/9]
template<typename RealType> UE::Geometry::TFrame3< RealType >::TFrame3 (const TVector< RealType > & OriginIn, const TQuaternion< RealType > RotationIn) inline
Construct a Frame from the given Origin and Rotation.
Definition at line 59 of file FrameTypes.h.
TFrame3() [4/9]
template<typename RealType> UE::Geometry::TFrame3< RealType >::TFrame3 (const TVector< RealType > & OriginIn, const TVector< RealType > & SetZ) inline
Construct a frame with the Z axis aligned to a target axis.
Parameters
OriginIn origin of frame
SetZ target Z axis
Definition at line 70 of file FrameTypes.h.
TFrame3() [5/9]
template<typename RealType> UE::Geometry::TFrame3< RealType >::TFrame3 (const TVector< RealType > & OriginIn, const TVector< RealType > & X, const TVector< RealType > & Y, const TVector< RealType > & Z) inline
Construct Frame from X/Y/Z axis vectors.
Vectors must be mutually orthogonal.
Parameters
OriginIn origin of frame
X desired X axis of frame
Y desired Y axis of frame
Z desired Z axis of frame
Definition at line 83 of file FrameTypes.h.
TFrame3() [6/9]
template<typename RealType> UE::Geometry::TFrame3< RealType >::TFrame3 (const FTransform & Transform) inline explicit
Construct a Frame from an FTransform.
Definition at line 90 of file FrameTypes.h.
TFrame3() [7/9]
template<typename RealType> UE::Geometry::TFrame3< RealType >::TFrame3 (const FPlane & Plane) inline explicit
Construct a Frame from an FPlane.
Definition at line 97 of file FrameTypes.h.
TFrame3() [8/9]
template<typename RealType> UE::Geometry::TFrame3< RealType >::TFrame3 (const FVector & OriginIn, const FQuat & RotationIn) inline explicit
Construct a Frame from an FVector and FQuat.
Definition at line 106 of file FrameTypes.h.
TFrame3() [9/9]
template<typename RealType> template<typename RealType2> UE::Geometry::TFrame3< RealType >::TFrame3 (const TFrame3< RealType2 > & OtherFrame) inline explicit
Convert between TFrame of different types.
Definition at line 114 of file FrameTypes.h.
Member Function Documentation
AlignAxis()
template<typename RealType> void UE::Geometry::TFrame3< RealType >::AlignAxis (int AxisIndex, const TVector< RealType > & ToDirection) inline
Align an axis of this frame with a target direction.
Parameters
AxisIndex which axis to align
ToDirection target direction
Definition at line 379 of file FrameTypes.h.
Referenced by UE::Geometry::FGeneralizedCylinderGenerator::Generate(), and UE::Geometry::TMeshLocalParam< PointSetType >::PropagateUV().
ConstrainedAlignAxis()
template<typename RealType> void UE::Geometry::TFrame3< RealType >::ConstrainedAlignAxis (int AxisIndex, const TVector< RealType > & ToDirection, const TVector< RealType > & AroundVector) inline
Compute rotation around vector that best-aligns axis of frame with target direction.
Parameters
AxisIndex which axis to try to align
ToDirection target direction
AroundVector rotation is constrained to be around this vector (ie this direction in frame stays constant)
Definition at line 392 of file FrameTypes.h.
Referenced by UE::Geometry::TFrame3< float >::ConstrainedAlignPerpAxes().
ConstrainedAlignPerpAxes()
template<typename RealType> void UE::Geometry::TFrame3< RealType >::ConstrainedAlignPerpAxes (int PerpAxis1 = 0, int PerpAxis2 = 1, int NormalAxis = 2, const TVector< RealType > & UpAxis = TVector<RealType>::UnitZ(), const TVector< RealType > & FallbackAxis = TVector<RealType>::UnitX(), RealType UpDotTolerance = (RealType)0.707) inline
Compute rotation around NormalAxis that best-aligns one of the other two frame axes with either given UpAxis or FallbackAxis (FallbackAxis is required if Dot(NormalAxis,UpAxis) > UpDotTolerance, ie if the Normal and Up directions are too closely aligned.
Basically this divides direction-sphere into three regions - polar caps with size defined by UpDotTolerance, and a wide equator band covering the rest. When crossing between these regions the alignment has a discontinuity. It is impossible to avoid this discontinuity because it is impossible to comb a sphere.
Parameters
PerpAxis1 Index of first axis orthogonal to NormalAxis
PerpAxis2 Index of second axis orthogonal to NormalAxis
NormalAxis Axis of frame to rotate around
UpAxis Target axis in equator region, defaults to UnitZ
FallbackAxis Target axis in polar region, defaults to UnitX
UpDotTolerance defaults to cos(45), ie flip between regions happens roughly half way to poles
Definition at line 416 of file FrameTypes.h.
FromFrame() [1/3]
template<typename RealType> TFrame3< RealType > UE::Geometry::TFrame3< RealType >::FromFrame (const TFrame3< RealType > & Frame) const inline
Returns
input Frame transformed from local coordinate system of this Frame into "World" coordinate system
Definition at line 265 of file FrameTypes.h.
FromFrame() [2/3]
template<typename RealType> TQuaternion< RealType > UE::Geometry::TFrame3< RealType >::FromFrame (const TQuaternion< RealType > & Quat) const inline
Returns
input Quaternion transformed from local coordinate system of Frame into "World" coordinate system
Definition at line 241 of file FrameTypes.h.
FromFrame() [3/3]
template<typename RealType> TRay< RealType > UE::Geometry::TFrame3< RealType >::FromFrame (const TRay< RealType > & Ray) const inline
Returns
input Ray transformed from local coordinate system of Frame into "World" coordinate system
Definition at line 253 of file FrameTypes.h.
FromFramePoint()
template<typename RealType> TVector< RealType > UE::Geometry::TFrame3< RealType >::FromFramePoint (const TVector< RealType > & Point) const inline
Returns
input Point transformed from local coordinate system of Frame into "World" coordinate system
Definition at line 217 of file FrameTypes.h.
Referenced by FBaseKelvinletBrushOp::DisplaceKelvinlet(), UE::Geometry::TFrame3< float >::FromFrame(), UE::Geometry::TFrame3< float >::FromFrame(), and FBaseKelvinletBrushOp::IntegrateKelvinlet().
FromFrameVector()
template<typename RealType> TVector< RealType > UE::Geometry::TFrame3< RealType >::FromFrameVector (const TVector< RealType > & Vector) const inline
Returns
input Vector transformed from local coordinate system of Frame into "World" coordinate system
Definition at line 229 of file FrameTypes.h.
Referenced by FMoveBrushOp::ApplyStamp().
FromPlaneUV()
template<typename RealType> TVector< RealType > UE::Geometry::TFrame3< RealType >::FromPlaneUV (const TVector2< RealType > & PosUV, int PlaneNormalAxis = 2) const inline
Map a point from local UV plane coordinates to the corresponding 3D point in one of the planes of the frame.
Parameters
PosUV local UV plane coordinates
PlaneNormalAxis which plane to map to, identified by perpendicular normal. Default is 2, ie normal is Z, plane is (X,Y)
Returns
3D coordinates in frame's plane (including Origin translation)
Definition at line 304 of file FrameTypes.h.
GetAxes()
template<typename RealType> void UE::Geometry::TFrame3< RealType >::GetAxes (TVector< RealType > & X, TVector< RealType > & Y, TVector< RealType > & Z) const inline
Returns
X/Y/Z axes of frame. This is more efficient than calculating each axis separately.
Definition at line 144 of file FrameTypes.h.
GetAxis()
template<typename RealType> TVector< RealType > UE::Geometry::TFrame3< RealType >::GetAxis (int AxisIndex) const inline
Parameters
AxisIndex index of axis of frame, either 0, 1, or 2
Returns
axis vector
Definition at line 125 of file FrameTypes.h.
Referenced by UE::Geometry::TFrame3< float >::AlignAxis(), UE::Geometry::TFrame3< float >::ConstrainedAlignAxis(), UE::Geometry::TFrame3< float >::ConstrainedAlignPerpAxes(), UE::Geometry::TFrame3< float >::RayPlaneIntersection(), UE::Geometry::TFrame3< float >::ToPlane(), and UE::Geometry::TFrame3< float >::ToPlaneUV().
PointAt() [1/2]
template<typename RealType> TVector< RealType > UE::Geometry::TFrame3< RealType >::PointAt (const TVector< RealType > & Point) const inline
Returns
point at distances along frame axes
Definition at line 206 of file FrameTypes.h.
PointAt() [2/2]
template<typename RealType> TVector< RealType > UE::Geometry::TFrame3< RealType >::PointAt (RealType X, RealType Y, RealType Z) const inline
Returns
point at distances along frame axes
Definition at line 200 of file FrameTypes.h.
RayPlaneIntersection()
template<typename RealType> bool UE::Geometry::TFrame3< RealType >::RayPlaneIntersection (const TVector< RealType > & RayOrigin, const TVector< RealType > & RayDirection, int PlaneNormalAxis, UE::Math::TVector< RealType > & HitPointOut) const inline
Compute intersection of ray with plane defined by frame origin and axis as normal.
Parameters
RayOrigin origin of ray
RayDirection direction of ray
PlaneNormalAxis which axis of frame to use as plane normal
HitPointOut intersection point, or invalid point if ray does not hit plane or is parallel to plane
Returns
true if ray intersects plane and HitPointOut is valid
Definition at line 445 of file FrameTypes.h.
Referenced by UE::Geometry::TSpatialPhotoSet< PixelType, RealType >::ComputeSampleLocation().
Rotate()
template<typename RealType> void UE::Geometry::TFrame3< RealType >::Rotate (const TQuaternion< RealType > & Quat) inline
Rotate this frame by given quaternion.
Definition at line 340 of file FrameTypes.h.
ToFPlane()
template<typename RealType> FPlane UE::Geometry::TFrame3< RealType >::ToFPlane () const inline
Returns
conversion of this Frame to FPlane
Definition at line 181 of file FrameTypes.h.
ToFrame() [1/3]
template<typename RealType> TFrame3< RealType > UE::Geometry::TFrame3< RealType >::ToFrame (const TFrame3< RealType > & Frame) const inline
Returns
input Frame transformed into local coordinate system of this Frame
Definition at line 260 of file FrameTypes.h.
ToFrame() [2/3]
template<typename RealType> TQuaternion< RealType > UE::Geometry::TFrame3< RealType >::ToFrame (const TQuaternion< RealType > & Quat) const inline
Returns
input Quaternion transformed into local coordinate system of Frame
Definition at line 236 of file FrameTypes.h.
ToFrame() [3/3]
template<typename RealType> TRay< RealType > UE::Geometry::TFrame3< RealType >::ToFrame (const TRay< RealType > & Ray) const inline
Returns
input Ray transformed into local coordinate system of Frame
Definition at line 248 of file FrameTypes.h.
ToFramePoint()
template<typename RealType> TVector< RealType > UE::Geometry::TFrame3< RealType >::ToFramePoint (const TVector< RealType > & Point) const inline
Returns
input Point transformed into local coordinate system of Frame
Definition at line 212 of file FrameTypes.h.
Referenced by FBaseKelvinletBrushOp::DisplaceKelvinlet(), FBaseKelvinletBrushOp::IntegrateKelvinlet(), UE::SculptFalloffs::MakeInverseBoxFalloff(), UE::SculptFalloffs::MakeLinearBoxFalloff(), UE::SculptFalloffs::MakeRoundBoxFalloff(), UE::SculptFalloffs::MakeSmoothBoxFalloff(), UE::Geometry::TFrame3< float >::ToFrame(), and UE::Geometry::TFrame3< float >::ToFrame().
ToFrameVector()
template<typename RealType> TVector< RealType > UE::Geometry::TFrame3< RealType >::ToFrameVector (const TVector< RealType > & Vector) const inline
Returns
input Vector transformed into local coordinate system of Frame
Definition at line 224 of file FrameTypes.h.
Referenced by FBiLaplacianPullKelvinletBrushOp::ApplyStamp(), FLaplacianPullKelvinletBrushOp::ApplyStamp(), FMoveBrushOp::ApplyStamp(), FPinchKelvinletBrushOp::ApplyStamp(), FPullKelvinletBrushOp::ApplyStamp(), FSharpPullKelvinletBrushOp::ApplyStamp(), and UE::Geometry::FGeneralizedCylinderGenerator::Generate().
ToFTransform()
template<typename RealType> FTransform UE::Geometry::TFrame3< RealType >::ToFTransform () const inline
Returns
conversion of this Frame to FTransform
Definition at line 168 of file FrameTypes.h.
ToInverseFTransform()
template<typename RealType> FTransform UE::Geometry::TFrame3< RealType >::ToInverseFTransform () const inline
Returns
conversion of this Frame to an inverse FTransform
Definition at line 174 of file FrameTypes.h.
ToInverseTransform()
template<typename RealType> TTransformSRT3< RealType > UE::Geometry::TFrame3< RealType >::ToInverseTransform () const inline
Returns
conversion of this Frame to an inverse TTransform
Definition at line 193 of file FrameTypes.h.
ToPlane()
template<typename RealType> TVector< RealType > UE::Geometry::TFrame3< RealType >::ToPlane (const TVector< RealType > & Pos, int PlaneNormalAxis = 2) const inline
Project a point onto one of the planes of the frame.
Parameters
Pos 3D position
PlaneNormalAxis which plane to project onto, identified by perpendicular normal. Default is 2, ie normal is Z, plane is (X,Y)
Returns
3D coordinate in the plane
Definition at line 326 of file FrameTypes.h.
ToPlaneUV()
template<typename RealType> TVector2< RealType > UE::Geometry::TFrame3< RealType >::ToPlaneUV (const TVector< RealType > & Pos, int PlaneNormalAxis = 2) const inline
Project 3D point into plane and convert to UV coordinates in that plane.
Parameters
Pos 3D position
PlaneNormalAxis which plane to project onto, identified by perpendicular normal. Default is 2, ie normal is Z, plane is (X,Y)
Returns
2D coordinates in UV plane, relative to origin
Definition at line 279 of file FrameTypes.h.
ToTransform()
template<typename RealType> TTransformSRT3< RealType > UE::Geometry::TFrame3< RealType >::ToTransform () const inline
Returns
conversion of this Frame to TTransform
Definition at line 187 of file FrameTypes.h.
Transform() [1/2]
template<typename RealType> void UE::Geometry::TFrame3< RealType >::Transform (const FTransform & XForm) inline
transform this frame by the given transform.
Note: Ignores scale, as TFrame3 does not support scaling
Definition at line 357 of file FrameTypes.h.
Transform() [2/2]
template<typename RealType> void UE::Geometry::TFrame3< RealType >::Transform (const TTransformSRT3< RealType > & XForm) inline
transform this frame by the given transform.
Note: Ignores scale, as TFrame3 does not support scaling
Definition at line 367 of file FrameTypes.h.
X()
template<typename RealType> TVector< RealType > UE::Geometry::TFrame3< RealType >::X () const inline
Returns
X axis of frame (axis 0)
Definition at line 150 of file FrameTypes.h.
Referenced by UE::Geometry::TSpatialPhotoSet< PixelType, RealType >::ComputeSampleLocation(), UE::Geometry::FGeneralizedCylinderGenerator::Generate(), and UE::Geometry::TMeshLocalParam< PointSetType >::PropagateUV().
Y()
template<typename RealType> TVector< RealType > UE::Geometry::TFrame3< RealType >::Y () const inline
Returns
Y axis of frame (axis 1)
Definition at line 156 of file FrameTypes.h.
Referenced by UE::Geometry::TSpatialPhotoSet< PixelType, RealType >::ComputeSampleLocation(), and UE::Geometry::FGeneralizedCylinderGenerator::Generate().
Z()
template<typename RealType> TVector< RealType > UE::Geometry::TFrame3< RealType >::Z () const inline
Returns
Z axis of frame (axis 2)
Definition at line 162 of file FrameTypes.h.
Referenced by FFlattenBrushOp::ApplyStamp(), FPinchBrushOp::ApplyStamp(), FViewAlignedSculptBrushOp::ApplyStamp(), FPinchBrushOp::BeginStroke(), UE::Geometry::TSpatialPhotoSet< PixelType, RealType >::ComputeSampleLocation(), UE::Geometry::TMeshLocalParam< PointSetType >::PropagateUV(), and UE::Geometry::TFrame3< float >::ToFPlane().
Field Documentation
Origin
template<typename RealType> TVector<RealType> UE::Geometry::TFrame3< RealType >::Origin
Origin of the frame.
Definition at line 31 of file FrameTypes.h.
Referenced by UE::Geometry::TFrame3< float >::TFrame3(), FBiLaplacianPullKelvinletBrushOp::ApplyStamp(), FFlattenBrushOp::ApplyStamp(), FInflateBrushOp::ApplyStamp(), FLaplacianPullKelvinletBrushOp::ApplyStamp(), FMoveBrushOp::ApplyStamp(), FPinchBrushOp::ApplyStamp(), FPinchKelvinletBrushOp::ApplyStamp(), FPlaneBrushOp::ApplyStamp(), FPullKelvinletBrushOp::ApplyStamp(), FSharpPullKelvinletBrushOp::ApplyStamp(), FSmoothBrushOp::ApplyStamp(), FSmoothFillBrushOp::ApplyStamp(), FGroupEraseBrushOp::ApplyStampByTriangles(), FGroupPaintBrushOp::ApplyStampByTriangles(), UE::Geometry::FVertexColorSmoothBrushOp::ApplyStampToVertexColors(), UE::Geometry::FVertexColorSoftenBrushOp::ApplyStampToVertexColors(), UE::Geometry::FVertexPaintBrushOp::ApplyStampToVertexColors(), FPinchBrushOp::BeginStroke(), UE::Geometry::TSpatialPhotoSet< PixelType, RealType >::ComputeSampleLocation(), UE::Geometry::GetFKElement(), UE::Geometry::GetShape(), UE::SculptFalloffs::MakeInverseFalloff(), UE::SculptFalloffs::MakeLinearFalloff(), UE::SculptFalloffs::MakeRoundFalloff(), UE::SculptFalloffs::MakeStandardSmoothFalloff(), and UE::Geometry::TMeshLocalParam< PointSetType >::UpdateUVExpmapUpwind().
Rotation
template<typename RealType> TQuaternion<RealType> UE::Geometry::TFrame3< RealType >::Rotation
Rotation of the frame.
Think of this as the rotation of the unit X/Y/Z axes to the 3D frame axes.
Definition at line 36 of file FrameTypes.h.
Referenced by UE::Geometry::TFrame3< float >::TFrame3(), UE::Geometry::GetFKElement(), and UE::Geometry::GetShape().
The documentation for this struct was generated from the following file:
Runtime/GeometryCore/Public/FrameTypes.h