Unreal Engine 5.6 C++ API: UE::Geometry::FOccupancyGrid3 Struct Reference
UE::Geometry::FOccupancyGrid3 Struct Reference
Sample mesh occupancy in a voxel grid by using the mesh's winding number, on voxel corners, to determine whether the voxel is fully contained within the interior of the mesh, touches the mesh's boundary, or is fully contained on the exterior of the mesh.
#include "OccupancyGrid3.h"
Public Types
enum class EDomain : int32 { Exterior , Boundary , Interior }
An enum representing a voxel's classification.
Public Member Functions
template<typename MeshType>
FOccupancyGrid3 (const MeshType &InMesh, const int32 InVoxelResolution)
FBox3f GetCellBoxFromIndex (const FVector3i &Index) const
Given an index into the occupancy grid, returns the bbox that represents the cell in the winding number grid, from which the occupancy got computed.
FVector3f GetCellCenterFromIndex (const FVector3i &Index) const
Given an index into the occupancy grid, returns the midpoint of the bbox that represents the matching cell in the winding number grid, from which the occupancy got computed.
FVector3i GetCellIndexFromPoint (const FVector &InPoint) const
Given a point in space, return a computed index into the occupancy grid.
float GetCellSize () const
const TDenseGrid3< EDomain > & GetOccupancyStateGrid () const
Returns a reference to the occupancy grid.
Private Attributes
FVector3f CellMidPoint
float CellSize
FVector3f GridOrigin
TDenseGrid3< EDomain > Occupancy
Detailed Description
Sample mesh occupancy in a voxel grid by using the mesh's winding number, on voxel corners, to determine whether the voxel is fully contained within the interior of the mesh, touches the mesh's boundary, or is fully contained on the exterior of the mesh.
Definition at line 19 of file OccupancyGrid3.h.
Member Enumeration Documentation
EDomain
enum class UE::Geometry::FOccupancyGrid3::EDomain : int32 strong
An enum representing a voxel's classification.
Enumerator
Exterior
Boundary
The point in the occupancy grid is completely on the exterior of the given mesh.
Interior
The point in the occupancy grid includes a mesh boundary.
The point in the occupancy grid is completely on the interior of the given mesh.
Definition at line 22 of file OccupancyGrid3.h.
Constructor & Destructor Documentation
FOccupancyGrid3()
template<typename MeshType> UE::Geometry::FOccupancyGrid3::FOccupancyGrid3 (const MeshType & InMesh, const int32 InVoxelResolution) inline
Definition at line 30 of file OccupancyGrid3.h.
References Boundary, CellMidPoint, CellSize, UE::Geometry::TMeshWindingNumberGrid< TriangleMeshType >::Compute(), UE::Count, UE::Geometry::TMeshWindingNumberGrid< TriangleMeshType >::Dimensions(), Exterior, float, UE::Geometry::TMeshAABBTree3< TriangleMeshType >::GetBoundingBox(), GridOrigin, UE::Geometry::TMeshWindingNumberGrid< TriangleMeshType >::GridOrigin, Interior, UE::Geometry::TAxisAlignedBox3< RealType >::MaxDim(), Occupancy, ParallelFor(), UE::Geometry::FVector3i::X, UE::Geometry::FVector3i::Y, and UE::Geometry::FVector3i::Z.
Member Function Documentation
GetCellBoxFromIndex()
FBox3f UE::Geometry::FOccupancyGrid3::GetCellBoxFromIndex (const FVector3i & Index) const inline
Given an index into the occupancy grid, returns the bbox that represents the cell in the winding number grid, from which the occupancy got computed.
Definition at line 123 of file OccupancyGrid3.h.
References CellMidPoint, and GetCellCenterFromIndex().
GetCellCenterFromIndex()
FVector3f UE::Geometry::FOccupancyGrid3::GetCellCenterFromIndex (const FVector3i & Index) const inline
Given an index into the occupancy grid, returns the midpoint of the bbox that represents the matching cell in the winding number grid, from which the occupancy got computed.
Definition at line 114 of file OccupancyGrid3.h.
References CellMidPoint, CellSize, float, and GridOrigin.
Referenced by GetCellBoxFromIndex().
GetCellIndexFromPoint()
FVector3i UE::Geometry::FOccupancyGrid3::GetCellIndexFromPoint (const FVector & InPoint) const inline
Given a point in space, return a computed index into the occupancy grid.
If the point is outside of the mesh's bounding box, the given index will be outside the range of the occupancy grid. To check for validity, test against the occupancy grid's extents as returned by GetOccupancy.
Definition at line 102 of file OccupancyGrid3.h.
References CellSize, FVector, GridOrigin, UE::Math::TVector< T >::X, UE::Math::TVector< T >::Y, and UE::Math::TVector< T >::Z.
GetCellSize()
float UE::Geometry::FOccupancyGrid3::GetCellSize () const inline
Definition at line 136 of file OccupancyGrid3.h.
References CellSize.
GetOccupancyStateGrid()
const TDenseGrid3< EDomain > & UE::Geometry::FOccupancyGrid3::GetOccupancyStateGrid () const inline
Returns a reference to the occupancy grid.
Definition at line 130 of file OccupancyGrid3.h.
References Occupancy.
Field Documentation
CellMidPoint
FVector3f UE::Geometry::FOccupancyGrid3::CellMidPoint private
Definition at line 154 of file OccupancyGrid3.h.
Referenced by FOccupancyGrid3(), GetCellBoxFromIndex(), and GetCellCenterFromIndex().
CellSize
float UE::Geometry::FOccupancyGrid3::CellSize private
Definition at line 146 of file OccupancyGrid3.h.
Referenced by FOccupancyGrid3(), GetCellCenterFromIndex(), GetCellIndexFromPoint(), and GetCellSize().
GridOrigin
FVector3f UE::Geometry::FOccupancyGrid3::GridOrigin private
Definition at line 151 of file OccupancyGrid3.h.
Referenced by FOccupancyGrid3(), GetCellCenterFromIndex(), and GetCellIndexFromPoint().
Occupancy
TDenseGrid3<EDomain> UE::Geometry::FOccupancyGrid3::Occupancy private
Definition at line 143 of file OccupancyGrid3.h.
Referenced by FOccupancyGrid3(), and GetOccupancyStateGrid().
The documentation for this struct was generated from the following file:
Runtime/GeometryCore/Public/Spatial/OccupancyGrid3.h