Unreal Engine 5.6 C++ API: UE::Anim::FMessageStack Struct Reference
UE::Anim::FMessageStack Struct Reference
#include "AnimNodeMessages.h"
Data Structures
struct FMessageEntry
struct FNodeInfo
Public Types
enum class EEnumerate { Stop , Continue }
Public Member Functions
FMessageStack ()=default
FMessageStack (FMessageStack &&InMessageStack)=default
FMessageStack (FMessageStack &)=delete
void CopyForCachedUpdate (const FMessageStack &InStack)
template<typename TGraphMessageType>
void ForEachMessage (TFunctionRef< EEnumerate(TGraphMessageType &)> InFunction) const
void ForEachTag (FName InTagId, TFunctionRef< EEnumerate(FNodeInfo)> InFunction) const
template<typename TGraphMessageType>
bool HasMessage () const
void MakeEventContextData (TArray< TUniquePtr< const IAnimNotifyEventContextDataInterface > > &ContextData) const
FMessageStack & operator= (const FMessageStack &)=delete
FMessageStack & operator= (FMessageStack &&)=default
template<typename TGraphMessageType>
void TopMessage (TFunctionRef< void(TGraphMessageType &)> InFunction) const
template<typename TGraphMessageType>
void TopMessageWeakPtr (TFunctionRef< void(TWeakPtr< TGraphMessageType > &)> InFunction)
Private Types
using FMessageMap = TMap<FName, FMessageStackEntry, TInlineSetAllocator<8>>
using FMessageStackEntry = TArray<FMessageEntry, TInlineAllocator<8>>
using FTagMap = TMap<FName, FTagStackEntry, TInlineSetAllocator<4>>
using FTagStackEntry = TArray<FNodeInfo, TInlineAllocator<4>>
Private Member Functions
void BottomMessage (FName InMessageType, TFunctionRef< void(IGraphMessage &)> InFunction) const
void ForEachMessage (FName InMessageType, TFunctionRef< EEnumerate(IGraphMessage &)> InFunction) const
bool HasMessage (FName InMessageType) const
void PopMessage (FName InMessageType)
void PopTag (FName InTag)
void PushMessage (FName InMessageType, FAnimNode_Base *InNode, const UScriptStruct *InStruct, TSharedRef< IGraphMessage > InMessage)
void PushTag (FAnimNode_Base *InNode, const UScriptStruct *InStruct, FName InTag)
void TopMessage (FName InMessageType, TFunctionRef< void(IGraphMessage &)> InFunction) const
void TopMessageSharedPtr (FName InMessageType, TFunctionRef< void(TSharedPtr< IGraphMessage > &)> InFunction)
Private Attributes
FMessageMap MessageStacks
FTagMap TagStacks
Friends
struct FScopedGraphMessage
struct FScopedGraphTag
Detailed Description
Definition at line 213 of file AnimNodeMessages.h.
Member Typedef Documentation
FMessageMap
using UE::Anim::FMessageStack::FMessageMap = TMap<FName, FMessageStackEntry, TInlineSetAllocator<8>> private
Definition at line 353 of file AnimNodeMessages.h.
FMessageStackEntry
using UE::Anim::FMessageStack::FMessageStackEntry = TArray<FMessageEntry, TInlineAllocator<8>> private
Definition at line 352 of file AnimNodeMessages.h.
FTagMap
using UE::Anim::FMessageStack::FTagMap = TMap<FName, FTagStackEntry, TInlineSetAllocator<4>> private
Definition at line 359 of file AnimNodeMessages.h.
FTagStackEntry
using UE::Anim::FMessageStack::FTagStackEntry = TArray<FNodeInfo, TInlineAllocator<4>> private
Definition at line 358 of file AnimNodeMessages.h.
Member Enumeration Documentation
EEnumerate
enum class UE::Anim::FMessageStack::EEnumerate strong
Enumerator
Stop
Continue
Definition at line 229 of file AnimNodeMessages.h.
Constructor & Destructor Documentation
FMessageStack() [1/3]
UE::Anim::FMessageStack::FMessageStack () default
Referenced by FMessageStack(), FMessageStack(), CopyForCachedUpdate(), operator=(), and operator=().
FMessageStack() [2/3]
UE::Anim::FMessageStack::FMessageStack (FMessageStack &) delete
References FMessageStack().
FMessageStack() [3/3]
UE::Anim::FMessageStack::FMessageStack (FMessageStack && InMessageStack) default
References FMessageStack().
Member Function Documentation
BottomMessage()
void UE::Anim::FMessageStack::BottomMessage (FName InMessageType, TFunctionRef< void(IGraphMessage &)> InFunction) const private
CopyForCachedUpdate()
void UE::Anim::FMessageStack::CopyForCachedUpdate (const FMessageStack & InStack)
References FMessageStack().
ForEachMessage() [1/2]
void UE::Anim::FMessageStack::ForEachMessage (FName InMessageType, TFunctionRef< EEnumerate(IGraphMessage &)> InFunction) const private
ForEachMessage() [2/2]
template<typename TGraphMessageType> void UE::Anim::FMessageStack::ForEachMessage (TFunctionRef< EEnumerate(TGraphMessageType &)> InFunction) const inline
Definition at line 245 of file AnimNodeMessages.h.
References ForEachMessage(), and TIsDerivedFrom< DerivedType, BaseType >::IsDerived.
Referenced by ForEachMessage().
ForEachTag()
void UE::Anim::FMessageStack::ForEachTag (FName InTagId, TFunctionRef< EEnumerate(FNodeInfo)> InFunction) const
HasMessage() [1/2]
template<typename TGraphMessageType> bool UE::Anim::FMessageStack::HasMessage () const inline
Definition at line 288 of file AnimNodeMessages.h.
References HasMessage(), and TIsDerivedFrom< DerivedType, BaseType >::IsDerived.
Referenced by HasMessage().
HasMessage() [2/2]
bool UE::Anim::FMessageStack::HasMessage (FName InMessageType) const private
MakeEventContextData()
void UE::Anim::FMessageStack::MakeEventContextData (TArray< TUniquePtr< const IAnimNotifyEventContextDataInterface > > & ContextData) const
operator=() [1/2]
FMessageStack & UE::Anim::FMessageStack::operator= (const FMessageStack &) delete
References FMessageStack().
operator=() [2/2]
FMessageStack & UE::Anim::FMessageStack::operator= (FMessageStack &&) default
References FMessageStack().
PopMessage()
void UE::Anim::FMessageStack::PopMessage (FName InMessageType) private
PopTag()
void UE::Anim::FMessageStack::PopTag (FName InTag) private
PushMessage()
void UE::Anim::FMessageStack::PushMessage (FName InMessageType, FAnimNode_Base * InNode, const UScriptStruct * InStruct, TSharedRef< IGraphMessage > InMessage) private
PushTag()
void UE::Anim::FMessageStack::PushTag (FAnimNode_Base * InNode, const UScriptStruct * InStruct, FName InTag) private
TopMessage() [1/2]
void UE::Anim::FMessageStack::TopMessage (FName InMessageType, TFunctionRef< void(IGraphMessage &)> InFunction) const private
TopMessage() [2/2]
template<typename TGraphMessageType> void UE::Anim::FMessageStack::TopMessage (TFunctionRef< void(TGraphMessageType &)> InFunction) const inline
Definition at line 259 of file AnimNodeMessages.h.
References TIsDerivedFrom< DerivedType, BaseType >::IsDerived, and TopMessage().
Referenced by TopMessage().
TopMessageSharedPtr()
void UE::Anim::FMessageStack::TopMessageSharedPtr (FName InMessageType, TFunctionRef< void(TSharedPtr< IGraphMessage > &)> InFunction) private
Referenced by TopMessageWeakPtr().
TopMessageWeakPtr()
template<typename TGraphMessageType> void UE::Anim::FMessageStack::TopMessageWeakPtr (TFunctionRef< void(TWeakPtr< TGraphMessageType > &)> InFunction) inline
Definition at line 273 of file AnimNodeMessages.h.
References TIsDerivedFrom< DerivedType, BaseType >::IsDerived, StaticCastSharedPtr(), and TopMessageSharedPtr().
Friends And Related Symbol Documentation
FScopedGraphMessage
friend struct FScopedGraphMessage friend
Definition at line 217 of file AnimNodeMessages.h.
References FScopedGraphMessage.
Referenced by FScopedGraphMessage.
FScopedGraphTag
friend struct FScopedGraphTag friend
Definition at line 216 of file AnimNodeMessages.h.
References FScopedGraphTag.
Referenced by FScopedGraphTag.
Field Documentation
MessageStacks
FMessageMap UE::Anim::FMessageStack::MessageStacks private
Definition at line 356 of file AnimNodeMessages.h.
TagStacks
FTagMap UE::Anim::FMessageStack::TagStacks private
Definition at line 362 of file AnimNodeMessages.h.
The documentation for this struct was generated from the following file:
Runtime/Engine/Public/Animation/AnimNodeMessages.h