Unreal Engine 5.6 C++ API: UE::Serialization::FEditorBulkData::FSharedBufferWithID Struct Reference
UE::Serialization::FEditorBulkData::FSharedBufferWithID Struct Reference
Utility struct used to compute the Payload ID before calling UpdatePayload.
#include "EditorBulkData.h"
Public Member Functions
FSharedBufferWithID ()=default
FSharedBufferWithID (const FSharedBufferWithID &)=delete
FSharedBufferWithID (FSharedBuffer InPayload)
FSharedBufferWithID (FSharedBufferWithID &&)=default
FSharedBuffer GetPayload ()
FSharedBufferWithID & operator= (const FSharedBufferWithID &)=delete
FSharedBufferWithID & operator= (FSharedBufferWithID &&)=default
Private Attributes
friend FEditorBulkData
FSharedBuffer Payload
FIoHash PayloadId
Detailed Description
Utility struct used to compute the Payload ID before calling UpdatePayload.
Definition at line 251 of file EditorBulkData.h.
Constructor & Destructor Documentation
FSharedBufferWithID() [1/4]
UE::Serialization::FEditorBulkData::FSharedBufferWithID::FSharedBufferWithID (FSharedBuffer InPayload)
Referenced by FSharedBufferWithID(), FSharedBufferWithID(), operator=(), and operator=().
FSharedBufferWithID() [2/4]
UE::Serialization::FEditorBulkData::FSharedBufferWithID::FSharedBufferWithID () default
FSharedBufferWithID() [3/4]
UE::Serialization::FEditorBulkData::FSharedBufferWithID::FSharedBufferWithID (FSharedBufferWithID &&) default
References FSharedBufferWithID().
FSharedBufferWithID() [4/4]
UE::Serialization::FEditorBulkData::FSharedBufferWithID::FSharedBufferWithID (const FSharedBufferWithID &) delete
References FSharedBufferWithID().
Member Function Documentation
GetPayload()
FSharedBuffer UE::Serialization::FEditorBulkData::FSharedBufferWithID::GetPayload () inline
Definition at line 262 of file EditorBulkData.h.
References Payload.
operator=() [1/2]
FSharedBufferWithID & UE::Serialization::FEditorBulkData::FSharedBufferWithID::operator= (const FSharedBufferWithID &) delete
References FSharedBufferWithID().
operator=() [2/2]
FSharedBufferWithID & UE::Serialization::FEditorBulkData::FSharedBufferWithID::operator= (FSharedBufferWithID &&) default
References FSharedBufferWithID().
Field Documentation
FEditorBulkData
friend UE::Serialization::FEditorBulkData::FSharedBufferWithID::FEditorBulkData private
Definition at line 265 of file EditorBulkData.h.
Payload
FSharedBuffer UE::Serialization::FEditorBulkData::FSharedBufferWithID::Payload private
Definition at line 267 of file EditorBulkData.h.
Referenced by GetPayload().
PayloadId
FIoHash UE::Serialization::FEditorBulkData::FSharedBufferWithID::PayloadId private
Definition at line 268 of file EditorBulkData.h.
The documentation for this struct was generated from the following file:
Runtime/CoreUObject/Public/Serialization/EditorBulkData.h