Unreal Engine 5.6 C++ API: FLandscapeComponentGrassData Struct Reference
FLandscapeComponentGrassData Struct Reference
#include "LandscapeComponent.h"
Public Member Functions
PRAGMA_DISABLE_DEPRECATION_WARNINGS FLandscapeComponentGrassData ()=default
FLandscapeComponentGrassData (const FLandscapeComponentGrassData &)=default
FLandscapeComponentGrassData (FLandscapeComponentGrassData &&)=default
FLandscapeComponentGrassData (ULandscapeComponent *Component)
~FLandscapeComponentGrassData ()=default
void ConditionalDiscardDataOnLoad ()
bool Contains (ULandscapeGrassType *GrassType) const
SIZE_T GetAllocatedSize () const
TArrayView< uint16 > GetHeightData ()
TArrayView< uint8 > GetWeightData (const ULandscapeGrassType *GrassType)
bool HasData () const
PRAGMA_ENABLE_DEPRECATION_WARNINGS bool HasValidData () const
bool HasWeightData () const
void InitializeFrom (const TArray< uint16 > &HeightData, const TMap< ULandscapeGrassType *, TArray< uint8 > > &WeightData)
void InitializeFrom (IBuffer2DView< uint16 > *HeightData, TMap< ULandscapeGrassType *, IBuffer2DView< uint8 > * > &WeightData, bool bStripEmptyWeights)
FLandscapeComponentGrassData & operator= (const FLandscapeComponentGrassData &)=default
FLandscapeComponentGrassData & operator= (FLandscapeComponentGrassData &&)=default
Data Fields
TArray< uint8 > HeightWeightData
int32 NumElements = UnknownNumElements
TMap< TObjectPtr< ULandscapeGrassType >, int32 > WeightOffsets
Static Public Attributes
static constexpr int32 UnknownNumElements = -1
Friends
FArchive & operator<< (FArchive &Ar, FLandscapeComponentGrassData &Data)
Detailed Description
Definition at line 207 of file LandscapeComponent.h.
Constructor & Destructor Documentation
FLandscapeComponentGrassData() [1/4]
PRAGMA_DISABLE_DEPRECATION_WARNINGS FLandscapeComponentGrassData::FLandscapeComponentGrassData () default
Referenced by FLandscapeComponentGrassData(), FLandscapeComponentGrassData(), operator<<, operator=(), and operator=().
FLandscapeComponentGrassData() [2/4]
FLandscapeComponentGrassData::FLandscapeComponentGrassData (ULandscapeComponent * Component)
References Component.
~FLandscapeComponentGrassData()
FLandscapeComponentGrassData::~FLandscapeComponentGrassData () default
FLandscapeComponentGrassData() [3/4]
FLandscapeComponentGrassData::FLandscapeComponentGrassData (const FLandscapeComponentGrassData &) default
References FLandscapeComponentGrassData().
FLandscapeComponentGrassData() [4/4]
FLandscapeComponentGrassData::FLandscapeComponentGrassData (FLandscapeComponentGrassData &&) default
References FLandscapeComponentGrassData().
Member Function Documentation
ConditionalDiscardDataOnLoad()
void FLandscapeComponentGrassData::ConditionalDiscardDataOnLoad ()
Contains()
bool FLandscapeComponentGrassData::Contains (ULandscapeGrassType * GrassType) const
GetAllocatedSize()
SIZE_T FLandscapeComponentGrassData::GetAllocatedSize () const
GetHeightData()
TArrayView< uint16 > FLandscapeComponentGrassData::GetHeightData ()
GetWeightData()
TArrayView< uint8 > FLandscapeComponentGrassData::GetWeightData (const ULandscapeGrassType * GrassType)
HasData()
bool FLandscapeComponentGrassData::HasData () const
HasValidData()
PRAGMA_ENABLE_DEPRECATION_WARNINGS bool FLandscapeComponentGrassData::HasValidData () const
HasWeightData()
bool FLandscapeComponentGrassData::HasWeightData () const
InitializeFrom() [1/2]
void FLandscapeComponentGrassData::InitializeFrom (const TArray< uint16 > & HeightData, const TMap< ULandscapeGrassType *, TArray< uint8 > > & WeightData)
InitializeFrom() [2/2]
void FLandscapeComponentGrassData::InitializeFrom (IBuffer2DView< uint16 > * HeightData, TMap< ULandscapeGrassType *, IBuffer2DView< uint8 > * > & WeightData, bool bStripEmptyWeights)
operator=() [1/2]
FLandscapeComponentGrassData & FLandscapeComponentGrassData::operator= (const FLandscapeComponentGrassData &) default
References FLandscapeComponentGrassData().
operator=() [2/2]
FLandscapeComponentGrassData & FLandscapeComponentGrassData::operator= (FLandscapeComponentGrassData &&) default
References FLandscapeComponentGrassData(), and PRAGMA_ENABLE_DEPRECATION_WARNINGS.
Friends And Related Symbol Documentation
operator<<
FArchive & operator<< (FArchive & Ar, FLandscapeComponentGrassData & Data) friend
References FLandscapeComponentGrassData(), and Ar.
Field Documentation
HeightWeightData
TArray<uint8> FLandscapeComponentGrassData::HeightWeightData
Definition at line 236 of file LandscapeComponent.h.
NumElements
int32 FLandscapeComponentGrassData::NumElements = UnknownNumElements
Definition at line 233 of file LandscapeComponent.h.
UnknownNumElements
int32 FLandscapeComponentGrassData::UnknownNumElements = -1 static constexpr
Definition at line 230 of file LandscapeComponent.h.
WeightOffsets
TMap<TObjectPtr<ULandscapeGrassType>, int32> FLandscapeComponentGrassData::WeightOffsets
Definition at line 235 of file LandscapeComponent.h.
The documentation for this struct was generated from the following file:
Runtime/Landscape/Classes/LandscapeComponent.h