Unreal Engine 5.6 C++ API: FReferenceToken Struct Reference
FReferenceToken Struct Reference
The reference token represents different types that might appear in reference relationships.
#include "ReferenceToken.h"
Public Member Functions
FReferenceToken ()
FReferenceToken (const FGCObject *GCObject)
FReferenceToken (const FGCObjectInfo *GCObjectInfo)
FReferenceToken (const FGCVerseCellInfo *GCVerseCellInfo)
FReferenceToken (const UObject *Object)
FReferenceToken (const Verse::VCell *Cell)
FReferenceToken (EReferenceTokenType TokenType)
FGCObject * AsGCObject () const
FGCObjectInfo * AsGCObjectInfo () const
FGCVerseCellInfo * AsGCVerseCellInfo () const
UObject * AsObject () const
Verse::VCell * AsVerseCell () const
FString GetDescription () const
Returns a formatted string with reference's info.
FString GetDescription (FName PropertyName, const TCHAR *DefaultPropertyName) const
FString GetMemberName (UE::GC::FMemberId &MemberId) const
Convert the member id to a member name.
EReferenceTokenType GetType () const
bool IsGCObject () const
bool IsGCObjectInfo () const
bool IsGCVerseCellInfo () const
bool IsObject () const
bool IsVerseCell () const
bool operator== (const FReferenceToken &Other) const
Private Attributes
uint64 EncodedBits { 0 }
Static Private Attributes
static constexpr uint64 EncodingBits = 0b111
Friends
uint32 GetTypeHash (const FReferenceToken &Info)
Detailed Description
The reference token represents different types that might appear in reference relationships.
Definition at line 43 of file ReferenceToken.h.
Constructor & Destructor Documentation
FReferenceToken() [1/7]
FReferenceToken::FReferenceToken () inline
Definition at line 45 of file ReferenceToken.h.
References EncodedBits.
Referenced by GetTypeHash, and operator==().
FReferenceToken() [2/7]
FReferenceToken::FReferenceToken (const UObject * Object) inline explicit
Definition at line 50 of file ReferenceToken.h.
References BitCast(), EncodedBits, and Object.
FReferenceToken() [3/7]
FReferenceToken::FReferenceToken (const FGCObject * GCObject) inline explicit
Definition at line 55 of file ReferenceToken.h.
References BitCast(), EncodedBits, and GCObject.
FReferenceToken() [4/7]
FReferenceToken::FReferenceToken (const Verse::VCell * Cell) inline explicit
Definition at line 60 of file ReferenceToken.h.
References BitCast(), Cell, EncodedBits, and VerseCell.
FReferenceToken() [5/7]
FReferenceToken::FReferenceToken (const FGCObjectInfo * GCObjectInfo) inline explicit
Definition at line 65 of file ReferenceToken.h.
References BitCast(), EncodedBits, and GCObjectInfo.
FReferenceToken() [6/7]
FReferenceToken::FReferenceToken (const FGCVerseCellInfo * GCVerseCellInfo) inline explicit
Definition at line 70 of file ReferenceToken.h.
References BitCast(), EncodedBits, and GCVerseCellInfo.
FReferenceToken() [7/7]
FReferenceToken::FReferenceToken (EReferenceTokenType TokenType) inline explicit
Definition at line 75 of file ReferenceToken.h.
References checkf, EncodedBits, EncodingBits, and TEXT.
Member Function Documentation
AsGCObject()
FGCObject * FReferenceToken::AsGCObject () const inline
Definition at line 104 of file ReferenceToken.h.
References BitCast(), checkSlow, EncodedBits, EncodingBits, and IsGCObject().
AsGCObjectInfo()
FGCObjectInfo * FReferenceToken::AsGCObjectInfo () const inline
Definition at line 115 of file ReferenceToken.h.
References BitCast(), checkSlow, EncodedBits, EncodingBits, and IsGCObjectInfo().
AsGCVerseCellInfo()
FGCVerseCellInfo * FReferenceToken::AsGCVerseCellInfo () const inline
Definition at line 137 of file ReferenceToken.h.
References BitCast(), checkSlow, EncodedBits, EncodingBits, and IsGCVerseCellInfo().
AsObject()
UObject * FReferenceToken::AsObject () const inline
Definition at line 93 of file ReferenceToken.h.
References BitCast(), checkSlow, EncodedBits, EncodingBits, and IsObject().
AsVerseCell()
Verse::VCell * FReferenceToken::AsVerseCell () const inline
Definition at line 126 of file ReferenceToken.h.
References BitCast(), checkSlow, EncodedBits, EncodingBits, and IsVerseCell().
GetDescription() [1/2]
FString FReferenceToken::GetDescription () const
Returns a formatted string with reference's info.
GetDescription() [2/2]
FString FReferenceToken::GetDescription (FName PropertyName, const TCHAR * DefaultPropertyName) const
References PropertyName.
GetMemberName()
FString FReferenceToken::GetMemberName (UE::GC::FMemberId & MemberId) const
Convert the member id to a member name.
GetType()
EReferenceTokenType FReferenceToken::GetType () const inline
Definition at line 81 of file ReferenceToken.h.
References EncodedBits, EncodingBits, and None.
Referenced by IsGCObject(), IsGCObjectInfo(), IsGCVerseCellInfo(), IsObject(), and IsVerseCell().
IsGCObject()
bool FReferenceToken::IsGCObject () const inline
Definition at line 99 of file ReferenceToken.h.
References GCObject, and GetType().
Referenced by AsGCObject().
IsGCObjectInfo()
bool FReferenceToken::IsGCObjectInfo () const inline
Definition at line 110 of file ReferenceToken.h.
References GCObjectInfo, and GetType().
Referenced by AsGCObjectInfo().
IsGCVerseCellInfo()
bool FReferenceToken::IsGCVerseCellInfo () const inline
Definition at line 132 of file ReferenceToken.h.
References GCVerseCellInfo, and GetType().
Referenced by AsGCVerseCellInfo().
IsObject()
bool FReferenceToken::IsObject () const inline
Definition at line 88 of file ReferenceToken.h.
References GetType(), and Object.
Referenced by AsObject().
IsVerseCell()
bool FReferenceToken::IsVerseCell () const inline
Definition at line 121 of file ReferenceToken.h.
References GetType(), and VerseCell.
Referenced by AsVerseCell().
operator==()
bool FReferenceToken::operator== (const FReferenceToken & Other) const inline
Definition at line 150 of file ReferenceToken.h.
References FReferenceToken(), EncodedBits, and Other.
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FReferenceToken & Info) friend
Definition at line 155 of file ReferenceToken.h.
References FReferenceToken(), GetTypeHash, and Info.
Referenced by GetTypeHash.
Field Documentation
EncodedBits
uint64 FReferenceToken::EncodedBits { 0 } private
Definition at line 162 of file ReferenceToken.h.
Referenced by FReferenceToken(), FReferenceToken(), FReferenceToken(), FReferenceToken(), FReferenceToken(), FReferenceToken(), FReferenceToken(), AsGCObject(), AsGCObjectInfo(), AsGCVerseCellInfo(), AsObject(), AsVerseCell(), GetType(), and operator==().
EncodingBits
uint64 FReferenceToken::EncodingBits = 0b111 static constexpr private
Definition at line 161 of file ReferenceToken.h.
Referenced by FReferenceToken(), AsGCObject(), AsGCObjectInfo(), AsGCVerseCellInfo(), AsObject(), AsVerseCell(), and GetType().
The documentation for this struct was generated from the following file:
Runtime/CoreUObject/Public/UObject/ReferenceToken.h