Unreal Engine 5.6 C++ API: IStereoLayers::FLayerDesc Struct Reference
IStereoLayers::FLayerDesc Struct Reference
Structure describing the visual appearance of a single stereo layer.
#include "IStereoLayers.h"
Public Member Functions
FLayerDesc ()
PRAGMA_DISABLE_DEPRECATION_WARNINGS FLayerDesc (const FLayerDesc &)=default
FLayerDesc (const IStereoLayerShape &InShape)
FLayerDesc (FLayerDesc &&)=default
template<typename T>
T & GetShape ()
template<typename T>
const T & GetShape () const
template<typename T>
bool HasShape () const
PRAGMA_DISABLE_DEPRECATION_WARNINGS bool HasValidTexture () const
PRAGMA_ENABLE_DEPRECATION_WARNINGS bool IsVisible () const
FLayerDesc & operator= (const FLayerDesc &)=default
FLayerDesc & operator= (FLayerDesc &&)=default
template<typename T, typename... InArgTypes>
void SetShape (InArgTypes &&... Args)
UE_DEPRECATED (5.6, "Reference the Id field directly") uint32 GetLayerId() const
PRAGMA_ENABLE_DEPRECATION_WARNINGS UE_DEPRECATED (5.6, "Reference the Id field directly") void SetLayerId(uint32 InId)
UE_DEPRECATED (5.6, "Use LeftTextureObj instead") FTextureRHIRef LeftTexture
UE_DEPRECATED (5.6, "Use TextureObj instead") FTextureRHIRef Texture
Data Fields
uint32 Flags = 0
uint32 Id = INVALID_LAYER_ID
FIntPoint LayerSize = FIntPoint(0, 0)
TWeakObjectPtr< class UTexture > LeftTextureObj = nullptr
ELayerType PositionType = ELayerType::FaceLocked
int32 Priority = 0
FVector2D QuadSize = FVector2D(1.0f, 1.0f)
TWeakObjectPtr< class UTexture > TextureObj = nullptr
FTransform Transform = FTransform::Identity
FBox2D UVRect = FBox2D(FVector2D(0.0f, 0.0f), FVector2D(1.0f, 1.0f))
Static Public Attributes
static const uint32 INVALID_LAYER_ID = 0
Private Attributes
FShapeWrapper Shape
Detailed Description
Structure describing the visual appearance of a single stereo layer.
Definition at line 91 of file IStereoLayers.h.
Constructor & Destructor Documentation
FLayerDesc() [1/4]
IStereoLayers::FLayerDesc::FLayerDesc () inline
Definition at line 94 of file IStereoLayers.h.
References Shape.
Referenced by FLayerDesc(), FLayerDesc(), operator=(), and operator=().
FLayerDesc() [2/4]
IStereoLayers::FLayerDesc::FLayerDesc (const IStereoLayerShape & InShape) inline
Definition at line 99 of file IStereoLayers.h.
References Shape.
FLayerDesc() [3/4]
PRAGMA_DISABLE_DEPRECATION_WARNINGS IStereoLayers::FLayerDesc::FLayerDesc (const FLayerDesc &) default
References FLayerDesc().
FLayerDesc() [4/4]
IStereoLayers::FLayerDesc::FLayerDesc (FLayerDesc &&) default
References FLayerDesc().
Member Function Documentation
GetShape() [1/2]
template<typename T> T & IStereoLayers::FLayerDesc::GetShape () inline
Definition at line 142 of file IStereoLayers.h.
References check, HasShape(), and Shape.
GetShape() [2/2]
template<typename T> const T & IStereoLayers::FLayerDesc::GetShape () const inline
Definition at line 143 of file IStereoLayers.h.
References check, HasShape(), and Shape.
HasShape()
template<typename T> bool IStereoLayers::FLayerDesc::HasShape () const inline
Definition at line 140 of file IStereoLayers.h.
References check, and Shape.
Referenced by GetShape(), and GetShape().
HasValidTexture()
PRAGMA_DISABLE_DEPRECATION_WARNINGS bool IStereoLayers::FLayerDesc::HasValidTexture () const inline
Definition at line 117 of file IStereoLayers.h.
References IStereoLayers::Texture, and TextureObj.
Referenced by IsVisible().
IsVisible()
PRAGMA_ENABLE_DEPRECATION_WARNINGS bool IStereoLayers::FLayerDesc::IsVisible () const inline
Definition at line 119 of file IStereoLayers.h.
References Flags, HasValidTexture(), and IStereoLayers::LAYER_FLAG_HIDDEN.
operator=() [1/2]
FLayerDesc & IStereoLayers::FLayerDesc::operator= (const FLayerDesc &) default
References FLayerDesc().
operator=() [2/2]
FLayerDesc & IStereoLayers::FLayerDesc::operator= (FLayerDesc &&) default
References FLayerDesc(), and PRAGMA_ENABLE_DEPRECATION_WARNINGS.
SetShape()
template<typename T, typename... InArgTypes> void IStereoLayers::FLayerDesc::SetShape (InArgTypes &&... Args) inline
Definition at line 144 of file IStereoLayers.h.
References Forward(), and Shape.
UE_DEPRECATED() [1/4]
IStereoLayers::FLayerDesc::UE_DEPRECATED (5. 6, "Reference the Id field directly") const inline
Definition at line 114 of file IStereoLayers.h.
References Id.
UE_DEPRECATED() [2/4]
PRAGMA_ENABLE_DEPRECATION_WARNINGS IStereoLayers::FLayerDesc::UE_DEPRECATED (5. 6, "Reference the Id field directly") inline
Definition at line 112 of file IStereoLayers.h.
References Id.
Referenced by UE_DEPRECATED().
UE_DEPRECATED() [3/4]
IStereoLayers::FLayerDesc::UE_DEPRECATED (5. 6, "Use LeftTextureObj instead")
References IStereoLayers::LeftTexture, and UE_DEPRECATED().
UE_DEPRECATED() [4/4]
IStereoLayers::FLayerDesc::UE_DEPRECATED (5. 6, "Use TextureObj instead")
References IStereoLayers::Texture.
Field Documentation
Flags
uint32 IStereoLayers::FLayerDesc::Flags = 0
Definition at line 158 of file IStereoLayers.h.
Referenced by IsVisible(), and IStereoLayers::UE_DEPRECATED().
Id
uint32 IStereoLayers::FLayerDesc::Id = INVALID_LAYER_ID
Definition at line 124 of file IStereoLayers.h.
Referenced by UE_DEPRECATED(), and UE_DEPRECATED().
INVALID_LAYER_ID
const uint32 IStereoLayers::FLayerDesc::INVALID_LAYER_ID = 0 static
Definition at line 122 of file IStereoLayers.h.
LayerSize
FIntPoint IStereoLayers::FLayerDesc::LayerSize = FIntPoint(0, 0)
Definition at line 133 of file IStereoLayers.h.
LeftTextureObj
TWeakObjectPtr<class UTexture> IStereoLayers::FLayerDesc::LeftTextureObj = nullptr
Definition at line 154 of file IStereoLayers.h.
PositionType
ELayerType IStereoLayers::FLayerDesc::PositionType = ELayerType::FaceLocked
Definition at line 137 of file IStereoLayers.h.
Referenced by IStereoLayers::UE_DEPRECATED().
Priority
int32 IStereoLayers::FLayerDesc::Priority = 0
Definition at line 135 of file IStereoLayers.h.
QuadSize
FVector2D IStereoLayers::FLayerDesc::QuadSize = FVector2D(1.0f, 1.0f)
Definition at line 128 of file IStereoLayers.h.
Referenced by IStereoLayers::UE_DEPRECATED().
Shape
FShapeWrapper IStereoLayers::FLayerDesc::Shape private
Definition at line 160 of file IStereoLayers.h.
Referenced by FLayerDesc(), FLayerDesc(), GetShape(), GetShape(), HasShape(), and SetShape().
TextureObj
TWeakObjectPtr<class UTexture> IStereoLayers::FLayerDesc::TextureObj = nullptr
Definition at line 149 of file IStereoLayers.h.
Referenced by HasValidTexture().
Transform
FTransform IStereoLayers::FLayerDesc::Transform = FTransform::Identity
Definition at line 126 of file IStereoLayers.h.
Referenced by IStereoLayers::UE_DEPRECATED().
UVRect
FBox2D IStereoLayers::FLayerDesc::UVRect = FBox2D(FVector2D(0.0f, 0.0f), FVector2D(1.0f, 1.0f))
Definition at line 130 of file IStereoLayers.h.
The documentation for this struct was generated from the following file:
Runtime/Engine/Public/IStereoLayers.h