Unreal Engine 5.6 C++ API: UE::Sequencer::FCastableTypeTable Struct Reference
UE::Sequencer::FCastableTypeTable Struct Reference
#include "CastableTypeTable.h"
Data Structures
struct FCastableTypeTableGenerator
Utility class that generates a type table used for dynamic casting and instance of an ICastable object.
Public Member Functions
FCastableTypeTable (const FCastableTypeTable &)=delete
FCastableTypeTable (FCastableTypeTable &&)=delete
FCastableTypeTable (uint8 *InTypeMaskStorage)
const void * Cast (const ICastable *BasePtr, uint32 ToType) const
Use this type table to cast the specified base ptr to another type.
const void * Cast (const IDynamicExtension *BasePtr, uint32 ToType) const
Use this type table to cast the specified base ptr to another type.
uint32 GetTypeID () const
Retrieve the type ID for this type table.
FName GetTypeName () const
Retrieve the C++ type name that this type table relates to.
void operator= (const FCastableTypeTable &)=delete
void operator= (FCastableTypeTable &&)=delete
Static Public Member Functions
static SEQUENCERCORE_API const FCastableTypeTable * FindTypeByName (FName InName)
Attempt to locate a type table by its C++ name.
template<typename T>
static FCastableTypeTable * MakeTypeTable (const ICastable *Unused, uint32 TypeID, FName InName)
template<typename T>
static FCastableTypeTable * MakeTypeTable (const IDynamicExtension *Unused, uint32 TypeID, FName InName)
template<typename T>
static FCastableTypeTable * MakeTypeTable (const void *Unused, uint32 TypeID, FName InName)
Make a new type table for the templated type, ID and typename.
Private Member Functions
const void * CastImpl (const void *BasePtr, uint32 ToType) const
Cast implementation function.
Private Attributes
uint32 NumStaticTypes
The number of static types implemented within this type table.
int16 * StaticTypeOffsets
Ptr to the static type offsets allocated at the end of this struct.
uint32 ThisTypeID
Unique static type ID for this type.
FName ThisTypeName
The name of the C++ type that this table relates to.
MovieScene::TFixedSparseBitSet< uint32, MovieScene::TFixedSparseBitSetBucketStorage< uint8 > > TypeMask
Fixed sparse bitset of types that this table contains.
Detailed Description
Definition at line 25 of file CastableTypeTable.h.
Constructor & Destructor Documentation
FCastableTypeTable() [1/3]
UE::Sequencer::FCastableTypeTable::FCastableTypeTable (uint8 * InTypeMaskStorage) explicit
Referenced by FCastableTypeTable(), FCastableTypeTable(), UE::Sequencer::FCastableTypeTable::FCastableTypeTableGenerator::ByteSize(), UE::Sequencer::FCastableTypeTable::FCastableTypeTableGenerator::Commit(), FindTypeByName(), MakeTypeTable(), MakeTypeTable(), MakeTypeTable(), operator=(), and operator=().
FCastableTypeTable() [2/3]
UE::Sequencer::FCastableTypeTable::FCastableTypeTable (const FCastableTypeTable &) delete
References FCastableTypeTable().
FCastableTypeTable() [3/3]
UE::Sequencer::FCastableTypeTable::FCastableTypeTable (FCastableTypeTable &&) delete
References FCastableTypeTable().
Member Function Documentation
Cast() [1/2]
const void * UE::Sequencer::FCastableTypeTable::Cast (const ICastable * BasePtr, uint32 ToType) const inline
Use this type table to cast the specified base ptr to another type.
Note
BasePtr must be an instance of the type specified by this type table, or the result is undefined.
Returns
BasePtr casted to the type ID specified by ToType, or nullptr if the cast failed
Definition at line 70 of file CastableTypeTable.h.
References CastImpl().
Cast() [2/2]
const void * UE::Sequencer::FCastableTypeTable::Cast (const IDynamicExtension * BasePtr, uint32 ToType) const inline
Use this type table to cast the specified base ptr to another type.
Note
BasePtr must be an instance of the type specified by this type table, or the result is undefined.
Returns
BasePtr casted to the type ID specified by ToType, or nullptr if the cast failed
Definition at line 82 of file CastableTypeTable.h.
References CastImpl().
CastImpl()
const void * UE::Sequencer::FCastableTypeTable::CastImpl (const void * BasePtr, uint32 ToType) const inline private
Cast implementation function.
Definition at line 110 of file CastableTypeTable.h.
References INDEX_NONE, StaticTypeOffsets, and TypeMask.
Referenced by Cast(), and Cast().
FindTypeByName()
SEQUENCERCORE_API const FCastableTypeTable * UE::Sequencer::FCastableTypeTable::FindTypeByName (FName InName) static
Attempt to locate a type table by its C++ name.
References FCastableTypeTable(), and InName.
GetTypeID()
uint32 UE::Sequencer::FCastableTypeTable::GetTypeID () const inline
Retrieve the type ID for this type table.
Warning: This type ID is not deterministic or stable across different processes and should not be saved persistently
Definition at line 100 of file CastableTypeTable.h.
References ThisTypeID.
GetTypeName()
FName UE::Sequencer::FCastableTypeTable::GetTypeName () const inline
Retrieve the C++ type name that this type table relates to.
Definition at line 90 of file CastableTypeTable.h.
References ThisTypeName.
MakeTypeTable() [1/3]
template<typename T> FCastableTypeTable * UE::Sequencer::FCastableTypeTable::MakeTypeTable (const ICastable * Unused, uint32 TypeID, FName InName) inline static
Definition at line 44 of file CastableTypeTable.h.
References FCastableTypeTable(), UE::Sequencer::FCastableTypeTable::FCastableTypeTableGenerator::Commit(), UE::Sequencer::FCastableTypeTable::FCastableTypeTableGenerator::Generate(), InName, and Unused.
MakeTypeTable() [2/3]
template<typename T> FCastableTypeTable * UE::Sequencer::FCastableTypeTable::MakeTypeTable (const IDynamicExtension * Unused, uint32 TypeID, FName InName) inline static
Definition at line 51 of file CastableTypeTable.h.
References FCastableTypeTable(), UE::Sequencer::FCastableTypeTable::FCastableTypeTableGenerator::Commit(), UE::Sequencer::FCastableTypeTable::FCastableTypeTableGenerator::Generate(), InName, and Unused.
MakeTypeTable() [3/3]
template<typename T> FCastableTypeTable * UE::Sequencer::FCastableTypeTable::MakeTypeTable (const void * Unused, uint32 TypeID, FName InName) inline static
Make a new type table for the templated type, ID and typename.
The new table is allocated using malloc and is intentionally leaked
Definition at line 39 of file CastableTypeTable.h.
References FCastableTypeTable(), InName, and Unused.
operator=() [1/2]
void UE::Sequencer::FCastableTypeTable::operator= (const FCastableTypeTable &) delete
References FCastableTypeTable().
operator=() [2/2]
void UE::Sequencer::FCastableTypeTable::operator= (FCastableTypeTable &&) delete
References FCastableTypeTable().
Field Documentation
NumStaticTypes
uint32 UE::Sequencer::FCastableTypeTable::NumStaticTypes private
The number of static types implemented within this type table.
Definition at line 244 of file CastableTypeTable.h.
StaticTypeOffsets
int16* UE::Sequencer::FCastableTypeTable::StaticTypeOffsets private
Ptr to the static type offsets allocated at the end of this struct.
Size = NumStaticTypes
Definition at line 240 of file CastableTypeTable.h.
Referenced by CastImpl().
ThisTypeID
uint32 UE::Sequencer::FCastableTypeTable::ThisTypeID private
Unique static type ID for this type.
Definition at line 246 of file CastableTypeTable.h.
Referenced by GetTypeID().
ThisTypeName
FName UE::Sequencer::FCastableTypeTable::ThisTypeName private
The name of the C++ type that this table relates to.
Definition at line 248 of file CastableTypeTable.h.
Referenced by GetTypeName().
TypeMask
MovieScene::TFixedSparseBitSet<uint32, MovieScene::TFixedSparseBitSetBucketStorage<uint8> > UE::Sequencer::FCastableTypeTable::TypeMask private
Fixed sparse bitset of types that this table contains.
Storage is allocated at the end of this struct.
Definition at line 242 of file CastableTypeTable.h.
Referenced by CastImpl().
The documentation for this struct was generated from the following file:
Editor/SequencerCore/Public/MVVM/CastableTypeTable.h