Unreal Engine 5.6 C++ API: FTextLocation Struct Reference
FTextLocation Struct Reference
Location within the text model.
#include "TextLayout.h"
Public Member Functions
FTextLocation (const FTextLocation &InLocation, const int32 InOffset)
FTextLocation (const int32 InLineIndex=0, const int32 InOffset=0)
int32 GetLineIndex () const
int32 GetOffset () const
bool IsValid () const
bool operator!= (const FTextLocation &Other) const
bool operator< (const FTextLocation &Other) const
bool operator== (const FTextLocation &Other) const
Private Attributes
int32 LineIndex
int32 Offset
Friends
FORCEINLINE uint32 GetTypeHash (const FTextLocation &InSubject)
Detailed Description
Location within the text model.
Definition at line 99 of file TextLayout.h.
Constructor & Destructor Documentation
FTextLocation() [1/2]
FTextLocation::FTextLocation (const int32 InLineIndex = 0, const int32 InOffset = 0) inline
Definition at line 102 of file TextLayout.h.
References LineIndex, and Offset.
Referenced by FTextLocation(), GetTypeHash, operator!=(), operator<(), and operator==().
FTextLocation() [2/2]
FTextLocation::FTextLocation (const FTextLocation & InLocation, const int32 InOffset) inline
Definition at line 109 of file TextLayout.h.
References FTextLocation(), GetLineIndex(), GetOffset(), LineIndex, Max, and Offset.
Member Function Documentation
GetLineIndex()
int32 FTextLocation::GetLineIndex () const inline
Definition at line 135 of file TextLayout.h.
References LineIndex.
Referenced by FTextLocation().
GetOffset()
int32 FTextLocation::GetOffset () const inline
Definition at line 136 of file TextLayout.h.
References Offset.
Referenced by FTextLocation().
IsValid()
bool FTextLocation::IsValid () const inline
Definition at line 137 of file TextLayout.h.
References INDEX_NONE, LineIndex, and Offset.
operator!=()
bool FTextLocation::operator!= (const FTextLocation & Other) const inline
Definition at line 123 of file TextLayout.h.
References FTextLocation(), LineIndex, Offset, and Other.
operator<()
bool FTextLocation::operator< (const FTextLocation & Other) const inline
Definition at line 130 of file TextLayout.h.
References FTextLocation(), LineIndex, Offset, and Other.
operator==()
bool FTextLocation::operator== (const FTextLocation & Other) const inline
Definition at line 116 of file TextLayout.h.
References FTextLocation(), LineIndex, Offset, and Other.
Friends And Related Symbol Documentation
GetTypeHash
FORCEINLINE uint32 GetTypeHash (const FTextLocation & InSubject) friend
Definition at line 139 of file TextLayout.h.
References FTextLocation(), FORCEINLINE, HashCombine(), LineIndex, and Offset.
Field Documentation
LineIndex
int32 FTextLocation::LineIndex private
Definition at line 145 of file TextLayout.h.
Referenced by FTextLocation(), FTextLocation(), GetLineIndex(), GetTypeHash, IsValid(), operator!=(), operator<(), and operator==().
Offset
int32 FTextLocation::Offset private
Definition at line 146 of file TextLayout.h.
Referenced by FTextLocation(), FTextLocation(), GetOffset(), GetTypeHash, IsValid(), operator!=(), operator<(), and operator==().
The documentation for this struct was generated from the following file:
Runtime/Slate/Public/Framework/Text/TextLayout.h