Unreal Engine 5.6 C++ API: TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::FPerThreadFreeBlockLists Struct Reference
TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::FPerThreadFreeBlockLists Struct Reference
#include "MallocBinnedCommon.h"
Public Member Functions
FORCEINLINE bool CanFree (uint32 InPoolIndex, uint32 InBinSize) const
FORCEINLINE bool Free (void *InPtr, uint32 InPoolIndex, uint32 InBinSize)
void Lock ()
FORCEINLINE void * Malloc (uint32 InPoolIndex)
template<class T>
bool ObtainRecycledPartial (uint32 InPoolIndex, T &InGlobalRecycler)
FBundleNode * PopBundles (uint32 InPoolIndex)
template<class T>
FBundleNode * RecycleFullBundle (uint32 InPoolIndex, T &InGlobalRecycler)
bool TryLock ()
void Unlock ()
bool UpdateEpoch (uint64 NewEpoch)
Static Public Member Functions
static void ClearTLS ()
static FORCEINLINE FPerThreadFreeBlockLists * Get () TSAN_SAFE
static void LockTLS ()
static void SetTLS ()
static void UnlockTLS ()
Data Fields
int64 AllocatedMemory = 0
Private Attributes
bool bLockedByOwnerThread = false
FFreeBlockList FreeLists [NUM_SMALL_POOLS]
uint64 MemoryTrimEpoch = 0
UE::FWordMutex Mutex
Detailed Description
template<class AllocType, int NumSmallPools, int MaxSmallPoolSize>
struct TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::FPerThreadFreeBlockLists
Definition at line 467 of file MallocBinnedCommon.h.
Member Function Documentation
CanFree()
template<class AllocType, int NumSmallPools, int MaxSmallPoolSize> FORCEINLINE bool TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::FPerThreadFreeBlockLists::CanFree (uint32 InPoolIndex, uint32 InBinSize) const inline
Definition at line 554 of file MallocBinnedCommon.h.
References FORCEINLINE, and FreeLists.
ClearTLS()
template<class AllocType, int NumSmallPools, int MaxSmallPoolSize> void TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::FPerThreadFreeBlockLists::ClearTLS () inline static
Definition at line 523 of file MallocBinnedCommon.h.
References Align, FMallocBinnedCommonBase::BinnedTlsSlot, bLockedByOwnerThread, check, FAndroidTLS::GetTlsValue(), FGenericPlatformTLS::IsValidTlsSlot(), FAndroidTLS::SetTlsValue(), FMallocBinnedCommonBase::TLSMemory, UE_MBC_UPDATE_STATS, Unlock(), and TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::UnregisterThreadFreeBlockLists().
Referenced by TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::ClearAndDisableTLSCachesOnCurrentThread().
Free()
template<class AllocType, int NumSmallPools, int MaxSmallPoolSize> FORCEINLINE bool TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::FPerThreadFreeBlockLists::Free (void * InPtr, uint32 InPoolIndex, uint32 InBinSize) inline
Definition at line 548 of file MallocBinnedCommon.h.
References FORCEINLINE, and FreeLists.
Get()
template<class AllocType, int NumSmallPools, int MaxSmallPoolSize> FORCEINLINE FPerThreadFreeBlockLists * TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::FPerThreadFreeBlockLists::Get () inline static
Definition at line 469 of file MallocBinnedCommon.h.
References FMallocBinnedCommonBase::BinnedTlsSlot, bLockedByOwnerThread, FORCEINLINE, FAndroidTLS::GetTlsValue(), FGenericPlatformTLS::IsValidTlsSlot(), and TSAN_SAFE.
Lock()
template<class AllocType, int NumSmallPools, int MaxSmallPoolSize> void TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::FPerThreadFreeBlockLists::Lock () inline
Definition at line 578 of file MallocBinnedCommon.h.
References Mutex.
Referenced by LockTLS(), and SetTLS().
LockTLS()
template<class AllocType, int NumSmallPools, int MaxSmallPoolSize> void TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::FPerThreadFreeBlockLists::LockTLS () inline static
Definition at line 513 of file MallocBinnedCommon.h.
References FMallocBinnedCommonBase::BinnedTlsSlot, bLockedByOwnerThread, FAndroidTLS::GetTlsValue(), and Lock().
Referenced by TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::MarkTLSCachesAsUsedOnCurrentThread().
Malloc()
template<class AllocType, int NumSmallPools, int MaxSmallPoolSize> FORCEINLINE void * TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::FPerThreadFreeBlockLists::Malloc (uint32 InPoolIndex) inline
Definition at line 542 of file MallocBinnedCommon.h.
References FORCEINLINE, and FreeLists.
ObtainRecycledPartial()
template<class AllocType, int NumSmallPools, int MaxSmallPoolSize> template<class T> bool TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::FPerThreadFreeBlockLists::ObtainRecycledPartial (uint32 InPoolIndex, T & InGlobalRecycler) inline
Definition at line 568 of file MallocBinnedCommon.h.
References FreeLists.
PopBundles()
template<class AllocType, int NumSmallPools, int MaxSmallPoolSize> FBundleNode * TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::FPerThreadFreeBlockLists::PopBundles (uint32 InPoolIndex) inline
Definition at line 573 of file MallocBinnedCommon.h.
References FreeLists.
RecycleFullBundle()
template<class AllocType, int NumSmallPools, int MaxSmallPoolSize> template<class T> FBundleNode * TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::FPerThreadFreeBlockLists::RecycleFullBundle (uint32 InPoolIndex, T & InGlobalRecycler) inline
Definition at line 561 of file MallocBinnedCommon.h.
References FreeLists.
SetTLS()
template<class AllocType, int NumSmallPools, int MaxSmallPoolSize> void TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::FPerThreadFreeBlockLists::SetTLS () inline static
Definition at line 485 of file MallocBinnedCommon.h.
References Align, FMallocBinnedCommonBase::BinnedTlsSlot, bLockedByOwnerThread, check, FAndroidTLS::GetTlsValue(), FGenericPlatformTLS::IsValidTlsSlot(), Lock(), TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::RegisterThreadFreeBlockLists(), FAndroidTLS::SetTlsValue(), FMallocBinnedCommonBase::TLSMemory, UE_MBC_UPDATE_STATS, and verify.
Referenced by TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::SetupTLSCachesOnCurrentThread().
TryLock()
template<class AllocType, int NumSmallPools, int MaxSmallPoolSize> bool TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::FPerThreadFreeBlockLists::TryLock () inline
Definition at line 583 of file MallocBinnedCommon.h.
References Mutex.
Unlock()
template<class AllocType, int NumSmallPools, int MaxSmallPoolSize> void TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::FPerThreadFreeBlockLists::Unlock () inline
Definition at line 588 of file MallocBinnedCommon.h.
References Mutex.
Referenced by ClearTLS(), and UnlockTLS().
UnlockTLS()
template<class AllocType, int NumSmallPools, int MaxSmallPoolSize> void TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::FPerThreadFreeBlockLists::UnlockTLS () inline static
Definition at line 503 of file MallocBinnedCommon.h.
References FMallocBinnedCommonBase::BinnedTlsSlot, bLockedByOwnerThread, FAndroidTLS::GetTlsValue(), and Unlock().
Referenced by TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::MarkTLSCachesAsUnusedOnCurrentThread().
UpdateEpoch()
template<class AllocType, int NumSmallPools, int MaxSmallPoolSize> bool TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::FPerThreadFreeBlockLists::UpdateEpoch (uint64 NewEpoch) inline
Definition at line 594 of file MallocBinnedCommon.h.
References MemoryTrimEpoch.
Field Documentation
AllocatedMemory
template<class AllocType, int NumSmallPools, int MaxSmallPoolSize> int64 TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::FPerThreadFreeBlockLists::AllocatedMemory = 0
Definition at line 607 of file MallocBinnedCommon.h.
Referenced by TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::UnregisterThreadFreeBlockLists().
bLockedByOwnerThread
template<class AllocType, int NumSmallPools, int MaxSmallPoolSize> bool TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::FPerThreadFreeBlockLists::bLockedByOwnerThread = false private
Definition at line 613 of file MallocBinnedCommon.h.
Referenced by ClearTLS(), Get(), LockTLS(), SetTLS(), and UnlockTLS().
FreeLists
template<class AllocType, int NumSmallPools, int MaxSmallPoolSize> FFreeBlockList TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::FPerThreadFreeBlockLists::FreeLists[NUM_SMALL_POOLS] private
Definition at line 612 of file MallocBinnedCommon.h.
Referenced by CanFree(), Free(), Malloc(), ObtainRecycledPartial(), PopBundles(), and RecycleFullBundle().
MemoryTrimEpoch
template<class AllocType, int NumSmallPools, int MaxSmallPoolSize> uint64 TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::FPerThreadFreeBlockLists::MemoryTrimEpoch = 0 private
Definition at line 611 of file MallocBinnedCommon.h.
Referenced by UpdateEpoch().
Mutex
template<class AllocType, int NumSmallPools, int MaxSmallPoolSize> UE::FWordMutex TMallocBinnedCommon< AllocType, NumSmallPools, MaxSmallPoolSize >::FPerThreadFreeBlockLists::Mutex private
Definition at line 610 of file MallocBinnedCommon.h.
Referenced by Lock(), TryLock(), and Unlock().
The documentation for this struct was generated from the following file:
Runtime/Core/Public/HAL/MallocBinnedCommon.h