Unreal Engine 5.6 C++ API: UE::MovieScene::FSystemTaskPrerequisites Struct Reference
UE::MovieScene::FSystemTaskPrerequisites Struct Reference
#include "MovieSceneSystemTaskDependencies.h"
Data Structures
struct FPrerequisite
Public Types
using FComponentTypeID = UE::MovieScene::FComponentTypeID
Public Member Functions
FSystemTaskPrerequisites ()
FSystemTaskPrerequisites (std::initializer_list< FGraphEventRef > InEvents)
MOVIESCENE_API void AddComponentTask (FComponentTypeID ComponentType, const FGraphEventRef &InNewTask)
void AddRootTask (const FGraphEventRef &InNewTask)
const FGraphEventArray * All () const
MOVIESCENE_API void Consume (const FSystemTaskPrerequisites &Other)
void Empty ()
FORCEINLINE void FilterByComponent (FGraphEventArray &OutArray, FComponentTypeID ComponentType) const
MOVIESCENE_API void FilterByComponent (FGraphEventArray &OutArray, std::initializer_list< FComponentTypeID > ComponentTypes) const
int32 Num () const
Private Attributes
FGraphEventArray AllTasks
TArray< FPrerequisite, TInlineAllocator< 4 > > Prereqs
Detailed Description
Definition at line 28 of file MovieSceneSystemTaskDependencies.h.
Member Typedef Documentation
FComponentTypeID
using UE::MovieScene::FSystemTaskPrerequisites::FComponentTypeID = UE::MovieScene::FComponentTypeID
Definition at line 30 of file MovieSceneSystemTaskDependencies.h.
Constructor & Destructor Documentation
FSystemTaskPrerequisites() [1/2]
UE::MovieScene::FSystemTaskPrerequisites::FSystemTaskPrerequisites () inline
Definition at line 32 of file MovieSceneSystemTaskDependencies.h.
Referenced by Consume().
FSystemTaskPrerequisites() [2/2]
UE::MovieScene::FSystemTaskPrerequisites::FSystemTaskPrerequisites (std::initializer_list< FGraphEventRef > InEvents) inline
Definition at line 35 of file MovieSceneSystemTaskDependencies.h.
References AllTasks, UE::MovieScene::FComponentTypeID::Invalid(), and Prereqs.
Member Function Documentation
AddComponentTask()
MOVIESCENE_API void UE::MovieScene::FSystemTaskPrerequisites::AddComponentTask (FComponentTypeID ComponentType, const FGraphEventRef & InNewTask)
Referenced by AddRootTask().
AddRootTask()
void UE::MovieScene::FSystemTaskPrerequisites::AddRootTask (const FGraphEventRef & InNewTask) inline
Definition at line 69 of file MovieSceneSystemTaskDependencies.h.
References AddComponentTask(), and UE::MovieScene::FComponentTypeID::Invalid().
Referenced by UE::MovieScene::TSimpleBlenderSystemImpl< PropertyType, ResultTraits >::Run().
All()
const FGraphEventArray * UE::MovieScene::FSystemTaskPrerequisites::All () const inline
Definition at line 49 of file MovieSceneSystemTaskDependencies.h.
References AllTasks, and Prereqs.
Consume()
MOVIESCENE_API void UE::MovieScene::FSystemTaskPrerequisites::Consume (const FSystemTaskPrerequisites & Other)
References FSystemTaskPrerequisites(), and Other.
Empty()
void UE::MovieScene::FSystemTaskPrerequisites::Empty () inline
Definition at line 78 of file MovieSceneSystemTaskDependencies.h.
References AllTasks, and Prereqs.
FilterByComponent() [1/2]
FORCEINLINE void UE::MovieScene::FSystemTaskPrerequisites::FilterByComponent (FGraphEventArray & OutArray, FComponentTypeID ComponentType) const inline
Definition at line 62 of file MovieSceneSystemTaskDependencies.h.
References FilterByComponent(), and FORCEINLINE.
Referenced by FilterByComponent(), UE::MovieScene::PopulatePrerequisites(), UE::MovieScene::PopulatePrerequisites(), and UE::MovieScene::TEntityTaskComponentsImpl< TIntegerSequence< int, Indices... >, T... >::PopulatePrerequisites().
FilterByComponent() [2/2]
MOVIESCENE_API void UE::MovieScene::FSystemTaskPrerequisites::FilterByComponent (FGraphEventArray & OutArray, std::initializer_list< FComponentTypeID > ComponentTypes) const
Num()
int32 UE::MovieScene::FSystemTaskPrerequisites::Num () const inline
Definition at line 44 of file MovieSceneSystemTaskDependencies.h.
References Prereqs.
Field Documentation
AllTasks
FGraphEventArray UE::MovieScene::FSystemTaskPrerequisites::AllTasks mutable private
Definition at line 92 of file MovieSceneSystemTaskDependencies.h.
Referenced by FSystemTaskPrerequisites(), All(), and Empty().
Prereqs
TArray<FPrerequisite, TInlineAllocator<4> > UE::MovieScene::FSystemTaskPrerequisites::Prereqs private
Definition at line 91 of file MovieSceneSystemTaskDependencies.h.
Referenced by FSystemTaskPrerequisites(), All(), Empty(), and Num().
The documentation for this struct was generated from the following file:
Runtime/MovieScene/Public/EntitySystem/MovieSceneSystemTaskDependencies.h