Unreal Engine 5.6 C++ API: UE::Anim::FCurveUtils Struct Reference
UE::Anim::FCurveUtils Struct Reference
#include "AnimCurveUtils.h"
Static Public Member Functions
template<typename NamePredicateType, typename ValuePredicateType, typename CurveAllocatorType, typename CurveElementType>
static FORCEINLINE_DEBUGGABLE void BuildSorted (TBaseBlendedCurve< CurveAllocatorType, CurveElementType > &OutCurve, int32 InNumElements, NamePredicateType InNamePredicate, ValuePredicateType InValuePredicate, const FCurveFilter *InFilter=nullptr)
template<typename CurveAllocatorType, typename CurveElementType>
static FORCEINLINE_DEBUGGABLE void BuildUnsorted (TBaseBlendedCurve< CurveAllocatorType, CurveElementType > &OutCurve, const TMap< FName, float > &InMap)
template<typename NamePredicateType, typename ValuePredicateType, typename CurveAllocatorType, typename CurveElementType>
static void BuildUnsorted (TBaseBlendedCurve< CurveAllocatorType, CurveElementType > &OutCurve, int32 InNumElements, NamePredicateType InNamePredicate, ValuePredicateType InValuePredicate, const FCurveFilter *InFilter=nullptr)
template<typename CurveAllocatorType, typename CurveElementType>
static FORCEINLINE_DEBUGGABLE void BuildUnsorted (TBaseBlendedCurve< CurveAllocatorType, CurveElementType > &OutCurve, std::initializer_list< TTuple< FName, float > > InInputArgs)
template<typename CurveAllocatorType, typename CurveElementType>
static FORCEINLINE_DEBUGGABLE void BuildUnsorted (TBaseBlendedCurve< CurveAllocatorType, CurveElementType > &OutCurve, std::initializer_list< TTuple< FName, float, UE::Anim::ECurveElementFlags > > InInputArgs)
template<typename CurveAllocatorType, typename CurveElementType>
static FORCEINLINE_DEBUGGABLE void BuildUnsorted (TBaseBlendedCurve< CurveAllocatorType, CurveElementType > &OutCurve, std::initializer_list< TTuple< FName, UE::Anim::ECurveElementFlags > > InInputArgs)
template<typename CurveAllocatorType, typename CurveElementType>
static FORCEINLINE_DEBUGGABLE void BuildUnsorted (TBaseBlendedCurve< CurveAllocatorType, CurveElementType > &OutCurve, TConstArrayView< TTuple< FName, float > > InInputArrayView)
template<typename NamePredicateType, typename ValuePredicateType, typename CurveAllocatorType, typename CurveElementType>
static FORCEINLINE_DEBUGGABLE void BuildUnsortedUnfiltered (TBaseBlendedCurve< CurveAllocatorType, CurveElementType > &OutCurve, int32 InNumElements, NamePredicateType InNamePredicate, ValuePredicateType InValuePredicate)
template<typename NamePredicateType, typename ValuePredicateType, typename ValidityPredicateType, typename CurveAllocatorType, typename CurveElementType>
static void BuildUnsortedValidated (TBaseBlendedCurve< CurveAllocatorType, CurveElementType > &OutCurve, int32 InNumElements, NamePredicateType InNamePredicate, ValuePredicateType InValuePredicate, ValidityPredicateType InValidityPredicate)
template<typename CurveType0, typename CurveType1, typename ValuePredicateType>
static void BulkGet (const CurveType0 &InCurve, const CurveType1 &InBulkCurves, ValuePredicateType InValuePredicate)
Extracts elements from curves in bulk.
template<typename CurveType0, typename CurveType1, typename ValuePredicateType>
static void BulkSet (CurveType0 &InCurve, const CurveType1 &InBulkCurves, ValuePredicateType InValuePredicate)
Inserts elements to curves in bulk.
template<typename CurveAllocatorType, typename CurveElementType>
static void Filter (TBaseBlendedCurve< CurveAllocatorType, CurveElementType > &InOutCurve, const FCurveFilter &InFilter)
Remove any curves in InOutCurve that are filtered by InFilter.
Static Private Member Functions
template<typename NamePredicateType, typename ValuePredicateType, typename CurveAllocatorType, typename CurveElementType>
static FORCEINLINE_DEBUGGABLE void BuildLinearUnfiltered (TBaseBlendedCurve< CurveAllocatorType, CurveElementType > &OutCurve, int32 InNumElements, NamePredicateType InNamePredicate, ValuePredicateType InValuePredicate)
template<typename NamePredicateType, typename ValuePredicateType, typename ValidityPredicateType, typename CurveAllocatorType, typename CurveElementType>
static FORCEINLINE_DEBUGGABLE void BuildLinearUnfiltered (TBaseBlendedCurve< CurveAllocatorType, CurveElementType > &OutCurve, int32 InNumElements, NamePredicateType InNamePredicate, ValuePredicateType InValuePredicate, ValidityPredicateType InValidityPredicate)
template<typename NamePredicateType, typename ValuePredicateType, typename CurveAllocatorType, typename CurveElementType>
static void BuildSortedFiltered (TBaseBlendedCurve< CurveAllocatorType, CurveElementType > &OutCurve, int32 InNumElements, NamePredicateType InNamePredicate, ValuePredicateType InValuePredicate, const FCurveFilter &InFilter)
static bool ElementPassesFilter (ECurveFilterMode InFilterMode, ECurveFilterFlags InFilterFlags)
Helper function used to apply filtering to elements.
Detailed Description
Definition at line 13 of file AnimCurveUtils.h.
Member Function Documentation
BuildLinearUnfiltered() [1/2]
template<typename NamePredicateType, typename ValuePredicateType, typename CurveAllocatorType, typename CurveElementType> FORCEINLINE_DEBUGGABLE void UE::Anim::FCurveUtils::BuildLinearUnfiltered (TBaseBlendedCurve< CurveAllocatorType, CurveElementType > & OutCurve, int32 InNumElements, NamePredicateType InNamePredicate, ValuePredicateType InValuePredicate) inline static private
Definition at line 133 of file AnimCurveUtils.h.
References UE::Anim::TNamedValueArray< InAllocatorType, InElementType >::CheckDuplicates(), UE::Anim::TNamedValueArray< InAllocatorType, InElementType >::Elements, TArray< InElementType, InAllocatorType >::Emplace(), UE::Anim::TNamedValueArray< InAllocatorType, InElementType >::Empty(), FORCEINLINE_DEBUGGABLE, and TBaseBlendedCurve< InAllocatorType, InElementType >::Reserve().
Referenced by BuildSorted(), BuildUnsorted(), BuildUnsortedUnfiltered(), and BuildUnsortedValidated().
BuildLinearUnfiltered() [2/2]
template<typename NamePredicateType, typename ValuePredicateType, typename ValidityPredicateType, typename CurveAllocatorType, typename CurveElementType> FORCEINLINE_DEBUGGABLE void UE::Anim::FCurveUtils::BuildLinearUnfiltered (TBaseBlendedCurve< CurveAllocatorType, CurveElementType > & OutCurve, int32 InNumElements, NamePredicateType InNamePredicate, ValuePredicateType InValuePredicate, ValidityPredicateType InValidityPredicate) inline static private
Definition at line 148 of file AnimCurveUtils.h.
References UE::Anim::TNamedValueArray< InAllocatorType, InElementType >::CheckDuplicates(), UE::Anim::TNamedValueArray< InAllocatorType, InElementType >::Elements, TArray< InElementType, InAllocatorType >::Emplace(), UE::Anim::TNamedValueArray< InAllocatorType, InElementType >::Empty(), FORCEINLINE_DEBUGGABLE, and TBaseBlendedCurve< InAllocatorType, InElementType >::Reserve().
BuildSorted()
template<typename NamePredicateType, typename ValuePredicateType, typename CurveAllocatorType, typename CurveElementType> FORCEINLINE_DEBUGGABLE void UE::Anim::FCurveUtils::BuildSorted (TBaseBlendedCurve< CurveAllocatorType, CurveElementType > & OutCurve, int32 InNumElements, NamePredicateType InNamePredicate, ValuePredicateType InValuePredicate, const FCurveFilter * InFilter = nullptr) inline static
Definition at line 168 of file AnimCurveUtils.h.
References UE::Anim::TNamedValueArray< InAllocatorType, InElementType >::bSorted, BuildLinearUnfiltered(), BuildSortedFiltered(), UE::Anim::TNamedValueArray< InAllocatorType, InElementType >::CheckSorted(), CURVE_PROFILE_CYCLE_COUNTER, and FORCEINLINE_DEBUGGABLE.
BuildSortedFiltered()
template<typename NamePredicateType, typename ValuePredicateType, typename CurveAllocatorType, typename CurveElementType> void UE::Anim::FCurveUtils::BuildSortedFiltered (TBaseBlendedCurve< CurveAllocatorType, CurveElementType > & OutCurve, int32 InNumElements, NamePredicateType InNamePredicate, ValuePredicateType InValuePredicate, const FCurveFilter & InFilter) inline static private
Definition at line 42 of file AnimCurveUtils.h.
References check, UE::Anim::TNamedValueArray< InAllocatorType, InElementType >::CheckDuplicates(), UE::Anim::DisallowAll, ElementPassesFilter(), UE::Anim::TNamedValueArray< InAllocatorType, InElementType >::Elements, TArray< InElementType, InAllocatorType >::Emplace(), UE::Anim::TNamedValueArray< InAllocatorType, InElementType >::Empty(), FName::FastLess(), UE::Anim::FCurveFilter::FilterMode, UE::Anim::None, TArray< InElementType, InAllocatorType >::Num(), TArray< InElementType, InAllocatorType >::Reserve(), TBaseBlendedCurve< InAllocatorType, InElementType >::Reserve(), RESTRICT, and UE::Anim::TNamedValueArray< InAllocatorType, InElementType >::SortElementsIfRequired().
Referenced by BuildSorted(), and BuildUnsorted().
BuildUnsorted() [1/6]
template<typename CurveAllocatorType, typename CurveElementType> FORCEINLINE_DEBUGGABLE void UE::Anim::FCurveUtils::BuildUnsorted (TBaseBlendedCurve< CurveAllocatorType, CurveElementType > & OutCurve, const TMap< FName, float > & InMap) inline static
Definition at line 197 of file AnimCurveUtils.h.
References CURVE_PROFILE_CYCLE_COUNTER, UE::Anim::TNamedValueArray< InAllocatorType, InElementType >::Elements, TArray< InElementType, InAllocatorType >::Emplace(), UE::Anim::TNamedValueArray< InAllocatorType, InElementType >::Empty(), FORCEINLINE_DEBUGGABLE, TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Num(), and TBaseBlendedCurve< InAllocatorType, InElementType >::Reserve().
BuildUnsorted() [2/6]
template<typename NamePredicateType, typename ValuePredicateType, typename CurveAllocatorType, typename CurveElementType> void UE::Anim::FCurveUtils::BuildUnsorted (TBaseBlendedCurve< CurveAllocatorType, CurveElementType > & OutCurve, int32 InNumElements, NamePredicateType InNamePredicate, ValuePredicateType InValuePredicate, const FCurveFilter * InFilter = nullptr) inline static
Definition at line 281 of file AnimCurveUtils.h.
References UE::Anim::TNamedValueArray< InAllocatorType, InElementType >::bSorted, BuildLinearUnfiltered(), BuildSortedFiltered(), UE::Anim::TNamedValueArray< InAllocatorType, InElementType >::CheckSorted(), CURVE_PROFILE_CYCLE_COUNTER, TArray< InElementType, InAllocatorType >::SetNumUninitialized(), and TArray< InElementType, InAllocatorType >::Sort().
BuildUnsorted() [3/6]
template<typename CurveAllocatorType, typename CurveElementType> FORCEINLINE_DEBUGGABLE void UE::Anim::FCurveUtils::BuildUnsorted (TBaseBlendedCurve< CurveAllocatorType, CurveElementType > & OutCurve, std::initializer_list< TTuple< FName, float > > InInputArgs) inline static
Definition at line 229 of file AnimCurveUtils.h.
References UE::Anim::TNamedValueArray< InAllocatorType, InElementType >::CheckDuplicates(), CURVE_PROFILE_CYCLE_COUNTER, UE::Anim::TNamedValueArray< InAllocatorType, InElementType >::Elements, TArray< InElementType, InAllocatorType >::Emplace(), UE::Anim::TNamedValueArray< InAllocatorType, InElementType >::Empty(), FORCEINLINE_DEBUGGABLE, and TBaseBlendedCurve< InAllocatorType, InElementType >::Reserve().
BuildUnsorted() [4/6]
template<typename CurveAllocatorType, typename CurveElementType> FORCEINLINE_DEBUGGABLE void UE::Anim::FCurveUtils::BuildUnsorted (TBaseBlendedCurve< CurveAllocatorType, CurveElementType > & OutCurve, std::initializer_list< TTuple< FName, float, UE::Anim::ECurveElementFlags > > InInputArgs) inline static
Definition at line 263 of file AnimCurveUtils.h.
References UE::Anim::TNamedValueArray< InAllocatorType, InElementType >::CheckDuplicates(), CURVE_PROFILE_CYCLE_COUNTER, UE::Anim::TNamedValueArray< InAllocatorType, InElementType >::Elements, TArray< InElementType, InAllocatorType >::Emplace(), UE::Anim::TNamedValueArray< InAllocatorType, InElementType >::Empty(), FORCEINLINE_DEBUGGABLE, and TBaseBlendedCurve< InAllocatorType, InElementType >::Reserve().
BuildUnsorted() [5/6]
template<typename CurveAllocatorType, typename CurveElementType> FORCEINLINE_DEBUGGABLE void UE::Anim::FCurveUtils::BuildUnsorted (TBaseBlendedCurve< CurveAllocatorType, CurveElementType > & OutCurve, std::initializer_list< TTuple< FName, UE::Anim::ECurveElementFlags > > InInputArgs) inline static
Definition at line 246 of file AnimCurveUtils.h.
References UE::Anim::TNamedValueArray< InAllocatorType, InElementType >::CheckDuplicates(), CURVE_PROFILE_CYCLE_COUNTER, UE::Anim::TNamedValueArray< InAllocatorType, InElementType >::Elements, TArray< InElementType, InAllocatorType >::Emplace(), UE::Anim::TNamedValueArray< InAllocatorType, InElementType >::Empty(), FORCEINLINE_DEBUGGABLE, and TBaseBlendedCurve< InAllocatorType, InElementType >::Reserve().
BuildUnsorted() [6/6]
template<typename CurveAllocatorType, typename CurveElementType> FORCEINLINE_DEBUGGABLE void UE::Anim::FCurveUtils::BuildUnsorted (TBaseBlendedCurve< CurveAllocatorType, CurveElementType > & OutCurve, TConstArrayView< TTuple< FName, float > > InInputArrayView) inline static
Definition at line 212 of file AnimCurveUtils.h.
References UE::Anim::TNamedValueArray< InAllocatorType, InElementType >::CheckDuplicates(), CURVE_PROFILE_CYCLE_COUNTER, UE::Anim::TNamedValueArray< InAllocatorType, InElementType >::Elements, TArray< InElementType, InAllocatorType >::Emplace(), UE::Anim::TNamedValueArray< InAllocatorType, InElementType >::Empty(), FORCEINLINE_DEBUGGABLE, and TBaseBlendedCurve< InAllocatorType, InElementType >::Reserve().
BuildUnsortedUnfiltered()
template<typename NamePredicateType, typename ValuePredicateType, typename CurveAllocatorType, typename CurveElementType> FORCEINLINE_DEBUGGABLE void UE::Anim::FCurveUtils::BuildUnsortedUnfiltered (TBaseBlendedCurve< CurveAllocatorType, CurveElementType > & OutCurve, int32 InNumElements, NamePredicateType InNamePredicate, ValuePredicateType InValuePredicate) inline static
Definition at line 188 of file AnimCurveUtils.h.
References BuildLinearUnfiltered(), CURVE_PROFILE_CYCLE_COUNTER, and FORCEINLINE_DEBUGGABLE.
BuildUnsortedValidated()
template<typename NamePredicateType, typename ValuePredicateType, typename ValidityPredicateType, typename CurveAllocatorType, typename CurveElementType> void UE::Anim::FCurveUtils::BuildUnsortedValidated (TBaseBlendedCurve< CurveAllocatorType, CurveElementType > & OutCurve, int32 InNumElements, NamePredicateType InNamePredicate, ValuePredicateType InValuePredicate, ValidityPredicateType InValidityPredicate) inline static
Definition at line 324 of file AnimCurveUtils.h.
References BuildLinearUnfiltered(), and CURVE_PROFILE_CYCLE_COUNTER.
BulkGet()
template<typename CurveType0, typename CurveType1, typename ValuePredicateType> void UE::Anim::FCurveUtils::BulkGet (const CurveType0 & InCurve, const CurveType1 & InBulkCurves, ValuePredicateType InValuePredicate) inline static
Extracts elements from curves in bulk.
This is more efficient that just calling Curve.Get() repeatedly.
Parameters
InCurve The curve to get values from
InBulkCurves The curve specifying values to get
InValuePredicate Predicate to get each value. Signature: (const CurveType1::ElementType& InElement1, float InValue) -> void
Definition at line 449 of file AnimCurveUtils.h.
References CURVE_PROFILE_CYCLE_COUNTER, and UE::Anim::FNamedValueArrayUtils::Intersection().
BulkSet()
template<typename CurveType0, typename CurveType1, typename ValuePredicateType> void UE::Anim::FCurveUtils::BulkSet (CurveType0 & InCurve, const CurveType1 & InBulkCurves, ValuePredicateType InValuePredicate) inline static
Inserts elements to curves in bulk.
This is more efficient that just calling Curve.Set() repeatedly.
Parameters
InCurve The curve to set values into
InBulkCurves The curve specifying values to set
InValuePredicate Predicate to set each value. Signature: (const CurveType1::ElementType& InElement1) -> float
Definition at line 468 of file AnimCurveUtils.h.
References CURVE_PROFILE_CYCLE_COUNTER, EnumHasAllFlags(), UE::Anim::FNamedValueArrayUtils::Union(), and UE::Anim::ValidArg1.
ElementPassesFilter()
bool UE::Anim::FCurveUtils::ElementPassesFilter (ECurveFilterMode InFilterMode, ECurveFilterFlags InFilterFlags) inline static private
Helper function used to apply filtering to elements.
Definition at line 17 of file AnimCurveUtils.h.
References UE::Anim::AllowOnlyFiltered, UE::Anim::DisallowAll, UE::Anim::Disallowed, UE::Anim::DisallowFiltered, EnumHasAnyFlags(), UE::Anim::Filtered, and UE::Anim::None.
Referenced by BuildSortedFiltered(), and Filter().
Filter()
template<typename CurveAllocatorType, typename CurveElementType> void UE::Anim::FCurveUtils::Filter (TBaseBlendedCurve< CurveAllocatorType, CurveElementType > & InOutCurve, const FCurveFilter & InFilter) inline static
Remove any curves in InOutCurve that are filtered by InFilter.
Definition at line 334 of file AnimCurveUtils.h.
References UE::Anim::AllowOnlyFiltered, UE::Anim::TNamedValueArray< InAllocatorType, InElementType >::CheckSorted(), CURVE_PROFILE_CYCLE_COUNTER, UE::Anim::DisallowAll, ElementPassesFilter(), UE::Anim::TNamedValueArray< InAllocatorType, InElementType >::Elements, UE::Anim::FCurveFilter::FilterMode, No, UE::Anim::None, UE::Anim::TNamedValueArray< InAllocatorType, InElementType >::Num(), TArray< InElementType, InAllocatorType >::RemoveAt(), TArray< InElementType, InAllocatorType >::Reset(), RESTRICT, and UE::Anim::TNamedValueArray< InAllocatorType, InElementType >::SortElementsIfRequired().
The documentation for this struct was generated from the following file:
Runtime/Engine/Public/Animation/AnimCurveUtils.h