Unreal Engine 5.6 C++ API: FGenericPlatformMath Struct Reference
FGenericPlatformMath Struct Reference
Generic implementation for most platforms.
#include "GenericPlatformMath.h"
Public Member Functions
template<>
FORCEINLINE double Abs (const double A)
template<>
FORCEINLINE float Abs (const float A)
Float specialization.
MIX_FLOATS_2_ARGS (Max)
MIX_FLOATS_2_ARGS (Min)
MIX_SIGNED_INTS_2_ARGS_CONSTEXPR (Max)
MIX_SIGNED_INTS_2_ARGS_CONSTEXPR (Min)
RESOLVE_FLOAT_AMBIGUITY_2_ARGS (Atan2)
RESOLVE_FLOAT_AMBIGUITY_2_ARGS (CopySign)
RESOLVE_FLOAT_AMBIGUITY_2_ARGS (Fmod)
RESOLVE_FLOAT_AMBIGUITY_2_ARGS (LogX)
RESOLVE_FLOAT_AMBIGUITY_2_ARGS (Pow)
UE_DEPRECATED (5.1, "IsNegative has been deprecated in favor of IsNegativeOrNegativeZero or simply A < 0.") static FORCEINLINE bool IsNegative(double A)
UE_DEPRECATED (5.1, "IsNegative has been deprecated in favor of IsNegativeOrNegativeZero or simply A < 0.") static FORCEINLINE bool IsNegative(float A)
UE_DEPRECATED (5.1, "IsNegativeDouble has been deprecated in favor of IsNegativeOrNegativeZero or simply A < 0.") static FORCEINLINE bool IsNegativeDouble(double A)
UE_DEPRECATED (5.1, "IsNegativeFloat has been deprecated in favor of IsNegativeOrNegativeZero or simply A < 0.") static FORCEINLINE bool IsNegativeFloat(float A)
Static Public Member Functions
template<class T>
static constexpr FORCEINLINE T Abs (const T A)
Computes absolute value in a generic way.
static FORCEINLINE double Acos (double Value)
static FORCEINLINE float Acos (float Value)
template<typename IntType UE_REQUIRES>
static FORCEINLINE bool AddAndCheckForOverflow (IntType A, IntType B, IntType &OutResult)
Adds two integers of any integer type, checking for overflow.
static float AsFloat (uint32 U)
Performs a bit cast of the given unsigned int to float of the same bit width.
static double AsFloat (uint64 U)
Performs a bit cast of the given unsigned int to float of the same bit width.
static FORCEINLINE double Asin (double Value)
static FORCEINLINE float Asin (float Value)
static uint64 AsUInt (double D)
Performs a bit cast of the given double to an unsigned int of the same bit width.
static uint32 AsUInt (float F)
Performs a bit cast of the given float to an unsigned int of the same bit width.
static FORCEINLINE double Atan (double Value)
static FORCEINLINE float Atan (float Value)
static double Atan2 (double Y, double X)
static float Atan2 (float Y, float X)
static constexpr FORCEINLINE uint32 CeilLogTwo (uint32 Arg)
Returns smallest N such that (1<<N)>=Arg.
static constexpr FORCEINLINE uint64 CeilLogTwo64 (uint64 Arg)
static FORCEINLINE double CeilToDouble (double F)
Converts a double to the nearest greater or equal integer.
static FORCEINLINE double CeilToFloat (double F)
static FORCEINLINE float CeilToFloat (float F)
Converts a float to the nearest greater or equal integer.
static FORCEINLINE int64 CeilToInt (double F)
static FORCEINLINE int32 CeilToInt (float F)
static FORCEINLINE int32 CeilToInt32 (double F)
static FORCEINLINE int32 CeilToInt32 (float F)
Converts a float to the nearest greater or equal integer.
static FORCEINLINE int64 CeilToInt64 (double F)
static constexpr FORCEINLINE uint8 ConstExprCeilLogTwo (SIZE_T Arg)
Returns the smallest N such that (1<<N)>=Arg.
static FORCEINLINE double CopySign (double X, double Y)
static FORCEINLINE float CopySign (float X, float Y)
Composes a floating-point value with the magnitude of X and the sign of Y.
static FORCEINLINE double Cos (double Value)
static FORCEINLINE float Cos (float Value)
static FORCEINLINE double Cosh (double Value)
static FORCEINLINE float Cosh (float Value)
static constexpr FORCEINLINE int32 CountBits (uint64 Bits)
static constexpr FORCEINLINE uint32 CountLeadingZeros (uint32 Value)
Counts the number of leading zeros in the bit representation of the 32-bit value.
static constexpr FORCEINLINE uint64 CountLeadingZeros64 (uint64 Value)
Counts the number of leading zeros in the bit representation of the 64-bit value.
static constexpr FORCEINLINE uint8 CountLeadingZeros8 (uint8 Value)
Counts the number of leading zeros in the bit representation of the 8-bit value.
static constexpr FORCEINLINE uint32 CountTrailingZeros (uint32 Value)
static constexpr FORCEINLINE uint64 CountTrailingZeros64 (uint64 Value)
static constexpr FORCEINLINE uint64 CountTrailingZeros64ConstExpr (uint64 Value)
Counts the number of trailing zeros in the bit representation of the value.
static constexpr FORCEINLINE uint32 CountTrailingZerosConstExpr (uint32 Value)
Counts the number of trailing zeros in the bit representation of the value.
static FORCEINLINE double Exp (double Value)
static FORCEINLINE float Exp (float Value)
static FORCEINLINE double Exp2 (double Value)
static FORCEINLINE float Exp2 (float Value)
static constexpr FORCEINLINE double FloatSelect (double Comparand, double ValueGEZero, double ValueLTZero)
Returns value based on comparand.
static constexpr FORCEINLINE float FloatSelect (float Comparand, float ValueGEZero, float ValueLTZero)
Returns value based on comparand.
static constexpr FORCEINLINE uint32 FloorLog2 (uint32 Value)
Computes the base 2 logarithm for an integer value.
static constexpr FORCEINLINE uint64 FloorLog2_64 (uint64 Value)
Computes the base 2 logarithm for a 64-bit value.
static constexpr FORCEINLINE uint32 FloorLog2NonZero (uint32 Value)
FloorLog2 but the caller guarantees that Value is not 0.
static constexpr FORCEINLINE uint64 FloorLog2NonZero_64 (uint64 Value)
FloorLog2_64 but the caller guarantees that Value is not 0.
static FORCEINLINE double FloorToDouble (double F)
Converts a double to a less or equal integer.
static FORCEINLINE double FloorToFloat (double F)
static FORCEINLINE float FloorToFloat (float F)
Converts a float to the nearest less or equal integer.
static FORCEINLINE int64 FloorToInt (double F)
static FORCEINLINE int32 FloorToInt (float F)
static FORCEINLINE int32 FloorToInt32 (double F)
static FORCEINLINE int32 FloorToInt32 (float F)
Converts a float to a nearest less or equal integer.
static FORCEINLINE int64 FloorToInt64 (double F)
static FORCENOINLINE double Fmod (double X, double Y)
static FORCENOINLINE float Fmod (float X, float Y)
Returns the floating-point remainder of X / Y Warning: Always returns remainder toward 0, not toward the smaller multiple of Y.
static FORCEINLINE double Frac (double Value)
static FORCEINLINE float Frac (float Value)
Returns the fractional part of a float.
static FORCEINLINE double Fractional (double Value)
static FORCEINLINE float Fractional (float Value)
Returns signed fractional part of a float.
static FORCEINLINE float FRand ()
Returns a random float between 0 and 1, inclusive.
template<class T>
static constexpr FORCEINLINE void GetMinMax (const T &A, const T &B, T &OutMin, T &OutMax)
Sort input A & B values into OutMin & OutMax.
template<class T>
static constexpr FORCEINLINE void GetMinMax (T &Min, T &Max)
Sort input values to be Min and Max.
static int32 GetRandSeed ()
Returns the current seed for SRand().
static FORCEINLINE double InvSqrt (double F)
static FORCEINLINE float InvSqrt (float F)
Computes a fully accurate inverse square root.
static FORCEINLINE double InvSqrtEst (double F)
static FORCEINLINE float InvSqrtEst (float F)
Computes a faster but less accurate inverse square root.
static FORCEINLINE bool IsFinite (double A)
static FORCEINLINE bool IsFinite (float A)
Return true if value is finite (not NaN and not Infinity).
static FORCEINLINE bool IsNaN (double A)
static FORCEINLINE bool IsNaN (float A)
Return true if value is NaN (not a number).
static FORCEINLINE bool IsNegativeOrNegativeZero (double A)
static FORCEINLINE bool IsNegativeOrNegativeZero (float A)
static constexpr FORCEINLINE float LoadHalf (const uint16 *Ptr)
static FORCEINLINE double Log2 (double Value)
static FORCEINLINE float Log2 (float Value)
static FORCEINLINE double Loge (double Value)
static FORCEINLINE float Loge (float Value)
static FORCEINLINE double LogX (double Base, double Value)
static FORCEINLINE float LogX (float Base, float Value)
template<class T>
static FORCEINLINE T Max (const TArray< T > &Values)
Max of Array.
template<class T>
static FORCEINLINE T Max (const TArray< T > &Values, int32 *MaxIndex)
Max of Array.
template<typename T, typename... OtherTypes UE_REQUIRES>
static constexpr FORCEINLINE T Max (T A, OtherTypes... Others)
template<typename T>
static constexpr FORCEINLINE T Max (T A, T B)
Returns higher value in a generic way.
template<class T>
static FORCEINLINE T Min (const TArray< T > &Values)
Min of Array.
template<class T>
static FORCEINLINE T Min (const TArray< T > &Values, int32 *MinIndex)
Min of Array.
template<typename T, typename... OtherTypes UE_REQUIRES>
static constexpr FORCEINLINE T Min (T A, OtherTypes... Others)
template<typename T>
static constexpr FORCEINLINE T Min (T A, T B)
Returns lower value in a generic way.
static FORCEINLINE double Modf (const double InValue, double *OutIntPart)
Breaks the given value into an integral and a fractional part.
static FORCEINLINE float Modf (const float InValue, float *OutIntPart)
Breaks the given value into an integral and a fractional part.
static constexpr FORCEINLINE uint32 MortonCode2 (uint32 x)
Spreads bits to every other.
static constexpr FORCEINLINE uint64 MortonCode2_64 (uint64 x)
static constexpr FORCEINLINE uint32 MortonCode3 (uint32 x)
Spreads bits to every 3rd.
template<typename IntType UE_REQUIRES>
static FORCEINLINE bool MultiplyAndCheckForOverflow (IntType A, IntType B, IntType &OutResult)
Multiplies two integers of any integer type, checking for overflow.
static FORCEINLINE double Pow (double A, double B)
static FORCEINLINE float Pow (float A, float B)
static FORCEINLINE int32 Rand ()
Returns a random integer between 0 and RAND_MAX, inclusive.
static FORCEINLINE int32 Rand32 ()
Returns a random integer between 0 and MAX_int32, inclusive.
static FORCEINLINE void RandInit (int32 Seed)
Seeds global random number functions Rand() and FRand()
static constexpr FORCEINLINE uint32 ReverseMortonCode2 (uint32 x)
Reverses MortonCode2.
static constexpr FORCEINLINE uint64 ReverseMortonCode2_64 (uint64 x)
static constexpr FORCEINLINE uint32 ReverseMortonCode3 (uint32 x)
Reverses MortonCode3.
static FORCEINLINE double RoundToDouble (double F)
Converts a double to the nearest integer.
static FORCEINLINE double RoundToFloat (double F)
static FORCEINLINE float RoundToFloat (float F)
Converts a float to the nearest integer.
static FORCEINLINE int64 RoundToInt (double F)
static FORCEINLINE int32 RoundToInt (float F)
static FORCEINLINE int32 RoundToInt32 (double F)
static FORCEINLINE int32 RoundToInt32 (float F)
Converts a float to the nearest integer.
static FORCEINLINE int64 RoundToInt64 (double F)
static int64 RoundToNearestTiesToEven (double F)
Converts a double to nearest int64 with ties rounding to nearest even May incur a performance penalty.
static constexpr FORCEINLINE uint32 RoundUpToPowerOfTwo (uint32 Arg)
static constexpr FORCEINLINE uint64 RoundUpToPowerOfTwo64 (uint64 V)
template<class T>
static constexpr FORCEINLINE T Sign (const T A)
Returns 1, 0, or -1 depending on relation of T to 0.
static FORCEINLINE double Sin (double Value)
static FORCEINLINE float Sin (float Value)
static FORCEINLINE double Sinh (double Value)
static FORCEINLINE float Sinh (float Value)
static FORCEINLINE double Sqrt (double Value)
static FORCEINLINE float Sqrt (float Value)
static float SRand ()
Returns a seeded random float in the range [0,1), using the seed from SRandInit().
static void SRandInit (int32 Seed)
Seeds future calls to SRand()
static constexpr FORCEINLINE void StoreHalf (uint16 *Ptr, float Value)
template<typename IntType UE_REQUIRES>
static FORCEINLINE bool SubtractAndCheckForOverflow (IntType A, IntType B, IntType &OutResult)
Subtracts two integers of any integer type, checking for overflow.
static FORCEINLINE double Tan (double Value)
static FORCEINLINE float Tan (float Value)
static FORCEINLINE double Tanh (double Value)
static FORCEINLINE float Tanh (float Value)
static FORCEINLINE double TruncToDouble (double F)
Converts a double to an integer value with truncation towards zero.
static FORCEINLINE double TruncToFloat (double F)
static FORCEINLINE float TruncToFloat (float F)
Converts a float to an integer value with truncation towards zero.
static constexpr FORCEINLINE int64 TruncToInt (double F)
static constexpr FORCEINLINE int32 TruncToInt (float F)
static constexpr FORCEINLINE int32 TruncToInt32 (double F)
static constexpr FORCEINLINE int32 TruncToInt32 (float F)
Converts a float to an integer with truncation towards zero.
static constexpr FORCEINLINE int64 TruncToInt64 (double F)
static constexpr FORCEINLINE void VectorLoadHalf (float *RESTRICT Dst, const uint16 *RESTRICT Src)
static constexpr FORCEINLINE void VectorStoreHalf (uint16 *RESTRICT Dst, const float *RESTRICT Src)
static constexpr FORCEINLINE void WideVectorLoadHalf (float *RESTRICT Dst, const uint16 *RESTRICT Src)
static constexpr FORCEINLINE void WideVectorStoreHalf (uint16 *RESTRICT Dst, const float *RESTRICT Src)
Static Private Member Functions
static void FmodReportError (double X, double Y)
static void FmodReportError (float X, float Y)
Error reporting for Fmod.
Detailed Description
Generic implementation for most platforms.
Definition at line 30 of file GenericPlatformMath.h.
Member Function Documentation
Abs() [1/3]
template<> FORCEINLINE double FGenericPlatformMath::Abs (const double A) nodiscard
Definition at line 1361 of file GenericPlatformMath.h.
References A, and FORCEINLINE.
Abs() [2/3]
template<> FORCEINLINE float FGenericPlatformMath::Abs (const float A) nodiscard
Float specialization.
Definition at line 1356 of file GenericPlatformMath.h.
References A, and FORCEINLINE.
Abs() [3/3]
template<class T> constexpr FORCEINLINE T FGenericPlatformMath::Abs (const T A) inline static nodiscard constexpr
Computes absolute value in a generic way.
Definition at line 946 of file GenericPlatformMath.h.
References A, and FORCEINLINE.
Referenced by UE::Color::DecodeREDLog3G10(), and UE::Color::EncodeREDLog3G10().
Acos() [1/2]
FORCEINLINE double FGenericPlatformMath::Acos (double Value) inline static nodiscard
Definition at line 533 of file GenericPlatformMath.h.
References FORCEINLINE, and Value.
Acos() [2/2]
FORCEINLINE float FGenericPlatformMath::Acos (float Value) inline static nodiscard
Definition at line 532 of file GenericPlatformMath.h.
References FORCEINLINE, and Value.
AddAndCheckForOverflow()
template<typename IntType UE_REQUIRES> FORCEINLINE bool FGenericPlatformMath::AddAndCheckForOverflow (IntType A, IntType B, IntType & OutResult) inline static nodiscard
Adds two integers of any integer type, checking for overflow.
If there was overflow, it returns false, and OutResult may or may not be written. If there wasn't overflow, it returns true, and the result of the addition is written to OutResult.
Definition at line 1188 of file GenericPlatformMath.h.
References A, B, and FORCEINLINE.
AsFloat() [1/2]
float FGenericPlatformMath::AsFloat (uint32 U) inline static nodiscard
Performs a bit cast of the given unsigned int to float of the same bit width.
Parameters
U The 32-bit unsigned int to bit cast to a 32-bit float.
Returns
A bitwise copy of the 32-bit float in a 32-bit unsigned integer value.
Definition at line 184 of file GenericPlatformMath.h.
AsFloat() [2/2]
double FGenericPlatformMath::AsFloat (uint64 U) inline static nodiscard
Performs a bit cast of the given unsigned int to float of the same bit width.
Parameters
U The 64-bit unsigned int to bit cast to a 64-bit float.
Returns
A bitwise copy of the 64-bit float in a 64-bit unsigned integer value.
Definition at line 197 of file GenericPlatformMath.h.
Asin() [1/2]
FORCEINLINE double FGenericPlatformMath::Asin (double Value) inline static nodiscard
Definition at line 524 of file GenericPlatformMath.h.
References FORCEINLINE, and Value.
Asin() [2/2]
FORCEINLINE float FGenericPlatformMath::Asin (float Value) inline static nodiscard
Definition at line 523 of file GenericPlatformMath.h.
References FORCEINLINE, and Value.
AsUInt() [1/2]
uint64 FGenericPlatformMath::AsUInt (double D) inline static nodiscard
Performs a bit cast of the given double to an unsigned int of the same bit width.
Parameters
D The double to bit cast to an unsigned integer.
Returns
A bitwise copy of the double in a 64-bit unsigned integer value.
Definition at line 171 of file GenericPlatformMath.h.
AsUInt() [2/2]
uint32 FGenericPlatformMath::AsUInt (float F) inline static nodiscard
Performs a bit cast of the given float to an unsigned int of the same bit width.
Parameters
F The float to bit cast to an unsigned integer.
Returns
A bitwise copy of the float in a 32-bit unsigned integer value.
Definition at line 158 of file GenericPlatformMath.h.
Atan() [1/2]
FORCEINLINE double FGenericPlatformMath::Atan (double Value) inline static nodiscard
Definition at line 542 of file GenericPlatformMath.h.
References FORCEINLINE, and Value.
Atan() [2/2]
FORCEINLINE float FGenericPlatformMath::Atan (float Value) inline static nodiscard
Definition at line 541 of file GenericPlatformMath.h.
References FORCEINLINE, and Value.
Atan2() [1/2]
double FGenericPlatformMath::Atan2 (double Y, double X) static nodiscard
References X, and Y.
Atan2() [2/2]
float FGenericPlatformMath::Atan2 (float Y, float X) static nodiscard
References X, and Y.
Referenced by RESOLVE_FLOAT_AMBIGUITY_2_ARGS().
CeilLogTwo()
constexpr FORCEINLINE uint32 FGenericPlatformMath::CeilLogTwo (uint32 Arg) inline static nodiscard constexpr
Returns smallest N such that (1<<N)>=Arg.
Note: CeilLogTwo(0)=0
Definition at line 797 of file GenericPlatformMath.h.
References CountLeadingZeros(), and FORCEINLINE.
Referenced by RoundUpToPowerOfTwo().
CeilLogTwo64()
constexpr FORCEINLINE uint64 FGenericPlatformMath::CeilLogTwo64 (uint64 Arg) inline static nodiscard constexpr
Definition at line 804 of file GenericPlatformMath.h.
References CountLeadingZeros64(), and FORCEINLINE.
Referenced by RoundUpToPowerOfTwo64().
CeilToDouble()
FORCEINLINE double FGenericPlatformMath::CeilToDouble (double F) inline static nodiscard
Converts a double to the nearest greater or equal integer.
Parameters
F Floating point value to convert
Returns
An integer greater or equal to 'F'.
Definition at line 393 of file GenericPlatformMath.h.
References FORCEINLINE.
Referenced by CeilToFloat().
CeilToFloat() [1/2]
FORCEINLINE double FGenericPlatformMath::CeilToFloat (double F) inline static nodiscard
Definition at line 398 of file GenericPlatformMath.h.
References CeilToDouble(), and FORCEINLINE.
CeilToFloat() [2/2]
FORCEINLINE float FGenericPlatformMath::CeilToFloat (float F) inline static nodiscard
Converts a float to the nearest greater or equal integer.
Parameters
F Floating point value to convert
Returns
An integer greater or equal to 'F'.
Definition at line 383 of file GenericPlatformMath.h.
References FORCEINLINE.
CeilToInt() [1/2]
FORCEINLINE int64 FGenericPlatformMath::CeilToInt (double F) inline static nodiscard
Definition at line 376 of file GenericPlatformMath.h.
References CeilToInt64(), and FORCEINLINE.
CeilToInt() [2/2]
FORCEINLINE int32 FGenericPlatformMath::CeilToInt (float F) inline static nodiscard
Definition at line 375 of file GenericPlatformMath.h.
References CeilToInt32(), and FORCEINLINE.
CeilToInt32() [1/2]
FORCEINLINE int32 FGenericPlatformMath::CeilToInt32 (double F) inline static nodiscard
Definition at line 362 of file GenericPlatformMath.h.
References FORCEINLINE, and TruncToInt32().
CeilToInt32() [2/2]
FORCEINLINE int32 FGenericPlatformMath::CeilToInt32 (float F) inline static nodiscard
Converts a float to the nearest greater or equal integer.
Parameters
F Floating point value to convert
Returns
An integer greater or equal to 'F'.
Definition at line 356 of file GenericPlatformMath.h.
References float, FORCEINLINE, and TruncToInt32().
Referenced by CeilToInt().
CeilToInt64()
FORCEINLINE int64 FGenericPlatformMath::CeilToInt64 (double F) inline static nodiscard
Definition at line 368 of file GenericPlatformMath.h.
References FORCEINLINE, and TruncToInt64().
Referenced by CeilToInt().
ConstExprCeilLogTwo()
constexpr FORCEINLINE uint8 FGenericPlatformMath::ConstExprCeilLogTwo (SIZE_T Arg) inline static nodiscard constexpr
Returns the smallest N such that (1<<N)>=Arg.
This is a less efficient version of CeilLogTwo, but written in a way that can be evaluated at compile-time.
Definition at line 815 of file GenericPlatformMath.h.
References ConstExprCeilLogTwo(), and FORCEINLINE.
Referenced by ConstExprCeilLogTwo().
CopySign() [1/2]
FORCEINLINE double FGenericPlatformMath::CopySign (double X, double Y) inline static nodiscard
Definition at line 568 of file GenericPlatformMath.h.
References FORCEINLINE, X, and Y.
CopySign() [2/2]
FORCEINLINE float FGenericPlatformMath::CopySign (float X, float Y) inline static nodiscard
Composes a floating-point value with the magnitude of X and the sign of Y.
Definition at line 567 of file GenericPlatformMath.h.
References FORCEINLINE, X, and Y.
Referenced by RESOLVE_FLOAT_AMBIGUITY_2_ARGS().
Cos() [1/2]
FORCEINLINE double FGenericPlatformMath::Cos (double Value) inline static nodiscard
Definition at line 530 of file GenericPlatformMath.h.
References FORCEINLINE, and Value.
Cos() [2/2]
FORCEINLINE float FGenericPlatformMath::Cos (float Value) inline static nodiscard
Definition at line 529 of file GenericPlatformMath.h.
References FORCEINLINE, and Value.
Cosh() [1/2]
FORCEINLINE double FGenericPlatformMath::Cosh (double Value) inline static nodiscard
Definition at line 536 of file GenericPlatformMath.h.
References FORCEINLINE, and Value.
Cosh() [2/2]
FORCEINLINE float FGenericPlatformMath::Cosh (float Value) inline static nodiscard
Definition at line 535 of file GenericPlatformMath.h.
References FORCEINLINE, and Value.
CountBits()
constexpr FORCEINLINE int32 FGenericPlatformMath::CountBits (uint64 Bits) inline static nodiscard constexpr
Definition at line 1165 of file GenericPlatformMath.h.
References FORCEINLINE.
CountLeadingZeros()
constexpr FORCEINLINE uint32 FGenericPlatformMath::CountLeadingZeros (uint32 Value) inline static nodiscard constexpr
Counts the number of leading zeros in the bit representation of the 32-bit value.
Parameters
Value the value to determine the number of leading zeros for
Returns
the number of zeros before the first "on" bit
Definition at line 720 of file GenericPlatformMath.h.
References FloorLog2(), FORCEINLINE, and Value.
Referenced by CeilLogTwo().
CountLeadingZeros64()
constexpr FORCEINLINE uint64 FGenericPlatformMath::CountLeadingZeros64 (uint64 Value) inline static nodiscard constexpr
Counts the number of leading zeros in the bit representation of the 64-bit value.
Parameters
Value the value to determine the number of leading zeros for
Returns
the number of zeros before the first "on" bit
Definition at line 733 of file GenericPlatformMath.h.
References FloorLog2_64(), FORCEINLINE, and Value.
Referenced by CeilLogTwo64().
CountLeadingZeros8()
constexpr FORCEINLINE uint8 FGenericPlatformMath::CountLeadingZeros8 (uint8 Value) inline static nodiscard constexpr
Counts the number of leading zeros in the bit representation of the 8-bit value.
Parameters
Value the value to determine the number of leading zeros for
Returns
the number of zeros before the first "on" bit
Definition at line 707 of file GenericPlatformMath.h.
References FloorLog2(), FORCEINLINE, and Value.
CountTrailingZeros()
constexpr FORCEINLINE uint32 FGenericPlatformMath::CountTrailingZeros (uint32 Value) inline static nodiscard constexpr
Definition at line 761 of file GenericPlatformMath.h.
References CountTrailingZerosConstExpr(), FORCEINLINE, and Value.
CountTrailingZeros64()
constexpr FORCEINLINE uint64 FGenericPlatformMath::CountTrailingZeros64 (uint64 Value) inline static nodiscard constexpr
Definition at line 788 of file GenericPlatformMath.h.
References CountTrailingZeros64ConstExpr(), FORCEINLINE, and Value.
CountTrailingZeros64ConstExpr()
constexpr FORCEINLINE uint64 FGenericPlatformMath::CountTrailingZeros64ConstExpr (uint64 Value) inline static nodiscard constexpr
Counts the number of trailing zeros in the bit representation of the value.
Parameters
Value the value to determine the number of trailing zeros for
Returns
the number of zeros after the last "on" bit
Definition at line 773 of file GenericPlatformMath.h.
References FORCEINLINE, and Value.
Referenced by CountTrailingZeros64().
CountTrailingZerosConstExpr()
constexpr FORCEINLINE uint32 FGenericPlatformMath::CountTrailingZerosConstExpr (uint32 Value) inline static nodiscard constexpr
Counts the number of trailing zeros in the bit representation of the value.
Parameters
Value the value to determine the number of trailing zeros for
Returns
the number of zeros after the last "on" bit
Definition at line 746 of file GenericPlatformMath.h.
References FORCEINLINE, and Value.
Referenced by CountTrailingZeros().
Exp() [1/2]
FORCEINLINE double FGenericPlatformMath::Exp (double Value) inline static nodiscard
Definition at line 488 of file GenericPlatformMath.h.
References FORCEINLINE, and Value.
Exp() [2/2]
FORCEINLINE float FGenericPlatformMath::Exp (float Value) inline static nodiscard
Definition at line 486 of file GenericPlatformMath.h.
References FORCEINLINE, and Value.
Exp2() [1/2]
FORCEINLINE double FGenericPlatformMath::Exp2 (double Value) inline static nodiscard
Definition at line 492 of file GenericPlatformMath.h.
References FORCEINLINE, and Value.
Exp2() [2/2]
FORCEINLINE float FGenericPlatformMath::Exp2 (float Value) inline static nodiscard
Definition at line 491 of file GenericPlatformMath.h.
References FORCEINLINE, and Value.
FloatSelect() [1/2]
constexpr FORCEINLINE double FGenericPlatformMath::FloatSelect (double Comparand, double ValueGEZero, double ValueLTZero) inline static nodiscard constexpr
Returns value based on comparand.
The main purpose of this function is to avoid branching based on floating point comparison which can be avoided via compiler intrinsics.
Please note that we don't define what happens in the case of NaNs as there might be platform specific differences.
Parameters
Comparand Comparand the results are based on
ValueGEZero Return value if Comparand >= 0
ValueLTZero Return value if Comparand < 0
Returns
ValueGEZero if Comparand >= 0, ValueLTZero otherwise
Definition at line 939 of file GenericPlatformMath.h.
References FORCEINLINE.
FloatSelect() [2/2]
constexpr FORCEINLINE float FGenericPlatformMath::FloatSelect (float Comparand, float ValueGEZero, float ValueLTZero) inline static nodiscard constexpr
Returns value based on comparand.
The main purpose of this function is to avoid branching based on floating point comparison which can be avoided via compiler intrinsics.
Please note that we don't define what happens in the case of NaNs as there might be platform specific differences.
Parameters
Comparand Comparand the results are based on
ValueGEZero Return value if Comparand >= 0
ValueLTZero Return value if Comparand < 0
Returns
ValueGEZero if Comparand >= 0, ValueLTZero otherwise
Definition at line 920 of file GenericPlatformMath.h.
References FORCEINLINE.
FloorLog2()
constexpr FORCEINLINE uint32 FGenericPlatformMath::FloorLog2 (uint32 Value) inline static nodiscard constexpr
Computes the base 2 logarithm for an integer value.
The result is rounded down to the nearest integer.
Parameters
Value The value to compute the log of
Returns
Log2 of Value. 0 if Value is 0.
Definition at line 658 of file GenericPlatformMath.h.
References FORCEINLINE, and Value.
Referenced by CountLeadingZeros(), CountLeadingZeros8(), and FloorLog2NonZero().
FloorLog2_64()
constexpr FORCEINLINE uint64 FGenericPlatformMath::FloorLog2_64 (uint64 Value) inline static nodiscard constexpr
Computes the base 2 logarithm for a 64-bit value.
The result is rounded down to the nearest integer.
Parameters
Value The value to compute the log of
Returns
Log2 of Value. 0 if Value is 0.
Definition at line 682 of file GenericPlatformMath.h.
References FORCEINLINE, and Value.
Referenced by CountLeadingZeros64(), and FloorLog2NonZero_64().
FloorLog2NonZero()
constexpr FORCEINLINE uint32 FGenericPlatformMath::FloorLog2NonZero (uint32 Value) inline static nodiscard constexpr
FloorLog2 but the caller guarantees that Value is not 0.
Definition at line 670 of file GenericPlatformMath.h.
References FloorLog2(), FORCEINLINE, and Value.
FloorLog2NonZero_64()
constexpr FORCEINLINE uint64 FGenericPlatformMath::FloorLog2NonZero_64 (uint64 Value) inline static nodiscard constexpr
FloorLog2_64 but the caller guarantees that Value is not 0.
Definition at line 695 of file GenericPlatformMath.h.
References FloorLog2_64(), FORCEINLINE, and Value.
FloorToDouble()
FORCEINLINE double FGenericPlatformMath::FloorToDouble (double F) inline static nodiscard
Converts a double to a less or equal integer.
Parameters
F Floating point value to convert
Returns
The nearest integer value to 'F'.
Definition at line 295 of file GenericPlatformMath.h.
References FORCEINLINE.
Referenced by FloorToFloat(), Frac(), and RoundToDouble().
FloorToFloat() [1/2]
FORCEINLINE double FGenericPlatformMath::FloorToFloat (double F) inline static nodiscard
Definition at line 300 of file GenericPlatformMath.h.
References FloorToDouble(), and FORCEINLINE.
FloorToFloat() [2/2]
FORCEINLINE float FGenericPlatformMath::FloorToFloat (float F) inline static nodiscard
Converts a float to the nearest less or equal integer.
Parameters
F Floating point value to convert
Returns
An integer less or equal to 'F'.
Definition at line 285 of file GenericPlatformMath.h.
References FORCEINLINE.
Referenced by Frac(), and RoundToFloat().
FloorToInt() [1/2]
FORCEINLINE int64 FGenericPlatformMath::FloorToInt (double F) inline static nodiscard
Definition at line 277 of file GenericPlatformMath.h.
References FloorToInt64(), and FORCEINLINE.
FloorToInt() [2/2]
FORCEINLINE int32 FGenericPlatformMath::FloorToInt (float F) inline static nodiscard
Definition at line 276 of file GenericPlatformMath.h.
References FloorToInt32(), and FORCEINLINE.
Referenced by FDisplayClusterShaderParameters_GenerateMips::GetRequiredNumMips().
FloorToInt32() [1/2]
FORCEINLINE int32 FGenericPlatformMath::FloorToInt32 (double F) inline static nodiscard
Definition at line 263 of file GenericPlatformMath.h.
References FORCEINLINE, and TruncToInt32().
FloorToInt32() [2/2]
FORCEINLINE int32 FGenericPlatformMath::FloorToInt32 (float F) inline static nodiscard
Converts a float to a nearest less or equal integer.
Parameters
F Floating point value to convert
Returns
An integer less or equal to 'F'.
Definition at line 257 of file GenericPlatformMath.h.
References float, FORCEINLINE, and TruncToInt32().
Referenced by FloorToInt(), RoundToInt32(), and RoundToInt32().
FloorToInt64()
FORCEINLINE int64 FGenericPlatformMath::FloorToInt64 (double F) inline static nodiscard
Definition at line 269 of file GenericPlatformMath.h.
References FORCEINLINE, and TruncToInt64().
Referenced by FloorToInt(), and RoundToInt64().
Fmod() [1/2]
FORCENOINLINE double FGenericPlatformMath::Fmod (double X, double Y) static nodiscard
References FORCENOINLINE, X, and Y.
Fmod() [2/2]
FORCENOINLINE float FGenericPlatformMath::Fmod (float X, float Y) static nodiscard
Returns the floating-point remainder of X / Y Warning: Always returns remainder toward 0, not toward the smaller multiple of Y.
So for example Fmod(2.8f, 2) gives .8f as you would expect, however, Fmod(-2.8f, 2) gives -.8f, NOT 1.2f Use Floor instead when snapping positions that can be negative to a grid
This is forced to NOT inline so that divisions by constant Y does not get optimized in to an inverse scalar multiply, which is not consistent with the intent nor with the vectorized version.
References FORCENOINLINE, X, and Y.
Referenced by RESOLVE_FLOAT_AMBIGUITY_2_ARGS().
FmodReportError() [1/2]
void FGenericPlatformMath::FmodReportError (double X, double Y) static private
References X, and Y.
FmodReportError() [2/2]
void FGenericPlatformMath::FmodReportError (float X, float Y) static private
Error reporting for Fmod.
Not inlined to avoid compilation issues and avoid all the checks and error reporting at all callsites.
References X, and Y.
Frac() [1/2]
FORCEINLINE double FGenericPlatformMath::Frac (double Value) inline static nodiscard
Definition at line 455 of file GenericPlatformMath.h.
References FloorToDouble(), FORCEINLINE, and Value.
Frac() [2/2]
FORCEINLINE float FGenericPlatformMath::Frac (float Value) inline static nodiscard
Returns the fractional part of a float.
Parameters
Value Floating point value to convert
Returns
A float between >=0 and < 1.
Definition at line 449 of file GenericPlatformMath.h.
References FloorToFloat(), FORCEINLINE, and Value.
Fractional() [1/2]
FORCEINLINE double FGenericPlatformMath::Fractional (double Value) inline static nodiscard
Definition at line 439 of file GenericPlatformMath.h.
References FORCEINLINE, TruncToDouble(), and Value.
Fractional() [2/2]
FORCEINLINE float FGenericPlatformMath::Fractional (float Value) inline static nodiscard
Returns signed fractional part of a float.
Parameters
Value Floating point value to convert
Returns
A float between >=0 and < 1 for nonnegative input. A float between >= -1 and < 0 for negative input.
Definition at line 434 of file GenericPlatformMath.h.
References FORCEINLINE, TruncToFloat(), and Value.
FRand()
FORCEINLINE float FGenericPlatformMath::FRand () inline static nodiscard
Returns a random float between 0 and 1, inclusive.
Definition at line 635 of file GenericPlatformMath.h.
References float, FORCEINLINE, and Rand().
GetMinMax() [1/2]
template<class T> constexpr FORCEINLINE void FGenericPlatformMath::GetMinMax (const T & A, const T & B, T & OutMin, T & OutMax) inline static constexpr
Sort input A & B values into OutMin & OutMax.
Definition at line 1139 of file GenericPlatformMath.h.
References A, B, and FORCEINLINE.
GetMinMax() [2/2]
template<class T> constexpr FORCEINLINE void FGenericPlatformMath::GetMinMax (T & Min, T & Max) inline static constexpr
Sort input values to be Min and Max.
Definition at line 1157 of file GenericPlatformMath.h.
References FORCEINLINE, Max(), Min(), and Swap.
GetRandSeed()
int32 FGenericPlatformMath::GetRandSeed () static nodiscard
Returns the current seed for SRand().
InvSqrt() [1/2]
FORCEINLINE double FGenericPlatformMath::InvSqrt (double F) inline static nodiscard
Definition at line 560 of file GenericPlatformMath.h.
References FORCEINLINE.
InvSqrt() [2/2]
FORCEINLINE float FGenericPlatformMath::InvSqrt (float F) inline static nodiscard
Computes a fully accurate inverse square root.
Definition at line 559 of file GenericPlatformMath.h.
References FORCEINLINE.
Referenced by InvSqrtEst(), and InvSqrtEst().
InvSqrtEst() [1/2]
FORCEINLINE double FGenericPlatformMath::InvSqrtEst (double F) inline static nodiscard
Definition at line 564 of file GenericPlatformMath.h.
References FORCEINLINE, and InvSqrt().
InvSqrtEst() [2/2]
FORCEINLINE float FGenericPlatformMath::InvSqrtEst (float F) inline static nodiscard
Computes a faster but less accurate inverse square root.
Definition at line 563 of file GenericPlatformMath.h.
References FORCEINLINE, and InvSqrt().
IsFinite() [1/2]
FORCEINLINE bool FGenericPlatformMath::IsFinite (double A) inline static nodiscard
Definition at line 586 of file GenericPlatformMath.h.
References A, BitCast(), and FORCEINLINE.
IsFinite() [2/2]
FORCEINLINE bool FGenericPlatformMath::IsFinite (float A) inline static nodiscard
Return true if value is finite (not NaN and not Infinity).
Definition at line 582 of file GenericPlatformMath.h.
References A, BitCast(), and FORCEINLINE.
IsNaN() [1/2]
FORCEINLINE bool FGenericPlatformMath::IsNaN (double A) inline static nodiscard
Definition at line 576 of file GenericPlatformMath.h.
References A, BitCast(), and FORCEINLINE.
IsNaN() [2/2]
FORCEINLINE bool FGenericPlatformMath::IsNaN (float A) inline static nodiscard
Return true if value is NaN (not a number).
Definition at line 572 of file GenericPlatformMath.h.
References A, BitCast(), and FORCEINLINE.
Referenced by TAudioBuffer< DataType >::SaturateWithNANCheck().
IsNegativeOrNegativeZero() [1/2]
FORCEINLINE bool FGenericPlatformMath::IsNegativeOrNegativeZero (double A) inline static nodiscard
Definition at line 596 of file GenericPlatformMath.h.
References A, BitCast(), and FORCEINLINE.
IsNegativeOrNegativeZero() [2/2]
FORCEINLINE bool FGenericPlatformMath::IsNegativeOrNegativeZero (float A) inline static nodiscard
Definition at line 591 of file GenericPlatformMath.h.
References A, BitCast(), and FORCEINLINE.
Referenced by UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
LoadHalf()
constexpr FORCEINLINE float FGenericPlatformMath::LoadHalf (const uint16 * Ptr) inline static nodiscard constexpr
Definition at line 34 of file GenericPlatformMath.h.
References FORCEINLINE.
Referenced by VectorLoadHalf().
Log2() [1/2]
FORCEINLINE double FGenericPlatformMath::Log2 (double Value) inline static nodiscard
Definition at line 504 of file GenericPlatformMath.h.
References FORCEINLINE, Loge(), and Value.
Log2() [2/2]
FORCEINLINE float FGenericPlatformMath::Log2 (float Value) inline static nodiscard
Definition at line 502 of file GenericPlatformMath.h.
References FORCEINLINE, Loge(), and Value.
Referenced by FDisplayClusterShaderParameters_GenerateMips::GetRequiredNumMips().
Loge() [1/2]
FORCEINLINE double FGenericPlatformMath::Loge (double Value) inline static nodiscard
Definition at line 495 of file GenericPlatformMath.h.
References FORCEINLINE, and Value.
Loge() [2/2]
FORCEINLINE float FGenericPlatformMath::Loge (float Value) inline static nodiscard
Definition at line 494 of file GenericPlatformMath.h.
References FORCEINLINE, and Value.
Referenced by UE::Color::EncodeGoProProTune(), Log2(), Log2(), LogX(), and LogX().
LogX() [1/2]
FORCEINLINE double FGenericPlatformMath::LogX (double Base, double Value) inline static nodiscard
Definition at line 498 of file GenericPlatformMath.h.
References FORCEINLINE, Loge(), and Value.
LogX() [2/2]
FORCEINLINE float FGenericPlatformMath::LogX (float Base, float Value) inline static nodiscard
Definition at line 497 of file GenericPlatformMath.h.
References FORCEINLINE, Loge(), and Value.
Referenced by UE::Color::EncodeArriAlexaV3LogC(), UE::Color::EncodeCanonLog(), UE::Color::EncodeCineon(), UE::Color::EncodePanasonicVLog(), UE::Color::EncodeREDLog(), UE::Color::EncodeREDLog3G10(), UE::Color::EncodeSLog1(), UE::Color::EncodeSLog2(), UE::Color::EncodeSLog3(), and RESOLVE_FLOAT_AMBIGUITY_2_ARGS().
Max() [1/4]
template<class T> FORCEINLINE T FGenericPlatformMath::Max (const TArray< T > & Values) inline static nodiscard
Max of Array.
Parameters
Values Array of templated type
Returns
The max value found in the array or default value if the array was empty
Definition at line 1078 of file GenericPlatformMath.h.
References FORCEINLINE, and Value.
Max() [2/4]
template<class T> FORCEINLINE T FGenericPlatformMath::Max (const TArray< T > & Values, int32 * MaxIndex) inline static
Max of Array.
Parameters
Values Array of templated type
MaxIndex Optional pointer for returning the index of the maximum element, if multiple maximum elements the first index is returned
Returns
The max value found in the array or default value if the array was empty
Definition at line 1105 of file GenericPlatformMath.h.
References FORCEINLINE, INDEX_NONE, and Value.
Max() [3/4]
template<typename T, typename... OtherTypes UE_REQUIRES> constexpr FORCEINLINE T FGenericPlatformMath::Max (T A, OtherTypes... Others) inline static nodiscard constexpr
Definition at line 971 of file GenericPlatformMath.h.
References A, FORCEINLINE, and Max().
Max() [4/4]
template<typename T> constexpr FORCEINLINE T FGenericPlatformMath::Max (T A, T B) inline static nodiscard constexpr
Returns higher value in a generic way.
Definition at line 960 of file GenericPlatformMath.h.
References A, B, and FORCEINLINE.
Referenced by UE::Color::DecodeBT1886(), UE::Color::DecodeST2084(), GetMinMax(), Max(), MIX_FLOATS_2_ARGS(), and MIX_SIGNED_INTS_2_ARGS_CONSTEXPR().
Min() [1/4]
template<class T> FORCEINLINE T FGenericPlatformMath::Min (const TArray< T > & Values) inline static nodiscard
Min of Array.
Parameters
Values Array of templated type
Returns
The min value found in the array or default value if the array was empty
Definition at line 1016 of file GenericPlatformMath.h.
References FORCEINLINE, and Value.
Min() [2/4]
template<class T> FORCEINLINE T FGenericPlatformMath::Min (const TArray< T > & Values, int32 * MinIndex) inline static
Min of Array.
Parameters
Values Array of templated type
MinIndex Optional pointer for returning the index of the minimum element, if multiple minimum elements the first index is returned
Returns
The min value found in the array or default value if the array was empty
Definition at line 1042 of file GenericPlatformMath.h.
References FORCEINLINE, INDEX_NONE, and Value.
Min() [3/4]
template<typename T, typename... OtherTypes UE_REQUIRES> constexpr FORCEINLINE T FGenericPlatformMath::Min (T A, OtherTypes... Others) inline static nodiscard constexpr
Definition at line 993 of file GenericPlatformMath.h.
References A, FORCEINLINE, and Min().
Min() [4/4]
template<typename T> constexpr FORCEINLINE T FGenericPlatformMath::Min (T A, T B) inline static nodiscard constexpr
Returns lower value in a generic way.
Definition at line 982 of file GenericPlatformMath.h.
References A, B, and FORCEINLINE.
Referenced by GetMinMax(), FDisplayClusterShaderParameters_GenerateMips::GetRequiredNumMips(), Min(), MIX_FLOATS_2_ARGS(), and MIX_SIGNED_INTS_2_ARGS_CONSTEXPR().
MIX_FLOATS_2_ARGS() [1/2]
FGenericPlatformMath::MIX_FLOATS_2_ARGS (Max)
References Max().
MIX_FLOATS_2_ARGS() [2/2]
FGenericPlatformMath::MIX_FLOATS_2_ARGS (Min)
References Min().
MIX_SIGNED_INTS_2_ARGS_CONSTEXPR() [1/2]
FGenericPlatformMath::MIX_SIGNED_INTS_2_ARGS_CONSTEXPR (Max)
References Max().
MIX_SIGNED_INTS_2_ARGS_CONSTEXPR() [2/2]
FGenericPlatformMath::MIX_SIGNED_INTS_2_ARGS_CONSTEXPR (Min)
References Min().
Modf() [1/2]
FORCEINLINE double FGenericPlatformMath::Modf (const double InValue, double * OutIntPart) inline static nodiscard
Breaks the given value into an integral and a fractional part.
Parameters
InValue Floating point value to convert
OutIntPart Floating point value that receives the integral part of the number.
Returns
The fractional part of the number.
Definition at line 477 of file GenericPlatformMath.h.
References FORCEINLINE.
Modf() [2/2]
FORCEINLINE float FGenericPlatformMath::Modf (const float InValue, float * OutIntPart) inline static nodiscard
Breaks the given value into an integral and a fractional part.
Parameters
InValue Floating point value to convert
OutIntPart Floating point value that receives the integral part of the number.
Returns
The fractional part of the number.
Definition at line 466 of file GenericPlatformMath.h.
References FORCEINLINE.
MortonCode2()
constexpr FORCEINLINE uint32 FGenericPlatformMath::MortonCode2 (uint32 x) inline static nodiscard constexpr
Spreads bits to every other.
Definition at line 841 of file GenericPlatformMath.h.
References FORCEINLINE.
MortonCode2_64()
constexpr FORCEINLINE uint64 FGenericPlatformMath::MortonCode2_64 (uint64 x) inline static nodiscard constexpr
Definition at line 851 of file GenericPlatformMath.h.
References FORCEINLINE.
MortonCode3()
constexpr FORCEINLINE uint32 FGenericPlatformMath::MortonCode3 (uint32 x) inline static nodiscard constexpr
Spreads bits to every 3rd.
Definition at line 885 of file GenericPlatformMath.h.
References FORCEINLINE.
MultiplyAndCheckForOverflow()
template<typename IntType UE_REQUIRES> FORCEINLINE bool FGenericPlatformMath::MultiplyAndCheckForOverflow (IntType A, IntType B, IntType & OutResult) inline static nodiscard
Multiplies two integers of any integer type, checking for overflow.
If there was overflow, it returns false, and OutResult may or may not be written. If there wasn't overflow, it returns true, and the result of the multiplication is written to OutResult.
Definition at line 1282 of file GenericPlatformMath.h.
References A, B, and FORCEINLINE.
Pow() [1/2]
FORCEINLINE double FGenericPlatformMath::Pow (double A, double B) inline static nodiscard
Definition at line 555 of file GenericPlatformMath.h.
References A, B, and FORCEINLINE.
Pow() [2/2]
FORCEINLINE float FGenericPlatformMath::Pow (float A, float B) inline static nodiscard
Definition at line 554 of file GenericPlatformMath.h.
References A, B, and FORCEINLINE.
Referenced by UE::Color::DecodeArriAlexaV3LogC(), UE::Color::DecodeBT1886(), UE::Color::DecodeCanonLog(), UE::Color::DecodeCineon(), UE::Color::DecodeGamma22(), UE::Color::DecodeGamma26(), UE::Color::DecodeGoProProTune(), UE::Color::DecodePanasonicVLog(), UE::Color::DecodeREDLog(), UE::Color::DecodeREDLog3G10(), UE::Color::DecodeSLog1(), UE::Color::DecodeSLog2(), UE::Color::DecodeSLog3(), UE::Color::DecodeSRGB(), UE::Color::DecodeST2084(), UE::Color::EncodeBT1886(), UE::Color::EncodeCineon(), UE::Color::EncodeGamma22(), UE::Color::EncodeGamma26(), UE::Color::EncodeREDLog(), UE::Color::EncodeSRGB(), UE::Color::EncodeST2084(), and RESOLVE_FLOAT_AMBIGUITY_2_ARGS().
Rand()
FORCEINLINE int32 FGenericPlatformMath::Rand () inline static nodiscard
Returns a random integer between 0 and RAND_MAX, inclusive.
Definition at line 626 of file GenericPlatformMath.h.
References FORCEINLINE.
Referenced by FRand().
Rand32()
FORCEINLINE int32 FGenericPlatformMath::Rand32 () inline static nodiscard
Returns a random integer between 0 and MAX_int32, inclusive.
RAND_MAX may only be 15 bits, so compose from multiple calls.
Definition at line 629 of file GenericPlatformMath.h.
References FORCEINLINE.
RandInit()
FORCEINLINE void FGenericPlatformMath::RandInit (int32 Seed) inline static
Seeds global random number functions Rand() and FRand()
Definition at line 632 of file GenericPlatformMath.h.
References FORCEINLINE, and Seed.
RESOLVE_FLOAT_AMBIGUITY_2_ARGS() [1/5]
FGenericPlatformMath::RESOLVE_FLOAT_AMBIGUITY_2_ARGS (Atan2)
References Atan2().
RESOLVE_FLOAT_AMBIGUITY_2_ARGS() [2/5]
FGenericPlatformMath::RESOLVE_FLOAT_AMBIGUITY_2_ARGS (CopySign)
References CopySign().
RESOLVE_FLOAT_AMBIGUITY_2_ARGS() [3/5]
FGenericPlatformMath::RESOLVE_FLOAT_AMBIGUITY_2_ARGS (Fmod)
References Fmod().
RESOLVE_FLOAT_AMBIGUITY_2_ARGS() [4/5]
FGenericPlatformMath::RESOLVE_FLOAT_AMBIGUITY_2_ARGS (LogX)
References LogX().
RESOLVE_FLOAT_AMBIGUITY_2_ARGS() [5/5]
FGenericPlatformMath::RESOLVE_FLOAT_AMBIGUITY_2_ARGS (Pow)
References Pow().
ReverseMortonCode2()
constexpr FORCEINLINE uint32 FGenericPlatformMath::ReverseMortonCode2 (uint32 x) inline static nodiscard constexpr
Reverses MortonCode2.
Compacts every other bit to the right.
Definition at line 863 of file GenericPlatformMath.h.
References FORCEINLINE.
ReverseMortonCode2_64()
constexpr FORCEINLINE uint64 FGenericPlatformMath::ReverseMortonCode2_64 (uint64 x) inline static nodiscard constexpr
Definition at line 873 of file GenericPlatformMath.h.
References FORCEINLINE.
ReverseMortonCode3()
constexpr FORCEINLINE uint32 FGenericPlatformMath::ReverseMortonCode3 (uint32 x) inline static nodiscard constexpr
Reverses MortonCode3.
Compacts every 3rd bit to the right.
Definition at line 896 of file GenericPlatformMath.h.
References FORCEINLINE.
RoundToDouble()
FORCEINLINE double FGenericPlatformMath::RoundToDouble (double F) inline static nodiscard
Converts a double to the nearest integer.
Rounds up when the fraction is .5
Parameters
F Floating point value to convert
Returns
The nearest integer to 'F'.
Definition at line 341 of file GenericPlatformMath.h.
References FloorToDouble(), and FORCEINLINE.
Referenced by RoundToFloat().
RoundToFloat() [1/2]
FORCEINLINE double FGenericPlatformMath::RoundToFloat (double F) inline static nodiscard
Definition at line 346 of file GenericPlatformMath.h.
References FORCEINLINE, and RoundToDouble().
RoundToFloat() [2/2]
FORCEINLINE float FGenericPlatformMath::RoundToFloat (float F) inline static nodiscard
Converts a float to the nearest integer.
Rounds up when the fraction is .5
Parameters
F Floating point value to convert
Returns
The nearest integer to 'F'.
Definition at line 331 of file GenericPlatformMath.h.
References FloorToFloat(), and FORCEINLINE.
RoundToInt() [1/2]
FORCEINLINE int64 FGenericPlatformMath::RoundToInt (double F) inline static nodiscard
Definition at line 324 of file GenericPlatformMath.h.
References FORCEINLINE, and RoundToInt64().
RoundToInt() [2/2]
FORCEINLINE int32 FGenericPlatformMath::RoundToInt (float F) inline static nodiscard
Definition at line 323 of file GenericPlatformMath.h.
References FORCEINLINE, and RoundToInt32().
RoundToInt32() [1/2]
FORCEINLINE int32 FGenericPlatformMath::RoundToInt32 (double F) inline static nodiscard
Definition at line 314 of file GenericPlatformMath.h.
References FloorToInt32(), and FORCEINLINE.
RoundToInt32() [2/2]
FORCEINLINE int32 FGenericPlatformMath::RoundToInt32 (float F) inline static nodiscard
Converts a float to the nearest integer.
Rounds up when the fraction is .5
Parameters
F Floating point value to convert
Returns
The nearest integer to 'F'.
Definition at line 310 of file GenericPlatformMath.h.
References FloorToInt32(), and FORCEINLINE.
Referenced by RoundToInt().
RoundToInt64()
FORCEINLINE int64 FGenericPlatformMath::RoundToInt64 (double F) inline static nodiscard
Definition at line 318 of file GenericPlatformMath.h.
References FloorToInt64(), and FORCEINLINE.
Referenced by RoundToInt().
RoundToNearestTiesToEven()
int64 FGenericPlatformMath::RoundToNearestTiesToEven (double F) inline static nodiscard
Converts a double to nearest int64 with ties rounding to nearest even May incur a performance penalty.
Asserts on platforms that do not support this mode.
Parameters
F Double precision floating point value to convert
Returns
The 64-bit integer closest to 'F', with ties going to the nearest even number
Definition at line 409 of file GenericPlatformMath.h.
References ensureAlwaysMsgf, and TEXT.
RoundUpToPowerOfTwo()
constexpr FORCEINLINE uint32 FGenericPlatformMath::RoundUpToPowerOfTwo (uint32 Arg) inline static nodiscard constexpr
Returns
Rounds the given number up to the next highest power of two.
Definition at line 830 of file GenericPlatformMath.h.
References CeilLogTwo(), and FORCEINLINE.
RoundUpToPowerOfTwo64()
constexpr FORCEINLINE uint64 FGenericPlatformMath::RoundUpToPowerOfTwo64 (uint64 V) inline static nodiscard constexpr
Definition at line 835 of file GenericPlatformMath.h.
References CeilLogTwo64(), and FORCEINLINE.
Sign()
template<class T> constexpr FORCEINLINE T FGenericPlatformMath::Sign (const T A) inline static nodiscard constexpr
Returns 1, 0, or -1 depending on relation of T to 0.
Definition at line 953 of file GenericPlatformMath.h.
References A, and FORCEINLINE.
Referenced by UE::Color::DecodeREDLog3G10(), and UE::Color::EncodeREDLog3G10().
Sin() [1/2]
FORCEINLINE double FGenericPlatformMath::Sin (double Value) inline static nodiscard
Definition at line 521 of file GenericPlatformMath.h.
References FORCEINLINE, and Value.
Sin() [2/2]
FORCEINLINE float FGenericPlatformMath::Sin (float Value) inline static nodiscard
Definition at line 520 of file GenericPlatformMath.h.
References FORCEINLINE, and Value.
Sinh() [1/2]
FORCEINLINE double FGenericPlatformMath::Sinh (double Value) inline static nodiscard
Definition at line 527 of file GenericPlatformMath.h.
References FORCEINLINE, and Value.
Sinh() [2/2]
FORCEINLINE float FGenericPlatformMath::Sinh (float Value) inline static nodiscard
Definition at line 526 of file GenericPlatformMath.h.
References FORCEINLINE, and Value.
Sqrt() [1/2]
FORCEINLINE double FGenericPlatformMath::Sqrt (double Value) inline static nodiscard
Definition at line 552 of file GenericPlatformMath.h.
References FORCEINLINE, and Value.
Sqrt() [2/2]
FORCEINLINE float FGenericPlatformMath::Sqrt (float Value) inline static nodiscard
Definition at line 551 of file GenericPlatformMath.h.
References FORCEINLINE, and Value.
SRand()
float FGenericPlatformMath::SRand () static nodiscard
Returns a seeded random float in the range [0,1), using the seed from SRandInit().
SRandInit()
void FGenericPlatformMath::SRandInit (int32 Seed) static
Seeds future calls to SRand()
References Seed.
StoreHalf()
constexpr FORCEINLINE void FGenericPlatformMath::StoreHalf (uint16 * Ptr, float Value) inline static constexpr
Definition at line 68 of file GenericPlatformMath.h.
References FORCEINLINE, and Value.
Referenced by VectorStoreHalf().
SubtractAndCheckForOverflow()
template<typename IntType UE_REQUIRES> FORCEINLINE bool FGenericPlatformMath::SubtractAndCheckForOverflow (IntType A, IntType B, IntType & OutResult) inline static nodiscard
Subtracts two integers of any integer type, checking for overflow.
If there was overflow, it returns false, and OutResult may or may not be written. If there wasn't overflow, it returns true, and the result of the subtraction is written to OutResult.
Definition at line 1238 of file GenericPlatformMath.h.
References A, B, and FORCEINLINE.
Tan() [1/2]
FORCEINLINE double FGenericPlatformMath::Tan (double Value) inline static nodiscard
Definition at line 539 of file GenericPlatformMath.h.
References FORCEINLINE, and Value.
Tan() [2/2]
FORCEINLINE float FGenericPlatformMath::Tan (float Value) inline static nodiscard
Definition at line 538 of file GenericPlatformMath.h.
References FORCEINLINE, and Value.
Tanh() [1/2]
FORCEINLINE double FGenericPlatformMath::Tanh (double Value) inline static nodiscard
Definition at line 545 of file GenericPlatformMath.h.
References FORCEINLINE, and Value.
Tanh() [2/2]
FORCEINLINE float FGenericPlatformMath::Tanh (float Value) inline static nodiscard
Definition at line 544 of file GenericPlatformMath.h.
References FORCEINLINE, and Value.
TruncToDouble()
FORCEINLINE double FGenericPlatformMath::TruncToDouble (double F) inline static nodiscard
Converts a double to an integer value with truncation towards zero.
Parameters
F Floating point value to convert
Returns
Truncated integer value.
Definition at line 242 of file GenericPlatformMath.h.
References FORCEINLINE.
Referenced by Fractional(), and TruncToFloat().
TruncToFloat() [1/2]
FORCEINLINE double FGenericPlatformMath::TruncToFloat (double F) inline static nodiscard
Definition at line 247 of file GenericPlatformMath.h.
References FORCEINLINE, and TruncToDouble().
TruncToFloat() [2/2]
FORCEINLINE float FGenericPlatformMath::TruncToFloat (float F) inline static nodiscard
Converts a float to an integer value with truncation towards zero.
Parameters
F Floating point value to convert
Returns
Truncated integer value.
Definition at line 232 of file GenericPlatformMath.h.
References FORCEINLINE.
Referenced by Fractional().
TruncToInt() [1/2]
constexpr FORCEINLINE int64 FGenericPlatformMath::TruncToInt (double F) inline static nodiscard constexpr
Definition at line 225 of file GenericPlatformMath.h.
References FORCEINLINE, and TruncToInt64().
TruncToInt() [2/2]
constexpr FORCEINLINE int32 FGenericPlatformMath::TruncToInt (float F) inline static nodiscard constexpr
Definition at line 224 of file GenericPlatformMath.h.
References FORCEINLINE, and TruncToInt32().
TruncToInt32() [1/2]
constexpr FORCEINLINE int32 FGenericPlatformMath::TruncToInt32 (double F) inline static nodiscard constexpr
Definition at line 215 of file GenericPlatformMath.h.
References FORCEINLINE.
TruncToInt32() [2/2]
constexpr FORCEINLINE int32 FGenericPlatformMath::TruncToInt32 (float F) inline static nodiscard constexpr
Converts a float to an integer with truncation towards zero.
Parameters
F Floating point value to convert
Returns
Truncated integer.
Definition at line 211 of file GenericPlatformMath.h.
References FORCEINLINE.
Referenced by CeilToInt32(), CeilToInt32(), FloorToInt32(), FloorToInt32(), and TruncToInt().
TruncToInt64()
constexpr FORCEINLINE int64 FGenericPlatformMath::TruncToInt64 (double F) inline static nodiscard constexpr
Definition at line 219 of file GenericPlatformMath.h.
References FORCEINLINE.
Referenced by CeilToInt64(), FloorToInt64(), and TruncToInt().
UE_DEPRECATED() [1/4]
FGenericPlatformMath::UE_DEPRECATED (5. 1) inline nodiscard
Definition at line 619 of file GenericPlatformMath.h.
References A, FORCEINLINE, and IsNegativeOrNegativeZero().
UE_DEPRECATED() [2/4]
FGenericPlatformMath::UE_DEPRECATED (5. 1) inline nodiscard
Definition at line 613 of file GenericPlatformMath.h.
References A, FORCEINLINE, and IsNegativeOrNegativeZero().
UE_DEPRECATED() [3/4]
FGenericPlatformMath::UE_DEPRECATED (5. 1) inline nodiscard
Definition at line 607 of file GenericPlatformMath.h.
References A, FORCEINLINE, and IsNegativeOrNegativeZero().
UE_DEPRECATED() [4/4]
FGenericPlatformMath::UE_DEPRECATED (5. 1) inline nodiscard
Definition at line 601 of file GenericPlatformMath.h.
References A, FORCEINLINE, and IsNegativeOrNegativeZero().
VectorLoadHalf()
constexpr FORCEINLINE void FGenericPlatformMath::VectorLoadHalf (float *RESTRICT Dst, const uint16 *RESTRICT Src) inline static constexpr
Definition at line 125 of file GenericPlatformMath.h.
References FORCEINLINE, LoadHalf(), and RESTRICT.
Referenced by WideVectorLoadHalf().
VectorStoreHalf()
constexpr FORCEINLINE void FGenericPlatformMath::VectorStoreHalf (uint16 *RESTRICT Dst, const float *RESTRICT Src) inline static constexpr
Definition at line 133 of file GenericPlatformMath.h.
References FORCEINLINE, RESTRICT, and StoreHalf().
Referenced by WideVectorStoreHalf().
WideVectorLoadHalf()
constexpr FORCEINLINE void FGenericPlatformMath::WideVectorLoadHalf (float *RESTRICT Dst, const uint16 *RESTRICT Src) inline static constexpr
Definition at line 141 of file GenericPlatformMath.h.
References FORCEINLINE, RESTRICT, and VectorLoadHalf().
WideVectorStoreHalf()
constexpr FORCEINLINE void FGenericPlatformMath::WideVectorStoreHalf (uint16 *RESTRICT Dst, const float *RESTRICT Src) inline static constexpr
Definition at line 147 of file GenericPlatformMath.h.
References FORCEINLINE, RESTRICT, and VectorStoreHalf().
The documentation for this struct was generated from the following file:
Runtime/Core/Public/GenericPlatform/GenericPlatformMath.h