Unreal Engine 5.6 C++ API: FSlateCachedElementData Struct Reference
FSlateCachedElementData Struct Reference
Top level class responsible for cached elements within a particular invalidation root.
#include "DrawElements.h"
Public Member Functions
FSlateCachedElementsHandle AddCache (const SWidget *Widget)
Create a new CachedElementList, occurs when adding a cached element whose top level draw widget is not already part of some cache.
template<EElementType ElementType>
TSlateDrawElement< ElementType > & AddCachedElement (FSlateCachedElementsHandle &CacheHandle, const FSlateClippingManager &ParentClipManager, const SWidget *CurrentWidget)
FSlateRenderBatch & AddCachedRenderBatch (FSlateRenderBatch &&NewBatch, int32 &OutIndex)
void AddReferencedObjects (FReferenceCollector &Collector)
void CleanupUnusedClipStates ()
void Empty ()
Reset all cached data, except num elements, call EmptyCachedNumElements for that.
FSlateCachedClipState & FindOrAddCachedClipState (const FSlateClippingState *RefClipState)
const TSparseArray< FSlateRenderBatch > & GetCachedBatches () const
const TArray< TSharedPtr< FSlateCachedElementList > > & GetCachedElementLists () const
TArrayView< FSlateCachedElementList *const > GetListsWithNewData () const
void RemoveCachedRenderBatches (const TArray< int32 > &CachedRenderBatchIndices)
void ValidateWidgetOwner (TSharedPtr< FSlateCachedElementList > List, const SWidget *CurrentWidget)
Static Public Member Functions
static const FSlateClippingState * GetClipStateFromParent (const FSlateClippingManager &ParentClipManager)
Private Member Functions
void RemoveList (FSlateCachedElementsHandle &CacheHandle)
Removes a cache node completely from the cache.
Private Attributes
TSparseArray< FSlateRenderBatch > CachedBatches
List of cached batches to submit for drawing.
TArray< FSlateCachedClipState > CachedClipStates
List of clip states used later when rendering.
TArray< TSharedPtr< FSlateCachedElementList > > CachedElementLists
List of cached element lists used to redraw when no invalidation occurs, each list corresponds to a particular widget.
TArray< FSlateCachedElementList *, TInlineAllocator< 50 > > ListsWithNewData
List of pointers to instances of the element lists above which have new data or have been invalidated.
Friends
struct FSlateCachedElementsHandle
class FSlateElementBatcher
Detailed Description
Top level class responsible for cached elements within a particular invalidation root.
Equivalent to the plain FSlateBatchData in that it manages multiple renderbatches, element lists (Per widget), & new element lists (Per invalidated widgets).
Note: Just as each window may have multiple invalidation roots, each window element list may have multiple 'FSlateCachedElementData' for each root
Definition at line 139 of file DrawElements.h.
Member Function Documentation
AddCache()
FSlateCachedElementsHandle FSlateCachedElementData::AddCache (const SWidget * Widget)
Create a new CachedElementList, occurs when adding a cached element whose top level draw widget is not already part of some cache.
References FSlateCachedElementsHandle.
Referenced by FSlateWindowElementList::AddCachedElement().
AddCachedElement()
template<EElementType ElementType> TSlateDrawElement< ElementType > & FSlateCachedElementData::AddCachedElement (FSlateCachedElementsHandle & CacheHandle, const FSlateClippingManager & ParentClipManager, const SWidget * CurrentWidget) inline
Definition at line 155 of file DrawElements.h.
References FSlateCachedClipState::ClippingState, Container, FindOrAddCachedClipState(), FSlateCachedElementsHandle, TSharedPtr< ObjectType, InMode >::Get(), TSharedRef< ObjectType, InMode >::Get(), GetClipStateFromParent(), ListsWithNewData, TWeakPtr< ObjectType, InMode >::Pin(), FSlateCachedElementsHandle::Ptr, and ValidateWidgetOwner().
Referenced by FSlateWindowElementList::AddCachedElement().
AddCachedRenderBatch()
FSlateRenderBatch & FSlateCachedElementData::AddCachedRenderBatch (FSlateRenderBatch && NewBatch, int32 & OutIndex)
AddReferencedObjects()
void FSlateCachedElementData::AddReferencedObjects (FReferenceCollector & Collector)
CleanupUnusedClipStates()
void FSlateCachedElementData::CleanupUnusedClipStates ()
Empty()
void FSlateCachedElementData::Empty ()
Reset all cached data, except num elements, call EmptyCachedNumElements for that.
FindOrAddCachedClipState()
FSlateCachedClipState & FSlateCachedElementData::FindOrAddCachedClipState (const FSlateClippingState * RefClipState)
Referenced by AddCachedElement().
GetCachedBatches()
const TSparseArray< FSlateRenderBatch > & FSlateCachedElementData::GetCachedBatches () const inline
Definition at line 191 of file DrawElements.h.
References CachedBatches.
GetCachedElementLists()
const TArray< TSharedPtr< FSlateCachedElementList > > & FSlateCachedElementData::GetCachedElementLists () const inline
Definition at line 192 of file DrawElements.h.
References CachedElementLists.
GetClipStateFromParent()
const FSlateClippingState * FSlateCachedElementData::GetClipStateFromParent (const FSlateClippingManager & ParentClipManager) static
Referenced by AddCachedElement().
GetListsWithNewData()
TArrayView< FSlateCachedElementList *const > FSlateCachedElementData::GetListsWithNewData () const inline
Definition at line 196 of file DrawElements.h.
References ListsWithNewData, and MakeArrayView().
RemoveCachedRenderBatches()
void FSlateCachedElementData::RemoveCachedRenderBatches (const TArray< int32 > & CachedRenderBatchIndices)
RemoveList()
void FSlateCachedElementData::RemoveList (FSlateCachedElementsHandle & CacheHandle) private
Removes a cache node completely from the cache.
References FSlateCachedElementsHandle.
ValidateWidgetOwner()
void FSlateCachedElementData::ValidateWidgetOwner (TSharedPtr< FSlateCachedElementList > List, const SWidget * CurrentWidget)
Referenced by AddCachedElement().
Friends And Related Symbol Documentation
FSlateCachedElementsHandle
friend struct FSlateCachedElementsHandle friend
Definition at line 142 of file DrawElements.h.
References FSlateCachedElementsHandle.
Referenced by AddCache(), AddCachedElement(), FSlateCachedElementsHandle, and RemoveList().
FSlateElementBatcher
friend class FSlateElementBatcher friend
Definition at line 141 of file DrawElements.h.
References FSlateElementBatcher.
Referenced by FSlateElementBatcher.
Field Documentation
CachedBatches
TSparseArray<FSlateRenderBatch> FSlateCachedElementData::CachedBatches private
List of cached batches to submit for drawing.
Definition at line 204 of file DrawElements.h.
Referenced by GetCachedBatches().
CachedClipStates
TArray<FSlateCachedClipState> FSlateCachedElementData::CachedClipStates private
List of clip states used later when rendering.
Definition at line 213 of file DrawElements.h.
CachedElementLists
TArray<TSharedPtr<FSlateCachedElementList> > FSlateCachedElementData::CachedElementLists private
List of cached element lists used to redraw when no invalidation occurs, each list corresponds to a particular widget.
See 'FSlateCachedElementsHandle'
Definition at line 207 of file DrawElements.h.
Referenced by GetCachedElementLists().
ListsWithNewData
TArray<FSlateCachedElementList*, TInlineAllocator<50> > FSlateCachedElementData::ListsWithNewData private
List of pointers to instances of the element lists above which have new data or have been invalidated.
Definition at line 210 of file DrawElements.h.
Referenced by AddCachedElement(), and GetListsWithNewData().
The documentation for this struct was generated from the following file:
Runtime/SlateCore/Public/Rendering/DrawElements.h