Unreal Engine 5.6 C++ API: Metasound::FLiteral Struct Reference
Metasound::FLiteral Struct Reference
FLiteral represents a constant value in a Metasound graph and is primarily used to invoke the correct constructor of a Metasound data type.
#include "MetasoundLiteral.h"
Data Structures
struct FInvalid
struct FNone
struct TIsSupportedLiteralType
struct TIsSupportedLiteralTypeHelper
struct TIsSupportedLiteralTypeHelper< U, TVariant< T, Ts... > >
Public Types
using FVariantType
Public Member Functions
FLiteral ()
Construct a literal param with no arguments.
template<typename ArgType, typename std::enable_if< TIsSupportedLiteralType< ArgType >::Value, int >::type = 0>
FLiteral (ArgType &&Arg)
Construct a literal param with a single argument.
METASOUNDGRAPHCORE_API ELiteralType GetType () const
METASOUNDGRAPHCORE_API bool IsValid () const
template<typename ArgType>
void Set (ArgType &&Arg)
Static Public Member Functions
static METASOUNDGRAPHCORE_API FLiteral CreateInvalid ()
static METASOUNDGRAPHCORE_API FLiteral GetDefaultForType (ELiteralType InType)
Data Fields
FVariantType Value
Detailed Description
FLiteral represents a constant value in a Metasound graph and is primarily used to invoke the correct constructor of a Metasound data type.
To be constructed using a FLiteral, the Metasound data type must support a constructor which accepts one of the types supported by a FLiteral. The Metasound data type may optionally accept a const FOperatorSettings& in addition.
Example: // Somewhere before DECLARE_METASOUND_DATA_REFERENCE_TYPES(FAudioBuffer...), ParseFrom<FAudioBuffer>(int32) is defined // which means this data type can be created from an integer. Metasound::FAudioBuffer ::Metasound::ParseFrom<Metasound::FAudioBuffer>(int32 InNumFrames, const ::Metasound::FOperatorSettings&) { return Metasound::FAudioBuffer(InNumFrames); }
//... // In the frontend, we know that int and pass it to somewhere in MetasoundGraphCore... FLiteral InitParam(512);
//... // In the backend, we can safely construct an FAudioBuffer. if(InitParam.IsCompatibleWithType<Metasound::FAudioBuffer>()) { Metasound::FAudioBuffer AudioBuffer = InitParam.ParseTo<Metasound::FAudioBuffer>(); //... }
Definition at line 70 of file MetasoundLiteral.h.
Member Typedef Documentation
FVariantType
using Metasound::FLiteral::FVariantType
Initial value:
 TVariant<
            FNone, bool, int32, float, FString, TSharedPtr<Audio::IProxyData>,
            TArray<FNone>, TArray<bool>, TArray<int32>, TArray<float>, TArray<FString>, TArray<TSharedPtr<Audio::IProxyData>>,
            FInvalid
        >
Definition at line 85 of file MetasoundLiteral.h.
Constructor & Destructor Documentation
FLiteral() [1/2]
template<typename ArgType, typename std::enable_if< TIsSupportedLiteralType< ArgType >::Value, int >::type = 0> Metasound::FLiteral::FLiteral (ArgType && Arg) inline
Construct a literal param with a single argument.
Definition at line 97 of file MetasoundLiteral.h.
References Forward(), and Value.
Referenced by CreateInvalid(), and GetDefaultForType().
FLiteral() [2/2]
Metasound::FLiteral::FLiteral () inline
Construct a literal param with no arguments.
Definition at line 106 of file MetasoundLiteral.h.
References Value.
Member Function Documentation
CreateInvalid()
METASOUNDGRAPHCORE_API FLiteral Metasound::FLiteral::CreateInvalid () static
References FLiteral(), and UE_API.
Referenced by Metasound::FDataReferenceCollection::GetDataReadReferenceOrConstructWithVertexDefault(), Metasound::FInputVertexInterfaceData::GetOrCreateDefaultDataReadReference(), and Metasound::FInputVertexInterfaceData::GetOrCreateDefaultDataWriteReference().
GetDefaultForType()
METASOUNDGRAPHCORE_API FLiteral Metasound::FLiteral::GetDefaultForType (ELiteralType InType) static
References FLiteral(), and UE_API.
GetType()
METASOUNDGRAPHCORE_API ELiteralType Metasound::FLiteral::GetType () const
References UE_API.
Referenced by Metasound::TDataLiteralFactory< DataType, CreatorType >::CreateExplicitArgs(), and Metasound::TLiteralTraits< DataType >::IsParsable().
IsValid()
METASOUNDGRAPHCORE_API bool Metasound::FLiteral::IsValid () const
References UE_API.
Set()
template<typename ArgType> void Metasound::FLiteral::Set (ArgType && Arg) inline
Definition at line 125 of file MetasoundLiteral.h.
References Forward(), and Value.
Field Documentation
Value
FVariantType Metasound::FLiteral::Value
Definition at line 114 of file MetasoundLiteral.h.
Referenced by FLiteral(), FLiteral(), Metasound::TDataLiteralFactory< DataType, CreatorType >::CreateExplicitArgs(), and Set().
The documentation for this struct was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/Metasound/Source/MetasoundGraphCore/Public/MetasoundLiteral.h