Unreal Engine 5.6 C++ API: FAsyncAddPrimitiveQueue Struct Reference
FAsyncAddPrimitiveQueue Struct Reference
#include "AsyncRegisterLevelContext.h"
Data Structures
struct FAddPrimitivesTask
Private Types
using FPrimitiveBatch = TArray<TWeakObjectPtr<UPrimitiveComponent>, FConcurrentLinearArrayAllocator>
Private Member Functions
FAsyncAddPrimitiveQueue (FAsyncRegisterLevelContext &InContext)
~FAsyncAddPrimitiveQueue ()
void AddPrimitive (UPrimitiveComponent *InComponent)
void Flush ()
bool HasRemainingWork () const
bool IsRunningAsync () const
void Push (FPrimitiveBatch &InAddPrimitives)
bool Tick ()
void WaitForAsyncTask ()
Private Attributes
TArray< FPrimitiveBatch > AddPrimitivesArray
FAddPrimitivesTask AsyncTask
FAsyncRegisterLevelContext & Context
friend FAsyncRegisterLevelContext
FPrimitiveBatch NextBatch
Detailed Description
Definition at line 14 of file AsyncRegisterLevelContext.h.
Member Typedef Documentation
FPrimitiveBatch
using FAsyncAddPrimitiveQueue::FPrimitiveBatch = TArray<TWeakObjectPtr<UPrimitiveComponent>, FConcurrentLinearArrayAllocator> private
Definition at line 17 of file AsyncRegisterLevelContext.h.
Constructor & Destructor Documentation
FAsyncAddPrimitiveQueue()
FAsyncAddPrimitiveQueue::FAsyncAddPrimitiveQueue (FAsyncRegisterLevelContext & InContext) private
Definition at line 128 of file AsyncRegisterLevelContext.cpp.
References Context, and FAsyncRegisterLevelContext.
~FAsyncAddPrimitiveQueue()
FAsyncAddPrimitiveQueue::~FAsyncAddPrimitiveQueue () private
Definition at line 133 of file AsyncRegisterLevelContext.cpp.
References check, and HasRemainingWork().
Member Function Documentation
AddPrimitive()
void FAsyncAddPrimitiveQueue::AddPrimitive (UPrimitiveComponent * InComponent) private
Definition at line 245 of file AsyncRegisterLevelContext.cpp.
References checkSlow, Flush(), NextBatch, and LevelStreaming::AsyncRegisterLevelContext::PrimitiveBatchSize.
Flush()
void FAsyncAddPrimitiveQueue::Flush () private
Definition at line 255 of file AsyncRegisterLevelContext.cpp.
References check, NextBatch, and Push().
Referenced by AddPrimitive().
HasRemainingWork()
bool FAsyncAddPrimitiveQueue::HasRemainingWork () const private
Definition at line 138 of file AsyncRegisterLevelContext.cpp.
References AddPrimitivesArray, AsyncTask, and NextBatch.
Referenced by ~FAsyncAddPrimitiveQueue(), and Tick().
IsRunningAsync()
bool FAsyncAddPrimitiveQueue::IsRunningAsync () const private
Definition at line 143 of file AsyncRegisterLevelContext.cpp.
References AsyncTask.
Referenced by Tick().
Push()
void FAsyncAddPrimitiveQueue::Push (FPrimitiveBatch & InAddPrimitives) private
Definition at line 264 of file AsyncRegisterLevelContext.cpp.
References AddPrimitivesArray, check, TArray< InElementType, InAllocatorType >::IsEmpty(), and MoveTemp().
Referenced by Flush().
Tick()
bool FAsyncAddPrimitiveQueue::Tick () private
Definition at line 158 of file AsyncRegisterLevelContext.cpp.
References AddPrimitivesArray, AsyncTask, FApp::CanEverRender(), Component, Context, Count, TArray< InElementType, InAllocatorType >::Emplace(), TArray< InElementType, InAllocatorType >::Emplace_GetRef(), FAsyncAddPrimitiveQueue::FAddPrimitivesTask::Execute(), GetData(), GLevelStreamingAddPrimitiveGranularity, HasRemainingWork(), TArray< InElementType, InAllocatorType >::IsEmpty(), IsRunningAsync(), MAX_int32, MoveTemp(), No, Num, QUICK_SCOPE_CYCLE_COUNTER, TArray< InElementType, InAllocatorType >::RemoveAtSwap(), Scene, and WaitForAsyncTask().
WaitForAsyncTask()
void FAsyncAddPrimitiveQueue::WaitForAsyncTask () private
Definition at line 148 of file AsyncRegisterLevelContext.cpp.
References AsyncTask, and QUICK_SCOPE_CYCLE_COUNTER.
Referenced by Tick().
Field Documentation
AddPrimitivesArray
TArray<FPrimitiveBatch> FAsyncAddPrimitiveQueue::AddPrimitivesArray private
Definition at line 45 of file AsyncRegisterLevelContext.h.
Referenced by HasRemainingWork(), Push(), and Tick().
AsyncTask
FAddPrimitivesTask FAsyncAddPrimitiveQueue::AsyncTask private
Definition at line 46 of file AsyncRegisterLevelContext.h.
Referenced by HasRemainingWork(), IsRunningAsync(), Tick(), and WaitForAsyncTask().
Context
FAsyncRegisterLevelContext& FAsyncAddPrimitiveQueue::Context private
Definition at line 43 of file AsyncRegisterLevelContext.h.
Referenced by FAsyncAddPrimitiveQueue(), and Tick().
FAsyncRegisterLevelContext
friend FAsyncAddPrimitiveQueue::FAsyncRegisterLevelContext private
Definition at line 47 of file AsyncRegisterLevelContext.h.
Referenced by FAsyncAddPrimitiveQueue().
NextBatch
FPrimitiveBatch FAsyncAddPrimitiveQueue::NextBatch private
Definition at line 44 of file AsyncRegisterLevelContext.h.
Referenced by AddPrimitive(), Flush(), and HasRemainingWork().
The documentation for this struct was generated from the following files:
Runtime/Engine/Internal/Streaming/AsyncRegisterLevelContext.h
Runtime/Engine/Internal/Streaming/AsyncRegisterLevelContext.cpp