Unreal Engine 5.6 C++ API: FAsyncRegisterLevelContext Struct Reference
FAsyncRegisterLevelContext Struct Reference
#include "AsyncRegisterLevelContext.h"
Public Member Functions
FAsyncRegisterLevelContext (ULevel *InLevel)
void AddPrimitive (UPrimitiveComponent *InComponent)
void AddSendRenderDynamicData (UPrimitiveComponent *InComponent)
bool GetIncrementalRegisterComponentsDone () const
bool HasRemainingWork () const
bool IsRunningAsync () const
void SetCanLaunchNewTasks (bool bValue)
void SetIncrementalRegisterComponentsDone (bool bValue)
bool Tick ()
void WaitForAsyncTasks ()
Static Public Member Functions
static TUniquePtr< FAsyncRegisterLevelContext > CreateInstance (ULevel *InLevel)
Private Member Functions
void Flush ()
Private Attributes
FAsyncAddPrimitiveQueue AsyncAddPrimitiveQueue
bool bCanLaunchNewTasks
bool bIncrementalRegisterComponentsDone
friend FAsyncAddPrimitiveQueue
friend FSendRenderDynamicDataPrimitivesQueue
ULevel * Level
FSendRenderDynamicDataPrimitivesQueue SendRenderDynamicDataPrimitivesQueue
Detailed Description
Definition at line 70 of file AsyncRegisterLevelContext.h.
Constructor & Destructor Documentation
FAsyncRegisterLevelContext()
FAsyncRegisterLevelContext::FAsyncRegisterLevelContext (ULevel * InLevel)
Definition at line 52 of file AsyncRegisterLevelContext.cpp.
References AsyncAddPrimitiveQueue, bCanLaunchNewTasks, bIncrementalRegisterComponentsDone, Level, and SendRenderDynamicDataPrimitivesQueue.
Member Function Documentation
AddPrimitive()
void FAsyncRegisterLevelContext::AddPrimitive (UPrimitiveComponent * InComponent)
Definition at line 61 of file AsyncRegisterLevelContext.cpp.
References AsyncAddPrimitiveQueue, bIncrementalRegisterComponentsDone, check, and Tick().
AddSendRenderDynamicData()
void FAsyncRegisterLevelContext::AddSendRenderDynamicData (UPrimitiveComponent * InComponent)
Definition at line 68 of file AsyncRegisterLevelContext.cpp.
References bIncrementalRegisterComponentsDone, check, SendRenderDynamicDataPrimitivesQueue, and Tick().
CreateInstance()
TUniquePtr< FAsyncRegisterLevelContext > FAsyncRegisterLevelContext::CreateInstance (ULevel * InLevel) static
Definition at line 34 of file AsyncRegisterLevelContext.cpp.
References LevelStreaming::AsyncRegisterLevelContext::bEnabled, FStaticMeshCompilingManager::Get(), FStaticMeshCompilingManager::IsAsyncStaticMeshCompilationEnabled(), MakeUnique(), and FApp::ShouldUseThreadingForPerformance().
Flush()
void FAsyncRegisterLevelContext::Flush () private
Definition at line 105 of file AsyncRegisterLevelContext.cpp.
References AsyncAddPrimitiveQueue, Flush(), SendRenderDynamicDataPrimitivesQueue, and TRACE_CPUPROFILER_EVENT_SCOPE.
Referenced by Flush(), and SetIncrementalRegisterComponentsDone().
GetIncrementalRegisterComponentsDone()
bool FAsyncRegisterLevelContext::GetIncrementalRegisterComponentsDone () const inline
Definition at line 79 of file AsyncRegisterLevelContext.h.
References bIncrementalRegisterComponentsDone.
HasRemainingWork()
bool FAsyncRegisterLevelContext::HasRemainingWork () const
Definition at line 89 of file AsyncRegisterLevelContext.cpp.
References AsyncAddPrimitiveQueue, and SendRenderDynamicDataPrimitivesQueue.
IsRunningAsync()
bool FAsyncRegisterLevelContext::IsRunningAsync () const
Definition at line 94 of file AsyncRegisterLevelContext.cpp.
References AsyncAddPrimitiveQueue, and SendRenderDynamicDataPrimitivesQueue.
SetCanLaunchNewTasks()
void FAsyncRegisterLevelContext::SetCanLaunchNewTasks (bool bValue)
Definition at line 84 of file AsyncRegisterLevelContext.cpp.
References bCanLaunchNewTasks.
SetIncrementalRegisterComponentsDone()
void FAsyncRegisterLevelContext::SetIncrementalRegisterComponentsDone (bool bValue)
Definition at line 75 of file AsyncRegisterLevelContext.cpp.
References bIncrementalRegisterComponentsDone, and Flush().
Tick()
bool FAsyncRegisterLevelContext::Tick ()
Definition at line 112 of file AsyncRegisterLevelContext.cpp.
References AsyncAddPrimitiveQueue, bIncrementalRegisterComponentsDone, check, SendRenderDynamicDataPrimitivesQueue, Tick(), and TRACE_CPUPROFILER_EVENT_SCOPE.
Referenced by AddPrimitive(), AddSendRenderDynamicData(), and Tick().
WaitForAsyncTasks()
void FAsyncRegisterLevelContext::WaitForAsyncTasks ()
Definition at line 99 of file AsyncRegisterLevelContext.cpp.
References AsyncAddPrimitiveQueue, and SendRenderDynamicDataPrimitivesQueue.
Field Documentation
AsyncAddPrimitiveQueue
FAsyncAddPrimitiveQueue FAsyncRegisterLevelContext::AsyncAddPrimitiveQueue private
Definition at line 89 of file AsyncRegisterLevelContext.h.
Referenced by FAsyncRegisterLevelContext(), AddPrimitive(), Flush(), HasRemainingWork(), IsRunningAsync(), Tick(), and WaitForAsyncTasks().
bCanLaunchNewTasks
bool FAsyncRegisterLevelContext::bCanLaunchNewTasks private
Definition at line 91 of file AsyncRegisterLevelContext.h.
Referenced by FAsyncRegisterLevelContext(), and SetCanLaunchNewTasks().
bIncrementalRegisterComponentsDone
bool FAsyncRegisterLevelContext::bIncrementalRegisterComponentsDone private
Definition at line 92 of file AsyncRegisterLevelContext.h.
Referenced by FAsyncRegisterLevelContext(), AddPrimitive(), AddSendRenderDynamicData(), GetIncrementalRegisterComponentsDone(), SetIncrementalRegisterComponentsDone(), and Tick().
FAsyncAddPrimitiveQueue
friend FAsyncRegisterLevelContext::FAsyncAddPrimitiveQueue private
Definition at line 94 of file AsyncRegisterLevelContext.h.
FSendRenderDynamicDataPrimitivesQueue
friend FAsyncRegisterLevelContext::FSendRenderDynamicDataPrimitivesQueue private
Definition at line 95 of file AsyncRegisterLevelContext.h.
Level
ULevel* FAsyncRegisterLevelContext::Level private
Definition at line 88 of file AsyncRegisterLevelContext.h.
Referenced by FAsyncRegisterLevelContext().
SendRenderDynamicDataPrimitivesQueue
FSendRenderDynamicDataPrimitivesQueue FAsyncRegisterLevelContext::SendRenderDynamicDataPrimitivesQueue private
Definition at line 90 of file AsyncRegisterLevelContext.h.
Referenced by FAsyncRegisterLevelContext(), AddSendRenderDynamicData(), Flush(), HasRemainingWork(), IsRunningAsync(), Tick(), and WaitForAsyncTasks().
The documentation for this struct was generated from the following files:
Runtime/Engine/Internal/Streaming/AsyncRegisterLevelContext.h
Runtime/Engine/Internal/Streaming/AsyncRegisterLevelContext.cpp