Unreal Engine 5.6 C++ API: FStreamableHandle Struct Reference
FStreamableHandle Struct Reference
A handle to a synchronous or async load.
#include "StreamableManager.h"
Data Structures
struct FPrivateToken
Constructor is private, but this allows use by MakeShared.
Public Member Functions
FStreamableHandle (const FStreamableHandle &)=delete
Not safe to copy or duplicate.
FStreamableHandle (FPrivateToken, UE::FSourceLocation &&InLocation)
~FStreamableHandle ()
Destructor.
template<typename T>
void AddContextData (const TSharedPtr< T > &NewData)
Unconditionally adds a contextual data struct to this handle.
bool BindCancelDelegate (FStreamableDelegate NewDelegate)
bool BindCancelDelegate (FStreamableDelegateWithHandle NewDelegate)
Bind delegate that is called if handle is canceled, only works if loading is in progress.
bool BindCompleteDelegate (FStreamableDelegate NewDelegate)
bool BindCompleteDelegate (FStreamableDelegateWithHandle NewDelegate)
Bind delegate that is called when load completes, only works if loading is in progress.
bool BindUpdateDelegate (FStreamableUpdateDelegate NewDelegate)
Bind delegate that is called periodically as request updates, only works if loading is in progress.
void CancelHandle ()
Cancel a request, callable from within the manager or externally This will immediately release the handle even if it is still in progress, and call the cancel callback if bound This stops the completion callback from happening, even if it is in the delayed callback queue.
TSharedPtr< FStreamableHandle > CreateCombinedHandle (const TConstArrayView< TSharedPtr< FStreamableHandle > > &OtherHandles)
Creates a new merged handle which contains this handle as well as any external handles.
template<typename T>
TSharedPtr< T > FindFirstContextDataOfType () const
Finds the first instance of a contextual data struct which is attached to this handle.
TSharedPtr< FStreamableHandle > FindMatchingHandle (TFunction< bool(const FStreamableHandle &)> Predicate) const
Return a TSharedPtr of the first handle among this and descendants which satisfies the predicate.
template<typename T>
T & FindOrAddContextData ()
Gives you a mutable reference to a contextual data struct of the specified type.
template<typename CallableT>
void ForEachLoadedAsset (CallableT Callable) const
Invokes a callable for each loaded asset if load has succeeded.
float GetAbsoluteDownloadProgress () const
Returns progress as a value between 0.0 and 1.0 representing the total percentage of installed packages for the request.
template<typename T>
TArray< TSharedPtr< T > > GetContextDataOfType () const
Finds all instances of a contextual data struct which are attached to this handle.
ECookLoadType GetCookLoadType () const
const FString & GetDebugName () const
Returns the debug name for this handle.
FStreamableDownloadCachePin GetDownloadCachePin () const
Get download cache pin for this handle.
TArray< FStreamableDownloadCachePin > GetDownloadCachePins () const
Get download cache pins for this handle and all childern.
TOptional< FStreamableDownloadPriority > GetDownloadPriority () const
Returns download priority.
const TOptional< UE::UnifiedError::FError > & GetError () const
Get error details.
UObject * GetLoadedAsset () const
Returns first asset in requested asset list, if it's been successfully loaded.
template<class T>
T * GetLoadedAsset () const
Templated version of above.
template<class T>
void GetLoadedAssets (TArray< T * > &LoadedAssets) const
Templated version of above.
void GetLoadedAssets (TArray< UObject * > &LoadedAssets) const
Adds all loaded assets if load has succeeded.
void GetLoadedCount (int32 &LoadedCount, int32 &RequestedCount) const
Returns number of assets that have completed loading out of initial list, failed loads will count as loaded.
float GetLoadProgress () const
Returns progress as a value between 0.0 and 1.0.
TSharedPtr< FStreamableHandle > GetOutermostHandle ()
Crawls out to the outermost handle and returns it.
struct FStreamableManager * GetOwningManager () const
Get the StreamableManager for this handle.
TAsyncLoadPriority GetPriority () const
Returns the streaming priority.
float GetProgress (EStreamableProgressType Type=EStreamableProgressType::Load) const
Returns progress as a value between 0.0 and 1.0.
float GetRelativeDownloadProgress () const
Returns progress as a value between 0.0 and 1.0 representing progress of downloading packages that were not installed when the request was issued.
void GetRequestedAssets (TArray< FSoftObjectPath > &AssetList, bool bIncludeChildren=true) const
Gets list of assets references this load was started with.
bool HasCancelDelegate () const
Check to see whether or not the Cancel delegate is bound; useful for doing extra work before/without stomping the existing delegate.
bool HasCompleteDelegate () const
Check to see whether or not the Complete delegate is bound; useful for doing extra work before/without stomping the existing delegate.
bool HasError () const
True if an error occured.
bool HasLoadCompleted () const
If this request has finished loading, meaning all available assets were loaded Any assets that failed to load will still be null This can be true before the completion callback has happened as it may be in the delayed callback queue.
bool HasLoadCompletedOrStalled () const
Returns true if we've done all the loading we can now, ie all handles are either completed or stalled.
bool HasUpdateDelegate () const
Check to see whether or not the Update delegate is bound; useful for doing extra work before/without stomping the existing delegate.
bool IsActive () const
If this handle is still active, meaning it wasn't canceled or released.
bool IsCombinedHandle () const
Returns true if this is a combined handle that depends on child handles.
bool IsLoadingInProgress () const
True if load is still ongoing and we haven't been cancelled.
bool IsStalled () const
If this handle is stalled and waiting for another event to occur before it is actually requested.
FStreamableHandle & operator= (const FStreamableHandle &)=delete
void ReleaseHandle ()
Release this handle.
void SetDebugNameIfEmptyOrDefault (const FString &NewName)
Allows user code to provide a more detailed name in the cases where a name is autogenerated or otherwise default.
bool SetDownloadPriority (FStreamableDownloadPriority Priority)
Set download priority.
void StartStalledHandle ()
Tells a stalled handle to start its actual request.
EAsyncPackageState::Type WaitUntilComplete (float Timeout=0.0f, bool bStartStalledHandles=true)
Blocks until the requested assets have loaded.
bool WasCanceled () const
If this request was cancelled.
Public Member Functions inherited from TSharedFromThis< FStreamableHandle >
TSharedRef< FStreamableHandle, Mode > AsShared ()
Provides a shared reference to this object.
TSharedRef< SubobjectType, Mode > AsSharedSubobject (SubobjectType *SubobjectPtr) const
Provides a shared reference to a subobject of this object, i.e.
TWeakPtr< FStreamableHandle, Mode > AsWeak ()
Provides a weak reference to this object.
TWeakPtr< SubobjectType, Mode > AsWeakSubobject (SubobjectType *SubobjectPtr) const
Provides a weak pointer to a subobject of this object, i.e.
FORCEINLINE bool DoesSharedInstanceExist () const
Checks whether our referenced instance is valid (ie, whether it's safe to call AsShared).
FORCEINLINE void UpdateWeakReferenceInternal (TSharedPtr< SharedPtrType, SharedPtrMode > const *InSharedPtr, OtherType *InObject) const
INTERNAL USE ONLY – Do not call this method.
Static Public Member Functions
static void ExecuteDelegate (const FStreamableDelegate &Delegate, TSharedPtr< FStreamableHandle > AssociatedHandle=nullptr, const FStreamableDelegate &CancelDelegate=FStreamableDelegate())
Calls a StreamableDelegate, this will add to the delayed callback queue depending on s.StreamableDelegateDelayFrames.
static void ExecuteDelegate (const FStreamableDelegateWithHandle &Delegate, TSharedPtr< FStreamableHandle > AssociatedHandle=nullptr, const FStreamableDelegateWithHandle &CancelDelegate=FStreamableDelegateWithHandle())
Calls a StreamableDelegate, this will add to the delayed callback queue depending on s.StreamableDelegateDelayFrames.
static void ExecuteDelegate (FStreamableDelegate &&Delegate, TSharedPtr< FStreamableHandle > AssociatedHandle=nullptr, FStreamableDelegate &&CancelDelegate=FStreamableDelegate())
Overload taking the Delegate by rvalue.
static void ExecuteDelegate (FStreamableDelegateWithHandle &&Delegate, TSharedPtr< FStreamableHandle > AssociatedHandle=nullptr, FStreamableDelegateWithHandle &&CancelDelegate=FStreamableDelegateWithHandle())
Overload taking the Delegate by rvalue.
Static Public Attributes
static const FString HandleDebugName_AssetList
static const FString HandleDebugName_CombinedHandle
static const FString HandleDebugName_Error
static const FString HandleDebugName_Preloading
Private Member Functions
FStreamableHandle ()=delete
void AsyncLoadCallbackWrapper (const FName &PackageName, UPackage *LevelPackage, EAsyncLoadingResult::Type Result, FSoftObjectPath TargetName)
Callback when async load finishes, it's here so we can use a shared pointer for callback safety.
void CallUpdateDelegate ()
Call to call the update delegate if bound, will propagate to parents.
void CompleteLoad ()
Called from manager to complete the request.
bool IsHandleNameEmptyOrDefault () const
Called from self as part of SetDebugNameIfEmptyOrDefault.
void NotifyParentsOfCancellation ()
Notify all parents that a child was canceled.
void NotifyParentsOfCompletion ()
Notify all parents that a child completed loading.
void SetError (const UE::UnifiedError::FError &Error)
Record any errors that occured with this handle.
void SetErrorOnParents (const UE::UnifiedError::FError &Error)
void UnbindDelegates ()
Unbind all of our delegates, called after a cancel/load.
void UpdateCombinedHandle ()
Called on meta handle when a child handle has completed/canceled.
Private Attributes
TArray< TSharedPtr< FStreamableHandleContextDataBase > > AdditionalContextData
Array of contextual data added by game/engine code.
bool bCanceled
True if this request was explicitly canceled, which stops it from calling the completion delegate and immediately releases it.
bool bIsCombinedHandle
If true, this is a combined handle that depends on child handles.
bool bLoadCompleted
True if this request has finished loading.
bool bReleased
True if this request was released, which will stop it from keeping hard GC references.
bool bReleaseWhenLoaded
If true, this handle will be released when it finishes loading.
bool bStalled
True if this handle has been created but not yet actually requested.
FStreamableDelegateWithHandle CancelDelegate
Delegate to call when streaming is canceled.
int32 CanceledChildCount = 0
How many of our children that have been canceled.
TArray< TSharedPtr< FStreamableHandle > > ChildHandles
List of handles this depends on, these will keep the child references alive.
int32 CompletedChildCount = 0
How many of our children that have been completed.
FStreamableDelegateWithHandle CompleteDelegate
Delegate to call when streaming is completed.
ECookLoadType CookLoadType
FString DebugName
Name of this handle, passed in by caller to help in debugging.
FStreamableDownloadCachePin DownloadCachePin
Handle that holds packages in the download cache.
TUniquePtr< UE::StreamableManager::Private::FDownloadContext > DownloadContext
Download book-keeping, released when download finishes.
TOptional< UE::UnifiedError::FError > Error
Error details in case of an error.
UE::FSourceLocation Location
Holds a location where this asset list was requested from.
struct FStreamableManager * OwningManager
This is set at the time of creation, and will be cleared when request completes or is canceled.
TArray< TWeakPtr< FStreamableHandle > > ParentHandles
Backpointer to handles that depend on this.
TAsyncLoadPriority Priority
The async priority for this request.
TArray< FSoftObjectPath > RequestedAssets
List of assets that were referenced by this handle.
int32 StreamablesLoading
How many FStreamables is this waiting on to finish loading.
FStreamableUpdateDelegate UpdateDelegate
Called periodically during streaming to update progress UI.
Friends
struct FStreamable
struct FStreamableManager
struct UE::StreamableManager::Private::FDownloadContext
Additional Inherited Members
Protected Member Functions inherited from TSharedFromThis< FStreamableHandle >
TSharedFromThis ()
Hidden stub constructor.
~TSharedFromThis ()
Hidden destructor.
FORCEINLINE TSharedFromThis & operator= (TSharedFromThis const &)
Hidden stub assignment operator.
Static Protected Member Functions inherited from TSharedFromThis< FStreamableHandle >
static FORCEINLINE TSharedRef< OtherType, Mode > SharedThis (OtherType *ThisPtr)
Provides access to a shared reference to an object, given the object's 'this' pointer.
Detailed Description
A handle to a synchronous or async load.
As long as the handle is Active, loaded assets will stay in memory
Definition at line 190 of file StreamableManager.h.
Constructor & Destructor Documentation
FStreamableHandle() [1/3]
FStreamableHandle::FStreamableHandle () private delete
Referenced by FStreamableHandle(), FindMatchingHandle(), and operator=().
FStreamableHandle() [2/3]
FStreamableHandle::FStreamableHandle (FPrivateToken , UE::FSourceLocation && InLocation) explicit
~FStreamableHandle()
FStreamableHandle::~FStreamableHandle ()
Destructor.
FStreamableHandle() [3/3]
FStreamableHandle::FStreamableHandle (const FStreamableHandle &) delete
Not safe to copy or duplicate.
References FStreamableHandle().
Member Function Documentation
AddContextData()
template<typename T> void FStreamableHandle::AddContextData (const TSharedPtr< T > & NewData) inline
Unconditionally adds a contextual data struct to this handle.
Uniqueness is not enforced.
See also
FindFirstContextDataOfType
Definition at line 477 of file StreamableManager.h.
References AdditionalContextData.
Referenced by FindOrAddContextData().
AsyncLoadCallbackWrapper()
void FStreamableHandle::AsyncLoadCallbackWrapper (const FName & PackageName, UPackage * LevelPackage, EAsyncLoadingResult::Type Result, FSoftObjectPath TargetName) private
Callback when async load finishes, it's here so we can use a shared pointer for callback safety.
References PackageName.
BindCancelDelegate() [1/2]
bool FStreamableHandle::BindCancelDelegate (FStreamableDelegate NewDelegate)
BindCancelDelegate() [2/2]
bool FStreamableHandle::BindCancelDelegate (FStreamableDelegateWithHandle NewDelegate)
Bind delegate that is called if handle is canceled, only works if loading is in progress.
This will overwrite any already bound delegate!
BindCompleteDelegate() [1/2]
bool FStreamableHandle::BindCompleteDelegate (FStreamableDelegate NewDelegate)
BindCompleteDelegate() [2/2]
bool FStreamableHandle::BindCompleteDelegate (FStreamableDelegateWithHandle NewDelegate)
Bind delegate that is called when load completes, only works if loading is in progress.
This will overwrite any already bound delegate!
BindUpdateDelegate()
bool FStreamableHandle::BindUpdateDelegate (FStreamableUpdateDelegate NewDelegate)
Bind delegate that is called periodically as request updates, only works if loading is in progress.
This will overwrite any already bound delegate!
CallUpdateDelegate()
void FStreamableHandle::CallUpdateDelegate () private
Call to call the update delegate if bound, will propagate to parents.
CancelHandle()
void FStreamableHandle::CancelHandle ()
Cancel a request, callable from within the manager or externally This will immediately release the handle even if it is still in progress, and call the cancel callback if bound This stops the completion callback from happening, even if it is in the delayed callback queue.
CompleteLoad()
void FStreamableHandle::CompleteLoad () private
Called from manager to complete the request.
CreateCombinedHandle()
TSharedPtr< FStreamableHandle > FStreamableHandle::CreateCombinedHandle (const TConstArrayView< TSharedPtr< FStreamableHandle > > & OtherHandles)
Creates a new merged handle which contains this handle as well as any external handles.
No delegates are moved, and the new handle is returned for convenience. Parent handles no longer directly track this, but will be correctly linked with the newly merged handle (and this handle is a child of the merged hande).
Parameters
OtherHandles Container of handles which should be merged with this handle
Returns
Either the new merged handle or nullptr when merging isn't feasible
ExecuteDelegate() [1/4]
void FStreamableHandle::ExecuteDelegate (const FStreamableDelegate & Delegate, TSharedPtr< FStreamableHandle > AssociatedHandle = nullptr, const FStreamableDelegate & CancelDelegate = FStreamableDelegate()) static
Calls a StreamableDelegate, this will add to the delayed callback queue depending on s.StreamableDelegateDelayFrames.
Parameters
Delegate Primary delegate to execute
AssociatedHandle Streamable handle associated with this delegate, may be null
CancelDelegate If handle gets cancelled before primary delegate executes, this delegate will be called instead
References CancelDelegate.
ExecuteDelegate() [2/4]
void FStreamableHandle::ExecuteDelegate (const FStreamableDelegateWithHandle & Delegate, TSharedPtr< FStreamableHandle > AssociatedHandle = nullptr, const FStreamableDelegateWithHandle & CancelDelegate = FStreamableDelegateWithHandle()) static
Calls a StreamableDelegate, this will add to the delayed callback queue depending on s.StreamableDelegateDelayFrames.
Parameters
Delegate Primary delegate to execute
AssociatedHandle Streamable handle associated with this delegate, may be null
CancelDelegate If handle gets cancelled before primary delegate executes, this delegate will be called instead
References CancelDelegate.
ExecuteDelegate() [3/4]
void FStreamableHandle::ExecuteDelegate (FStreamableDelegate && Delegate, TSharedPtr< FStreamableHandle > AssociatedHandle = nullptr, FStreamableDelegate && CancelDelegate = FStreamableDelegate()) static
Overload taking the Delegate by rvalue.
Using this will prevent any copies of FStreamableDelegate from being made if the callback is deferred.
References CancelDelegate.
ExecuteDelegate() [4/4]
void FStreamableHandle::ExecuteDelegate (FStreamableDelegateWithHandle && Delegate, TSharedPtr< FStreamableHandle > AssociatedHandle = nullptr, FStreamableDelegateWithHandle && CancelDelegate = FStreamableDelegateWithHandle()) static
Overload taking the Delegate by rvalue.
Using this will prevent any copies of FStreamableDelegate from being made if the callback is deferred.
References CancelDelegate.
FindFirstContextDataOfType()
template<typename T> TSharedPtr< T > FStreamableHandle::FindFirstContextDataOfType () const inline
Finds the first instance of a contextual data struct which is attached to this handle.
Returns
Either nullptr, or TSharedPtr to the first instance of a T on this handle.
See also
AddContextData
Definition at line 489 of file StreamableManager.h.
References AdditionalContextData, and StaticCastSharedPtr().
Referenced by FindOrAddContextData().
FindMatchingHandle()
TSharedPtr< FStreamableHandle > FStreamableHandle::FindMatchingHandle (TFunction< bool(const FStreamableHandle &)> Predicate) const
Return a TSharedPtr of the first handle among this and descendants which satisfies the predicate.
Parameters
Predicate Conditional applied to each candidate handle
Returns
Either the first matching handle, or nullptr
See also
GetOutermostHandle
References FStreamableHandle(), and Predicate.
FindOrAddContextData()
template<typename T> T & FStreamableHandle::FindOrAddContextData () inline
Gives you a mutable reference to a contextual data struct of the specified type.
Returns
Either a newly constructed T, or one which was previously added to this handle.
Definition at line 457 of file StreamableManager.h.
References AddContextData(), FindFirstContextDataOfType(), TSharedPtr< ObjectType, InMode >::Get(), TSharedPtr< ObjectType, InMode >::IsValid(), and MakeShared().
ForEachLoadedAsset()
template<typename CallableT> void FStreamableHandle::ForEachLoadedAsset (CallableT Callable) const
Invokes a callable for each loaded asset if load has succeeded.
Some entries will be null if loading failed
Parameters
Callable Callable object
Definition at line 936 of file StreamableManager.h.
References ChildHandles, HasLoadCompleted(), Invoke(), IsActive(), OwningManager, and RequestedAssets.
Referenced by GetLoadedAssets().
GetAbsoluteDownloadProgress()
float FStreamableHandle::GetAbsoluteDownloadProgress () const inline
Returns progress as a value between 0.0 and 1.0 representing the total percentage of installed packages for the request.
Definition at line 396 of file StreamableManager.h.
References DownloadAbsolute, and GetProgress().
GetContextDataOfType()
template<typename T> TArray< TSharedPtr< T > > FStreamableHandle::GetContextDataOfType () const inline
Finds all instances of a contextual data struct which are attached to this handle.
Returns
Array filled with all instances of T currently attached to this handle
Definition at line 508 of file StreamableManager.h.
References TArray< InElementType, InAllocatorType >::Add(), AdditionalContextData, and StaticCastSharedPtr().
GetCookLoadType()
ECookLoadType FStreamableHandle::GetCookLoadType () const inline
Definition at line 276 of file StreamableManager.h.
References CookLoadType.
GetDebugName()
const FString & FStreamableHandle::GetDebugName () const inline
Returns the debug name for this handle.
Definition at line 260 of file StreamableManager.h.
References DebugName.
GetDownloadCachePin()
FStreamableDownloadCachePin FStreamableHandle::GetDownloadCachePin () const inline
Get download cache pin for this handle.
Definition at line 245 of file StreamableManager.h.
References DownloadCachePin.
GetDownloadCachePins()
TArray< FStreamableDownloadCachePin > FStreamableHandle::GetDownloadCachePins () const
Get download cache pins for this handle and all childern.
GetDownloadPriority()
TOptional< FStreamableDownloadPriority > FStreamableHandle::GetDownloadPriority () const
Returns download priority.
Only valid if a download has been requested and is not yet complete.
GetError()
const TOptional< UE::UnifiedError::FError > & FStreamableHandle::GetError () const inline
Get error details.
Definition at line 239 of file StreamableManager.h.
References Error.
GetLoadedAsset() [1/2]
UObject * FStreamableHandle::GetLoadedAsset () const
Returns first asset in requested asset list, if it's been successfully loaded.
This will fail if the asset failed to load
Referenced by GetLoadedAsset().
GetLoadedAsset() [2/2]
template<class T> T * FStreamableHandle::GetLoadedAsset () const inline
Templated version of above.
Definition at line 369 of file StreamableManager.h.
References Cast(), and GetLoadedAsset().
GetLoadedAssets() [1/2]
template<class T> void FStreamableHandle::GetLoadedAssets (TArray< T * > & LoadedAssets) const inline
Templated version of above.
Entries that fail to cast will also be null.
Definition at line 356 of file StreamableManager.h.
References TArray< InElementType, InAllocatorType >::Add(), Cast(), and ForEachLoadedAsset().
GetLoadedAssets() [2/2]
void FStreamableHandle::GetLoadedAssets (TArray< UObject * > & LoadedAssets) const
Adds all loaded assets if load has succeeded.
Some entries will be null if loading failed
GetLoadedCount()
void FStreamableHandle::GetLoadedCount (int32 & LoadedCount, int32 & RequestedCount) const
Returns number of assets that have completed loading out of initial list, failed loads will count as loaded.
GetLoadProgress()
float FStreamableHandle::GetLoadProgress () const inline
Returns progress as a value between 0.0 and 1.0.
Definition at line 390 of file StreamableManager.h.
References GetProgress(), and Load.
GetOutermostHandle()
TSharedPtr< FStreamableHandle > FStreamableHandle::GetOutermostHandle ()
Crawls out to the outermost handle and returns it.
Since we could have multiple Parent handles, we might have a tie. In cases of a tie, the eldest parent handle (so, lower indices) will win.
Returns
The single parent which is the most outer, or this if no Parent Handle
GetOwningManager()
struct FStreamableManager * FStreamableHandle::GetOwningManager () const
Get the StreamableManager for this handle.
References FStreamableManager.
GetPriority()
TAsyncLoadPriority FStreamableHandle::GetPriority () const inline
Returns the streaming priority.
Definition at line 283 of file StreamableManager.h.
References Priority.
GetProgress()
float FStreamableHandle::GetProgress (EStreamableProgressType Type = EStreamableProgressType::Load) const
Returns progress as a value between 0.0 and 1.0.
References Load.
Referenced by GetAbsoluteDownloadProgress(), GetLoadProgress(), and GetRelativeDownloadProgress().
GetRelativeDownloadProgress()
float FStreamableHandle::GetRelativeDownloadProgress () const inline
Returns progress as a value between 0.0 and 1.0 representing progress of downloading packages that were not installed when the request was issued.
Definition at line 393 of file StreamableManager.h.
References DownloadRelative, and GetProgress().
GetRequestedAssets()
void FStreamableHandle::GetRequestedAssets (TArray< FSoftObjectPath > & AssetList, bool bIncludeChildren = true) const
Gets list of assets references this load was started with.
This will be the paths before redirectors, and not all of these are guaranteed to be loaded
Parameters
AssetList Output array for requested assets. Array is Reset before adding values.
bIncludeChildren Whether the child handles should be included in the search.
HasCancelDelegate()
bool FStreamableHandle::HasCancelDelegate () const
Check to see whether or not the Cancel delegate is bound; useful for doing extra work before/without stomping the existing delegate.
HasCompleteDelegate()
bool FStreamableHandle::HasCompleteDelegate () const
Check to see whether or not the Complete delegate is bound; useful for doing extra work before/without stomping the existing delegate.
HasError()
bool FStreamableHandle::HasError () const inline
True if an error occured.
Definition at line 233 of file StreamableManager.h.
References Error.
HasLoadCompleted()
bool FStreamableHandle::HasLoadCompleted () const inline
If this request has finished loading, meaning all available assets were loaded Any assets that failed to load will still be null This can be true before the completion callback has happened as it may be in the delayed callback queue.
Definition at line 197 of file StreamableManager.h.
References bLoadCompleted.
Referenced by ForEachLoadedAsset().
HasLoadCompletedOrStalled()
bool FStreamableHandle::HasLoadCompletedOrStalled () const
Returns true if we've done all the loading we can now, ie all handles are either completed or stalled.
HasUpdateDelegate()
bool FStreamableHandle::HasUpdateDelegate () const
Check to see whether or not the Update delegate is bound; useful for doing extra work before/without stomping the existing delegate.
IsActive()
bool FStreamableHandle::IsActive () const inline
If this handle is still active, meaning it wasn't canceled or released.
Definition at line 215 of file StreamableManager.h.
References bCanceled, and bReleased.
Referenced by ForEachLoadedAsset().
IsCombinedHandle()
bool FStreamableHandle::IsCombinedHandle () const inline
Returns true if this is a combined handle that depends on child handles.
Definition at line 227 of file StreamableManager.h.
References bIsCombinedHandle.
IsHandleNameEmptyOrDefault()
bool FStreamableHandle::IsHandleNameEmptyOrDefault () const private
Called from self as part of SetDebugNameIfEmptyOrDefault.
IsLoadingInProgress()
bool FStreamableHandle::IsLoadingInProgress () const inline
True if load is still ongoing and we haven't been cancelled.
Definition at line 209 of file StreamableManager.h.
References bCanceled, and bLoadCompleted.
IsStalled()
bool FStreamableHandle::IsStalled () const inline
If this handle is stalled and waiting for another event to occur before it is actually requested.
Definition at line 221 of file StreamableManager.h.
References bStalled.
NotifyParentsOfCancellation()
void FStreamableHandle::NotifyParentsOfCancellation () private
Notify all parents that a child was canceled.
NotifyParentsOfCompletion()
void FStreamableHandle::NotifyParentsOfCompletion () private
Notify all parents that a child completed loading.
operator=()
FStreamableHandle & FStreamableHandle::operator= (const FStreamableHandle &) delete
References FStreamableHandle().
ReleaseHandle()
void FStreamableHandle::ReleaseHandle ()
Release this handle.
This can be called from normal gameplay code to indicate that the loaded assets are no longer needed This will be called implicitly if all shared pointers to this handle are destroyed If called before the completion delegate, the release will be delayed until after completion
SetDebugNameIfEmptyOrDefault()
void FStreamableHandle::SetDebugNameIfEmptyOrDefault (const FString & NewName)
Allows user code to provide a more detailed name in the cases where a name is autogenerated or otherwise default.
SetDownloadPriority()
bool FStreamableHandle::SetDownloadPriority (FStreamableDownloadPriority Priority)
Set download priority.
Only valid if a download has been requested and is not yet complete.
Returns
true if the priority could be set.
References Priority.
SetError()
void FStreamableHandle::SetError (const UE::UnifiedError::FError & Error) private
Record any errors that occured with this handle.
References Error.
SetErrorOnParents()
void FStreamableHandle::SetErrorOnParents (const UE::UnifiedError::FError & Error) private
References Error.
StartStalledHandle()
void FStreamableHandle::StartStalledHandle ()
Tells a stalled handle to start its actual request.
UnbindDelegates()
void FStreamableHandle::UnbindDelegates () private
Unbind all of our delegates, called after a cancel/load.
UpdateCombinedHandle()
void FStreamableHandle::UpdateCombinedHandle () private
Called on meta handle when a child handle has completed/canceled.
WaitUntilComplete()
EAsyncPackageState::Type FStreamableHandle::WaitUntilComplete (float Timeout = 0.0f, bool bStartStalledHandles = true)
Blocks until the requested assets have loaded.
This pushes the requested asset to the top of the priority list, but does not flush all async loading, usually resulting in faster completion than a LoadObject call
Parameters
Timeout Maximum time to wait, if this is 0 it will wait forever
StartStalledHandles If true it will force all handles waiting on external resources to try and load right now
References Timeout.
WasCanceled()
bool FStreamableHandle::WasCanceled () const inline
If this request was cancelled.
Assets may still have been loaded, but completion delegate was not called
Definition at line 203 of file StreamableManager.h.
References bCanceled.
Friends And Related Symbol Documentation
FStreamable
friend struct FStreamable friend
Definition at line 544 of file StreamableManager.h.
References FStreamable.
Referenced by FStreamable.
FStreamableManager
friend struct FStreamableManager friend
Definition at line 543 of file StreamableManager.h.
References FStreamableManager.
Referenced by FStreamableManager, and GetOwningManager().
UE::StreamableManager::Private::FDownloadContext
friend struct UE::StreamableManager::Private::FDownloadContext friend
Definition at line 545 of file StreamableManager.h.
References UE::StreamableManager::Private::FDownloadContext.
Referenced by UE::StreamableManager::Private::FDownloadContext.
Field Documentation
AdditionalContextData
TArray<TSharedPtr<FStreamableHandleContextDataBase> > FStreamableHandle::AdditionalContextData private
Array of contextual data added by game/engine code.
Definition at line 629 of file StreamableManager.h.
Referenced by AddContextData(), FindFirstContextDataOfType(), and GetContextDataOfType().
bCanceled
bool FStreamableHandle::bCanceled private
True if this request was explicitly canceled, which stops it from calling the completion delegate and immediately releases it.
Definition at line 642 of file StreamableManager.h.
Referenced by IsActive(), IsLoadingInProgress(), and WasCanceled().
bIsCombinedHandle
bool FStreamableHandle::bIsCombinedHandle private
If true, this is a combined handle that depends on child handles.
Definition at line 651 of file StreamableManager.h.
Referenced by IsCombinedHandle().
bLoadCompleted
bool FStreamableHandle::bLoadCompleted private
True if this request has finished loading.
It may still be active, or it may have been released
Definition at line 636 of file StreamableManager.h.
Referenced by HasLoadCompleted(), and IsLoadingInProgress().
bReleased
bool FStreamableHandle::bReleased private
True if this request was released, which will stop it from keeping hard GC references.
Definition at line 639 of file StreamableManager.h.
Referenced by IsActive().
bReleaseWhenLoaded
bool FStreamableHandle::bReleaseWhenLoaded private
If true, this handle will be released when it finishes loading.
Definition at line 648 of file StreamableManager.h.
bStalled
bool FStreamableHandle::bStalled private
True if this handle has been created but not yet actually requested.
This handle is probably waiting for a resource like a chunk to be available
Definition at line 645 of file StreamableManager.h.
Referenced by IsStalled().
CancelDelegate
FStreamableDelegateWithHandle FStreamableHandle::CancelDelegate private
Delegate to call when streaming is canceled.
Definition at line 579 of file StreamableManager.h.
Referenced by ExecuteDelegate(), ExecuteDelegate(), ExecuteDelegate(), and ExecuteDelegate().
CanceledChildCount
int32 FStreamableHandle::CanceledChildCount = 0 private
How many of our children that have been canceled.
Definition at line 609 of file StreamableManager.h.
ChildHandles
TArray<TSharedPtr<FStreamableHandle> > FStreamableHandle::ChildHandles private
List of handles this depends on, these will keep the child references alive.
Definition at line 615 of file StreamableManager.h.
Referenced by ForEachLoadedAsset().
CompletedChildCount
int32 FStreamableHandle::CompletedChildCount = 0 private
How many of our children that have been completed.
Definition at line 606 of file StreamableManager.h.
CompleteDelegate
FStreamableDelegateWithHandle FStreamableHandle::CompleteDelegate private
Delegate to call when streaming is completed.
Definition at line 576 of file StreamableManager.h.
CookLoadType
ECookLoadType FStreamableHandle::CookLoadType private
Definition at line 632 of file StreamableManager.h.
Referenced by GetCookLoadType().
DebugName
FString FStreamableHandle::DebugName private
Name of this handle, passed in by caller to help in debugging.
Definition at line 585 of file StreamableManager.h.
Referenced by GetDebugName().
DownloadCachePin
FStreamableDownloadCachePin FStreamableHandle::DownloadCachePin private
Handle that holds packages in the download cache.
Definition at line 594 of file StreamableManager.h.
Referenced by GetDownloadCachePin().
DownloadContext
TUniquePtr<UE::StreamableManager::Private::FDownloadContext> FStreamableHandle::DownloadContext private
Download book-keeping, released when download finishes.
Definition at line 597 of file StreamableManager.h.
Error
TOptional<UE::UnifiedError::FError> FStreamableHandle::Error private
Error details in case of an error.
Definition at line 591 of file StreamableManager.h.
Referenced by GetError(), HasError(), SetError(), and SetErrorOnParents().
HandleDebugName_AssetList
const FString FStreamableHandle::HandleDebugName_AssetList static
Definition at line 538 of file StreamableManager.h.
HandleDebugName_CombinedHandle
const FString FStreamableHandle::HandleDebugName_CombinedHandle static
Definition at line 539 of file StreamableManager.h.
Referenced by FStreamableManager::CreateCombinedHandle(), and FStreamableManager::CreateErrorHandle().
HandleDebugName_Error
const FString FStreamableHandle::HandleDebugName_Error static
Definition at line 540 of file StreamableManager.h.
HandleDebugName_Preloading
const FString FStreamableHandle::HandleDebugName_Preloading static
Definition at line 537 of file StreamableManager.h.
Location
UE::FSourceLocation FStreamableHandle::Location private
Holds a location where this asset list was requested from.
Definition at line 588 of file StreamableManager.h.
OwningManager
struct FStreamableManager* FStreamableHandle::OwningManager private
This is set at the time of creation, and will be cleared when request completes or is canceled.
Definition at line 626 of file StreamableManager.h.
Referenced by ForEachLoadedAsset().
ParentHandles
TArray<TWeakPtr<FStreamableHandle> > FStreamableHandle::ParentHandles private
Backpointer to handles that depend on this.
Definition at line 618 of file StreamableManager.h.
Priority
TAsyncLoadPriority FStreamableHandle::Priority private
The async priority for this request.
Definition at line 600 of file StreamableManager.h.
Referenced by GetPriority(), and SetDownloadPriority().
RequestedAssets
TArray<FSoftObjectPath> FStreamableHandle::RequestedAssets private
List of assets that were referenced by this handle.
Definition at line 612 of file StreamableManager.h.
Referenced by ForEachLoadedAsset().
StreamablesLoading
int32 FStreamableHandle::StreamablesLoading private
How many FStreamables is this waiting on to finish loading.
Definition at line 603 of file StreamableManager.h.
UpdateDelegate
FStreamableUpdateDelegate FStreamableHandle::UpdateDelegate private
Called periodically during streaming to update progress UI.
Definition at line 582 of file StreamableManager.h.
The documentation for this struct was generated from the following file:
Runtime/Engine/Classes/Engine/StreamableManager.h