Unreal Engine 5.6 C++ API: UE::Slate::TSlotAccessor< SlotType, std::enable_if_t< std::is_base_of_v< FSlotProxy, std::decay_t< SlotType > > > > Struct Template Reference
UE::Slate::TSlotAccessor< SlotType, std::enable_if_t< std::is_base_of_v< FSlotProxy, std::decay_t< SlotType > > > > Struct Template Reference
Specialization for FSlotProxy (and derived).
#include "LayoutUtils.h"
Public Member Functions
FVector2f GetArrangedSize (const FSlotProxy &InSlot, const FVector2f &InDefaultValue=FVector2f::ZeroVector) const
Get the slot's arranged size as it was last calculated.
FVector2f GetDesiredSize (const FSlotProxy &InSlot, const FVector2f &InDefaultValue=FVector2f::ZeroVector) const
Get the slot's desired size as it was last calculated.
int32 GetIndex (const FSlotProxy &InSlot, const int32 InDefaultValue=INDEX_NONE) const
Get the index of the slot within it's parent container.
FVector2f::FReal GetMaxSize (const FSlotProxy &InSlot, const FVector2f::FReal &InDefaultValue=0.0f) const
Get the slot's maximum size, if set.
FVector2f::FReal GetMinSize (const FSlotProxy &InSlot, const FVector2f::FReal &InDefaultValue=0.0f) const
Get the slot's minimum size, if set.
FMargin GetPadding (const FSlotProxy &InSlot, const FMargin &InDefaultValue=FMargin()) const
Get the slot padding.
float GetShrinkSizeValue (const FSlotProxy &InSlot, const float &InDefaultValue=0.0f) const
Get the slot's shrink size value, applicable if the size rule is FillContent.
FSizeParam::ESizeRule GetSizeRule (const FSlotProxy &InSlot, const FSizeParam::ESizeRule InDefaultValue=FSizeParam::SizeRule_Auto) const
Get the slot's applied size rule, ie.
float GetSizeValue (const FSlotProxy &InSlot, const float &InDefaultValue=0.0f) const
Get the slot's size value, applicable if the size rule is Fill or FillContent.
EVisibility GetVisibility (const FSlotProxy &InSlot, const EVisibility InDefaultValue=EVisibility::Visible) const
Get the current visibility state of the slot.
TSharedRef< SWidget > GetWidget (const FSlotProxy &InSlot) const
Get the contained widget.
FArrangedWidget MakeArrangedWidget (const FSlotProxy &InSlot, const FGeometry &InAllottedGeometry, const FVector2f &InLocalOffset, const FVector2f &InLocalSize) const
Makes an arranged widget for the given Slot.
Detailed Description
template<typename SlotType>
struct UE::Slate::TSlotAccessor< SlotType, std::enable_if_t< std::is_base_of_v< FSlotProxy, std::decay_t< SlotType > > > >
Specialization for FSlotProxy (and derived).
Definition at line 431 of file LayoutUtils.h.
Member Function Documentation
GetArrangedSize()
template<typename SlotType> FVector2f UE::Slate::TSlotAccessor< SlotType, std::enable_if_t< std::is_base_of_v< FSlotProxy, std::decay_t< SlotType > > > >::GetArrangedSize (const FSlotProxy & InSlot, const FVector2f & InDefaultValue = FVector2f::ZeroVector) const inline
Get the slot's arranged size as it was last calculated.
Definition at line 466 of file LayoutUtils.h.
References FSlotProxy::ArrangedSize, and UE::Math::TVector2< float >::ZeroVector.
GetDesiredSize()
template<typename SlotType> FVector2f UE::Slate::TSlotAccessor< SlotType, std::enable_if_t< std::is_base_of_v< FSlotProxy, std::decay_t< SlotType > > > >::GetDesiredSize (const FSlotProxy & InSlot, const FVector2f & InDefaultValue = FVector2f::ZeroVector) const inline
Get the slot's desired size as it was last calculated.
Definition at line 460 of file LayoutUtils.h.
References FSlotProxy::DesiredSize, and UE::Math::TVector2< float >::ZeroVector.
GetIndex()
template<typename SlotType> int32 UE::Slate::TSlotAccessor< SlotType, std::enable_if_t< std::is_base_of_v< FSlotProxy, std::decay_t< SlotType > > > >::GetIndex (const FSlotProxy & InSlot, const int32 InDefaultValue = INDEX_NONE) const inline
Get the index of the slot within it's parent container.
Definition at line 436 of file LayoutUtils.h.
References INDEX_NONE, and FSlotProxy::SlotIndex.
GetMaxSize()
template<typename SlotType> FVector2f::FReal UE::Slate::TSlotAccessor< SlotType, std::enable_if_t< std::is_base_of_v< FSlotProxy, std::decay_t< SlotType > > > >::GetMaxSize (const FSlotProxy & InSlot, const FVector2f::FReal & InDefaultValue = 0.0f) const inline
Get the slot's maximum size, if set.
A value of 0.0f indicates this is not set.
Definition at line 496 of file LayoutUtils.h.
References FSlotProxy::MaxSize.
GetMinSize()
template<typename SlotType> FVector2f::FReal UE::Slate::TSlotAccessor< SlotType, std::enable_if_t< std::is_base_of_v< FSlotProxy, std::decay_t< SlotType > > > >::GetMinSize (const FSlotProxy & InSlot, const FVector2f::FReal & InDefaultValue = 0.0f) const inline
Get the slot's minimum size, if set.
A value of 0.0f indicates this is not set.
Definition at line 490 of file LayoutUtils.h.
References FSlotProxy::MinSize.
GetPadding()
template<typename SlotType> FMargin UE::Slate::TSlotAccessor< SlotType, std::enable_if_t< std::is_base_of_v< FSlotProxy, std::decay_t< SlotType > > > >::GetPadding (const FSlotProxy & InSlot, const FMargin & InDefaultValue = FMargin()) const inline
Get the slot padding.
Definition at line 454 of file LayoutUtils.h.
References FSlotProxy::Padding.
GetShrinkSizeValue()
template<typename SlotType> float UE::Slate::TSlotAccessor< SlotType, std::enable_if_t< std::is_base_of_v< FSlotProxy, std::decay_t< SlotType > > > >::GetShrinkSizeValue (const FSlotProxy & InSlot, const float & InDefaultValue = 0.0f) const inline
Get the slot's shrink size value, applicable if the size rule is FillContent.
Definition at line 484 of file LayoutUtils.h.
References TAttribute< ObjectType >::Get(), FSizeParam::ShrinkValue, and FSlotProxy::SizeParam.
GetSizeRule()
template<typename SlotType> FSizeParam::ESizeRule UE::Slate::TSlotAccessor< SlotType, std::enable_if_t< std::is_base_of_v< FSlotProxy, std::decay_t< SlotType > > > >::GetSizeRule (const FSlotProxy & InSlot, const FSizeParam::ESizeRule InDefaultValue = FSizeParam::SizeRule_Auto) const inline
Get the slot's applied size rule, ie.
Auto, Fill.
Definition at line 472 of file LayoutUtils.h.
References FSlotProxy::SizeParam, FSizeParam::SizeRule, and FSizeParam::SizeRule_Auto.
GetSizeValue()
template<typename SlotType> float UE::Slate::TSlotAccessor< SlotType, std::enable_if_t< std::is_base_of_v< FSlotProxy, std::decay_t< SlotType > > > >::GetSizeValue (const FSlotProxy & InSlot, const float & InDefaultValue = 0.0f) const inline
Get the slot's size value, applicable if the size rule is Fill or FillContent.
Definition at line 478 of file LayoutUtils.h.
References TAttribute< ObjectType >::Get(), FSlotProxy::SizeParam, and FSizeParam::Value.
GetVisibility()
template<typename SlotType> EVisibility UE::Slate::TSlotAccessor< SlotType, std::enable_if_t< std::is_base_of_v< FSlotProxy, std::decay_t< SlotType > > > >::GetVisibility (const FSlotProxy & InSlot, const EVisibility InDefaultValue = EVisibility::Visible) const inline
Get the current visibility state of the slot.
Definition at line 448 of file LayoutUtils.h.
References FSlotProxy::Visibility, and EVisibility::Visible.
GetWidget()
template<typename SlotType> TSharedRef< SWidget > UE::Slate::TSlotAccessor< SlotType, std::enable_if_t< std::is_base_of_v< FSlotProxy, std::decay_t< SlotType > > > >::GetWidget (const FSlotProxy & InSlot) const inline
Get the contained widget.
This should always be valid, and return SNullWidget by default.
Definition at line 442 of file LayoutUtils.h.
References TSharedPtr< ObjectType, InMode >::IsValid(), SNullWidget::NullWidget, TSharedPtr< ObjectType, InMode >::ToSharedRef(), and FSlotProxy::Widget.
MakeArrangedWidget()
template<typename SlotType> FArrangedWidget UE::Slate::TSlotAccessor< SlotType, std::enable_if_t< std::is_base_of_v< FSlotProxy, std::decay_t< SlotType > > > >::MakeArrangedWidget (const FSlotProxy & InSlot, const FGeometry & InAllottedGeometry, const FVector2f & InLocalOffset, const FVector2f & InLocalSize) const inline
Makes an arranged widget for the given Slot.
This usually wraps FGeometry::MakeChild().
Definition at line 502 of file LayoutUtils.h.
References UE::Slate::TSlotAccessor< SlotType, typename >::GetWidget().
The documentation for this struct was generated from the following file:
Runtime/SlateCore/Public/Layout/LayoutUtils.h