Unreal Engine 5.6 C++ API: FMovieSceneEvaluationTreeRangeIterator Struct Reference
FMovieSceneEvaluationTreeRangeIterator Struct Reference
Type that iterates contiguous range/data combinations sequentially (including empty space between time ranges)
#include "MovieSceneEvaluationTree.h"
Public Member Functions
MOVIESCENE_API FMovieSceneEvaluationTreeRangeIterator (const FMovieSceneEvaluationTree &InTree)
Iterate the tree from -infinity.
MOVIESCENE_API FMovieSceneEvaluationTreeRangeIterator (const FMovieSceneEvaluationTree &InTree, TRangeBound< FFrameNumber > StartingBound)
Iterate the tree ranges starting at the range that overlaps the specified lower bound.
FMovieSceneEvaluationTreeRangeIterator Next () const
Get an iterator pointing to the next range.
FMovieSceneEvaluationTreeNodeHandle Node () const
Get the current node.
operator bool () const
conversion to "bool" returning true if the iterator has not reached the last element.
FMovieSceneEvaluationTreeRangeIterator & operator++ ()
Move onto the next time range.
FMovieSceneEvaluationTreeRangeIterator & operator-- ()
Move onto the previous time range.
FMovieSceneEvaluationTreeRangeIterator Previous () const
Get an iterator pointing to the previous range.
TRange< FFrameNumber > Range () const
Get the current range.
Private Member Functions
MOVIESCENE_API FMovieSceneEvaluationTreeNodeHandle FindNextChild (FMovieSceneEvaluationTreeNodeHandle ParentNodeHandle, TRangeBound< FFrameNumber > PredicateBound, bool bForwards)
Find the next child within the given parent that is >= the specified bound based on whether we're going forwards or backwards.
MOVIESCENE_API void Iter (bool bForwards)
Iterate onto the next range based on whether we're going forwards or backwards.
Static Private Member Functions
static bool CompareBound (bool bForwards, TRange< FFrameNumber > Range, TRangeBound< FFrameNumber > Bound)
Compare a bound with a range based on whether we're iterating forwards or backwards.
static TRangeBound< FFrameNumber > GetLeadingBound (bool bForwards, TRange< FFrameNumber > Range)
Access the 'leading' bound of a range (lowerbound if forwards, upperbound if backwards)
static TRangeBound< FFrameNumber > GetTrailingBound (bool bForwards, TRange< FFrameNumber > Range)
Access the 'trailing' bound of a range (upperbound if forwards, lowerbound if backwards)
Private Attributes
FMovieSceneEvaluationTreeNodeHandle CurrentNodeHandle
Handle of the current node.
TRange< FFrameNumber > CurrentRange
The unique time range that we're currently at.
const FMovieSceneEvaluationTree * Tree
The tree we're iterating.
Friends
bool operator!= (const FMovieSceneEvaluationTreeRangeIterator &Lhs, const FMovieSceneEvaluationTreeRangeIterator &Rhs)
bool operator== (const FMovieSceneEvaluationTreeRangeIterator &Lhs, const FMovieSceneEvaluationTreeRangeIterator &Rhs)
(In)Equality operators
Detailed Description
Type that iterates contiguous range/data combinations sequentially (including empty space between time ranges)
Definition at line 499 of file MovieSceneEvaluationTree.h.
Constructor & Destructor Documentation
FMovieSceneEvaluationTreeRangeIterator() [1/2]
MOVIESCENE_API FMovieSceneEvaluationTreeRangeIterator::FMovieSceneEvaluationTreeRangeIterator (const FMovieSceneEvaluationTree & InTree)
Iterate the tree from -infinity.
Referenced by Next(), operator!=, operator++(), operator--(), operator==, and Previous().
FMovieSceneEvaluationTreeRangeIterator() [2/2]
MOVIESCENE_API FMovieSceneEvaluationTreeRangeIterator::FMovieSceneEvaluationTreeRangeIterator (const FMovieSceneEvaluationTree & InTree, TRangeBound< FFrameNumber > StartingBound)
Iterate the tree ranges starting at the range that overlaps the specified lower bound.
Member Function Documentation
CompareBound()
bool FMovieSceneEvaluationTreeRangeIterator::CompareBound (bool bForwards, TRange< FFrameNumber > Range, TRangeBound< FFrameNumber > Bound) inline static private
Compare a bound with a range based on whether we're iterating forwards or backwards.
Definition at line 566 of file MovieSceneEvaluationTree.h.
References Range().
FindNextChild()
MOVIESCENE_API FMovieSceneEvaluationTreeNodeHandle FMovieSceneEvaluationTreeRangeIterator::FindNextChild (FMovieSceneEvaluationTreeNodeHandle ParentNodeHandle, TRangeBound< FFrameNumber > PredicateBound, bool bForwards) private
Find the next child within the given parent that is >= the specified bound based on whether we're going forwards or backwards.
GetLeadingBound()
TRangeBound< FFrameNumber > FMovieSceneEvaluationTreeRangeIterator::GetLeadingBound (bool bForwards, TRange< FFrameNumber > Range) inline static private
Access the 'leading' bound of a range (lowerbound if forwards, upperbound if backwards)
Definition at line 572 of file MovieSceneEvaluationTree.h.
References Range().
GetTrailingBound()
TRangeBound< FFrameNumber > FMovieSceneEvaluationTreeRangeIterator::GetTrailingBound (bool bForwards, TRange< FFrameNumber > Range) inline static private
Access the 'trailing' bound of a range (upperbound if forwards, lowerbound if backwards)
Definition at line 578 of file MovieSceneEvaluationTree.h.
References Range().
Iter()
MOVIESCENE_API void FMovieSceneEvaluationTreeRangeIterator::Iter (bool bForwards) private
Iterate onto the next range based on whether we're going forwards or backwards.
Referenced by operator++(), and operator--().
Next()
FMovieSceneEvaluationTreeRangeIterator FMovieSceneEvaluationTreeRangeIterator::Next () const inline
Get an iterator pointing to the next range.
Definition at line 522 of file MovieSceneEvaluationTree.h.
References FMovieSceneEvaluationTreeRangeIterator().
Node()
FMovieSceneEvaluationTreeNodeHandle FMovieSceneEvaluationTreeRangeIterator::Node () const inline
Get the current node.
Definition at line 542 of file MovieSceneEvaluationTree.h.
References CurrentNodeHandle.
operator bool()
FMovieSceneEvaluationTreeRangeIterator::operator bool () const inline explicit
conversion to "bool" returning true if the iterator has not reached the last element.
Definition at line 548 of file MovieSceneEvaluationTree.h.
References CurrentNodeHandle.
operator++()
FMovieSceneEvaluationTreeRangeIterator & FMovieSceneEvaluationTreeRangeIterator::operator++ () inline
Move onto the next time range.
Definition at line 508 of file MovieSceneEvaluationTree.h.
References FMovieSceneEvaluationTreeRangeIterator(), and Iter().
operator--()
FMovieSceneEvaluationTreeRangeIterator & FMovieSceneEvaluationTreeRangeIterator::operator-- () inline
Move onto the previous time range.
Definition at line 515 of file MovieSceneEvaluationTree.h.
References FMovieSceneEvaluationTreeRangeIterator(), and Iter().
Previous()
FMovieSceneEvaluationTreeRangeIterator FMovieSceneEvaluationTreeRangeIterator::Previous () const inline
Get an iterator pointing to the previous range.
Definition at line 529 of file MovieSceneEvaluationTree.h.
References FMovieSceneEvaluationTreeRangeIterator().
Range()
TRange< FFrameNumber > FMovieSceneEvaluationTreeRangeIterator::Range () const inline
Get the current range.
Definition at line 536 of file MovieSceneEvaluationTree.h.
References CurrentRange.
Referenced by CompareBound(), GetLeadingBound(), and GetTrailingBound().
Friends And Related Symbol Documentation
operator!=
bool operator!= (const FMovieSceneEvaluationTreeRangeIterator & Lhs, const FMovieSceneEvaluationTreeRangeIterator & Rhs) friend
Definition at line 560 of file MovieSceneEvaluationTree.h.
References FMovieSceneEvaluationTreeRangeIterator(), CurrentNodeHandle, CurrentRange, and Tree.
operator==
bool operator== (const FMovieSceneEvaluationTreeRangeIterator & Lhs, const FMovieSceneEvaluationTreeRangeIterator & Rhs) friend
(In)Equality operators
Definition at line 556 of file MovieSceneEvaluationTree.h.
References FMovieSceneEvaluationTreeRangeIterator(), CurrentNodeHandle, CurrentRange, and Tree.
Field Documentation
CurrentNodeHandle
FMovieSceneEvaluationTreeNodeHandle FMovieSceneEvaluationTreeRangeIterator::CurrentNodeHandle private
Handle of the current node.
Definition at line 593 of file MovieSceneEvaluationTree.h.
Referenced by Node(), operator bool(), operator!=, and operator==.
CurrentRange
TRange<FFrameNumber> FMovieSceneEvaluationTreeRangeIterator::CurrentRange private
The unique time range that we're currently at.
Definition at line 591 of file MovieSceneEvaluationTree.h.
Referenced by operator!=, operator==, and Range().
Tree
const FMovieSceneEvaluationTree* FMovieSceneEvaluationTreeRangeIterator::Tree private
The tree we're iterating.
Definition at line 595 of file MovieSceneEvaluationTree.h.
Referenced by operator!=, and operator==.
The documentation for this struct was generated from the following file:
Runtime/MovieScene/Public/Evaluation/MovieSceneEvaluationTree.h