Unreal Engine 5.6 C++ API: FixedTagPrivate::FMapHandle Struct Reference
FixedTagPrivate::FMapHandle Struct Reference
#include "AssetDataTagMap.h"
Public Member Functions
FNumberedPair At (uint32 Index) const
const FValueId * FindValue (FName Key) const
template<typename Func>
void ForEachPair (Func Fn) const
TArrayView< const FNumberedPair > GetNumberedView () const
TArrayView< const FNumberlessPair > GetNumberlessView () const
Data Fields
uint16 HasNumberlessKeys: 1
uint16 IsValid: 1
uint16 Num
uint32 PairBegin
uint16 StoreIndex: StoreIndexBits
Static Public Attributes
static constexpr uint32 StoreIndexBits = 14
Friends
bool operator== (FMapHandle A, FMapHandle B)
Detailed Description
Definition at line 134 of file AssetDataTagMap.h.
Member Function Documentation
At()
FNumberedPair FixedTagPrivate::FMapHandle::At (uint32 Index) const
FindValue()
const FValueId * FixedTagPrivate::FMapHandle::FindValue (FName Key) const
References Key.
ForEachPair()
template<typename Func> void FixedTagPrivate::FMapHandle::ForEachPair (Func Fn) const inline
Definition at line 155 of file AssetDataTagMap.h.
References GetNumberedView(), GetNumberlessView(), HasNumberlessKeys, and NAME_NO_NUMBER_INTERNAL.
GetNumberedView()
TArrayView< const FNumberedPair > FixedTagPrivate::FMapHandle::GetNumberedView () const
Referenced by ForEachPair().
GetNumberlessView()
TArrayView< const FNumberlessPair > FixedTagPrivate::FMapHandle::GetNumberlessView () const
Referenced by ForEachPair().
Friends And Related Symbol Documentation
operator==
bool operator== (FMapHandle A, FMapHandle B) friend
References A, and B.
Field Documentation
HasNumberlessKeys
uint16 FixedTagPrivate::FMapHandle::HasNumberlessKeys
Definition at line 139 of file AssetDataTagMap.h.
Referenced by ForEachPair().
IsValid
uint16 FixedTagPrivate::FMapHandle::IsValid
Definition at line 138 of file AssetDataTagMap.h.
Num
uint16 FixedTagPrivate::FMapHandle::Num
Definition at line 141 of file AssetDataTagMap.h.
PairBegin
uint32 FixedTagPrivate::FMapHandle::PairBegin
Definition at line 142 of file AssetDataTagMap.h.
StoreIndex
uint16 FixedTagPrivate::FMapHandle::StoreIndex
Definition at line 140 of file AssetDataTagMap.h.
StoreIndexBits
uint32 FixedTagPrivate::FMapHandle::StoreIndexBits = 14 static constexpr
Definition at line 136 of file AssetDataTagMap.h.
The documentation for this struct was generated from the following file:
Runtime/CoreUObject/Public/AssetRegistry/AssetDataTagMap.h