Unreal Engine 5.6 C++ API: FAudioChunkCache::FChunkKey Struct Reference
FAudioChunkCache::FChunkKey Struct Reference
#include "AudioStreamingCache.h"
Public Member Functions
FChunkKey ()=default
FChunkKey (const FChunkKey &Other)=default
FChunkKey (const FName &InSoundWaveName, const FGuid &InSoundWaveGuid, uint32 InChunkIndex, uint32 InChunkRevision=0)
FChunkKey (const FSoundWavePtr &InSoundWave, uint32 InChunkIndex, uint32 InChunkRevision=0)
FChunkKey & operator= (const FChunkKey &Other)=default
bool operator== (const FChunkKey &Other) const
Data Fields
uint32 ChunkIndex = INDEX_NONE
uint32 ChunkRevision = 0
FGuid ObjectKey = FGuid()
FName SoundWaveName = FName()
Friends
uint32 GetTypeHash (const FChunkKey &InChunkKey)
Hash function.
Detailed Description
Definition at line 36 of file AudioStreamingCache.h.
Constructor & Destructor Documentation
FChunkKey() [1/4]
FAudioChunkCache::FChunkKey::FChunkKey () default
Referenced by FChunkKey(), GetTypeHash, operator=(), and operator==().
FChunkKey() [2/4]
FAudioChunkCache::FChunkKey::FChunkKey (const FChunkKey & Other) default
References FChunkKey(), and Other.
FChunkKey() [3/4]
FAudioChunkCache::FChunkKey::FChunkKey (const FName & InSoundWaveName, const FGuid & InSoundWaveGuid, uint32 InChunkIndex, uint32 InChunkRevision = 0)
FChunkKey() [4/4]
FAudioChunkCache::FChunkKey::FChunkKey (const FSoundWavePtr & InSoundWave, uint32 InChunkIndex, uint32 InChunkRevision = 0)
Member Function Documentation
operator=()
FChunkKey & FAudioChunkCache::FChunkKey::operator= (const FChunkKey & Other) default
References FChunkKey(), and Other.
operator==()
bool FAudioChunkCache::FChunkKey::operator== (const FChunkKey & Other) const
References FChunkKey(), and Other.
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FChunkKey & InChunkKey) friend
Hash function.
Definition at line 75 of file AudioStreamingCache.h.
References FChunkKey(), ChunkIndex, ChunkRevision, GetTypeHash, Hash, HashCombineFast(), ObjectKey, and SoundWaveName.
Referenced by GetTypeHash.
Field Documentation
ChunkIndex
uint32 FAudioChunkCache::FChunkKey::ChunkIndex = INDEX_NONE
Definition at line 66 of file AudioStreamingCache.h.
Referenced by GetTypeHash.
ChunkRevision
uint32 FAudioChunkCache::FChunkKey::ChunkRevision = 0
Definition at line 70 of file AudioStreamingCache.h.
Referenced by GetTypeHash.
ObjectKey
FGuid FAudioChunkCache::FChunkKey::ObjectKey = FGuid()
Definition at line 65 of file AudioStreamingCache.h.
Referenced by GetTypeHash.
SoundWaveName
FName FAudioChunkCache::FChunkKey::SoundWaveName = FName()
Definition at line 64 of file AudioStreamingCache.h.
Referenced by GetTypeHash.
The documentation for this struct was generated from the following file:
Runtime/Engine/Public/AudioStreamingCache.h