Unreal Engine 5.6 C++ API: TSlateBaseNamedArgs< InWidgetType > Struct Template Reference
TSlateBaseNamedArgs< InWidgetType > Struct Template Reference
Base class for named arguments.
#include "DeclarativeSyntaxSupport.h"
Public Types
typedef WidgetType::FArguments WidgetArgsType
typedef InWidgetType WidgetType
Public Member Functions
WidgetArgsType & AccessibleParams (TOptional< FAccessibleWidgetData > InArg)
WidgetArgsType & AccessibleText (TAttribute< FText > InAttribute)
template<class UserClass, typename... VarTypes>
WidgetArgsType & AccessibleText (TSharedRef< UserClass > InUserObjectRef, typename TAttribute< FText >::FGetter::template TConstMethodPtr< UserClass, VarTypes... > InFunc, VarTypes... Vars)
template<class UserClass, typename... VarTypes>
WidgetArgsType & AccessibleText (UserClass *InUserObject, typename TAttribute< FText >::FGetter::template TConstMethodPtr< UserClass, VarTypes... > InFunc, VarTypes... Vars)
WidgetArgsType & AccessibleText_Lambda (TFunction< FText(void) > &&InFunctor)
template<class UserClass, typename... VarTypes>
WidgetArgsType & AccessibleText_Raw (UserClass *InUserObject, typename TAttribute< FText >::FGetter::template TConstMethodPtr< UserClass, VarTypes... > InFunc, VarTypes... Vars)
template<typename... VarTypes>
WidgetArgsType & AccessibleText_Static (TIdentity_T< typename TAttribute< FText >::FGetter::template TFuncPtr< VarTypes... > > InFunc, VarTypes... Vars)
template<class UserClass, typename... VarTypes>
WidgetArgsType & AccessibleText_UObject (UserClass *InUserObject, typename TAttribute< FText >::FGetter::template TConstMethodPtr< UserClass, VarTypes... > InFunc, VarTypes... Vars)
template<typename MetaDataType, typename Arg0Type>
WidgetArgsType & AddMetaData (Arg0Type InArg0)
Add metadata to this widget - convenience method - 1 argument.
template<typename MetaDataType, typename Arg0Type, typename Arg1Type>
WidgetArgsType & AddMetaData (Arg0Type InArg0, Arg1Type InArg1)
Add metadata to this widget - convenience method - 2 arguments.
WidgetArgsType & AddMetaData (TSharedRef< ISlateMetaData > InMetaData)
Add metadata to this widget.
WidgetArgsType & Clipping (EWidgetClipping InArg)
WidgetArgsType & Cursor (TAttribute< TOptional< EMouseCursor::Type > > InAttribute)
template<class UserClass, typename... VarTypes>
WidgetArgsType & Cursor (TSharedRef< UserClass > InUserObjectRef, typename TAttribute< TOptional< EMouseCursor::Type > >::FGetter::template TConstMethodPtr< UserClass, VarTypes... > InFunc, VarTypes... Vars)
template<class UserClass, typename... VarTypes>
WidgetArgsType & Cursor (UserClass *InUserObject, typename TAttribute< TOptional< EMouseCursor::Type > >::FGetter::template TConstMethodPtr< UserClass, VarTypes... > InFunc, VarTypes... Vars)
WidgetArgsType & Cursor_Lambda (TFunction< TOptional< EMouseCursor::Type >(void) > &&InFunctor)
template<class UserClass, typename... VarTypes>
WidgetArgsType & Cursor_Raw (UserClass *InUserObject, typename TAttribute< TOptional< EMouseCursor::Type > >::FGetter::template TConstMethodPtr< UserClass, VarTypes... > InFunc, VarTypes... Vars)
template<typename... VarTypes>
WidgetArgsType & Cursor_Static (TIdentity_T< typename TAttribute< TOptional< EMouseCursor::Type > >::FGetter::template TFuncPtr< VarTypes... > > InFunc, VarTypes... Vars)
template<class UserClass, typename... VarTypes>
WidgetArgsType & Cursor_UObject (UserClass *InUserObject, typename TAttribute< TOptional< EMouseCursor::Type > >::FGetter::template TConstMethodPtr< UserClass, VarTypes... > InFunc, VarTypes... Vars)
WidgetArgsType & FlowDirectionPreference (EFlowDirectionPreference InArg)
WidgetArgsType & ForceVolatile (bool InArg)
WidgetArgsType & IsEnabled (TAttribute< bool > InAttribute)
template<class UserClass, typename... VarTypes>
WidgetArgsType & IsEnabled (TSharedRef< UserClass > InUserObjectRef, typename TAttribute< bool >::FGetter::template TConstMethodPtr< UserClass, VarTypes... > InFunc, VarTypes... Vars)
template<class UserClass, typename... VarTypes>
WidgetArgsType & IsEnabled (UserClass *InUserObject, typename TAttribute< bool >::FGetter::template TConstMethodPtr< UserClass, VarTypes... > InFunc, VarTypes... Vars)
WidgetArgsType & IsEnabled_Lambda (TFunction< bool(void) > &&InFunctor)
template<class UserClass, typename... VarTypes>
WidgetArgsType & IsEnabled_Raw (UserClass *InUserObject, typename TAttribute< bool >::FGetter::template TConstMethodPtr< UserClass, VarTypes... > InFunc, VarTypes... Vars)
template<typename... VarTypes>
WidgetArgsType & IsEnabled_Static (TIdentity_T< typename TAttribute< bool >::FGetter::template TFuncPtr< VarTypes... > > InFunc, VarTypes... Vars)
template<class UserClass, typename... VarTypes>
WidgetArgsType & IsEnabled_UObject (UserClass *InUserObject, typename TAttribute< bool >::FGetter::template TConstMethodPtr< UserClass, VarTypes... > InFunc, VarTypes... Vars)
WidgetArgsType & Me ()
Used by the named argument pattern as a safe way to 'return *this' for call-chaining purposes.
WidgetArgsType & PixelSnappingMethod (EWidgetPixelSnapping InArg)
WidgetArgsType & RenderOpacity (float InArg)
WidgetArgsType & RenderTransform (TAttribute< TOptional< FSlateRenderTransform > > InAttribute)
template<class UserClass, typename... VarTypes>
WidgetArgsType & RenderTransform (TSharedRef< UserClass > InUserObjectRef, typename TAttribute< TOptional< FSlateRenderTransform > >::FGetter::template TConstMethodPtr< UserClass, VarTypes... > InFunc, VarTypes... Vars)
template<class UserClass, typename... VarTypes>
WidgetArgsType & RenderTransform (UserClass *InUserObject, typename TAttribute< TOptional< FSlateRenderTransform > >::FGetter::template TConstMethodPtr< UserClass, VarTypes... > InFunc, VarTypes... Vars)
WidgetArgsType & RenderTransform_Lambda (TFunction< TOptional< FSlateRenderTransform >(void) > &&InFunctor)
template<class UserClass, typename... VarTypes>
WidgetArgsType & RenderTransform_Raw (UserClass *InUserObject, typename TAttribute< TOptional< FSlateRenderTransform > >::FGetter::template TConstMethodPtr< UserClass, VarTypes... > InFunc, VarTypes... Vars)
template<typename... VarTypes>
WidgetArgsType & RenderTransform_Static (TIdentity_T< typename TAttribute< TOptional< FSlateRenderTransform > >::FGetter::template TFuncPtr< VarTypes... > > InFunc, VarTypes... Vars)
template<class UserClass, typename... VarTypes>
WidgetArgsType & RenderTransform_UObject (UserClass *InUserObject, typename TAttribute< TOptional< FSlateRenderTransform > >::FGetter::template TConstMethodPtr< UserClass, VarTypes... > InFunc, VarTypes... Vars)
WidgetArgsType & RenderTransformPivot (TAttribute< FVector2D > InAttribute)
template<class UserClass, typename... VarTypes>
WidgetArgsType & RenderTransformPivot (TSharedRef< UserClass > InUserObjectRef, typename TAttribute< FVector2D >::FGetter::template TConstMethodPtr< UserClass, VarTypes... > InFunc, VarTypes... Vars)
template<class UserClass, typename... VarTypes>
WidgetArgsType & RenderTransformPivot (UserClass *InUserObject, typename TAttribute< FVector2D >::FGetter::template TConstMethodPtr< UserClass, VarTypes... > InFunc, VarTypes... Vars)
WidgetArgsType & RenderTransformPivot_Lambda (TFunction< FVector2D(void) > &&InFunctor)
template<class UserClass, typename... VarTypes>
WidgetArgsType & RenderTransformPivot_Raw (UserClass *InUserObject, typename TAttribute< FVector2D >::FGetter::template TConstMethodPtr< UserClass, VarTypes... > InFunc, VarTypes... Vars)
template<typename... VarTypes>
WidgetArgsType & RenderTransformPivot_Static (TIdentity_T< typename TAttribute< FVector2D >::FGetter::template TFuncPtr< VarTypes... > > InFunc, VarTypes... Vars)
template<class UserClass, typename... VarTypes>
WidgetArgsType & RenderTransformPivot_UObject (UserClass *InUserObject, typename TAttribute< FVector2D >::FGetter::template TConstMethodPtr< UserClass, VarTypes... > InFunc, VarTypes... Vars)
WidgetArgsType & Tag (FName InArg)
WidgetArgsType & ToolTip (TAttribute< TSharedPtr< IToolTip > > InAttribute)
template<class UserClass, typename... VarTypes>
WidgetArgsType & ToolTip (TSharedRef< UserClass > InUserObjectRef, typename TAttribute< TSharedPtr< IToolTip > >::FGetter::template TConstMethodPtr< UserClass, VarTypes... > InFunc, VarTypes... Vars)
template<class UserClass, typename... VarTypes>
WidgetArgsType & ToolTip (UserClass *InUserObject, typename TAttribute< TSharedPtr< IToolTip > >::FGetter::template TConstMethodPtr< UserClass, VarTypes... > InFunc, VarTypes... Vars)
WidgetArgsType & ToolTip_Lambda (TFunction< TSharedPtr< IToolTip >(void) > &&InFunctor)
template<class UserClass, typename... VarTypes>
WidgetArgsType & ToolTip_Raw (UserClass *InUserObject, typename TAttribute< TSharedPtr< IToolTip > >::FGetter::template TConstMethodPtr< UserClass, VarTypes... > InFunc, VarTypes... Vars)
template<typename... VarTypes>
WidgetArgsType & ToolTip_Static (TIdentity_T< typename TAttribute< TSharedPtr< IToolTip > >::FGetter::template TFuncPtr< VarTypes... > > InFunc, VarTypes... Vars)
template<class UserClass, typename... VarTypes>
WidgetArgsType & ToolTip_UObject (UserClass *InUserObject, typename TAttribute< TSharedPtr< IToolTip > >::FGetter::template TConstMethodPtr< UserClass, VarTypes... > InFunc, VarTypes... Vars)
WidgetArgsType & ToolTipText (TAttribute< FText > InAttribute)
template<class UserClass, typename... VarTypes>
WidgetArgsType & ToolTipText (TSharedRef< UserClass > InUserObjectRef, typename TAttribute< FText >::FGetter::template TConstMethodPtr< UserClass, VarTypes... > InFunc, VarTypes... Vars)
template<class UserClass, typename... VarTypes>
WidgetArgsType & ToolTipText (UserClass *InUserObject, typename TAttribute< FText >::FGetter::template TConstMethodPtr< UserClass, VarTypes... > InFunc, VarTypes... Vars)
WidgetArgsType & ToolTipText_Lambda (TFunction< FText(void) > &&InFunctor)
template<class UserClass, typename... VarTypes>
WidgetArgsType & ToolTipText_Raw (UserClass *InUserObject, typename TAttribute< FText >::FGetter::template TConstMethodPtr< UserClass, VarTypes... > InFunc, VarTypes... Vars)
template<typename... VarTypes>
WidgetArgsType & ToolTipText_Static (TIdentity_T< typename TAttribute< FText >::FGetter::template TFuncPtr< VarTypes... > > InFunc, VarTypes... Vars)
template<class UserClass, typename... VarTypes>
WidgetArgsType & ToolTipText_UObject (UserClass *InUserObject, typename TAttribute< FText >::FGetter::template TConstMethodPtr< UserClass, VarTypes... > InFunc, VarTypes... Vars)
WidgetArgsType & Visibility (TAttribute< EVisibility > InAttribute)
template<class UserClass, typename... VarTypes>
WidgetArgsType & Visibility (TSharedRef< UserClass > InUserObjectRef, typename TAttribute< EVisibility >::FGetter::template TConstMethodPtr< UserClass, VarTypes... > InFunc, VarTypes... Vars)
template<class UserClass, typename... VarTypes>
WidgetArgsType & Visibility (UserClass *InUserObject, typename TAttribute< EVisibility >::FGetter::template TConstMethodPtr< UserClass, VarTypes... > InFunc, VarTypes... Vars)
WidgetArgsType & Visibility_Lambda (TFunction< EVisibility(void) > &&InFunctor)
template<class UserClass, typename... VarTypes>
WidgetArgsType & Visibility_Raw (UserClass *InUserObject, typename TAttribute< EVisibility >::FGetter::template TConstMethodPtr< UserClass, VarTypes... > InFunc, VarTypes... Vars)
template<typename... VarTypes>
WidgetArgsType & Visibility_Static (TIdentity_T< typename TAttribute< EVisibility >::FGetter::template TFuncPtr< VarTypes... > > InFunc, VarTypes... Vars)
template<class UserClass, typename... VarTypes>
WidgetArgsType & Visibility_UObject (UserClass *InUserObject, typename TAttribute< EVisibility >::FGetter::template TConstMethodPtr< UserClass, VarTypes... > InFunc, VarTypes... Vars)
Public Member Functions inherited from FSlateBaseNamedArgs
FSlateBaseNamedArgs ()=default
Additional Inherited Members
Data Fields inherited from FSlateBaseNamedArgs
TOptional< FAccessibleWidgetData > _AccessibleParams
TAttribute< FText > _AccessibleText
EWidgetClipping _Clipping = EWidgetClipping::Inherit
TAttribute< TOptional< EMouseCursor::Type > > _Cursor
bool _EnabledAttributesUpdate = true
If true, bound Slate Attributes will be updated once per frame.
EFlowDirectionPreference _FlowDirectionPreference = EFlowDirectionPreference::Inherit
bool _ForceVolatile = false
TAttribute< bool > _IsEnabled = true
EWidgetPixelSnapping _PixelSnappingMethod = EWidgetPixelSnapping::Inherit
float _RenderOpacity = 1.f
TAttribute< TOptional< FSlateRenderTransform > > _RenderTransform
TAttribute< FVector2D > _RenderTransformPivot = FVector2D::ZeroVector
FName _Tag
TAttribute< TSharedPtr< IToolTip > > _ToolTip
TAttribute< FText > _ToolTipText
TAttribute< EVisibility > _Visibility = EVisibility::Visible
TArray< TSharedRef< ISlateMetaData > > MetaData
Detailed Description
template<typename InWidgetType>
struct TSlateBaseNamedArgs< InWidgetType >
Base class for named arguments.
Provides settings necessary for all widgets.
Definition at line 679 of file DeclarativeSyntaxSupport.h.
Member Typedef Documentation
WidgetArgsType
template<typename InWidgetType> typedef WidgetType::FArguments TSlateBaseNamedArgs< InWidgetType >::WidgetArgsType
Definition at line 682 of file DeclarativeSyntaxSupport.h.
WidgetType
template<typename InWidgetType> typedef InWidgetType TSlateBaseNamedArgs< InWidgetType >::WidgetType
Definition at line 681 of file DeclarativeSyntaxSupport.h.
Member Function Documentation
AccessibleParams()
template<typename InWidgetType> WidgetArgsType & TSlateBaseNamedArgs< InWidgetType >::AccessibleParams (TOptional< FAccessibleWidgetData > InArg) inline
Definition at line 697 of file DeclarativeSyntaxSupport.h.
References RenderTransform(), and SLATE_PRIVATE_ATTRIBUTE_FUNCTION.
Referenced by AccessibleText().
AccessibleText() [1/3]
template<typename InWidgetType> WidgetArgsType & TSlateBaseNamedArgs< InWidgetType >::AccessibleText (TAttribute< FText > InAttribute) inline
Definition at line 698 of file DeclarativeSyntaxSupport.h.
References AccessibleParams(), RenderTransformPivot(), SLATE_PRIVATE_ARGUMENT_FUNCTION, SLATE_PRIVATE_ATTRIBUTE_FUNCTION, and Tag().
Referenced by Me().
AccessibleText() [2/3]
template<typename InWidgetType> template<class UserClass, typename... VarTypes> WidgetArgsType & TSlateBaseNamedArgs< InWidgetType >::AccessibleText (TSharedRef< UserClass > InUserObjectRef, typename TAttribute< FText >::FGetter::template TConstMethodPtr< UserClass, VarTypes... > InFunc, VarTypes... Vars) inline
Definition at line 698 of file DeclarativeSyntaxSupport.h.
AccessibleText() [3/3]
template<typename InWidgetType> template<class UserClass, typename... VarTypes> WidgetArgsType & TSlateBaseNamedArgs< InWidgetType >::AccessibleText (UserClass * InUserObject, typename TAttribute< FText >::FGetter::template TConstMethodPtr< UserClass, VarTypes... > InFunc, VarTypes... Vars) inline
Definition at line 698 of file DeclarativeSyntaxSupport.h.
AccessibleText_Lambda()
template<typename InWidgetType> WidgetArgsType & TSlateBaseNamedArgs< InWidgetType >::AccessibleText_Lambda (TFunction< FText(void) > && InFunctor) inline
Definition at line 698 of file DeclarativeSyntaxSupport.h.
AccessibleText_Raw()
template<typename InWidgetType> template<class UserClass, typename... VarTypes> WidgetArgsType & TSlateBaseNamedArgs< InWidgetType >::AccessibleText_Raw (UserClass * InUserObject, typename TAttribute< FText >::FGetter::template TConstMethodPtr< UserClass, VarTypes... > InFunc, VarTypes... Vars) inline
Definition at line 698 of file DeclarativeSyntaxSupport.h.
AccessibleText_Static()
template<typename InWidgetType> template<typename... VarTypes> WidgetArgsType & TSlateBaseNamedArgs< InWidgetType >::AccessibleText_Static (TIdentity_T< typename TAttribute< FText >::FGetter::template TFuncPtr< VarTypes... > > InFunc, VarTypes... Vars) inline
Definition at line 698 of file DeclarativeSyntaxSupport.h.
AccessibleText_UObject()
template<typename InWidgetType> template<class UserClass, typename... VarTypes> WidgetArgsType & TSlateBaseNamedArgs< InWidgetType >::AccessibleText_UObject (UserClass * InUserObject, typename TAttribute< FText >::FGetter::template TConstMethodPtr< UserClass, VarTypes... > InFunc, VarTypes... Vars) inline
Definition at line 698 of file DeclarativeSyntaxSupport.h.
AddMetaData() [1/3]
template<typename InWidgetType> template<typename MetaDataType, typename Arg0Type> WidgetArgsType & TSlateBaseNamedArgs< InWidgetType >::AddMetaData (Arg0Type InArg0) inline
Add metadata to this widget - convenience method - 1 argument.
Definition at line 715 of file DeclarativeSyntaxSupport.h.
References MakeShared(), Me(), and FSlateBaseNamedArgs::MetaData.
AddMetaData() [2/3]
template<typename InWidgetType> template<typename MetaDataType, typename Arg0Type, typename Arg1Type> WidgetArgsType & TSlateBaseNamedArgs< InWidgetType >::AddMetaData (Arg0Type InArg0, Arg1Type InArg1) inline
Add metadata to this widget - convenience method - 2 arguments.
Definition at line 723 of file DeclarativeSyntaxSupport.h.
References MakeShared(), Me(), and FSlateBaseNamedArgs::MetaData.
AddMetaData() [3/3]
template<typename InWidgetType> WidgetArgsType & TSlateBaseNamedArgs< InWidgetType >::AddMetaData (TSharedRef< ISlateMetaData > InMetaData) inline
Add metadata to this widget.
Definition at line 707 of file DeclarativeSyntaxSupport.h.
Clipping()
template<typename InWidgetType> WidgetArgsType & TSlateBaseNamedArgs< InWidgetType >::Clipping (EWidgetClipping InArg) inline
Definition at line 690 of file DeclarativeSyntaxSupport.h.
References IsEnabled(), and SLATE_PRIVATE_ATTRIBUTE_FUNCTION.
Referenced by RenderOpacity().
Cursor() [1/3]
template<typename InWidgetType> WidgetArgsType & TSlateBaseNamedArgs< InWidgetType >::Cursor (TAttribute< TOptional< EMouseCursor::Type > > InAttribute) inline
Definition at line 686 of file DeclarativeSyntaxSupport.h.
Referenced by ForceVolatile().
Cursor() [2/3]
template<typename InWidgetType> template<class UserClass, typename... VarTypes> WidgetArgsType & TSlateBaseNamedArgs< InWidgetType >::Cursor (TSharedRef< UserClass > InUserObjectRef, typename TAttribute< TOptional< EMouseCursor::Type > >::FGetter::template TConstMethodPtr< UserClass, VarTypes... > InFunc, VarTypes... Vars) inline
Definition at line 686 of file DeclarativeSyntaxSupport.h.
Cursor() [3/3]
template<typename InWidgetType> template<class UserClass, typename... VarTypes> WidgetArgsType & TSlateBaseNamedArgs< InWidgetType >::Cursor (UserClass * InUserObject, typename TAttribute< TOptional< EMouseCursor::Type > >::FGetter::template TConstMethodPtr< UserClass, VarTypes... > InFunc, VarTypes... Vars) inline
Definition at line 686 of file DeclarativeSyntaxSupport.h.
Cursor_Lambda()
template<typename InWidgetType> WidgetArgsType & TSlateBaseNamedArgs< InWidgetType >::Cursor_Lambda (TFunction< TOptional< EMouseCursor::Type >(void) > && InFunctor) inline
Definition at line 686 of file DeclarativeSyntaxSupport.h.
Cursor_Raw()
template<typename InWidgetType> template<class UserClass, typename... VarTypes> WidgetArgsType & TSlateBaseNamedArgs< InWidgetType >::Cursor_Raw (UserClass * InUserObject, typename TAttribute< TOptional< EMouseCursor::Type > >::FGetter::template TConstMethodPtr< UserClass, VarTypes... > InFunc, VarTypes... Vars) inline
Definition at line 686 of file DeclarativeSyntaxSupport.h.
Cursor_Static()
template<typename InWidgetType> template<typename... VarTypes> WidgetArgsType & TSlateBaseNamedArgs< InWidgetType >::Cursor_Static (TIdentity_T< typename TAttribute< TOptional< EMouseCursor::Type > >::FGetter::template TFuncPtr< VarTypes... > > InFunc, VarTypes... Vars) inline
Definition at line 686 of file DeclarativeSyntaxSupport.h.
Cursor_UObject()
template<typename InWidgetType> template<class UserClass, typename... VarTypes> WidgetArgsType & TSlateBaseNamedArgs< InWidgetType >::Cursor_UObject (UserClass * InUserObject, typename TAttribute< TOptional< EMouseCursor::Type > >::FGetter::template TConstMethodPtr< UserClass, VarTypes... > InFunc, VarTypes... Vars) inline
Definition at line 686 of file DeclarativeSyntaxSupport.h.
FlowDirectionPreference()
template<typename InWidgetType> WidgetArgsType & TSlateBaseNamedArgs< InWidgetType >::FlowDirectionPreference (EFlowDirectionPreference InArg) inline
Definition at line 692 of file DeclarativeSyntaxSupport.h.
References ForceVolatile(), and SLATE_PRIVATE_ARGUMENT_FUNCTION.
Referenced by RenderTransformPivot().
ForceVolatile()
template<typename InWidgetType> WidgetArgsType & TSlateBaseNamedArgs< InWidgetType >::ForceVolatile (bool InArg) inline
Definition at line 689 of file DeclarativeSyntaxSupport.h.
References Cursor(), and SLATE_PRIVATE_ATTRIBUTE_FUNCTION.
Referenced by FlowDirectionPreference().
IsEnabled() [1/3]
template<typename InWidgetType> WidgetArgsType & TSlateBaseNamedArgs< InWidgetType >::IsEnabled (TAttribute< bool > InAttribute) inline
Definition at line 687 of file DeclarativeSyntaxSupport.h.
References ToolTipText().
Referenced by Clipping().
IsEnabled() [2/3]
template<typename InWidgetType> template<class UserClass, typename... VarTypes> WidgetArgsType & TSlateBaseNamedArgs< InWidgetType >::IsEnabled (TSharedRef< UserClass > InUserObjectRef, typename TAttribute< bool >::FGetter::template TConstMethodPtr< UserClass, VarTypes... > InFunc, VarTypes... Vars) inline
Definition at line 687 of file DeclarativeSyntaxSupport.h.
IsEnabled() [3/3]
template<typename InWidgetType> template<class UserClass, typename... VarTypes> WidgetArgsType & TSlateBaseNamedArgs< InWidgetType >::IsEnabled (UserClass * InUserObject, typename TAttribute< bool >::FGetter::template TConstMethodPtr< UserClass, VarTypes... > InFunc, VarTypes... Vars) inline
Definition at line 687 of file DeclarativeSyntaxSupport.h.
IsEnabled_Lambda()
template<typename InWidgetType> WidgetArgsType & TSlateBaseNamedArgs< InWidgetType >::IsEnabled_Lambda (TFunction< bool(void) > && InFunctor) inline
Definition at line 687 of file DeclarativeSyntaxSupport.h.
IsEnabled_Raw()
template<typename InWidgetType> template<class UserClass, typename... VarTypes> WidgetArgsType & TSlateBaseNamedArgs< InWidgetType >::IsEnabled_Raw (UserClass * InUserObject, typename TAttribute< bool >::FGetter::template TConstMethodPtr< UserClass, VarTypes... > InFunc, VarTypes... Vars) inline
Definition at line 687 of file DeclarativeSyntaxSupport.h.
IsEnabled_Static()
template<typename InWidgetType> template<typename... VarTypes> WidgetArgsType & TSlateBaseNamedArgs< InWidgetType >::IsEnabled_Static (TIdentity_T< typename TAttribute< bool >::FGetter::template TFuncPtr< VarTypes... > > InFunc, VarTypes... Vars) inline
Definition at line 687 of file DeclarativeSyntaxSupport.h.
IsEnabled_UObject()
template<typename InWidgetType> template<class UserClass, typename... VarTypes> WidgetArgsType & TSlateBaseNamedArgs< InWidgetType >::IsEnabled_UObject (UserClass * InUserObject, typename TAttribute< bool >::FGetter::template TConstMethodPtr< UserClass, VarTypes... > InFunc, VarTypes... Vars) inline
Definition at line 687 of file DeclarativeSyntaxSupport.h.
Me()
template<typename InWidgetType> WidgetArgsType & TSlateBaseNamedArgs< InWidgetType >::Me () inline
Used by the named argument pattern as a safe way to 'return *this' for call-chaining purposes.
Definition at line 701 of file DeclarativeSyntaxSupport.h.
References AccessibleText(), Me(), and SLATE_PRIVATE_ATTRIBUTE_FUNCTION.
Referenced by AddMetaData(), AddMetaData(), and Me().
PixelSnappingMethod()
template<typename InWidgetType> WidgetArgsType & TSlateBaseNamedArgs< InWidgetType >::PixelSnappingMethod (EWidgetPixelSnapping InArg) inline
Definition at line 691 of file DeclarativeSyntaxSupport.h.
References SLATE_PRIVATE_ATTRIBUTE_FUNCTION, and Visibility().
Referenced by RenderTransform().
RenderOpacity()
template<typename InWidgetType> WidgetArgsType & TSlateBaseNamedArgs< InWidgetType >::RenderOpacity (float InArg) inline
Definition at line 693 of file DeclarativeSyntaxSupport.h.
References Clipping(), and SLATE_PRIVATE_ARGUMENT_FUNCTION.
Referenced by Tag().
RenderTransform() [1/3]
template<typename InWidgetType> WidgetArgsType & TSlateBaseNamedArgs< InWidgetType >::RenderTransform (TAttribute< TOptional< FSlateRenderTransform > > InAttribute) inline
Definition at line 694 of file DeclarativeSyntaxSupport.h.
References PixelSnappingMethod(), and SLATE_PRIVATE_ARGUMENT_FUNCTION.
Referenced by AccessibleParams().
RenderTransform() [2/3]
template<typename InWidgetType> template<class UserClass, typename... VarTypes> WidgetArgsType & TSlateBaseNamedArgs< InWidgetType >::RenderTransform (TSharedRef< UserClass > InUserObjectRef, typename TAttribute< TOptional< FSlateRenderTransform > >::FGetter::template TConstMethodPtr< UserClass, VarTypes... > InFunc, VarTypes... Vars) inline
Definition at line 694 of file DeclarativeSyntaxSupport.h.
RenderTransform() [3/3]
template<typename InWidgetType> template<class UserClass, typename... VarTypes> WidgetArgsType & TSlateBaseNamedArgs< InWidgetType >::RenderTransform (UserClass * InUserObject, typename TAttribute< TOptional< FSlateRenderTransform > >::FGetter::template TConstMethodPtr< UserClass, VarTypes... > InFunc, VarTypes... Vars) inline
Definition at line 694 of file DeclarativeSyntaxSupport.h.
RenderTransform_Lambda()
template<typename InWidgetType> WidgetArgsType & TSlateBaseNamedArgs< InWidgetType >::RenderTransform_Lambda (TFunction< TOptional< FSlateRenderTransform >(void) > && InFunctor) inline
Definition at line 694 of file DeclarativeSyntaxSupport.h.
RenderTransform_Raw()
template<typename InWidgetType> template<class UserClass, typename... VarTypes> WidgetArgsType & TSlateBaseNamedArgs< InWidgetType >::RenderTransform_Raw (UserClass * InUserObject, typename TAttribute< TOptional< FSlateRenderTransform > >::FGetter::template TConstMethodPtr< UserClass, VarTypes... > InFunc, VarTypes... Vars) inline
Definition at line 694 of file DeclarativeSyntaxSupport.h.
RenderTransform_Static()
template<typename InWidgetType> template<typename... VarTypes> WidgetArgsType & TSlateBaseNamedArgs< InWidgetType >::RenderTransform_Static (TIdentity_T< typename TAttribute< TOptional< FSlateRenderTransform > >::FGetter::template TFuncPtr< VarTypes... > > InFunc, VarTypes... Vars) inline
Definition at line 694 of file DeclarativeSyntaxSupport.h.
RenderTransform_UObject()
template<typename InWidgetType> template<class UserClass, typename... VarTypes> WidgetArgsType & TSlateBaseNamedArgs< InWidgetType >::RenderTransform_UObject (UserClass * InUserObject, typename TAttribute< TOptional< FSlateRenderTransform > >::FGetter::template TConstMethodPtr< UserClass, VarTypes... > InFunc, VarTypes... Vars) inline
Definition at line 694 of file DeclarativeSyntaxSupport.h.
RenderTransformPivot() [1/3]
template<typename InWidgetType> WidgetArgsType & TSlateBaseNamedArgs< InWidgetType >::RenderTransformPivot (TAttribute< FVector2D > InAttribute) inline
Definition at line 695 of file DeclarativeSyntaxSupport.h.
References FlowDirectionPreference(), and SLATE_PRIVATE_ARGUMENT_FUNCTION.
Referenced by AccessibleText().
RenderTransformPivot() [2/3]
template<typename InWidgetType> template<class UserClass, typename... VarTypes> WidgetArgsType & TSlateBaseNamedArgs< InWidgetType >::RenderTransformPivot (TSharedRef< UserClass > InUserObjectRef, typename TAttribute< FVector2D >::FGetter::template TConstMethodPtr< UserClass, VarTypes... > InFunc, VarTypes... Vars) inline
Definition at line 695 of file DeclarativeSyntaxSupport.h.
RenderTransformPivot() [3/3]
template<typename InWidgetType> template<class UserClass, typename... VarTypes> WidgetArgsType & TSlateBaseNamedArgs< InWidgetType >::RenderTransformPivot (UserClass * InUserObject, typename TAttribute< FVector2D >::FGetter::template TConstMethodPtr< UserClass, VarTypes... > InFunc, VarTypes... Vars) inline
Definition at line 695 of file DeclarativeSyntaxSupport.h.
RenderTransformPivot_Lambda()
template<typename InWidgetType> WidgetArgsType & TSlateBaseNamedArgs< InWidgetType >::RenderTransformPivot_Lambda (TFunction< FVector2D(void) > && InFunctor) inline
Definition at line 695 of file DeclarativeSyntaxSupport.h.
RenderTransformPivot_Raw()
template<typename InWidgetType> template<class UserClass, typename... VarTypes> WidgetArgsType & TSlateBaseNamedArgs< InWidgetType >::RenderTransformPivot_Raw (UserClass * InUserObject, typename TAttribute< FVector2D >::FGetter::template TConstMethodPtr< UserClass, VarTypes... > InFunc, VarTypes... Vars) inline
Definition at line 695 of file DeclarativeSyntaxSupport.h.
RenderTransformPivot_Static()
template<typename InWidgetType> template<typename... VarTypes> WidgetArgsType & TSlateBaseNamedArgs< InWidgetType >::RenderTransformPivot_Static (TIdentity_T< typename TAttribute< FVector2D >::FGetter::template TFuncPtr< VarTypes... > > InFunc, VarTypes... Vars) inline
Definition at line 695 of file DeclarativeSyntaxSupport.h.
RenderTransformPivot_UObject()
template<typename InWidgetType> template<class UserClass, typename... VarTypes> WidgetArgsType & TSlateBaseNamedArgs< InWidgetType >::RenderTransformPivot_UObject (UserClass * InUserObject, typename TAttribute< FVector2D >::FGetter::template TConstMethodPtr< UserClass, VarTypes... > InFunc, VarTypes... Vars) inline
Definition at line 695 of file DeclarativeSyntaxSupport.h.
Tag()
template<typename InWidgetType> WidgetArgsType & TSlateBaseNamedArgs< InWidgetType >::Tag (FName InArg) inline
Definition at line 696 of file DeclarativeSyntaxSupport.h.
References RenderOpacity(), and SLATE_PRIVATE_ARGUMENT_FUNCTION.
Referenced by AccessibleText().
ToolTip() [1/3]
template<typename InWidgetType> WidgetArgsType & TSlateBaseNamedArgs< InWidgetType >::ToolTip (TAttribute< TSharedPtr< IToolTip > > InAttribute) inline
Definition at line 685 of file DeclarativeSyntaxSupport.h.
Referenced by Visibility().
ToolTip() [2/3]
template<typename InWidgetType> template<class UserClass, typename... VarTypes> WidgetArgsType & TSlateBaseNamedArgs< InWidgetType >::ToolTip (TSharedRef< UserClass > InUserObjectRef, typename TAttribute< TSharedPtr< IToolTip > >::FGetter::template TConstMethodPtr< UserClass, VarTypes... > InFunc, VarTypes... Vars) inline
Definition at line 685 of file DeclarativeSyntaxSupport.h.
ToolTip() [3/3]
template<typename InWidgetType> template<class UserClass, typename... VarTypes> WidgetArgsType & TSlateBaseNamedArgs< InWidgetType >::ToolTip (UserClass * InUserObject, typename TAttribute< TSharedPtr< IToolTip > >::FGetter::template TConstMethodPtr< UserClass, VarTypes... > InFunc, VarTypes... Vars) inline
Definition at line 685 of file DeclarativeSyntaxSupport.h.
ToolTip_Lambda()
template<typename InWidgetType> WidgetArgsType & TSlateBaseNamedArgs< InWidgetType >::ToolTip_Lambda (TFunction< TSharedPtr< IToolTip >(void) > && InFunctor) inline
Definition at line 685 of file DeclarativeSyntaxSupport.h.
ToolTip_Raw()
template<typename InWidgetType> template<class UserClass, typename... VarTypes> WidgetArgsType & TSlateBaseNamedArgs< InWidgetType >::ToolTip_Raw (UserClass * InUserObject, typename TAttribute< TSharedPtr< IToolTip > >::FGetter::template TConstMethodPtr< UserClass, VarTypes... > InFunc, VarTypes... Vars) inline
Definition at line 685 of file DeclarativeSyntaxSupport.h.
ToolTip_Static()
template<typename InWidgetType> template<typename... VarTypes> WidgetArgsType & TSlateBaseNamedArgs< InWidgetType >::ToolTip_Static (TIdentity_T< typename TAttribute< TSharedPtr< IToolTip > >::FGetter::template TFuncPtr< VarTypes... > > InFunc, VarTypes... Vars) inline
Definition at line 685 of file DeclarativeSyntaxSupport.h.
ToolTip_UObject()
template<typename InWidgetType> template<class UserClass, typename... VarTypes> WidgetArgsType & TSlateBaseNamedArgs< InWidgetType >::ToolTip_UObject (UserClass * InUserObject, typename TAttribute< TSharedPtr< IToolTip > >::FGetter::template TConstMethodPtr< UserClass, VarTypes... > InFunc, VarTypes... Vars) inline
Definition at line 685 of file DeclarativeSyntaxSupport.h.
ToolTipText() [1/3]
template<typename InWidgetType> WidgetArgsType & TSlateBaseNamedArgs< InWidgetType >::ToolTipText (TAttribute< FText > InAttribute) inline
Definition at line 684 of file DeclarativeSyntaxSupport.h.
Referenced by IsEnabled().
ToolTipText() [2/3]
template<typename InWidgetType> template<class UserClass, typename... VarTypes> WidgetArgsType & TSlateBaseNamedArgs< InWidgetType >::ToolTipText (TSharedRef< UserClass > InUserObjectRef, typename TAttribute< FText >::FGetter::template TConstMethodPtr< UserClass, VarTypes... > InFunc, VarTypes... Vars) inline
Definition at line 684 of file DeclarativeSyntaxSupport.h.
ToolTipText() [3/3]
template<typename InWidgetType> template<class UserClass, typename... VarTypes> WidgetArgsType & TSlateBaseNamedArgs< InWidgetType >::ToolTipText (UserClass * InUserObject, typename TAttribute< FText >::FGetter::template TConstMethodPtr< UserClass, VarTypes... > InFunc, VarTypes... Vars) inline
Definition at line 684 of file DeclarativeSyntaxSupport.h.
ToolTipText_Lambda()
template<typename InWidgetType> WidgetArgsType & TSlateBaseNamedArgs< InWidgetType >::ToolTipText_Lambda (TFunction< FText(void) > && InFunctor) inline
Definition at line 684 of file DeclarativeSyntaxSupport.h.
ToolTipText_Raw()
template<typename InWidgetType> template<class UserClass, typename... VarTypes> WidgetArgsType & TSlateBaseNamedArgs< InWidgetType >::ToolTipText_Raw (UserClass * InUserObject, typename TAttribute< FText >::FGetter::template TConstMethodPtr< UserClass, VarTypes... > InFunc, VarTypes... Vars) inline
Definition at line 684 of file DeclarativeSyntaxSupport.h.
ToolTipText_Static()
template<typename InWidgetType> template<typename... VarTypes> WidgetArgsType & TSlateBaseNamedArgs< InWidgetType >::ToolTipText_Static (TIdentity_T< typename TAttribute< FText >::FGetter::template TFuncPtr< VarTypes... > > InFunc, VarTypes... Vars) inline
Definition at line 684 of file DeclarativeSyntaxSupport.h.
ToolTipText_UObject()
template<typename InWidgetType> template<class UserClass, typename... VarTypes> WidgetArgsType & TSlateBaseNamedArgs< InWidgetType >::ToolTipText_UObject (UserClass * InUserObject, typename TAttribute< FText >::FGetter::template TConstMethodPtr< UserClass, VarTypes... > InFunc, VarTypes... Vars) inline
Definition at line 684 of file DeclarativeSyntaxSupport.h.
Visibility() [1/3]
template<typename InWidgetType> WidgetArgsType & TSlateBaseNamedArgs< InWidgetType >::Visibility (TAttribute< EVisibility > InAttribute) inline
Definition at line 688 of file DeclarativeSyntaxSupport.h.
References SLATE_PRIVATE_ATTRIBUTE_FUNCTION, and ToolTip().
Referenced by PixelSnappingMethod().
Visibility() [2/3]
template<typename InWidgetType> template<class UserClass, typename... VarTypes> WidgetArgsType & TSlateBaseNamedArgs< InWidgetType >::Visibility (TSharedRef< UserClass > InUserObjectRef, typename TAttribute< EVisibility >::FGetter::template TConstMethodPtr< UserClass, VarTypes... > InFunc, VarTypes... Vars) inline
Definition at line 688 of file DeclarativeSyntaxSupport.h.
Visibility() [3/3]
template<typename InWidgetType> template<class UserClass, typename... VarTypes> WidgetArgsType & TSlateBaseNamedArgs< InWidgetType >::Visibility (UserClass * InUserObject, typename TAttribute< EVisibility >::FGetter::template TConstMethodPtr< UserClass, VarTypes... > InFunc, VarTypes... Vars) inline
Definition at line 688 of file DeclarativeSyntaxSupport.h.
Visibility_Lambda()
template<typename InWidgetType> WidgetArgsType & TSlateBaseNamedArgs< InWidgetType >::Visibility_Lambda (TFunction< EVisibility(void) > && InFunctor) inline
Definition at line 688 of file DeclarativeSyntaxSupport.h.
Visibility_Raw()
template<typename InWidgetType> template<class UserClass, typename... VarTypes> WidgetArgsType & TSlateBaseNamedArgs< InWidgetType >::Visibility_Raw (UserClass * InUserObject, typename TAttribute< EVisibility >::FGetter::template TConstMethodPtr< UserClass, VarTypes... > InFunc, VarTypes... Vars) inline
Definition at line 688 of file DeclarativeSyntaxSupport.h.
Visibility_Static()
template<typename InWidgetType> template<typename... VarTypes> WidgetArgsType & TSlateBaseNamedArgs< InWidgetType >::Visibility_Static (TIdentity_T< typename TAttribute< EVisibility >::FGetter::template TFuncPtr< VarTypes... > > InFunc, VarTypes... Vars) inline
Definition at line 688 of file DeclarativeSyntaxSupport.h.
Visibility_UObject()
template<typename InWidgetType> template<class UserClass, typename... VarTypes> WidgetArgsType & TSlateBaseNamedArgs< InWidgetType >::Visibility_UObject (UserClass * InUserObject, typename TAttribute< EVisibility >::FGetter::template TConstMethodPtr< UserClass, VarTypes... > InFunc, VarTypes... Vars) inline
Definition at line 688 of file DeclarativeSyntaxSupport.h.
The documentation for this struct was generated from the following file:
Runtime/SlateCore/Public/Widgets/DeclarativeSyntaxSupport.h