Unreal Engine 5.6 C++ API: FRigVMPinInfoArray Struct Reference
FRigVMPinInfoArray Struct Reference
#include "RigVMController.h"
Public Member Functions
FRigVMPinInfoArray ()
FRigVMPinInfoArray (const FRigVMGraphFunctionHeader &FunctionHeader, URigVMController *InController, const FRigVMPinInfoArray *InPreviousPinInfos=nullptr)
FRigVMPinInfoArray (const URigVMNode *InNode, URigVMController *InController)
FRigVMPinInfoArray (const URigVMNode *InNode, URigVMController *InController, const FRigVMPinInfoArray *InPreviousPinInfos)
int32 AddPin (const URigVMPin *InPin, int32 InParentIndex, ERigVMPinDirection InDirection, ERigVMPinDefaultValueType InDefaultValueType)
int32 AddPin (FProperty *InProperty, URigVMController *InController, ERigVMPinDirection InDirection, int32 InParentIndex, ERigVMPinDefaultValueType InDefaultValueType, const uint8 *InDefaultValueMemory, bool bAddSubPins)
int32 AddPin (URigVMController *InController, int32 InParentIndex, const FName &InName, ERigVMPinDirection InDirection, TRigVMTypeIndex InTypeIndex, const FString &InDefaultValue, ERigVMPinDefaultValueType InDefaultValueType, const uint8 *InDefaultValueMemory, const FRigVMPinInfoArray *InPreviousPinInfos, bool bAddSubPins)
void AddPins (UScriptStruct *InScriptStruct, URigVMController *InController, ERigVMPinDirection InDirection, int32 InParentIndex, TFunction< ERigVMPinDefaultValueType(const FName &)> InDefaultValueTypeGetter, const uint8 *InDefaultValueMemory, bool bAddSubPins)
TArray< FRigVMPinInfo >::RangedForIteratorType begin () const
TArray< FRigVMPinInfo >::RangedForIteratorType end () const
int32 GetIndexFromPinPath (const FString &InPinPath) const
const FRigVMPinInfo * GetPinFromPinPath (const FString &InPinPath) const
const FString & GetPinPath (const int32 InIndex) const
int32 GetRootIndex (const int32 InIndex) const
int32 Num () const
FRigVMPinInfo & operator[] (int32 InIndex)
const FRigVMPinInfo & operator[] (int32 InIndex) const
Data Fields
TMap< FString, int32 > PinPathLookup
TArray< FRigVMPinInfo > Pins
Friends
RIGVMDEVELOPER_API uint32 GetTypeHash (const FRigVMPinInfoArray &InPins)
Detailed Description
Definition at line 200 of file RigVMController.h.
Constructor & Destructor Documentation
FRigVMPinInfoArray() [1/4]
FRigVMPinInfoArray::FRigVMPinInfoArray () inline
Definition at line 202 of file RigVMController.h.
Referenced by FRigVMPinInfoArray(), FRigVMPinInfoArray(), AddPin(), and GetTypeHash.
FRigVMPinInfoArray() [2/4]
FRigVMPinInfoArray::FRigVMPinInfoArray (const URigVMNode * InNode, URigVMController * InController) explicit
FRigVMPinInfoArray() [3/4]
FRigVMPinInfoArray::FRigVMPinInfoArray (const URigVMNode * InNode, URigVMController * InController, const FRigVMPinInfoArray * InPreviousPinInfos)
References FRigVMPinInfoArray().
FRigVMPinInfoArray() [4/4]
FRigVMPinInfoArray::FRigVMPinInfoArray (const FRigVMGraphFunctionHeader & FunctionHeader, URigVMController * InController, const FRigVMPinInfoArray * InPreviousPinInfos = nullptr)
References FRigVMPinInfoArray().
Member Function Documentation
AddPin() [1/3]
int32 FRigVMPinInfoArray::AddPin (const URigVMPin * InPin, int32 InParentIndex, ERigVMPinDirection InDirection, ERigVMPinDefaultValueType InDefaultValueType)
AddPin() [2/3]
int32 FRigVMPinInfoArray::AddPin (FProperty * InProperty, URigVMController * InController, ERigVMPinDirection InDirection, int32 InParentIndex, ERigVMPinDefaultValueType InDefaultValueType, const uint8 * InDefaultValueMemory, bool bAddSubPins)
AddPin() [3/3]
int32 FRigVMPinInfoArray::AddPin (URigVMController * InController, int32 InParentIndex, const FName & InName, ERigVMPinDirection InDirection, TRigVMTypeIndex InTypeIndex, const FString & InDefaultValue, ERigVMPinDefaultValueType InDefaultValueType, const uint8 * InDefaultValueMemory, const FRigVMPinInfoArray * InPreviousPinInfos, bool bAddSubPins)
References FRigVMPinInfoArray(), and InName.
AddPins()
void FRigVMPinInfoArray::AddPins (UScriptStruct * InScriptStruct, URigVMController * InController, ERigVMPinDirection InDirection, int32 InParentIndex, TFunction< ERigVMPinDefaultValueType(const FName &)> InDefaultValueTypeGetter, const uint8 * InDefaultValueMemory, bool bAddSubPins)
begin()
TArray< FRigVMPinInfo >::RangedForIteratorType FRigVMPinInfoArray::begin () const inline
Definition at line 210 of file RigVMController.h.
References Pins.
end()
TArray< FRigVMPinInfo >::RangedForIteratorType FRigVMPinInfoArray::end () const inline
Definition at line 211 of file RigVMController.h.
References Pins.
GetIndexFromPinPath()
int32 FRigVMPinInfoArray::GetIndexFromPinPath (const FString & InPinPath) const
GetPinFromPinPath()
const FRigVMPinInfo * FRigVMPinInfoArray::GetPinFromPinPath (const FString & InPinPath) const
GetPinPath()
const FString & FRigVMPinInfoArray::GetPinPath (const int32 InIndex) const
GetRootIndex()
int32 FRigVMPinInfoArray::GetRootIndex (const int32 InIndex) const
Num()
int32 FRigVMPinInfoArray::Num () const inline
Definition at line 207 of file RigVMController.h.
References Pins.
operator[]() [1/2]
FRigVMPinInfo & FRigVMPinInfoArray::operator[] (int32 InIndex) inline
Definition at line 209 of file RigVMController.h.
References Pins.
operator[]() [2/2]
const FRigVMPinInfo & FRigVMPinInfoArray::operator[] (int32 InIndex) const inline
Definition at line 208 of file RigVMController.h.
References Pins.
Friends And Related Symbol Documentation
GetTypeHash
RIGVMDEVELOPER_API uint32 GetTypeHash (const FRigVMPinInfoArray & InPins) friend
References FRigVMPinInfoArray().
Field Documentation
PinPathLookup
TMap<FString, int32> FRigVMPinInfoArray::PinPathLookup mutable
Definition at line 226 of file RigVMController.h.
Pins
TArray<FRigVMPinInfo> FRigVMPinInfoArray::Pins mutable
Definition at line 225 of file RigVMController.h.
Referenced by begin(), end(), Num(), operator[](), and operator[]().
The documentation for this struct was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/RigVM/Source/RigVMDeveloper/Public/RigVMModel/RigVMController.h