Unreal Engine 5.6 C++ API: Runtime/CoreUObject/Public/StructUtils/InstancedStruct.h File Reference
InstancedStruct.h File Reference
#include "StructUtils.h"
#include "InstancedStruct.generated.h"
Data Structures
struct TInstancedStruct< BaseStructT >
TInstancedStruct is a type-safe FInstancedStruct wrapper against the given BaseStruct type.
struct TStructOpsTypeTraits< FInstancedStruct >
Macros
#define UE_API COREUOBJECT_API
Functions
USTRUCT ()) struct FInstancedStruct
FInstancedStruct works similarly as instanced UObject* property but is USTRUCTs.
Macro Definition Documentation
UE_API
#define UE_API COREUOBJECT_API
Definition at line 9 of file InstancedStruct.h.
Function Documentation
USTRUCT()
USTRUCT () nodiscard
FInstancedStruct works similarly as instanced UObject* property but is USTRUCTs.
Example:
UPROPERTY(EditAnywhere, Category = Foo, meta = (BaseStruct = "/Script/ModuleName.TestStructBase")) FInstancedStruct Test;
UPROPERTY(EditAnywhere, Category = Foo, meta = (BaseStruct = "/Script/ModuleName.TestStructBase")) TArray<FInstancedStruct> TestArray;
This constructor is explicit to avoid accidentally converting struct views to instanced structs (which would result in costly copy of the struct to be made). Implicit conversion could happen e.g. when comparing FInstancedStruct to FConstStructView.
Initializes from struct type and optional data.
Initializes from struct type and emplace construct.
Creates a new FInstancedStruct from templated struct type.
Creates a new FInstancedStruct from templated struct.
Creates a new FInstancedStruct from the templated type and forward all arguments to constructor.
For StructOpsTypeTraits
Returns struct type.
Returns const pointer to struct memory.
Reset to empty.
Returns const reference to the struct, this getter assumes that all data is valid.
Returns const pointer to the struct, or nullptr if cast is not valid.
Returns a mutable pointer to struct memory.
Returns mutable reference to the struct, this getter assumes that all data is valid.
Returns mutable pointer to the struct, or nullptr if cast is not valid.
Returns True if the struct is valid.
Comparison operators. Deep compares the struct instance when identical.
Internal method used to replace the script struct during user defined struct instantiation.
Definition at line 28 of file InstancedStruct.h.
References Ar, BlueprintType, Buffer, check, UE::StructUtils::CheckStructType(), DECLARE_DELEGATE_RetVal_ThreeParams, Forward(), GENERATED_BODY, TBaseStructureBase< T, bHasStaticStruct >::Get(), FConstStructView::GetScriptStruct(), UE::StructUtils::GetStructPtr(), UE::StructUtils::GetStructRef(), HasNativeMake, Identical, Info, IsValid(), Map, FMath::Max, Memory, meta, operator!=(), operator=(), operator==(), Other, Parent, PPF_None, PropertyName, Reset, ScriptStruct, FConstStructView::SetStructData(), Struct, UE_API, and Visit().