Unreal Engine 5.6 C++ API: TDereferencingIterator< ElementType, IteratorType > Struct Template Reference
TDereferencingIterator< ElementType, IteratorType > Struct Template Reference
#include "Array.h"
Public Member Functions
UE_NODEBUG TDereferencingIterator (IteratorType InIter)
UE_NODEBUG FORCEINLINE bool operator!= (const TDereferencingIterator &Rhs) const
UE_NODEBUG FORCEINLINE ElementType & operator* () const
UE_NODEBUG FORCEINLINE TDereferencingIterator & operator++ ()
Private Attributes
IteratorType Iter
Detailed Description
template<typename ElementType, typename IteratorType>
struct TDereferencingIterator< ElementType, IteratorType >
Definition at line 276 of file Array.h.
Constructor & Destructor Documentation
TDereferencingIterator()
template<typename ElementType, typename IteratorType> UE_NODEBUG TDereferencingIterator< ElementType, IteratorType >::TDereferencingIterator (IteratorType InIter) inline explicit nodiscard
Definition at line 278 of file Array.h.
References Iter, and UE_NODEBUG.
Referenced by operator!=(), and operator++().
Member Function Documentation
operator!=()
template<typename ElementType, typename IteratorType> UE_NODEBUG FORCEINLINE bool TDereferencingIterator< ElementType, IteratorType >::operator!= (const TDereferencingIterator< ElementType, IteratorType > & Rhs) const inline nodiscard
Definition at line 294 of file Array.h.
References TDereferencingIterator(), FORCEINLINE, Iter, and UE_NODEBUG.
operator*()
template<typename ElementType, typename IteratorType> UE_NODEBUG FORCEINLINE ElementType & TDereferencingIterator< ElementType, IteratorType >::operator* () const inline nodiscard
Definition at line 283 of file Array.h.
References FORCEINLINE, Iter, and UE_NODEBUG.
operator++()
template<typename ElementType, typename IteratorType> UE_NODEBUG FORCEINLINE TDereferencingIterator & TDereferencingIterator< ElementType, IteratorType >::operator++ () inline
Definition at line 288 of file Array.h.
References TDereferencingIterator(), FORCEINLINE, Iter, and UE_NODEBUG.
Field Documentation
Iter
template<typename ElementType, typename IteratorType> IteratorType TDereferencingIterator< ElementType, IteratorType >::Iter private
Definition at line 300 of file Array.h.
Referenced by TDereferencingIterator(), operator!=(), operator*(), and operator++().
The documentation for this struct was generated from the following file:
Runtime/Core/Public/Containers/Array.h