Unreal Engine 5.6 C++ API: FAnimCurveBufferAccess Struct Reference
FAnimCurveBufferAccess Struct Reference
Stores the raw rich curves as FCompressedRichCurve internally with optional key reduction and key time quantization.
#include "AnimCurveCompressionCodec_UniformIndexable.h"
Public Member Functions
FAnimCurveBufferAccess (const UAnimSequenceBase *InSequence, FName InName)
int32 GetNumSamples () const
float GetTime (int32 SampleIndex) const
float GetValue (int32 SampleIndex) const
bool IsValid () const
UE_DEPRECATED (5.3, "Please use the constructor that takes a FName") 1 FAnimCurveBufferAccess(const UAnimSequenceBase *InSequence
Data Fields
SmartName::UID_Type InUID
Private Attributes
bool bUseCompressedData
const float * CompressedBuffer
int32 NumSamples
const FFloatCurve * RawCurve
float SampleRate
Detailed Description
Stores the raw rich curves as FCompressedRichCurve internally with optional key reduction and key time quantization.
Definition at line 14 of file AnimCurveCompressionCodec_UniformIndexable.h.
Constructor & Destructor Documentation
FAnimCurveBufferAccess()
FAnimCurveBufferAccess::FAnimCurveBufferAccess (const UAnimSequenceBase * InSequence, FName InName)
References FAnimCurveBufferAccess(), and InName.
Referenced by FAnimCurveBufferAccess().
Member Function Documentation
GetNumSamples()
int32 FAnimCurveBufferAccess::GetNumSamples () const inline
Definition at line 36 of file AnimCurveCompressionCodec_UniformIndexable.h.
References NumSamples.
GetTime()
float FAnimCurveBufferAccess::GetTime (int32 SampleIndex) const
GetValue()
float FAnimCurveBufferAccess::GetValue (int32 SampleIndex) const
IsValid()
bool FAnimCurveBufferAccess::IsValid () const inline
Definition at line 31 of file AnimCurveCompressionCodec_UniformIndexable.h.
References CompressedBuffer, IsValid(), and RawCurve.
Referenced by IsValid().
UE_DEPRECATED()
FAnimCurveBufferAccess::UE_DEPRECATED (5. 3, "Please use the constructor that takes a FName") const
Field Documentation
bUseCompressedData
bool FAnimCurveBufferAccess::bUseCompressedData private
Definition at line 23 of file AnimCurveCompressionCodec_UniformIndexable.h.
CompressedBuffer
const float* FAnimCurveBufferAccess::CompressedBuffer private
Definition at line 20 of file AnimCurveCompressionCodec_UniformIndexable.h.
Referenced by IsValid().
InUID
SmartName::UID_Type FAnimCurveBufferAccess::InUID
Definition at line 27 of file AnimCurveCompressionCodec_UniformIndexable.h.
NumSamples
int32 FAnimCurveBufferAccess::NumSamples private
Definition at line 17 of file AnimCurveCompressionCodec_UniformIndexable.h.
Referenced by GetNumSamples().
RawCurve
const FFloatCurve* FAnimCurveBufferAccess::RawCurve private
Definition at line 22 of file AnimCurveCompressionCodec_UniformIndexable.h.
Referenced by IsValid().
SampleRate
float FAnimCurveBufferAccess::SampleRate private
Definition at line 18 of file AnimCurveCompressionCodec_UniformIndexable.h.
The documentation for this struct was generated from the following file:
Runtime/Engine/Classes/Animation/AnimCurveCompressionCodec_UniformIndexable.h