Unreal Engine 5.6 C++ API: UE::AnimNext::ITimeline Struct Reference
UE::AnimNext::ITimeline Struct Reference
ITimeline.
#include "ITimeline.h"
Public Member Functions
DECLARE_ANIM_TRAIT_INTERFACE (ITimeline) ANIMNEXTANIMGRAPH_API virtual void GetSyncMarkers(const FExecutionContext &Context
virtual ANIMNEXTANIMGRAPH_API FTimelineDelta GetDelta (const FExecutionContext &Context, const TTraitBinding< ITimeline > &Binding) const
virtual ANIMNEXTANIMGRAPH_API const FText & GetDisplayName () const override
virtual ANIMNEXTANIMGRAPH_API const FText & GetDisplayShortName () const override
virtual ANIMNEXTANIMGRAPH_API FTimelineState GetState (const FExecutionContext &Context, const TTraitBinding< ITimeline > &Binding) const
Public Member Functions inherited from UE::AnimNext::ITraitInterface
virtual ~ITraitInterface ()
virtual FTraitInterfaceUID GetInterfaceUID () const
virtual bool IsInternal () const
Data Fields
const TTraitBinding< ITimeline > & Binding
const TTraitBinding< ITimeline > FTimelineSyncMarkerArray &OutSyncMarkers const
Additional Inherited Members
Static Public Attributes inherited from UE::AnimNext::ITraitInterface
static constexpr FTraitInterfaceUID InterfaceUID = FTraitInterfaceUID::MakeUID(TEXT("ITraitInterface"))
Detailed Description
ITimeline.
This interface exposes timeline related information.
Definition at line 224 of file ITimeline.h.
Member Function Documentation
DECLARE_ANIM_TRAIT_INTERFACE()
UE::AnimNext::ITimeline::DECLARE_ANIM_TRAIT_INTERFACE (ITimeline) const &
GetDelta()
virtual ANIMNEXTANIMGRAPH_API FTimelineDelta UE::AnimNext::ITimeline::GetDelta (const FExecutionContext & Context, const TTraitBinding< ITimeline > & Binding) const virtual
References Binding, const, GetDelta(), and UE_API.
Referenced by GetDelta().
GetDisplayName()
virtual ANIMNEXTANIMGRAPH_API const FText & UE::AnimNext::ITimeline::GetDisplayName () const override virtual
Reimplemented from UE::AnimNext::ITraitInterface.
References UE_API.
GetDisplayShortName()
virtual ANIMNEXTANIMGRAPH_API const FText & UE::AnimNext::ITimeline::GetDisplayShortName () const override virtual
Reimplemented from UE::AnimNext::ITraitInterface.
References UE_API.
GetState()
virtual ANIMNEXTANIMGRAPH_API FTimelineState UE::AnimNext::ITimeline::GetState (const FExecutionContext & Context, const TTraitBinding< ITimeline > & Binding) const virtual
Reimplemented in UE::AnimNext::FBlendStackCoreTrait.
References Binding, const, GetState(), and UE_API.
Referenced by GetState().
Field Documentation
Binding
const TTraitBinding<ITimeline>& UE::AnimNext::ITimeline::Binding
Definition at line 229 of file ITimeline.h.
Referenced by GetDelta(), and GetState().
const
const TTraitBinding<ITimeline> FTimelineSyncMarkerArray& OutSyncMarkers UE::AnimNext::ITimeline::const
Definition at line 229 of file ITimeline.h.
Referenced by GetDelta(), and GetState().
The documentation for this struct was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Experimental/AnimNextAnimGraph/Source/AnimNextAnimGraph/Public/TraitInterfaces/ITimeline.h