Unreal Engine 5.6 C++ API: UE::AnimNext::FTraitTemplate Struct Reference
UE::AnimNext::FTraitTemplate Struct Reference
Trait Template A trait template represents a specific trait within a FNodeTemplate.
#include "TraitTemplate.h"
Public Member Functions
ETraitMode GetMode () const noexcept
uint32 GetNodeInstanceOffset () const noexcept
uint32 GetNodeSharedLatentPropertyHandlesOffset () const noexcept
uint32 GetNodeSharedOffset () const noexcept
uint32 GetNumLatentPropreties () const noexcept
uint32 GetNumStackTraits () const
uint32 GetNumSubStackLatentPropreties () const
FTraitRegistryHandle GetRegistryHandle () const noexcept
const FAnimNextTraitSharedData * GetTraitDescription (const FNodeDescription &NodeDescription) const noexcept
FAnimNextTraitSharedData * GetTraitDescription (FNodeDescription &NodeDescription) const noexcept
uint32 GetTraitIndex () const
const FTraitInstanceData * GetTraitInstance (const FNodeInstance &NodeInstance) const noexcept
FTraitInstanceData * GetTraitInstance (FNodeInstance &NodeInstance) const noexcept
const FLatentPropertiesHeader & GetTraitLatentPropertiesHeader (const FNodeDescription &NodeDescription) const noexcept
FLatentPropertiesHeader & GetTraitLatentPropertiesHeader (FNodeDescription &NodeDescription) const noexcept
const FLatentPropertyHandle * GetTraitLatentPropertyHandles (const FNodeDescription &NodeDescription) const noexcept
FLatentPropertyHandle * GetTraitLatentPropertyHandles (FNodeDescription &NodeDescription) const noexcept
FTraitUID GetUID () const noexcept
bool HasLatentProperties () const noexcept
bool IsValid () const noexcept
ANIMNEXTANIMGRAPH_API void Serialize (FArchive &Ar)
Private Member Functions
FTraitTemplate (FTraitUID InUID, FTraitRegistryHandle InRegistryHandle, ETraitMode InMode, uint32 InTraitIndexOrNumTraits) noexcept
Private Attributes
uint8 Mode
uint16 NodeInstanceOffset
uint16 NodeSharedLatentPropertyHandlesOffset
uint16 NodeSharedOffset
uint16 NumLatentProperties
uint16 NumSubStackLatentProperties
uint16 Padding0
FTraitRegistryHandle RegistryHandle
uint8 TraitIndexOrNumTraits
FTraitUIDRaw UID
Friends
struct FNodeTemplate
struct FNodeTemplateBuilder
Detailed Description
Trait Template A trait template represents a specific trait within a FNodeTemplate.
See also
FNodeTemplate
Definition at line 28 of file TraitTemplate.h.
Constructor & Destructor Documentation
FTraitTemplate()
UE::AnimNext::FTraitTemplate::FTraitTemplate (FTraitUID InUID, FTraitRegistryHandle InRegistryHandle, ETraitMode InMode, uint32 InTraitIndexOrNumTraits) inline private noexcept
Definition at line 139 of file TraitTemplate.h.
Member Function Documentation
GetMode()
ETraitMode UE::AnimNext::FTraitTemplate::GetMode () const inline noexcept
Definition at line 41 of file TraitTemplate.h.
References Mode.
Referenced by GetNumStackTraits(), GetNumSubStackLatentPropreties(), GetTraitIndex(), GetTraitLatentPropertiesHeader(), and GetTraitLatentPropertiesHeader().
GetNodeInstanceOffset()
uint32 UE::AnimNext::FTraitTemplate::GetNodeInstanceOffset () const inline noexcept
Definition at line 77 of file TraitTemplate.h.
References NodeInstanceOffset.
Referenced by GetTraitInstance(), and GetTraitInstance().
GetNodeSharedLatentPropertyHandlesOffset()
uint32 UE::AnimNext::FTraitTemplate::GetNodeSharedLatentPropertyHandlesOffset () const inline noexcept
Definition at line 74 of file TraitTemplate.h.
References NodeSharedLatentPropertyHandlesOffset.
Referenced by GetTraitLatentPropertiesHeader(), GetTraitLatentPropertiesHeader(), GetTraitLatentPropertyHandles(), and GetTraitLatentPropertyHandles().
GetNodeSharedOffset()
uint32 UE::AnimNext::FTraitTemplate::GetNodeSharedOffset () const inline noexcept
Definition at line 68 of file TraitTemplate.h.
References NodeSharedOffset.
Referenced by GetTraitDescription(), and GetTraitDescription().
GetNumLatentPropreties()
uint32 UE::AnimNext::FTraitTemplate::GetNumLatentPropreties () const inline noexcept
Definition at line 57 of file TraitTemplate.h.
References NumLatentProperties.
GetNumStackTraits()
uint32 UE::AnimNext::FTraitTemplate::GetNumStackTraits () const inline
Definition at line 44 of file TraitTemplate.h.
References UE::AnimNext::Base, check, GetMode(), and TraitIndexOrNumTraits.
GetNumSubStackLatentPropreties()
uint32 UE::AnimNext::FTraitTemplate::GetNumSubStackLatentPropreties () const inline
Definition at line 61 of file TraitTemplate.h.
References UE::AnimNext::Base, check, GetMode(), and NumSubStackLatentProperties.
GetRegistryHandle()
FTraitRegistryHandle UE::AnimNext::FTraitTemplate::GetRegistryHandle () const inline noexcept
Definition at line 34 of file TraitTemplate.h.
References RegistryHandle.
GetTraitDescription() [1/2]
const FAnimNextTraitSharedData * UE::AnimNext::FTraitTemplate::GetTraitDescription (const FNodeDescription & NodeDescription) const inline noexcept
Definition at line 89 of file TraitTemplate.h.
References GetNodeSharedOffset().
GetTraitDescription() [2/2]
FAnimNextTraitSharedData * UE::AnimNext::FTraitTemplate::GetTraitDescription (FNodeDescription & NodeDescription) const inline noexcept
Definition at line 83 of file TraitTemplate.h.
References GetNodeSharedOffset().
Referenced by UE::AnimNext::FTraitBinding::GetSharedData().
GetTraitIndex()
uint32 UE::AnimNext::FTraitTemplate::GetTraitIndex () const inline
Definition at line 51 of file TraitTemplate.h.
References UE::AnimNext::Base, GetMode(), and TraitIndexOrNumTraits.
GetTraitInstance() [1/2]
const FTraitInstanceData * UE::AnimNext::FTraitTemplate::GetTraitInstance (const FNodeInstance & NodeInstance) const inline noexcept
Definition at line 127 of file TraitTemplate.h.
References GetNodeInstanceOffset().
GetTraitInstance() [2/2]
FTraitInstanceData * UE::AnimNext::FTraitTemplate::GetTraitInstance (FNodeInstance & NodeInstance) const inline noexcept
Definition at line 121 of file TraitTemplate.h.
References GetNodeInstanceOffset().
Referenced by UE::AnimNext::FTraitBinding::GetInstanceData().
GetTraitLatentPropertiesHeader() [1/2]
const FLatentPropertiesHeader & UE::AnimNext::FTraitTemplate::GetTraitLatentPropertiesHeader (const FNodeDescription & NodeDescription) const inline noexcept
Definition at line 102 of file TraitTemplate.h.
References UE::AnimNext::Base, check, GetMode(), and GetNodeSharedLatentPropertyHandlesOffset().
GetTraitLatentPropertiesHeader() [2/2]
FLatentPropertiesHeader & UE::AnimNext::FTraitTemplate::GetTraitLatentPropertiesHeader (FNodeDescription & NodeDescription) const inline noexcept
Definition at line 95 of file TraitTemplate.h.
References UE::AnimNext::Base, check, GetMode(), and GetNodeSharedLatentPropertyHandlesOffset().
GetTraitLatentPropertyHandles() [1/2]
const FLatentPropertyHandle * UE::AnimNext::FTraitTemplate::GetTraitLatentPropertyHandles (const FNodeDescription & NodeDescription) const inline noexcept
Definition at line 115 of file TraitTemplate.h.
References GetNodeSharedLatentPropertyHandlesOffset().
GetTraitLatentPropertyHandles() [2/2]
FLatentPropertyHandle * UE::AnimNext::FTraitTemplate::GetTraitLatentPropertyHandles (FNodeDescription & NodeDescription) const inline noexcept
Definition at line 109 of file TraitTemplate.h.
References GetNodeSharedLatentPropertyHandlesOffset().
Referenced by UE::AnimNext::FTraitBinding::GetLatentPropertyHandles().
GetUID()
FTraitUID UE::AnimNext::FTraitTemplate::GetUID () const inline noexcept
Definition at line 31 of file TraitTemplate.h.
References UID.
HasLatentProperties()
bool UE::AnimNext::FTraitTemplate::HasLatentProperties () const inline noexcept
Definition at line 80 of file TraitTemplate.h.
References NumLatentProperties.
Referenced by UE::AnimNext::FTraitBinding::GetLatentPropertyHandles().
IsValid()
bool UE::AnimNext::FTraitTemplate::IsValid () const inline noexcept
Definition at line 38 of file TraitTemplate.h.
References RegistryHandle.
Serialize()
ANIMNEXTANIMGRAPH_API void UE::AnimNext::FTraitTemplate::Serialize (FArchive & Ar)
References Ar.
Friends And Related Symbol Documentation
FNodeTemplate
friend struct FNodeTemplate friend
Definition at line 136 of file TraitTemplate.h.
References FNodeTemplate.
Referenced by FNodeTemplate.
FNodeTemplateBuilder
friend struct FNodeTemplateBuilder friend
Definition at line 137 of file TraitTemplate.h.
References FNodeTemplateBuilder.
Referenced by FNodeTemplateBuilder.
Field Documentation
Mode
uint8 UE::AnimNext::FTraitTemplate::Mode private
Definition at line 161 of file TraitTemplate.h.
Referenced by GetMode().
NodeInstanceOffset
uint16 UE::AnimNext::FTraitTemplate::NodeInstanceOffset private
Definition at line 190 of file TraitTemplate.h.
Referenced by GetNodeInstanceOffset().
NodeSharedLatentPropertyHandlesOffset
uint16 UE::AnimNext::FTraitTemplate::NodeSharedLatentPropertyHandlesOffset private
Definition at line 189 of file TraitTemplate.h.
Referenced by GetNodeSharedLatentPropertyHandlesOffset().
NodeSharedOffset
uint16 UE::AnimNext::FTraitTemplate::NodeSharedOffset private
Definition at line 188 of file TraitTemplate.h.
Referenced by GetNodeSharedOffset().
NumLatentProperties
uint16 UE::AnimNext::FTraitTemplate::NumLatentProperties private
Definition at line 176 of file TraitTemplate.h.
Referenced by GetNumLatentPropreties(), and HasLatentProperties().
NumSubStackLatentProperties
uint16 UE::AnimNext::FTraitTemplate::NumSubStackLatentProperties private
Definition at line 180 of file TraitTemplate.h.
Referenced by GetNumSubStackLatentPropreties().
Padding0
uint16 UE::AnimNext::FTraitTemplate::Padding0 private
Definition at line 192 of file TraitTemplate.h.
RegistryHandle
FTraitRegistryHandle UE::AnimNext::FTraitTemplate::RegistryHandle private
Definition at line 158 of file TraitTemplate.h.
Referenced by GetRegistryHandle(), and IsValid().
TraitIndexOrNumTraits
uint8 UE::AnimNext::FTraitTemplate::TraitIndexOrNumTraits private
Definition at line 166 of file TraitTemplate.h.
Referenced by GetNumStackTraits(), and GetTraitIndex().
UID
FTraitUIDRaw UE::AnimNext::FTraitTemplate::UID private
Definition at line 155 of file TraitTemplate.h.
Referenced by GetUID().
The documentation for this struct was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Experimental/AnimNextAnimGraph/Source/AnimNextAnimGraph/Public/TraitCore/TraitTemplate.h