Unreal Engine 5.6 C++ API: FResourceArrayUploadArrayView Struct Reference
FResourceArrayUploadArrayView Struct Reference
Utility to do a simple upload of data from an array managed by the caller.
#include "ResourceArray.h"
Public Member Functions
FResourceArrayUploadArrayView ()=delete
template<typename ElementType, typename AllocatorType>
FResourceArrayUploadArrayView (const TArray< ElementType, AllocatorType > &InArray)
FResourceArrayUploadArrayView (const void *InData, uint32 InSizeInBytes)
template<typename ElementType>
FResourceArrayUploadArrayView (TConstArrayView< ElementType > View)
virtual void Discard () final
Called on non-UMA systems after the RHI has copied the resource data, and no longer needs the CPU's copy.
virtual const void * GetResourceData () const final
Returns a pointer to the resource data.
virtual uint32 GetResourceDataSize () const final
Returns size of resource data allocation.
Public Member Functions inherited from FResourceArrayUploadInterface
virtual ~FResourceArrayUploadInterface ()
template<typename TElement>
TConstArrayView< TElement > GetResourceDataView () const
Data Fields
const void *const Data
const uint32 SizeInBytes
Detailed Description
Utility to do a simple upload of data from an array managed by the caller.
Definition at line 30 of file ResourceArray.h.
Constructor & Destructor Documentation
FResourceArrayUploadArrayView() [1/4]
FResourceArrayUploadArrayView::FResourceArrayUploadArrayView () delete
Referenced by FResourceArrayUploadArrayView().
FResourceArrayUploadArrayView() [2/4]
FResourceArrayUploadArrayView::FResourceArrayUploadArrayView (const void * InData, uint32 InSizeInBytes) inline explicit nodiscard
Definition at line 37 of file ResourceArray.h.
References Data, and SizeInBytes.
FResourceArrayUploadArrayView() [3/4]
template<typename ElementType> FResourceArrayUploadArrayView::FResourceArrayUploadArrayView (TConstArrayView< ElementType > View) inline explicit nodiscard
Definition at line 44 of file ResourceArray.h.
References Data, GetData(), Num, and SizeInBytes.
FResourceArrayUploadArrayView() [4/4]
template<typename ElementType, typename AllocatorType> FResourceArrayUploadArrayView::FResourceArrayUploadArrayView (const TArray< ElementType, AllocatorType > & InArray) inline explicit nodiscard
Definition at line 51 of file ResourceArray.h.
References FResourceArrayUploadArrayView(), and MakeArrayView().
Member Function Documentation
Discard()
virtual void FResourceArrayUploadArrayView::Discard () inline final virtual
Called on non-UMA systems after the RHI has copied the resource data, and no longer needs the CPU's copy.
Implements FResourceArrayUploadInterface.
Definition at line 67 of file ResourceArray.h.
GetResourceData()
virtual const void * FResourceArrayUploadArrayView::GetResourceData () const inline nodiscard final virtual
Returns a pointer to the resource data.
Implements FResourceArrayUploadInterface.
Definition at line 57 of file ResourceArray.h.
References Data.
GetResourceDataSize()
virtual uint32 FResourceArrayUploadArrayView::GetResourceDataSize () const inline nodiscard final virtual
Returns size of resource data allocation.
Implements FResourceArrayUploadInterface.
Definition at line 62 of file ResourceArray.h.
References SizeInBytes.
Field Documentation
Data
const void* const FResourceArrayUploadArrayView::Data
Definition at line 32 of file ResourceArray.h.
Referenced by FResourceArrayUploadArrayView(), FResourceArrayUploadArrayView(), and GetResourceData().
SizeInBytes
const uint32 FResourceArrayUploadArrayView::SizeInBytes
Definition at line 33 of file ResourceArray.h.
Referenced by FResourceArrayUploadArrayView(), FResourceArrayUploadArrayView(), and GetResourceDataSize().
The documentation for this struct was generated from the following file:
Runtime/Core/Public/Containers/ResourceArray.h