Unreal Engine 5.6 C++ API: UE::AnimNext::FTraitStackBinding Struct Reference
UE::AnimNext::FTraitStackBinding Struct Reference
FTraitStackBinding.
#include "TraitStackBinding.h"
Public Member Functions
FTraitStackBinding ()=default
ANIMNEXTANIMGRAPH_API bool GetBaseTrait (FTraitBinding &OutBinding) const
FWeakTraitPtr GetBaseTraitPtr () const
ANIMNEXTANIMGRAPH_API bool GetChildTrait (const FTraitBinding &ParentBinding, FTraitBinding &OutChildBinding) const
template<class TraitInterface>
bool GetInterface (TTraitBinding< TraitInterface > &OutBinding) const
template<class TraitInterface>
bool GetInterfaceSuper (const FTraitBinding &Binding, TTraitBinding< TraitInterface > &OutSuperBinding) const
ANIMNEXTANIMGRAPH_API uint32 GetNumTraits () const
ANIMNEXTANIMGRAPH_API bool GetParentTrait (const FTraitBinding &ChildBinding, FTraitBinding &OutParentBinding) const
ANIMNEXTANIMGRAPH_API bool GetTopTrait (FTraitBinding &OutBinding) const
ANIMNEXTANIMGRAPH_API bool GetTrait (uint32 TraitIndex, FTraitBinding &OutBinding) const
template<class TraitInterface>
bool HasInterface () const
template<class TraitInterface>
bool HasInterfaceSuper (const FTraitBinding &Binding) const
bool IsValid () const
bool operator!= (const FTraitStackBinding &Other) const
ANIMNEXTANIMGRAPH_API bool operator== (const FTraitStackBinding &Other) const
ANIMNEXTANIMGRAPH_API void Reset ()
ANIMNEXTANIMGRAPH_API void SnapshotLatentProperties (bool bIsFrozen)
Private Member Functions
ANIMNEXTANIMGRAPH_API FTraitStackBinding (const FExecutionContext &InContext, const FWeakTraitPtr &TraitPtr)
ANIMNEXTANIMGRAPH_API bool GetInterfaceImpl (FTraitInterfaceUID InterfaceUID, FTraitBinding &OutBinding) const
ANIMNEXTANIMGRAPH_API bool GetInterfaceSuperImpl (FTraitInterfaceUID InterfaceUID, const FTraitBinding &Binding, FTraitBinding &OutSuperBinding) const
ANIMNEXTANIMGRAPH_API bool HasInterfaceImpl (FTraitInterfaceUID InterfaceUID) const
ANIMNEXTANIMGRAPH_API bool HasInterfaceSuperImpl (FTraitInterfaceUID InterfaceUID, const FTraitBinding &Binding) const
Private Attributes
uint32 BaseTraitIndex = 0
const FExecutionContext * Context = nullptr
friend FExecutionContext
friend FTraitBinding
const FNodeDescription * NodeDescription = nullptr
FNodeInstance * NodeInstance = nullptr
const FNodeTemplate * NodeTemplate = nullptr
uint32 TopTraitIndex = 0
Detailed Description
FTraitStackBinding.
To keep the node instance cost as low as possible, data such as pointers to the shared data are not stored per node and are instead fetched on demand. In order to be able to query for interfaces on a trait stack from a trait pointer, a trait stack binding must first be created.
Definition at line 31 of file TraitStackBinding.h.
Constructor & Destructor Documentation
FTraitStackBinding() [1/2]
UE::AnimNext::FTraitStackBinding::FTraitStackBinding () default
Referenced by operator!=(), and operator==().
FTraitStackBinding() [2/2]
ANIMNEXTANIMGRAPH_API UE::AnimNext::FTraitStackBinding::FTraitStackBinding (const FExecutionContext & InContext, const FWeakTraitPtr & TraitPtr) private
References FExecutionContext, and UE_API.
Member Function Documentation
GetBaseTrait()
ANIMNEXTANIMGRAPH_API bool UE::AnimNext::FTraitStackBinding::GetBaseTrait (FTraitBinding & OutBinding) const
References FTraitBinding, and UE_API.
GetBaseTraitPtr()
FWeakTraitPtr UE::AnimNext::FTraitStackBinding::GetBaseTraitPtr () const inline
Definition at line 50 of file TraitStackBinding.h.
References BaseTraitIndex, and NodeInstance.
GetChildTrait()
ANIMNEXTANIMGRAPH_API bool UE::AnimNext::FTraitStackBinding::GetChildTrait (const FTraitBinding & ParentBinding, FTraitBinding & OutChildBinding) const
References FTraitBinding, and UE_API.
GetInterface()
template<class TraitInterface> bool UE::AnimNext::FTraitStackBinding::GetInterface (TTraitBinding< TraitInterface > & OutBinding) const inline
Definition at line 151 of file TraitStackBinding.h.
References GetInterfaceImpl().
GetInterfaceImpl()
ANIMNEXTANIMGRAPH_API bool UE::AnimNext::FTraitStackBinding::GetInterfaceImpl (FTraitInterfaceUID InterfaceUID, FTraitBinding & OutBinding) const private
References FTraitBinding, and UE_API.
Referenced by GetInterface().
GetInterfaceSuper()
template<class TraitInterface> bool UE::AnimNext::FTraitStackBinding::GetInterfaceSuper (const FTraitBinding & Binding, TTraitBinding< TraitInterface > & OutSuperBinding) const inline
Definition at line 160 of file TraitStackBinding.h.
References FTraitBinding, and GetInterfaceSuperImpl().
GetInterfaceSuperImpl()
ANIMNEXTANIMGRAPH_API bool UE::AnimNext::FTraitStackBinding::GetInterfaceSuperImpl (FTraitInterfaceUID InterfaceUID, const FTraitBinding & Binding, FTraitBinding & OutSuperBinding) const private
References FTraitBinding, and UE_API.
Referenced by GetInterfaceSuper().
GetNumTraits()
ANIMNEXTANIMGRAPH_API uint32 UE::AnimNext::FTraitStackBinding::GetNumTraits () const
References FTraitBinding, and UE_API.
GetParentTrait()
ANIMNEXTANIMGRAPH_API bool UE::AnimNext::FTraitStackBinding::GetParentTrait (const FTraitBinding & ChildBinding, FTraitBinding & OutParentBinding) const
References FTraitBinding, and UE_API.
GetTopTrait()
ANIMNEXTANIMGRAPH_API bool UE::AnimNext::FTraitStackBinding::GetTopTrait (FTraitBinding & OutBinding) const
References FTraitBinding, and UE_API.
GetTrait()
ANIMNEXTANIMGRAPH_API bool UE::AnimNext::FTraitStackBinding::GetTrait (uint32 TraitIndex, FTraitBinding & OutBinding) const
References FTraitBinding, and UE_API.
HasInterface()
template<class TraitInterface> bool UE::AnimNext::FTraitStackBinding::HasInterface () const inline
Definition at line 169 of file TraitStackBinding.h.
References HasInterfaceImpl().
HasInterfaceImpl()
ANIMNEXTANIMGRAPH_API bool UE::AnimNext::FTraitStackBinding::HasInterfaceImpl (FTraitInterfaceUID InterfaceUID) const private
References UE_API.
Referenced by HasInterface().
HasInterfaceSuper()
template<class TraitInterface> bool UE::AnimNext::FTraitStackBinding::HasInterfaceSuper (const FTraitBinding & Binding) const inline
Definition at line 178 of file TraitStackBinding.h.
References FTraitBinding, and HasInterfaceSuperImpl().
HasInterfaceSuperImpl()
ANIMNEXTANIMGRAPH_API bool UE::AnimNext::FTraitStackBinding::HasInterfaceSuperImpl (FTraitInterfaceUID InterfaceUID, const FTraitBinding & Binding) const private
References FTraitBinding, and UE_API.
Referenced by HasInterfaceSuper().
IsValid()
bool UE::AnimNext::FTraitStackBinding::IsValid () const inline
Definition at line 37 of file TraitStackBinding.h.
References Context.
operator!=()
bool UE::AnimNext::FTraitStackBinding::operator!= (const FTraitStackBinding & Other) const inline
Definition at line 57 of file TraitStackBinding.h.
References FTraitStackBinding(), operator==(), and Other.
operator==()
ANIMNEXTANIMGRAPH_API bool UE::AnimNext::FTraitStackBinding::operator== (const FTraitStackBinding & Other) const
References FTraitStackBinding(), Other, and UE_API.
Referenced by operator!=().
Reset()
ANIMNEXTANIMGRAPH_API void UE::AnimNext::FTraitStackBinding::Reset ()
References UE_API.
SnapshotLatentProperties()
ANIMNEXTANIMGRAPH_API void UE::AnimNext::FTraitStackBinding::SnapshotLatentProperties (bool bIsFrozen)
References UE_API.
Field Documentation
BaseTraitIndex
uint32 UE::AnimNext::FTraitStackBinding::BaseTraitIndex = 0 private
Definition at line 138 of file TraitStackBinding.h.
Referenced by GetBaseTraitPtr().
Context
const FExecutionContext* UE::AnimNext::FTraitStackBinding::Context = nullptr private
Definition at line 125 of file TraitStackBinding.h.
Referenced by IsValid().
FExecutionContext
friend UE::AnimNext::FTraitStackBinding::FExecutionContext private
Definition at line 143 of file TraitStackBinding.h.
Referenced by FTraitStackBinding().
FTraitBinding
friend UE::AnimNext::FTraitStackBinding::FTraitBinding private
Definition at line 144 of file TraitStackBinding.h.
Referenced by GetBaseTrait(), GetChildTrait(), GetInterfaceImpl(), GetInterfaceSuper(), GetInterfaceSuperImpl(), GetNumTraits(), GetParentTrait(), GetTopTrait(), GetTrait(), HasInterfaceSuper(), and HasInterfaceSuperImpl().
NodeDescription
const FNodeDescription* UE::AnimNext::FTraitStackBinding::NodeDescription = nullptr private
Definition at line 131 of file TraitStackBinding.h.
NodeInstance
FNodeInstance* UE::AnimNext::FTraitStackBinding::NodeInstance = nullptr private
Definition at line 128 of file TraitStackBinding.h.
Referenced by GetBaseTraitPtr().
NodeTemplate
const FNodeTemplate* UE::AnimNext::FTraitStackBinding::NodeTemplate = nullptr private
Definition at line 134 of file TraitStackBinding.h.
TopTraitIndex
uint32 UE::AnimNext::FTraitStackBinding::TopTraitIndex = 0 private
Definition at line 141 of file TraitStackBinding.h.
The documentation for this struct was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Experimental/AnimNextAnimGraph/Source/AnimNextAnimGraph/Public/TraitCore/TraitStackBinding.h