Unreal Engine 5.6 C++ API: UE::Geometry::FVertexConstraint Struct Reference
UE::Geometry::FVertexConstraint Struct Reference
FVertexConstraint is a constraint on a triangle mesh vertex.
#include "MeshConstraints.h"
Public Member Functions
FVertexConstraint ()
FVertexConstraint (bool bCannotDelete, bool bCanMove, int FixedSetID=InvalidSetID)
FVertexConstraint (IProjectionTarget *Target, int FixedSetID=InvalidSetID)
void CombineConstraint (const FVertexConstraint &OtherConstraint)
Combine the incoming constraint with this constraint.
bool IsUnconstrained () const
Static Public Member Functions
static FVertexConstraint FullyConstrained ()
static FVertexConstraint PermanentMovable ()
static FVertexConstraint Unconstrained ()
Data Fields
bool bCanMove
Can this vertex be moved.
bool bCannotDelete
Is this vertex permanent (i.e.
int FixedSetID
Vertices marked as "CannotDelete" but sharing the same FixedSetID can optionally be collapsed together (ie in Remesher)
IProjectionTarget * Target
Vertex is associated with this ProjectionTarget, and should be projected onto it (ie in Remesher)
Static Public Attributes
static constexpr int InvalidSetID = -1
value for FixedSetID that is treated as not-a-fixed-set-ID by various functions (ie don't use this value yourself)
Detailed Description
FVertexConstraint is a constraint on a triangle mesh vertex.
Definition at line 146 of file MeshConstraints.h.
Constructor & Destructor Documentation
FVertexConstraint() [1/3]
UE::Geometry::FVertexConstraint::FVertexConstraint () inline
Definition at line 165 of file MeshConstraints.h.
References bCanMove, bCannotDelete, FixedSetID, InvalidSetID, and Target.
Referenced by CombineConstraint(), FullyConstrained(), PermanentMovable(), and Unconstrained().
FVertexConstraint() [2/3]
UE::Geometry::FVertexConstraint::FVertexConstraint (bool bCannotDelete, bool bCanMove, int FixedSetID = InvalidSetID) inline explicit
Definition at line 172 of file MeshConstraints.h.
References bCanMove, bCannotDelete, FixedSetID, InvalidSetID, and Target.
FVertexConstraint() [3/3]
UE::Geometry::FVertexConstraint::FVertexConstraint (IProjectionTarget * Target, int FixedSetID = InvalidSetID) inline explicit
Definition at line 179 of file MeshConstraints.h.
References bCanMove, bCannotDelete, FixedSetID, InvalidSetID, and Target.
Member Function Documentation
CombineConstraint()
void UE::Geometry::FVertexConstraint::CombineConstraint (const FVertexConstraint & OtherConstraint) inline
Combine the incoming constraint with this constraint.
The combination cannot be less restrictive than the existing constraint.
Definition at line 202 of file MeshConstraints.h.
References FVertexConstraint(), bCanMove, bCannotDelete, and Target.
FullyConstrained()
FVertexConstraint UE::Geometry::FVertexConstraint::FullyConstrained () inline static
Returns
a fully constrained vertex: can't delete and can't move
Definition at line 195 of file MeshConstraints.h.
References FVertexConstraint().
Referenced by UE::Geometry::FMeshConstraintsUtil::ConstrainSeams(), UE::Geometry::FMeshConstraintsUtil::FullyConstrainEdges(), and UE::Geometry::FMeshConstraintsUtil::FullyConstrainEdges().
IsUnconstrained()
bool UE::Geometry::FVertexConstraint::IsUnconstrained () const inline
Definition at line 186 of file MeshConstraints.h.
References bCanMove, bCannotDelete, and Target.
PermanentMovable()
FVertexConstraint UE::Geometry::FVertexConstraint::PermanentMovable () inline static
Returns
a movable but not "delete-able" vertex constraint
Definition at line 198 of file MeshConstraints.h.
References FVertexConstraint().
Unconstrained()
FVertexConstraint UE::Geometry::FVertexConstraint::Unconstrained () inline static
Returns
an unconstrained vertex constraint (ie not constrained at all)
Definition at line 192 of file MeshConstraints.h.
References FVertexConstraint().
Referenced by UE::Geometry::FMeshConstraints::GetVertexConstraint(), and UE::Geometry::FMeshRefinerBase::GetVertexConstraint().
Field Documentation
bCanMove
bool UE::Geometry::FVertexConstraint::bCanMove
Can this vertex be moved.
Definition at line 154 of file MeshConstraints.h.
Referenced by FVertexConstraint(), FVertexConstraint(), FVertexConstraint(), CombineConstraint(), IsUnconstrained(), and UE::Geometry::FMeshRefinerBase::IsVertexPositionConstrained().
bCannotDelete
bool UE::Geometry::FVertexConstraint::bCannotDelete
Is this vertex permanent (i.e.
cannot be removed by topology-change operations).
Definition at line 151 of file MeshConstraints.h.
Referenced by FVertexConstraint(), FVertexConstraint(), FVertexConstraint(), CombineConstraint(), and IsUnconstrained().
FixedSetID
int UE::Geometry::FVertexConstraint::FixedSetID
Vertices marked as "CannotDelete" but sharing the same FixedSetID can optionally be collapsed together (ie in Remesher)
Definition at line 157 of file MeshConstraints.h.
Referenced by FVertexConstraint(), FVertexConstraint(), and FVertexConstraint().
InvalidSetID
int UE::Geometry::FVertexConstraint::InvalidSetID = -1 static constexpr
value for FixedSetID that is treated as not-a-fixed-set-ID by various functions (ie don't use this value yourself)
Definition at line 160 of file MeshConstraints.h.
Referenced by FVertexConstraint(), FVertexConstraint(), and FVertexConstraint().
Target
IProjectionTarget* UE::Geometry::FVertexConstraint::Target
Vertex is associated with this ProjectionTarget, and should be projected onto it (ie in Remesher)
Definition at line 163 of file MeshConstraints.h.
Referenced by FVertexConstraint(), FVertexConstraint(), FVertexConstraint(), CombineConstraint(), IsUnconstrained(), and UE::Geometry::FMeshRefinerBase::IsVertexPositionConstrained().
The documentation for this struct was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/GeometryProcessing/Source/DynamicMesh/Public/MeshConstraints.h