Unreal Engine 5.6 C++ API: FFormatArgsTrace Struct Reference
FFormatArgsTrace Struct Reference
#include "FormatArgsTrace.h"
Data Structures
struct TIsStringArgument
Public Types
enum EFormatArgTypeCode {
FormatArgTypeCode_CategoryBitShift = 6 , FormatArgTypeCode_SizeBitMask = (1 << FormatArgTypeCode_CategoryBitShift) - 1 , FormatArgTypeCode_CategoryBitMask = ~FormatArgTypeCode_SizeBitMask , FormatArgTypeCode_CategoryInteger = 1 << FormatArgTypeCode_CategoryBitShift ,
FormatArgTypeCode_CategoryFloatingPoint = 2 << FormatArgTypeCode_CategoryBitShift , FormatArgTypeCode_CategoryString = 3 << FormatArgTypeCode_CategoryBitShift
}
template<int InlineSize>
using TBufferWithOverflow = TArray<uint8, TInlineAllocator<InlineSize>>
Static Public Member Functions
template<int BufferSize, typename... Types>
static uint16 EncodeArguments (uint8(&Buffer)[BufferSize], Types... FormatArgs)
template<typename BufferType, typename... Types>
static int32 EncodeArgumentsWithArray (BufferType &Array, Types... FormatArgs)
Static Private Member Functions
template<typename T>
static void EncodeArgumentInternal (uint8 *&TypeCodesPtr, uint8 *&PayloadPtr, T Argument)
template<typename T, typename... Types>
static void EncodeArgumentsInternal (uint8 *&ArgDescriptorsPtr, uint8 *&ArgPayloadPtr, T Head, Types... Tail)
static constexpr void EncodeArgumentsInternal (uint8 *&TypeCodesPtr, uint8 *&PayloadPtr)
template<typename T, typename CharType = std::remove_cv_t<typename TRemovePointer<T>::Type>>
static constexpr uint64 GetArgumentEncodedSize (T Argument)
static constexpr uint64 GetArgumentsEncodedSize ()
template<typename T, typename... Types>
static uint64 GetArgumentsEncodedSize (T Head, Types... Tail)
Detailed Description
Definition at line 14 of file FormatArgsTrace.h.
Member Typedef Documentation
TBufferWithOverflow
template<int InlineSize> using FFormatArgsTrace::TBufferWithOverflow = TArray<uint8, TInlineAllocator<InlineSize>>
Definition at line 28 of file FormatArgsTrace.h.
Member Enumeration Documentation
EFormatArgTypeCode
enum FFormatArgsTrace::EFormatArgTypeCode
Enumerator
FormatArgTypeCode_CategoryBitShift
FormatArgTypeCode_SizeBitMask
FormatArgTypeCode_CategoryBitMask
FormatArgTypeCode_CategoryInteger
FormatArgTypeCode_CategoryFloatingPoint
FormatArgTypeCode_CategoryString
Definition at line 16 of file FormatArgsTrace.h.
Member Function Documentation
EncodeArgumentInternal()
template<typename T> void FFormatArgsTrace::EncodeArgumentInternal (uint8 *& TypeCodesPtr, uint8 *& PayloadPtr, T Argument) inline static private
Definition at line 111 of file FormatArgsTrace.h.
References FormatArgTypeCode_CategoryFloatingPoint, FormatArgTypeCode_CategoryInteger, FormatArgTypeCode_CategoryString, FMath::Min, TCString< T >::Strlen(), UNLIKELY, and FFormatArgsTrace::TIsStringArgument< T >::Value.
Referenced by EncodeArgumentsInternal().
EncodeArguments()
template<int BufferSize, typename... Types> uint16 FFormatArgsTrace::EncodeArguments (uint8(&) Buffer[BufferSize], Types... FormatArgs) inline static
Definition at line 49 of file FormatArgsTrace.h.
References Buffer, check, EncodeArgumentsInternal(), and GetArgumentsEncodedSize().
EncodeArgumentsInternal() [1/2]
template<typename T, typename... Types> void FFormatArgsTrace::EncodeArgumentsInternal (uint8 *& ArgDescriptorsPtr, uint8 *& ArgPayloadPtr, T Head, Types... Tail) inline static private
Definition at line 167 of file FormatArgsTrace.h.
References EncodeArgumentInternal(), and EncodeArgumentsInternal().
EncodeArgumentsInternal() [2/2]
constexpr void FFormatArgsTrace::EncodeArgumentsInternal (uint8 *& TypeCodesPtr, uint8 *& PayloadPtr) inline static constexpr private
Definition at line 162 of file FormatArgsTrace.h.
Referenced by EncodeArguments(), EncodeArgumentsInternal(), and EncodeArgumentsWithArray().
EncodeArgumentsWithArray()
template<typename BufferType, typename... Types> int32 FFormatArgsTrace::EncodeArgumentsWithArray (BufferType & Array, Types... FormatArgs) inline static
Definition at line 32 of file FormatArgsTrace.h.
References Array, Buffer, check, EncodeArgumentsInternal(), and GetArgumentsEncodedSize().
GetArgumentEncodedSize()
template<typename T, typename CharType = std::remove_cv_t<typename TRemovePointer<T>::Type>> constexpr uint64 FFormatArgsTrace::GetArgumentEncodedSize (T Argument) inline static constexpr private
Definition at line 80 of file FormatArgsTrace.h.
References FMath::Min, TCString< T >::Strlen(), and FFormatArgsTrace::TIsStringArgument< T >::Value.
Referenced by GetArgumentsEncodedSize().
GetArgumentsEncodedSize() [1/2]
constexpr uint64 FFormatArgsTrace::GetArgumentsEncodedSize () inline static constexpr private
Definition at line 99 of file FormatArgsTrace.h.
Referenced by EncodeArguments(), EncodeArgumentsWithArray(), and GetArgumentsEncodedSize().
GetArgumentsEncodedSize() [2/2]
template<typename T, typename... Types> uint64 FFormatArgsTrace::GetArgumentsEncodedSize (T Head, Types... Tail) inline static private
Definition at line 105 of file FormatArgsTrace.h.
References GetArgumentEncodedSize(), and GetArgumentsEncodedSize().
The documentation for this struct was generated from the following file:
Runtime/Core/Public/ProfilingDebugging/FormatArgsTrace.h