Unreal Engine 5.6 C++ API: UE::MovieScene::FComplexInclusivityFilter Struct Reference
UE::MovieScene::FComplexInclusivityFilter Struct Reference
Filter used for specifying more complex mutual inclusivity rules that depend on more than one component type.
#include "MovieSceneMutualComponentInclusivity.h"
Public Member Functions
FComplexInclusivityFilter (const FComponentMask &InMask, EComplexInclusivityFilterMode InMode)
UE_DEPRECATED (5.2, "This function will no longer be called") bool Match(FComponentMask Input) const
Static Public Member Functions
static FComplexInclusivityFilter All (std::initializer_list< FComponentTypeID > InComponentTypes)
static FComplexInclusivityFilter Any (std::initializer_list< FComponentTypeID > InComponentTypes)
Data Fields
FComponentMask Mask
The component mask defining the set of components to test for.
EComplexInclusivityFilterMode Mode
The filter mode used for matching.
Friends
uint32 GetTypeHash (const FComplexInclusivityFilter &Filter)
bool operator== (const FComplexInclusivityFilter &A, const FComplexInclusivityFilter &B)
Detailed Description
Filter used for specifying more complex mutual inclusivity rules that depend on more than one component type.
Definition at line 43 of file MovieSceneMutualComponentInclusivity.h.
Constructor & Destructor Documentation
FComplexInclusivityFilter()
UE::MovieScene::FComplexInclusivityFilter::FComplexInclusivityFilter (const FComponentMask & InMask, EComplexInclusivityFilterMode InMode) inline
Definition at line 50 of file MovieSceneMutualComponentInclusivity.h.
References Mask, and Mode.
Referenced by All(), Any(), GetTypeHash, and operator==.
Member Function Documentation
All()
FComplexInclusivityFilter UE::MovieScene::FComplexInclusivityFilter::All (std::initializer_list< FComponentTypeID > InComponentTypes) inline static
Definition at line 64 of file MovieSceneMutualComponentInclusivity.h.
References FComplexInclusivityFilter(), and UE::MovieScene::AllOf.
Any()
FComplexInclusivityFilter UE::MovieScene::FComplexInclusivityFilter::Any (std::initializer_list< FComponentTypeID > InComponentTypes) inline static
Definition at line 69 of file MovieSceneMutualComponentInclusivity.h.
References FComplexInclusivityFilter(), and UE::MovieScene::AnyOf.
UE_DEPRECATED()
UE::MovieScene::FComplexInclusivityFilter::UE_DEPRECATED (5. 2, "This function will no longer be called") const inline
Definition at line 74 of file MovieSceneMutualComponentInclusivity.h.
References UE::MovieScene::AllOf, UE::MovieScene::AnyOf, bool, checkf, UE::MovieScene::FComponentMask::CombineWithBitwiseAND(), UE::MovieScene::FComponentMask::Find(), INDEX_NONE, Input, MaintainSize, Mask, Match, Mode, and TEXT.
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FComplexInclusivityFilter & Filter) friend
Definition at line 54 of file MovieSceneMutualComponentInclusivity.h.
References FComplexInclusivityFilter(), Filter, GetTypeHash, and HashCombine().
Referenced by GetTypeHash.
operator==
bool operator== (const FComplexInclusivityFilter & A, const FComplexInclusivityFilter & B) friend
Definition at line 59 of file MovieSceneMutualComponentInclusivity.h.
References FComplexInclusivityFilter(), A, and B.
Field Documentation
Mask
FComponentMask UE::MovieScene::FComplexInclusivityFilter::Mask
The component mask defining the set of components to test for.
Definition at line 46 of file MovieSceneMutualComponentInclusivity.h.
Referenced by FComplexInclusivityFilter(), and UE_DEPRECATED().
Mode
EComplexInclusivityFilterMode UE::MovieScene::FComplexInclusivityFilter::Mode
The filter mode used for matching.
Definition at line 48 of file MovieSceneMutualComponentInclusivity.h.
Referenced by FComplexInclusivityFilter(), and UE_DEPRECATED().
The documentation for this struct was generated from the following file:
Runtime/MovieScene/Public/EntitySystem/MovieSceneMutualComponentInclusivity.h