Unreal Engine 5.6 C++ API: UE::Tick::FActiveSyncPoint::FActiveSyncWork Struct Reference
UE::Tick::FActiveSyncPoint::FActiveSyncWork Struct Reference
Struct defining a unit of work that is executed as part of an FActiveSyncPoint.
Public Member Functions
FActiveSyncWork ()
FActiveSyncWork (const FActiveSyncWork &)=delete
~FActiveSyncWork ()
bool IsInitialized () const
FActiveSyncWork & operator= (const FActiveSyncWork &)=delete
void Reset ()
void SetTickFunction (FTickFunction *InTickFunction, bool bWasAllocatedInternally)
Data Fields
union {
struct {
uint32 bAllocatedTickFunction: 1
If true, the tick function allocated by this work and should be freed when reset.
uint32 bAlreadyExecuted: 1
If true, this work has completely finished executing this frame.
uint32 bCurrentlyExecuting: 1
If true, this work is in the middle of being executed and is in the ExecutingWork array.
uint32 bHasActiveHandle: 1
If true, this work corresponds to an active handle.
uint32 bLateWorkRequested: 1
If true, a late work request was created for this handle.
uint32 bRequestEveryFrame: 1
If true, work will be requested at the start of every frame.
uint32 bReserveEveryFrame: 1
If true, work will be reserved at the start of every frame.
uint32 bWorkRequested: 1
If true, this work can be executed this frame.
uint32 bWorkReserved: 1
If true, this work has been reserved for execution later in the frame.
}
uint32 StateValue
Default state of 0 means it can be reused immediately.
};
FTickFunction * TickFunction
Function to actually execute.
Detailed Description
Struct defining a unit of work that is executed as part of an FActiveSyncPoint.
Definition at line 525 of file TaskSyncManager.h.
Constructor & Destructor Documentation
FActiveSyncWork() [1/2]
UE::Tick::FActiveSyncPoint::FActiveSyncWork::FActiveSyncWork () inline
Definition at line 566 of file TaskSyncManager.h.
References StateValue, and TickFunction.
Referenced by FActiveSyncWork(), and operator=().
~FActiveSyncWork()
UE::Tick::FActiveSyncPoint::FActiveSyncWork::~FActiveSyncWork () inline
Definition at line 572 of file TaskSyncManager.h.
References bAllocatedTickFunction, and TickFunction.
FActiveSyncWork() [2/2]
UE::Tick::FActiveSyncPoint::FActiveSyncWork::FActiveSyncWork (const FActiveSyncWork &) delete
References FActiveSyncWork().
Member Function Documentation
IsInitialized()
bool UE::Tick::FActiveSyncPoint::FActiveSyncWork::IsInitialized () const inline
Definition at line 596 of file TaskSyncManager.h.
References StateValue.
operator=()
FActiveSyncWork & UE::Tick::FActiveSyncPoint::FActiveSyncWork::operator= (const FActiveSyncWork &) delete
References FActiveSyncWork().
Reset()
void UE::Tick::FActiveSyncPoint::FActiveSyncWork::Reset () inline
Definition at line 590 of file TaskSyncManager.h.
References SetTickFunction(), and StateValue.
SetTickFunction()
void UE::Tick::FActiveSyncPoint::FActiveSyncWork::SetTickFunction (FTickFunction * InTickFunction, bool bWasAllocatedInternally) inline
Definition at line 580 of file TaskSyncManager.h.
References bAllocatedTickFunction, and TickFunction.
Referenced by Reset().
Field Documentation
[union]
union { ... } UE::Tick::FActiveSyncPoint::FActiveSyncWork
bAllocatedTickFunction
uint32 UE::Tick::FActiveSyncPoint::FActiveSyncWork::bAllocatedTickFunction
If true, the tick function allocated by this work and should be freed when reset.
Definition at line 559 of file TaskSyncManager.h.
Referenced by ~FActiveSyncWork(), and SetTickFunction().
bAlreadyExecuted
uint32 UE::Tick::FActiveSyncPoint::FActiveSyncWork::bAlreadyExecuted
If true, this work has completely finished executing this frame.
Definition at line 553 of file TaskSyncManager.h.
bCurrentlyExecuting
uint32 UE::Tick::FActiveSyncPoint::FActiveSyncWork::bCurrentlyExecuting
If true, this work is in the middle of being executed and is in the ExecutingWork array.
Definition at line 550 of file TaskSyncManager.h.
bHasActiveHandle
uint32 UE::Tick::FActiveSyncPoint::FActiveSyncWork::bHasActiveHandle
If true, this work corresponds to an active handle.
Definition at line 535 of file TaskSyncManager.h.
bLateWorkRequested
uint32 UE::Tick::FActiveSyncPoint::FActiveSyncWork::bLateWorkRequested
If true, a late work request was created for this handle.
Definition at line 556 of file TaskSyncManager.h.
bRequestEveryFrame
uint32 UE::Tick::FActiveSyncPoint::FActiveSyncWork::bRequestEveryFrame
If true, work will be requested at the start of every frame.
Definition at line 547 of file TaskSyncManager.h.
bReserveEveryFrame
uint32 UE::Tick::FActiveSyncPoint::FActiveSyncWork::bReserveEveryFrame
If true, work will be reserved at the start of every frame.
Definition at line 544 of file TaskSyncManager.h.
bWorkRequested
uint32 UE::Tick::FActiveSyncPoint::FActiveSyncWork::bWorkRequested
If true, this work can be executed this frame.
Definition at line 541 of file TaskSyncManager.h.
bWorkReserved
uint32 UE::Tick::FActiveSyncPoint::FActiveSyncWork::bWorkReserved
If true, this work has been reserved for execution later in the frame.
Definition at line 538 of file TaskSyncManager.h.
StateValue
uint32 UE::Tick::FActiveSyncPoint::FActiveSyncWork::StateValue
Default state of 0 means it can be reused immediately.
Definition at line 530 of file TaskSyncManager.h.
Referenced by FActiveSyncWork(), IsInitialized(), and Reset().
TickFunction
FTickFunction* UE::Tick::FActiveSyncPoint::FActiveSyncWork::TickFunction
Function to actually execute.
Definition at line 564 of file TaskSyncManager.h.
Referenced by FActiveSyncWork(), ~FActiveSyncWork(), and SetTickFunction().
The documentation for this struct was generated from the following file:
Runtime/Engine/Public/TaskSyncManager.h