Unreal Engine 5.6 C++ API: FNetAsyncLoadDelinquencyAnalytics Struct Reference
FNetAsyncLoadDelinquencyAnalytics Struct Reference
Tracks data related specific to a NetDriver that can can result in prolonged periods of apparent network inactivity, despite actually receiving traffic.
#include "NetAnalyticsTypes.h"
Public Member Functions
FNetAsyncLoadDelinquencyAnalytics ()
FNetAsyncLoadDelinquencyAnalytics (const FNetAsyncLoadDelinquencyAnalytics &)=delete
FNetAsyncLoadDelinquencyAnalytics (const uint32 NumberOfTopOffendersToTrack)
FNetAsyncLoadDelinquencyAnalytics (FNetAsyncLoadDelinquencyAnalytics &&Other)
void CountBytes (FArchive &Ar) const
const FNetAsyncLoadDelinquencyAnalytics & operator= (const FNetAsyncLoadDelinquencyAnalytics &)=delete
FNetAsyncLoadDelinquencyAnalytics & operator= (FNetAsyncLoadDelinquencyAnalytics &&)=default
void Reset ()
Data Fields
FDelinquencyAnalytics DelinquentAsyncLoads
uint32 MaxConcurrentAsyncLoads
Detailed Description
Tracks data related specific to a NetDriver that can can result in prolonged periods of apparent network inactivity, despite actually receiving traffic.
This includes things like Pending Async Loads.
Also
See also
FConnectionDelinquencyAnalytics and FDelinquencyAnalytics.
Definition at line 132 of file NetAnalyticsTypes.h.
Constructor & Destructor Documentation
FNetAsyncLoadDelinquencyAnalytics() [1/4]
FNetAsyncLoadDelinquencyAnalytics::FNetAsyncLoadDelinquencyAnalytics () inline
Definition at line 134 of file NetAnalyticsTypes.h.
References DelinquentAsyncLoads, and MaxConcurrentAsyncLoads.
Referenced by FNetAsyncLoadDelinquencyAnalytics(), FNetAsyncLoadDelinquencyAnalytics(), operator=(), and operator=().
FNetAsyncLoadDelinquencyAnalytics() [2/4]
FNetAsyncLoadDelinquencyAnalytics::FNetAsyncLoadDelinquencyAnalytics (const uint32 NumberOfTopOffendersToTrack) inline
Definition at line 140 of file NetAnalyticsTypes.h.
References DelinquentAsyncLoads, and MaxConcurrentAsyncLoads.
FNetAsyncLoadDelinquencyAnalytics() [3/4]
FNetAsyncLoadDelinquencyAnalytics::FNetAsyncLoadDelinquencyAnalytics (FNetAsyncLoadDelinquencyAnalytics && Other) inline
Definition at line 146 of file NetAnalyticsTypes.h.
References FNetAsyncLoadDelinquencyAnalytics(), DelinquentAsyncLoads, MaxConcurrentAsyncLoads, MoveTemp(), and Other.
FNetAsyncLoadDelinquencyAnalytics() [4/4]
FNetAsyncLoadDelinquencyAnalytics::FNetAsyncLoadDelinquencyAnalytics (const FNetAsyncLoadDelinquencyAnalytics &) delete
References FNetAsyncLoadDelinquencyAnalytics().
Member Function Documentation
CountBytes()
void FNetAsyncLoadDelinquencyAnalytics::CountBytes (FArchive & Ar) const inline
Definition at line 156 of file NetAnalyticsTypes.h.
References Ar, and DelinquentAsyncLoads.
operator=() [1/2]
const FNetAsyncLoadDelinquencyAnalytics & FNetAsyncLoadDelinquencyAnalytics::operator= (const FNetAsyncLoadDelinquencyAnalytics &) delete
References FNetAsyncLoadDelinquencyAnalytics().
operator=() [2/2]
FNetAsyncLoadDelinquencyAnalytics & FNetAsyncLoadDelinquencyAnalytics::operator= (FNetAsyncLoadDelinquencyAnalytics &&) default
References FNetAsyncLoadDelinquencyAnalytics().
Reset()
void FNetAsyncLoadDelinquencyAnalytics::Reset () inline
Definition at line 161 of file NetAnalyticsTypes.h.
References DelinquentAsyncLoads, and MaxConcurrentAsyncLoads.
Field Documentation
DelinquentAsyncLoads
FDelinquencyAnalytics FNetAsyncLoadDelinquencyAnalytics::DelinquentAsyncLoads
Definition at line 167 of file NetAnalyticsTypes.h.
Referenced by FNetAsyncLoadDelinquencyAnalytics(), FNetAsyncLoadDelinquencyAnalytics(), FNetAsyncLoadDelinquencyAnalytics(), CountBytes(), and Reset().
MaxConcurrentAsyncLoads
uint32 FNetAsyncLoadDelinquencyAnalytics::MaxConcurrentAsyncLoads
Definition at line 168 of file NetAnalyticsTypes.h.
Referenced by FNetAsyncLoadDelinquencyAnalytics(), FNetAsyncLoadDelinquencyAnalytics(), FNetAsyncLoadDelinquencyAnalytics(), and Reset().
The documentation for this struct was generated from the following file:
Runtime/Engine/Public/Net/NetAnalyticsTypes.h