Unreal Engine 5.6 C++ API: FTypedElementCommonActionsElement Struct Reference
FTypedElementCommonActionsElement Struct Reference
Utility to hold a typed element handle and its associated world interface and common actions customization.
#include "TypedElementCommonActions.h"
Public Member Functions
FTypedElementCommonActionsElement ()=default
FTypedElementCommonActionsElement (const FTypedElementCommonActionsElement &)=default
FTypedElementCommonActionsElement (FTypedElementCommonActionsElement &&)=default
FTypedElementCommonActionsElement (TTypedElement< ITypedElementWorldInterface > InElementWorldHandle, FTypedElementCommonActionsCustomization *InCommonActionsCustomization)
FORCEINLINE bool IsSet () const
FORCEINLINE operator bool () const
FTypedElementCommonActionsElement & operator= (const FTypedElementCommonActionsElement &)=default
FTypedElementCommonActionsElement & operator= (FTypedElementCommonActionsElement &&)=default
Private Attributes
FTypedElementCommonActionsCustomization * CommonActionsCustomization = nullptr
TTypedElement< ITypedElementWorldInterface > ElementWorldHandle
Detailed Description
Utility to hold a typed element handle and its associated world interface and common actions customization.
Definition at line 34 of file TypedElementCommonActions.h.
Constructor & Destructor Documentation
FTypedElementCommonActionsElement() [1/4]
FTypedElementCommonActionsElement::FTypedElementCommonActionsElement () default
Referenced by FTypedElementCommonActionsElement(), FTypedElementCommonActionsElement(), operator=(), and operator=().
FTypedElementCommonActionsElement() [2/4]
FTypedElementCommonActionsElement::FTypedElementCommonActionsElement (TTypedElement< ITypedElementWorldInterface > InElementWorldHandle, FTypedElementCommonActionsCustomization * InCommonActionsCustomization) inline
Definition at line 39 of file TypedElementCommonActions.h.
References CommonActionsCustomization, ElementWorldHandle, and MoveTemp().
FTypedElementCommonActionsElement() [3/4]
FTypedElementCommonActionsElement::FTypedElementCommonActionsElement (const FTypedElementCommonActionsElement &) default
References FTypedElementCommonActionsElement().
FTypedElementCommonActionsElement() [4/4]
FTypedElementCommonActionsElement::FTypedElementCommonActionsElement (FTypedElementCommonActionsElement &&) default
References FTypedElementCommonActionsElement().
Member Function Documentation
IsSet()
FORCEINLINE bool FTypedElementCommonActionsElement::IsSet () const inline
Definition at line 56 of file TypedElementCommonActions.h.
References CommonActionsCustomization, ElementWorldHandle, and FORCEINLINE.
Referenced by operator bool().
operator bool()
FORCEINLINE FTypedElementCommonActionsElement::operator bool () const inline explicit
Definition at line 51 of file TypedElementCommonActions.h.
References FORCEINLINE, and IsSet().
operator=() [1/2]
FTypedElementCommonActionsElement & FTypedElementCommonActionsElement::operator= (const FTypedElementCommonActionsElement &) default
References FTypedElementCommonActionsElement().
operator=() [2/2]
FTypedElementCommonActionsElement & FTypedElementCommonActionsElement::operator= (FTypedElementCommonActionsElement &&) default
References FTypedElementCommonActionsElement().
Field Documentation
CommonActionsCustomization
FTypedElementCommonActionsCustomization* FTypedElementCommonActionsElement::CommonActionsCustomization = nullptr private
Definition at line 66 of file TypedElementCommonActions.h.
Referenced by FTypedElementCommonActionsElement(), and IsSet().
ElementWorldHandle
TTypedElement<ITypedElementWorldInterface> FTypedElementCommonActionsElement::ElementWorldHandle private
Definition at line 65 of file TypedElementCommonActions.h.
Referenced by FTypedElementCommonActionsElement(), and IsSet().
The documentation for this struct was generated from the following file:
Runtime/Engine/Public/Elements/Framework/TypedElementCommonActions.h