Unreal Engine 5.6 C++ API: FNavPathPoint Struct Reference
FNavPathPoint Struct Reference
Describes node in navigation path.
#include "NavigationTypes.h"
Public Member Functions
FNavPathPoint ()
PRAGMA_DISABLE_DEPRECATION_WARNINGS FNavPathPoint (const FNavPathPoint &)=default
FNavPathPoint (const FVector &InLocation, NavNodeRef InNodeRef=NavNodeRef(0), uint32 InFlags=0)
FNavPathPoint (FNavPathPoint &&Other)=default
FNavPathPoint & operator= (const FNavPathPoint &Other)=default
FNavPathPoint & operator= (FNavPathPoint &&Other)=default
PRAGMA_ENABLE_DEPRECATION_WARNINGS bool operator== (const FNavPathPoint &Other) const
UE_DEPRECATED (5.3, "Use CustomNavLinkId instead. This id is no longer used in the engine.") uint32 CustomLinkId
Public Member Functions inherited from FNavLocation
FNavLocation ()
FNavLocation (const FVector &InLocation, NavNodeRef InNodeRef=NavNodeRef(0))
FORCEINLINE bool HasNodeRef () const
checks if location has associated navigation node ref
FORCEINLINE operator FVector () const
bool operator== (const FNavLocation &Other) const
Data Fields
FNavLinkId CustomNavLinkId
unique Id of custom navigation link starting at this point
uint32 Flags
extra node flags
Data Fields inherited from FNavLocation
FVector Location
location relative to path's base
NavNodeRef NodeRef
node reference in navigation data
Detailed Description
Describes node in navigation path.
Definition at line 275 of file NavigationTypes.h.
Constructor & Destructor Documentation
FNavPathPoint() [1/4]
FNavPathPoint::FNavPathPoint () inline
Definition at line 286 of file NavigationTypes.h.
References FNavPathPoint(), Flags, PRAGMA_DISABLE_DEPRECATION_WARNINGS, and PRAGMA_ENABLE_DEPRECATION_WARNINGS.
Referenced by FNavPathPoint(), FNavPathPoint(), FNavPathPoint(), operator=(), operator=(), and operator==().
FNavPathPoint() [2/4]
FNavPathPoint::FNavPathPoint (const FVector & InLocation, NavNodeRef InNodeRef = NavNodeRef(0), uint32 InFlags = 0) inline
Definition at line 293 of file NavigationTypes.h.
References FNavLocation::FNavLocation(), Flags, FVector, INVALID_NAVNODEREF, PRAGMA_DISABLE_DEPRECATION_WARNINGS, and PRAGMA_ENABLE_DEPRECATION_WARNINGS.
FNavPathPoint() [3/4]
PRAGMA_DISABLE_DEPRECATION_WARNINGS FNavPathPoint::FNavPathPoint (const FNavPathPoint &) default
References FNavPathPoint().
FNavPathPoint() [4/4]
FNavPathPoint::FNavPathPoint (FNavPathPoint && Other) default
References FNavPathPoint(), and Other.
Member Function Documentation
operator=() [1/2]
FNavPathPoint & FNavPathPoint::operator= (const FNavPathPoint & Other) default
References FNavPathPoint(), and Other.
operator=() [2/2]
FNavPathPoint & FNavPathPoint::operator= (FNavPathPoint && Other) default
References FNavPathPoint(), Other, and PRAGMA_ENABLE_DEPRECATION_WARNINGS.
operator==()
PRAGMA_ENABLE_DEPRECATION_WARNINGS bool FNavPathPoint::operator== (const FNavPathPoint & Other) const inline
Definition at line 308 of file NavigationTypes.h.
References FNavPathPoint(), CustomNavLinkId, Flags, FNavLocation::operator==(), and Other.
UE_DEPRECATED()
FNavPathPoint::UE_DEPRECATED (5. 3, "Use CustomNavLinkId instead. This id is no longer used in the engine.")
Field Documentation
CustomNavLinkId
FNavLinkId FNavPathPoint::CustomNavLinkId
unique Id of custom navigation link starting at this point
Definition at line 284 of file NavigationTypes.h.
Referenced by operator==().
Flags
uint32 FNavPathPoint::Flags
extra node flags
Definition at line 278 of file NavigationTypes.h.
Referenced by FNavPathPoint(), FNavPathPoint(), and operator==().
The documentation for this struct was generated from the following file:
Runtime/Engine/Classes/AI/Navigation/NavigationTypes.h