Unreal Engine 5.6 C++ API: FAndroidTime Struct Reference
FAndroidTime Struct Reference
Android implementation of the Time OS functions.
#include "AndroidPlatformTime.h"
Static Public Member Functions
static FORCEINLINE uint32 Cycles ()
static FORCEINLINE uint64 Cycles64 ()
static FORCEINLINE double Seconds ()
Static Public Member Functions inherited from FGenericPlatformTime
static void AutoUpdateGameThreadCPUTime (double UpdateInterval)
Registers automatic updates of Game Thread CPU utilization.
static FCPUTime GetCPUTime ()
static double GetLastIntervalCPUTimeInSeconds ()
static double GetLastIntervalThreadCPUTimeInSeconds ()
Gets the per-thread CPU processing time (kernel + user) from the last update.
static double GetSecondsPerCycle ()
Each platform implements these two functions, which return the current time in platform-specific cpu cycles.
static double GetSecondsPerCycle64 ()
Returns seconds per cycle, to pair with Cycles64().
static FCPUTime GetThreadCPUTime ()
Gets current threads CPU Utilization.
static FString PrettyTime (double Seconds)
Returns a pretty-string for a time given in seconds.
static uint64 SecondsToCycles64 (double Seconds)
Convert seconds to cycles, can be added to Cycles64 to set a high resolution timeout.
static TCHAR * StrDate (TCHAR *Dest, SIZE_T DestSize)
Get the system date.
static TCHAR * StrTime (TCHAR *Dest, SIZE_T DestSize)
Get the system time.
static const TCHAR * StrTimestamp ()
Returns a timestamp string built from the current date and time.
static float ToMilliseconds (const uint32 Cycles)
Converts cycles to milliseconds.
static double ToMilliseconds64 (const uint64 Cycles)
Converts 64 bit cycles to milliseconds.
static float ToSeconds (const uint32 Cycles)
Converts cycles to seconds.
static double ToSeconds64 (const uint64 Cycles)
Converts 64 bit cycles to seconds.
static bool UpdateCPUTime (float DeltaTime)
Updates CPU utilization, called through a delegate from the Core ticker.
static bool UpdateThreadCPUTime (float=0.0)
Updates current thread CPU utilization, calling is user defined per-thread (unused float parameter, is for FTicker compatibility).
Additional Inherited Members
Static Protected Attributes inherited from FGenericPlatformTime
static double LastIntervalCPUTimeInSeconds
static double SecondsPerCycle
static double SecondsPerCycle64
Detailed Description
Android implementation of the Time OS functions.
Definition at line 17 of file AndroidPlatformTime.h.
Member Function Documentation
Cycles()
FORCEINLINE uint32 FAndroidTime::Cycles () inline static
Definition at line 27 of file AndroidPlatformTime.h.
References FORCEINLINE.
Referenced by TScopedDurationThreadSafeTimer< FThreadSafeCounter >::~TScopedDurationThreadSafeTimer(), FInGameCycleCounter::Begin(), FInGameCycleCounter::End(), FRandomStream::Initialize(), and LowLevelTasks::Private::TLocalQueueRegistry< NumLocalItems, MaxLocalQueues >::Rand().
Cycles64()
FORCEINLINE uint64 FAndroidTime::Cycles64 () inline static
Definition at line 34 of file AndroidPlatformTime.h.
References FORCEINLINE.
Referenced by FScopedCookStat::FScopedCookStat(), FParticlePerfStatScope< TWriterFunc >::~FParticlePerfStatScope(), FScopedCookStat::~FScopedCookStat(), FCookStats::FScopedStatsCounter::~FScopedStatsCounter(), UE::FTimeout::AlwaysExpired(), UE::FIoFileBlockRequestQueue::GetByOffset(), Audio::FQuartzLatencyTimer::GetCurrentTimePassedMs(), UE::FTimeout::GetElapsedSeconds(), UE::FTimeout::IsExpired(), UE::FTimeout::Never(), UE::Insights::FStopwatch::Restart(), UE::Insights::FStopwatch::Start(), Audio::FQuartzLatencyTimer::StartTimer(), UE::Insights::FStopwatch::Stop(), Audio::FQuartzLatencyTimer::StopTimer(), and UE::Insights::FStopwatch::Update().
Seconds()
FORCEINLINE double FAndroidTime::Seconds () inline static
Definition at line 20 of file AndroidPlatformTime.h.
References FORCEINLINE.
Referenced by FReplayHelper::FCheckpointStepHelper::FCheckpointStepHelper(), FTransitionEvent::FTransitionEvent(), FReplayHelper::FCheckpointStepHelper::~FCheckpointStepHelper(), FScopedDurationTimeCustomLogger< Func >::~FScopedDurationTimeCustomLogger(), FScopedSwitchedDurationTimer::~FScopedSwitchedDurationTimer(), FSimpleScopeSecondsCounter::~FSimpleScopeSecondsCounter(), FLoggedPlatformFile::CopyFile(), FLoggedPlatformFile::CreateDirectory(), FLoggedPlatformFile::DeleteDirectory(), FLoggedPlatformFile::DeleteDirectoryRecursively(), FLoggedPlatformFile::DeleteFile(), FLoggedPlatformFile::DirectoryExists(), ENUM_CLASS_FLAGS(), FLoggedPlatformFile::FileExists(), FLoggedPlatformFile::FileSize(), FFeedbackContext::FinalizeSlowTask(), FCompilerResultsLog::FCompilerEvent::Finish(), FLoggedFileHandle::Flush(), FMallocBinnedCommonUtils::FlushCurrentThreadCache(), FLoggedPlatformFile::GetAccessTimeStamp(), FLoggedPlatformFile::GetFilenameOnDisk(), FTransitionEvent::GetRemainingTime(), FLoggedPlatformFile::GetStatData(), FLoggedPlatformFile::GetTimeStamp(), FLoggedPlatformFile::IsReadOnly(), FLoggedPlatformFile::IterateDirectory(), FLoggedPlatformFile::IterateDirectoryRecursively(), FLoggedPlatformFile::IterateDirectoryStat(), FLoggedPlatformFile::IterateDirectoryStatRecursively(), FRPCDoSDetection::LightweightReceivedRPC(), UE::MediaIO::LogThrottle(), FLoggedPlatformFile::MoveFile(), FRPCDoSDetection::NotifyReceivedRPC(), FLoggedPlatformFile::OpenAsyncRead(), FLoggedPlatformFile::OpenRead(), FLoggedPlatformFile::OpenWrite(), FRPCDoSDetection::PostReceivedRPC(), FLoggedFileHandle::Read(), FLoggedFileHandle::ReadAt(), FLoggedFileHandle::Seek(), FLoggedFileHandle::SeekFromEnd(), FLoggedPlatformFile::SetReadOnly(), FLoggedPlatformFile::SetTimeStamp(), FLoggedFileHandle::ShrinkBuffers(), FLoggedFileHandle::Size(), FCompilerResultsLog::FCompilerEvent::Start(), FDurationAtomicTimer::Start(), FDurationTimer::Start(), FScopedSwitchedDurationTimer::Start(), FFeedbackContext::StartSlowTask(), FDurationAtomicTimer::Stop(), FDurationTimer::Stop(), FLoggedFileHandle::Tell(), TAsyncTreeDifferences< InNodeType >::Tick(), FCachedLandscapeFoliage::FGrassComp::Touch(), FLoggedFileHandle::Truncate(), FAudioDevice::UpdateDeviceDeltaTime(), FLoggedPlatformFile::FLogStatVisitor::Visit(), FLoggedPlatformFile::FLogVisitor::Visit(), and FLoggedFileHandle::Write().
The documentation for this struct was generated from the following file:
Runtime/Core/Public/Android/AndroidPlatformTime.h