Unreal Engine 5.6 C++ API: FMovieSceneClipboardKey::TKey< T > Struct Template Reference
FMovieSceneClipboardKey::TKey< T > Struct Template Reference
Implementation of any key-value type.
Public Member Functions
TKey (T InValue)
virtual void CopyTo (TInlineValue< IKey, 64 > &OutDest) const
Copy this value to another destination ptr.
virtual FConversionFunction * FindConversionTo (FName DestinationTypeName) const
Find a conversion from this type to the specified destination type.
virtual FName GetTypeName () const
Get the name of this value type.
Public Member Functions inherited from FMovieSceneClipboardKey::IKey
virtual ~IKey ()
Data Fields
T Value
The actual value.
Detailed Description
template<typename T>
struct FMovieSceneClipboardKey::TKey< T >
Implementation of any key-value type.
Definition at line 129 of file MovieSceneClipboard.h.
Constructor & Destructor Documentation
TKey()
template<typename T> FMovieSceneClipboardKey::TKey< T >::TKey (T InValue) inline
Definition at line 131 of file MovieSceneClipboard.h.
References MoveTemp(), and Value.
Referenced by CopyTo().
Member Function Documentation
CopyTo()
template<typename T> virtual void FMovieSceneClipboardKey::TKey< T >::CopyTo (TInlineValue< IKey, 64 > & OutDest) const inline virtual
Copy this value to another destination ptr.
Implements FMovieSceneClipboardKey::IKey.
Definition at line 151 of file MovieSceneClipboard.h.
References TKey(), and Value.
FindConversionTo()
template<typename T> virtual FConversionFunction * FMovieSceneClipboardKey::TKey< T >::FindConversionTo (FName DestinationTypeName) const inline virtual
Find a conversion from this type to the specified destination type.
Implements FMovieSceneClipboardKey::IKey.
Definition at line 134 of file MovieSceneClipboard.h.
References FMovieSceneClipboardKey::ConversionMap, TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Find(), and MovieSceneClipboard::GetKeyTypeName().
GetTypeName()
template<typename T> virtual FName FMovieSceneClipboardKey::TKey< T >::GetTypeName () const inline virtual
Get the name of this value type.
Implements FMovieSceneClipboardKey::IKey.
Definition at line 145 of file MovieSceneClipboard.h.
References MovieSceneClipboard::GetKeyTypeName().
Field Documentation
Value
template<typename T> T FMovieSceneClipboardKey::TKey< T >::Value
The actual value.
Definition at line 157 of file MovieSceneClipboard.h.
Referenced by TKey(), CopyTo(), FMovieSceneClipboardKey::DefineConversion(), and FMovieSceneClipboardKey::TryGetValue().
The documentation for this struct was generated from the following file:
Runtime/MovieScene/Public/MovieSceneClipboard.h