Unreal Engine 5.6 C++ API: FRigVMNameOp Struct Reference
FRigVMNameOp Struct Reference
#include "RigVMNameCache.h"
Public Member Functions
FRigVMNameOp ()
bool operator!= (const FRigVMNameOp &Other) const
bool operator< (const FRigVMNameOp &Other) const
bool operator== (const FRigVMNameOp &Other) const
bool operator> (const FRigVMNameOp &Other) const
Static Public Member Functions
static RIGVM_API FRigVMNameOp Concat (const FName &InA, const FName &InB)
static RIGVM_API FRigVMNameOp Contains (const FName &InA, const FName &InB, const ESearchCase::Type InSearchCase)
static RIGVM_API FRigVMNameOp EndsWith (const FName &InA, const FName &InB, const ESearchCase::Type InSearchCase)
static uint32 GetTypeHash (const FName &InName)
static RIGVM_API FRigVMNameOp Left (const FName &InA, const uint32 InCount)
static RIGVM_API FRigVMNameOp LeftChop (const FName &InA, const uint32 InCount)
static RIGVM_API FRigVMNameOp Replace (const FName &InA, const FName &InB, const FName &InC, const ESearchCase::Type InSearchCase)
static RIGVM_API FRigVMNameOp Right (const FName &InA, const uint32 InCount)
static RIGVM_API FRigVMNameOp RightChop (const FName &InA, const uint32 InCount)
static RIGVM_API FRigVMNameOp StartsWith (const FName &InA, const FName &InB, const ESearchCase::Type InSearchCase)
Private Attributes
uint32 A
uint32 B
uint32 C
ERigVMNameOp Type
Friends
uint32 GetTypeHash (const FRigVMNameOp &Op)
Detailed Description
Definition at line 25 of file RigVMNameCache.h.
Constructor & Destructor Documentation
FRigVMNameOp()
FRigVMNameOp::FRigVMNameOp () inline
Definition at line 29 of file RigVMNameCache.h.
References A, B, C, INDEX_NONE, None, and Type.
Referenced by Concat(), Contains(), EndsWith(), GetTypeHash, Left(), LeftChop(), operator!=(), operator<(), operator==(), operator>(), Replace(), Right(), RightChop(), and StartsWith().
Member Function Documentation
Concat()
RIGVM_API FRigVMNameOp FRigVMNameOp::Concat (const FName & InA, const FName & InB) static
References FRigVMNameOp().
Contains()
RIGVM_API FRigVMNameOp FRigVMNameOp::Contains (const FName & InA, const FName & InB, const ESearchCase::Type InSearchCase) static
References FRigVMNameOp().
EndsWith()
RIGVM_API FRigVMNameOp FRigVMNameOp::EndsWith (const FName & InA, const FName & InB, const ESearchCase::Type InSearchCase) static
References FRigVMNameOp().
GetTypeHash()
uint32 FRigVMNameOp::GetTypeHash (const FName & InName) inline static
Definition at line 36 of file RigVMNameCache.h.
References HashCombine(), and InName.
Left()
RIGVM_API FRigVMNameOp FRigVMNameOp::Left (const FName & InA, const uint32 InCount) static
References FRigVMNameOp().
LeftChop()
RIGVM_API FRigVMNameOp FRigVMNameOp::LeftChop (const FName & InA, const uint32 InCount) static
References FRigVMNameOp().
operator!=()
bool FRigVMNameOp::operator!= (const FRigVMNameOp & Other) const inline
Definition at line 61 of file RigVMNameCache.h.
References FRigVMNameOp(), A, B, C, Other, and Type.
operator<()
bool FRigVMNameOp::operator< (const FRigVMNameOp & Other) const inline
Definition at line 66 of file RigVMNameCache.h.
References FRigVMNameOp(), A, B, C, Other, and Type.
operator==()
bool FRigVMNameOp::operator== (const FRigVMNameOp & Other) const inline
Definition at line 56 of file RigVMNameCache.h.
References FRigVMNameOp(), A, B, C, Other, and Type.
operator>()
bool FRigVMNameOp::operator> (const FRigVMNameOp & Other) const inline
Definition at line 83 of file RigVMNameCache.h.
References FRigVMNameOp(), A, B, C, Other, and Type.
Replace()
RIGVM_API FRigVMNameOp FRigVMNameOp::Replace (const FName & InA, const FName & InB, const FName & InC, const ESearchCase::Type InSearchCase) static
References FRigVMNameOp().
Right()
RIGVM_API FRigVMNameOp FRigVMNameOp::Right (const FName & InA, const uint32 InCount) static
References FRigVMNameOp().
RightChop()
RIGVM_API FRigVMNameOp FRigVMNameOp::RightChop (const FName & InA, const uint32 InCount) static
References FRigVMNameOp().
StartsWith()
RIGVM_API FRigVMNameOp FRigVMNameOp::StartsWith (const FName & InA, const FName & InB, const ESearchCase::Type InSearchCase) static
References FRigVMNameOp().
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FRigVMNameOp & Op) friend
Definition at line 51 of file RigVMNameCache.h.
References FRigVMNameOp(), A, B, C, HashCombine(), and Type.
Field Documentation
A
uint32 FRigVMNameOp::A private
Definition at line 103 of file RigVMNameCache.h.
Referenced by FRigVMNameOp(), GetTypeHash, operator!=(), operator<(), operator==(), and operator>().
B
uint32 FRigVMNameOp::B private
Definition at line 104 of file RigVMNameCache.h.
Referenced by FRigVMNameOp(), GetTypeHash, operator!=(), operator<(), operator==(), and operator>().
C
uint32 FRigVMNameOp::C private
Definition at line 105 of file RigVMNameCache.h.
Referenced by FRigVMNameOp(), GetTypeHash, operator!=(), operator<(), operator==(), and operator>().
Type
ERigVMNameOp FRigVMNameOp::Type private
Definition at line 106 of file RigVMNameCache.h.
Referenced by FRigVMNameOp(), GetTypeHash, operator!=(), operator<(), operator==(), and operator>().
The documentation for this struct was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/RigVM/Source/RigVM/Public/RigVMCore/RigVMNameCache.h