Unreal Engine 5.6 C++ API: FMaterialShaders Struct Reference
FMaterialShaders Struct Reference
#include "MaterialShaderType.h"
Public Member Functions
FMaterialShaders ()
template<typename ShaderType>
bool TryGetComputeShader (TShaderRef< ShaderType > &OutShader) const
template<typename ShaderType>
bool TryGetComputeShader (TShaderRef< ShaderType > *OutShader) const
template<typename ShaderType>
bool TryGetGeometryShader (TShaderRef< ShaderType > &OutShader) const
template<typename ShaderType>
bool TryGetGeometryShader (TShaderRef< ShaderType > *OutShader) const
template<typename ShaderType>
bool TryGetMeshShader (TShaderRef< ShaderType > &OutShader) const
template<typename ShaderType>
bool TryGetMeshShader (TShaderRef< ShaderType > *OutShader) const
bool TryGetPipeline (FShaderPipelineRef &OutPipeline) const
template<typename ShaderType>
bool TryGetPixelShader (TShaderRef< ShaderType > &OutShader) const
template<typename ShaderType>
bool TryGetPixelShader (TShaderRef< ShaderType > *OutShader) const
template<typename ShaderType>
bool TryGetShader (EShaderFrequency InFrequency, TShaderRef< ShaderType > &OutShader) const
template<typename ShaderType>
bool TryGetShader (EShaderFrequency InFrequency, TShaderRef< ShaderType > *OutShader) const
template<typename ShaderType>
bool TryGetVertexShader (TShaderRef< ShaderType > &OutShader) const
template<typename ShaderType>
bool TryGetVertexShader (TShaderRef< ShaderType > *OutShader) const
Data Fields
FShaderPipeline * Pipeline
const FShaderMapBase * ShaderMap
FShader * Shaders [SF_NumFrequencies]
Detailed Description
Definition at line 228 of file MaterialShaderType.h.
Constructor & Destructor Documentation
FMaterialShaders()
FMaterialShaders::FMaterialShaders () inline
Definition at line 234 of file MaterialShaderType.h.
References FMemory::Memzero(), Pipeline, ShaderMap, and Shaders.
Member Function Documentation
TryGetComputeShader() [1/2]
template<typename ShaderType> bool FMaterialShaders::TryGetComputeShader (TShaderRef< ShaderType > & OutShader) const inline
Definition at line 285 of file MaterialShaderType.h.
References TryGetShader().
TryGetComputeShader() [2/2]
template<typename ShaderType> bool FMaterialShaders::TryGetComputeShader (TShaderRef< ShaderType > * OutShader) const inline
Definition at line 291 of file MaterialShaderType.h.
References TryGetShader().
TryGetGeometryShader() [1/2]
template<typename ShaderType> bool FMaterialShaders::TryGetGeometryShader (TShaderRef< ShaderType > & OutShader) const inline
Definition at line 283 of file MaterialShaderType.h.
References TryGetShader().
TryGetGeometryShader() [2/2]
template<typename ShaderType> bool FMaterialShaders::TryGetGeometryShader (TShaderRef< ShaderType > * OutShader) const inline
Definition at line 289 of file MaterialShaderType.h.
References TryGetShader().
TryGetMeshShader() [1/2]
template<typename ShaderType> bool FMaterialShaders::TryGetMeshShader (TShaderRef< ShaderType > & OutShader) const inline
Definition at line 284 of file MaterialShaderType.h.
References TryGetShader().
TryGetMeshShader() [2/2]
template<typename ShaderType> bool FMaterialShaders::TryGetMeshShader (TShaderRef< ShaderType > * OutShader) const inline
Definition at line 290 of file MaterialShaderType.h.
References TryGetShader().
TryGetPipeline()
bool FMaterialShaders::TryGetPipeline (FShaderPipelineRef & OutPipeline) const inline
Definition at line 236 of file MaterialShaderType.h.
References Pipeline, and ShaderMap.
TryGetPixelShader() [1/2]
template<typename ShaderType> bool FMaterialShaders::TryGetPixelShader (TShaderRef< ShaderType > & OutShader) const inline
Definition at line 282 of file MaterialShaderType.h.
References TryGetShader().
TryGetPixelShader() [2/2]
template<typename ShaderType> bool FMaterialShaders::TryGetPixelShader (TShaderRef< ShaderType > * OutShader) const inline
Definition at line 288 of file MaterialShaderType.h.
References TryGetShader().
TryGetShader() [1/2]
template<typename ShaderType> bool FMaterialShaders::TryGetShader (EShaderFrequency InFrequency, TShaderRef< ShaderType > & OutShader) const inline
Definition at line 247 of file MaterialShaderType.h.
References checkSlow, FShader::GetFrequency(), ShaderMap, and Shaders.
Referenced by TryGetComputeShader(), TryGetComputeShader(), TryGetGeometryShader(), TryGetGeometryShader(), TryGetMeshShader(), TryGetMeshShader(), TryGetPixelShader(), TryGetPixelShader(), TryGetVertexShader(), and TryGetVertexShader().
TryGetShader() [2/2]
template<typename ShaderType> bool FMaterialShaders::TryGetShader (EShaderFrequency InFrequency, TShaderRef< ShaderType > * OutShader) const inline
Definition at line 264 of file MaterialShaderType.h.
References check, checkSlow, FShader::GetFrequency(), ShaderMap, and Shaders.
TryGetVertexShader() [1/2]
template<typename ShaderType> bool FMaterialShaders::TryGetVertexShader (TShaderRef< ShaderType > & OutShader) const inline
Definition at line 281 of file MaterialShaderType.h.
References TryGetShader().
TryGetVertexShader() [2/2]
template<typename ShaderType> bool FMaterialShaders::TryGetVertexShader (TShaderRef< ShaderType > * OutShader) const inline
Definition at line 287 of file MaterialShaderType.h.
References TryGetShader().
Field Documentation
Pipeline
FShaderPipeline* FMaterialShaders::Pipeline
Definition at line 231 of file MaterialShaderType.h.
Referenced by FMaterialShaders(), and TryGetPipeline().
ShaderMap
const FShaderMapBase* FMaterialShaders::ShaderMap
Definition at line 230 of file MaterialShaderType.h.
Referenced by FMaterialShaders(), TryGetPipeline(), TryGetShader(), and TryGetShader().
Shaders
FShader* FMaterialShaders::Shaders[SF_NumFrequencies]
Definition at line 232 of file MaterialShaderType.h.
Referenced by FMaterialShaders(), TryGetShader(), and TryGetShader().
The documentation for this struct was generated from the following file:
Runtime/Engine/Public/MaterialShaderType.h