Unreal Engine 5.6 C++ API: FSlateAttributeDescriptor::FInitializer Struct Reference
FSlateAttributeDescriptor::FInitializer Struct Reference
Internal class to initialize the SlateAttributeDescriptor (Add attributes or modify existing attributes).
#include "SlateAttributeDescriptor.h"
Data Structures
struct FAttributeEntry
Public Member Functions
~FInitializer ()
FContainerInitializer AddContainer (FName ContainerName, OffsetType Offset)
FAttributeEntry AddMemberAttribute (FName AttributeName, OffsetType Offset, const FInvalidateWidgetReasonAttribute &ReasonGetter)
FAttributeEntry AddMemberAttribute (FName AttributeName, OffsetType Offset, FInvalidateWidgetReasonAttribute &&ReasonGetter)
void OverrideInvalidationReason (FName AttributeName, const FInvalidateWidgetReasonAttribute &Reason)
Change the InvalidationReason of an attribute defined in a base class.
void OverrideInvalidationReason (FName AttributeName, FInvalidateWidgetReasonAttribute &&Reason)
Change the InvalidationReason of an attribute defined in a base class.
void OverrideOnValueChanged (FName AttributeName, ECallbackOverrideType OverrideType, FAttributeValueChangedDelegate Callback)
Change the FAttributeValueChangedDelegate of an attribute defined in a base class.
void SetAffectVisibility (FName AttributeName, bool bAffectVisibility)
Change the update type of an attribute defined in a base class.
Private Member Functions
FInitializer (const FInitializer &)=delete
FInitializer (FSlateAttributeDescriptor &InDescriptor)
FInitializer (FSlateAttributeDescriptor &InDescriptor, const FSlateAttributeDescriptor &ParentDescriptor)
FInitializer & operator= (const FInitializer &)=delete
Private Attributes
FSlateAttributeDescriptor & Descriptor
friend FSlateWidgetClassData
Detailed Description
Internal class to initialize the SlateAttributeDescriptor (Add attributes or modify existing attributes).
Definition at line 260 of file SlateAttributeDescriptor.h.
Constructor & Destructor Documentation
FInitializer() [1/3]
FSlateAttributeDescriptor::FInitializer::FInitializer (FSlateAttributeDescriptor & InDescriptor) private
Referenced by FInitializer(), and operator=().
FInitializer() [2/3]
FSlateAttributeDescriptor::FInitializer::FInitializer (FSlateAttributeDescriptor & InDescriptor, const FSlateAttributeDescriptor & ParentDescriptor) private
FInitializer() [3/3]
FSlateAttributeDescriptor::FInitializer::FInitializer (const FInitializer &) private delete
References FInitializer().
~FInitializer()
FSlateAttributeDescriptor::FInitializer::~FInitializer ()
Member Function Documentation
AddContainer()
FContainerInitializer FSlateAttributeDescriptor::FInitializer::AddContainer (FName ContainerName, OffsetType Offset)
AddMemberAttribute() [1/2]
FAttributeEntry FSlateAttributeDescriptor::FInitializer::AddMemberAttribute (FName AttributeName, OffsetType Offset, const FInvalidateWidgetReasonAttribute & ReasonGetter)
AddMemberAttribute() [2/2]
FAttributeEntry FSlateAttributeDescriptor::FInitializer::AddMemberAttribute (FName AttributeName, OffsetType Offset, FInvalidateWidgetReasonAttribute && ReasonGetter)
operator=()
FInitializer & FSlateAttributeDescriptor::FInitializer::operator= (const FInitializer &) private delete
References FInitializer().
OverrideInvalidationReason() [1/2]
void FSlateAttributeDescriptor::FInitializer::OverrideInvalidationReason (FName AttributeName, const FInvalidateWidgetReasonAttribute & Reason)
Change the InvalidationReason of an attribute defined in a base class.
OverrideInvalidationReason() [2/2]
void FSlateAttributeDescriptor::FInitializer::OverrideInvalidationReason (FName AttributeName, FInvalidateWidgetReasonAttribute && Reason)
Change the InvalidationReason of an attribute defined in a base class.
OverrideOnValueChanged()
void FSlateAttributeDescriptor::FInitializer::OverrideOnValueChanged (FName AttributeName, ECallbackOverrideType OverrideType, FAttributeValueChangedDelegate Callback)
Change the FAttributeValueChangedDelegate of an attribute defined in a base class.
SetAffectVisibility()
void FSlateAttributeDescriptor::FInitializer::SetAffectVisibility (FName AttributeName, bool bAffectVisibility)
Change the update type of an attribute defined in a base class.
Field Documentation
Descriptor
FSlateAttributeDescriptor& FSlateAttributeDescriptor::FInitializer::Descriptor private
Definition at line 322 of file SlateAttributeDescriptor.h.
FSlateWidgetClassData
friend FSlateAttributeDescriptor::FInitializer::FSlateWidgetClassData private
Definition at line 263 of file SlateAttributeDescriptor.h.
The documentation for this struct was generated from the following file:
Runtime/SlateCore/Public/Types/SlateAttributeDescriptor.h