Unreal Engine 5.6 C++ API: FMovieSceneChannelEditorDataEntry Struct Reference
FMovieSceneChannelEditorDataEntry Struct Reference
Base entry type for use in FMovieSceneChannelProxy that stores editor meta-data and extended editor data for each channel of a given type (one entry per type).
#include "MovieSceneChannelEditorDataEntry.h"
Data Structures
struct IMovieSceneExtendedEditorDataArray
We store the array behind an interface whose access is via void* Typed access is only permitted using the original ChannelType templated methods to ensure safe casting of the array.
struct TMovieSceneExtendedEditorDataArray
Public Member Functions
template<typename ChannelType>
FMovieSceneChannelEditorDataEntry (const ChannelType &Channel)
Templated constructor that uses the channel parameter to construct the editor data array from the correct editor data type.
const void * GetExtendedEditorData (int32 ChannelIndex) const
Access the extended editor data for a specific channel.
TArrayView< const FMovieSceneChannelMetaData > GetMetaData () const
Get the common editor data for all channels.
Protected Member Functions
template<typename ChannelType>
void AddMetaData (const FMovieSceneChannelMetaData &MetaData)
Add new editor data for the specified channel type at the last index in the array.
template<typename ChannelType, typename ExtendedEditorDataType>
void AddMetaData (const FMovieSceneChannelMetaData &MetaData, ExtendedEditorDataType &&InExtendedEditorData)
Add new editor data for the specified channel type at the last index in the arrays.
template<typename ChannelType>
TArrayView< const typename TMovieSceneChannelTraits< ChannelType >::ExtendedEditorDataType > GetAllExtendedEditorData () const
Access the extended editor data for channels stored in this entry.
template<typename ChannelType, typename ExtendedEditorDataType>
void SetExtendedEditorData (int32 EntryIndex, ExtendedEditorDataType &&InExtendedEditorData)
Set the extended channel-type specific editor data on an already added channel entry.
Private Member Functions
template<typename ChannelType, typename ExtendedEditorDataType>
void ConstructExtendedEditorDataArray (ExtendedEditorDataType *)
Construct the extended editor data container for channel types that require it.
template<typename ChannelType>
void ConstructExtendedEditorDataArray (void *)
Private Attributes
TInlineValue< IMovieSceneExtendedEditorDataArray, 8 > ExtendedEditorDataArray
Extended editor data, one per channel, defined by TMovieSceneChannelTraits::ExtendedEditorDataType.
TArray< FMovieSceneChannelMetaData, TInlineAllocator< 1 > > MetaDataArray
Base editor data, one per channel.
Detailed Description
Base entry type for use in FMovieSceneChannelProxy that stores editor meta-data and extended editor data for each channel of a given type (one entry per type).
Definition at line 19 of file MovieSceneChannelEditorDataEntry.h.
Constructor & Destructor Documentation
FMovieSceneChannelEditorDataEntry()
template<typename ChannelType> FMovieSceneChannelEditorDataEntry::FMovieSceneChannelEditorDataEntry (const ChannelType & Channel) inline explicit
Templated constructor that uses the channel parameter to construct the editor data array from the correct editor data type.
Definition at line 26 of file MovieSceneChannelEditorDataEntry.h.
References ConstructExtendedEditorDataArray().
Referenced by FMovieSceneChannelEntry::FMovieSceneChannelEntry().
Member Function Documentation
AddMetaData() [1/2]
template<typename ChannelType> void FMovieSceneChannelEditorDataEntry::AddMetaData (const FMovieSceneChannelMetaData & MetaData) inline protected
Add new editor data for the specified channel type at the last index in the array.
Definition at line 57 of file MovieSceneChannelEditorDataEntry.h.
References MetaData, and MetaDataArray.
AddMetaData() [2/2]
template<typename ChannelType, typename ExtendedEditorDataType> void FMovieSceneChannelEditorDataEntry::AddMetaData (const FMovieSceneChannelMetaData & MetaData, ExtendedEditorDataType && InExtendedEditorData) inline protected
Add new editor data for the specified channel type at the last index in the arrays.
Definition at line 69 of file MovieSceneChannelEditorDataEntry.h.
References ExtendedEditorDataArray, Forward(), MetaData, and MetaDataArray.
ConstructExtendedEditorDataArray() [1/2]
template<typename ChannelType, typename ExtendedEditorDataType> void FMovieSceneChannelEditorDataEntry::ConstructExtendedEditorDataArray (ExtendedEditorDataType *) inline private
Construct the extended editor data container for channel types that require it.
Definition at line 106 of file MovieSceneChannelEditorDataEntry.h.
References ExtendedEditorDataArray.
Referenced by FMovieSceneChannelEditorDataEntry().
ConstructExtendedEditorDataArray() [2/2]
template<typename ChannelType> void FMovieSceneChannelEditorDataEntry::ConstructExtendedEditorDataArray (void *) inline private
Definition at line 112 of file MovieSceneChannelEditorDataEntry.h.
GetAllExtendedEditorData()
template<typename ChannelType> TArrayView< const typename TMovieSceneChannelTraits< ChannelType >::ExtendedEditorDataType > FMovieSceneChannelEditorDataEntry::GetAllExtendedEditorData () const inline protected
Access the extended editor data for channels stored in this entry.
Definition at line 94 of file MovieSceneChannelEditorDataEntry.h.
References ExtendedEditorDataArray.
Referenced by FMovieSceneChannelEntry::GetAllExtendedEditorData().
GetExtendedEditorData()
const void * FMovieSceneChannelEditorDataEntry::GetExtendedEditorData (int32 ChannelIndex) const inline
Access the extended editor data for a specific channel.
Definition at line 42 of file MovieSceneChannelEditorDataEntry.h.
References ExtendedEditorDataArray.
GetMetaData()
TArrayView< const FMovieSceneChannelMetaData > FMovieSceneChannelEditorDataEntry::GetMetaData () const inline
Get the common editor data for all channels.
Definition at line 34 of file MovieSceneChannelEditorDataEntry.h.
References MetaDataArray.
Referenced by FMovieSceneChannelProxy::GetMetaData().
SetExtendedEditorData()
template<typename ChannelType, typename ExtendedEditorDataType> void FMovieSceneChannelEditorDataEntry::SetExtendedEditorData (int32 EntryIndex, ExtendedEditorDataType && InExtendedEditorData) inline protected
Set the extended channel-type specific editor data on an already added channel entry.
Definition at line 83 of file MovieSceneChannelEditorDataEntry.h.
References ExtendedEditorDataArray, and Forward().
Referenced by FMovieSceneChannelProxyData::SetExtendedEditorData().
Field Documentation
ExtendedEditorDataArray
TInlineValue<IMovieSceneExtendedEditorDataArray, 8> FMovieSceneChannelEditorDataEntry::ExtendedEditorDataArray private
Extended editor data, one per channel, defined by TMovieSceneChannelTraits::ExtendedEditorDataType.
Unused if ExtendedEditorDataType is void.
Definition at line 144 of file MovieSceneChannelEditorDataEntry.h.
Referenced by AddMetaData(), ConstructExtendedEditorDataArray(), GetAllExtendedEditorData(), GetExtendedEditorData(), and SetExtendedEditorData().
MetaDataArray
TArray<FMovieSceneChannelMetaData, TInlineAllocator<1> > FMovieSceneChannelEditorDataEntry::MetaDataArray private
Base editor data, one per channel.
Definition at line 119 of file MovieSceneChannelEditorDataEntry.h.
Referenced by AddMetaData(), AddMetaData(), and GetMetaData().
The documentation for this struct was generated from the following file:
Runtime/MovieScene/Public/Channels/MovieSceneChannelEditorDataEntry.h