Unreal Engine 5.6 C++ API: ConstructorHelpers::FClassFinder< T > Struct Template Reference
ConstructorHelpers::FClassFinder< T > Struct Template Reference
#include "ConstructorHelpers.h"
Public Member Functions
FClassFinder (const TCHAR *ClassToFind)
virtual void AddReferencedObjects (FReferenceCollector &Collector) override
Pure virtual that must be overloaded by the inheriting class.
virtual FString GetReferencerName () const override
Overload this method to report a name for your referencer.
bool Succeeded ()
Public Member Functions inherited from FGCObject
FGCObject ()
Tells the global object that forwards AddReferencedObjects calls on to objects that a new object is requiring AddReferencedObjects call.
FGCObject (const FGCObject &Other)
FGCObject (EFlags Flags)
FGCObject (FGCObject &&Other)
virtual ~FGCObject ()
virtual bool GetReferencerPropertyName (UObject *Object, FString &OutPropertyName) const
Overload this method to report how the specified object is referenced, if necessary.
FGCObject & operator= (const FGCObject &)
FGCObject & operator= (FGCObject &&)
void RegisterGCObject ()
Register with GC, only needed if constructed with EFlags::RegisterLater or after unregistering.
void UnregisterGCObject ()
Unregister ahead of destruction.
Data Fields
TSubclassOf< T > Class
Additional Inherited Members
Public Types inherited from FGCObject
enum class EFlags : uint32 { None = 0 , RegisterLater = 1 << 0 , AddStableNativeReferencesOnly = 1 << 1 }
Static Public Member Functions inherited from FGCObject
static void StaticInit ()
Initializes the global object referencer and adds it to the root set.
Static Public Attributes inherited from FGCObject
static UGCObjectReferencer * GGCObjectReferencer
The static object referencer object that is shared across all garbage collectible non-UObject objects.
Detailed Description
template<class T>
struct ConstructorHelpers::FClassFinder< T >
Definition at line 157 of file ConstructorHelpers.h.
Constructor & Destructor Documentation
FClassFinder()
template<class T> ConstructorHelpers::FClassFinder< T >::FClassFinder (const TCHAR * ClassToFind) inline
Definition at line 160 of file ConstructorHelpers.h.
References ConstructorHelpers::CheckIfIsInConstructor(), Class, ConstructorHelpersInternal::FindOrLoadClass(), ConstructorHelpers::StripObjectClass(), and ConstructorHelpers::ValidateObject().
Member Function Documentation
AddReferencedObjects()
template<class T> virtual void ConstructorHelpers::FClassFinder< T >::AddReferencedObjects (FReferenceCollector & Collector) inline override virtual
Pure virtual that must be overloaded by the inheriting class.
Use this method to serialize any UObjects contained that you wish to keep around.
Parameters
Collector The collector of referenced objects.
Implements FGCObject.
Definition at line 173 of file ConstructorHelpers.h.
References Class.
GetReferencerName()
template<class T> virtual FString ConstructorHelpers::FClassFinder< T >::GetReferencerName () const inline override virtual
Overload this method to report a name for your referencer.
Implements FGCObject.
Definition at line 178 of file ConstructorHelpers.h.
References TEXT.
Succeeded()
template<class T> bool ConstructorHelpers::FClassFinder< T >::Succeeded () inline
Definition at line 168 of file ConstructorHelpers.h.
References Class.
Field Documentation
Class
template<class T> TSubclassOf<T> ConstructorHelpers::FClassFinder< T >::Class
Definition at line 159 of file ConstructorHelpers.h.
Referenced by FClassFinder(), AddReferencedObjects(), and Succeeded().
The documentation for this struct was generated from the following file:
Runtime/CoreUObject/Public/UObject/ConstructorHelpers.h