Unreal Engine 5.6 C++ API: UE::MovieScene::FSystemSubsequentTasks Struct Reference
UE::MovieScene::FSystemSubsequentTasks Struct Reference
#include "MovieSceneSystemTaskDependencies.h"
Public Types
using FComponentTypeID = UE::MovieScene::FComponentTypeID
Public Member Functions
MOVIESCENE_API void AddComponentTask (FComponentTypeID ComponentType, FGraphEventRef ComponentTask)
MOVIESCENE_API void AddRootTask (FGraphEventRef RootTask)
Private Member Functions
MOVIESCENE_API FSystemSubsequentTasks (FMovieSceneEntitySystemGraph *InGraph, FGraphEventArray *InAllTasks, EEntityThreadingModel InThreadingModel)
MOVIESCENE_API void ResetNode (uint16 InNodeID)
Private Attributes
FGraphEventArray * AllTasks
friend FMovieSceneEntitySystemGraph
FMovieSceneEntitySystemGraph * Graph
uint16 NodeID
TSharedPtr< UE::MovieScene::FSystemTaskPrerequisites > Subsequents
EEntityThreadingModel ThreadingModel
Detailed Description
Definition at line 97 of file MovieSceneSystemTaskDependencies.h.
Member Typedef Documentation
FComponentTypeID
using UE::MovieScene::FSystemSubsequentTasks::FComponentTypeID = UE::MovieScene::FComponentTypeID
Definition at line 99 of file MovieSceneSystemTaskDependencies.h.
Constructor & Destructor Documentation
FSystemSubsequentTasks()
MOVIESCENE_API UE::MovieScene::FSystemSubsequentTasks::FSystemSubsequentTasks (FMovieSceneEntitySystemGraph * InGraph, FGraphEventArray * InAllTasks, EEntityThreadingModel InThreadingModel) private
References FMovieSceneEntitySystemGraph.
Member Function Documentation
AddComponentTask()
MOVIESCENE_API void UE::MovieScene::FSystemSubsequentTasks::AddComponentTask (FComponentTypeID ComponentType, FGraphEventRef ComponentTask)
Referenced by UE::MovieScene::PopulateSubsequents(), and UE::MovieScene::PopulateSubsequents().
AddRootTask()
MOVIESCENE_API void UE::MovieScene::FSystemSubsequentTasks::AddRootTask (FGraphEventRef RootTask)
Referenced by UE::MovieScene::TEntityTaskComponents< T >::Dispatch_PerEntity(), and UE::MovieScene::TEntityTaskComponentsImpl< TIntegerSequence< int, Indices... >, T... >::PopulateSubsequents().
ResetNode()
MOVIESCENE_API void UE::MovieScene::FSystemSubsequentTasks::ResetNode (uint16 InNodeID) private
Field Documentation
AllTasks
FGraphEventArray* UE::MovieScene::FSystemSubsequentTasks::AllTasks private
Definition at line 115 of file MovieSceneSystemTaskDependencies.h.
FMovieSceneEntitySystemGraph
friend UE::MovieScene::FSystemSubsequentTasks::FMovieSceneEntitySystemGraph private
Definition at line 107 of file MovieSceneSystemTaskDependencies.h.
Referenced by FSystemSubsequentTasks().
Graph
FMovieSceneEntitySystemGraph* UE::MovieScene::FSystemSubsequentTasks::Graph private
Definition at line 114 of file MovieSceneSystemTaskDependencies.h.
NodeID
uint16 UE::MovieScene::FSystemSubsequentTasks::NodeID private
Definition at line 116 of file MovieSceneSystemTaskDependencies.h.
Subsequents
TSharedPtr<UE::MovieScene::FSystemTaskPrerequisites> UE::MovieScene::FSystemSubsequentTasks::Subsequents private
Definition at line 113 of file MovieSceneSystemTaskDependencies.h.
ThreadingModel
EEntityThreadingModel UE::MovieScene::FSystemSubsequentTasks::ThreadingModel private
Definition at line 117 of file MovieSceneSystemTaskDependencies.h.
The documentation for this struct was generated from the following file:
Runtime/MovieScene/Public/EntitySystem/MovieSceneSystemTaskDependencies.h