Unreal Engine 5.6 C++ API: FRemoteObjectPathName Struct Reference
FRemoteObjectPathName Struct Reference
Structure that represents remote object pathname (noexport type) Stores pathnames as an array of FNames and associated FRemoteObjectIds Names and Ids are stored from the innermost object first to the outermost object last.
#include "RemoteObjectPathName.h"
Public Member Functions
FRemoteObjectPathName ()=default
FRemoteObjectPathName (const FRemoteObjectPathName &)=default
FRemoteObjectPathName (FRemoteObjectPathName &&)=default
FRemoteObjectPathName (UObject *InObject)
FORCEINLINE FRemoteObjectId GetSegmentId (int32 InSegmentIndex, const FRemoteObjectTables &) const
FORCEINLINE FName GetSegmentName (int32 InSegmentIndex, const FRemoteObjectTables &) const
FRemoteObjectPathName & operator= (const FRemoteObjectPathName &)=default
FRemoteObjectPathName & operator= (FRemoteObjectPathName &&)=default
UObject * Resolve () const
FString ToString (int32 InMinPathSegmentIndex=0) const
Public Member Functions inherited from FRemoteObjectTables
FORCEINLINE int32 Num () const
void Serialize (FArchive &Ar)
Additional Inherited Members
Data Fields inherited from FRemoteObjectTables
TArray< FName > Names
TArray< FRemoteObjectId > RemoteIds
Detailed Description
Structure that represents remote object pathname (noexport type) Stores pathnames as an array of FNames and associated FRemoteObjectIds Names and Ids are stored from the innermost object first to the outermost object last.
Definition at line 72 of file RemoteObjectPathName.h.
Constructor & Destructor Documentation
FRemoteObjectPathName() [1/4]
FRemoteObjectPathName::FRemoteObjectPathName () default
Referenced by FRemoteObjectPathName(), FRemoteObjectPathName(), operator=(), and operator=().
FRemoteObjectPathName() [2/4]
FRemoteObjectPathName::FRemoteObjectPathName (FRemoteObjectPathName &&) default
References FRemoteObjectPathName().
FRemoteObjectPathName() [3/4]
FRemoteObjectPathName::FRemoteObjectPathName (UObject * InObject) explicit
FRemoteObjectPathName() [4/4]
FRemoteObjectPathName::FRemoteObjectPathName (const FRemoteObjectPathName &) default
References FRemoteObjectPathName().
Member Function Documentation
GetSegmentId()
FORCEINLINE FRemoteObjectId FRemoteObjectPathName::GetSegmentId (int32 InSegmentIndex, const FRemoteObjectTables &) const inline
Definition at line 87 of file RemoteObjectPathName.h.
References FORCEINLINE, and FRemoteObjectTables::RemoteIds.
GetSegmentName()
FORCEINLINE FName FRemoteObjectPathName::GetSegmentName (int32 InSegmentIndex, const FRemoteObjectTables &) const inline
Definition at line 82 of file RemoteObjectPathName.h.
References FORCEINLINE, and FRemoteObjectTables::Names.
operator=() [1/2]
FRemoteObjectPathName & FRemoteObjectPathName::operator= (const FRemoteObjectPathName &) default
References FRemoteObjectPathName().
operator=() [2/2]
FRemoteObjectPathName & FRemoteObjectPathName::operator= (FRemoteObjectPathName &&) default
References FRemoteObjectPathName().
Resolve()
UObject * FRemoteObjectPathName::Resolve () const
ToString()
FString FRemoteObjectPathName::ToString (int32 InMinPathSegmentIndex = 0) const
The documentation for this struct was generated from the following file:
Runtime/CoreUObject/Public/UObject/RemoteObjectPathName.h