Unreal Engine 5.6 C++ API: UE::SequenceNavigator::FNavigationToolViewModelTypeID Struct Reference
UE::SequenceNavigator::FNavigationToolViewModelTypeID Struct Reference
#include "NavigationToolViewModelTypeID.h"
Public Member Functions
FNavigationToolViewModelTypeID (FNavigationToolCastableTypeTable *InTypeTable, uint32 InID)
uint32 GetTypeID () const
Static Public Member Functions
static SEQUENCERCORE_API uint32 RegisterNewID ()
Private Attributes
uint32 ID
FNavigationToolCastableTypeTable * TypeTable = nullptr
Friends
uint32 GetTypeHash (FNavigationToolViewModelTypeID In)
bool operator< (FNavigationToolViewModelTypeID A, FNavigationToolViewModelTypeID B)
bool operator== (FNavigationToolViewModelTypeID A, FNavigationToolViewModelTypeID B)
Detailed Description
Definition at line 29 of file NavigationToolViewModelTypeID.h.
Constructor & Destructor Documentation
FNavigationToolViewModelTypeID()
UE::SequenceNavigator::FNavigationToolViewModelTypeID::FNavigationToolViewModelTypeID (FNavigationToolCastableTypeTable * InTypeTable, uint32 InID) inline
Definition at line 53 of file NavigationToolViewModelTypeID.h.
References ID, and TypeTable.
Referenced by GetTypeHash, operator<, and operator==.
Member Function Documentation
GetTypeID()
uint32 UE::SequenceNavigator::FNavigationToolViewModelTypeID::GetTypeID () const inline
Definition at line 46 of file NavigationToolViewModelTypeID.h.
References ID.
RegisterNewID()
SEQUENCERCORE_API uint32 UE::SequenceNavigator::FNavigationToolViewModelTypeID::RegisterNewID () static
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (FNavigationToolViewModelTypeID In) friend
Definition at line 31 of file NavigationToolViewModelTypeID.h.
References FNavigationToolViewModelTypeID(), and ID.
operator<
bool operator< (FNavigationToolViewModelTypeID A, FNavigationToolViewModelTypeID B) friend
Definition at line 36 of file NavigationToolViewModelTypeID.h.
References FNavigationToolViewModelTypeID(), A, and B.
operator==
bool operator== (FNavigationToolViewModelTypeID A, FNavigationToolViewModelTypeID B) friend
Definition at line 41 of file NavigationToolViewModelTypeID.h.
References FNavigationToolViewModelTypeID(), A, and B.
Field Documentation
ID
uint32 UE::SequenceNavigator::FNavigationToolViewModelTypeID::ID private
Definition at line 60 of file NavigationToolViewModelTypeID.h.
Referenced by FNavigationToolViewModelTypeID(), GetTypeHash, and GetTypeID().
TypeTable
FNavigationToolCastableTypeTable* UE::SequenceNavigator::FNavigationToolViewModelTypeID::TypeTable = nullptr private
Definition at line 59 of file NavigationToolViewModelTypeID.h.
Referenced by FNavigationToolViewModelTypeID().
The documentation for this struct was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Experimental/SequenceNavigator/Source/SequenceNavigator/Public/NavigationToolViewModelTypeID.h