Unreal Engine 5.6 C++ API: FDisplayClusterMeshUVs Struct Reference
FDisplayClusterMeshUVs Struct Reference
#include "DisplayClusterRender_MeshComponentTypes.h"
Public Types
enum class ERemapTarget : uint8 { Base = 0 , Chromakey , COUNT }
Public Member Functions
FDisplayClusterMeshUVs ()=default
FDisplayClusterMeshUVs (const int32 InBaseUVIndex, const int32 InChromakeyUVIndex)
const int32 GetSourceGeometryUVIndex (const ERemapTarget RemapTarget, const int32 MaxValue, const int32 DefaultValue) const
const int32 operator[] (const ERemapTarget RemapTarget) const
Private Attributes
int32 RemapValue [(uint8) ERemapTarget::COUNT] = {INDEX_NONE, INDEX_NONE}
Detailed Description
Definition at line 34 of file DisplayClusterRender_MeshComponentTypes.h.
Member Enumeration Documentation
ERemapTarget
enum class FDisplayClusterMeshUVs::ERemapTarget : uint8 strong
Enumerator
Base
Chromakey
COUNT
Definition at line 36 of file DisplayClusterRender_MeshComponentTypes.h.
Constructor & Destructor Documentation
FDisplayClusterMeshUVs() [1/2]
FDisplayClusterMeshUVs::FDisplayClusterMeshUVs () default
FDisplayClusterMeshUVs() [2/2]
FDisplayClusterMeshUVs::FDisplayClusterMeshUVs (const int32 InBaseUVIndex, const int32 InChromakeyUVIndex) inline
Definition at line 45 of file DisplayClusterRender_MeshComponentTypes.h.
References Base, Chromakey, and RemapValue.
Member Function Documentation
GetSourceGeometryUVIndex()
const int32 FDisplayClusterMeshUVs::GetSourceGeometryUVIndex (const ERemapTarget RemapTarget, const int32 MaxValue, const int32 DefaultValue) const inline
Definition at line 58 of file DisplayClusterRender_MeshComponentTypes.h.
References INDEX_NONE, and operator[]().
operator[]()
const int32 FDisplayClusterMeshUVs::operator[] (const ERemapTarget RemapTarget) const inline
Definition at line 51 of file DisplayClusterRender_MeshComponentTypes.h.
References check, COUNT, and RemapValue.
Referenced by GetSourceGeometryUVIndex().
Field Documentation
RemapValue
int32 FDisplayClusterMeshUVs::RemapValue[(uint8) ERemapTarget::COUNT] = {INDEX_NONE, INDEX_NONE} private
Definition at line 70 of file DisplayClusterRender_MeshComponentTypes.h.
Referenced by FDisplayClusterMeshUVs(), and operator[]().
The documentation for this struct was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/nDisplay/Source/DisplayCluster/Public/Render/Containers/DisplayClusterRender_MeshComponentTypes.h