Unreal Engine 5.6 C++ API: FShaderPipelineCompileJobKey Struct Reference
FShaderPipelineCompileJobKey Struct Reference
#include "ShaderCompilerJobTypes.h"
Public Member Functions
FShaderPipelineCompileJobKey (const FShaderPipelineType *InType=nullptr, const FVertexFactoryType *InVFType=nullptr, int32 InPermutationId=0)
uint32 MakeHash (uint32 Id) const
Data Fields
int32 PermutationId
const FShaderPipelineType * ShaderPipeline
const FVertexFactoryType * VFType
Friends
bool operator!= (const FShaderPipelineCompileJobKey &Lhs, const FShaderPipelineCompileJobKey &Rhs)
bool operator== (const FShaderPipelineCompileJobKey &Lhs, const FShaderPipelineCompileJobKey &Rhs)
Detailed Description
Definition at line 388 of file ShaderCompilerJobTypes.h.
Constructor & Destructor Documentation
FShaderPipelineCompileJobKey()
FShaderPipelineCompileJobKey::FShaderPipelineCompileJobKey (const FShaderPipelineType * InType = nullptr, const FVertexFactoryType * InVFType = nullptr, int32 InPermutationId = 0) inline explicit
Definition at line 390 of file ShaderCompilerJobTypes.h.
References PermutationId, ShaderPipeline, and VFType.
Referenced by operator!=, and operator==.
Member Function Documentation
MakeHash()
uint32 FShaderPipelineCompileJobKey::MakeHash (uint32 Id) const inline
Definition at line 394 of file ShaderCompilerJobTypes.h.
References GetTypeHash(), HashCombine(), PermutationId, ShaderPipeline, and VFType.
Friends And Related Symbol Documentation
operator!=
bool operator!= (const FShaderPipelineCompileJobKey & Lhs, const FShaderPipelineCompileJobKey & Rhs) friend
Definition at line 404 of file ShaderCompilerJobTypes.h.
References FShaderPipelineCompileJobKey(), and operator==.
operator==
bool operator== (const FShaderPipelineCompileJobKey & Lhs, const FShaderPipelineCompileJobKey & Rhs) friend
Definition at line 400 of file ShaderCompilerJobTypes.h.
References FShaderPipelineCompileJobKey(), PermutationId, ShaderPipeline, and VFType.
Referenced by operator!=.
Field Documentation
PermutationId
int32 FShaderPipelineCompileJobKey::PermutationId
Definition at line 398 of file ShaderCompilerJobTypes.h.
Referenced by FShaderPipelineCompileJobKey(), MakeHash(), and operator==.
ShaderPipeline
const FShaderPipelineType* FShaderPipelineCompileJobKey::ShaderPipeline
Definition at line 396 of file ShaderCompilerJobTypes.h.
Referenced by FShaderPipelineCompileJobKey(), MakeHash(), and operator==.
VFType
const FVertexFactoryType* FShaderPipelineCompileJobKey::VFType
Definition at line 397 of file ShaderCompilerJobTypes.h.
Referenced by FShaderPipelineCompileJobKey(), MakeHash(), and operator==.
The documentation for this struct was generated from the following file:
Runtime/RenderCore/Public/ShaderCompilerJobTypes.h