Unreal Engine 5.6 C++ API: FCrc Struct Reference
FCrc Struct Reference
CRC hash generation for different types of input data.
#include "Crc.h"
Public Types
typedef uint32(* MemCrc32Functor) (const void *Data, int32 Length, uint32 CRC)
generates CRC hash of the memory area
Public Member Functions
template<>
uint32 Strihash_DEPRECATED (const ANSICHAR *Data)
template<>
uint32 Strihash_DEPRECATED (const int32 DataLen, const ANSICHAR *Data)
template<>
uint32 Strihash_DEPRECATED (const int32 DataLen, const UTF8CHAR *Data)
template<>
uint32 Strihash_DEPRECATED (const int32 DataLen, const WIDECHAR *Data)
template<>
uint32 Strihash_DEPRECATED (const UTF8CHAR *Data)
template<>
uint32 Strihash_DEPRECATED (const WIDECHAR *Data)
Static Public Member Functions
static void Init ()
initializes the CRC lookup table.
static FORCEINLINE uint32 MemCrc32 (const void *Data, int32 Length, uint32 CRC=0)
static uint32 MemCrc_DEPRECATED (const void *Data, int32 Length, uint32 CRC=0)
generates CRC hash of the memory area
template<typename CharType>
static uint32 StrCrc32 (const CharType *Data, uint32 CRC=0)
String CRC.
template<typename CharType>
static uint32 StrCrc32Len (const CharType *Data, int32 Length, uint32 CRC=0)
String CRC.
template<typename CharType>
static uint32 StrCrc_DEPRECATED (const CharType *Data)
String CRC.
template<typename CharType>
static uint32 StrCrc_DEPRECATED (const int32 DataLen, const CharType *Data)
String CRC.
template<typename CharType>
static uint32 Strihash_DEPRECATED (const CharType *Data)
Case insensitive string hash function.
template<typename CharType>
static uint32 Strihash_DEPRECATED (const int32 DataLen, const CharType *Data)
template<typename T>
static uint32 TypeCrc32 (const T &Data, uint32 CRC=0)
generates CRC hash of the element
Static Public Attributes
static uint32 CRCTable_DEPRECATED [256]
DEPRECATED These tables and functions are deprecated because they're using tables and implementations which give values different from what a user of a typical CRC32 algorithm might expect.
static uint32 CRCTablesSB8 [8][256]
lookup table with precalculated CRC values - slicing by 8 implementation
static uint32 CRCTablesSB8_DEPRECATED [8][256]
lookup table with precalculated CRC values - slicing by 8 implementation
static MemCrc32Functor MemCrc32Func
Detailed Description
CRC hash generation for different types of input data.
Definition at line 19 of file Crc.h.
Member Typedef Documentation
MemCrc32Functor
typedef uint32(* FCrc::MemCrc32Functor) (const void *Data, int32 Length, uint32 CRC)
generates CRC hash of the memory area
Definition at line 29 of file Crc.h.
Member Function Documentation
Init()
void FCrc::Init () static
initializes the CRC lookup table.
Must be called before any of the CRC functions are used.
MemCrc32()
FORCEINLINE uint32 FCrc::MemCrc32 (const void * Data, int32 Length, uint32 CRC = 0) inline static nodiscard
Definition at line 31 of file Crc.h.
References FORCEINLINE, and MemCrc32Func.
Referenced by FMallocCallstackHandler::FCallStackMapKey::FCallStackMapKey(), TAttributeArrayContainer< AttributeType >::GetHash(), TMeshAttributeArrayBase< AttributeType >::GetHash(), TMeshAttributeArrayBase< AttributeType >::GetHash(), FShaderCodeLibraryPipeline::GetTypeHash, FTextFormatString::GetTypeHash, UE::Math::GetTypeHash(), UE::Math::GetTypeHash(), and TypeCrc32().
MemCrc_DEPRECATED()
uint32 FCrc::MemCrc_DEPRECATED (const void * Data, int32 Length, uint32 CRC = 0) static
generates CRC hash of the memory area
Referenced by FCanvas::FTransformEntry::FTransformEntry(), FLinearColor::GetTypeHash, SkeletalMeshImportData::FVertex::GetTypeHash, UE::Geometry::GetTypeHash(), UE::Geometry::GetTypeHash(), UE::Geometry::GetTypeHash(), UE::Geometry::GetTypeHash(), UE::Geometry::GetTypeHash(), UE::Math::GetTypeHash(), UE::Math::GetTypeHash(), UE::Math::GetTypeHash(), UE::Math::GetTypeHash(), UE::Math::TVector4< U >::GetTypeHash, and FCanvas::FTransformEntry::SetMatrix().
StrCrc32()
template<typename CharType> uint32 FCrc::StrCrc32 (const CharType * Data, uint32 CRC = 0) inline static nodiscard
String CRC.
Definition at line 45 of file Crc.h.
References CRCTablesSB8.
Referenced by UE::Core::GetTypeHash(), FTextLocalizationResource::HashString(), FTextLocalizationResource::HashString(), and FLocKey::ProduceHash().
StrCrc32Len()
template<typename CharType> uint32 FCrc::StrCrc32Len (const CharType * Data, int32 Length, uint32 CRC = 0) inline static nodiscard
String CRC.
Definition at line 84 of file Crc.h.
References CRCTablesSB8.
Referenced by Verse::FNativeString::GetTypeHash.
StrCrc_DEPRECATED() [1/2]
template<typename CharType> uint32 FCrc::StrCrc_DEPRECATED (const CharType * Data) inline static
String CRC.
Definition at line 136 of file Crc.h.
References check, and CRCTable_DEPRECATED.
StrCrc_DEPRECATED() [2/2]
template<typename CharType> uint32 FCrc::StrCrc_DEPRECATED (const int32 DataLen, const CharType * Data) inline static
String CRC.
Definition at line 155 of file Crc.h.
References check, and CRCTable_DEPRECATED.
Strihash_DEPRECATED() [1/8]
template<> uint32 FCrc::Strihash_DEPRECATED (const ANSICHAR * Data) inline
Definition at line 181 of file Crc.h.
References B, check, CRCTable_DEPRECATED, Hash, and TChar< CharType >::ToUpper().
Strihash_DEPRECATED() [2/8]
template<typename CharType> uint32 FCrc::Strihash_DEPRECATED (const CharType * Data) inline static
Case insensitive string hash function.
Referenced by TStringPointerMapKeyFuncs_DEPRECATED< InKeyType, InValueType, bInAllowDuplicateKeys >::GetKeyHash(), TStringPointerSetKeyFuncs_DEPRECATED< InKeyType, bInAllowDuplicateKeys >::GetKeyHash(), FMemoryImageString::GetTypeHash, TStringView< TCHAR >::GetTypeHash, Strihash_DEPRECATED(), Strihash_DEPRECATED(), and UE_DEPRECATED().
Strihash_DEPRECATED() [3/8]
template<> uint32 FCrc::Strihash_DEPRECATED (const int32 DataLen, const ANSICHAR * Data) inline
Definition at line 197 of file Crc.h.
References B, check, CRCTable_DEPRECATED, Hash, and TChar< CharType >::ToUpper().
Strihash_DEPRECATED() [4/8]
template<typename CharType> uint32 FCrc::Strihash_DEPRECATED (const int32 DataLen, const CharType * Data) inline static
Strihash_DEPRECATED() [5/8]
template<> uint32 FCrc::Strihash_DEPRECATED (const int32 DataLen, const UTF8CHAR * Data) inline
Definition at line 271 of file Crc.h.
References checkf, FGenericPlatformString::Convert(), FGenericPlatformString::ConvertedLength(), Strihash_DEPRECATED(), and TEXT.
Strihash_DEPRECATED() [6/8]
template<> uint32 FCrc::Strihash_DEPRECATED (const int32 DataLen, const WIDECHAR * Data) inline
Definition at line 231 of file Crc.h.
References B, check, CRCTable_DEPRECATED, Hash, and TChar< CharType >::ToUpper().
Strihash_DEPRECATED() [7/8]
template<> uint32 FCrc::Strihash_DEPRECATED (const UTF8CHAR * Data) inline
Definition at line 249 of file Crc.h.
References checkf, FGenericPlatformString::Convert(), FGenericPlatformString::ConvertedLength(), Strihash_DEPRECATED(), FAndroidPlatformString::Strlen(), and TEXT.
Strihash_DEPRECATED() [8/8]
template<> uint32 FCrc::Strihash_DEPRECATED (const WIDECHAR * Data) inline
Definition at line 213 of file Crc.h.
References B, check, CRCTable_DEPRECATED, Hash, and TChar< CharType >::ToUpper().
TypeCrc32()
template<typename T> uint32 FCrc::TypeCrc32 (const T & Data, uint32 CRC = 0) inline static nodiscard
generates CRC hash of the element
Definition at line 38 of file Crc.h.
References MemCrc32().
Referenced by FPackedLevelActorBuilderCluster::ComputeHash(), and Scalability::FQualityLevels::GetHash().
Field Documentation
CRCTable_DEPRECATED
uint32 FCrc::CRCTable_DEPRECATED[256] static
DEPRECATED These tables and functions are deprecated because they're using tables and implementations which give values different from what a user of a typical CRC32 algorithm might expect.
lookup table with precalculated CRC values
Definition at line 130 of file Crc.h.
Referenced by StrCrc_DEPRECATED(), StrCrc_DEPRECATED(), Strihash_DEPRECATED(), Strihash_DEPRECATED(), Strihash_DEPRECATED(), and Strihash_DEPRECATED().
CRCTablesSB8
uint32 FCrc::CRCTablesSB8[8][256] static
lookup table with precalculated CRC values - slicing by 8 implementation
Definition at line 22 of file Crc.h.
Referenced by StrCrc32(), and StrCrc32Len().
CRCTablesSB8_DEPRECATED
uint32 FCrc::CRCTablesSB8_DEPRECATED[8][256] static
lookup table with precalculated CRC values - slicing by 8 implementation
Definition at line 132 of file Crc.h.
MemCrc32Func
MemCrc32Functor FCrc::MemCrc32Func static
Definition at line 30 of file Crc.h.
Referenced by MemCrc32().
The documentation for this struct was generated from the following file:
Runtime/Core/Public/Misc/Crc.h