Unreal Engine 5.6 C++ API: FSlateInvalidationWidgetSortOrder Struct Reference
FSlateInvalidationWidgetSortOrder Struct Reference
SlateInvalidationWidgetIndex cannot be used to sort the widget since the ArrayIndex may not be in the expected order.
#include "SlateInvalidationWidgetSortOrder.h"
Public Member Functions
FSlateInvalidationWidgetSortOrder ()=default
FSlateInvalidationWidgetSortOrder (const FSlateInvalidationWidgetList &List, FSlateInvalidationWidgetIndex Index)
bool operator!= (const FSlateInvalidationWidgetSortOrder Other) const
bool operator< (const FSlateInvalidationWidgetSortOrder Other) const
bool operator<= (const FSlateInvalidationWidgetSortOrder Other) const
bool operator== (const FSlateInvalidationWidgetSortOrder Other) const
bool operator> (const FSlateInvalidationWidgetSortOrder Other) const
bool operator>= (const FSlateInvalidationWidgetSortOrder Other) const
Static Public Member Functions
static FSlateInvalidationWidgetSortOrder LimitMax ()
static FSlateInvalidationWidgetSortOrder LimitMin ()
Private Member Functions
FSlateInvalidationWidgetSortOrder (uint32 InOrder)
Private Attributes
uint32 Order = 0
Detailed Description
SlateInvalidationWidgetIndex cannot be used to sort the widget since the ArrayIndex may not be in the expected order.
(See the array as a double linked list). SlateInvalidationWidgetSortOrder builds a unique number that represents the order of the widget. The number is padded in a way to keep the order but not necessarily sequential. It is valid until the next SlateInvalidationRoot::ProcessInvalidation()
Definition at line 16 of file SlateInvalidationWidgetSortOrder.h.
Constructor & Destructor Documentation
FSlateInvalidationWidgetSortOrder() [1/3]
FSlateInvalidationWidgetSortOrder::FSlateInvalidationWidgetSortOrder (uint32 InOrder) inline private
Definition at line 20 of file SlateInvalidationWidgetSortOrder.h.
References Order.
Referenced by LimitMax(), LimitMin(), operator!=(), operator<(), operator<=(), operator==(), operator>(), and operator>=().
FSlateInvalidationWidgetSortOrder() [2/3]
FSlateInvalidationWidgetSortOrder::FSlateInvalidationWidgetSortOrder () default
FSlateInvalidationWidgetSortOrder() [3/3]
FSlateInvalidationWidgetSortOrder::FSlateInvalidationWidgetSortOrder (const FSlateInvalidationWidgetList & List, FSlateInvalidationWidgetIndex Index)
Member Function Documentation
LimitMax()
FSlateInvalidationWidgetSortOrder FSlateInvalidationWidgetSortOrder::LimitMax () static
References FSlateInvalidationWidgetSortOrder().
LimitMin()
FSlateInvalidationWidgetSortOrder FSlateInvalidationWidgetSortOrder::LimitMin () static
References FSlateInvalidationWidgetSortOrder().
operator!=()
bool FSlateInvalidationWidgetSortOrder::operator!= (const FSlateInvalidationWidgetSortOrder Other) const inline
Definition at line 34 of file SlateInvalidationWidgetSortOrder.h.
References FSlateInvalidationWidgetSortOrder(), Order, and Other.
operator<()
bool FSlateInvalidationWidgetSortOrder::operator< (const FSlateInvalidationWidgetSortOrder Other) const inline
Definition at line 29 of file SlateInvalidationWidgetSortOrder.h.
References FSlateInvalidationWidgetSortOrder(), Order, and Other.
operator<=()
bool FSlateInvalidationWidgetSortOrder::operator<= (const FSlateInvalidationWidgetSortOrder Other) const inline
Definition at line 30 of file SlateInvalidationWidgetSortOrder.h.
References FSlateInvalidationWidgetSortOrder(), Order, and Other.
operator==()
bool FSlateInvalidationWidgetSortOrder::operator== (const FSlateInvalidationWidgetSortOrder Other) const inline
Definition at line 33 of file SlateInvalidationWidgetSortOrder.h.
References FSlateInvalidationWidgetSortOrder(), Order, and Other.
operator>()
bool FSlateInvalidationWidgetSortOrder::operator> (const FSlateInvalidationWidgetSortOrder Other) const inline
Definition at line 31 of file SlateInvalidationWidgetSortOrder.h.
References FSlateInvalidationWidgetSortOrder(), Order, and Other.
operator>=()
bool FSlateInvalidationWidgetSortOrder::operator>= (const FSlateInvalidationWidgetSortOrder Other) const inline
Definition at line 32 of file SlateInvalidationWidgetSortOrder.h.
References FSlateInvalidationWidgetSortOrder(), Order, and Other.
Field Documentation
Order
uint32 FSlateInvalidationWidgetSortOrder::Order = 0 private
Definition at line 19 of file SlateInvalidationWidgetSortOrder.h.
Referenced by FSlateInvalidationWidgetSortOrder(), operator!=(), operator<(), operator<=(), operator==(), operator>(), and operator>=().
The documentation for this struct was generated from the following file:
Runtime/SlateCore/Public/FastUpdate/SlateInvalidationWidgetSortOrder.h