Unreal Engine 5.6 C++ API: TAddKeyImpl< FMovieSceneDoubleChannel, double > Struct Reference
TAddKeyImpl< FMovieSceneDoubleChannel, double > Struct Reference
#include "KeyframeTrackEditor.h"
Public Member Functions
TAddKeyImpl (int32 InChannelIndex, bool bInAddKey, const double &InValue)
virtual bool Apply (UMovieSceneSection *Section, FMovieSceneChannelProxy &Proxy, FFrameNumber InTime, EMovieSceneKeyInterpolation InterpolationMode, bool bKeyEvenIfUnchanged, bool bKeyEvenIfEmpty) const override
virtual void ApplyDefault (UMovieSceneSection *Section, FMovieSceneChannelProxy &Proxy, EKeyFrameTrackEditorSetDefault SetDefault) const override
virtual bool ModifyByCurrentAndWeight (FMovieSceneChannelProxy &Proxy, FFrameNumber InTime, void *VCurrentValue, float Weight) override
Public Member Functions inherited from IImpl
virtual ~IImpl ()
Data Fields
bool bAddKey
int32 ChannelIndex
double ValueToSet
Detailed Description
Definition at line 175 of file KeyframeTrackEditor.h.
Constructor & Destructor Documentation
TAddKeyImpl()
TAddKeyImpl< FMovieSceneDoubleChannel, double >::TAddKeyImpl (int32 InChannelIndex, bool bInAddKey, const double & InValue) inline
Definition at line 181 of file KeyframeTrackEditor.h.
References bAddKey, ChannelIndex, and ValueToSet.
Member Function Documentation
Apply()
virtual bool TAddKeyImpl< FMovieSceneDoubleChannel, double >::Apply (UMovieSceneSection * Section, FMovieSceneChannelProxy & Proxy, FFrameNumber InTime, EMovieSceneKeyInterpolation InterpolationMode, bool bKeyEvenIfUnchanged, bool bKeyEvenIfEmpty) const inline override virtual
Reimplemented from IImpl.
Definition at line 185 of file KeyframeTrackEditor.h.
References AddKeyToChannel(), bAddKey, ChannelIndex, FMovieSceneChannelProxy::GetChannel(), GetInterpolationMode(), InTime, ValueExistsAtTime(), and ValueToSet.
ApplyDefault()
virtual void TAddKeyImpl< FMovieSceneDoubleChannel, double >::ApplyDefault (UMovieSceneSection * Section, FMovieSceneChannelProxy & Proxy, EKeyFrameTrackEditorSetDefault SetDefault) const inline override virtual
Reimplemented from IImpl.
Definition at line 216 of file KeyframeTrackEditor.h.
References bAddKey, ChannelIndex, FMovieSceneChannelProxy::GetChannel(), UE::MovieScene::SetChannelDefault(), SetDefault, SetDefaultOnAddKeys, and ValueToSet.
ModifyByCurrentAndWeight()
virtual bool TAddKeyImpl< FMovieSceneDoubleChannel, double >::ModifyByCurrentAndWeight (FMovieSceneChannelProxy & Proxy, FFrameNumber InTime, void * VCurrentValue, float Weight) inline override virtual
Reimplemented from IImpl.
Definition at line 232 of file KeyframeTrackEditor.h.
References ChannelIndex, EvaluateChannel(), FMovieSceneChannelProxy::GetChannel(), TOptional< OptionalType >::GetValue(), InTime, TOptional< OptionalType >::IsSet(), ValueToSet, and Weight.
Field Documentation
bAddKey
bool TAddKeyImpl< FMovieSceneDoubleChannel, double >::bAddKey
Definition at line 178 of file KeyframeTrackEditor.h.
Referenced by TAddKeyImpl(), Apply(), and ApplyDefault().
ChannelIndex
int32 TAddKeyImpl< FMovieSceneDoubleChannel, double >::ChannelIndex
Definition at line 177 of file KeyframeTrackEditor.h.
Referenced by TAddKeyImpl(), Apply(), ApplyDefault(), and ModifyByCurrentAndWeight().
ValueToSet
double TAddKeyImpl< FMovieSceneDoubleChannel, double >::ValueToSet
Definition at line 179 of file KeyframeTrackEditor.h.
Referenced by TAddKeyImpl(), Apply(), ApplyDefault(), and ModifyByCurrentAndWeight().
The documentation for this struct was generated from the following file:
Editor/MovieSceneTools/Public/KeyframeTrackEditor.h