Unreal Engine 5.6 C++ API: FStreamingAnimationData Struct Reference
FStreamingAnimationData Struct Reference final
Contains everything that will be needed by a Streamable Anim that's streaming in data.
#include "AnimationStreaming.h"
Public Member Functions
FStreamingAnimationData ()
~FStreamingAnimationData ()
void BeginPendingRequests (const TArray< uint32 > &IndicesToLoad, const TArray< uint32 > &IndicesToFree)
Kicks off any pending requests.
bool BlockTillAllRequestsFinished (float TimeLimit=0.0f)
Blocks till all pending requests are fulfilled.
void FreeResources ()
SIZE_T GetMemorySize () const
bool HasPendingRequests (TArray< uint32 > &IndicesToLoad, TArray< uint32 > &IndicesToFree) const
Checks whether the requested chunk indices differ from those loaded.
bool Initialize (UAnimStreamable *InStreamableAnim, FAnimationStreamingManager *InAnimationStreamingManager)
Sets up the streaming wave data and loads the first chunk of animation for instant play.
bool UpdateStreamingStatus ()
Updates the streaming status of the animation and performs finalization when appropriate.
Data Fields
FAnimationStreamingManager * AnimationStreamingManager
Ptr to owning animation streaming manager.
TArray< uint32 > LoadedChunkIndices
Indices of chunks that are currently loaded.
TArray< FLoadedAnimationChunk > LoadedChunks
FCriticalSection LoadedChunksCritcalSection
TArray< uint32 > LoadFailedChunks
TArray< uint32 > RequestedChunks
UAnimStreamable * StreamableAnim
AnimStreamable this streaming data is for.
Private Member Functions
FStreamingAnimationData (const FStreamingAnimationData &that)
FLoadedAnimationChunk & AddNewLoadedChunk (uint32 ChunkIndex, FCompressedAnimSequence *ExistingData)
void FreeLoadedChunk (FLoadedAnimationChunk &LoadedChunk)
FStreamingAnimationData & operator= (FStreamingAnimationData const &)
void ResetRequestedChunks ()
Detailed Description
Contains everything that will be needed by a Streamable Anim that's streaming in data.
Definition at line 52 of file AnimationStreaming.h.
Constructor & Destructor Documentation
FStreamingAnimationData() [1/2]
FStreamingAnimationData::FStreamingAnimationData ()
Referenced by FStreamingAnimationData(), and operator=().
~FStreamingAnimationData()
FStreamingAnimationData::~FStreamingAnimationData ()
FStreamingAnimationData() [2/2]
FStreamingAnimationData::FStreamingAnimationData (const FStreamingAnimationData & that) private
References FStreamingAnimationData().
Member Function Documentation
AddNewLoadedChunk()
FLoadedAnimationChunk & FStreamingAnimationData::AddNewLoadedChunk (uint32 ChunkIndex, FCompressedAnimSequence * ExistingData) private
BeginPendingRequests()
void FStreamingAnimationData::BeginPendingRequests (const TArray< uint32 > & IndicesToLoad, const TArray< uint32 > & IndicesToFree)
Kicks off any pending requests.
BlockTillAllRequestsFinished()
bool FStreamingAnimationData::BlockTillAllRequestsFinished (float TimeLimit = 0.0f)
Blocks till all pending requests are fulfilled.
Parameters
TimeLimit Optional time limit for processing, in seconds. Specifying 0 means infinite time limit.
Returns
Return true if there are no requests left in flight, false if the time limit was reached before they were finished.
References TimeLimit.
FreeLoadedChunk()
void FStreamingAnimationData::FreeLoadedChunk (FLoadedAnimationChunk & LoadedChunk) private
FreeResources()
void FStreamingAnimationData::FreeResources ()
GetMemorySize()
SIZE_T FStreamingAnimationData::GetMemorySize () const
HasPendingRequests()
bool FStreamingAnimationData::HasPendingRequests (TArray< uint32 > & IndicesToLoad, TArray< uint32 > & IndicesToFree) const
Checks whether the requested chunk indices differ from those loaded.
Parameters
IndicesToLoad List of chunk indices that should be loaded
IndicesToFree List of chunk indices that should be freed
Returns
Whether any changes to loaded chunks are required
Initialize()
bool FStreamingAnimationData::Initialize (UAnimStreamable * InStreamableAnim, FAnimationStreamingManager * InAnimationStreamingManager)
Sets up the streaming wave data and loads the first chunk of animation for instant play.
Parameters
Anim The streamable animation we are managing
operator=()
FStreamingAnimationData & FStreamingAnimationData::operator= (FStreamingAnimationData const &) private
References FStreamingAnimationData().
ResetRequestedChunks()
void FStreamingAnimationData::ResetRequestedChunks () private
UpdateStreamingStatus()
bool FStreamingAnimationData::UpdateStreamingStatus ()
Updates the streaming status of the animation and performs finalization when appropriate.
The function returns true while there are pending requests in flight and updating needs to continue.
Returns
true if there are requests in flight, false otherwise
Field Documentation
AnimationStreamingManager
FAnimationStreamingManager* FStreamingAnimationData::AnimationStreamingManager
Ptr to owning animation streaming manager.
Definition at line 127 of file AnimationStreaming.h.
LoadedChunkIndices
TArray<uint32> FStreamingAnimationData::LoadedChunkIndices
Indices of chunks that are currently loaded.
Definition at line 120 of file AnimationStreaming.h.
LoadedChunks
TArray<FLoadedAnimationChunk> FStreamingAnimationData::LoadedChunks
Definition at line 115 of file AnimationStreaming.h.
LoadedChunksCritcalSection
FCriticalSection FStreamingAnimationData::LoadedChunksCritcalSection mutable
Definition at line 117 of file AnimationStreaming.h.
LoadFailedChunks
TArray<uint32> FStreamingAnimationData::LoadFailedChunks
Definition at line 124 of file AnimationStreaming.h.
RequestedChunks
TArray<uint32> FStreamingAnimationData::RequestedChunks
Definition at line 122 of file AnimationStreaming.h.
StreamableAnim
UAnimStreamable* FStreamingAnimationData::StreamableAnim
AnimStreamable this streaming data is for.
Definition at line 112 of file AnimationStreaming.h.
The documentation for this struct was generated from the following file:
Runtime/Engine/Public/Animation/AnimationStreaming.h