Unreal Engine 5.6 C++ API: FArchiveDiffInfo Struct Reference
FArchiveDiffInfo Struct Reference
#include "ArchiveStackTrace.h"
Public Member Functions
FArchiveDiffInfo ()
FArchiveDiffInfo (int64 InOffset, int64 InSize)
bool operator< (const FArchiveDiffInfo &InOther) const
bool operator== (const FArchiveDiffInfo &InOther) const
Data Fields
int64 Offset
int64 Size
Friends
FArchive & operator<< (FArchive &Ar, FArchiveDiffInfo &InDiffInfo)
Detailed Description
Definition at line 94 of file ArchiveStackTrace.h.
Constructor & Destructor Documentation
FArchiveDiffInfo() [1/2]
FArchiveDiffInfo::FArchiveDiffInfo () inline
Definition at line 100 of file ArchiveStackTrace.h.
References Offset, and Size.
Referenced by operator<(), operator<<, and operator==().
FArchiveDiffInfo() [2/2]
FArchiveDiffInfo::FArchiveDiffInfo (int64 InOffset, int64 InSize) inline
Definition at line 105 of file ArchiveStackTrace.h.
References Offset, and Size.
Member Function Documentation
operator<()
bool FArchiveDiffInfo::operator< (const FArchiveDiffInfo & InOther) const inline
Definition at line 114 of file ArchiveStackTrace.h.
References FArchiveDiffInfo(), and Offset.
operator==()
bool FArchiveDiffInfo::operator== (const FArchiveDiffInfo & InOther) const inline
Definition at line 110 of file ArchiveStackTrace.h.
References FArchiveDiffInfo(), and Offset.
Friends And Related Symbol Documentation
operator<<
FArchive & operator<< (FArchive & Ar, FArchiveDiffInfo & InDiffInfo) friend
Definition at line 118 of file ArchiveStackTrace.h.
References FArchiveDiffInfo(), Ar, Offset, and Size.
Field Documentation
Offset
int64 FArchiveDiffInfo::Offset
Definition at line 98 of file ArchiveStackTrace.h.
Referenced by FArchiveDiffInfo(), FArchiveDiffInfo(), operator<(), operator<<, and operator==().
Size
int64 FArchiveDiffInfo::Size
Definition at line 99 of file ArchiveStackTrace.h.
Referenced by FArchiveDiffInfo(), FArchiveDiffInfo(), and operator<<.
The documentation for this struct was generated from the following file:
Runtime/CoreUObject/Public/Serialization/ArchiveStackTrace.h