Unreal Engine 5.6 C++ API: FAudioDeviceManager::FAudioDeviceContainer Struct Reference
FAudioDeviceManager::FAudioDeviceContainer Struct Reference
Public Member Functions
FAudioDeviceContainer (const FAudioDeviceContainer &Other)
FAudioDeviceContainer (const FAudioDeviceParams &InParams, Audio::FDeviceId InDeviceID, FAudioDeviceManager *DeviceManager)
FAudioDeviceContainer (FAudioDeviceContainer &&Other)
~FAudioDeviceContainer ()
Data Fields
bool bIsNonRealtime
Whether this audio device is realtime or not.
FAudioDevice * Device
int32 NumberOfHandlesToThisDevice
EAudioDeviceScope Scope
Whether this device can be shared.
IAudioDeviceModule * SpecifiedModule
Module this was created with.
TArray< UWorld * > WorldsUsingThisDevice
Worlds that have been registered to this device.
Private Member Functions
FAudioDeviceContainer ()
Detailed Description
Definition at line 387 of file AudioDeviceManager.h.
Constructor & Destructor Documentation
FAudioDeviceContainer() [1/4]
FAudioDeviceManager::FAudioDeviceContainer::FAudioDeviceContainer (const FAudioDeviceParams & InParams, Audio::FDeviceId InDeviceID, FAudioDeviceManager * DeviceManager)
References FAudioDeviceManager::FAudioDeviceManager().
Referenced by FAudioDeviceContainer(), and FAudioDeviceContainer().
~FAudioDeviceContainer()
FAudioDeviceManager::FAudioDeviceContainer::~FAudioDeviceContainer ()
FAudioDeviceContainer() [2/4]
FAudioDeviceManager::FAudioDeviceContainer::FAudioDeviceContainer (const FAudioDeviceContainer & Other) inline
Definition at line 411 of file AudioDeviceManager.h.
References FAudioDeviceContainer(), checkNoEntry, and Other.
FAudioDeviceContainer() [3/4]
FAudioDeviceManager::FAudioDeviceContainer::FAudioDeviceContainer (FAudioDeviceContainer && Other)
References FAudioDeviceContainer(), and Other.
FAudioDeviceContainer() [4/4]
FAudioDeviceManager::FAudioDeviceContainer::FAudioDeviceContainer () private
Field Documentation
bIsNonRealtime
bool FAudioDeviceManager::FAudioDeviceContainer::bIsNonRealtime
Whether this audio device is realtime or not.
Definition at line 403 of file AudioDeviceManager.h.
Device
FAudioDevice* FAudioDeviceManager::FAudioDeviceContainer::Device
Definition at line 391 of file AudioDeviceManager.h.
NumberOfHandlesToThisDevice
int32 FAudioDeviceManager::FAudioDeviceContainer::NumberOfHandlesToThisDevice
Definition at line 394 of file AudioDeviceManager.h.
Scope
EAudioDeviceScope FAudioDeviceManager::FAudioDeviceContainer::Scope
Whether this device can be shared.
Definition at line 400 of file AudioDeviceManager.h.
SpecifiedModule
IAudioDeviceModule* FAudioDeviceManager::FAudioDeviceContainer::SpecifiedModule
Module this was created with.
If nullptr, this device was created with the default module.
Definition at line 406 of file AudioDeviceManager.h.
WorldsUsingThisDevice
TArray<UWorld*> FAudioDeviceManager::FAudioDeviceContainer::WorldsUsingThisDevice
Worlds that have been registered to this device.
Definition at line 397 of file AudioDeviceManager.h.
The documentation for this struct was generated from the following file:
Runtime/Engine/Public/AudioDeviceManager.h