Unreal Engine 5.6 C++ API: FSkinWeightProfileStack Struct Reference
FSkinWeightProfileStack Struct Reference
An identifier to identify a skin weight profile layer stack.
#include "SkinWeightProfile.h"
Public Member Functions
FSkinWeightProfileStack ()
template<typename... ArgTypes UE_REQUIRES>
FSkinWeightProfileStack (ArgTypes &&... Args)
FSkinWeightProfileStack (const FName InProfileNames[MaxLayerCount])
void CopyIntoArray (FName OutProfileNames[MaxLayerCount]) const
FString GetUniqueId () const
bool IsEmpty () const
FSkinWeightProfileStack Normalized () const
Returns a normalized layer stack, such that any empty layers are collapsed.
bool operator!= (const FSkinWeightProfileStack &InProfileStack) const
bool operator== (const FSkinWeightProfileStack &InProfileStack) const
FName & operator[] (int32 InLayerIndex)
FName operator[] (int32 InLayerIndex) const
Data Fields
TStaticArray< FName, MaxLayerCount > Layers
Static Public Attributes
static constexpr int32 MaxLayerCount = 2
Friends
uint32 GetTypeHash (const FSkinWeightProfileStack &InProfileStack)
Detailed Description
An identifier to identify a skin weight profile layer stack.
Currently limited to two layers, but can be extended if needed.
Definition at line 132 of file SkinWeightProfile.h.
Constructor & Destructor Documentation
FSkinWeightProfileStack() [1/3]
FSkinWeightProfileStack::FSkinWeightProfileStack () inline
Definition at line 137 of file SkinWeightProfile.h.
References InPlace, and Layers.
Referenced by GetTypeHash, Normalized(), operator!=(), and operator==().
FSkinWeightProfileStack() [2/3]
template<typename... ArgTypes UE_REQUIRES> FSkinWeightProfileStack::FSkinWeightProfileStack (ArgTypes &&... Args) inline explicit
Definition at line 146 of file SkinWeightProfile.h.
References Forward(), Layers, and MaxLayerCount.
FSkinWeightProfileStack() [3/3]
FSkinWeightProfileStack::FSkinWeightProfileStack (const FName InProfileNames[MaxLayerCount]) inline explicit
Definition at line 156 of file SkinWeightProfile.h.
References Layers, and MaxLayerCount.
Member Function Documentation
CopyIntoArray()
void FSkinWeightProfileStack::CopyIntoArray (FName OutProfileNames[MaxLayerCount]) const inline
Definition at line 195 of file SkinWeightProfile.h.
References Layers, and MaxLayerCount.
GetUniqueId()
FString FSkinWeightProfileStack::GetUniqueId () const inline
Definition at line 218 of file SkinWeightProfile.h.
References InPlace, UE::String::JoinBy(), Layers, TEXT, and FName::ToString().
IsEmpty()
bool FSkinWeightProfileStack::IsEmpty () const inline
Definition at line 183 of file SkinWeightProfile.h.
References Layers, and MaxLayerCount.
Normalized()
FSkinWeightProfileStack FSkinWeightProfileStack::Normalized () const inline
Returns a normalized layer stack, such that any empty layers are collapsed.
Definition at line 204 of file SkinWeightProfile.h.
References FSkinWeightProfileStack(), Layers, and MaxLayerCount.
operator!=()
bool FSkinWeightProfileStack::operator!= (const FSkinWeightProfileStack & InProfileStack) const inline
Definition at line 168 of file SkinWeightProfile.h.
References FSkinWeightProfileStack(), and Layers.
operator==()
bool FSkinWeightProfileStack::operator== (const FSkinWeightProfileStack & InProfileStack) const inline
Definition at line 164 of file SkinWeightProfile.h.
References FSkinWeightProfileStack(), and Layers.
operator[]() [1/2]
FName & FSkinWeightProfileStack::operator[] (int32 InLayerIndex) inline
Definition at line 178 of file SkinWeightProfile.h.
References Layers.
operator[]() [2/2]
FName FSkinWeightProfileStack::operator[] (int32 InLayerIndex) const inline
Definition at line 173 of file SkinWeightProfile.h.
References Layers.
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FSkinWeightProfileStack & InProfileStack) friend
Definition at line 224 of file SkinWeightProfile.h.
References FSkinWeightProfileStack(), GetTypeHash, Hash, HashCombineFast(), and MaxLayerCount.
Referenced by GetTypeHash.
Field Documentation
Layers
TStaticArray<FName, MaxLayerCount> FSkinWeightProfileStack::Layers
Definition at line 135 of file SkinWeightProfile.h.
Referenced by FSkinWeightProfileStack(), FSkinWeightProfileStack(), FSkinWeightProfileStack(), CopyIntoArray(), GetUniqueId(), IsEmpty(), Normalized(), operator!=(), operator==(), operator[](), and operator[]().
MaxLayerCount
int32 FSkinWeightProfileStack::MaxLayerCount = 2 static constexpr
Definition at line 134 of file SkinWeightProfile.h.
Referenced by FSkinWeightProfileStack(), FSkinWeightProfileStack(), CopyIntoArray(), GetTypeHash, IsEmpty(), and Normalized().
The documentation for this struct was generated from the following file:
Runtime/Engine/Public/Animation/SkinWeightProfile.h