Unreal Engine 5.6 C++ API: TTypeCompatibleBytes< ElementType > Struct Template Reference
TTypeCompatibleBytes< ElementType > Struct Template Reference
An untyped array of data with compile-time alignment and size derived from another type.
#include "TypeCompatibleBytes.h"
Public Types
using ConstGetType = const ElementType&
using ElementTypeAlias_NatVisHelper = ElementType
using MutableGetType = ElementType&
using RvalueGetType = ElementType&&
Public Member Functions
TTypeCompatibleBytes ()=default
TTypeCompatibleBytes (const TTypeCompatibleBytes &)=delete
TTypeCompatibleBytes (TTypeCompatibleBytes &&)=delete
~TTypeCompatibleBytes ()=default
void DestroyUnchecked ()
template<typename... ArgTypes>
void EmplaceUnchecked (ArgTypes &&... Args)
ElementType * GetTypedPtr ()
const ElementType * GetTypedPtr () const
ElementType & GetUnchecked () &
ElementType && GetUnchecked () &&
const ElementType & GetUnchecked () const &
TTypeCompatibleBytes & operator= (const TTypeCompatibleBytes &)=delete
TTypeCompatibleBytes & operator= (TTypeCompatibleBytes &&)=delete
Data Fields
uint8 Pad [sizeof(ElementType)]
Detailed Description
template<typename ElementType>
struct TTypeCompatibleBytes< ElementType >
An untyped array of data with compile-time alignment and size derived from another type.
Definition at line 23 of file TypeCompatibleBytes.h.
Member Typedef Documentation
ConstGetType
template<typename ElementType> using TTypeCompatibleBytes< ElementType >::ConstGetType = const ElementType&
Definition at line 48 of file TypeCompatibleBytes.h.
ElementTypeAlias_NatVisHelper
template<typename ElementType> using TTypeCompatibleBytes< ElementType >::ElementTypeAlias_NatVisHelper = ElementType
Definition at line 25 of file TypeCompatibleBytes.h.
MutableGetType
template<typename ElementType> using TTypeCompatibleBytes< ElementType >::MutableGetType = ElementType&
Definition at line 47 of file TypeCompatibleBytes.h.
RvalueGetType
template<typename ElementType> using TTypeCompatibleBytes< ElementType >::RvalueGetType = ElementType&&
Definition at line 49 of file TypeCompatibleBytes.h.
Constructor & Destructor Documentation
TTypeCompatibleBytes() [1/3]
template<typename ElementType> TTypeCompatibleBytes< ElementType >::TTypeCompatibleBytes () default
Referenced by TTypeCompatibleBytes(), TTypeCompatibleBytes(), operator=(), and operator=().
~TTypeCompatibleBytes()
template<typename ElementType> TTypeCompatibleBytes< ElementType >::~TTypeCompatibleBytes () default
TTypeCompatibleBytes() [2/3]
template<typename ElementType> TTypeCompatibleBytes< ElementType >::TTypeCompatibleBytes (TTypeCompatibleBytes< ElementType > &&) delete
References TTypeCompatibleBytes().
TTypeCompatibleBytes() [3/3]
template<typename ElementType> TTypeCompatibleBytes< ElementType >::TTypeCompatibleBytes (const TTypeCompatibleBytes< ElementType > &) delete
References TTypeCompatibleBytes().
Member Function Documentation
DestroyUnchecked()
template<typename ElementType> void TTypeCompatibleBytes< ElementType >::DestroyUnchecked () inline
Definition at line 75 of file TypeCompatibleBytes.h.
EmplaceUnchecked()
template<typename ElementType> template<typename... ArgTypes> void TTypeCompatibleBytes< ElementType >::EmplaceUnchecked (ArgTypes &&... Args) inline
Definition at line 68 of file TypeCompatibleBytes.h.
References GetTypedPtr().
GetTypedPtr() [1/2]
template<typename ElementType> ElementType * TTypeCompatibleBytes< ElementType >::GetTypedPtr () inline
Definition at line 38 of file TypeCompatibleBytes.h.
Referenced by UE::TConsumeAllMpmcQueue< T, AllocatorType >::ConsumeAll(), EmplaceUnchecked(), and UScriptStruct::TCppStructOps< CPPSTRUCT >::ExportTextItem().
GetTypedPtr() [2/2]
template<typename ElementType> const ElementType * TTypeCompatibleBytes< ElementType >::GetTypedPtr () const inline
Definition at line 42 of file TypeCompatibleBytes.h.
GetUnchecked() [1/3]
template<typename ElementType> ElementType & TTypeCompatibleBytes< ElementType >::GetUnchecked () & inline
Definition at line 52 of file TypeCompatibleBytes.h.
GetUnchecked() [2/3]
template<typename ElementType> ElementType && TTypeCompatibleBytes< ElementType >::GetUnchecked () && inline
Definition at line 60 of file TypeCompatibleBytes.h.
GetUnchecked() [3/3]
template<typename ElementType> const ElementType & TTypeCompatibleBytes< ElementType >::GetUnchecked () const & inline
Definition at line 56 of file TypeCompatibleBytes.h.
operator=() [1/2]
template<typename ElementType> TTypeCompatibleBytes & TTypeCompatibleBytes< ElementType >::operator= (const TTypeCompatibleBytes< ElementType > &) delete
References TTypeCompatibleBytes().
operator=() [2/2]
template<typename ElementType> TTypeCompatibleBytes & TTypeCompatibleBytes< ElementType >::operator= (TTypeCompatibleBytes< ElementType > &&) delete
References TTypeCompatibleBytes().
Field Documentation
Pad
template<typename ElementType> uint8 TTypeCompatibleBytes< ElementType >::Pad[sizeof(ElementType)]
Definition at line 81 of file TypeCompatibleBytes.h.
The documentation for this struct was generated from the following file:
Runtime/Core/Public/Templates/TypeCompatibleBytes.h