Unreal Engine 5.6 C++ API: FSmartObjectHandleFactory Struct Reference
FSmartObjectHandleFactory Struct Reference
Struct used as a friend to FSmartObjectHandle that is the only caller allowed to create a handle from a Guid.
#include "SmartObjectTypes.h"
Public Member Functions
UE_DEPRECATED (5.6, "Use CreateHandleFromComponent instead.") static FSmartObjectHandle CreateHandleForComponent(const UWorld &World
Static Public Member Functions
static FSmartObjectHandle CreateHandleForDynamicObject ()
static FSmartObjectHandle CreateHandleFromComponent (const TNotNull< const USmartObjectComponent * > Component)
static FSmartObjectHandle CreateHandleFromGuid (const FGuid Guid)
static SMARTOBJECTSMODULE_API FGuid CreateHandleGuidFromComponent (TNotNull< const USmartObjectComponent * > Component)
Data Fields
const USmartObjectComponent & Component
Detailed Description
Struct used as a friend to FSmartObjectHandle that is the only caller allowed to create a handle from a Guid.
Definition at line 839 of file SmartObjectTypes.h.
Member Function Documentation
CreateHandleForDynamicObject()
FSmartObjectHandle FSmartObjectHandleFactory::CreateHandleForDynamicObject () inline static
Definition at line 846 of file SmartObjectTypes.h.
References FGuid::NewGuid().
CreateHandleFromComponent()
FSmartObjectHandle FSmartObjectHandleFactory::CreateHandleFromComponent (const TNotNull< const USmartObjectComponent * > Component) inline static
Definition at line 851 of file SmartObjectTypes.h.
References Component, and CreateHandleGuidFromComponent().
CreateHandleFromGuid()
FSmartObjectHandle FSmartObjectHandleFactory::CreateHandleFromGuid (const FGuid Guid) inline static
Definition at line 841 of file SmartObjectTypes.h.
References Guid.
CreateHandleGuidFromComponent()
SMARTOBJECTSMODULE_API FGuid FSmartObjectHandleFactory::CreateHandleGuidFromComponent (TNotNull< const USmartObjectComponent * > Component) static
References Component.
Referenced by CreateHandleFromComponent().
UE_DEPRECATED()
FSmartObjectHandleFactory::UE_DEPRECATED (5. 6, "Use CreateHandleFromComponent instead.") const &
Field Documentation
Component
const USmartObjectComponent& FSmartObjectHandleFactory::Component
Initial value:
{
        return CreateHandleFromComponent(&Component)
Definition at line 859 of file SmartObjectTypes.h.
Referenced by CreateHandleFromComponent(), and CreateHandleGuidFromComponent().
The documentation for this struct was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/SmartObjects/Source/SmartObjectsModule/Public/SmartObjectTypes.h