Unreal Engine 5.6 C++ API: FRigidBodyIndexPair Struct Reference
FRigidBodyIndexPair Struct Reference
Endian save storage for a pair of rigid body indices used as a key in the CollisionDisableTable TMap.
#include "RigidBodyIndexPair.h"
Public Member Functions
FRigidBodyIndexPair ()
Default constructor required for use with TMap.
FRigidBodyIndexPair (int32 Index1, int32 Index2)
Constructor, taking unordered pair of indices and generating a key.
bool operator== (const FRigidBodyIndexPair &Other) const
== operator required for use with TMap
Data Fields
int32 Indices [2]
Pair of indices.
Friends
FArchive & operator<< (FArchive &Ar, FRigidBodyIndexPair &Pair)
Serializes the rigid body index pair to the passed in archive.
Detailed Description
Endian save storage for a pair of rigid body indices used as a key in the CollisionDisableTable TMap.
Definition at line 10 of file RigidBodyIndexPair.h.
Constructor & Destructor Documentation
FRigidBodyIndexPair() [1/2]
FRigidBodyIndexPair::FRigidBodyIndexPair () inline
Default constructor required for use with TMap.
Definition at line 16 of file RigidBodyIndexPair.h.
Referenced by operator<<, and operator==().
FRigidBodyIndexPair() [2/2]
FRigidBodyIndexPair::FRigidBodyIndexPair (int32 Index1, int32 Index2) inline
Constructor, taking unordered pair of indices and generating a key.
Parameters
Index1 1st unordered index
Index2 2nd unordered index
Definition at line 25 of file RigidBodyIndexPair.h.
References Indices, FMath::Max, and FMath::Min.
Member Function Documentation
operator==()
bool FRigidBodyIndexPair::operator== (const FRigidBodyIndexPair & Other) const inline
== operator required for use with TMap
Parameters
Other FRigidBodyIndexPair to compare this one to.
Returns
true if the passed in FRigidBodyIndexPair is identical to this one, false otherwise
Definition at line 37 of file RigidBodyIndexPair.h.
References FRigidBodyIndexPair(), Indices, and Other.
Friends And Related Symbol Documentation
operator<<
FArchive & operator<< (FArchive & Ar, FRigidBodyIndexPair & Pair) friend
Serializes the rigid body index pair to the passed in archive.
Parameters
Ar Archive to serialize data to.
Pair FRigidBodyIndexPair to serialize
Returns
returns the passed in FArchive after using it for serialization
Definition at line 49 of file RigidBodyIndexPair.h.
References FRigidBodyIndexPair(), Ar, and Indices.
Field Documentation
Indices
int32 FRigidBodyIndexPair::Indices[2]
Pair of indices.
Definition at line 13 of file RigidBodyIndexPair.h.
Referenced by FRigidBodyIndexPair(), GetTypeHash(), operator<<, and operator==().
The documentation for this struct was generated from the following file:
Runtime/Engine/Classes/PhysicsEngine/RigidBodyIndexPair.h