Unreal Engine 5.6 C++ API: UE::Geometry::FActorChildMesh Struct Reference
UE::Geometry::FActorChildMesh Struct Reference
FActorChildMesh represents a 3D Mesh attached to an Actor.
#include "MeshSceneAdapter.h"
Public Member Functions
FActorChildMesh ()
FActorChildMesh (const FActorChildMesh &)=delete
FActorChildMesh (FActorChildMesh &&)=delete
Data Fields
bool bIsNonUniformScaled = false
int32 ComponentIndex = 0
Index of this Mesh in the SourceComponent, if such an index exists (eg Instance Index in InstancedStaticMeshComponent)
EActorMeshComponentType ComponentType = EActorMeshComponentType::Unknown
Type of SourceComponent, if known.
FMeshTypeContainer MeshContainer
Wrapper around the Mesh this FActorChildMesh refers to (eg from a StaticMeshAsset, etc)
IMeshSpatialWrapper * MeshSpatial = nullptr
Spatial data structure that represents the Mesh in MeshContainer - assumption is this is owned externally.
UActorComponent * SourceComponent = nullptr
the Component this Mesh was generated from, if there is one.
FTransformSequence3d WorldTransform
Local-to-World transformation of the Mesh in the MeshContainer.
Detailed Description
FActorChildMesh represents a 3D Mesh attached to an Actor.
This generally comes from a Component, however in some cases a Component generates multiple FActorChildMesh (eg an InstancedStaticMeshComponent), and potentially some Actors may store/represent a Mesh directly (no examples currently).
Definition at line 212 of file MeshSceneAdapter.h.
Constructor & Destructor Documentation
FActorChildMesh() [1/3]
UE::Geometry::FActorChildMesh::FActorChildMesh () inline
Definition at line 215 of file MeshSceneAdapter.h.
Referenced by FActorChildMesh(), and FActorChildMesh().
FActorChildMesh() [2/3]
UE::Geometry::FActorChildMesh::FActorChildMesh (const FActorChildMesh &) delete
References FActorChildMesh().
FActorChildMesh() [3/3]
UE::Geometry::FActorChildMesh::FActorChildMesh (FActorChildMesh &&) delete
References FActorChildMesh().
Field Documentation
bIsNonUniformScaled
bool UE::Geometry::FActorChildMesh::bIsNonUniformScaled = false
Definition at line 230 of file MeshSceneAdapter.h.
ComponentIndex
int32 UE::Geometry::FActorChildMesh::ComponentIndex = 0
Index of this Mesh in the SourceComponent, if such an index exists (eg Instance Index in InstancedStaticMeshComponent)
Definition at line 224 of file MeshSceneAdapter.h.
ComponentType
EActorMeshComponentType UE::Geometry::FActorChildMesh::ComponentType = EActorMeshComponentType::Unknown
Type of SourceComponent, if known.
Definition at line 222 of file MeshSceneAdapter.h.
MeshContainer
FMeshTypeContainer UE::Geometry::FActorChildMesh::MeshContainer
Wrapper around the Mesh this FActorChildMesh refers to (eg from a StaticMeshAsset, etc)
Definition at line 227 of file MeshSceneAdapter.h.
MeshSpatial
IMeshSpatialWrapper* UE::Geometry::FActorChildMesh::MeshSpatial = nullptr
Spatial data structure that represents the Mesh in MeshContainer - assumption is this is owned externally.
Definition at line 233 of file MeshSceneAdapter.h.
SourceComponent
UActorComponent* UE::Geometry::FActorChildMesh::SourceComponent = nullptr
the Component this Mesh was generated from, if there is one.
Definition at line 220 of file MeshSceneAdapter.h.
WorldTransform
FTransformSequence3d UE::Geometry::FActorChildMesh::WorldTransform
Local-to-World transformation of the Mesh in the MeshContainer.
Definition at line 229 of file MeshSceneAdapter.h.
The documentation for this struct was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/MeshModelingToolset/Source/ModelingComponents/Public/Scene/MeshSceneAdapter.h