Unreal Engine 5.6 C++ API: FDisplayClusterWarpAABB Struct Reference
FDisplayClusterWarpAABB Struct Reference
Implement AABB math.
#include "DisplayClusterWarpAABB.h"
Public Member Functions
FDisplayClusterWarpAABB ()
FVector GetAABBPts (const uint32 InPtsIndex) const
The AABB defined by 8 points Get AABB 3d-cube points:
template<typename FArg>
void UpdateAABB (const FArg X, const FArg Y, const FArg Z)
Expand the value in AABB with the new values.
void UpdateAABB (const FDisplayClusterWarpAABB &InAABB)
Expand the value in AABB using the input AABB.
void UpdateAABB (const FVector &InPts)
Expand value in AABB with a new point.
void UpdateAABB (const FVector4f &InPts)
Expand value in AABB with a new point.
void UpdateAABB (const TArray< FVector > &InPoints)
Expand the value in AABB using the input point list.
Public Member Functions inherited from UE::Math::TBox< double >
constexpr TBox ()
Default constructor.
TBox (const TArray< TVector< double > > &Points)
Creates and initializes a new box from an array of points.
TBox (const TBox< FArg > &From)
TBox (const TSphere< double > &Sphere)
Creates and initializes a box that tightly encloses the given sphere.
TBox (const TVector4< double > &InMin, const TVector4< double > &InMax)
TBox (const TVector< double > *Points, const int32 Count)
Creates and initializes a new box from the given set of points.
TBox (const TVector< FArg > &InMin, const TVector< FArg > &InMax)
Creates and initializes a new box from the specified extents.
constexpr TBox (EForceInit)
Creates and initializes a new box with zero extent and marks it as invalid.
constexpr TBox (EForceInit, TBoxConstInit)
constexpr TBox (ENoInit)
Creates a new box without initialization.
FORCEINLINE double ComputeSquaredDistanceToBox (const TBox< double > &Box) const
Calculates squared distance between two boxes.
FORCEINLINE double ComputeSquaredDistanceToPoint (const TVector< double > &Point) const
Calculates the distance of a point to this box.
bool ContainsNaN () const
FORCEINLINE void DiagnosticCheck () const
bool Equals (const TBox< double > &Other, double Tolerance=UE_KINDA_SMALL_NUMBER) const
Check against another box for equality, within specified error limits.
TBox< double > ExpandBy (const TVector< double > &Neg, const TVector< double > &Pos) const
Returns a box of increased size.
FORCEINLINE TBox< double > ExpandBy (const TVector< double > &V) const
Returns a box of increased size.
FORCEINLINE TBox< double > ExpandBy (double W) const
Returns a box of increased size.
FORCEINLINE TVector< double > GetCenter () const
Gets the center point of this box.
FORCEINLINE void GetCenterAndExtents (TVector< double > &Center, TVector< double > &Extents) const
Gets the center and extents of this box.
FORCEINLINE TVector< double > GetClosestPointTo (const TVector< double > &Point) const
Calculates the closest point on or inside the box to a given point in space.
FORCEINLINE TVector< double > GetExtent () const
Gets the extents of this box.
FORCEINLINE TVector< double > GetSize () const
Gets the size of this box.
void GetVertices (TVector< double >(&Vertices)[8]) const
Get the vertices that make up this box.
FORCEINLINE double GetVolume () const
Gets the volume of this box.
FORCEINLINE void Init ()
Set the initial values of the bounding box to Zero.
FORCEINLINE bool Intersect (const TBox< double > &Other) const
Checks whether the given bounding box intersects this bounding box.
FORCEINLINE bool IntersectXY (const TBox< double > &Other) const
Checks whether the given bounding box intersects this bounding box in the XY plane.
TBox< double > InverseTransformBy (const TTransform< double > &M) const
Gets a bounding volume transformed by an inverted TTransform<T> object.
FORCEINLINE bool IsInside (const TBox< double > &Other) const
Checks whether a given box is fully encapsulated by this box.
FORCEINLINE bool IsInside (const TVector< double > &In) const
Checks whether the given location is inside this box.
FORCEINLINE bool IsInsideOrOn (const TBox< double > &Other) const
Checks whether a given box is fully encapsulated by this box.
FORCEINLINE bool IsInsideOrOn (const TVector< double > &In) const
Checks whether the given location is inside or on this box.
FORCEINLINE bool IsInsideOrOnXY (const TVector< double > &In) const
Checks whether the given location is inside or on this box in the XY plane.
FORCEINLINE bool IsInsideXY (const TBox< double > &Other) const
Checks whether the given box is fully encapsulated by this box in the XY plane.
FORCEINLINE bool IsInsideXY (const TVector< double > &In) const
Checks whether the given location is inside this box in the XY plane.
FORCEINLINE TBox< double > MoveTo (const TVector< double > &Destination) const
Returns a box with its center moved to the new destination.
FORCEINLINE bool operator!= (const TBox< double > &Other) const
Compares two boxes for inequality.
FORCEINLINE TBox< double > operator+ (const TBox< double > &Other) const
Gets the result of addition to this bounding volume.
FORCEINLINE TBox< double > operator+ (const TVector< double > &Other) const
Gets the result of addition to this bounding volume.
FORCEINLINE TBox< double > & operator+= (const TBox< double > &Other)
Adds to this bounding box to include a new bounding volume.
FORCEINLINE TBox< double > & operator+= (const TVector< double > &Other)
Adds to this bounding box to include a given point.
FORCEINLINE bool operator== (const TBox< double > &Other) const
Compares two boxes for equality.
FORCEINLINE TVector< double > & operator[] (int32 Index)
Gets reference to the min or max of this bounding volume.
FORCEINLINE const TVector< double > & operator[] (int32 Index) const
TBox< double > Overlap (const TBox< double > &Other) const
Returns the overlap TBox<T> of two box.
bool Serialize (FArchive &Ar)
bool Serialize (FStructuredArchive::FSlot Slot)
bool SerializeFromMismatchedTag (FName StructTag, FArchive &Ar)
FORCEINLINE TBox< double > ShiftBy (const TVector< double > &Offset) const
Returns a box with its position shifted.
FString ToCompactString () const
Get a textual representation of this box, without min/max values if invalid.
FString ToString () const
Get a textual representation of this box.
TBox< double > TransformBy (const TMatrix< double > &M) const
Gets a bounding volume transformed by a matrix.
TBox< double > TransformBy (const TTransform< double > &M) const
Gets a bounding volume transformed by a TTransform<T> object.
TBox< double > TransformProjectBy (const TMatrix< double > &ProjM) const
Returns the current world bounding box transformed and projected to screen space.
Additional Inherited Members
Public Types inherited from UE::Math::TBox< double >
using FReal
Static Public Member Functions inherited from UE::Math::TBox< double >
static TBox< double > BuildAABB (const TVector< double > &Origin, const TVector< double > &Extent)
Utility function to build an AABB from Origin and Extent.
Data Fields inherited from UE::Math::TBox< double >
uint8 IsValid
Holds a flag indicating whether this box is valid.
TVector< double > Max
Holds the box's maximum point.
TVector< double > Min
Holds the box's minimum point.
Detailed Description
Implement AABB math.
Definition at line 10 of file DisplayClusterWarpAABB.h.
Constructor & Destructor Documentation
FDisplayClusterWarpAABB()
FDisplayClusterWarpAABB::FDisplayClusterWarpAABB () inline
Definition at line 13 of file DisplayClusterWarpAABB.h.
References FVector.
Referenced by UpdateAABB().
Member Function Documentation
GetAABBPts()
FVector FDisplayClusterWarpAABB::GetAABBPts (const uint32 InPtsIndex) const inline
The AABB defined by 8 points Get AABB 3d-cube points:
Definition at line 63 of file DisplayClusterWarpAABB.h.
References FVector, UE::Math::TBox< double >::GetCenter(), UE::Math::TBox< double >::Max, and UE::Math::TBox< double >::Min.
UpdateAABB() [1/5]
template<typename FArg> void FDisplayClusterWarpAABB::UpdateAABB (const FArg X, const FArg Y, const FArg Z) inline
Expand the value in AABB with the new values.
Definition at line 19 of file DisplayClusterWarpAABB.h.
References FMath::Max, UE::Math::TBox< double >::Max, FMath::Min, UE::Math::TBox< double >::Min, X, Y, and Z.
Referenced by UpdateAABB(), UpdateAABB(), and UpdateAABB().
UpdateAABB() [2/5]
void FDisplayClusterWarpAABB::UpdateAABB (const FDisplayClusterWarpAABB & InAABB) inline
Expand the value in AABB using the input AABB.
Definition at line 55 of file DisplayClusterWarpAABB.h.
References FDisplayClusterWarpAABB(), and UE::Math::TBox< double >::operator+=().
UpdateAABB() [3/5]
void FDisplayClusterWarpAABB::UpdateAABB (const FVector & InPts) inline
Expand value in AABB with a new point.
Definition at line 40 of file DisplayClusterWarpAABB.h.
References FVector, UpdateAABB(), UE::Math::TVector< T >::X, UE::Math::TVector< T >::Y, and UE::Math::TVector< T >::Z.
UpdateAABB() [4/5]
void FDisplayClusterWarpAABB::UpdateAABB (const FVector4f & InPts) inline
Expand value in AABB with a new point.
Definition at line 31 of file DisplayClusterWarpAABB.h.
References UpdateAABB(), UE::Math::TVector4< T >::W, UE::Math::TVector4< T >::X, UE::Math::TVector4< T >::Y, and UE::Math::TVector4< T >::Z.
UpdateAABB() [5/5]
void FDisplayClusterWarpAABB::UpdateAABB (const TArray< FVector > & InPoints) inline
Expand the value in AABB using the input point list.
Definition at line 46 of file DisplayClusterWarpAABB.h.
References FVector, and UpdateAABB().
The documentation for this struct was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/nDisplay/Source/DisplayClusterWarp/Public/Containers/DisplayClusterWarpAABB.h