Unreal Engine 5.6 C++ API: FMovieSceneBlendTypeField Struct Reference
FMovieSceneBlendTypeField Struct Reference
Type that specifies a set of blend types that are supported for a particular section.
#include "MovieSceneBlendType.h"
Public Member Functions
MOVIESCENE_API FMovieSceneBlendTypeField ()
Constructor.
template<typename... E>
void Add (E... Types)
Add or remove the specified blend types.
MOVIESCENE_API void Add (EMovieSceneBlendType Type)
Add the specified blend type to this field.
MOVIESCENE_API void Add (FMovieSceneBlendTypeField Field)
MOVIESCENE_API bool Contains (EMovieSceneBlendType InBlendType) const
Check whether this field contains the specified blend type.
MOVIESCENE_API FMovieSceneBlendTypeField Invert () const
Invert this type field.
MOVIESCENE_API int32 Num () const
Count how many blend types are contained within this field.
template<typename... E>
void Remove (E... Types)
MOVIESCENE_API void Remove (EMovieSceneBlendType Type)
Remove the specified blend type from this field.
MOVIESCENE_API void Remove (FMovieSceneBlendTypeField Field)
Static Public Member Functions
static MOVIESCENE_API FMovieSceneBlendTypeField All ()
Retrieve a bit field representing all blend types.
static MOVIESCENE_API FMovieSceneBlendTypeField None ()
Retrieve a bit field representing No blend types.
Private Member Functions
FMovieSceneBlendTypeField (EMovieSceneBlendType InBlendTypeField)
Private Attributes
EMovieSceneBlendType BlendTypeField
The actual enumeration value representing all valid blend types.
Friends
bool operator!= (const FMovieSceneBlendTypeField &A, const FMovieSceneBlendTypeField &B)
bool operator== (const FMovieSceneBlendTypeField &A, const FMovieSceneBlendTypeField &B)
Detailed Description
Type that specifies a set of blend types that are supported for a particular section.
Implemented in this way to avoid direct use of EMovieSceneBlendType as bit flags.
Definition at line 93 of file MovieSceneBlendType.h.
Constructor & Destructor Documentation
FMovieSceneBlendTypeField() [1/2]
MOVIESCENE_API FMovieSceneBlendTypeField::FMovieSceneBlendTypeField ()
Constructor.
Referenced by Add(), All(), Invert(), None(), operator!=, operator==, and Remove().
FMovieSceneBlendTypeField() [2/2]
FMovieSceneBlendTypeField::FMovieSceneBlendTypeField (EMovieSceneBlendType InBlendTypeField) inline explicit private
Definition at line 154 of file MovieSceneBlendType.h.
References BlendTypeField.
Member Function Documentation
Add() [1/3]
template<typename... E> void FMovieSceneBlendTypeField::Add (E... Types) inline
Add or remove the specified blend types.
Definition at line 113 of file MovieSceneBlendType.h.
References Add().
Referenced by Add().
Add() [2/3]
MOVIESCENE_API void FMovieSceneBlendTypeField::Add (EMovieSceneBlendType Type)
Add the specified blend type to this field.
Add() [3/3]
MOVIESCENE_API void FMovieSceneBlendTypeField::Add (FMovieSceneBlendTypeField Field)
References FMovieSceneBlendTypeField().
All()
MOVIESCENE_API FMovieSceneBlendTypeField FMovieSceneBlendTypeField::All () static
Retrieve a bit field representing all blend types.
References FMovieSceneBlendTypeField().
Contains()
MOVIESCENE_API bool FMovieSceneBlendTypeField::Contains (EMovieSceneBlendType InBlendType) const
Check whether this field contains the specified blend type.
Invert()
MOVIESCENE_API FMovieSceneBlendTypeField FMovieSceneBlendTypeField::Invert () const
Invert this type field.
References FMovieSceneBlendTypeField().
None()
MOVIESCENE_API FMovieSceneBlendTypeField FMovieSceneBlendTypeField::None () static
Retrieve a bit field representing No blend types.
References FMovieSceneBlendTypeField().
Num()
MOVIESCENE_API int32 FMovieSceneBlendTypeField::Num () const
Count how many blend types are contained within this field.
Remove() [1/3]
template<typename... E> void FMovieSceneBlendTypeField::Remove (E... Types) inline
Definition at line 114 of file MovieSceneBlendType.h.
References Remove().
Referenced by Remove().
Remove() [2/3]
MOVIESCENE_API void FMovieSceneBlendTypeField::Remove (EMovieSceneBlendType Type)
Remove the specified blend type from this field.
Remove() [3/3]
MOVIESCENE_API void FMovieSceneBlendTypeField::Remove (FMovieSceneBlendTypeField Field)
References FMovieSceneBlendTypeField().
Friends And Related Symbol Documentation
operator!=
bool operator!= (const FMovieSceneBlendTypeField & A, const FMovieSceneBlendTypeField & B) friend
Definition at line 148 of file MovieSceneBlendType.h.
References FMovieSceneBlendTypeField(), A, and B.
operator==
bool operator== (const FMovieSceneBlendTypeField & A, const FMovieSceneBlendTypeField & B) friend
Definition at line 143 of file MovieSceneBlendType.h.
References FMovieSceneBlendTypeField(), A, and B.
Field Documentation
BlendTypeField
EMovieSceneBlendType FMovieSceneBlendTypeField::BlendTypeField private
The actual enumeration value representing all valid blend types.
Definition at line 157 of file MovieSceneBlendType.h.
Referenced by FMovieSceneBlendTypeField().
The documentation for this struct was generated from the following file:
Runtime/MovieScene/Public/Evaluation/Blending/MovieSceneBlendType.h