Unreal Engine 5.6 C++ API: FLandscapeTextureAtlas::FAllocation Struct Reference
FLandscapeTextureAtlas::FAllocation Struct Reference
Public Member Functions
FAllocation ()
FAllocation (UTexture2D *InTexture, uint32 InVisibilityChannel=0)
bool operator== (const FAllocation &Other) const
Data Fields
uint32 Handle
uint32 RefCount: 30
UTexture2D * SourceTexture
uint32 VisibilityChannel: 2
Friends
uint32 GetTypeHash (const FAllocation &Key)
Detailed Description
Definition at line 143 of file DistanceFieldAtlas.h.
Constructor & Destructor Documentation
FAllocation() [1/2]
FLandscapeTextureAtlas::FAllocation::FAllocation ()
Referenced by GetTypeHash, and operator==().
FAllocation() [2/2]
FLandscapeTextureAtlas::FAllocation::FAllocation (UTexture2D * InTexture, uint32 InVisibilityChannel = 0)
Member Function Documentation
operator==()
bool FLandscapeTextureAtlas::FAllocation::operator== (const FAllocation & Other) const inline
Definition at line 154 of file DistanceFieldAtlas.h.
References FAllocation(), Other, and SourceTexture.
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FAllocation & Key) friend
Definition at line 159 of file DistanceFieldAtlas.h.
References FAllocation(), GetTypeHash, and Key.
Referenced by GetTypeHash.
Field Documentation
Handle
uint32 FLandscapeTextureAtlas::FAllocation::Handle
Definition at line 146 of file DistanceFieldAtlas.h.
RefCount
uint32 FLandscapeTextureAtlas::FAllocation::RefCount
Definition at line 148 of file DistanceFieldAtlas.h.
SourceTexture
UTexture2D* FLandscapeTextureAtlas::FAllocation::SourceTexture
Definition at line 145 of file DistanceFieldAtlas.h.
Referenced by operator==().
VisibilityChannel
uint32 FLandscapeTextureAtlas::FAllocation::VisibilityChannel
Definition at line 147 of file DistanceFieldAtlas.h.
The documentation for this struct was generated from the following file:
Runtime/Engine/Public/DistanceFieldAtlas.h