Unreal Engine 5.6 C++ API: FPackedPosition Struct Reference
FPackedPosition Struct Reference
A 3x1 of xyz(11:11:10) format.
#include "RenderUtils.h"
Public Member Functions
FPackedPosition ()
FPackedPosition (const FVector3d &Other)
FPackedPosition (const FVector3f &Other)
VectorRegister GetVectorRegister () const
operator FVector3f () const
FPackedPosition & operator= (FVector3d Other)
FPackedPosition & operator= (FVector3f Other)
void Set (const FVector3d &InVector)
void Set (const FVector3f &InVector)
Data Fields
union {
uint32 Packed
struct {
int32 X: 11
int32 Y: 11
int32 Z: 10
} Vector
};
Friends
FArchive & operator<< (FArchive &Ar, FPackedPosition &N)
Detailed Description
A 3x1 of xyz(11:11:10) format.
Definition at line 68 of file RenderUtils.h.
Constructor & Destructor Documentation
FPackedPosition() [1/3]
FPackedPosition::FPackedPosition () inline
Definition at line 89 of file RenderUtils.h.
References Packed.
Referenced by operator<<, operator=(), and operator=().
FPackedPosition() [2/3]
FPackedPosition::FPackedPosition (const FVector3f & Other) inline
Definition at line 90 of file RenderUtils.h.
References Other, Packed, and Set().
FPackedPosition() [3/3]
FPackedPosition::FPackedPosition (const FVector3d & Other) inline
Definition at line 94 of file RenderUtils.h.
References Other, Packed, and Set().
Member Function Documentation
GetVectorRegister()
VectorRegister FPackedPosition::GetVectorRegister () const
operator FVector3f()
FPackedPosition::operator FVector3f () const
operator=() [1/2]
FPackedPosition & FPackedPosition::operator= (FVector3d Other) inline
Definition at line 105 of file RenderUtils.h.
References FPackedPosition(), Other, and Set().
operator=() [2/2]
FPackedPosition & FPackedPosition::operator= (FVector3f Other) inline
Definition at line 100 of file RenderUtils.h.
References FPackedPosition(), Other, and Set().
Set() [1/2]
void FPackedPosition::Set (const FVector3d & InVector)
Set() [2/2]
void FPackedPosition::Set (const FVector3f & InVector)
Referenced by FPackedPosition(), FPackedPosition(), operator=(), and operator=().
Friends And Related Symbol Documentation
operator<<
FArchive & operator<< (FArchive & Ar, FPackedPosition & N) friend
References FPackedPosition(), and Ar.
Field Documentation
[union]
union { ... } FPackedPosition
Packed
uint32 FPackedPosition::Packed
Definition at line 85 of file RenderUtils.h.
Referenced by FPackedPosition(), FPackedPosition(), and FPackedPosition().
[struct]
struct { ... } FPackedPosition::Vector
X
int32 FPackedPosition::X
Definition at line 81 of file RenderUtils.h.
Y
int32 FPackedPosition::Y
Definition at line 80 of file RenderUtils.h.
Z
int32 FPackedPosition::Z
Definition at line 79 of file RenderUtils.h.
The documentation for this struct was generated from the following file:
Runtime/RenderCore/Public/RenderUtils.h