Unreal Engine 5.6 C++ API: TDefaultNumericTypeInterface< NumericType > Struct Template Reference
TDefaultNumericTypeInterface< NumericType > Struct Template Reference
Default numeric type interface.
#include "NumericTypeInterface.h"
Public Member Functions
virtual TOptional< NumericType > FromString (const FString &InString, const NumericType &InExistingValue) override
virtual bool GetIndicateNearlyInteger () const override
Get if we should indicate nearly integer values.
virtual int32 GetMaxFractionalDigits () const override
virtual int32 GetMinFractionalDigits () const override
Gets the minimum and maximum fractional digits.
virtual bool IsCharacterValid (TCHAR InChar) const override
Check whether the typed character is valid.
virtual void SetIndicateNearlyInteger (const TAttribute< TOptional< bool > > &NewValue) override
Sets if we should indicate that a value is being rounded to an integer via '...' (Ex: 0.0 shown, real value 1e-18).
virtual void SetMaxFractionalDigits (const TAttribute< TOptional< int32 > > &NewValue) override
virtual void SetMinFractionalDigits (const TAttribute< TOptional< int32 > > &NewValue) override
Sets the minimum and maximum fractional digits - A minimum greater than 0 will always have that many trailing zeros.
virtual FString ToString (const NumericType &Value) const override
Convert the type to/from a string.
Public Member Functions inherited from INumericTypeInterface< NumericType >
virtual ~INumericTypeInterface ()
virtual FOnSettingChanged * GetOnSettingChanged ()
Optional callback to broadcast when a setting in the type interface changes.
Data Fields
bool bIndicateNearlyInteger = false
True implies indicate when a value is displayed as rounded via '...'.
int16 MaxFractionalDigits = DefaultMaxFractionalDigits
The current maximum fractional digits.
int16 MinFractionalDigits = DefaultMinFractionalDigits
The current minimum fractional digits.
Static Public Attributes
static const bool DefaultIndicateNearlyInteger = false
The default indicate nearly integer.
static const int16 DefaultMaxFractionalDigits = 6
The default maximum fractional digits.
static const int16 DefaultMinFractionalDigits = 1
The default minimum fractional digits.
Detailed Description
template<typename NumericType>
struct TDefaultNumericTypeInterface< NumericType >
Default numeric type interface.
Definition at line 49 of file NumericTypeInterface.h.
Member Function Documentation
FromString()
template<typename NumericType> virtual TOptional< NumericType > TDefaultNumericTypeInterface< NumericType >::FromString (const FString & InString, const NumericType & InExistingValue) inline override virtual
Implements INumericTypeInterface< NumericType >.
Reimplemented in TNumericUnitTypeInterface< NumericType >.
Definition at line 116 of file NumericTypeInterface.h.
References FMath::Clamp(), FBasicMathExpressionEvaluator::Evaluate(), FastDecimalFormat::GetCultureAgnosticFormattingRules(), FNumberParsingOptions::SetUseClamping(), FNumberParsingOptions::SetUseGrouping(), and FastDecimalFormat::StringToNumber().
Referenced by SGraphPinVector< NumericType >::ConvertDefaultValueStringToVector(), and SGraphPinVectorSlider< NumericType >::ConvertDefaultValueStringToVector().
GetIndicateNearlyInteger()
template<typename NumericType> virtual bool TDefaultNumericTypeInterface< NumericType >::GetIndicateNearlyInteger () const inline override virtual
Get if we should indicate nearly integer values.
Reimplemented from INumericTypeInterface< NumericType >.
Definition at line 81 of file NumericTypeInterface.h.
References bIndicateNearlyInteger.
GetMaxFractionalDigits()
template<typename NumericType> virtual int32 TDefaultNumericTypeInterface< NumericType >::GetMaxFractionalDigits () const inline override virtual
Implements INumericTypeInterface< NumericType >.
Definition at line 75 of file NumericTypeInterface.h.
References IntCastChecked(), and MaxFractionalDigits.
GetMinFractionalDigits()
template<typename NumericType> virtual int32 TDefaultNumericTypeInterface< NumericType >::GetMinFractionalDigits () const inline override virtual
Gets the minimum and maximum fractional digits.
Implements INumericTypeInterface< NumericType >.
Definition at line 71 of file NumericTypeInterface.h.
References IntCastChecked(), and MinFractionalDigits.
IsCharacterValid()
template<typename NumericType> virtual bool TDefaultNumericTypeInterface< NumericType >::IsCharacterValid (TCHAR InChar) const inline override virtual
Check whether the typed character is valid.
Implements INumericTypeInterface< NumericType >.
Reimplemented in TNumericUnitTypeInterface< NumericType >.
Definition at line 154 of file NumericTypeInterface.h.
References FDecimalNumberFormattingRules::DecimalSeparatorCharacter, FDecimalNumberFormattingRules::DigitCharacters, Algo::Find(), FDecimalNumberFormattingRules::GroupingSeparatorCharacter, and TEXT.
SetIndicateNearlyInteger()
template<typename NumericType> virtual void TDefaultNumericTypeInterface< NumericType >::SetIndicateNearlyInteger (const TAttribute< TOptional< bool > > & NewValue) inline override virtual
Sets if we should indicate that a value is being rounded to an integer via '...' (Ex: 0.0 shown, real value 1e-18).
Reimplemented from INumericTypeInterface< NumericType >.
Definition at line 99 of file NumericTypeInterface.h.
References bIndicateNearlyInteger, and DefaultIndicateNearlyInteger.
SetMaxFractionalDigits()
template<typename NumericType> virtual void TDefaultNumericTypeInterface< NumericType >::SetMaxFractionalDigits (const TAttribute< TOptional< int32 > > & NewValue) inline override virtual
Implements INumericTypeInterface< NumericType >.
Definition at line 93 of file NumericTypeInterface.h.
References DefaultMaxFractionalDigits, IntCastChecked(), FMath::Max, and MaxFractionalDigits.
SetMinFractionalDigits()
template<typename NumericType> virtual void TDefaultNumericTypeInterface< NumericType >::SetMinFractionalDigits (const TAttribute< TOptional< int32 > > & NewValue) inline override virtual
Sets the minimum and maximum fractional digits - A minimum greater than 0 will always have that many trailing zeros.
Implements INumericTypeInterface< NumericType >.
Definition at line 87 of file NumericTypeInterface.h.
References DefaultMinFractionalDigits, IntCastChecked(), FMath::Max, and MinFractionalDigits.
ToString()
template<typename NumericType> virtual FString TDefaultNumericTypeInterface< NumericType >::ToString (const NumericType & Value) const inline override virtual
Convert the type to/from a string.
Implements INumericTypeInterface< NumericType >.
Reimplemented in FVariablePrecisionNumericInterface, FVariablePrecisionNumericInterface, and TNumericUnitTypeInterface< NumericType >.
Definition at line 106 of file NumericTypeInterface.h.
References bIndicateNearlyInteger, FMath::Max, MaxFractionalDigits, MinFractionalDigits, FastDecimalFormat::NumberToString(), FNumberFormattingOptions::SetIndicateNearlyInteger(), FNumberFormattingOptions::SetMaximumFractionalDigits(), FNumberFormattingOptions::SetMinimumFractionalDigits(), FNumberFormattingOptions::SetUseGrouping(), TIsIntegral< T >::Value, and Value.
Field Documentation
bIndicateNearlyInteger
template<typename NumericType> bool TDefaultNumericTypeInterface< NumericType >::bIndicateNearlyInteger = false
True implies indicate when a value is displayed as rounded via '...'.
Definition at line 68 of file NumericTypeInterface.h.
Referenced by GetIndicateNearlyInteger(), SetIndicateNearlyInteger(), and ToString().
DefaultIndicateNearlyInteger
template<typename NumericType> const bool TDefaultNumericTypeInterface< NumericType >::DefaultIndicateNearlyInteger = false static
The default indicate nearly integer.
Definition at line 59 of file NumericTypeInterface.h.
Referenced by SetIndicateNearlyInteger().
DefaultMaxFractionalDigits
template<typename NumericType> const int16 TDefaultNumericTypeInterface< NumericType >::DefaultMaxFractionalDigits = 6 static
The default maximum fractional digits.
Definition at line 56 of file NumericTypeInterface.h.
Referenced by SetMaxFractionalDigits().
DefaultMinFractionalDigits
template<typename NumericType> const int16 TDefaultNumericTypeInterface< NumericType >::DefaultMinFractionalDigits = 1 static
The default minimum fractional digits.
Definition at line 53 of file NumericTypeInterface.h.
Referenced by SetMinFractionalDigits().
MaxFractionalDigits
template<typename NumericType> int16 TDefaultNumericTypeInterface< NumericType >::MaxFractionalDigits = DefaultMaxFractionalDigits
The current maximum fractional digits.
Definition at line 65 of file NumericTypeInterface.h.
Referenced by GetMaxFractionalDigits(), SetMaxFractionalDigits(), and ToString().
MinFractionalDigits
template<typename NumericType> int16 TDefaultNumericTypeInterface< NumericType >::MinFractionalDigits = DefaultMinFractionalDigits
The current minimum fractional digits.
Definition at line 62 of file NumericTypeInterface.h.
Referenced by GetMinFractionalDigits(), SetMinFractionalDigits(), and ToString().
The documentation for this struct was generated from the following file:
Runtime/Slate/Public/Widgets/Input/NumericTypeInterface.h