Unreal Engine 5.6 C++ API: UE::Anim::TNamedValueArray< InAllocatorType, InElementType > Struct Template Reference
UE::Anim::TNamedValueArray< InAllocatorType, InElementType > Struct Template Reference
Container of lazily-sorted name/value pairs.
#include "NamedValueArray.h"
Data Structures
struct FElementSortPredicate
Public Types
typedef InAllocatorType AllocatorType
typedef InElementType ElementType
Public Member Functions
template<typename... ArgTypes>
void Add (ArgTypes &&... Args)
Add a named element.
void AppendNames (std::initializer_list< const FName > InInputArgs)
Add an array of named elements.
void AppendNames (TConstArrayView< FName > InNameArray)
Add an array of named elements.
void Empty ()
Reset the internal allocations.
template<typename PredicateType>
void ForEachElement (PredicateType InPredicate) const
Iterate over each element calling InPredicate for each.
bool HasElement (FName InName) const
Check whether an element is present for the supplied name Note that this performs a binary search per-call.
int32 Max () const
int32 Num () const
void Reserve (int32 InNumElements)
Reserves memory for InNumElements.
void Shrink ()
Compacts the memory for the elements based on what was actually used.
Protected Member Functions
void CheckDuplicates () const
void CheckSorted () const
ElementType * Find (FName InName)
Finds the element with the specified name.
const ElementType * Find (FName InName) const
Finds the element with the specified name (const)
int32 IndexOf (FName InName) const
Finds index of the element with the specified name, disregarding enabled state.
void SortElementsIfRequired () const
Protected Attributes
bool bSorted = false
TArray< ElementType, AllocatorType > Elements
Friends
struct FNamedValueArrayUtils
Detailed Description
template<typename InAllocatorType, typename InElementType>
struct UE::Anim::TNamedValueArray< InAllocatorType, InElementType >
Container of lazily-sorted name/value pairs.
Used to perform efficient merge operations. Assumes that InElementType has an accessible member: FName Name.
Definition at line 34 of file NamedValueArray.h.
Member Typedef Documentation
AllocatorType
template<typename InAllocatorType, typename InElementType> typedef InAllocatorType UE::Anim::TNamedValueArray< InAllocatorType, InElementType >::AllocatorType
Definition at line 36 of file NamedValueArray.h.
ElementType
template<typename InAllocatorType, typename InElementType> typedef InElementType UE::Anim::TNamedValueArray< InAllocatorType, InElementType >::ElementType
Definition at line 37 of file NamedValueArray.h.
Member Function Documentation
Add()
template<typename InAllocatorType, typename InElementType> template<typename... ArgTypes> void UE::Anim::TNamedValueArray< InAllocatorType, InElementType >::Add (ArgTypes &&... Args) inline
Add a named element.
Note that this should only really be used when building a fresh value array, as using this during runtime can introduce duplicate values. Asserts in debug builds if duplicate values are present
Definition at line 48 of file NamedValueArray.h.
AppendNames() [1/2]
template<typename InAllocatorType, typename InElementType> void UE::Anim::TNamedValueArray< InAllocatorType, InElementType >::AppendNames (std::initializer_list< const FName > InInputArgs) inline
Add an array of named elements.
Note that this should only really be used when building a fresh array, as using this during runtime can introduce duplicate values. Asserts in debug builds if duplicate values are present
Definition at line 80 of file NamedValueArray.h.
AppendNames() [2/2]
template<typename InAllocatorType, typename InElementType> void UE::Anim::TNamedValueArray< InAllocatorType, InElementType >::AppendNames (TConstArrayView< FName > InNameArray) inline
Add an array of named elements.
Note that this should only really be used when building a fresh array, as using this during runtime can introduce duplicate values. Asserts in debug builds if duplicate values are present
Definition at line 62 of file NamedValueArray.h.
CheckDuplicates()
template<typename InAllocatorType, typename InElementType> void UE::Anim::TNamedValueArray< InAllocatorType, InElementType >::CheckDuplicates () const inline protected
Definition at line 181 of file NamedValueArray.h.
Referenced by UE::Anim::TNamedValueArray< AllocatorType, FCurveFilterElement >::Add(), UE::Anim::TNamedValueArray< AllocatorType, FCurveFilterElement >::AppendNames(), UE::Anim::TNamedValueArray< AllocatorType, FCurveFilterElement >::AppendNames(), UE::Anim::FCurveUtils::BuildLinearUnfiltered(), UE::Anim::FCurveUtils::BuildLinearUnfiltered(), UE::Anim::FCurveUtils::BuildSortedFiltered(), UE::Anim::FCurveUtils::BuildUnsorted(), UE::Anim::FCurveUtils::BuildUnsorted(), UE::Anim::FCurveUtils::BuildUnsorted(), and UE::Anim::FCurveUtils::BuildUnsorted().
CheckSorted()
template<typename InAllocatorType, typename InElementType> void UE::Anim::TNamedValueArray< InAllocatorType, InElementType >::CheckSorted () const inline protected
Definition at line 170 of file NamedValueArray.h.
Referenced by UE::Anim::FCurveUtils::BuildSorted(), UE::Anim::FCurveUtils::BuildUnsorted(), UE::Anim::FCurveUtils::Filter(), UE::Anim::FNamedValueArrayUtils::RemoveByPredicate(), UE::Anim::FNamedValueArrayUtils::Union(), and UE::Anim::FNamedValueArrayUtils::Union().
Empty()
template<typename InAllocatorType, typename InElementType> void UE::Anim::TNamedValueArray< InAllocatorType, InElementType >::Empty () inline
Reset the internal allocations.
Definition at line 93 of file NamedValueArray.h.
Referenced by UE::Anim::FCurveUtils::BuildLinearUnfiltered(), UE::Anim::FCurveUtils::BuildLinearUnfiltered(), UE::Anim::FCurveUtils::BuildSortedFiltered(), UE::Anim::FCurveUtils::BuildUnsorted(), UE::Anim::FCurveUtils::BuildUnsorted(), UE::Anim::FCurveUtils::BuildUnsorted(), UE::Anim::FCurveUtils::BuildUnsorted(), and UE::Anim::FCurveUtils::BuildUnsorted().
Find() [1/2]
template<typename InAllocatorType, typename InElementType> ElementType * UE::Anim::TNamedValueArray< InAllocatorType, InElementType >::Find (FName InName) inline protected
Finds the element with the specified name.
Definition at line 217 of file NamedValueArray.h.
Find() [2/2]
template<typename InAllocatorType, typename InElementType> const ElementType * UE::Anim::TNamedValueArray< InAllocatorType, InElementType >::Find (FName InName) const inline protected
Finds the element with the specified name (const)
Definition at line 206 of file NamedValueArray.h.
ForEachElement()
template<typename InAllocatorType, typename InElementType> template<typename PredicateType> void UE::Anim::TNamedValueArray< InAllocatorType, InElementType >::ForEachElement (PredicateType InPredicate) const inline
Iterate over each element calling InPredicate for each.
Predicate: (const ElementType&) -> void
Definition at line 121 of file NamedValueArray.h.
HasElement()
template<typename InAllocatorType, typename InElementType> bool UE::Anim::TNamedValueArray< InAllocatorType, InElementType >::HasElement (FName InName) const inline
Check whether an element is present for the supplied name Note that this performs a binary search per-call.
Parameters
InName the name of the element to check
Returns
true if an element with the supplied name is present
Definition at line 111 of file NamedValueArray.h.
IndexOf()
template<typename InAllocatorType, typename InElementType> int32 UE::Anim::TNamedValueArray< InAllocatorType, InElementType >::IndexOf (FName InName) const inline protected
Finds index of the element with the specified name, disregarding enabled state.
Definition at line 198 of file NamedValueArray.h.
Referenced by UE::Anim::TNamedValueArray< AllocatorType, FCurveFilterElement >::Find(), and UE::Anim::TNamedValueArray< AllocatorType, FCurveFilterElement >::Find().
Max()
template<typename InAllocatorType, typename InElementType> int32 UE::Anim::TNamedValueArray< InAllocatorType, InElementType >::Max () const inline
Returns
the max number of elements reserved in the array
Definition at line 136 of file NamedValueArray.h.
Num()
template<typename InAllocatorType, typename InElementType> int32 UE::Anim::TNamedValueArray< InAllocatorType, InElementType >::Num () const inline
Returns
the number of elements
Definition at line 130 of file NamedValueArray.h.
Referenced by UE::Anim::FCurveUtils::Filter(), UE::Anim::FNamedValueArrayUtils::Intersection(), UE::Anim::FNamedValueArrayUtils::RemoveByPredicate(), UE::Anim::FNamedValueArrayUtils::Union(), UE::Anim::FNamedValueArrayUtils::Union(), UE::Anim::FNamedValueArrayUtils::Union(), and UE::Anim::FNamedValueArrayUtils::Union().
Reserve()
template<typename InAllocatorType, typename InElementType> void UE::Anim::TNamedValueArray< InAllocatorType, InElementType >::Reserve (int32 InNumElements) inline
Reserves memory for InNumElements.
Definition at line 100 of file NamedValueArray.h.
Referenced by UE::Anim::FNamedValueArrayUtils::Union(), and UE::Anim::FNamedValueArrayUtils::Union().
Shrink()
template<typename InAllocatorType, typename InElementType> void UE::Anim::TNamedValueArray< InAllocatorType, InElementType >::Shrink () inline
Compacts the memory for the elements based on what was actually used.
Definition at line 142 of file NamedValueArray.h.
SortElementsIfRequired()
template<typename InAllocatorType, typename InElementType> void UE::Anim::TNamedValueArray< InAllocatorType, InElementType >::SortElementsIfRequired () const inline protected
Definition at line 158 of file NamedValueArray.h.
Referenced by UE::Anim::FCurveUtils::BuildSortedFiltered(), UE::Anim::FCurveUtils::Filter(), UE::Anim::TNamedValueArray< AllocatorType, FCurveFilterElement >::IndexOf(), UE::Anim::FNamedValueArrayUtils::Intersection(), UE::Anim::FNamedValueArrayUtils::RemoveByPredicate(), UE::Anim::FNamedValueArrayUtils::Union(), UE::Anim::FNamedValueArrayUtils::Union(), and UE::Anim::FNamedValueArrayUtils::Union().
Friends And Related Symbol Documentation
FNamedValueArrayUtils
template<typename InAllocatorType, typename InElementType> friend struct FNamedValueArrayUtils friend
Definition at line 39 of file NamedValueArray.h.
Field Documentation
bSorted
template<typename InAllocatorType, typename InElementType> bool UE::Anim::TNamedValueArray< InAllocatorType, InElementType >::bSorted = false mutable protected
Definition at line 232 of file NamedValueArray.h.
Referenced by UE::Anim::FCurveUtils::BuildSorted(), UE::Anim::FCurveUtils::BuildUnsorted(), TBaseBlendedCurve< InAllocatorType, InElementType >::CopyFrom(), TBaseBlendedCurve< InAllocatorType, InElementType >::MoveFrom(), TBaseBlendedCurve< InAllocatorType, InElementType >::OverrideMove(), UE::Anim::FNamedValueArrayUtils::Union(), and UE::Anim::FNamedValueArrayUtils::Union().
Elements
template<typename InAllocatorType, typename InElementType> TArray<ElementType, AllocatorType> UE::Anim::TNamedValueArray< InAllocatorType, InElementType >::Elements mutable protected
Definition at line 229 of file NamedValueArray.h.
Referenced by UE::Anim::FCurveUtils::BuildLinearUnfiltered(), UE::Anim::FCurveUtils::BuildLinearUnfiltered(), UE::Anim::FCurveUtils::BuildSortedFiltered(), UE::Anim::FCurveUtils::BuildUnsorted(), UE::Anim::FCurveUtils::BuildUnsorted(), UE::Anim::FCurveUtils::BuildUnsorted(), UE::Anim::FCurveUtils::BuildUnsorted(), UE::Anim::FCurveUtils::BuildUnsorted(), TBaseBlendedCurve< InAllocatorType, InElementType >::CopyFrom(), UE::Anim::FCurveUtils::Filter(), UE::Anim::FNamedValueArrayUtils::Intersection(), TBaseBlendedCurve< InAllocatorType, InElementType >::MoveFrom(), TBaseBlendedCurve< InAllocatorType, InElementType >::OverrideMove(), UE::Anim::FNamedValueArrayUtils::RemoveByPredicate(), UE::Anim::FNamedValueArrayUtils::Union(), UE::Anim::FNamedValueArrayUtils::Union(), UE::Anim::FNamedValueArrayUtils::Union(), and UE::Anim::FNamedValueArrayUtils::Union().
The documentation for this struct was generated from the following file:
Runtime/Engine/Public/Animation/NamedValueArray.h