Unreal Engine 5.6 C++ API: ISequencerInputHandler Struct Reference
ISequencerInputHandler Struct Reference abstract
Common base-class for objects that handle input in the sequencer.
#include "ISequencerInputHandler.h"
Public Member Functions
virtual FReply OnKeyDown (SWidget &OwnerWidget, const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
virtual FReply OnKeyUp (SWidget &OwnerWidget, const FGeometry &MyGeometry, const FKeyEvent &InKeyEvent)
virtual FReply OnMouseButtonDoubleClick (SWidget &OwnerWidget, const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)=0
virtual FReply OnMouseButtonDown (SWidget &OwnerWidget, const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)=0
virtual FReply OnMouseButtonUp (SWidget &OwnerWidget, const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)=0
virtual FReply OnMouseMove (SWidget &OwnerWidget, const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)=0
virtual FReply OnMouseWheel (SWidget &OwnerWidget, const FGeometry &MyGeometry, const FPointerEvent &MouseEvent)=0
Detailed Description
Common base-class for objects that handle input in the sequencer.
Definition at line 13 of file ISequencerInputHandler.h.
Member Function Documentation
OnKeyDown()
virtual FReply ISequencerInputHandler::OnKeyDown (SWidget & OwnerWidget, const FGeometry & MyGeometry, const FKeyEvent & InKeyEvent) inline virtual
Reimplemented in UE::Sequencer::ISequencerEditTool.
Definition at line 20 of file ISequencerInputHandler.h.
References FReply::Unhandled().
Referenced by UE::Sequencer::FInputHandlerStack::HandleKeyDown().
OnKeyUp()
virtual FReply ISequencerInputHandler::OnKeyUp (SWidget & OwnerWidget, const FGeometry & MyGeometry, const FKeyEvent & InKeyEvent) inline virtual
Reimplemented in UE::Sequencer::ISequencerEditTool.
Definition at line 21 of file ISequencerInputHandler.h.
References FReply::Unhandled().
Referenced by UE::Sequencer::FInputHandlerStack::HandleKeyUp().
OnMouseButtonDoubleClick()
virtual FReply ISequencerInputHandler::OnMouseButtonDoubleClick (SWidget & OwnerWidget, const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) pure virtual
References MouseEvent.
Referenced by UE::Sequencer::FInputHandlerStack::HandleMouseDoubleClick().
OnMouseButtonDown()
virtual FReply ISequencerInputHandler::OnMouseButtonDown (SWidget & OwnerWidget, const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) pure virtual
References MouseEvent.
Referenced by UE::Sequencer::FInputHandlerStack::HandleMouseButtonDown().
OnMouseButtonUp()
virtual FReply ISequencerInputHandler::OnMouseButtonUp (SWidget & OwnerWidget, const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) pure virtual
References MouseEvent.
Referenced by UE::Sequencer::FInputHandlerStack::HandleMouseButtonUp().
OnMouseMove()
virtual FReply ISequencerInputHandler::OnMouseMove (SWidget & OwnerWidget, const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) pure virtual
References MouseEvent.
Referenced by UE::Sequencer::FInputHandlerStack::HandleMouseMove().
OnMouseWheel()
virtual FReply ISequencerInputHandler::OnMouseWheel (SWidget & OwnerWidget, const FGeometry & MyGeometry, const FPointerEvent & MouseEvent) pure virtual
References MouseEvent.
Referenced by UE::Sequencer::FInputHandlerStack::HandleMouseWheel().
The documentation for this struct was generated from the following file:
Editor/SequencerCore/Public/ISequencerInputHandler.h