Unreal Engine 5.6 C++ API: FMovieSceneAnimTypeID Struct Reference
FMovieSceneAnimTypeID Struct Reference
Animation type ID that uniquely identifies the type of a change made (ie changing a transform, spawning an object, etc) as part of a sequence evaluation.
#include "MovieSceneAnimTypeID.h"
Static Public Member Functions
static MOVIESCENE_API FMovieSceneAnimTypeID Combine (FMovieSceneAnimTypeID A, FMovieSceneAnimTypeID B)
static MOVIESCENE_API FMovieSceneAnimTypeID Unique ()
Protected Member Functions
FMovieSceneAnimTypeID ()
FMovieSceneAnimTypeID (uint64 *StaticPtr, uint32 Seed=0)
Static Protected Member Functions
static MOVIESCENE_API uint64 GenerateHash (void *StaticPtr, uint32 Seed)
Generate a hash from the specified static ptr.
static MOVIESCENE_API uint64 Initialize (uint64 *StaticPtr, uint32 Seed)
Initialize this structure by storing the hash result in the static ptr itself This ensures subsequent constructions with the same pointer are fast.
Protected Attributes
uint64 ID
Friends
uint32 GetTypeHash (FMovieSceneAnimTypeID In)
MOVIESCENE_API FString LexToString (const FMovieSceneAnimTypeID &)
bool operator!= (FMovieSceneAnimTypeID A, FMovieSceneAnimTypeID B)
bool operator== (FMovieSceneAnimTypeID A, FMovieSceneAnimTypeID B)
Detailed Description
Animation type ID that uniquely identifies the type of a change made (ie changing a transform, spawning an object, etc) as part of a sequence evaluation.
Definition at line 19 of file MovieSceneAnimTypeID.h.
Constructor & Destructor Documentation
FMovieSceneAnimTypeID() [1/2]
FMovieSceneAnimTypeID::FMovieSceneAnimTypeID (uint64 * StaticPtr, uint32 Seed = 0) inline protected
Definition at line 44 of file MovieSceneAnimTypeID.h.
References ID, Initialize(), and Seed.
Referenced by FMovieSceneBlendingActuatorID::FMovieSceneBlendingActuatorID(), TMovieSceneAnimTypeID< T, Seed >::TMovieSceneAnimTypeID(), Combine(), GetTypeHash, LexToString, operator!=, operator==, and Unique().
FMovieSceneAnimTypeID() [2/2]
FMovieSceneAnimTypeID::FMovieSceneAnimTypeID () inline protected
Definition at line 47 of file MovieSceneAnimTypeID.h.
References ID.
Member Function Documentation
Combine()
MOVIESCENE_API FMovieSceneAnimTypeID FMovieSceneAnimTypeID::Combine (FMovieSceneAnimTypeID A, FMovieSceneAnimTypeID B) static
References FMovieSceneAnimTypeID(), A, and B.
GenerateHash()
MOVIESCENE_API uint64 FMovieSceneAnimTypeID::GenerateHash (void * StaticPtr, uint32 Seed) static protected
Generate a hash from the specified static ptr.
References Seed.
Referenced by TMovieSceneAnimTypeIDContainer< DataType >::FTypeID::FTypeID().
Initialize()
MOVIESCENE_API uint64 FMovieSceneAnimTypeID::Initialize (uint64 * StaticPtr, uint32 Seed) static protected
Initialize this structure by storing the hash result in the static ptr itself This ensures subsequent constructions with the same pointer are fast.
References Seed.
Referenced by FMovieSceneAnimTypeID().
Unique()
MOVIESCENE_API FMovieSceneAnimTypeID FMovieSceneAnimTypeID::Unique () static
References FMovieSceneAnimTypeID().
Referenced by GetBlendingDataType().
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (FMovieSceneAnimTypeID In) friend
Definition at line 31 of file MovieSceneAnimTypeID.h.
References FMovieSceneAnimTypeID(), GetTypeHash, and ID.
Referenced by GetTypeHash.
LexToString
MOVIESCENE_API FString LexToString (const FMovieSceneAnimTypeID &) friend
References FMovieSceneAnimTypeID().
operator!=
bool operator!= (FMovieSceneAnimTypeID A, FMovieSceneAnimTypeID B) friend
Definition at line 26 of file MovieSceneAnimTypeID.h.
References FMovieSceneAnimTypeID(), A, and B.
operator==
bool operator== (FMovieSceneAnimTypeID A, FMovieSceneAnimTypeID B) friend
Definition at line 21 of file MovieSceneAnimTypeID.h.
References FMovieSceneAnimTypeID(), A, and B.
Field Documentation
ID
uint64 FMovieSceneAnimTypeID::ID protected
Definition at line 62 of file MovieSceneAnimTypeID.h.
Referenced by FMovieSceneAnimTypeID(), FMovieSceneAnimTypeID(), TMovieSceneAnimTypeIDContainer< DataType >::FTypeID::FTypeID(), GetTypeHash, and FMovieSceneBlendingActuatorID::GetTypeHash.
The documentation for this struct was generated from the following file:
Runtime/MovieScene/Public/Evaluation/MovieSceneAnimTypeID.h