Unreal Engine 5.6 C++ API: FMovieSceneChannelEntry Struct Reference
FMovieSceneChannelEntry Struct Reference
An entry within FMovieSceneChannelProxy that contains all channels (and editor data) for any given channel type.
#include "MovieSceneChannelProxy.h"
Public Member Functions
template<typename ChannelType>
TArrayView< const typename TMovieSceneChannelTraits< ChannelType >::ExtendedEditorDataType > GetAllExtendedEditorData () const
Access extended typed editor data for channels stored in this entry.
TArrayView< FMovieSceneChannel *const > GetChannels () const
Access all the channels contained within this entry.
FName GetChannelTypeName () const
Get the type name of the channels stored in this entry.
Public Member Functions inherited from FMovieSceneChannelEditorDataEntry
template<typename ChannelType>
FMovieSceneChannelEditorDataEntry (const ChannelType &Channel)
Templated constructor that uses the channel parameter to construct the editor data array from the correct editor data type.
const void * GetExtendedEditorData (int32 ChannelIndex) const
Access the extended editor data for a specific channel.
TArrayView< const FMovieSceneChannelMetaData > GetMetaData () const
Get the common editor data for all channels.
Private Member Functions
template<typename ChannelType>
FMovieSceneChannelEntry (FName InChannelTypeName, const ChannelType &Channel)
Templated constructor from the channel and its ID.
Private Attributes
TArray< FMovieSceneChannel * > Channels
Pointers to the channels that this entry contains.
FName ChannelTypeName
The name of the channel's struct type.
friend FMovieSceneChannelProxy
friend FMovieSceneChannelProxyData
Additional Inherited Members
Protected Member Functions inherited from FMovieSceneChannelEditorDataEntry
template<typename ChannelType>
void AddMetaData (const FMovieSceneChannelMetaData &MetaData)
Add new editor data for the specified channel type at the last index in the array.
template<typename ChannelType, typename ExtendedEditorDataType>
void AddMetaData (const FMovieSceneChannelMetaData &MetaData, ExtendedEditorDataType &&InExtendedEditorData)
Add new editor data for the specified channel type at the last index in the arrays.
template<typename ChannelType>
TArrayView< const typename TMovieSceneChannelTraits< ChannelType >::ExtendedEditorDataType > GetAllExtendedEditorData () const
Access the extended editor data for channels stored in this entry.
template<typename ChannelType, typename ExtendedEditorDataType>
void SetExtendedEditorData (int32 EntryIndex, ExtendedEditorDataType &&InExtendedEditorData)
Set the extended channel-type specific editor data on an already added channel entry.
Detailed Description
An entry within FMovieSceneChannelProxy that contains all channels (and editor data) for any given channel type.
Definition at line 28 of file MovieSceneChannelProxy.h.
Constructor & Destructor Documentation
FMovieSceneChannelEntry()
template<typename ChannelType> FMovieSceneChannelEntry::FMovieSceneChannelEntry (FName InChannelTypeName, const ChannelType & Channel) inline explicit private
Templated constructor from the channel and its ID.
Definition at line 68 of file MovieSceneChannelProxy.h.
References FMovieSceneChannelEditorDataEntry::FMovieSceneChannelEditorDataEntry(), and ChannelTypeName.
Member Function Documentation
GetAllExtendedEditorData()
template<typename ChannelType> TArrayView< const typename TMovieSceneChannelTraits< ChannelType >::ExtendedEditorDataType > FMovieSceneChannelEntry::GetAllExtendedEditorData () const inline
Access extended typed editor data for channels stored in this entry.
Definition at line 52 of file MovieSceneChannelProxy.h.
References ChannelTypeName, check, and FMovieSceneChannelEditorDataEntry::GetAllExtendedEditorData().
Referenced by FMovieSceneChannelProxy::GetAllExtendedEditorData().
GetChannels()
TArrayView< FMovieSceneChannel *const > FMovieSceneChannelEntry::GetChannels () const inline
Access all the channels contained within this entry.
Definition at line 41 of file MovieSceneChannelProxy.h.
References Channels.
GetChannelTypeName()
FName FMovieSceneChannelEntry::GetChannelTypeName () const inline
Get the type name of the channels stored in this entry.
Definition at line 33 of file MovieSceneChannelProxy.h.
References ChannelTypeName.
Referenced by FMovieSceneChannelProxyData::AddInternal().
Field Documentation
Channels
TArray<FMovieSceneChannel*> FMovieSceneChannelEntry::Channels private
Pointers to the channels that this entry contains.
Pointers are assumed to stay alive as long as this entry is. If channels are reallocated, a new channel proxy should be created
Definition at line 77 of file MovieSceneChannelProxy.h.
Referenced by GetChannels(), and FMovieSceneChannelProxy::GetChannels().
ChannelTypeName
FName FMovieSceneChannelEntry::ChannelTypeName private
The name of the channel's struct type.
Definition at line 74 of file MovieSceneChannelProxy.h.
Referenced by FMovieSceneChannelEntry(), GetAllExtendedEditorData(), GetChannelTypeName(), and FMovieSceneChannelProxyData::SetExtendedEditorData().
FMovieSceneChannelProxy
friend FMovieSceneChannelEntry::FMovieSceneChannelProxy private
Definition at line 64 of file MovieSceneChannelProxy.h.
FMovieSceneChannelProxyData
friend FMovieSceneChannelEntry::FMovieSceneChannelProxyData private
Definition at line 63 of file MovieSceneChannelProxy.h.
The documentation for this struct was generated from the following file:
Runtime/MovieScene/Public/Channels/MovieSceneChannelProxy.h