Unreal Engine 5.6 C++ API: IAnimationEditorsAssetFamilyInterface Struct Reference
IAnimationEditorsAssetFamilyInterface Struct Reference abstract
#include "AnimationEditorsAssetFamilyExtension.h"
Public Member Functions
template<typename T>
TObjectPtr< const T > GetAssetOfType () const
virtual TWeakObjectPtr< const UObject > GetAssetOfType (const TObjectPtr< UClass > InClass) const =0
template<typename T>
bool IsAssetTypeInFamily () const
virtual bool IsAssetTypeInFamily (const TObjectPtr< UClass > InClass) const =0
template<typename T>
bool IsAssetTypeInFamilyAndUnassigned () const
bool IsAssetTypeInFamilyAndUnassigned (const TObjectPtr< UClass > InClass) const
virtual bool SetAssetOfType (const TObjectPtr< UClass > InClass, TWeakObjectPtr< const UObject > InObject)=0
template<typename T>
bool SetAssetOfType (TWeakObjectPtr< const UObject > InObject)
Detailed Description
Definition at line 13 of file AnimationEditorsAssetFamilyExtension.h.
Member Function Documentation
GetAssetOfType() [1/2]
template<typename T> TObjectPtr< const T > IAnimationEditorsAssetFamilyInterface::GetAssetOfType () const inline
Definition at line 26 of file AnimationEditorsAssetFamilyExtension.h.
References CastChecked(), GetAssetOfType(), and TWeakObjectPtr< T, TWeakObjectPtrBase >::Pin().
Referenced by GetAssetOfType(), and IsAssetTypeInFamilyAndUnassigned().
GetAssetOfType() [2/2]
virtual TWeakObjectPtr< const UObject > IAnimationEditorsAssetFamilyInterface::GetAssetOfType (const TObjectPtr< UClass > InClass) const pure virtual
IsAssetTypeInFamily() [1/2]
template<typename T> bool IAnimationEditorsAssetFamilyInterface::IsAssetTypeInFamily () const inline
Definition at line 18 of file AnimationEditorsAssetFamilyExtension.h.
References IsAssetTypeInFamily().
Referenced by IsAssetTypeInFamily(), and IsAssetTypeInFamilyAndUnassigned().
IsAssetTypeInFamily() [2/2]
virtual bool IAnimationEditorsAssetFamilyInterface::IsAssetTypeInFamily (const TObjectPtr< UClass > InClass) const pure virtual
IsAssetTypeInFamilyAndUnassigned() [1/2]
template<typename T> bool IAnimationEditorsAssetFamilyInterface::IsAssetTypeInFamilyAndUnassigned () const inline
Definition at line 46 of file AnimationEditorsAssetFamilyExtension.h.
References IsAssetTypeInFamilyAndUnassigned().
Referenced by IsAssetTypeInFamilyAndUnassigned().
IsAssetTypeInFamilyAndUnassigned() [2/2]
bool IAnimationEditorsAssetFamilyInterface::IsAssetTypeInFamilyAndUnassigned (const TObjectPtr< UClass > InClass) const inline
Definition at line 36 of file AnimationEditorsAssetFamilyExtension.h.
References GetAssetOfType(), and IsAssetTypeInFamily().
SetAssetOfType() [1/2]
virtual bool IAnimationEditorsAssetFamilyInterface::SetAssetOfType (const TObjectPtr< UClass > InClass, TWeakObjectPtr< const UObject > InObject) pure virtual
Referenced by SetAssetOfType().
SetAssetOfType() [2/2]
template<typename T> bool IAnimationEditorsAssetFamilyInterface::SetAssetOfType (TWeakObjectPtr< const UObject > InObject) inline
Definition at line 54 of file AnimationEditorsAssetFamilyExtension.h.
References SetAssetOfType().
The documentation for this struct was generated from the following file:
Editor/Persona/Public/AnimationEditorsAssetFamilyExtension.h