Unreal Engine 5.6 C++ API: FFileHelper Struct Reference
FFileHelper Struct Reference
#include "FileHelper.h"
Public Types
enum class EColorChannel {
R , G , B , A ,
All
}
enum class EEncodingOptions {
AutoDetect , ForceAnsi , ForceUnicode , ForceUTF8 ,
ForceUTF8WithoutBOM
}
enum class EHashOptions { None =0 , EnableVerify =1<<0 , ErrorMissingHash =1<<1 }
Public Member Functions
UE_DEPRECATED (4.26, "LoadFileToStringArray no longer supports VerifyFlags. You can use UE::String::ParseLines to split up a string loaded with LoadFileToString") static 1 bool LoadFileToStringArray(TArray< FString > &Result
UE_DEPRECATED (4.26, "LoadFileToStringArrayWithPredicate no longer supports VerifyFlags. You can use UE::String::ParseLines to split up a string loaded with LoadFileToString") static 1 bool LoadFileToStringArrayWithPredicate(TArray< FString > &Result
enum UE_DEPRECATED (5.0, "EChannelMask has been deprecated in favor of EColorChannel") EChannelMask
PRAGMA_DISABLE_DEPRECATION_WARNINGS UE_DEPRECATED (5.0, "EChannelMask has been deprecated in favor of EColorChannel, please use the other CreateBitmap() method.") static 1 bool CreateBitmap(const TCHAR *Pattern
Static Public Member Functions
static void BufferToString (FString &Result, const uint8 *Buffer, int32 Size)
Load a text file to an FString.
static bool CreateBitmap (const TCHAR *Pattern, int32 DataWidth, int32 DataHeight, const struct FColor *Data, FIntRect *SubRectangle=NULL, IFileManager *FileManager=&IFileManager::Get(), FString *OutFilename=NULL, bool bInWriteAlpha=false, EColorChannel ColorChannel=EColorChannel::All)
Saves a 24/32Bit BMP file to disk for debug image dump purposes.
static void GenerateDateTimeBasedBitmapFilename (const FString &Pattern, const FString &Extension, FString &OutFilename)
Generates the next unique bitmap filename with a specified extension.
static bool GenerateNextBitmapFilename (const FString &Pattern, const FString &Extension, FString &OutFilename, IFileManager *FileManager=&IFileManager::Get())
Generates the next unique bitmap filename with a specified extension.
static bool IsFilenameValidForSaving (const FString &Filename, FText &OutError)
Checks to see if a filename is valid for saving.
static bool LoadANSITextFileToStrings (const TCHAR *InFilename, IFileManager *InFileManager, TArray< FString > &OutStrings)
Load the given ANSI text file to an array of strings - one FString per line of the file.
static bool LoadFileInBlocks (FStringView Filename, TFunctionRef< void(FMemoryView)> BlockVisitor, int64 Offset=0, int64 Size=-1, uint32 Flags=0, int64 BlockSize=0)
Load a binary file a block at a time into a buffer and call the visitor each time the buffer is populated with a new block.
static bool LoadFileToArray (TArray64< uint8 > &Result, const TCHAR *Filename, uint32 Flags=0)
Load a binary file to a dynamic array with two uninitialized bytes at end as padding.
static bool LoadFileToArray (TArray< uint8 > &Result, const TCHAR *Filename, uint32 Flags=0)
Load a binary file to a dynamic array with two uninitialized bytes at end as padding.
static bool LoadFileToString (FString &Result, const TCHAR *Filename, EHashOptions VerifyFlags=EHashOptions::None, uint32 ReadFlags=0)
Load a text file to an FString.
static bool LoadFileToString (FString &Result, FArchive &Reader, EHashOptions VerifyFlags=EHashOptions::None)
Loads a text file from an FArchive to an FString.
static bool LoadFileToString (FString &Result, IPlatformFile *PlatformFile, const TCHAR *Filename, EHashOptions VerifyFlags=EHashOptions::None, uint32 ReadFlags=0)
Load a text file to an FString.
static bool LoadFileToStringArray (TArray< FString > &Result, const TCHAR *Filename)
Load a text file to an array of strings.
static bool LoadFileToStringArrayWithPredicate (TArray< FString > &Result, const TCHAR *Filename, TFunctionRef< bool(const FString &)> Predicate)
Load a text file to an array of strings, filtered by a user-defined predicate.
static bool LoadFileToStringWithLineVisitor (const TCHAR *Filename, TFunctionRef< void(FStringView Line)> Visitor)
Load a text file and invoke a visitor for each line.
static bool SaveArrayToFile (const TArray64< uint8 > &Array, const TCHAR *Filename, IFileManager *FileManager=&IFileManager::Get(), uint32 WriteFlags=0)
Save a binary array to a file.
static bool SaveArrayToFile (TArrayView64< const uint8 > Array, const TCHAR *Filename, IFileManager *FileManager=&IFileManager::Get(), uint32 WriteFlags=0)
Save a binary array to a file.
static bool SaveStringArrayToFile (const TArray< FString > &Lines, const TCHAR *Filename, EEncodingOptions EncodingOptions=EEncodingOptions::AutoDetect, IFileManager *FileManager=&IFileManager::Get(), uint32 WriteFlags=0)
Write the FString to a file.
static bool SaveStringToFile (FStringView String, const TCHAR *Filename, EEncodingOptions EncodingOptions=EEncodingOptions::AutoDetect, IFileManager *FileManager=&IFileManager::Get(), uint32 WriteFlags=0)
Write the FString to a file.
Data Fields
PRAGMA_DISABLE_DEPRECATION_WARNINGS int32 int32 const struct FColor FIntRect IFileManager FString bool bInWriteAlpha
PRAGMA_DISABLE_DEPRECATION_WARNINGS int32 int32 const struct FColor FIntRect IFileManager FString bool EChannelMask ChannelMask
PRAGMA_DISABLE_DEPRECATION_WARNINGS int32 int32 const struct FColor * Data
PRAGMA_DISABLE_DEPRECATION_WARNINGS int32 int32 DataHeight
PRAGMA_DISABLE_DEPRECATION_WARNINGS int32 DataWidth
PRAGMA_DISABLE_DEPRECATION_WARNINGS int32 int32 const struct FColor FIntRect IFileManager * FileManager
const TCHAR * Filename
PRAGMA_DISABLE_DEPRECATION_WARNINGS int32 int32 const struct FColor FIntRect IFileManager FString * OutFilename
const TCHAR TFunctionRef< bool(const FString &)> Predicate
PRAGMA_DISABLE_DEPRECATION_WARNINGS int32 int32 const struct FColor FIntRect * SubRectangle
const TCHAR EHashOptions VerifyFlags
const TCHAR TFunctionRef< bool(const FString &)> EHashOptions VerifyFlags
Detailed Description
Definition at line 28 of file FileHelper.h.
Member Enumeration Documentation
EColorChannel
enum class FFileHelper::EColorChannel strong
Enumerator
R
G
B
A
All
Definition at line 48 of file FileHelper.h.
EEncodingOptions
enum class FFileHelper::EEncodingOptions strong
Enumerator
AutoDetect
ForceAnsi
ForceUnicode
ForceUTF8
ForceUTF8WithoutBOM
Definition at line 39 of file FileHelper.h.
EHashOptions
enum class FFileHelper::EHashOptions strong
Enumerator
None
EnableVerify
Enable the async task for verifying the hash for the file being loaded.
ErrorMissingHash
A missing hash entry should trigger an error.
Definition at line 30 of file FileHelper.h.
Member Function Documentation
BufferToString()
void FFileHelper::BufferToString (FString & Result, const uint8 * Buffer, int32 Size) static
Load a text file to an FString.
Supports all combination of ANSI/Unicode files and platforms.
References Buffer, and TSequenceHistory< HistorySize >::Size.
CreateBitmap()
bool FFileHelper::CreateBitmap (const TCHAR * Pattern, int32 DataWidth, int32 DataHeight, const struct FColor * Data, FIntRect * SubRectangle = NULL, IFileManager * FileManager = &IFileManager::Get(), FString * OutFilename = NULL, bool bInWriteAlpha = false, EColorChannel ColorChannel = EColorChannel::All) static
Saves a 24/32Bit BMP file to disk for debug image dump purposes.
for general image saving (to BMP or any other format); use FImageUtils::SaveImage instead CreateBitmap is mainly for debug dump images
note this also calls SendDataToPCViaUnrealConsole and uses GenerateNextBitmapFilename if Pattern does not have ".bmp" on it
Parameters
Pattern filename with path, must not be 0, if with "bmp" extension (e.g. "out.bmp") the filename stays like this, if without (e.g. "out") automatic index numbers are addended (e.g. "out00002.bmp")
DataWidth - Width of the bitmap supplied in Data >0
DataHeight - Height of the bitmap supplied in Data >0
Data must not be 0
SubRectangle optional, specifies a sub-rectangle of the source image to save out. If NULL, the whole bitmap is saved
FileManager must not be 0
OutFilename optional, if specified filename will be output
bInWriteAlpha optional, specifies whether to write out the alpha channel. Will force BMP V4 format.
ColorChannel optional, specifies a specific channel to write out (will be written out to all channels gray scale).
Returns
true if success
References All, bInWriteAlpha, CreateBitmap(), Data, DataHeight, DataWidth, FileManager, OutFilename, and SubRectangle.
Referenced by CreateBitmap().
GenerateDateTimeBasedBitmapFilename()
void FFileHelper::GenerateDateTimeBasedBitmapFilename (const FString & Pattern, const FString & Extension, FString & OutFilename) static
Generates the next unique bitmap filename with a specified extension.
Parameters
Pattern Filename with path, but without extension.
Extension File extension to be appended
OutFilename Reference to an FString where the newly generated filename will be placed
Returns
true if success
References GenerateDateTimeBasedBitmapFilename(), and OutFilename.
Referenced by GenerateDateTimeBasedBitmapFilename().
GenerateNextBitmapFilename()
bool FFileHelper::GenerateNextBitmapFilename (const FString & Pattern, const FString & Extension, FString & OutFilename, IFileManager * FileManager = &IFileManager::Get()) static
Generates the next unique bitmap filename with a specified extension.
Parameters
Pattern Filename with path, but without extension.
Extension File extension to be appended
OutFilename Reference to an FString where the newly generated filename will be placed
FileManager Reference to a IFileManager (or the global instance by default)
Returns
true if success
References FileManager, GenerateNextBitmapFilename(), and OutFilename.
Referenced by GenerateNextBitmapFilename().
IsFilenameValidForSaving()
bool FFileHelper::IsFilenameValidForSaving (const FString & Filename, FText & OutError) static
Checks to see if a filename is valid for saving.
A filename must be under FPlatformMisc::GetMaxPathLength() to be saved
Parameters
Filename Filename, with or without path information, to check.
OutError If an error occurs, this is the reason why
References A, All, B, Filename, G, IsFilenameValidForSaving(), R, STRUCT_OFFSET, and UE_DEPRECATED().
Referenced by IsFilenameValidForSaving().
LoadANSITextFileToStrings()
bool FFileHelper::LoadANSITextFileToStrings (const TCHAR * InFilename, IFileManager * InFileManager, TArray< FString > & OutStrings) static
Load the given ANSI text file to an array of strings - one FString per line of the file.
Intended for use in simple text parsing actions
Parameters
InFilename The text file to read, full path
InFileManager The filemanager to use - NULL will use &IFileManager::Get()
OutStrings The array of FStrings to fill in
Returns
bool true if successful, false if not
References LoadANSITextFileToStrings().
Referenced by LoadANSITextFileToStrings().
LoadFileInBlocks()
bool FFileHelper::LoadFileInBlocks (FStringView Filename, TFunctionRef< void(FMemoryView)> BlockVisitor, int64 Offset = 0, int64 Size = -1, uint32 Flags = 0, int64 BlockSize = 0) static
Load a binary file a block at a time into a buffer and call the visitor each time the buffer is populated with a new block.
This uses less memory and has higher cache coherency than loading the entire file into a block of bytes, and is more performant than reading the file a byte at a time. Useful for e.g. hashing or parsing.
Parameters
Filename The file to read
BlockVisitor Function called repeatedly with each sequential block. Size of the input might change for performance and should not be assumed. Possibly the entire file will be passed in a single block. If LoadFileInBlocks returns true, the sum of sizes in each call to BlockVisitor equals the size of the requested range of the the file on disk. If the requested range has size 0, LoadFileInBlocks will return true and the BlockVisitor will not be called.
Offset Start of the range of bytes to read from the file. If less than zero or larger than filesize, it will be silently clamped to the [0,FileSize] range. This may result in LoadFileInBlocks returning true but using an empty range and not calling BlockVisitor.
Length of the range of bytes to read from the file. If less than zero, all bytes between Offset and end of file are read. If larger than the size of the range between Offset and end of file, it will be silently shortened to the size of the range.
Flags Flags to pass to IFileManager::CreateFileReader
BlockSize Size of the internally-allocated buffer to read bytes into and pass to each call to BlockVisitor. Sizes <= 0 use the default-selected block size for the current platform.
References Filename, Flags, and TSequenceHistory< HistorySize >::Size.
LoadFileToArray() [1/2]
bool FFileHelper::LoadFileToArray (TArray64< uint8 > & Result, const TCHAR * Filename, uint32 Flags = 0) static
Load a binary file to a dynamic array with two uninitialized bytes at end as padding.
Parameters
Result Receives the contents of the file
Filename The file to read
Flags Flags to pass to IFileManager::CreateFileReader
References Filename, and Flags.
LoadFileToArray() [2/2]
bool FFileHelper::LoadFileToArray (TArray< uint8 > & Result, const TCHAR * Filename, uint32 Flags = 0) static
Load a binary file to a dynamic array with two uninitialized bytes at end as padding.
Parameters
Result Receives the contents of the file
Filename The file to read
Flags Flags to pass to IFileManager::CreateFileReader
References Filename, and Flags.
Referenced by FGenericSaveGameSystem::LoadGame().
LoadFileToString() [1/3]
bool FFileHelper::LoadFileToString (FString & Result, const TCHAR * Filename, EHashOptions VerifyFlags = EHashOptions::None, uint32 ReadFlags = 0) static
Load a text file to an FString.
Supports all combination of ANSI/Unicode files and platforms.
Parameters
Result String representation of the loaded file
Filename Name of the file to load
VerifyFlags Flags controlling the hash verification behavior (see EHashOptions)
References Filename, None, and VerifyFlags.
LoadFileToString() [2/3]
bool FFileHelper::LoadFileToString (FString & Result, FArchive & Reader, EHashOptions VerifyFlags = EHashOptions::None) static
Loads a text file from an FArchive to an FString.
Supports all combination of ANSI/Unicode files and platforms.
Parameters
Result String representation of the loaded file
Reader The archive to load from
VerifyFlags Flags controlling the hash verification behavior (see EHashOptions)
References None, and VerifyFlags.
LoadFileToString() [3/3]
bool FFileHelper::LoadFileToString (FString & Result, IPlatformFile * PlatformFile, const TCHAR * Filename, EHashOptions VerifyFlags = EHashOptions::None, uint32 ReadFlags = 0) static
Load a text file to an FString.
Supports all combination of ANSI/Unicode files and platforms.
Parameters
Result String representation of the loaded file
PlatformFile PlatformFile interface to use
Filename Name of the file to load
VerifyFlags Flags controlling the hash verification behavior (see EHashOptions)
References Filename, None, and VerifyFlags.
LoadFileToStringArray()
bool FFileHelper::LoadFileToStringArray (TArray< FString > & Result, const TCHAR * Filename) static
Load a text file to an array of strings.
Supports all combination of ANSI/Unicode files and platforms.
Parameters
Result String representation of the loaded file
Filename Name of the file to load
References Filename.
Referenced by TAllocPlaybackLog< FModifier, FAllocOp >::Load().
LoadFileToStringArrayWithPredicate()
bool FFileHelper::LoadFileToStringArrayWithPredicate (TArray< FString > & Result, const TCHAR * Filename, TFunctionRef< bool(const FString &)> Predicate) static
Load a text file to an array of strings, filtered by a user-defined predicate.
Supports all combination of ANSI/Unicode files and platforms.
Parameters
Result String representation of the loaded file
Filename Name of the file to load
Predicate Condition for whether or not to add the line to the array
References Filename, LoadFileToStringArrayWithPredicate(), and Predicate.
Referenced by LoadFileToStringArrayWithPredicate().
LoadFileToStringWithLineVisitor()
bool FFileHelper::LoadFileToStringWithLineVisitor (const TCHAR * Filename, TFunctionRef< void(FStringView Line)> Visitor) static
Load a text file and invoke a visitor for each line.
Supports all combination of ANSI/Unicode files and platforms.
Parameters
Filename Name of the file to load
Visitor Visitor to invoke for each non-empty line in the file
References Filename, Line, and LoadFileToStringWithLineVisitor().
Referenced by LoadFileToStringWithLineVisitor().
SaveArrayToFile() [1/2]
bool FFileHelper::SaveArrayToFile (const TArray64< uint8 > & Array, const TCHAR * Filename, IFileManager * FileManager = &IFileManager::Get(), uint32 WriteFlags = 0) static
Save a binary array to a file.
References Array, FileManager, Filename, and SaveArrayToFile().
SaveArrayToFile() [2/2]
bool FFileHelper::SaveArrayToFile (TArrayView64< const uint8 > Array, const TCHAR * Filename, IFileManager * FileManager = &IFileManager::Get(), uint32 WriteFlags = 0) static
Save a binary array to a file.
References Array, FileManager, Filename, and SaveArrayToFile().
Referenced by SaveArrayToFile(), SaveArrayToFile(), and FGenericSaveGameSystem::SaveGame().
SaveStringArrayToFile()
bool FFileHelper::SaveStringArrayToFile (const TArray< FString > & Lines, const TCHAR * Filename, EEncodingOptions EncodingOptions = EEncodingOptions::AutoDetect, IFileManager * FileManager = &IFileManager::Get(), uint32 WriteFlags = 0) static
Write the FString to a file.
Supports all combination of ANSI/Unicode files and platforms.
References AutoDetect, FileManager, Filename, and SaveStringArrayToFile().
Referenced by SaveStringArrayToFile().
SaveStringToFile()
bool FFileHelper::SaveStringToFile (FStringView String, const TCHAR * Filename, EEncodingOptions EncodingOptions = EEncodingOptions::AutoDetect, IFileManager * FileManager = &IFileManager::Get(), uint32 WriteFlags = 0) static
Write the FString to a file.
Supports all combination of ANSI/Unicode files and platforms.
References AutoDetect, FileManager, Filename, SaveStringToFile(), and String.
Referenced by SaveStringToFile().
UE_DEPRECATED() [1/4]
FFileHelper::UE_DEPRECATED (4. 26, "LoadFileToStringArray no longer supports VerifyFlags. You can use UE::String::ParseLines to split up a string loaded with LoadFileToString") &
Referenced by IsFilenameValidForSaving(), and UE_DEPRECATED().
UE_DEPRECATED() [2/4]
FFileHelper::UE_DEPRECATED (4. 26, "LoadFileToStringArrayWithPredicate no longer supports VerifyFlags. You can use UE::String::ParseLines to split up a string loaded with LoadFileToString") &
References UE_DEPRECATED().
UE_DEPRECATED() [3/4]
enum FFileHelper::UE_DEPRECATED (5. 0, "EChannelMask has been deprecated in favor of EColorChannel") inline strong
Definition at line 251 of file FileHelper.h.
UE_DEPRECATED() [4/4]
PRAGMA_DISABLE_DEPRECATION_WARNINGS FFileHelper::UE_DEPRECATED (5. 0, "EChannelMask has been deprecated in favor of EColorChannel, please use the other CreateBitmap() method.") const
Field Documentation
bInWriteAlpha
PRAGMA_DISABLE_DEPRECATION_WARNINGS int32 int32 const struct FColor FIntRect IFileManager FString bool FFileHelper::bInWriteAlpha
Definition at line 264 of file FileHelper.h.
Referenced by CreateBitmap().
ChannelMask
PRAGMA_DISABLE_DEPRECATION_WARNINGS int32 int32 const struct FColor FIntRect IFileManager FString bool EChannelMask FFileHelper::ChannelMask
Definition at line 264 of file FileHelper.h.
Data
PRAGMA_DISABLE_DEPRECATION_WARNINGS int32 int32 const struct FColor* FFileHelper::Data
Definition at line 264 of file FileHelper.h.
Referenced by CreateBitmap().
DataHeight
PRAGMA_DISABLE_DEPRECATION_WARNINGS int32 int32 FFileHelper::DataHeight
Definition at line 264 of file FileHelper.h.
Referenced by CreateBitmap().
DataWidth
PRAGMA_DISABLE_DEPRECATION_WARNINGS int32 FFileHelper::DataWidth
Definition at line 264 of file FileHelper.h.
Referenced by CreateBitmap().
FileManager
PRAGMA_DISABLE_DEPRECATION_WARNINGS int32 int32 const struct FColor FIntRect IFileManager* FFileHelper::FileManager
Definition at line 264 of file FileHelper.h.
Referenced by CreateBitmap(), GenerateNextBitmapFilename(), SaveArrayToFile(), SaveArrayToFile(), SaveStringArrayToFile(), and SaveStringToFile().
Filename
const TCHAR * FFileHelper::Filename
Definition at line 142 of file FileHelper.h.
Referenced by IsFilenameValidForSaving(), LoadFileInBlocks(), LoadFileToArray(), LoadFileToArray(), LoadFileToString(), LoadFileToString(), LoadFileToStringArray(), LoadFileToStringArrayWithPredicate(), LoadFileToStringWithLineVisitor(), SaveArrayToFile(), SaveArrayToFile(), SaveStringArrayToFile(), and SaveStringToFile().
OutFilename
PRAGMA_DISABLE_DEPRECATION_WARNINGS int32 int32 const struct FColor FIntRect IFileManager FString* FFileHelper::OutFilename
Definition at line 264 of file FileHelper.h.
Referenced by CreateBitmap(), GenerateDateTimeBasedBitmapFilename(), and GenerateNextBitmapFilename().
Predicate
const TCHAR TFunctionRef<bool(const FString&)> FFileHelper::Predicate
Definition at line 154 of file FileHelper.h.
Referenced by LoadFileToStringArrayWithPredicate().
SubRectangle
PRAGMA_DISABLE_DEPRECATION_WARNINGS int32 int32 const struct FColor FIntRect* FFileHelper::SubRectangle
Definition at line 264 of file FileHelper.h.
Referenced by CreateBitmap().
VerifyFlags [1/2]
const TCHAR EHashOptions FFileHelper::VerifyFlags
Definition at line 142 of file FileHelper.h.
Referenced by LoadFileToString(), LoadFileToString(), and LoadFileToString().
VerifyFlags [2/2]
const TCHAR TFunctionRef<bool(const FString&)> EHashOptions FFileHelper::VerifyFlags
Definition at line 154 of file FileHelper.h.
The documentation for this struct was generated from the following file:
Runtime/Core/Public/Misc/FileHelper.h