Unreal Engine 5.6 C++ API: FToolBuilderState Struct Reference
FToolBuilderState Struct Reference
FToolBuilderState is a bucket of state information that a ToolBuilder might need to construct a Tool.
#include "ToolContextInterfaces.h"
Public Member Functions
PRAGMA_DISABLE_DEPRECATION_WARNINGS FToolBuilderState ()=default
FToolBuilderState (const FToolBuilderState &)=default
FToolBuilderState (FToolBuilderState &&)=default
FToolBuilderState & operator= (const FToolBuilderState &)=default
FToolBuilderState & operator= (FToolBuilderState &&)=default
UE_DEPRECATED (5.1, "This has moved to a context object. See IAssetEditorContextInterface") TWeakObjectPtr< UTypedElementSelectionSet > TypedElementSelectionSet
Data Fields
UInteractiveGizmoManager * GizmoManager = nullptr
The current GizmoManager.
TArray< AActor * > SelectedActors
Current selected Actors.
TArray< UActorComponent * > SelectedComponents
Current selected Components.
UToolTargetManager * TargetManager = nullptr
The current TargetManager.
UInteractiveToolManager * ToolManager = nullptr
The current ToolManager.
UWorld * World = nullptr
The current UWorld.
Detailed Description
FToolBuilderState is a bucket of state information that a ToolBuilder might need to construct a Tool.
This information comes from a level above the Tools framework, and depends on the context we are in (Editor vs Runtime, for example).
Definition at line 48 of file ToolContextInterfaces.h.
Constructor & Destructor Documentation
FToolBuilderState() [1/3]
PRAGMA_DISABLE_DEPRECATION_WARNINGS FToolBuilderState::FToolBuilderState () default
References FToolBuilderState().
Referenced by FToolBuilderState(), FToolBuilderState(), FToolBuilderState(), operator=(), and operator=().
FToolBuilderState() [2/3]
FToolBuilderState::FToolBuilderState (FToolBuilderState &&) default
References FToolBuilderState().
FToolBuilderState() [3/3]
FToolBuilderState::FToolBuilderState (const FToolBuilderState &) default
References FToolBuilderState().
Member Function Documentation
operator=() [1/2]
FToolBuilderState & FToolBuilderState::operator= (const FToolBuilderState &) default
References FToolBuilderState(), and PRAGMA_ENABLE_DEPRECATION_WARNINGS.
operator=() [2/2]
FToolBuilderState & FToolBuilderState::operator= (FToolBuilderState &&) default
References FToolBuilderState().
UE_DEPRECATED()
FToolBuilderState::UE_DEPRECATED (5. 1, "This has moved to a context object. See IAssetEditorContextInterface")
References PRAGMA_DISABLE_DEPRECATION_WARNINGS.
Field Documentation
GizmoManager
UInteractiveGizmoManager* FToolBuilderState::GizmoManager = nullptr
The current GizmoManager.
Definition at line 57 of file ToolContextInterfaces.h.
SelectedActors
TArray<AActor*> FToolBuilderState::SelectedActors
Current selected Actors.
May be empty or nullptr.
Definition at line 60 of file ToolContextInterfaces.h.
SelectedComponents
TArray<UActorComponent*> FToolBuilderState::SelectedComponents
Current selected Components.
May be empty or nullptr.
Definition at line 62 of file ToolContextInterfaces.h.
TargetManager
UToolTargetManager* FToolBuilderState::TargetManager = nullptr
The current TargetManager.
Definition at line 55 of file ToolContextInterfaces.h.
ToolManager
UInteractiveToolManager* FToolBuilderState::ToolManager = nullptr
The current ToolManager.
Definition at line 53 of file ToolContextInterfaces.h.
World
UWorld* FToolBuilderState::World = nullptr
The current UWorld.
Definition at line 51 of file ToolContextInterfaces.h.
The documentation for this struct was generated from the following file:
Runtime/InteractiveToolsFramework/Public/ToolContextInterfaces.h