Unreal Engine 5.6 C++ API: FNavigationDirtyArea Struct Reference
FNavigationDirtyArea Struct Reference
#include "NavigationDirtyArea.h"
Public Member Functions
FNavigationDirtyArea ()=default
FNavigationDirtyArea (const FBox &InBounds, ENavigationDirtyFlag InFlags, const TSharedPtr< const FNavigationElement > &InOptionalSourceElement=nullptr)
FNavigationDirtyArea (const FNavigationDirtyArea &Other)
FNavigationDirtyArea (FNavigationDirtyArea &&Other)
FString GetSourceDescription () const
bool HasFlag (const ENavigationDirtyFlag Flag) const
bool operator!= (const FNavigationDirtyArea &Other) const
FNavigationDirtyArea & operator= (const FNavigationDirtyArea &Other)
FNavigationDirtyArea & operator= (FNavigationDirtyArea &&Other)
bool operator== (const FNavigationDirtyArea &Other) const
UE_DEPRECATED (5.5, "Use the constructor taking ENavigationDirtyFlag and FNavigationElement instead.") 1 FNavigationDirtyArea(const FBox &InBounds
Data Fields
FBox Bounds = FBox(ForceInit)
ENavigationDirtyFlag Flags = ENavigationDirtyFlag::None
int32 InFlags
int32 UObject *const InOptionalSourceObject = nullptr)
TSharedPtr< const FNavigationElement > OptionalSourceElement
Detailed Description
Definition at line 24 of file NavigationDirtyArea.h.
Constructor & Destructor Documentation
FNavigationDirtyArea() [1/4]
FNavigationDirtyArea::FNavigationDirtyArea () default
Referenced by FNavigationDirtyArea(), FNavigationDirtyArea(), operator!=(), operator=(), operator=(), and operator==().
FNavigationDirtyArea() [2/4]
FNavigationDirtyArea::FNavigationDirtyArea (const FBox & InBounds, ENavigationDirtyFlag InFlags, const TSharedPtr< const FNavigationElement > & InOptionalSourceElement = nullptr)
References InFlags.
FNavigationDirtyArea() [3/4]
FNavigationDirtyArea::FNavigationDirtyArea (const FNavigationDirtyArea & Other)
References FNavigationDirtyArea(), and Other.
FNavigationDirtyArea() [4/4]
FNavigationDirtyArea::FNavigationDirtyArea (FNavigationDirtyArea && Other)
References FNavigationDirtyArea(), and Other.
Member Function Documentation
GetSourceDescription()
FString FNavigationDirtyArea::GetSourceDescription () const
HasFlag()
bool FNavigationDirtyArea::HasFlag (const ENavigationDirtyFlag Flag) const inline
Definition at line 46 of file NavigationDirtyArea.h.
References Flags, HasFlag(), and None.
Referenced by HasFlag().
operator!=()
bool FNavigationDirtyArea::operator!= (const FNavigationDirtyArea & Other) const inline
Definition at line 56 of file NavigationDirtyArea.h.
References FNavigationDirtyArea(), and Other.
operator=() [1/2]
FNavigationDirtyArea & FNavigationDirtyArea::operator= (const FNavigationDirtyArea & Other)
References FNavigationDirtyArea(), and Other.
operator=() [2/2]
FNavigationDirtyArea & FNavigationDirtyArea::operator= (FNavigationDirtyArea && Other)
References FNavigationDirtyArea(), and Other.
operator==()
bool FNavigationDirtyArea::operator== (const FNavigationDirtyArea & Other) const inline
Definition at line 51 of file NavigationDirtyArea.h.
References FNavigationDirtyArea(), Bounds, Flags, OptionalSourceElement, and Other.
UE_DEPRECATED()
FNavigationDirtyArea::UE_DEPRECATED (5. 5, "Use the constructor taking ENavigationDirtyFlag and FNavigationElement instead.") const &
Field Documentation
Bounds
FBox FNavigationDirtyArea::Bounds = FBox(ForceInit)
Definition at line 26 of file NavigationDirtyArea.h.
Referenced by operator==().
Flags
ENavigationDirtyFlag FNavigationDirtyArea::Flags = ENavigationDirtyFlag::None
Definition at line 32 of file NavigationDirtyArea.h.
Referenced by HasFlag(), and operator==().
InFlags
int32 FNavigationDirtyArea::InFlags
Definition at line 38 of file NavigationDirtyArea.h.
Referenced by FNavigationDirtyArea().
InOptionalSourceObject
int32 UObject* const FNavigationDirtyArea::InOptionalSourceObject = nullptr)
Definition at line 38 of file NavigationDirtyArea.h.
OptionalSourceElement
TSharedPtr<const FNavigationElement> FNavigationDirtyArea::OptionalSourceElement
Definition at line 31 of file NavigationDirtyArea.h.
Referenced by operator==().
The documentation for this struct was generated from the following file:
Runtime/Engine/Classes/AI/Navigation/NavigationDirtyArea.h