Unreal Engine 5.6 C++ API: UE::MovieScene::TInitializeBoundMaterials< AccessorType, RequiredComponents > Struct Template Reference
UE::MovieScene::TInitializeBoundMaterials< AccessorType, RequiredComponents > Struct Template Reference
#include "MovieSceneMaterialSystem.h"
Static Public Member Functions
static void ForEachEntity (typename TCallTraits< RequiredComponents >::ParamType... Inputs, FObjectComponent &OutDynamicMaterial)
static bool InitializeBoundMaterial (typename TCallTraits< RequiredComponents >::ParamType... Inputs, FObjectComponent &OutDynamicMaterial)
Detailed Description
template<typename AccessorType, typename... RequiredComponents>
struct UE::MovieScene::TInitializeBoundMaterials< AccessorType, RequiredComponents >
Definition at line 221 of file MovieSceneMaterialSystem.h.
Member Function Documentation
ForEachEntity()
template<typename AccessorType, typename... RequiredComponents> void UE::MovieScene::TInitializeBoundMaterials< AccessorType, RequiredComponents >::ForEachEntity (typename TCallTraits< RequiredComponents >::ParamType... Inputs, FObjectComponent & OutDynamicMaterial) inline static
Definition at line 268 of file MovieSceneMaterialSystem.h.
References InitializeBoundMaterial().
InitializeBoundMaterial()
template<typename AccessorType, typename... RequiredComponents> bool UE::MovieScene::TInitializeBoundMaterials< AccessorType, RequiredComponents >::InitializeBoundMaterial (typename TCallTraits< RequiredComponents >::ParamType... Inputs, FObjectComponent & OutDynamicMaterial) inline static
Definition at line 223 of file MovieSceneMaterialSystem.h.
References Cast(), UE::MovieScene::FObjectComponent::GetObject(), UE::MovieScene::FObjectComponent::Null(), and UE::MovieScene::FObjectComponent::Weak().
Referenced by ForEachEntity(), and UE::MovieScene::TReinitializeBoundMaterials< AccessorType, RequiredComponents >::ForEachEntity().
The documentation for this struct was generated from the following file:
Runtime/MovieSceneTracks/Public/Systems/MovieSceneMaterialSystem.h