Unreal Engine 5.6 C++ API: FAssetRegistryExportPath Struct Reference
FAssetRegistryExportPath Struct Reference
Helper class for condensing strings of these types into 1 - 3 FNames [class]'[package].
#include "AssetDataTagMap.h"
Public Member Functions
PRAGMA_DISABLE_DEPRECATION_WARNINGS FAssetRegistryExportPath ()=default
FAssetRegistryExportPath (const FAssetRegistryExportPath &)=default
FAssetRegistryExportPath (FAnsiStringView String)
FAssetRegistryExportPath (FAssetRegistryExportPath &&)=default
PRAGMA_ENABLE_DEPRECATION_WARNINGS FAssetRegistryExportPath (FWideStringView String)
bool IsEmpty () const
operator bool () const
FAssetRegistryExportPath & operator= (const FAssetRegistryExportPath &)=default
FAssetRegistryExportPath & operator= (FAssetRegistryExportPath &&)=default
FName ToName () const
FString ToPath () const
void ToPath (FStringBuilderBase &Out) const
FString ToString () const
void ToString (FStringBuilderBase &Out) const
FTopLevelAssetPath ToTopLevelAssetPath () const
UE_DEPRECATED (5.1, "Class names are now represented by path names. Please use ClassPath member") FName Class
Data Fields
FTopLevelAssetPath ClassPath
FName Object
FName Package
Friends
uint32 GetTypeHash (const FAssetRegistryExportPath &Export)
bool operator== (const FAssetRegistryExportPath &A, const FAssetRegistryExportPath &B)
Detailed Description
Helper class for condensing strings of these types into 1 - 3 FNames [class]'[package].
[object]' [package].[object] [package]
Definition at line 26 of file AssetDataTagMap.h.
Constructor & Destructor Documentation
FAssetRegistryExportPath() [1/5]
PRAGMA_DISABLE_DEPRECATION_WARNINGS FAssetRegistryExportPath::FAssetRegistryExportPath () default
Referenced by FAssetRegistryExportPath(), FAssetRegistryExportPath(), GetTypeHash, operator=(), operator=(), and operator==.
FAssetRegistryExportPath() [2/5]
FAssetRegistryExportPath::FAssetRegistryExportPath (FAssetRegistryExportPath &&) default
References FAssetRegistryExportPath().
FAssetRegistryExportPath() [3/5]
FAssetRegistryExportPath::FAssetRegistryExportPath (const FAssetRegistryExportPath &) default
References FAssetRegistryExportPath().
FAssetRegistryExportPath() [4/5]
PRAGMA_ENABLE_DEPRECATION_WARNINGS FAssetRegistryExportPath::FAssetRegistryExportPath (FWideStringView String) explicit
References String.
FAssetRegistryExportPath() [5/5]
FAssetRegistryExportPath::FAssetRegistryExportPath (FAnsiStringView String) explicit
References String.
Member Function Documentation
IsEmpty()
bool FAssetRegistryExportPath::IsEmpty () const inline
Definition at line 54 of file AssetDataTagMap.h.
References ClassPath, Object, and Package.
Referenced by operator bool().
operator bool()
FAssetRegistryExportPath::operator bool () const inline explicit
Definition at line 55 of file AssetDataTagMap.h.
References IsEmpty().
operator=() [1/2]
FAssetRegistryExportPath & FAssetRegistryExportPath::operator= (const FAssetRegistryExportPath &) default
References FAssetRegistryExportPath(), and PRAGMA_ENABLE_DEPRECATION_WARNINGS.
operator=() [2/2]
FAssetRegistryExportPath & FAssetRegistryExportPath::operator= (FAssetRegistryExportPath &&) default
References FAssetRegistryExportPath().
ToName()
FName FAssetRegistryExportPath::ToName () const
References ToName().
Referenced by ToName().
ToPath() [1/2]
FString FAssetRegistryExportPath::ToPath () const
References ToPath().
Referenced by ToPath(), and ToPath().
ToPath() [2/2]
void FAssetRegistryExportPath::ToPath (FStringBuilderBase & Out) const
References ToPath().
ToString() [1/2]
FString FAssetRegistryExportPath::ToString () const
References ToString().
Referenced by ToString(), and ToString().
ToString() [2/2]
void FAssetRegistryExportPath::ToString (FStringBuilderBase & Out) const
References ToString().
ToTopLevelAssetPath()
FTopLevelAssetPath FAssetRegistryExportPath::ToTopLevelAssetPath () const inline
Definition at line 50 of file AssetDataTagMap.h.
References Object, Package, and ToTopLevelAssetPath().
Referenced by ToTopLevelAssetPath().
UE_DEPRECATED()
FAssetRegistryExportPath::UE_DEPRECATED (5. 1, "Class names are now represented by path names. Please use ClassPath member")
References Class.
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FAssetRegistryExportPath & Export) friend
References FAssetRegistryExportPath().
operator==
bool operator== (const FAssetRegistryExportPath & A, const FAssetRegistryExportPath & B) friend
References FAssetRegistryExportPath(), A, and B.
Field Documentation
ClassPath
FTopLevelAssetPath FAssetRegistryExportPath::ClassPath
Definition at line 39 of file AssetDataTagMap.h.
Referenced by IsEmpty().
Object
FName FAssetRegistryExportPath::Object
Definition at line 43 of file AssetDataTagMap.h.
Referenced by IsEmpty(), and ToTopLevelAssetPath().
Package
FName FAssetRegistryExportPath::Package
Definition at line 42 of file AssetDataTagMap.h.
Referenced by IsEmpty(), and ToTopLevelAssetPath().
The documentation for this struct was generated from the following file:
Runtime/CoreUObject/Public/AssetRegistry/AssetDataTagMap.h