Unreal Engine 5.6 C++ API: TListTypeTraits< UE::Sequencer::TWeakViewModelPtr< ExtensionType > > Struct Template Reference
TListTypeTraits< UE::Sequencer::TWeakViewModelPtr< ExtensionType > > Struct Template Reference
#include "TreeViewTraits.h"
Data Structures
class SerializerType
Public Types
using MapKeyFuncs = TDefaultMapHashableKeyFuncs<PtrType, TSharedRef<ITableRow>, false>
using MapKeyFuncsSparse = TDefaultMapHashableKeyFuncs<PtrType, FSparseItemInfo, false>
using NullableType = PtrType
using PtrType = UE::Sequencer::TWeakViewModelPtr<ExtensionType>
using SetKeyFuncs = DefaultKeyFuncs<PtrType>
Static Public Member Functions
template<typename U>
static void AddReferencedObjects (FReferenceCollector &, TArray< PtrType > &, TSet< PtrType > &, TMap< const U *, PtrType > &)
static FString DebugDump (PtrType InPtr)
static bool IsPtrValid (const PtrType &InPtr)
static PtrType MakeNullPtr ()
static PtrType NullableItemTypeConvertToItemType (const PtrType &InPtr)
static void ResetPtr (PtrType &InPtr)
Detailed Description
template<typename ExtensionType>
struct TListTypeTraits< UE::Sequencer::TWeakViewModelPtr< ExtensionType > >
Definition at line 10 of file TreeViewTraits.h.
Member Typedef Documentation
MapKeyFuncs
template<typename ExtensionType> using TListTypeTraits< UE::Sequencer::TWeakViewModelPtr< ExtensionType > >::MapKeyFuncs = TDefaultMapHashableKeyFuncs<PtrType, TSharedRef<ITableRow>, false>
Definition at line 16 of file TreeViewTraits.h.
MapKeyFuncsSparse
template<typename ExtensionType> using TListTypeTraits< UE::Sequencer::TWeakViewModelPtr< ExtensionType > >::MapKeyFuncsSparse = TDefaultMapHashableKeyFuncs<PtrType, FSparseItemInfo, false>
Definition at line 17 of file TreeViewTraits.h.
NullableType
template<typename ExtensionType> using TListTypeTraits< UE::Sequencer::TWeakViewModelPtr< ExtensionType > >::NullableType = PtrType
Definition at line 14 of file TreeViewTraits.h.
PtrType
template<typename ExtensionType> using TListTypeTraits< UE::Sequencer::TWeakViewModelPtr< ExtensionType > >::PtrType = UE::Sequencer::TWeakViewModelPtr<ExtensionType>
Definition at line 13 of file TreeViewTraits.h.
SetKeyFuncs
template<typename ExtensionType> using TListTypeTraits< UE::Sequencer::TWeakViewModelPtr< ExtensionType > >::SetKeyFuncs = DefaultKeyFuncs<PtrType>
Definition at line 18 of file TreeViewTraits.h.
Member Function Documentation
AddReferencedObjects()
template<typename ExtensionType> template<typename U> void TListTypeTraits< UE::Sequencer::TWeakViewModelPtr< ExtensionType > >::AddReferencedObjects (FReferenceCollector & , TArray< PtrType > & , TSet< PtrType > & , TMap< const U *, PtrType > &) inline static
Definition at line 21 of file TreeViewTraits.h.
DebugDump()
template<typename ExtensionType> FString TListTypeTraits< UE::Sequencer::TWeakViewModelPtr< ExtensionType > >::DebugDump (PtrType InPtr) inline static
Definition at line 47 of file TreeViewTraits.h.
References UE::Sequencer::TViewModelPtr< T >::AsModel(), TSharedPtr< ObjectType, InMode >::Get(), UE::Sequencer::TWeakViewModelPtr< T >::Pin(), TEXT, and UPTRINT_x_FMT.
IsPtrValid()
template<typename ExtensionType> bool TListTypeTraits< UE::Sequencer::TWeakViewModelPtr< ExtensionType > >::IsPtrValid (const PtrType & InPtr) inline static
Definition at line 27 of file TreeViewTraits.h.
References UE::Sequencer::TWeakViewModelPtr< T >::Pin().
MakeNullPtr()
template<typename ExtensionType> PtrType TListTypeTraits< UE::Sequencer::TWeakViewModelPtr< ExtensionType > >::MakeNullPtr () inline static
Definition at line 37 of file TreeViewTraits.h.
NullableItemTypeConvertToItemType()
template<typename ExtensionType> PtrType TListTypeTraits< UE::Sequencer::TWeakViewModelPtr< ExtensionType > >::NullableItemTypeConvertToItemType (const PtrType & InPtr) inline static
Definition at line 42 of file TreeViewTraits.h.
ResetPtr()
template<typename ExtensionType> void TListTypeTraits< UE::Sequencer::TWeakViewModelPtr< ExtensionType > >::ResetPtr (PtrType & InPtr) inline static
Definition at line 32 of file TreeViewTraits.h.
The documentation for this struct was generated from the following file:
Editor/SequencerCore/Public/MVVM/Views/TreeViewTraits.h