Unreal Engine 5.6 C++ API: TFrameValue< ValueType > Struct Template Reference
TFrameValue< ValueType > Struct Template Reference
This struct allows you to cache a value for a frame, and automatically invalidates when the frame advances.
#include "FrameValue.h"
Public Member Functions
TFrameValue ()
Construct an OptionalType with no value; i.e.
TFrameValue (const TFrameValue &InValue)
Copy/Move construction.
TFrameValue (const ValueType &InValue)
Construct an OptionalType with a valid value.
TFrameValue (TFrameValue &&InValue)
TFrameValue (ValueType &&InValue)
const ValueType & GetValue () const
bool IsSet () const
TFrameValue & operator= (const TFrameValue &InValue)
TFrameValue & operator= (const ValueType &InValue)
TFrameValue & operator= (TFrameValue &&InValue)
TFrameValue & operator= (ValueType &&InValue)
ValueType TryGetValue (ValueType UnsetValue) &&
ValueType TryGetValue (ValueType UnsetValue) const &
Private Attributes
uint64 FrameSet
TOptional< ValueType > Value
Detailed Description
template<typename ValueType>
struct TFrameValue< ValueType >
This struct allows you to cache a value for a frame, and automatically invalidates when the frame advances.
If the value was set this frame, IsSet() returns true and GetValue() is valid.
Definition at line 14 of file FrameValue.h.
Constructor & Destructor Documentation
TFrameValue() [1/5]
template<typename ValueType> TFrameValue< ValueType >::TFrameValue (const ValueType & InValue) inline
Construct an OptionalType with a valid value.
Definition at line 22 of file FrameValue.h.
References FrameSet, GFrameCounter, and Value.
Referenced by TFrameValue(), TFrameValue(), operator=(), operator=(), operator=(), and operator=().
TFrameValue() [2/5]
template<typename ValueType> TFrameValue< ValueType >::TFrameValue (ValueType && InValue) inline
Definition at line 28 of file FrameValue.h.
References FrameSet, GFrameCounter, MoveTemp(), and Value.
TFrameValue() [3/5]
template<typename ValueType> TFrameValue< ValueType >::TFrameValue () inline
Construct an OptionalType with no value; i.e.
unset
Definition at line 35 of file FrameValue.h.
References FrameSet, and GFrameCounter.
TFrameValue() [4/5]
template<typename ValueType> TFrameValue< ValueType >::TFrameValue (const TFrameValue< ValueType > & InValue) inline
Copy/Move construction.
Definition at line 41 of file FrameValue.h.
References TFrameValue(), FrameSet, GFrameCounter, and Value.
TFrameValue() [5/5]
template<typename ValueType> TFrameValue< ValueType >::TFrameValue (TFrameValue< ValueType > && InValue) inline
Definition at line 47 of file FrameValue.h.
References TFrameValue(), FrameSet, GFrameCounter, MoveTemp(), and Value.
Member Function Documentation
GetValue()
template<typename ValueType> const ValueType & TFrameValue< ValueType >::GetValue () const inline
Definition at line 88 of file FrameValue.h.
References checkf, FrameSet, GFrameCounter, TEXT, and Value.
IsSet()
template<typename ValueType> bool TFrameValue< ValueType >::IsSet () const inline
Definition at line 83 of file FrameValue.h.
References FrameSet, GFrameCounter, and Value.
Referenced by TryGetValue(), and TryGetValue().
operator=() [1/4]
template<typename ValueType> TFrameValue & TFrameValue< ValueType >::operator= (const TFrameValue< ValueType > & InValue) inline
Definition at line 53 of file FrameValue.h.
References TFrameValue(), FrameSet, GFrameCounter, and Value.
operator=() [2/4]
template<typename ValueType> TFrameValue & TFrameValue< ValueType >::operator= (const ValueType & InValue) inline
Definition at line 67 of file FrameValue.h.
References TFrameValue(), FrameSet, GFrameCounter, and Value.
operator=() [3/4]
template<typename ValueType> TFrameValue & TFrameValue< ValueType >::operator= (TFrameValue< ValueType > && InValue) inline
Definition at line 60 of file FrameValue.h.
References TFrameValue(), FrameSet, GFrameCounter, MoveTemp(), and Value.
operator=() [4/4]
template<typename ValueType> TFrameValue & TFrameValue< ValueType >::operator= (ValueType && InValue) inline
Definition at line 74 of file FrameValue.h.
References TFrameValue(), FrameSet, GFrameCounter, MoveTemp(), and Value.
TryGetValue() [1/2]
template<typename ValueType> ValueType TFrameValue< ValueType >::TryGetValue (ValueType UnsetValue) && inline
Definition at line 99 of file FrameValue.h.
References IsSet(), MoveTemp(), and Value.
TryGetValue() [2/2]
template<typename ValueType> ValueType TFrameValue< ValueType >::TryGetValue (ValueType UnsetValue) const & inline
Definition at line 94 of file FrameValue.h.
References IsSet(), MoveTemp(), and Value.
Field Documentation
FrameSet
template<typename ValueType> uint64 TFrameValue< ValueType >::FrameSet private
Definition at line 17 of file FrameValue.h.
Referenced by TFrameValue(), TFrameValue(), TFrameValue(), TFrameValue(), TFrameValue(), GetValue(), IsSet(), operator=(), operator=(), operator=(), and operator=().
Value
template<typename ValueType> TOptional<ValueType> TFrameValue< ValueType >::Value private
Definition at line 18 of file FrameValue.h.
Referenced by TFrameValue(), TFrameValue(), TFrameValue(), TFrameValue(), GetValue(), IsSet(), operator=(), operator=(), operator=(), operator=(), TryGetValue(), and TryGetValue().
The documentation for this struct was generated from the following file:
Runtime/Core/Public/Misc/FrameValue.h