Unreal Engine 5.6 C++ API: UE::Geometry::FMeshBevel::FBevelEdge Struct Reference
UE::Geometry::FMeshBevel::FBevelEdge Struct Reference
#include "MeshBevel.h"
Public Member Functions
PRAGMA_DISABLE_DEPRECATION_WARNINGS FBevelEdge ()=default
FBevelEdge (const FBevelEdge &)=default
FBevelEdge (FBevelEdge &&)=default
UE_DEPRECATED (5.5, "Mapping back to source topology is not used.") FIndex2i GroupIDs
UE_DEPRECATED (5.5, "Mapping back to source topology is not used.") int32 GroupEdgeID
Data Fields
bool bEndpointBoundaryFlag [2]
FIndex2i BevelVertices
PRAGMA_ENABLE_DEPRECATION_WARNINGS int32 EdgeIndex
TArray< FVector3d > InitialPositions
TArray< int32 > MeshEdges
TArray< FIndex2i > MeshEdgeTris
TArray< int32 > MeshVertices
int32 NewGroupID
TArray< int32 > NewMeshEdges
TArray< int32 > NewMeshVertices
TArray< FVector3d > NewPositions0
TArray< FVector3d > NewPositions1
TArray< FVector3d > NormalsA
TArray< FVector3d > NormalsB
FQuadGridPatch StripQuadPatch
TArray< FIndex2i > StripQuads
Detailed Description
Definition at line 183 of file MeshBevel.h.
Constructor & Destructor Documentation
FBevelEdge() [1/3]
PRAGMA_DISABLE_DEPRECATION_WARNINGS UE::Geometry::FMeshBevel::FBevelEdge::FBevelEdge () default
Referenced by FBevelEdge(), and FBevelEdge().
FBevelEdge() [2/3]
UE::Geometry::FMeshBevel::FBevelEdge::FBevelEdge (const FBevelEdge &) default
References FBevelEdge().
FBevelEdge() [3/3]
UE::Geometry::FMeshBevel::FBevelEdge::FBevelEdge (FBevelEdge &&) default
References FBevelEdge(), and PRAGMA_ENABLE_DEPRECATION_WARNINGS.
Member Function Documentation
UE_DEPRECATED() [1/2]
UE::Geometry::FMeshBevel::FBevelEdge::UE_DEPRECATED (5. 5, "Mapping back to source topology is not used.")
References UE_DEPRECATED().
UE_DEPRECATED() [2/2]
UE::Geometry::FMeshBevel::FBevelEdge::UE_DEPRECATED (5. 5, "Mapping back to source topology is not used.")
Referenced by UE_DEPRECATED().
Field Documentation
bEndpointBoundaryFlag
bool UE::Geometry::FMeshBevel::FBevelEdge::bEndpointBoundaryFlag[2]
Definition at line 200 of file MeshBevel.h.
BevelVertices
FIndex2i UE::Geometry::FMeshBevel::FBevelEdge::BevelVertices
Definition at line 202 of file MeshBevel.h.
EdgeIndex
PRAGMA_ENABLE_DEPRECATION_WARNINGS int32 UE::Geometry::FMeshBevel::FBevelEdge::EdgeIndex
Definition at line 192 of file MeshBevel.h.
InitialPositions
TArray<FVector3d> UE::Geometry::FMeshBevel::FBevelEdge::InitialPositions
Definition at line 201 of file MeshBevel.h.
MeshEdges
TArray<int32> UE::Geometry::FMeshBevel::FBevelEdge::MeshEdges
Definition at line 194 of file MeshBevel.h.
MeshEdgeTris
TArray<FIndex2i> UE::Geometry::FMeshBevel::FBevelEdge::MeshEdgeTris
Definition at line 195 of file MeshBevel.h.
MeshVertices
TArray<int32> UE::Geometry::FMeshBevel::FBevelEdge::MeshVertices
Definition at line 193 of file MeshBevel.h.
NewGroupID
int32 UE::Geometry::FMeshBevel::FBevelEdge::NewGroupID
Definition at line 213 of file MeshBevel.h.
NewMeshEdges
TArray<int32> UE::Geometry::FMeshBevel::FBevelEdge::NewMeshEdges
Definition at line 206 of file MeshBevel.h.
NewMeshVertices
TArray<int32> UE::Geometry::FMeshBevel::FBevelEdge::NewMeshVertices
Definition at line 205 of file MeshBevel.h.
NewPositions0
TArray<FVector3d> UE::Geometry::FMeshBevel::FBevelEdge::NewPositions0
Definition at line 209 of file MeshBevel.h.
NewPositions1
TArray<FVector3d> UE::Geometry::FMeshBevel::FBevelEdge::NewPositions1
Definition at line 210 of file MeshBevel.h.
NormalsA
TArray<FVector3d> UE::Geometry::FMeshBevel::FBevelEdge::NormalsA
Definition at line 216 of file MeshBevel.h.
NormalsB
TArray<FVector3d> UE::Geometry::FMeshBevel::FBevelEdge::NormalsB
Definition at line 216 of file MeshBevel.h.
StripQuadPatch
FQuadGridPatch UE::Geometry::FMeshBevel::FBevelEdge::StripQuadPatch
Definition at line 215 of file MeshBevel.h.
StripQuads
TArray<FIndex2i> UE::Geometry::FMeshBevel::FBevelEdge::StripQuads
Definition at line 214 of file MeshBevel.h.
The documentation for this struct was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/GeometryProcessing/Source/DynamicMesh/Public/Operations/MeshBevel.h