Unreal Engine 5.6 C++ API: TAddKeyImpl< FMovieSceneFloatChannel, float > Struct Reference
TAddKeyImpl< FMovieSceneFloatChannel, float > Struct Reference
#include "KeyframeTrackEditor.h"
Public Member Functions
TAddKeyImpl (int32 InChannelIndex, bool bInAddKey, const float &InValue)
virtual bool Apply (UMovieSceneSection *Section, FMovieSceneChannelProxy &Proxy, FFrameNumber InTime, EMovieSceneKeyInterpolation InterpolationMode, bool bKeyEvenIfUnchanged, bool bKeyEvenIfEmpty) const override
virtual void ApplyDefault (UMovieSceneSection *Section, FMovieSceneChannelProxy &Proxy, EKeyFrameTrackEditorSetDefault SetDefault) const override
virtual bool ModifyByCurrentAndWeight (FMovieSceneChannelProxy &Proxy, FFrameNumber InTime, void *VCurrentValue, float Weight) override
Public Member Functions inherited from IImpl
virtual ~IImpl ()
Data Fields
bool bAddKey
int32 ChannelIndex
float ValueToSet
Detailed Description
Definition at line 254 of file KeyframeTrackEditor.h.
Constructor & Destructor Documentation
TAddKeyImpl()
TAddKeyImpl< FMovieSceneFloatChannel, float >::TAddKeyImpl (int32 InChannelIndex, bool bInAddKey, const float & InValue) inline
Definition at line 260 of file KeyframeTrackEditor.h.
References bAddKey, ChannelIndex, and ValueToSet.
Member Function Documentation
Apply()
virtual bool TAddKeyImpl< FMovieSceneFloatChannel, float >::Apply (UMovieSceneSection * Section, FMovieSceneChannelProxy & Proxy, FFrameNumber InTime, EMovieSceneKeyInterpolation InterpolationMode, bool bKeyEvenIfUnchanged, bool bKeyEvenIfEmpty) const inline override virtual
Reimplemented from IImpl.
Definition at line 264 of file KeyframeTrackEditor.h.
References AddKeyToChannel(), bAddKey, ChannelIndex, FMovieSceneChannelProxy::GetChannel(), GetInterpolationMode(), InTime, ValueExistsAtTime(), and ValueToSet.
ApplyDefault()
virtual void TAddKeyImpl< FMovieSceneFloatChannel, float >::ApplyDefault (UMovieSceneSection * Section, FMovieSceneChannelProxy & Proxy, EKeyFrameTrackEditorSetDefault SetDefault) const inline override virtual
Reimplemented from IImpl.
Definition at line 295 of file KeyframeTrackEditor.h.
References bAddKey, ChannelIndex, FMovieSceneChannelProxy::GetChannel(), UE::MovieScene::SetChannelDefault(), SetDefault, SetDefaultOnAddKeys, and ValueToSet.
ModifyByCurrentAndWeight()
virtual bool TAddKeyImpl< FMovieSceneFloatChannel, float >::ModifyByCurrentAndWeight (FMovieSceneChannelProxy & Proxy, FFrameNumber InTime, void * VCurrentValue, float Weight) inline override virtual
Reimplemented from IImpl.
Definition at line 311 of file KeyframeTrackEditor.h.
References ChannelIndex, EvaluateChannel(), FMovieSceneChannelProxy::GetChannel(), TOptional< OptionalType >::GetValue(), InTime, TOptional< OptionalType >::IsSet(), ValueToSet, and Weight.
Field Documentation
bAddKey
bool TAddKeyImpl< FMovieSceneFloatChannel, float >::bAddKey
Definition at line 257 of file KeyframeTrackEditor.h.
Referenced by TAddKeyImpl(), Apply(), and ApplyDefault().
ChannelIndex
int32 TAddKeyImpl< FMovieSceneFloatChannel, float >::ChannelIndex
Definition at line 256 of file KeyframeTrackEditor.h.
Referenced by TAddKeyImpl(), Apply(), ApplyDefault(), and ModifyByCurrentAndWeight().
ValueToSet
float TAddKeyImpl< FMovieSceneFloatChannel, float >::ValueToSet
Definition at line 258 of file KeyframeTrackEditor.h.
Referenced by TAddKeyImpl(), Apply(), ApplyDefault(), and ModifyByCurrentAndWeight().
The documentation for this struct was generated from the following file:
Editor/MovieSceneTools/Public/KeyframeTrackEditor.h