Unreal Engine 5.6 C++ API: FCurveModelID Struct Reference
FCurveModelID Struct Reference
A unique identifier for a curve model existing on a curve editor.
#include "CurveEditorTypes.h"
Public Member Functions
FCurveModelID ()
Default constructor is needed by e.g.
bool IsValid () const
Static Public Member Functions
static FCurveModelID Unique ()
Generate a new curve model ID.
Private Attributes
uint32 ID
Internal serial ID.
Friends
FORCEINLINE friend uint32 GetTypeHash (FCurveModelID In)
Hash a curve model ID.
FORCEINLINE friend bool operator!= (FCurveModelID A, FCurveModelID B)
Check two IDs for inequality.
FORCEINLINE friend bool operator< (FCurveModelID A, FCurveModelID B)
Test whether A is less than B.
FORCEINLINE friend FArchive & operator<< (FArchive &Ar, FCurveModelID &Handle)
Save a curve model ID.
FORCEINLINE friend bool operator== (FCurveModelID A, FCurveModelID B)
Check two IDs for equality.
Detailed Description
A unique identifier for a curve model existing on a curve editor.
Definition at line 48 of file CurveEditorTypes.h.
Constructor & Destructor Documentation
FCurveModelID()
FCurveModelID::FCurveModelID () inline
Default constructor is needed by e.g.
TArray::operator<<
Definition at line 51 of file CurveEditorTypes.h.
References ID.
Referenced by GetTypeHash, operator!=, operator<, operator<<, operator==, and Unique().
Member Function Documentation
IsValid()
bool FCurveModelID::IsValid () const inline
Returns
Whether this ID is valid (was constructed with Unique)
Definition at line 61 of file CurveEditorTypes.h.
References ID.
Unique()
FCurveModelID FCurveModelID::Unique () static
Generate a new curve model ID.
References FCurveModelID().
Referenced by FCurveModel::InitCurveId().
Friends And Related Symbol Documentation
GetTypeHash
FORCEINLINE friend uint32 GetTypeHash (FCurveModelID In) friend
Hash a curve model ID.
Definition at line 90 of file CurveEditorTypes.h.
References FCurveModelID(), FORCEINLINE, GetTypeHash(), and ID.
operator!=
FORCEINLINE friend bool operator!= (FCurveModelID A, FCurveModelID B) friend
Check two IDs for inequality.
Definition at line 74 of file CurveEditorTypes.h.
References FCurveModelID(), A, B, and FORCEINLINE.
operator<
FORCEINLINE friend bool operator< (FCurveModelID A, FCurveModelID B) friend
Test whether A is less than B.
Definition at line 82 of file CurveEditorTypes.h.
References FCurveModelID(), A, B, and FORCEINLINE.
operator<<
FORCEINLINE friend FArchive & operator<< (FArchive & Ar, FCurveModelID & Handle) friend
Save a curve model ID.
Definition at line 98 of file CurveEditorTypes.h.
References FCurveModelID(), Ar, FORCEINLINE, and Handle.
operator==
FORCEINLINE friend bool operator== (FCurveModelID A, FCurveModelID B) friend
Check two IDs for equality.
Definition at line 66 of file CurveEditorTypes.h.
References FCurveModelID(), A, B, and FORCEINLINE.
Field Documentation
ID
uint32 FCurveModelID::ID private
Internal serial ID.
Definition at line 107 of file CurveEditorTypes.h.
Referenced by FCurveModelID(), GetTypeHash, and IsValid().
The documentation for this struct was generated from the following file:
Editor/CurveEditor/Public/CurveEditorTypes.h