Unreal Engine 5.6 C++ API: FAndroidGamepadDeviceMapping Struct Reference
FAndroidGamepadDeviceMapping Struct Reference
#include "AndroidInputInterface.h"
Public Member Functions
FAndroidGamepadDeviceMapping ()
FAndroidGamepadDeviceMapping (const FName DeviceName)
void Init (const FName DeviceName)
void ResetRuntimeData ()
Data Fields
ButtonRemapType ButtonRemapping = ButtonRemapType::Normal
ControllerClassType ControllerClass = ControllerClassType::Generic
FAndroidControllerVibeState ControllerVibeState
float LTAnalogRangeMinimum = .0f
bool MapL1R1ToTriggers = false
bool MapRXRYToTriggers = false
bool MapZRZToTriggers = false
FAndroidControllerData NewControllerData
FAndroidControllerData OldControllerData
bool RightStickRXRY = false
bool RightStickZRZ = true
float RTAnalogRangeMinimum = .0f
bool SupportsHat = true
bool TriggersUseThresholdForClick = false
Detailed Description
Definition at line 185 of file AndroidInputInterface.h.
Constructor & Destructor Documentation
FAndroidGamepadDeviceMapping() [1/2]
FAndroidGamepadDeviceMapping::FAndroidGamepadDeviceMapping () inline
Definition at line 187 of file AndroidInputInterface.h.
References ResetRuntimeData().
FAndroidGamepadDeviceMapping() [2/2]
FAndroidGamepadDeviceMapping::FAndroidGamepadDeviceMapping (const FName DeviceName) inline
Definition at line 192 of file AndroidInputInterface.h.
References Init.
Member Function Documentation
Init()
void FAndroidGamepadDeviceMapping::Init (const FName DeviceName)
ResetRuntimeData()
void FAndroidGamepadDeviceMapping::ResetRuntimeData () inline
Definition at line 199 of file AndroidInputInterface.h.
References ControllerVibeState, FMemory::Memset(), NewControllerData, and OldControllerData.
Referenced by FAndroidGamepadDeviceMapping().
Field Documentation
ButtonRemapping
ButtonRemapType FAndroidGamepadDeviceMapping::ButtonRemapping = ButtonRemapType::Normal
Definition at line 210 of file AndroidInputInterface.h.
ControllerClass
ControllerClassType FAndroidGamepadDeviceMapping::ControllerClass = ControllerClassType::Generic
Definition at line 207 of file AndroidInputInterface.h.
ControllerVibeState
FAndroidControllerVibeState FAndroidGamepadDeviceMapping::ControllerVibeState
Definition at line 239 of file AndroidInputInterface.h.
Referenced by ResetRuntimeData().
LTAnalogRangeMinimum
float FAndroidGamepadDeviceMapping::LTAnalogRangeMinimum = .0f
Definition at line 213 of file AndroidInputInterface.h.
MapL1R1ToTriggers
bool FAndroidGamepadDeviceMapping::MapL1R1ToTriggers = false
Definition at line 223 of file AndroidInputInterface.h.
MapRXRYToTriggers
bool FAndroidGamepadDeviceMapping::MapRXRYToTriggers = false
Definition at line 235 of file AndroidInputInterface.h.
MapZRZToTriggers
bool FAndroidGamepadDeviceMapping::MapZRZToTriggers = false
Definition at line 226 of file AndroidInputInterface.h.
NewControllerData
FAndroidControllerData FAndroidGamepadDeviceMapping::NewControllerData
Definition at line 238 of file AndroidInputInterface.h.
Referenced by ResetRuntimeData().
OldControllerData
FAndroidControllerData FAndroidGamepadDeviceMapping::OldControllerData
Definition at line 237 of file AndroidInputInterface.h.
Referenced by ResetRuntimeData().
RightStickRXRY
bool FAndroidGamepadDeviceMapping::RightStickRXRY = false
Definition at line 232 of file AndroidInputInterface.h.
RightStickZRZ
bool FAndroidGamepadDeviceMapping::RightStickZRZ = true
Definition at line 229 of file AndroidInputInterface.h.
RTAnalogRangeMinimum
float FAndroidGamepadDeviceMapping::RTAnalogRangeMinimum = .0f
Definition at line 214 of file AndroidInputInterface.h.
SupportsHat
bool FAndroidGamepadDeviceMapping::SupportsHat = true
Definition at line 217 of file AndroidInputInterface.h.
TriggersUseThresholdForClick
bool FAndroidGamepadDeviceMapping::TriggersUseThresholdForClick = false
Definition at line 220 of file AndroidInputInterface.h.
The documentation for this struct was generated from the following file:
Runtime/ApplicationCore/Public/Android/AndroidInputInterface.h