Unreal Engine 5.6 C++ API: FMemory Struct Reference
FMemory Struct Reference
#include "UnrealMemory.h"
Public Types
enum AllocationHints {
None = -1 , Default , Temporary , SmallPool ,
Max
}
Some allocators can be given hints to treat allocations differently depending on how the memory is used, it's lifetime etc.
Memory functions (wrapper for FPlatformMemory)
uint32 Alignment = DEFAULT_ALIGNMENT)
Returns true if memory is zeroes, false otherwise.
SIZE_T Count
Returns true if memory is zeroes, false otherwise.
SIZE_T uint32 Alignment = DEFAULT_ALIGNMENT)
Returns true if memory is zeroes, false otherwise.
SIZE_T
Returns true if memory is zeroes, false otherwise.
static FORCEINLINE void * Memmove (void *Dest, const void *Src, SIZE_T Count)
Returns true if memory is zeroes, false otherwise.
static FORCEINLINE int32 Memcmp (const void *Buf1, const void *Buf2, SIZE_T Count)
Returns true if memory is zeroes, false otherwise.
static FORCEINLINE void * Memset (void *Dest, uint8 Char, SIZE_T Count)
Returns true if memory is zeroes, false otherwise.
template<class T>
static FORCEINLINE void Memset (T &Src, uint8 ValueToSet)
Returns true if memory is zeroes, false otherwise.
static FORCEINLINE void * Memzero (void *Dest, SIZE_T Count)
Returns true if memory is zeroes, false otherwise.
static FORCEINLINE bool MemIsZero (const void *Ptr, SIZE_T Count)
Returns true if memory is zeroes, false otherwise.
template<class T>
static FORCEINLINE void Memzero (T &Src)
Returns true if memory is zeroes, false otherwise.
static FORCEINLINE void * Memcpy (void *Dest, const void *Src, SIZE_T Count)
Returns true if memory is zeroes, false otherwise.
template<class T>
static FORCEINLINE void Memcpy (T &Dest, const T &Src)
Returns true if memory is zeroes, false otherwise.
static FORCEINLINE void * BigBlockMemcpy (void *Dest, const void *Src, SIZE_T Count)
Returns true if memory is zeroes, false otherwise.
static FORCEINLINE void * StreamingMemcpy (void *Dest, const void *Src, SIZE_T Count)
Returns true if memory is zeroes, false otherwise.
static FORCEINLINE void * ParallelMemcpy (void *Dest, const void *Src, SIZE_T Count, EMemcpyCachePolicy Policy=EMemcpyCachePolicy::StoreCached)
Returns true if memory is zeroes, false otherwise.
static FORCEINLINE void Memswap (void *Ptr1, void *Ptr2, SIZE_T Size)
Returns true if memory is zeroes, false otherwise.
static FORCEINLINE void SystemFree (void *Ptr)
Returns true if memory is zeroes, false otherwise.
static void Free (void *Original)
Returns true if memory is zeroes, false otherwise.
static SIZE_T GetAllocSize (void *Original)
Returns true if memory is zeroes, false otherwise.
static SIZE_T QuantizeSize (SIZE_T Count, uint32 Alignment=DEFAULT_ALIGNMENT)
For some allocators this will return the actual size that should be requested to eliminate internal fragmentation.
static void Trim (bool bTrimThreadCaches=true)
Releases as much memory as possible.
static void SetupTLSCachesOnCurrentThread ()
Set up TLS caches on the current thread.
static void ClearAndDisableTLSCachesOnCurrentThread ()
Clears the TLS caches on the current thread and disables any future caching.
static void MarkTLSCachesAsUsedOnCurrentThread ()
Mark TLS caches for the current thread as used.
static void MarkTLSCachesAsUnusedOnCurrentThread ()
Mark TLS caches for current thread as unused.
static void TestMemory ()
A helper function that will perform a series of random heap allocations to test the internal validity of the heap.
static void EnablePurgatoryTests ()
Called once main is started and we have -purgatorymallocproxy.
static void EnablePoisonTests ()
Called once main is started and we have -poisonmallocproxy.
static void ExplicitInit (FMalloc &Allocator)
Set global allocator instead of creating it lazily on first allocation.
UE_ALLOCATION_FUNCTION (1) static FORCEINLINE void *SystemMalloc(SIZE_T Size)
Returns true if memory is zeroes, false otherwise.
UE_ALLOCATION_FUNCTION (1, 2) static 1 void *Malloc(SIZE_T Count
Returns true if memory is zeroes, false otherwise.
UE_ALLOCATION_FUNCTION (2, 3) static 1 void *Realloc(void *Original
Returns true if memory is zeroes, false otherwise.
UE_ALLOCATION_FUNCTION (1, 2) static 1 void *MallocZeroed(SIZE_T Count
Returns true if memory is zeroes, false otherwise.
UE_DEPRECATED (5.5, "Persistent Auxiliary allocator is obsolete and is replaced by a GetPersistentLinearAllocator()") static inline void RegisterPersistentAuxiliary(void *
Functions to handle special memory given to the title from the platform This memory is allocated like a stack, it's never really freed.
UE_DEPRECATED (5.5, "Persistent Auxiliary allocator is obsolete and is replaced by a GetPersistentLinearAllocator()") static inline void FreePersistentAuxiliary(void *InPtr)
Returns true if memory is zeroes, false otherwise.
UE_DEPRECATED (5.5, "Persistent Auxiliary allocator is obsolete and is replaced by a GetPersistentLinearAllocator()") static 1 bool IsPersistentAuxiliaryActive()
Returns true if memory is zeroes, false otherwise.
UE_DEPRECATED (5.5, "Persistent Auxiliary allocator is obsolete and is replaced by a GetPersistentLinearAllocator()") static inline void DisablePersistentAuxiliary()
Returns true if memory is zeroes, false otherwise.
UE_DEPRECATED (5.5, "Persistent Auxiliary allocator is obsolete and is replaced by a GetPersistentLinearAllocator()") static inline void EnablePersistentAuxiliary()
Returns true if memory is zeroes, false otherwise.
UE_DEPRECATED (5.5, "Persistent Auxiliary allocator is obsolete and is replaced by a GetPersistentLinearAllocator()") static 1 SIZE_T GetUsedPersistentAuxiliary()
Returns true if memory is zeroes, false otherwise.
static void GCreateMalloc ()
Returns true if memory is zeroes, false otherwise.
static void * MallocExternal (SIZE_T Count, uint32 Alignment=DEFAULT_ALIGNMENT)
Returns true if memory is zeroes, false otherwise.
static void * ReallocExternal (void *Original, SIZE_T Count, uint32 Alignment=DEFAULT_ALIGNMENT)
Returns true if memory is zeroes, false otherwise.
static void FreeExternal (void *Original)
Returns true if memory is zeroes, false otherwise.
static SIZE_T GetAllocSizeExternal (void *Original)
Returns true if memory is zeroes, false otherwise.
static void * MallocZeroedExternal (SIZE_T Count, uint32 Alignment=DEFAULT_ALIGNMENT)
Returns true if memory is zeroes, false otherwise.
static SIZE_T QuantizeSizeExternal (SIZE_T Count, uint32 Alignment=DEFAULT_ALIGNMENT)
Returns true if memory is zeroes, false otherwise.
Detailed Description
Definition at line 93 of file UnrealMemory.h.
Member Enumeration Documentation
AllocationHints
enum FMemory::AllocationHints
Some allocators can be given hints to treat allocations differently depending on how the memory is used, it's lifetime etc.
Enumerator
None
Default
Temporary
SmallPool
Max
Definition at line 96 of file UnrealMemory.h.
Member Function Documentation
BigBlockMemcpy()
FORCEINLINE void * FMemory::BigBlockMemcpy (void * Dest, const void * Src, SIZE_T Count) inline static
Returns true if memory is zeroes, false otherwise.
Definition at line 172 of file UnrealMemory.h.
References FGenericPlatformMemory::BigBlockMemcpy(), Count, FORCEINLINE, and SIZE_T.
ClearAndDisableTLSCachesOnCurrentThread()
void FMemory::ClearAndDisableTLSCachesOnCurrentThread () static
Clears the TLS caches on the current thread and disables any future caching.
References ClearAndDisableTLSCachesOnCurrentThread().
Referenced by ClearAndDisableTLSCachesOnCurrentThread().
EnablePoisonTests()
void FMemory::EnablePoisonTests () static
Called once main is started and we have -poisonmallocproxy.
References EnablePoisonTests().
Referenced by EnablePoisonTests().
EnablePurgatoryTests()
void FMemory::EnablePurgatoryTests () static
Called once main is started and we have -purgatorymallocproxy.
This uses the purgatory malloc proxy to check if things are writing to stale pointers.
References EnablePurgatoryTests().
Referenced by EnablePurgatoryTests().
ExplicitInit()
void FMemory::ExplicitInit (FMalloc & Allocator) static
Set global allocator instead of creating it lazily on first allocation.
Must only be called once and only if lazy init is disabled via a macro.
References Allocator, and ExplicitInit().
Referenced by ExplicitInit().
Free()
void FMemory::Free (void * Original) static
Returns true if memory is zeroes, false otherwise.
References Free().
Referenced by FDefaultConstructedPropertyElement::FDefaultConstructedPropertyElement(), FAudioChunkCache::FCacheElement::~FCacheElement(), UE::Geometry::FMeshMapTileBuffer::~FMeshMapTileBuffer(), TAlignedHeapAllocator< Alignment >::ForAnyElementType::~ForAnyElementType(), TNonRelocatableInlineAllocator< NumInlineElements >::ForElementType< ElementType >::~ForElementType(), TBasicArray< T >::~TBasicArray(), TUniformBuffer< FLightmapResourceClusterShaderParameters >::~TUniformBuffer(), FAsyncSHAVerify::Abandon(), UE::MovieScene::FPlaybackCapabilitiesImpl::AddCapability(), FBufferReaderBase::Close(), FBufferWriter::Close(), TInlineValue< FChannelOverrideProviderTraits, 64 >::ConditionallyDestroyAllocation(), Experimental::TSherwoodHashTable_Private::TSherwoodHashTable< KeyType, ValueType, KeyFuncs >::Deallocate(), FStructOnScope::Destroy(), TMemoryImageObject< T >::Destroy(), UE::Core::Private::Function::TFunction_OwnedObject< T, bUnique, bOnHeap >::Destroy(), UE::FPlatformIoDispatcherRequestMgr::Destroy(), FAlignedAllocator::Free(), Free(), TLockFreeFixedSizeAllocator_TLSCacheBase< SIZE, TBundleRecycler, TTrackingCounter >::Free(), UE::Logging::Private::FMemoryLogTemplateStorage::Free(), UE::PixelStreaming2::FEpicRtcAllocator::Free(), FBulkDataBuffer< DataType >::FreeBuffer(), UE::FDynamicallyTypedValue::FreeData(), TAlignedHeapAllocator< Alignment >::ForAnyElementType::MoveToEmpty(), TNonRelocatableInlineAllocator< NumInlineElements >::ForElementType< ElementType >::MoveToEmpty(), FHazardPointerCollection::FHazardRecordChunk::operator delete(), FQueuedLowLevelThreadPool::operator delete(), FSlateControlledConstruction::operator delete(), SUserWidget::operator delete(), FStructSharedMemory::FStructSharedMemoryDeleter::operator()(), ICookedPackageWriter::FDeleteByFree::operator()(), UE::ArchiveStackTrace::FDeleteByFree::operator()(), UE::FIoFileBlockMemoryPool::FDeleteByFree::operator()(), UE::AnimNext::FEvaluationVM::PopValue(), FScatterUploadBuffer::Release(), UE::TSharedString< CharType >::Release(), TAudioBuffer< DataType >::Reset(), TMaybeMappedAllocator< Alignment >::ForAnyElementType::Reset(), TNonRelocatableInlineAllocator< NumInlineElements >::ForElementType< ElementType >::ResizeAllocation(), and TLockFreeFixedSizeAllocator< PageSize, PLATFORM_CACHE_LINE_SIZE, FThreadSafeCounter >::Trim().
FreeExternal()
void FMemory::FreeExternal (void * Original) static private
Returns true if memory is zeroes, false otherwise.
References FreeExternal().
Referenced by FreeExternal().
GCreateMalloc()
void FMemory::GCreateMalloc () static private
Returns true if memory is zeroes, false otherwise.
References GCreateMalloc().
Referenced by GCreateMalloc().
GetAllocSize()
SIZE_T FMemory::GetAllocSize (void * Original) static
Returns true if memory is zeroes, false otherwise.
References GetAllocSize(), and SIZE_T.
Referenced by GetAllocSize().
GetAllocSizeExternal()
SIZE_T FMemory::GetAllocSizeExternal (void * Original) static private
Returns true if memory is zeroes, false otherwise.
References GetAllocSizeExternal(), and SIZE_T.
Referenced by GetAllocSizeExternal().
MallocExternal()
void * FMemory::MallocExternal (SIZE_T Count, uint32 Alignment = DEFAULT_ALIGNMENT) static private
Returns true if memory is zeroes, false otherwise.
References Alignment, Count, DEFAULT_ALIGNMENT, MallocExternal(), and SIZE_T.
Referenced by MallocExternal().
MallocZeroedExternal()
void * FMemory::MallocZeroedExternal (SIZE_T Count, uint32 Alignment = DEFAULT_ALIGNMENT) static private
Returns true if memory is zeroes, false otherwise.
References Alignment, Count, DEFAULT_ALIGNMENT, MallocZeroedExternal(), and SIZE_T.
Referenced by MallocZeroedExternal().
MarkTLSCachesAsUnusedOnCurrentThread()
void FMemory::MarkTLSCachesAsUnusedOnCurrentThread () static
Mark TLS caches for current thread as unused.
Typically before going to sleep. These are the threads that we can trim without waking them up.
References MarkTLSCachesAsUnusedOnCurrentThread().
Referenced by MarkTLSCachesAsUnusedOnCurrentThread().
MarkTLSCachesAsUsedOnCurrentThread()
void FMemory::MarkTLSCachesAsUsedOnCurrentThread () static
Mark TLS caches for the current thread as used.
Thread has woken up to do some processing and needs its TLS caches back.
References MarkTLSCachesAsUsedOnCurrentThread().
Referenced by MarkTLSCachesAsUsedOnCurrentThread().
Memcmp()
FORCEINLINE int32 FMemory::Memcmp (const void * Buf1, const void * Buf2, SIZE_T Count) inline static
Returns true if memory is zeroes, false otherwise.
Definition at line 114 of file UnrealMemory.h.
References Count, FORCEINLINE, FGenericPlatformMemory::Memcmp(), and SIZE_T.
Referenced by FIoStoreTocHeader::CheckMagic(), TMemoryView< const void >::CompareBytes(), CompareItems(), StatelessConnectHandlerComponent::DoesRestartedHandshakeMatch(), TMemoryView< const void >::EqualBytes(), FBlake3Hash::operator!=(), FCbObjectId::operator!=(), FIoBuffer::operator!=(), FIoHash::operator!=, FMD5Hash::operator!=, FSHAHash::operator!=, TSequenceHistory< MaxSequenceHistoryLength >::operator!=(), UE::MovieScene::FHierarchicalBlendTarget::operator!=, FBlake3Hash::operator<(), FCbObjectId::operator<(), FIoChunkId::operator<(), FIoHash::operator<, FSHAHash::operator<, UE::MovieScene::FHierarchicalBlendTarget::operator<, FAES::FAESKey::operator==(), FBlake3Hash::operator==(), FCbObjectId::operator==(), FIoChunkId::operator==(), FIoHash::operator==, FMD5Hash::operator==, FSHAHash::operator==, TBitArray< typename Allocator::BitArrayAllocator >::operator==(), TSequenceHistory< MaxSequenceHistoryLength >::operator==(), UE::MovieScene::FHierarchicalBlendTarget::operator==, and FIoChunkId::operator>().
Memcpy() [1/2]
template<class T> FORCEINLINE void FMemory::Memcpy (T & Dest, const T & Src) inline static
Returns true if memory is zeroes, false otherwise.
Definition at line 166 of file UnrealMemory.h.
References FORCEINLINE, Memcpy(), and TIsPointer< T >::Value.
Memcpy() [2/2]
FORCEINLINE void * FMemory::Memcpy (void * Dest, const void * Src, SIZE_T Count) inline static
Returns true if memory is zeroes, false otherwise.
Definition at line 160 of file UnrealMemory.h.
References Count, FORCEINLINE, FGenericPlatformMemory::Memcpy(), and SIZE_T.
Referenced by FBlake3Hash::FBlake3Hash(), FCbObjectId::FCbObjectId(), UE::Core::Private::Function::FFunctionStorage::FFunctionStorage(), FHashTable::FHashTable(), FIoHash::FIoHash(), FIoHash::FIoHash(), FQueuedDemoPacket::FQueuedDemoPacket(), FQueuedDemoPacket::FQueuedDemoPacket(), FSlateTextureData::FSlateTextureData(), TBigInt< NumBits, bSigned >::TBigInt(), TBigInt< NumBits, bSigned >::TBigInt(), UE::Core::Private::Function::TFunctionRefBase< StorageType, Ret(ParamTypes...)>::TFunctionRefBase(), UE::Core::Private::Function::TFunctionRefBase< StorageType, Ret(ParamTypes...)>::TFunctionRefBase(), UE::Core::Private::Function::TFunctionRefBase< StorageType, Ret(ParamTypes...)>::TFunctionRefBase(), UE::Core::Private::Function::TFunctionRefBase< StorageType, Ret(ParamTypes...)>::TFunctionRefBase(), UE::MemStack::AllocateString(), KeyChainUtilities::ApplyEncryptionKeys(), TBitArray< typename Allocator::BitArrayAllocator >::Assign(), ConstructItems(), TAudioBuffer< DataType >::Copy(), TAudioBuffer< DataType >::Copy(), CopyAssignItems(), FProperty::CopyCompleteValue(), FClipSMFace::CopyFace(), TMemoryView< const void >::CopyFrom(), UE::MovieScene::FComponentTypeInfo::CopyItems(), UE::Geometry::TDynamicVertexSkinWeightsAttribute< FDynamicMesh3 >::CopyOut(), FProperty::CopySingleValue(), TStringView< CharType >::CopyString(), TChunkedArray< TUniquePtr< DescType > >::CopyToLinearArray(), UE::MovieScene::TFixedSparseBitSet< HashType, BucketStorage >::CopyToUnsafe(), THashTable< FMemoryImageAllocator >::CopyUnfrozen(), TSet< class UObject * >::CopyUnfrozen(), FPrimitiveUniformShaderParametersBuilder::CustomPrimitiveData(), UE::MovieScene::FPropertyRegistry::DefinePropertyImpl(), FLandscapeConfigHelper::ExpandData(), FXxHash128::FromByteArray(), FXxHash64::FromByteArray(), FBlake3Hash::FromView(), FIoHash::FromView(), UE::FIoFileBlockCache::Get(), UE::PixelStreaming2::FBufferBuilder::Insert(), UE::PixelStreaming::BufferBuilder::Insert(), KeyChainUtilities::LoadKeyChainFromFile(), FIoStoreTocHeader::MakeMagic(), MD5HashToGuid(), Memcpy(), UMaterialCacheVirtualTextureDescriptor::operator FUintVector2(), FBulkDataBuffer< DataType >::operator=(), FHashTable::operator=(), TSparseArray< SetElementType, typename Allocator::SparseArrayAllocator >::operator=(), UE::FIoFileBlockCache::Put(), FCachedFileHandle::Read(), FMallocDebug::Realloc(), FMallocBinned2::ReallocInline(), TMemStackAllocator< Alignment >::ForElementType< FScriptContainerElement >::ResizeAllocation(), TRDGArrayAllocator< Alignment >::ForElementType< FScriptContainerElement >::ResizeAllocation(), FBinaryHeap< KeyType, IndexType >::ResizeHeap(), RigVMCopy(), TDeltaSetup< ElementType, DeltaType >::FReader::Scatter(), FArrayReader::Serialize(), FBufferReaderBase::Serialize(), FBufferWriter::Serialize(), FBulkDataWriter::Serialize(), FDynamicEmitterReplayDataBase::Serialize(), FMemoryReader::Serialize(), FObjectReader::Serialize(), FStaticMemoryReader::Serialize(), TMemoryWriterBase< TSizedDefaultAllocator< IndexSize > >< 32 >::Serialize(), UE::Geometry::TDynamicVector< Type, BlockSize >::Serialize(), UE::Geometry::TDynamicVertexSkinWeightsAttribute< FDynamicMesh3 >::Serialize(), UE::PixelStreaming2::FBufferBuilder::Serialize(), FIoChunkId::Set(), FIoChunkId::Set(), TUniformBuffer< FLightmapResourceClusterShaderParameters >::SetContentsNoUpdate(), Nanite::FPackedCluster::SetVertResourceBatchInfo(), TraceServices::TCachedStringStore< WIDECHAR >::StoreInternal(), FXxHash128::ToByteArray(), FXxHash64::ToByteArray(), FName::ToUnstableInt(), SAnimAttributeView::FAttributeValueView::UpdateValue(), VectorStore(), VectorStore(), VectorStore16(), VectorStoreAligned(), VectorStoreAligned(), VectorStoreFloat1(), VectorStoreFloat1(), VectorStoreFloat3(), VectorStoreFloat3(), FMemoryImageSection::WriteBytes(), and TraceServices::FMetadataSchema::FWriter::WriteField().
MemIsZero()
FORCEINLINE bool FMemory::MemIsZero (const void * Ptr, SIZE_T Count) inline static
Returns true if memory is zeroes, false otherwise.
Definition at line 137 of file UnrealMemory.h.
References Count, End, FORCEINLINE, and SIZE_T.
Memmove()
FORCEINLINE void * FMemory::Memmove (void * Dest, const void * Src, SIZE_T Count) inline static
Returns true if memory is zeroes, false otherwise.
Definition at line 109 of file UnrealMemory.h.
References Count, FORCEINLINE, FGenericPlatformMemory::Memmove(), and SIZE_T.
Referenced by UE::MovieScene::FPlaybackCapabilitiesImpl::AddCapability(), StringConv::InlineCombineSurrogates_Buffer(), TScriptArray< FHeapAllocator >::Insert(), MoveAssignItems(), MoveConstructItems(), RelocateConstructItem(), RelocateConstructItems(), UE::MovieScene::FComponentTypeInfo::RelocateConstructItems(), TScriptArray< FHeapAllocator >::Remove(), TAttributeArrayContainer< AttributeType >::SetElementSize(), and FLandscapeEditDataInterface::ShrinkData().
Memset() [1/2]
template<class T> FORCEINLINE void FMemory::Memset (T & Src, uint8 ValueToSet) inline static
Returns true if memory is zeroes, false otherwise.
Definition at line 125 of file UnrealMemory.h.
References FORCEINLINE, Memset(), and TIsPointer< T >::Value.
Memset() [2/2]
FORCEINLINE void * FMemory::Memset (void * Dest, uint8 Char, SIZE_T Count) inline static
Returns true if memory is zeroes, false otherwise.
Definition at line 119 of file UnrealMemory.h.
References Count, FORCEINLINE, FGenericPlatformMemory::Memset(), and SIZE_T.
Referenced by FBinaryHeap< KeyType, IndexType >::FBinaryHeap(), FHashTable::FHashTable(), FInterpCurvePoint< T >::FInterpCurvePoint(), FInterpCurvePoint< T >::FInterpCurvePoint(), FSHAHash::FSHAHash(), FVirtualInstrument::FVirtualInstrument(), THashTable< InAllocator >::THashTable(), Experimental::TSherwoodHashTable_Private::TSherwoodHashTable< KeyType, ValueType, KeyFuncs >::AllocateData(), FGainMatrix::ApplyToBuffer(), FBinaryHeap< KeyType, IndexType >::Clear(), FHashTable::Clear(), FHashTable::Clear(), THashTable< InAllocator >::Clear(), TStaticHashTable< HashSize, IndexSize >::Clear(), UE::MovieScene::FComponentTypeInfo::ConstructItems(), TAudioBuffer< DataType >::Copy(), TAudioBuffer< DataType >::Copy(), UE::AnimNext::TTransformArrayAoS< FDefaultAllocator >::DebugFill(), UE::AnimNext::TTransformArraySoA< FDefaultAllocator >::DebugFill(), DefaultConstructItems(), TAudioBuffer< DataType >::Deinterleave(), Freeze::DestroyObject(), TAudioBuffer< DataType >::FillData(), TAudioBuffer< DataType >::FillValidFrames(), FMallocDebug::Free(), FMallocPoisonProxy::Free(), UE::Geometry::FUniqueIndexSet::Initialize(), FMallocDebug::Malloc(), FMallocPoisonProxy::Malloc(), TConcurrentLinearBulkObjectAllocator< FDefaultBlockAllocationTag >::MallocAndMemset(), TConcurrentLinearBulkObjectAllocator< FDefaultBlockAllocationTag >::MallocAndMemset(), TConcurrentLinearBulkObjectAllocator< FDefaultBlockAllocationTag >::MallocAndMemsetArray(), Memset(), NewOned(), FMemStackBase::operator new, FMemStackBase::operator new, FMemStackBase::operator new[], FMemStackBase::operator new[], FMallocPoisonProxy::Realloc(), Experimental::TSherwoodHashTable_Private::TSherwoodHashTable< KeyType, ValueType, KeyFuncs >::Reset(), FAES::FAESKey::Reset(), FPredictMatch8::Reset(), FAndroidGamepadDeviceMapping::ResetRuntimeData(), Harmonix::Dsp::Effects::TMultipassBiquadFilter< T, Num >::ResetState(), TBitArray< typename Allocator::BitArrayAllocator >::SetWords(), Metasound::FAudioBuffer::Zero(), and TBigInt< NumBits, bSigned >::Zero().
Memswap()
FORCEINLINE void FMemory::Memswap (void * Ptr1, void * Ptr2, SIZE_T Size) inline static
Returns true if memory is zeroes, false otherwise.
Definition at line 187 of file UnrealMemory.h.
References FORCEINLINE, FGenericPlatformMemory::Memswap(), SIZE_T, and TSequenceHistory< HistorySize >::Size.
Referenced by FStructArrayView::Swap(), and TScriptArray< FHeapAllocator >::SwapMemory().
Memzero() [1/2]
template<class T> FORCEINLINE void FMemory::Memzero (T & Src) inline static
Returns true if memory is zeroes, false otherwise.
Definition at line 154 of file UnrealMemory.h.
References FORCEINLINE, Memzero(), and TIsPointer< T >::Value.
Memzero() [2/2]
FORCEINLINE void * FMemory::Memzero (void * Dest, SIZE_T Count) inline static
Returns true if memory is zeroes, false otherwise.
Definition at line 131 of file UnrealMemory.h.
References Count, FORCEINLINE, FGenericPlatformMemory::Memzero(), and SIZE_T.
Referenced by UAbilitySystemComponent::FAbilitySystemComponentDebugInfo::FAbilitySystemComponentDebugInfo(), FAsyncBufferFillData::FAsyncBufferFillData(), FMeshElementIndexer::FChunk::FChunk(), FClipSMPolygon::FClipSMPolygon(), FClipSMTriangle::FClipSMTriangle(), FContentComparisonAssetInfo::FContentComparisonAssetInfo(), FLightSample::FLightSample(), FMallocLeakReportOptions::FMallocLeakReportOptions(), FMaterialCompilationOutput::FMaterialCompilationOutput(), FMaterialShaders::FMaterialShaders(), FMaterialShaderTypes::FMaterialShaderTypes(), FNiagaraDIChaosDestruction_InstanceDataToPassToRT::FNiagaraDIChaosDestruction_InstanceDataToPassToRT(), FShaderPipeline::FShaderPipeline(), FStaticMeshLODGroup::FStaticMeshLODGroup(), FStaticMeshSection::FStaticMeshSection(), SkeletalMeshImportData::FVertex::FVertex(), FWaveFormatInfo::FWaveFormatInfo(), FLinuxApplication::SDLControllerState::SDLControllerState(), UE::MovieScene::TMaskedBlendable< double, 1 >::TMaskedBlendable(), UE::Math::TMatrix< double >::TMatrix(), TSplineMeshSceneProxyCommon< TDerived >::TSplineMeshSceneProxyCommon(), FAsyncBufferFillData::~FAsyncBufferFillData(), FScriptSetHelper::AddElement(), FScriptMapHelper::AddPair(), RangedForIteratorType< FAnimNextTraitEventPtr >::AddZeroed(), RangedForIteratorType< FAnimNextTraitEventPtr >::AddZeroed(), TScriptArray< FHeapAllocator >::AddZeroed(), TTransArray< T >::AddZeroed(), RangedForIteratorType< FAnimNextTraitEventPtr >::AddZeroed_GetRef(), Harmonix::Dsp::Effects::FDelay::Clear(), FScriptArrayHelper::ClearItems(), FProperty::ClearValue(), FProperty::ClearValue_InContainer(), FScriptMapHelper::ConstructItem(), FScriptSetHelper::ConstructItem(), FScriptArrayHelper::ConstructItems(), FPrimitiveUniformShaderParametersBuilder::CustomPrimitiveData(), UScriptStruct::TCppStructOps< CPPSTRUCT >::ExportTextItem(), FScriptMapHelper::FindOrAdd(), FAssetData::GetTagValue(), FAssetData::GetTagValueRef(), FDuplicatedVerticesBuffer::Init(), FProperty::InitializeValue(), FProperty::InitializeValue_InContainer(), RangedForIteratorType< FAnimNextTraitEventPtr >::InsertZeroed(), RangedForIteratorType< FAnimNextTraitEventPtr >::InsertZeroed(), TScriptArray< FHeapAllocator >::InsertZeroed(), RangedForIteratorType< FAnimNextTraitEventPtr >::InsertZeroed_GetRef(), Memzero(), NewZeroed(), FSoundGeneratorNull::OnGenerateAudio(), FMemStackBase::operator new, FMemStackBase::operator new, FMemStackBase::operator new[], FMemStackBase::operator new[], FChunkedFixedUObjectArray::PreAllocate(), RadixSort32(), RadixSort64(), TScriptBitArray< FDefaultBitArrayAllocator, FScriptBitArray >::Realloc(), TScriptBitArray< FDefaultBitArrayAllocator, FScriptBitArray >::ReallocGrow(), StatelessConnectHandlerComponent::ResetChallengeData(), RigVMInitialize(), FBitReader::SerializeBits(), TUniformBuffer< FLightmapResourceClusterShaderParameters >::SetContentsToZero(), FShaderSource::SetLen(), Nanite::FPackedCluster::SetVertResourceBatchInfo(), USTRUCT(), USTRUCT(), USTRUCT(), UE::MovieScene::FSimpleBlenderEnumResultTraits::ZeroAccumulationBuffer(), and UE::MovieScene::TSimpleBlendResultTraits< PropertyType >::ZeroAccumulationBuffer().
ParallelMemcpy()
FORCEINLINE void * FMemory::ParallelMemcpy (void * Dest, const void * Src, SIZE_T Count, EMemcpyCachePolicy Policy = EMemcpyCachePolicy::StoreCached) inline static
Returns true if memory is zeroes, false otherwise.
Definition at line 182 of file UnrealMemory.h.
References Count, FORCEINLINE, FGenericPlatformMemory::ParallelMemcpy(), SIZE_T, and StoreCached.
Referenced by FRDGScatterUploadBase::Add(), FRDGScatterUploadBase::Add(), and FScatterUploadBuffer::Add().
QuantizeSize()
SIZE_T FMemory::QuantizeSize (SIZE_T Count, uint32 Alignment = DEFAULT_ALIGNMENT) static
For some allocators this will return the actual size that should be requested to eliminate internal fragmentation.
The return value will always be >= Count. This can be used to grow and shrink containers to optimal sizes. This call is always fast and threadsafe with no locking.
References Alignment, Count, DEFAULT_ALIGNMENT, QuantizeSize(), and SIZE_T.
Referenced by DefaultCalculateSlackGrow(), DefaultCalculateSlackReserve(), DefaultCalculateSlackShrink(), and QuantizeSize().
QuantizeSizeExternal()
SIZE_T FMemory::QuantizeSizeExternal (SIZE_T Count, uint32 Alignment = DEFAULT_ALIGNMENT) static private
Returns true if memory is zeroes, false otherwise.
References Alignment, Count, DEFAULT_ALIGNMENT, QuantizeSizeExternal(), and SIZE_T.
Referenced by QuantizeSizeExternal().
ReallocExternal()
void * FMemory::ReallocExternal (void * Original, SIZE_T Count, uint32 Alignment = DEFAULT_ALIGNMENT) static private
Returns true if memory is zeroes, false otherwise.
References Alignment, Count, DEFAULT_ALIGNMENT, ReallocExternal(), and SIZE_T.
Referenced by ReallocExternal().
SetupTLSCachesOnCurrentThread()
void FMemory::SetupTLSCachesOnCurrentThread () static
Set up TLS caches on the current thread.
These are the threads that we can trim.
References SetupTLSCachesOnCurrentThread().
Referenced by SetupTLSCachesOnCurrentThread().
StreamingMemcpy()
FORCEINLINE void * FMemory::StreamingMemcpy (void * Dest, const void * Src, SIZE_T Count) inline static
Returns true if memory is zeroes, false otherwise.
Definition at line 177 of file UnrealMemory.h.
References Count, FORCEINLINE, SIZE_T, and FGenericPlatformMemory::StreamingMemcpy().
SystemFree()
FORCEINLINE void FMemory::SystemFree (void * Ptr) inline static
Returns true if memory is zeroes, false otherwise.
Definition at line 202 of file UnrealMemory.h.
References FORCEINLINE, MemoryTrace_Free(), and SystemMemory.
TestMemory()
void FMemory::TestMemory () static
A helper function that will perform a series of random heap allocations to test the internal validity of the heap.
Note, this function will "leak" memory, but another call will clean up previously allocated blocks before returning. This will help to A/B testing where you call it in a good state, do something to corrupt memory, then call this again and hopefully freeing some pointers will trigger a crash.
References TestMemory().
Referenced by TestMemory().
Trim()
void FMemory::Trim (bool bTrimThreadCaches = true) static
Releases as much memory as possible.
Must be called from the main thread.
References Trim().
Referenced by Trim().
UE_ALLOCATION_FUNCTION() [1/4]
FMemory::UE_ALLOCATION_FUNCTION (1) inline
Returns true if memory is zeroes, false otherwise.
Definition at line 195 of file UnrealMemory.h.
References FORCEINLINE, MemoryTrace_Alloc(), SIZE_T, SystemMemory, and TSequenceHistory< HistorySize >::Size.
Referenced by UE_ALLOCATION_FUNCTION().
UE_ALLOCATION_FUNCTION() [2/4]
FMemory::UE_ALLOCATION_FUNCTION (1 , 2)
Returns true if memory is zeroes, false otherwise.
UE_ALLOCATION_FUNCTION() [3/4]
FMemory::UE_ALLOCATION_FUNCTION (1 , 2)
Returns true if memory is zeroes, false otherwise.
References Alignment, Count, DEFAULT_ALIGNMENT, SIZE_T, and UE_ALLOCATION_FUNCTION().
UE_ALLOCATION_FUNCTION() [4/4]
FMemory::UE_ALLOCATION_FUNCTION (2 , 3)
Returns true if memory is zeroes, false otherwise.
UE_DEPRECATED() [1/6]
FMemory::UE_DEPRECATED (5. 5, "Persistent Auxiliary allocator is obsolete and is replaced by a GetPersistentLinearAllocator()")
Returns true if memory is zeroes, false otherwise.
UE_DEPRECATED() [2/6]
FMemory::UE_DEPRECATED (5. 5, "Persistent Auxiliary allocator is obsolete and is replaced by a GetPersistentLinearAllocator()")
Returns true if memory is zeroes, false otherwise.
References SIZE_T.
UE_DEPRECATED() [3/6]
FMemory::UE_DEPRECATED (5. 5, "Persistent Auxiliary allocator is obsolete and is replaced by a GetPersistentLinearAllocator()") inline
Returns true if memory is zeroes, false otherwise.
Definition at line 291 of file UnrealMemory.h.
References UE_DEPRECATED().
UE_DEPRECATED() [4/6]
FMemory::UE_DEPRECATED (5. 5, "Persistent Auxiliary allocator is obsolete and is replaced by a GetPersistentLinearAllocator()") inline
Returns true if memory is zeroes, false otherwise.
Definition at line 294 of file UnrealMemory.h.
UE_DEPRECATED() [5/6]
FMemory::UE_DEPRECATED (5. 5, "Persistent Auxiliary allocator is obsolete and is replaced by a GetPersistentLinearAllocator()") inline
Returns true if memory is zeroes, false otherwise.
Definition at line 285 of file UnrealMemory.h.
References UE_DEPRECATED().
UE_DEPRECATED() [6/6]
FMemory::UE_DEPRECATED (5. 5, "Persistent Auxiliary allocator is obsolete and is replaced by a GetPersistentLinearAllocator()")
Functions to handle special memory given to the title from the platform This memory is allocated like a stack, it's never really freed.
References UE_DEPRECATED().
Referenced by UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
Field Documentation
Alignment [1/2]
uint32 FMemory::Alignment = DEFAULT_ALIGNMENT)
Returns true if memory is zeroes, false otherwise.
Definition at line 212 of file UnrealMemory.h.
Referenced by MallocExternal(), MallocZeroedExternal(), QuantizeSize(), QuantizeSizeExternal(), ReallocExternal(), and UE_ALLOCATION_FUNCTION().
Alignment [2/2]
SIZE_T uint32 FMemory::Alignment = DEFAULT_ALIGNMENT)
Returns true if memory is zeroes, false otherwise.
Definition at line 213 of file UnrealMemory.h.
Count
SIZE_T FMemory::Count
Returns true if memory is zeroes, false otherwise.
Definition at line 213 of file UnrealMemory.h.
Referenced by BigBlockMemcpy(), MallocExternal(), MallocZeroedExternal(), Memcmp(), Memcpy(), MemIsZero(), Memmove(), Memset(), Memzero(), ParallelMemcpy(), QuantizeSize(), QuantizeSizeExternal(), ReallocExternal(), StreamingMemcpy(), and UE_ALLOCATION_FUNCTION().
SIZE_T
FMemory::SIZE_T
Initial value:
{}
    UE_DEPRECATED(5.5, "Persistent Auxiliary allocator is obsolete and is replaced by a GetPersistentLinearAllocator()")
    static 1 void* MallocPersistentAuxiliary(SIZE_T InSize, uint32 InAlignment = 0)
Returns true if memory is zeroes, false otherwise.
Definition at line 280 of file UnrealMemory.h.
Referenced by BigBlockMemcpy(), GetAllocSize(), GetAllocSizeExternal(), MallocExternal(), MallocZeroedExternal(), Memcmp(), Memcpy(), MemIsZero(), Memmove(), Memset(), Memswap(), Memzero(), ParallelMemcpy(), QuantizeSize(), QuantizeSizeExternal(), ReallocExternal(), StreamingMemcpy(), UE_ALLOCATION_FUNCTION(), UE_ALLOCATION_FUNCTION(), and UE_DEPRECATED().
The documentation for this struct was generated from the following file:
Runtime/Core/Public/HAL/UnrealMemory.h