Unreal Engine 5.6 C++ API: FPersistentEvaluationData Struct Reference
FPersistentEvaluationData Struct Reference
Structure that stores persistent data that track templates may need during evaluation.
#include "PersistentEvaluationData.h"
Public Member Functions
FPersistentEvaluationData (const FPersistentEvaluationData &)=delete
MOVIESCENE_API FPersistentEvaluationData (IMovieScenePlayer &InPlayer)
Proxy constructor from 2 externally owned maps for entity, and shared data.
template<typename T>
T & Add (const FSharedPersistentDataKey &InKey)
template<typename T>
T & AddSectionData ()
template<typename T>
T & AddTrackData ()
const FMovieSceneEvaluationKey & DeriveSectionKey (uint32 InSectionIdentifier) const
Set the current section based off the current track with the specified section identifier.
template<typename T>
T * Find (const FSharedPersistentDataKey &InKey)
template<typename T>
const T * Find (const FSharedPersistentDataKey &InKey) const
template<typename T>
const T * FindInstanceData () const
Find the current sequence's instance data as the templated type, provided its type matches.
template<typename T>
T * FindSectionData () const
template<typename T>
T * FindTrackData ()
template<typename T>
T * FindTrackData () const
template<typename T>
T & Get (const FSharedPersistentDataKey &InKey)
template<typename T>
const T & Get (const FSharedPersistentDataKey &InKey) const
MOVIESCENE_API const FMovieSceneSequenceInstanceData * GetInstanceData () const
Get the raw instance data for the current sequence.
IMovieScenePlayer & GetMovieScenePlayer () const
Get the player.
template<typename T>
T & GetOrAdd (const FSharedPersistentDataKey &InKey)
User accessor functions for shared data keys.
template<typename T>
T & GetOrAddSectionData ()
User accessor functions for persistent data relating to the current section.
template<typename T>
T & GetOrAddTrackData ()
User accessor functions for persistent data relating to the current track.
template<typename T>
T & GetSectionData () const
~ Section data access is considered const as it can only ever be accessed from a single template (it can do whatever it likes with its own data)
const FMovieSceneEvaluationKey & GetSectionKey () const
Get the currently set section key (ie the section we're currently evaluating)
template<typename T>
T & GetTrackData ()
template<typename T>
T & GetTrackData () const
~ Section data access is considered const as it can only ever be accessed from a single template (it can do whatever it likes with its own data)
const FMovieSceneEvaluationKey & GetTrackKey () const
Get the currently set track key (ie the track we're currently evaluating)
FPersistentEvaluationData & operator= (const FPersistentEvaluationData &)=delete
void Reset (const FSharedPersistentDataKey &InKey)
void ResetSectionData ()
void ResetTrackData ()
void SetSectionKey (const FMovieSceneEvaluationKey &Key) const
Set the current section.
void SetTrackKey (const FMovieSceneEvaluationKey &Key) const
Set the current track.
Private Member Functions
template<typename T>
T & Add (const FMovieSceneEvaluationKey &InKey)
template<typename T>
T * Find (const FMovieSceneEvaluationKey &InKey) const
template<typename T>
T & Get (const FMovieSceneEvaluationKey &InKey) const
template<typename T>
T & GetOrAdd (const FMovieSceneEvaluationKey &InKey)
Implementation methods.
void Reset (const FMovieSceneEvaluationKey &InKey)
Private Attributes
TMap< FMovieSceneEvaluationKey, TUniquePtr< IPersistentEvaluationData > > * EntityData
Persistent data that's associated with a template entity (such as a track or a section)
IMovieScenePlayer & Player
The movie scene player.
FMovieSceneEvaluationKey SectionKey
TMap< FSharedPersistentDataKey, TUniquePtr< IPersistentEvaluationData > > * SharedData
Persistent data that's shared across multiple template entities.
FMovieSceneEvaluationKey TrackKey
Detailed Description
Structure that stores persistent data that track templates may need during evaluation.
Such data can be thought of as a cache which exists as long as the track is being evaluated. The cache can store any abstract data provided it implements IPersistentEvaluationData. Data is stored in buckets that is keyed on either the track (ie, accessible from all child templates/sections), or section (only accessible within the section) Type-safety (through the templated methods) is the responsibility of the user. There should only ever be 1 type of data for each section/track association.
Definition at line 90 of file PersistentEvaluationData.h.
Constructor & Destructor Documentation
FPersistentEvaluationData() [1/2]
MOVIESCENE_API FPersistentEvaluationData::FPersistentEvaluationData (IMovieScenePlayer & InPlayer)
Proxy constructor from 2 externally owned maps for entity, and shared data.
Referenced by FPersistentEvaluationData(), and operator=().
FPersistentEvaluationData() [2/2]
FPersistentEvaluationData::FPersistentEvaluationData (const FPersistentEvaluationData &) delete
References FPersistentEvaluationData().
Member Function Documentation
Add() [1/2]
template<typename T> T & FPersistentEvaluationData::Add (const FMovieSceneEvaluationKey & InKey) inline private
Definition at line 296 of file PersistentEvaluationData.h.
References check, EntityData, and MOVIESCENE_DETAILED_SCOPE_CYCLE_COUNTER.
Add() [2/2]
template<typename T> T & FPersistentEvaluationData::Add (const FSharedPersistentDataKey & InKey) inline
Definition at line 210 of file PersistentEvaluationData.h.
References check, MOVIESCENE_DETAILED_SCOPE_CYCLE_COUNTER, and SharedData.
AddSectionData()
template<typename T> T & FPersistentEvaluationData::AddSectionData () inline
Definition at line 117 of file PersistentEvaluationData.h.
References Add, and SectionKey.
Referenced by USTRUCT().
AddTrackData()
template<typename T> T & FPersistentEvaluationData::AddTrackData () inline
Definition at line 105 of file PersistentEvaluationData.h.
References Add, and TrackKey.
DeriveSectionKey()
const FMovieSceneEvaluationKey & FPersistentEvaluationData::DeriveSectionKey (uint32 InSectionIdentifier) const inline
Set the current section based off the current track with the specified section identifier.
Definition at line 183 of file PersistentEvaluationData.h.
References SectionKey, and TrackKey.
Find() [1/3]
template<typename T> T * FPersistentEvaluationData::Find (const FMovieSceneEvaluationKey & InKey) const inline private
Definition at line 308 of file PersistentEvaluationData.h.
References ensure, EntityData, and MOVIESCENE_DETAILED_SCOPE_CYCLE_COUNTER.
Find() [2/3]
template<typename T> T * FPersistentEvaluationData::Find (const FSharedPersistentDataKey & InKey) inline
Definition at line 222 of file PersistentEvaluationData.h.
References ensure, MOVIESCENE_DETAILED_SCOPE_CYCLE_COUNTER, and SharedData.
Find() [3/3]
template<typename T> const T * FPersistentEvaluationData::Find (const FSharedPersistentDataKey & InKey) const inline
Definition at line 235 of file PersistentEvaluationData.h.
References ensure, MOVIESCENE_DETAILED_SCOPE_CYCLE_COUNTER, and SharedData.
FindInstanceData()
template<typename T> const T * FPersistentEvaluationData::FindInstanceData () const inline
Find the current sequence's instance data as the templated type, provided its type matches.
Definition at line 136 of file PersistentEvaluationData.h.
References GetInstanceData().
FindSectionData()
template<typename T> T * FPersistentEvaluationData::FindSectionData () const inline
Definition at line 120 of file PersistentEvaluationData.h.
References Find, and SectionKey.
FindTrackData() [1/2]
template<typename T> T * FPersistentEvaluationData::FindTrackData () inline
Definition at line 107 of file PersistentEvaluationData.h.
References Find, and TrackKey.
FindTrackData() [2/2]
template<typename T> T * FPersistentEvaluationData::FindTrackData () const inline
Definition at line 110 of file PersistentEvaluationData.h.
References Find, and TrackKey.
Get() [1/3]
template<typename T> T & FPersistentEvaluationData::Get (const FMovieSceneEvaluationKey & InKey) const inline private
Definition at line 321 of file PersistentEvaluationData.h.
References check, Find, and MOVIESCENE_DETAILED_SCOPE_CYCLE_COUNTER.
Get() [2/3]
template<typename T> T & FPersistentEvaluationData::Get (const FSharedPersistentDataKey & InKey) inline
Definition at line 248 of file PersistentEvaluationData.h.
References check, Find, and MOVIESCENE_DETAILED_SCOPE_CYCLE_COUNTER.
Referenced by GetSectionData(), GetTrackData(), and GetTrackData().
Get() [3/3]
template<typename T> const T & FPersistentEvaluationData::Get (const FSharedPersistentDataKey & InKey) const inline
Definition at line 258 of file PersistentEvaluationData.h.
References check, Find, and MOVIESCENE_DETAILED_SCOPE_CYCLE_COUNTER.
GetInstanceData()
MOVIESCENE_API const FMovieSceneSequenceInstanceData * FPersistentEvaluationData::GetInstanceData () const
Get the raw instance data for the current sequence.
Referenced by FindInstanceData().
GetMovieScenePlayer()
IMovieScenePlayer & FPersistentEvaluationData::GetMovieScenePlayer () const inline
Get the player.
Definition at line 131 of file PersistentEvaluationData.h.
References Player.
GetOrAdd() [1/2]
template<typename T> T & FPersistentEvaluationData::GetOrAdd (const FMovieSceneEvaluationKey & InKey) inline private
Implementation methods.
Definition at line 281 of file PersistentEvaluationData.h.
References Add, check, EntityData, and MOVIESCENE_DETAILED_SCOPE_CYCLE_COUNTER.
GetOrAdd() [2/2]
template<typename T> T & FPersistentEvaluationData::GetOrAdd (const FSharedPersistentDataKey & InKey) inline
User accessor functions for shared data keys.
Definition at line 195 of file PersistentEvaluationData.h.
References Add, check, MOVIESCENE_DETAILED_SCOPE_CYCLE_COUNTER, and SharedData.
Referenced by GetOrAddSectionData(), and GetOrAddTrackData().
GetOrAddSectionData()
template<typename T> T & FPersistentEvaluationData::GetOrAddSectionData () inline
User accessor functions for persistent data relating to the current section.
Definition at line 116 of file PersistentEvaluationData.h.
References GetOrAdd(), and SectionKey.
GetOrAddTrackData()
template<typename T> T & FPersistentEvaluationData::GetOrAddTrackData () inline
User accessor functions for persistent data relating to the current track.
Definition at line 104 of file PersistentEvaluationData.h.
References GetOrAdd(), and TrackKey.
GetSectionData()
template<typename T> T & FPersistentEvaluationData::GetSectionData () const inline
~ Section data access is considered const as it can only ever be accessed from a single template (it can do whatever it likes with its own data)
Definition at line 119 of file PersistentEvaluationData.h.
References Get(), and SectionKey.
Referenced by TPropertyTrackExecutionToken< PropertyValueType, IntermediateType >::Execute().
GetSectionKey()
const FMovieSceneEvaluationKey & FPersistentEvaluationData::GetSectionKey () const inline
Get the currently set section key (ie the section we're currently evaluating)
Definition at line 159 of file PersistentEvaluationData.h.
References SectionKey.
GetTrackData() [1/2]
template<typename T> T & FPersistentEvaluationData::GetTrackData () inline
Definition at line 106 of file PersistentEvaluationData.h.
References Get(), and TrackKey.
GetTrackData() [2/2]
template<typename T> T & FPersistentEvaluationData::GetTrackData () const inline
~ Section data access is considered const as it can only ever be accessed from a single template (it can do whatever it likes with its own data)
Definition at line 109 of file PersistentEvaluationData.h.
References Get(), and TrackKey.
GetTrackKey()
const FMovieSceneEvaluationKey & FPersistentEvaluationData::GetTrackKey () const inline
Get the currently set track key (ie the track we're currently evaluating)
Definition at line 151 of file PersistentEvaluationData.h.
References TrackKey.
operator=()
FPersistentEvaluationData & FPersistentEvaluationData::operator= (const FPersistentEvaluationData &) delete
References FPersistentEvaluationData().
Reset() [1/2]
void FPersistentEvaluationData::Reset (const FMovieSceneEvaluationKey & InKey) inline private
Definition at line 330 of file PersistentEvaluationData.h.
References ensure, EntityData, and MOVIESCENE_DETAILED_SCOPE_CYCLE_COUNTER.
Reset() [2/2]
void FPersistentEvaluationData::Reset (const FSharedPersistentDataKey & InKey) inline
Definition at line 267 of file PersistentEvaluationData.h.
References ensure, MOVIESCENE_DETAILED_SCOPE_CYCLE_COUNTER, and SharedData.
ResetSectionData()
void FPersistentEvaluationData::ResetSectionData () inline
Definition at line 121 of file PersistentEvaluationData.h.
References Reset, and SectionKey.
ResetTrackData()
void FPersistentEvaluationData::ResetTrackData () inline
Definition at line 111 of file PersistentEvaluationData.h.
References Reset, and TrackKey.
SetSectionKey()
void FPersistentEvaluationData::SetSectionKey (const FMovieSceneEvaluationKey & Key) const inline
Set the current section.
Definition at line 175 of file PersistentEvaluationData.h.
References Key, and SectionKey.
SetTrackKey()
void FPersistentEvaluationData::SetTrackKey (const FMovieSceneEvaluationKey & Key) const inline
Set the current track.
Definition at line 167 of file PersistentEvaluationData.h.
References Key, and TrackKey.
Field Documentation
EntityData
TMap<FMovieSceneEvaluationKey, TUniquePtr<IPersistentEvaluationData> >* FPersistentEvaluationData::EntityData private
Persistent data that's associated with a template entity (such as a track or a section)
Definition at line 346 of file PersistentEvaluationData.h.
Referenced by Add(), Find(), GetOrAdd(), and Reset().
Player
IMovieScenePlayer& FPersistentEvaluationData::Player private
The movie scene player.
Definition at line 343 of file PersistentEvaluationData.h.
Referenced by GetMovieScenePlayer().
SectionKey
FMovieSceneEvaluationKey FPersistentEvaluationData::SectionKey mutable private
Definition at line 354 of file PersistentEvaluationData.h.
Referenced by AddSectionData(), DeriveSectionKey(), FindSectionData(), GetOrAddSectionData(), GetSectionData(), GetSectionKey(), ResetSectionData(), and SetSectionKey().
SharedData
TMap<FSharedPersistentDataKey, TUniquePtr<IPersistentEvaluationData> >* FPersistentEvaluationData::SharedData private
Persistent data that's shared across multiple template entities.
Definition at line 349 of file PersistentEvaluationData.h.
Referenced by Add(), Find(), Find(), GetOrAdd(), and Reset().
TrackKey
FMovieSceneEvaluationKey FPersistentEvaluationData::TrackKey mutable private
Definition at line 353 of file PersistentEvaluationData.h.
Referenced by AddTrackData(), DeriveSectionKey(), FindTrackData(), FindTrackData(), GetOrAddTrackData(), GetTrackData(), GetTrackData(), GetTrackKey(), ResetTrackData(), and SetTrackKey().
The documentation for this struct was generated from the following file:
Runtime/MovieScene/Public/Evaluation/PersistentEvaluationData.h