Unreal Engine 5.6 C++ API: FAutoRegisterLocalizationDataGatheringCallback Struct Reference
FAutoRegisterLocalizationDataGatheringCallback Struct Reference
Struct to automatically register a callback when it's constructed.
#include "PropertyLocalizationDataGathering.h"
Public Member Functions
FORCEINLINE FAutoRegisterLocalizationDataGatheringCallback (const UClass *InClass, const FPropertyLocalizationDataGatherer::FLocalizationDataObjectGatheringCallback &InCallback)
FORCEINLINE FAutoRegisterLocalizationDataGatheringCallback (const UScriptStruct *InStruct, const FPropertyLocalizationDataGatherer::FLocalizationDataStructGatheringCallback &InCallback)
Detailed Description
Struct to automatically register a callback when it's constructed.
Definition at line 207 of file PropertyLocalizationDataGathering.h.
Constructor & Destructor Documentation
FAutoRegisterLocalizationDataGatheringCallback() [1/2]
FORCEINLINE FAutoRegisterLocalizationDataGatheringCallback::FAutoRegisterLocalizationDataGatheringCallback (const UClass * InClass, const FPropertyLocalizationDataGatherer::FLocalizationDataObjectGatheringCallback & InCallback) inline
Definition at line 209 of file PropertyLocalizationDataGathering.h.
References TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Add(), FORCEINLINE, and FPropertyLocalizationDataGatherer::GetTypeSpecificLocalizationDataObjectGatheringCallbacks().
FAutoRegisterLocalizationDataGatheringCallback() [2/2]
FORCEINLINE FAutoRegisterLocalizationDataGatheringCallback::FAutoRegisterLocalizationDataGatheringCallback (const UScriptStruct * InStruct, const FPropertyLocalizationDataGatherer::FLocalizationDataStructGatheringCallback & InCallback) inline
Definition at line 214 of file PropertyLocalizationDataGathering.h.
References TMapBase< KeyType, ValueType, SetAllocator, KeyFuncs >::Add(), FORCEINLINE, and FPropertyLocalizationDataGatherer::GetTypeSpecificLocalizationDataStructGatheringCallbacks().
The documentation for this struct was generated from the following file:
Runtime/CoreUObject/Public/Serialization/PropertyLocalizationDataGathering.h