Unreal Engine 5.6 C++ API: FRigVMExplorerElementKey Struct Reference
FRigVMExplorerElementKey Struct Reference
#include "SRigVMEditorGraphExplorerTreeView.h"
Public Member Functions
FRigVMExplorerElementKey ()
FRigVMExplorerElementKey (const ERigVMExplorerElementType::Type &InType, const FString &InName)
Data Fields
FString Name
ERigVMExplorerElementType::Type Type
Friends
uint32 GetTypeHash (const FRigVMExplorerElementKey &Key)
bool operator== (const FRigVMExplorerElementKey &A, const FRigVMExplorerElementKey &B)
Detailed Description
Definition at line 34 of file SRigVMEditorGraphExplorerTreeView.h.
Constructor & Destructor Documentation
FRigVMExplorerElementKey() [1/2]
FRigVMExplorerElementKey::FRigVMExplorerElementKey () inline
Definition at line 37 of file SRigVMEditorGraphExplorerTreeView.h.
References Invalid, Name, and Type.
Referenced by GetTypeHash, and operator==.
FRigVMExplorerElementKey() [2/2]
FRigVMExplorerElementKey::FRigVMExplorerElementKey (const ERigVMExplorerElementType::Type & InType, const FString & InName) inline
Definition at line 40 of file SRigVMEditorGraphExplorerTreeView.h.
References InName, Name, and Type.
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FRigVMExplorerElementKey & Key) friend
Definition at line 51 of file SRigVMEditorGraphExplorerTreeView.h.
References FRigVMExplorerElementKey(), GetTypeHash, HashCombine(), and Key.
Referenced by GetTypeHash.
operator==
bool operator== (const FRigVMExplorerElementKey & A, const FRigVMExplorerElementKey & B) friend
Definition at line 46 of file SRigVMEditorGraphExplorerTreeView.h.
References FRigVMExplorerElementKey(), A, and B.
Field Documentation
Name
FString FRigVMExplorerElementKey::Name
Definition at line 44 of file SRigVMEditorGraphExplorerTreeView.h.
Referenced by FRigVMExplorerElementKey(), and FRigVMExplorerElementKey().
Type
ERigVMExplorerElementType::Type FRigVMExplorerElementKey::Type
Definition at line 43 of file SRigVMEditorGraphExplorerTreeView.h.
Referenced by FRigVMExplorerElementKey(), and FRigVMExplorerElementKey().
The documentation for this struct was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/RigVM/Source/RigVMEditor/Public/Widgets/SRigVMEditorGraphExplorerTreeView.h