Unreal Engine 5.6 C++ API: FMovieSceneBlendChannelID Struct Reference
FMovieSceneBlendChannelID Struct Reference
A blend channel ID.
#include "MovieSceneBlenderSystemTypes.h"
Public Member Functions
FMovieSceneBlendChannelID ()
Builds a default, invalid channel ID.
FMovieSceneBlendChannelID (FMovieSceneBlenderSystemID InSystemID, uint16 InChannelID)
Builds a channel ID.
MOVIESCENE_API UMovieSceneBlenderSystem * FindSystem (const UMovieSceneEntitySystemLinker *Linker) const
Returns the blender system instance found in a given linker.
template<typename BlenderSystemClass>
BlenderSystemClass * FindSystem (const UMovieSceneEntitySystemLinker *Linker) const
Returns the blender system instance found in a given linker.
MOVIESCENE_API TSubclassOf< UMovieSceneBlenderSystem > GetSystemClass () const
Returns the blender system type.
bool IsValid () const
Returns whether this ID is valid.
Data Fields
uint16 ChannelID
The blend channel ID for the given blender system.
FMovieSceneBlenderSystemID SystemID
The blender system associated with the blend channel.
Static Public Attributes
static constexpr uint16 INVALID_BLEND_CHANNEL = uint16(-1)
Invalid blend channel ID.
Friends
uint32 GetTypeHash (const FMovieSceneBlendChannelID A)
bool operator== (const FMovieSceneBlendChannelID A, const FMovieSceneBlendChannelID B)
Detailed Description
A blend channel ID.
Definition at line 50 of file MovieSceneBlenderSystemTypes.h.
Constructor & Destructor Documentation
FMovieSceneBlendChannelID() [1/2]
FMovieSceneBlendChannelID::FMovieSceneBlendChannelID () inline
Builds a default, invalid channel ID.
Definition at line 56 of file MovieSceneBlenderSystemTypes.h.
References ChannelID, and INVALID_BLEND_CHANNEL.
Referenced by GetTypeHash, and operator==.
FMovieSceneBlendChannelID() [2/2]
FMovieSceneBlendChannelID::FMovieSceneBlendChannelID (FMovieSceneBlenderSystemID InSystemID, uint16 InChannelID) inline
Builds a channel ID.
Definition at line 58 of file MovieSceneBlenderSystemTypes.h.
References ChannelID, and SystemID.
Member Function Documentation
FindSystem() [1/2]
MOVIESCENE_API UMovieSceneBlenderSystem * FMovieSceneBlendChannelID::FindSystem (const UMovieSceneEntitySystemLinker * Linker) const
Returns the blender system instance found in a given linker.
Referenced by FindSystem().
FindSystem() [2/2]
template<typename BlenderSystemClass> BlenderSystemClass * FMovieSceneBlendChannelID::FindSystem (const UMovieSceneEntitySystemLinker * Linker) const inline
Returns the blender system instance found in a given linker.
Definition at line 71 of file MovieSceneBlenderSystemTypes.h.
References CastChecked(), and FindSystem().
GetSystemClass()
MOVIESCENE_API TSubclassOf< UMovieSceneBlenderSystem > FMovieSceneBlendChannelID::GetSystemClass () const
Returns the blender system type.
IsValid()
bool FMovieSceneBlendChannelID::IsValid () const inline
Returns whether this ID is valid.
Definition at line 61 of file MovieSceneBlenderSystemTypes.h.
References ChannelID, and INVALID_BLEND_CHANNEL.
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FMovieSceneBlendChannelID A) friend
Definition at line 81 of file MovieSceneBlenderSystemTypes.h.
References FMovieSceneBlendChannelID(), A, GetTypeHash, and HashCombine().
Referenced by GetTypeHash.
operator==
bool operator== (const FMovieSceneBlendChannelID A, const FMovieSceneBlendChannelID B) friend
Definition at line 76 of file MovieSceneBlenderSystemTypes.h.
References FMovieSceneBlendChannelID(), A, and B.
Field Documentation
ChannelID
uint16 FMovieSceneBlendChannelID::ChannelID
The blend channel ID for the given blender system.
Definition at line 90 of file MovieSceneBlenderSystemTypes.h.
Referenced by FMovieSceneBlendChannelID(), FMovieSceneBlendChannelID(), UE::MovieScene::TSimpleBlenderCombineResults< PropertyType, ResultTraits >::ForEachEntity(), UE::MovieScene::TSimpleBlenderGatherResults< PropertyType, ResultTraits >::ForEachEntity(), and IsValid().
INVALID_BLEND_CHANNEL
uint16 FMovieSceneBlendChannelID::INVALID_BLEND_CHANNEL = uint16(-1) static constexpr
Invalid blend channel ID.
Definition at line 53 of file MovieSceneBlenderSystemTypes.h.
Referenced by FMovieSceneBlendChannelID(), and IsValid().
SystemID
FMovieSceneBlenderSystemID FMovieSceneBlendChannelID::SystemID
The blender system associated with the blend channel.
Definition at line 87 of file MovieSceneBlenderSystemTypes.h.
Referenced by FMovieSceneBlendChannelID(), UE::MovieScene::TSimpleBlenderCombineResults< PropertyType, ResultTraits >::ForEachEntity(), and UE::MovieScene::TSimpleBlenderGatherResults< PropertyType, ResultTraits >::ForEachEntity().
The documentation for this struct was generated from the following file:
Runtime/MovieScene/Public/EntitySystem/MovieSceneBlenderSystemTypes.h