Unreal Engine 5.6 C++ API: FFunctionGraphTask Struct Reference
FFunctionGraphTask Struct Reference
#include "TaskGraphInterfaces.h"
Static Public Member Functions
static FGraphEventRef CreateAndDispatchWhenReady (TUniqueFunction< void()> InFunction, TStatId InStatId, const FGraphEventRef &InPrerequisite, ENamedThreads::Type InDesiredThread=ENamedThreads::AnyThread)
Create a task and dispatch it when the prerequisites are complete.
static FGraphEventRef CreateAndDispatchWhenReady (TUniqueFunction< void()> InFunction, TStatId InStatId=TStatId{}, const FGraphEventArray *InPrerequisites=nullptr, ENamedThreads::Type InDesiredThread=ENamedThreads::AnyThread)
Create a task and dispatch it when the prerequisites are complete.
static FGraphEventRef CreateAndDispatchWhenReady (TUniqueFunction< void(ENamedThreads::Type, const FGraphEventRef &)> InFunction, TStatId InStatId, const FGraphEventRef &InPrerequisite, ENamedThreads::Type InDesiredThread=ENamedThreads::AnyThread)
static FGraphEventRef CreateAndDispatchWhenReady (TUniqueFunction< void(ENamedThreads::Type, const FGraphEventRef &)> InFunction, TStatId InStatId=TStatId{}, const FGraphEventArray *InPrerequisites=nullptr, ENamedThreads::Type InDesiredThread=ENamedThreads::AnyThread)
Detailed Description
Definition at line 1127 of file TaskGraphInterfaces.h.
Member Function Documentation
CreateAndDispatchWhenReady() [1/4]
FGraphEventRef FFunctionGraphTask::CreateAndDispatchWhenReady (TUniqueFunction< void()> InFunction, TStatId InStatId, const FGraphEventRef & InPrerequisite, ENamedThreads::Type InDesiredThread = ENamedThreads::AnyThread) inline static
Create a task and dispatch it when the prerequisites are complete.
Parameters
InFunction - a function to execute when the prerequisites are complete, with signature void() or void(ENamedThreads::Type, const FGraphEventRef&)
InStatId - StatId of task for debugging or analysis tools
InPrerequisite - Handle for a single prerequisite for this task
InDesiredThread - Thread to run on
Returns
completion handle for the new task
Definition at line 1156 of file TaskGraphInterfaces.h.
References ENamedThreads::AnyThread, check, CreateAndDispatchWhenReady(), TRefCountPtr< ReferencedType >::GetReference(), and MoveTemp().
CreateAndDispatchWhenReady() [2/4]
FGraphEventRef FFunctionGraphTask::CreateAndDispatchWhenReady (TUniqueFunction< void()> InFunction, TStatId InStatId = TStatId{}, const FGraphEventArray * InPrerequisites = nullptr, ENamedThreads::Type InDesiredThread = ENamedThreads::AnyThread) inline static
Create a task and dispatch it when the prerequisites are complete.
Parameters
InFunction - a functor object to execute when the prerequisites are complete, with signature void() or void(ENamedThreads::Type, const FGraphEventRef&)
InStatId - StatId of task for debugging or analysis tools
InPrerequisites - Handles for prerequisites for this task, can be NULL if there are no prerequisites
InDesiredThread - Thread to run on
Returns
completion handle for the new task
Definition at line 1138 of file TaskGraphInterfaces.h.
Referenced by FQueuedThreadPoolTaskGraphWrapper::AddQueuedWork(), CreateAndDispatchWhenReady(), and CreateAndDispatchWhenReady().
CreateAndDispatchWhenReady() [3/4]
FGraphEventRef FFunctionGraphTask::CreateAndDispatchWhenReady (TUniqueFunction< void(ENamedThreads::Type, const FGraphEventRef &)> InFunction, TStatId InStatId, const FGraphEventRef & InPrerequisite, ENamedThreads::Type InDesiredThread = ENamedThreads::AnyThread) inline static
Definition at line 1164 of file TaskGraphInterfaces.h.
References ENamedThreads::AnyThread, check, CreateAndDispatchWhenReady(), TRefCountPtr< ReferencedType >::GetReference(), and MoveTemp().
CreateAndDispatchWhenReady() [4/4]
FGraphEventRef FFunctionGraphTask::CreateAndDispatchWhenReady (TUniqueFunction< void(ENamedThreads::Type, const FGraphEventRef &)> InFunction, TStatId InStatId = TStatId{}, const FGraphEventArray * InPrerequisites = nullptr, ENamedThreads::Type InDesiredThread = ENamedThreads::AnyThread) inline static
Definition at line 1143 of file TaskGraphInterfaces.h.
The documentation for this struct was generated from the following file:
Runtime/Core/Public/Async/TaskGraphInterfaces.h