Unreal Engine 5.6 C++ API: FStructTracker Struct Reference
FStructTracker Struct Reference
FStructTracker is a utility class used to track and map UStruct types to indices, which are used in bitsets.
#include "StructTypeBitSet.h"
Public Types
using FBaseStructGetter = TFunction<UStruct*()>
using FTypeValidation = TFunction<bool(const UStruct*)>
Public Member Functions
FStructTracker (const FBaseStructGetter &InBaseStructGetter)
The input parameter is a function that fetches the UStruct representing the base class for all the stored structs.
FStructTracker (const UStruct *InBaseType, const FTypeValidation &InTypeVerification=FTypeValidation())
~FStructTracker ()
int32 FindOrAddStructTypeIndex (const UStruct &InStructType)
Fetches the internal index representing the given UStruct instance.
int32 FindStructTypeIndex (const UStruct &InStructType) const
const UStruct * GetBaseType () const
Retrieves the base UStruct type used for validation.
const UStruct * GetStructType (const int32 StructTypeIndex) const
Retrieves the UStruct type associated with a given index.
int32 Num () const
Gets the number of registered struct types.
int32 Register (const UStruct &InStructType)
Registers the given UStruct with the struct tracker.
void Serialize (FArchive &Ar, FStructTypeBitSet::FBitSetContainer &StructTypesBitArray)
Serializes the struct types bit array using the archive provided.
UE_NONCOPYABLE (FStructTracker)
Protected Member Functions
int32 RegisterImplementation (const UStruct &InStructType, const bool bCheckPrevious)
Protected Attributes
const FBaseStructGetter BaseStructGetter
Function to retrieve the base UStruct.
uint32 bIsSerializable: 1 = true
Flag indicating whether this tracker is serializable.
uint32 SerializationHash = 0
Hash used during serialization to detect mismatches.
TArray< TWeakObjectPtr< const UStruct >, TInlineAllocator< 64 > > StructTypesList
List of weak pointers to struct types, indexed by their assigned indices.
TSet< uint32 > StructTypeToIndexSet
Set mapping struct type hashes to their indices.
const FTypeValidation TypeVerification
Function to perform additional type verification.
Private Attributes
const UStruct * BaseType
Detailed Description
FStructTracker is a utility class used to track and map UStruct types to indices, which are used in bitsets.
It manages a mapping between UStruct instances and integer indices, allowing for efficient storage and querying of types in a bitset
The FStructTracker assigns an index to a given type the first time it encounters it
Definition at line 273 of file StructTypeBitSet.h.
Member Typedef Documentation
FBaseStructGetter
using FStructTracker::FBaseStructGetter = TFunction<UStruct*()>
Definition at line 275 of file StructTypeBitSet.h.
FTypeValidation
using FStructTracker::FTypeValidation = TFunction<bool(const UStruct*)>
Definition at line 276 of file StructTypeBitSet.h.
Constructor & Destructor Documentation
FStructTracker() [1/2]
FStructTracker::FStructTracker (const FBaseStructGetter & InBaseStructGetter) explicit
The input parameter is a function that fetches the UStruct representing the base class for all the stored structs.
We're unable to get the UStruct parameter directly since FStructTracker instances are being created during module loading (via DEFINE_TYPEBITSET macro), and the StaticStruct call fails at that point for types defined in the same module.
References UE_API.
Referenced by UE_NONCOPYABLE().
FStructTracker() [2/2]
FStructTracker::FStructTracker (const UStruct * InBaseType, const FTypeValidation & InTypeVerification = FTypeValidation()) explicit
References UE_API.
~FStructTracker()
FStructTracker::~FStructTracker ()
References UE_API.
Member Function Documentation
FindOrAddStructTypeIndex()
int32 FStructTracker::FindOrAddStructTypeIndex (const UStruct & InStructType)
Fetches the internal index representing the given UStruct instance.
If it hasn't been registered yet, it will be automatically added.
Returns
the index for the given type.
References UE_API.
FindStructTypeIndex()
int32 FStructTracker::FindStructTypeIndex (const UStruct & InStructType) const
Returns
the index for the given type, or INDEX_NONE if it hasn't been registered with this struct tracker
References UE_API.
GetBaseType()
const UStruct * FStructTracker::GetBaseType () const
Retrieves the base UStruct type used for validation.
Returns
Pointer to the base UStruct.
References UE_API.
GetStructType()
const UStruct * FStructTracker::GetStructType (const int32 StructTypeIndex) const inline
Retrieves the UStruct type associated with a given index.
Parameters
StructTypeIndex - The index of the struct type
Returns
Pointer to the UStruct if found, nullptr otherwise
Definition at line 315 of file StructTypeBitSet.h.
References StructTypesList.
Num()
int32 FStructTracker::Num () const inline
Gets the number of registered struct types.
Returns
Number of struct types.
Definition at line 330 of file StructTypeBitSet.h.
References StructTypeToIndexSet.
Register()
int32 FStructTracker::Register (const UStruct & InStructType) inline
Registers the given UStruct with the struct tracker.
Returns
the index for the registered type.
Definition at line 305 of file StructTypeBitSet.h.
References RegisterImplementation().
RegisterImplementation()
int32 FStructTracker::RegisterImplementation (const UStruct & InStructType, const bool bCheckPrevious) protected
References UE_API.
Referenced by Register().
Serialize()
void FStructTracker::Serialize (FArchive & Ar, FStructTypeBitSet::FBitSetContainer & StructTypesBitArray)
Serializes the struct types bit array using the archive provided.
Parameters
Ar - The archive to serialize with.
StructTypesBitArray - The bit array representing struct types.
References Ar, and UE_API.
UE_NONCOPYABLE()
FStructTracker::UE_NONCOPYABLE (FStructTracker)
References FStructTracker().
Field Documentation
BaseStructGetter
const FBaseStructGetter FStructTracker::BaseStructGetter protected
Function to retrieve the base UStruct.
Definition at line 382 of file StructTypeBitSet.h.
BaseType
const UStruct* FStructTracker::BaseType mutable private
Definition at line 387 of file StructTypeBitSet.h.
bIsSerializable
uint32 FStructTracker::bIsSerializable protected
Flag indicating whether this tracker is serializable.
Definition at line 380 of file StructTypeBitSet.h.
SerializationHash
uint32 FStructTracker::SerializationHash = 0 protected
Hash used during serialization to detect mismatches.
Definition at line 378 of file StructTypeBitSet.h.
StructTypesList
TArray<TWeakObjectPtr<const UStruct>, TInlineAllocator<64> > FStructTracker::StructTypesList protected
List of weak pointers to struct types, indexed by their assigned indices.
Definition at line 376 of file StructTypeBitSet.h.
Referenced by GetStructType().
StructTypeToIndexSet
TSet<uint32> FStructTracker::StructTypeToIndexSet protected
Set mapping struct type hashes to their indices.
Definition at line 374 of file StructTypeBitSet.h.
Referenced by Num().
TypeVerification
const FTypeValidation FStructTracker::TypeVerification protected
Function to perform additional type verification.
Definition at line 384 of file StructTypeBitSet.h.
The documentation for this struct was generated from the following file:
Runtime/CoreUObject/Public/StructUtils/StructTypeBitSet.h