Unreal Engine 5.6 C++ API: UE::Geometry::TSegment2< T > Struct Template Reference
UE::Geometry::TSegment2< T > Struct Template Reference
#include "SegmentTypes.h"
Public Member Functions
TSegment2 ()=default
TSegment2 (const TVector2< T > &CenterIn, const TVector2< T > &DirectionIn, T ExtentIn)
Construct a segment from a Center Point, normalized Direction, and scalar Extent.
TSegment2 (const TVector2< T > &Point0, const TVector2< T > &Point1)
Construct a Segment from two Points.
T ConvertToUnitRange (T DistanceParameter) const
T DistanceSquared (const TVector2< T > &Point) const
T DistanceSquared (const TVector2< T > &Point, T &DistParameterOut) const
TVector2< T > EndPoint () const
TVector2< T > GetPointFromIndex (int i) const
int GetSide (const TVector2< T > &QueryPoint, T Tolerance=0)
Determine which side of the segment the query point lies on.
T Length () const
TVector2< T > NearestPoint (const TVector2< T > &QueryPoint) const
TVector2< T > PointAt (T DistanceParameter) const
TVector2< T > PointBetween (T UnitParameter) const
T Project (const TVector2< T > &QueryPoint) const
T ProjectUnitRange (const TVector2< T > &QueryPoint) const
void Reverse ()
Reverse the segment.
void SetEndPoint (const TVector2< T > &Point)
Update the Segment with a new end point.
void SetStartPoint (const TVector2< T > &Point)
Update the Segment with a new start point.
TVector2< T > StartPoint () const
UE_DEPRECATED (5.5, "Use GetSide instead.") int WhichSide(const TVector2< T > &QueryPoint
Determine which side of the segment the query point lies on.
Data Fields
TVector2< T > Center = TVector2<T>::Zero()
Center point of segment.
TVector2< T > Direction = TVector2<T>::UnitX()
normalized Direction vector of segment
T Extent = (T)0
Extent of segment, which is half the total length.
Detailed Description
template<typename T>
struct UE::Geometry::TSegment2< T >
Definition at line 22 of file SegmentTypes.h.
Constructor & Destructor Documentation
TSegment2() [1/3]
template<typename T> UE::Geometry::TSegment2< T >::TSegment2 () default
TSegment2() [2/3]
template<typename T> UE::Geometry::TSegment2< T >::TSegment2 (const TVector2< T > & Point0, const TVector2< T > & Point1) inline
Construct a Segment from two Points.
Definition at line 37 of file SegmentTypes.h.
TSegment2() [3/3]
template<typename T> UE::Geometry::TSegment2< T >::TSegment2 (const TVector2< T > & CenterIn, const TVector2< T > & DirectionIn, T ExtentIn) inline
Construct a segment from a Center Point, normalized Direction, and scalar Extent.
Definition at line 48 of file SegmentTypes.h.
Member Function Documentation
ConvertToUnitRange()
template<typename T> T UE::Geometry::TSegment2< T >::ConvertToUnitRange (T DistanceParameter) const inline
Parameters
DistanceParameter distance on the segment from the segment Origin in range [-Extent, Extent]
Returns
unit value in range [0,1]
Definition at line 124 of file SegmentTypes.h.
DistanceSquared() [1/2]
template<typename T> T UE::Geometry::TSegment2< T >::DistanceSquared (const TVector2< T > & Point) const inline
Returns
minimum squared distance from Point to segment
Definition at line 132 of file SegmentTypes.h.
Referenced by UE::Geometry::TSegment2< FVector::FReal >::DistanceSquared(), UE::Geometry::FArrangement2d::find_intersecting_floating_vertices(), UE::Geometry::FArrangement2d::insert_point(), and UE::Geometry::TPolygon2< double >::SimplifyDouglasPeucker().
DistanceSquared() [2/2]
template<typename T> T UE::Geometry::TSegment2< T >::DistanceSquared (const TVector2< T > & Point, T & DistParameterOut) const inline
Parameters
Point query point
DistParameterOut calculated distance parameter in range [-Extent,Extent]
Returns
minimum squared distance from Point to Segment
Definition at line 145 of file SegmentTypes.h.
EndPoint()
template<typename T> TVector2< T > UE::Geometry::TSegment2< T >::EndPoint () const inline
Returns
end point of segment
Definition at line 85 of file SegmentTypes.h.
Referenced by UE::Geometry::TPolygon2< double >::DistanceSquared(), UE::Geometry::TSegment2< FVector::FReal >::DistanceSquared(), UE::Geometry::TSegment2< FVector::FReal >::NearestPoint(), UE::Geometry::TSegment2< FVector::FReal >::Reverse(), and UE::Geometry::TSegment2< FVector::FReal >::SetStartPoint().
GetPointFromIndex()
template<typename T> TVector2< T > UE::Geometry::TSegment2< T >::GetPointFromIndex (int i) const inline
Returns
first (i == 0) or second (i == 1) endpoint of the Segment
Definition at line 98 of file SegmentTypes.h.
GetSide()
template<typename T> int UE::Geometry::TSegment2< T >::GetSide (const TVector2< T > & QueryPoint, T Tolerance = 0) inline
Determine which side of the segment the query point lies on.
Parameters
QueryPoint test point
Tolerance tolerance band in which we return 0
Returns
-1 if point is to right of line, +1 if left, and 0 if on line or within tolerance band
Definition at line 206 of file SegmentTypes.h.
Referenced by UE::Geometry::TTriangle2< float >::IsInsideOrOn(), and UE::Geometry::TTriangle2< float >::IsInsideOrOn_Oriented().
Length()
template<typename T> T UE::Geometry::TSegment2< T >::Length () const inline
Returns
the Length of the segment
Definition at line 92 of file SegmentTypes.h.
NearestPoint()
template<typename T> TVector2< T > UE::Geometry::TSegment2< T >::NearestPoint (const TVector2< T > & QueryPoint) const inline
Returns
nearest point on segment to QueryPoint
Definition at line 166 of file SegmentTypes.h.
PointAt()
template<typename T> TVector2< T > UE::Geometry::TSegment2< T >::PointAt (T DistanceParameter) const inline
Returns
point on segment at given (signed) Distance from the segment Origin
Definition at line 106 of file SegmentTypes.h.
Referenced by UE::Geometry::TPolygon2< double >::DistanceSquared(), UE::Geometry::TPolygon2< double >::GetSegmentPoint(), UE::Geometry::FArrangement2d::insert_segment(), and UE::Geometry::FArrangement2d::split_segment_at_t().
PointBetween()
template<typename T> TVector2< T > UE::Geometry::TSegment2< T >::PointBetween (T UnitParameter) const inline
Parameters
UnitParameter value in range [0,1]
Returns
point on segment at that linearly interpolates between start and end based on Unit Parameter
Definition at line 115 of file SegmentTypes.h.
Referenced by UE::Geometry::TPolygon2< double >::GetSegmentPointUnitParam().
Project()
template<typename T> T UE::Geometry::TSegment2< T >::Project (const TVector2< T > & QueryPoint) const inline
Returns
scalar projection of QueryPoint onto line of Segment (not clamped to Extents)
Definition at line 184 of file SegmentTypes.h.
Referenced by UE::Geometry::FArrangement2d::insert_segment().
ProjectUnitRange()
template<typename T> T UE::Geometry::TSegment2< T >::ProjectUnitRange (const TVector2< T > & QueryPoint) const inline
Returns
scalar projection of QueryPoint onto line of Segment, mapped to [0,1] range along segment
Definition at line 193 of file SegmentTypes.h.
Reverse()
template<typename T> void UE::Geometry::TSegment2< T >::Reverse () inline
Reverse the segment.
Definition at line 70 of file SegmentTypes.h.
SetEndPoint()
template<typename T> void UE::Geometry::TSegment2< T >::SetEndPoint (const TVector2< T > & Point) inline
Update the Segment with a new end point.
Definition at line 64 of file SegmentTypes.h.
SetStartPoint()
template<typename T> void UE::Geometry::TSegment2< T >::SetStartPoint (const TVector2< T > & Point) inline
Update the Segment with a new start point.
Definition at line 58 of file SegmentTypes.h.
StartPoint()
template<typename T> TVector2< T > UE::Geometry::TSegment2< T >::StartPoint () const inline
Returns
start point of segment
Definition at line 79 of file SegmentTypes.h.
Referenced by UE::Geometry::TPolygon2< double >::DistanceSquared(), UE::Geometry::TSegment2< FVector::FReal >::DistanceSquared(), UE::Geometry::TSegment2< FVector::FReal >::NearestPoint(), UE::Geometry::TSegment2< FVector::FReal >::Reverse(), and UE::Geometry::TSegment2< FVector::FReal >::SetEndPoint().
UE_DEPRECATED()
template<typename T> UE::Geometry::TSegment2< T >::UE_DEPRECATED (5. 5, "Use GetSide instead.") const &
Determine which side of the segment the query point lies on.
This version is deprecated because it and the static function give opposite results. It also does not correctly handle tolerance.
Parameters
QueryPoint test point
Tolerance tolerance band in which we return 0
Returns
-1 if point is to right of line, +1 if left, and 0 if on line or within tolerance band
Field Documentation
Center
template<typename T> TVector2<T> UE::Geometry::TSegment2< T >::Center = TVector2<T>::Zero()
Center point of segment.
Definition at line 26 of file SegmentTypes.h.
Referenced by UE::Geometry::TPolygon2< double >::DistanceSquared().
Direction
template<typename T> TVector2<T> UE::Geometry::TSegment2< T >::Direction = TVector2<T>::UnitX()
normalized Direction vector of segment
Definition at line 28 of file SegmentTypes.h.
Referenced by UE::Geometry::TPolygon2< double >::DistanceSquared().
Extent
template<typename T> T UE::Geometry::TSegment2< T >::Extent = (T)0
Extent of segment, which is half the total length.
Definition at line 30 of file SegmentTypes.h.
Referenced by UE::Geometry::TPolygon2< double >::DistanceSquared(), UE::Geometry::TPolygon2< double >::GetNormal(), UE::Geometry::FArrangement2d::insert_segment(), and UE::Geometry::FArrangement2d::split_segment_at_t().
The documentation for this struct was generated from the following files:
Runtime/GeometryCore/Public/Intersection/IntersectionQueries2.h
Runtime/GeometryCore/Public/SegmentTypes.h