Unreal Engine 5.6 C++ API: UE::Math::TIntRect< InIntType > Struct Template Reference
UE::Math::TIntRect< InIntType > Struct Template Reference
Structure for integer rectangles in 2-d space.
#include "IntRect.h"
Public Types
using IntPointType = TIntPoint<IntType>
using IntType = InIntType
Public Member Functions
TIntRect ()
Constructor.
TIntRect (const TIntRect &Other)
TIntRect (IntPointType InMin, IntPointType InMax)
Constructor.
TIntRect (IntType X0, IntType Y0, IntType X1, IntType Y1)
Constructor.
template<typename OtherIntType>
TIntRect (TIntRect< OtherIntType > Other)
Converts to another int type.
IntType Area () const
Calculates the area of this rectangle.
TIntRect Bottom (IntType InHeight) const
Creates a rectangle from the bottom part of this rectangle.
void Clip (const TIntRect &R)
Clip a rectangle using the bounds of another rectangle.
bool Contains (IntPointType P) const
Test whether this rectangle contains a point.
void GetCenterAndExtents (IntPointType &OutCenter, IntPointType &OutExtent) const
Gets the Center and Extents of this rectangle.
IntType Height () const
Gets the Height of the rectangle.
void Include (IntPointType Point)
Adds to this rectangle to include a given point.
void InflateRect (IntType Amount)
Inflates or deflates the rectangle.
TIntRect Inner (IntPointType Shrink) const
Gets a new rectangle from the inner of this one.
bool Intersect (const TIntRect &Other) const
Returns true if the two rects have any overlap.
bool IsEmpty () const
Returns true if the rectangle is 0 x 0.
bool operator!= (const TIntRect &Other) const
Compares Rectangles for inequality.
TIntRect & operator() (int32 PointIndex)
Gets a specific point in this rectangle.
const TIntRect & operator() (int32 PointIndex) const
Gets a specific point in this rectangle.
TIntRect operator* (IntType Scale) const
Gets the result of scaling on this rectangle.
TIntRect & operator*= (IntType Scale)
Applies scaling to this rectangle.
TIntRect operator+ (const IntPointType &Point) const
Gets the result of adding a point to this rectangle.
TIntRect operator+ (const TIntRect &Other) const
Gets the result of adding two rectangles together.
TIntRect & operator+= (const IntPointType &Point)
Adds a point to this rectangle.
TIntRect operator- (const IntPointType &Point) const
Gets the result of subtracting a point from this rectangle.
TIntRect operator- (const TIntRect &Other) const
Gets the result of subtracting a rectangle from this one.
TIntRect & operator-= (const IntPointType &Point)
Subtracts a point from this rectangle.
TIntRect operator/ (const IntPointType &Point) const
Gets the result of dividing a point with this rectangle.
TIntRect operator/ (IntType Div) const
Gets the result of division on this rectangle.
TIntRect & operator= (const TIntRect &Other)
bool operator== (const TIntRect &Other) const
Compares Rectangles for equality.
TIntRect Right (IntType InWidth) const
Creates a rectangle from the right hand side of this rectangle.
TIntRect Scale (double Fraction) const
Scales a rectangle using a floating point number.
IntPointType Size () const
Gets the distance from one corner of the rectangle to the other.
FString ToString () const
Get a textual representation of this rectangle.
void Union (const TIntRect &R)
Combines the two rectanges.
IntType Width () const
Gets the width of the rectangle.
Static Public Member Functions
static TIntRect DivideAndRoundUp (TIntRect lhs, IntPointType Div)
static TIntRect DivideAndRoundUp (TIntRect lhs, IntType Div)
Divides a rectangle and rounds up to the nearest integer.
static int32 Num ()
Gets number of points in the Rectangle.
Data Fields
union {
struct {
IntPointType Max
Holds the last pixel line/row (like in Win32 RECT).
IntPointType Min
Holds the first pixel line/row (like in Win32 RECT).
}
};
Friends
FArchive & operator<< (FArchive &Ar, TIntRect &Rect)
Serializes the Rectangle.
Detailed Description
template<typename InIntType>
struct UE::Math::TIntRect< InIntType >
Structure for integer rectangles in 2-d space.
Todo
Docs: The operators need better documentation, i.e. what does it mean to divide a rectangle?
Definition at line 21 of file IntRect.h.
Member Typedef Documentation
IntPointType
template<typename InIntType> using UE::Math::TIntRect< InIntType >::IntPointType = TIntPoint<IntType>
Definition at line 24 of file IntRect.h.
IntType
template<typename InIntType> using UE::Math::TIntRect< InIntType >::IntType = InIntType
Definition at line 23 of file IntRect.h.
Constructor & Destructor Documentation
TIntRect() [1/5]
template<typename InIntType> UE::Math::TIntRect< InIntType >::TIntRect () inline nodiscard
Constructor.
Definition at line 43 of file IntRect.h.
Referenced by UE::Math::TIntRect< int32 >::Bottom(), UE::Math::TIntRect< int32 >::DivideAndRoundUp(), UE::Math::TIntRect< int32 >::Inner(), UE::Math::TIntRect< int32 >::operator*(), UE::Math::TIntRect< int32 >::operator+(), UE::Math::TIntRect< int32 >::operator+(), UE::Math::TIntRect< int32 >::operator-(), UE::Math::TIntRect< int32 >::operator-(), UE::Math::TIntRect< int32 >::operator/(), UE::Math::TIntRect< int32 >::operator/(), UE::Math::TIntRect< int32 >::Right(), and UE::Math::TIntRect< int32 >::Scale().
TIntRect() [2/5]
template<typename InIntType> UE::Math::TIntRect< InIntType >::TIntRect (IntType X0, IntType Y0, IntType X1, IntType Y1) inline nodiscard
Constructor.
Parameters
X0 Minimum X coordinate.
Y0 Minimum Y coordinate.
X1 Maximum X coordinate.
Y1 Maximum Y coordinate.
Definition at line 56 of file IntRect.h.
TIntRect() [3/5]
template<typename InIntType> UE::Math::TIntRect< InIntType >::TIntRect (IntPointType InMin, IntPointType InMax) inline nodiscard
Constructor.
Parameters
InMin Minimum Point
InMax Maximum Point
Definition at line 68 of file IntRect.h.
TIntRect() [4/5]
template<typename InIntType> UE::Math::TIntRect< InIntType >::TIntRect (const TIntRect< InIntType > & Other) inline nodiscard
Definition at line 74 of file IntRect.h.
TIntRect() [5/5]
template<typename InIntType> template<typename OtherIntType> UE::Math::TIntRect< InIntType >::TIntRect (TIntRect< OtherIntType > Other) inline explicit nodiscard
Converts to another int type.
Checks that the cast will succeed.
Definition at line 90 of file IntRect.h.
Member Function Documentation
Area()
template<typename InIntType> IntType UE::Math::TIntRect< InIntType >::Area () const inline nodiscard
Calculates the area of this rectangle.
Returns
The area of this rectangle.
Definition at line 268 of file IntRect.h.
Referenced by FLandscapeConfigHelper::CopySubregion().
Bottom()
template<typename InIntType> TIntRect UE::Math::TIntRect< InIntType >::Bottom (IntType InHeight) const inline nodiscard
Creates a rectangle from the bottom part of this rectangle.
Parameters
InHeight Height of the new rectangle (<= rectangles original height).
Returns
The new rectangle.
Definition at line 280 of file IntRect.h.
Clip()
template<typename InIntType> void UE::Math::TIntRect< InIntType >::Clip (const TIntRect< InIntType > & R) inline
Clip a rectangle using the bounds of another rectangle.
Parameters
Other The other rectangle to clip against.
Definition at line 290 of file IntRect.h.
Contains()
template<typename InIntType> bool UE::Math::TIntRect< InIntType >::Contains (IntPointType P) const inline nodiscard
Test whether this rectangle contains a point.
Parameters
Point The point to test against.
Returns
true if the rectangle contains the specified point, false otherwise.
Note
This function assumes rects have half-open bounds, i.e. points are contained by the minimum border of the box, but not the maximum border.
Definition at line 334 of file IntRect.h.
DivideAndRoundUp() [1/2]
template<typename InIntType> TIntRect UE::Math::TIntRect< InIntType >::DivideAndRoundUp (TIntRect< InIntType > lhs, IntPointType Div) inline static nodiscard
Definition at line 483 of file IntRect.h.
DivideAndRoundUp() [2/2]
template<typename InIntType> TIntRect UE::Math::TIntRect< InIntType >::DivideAndRoundUp (TIntRect< InIntType > lhs, IntType Div) inline static nodiscard
Divides a rectangle and rounds up to the nearest integer.
Parameters
lhs The Rectangle to divide.
Div What to divide by.
Returns
New divided rectangle.
Definition at line 478 of file IntRect.h.
Referenced by UE::Math::TIntRect< int32 >::DivideAndRoundUp().
GetCenterAndExtents()
template<typename InIntType> void UE::Math::TIntRect< InIntType >::GetCenterAndExtents (IntPointType & OutCenter, IntPointType & OutExtent) const inline
Gets the Center and Extents of this rectangle.
Parameters
OutCenter Will contain the center point.
OutExtent Will contain the extent.
Definition at line 345 of file IntRect.h.
Height()
template<typename InIntType> IntType UE::Math::TIntRect< InIntType >::Height () const inline nodiscard
Gets the Height of the rectangle.
Returns
The Height of the rectangle.
Definition at line 359 of file IntRect.h.
Referenced by FLandscapeConfigHelper::CopySubregion(), FLandscapeConfigHelper::ExpandData(), UE::Math::TIntRect< int32 >::IsEmpty(), and FLandscapeConfigHelper::ResampleData().
Include()
template<typename InIntType> void UE::Math::TIntRect< InIntType >::Include (IntPointType Point) inline
Adds to this rectangle to include a given point.
Parameters
Point The point to increase the rectangle to.
Definition at line 382 of file IntRect.h.
InflateRect()
template<typename InIntType> void UE::Math::TIntRect< InIntType >::InflateRect (IntType Amount) inline
Inflates or deflates the rectangle.
Parameters
Amount The amount to inflate or deflate the rectangle on each side.
Definition at line 370 of file IntRect.h.
Inner()
template<typename InIntType> TIntRect UE::Math::TIntRect< InIntType >::Inner (IntPointType Shrink) const inline nodiscard
Gets a new rectangle from the inner of this one.
Parameters
Shrink How much to remove from each point of this rectangle.
Returns
New inner Rectangle.
Definition at line 396 of file IntRect.h.
Intersect()
template<typename InIntType> bool UE::Math::TIntRect< InIntType >::Intersect (const TIntRect< InIntType > & Other) const inline nodiscard
Returns true if the two rects have any overlap.
Parameters
Other The rect to compare with.
Returns
true if the rectangle overlaps the other rectangle, false otherwise.
Note
This function assumes rects have open bounds, i.e. rects with coincident borders on any edge will not overlap.
Definition at line 320 of file IntRect.h.
IsEmpty()
template<typename InIntType> bool UE::Math::TIntRect< InIntType >::IsEmpty () const inline nodiscard
Returns true if the rectangle is 0 x 0.
Returns
true if the rectangle is 0 x 0.
Definition at line 466 of file IntRect.h.
Num()
template<typename InIntType> int32 UE::Math::TIntRect< InIntType >::Num () inline static nodiscard
Gets number of points in the Rectangle.
Returns
Number of points in the Rectangle.
Definition at line 493 of file IntRect.h.
operator!=()
template<typename InIntType> bool UE::Math::TIntRect< InIntType >::operator!= (const TIntRect< InIntType > & Other) const inline nodiscard
Compares Rectangles for inequality.
Parameters
Other The Other Rectangle for comparison.
Returns
true if the rectangles are not equal, false otherwise..
Definition at line 139 of file IntRect.h.
operator()() [1/2]
template<typename InIntType> TIntRect & UE::Math::TIntRect< InIntType >::operator() (int32 PointIndex) inline nodiscard
Gets a specific point in this rectangle.
Parameters
PointIndex Index of Point in rectangle.
Returns
Reference to point in rectangle.
Definition at line 115 of file IntRect.h.
operator()() [2/2]
template<typename InIntType> const TIntRect & UE::Math::TIntRect< InIntType >::operator() (int32 PointIndex) const inline nodiscard
Gets a specific point in this rectangle.
Parameters
PointIndex Index of Point in rectangle.
Returns
Const reference to point in rectangle.
Definition at line 102 of file IntRect.h.
operator*()
template<typename InIntType> TIntRect UE::Math::TIntRect< InIntType >::operator* (IntType Scale) const inline nodiscard
Gets the result of scaling on this rectangle.
Parameters
Scale What to multiply this rectangle by.
Returns
New scaled rectangle.
Definition at line 192 of file IntRect.h.
operator*=()
template<typename InIntType> TIntRect & UE::Math::TIntRect< InIntType >::operator*= (IntType Scale) inline
Applies scaling to this rectangle.
Parameters
Scale What to multiply the rectangle by.
Returns
Reference to this rectangle after scaling.
Definition at line 150 of file IntRect.h.
operator+() [1/2]
template<typename InIntType> TIntRect UE::Math::TIntRect< InIntType >::operator+ (const IntPointType & Point) const inline nodiscard
Gets the result of adding a point to this rectangle.
Parameters
Point The point to add to both points in the rectangle.
Returns
New rectangle with point added to it.
Definition at line 214 of file IntRect.h.
operator+() [2/2]
template<typename InIntType> TIntRect UE::Math::TIntRect< InIntType >::operator+ (const TIntRect< InIntType > & Other) const inline nodiscard
Gets the result of adding two rectangles together.
Parameters
Other The other rectangle to add to this.
Returns
New rectangle after both are added together.
Definition at line 247 of file IntRect.h.
operator+=()
template<typename InIntType> TIntRect & UE::Math::TIntRect< InIntType >::operator+= (const IntPointType & Point) inline
Adds a point to this rectangle.
Parameters
Point The point to add onto both points in the rectangle.
Returns
Reference to this rectangle after addition.
Definition at line 164 of file IntRect.h.
operator-() [1/2]
template<typename InIntType> TIntRect UE::Math::TIntRect< InIntType >::operator- (const IntPointType & Point) const inline nodiscard
Gets the result of subtracting a point from this rectangle.
Parameters
Point The point to subtract from both points in the rectangle.
Returns
New rectangle with point subtracted from it.
Definition at line 236 of file IntRect.h.
operator-() [2/2]
template<typename InIntType> TIntRect UE::Math::TIntRect< InIntType >::operator- (const TIntRect< InIntType > & Other) const inline nodiscard
Gets the result of subtracting a rectangle from this one.
Parameters
Other The other rectangle to subtract from this.
Returns
New rectangle after one is subtracted from this.
Definition at line 258 of file IntRect.h.
operator-=()
template<typename InIntType> TIntRect & UE::Math::TIntRect< InIntType >::operator-= (const IntPointType & Point) inline
Subtracts a point from this rectangle.
Parameters
Point The point to subtract from both points in the rectangle.
Returns
Reference to this rectangle after subtraction.
Definition at line 178 of file IntRect.h.
operator/() [1/2]
template<typename InIntType> TIntRect UE::Math::TIntRect< InIntType >::operator/ (const IntPointType & Point) const inline nodiscard
Gets the result of dividing a point with this rectangle.
Parameters
Point The point to divide with.
Returns
New rectangle with point divided.
Definition at line 225 of file IntRect.h.
operator/() [2/2]
template<typename InIntType> TIntRect UE::Math::TIntRect< InIntType >::operator/ (IntType Div) const inline nodiscard
Gets the result of division on this rectangle.
Parameters
Div What to divide this rectangle by.
Returns
New divided rectangle.
Definition at line 203 of file IntRect.h.
operator=()
template<typename InIntType> TIntRect & UE::Math::TIntRect< InIntType >::operator= (const TIntRect< InIntType > & Other) inline
Definition at line 79 of file IntRect.h.
operator==()
template<typename InIntType> bool UE::Math::TIntRect< InIntType >::operator== (const TIntRect< InIntType > & Other) const inline nodiscard
Compares Rectangles for equality.
Parameters
Other The Other Rectangle for comparison.
Returns
true if the rectangles are equal, false otherwise..
Definition at line 128 of file IntRect.h.
Right()
template<typename InIntType> TIntRect UE::Math::TIntRect< InIntType >::Right (IntType InWidth) const inline nodiscard
Creates a rectangle from the right hand side of this rectangle.
Parameters
InWidth Width of the new rectangle (<= rectangles original width).
Returns
The new rectangle.
Definition at line 406 of file IntRect.h.
Scale()
template<typename InIntType> TIntRect UE::Math::TIntRect< InIntType >::Scale (double Fraction) const inline nodiscard
Scales a rectangle using a floating point number.
Parameters
Fraction What to scale the rectangle by
Returns
New scaled rectangle.
Definition at line 417 of file IntRect.h.
Size()
template<typename InIntType> IntPointType UE::Math::TIntRect< InIntType >::Size () const inline nodiscard
Gets the distance from one corner of the rectangle to the other.
Returns
The distance from one corner of the rectangle to the other.
Definition at line 436 of file IntRect.h.
ToString()
template<typename InIntType> FString UE::Math::TIntRect< InIntType >::ToString () const inline nodiscard
Get a textual representation of this rectangle.
Returns
A string describing the rectangle.
Definition at line 446 of file IntRect.h.
Union()
template<typename InIntType> void UE::Math::TIntRect< InIntType >::Union (const TIntRect< InIntType > & R) inline
Combines the two rectanges.
Definition at line 303 of file IntRect.h.
Width()
template<typename InIntType> IntType UE::Math::TIntRect< InIntType >::Width () const inline nodiscard
Gets the width of the rectangle.
Returns
The width of the rectangle.
Definition at line 456 of file IntRect.h.
Referenced by FLandscapeConfigHelper::CopySubregion(), FLandscapeConfigHelper::ExpandData(), UE::Math::TIntRect< int32 >::IsEmpty(), and FLandscapeConfigHelper::ResampleData().
Friends And Related Symbol Documentation
operator<<
template<typename InIntType> FArchive & operator<< (FArchive & Ar, TIntRect< InIntType > & Rect) friend
Serializes the Rectangle.
Parameters
Ar The archive to serialize into.
Rect The rectangle to serialize.
Returns
Reference to the Archive after serialization.
Definition at line 507 of file IntRect.h.
Field Documentation
[union]
union { ... } UE::Math::TIntRect< InIntType >
Max
template<typename InIntType> IntPointType UE::Math::TIntRect< InIntType >::Max
Holds the last pixel line/row (like in Win32 RECT).
Definition at line 35 of file IntRect.h.
Referenced by CropUnmappedTexels(), UE::Math::TIntRect< int32 >::DivideAndRoundUp(), FPixelShaderUtils::DrawFullscreenInstancedMultiViewportPixelShader(), UE::Math::GetTypeHash(), TSimpleCellGrid< CellType, InvalidCellValue >::GetWorldCellRectangleBox(), and UE::Math::TIntRect< int32 >::operator<<.
Min
template<typename InIntType> IntPointType UE::Math::TIntRect< InIntType >::Min
Holds the first pixel line/row (like in Win32 RECT).
Definition at line 32 of file IntRect.h.
Referenced by FLandscapeConfigHelper::CopySubregion(), CropUnmappedTexels(), UE::Math::TIntRect< int32 >::DivideAndRoundUp(), FPixelShaderUtils::DrawFullscreenInstancedMultiViewportPixelShader(), FLandscapeConfigHelper::ExpandData(), UE::Math::GetTypeHash(), TSimpleCellGrid< CellType, InvalidCellValue >::GetWorldCellRectangleBox(), and UE::Math::TIntRect< int32 >::operator<<.
The documentation for this struct was generated from the following file:
Runtime/Core/Public/Math/IntRect.h