Unreal Engine 5.6 C++ API: UE::Math::TTranslationMatrix< T > Struct Template Reference
UE::Math::TTranslationMatrix< T > Struct Template Reference
#include "TranslationMatrix.h"
Public Member Functions
template<typename FArg UE_REQUIRES>
TTranslationMatrix (const TTranslationMatrix< FArg > &From)
TTranslationMatrix (const TVector< T > &Delta)
Constructor translation matrix based on given vector.
Public Member Functions inherited from UE::Math::TMatrix< T >
TMatrix ()=default
template<typename FArg UE_REQUIRES>
TMatrix (const TMatrix< FArg > &From)
FORCEINLINE TMatrix (const TPlane< T > &InX, const TPlane< T > &InY, const TPlane< T > &InZ, const TPlane< T > &InW)
Constructor.
FORCEINLINE TMatrix (const TVector< T > &InX, const TVector< T > &InY, const TVector< T > &InZ, const TVector< T > &InW)
Constructor.
FORCEINLINE TMatrix (EForceInit)
Constructor.
TMatrix< T > ApplyScale (T Scale) const
Apply Scale to this matrix.
uint32 ComputeHash () const
For debugging purpose, could be changed.
TMatrix< T > ConcatTranslation (const TVector< T > &Translation) const
Returns a matrix with an additional translation concatenated.
bool ContainsNaN () const
Returns true if any element of this matrix is NaN.
void DebugPrint () const
Output ToString.
T Determinant () const
FORCEINLINE void DiagnosticCheckNaN () const
bool Equals (const TMatrix< T > &Other, T Tolerance=UE_KINDA_SMALL_NUMBER) const
Checks whether another Matrix is equal to this, within specified tolerance.
TVector< T > ExtractScaling (T Tolerance=UE_SMALL_NUMBER)
Remove any scaling from this matrix (ie magnitude of each row is 1) and return the 3D scale vector that was initially present with error Tolerance.
TVector< T > GetColumn (int32 i) const
get a column of this matrix
FORCEINLINE bool GetFrustumBottomPlane (TPlane< T > &OuTPln) const
FORCEINLINE bool GetFrustumFarPlane (TPlane< T > &OuTPln) const
FORCEINLINE bool GetFrustumLeftPlane (TPlane< T > &OuTPln) const
FORCEINLINE bool GetFrustumNearPlane (TPlane< T > &OuTPln) const
FORCEINLINE bool GetFrustumRightPlane (TPlane< T > &OuTPln) const
FORCEINLINE bool GetFrustumTopPlane (TPlane< T > &OuTPln) const
TMatrix< T > GetMatrixWithoutScale (T Tolerance=UE_SMALL_NUMBER) const
T GetMaximumAxisScale () const
T GetMinimumAxisScale () const
TVector< T > GetOrigin () const
void GetScaledAxes (TVector< T > &X, TVector< T > &Y, TVector< T > &Z) const
get axes of this matrix scaled by the scale of the matrix
TVector< T > GetScaledAxis (EAxis::Type Axis) const
get axis of this matrix scaled by the scale of the matrix
TVector< T > GetScaleVector (T Tolerance=UE_SMALL_NUMBER) const
return a 3D scale vector calculated from this matrix (where each component is the magnitude of a row vector) with error Tolerance.
FORCEINLINE TMatrix< T > GetTransposed () const
void GetUnitAxes (TVector< T > &X, TVector< T > &Y, TVector< T > &Z) const
get unit length axes of this matrix
TVector< T > GetUnitAxis (EAxis::Type Axis) const
get unit length axis of this matrix
TMatrix< T > Inverse () const
Get the inverse of this matrix.
TMatrix< T > InverseFast () const
Get the inverse of this matrix.
FORCEINLINE TVector< T > InverseTransformPosition (const TVector< T > &V) const
Inverts the matrix and then transforms V - correctly handles scaling in this matrix.
FORCEINLINE TVector< T > InverseTransformVector (const TVector< T > &V) const
Transform a direction vector by the inverse of this matrix - will not take into account translation part.
void Mirror (EAxis::Type MirrorAxis, EAxis::Type FlipAxis)
Utility for mirroring this transform across a certain plane, and flipping one of the axis as well.
bool operator!= (const TMatrix< T > &Other) const
Checks whether another Matrix is not equal to this, within specified tolerance.
FORCEINLINE TMatrix< T > operator* (const TMatrix< T > &Other) const
Gets the result of multiplying a Matrix to this.
FORCEINLINE TMatrix< T > operator* (T Other) const
This isn't applying SCALE, just multiplying the value to all members - i.e.
FORCEINLINE void operator*= (const TMatrix< T > &Other)
Multiply this by a matrix.
FORCEINLINE void operator*= (T Other)
Multiply this matrix by a weighting factor.
FORCEINLINE TMatrix< T > operator+ (const TMatrix< T > &Other) const
Gets the result of adding a matrix to this.
FORCEINLINE void operator+= (const TMatrix< T > &Other)
Adds to this matrix.
bool operator== (const TMatrix< T > &Other) const
Checks whether two matrix are identical.
void RemoveScaling (T Tolerance=UE_SMALL_NUMBER)
TMatrix< T > RemoveTranslation () const
UE::Math::TRotator< T > Rotator () const
T RotDeterminant () const
void ScaleTranslation (const TVector< T > &Scale3D)
Scale the translation part of the matrix by the supplied vector.
bool Serialize (FArchive &Ar)
bool SerializeFromMismatchedTag (FName StructTag, FArchive &Ar)
void SetAxes (const TVector< T > *Axis0=NULL, const TVector< T > *Axis1=NULL, const TVector< T > *Axis2=NULL, const TVector< T > *Origin=NULL)
Update the axes of the matrix if any value is NULL do not update that axis.
void SetAxis (int32 i, const TVector< T > &Axis)
set an axis of this matrix
void SetColumn (int32 i, TVector< T > Value)
Set a column of this matrix.
void SetIdentity ()
void SetOrigin (const TVector< T > &NewOrigin)
FORCEINLINE void To3x4MatrixTranspose (T *Out) const
Convert this Atom to the 3x4 transpose of the transformation matrix.
UE::Math::TQuat< T > ToQuat () const
Transform a rotation matrix into a quaternion.
FString ToString () const
Get a textual representation of the vector.
FORCEINLINE TVector4< T > TransformFVector4 (const TVector4< T > &V) const
FORCEINLINE TVector4< T > TransformPosition (const TVector< T > &V) const
Transform a location - will take into account translation part of the TMatrix<T>.
FORCEINLINE TVector4< T > TransformVector (const TVector< T > &V) const
Transform a direction vector - will not take into account translation part of the TMatrix<T>.
TMatrix< T > TransposeAdjoint () const
Static Public Member Functions
static TMatrix< T > Make (TVector< T > const &Delta)
Matrix factory.
Additional Inherited Members
Public Types inherited from UE::Math::TMatrix< T >
using FReal = T
Data Fields inherited from UE::Math::TMatrix< T >
T M [4][4]
Static Public Attributes inherited from UE::Math::TMatrix< T >
static const TMatrix Identity
Detailed Description
template<typename T>
struct UE::Math::TTranslationMatrix< T >
Definition at line 14 of file TranslationMatrix.h.
Constructor & Destructor Documentation
TTranslationMatrix() [1/2]
template<typename T> FORCEINLINE UE::Math::TTranslationMatrix< T >::TTranslationMatrix (const TVector< T > & Delta) nodiscard
Constructor translation matrix based on given vector.
Definition at line 37 of file TranslationMatrix.h.
References UE::Math::TMatrix< T >::TMatrix(), FORCEINLINE, X, Y, and Z.
Referenced by TTranslationMatrix(), and Make().
TTranslationMatrix() [2/2]
template<typename T> template<typename FArg UE_REQUIRES> UE::Math::TTranslationMatrix< T >::TTranslationMatrix (const TTranslationMatrix< FArg > & From) inline explicit nodiscard
Definition at line 24 of file TranslationMatrix.h.
References UE::Math::TMatrix< T >::TMatrix(), and TTranslationMatrix().
Member Function Documentation
Make()
template<typename T> TMatrix< T > UE::Math::TTranslationMatrix< T >::Make (TVector< T > const & Delta) inline static nodiscard
Matrix factory.
Return an FMatrix so we don't have type conversion issues in expressions.
Definition at line 30 of file TranslationMatrix.h.
References UE::Math::TMatrix< T >::TMatrix(), and TTranslationMatrix().
The documentation for this struct was generated from the following file:
Runtime/Core/Public/Math/TranslationMatrix.h