Unreal Engine 5.6 C++ API: FMovieSceneExecutionTokens Struct Reference
FMovieSceneExecutionTokens Struct Reference
Ordered execution token stack that accumulates tokens that will apply animated state to the sequence environment at a later time.
#include "MovieSceneExecutionTokens.h"
Data Structures
struct FEntry
Public Member Functions
FMovieSceneExecutionTokens ()
FMovieSceneExecutionTokens (const FMovieSceneExecutionTokens &)=delete
FMovieSceneExecutionTokens (FMovieSceneExecutionTokens &&)=default
template<typename T>
FORCEINLINE TEnableIf< TPointerIsConvertibleFromTo< typenameTRemoveReference< T >::Type, constIMovieSceneExecutionToken >::Value >::Type Add (T &&InToken)
Add a new IMovieSceneExecutionToken derived token to the stack.
template<typename T>
FORCEINLINE TEnableIf< TPointerIsConvertibleFromTo< typenameTRemoveReference< T >::Type, constIMovieSceneSharedExecutionToken >::Value >::Type AddShared (FMovieSceneSharedDataId ID, T &&InToken)
Add a new shared execution token to the sorted array of tokens.
MOVIESCENE_API void Apply (const FMovieSceneContext &RootContext, IMovieScenePlayer &Player)
Apply all execution tokens in order, followed by blended tokens.
template<typename ActuatorDataType>
void BlendToken (FMovieSceneBlendingActuatorID InActuatorTypeID, TBlendableToken< ActuatorDataType > &&InToken)
Blend the specified global token using the specified actuator ID.
IMovieSceneSharedExecutionToken * FindShared (FMovieSceneSharedDataId ID)
Attempt to locate an existing shared execution token by its ID.
FMovieSceneBlendingAccumulator & GetBlendingAccumulator ()
Access the execution stack's blending accumulator which is responsible for marshalling all blending operations for all animated objects.
const FMovieSceneBlendingAccumulator & GetBlendingAccumulator () const
Access the execution stack's blending accumulator which is responsible for marshalling all blending operations for all animated objects.
FORCEINLINE FMovieSceneEvaluationScope GetCurrentScope () const
Get the current evaluation scope.
FMovieSceneExecutionTokens & operator= (const FMovieSceneExecutionTokens &)=delete
FMovieSceneExecutionTokens & operator= (FMovieSceneExecutionTokens &&)=default
FORCEINLINE void SetContext (const FMovieSceneContext &InContext)
Internal: Set the current context.
FORCEINLINE void SetCurrentScope (const FMovieSceneEvaluationScope &InScope)
Internal: Set the current scope.
FORCEINLINE void SetOperand (const FMovieSceneEvaluationOperand &InOperand)
Internal: Set the operand we're currently operating on.
Private Attributes
FMovieSceneBlendingAccumulator BlendingAccumulator
Accumulator used to marshal blended animation data.
FMovieSceneContext Context
The current context.
FMovieSceneEvaluationOperand Operand
The operand we're currently operating on.
TArray< FEntry > OrderedTokens
Ordered array of tokens.
FMovieSceneEvaluationScope Scope
The current evaluation scope.
TMap< FMovieSceneSharedDataId, TInlineValue< IMovieSceneSharedExecutionToken, 32 > > SharedTokens
Sortable, shared array of identifyable tokens.
Detailed Description
Ordered execution token stack that accumulates tokens that will apply animated state to the sequence environment at a later time.
Definition at line 34 of file MovieSceneExecutionTokens.h.
Constructor & Destructor Documentation
FMovieSceneExecutionTokens() [1/3]
FMovieSceneExecutionTokens::FMovieSceneExecutionTokens () inline
Definition at line 36 of file MovieSceneExecutionTokens.h.
References Context.
Referenced by FMovieSceneExecutionTokens(), FMovieSceneExecutionTokens(), operator=(), and operator=().
FMovieSceneExecutionTokens() [2/3]
FMovieSceneExecutionTokens::FMovieSceneExecutionTokens (const FMovieSceneExecutionTokens &) delete
References FMovieSceneExecutionTokens().
FMovieSceneExecutionTokens() [3/3]
FMovieSceneExecutionTokens::FMovieSceneExecutionTokens (FMovieSceneExecutionTokens &&) default
References FMovieSceneExecutionTokens().
Member Function Documentation
Add()
template<typename T> FORCEINLINE TEnableIf< TPointerIsConvertibleFromTo< typenameTRemoveReference< T >::Type, constIMovieSceneExecutionToken >::Value >::Type FMovieSceneExecutionTokens::Add (T && InToken) inline
Add a new IMovieSceneExecutionToken derived token to the stack.
Definition at line 51 of file MovieSceneExecutionTokens.h.
References check, Context, FORCEINLINE, Forward(), Operand, OrderedTokens, Scope, and Value.
AddShared()
template<typename T> FORCEINLINE TEnableIf< TPointerIsConvertibleFromTo< typenameTRemoveReference< T >::Type, constIMovieSceneSharedExecutionToken >::Value >::Type FMovieSceneExecutionTokens::AddShared (FMovieSceneSharedDataId ID, T && InToken) inline
Add a new shared execution token to the sorted array of tokens.
Definition at line 61 of file MovieSceneExecutionTokens.h.
References checkf, FORCEINLINE, ID, MoveTemp(), SharedTokens, TEXT, and Value.
Apply()
MOVIESCENE_API void FMovieSceneExecutionTokens::Apply (const FMovieSceneContext & RootContext, IMovieScenePlayer & Player)
Apply all execution tokens in order, followed by blended tokens.
BlendToken()
template<typename ActuatorDataType> void FMovieSceneExecutionTokens::BlendToken (FMovieSceneBlendingActuatorID InActuatorTypeID, TBlendableToken< ActuatorDataType > && InToken) inline
Blend the specified global token using the specified actuator ID.
Note
: Actuator must already exist for this function to succeed
Parameters
InActuatorTypeID Type identifier that uniquely identifies the actuator to be used to apply the final blend
InToken Token holding the data to blend
Definition at line 104 of file MovieSceneExecutionTokens.h.
References BlendingAccumulator, Context, MoveTemp(), Operand, and Scope.
FindShared()
IMovieSceneSharedExecutionToken * FMovieSceneExecutionTokens::FindShared (FMovieSceneSharedDataId ID) inline
Attempt to locate an existing shared execution token by its ID.
Definition at line 70 of file MovieSceneExecutionTokens.h.
References ID, and SharedTokens.
GetBlendingAccumulator() [1/2]
FMovieSceneBlendingAccumulator & FMovieSceneExecutionTokens::GetBlendingAccumulator () inline
Access the execution stack's blending accumulator which is responsible for marshalling all blending operations for all animated objects.
Returns
Mutable reference to the blending accumulator
Definition at line 82 of file MovieSceneExecutionTokens.h.
References BlendingAccumulator.
GetBlendingAccumulator() [2/2]
const FMovieSceneBlendingAccumulator & FMovieSceneExecutionTokens::GetBlendingAccumulator () const inline
Access the execution stack's blending accumulator which is responsible for marshalling all blending operations for all animated objects.
Returns
Mutable reference to the blending accumulator
Definition at line 91 of file MovieSceneExecutionTokens.h.
References BlendingAccumulator.
GetCurrentScope()
FORCEINLINE FMovieSceneEvaluationScope FMovieSceneExecutionTokens::GetCurrentScope () const inline
Get the current evaluation scope.
Definition at line 143 of file MovieSceneExecutionTokens.h.
References FORCEINLINE, and Scope.
operator=() [1/2]
FMovieSceneExecutionTokens & FMovieSceneExecutionTokens::operator= (const FMovieSceneExecutionTokens &) delete
References FMovieSceneExecutionTokens().
operator=() [2/2]
FMovieSceneExecutionTokens & FMovieSceneExecutionTokens::operator= (FMovieSceneExecutionTokens &&) default
References FMovieSceneExecutionTokens().
SetContext()
FORCEINLINE void FMovieSceneExecutionTokens::SetContext (const FMovieSceneContext & InContext) inline
Internal: Set the current context.
Definition at line 135 of file MovieSceneExecutionTokens.h.
References Context, and FORCEINLINE.
SetCurrentScope()
FORCEINLINE void FMovieSceneExecutionTokens::SetCurrentScope (const FMovieSceneEvaluationScope & InScope) inline
Internal: Set the current scope.
Definition at line 127 of file MovieSceneExecutionTokens.h.
References FORCEINLINE, and Scope.
SetOperand()
FORCEINLINE void FMovieSceneExecutionTokens::SetOperand (const FMovieSceneEvaluationOperand & InOperand) inline
Internal: Set the operand we're currently operating on.
Definition at line 119 of file MovieSceneExecutionTokens.h.
References FORCEINLINE, and Operand.
Field Documentation
BlendingAccumulator
FMovieSceneBlendingAccumulator FMovieSceneExecutionTokens::BlendingAccumulator private
Accumulator used to marshal blended animation data.
Definition at line 180 of file MovieSceneExecutionTokens.h.
Referenced by BlendToken(), GetBlendingAccumulator(), and GetBlendingAccumulator().
Context
FMovieSceneContext FMovieSceneExecutionTokens::Context private
The current context.
Definition at line 187 of file MovieSceneExecutionTokens.h.
Referenced by FMovieSceneExecutionTokens(), Add(), BlendToken(), and SetContext().
Operand
FMovieSceneEvaluationOperand FMovieSceneExecutionTokens::Operand private
The operand we're currently operating on.
Definition at line 183 of file MovieSceneExecutionTokens.h.
Referenced by Add(), BlendToken(), and SetOperand().
OrderedTokens
TArray<FEntry> FMovieSceneExecutionTokens::OrderedTokens private
Ordered array of tokens.
Definition at line 174 of file MovieSceneExecutionTokens.h.
Referenced by Add().
Scope
FMovieSceneEvaluationScope FMovieSceneExecutionTokens::Scope private
The current evaluation scope.
Definition at line 185 of file MovieSceneExecutionTokens.h.
Referenced by Add(), BlendToken(), GetCurrentScope(), and SetCurrentScope().
SharedTokens
TMap<FMovieSceneSharedDataId, TInlineValue<IMovieSceneSharedExecutionToken, 32> > FMovieSceneExecutionTokens::SharedTokens private
Sortable, shared array of identifyable tokens.
Definition at line 177 of file MovieSceneExecutionTokens.h.
Referenced by AddShared(), and FindShared().
The documentation for this struct was generated from the following file:
Runtime/MovieScene/Public/Evaluation/MovieSceneExecutionTokens.h