Unreal Engine 5.6 C++ API: UE::Geometry::IMeshSpatial::FQueryOptions Struct Reference
UE::Geometry::IMeshSpatial::FQueryOptions Struct Reference
#include "SpatialInterfaces.h"
Public Member Functions
FQueryOptions ()
FQueryOptions (double MaxDistance, TFunction< bool(int)> TriangleFilterF=nullptr)
FQueryOptions (TFunction< bool(int)> TriangleFilterF)
Data Fields
bool bAllowUnsafeModifiedMeshQueries = false
double MaxDistance = TNumericLimits<double>::Max()
Maximum search distance / hit distance, where applicable.
TFunction< bool(int)> TriangleFilterF = nullptr
If non-null, only triangle IDs that pass this filter (i.e.
Detailed Description
Definition at line 56 of file SpatialInterfaces.h.
Constructor & Destructor Documentation
FQueryOptions() [1/3]
UE::Geometry::IMeshSpatial::FQueryOptions::FQueryOptions () inline
Definition at line 75 of file SpatialInterfaces.h.
FQueryOptions() [2/3]
UE::Geometry::IMeshSpatial::FQueryOptions::FQueryOptions (TFunction< bool(int)> TriangleFilterF) inline
Definition at line 76 of file SpatialInterfaces.h.
References TriangleFilterF.
FQueryOptions() [3/3]
UE::Geometry::IMeshSpatial::FQueryOptions::FQueryOptions (double MaxDistance, TFunction< bool(int)> TriangleFilterF = nullptr) inline
Definition at line 77 of file SpatialInterfaces.h.
References MaxDistance, and TriangleFilterF.
Field Documentation
bAllowUnsafeModifiedMeshQueries
bool UE::Geometry::IMeshSpatial::FQueryOptions::bAllowUnsafeModifiedMeshQueries = false
Definition at line 73 of file SpatialInterfaces.h.
MaxDistance
double UE::Geometry::IMeshSpatial::FQueryOptions::MaxDistance = TNumericLimits<double>::Max()
Maximum search distance / hit distance, where applicable.
Definition at line 61 of file SpatialInterfaces.h.
Referenced by FQueryOptions().
TriangleFilterF
TFunction<bool(int)> UE::Geometry::IMeshSpatial::FQueryOptions::TriangleFilterF = nullptr
If non-null, only triangle IDs that pass this filter (i.e.
filter is true) are considered
Definition at line 66 of file SpatialInterfaces.h.
Referenced by FQueryOptions(), FQueryOptions(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::find_any_intersection(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::find_intersections(), and UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::find_nearest_triangles().
The documentation for this struct was generated from the following file:
Runtime/GeometryCore/Public/Spatial/SpatialInterfaces.h