Unreal Engine 5.6 C++ API: UE::AnimNext::FNodeTemplate Struct Reference
UE::AnimNext::FNodeTemplate Struct Reference
Node Template A node template represents a specific combination and ordering of traits on a node.
#include "NodeTemplate.h"
Public Member Functions
uint32 GetNodeInstanceDataSize () const
uint32 GetNodeSharedDataSize () const
uint32 GetNodeTemplateSize () const
uint32 GetNumTraits () const
FTraitTemplate * GetTraits ()
const FTraitTemplate * GetTraits () const
uint32 GetUID () const
bool IsValid () const
ANIMNEXTANIMGRAPH_API void Serialize (FArchive &Ar)
Static Public Attributes
static constexpr uint32 MAXIMUM_SIZE = 64 * 1024
Private Member Functions
FNodeTemplate (uint32 InUID, uint32 InNumTraits)
ANIMNEXTANIMGRAPH_API void Finalize ()
Private Attributes
uint16 NodeInstanceDataSize
uint16 NodeSharedDataSize
uint8 NumTraits
uint8 Padding [3]
uint32 UID
Friends
struct FNodeTemplateBuilder
Detailed Description
Node Template A node template represents a specific combination and ordering of traits on a node.
For example, a sequence player + sync group trait + output caching trait
Multiple node descriptions can share the same template each with their own property/pin values.
Templates can exist in multiple sub-graphs on disk. On load, a single unique copy is retained in memory and shared between ALL graphs.
Node templates are created through the FNodeTemplateBuilder.
See also
FNodeDescription, FNodeTemplateBuilder
Definition at line 28 of file NodeTemplate.h.
Constructor & Destructor Documentation
FNodeTemplate()
UE::AnimNext::FNodeTemplate::FNodeTemplate (uint32 InUID, uint32 InNumTraits) inline private
Definition at line 65 of file NodeTemplate.h.
References NodeInstanceDataSize, NodeSharedDataSize, NumTraits, and UID.
Referenced by GetNodeTemplateSize(), GetTraits(), and GetTraits().
Member Function Documentation
Finalize()
ANIMNEXTANIMGRAPH_API void UE::AnimNext::FNodeTemplate::Finalize () private
GetNodeInstanceDataSize()
uint32 UE::AnimNext::FNodeTemplate::GetNodeInstanceDataSize () const inline
Definition at line 45 of file NodeTemplate.h.
References NodeInstanceDataSize.
GetNodeSharedDataSize()
uint32 UE::AnimNext::FNodeTemplate::GetNodeSharedDataSize () const inline
Definition at line 42 of file NodeTemplate.h.
References NodeSharedDataSize.
GetNodeTemplateSize()
uint32 UE::AnimNext::FNodeTemplate::GetNodeTemplateSize () const inline
Definition at line 39 of file NodeTemplate.h.
References FNodeTemplate(), and NumTraits.
GetNumTraits()
uint32 UE::AnimNext::FNodeTemplate::GetNumTraits () const inline
Definition at line 48 of file NodeTemplate.h.
References NumTraits.
GetTraits() [1/2]
FTraitTemplate * UE::AnimNext::FNodeTemplate::GetTraits () inline
Definition at line 54 of file NodeTemplate.h.
References FNodeTemplate().
GetTraits() [2/2]
const FTraitTemplate * UE::AnimNext::FNodeTemplate::GetTraits () const inline
Definition at line 57 of file NodeTemplate.h.
References FNodeTemplate().
GetUID()
uint32 UE::AnimNext::FNodeTemplate::GetUID () const inline
Definition at line 36 of file NodeTemplate.h.
References UID.
IsValid()
bool UE::AnimNext::FNodeTemplate::IsValid () const inline
Definition at line 51 of file NodeTemplate.h.
References NodeInstanceDataSize, and NodeSharedDataSize.
Serialize()
ANIMNEXTANIMGRAPH_API void UE::AnimNext::FNodeTemplate::Serialize (FArchive & Ar)
References Ar.
Friends And Related Symbol Documentation
FNodeTemplateBuilder
friend struct FNodeTemplateBuilder friend
Definition at line 63 of file NodeTemplate.h.
References FNodeTemplateBuilder.
Referenced by FNodeTemplateBuilder.
Field Documentation
MAXIMUM_SIZE
uint32 UE::AnimNext::FNodeTemplate::MAXIMUM_SIZE = 64 * 1024 static constexpr
Definition at line 33 of file NodeTemplate.h.
NodeInstanceDataSize
uint16 UE::AnimNext::FNodeTemplate::NodeInstanceDataSize private
Definition at line 79 of file NodeTemplate.h.
Referenced by FNodeTemplate(), GetNodeInstanceDataSize(), and IsValid().
NodeSharedDataSize
uint16 UE::AnimNext::FNodeTemplate::NodeSharedDataSize private
Definition at line 78 of file NodeTemplate.h.
Referenced by FNodeTemplate(), GetNodeSharedDataSize(), and IsValid().
NumTraits
uint8 UE::AnimNext::FNodeTemplate::NumTraits private
Definition at line 81 of file NodeTemplate.h.
Referenced by FNodeTemplate(), GetNodeTemplateSize(), and GetNumTraits().
Padding
uint8 UE::AnimNext::FNodeTemplate::Padding[3] private
Definition at line 82 of file NodeTemplate.h.
UID
uint32 UE::AnimNext::FNodeTemplate::UID private
Definition at line 76 of file NodeTemplate.h.
Referenced by FNodeTemplate(), and GetUID().
The documentation for this struct was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Experimental/AnimNextAnimGraph/Source/AnimNextAnimGraph/Public/TraitCore/NodeTemplate.h