Unreal Engine 5.6 C++ API: FGPUDriverInfo Struct Reference
FGPUDriverInfo Struct Reference
#include "GenericPlatformDriver.h"
Public Member Functions
FString GetUnifiedDriverVersion () const
bool IsAMD () const
bool IsIntel () const
bool IsNVIDIA () const
bool IsSameDriverVersionGeneration (const FDriverVersion &UnifiedDriverVersion) const
bool IsValid () const
void SetAMD ()
void SetIntel ()
void SetNVIDIA ()
Static Public Member Functions
static FString GetIntelUnifiedVersion (const FString &InternalVersion)
static FString GetNVIDIAUnifiedVersion (const FString &InternalVersion)
Data Fields
FString DeviceDescription
FString DriverDate
FString InternalDriverVersion
FString ProviderName
FString RHIName
FString UserDriverVersion
uint32 VendorId = 0
Detailed Description
Definition at line 155 of file GenericPlatformDriver.h.
Member Function Documentation
GetIntelUnifiedVersion()
FString FGPUDriverInfo::GetIntelUnifiedVersion (const FString & InternalVersion) inline static
Definition at line 225 of file GenericPlatformDriver.h.
References ESearchCase::CaseSensitive, ESearchDir::FromStart, INDEX_NONE, and TEXT.
Referenced by GetUnifiedDriverVersion().
GetNVIDIAUnifiedVersion()
FString FGPUDriverInfo::GetNVIDIAUnifiedVersion (const FString & InternalVersion) inline static
Definition at line 209 of file GenericPlatformDriver.h.
References TEXT.
Referenced by GetUnifiedDriverVersion().
GetUnifiedDriverVersion()
FString FGPUDriverInfo::GetUnifiedDriverVersion () const inline
Definition at line 242 of file GenericPlatformDriver.h.
References GetIntelUnifiedVersion(), GetNVIDIAUnifiedVersion(), InternalDriverVersion, IsIntel(), IsNVIDIA(), and UserDriverVersion.
Referenced by IsSameDriverVersionGeneration().
IsAMD()
bool FGPUDriverInfo::IsAMD () const inline
Definition at line 190 of file GenericPlatformDriver.h.
References VendorId.
IsIntel()
bool FGPUDriverInfo::IsIntel () const inline
Definition at line 191 of file GenericPlatformDriver.h.
References VendorId.
Referenced by GetUnifiedDriverVersion(), and IsSameDriverVersionGeneration().
IsNVIDIA()
bool FGPUDriverInfo::IsNVIDIA () const inline
Definition at line 192 of file GenericPlatformDriver.h.
References VendorId.
Referenced by GetUnifiedDriverVersion().
IsSameDriverVersionGeneration()
bool FGPUDriverInfo::IsSameDriverVersionGeneration (const FDriverVersion & UnifiedDriverVersion) const inline
Definition at line 194 of file GenericPlatformDriver.h.
References GetUnifiedDriverVersion(), FDriverVersion::GetVersionValue(), and IsIntel().
IsValid()
bool FGPUDriverInfo::IsValid () const inline
Definition at line 178 of file GenericPlatformDriver.h.
References DeviceDescription, InternalDriverVersion, TEXT, and VendorId.
SetAMD()
void FGPUDriverInfo::SetAMD () inline
Definition at line 186 of file GenericPlatformDriver.h.
References VendorId.
SetIntel()
void FGPUDriverInfo::SetIntel () inline
Definition at line 187 of file GenericPlatformDriver.h.
References VendorId.
SetNVIDIA()
void FGPUDriverInfo::SetNVIDIA () inline
Definition at line 188 of file GenericPlatformDriver.h.
References VendorId.
Field Documentation
DeviceDescription
FString FGPUDriverInfo::DeviceDescription
Definition at line 161 of file GenericPlatformDriver.h.
Referenced by IsValid().
DriverDate
FString FGPUDriverInfo::DriverDate
Definition at line 173 of file GenericPlatformDriver.h.
InternalDriverVersion
FString FGPUDriverInfo::InternalDriverVersion
Definition at line 167 of file GenericPlatformDriver.h.
Referenced by GetUnifiedDriverVersion(), and IsValid().
ProviderName
FString FGPUDriverInfo::ProviderName
Definition at line 164 of file GenericPlatformDriver.h.
RHIName
FString FGPUDriverInfo::RHIName
Definition at line 176 of file GenericPlatformDriver.h.
UserDriverVersion
FString FGPUDriverInfo::UserDriverVersion
Definition at line 170 of file GenericPlatformDriver.h.
Referenced by GetUnifiedDriverVersion().
VendorId
uint32 FGPUDriverInfo::VendorId = 0
Definition at line 158 of file GenericPlatformDriver.h.
Referenced by IsAMD(), IsIntel(), IsNVIDIA(), IsValid(), SetAMD(), SetIntel(), and SetNVIDIA().
The documentation for this struct was generated from the following file:
Runtime/Core/Public/GenericPlatform/GenericPlatformDriver.h