Unreal Engine 5.6 C++ API: TDontCopy< T > Struct Template Reference
TDontCopy< T > Struct Template Reference
#include "DontCopy.h"
Public Member Functions
TDontCopy ()=default
TDontCopy (const TDontCopy &)
TDontCopy (TDontCopy &&)
~TDontCopy ()=default
T & Get ()
const T & Get () const
T & operator* ()
const T & operator* () const
T * operator-> ()
const T * operator-> () const
TDontCopy & operator= (const TDontCopy &)
TDontCopy & operator= (TDontCopy &&)
Private Attributes
T Value
Detailed Description
template<typename T>
struct TDontCopy< T >
Definition at line 12 of file DontCopy.h.
Constructor & Destructor Documentation
TDontCopy() [1/3]
template<typename T> TDontCopy< T >::TDontCopy () default
Referenced by TDontCopy(), TDontCopy(), operator=(), and operator=().
~TDontCopy()
template<typename T> TDontCopy< T >::~TDontCopy () default
TDontCopy() [2/3]
template<typename T> TDontCopy< T >::TDontCopy (TDontCopy< T > &&) inline
Definition at line 16 of file DontCopy.h.
References TDontCopy().
TDontCopy() [3/3]
template<typename T> TDontCopy< T >::TDontCopy (const TDontCopy< T > &) inline
Definition at line 17 of file DontCopy.h.
References TDontCopy().
Member Function Documentation
Get() [1/2]
template<typename T> T & TDontCopy< T >::Get () inline
Definition at line 21 of file DontCopy.h.
References Value.
Get() [2/2]
template<typename T> const T & TDontCopy< T >::Get () const inline
Definition at line 22 of file DontCopy.h.
References Value.
operator*() [1/2]
template<typename T> T & TDontCopy< T >::operator* () inline
Definition at line 27 of file DontCopy.h.
References Value.
operator*() [2/2]
template<typename T> const T & TDontCopy< T >::operator* () const inline
Definition at line 28 of file DontCopy.h.
References Value.
operator->() [1/2]
template<typename T> T * TDontCopy< T >::operator-> () inline
Definition at line 24 of file DontCopy.h.
References Value.
operator->() [2/2]
template<typename T> const T * TDontCopy< T >::operator-> () const inline
Definition at line 25 of file DontCopy.h.
References Value.
operator=() [1/2]
template<typename T> TDontCopy & TDontCopy< T >::operator= (const TDontCopy< T > &) inline
Definition at line 19 of file DontCopy.h.
References TDontCopy().
operator=() [2/2]
template<typename T> TDontCopy & TDontCopy< T >::operator= (TDontCopy< T > &&) inline
Definition at line 18 of file DontCopy.h.
References TDontCopy().
Field Documentation
Value
template<typename T> T TDontCopy< T >::Value private
Definition at line 31 of file DontCopy.h.
Referenced by Get(), Get(), operator*(), operator*(), operator->(), and operator->().
The documentation for this struct was generated from the following file:
Runtime/Core/Public/Templates/DontCopy.h