Unreal Engine 5.6 C++ API: UE::FDynamicallyTypedValue Struct Reference
UE::FDynamicallyTypedValue Struct Reference
#include "DynamicallyTypedValue.h"
Public Member Functions
FDynamicallyTypedValue ()
FDynamicallyTypedValue (const FDynamicallyTypedValue &Copyee)
FDynamicallyTypedValue (FDynamicallyTypedValue &&Movee)
~FDynamicallyTypedValue ()
void * GetDataPointer ()
const void * GetDataPointer () const
FDynamicallyTypedValueType & GetType () const
void InitializeAsType (FDynamicallyTypedValueType &NewType)
FDynamicallyTypedValue & operator= (const FDynamicallyTypedValue &Copyee)
FDynamicallyTypedValue & operator= (FDynamicallyTypedValue &&Movee)
void SetToNull ()
Static Public Member Functions
static FDynamicallyTypedValueType & NullType ()
Private Member Functions
void AllocateData ()
void Deinit ()
void FreeData ()
void InitializeFromCopy (const FDynamicallyTypedValue &Copyee)
void InitializeFromMove (FDynamicallyTypedValue &&Movee)
void InitializeToNull ()
bool IsInline () const
void MarkTypeReachableIfIncrementalReachabilityPending ()
Private Attributes
union {
void * HeapData
UPTRINT InlineData
};
FDynamicallyTypedValueType * Type
Friends
uint32 GetTypeHash (const FDynamicallyTypedValue &DynamicallyTypedValue)
Detailed Description
Definition at line 62 of file DynamicallyTypedValue.h.
Constructor & Destructor Documentation
FDynamicallyTypedValue() [1/3]
UE::FDynamicallyTypedValue::FDynamicallyTypedValue () inline
Definition at line 66 of file DynamicallyTypedValue.h.
References InitializeToNull().
Referenced by FDynamicallyTypedValue(), FDynamicallyTypedValue(), GetTypeHash, InitializeFromCopy(), InitializeFromMove(), operator=(), and operator=().
FDynamicallyTypedValue() [2/3]
UE::FDynamicallyTypedValue::FDynamicallyTypedValue (const FDynamicallyTypedValue & Copyee) inline
Definition at line 78 of file DynamicallyTypedValue.h.
References FDynamicallyTypedValue(), and InitializeFromCopy().
FDynamicallyTypedValue() [3/3]
UE::FDynamicallyTypedValue::FDynamicallyTypedValue (FDynamicallyTypedValue && Movee) inline
Definition at line 81 of file DynamicallyTypedValue.h.
References FDynamicallyTypedValue(), InitializeFromMove(), and MoveTemp().
~FDynamicallyTypedValue()
UE::FDynamicallyTypedValue::~FDynamicallyTypedValue () inline
Definition at line 83 of file DynamicallyTypedValue.h.
References Deinit().
Member Function Documentation
AllocateData()
void UE::FDynamicallyTypedValue::AllocateData () inline private
Definition at line 213 of file DynamicallyTypedValue.h.
References HeapData, InlineData, IsInline(), and Type.
Referenced by InitializeAsType(), and InitializeFromCopy().
Deinit()
void UE::FDynamicallyTypedValue::Deinit () inline private
Definition at line 177 of file DynamicallyTypedValue.h.
References FreeData(), GetDataPointer(), and Type.
Referenced by ~FDynamicallyTypedValue(), InitializeAsType(), operator=(), operator=(), and SetToNull().
FreeData()
void UE::FDynamicallyTypedValue::FreeData () inline private
Definition at line 228 of file DynamicallyTypedValue.h.
References FMemory::Free(), HeapData, InlineData, and IsInline().
Referenced by Deinit().
GetDataPointer() [1/2]
void * UE::FDynamicallyTypedValue::GetDataPointer () inline
Definition at line 106 of file DynamicallyTypedValue.h.
References HeapData, InlineData, and IsInline().
GetDataPointer() [2/2]
const void * UE::FDynamicallyTypedValue::GetDataPointer () const inline
Definition at line 105 of file DynamicallyTypedValue.h.
References HeapData, InlineData, and IsInline().
Referenced by Deinit(), InitializeAsType(), and InitializeFromCopy().
GetType()
FDynamicallyTypedValueType & UE::FDynamicallyTypedValue::GetType () const inline
Definition at line 109 of file DynamicallyTypedValue.h.
References Type.
InitializeAsType()
void UE::FDynamicallyTypedValue::InitializeAsType (FDynamicallyTypedValueType & NewType) inline
Definition at line 119 of file DynamicallyTypedValue.h.
References AllocateData(), check, Deinit(), GetDataPointer(), MarkTypeReachableIfIncrementalReachabilityPending(), and Type.
InitializeFromCopy()
void UE::FDynamicallyTypedValue::InitializeFromCopy (const FDynamicallyTypedValue & Copyee) inline private
Definition at line 184 of file DynamicallyTypedValue.h.
References FDynamicallyTypedValue(), AllocateData(), GetDataPointer(), MarkTypeReachableIfIncrementalReachabilityPending(), and Type.
Referenced by FDynamicallyTypedValue(), and operator=().
InitializeFromMove()
void UE::FDynamicallyTypedValue::InitializeFromMove (FDynamicallyTypedValue && Movee) inline private
Definition at line 193 of file DynamicallyTypedValue.h.
References FDynamicallyTypedValue(), InlineData, MarkTypeReachableIfIncrementalReachabilityPending(), and Type.
Referenced by FDynamicallyTypedValue(), and operator=().
InitializeToNull()
void UE::FDynamicallyTypedValue::InitializeToNull () inline private
Definition at line 170 of file DynamicallyTypedValue.h.
References HeapData, MarkTypeReachableIfIncrementalReachabilityPending(), NullType(), and Type.
Referenced by FDynamicallyTypedValue(), and SetToNull().
IsInline()
bool UE::FDynamicallyTypedValue::IsInline () const inline private
Definition at line 206 of file DynamicallyTypedValue.h.
References Type, and UE_FORCE_CONSTEVAL.
Referenced by AllocateData(), FreeData(), GetDataPointer(), and GetDataPointer().
MarkTypeReachableIfIncrementalReachabilityPending()
void UE::FDynamicallyTypedValue::MarkTypeReachableIfIncrementalReachabilityPending () inline private
Definition at line 136 of file DynamicallyTypedValue.h.
References UE::GC::GIsIncrementalReachabilityPending, UE::GC::MarkAsReachable(), and Type.
Referenced by InitializeAsType(), InitializeFromCopy(), InitializeFromMove(), and InitializeToNull().
NullType()
FDynamicallyTypedValueType & UE::FDynamicallyTypedValue::NullType () static
Referenced by InitializeToNull().
operator=() [1/2]
FDynamicallyTypedValue & UE::FDynamicallyTypedValue::operator= (const FDynamicallyTypedValue & Copyee) inline
Definition at line 85 of file DynamicallyTypedValue.h.
References FDynamicallyTypedValue(), Deinit(), and InitializeFromCopy().
operator=() [2/2]
FDynamicallyTypedValue & UE::FDynamicallyTypedValue::operator= (FDynamicallyTypedValue && Movee) inline
Definition at line 94 of file DynamicallyTypedValue.h.
References FDynamicallyTypedValue(), Deinit(), InitializeFromMove(), and MoveTemp().
SetToNull()
void UE::FDynamicallyTypedValue::SetToNull () inline
Definition at line 112 of file DynamicallyTypedValue.h.
References Deinit(), and InitializeToNull().
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FDynamicallyTypedValue & DynamicallyTypedValue) friend
Definition at line 130 of file DynamicallyTypedValue.h.
References FDynamicallyTypedValue().
Field Documentation
[union]
union { ... } UE::FDynamicallyTypedValue
HeapData
void* UE::FDynamicallyTypedValue::HeapData
Definition at line 166 of file DynamicallyTypedValue.h.
Referenced by AllocateData(), FreeData(), GetDataPointer(), GetDataPointer(), and InitializeToNull().
InlineData
UPTRINT UE::FDynamicallyTypedValue::InlineData
Definition at line 165 of file DynamicallyTypedValue.h.
Referenced by AllocateData(), FreeData(), GetDataPointer(), GetDataPointer(), and InitializeFromMove().
Type
FDynamicallyTypedValueType* UE::FDynamicallyTypedValue::Type private
Definition at line 160 of file DynamicallyTypedValue.h.
Referenced by AllocateData(), Deinit(), GetType(), InitializeAsType(), InitializeFromCopy(), InitializeFromMove(), InitializeToNull(), IsInline(), and MarkTypeReachableIfIncrementalReachabilityPending().
The documentation for this struct was generated from the following file:
Runtime/CoreUObject/Public/UObject/DynamicallyTypedValue.h