Unreal Engine 5.6 C++ API: Metasound::MetasoundExecutableOperatorPrivate::TPostExecuteFunctionAdapter< OperatorType > Struct Template Reference
Metasound::MetasoundExecutableOperatorPrivate::TPostExecuteFunctionAdapter< OperatorType > Struct Template Reference
#include "MetasoundExecutableOperator.h"
Static Public Member Functions
static IOperator::FPostExecuteFunction GetPostExecuteFunction ()
Static Private Member Functions
static void PostExecuteFunction (IOperator *InOperator)
Detailed Description
template<typename OperatorType>
struct Metasound::MetasoundExecutableOperatorPrivate::TPostExecuteFunctionAdapter< OperatorType >
Definition at line 104 of file MetasoundExecutableOperator.h.
Member Function Documentation
GetPostExecuteFunction()
template<typename OperatorType> IOperator::FPostExecuteFunction Metasound::MetasoundExecutableOperatorPrivate::TPostExecuteFunctionAdapter< OperatorType >::GetPostExecuteFunction () inline static
Definition at line 108 of file MetasoundExecutableOperator.h.
References PostExecuteFunction(), and Metasound::MetasoundExecutableOperatorPrivate::TIsPostExecuteMethodDeclared< U >::Value.
Referenced by Metasound::TExecutableOperator< DerivedOperatorType >::GetPostExecuteFunction().
PostExecuteFunction()
template<typename OperatorType> void Metasound::MetasoundExecutableOperatorPrivate::TPostExecuteFunctionAdapter< OperatorType >::PostExecuteFunction (IOperator * InOperator) inline static private
Definition at line 121 of file MetasoundExecutableOperator.h.
References check, checkNoEntry, and Metasound::MetasoundExecutableOperatorPrivate::TIsPostExecuteMethodDeclared< U >::Value.
Referenced by GetPostExecuteFunction().
The documentation for this struct was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/Metasound/Source/MetasoundGraphCore/Public/MetasoundExecutableOperator.h