Unreal Engine 5.6 C++ API: FBoneContainer Struct Reference
FBoneContainer Struct Reference
This is a native transient structure.
#include "BoneContainer.h"
Data Structures
struct FRangedForReverseSupport
struct FRangedForSupport
Public Member Functions
FBoneContainer ()
FBoneContainer (const TArrayView< const FBoneIndexType > &InRequiredBoneIndexArray, const UE::Anim::FCurveFilterSettings &InCurveFilterSettings, UObject &InAsset)
bool BoneIsChildOf (const FCompactPoseBoneIndex &BoneIndex, const FCompactPoseBoneIndex &ParentBoneIndex) const
Returns true if bone is child of for current asset.
bool BoneIsChildOf (const int32 BoneIndex, const int32 ParentBoneIndex) const
Returns true if bone is child of for current asset.
void CacheRequiredAnimCurves (const UE::Anim::FCurveFilterSettings &InCurveFilterSettings)
Cache required Anim Curves.
bool Contains (FBoneIndexType NewIndex) const
Returns true of RequiredBonesArray contains this bone index.
template<typename ArrayType>
void FillWithCompactRefPose (ArrayType &OutTransforms) const
FORCEINLINE FRangedForSupport< FCompactPoseBoneIndexIterator > ForEachCompactPoseBoneIndex () const
FORCEINLINE FRangedForReverseSupport< FCompactPoseBoneIndexReverseIterator > ForEachCompactPoseBoneIndexReverse () const
UObject * GetAsset () const
Get Asset this BoneContainer was made for.
const TArray< FBoneIndexType > & GetBoneIndicesArray () const
Returns array of the size of compact pose, mapping to mesh pose index returns Required Bone Indices Array.
const TBitArray & GetBoneSwitchArray () const
returns Bone Switch Array.
FCompactPoseBoneIndex GetCompactPoseIndexFromSkeletonIndex (const int32 SkeletonIndex) const
FCompactPoseBoneIndex GetCompactPoseIndexFromSkeletonPoseIndex (const FSkeletonPoseBoneIndex &SkeletonIndex) const
Map skeleton bone index to compact pose index.
const int32 GetCompactPoseNumBones () const
const TArray< FCompactPoseBoneIndex > & GetCompactPoseParentBoneArray () const
const UE::Anim::FCurveFilter & GetCurveFilter () const
Get filter used for filtering by LOD/bone.
const UE::Anim::FBulkCurveFlags & GetCurveFlags () const
Get flags to apply to curves (built from metadata)
int32 GetDepthBetweenBones (const int32 BoneIndex, const int32 ParentBoneIndex) const
Get Depth between bones for current asset.
bool GetDisableRetargeting () const
True if retargeting is disabled for debugging.
FMeshPoseBoneIndex GetMeshPoseIndexFromSkeletonPoseIndex (const FSkeletonPoseBoneIndex &SkeletonIndex) const
Map skeleton bone index to mesh index.
const int32 GetNumBones () const
Number of Bones in RefPose for current asset.
const FCachedSkeletonCurveMapping & GetOrCreateCachedCurveMapping (const FSkeletonRemapping *SkeletonRemapping)
FCompactPoseBoneIndex GetParentBoneIndex (const FCompactPoseBoneIndex &BoneIndex) const
Get ParentBoneIndex for current Asset.
int32 GetParentBoneIndex (const int32 BoneIndex) const
Get ParentBoneIndex for current Asset.
int32 GetPoseBoneIndexForBoneName (const FName &BoneName) const
Get BoneIndex for BoneName for current Asset.
const FReferenceSkeleton & GetReferenceSkeleton () const
Access to Asset's RefSkeleton.
const TArray< FTransform > & GetRefPoseArray () const
Pointer to RefPoseArray for current Asset.
const FTransform & GetRefPoseTransform (const FCompactPoseBoneIndex &BoneIndex) const
const FRetargetSourceCachedData & GetRetargetSourceCachedData (const FName &InRetargetSource) const
const FRetargetSourceCachedData & GetRetargetSourceCachedData (const FName &InSourceName, const FSkeletonRemapping &InRemapping, const TArray< FTransform > &InRetargetTransforms) const
uint16 GetSerialNumber () const
USkeletalMesh * GetSkeletalMeshAsset () const
Get SkeletalMesh Asset this BoneContainer was made for.
USkeleton * GetSkeletonAsset (bool bEvenIfUnreachable=false) const
Get Skeleton Asset.
int32 GetSkeletonIndex (const FCompactPoseBoneIndex &BoneIndex) const
FSkeletonPoseBoneIndex GetSkeletonPoseIndexFromCompactPoseIndex (const FCompactPoseBoneIndex &BoneIndex) const
Map compact bone index to skeleton index.
FSkeletonPoseBoneIndex GetSkeletonPoseIndexFromMeshPoseIndex (const FMeshPoseBoneIndex &MeshIndex) const
Map mesh bone index to skeleton index.
const TArray< FVirtualBoneCompactPoseData > & GetVirtualBoneCompactPoseData () const
returns virutal bone cached data
void InitializeTo (const TArrayView< const FBoneIndexType > &InRequiredBoneIndexArray, const UE::Anim::FCurveFilterSettings &InCurveFilterSettings, const UObject &InAsset)
bool IsSkeletonPoseIndexValid (const FSkeletonPoseBoneIndex &SkeletonIndex) const
Returns whether or not the skeleton index is contained in the mapping used to build this container.
const bool IsValid () const
Returns true if FBoneContainer is Valid.
FORCEINLINE FCompactPoseBoneIndexIterator MakeBeginIter () const
FORCEINLINE FCompactPoseBoneIndexReverseIterator MakeBeginIterReverse () const
FCompactPoseBoneIndex MakeCompactPoseIndex (const FMeshPoseBoneIndex &BoneIndex) const
FORCEINLINE FCompactPoseBoneIndexIterator MakeEndIter () const
FORCEINLINE FCompactPoseBoneIndexReverseIterator MakeEndIterReverse () const
FMeshPoseBoneIndex MakeMeshPoseIndex (const FCompactPoseBoneIndex &BoneIndex) const
void MarkAllCachedCurveMappingsDirty ()
void Reset ()
Resets the container and reclaims all allocated memory but preserve the serial number.
void SetDisableRetargeting (bool InbDisableRetargeting)
Disable Retargeting for debugging.
void SetRefPoseOverride (const TSharedPtr< FSkelMeshRefPoseOverride > &InRefPoseOverride)
Override skeleton ref pose.
void SetUseRAWData (bool InbUseRAWData)
Ignore compressed data and use RAW data instead, for debugging.
void SetUseSourceData (bool InbUseSourceData)
use Source data instead.
bool ShouldUseRawData () const
True if we're requesting RAW data instead of compressed data.
bool ShouldUseSourceData () const
True if we're requesting Source data instead of RawAnimationData.
UE_DEPRECATED (5.0, "GetUIDToCurveTypeLookupTable is deprecated, please access from the SmartNameMapping directly via GetSkeletonAsset()->GetSmartNameContainer(USkeleton::AnimCurveMappingName)") 1 TArray< FAnimCurveType > const &GetUIDToCurveTypeLookupTable() const
UE_DEPRECATED (5.0, "GetUIDToNameLookupTable is deprecated, please access from the SmartNameMapping directly via GetSkeletonAsset()->GetSmartNameContainer(USkeleton::AnimCurveMappingName)") TArray< FName > const &GetUIDToNameLookupTable() const
UE_DEPRECATED (5.0, "Please use GetMeshPoseIndexFromSkeletonPoseIndex") TArray< int32 > const &GetSkeletonToPoseBoneIndexArray() const
Const accessor to SkeletonToPoseBoneIndexArray.
UE_DEPRECATED (5.0, "Please use GetSkeletonPoseIndexFromMeshPoseIndex") TArray< int32 > const &GetPoseToSkeletonBoneIndexArray() const
Const accessor to PoseToSkeletonBoneIndexArray.
UE_DEPRECATED (5.3, "GetUIDToArrayIndexLookupTableValidCount is deprecated, it is no longer used.") 1 int32 GetUIDToArrayIndexLookupTableValidCount() const
UE_DEPRECATED (5.3, "GetUIDToArrayLookupTable is deprecated, it is no longer used.") 1 TArray< uint16 > const &GetUIDToArrayLookupTable() const
UE_DEPRECATED (5.3, "Please use CacheRequiredAnimCurves with a FCurveFilterSettings.") void CacheRequiredAnimCurveUids(const FCurveEvaluationOption &CurveEvalOption)
UE_DEPRECATED (5.3, "Please use InitializeTo that takes a FCurveFilterSettings.") 1 void InitializeTo(const TArrayView< const FBoneIndexType > &InRequiredBoneIndexArray
UE_DEPRECATED (5.3, "Please use the constructor that takes a FCurveFilterSettings.") 1 FBoneContainer(const TArrayView< const FBoneIndexType > &InRequiredBoneIndexArray
Data Fields
const FCurveEvaluationOption & CurveEvalOption
const FCurveEvaluationOption UObject & InAsset
const FCurveEvaluationOption const UObject & InAsset
Private Member Functions
void Initialize (const UE::Anim::FCurveFilterSettings &CurveFilterSettings)
Initialize FBoneContainer.
void RegenerateSerialNumber ()
void RemapFromSkeleton (USkeleton const &SourceSkeleton)
Cache remapping data if current Asset is a Skeleton, with all compatible Skeletons.
void RemapFromSkelMesh (USkeletalMesh const &SourceSkeletalMesh, USkeleton &TargetSkeleton)
Cache remapping data if current Asset is a SkeletalMesh, with all compatible Skeletons.
Private Attributes
TWeakObjectPtr< UObject > Asset
Asset BoneIndicesArray was made for.
TWeakObjectPtr< USkeletalMesh > AssetSkeletalMesh
If Asset is a SkeletalMesh, this will be a pointer to it.
TWeakObjectPtr< USkeleton > AssetSkeleton
If Asset is a Skeleton that will be it.
bool bDisableRetargeting
For debugging.
TArray< FBoneIndexType > BoneIndicesArray
Array of RequiredBonesIndices.
TBitArray BoneSwitchArray
Array sized by Current RefPose.
bool bUseRAWData
Disable animation compression, use RAW data instead.
bool bUseSourceData
Use Source Data that is imported that are not compressed.
TArray< FCompactPoseBoneIndex > CompactPoseParentBones
TArray< int32 > CompactPoseToSkeletonIndex
UE::Anim::FCurveFilter CurveFilter
Curve used for filtering by LOD/bone.
UE::Anim::FBulkCurveFlags CurveFlags
Curve flags to apply (built from curve metadata)
TArray< int32 > PoseToSkeletonBoneIndexArray
Mapping table between Pose Bone Indices and Skeleton Bone Indices.
TSharedPtr< FSkelMeshRefPoseOverride > RefPoseOverride
const FReferenceSkeleton * RefSkeleton
Pointer to RefSkeleton of Asset.
TMap< FRetargetSourceCachedDataKey, FRetargetSourceCachedData > RetargetSourceCachedDataLUT
Runtime cached data for retargeting from a specific RetargetSource to this current SkelMesh LOD.
uint16 SerialNumber
TArray< FCompactPoseBoneIndex > SkeletonToCompactPose
TArray< int32 > SkeletonToPoseBoneIndexArray
Mapping table between Skeleton Bone Indices and Pose Bone Indices.
TArray< FVirtualBoneCompactPoseData > VirtualBoneCompactPoseData
Friends
UE_DEPRECATED(5.3, "GetUIDToArrayLookupTableBackup is deprecated, it is no longer used.") 1 TArray< SmartName friend FArchive & operator<< (FArchive &Ar, FBoneContainer &B)
Serializes the bones.
Detailed Description
This is a native transient structure.
Contains:
BoneIndicesArray: Array of RequiredBoneIndices for Current Asset. In increasing order. Mapping to current Array of Transforms (Pose).
BoneSwitchArray: Size of current Skeleton. true if Bone is contained in RequiredBones array, false otherwise.
Definition at line 191 of file BoneContainer.h.
Constructor & Destructor Documentation
FBoneContainer() [1/2]
FBoneContainer::FBoneContainer ()
Referenced by FBoneContainer::FRangedForReverseSupport< IterType >::FRangedForReverseSupport(), FBoneContainer::FRangedForSupport< IterType >::FRangedForSupport(), and operator<<.
FBoneContainer() [2/2]
FBoneContainer::FBoneContainer (const TArrayView< const FBoneIndexType > & InRequiredBoneIndexArray, const UE::Anim::FCurveFilterSettings & InCurveFilterSettings, UObject & InAsset)
References InAsset.
Member Function Documentation
BoneIsChildOf() [1/2]
bool FBoneContainer::BoneIsChildOf (const FCompactPoseBoneIndex & BoneIndex, const FCompactPoseBoneIndex & ParentBoneIndex) const
Returns true if bone is child of for current asset.
BoneIsChildOf() [2/2]
bool FBoneContainer::BoneIsChildOf (const int32 BoneIndex, const int32 ParentBoneIndex) const
Returns true if bone is child of for current asset.
CacheRequiredAnimCurves()
void FBoneContainer::CacheRequiredAnimCurves (const UE::Anim::FCurveFilterSettings & InCurveFilterSettings)
Cache required Anim Curves.
Referenced by UE_DEPRECATED().
Contains()
bool FBoneContainer::Contains (FBoneIndexType NewIndex) const inline
Returns true of RequiredBonesArray contains this bone index.
Definition at line 496 of file BoneContainer.h.
References BoneSwitchArray.
FillWithCompactRefPose()
template<typename ArrayType> void FBoneContainer::FillWithCompactRefPose (ArrayType & OutTransforms) const inline
Definition at line 373 of file BoneContainer.h.
References BoneIndicesArray, GetCompactPoseNumBones(), RefPoseOverride, and RefSkeleton.
Referenced by FBaseCompactPose< InAllocator >::ResetToRefPose().
ForEachCompactPoseBoneIndex()
FORCEINLINE FRangedForSupport< FCompactPoseBoneIndexIterator > FBoneContainer::ForEachCompactPoseBoneIndex () const inline
Definition at line 537 of file BoneContainer.h.
References FORCEINLINE.
ForEachCompactPoseBoneIndexReverse()
FORCEINLINE FRangedForReverseSupport< FCompactPoseBoneIndexReverseIterator > FBoneContainer::ForEachCompactPoseBoneIndexReverse () const inline
Definition at line 541 of file BoneContainer.h.
References FORCEINLINE.
GetAsset()
UObject * FBoneContainer::GetAsset () const inline
Get Asset this BoneContainer was made for.
Typically a SkeletalMesh, but could also be a USkeleton.
Definition at line 281 of file BoneContainer.h.
References Asset.
GetBoneIndicesArray()
const TArray< FBoneIndexType > & FBoneContainer::GetBoneIndicesArray () const inline
Returns array of the size of compact pose, mapping to mesh pose index returns Required Bone Indices Array.
Definition at line 342 of file BoneContainer.h.
References BoneIndicesArray.
Referenced by MakeCompactPoseIndex(), UE::Anim::Conversion::MakeIndex(), and MakeMeshPoseIndex().
GetBoneSwitchArray()
const TBitArray & FBoneContainer::GetBoneSwitchArray () const inline
returns Bone Switch Array.
BitMask for RequiredBoneIndex array.
Definition at line 355 of file BoneContainer.h.
References BoneSwitchArray.
GetCompactPoseIndexFromSkeletonIndex()
FCompactPoseBoneIndex FBoneContainer::GetCompactPoseIndexFromSkeletonIndex (const int32 SkeletonIndex) const inline
Definition at line 614 of file BoneContainer.h.
References ensure, INDEX_NONE, and SkeletonToCompactPose.
GetCompactPoseIndexFromSkeletonPoseIndex()
FCompactPoseBoneIndex FBoneContainer::GetCompactPoseIndexFromSkeletonPoseIndex (const FSkeletonPoseBoneIndex & SkeletonIndex) const inline
Map skeleton bone index to compact pose index.
Returns
the compact pose bone index for the specified skeleton pose bone index. Returns an invalid index if the compact pose does not include the specified skeleton bone.
Definition at line 629 of file BoneContainer.h.
References INDEX_NONE, and SkeletonToCompactPose.
GetCompactPoseNumBones()
const int32 FBoneContainer::GetCompactPoseNumBones () const inline
Definition at line 413 of file BoneContainer.h.
References BoneIndicesArray.
Referenced by FillWithCompactRefPose(), MakeBeginIterReverse(), and MakeEndIter().
GetCompactPoseParentBoneArray()
const TArray< FCompactPoseBoneIndex > & FBoneContainer::GetCompactPoseParentBoneArray () const inline
Definition at line 366 of file BoneContainer.h.
References CompactPoseParentBones.
GetCurveFilter()
const UE::Anim::FCurveFilter & FBoneContainer::GetCurveFilter () const inline
Get filter used for filtering by LOD/bone.
Definition at line 437 of file BoneContainer.h.
References CurveFilter.
GetCurveFlags()
const UE::Anim::FBulkCurveFlags & FBoneContainer::GetCurveFlags () const inline
Get flags to apply to curves (built from metadata)
Definition at line 443 of file BoneContainer.h.
References CurveFlags.
GetDepthBetweenBones()
int32 FBoneContainer::GetDepthBetweenBones (const int32 BoneIndex, const int32 ParentBoneIndex) const
Get Depth between bones for current asset.
GetDisableRetargeting()
bool FBoneContainer::GetDisableRetargeting () const inline
True if retargeting is disabled for debugging.
Definition at line 309 of file BoneContainer.h.
References bDisableRetargeting.
Referenced by FBaseCompactPose< InAllocator >::ResetToRefPose().
GetMeshPoseIndexFromSkeletonPoseIndex()
FMeshPoseBoneIndex FBoneContainer::GetMeshPoseIndexFromSkeletonPoseIndex (const FSkeletonPoseBoneIndex & SkeletonIndex) const inline
Map skeleton bone index to mesh index.
Returns
the mesh pose bone index for the specified skeleton pose bone index. Returns an invalid index if the mesh does not include the specified skeleton bone.
Definition at line 567 of file BoneContainer.h.
References INDEX_NONE, and SkeletonToPoseBoneIndexArray.
GetNumBones()
const int32 FBoneContainer::GetNumBones () const inline
Number of Bones in RefPose for current asset.
This is NOT the number of bones in RequiredBonesArray, but the TOTAL number of bones in the RefPose of the current Asset!
Definition at line 408 of file BoneContainer.h.
References RefSkeleton.
GetOrCreateCachedCurveMapping()
const FCachedSkeletonCurveMapping & FBoneContainer::GetOrCreateCachedCurveMapping (const FSkeletonRemapping * SkeletonRemapping)
GetParentBoneIndex() [1/2]
FCompactPoseBoneIndex FBoneContainer::GetParentBoneIndex (const FCompactPoseBoneIndex & BoneIndex) const
Get ParentBoneIndex for current Asset.
GetParentBoneIndex() [2/2]
int32 FBoneContainer::GetParentBoneIndex (const int32 BoneIndex) const
Get ParentBoneIndex for current Asset.
Referenced by FBaseCompactPose< InAllocator >::GetParentBoneIndex().
GetPoseBoneIndexForBoneName()
int32 FBoneContainer::GetPoseBoneIndexForBoneName (const FName & BoneName) const
Get BoneIndex for BoneName for current Asset.
GetReferenceSkeleton()
const FReferenceSkeleton & FBoneContainer::GetReferenceSkeleton () const inline
Access to Asset's RefSkeleton.
Definition at line 402 of file BoneContainer.h.
References RefSkeleton.
GetRefPoseArray()
const TArray< FTransform > & FBoneContainer::GetRefPoseArray () const inline
Pointer to RefPoseArray for current Asset.
Definition at line 361 of file BoneContainer.h.
References RefSkeleton.
Referenced by FRootMotionReset::ResetRootBoneForRootMotion().
GetRefPoseTransform()
const FTransform & FBoneContainer::GetRefPoseTransform (const FCompactPoseBoneIndex & BoneIndex) const inline
Definition at line 386 of file BoneContainer.h.
References BoneIndicesArray, RefPoseOverride, and RefSkeleton.
Referenced by FBaseCompactPose< InAllocator >::GetRefPose().
GetRetargetSourceCachedData() [1/2]
const FRetargetSourceCachedData & FBoneContainer::GetRetargetSourceCachedData (const FName & InRetargetSource) const
GetRetargetSourceCachedData() [2/2]
const FRetargetSourceCachedData & FBoneContainer::GetRetargetSourceCachedData (const FName & InSourceName, const FSkeletonRemapping & InRemapping, const TArray< FTransform > & InRetargetTransforms) const
GetSerialNumber()
uint16 FBoneContainer::GetSerialNumber () const inline
Definition at line 682 of file BoneContainer.h.
References SerialNumber.
GetSkeletalMeshAsset()
USkeletalMesh * FBoneContainer::GetSkeletalMeshAsset () const inline
Get SkeletalMesh Asset this BoneContainer was made for.
Could be NULL if Asset is a Skeleton.
Definition at line 287 of file BoneContainer.h.
References AssetSkeletalMesh.
Referenced by FBaseCompactPose< InAllocator >::ResetToRefPose().
GetSkeletonAsset()
USkeleton * FBoneContainer::GetSkeletonAsset (bool bEvenIfUnreachable = false) const inline
Get Skeleton Asset.
Could either be the SkeletalMesh's Skeleton, or the Skeleton this BoneContainer was made for. Is non NULL is BoneContainer is valid.
Definition at line 293 of file BoneContainer.h.
References AssetSkeleton.
Referenced by FBaseCompactPose< InAllocator >::ResetToRefPose().
GetSkeletonIndex()
int32 FBoneContainer::GetSkeletonIndex (const FCompactPoseBoneIndex & BoneIndex) const inline
Definition at line 593 of file BoneContainer.h.
References CompactPoseToSkeletonIndex.
Referenced by FBaseCompactPose< InAllocator >::ResetToRefPose().
GetSkeletonPoseIndexFromCompactPoseIndex()
FSkeletonPoseBoneIndex FBoneContainer::GetSkeletonPoseIndexFromCompactPoseIndex (const FCompactPoseBoneIndex & BoneIndex) const inline
Map compact bone index to skeleton index.
Returns
the skeleton pose bone index for the specified compact pose bone index. Ensures and returns an invalid index if the skeleton does not include the specified compact pose bone.
Definition at line 603 of file BoneContainer.h.
References CompactPoseToSkeletonIndex, ensure, and INDEX_NONE.
GetSkeletonPoseIndexFromMeshPoseIndex()
FSkeletonPoseBoneIndex FBoneContainer::GetSkeletonPoseIndexFromMeshPoseIndex (const FMeshPoseBoneIndex & MeshIndex) const inline
Map mesh bone index to skeleton index.
Returns
the skeleton pose bone index for the specified mesh pose bone index. Ensures and returns an invalid index if the skeleton does not include the specified mesh bone.
Definition at line 582 of file BoneContainer.h.
References ensure, INDEX_NONE, and PoseToSkeletonBoneIndexArray.
GetVirtualBoneCompactPoseData()
const TArray< FVirtualBoneCompactPoseData > & FBoneContainer::GetVirtualBoneCompactPoseData () const inline
returns virutal bone cached data
Definition at line 350 of file BoneContainer.h.
References VirtualBoneCompactPoseData.
Initialize()
void FBoneContainer::Initialize (const UE::Anim::FCurveFilterSettings & CurveFilterSettings) private
Initialize FBoneContainer.
InitializeTo()
void FBoneContainer::InitializeTo (const TArrayView< const FBoneIndexType > & InRequiredBoneIndexArray, const UE::Anim::FCurveFilterSettings & InCurveFilterSettings, const UObject & InAsset)
References InAsset.
IsSkeletonPoseIndexValid()
bool FBoneContainer::IsSkeletonPoseIndexValid (const FSkeletonPoseBoneIndex & SkeletonIndex) const inline
Returns whether or not the skeleton index is contained in the mapping used to build this container.
Note that even if the skeleton index is valid, it might not contain a valid compact pose index if that bone isn't used due to LOD or other reasons.
Definition at line 644 of file BoneContainer.h.
References SkeletonToCompactPose.
IsValid()
const bool FBoneContainer::IsValid () const inline
Returns true if FBoneContainer is Valid.
Needs an Asset, a RefPoseArray, and a RequiredBonesArray.
Definition at line 270 of file BoneContainer.h.
References Asset, BoneIndicesArray, IsValid(), and RefSkeleton.
Referenced by FPoseContext::FPoseContext(), IsValid(), FBaseCompactPose< InAllocator >::ResetToRefPose(), FBaseCompactPose< InAllocator >::SetBoneContainer(), and FMeshPose::SetBoneContainer().
MakeBeginIter()
FORCEINLINE FCompactPoseBoneIndexIterator FBoneContainer::MakeBeginIter () const inline
Definition at line 545 of file BoneContainer.h.
References FORCEINLINE.
MakeBeginIterReverse()
FORCEINLINE FCompactPoseBoneIndexReverseIterator FBoneContainer::MakeBeginIterReverse () const inline
Definition at line 553 of file BoneContainer.h.
References FORCEINLINE, and GetCompactPoseNumBones().
MakeCompactPoseIndex()
FCompactPoseBoneIndex FBoneContainer::MakeCompactPoseIndex (const FMeshPoseBoneIndex & BoneIndex) const inline
Definition at line 654 of file BoneContainer.h.
References GetBoneIndicesArray().
Referenced by UE::Anim::Conversion::MakeIndex().
MakeEndIter()
FORCEINLINE FCompactPoseBoneIndexIterator FBoneContainer::MakeEndIter () const inline
Definition at line 549 of file BoneContainer.h.
References FORCEINLINE, and GetCompactPoseNumBones().
MakeEndIterReverse()
FORCEINLINE FCompactPoseBoneIndexReverseIterator FBoneContainer::MakeEndIterReverse () const inline
Definition at line 557 of file BoneContainer.h.
References FORCEINLINE.
MakeMeshPoseIndex()
FMeshPoseBoneIndex FBoneContainer::MakeMeshPoseIndex (const FCompactPoseBoneIndex & BoneIndex) const inline
Definition at line 649 of file BoneContainer.h.
References GetBoneIndicesArray().
Referenced by UE::Anim::Conversion::MakeIndex().
MarkAllCachedCurveMappingsDirty()
void FBoneContainer::MarkAllCachedCurveMappingsDirty ()
RegenerateSerialNumber()
void FBoneContainer::RegenerateSerialNumber () private
RemapFromSkeleton()
void FBoneContainer::RemapFromSkeleton (USkeleton const & SourceSkeleton) private
Cache remapping data if current Asset is a Skeleton, with all compatible Skeletons.
References SourceSkeleton.
RemapFromSkelMesh()
void FBoneContainer::RemapFromSkelMesh (USkeletalMesh const & SourceSkeletalMesh, USkeleton & TargetSkeleton) private
Cache remapping data if current Asset is a SkeletalMesh, with all compatible Skeletons.
Reset()
void FBoneContainer::Reset ()
Resets the container and reclaims all allocated memory but preserve the serial number.
References Reset().
Referenced by Reset().
SetDisableRetargeting()
void FBoneContainer::SetDisableRetargeting (bool InbDisableRetargeting) inline
Disable Retargeting for debugging.
Definition at line 303 of file BoneContainer.h.
References bDisableRetargeting.
SetRefPoseOverride()
void FBoneContainer::SetRefPoseOverride (const TSharedPtr< FSkelMeshRefPoseOverride > & InRefPoseOverride) inline
Override skeleton ref pose.
Definition at line 393 of file BoneContainer.h.
References TSharedPtr< ObjectType, InMode >::Get(), and RefPoseOverride.
SetUseRAWData()
void FBoneContainer::SetUseRAWData (bool InbUseRAWData) inline
Ignore compressed data and use RAW data instead, for debugging.
Definition at line 315 of file BoneContainer.h.
References bUseRAWData.
SetUseSourceData()
void FBoneContainer::SetUseSourceData (bool InbUseSourceData) inline
use Source data instead.
Definition at line 327 of file BoneContainer.h.
References bUseSourceData.
ShouldUseRawData()
bool FBoneContainer::ShouldUseRawData () const inline
True if we're requesting RAW data instead of compressed data.
For debugging.
Definition at line 321 of file BoneContainer.h.
References bUseRAWData.
ShouldUseSourceData()
bool FBoneContainer::ShouldUseSourceData () const inline
True if we're requesting Source data instead of RawAnimationData.
For debugging.
Definition at line 333 of file BoneContainer.h.
References bUseSourceData.
UE_DEPRECATED() [1/9]
FBoneContainer::UE_DEPRECATED (5. 0, "GetUIDToCurveTypeLookupTable is deprecated, please access from the SmartNameMapping directly via GetSkeletonAsset() ->GetSmartNameContainer(USkeleton::AnimCurveMappingName)") const &
References UE_DEPRECATED().
UE_DEPRECATED() [2/9]
FBoneContainer::UE_DEPRECATED (5. 0, "GetUIDToNameLookupTable is deprecated, please access from the SmartNameMapping directly via GetSkeletonAsset() ->GetSmartNameContainer(USkeleton::AnimCurveMappingName)") const & inline
Definition at line 454 of file BoneContainer.h.
References UE_DEPRECATED().
UE_DEPRECATED() [3/9]
FBoneContainer::UE_DEPRECATED (5. 0, "Please use GetMeshPoseIndexFromSkeletonPoseIndex") const & inline
Const accessor to SkeletonToPoseBoneIndexArray.
Definition at line 502 of file BoneContainer.h.
References SkeletonToPoseBoneIndexArray.
UE_DEPRECATED() [4/9]
FBoneContainer::UE_DEPRECATED (5. 0, "Please use GetSkeletonPoseIndexFromMeshPoseIndex") const & inline
Const accessor to PoseToSkeletonBoneIndexArray.
Definition at line 509 of file BoneContainer.h.
References PoseToSkeletonBoneIndexArray.
UE_DEPRECATED() [5/9]
FBoneContainer::UE_DEPRECATED (5. 3, "GetUIDToArrayIndexLookupTableValidCount is deprecated, it is no longer used.") const
References UE_DEPRECATED().
UE_DEPRECATED() [6/9]
FBoneContainer::UE_DEPRECATED (5. 3, "GetUIDToArrayLookupTable is deprecated, it is no longer used.") const &
UE_DEPRECATED() [7/9]
FBoneContainer::UE_DEPRECATED (5. 3, "Please use CacheRequiredAnimCurves with a FCurveFilterSettings.") const & inline
Definition at line 659 of file BoneContainer.h.
References CacheRequiredAnimCurves(), CurveEvalOption, UE::Anim::DisallowAll, and UE::Anim::None.
UE_DEPRECATED() [8/9]
FBoneContainer::UE_DEPRECATED (5. 3, "Please use InitializeTo that takes a FCurveFilterSettings.") const &
References UE_DEPRECATED().
UE_DEPRECATED() [9/9]
FBoneContainer::UE_DEPRECATED (5. 3, "Please use the constructor that takes a FCurveFilterSettings.") const &
Referenced by UE_DEPRECATED(), UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
Friends And Related Symbol Documentation
operator<<
UE_DEPRECATED(5.3, "GetUIDToArrayLookupTableBackup is deprecated, it is no longer used.") 1 TArray< SmartName friend FArchive & operator<< (FArchive & Ar, FBoneContainer & B) friend
Serializes the bones.
Parameters
Ar - The archive to serialize into.
Rect - The bone container to serialize.
Returns
Reference to the Archive after serialization.
Definition at line 475 of file BoneContainer.h.
References FBoneContainer(), Ar, and B.
Field Documentation
Asset
TWeakObjectPtr<UObject> FBoneContainer::Asset private
Asset BoneIndicesArray was made for.
Typically a SkeletalMesh.
Definition at line 200 of file BoneContainer.h.
Referenced by GetAsset(), and IsValid().
AssetSkeletalMesh
TWeakObjectPtr<USkeletalMesh> FBoneContainer::AssetSkeletalMesh private
If Asset is a SkeletalMesh, this will be a pointer to it.
Can be NULL if Asset is a USkeleton.
Definition at line 202 of file BoneContainer.h.
Referenced by GetSkeletalMeshAsset().
AssetSkeleton
TWeakObjectPtr<USkeleton> FBoneContainer::AssetSkeleton private
If Asset is a Skeleton that will be it.
If Asset is a SkeletalMesh, that will be its Skeleton.
Definition at line 204 of file BoneContainer.h.
Referenced by GetSkeletonAsset().
bDisableRetargeting
bool FBoneContainer::bDisableRetargeting private
For debugging.
Disable Retargeting. Extract animation, but do not retarget it.
Definition at line 246 of file BoneContainer.h.
Referenced by GetDisableRetargeting(), and SetDisableRetargeting().
BoneIndicesArray
TArray<FBoneIndexType> FBoneContainer::BoneIndicesArray private
Array of RequiredBonesIndices.
In increasing order.
Definition at line 195 of file BoneContainer.h.
Referenced by FillWithCompactRefPose(), GetBoneIndicesArray(), GetCompactPoseNumBones(), GetRefPoseTransform(), and IsValid().
BoneSwitchArray
TBitArray FBoneContainer::BoneSwitchArray private
Array sized by Current RefPose.
true if Bone is contained in RequiredBones array, false otherwise.
Definition at line 197 of file BoneContainer.h.
Referenced by Contains(), and GetBoneSwitchArray().
bUseRAWData
bool FBoneContainer::bUseRAWData private
Disable animation compression, use RAW data instead.
Definition at line 248 of file BoneContainer.h.
Referenced by SetUseRAWData(), and ShouldUseRawData().
bUseSourceData
bool FBoneContainer::bUseSourceData private
Use Source Data that is imported that are not compressed.
Definition at line 250 of file BoneContainer.h.
Referenced by SetUseSourceData(), and ShouldUseSourceData().
CompactPoseParentBones
TArray<FCompactPoseBoneIndex> FBoneContainer::CompactPoseParentBones private
Definition at line 222 of file BoneContainer.h.
Referenced by GetCompactPoseParentBoneArray().
CompactPoseToSkeletonIndex
TArray<int32> FBoneContainer::CompactPoseToSkeletonIndex private
Definition at line 216 of file BoneContainer.h.
Referenced by GetSkeletonIndex(), and GetSkeletonPoseIndexFromCompactPoseIndex().
CurveEvalOption
const FCurveEvaluationOption & FBoneContainer::CurveEvalOption
Definition at line 261 of file BoneContainer.h.
Referenced by UE_DEPRECATED().
CurveFilter
UE::Anim::FCurveFilter FBoneContainer::CurveFilter private
Curve used for filtering by LOD/bone.
Definition at line 228 of file BoneContainer.h.
Referenced by GetCurveFilter().
CurveFlags
UE::Anim::FBulkCurveFlags FBoneContainer::CurveFlags private
Curve flags to apply (built from curve metadata)
Definition at line 231 of file BoneContainer.h.
Referenced by GetCurveFlags().
InAsset [1/2]
const FCurveEvaluationOption UObject& FBoneContainer::InAsset
Definition at line 261 of file BoneContainer.h.
Referenced by FBoneContainer(), and InitializeTo().
InAsset [2/2]
const FCurveEvaluationOption const UObject& FBoneContainer::InAsset
Definition at line 264 of file BoneContainer.h.
PoseToSkeletonBoneIndexArray
TArray<int32> FBoneContainer::PoseToSkeletonBoneIndexArray private
Mapping table between Pose Bone Indices and Skeleton Bone Indices.
Definition at line 213 of file BoneContainer.h.
Referenced by GetSkeletonPoseIndexFromMeshPoseIndex(), and UE_DEPRECATED().
RefPoseOverride
TSharedPtr<FSkelMeshRefPoseOverride> FBoneContainer::RefPoseOverride private
Definition at line 233 of file BoneContainer.h.
Referenced by FillWithCompactRefPose(), GetRefPoseTransform(), and SetRefPoseOverride().
RefSkeleton
const FReferenceSkeleton* FBoneContainer::RefSkeleton private
Pointer to RefSkeleton of Asset.
Definition at line 207 of file BoneContainer.h.
Referenced by FillWithCompactRefPose(), GetNumBones(), GetReferenceSkeleton(), GetRefPoseArray(), GetRefPoseTransform(), and IsValid().
RetargetSourceCachedDataLUT
TMap<FRetargetSourceCachedDataKey, FRetargetSourceCachedData> FBoneContainer::RetargetSourceCachedDataLUT mutable private
Runtime cached data for retargeting from a specific RetargetSource to this current SkelMesh LOD.
Todo
: We could also cache this once per skelmesh per lod, rather than creating it at runtime for each skelmesh instance.
Definition at line 689 of file BoneContainer.h.
SerialNumber
uint16 FBoneContainer::SerialNumber private
Definition at line 238 of file BoneContainer.h.
Referenced by GetSerialNumber().
SkeletonToCompactPose
TArray<FCompactPoseBoneIndex> FBoneContainer::SkeletonToCompactPose private
Definition at line 219 of file BoneContainer.h.
Referenced by GetCompactPoseIndexFromSkeletonIndex(), GetCompactPoseIndexFromSkeletonPoseIndex(), and IsSkeletonPoseIndexValid().
SkeletonToPoseBoneIndexArray
TArray<int32> FBoneContainer::SkeletonToPoseBoneIndexArray private
Mapping table between Skeleton Bone Indices and Pose Bone Indices.
Definition at line 210 of file BoneContainer.h.
Referenced by GetMeshPoseIndexFromSkeletonPoseIndex(), and UE_DEPRECATED().
VirtualBoneCompactPoseData
TArray<FVirtualBoneCompactPoseData> FBoneContainer::VirtualBoneCompactPoseData private
Definition at line 225 of file BoneContainer.h.
Referenced by GetVirtualBoneCompactPoseData().
The documentation for this struct was generated from the following file:
Runtime/Engine/Public/BoneContainer.h