Unreal Engine 5.6 C++ API: FHairStrandsDeformedResource Struct Reference
FHairStrandsDeformedResource Struct Reference
#include "GroomResources.h"
Public Types
enum EFrameType { Previous , Current }
Public Types inherited from FRenderResource
enum class EInitPhase : uint8 { Pre , Default , MAX }
Controls initialization order of render resources.
Public Member Functions
FHairStrandsDeformedResource (FHairStrandsBulkData &BulkData, EHairStrandsResourcesType CurveType, const FHairResourceName &ResourceName, const FName &OwnerName)
Build the hair strands resource.
FRDGExternalBuffer & GetBuffer (EFrameType T)
HAIRSTRANDSCORE_API FRDGExternalBuffer & GetDeformerBuffer (FRDGBuilder &GraphBuilder)
HAIRSTRANDSCORE_API FRDGExternalBuffer & GetDeformerCurveAttributeBuffer (FRDGBuilder &GraphBuilder)
HAIRSTRANDSCORE_API FRDGExternalBuffer & GetDeformerPointAttributeBuffer (FRDGBuilder &GraphBuilder)
virtual FString GetFriendlyName () const override
uint32 GetIndex (EFrameType T) const
FVector & GetPositionOffset (EFrameType T)
const FVector & GetPositionOffset (EFrameType T) const
FRDGExternalBuffer & GetPositionOffsetBuffer (EFrameType T)
const FRDGExternalBuffer & GetPositionOffsetBuffer (EFrameType T) const
uint32 GetResourcesSize () const
uint32 & GetUniqueViewID (EFrameType T)
uint32 GetUniqueViewID (EFrameType T) const
virtual void InternalAllocate (FRDGBuilder &GraphBuilder, uint32 InCurveCount, uint32 InPointCount) override
virtual void InternalRelease () override
void SetPositionOffset (EFrameType T, const FVector &Offset)
void SwapBuffer ()
Public Member Functions inherited from FHairCommonResource
FHairCommonResource (EHairStrandsAllocationType AllocationType, const FHairResourceName &InResourceName, const FName &InOwnerName, bool bUseRenderGraph=true)
Build the hair strands resource.
void Allocate (FRDGBuilder &GraphBuilder, EHairResourceLoadingType LoadingType)
void Allocate (FRDGBuilder &GraphBuilder, EHairResourceLoadingType LoadingType, EHairResourceStatus &Status)
void Allocate (FRDGBuilder &GraphBuilder, EHairResourceLoadingType LoadingType, EHairResourceStatus &Status, uint32 InRequestedCurveCount, uint32 InRequestedPointCount, bool bAllowDeallocation=true)
virtual void InitRHI (FRHICommandListBase &RHICmdList) override
Initializes the RHI resources used by this resource.
virtual void InternalAllocate ()
virtual void InternalAllocate (FRDGBuilder &GraphBuilder)
virtual FHairStrandsBulkCommon * InternalGetBulkData ()
virtual bool InternalGetOrRequestData (uint32 InRequestedCurveCount, uint32 InRequestedPointCount)
virtual void InternalResetLoadedSize ()
virtual void ReleaseRHI () override
Releases the RHI resources used by this resource.
void StreamInData ()
Public Member Functions inherited from FRenderResource
RENDERCORE_API FRenderResource ()
Default constructor.
RENDERCORE_API FRenderResource (const FRenderResource &)
Misc copy/assignment.
RENDERCORE_API FRenderResource (ERHIFeatureLevel::Type InFeatureLevel)
Constructor when we know what feature level this resource should support.
RENDERCORE_API FRenderResource (FRenderResource &&)
virtual RENDERCORE_API ~FRenderResource ()
Destructor used to catch unreleased resources.
EInitPhase GetInitPhase () const
int32 GetListIndex () const
FName GetOwnerName () const
FName GetResourceName () const
virtual RENDERCORE_API void InitResource (FRHICommandListBase &RHICmdList)
Initializes the resource.
FORCEINLINE bool IsInitialized () const
RENDERCORE_API FRenderResource & operator= (const FRenderResource &Other)
RENDERCORE_API FRenderResource & operator= (FRenderResource &&Other)
virtual RENDERCORE_API void ReleaseResource ()
Prepares the resource for deletion.
void SetOwnerName (FName InOwnerName)
SetOwnerName should be called before BeginInitResource for the owner name to be successfully tracked.
void SetResourceName (FName InResourceName)
RENDERCORE_API void UpdateRHI (FRHICommandListBase &RHICmdList)
If the resource's RHI resources have been initialized, then release and reinitialize it.
Data Fields
FHairStrandsBulkData & BulkData
uint32 CurrentIndex = 0
const EHairStrandsResourcesType CurveType
FRDGExternalBuffer DeformedOffsetBuffer [2]
FRDGExternalBuffer DeformedPositionBuffer [2]
FRDGExternalBuffer DeformerBuffer
FRDGExternalBuffer DeformerCurveAttributeBuffer
FRDGExternalBuffer DeformerPointAttributeBuffer
TMap< FString, FRDGExternalBuffer > ExternalBuffers
List of external buffers.
FVector PositionOffset [2] = {FVector::ZeroVector, FVector::ZeroVector}
FRDGExternalBuffer TangentBuffer
uint32 UniqueViewIDs [2] = { 0, 0 }
Data Fields inherited from FHairCommonResource
EHairStrandsAllocationType AllocationType = EHairStrandsAllocationType::Deferred
bool bIsInitialized = false
bool bUseRenderGraph = true
uint32 MaxAvailableCurveCount = HAIR_MAX_NUM_CURVE_PER_GROUP
FName OwnerName
FHairResourceName ResourceName
FHairStreamingRequest StreamingRequest
Data Fields inherited from FRenderResource
ERenderResourceState ResourceState = ERenderResourceState::Default
Additional Inherited Members
Static Public Member Functions inherited from FRenderResource
static RENDERCORE_API void ChangeFeatureLevel (ERHIFeatureLevel::Type NewFeatureLevel)
Reinitializes render resources at a new feature level.
static RENDERCORE_API void InitPreRHIResources ()
Initialize all resources initialized before the RHI was initialized.
static RENDERCORE_API void ReleaseRHIForAllResources ()
Release all render resources that are currently initialized.
Protected Member Functions inherited from FRenderResource
template<typename T>
FBufferRHIRef CreateRHIBuffer (FRHICommandListBase &RHICmdList, T &InOutResourceObject, uint32 ResourceCount, EBufferUsageFlags InBufferUsageFlags, const TCHAR *InDebugName)
const FStaticFeatureLevel GetFeatureLevel () const
FORCEINLINE bool HasValidFeatureLevel () const
void SetFeatureLevel (const FStaticFeatureLevel InFeatureLevel)
void SetInitPhase (EInitPhase InInitPhase)
Static Protected Member Functions inherited from FRenderResource
static RENDERCORE_API FRHICommandListBase & GetImmediateCommandList ()
Detailed Description
Definition at line 220 of file GroomResources.h.
Member Enumeration Documentation
EFrameType
enum FHairStrandsDeformedResource::EFrameType
Enumerator
Previous
Current
Definition at line 275 of file GroomResources.h.
Constructor & Destructor Documentation
FHairStrandsDeformedResource()
FHairStrandsDeformedResource::FHairStrandsDeformedResource (FHairStrandsBulkData & BulkData, EHairStrandsResourcesType CurveType, const FHairResourceName & ResourceName, const FName & OwnerName)
Build the hair strands resource.
References BulkData, CurveType, FHairCommonResource::OwnerName, and FHairCommonResource::ResourceName.
Member Function Documentation
GetBuffer()
FRDGExternalBuffer & FHairStrandsDeformedResource::GetBuffer (EFrameType T) inline
Definition at line 283 of file GroomResources.h.
References DeformedPositionBuffer, and GetIndex().
GetDeformerBuffer()
HAIRSTRANDSCORE_API FRDGExternalBuffer & FHairStrandsDeformedResource::GetDeformerBuffer (FRDGBuilder & GraphBuilder)
GetDeformerCurveAttributeBuffer()
HAIRSTRANDSCORE_API FRDGExternalBuffer & FHairStrandsDeformedResource::GetDeformerCurveAttributeBuffer (FRDGBuilder & GraphBuilder)
GetDeformerPointAttributeBuffer()
HAIRSTRANDSCORE_API FRDGExternalBuffer & FHairStrandsDeformedResource::GetDeformerPointAttributeBuffer (FRDGBuilder & GraphBuilder)
GetFriendlyName()
virtual FString FHairStrandsDeformedResource::GetFriendlyName () const inline override virtual
Returns
The resource's friendly name. Typically a UObject name.
Reimplemented from FRenderResource.
Definition at line 230 of file GroomResources.h.
References TEXT.
GetIndex()
uint32 FHairStrandsDeformedResource::GetIndex (EFrameType T) const inline
Definition at line 282 of file GroomResources.h.
References Current, and CurrentIndex.
Referenced by GetBuffer(), GetPositionOffset(), GetPositionOffset(), GetPositionOffsetBuffer(), GetPositionOffsetBuffer(), GetUniqueViewID(), GetUniqueViewID(), and SetPositionOffset().
GetPositionOffset() [1/2]
FVector & FHairStrandsDeformedResource::GetPositionOffset (EFrameType T) inline
Definition at line 284 of file GroomResources.h.
References FVector, GetIndex(), and PositionOffset.
GetPositionOffset() [2/2]
const FVector & FHairStrandsDeformedResource::GetPositionOffset (EFrameType T) const inline
Definition at line 287 of file GroomResources.h.
References FVector, GetIndex(), and PositionOffset.
GetPositionOffsetBuffer() [1/2]
FRDGExternalBuffer & FHairStrandsDeformedResource::GetPositionOffsetBuffer (EFrameType T) inline
Definition at line 286 of file GroomResources.h.
References DeformedOffsetBuffer, and GetIndex().
GetPositionOffsetBuffer() [2/2]
const FRDGExternalBuffer & FHairStrandsDeformedResource::GetPositionOffsetBuffer (EFrameType T) const inline
Definition at line 285 of file GroomResources.h.
References DeformedOffsetBuffer, and GetIndex().
GetResourcesSize()
uint32 FHairStrandsDeformedResource::GetResourcesSize () const inline
Definition at line 233 of file GroomResources.h.
References DeformedPositionBuffer, DeformerBuffer, GetBufferTotalNumBytes(), and TangentBuffer.
GetUniqueViewID() [1/2]
uint32 & FHairStrandsDeformedResource::GetUniqueViewID (EFrameType T) inline
Definition at line 290 of file GroomResources.h.
References GetIndex(), and UniqueViewIDs.
GetUniqueViewID() [2/2]
uint32 FHairStrandsDeformedResource::GetUniqueViewID (EFrameType T) const inline
Definition at line 291 of file GroomResources.h.
References GetIndex(), and UniqueViewIDs.
InternalAllocate()
virtual void FHairStrandsDeformedResource::InternalAllocate (FRDGBuilder & GraphBuilder, uint32 InCurveCount, uint32 InPointCount) override virtual
Reimplemented from FHairCommonResource.
InternalRelease()
virtual void FHairStrandsDeformedResource::InternalRelease () override virtual
Reimplemented from FHairCommonResource.
SetPositionOffset()
void FHairStrandsDeformedResource::SetPositionOffset (EFrameType T, const FVector & Offset) inline
Definition at line 288 of file GroomResources.h.
References FVector, GetIndex(), and PositionOffset.
SwapBuffer()
void FHairStrandsDeformedResource::SwapBuffer () inline
Definition at line 289 of file GroomResources.h.
References CurrentIndex.
Field Documentation
BulkData
FHairStrandsBulkData& FHairStrandsDeformedResource::BulkData
Definition at line 261 of file GroomResources.h.
Referenced by FHairStrandsDeformedResource().
CurrentIndex
uint32 FHairStrandsDeformedResource::CurrentIndex = 0
Definition at line 264 of file GroomResources.h.
Referenced by GetIndex(), and SwapBuffer().
CurveType
const EHairStrandsResourcesType FHairStrandsDeformedResource::CurveType
Definition at line 273 of file GroomResources.h.
Referenced by FHairStrandsDeformedResource().
DeformedOffsetBuffer
FRDGExternalBuffer FHairStrandsDeformedResource::DeformedOffsetBuffer[2]
Definition at line 247 of file GroomResources.h.
Referenced by GetPositionOffsetBuffer(), and GetPositionOffsetBuffer().
DeformedPositionBuffer
FRDGExternalBuffer FHairStrandsDeformedResource::DeformedPositionBuffer[2]
Definition at line 244 of file GroomResources.h.
Referenced by GetBuffer(), and GetResourcesSize().
DeformerBuffer
FRDGExternalBuffer FHairStrandsDeformedResource::DeformerBuffer
Definition at line 253 of file GroomResources.h.
Referenced by GetResourcesSize().
DeformerCurveAttributeBuffer
FRDGExternalBuffer FHairStrandsDeformedResource::DeformerCurveAttributeBuffer
Definition at line 255 of file GroomResources.h.
DeformerPointAttributeBuffer
FRDGExternalBuffer FHairStrandsDeformedResource::DeformerPointAttributeBuffer
Definition at line 254 of file GroomResources.h.
ExternalBuffers
TMap<FString,FRDGExternalBuffer> FHairStrandsDeformedResource::ExternalBuffers
List of external buffers.
Definition at line 300 of file GroomResources.h.
PositionOffset
FVector FHairStrandsDeformedResource::PositionOffset[2] = {FVector::ZeroVector, FVector::ZeroVector}
Definition at line 258 of file GroomResources.h.
Referenced by GetPositionOffset(), GetPositionOffset(), and SetPositionOffset().
TangentBuffer
FRDGExternalBuffer FHairStrandsDeformedResource::TangentBuffer
Definition at line 250 of file GroomResources.h.
Referenced by GetResourcesSize().
UniqueViewIDs
uint32 FHairStrandsDeformedResource::UniqueViewIDs[2] = { 0, 0 }
Definition at line 270 of file GroomResources.h.
Referenced by GetUniqueViewID(), and GetUniqueViewID().
The documentation for this struct was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/HairStrands/Source/HairStrandsCore/Public/GroomResources.h