Unreal Engine 5.6 C++ API: FSkeletalMeshStreamIn::FIntermediateBuffers Struct Reference
FSkeletalMeshStreamIn::FIntermediateBuffers Struct Reference
Correspond to the buffers in FSkeletalMeshLODRenderData.
#include "SkeletalMeshUpdate.h"
Public Member Functions
void CreateFromCPUData (FRHICommandListBase &RHICmdList, FSkeletalMeshLODRenderData &LODResource)
void TransferBuffers (FSkeletalMeshLODRenderData &LODResource, FRHIResourceReplaceBatcher &Batcher)
Transfer ownership of buffers to a LOD resource.
Data Fields
TArray< TPair< FSkinWeightProfileStack, FSkinWeightRHIInfo > > AltSkinWeightVertexBuffers
FBufferRHIRef ClothVertexBuffer
FBufferRHIRef ColorVertexBuffer
FSkeletalMeshHalfEdgeBuffer::FRHIInfo HalfEdgeBuffer
FBufferRHIRef IndexBuffer
FBufferRHIRef PositionVertexBuffer
FSkinWeightRHIInfo SkinWeightVertexBuffer
FBufferRHIRef TangentsVertexBuffer
FBufferRHIRef TexCoordVertexBuffer
Detailed Description
Correspond to the buffers in FSkeletalMeshLODRenderData.
Definition at line 83 of file SkeletalMeshUpdate.h.
Member Function Documentation
CreateFromCPUData()
void FSkeletalMeshStreamIn::FIntermediateBuffers::CreateFromCPUData (FRHICommandListBase & RHICmdList, FSkeletalMeshLODRenderData & LODResource)
Definition at line 54 of file SkeletalMeshUpdate.cpp.
References AltSkinWeightVertexBuffers, FSkeletalMeshLODRenderData::ClothVertexBuffer, ClothVertexBuffer, ColorVertexBuffer, FStaticMeshVertexBuffers::ColorVertexBuffer, FColorVertexBuffer::CreateRHIBuffer(), FMultiSizeIndexContainer::CreateRHIBuffer(), FPositionVertexBuffer::CreateRHIBuffer(), FSkeletalMeshHalfEdgeBuffer::CreateRHIBuffer(), FSkeletalMeshVertexClothBuffer::CreateRHIBuffer(), FSkinWeightVertexBuffer::CreateRHIBuffer(), FSkinWeightProfilesData::CreateRHIBuffers(), FStaticMeshVertexBuffer::CreateTangentsRHIBuffer(), FStaticMeshVertexBuffer::CreateTexCoordRHIBuffer(), FSkeletalMeshLODRenderData::HalfEdgeBuffer, HalfEdgeBuffer, IndexBuffer, FSkeletalMeshLODRenderData::MultiSizeIndexContainer, PositionVertexBuffer, FStaticMeshVertexBuffers::PositionVertexBuffer, FSkeletalMeshLODRenderData::SkinWeightProfilesData, FSkeletalMeshLODRenderData::SkinWeightVertexBuffer, SkinWeightVertexBuffer, FStaticMeshVertexBuffers::StaticMeshVertexBuffer, FSkeletalMeshLODRenderData::StaticVertexBuffers, TangentsVertexBuffer, and TexCoordVertexBuffer.
TransferBuffers()
void FSkeletalMeshStreamIn::FIntermediateBuffers::TransferBuffers (FSkeletalMeshLODRenderData & LODResource, FRHIResourceReplaceBatcher & Batcher)
Transfer ownership of buffers to a LOD resource.
Definition at line 68 of file SkeletalMeshUpdate.cpp.
References AltSkinWeightVertexBuffers, FSkeletalMeshLODRenderData::ClothVertexBuffer, ClothVertexBuffer, ColorVertexBuffer, FStaticMeshVertexBuffers::ColorVertexBuffer, FSkeletalMeshLODRenderData::HalfEdgeBuffer, HalfEdgeBuffer, IndexBuffer, FColorVertexBuffer::InitRHIForStreaming(), FMultiSizeIndexContainer::InitRHIForStreaming(), FPositionVertexBuffer::InitRHIForStreaming(), FSkeletalMeshHalfEdgeBuffer::InitRHIForStreaming(), FSkeletalMeshVertexClothBuffer::InitRHIForStreaming(), FSkinWeightProfilesData::InitRHIForStreaming(), FSkinWeightVertexBuffer::InitRHIForStreaming(), FStaticMeshVertexBuffer::InitRHIForStreaming(), FSkeletalMeshLODRenderData::MultiSizeIndexContainer, PositionVertexBuffer, FStaticMeshVertexBuffers::PositionVertexBuffer, FSkeletalMeshLODRenderData::SkinWeightProfilesData, FSkeletalMeshLODRenderData::SkinWeightVertexBuffer, SkinWeightVertexBuffer, FStaticMeshVertexBuffers::StaticMeshVertexBuffer, FSkeletalMeshLODRenderData::StaticVertexBuffers, TangentsVertexBuffer, and TexCoordVertexBuffer.
Field Documentation
AltSkinWeightVertexBuffers
TArray<TPair<FSkinWeightProfileStack, FSkinWeightRHIInfo> > FSkeletalMeshStreamIn::FIntermediateBuffers::AltSkinWeightVertexBuffers
Definition at line 92 of file SkeletalMeshUpdate.h.
Referenced by CreateFromCPUData(), and TransferBuffers().
ClothVertexBuffer
FBufferRHIRef FSkeletalMeshStreamIn::FIntermediateBuffers::ClothVertexBuffer
Definition at line 90 of file SkeletalMeshUpdate.h.
Referenced by CreateFromCPUData(), and TransferBuffers().
ColorVertexBuffer
FBufferRHIRef FSkeletalMeshStreamIn::FIntermediateBuffers::ColorVertexBuffer
Definition at line 88 of file SkeletalMeshUpdate.h.
Referenced by CreateFromCPUData(), and TransferBuffers().
HalfEdgeBuffer
FSkeletalMeshHalfEdgeBuffer::FRHIInfo FSkeletalMeshStreamIn::FIntermediateBuffers::HalfEdgeBuffer
Definition at line 93 of file SkeletalMeshUpdate.h.
Referenced by CreateFromCPUData(), and TransferBuffers().
IndexBuffer
FBufferRHIRef FSkeletalMeshStreamIn::FIntermediateBuffers::IndexBuffer
Definition at line 91 of file SkeletalMeshUpdate.h.
Referenced by CreateFromCPUData(), and TransferBuffers().
PositionVertexBuffer
FBufferRHIRef FSkeletalMeshStreamIn::FIntermediateBuffers::PositionVertexBuffer
Definition at line 87 of file SkeletalMeshUpdate.h.
Referenced by CreateFromCPUData(), and TransferBuffers().
SkinWeightVertexBuffer
FSkinWeightRHIInfo FSkeletalMeshStreamIn::FIntermediateBuffers::SkinWeightVertexBuffer
Definition at line 89 of file SkeletalMeshUpdate.h.
Referenced by CreateFromCPUData(), and TransferBuffers().
TangentsVertexBuffer
FBufferRHIRef FSkeletalMeshStreamIn::FIntermediateBuffers::TangentsVertexBuffer
Definition at line 85 of file SkeletalMeshUpdate.h.
Referenced by CreateFromCPUData(), and TransferBuffers().
TexCoordVertexBuffer
FBufferRHIRef FSkeletalMeshStreamIn::FIntermediateBuffers::TexCoordVertexBuffer
Definition at line 86 of file SkeletalMeshUpdate.h.
Referenced by CreateFromCPUData(), and TransferBuffers().
The documentation for this struct was generated from the following files:
Runtime/Engine/Internal/Streaming/SkeletalMeshUpdate.h
Runtime/Engine/Internal/Streaming/SkeletalMeshUpdate.cpp