Unreal Engine 5.6 C++ API: FInputActionBinding Struct Reference
FInputActionBinding Struct Reference
Binds a delegate to an action.
#include "InputComponent.h"
Public Member Functions
FInputActionBinding ()
FInputActionBinding (const FName InActionName, const EInputEvent InKeyEvent)
void GenerateNewHandle ()
FName GetActionName () const
int32 GetHandle () const
bool IsPaired () const
bool IsValid ()
Indicates GenerateNewHandle was called.
bool operator== (const FInputActionBinding &Rhs)
Public Member Functions inherited from FInputBinding
FInputBinding ()
Data Fields
FInputActionUnifiedDelegate ActionDelegate
The delegate bound to the action.
TEnumAsByte< EInputEvent > KeyEvent
Key event to bind it to, e.g.
Data Fields inherited from FInputBinding
uint8 bConsumeInput:1
Whether the binding should consume the input or allow it to pass to another component.
uint8 bExecuteWhenPaused:1
Whether the binding should execute while paused.
Private Attributes
FName ActionName
Friendly name of action, e.g "jump".
uint8 bPaired:1
Whether the binding is part of a paired (both pressed and released events bound) action.
int32 Handle
The handle for this binding action.
Friends
class UInputComponent
Detailed Description
Binds a delegate to an action.
Definition at line 327 of file InputComponent.h.
Constructor & Destructor Documentation
FInputActionBinding() [1/2]
FInputActionBinding::FInputActionBinding () inline
Definition at line 348 of file InputComponent.h.
References FInputBinding::FInputBinding(), ActionName, bPaired, Handle, INDEX_NONE, and KeyEvent.
Referenced by operator==().
FInputActionBinding() [2/2]
FInputActionBinding::FInputActionBinding (const FName InActionName, const EInputEvent InKeyEvent) inline
Definition at line 356 of file InputComponent.h.
References FInputBinding::FInputBinding(), ActionName, bPaired, Handle, INDEX_NONE, and KeyEvent.
Member Function Documentation
GenerateNewHandle()
void FInputActionBinding::GenerateNewHandle ()
GetActionName()
FName FInputActionBinding::GetActionName () const inline
Definition at line 364 of file InputComponent.h.
References ActionName.
GetHandle()
int32 FInputActionBinding::GetHandle () const inline
Definition at line 366 of file InputComponent.h.
References Handle.
Referenced by operator==().
IsPaired()
bool FInputActionBinding::IsPaired () const inline
Definition at line 365 of file InputComponent.h.
References bPaired.
IsValid()
bool FInputActionBinding::IsValid () inline
Indicates GenerateNewHandle was called.
Definition at line 374 of file InputComponent.h.
References Handle, and INDEX_NONE.
Referenced by operator==().
operator==()
bool FInputActionBinding::operator== (const FInputActionBinding & Rhs) inline
Definition at line 368 of file InputComponent.h.
References FInputActionBinding(), GetHandle(), and IsValid().
Friends And Related Symbol Documentation
UInputComponent
friend class UInputComponent friend
Definition at line 378 of file InputComponent.h.
References UInputComponent.
Referenced by UInputComponent.
Field Documentation
ActionDelegate
FInputActionUnifiedDelegate FInputActionBinding::ActionDelegate
The delegate bound to the action.
Definition at line 346 of file InputComponent.h.
Referenced by UInputComponent::BindAction(), UInputComponent::BindAction(), and UInputComponent::BindAction().
ActionName
FName FInputActionBinding::ActionName private
Friendly name of action, e.g "jump".
Definition at line 339 of file InputComponent.h.
Referenced by FInputActionBinding(), FInputActionBinding(), and GetActionName().
bPaired
uint8 FInputActionBinding::bPaired private
Whether the binding is part of a paired (both pressed and released events bound) action.
Definition at line 331 of file InputComponent.h.
Referenced by FInputActionBinding(), FInputActionBinding(), and IsPaired().
Handle
int32 FInputActionBinding::Handle private
The handle for this binding action.
Definition at line 342 of file InputComponent.h.
Referenced by FInputActionBinding(), FInputActionBinding(), GetHandle(), and IsValid().
KeyEvent
TEnumAsByte<EInputEvent> FInputActionBinding::KeyEvent
Key event to bind it to, e.g.
pressed, released, double click
Definition at line 335 of file InputComponent.h.
Referenced by FInputActionBinding(), and FInputActionBinding().
The documentation for this struct was generated from the following file:
Runtime/Engine/Classes/Components/InputComponent.h