Unreal Engine 5.6 C++ API: FSlotProxy Struct Reference
FSlotProxy Struct Reference
Represents a single slot, used to perform arrangement operations.
#include "LayoutUtils.h"
Public Member Functions
FSlotProxy ()=default
template<typename SlotType>
FSlotProxy (const int32 InSlotIndex, const SlotType &InSlot)
Constructs a SlotProxy for the given slot index and FSlot.
FGeometry MakeGeometry (const FGeometry &InParentGeometry, const FVector2f &InChildOffset, const FVector2f &InLocalSize) const
Performs the same functionality as FGeometry::MakeChild, without the need for the original Widget reference.
bool operator< (const FSlotProxy &InOtherSlot) const
Default comparison operator for sorting by slot index.
bool operator== (const int32 InSlotIndex) const
Equality tested against the slot index.
template<typename SlotType, bool CompareArranged = false>
bool UpdateFromSlot (const int32 InSlotIndex, const SlotType &InSlot)
Applies the given slot's values to this proxy.
Data Fields
FVector2f ArrangedSize = FVector2f::ZeroVector
Contained widget's arranged size (as it was last calculated).
FVector2f DesiredSize = FVector2f::ZeroVector
Contained widget's desired size.
EHorizontalAlignment HorizontalAlignment = HAlign_Fill
Horizontal slot alignment.
float MaxSize = 0.0f
Max Size, if any.
float MinSize = 0.0f
Min Size, if any.
FMargin Padding = FMargin(0)
Padding margin.
TOptional< FSlateRenderTransform > RenderTransform
Last calculated RenderTransform.
FVector2f RenderTransformPivot = FVector2f::ZeroVector
Corresponds with the RenderTransform.
FSizeParam SizeParam = FAuto()
Sizing option, ie.
int32 SlotIndex = INDEX_NONE
The original index of the slot represented by this proxy.
EVerticalAlignment VerticalAlignment = VAlign_Fill
Vertical slot alignment.
EVisibility Visibility = EVisibility::Visible
Current visibility state.
TSharedPtr< SWidget > Widget = nullptr
Here for convenience and backwards compatibility.
Private Member Functions
FSlotProxy (const TSharedRef< SWidget > &InWidget)
bool UpdateFromSlot (const TSharedRef< SWidget > &InWidget)
Applies the given slot widget's values to this proxy.
Detailed Description
Represents a single slot, used to perform arrangement operations.
Allows layout with an arbitrary child order that can map back to a sequential array.
Definition at line 32 of file LayoutUtils.h.
Constructor & Destructor Documentation
FSlotProxy() [1/3]
FSlotProxy::FSlotProxy () default
Referenced by FSlotProxy(), and operator<().
FSlotProxy() [2/3]
template<typename SlotType> FSlotProxy::FSlotProxy (const int32 InSlotIndex, const SlotType & InSlot) inline explicit
Constructs a SlotProxy for the given slot index and FSlot.
Definition at line 38 of file LayoutUtils.h.
References FSlotProxy(), HorizontalAlignment, MaxSize, MinSize, Padding, SizeParam, SlotIndex, and VerticalAlignment.
FSlotProxy() [3/3]
FSlotProxy::FSlotProxy (const TSharedRef< SWidget > & InWidget) explicit private
Member Function Documentation
MakeGeometry()
FGeometry FSlotProxy::MakeGeometry (const FGeometry & InParentGeometry, const FVector2f & InChildOffset, const FVector2f & InLocalSize) const
Performs the same functionality as FGeometry::MakeChild, without the need for the original Widget reference.
operator<()
bool FSlotProxy::operator< (const FSlotProxy & InOtherSlot) const inline
Default comparison operator for sorting by slot index.
Definition at line 121 of file LayoutUtils.h.
References FSlotProxy(), and SlotIndex.
operator==()
bool FSlotProxy::operator== (const int32 InSlotIndex) const inline
Equality tested against the slot index.
This makes it simple to find a slot by its index, even if the slot proxies are differently ordered.
Definition at line 115 of file LayoutUtils.h.
References SlotIndex.
UpdateFromSlot() [1/2]
template<typename SlotType, bool CompareArranged = false> bool FSlotProxy::UpdateFromSlot (const int32 InSlotIndex, const SlotType & InSlot) inline
Applies the given slot's values to this proxy.
Will return true if any values have changed from those stored. If CompareArranged is true, the "changed" flag is only true if the new DesiredSize doesn't match the previous ArrangedSize, rather than previous DesiredSize.
Definition at line 61 of file LayoutUtils.h.
References ArrangedSize, DesiredSize, HorizontalAlignment, FMath::IsNearlyEqual(), MaxSize, MinSize, Padding, SizeParam, SlotIndex, UpdateFromSlot(), and VerticalAlignment.
Referenced by UpdateFromSlot().
UpdateFromSlot() [2/2]
bool FSlotProxy::UpdateFromSlot (const TSharedRef< SWidget > & InWidget) private
Applies the given slot widget's values to this proxy.
Will return true if any values have changed from those stored.
Field Documentation
ArrangedSize
FVector2f FSlotProxy::ArrangedSize = FVector2f::ZeroVector
Contained widget's arranged size (as it was last calculated).
Definition at line 143 of file LayoutUtils.h.
Referenced by UE::Slate::TSlotAccessor< SlotType, std::enable_if_t< std::is_base_of_v< FSlotProxy, std::decay_t< SlotType > > > >::GetArrangedSize(), and UpdateFromSlot().
DesiredSize
FVector2f FSlotProxy::DesiredSize = FVector2f::ZeroVector
Contained widget's desired size.
Definition at line 140 of file LayoutUtils.h.
Referenced by UE::Slate::TSlotAccessor< SlotType, std::enable_if_t< std::is_base_of_v< FSlotProxy, std::decay_t< SlotType > > > >::GetDesiredSize(), and UpdateFromSlot().
HorizontalAlignment
EHorizontalAlignment FSlotProxy::HorizontalAlignment = HAlign_Fill
Horizontal slot alignment.
Definition at line 158 of file LayoutUtils.h.
Referenced by FSlotProxy(), and UpdateFromSlot().
MaxSize
float FSlotProxy::MaxSize = 0.0f
Max Size, if any.
Definition at line 152 of file LayoutUtils.h.
Referenced by FSlotProxy(), UE::Slate::TSlotAccessor< SlotType, std::enable_if_t< std::is_base_of_v< FSlotProxy, std::decay_t< SlotType > > > >::GetMaxSize(), and UpdateFromSlot().
MinSize
float FSlotProxy::MinSize = 0.0f
Min Size, if any.
Definition at line 149 of file LayoutUtils.h.
Referenced by FSlotProxy(), UE::Slate::TSlotAccessor< SlotType, std::enable_if_t< std::is_base_of_v< FSlotProxy, std::decay_t< SlotType > > > >::GetMinSize(), and UpdateFromSlot().
Padding
FMargin FSlotProxy::Padding = FMargin(0)
Padding margin.
Definition at line 137 of file LayoutUtils.h.
Referenced by FSlotProxy(), UE::Slate::TSlotAccessor< SlotType, std::enable_if_t< std::is_base_of_v< FSlotProxy, std::decay_t< SlotType > > > >::GetPadding(), and UpdateFromSlot().
RenderTransform
TOptional<FSlateRenderTransform> FSlotProxy::RenderTransform
Last calculated RenderTransform.
Definition at line 164 of file LayoutUtils.h.
RenderTransformPivot
FVector2f FSlotProxy::RenderTransformPivot = FVector2f::ZeroVector
Corresponds with the RenderTransform.
Definition at line 167 of file LayoutUtils.h.
SizeParam
FSizeParam FSlotProxy::SizeParam = FAuto()
Sizing option, ie.
Auto, Fill.
Definition at line 146 of file LayoutUtils.h.
Referenced by FSlotProxy(), UE::Slate::TSlotAccessor< SlotType, std::enable_if_t< std::is_base_of_v< FSlotProxy, std::decay_t< SlotType > > > >::GetShrinkSizeValue(), UE::Slate::TSlotAccessor< SlotType, std::enable_if_t< std::is_base_of_v< FSlotProxy, std::decay_t< SlotType > > > >::GetSizeRule(), UE::Slate::TSlotAccessor< SlotType, std::enable_if_t< std::is_base_of_v< FSlotProxy, std::decay_t< SlotType > > > >::GetSizeValue(), and UpdateFromSlot().
SlotIndex
int32 FSlotProxy::SlotIndex = INDEX_NONE
The original index of the slot represented by this proxy.
Definition at line 134 of file LayoutUtils.h.
Referenced by FSlotProxy(), UE::Slate::TSlotAccessor< SlotType, std::enable_if_t< std::is_base_of_v< FSlotProxy, std::decay_t< SlotType > > > >::GetIndex(), operator<(), operator==(), and UpdateFromSlot().
VerticalAlignment
EVerticalAlignment FSlotProxy::VerticalAlignment = VAlign_Fill
Vertical slot alignment.
Definition at line 161 of file LayoutUtils.h.
Referenced by FSlotProxy(), and UpdateFromSlot().
Visibility
EVisibility FSlotProxy::Visibility = EVisibility::Visible
Current visibility state.
Definition at line 155 of file LayoutUtils.h.
Referenced by UE::Slate::TSlotAccessor< SlotType, std::enable_if_t< std::is_base_of_v< FSlotProxy, std::decay_t< SlotType > > > >::GetVisibility().
Widget
TSharedPtr<SWidget> FSlotProxy::Widget = nullptr
Here for convenience and backwards compatibility.
Not always valid.
Definition at line 170 of file LayoutUtils.h.
Referenced by UE::Slate::TSlotAccessor< SlotType, std::enable_if_t< std::is_base_of_v< FSlotProxy, std::decay_t< SlotType > > > >::GetWidget().
The documentation for this struct was generated from the following file:
Runtime/SlateCore/Public/Layout/LayoutUtils.h