Unreal Engine 5.6 C++ API: FPropertyVisitorInfo Struct Reference
FPropertyVisitorInfo Struct Reference
#include "PropertyVisitor.h"
Public Member Functions
FPropertyVisitorInfo (const FProperty *InProperty, int32 InIndex=INDEX_NONE, EPropertyVisitorInfoType InPropertyInfo=EPropertyVisitorInfoType::None)
FPropertyVisitorInfo (const FPropertyVisitorInfo &)=default
FPropertyVisitorInfo (FPropertyVisitorInfo &&)=default
bool Identical (const FPropertyVisitorInfo &Other) const
FPropertyVisitorInfo & operator= (const FPropertyVisitorInfo &)=default
FPropertyVisitorInfo & operator= (FPropertyVisitorInfo &&)=default
void SetIndex (int32 InIndex, EPropertyVisitorInfoType InPropertyInfo)
Data Fields
bool bContainsInnerProperties
int32 Index
Index of the element being visited in the container, otherwise INDEX_NONE.
const UStruct * ParentStructType = nullptr
The parent struct that provided the property being iterated, if iterating a sub-property within a struct.
const FProperty * Property
The property currently being visited.
EPropertyVisitorInfoType PropertyInfo
Whether this property is inside a container and if it is key or a value of a map.
Friends
uint32 GetTypeHash (const FPropertyVisitorInfo &A)
bool operator!= (const FPropertyVisitorInfo &A, const FPropertyVisitorInfo &B)
bool operator== (const FPropertyVisitorInfo &A, const FPropertyVisitorInfo &B)
Detailed Description
Definition at line 31 of file PropertyVisitor.h.
Constructor & Destructor Documentation
FPropertyVisitorInfo() [1/3]
FPropertyVisitorInfo::FPropertyVisitorInfo (const FProperty * InProperty, int32 InIndex = INDEX_NONE, EPropertyVisitorInfoType InPropertyInfo = EPropertyVisitorInfoType::None) inline explicit
Definition at line 33 of file PropertyVisitor.h.
References bContainsInnerProperties, Index, INDEX_NONE, None, Property, and PropertyInfo.
Referenced by FPropertyVisitorInfo(), FPropertyVisitorInfo(), GetTypeHash, Identical(), operator!=, operator=(), operator=(), and operator==.
FPropertyVisitorInfo() [2/3]
FPropertyVisitorInfo::FPropertyVisitorInfo (const FPropertyVisitorInfo &) default
References FPropertyVisitorInfo().
FPropertyVisitorInfo() [3/3]
FPropertyVisitorInfo::FPropertyVisitorInfo (FPropertyVisitorInfo &&) default
References FPropertyVisitorInfo().
Member Function Documentation
Identical()
bool FPropertyVisitorInfo::Identical (const FPropertyVisitorInfo & Other) const
References FPropertyVisitorInfo(), and Other.
operator=() [1/2]
FPropertyVisitorInfo & FPropertyVisitorInfo::operator= (const FPropertyVisitorInfo &) default
References FPropertyVisitorInfo().
operator=() [2/2]
FPropertyVisitorInfo & FPropertyVisitorInfo::operator= (FPropertyVisitorInfo &&) default
References FPropertyVisitorInfo().
SetIndex()
void FPropertyVisitorInfo::SetIndex (int32 InIndex, EPropertyVisitorInfoType InPropertyInfo) inline
Definition at line 46 of file PropertyVisitor.h.
References Index, and PropertyInfo.
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FPropertyVisitorInfo & A) friend
Definition at line 64 of file PropertyVisitor.h.
References FPropertyVisitorInfo(), A, GetTypeHash, and HashCombine().
Referenced by GetTypeHash.
operator!=
bool operator!= (const FPropertyVisitorInfo & A, const FPropertyVisitorInfo & B) friend
Definition at line 59 of file PropertyVisitor.h.
References FPropertyVisitorInfo(), A, and B.
operator==
bool operator== (const FPropertyVisitorInfo & A, const FPropertyVisitorInfo & B) friend
Note
The default comparison only compares the key data to match GetTypeHash and is for use with hashed containers and ResolveVisitedPathInfo_Generic; use Identical for an exact comparison
Definition at line 55 of file PropertyVisitor.h.
References FPropertyVisitorInfo(), A, and B.
Field Documentation
bContainsInnerProperties
bool FPropertyVisitorInfo::bContainsInnerProperties
Definition at line 88 of file PropertyVisitor.h.
Referenced by FPropertyVisitorInfo().
Index
int32 FPropertyVisitorInfo::Index
Index of the element being visited in the container, otherwise INDEX_NONE.
For maps and sets it indicates the logical index.
Definition at line 82 of file PropertyVisitor.h.
Referenced by FPropertyVisitorInfo(), and SetIndex().
ParentStructType
const UStruct* FPropertyVisitorInfo::ParentStructType = nullptr
The parent struct that provided the property being iterated, if iterating a sub-property within a struct.
Note
This is slighty different than Property->GetOwnerStruct() as you might be iterating a FDerived instance but processing a FBase struct property. In this case this will be set to FDerived rather than FBase.
Definition at line 77 of file PropertyVisitor.h.
Property
const FProperty* FPropertyVisitorInfo::Property
The property currently being visited.
Definition at line 70 of file PropertyVisitor.h.
Referenced by FPropertyVisitorInfo(), and PropertyVisitorHelpers::ResolveVisitedPath().
PropertyInfo
EPropertyVisitorInfoType FPropertyVisitorInfo::PropertyInfo
Whether this property is inside a container and if it is key or a value of a map.
Definition at line 85 of file PropertyVisitor.h.
Referenced by FPropertyVisitorInfo(), and SetIndex().
The documentation for this struct was generated from the following file:
Runtime/CoreUObject/Public/UObject/PropertyVisitor.h