Unreal Engine 5.6 C++ API: Verse::TPtrVariant< Ts > Struct Template Reference
Verse::TPtrVariant< Ts > Struct Template Reference
#include "VVMPtrVariant.h"
Public Member Functions
template<typename T>
TPtrVariant (T InT)
template<typename T>
T As ()
template<typename T>
bool Is ()
bool operator== (TPtrVariant Other) const
uintptr_t RawPtr () const
Static Public Attributes
static constexpr uintptr_t Mask = BitCeil(sizeof...(Ts)) - 1
Private Attributes
uintptr_t Ptr
Detailed Description
template<typename... Ts>
struct Verse::TPtrVariant< Ts >
Definition at line 41 of file VVMPtrVariant.h.
Constructor & Destructor Documentation
TPtrVariant()
template<typename... Ts> template<typename T> Verse::TPtrVariant< Ts >::TPtrVariant (T InT) inline
Definition at line 48 of file VVMPtrVariant.h.
References BitCast(), checkSlow, Mask, Ptr, and Value.
Referenced by operator==().
Member Function Documentation
As()
template<typename... Ts> template<typename T> T Verse::TPtrVariant< Ts >::As () inline
Definition at line 64 of file VVMPtrVariant.h.
References BitCast(), checkSlow, Is(), Mask, and Ptr.
Is()
template<typename... Ts> template<typename T> bool Verse::TPtrVariant< Ts >::Is () inline
Definition at line 57 of file VVMPtrVariant.h.
References Mask, Ptr, and Value.
Referenced by As().
operator==()
template<typename... Ts> bool Verse::TPtrVariant< Ts >::operator== (TPtrVariant< Ts > Other) const inline
Definition at line 71 of file VVMPtrVariant.h.
References TPtrVariant(), Other, and Ptr.
RawPtr()
template<typename... Ts> uintptr_t Verse::TPtrVariant< Ts >::RawPtr () const inline
Definition at line 76 of file VVMPtrVariant.h.
References Ptr.
Referenced by Verse::GetTypeHash().
Field Documentation
Mask
template<typename... Ts> uintptr_t Verse::TPtrVariant< Ts >::Mask = BitCeil(sizeof...(Ts)) - 1 static constexpr
Definition at line 45 of file VVMPtrVariant.h.
Referenced by TPtrVariant(), As(), and Is().
Ptr
template<typename... Ts> uintptr_t Verse::TPtrVariant< Ts >::Ptr private
Definition at line 79 of file VVMPtrVariant.h.
Referenced by TPtrVariant(), As(), Is(), operator==(), and RawPtr().
The documentation for this struct was generated from the following file:
Runtime/CoreUObject/Public/VerseVM/VVMPtrVariant.h