Unreal Engine 5.6 C++ API: FSequencerFilterData Struct Reference
FSequencerFilterData Struct Reference
Represents a cache between nodes for a filter operation.
#include "SequencerFilterData.h"
Public Member Functions
FSequencerFilterData (const FString &InRawFilterText)
bool ContainsFilterInNodes (const FSequencerFilterData &InOtherData) const
void FilterInNode (UE::Sequencer::TWeakViewModelPtr< UE::Sequencer::IOutlinerExtension > InNodeWeak)
void FilterInNodeWithAncestors (const UE::Sequencer::TViewModelPtr< UE::Sequencer::IOutlinerExtension > &InNode)
void FilterInParentChildNodes (const UE::Sequencer::TViewModelPtr< UE::Sequencer::IOutlinerExtension > &InNode, const bool bInIncludeSelf, const bool bInIncludeParents, const bool bInIncludeChildren=false)
void FilterOutNode (UE::Sequencer::TWeakViewModelPtr< UE::Sequencer::IOutlinerExtension > InNodeWeak)
uint32 GetDisplayNodeCount () const
uint32 GetFilterInCount () const
uint32 GetFilterOutCount () const
FString GetRawFilterText () const
uint32 GetTotalNodeCount () const
void IncrementTotalNodeCount ()
bool IsFilteredOut (const UE::Sequencer::TViewModelPtr< UE::Sequencer::IOutlinerExtension > &InNode) const
bool operator!= (const FSequencerFilterData &InRhs) const
bool operator== (const FSequencerFilterData &InRhs) const
void Reset ()
UMovieSceneTrack * ResolveMovieSceneTrackObject (FSequencerTrackFilterType InNode)
UE::Sequencer::TWeakViewModelPtr< UE::Sequencer::ITrackExtension > ResolveTrack (FSequencerTrackFilterType InNode)
UObject * ResolveTrackBoundObject (ISequencer &InSequencer, FSequencerTrackFilterType InNode)
Data Fields
TMap< UE::Sequencer::TWeakViewModelPtr< UE::Sequencer::IOutlinerExtension >, TWeakObjectPtr<> > ResolvedObjects
TMap< UE::Sequencer::TWeakViewModelPtr< UE::Sequencer::IOutlinerExtension >, TWeakObjectPtr< UMovieSceneTrack > > ResolvedTrackObjects
TMap< UE::Sequencer::TWeakViewModelPtr< UE::Sequencer::IOutlinerExtension >, UE::Sequencer::TWeakViewModelPtr< UE::Sequencer::ITrackExtension > > ResolvedTracks
Protected Attributes
TSet< UE::Sequencer::TWeakViewModelPtr< UE::Sequencer::IOutlinerExtension > > FilterInNodes
Nodes to be displayed in the UI.
FString RawFilterText
uint32 TotalNodeCount = 0
Detailed Description
Represents a cache between nodes for a filter operation.
Definition at line 20 of file SequencerFilterData.h.
Constructor & Destructor Documentation
FSequencerFilterData()
FSequencerFilterData::FSequencerFilterData (const FString & InRawFilterText)
Referenced by ContainsFilterInNodes(), operator!=(), and operator==().
Member Function Documentation
ContainsFilterInNodes()
bool FSequencerFilterData::ContainsFilterInNodes (const FSequencerFilterData & InOtherData) const
References FSequencerFilterData().
FilterInNode()
void FSequencerFilterData::FilterInNode (UE::Sequencer::TWeakViewModelPtr< UE::Sequencer::IOutlinerExtension > InNodeWeak)
FilterInNodeWithAncestors()
void FSequencerFilterData::FilterInNodeWithAncestors (const UE::Sequencer::TViewModelPtr< UE::Sequencer::IOutlinerExtension > & InNode)
FilterInParentChildNodes()
void FSequencerFilterData::FilterInParentChildNodes (const UE::Sequencer::TViewModelPtr< UE::Sequencer::IOutlinerExtension > & InNode, const bool bInIncludeSelf, const bool bInIncludeParents, const bool bInIncludeChildren = false)
FilterOutNode()
void FSequencerFilterData::FilterOutNode (UE::Sequencer::TWeakViewModelPtr< UE::Sequencer::IOutlinerExtension > InNodeWeak)
GetDisplayNodeCount()
uint32 FSequencerFilterData::GetDisplayNodeCount () const
GetFilterInCount()
uint32 FSequencerFilterData::GetFilterInCount () const
GetFilterOutCount()
uint32 FSequencerFilterData::GetFilterOutCount () const
GetRawFilterText()
FString FSequencerFilterData::GetRawFilterText () const
GetTotalNodeCount()
uint32 FSequencerFilterData::GetTotalNodeCount () const
IncrementTotalNodeCount()
void FSequencerFilterData::IncrementTotalNodeCount ()
IsFilteredOut()
bool FSequencerFilterData::IsFilteredOut (const UE::Sequencer::TViewModelPtr< UE::Sequencer::IOutlinerExtension > & InNode) const
operator!=()
bool FSequencerFilterData::operator!= (const FSequencerFilterData & InRhs) const
References FSequencerFilterData().
operator==()
bool FSequencerFilterData::operator== (const FSequencerFilterData & InRhs) const
References FSequencerFilterData().
Reset()
void FSequencerFilterData::Reset ()
ResolveMovieSceneTrackObject()
UMovieSceneTrack * FSequencerFilterData::ResolveMovieSceneTrackObject (FSequencerTrackFilterType InNode)
Referenced by FSequencerTrackFilter_ClassType< InClassType >::PassesFilter().
ResolveTrack()
UE::Sequencer::TWeakViewModelPtr< UE::Sequencer::ITrackExtension > FSequencerFilterData::ResolveTrack (FSequencerTrackFilterType InNode)
ResolveTrackBoundObject()
UObject * FSequencerFilterData::ResolveTrackBoundObject (ISequencer & InSequencer, FSequencerTrackFilterType InNode)
Referenced by FSequencerTrackFilter_ComponentType< InComponentType >::PassesFilter().
Field Documentation
FilterInNodes
TSet<UE::Sequencer::TWeakViewModelPtr<UE::Sequencer::IOutlinerExtension> > FSequencerFilterData::FilterInNodes protected
Nodes to be displayed in the UI.
Definition at line 65 of file SequencerFilterData.h.
RawFilterText
FString FSequencerFilterData::RawFilterText protected
Definition at line 60 of file SequencerFilterData.h.
ResolvedObjects
TMap<UE::Sequencer::TWeakViewModelPtr<UE::Sequencer::IOutlinerExtension>, TWeakObjectPtr<> > FSequencerFilterData::ResolvedObjects
Definition at line 57 of file SequencerFilterData.h.
ResolvedTrackObjects
TMap<UE::Sequencer::TWeakViewModelPtr<UE::Sequencer::IOutlinerExtension>, TWeakObjectPtr<UMovieSceneTrack> > FSequencerFilterData::ResolvedTrackObjects
Definition at line 56 of file SequencerFilterData.h.
ResolvedTracks
TMap<UE::Sequencer::TWeakViewModelPtr<UE::Sequencer::IOutlinerExtension>, UE::Sequencer::TWeakViewModelPtr<UE::Sequencer::ITrackExtension> > FSequencerFilterData::ResolvedTracks
Definition at line 55 of file SequencerFilterData.h.
TotalNodeCount
uint32 FSequencerFilterData::TotalNodeCount = 0 protected
Definition at line 62 of file SequencerFilterData.h.
The documentation for this struct was generated from the following file:
Editor/Sequencer/Public/Filters/SequencerFilterData.h