Unreal Engine 5.6 C++ API: UE::AnimNext::FInjectionUtils Struct Reference
UE::AnimNext::FInjectionUtils Struct Reference
#include "InjectionUtils.h"
Public Member Functions
UE_DEPRECATED (5.6, "Use PlayAnim that takes FPlayAnimArgs") ANIMNEXTANIMGRAPH_API static FInjectionRequestPtr PlayAnim(UAnimNextComponent *InComponent
Static Public Member Functions
static ANIMNEXTANIMGRAPH_API FInjectionRequestPtr Inject (UAnimNextComponent *InComponent, FInjectionRequestArgs &&InArgs, FInjectionLifetimeEvents &&InLifetimeEvents=FInjectionLifetimeEvents())
static ANIMNEXTANIMGRAPH_API FInjectionRequestPtr Inject (UObject *InHost, FModuleHandle InHandle, FInjectionRequestArgs &&InArgs, FInjectionLifetimeEvents &&InLifetimeEvents=FInjectionLifetimeEvents())
static ANIMNEXTANIMGRAPH_API FInjectionRequestPtr InjectAsset (UAnimNextComponent *InComponent, const FInjectionSite &InSite, UObject *InAsset, FAnimNextDataInterfacePayload &&InPayload=FAnimNextDataInterfacePayload(), UAnimNextComponent *InBindingComponent=nullptr, const FInjectionBlendSettings &InBlendInSettings=FInjectionBlendSettings(), const FInjectionBlendSettings &InBlendOutSettings=FInjectionBlendSettings(), FInjectionLifetimeEvents &&InLifetimeEvents=FInjectionLifetimeEvents())
static ANIMNEXTANIMGRAPH_API FInjectionRequestPtr InjectAsset (UObject *InHost, FModuleHandle InModuleHandle, const FInjectionSite &InSite, UObject *InAsset, FAnimNextDataInterfacePayload &&InPayload=FAnimNextDataInterfacePayload(), FModuleHandle InBindingModuleHandle=FModuleHandle(), const FInjectionBlendSettings &InBlendInSettings=FInjectionBlendSettings(), const FInjectionBlendSettings &InBlendOutSettings=FInjectionBlendSettings(), FInjectionLifetimeEvents &&InLifetimeEvents=FInjectionLifetimeEvents())
static ANIMNEXTANIMGRAPH_API FInjectionRequestPtr InjectEvaluationModifier (UAnimNextComponent *InComponent, const TSharedRef< IEvaluationModifier > &InEvaluationModifier, const FInjectionSite &InSite=FInjectionSite())
static ANIMNEXTANIMGRAPH_API FInjectionRequestPtr InjectEvaluationModifier (UObject *InHost, FModuleHandle InModuleHandle, const TSharedRef< IEvaluationModifier > &InEvaluationModifier, const FInjectionSite &InSite=FInjectionSite())
static ANIMNEXTANIMGRAPH_API FInjectionRequestPtr PlayAnim (UAnimNextComponent *InComponent, const FInjectionSite &InSite, UAnimSequence *InAnimSequence, const FPlayAnimArgs &InArgs=FPlayAnimArgs(), const FInjectionBlendSettings &InBlendInSettings=FInjectionBlendSettings(), const FInjectionBlendSettings &InBlendOutSettings=FInjectionBlendSettings(), FInjectionLifetimeEvents &&InLifetimeEvents=FInjectionLifetimeEvents())
static ANIMNEXTANIMGRAPH_API FInjectionRequestPtr PlayAnimHandle (UObject *InHost, FModuleHandle InModuleHandle, const FInjectionSite &InSite, UAnimSequence *InAnimSequence, const FPlayAnimArgs &InArgs=FPlayAnimArgs(), const FInjectionBlendSettings &InBlendInSettings=FInjectionBlendSettings(), const FInjectionBlendSettings &InBlendOutSettings=FInjectionBlendSettings(), FInjectionLifetimeEvents &&InLifetimeEvents=FInjectionLifetimeEvents())
static ANIMNEXTANIMGRAPH_API void Uninject (FInjectionRequestPtr InInjectionRequest)
Data Fields
const FInjectionSite UAnimSequence * InAnimSequence
const FInjectionSite UAnimSequence float float const FInjectionBlendSettings & InBlendInSettings = FInjectionBlendSettings()
const FInjectionSite UAnimSequence float float const FInjectionBlendSettings const FInjectionBlendSettings & InBlendOutSettings = FInjectionBlendSettings()
const FInjectionSite UAnimSequence float float const FInjectionBlendSettings const FInjectionBlendSettings FInjectionLifetimeEvents && InLifetimeEvents = FInjectionLifetimeEvents())
const FInjectionSite UAnimSequence float InPlayRate = 1.0f
const FInjectionSite & InSite
const FInjectionSite UAnimSequence float float InStartPosition = 0.0f
Detailed Description
Definition at line 44 of file InjectionUtils.h.
Member Function Documentation
Inject() [1/2]
ANIMNEXTANIMGRAPH_API FInjectionRequestPtr UE::AnimNext::FInjectionUtils::Inject (UAnimNextComponent * InComponent, FInjectionRequestArgs && InArgs, FInjectionLifetimeEvents && InLifetimeEvents = FInjectionLifetimeEvents()) static
References Inject(), and InLifetimeEvents.
Referenced by Inject(), and Inject().
Inject() [2/2]
ANIMNEXTANIMGRAPH_API FInjectionRequestPtr UE::AnimNext::FInjectionUtils::Inject (UObject * InHost, FModuleHandle InHandle, FInjectionRequestArgs && InArgs, FInjectionLifetimeEvents && InLifetimeEvents = FInjectionLifetimeEvents()) static
References Inject(), and InLifetimeEvents.
InjectAsset() [1/2]
ANIMNEXTANIMGRAPH_API FInjectionRequestPtr UE::AnimNext::FInjectionUtils::InjectAsset (UAnimNextComponent * InComponent, const FInjectionSite & InSite, UObject * InAsset, FAnimNextDataInterfacePayload && InPayload = FAnimNextDataInterfacePayload(), UAnimNextComponent * InBindingComponent = nullptr, const FInjectionBlendSettings & InBlendInSettings = FInjectionBlendSettings(), const FInjectionBlendSettings & InBlendOutSettings = FInjectionBlendSettings(), FInjectionLifetimeEvents && InLifetimeEvents = FInjectionLifetimeEvents()) static
References InBlendInSettings, InBlendOutSettings, InjectAsset(), InLifetimeEvents, and InSite.
Referenced by InjectAsset(), and InjectAsset().
InjectAsset() [2/2]
ANIMNEXTANIMGRAPH_API FInjectionRequestPtr UE::AnimNext::FInjectionUtils::InjectAsset (UObject * InHost, FModuleHandle InModuleHandle, const FInjectionSite & InSite, UObject * InAsset, FAnimNextDataInterfacePayload && InPayload = FAnimNextDataInterfacePayload(), FModuleHandle InBindingModuleHandle = FModuleHandle(), const FInjectionBlendSettings & InBlendInSettings = FInjectionBlendSettings(), const FInjectionBlendSettings & InBlendOutSettings = FInjectionBlendSettings(), FInjectionLifetimeEvents && InLifetimeEvents = FInjectionLifetimeEvents()) static
References InBlendInSettings, InBlendOutSettings, InjectAsset(), InLifetimeEvents, and InSite.
InjectEvaluationModifier() [1/2]
ANIMNEXTANIMGRAPH_API FInjectionRequestPtr UE::AnimNext::FInjectionUtils::InjectEvaluationModifier (UAnimNextComponent * InComponent, const TSharedRef< IEvaluationModifier > & InEvaluationModifier, const FInjectionSite & InSite = FInjectionSite()) static
References InjectEvaluationModifier(), and InSite.
Referenced by InjectEvaluationModifier(), and InjectEvaluationModifier().
InjectEvaluationModifier() [2/2]
ANIMNEXTANIMGRAPH_API FInjectionRequestPtr UE::AnimNext::FInjectionUtils::InjectEvaluationModifier (UObject * InHost, FModuleHandle InModuleHandle, const TSharedRef< IEvaluationModifier > & InEvaluationModifier, const FInjectionSite & InSite = FInjectionSite()) static
References InjectEvaluationModifier(), and InSite.
PlayAnim()
ANIMNEXTANIMGRAPH_API FInjectionRequestPtr UE::AnimNext::FInjectionUtils::PlayAnim (UAnimNextComponent * InComponent, const FInjectionSite & InSite, UAnimSequence * InAnimSequence, const FPlayAnimArgs & InArgs = FPlayAnimArgs(), const FInjectionBlendSettings & InBlendInSettings = FInjectionBlendSettings(), const FInjectionBlendSettings & InBlendOutSettings = FInjectionBlendSettings(), FInjectionLifetimeEvents && InLifetimeEvents = FInjectionLifetimeEvents()) static
References InAnimSequence, InBlendInSettings, InBlendOutSettings, InLifetimeEvents, InSite, and PlayAnim().
Referenced by PlayAnim(), and UE_DEPRECATED().
PlayAnimHandle()
ANIMNEXTANIMGRAPH_API FInjectionRequestPtr UE::AnimNext::FInjectionUtils::PlayAnimHandle (UObject * InHost, FModuleHandle InModuleHandle, const FInjectionSite & InSite, UAnimSequence * InAnimSequence, const FPlayAnimArgs & InArgs = FPlayAnimArgs(), const FInjectionBlendSettings & InBlendInSettings = FInjectionBlendSettings(), const FInjectionBlendSettings & InBlendOutSettings = FInjectionBlendSettings(), FInjectionLifetimeEvents && InLifetimeEvents = FInjectionLifetimeEvents()) static
References InAnimSequence, InBlendInSettings, InBlendOutSettings, InLifetimeEvents, InSite, and PlayAnimHandle().
Referenced by PlayAnimHandle().
UE_DEPRECATED()
UE::AnimNext::FInjectionUtils::UE_DEPRECATED (5. 6, "Use PlayAnim that takes FPlayAnimArgs")
References PlayAnim().
Uninject()
ANIMNEXTANIMGRAPH_API void UE::AnimNext::FInjectionUtils::Uninject (FInjectionRequestPtr InInjectionRequest) static
References Uninject().
Referenced by Uninject().
Field Documentation
InAnimSequence
const FInjectionSite UAnimSequence* UE::AnimNext::FInjectionUtils::InAnimSequence
Definition at line 50 of file InjectionUtils.h.
Referenced by PlayAnim(), and PlayAnimHandle().
InBlendInSettings
const FInjectionSite UAnimSequence float float const FInjectionBlendSettings& UE::AnimNext::FInjectionUtils::InBlendInSettings = FInjectionBlendSettings()
Definition at line 53 of file InjectionUtils.h.
Referenced by InjectAsset(), InjectAsset(), PlayAnim(), and PlayAnimHandle().
InBlendOutSettings
const FInjectionSite UAnimSequence float float const FInjectionBlendSettings const FInjectionBlendSettings& UE::AnimNext::FInjectionUtils::InBlendOutSettings = FInjectionBlendSettings()
Definition at line 54 of file InjectionUtils.h.
Referenced by InjectAsset(), InjectAsset(), PlayAnim(), and PlayAnimHandle().
InLifetimeEvents
const FInjectionSite UAnimSequence float float const FInjectionBlendSettings const FInjectionBlendSettings FInjectionLifetimeEvents&& UE::AnimNext::FInjectionUtils::InLifetimeEvents = FInjectionLifetimeEvents())
Definition at line 55 of file InjectionUtils.h.
Referenced by Inject(), Inject(), InjectAsset(), InjectAsset(), PlayAnim(), and PlayAnimHandle().
InPlayRate
const FInjectionSite UAnimSequence float UE::AnimNext::FInjectionUtils::InPlayRate = 1.0f
Definition at line 51 of file InjectionUtils.h.
InSite
const FInjectionSite& UE::AnimNext::FInjectionUtils::InSite
Definition at line 49 of file InjectionUtils.h.
Referenced by InjectAsset(), InjectAsset(), InjectEvaluationModifier(), InjectEvaluationModifier(), PlayAnim(), and PlayAnimHandle().
InStartPosition
const FInjectionSite UAnimSequence float float UE::AnimNext::FInjectionUtils::InStartPosition = 0.0f
Definition at line 52 of file InjectionUtils.h.
The documentation for this struct was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Experimental/AnimNextAnimGraph/Source/AnimNextAnimGraph/Public/Injection/InjectionUtils.h