Unreal Engine 5.6 C++ API: Audio::FQuartzOffset Struct Reference
Audio::FQuartzOffset Struct Reference
#include "QuartzQuantizationUtilities.h"
Public Member Functions
FQuartzOffset (double InOffsetInMilliseconds=0.0)
FQuartzOffset (EQuartzCommandQuantization InDuration, double InMultiplier)
int32 GetOffsetInAudioFrames (const FQuartzClockTickRate &InTickRate)
bool IsSet () const
bool IsSetAsMilliseconds () const
bool IsSetAsMusicalDuration () const
bool operator== (const FQuartzOffset &Other) const
void SetOffsetInMilliseconds (double InMilliseconds)
void SetOffsetMusical (EQuartzCommandQuantization Duration, double Multiplier)
Private Attributes
TOptional< TPair< EQuartzCommandQuantization, double > > OffsetAsDuration
TOptional< double > OffsetInMilliseconds
Detailed Description
Definition at line 397 of file QuartzQuantizationUtilities.h.
Constructor & Destructor Documentation
FQuartzOffset() [1/2]
Audio::FQuartzOffset::FQuartzOffset (double InOffsetInMilliseconds = 0.0)
Definition at line 177 of file QuartzSubscription.cpp.
References MoveTemp(), and OffsetInMilliseconds.
Referenced by operator==().
FQuartzOffset() [2/2]
Audio::FQuartzOffset::FQuartzOffset (EQuartzCommandQuantization InDuration, double InMultiplier)
Definition at line 182 of file QuartzSubscription.cpp.
References MoveTemp(), and OffsetAsDuration.
Member Function Documentation
GetOffsetInAudioFrames()
int32 Audio::FQuartzOffset::GetOffsetInAudioFrames (const FQuartzClockTickRate & InTickRate)
Definition at line 209 of file QuartzSubscription.cpp.
References check, ensure, Audio::FQuartzClockTickRate::GetFramesPerDuration(), Audio::FQuartzClockTickRate::GetSampleRate(), Multiplier, OffsetAsDuration, and OffsetInMilliseconds.
IsSet()
bool Audio::FQuartzOffset::IsSet () const inline
Definition at line 409 of file QuartzQuantizationUtilities.h.
References IsSetAsMilliseconds(), and IsSetAsMusicalDuration().
IsSetAsMilliseconds()
bool Audio::FQuartzOffset::IsSetAsMilliseconds () const
Definition at line 199 of file QuartzSubscription.cpp.
References OffsetInMilliseconds.
Referenced by IsSet().
IsSetAsMusicalDuration()
bool Audio::FQuartzOffset::IsSetAsMusicalDuration () const
Definition at line 204 of file QuartzSubscription.cpp.
References OffsetAsDuration.
Referenced by IsSet().
operator==()
bool Audio::FQuartzOffset::operator== (const FQuartzOffset & Other) const
Definition at line 761 of file QuartzQuantizationUtilities.cpp.
References FQuartzOffset(), OffsetAsDuration, OffsetInMilliseconds, and Other.
SetOffsetInMilliseconds()
void Audio::FQuartzOffset::SetOffsetInMilliseconds (double InMilliseconds)
Definition at line 187 of file QuartzSubscription.cpp.
References OffsetAsDuration, and OffsetInMilliseconds.
SetOffsetMusical()
void Audio::FQuartzOffset::SetOffsetMusical (EQuartzCommandQuantization Duration, double Multiplier)
Definition at line 193 of file QuartzSubscription.cpp.
References Duration, Multiplier, OffsetAsDuration, and OffsetInMilliseconds.
Field Documentation
OffsetAsDuration
TOptional<TPair<EQuartzCommandQuantization, double> > Audio::FQuartzOffset::OffsetAsDuration private
Definition at line 423 of file QuartzQuantizationUtilities.h.
Referenced by FQuartzOffset(), GetOffsetInAudioFrames(), IsSetAsMusicalDuration(), operator==(), SetOffsetInMilliseconds(), and SetOffsetMusical().
OffsetInMilliseconds
TOptional<double> Audio::FQuartzOffset::OffsetInMilliseconds private
Definition at line 422 of file QuartzQuantizationUtilities.h.
Referenced by FQuartzOffset(), GetOffsetInAudioFrames(), IsSetAsMilliseconds(), operator==(), SetOffsetInMilliseconds(), and SetOffsetMusical().
The documentation for this struct was generated from the following files:
Runtime/Engine/Classes/Sound/QuartzQuantizationUtilities.h
Runtime/Engine/Classes/Sound/QuartzQuantizationUtilities.cpp
Runtime/Engine/Classes/Sound/QuartzSubscription.cpp