Unreal Engine 5.6 C++ API: UE::Sequencer::TViewModelExtensionCollection< T > Struct Template Reference
UE::Sequencer::TViewModelExtensionCollection< T > Struct Template Reference
Strongly typed version of FViewModelExtensionCollection.
#include "ViewModelExtensionCollection.h"
Public Member Functions
TViewModelExtensionCollection ()
TViewModelExtensionCollection (TWeakPtr< FViewModel > InWeakModel)
TViewModelExtensionCollection (TWeakPtr< FViewModel > InWeakModel, int32 InDesiredRecursionDepth)
template<typename Predicate>
void FilterExtensions (Predicate &&InPredicate)
TArrayView< T *const > GetExtensions () const
Additional Inherited Members
Protected Member Functions inherited from UE::Sequencer::FViewModelExtensionCollection
void Destroy ()
TSharedPtr< FViewModel > GetObservedModel () const
void Initialize ()
virtual void OnExtensionsDirtied ()
void Reinitialize (TWeakPtr< FViewModel > InWeakModel, int32 InDesiredRecursionDepth=-1)
Protected Member Functions inherited from FNoncopyable
FNoncopyable ()
~FNoncopyable ()
Detailed Description
template<typename T>
struct UE::Sequencer::TViewModelExtensionCollection< T >
Strongly typed version of FViewModelExtensionCollection.
Definition at line 87 of file ViewModelExtensionCollection.h.
Constructor & Destructor Documentation
TViewModelExtensionCollection() [1/3]
template<typename T> UE::Sequencer::TViewModelExtensionCollection< T >::TViewModelExtensionCollection () inline
Definition at line 89 of file ViewModelExtensionCollection.h.
References UE::Sequencer::FViewModelExtensionCollection::FViewModelExtensionCollection(), and ID.
TViewModelExtensionCollection() [2/3]
template<typename T> UE::Sequencer::TViewModelExtensionCollection< T >::TViewModelExtensionCollection (TWeakPtr< FViewModel > InWeakModel) inline explicit
Definition at line 93 of file ViewModelExtensionCollection.h.
References UE::Sequencer::FViewModelExtensionCollection::FViewModelExtensionCollection(), and ID.
TViewModelExtensionCollection() [3/3]
template<typename T> UE::Sequencer::TViewModelExtensionCollection< T >::TViewModelExtensionCollection (TWeakPtr< FViewModel > InWeakModel, int32 InDesiredRecursionDepth) inline explicit
Definition at line 97 of file ViewModelExtensionCollection.h.
References UE::Sequencer::FViewModelExtensionCollection::FViewModelExtensionCollection(), and ID.
Member Function Documentation
FilterExtensions()
template<typename T> template<typename Predicate> void UE::Sequencer::TViewModelExtensionCollection< T >::FilterExtensions (Predicate && InPredicate) inline
Definition at line 107 of file ViewModelExtensionCollection.h.
References UE::Sequencer::FViewModelExtensionCollection::ExtensionContainer, No, and Predicate.
GetExtensions()
template<typename T> TArrayView< T *const > UE::Sequencer::TViewModelExtensionCollection< T >::GetExtensions () const inline
Definition at line 101 of file ViewModelExtensionCollection.h.
References UE::Sequencer::FViewModelExtensionCollection::GetExtensions().
The documentation for this struct was generated from the following file:
Editor/SequencerCore/Public/MVVM/Extensions/ViewModelExtensionCollection.h