Unreal Engine 5.6 C++ API: UE::Transaction::FPersistentObjectRef Struct Reference
UE::Transaction::FPersistentObjectRef Struct Reference
This type is necessary because the blueprint system is destroying and creating CDOs at edit time (usually on compile, but also on load), but also stores user entered data in the CDO.
#include "TransactionCommon.h"
Public Member Functions
FPersistentObjectRef ()=default
FPersistentObjectRef (UObject *InObject)
void AddReferencedObjects (FReferenceCollector &Collector)
UObject * Get () const
bool IsRootObjectReference () const
bool IsSubObjectReference () const
bool Serialize (FArchive &Ar)
Private Types
enum class EReferenceType : uint8 { Unknown , RootObject , SubObject }
This enum represents all of the different special cases we are handling with this type.
Private Attributes
TWeakObjectPtr< UObject > CachedRootObject
Cached pointers corresponding to RootObject when ReferenceType==SubObject (.
TArray< TWeakObjectPtr< UObject >, TInlineAllocator< 4 > > CachedSubObjectHierarchy
Cache of pointers corresponding to the items within SubObjectHierarchyIDs when ReferenceType==SubObject (.
EReferenceType ReferenceType = EReferenceType::Unknown
The reference type we're handling.
TObjectPtr< UObject > RootObject = nullptr
Stores the object pointer when ReferenceType==RootObject, and the outermost pointer of the sub-object chain when when ReferenceType==SubObject.
TArray< FName, TInlineAllocator< 4 > > SubObjectHierarchyIDs
Stores the sub-object name chain when ReferenceType==SubObject.
Friends
uint32 GetTypeHash (const FPersistentObjectRef &InObjRef)
bool operator!= (const FPersistentObjectRef &LHS, const FPersistentObjectRef &RHS)
FArchive & operator<< (FArchive &Ar, FPersistentObjectRef &ReferencedObject)
bool operator== (const FPersistentObjectRef &LHS, const FPersistentObjectRef &RHS)
Detailed Description
This type is necessary because the blueprint system is destroying and creating CDOs at edit time (usually on compile, but also on load), but also stores user entered data in the CDO.
We "need" changes to a CDO to persist across instances because as we undo and redo we need to apply changes to different instances of the CDO - alternatively we could destroy and create the CDO as part of a transaction (this alternative is the reason for the bunny ears around need).
DanO: My long term preference is for the editor to use a dynamic, mutable type (rather than the CDO) to store editor data. The CDO can then be re-instanced (or not) as runtime code requires.
Definition at line 32 of file TransactionCommon.h.
Member Enumeration Documentation
EReferenceType
enum class UE::Transaction::FPersistentObjectRef::EReferenceType : uint8 strong private
This enum represents all of the different special cases we are handling with this type.
Enumerator
Unknown
RootObject
SubObject
Definition at line 85 of file TransactionCommon.h.
Constructor & Destructor Documentation
FPersistentObjectRef() [1/2]
UE::Transaction::FPersistentObjectRef::FPersistentObjectRef () default
Referenced by GetTypeHash, operator!=, operator<<, and operator==.
FPersistentObjectRef() [2/2]
UE::Transaction::FPersistentObjectRef::FPersistentObjectRef (UObject * InObject) explicit
Member Function Documentation
AddReferencedObjects()
void UE::Transaction::FPersistentObjectRef::AddReferencedObjects (FReferenceCollector & Collector)
Get()
UObject * UE::Transaction::FPersistentObjectRef::Get () const
IsRootObjectReference()
bool UE::Transaction::FPersistentObjectRef::IsRootObjectReference () const inline
Definition at line 69 of file TransactionCommon.h.
References ReferenceType, and RootObject.
IsSubObjectReference()
bool UE::Transaction::FPersistentObjectRef::IsSubObjectReference () const inline
Definition at line 74 of file TransactionCommon.h.
References ReferenceType, and SubObject.
Serialize()
bool UE::Transaction::FPersistentObjectRef::Serialize (FArchive & Ar) inline
Definition at line 38 of file TransactionCommon.h.
References Ar.
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FPersistentObjectRef & InObjRef) friend
Definition at line 64 of file TransactionCommon.h.
References FPersistentObjectRef(), GetTypeHash, HashCombine(), ReferenceType, and RootObject.
Referenced by GetTypeHash.
operator!=
bool operator!= (const FPersistentObjectRef & LHS, const FPersistentObjectRef & RHS) friend
Definition at line 59 of file TransactionCommon.h.
References FPersistentObjectRef().
operator<<
FArchive & operator<< (FArchive & Ar, FPersistentObjectRef & ReferencedObject) friend
Definition at line 44 of file TransactionCommon.h.
References FPersistentObjectRef(), Ar, ReferenceType, RootObject, and SubObjectHierarchyIDs.
operator==
bool operator== (const FPersistentObjectRef & LHS, const FPersistentObjectRef & RHS) friend
Definition at line 52 of file TransactionCommon.h.
References FPersistentObjectRef(), ReferenceType, RootObject, SubObject, and SubObjectHierarchyIDs.
Field Documentation
CachedRootObject
TWeakObjectPtr<UObject> UE::Transaction::FPersistentObjectRef::CachedRootObject mutable private
Cached pointers corresponding to RootObject when ReferenceType==SubObject (.
Note
cache needs testing on access as it may have become stale)
Definition at line 100 of file TransactionCommon.h.
CachedSubObjectHierarchy
TArray<TWeakObjectPtr<UObject>, TInlineAllocator<4> > UE::Transaction::FPersistentObjectRef::CachedSubObjectHierarchy mutable private
Cache of pointers corresponding to the items within SubObjectHierarchyIDs when ReferenceType==SubObject (.
Note
cache needs testing on access as it may have become stale)
Definition at line 102 of file TransactionCommon.h.
ReferenceType
EReferenceType UE::Transaction::FPersistentObjectRef::ReferenceType = EReferenceType::Unknown private
The reference type we're handling.
Definition at line 93 of file TransactionCommon.h.
Referenced by GetTypeHash, IsRootObjectReference(), IsSubObjectReference(), operator<<, and operator==.
RootObject
TObjectPtr<UObject> UE::Transaction::FPersistentObjectRef::RootObject = nullptr private
Stores the object pointer when ReferenceType==RootObject, and the outermost pointer of the sub-object chain when when ReferenceType==SubObject.
Definition at line 95 of file TransactionCommon.h.
Referenced by GetTypeHash, operator<<, and operator==.
SubObjectHierarchyIDs
TArray<FName, TInlineAllocator<4> > UE::Transaction::FPersistentObjectRef::SubObjectHierarchyIDs private
Stores the sub-object name chain when ReferenceType==SubObject.
Definition at line 97 of file TransactionCommon.h.
Referenced by operator<<, and operator==.
The documentation for this struct was generated from the following file:
Runtime/Engine/Public/TransactionCommon.h