Unreal Engine 5.6 C++ API: FSquare2DGridHelper::FGridLevel::FGridCellDataChunk Struct Reference
FSquare2DGridHelper::FGridLevel::FGridCellDataChunk Struct Reference
#include "RuntimeSpatialHashGridHelper.h"
Public Member Functions
FGridCellDataChunk (const TArray< const UDataLayerInstance * > &InDataLayers, const FGuid &InContentBundleID)
void AddActorSetInstance (const IStreamingGenerationContext::FActorSetInstance *ActorSetInstance)
const TArray< const IStreamingGenerationContext::FActorSetInstance * > & GetActorSetInstances () const
FGuid GetContentBundleID () const
const TArray< const UDataLayerInstance * > & GetDataLayers () const
const FDataLayersID & GetDataLayersID () const
bool HasDataLayers () const
bool operator== (const FGridCellDataChunk &InGridCellDataChunk) const
Private Attributes
TArray< const IStreamingGenerationContext::FActorSetInstance * > ActorSetInstances
FGuid ContentBundleID
TArray< const UDataLayerInstance * > DataLayers
FDataLayersID DataLayersID
Friends
uint32 GetTypeHash (const FGridCellDataChunk &InGridCellDataChunk)
Detailed Description
Definition at line 270 of file RuntimeSpatialHashGridHelper.h.
Constructor & Destructor Documentation
FGridCellDataChunk()
FSquare2DGridHelper::FGridLevel::FGridCellDataChunk::FGridCellDataChunk (const TArray< const UDataLayerInstance * > & InDataLayers, const FGuid & InContentBundleID) inline
Definition at line 272 of file RuntimeSpatialHashGridHelper.h.
References ContentBundleID, DataLayers, DataLayersID, and Algo::TransformIf().
Referenced by GetTypeHash, and operator==().
Member Function Documentation
AddActorSetInstance()
void FSquare2DGridHelper::FGridLevel::FGridCellDataChunk::AddActorSetInstance (const IStreamingGenerationContext::FActorSetInstance * ActorSetInstance) inline
Definition at line 279 of file RuntimeSpatialHashGridHelper.h.
References ActorSetInstances.
Referenced by FSquare2DGridHelper::FGridLevel::FGridCell::AddActorSetInstance().
GetActorSetInstances()
const TArray< const IStreamingGenerationContext::FActorSetInstance * > & FSquare2DGridHelper::FGridLevel::FGridCellDataChunk::GetActorSetInstances () const inline
Definition at line 280 of file RuntimeSpatialHashGridHelper.h.
References ActorSetInstances.
GetContentBundleID()
FGuid FSquare2DGridHelper::FGridLevel::FGridCellDataChunk::GetContentBundleID () const inline
Definition at line 284 of file RuntimeSpatialHashGridHelper.h.
References ContentBundleID.
GetDataLayers()
const TArray< const UDataLayerInstance * > & FSquare2DGridHelper::FGridLevel::FGridCellDataChunk::GetDataLayers () const inline
Definition at line 282 of file RuntimeSpatialHashGridHelper.h.
References DataLayers.
GetDataLayersID()
const FDataLayersID & FSquare2DGridHelper::FGridLevel::FGridCellDataChunk::GetDataLayersID () const inline
Definition at line 283 of file RuntimeSpatialHashGridHelper.h.
References DataLayersID.
HasDataLayers()
bool FSquare2DGridHelper::FGridLevel::FGridCellDataChunk::HasDataLayers () const inline
Definition at line 281 of file RuntimeSpatialHashGridHelper.h.
References DataLayers.
operator==()
bool FSquare2DGridHelper::FGridLevel::FGridCellDataChunk::operator== (const FGridCellDataChunk & InGridCellDataChunk) const inline
Definition at line 285 of file RuntimeSpatialHashGridHelper.h.
References FGridCellDataChunk(), and DataLayersID.
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FGridCellDataChunk & InGridCellDataChunk) friend
Definition at line 286 of file RuntimeSpatialHashGridHelper.h.
References FGridCellDataChunk(), DataLayersID, and GetTypeHash.
Referenced by GetTypeHash.
Field Documentation
ActorSetInstances
TArray<const IStreamingGenerationContext::FActorSetInstance*> FSquare2DGridHelper::FGridLevel::FGridCellDataChunk::ActorSetInstances private
Definition at line 289 of file RuntimeSpatialHashGridHelper.h.
Referenced by AddActorSetInstance(), and GetActorSetInstances().
ContentBundleID
FGuid FSquare2DGridHelper::FGridLevel::FGridCellDataChunk::ContentBundleID private
Definition at line 292 of file RuntimeSpatialHashGridHelper.h.
Referenced by FGridCellDataChunk(), and GetContentBundleID().
DataLayers
TArray<const UDataLayerInstance*> FSquare2DGridHelper::FGridLevel::FGridCellDataChunk::DataLayers private
Definition at line 290 of file RuntimeSpatialHashGridHelper.h.
Referenced by FGridCellDataChunk(), GetDataLayers(), and HasDataLayers().
DataLayersID
FDataLayersID FSquare2DGridHelper::FGridLevel::FGridCellDataChunk::DataLayersID private
Definition at line 291 of file RuntimeSpatialHashGridHelper.h.
Referenced by FGridCellDataChunk(), GetDataLayersID(), GetTypeHash, and operator==().
The documentation for this struct was generated from the following file:
Runtime/Engine/Public/WorldPartition/RuntimeSpatialHash/RuntimeSpatialHashGridHelper.h