Unreal Engine 5.6 C++ API: FPositioningData Struct Reference
FPositioningData Struct Reference
Positioning data struct.
#include "ActorPositioning.h"
Public Member Functions
FPositioningData (const FVector &InSurfaceLocation, const FVector &InSurfaceNormal)
FPositioningData & AlignToSurfaceRotation (bool bInAlignRotation)
Whether to align to the surface normal, or just snap to its position.
FPositioningData & UseFactory (const UActorFactory *InActorFactory)
A factory to use for the alignment.
FPositioningData & UsePlacementExtent (const FVector &InPlacementExtent)
Placement extent offset to use (default = 0,0,0)
FPositioningData & UseStartTransform (const FTransform &InStartTransform)
The start transform we are using for positioning.
Data Fields
const UActorFactory * ActorFactory
bool bAlignRotation
FVector PlacementExtent
FTransform StartTransform
FVector SurfaceLocation
The surface location we want to position to.
FVector SurfaceNormal
The surface normal we want to potentially align to.
Detailed Description
Positioning data struct.
Definition at line 15 of file ActorPositioning.h.
Constructor & Destructor Documentation
FPositioningData()
FPositioningData::FPositioningData (const FVector & InSurfaceLocation, const FVector & InSurfaceNormal) inline
Definition at line 17 of file ActorPositioning.h.
References ActorFactory, bAlignRotation, FVector, GetDefault(), PlacementExtent, StartTransform, SurfaceLocation, and SurfaceNormal.
Referenced by FSnappedPositioningData::FSnappedPositioningData(), AlignToSurfaceRotation(), UseFactory(), UsePlacementExtent(), and UseStartTransform().
Member Function Documentation
AlignToSurfaceRotation()
FPositioningData & FPositioningData::AlignToSurfaceRotation (bool bInAlignRotation) inline
Whether to align to the surface normal, or just snap to its position.
Definition at line 48 of file ActorPositioning.h.
References FPositioningData(), and bAlignRotation.
UseFactory()
FPositioningData & FPositioningData::UseFactory (const UActorFactory * InActorFactory) inline
A factory to use for the alignment.
Factories define the alignment routine and spawn offset amounts if necessary.
Definition at line 44 of file ActorPositioning.h.
References FPositioningData(), and ActorFactory.
UsePlacementExtent()
FPositioningData & FPositioningData::UsePlacementExtent (const FVector & InPlacementExtent) inline
Placement extent offset to use (default = 0,0,0)
Definition at line 36 of file ActorPositioning.h.
References FPositioningData(), FVector, and PlacementExtent.
UseStartTransform()
FPositioningData & FPositioningData::UseStartTransform (const FTransform & InStartTransform) inline
The start transform we are using for positioning.
Ensures a natural alignment to the surface when using rotation. (default = Identity)
Definition at line 40 of file ActorPositioning.h.
References FPositioningData(), and StartTransform.
Field Documentation
ActorFactory
const UActorFactory* FPositioningData::ActorFactory
Definition at line 45 of file ActorPositioning.h.
Referenced by FPositioningData(), UseFactory(), and FSnappedPositioningData::UseFactory().
bAlignRotation
bool FPositioningData::bAlignRotation
Definition at line 49 of file ActorPositioning.h.
Referenced by FPositioningData(), AlignToSurfaceRotation(), and FSnappedPositioningData::AlignToSurfaceRotation().
PlacementExtent
FVector FPositioningData::PlacementExtent
Definition at line 37 of file ActorPositioning.h.
Referenced by FPositioningData(), UsePlacementExtent(), and FSnappedPositioningData::UsePlacementExtent().
StartTransform
FTransform FPositioningData::StartTransform
Definition at line 41 of file ActorPositioning.h.
Referenced by FPositioningData(), UseStartTransform(), and FSnappedPositioningData::UseStartTransform().
SurfaceLocation
FVector FPositioningData::SurfaceLocation
The surface location we want to position to.
Definition at line 30 of file ActorPositioning.h.
Referenced by FPositioningData().
SurfaceNormal
FVector FPositioningData::SurfaceNormal
The surface normal we want to potentially align to.
Definition at line 33 of file ActorPositioning.h.
Referenced by FPositioningData().
The documentation for this struct was generated from the following file:
Editor/UnrealEd/Public/Editor/ActorPositioning.h