Unreal Engine 5.6 C++ API: FLevelInstanceActorGuid Struct Reference
FLevelInstanceActorGuid Struct Reference
Helper struct that allows serializing the ActorGuid for runtime use.
#include "LevelInstanceActorGuid.h"
Public Member Functions
FLevelInstanceActorGuid ()
FLevelInstanceActorGuid (AActor *InActor)
const FGuid & GetGuid () const
bool IsValid () const
Data Fields
TObjectPtr< AActor > Actor = nullptr
FGuid ActorGuid
Private Member Functions
const FGuid & GetGuid_Internal () const
Friends
FArchive & operator<< (FArchive &Ar, FLevelInstanceActorGuid &LevelInstanceActorGuid)
Detailed Description
Helper struct that allows serializing the ActorGuid for runtime use.
Definition at line 14 of file LevelInstanceActorGuid.h.
Constructor & Destructor Documentation
FLevelInstanceActorGuid() [1/2]
FLevelInstanceActorGuid::FLevelInstanceActorGuid () inline
Definition at line 17 of file LevelInstanceActorGuid.h.
References FLevelInstanceActorGuid().
Referenced by FLevelInstanceActorGuid(), and operator<<.
FLevelInstanceActorGuid() [2/2]
FLevelInstanceActorGuid::FLevelInstanceActorGuid (AActor * InActor) inline
Definition at line 19 of file LevelInstanceActorGuid.h.
References Actor.
Member Function Documentation
GetGuid()
const FGuid & FLevelInstanceActorGuid::GetGuid () const
GetGuid_Internal()
const FGuid & FLevelInstanceActorGuid::GetGuid_Internal () const private
IsValid()
bool FLevelInstanceActorGuid::IsValid () const
Friends And Related Symbol Documentation
operator<<
FArchive & operator<< (FArchive & Ar, FLevelInstanceActorGuid & LevelInstanceActorGuid) friend
References FLevelInstanceActorGuid(), and Ar.
Field Documentation
Actor
TObjectPtr<AActor> FLevelInstanceActorGuid::Actor = nullptr
Definition at line 28 of file LevelInstanceActorGuid.h.
Referenced by FLevelInstanceActorGuid().
ActorGuid
FGuid FLevelInstanceActorGuid::ActorGuid
Definition at line 29 of file LevelInstanceActorGuid.h.
The documentation for this struct was generated from the following file:
Runtime/Engine/Public/LevelInstance/LevelInstanceActorGuid.h