Unreal Engine 5.6 C++ API: FCameraRectangle Struct Reference
FCameraRectangle Struct Reference
Struct containing:
#include "RectangleMarqueeMechanic.h"
Data Structures
struct FRectangleInPlane
Public Types
using FAxisAlignedBox2 = UE::Geometry::TAxisAlignedBox2<FVector::FReal>
using FGeometrySet3 = UE::Geometry::FGeometrySet3
using FPlane3 = UE::Geometry::TPlane3<FVector::FReal>
using FSegment2 = UE::Geometry::TSegment2<FVector::FReal>
using FVector2 = UE::Math::TVector2<FVector::FReal>
Public Member Functions
MODELINGCOMPONENTS_API FConvexVolume FrustumAsConvexVolume () const
MODELINGCOMPONENTS_API void Initialize ()
MODELINGCOMPONENTS_API bool IsProjectedPointInRectangle (const FVector &Point) const
MODELINGCOMPONENTS_API bool IsProjectedSegmentIntersectingRectangle (const FVector &Endpoint1, const FVector &Endpoint2) const
FVector PerspectiveProjection (const FPlane3 &Plane, const FVector &Point) const
FVector2 Point3DToPointUV (const FPlane3 &Plane, const FVector &Point3DInPlane) const
FVector PointUVToPoint3D (const FPlane3 &Plane, const FVector2 &PointUV) const
MODELINGCOMPONENTS_API FRectangleInPlane ProjectSelectionDomain (double OffsetFromCameraPlane=0.) const
Static Public Member Functions
static FVector OrthographicProjection (const FPlane3 &Plane, const FVector &Point)
Data Fields
bool bIsInitialized = false
FViewCameraState CameraState
FInputDeviceRay RectangleEndRay = FInputDeviceRay(FRay())
FInputDeviceRay RectangleStartRay = FInputDeviceRay(FRay())
FRectangleInPlane SelectionDomain
Detailed Description
Struct containing:
camera information,
input device rays used to define the corners of a rectangle contained in a selection plane, the device ray screen positions could be used to change the selection behavior when dragging from the top right to bottom left or vice-versa
Definition at line 30 of file RectangleMarqueeMechanic.h.
Member Typedef Documentation
FAxisAlignedBox2
using FCameraRectangle::FAxisAlignedBox2 = UE::Geometry::TAxisAlignedBox2<FVector::FReal>
Definition at line 33 of file RectangleMarqueeMechanic.h.
FGeometrySet3
using FCameraRectangle::FGeometrySet3 = UE::Geometry::FGeometrySet3
Definition at line 32 of file RectangleMarqueeMechanic.h.
FPlane3
using FCameraRectangle::FPlane3 = UE::Geometry::TPlane3<FVector::FReal>
Definition at line 34 of file RectangleMarqueeMechanic.h.
FSegment2
using FCameraRectangle::FSegment2 = UE::Geometry::TSegment2<FVector::FReal>
Definition at line 35 of file RectangleMarqueeMechanic.h.
FVector2
using FCameraRectangle::FVector2 = UE::Math::TVector2<FVector::FReal>
Definition at line 36 of file RectangleMarqueeMechanic.h.
Member Function Documentation
FrustumAsConvexVolume()
MODELINGCOMPONENTS_API FConvexVolume FCameraRectangle::FrustumAsConvexVolume () const
References UE_API.
Initialize()
MODELINGCOMPONENTS_API void FCameraRectangle::Initialize ()
References UE_API.
IsProjectedPointInRectangle()
MODELINGCOMPONENTS_API bool FCameraRectangle::IsProjectedPointInRectangle (const FVector & Point) const
References FVector, Point, and UE_API.
IsProjectedSegmentIntersectingRectangle()
MODELINGCOMPONENTS_API bool FCameraRectangle::IsProjectedSegmentIntersectingRectangle (const FVector & Endpoint1, const FVector & Endpoint2) const
References FVector, and UE_API.
OrthographicProjection()
FVector FCameraRectangle::OrthographicProjection (const FPlane3 & Plane, const FVector & Point) inline static
Definition at line 73 of file RectangleMarqueeMechanic.h.
References FVector, Plane, Point, and UE::Math::TVector< double >::PointPlaneProject().
PerspectiveProjection()
FVector FCameraRectangle::PerspectiveProjection (const FPlane3 & Plane, const FVector & Point) const inline
Definition at line 80 of file RectangleMarqueeMechanic.h.
References bIsInitialized, CameraState, checkSlow, ensure, FVector, Plane, Point, and FMath::RayPlaneIntersection().
Point3DToPointUV()
FVector2 FCameraRectangle::Point3DToPointUV (const FPlane3 & Plane, const FVector & Point3DInPlane) const inline
Definition at line 92 of file RectangleMarqueeMechanic.h.
References bIsInitialized, CameraState, UE::Math::TVector< double >::DotProduct(), ensure, FVector, and Plane.
PointUVToPoint3D()
FVector FCameraRectangle::PointUVToPoint3D (const FPlane3 & Plane, const FVector2 & PointUV) const inline
Definition at line 103 of file RectangleMarqueeMechanic.h.
References bIsInitialized, CameraState, ensure, FVector, and Plane.
ProjectSelectionDomain()
MODELINGCOMPONENTS_API FRectangleInPlane FCameraRectangle::ProjectSelectionDomain (double OffsetFromCameraPlane = 0.) const
References UE_API.
Field Documentation
bIsInitialized
bool FCameraRectangle::bIsInitialized = false
Definition at line 54 of file RectangleMarqueeMechanic.h.
Referenced by PerspectiveProjection(), Point3DToPointUV(), and PointUVToPoint3D().
CameraState
FViewCameraState FCameraRectangle::CameraState
Definition at line 38 of file RectangleMarqueeMechanic.h.
Referenced by PerspectiveProjection(), Point3DToPointUV(), and PointUVToPoint3D().
RectangleEndRay
FInputDeviceRay FCameraRectangle::RectangleEndRay = FInputDeviceRay(FRay())
Definition at line 40 of file RectangleMarqueeMechanic.h.
RectangleStartRay
FInputDeviceRay FCameraRectangle::RectangleStartRay = FInputDeviceRay(FRay())
Definition at line 39 of file RectangleMarqueeMechanic.h.
SelectionDomain
FRectangleInPlane FCameraRectangle::SelectionDomain
Definition at line 49 of file RectangleMarqueeMechanic.h.
The documentation for this struct was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/MeshModelingToolset/Source/ModelingComponents/Public/Mechanics/RectangleMarqueeMechanic.h