Unreal Engine 5.6 C++ API: FScriptName Struct Reference
FScriptName Struct Reference
The full amount of data required to reconstruct a case-preserving name This will be the maximum size of an FName across all values of WITH_CASE_PRESERVING_NAME and UE_FNAME_OUTLINE_NUMBER and is used to store an FName in cases where the size of a name must be constant between build configurations (eg, blueprint bytecode) the layout is not guaranteed to be the same as FName even if the size is the same, so memory cannot be reinterpreted between the two.
#include "NameTypes.h"
Public Member Functions
FScriptName ()
FORCEINLINE FScriptName (const FName &Name)
FScriptName (EName Ename)
FORCEINLINE bool IsNone () const
bool operator== (EName Name)
FString ToString () const
FUtf8String ToUtf8String () const
Data Fields
friend FName
Private Attributes
FNameEntryId ComparisonIndex
Encoded address of name entry (used to find String portion of the string/number pair used for comparison)
FNameEntryId DisplayIndex
Encoded address of name entry (used to find String portion of the string/number pair used for display)
uint32 Number = 0
Number portion of the string/number pair (stored internally as 1 more than actual, so zero'd memory will be the default, no-instance case)
Friends
FORCEINLINE uint32 GetTypeHash (FScriptName Name)
FORCEINLINE bool operator!= (FScriptName Lhs, FScriptName Rhs)
FORCEINLINE bool operator== (FScriptName Lhs, FScriptName Rhs)
Detailed Description
The full amount of data required to reconstruct a case-preserving name This will be the maximum size of an FName across all values of WITH_CASE_PRESERVING_NAME and UE_FNAME_OUTLINE_NUMBER and is used to store an FName in cases where the size of a name must be constant between build configurations (eg, blueprint bytecode) the layout is not guaranteed to be the same as FName even if the size is the same, so memory cannot be reinterpreted between the two.
The layout here must be as expected by FScriptBytecodeWriter and XFER_NAME
Definition at line 442 of file NameTypes.h.
Constructor & Destructor Documentation
FScriptName() [1/3]
FScriptName::FScriptName () inline
Definition at line 446 of file NameTypes.h.
Referenced by GetTypeHash, operator!=, operator==(), and operator==.
FScriptName() [2/3]
FScriptName::FScriptName (EName Ename) inline
Definition at line 448 of file NameTypes.h.
References ComparisonIndex, and DisplayIndex.
FScriptName() [3/3]
FORCEINLINE FScriptName::FScriptName (const FName & Name) explicit
Definition at line 1525 of file NameTypes.h.
References ComparisonIndex, DisplayIndex, FName, FORCEINLINE, Name, Number, and WITH_CASE_PRESERVING_NAME.
Member Function Documentation
IsNone()
FORCEINLINE bool FScriptName::IsNone () const
Definition at line 1553 of file NameTypes.h.
References ComparisonIndex, FORCEINLINE, NAME_NO_NUMBER_INTERNAL, and Number.
operator==()
bool FScriptName::operator== (EName Name) inline
Definition at line 456 of file NameTypes.h.
References FScriptName(), and Name.
ToString()
FString FScriptName::ToString () const
ToUtf8String()
FUtf8String FScriptName::ToUtf8String () const
Friends And Related Symbol Documentation
GetTypeHash
FORCEINLINE uint32 GetTypeHash (FScriptName Name) friend
Definition at line 489 of file NameTypes.h.
References FScriptName(), FORCEINLINE, GetTypeHash, and Name.
Referenced by GetTypeHash.
operator!=
FORCEINLINE bool operator!= (FScriptName Lhs, FScriptName Rhs) friend
Definition at line 494 of file NameTypes.h.
References FScriptName(), and FORCEINLINE.
operator==
FORCEINLINE bool operator== (FScriptName Lhs, FScriptName Rhs) friend
Definition at line 485 of file NameTypes.h.
References FScriptName(), ComparisonIndex, FORCEINLINE, and Number.
Field Documentation
ComparisonIndex
FNameEntryId FScriptName::ComparisonIndex private
Encoded address of name entry (used to find String portion of the string/number pair used for comparison)
Definition at line 464 of file NameTypes.h.
Referenced by FScriptName(), FScriptName(), IsNone(), and operator==.
DisplayIndex
FNameEntryId FScriptName::DisplayIndex private
Encoded address of name entry (used to find String portion of the string/number pair used for display)
Definition at line 466 of file NameTypes.h.
Referenced by FScriptName(), and FScriptName().
FName
friend FScriptName::FName
Definition at line 444 of file NameTypes.h.
Referenced by FScriptName().
Number
uint32 FScriptName::Number = 0 private
Number portion of the string/number pair (stored internally as 1 more than actual, so zero'd memory will be the default, no-instance case)
Definition at line 471 of file NameTypes.h.
Referenced by FScriptName(), IsNone(), and operator==.
The documentation for this struct was generated from the following file:
Runtime/Core/Public/UObject/NameTypes.h