Unreal Engine 5.6 C++ API: FOptTexturePlatformData Struct Reference
FOptTexturePlatformData Struct Reference
Optional extra fields for texture platform data required by some platforms.
#include "Texture.h"
Public Member Functions
FOptTexturePlatformData ()
bool operator!= (FOptTexturePlatformData const &RHS) const
bool operator== (FOptTexturePlatformData const &RHS) const
Data Fields
uint32 ExtData
Arbitrary extra data that the runtime may need.
uint32 NumMipsInTail
Number of mips making up the mip tail, which must always be resident.
Friends
FArchive & operator<< (FArchive &Ar, FOptTexturePlatformData &Data)
Detailed Description
Optional extra fields for texture platform data required by some platforms.
Data in this struct is only serialized if the struct's value is non-default.
Definition at line 803 of file Texture.h.
Constructor & Destructor Documentation
FOptTexturePlatformData()
FOptTexturePlatformData::FOptTexturePlatformData () inline
Definition at line 810 of file Texture.h.
References ExtData, and NumMipsInTail.
Referenced by operator!=(), operator<<, and operator==().
Member Function Documentation
operator!=()
bool FOptTexturePlatformData::operator!= (FOptTexturePlatformData const & RHS) const inline
Definition at line 821 of file Texture.h.
References FOptTexturePlatformData().
operator==()
bool FOptTexturePlatformData::operator== (FOptTexturePlatformData const & RHS) const inline
Definition at line 815 of file Texture.h.
References FOptTexturePlatformData(), ExtData, and NumMipsInTail.
Friends And Related Symbol Documentation
operator<<
FArchive & operator<< (FArchive & Ar, FOptTexturePlatformData & Data) friend
Definition at line 826 of file Texture.h.
References FOptTexturePlatformData(), Ar, ExtData, and NumMipsInTail.
Field Documentation
ExtData
uint32 FOptTexturePlatformData::ExtData
Arbitrary extra data that the runtime may need.
Definition at line 806 of file Texture.h.
Referenced by FOptTexturePlatformData(), operator<<, and operator==().
NumMipsInTail
uint32 FOptTexturePlatformData::NumMipsInTail
Number of mips making up the mip tail, which must always be resident.
Definition at line 808 of file Texture.h.
Referenced by FOptTexturePlatformData(), operator<<, and operator==().
The documentation for this struct was generated from the following file:
Runtime/Engine/Classes/Engine/Texture.h