Unreal Engine 5.6 C++ API: TNetRewindHistory< DataType > Struct Template Reference
TNetRewindHistory< DataType > Struct Template Reference
Templated data history, holding a data buffer.
#include "NetworkPhysicsComponent.h"
Public Types
using Super = Chaos::TDataRewindHistory<DataType>
Public Member Functions
FORCEINLINE TNetRewindHistory (const int32 FrameCount)
FORCEINLINE TNetRewindHistory (const int32 FrameCount, const bool bIsHistoryLocal)
virtual FORCEINLINE ~TNetRewindHistory ()
virtual void ApplyDataRange (const int32 FromFrame, const int32 ToFrame, void *ActorComponent, const bool bOnlyImportant=false) override
virtual TUniquePtr< Chaos::FBaseRewindHistory > Clone () const
virtual bool CopyAllData (Chaos::FBaseRewindHistory &OutHistory, bool bIncludeUnimportant=true, bool bIncludeImportant=false) override
virtual bool CopyAlteredData (Chaos::FBaseRewindHistory &OutHistory, bool bIncludeUnimportant=true, bool bIncludeImportant=false) override
virtual bool CopyData (Chaos::FBaseRewindHistory &OutHistory, const uint32 StartFrame, const uint32 EndFrame, bool bIncludeUnimportant=true, bool bIncludeImportant=false) override
virtual TUniquePtr< Chaos::FBaseRewindHistory > CopyFramesWithOffset (const uint32 StartFrame, const uint32 EndFrame, const int32 FrameOffset) override
virtual int32 CountAlteredData (const bool bIncludeUnimportant=true, const bool bIncludeImportant=false) override
virtual int32 CountValidData (const uint32 StartFrame, const uint32 EndFrame, const bool bIncludeUnimportant=true, const bool bIncludeImportant=false) override
virtual TUniquePtr< Chaos::FBaseRewindHistory > CreateNew () const
virtual FORCEINLINE void DebugData (const Chaos::FBaseRewindHistory &DebugHistory, TArray< int32 > &LocalFrames, TArray< int32 > &ServerFrames, TArray< int32 > &InputFrames) override
Debug the data from the archive.
virtual FORCEINLINE void DebugData (const FString &DebugText) override
Print custom string along with values for each entry in history.
virtual void NetSerialize (FArchive &Ar, UPackageMap *InPackageMap, TUniqueFunction< void(void *Data, const int32 DataIndex)> DataSetupFunction) override
virtual int32 ReceiveNewData (Chaos::FBaseRewindHistory &NewData, const int32 FrameOffset, bool CompareDataForRewind=false, const bool bImportant=false) override
virtual void SetImportant (const bool bImportant, const int32 Frame=INDEX_NONE) override
virtual bool ShouldRecordReceivedDataOnFrame (const DataType &ReceivedData)
Check if we should record received data into history.
virtual bool TriggerRewindFromNewData (DataType &NewData)
Compares new received data with local predicted data and returns true if they differ enough to trigger a resimulation.
UE_DEPRECATED (5.6, "Deprecated, use the NetSerialize call with parameter that takes a function DataSetupFunction, pass in nullptr to opt out of implementing a function.") virtual void NetSerialize(FArchive &Ar
virtual void ValidateDataInHistory (const void *ActorComponent) override
Data Fields
UPackageMap *InPackageMap override
Private Member Functions
FORCEINLINE bool NetSerializeData (DataType &FrameData, FArchive &Ar, UPackageMap *PackageMap) const
Use net serialize path to serialize data.
Static Private Member Functions
static int32 GetMaxArraySize ()
Serialized array size limit to guard against invalid network data.
Detailed Description
template<typename DataType>
struct TNetRewindHistory< DataType >
Templated data history, holding a data buffer.
Definition at line 30 of file NetworkPhysicsComponent.h.
Member Typedef Documentation
Super
template<typename DataType> using TNetRewindHistory< DataType >::Super = Chaos::TDataRewindHistory<DataType>
Definition at line 32 of file NetworkPhysicsComponent.h.
Constructor & Destructor Documentation
TNetRewindHistory() [1/2]
template<typename DataType> FORCEINLINE TNetRewindHistory< DataType >::TNetRewindHistory (const int32 FrameCount, const bool bIsHistoryLocal) inline
Definition at line 34 of file NetworkPhysicsComponent.h.
References FORCEINLINE.
Referenced by CopyAllData(), CopyAlteredData(), CopyData(), DebugData(), and ReceiveNewData().
TNetRewindHistory() [2/2]
template<typename DataType> FORCEINLINE TNetRewindHistory< DataType >::TNetRewindHistory (const int32 FrameCount) inline
Definition at line 39 of file NetworkPhysicsComponent.h.
References FORCEINLINE.
~TNetRewindHistory()
template<typename DataType> virtual FORCEINLINE TNetRewindHistory< DataType >::~TNetRewindHistory () inline virtual
Definition at line 44 of file NetworkPhysicsComponent.h.
References FORCEINLINE.
Member Function Documentation
ApplyDataRange()
template<typename DataType> virtual void TNetRewindHistory< DataType >::ApplyDataRange (const int32 FromFrame, const int32 ToFrame, void * ActorComponent, const bool bOnlyImportant = false) inline override virtual
Definition at line 128 of file NetworkPhysicsComponent.h.
Clone()
template<typename DataType> virtual TUniquePtr< Chaos::FBaseRewindHistory > TNetRewindHistory< DataType >::Clone () const inline virtual
Definition at line 53 of file NetworkPhysicsComponent.h.
References MakeUnique().
CopyAllData()
template<typename DataType> virtual bool TNetRewindHistory< DataType >::CopyAllData (Chaos::FBaseRewindHistory & OutHistory, bool bIncludeUnimportant = true, bool bIncludeImportant = false) inline override virtual
Definition at line 143 of file NetworkPhysicsComponent.h.
References TNetRewindHistory().
CopyAlteredData()
template<typename DataType> virtual bool TNetRewindHistory< DataType >::CopyAlteredData (Chaos::FBaseRewindHistory & OutHistory, bool bIncludeUnimportant = true, bool bIncludeImportant = false) inline override virtual
Definition at line 163 of file NetworkPhysicsComponent.h.
References TNetRewindHistory().
CopyData()
template<typename DataType> virtual bool TNetRewindHistory< DataType >::CopyData (Chaos::FBaseRewindHistory & OutHistory, const uint32 StartFrame, const uint32 EndFrame, bool bIncludeUnimportant = true, bool bIncludeImportant = false) inline override virtual
Definition at line 183 of file NetworkPhysicsComponent.h.
References TNetRewindHistory(), and EndFrame.
CopyFramesWithOffset()
template<typename DataType> virtual TUniquePtr< Chaos::FBaseRewindHistory > TNetRewindHistory< DataType >::CopyFramesWithOffset (const uint32 StartFrame, const uint32 EndFrame, const int32 FrameOffset) inline override virtual
Definition at line 207 of file NetworkPhysicsComponent.h.
References Copy, EndFrame, and MakeUnique().
CountAlteredData()
template<typename DataType> virtual int32 TNetRewindHistory< DataType >::CountAlteredData (const bool bIncludeUnimportant = true, const bool bIncludeImportant = false) inline override virtual
Definition at line 90 of file NetworkPhysicsComponent.h.
References Count.
CountValidData()
template<typename DataType> virtual int32 TNetRewindHistory< DataType >::CountValidData (const uint32 StartFrame, const uint32 EndFrame, const bool bIncludeUnimportant = true, const bool bIncludeImportant = false) inline override virtual
Definition at line 68 of file NetworkPhysicsComponent.h.
References Count, and EndFrame.
CreateNew()
template<typename DataType> virtual TUniquePtr< Chaos::FBaseRewindHistory > TNetRewindHistory< DataType >::CreateNew () const inline virtual
Definition at line 46 of file NetworkPhysicsComponent.h.
References Copy, and MakeUnique().
DebugData() [1/2]
template<typename DataType> virtual FORCEINLINE void TNetRewindHistory< DataType >::DebugData (const Chaos::FBaseRewindHistory & DebugHistory, TArray< int32 > & LocalFrames, TArray< int32 > & ServerFrames, TArray< int32 > & InputFrames) inline override virtual
Debug the data from the archive.
Definition at line 346 of file NetworkPhysicsComponent.h.
References TNetRewindHistory(), FORCEINLINE, and TArray< InElementType, InAllocatorType >::SetNum().
Referenced by DebugData().
DebugData() [2/2]
template<typename DataType> virtual FORCEINLINE void TNetRewindHistory< DataType >::DebugData (const FString & DebugText) inline override virtual
Print custom string along with values for each entry in history.
Definition at line 368 of file NetworkPhysicsComponent.h.
References DebugData(), FORCEINLINE, Log, TEXT, and UE_LOG.
GetMaxArraySize()
template<typename DataType> int32 TNetRewindHistory< DataType >::GetMaxArraySize () inline static private
Serialized array size limit to guard against invalid network data.
Definition at line 392 of file NetworkPhysicsComponent.h.
Referenced by NetSerialize().
NetSerialize()
template<typename DataType> virtual void TNetRewindHistory< DataType >::NetSerialize (FArchive & Ar, UPackageMap * InPackageMap, TUniqueFunction< void(void *Data, const int32 DataIndex)> DataSetupFunction) inline override virtual
Definition at line 288 of file NetworkPhysicsComponent.h.
References Ar, GetMaxArraySize(), LogTemp, NetSerializeData(), TEXT, UE_LOG, and Warning.
NetSerializeData()
template<typename DataType> FORCEINLINE bool TNetRewindHistory< DataType >::NetSerializeData (DataType & FrameData, FArchive & Ar, UPackageMap * PackageMap) const inline private
Use net serialize path to serialize data.
Definition at line 399 of file NetworkPhysicsComponent.h.
References Ar, Error, FORCEINLINE, LogTemp, ScriptStruct, STRUCT_NetSerializeNative, TEXT, and UE_LOG.
Referenced by NetSerialize().
ReceiveNewData()
template<typename DataType> virtual int32 TNetRewindHistory< DataType >::ReceiveNewData (Chaos::FBaseRewindHistory & NewData, const int32 FrameOffset, bool CompareDataForRewind = false, const bool bImportant = false) inline override virtual
Definition at line 228 of file NetworkPhysicsComponent.h.
References TNetRewindHistory(), INDEX_NONE, ShouldRecordReceivedDataOnFrame(), and TriggerRewindFromNewData().
SetImportant()
template<typename DataType> virtual void TNetRewindHistory< DataType >::SetImportant (const bool bImportant, const int32 Frame = INDEX_NONE) inline override virtual
Definition at line 107 of file NetworkPhysicsComponent.h.
References INDEX_NONE.
ShouldRecordReceivedDataOnFrame()
template<typename DataType> virtual bool TNetRewindHistory< DataType >::ShouldRecordReceivedDataOnFrame (const DataType & ReceivedData) inline virtual
Check if we should record received data into history.
Can for example block received data from client from overriding server authoritative data
Definition at line 259 of file NetworkPhysicsComponent.h.
Referenced by ReceiveNewData().
TriggerRewindFromNewData()
template<typename DataType> virtual bool TNetRewindHistory< DataType >::TriggerRewindFromNewData (DataType & NewData) inline virtual
Compares new received data with local predicted data and returns true if they differ enough to trigger a resimulation.
Definition at line 272 of file NetworkPhysicsComponent.h.
Referenced by ReceiveNewData().
UE_DEPRECATED()
template<typename DataType> TNetRewindHistory< DataType >::UE_DEPRECATED (5. 6, " Deprecated, use the NetSerialize call with parameter that takes a function DataSetupFunction, pass in nullptr to opt out of implementing a function.") &
ValidateDataInHistory()
template<typename DataType> virtual void TNetRewindHistory< DataType >::ValidateDataInHistory (const void * ActorComponent) inline override virtual
Definition at line 58 of file NetworkPhysicsComponent.h.
Field Documentation
override
template<typename DataType> UPackageMap* InPackageMap TNetRewindHistory< DataType >::override
Initial value:
{
        NetSerialize(Ar, InPackageMap, [](void* Data, const int32 DataIndex) {})
Definition at line 283 of file NetworkPhysicsComponent.h.
The documentation for this struct was generated from the following file:
Runtime/Engine/Public/Physics/NetworkPhysicsComponent.h