Unreal Engine 5.6 C++ API: UE::Math::TBoxSphereBounds< T, TExtent > Struct Template Reference
UE::Math::TBoxSphereBounds< T, TExtent > Struct Template Reference
#include "BoxSphereBounds.h"
Data Structures
struct Builder
Utility class to build a TBoxSphereBounds by adding other math primitives.
Public Types
using FReal = T
Public Member Functions
TBoxSphereBounds ()=default
Default constructor.
TBoxSphereBounds (const TBox< T > &Box)
Creates and initializes a new instance the given Box.
TBoxSphereBounds (const TBox< T > &Box, const TSphere< T > &Sphere)
Creates and initializes a new instance from the given Box and Sphere.
template<typename TFrom, typename TExtentFrom UE_REQUIRES>
TBoxSphereBounds (const TBoxSphereBounds< TFrom, TExtentFrom > &From)
TBoxSphereBounds (const TSphere< T > &Sphere)
Creates and initializes a new instance for the given sphere.
TBoxSphereBounds (const TVector< T > &InOrigin, const TVector< TExtent > &InBoxExtent, TExtent InSphereRadius)
Creates and initializes a new instance from the specified parameters.
TBoxSphereBounds (const TVector< T > *Points, uint32 NumPoints)
Creates and initializes a new instance from the given set of points.
FORCEINLINE TBoxSphereBounds (EForceInit)
Creates and initializes a new instance.
FORCEINLINE T ComputeSquaredDistanceFromBoxToPoint (const TVector< T > &Point) const
Calculates the squared distance from a point to a bounding box.
bool ContainsNaN () const
FORCEINLINE void DiagnosticCheckNaN () const
FORCEINLINE TBoxSphereBounds< T, TExtent > ExpandBy (TExtent ExpandAmount) const
Increase the size of the box and sphere by a given size.
FORCEINLINE TBox< T > GetBox () const
Gets the bounding box.
TVector< T > GetBoxExtrema (uint32 Extrema) const
Gets the extrema for the bounding box.
FORCEINLINE TSphere< T > GetSphere () const
Gets the bounding sphere.
FORCEINLINE bool operator!= (const TBoxSphereBounds< T, TExtent > &Other) const
Compare bounding volume this and Other.
FORCEINLINE TBoxSphereBounds< T, TExtent > operator+ (const TBoxSphereBounds< T, TExtent > &Other) const
Constructs a bounding volume containing both this and B.
FORCEINLINE bool operator== (const TBoxSphereBounds< T, TExtent > &Other) const
Compare bounding volume this and Other.
bool Serialize (FArchive &Ar)
bool SerializeFromMismatchedTag (FName StructTag, FArchive &Ar)
FString ToString () const
Get a textual representation of this bounding box.
TBoxSphereBounds< T, TExtent > TransformBy (const TMatrix< T > &M) const
Gets a bounding volume transformed by a matrix.
TBoxSphereBounds< T, TExtent > TransformBy (const TTransform< T > &M) const
Gets a bounding volume transformed by a FTransform object.
Static Public Member Functions
static FORCEINLINE bool BoxesIntersect (const TBoxSphereBounds< T, TExtent > &A, const TBoxSphereBounds< T, TExtent > &B)
Test whether the boxes from two BoxSphereBounds intersect/overlap.
static FORCEINLINE bool SpheresIntersect (const TBoxSphereBounds< T, TExtent > &A, const TBoxSphereBounds< T, TExtent > &B, TExtent Tolerance=UE_KINDA_SMALL_NUMBER)
Test whether the spheres from two BoxSphereBounds intersect/overlap.
Data Fields
TVector< TExtent > BoxExtent
Holds the extent of the bounding box.
TVector< T > Origin
Holds the origin of the bounding box and sphere.
TExtent SphereRadius
Holds the radius of the bounding sphere.
Friends
TBoxSphereBounds< T, TExtent > Union (const TBoxSphereBounds< T, TExtent > &A, const TBoxSphereBounds< T, TExtent > &B)
Constructs a bounding volume containing both A and B.
Detailed Description
template<typename T, typename TExtent>
struct UE::Math::TBoxSphereBounds< T, TExtent >
Definition at line 24 of file BoxSphereBounds.h.
Member Typedef Documentation
FReal
template<typename T, typename TExtent> using UE::Math::TBoxSphereBounds< T, TExtent >::FReal = T
Definition at line 26 of file BoxSphereBounds.h.
Constructor & Destructor Documentation
TBoxSphereBounds() [1/8]
template<typename T, typename TExtent> UE::Math::TBoxSphereBounds< T, TExtent >::TBoxSphereBounds () nodiscard default
Default constructor.
Referenced by UE::Math::TBoxSphereBounds< T, TExtent >::Builder::Append(), UE::Math::TBoxSphereBounds< float, float >::ExpandBy(), operator!=(), operator+(), UE::Math::TBoxSphereBounds< T, TExtent >::Builder::operator+=(), UE::Math::TBoxSphereBounds< T, TExtent >::Builder::operator+=(), operator==(), TransformBy(), and TransformBy().
TBoxSphereBounds() [2/8]
template<typename T, typename TExtent> FORCEINLINE UE::Math::TBoxSphereBounds< T, TExtent >::TBoxSphereBounds (EForceInit) inline explicit nodiscard
Creates and initializes a new instance.
Parameters
EForceInit Force Init Enum.
Definition at line 47 of file BoxSphereBounds.h.
TBoxSphereBounds() [3/8]
template<typename T, typename TExtent> UE::Math::TBoxSphereBounds< T, TExtent >::TBoxSphereBounds (const TVector< T > & InOrigin, const TVector< TExtent > & InBoxExtent, TExtent InSphereRadius) inline nodiscard
Creates and initializes a new instance from the specified parameters.
Parameters
InOrigin origin of the bounding box and sphere.
InBoxExtent half size of box.
InSphereRadius radius of the sphere.
Definition at line 62 of file BoxSphereBounds.h.
TBoxSphereBounds() [4/8]
template<typename T, typename TExtent> UE::Math::TBoxSphereBounds< T, TExtent >::TBoxSphereBounds (const TBox< T > & Box, const TSphere< T > & Sphere) inline nodiscard
Creates and initializes a new instance from the given Box and Sphere.
Parameters
Box The bounding box.
Sphere The bounding sphere.
Definition at line 76 of file BoxSphereBounds.h.
TBoxSphereBounds() [5/8]
template<typename T, typename TExtent> UE::Math::TBoxSphereBounds< T, TExtent >::TBoxSphereBounds (const TBox< T > & Box) inline nodiscard
Creates and initializes a new instance the given Box.
The sphere radius is taken from the extent of the box.
Parameters
Box The bounding box.
Definition at line 94 of file BoxSphereBounds.h.
TBoxSphereBounds() [6/8]
template<typename T, typename TExtent> UE::Math::TBoxSphereBounds< T, TExtent >::TBoxSphereBounds (const TSphere< T > & Sphere) inline nodiscard
Creates and initializes a new instance for the given sphere.
Definition at line 108 of file BoxSphereBounds.h.
TBoxSphereBounds() [7/8]
template<typename T, typename TExtent> FORCEINLINE UE::Math::TBoxSphereBounds< T, TExtent >::TBoxSphereBounds (const TVector< T > * Points, uint32 NumPoints) nodiscard
Creates and initializes a new instance from the given set of points.
The sphere radius is taken from the extent of the box.
Parameters
Points The points to be considered for the bounding box.
NumPoints Number of points in the Points array.
Definition at line 429 of file BoxSphereBounds.h.
References BoundingBox, BoxExtent, DiagnosticCheckNaN(), ForceInit, FORCEINLINE, FMath::Max, Origin, Points, and SphereRadius.
TBoxSphereBounds() [8/8]
template<typename T, typename TExtent> template<typename TFrom, typename TExtentFrom UE_REQUIRES> UE::Math::TBoxSphereBounds< T, TExtent >::TBoxSphereBounds (const TBoxSphereBounds< TFrom, TExtentFrom > & From) inline explicit
Definition at line 129 of file BoxSphereBounds.h.
Member Function Documentation
BoxesIntersect()
template<typename T, typename TExtent> FORCEINLINE bool UE::Math::TBoxSphereBounds< T, TExtent >::BoxesIntersect (const TBoxSphereBounds< T, TExtent > & A, const TBoxSphereBounds< T, TExtent > & B) inline static nodiscard
Test whether the boxes from two BoxSphereBounds intersect/overlap.
Parameters
A First BoxSphereBounds to test.
B Second BoxSphereBounds to test.
Returns
true if boxes intersect, false otherwise.
Definition at line 216 of file BoxSphereBounds.h.
ComputeSquaredDistanceFromBoxToPoint()
template<typename T, typename TExtent> FORCEINLINE T UE::Math::TBoxSphereBounds< T, TExtent >::ComputeSquaredDistanceFromBoxToPoint (const TVector< T > & Point) const inline nodiscard
Calculates the squared distance from a point to a bounding box.
Parameters
Point The point.
Returns
The distance.
Definition at line 188 of file BoxSphereBounds.h.
ContainsNaN()
template<typename T, typename TExtent> bool UE::Math::TBoxSphereBounds< T, TExtent >::ContainsNaN () const inline nodiscard
Definition at line 324 of file BoxSphereBounds.h.
DiagnosticCheckNaN()
template<typename T, typename TExtent> FORCEINLINE void UE::Math::TBoxSphereBounds< T, TExtent >::DiagnosticCheckNaN () const inline
Definition at line 321 of file BoxSphereBounds.h.
Referenced by TBoxSphereBounds(), UE::Math::TBoxSphereBounds< float, float >::TBoxSphereBounds(), UE::Math::TBoxSphereBounds< float, float >::TBoxSphereBounds(), UE::Math::TBoxSphereBounds< float, float >::TBoxSphereBounds(), UE::Math::TBoxSphereBounds< float, float >::TBoxSphereBounds(), and UE::Math::TBoxSphereBounds< float, float >::TBoxSphereBounds().
ExpandBy()
template<typename T, typename TExtent> FORCEINLINE TBoxSphereBounds< T, TExtent > UE::Math::TBoxSphereBounds< T, TExtent >::ExpandBy (TExtent ExpandAmount) const inline nodiscard
Increase the size of the box and sphere by a given size.
Parameters
ExpandAmount The size to increase by.
Returns
A new box with the expanded size.
Definition at line 263 of file BoxSphereBounds.h.
GetBox()
template<typename T, typename TExtent> FORCEINLINE TBox< T > UE::Math::TBoxSphereBounds< T, TExtent >::GetBox () const inline nodiscard
Gets the bounding box.
Returns
The bounding box.
Definition at line 226 of file BoxSphereBounds.h.
Referenced by FInstancedSkinnedMeshComponentHelper::CalcBounds(), and FInstancedStaticMeshComponentHelper::GetNavigationPerInstanceTransforms().
GetBoxExtrema()
template<typename T, typename TExtent> TVector< T > UE::Math::TBoxSphereBounds< T, TExtent >::GetBoxExtrema (uint32 Extrema) const inline nodiscard
Gets the extrema for the bounding box.
Parameters
Extrema 1 for positive extrema from the origin, else negative
Returns
The boxes extrema
Definition at line 237 of file BoxSphereBounds.h.
Referenced by FPrimitiveUniformShaderParametersBuilder::LocalBounds(), and FPrimitiveUniformShaderParametersBuilder::PreSkinnedLocalBounds().
GetSphere()
template<typename T, typename TExtent> FORCEINLINE TSphere< T > UE::Math::TBoxSphereBounds< T, TExtent >::GetSphere () const inline nodiscard
Gets the bounding sphere.
Returns
The bounding sphere.
Definition at line 252 of file BoxSphereBounds.h.
operator!=()
template<typename T, typename TExtent> FORCEINLINE bool UE::Math::TBoxSphereBounds< T, TExtent >::operator!= (const TBoxSphereBounds< T, TExtent > & Other) const nodiscard
Compare bounding volume this and Other.
Parameters
Other The other bounding volume.
Returns
true of they do not match.
Definition at line 482 of file BoxSphereBounds.h.
References TBoxSphereBounds(), FORCEINLINE, and Other.
operator+()
template<typename T, typename TExtent> FORCEINLINE TBoxSphereBounds< T, TExtent > UE::Math::TBoxSphereBounds< T, TExtent >::operator+ (const TBoxSphereBounds< T, TExtent > & Other) const nodiscard
Constructs a bounding volume containing both this and B.
Parameters
Other The other bounding volume.
Returns
The combined bounding volume.
Definition at line 457 of file BoxSphereBounds.h.
References TBoxSphereBounds(), BoundingBox, ForceInit, FORCEINLINE, FMath::Max, FMath::Min, Origin, Other, and SphereRadius.
operator==()
template<typename T, typename TExtent> FORCEINLINE bool UE::Math::TBoxSphereBounds< T, TExtent >::operator== (const TBoxSphereBounds< T, TExtent > & Other) const nodiscard
Compare bounding volume this and Other.
Parameters
Other The other bounding volume.
Returns
true of they match.
Definition at line 476 of file BoxSphereBounds.h.
References TBoxSphereBounds(), BoxExtent, FORCEINLINE, Origin, Other, and SphereRadius.
Serialize()
template<typename T, typename TExtent> FORCEINLINE bool UE::Math::TBoxSphereBounds< T, TExtent >::Serialize (FArchive & Ar)
Definition at line 488 of file BoxSphereBounds.h.
References Ar, and FORCEINLINE.
SerializeFromMismatchedTag()
template<typename T, typename TExtent> bool UE::Math::TBoxSphereBounds< T, TExtent >::SerializeFromMismatchedTag (FName StructTag, FArchive & Ar) inline
Definition at line 137 of file BoxSphereBounds.h.
SpheresIntersect()
template<typename T, typename TExtent> FORCEINLINE bool UE::Math::TBoxSphereBounds< T, TExtent >::SpheresIntersect (const TBoxSphereBounds< T, TExtent > & A, const TBoxSphereBounds< T, TExtent > & B, TExtent Tolerance = UE_KINDA_SMALL_NUMBER) inline static nodiscard
Test whether the spheres from two BoxSphereBounds intersect/overlap.
Parameters
A First BoxSphereBounds to test.
B Second BoxSphereBounds to test.
Tolerance Error tolerance added to test distance.
Returns
true if spheres intersect, false otherwise.
Definition at line 204 of file BoxSphereBounds.h.
ToString()
template<typename T, typename TExtent> FORCEINLINE FString UE::Math::TBoxSphereBounds< T, TExtent >::ToString () const nodiscard
Get a textual representation of this bounding box.
Returns
Text describing the bounding box.
Definition at line 495 of file BoxSphereBounds.h.
References BoxExtent, FORCEINLINE, Origin, SphereRadius, and TEXT.
TransformBy() [1/2]
template<typename T, typename TExtent> TBoxSphereBounds< T, TExtent > UE::Math::TBoxSphereBounds< T, TExtent >::TransformBy (const TMatrix< T > & M) const nodiscard
Gets a bounding volume transformed by a matrix.
Parameters
M The matrix.
Returns
The transformed volume.
Definition at line 501 of file BoxSphereBounds.h.
References TBoxSphereBounds(), BoxExtent, UE::Math::TMatrix< T >::ContainsNaN(), logOrEnsureNanError, UE::Math::TMatrix< T >::M, FMath::Min, Origin, SphereRadius, TEXT, UE::Math::TMatrix< T >::ToString(), VectorAbs(), VectorAdd(), VectorDot3Scalar(), VectorGetComponent, VectorLoadAligned(), VectorLoadFloat3(), VectorMax(), VectorMultiply(), VectorMultiplyAdd(), VectorReplicate, and VectorStoreFloat3().
Referenced by TransformBy().
TransformBy() [2/2]
template<typename T, typename TExtent> TBoxSphereBounds< T, TExtent > UE::Math::TBoxSphereBounds< T, TExtent >::TransformBy (const TTransform< T > & M) const nodiscard
Gets a bounding volume transformed by a FTransform object.
Parameters
M The FTransform object.
Returns
The transformed volume.
Definition at line 554 of file BoxSphereBounds.h.
References TBoxSphereBounds(), UE::Math::TTransform< T >::DiagnosticCheckNaN_All(), UE::Math::TTransform< T >::ToMatrixWithScale(), and TransformBy().
Friends And Related Symbol Documentation
Union
template<typename T, typename TExtent> TBoxSphereBounds< T, TExtent > Union (const TBoxSphereBounds< T, TExtent > & A, const TBoxSphereBounds< T, TExtent > & B) friend
Constructs a bounding volume containing both A and B.
This is a legacy version of the function used to compute primitive bounds, to avoid the need to rebuild lighting after the change.
Definition at line 296 of file BoxSphereBounds.h.
Field Documentation
BoxExtent
template<typename T, typename TExtent> TVector<TExtent> UE::Math::TBoxSphereBounds< T, TExtent >::BoxExtent
Holds the extent of the bounding box.
Definition at line 32 of file BoxSphereBounds.h.
Referenced by FBoxCenterAndExtent::FBoxCenterAndExtent(), FRenderBounds::FRenderBounds(), TBoxSphereBounds(), FProjectedShadowInitializer::IsCachedShadowValid(), UE::Math::operator<<(), UE::Math::operator<<(), operator==(), ToString(), TransformBy(), and FPrimitiveUniformShaderParametersBuilder::WorldBounds().
Origin
template<typename T, typename TExtent> TVector<T> UE::Math::TBoxSphereBounds< T, TExtent >::Origin
Holds the origin of the bounding box and sphere.
Definition at line 29 of file BoxSphereBounds.h.
Referenced by FBoxCenterAndExtent::FBoxCenterAndExtent(), FRenderBounds::FRenderBounds(), TBoxSphereBounds(), FProjectedShadowInitializer::IsCachedShadowValid(), operator+(), UE::Math::operator<<(), UE::Math::operator<<(), operator==(), ToString(), TransformBy(), and FPrimitiveUniformShaderParametersBuilder::WorldBounds().
SphereRadius
template<typename T, typename TExtent> TExtent UE::Math::TBoxSphereBounds< T, TExtent >::SphereRadius
Holds the radius of the bounding sphere.
Definition at line 35 of file BoxSphereBounds.h.
Referenced by TBoxSphereBounds(), FProjectedShadowInitializer::IsCachedShadowValid(), operator+(), UE::Math::operator<<(), UE::Math::operator<<(), operator==(), ToString(), TransformBy(), USTRUCT(), and FPrimitiveUniformShaderParametersBuilder::WorldBounds().
The documentation for this struct was generated from the following file:
Runtime/Core/Public/Math/BoxSphereBounds.h