Unreal Engine 5.6 C++ API: UE::Core::Private::TReverseIterationAdapter< ElementType(&)[N]> Struct Template Reference
UE::Core::Private::TReverseIterationAdapter< ElementType(&)[N]> Struct Template Reference
#include "ReverseIterate.h"
Public Member Functions
TReverseIterationAdapter (const TReverseIterationAdapter &)=delete
constexpr TReverseIterationAdapter (ElementType *InArray UE_LIFETIMEBOUND)
TReverseIterationAdapter (TReverseIterationAdapter &&)=delete
~TReverseIterationAdapter ()=default
constexpr TReversePointerIterator< ElementType > begin () const UE_LIFETIMEBOUND
constexpr TReversePointerIterator< ElementType > end () const UE_LIFETIMEBOUND
TReverseIterationAdapter & operator= (const TReverseIterationAdapter &)=delete
TReverseIterationAdapter & operator= (TReverseIterationAdapter &&)=delete
Private Attributes
ElementType * Array
ElementType(&) & Range
Detailed Description
template<typename ElementType, std::size_t N>
struct UE::Core::Private::TReverseIterationAdapter< ElementType(&)[N]>
Definition at line 84 of file ReverseIterate.h.
Constructor & Destructor Documentation
TReverseIterationAdapter() [1/3]
template<typename ElementType, std::size_t N> UE::Core::Private::TReverseIterationAdapter< ElementType(&)[N]>::TReverseIterationAdapter (ElementType *InArray UE_LIFETIMEBOUND) inline explicit constexpr
Definition at line 86 of file ReverseIterate.h.
References Array, and UE_LIFETIMEBOUND.
Referenced by TReverseIterationAdapter(), TReverseIterationAdapter(), operator=(), and operator=().
TReverseIterationAdapter() [2/3]
template<typename ElementType, std::size_t N> UE::Core::Private::TReverseIterationAdapter< ElementType(&)[N]>::TReverseIterationAdapter (TReverseIterationAdapter< ElementType(&)[N]> &&) delete
References TReverseIterationAdapter().
TReverseIterationAdapter() [3/3]
template<typename ElementType, std::size_t N> UE::Core::Private::TReverseIterationAdapter< ElementType(&)[N]>::TReverseIterationAdapter (const TReverseIterationAdapter< ElementType(&)[N]> &) delete
References TReverseIterationAdapter().
~TReverseIterationAdapter()
template<typename ElementType, std::size_t N> UE::Core::Private::TReverseIterationAdapter< ElementType(&)[N]>::~TReverseIterationAdapter () default
Member Function Documentation
begin()
template<typename ElementType, std::size_t N> TReversePointerIterator< ElementType > UE::Core::Private::TReverseIterationAdapter< ElementType(&)[N]>::begin () const inline constexpr
Definition at line 97 of file ReverseIterate.h.
References Array, and UE_LIFETIMEBOUND.
end()
template<typename ElementType, std::size_t N> TReversePointerIterator< ElementType > UE::Core::Private::TReverseIterationAdapter< ElementType(&)[N]>::end () const inline constexpr
Definition at line 102 of file ReverseIterate.h.
References Array, and UE_LIFETIMEBOUND.
operator=() [1/2]
template<typename ElementType, std::size_t N> TReverseIterationAdapter & UE::Core::Private::TReverseIterationAdapter< ElementType(&)[N]>::operator= (const TReverseIterationAdapter< ElementType(&)[N]> &) delete
References TReverseIterationAdapter().
operator=() [2/2]
template<typename ElementType, std::size_t N> TReverseIterationAdapter & UE::Core::Private::TReverseIterationAdapter< ElementType(&)[N]>::operator= (TReverseIterationAdapter< ElementType(&)[N]> &&) delete
References TReverseIterationAdapter().
Field Documentation
Array
template<typename ElementType, std::size_t N> ElementType* UE::Core::Private::TReverseIterationAdapter< ElementType(&)[N]>::Array private
Definition at line 108 of file ReverseIterate.h.
Referenced by TReverseIterationAdapter(), begin(), and end().
Range
ElementType(&)& UE::Core::Private::TReverseIterationAdapter< ElementType(&) >::Range private
Definition at line 80 of file ReverseIterate.h.
The documentation for this struct was generated from the following file:
Runtime/Core/Public/Misc/ReverseIterate.h