Unreal Engine 5.6 C++ API: FPreviewScene::ConstructionValues Struct Reference
FPreviewScene::ConstructionValues Struct Reference
#include "PreviewScene.h"
Public Member Functions
ConstructionValues ()
ConstructionValues & AllowAudioPlayback (const bool bAllow)
ConstructionValues & ForceUseMovementComponentInNonGameWorld (const bool bInForceUseMovementComponentInNonGameWorld)
ConstructionValues & SetCreateDefaultLighting (const bool bDefault)
ConstructionValues & SetCreatePhysicsScene (const bool bCreate)
ConstructionValues & SetDefaultGameMode (TSubclassOf< class AGameModeBase > GameMode)
ConstructionValues & SetEditor (const bool bInEditor)
ConstructionValues & SetForceMipsResident (const bool bForce)
ConstructionValues & SetLightBrightness (const float Brightness)
ConstructionValues & SetLightRotation (const FRotator &Rotation)
ConstructionValues & SetOwningGameInstance (class UGameInstance *InGameInstance)
ConstructionValues & SetSkyBrightness (const float Brightness)
ConstructionValues & SetTransactional (const bool bInTransactional)
ConstructionValues & ShouldSimulatePhysics (const bool bInShouldSimulatePhysics)
Data Fields
uint32 bAllowAudioPlayback:1
uint32 bCreatePhysicsScene:1
uint32 bDefaultLighting: 1
uint32 bEditor:1
uint32 bForceMipsResident:1
uint32 bForceUseMovementComponentInNonGameWorld:1
uint32 bShouldSimulatePhysics:1
uint32 bTransactional:1
TSubclassOf< class AGameModeBase > DefaultGameMode
float LightBrightness
FRotator LightRotation
class UGameInstance * OwningGameInstance = nullptr
float SkyBrightness
Detailed Description
Definition at line 21 of file PreviewScene.h.
Constructor & Destructor Documentation
ConstructionValues()
FPreviewScene::ConstructionValues::ConstructionValues () inline
Definition at line 23 of file PreviewScene.h.
References bAllowAudioPlayback, bCreatePhysicsScene, bDefaultLighting, bEditor, bForceMipsResident, bForceUseMovementComponentInNonGameWorld, bShouldSimulatePhysics, bTransactional, LightBrightness, LightRotation, SkyBrightness, and UE_PI.
Referenced by AllowAudioPlayback(), ForceUseMovementComponentInNonGameWorld(), SetCreateDefaultLighting(), SetCreatePhysicsScene(), SetDefaultGameMode(), SetEditor(), SetForceMipsResident(), SetLightBrightness(), SetLightRotation(), SetOwningGameInstance(), SetSkyBrightness(), SetTransactional(), and ShouldSimulatePhysics().
Member Function Documentation
AllowAudioPlayback()
ConstructionValues & FPreviewScene::ConstructionValues::AllowAudioPlayback (const bool bAllow) inline
Definition at line 58 of file PreviewScene.h.
References ConstructionValues(), and bAllowAudioPlayback.
ForceUseMovementComponentInNonGameWorld()
ConstructionValues & FPreviewScene::ConstructionValues::ForceUseMovementComponentInNonGameWorld (const bool bInForceUseMovementComponentInNonGameWorld) inline
Definition at line 64 of file PreviewScene.h.
References ConstructionValues(), and bForceUseMovementComponentInNonGameWorld.
SetCreateDefaultLighting()
ConstructionValues & FPreviewScene::ConstructionValues::SetCreateDefaultLighting (const bool bDefault) inline
Definition at line 53 of file PreviewScene.h.
References ConstructionValues(), and bDefaultLighting.
SetCreatePhysicsScene()
ConstructionValues & FPreviewScene::ConstructionValues::SetCreatePhysicsScene (const bool bCreate) inline
Definition at line 60 of file PreviewScene.h.
References ConstructionValues(), and bCreatePhysicsScene.
SetDefaultGameMode()
ConstructionValues & FPreviewScene::ConstructionValues::SetDefaultGameMode (TSubclassOf< class AGameModeBase > GameMode) inline
Definition at line 66 of file PreviewScene.h.
References ConstructionValues(), and DefaultGameMode.
SetEditor()
ConstructionValues & FPreviewScene::ConstructionValues::SetEditor (const bool bInEditor) inline
Definition at line 63 of file PreviewScene.h.
References ConstructionValues(), and bEditor.
SetForceMipsResident()
ConstructionValues & FPreviewScene::ConstructionValues::SetForceMipsResident (const bool bForce) inline
Definition at line 59 of file PreviewScene.h.
References ConstructionValues(), and bForceMipsResident.
SetLightBrightness()
ConstructionValues & FPreviewScene::ConstructionValues::SetLightBrightness (const float Brightness) inline
Definition at line 56 of file PreviewScene.h.
References ConstructionValues(), and LightBrightness.
SetLightRotation()
ConstructionValues & FPreviewScene::ConstructionValues::SetLightRotation (const FRotator & Rotation) inline
Definition at line 54 of file PreviewScene.h.
References ConstructionValues(), LightRotation, and Rotation.
SetOwningGameInstance()
ConstructionValues & FPreviewScene::ConstructionValues::SetOwningGameInstance (class UGameInstance * InGameInstance) inline
Definition at line 67 of file PreviewScene.h.
References ConstructionValues(), and OwningGameInstance.
SetSkyBrightness()
ConstructionValues & FPreviewScene::ConstructionValues::SetSkyBrightness (const float Brightness) inline
Definition at line 55 of file PreviewScene.h.
References ConstructionValues(), and SkyBrightness.
SetTransactional()
ConstructionValues & FPreviewScene::ConstructionValues::SetTransactional (const bool bInTransactional) inline
Definition at line 62 of file PreviewScene.h.
References ConstructionValues(), and bTransactional.
ShouldSimulatePhysics()
ConstructionValues & FPreviewScene::ConstructionValues::ShouldSimulatePhysics (const bool bInShouldSimulatePhysics) inline
Definition at line 61 of file PreviewScene.h.
References ConstructionValues(), and bShouldSimulatePhysics.
Field Documentation
bAllowAudioPlayback
uint32 FPreviewScene::ConstructionValues::bAllowAudioPlayback
Definition at line 42 of file PreviewScene.h.
Referenced by ConstructionValues(), and AllowAudioPlayback().
bCreatePhysicsScene
uint32 FPreviewScene::ConstructionValues::bCreatePhysicsScene
Definition at line 44 of file PreviewScene.h.
Referenced by ConstructionValues(), and SetCreatePhysicsScene().
bDefaultLighting
uint32 FPreviewScene::ConstructionValues::bDefaultLighting
Definition at line 41 of file PreviewScene.h.
Referenced by ConstructionValues(), and SetCreateDefaultLighting().
bEditor
uint32 FPreviewScene::ConstructionValues::bEditor
Definition at line 47 of file PreviewScene.h.
Referenced by ConstructionValues(), and SetEditor().
bForceMipsResident
uint32 FPreviewScene::ConstructionValues::bForceMipsResident
Definition at line 43 of file PreviewScene.h.
Referenced by ConstructionValues(), and SetForceMipsResident().
bForceUseMovementComponentInNonGameWorld
uint32 FPreviewScene::ConstructionValues::bForceUseMovementComponentInNonGameWorld
Definition at line 48 of file PreviewScene.h.
Referenced by ConstructionValues(), and ForceUseMovementComponentInNonGameWorld().
bShouldSimulatePhysics
uint32 FPreviewScene::ConstructionValues::bShouldSimulatePhysics
Definition at line 45 of file PreviewScene.h.
Referenced by ConstructionValues(), and ShouldSimulatePhysics().
bTransactional
uint32 FPreviewScene::ConstructionValues::bTransactional
Definition at line 46 of file PreviewScene.h.
Referenced by ConstructionValues(), and SetTransactional().
DefaultGameMode
TSubclassOf<class AGameModeBase> FPreviewScene::ConstructionValues::DefaultGameMode
Definition at line 50 of file PreviewScene.h.
Referenced by SetDefaultGameMode().
LightBrightness
float FPreviewScene::ConstructionValues::LightBrightness
Definition at line 40 of file PreviewScene.h.
Referenced by ConstructionValues(), and SetLightBrightness().
LightRotation
FRotator FPreviewScene::ConstructionValues::LightRotation
Definition at line 38 of file PreviewScene.h.
Referenced by ConstructionValues(), and SetLightRotation().
OwningGameInstance
class UGameInstance* FPreviewScene::ConstructionValues::OwningGameInstance = nullptr
Definition at line 51 of file PreviewScene.h.
Referenced by SetOwningGameInstance().
SkyBrightness
float FPreviewScene::ConstructionValues::SkyBrightness
Definition at line 39 of file PreviewScene.h.
Referenced by ConstructionValues(), and SetSkyBrightness().
The documentation for this struct was generated from the following file:
Runtime/Engine/Public/PreviewScene.h