Unreal Engine 5.6 C++ API: FAnimCompressContext Struct Reference
FAnimCompressContext Struct Reference
#include "AnimCompress.h"
Public Member Functions
FAnimCompressContext (bool bInOutput, uint32 InMaxAnimations=1)
FAnimCompressContext (const FAnimCompressContext &Rhs)
FAnimCompressContext & operator= (const FAnimCompressContext &)=default
Data Fields
uint32 AnimIndex
bool bOutput
uint32 MaxAnimations
Private Member Functions
void GatherPostCompressionStats (const FCompressedAnimSequence &CompressedData, const TArray< FBoneData > &BoneData, const FName AnimFName, double CompressionTime, bool bInPerformedCompression)
void GatherPreCompressionStats (const FString &Name, int32 RawSize, int32 PreviousCompressionSize)
Private Attributes
FCompressionMemorySummary CompressionSummary
Friends
class FAnimationUtils
class FDerivedDataAnimationCompression
class UAnimSequence
Detailed Description
Definition at line 229 of file AnimCompress.h.
Constructor & Destructor Documentation
FAnimCompressContext() [1/2]
FAnimCompressContext::FAnimCompressContext (bool bInOutput, uint32 InMaxAnimations = 1) inline
Definition at line 242 of file AnimCompress.h.
References AnimIndex, bOutput, CompressionSummary, and MaxAnimations.
Referenced by FAnimCompressContext(), and operator=().
FAnimCompressContext() [2/2]
FAnimCompressContext::FAnimCompressContext (const FAnimCompressContext & Rhs) inline
Definition at line 250 of file AnimCompress.h.
References FAnimCompressContext(), AnimIndex, bOutput, CompressionSummary, and MaxAnimations.
Member Function Documentation
GatherPostCompressionStats()
void FAnimCompressContext::GatherPostCompressionStats (const FCompressedAnimSequence & CompressedData, const TArray< FBoneData > & BoneData, const FName AnimFName, double CompressionTime, bool bInPerformedCompression) inline private
Definition at line 236 of file AnimCompress.h.
References CompressedData.
GatherPreCompressionStats()
void FAnimCompressContext::GatherPreCompressionStats (const FString & Name, int32 RawSize, int32 PreviousCompressionSize) inline private
Definition at line 234 of file AnimCompress.h.
References Name.
operator=()
FAnimCompressContext & FAnimCompressContext::operator= (const FAnimCompressContext &) default
References FAnimCompressContext().
Friends And Related Symbol Documentation
FAnimationUtils
friend class FAnimationUtils friend
Definition at line 260 of file AnimCompress.h.
References FAnimationUtils.
Referenced by FAnimationUtils.
FDerivedDataAnimationCompression
friend class FDerivedDataAnimationCompression friend
Definition at line 261 of file AnimCompress.h.
References FDerivedDataAnimationCompression.
Referenced by FDerivedDataAnimationCompression.
UAnimSequence
friend class UAnimSequence friend
Definition at line 262 of file AnimCompress.h.
References UAnimSequence.
Referenced by UAnimSequence.
Field Documentation
AnimIndex
uint32 FAnimCompressContext::AnimIndex
Definition at line 238 of file AnimCompress.h.
Referenced by FAnimCompressContext(), and FAnimCompressContext().
bOutput
bool FAnimCompressContext::bOutput
Definition at line 240 of file AnimCompress.h.
Referenced by FAnimCompressContext(), and FAnimCompressContext().
CompressionSummary
FCompressionMemorySummary FAnimCompressContext::CompressionSummary private
Definition at line 232 of file AnimCompress.h.
Referenced by FAnimCompressContext(), and FAnimCompressContext().
MaxAnimations
uint32 FAnimCompressContext::MaxAnimations
Definition at line 239 of file AnimCompress.h.
Referenced by FAnimCompressContext(), and FAnimCompressContext().
The documentation for this struct was generated from the following file:
Runtime/Engine/Classes/Animation/AnimCompress.h