Unreal Engine 5.6 C++ API: UE::AnimNext::FNodeTemplateRegistry Struct Reference
UE::AnimNext::FNodeTemplateRegistry Struct Reference final
FNodeTemplateRegistry.
#include "NodeTemplateRegistry.h"
Public Member Functions
ANIMNEXTANIMGRAPH_API const FNodeTemplate * Find (FNodeTemplateRegistryHandle TemplateHandle) const
ANIMNEXTANIMGRAPH_API FNodeTemplateRegistryHandle Find (uint32 NodeTemplateUID) const
ANIMNEXTANIMGRAPH_API FNodeTemplateRegistryHandle FindOrAdd (const FNodeTemplate *NodeTemplate)
ANIMNEXTANIMGRAPH_API uint32 GetNum () const
ANIMNEXTANIMGRAPH_API void Unregister (const FNodeTemplate *NodeTemplate)
Static Public Member Functions
static ANIMNEXTANIMGRAPH_API FNodeTemplateRegistry & Get ()
Private Member Functions
FNodeTemplateRegistry ()=default
FNodeTemplateRegistry (const FNodeTemplateRegistry &)=delete
FNodeTemplateRegistry (FNodeTemplateRegistry &&)=default
ANIMNEXTANIMGRAPH_API FNodeTemplate * FindMutable (FNodeTemplateRegistryHandle TemplateHandle)
FNodeTemplateRegistry & operator= (const FNodeTemplateRegistry &)=delete
FNodeTemplateRegistry & operator= (FNodeTemplateRegistry &&)=default
Static Private Member Functions
static ANIMNEXTANIMGRAPH_API void Destroy ()
static ANIMNEXTANIMGRAPH_API void Init ()
Private Attributes
TArray< uint8 > TemplateBuffer
TMap< uint32, FNodeTemplateRegistryHandle > TemplateUIDToHandleMap
Friends
struct FScopedClearNodeTemplateRegistry
class FTraitWriter
class UE::AnimNext::AnimGraph::FAnimNextAnimGraphModule
Detailed Description
FNodeTemplateRegistry.
A global registry of all existing node templates that can be shared between animation graph instances.
See also
FNodeTemplate
Definition at line 26 of file NodeTemplateRegistry.h.
Constructor & Destructor Documentation
FNodeTemplateRegistry() [1/3]
UE::AnimNext::FNodeTemplateRegistry::FNodeTemplateRegistry () private default
Referenced by FNodeTemplateRegistry(), FNodeTemplateRegistry(), Get(), operator=(), and operator=().
FNodeTemplateRegistry() [2/3]
UE::AnimNext::FNodeTemplateRegistry::FNodeTemplateRegistry (const FNodeTemplateRegistry &) private delete
References FNodeTemplateRegistry().
FNodeTemplateRegistry() [3/3]
UE::AnimNext::FNodeTemplateRegistry::FNodeTemplateRegistry (FNodeTemplateRegistry &&) private default
References FNodeTemplateRegistry().
Member Function Documentation
Destroy()
ANIMNEXTANIMGRAPH_API void UE::AnimNext::FNodeTemplateRegistry::Destroy () static private
References UE_API.
Find() [1/2]
ANIMNEXTANIMGRAPH_API const FNodeTemplate * UE::AnimNext::FNodeTemplateRegistry::Find (FNodeTemplateRegistryHandle TemplateHandle) const
References UE_API.
Find() [2/2]
ANIMNEXTANIMGRAPH_API FNodeTemplateRegistryHandle UE::AnimNext::FNodeTemplateRegistry::Find (uint32 NodeTemplateUID) const
References UE_API.
FindMutable()
ANIMNEXTANIMGRAPH_API FNodeTemplate * UE::AnimNext::FNodeTemplateRegistry::FindMutable (FNodeTemplateRegistryHandle TemplateHandle) private
References UE_API.
FindOrAdd()
ANIMNEXTANIMGRAPH_API FNodeTemplateRegistryHandle UE::AnimNext::FNodeTemplateRegistry::FindOrAdd (const FNodeTemplate * NodeTemplate)
References UE_API.
Get()
ANIMNEXTANIMGRAPH_API FNodeTemplateRegistry & UE::AnimNext::FNodeTemplateRegistry::Get () static
References FNodeTemplateRegistry(), and UE_API.
GetNum()
ANIMNEXTANIMGRAPH_API uint32 UE::AnimNext::FNodeTemplateRegistry::GetNum () const
References UE_API.
Init()
ANIMNEXTANIMGRAPH_API void UE::AnimNext::FNodeTemplateRegistry::Init () static private
References UE_API.
operator=() [1/2]
FNodeTemplateRegistry & UE::AnimNext::FNodeTemplateRegistry::operator= (const FNodeTemplateRegistry &) private delete
References FNodeTemplateRegistry().
operator=() [2/2]
FNodeTemplateRegistry & UE::AnimNext::FNodeTemplateRegistry::operator= (FNodeTemplateRegistry &&) private default
References FNodeTemplateRegistry().
Unregister()
ANIMNEXTANIMGRAPH_API void UE::AnimNext::FNodeTemplateRegistry::Unregister (const FNodeTemplate * NodeTemplate)
References UE_API.
Friends And Related Symbol Documentation
FScopedClearNodeTemplateRegistry
friend struct FScopedClearNodeTemplateRegistry friend
Definition at line 72 of file NodeTemplateRegistry.h.
References FScopedClearNodeTemplateRegistry.
Referenced by FScopedClearNodeTemplateRegistry.
FTraitWriter
friend class FTraitWriter friend
Definition at line 71 of file NodeTemplateRegistry.h.
References FTraitWriter.
Referenced by FTraitWriter.
UE::AnimNext::AnimGraph::FAnimNextAnimGraphModule
friend class UE::AnimNext::AnimGraph::FAnimNextAnimGraphModule friend
Definition at line 70 of file NodeTemplateRegistry.h.
References UE::AnimNext::AnimGraph::FAnimNextAnimGraphModule.
Referenced by UE::AnimNext::AnimGraph::FAnimNextAnimGraphModule.
Field Documentation
TemplateBuffer
TArray<uint8> UE::AnimNext::FNodeTemplateRegistry::TemplateBuffer private
Definition at line 67 of file NodeTemplateRegistry.h.
TemplateUIDToHandleMap
TMap<uint32, FNodeTemplateRegistryHandle> UE::AnimNext::FNodeTemplateRegistry::TemplateUIDToHandleMap private
Definition at line 68 of file NodeTemplateRegistry.h.
The documentation for this struct was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Experimental/AnimNextAnimGraph/Source/AnimNextAnimGraph/Internal/TraitCore/NodeTemplateRegistry.h