Unreal Engine 5.6 C++ API: UE::MovieScene::TPrelockedDataOffsets< AccessorTypes > Struct Template Reference
UE::MovieScene::TPrelockedDataOffsets< AccessorTypes > Struct Template Reference
#include "MovieSceneEntitySystemTask.h"
Public Member Functions
constexpr TPrelockedDataOffsets ()
constexpr void Assign (int &Index, int &DataIndex, int DataSize)
Data Fields
int32 StartOffset [sizeof...(AccessorTypes)] ={}
Static Public Attributes
static constexpr int32 Num = (... + AccessorTypes::PreLockedDataNum)
Detailed Description
template<typename ... AccessorTypes>
struct UE::MovieScene::TPrelockedDataOffsets< AccessorTypes >
Definition at line 1852 of file MovieSceneEntitySystemTask.h.
Constructor & Destructor Documentation
TPrelockedDataOffsets()
template<typename ... AccessorTypes> UE::MovieScene::TPrelockedDataOffsets< AccessorTypes >::TPrelockedDataOffsets () inline constexpr
Definition at line 1858 of file MovieSceneEntitySystemTask.h.
References Assign().
Member Function Documentation
Assign()
template<typename ... AccessorTypes> void UE::MovieScene::TPrelockedDataOffsets< AccessorTypes >::Assign (int & Index, int & DataIndex, int DataSize) inline constexpr
Definition at line 1863 of file MovieSceneEntitySystemTask.h.
References DataSize, and StartOffset.
Referenced by TPrelockedDataOffsets().
Field Documentation
Num
template<typename ... AccessorTypes> int32 UE::MovieScene::TPrelockedDataOffsets< AccessorTypes >::Num = (... + AccessorTypes::PreLockedDataNum) static constexpr
Definition at line 1854 of file MovieSceneEntitySystemTask.h.
StartOffset
template<typename ... AccessorTypes> int32 UE::MovieScene::TPrelockedDataOffsets< AccessorTypes >::StartOffset[sizeof...(AccessorTypes)] ={}
Definition at line 1856 of file MovieSceneEntitySystemTask.h.
Referenced by Assign().
The documentation for this struct was generated from the following file:
Runtime/MovieScene/Public/EntitySystem/MovieSceneEntitySystemTask.h