Unreal Engine 5.6 C++ API: TAddKeyImpl< ChannelType, ValueType > Struct Template Reference
TAddKeyImpl< ChannelType, ValueType > Struct Template Reference
#include "KeyframeTrackEditor.h"
Public Member Functions
TAddKeyImpl (int32 InChannelIndex, bool bInAddKey, const ValueType &InValue)
virtual bool Apply (UMovieSceneSection *Section, FMovieSceneChannelProxy &Proxy, FFrameNumber InTime, EMovieSceneKeyInterpolation InterpolationMode, bool bKeyEvenIfUnchanged, bool bKeyEvenIfEmpty) const override
virtual void ApplyDefault (UMovieSceneSection *Section, FMovieSceneChannelProxy &Proxy, EKeyFrameTrackEditorSetDefault SetDefault) const override
virtual bool ModifyByCurrentAndWeight (FMovieSceneChannelProxy &Proxy, FFrameNumber InTime, void *VCurrentValue, float Weight)
Public Member Functions inherited from IImpl
virtual ~IImpl ()
Data Fields
bool bAddKey
int32 ChannelIndex
ValueType ValueToSet
Detailed Description
template<typename ChannelType, typename ValueType>
struct TAddKeyImpl< ChannelType, ValueType >
Definition at line 53 of file KeyframeTrackEditor.h.
Constructor & Destructor Documentation
TAddKeyImpl()
template<typename ChannelType, typename ValueType> TAddKeyImpl< ChannelType, ValueType >::TAddKeyImpl (int32 InChannelIndex, bool bInAddKey, const ValueType & InValue) inline
Definition at line 59 of file KeyframeTrackEditor.h.
References bAddKey, ChannelIndex, and ValueToSet.
Member Function Documentation
Apply()
template<typename ChannelType, typename ValueType> virtual bool TAddKeyImpl< ChannelType, ValueType >::Apply (UMovieSceneSection * Section, FMovieSceneChannelProxy & Proxy, FFrameNumber InTime, EMovieSceneKeyInterpolation InterpolationMode, bool bKeyEvenIfUnchanged, bool bKeyEvenIfEmpty) const inline override virtual
Reimplemented from IImpl.
Definition at line 63 of file KeyframeTrackEditor.h.
References AddKeyToChannel(), bAddKey, ChannelIndex, FMovieSceneChannelProxy::GetChannel(), GetInterpolationMode(), InTime, ValueExistsAtTime(), and ValueToSet.
ApplyDefault()
template<typename ChannelType, typename ValueType> virtual void TAddKeyImpl< ChannelType, ValueType >::ApplyDefault (UMovieSceneSection * Section, FMovieSceneChannelProxy & Proxy, EKeyFrameTrackEditorSetDefault SetDefault) const inline override virtual
Reimplemented from IImpl.
Definition at line 94 of file KeyframeTrackEditor.h.
References ChannelIndex, FMovieSceneChannelProxy::GetChannel(), UE::MovieScene::SetChannelDefault(), SetDefault, and ValueToSet.
ModifyByCurrentAndWeight()
template<typename ChannelType, typename ValueType> virtual bool TAddKeyImpl< ChannelType, ValueType >::ModifyByCurrentAndWeight (FMovieSceneChannelProxy & Proxy, FFrameNumber InTime, void * VCurrentValue, float Weight) inline virtual
Reimplemented from IImpl.
Definition at line 108 of file KeyframeTrackEditor.h.
References InTime, and Weight.
Field Documentation
bAddKey
template<typename ChannelType, typename ValueType> bool TAddKeyImpl< ChannelType, ValueType >::bAddKey
Definition at line 56 of file KeyframeTrackEditor.h.
Referenced by TAddKeyImpl(), and Apply().
ChannelIndex
template<typename ChannelType, typename ValueType> int32 TAddKeyImpl< ChannelType, ValueType >::ChannelIndex
Definition at line 55 of file KeyframeTrackEditor.h.
Referenced by TAddKeyImpl(), Apply(), and ApplyDefault().
ValueToSet
template<typename ChannelType, typename ValueType> ValueType TAddKeyImpl< ChannelType, ValueType >::ValueToSet
Definition at line 57 of file KeyframeTrackEditor.h.
Referenced by TAddKeyImpl(), Apply(), and ApplyDefault().
The documentation for this struct was generated from the following file:
Editor/MovieSceneTools/Public/KeyframeTrackEditor.h