Unreal Engine 5.6 C++ API: FBTNodeIndex Struct Reference
FBTNodeIndex Struct Reference
#include "BehaviorTreeTypes.h"
Public Member Functions
FBTNodeIndex ()
FBTNodeIndex (uint16 InInstanceIndex, uint16 InExecutionIndex)
FORCEINLINE FString Describe () const
bool IsSet () const
FORCEINLINE bool operator!= (const FBTNodeIndex &Other) const
FORCEINLINE bool operator== (const FBTNodeIndex &Other) const
bool TakesPriorityOver (const FBTNodeIndex &Other) const
Data Fields
uint16 ExecutionIndex
execution index within instance
uint16 InstanceIndex
index of instance of stack
Static Public Attributes
static constexpr uint16 InvalidIndex = TNumericLimits<uint16>::Max()
Friends
FORCEINLINE friend uint32 GetTypeHash (const FBTNodeIndex &Other)
Detailed Description
Definition at line 449 of file BehaviorTreeTypes.h.
Constructor & Destructor Documentation
FBTNodeIndex() [1/2]
FBTNodeIndex::FBTNodeIndex () inline
Definition at line 459 of file BehaviorTreeTypes.h.
References ExecutionIndex, InstanceIndex, and InvalidIndex.
Referenced by GetTypeHash, operator!=(), operator==(), and TakesPriorityOver().
FBTNodeIndex() [2/2]
FBTNodeIndex::FBTNodeIndex (uint16 InInstanceIndex, uint16 InExecutionIndex) inline
Definition at line 460 of file BehaviorTreeTypes.h.
References ExecutionIndex, and InstanceIndex.
Member Function Documentation
Describe()
FORCEINLINE FString FBTNodeIndex::Describe () const inline
Definition at line 469 of file BehaviorTreeTypes.h.
References ExecutionIndex, FORCEINLINE, InstanceIndex, and TEXT.
IsSet()
bool FBTNodeIndex::IsSet () const inline
Definition at line 463 of file BehaviorTreeTypes.h.
References InstanceIndex, and InvalidIndex.
operator!=()
FORCEINLINE bool FBTNodeIndex::operator!= (const FBTNodeIndex & Other) const inline
Definition at line 466 of file BehaviorTreeTypes.h.
References FBTNodeIndex(), FORCEINLINE, operator==(), and Other.
operator==()
FORCEINLINE bool FBTNodeIndex::operator== (const FBTNodeIndex & Other) const inline
Definition at line 465 of file BehaviorTreeTypes.h.
References FBTNodeIndex(), ExecutionIndex, FORCEINLINE, InstanceIndex, and Other.
Referenced by operator!=().
TakesPriorityOver()
bool FBTNodeIndex::TakesPriorityOver (const FBTNodeIndex & Other) const
References FBTNodeIndex(), and Other.
Friends And Related Symbol Documentation
GetTypeHash
FORCEINLINE friend uint32 GetTypeHash (const FBTNodeIndex & Other) friend
Definition at line 467 of file BehaviorTreeTypes.h.
References FBTNodeIndex(), FORCEINLINE, and Other.
Field Documentation
ExecutionIndex
uint16 FBTNodeIndex::ExecutionIndex
execution index within instance
Definition at line 457 of file BehaviorTreeTypes.h.
Referenced by FBTNodeIndex(), FBTNodeIndex(), Describe(), and operator==().
InstanceIndex
uint16 FBTNodeIndex::InstanceIndex
index of instance of stack
Definition at line 454 of file BehaviorTreeTypes.h.
Referenced by FBTNodeIndex(), FBTNodeIndex(), Describe(), IsSet(), and operator==().
InvalidIndex
uint16 FBTNodeIndex::InvalidIndex = TNumericLimits<uint16>::Max() static constexpr
Definition at line 451 of file BehaviorTreeTypes.h.
Referenced by FBTNodeIndex(), and IsSet().
The documentation for this struct was generated from the following file:
Runtime/AIModule/Classes/BehaviorTree/BehaviorTreeTypes.h