Unreal Engine 5.6 C++ API: TContainerElementTypeCompatibility< InElementType > Struct Template Reference
TContainerElementTypeCompatibility< InElementType > Struct Template Reference
Temporary compatibility mechanism to be used solely for the purpose of raw pointers to wrapped pointers.
#include "ContainerElementTypeCompatibility.h"
Public Types
typedef InElementType CopyFromOtherType
typedef InElementType ReinterpretType
Static Public Member Functions
static constexpr void CopyingFromOtherType ()
template<typename IterBeginType, typename IterEndType, typename OperatorType = InElementType&(*)(IterBeginType&)>
static void ReinterpretRange (IterBeginType Iter, IterEndType IterEnd, OperatorType Operator=[](IterBeginType &InIt) -> InElementType &{ return *InIt;})
template<typename IterBeginType, typename IterEndType, typename SizeType, typename OperatorType = InElementType & (*)(IterBeginType&)>
static void ReinterpretRangeContiguous (IterBeginType Iter, IterEndType IterEnd, SizeType Size, OperatorType Operator=[](IterBeginType &InIt) -> InElementType &{ return *InIt;})
Detailed Description
template<typename InElementType>
struct TContainerElementTypeCompatibility< InElementType >
Temporary compatibility mechanism to be used solely for the purpose of raw pointers to wrapped pointers.
Specialization and use of this type is not supported beyond the specific instances in ObjectPtr.h. These types and the container methods that leverage them will be removed in a future release.
Definition at line 14 of file ContainerElementTypeCompatibility.h.
Member Typedef Documentation
CopyFromOtherType
template<typename InElementType> typedef InElementType TContainerElementTypeCompatibility< InElementType >::CopyFromOtherType
Definition at line 17 of file ContainerElementTypeCompatibility.h.
ReinterpretType
template<typename InElementType> typedef InElementType TContainerElementTypeCompatibility< InElementType >::ReinterpretType
Definition at line 16 of file ContainerElementTypeCompatibility.h.
Member Function Documentation
CopyingFromOtherType()
template<typename InElementType> constexpr void TContainerElementTypeCompatibility< InElementType >::CopyingFromOtherType () inline static constexpr
Definition at line 29 of file ContainerElementTypeCompatibility.h.
Referenced by RangedForIteratorType< FAnimNextTraitEventPtr >::Append(), TSet< class UObject * >::Append(), TSet< class UObject * >::Append(), RangedForIteratorType< FAnimNextTraitEventPtr >::Insert(), RangedForIteratorType< FAnimNextTraitEventPtr >::Insert(), RangedForIteratorType< FAnimNextTraitEventPtr >::operator=(), RangedForIteratorType< FAnimNextTraitEventPtr >::operator=(), TSet< class UObject * >::operator=(), and TSet< class UObject * >::operator=().
ReinterpretRange()
template<typename InElementType> template<typename IterBeginType, typename IterEndType, typename OperatorType = InElementType&(*)(IterBeginType&)> void TContainerElementTypeCompatibility< InElementType >::ReinterpretRange (IterBeginType Iter, IterEndType IterEnd, OperatorType Operator = [](IterBeginType& InIt) -> InElementType& { return *InIt; }) inline static
Definition at line 20 of file ContainerElementTypeCompatibility.h.
ReinterpretRangeContiguous()
template<typename InElementType> template<typename IterBeginType, typename IterEndType, typename SizeType, typename OperatorType = InElementType & (*)(IterBeginType&)> void TContainerElementTypeCompatibility< InElementType >::ReinterpretRangeContiguous (IterBeginType Iter, IterEndType IterEnd, SizeType Size, OperatorType Operator = [](IterBeginType& InIt) -> InElementType& { return *InIt; }) inline static
Definition at line 25 of file ContainerElementTypeCompatibility.h.
Referenced by UE::Core::ArrayView::Private::GetReinterpretedDataHelper().
The documentation for this struct was generated from the following file:
Runtime/Core/Public/Containers/ContainerElementTypeCompatibility.h