Unreal Engine 5.6 C++ API: TWeakInterfacePtr< T > Struct Template Reference
TWeakInterfacePtr< T > Struct Template Reference
An alternative to TWeakObjectPtr that makes it easier to work through an interface.
#include "WeakInterfacePtr.h"
Public Types
using ElementType = T
using UObjectType = TCopyQualifiersFromTo_T<T, UObject>
Public Member Functions
FORCEINLINE TWeakInterfacePtr ()=default
TWeakInterfacePtr (const TScriptInterface< T > &ScriptInterface)
Construct from a TScriptInterface of the same interface type.
FORCEINLINE TWeakInterfacePtr (const TWeakInterfacePtr &Other)=default
TWeakInterfacePtr (T *Interface)
Construct from an interface pointer.
FORCEINLINE TWeakInterfacePtr (TWeakInterfacePtr &&Other)=default
template<typename U UE_REQUIRES>
TWeakInterfacePtr (U &&Object)
Construct from an object pointer.
FORCEINLINE ~TWeakInterfacePtr ()=default
FORCEINLINE T * Get () const
Dereference the weak pointer into an interface pointer.
FORCEINLINE UObjectType * GetObject () const
Dereference the weak pointer into a UObject pointer.
FORCEINLINE TWeakObjectPtr< UObjectType > GetWeakObjectPtr () const
FORCEINLINE bool IsStale (bool bEvenIfPendingKill=false, bool bThreadsafeTest=false) const
Test if this pointer is stale.
FORCEINLINE bool IsValid () const
Test if this points to a live object.
FORCEINLINE bool IsValid (bool bEvenIfPendingKill, bool bThreadsafeTest=false) const
Test if this points to a live object.
FORCEINLINE bool operator!= (const TWeakInterfacePtr< T > &Other) const
FORCEINLINE T & operator* () const
Dereference the weak pointer.
FORCEINLINE T * operator-> () const
Dereference the weak pointer.
FORCEINLINE TWeakInterfacePtr< T > & operator= (const TScriptInterface< T > &Other)
Assign from a script interface.
FORCEINLINE TWeakInterfacePtr & operator= (const TWeakInterfacePtr &Other)=default
FORCEINLINE TWeakInterfacePtr< T > & operator= (T *Other)
Assign from an interface pointer.
FORCEINLINE TWeakInterfacePtr & operator= (TWeakInterfacePtr &&Other)=default
FORCEINLINE bool operator== (const TWeakInterfacePtr< T > &Other) const
FORCEINLINE void Reset ()
Reset the weak pointer back to the null state.
FORCEINLINE TScriptInterface< T > ToScriptInterface () const
Private Attributes
T * InterfaceInstance = nullptr
TWeakObjectPtr< UObjectType > ObjectInstance
Detailed Description
template<class T>
struct TWeakInterfacePtr< T >
An alternative to TWeakObjectPtr that makes it easier to work through an interface.
Definition at line 17 of file WeakInterfacePtr.h.
Member Typedef Documentation
ElementType
template<class T> using TWeakInterfacePtr< T >::ElementType = T
Definition at line 19 of file WeakInterfacePtr.h.
UObjectType
template<class T> using TWeakInterfacePtr< T >::UObjectType = TCopyQualifiersFromTo_T<T, UObject>
Definition at line 20 of file WeakInterfacePtr.h.
Constructor & Destructor Documentation
TWeakInterfacePtr() [1/6]
template<class T> FORCEINLINE TWeakInterfacePtr< T >::TWeakInterfacePtr () default
Referenced by TWeakInterfacePtr< IActorInstanceManagerInterface >::operator=().
TWeakInterfacePtr() [2/6]
template<class T> FORCEINLINE TWeakInterfacePtr< T >::TWeakInterfacePtr (const TWeakInterfacePtr< T > & Other) default
TWeakInterfacePtr() [3/6]
template<class T> FORCEINLINE TWeakInterfacePtr< T >::TWeakInterfacePtr (TWeakInterfacePtr< T > && Other) default
~TWeakInterfacePtr()
template<class T> FORCEINLINE TWeakInterfacePtr< T >::~TWeakInterfacePtr () default
TWeakInterfacePtr() [4/6]
template<class T> template<typename U UE_REQUIRES> TWeakInterfacePtr< T >::TWeakInterfacePtr (U && Object) inline
Construct from an object pointer.
Parameters
Object The object to create a weak pointer to. This object must implement interface T.
Definition at line 37 of file WeakInterfacePtr.h.
TWeakInterfacePtr() [5/6]
template<class T> TWeakInterfacePtr< T >::TWeakInterfacePtr (T * Interface) inline
Construct from an interface pointer.
Parameters
Interface The interface pointer to create a weak pointer to. There must be a UObject behind the interface.
Definition at line 50 of file WeakInterfacePtr.h.
TWeakInterfacePtr() [6/6]
template<class T> TWeakInterfacePtr< T >::TWeakInterfacePtr (const TScriptInterface< T > & ScriptInterface) inline
Construct from a TScriptInterface of the same interface type.
Parameters
ScriptInterface The TScriptInterface to copy from. No validation is done here; passing an invalid TScriptInterface in will result in an invalid TWeakInterfacePtr.
Definition at line 64 of file WeakInterfacePtr.h.
Member Function Documentation
Get()
template<class T> FORCEINLINE T * TWeakInterfacePtr< T >::Get () const inline
Dereference the weak pointer into an interface pointer.
Definition at line 106 of file WeakInterfacePtr.h.
Referenced by UE::PixelStreaming2::TObserverVariant< T >::operator->().
GetObject()
template<class T> FORCEINLINE UObjectType * TWeakInterfacePtr< T >::GetObject () const inline
Dereference the weak pointer into a UObject pointer.
Definition at line 114 of file WeakInterfacePtr.h.
GetWeakObjectPtr()
template<class T> FORCEINLINE TWeakObjectPtr< UObjectType > TWeakInterfacePtr< T >::GetWeakObjectPtr () const inline
Definition at line 177 of file WeakInterfacePtr.h.
IsStale()
template<class T> FORCEINLINE bool TWeakInterfacePtr< T >::IsStale (bool bEvenIfPendingKill = false, bool bThreadsafeTest = false) const inline
Test if this pointer is stale.
Parameters are passed to the underlying TWeakObjectPtr.
Definition at line 98 of file WeakInterfacePtr.h.
IsValid() [1/2]
template<class T> FORCEINLINE bool TWeakInterfacePtr< T >::IsValid () const inline
Test if this points to a live object.
Calls the underlying TWeakObjectPtr's parameterless IsValid method.
Definition at line 90 of file WeakInterfacePtr.h.
Referenced by TWeakInterfacePtr< IActorInstanceManagerInterface >::Get(), TWeakInterfacePtr< IActorInstanceManagerInterface >::operator*(), and TWeakInterfacePtr< IActorInstanceManagerInterface >::operator->().
IsValid() [2/2]
template<class T> FORCEINLINE bool TWeakInterfacePtr< T >::IsValid (bool bEvenIfPendingKill, bool bThreadsafeTest = false) const inline
Test if this points to a live object.
Parameters are passed to the underlying TWeakObjectPtr.
Definition at line 82 of file WeakInterfacePtr.h.
Referenced by UE::PixelStreaming2::TObserverVariant< T >::operator->().
operator!=()
template<class T> FORCEINLINE bool TWeakInterfacePtr< T >::operator!= (const TWeakInterfacePtr< T > & Other) const inline
Definition at line 161 of file WeakInterfacePtr.h.
operator*()
template<class T> FORCEINLINE T & TWeakInterfacePtr< T >::operator* () const inline
Dereference the weak pointer.
Definition at line 122 of file WeakInterfacePtr.h.
operator->()
template<class T> FORCEINLINE T * TWeakInterfacePtr< T >::operator-> () const inline
Dereference the weak pointer.
Definition at line 131 of file WeakInterfacePtr.h.
operator=() [1/4]
template<class T> FORCEINLINE TWeakInterfacePtr< T > & TWeakInterfacePtr< T >::operator= (const TScriptInterface< T > & Other) inline
Assign from a script interface.
Definition at line 149 of file WeakInterfacePtr.h.
operator=() [2/4]
template<class T> FORCEINLINE TWeakInterfacePtr & TWeakInterfacePtr< T >::operator= (const TWeakInterfacePtr< T > & Other) default
operator=() [3/4]
template<class T> FORCEINLINE TWeakInterfacePtr< T > & TWeakInterfacePtr< T >::operator= (T * Other) inline
Assign from an interface pointer.
Definition at line 140 of file WeakInterfacePtr.h.
operator=() [4/4]
template<class T> FORCEINLINE TWeakInterfacePtr & TWeakInterfacePtr< T >::operator= (TWeakInterfacePtr< T > && Other) default
operator==()
template<class T> FORCEINLINE bool TWeakInterfacePtr< T >::operator== (const TWeakInterfacePtr< T > & Other) const inline
Definition at line 156 of file WeakInterfacePtr.h.
Reset()
template<class T> FORCEINLINE void TWeakInterfacePtr< T >::Reset () inline
Reset the weak pointer back to the null state.
Definition at line 73 of file WeakInterfacePtr.h.
ToScriptInterface()
template<class T> FORCEINLINE TScriptInterface< T > TWeakInterfacePtr< T >::ToScriptInterface () const inline
Definition at line 166 of file WeakInterfacePtr.h.
Field Documentation
InterfaceInstance
template<class T> T* TWeakInterfacePtr< T >::InterfaceInstance = nullptr private
Definition at line 184 of file WeakInterfacePtr.h.
ObjectInstance
template<class T> TWeakObjectPtr<UObjectType> TWeakInterfacePtr< T >::ObjectInstance private
Definition at line 183 of file WeakInterfacePtr.h.
The documentation for this struct was generated from the following file:
Runtime/CoreUObject/Public/UObject/WeakInterfacePtr.h