Unreal Engine 5.6 C++ API: UE::MovieScene::TPropertyDefinitionBuilder< PropertyTraits > Struct Template Reference
UE::MovieScene::TPropertyDefinitionBuilder< PropertyTraits > Struct Template Reference
#include "MovieScenePropertyComponentHandler.h"
Public Member Functions
TPropertyDefinitionBuilder< PropertyTraits > & AddSoleChannel (TComponentTypeID< typename PropertyTraits::StorageType > InComponent)
void Commit ()
template<typename HandlerType>
void Commit (HandlerType &&InHandler)
template<typename BlenderSystemType>
TPropertyDefinitionBuilder< PropertyTraits > & SetBlenderSystem ()
TPropertyDefinitionBuilder< PropertyTraits > & SetBlenderSystem (UClass *BlenderSystemClass)
template<int InlineSize>
TPropertyDefinitionBuilder< PropertyTraits > & SetCustomAccessors (TCustomPropertyRegistration< PropertyTraits, InlineSize > *InCustomAccessors)
TPropertyDefinitionBuilder< PropertyTraits > & SetStat (TStatId InStatID)
Protected Member Functions
TPropertyDefinitionBuilder (FPropertyDefinition *InDefinition, FPropertyRegistry *InRegistry)
Protected Attributes
FPropertyDefinition * Definition
friend FPropertyRegistry
FPropertyRegistry * Registry
Detailed Description
template<typename PropertyTraits>
struct UE::MovieScene::TPropertyDefinitionBuilder< PropertyTraits >
Definition at line 636 of file MovieScenePropertyComponentHandler.h.
Constructor & Destructor Documentation
TPropertyDefinitionBuilder()
template<typename PropertyTraits> UE::MovieScene::TPropertyDefinitionBuilder< PropertyTraits >::TPropertyDefinitionBuilder (FPropertyDefinition * InDefinition, FPropertyRegistry * InRegistry) inline protected
Definition at line 701 of file MovieScenePropertyComponentHandler.h.
References Definition, FPropertyRegistry, and Registry.
Referenced by AddSoleChannel(), SetBlenderSystem(), SetBlenderSystem(), SetCustomAccessors(), and SetStat().
Member Function Documentation
AddSoleChannel()
template<typename PropertyTraits> TPropertyDefinitionBuilder< PropertyTraits > & UE::MovieScene::TPropertyDefinitionBuilder< PropertyTraits >::AddSoleChannel (TComponentTypeID< typename PropertyTraits::StorageType > InComponent) inline
Definition at line 638 of file MovieScenePropertyComponentHandler.h.
References TPropertyDefinitionBuilder(), checkf, Definition, Registry, and TEXT.
Commit() [1/2]
template<typename PropertyTraits> void UE::MovieScene::TPropertyDefinitionBuilder< PropertyTraits >::Commit () inline
Definition at line 684 of file MovieScenePropertyComponentHandler.h.
References Definition.
Commit() [2/2]
template<typename PropertyTraits> template<typename HandlerType> void UE::MovieScene::TPropertyDefinitionBuilder< PropertyTraits >::Commit (HandlerType && InHandler) inline
Definition at line 691 of file MovieScenePropertyComponentHandler.h.
References Definition, and Forward().
SetBlenderSystem() [1/2]
template<typename PropertyTraits> template<typename BlenderSystemType> TPropertyDefinitionBuilder< PropertyTraits > & UE::MovieScene::TPropertyDefinitionBuilder< PropertyTraits >::SetBlenderSystem () inline
Definition at line 672 of file MovieScenePropertyComponentHandler.h.
References TPropertyDefinitionBuilder(), and Definition.
SetBlenderSystem() [2/2]
template<typename PropertyTraits> TPropertyDefinitionBuilder< PropertyTraits > & UE::MovieScene::TPropertyDefinitionBuilder< PropertyTraits >::SetBlenderSystem (UClass * BlenderSystemClass) inline
Definition at line 678 of file MovieScenePropertyComponentHandler.h.
References TPropertyDefinitionBuilder(), and Definition.
SetCustomAccessors()
template<typename PropertyTraits> template<int InlineSize> TPropertyDefinitionBuilder< PropertyTraits > & UE::MovieScene::TPropertyDefinitionBuilder< PropertyTraits >::SetCustomAccessors (TCustomPropertyRegistration< PropertyTraits, InlineSize > * InCustomAccessors) inline
Definition at line 659 of file MovieScenePropertyComponentHandler.h.
References TPropertyDefinitionBuilder(), and Definition.
SetStat()
template<typename PropertyTraits> TPropertyDefinitionBuilder< PropertyTraits > & UE::MovieScene::TPropertyDefinitionBuilder< PropertyTraits >::SetStat (TStatId InStatID) inline
Definition at line 665 of file MovieScenePropertyComponentHandler.h.
References TPropertyDefinitionBuilder(), and Definition.
Field Documentation
Definition
template<typename PropertyTraits> FPropertyDefinition* UE::MovieScene::TPropertyDefinitionBuilder< PropertyTraits >::Definition protected
Definition at line 705 of file MovieScenePropertyComponentHandler.h.
Referenced by TPropertyDefinitionBuilder(), AddSoleChannel(), Commit(), Commit(), SetBlenderSystem(), SetBlenderSystem(), SetCustomAccessors(), and SetStat().
FPropertyRegistry
template<typename PropertyTraits> friend UE::MovieScene::TPropertyDefinitionBuilder< PropertyTraits >::FPropertyRegistry protected
Definition at line 699 of file MovieScenePropertyComponentHandler.h.
Referenced by TPropertyDefinitionBuilder().
Registry
template<typename PropertyTraits> FPropertyRegistry* UE::MovieScene::TPropertyDefinitionBuilder< PropertyTraits >::Registry protected
Definition at line 706 of file MovieScenePropertyComponentHandler.h.
Referenced by TPropertyDefinitionBuilder(), and AddSoleChannel().
The documentation for this struct was generated from the following file:
Runtime/MovieScene/Public/EntitySystem/MovieScenePropertyComponentHandler.h