Unreal Engine 5.6 C++ API: FNetQueuedActorDelinquencyAnalytics Struct Reference
FNetQueuedActorDelinquencyAnalytics Struct Reference
Tracks data related specific to a NetConnection that can can result in prolonged periods of apparent network inactivity, despite actually receiving traffic.
#include "NetAnalyticsTypes.h"
Public Member Functions
FNetQueuedActorDelinquencyAnalytics ()
FNetQueuedActorDelinquencyAnalytics (const FNetQueuedActorDelinquencyAnalytics &)=delete
FNetQueuedActorDelinquencyAnalytics (const uint32 NumberOfTopOffendersToTrack)
FNetQueuedActorDelinquencyAnalytics (FNetQueuedActorDelinquencyAnalytics &&Other)
void CountBytes (FArchive &Ar) const
const FNetQueuedActorDelinquencyAnalytics & operator= (const FNetQueuedActorDelinquencyAnalytics &)=delete
FNetQueuedActorDelinquencyAnalytics & operator= (FNetQueuedActorDelinquencyAnalytics &&)=default
void Reset ()
Data Fields
FDelinquencyAnalytics DelinquentQueuedActors
uint32 MaxConcurrentQueuedActors
Detailed Description
Tracks data related specific to a NetConnection that can can result in prolonged periods of apparent network inactivity, despite actually receiving traffic.
Also
See also
FDriverDelinquencyAnalytics and FDelinquencyAnalytics.
Definition at line 177 of file NetAnalyticsTypes.h.
Constructor & Destructor Documentation
FNetQueuedActorDelinquencyAnalytics() [1/4]
FNetQueuedActorDelinquencyAnalytics::FNetQueuedActorDelinquencyAnalytics () inline
Definition at line 179 of file NetAnalyticsTypes.h.
References DelinquentQueuedActors, and MaxConcurrentQueuedActors.
Referenced by FNetQueuedActorDelinquencyAnalytics(), FNetQueuedActorDelinquencyAnalytics(), operator=(), and operator=().
FNetQueuedActorDelinquencyAnalytics() [2/4]
FNetQueuedActorDelinquencyAnalytics::FNetQueuedActorDelinquencyAnalytics (const uint32 NumberOfTopOffendersToTrack) inline
Definition at line 185 of file NetAnalyticsTypes.h.
References DelinquentQueuedActors, and MaxConcurrentQueuedActors.
FNetQueuedActorDelinquencyAnalytics() [3/4]
FNetQueuedActorDelinquencyAnalytics::FNetQueuedActorDelinquencyAnalytics (FNetQueuedActorDelinquencyAnalytics && Other) inline
Definition at line 191 of file NetAnalyticsTypes.h.
References FNetQueuedActorDelinquencyAnalytics(), DelinquentQueuedActors, MaxConcurrentQueuedActors, MoveTemp(), and Other.
FNetQueuedActorDelinquencyAnalytics() [4/4]
FNetQueuedActorDelinquencyAnalytics::FNetQueuedActorDelinquencyAnalytics (const FNetQueuedActorDelinquencyAnalytics &) delete
References FNetQueuedActorDelinquencyAnalytics().
Member Function Documentation
CountBytes()
void FNetQueuedActorDelinquencyAnalytics::CountBytes (FArchive & Ar) const inline
Definition at line 202 of file NetAnalyticsTypes.h.
References Ar, and DelinquentQueuedActors.
operator=() [1/2]
const FNetQueuedActorDelinquencyAnalytics & FNetQueuedActorDelinquencyAnalytics::operator= (const FNetQueuedActorDelinquencyAnalytics &) delete
References FNetQueuedActorDelinquencyAnalytics().
operator=() [2/2]
FNetQueuedActorDelinquencyAnalytics & FNetQueuedActorDelinquencyAnalytics::operator= (FNetQueuedActorDelinquencyAnalytics &&) default
References FNetQueuedActorDelinquencyAnalytics().
Reset()
void FNetQueuedActorDelinquencyAnalytics::Reset () inline
Definition at line 207 of file NetAnalyticsTypes.h.
References DelinquentQueuedActors, and MaxConcurrentQueuedActors.
Field Documentation
DelinquentQueuedActors
FDelinquencyAnalytics FNetQueuedActorDelinquencyAnalytics::DelinquentQueuedActors
Definition at line 213 of file NetAnalyticsTypes.h.
Referenced by FNetQueuedActorDelinquencyAnalytics(), FNetQueuedActorDelinquencyAnalytics(), FNetQueuedActorDelinquencyAnalytics(), CountBytes(), and Reset().
MaxConcurrentQueuedActors
uint32 FNetQueuedActorDelinquencyAnalytics::MaxConcurrentQueuedActors
Definition at line 214 of file NetAnalyticsTypes.h.
Referenced by FNetQueuedActorDelinquencyAnalytics(), FNetQueuedActorDelinquencyAnalytics(), FNetQueuedActorDelinquencyAnalytics(), and Reset().
The documentation for this struct was generated from the following file:
Runtime/Engine/Public/Net/NetAnalyticsTypes.h