Unreal Engine 5.6 C++ API: FCompressedTransform Struct Reference
FCompressedTransform Struct Reference
#include "RenderTransform.h"
Public Member Functions
FORCEINLINE FCompressedTransform ()
FORCEINLINE_DEBUGGABLE FCompressedTransform (const FRenderTransform &In)
FORCEINLINE FRenderTransform ToRenderTransform () const
Data Fields
uint16 Rotation [4]
uint16 Scale_SharedExp [4]
FVector3f Translation
Static Public Attributes
static constexpr uint32 ExpBias = (1 << (ExpBits - 1)) - 1
static constexpr uint32 ExpBits = 8
static constexpr uint32 MantissaBits = SignMantissaBits - 1
static constexpr uint32 SignMantissaBits = 16
static constexpr uint32 SignMantissaMask = (1 << SignMantissaBits) - 1
Detailed Description
Definition at line 439 of file RenderTransform.h.
Constructor & Destructor Documentation
FCompressedTransform() [1/2]
FORCEINLINE FCompressedTransform::FCompressedTransform () inline
Definition at line 451 of file RenderTransform.h.
References FORCEINLINE.
FCompressedTransform() [2/2]
FORCEINLINE_DEBUGGABLE FCompressedTransform::FCompressedTransform (const FRenderTransform & In) inline
Definition at line 452 of file RenderTransform.h.
References Axis, FFloat32::Components, ExpBias, FFloat32::Exponent, FFloat32::FloatValue, FORCEINLINE_DEBUGGABLE, GetHemiOrthoBasis(), MantissaBits, FRenderTransform::Origin, Rotation, Scale, Scale_SharedExp, SignMantissaBits, FRenderTransform::TransformRows, Translation, UnitVectorToHemiOctahedron(), UE::Math::TVector2< T >::X, X, Y, UE::Math::TVector2< T >::Y, and Z.
Member Function Documentation
ToRenderTransform()
FORCEINLINE FRenderTransform FCompressedTransform::ToRenderTransform () const inline
Definition at line 550 of file RenderTransform.h.
References FFloat32::Components, ExpBias, FFloat32::Exponent, float, FFloat32::FloatValue, FORCEINLINE, GetHemiOrthoBasis(), HemiOctahedronToUnitVector(), MantissaBits, FRenderTransform::Origin, Rotation, Scale, Scale_SharedExp, SignMantissaBits, SignMantissaMask, FRenderTransform::TransformRows, Translation, UE::Math::TVector2< T >::X, X, Y, and UE::Math::TVector2< T >::Y.
Field Documentation
ExpBias
uint32 FCompressedTransform::ExpBias = (1 << (ExpBits - 1)) - 1 static constexpr
Definition at line 442 of file RenderTransform.h.
Referenced by FCompressedTransform(), and ToRenderTransform().
ExpBits
uint32 FCompressedTransform::ExpBits = 8 static constexpr
Definition at line 441 of file RenderTransform.h.
MantissaBits
uint32 FCompressedTransform::MantissaBits = SignMantissaBits - 1 static constexpr
Definition at line 445 of file RenderTransform.h.
Referenced by FCompressedTransform(), and ToRenderTransform().
Rotation
uint16 FCompressedTransform::Rotation[4]
Definition at line 448 of file RenderTransform.h.
Referenced by FCompressedTransform(), FInstanceSceneShaderData::BuildInternal(), and ToRenderTransform().
Scale_SharedExp
uint16 FCompressedTransform::Scale_SharedExp[4]
Definition at line 449 of file RenderTransform.h.
Referenced by FCompressedTransform(), and ToRenderTransform().
SignMantissaBits
uint32 FCompressedTransform::SignMantissaBits = 16 static constexpr
Definition at line 443 of file RenderTransform.h.
Referenced by FCompressedTransform(), and ToRenderTransform().
SignMantissaMask
uint32 FCompressedTransform::SignMantissaMask = (1 << SignMantissaBits) - 1 static constexpr
Definition at line 444 of file RenderTransform.h.
Referenced by ToRenderTransform().
Translation
FVector3f FCompressedTransform::Translation
Definition at line 447 of file RenderTransform.h.
Referenced by FCompressedTransform(), FInstanceSceneShaderData::BuildInternal(), and ToRenderTransform().
The documentation for this struct was generated from the following file:
Runtime/RenderCore/Public/RenderTransform.h