Unreal Engine 5.6 C++ API: Audio::FModulationDestination Struct Reference
Audio::FModulationDestination Struct Reference
#include "SoundModulationDestination.h"
Data Structures
struct FModulationDestinationData
Public Member Functions
FModulationDestination ()=default
FModulationDestination (const FModulationDestination &InModulationDestination)
FModulationDestination (FModulationDestination &&InModulationDestination)
FORCEINLINE const FAlignedFloatBuffer & GetBuffer () const
Returns buffer of interpolated modulation values.
FORCEINLINE bool GetHasProcessed () const
Returns whether or not the destination has requested to process the control or not.
FORCEINLINE float GetValue () const
Returns sample value last reported by modulator.
void Init (FDeviceId InDeviceId, bool bInIsBuffered=false, bool bInValueNormalized=false)
Initializes the modulation destination InDeviceId - DeviceId associated with modulation plugin instance bInIsBuffered - Whether or not to run destination in "buffered mode," which manages an internal buffer to smooth modulation value between process calls bInValueNormalized - Whether or not to keep the output value in normalized, unitless [0.0f, 1.0f] space.
void Init (FDeviceId InDeviceId, FName InParameterName, bool bInIsBuffered=false, bool bInValueNormalized=false)
Initializes the modulation destination InDeviceId - DeviceId associated with modulation plugin instance InParameterName - Name of parameter used to mix/convert destination value to/from unit space bInIsBuffered - Whether or not to run destination in "buffered mode," which manages an internal buffer to smooth modulation value between process calls bInValueNormalized - Whether or not to keep the output value in normalized, unitless [0.0f, 1.0f] space.
bool IsActive () const
returns whether or not destination references an active modulator
FModulationDestination & operator= (const FModulationDestination &InModulationDestination)
FModulationDestination & operator= (FModulationDestination &&InModulationDestination)
bool ProcessControl (float InValueUnitBase, int32 InNumSamples=0)
UE_DEPRECATED (5.1, "Deprecated in favor of supporting multiple modulators per destination. Use 'UpdateModulators' instead.") 1 void UpdateModulator(const USoundModulatorBase *InModulator)
void UpdateModulators (const TSet< const USoundModulatorBase * > &InModulators)
void UpdateModulators (const TSet< TObjectPtr< USoundModulatorBase > > &InModulators)
void UpdateModulators (const TSet< USoundModulatorBase * > &InModulators)
Private Member Functions
void UpdateModulatorsInternal (TArray< TUniquePtr< Audio::IModulatorSettings > > &&ProxySettings)
Private Attributes
TSharedRef< FModulationDestinationData > DestinationData { MakeShared<FModulationDestinationData>() }
Detailed Description
Definition at line 160 of file SoundModulationDestination.h.
Constructor & Destructor Documentation
FModulationDestination() [1/3]
Audio::FModulationDestination::FModulationDestination () default
Referenced by FModulationDestination(), FModulationDestination(), operator=(), and operator=().
FModulationDestination() [2/3]
Audio::FModulationDestination::FModulationDestination (const FModulationDestination & InModulationDestination)
References FModulationDestination().
FModulationDestination() [3/3]
Audio::FModulationDestination::FModulationDestination (FModulationDestination && InModulationDestination)
References FModulationDestination().
Member Function Documentation
GetBuffer()
FORCEINLINE const FAlignedFloatBuffer & Audio::FModulationDestination::GetBuffer () const inline
Returns buffer of interpolated modulation values.
If not set to "IsBuffered" when initialized, returns an empty array.
Definition at line 235 of file SoundModulationDestination.h.
References DestinationData, and FORCEINLINE.
GetHasProcessed()
FORCEINLINE bool Audio::FModulationDestination::GetHasProcessed () const inline
Returns whether or not the destination has requested to process the control or not.
Definition at line 242 of file SoundModulationDestination.h.
References DestinationData, and FORCEINLINE.
GetValue()
FORCEINLINE float Audio::FModulationDestination::GetValue () const inline
Returns sample value last reported by modulator.
Returns value in unit space, unless 'ValueNormalized' option is set on initialization.
Definition at line 250 of file SoundModulationDestination.h.
References DestinationData, and FORCEINLINE.
Init() [1/2]
void Audio::FModulationDestination::Init (FDeviceId InDeviceId, bool bInIsBuffered = false, bool bInValueNormalized = false)
Initializes the modulation destination InDeviceId - DeviceId associated with modulation plugin instance bInIsBuffered - Whether or not to run destination in "buffered mode," which manages an internal buffer to smooth modulation value between process calls bInValueNormalized - Whether or not to keep the output value in normalized, unitless [0.0f, 1.0f] space.
Init() [2/2]
void Audio::FModulationDestination::Init (FDeviceId InDeviceId, FName InParameterName, bool bInIsBuffered = false, bool bInValueNormalized = false)
Initializes the modulation destination InDeviceId - DeviceId associated with modulation plugin instance InParameterName - Name of parameter used to mix/convert destination value to/from unit space bInIsBuffered - Whether or not to run destination in "buffered mode," which manages an internal buffer to smooth modulation value between process calls bInValueNormalized - Whether or not to keep the output value in normalized, unitless [0.0f, 1.0f] space.
IsActive()
bool Audio::FModulationDestination::IsActive () const
returns whether or not destination references an active modulator
operator=() [1/2]
FModulationDestination & Audio::FModulationDestination::operator= (const FModulationDestination & InModulationDestination)
References FModulationDestination().
operator=() [2/2]
FModulationDestination & Audio::FModulationDestination::operator= (FModulationDestination && InModulationDestination)
References FModulationDestination().
ProcessControl()
bool Audio::FModulationDestination::ProcessControl (float InValueUnitBase, int32 InNumSamples = 0)
UE_DEPRECATED()
Audio::FModulationDestination::UE_DEPRECATED (5. 1, "Deprecated in favor of supporting multiple modulators per destination. Use 'UpdateModulators' instead.") const
UpdateModulators() [1/3]
void Audio::FModulationDestination::UpdateModulators (const TSet< const USoundModulatorBase * > & InModulators)
References UpdateModulators().
UpdateModulators() [2/3]
void Audio::FModulationDestination::UpdateModulators (const TSet< TObjectPtr< USoundModulatorBase > > & InModulators)
References UpdateModulators().
Referenced by UpdateModulators(), UpdateModulators(), and UpdateModulators().
UpdateModulators() [3/3]
void Audio::FModulationDestination::UpdateModulators (const TSet< USoundModulatorBase * > & InModulators)
References UpdateModulators().
UpdateModulatorsInternal()
void Audio::FModulationDestination::UpdateModulatorsInternal (TArray< TUniquePtr< Audio::IModulatorSettings > > && ProxySettings) private
References UpdateModulatorsInternal().
Referenced by UpdateModulatorsInternal().
Field Documentation
DestinationData
TSharedRef<FModulationDestinationData> Audio::FModulationDestination::DestinationData { MakeShared<FModulationDestinationData>() } private
Definition at line 231 of file SoundModulationDestination.h.
Referenced by GetBuffer(), GetHasProcessed(), and GetValue().
The documentation for this struct was generated from the following file:
Runtime/Engine/Classes/Sound/SoundModulationDestination.h