Unreal Engine 5.6 C++ API: UE::Core::FVisualizerDebuggingState Struct Reference
UE::Core::FVisualizerDebuggingState Struct Reference
Global visualizer state manager that handles the complexities of natvis lookup rules for DLLs and LiveCoding.
#include "VisualizerDebuggingState.h"
Public Member Functions
FVisualizerDebuggingState ()
FVisualizerDebuggingState (const FVisualizerDebuggingState &)=delete
FVisualizerDebuggingState (FVisualizerDebuggingState &&)=delete
~FVisualizerDebuggingState ()
void operator= (const FVisualizerDebuggingState &)=delete
void operator= (FVisualizerDebuggingState &&)=delete
Static Public Member Functions
static EVisualizerDebuggingStateResult Assign (const FGuid &UniqueId, void *DebugPtr)
Assign a globally accessible debugging state ptr by name, potentially overwriting a previously assigned ptr.
Protected Member Functions
EVisualizerDebuggingStateResult AssignImpl (const FGuid &UniqueId, void *DebugPtr)
Implementation function for Assign.
void * Find (const FGuid &UniqueId) const
Attempt to locate the index of the specified unique ID.
Protected Attributes
const char * GuidString = nullptr
Single string containing all GUID strings ordered by their insertion order.
FVisualizerDebuggingStateImpl * PimplData = nullptr
Pimpl to avoid pulling in too many headers since this header is included everywhere.
void ** Ptrs = nullptr
Array of void* ptrs to the user-provided debugging state ptrs for each entry.
Detailed Description
Global visualizer state manager that handles the complexities of natvis lookup rules for DLLs and LiveCoding.
The singleton instance of this class is forward declared in CoreGlobals.h (GCoreDebuggingState), with additional symbols added to each DLL through UE_VISUALIZERS_HELPERS (GDebuggingState).
When a plugin or engine system needs to provide a globally accessible pointer to a natvis visualizer, that pointer can be added by calling FVisualizerDebuggingState::Assign using a globally unique ID that is used to find the pointer in the natvis. GUIDs may be generated using any readily-available GUID generator tool.
Pointers are located using an intrinsic call to strstr that finds the pointer's offset using a string match of the original GUID's lower-case, 32-character string representation of the form "c198d347ec1243ec833c423bd5fb6084". The offset of the address of the match divided by 32 gives the entry index from which the actual debug ptr can be retrieved.
An example visualizer syntax is included below. It is recommended that most natvis files utilizing this method would include an global intrinsic function at the top for quick access:
<Intrinsic Name="GetDebugState" Expression="GDebuggingState->Ptrs[(strstr(GDebuggingState->GuidString, GuidString) - GDebuggingState->GuidString)/32]"> <Parameter Name="GuidString" Type="char*"> </Intrinsic>
// C++: struct FMyGlobalState { static FMyGlobalState* GetSingleton(); TArray<FString> TypeNames; }; struct FMyStruct { int32 TypeNameIndex; };
// Register the global state FGuid DebugVisualizerID(0x1bdc1747, 0x6b924697, 0xbd8fccc8, 0xb26b4f79) EVisualizerDebuggingStateResult Result = FVisualizerDebuggingState::Assign(DebugVisualizerID, FMyGlobalState::GetSingleton());
// .natvis:
<Type Name="FMyStruct">
<Intrinsic Name="GetGlobalState" Expression="((FMyGlobalState*)GetDebugState(&quot;1bdc17476b924697bd8fccc8b26b4f79&quot;))""></Intrinsic>
<DisplayString>Type={ GetGlobalState()->TypeNames[TypeNameIndex] }</DisplayString> </Type>
Definition at line 74 of file VisualizerDebuggingState.h.
Constructor & Destructor Documentation
FVisualizerDebuggingState() [1/3]
UE::Core::FVisualizerDebuggingState::FVisualizerDebuggingState ()
Referenced by FVisualizerDebuggingState(), FVisualizerDebuggingState(), operator=(), and operator=().
FVisualizerDebuggingState() [2/3]
UE::Core::FVisualizerDebuggingState::FVisualizerDebuggingState (const FVisualizerDebuggingState &) delete
References FVisualizerDebuggingState().
FVisualizerDebuggingState() [3/3]
UE::Core::FVisualizerDebuggingState::FVisualizerDebuggingState (FVisualizerDebuggingState &&) delete
References FVisualizerDebuggingState().
~FVisualizerDebuggingState()
UE::Core::FVisualizerDebuggingState::~FVisualizerDebuggingState ()
References UE::Core::FeatureDisabled.
Member Function Documentation
Assign()
EVisualizerDebuggingStateResult UE::Core::FVisualizerDebuggingState::Assign (const FGuid & UniqueId, void * DebugPtr) static nodiscard
Assign a globally accessible debugging state ptr by name, potentially overwriting a previously assigned ptr.
Parameters
UniqueId A guid that uniquely identifies this debug ptr. This should be the same as is used to access the ptr inside a natvis file.
DebugPtr The pointer that needs to be accessible from natvis
Returns
EVisualizerDebuggingStateResult::Success if the operation completed successfully, otherwise an error code
AssignImpl()
EVisualizerDebuggingStateResult UE::Core::FVisualizerDebuggingState::AssignImpl (const FGuid & UniqueId, void * DebugPtr) protected
Implementation function for Assign.
Find()
void * UE::Core::FVisualizerDebuggingState::Find (const FGuid & UniqueId) const protected
Attempt to locate the index of the specified unique ID.
operator=() [1/2]
void UE::Core::FVisualizerDebuggingState::operator= (const FVisualizerDebuggingState &) delete
References FVisualizerDebuggingState().
operator=() [2/2]
void UE::Core::FVisualizerDebuggingState::operator= (FVisualizerDebuggingState &&) delete
References FVisualizerDebuggingState().
Field Documentation
GuidString
const char* UE::Core::FVisualizerDebuggingState::GuidString = nullptr protected
Single string containing all GUID strings ordered by their insertion order.
The single string is designed to support finding a string offset using a single strstr instrinsic call, and dividing the result by 32. This string exists for easy referencing inside natvis files; it points to PimplData->OrderedGuidString. Example layout:
OrderedGuidString: "d9ad42709d2c4bc8a2f8f925e1617b288456cfc3222f4833a8afa45a6ed73b5a9873a9fedd8441d49ef6b3258e8a6c60#" Ptrs: [Ptr1 ,Ptr2 ,Ptr3]
Definition at line 134 of file VisualizerDebuggingState.h.
PimplData
FVisualizerDebuggingStateImpl* UE::Core::FVisualizerDebuggingState::PimplData = nullptr protected
Pimpl to avoid pulling in too many headers since this header is included everywhere.
Definition at line 143 of file VisualizerDebuggingState.h.
Ptrs
void** UE::Core::FVisualizerDebuggingState::Ptrs = nullptr protected
Array of void* ptrs to the user-provided debugging state ptrs for each entry.
Points directly to PimplData->DebugPtrs.GetData() for quick referencing inside natvis without needing any other symbols or casting.
Definition at line 140 of file VisualizerDebuggingState.h.
The documentation for this struct was generated from the following file:
Runtime/Core/Public/Modules/VisualizerDebuggingState.h