Unreal Engine 5.6 C++ API: FCompoundChangeInput Struct Reference
FCompoundChangeInput Struct Reference
#include "Change.h"
Public Member Functions
FCompoundChangeInput ()
FCompoundChangeInput (FCompoundChangeInput &&RHS)
Data Fields
TArray< TUniquePtr< FChange > > Subchanges
Ordered list of changes that comprise everything needed to describe this change.
Private Member Functions
FCompoundChangeInput (const FCompoundChangeInput &)=delete
FCompoundChangeInput & operator= (const FCompoundChangeInput &)=delete
Detailed Description
Definition at line 142 of file Change.h.
Constructor & Destructor Documentation
FCompoundChangeInput() [1/3]
FCompoundChangeInput::FCompoundChangeInput () inline
Definition at line 144 of file Change.h.
Referenced by FCompoundChangeInput(), FCompoundChangeInput(), and operator=().
FCompoundChangeInput() [2/3]
FCompoundChangeInput::FCompoundChangeInput (FCompoundChangeInput && RHS) inline explicit
Definition at line 148 of file Change.h.
References FCompoundChangeInput(), MoveTemp(), and Subchanges.
FCompoundChangeInput() [3/3]
FCompoundChangeInput::FCompoundChangeInput (const FCompoundChangeInput &) private delete
References FCompoundChangeInput().
Member Function Documentation
operator=()
FCompoundChangeInput & FCompoundChangeInput::operator= (const FCompoundChangeInput &) private delete
References FCompoundChangeInput().
Field Documentation
Subchanges
TArray<TUniquePtr<FChange> > FCompoundChangeInput::Subchanges
Ordered list of changes that comprise everything needed to describe this change.
Definition at line 154 of file Change.h.
Referenced by FCompoundChangeInput().
The documentation for this struct was generated from the following file:
Runtime/Core/Public/Misc/Change.h