Unreal Engine 5.6 C++ API: FWindowsPlatformProperties< HAS_EDITOR_DATA, IS_DEDICATED_SERVER, IS_CLIENT_ONLY > Struct Template Reference
FWindowsPlatformProperties< HAS_EDITOR_DATA, IS_DEDICATED_SERVER, IS_CLIENT_ONLY > Struct Template Reference
Implements Windows platform properties.
#include "WindowsPlatformProperties.h"
Static Public Member Functions
static constexpr FORCEINLINE int GetMaxSupportedVirtualMemoryAlignment ()
static constexpr FORCEINLINE int64 GetMemoryMappingAlignment ()
static constexpr FORCEINLINE const TCHAR * GetRuntimeSettingsClassName ()
static constexpr FORCEINLINE float GetVariantPriority ()
static constexpr FORCEINLINE bool HasEditorOnlyData ()
static constexpr FORCEINLINE bool HasFixedResolution ()
static constexpr FORCEINLINE bool HasSecurePackageFormat ()
static constexpr FORCEINLINE const char * IniPlatformName ()
static constexpr FORCEINLINE bool IsClientOnly ()
static constexpr FORCEINLINE bool IsGameOnly ()
static constexpr FORCEINLINE bool IsServerOnly ()
static constexpr FORCEINLINE const char * PlatformName ()
static constexpr FORCEINLINE bool RequiresCookedData ()
static constexpr FORCEINLINE bool SupportsAudioStreaming ()
static constexpr FORCEINLINE bool SupportsGrayscaleSRGB ()
static constexpr FORCEINLINE bool SupportsMemoryMappedFiles ()
static constexpr FORCEINLINE bool SupportsMeshLODStreaming ()
static constexpr FORCEINLINE bool SupportsMultipleGameInstances ()
static constexpr FORCEINLINE bool SupportsQuit ()
static constexpr FORCEINLINE bool SupportsRayTracing ()
static constexpr FORCEINLINE bool SupportsWindowedMode ()
Static Public Member Functions inherited from FGenericPlatformProperties
static constexpr FORCEINLINE bool AllowsCallStackDumpDuringAssert ()
static constexpr FORCEINLINE bool AllowsFramerateSmoothing ()
Whether this platform wants to allow framerate smoothing or not.
static constexpr FORCEINLINE int GetMaxSupportedVirtualMemoryAlignment ()
static constexpr FORCEINLINE int64 GetMemoryMappingAlignment ()
static constexpr FORCEINLINE const char * GetPhysicsFormat ()
Gets the platform's physics format.
static constexpr FORCEINLINE const char * GetZlibReplacementFormat ()
static constexpr FORCEINLINE bool HasEditorOnlyData ()
Gets whether this platform has Editor-only data.
static constexpr FORCEINLINE bool HasFixedResolution ()
Gets whether user settings should override the resolution or not.
static constexpr FORCEINLINE bool HasSecurePackageFormat ()
Checks whether shipped data on this platform is secure, and doesn't require extra encryption/signing to protect it.
static const char * IniPlatformName ()
Gets the name of this platform when loading INI files.
static constexpr FORCEINLINE bool IsClientOnly ()
Gets whether this is a client only (no capability to run the game without connecting to a server) platform.
static constexpr FORCEINLINE bool IsGameOnly ()
Gets whether this is a game only platform.
static constexpr FORCEINLINE bool IsLittleEndian ()
Gets whether this is a Little Endian platform.
static constexpr FORCEINLINE bool IsMonolithicBuild ()
Gets whether this was a monolithic build or not.
static constexpr FORCEINLINE bool IsProgram ()
Gets whether this was a program or not.
static constexpr FORCEINLINE bool IsServerOnly ()
Gets whether this is a server only platform.
static FORCEINLINE const char * PlatformName ()
Gets the name of this platform.
static FORCEINLINE const char * PlatformVariantName ()
Get the name of the hardware variant of the current platform.
static constexpr FORCEINLINE bool RequiresCookedData ()
Checks whether this platform requires cooked data.
static constexpr FORCEINLINE bool RequiresOriginalReleaseVersionForPatch ()
static constexpr FORCEINLINE bool RequiresUserCredentials ()
Checks whether this platform requires user credentials (typically server platforms).
static constexpr FORCEINLINE bool SupportsAudioStreaming ()
Whether this platform supports streaming audio.
static constexpr FORCEINLINE bool SupportsAutoSDK ()
Returns true if platform supports the AutoSDK system.
static FORCEINLINE bool SupportsBuildTarget (EBuildTargetType TargetType)
Checks whether the specified build target is supported.
static constexpr FORCEINLINE bool SupportsDistanceFieldAO ()
static constexpr FORCEINLINE bool SupportsDistanceFieldShadows ()
static constexpr FORCEINLINE bool SupportsGrayscaleSRGB ()
Gets whether this platform supports gray scale sRGB texture formats.
static constexpr FORCEINLINE bool SupportsHardwareLZDecompression ()
static constexpr FORCEINLINE bool SupportsHighQualityLightmaps ()
static constexpr FORCEINLINE bool SupportsLowQualityLightmaps ()
static constexpr FORCEINLINE bool SupportsLumenGI ()
static constexpr FORCEINLINE bool SupportsMemoryMappedAnimation ()
static constexpr FORCEINLINE bool SupportsMemoryMappedAudio ()
static constexpr FORCEINLINE bool SupportsMemoryMappedFiles ()
static constexpr FORCEINLINE bool SupportsMeshLODStreaming ()
static constexpr FORCEINLINE bool SupportsMinimize ()
static constexpr FORCEINLINE bool SupportsMultipleGameInstances ()
Checks whether this platforms supports running multiple game instances on a single device.
static constexpr FORCEINLINE bool SupportsQuit ()
static constexpr FORCEINLINE bool SupportsRayTracing ()
static constexpr FORCEINLINE bool SupportsTextureStreaming ()
static constexpr FORCEINLINE bool SupportsWindowedMode ()
Gets whether this platform supports windowed mode rendering.
Detailed Description
template<bool HAS_EDITOR_DATA, bool IS_DEDICATED_SERVER, bool IS_CLIENT_ONLY>
struct FWindowsPlatformProperties< HAS_EDITOR_DATA, IS_DEDICATED_SERVER, IS_CLIENT_ONLY >
Implements Windows platform properties.
Definition at line 13 of file WindowsPlatformProperties.h.
Member Function Documentation
GetMaxSupportedVirtualMemoryAlignment()
template<bool HAS_EDITOR_DATA, bool IS_DEDICATED_SERVER, bool IS_CLIENT_ONLY> constexpr FORCEINLINE int FWindowsPlatformProperties< HAS_EDITOR_DATA, IS_DEDICATED_SERVER, IS_CLIENT_ONLY >::GetMaxSupportedVirtualMemoryAlignment () inline static constexpr
Definition at line 146 of file WindowsPlatformProperties.h.
References FORCEINLINE.
GetMemoryMappingAlignment()
template<bool HAS_EDITOR_DATA, bool IS_DEDICATED_SERVER, bool IS_CLIENT_ONLY> constexpr FORCEINLINE int64 FWindowsPlatformProperties< HAS_EDITOR_DATA, IS_DEDICATED_SERVER, IS_CLIENT_ONLY >::GetMemoryMappingAlignment () inline static constexpr
Definition at line 141 of file WindowsPlatformProperties.h.
References FORCEINLINE.
GetRuntimeSettingsClassName()
template<bool HAS_EDITOR_DATA, bool IS_DEDICATED_SERVER, bool IS_CLIENT_ONLY> constexpr FORCEINLINE const TCHAR * FWindowsPlatformProperties< HAS_EDITOR_DATA, IS_DEDICATED_SERVER, IS_CLIENT_ONLY >::GetRuntimeSettingsClassName () inline static constexpr
Definition at line 26 of file WindowsPlatformProperties.h.
References FORCEINLINE, and TEXT.
GetVariantPriority()
template<bool HAS_EDITOR_DATA, bool IS_DEDICATED_SERVER, bool IS_CLIENT_ONLY> constexpr FORCEINLINE float FWindowsPlatformProperties< HAS_EDITOR_DATA, IS_DEDICATED_SERVER, IS_CLIENT_ONLY >::GetVariantPriority () inline static constexpr
Definition at line 121 of file WindowsPlatformProperties.h.
References FORCEINLINE.
HasEditorOnlyData()
template<bool HAS_EDITOR_DATA, bool IS_DEDICATED_SERVER, bool IS_CLIENT_ONLY> constexpr FORCEINLINE bool FWindowsPlatformProperties< HAS_EDITOR_DATA, IS_DEDICATED_SERVER, IS_CLIENT_ONLY >::HasEditorOnlyData () inline static constexpr
Definition at line 16 of file WindowsPlatformProperties.h.
References FORCEINLINE.
Referenced by SupportsMeshLODStreaming().
HasFixedResolution()
template<bool HAS_EDITOR_DATA, bool IS_DEDICATED_SERVER, bool IS_CLIENT_ONLY> constexpr FORCEINLINE bool FWindowsPlatformProperties< HAS_EDITOR_DATA, IS_DEDICATED_SERVER, IS_CLIENT_ONLY >::HasFixedResolution () inline static constexpr
Definition at line 111 of file WindowsPlatformProperties.h.
References FORCEINLINE.
HasSecurePackageFormat()
template<bool HAS_EDITOR_DATA, bool IS_DEDICATED_SERVER, bool IS_CLIENT_ONLY> constexpr FORCEINLINE bool FWindowsPlatformProperties< HAS_EDITOR_DATA, IS_DEDICATED_SERVER, IS_CLIENT_ONLY >::HasSecurePackageFormat () inline static constexpr
Definition at line 71 of file WindowsPlatformProperties.h.
References FORCEINLINE.
IniPlatformName()
template<bool HAS_EDITOR_DATA, bool IS_DEDICATED_SERVER, bool IS_CLIENT_ONLY> constexpr FORCEINLINE const char * FWindowsPlatformProperties< HAS_EDITOR_DATA, IS_DEDICATED_SERVER, IS_CLIENT_ONLY >::IniPlatformName () inline static constexpr
Definition at line 21 of file WindowsPlatformProperties.h.
References FORCEINLINE.
IsClientOnly()
template<bool HAS_EDITOR_DATA, bool IS_DEDICATED_SERVER, bool IS_CLIENT_ONLY> constexpr FORCEINLINE bool FWindowsPlatformProperties< HAS_EDITOR_DATA, IS_DEDICATED_SERVER, IS_CLIENT_ONLY >::IsClientOnly () inline static constexpr
Definition at line 41 of file WindowsPlatformProperties.h.
References FORCEINLINE.
IsGameOnly()
template<bool HAS_EDITOR_DATA, bool IS_DEDICATED_SERVER, bool IS_CLIENT_ONLY> constexpr FORCEINLINE bool FWindowsPlatformProperties< HAS_EDITOR_DATA, IS_DEDICATED_SERVER, IS_CLIENT_ONLY >::IsGameOnly () inline static constexpr
Definition at line 31 of file WindowsPlatformProperties.h.
References FORCEINLINE, and UE_GAME.
IsServerOnly()
template<bool HAS_EDITOR_DATA, bool IS_DEDICATED_SERVER, bool IS_CLIENT_ONLY> constexpr FORCEINLINE bool FWindowsPlatformProperties< HAS_EDITOR_DATA, IS_DEDICATED_SERVER, IS_CLIENT_ONLY >::IsServerOnly () inline static constexpr
Definition at line 36 of file WindowsPlatformProperties.h.
References FORCEINLINE.
Referenced by SupportsAudioStreaming(), and SupportsMeshLODStreaming().
PlatformName()
template<bool HAS_EDITOR_DATA, bool IS_DEDICATED_SERVER, bool IS_CLIENT_ONLY> constexpr FORCEINLINE const char * FWindowsPlatformProperties< HAS_EDITOR_DATA, IS_DEDICATED_SERVER, IS_CLIENT_ONLY >::PlatformName () inline static constexpr
Definition at line 46 of file WindowsPlatformProperties.h.
References FORCEINLINE.
RequiresCookedData()
template<bool HAS_EDITOR_DATA, bool IS_DEDICATED_SERVER, bool IS_CLIENT_ONLY> constexpr FORCEINLINE bool FWindowsPlatformProperties< HAS_EDITOR_DATA, IS_DEDICATED_SERVER, IS_CLIENT_ONLY >::RequiresCookedData () inline static constexpr
Definition at line 66 of file WindowsPlatformProperties.h.
References FORCEINLINE.
SupportsAudioStreaming()
template<bool HAS_EDITOR_DATA, bool IS_DEDICATED_SERVER, bool IS_CLIENT_ONLY> constexpr FORCEINLINE bool FWindowsPlatformProperties< HAS_EDITOR_DATA, IS_DEDICATED_SERVER, IS_CLIENT_ONLY >::SupportsAudioStreaming () inline static constexpr
Definition at line 81 of file WindowsPlatformProperties.h.
References FORCEINLINE, and IsServerOnly().
SupportsGrayscaleSRGB()
template<bool HAS_EDITOR_DATA, bool IS_DEDICATED_SERVER, bool IS_CLIENT_ONLY> constexpr FORCEINLINE bool FWindowsPlatformProperties< HAS_EDITOR_DATA, IS_DEDICATED_SERVER, IS_CLIENT_ONLY >::SupportsGrayscaleSRGB () inline static constexpr
Definition at line 96 of file WindowsPlatformProperties.h.
References FORCEINLINE.
SupportsMemoryMappedFiles()
template<bool HAS_EDITOR_DATA, bool IS_DEDICATED_SERVER, bool IS_CLIENT_ONLY> constexpr FORCEINLINE bool FWindowsPlatformProperties< HAS_EDITOR_DATA, IS_DEDICATED_SERVER, IS_CLIENT_ONLY >::SupportsMemoryMappedFiles () inline static constexpr
Definition at line 76 of file WindowsPlatformProperties.h.
References FORCEINLINE.
SupportsMeshLODStreaming()
template<bool HAS_EDITOR_DATA, bool IS_DEDICATED_SERVER, bool IS_CLIENT_ONLY> constexpr FORCEINLINE bool FWindowsPlatformProperties< HAS_EDITOR_DATA, IS_DEDICATED_SERVER, IS_CLIENT_ONLY >::SupportsMeshLODStreaming () inline static constexpr
Definition at line 86 of file WindowsPlatformProperties.h.
References FORCEINLINE, HasEditorOnlyData(), and IsServerOnly().
SupportsMultipleGameInstances()
template<bool HAS_EDITOR_DATA, bool IS_DEDICATED_SERVER, bool IS_CLIENT_ONLY> constexpr FORCEINLINE bool FWindowsPlatformProperties< HAS_EDITOR_DATA, IS_DEDICATED_SERVER, IS_CLIENT_ONLY >::SupportsMultipleGameInstances () inline static constexpr
Definition at line 101 of file WindowsPlatformProperties.h.
References FORCEINLINE.
SupportsQuit()
template<bool HAS_EDITOR_DATA, bool IS_DEDICATED_SERVER, bool IS_CLIENT_ONLY> constexpr FORCEINLINE bool FWindowsPlatformProperties< HAS_EDITOR_DATA, IS_DEDICATED_SERVER, IS_CLIENT_ONLY >::SupportsQuit () inline static constexpr
Definition at line 116 of file WindowsPlatformProperties.h.
References FORCEINLINE.
SupportsRayTracing()
template<bool HAS_EDITOR_DATA, bool IS_DEDICATED_SERVER, bool IS_CLIENT_ONLY> constexpr FORCEINLINE bool FWindowsPlatformProperties< HAS_EDITOR_DATA, IS_DEDICATED_SERVER, IS_CLIENT_ONLY >::SupportsRayTracing () inline static constexpr
Definition at line 91 of file WindowsPlatformProperties.h.
References FORCEINLINE.
SupportsWindowedMode()
template<bool HAS_EDITOR_DATA, bool IS_DEDICATED_SERVER, bool IS_CLIENT_ONLY> constexpr FORCEINLINE bool FWindowsPlatformProperties< HAS_EDITOR_DATA, IS_DEDICATED_SERVER, IS_CLIENT_ONLY >::SupportsWindowedMode () inline static constexpr
Definition at line 106 of file WindowsPlatformProperties.h.
References FORCEINLINE.
The documentation for this struct was generated from the following file:
Runtime/Core/Public/Windows/WindowsPlatformProperties.h