Unreal Engine 5.6 C++ API: FAppleProResEncoderOptions Struct Reference
FAppleProResEncoderOptions Struct Reference
#include "AppleProResEncoder.h"
Public Member Functions
PRAGMA_DISABLE_DEPRECATION_WARNINGS FAppleProResEncoderOptions ()
FAppleProResEncoderOptions (const FAppleProResEncoderOptions &)=default
FAppleProResEncoderOptions (FAppleProResEncoderOptions &&)=default
FAppleProResEncoderOptions (FAppleProResEncoderOptions &)=default
~FAppleProResEncoderOptions ()=default
FAppleProResEncoderOptions & operator= (const FAppleProResEncoderOptions &)=default
FAppleProResEncoderOptions & operator= (FAppleProResEncoderOptions &&)=default
UE_DEPRECATED (5.6, "The encoder currently always assumes Rec 709 input, and never used this parameter.") bool bConvertToSrgb
Whether the data should be converted to sRGB before being sent to the encoder.
Data Fields
uint32 AudioChannelCount
The number of audio channels in the encoding data.
uint32 AudioSampleRate
The sample rate of the incoming audio data.
bool bDropFrameTimecode
If true, timecode track will use drop frame notation for the 29.97 frame rate.
bool bIncludeAudio
If false, then audio tracks will not be written and calls to WriteAudioSample will be ignored.
bool bWriteAlpha
If true, attempts to write the alpha channel from the incoming pixel data.
EAppleProResEncoderCodec Codec
Which ProRes codec should we use?
EAppleProResEncoderColorPrimaries ColorPrimaries
Which color primaries do we use?
int32 FrameNumberOffset
The number of frames to offset the Timecode track by.
FFrameRate FrameRate
Frame Rate of the output video.
uint32 Height
The height of the video file.
int32 MaxNumberOfEncodingThreads
Maximum number of threads to use for encoding.
PRAGMA_ENABLE_DEPRECATION_WARNINGS FString OutputFilename
The absolute path on disk to try and save the video file to.
EAppleProResEncoderScanMode ScanMode
Which scan mode do we use?
uint32 Width
The width of the video file.
Detailed Description
Definition at line 57 of file AppleProResEncoder.h.
Constructor & Destructor Documentation
FAppleProResEncoderOptions() [1/4]
PRAGMA_DISABLE_DEPRECATION_WARNINGS FAppleProResEncoderOptions::FAppleProResEncoderOptions () inline
Definition at line 61 of file AppleProResEncoder.h.
References AudioChannelCount, AudioSampleRate, bDropFrameTimecode, bIncludeAudio, bWriteAlpha, Codec, ColorPrimaries, FrameNumberOffset, FrameRate, Height, MaxNumberOfEncodingThreads, OutputFilename, ScanMode, and Width.
Referenced by FAppleProResEncoderOptions(), FAppleProResEncoderOptions(), FAppleProResEncoderOptions(), operator=(), and operator=().
FAppleProResEncoderOptions() [2/4]
FAppleProResEncoderOptions::FAppleProResEncoderOptions (FAppleProResEncoderOptions &) default
References FAppleProResEncoderOptions().
~FAppleProResEncoderOptions()
FAppleProResEncoderOptions::~FAppleProResEncoderOptions () default
FAppleProResEncoderOptions() [3/4]
FAppleProResEncoderOptions::FAppleProResEncoderOptions (const FAppleProResEncoderOptions &) default
References FAppleProResEncoderOptions().
FAppleProResEncoderOptions() [4/4]
FAppleProResEncoderOptions::FAppleProResEncoderOptions (FAppleProResEncoderOptions &&) default
References FAppleProResEncoderOptions().
Member Function Documentation
operator=() [1/2]
FAppleProResEncoderOptions & FAppleProResEncoderOptions::operator= (const FAppleProResEncoderOptions &) default
References FAppleProResEncoderOptions().
operator=() [2/2]
FAppleProResEncoderOptions & FAppleProResEncoderOptions::operator= (FAppleProResEncoderOptions &&) default
References FAppleProResEncoderOptions(), and PRAGMA_ENABLE_DEPRECATION_WARNINGS.
UE_DEPRECATED()
FAppleProResEncoderOptions::UE_DEPRECATED (5. 6, "The encoder currently always assumes Rec 709 input, and never used this parameter.")
Whether the data should be converted to sRGB before being sent to the encoder.
Should not be used when OCIO is active.
References bool.
Field Documentation
AudioChannelCount
uint32 FAppleProResEncoderOptions::AudioChannelCount
The number of audio channels in the encoding data.
Only tested with 2.
Definition at line 131 of file AppleProResEncoder.h.
Referenced by FAppleProResEncoderOptions().
AudioSampleRate
uint32 FAppleProResEncoderOptions::AudioSampleRate
The sample rate of the incoming audio data.
Only tested with 48'000.
Definition at line 128 of file AppleProResEncoder.h.
Referenced by FAppleProResEncoderOptions().
bDropFrameTimecode
bool FAppleProResEncoderOptions::bDropFrameTimecode
If true, timecode track will use drop frame notation for the 29.97 frame rate.
Definition at line 119 of file AppleProResEncoder.h.
Referenced by FAppleProResEncoderOptions().
bIncludeAudio
bool FAppleProResEncoderOptions::bIncludeAudio
If false, then audio tracks will not be written and calls to WriteAudioSample will be ignored.
Definition at line 125 of file AppleProResEncoder.h.
Referenced by FAppleProResEncoderOptions().
bWriteAlpha
bool FAppleProResEncoderOptions::bWriteAlpha
If true, attempts to write the alpha channel from the incoming pixel data.
Increases encoding time. Only works on some Codecs.
Definition at line 116 of file AppleProResEncoder.h.
Referenced by FAppleProResEncoderOptions().
Codec
EAppleProResEncoderCodec FAppleProResEncoderOptions::Codec
Which ProRes codec should we use?
Not all support alpha channels.
Definition at line 100 of file AppleProResEncoder.h.
Referenced by FAppleProResEncoderOptions().
ColorPrimaries
EAppleProResEncoderColorPrimaries FAppleProResEncoderOptions::ColorPrimaries
Which color primaries do we use?
Only Rec 709 is well tested right now.
Definition at line 103 of file AppleProResEncoder.h.
Referenced by FAppleProResEncoderOptions().
FrameNumberOffset
int32 FAppleProResEncoderOptions::FrameNumberOffset
The number of frames to offset the Timecode track by.
Definition at line 122 of file AppleProResEncoder.h.
Referenced by FAppleProResEncoderOptions().
FrameRate
FFrameRate FAppleProResEncoderOptions::FrameRate
Frame Rate of the output video.
Definition at line 97 of file AppleProResEncoder.h.
Referenced by FAppleProResEncoderOptions().
Height
uint32 FAppleProResEncoderOptions::Height
The height of the video file.
Definition at line 94 of file AppleProResEncoder.h.
Referenced by FAppleProResEncoderOptions().
MaxNumberOfEncodingThreads
int32 FAppleProResEncoderOptions::MaxNumberOfEncodingThreads
Maximum number of threads to use for encoding.
Set to 0 for auto-determine based on hardware.
Definition at line 113 of file AppleProResEncoder.h.
Referenced by FAppleProResEncoderOptions().
OutputFilename
PRAGMA_ENABLE_DEPRECATION_WARNINGS FString FAppleProResEncoderOptions::OutputFilename
The absolute path on disk to try and save the video file to.
Definition at line 88 of file AppleProResEncoder.h.
Referenced by FAppleProResEncoderOptions().
ScanMode
EAppleProResEncoderScanMode FAppleProResEncoderOptions::ScanMode
Which scan mode do we use?
Only Progressive is tested right now.
Definition at line 110 of file AppleProResEncoder.h.
Referenced by FAppleProResEncoderOptions().
Width
uint32 FAppleProResEncoderOptions::Width
The width of the video file.
Definition at line 91 of file AppleProResEncoder.h.
Referenced by FAppleProResEncoderOptions().
The documentation for this struct was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Media/AppleProResMedia/Source/AppleProResMedia/Public/AppleProResEncoder/AppleProResEncoder.h