Unreal Engine 5.6 C++ API: FDesiredLODLevel Struct Reference
FDesiredLODLevel Struct Reference
#include "PrimitiveSceneProxy.h"
Public Types
enum class EType : uint8 { First , Fixed }
Public Member Functions
FDesiredLODLevel (uint8 InLOD, EType InType)
bool IsFirst () const
bool IsFixed () const
Static Public Member Functions
static FDesiredLODLevel CreateFirst (uint8 LOD)
static FDesiredLODLevel CreateFixed (uint8 LOD)
Data Fields
uint8 LOD = 0
EType Type = EType::First
Detailed Description
Definition at line 65 of file PrimitiveSceneProxy.h.
Member Enumeration Documentation
EType
enum class FDesiredLODLevel::EType : uint8 strong
Enumerator
First
Fixed
Definition at line 67 of file PrimitiveSceneProxy.h.
Constructor & Destructor Documentation
FDesiredLODLevel()
FDesiredLODLevel::FDesiredLODLevel (uint8 InLOD, EType InType) inline
Definition at line 86 of file PrimitiveSceneProxy.h.
References LOD, and Type.
Referenced by CreateFirst(), and CreateFixed().
Member Function Documentation
CreateFirst()
FDesiredLODLevel FDesiredLODLevel::CreateFirst (uint8 LOD) inline static
Definition at line 81 of file PrimitiveSceneProxy.h.
References FDesiredLODLevel(), First, and LOD.
Referenced by FPrimitiveSceneProxy::GetDesiredLODLevel_RenderThread(), and FStaticMeshSceneProxy::GetDesiredLODLevel_RenderThread().
CreateFixed()
FDesiredLODLevel FDesiredLODLevel::CreateFixed (uint8 LOD) inline static
Definition at line 76 of file PrimitiveSceneProxy.h.
References FDesiredLODLevel(), Fixed, and LOD.
IsFirst()
bool FDesiredLODLevel::IsFirst () const inline
Definition at line 92 of file PrimitiveSceneProxy.h.
References First, and Type.
IsFixed()
bool FDesiredLODLevel::IsFixed () const inline
Definition at line 91 of file PrimitiveSceneProxy.h.
References Fixed, and Type.
Field Documentation
LOD
uint8 FDesiredLODLevel::LOD = 0
Definition at line 94 of file PrimitiveSceneProxy.h.
Referenced by FDesiredLODLevel(), CreateFirst(), and CreateFixed().
Type
EType FDesiredLODLevel::Type = EType::First
Definition at line 95 of file PrimitiveSceneProxy.h.
Referenced by FDesiredLODLevel(), IsFirst(), and IsFixed().
The documentation for this struct was generated from the following file:
Runtime/Engine/Public/PrimitiveSceneProxy.h