Unreal Engine 5.6 C++ API: TPersistentObjectPtr< TObjectID > Struct Template Reference
TPersistentObjectPtr< TObjectID > Struct Template Reference
TPersistentObjectPtr is a template base class for FLazyObjectPtr and FSoftObjectPtr.
#include "PersistentObjectPtr.h"
Public Types
using ElementType = TObjectID
Public Member Functions
FORCEINLINE TPersistentObjectPtr ()
Default constructor, will be null.
FORCEINLINE TPersistentObjectPtr (const TObjectID &InObjectID)
Construct from a unique object identifier.
FORCEINLINE UObject * Get () const
Dereference the pointer, which may cause it to become valid again.
FORCEINLINE UObject * Get (bool bEvenIfPendingKill) const
Dereference the lazy pointer, which may cause it to become valid again.
FORCEINLINE TObjectID & GetUniqueID ()
Non-const version of the above.
FORCEINLINE const TObjectID & GetUniqueID () const
Gets the unique object identifier associated with this lazy pointer.
FORCEINLINE bool IsNull () const
Test if this can never point to a live UObject.
FORCEINLINE bool IsPending () const
Test if this does not point to a live UObject, but may in the future.
FORCEINLINE bool IsStale () const
Slightly different than !IsValid(), returns true if this used to point to a UObject, but doesn't any more and has not been assigned or reset in the mean time.
FORCEINLINE bool IsValid () const
Test if this points to a live UObject.
FORCEINLINE bool operator!= (const TPersistentObjectPtr &Rhs) const
Compare pointers for inequality.
FORCEINLINE bool operator!= (TYPE_OF_NULLPTR) const
FORCEINLINE UObject & operator* () const
Dereference the pointer.
FORCEINLINE UObject * operator-> () const
Dereference the pointer.
FORCEINLINE void operator= (const FWeakObjectPtr &Other)
Copy from an existing weak pointer, reserve IDs if required.
FORCEINLINE void operator= (const TObjectID &InObjectID)
Copy from a unique object identifier.
FORCEINLINE void operator= (const UObject *Object)
void operator= (FObjectPtr Object)
Copy from an object pointer.
template<typename T>
FORCEINLINE void operator= (TObjectPtr< T > Object)
FORCEINLINE bool operator== (const TPersistentObjectPtr &Rhs) const
Compare pointers for equality.
FORCEINLINE bool operator== (TYPE_OF_NULLPTR) const
FORCEINLINE void Reset ()
Reset the lazy pointer back to the null state.
FORCEINLINE void ResetWeakPtr ()
Resets the weak ptr only, call this when ObjectId may change.
Private Member Functions
bool CanCacheObjectPointer (FObjectPtr Ptr) const
Private Attributes
TObjectID ObjectID
Guid for the object this pointer points to or will point to.
FWeakObjectPtr WeakPtr
Once the object has been noticed to be loaded, this is set to the object weak pointer.
Friends
FORCEINLINE friend uint32 GetTypeHash (const TPersistentObjectPtr &Ptr)
Hash function.
FORCEINLINE friend bool operator!= (TYPE_OF_NULLPTR, const TPersistentObjectPtr &Rhs)
FORCEINLINE friend bool operator== (TYPE_OF_NULLPTR, const TPersistentObjectPtr &Rhs)
Detailed Description
template<class TObjectID>
struct TPersistentObjectPtr< TObjectID >
TPersistentObjectPtr is a template base class for FLazyObjectPtr and FSoftObjectPtr.
Definition at line 18 of file PersistentObjectPtr.h.
Member Typedef Documentation
ElementType
template<class TObjectID> using TPersistentObjectPtr< TObjectID >::ElementType = TObjectID
Definition at line 20 of file PersistentObjectPtr.h.
Constructor & Destructor Documentation
TPersistentObjectPtr() [1/2]
template<class TObjectID> FORCEINLINE TPersistentObjectPtr< TObjectID >::TPersistentObjectPtr () inline
Default constructor, will be null.
Definition at line 23 of file PersistentObjectPtr.h.
TPersistentObjectPtr() [2/2]
template<class TObjectID> FORCEINLINE TPersistentObjectPtr< TObjectID >::TPersistentObjectPtr (const TObjectID & InObjectID) inline explicit
Construct from a unique object identifier.
Definition at line 42 of file PersistentObjectPtr.h.
Member Function Documentation
CanCacheObjectPointer()
template<class TObjectID> bool TPersistentObjectPtr< TObjectID >::CanCacheObjectPointer (FObjectPtr Ptr) const inline private
Definition at line 262 of file PersistentObjectPtr.h.
Referenced by TPersistentObjectPtr< FUniqueObjectGuid >::Get(), TPersistentObjectPtr< FUniqueObjectGuid >::Get(), and TPersistentObjectPtr< FUniqueObjectGuid >::operator=().
Get() [1/2]
template<class TObjectID> FORCEINLINE UObject * TPersistentObjectPtr< TObjectID >::Get () const inline
Dereference the pointer, which may cause it to become valid again.
Will not try to load pending outside of game thread
Returns
nullptr if this object is gone or the pointer was null, otherwise a valid UObject pointer
Definition at line 120 of file PersistentObjectPtr.h.
Referenced by TPersistentObjectPtr< FUniqueObjectGuid >::IsPending(), TPersistentObjectPtr< FUniqueObjectGuid >::IsValid(), TPersistentObjectPtr< FUniqueObjectGuid >::operator*(), and TPersistentObjectPtr< FUniqueObjectGuid >::operator->().
Get() [2/2]
template<class TObjectID> FORCEINLINE UObject * TPersistentObjectPtr< TObjectID >::Get (bool bEvenIfPendingKill) const inline
Dereference the lazy pointer, which may cause it to become valid again.
Will not try to load pending outside of game thread
Parameters
bEvenIfPendingKill,if this is true, pendingkill objects are considered valid
Returns
nullptr if this object is gone or the lazy pointer was null, otherwise a valid UObject pointer
Definition at line 146 of file PersistentObjectPtr.h.
GetUniqueID() [1/2]
template<class TObjectID> FORCEINLINE TObjectID & TPersistentObjectPtr< TObjectID >::GetUniqueID () inline
Non-const version of the above.
Definition at line 110 of file PersistentObjectPtr.h.
GetUniqueID() [2/2]
template<class TObjectID> FORCEINLINE const TObjectID & TPersistentObjectPtr< TObjectID >::GetUniqueID () const inline
Gets the unique object identifier associated with this lazy pointer.
Valid even if pointer is not currently valid
Returns
Unique ID for this object, or an invalid FUniqueObjectGuid if this pointer isn't set to anything
Definition at line 104 of file PersistentObjectPtr.h.
IsNull()
template<class TObjectID> FORCEINLINE bool TPersistentObjectPtr< TObjectID >::IsNull () const inline
Test if this can never point to a live UObject.
Returns
true if this is explicitly pointing to no object
Definition at line 247 of file PersistentObjectPtr.h.
IsPending()
template<class TObjectID> FORCEINLINE bool TPersistentObjectPtr< TObjectID >::IsPending () const inline
Test if this does not point to a live UObject, but may in the future.
Returns
true if this does not point to a real object, but could possibly
Definition at line 218 of file PersistentObjectPtr.h.
IsStale()
template<class TObjectID> FORCEINLINE bool TPersistentObjectPtr< TObjectID >::IsStale () const inline
Slightly different than !IsValid(), returns true if this used to point to a UObject, but doesn't any more and has not been assigned or reset in the mean time.
Returns
true if this used to point at a real object but no longer does.
Definition at line 238 of file PersistentObjectPtr.h.
IsValid()
template<class TObjectID> FORCEINLINE bool TPersistentObjectPtr< TObjectID >::IsValid () const inline
Test if this points to a live UObject.
Returns
true if Get() would return a valid non-null pointer
Definition at line 228 of file PersistentObjectPtr.h.
Referenced by TPersistentObjectPtr< FUniqueObjectGuid >::operator!=(), TPersistentObjectPtr< FUniqueObjectGuid >::operator!=, TPersistentObjectPtr< FUniqueObjectGuid >::operator==(), and TPersistentObjectPtr< FUniqueObjectGuid >::operator==.
operator!=() [1/2]
template<class TObjectID> FORCEINLINE bool TPersistentObjectPtr< TObjectID >::operator!= (const TPersistentObjectPtr< TObjectID > & Rhs) const inline
Compare pointers for inequality.
Only Serial Number matters for the base implementation
Definition at line 191 of file PersistentObjectPtr.h.
operator!=() [2/2]
template<class TObjectID> FORCEINLINE bool TPersistentObjectPtr< TObjectID >::operator!= (TYPE_OF_NULLPTR) const inline
Definition at line 196 of file PersistentObjectPtr.h.
operator*()
template<class TObjectID> FORCEINLINE UObject & TPersistentObjectPtr< TObjectID >::operator* () const inline
Dereference the pointer.
Definition at line 168 of file PersistentObjectPtr.h.
operator->()
template<class TObjectID> FORCEINLINE UObject * TPersistentObjectPtr< TObjectID >::operator-> () const inline
Dereference the pointer.
Definition at line 174 of file PersistentObjectPtr.h.
operator=() [1/5]
template<class TObjectID> FORCEINLINE void TPersistentObjectPtr< TObjectID >::operator= (const FWeakObjectPtr & Other) inline
Copy from an existing weak pointer, reserve IDs if required.
Definition at line 92 of file PersistentObjectPtr.h.
operator=() [2/5]
template<class TObjectID> FORCEINLINE void TPersistentObjectPtr< TObjectID >::operator= (const TObjectID & InObjectID) inline
Copy from a unique object identifier.
Definition at line 49 of file PersistentObjectPtr.h.
operator=() [3/5]
template<class TObjectID> FORCEINLINE void TPersistentObjectPtr< TObjectID >::operator= (const UObject * Object) inline
Definition at line 75 of file PersistentObjectPtr.h.
operator=() [4/5]
template<class TObjectID> void TPersistentObjectPtr< TObjectID >::operator= (FObjectPtr Object) inline
Copy from an object pointer.
Definition at line 56 of file PersistentObjectPtr.h.
operator=() [5/5]
template<class TObjectID> template<typename T> FORCEINLINE void TPersistentObjectPtr< TObjectID >::operator= (TObjectPtr< T > Object) inline
Definition at line 80 of file PersistentObjectPtr.h.
operator==() [1/2]
template<class TObjectID> FORCEINLINE bool TPersistentObjectPtr< TObjectID >::operator== (const TPersistentObjectPtr< TObjectID > & Rhs) const inline
Compare pointers for equality.
Only Serial Number matters for the base implementation
Definition at line 180 of file PersistentObjectPtr.h.
operator==() [2/2]
template<class TObjectID> FORCEINLINE bool TPersistentObjectPtr< TObjectID >::operator== (TYPE_OF_NULLPTR) const inline
Definition at line 185 of file PersistentObjectPtr.h.
Reset()
template<class TObjectID> FORCEINLINE void TPersistentObjectPtr< TObjectID >::Reset () inline
Reset the lazy pointer back to the null state.
Definition at line 29 of file PersistentObjectPtr.h.
Referenced by TPersistentObjectPtr< FUniqueObjectGuid >::TPersistentObjectPtr(), and TPersistentObjectPtr< FUniqueObjectGuid >::operator=().
ResetWeakPtr()
template<class TObjectID> FORCEINLINE void TPersistentObjectPtr< TObjectID >::ResetWeakPtr () inline
Resets the weak ptr only, call this when ObjectId may change.
Definition at line 36 of file PersistentObjectPtr.h.
Friends And Related Symbol Documentation
GetTypeHash
template<class TObjectID> FORCEINLINE friend uint32 GetTypeHash (const TPersistentObjectPtr< TObjectID > & Ptr) friend
Hash function.
Definition at line 253 of file PersistentObjectPtr.h.
Referenced by TPersistentObjectPtr< FUniqueObjectGuid >::GetTypeHash.
operator!=
template<class TObjectID> FORCEINLINE friend bool operator!= (TYPE_OF_NULLPTR , const TPersistentObjectPtr< TObjectID > & Rhs) friend
Definition at line 207 of file PersistentObjectPtr.h.
operator==
template<class TObjectID> FORCEINLINE friend bool operator== (TYPE_OF_NULLPTR , const TPersistentObjectPtr< TObjectID > & Rhs) friend
Definition at line 202 of file PersistentObjectPtr.h.
Field Documentation
ObjectID
template<class TObjectID> TObjectID TPersistentObjectPtr< TObjectID >::ObjectID private
Guid for the object this pointer points to or will point to.
Definition at line 274 of file PersistentObjectPtr.h.
Referenced by TPersistentObjectPtr< FUniqueObjectGuid >::GetTypeHash, TPersistentObjectPtr< FUniqueObjectGuid >::operator!=(), and TPersistentObjectPtr< FUniqueObjectGuid >::operator==().
WeakPtr
template<class TObjectID> FWeakObjectPtr TPersistentObjectPtr< TObjectID >::WeakPtr mutable private
Once the object has been noticed to be loaded, this is set to the object weak pointer.
Definition at line 272 of file PersistentObjectPtr.h.
The documentation for this struct was generated from the following file:
Runtime/CoreUObject/Public/UObject/PersistentObjectPtr.h