Unreal Engine 5.6 C++ API: UE::Cook::FWorkerId Struct Reference
UE::Cook::FWorkerId Struct Reference
Identifier for a CookWorker process launched from a Director process, or for the local process.
#include "MPCollector.h"
Public Member Functions
FWorkerId ()
uint8 GetMultiprocessId () const
uint8 GetRemoteIndex () const
bool IsInvalid () const
bool IsLocal () const
bool IsRemote () const
bool IsValid () const
bool operator!= (const FWorkerId &Other) const
bool operator< (const FWorkerId &Other) const
bool operator== (const FWorkerId &Other) const
FString ToString ()
Static Public Member Functions
static FWorkerId FromLocalOrRemoteIndex (uint8 Index)
static FWorkerId FromRemoteIndex (uint8 Index)
static int32 GetMaxCookWorkerCount ()
static constexpr FWorkerId Invalid ()
static constexpr FWorkerId Local ()
Private Member Functions
constexpr FWorkerId (uint8 InId)
Private Attributes
uint8 Id
Static Private Attributes
static constexpr uint8 InvalidId = 255
static constexpr uint8 LocalId = 0
Friends
int32 GetTypeHash (const FWorkerId &WorkerId)
Detailed Description
Identifier for a CookWorker process launched from a Director process, or for the local process.
A director can have multiple CookWorkers.
Definition at line 35 of file MPCollector.h.
Constructor & Destructor Documentation
FWorkerId() [1/2]
UE::Cook::FWorkerId::FWorkerId () inline
Definition at line 38 of file MPCollector.h.
References Id, and InvalidId.
Referenced by FromLocalOrRemoteIndex(), FromRemoteIndex(), GetTypeHash, Invalid(), Local(), operator!=(), operator<(), and operator==().
FWorkerId() [2/2]
UE::Cook::FWorkerId::FWorkerId (uint8 InId) inline explicit constexpr private
Definition at line 59 of file MPCollector.h.
References Id.
Member Function Documentation
FromLocalOrRemoteIndex()
FWorkerId UE::Cook::FWorkerId::FromLocalOrRemoteIndex (uint8 Index) inline static
Definition at line 42 of file MPCollector.h.
References FWorkerId(), check, and InvalidId.
FromRemoteIndex()
FWorkerId UE::Cook::FWorkerId::FromRemoteIndex (uint8 Index) inline static
Definition at line 41 of file MPCollector.h.
References FWorkerId(), check, and InvalidId.
GetMaxCookWorkerCount()
int32 UE::Cook::FWorkerId::GetMaxCookWorkerCount () inline static
Definition at line 43 of file MPCollector.h.
References InvalidId.
GetMultiprocessId()
uint8 UE::Cook::FWorkerId::GetMultiprocessId () const inline
Definition at line 50 of file MPCollector.h.
References check, Id, and IsValid().
GetRemoteIndex()
uint8 UE::Cook::FWorkerId::GetRemoteIndex () const inline
Definition at line 49 of file MPCollector.h.
References check, Id, and IsRemote().
Referenced by ToString().
Invalid()
constexpr FWorkerId UE::Cook::FWorkerId::Invalid () inline static constexpr
Definition at line 39 of file MPCollector.h.
References FWorkerId(), and InvalidId.
IsInvalid()
bool UE::Cook::FWorkerId::IsInvalid () const inline
Definition at line 46 of file MPCollector.h.
References Id, and InvalidId.
Referenced by ToString().
IsLocal()
bool UE::Cook::FWorkerId::IsLocal () const inline
Definition at line 47 of file MPCollector.h.
References Id, and LocalId.
Referenced by ToString().
IsRemote()
bool UE::Cook::FWorkerId::IsRemote () const inline
Definition at line 48 of file MPCollector.h.
References Id, InvalidId, and LocalId.
Referenced by GetRemoteIndex().
IsValid()
bool UE::Cook::FWorkerId::IsValid () const inline
Definition at line 45 of file MPCollector.h.
References Id, and InvalidId.
Referenced by GetMultiprocessId().
Local()
constexpr FWorkerId UE::Cook::FWorkerId::Local () inline static constexpr
Definition at line 40 of file MPCollector.h.
References FWorkerId(), and LocalId.
operator!=()
bool UE::Cook::FWorkerId::operator!= (const FWorkerId & Other) const inline
Definition at line 52 of file MPCollector.h.
References FWorkerId(), Id, and Other.
operator<()
bool UE::Cook::FWorkerId::operator< (const FWorkerId & Other) const inline
Definition at line 53 of file MPCollector.h.
References FWorkerId(), Id, and Other.
operator==()
bool UE::Cook::FWorkerId::operator== (const FWorkerId & Other) const inline
Definition at line 51 of file MPCollector.h.
References FWorkerId(), Id, and Other.
ToString()
FString UE::Cook::FWorkerId::ToString () inline
Definition at line 337 of file MPCollector.h.
References GetRemoteIndex(), IsInvalid(), IsLocal(), and TEXT.
Friends And Related Symbol Documentation
GetTypeHash
int32 GetTypeHash (const FWorkerId & WorkerId) friend
Definition at line 54 of file MPCollector.h.
References FWorkerId(), and Id.
Field Documentation
Id
uint8 UE::Cook::FWorkerId::Id private
Definition at line 62 of file MPCollector.h.
Referenced by FWorkerId(), FWorkerId(), GetMultiprocessId(), GetRemoteIndex(), GetTypeHash, IsInvalid(), IsLocal(), IsRemote(), IsValid(), operator!=(), operator<(), and operator==().
InvalidId
uint8 UE::Cook::FWorkerId::InvalidId = 255 static constexpr private
Definition at line 64 of file MPCollector.h.
Referenced by FWorkerId(), FromLocalOrRemoteIndex(), FromRemoteIndex(), GetMaxCookWorkerCount(), Invalid(), IsInvalid(), IsRemote(), and IsValid().
LocalId
uint8 UE::Cook::FWorkerId::LocalId = 0 static constexpr private
Definition at line 65 of file MPCollector.h.
Referenced by IsLocal(), IsRemote(), and Local().
The documentation for this struct was generated from the following file:
Runtime/CoreUObject/Public/Cooker/MPCollector.h