Unreal Engine 5.6 C++ API: FBuzHash Struct Reference
FBuzHash Struct Reference
Rolling hash function.
#include "BuzHash.h"
Public Member Functions
FORCEINLINE void Add (const uint8 *Data, uint64 Size)
Adds an array of bytes to the start of the window.
FORCEINLINE void Add (FMemoryView View)
Adds an array of bytes to the start of the window.
FORCEINLINE void Add (uint8 X)
Appends a byte to the start of the window and updates the hash.
FORCEINLINE uint32 Get () const
Gets the current hash value.
FORCEINLINE uint64 GetWindowSize () const
Gets the size of the window.
FORCEINLINE void Reset ()
Reset the state of the hasher.
FORCEINLINE void Sub (uint8 X)
Removes a byte from the back of the sliding window and updates the hash.
Static Private Member Functions
static FORCEINLINE uint32 Rol32 (uint32 V, uint32 N)
Private Attributes
uint64 Count = 0
uint32 State = 0
Static Private Attributes
static const uint32 Table [256]
Detailed Description
Rolling hash function.
Allows efficient computation of the hash of a window into a block of data, which can be moved through the data byte by byte.
Definition at line 12 of file BuzHash.h.
Member Function Documentation
Add() [1/3]
FORCEINLINE void FBuzHash::Add (const uint8 * Data, uint64 Size) inline
Adds an array of bytes to the start of the window.
Definition at line 38 of file BuzHash.h.
References Add, FORCEINLINE, and TSequenceHistory< HistorySize >::Size.
Add() [2/3]
FORCEINLINE void FBuzHash::Add (FMemoryView View) inline
Adds an array of bytes to the start of the window.
Definition at line 32 of file BuzHash.h.
References Add, FORCEINLINE, TMemoryView< DataType >::GetData(), and TMemoryView< DataType >::GetSize().
Add() [3/3]
FORCEINLINE void FBuzHash::Add (uint8 X) inline
Appends a byte to the start of the window and updates the hash.
Definition at line 25 of file BuzHash.h.
References Count, FORCEINLINE, Rol32(), State, Table, and X.
Get()
FORCEINLINE uint32 FBuzHash::Get () const inline
Gets the current hash value.
Definition at line 19 of file BuzHash.h.
References FORCEINLINE, and State.
GetWindowSize()
FORCEINLINE uint64 FBuzHash::GetWindowSize () const inline
Gets the size of the window.
Definition at line 22 of file BuzHash.h.
References Count, and FORCEINLINE.
Reset()
FORCEINLINE void FBuzHash::Reset () inline
Reset the state of the hasher.
Definition at line 16 of file BuzHash.h.
References FORCEINLINE.
Rol32()
FORCEINLINE uint32 FBuzHash::Rol32 (uint32 V, uint32 N) inline static private
Definition at line 59 of file BuzHash.h.
References FORCEINLINE.
Referenced by Add(), and Sub().
Sub()
FORCEINLINE void FBuzHash::Sub (uint8 X) inline
Removes a byte from the back of the sliding window and updates the hash.
Definition at line 47 of file BuzHash.h.
References Count, FORCEINLINE, Rol32(), State, Table, and X.
Field Documentation
Count
uint64 FBuzHash::Count = 0 private
Definition at line 56 of file BuzHash.h.
Referenced by Add(), GetWindowSize(), and Sub().
State
uint32 FBuzHash::State = 0 private
Definition at line 57 of file BuzHash.h.
Referenced by Add(), Get(), and Sub().
Table
const uint32 FBuzHash::Table[256] static private
Definition at line 54 of file BuzHash.h.
Referenced by Add(), and Sub().
The documentation for this struct was generated from the following file:
Runtime/Core/Public/Hash/BuzHash.h