Unreal Engine 5.6 C++ API: UE::Transaction::FSerializedObjectData Struct Reference
UE::Transaction::FSerializedObjectData Struct Reference
#include "TransactionCommon.h"
Public Member Functions
const void * GetPtr (int64 Offset) const
int64 Num () const
void Read (void *Dest, int64 Offset, int64 Num) const
void Reset ()
bool Serialize (FArchive &Ar)
void Write (const void *Src, int64 Offset, int64 Num)
Private Attributes
TArray64< uint8 > Data
Friends
bool operator!= (const FSerializedObjectData &LHS, const FSerializedObjectData &RHS)
FArchive & operator<< (FArchive &Ar, FSerializedObjectData &SerializedData)
bool operator== (const FSerializedObjectData &LHS, const FSerializedObjectData &RHS)
Detailed Description
Definition at line 144 of file TransactionCommon.h.
Member Function Documentation
GetPtr()
const void * UE::Transaction::FSerializedObjectData::GetPtr (int64 Offset) const inline
Definition at line 172 of file TransactionCommon.h.
References Data.
Num()
int64 UE::Transaction::FSerializedObjectData::Num () const inline
Definition at line 182 of file TransactionCommon.h.
References Data.
Referenced by Read(), and Write().
Read()
void UE::Transaction::FSerializedObjectData::Read (void * Dest, int64 Offset, int64 Num) const
References Num().
Reset()
void UE::Transaction::FSerializedObjectData::Reset () inline
Definition at line 177 of file TransactionCommon.h.
References Data.
Serialize()
bool UE::Transaction::FSerializedObjectData::Serialize (FArchive & Ar) inline
Definition at line 147 of file TransactionCommon.h.
References Ar.
Write()
void UE::Transaction::FSerializedObjectData::Write (const void * Src, int64 Offset, int64 Num)
References Num().
Friends And Related Symbol Documentation
operator!=
bool operator!= (const FSerializedObjectData & LHS, const FSerializedObjectData & RHS) friend
Definition at line 164 of file TransactionCommon.h.
operator<<
FArchive & operator<< (FArchive & Ar, FSerializedObjectData & SerializedData) friend
Definition at line 153 of file TransactionCommon.h.
References Ar, and Data.
operator==
bool operator== (const FSerializedObjectData & LHS, const FSerializedObjectData & RHS) friend
Definition at line 159 of file TransactionCommon.h.
References Data.
Field Documentation
Data
TArray64<uint8> UE::Transaction::FSerializedObjectData::Data private
Definition at line 188 of file TransactionCommon.h.
Referenced by GetPtr(), Num(), operator<<, operator==, and Reset().
The documentation for this struct was generated from the following file:
Runtime/Engine/Public/TransactionCommon.h