Unreal Engine 5.6 C++ API: TListTypeTraits< TSharedRef< T, ESPMode::NotThreadSafe > > Struct Template Reference
TListTypeTraits< TSharedRef< T, ESPMode::NotThreadSafe > > Struct Template Reference
#include "TableViewTypeTraits.h"
Data Structures
class SerializerType
Public Types
using MapKeyFuncs = TDefaultMapHashableKeyFuncs<TSharedRef<T, ESPMode::NotThreadSafe>, TSharedRef<ITableRow>, false>
using MapKeyFuncsSparse = TDefaultMapHashableKeyFuncs<TSharedRef<T, ESPMode::NotThreadSafe>, FSparseItemInfo, false>
typedef TSharedPtr< T > NullableType
using SetKeyFuncs = DefaultKeyFuncs<TSharedRef<T, ESPMode::NotThreadSafe>>
Static Public Member Functions
template<typename U>
static void AddReferencedObjects (FReferenceCollector &, TArray< TSharedRef< T > > &, TSet< TSharedRef< T > > &, TMap< const U *, TSharedRef< T > > &)
static FString DebugDump (TSharedRef< T > InPtr)
static bool IsPtrValid (const TSharedPtr< T > &InPtr)
static TSharedPtr< T > MakeNullPtr ()
static TSharedRef< T > NullableItemTypeConvertToItemType (const TSharedPtr< T > &InPtr)
static void ResetPtr (TSharedPtr< T > &InPtr)
Detailed Description
template<typename T>
struct TListTypeTraits< TSharedRef< T, ESPMode::NotThreadSafe > >
Definition at line 221 of file TableViewTypeTraits.h.
Member Typedef Documentation
MapKeyFuncs
template<typename T> using TListTypeTraits< TSharedRef< T, ESPMode::NotThreadSafe > >::MapKeyFuncs = TDefaultMapHashableKeyFuncs<TSharedRef<T, ESPMode::NotThreadSafe>, TSharedRef<ITableRow>, false>
Definition at line 226 of file TableViewTypeTraits.h.
MapKeyFuncsSparse
template<typename T> using TListTypeTraits< TSharedRef< T, ESPMode::NotThreadSafe > >::MapKeyFuncsSparse = TDefaultMapHashableKeyFuncs<TSharedRef<T, ESPMode::NotThreadSafe>, FSparseItemInfo, false>
Definition at line 227 of file TableViewTypeTraits.h.
NullableType
template<typename T> typedef TSharedPtr<T> TListTypeTraits< TSharedRef< T, ESPMode::NotThreadSafe > >::NullableType
Definition at line 224 of file TableViewTypeTraits.h.
SetKeyFuncs
template<typename T> using TListTypeTraits< TSharedRef< T, ESPMode::NotThreadSafe > >::SetKeyFuncs = DefaultKeyFuncs<TSharedRef<T, ESPMode::NotThreadSafe>>
Definition at line 228 of file TableViewTypeTraits.h.
Member Function Documentation
AddReferencedObjects()
template<typename T> template<typename U> void TListTypeTraits< TSharedRef< T, ESPMode::NotThreadSafe > >::AddReferencedObjects (FReferenceCollector & , TArray< TSharedRef< T > > & , TSet< TSharedRef< T > > & , TMap< const U *, TSharedRef< T > > &) inline static
Definition at line 231 of file TableViewTypeTraits.h.
DebugDump()
template<typename T> FString TListTypeTraits< TSharedRef< T, ESPMode::NotThreadSafe > >::DebugDump (TSharedRef< T > InPtr) inline static
Definition at line 258 of file TableViewTypeTraits.h.
References TSharedRef< ObjectType, InMode >::Get(), TEXT, and UPTRINT_x_FMT.
IsPtrValid()
template<typename T> bool TListTypeTraits< TSharedRef< T, ESPMode::NotThreadSafe > >::IsPtrValid (const TSharedPtr< T > & InPtr) inline static
Definition at line 238 of file TableViewTypeTraits.h.
References TSharedPtr< ObjectType, InMode >::IsValid().
MakeNullPtr()
template<typename T> TSharedPtr< T > TListTypeTraits< TSharedRef< T, ESPMode::NotThreadSafe > >::MakeNullPtr () inline static
Definition at line 248 of file TableViewTypeTraits.h.
NullableItemTypeConvertToItemType()
template<typename T> TSharedRef< T > TListTypeTraits< TSharedRef< T, ESPMode::NotThreadSafe > >::NullableItemTypeConvertToItemType (const TSharedPtr< T > & InPtr) inline static
Definition at line 253 of file TableViewTypeTraits.h.
References TSharedPtr< ObjectType, InMode >::ToSharedRef().
ResetPtr()
template<typename T> void TListTypeTraits< TSharedRef< T, ESPMode::NotThreadSafe > >::ResetPtr (TSharedPtr< T > & InPtr) inline static
Definition at line 243 of file TableViewTypeTraits.h.
References TSharedPtr< ObjectType, InMode >::Reset().
The documentation for this struct was generated from the following file:
Runtime/Slate/Public/Framework/Views/TableViewTypeTraits.h