Unreal Engine 5.6 C++ API: UE::Landscape::EditLayers::FWeightmapBlendParams Struct Reference
UE::Landscape::EditLayers::FWeightmapBlendParams Struct Reference
#include "LandscapeEditLayerTypes.h"
Public Member Functions
FWeightmapBlendParams ()=default
FWeightmapBlendParams (EWeightmapBlendMode InBlendMode)
Static Public Member Functions
static const FWeightmapBlendParams & GetDefaultAdditiveBlendParams ()
static const FWeightmapBlendParams & GetDefaultPassthroughBlendParams ()
Data Fields
float Alpha = 1.0f
EWeightmapBlendMode BlendMode = EWeightmapBlendMode::Passthrough
Detailed Description
Definition at line 108 of file LandscapeEditLayerTypes.h.
Constructor & Destructor Documentation
FWeightmapBlendParams() [1/2]
UE::Landscape::EditLayers::FWeightmapBlendParams::FWeightmapBlendParams () default
Referenced by GetDefaultAdditiveBlendParams(), and GetDefaultPassthroughBlendParams().
FWeightmapBlendParams() [2/2]
UE::Landscape::EditLayers::FWeightmapBlendParams::FWeightmapBlendParams (EWeightmapBlendMode InBlendMode) inline
Definition at line 111 of file LandscapeEditLayerTypes.h.
References BlendMode.
Member Function Documentation
GetDefaultAdditiveBlendParams()
const FWeightmapBlendParams & UE::Landscape::EditLayers::FWeightmapBlendParams::GetDefaultAdditiveBlendParams () inline static
Definition at line 121 of file LandscapeEditLayerTypes.h.
References FWeightmapBlendParams(), and UE::Landscape::EditLayers::Additive.
GetDefaultPassthroughBlendParams()
const FWeightmapBlendParams & UE::Landscape::EditLayers::FWeightmapBlendParams::GetDefaultPassthroughBlendParams () inline static
Definition at line 115 of file LandscapeEditLayerTypes.h.
References FWeightmapBlendParams(), and UE::Landscape::EditLayers::Passthrough.
Field Documentation
Alpha
float UE::Landscape::EditLayers::FWeightmapBlendParams::Alpha = 1.0f
Definition at line 128 of file LandscapeEditLayerTypes.h.
BlendMode
EWeightmapBlendMode UE::Landscape::EditLayers::FWeightmapBlendParams::BlendMode = EWeightmapBlendMode::Passthrough
Definition at line 127 of file LandscapeEditLayerTypes.h.
Referenced by FWeightmapBlendParams().
The documentation for this struct was generated from the following file:
Runtime/Landscape/Public/LandscapeEditLayerTypes.h