Unreal Engine 5.6 C++ API: TConcurrentLinearBulkObjectAllocator< BlockAllocationTag >::TObjectArray< T > Struct Template Reference
TConcurrentLinearBulkObjectAllocator< BlockAllocationTag >::TObjectArray< T > Struct Template Reference final
Public Member Functions
TObjectArray (SIZE_T InNum)
virtual ~TObjectArray () override
Public Member Functions inherited from TConcurrentLinearBulkObjectAllocator< BlockAllocationTag >::FAllocation
virtual ~FAllocation ()=default
Data Fields
SIZE_T Num
Data Fields inherited from TConcurrentLinearBulkObjectAllocator< BlockAllocationTag >::FAllocation
FAllocation * Next = nullptr
Detailed Description
template<typename BlockAllocationTag>
template<typename T>
struct TConcurrentLinearBulkObjectAllocator< BlockAllocationTag >::TObjectArray< T >
Definition at line 756 of file ConcurrentLinearAllocator.h.
Constructor & Destructor Documentation
TObjectArray()
template<typename BlockAllocationTag> template<typename T> TConcurrentLinearBulkObjectAllocator< BlockAllocationTag >::TObjectArray< T >::TObjectArray (SIZE_T InNum) inline
Definition at line 758 of file ConcurrentLinearAllocator.h.
References Num.
Referenced by ~TObjectArray().
~TObjectArray()
template<typename BlockAllocationTag> template<typename T> virtual TConcurrentLinearBulkObjectAllocator< BlockAllocationTag >::TObjectArray< T >::~TObjectArray () inline override virtual
Definition at line 763 of file ConcurrentLinearAllocator.h.
References TObjectArray(), Align, checkSlow, IsAligned(), and Num.
Field Documentation
Num
template<typename BlockAllocationTag> template<typename T> SIZE_T TConcurrentLinearBulkObjectAllocator< BlockAllocationTag >::TObjectArray< T >::Num
Definition at line 775 of file ConcurrentLinearAllocator.h.
Referenced by TObjectArray(), and ~TObjectArray().
The documentation for this struct was generated from the following file:
Runtime/Core/Public/Experimental/ConcurrentLinearAllocator.h