Unreal Engine 5.6 C++ API: FSuggestedDriverEntry Struct Reference
FSuggestedDriverEntry Struct Reference
#include "GenericPlatformDriver.h"
Public Member Functions
FSuggestedDriverEntry ()=default
FSuggestedDriverEntry (const TCHAR *Entry)
bool AppliesToDriver (const FGPUDriverInfo &Info, uint32 &OutNumSatisfiedConstraints)
bool IsValid ()
Public Member Functions inherited from FDriverConfigEntryConstraints
FDriverConfigEntryConstraints ()=default
FDriverConfigEntryConstraints (const TCHAR *Entry)
bool AreConstraintsSatisfied (const FGPUDriverInfo &Info, uint32 &OutNumSatisfiedConstraints) const
bool HasConstraints ()
Data Fields
FString SuggestedDriverVersion
Data Fields inherited from FDriverConfigEntryConstraints
TOptional< FRegexPattern > AdapterNameRegexConstraint
TOptional< FString > RHINameConstraint
Detailed Description
Definition at line 449 of file GenericPlatformDriver.h.
Constructor & Destructor Documentation
FSuggestedDriverEntry() [1/2]
FSuggestedDriverEntry::FSuggestedDriverEntry () default
FSuggestedDriverEntry() [2/2]
FSuggestedDriverEntry::FSuggestedDriverEntry (const TCHAR * Entry) inline
Definition at line 452 of file GenericPlatformDriver.h.
References FDriverConfigEntryConstraints::FDriverConfigEntryConstraints(), FDriverConfigEntryConstraints::HasConstraints(), SuggestedDriverVersion, TEXT, and FParse::Value().
Member Function Documentation
AppliesToDriver()
bool FSuggestedDriverEntry::AppliesToDriver (const FGPUDriverInfo & Info, uint32 & OutNumSatisfiedConstraints) inline
Definition at line 466 of file GenericPlatformDriver.h.
References FDriverConfigEntryConstraints::AreConstraintsSatisfied(), Info, and IsValid().
IsValid()
bool FSuggestedDriverEntry::IsValid () inline
Definition at line 471 of file GenericPlatformDriver.h.
References SuggestedDriverVersion.
Referenced by AppliesToDriver().
Field Documentation
SuggestedDriverVersion
FString FSuggestedDriverEntry::SuggestedDriverVersion
Definition at line 476 of file GenericPlatformDriver.h.
Referenced by FSuggestedDriverEntry(), and IsValid().
The documentation for this struct was generated from the following file:
Runtime/Core/Public/GenericPlatform/GenericPlatformDriver.h