Unreal Engine 5.6 C++ API: UE::SequenceNavigator::FNavigationToolCastableTypeTable::FNavigationToolCastableTypeTableGenerator Struct Reference
UE::SequenceNavigator::FNavigationToolCastableTypeTable::FNavigationToolCastableTypeTableGenerator Struct Reference
Utility class that generates a type table used for dynamic casting and instance of an ICastable object.
Public Member Functions
template<typename StartClass, typename T, typename U = decltype(T::ID)>
void AddStaticType (T *, int16 StartOffset)
template<typename StartClass>
constexpr void AddStaticType (void *, int16 StartOffset)
uint32 ByteSize () const
SEQUENCERCORE_API FNavigationToolCastableTypeTable * Commit (uint32 TypeID, FName InName)
Commit this generator to its final form.
template<typename StartClass>
void ConsumeImplements (...)
template<typename StartClass, typename T, typename U = typename T::Implements>
void ConsumeImplements (T *, int16 StartOffset)
template<typename StartClass, typename T>
void ConsumeImplements (void *, int16 StartOffset)
template<typename StartClass, typename ... Types>
void ConsumeImplementsImpl (TImplements< Types... > *, int16 StartOffset)
template<typename T>
void Generate ()
Generate the type table from a template type.
Static Public Member Functions
template<typename FromType, typename ToType>
static int16 ClassOffsetFrom ()
Compute the ptr offset from one class to another in an inheritance hierarchy.
template<typename T>
static int16 ComputeStartOffset (const ICastable *)
Compute the start offset from an ICastable type to the root of T This offset is added to all other class offsets that are computed from T so that we can always cast from an ICastable* to the concrete types.
template<typename T>
static int16 ComputeStartOffset (const IDynamicExtension *)
Compute the start offset from an IDynamicExtension type to the root of T This offset is added to all other class offsets that are computed from T so that we can always cast from an IDynamicExtension* to the concrete types.
Private Attributes
TArray< int16 > StaticTypeOffsets
MovieScene::TFixedSparseBitSet< uint32 > TypeMask
Detailed Description
Utility class that generates a type table used for dynamic casting and instance of an ICastable object.
Definition at line 121 of file NavigationToolCastableTypeTable.h.
Member Function Documentation
AddStaticType() [1/2]
template<typename StartClass, typename T, typename U = decltype(T::ID)> void UE::SequenceNavigator::FNavigationToolCastableTypeTable::FNavigationToolCastableTypeTableGenerator::AddStaticType (T * , int16 StartOffset) inline
Definition at line 208 of file NavigationToolCastableTypeTable.h.
References ClassOffsetFrom(), ID, UE::MovieScene::NewlySet, StaticTypeOffsets, and TypeMask.
Referenced by ConsumeImplementsImpl(), and Generate().
AddStaticType() [2/2]
template<typename StartClass> void UE::SequenceNavigator::FNavigationToolCastableTypeTable::FNavigationToolCastableTypeTableGenerator::AddStaticType (void * , int16 StartOffset) inline constexpr
Definition at line 223 of file NavigationToolCastableTypeTable.h.
ByteSize()
uint32 UE::SequenceNavigator::FNavigationToolCastableTypeTable::FNavigationToolCastableTypeTableGenerator::ByteSize () const inline
Definition at line 179 of file NavigationToolCastableTypeTable.h.
References UE::SequenceNavigator::FNavigationToolCastableTypeTable::FNavigationToolCastableTypeTable(), and StaticTypeOffsets.
ClassOffsetFrom()
template<typename FromType, typename ToType> int16 UE::SequenceNavigator::FNavigationToolCastableTypeTable::FNavigationToolCastableTypeTableGenerator::ClassOffsetFrom () inline static
Compute the ptr offset from one class to another in an inheritance hierarchy.
Note
: This can be negative for situations where multiple inheritance would put the FromType class after the ToType in memory.
Definition at line 145 of file NavigationToolCastableTypeTable.h.
References Buffer, checkf, and TEXT.
Referenced by AddStaticType(), ComputeStartOffset(), and ComputeStartOffset().
Commit()
SEQUENCERCORE_API FNavigationToolCastableTypeTable * UE::SequenceNavigator::FNavigationToolCastableTypeTable::FNavigationToolCastableTypeTableGenerator::Commit (uint32 TypeID, FName InName)
Commit this generator to its final form.
References UE::SequenceNavigator::FNavigationToolCastableTypeTable::FNavigationToolCastableTypeTable(), and InName.
Referenced by UE::SequenceNavigator::FNavigationToolCastableTypeTable::MakeTypeTable(), and UE::SequenceNavigator::FNavigationToolCastableTypeTable::MakeTypeTable().
ComputeStartOffset() [1/2]
template<typename T> int16 UE::SequenceNavigator::FNavigationToolCastableTypeTable::FNavigationToolCastableTypeTableGenerator::ComputeStartOffset (const ICastable *) inline static
Compute the start offset from an ICastable type to the root of T This offset is added to all other class offsets that are computed from T so that we can always cast from an ICastable* to the concrete types.
Definition at line 163 of file NavigationToolCastableTypeTable.h.
References ClassOffsetFrom().
Referenced by Generate().
ComputeStartOffset() [2/2]
template<typename T> int16 UE::SequenceNavigator::FNavigationToolCastableTypeTable::FNavigationToolCastableTypeTableGenerator::ComputeStartOffset (const IDynamicExtension *) inline static
Compute the start offset from an IDynamicExtension type to the root of T This offset is added to all other class offsets that are computed from T so that we can always cast from an IDynamicExtension* to the concrete types.
Definition at line 174 of file NavigationToolCastableTypeTable.h.
References ClassOffsetFrom().
ConsumeImplements() [1/3]
template<typename StartClass> void UE::SequenceNavigator::FNavigationToolCastableTypeTable::FNavigationToolCastableTypeTableGenerator::ConsumeImplements (...) inline
Definition at line 191 of file NavigationToolCastableTypeTable.h.
ConsumeImplements() [2/3]
template<typename StartClass, typename T, typename U = typename T::Implements> void UE::SequenceNavigator::FNavigationToolCastableTypeTable::FNavigationToolCastableTypeTableGenerator::ConsumeImplements (T * , int16 StartOffset) inline
Definition at line 185 of file NavigationToolCastableTypeTable.h.
References ConsumeImplementsImpl().
Referenced by ConsumeImplementsImpl(), and Generate().
ConsumeImplements() [3/3]
template<typename StartClass, typename T> void UE::SequenceNavigator::FNavigationToolCastableTypeTable::FNavigationToolCastableTypeTableGenerator::ConsumeImplements (void * , int16 StartOffset) inline
Definition at line 203 of file NavigationToolCastableTypeTable.h.
ConsumeImplementsImpl()
template<typename StartClass, typename ... Types> void UE::SequenceNavigator::FNavigationToolCastableTypeTable::FNavigationToolCastableTypeTableGenerator::ConsumeImplementsImpl (TImplements< Types... > * , int16 StartOffset) inline
Definition at line 196 of file NavigationToolCastableTypeTable.h.
References AddStaticType(), and ConsumeImplements().
Referenced by ConsumeImplements().
Generate()
template<typename T> void UE::SequenceNavigator::FNavigationToolCastableTypeTable::FNavigationToolCastableTypeTableGenerator::Generate () inline
Generate the type table from a template type.
Definition at line 127 of file NavigationToolCastableTypeTable.h.
References AddStaticType(), ComputeStartOffset(), and ConsumeImplements().
Referenced by UE::SequenceNavigator::FNavigationToolCastableTypeTable::MakeTypeTable(), and UE::SequenceNavigator::FNavigationToolCastableTypeTable::MakeTypeTable().
Field Documentation
StaticTypeOffsets
TArray<int16> UE::SequenceNavigator::FNavigationToolCastableTypeTable::FNavigationToolCastableTypeTableGenerator::StaticTypeOffsets private
Definition at line 232 of file NavigationToolCastableTypeTable.h.
Referenced by AddStaticType(), and ByteSize().
TypeMask
MovieScene::TFixedSparseBitSet<uint32> UE::SequenceNavigator::FNavigationToolCastableTypeTable::FNavigationToolCastableTypeTableGenerator::TypeMask private
Definition at line 230 of file NavigationToolCastableTypeTable.h.
Referenced by AddStaticType().
The documentation for this struct was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Experimental/SequenceNavigator/Source/SequenceNavigator/Public/NavigationToolCastableTypeTable.h