Unreal Engine 5.6 C++ API: FTabPayload_UObject Struct Reference
FTabPayload_UObject Struct Reference
#include "WorkflowUObjectDocuments.h"
Public Member Functions
virtual ~FTabPayload_UObject ()
virtual bool IsEqual (const TSharedRef< FTabPayload > &OtherPayload) const override
virtual bool IsValid () const override
Public Member Functions inherited from FTabPayload
virtual ~FTabPayload ()
Static Public Member Functions
template<typename CastType>
static CastType * CastChecked (TSharedPtr< FTabPayload > Payload)
static TSharedRef< FTabPayload_UObject > Make (const UObject *DocumentID)
Private Member Functions
FTabPayload_UObject (UObject *InDocumentID)
Private Attributes
TWeakObjectPtr< UObject > DocumentID
Additional Inherited Members
Data Fields inherited from FTabPayload
const FName PayloadType
Protected Member Functions inherited from FTabPayload
FTabPayload (FName InPayloadType)
Detailed Description
Definition at line 18 of file WorkflowUObjectDocuments.h.
Constructor & Destructor Documentation
~FTabPayload_UObject()
virtual FTabPayload_UObject::~FTabPayload_UObject () inline virtual
Definition at line 54 of file WorkflowUObjectDocuments.h.
FTabPayload_UObject()
FTabPayload_UObject::FTabPayload_UObject (UObject * InDocumentID) inline private
Definition at line 58 of file WorkflowUObjectDocuments.h.
References FTabPayload::FTabPayload(), and DocumentID.
Referenced by Make().
Member Function Documentation
CastChecked()
template<typename CastType> CastType * FTabPayload_UObject::CastChecked (TSharedPtr< FTabPayload > Payload) inline static
Definition at line 30 of file WorkflowUObjectDocuments.h.
References check, TSharedPtr< ObjectType, InMode >::IsValid(), and StaticCastSharedPtr().
Referenced by FDocumentTabFactoryForObjects< BaseClass >::ConstructTabName(), FDocumentTabFactoryForObjects< BaseClass >::CreateTabBody(), FDocumentTabFactoryForObjects< BaseClass >::GetTabIcon(), and FDocumentTabFactoryForObjects< BaseClass >::IsPayloadSupported().
IsEqual()
virtual bool FTabPayload_UObject::IsEqual (const TSharedRef< FTabPayload > & OtherPayload) const inline override virtual
Reimplemented from FTabPayload.
Definition at line 39 of file WorkflowUObjectDocuments.h.
References DocumentID, FTabPayload::PayloadType, and StaticCastSharedRef().
IsValid()
virtual bool FTabPayload_UObject::IsValid () const inline override virtual
Reimplemented from FTabPayload.
Definition at line 49 of file WorkflowUObjectDocuments.h.
References DocumentID.
Make()
TSharedRef< FTabPayload_UObject > FTabPayload_UObject::Make (const UObject * DocumentID) inline static
Definition at line 22 of file WorkflowUObjectDocuments.h.
References FTabPayload_UObject(), DocumentID, and MakeShareable().
Field Documentation
DocumentID
TWeakObjectPtr<UObject> FTabPayload_UObject::DocumentID private
Definition at line 66 of file WorkflowUObjectDocuments.h.
Referenced by FTabPayload_UObject(), IsEqual(), IsValid(), and Make().
The documentation for this struct was generated from the following file:
Editor/UnrealEd/Public/WorkflowOrientedApp/WorkflowUObjectDocuments.h