Unreal Engine 5.6 C++ API: FRDGBuilder::FAsyncSetupOp Struct Reference
FRDGBuilder::FAsyncSetupOp Struct Reference
Public Types
enum class EType : uint8 { SetupPassResources , CullRootBuffer , CullRootTexture , ReservedBufferCommit }
Public Member Functions
FAsyncSetupOp (EType InType, uint64 InPayload=0)
EType GetType () const
Static Public Member Functions
static FAsyncSetupOp CullRootBuffer (FRDGBuffer *Buffer)
static FAsyncSetupOp CullRootTexture (FRDGTexture *Texture)
static FAsyncSetupOp ReservedBufferCommit (FRDGBuffer *Buffer, uint64 CommitSizeInBytes)
static FAsyncSetupOp SetupPassResources (FRDGPass *Pass)
Data Fields
union {
FRDGBuffer * Buffer
FRDGPass * Pass
FRDGTexture * Texture
};
uint64 Payload: 48
uint64 Type: 8
Detailed Description
Definition at line 877 of file RenderGraphBuilder.h.
Member Enumeration Documentation
EType
enum class FRDGBuilder::FAsyncSetupOp::EType : uint8 strong
Enumerator
SetupPassResources
CullRootBuffer
CullRootTexture
ReservedBufferCommit
Definition at line 879 of file RenderGraphBuilder.h.
Constructor & Destructor Documentation
FAsyncSetupOp()
FRDGBuilder::FAsyncSetupOp::FAsyncSetupOp (EType InType, uint64 InPayload = 0) inline
Definition at line 923 of file RenderGraphBuilder.h.
References check, Payload, and Type.
Referenced by CullRootBuffer(), CullRootTexture(), ReservedBufferCommit(), and SetupPassResources().
Member Function Documentation
CullRootBuffer()
FAsyncSetupOp FRDGBuilder::FAsyncSetupOp::CullRootBuffer (FRDGBuffer * Buffer) inline static
Definition at line 894 of file RenderGraphBuilder.h.
References FAsyncSetupOp(), Buffer, and CullRootBuffer.
CullRootTexture()
FAsyncSetupOp FRDGBuilder::FAsyncSetupOp::CullRootTexture (FRDGTexture * Texture) inline static
Definition at line 901 of file RenderGraphBuilder.h.
References FAsyncSetupOp(), CullRootTexture, and Texture.
GetType()
EType FRDGBuilder::FAsyncSetupOp::GetType () const inline
Definition at line 915 of file RenderGraphBuilder.h.
References Type.
ReservedBufferCommit()
FAsyncSetupOp FRDGBuilder::FAsyncSetupOp::ReservedBufferCommit (FRDGBuffer * Buffer, uint64 CommitSizeInBytes) inline static
Definition at line 908 of file RenderGraphBuilder.h.
References FAsyncSetupOp(), Buffer, and ReservedBufferCommit.
SetupPassResources()
FAsyncSetupOp FRDGBuilder::FAsyncSetupOp::SetupPassResources (FRDGPass * Pass) inline static
Definition at line 887 of file RenderGraphBuilder.h.
References FAsyncSetupOp(), Pass, and SetupPassResources.
Field Documentation
[union]
union { ... } FRDGBuilder::FAsyncSetupOp
Buffer
FRDGBuffer* FRDGBuilder::FAsyncSetupOp::Buffer
Definition at line 933 of file RenderGraphBuilder.h.
Referenced by CullRootBuffer(), and ReservedBufferCommit().
Pass
FRDGPass* FRDGBuilder::FAsyncSetupOp::Pass
Definition at line 932 of file RenderGraphBuilder.h.
Referenced by SetupPassResources().
Payload
uint64 FRDGBuilder::FAsyncSetupOp::Payload
Definition at line 921 of file RenderGraphBuilder.h.
Referenced by FAsyncSetupOp().
Texture
FRDGTexture* FRDGBuilder::FAsyncSetupOp::Texture
Definition at line 934 of file RenderGraphBuilder.h.
Referenced by CullRootTexture().
Type
uint64 FRDGBuilder::FAsyncSetupOp::Type
Definition at line 920 of file RenderGraphBuilder.h.
Referenced by FAsyncSetupOp(), and GetType().
The documentation for this struct was generated from the following file:
Runtime/RenderCore/Public/RenderGraphBuilder.h