Unreal Engine 5.6 C++ API: FInputEventState Struct Reference
FInputEventState Struct Reference
#include "EditorViewportClient.h"
Public Member Functions
FInputEventState (FViewport *InViewport, FKey InKey, EInputEvent InInputEvent)
EInputEvent GetInputEvent () const
FKey GetKey () const
FViewport * GetViewport () const
bool IsAltButtonEvent () const
bool IsAltButtonPressed () const
return true if alt is pressed right now.
bool IsAnyMouseButtonDown () const
bool IsButtonPressed (FKey InKey) const
bool IsCommandButtonEvent () const
bool IsCommandButtonPressed () const
bool IsCtrlButtonEvent () const
return true if the event causing button is a control key
bool IsCtrlButtonPressed () const
bool IsLeftMouseButtonPressed () const
bool IsMiddleMouseButtonPressed () const
bool IsMouseButtonEvent () const
bool IsRightMouseButtonPressed () const
bool IsShiftButtonEvent () const
bool IsShiftButtonPressed () const
bool IsSpaceBarPressed () const
Private Attributes
EInputEvent InputEvent
Key event.
FKey Key
Pressed Key.
FViewport * Viewport
Viewport the event was sent to.
Detailed Description
Definition at line 113 of file EditorViewportClient.h.
Constructor & Destructor Documentation
FInputEventState()
FInputEventState::FInputEventState (FViewport * InViewport, FKey InKey, EInputEvent InInputEvent) inline
Definition at line 116 of file EditorViewportClient.h.
References InputEvent, Key, and Viewport.
Member Function Documentation
GetInputEvent()
EInputEvent FInputEventState::GetInputEvent () const inline
Definition at line 123 of file EditorViewportClient.h.
References InputEvent.
GetKey()
FKey FInputEventState::GetKey () const inline
Definition at line 124 of file EditorViewportClient.h.
References Key.
GetViewport()
FViewport * FInputEventState::GetViewport () const inline
Definition at line 122 of file EditorViewportClient.h.
References Viewport.
IsAltButtonEvent()
bool FInputEventState::IsAltButtonEvent () const inline
Definition at line 129 of file EditorViewportClient.h.
References Key, EKeys::LeftAlt, and EKeys::RightAlt.
Referenced by IsAltButtonPressed().
IsAltButtonPressed()
bool FInputEventState::IsAltButtonPressed () const inline
return true if alt is pressed right now.
This will be true even if the event was for a different key but an alt key is currently pressed
Definition at line 141 of file EditorViewportClient.h.
References InputEvent, IsAltButtonEvent(), IsButtonPressed(), EKeys::LeftAlt, and EKeys::RightAlt.
IsAnyMouseButtonDown()
bool FInputEventState::IsAnyMouseButtonDown () const inline
Definition at line 138 of file EditorViewportClient.h.
References IsButtonPressed(), EKeys::LeftMouseButton, EKeys::MiddleMouseButton, and EKeys::RightMouseButton.
IsButtonPressed()
bool FInputEventState::IsButtonPressed (FKey InKey) const inline
Definition at line 137 of file EditorViewportClient.h.
References Viewport.
Referenced by IsAltButtonPressed(), IsAnyMouseButtonDown(), IsCommandButtonPressed(), IsCtrlButtonPressed(), IsLeftMouseButtonPressed(), IsMiddleMouseButtonPressed(), IsRightMouseButtonPressed(), IsShiftButtonPressed(), and IsSpaceBarPressed().
IsCommandButtonEvent()
bool FInputEventState::IsCommandButtonEvent () const inline
Definition at line 130 of file EditorViewportClient.h.
References Key, EKeys::LeftCommand, and EKeys::RightCommand.
Referenced by IsCommandButtonPressed().
IsCommandButtonPressed()
bool FInputEventState::IsCommandButtonPressed () const inline
Definition at line 144 of file EditorViewportClient.h.
References InputEvent, IsButtonPressed(), IsCommandButtonEvent(), EKeys::LeftCommand, and EKeys::RightCommand.
IsCtrlButtonEvent()
bool FInputEventState::IsCtrlButtonEvent () const inline
return true if the event causing button is a control key
Definition at line 127 of file EditorViewportClient.h.
References Key, EKeys::LeftControl, and EKeys::RightControl.
Referenced by IsCtrlButtonPressed().
IsCtrlButtonPressed()
bool FInputEventState::IsCtrlButtonPressed () const inline
Definition at line 143 of file EditorViewportClient.h.
References InputEvent, IsButtonPressed(), IsCtrlButtonEvent(), EKeys::LeftControl, and EKeys::RightControl.
IsLeftMouseButtonPressed()
bool FInputEventState::IsLeftMouseButtonPressed () const inline
Definition at line 132 of file EditorViewportClient.h.
References IsButtonPressed(), and EKeys::LeftMouseButton.
IsMiddleMouseButtonPressed()
bool FInputEventState::IsMiddleMouseButtonPressed () const inline
Definition at line 133 of file EditorViewportClient.h.
References IsButtonPressed(), and EKeys::MiddleMouseButton.
IsMouseButtonEvent()
bool FInputEventState::IsMouseButtonEvent () const inline
Definition at line 136 of file EditorViewportClient.h.
References Key, EKeys::LeftMouseButton, EKeys::MiddleMouseButton, and EKeys::RightMouseButton.
IsRightMouseButtonPressed()
bool FInputEventState::IsRightMouseButtonPressed () const inline
Definition at line 134 of file EditorViewportClient.h.
References IsButtonPressed(), and EKeys::RightMouseButton.
IsShiftButtonEvent()
bool FInputEventState::IsShiftButtonEvent () const inline
Definition at line 128 of file EditorViewportClient.h.
References Key, EKeys::LeftShift, and EKeys::RightShift.
Referenced by IsShiftButtonPressed().
IsShiftButtonPressed()
bool FInputEventState::IsShiftButtonPressed () const inline
Definition at line 142 of file EditorViewportClient.h.
References InputEvent, IsButtonPressed(), IsShiftButtonEvent(), EKeys::LeftShift, and EKeys::RightShift.
IsSpaceBarPressed()
bool FInputEventState::IsSpaceBarPressed () const inline
Definition at line 145 of file EditorViewportClient.h.
References IsButtonPressed(), and EKeys::SpaceBar.
Field Documentation
InputEvent
EInputEvent FInputEventState::InputEvent private
Key event.
Definition at line 153 of file EditorViewportClient.h.
Referenced by FInputEventState(), GetInputEvent(), IsAltButtonPressed(), IsCommandButtonPressed(), IsCtrlButtonPressed(), and IsShiftButtonPressed().
Key
FKey FInputEventState::Key private
Pressed Key.
Definition at line 151 of file EditorViewportClient.h.
Referenced by FInputEventState(), GetKey(), IsAltButtonEvent(), IsCommandButtonEvent(), IsCtrlButtonEvent(), IsMouseButtonEvent(), and IsShiftButtonEvent().
Viewport
FViewport* FInputEventState::Viewport private
Viewport the event was sent to.
Definition at line 149 of file EditorViewportClient.h.
Referenced by FInputEventState(), GetViewport(), and IsButtonPressed().
The documentation for this struct was generated from the following file:
Editor/UnrealEd/Public/EditorViewportClient.h