Unreal Engine 5.6 C++ API: FAnalogNavigationKey Struct Reference
FAnalogNavigationKey Struct Reference
#include "NavigationConfig.h"
Public Member Functions
FAnalogNavigationKey (const FKey &InKey, const EUINavigation InNavDir)
bool operator== (const FAnalogNavigationKey &Rhs) const
Data Fields
FKey AnalogKey
EUINavigation NavigationDir
Friends
uint32 GetTypeHash (const FAnalogNavigationKey &InAnalogNavKey)
Detailed Description
Definition at line 14 of file NavigationConfig.h.
Constructor & Destructor Documentation
FAnalogNavigationKey()
FAnalogNavigationKey::FAnalogNavigationKey (const FKey & InKey, const EUINavigation InNavDir) inline
Definition at line 19 of file NavigationConfig.h.
References AnalogKey, and NavigationDir.
Referenced by GetTypeHash, and operator==().
Member Function Documentation
operator==()
bool FAnalogNavigationKey::operator== (const FAnalogNavigationKey & Rhs) const inline
Definition at line 24 of file NavigationConfig.h.
References FAnalogNavigationKey(), AnalogKey, and NavigationDir.
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FAnalogNavigationKey & InAnalogNavKey) friend
Definition at line 30 of file NavigationConfig.h.
References FAnalogNavigationKey(), AnalogKey, GetTypeHash, HashCombine(), and NavigationDir.
Referenced by GetTypeHash.
Field Documentation
AnalogKey
FKey FAnalogNavigationKey::AnalogKey
Definition at line 16 of file NavigationConfig.h.
Referenced by FAnalogNavigationKey(), GetTypeHash, and operator==().
NavigationDir
EUINavigation FAnalogNavigationKey::NavigationDir
Definition at line 17 of file NavigationConfig.h.
Referenced by FAnalogNavigationKey(), GetTypeHash, and operator==().
The documentation for this struct was generated from the following file:
Runtime/Slate/Public/Framework/Application/NavigationConfig.h