Unreal Engine 5.6 C++ API: UE::Geometry::FClusterKMeans Struct Reference
UE::Geometry::FClusterKMeans Struct Reference
#include "KMeans.h"
Public Member Functions
template<typename TVectorType = FVector, bool bRunParallel = false>
int32 ComputeClusters (TArrayView< const TVectorType > PointsToCluster, int32 NumClusters, TArrayView< const TVectorType > InitialCenters=TArrayView< const TVectorType >(), TArray< TVectorType > *OutClusterCenters=nullptr)
Compute the K-Means clustering of FVector points.
void GEOMETRYCORE_API GetClusters (TArray< TArray< int32 > > &OutClusters)
template<typename TVectorType = FVector>
void GetUniformSpacedInitialCenters (TArrayView< const TVectorType > PointsToCluster, int32 NumClusters, TArray< TVectorType > &OutCenters)
Helper function to generate (approximately) uniform-spaced initial clusters centers, which can be passed to ComputeClusters.
Data Fields
TArray< int32 > ClusterIDs
Outputs.
TArray< std::atomic< int32 > > ClusterSizes
int32 MaxIterations = 500
Parameters.
int32 RandomSeed = 0
Detailed Description
Definition at line 123 of file KMeans.h.
Member Function Documentation
ComputeClusters()
template<typename TVectorType = FVector, bool bRunParallel = false> int32 UE::Geometry::FClusterKMeans::ComputeClusters (TArrayView< const TVectorType > PointsToCluster, int32 NumClusters, TArrayView< const TVectorType > InitialCenters = TArrayView<const TVectorType>(), TArray< TVectorType > * OutClusterCenters = nullptr) inline
Compute the K-Means clustering of FVector points.
Parameters
PointsToCluster Points to partition into clusters
NumClusters Target number of clusters to create, if InitialCenters is not provided
InitialCenters If non-empty, these positions will be used to initialize the cluster locations
OutClusterCenters If non-null, will be filled with the cluster centers
bRunParallel Runs a parallel algorithm (faster) if possible. The output might be non-deterministic when running in parallel
Returns
number of clusters found
Definition at line 152 of file KMeans.h.
References UE::Geometry::TClusterCenterArray< TVectorType, bUseAtomicType >::Accumulate(), TArray< InElementType, InAllocatorType >::Add(), TArray< InElementType, InAllocatorType >::Append(), UE::Geometry::TClusterCenterArray< TVectorType, bUseAtomicType >::Assign(), checkSlow, ClusterIDs, ClusterSizes, UE::Geometry::DistanceSquared(), UE::Geometry::TClusterCenterArray< TVectorType, bUseAtomicType >::DivideBy(), TArrayView< InElementType, InSizeType >::IsEmpty(), FMath::Max, MaxIterations, FMath::Min, No, TArray< InElementType, InAllocatorType >::Num(), TArrayView< InElementType, InSizeType >::Num(), ParallelFor(), PLATFORM_SUPPORT_FLOATING_INTERLOCKED_ADD, Point, RandomSeed, RandomStream, TArray< InElementType, InAllocatorType >::RemoveAtSwap(), UE::Geometry::TClusterCenterArray< TVectorType, bUseAtomicType >::RemoveAtSwap(), TArray< InElementType, InAllocatorType >::Reserve(), TArray< InElementType, InAllocatorType >::Reset(), TArray< InElementType, InAllocatorType >::SetNumUninitialized(), UE::Geometry::TClusterCenterArray< TVectorType, bUseAtomicType >::SetNumZeroed(), and Swap.
GetClusters()
void GEOMETRYCORE_API UE::Geometry::FClusterKMeans::GetClusters (TArray< TArray< int32 > > & OutClusters)
GetUniformSpacedInitialCenters()
template<typename TVectorType = FVector> void UE::Geometry::FClusterKMeans::GetUniformSpacedInitialCenters (TArrayView< const TVectorType > PointsToCluster, int32 NumClusters, TArray< TVectorType > & OutCenters) inline
Helper function to generate (approximately) uniform-spaced initial clusters centers, which can be passed to ComputeClusters.
Definition at line 350 of file KMeans.h.
References TArray< InElementType, InAllocatorType >::Add(), UE::Geometry::FPriorityOrderPoints::ComputeUniformSpaced(), FMath::Min, TArray< InElementType, InAllocatorType >::Num(), UE::Geometry::FPriorityOrderPoints::Order, and TArray< InElementType, InAllocatorType >::Reset().
Field Documentation
ClusterIDs
TArray<int32> UE::Geometry::FClusterKMeans::ClusterIDs
Outputs.
Definition at line 136 of file KMeans.h.
Referenced by ComputeClusters().
ClusterSizes
TArray<std::atomic<int32> > UE::Geometry::FClusterKMeans::ClusterSizes
Definition at line 139 of file KMeans.h.
Referenced by ComputeClusters().
MaxIterations
int32 UE::Geometry::FClusterKMeans::MaxIterations = 500
Parameters.
Definition at line 128 of file KMeans.h.
Referenced by ComputeClusters().
RandomSeed
int32 UE::Geometry::FClusterKMeans::RandomSeed = 0
Definition at line 131 of file KMeans.h.
Referenced by ComputeClusters().
The documentation for this struct was generated from the following file:
Runtime/GeometryCore/Public/Clustering/KMeans.h