Unreal Engine 5.6 C++ API: FSavedCue Struct Reference
FSavedCue Struct Reference
#include "NetworkPredictionCues.h"
Public Member Functions
FSavedCue (bool bInNetConfirmed)
FSavedCue (const FNetSimCueTypeId &InId, const int32 &InFrame, const int32 &InTime, const bool &bInAllowRollback, const bool &bInNetConfirmed, const bool &bInResimulates, FNetSimCueWrapperBase *Cue)
FSavedCue (const FSavedCue &)=delete
FSavedCue (FSavedCue &&)=default
FString GetDebugName () const
bool NetIdentical (FSavedCue &OtherCue) const
template<typename TCue>
bool NetIdentical (TCue &OtherCue) const
void NetSerialize (FArchive &Ar, const bool bSerializeFrameNumber)
FSavedCue & operator= (const FSavedCue &)=delete
FSavedCue & operator= (FSavedCue &&)=default
Data Fields
bool bAllowRollback = false
bool bDispatched = false
bool bNetConfirmed = false
bool bPendingResimulateRollback = false
bool bResimulates = false
FNetSimCueCallbacks Callbacks
TUniquePtr< FNetSimCueWrapperBase > CueInstance
int32 Frame = INDEX_NONE
FNetSimCueTypeId ID = 0
ENetSimCueReplicationTarget ReplicationTarget
int32 Time = 0
Detailed Description
Definition at line 273 of file NetworkPredictionCues.h.
Constructor & Destructor Documentation
FSavedCue() [1/4]
FSavedCue::FSavedCue (bool bInNetConfirmed) inline
Definition at line 275 of file NetworkPredictionCues.h.
References bNetConfirmed.
Referenced by FSavedCue(), FSavedCue(), NetIdentical(), operator=(), and operator=().
FSavedCue() [2/4]
FSavedCue::FSavedCue (const FSavedCue &) delete
References FSavedCue().
FSavedCue() [3/4]
FSavedCue::FSavedCue (FSavedCue &&) default
References FSavedCue().
FSavedCue() [4/4]
FSavedCue::FSavedCue (const FNetSimCueTypeId & InId, const int32 & InFrame, const int32 & InTime, const bool & bInAllowRollback, const bool & bInNetConfirmed, const bool & bInResimulates, FNetSimCueWrapperBase * Cue) inline
Definition at line 283 of file NetworkPredictionCues.h.
References bAllowRollback, bNetConfirmed, bResimulates, Cue, CueInstance, Frame, ID, InTime, ReplicationTarget, and Time.
Member Function Documentation
GetDebugName()
FString FSavedCue::GetDebugName () const inline
Definition at line 340 of file NetworkPredictionCues.h.
References Frame, FGlobalCueTypeTable::Get(), GetTypeName(), ID, INT64_FMT, TEXT, and Time.
Referenced by TNetSimCueDispatcher< ModelDef >::DispatchCueRecord(), and TNetSimCueDispatcher< ModelDef >::NetRecvSavedCues().
NetIdentical() [1/2]
bool FSavedCue::NetIdentical (FSavedCue & OtherCue) const inline
Definition at line 327 of file NetworkPredictionCues.h.
References FSavedCue(), FNetSimCueWrapperBase::CueData(), CueInstance, and ID.
Referenced by TNetSimCueDispatcher< ModelDef >::NetRecvSavedCues().
NetIdentical() [2/2]
template<typename TCue> bool FSavedCue::NetIdentical (TCue & OtherCue) const inline
Definition at line 334 of file NetworkPredictionCues.h.
References CueInstance, and ID.
NetSerialize()
void FSavedCue::NetSerialize (FArchive & Ar, const bool bSerializeFrameNumber) inline
Definition at line 289 of file NetworkPredictionCues.h.
References Ar, check, CueInstance, Frame, FGlobalCueTypeTable::Get(), ID, FGlobalCueTypeTable::IsRegisterationTypeInfoDirty(), npCheckSlow, ReplicationTarget, and Time.
Referenced by TNetSimCueDispatcher< ModelDef >::NetRecvSavedCues().
operator=() [1/2]
FSavedCue & FSavedCue::operator= (const FSavedCue &) delete
References FSavedCue().
operator=() [2/2]
FSavedCue & FSavedCue::operator= (FSavedCue &&) default
References FSavedCue().
Field Documentation
bAllowRollback
bool FSavedCue::bAllowRollback = false
Definition at line 352 of file NetworkPredictionCues.h.
Referenced by FSavedCue().
bDispatched
bool FSavedCue::bDispatched = false
Definition at line 351 of file NetworkPredictionCues.h.
Referenced by TNetSimCueDispatcher< ModelDef >::DispatchCueRecord().
bNetConfirmed
bool FSavedCue::bNetConfirmed = false
Definition at line 353 of file NetworkPredictionCues.h.
Referenced by FSavedCue(), FSavedCue(), TNetSimCueDispatcher< ModelDef >::DispatchCueRecord(), and TNetSimCueDispatcher< ModelDef >::NetRecvSavedCues().
bPendingResimulateRollback
bool FSavedCue::bPendingResimulateRollback = false
Definition at line 356 of file NetworkPredictionCues.h.
Referenced by TNetSimCueDispatcher< ModelDef >::DispatchCueRecord().
bResimulates
bool FSavedCue::bResimulates = false
Definition at line 355 of file NetworkPredictionCues.h.
Referenced by FSavedCue().
Callbacks
FNetSimCueCallbacks FSavedCue::Callbacks
Definition at line 349 of file NetworkPredictionCues.h.
Referenced by TNetSimCueDispatcher< ModelDef >::DispatchCueRecord().
CueInstance
TUniquePtr<FNetSimCueWrapperBase> FSavedCue::CueInstance
Definition at line 348 of file NetworkPredictionCues.h.
Referenced by FSavedCue(), TCueDispatchTable< TCueHandler >::Dispatch(), NetIdentical(), NetIdentical(), and NetSerialize().
Frame
int32 FSavedCue::Frame = INDEX_NONE
Definition at line 346 of file NetworkPredictionCues.h.
Referenced by FSavedCue(), TNetSimCueDispatcher< ModelDef >::DispatchCueRecord(), GetDebugName(), TNetSimCueDispatcher< ModelDef >::NetRecvSavedCues(), and NetSerialize().
ID
FNetSimCueTypeId FSavedCue::ID = 0
Definition at line 345 of file NetworkPredictionCues.h.
Referenced by FSavedCue(), TCueDispatchTable< TCueHandler >::Dispatch(), GetDebugName(), NetIdentical(), NetIdentical(), and NetSerialize().
ReplicationTarget
ENetSimCueReplicationTarget FSavedCue::ReplicationTarget
Definition at line 358 of file NetworkPredictionCues.h.
Referenced by FSavedCue(), TNetSimCueDispatcher< ModelDef >::NetRecvSavedCues(), and NetSerialize().
Time
int32 FSavedCue::Time = 0
Definition at line 347 of file NetworkPredictionCues.h.
Referenced by FSavedCue(), TNetSimCueDispatcher< ModelDef >::DispatchCueRecord(), GetDebugName(), TNetSimCueDispatcher< ModelDef >::NetRecvSavedCues(), and NetSerialize().
The documentation for this struct was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/NetworkPrediction/Source/NetworkPrediction/Public/NetworkPredictionCues.h