Unreal Engine 5.6 C++ API: FPooledSyncEvent Struct Reference
FPooledSyncEvent Struct Reference
#include "PooledSyncEvent.h"
Public Member Functions
FPooledSyncEvent (bool bIsManualReset=false)
FPooledSyncEvent (const FPooledSyncEvent &)=delete
FPooledSyncEvent (FPooledSyncEvent &&)=delete
~FPooledSyncEvent ()
operator bool () const
FEvent * operator-> () const
FPooledSyncEvent & operator= (const FPooledSyncEvent &)=delete
FPooledSyncEvent & operator= (FPooledSyncEvent &&)=delete
FPooledSyncEvent & operator= (TYPE_OF_NULLPTR)
Data Fields
FEvent * Event
Detailed Description
Definition at line 8 of file PooledSyncEvent.h.
Constructor & Destructor Documentation
FPooledSyncEvent() [1/3]
FPooledSyncEvent::FPooledSyncEvent (bool bIsManualReset = false) inline explicit
Definition at line 10 of file PooledSyncEvent.h.
References Event, and FGenericPlatformProcess::GetSynchEventFromPool().
Referenced by FPooledSyncEvent(), FPooledSyncEvent(), operator=(), operator=(), and operator=().
~FPooledSyncEvent()
FPooledSyncEvent::~FPooledSyncEvent () inline
Definition at line 14 of file PooledSyncEvent.h.
FPooledSyncEvent() [2/3]
FPooledSyncEvent::FPooledSyncEvent (FPooledSyncEvent &&) delete
References FPooledSyncEvent().
FPooledSyncEvent() [3/3]
FPooledSyncEvent::FPooledSyncEvent (const FPooledSyncEvent &) delete
References FPooledSyncEvent().
Member Function Documentation
operator bool()
FPooledSyncEvent::operator bool () const inline explicit
Definition at line 25 of file PooledSyncEvent.h.
References Event.
operator->()
FEvent * FPooledSyncEvent::operator-> () const inline
Definition at line 30 of file PooledSyncEvent.h.
References Event.
operator=() [1/3]
FPooledSyncEvent & FPooledSyncEvent::operator= (const FPooledSyncEvent &) delete
References FPooledSyncEvent().
operator=() [2/3]
FPooledSyncEvent & FPooledSyncEvent::operator= (FPooledSyncEvent &&) delete
References FPooledSyncEvent().
operator=() [3/3]
FPooledSyncEvent & FPooledSyncEvent::operator= (TYPE_OF_NULLPTR) inline
Definition at line 35 of file PooledSyncEvent.h.
References FPooledSyncEvent(), Event, and FGenericPlatformProcess::ReturnSynchEventToPool().
Field Documentation
Event
FEvent* FPooledSyncEvent::Event
Definition at line 45 of file PooledSyncEvent.h.
Referenced by FPooledSyncEvent(), operator bool(), operator->(), and operator=().
The documentation for this struct was generated from the following file:
Runtime/Core/Public/HAL/PooledSyncEvent.h