Unreal Engine 5.6 C++ API: UE::Anim::FAttributeBlendData::TSingleRawIterator Struct Reference
UE::Anim::FAttributeBlendData::TSingleRawIterator Struct Reference
#include "AttributeBlendData.h"
Public Member Functions
EAdditiveAnimationType GetAdditiveType () const
const float GetBoneWeight () const
Returns (bone level) weight value for the unique attribute its bone and container.
const FAttributeId & GetIdentifier () const
Returns the identifier for the current attribute set.
const uint8 * GetValuePtr () const
Return the value for the currently indexed unique attribute.
const float GetWeight () const
Returns (container level) weight value for the unique attribute its container.
bool IsFilteredBlend () const
bool IsHighestBoneWeighted () const
Returns whether or not the unique attribute its (bone level) weight is the highest across the containers.
bool Next ()
Cycle through to next unique attribute, returns false if the end was reached.
Protected Member Functions
TSingleRawIterator (const FAttributeBlendData &InData, const TArray< FUniqueAttribute > &InAttributes)
Protected Attributes
TArrayView< const FUniqueAttribute > AttributesView
int32 CurrentIndex
const FAttributeBlendData & Data
Outer object that creates this.
Friends
struct FAttributeBlendData
Detailed Description
Definition at line 467 of file AttributeBlendData.h.
Constructor & Destructor Documentation
TSingleRawIterator()
UE::Anim::FAttributeBlendData::TSingleRawIterator::TSingleRawIterator (const FAttributeBlendData & InData, const TArray< FUniqueAttribute > & InAttributes) inline protected
Definition at line 471 of file AttributeBlendData.h.
References AttributesView, CurrentIndex, Data, and FAttributeBlendData.
Member Function Documentation
GetAdditiveType()
EAdditiveAnimationType UE::Anim::FAttributeBlendData::TSingleRawIterator::GetAdditiveType () const inline
Definition at line 522 of file AttributeBlendData.h.
References Data.
GetBoneWeight()
const float UE::Anim::FAttributeBlendData::TSingleRawIterator::GetBoneWeight () const inline
Returns (bone level) weight value for the unique attribute its bone and container.
Definition at line 497 of file AttributeBlendData.h.
References AttributesView, check, CurrentIndex, and Data.
GetIdentifier()
const FAttributeId & UE::Anim::FAttributeBlendData::TSingleRawIterator::GetIdentifier () const inline
Returns the identifier for the current attribute set.
Definition at line 516 of file AttributeBlendData.h.
References AttributesView, check, and CurrentIndex.
Referenced by UE::Anim::FNonBlendableAttributeBlendOperator::Accumulate(), UE::Anim::FNonBlendableAttributeBlendOperator::ConvertToAdditive(), and UE::Anim::FNonBlendableAttributeBlendOperator::Override().
GetValuePtr()
const uint8 * UE::Anim::FAttributeBlendData::TSingleRawIterator::GetValuePtr () const inline
Return the value for the currently indexed unique attribute.
Definition at line 481 of file AttributeBlendData.h.
References AttributesView, check, and CurrentIndex.
Referenced by UE::Anim::FNonBlendableAttributeBlendOperator::Accumulate(), UE::Anim::FNonBlendableAttributeBlendOperator::ConvertToAdditive(), and UE::Anim::FNonBlendableAttributeBlendOperator::Override().
GetWeight()
const float UE::Anim::FAttributeBlendData::TSingleRawIterator::GetWeight () const inline
Returns (container level) weight value for the unique attribute its container.
Definition at line 488 of file AttributeBlendData.h.
References AttributesView, check, CurrentIndex, and Data.
Referenced by UE::Anim::FNonBlendableAttributeBlendOperator::Accumulate(), and UE::Anim::FNonBlendableAttributeBlendOperator::ConvertToAdditive().
IsFilteredBlend()
bool UE::Anim::FAttributeBlendData::TSingleRawIterator::IsFilteredBlend () const inline
Definition at line 527 of file AttributeBlendData.h.
References Data.
IsHighestBoneWeighted()
bool UE::Anim::FAttributeBlendData::TSingleRawIterator::IsHighestBoneWeighted () const inline
Returns whether or not the unique attribute its (bone level) weight is the highest across the containers.
Definition at line 506 of file AttributeBlendData.h.
References AttributesView, check, CurrentIndex, and Data.
Next()
bool UE::Anim::FAttributeBlendData::TSingleRawIterator::Next () inline
Cycle through to next unique attribute, returns false if the end was reached.
Definition at line 474 of file AttributeBlendData.h.
References AttributesView, and CurrentIndex.
Referenced by UE::Anim::FNonBlendableAttributeBlendOperator::Accumulate(), UE::Anim::FNonBlendableAttributeBlendOperator::ConvertToAdditive(), and UE::Anim::FNonBlendableAttributeBlendOperator::Override().
Friends And Related Symbol Documentation
FAttributeBlendData
friend struct FAttributeBlendData friend
Definition at line 469 of file AttributeBlendData.h.
References FAttributeBlendData.
Referenced by TSingleRawIterator(), and FAttributeBlendData.
Field Documentation
AttributesView
TArrayView<const FUniqueAttribute> UE::Anim::FAttributeBlendData::TSingleRawIterator::AttributesView protected
Definition at line 535 of file AttributeBlendData.h.
Referenced by TSingleRawIterator(), GetBoneWeight(), GetIdentifier(), GetValuePtr(), GetWeight(), IsHighestBoneWeighted(), and Next().
CurrentIndex
int32 UE::Anim::FAttributeBlendData::TSingleRawIterator::CurrentIndex protected
Definition at line 536 of file AttributeBlendData.h.
Referenced by TSingleRawIterator(), GetBoneWeight(), GetIdentifier(), GetValuePtr(), GetWeight(), IsHighestBoneWeighted(), and Next().
Data
const FAttributeBlendData& UE::Anim::FAttributeBlendData::TSingleRawIterator::Data protected
Outer object that creates this.
Definition at line 534 of file AttributeBlendData.h.
Referenced by TSingleRawIterator(), GetAdditiveType(), GetBoneWeight(), GetWeight(), IsFilteredBlend(), and IsHighestBoneWeighted().
The documentation for this struct was generated from the following file:
Runtime/Engine/Classes/Animation/AttributeBlendData.h