Unreal Engine 5.6 C++ API: UE::SequenceNavigator::FNavigationToolItemId Struct Reference
UE::SequenceNavigator::FNavigationToolItemId Struct Reference
Struct to identify an item in the Navigation Tool.
#include "NavigationToolItemId.h"
Public Member Functions
FNavigationToolItemId ()=default
Default Ctor.
FNavigationToolItemId (const FNavigationToolItemId &Other)
FNavigationToolItemId (const FNavigationToolItemPtr &InParentItem, const INavigationToolItem &InItemProxy)
Ctor used for making the Item Id for an Item Proxy under the given Parent Item.
FNavigationToolItemId (const FNavigationToolItemPtr &InParentItem, const INavigationToolItemProxyFactory &InItemProxyFactory)
Ctor used for making the Item Id for an item proxy that will be under the given Parent Item.
FNavigationToolItemId (const FNavigationToolItemPtr &InParentItem, const UMovieSceneSequence *const InSequence, const UMovieSceneSection *const InSection=nullptr, const int32 InSectionIndex=0, const FString &InReferenceId=FString())
Ctor used for making the Item Id for most sequence items.
FNavigationToolItemId (const FString &InUniqueId)
More flexible option to just specify the string directly.
FNavigationToolItemId (const UE::Sequencer::FViewModelPtr &InViewModel)
Ctor used for making the Item Id from a Sequencer view model.
FNavigationToolItemId (const UObject *InObject, const FNavigationToolItemPtr &InReferencingItem, const FString &InReferencingId)
Ctor used for Objects that are expected to appear multiple times in the Navigation Tool (e.g.
FNavigationToolItemId (FNavigationToolItemId &&Other) noexcept
FString GetStringId () const
bool IsValidId () const
Returns whether this Id has a cached hash (i.e.
FNavigationToolItemId & operator= (const FNavigationToolItemId &Other)
FNavigationToolItemId & operator= (FNavigationToolItemId &&Other) noexcept
bool operator== (const FNavigationToolItemId &Other) const
Static Public Member Functions
static void AddSeparatedSegment (FString &OutString, const FString &InSegment)
static FString GetObjectPath (const UObject *const InObject)
Static Public Attributes
static FNavigationToolItemId RootId
static constexpr const TCHAR * Separator = TEXT(",")
Private Member Functions
void CalculateTypeHash ()
void ConstructId (const FNavigationToolItemPtr &InParentItem, const UMovieSceneSequence *const InSequence, const UMovieSceneSection *const InSection=nullptr, const int32 InSectionIndex=0, const FString &InReferenceId=FString())
Constructs an Item Id for most sequence items.
Private Attributes
bool bHasCachedHash = false
uint32 CachedHash = 0
FString Id
Friends
uint32 GetTypeHash (const FNavigationToolItemId &InItemId)
Detailed Description
Struct to identify an item in the Navigation Tool.
Definition at line 19 of file NavigationToolItemId.h.
Constructor & Destructor Documentation
FNavigationToolItemId() [1/9]
UE::SequenceNavigator::FNavigationToolItemId::FNavigationToolItemId () default
Default Ctor.
Does not run any CalculateTypeHash so this instance remains invalid
Referenced by FNavigationToolItemId(), FNavigationToolItemId(), GetTypeHash, operator=(), operator=(), and operator==().
FNavigationToolItemId() [2/9]
UE::SequenceNavigator::FNavigationToolItemId::FNavigationToolItemId (const FString & InUniqueId)
More flexible option to just specify the string directly.
Could be used for folders (e.g. for a nested folder C could be "A/B/C"
FNavigationToolItemId() [3/9]
UE::SequenceNavigator::FNavigationToolItemId::FNavigationToolItemId (const UObject * InObject, const FNavigationToolItemPtr & InReferencingItem, const FString & InReferencingId)
Ctor used for Objects that are expected to appear multiple times in the Navigation Tool (e.g.
a Material Ref)
Example Id #1: [Component Path], [Full Path of Material Asset], [Slot Index] "/Game/World.World:PersistentLevel.StaticMeshActor_0.StaticMeshComponent,/Game/Materials/M_TestMaterial.M_TestMaterial,[Slot 0]"
Example Id #2: [Component Path], [Material Instance Dynamic Path], [Slot Index] "/Game/World.World:PersistentLevel.StaticMeshActor_0.StaticMeshComponent,/Game/World.World:PersistentLevel.StaticMeshActor_0.StaticMeshComponent.MaterialInstanceDynamic_0,[Slot 0]"
Parameters
InObject The Object being referenced multiple times (e.g. a Material)
InReferencingItem The Item holding a reference to the object (e.g. a Primitive Comp referencing a Material)
InReferencingId The Id to differentiate this reference from other references within the same object (e.g. can be slot or property name)
FNavigationToolItemId() [4/9]
UE::SequenceNavigator::FNavigationToolItemId::FNavigationToolItemId (const FNavigationToolItemPtr & InParentItem, const INavigationToolItemProxyFactory & InItemProxyFactory)
Ctor used for making the Item Id for an item proxy that will be under the given Parent Item.
Used when the actual Item Proxy is not created yet, but know it's factory and want to know whether the item proxy already exists
Parameters
InParentItem The parent item holding the item proxy
InItemProxyFactory The factory responsible for creating the item proxy
FNavigationToolItemId() [5/9]
UE::SequenceNavigator::FNavigationToolItemId::FNavigationToolItemId (const FNavigationToolItemPtr & InParentItem, const INavigationToolItem & InItemProxy)
Ctor used for making the Item Id for an Item Proxy under the given Parent Item.
Parameters
InParentItem The parent item holding the item proxy
InItemProxy The item proxy under the parent item
FNavigationToolItemId() [6/9]
UE::SequenceNavigator::FNavigationToolItemId::FNavigationToolItemId (const FNavigationToolItemPtr & InParentItem, const UMovieSceneSequence *const InSequence, const UMovieSceneSection *const InSection = nullptr, const int32 InSectionIndex = 0, const FString & InReferenceId = FString())
Ctor used for making the Item Id for most sequence items.
Parameters
InParentItem The parent item holding the item proxy
InSequence The parent sequence object
InSection The parent section this sequence belongs to, if any
InSectionIndex The parent section index, if any. Should be specified if InSection is used.
InReferenceId The optional additional reference string
FNavigationToolItemId() [7/9]
UE::SequenceNavigator::FNavigationToolItemId::FNavigationToolItemId (const UE::Sequencer::FViewModelPtr & InViewModel)
Ctor used for making the Item Id from a Sequencer view model.
Parameters
InViewModel The view model to construct the Id from
FNavigationToolItemId() [8/9]
UE::SequenceNavigator::FNavigationToolItemId::FNavigationToolItemId (const FNavigationToolItemId & Other)
References FNavigationToolItemId(), and Other.
FNavigationToolItemId() [9/9]
UE::SequenceNavigator::FNavigationToolItemId::FNavigationToolItemId (FNavigationToolItemId && Other) noexcept
References FNavigationToolItemId(), and Other.
Member Function Documentation
AddSeparatedSegment()
void UE::SequenceNavigator::FNavigationToolItemId::AddSeparatedSegment (FString & OutString, const FString & InSegment) static
CalculateTypeHash()
void UE::SequenceNavigator::FNavigationToolItemId::CalculateTypeHash () private
ConstructId()
void UE::SequenceNavigator::FNavigationToolItemId::ConstructId (const FNavigationToolItemPtr & InParentItem, const UMovieSceneSequence *const InSequence, const UMovieSceneSection *const InSection = nullptr, const int32 InSectionIndex = 0, const FString & InReferenceId = FString()) private
Constructs an Item Id for most sequence items.
Parameters
InParentItem The parent item holding the item proxy
InSequence The parent sequence object
InSection The parent section this sequence belongs to, if any
InSectionIndex The parent section index, if any. Should be specified if InSection is used.
InReferenceId The optional additional reference string
GetObjectPath()
FString UE::SequenceNavigator::FNavigationToolItemId::GetObjectPath (const UObject *const InObject) static
GetStringId()
FString UE::SequenceNavigator::FNavigationToolItemId::GetStringId () const
IsValidId()
bool UE::SequenceNavigator::FNavigationToolItemId::IsValidId () const
Returns whether this Id has a cached hash (i.e.
ran any ctor except the default one)
operator=() [1/2]
FNavigationToolItemId & UE::SequenceNavigator::FNavigationToolItemId::operator= (const FNavigationToolItemId & Other)
References FNavigationToolItemId(), and Other.
operator=() [2/2]
FNavigationToolItemId & UE::SequenceNavigator::FNavigationToolItemId::operator= (FNavigationToolItemId && Other) noexcept
References FNavigationToolItemId(), and Other.
operator==()
bool UE::SequenceNavigator::FNavigationToolItemId::operator== (const FNavigationToolItemId & Other) const
References FNavigationToolItemId(), and Other.
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FNavigationToolItemId & InItemId) friend
Definition at line 99 of file NavigationToolItemId.h.
References FNavigationToolItemId(), and CachedHash.
Field Documentation
bHasCachedHash
bool UE::SequenceNavigator::FNavigationToolItemId::bHasCachedHash = false private
Definition at line 129 of file NavigationToolItemId.h.
CachedHash
uint32 UE::SequenceNavigator::FNavigationToolItemId::CachedHash = 0 private
Definition at line 128 of file NavigationToolItemId.h.
Referenced by GetTypeHash.
Id
FString UE::SequenceNavigator::FNavigationToolItemId::Id private
Definition at line 126 of file NavigationToolItemId.h.
RootId
FNavigationToolItemId UE::SequenceNavigator::FNavigationToolItemId::RootId static
Definition at line 25 of file NavigationToolItemId.h.
Referenced by UE::SequenceNavigator::INavigationToolItem::GetParents().
Separator
const TCHAR* UE::SequenceNavigator::FNavigationToolItemId::Separator = TEXT(",") static constexpr
Definition at line 27 of file NavigationToolItemId.h.
The documentation for this struct was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Experimental/SequenceNavigator/Source/SequenceNavigator/Public/Items/NavigationToolItemId.h