Unreal Engine 5.6 C++ API: TPanelChildren< SlotType >::FScopedWidgetSlotArguments Struct Reference
TPanelChildren< SlotType >::FScopedWidgetSlotArguments Struct Reference final
At the end of the scope a slot will be constructed and added to the FChildren.
#include "Children.h"
Public Member Functions
FScopedWidgetSlotArguments (const FScopedWidgetSlotArguments &)=delete
FScopedWidgetSlotArguments (FScopedWidgetSlotArguments &&)=default
FScopedWidgetSlotArguments (TUniquePtr< SlotType > InSlot, TPanelChildren< SlotType > &InChildren, int32 InIndex)
FScopedWidgetSlotArguments (TUniquePtr< SlotType > InSlot, TPanelChildren< SlotType > &InChildren, int32 InIndex, TFunction< void(const SlotType *, int32)> OnAdded)
~FScopedWidgetSlotArguments ()
FScopedWidgetSlotArguments & operator= (const FScopedWidgetSlotArguments &)=delete
FScopedWidgetSlotArguments & operator= (FScopedWidgetSlotArguments &&)=default
Private Attributes
TFunction< void(const SlotType *, int32)> Added
TPanelChildren< SlotType > & Children
int32 Index
Detailed Description
template<typename SlotType>
struct TPanelChildren< SlotType >::FScopedWidgetSlotArguments
At the end of the scope a slot will be constructed and added to the FChildren.
Definition at line 665 of file Children.h.
Constructor & Destructor Documentation
FScopedWidgetSlotArguments() [1/4]
template<typename SlotType> TPanelChildren< SlotType >::FScopedWidgetSlotArguments::FScopedWidgetSlotArguments (TUniquePtr< SlotType > InSlot, TPanelChildren< SlotType > & InChildren, int32 InIndex) inline
Definition at line 668 of file Children.h.
References Children, Index, and MoveTemp().
Referenced by FScopedWidgetSlotArguments(), FScopedWidgetSlotArguments(), operator=(), and operator=().
FScopedWidgetSlotArguments() [2/4]
template<typename SlotType> TPanelChildren< SlotType >::FScopedWidgetSlotArguments::FScopedWidgetSlotArguments (TUniquePtr< SlotType > InSlot, TPanelChildren< SlotType > & InChildren, int32 InIndex, TFunction< void(const SlotType *, int32)> OnAdded) inline
Definition at line 674 of file Children.h.
References Added, Children, Index, and MoveTemp().
FScopedWidgetSlotArguments() [3/4]
template<typename SlotType> TPanelChildren< SlotType >::FScopedWidgetSlotArguments::FScopedWidgetSlotArguments (const FScopedWidgetSlotArguments &) delete
References FScopedWidgetSlotArguments().
FScopedWidgetSlotArguments() [4/4]
template<typename SlotType> TPanelChildren< SlotType >::FScopedWidgetSlotArguments::FScopedWidgetSlotArguments (FScopedWidgetSlotArguments &&) default
References FScopedWidgetSlotArguments().
~FScopedWidgetSlotArguments()
template<typename SlotType> TPanelChildren< SlotType >::FScopedWidgetSlotArguments::~FScopedWidgetSlotArguments () inline
Definition at line 687 of file Children.h.
References Added, Children, Index, INDEX_NONE, and MoveTemp().
Member Function Documentation
operator=() [1/2]
template<typename SlotType> FScopedWidgetSlotArguments & TPanelChildren< SlotType >::FScopedWidgetSlotArguments::operator= (const FScopedWidgetSlotArguments &) delete
References FScopedWidgetSlotArguments().
operator=() [2/2]
template<typename SlotType> FScopedWidgetSlotArguments & TPanelChildren< SlotType >::FScopedWidgetSlotArguments::operator= (FScopedWidgetSlotArguments &&) default
References FScopedWidgetSlotArguments().
Field Documentation
Added
template<typename SlotType> TFunction<void(const SlotType*, int32)> TPanelChildren< SlotType >::FScopedWidgetSlotArguments::Added private
Definition at line 709 of file Children.h.
Referenced by FScopedWidgetSlotArguments(), and ~FScopedWidgetSlotArguments().
Children
template<typename SlotType> TPanelChildren<SlotType>& TPanelChildren< SlotType >::FScopedWidgetSlotArguments::Children private
Definition at line 707 of file Children.h.
Referenced by FScopedWidgetSlotArguments(), FScopedWidgetSlotArguments(), and ~FScopedWidgetSlotArguments().
Index
template<typename SlotType> int32 TPanelChildren< SlotType >::FScopedWidgetSlotArguments::Index private
Definition at line 708 of file Children.h.
Referenced by FScopedWidgetSlotArguments(), FScopedWidgetSlotArguments(), and ~FScopedWidgetSlotArguments().
The documentation for this struct was generated from the following file:
Runtime/SlateCore/Public/Layout/Children.h