Unreal Engine 5.6 C++ API: TLargeWorldRenderScalar< TScalar > Struct Template Reference
TLargeWorldRenderScalar< TScalar > Struct Template Reference
#include "LargeWorldRenderPosition.h"
Public Member Functions
TLargeWorldRenderScalar ()
template<typename TInputScalar = double>
TLargeWorldRenderScalar (const TLargeWorldRenderScalar< TInputScalar > &In)
TLargeWorldRenderScalar (double InAbsolute)
TLargeWorldRenderScalar (TScalar InTile, TScalar InOffset)
double GetAbsolute () const
template<typename TResult = float>
TResult GetOffset () const
template<typename TResult = float>
TResult GetTile () const
double GetTileOffset () const
UE_DEPRECATED (5.2, "GetOffsetAsDouble is deprecated, please use GetOffset<double>() instead.") double GetOffsetAsDouble() const
UE_DEPRECATED (5.2, "GetTileAsDouble is deprecated, please use GetTile<double>() instead.") double GetTileAsDouble() const
Static Public Member Functions
static FVector3f GetTileFor (FVector InPosition)
static FORCEINLINE TScalar GetTileSize ()
static FMatrix44f MakeClampedToRelativeWorldMatrix (const FVector Origin, const FMatrix &ToWorld)
static FMatrix MakeClampedToRelativeWorldMatrixDouble (const FVector Origin, const FMatrix &ToWorld)
static FMatrix44f MakeFromRelativeWorldMatrix (const FVector Origin, const FMatrix &FromWorld)
static FMatrix MakeFromRelativeWorldMatrixDouble (const FVector Origin, const FMatrix &FromWorld)
static VectorType MakeQuantizedTile (const FVector &InValue, double InQuantization)
static TScalar MakeQuantizedTile (double InValue, double InQuantization)
static VectorType MakeTile (const FVector &InValue)
static TScalar MakeTile (double InValue)
static FMatrix44f MakeToRelativeWorldMatrix (const FVector Origin, const FMatrix &ToWorld)
static FMatrix MakeToRelativeWorldMatrixDouble (const FVector Origin, const FMatrix &ToWorld)
static FMatrix44f SafeCastMatrix (const FMatrix &Matrix)
Private Types
using VectorType = UE::Math::TVector<TScalar>
Private Member Functions
void Validate (double InAbsolute)
Private Attributes
TScalar Offset
TScalar Tile
Detailed Description
template<typename TScalar>
struct TLargeWorldRenderScalar< TScalar >
Definition at line 17 of file LargeWorldRenderPosition.h.
Member Typedef Documentation
VectorType
template<typename TScalar> using TLargeWorldRenderScalar< TScalar >::VectorType = UE::Math::TVector<TScalar> private
Definition at line 20 of file LargeWorldRenderPosition.h.
Constructor & Destructor Documentation
TLargeWorldRenderScalar() [1/4]
template<typename TScalar> TLargeWorldRenderScalar< TScalar >::TLargeWorldRenderScalar () inline
Definition at line 69 of file LargeWorldRenderPosition.h.
TLargeWorldRenderScalar() [2/4]
template<typename TScalar> TLargeWorldRenderScalar< TScalar >::TLargeWorldRenderScalar (TScalar InTile, TScalar InOffset) inline
Definition at line 70 of file LargeWorldRenderPosition.h.
TLargeWorldRenderScalar() [3/4]
template<typename TScalar> template<typename TInputScalar = double> TLargeWorldRenderScalar< TScalar >::TLargeWorldRenderScalar (const TLargeWorldRenderScalar< TInputScalar > & In) inline explicit
Definition at line 73 of file LargeWorldRenderPosition.h.
TLargeWorldRenderScalar() [4/4]
template<typename TScalar> TLargeWorldRenderScalar< TScalar >::TLargeWorldRenderScalar (double InAbsolute) inline
Definition at line 77 of file LargeWorldRenderPosition.h.
Member Function Documentation
GetAbsolute()
template<typename TScalar> double TLargeWorldRenderScalar< TScalar >::GetAbsolute () const inline
Definition at line 67 of file LargeWorldRenderPosition.h.
GetOffset()
template<typename TScalar> template<typename TResult = float> TResult TLargeWorldRenderScalar< TScalar >::GetOffset () const inline
Definition at line 61 of file LargeWorldRenderPosition.h.
Referenced by TLargeWorldRenderScalar< double >::UE_DEPRECATED().
GetTile()
template<typename TScalar> template<typename TResult = float> TResult TLargeWorldRenderScalar< TScalar >::GetTile () const inline
Definition at line 59 of file LargeWorldRenderPosition.h.
Referenced by TLargeWorldRenderScalar< double >::UE_DEPRECATED().
GetTileFor()
template<typename TScalar> FVector3f TLargeWorldRenderScalar< TScalar >::GetTileFor (FVector InPosition) static
GetTileOffset()
template<typename TScalar> double TLargeWorldRenderScalar< TScalar >::GetTileOffset () const inline
Definition at line 66 of file LargeWorldRenderPosition.h.
Referenced by TLargeWorldRenderScalar< double >::TLargeWorldRenderScalar(), and TLargeWorldRenderScalar< double >::GetAbsolute().
GetTileSize()
template<typename TScalar> FORCEINLINE TScalar TLargeWorldRenderScalar< TScalar >::GetTileSize () inline static
Definition at line 23 of file LargeWorldRenderPosition.h.
Referenced by TLargeWorldRenderScalar< double >::GetTileOffset(), TLargeWorldRenderScalar< double >::MakeQuantizedTile(), and TLargeWorldRenderScalar< double >::MakeTile().
MakeClampedToRelativeWorldMatrix()
template<typename TScalar> FMatrix44f TLargeWorldRenderScalar< TScalar >::MakeClampedToRelativeWorldMatrix (const FVector Origin, const FMatrix & ToWorld) static
MakeClampedToRelativeWorldMatrixDouble()
template<typename TScalar> FMatrix TLargeWorldRenderScalar< TScalar >::MakeClampedToRelativeWorldMatrixDouble (const FVector Origin, const FMatrix & ToWorld) static
MakeFromRelativeWorldMatrix()
template<typename TScalar> FMatrix44f TLargeWorldRenderScalar< TScalar >::MakeFromRelativeWorldMatrix (const FVector Origin, const FMatrix & FromWorld) static
MakeFromRelativeWorldMatrixDouble()
template<typename TScalar> FMatrix TLargeWorldRenderScalar< TScalar >::MakeFromRelativeWorldMatrixDouble (const FVector Origin, const FMatrix & FromWorld) static
MakeQuantizedTile() [1/2]
template<typename TScalar> VectorType TLargeWorldRenderScalar< TScalar >::MakeQuantizedTile (const FVector & InValue, double InQuantization) inline static
Definition at line 45 of file LargeWorldRenderPosition.h.
MakeQuantizedTile() [2/2]
template<typename TScalar> TScalar TLargeWorldRenderScalar< TScalar >::MakeQuantizedTile (double InValue, double InQuantization) inline static
Definition at line 35 of file LargeWorldRenderPosition.h.
Referenced by TLargeWorldRenderScalar< double >::MakeQuantizedTile().
MakeTile() [1/2]
template<typename TScalar> VectorType TLargeWorldRenderScalar< TScalar >::MakeTile (const FVector & InValue) inline static
Definition at line 40 of file LargeWorldRenderPosition.h.
MakeTile() [2/2]
template<typename TScalar> TScalar TLargeWorldRenderScalar< TScalar >::MakeTile (double InValue) inline static
Definition at line 30 of file LargeWorldRenderPosition.h.
Referenced by TLargeWorldRenderScalar< double >::TLargeWorldRenderScalar(), and TLargeWorldRenderScalar< double >::MakeTile().
MakeToRelativeWorldMatrix()
template<typename TScalar> FMatrix44f TLargeWorldRenderScalar< TScalar >::MakeToRelativeWorldMatrix (const FVector Origin, const FMatrix & ToWorld) static
MakeToRelativeWorldMatrixDouble()
template<typename TScalar> FMatrix TLargeWorldRenderScalar< TScalar >::MakeToRelativeWorldMatrixDouble (const FVector Origin, const FMatrix & ToWorld) static
SafeCastMatrix()
template<typename TScalar> FMatrix44f TLargeWorldRenderScalar< TScalar >::SafeCastMatrix (const FMatrix & Matrix) static
UE_DEPRECATED() [1/2]
template<typename TScalar> TLargeWorldRenderScalar< TScalar >::UE_DEPRECATED (5. 2, "GetOffsetAsDouble is deprecated, please use GetOffset< double >() instead.") const inline
Definition at line 64 of file LargeWorldRenderPosition.h.
UE_DEPRECATED() [2/2]
template<typename TScalar> TLargeWorldRenderScalar< TScalar >::UE_DEPRECATED (5. 2, "GetTileAsDouble is deprecated, please use GetTile< double >() instead.") const inline
Definition at line 62 of file LargeWorldRenderPosition.h.
Validate()
template<typename TScalar> void TLargeWorldRenderScalar< TScalar >::Validate (double InAbsolute) private
Referenced by TLargeWorldRenderScalar< double >::TLargeWorldRenderScalar().
Field Documentation
Offset
template<typename TScalar> TScalar TLargeWorldRenderScalar< TScalar >::Offset private
Definition at line 89 of file LargeWorldRenderPosition.h.
Tile
template<typename TScalar> TScalar TLargeWorldRenderScalar< TScalar >::Tile private
Definition at line 88 of file LargeWorldRenderPosition.h.
The documentation for this struct was generated from the following file:
Runtime/Core/Public/Misc/LargeWorldRenderPosition.h