Unreal Engine 5.6 C++ API: UE::MovieScene::FFloatPropertyTraits Struct Reference
UE::MovieScene::FFloatPropertyTraits Struct Reference
#include "MovieSceneTracksComponentTypes.h"
Public Types
using CustomAccessorStorageType = float
using FloatTraitsImpl = TDirectPropertyTraits<float>
using MetaDataType = TPropertyMetaData<>
using StorageType = double
using TraitsType = FFloatPropertyTraits
Static Public Member Functions
static void GetObjectPropertyValue (const UObject *InObject, const FCustomPropertyAccessor &BaseCustomAccessor, double &OutValue)
static void GetObjectPropertyValue (const UObject *InObject, const FName &PropertyPath, double &OutValue)
static void GetObjectPropertyValue (const UObject *InObject, FTrackInstancePropertyBindings *PropertyBindings, double &OutValue)
static void GetObjectPropertyValue (const UObject *InObject, uint16 PropertyOffset, double &OutValue)
static void SetObjectPropertyValue (UObject *InObject, const FCustomPropertyAccessor &BaseCustomAccessor, double InValue)
static void SetObjectPropertyValue (UObject *InObject, FTrackInstancePropertyBindings *PropertyBindings, double InValue)
static void SetObjectPropertyValue (UObject *InObject, uint16 PropertyOffset, double InValue)
Static Public Attributes
static constexpr bool bIsComposite = false
Detailed Description
Definition at line 236 of file MovieSceneTracksComponentTypes.h.
Member Typedef Documentation
CustomAccessorStorageType
using UE::MovieScene::FFloatPropertyTraits::CustomAccessorStorageType = float
Definition at line 241 of file MovieSceneTracksComponentTypes.h.
FloatTraitsImpl
using UE::MovieScene::FFloatPropertyTraits::FloatTraitsImpl = TDirectPropertyTraits<float>
Definition at line 245 of file MovieSceneTracksComponentTypes.h.
MetaDataType
using UE::MovieScene::FFloatPropertyTraits::MetaDataType = TPropertyMetaData<>
Definition at line 242 of file MovieSceneTracksComponentTypes.h.
StorageType
using UE::MovieScene::FFloatPropertyTraits::StorageType = double
Definition at line 240 of file MovieSceneTracksComponentTypes.h.
TraitsType
using UE::MovieScene::FFloatPropertyTraits::TraitsType = FFloatPropertyTraits
Definition at line 243 of file MovieSceneTracksComponentTypes.h.
Member Function Documentation
GetObjectPropertyValue() [1/4]
void UE::MovieScene::FFloatPropertyTraits::GetObjectPropertyValue (const UObject * InObject, const FCustomPropertyAccessor & BaseCustomAccessor, double & OutValue) inline static
Definition at line 247 of file MovieSceneTracksComponentTypes.h.
References UE::MovieScene::TCustomPropertyAccessor< PropertyTraits >::Functions.
GetObjectPropertyValue() [2/4]
void UE::MovieScene::FFloatPropertyTraits::GetObjectPropertyValue (const UObject * InObject, const FName & PropertyPath, double & OutValue) inline static
Definition at line 265 of file MovieSceneTracksComponentTypes.h.
References UE::MovieScene::TDirectPropertyTraits< float >::GetObjectPropertyValue(), and Value.
GetObjectPropertyValue() [3/4]
void UE::MovieScene::FFloatPropertyTraits::GetObjectPropertyValue (const UObject * InObject, FTrackInstancePropertyBindings * PropertyBindings, double & OutValue) inline static
Definition at line 259 of file MovieSceneTracksComponentTypes.h.
References UE::MovieScene::TDirectPropertyTraits< float >::GetObjectPropertyValue(), and Value.
GetObjectPropertyValue() [4/4]
void UE::MovieScene::FFloatPropertyTraits::GetObjectPropertyValue (const UObject * InObject, uint16 PropertyOffset, double & OutValue) inline static
Definition at line 253 of file MovieSceneTracksComponentTypes.h.
References UE::MovieScene::TDirectPropertyTraits< float >::GetObjectPropertyValue(), and Value.
SetObjectPropertyValue() [1/3]
void UE::MovieScene::FFloatPropertyTraits::SetObjectPropertyValue (UObject * InObject, const FCustomPropertyAccessor & BaseCustomAccessor, double InValue) inline static
Definition at line 272 of file MovieSceneTracksComponentTypes.h.
References float, and UE::MovieScene::TCustomPropertyAccessor< PropertyTraits >::Functions.
SetObjectPropertyValue() [2/3]
void UE::MovieScene::FFloatPropertyTraits::SetObjectPropertyValue (UObject * InObject, FTrackInstancePropertyBindings * PropertyBindings, double InValue) inline static
Definition at line 283 of file MovieSceneTracksComponentTypes.h.
References float, and UE::MovieScene::TDirectPropertyTraits< float >::SetObjectPropertyValue().
SetObjectPropertyValue() [3/3]
void UE::MovieScene::FFloatPropertyTraits::SetObjectPropertyValue (UObject * InObject, uint16 PropertyOffset, double InValue) inline static
Definition at line 278 of file MovieSceneTracksComponentTypes.h.
References float, and UE::MovieScene::TDirectPropertyTraits< float >::SetObjectPropertyValue().
Field Documentation
bIsComposite
bool UE::MovieScene::FFloatPropertyTraits::bIsComposite = false static constexpr
Definition at line 238 of file MovieSceneTracksComponentTypes.h.
The documentation for this struct was generated from the following file:
Runtime/MovieSceneTracks/Public/MovieSceneTracksComponentTypes.h