Unreal Engine 5.6 C++ API: FWorldPartitionCookPackage Struct Reference
FWorldPartitionCookPackage Struct Reference
#include "WorldPartitionCookPackage.h"
Public Types
enum class EType { Unknown , Level , Generic }
using IDType = uint64
Public Member Functions
FWorldPartitionCookPackage (const FString &InRoot, const FString &InRelativePath, EType InType, const FWorldPartitionPackageHash &InGenerationHash)
FString GetFullGeneratedPath () const
UPackage * GetPackage () const
Static Public Member Functions
static FStringView GetGeneratedFolderName ()
Returns "_Generated_".
static IDType MakeCookPackageID (const FString &InRoot, const FString &InRelativeFilename)
static FString MakeGeneratedFullPath (const FString &InRoot, const FString &InRelativeFilename)
static FString SanitizePathComponent (const FString &Path)
Data Fields
const FWorldPartitionPackageHash GenerationHash
const IDType PackageId
const FString RelativePath
const FString Root
const EType Type
Static Private Attributes
static constexpr FStringView GeneratedFolder = TEXTVIEW("/_Generated_/")
Detailed Description
Definition at line 19 of file WorldPartitionCookPackage.h.
Member Typedef Documentation
IDType
using FWorldPartitionCookPackage::IDType = uint64
Definition at line 30 of file WorldPartitionCookPackage.h.
Member Enumeration Documentation
EType
enum class FWorldPartitionCookPackage::EType strong
Enumerator
Unknown
Level
Generic
Definition at line 23 of file WorldPartitionCookPackage.h.
Constructor & Destructor Documentation
FWorldPartitionCookPackage()
FWorldPartitionCookPackage::FWorldPartitionCookPackage (const FString & InRoot, const FString & InRelativePath, EType InType, const FWorldPartitionPackageHash & InGenerationHash) inline
Definition at line 70 of file WorldPartitionCookPackage.h.
References GenerationHash, MakeCookPackageID(), PackageId, RelativePath, Root, SanitizePathComponent(), and Type.
Member Function Documentation
GetFullGeneratedPath()
FString FWorldPartitionCookPackage::GetFullGeneratedPath () const inline
Definition at line 79 of file WorldPartitionCookPackage.h.
References MakeGeneratedFullPath(), RelativePath, and Root.
Referenced by GetPackage().
GetGeneratedFolderName()
FStringView FWorldPartitionCookPackage::GetGeneratedFolderName () inline static
Returns "_Generated_".
Definition at line 91 of file WorldPartitionCookPackage.h.
References GeneratedFolder.
GetPackage()
UPackage * FWorldPartitionCookPackage::GetPackage () const inline
Definition at line 81 of file WorldPartitionCookPackage.h.
References GetFullGeneratedPath().
MakeCookPackageID()
IDType FWorldPartitionCookPackage::MakeCookPackageID (const FString & InRoot, const FString & InRelativeFilename) inline static
Definition at line 32 of file WorldPartitionCookPackage.h.
References check, and CityHash64().
Referenced by FWorldPartitionCookPackage().
MakeGeneratedFullPath()
FString FWorldPartitionCookPackage::MakeGeneratedFullPath (const FString & InRoot, const FString & InRelativeFilename) inline static
Definition at line 59 of file WorldPartitionCookPackage.h.
References GeneratedFolder, FPaths::RemoveDuplicateSlashes(), and TEXT.
Referenced by GetFullGeneratedPath().
SanitizePathComponent()
FString FWorldPartitionCookPackage::SanitizePathComponent (const FString & Path) inline static
Definition at line 46 of file WorldPartitionCookPackage.h.
References Path, FPaths::RemoveDuplicateSlashes(), and TEXT.
Referenced by FWorldPartitionCookPackage().
Field Documentation
GeneratedFolder
FStringView FWorldPartitionCookPackage::GeneratedFolder = TEXTVIEW("/_Generated_/") static constexpr private
Definition at line 94 of file WorldPartitionCookPackage.h.
Referenced by GetGeneratedFolderName(), and MakeGeneratedFullPath().
GenerationHash
const FWorldPartitionPackageHash FWorldPartitionCookPackage::GenerationHash
Definition at line 87 of file WorldPartitionCookPackage.h.
Referenced by FWorldPartitionCookPackage().
PackageId
const IDType FWorldPartitionCookPackage::PackageId
Definition at line 85 of file WorldPartitionCookPackage.h.
Referenced by FWorldPartitionCookPackage().
RelativePath
const FString FWorldPartitionCookPackage::RelativePath
Definition at line 84 of file WorldPartitionCookPackage.h.
Referenced by FWorldPartitionCookPackage(), and GetFullGeneratedPath().
Root
const FString FWorldPartitionCookPackage::Root
Definition at line 83 of file WorldPartitionCookPackage.h.
Referenced by FWorldPartitionCookPackage(), and GetFullGeneratedPath().
Type
const EType FWorldPartitionCookPackage::Type
Definition at line 86 of file WorldPartitionCookPackage.h.
Referenced by FWorldPartitionCookPackage().
The documentation for this struct was generated from the following file:
Runtime/Engine/Public/WorldPartition/Cook/WorldPartitionCookPackage.h