Unreal Engine 5.6 C++ API: FMovieSceneDirectorBlueprintConditionUtils Struct Reference
FMovieSceneDirectorBlueprintConditionUtils Struct Reference
A utility class for managing director blueprint condition endpoints.
#include "MovieSceneDirectorBlueprintConditionUtils.h"
Public Types
using FSharedPlaybackState = UE::MovieScene::FSharedPlaybackState
Static Public Member Functions
static void EnsureBlueprintExtensionCreated (UMovieSceneSequence *MovieSceneSequence, UBlueprint *Blueprint)
Ensures that the condition blueprint extension has been added to the given sequence's director blueprint.
static void GatherDirectorBlueprintConditions (UMovieScene *InMovieScene, TArray< FMovieSceneDirectorBlueprintConditionData * > &OutDirectorBlueprintConditionData)
Utility function for gathering all blueprint conditions in a sequence into a container.
template<typename Callback>
static void IterateDirectorBlueprintConditions (UMovieScene *InMovieScene, Callback &&InCallback)
Utility function for iterating all blueprint conditions in a sequence.
static void SetEndpoint (UMovieScene *MovieScene, FMovieSceneDirectorBlueprintConditionData *DirectorBlueprintConditionData, UK2Node *NewEndpoint)
Set an endpoint on the given blueprint condition.
Detailed Description
A utility class for managing director blueprint condition endpoints.
Definition at line 19 of file MovieSceneDirectorBlueprintConditionUtils.h.
Member Typedef Documentation
FSharedPlaybackState
using FMovieSceneDirectorBlueprintConditionUtils::FSharedPlaybackState = UE::MovieScene::FSharedPlaybackState
Definition at line 21 of file MovieSceneDirectorBlueprintConditionUtils.h.
Member Function Documentation
EnsureBlueprintExtensionCreated()
void FMovieSceneDirectorBlueprintConditionUtils::EnsureBlueprintExtensionCreated (UMovieSceneSequence * MovieSceneSequence, UBlueprint * Blueprint) static
Ensures that the condition blueprint extension has been added to the given sequence's director blueprint.
GatherDirectorBlueprintConditions()
void FMovieSceneDirectorBlueprintConditionUtils::GatherDirectorBlueprintConditions (UMovieScene * InMovieScene, TArray< FMovieSceneDirectorBlueprintConditionData * > & OutDirectorBlueprintConditionData) inline static
Utility function for gathering all blueprint conditions in a sequence into a container.
Definition at line 90 of file MovieSceneDirectorBlueprintConditionUtils.h.
References TArray< InElementType, InAllocatorType >::Add(), Item, and IterateDirectorBlueprintConditions().
IterateDirectorBlueprintConditions()
template<typename Callback> void FMovieSceneDirectorBlueprintConditionUtils::IterateDirectorBlueprintConditions (UMovieScene * InMovieScene, Callback && InCallback) inline static
Utility function for iterating all blueprint conditions in a sequence.
Definition at line 37 of file MovieSceneDirectorBlueprintConditionUtils.h.
References Cast(), Container, and Tracks.
Referenced by GatherDirectorBlueprintConditions().
SetEndpoint()
void FMovieSceneDirectorBlueprintConditionUtils::SetEndpoint (UMovieScene * MovieScene, FMovieSceneDirectorBlueprintConditionData * DirectorBlueprintConditionData, UK2Node * NewEndpoint) static
Set an endpoint on the given blueprint condition.
The documentation for this struct was generated from the following file:
Editor/MovieSceneTools/Public/Conditions/MovieSceneDirectorBlueprintConditionUtils.h