Unreal Engine 5.6 C++ API: UE::Graph::FGraph Struct Reference
UE::Graph::FGraph Struct Reference
Convenience structure for storing a graph in edge list form.
#include "GraphConvert.h"
Public Member Functions
FGraph ()=default
FGraph (const FGraph &)=delete
FGraph (FGraph &&)=default
SIZE_T GetAllocatedSize () const
FGraph & operator= (const FGraph &)=delete
FGraph & operator= (FGraph &&)=default
Data Fields
TArray64< FVertex > Buffer
TArray< TConstArrayView< FVertex > > EdgeLists
Detailed Description
Convenience structure for storing a graph in edge list form.
EdgeLists[i] is a TConstArrayView of edges from Vertex i. Each element of EdgeList[i] is a an FVertex j such that (i, j) is an edge in the graph.
Definition at line 34 of file GraphConvert.h.
Constructor & Destructor Documentation
FGraph() [1/3]
UE::Graph::FGraph::FGraph () default
Referenced by FGraph(), FGraph(), operator=(), and operator=().
FGraph() [2/3]
UE::Graph::FGraph::FGraph (const FGraph &) delete
References FGraph().
FGraph() [3/3]
UE::Graph::FGraph::FGraph (FGraph &&) default
References FGraph().
Member Function Documentation
GetAllocatedSize()
SIZE_T UE::Graph::FGraph::GetAllocatedSize () const inline
Definition at line 48 of file GraphConvert.h.
References Buffer, and EdgeLists.
operator=() [1/2]
FGraph & UE::Graph::FGraph::operator= (const FGraph &) delete
References FGraph().
operator=() [2/2]
FGraph & UE::Graph::FGraph::operator= (FGraph &&) default
References FGraph().
Field Documentation
Buffer
TArray64<FVertex> UE::Graph::FGraph::Buffer
Definition at line 37 of file GraphConvert.h.
Referenced by UE::Graph::ConvertToGraph(), UE::Graph::ConvertToSingleBufferGraph(), and GetAllocatedSize().
EdgeLists
TArray<TConstArrayView<FVertex> > UE::Graph::FGraph::EdgeLists
Definition at line 39 of file GraphConvert.h.
Referenced by UE::Graph::ConvertToGraph(), UE::Graph::ConvertToSingleBufferGraph(), and GetAllocatedSize().
The documentation for this struct was generated from the following file:
Runtime/Core/Public/Experimental/Graph/GraphConvert.h