Unreal Engine 5.6 C++ API: FPopupLayerSlot Struct Reference
FPopupLayerSlot Struct Reference
Popups, tooltips, drag and drop decorators all can be executed without creating a new window.
#include "SWindow.h"
Public Member Functions
FPopupLayerSlot ()
void SetClampBuffer (TAttribute< FVector2D > InClampBuffer_Attribute)
If this slot is kept within the parent window, how far from the edges should we clamp it.
void SetClampToWindow (TAttribute< bool > InClamp_Attribute)
Should this slot be kept within the parent window.
void SetDesktopPosition (TAttribute< FVector2D > InDesktopPosition)
Pixel position in desktop space.
void SetHeightOverride (TAttribute< float > InHeightOverride)
Width override in pixels.
void SetScale (TAttribute< float > InScale)
DPI scaling to be applied to the contents of this slot.
void SetWidthOverride (TAttribute< float > InWidthOverride)
Width override in pixels.
DesktopPosition HeightOverride SLATE_ATTRIBUTE (float, Scale) SLATE_ATTRIBUTE(bool
DPI scaling to be applied to the contents of this slot.
DesktopPosition SLATE_ATTRIBUTE (float, WidthOverride) SLATE_ATTRIBUTE(float
Width override in pixels.
DesktopPosition HeightOverride ClampToWindow SLATE_ATTRIBUTE (FVector2D, ClampBuffer) SLATE_SLOT_END_ARGS() void Construct(const FChildren &SlotOwner
If this slot is kept within the parent window, how far from the edges should we clamp it.
SLATE_SLOT_BEGIN_ARGS (FPopupLayerSlot, TSlotBase< FPopupLayerSlot >) SLATE_ATTRIBUTE(FVector2D
Pixel position in desktop space.
Public Member Functions inherited from TSlotBase< FPopupLayerSlot >
void Construct (const FChildren &SlotOwner, FSlotArguments &&InArgs)
FPopupLayerSlot & Expose (FPopupLayerSlot *&OutVarToInit)
FSlotBase ()
FSlotBase (const FChildren &InParent)
FSlotBase (const FSlotBase &)=delete
FSlotBase (const TSharedRef< SWidget > &InWidget)
FPopupLayerSlot & operator[] (TSharedRef< SWidget > &&InChildWidget)
Public Member Functions inherited from FSlotBase
FSlotBase ()
FSlotBase (const FChildren &InParent)
FSlotBase (const FSlotBase &)=delete
FSlotBase (const TSharedRef< SWidget > &InWidget)
virtual ~FSlotBase ()
FORCEINLINE_DEBUGGABLE void AttachWidget (const TSharedRef< SWidget > &InWidget)
FORCEINLINE_DEBUGGABLE void AttachWidget (TSharedRef< SWidget > &&InWidget)
Attach the child widget the slot now owns.
const TSharedPtr< SWidget > DetachWidget ()
Remove the widget from its current slot.
const FChildren * GetOwner () const
Access the FChildren that own the slot.
SWidget * GetOwnerWidget () const
Access the widget that own the slot.
FORCEINLINE_DEBUGGABLE const TSharedRef< SWidget > & GetWidget () const
Access the widget in the current slot.
void Invalidate (EInvalidateWidgetReason InvalidateReason)
Invalidate the widget's owner.
FSlotBase & operator= (const FSlotBase &)=delete
void SetOwner (const FChildren &Children)
Set the owner of the slot.
Data Fields
DesktopPosition HeightOverride ClampToWindow FSlotArguments && InArgs
Private Attributes
TAttribute< bool > Clamp_Attribute
TAttribute< FVector2D > ClampBuffer_Attribute
TAttribute< FVector2D > DesktopPosition_Attribute
TAttribute< float > HeightOverride_Attribute
TAttribute< float > Scale_Attribute
TAttribute< float > WidthOverride_Attribute
Friends
class SPopupLayer
SPopupLayer arranges FPopupLayerSlots, so it needs to know all about.
class TPanelChildren< FPopupLayerSlot >
TPanelChildren need access to the Widget member.
Additional Inherited Members
Public Types inherited from TSlotBase< FPopupLayerSlot >
enum EConstructSlotIsFChildren
Argument to indicate the Slot is also its owner.
Protected Member Functions inherited from FSlotBase
template<typename TargetValueType, typename SourceValueType>
bool SetAttribute (TAttribute< TargetValueType > &TargetValue, const TAttribute< SourceValueType > &SourceValue, EInvalidateWidgetReason BaseInvalidationReason)
Performs the attribute assignment and invalidates the widget minimally based on what actually changed.
Detailed Description
Popups, tooltips, drag and drop decorators all can be executed without creating a new window.
This slot along with the SWindow::AddPopupLayerSlot() API enabled it.
Definition at line 129 of file SWindow.h.
Constructor & Destructor Documentation
FPopupLayerSlot()
FPopupLayerSlot::FPopupLayerSlot () inline
Definition at line 132 of file SWindow.h.
References FPopupLayerSlot(), Clamp_Attribute, ClampBuffer_Attribute, DesktopPosition_Attribute, HeightOverride_Attribute, Scale_Attribute, and WidthOverride_Attribute.
Referenced by FPopupLayerSlot(), SLATE_SLOT_BEGIN_ARGS(), and SPopupLayer.
Member Function Documentation
SetClampBuffer()
void FPopupLayerSlot::SetClampBuffer (TAttribute< FVector2D > InClampBuffer_Attribute) inline
If this slot is kept within the parent window, how far from the edges should we clamp it.
Definition at line 217 of file SWindow.h.
References ClampBuffer_Attribute, and MoveTemp().
SetClampToWindow()
void FPopupLayerSlot::SetClampToWindow (TAttribute< bool > InClamp_Attribute) inline
Should this slot be kept within the parent window.
Definition at line 211 of file SWindow.h.
References Clamp_Attribute, and MoveTemp().
SetDesktopPosition()
void FPopupLayerSlot::SetDesktopPosition (TAttribute< FVector2D > InDesktopPosition) inline
Pixel position in desktop space.
Definition at line 187 of file SWindow.h.
References DesktopPosition_Attribute, and MoveTemp().
SetHeightOverride()
void FPopupLayerSlot::SetHeightOverride (TAttribute< float > InHeightOverride) inline
Width override in pixels.
Definition at line 199 of file SWindow.h.
References HeightOverride_Attribute, and MoveTemp().
SetScale()
void FPopupLayerSlot::SetScale (TAttribute< float > InScale) inline
DPI scaling to be applied to the contents of this slot.
Definition at line 205 of file SWindow.h.
References MoveTemp(), and Scale_Attribute.
SetWidthOverride()
void FPopupLayerSlot::SetWidthOverride (TAttribute< float > InWidthOverride) inline
Width override in pixels.
Definition at line 193 of file SWindow.h.
References MoveTemp(), and WidthOverride_Attribute.
SLATE_ATTRIBUTE() [1/3]
DesktopPosition HeightOverride FPopupLayerSlot::SLATE_ATTRIBUTE (float , Scale)
DPI scaling to be applied to the contents of this slot.
Should this slot be kept within the parent window
References Scale, and SLATE_ATTRIBUTE().
SLATE_ATTRIBUTE() [2/3]
DesktopPosition FPopupLayerSlot::SLATE_ATTRIBUTE (float , WidthOverride)
Width override in pixels.
Width override in pixels
References SLATE_ATTRIBUTE().
Referenced by SLATE_ATTRIBUTE(), SLATE_ATTRIBUTE(), and SLATE_ATTRIBUTE().
SLATE_ATTRIBUTE() [3/3]
DesktopPosition HeightOverride ClampToWindow FPopupLayerSlot::SLATE_ATTRIBUTE (FVector2D , ClampBuffer) const &
If this slot is kept within the parent window, how far from the edges should we clamp it.
References SLATE_ATTRIBUTE(), and SLATE_SLOT_END_ARGS.
SLATE_SLOT_BEGIN_ARGS()
FPopupLayerSlot::SLATE_SLOT_BEGIN_ARGS (FPopupLayerSlot , TSlotBase< FPopupLayerSlot >)
Pixel position in desktop space.
References FPopupLayerSlot().
Friends And Related Symbol Documentation
SPopupLayer
friend class SPopupLayer friend
SPopupLayer arranges FPopupLayerSlots, so it needs to know all about.
Definition at line 224 of file SWindow.h.
References FPopupLayerSlot(), and SPopupLayer.
Referenced by SPopupLayer.
TPanelChildren< FPopupLayerSlot >
friend class TPanelChildren< FPopupLayerSlot > friend
TPanelChildren need access to the Widget member.
Definition at line 224 of file SWindow.h.
Field Documentation
Clamp_Attribute
TAttribute<bool> FPopupLayerSlot::Clamp_Attribute private
Definition at line 232 of file SWindow.h.
Referenced by FPopupLayerSlot(), and SetClampToWindow().
ClampBuffer_Attribute
TAttribute<FVector2D> FPopupLayerSlot::ClampBuffer_Attribute private
Definition at line 233 of file SWindow.h.
Referenced by FPopupLayerSlot(), and SetClampBuffer().
DesktopPosition_Attribute
TAttribute<FVector2D> FPopupLayerSlot::DesktopPosition_Attribute private
Definition at line 228 of file SWindow.h.
Referenced by FPopupLayerSlot(), and SetDesktopPosition().
HeightOverride_Attribute
TAttribute<float> FPopupLayerSlot::HeightOverride_Attribute private
Definition at line 230 of file SWindow.h.
Referenced by FPopupLayerSlot(), and SetHeightOverride().
InArgs
DesktopPosition HeightOverride ClampToWindow FSlotArguments&& FPopupLayerSlot::InArgs
Initial value:
{
        if (InArgs._DesktopPosition.IsSet())
        {
            SetDesktopPosition(MoveTemp(InArgs._DesktopPosition));
        }
        if (InArgs._WidthOverride.IsSet())
        {
            SetWidthOverride(MoveTemp(InArgs._WidthOverride));
        }
        if (InArgs._HeightOverride.IsSet())
        {
            SetHeightOverride(MoveTemp(InArgs._HeightOverride));
        }
        if (InArgs._Scale.IsSet())
        {
            SetScale(MoveTemp(InArgs._Scale));
        }
        if (InArgs._ClampToWindow.IsSet())
        {
            SetClampToWindow(MoveTemp(InArgs._ClampToWindow));
        }
        if (InArgs._ClampBuffer.IsSet())
        {
            SetClampBuffer(MoveTemp(InArgs._ClampBuffer));
        }
        TSlotBase<FPopupLayerSlot>::Construct(SlotOwner, MoveTemp(InArgs))
Definition at line 157 of file SWindow.h.
Scale_Attribute
TAttribute<float> FPopupLayerSlot::Scale_Attribute private
Definition at line 231 of file SWindow.h.
Referenced by FPopupLayerSlot(), and SetScale().
WidthOverride_Attribute
TAttribute<float> FPopupLayerSlot::WidthOverride_Attribute private
Definition at line 229 of file SWindow.h.
Referenced by FPopupLayerSlot(), and SetWidthOverride().
The documentation for this struct was generated from the following file:
Runtime/SlateCore/Public/Widgets/SWindow.h