Unreal Engine 5.6 C++ API: FAnimationUpdateSharedContext Struct Reference
FAnimationUpdateSharedContext Struct Reference
Persistent state shared during animation tree update.
#include "AnimNodeBase.h"
Public Member Functions
FAnimationUpdateSharedContext ()=default
FAnimationUpdateSharedContext (FAnimationUpdateSharedContext &)=delete
void CopyForCachedUpdate (FAnimationUpdateSharedContext &Source)
FAnimationUpdateSharedContext & operator= (const FAnimationUpdateSharedContext &)=delete
UE_DEPRECATED (5.0, "Please use the message & tagging system in UE::Anim::FMessageStack") FAnimNodeTracker AncestorTracker
Data Fields
UE::Anim::FMessageStack MessageStack
Detailed Description
Persistent state shared during animation tree update.
Definition at line 130 of file AnimNodeBase.h.
Constructor & Destructor Documentation
FAnimationUpdateSharedContext() [1/2]
FAnimationUpdateSharedContext::FAnimationUpdateSharedContext () default
Referenced by FAnimationUpdateSharedContext(), CopyForCachedUpdate(), and operator=().
FAnimationUpdateSharedContext() [2/2]
FAnimationUpdateSharedContext::FAnimationUpdateSharedContext (FAnimationUpdateSharedContext &) delete
References FAnimationUpdateSharedContext().
Member Function Documentation
CopyForCachedUpdate()
void FAnimationUpdateSharedContext::CopyForCachedUpdate (FAnimationUpdateSharedContext & Source) inline
Definition at line 146 of file AnimNodeBase.h.
References FAnimationUpdateSharedContext(), FAnimNodeTracker::CopyTopsOnly(), MessageStack, PRAGMA_DISABLE_DEPRECATION_WARNINGS, PRAGMA_ENABLE_DEPRECATION_WARNINGS, and Source.
operator=()
FAnimationUpdateSharedContext & FAnimationUpdateSharedContext::operator= (const FAnimationUpdateSharedContext &) delete
References FAnimationUpdateSharedContext().
UE_DEPRECATED()
FAnimationUpdateSharedContext::UE_DEPRECATED (5. 0, "Please use the message & tagging system in UE::Anim::FMessageStack")
Field Documentation
MessageStack
UE::Anim::FMessageStack FAnimationUpdateSharedContext::MessageStack
Definition at line 144 of file AnimNodeBase.h.
Referenced by CopyForCachedUpdate().
The documentation for this struct was generated from the following file:
Runtime/Engine/Classes/Animation/AnimNodeBase.h