Unreal Engine 5.6 C++ API: LowLevelTasks::TTaskDelegate< ReturnType(ParamTypes...), TotalSize >::TTaskDelegateImpl< TCallableType, true > Struct Template Reference
LowLevelTasks::TTaskDelegate< ReturnType(ParamTypes...), TotalSize >::TTaskDelegateImpl< TCallableType, true > Struct Template Reference final
Public Member Functions
template<typename CallableT>
TTaskDelegateImpl (CallableT &&Callable, void *InlineData)
ReturnType Call (void *InlineData, ParamTypes... Params) const override
ReturnType CallAndMove (ThisClass &Destination, void *InlineData, uint32 DestInlineSize, ParamTypes... Params) override
uint32 DelegateSize () const override
void Destroy (void *InlineData) override
bool IsHeapAllocated () const override
bool IsSet () const override
void Move (TTaskDelegateBase &DstWrapper, void *DstData, void *SrcData, uint32 DestInlineSize) override
Private Member Functions
TTaskDelegateImpl (void *DstData, void *SrcData)
Detailed Description
template<uint32 TotalSize, typename ReturnType, typename... ParamTypes>
template<typename TCallableType>
struct LowLevelTasks::TTaskDelegate< ReturnType(ParamTypes...), TotalSize >::TTaskDelegateImpl< TCallableType, true >
Definition at line 197 of file TaskDelegate.h.
Constructor & Destructor Documentation
TTaskDelegateImpl() [1/2]
template<uint32 TotalSize, typename ReturnType, typename... ParamTypes> template<typename TCallableType> LowLevelTasks::TTaskDelegate< ReturnType(ParamTypes...), TotalSize >::TTaskDelegateImpl< TCallableType, true >::TTaskDelegateImpl (void * DstData, void * SrcData) inline private
Definition at line 200 of file TaskDelegate.h.
Referenced by TTaskDelegateImpl(), and Move().
TTaskDelegateImpl() [2/2]
template<uint32 TotalSize, typename ReturnType, typename... ParamTypes> template<typename TCallableType> template<typename CallableT> LowLevelTasks::TTaskDelegate< ReturnType(ParamTypes...), TotalSize >::TTaskDelegateImpl< TCallableType, true >::TTaskDelegateImpl (CallableT && Callable, void * InlineData) inline
Definition at line 207 of file TaskDelegate.h.
References TTaskDelegateImpl(), Forward(), TBlockAllocationCache< BlockSize, FAlignedAllocator >::MaxAlignment, and Value.
Member Function Documentation
Call()
template<uint32 TotalSize, typename ReturnType, typename... ParamTypes> template<typename TCallableType> ReturnType LowLevelTasks::TTaskDelegate< ReturnType(ParamTypes...), TotalSize >::TTaskDelegateImpl< TCallableType, true >::Call (void * InlineData, ParamTypes... Params) const inline override virtual
Reimplemented from LowLevelTasks::TTaskDelegate< ReturnType(ParamTypes...), TotalSize >::TTaskDelegateBase.
Definition at line 224 of file TaskDelegate.h.
References Invoke(), and Params.
Referenced by CallAndMove().
CallAndMove()
template<uint32 TotalSize, typename ReturnType, typename... ParamTypes> template<typename TCallableType> ReturnType LowLevelTasks::TTaskDelegate< ReturnType(ParamTypes...), TotalSize >::TTaskDelegateImpl< TCallableType, true >::CallAndMove (ThisClass & Destination, void * InlineData, uint32 DestInlineSize, ParamTypes... Params) inline override virtual
Reimplemented from LowLevelTasks::TTaskDelegate< ReturnType(ParamTypes...), TotalSize >::TTaskDelegateBase.
Definition at line 230 of file TaskDelegate.h.
References Call(), Move, ON_SCOPE_EXIT, and Params.
DelegateSize()
template<uint32 TotalSize, typename ReturnType, typename... ParamTypes> template<typename TCallableType> uint32 LowLevelTasks::TTaskDelegate< ReturnType(ParamTypes...), TotalSize >::TTaskDelegateImpl< TCallableType, true >::DelegateSize () const inline override virtual
Reimplemented from LowLevelTasks::TTaskDelegate< ReturnType(ParamTypes...), TotalSize >::TTaskDelegateBase.
Definition at line 258 of file TaskDelegate.h.
Destroy()
template<uint32 TotalSize, typename ReturnType, typename... ParamTypes> template<typename TCallableType> void LowLevelTasks::TTaskDelegate< ReturnType(ParamTypes...), TotalSize >::TTaskDelegateImpl< TCallableType, true >::Destroy (void * InlineData) inline override virtual
Reimplemented from LowLevelTasks::TTaskDelegate< ReturnType(ParamTypes...), TotalSize >::TTaskDelegateBase.
Definition at line 239 of file TaskDelegate.h.
References TLinearAllocatorBase< T, ELinearAllocatorThreadPolicy::ThreadSafe >::Free().
IsHeapAllocated()
template<uint32 TotalSize, typename ReturnType, typename... ParamTypes> template<typename TCallableType> bool LowLevelTasks::TTaskDelegate< ReturnType(ParamTypes...), TotalSize >::TTaskDelegateImpl< TCallableType, true >::IsHeapAllocated () const inline override virtual
Reimplemented from LowLevelTasks::TTaskDelegate< ReturnType(ParamTypes...), TotalSize >::TTaskDelegateBase.
Definition at line 248 of file TaskDelegate.h.
IsSet()
template<uint32 TotalSize, typename ReturnType, typename... ParamTypes> template<typename TCallableType> bool LowLevelTasks::TTaskDelegate< ReturnType(ParamTypes...), TotalSize >::TTaskDelegateImpl< TCallableType, true >::IsSet () const inline override virtual
Reimplemented from LowLevelTasks::TTaskDelegate< ReturnType(ParamTypes...), TotalSize >::TTaskDelegateBase.
Definition at line 253 of file TaskDelegate.h.
Move()
template<uint32 TotalSize, typename ReturnType, typename... ParamTypes> template<typename TCallableType> void LowLevelTasks::TTaskDelegate< ReturnType(ParamTypes...), TotalSize >::TTaskDelegateImpl< TCallableType, true >::Move (TTaskDelegateBase & DstWrapper, void * DstData, void * SrcData, uint32 DestInlineSize) inline override virtual
Reimplemented from LowLevelTasks::TTaskDelegate< ReturnType(ParamTypes...), TotalSize >::TTaskDelegateBase.
Definition at line 218 of file TaskDelegate.h.
References TTaskDelegateImpl().
The documentation for this struct was generated from the following file:
Runtime/Core/Public/Async/Fundamental/TaskDelegate.h