Unreal Engine 5.6 C++ API: FPropertyTempVal Struct Reference
FPropertyTempVal Struct Reference
#include "PropertyTempVal.h"
Public Member Functions
FPropertyTempVal (const FPropertyTempVal &)=delete
FPropertyTempVal (FProperty *InProp)
~FPropertyTempVal ()
void ExportText (FString &ValueStr, const void *Defaults=nullptr, UObject *Parent=nullptr, int32 PortFlags=0, UObject *ExportRootScope=nullptr)
FORCEINLINE void * Get ()
FORCEINLINE const void * Get () const
FPropertyTempVal & operator= (const FPropertyTempVal &)=delete
void Serialize (FArchive &Ar, const void *Defaults=nullptr)
Private Attributes
FProperty * Prop
void * Value
Detailed Description
Definition at line 16 of file PropertyTempVal.h.
Constructor & Destructor Documentation
FPropertyTempVal() [1/2]
FPropertyTempVal::FPropertyTempVal (FProperty * InProp) explicit
Referenced by FPropertyTempVal(), and operator=().
~FPropertyTempVal()
FPropertyTempVal::~FPropertyTempVal ()
FPropertyTempVal() [2/2]
FPropertyTempVal::FPropertyTempVal (const FPropertyTempVal &) delete
References FPropertyTempVal().
Member Function Documentation
ExportText()
void FPropertyTempVal::ExportText (FString & ValueStr, const void * Defaults = nullptr, UObject * Parent = nullptr, int32 PortFlags = 0, UObject * ExportRootScope = nullptr)
References Parent.
Get() [1/2]
FORCEINLINE void * FPropertyTempVal::Get () inline
Definition at line 32 of file PropertyTempVal.h.
References FORCEINLINE, and Value.
Get() [2/2]
FORCEINLINE const void * FPropertyTempVal::Get () const inline
Definition at line 38 of file PropertyTempVal.h.
References FORCEINLINE, and Value.
operator=()
FPropertyTempVal & FPropertyTempVal::operator= (const FPropertyTempVal &) delete
References FPropertyTempVal().
Serialize()
void FPropertyTempVal::Serialize (FArchive & Ar, const void * Defaults = nullptr)
References Ar.
Field Documentation
Prop
FProperty* FPropertyTempVal::Prop private
Definition at line 45 of file PropertyTempVal.h.
Value
void* FPropertyTempVal::Value private
Definition at line 48 of file PropertyTempVal.h.
Referenced by Get(), and Get().
The documentation for this struct was generated from the following file:
Runtime/CoreUObject/Public/UObject/PropertyTempVal.h