Unreal Engine 5.6 C++ API: FSizeTableEntry Struct Reference
FSizeTableEntry Struct Reference
#include "MallocBinnedCommon.h"
Public Member Functions
FSizeTableEntry ()=default
FSizeTableEntry (uint32 InBinSize, uint64 PlatformPageSize, uint8 Num4kbPages, uint32 BasePageSize)
bool operator< (const FSizeTableEntry &Other) const
Static Public Member Functions
static uint8 FillSizeTable (uint64 PlatformPageSize, FSizeTableEntry *SizeTable, uint32 BasePageSize, uint32 MaxSize, uint32 SizeIncrement)
Data Fields
uint32 BinSize
uint32 NumMemoryPagesPerBlock
Detailed Description
Definition at line 152 of file MallocBinnedCommon.h.
Constructor & Destructor Documentation
FSizeTableEntry() [1/2]
FSizeTableEntry::FSizeTableEntry () default
Referenced by FillSizeTable(), and operator<().
FSizeTableEntry() [2/2]
FSizeTableEntry::FSizeTableEntry (uint32 InBinSize, uint64 PlatformPageSize, uint8 Num4kbPages, uint32 BasePageSize)
Member Function Documentation
FillSizeTable()
uint8 FSizeTableEntry::FillSizeTable (uint64 PlatformPageSize, FSizeTableEntry * SizeTable, uint32 BasePageSize, uint32 MaxSize, uint32 SizeIncrement) static
References FSizeTableEntry(), and MaxSize.
operator<()
bool FSizeTableEntry::operator< (const FSizeTableEntry & Other) const inline
Definition at line 160 of file MallocBinnedCommon.h.
References FSizeTableEntry(), BinSize, and Other.
Field Documentation
BinSize
uint32 FSizeTableEntry::BinSize
Definition at line 154 of file MallocBinnedCommon.h.
Referenced by operator<().
NumMemoryPagesPerBlock
uint32 FSizeTableEntry::NumMemoryPagesPerBlock
Definition at line 155 of file MallocBinnedCommon.h.
The documentation for this struct was generated from the following file:
Runtime/Core/Public/HAL/MallocBinnedCommon.h