Unreal Engine 5.6 C++ API: UE::Geometry::TAxisAlignedBox3< RealType > Struct Template Reference
UE::Geometry::TAxisAlignedBox3< RealType > Struct Template Reference
#include "BoxTypes.h"
Public Member Functions
TAxisAlignedBox3 ()
TAxisAlignedBox3 (const TArray< TVector< RealType > > &Pts)
TAxisAlignedBox3 (const TAxisAlignedBox3 &Box, const FTransformSRT3d &Transform)
TAxisAlignedBox3 (const TAxisAlignedBox3 &Box, const TFunction< TVector< RealType >(const TVector< RealType > &)> TransformF)
template<typename OtherRealType>
TAxisAlignedBox3 (const TAxisAlignedBox3< OtherRealType > &OtherBox)
template<typename InRealType>
TAxisAlignedBox3 (const TBox< InRealType > &Box)
TAxisAlignedBox3 (const TVector< RealType > &A, const TVector< RealType > &B, const TVector< RealType > &C)
TAxisAlignedBox3 (const TVector< RealType > &Center, RealType HalfWidth)
TAxisAlignedBox3 (const TVector< RealType > &Min, const TVector< RealType > &Max)
TAxisAlignedBox3 (TArrayView< const TVector< RealType > > Pts)
TVector< RealType > Center () const
TVector< RealType > Clamp (const TVector< RealType > &V) const
void Contain (const TArray< TVector< RealType > > &Pts)
void Contain (const TAxisAlignedBox3< RealType > &Other)
void Contain (const TVector< RealType > &V)
void Contain (TArrayView< const TVector< RealType > > Pts)
bool Contains (const TAxisAlignedBox3< RealType > &Box) const
bool Contains (const TVector< RealType > &V) const
RealType Depth () const
TVector< RealType > Diagonal () const
RealType DiagonalLength () const
RealType Dimension (int32 Index) const
RealType DistanceSquared (const TAxisAlignedBox3< RealType > &Box) const
RealType DistanceSquared (const TVector< RealType > &V) const
void Expand (RealType Radius)
TVector< RealType > Extents () const
TVector< RealType > GetCorner (int Index) const
RealType Height () const
TAxisAlignedBox3< RealType > Intersect (const TAxisAlignedBox3< RealType > &Box) const
bool Intersects (TAxisAlignedBox3 Box) const
bool IsEmpty () const
RealType MaxDim () const
RealType MinDim () const
template<typename OutRealType>
operator TBox< OutRealType > () const
bool operator!= (const TAxisAlignedBox3< RealType > &Other) const
bool operator== (const TAxisAlignedBox3< RealType > &Other) const
RealType SurfaceArea () const
RealType Volume () const
RealType Width () const
Static Public Member Functions
static TAxisAlignedBox3< RealType > Empty ()
static TAxisAlignedBox3< RealType > Infinite ()
template<typename EnumerableIntType, typename PointFunc>
static TAxisAlignedBox3< RealType > MakeBoundsFromIndices (EnumerableIntType IndexEnumerable, PointFunc GetPoint)
Compute bounding box of 3D points returned by GetPoint(Index) for indices in range for_each(IndexEnumerable)
template<typename PointFunc>
static TAxisAlignedBox3< RealType > MakeBoundsFromIndices (int32 MaxIndex, PointFunc GetPoint)
Compute bounding box of 3D points returned by GetPoint(Index) for indices in range [0...MaxIndex)
Data Fields
TVector< RealType > Max
TVector< RealType > Min
Detailed Description
template<typename RealType>
struct UE::Geometry::TAxisAlignedBox3< RealType >
Definition at line 235 of file BoxTypes.h.
Constructor & Destructor Documentation
TAxisAlignedBox3() [1/10]
template<typename RealType> UE::Geometry::TAxisAlignedBox3< RealType >::TAxisAlignedBox3 () inline
Definition at line 240 of file BoxTypes.h.
Referenced by UE::Geometry::TAxisAlignedBox3< float >::Empty(), and UE::Geometry::TAxisAlignedBox3< float >::Infinite().
TAxisAlignedBox3() [2/10]
template<typename RealType> UE::Geometry::TAxisAlignedBox3< RealType >::TAxisAlignedBox3 (const TVector< RealType > & Min, const TVector< RealType > & Max) inline
Definition at line 245 of file BoxTypes.h.
TAxisAlignedBox3() [3/10]
template<typename RealType> UE::Geometry::TAxisAlignedBox3< RealType >::TAxisAlignedBox3 (const TVector< RealType > & A, const TVector< RealType > & B, const TVector< RealType > & C) inline
Definition at line 251 of file BoxTypes.h.
TAxisAlignedBox3() [4/10]
template<typename RealType> template<typename OtherRealType> UE::Geometry::TAxisAlignedBox3< RealType >::TAxisAlignedBox3 (const TAxisAlignedBox3< OtherRealType > & OtherBox) inline explicit
Definition at line 266 of file BoxTypes.h.
TAxisAlignedBox3() [5/10]
template<typename RealType> UE::Geometry::TAxisAlignedBox3< RealType >::TAxisAlignedBox3 (const TVector< RealType > & Center, RealType HalfWidth) inline
Definition at line 272 of file BoxTypes.h.
TAxisAlignedBox3() [6/10]
template<typename RealType> UE::Geometry::TAxisAlignedBox3< RealType >::TAxisAlignedBox3 (const TAxisAlignedBox3< RealType > & Box, const TFunction< TVector< RealType >(const TVector< RealType > &)> TransformF) inline
Definition at line 279 of file BoxTypes.h.
TAxisAlignedBox3() [7/10]
template<typename RealType> UE::Geometry::TAxisAlignedBox3< RealType >::TAxisAlignedBox3 (const TAxisAlignedBox3< RealType > & Box, const FTransformSRT3d & Transform) inline
Definition at line 297 of file BoxTypes.h.
TAxisAlignedBox3() [8/10]
template<typename RealType> UE::Geometry::TAxisAlignedBox3< RealType >::TAxisAlignedBox3 (TArrayView< const TVector< RealType > > Pts) inline
Definition at line 315 of file BoxTypes.h.
TAxisAlignedBox3() [9/10]
template<typename RealType> UE::Geometry::TAxisAlignedBox3< RealType >::TAxisAlignedBox3 (const TArray< TVector< RealType > > & Pts) inline
Definition at line 321 of file BoxTypes.h.
TAxisAlignedBox3() [10/10]
template<typename RealType> template<typename InRealType> UE::Geometry::TAxisAlignedBox3< RealType >::TAxisAlignedBox3 (const TBox< InRealType > & Box) inline
Definition at line 345 of file BoxTypes.h.
Member Function Documentation
Center()
template<typename RealType> TVector< RealType > UE::Geometry::TAxisAlignedBox3< RealType >::Center () const inline
Definition at line 414 of file BoxTypes.h.
Referenced by UE::Geometry::TOrientedBox3< float >::Merge().
Clamp()
template<typename RealType> TVector< RealType > UE::Geometry::TAxisAlignedBox3< RealType >::Clamp (const TVector< RealType > & V) const inline
Definition at line 491 of file BoxTypes.h.
Contain() [1/4]
template<typename RealType> void UE::Geometry::TAxisAlignedBox3< RealType >::Contain (const TArray< TVector< RealType > > & Pts) inline
Definition at line 473 of file BoxTypes.h.
Contain() [2/4]
template<typename RealType> void UE::Geometry::TAxisAlignedBox3< RealType >::Contain (const TAxisAlignedBox3< RealType > & Other) inline
Definition at line 455 of file BoxTypes.h.
Contain() [3/4]
template<typename RealType> void UE::Geometry::TAxisAlignedBox3< RealType >::Contain (const TVector< RealType > & V) inline
Definition at line 427 of file BoxTypes.h.
Referenced by UE::Geometry::TAxisAlignedBox3< float >::TAxisAlignedBox3(), UE::Geometry::TAxisAlignedBox3< float >::TAxisAlignedBox3(), UE::Geometry::TAxisAlignedBox3< float >::TAxisAlignedBox3(), UE::Geometry::TAxisAlignedBox3< float >::TAxisAlignedBox3(), UE::Geometry::TTetrahedron3< float >::Bounds(), UE::Geometry::TMeshSpatialSort< TriangleMeshType >::Compute(), UE::Geometry::FVertexConnectedComponents::ConnectOverlappingComponents(), UE::Geometry::TAxisAlignedBox3< float >::Contain(), UE::Geometry::TAxisAlignedBox3< float >::Contain(), UE::Geometry::TMeshQueries< TriangleMeshType >::GetBounds(), UE::Geometry::TMeshQueries< TriangleMeshType >::GetTrianglesBounds(), UE::Geometry::TMeshQueries< TriangleMeshType >::GetVerticesBounds(), UE::Geometry::IsInside(), UE::Geometry::IsInside(), and UE::Geometry::TOrientedBox3< float >::Merge().
Contain() [4/4]
template<typename RealType> void UE::Geometry::TAxisAlignedBox3< RealType >::Contain (TArrayView< const TVector< RealType > > Pts) inline
Definition at line 465 of file BoxTypes.h.
Contains() [1/2]
template<typename RealType> bool UE::Geometry::TAxisAlignedBox3< RealType >::Contains (const TAxisAlignedBox3< RealType > & Box) const inline
Definition at line 486 of file BoxTypes.h.
Contains() [2/2]
template<typename RealType> bool UE::Geometry::TAxisAlignedBox3< RealType >::Contains (const TVector< RealType > & V) const inline
Definition at line 481 of file BoxTypes.h.
Referenced by UE::Geometry::FSparseDynamicOctree3::CanFit(), UE::Geometry::FSparseDynamicPointOctree3::CellContains(), UE::Geometry::FSparseDynamicPointOctree3::CheckValidity(), UE::Geometry::TAxisAlignedBox3< float >::Contains(), UE::Geometry::FWindingNumberBasedSolidify::Generate(), UE::Geometry::TImplicitSolidify< TriangleMeshType >::Generate(), and UE::Geometry::FSparseDynamicOctree3::InitializeQueryQueue().
Depth()
template<typename RealType> RealType UE::Geometry::TAxisAlignedBox3< RealType >::Depth () const inline
Definition at line 567 of file BoxTypes.h.
Referenced by UE::Geometry::TAxisAlignedBox3< float >::MaxDim(), UE::Geometry::TAxisAlignedBox3< float >::MinDim(), UE::Geometry::FMeshPropertyMapEvaluator::PositionToColor(), UE::Geometry::TAxisAlignedBox3< float >::SurfaceArea(), and UE::Geometry::TAxisAlignedBox3< float >::Volume().
Diagonal()
template<typename RealType> TVector< RealType > UE::Geometry::TAxisAlignedBox3< RealType >::Diagonal () const inline
Definition at line 597 of file BoxTypes.h.
Referenced by UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::Compute().
DiagonalLength()
template<typename RealType> RealType UE::Geometry::TAxisAlignedBox3< RealType >::DiagonalLength () const inline
Definition at line 582 of file BoxTypes.h.
Dimension()
template<typename RealType> RealType UE::Geometry::TAxisAlignedBox3< RealType >::Dimension (int32 Index) const inline
Definition at line 552 of file BoxTypes.h.
DistanceSquared() [1/2]
template<typename RealType> RealType UE::Geometry::TAxisAlignedBox3< RealType >::DistanceSquared (const TAxisAlignedBox3< RealType > & Box) const inline
Definition at line 528 of file BoxTypes.h.
DistanceSquared() [2/2]
template<typename RealType> RealType UE::Geometry::TAxisAlignedBox3< RealType >::DistanceSquared (const TVector< RealType > & V) const inline
Definition at line 520 of file BoxTypes.h.
Referenced by UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::box_box_distsqr(), and UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::find_nearest_triangles().
Empty()
template<typename RealType> TAxisAlignedBox3< RealType > UE::Geometry::TAxisAlignedBox3< RealType >::Empty () inline static
Definition at line 371 of file BoxTypes.h.
Referenced by UE::Geometry::TAxisAlignedBox3< float >::TAxisAlignedBox3(), UE::Geometry::TDynamicPointSet3< float >::GetBounds(), UE::Geometry::TAxisAlignedBox3< float >::Intersect(), UE::Geometry::TAxisAlignedBox3< float >::MakeBoundsFromIndices(), and UE::Geometry::TAxisAlignedBox3< float >::MakeBoundsFromIndices().
Expand()
template<typename RealType> void UE::Geometry::TAxisAlignedBox3< RealType >::Expand (RealType Radius) inline
Definition at line 607 of file BoxTypes.h.
Referenced by UE::Geometry::TImplicitMorphology< TriangleMeshType >::ComputeSecondPass(), UE::Geometry::FWindingNumberBasedSolidify::Generate(), and UE::Geometry::TImplicitSolidify< TriangleMeshType >::Generate().
Extents()
template<typename RealType> TVector< RealType > UE::Geometry::TAxisAlignedBox3< RealType >::Extents () const inline
Definition at line 422 of file BoxTypes.h.
Referenced by UE::Geometry::TOrientedBox3< float >::Merge().
GetCorner()
template<typename RealType> TVector< RealType > UE::Geometry::TAxisAlignedBox3< RealType >::GetCorner (int Index) const inline
Parameters
Index corner index in range 0-7
Returns
Corner point on the box identified by the given index. See diagram in OrientedBoxTypes.h for index/corner mapping.
Definition at line 362 of file BoxTypes.h.
Height()
template<typename RealType> RealType UE::Geometry::TAxisAlignedBox3< RealType >::Height () const inline
Definition at line 562 of file BoxTypes.h.
Referenced by UE::Geometry::TAxisAlignedBox3< float >::MaxDim(), UE::Geometry::TAxisAlignedBox3< float >::MinDim(), UE::Geometry::FMeshPropertyMapEvaluator::PositionToColor(), UE::Geometry::TAxisAlignedBox3< float >::SurfaceArea(), and UE::Geometry::TAxisAlignedBox3< float >::Volume().
Infinite()
template<typename RealType> TAxisAlignedBox3< RealType > UE::Geometry::TAxisAlignedBox3< RealType >::Infinite () inline static
Definition at line 378 of file BoxTypes.h.
Intersect()
template<typename RealType> TAxisAlignedBox3< RealType > UE::Geometry::TAxisAlignedBox3< RealType >::Intersect (const TAxisAlignedBox3< RealType > & Box) const inline
Definition at line 500 of file BoxTypes.h.
Intersects()
template<typename RealType> bool UE::Geometry::TAxisAlignedBox3< RealType >::Intersects (TAxisAlignedBox3< RealType > Box) const inline
Definition at line 515 of file BoxTypes.h.
Referenced by UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::find_any_intersection(), UE::Geometry::TMeshAABBTree3< FDynamicMesh3 >::find_intersections(), UE::Geometry::FSparseDynamicOctree3::InitializeQueryQueue(), and UE::Geometry::FDynamicMeshOctree3::TestCellIntersection().
IsEmpty()
template<typename RealType> bool UE::Geometry::TAxisAlignedBox3< RealType >::IsEmpty () const inline
Definition at line 602 of file BoxTypes.h.
Referenced by UE::Geometry::TMeshWindingNumberGrid< TriangleMeshType >::Compute(), UE::Geometry::TAxisAlignedBox3< float >::operator TBox< OutRealType >(), UE::Geometry::TCachingMeshSDF< TriangleMeshType >::Validate(), UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::Validate(), and UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::Validate().
MakeBoundsFromIndices() [1/2]
template<typename RealType> template<typename EnumerableIntType, typename PointFunc> TAxisAlignedBox3< RealType > UE::Geometry::TAxisAlignedBox3< RealType >::MakeBoundsFromIndices (EnumerableIntType IndexEnumerable, PointFunc GetPoint) inline static
Compute bounding box of 3D points returned by GetPoint(Index) for indices in range for_each(IndexEnumerable)
Definition at line 403 of file BoxTypes.h.
MakeBoundsFromIndices() [2/2]
template<typename RealType> template<typename PointFunc> TAxisAlignedBox3< RealType > UE::Geometry::TAxisAlignedBox3< RealType >::MakeBoundsFromIndices (int32 MaxIndex, PointFunc GetPoint) inline static
Compute bounding box of 3D points returned by GetPoint(Index) for indices in range [0...MaxIndex)
Definition at line 389 of file BoxTypes.h.
MaxDim()
template<typename RealType> RealType UE::Geometry::TAxisAlignedBox3< RealType >::MaxDim () const inline
Definition at line 587 of file BoxTypes.h.
Referenced by UE::Geometry::FOccupancyGrid3::FOccupancyGrid3(), UE::Geometry::TMeshSpatialSort< TriangleMeshType >::Compute(), UE::Geometry::TImplicitMorphology< TriangleMeshType >::ComputeSecondPass(), UE::Geometry::FWindingNumberBasedSolidify::SetCellSizeAndExtendBounds(), UE::Geometry::TImplicitSolidify< TriangleMeshType >::SetCellSizeAndExtendBounds(), UE::Geometry::TImplicitBlend< TriangleMeshType >::SetCellSizesAndFalloff(), UE::Geometry::TImplicitMorphology< TriangleMeshType >::SetGridCellSize(), UE::Geometry::TImplicitMorphology< TriangleMeshType >::SetMeshCellSize(), UE::Geometry::TCachingMeshSDF< TriangleMeshType >::Validate(), UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::Validate(), and UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::Validate().
MinDim()
template<typename RealType> RealType UE::Geometry::TAxisAlignedBox3< RealType >::MinDim () const inline
Definition at line 592 of file BoxTypes.h.
operator TBox< OutRealType >()
template<typename RealType> template<typename OutRealType> UE::Geometry::TAxisAlignedBox3< RealType >::operator TBox< OutRealType > () const inline explicit
Definition at line 338 of file BoxTypes.h.
operator!=()
template<typename RealType> bool UE::Geometry::TAxisAlignedBox3< RealType >::operator!= (const TAxisAlignedBox3< RealType > & Other) const inline
Definition at line 331 of file BoxTypes.h.
operator==()
template<typename RealType> bool UE::Geometry::TAxisAlignedBox3< RealType >::operator== (const TAxisAlignedBox3< RealType > & Other) const inline
Definition at line 327 of file BoxTypes.h.
SurfaceArea()
template<typename RealType> RealType UE::Geometry::TAxisAlignedBox3< RealType >::SurfaceArea () const inline
Definition at line 577 of file BoxTypes.h.
Volume()
template<typename RealType> RealType UE::Geometry::TAxisAlignedBox3< RealType >::Volume () const inline
Definition at line 572 of file BoxTypes.h.
Referenced by UE::Geometry::TOrientedBox3< float >::Merge().
Width()
template<typename RealType> RealType UE::Geometry::TAxisAlignedBox3< RealType >::Width () const inline
Definition at line 557 of file BoxTypes.h.
Referenced by UE::Geometry::TAxisAlignedBox3< float >::MaxDim(), UE::Geometry::TAxisAlignedBox3< float >::MinDim(), UE::Geometry::FMeshPropertyMapEvaluator::PositionToColor(), UE::Geometry::TAxisAlignedBox3< float >::SurfaceArea(), and UE::Geometry::TAxisAlignedBox3< float >::Volume().
Field Documentation
Max
template<typename RealType> TVector<RealType> UE::Geometry::TAxisAlignedBox3< RealType >::Max
Definition at line 238 of file BoxTypes.h.
Referenced by UE::Geometry::TAxisAlignedBox3< float >::TAxisAlignedBox3(), UE::Geometry::TMeshWindingNumberGrid< TriangleMeshType >::Compute(), UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::Compute(), UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::Compute(), UE::Geometry::TCachingMeshSDF< TriangleMeshType >::Initialize(), UE::Geometry::IsInside(), UE::Geometry::TOrientedBox3< float >::Merge(), UE::Geometry::FSparseDynamicPointOctree3::ParallelRangeQuery(), and UE::Geometry::FSparseDynamicPointOctree3::RangeQuery().
Min
template<typename RealType> TVector<RealType> UE::Geometry::TAxisAlignedBox3< RealType >::Min
Definition at line 237 of file BoxTypes.h.
Referenced by UE::Geometry::TAxisAlignedBox3< float >::TAxisAlignedBox3(), UE::Geometry::TMeshWindingNumberGrid< TriangleMeshType >::Compute(), UE::Geometry::TSparseNarrowBandMeshSDF< MeshType >::Compute(), UE::Geometry::TSweepingMeshSDF< TriangleMeshType, bScalarCellSize >::Compute(), UE::Geometry::TCachingMeshSDF< TriangleMeshType >::Initialize(), UE::Geometry::IsInside(), UE::Geometry::TOrientedBox3< float >::Merge(), UE::Geometry::FSparseDynamicPointOctree3::ParallelRangeQuery(), UE::Geometry::FMeshPropertyMapEvaluator::PositionToColor(), and UE::Geometry::FSparseDynamicPointOctree3::RangeQuery().
The documentation for this struct was generated from the following file:
Runtime/GeometryCore/Public/BoxTypes.h