Unreal Engine 5.6 C++ API: FCsvParser Struct Reference
FCsvParser Struct Reference
A simple, efficient csv parser.
#include "CsvParser.h"
Public Types
typedef TArray< TArray< const TCHAR * > > FRows
Public Member Functions
FCsvParser (const FCsvParser &)=delete
FCsvParser (const FString &InSourceString)
FCsvParser (FCsvParser &&)=delete
Non copyable - has pointers to itself.
FCsvParser (FString &&InSourceString)
Construct with a string.
const FRows & GetRows () const
Const access to the parsed rows Rows are stored as arrays of parsed, null-terminated cell-strings.
FCsvParser & operator= (const FCsvParser &)=delete
FCsvParser & operator= (FCsvParser &&)=delete
Private Types
enum struct EParseResult { EndOfCell , EndOfRow , EndOfString }
Internal enum to control parsing progress.
Private Member Functions
int8 MeasureNewLine (const TCHAR *At)
Helper to measure the size of a new line at the current read position.
EParseResult ParseCell ()
Parse a cell at the current read position.
EParseResult ParseRow ()
Parse a single row at the current read position.
void ParseRows ()
Parse all the rows in the source data.
Private Attributes
TCHAR * BufferStart
Fixed pointer to the start of the buffer.
const TCHAR * ReadAt
Current parser read position.
FRows Rows
Array of cell string arrays.
FString SourceString
Raw csv buffer, sliced and diced by the parser.
Detailed Description
A simple, efficient csv parser.
Definition at line 10 of file CsvParser.h.
Member Typedef Documentation
FRows
typedef TArray<TArray<const TCHAR*> > FCsvParser::FRows
Definition at line 12 of file CsvParser.h.
Member Enumeration Documentation
EParseResult
enum struct FCsvParser::EParseResult strong private
Internal enum to control parsing progress.
Enumerator
EndOfCell
EndOfRow
EndOfString
Definition at line 40 of file CsvParser.h.
Constructor & Destructor Documentation
FCsvParser() [1/4]
FCsvParser::FCsvParser (FString && InSourceString)
Construct with a string.
Takes a copy because the parser tramples over the file to create null-terminated cell strings Avoid a copy by passing overship of the source string with MoveTemp()
Referenced by FCsvParser(), FCsvParser(), operator=(), and operator=().
FCsvParser() [2/4]
FCsvParser::FCsvParser (const FString & InSourceString)
FCsvParser() [3/4]
FCsvParser::FCsvParser (FCsvParser &&) delete
Non copyable - has pointers to itself.
References FCsvParser().
FCsvParser() [4/4]
FCsvParser::FCsvParser (const FCsvParser &) delete
References FCsvParser().
Member Function Documentation
GetRows()
const FRows & FCsvParser::GetRows () const inline
Const access to the parsed rows Rows are stored as arrays of parsed, null-terminated cell-strings.
Object (and contained strings) is valid for the lifetime of the parser.
Definition at line 27 of file CsvParser.h.
References Rows.
MeasureNewLine()
int8 FCsvParser::MeasureNewLine (const TCHAR * At) private
Helper to measure the size of a new line at the current read position.
operator=() [1/2]
FCsvParser & FCsvParser::operator= (const FCsvParser &) delete
References FCsvParser().
operator=() [2/2]
FCsvParser & FCsvParser::operator= (FCsvParser &&) delete
References FCsvParser().
ParseCell()
EParseResult FCsvParser::ParseCell () private
Parse a cell at the current read position.
ParseRow()
EParseResult FCsvParser::ParseRow () private
Parse a single row at the current read position.
ParseRows()
void FCsvParser::ParseRows () private
Parse all the rows in the source data.
Field Documentation
BufferStart
TCHAR* FCsvParser::BufferStart private
Fixed pointer to the start of the buffer.
Definition at line 57 of file CsvParser.h.
ReadAt
const TCHAR* FCsvParser::ReadAt private
Current parser read position.
Definition at line 60 of file CsvParser.h.
Rows
FRows FCsvParser::Rows private
Array of cell string arrays.
Definition at line 63 of file CsvParser.h.
Referenced by GetRows().
SourceString
FString FCsvParser::SourceString private
Raw csv buffer, sliced and diced by the parser.
Definition at line 54 of file CsvParser.h.
The documentation for this struct was generated from the following file:
Runtime/Core/Public/Serialization/Csv/CsvParser.h