Unreal Engine 5.6 C++ API: TBitArray< Allocator >::TSupportsFreezeMemoryImageHelper< bFreezeMemoryImage, Dummy > Struct Template Reference
TBitArray< Allocator >::TSupportsFreezeMemoryImageHelper< bFreezeMemoryImage, Dummy > Struct Template Reference
Static Public Member Functions
static void WriteMemoryImage (FMemoryImageWriter &Writer, const TBitArray &)
Detailed Description
template<typename Allocator>
template<bool bFreezeMemoryImage, typename Dummy = void>
struct TBitArray< Allocator >::TSupportsFreezeMemoryImageHelper< bFreezeMemoryImage, Dummy >
Definition at line 1862 of file BitArray.h.
Member Function Documentation
WriteMemoryImage()
template<typename Allocator> template<bool bFreezeMemoryImage, typename Dummy = void> void TBitArray< Allocator >::TSupportsFreezeMemoryImageHelper< bFreezeMemoryImage, Dummy >::WriteMemoryImage (FMemoryImageWriter & Writer, const TBitArray &) inline static
Definition at line 1864 of file BitArray.h.
References TBitArray< Allocator >::TBitArray(), and FMemoryImageWriter::WriteBytes().
Referenced by TBitArray< typename Allocator::BitArrayAllocator >::WriteMemoryImage().
The documentation for this struct was generated from the following file:
Runtime/Core/Public/Containers/BitArray.h