Unreal Engine 5.6 C++ API: TNetworkPhysicsDataHelper< DataType > Struct Template Reference
TNetworkPhysicsDataHelper< DataType > Struct Template Reference
Helper for the creation of state / input data and history with correct derived type.
#include "NetworkPhysicsComponent.h"
Public Member Functions
virtual ~TNetworkPhysicsDataHelper ()=default
virtual TUniquePtr< FNetworkPhysicsDataHelper > Clone () const
virtual void CopyData (FNetworkPhysicsData *To, FNetworkPhysicsData *From)
virtual TUniquePtr< FNetworkPhysicsData > CreateUniqueData () const
virtual TUniquePtr< Chaos::FBaseRewindHistory > CreateUniqueRewindHistory (const int32 Size) const
Public Member Functions inherited from FNetworkPhysicsDataHelper
virtual ~FNetworkPhysicsDataHelper ()=default
Detailed Description
template<typename DataType>
struct TNetworkPhysicsDataHelper< DataType >
Helper for the creation of state / input data and history with correct derived type.
Definition at line 873 of file NetworkPhysicsComponent.h.
Constructor & Destructor Documentation
~TNetworkPhysicsDataHelper()
template<typename DataType> virtual TNetworkPhysicsDataHelper< DataType >::~TNetworkPhysicsDataHelper () virtual default
Member Function Documentation
Clone()
template<typename DataType> virtual TUniquePtr< FNetworkPhysicsDataHelper > TNetworkPhysicsDataHelper< DataType >::Clone () const inline virtual
Implements FNetworkPhysicsDataHelper.
Definition at line 877 of file NetworkPhysicsComponent.h.
References MakeUnique().
CopyData()
template<typename DataType> virtual void TNetworkPhysicsDataHelper< DataType >::CopyData (FNetworkPhysicsData * To, FNetworkPhysicsData * From) inline virtual
Implements FNetworkPhysicsDataHelper.
Definition at line 879 of file NetworkPhysicsComponent.h.
CreateUniqueData()
template<typename DataType> virtual TUniquePtr< FNetworkPhysicsData > TNetworkPhysicsDataHelper< DataType >::CreateUniqueData () const inline virtual
Implements FNetworkPhysicsDataHelper.
Definition at line 878 of file NetworkPhysicsComponent.h.
References MakeUnique().
CreateUniqueRewindHistory()
template<typename DataType> virtual TUniquePtr< Chaos::FBaseRewindHistory > TNetworkPhysicsDataHelper< DataType >::CreateUniqueRewindHistory (const int32 Size) const inline virtual
Implements FNetworkPhysicsDataHelper.
Definition at line 883 of file NetworkPhysicsComponent.h.
References MakeUnique(), and TSequenceHistory< HistorySize >::Size.
The documentation for this struct was generated from the following file:
Runtime/Engine/Public/Physics/NetworkPhysicsComponent.h