Unreal Engine 5.6 C++ API: Experimental::TSherwoodHashTable_Private::TSherwoodHashTable< KeyType, ValueType, KeyFuncs > Struct Template Reference
Experimental::TSherwoodHashTable_Private::TSherwoodHashTable< KeyType, ValueType, KeyFuncs > Struct Template Reference
Implementation of Robin Hood hash table based on sherwood_v3_table by Malte Skarupke.
#include "SherwoodHashTable.h"
Data Structures
struct FData
Public Types
using HashType = uint32
Public Member Functions
TSherwoodHashTable ()=default
TSherwoodHashTable (const TSherwoodHashTable &)=delete
TSherwoodHashTable (TSherwoodHashTable &&)=delete
~TSherwoodHashTable ()
FORCENOINLINE ValueType * Add (int8 Distance, FData &Data, uint32 Cursor, KeyType Key, HashType Hash, ValueType Value)
void Empty ()
FORCEINLINE_DEBUGGABLE TTuple< const KeyType *, ValueType * > Find (KeyType Key) const
FORCEINLINE_DEBUGGABLE ValueType * FindOrAdd (KeyType Key, ValueType Value, bool *bIsAlreadyInContainerPtr=nullptr)
FORCEINLINE_DEBUGGABLE ValueType * FindOrAddByHash (KeyType Key, HashType Hash, ValueType Value, bool *bIsAlreadyInContainerPtr=nullptr)
void Grow ()
uint32 NumSlots () const
TSherwoodHashTable & operator= (const TSherwoodHashTable &)=delete
TSherwoodHashTable & operator= (TSherwoodHashTable &&)=delete
void Rehash (uint32 DesiredNumSlots)
void Reserve (uint32 DesiredNumElements)
void Reset ()
Static Public Member Functions
static FData AllocateData (uint32 Count)
template<typename T>
static T * AllocateUninitialized (uint32 Count)
static uint8 ComputeMaxLookups (uint32 InNumSlots)
static void Deallocate (void *Ptr)
static void DeallocateData (FData &Data)
Data Fields
FData CurrentData
int8 MaxLookups = 0
int32 NumElements = 0
uint32 NumSlotsMinusOne = 0
Static Public Attributes
static constexpr bool bIsMap = !std::is_same_v<ValueType, FNoopStruct>
static constexpr float MaxLoadFactor = 0.9f
static constexpr uint32 MinNumLookups = 4
static constexpr uint32 MinNumSlots = 4
Detailed Description
template<typename KeyType, typename ValueType, typename KeyFuncs = TSherwoodHashKeyFuncs<KeyType, ValueType>>
struct Experimental::TSherwoodHashTable_Private::TSherwoodHashTable< KeyType, ValueType, KeyFuncs >
Implementation of Robin Hood hash table based on sherwood_v3_table by Malte Skarupke.
Good for small keys and values. If key is already a high quality hash, then identity hash function should be used. Current limitations:
Requires key and value to be trivial types.
Does not allow move or copy.
Does not support custom allocators.
Definition at line 38 of file SherwoodHashTable.h.
Member Typedef Documentation
HashType
template<typename KeyType, typename ValueType, typename KeyFuncs = TSherwoodHashKeyFuncs<KeyType, ValueType>> using Experimental::TSherwoodHashTable_Private::TSherwoodHashTable< KeyType, ValueType, KeyFuncs >::HashType = uint32
Definition at line 40 of file SherwoodHashTable.h.
Constructor & Destructor Documentation
TSherwoodHashTable() [1/3]
template<typename KeyType, typename ValueType, typename KeyFuncs = TSherwoodHashKeyFuncs<KeyType, ValueType>> Experimental::TSherwoodHashTable_Private::TSherwoodHashTable< KeyType, ValueType, KeyFuncs >::TSherwoodHashTable () default
Referenced by TSherwoodHashTable(), TSherwoodHashTable(), operator=(), and operator=().
TSherwoodHashTable() [2/3]
template<typename KeyType, typename ValueType, typename KeyFuncs = TSherwoodHashKeyFuncs<KeyType, ValueType>> Experimental::TSherwoodHashTable_Private::TSherwoodHashTable< KeyType, ValueType, KeyFuncs >::TSherwoodHashTable (const TSherwoodHashTable< KeyType, ValueType, KeyFuncs > &) delete
References TSherwoodHashTable().
TSherwoodHashTable() [3/3]
template<typename KeyType, typename ValueType, typename KeyFuncs = TSherwoodHashKeyFuncs<KeyType, ValueType>> Experimental::TSherwoodHashTable_Private::TSherwoodHashTable< KeyType, ValueType, KeyFuncs >::TSherwoodHashTable (TSherwoodHashTable< KeyType, ValueType, KeyFuncs > &&) delete
References TSherwoodHashTable().
~TSherwoodHashTable()
template<typename KeyType, typename ValueType, typename KeyFuncs = TSherwoodHashKeyFuncs<KeyType, ValueType>> Experimental::TSherwoodHashTable_Private::TSherwoodHashTable< KeyType, ValueType, KeyFuncs >::~TSherwoodHashTable () inline
Definition at line 65 of file SherwoodHashTable.h.
References Empty().
Member Function Documentation
Add()
template<typename KeyType, typename ValueType, typename KeyFuncs = TSherwoodHashKeyFuncs<KeyType, ValueType>> FORCENOINLINE ValueType * Experimental::TSherwoodHashTable_Private::TSherwoodHashTable< KeyType, ValueType, KeyFuncs >::Add (int8 Distance, FData & Data, uint32 Cursor, KeyType Key, HashType Hash, ValueType Value) inline
Definition at line 227 of file SherwoodHashTable.h.
References Experimental::TSherwoodHashTable_Private::TSherwoodHashTable< KeyType, ValueType, KeyFuncs >::FData::AddAt(), bIsMap, Distance, Experimental::TSherwoodHashTable_Private::TSherwoodHashTable< KeyType, ValueType, KeyFuncs >::FData::Distances, FindOrAdd(), FindOrAddByHash(), FORCENOINLINE, Grow(), Hash, Experimental::TSherwoodHashTable_Private::TSherwoodHashTable< KeyType, ValueType, KeyFuncs >::FData::IsEmpty(), Key, Experimental::TSherwoodHashTable_Private::TSherwoodHashTable< KeyType, ValueType, KeyFuncs >::FData::Keys, MaxLoadFactor, MaxLookups, NumElements, NumSlotsMinusOne, Swap, Value, and Experimental::TSherwoodHashTable_Private::TSherwoodHashTable< KeyType, ValueType, KeyFuncs >::FData::Values.
AllocateData()
template<typename KeyType, typename ValueType, typename KeyFuncs = TSherwoodHashKeyFuncs<KeyType, ValueType>> FData Experimental::TSherwoodHashTable_Private::TSherwoodHashTable< KeyType, ValueType, KeyFuncs >::AllocateData (uint32 Count) inline static
Definition at line 158 of file SherwoodHashTable.h.
References AllocateUninitialized(), bIsMap, Count, and FMemory::Memset().
Referenced by Rehash().
AllocateUninitialized()
template<typename KeyType, typename ValueType, typename KeyFuncs = TSherwoodHashKeyFuncs<KeyType, ValueType>> template<typename T> T * Experimental::TSherwoodHashTable_Private::TSherwoodHashTable< KeyType, ValueType, KeyFuncs >::AllocateUninitialized (uint32 Count) inline static
Definition at line 71 of file SherwoodHashTable.h.
References Count.
Referenced by AllocateData().
ComputeMaxLookups()
template<typename KeyType, typename ValueType, typename KeyFuncs = TSherwoodHashKeyFuncs<KeyType, ValueType>> uint8 Experimental::TSherwoodHashTable_Private::TSherwoodHashTable< KeyType, ValueType, KeyFuncs >::ComputeMaxLookups (uint32 InNumSlots) inline static
Definition at line 152 of file SherwoodHashTable.h.
References FMath::Max, and MinNumLookups.
Referenced by Rehash().
Deallocate()
template<typename KeyType, typename ValueType, typename KeyFuncs = TSherwoodHashKeyFuncs<KeyType, ValueType>> void Experimental::TSherwoodHashTable_Private::TSherwoodHashTable< KeyType, ValueType, KeyFuncs >::Deallocate (void * Ptr) inline static
Definition at line 76 of file SherwoodHashTable.h.
References FMemory::Free().
Referenced by DeallocateData().
DeallocateData()
template<typename KeyType, typename ValueType, typename KeyFuncs = TSherwoodHashKeyFuncs<KeyType, ValueType>> void Experimental::TSherwoodHashTable_Private::TSherwoodHashTable< KeyType, ValueType, KeyFuncs >::DeallocateData (FData & Data) inline static
Definition at line 116 of file SherwoodHashTable.h.
References Deallocate(), Experimental::TSherwoodHashTable_Private::TSherwoodHashTable< KeyType, ValueType, KeyFuncs >::FData::Distances, Experimental::TSherwoodHashTable_Private::TSherwoodHashTable< KeyType, ValueType, KeyFuncs >::FData::IsValid(), Experimental::TSherwoodHashTable_Private::TSherwoodHashTable< KeyType, ValueType, KeyFuncs >::FData::Keys, and Experimental::TSherwoodHashTable_Private::TSherwoodHashTable< KeyType, ValueType, KeyFuncs >::FData::Values.
Referenced by Empty(), and Rehash().
Empty()
template<typename KeyType, typename ValueType, typename KeyFuncs = TSherwoodHashKeyFuncs<KeyType, ValueType>> void Experimental::TSherwoodHashTable_Private::TSherwoodHashTable< KeyType, ValueType, KeyFuncs >::Empty () inline
Definition at line 137 of file SherwoodHashTable.h.
References CurrentData, DeallocateData(), MaxLookups, NumElements, and NumSlotsMinusOne.
Referenced by ~TSherwoodHashTable(), and Rehash().
Find()
template<typename KeyType, typename ValueType, typename KeyFuncs = TSherwoodHashKeyFuncs<KeyType, ValueType>> FORCEINLINE_DEBUGGABLE TTuple< const KeyType *, ValueType * > Experimental::TSherwoodHashTable_Private::TSherwoodHashTable< KeyType, ValueType, KeyFuncs >::Find (KeyType Key) const inline
Definition at line 175 of file SherwoodHashTable.h.
References bIsMap, CurrentData, Distance, FORCEINLINE_DEBUGGABLE, Key, and NumSlotsMinusOne.
FindOrAdd()
template<typename KeyType, typename ValueType, typename KeyFuncs = TSherwoodHashKeyFuncs<KeyType, ValueType>> FORCEINLINE_DEBUGGABLE ValueType * Experimental::TSherwoodHashTable_Private::TSherwoodHashTable< KeyType, ValueType, KeyFuncs >::FindOrAdd (KeyType Key, ValueType Value, bool * bIsAlreadyInContainerPtr = nullptr) inline
Definition at line 194 of file SherwoodHashTable.h.
References FindOrAddByHash(), FORCEINLINE_DEBUGGABLE, Key, and Value.
Referenced by Add(), and Rehash().
FindOrAddByHash()
template<typename KeyType, typename ValueType, typename KeyFuncs = TSherwoodHashKeyFuncs<KeyType, ValueType>> FORCEINLINE_DEBUGGABLE ValueType * Experimental::TSherwoodHashTable_Private::TSherwoodHashTable< KeyType, ValueType, KeyFuncs >::FindOrAddByHash (KeyType Key, HashType Hash, ValueType Value, bool * bIsAlreadyInContainerPtr = nullptr) inline
Definition at line 199 of file SherwoodHashTable.h.
References Add, bIsMap, CurrentData, Distance, FORCEINLINE_DEBUGGABLE, Hash, Key, NumSlotsMinusOne, and Value.
Referenced by Add(), and FindOrAdd().
Grow()
template<typename KeyType, typename ValueType, typename KeyFuncs = TSherwoodHashKeyFuncs<KeyType, ValueType>> void Experimental::TSherwoodHashTable_Private::TSherwoodHashTable< KeyType, ValueType, KeyFuncs >::Grow () inline
Definition at line 333 of file SherwoodHashTable.h.
References FMath::Max, MinNumSlots, NumSlots(), and Rehash().
Referenced by Add().
NumSlots()
template<typename KeyType, typename ValueType, typename KeyFuncs = TSherwoodHashKeyFuncs<KeyType, ValueType>> uint32 Experimental::TSherwoodHashTable_Private::TSherwoodHashTable< KeyType, ValueType, KeyFuncs >::NumSlots () const inline
Definition at line 147 of file SherwoodHashTable.h.
References NumSlotsMinusOne.
Referenced by Grow(), Rehash(), and Reserve().
operator=() [1/2]
template<typename KeyType, typename ValueType, typename KeyFuncs = TSherwoodHashKeyFuncs<KeyType, ValueType>> TSherwoodHashTable & Experimental::TSherwoodHashTable_Private::TSherwoodHashTable< KeyType, ValueType, KeyFuncs >::operator= (const TSherwoodHashTable< KeyType, ValueType, KeyFuncs > &) delete
References TSherwoodHashTable().
operator=() [2/2]
template<typename KeyType, typename ValueType, typename KeyFuncs = TSherwoodHashKeyFuncs<KeyType, ValueType>> TSherwoodHashTable & Experimental::TSherwoodHashTable_Private::TSherwoodHashTable< KeyType, ValueType, KeyFuncs >::operator= (TSherwoodHashTable< KeyType, ValueType, KeyFuncs > &&) delete
References TSherwoodHashTable().
Rehash()
template<typename KeyType, typename ValueType, typename KeyFuncs = TSherwoodHashKeyFuncs<KeyType, ValueType>> void Experimental::TSherwoodHashTable_Private::TSherwoodHashTable< KeyType, ValueType, KeyFuncs >::Rehash (uint32 DesiredNumSlots) inline
Definition at line 287 of file SherwoodHashTable.h.
References AllocateData(), bIsMap, ComputeMaxLookups(), CurrentData, DeallocateData(), Empty(), End, FindOrAdd(), Experimental::TSherwoodHashTable_Private::TSherwoodHashTable< KeyType, ValueType, KeyFuncs >::FData::HasValue(), Experimental::TSherwoodHashTable_Private::TSherwoodHashTable< KeyType, ValueType, KeyFuncs >::FData::Keys, FMath::Max, MaxLoadFactor, MaxLookups, NumElements, NumSlots(), NumSlotsMinusOne, and Experimental::TSherwoodHashTable_Private::TSherwoodHashTable< KeyType, ValueType, KeyFuncs >::FData::Values.
Referenced by Grow(), and Reserve().
Reserve()
template<typename KeyType, typename ValueType, typename KeyFuncs = TSherwoodHashKeyFuncs<KeyType, ValueType>> void Experimental::TSherwoodHashTable_Private::TSherwoodHashTable< KeyType, ValueType, KeyFuncs >::Reserve (uint32 DesiredNumElements) inline
Definition at line 339 of file SherwoodHashTable.h.
References FMath::Max, MaxLoadFactor, NumSlots(), and Rehash().
Reset()
template<typename KeyType, typename ValueType, typename KeyFuncs = TSherwoodHashKeyFuncs<KeyType, ValueType>> void Experimental::TSherwoodHashTable_Private::TSherwoodHashTable< KeyType, ValueType, KeyFuncs >::Reset () inline
Definition at line 128 of file SherwoodHashTable.h.
References CurrentData, FMemory::Memset(), and NumElements.
Field Documentation
bIsMap
template<typename KeyType, typename ValueType, typename KeyFuncs = TSherwoodHashKeyFuncs<KeyType, ValueType>> bool Experimental::TSherwoodHashTable_Private::TSherwoodHashTable< KeyType, ValueType, KeyFuncs >::bIsMap = !std::is_same_v<ValueType, FNoopStruct> static constexpr
Definition at line 44 of file SherwoodHashTable.h.
Referenced by Add(), Experimental::TSherwoodHashTable_Private::TSherwoodHashTable< KeyType, ValueType, KeyFuncs >::FData::AddAt(), AllocateData(), Find(), FindOrAddByHash(), and Rehash().
CurrentData
template<typename KeyType, typename ValueType, typename KeyFuncs = TSherwoodHashKeyFuncs<KeyType, ValueType>> FData Experimental::TSherwoodHashTable_Private::TSherwoodHashTable< KeyType, ValueType, KeyFuncs >::CurrentData
Definition at line 111 of file SherwoodHashTable.h.
Referenced by Empty(), Find(), FindOrAddByHash(), Rehash(), and Reset().
MaxLoadFactor
template<typename KeyType, typename ValueType, typename KeyFuncs = TSherwoodHashKeyFuncs<KeyType, ValueType>> float Experimental::TSherwoodHashTable_Private::TSherwoodHashTable< KeyType, ValueType, KeyFuncs >::MaxLoadFactor = 0.9f static constexpr
Definition at line 53 of file SherwoodHashTable.h.
Referenced by Add(), Rehash(), and Reserve().
MaxLookups
template<typename KeyType, typename ValueType, typename KeyFuncs = TSherwoodHashKeyFuncs<KeyType, ValueType>> int8 Experimental::TSherwoodHashTable_Private::TSherwoodHashTable< KeyType, ValueType, KeyFuncs >::MaxLookups = 0
Definition at line 113 of file SherwoodHashTable.h.
Referenced by Add(), Empty(), and Rehash().
MinNumLookups
template<typename KeyType, typename ValueType, typename KeyFuncs = TSherwoodHashKeyFuncs<KeyType, ValueType>> uint32 Experimental::TSherwoodHashTable_Private::TSherwoodHashTable< KeyType, ValueType, KeyFuncs >::MinNumLookups = 4 static constexpr
Definition at line 47 of file SherwoodHashTable.h.
Referenced by ComputeMaxLookups().
MinNumSlots
template<typename KeyType, typename ValueType, typename KeyFuncs = TSherwoodHashKeyFuncs<KeyType, ValueType>> uint32 Experimental::TSherwoodHashTable_Private::TSherwoodHashTable< KeyType, ValueType, KeyFuncs >::MinNumSlots = 4 static constexpr
Definition at line 50 of file SherwoodHashTable.h.
Referenced by Grow().
NumElements
template<typename KeyType, typename ValueType, typename KeyFuncs = TSherwoodHashKeyFuncs<KeyType, ValueType>> int32 Experimental::TSherwoodHashTable_Private::TSherwoodHashTable< KeyType, ValueType, KeyFuncs >::NumElements = 0
Definition at line 114 of file SherwoodHashTable.h.
Referenced by Add(), Empty(), Rehash(), and Reset().
NumSlotsMinusOne
template<typename KeyType, typename ValueType, typename KeyFuncs = TSherwoodHashKeyFuncs<KeyType, ValueType>> uint32 Experimental::TSherwoodHashTable_Private::TSherwoodHashTable< KeyType, ValueType, KeyFuncs >::NumSlotsMinusOne = 0
Definition at line 112 of file SherwoodHashTable.h.
Referenced by Add(), Empty(), Find(), FindOrAddByHash(), NumSlots(), and Rehash().
The documentation for this struct was generated from the following file:
Runtime/Core/Public/Experimental/Containers/SherwoodHashTable.h