Unreal Engine 5.6 C++ API: FFrame Struct Reference
FFrame Struct Reference
#include "Stack.h"
Public Member Functions
FFrame (UObject *InObject, UFunction *InNode, void *InLocals, FFrame *InPreviousFrame=NULL, FField *InPropertyChainForCompiledIn=NULL)
virtual ~FFrame ()
void GetStackDescription (FStringBuilderBase &StringBuilder) const
This will append a string of the form "ScopeName.FunctionName" associated with this stack frame.
FString GetStackTrace () const
This will return the StackTrace of the current callstack from the last native entry point.
void GetStackTrace (FStringBuilderBase &StringBuilder) const
This will return the StackTrace of the current callstack from the last native entry point.
const uint8 PeekCode () const
Returns the current script op code.
template<typename T>
T Read ()
CodeSkipSizeType ReadCodeSkipCount ()
Reads a value from the bytestream, which represents the number of bytes to advance the code pointer for certain expressions.
double ReadDouble ()
float ReadFloat ()
template<typename TNumericType>
TNumericType ReadInt ()
FName ReadName ()
UObject * ReadObject ()
ScriptPointerType ReadPointer ()
FProperty * ReadProperty ()
FProperty * ReadPropertyUnchecked ()
May return null.
VariableSizeType ReadVariableSize (FProperty **ExpressionField)
Reads a value from the bytestream which represents the number of bytes that should be zero'd out if a NULL context is encountered.
int32 ReadWord ()
virtual void Serialize (const TCHAR *V, ELogVerbosity::Type Verbosity, const class FName &Category) override
void SkipCode (const int32 NumOps)
Skips over the number of op codes specified by NumOps.
void Step (UObject *Context, RESULT_DECL)
FORCEINLINE_DEBUGGABLE bool StepAndCheckMostRecentProperty (UObject *Context, RESULT_DECL)
Convenience function that calls Step, but also returns true if both MostRecentProperty and MostRecentPropertyAddress are non-null.
template<class TProperty>
FORCEINLINE_DEBUGGABLE void StepCompiledIn (void *Result)
Replacement for Step that checks the for byte code, and if none exists, then PropertyChainForCompiledIn is used.
FORCEINLINE_DEBUGGABLE void StepCompiledIn (void *Result, const FFieldClass *ExpectedPropertyType)
template<class TProperty, typename TNativeType>
FORCEINLINE_DEBUGGABLE TNativeType & StepCompiledInRef (void *const TemporaryBuffer)
Replacement for Step that checks the for byte code, and if none exists, then PropertyChainForCompiledIn is used.
void StepExplicitProperty (void *const Result, FProperty *Property)
Replacement for Step that uses an explicitly specified property to unpack arguments.
UE_DEPRECATED (5.1, "Please use GetStackDescription(FStringBuilderBase&).") 1 FString GetStackDescription() const
This will return a string of the form "ScopeName.FunctionName" associated with this stack frame:
Public Member Functions inherited from FOutputDevice
FOutputDevice ()
FOutputDevice (const FOutputDevice &)
FOutputDevice (FOutputDevice &&)
virtual ~FOutputDevice ()
virtual bool CanBeUsedOnAnyThread () const
virtual bool CanBeUsedOnMultipleThreads () const
virtual bool CanBeUsedOnPanicThread () const
template<typename FmtType, typename... Types>
FORCEINLINE void CategorizedLogf (const FName &Category, ELogVerbosity::Type Verbosity, const FmtType &Fmt, Types... Args)
virtual void Dump (class FArchive &Ar)
Dumps the contents of this output device's buffer to an archive (supported by output device that have a memory buffer)
virtual void Flush ()
FORCEINLINE bool GetAutoEmitLineTerminator () const
FORCEINLINE bool GetSuppressEventTag () const
virtual bool IsMemoryOnly () const
void Log (const FName &Category, ELogVerbosity::Type Verbosity, const FString &S)
void Log (const FName &Category, ELogVerbosity::Type Verbosity, const TCHAR *Str)
void Log (const FString &S)
void Log (const FText &S)
void Log (const TCHAR *S)
void Log (ELogVerbosity::Type Verbosity, const FString &S)
void Log (ELogVerbosity::Type Verbosity, const TCHAR *S)
template<typename FmtType>
void Logf (const FmtType &Fmt)
template<typename FmtType, typename... Types>
FORCEINLINE void Logf (const FmtType &Fmt, Types... Args)
template<typename FmtType, typename... Types>
FORCEINLINE void Logf (ELogVerbosity::Type Verbosity, const FmtType &Fmt, Types... Args)
FOutputDevice & operator= (const FOutputDevice &)
FOutputDevice & operator= (FOutputDevice &&)
virtual void Serialize (const TCHAR *V, ELogVerbosity::Type Verbosity, const FName &Category)=0
virtual void Serialize (const TCHAR *V, ELogVerbosity::Type Verbosity, const FName &Category, const double Time)
virtual void SerializeRecord (const UE::FLogRecord &Record)
void SetAutoEmitLineTerminator (bool bInAutoEmitLineTerminator)
void SetSuppressEventTag (bool bInSuppressEventTag)
virtual void TearDown ()
Closes output device and cleans up.
Static Public Member Functions
static FString GetScriptCallstack (bool bReturnEmpty=false, bool bTopOfStackOnly=false)
This will return the StackTrace of the all script frames currently active.
static void GetScriptCallstack (FStringBuilderBase &StringBuilder, bool bReturnEmpty=false, bool bTopOfStackOnly=false)
This will return the StackTrace of the all script frames currently active.
static FFrame * GetThreadLocalTopStackFrame ()
static void KismetExecutionMessage (const TCHAR *Message, ELogVerbosity::Type Verbosity, FName WarningId=FName())
static void PopThreadLocalTopStackFrame (FFrame *NewTopStackFrame)
static FFrame * PushThreadLocalTopStackFrame (FFrame *NewTopStackFrame)
Data Fields
bool bAbortingExecution
If this flag gets set (usually from throwing a EBlueprintExceptionType::AbortExecution exception), execution shall immediately stop and return.
bool bArrayContextFailed
uint8 * Code
UFunction * CurrentNativeFunction
Currently executed native function.
FlowStackType FlowStack
The execution flow stack for compiled Kismet code.
uint8 * Locals
FProperty * MostRecentProperty
uint8 * MostRecentPropertyAddress
uint8 * MostRecentPropertyContainer
UFunction * Node
UObject * Object
FOutParmRec * OutParms
contains information on any out parameters
FFrame * PreviousFrame
Previous frame on the stack.
FFrame * PreviousTrackingFrame
Previous tracking frame.
FField * PropertyChainForCompiledIn
If a class is compiled in then this is set to the property chain for compiled-in functions.
Additional Inherited Members
Protected Attributes inherited from FOutputDevice
bool bAutoEmitLineTerminator
Whether to output a line-terminator after each log call...
bool bSuppressEventTag
Whether to output the 'Log: ' type front...
Detailed Description
Definition at line 113 of file Stack.h.
Constructor & Destructor Documentation
FFrame()
FFrame::FFrame (UObject * InObject, UFunction * InNode, void * InLocals, FFrame * InPreviousFrame = NULL, FField * InPropertyChainForCompiledIn = NULL) inline
Definition at line 308 of file Stack.h.
References FFrame(), bAbortingExecution, bArrayContextFailed, Code, CurrentNativeFunction, GetData(), FBlueprintContext::GetThreadSingleton(), FBlueprintContext::GetVirtualStackAllocator(), Locals, MAX_uint8, MostRecentProperty, MostRecentPropertyAddress, MostRecentPropertyContainer, Node, Object, OutParms, PER_FUNCTION_SCRIPT_STATS, PreviousFrame, PreviousTrackingFrame, PropertyChainForCompiledIn, and PushThreadLocalTopStackFrame().
Referenced by FFrame(), GetThreadLocalTopStackFrame(), PopThreadLocalTopStackFrame(), and PushThreadLocalTopStackFrame().
~FFrame()
virtual FFrame::~FFrame () inline virtual
Definition at line 162 of file Stack.h.
References bAbortingExecution, ensure, No, PopThreadLocalTopStackFrame(), and PreviousTrackingFrame.
Member Function Documentation
GetScriptCallstack() [1/2]
FString FFrame::GetScriptCallstack (bool bReturnEmpty = false, bool bTopOfStackOnly = false) static
This will return the StackTrace of the all script frames currently active.
Parameters
bReturnEmpty if true, returns empty string when no script callstack found
bTopOfStackOnly if true only returns the top of the callstack
GetScriptCallstack() [2/2]
void FFrame::GetScriptCallstack (FStringBuilderBase & StringBuilder, bool bReturnEmpty = false, bool bTopOfStackOnly = false) static
This will return the StackTrace of the all script frames currently active.
Parameters
StringBuilder to populate
bReturnEmpty if true, returns empty string when no script callstack found
bTopOfStackOnly if true only returns the top of the callstack
GetStackDescription()
void FFrame::GetStackDescription (FStringBuilderBase & StringBuilder) const
This will append a string of the form "ScopeName.FunctionName" associated with this stack frame.
Parameters
StringBuilder to populate
References GetStackDescription().
Referenced by GetStackDescription(), and UE_DEPRECATED().
GetStackTrace() [1/2]
FString FFrame::GetStackTrace () const
This will return the StackTrace of the current callstack from the last native entry point.
GetStackTrace() [2/2]
void FFrame::GetStackTrace (FStringBuilderBase & StringBuilder) const
This will return the StackTrace of the current callstack from the last native entry point.
Parameters
StringBuilder to populate
GetThreadLocalTopStackFrame()
FFrame * FFrame::GetThreadLocalTopStackFrame () static
References FFrame().
KismetExecutionMessage()
void FFrame::KismetExecutionMessage (const TCHAR * Message, ELogVerbosity::Type Verbosity, FName WarningId = FName()) static
Referenced by UKismetMathLibrary::DECLARE_FUNCTION().
PeekCode()
const uint8 FFrame::PeekCode () const inline
Returns the current script op code.
Definition at line 214 of file Stack.h.
References Code.
PopThreadLocalTopStackFrame()
void FFrame::PopThreadLocalTopStackFrame (FFrame * NewTopStackFrame) static
References FFrame().
Referenced by ~FFrame().
PushThreadLocalTopStackFrame()
FFrame * FFrame::PushThreadLocalTopStackFrame (FFrame * NewTopStackFrame) static
References FFrame().
Referenced by FFrame().
Read()
template<typename T> T FFrame::Read () inline
Definition at line 363 of file Stack.h.
References Code, and FGenericPlatformMemory::ReadUnaligned().
Referenced by ReadDouble(), ReadFloat(), ReadInt(), and ReadWord().
ReadCodeSkipCount()
CodeSkipSizeType FFrame::ReadCodeSkipCount () inline
Reads a value from the bytestream, which represents the number of bytes to advance the code pointer for certain expressions.
Parameters
ExpressionField receives a pointer to the field representing the expression; used by various execs to drive VM logic
Definition at line 433 of file Stack.h.
References Code, and FGenericPlatformMemory::ReadUnaligned().
ReadDouble()
double FFrame::ReadDouble () inline
Definition at line 410 of file Stack.h.
References Read().
ReadFloat()
float FFrame::ReadFloat () inline
Definition at line 405 of file Stack.h.
References Read().
ReadInt()
template<typename TNumericType> TNumericType FFrame::ReadInt () inline
Definition at line 371 of file Stack.h.
References Read().
ReadName()
FName FFrame::ReadName () inline
Definition at line 459 of file Stack.h.
References Code, FGenericPlatformMemory::ReadUnaligned(), and ScriptNameToName().
ReadObject()
UObject * FFrame::ReadObject () inline
Definition at line 376 of file Stack.h.
References TObjectPtr< T >::Get(), and ReadPointer().
ReadPointer()
ScriptPointerType FFrame::ReadPointer () inline
Definition at line 415 of file Stack.h.
References Code, Pointer, and FGenericPlatformMemory::ReadUnaligned().
Referenced by ReadObject(), and ReadPropertyUnchecked().
ReadProperty()
FProperty * FFrame::ReadProperty () inline
Definition at line 388 of file Stack.h.
References check, and ReadPropertyUnchecked().
ReadPropertyUnchecked()
FProperty * FFrame::ReadPropertyUnchecked () inline
May return null.
Definition at line 398 of file Stack.h.
References MostRecentProperty, and ReadPointer().
Referenced by ReadProperty(), and ReadVariableSize().
ReadVariableSize()
VariableSizeType FFrame::ReadVariableSize (FProperty ** ExpressionField) inline
Reads a value from the bytestream which represents the number of bytes that should be zero'd out if a NULL context is encountered.
Parameters
ExpressionField receives a pointer to the field representing the expression; used by various execs to drive VM logic
Definition at line 440 of file Stack.h.
References CastField(), Property, and ReadPropertyUnchecked().
ReadWord()
int32 FFrame::ReadWord () inline
Definition at line 424 of file Stack.h.
References Read().
Serialize()
virtual void FFrame::Serialize (const TCHAR * V, ELogVerbosity::Type Verbosity, const class FName & Category) override virtual
References Category.
SkipCode()
void FFrame::SkipCode (const int32 NumOps) inline
Skips over the number of op codes specified by NumOps.
Definition at line 217 of file Stack.h.
References Code.
Step()
void FFrame::Step (UObject * Context, RESULT_DECL)
References FORCEINLINE_DEBUGGABLE, and RESULT_DECL.
Referenced by StepAndCheckMostRecentProperty(), StepCompiledIn(), and StepCompiledInRef().
StepAndCheckMostRecentProperty()
FORCEINLINE_DEBUGGABLE bool FFrame::StepAndCheckMostRecentProperty (UObject * Context, RESULT_DECL)
Convenience function that calls Step, but also returns true if both MostRecentProperty and MostRecentPropertyAddress are non-null.
Definition at line 468 of file Stack.h.
References FORCEINLINE_DEBUGGABLE, MostRecentProperty, MostRecentPropertyAddress, RESULT_DECL, RESULT_PARAM, and Step().
StepCompiledIn() [1/2]
template<class TProperty> FORCEINLINE_DEBUGGABLE void FFrame::StepCompiledIn (void * Result)
Replacement for Step that checks the for byte code, and if none exists, then PropertyChainForCompiledIn is used.
Also, makes an effort to verify that the params are in the correct order and the types are compatible.
Also makes an effort to verify that the params are in the correct order and the types are compatible.
Definition at line 480 of file Stack.h.
References FORCEINLINE_DEBUGGABLE, and StepCompiledIn().
Referenced by StepCompiledIn().
StepCompiledIn() [2/2]
FORCEINLINE_DEBUGGABLE void FFrame::StepCompiledIn (void * Result, const FFieldClass * ExpectedPropertyType)
Definition at line 485 of file Stack.h.
References checkSlow, Code, FORCEINLINE_DEBUGGABLE, FFieldClass::IsChildOf(), Object, Property, PropertyChainForCompiledIn, FField::StaticClass(), Step(), and StepExplicitProperty().
StepCompiledInRef()
template<class TProperty, typename TNativeType> FORCEINLINE_DEBUGGABLE TNativeType & FFrame::StepCompiledInRef (void *const TemporaryBuffer)
Replacement for Step that checks the for byte code, and if none exists, then PropertyChainForCompiledIn is used.
Also, makes an effort to verify that the params are in the correct order and the types are compatible.
Definition at line 502 of file Stack.h.
References CastField(), checkSlow, Code, FORCEINLINE_DEBUGGABLE, MostRecentPropertyAddress, MostRecentPropertyContainer, Object, Property, PropertyChainForCompiledIn, Step(), and StepExplicitProperty().
StepExplicitProperty()
void FFrame::StepExplicitProperty (void *const Result, FProperty * Property)
Replacement for Step that uses an explicitly specified property to unpack arguments.
References FORCEINLINE_DEBUGGABLE, and Property.
Referenced by StepCompiledIn(), and StepCompiledInRef().
UE_DEPRECATED()
FFrame::UE_DEPRECATED (5. 1, "Please use GetStackDescription(FStringBuilderBase&).") const
This will return a string of the form "ScopeName.FunctionName" associated with this stack frame:
References GetStackDescription().
Field Documentation
bAbortingExecution
bool FFrame::bAbortingExecution
If this flag gets set (usually from throwing a EBlueprintExceptionType::AbortExecution exception), execution shall immediately stop and return.
Definition at line 151 of file Stack.h.
Referenced by FFrame(), and ~FFrame().
bArrayContextFailed
bool FFrame::bArrayContextFailed
Definition at line 148 of file Stack.h.
Referenced by FFrame().
Code
uint8* FFrame::Code
Definition at line 119 of file Stack.h.
Referenced by FFrame(), PeekCode(), Read(), ReadCodeSkipCount(), ReadName(), ReadPointer(), SkipCode(), StepCompiledIn(), and StepCompiledInRef().
CurrentNativeFunction
UFunction* FFrame::CurrentNativeFunction
Currently executed native function.
Definition at line 139 of file Stack.h.
Referenced by FFrame().
FlowStack
FlowStackType FFrame::FlowStack
The execution flow stack for compiled Kismet code.
Definition at line 127 of file Stack.h.
Locals
uint8* FFrame::Locals
Definition at line 120 of file Stack.h.
Referenced by FFrame().
MostRecentProperty
FProperty* FFrame::MostRecentProperty
Definition at line 122 of file Stack.h.
Referenced by FFrame(), ReadPropertyUnchecked(), and StepAndCheckMostRecentProperty().
MostRecentPropertyAddress
uint8* FFrame::MostRecentPropertyAddress
Definition at line 123 of file Stack.h.
Referenced by FFrame(), StepAndCheckMostRecentProperty(), and StepCompiledInRef().
MostRecentPropertyContainer
uint8* FFrame::MostRecentPropertyContainer
Definition at line 124 of file Stack.h.
Referenced by FFrame(), and StepCompiledInRef().
Node
UFunction* FFrame::Node
Definition at line 117 of file Stack.h.
Referenced by FFrame().
Object
UObject* FFrame::Object
Definition at line 118 of file Stack.h.
Referenced by FFrame(), StepCompiledIn(), and StepCompiledInRef().
OutParms
FOutParmRec* FFrame::OutParms
contains information on any out parameters
Definition at line 133 of file Stack.h.
Referenced by FFrame().
PreviousFrame
FFrame* FFrame::PreviousFrame
Previous frame on the stack.
Definition at line 130 of file Stack.h.
Referenced by FFrame().
PreviousTrackingFrame
FFrame* FFrame::PreviousTrackingFrame
Previous tracking frame.
Definition at line 146 of file Stack.h.
Referenced by FFrame(), and ~FFrame().
PropertyChainForCompiledIn
FField* FFrame::PropertyChainForCompiledIn
If a class is compiled in then this is set to the property chain for compiled-in functions.
In that case, we follow the links to setup the args instead of executing by code.
Definition at line 136 of file Stack.h.
Referenced by FFrame(), StepCompiledIn(), and StepCompiledInRef().
The documentation for this struct was generated from the following file:
Runtime/CoreUObject/Public/UObject/Stack.h