Unreal Engine 5.6 C++ API: UE::Sequencer::FViewModelExtensionCollection Struct Reference
UE::Sequencer::FViewModelExtensionCollection Struct Reference
Utility class for maintaining a list of view-models that implement a given extension in a given hierarchy.
#include "ViewModelExtensionCollection.h"
Protected Member Functions
void Destroy ()
TSharedPtr< FViewModel > GetObservedModel () const
void Initialize ()
virtual void OnExtensionsDirtied ()
void Reinitialize (TWeakPtr< FViewModel > InWeakModel, int32 InDesiredRecursionDepth=-1)
Protected Member Functions inherited from FNoncopyable
FNoncopyable ()
~FNoncopyable ()
Private Member Functions
FViewModelExtensionCollection (FViewModelTypeID InExtensionType)
FViewModelExtensionCollection (FViewModelTypeID InExtensionType, TWeakPtr< FViewModel > InWeakModel, int32 InDesiredRecursionDepth=-1)
virtual ~FViewModelExtensionCollection ()
void ConditionalUpdate () const
void DestroyImpl ()
template<typename T>
TArrayView< T *const > GetExtensions () const
void OnHierarchyUpdated ()
void Update () const
Private Attributes
bool bNeedsUpdate
int32 DesiredRecursionDepth
TArray< void * > ExtensionContainer
FViewModelTypeID ExtensionType
FDelegateHandle OnHierarchyUpdatedHandle
TWeakPtr< FViewModel > WeakModel
Friends
template<typename T>
struct TViewModelExtensionCollection
Detailed Description
Utility class for maintaining a list of view-models that implement a given extension in a given hierarchy.
The list is kept up to date when the hierarchy changes.
Definition at line 28 of file ViewModelExtensionCollection.h.
Constructor & Destructor Documentation
FViewModelExtensionCollection() [1/2]
UE::Sequencer::FViewModelExtensionCollection::FViewModelExtensionCollection (FViewModelTypeID InExtensionType) private
Referenced by UE::Sequencer::TViewModelExtensionCollection< T >::TViewModelExtensionCollection(), UE::Sequencer::TViewModelExtensionCollection< T >::TViewModelExtensionCollection(), and UE::Sequencer::TViewModelExtensionCollection< T >::TViewModelExtensionCollection().
FViewModelExtensionCollection() [2/2]
UE::Sequencer::FViewModelExtensionCollection::FViewModelExtensionCollection (FViewModelTypeID InExtensionType, TWeakPtr< FViewModel > InWeakModel, int32 InDesiredRecursionDepth = -1) explicit private
~FViewModelExtensionCollection()
virtual UE::Sequencer::FViewModelExtensionCollection::~FViewModelExtensionCollection () private virtual
Member Function Documentation
ConditionalUpdate()
void UE::Sequencer::FViewModelExtensionCollection::ConditionalUpdate () const private
Referenced by GetExtensions().
Destroy()
void UE::Sequencer::FViewModelExtensionCollection::Destroy () protected
DestroyImpl()
void UE::Sequencer::FViewModelExtensionCollection::DestroyImpl () private
GetExtensions()
template<typename T> TArrayView< T *const > UE::Sequencer::FViewModelExtensionCollection::GetExtensions () const inline private
Definition at line 61 of file ViewModelExtensionCollection.h.
References ConditionalUpdate(), ExtensionContainer, and MakeArrayView().
Referenced by UE::Sequencer::TViewModelExtensionCollection< T >::GetExtensions().
GetObservedModel()
TSharedPtr< FViewModel > UE::Sequencer::FViewModelExtensionCollection::GetObservedModel () const inline protected
Definition at line 45 of file ViewModelExtensionCollection.h.
References WeakModel.
Initialize()
void UE::Sequencer::FViewModelExtensionCollection::Initialize () protected
OnExtensionsDirtied()
virtual void UE::Sequencer::FViewModelExtensionCollection::OnExtensionsDirtied () inline protected virtual
Reimplemented in UE::Sequencer::FLayerBarModel.
Definition at line 39 of file ViewModelExtensionCollection.h.
OnHierarchyUpdated()
void UE::Sequencer::FViewModelExtensionCollection::OnHierarchyUpdated () private
Reinitialize()
void UE::Sequencer::FViewModelExtensionCollection::Reinitialize (TWeakPtr< FViewModel > InWeakModel, int32 InDesiredRecursionDepth = -1) protected
Update()
void UE::Sequencer::FViewModelExtensionCollection::Update () const private
Friends And Related Symbol Documentation
TViewModelExtensionCollection
template<typename T> friend struct TViewModelExtensionCollection friend
Definition at line 73 of file ViewModelExtensionCollection.h.
References TViewModelExtensionCollection.
Referenced by TViewModelExtensionCollection.
Field Documentation
bNeedsUpdate
bool UE::Sequencer::FViewModelExtensionCollection::bNeedsUpdate mutable private
Definition at line 80 of file ViewModelExtensionCollection.h.
DesiredRecursionDepth
int32 UE::Sequencer::FViewModelExtensionCollection::DesiredRecursionDepth private
Definition at line 79 of file ViewModelExtensionCollection.h.
ExtensionContainer
TArray<void*> UE::Sequencer::FViewModelExtensionCollection::ExtensionContainer mutable private
Definition at line 75 of file ViewModelExtensionCollection.h.
Referenced by UE::Sequencer::TViewModelExtensionCollection< T >::FilterExtensions(), and GetExtensions().
ExtensionType
FViewModelTypeID UE::Sequencer::FViewModelExtensionCollection::ExtensionType private
Definition at line 78 of file ViewModelExtensionCollection.h.
OnHierarchyUpdatedHandle
FDelegateHandle UE::Sequencer::FViewModelExtensionCollection::OnHierarchyUpdatedHandle private
Definition at line 77 of file ViewModelExtensionCollection.h.
WeakModel
TWeakPtr<FViewModel> UE::Sequencer::FViewModelExtensionCollection::WeakModel private
Definition at line 76 of file ViewModelExtensionCollection.h.
Referenced by GetObservedModel().
The documentation for this struct was generated from the following file:
Editor/SequencerCore/Public/MVVM/Extensions/ViewModelExtensionCollection.h