Unreal Engine 5.6 C++ API: FDisplayMetrics Struct Reference
FDisplayMetrics Struct Reference
Contains metrics information for the desktop area.
#include "GenericApplication.h"
Public Member Functions
FDisplayMetrics ()
APPLICATIONCORE_API FPlatformRect GetMonitorWorkAreaFromPoint (const FVector2D &Point) const
Gets the monitor work area from a position in the global display rect.
APPLICATIONCORE_API void PrintToLog () const
Logs out display metrics.
UE_DEPRECATED (4.21, "Please use RebuildDisplayMetrics - it is functionally the same but is clearer about the function cost") static void GetDisplayMetrics(struct FDisplayMetrics &OutDisplayMetrics)
Static Public Member Functions
static APPLICATIONCORE_API float GetDebugTitleSafeZoneRatio ()
static APPLICATIONCORE_API void RebuildDisplayMetrics (struct FDisplayMetrics &OutDisplayMetrics)
Data Fields
FVector4 ActionSafePaddingSize
The safe area for less important spill over on TVs (see TitleSafePaddingSize)
TArray< FMonitorInfo > MonitorInfo
Info on connected physical monitors.
int32 PrimaryDisplayHeight
Height of the primary display in pixels.
int32 PrimaryDisplayWidth
Width of the primary display in pixels.
FPlatformRect PrimaryDisplayWorkAreaRect
Area of the primary display not covered by task bars or other docked widgets.
FVector4 TitleSafePaddingSize
The safe area for all content on TVs (see http://en.wikipedia.org/wiki/Safe_area_%28television%29) - content will be inset Left - X Top - Y Right - Z Bottom - W.
FPlatformRect VirtualDisplayRect
Virtual display coordinate range (includes all active displays)
Protected Member Functions
void ApplyDefaultSafeZones ()
bool TryGetTitleSafeZoneOverwrite (FVector4 &InOutTitleSafePaddingSize)
Static Protected Member Functions
static float GetDebugActionSafeZoneRatio ()
Detailed Description
Contains metrics information for the desktop area.
Definition at line 356 of file GenericApplication.h.
Constructor & Destructor Documentation
FDisplayMetrics()
FDisplayMetrics::FDisplayMetrics () inline
Definition at line 358 of file GenericApplication.h.
References ActionSafePaddingSize, and TitleSafePaddingSize.
Referenced by RebuildDisplayMetrics(), FNullPlatformDisplayMetrics::RebuildDisplayMetrics(), and UE_DEPRECATED().
Member Function Documentation
ApplyDefaultSafeZones()
void FDisplayMetrics::ApplyDefaultSafeZones () protected
GetDebugActionSafeZoneRatio()
float FDisplayMetrics::GetDebugActionSafeZoneRatio () static protected
GetDebugTitleSafeZoneRatio()
APPLICATIONCORE_API float FDisplayMetrics::GetDebugTitleSafeZoneRatio () static
GetMonitorWorkAreaFromPoint()
APPLICATIONCORE_API FPlatformRect FDisplayMetrics::GetMonitorWorkAreaFromPoint (const FVector2D & Point) const
Gets the monitor work area from a position in the global display rect.
References Point.
PrintToLog()
APPLICATIONCORE_API void FDisplayMetrics::PrintToLog () const
Logs out display metrics.
RebuildDisplayMetrics()
APPLICATIONCORE_API void FDisplayMetrics::RebuildDisplayMetrics (struct FDisplayMetrics & OutDisplayMetrics) static
References FDisplayMetrics().
Referenced by GenericApplication::GetInitialDisplayMetrics(), and UE_DEPRECATED().
TryGetTitleSafeZoneOverwrite()
bool FDisplayMetrics::TryGetTitleSafeZoneOverwrite (FVector4 & InOutTitleSafePaddingSize) protected
UE_DEPRECATED()
FDisplayMetrics::UE_DEPRECATED (4. 21, "Please use RebuildDisplayMetrics - it is functionally the same but is clearer about the function cost") & inline
Definition at line 391 of file GenericApplication.h.
References FDisplayMetrics(), and RebuildDisplayMetrics().
Field Documentation
ActionSafePaddingSize
FVector4 FDisplayMetrics::ActionSafePaddingSize
The safe area for less important spill over on TVs (see TitleSafePaddingSize)
Definition at line 389 of file GenericApplication.h.
Referenced by FDisplayMetrics().
MonitorInfo
TArray<FMonitorInfo> FDisplayMetrics::MonitorInfo
Info on connected physical monitors.
Only available on platforms where this information is accessible (PC currently)
Definition at line 371 of file GenericApplication.h.
PrimaryDisplayHeight
int32 FDisplayMetrics::PrimaryDisplayHeight
Height of the primary display in pixels.
Definition at line 368 of file GenericApplication.h.
PrimaryDisplayWidth
int32 FDisplayMetrics::PrimaryDisplayWidth
Width of the primary display in pixels.
Definition at line 365 of file GenericApplication.h.
PrimaryDisplayWorkAreaRect
FPlatformRect FDisplayMetrics::PrimaryDisplayWorkAreaRect
Area of the primary display not covered by task bars or other docked widgets.
Definition at line 374 of file GenericApplication.h.
TitleSafePaddingSize
FVector4 FDisplayMetrics::TitleSafePaddingSize
The safe area for all content on TVs (see http://en.wikipedia.org/wiki/Safe_area_%28television%29) - content will be inset Left - X Top - Y Right - Z Bottom - W.
Definition at line 386 of file GenericApplication.h.
Referenced by FDisplayMetrics().
VirtualDisplayRect
FPlatformRect FDisplayMetrics::VirtualDisplayRect
Virtual display coordinate range (includes all active displays)
Definition at line 377 of file GenericApplication.h.
The documentation for this struct was generated from the following file:
Runtime/ApplicationCore/Public/GenericPlatform/GenericApplication.h