Unreal Engine 5.6 C++ API: FShapedTextContext Struct Reference
FShapedTextContext Struct Reference
The basic data needed when shaping a run of text.
#include "IRun.h"
Public Member Functions
FShapedTextContext (const ETextShapingMethod InTextShapingMethod, const TextBiDi::ETextDirection InBaseDirection)
FORCEINLINE bool operator!= (const FShapedTextContext &Other) const
FORCEINLINE bool operator== (const FShapedTextContext &Other) const
Data Fields
TextBiDi::ETextDirection BaseDirection
The base direction of the current line of text.
ETextShapingMethod TextShapingMethod
The method used to shape the text within this layout.
Friends
uint32 GetTypeHash (const FShapedTextContext &Key)
Detailed Description
The basic data needed when shaping a run of text.
Definition at line 49 of file IRun.h.
Constructor & Destructor Documentation
FShapedTextContext()
FShapedTextContext::FShapedTextContext (const ETextShapingMethod InTextShapingMethod, const TextBiDi::ETextDirection InBaseDirection) inline
Definition at line 51 of file IRun.h.
References BaseDirection, and TextShapingMethod.
Referenced by FRunTextContext::FRunTextContext(), GetTypeHash, operator!=(), and operator==().
Member Function Documentation
operator!=()
FORCEINLINE bool FShapedTextContext::operator!= (const FShapedTextContext & Other) const inline
Definition at line 63 of file IRun.h.
References FShapedTextContext(), FORCEINLINE, and Other.
operator==()
FORCEINLINE bool FShapedTextContext::operator== (const FShapedTextContext & Other) const inline
Definition at line 57 of file IRun.h.
References FShapedTextContext(), BaseDirection, FORCEINLINE, Other, and TextShapingMethod.
Referenced by FLayoutBlockTextContext::operator==().
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FShapedTextContext & Key) friend
Definition at line 68 of file IRun.h.
References FShapedTextContext(), GetTypeHash, HashCombine(), and Key.
Referenced by GetTypeHash.
Field Documentation
BaseDirection
TextBiDi::ETextDirection FShapedTextContext::BaseDirection
The base direction of the current line of text.
Definition at line 80 of file IRun.h.
Referenced by FShapedTextContext(), and operator==().
TextShapingMethod
ETextShapingMethod FShapedTextContext::TextShapingMethod
The method used to shape the text within this layout.
Definition at line 77 of file IRun.h.
Referenced by FShapedTextContext(), and operator==().
The documentation for this struct was generated from the following file:
Runtime/Slate/Public/Framework/Text/IRun.h