Unreal Engine 5.6 C++ API: UE::StateTree::FActiveState Struct Reference
UE::StateTree::FActiveState Struct Reference
A state entry in the state path.
#include "StateTreeStatePath.h"
Public Member Functions
FActiveState ()=default
FActiveState (FActiveFrameID InFrameID, FActiveStateID InStateID, FStateTreeStateHandle InHandle)
FActiveFrameID GetFrameID () const
FStateTreeStateHandle GetStateHandle () const
FActiveStateID GetStateID () const
bool IsValid () const
bool operator!= (const FActiveState &) const =default
bool operator== (const FActiveState &) const =default
Private Attributes
FActiveFrameID FrameID
The unique ID of the state for this instance.
FStateTreeStateHandle StateHandle
The index of the state handle the state tree asset.
FActiveStateID StateID
The unique ID of the state for this instance.
Detailed Description
A state entry in the state path.
Definition at line 73 of file StateTreeStatePath.h.
Constructor & Destructor Documentation
FActiveState() [1/2]
UE::StateTree::FActiveState::FActiveState () default
Referenced by operator!=(), and operator==().
FActiveState() [2/2]
UE::StateTree::FActiveState::FActiveState (FActiveFrameID InFrameID, FActiveStateID InStateID, FStateTreeStateHandle InHandle) inline explicit
Definition at line 210 of file StateTreeStatePath.h.
References FrameID, StateHandle, and StateID.
Member Function Documentation
GetFrameID()
FActiveFrameID UE::StateTree::FActiveState::GetFrameID () const inline nodiscard
Definition at line 86 of file StateTreeStatePath.h.
References FrameID.
GetStateHandle()
FStateTreeStateHandle UE::StateTree::FActiveState::GetStateHandle () const inline nodiscard
Definition at line 96 of file StateTreeStatePath.h.
References StateHandle.
GetStateID()
FActiveStateID UE::StateTree::FActiveState::GetStateID () const inline nodiscard
Definition at line 91 of file StateTreeStatePath.h.
References StateID.
IsValid()
bool UE::StateTree::FActiveState::IsValid () const inline nodiscard
Definition at line 81 of file StateTreeStatePath.h.
References StateHandle.
operator!=()
bool UE::StateTree::FActiveState::operator!= (const FActiveState &) const nodiscard default
References FActiveState().
operator==()
bool UE::StateTree::FActiveState::operator== (const FActiveState &) const nodiscard default
References FActiveState().
Field Documentation
FrameID
FActiveFrameID UE::StateTree::FActiveState::FrameID private
The unique ID of the state for this instance.
Definition at line 103 of file StateTreeStatePath.h.
Referenced by FActiveState(), and GetFrameID().
StateHandle
FStateTreeStateHandle UE::StateTree::FActiveState::StateHandle private
The index of the state handle the state tree asset.
Definition at line 107 of file StateTreeStatePath.h.
Referenced by FActiveState(), GetStateHandle(), and IsValid().
StateID
FActiveStateID UE::StateTree::FActiveState::StateID private
The unique ID of the state for this instance.
Definition at line 105 of file StateTreeStatePath.h.
Referenced by FActiveState(), and GetStateID().
The documentation for this struct was generated from the following file:
S:/Development/U_E/UE_5.6/Engine/Plugins/Runtime/StateTree/Source/StateTreeModule/Public/StateTreeStatePath.h