Unreal Engine 5.6 C++ API: TStructTypeBitSet< TBaseStruct, TStructTrackerWrapper, TUStructType > Struct Template Reference
TStructTypeBitSet< TBaseStruct, TStructTrackerWrapper, TUStructType > Struct Template Reference
The TStructTypeBitSet holds information on "existence" of subtypes of a given UStruct.
#include "StructTypeBitSet.h"
Public Types
using FBaseStruct = TBaseStruct
using FStructTrackerWrapper = TStructTrackerWrapper
using FUStructType = TUStructType
using Super = TTypeBitSetBase<TStructTypeBitSet, TBaseStruct, TUStructType, FStructTypeBitSet::FBitSetContainer>
Public Types inherited from TTypeBitSetBase< TStructTypeBitSet< TBaseStruct, TStructTrackerWrapper, UScriptStruct >, TBaseStruct, UScriptStruct, FStructTypeBitSet::FBitSetContainer >
using FBaseStruct
using FContainer
using FUStructType
Public Member Functions
TStructTypeBitSet ()=default
TStructTypeBitSet (const FUStructType &StructType)
Constructor that initializes the bitset with a single struct type.
TStructTypeBitSet (std::initializer_list< const FUStructType * > InitList)
Constructor that initializes the bitset with an initializer list of struct types.
TStructTypeBitSet (TConstArrayView< const FUStructType * > InitList)
Constructor that initializes the bitset with an array view of struct types.
template<typename T = TBaseStruct, typename = typename TEnableIf<!TIsDerivedFrom<T, UObject>::IsDerived>::Type>
TStructTypeBitSet (TConstArrayView< FInstancedStruct > InitList)
This constructor is only available for UScriptStructs.
template<typename T>
FORCEINLINE void Add ()
Adds a struct type to the bitset.
void Add (const FUStructType &InStructType)
Adds a struct type to the bitset.
template<typename T>
FORCEINLINE bool Contains () const
Checks if the bitset contains a specific struct type.
bool Contains (const FUStructType &InStructType) const
Checks if the bitset contains a specific struct type.
FString DebugGetStringDesc () const
Provides a placeholder debug string when debug info is compiled out.
void ExportTypes (TArray< const TOutStructType *, Allocator > &OutTypes) const
Exports types stored in the bitset to an output array.
void ExportTypes (TFunctionRef< bool(const FUStructType *)> Callback) const
Lists all types used by this bitset, calling the provided callback for each one.
FStructTracker & GetStructTracker ()
Retrieves the FStructTracker associated with this bitset.
const FStructTracker & GetStructTracker () const
Retrieves the FStructTracker associated with this bitset (const version).
FORCEINLINE bool operator!= (const TStructTypeBitSet &Other) const
Inequality operator.
FORCEINLINE TStructTypeBitSet operator+ (const FUStructType &NewElement) const
Adds a struct type to the bitset, returning a new bitset.
FORCEINLINE TStructTypeBitSet operator+ (const TStructTypeBitSet &Other) const
Performs a union operation with another bitset.
FORCEINLINE void operator+= (const TStructTypeBitSet &Other)
Adds the bits from another bitset to this one (union).
FORCEINLINE TStructTypeBitSet operator- (const FUStructType &NewElement) const
Removes a struct type from the bitset, returning a new bitset.
FORCEINLINE TStructTypeBitSet operator- (const TStructTypeBitSet &Other) const
Performs a difference operation with another bitset.
FORCEINLINE void operator-= (const TStructTypeBitSet &Other)
Removes the bits from another bitset from this one (difference).
FORCEINLINE bool operator== (const TStructTypeBitSet &Other) const
Equality operator.
template<typename T>
FORCEINLINE void Remove ()
Removes a struct type from the bitset.
void Remove (const FUStructType &InStructType)
Removes a struct type from the bitset.
FORCEINLINE void Remove (const TStructTypeBitSet &Other)
Removes the bits from another bitset from this one (difference).
void Serialize (FArchive &Ar)
Serializes the bitset using the provided archive.
Public Member Functions inherited from TTypeBitSetBase< TStructTypeBitSet< TBaseStruct, TStructTrackerWrapper, UScriptStruct >, TBaseStruct, UScriptStruct, FStructTypeBitSet::FBitSetContainer >
void Add (const FUStructType &InStructType)
Adds a struct type to the bitset.
bool Contains (const FUStructType &InStructType) const
Checks if the bitset contains a specific struct type.
int32 CountStoredTypes () const
Counts the number of set bits in the bitset.
void ExportTypes (TArray< const TOutStructType *, Allocator > &OutTypes) const
Exports types stored in the bitset to an output array.
SIZE_T GetAllocatedSize () const
Gets the allocated size of the bitset.
TStructTypeBitSet< TBaseStruct, TStructTrackerWrapper, UScriptStruct > & GetImplementation ()
Retrieves the derived implementation of this base class.
FIndexIterator GetIndexIterator (const bool bValueToCheck=true) const
Creates an index iterator for bits with the specified value.
FORCEINLINE TStructTypeBitSet< TBaseStruct, TStructTrackerWrapper, UScriptStruct > GetOverlap (const TStructTypeBitSet< TBaseStruct, TStructTrackerWrapper, UScriptStruct > &Other) const
FORCEINLINE bool HasAll (const TStructTypeBitSet< TBaseStruct, TStructTrackerWrapper, UScriptStruct > &Other) const
FORCEINLINE bool HasAny (const TStructTypeBitSet< TBaseStruct, TStructTrackerWrapper, UScriptStruct > &Other) const
FORCEINLINE bool HasNone (const TStructTypeBitSet< TBaseStruct, TStructTrackerWrapper, UScriptStruct > &Other) const
FORCEINLINE bool IsBitSet (const int32 BitIndex) const
Checks if a specific bit is set in the bitset.
bool IsEmpty () const
Checks if the bitset is empty (no bits are set).
FORCEINLINE bool IsEquivalent (const TStructTypeBitSet< TBaseStruct, TStructTrackerWrapper, UScriptStruct > &Other) const
Checks if the current bitset is equivalent to another, i.e., whether both contain same "true" bits and ignoring the trailing "false" bits.
FORCEINLINE TStructTypeBitSet< TBaseStruct, TStructTrackerWrapper, UScriptStruct > operator& (const TStructTypeBitSet< TBaseStruct, TStructTrackerWrapper, UScriptStruct > &Other) const
Performs a bitwise AND operation with another bitset.
FORCEINLINE TStructTypeBitSet< TBaseStruct, TStructTrackerWrapper, UScriptStruct > operator+ (const FUStructType &NewElement) const
Adds a struct type to the bitset, returning a new bitset.
FORCEINLINE void operator+= (const TStructTypeBitSet< TBaseStruct, TStructTrackerWrapper, UScriptStruct > &Other)
Adds the bits from another bitset to this one (union).
FORCEINLINE TStructTypeBitSet< TBaseStruct, TStructTrackerWrapper, UScriptStruct > operator- (const FUStructType &NewElement) const
Removes a struct type from the bitset, returning a new bitset.
FORCEINLINE void operator-= (const TStructTypeBitSet< TBaseStruct, TStructTrackerWrapper, UScriptStruct > &Other)
Removes the bits from another bitset from this one (difference).
FORCEINLINE TStructTypeBitSet< TBaseStruct, TStructTrackerWrapper, UScriptStruct > operator| (const TStructTypeBitSet< TBaseStruct, TStructTrackerWrapper, UScriptStruct > &Other) const
Performs a bitwise OR operation with another bitset.
void Remove (const FUStructType &InStructType)
Removes a struct type from the bitset.
void Reset ()
Resets all bits in the bitset.
void SetAll (const bool bValue=true)
Sets all bits in the bitset to the specified value.
Static Public Member Functions
static FORCEINLINE_DEBUGGABLE const UStruct * GetBaseUStruct ()
Retrieves the base UStruct type used for validation.
static int32 GetMaxNum ()
Gets the maximum number of struct types registered in the tracker.
static const FUStructType * GetTypeAtIndex (const int32 Index)
Gets the struct type associated with a given index.
template<typename T>
static const TStructTypeBitSet & GetTypeBitSet ()
Gets a bitset representing a single struct type.
template<typename T>
static int32 GetTypeIndex ()
Gets the index of a struct type within the tracker, adding it if not already present.
static int32 GetTypeIndex (const FUStructType &InStructType)
Gets the index of a struct type within the tracker, adding it if not already present.
Static Public Member Functions inherited from TTypeBitSetBase< TStructTypeBitSet< TBaseStruct, TStructTrackerWrapper, UScriptStruct >, TBaseStruct, UScriptStruct, FStructTypeBitSet::FBitSetContainer >
static FORCEINLINE_DEBUGGABLE const UStruct * GetBaseUStruct ()
Retrieves the base UStruct type used for validation.
Data Fields
FContainer StructTypesBitArray
The bitset container storing the bits representing struct types.
friend Super
Private Member Functions
TStructTypeBitSet (const int32 BitToSet)
TStructTypeBitSet (const TBitArray<> &Source)
TStructTypeBitSet (TBitArray<> &&Source)
A private constructor for creating an instance straight from TBitArrays.
Friends
FORCEINLINE friend uint32 GetTypeHash (const TStructTypeBitSet &Instance)
Hash function for the bitset.
FORCEINLINE friend FArchive & operator<< (FArchive &Ar, TStructTypeBitSet &Instance)
Stream insertion operator for serialization.
Additional Inherited Members
Protected Member Functions inherited from TTypeBitSetBase< TStructTypeBitSet< TBaseStruct, TStructTrackerWrapper, UScriptStruct >, TBaseStruct, UScriptStruct, FStructTypeBitSet::FBitSetContainer >
TTypeBitSetBase ()=default
Default constructor.
Protected Attributes inherited from TTypeBitSetBase< TStructTypeBitSet< TBaseStruct, TStructTrackerWrapper, UScriptStruct >, TBaseStruct, UScriptStruct, FStructTypeBitSet::FBitSetContainer >
FContainer StructTypesBitArray
The bitset container storing the bits representing struct types.
Detailed Description
template<typename TBaseStruct, typename TStructTrackerWrapper, typename TUStructType = UScriptStruct>
struct TStructTypeBitSet< TBaseStruct, TStructTrackerWrapper, TUStructType >
The TStructTypeBitSet holds information on "existence" of subtypes of a given UStruct.
The information on available child-structs is gathered lazily - the internal FStructTracker assigns a given type a new index the very first time the type is encountered. To create a specific instantiation of the type, you also need to provide a type that will instantiate a static FStructTracker instance. The supplied macros hide this detail.
To declare a bitset type for an arbitrary struct type FFooBar, add the following in your header or cpp file:
DECLARE_STRUCTTYPEBITSET(FMyFooBarBitSet, FFooBar);
where FMyFooBarBitSet is the alias of the type you can use in your code. To have your type exposed to other modules use DECLARE_STRUCTTYPEBITSET_EXPORTED, like so:
DECLARE_STRUCTTYPEBITSET_EXPORTED(MYMODULE_API, FMyFooBarBitSet, FFooBar);
You also need to instantiate the static FStructTracker added by the DECLARE* macro. You can easily do it by placing the following in your cpp file (continuing the FFooBar example):
DEFINE_TYPEBITSET(FMyFooBarBitSet);
Parameters
TBaseStruct - The base struct type for type validation.
TStructTrackerWrapper - A wrapper providing a FStructTracker instance.
TUStructType - Unreal's struct type, typically UScriptStruct or UClass (defaults to UScriptStruct).
Definition at line 808 of file StructTypeBitSet.h.
Member Typedef Documentation
FBaseStruct
template<typename TBaseStruct, typename TStructTrackerWrapper, typename TUStructType = UScriptStruct> using TStructTypeBitSet< TBaseStruct, TStructTrackerWrapper, TUStructType >::FBaseStruct = TBaseStruct
Definition at line 813 of file StructTypeBitSet.h.
FStructTrackerWrapper
template<typename TBaseStruct, typename TStructTrackerWrapper, typename TUStructType = UScriptStruct> using TStructTypeBitSet< TBaseStruct, TStructTrackerWrapper, TUStructType >::FStructTrackerWrapper = TStructTrackerWrapper
Definition at line 811 of file StructTypeBitSet.h.
FUStructType
template<typename TBaseStruct, typename TStructTrackerWrapper, typename TUStructType = UScriptStruct> using TStructTypeBitSet< TBaseStruct, TStructTrackerWrapper, TUStructType >::FUStructType = TUStructType
Definition at line 812 of file StructTypeBitSet.h.
Super
template<typename TBaseStruct, typename TStructTrackerWrapper, typename TUStructType = UScriptStruct> using TStructTypeBitSet< TBaseStruct, TStructTrackerWrapper, TUStructType >::Super = TTypeBitSetBase<TStructTypeBitSet, TBaseStruct, TUStructType, FStructTypeBitSet::FBitSetContainer>
Definition at line 810 of file StructTypeBitSet.h.
Constructor & Destructor Documentation
TStructTypeBitSet() [1/8]
template<typename TBaseStruct, typename TStructTrackerWrapper, typename TUStructType = UScriptStruct> TStructTypeBitSet< TBaseStruct, TStructTrackerWrapper, TUStructType >::TStructTypeBitSet () default
Referenced by GetTypeBitSet(), GetTypeHash, operator!=(), operator+(), operator-(), operator<<, operator==(), and Remove().
TStructTypeBitSet() [2/8]
template<typename TBaseStruct, typename TStructTrackerWrapper, typename TUStructType = UScriptStruct> TStructTypeBitSet< TBaseStruct, TStructTrackerWrapper, TUStructType >::TStructTypeBitSet (const FUStructType & StructType) inline explicit
Constructor that initializes the bitset with a single struct type.
Parameters
StructType - The struct type to add.
Definition at line 833 of file StructTypeBitSet.h.
References Add().
TStructTypeBitSet() [3/8]
template<typename TBaseStruct, typename TStructTrackerWrapper, typename TUStructType = UScriptStruct> TStructTypeBitSet< TBaseStruct, TStructTrackerWrapper, TUStructType >::TStructTypeBitSet (std::initializer_list< const FUStructType * > InitList) inline explicit
Constructor that initializes the bitset with an initializer list of struct types.
Parameters
InitList - The initializer list of struct type pointers.
Definition at line 842 of file StructTypeBitSet.h.
References Add().
TStructTypeBitSet() [4/8]
template<typename TBaseStruct, typename TStructTrackerWrapper, typename TUStructType = UScriptStruct> TStructTypeBitSet< TBaseStruct, TStructTrackerWrapper, TUStructType >::TStructTypeBitSet (TConstArrayView< const FUStructType * > InitList) inline explicit
Constructor that initializes the bitset with an array view of struct types.
Parameters
InitList - The array view of struct type pointers.
Definition at line 857 of file StructTypeBitSet.h.
References Add().
TStructTypeBitSet() [5/8]
template<typename TBaseStruct, typename TStructTrackerWrapper, typename TUStructType = UScriptStruct> template<typename T = TBaseStruct, typename = typename TEnableIf<!TIsDerivedFrom<T, UObject>::IsDerived>::Type> TStructTypeBitSet< TBaseStruct, TStructTrackerWrapper, TUStructType >::TStructTypeBitSet (TConstArrayView< FInstancedStruct > InitList) inline explicit
This constructor is only available for UScriptStructs.
Initializes the bitset with an array view of FInstancedStruct.
Parameters
InitList - The array view of FInstancedStruct.
Definition at line 874 of file StructTypeBitSet.h.
References Add().
TStructTypeBitSet() [6/8]
template<typename TBaseStruct, typename TStructTrackerWrapper, typename TUStructType = UScriptStruct> TStructTypeBitSet< TBaseStruct, TStructTrackerWrapper, TUStructType >::TStructTypeBitSet (TBitArray<> && Source) inline private
A private constructor for creating an instance straight from TBitArrays.
Note that this constructor needs to remain private to ensure consistency of stored values with data tracked by the TStructTrackerWrapper::StructTracker.
Definition at line 891 of file StructTypeBitSet.h.
References Forward(), Source, and StructTypesBitArray.
TStructTypeBitSet() [7/8]
template<typename TBaseStruct, typename TStructTrackerWrapper, typename TUStructType = UScriptStruct> TStructTypeBitSet< TBaseStruct, TStructTrackerWrapper, TUStructType >::TStructTypeBitSet (const TBitArray<> & Source) inline private
Definition at line 896 of file StructTypeBitSet.h.
References Source, and StructTypesBitArray.
TStructTypeBitSet() [8/8]
template<typename TBaseStruct, typename TStructTrackerWrapper, typename TUStructType = UScriptStruct> TStructTypeBitSet< TBaseStruct, TStructTrackerWrapper, TUStructType >::TStructTypeBitSet (const int32 BitToSet) inline private
Definition at line 901 of file StructTypeBitSet.h.
References StructTypesBitArray.
Member Function Documentation
Add() [1/2]
template<typename TBaseStruct, typename TStructTrackerWrapper, typename TUStructType = UScriptStruct> template<typename T> FORCEINLINE void TStructTypeBitSet< TBaseStruct, TStructTrackerWrapper, TUStructType >::Add () inline
Adds a struct type to the bitset.
Parameters
T - The struct type to add.
Definition at line 983 of file StructTypeBitSet.h.
References FORCEINLINE, GetTypeIndex(), TIsDerivedFrom< DerivedType, BaseType >::IsDerived, and StructTypesBitArray.
Referenced by TStructTypeBitSet(), TStructTypeBitSet(), TStructTypeBitSet(), and TStructTypeBitSet().
Add() [2/2]
template<typename TBaseStruct, typename TStructTrackerWrapper, typename TUStructType = UScriptStruct> void TTypeBitSetBase< TStructTypeBitSet, TBaseStruct, TUStructType, FStructTypeBitSet::FBitSetContainer, WITH_STRUCTUTILS_DEBUG >::Add (const FUStructType & InStructType) inline
Adds a struct type to the bitset.
Parameters
InStructType - The struct type to add.
Definition at line 509 of file StructTypeBitSet.h.
Contains() [1/2]
template<typename TBaseStruct, typename TStructTrackerWrapper, typename TUStructType = UScriptStruct> template<typename T> FORCEINLINE bool TStructTypeBitSet< TBaseStruct, TStructTrackerWrapper, TUStructType >::Contains () const inline
Checks if the bitset contains a specific struct type.
Parameters
T - The struct type to check for.
Returns
True if the struct type is in the bitset; false otherwise.
Definition at line 1017 of file StructTypeBitSet.h.
References FORCEINLINE, GetTypeIndex(), TIsDerivedFrom< DerivedType, BaseType >::IsDerived, and StructTypesBitArray.
Contains() [2/2]
template<typename TBaseStruct, typename TStructTrackerWrapper, typename TUStructType = UScriptStruct> bool TTypeBitSetBase< TStructTypeBitSet, TBaseStruct, TUStructType, FStructTypeBitSet::FBitSetContainer, WITH_STRUCTUTILS_DEBUG >::Contains (const FUStructType & InStructType) const inline
Checks if the bitset contains a specific struct type.
Parameters
InStructType - The struct type to check for.
Returns
True if the struct type is in the bitset; false otherwise.
Definition at line 558 of file StructTypeBitSet.h.
DebugGetStringDesc()
template<typename TBaseStruct, typename TStructTrackerWrapper, typename TUStructType = UScriptStruct> FString TStructTypeBitSet< TBaseStruct, TStructTrackerWrapper, TUStructType >::DebugGetStringDesc () const inline
Provides a placeholder debug string when debug info is compiled out.
Returns
The placeholder string.
Definition at line 1116 of file StructTypeBitSet.h.
References TEXT.
ExportTypes() [1/2]
template<typename TBaseStruct, typename TStructTrackerWrapper, typename TUStructType = UScriptStruct> void TTypeBitSetBase< TStructTypeBitSet, TBaseStruct, TUStructType, FStructTypeBitSet::FBitSetContainer, WITH_STRUCTUTILS_DEBUG >::ExportTypes (TArray< const TOutStructType *, Allocator > & OutTypes) const inline
Exports types stored in the bitset to an output array.
Note: This method can be slow due to the use of weak pointers in the struct tracker.
Todo
To be improved.
Parameters
OutTypes - The array to populate with struct types.
Definition at line 702 of file StructTypeBitSet.h.
ExportTypes() [2/2]
template<typename TBaseStruct, typename TStructTrackerWrapper, typename TUStructType = UScriptStruct> void TStructTypeBitSet< TBaseStruct, TStructTrackerWrapper, TUStructType >::ExportTypes (TFunctionRef< bool(const FUStructType *)> Callback) const inline
Lists all types used by this bitset, calling the provided callback for each one.
Returning false from the callback will early-out of iterating over the types.
Note that this function is slow due to the FStructTracker utilizing WeakObjectPtrs to store types.
Todo
To be improved.
Parameters
Callback - The callback function to invoke for each type.
Definition at line 1085 of file StructTypeBitSet.h.
References TBitArray< Allocator >::FConstIterator::GetIndex(), GetTypeAtIndex(), TBitArray< Allocator >::FConstIterator::GetValue(), and TTypeBitSetBase< TStructTypeBitSet, TBaseStruct, TUStructType, FStructTypeBitSet::FBitSetContainer >::StructTypesBitArray.
GetBaseUStruct()
template<typename TBaseStruct, typename TStructTrackerWrapper, typename TUStructType = UScriptStruct> FORCEINLINE_DEBUGGABLE const UStruct * TTypeBitSetBase< TStructTypeBitSet, TBaseStruct, TUStructType, FStructTypeBitSet::FBitSetContainer, WITH_STRUCTUTILS_DEBUG >::GetBaseUStruct () inline static
Retrieves the base UStruct type used for validation.
Returns
Pointer to the base UStruct.
Definition at line 483 of file StructTypeBitSet.h.
Referenced by GetTypeHash, and GetTypeIndex().
GetMaxNum()
template<typename TBaseStruct, typename TStructTrackerWrapper, typename TUStructType = UScriptStruct> int32 TStructTypeBitSet< TBaseStruct, TStructTrackerWrapper, TUStructType >::GetMaxNum () inline static
Gets the maximum number of struct types registered in the tracker.
Returns
The number of struct types.
Definition at line 1040 of file StructTypeBitSet.h.
GetStructTracker() [1/2]
template<typename TBaseStruct, typename TStructTrackerWrapper, typename TUStructType = UScriptStruct> FStructTracker & TStructTypeBitSet< TBaseStruct, TStructTrackerWrapper, TUStructType >::GetStructTracker () inline
Retrieves the FStructTracker associated with this bitset.
Returns
Reference to the FStructTracker.
Definition at line 912 of file StructTypeBitSet.h.
GetStructTracker() [2/2]
template<typename TBaseStruct, typename TStructTrackerWrapper, typename TUStructType = UScriptStruct> const FStructTracker & TStructTypeBitSet< TBaseStruct, TStructTrackerWrapper, TUStructType >::GetStructTracker () const inline
Retrieves the FStructTracker associated with this bitset (const version).
Returns
Const reference to the FStructTracker.
Definition at line 921 of file StructTypeBitSet.h.
GetTypeAtIndex()
template<typename TBaseStruct, typename TStructTrackerWrapper, typename TUStructType = UScriptStruct> const FUStructType * TStructTypeBitSet< TBaseStruct, TStructTrackerWrapper, TUStructType >::GetTypeAtIndex (const int32 Index) inline static
Gets the struct type associated with a given index.
Parameters
Index - The index of the struct type.
Returns
Pointer to the struct type if found; nullptr otherwise.
Definition at line 973 of file StructTypeBitSet.h.
References Cast().
Referenced by ExportTypes().
GetTypeBitSet()
template<typename TBaseStruct, typename TStructTrackerWrapper, typename TUStructType = UScriptStruct> template<typename T> const TStructTypeBitSet & TStructTypeBitSet< TBaseStruct, TStructTrackerWrapper, TUStructType >::GetTypeBitSet () inline static
Gets a bitset representing a single struct type.
Parameters
T - The struct type to get the bitset for.
Returns
Reference to a static bitset representing the struct type.
Definition at line 961 of file StructTypeBitSet.h.
References TStructTypeBitSet(), GetTypeIndex(), and TIsDerivedFrom< DerivedType, BaseType >::IsDerived.
GetTypeIndex() [1/2]
template<typename TBaseStruct, typename TStructTrackerWrapper, typename TUStructType = UScriptStruct> template<typename T> int32 TStructTypeBitSet< TBaseStruct, TStructTrackerWrapper, TUStructType >::GetTypeIndex () inline static
Gets the index of a struct type within the tracker, adding it if not already present.
Parameters
T - The struct type to get the index for.
Returns
The index of the struct type.
Definition at line 948 of file StructTypeBitSet.h.
References UE::StructUtils::GetAsUStruct(), GetTypeIndex(), and TIsDerivedFrom< DerivedType, BaseType >::IsDerived.
Referenced by Add(), Contains(), GetTypeIndex(), and Remove().
GetTypeIndex() [2/2]
template<typename TBaseStruct, typename TStructTrackerWrapper, typename TUStructType = UScriptStruct> int32 TStructTypeBitSet< TBaseStruct, TStructTrackerWrapper, TUStructType >::GetTypeIndex (const FUStructType & InStructType) inline static
Gets the index of a struct type within the tracker, adding it if not already present.
Parameters
InStructType - The struct type to get the index for.
Returns
The index of the struct type.
Definition at line 931 of file StructTypeBitSet.h.
References ensureMsgf, GetBaseUStruct(), and TEXT.
Referenced by GetTypeBitSet().
operator!=()
template<typename TBaseStruct, typename TStructTrackerWrapper, typename TUStructType = UScriptStruct> FORCEINLINE bool TStructTypeBitSet< TBaseStruct, TStructTrackerWrapper, TUStructType >::operator!= (const TStructTypeBitSet< TBaseStruct, TStructTrackerWrapper, TUStructType > & Other) const inline
Inequality operator.
Parameters
Other - The other bitset to compare.
Returns
True if the bitsets are not equal; false otherwise.
Definition at line 1060 of file StructTypeBitSet.h.
References TStructTypeBitSet(), FORCEINLINE, and Other.
operator+() [1/2]
template<typename TBaseStruct, typename TStructTrackerWrapper, typename TUStructType = UScriptStruct> FORCEINLINE TStructTypeBitSet TTypeBitSetBase< TStructTypeBitSet, TBaseStruct, TUStructType, FStructTypeBitSet::FBitSetContainer, WITH_STRUCTUTILS_DEBUG >::operator+ (const FUStructType & NewElement) const inline
Adds a struct type to the bitset, returning a new bitset.
Parameters
NewElement - The struct type to add.
Returns
A new bitset with the added struct type.
Definition at line 667 of file StructTypeBitSet.h.
operator+() [2/2]
template<typename TBaseStruct, typename TStructTrackerWrapper, typename TUStructType = UScriptStruct> FORCEINLINE TStructTypeBitSet TStructTypeBitSet< TBaseStruct, TStructTrackerWrapper, TUStructType >::operator+ (const TStructTypeBitSet< TBaseStruct, TStructTrackerWrapper, TUStructType > & Other) const inline
Performs a union operation with another bitset.
Parameters
Other - The other bitset to combine with.
Returns
A new bitset representing the union.
Definition at line 1029 of file StructTypeBitSet.h.
References TStructTypeBitSet(), TBitArray< Allocator >::BitwiseOR(), FORCEINLINE, MaxSize, MoveTemp(), Other, and StructTypesBitArray.
operator+=()
template<typename TBaseStruct, typename TStructTrackerWrapper, typename TUStructType = UScriptStruct> FORCEINLINE void TTypeBitSetBase< TStructTypeBitSet, TBaseStruct, TUStructType, FStructTypeBitSet::FBitSetContainer, WITH_STRUCTUTILS_DEBUG >::operator+= (const TStructTypeBitSet< TBaseStruct, TStructTrackerWrapper, TUStructType > & Other) inline
Adds the bits from another bitset to this one (union).
Parameters
Other - The other bitset to add.
Definition at line 648 of file StructTypeBitSet.h.
operator-() [1/2]
template<typename TBaseStruct, typename TStructTrackerWrapper, typename TUStructType = UScriptStruct> FORCEINLINE TStructTypeBitSet TTypeBitSetBase< TStructTypeBitSet, TBaseStruct, TUStructType, FStructTypeBitSet::FBitSetContainer, WITH_STRUCTUTILS_DEBUG >::operator- (const FUStructType & NewElement) const inline
Removes a struct type from the bitset, returning a new bitset.
Parameters
NewElement - The struct type to remove.
Returns
A new bitset with the struct type removed.
Definition at line 679 of file StructTypeBitSet.h.
operator-() [2/2]
template<typename TBaseStruct, typename TStructTrackerWrapper, typename TUStructType = UScriptStruct> FORCEINLINE TStructTypeBitSet TStructTypeBitSet< TBaseStruct, TStructTrackerWrapper, TUStructType >::operator- (const TStructTypeBitSet< TBaseStruct, TStructTrackerWrapper, TUStructType > & Other) const inline
Performs a difference operation with another bitset.
Parameters
Other - The other bitset to subtract.
Returns
A new bitset representing the difference.
Definition at line 1070 of file StructTypeBitSet.h.
References TStructTypeBitSet(), FORCEINLINE, MoveTemp(), and Other.
operator-=()
template<typename TBaseStruct, typename TStructTrackerWrapper, typename TUStructType = UScriptStruct> FORCEINLINE void TTypeBitSetBase< TStructTypeBitSet, TBaseStruct, TUStructType, FStructTypeBitSet::FBitSetContainer, WITH_STRUCTUTILS_DEBUG >::operator-= (const TStructTypeBitSet< TBaseStruct, TStructTrackerWrapper, TUStructType > & Other) inline
Removes the bits from another bitset from this one (difference).
Parameters
Other - The other bitset to subtract.
Definition at line 657 of file StructTypeBitSet.h.
operator==()
template<typename TBaseStruct, typename TStructTrackerWrapper, typename TUStructType = UScriptStruct> FORCEINLINE bool TStructTypeBitSet< TBaseStruct, TStructTrackerWrapper, TUStructType >::operator== (const TStructTypeBitSet< TBaseStruct, TStructTrackerWrapper, TUStructType > & Other) const inline
Equality operator.
Parameters
Other - The other bitset to compare
Returns
True if the bitsets are equal; false otherwise.
Definition at line 1050 of file StructTypeBitSet.h.
References TStructTypeBitSet(), FORCEINLINE, Other, and TTypeBitSetBase< TStructTypeBitSet, TBaseStruct, TUStructType, FStructTypeBitSet::FBitSetContainer >::StructTypesBitArray.
Remove() [1/3]
template<typename TBaseStruct, typename TStructTrackerWrapper, typename TUStructType = UScriptStruct> template<typename T> FORCEINLINE void TStructTypeBitSet< TBaseStruct, TStructTrackerWrapper, TUStructType >::Remove () inline
Removes a struct type from the bitset.
Parameters
T - The struct type to remove.
Definition at line 995 of file StructTypeBitSet.h.
References FORCEINLINE, GetTypeIndex(), TIsDerivedFrom< DerivedType, BaseType >::IsDerived, and StructTypesBitArray.
Remove() [2/3]
template<typename TBaseStruct, typename TStructTrackerWrapper, typename TUStructType = UScriptStruct> void TTypeBitSetBase< TStructTypeBitSet, TBaseStruct, TUStructType, FStructTypeBitSet::FBitSetContainer, WITH_STRUCTUTILS_DEBUG >::Remove (const FUStructType & InStructType) inline
Removes a struct type from the bitset.
Parameters
InStructType - The struct type to remove.
Definition at line 529 of file StructTypeBitSet.h.
Remove() [3/3]
template<typename TBaseStruct, typename TStructTrackerWrapper, typename TUStructType = UScriptStruct> FORCEINLINE void TStructTypeBitSet< TBaseStruct, TStructTrackerWrapper, TUStructType >::Remove (const TStructTypeBitSet< TBaseStruct, TStructTrackerWrapper, TUStructType > & Other) inline
Removes the bits from another bitset from this one (difference).
Parameters
Other - The other bitset to subtract.
Definition at line 1006 of file StructTypeBitSet.h.
References TStructTypeBitSet(), FORCEINLINE, Other, and StructTypesBitArray.
Serialize()
template<typename TBaseStruct, typename TStructTrackerWrapper, typename TUStructType = UScriptStruct> void TStructTypeBitSet< TBaseStruct, TStructTrackerWrapper, TUStructType >::Serialize (FArchive & Ar) inline
Serializes the bitset using the provided archive.
Parameters
Ar - The archive to serialize with.
Definition at line 1175 of file StructTypeBitSet.h.
References Ar, and TTypeBitSetBase< TStructTypeBitSet, TBaseStruct, TUStructType, FStructTypeBitSet::FBitSetContainer >::StructTypesBitArray.
Friends And Related Symbol Documentation
GetTypeHash
template<typename TBaseStruct, typename TStructTrackerWrapper, typename TUStructType = UScriptStruct> FORCEINLINE friend uint32 GetTypeHash (const TStructTypeBitSet< TBaseStruct, TStructTrackerWrapper, TUStructType > & Instance) friend
Hash function for the bitset.
Parameters
Instance - The bitset instance to hash.
Returns
The hash value.
Definition at line 1164 of file StructTypeBitSet.h.
References TStructTypeBitSet(), FORCEINLINE, GetBaseUStruct(), GetTypeHash, HashCombine(), Instance, and PointerHash().
Referenced by GetTypeHash.
operator<<
template<typename TBaseStruct, typename TStructTrackerWrapper, typename TUStructType = UScriptStruct> FORCEINLINE friend FArchive & operator<< (FArchive & Ar, TStructTypeBitSet< TBaseStruct, TStructTrackerWrapper, TUStructType > & Instance) friend
Stream insertion operator for serialization.
Parameters
Ar - The archive to serialize with.
Instance - The bitset instance to serialize.
Returns
The archive after serialization.
Definition at line 1186 of file StructTypeBitSet.h.
References TStructTypeBitSet(), Ar, FORCEINLINE, and Instance.
Field Documentation
StructTypesBitArray
template<typename TBaseStruct, typename TStructTrackerWrapper, typename TUStructType = UScriptStruct> FContainer TTypeBitSetBase< TStructTypeBitSet, TBaseStruct, TUStructType, FStructTypeBitSet::FBitSetContainer, WITH_STRUCTUTILS_DEBUG >::StructTypesBitArray
The bitset container storing the bits representing struct types.
Definition at line 777 of file StructTypeBitSet.h.
Referenced by TStructTypeBitSet(), TStructTypeBitSet(), TStructTypeBitSet(), Add(), Contains(), operator+(), Remove(), and Remove().
Super
template<typename TBaseStruct, typename TStructTrackerWrapper, typename TUStructType = UScriptStruct> friend TStructTypeBitSet< TBaseStruct, TStructTrackerWrapper, TUStructType >::Super
Definition at line 815 of file StructTypeBitSet.h.
The documentation for this struct was generated from the following file:
Runtime/CoreUObject/Public/StructUtils/StructTypeBitSet.h