Unreal Engine 5.6 C++ API: FAndroidMisc Struct Reference
FAndroidMisc Struct Reference
Android implementation of the misc OS functions.
#include "AndroidPlatformMisc.h"
Data Structures
struct FBatteryState
struct FCPUState
struct FCPUStatTime
Public Types
enum EBatteryState {
BATTERY_STATE_UNKNOWN = 1 , BATTERY_STATE_CHARGING , BATTERY_STATE_DISCHARGING , BATTERY_STATE_NOT_CHARGING ,
BATTERY_STATE_FULL
}
enum class ECoreFrequencyProperty { CurrentFrequency , MaxFrequency , MinFrequency }
typedef TFunction< void()> OnPauseCallBackType
typedef TFunction< void(void *NewNativeHandle)> ReInitWindowCallbackType
typedef TFunction< void()> ReleaseWindowCallbackType
Public Member Functions
UE_DEPRECATED (4.21, "void FPlatformMisc::GetEnvironmentVariable(Name, Result, Length) is deprecated. Use FString FPlatformMisc::GetEnvironmentVariable(Name) instead.") static 1 void GetEnvironmentVariable(const TCHAR *VariableName
UE_DEPRECATED (5.1, "SetDeviceOrientation is deprecated. Use SetAllowedDeviceOrientation instead.") static 1 void SetDeviceOrientation(EDeviceScreenOrientation NewDeviceOrentation)
Public Member Functions inherited from FGenericPlatformMisc
UE_DEPRECATED (4.14, "GetHasedMacAddressString is deprecated. It is not reliable on all platforms") static 1 FString GetHashedMacAddressString()
Retrieve the Mac address of the current adapter as a hashed string (privacy).
UE_DEPRECATED (4.14, "GetMacAddress is deprecated. It is not reliable on all platforms") static 1 TArray< uint8 > GetMacAddress()
Retrieve the Mac address of the current adapter.
UE_DEPRECATED (4.14, "GetMacAddressString is deprecated. It is not reliable on all platforms") static 1 FString GetMacAddressString()
Retrieve the Mac address of the current adapter as a string.
UE_DEPRECATED (4.14, "GetMachineId is deprecated. Use GetLoginId instead.") static 1 FGuid GetMachineId()
Get (or create) the unique ID used to identify this computer.
UE_DEPRECATED (4.18, "FPaths::SetOverrideGameDir() has been superseded by FPaths::SetOverrideProjectDir().") static FORCEINLINE void SetOverrideGameDir(const FString &InOverrideDir)
UE_DEPRECATED (4.19, "FPlatformMisc::DebugBreak is deprecated. Use the UE_DEBUG_BREAK() macro instead.") FORCEINLINE static void DebugBreak()
Break into the debugger, if IsDebuggerPresent returns true, otherwise do nothing.
UE_DEPRECATED (5.1, "SetDeviceOrientation is deprecated. Use SetAllowedDeviceOrientation instead.") static 1 void SetDeviceOrientation(EDeviceScreenOrientation NewDeviceOrientation)
Change the orientation of the device.
UE_DEPRECATED (5.2, "Must supply size when prefetching a block of data") FORCEINLINE static void PrefetchBlock(const void *Ptr)
Static Public Member Functions
static FDelegateHandle AddNetworkListener (FOnNetworkConnectionChangedDelegate &&InNewDelegate)
static bool AllowThreadHeartBeat ()
static bool AreHeadPhonesPluggedIn ()
static void CreateGuid (struct FGuid &Result)
static bool DeleteStoredSection (const FString &InStoreId, const FString &InSectionName)
static bool DeleteStoredValue (const FString &InStoreId, const FString &InSectionName, const FString &InKeyName)
static bool Expand16BitIndicesTo32BitOnLoad ()
Returns whether or not a 16 bit index buffer should be promoted to 32 bit on load, needed for some Android devices.
static bool FileExistsInPlatformPackage (const FString &RelativePath)
static int32 GetAndroidMajorVersion ()
static const FString GetAndroidVersion ()
static int GetBatteryLevel ()
static FBatteryState GetBatteryState ()
static int32 GetCellularPreference ()
static const TMap< FString, FString > & GetConfigRuleVars ()
static uint32 GetCoreFrequency (int32 CoreIndex, ECoreFrequencyProperty CoreFrequencyProperty)
static FString GetCPUBrand ()
static FString GetCPUChipset ()
static FCPUState & GetCPUState ()
static float GetCPUTemperature ()
static FString GetCPUVendor ()
static const TCHAR * GetDefaultDeviceProfileName ()
static FString GetDefaultLocale ()
static const FString GetDeviceBuildNumber ()
static const FString GetDeviceMake ()
static const FString GetDeviceModel ()
static EDeviceScreenOrientation GetDeviceOrientation ()
static float GetDeviceTemperatureLevel ()
static int32 GetDeviceVolume ()
static bool GetDiskTotalAndFreeSpace (const FString &InPath, uint64 &TotalNumberOfBytes, uint64 &NumberOfFreeBytes)
static FString GetEnvironmentVariable (const TCHAR *VariableName)
static FString GetFatalSignalMessage (int Signal, siginfo *Info)
static FString GetGLVersion ()
static FString GetGPUFamily ()
static FORCEINLINE int32 GetMaxPathLength ()
static int GetMobilePropagateAlphaSetting ()
Will return true if we wish to propagate the alpha to the backbuffer.
static int32 GetNativeDisplayRefreshRate ()
static ENetworkConnectionType GetNetworkConnectionType ()
static OnPauseCallBackType GetOnPauseCallback ()
static ReInitWindowCallbackType GetOnReInitWindowCallback ()
static ReleaseWindowCallbackType GetOnReleaseWindowCallback ()
static const FString GetOSLanguage ()
static FString GetOSVersion ()
static void GetOSVersions (FString &out_OSVersionLabel, FString &out_OSSubVersionLabel)
static bool GetOverrideResolution (int32 &ResX, int32 &ResY)
static FString GetPendingActivationProtocol ()
static IPlatformChunkInstall * GetPlatformChunkInstall ()
static FString GetPrimaryGPUBrand ()
static const FString GetProductName ()
static const FString GetProjectVersion ()
static bool GetStoredValue (const FString &InStoreId, const FString &InSectionName, const FString &InKeyName, FString &OutValue)
static TArray< int32 > GetSupportedNativeDisplayRefreshRates ()
static const TCHAR * GetSystemErrorMessage (TCHAR *OutBuffer, int32 BufferCount, int32 Error)
static TArray< uint8 > GetSystemFontBytes ()
static int32 GetTargetSDKVersion ()
static const char * GetThreadName (uint32 ThreadId)
static bool GetUseVirtualJoysticks ()
static void GetValidTargetPlatforms (class TArray< class FString > &TargetPlatformNames)
static float GetVirtualKeyboardInputHeight ()
static bool GetVolumeButtonsHandledBySystem ()
static int GetVolumeState (double *OutTimeOfChangeInSec=nullptr)
static FString GetVulkanVersion ()
static void HandleNewIntentUri (const FString &IntentUri)
static bool HasMemoryWarningHandler ()
static bool HasPlatformFeature (const TCHAR *FeatureName)
static bool HasVulkanDriverSupport ()
static bool IsAllowedRemoteNotifications ()
static bool IsDebuggerPresent ()
static bool IsDesktopVulkanAvailable ()
static bool IsExternalMemoryAndroidHardwareBufferExtensionLoaded ()
static bool IsInLowPowerMode ()
static bool IsInSignalHandler ()
static bool IsLocalPrintThreadSafe ()
static bool IsRunningOnBattery ()
static bool IsSupportedAndroidDevice ()
static bool IsVulkanAvailable ()
static FString LoadTextFileFromPlatformPackage (const FString &RelativePath)
static void LocalPrint (const TCHAR *Message)
static FORCEINLINE void MemoryBarrier ()
static EAppReturnType::Type MessageBoxExt (EAppMsgType::Type MsgType, const TCHAR *Text, const TCHAR *Caption)
static void NonReentrantRequestExit ()
static int32 NumberOfCores ()
static int32 NumberOfCoresIncludingHyperthreads ()
static void OverrideFatalSignalHandler (void(*FatalSignalHandlerOverrideFunc)(int Signal, struct siginfo *Info, void *Context, uint32 CrashingThreadId))
static void PlatformHandleSplashScreen (bool ShowSplashScreen)
static void PlatformInit ()
static void PlatformPreInit ()
static void PlatformTearDown ()
static void PrepareMobileHaptics (EMobileHapticsType Type)
static void RegisterForRemoteNotifications ()
static void RegisterThreadName (const char *Name, uint32 ThreadId)
static void ReleaseMobileHaptics ()
static bool RemoveNetworkListener (FDelegateHandle Handle)
static void RequestExit (bool Force, const TCHAR *CallSite=nullptr)
static bool RestartApplication ()
static void SaveDeviceOrientation (EDeviceScreenOrientation NewDeviceOrentation)
static void SetAllowedDeviceOrientation (EDeviceScreenOrientation NewAllowedDeviceOrientation)
static void SetCellularPreference (int32 Value)
static void SetCrashHandler (void(*CrashHandler)(const FGenericCrashContext &Context))
static void SetForceUnsupported (bool bInOverride)
static void SetMemoryWarningHandler (void(*Handler)(const FGenericMemoryWarningContext &Context))
static bool SetNativeDisplayRefreshRate (int32 RefreshRate)
static void SetOnPauseCallback (OnPauseCallBackType InOnPauseCallback)
static void SetOnReInitWindowCallback (ReInitWindowCallbackType InOnReInitWindowCallback)
static void SetOnReleaseWindowCallback (ReleaseWindowCallbackType InOnReleaseWindowCallback)
static bool SetStoredValue (const FString &InStoreId, const FString &InSectionName, const FString &InKeyName, const FString &InValue)
static void SetVersionInfo (FString AndroidVersion, int32 InTargetSDKVersion, FString DeviceMake, FString DeviceModel, FString DeviceBuildNumber, FString OSLanguage, FString ProductName)
static void SetVolumeButtonsHandledBySystem (bool enabled)
static void ShareURL (const FString &URL, const FText &Description, int32 LocationHintX, int32 LocationHintY)
static bool ShouldUseDesktopVulkan ()
static bool ShouldUseVulkan ()
static void ShowConsoleWindow ()
static bool SupportsBackbufferSampling ()
static bool SupportsES30 ()
static bool SupportsFloatingPointRenderTargets ()
static bool SupportsLocalCaching ()
static bool SupportsShaderFramebufferFetch ()
static bool SupportsShaderIOBlocks ()
static bool SupportsTouchInput ()
static void TriggerCrashHandler (ECrashContextType InType, const TCHAR *InErrorMessage, const TCHAR *OverrideCallstack=nullptr)
static void TriggerMobileHaptics ()
static void UnlockAndroidWindow ()
static void UnregisterForRemoteNotifications ()
static void UpdateDeviceOrientation ()
static bool UseNewWindowBehavior ()
static bool UseRenderThread ()
Static Public Member Functions inherited from FGenericPlatformMisc
static void AddAdditionalRootDirectory (const FString &RootDir)
add an additional root directory
static FDelegateHandle AddNetworkListener (FOnNetworkConnectionChangedDelegate &&InNewDelegate)
static bool AllowAudioThread ()
Checks if platform wants to allow an audio thread on current device (note: does not imply it will, only if okay given other criteria met)
static bool AllowLocalCaching ()
static bool AllowThreadHeartBeat ()
Checks if platform wants to allow the thread heartbeat hang detection.
static void BeginEnterBackgroundEvent (const TCHAR *Text)
Profiler enter background events.
static FORCEINLINE void BeginNamedEvent (const struct FColor &Color, const ANSICHAR *Text)
static FORCEINLINE void BeginNamedEvent (const struct FColor &Color, const TCHAR *Text)
static FORCEINLINE void BeginNamedEventFrame ()
static void CacheLaunchDir ()
Function to store the current working directory for use with LaunchDir()
static bool CheckPersistentDownloadStorageSpaceAvailable (uint64 BytesRequired, bool bAttemptToUseUI)
Ensure that there enough space in the persistent download dir.
static FORCEINLINE void ChooseHDRDeviceAndColorGamut (uint32 DeviceId, uint32 DisplayNitLevel, EDisplayOutputFormat &OutputDevice, EDisplayColorGamut &ColorGamut)
static FString CloudDir ()
Return the CloudDir.
static bool CommandLineCommands ()
Handles Game Explorer, Firewall and FirstInstall commands, typically from the installer.
static void CreateGuid (struct FGuid &Result)
Create a new globally unique identifier.
static FORCEINLINE void CustomNamedStat (const ANSICHAR *Text, float Value, const ANSICHAR *Graph, const ANSICHAR *Unit)
static FORCEINLINE void CustomNamedStat (const TCHAR *Text, float Value, const TCHAR *Graph, const TCHAR *Unit)
static bool DeleteStoredSection (const FString &InStoreId, const FString &InSectionName)
Deletes the given section and its contained values in the platform specific key->value store Note: The key->value store is user-specific, but may be used to share data between different applications for the same user.
static bool DeleteStoredValue (const FString &InStoreId, const FString &InSectionName, const FString &InKeyName)
Deletes value for the given section and key in the platform specific key->value store Note: The key->value store is user-specific, but may be used to share data between different applications for the same user.
static bool DesktopTouchScreen ()
static void DisableScreenTimeout ()
static void EnableScreenTimeout ()
static void EndEnterBackgroundEvent ()
static FORCEINLINE void EndNamedEvent ()
static const TCHAR * EngineDir ()
Get the engine directory.
static void EnsureNetworkIfNecessary ()
static bool Exec (class UWorld *InWorld, const TCHAR *Cmd, FOutputDevice &Out)
Platform-specific Exec function.
static FORCEINLINE bool Expand16BitIndicesTo32BitOnLoad ()
static bool FileExistsInPlatformPackage (const FString &RelativePath)
static bool FullscreenSameAsWindowedFullscreen ()
static const TCHAR * GamePersistentDownloadDir ()
Return the GamePersistentDownloadDir.
static const TCHAR * GameTemporaryDownloadDir ()
Return the temporary directory.
static const TCHAR * GeneratedConfigDir ()
static TArray< FString > GetAdditionalRootDirectories ()
get additional directories which can be considered as root directories
static EDeviceScreenOrientation GetAllowedDeviceOrientation ()
Returns the allowed orientation of the device.
static FORCEINLINE int GetBatteryLevel ()
Gets the current battery level.
static bool GetBlockingIOStats (FProcessIOStats &OutStats, EInputOutputFlags Flags=EInputOutputFlags::All)
Gets Blocking Input/Output stats covering the lifetime of the process.
static FORCEINLINE float GetBrightness ()
static FORCEINLINE int32 GetChunkIDFromPakchunkIndex (int32 PakchunkIndex)
static const FString * GetConfigRulesVariable (const FString &Key)
static const class TMap< FString, FString > & GetConfigRuleVars ()
static bool GetContextSwitchStats (FContextSwitchStats &OutStats, EContextSwitchFlags Flags=EContextSwitchFlags::All)
Gets Context Switch stats covering the lifetime of the process.
static EConvertibleLaptopMode GetConvertibleLaptopMode ()
Gets the current mode of convertible laptops, i.e.
static FString GetCPUBrand ()
Uses cpuid instruction to get the CPU brand string.
static FString GetCPUChipset ()
Returns the CPU chipset if known.
static uint32 GetCPUInfo ()
On x86(-64) platforms, uses cpuid instruction to get the CPU signature.
static FString GetCPUVendor ()
Uses cpuid instruction to get the vendor string.
static ECrashHandlingType GetCrashHandlingType ()
Gets the current crash handling type.
static const TCHAR * GetDefaultDeviceProfileName ()
Gets the default profile name.
static FString GetDefaultLanguage ()
Get the default language (for localization) used by this platform.
static FString GetDefaultLocale ()
Get the default locale (for internationalization) used by this platform.
static const TCHAR * GetDefaultPathSeparator ()
static FString GetDeviceId ()
Returns a unique string for device identification.
static FString GetDeviceMakeAndModel ()
static EDeviceScreenOrientation GetDeviceOrientation ()
Returns the current orientation of the device: will be either Portrait, LandscapeLeft, PortraitUpsideDown or LandscapeRight.
static FString GetDeviceTag ()
Get Device Tag of the device running the session.
static float GetDeviceTemperatureLevel ()
Returns the current device temperature level.
static int32 GetDeviceVolume ()
Returns the device volume if the device is capable of returning that information.
static bool GetDiskTotalAndFreeSpace (const FString &InPath, uint64 &TotalNumberOfBytes, uint64 &NumberOfFreeBytes)
Retrieves information about the total number of bytes and number of free bytes for the specified disk path.
static bool GetEngineAndProjectAbsoluteDirsFromExecutable (FString &OutProjectDir, FString &OutEngineDir)
Return the engine and project directory based from the executable.
static const TCHAR * GetEngineMode ()
Get a string description of the mode the engine was running in.
static FString GetEnvironmentVariable (const TCHAR *VariableName)
Retrieve a environment variable from the system.
static FString GetEpicAccountId ()
Get the Epic account ID for the user who last used the Launcher.
static FText GetFileManagerName ()
static struct FGPUDriverInfo GetGPUDriverInfo (const FString &DeviceDescription)
static FString GetHostArchitecture ()
static FORCEINLINE uint32 GetLastError ()
static FString GetLocalCurrencyCode ()
Returns the currency code associated with the device's locale.
static FString GetLocalCurrencySymbol ()
Returns the currency symbol associated with the device's locale.
static FString GetLoginId ()
Returns a unique string associated with the login account of the current machine.
static FORCEINLINE int32 GetMaxPathLength ()
Returns the maximum length of a path.
static int32 GetMaxRefreshRate ()
retrieves the current maximum refresh rate supported by the platform
static int32 GetMaxSupportedRefreshRate ()
retrieves the maximum refresh rate supported by the platform
static int32 GetMaxSyncInterval ()
Returns the platform's maximum allowed value for rhi.SyncInterval.
static int GetMobilePropagateAlphaSetting ()
static ENetworkConnectionStatus GetNetworkConnectionStatus ()
Returns the current status for the network connection.
static ENetworkConnectionType GetNetworkConnectionType ()
Returns whether WiFi connection is currently active.
static FORCEINLINE void GetNetworkFileCustomData (TMap< FString, FString > &OutCustomPlatformData)
Returns any platform-specific key-value data that needs to be sent to the network file server.
static const TCHAR * GetNullRHIShaderFormat ()
Determines the shader format for the platform.
static FString GetOperatingSystemId ()
Gets a globally unique ID the represents a particular operating system install.
static FString GetOSVersion ()
Gets a string representing the numeric OS version (as opposed to a translated OS version that GetOSVersions returns).
static void GetOSVersions (FString &out_OSVersionLabel, FString &out_OSSubVersionLabel)
Gets the OS Version and OS Subversion.
static bool GetPageFaultStats (FPageFaultStats &OutStats, EPageFaultFlags Flags=EPageFaultFlags::All)
Gets Page Fault stats covering the lifetime of the process.
static int32 GetPakchunkIndexFromPakFile (FStringView InFilename)
static FStringView GetPakFilenamePrefix ()
static const TCHAR * GetPathVarDelimiter ()
return the delimiter between paths in the PATH environment variable.
static FString GetPendingActivationProtocol ()
Returns activation protocol that's waiting to be broadcast.
static IPlatformChunkInstall * GetPlatformChunkInstall ()
Returns the platform specific chunk based install interface.
static IPlatformCompression * GetPlatformCompression ()
Returns the platform specific compression interface.
static const TCHAR * GetPlatformFeaturesModuleName ()
Return the name of the platform features module.
static IPlatformHostCommunication & GetPlatformHostCommunication ()
Returns the platform specific interface for communication with processes running on the host pc.
static bool GetPlatformScreenWarnings (TArray< FText > &PlatformScreenWarnings)
Returns any platform specific warning messages we want printed on screen.
static struct FAsyncIOSystemBase * GetPlatformSpecificAsyncIOSystem ()
Return the platform specific async IO system, or nullptr if the standard one should be used.
static FPlatformUserId GetPlatformUserForUserIndex (int32 LocalUserIndex)
static TArray< FString > GetPreferredLanguages ()
Returns an array of the user's preferred languages in order of preference.
static FString GetPrimaryGPUBrand ()
static EProcessDiagnosticFlags GetProcessDiagnostics ()
Returns non-zero if a performance-sensitive diagnostic, like a memory sanitizer, is detected for this process.
static const FProcessorGroupDesc & GetProcessorGroupDesc ()
static bool GetSHA256Signature (const void *Data, uint32 ByteSize, FSHA256Signature &OutSignature)
Generates the SHA256 signature of the given data.
static bool GetStoredValue (const FString &InStoreId, const FString &InSectionName, const FString &InKeyName, FString &OutValue)
Get the value for the given section and key from the platform specific key->value store Note: The key->value store is user-specific, but may be used to share data between different applications for the same user.
static const TCHAR * GetSystemErrorMessage (TCHAR *OutBuffer, int32 BufferCount, int32 Error)
Returns the last system error code in string form.
static TArray< uint8 > GetSystemFontBytes ()
static FString GetTimeZoneId ()
Get the timezone identifier for this platform, or an empty string if the default timezone calculation will work.
static const TCHAR * GetUBTPlatform ()
static const TCHAR * GetUBTTarget ()
static const TCHAR * GetUBTTargetName ()
static FString GetUniqueAdvertisingId ()
Returns a unique string for advertising identification.
static int32 GetUserIndexForPlatformUser (FPlatformUserId PlatformUser)
static bool GetUseVirtualJoysticks ()
Returns whether the platform wants to use a touch screen for virtual joysticks.
static void GetValidTargetPlatforms (TArray< FString > &TargetPlatformNames)
Return an ordered list of target platforms this runtime can support (ie Android_DXT, Android would mean that it prefers Android_DXT, but can use Android as well)
static const float GetVirtualKeyboardInputHeight ()
static bool GetVolumeButtonsHandledBySystem ()
static bool HasActiveWiFiConnection ()
Returns whether WiFi connection is currently active.
static bool HasMemoryWarningHandler ()
Determines if a warning handler has been set.
static bool HasNonoptionalCPUFeatures ()
static bool HasPlatformFeature (const TCHAR *FeatureName)
Returns whether the given platform feature is currently available (for instance, Metal is only available in IOS8 and with A7 devices)
static bool HasProjectPersistentDownloadDir ()
Return true if the PersistentDownloadDir is available.
static bool HasSeparateChannelForDebugOutput ()
Whether the platform has a separate debug channel to stdout (eg.
static bool HasVariableHardware ()
Returns whether the platform has variable hardware (configurable/upgradeable system).
static void HidePlatformStartupScreen ()
static FORCEINLINE void InitTaggedStorage (uint32 NumTags)
Platform specific function for initializing storage of tagged memory buffers.
static FORCEINLINE bool Is64bitOperatingSystem ()
Detects whether we're running in a 64-bit operating system.
static bool IsCacheStorageAvailable ()
For platforms that support cache storage functionality, setting a directory for it when it's not available can result in errors.
static FORCEINLINE bool IsDebuggerPresent ()
Return true if a debugger is present.
static bool IsEnsureAllowed ()
Allows disabling ensure()s without rebuilding the binary, by either a commandline switch or a hotfix.
static FORCEINLINE bool IsInLowPowerMode ()
static bool IsLocalPrintThreadSafe ()
Whether LocalPrint can be called from any thread without overlapping.
static bool IsLowLevelOutputDebugStringStructured ()
Whether LowLevelOutputDebugString[f] can receive structured output as lines of JSON.
static bool IsPackagedForDistribution ()
static bool IsPGIActive ()
Returns true if PGI (profile-guided instrumentation, needed for PGO) is currently ongoing.
static bool IsPGICapableBinary ()
Returns true if this binary has been instrumented for collection of data needed for profile-guided optimization (PGO) This value is not expected to change during the run-time.
static bool IsPGOEnabled ()
Returns true if PGO is currently enabled.
static bool IsRegisteredForRemoteNotifications ()
Returns whether or not the device has been registered to receive remote notifications.
static bool IsRemoteSession ()
Check to see if the platform is being viewed remotely.
static bool IsRunningInCloud ()
Return if the game is running on cloud server.
static bool IsRunningOnBattery ()
Returns whether the platform is running on battery power or not.
static bool IsValidAbsolutePathFormat (const FString &Path)
Checks structure of the path against platform formatting requirements.
static const TCHAR * LaunchDir ()
Get the directory the application was launched from (useful for commandline utilities)
static FString LoadTextFileFromPlatformPackage (const FString &RelativePath)
Loads a text file relative to the package root on platforms that distribute apps in package formats.
static void LocalPrint (const TCHAR *Str)
Prints string to the default output.
static void LogNameEventStatsInit ()
static void LowLevelOutputDebugString (const TCHAR *Message)
Sends a message to a remote tool, and debugger consoles.
static void VARARGS LowLevelOutputDebugStringf (const TCHAR *Format,...)
static FORCENOINLINE void MemoryBarrier ()
Enforces strict memory load/store ordering across the memory barrier call.
static EAppReturnType::Type MessageBoxExt (EAppMsgType::Type MsgType, const TCHAR *Text, const TCHAR *Caption)
Show a message box if possible, otherwise print a message and return the default.
static bool NeedsNonoptionalCPUFeaturesCheck ()
static void NormalizePath (FString &InPath)
Platform-specific normalization of path E.g.
static void NormalizePath (FStringBuilderBase &InPath)
Platform-specific normalization of path E.g.
static int32 NumberOfCores ()
return the number of hardware CPU cores
static int32 NumberOfCoresIncludingHyperthreads ()
return the number of logical CPU cores
static int32 NumberOfIOWorkerThreadsToSpawn ()
Return the number of worker threads we should spawn to service IO, NOT based on number of cores.
static int32 NumberOfWorkerThreadsToSpawn ()
Return the number of worker threads we should spawn, based on number of cores.
static bool OsExecute (const TCHAR *CommandType, const TCHAR *Command, const TCHAR *CommandLine=NULL)
Has the OS execute a command and path pair (such as launch a browser)
static void ParseChunkIdPakchunkIndexMapping (TArray< FString > ChunkIndexRedirects, TMap< int32, int32 > &OutMapping)
static void PlatformHandleSplashScreen (bool ShowSplashScreen=false)
Called to dismiss splash screen.
static void PlatformInit ()
static void PlatformPreInit ()
Called during appInit() after cmd line setup.
static void PlatformTearDown ()
Called during AppExit().
static FORCEINLINE void Prefetch (const void *Ptr)
static FORCEINLINE void Prefetch (const void *Ptr, int32 Offset)
static FORCEINLINE void PrefetchBlock (const void *Ptr, int32 NumBytes)
static void PrepareMobileHaptics (EMobileHapticsType Type)
For mobile devices, this will crank up a haptic engine for the specified type to be played later with TriggerMobileHaptics If this is called again before Release, it will switch to this type.
static const TCHAR * ProjectDir ()
Return the project directory.
static void PromptForRemoteDebugging (bool bIsEnsure)
static void PumpEssentialAppMessages ()
Pumps app messages only if there are essential keep-alive messages pending.
static void PumpMessagesForSlowTask ()
static void PumpMessagesOutsideMainLoop ()
static void RaiseException (uint32 ExceptionCode)
static void RegisterForRemoteNotifications ()
Requests permission to send remote notifications to the user's device.
static void ReleaseMobileHaptics ()
For mobile devices, this will shutdown the haptics, allowing system to put it to reset as needed.
static bool RemoveNetworkListener (FDelegateHandle Handle)
static bool RequestDeviceCheckToken (TFunction< void(const TArray< uint8 > &)> QuerySucceededFunc, TFunction< void(const FString &, const FString &)> QueryFailedFunc)
static void RequestExit (bool Force, const TCHAR *CallSite=nullptr)
Requests application exit.
static void RequestExitWithStatus (bool Force, uint8 ReturnCode, const TCHAR *CallSite=nullptr)
Requests application exit with a specified return code.
static bool RestartApplication ()
Requests application to restart.
static bool RestartApplicationWithCmdLine (const char *CmdLine)
Requests application to restart appending the passed in CmdLine to the restart.
static const TCHAR * RootDir ()
Get the application root directory.
static void SetAllowedDeviceOrientation (EDeviceScreenOrientation NewAllowedDeviceOrientation)
Change the allowed orientation of the device.
static FORCEINLINE void SetBrightness (float bBright)
static void SetCrashHandler (void(*CrashHandler)(const FGenericCrashContext &Context))
Installs handler for the unexpected (due to error) termination of the program, including, but not limited to, crashes.
static ECrashHandlingType SetCrashHandlingType (ECrashHandlingType Type)
Sets the type of crash handling done by the engine.
static void SetEnvironmentVar (const TCHAR *VariableName, const TCHAR *Value)
Sets an environment variable to the local process's environment.
static void SetGracefulTerminationHandler ()
Set/restore the Console Interrupt (Control-C, Control-Break, Close) handler.
static void SetLastError (uint32 ErrorCode)
static void SetMemoryWarningHandler (void(*Handler)(const FGenericMemoryWarningContext &Context))
Set a handler to be called when there is a memory warning from the OS.
static void SetNetworkConnectionStatus (ENetworkConnectionStatus NewNetworkConnectionStatus)
Updates the current status for the network connection.
static void SetOverrideProjectDir (const FString &InOverrideDir)
Allows a game/program/etc to control the game directory in a special place (for instance, monolithic programs that don't have .uprojects)
static void SetShouldPromptForRemoteDebugging (bool bInShouldPrompt)
static void SetShouldPromptForRemoteDebugOnEnsure (bool bInShouldPrompt)
static bool SetStoredValue (const FString &InStoreId, const FString &InSectionName, const FString &InKeyName, const FString &InValue)
Set the value for the given section and key in the platform specific key->value store Note: The key->value store is user-specific, but may be used to share data between different applications for the same user.
static bool SetStoredValues (const FString &InStoreId, const FString &InSectionName, const TMap< FString, FString > &InKeyValues)
Set the value for the given section and key in the platform specific key->value store Note: The key->value store is user-specific, but may be used to share data between different applications for the same user.
static void SetUBTTargetName (const TCHAR *InTargetName)
static bool SetupSyscallFilters ()
static void SetUTF8Output ()
Sets the default output to UTF8.
static void SetVolumeButtonsHandledBySystem (bool enabled)
static void ShareURL (const FString &URL, const FText &Description, int32 LocationHintX, int32 LocationHintY)
Perform a mobile-style sharing of a URL.
static bool ShouldDisablePluginAtRuntime (const FString &PluginName)
Allows platform at runtime to disable unsupported plugins.
static bool ShouldDisplayTouchInterfaceOnFakingTouchEvents ()
static void ShowConsoleWindow ()
static FORCEINLINE void ShutdownTaggedStorage ()
Platform specific function for freeing storage of tagged memory buffers.
static bool StartNewPGOCollection (const FString &AbsoluteFileName)
On platforms that support run-time PGI on/off, starts a new collection with a given file name.
template<typename CharType>
static void StatNamedEvent (const CharType *Text)
Stats logging for named event.
static bool StopPGOCollectionAndCloseFile ()
On platforms that support run-time PGI on/off, stops the current collection and writes out the file (or completes its write).
static void SubmitErrorReport (const TCHAR *InErrorHist, EErrorReportMode::Type InMode)
Submits a crash report to a central server (release builds only)
static FORCEINLINE bool SupportsBackbufferSampling ()
static FORCEINLINE bool SupportsBrightness ()
static bool SupportsDeviceCheckToken ()
static bool SupportsForceTouchInput ()
static bool SupportsFullCrashDumps ()
Platform can generate a full-memory crashdump during crash handling.
static bool SupportsLocalCaching ()
static bool SupportsMessaging ()
static bool SupportsMultithreadedFileHandles ()
static bool SupportsTouchInput ()
static FORCEINLINE void TagBuffer (const char *Label, uint32 Category, const void *Buffer, size_t BufferSize)
Platform specific function for tagging a memory buffer with a label.
static void TearDown ()
Frees any memory retained by FGenericPlatformMisc.
static void TickHotfixables ()
Ticks values that can be hotfixable in the config.
static void TickStatNamedEvents ()
static void TriggerMobileHaptics ()
For mobile devices, this will kick the haptic type that was set in PrepareMobileHaptics.
static void UnregisterForRemoteNotifications ()
Requests unregistering from receiving remote notifications on the user's device.
static void UpdateHotfixableEnsureSettings ()
Updates hotfixable ensure settings from config and commandline (config takes priority).
static FORCEINLINE bool UseHDRByDefault ()
static bool UseRenderThread ()
Checks if platform wants to use a rendering thread on current device.
static const FString VersionCheckPlatformName ()
static bool WasLaunchedStreaming ()
Return true if the game is being streamed to a separate client device.
Data Fields
TCHAR * Result
TCHAR int32 ResultLength
Static Public Attributes
static int32 AndroidBuildVersion
static int32 AndroidMajorVersion
static FString AndroidVersion
static bool bNeedsRestartAfterPSOPrecompile
static TMap< FString, FString > ConfigRulesVariables
static FString DeviceBuildNumber
static FString DeviceMake
static FString DeviceModel
static FString OSLanguage
static FString ProductName
static int32 TargetSDKVersion
static bool VolumeButtonsHandledBySystem
Static Private Member Functions
static const ANSICHAR * CodeToString (int Signal, int si_code)
Static Private Attributes
static EDeviceScreenOrientation DeviceOrientation
Additional Inherited Members
Static Protected Member Functions inherited from FGenericPlatformMisc
static void GetConfiguredCoreLimits (int32 PlatformNumPhysicalCores, int32 PlatformNumLogicalCores, bool &bOutFullyInitialized, int32 &OutPhysicalCoreLimit, int32 &OutLogicalCoreLimit, bool &bOutSetPhysicalCountToLogicalCount)
Parse CoreLimit from CommandLine or from the SetCoreLimit value.
Static Protected Attributes inherited from FGenericPlatformMisc
static EDeviceScreenOrientation AllowedDeviceOrientation
static bool bPromptForRemoteDebugOnEnsure
Whether the user should be prompted to allow for a remote debugger to be attached on an ensure.
static bool bShouldPromptForRemoteDebugging
Whether the user should be prompted to allow for a remote debugger to be attached.
static ENetworkConnectionStatus CurrentNetworkConnectionStatus
Detailed Description
Android implementation of the misc OS functions.
Definition at line 32 of file AndroidPlatformMisc.h.
Member Typedef Documentation
OnPauseCallBackType
typedef TFunction<void()> FAndroidMisc::OnPauseCallBackType
Definition at line 230 of file AndroidPlatformMisc.h.
ReInitWindowCallbackType
typedef TFunction<void(void* NewNativeHandle)> FAndroidMisc::ReInitWindowCallbackType
Definition at line 222 of file AndroidPlatformMisc.h.
ReleaseWindowCallbackType
typedef TFunction<void()> FAndroidMisc::ReleaseWindowCallbackType
Definition at line 225 of file AndroidPlatformMisc.h.
Member Enumeration Documentation
EBatteryState
enum FAndroidMisc::EBatteryState
Enumerator
BATTERY_STATE_UNKNOWN
BATTERY_STATE_CHARGING
BATTERY_STATE_DISCHARGING
BATTERY_STATE_NOT_CHARGING
BATTERY_STATE_FULL
Definition at line 132 of file AndroidPlatformMisc.h.
ECoreFrequencyProperty
enum class FAndroidMisc::ECoreFrequencyProperty strong
Enumerator
CurrentFrequency
MaxFrequency
MinFrequency
Definition at line 286 of file AndroidPlatformMisc.h.
Member Function Documentation
AddNetworkListener()
FDelegateHandle FAndroidMisc::AddNetworkListener (FOnNetworkConnectionChangedDelegate && InNewDelegate) static
AllowThreadHeartBeat()
bool FAndroidMisc::AllowThreadHeartBeat () static
References AllowThreadHeartBeat().
Referenced by AllowThreadHeartBeat().
AreHeadPhonesPluggedIn()
bool FAndroidMisc::AreHeadPhonesPluggedIn () static
CodeToString()
const ANSICHAR * FAndroidMisc::CodeToString (int Signal, int si_code) static private
CreateGuid()
void FAndroidMisc::CreateGuid (struct FGuid & Result) static
References Result.
Referenced by USTRUCT().
DeleteStoredSection()
bool FAndroidMisc::DeleteStoredSection (const FString & InStoreId, const FString & InSectionName) static
References DeleteStoredSection().
Referenced by DeleteStoredSection().
DeleteStoredValue()
bool FAndroidMisc::DeleteStoredValue (const FString & InStoreId, const FString & InSectionName, const FString & InKeyName) static
References DeleteStoredValue().
Referenced by DeleteStoredValue().
Expand16BitIndicesTo32BitOnLoad()
bool FAndroidMisc::Expand16BitIndicesTo32BitOnLoad () static
Returns whether or not a 16 bit index buffer should be promoted to 32 bit on load, needed for some Android devices.
FileExistsInPlatformPackage()
bool FAndroidMisc::FileExistsInPlatformPackage (const FString & RelativePath) static
GetAndroidMajorVersion()
int32 FAndroidMisc::GetAndroidMajorVersion () static
GetAndroidVersion()
const FString FAndroidMisc::GetAndroidVersion () static
GetBatteryLevel()
int FAndroidMisc::GetBatteryLevel () static
GetBatteryState()
FBatteryState FAndroidMisc::GetBatteryState () static
GetCellularPreference()
int32 FAndroidMisc::GetCellularPreference () static
References GetCellularPreference().
Referenced by GetCellularPreference().
GetConfigRuleVars()
const TMap< FString, FString > & FAndroidMisc::GetConfigRuleVars () static
GetCoreFrequency()
uint32 FAndroidMisc::GetCoreFrequency (int32 CoreIndex, ECoreFrequencyProperty CoreFrequencyProperty) static
GetCPUBrand()
FString FAndroidMisc::GetCPUBrand () static
GetCPUChipset()
FString FAndroidMisc::GetCPUChipset () static
GetCPUState()
FCPUState & FAndroidMisc::GetCPUState () static
GetCPUTemperature()
float FAndroidMisc::GetCPUTemperature () static
GetCPUVendor()
FString FAndroidMisc::GetCPUVendor () static
GetDefaultDeviceProfileName()
const TCHAR * FAndroidMisc::GetDefaultDeviceProfileName () inline static
Definition at line 109 of file AndroidPlatformMisc.h.
References TEXT.
GetDefaultLocale()
FString FAndroidMisc::GetDefaultLocale () static
GetDeviceBuildNumber()
const FString FAndroidMisc::GetDeviceBuildNumber () static
GetDeviceMake()
const FString FAndroidMisc::GetDeviceMake () static
GetDeviceModel()
const FString FAndroidMisc::GetDeviceModel () static
GetDeviceOrientation()
EDeviceScreenOrientation FAndroidMisc::GetDeviceOrientation () inline static
Definition at line 42 of file AndroidPlatformMisc.h.
References DeviceOrientation.
GetDeviceTemperatureLevel()
float FAndroidMisc::GetDeviceTemperatureLevel () static
GetDeviceVolume()
int32 FAndroidMisc::GetDeviceVolume () static
GetDiskTotalAndFreeSpace()
bool FAndroidMisc::GetDiskTotalAndFreeSpace (const FString & InPath, uint64 & TotalNumberOfBytes, uint64 & NumberOfFreeBytes) static
GetEnvironmentVariable()
FString FAndroidMisc::GetEnvironmentVariable (const TCHAR * VariableName) static
References GetEnvironmentVariable().
Referenced by GetEnvironmentVariable().
GetFatalSignalMessage()
FString FAndroidMisc::GetFatalSignalMessage (int Signal, siginfo * Info) static
References Info.
GetGLVersion()
FString FAndroidMisc::GetGLVersion () static
GetGPUFamily()
FString FAndroidMisc::GetGPUFamily () static
GetMaxPathLength()
FORCEINLINE int32 FAndroidMisc::GetMaxPathLength () inline static
Definition at line 51 of file AndroidPlatformMisc.h.
References ANDROID_MAX_PATH, FORCEINLINE, and GetMaxPathLength().
Referenced by GetMaxPathLength().
GetMobilePropagateAlphaSetting()
int FAndroidMisc::GetMobilePropagateAlphaSetting () static
Will return true if we wish to propagate the alpha to the backbuffer.
GetNativeDisplayRefreshRate()
int32 FAndroidMisc::GetNativeDisplayRefreshRate () static
GetNetworkConnectionType()
ENetworkConnectionType FAndroidMisc::GetNetworkConnectionType () static
GetOnPauseCallback()
OnPauseCallBackType FAndroidMisc::GetOnPauseCallback () static
GetOnReInitWindowCallback()
ReInitWindowCallbackType FAndroidMisc::GetOnReInitWindowCallback () static
GetOnReleaseWindowCallback()
ReleaseWindowCallbackType FAndroidMisc::GetOnReleaseWindowCallback () static
GetOSLanguage()
const FString FAndroidMisc::GetOSLanguage () static
GetOSVersion()
FString FAndroidMisc::GetOSVersion () static
GetOSVersions()
void FAndroidMisc::GetOSVersions (FString & out_OSVersionLabel, FString & out_OSSubVersionLabel) static
GetOverrideResolution()
bool FAndroidMisc::GetOverrideResolution (int32 & ResX, int32 & ResY) inline static
Definition at line 229 of file AndroidPlatformMisc.h.
GetPendingActivationProtocol()
FString FAndroidMisc::GetPendingActivationProtocol () static
GetPlatformChunkInstall()
IPlatformChunkInstall * FAndroidMisc::GetPlatformChunkInstall () static
GetPrimaryGPUBrand()
FString FAndroidMisc::GetPrimaryGPUBrand () static
GetProductName()
const FString FAndroidMisc::GetProductName () static
GetProjectVersion()
const FString FAndroidMisc::GetProjectVersion () static
GetStoredValue()
bool FAndroidMisc::GetStoredValue (const FString & InStoreId, const FString & InSectionName, const FString & InKeyName, FString & OutValue) static
References GetStoredValue().
Referenced by GetStoredValue(), and FIOSCommandLineHelper::InitCommandArgs().
GetSupportedNativeDisplayRefreshRates()
TArray< int32 > FAndroidMisc::GetSupportedNativeDisplayRefreshRates () static
GetSystemErrorMessage()
const TCHAR * FAndroidMisc::GetSystemErrorMessage (TCHAR * OutBuffer, int32 BufferCount, int32 Error) static
References Error, and GetSystemErrorMessage().
Referenced by FFileSystemError::GetMessage(), GetSystemErrorMessage(), and FFileSystemError::operator<<.
GetSystemFontBytes()
TArray< uint8 > FAndroidMisc::GetSystemFontBytes () static
Returns
Memory representing a true type or open type font provided by the platform as a default font for unreal to consume; empty array if the default font failed to load.
GetTargetSDKVersion()
int32 FAndroidMisc::GetTargetSDKVersion () static
GetThreadName()
const char * FAndroidMisc::GetThreadName (uint32 ThreadId) static
GetUseVirtualJoysticks()
bool FAndroidMisc::GetUseVirtualJoysticks () static
GetValidTargetPlatforms()
void FAndroidMisc::GetValidTargetPlatforms (class TArray< class FString > & TargetPlatformNames) static
GetVirtualKeyboardInputHeight()
float FAndroidMisc::GetVirtualKeyboardInputHeight () static
GetVolumeButtonsHandledBySystem()
bool FAndroidMisc::GetVolumeButtonsHandledBySystem () static
GetVolumeState()
int FAndroidMisc::GetVolumeState (double * OutTimeOfChangeInSec = nullptr) static
GetVulkanVersion()
FString FAndroidMisc::GetVulkanVersion () static
HandleNewIntentUri()
void FAndroidMisc::HandleNewIntentUri (const FString & IntentUri) static
HasMemoryWarningHandler()
bool FAndroidMisc::HasMemoryWarningHandler () static
HasPlatformFeature()
bool FAndroidMisc::HasPlatformFeature (const TCHAR * FeatureName) static
References HasPlatformFeature().
Referenced by HasPlatformFeature().
HasVulkanDriverSupport()
bool FAndroidMisc::HasVulkanDriverSupport () static
IsAllowedRemoteNotifications()
bool FAndroidMisc::IsAllowedRemoteNotifications () static
IsDebuggerPresent()
bool FAndroidMisc::IsDebuggerPresent () static
IsDesktopVulkanAvailable()
bool FAndroidMisc::IsDesktopVulkanAvailable () static
IsExternalMemoryAndroidHardwareBufferExtensionLoaded()
bool FAndroidMisc::IsExternalMemoryAndroidHardwareBufferExtensionLoaded () static
IsInLowPowerMode()
bool FAndroidMisc::IsInLowPowerMode () static
IsInSignalHandler()
bool FAndroidMisc::IsInSignalHandler () static
IsLocalPrintThreadSafe()
bool FAndroidMisc::IsLocalPrintThreadSafe () inline static
Definition at line 37 of file AndroidPlatformMisc.h.
IsRunningOnBattery()
bool FAndroidMisc::IsRunningOnBattery () static
IsSupportedAndroidDevice()
bool FAndroidMisc::IsSupportedAndroidDevice () static
IsVulkanAvailable()
bool FAndroidMisc::IsVulkanAvailable () static
LoadTextFileFromPlatformPackage()
FString FAndroidMisc::LoadTextFileFromPlatformPackage (const FString & RelativePath) static
LocalPrint()
void FAndroidMisc::LocalPrint (const TCHAR * Message) static
MemoryBarrier()
FORCEINLINE void FAndroidMisc::MemoryBarrier () inline static
Definition at line 246 of file AndroidPlatformMisc.h.
References FORCEINLINE.
Referenced by FFixedUObjectArray::AddRange(), FFixedUObjectArray::AddSingle(), IAsyncReadRequest::Cancel(), TQueue< T, Mode >::Enqueue(), TQueue< T, Mode >::Enqueue(), TTripleBuffer< BufferType >::Reset(), IAsyncReadRequest::SetAllComplete(), IAsyncReadRequest::SetDataComplete(), FAsyncTaskBase::Start(), FAutoDeleteAsyncTask< FCancelIORequestsTask >::Start(), FAsyncTaskBase::SyncCompletion(), and FAsyncTaskBase::WaitCompletionWithTimeout().
MessageBoxExt()
EAppReturnType::Type FAndroidMisc::MessageBoxExt (EAppMsgType::Type MsgType, const TCHAR * Text, const TCHAR * Caption) static
References Caption, MessageBoxExt(), and Text.
Referenced by MessageBoxExt(), and FMacFeedbackContext::YesNof().
NonReentrantRequestExit()
void FAndroidMisc::NonReentrantRequestExit () static
NumberOfCores()
int32 FAndroidMisc::NumberOfCores () static
Referenced by PhysSingleThreadedMode().
NumberOfCoresIncludingHyperthreads()
int32 FAndroidMisc::NumberOfCoresIncludingHyperthreads () static
Referenced by ENUM_CLASS_FLAGS().
OverrideFatalSignalHandler()
void FAndroidMisc::OverrideFatalSignalHandler (void(* FatalSignalHandlerOverrideFunc)(int Signal, struct siginfo *Info, void *Context, uint32 CrashingThreadId)) static
References Info.
PlatformHandleSplashScreen()
void FAndroidMisc::PlatformHandleSplashScreen (bool ShowSplashScreen) static
PlatformInit()
void FAndroidMisc::PlatformInit () static
PlatformPreInit()
void FAndroidMisc::PlatformPreInit () static
PlatformTearDown()
void FAndroidMisc::PlatformTearDown () static
PrepareMobileHaptics()
void FAndroidMisc::PrepareMobileHaptics (EMobileHapticsType Type) static
RegisterForRemoteNotifications()
void FAndroidMisc::RegisterForRemoteNotifications () static
RegisterThreadName()
void FAndroidMisc::RegisterThreadName (const char * Name, uint32 ThreadId) static
References Name.
ReleaseMobileHaptics()
void FAndroidMisc::ReleaseMobileHaptics () static
RemoveNetworkListener()
bool FAndroidMisc::RemoveNetworkListener (FDelegateHandle Handle) static
References Handle.
RequestExit()
void FAndroidMisc::RequestExit (bool Force, const TCHAR * CallSite = nullptr) static
References Force.
RestartApplication()
bool FAndroidMisc::RestartApplication () static
SaveDeviceOrientation()
void FAndroidMisc::SaveDeviceOrientation (EDeviceScreenOrientation NewDeviceOrentation) inline static
Definition at line 301 of file AndroidPlatformMisc.h.
References DeviceOrientation.
SetAllowedDeviceOrientation()
void FAndroidMisc::SetAllowedDeviceOrientation (EDeviceScreenOrientation NewAllowedDeviceOrientation) static
References SetAllowedDeviceOrientation().
Referenced by SetAllowedDeviceOrientation().
SetCellularPreference()
void FAndroidMisc::SetCellularPreference (int32 Value) static
References SetCellularPreference(), and Value.
Referenced by SetCellularPreference().
SetCrashHandler()
void FAndroidMisc::SetCrashHandler (void(* CrashHandler)(const FGenericCrashContext &Context)) static
SetForceUnsupported()
void FAndroidMisc::SetForceUnsupported (bool bInOverride) static
SetMemoryWarningHandler()
void FAndroidMisc::SetMemoryWarningHandler (void(* Handler)(const FGenericMemoryWarningContext &Context)) static
SetNativeDisplayRefreshRate()
bool FAndroidMisc::SetNativeDisplayRefreshRate (int32 RefreshRate) static
SetOnPauseCallback()
void FAndroidMisc::SetOnPauseCallback (OnPauseCallBackType InOnPauseCallback) static
SetOnReInitWindowCallback()
void FAndroidMisc::SetOnReInitWindowCallback (ReInitWindowCallbackType InOnReInitWindowCallback) static
SetOnReleaseWindowCallback()
void FAndroidMisc::SetOnReleaseWindowCallback (ReleaseWindowCallbackType InOnReleaseWindowCallback) static
SetStoredValue()
bool FAndroidMisc::SetStoredValue (const FString & InStoreId, const FString & InSectionName, const FString & InKeyName, const FString & InValue) static
References SetStoredValue().
Referenced by SetStoredValue().
SetVersionInfo()
void FAndroidMisc::SetVersionInfo (FString AndroidVersion, int32 InTargetSDKVersion, FString DeviceMake, FString DeviceModel, FString DeviceBuildNumber, FString OSLanguage, FString ProductName) static
References AndroidVersion, DeviceBuildNumber, DeviceMake, DeviceModel, OSLanguage, and ProductName.
SetVolumeButtonsHandledBySystem()
void FAndroidMisc::SetVolumeButtonsHandledBySystem (bool enabled) static
ShareURL()
void FAndroidMisc::ShareURL (const FString & URL, const FText & Description, int32 LocationHintX, int32 LocationHintY) static
ShouldUseDesktopVulkan()
bool FAndroidMisc::ShouldUseDesktopVulkan () static
ShouldUseVulkan()
bool FAndroidMisc::ShouldUseVulkan () static
ShowConsoleWindow()
void FAndroidMisc::ShowConsoleWindow () static
SupportsBackbufferSampling()
bool FAndroidMisc::SupportsBackbufferSampling () static
SupportsES30()
bool FAndroidMisc::SupportsES30 () static
References SupportsES30().
Referenced by SupportsES30().
SupportsFloatingPointRenderTargets()
bool FAndroidMisc::SupportsFloatingPointRenderTargets () static
SupportsLocalCaching()
bool FAndroidMisc::SupportsLocalCaching () static
SupportsShaderFramebufferFetch()
bool FAndroidMisc::SupportsShaderFramebufferFetch () static
SupportsShaderIOBlocks()
bool FAndroidMisc::SupportsShaderIOBlocks () static
SupportsTouchInput()
bool FAndroidMisc::SupportsTouchInput () static
TriggerCrashHandler()
void FAndroidMisc::TriggerCrashHandler (ECrashContextType InType, const TCHAR * InErrorMessage, const TCHAR * OverrideCallstack = nullptr) static
TriggerMobileHaptics()
void FAndroidMisc::TriggerMobileHaptics () static
UE_DEPRECATED() [1/2]
FAndroidMisc::UE_DEPRECATED (4. 21, "void FPlatformMisc::GetEnvironmentVariable(Name, Result, Length) is deprecated. Use FString FPlatformMisc::GetEnvironmentVariable(Name) instead.") const
UE_DEPRECATED() [2/2]
FAndroidMisc::UE_DEPRECATED (5. 1, "SetDeviceOrientation is deprecated. Use SetAllowedDeviceOrientation instead.")
UnlockAndroidWindow()
void FAndroidMisc::UnlockAndroidWindow () static
UnregisterForRemoteNotifications()
void FAndroidMisc::UnregisterForRemoteNotifications () static
UpdateDeviceOrientation()
void FAndroidMisc::UpdateDeviceOrientation () static
UseNewWindowBehavior()
bool FAndroidMisc::UseNewWindowBehavior () static
References Color, and Text.
UseRenderThread()
bool FAndroidMisc::UseRenderThread () static
References UseRenderThread().
Referenced by UseRenderThread().
Field Documentation
AndroidBuildVersion
int32 FAndroidMisc::AndroidBuildVersion static
Definition at line 277 of file AndroidPlatformMisc.h.
AndroidMajorVersion
int32 FAndroidMisc::AndroidMajorVersion static
Definition at line 268 of file AndroidPlatformMisc.h.
AndroidVersion
FString FAndroidMisc::AndroidVersion static
Definition at line 267 of file AndroidPlatformMisc.h.
Referenced by SetVersionInfo().
bNeedsRestartAfterPSOPrecompile
bool FAndroidMisc::bNeedsRestartAfterPSOPrecompile static
Definition at line 284 of file AndroidPlatformMisc.h.
ConfigRulesVariables
TMap<FString, FString> FAndroidMisc::ConfigRulesVariables static
Definition at line 280 of file AndroidPlatformMisc.h.
DeviceBuildNumber
FString FAndroidMisc::DeviceBuildNumber static
Definition at line 272 of file AndroidPlatformMisc.h.
Referenced by SetVersionInfo().
DeviceMake
FString FAndroidMisc::DeviceMake static
Definition at line 270 of file AndroidPlatformMisc.h.
Referenced by SetVersionInfo().
DeviceModel
FString FAndroidMisc::DeviceModel static
Definition at line 271 of file AndroidPlatformMisc.h.
Referenced by SetVersionInfo().
DeviceOrientation
EDeviceScreenOrientation FAndroidMisc::DeviceOrientation static private
Definition at line 343 of file AndroidPlatformMisc.h.
Referenced by GetDeviceOrientation(), and SaveDeviceOrientation().
OSLanguage
FString FAndroidMisc::OSLanguage static
Definition at line 273 of file AndroidPlatformMisc.h.
Referenced by SetVersionInfo().
ProductName
FString FAndroidMisc::ProductName static
Definition at line 274 of file AndroidPlatformMisc.h.
Referenced by SetVersionInfo().
Result
TCHAR* FAndroidMisc::Result
Definition at line 57 of file AndroidPlatformMisc.h.
Referenced by CreateGuid().
ResultLength
TCHAR int32 FAndroidMisc::ResultLength
Definition at line 57 of file AndroidPlatformMisc.h.
TargetSDKVersion
int32 FAndroidMisc::TargetSDKVersion static
Definition at line 269 of file AndroidPlatformMisc.h.
VolumeButtonsHandledBySystem
bool FAndroidMisc::VolumeButtonsHandledBySystem static
Definition at line 282 of file AndroidPlatformMisc.h.
The documentation for this struct was generated from the following file:
Runtime/Core/Public/Android/AndroidPlatformMisc.h