Unreal Engine 5.6 C++ API: UE::MovieScene::FEntityAllocationIterator Struct Reference
UE::MovieScene::FEntityAllocationIterator Struct Reference
Object that iterates all entity allocations that match a specific filter.
#include "EntityAllocationIterator.h"
Public Member Functions
MOVIESCENE_API FEntityAllocationIterator (const FEntityManager *InManager)
End iterator constructor.
MOVIESCENE_API FEntityAllocationIterator (const FEntityManager *InManager, const FEntityComponentFilter *InFilter)
Construction from the entity manager to iterate, and a filter.
MOVIESCENE_API FEntityAllocationIterator (FEntityAllocationIterator &&)
MOVIESCENE_API ~FEntityAllocationIterator ()
Destructor.
MOVIESCENE_API bool operator!= (const FEntityAllocationIterator &Other) const
Test whether this iterator is valid (ie not at the end of the iteration)
MOVIESCENE_API FEntityAllocationIteratorItem operator* () const
Retrieve the entity allocation that this iterator represents.
MOVIESCENE_API FEntityAllocationIterator & operator++ ()
Increment this iterator to the next matching allocation.
MOVIESCENE_API FEntityAllocationIterator & operator= (FEntityAllocationIterator &&)
Private Member Functions
int32 FindMatchingAllocationStartingAt (int32 Index) const
Find the index of the next allocation that matches our filter.
Private Attributes
int32 AllocationIndex
Current allocation index or Manager->EntityAllocationMasks.GetMaxIndex() when finished.
const FEntityComponentFilter * Filter
Filter to match entity allocations against.
const FEntityManager * Manager
Entity manager being iterated.
Detailed Description
Object that iterates all entity allocations that match a specific filter.
Definition at line 22 of file EntityAllocationIterator.h.
Constructor & Destructor Documentation
FEntityAllocationIterator() [1/3]
MOVIESCENE_API UE::MovieScene::FEntityAllocationIterator::FEntityAllocationIterator (const FEntityManager * InManager) explicit
End iterator constructor.
Referenced by FEntityAllocationIterator(), operator!=(), operator++(), and operator=().
FEntityAllocationIterator() [2/3]
MOVIESCENE_API UE::MovieScene::FEntityAllocationIterator::FEntityAllocationIterator (const FEntityManager * InManager, const FEntityComponentFilter * InFilter) explicit
Construction from the entity manager to iterate, and a filter.
Parameters
InManager The entity manager to iterate
InFilter Filter that defines the components to match. Copied into this object.
FEntityAllocationIterator() [3/3]
MOVIESCENE_API UE::MovieScene::FEntityAllocationIterator::FEntityAllocationIterator (FEntityAllocationIterator &&)
References FEntityAllocationIterator().
~FEntityAllocationIterator()
MOVIESCENE_API UE::MovieScene::FEntityAllocationIterator::~FEntityAllocationIterator ()
Destructor.
Member Function Documentation
FindMatchingAllocationStartingAt()
int32 UE::MovieScene::FEntityAllocationIterator::FindMatchingAllocationStartingAt (int32 Index) const private
Find the index of the next allocation that matches our filter.
operator!=()
MOVIESCENE_API bool UE::MovieScene::FEntityAllocationIterator::operator!= (const FEntityAllocationIterator & Other) const
Test whether this iterator is valid (ie not at the end of the iteration)
References FEntityAllocationIterator(), and Other.
operator*()
MOVIESCENE_API FEntityAllocationIteratorItem UE::MovieScene::FEntityAllocationIterator::operator* () const
Retrieve the entity allocation that this iterator represents.
Only valid if this iterator != end()
operator++()
MOVIESCENE_API FEntityAllocationIterator & UE::MovieScene::FEntityAllocationIterator::operator++ ()
Increment this iterator to the next matching allocation.
Only valid if this iterator != end()
References FEntityAllocationIterator().
operator=()
MOVIESCENE_API FEntityAllocationIterator & UE::MovieScene::FEntityAllocationIterator::operator= (FEntityAllocationIterator &&)
References FEntityAllocationIterator().
Field Documentation
AllocationIndex
int32 UE::MovieScene::FEntityAllocationIterator::AllocationIndex private
Current allocation index or Manager->EntityAllocationMasks.GetMaxIndex() when finished.
Definition at line 77 of file EntityAllocationIterator.h.
Filter
const FEntityComponentFilter* UE::MovieScene::FEntityAllocationIterator::Filter private
Filter to match entity allocations against.
Definition at line 71 of file EntityAllocationIterator.h.
Manager
const FEntityManager* UE::MovieScene::FEntityAllocationIterator::Manager private
Entity manager being iterated.
Definition at line 74 of file EntityAllocationIterator.h.
The documentation for this struct was generated from the following file:
Runtime/MovieScene/Public/EntitySystem/EntityAllocationIterator.h