Unreal Engine 5.6 C++ API: TPayload< Ret(Types...)> Struct Template Reference
TPayload< Ret(Types...)> Struct Template Reference
#include "DelegateInstanceInterface.h"
Public Member Functions
template<typename... ArgTypes>
TPayload (ArgTypes &&... Args)
Ret & GetResult ()
Data Fields
TTuple< Types..., Ret > Values
Detailed Description
template<typename Ret, typename... Types>
struct TPayload< Ret(Types...)>
Definition at line 70 of file DelegateInstanceInterface.h.
Constructor & Destructor Documentation
TPayload()
template<typename Ret, typename... Types> template<typename... ArgTypes> TPayload< Ret(Types...)>::TPayload (ArgTypes &&... Args) inline explicit
Definition at line 75 of file DelegateInstanceInterface.h.
References Forward(), and Values.
Member Function Documentation
GetResult()
template<typename Ret, typename... Types> Ret & TPayload< Ret(Types...)>::GetResult () inline
Definition at line 80 of file DelegateInstanceInterface.h.
References Values.
Field Documentation
Values
template<typename Ret, typename... Types> TTuple<Types..., Ret> TPayload< Ret(Types...)>::Values
Definition at line 72 of file DelegateInstanceInterface.h.
Referenced by TPayload(), and GetResult().
The documentation for this struct was generated from the following file:
Runtime/Core/Public/Delegates/DelegateInstanceInterface.h