Unreal Engine 5.6 C++ API: UE::Sequencer::FTimeToPixelSpace Struct Reference
UE::Sequencer::FTimeToPixelSpace Struct Reference
Utility for converting time units to slate pixel units and vice versa.
#include "TimeToPixel.h"
Public Member Functions
SEQUENCERCORE_API FTimeToPixelSpace (const FGeometry &AllottedGeometry, const TRange< double > &InLocalViewRange, const FFrameRate &InTickResolution)
SEQUENCERCORE_API FTimeToPixelSpace (float WidthPx, const TRange< double > &InLocalViewRange, const FFrameRate &InTickResolution)
SEQUENCERCORE_API FTimeToPixelSpace CreateNonLinear (TSharedPtr< INonLinearTimeTransform > InNonLinearTransform) const
SEQUENCERCORE_API float FrameDeltaToPixel (const FFrameTime &TimeDelta) const
Converts a frame delta value to pixel delta.
SEQUENCERCORE_API float FrameToPixel (const FFrameTime &Time) const
Converts a frame time to a pixel point relative to the geometry of a widget (passed into the constructor)
SEQUENCERCORE_API FFrameRate GetTickResolution () const
Retrieve the tick resolution of the current sequence.
SEQUENCERCORE_API FFrameTime PixelDeltaToFrame (float PixelDelta) const
Converts a pixel delta value to delta frame time.
SEQUENCERCORE_API double PixelDeltaToSeconds (float PixelDelta) const
Converts a pixel delta value to delta seconds time.
SEQUENCERCORE_API FFrameTime PixelToFrame (float PixelX) const
Converts a pixel value to frame time.
SEQUENCERCORE_API double PixelToSeconds (float PixelX) const
Converts a pixel value to time.
SEQUENCERCORE_API FTimeToPixelSpace RelativeTo (const FFrameTime &FrameZero) const
Make this converter relative to the specified time (ie, such that pixel 0 == FrameAmount)
SEQUENCERCORE_API float SecondsDeltaToPixel (double TimeDelta) const
Converts a time delta to a pixel delta.
SEQUENCERCORE_API float SecondsToPixel (double Time) const
Converts a time to a pixel point relative to the geometry of a widget (passed into the constructor)
Data Fields
TSharedPtr< INonLinearTimeTransform > NonLinearTransform
Protected Member Functions
FTimeToPixelSpace ()
Protected Attributes
float PixelOffset
float PixelsPerSecond
The number of pixels in the view range.
FFrameRate TickResolution
The tick resolution of the current timeline.
Detailed Description
Utility for converting time units to slate pixel units and vice versa.
Definition at line 27 of file TimeToPixel.h.
Constructor & Destructor Documentation
FTimeToPixelSpace() [1/3]
SEQUENCERCORE_API UE::Sequencer::FTimeToPixelSpace::FTimeToPixelSpace (const FGeometry & AllottedGeometry, const TRange< double > & InLocalViewRange, const FFrameRate & InTickResolution)
Referenced by FTimeToPixel::FTimeToPixel(), FTimeToPixel::FTimeToPixel(), FTimeToPixel::FTimeToPixel(), CreateNonLinear(), and RelativeTo().
FTimeToPixelSpace() [2/3]
SEQUENCERCORE_API UE::Sequencer::FTimeToPixelSpace::FTimeToPixelSpace (float WidthPx, const TRange< double > & InLocalViewRange, const FFrameRate & InTickResolution)
FTimeToPixelSpace() [3/3]
UE::Sequencer::FTimeToPixelSpace::FTimeToPixelSpace () inline protected
Definition at line 114 of file TimeToPixel.h.
Member Function Documentation
CreateNonLinear()
SEQUENCERCORE_API FTimeToPixelSpace UE::Sequencer::FTimeToPixelSpace::CreateNonLinear (TSharedPtr< INonLinearTimeTransform > InNonLinearTransform) const
References FTimeToPixelSpace().
FrameDeltaToPixel()
SEQUENCERCORE_API float UE::Sequencer::FTimeToPixelSpace::FrameDeltaToPixel (const FFrameTime & TimeDelta) const
Converts a frame delta value to pixel delta.
Parameters
TimeDelta The time delta to convert
Returns
The pixel equivalent of the delta time
FrameToPixel()
SEQUENCERCORE_API float UE::Sequencer::FTimeToPixelSpace::FrameToPixel (const FFrameTime & Time) const
Converts a frame time to a pixel point relative to the geometry of a widget (passed into the constructor)
Parameters
Time The time to convert
Returns
The pixel equivalent of the frame time
References Time.
GetTickResolution()
SEQUENCERCORE_API FFrameRate UE::Sequencer::FTimeToPixelSpace::GetTickResolution () const
Retrieve the tick resolution of the current sequence.
PixelDeltaToFrame()
SEQUENCERCORE_API FFrameTime UE::Sequencer::FTimeToPixelSpace::PixelDeltaToFrame (float PixelDelta) const
Converts a pixel delta value to delta frame time.
Parameters
PixelDelta The delta value in pixel space
Returns
The equivalent delta frame time
PixelDeltaToSeconds()
SEQUENCERCORE_API double UE::Sequencer::FTimeToPixelSpace::PixelDeltaToSeconds (float PixelDelta) const
Converts a pixel delta value to delta seconds time.
Parameters
PixelDelta The delta value in pixel space
Returns
The equivalent delta time in seconds
PixelToFrame()
SEQUENCERCORE_API FFrameTime UE::Sequencer::FTimeToPixelSpace::PixelToFrame (float PixelX) const
Converts a pixel value to frame time.
Parameters
PixelX The x value of a pixel coordinate relative to the geometry that was passed into the constructor.
Returns
The frame time where the pixel is located
PixelToSeconds()
SEQUENCERCORE_API double UE::Sequencer::FTimeToPixelSpace::PixelToSeconds (float PixelX) const
Converts a pixel value to time.
Parameters
PixelX The x value of a pixel coordinate relative to the geometry that was passed into the constructor.
Returns
The time where the pixel is located
Referenced by TPerlinNoiseChannelInterface< ChannelContainerType >::DrawExtra_Raw().
RelativeTo()
SEQUENCERCORE_API FTimeToPixelSpace UE::Sequencer::FTimeToPixelSpace::RelativeTo (const FFrameTime & FrameZero) const
Make this converter relative to the specified time (ie, such that pixel 0 == FrameAmount)
References FTimeToPixelSpace().
SecondsDeltaToPixel()
SEQUENCERCORE_API float UE::Sequencer::FTimeToPixelSpace::SecondsDeltaToPixel (double TimeDelta) const
Converts a time delta to a pixel delta.
Parameters
TimeDelta The time delta to convert
Returns
The pixel equivalent of the delta time
SecondsToPixel()
SEQUENCERCORE_API float UE::Sequencer::FTimeToPixelSpace::SecondsToPixel (double Time) const
Converts a time to a pixel point relative to the geometry of a widget (passed into the constructor)
Parameters
Time The time to convert
Returns
The pixel equivalent of the time
References Time.
Field Documentation
NonLinearTransform
TSharedPtr<INonLinearTimeTransform> UE::Sequencer::FTimeToPixelSpace::NonLinearTransform
Definition at line 111 of file TimeToPixel.h.
PixelOffset
float UE::Sequencer::FTimeToPixelSpace::PixelOffset protected
Definition at line 120 of file TimeToPixel.h.
PixelsPerSecond
float UE::Sequencer::FTimeToPixelSpace::PixelsPerSecond protected
The number of pixels in the view range.
Definition at line 119 of file TimeToPixel.h.
TickResolution
FFrameRate UE::Sequencer::FTimeToPixelSpace::TickResolution protected
The tick resolution of the current timeline.
Definition at line 117 of file TimeToPixel.h.
The documentation for this struct was generated from the following file:
Editor/SequencerCore/Public/TimeToPixel.h