Unreal Engine 5.6 C++ API: FAssetIdentifier Struct Reference
FAssetIdentifier Struct Reference
A structure defining a thing that can be reference by something else in the asset registry.
#include "AssetIdentifier.h"
Public Member Functions
FAssetIdentifier ()
FAssetIdentifier (const FPrimaryAssetId &PrimaryAssetId, FName InValueName=FName())
Construct from a primary asset id.
FAssetIdentifier (FName InPackageName, FName InObjectName=FName(), FName InValueName=FName())
Can be implicitly constructed from just the package name.
FAssetIdentifier (UObject *SourceObject, FName InValueName)
void AppendString (FStringBuilderBase &Builder) const
Appends to the given builder the string version of this identifier in Package.Object::Name format.
bool FastLess (const FAssetIdentifier &Other) const
FPrimaryAssetId GetPrimaryAssetId () const
Returns primary asset id for this identifier, if valid.
bool IsObject () const
Returns true if this represents an object, true for both package objects and PrimaryAssetId objects.
bool IsPackage () const
Returns true if this represents a package.
bool IsValid () const
Returns true if this is a valid non-null identifier.
bool IsValue () const
Returns true if this represents a specific value.
bool LexicalLess (const FAssetIdentifier &Other) const
FString ToString () const
Returns string version of this identifier in Package.Object::Name format.
void WriteCompactBinary (FCbWriter &Writer) const
Static Public Member Functions
static FAssetIdentifier FromString (const FString &String)
Converts from Package.Object::Name format.
Data Fields
FName ObjectName
Specific object within a package.
FName PackageName
The name of the package that is depended on, this is always set unless PrimaryAssetType is.
FPrimaryAssetType PrimaryAssetType
The primary asset type, if valid the ObjectName is the PrimaryAssetName.
FName ValueName
Name of specific value being referenced, if ObjectName specifies a type such as a UStruct.
Friends
uint32 GetTypeHash (const FAssetIdentifier &Key)
bool LoadFromCompactBinary (FCbFieldView Field, FAssetIdentifier &Identifier)
FArchive & operator<< (FArchive &Ar, FAssetIdentifier &AssetIdentifier)
Identifiers may be serialized as part of the registry cache, or in other contexts.
FCbWriter & operator<< (FCbWriter &Writer, const FAssetIdentifier &Identifier)
bool operator== (const FAssetIdentifier &A, const FAssetIdentifier &B)
void SerializeForLog (FCbWriter &Writer, const FAssetIdentifier &Value)
Detailed Description
A structure defining a thing that can be reference by something else in the asset registry.
Represents either a package of a primary asset id
Definition at line 11 of file AssetIdentifier.h.
Constructor & Destructor Documentation
FAssetIdentifier() [1/4]
FAssetIdentifier::FAssetIdentifier (FName InPackageName, FName InObjectName = FName(), FName InValueName = FName()) inline
Can be implicitly constructed from just the package name.
Definition at line 23 of file AssetIdentifier.h.
References ObjectName, PackageName, PrimaryAssetType, and ValueName.
Referenced by FastLess(), FromString(), GetTypeHash, LexicalLess(), LoadFromCompactBinary, operator<<, operator<<, operator==, and SerializeForLog.
FAssetIdentifier() [2/4]
FAssetIdentifier::FAssetIdentifier (const FPrimaryAssetId & PrimaryAssetId, FName InValueName = FName()) inline
Construct from a primary asset id.
Definition at line 28 of file AssetIdentifier.h.
References ObjectName, PackageName, PrimaryAssetType, and ValueName.
FAssetIdentifier() [3/4]
FAssetIdentifier::FAssetIdentifier (UObject * SourceObject, FName InValueName)
FAssetIdentifier() [4/4]
FAssetIdentifier::FAssetIdentifier () inline
Definition at line 34 of file AssetIdentifier.h.
Referenced by FromString().
Member Function Documentation
AppendString()
void FAssetIdentifier::AppendString (FStringBuilderBase & Builder) const inline
Appends to the given builder the string version of this identifier in Package.Object::Name format.
Definition at line 79 of file AssetIdentifier.h.
References TStringBuilderBase< CharType >::Append(), FPrimaryAssetId::AppendString(), GetPrimaryAssetId(), ObjectName, PackageName, PrimaryAssetType, TEXT, and ValueName.
Referenced by ToString().
FastLess()
bool FAssetIdentifier::FastLess (const FAssetIdentifier & Other) const inline
Definition at line 210 of file AssetIdentifier.h.
References FAssetIdentifier(), ObjectName, Other, PackageName, PrimaryAssetType, and ValueName.
FromString()
FAssetIdentifier FAssetIdentifier::FromString (const FString & String) inline static
Converts from Package.Object::Name format.
Definition at line 102 of file AssetIdentifier.h.
References FAssetIdentifier(), FAssetIdentifier(), FPrimaryAssetId::FromString(), FPrimaryAssetId::IsValid(), String, and TEXT.
GetPrimaryAssetId()
FPrimaryAssetId FAssetIdentifier::GetPrimaryAssetId () const inline
Returns primary asset id for this identifier, if valid.
Definition at line 37 of file AssetIdentifier.h.
References ObjectName, and PrimaryAssetType.
Referenced by AppendString(), and IsValid().
IsObject()
bool FAssetIdentifier::IsObject () const inline
Returns true if this represents an object, true for both package objects and PrimaryAssetId objects.
Definition at line 53 of file AssetIdentifier.h.
References IsValue(), and ObjectName.
Referenced by IsPackage().
IsPackage()
bool FAssetIdentifier::IsPackage () const inline
Returns true if this represents a package.
Definition at line 47 of file AssetIdentifier.h.
References IsObject(), IsValue(), and PackageName.
IsValid()
bool FAssetIdentifier::IsValid () const inline
Returns true if this is a valid non-null identifier.
Definition at line 65 of file AssetIdentifier.h.
References GetPrimaryAssetId(), FPrimaryAssetId::IsValid(), and PackageName.
IsValue()
bool FAssetIdentifier::IsValue () const inline
Returns true if this represents a specific value.
Definition at line 59 of file AssetIdentifier.h.
References ValueName.
Referenced by IsObject(), and IsPackage().
LexicalLess()
bool FAssetIdentifier::LexicalLess (const FAssetIdentifier & Other) const inline
Definition at line 193 of file AssetIdentifier.h.
References FAssetIdentifier(), ObjectName, Other, PackageName, PrimaryAssetType, and ValueName.
ToString()
FString FAssetIdentifier::ToString () const inline
Returns string version of this identifier in Package.Object::Name format.
Definition at line 71 of file AssetIdentifier.h.
References AppendString(), TStringBuilderBase< CharType >::GetData(), and TStringBuilderBase< CharType >::Len().
WriteCompactBinary()
void FAssetIdentifier::WriteCompactBinary (FCbWriter & Writer) const
Referenced by operator<<.
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FAssetIdentifier & Key) friend
Definition at line 134 of file AssetIdentifier.h.
References FAssetIdentifier(), GetTypeHash, Hash, HashCombine(), and Key.
Referenced by GetTypeHash.
LoadFromCompactBinary
bool LoadFromCompactBinary (FCbFieldView Field, FAssetIdentifier & Identifier) friend
References FAssetIdentifier().
operator<< [1/2]
FArchive & operator<< (FArchive & Ar, FAssetIdentifier & AssetIdentifier) friend
Identifiers may be serialized as part of the registry cache, or in other contexts.
If you make changes here you must also change FAssetRegistryVersion
Definition at line 152 of file AssetIdentifier.h.
References FAssetIdentifier(), Ar, FPrimaryAssetType::GetName(), FPrimaryAssetType::IsValid(), ObjectName, PackageName, PrimaryAssetType, and ValueName.
operator<< [2/2]
FCbWriter & operator<< (FCbWriter & Writer, const FAssetIdentifier & Identifier) friend
Definition at line 229 of file AssetIdentifier.h.
References FAssetIdentifier(), and WriteCompactBinary().
operator==
bool operator== (const FAssetIdentifier & A, const FAssetIdentifier & B) friend
Definition at line 129 of file AssetIdentifier.h.
References FAssetIdentifier(), A, and B.
SerializeForLog
void SerializeForLog (FCbWriter & Writer, const FAssetIdentifier & Value) friend
References FAssetIdentifier(), and Value.
Field Documentation
ObjectName
FName FAssetIdentifier::ObjectName
Specific object within a package.
If empty, assumed to be the default asset
Definition at line 18 of file AssetIdentifier.h.
Referenced by FAssetIdentifier(), FAssetIdentifier(), AppendString(), FastLess(), GetPrimaryAssetId(), IsObject(), LexicalLess(), and operator<<.
PackageName
FName FAssetIdentifier::PackageName
The name of the package that is depended on, this is always set unless PrimaryAssetType is.
Definition at line 14 of file AssetIdentifier.h.
Referenced by FAssetIdentifier(), FAssetIdentifier(), AppendString(), FastLess(), IsPackage(), IsValid(), LexicalLess(), and operator<<.
PrimaryAssetType
FPrimaryAssetType FAssetIdentifier::PrimaryAssetType
The primary asset type, if valid the ObjectName is the PrimaryAssetName.
Definition at line 16 of file AssetIdentifier.h.
Referenced by FAssetIdentifier(), FAssetIdentifier(), AppendString(), FastLess(), GetPrimaryAssetId(), LexicalLess(), and operator<<.
ValueName
FName FAssetIdentifier::ValueName
Name of specific value being referenced, if ObjectName specifies a type such as a UStruct.
Definition at line 20 of file AssetIdentifier.h.
Referenced by FAssetIdentifier(), FAssetIdentifier(), AppendString(), FastLess(), IsValue(), LexicalLess(), and operator<<.
The documentation for this struct was generated from the following file:
Runtime/CoreUObject/Public/AssetRegistry/AssetIdentifier.h