Unreal Engine 5.6 C++ API: FAssetBundleData Struct Reference
FAssetBundleData Struct Reference
A struct with a list of asset bundle entries.
#include "AssetBundleData.h"
Public Member Functions
FORCEINLINE FAssetBundleData ()
Declare constructors inline so this can be a header only class.
FAssetBundleData (const FAssetBundleData &)=default
FAssetBundleData (FAssetBundleData &&)=default
FORCEINLINE ~FAssetBundleData ()
void AddBundleAsset (FName BundleName, const FTopLevelAssetPath &AssetPath)
Adds or updates an entry with the given BundleName -> Path.
void AddBundleAssets (FName BundleName, const TArray< FTopLevelAssetPath > &AssetPaths)
Adds multiple assets at once.
void AddBundleAssetsTruncated (FName BundleName, const TArray< FSoftObjectPath > &AssetPaths)
Adds multiple assets at once, truncating to top-level asset paths if necessary.
void AddBundleAssetTruncated (FName BundleName, const FSoftObjectPath &AssetPath)
Adds or updates an entry with the given BundleName -> Path, truncating to a top-level asset path if necessary.
bool ExportTextItem (FString &ValueStr, FAssetBundleData const &DefaultValue, UObject *Parent, int32 PortFlags, UObject *ExportRootScope) const
Override Import/Export to not write out empty structs.
FAssetBundleEntry * FindEntry (FName SearchName)
Returns pointer to an entry with given Scope/Name.
bool ImportTextItem (const TCHAR *&Buffer, int32 PortFlags, UObject *Parent, FOutputDevice *ErrorText)
bool operator!= (const FAssetBundleData &Other) const
FAssetBundleData & operator= (const FAssetBundleData &)=default
FAssetBundleData & operator= (FAssetBundleData &&)=default
bool operator== (const FAssetBundleData &Other) const
Equality.
void Reset ()
Resets the data to defaults.
void SetBundleAssets (FName BundleName, TArray< FTopLevelAssetPath > &&AssetPaths)
A fast set of asset bundle assets, will destroy copied in path list.
void SetBundleAssetsTruncated (FName BundleName, const TArray< FSoftObjectPath > &AssetPaths)
Replaces the contents of this bundle with the given assets, truncating to top-level asset paths if necessary.
FString ToDebugString () const
UE_DEPRECATED (5.1, "The contents of an asset bundle now use FTopLevelAssetPath instead of FSoftObjectPath.") 1 void AddBundleAsset(FName BundleName
Adds or updates an entry with the given BundleName -> Path.
UE_DEPRECATED (5.1, "The contents of an asset bundle now use FTopLevelAssetPath instead of FSoftObjectPath.") 1 void AddBundleAssets(FName BundleName
Adds multiple assets at once.
UE_DEPRECATED (5.1, "The contents of an asset bundle now use FTopLevelAssetPath instead of FSoftObjectPath.") 1 void SetBundleAssets(FName BundleName
A fast set of asset bundle assets, will destroy copied in path list.
template<typename T>
UE_DEPRECATED (5.1, "The contents of an asset bundle now use FTopLevelAssetPath instead of FSoftObjectPath.") void AddBundleAsset(FName BundleName
Data Fields
const FSoftObjectPath & AssetPath
const TArray< FSoftObjectPath > & AssetPaths
TArray< FSoftObjectPath > && AssetPaths
TArray< FAssetBundleEntry > Bundles
List of bundles defined.
const TSoftObjectPtr< T > & SoftObjectPtr
Detailed Description
A struct with a list of asset bundle entries.
If one of these is inside a UObject it will get automatically exported as the asset registry tag AssetBundleData
Definition at line 72 of file AssetBundleData.h.
Constructor & Destructor Documentation
FAssetBundleData() [1/3]
FORCEINLINE FAssetBundleData::FAssetBundleData () inline
Declare constructors inline so this can be a header only class.
Definition at line 75 of file AssetBundleData.h.
References FORCEINLINE.
Referenced by FAssetBundleData(), FAssetBundleData(), ExportTextItem(), operator!=(), operator=(), operator=(), and operator==().
~FAssetBundleData()
FORCEINLINE FAssetBundleData::~FAssetBundleData () inline
Definition at line 76 of file AssetBundleData.h.
References FORCEINLINE.
FAssetBundleData() [2/3]
FAssetBundleData::FAssetBundleData (const FAssetBundleData &) default
References FAssetBundleData().
FAssetBundleData() [3/3]
FAssetBundleData::FAssetBundleData (FAssetBundleData &&) default
References FAssetBundleData().
Member Function Documentation
AddBundleAsset()
void FAssetBundleData::AddBundleAsset (FName BundleName, const FTopLevelAssetPath & AssetPath)
Adds or updates an entry with the given BundleName -> Path.
References AddBundleAsset(), and AssetPath.
Referenced by AddBundleAsset().
AddBundleAssets()
void FAssetBundleData::AddBundleAssets (FName BundleName, const TArray< FTopLevelAssetPath > & AssetPaths)
Adds multiple assets at once.
References AddBundleAssets(), and AssetPaths.
Referenced by AddBundleAssets().
AddBundleAssetsTruncated()
void FAssetBundleData::AddBundleAssetsTruncated (FName BundleName, const TArray< FSoftObjectPath > & AssetPaths)
Adds multiple assets at once, truncating to top-level asset paths if necessary.
References AddBundleAssetsTruncated(), and AssetPaths.
Referenced by AddBundleAssetsTruncated().
AddBundleAssetTruncated()
void FAssetBundleData::AddBundleAssetTruncated (FName BundleName, const FSoftObjectPath & AssetPath)
Adds or updates an entry with the given BundleName -> Path, truncating to a top-level asset path if necessary.
References AddBundleAssetTruncated(), and AssetPath.
Referenced by AddBundleAssetTruncated().
ExportTextItem()
bool FAssetBundleData::ExportTextItem (FString & ValueStr, FAssetBundleData const & DefaultValue, UObject * Parent, int32 PortFlags, UObject * ExportRootScope) const
Override Import/Export to not write out empty structs.
References FAssetBundleData(), ExportTextItem(), and Parent.
Referenced by ExportTextItem().
FindEntry()
FAssetBundleEntry * FAssetBundleData::FindEntry (FName SearchName)
Returns pointer to an entry with given Scope/Name.
ImportTextItem()
bool FAssetBundleData::ImportTextItem (const TCHAR *& Buffer, int32 PortFlags, UObject * Parent, FOutputDevice * ErrorText)
References Buffer, ImportTextItem(), and Parent.
Referenced by ImportTextItem().
operator!=()
bool FAssetBundleData::operator!= (const FAssetBundleData & Other) const inline
Definition at line 90 of file AssetBundleData.h.
References FAssetBundleData(), and Other.
operator=() [1/2]
FAssetBundleData & FAssetBundleData::operator= (const FAssetBundleData &) default
References FAssetBundleData().
operator=() [2/2]
FAssetBundleData & FAssetBundleData::operator= (FAssetBundleData &&) default
References FAssetBundleData().
operator==()
bool FAssetBundleData::operator== (const FAssetBundleData & Other) const inline
Equality.
Definition at line 86 of file AssetBundleData.h.
References FAssetBundleData(), Bundles, and Other.
Reset()
void FAssetBundleData::Reset ()
Resets the data to defaults.
References Reset().
Referenced by Reset().
SetBundleAssets()
void FAssetBundleData::SetBundleAssets (FName BundleName, TArray< FTopLevelAssetPath > && AssetPaths)
A fast set of asset bundle assets, will destroy copied in path list.
References AssetPaths, and SetBundleAssets().
Referenced by SetBundleAssets().
SetBundleAssetsTruncated()
void FAssetBundleData::SetBundleAssetsTruncated (FName BundleName, const TArray< FSoftObjectPath > & AssetPaths)
Replaces the contents of this bundle with the given assets, truncating to top-level asset paths if necessary.
References AssetPaths, and SetBundleAssetsTruncated().
Referenced by SetBundleAssetsTruncated().
ToDebugString()
FString FAssetBundleData::ToDebugString () const
References ToDebugString().
Referenced by ToDebugString().
UE_DEPRECATED() [1/4]
FAssetBundleData::UE_DEPRECATED (5. 1, "The contents of an asset bundle now use FTopLevelAssetPath instead of FSoftObjectPath.")
Adds or updates an entry with the given BundleName -> Path.
Scope is empty and will be filled in later
Referenced by UE_DEPRECATED(), and UE_DEPRECATED().
UE_DEPRECATED() [2/4]
FAssetBundleData::UE_DEPRECATED (5. 1, "The contents of an asset bundle now use FTopLevelAssetPath instead of FSoftObjectPath.")
Adds multiple assets at once.
UE_DEPRECATED() [3/4]
FAssetBundleData::UE_DEPRECATED (5. 1, "The contents of an asset bundle now use FTopLevelAssetPath instead of FSoftObjectPath.")
A fast set of asset bundle assets, will destroy copied in path list.
References UE_DEPRECATED().
UE_DEPRECATED() [4/4]
template<typename T> FAssetBundleData::UE_DEPRECATED (5. 1, "The contents of an asset bundle now use FTopLevelAssetPath instead of FSoftObjectPath.")
References UE_DEPRECATED().
Field Documentation
AssetPath
const FSoftObjectPath& FAssetBundleData::AssetPath
Definition at line 100 of file AssetBundleData.h.
Referenced by AddBundleAsset(), and AddBundleAssetTruncated().
AssetPaths [1/2]
const TArray<FSoftObjectPath>& FAssetBundleData::AssetPaths
Definition at line 111 of file AssetBundleData.h.
Referenced by AddBundleAssets(), AddBundleAssetsTruncated(), SetBundleAssets(), and SetBundleAssetsTruncated().
AssetPaths [2/2]
TArray<FSoftObjectPath>&& FAssetBundleData::AssetPaths
Definition at line 115 of file AssetBundleData.h.
Bundles
TArray<FAssetBundleEntry> FAssetBundleData::Bundles
List of bundles defined.
Definition at line 83 of file AssetBundleData.h.
Referenced by operator==().
SoftObjectPtr
const TSoftObjectPtr<T>& FAssetBundleData::SoftObjectPtr
Initial value:
{
        AddBundleAsset(BundleName, SoftObjectPtr.ToSoftObjectPath().GetAssetPath())
Definition at line 104 of file AssetBundleData.h.
The documentation for this struct was generated from the following file:
Runtime/CoreUObject/Public/AssetRegistry/AssetBundleData.h