Unreal Engine 5.6 C++ API: UE::MovieScene::TReinitializeBoundMaterials< AccessorType, RequiredComponents > Struct Template Reference
UE::MovieScene::TReinitializeBoundMaterials< AccessorType, RequiredComponents > Struct Template Reference
#include "MovieSceneMaterialSystem.h"
Public Member Functions
TReinitializeBoundMaterials (UMovieSceneEntitySystemLinker *InLinker)
void ForEachAllocation (int32 Num, const FMovieSceneEntityID *EntityIDs, const RequiredComponents *... Inputs, FObjectComponent *Objects)
void ForEachEntity (FMovieSceneEntityID EntityID, typename TCallTraits< RequiredComponents >::ParamType... Inputs, FObjectComponent &OutDynamicMaterial)
void PostTask ()
Data Fields
UMovieSceneEntitySystemLinker * Linker
TArray< FMovieSceneEntityID > ReboundMaterials
Detailed Description
template<typename AccessorType, typename... RequiredComponents>
struct UE::MovieScene::TReinitializeBoundMaterials< AccessorType, RequiredComponents >
Definition at line 276 of file MovieSceneMaterialSystem.h.
Constructor & Destructor Documentation
TReinitializeBoundMaterials()
template<typename AccessorType, typename... RequiredComponents> UE::MovieScene::TReinitializeBoundMaterials< AccessorType, RequiredComponents >::TReinitializeBoundMaterials (UMovieSceneEntitySystemLinker * InLinker) inline
Definition at line 281 of file MovieSceneMaterialSystem.h.
References Linker.
Member Function Documentation
ForEachAllocation()
template<typename AccessorType, typename... RequiredComponents> void UE::MovieScene::TReinitializeBoundMaterials< AccessorType, RequiredComponents >::ForEachAllocation (int32 Num, const FMovieSceneEntityID * EntityIDs, const RequiredComponents *... Inputs, FObjectComponent * Objects) inline
Definition at line 285 of file MovieSceneMaterialSystem.h.
References ForEachEntity(), and Num.
ForEachEntity()
template<typename AccessorType, typename... RequiredComponents> void UE::MovieScene::TReinitializeBoundMaterials< AccessorType, RequiredComponents >::ForEachEntity (FMovieSceneEntityID EntityID, typename TCallTraits< RequiredComponents >::ParamType... Inputs, FObjectComponent & OutDynamicMaterial) inline
Definition at line 293 of file MovieSceneMaterialSystem.h.
References UE::MovieScene::TInitializeBoundMaterials< AccessorType, RequiredComponents >::InitializeBoundMaterial(), and ReboundMaterials.
Referenced by ForEachAllocation().
PostTask()
template<typename AccessorType, typename... RequiredComponents> void UE::MovieScene::TReinitializeBoundMaterials< AccessorType, RequiredComponents >::PostTask () inline
Definition at line 301 of file MovieSceneMaterialSystem.h.
References UE::MovieScene::FMovieSceneTracksComponentTypes::BoundMaterialChanged, UE::MovieScene::FMovieSceneTracksComponentTypes::Get(), Linker, ReboundMaterials, and UE::MovieScene::FMovieSceneTracksComponentTypes::Tags.
Field Documentation
Linker
template<typename AccessorType, typename... RequiredComponents> UMovieSceneEntitySystemLinker* UE::MovieScene::TReinitializeBoundMaterials< AccessorType, RequiredComponents >::Linker
Definition at line 278 of file MovieSceneMaterialSystem.h.
Referenced by TReinitializeBoundMaterials(), and PostTask().
ReboundMaterials
template<typename AccessorType, typename... RequiredComponents> TArray<FMovieSceneEntityID> UE::MovieScene::TReinitializeBoundMaterials< AccessorType, RequiredComponents >::ReboundMaterials
Definition at line 279 of file MovieSceneMaterialSystem.h.
Referenced by ForEachEntity(), and PostTask().
The documentation for this struct was generated from the following file:
Runtime/MovieSceneTracks/Public/Systems/MovieSceneMaterialSystem.h