Unreal Engine 5.6 C++ API: FAndroidPlatformString Struct Reference
FAndroidPlatformString Struct Reference
Android string implementation.
#include "AndroidPlatformString.h"
Public Member Functions
UE_DEPRECATED (5.6, "Use Strncat instead. !!NOTE THAT STRNCAT takes SrcLen rather than DestCount. You must call Strncat(Dest, Src, DestCount - Strlen(Dest) - 1).") static FORCEINLINE ANSICHAR *Strcat(ANSICHAR *Dest
UE_DEPRECATED (5.6, "Use Strncat instead. !!NOTE THAT STRNCAT takes SrcLen rather than DestCount. You must call Strncat(Dest, Src, DestCount - Strlen(Dest) - 1).") static FORCEINLINE UTF8CHAR *Strcat(UTF8CHAR *Dest
UE_DEPRECATED (5.6, "Use Strncat instead. !!NOTE THAT STRNCAT takes SrcLen rather than DestCount. You must call Strncat(Dest, Src, DestCount - Strlen(Dest) - 1).") static FORCEINLINE WIDECHAR *Strcat(WIDECHAR *Dest
UE_DEPRECATED (5.6, "Use Strncpy instead. Note that Strncpy has a behavior difference from Strcpy: it memzeroes the entire DestCount-sized buffer after the end of string.") static FORCEINLINE ANSICHAR *Strcpy(ANSICHAR *Dest
UE_DEPRECATED (5.6, "Use Strncpy instead. Note that Strncpy has a behavior difference from Strcpy: it memzeroes the entire DestCount-sized buffer after the end of string.") static FORCEINLINE UTF8CHAR *Strcpy(UTF8CHAR *Dest
UE_DEPRECATED (5.6, "Use Strncpy instead. Note that Strncpy has a behavior difference from Strcpy: it memzeroes the entire DestCount-sized buffer after the end of string.") static FORCEINLINE WIDECHAR *Strcpy(WIDECHAR *Dest
Static Public Member Functions
static FORCEINLINE double Atod (const ANSICHAR *String)
static FORCEINLINE double Atod (const UTF8CHAR *String)
static FORCEINLINE double Atod (const WIDECHAR *String)
static FORCEINLINE float Atof (const ANSICHAR *String)
static FORCEINLINE float Atof (const UTF8CHAR *String)
static FORCEINLINE float Atof (const WIDECHAR *String)
static FORCEINLINE int32 Atoi (const ANSICHAR *String)
static FORCEINLINE int32 Atoi (const UTF8CHAR *String)
static FORCEINLINE int32 Atoi (const WIDECHAR *String)
static FORCEINLINE int64 Atoi64 (const ANSICHAR *String)
static FORCEINLINE int64 Atoi64 (const UTF8CHAR *String)
static FORCEINLINE int64 Atoi64 (const WIDECHAR *String)
static FORCEINLINE void CopyAnsiToWide (WIDECHAR *Dest, const ANSICHAR *Src)
static FORCEINLINE void CopyWideToAnsi (ANSICHAR *Dest, const WIDECHAR *Src)
static FORCEINLINE int32 GetVarArgs (ANSICHAR *Dest, SIZE_T DestSize, const ANSICHAR *&Fmt, va_list ArgPtr)
static FORCEINLINE int32 GetVarArgs (UTF8CHAR *Dest, SIZE_T DestSize, const UTF8CHAR *&Fmt, va_list ArgPtr)
static FORCEINLINE int32 GetVarArgs (WIDECHAR *Dest, SIZE_T DestSize, const WIDECHAR *&Fmt, va_list ArgPtr)
static FORCEINLINE ANSICHAR * Strcat (ANSICHAR *Dest, const ANSICHAR *Src)
static FORCEINLINE UTF8CHAR * Strcat (UTF8CHAR *Dest, const UTF8CHAR *Src)
static FORCEINLINE WIDECHAR * Strcat (WIDECHAR *Dest, const WIDECHAR *Src)
static FORCEINLINE const ANSICHAR * Strchr (const ANSICHAR *String, ANSICHAR C)
static FORCEINLINE const UTF8CHAR * Strchr (const UTF8CHAR *String, UTF8CHAR C)
static FORCEINLINE const WIDECHAR * Strchr (const WIDECHAR *String, WIDECHAR C)
static FORCEINLINE int32 Strcmp (const ANSICHAR *String1, const ANSICHAR *String2)
static FORCEINLINE int32 Strcmp (const UTF8CHAR *String1, const UTF8CHAR *String2)
static FORCEINLINE int32 Strcmp (const WIDECHAR *String1, const WIDECHAR *String2)
static FORCEINLINE ANSICHAR * Strcpy (ANSICHAR *Dest, const ANSICHAR *Src)
Ansi implementation.
static FORCEINLINE UTF8CHAR * Strcpy (UTF8CHAR *Dest, const UTF8CHAR *Src)
UTF8CHAR implementation.
static FORCEINLINE WIDECHAR * Strcpy (WIDECHAR *Dest, const WIDECHAR *Src)
Widechar implementation.
static FORCEINLINE int32 Strlen (const ANSICHAR *String)
static FORCEINLINE int32 Strlen (const UCS2CHAR *String)
UCS2 implementation.
static FORCEINLINE int32 Strlen (const UTF8CHAR *String)
static FORCEINLINE int32 Strlen (const WIDECHAR *String)
static FORCEINLINE ANSICHAR * Strncat (ANSICHAR *Dest, const ANSICHAR *Src, SIZE_T SrcLen)
static PRAGMA_ENABLE_DEPRECATION_WARNINGS FORCEINLINE UTF8CHAR * Strncat (UTF8CHAR *Dest, const UTF8CHAR *Src, SIZE_T SrcLen)
static FORCEINLINE WIDECHAR * Strncat (WIDECHAR *Dest, const WIDECHAR *Src, SIZE_T SrcLen)
static FORCEINLINE int32 Strncmp (const ANSICHAR *String1, const ANSICHAR *String2, SIZE_T Count)
static int32 Strncmp (const ANSICHAR *String1, const UTF8CHAR *String2, SIZE_T Count)
static int32 Strncmp (const ANSICHAR *String1, const WIDECHAR *String2, SIZE_T Count)
static int32 Strncmp (const UTF8CHAR *String1, const ANSICHAR *String2, SIZE_T Count)
static FORCEINLINE int32 Strncmp (const UTF8CHAR *String1, const UTF8CHAR *String2, SIZE_T Count)
static int32 Strncmp (const UTF8CHAR *String1, const WIDECHAR *String2, SIZE_T Count)
static int32 Strncmp (const WIDECHAR *String1, const ANSICHAR *String2, SIZE_T Count)
static int32 Strncmp (const WIDECHAR *String1, const UTF8CHAR *String2, SIZE_T Count)
static int32 Strncmp (const WIDECHAR *String1, const WIDECHAR *String2, SIZE_T Count)
static FORCEINLINE ANSICHAR * Strncpy (ANSICHAR *Dest, const ANSICHAR *Src, SIZE_T MaxLen)
static PRAGMA_ENABLE_DEPRECATION_WARNINGS FORCEINLINE UTF8CHAR * Strncpy (UTF8CHAR *Dest, const UTF8CHAR *Src, SIZE_T MaxLen)
static FORCEINLINE WIDECHAR * Strncpy (WIDECHAR *Dest, const WIDECHAR *Src, SIZE_T MaxLen)
static FORCEINLINE int32 Strnlen (const ANSICHAR *String, SIZE_T StringSize)
static FORCEINLINE int32 Strnlen (const UCS2CHAR *String, SIZE_T StringSize)
static FORCEINLINE int32 Strnlen (const UTF8CHAR *String, SIZE_T StringSize)
static FORCEINLINE int32 Strnlen (const WIDECHAR *String, SIZE_T StringSize)
static FORCEINLINE const ANSICHAR * Strrchr (const ANSICHAR *String, ANSICHAR C)
static FORCEINLINE const UTF8CHAR * Strrchr (const UTF8CHAR *String, UTF8CHAR C)
static FORCEINLINE const WIDECHAR * Strrchr (const WIDECHAR *String, WIDECHAR C)
static FORCEINLINE const ANSICHAR * Strstr (const ANSICHAR *String, const ANSICHAR *Find)
static FORCEINLINE const UTF8CHAR * Strstr (const UTF8CHAR *String, const UTF8CHAR *Find)
static FORCEINLINE const WIDECHAR * Strstr (const WIDECHAR *String, const WIDECHAR *Find)
static FORCEINLINE int32 Strtoi (const ANSICHAR *Start, ANSICHAR **End, int32 Base)
static FORCEINLINE int32 Strtoi (const UTF8CHAR *Start, UTF8CHAR **End, int32 Base)
static FORCEINLINE int32 Strtoi (const WIDECHAR *Start, WIDECHAR **End, int32 Base)
static FORCEINLINE int64 Strtoi64 (const ANSICHAR *Start, ANSICHAR **End, int32 Base)
static FORCEINLINE int64 Strtoi64 (const UTF8CHAR *Start, UTF8CHAR **End, int32 Base)
static FORCEINLINE int64 Strtoi64 (const WIDECHAR *Start, WIDECHAR **End, int32 Base)
static FORCEINLINE ANSICHAR * Strtok (ANSICHAR *StrToken, const ANSICHAR *Delim, ANSICHAR **Context)
static FORCEINLINE UTF8CHAR * Strtok (UTF8CHAR *StrToken, const UTF8CHAR *Delim, UTF8CHAR **Context)
static FORCEINLINE WIDECHAR * Strtok (WIDECHAR *StrToken, const WIDECHAR *Delim, WIDECHAR **Context)
static FORCEINLINE uint64 Strtoui64 (const ANSICHAR *Start, ANSICHAR **End, int32 Base)
static FORCEINLINE uint64 Strtoui64 (const UTF8CHAR *Start, UTF8CHAR **End, int32 Base)
static FORCEINLINE uint64 Strtoui64 (const WIDECHAR *Start, WIDECHAR **End, int32 Base)
template<typename CharType>
static CharType * Strupr (CharType *Dest, SIZE_T DestCount)
Static Public Member Functions inherited from FGenericPlatformString
template<typename DestEncoding, typename SourceEncoding>
static constexpr bool CanConvertCodepoint (SourceEncoding Codepoint)
Tests whether a particular codepoint can be converted to the destination encoding.
template<typename SourceEncoding, typename DestEncoding>
static FORCEINLINE DestEncoding * Convert (DestEncoding *Dest, int32 DestSize, const SourceEncoding *Src)
Converts the null-terminated Src string range from SourceEncoding to DestEncoding and writes it to the [Dest, Dest+DestSize) range, including a null terminator.
template<typename SourceEncoding, typename DestEncoding>
static FORCEINLINE DestEncoding * Convert (DestEncoding *Dest, int32 DestSize, const SourceEncoding *Src, int32 SrcSize)
Converts the [Src, Src+SrcSize) string range from SourceEncoding to DestEncoding and writes it to the [Dest, Dest+DestSize) range.
template<typename DestEncoding, typename SourceEncoding>
static int32 ConvertedLength (const SourceEncoding *Src)
Returns the required buffer length for the null-terminated Src string when converted to the DestChar encoding.
template<typename DestEncoding, typename SourceEncoding>
static int32 ConvertedLength (const SourceEncoding *Src, int32 SrcSize)
Returns the required buffer length for the [Src, Src+SrcSize) string when converted to the DestChar encoding.
static const ANSICHAR * GetEncodingName ()
template<typename Encoding>
static const TCHAR * GetEncodingTypeName ()
Returns the string representing the name of the given encoding type.
static int32 Strncmp (const ANSICHAR *String1, const ANSICHAR *String2, SIZE_T Count)
static int32 Strncmp (const ANSICHAR *String1, const UTF8CHAR *String2, SIZE_T Count)
static int32 Strncmp (const ANSICHAR *String1, const WIDECHAR *String2, SIZE_T Count)
static int32 Strncmp (const UTF8CHAR *String1, const ANSICHAR *String2, SIZE_T Count)
static int32 Strncmp (const UTF8CHAR *String1, const UTF8CHAR *String2, SIZE_T Count)
static int32 Strncmp (const UTF8CHAR *String1, const WIDECHAR *String2, SIZE_T Count)
static int32 Strncmp (const WIDECHAR *String1, const ANSICHAR *String2, SIZE_T Count)
static int32 Strncmp (const WIDECHAR *String1, const UTF8CHAR *String2, SIZE_T Count)
static int32 Strncmp (const WIDECHAR *String1, const WIDECHAR *String2, SIZE_T Count)
Static Public Member Functions inherited from FGenericPlatformStricmp
static int32 Stricmp (const ANSICHAR *String1, const ANSICHAR *String2)
static int32 Stricmp (const ANSICHAR *String1, const UTF16CHAR *String2)
static int32 Stricmp (const ANSICHAR *String1, const UTF32CHAR *String2)
static int32 Stricmp (const ANSICHAR *String1, const UTF8CHAR *String2)
static int32 Stricmp (const ANSICHAR *String1, const WIDECHAR *String2)
static int32 Stricmp (const UTF16CHAR *String1, const ANSICHAR *String2)
static int32 Stricmp (const UTF16CHAR *String1, const UTF16CHAR *String2)
static int32 Stricmp (const UTF32CHAR *String1, const ANSICHAR *String2)
static int32 Stricmp (const UTF32CHAR *String1, const UTF32CHAR *String2)
static int32 Stricmp (const UTF8CHAR *String1, const ANSICHAR *String2)
static int32 Stricmp (const UTF8CHAR *String1, const UTF8CHAR *String2)
static int32 Stricmp (const WIDECHAR *String1, const ANSICHAR *String2)
static int32 Stricmp (const WIDECHAR *String1, const WIDECHAR *String2)
static int32 Strnicmp (const ANSICHAR *String1, const ANSICHAR *String2, SIZE_T Count)
static int32 Strnicmp (const ANSICHAR *String1, const UTF16CHAR *String2, SIZE_T Count)
static int32 Strnicmp (const ANSICHAR *String1, const UTF32CHAR *String2, SIZE_T Count)
static int32 Strnicmp (const ANSICHAR *String1, const UTF8CHAR *String2, SIZE_T Count)
static int32 Strnicmp (const ANSICHAR *String1, const WIDECHAR *String2, SIZE_T Count)
static int32 Strnicmp (const UTF16CHAR *String1, const ANSICHAR *String2, SIZE_T Count)
static int32 Strnicmp (const UTF16CHAR *String1, const UTF16CHAR *String2, SIZE_T Count)
static int32 Strnicmp (const UTF32CHAR *String1, const ANSICHAR *String2, SIZE_T Count)
static int32 Strnicmp (const UTF32CHAR *String1, const UTF32CHAR *String2, SIZE_T Count)
static int32 Strnicmp (const UTF8CHAR *String1, const ANSICHAR *String2, SIZE_T Count)
static int32 Strnicmp (const UTF8CHAR *String1, const UTF8CHAR *String2, SIZE_T Count)
static int32 Strnicmp (const WIDECHAR *String1, const ANSICHAR *String2, SIZE_T Count)
static int32 Strnicmp (const WIDECHAR *String1, const WIDECHAR *String2, SIZE_T Count)
Data Fields
SIZE_T DestCount
SIZE_T const WIDECHAR * Src
SIZE_T const ANSICHAR * Src
SIZE_T const UTF8CHAR * Src
Additional Inherited Members
Static Public Attributes inherited from FGenericPlatformString
static constexpr bool IsUnicodeEncoded = true
True if the encoding type of the string is some form of unicode.
Detailed Description
Android string implementation.
Definition at line 39 of file AndroidPlatformString.h.
Member Function Documentation
Atod() [1/3]
FORCEINLINE double FAndroidPlatformString::Atod (const ANSICHAR * String) inline static
Definition at line 594 of file AndroidPlatformString.h.
References FORCEINLINE, and String.
Atod() [2/3]
FORCEINLINE double FAndroidPlatformString::Atod (const UTF8CHAR * String) inline static
Definition at line 716 of file AndroidPlatformString.h.
References Atod(), FORCEINLINE, and String.
Atod() [3/3]
FORCEINLINE double FAndroidPlatformString::Atod (const WIDECHAR * String) inline static
Definition at line 343 of file AndroidPlatformString.h.
References CopyWideToAnsi(), FMemory_Alloca, FORCEINLINE, String, and Strlen().
Referenced by Atod(), and TCString< T >::Atod().
Atof() [1/3]
FORCEINLINE float FAndroidPlatformString::Atof (const ANSICHAR * String) inline static
Definition at line 589 of file AndroidPlatformString.h.
References FORCEINLINE, and String.
Atof() [2/3]
FORCEINLINE float FAndroidPlatformString::Atof (const UTF8CHAR * String) inline static
Definition at line 711 of file AndroidPlatformString.h.
References Atof(), FORCEINLINE, and String.
Atof() [3/3]
FORCEINLINE float FAndroidPlatformString::Atof (const WIDECHAR * String) inline static
Definition at line 334 of file AndroidPlatformString.h.
References CopyWideToAnsi(), FMemory_Alloca, FORCEINLINE, String, and Strlen().
Referenced by Atof(), and TCString< T >::Atof().
Atoi() [1/3]
FORCEINLINE int32 FAndroidPlatformString::Atoi (const ANSICHAR * String) inline static
Definition at line 579 of file AndroidPlatformString.h.
References FORCEINLINE, and String.
Atoi() [2/3]
FORCEINLINE int32 FAndroidPlatformString::Atoi (const UTF8CHAR * String) inline static
Definition at line 701 of file AndroidPlatformString.h.
References Atoi(), FORCEINLINE, and String.
Atoi() [3/3]
FORCEINLINE int32 FAndroidPlatformString::Atoi (const WIDECHAR * String) inline static
Definition at line 316 of file AndroidPlatformString.h.
References CopyWideToAnsi(), FMemory_Alloca, FORCEINLINE, String, and Strlen().
Referenced by Atoi(), and TCString< T >::Atoi().
Atoi64() [1/3]
FORCEINLINE int64 FAndroidPlatformString::Atoi64 (const ANSICHAR * String) inline static
Definition at line 584 of file AndroidPlatformString.h.
References FORCEINLINE, and String.
Atoi64() [2/3]
FORCEINLINE int64 FAndroidPlatformString::Atoi64 (const UTF8CHAR * String) inline static
Definition at line 706 of file AndroidPlatformString.h.
References Atoi64(), FORCEINLINE, and String.
Atoi64() [3/3]
FORCEINLINE int64 FAndroidPlatformString::Atoi64 (const WIDECHAR * String) inline static
Definition at line 325 of file AndroidPlatformString.h.
References CopyWideToAnsi(), FMemory_Alloca, FORCEINLINE, String, and Strlen().
Referenced by Atoi64(), and TCString< T >::Atoi64().
CopyAnsiToWide()
FORCEINLINE void FAndroidPlatformString::CopyAnsiToWide (WIDECHAR * Dest, const ANSICHAR * Src) inline static
Definition at line 216 of file AndroidPlatformString.h.
References FORCEINLINE, and Src.
CopyWideToAnsi()
FORCEINLINE void FAndroidPlatformString::CopyWideToAnsi (ANSICHAR * Dest, const WIDECHAR * Src) inline static
Definition at line 193 of file AndroidPlatformString.h.
References FORCEINLINE, and Src.
Referenced by Atod(), Atof(), Atoi(), Atoi64(), Strtoi(), Strtoi64(), Strtok(), and Strtoui64().
GetVarArgs() [1/3]
FORCEINLINE int32 FAndroidPlatformString::GetVarArgs (ANSICHAR * Dest, SIZE_T DestSize, const ANSICHAR *& Fmt, va_list ArgPtr) inline static
Definition at line 619 of file AndroidPlatformString.h.
References FORCEINLINE.
GetVarArgs() [2/3]
FORCEINLINE int32 FAndroidPlatformString::GetVarArgs (UTF8CHAR * Dest, SIZE_T DestSize, const UTF8CHAR *& Fmt, va_list ArgPtr) inline static
Definition at line 741 of file AndroidPlatformString.h.
References FORCEINLINE, and GetVarArgs().
GetVarArgs() [3/3]
FORCEINLINE int32 FAndroidPlatformString::GetVarArgs (WIDECHAR * Dest, SIZE_T DestSize, const WIDECHAR *& Fmt, va_list ArgPtr) inline static
Definition at line 446 of file AndroidPlatformString.h.
References FMemory_Alloca, FORCEINLINE, TChar< TCHAR >::IsAlpha(), LITERAL, Strlen(), and vswprintf().
Referenced by GetVarArgs(), and TCString< T >::GetVarArgs().
Strcat() [1/3]
FORCEINLINE ANSICHAR * FAndroidPlatformString::Strcat (ANSICHAR * Dest, const ANSICHAR * Src) inline static
Definition at line 527 of file AndroidPlatformString.h.
References FORCEINLINE, and Src.
Strcat() [2/3]
FORCEINLINE UTF8CHAR * FAndroidPlatformString::Strcat (UTF8CHAR * Dest, const UTF8CHAR * Src) inline static
Definition at line 647 of file AndroidPlatformString.h.
References FORCEINLINE, Src, and Strcat().
Strcat() [3/3]
FORCEINLINE WIDECHAR * FAndroidPlatformString::Strcat (WIDECHAR * Dest, const WIDECHAR * Src) inline static
Definition at line 109 of file AndroidPlatformString.h.
References FORCEINLINE, Src, and Strlen().
Referenced by Strcat(), TCString< T >::Strcat(), TCString< TCHAR >::Strcat(), UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
Strchr() [1/3]
FORCEINLINE const ANSICHAR * FAndroidPlatformString::Strchr (const ANSICHAR * String, ANSICHAR C) inline static
Definition at line 569 of file AndroidPlatformString.h.
References FORCEINLINE, and String.
Strchr() [2/3]
FORCEINLINE const UTF8CHAR * FAndroidPlatformString::Strchr (const UTF8CHAR * String, UTF8CHAR C) inline static
Definition at line 691 of file AndroidPlatformString.h.
References FORCEINLINE, Strchr(), and String.
Strchr() [3/3]
FORCEINLINE const WIDECHAR * FAndroidPlatformString::Strchr (const WIDECHAR * String, WIDECHAR C) inline static
Definition at line 266 of file AndroidPlatformString.h.
References FORCEINLINE, and String.
Referenced by Strchr(), TCString< T >::Strchr(), and TCString< T >::Strchr().
Strcmp() [1/3]
FORCEINLINE int32 FAndroidPlatformString::Strcmp (const ANSICHAR * String1, const ANSICHAR * String2) inline static
Definition at line 544 of file AndroidPlatformString.h.
References FORCEINLINE.
Strcmp() [2/3]
FORCEINLINE int32 FAndroidPlatformString::Strcmp (const UTF8CHAR * String1, const UTF8CHAR * String2) inline static
Definition at line 666 of file AndroidPlatformString.h.
References FORCEINLINE, and Strcmp().
Strcmp() [3/3]
FORCEINLINE int32 FAndroidPlatformString::Strcmp (const WIDECHAR * String1, const WIDECHAR * String2) inline static
Definition at line 157 of file AndroidPlatformString.h.
References FORCEINLINE.
Referenced by Strcmp(), and TCString< T >::Strcmp().
Strcpy() [1/3]
FORCEINLINE ANSICHAR * FAndroidPlatformString::Strcpy (ANSICHAR * Dest, const ANSICHAR * Src) inline static
Ansi implementation.
Definition at line 507 of file AndroidPlatformString.h.
References FORCEINLINE, and Src.
Strcpy() [2/3]
FORCEINLINE UTF8CHAR * FAndroidPlatformString::Strcpy (UTF8CHAR * Dest, const UTF8CHAR * Src) inline static
UTF8CHAR implementation.
Definition at line 628 of file AndroidPlatformString.h.
References FORCEINLINE, Src, and Strcpy().
Strcpy() [3/3]
FORCEINLINE WIDECHAR * FAndroidPlatformString::Strcpy (WIDECHAR * Dest, const WIDECHAR * Src) inline static
Widechar implementation.
Definition at line 58 of file AndroidPlatformString.h.
References FORCEINLINE, and Src.
Referenced by Strcpy(), TCString< T >::Strcpy(), and TCString< TCHAR >::Strcpy().
Strlen() [1/4]
FORCEINLINE int32 FAndroidPlatformString::Strlen (const ANSICHAR * String) inline static
Definition at line 554 of file AndroidPlatformString.h.
References FORCEINLINE, and String.
Strlen() [2/4]
FORCEINLINE int32 FAndroidPlatformString::Strlen (const UCS2CHAR * String) inline static
UCS2 implementation.
Definition at line 750 of file AndroidPlatformString.h.
References FORCEINLINE, and String.
Strlen() [3/4]
FORCEINLINE int32 FAndroidPlatformString::Strlen (const UTF8CHAR * String) inline static
Definition at line 676 of file AndroidPlatformString.h.
References FORCEINLINE, String, and Strlen().
Strlen() [4/4]
FORCEINLINE int32 FAndroidPlatformString::Strlen (const WIDECHAR * String) inline static
Definition at line 169 of file AndroidPlatformString.h.
References FORCEINLINE, and String.
Referenced by Atod(), Atof(), Atoi(), Atoi64(), GetVarArgs(), Strcat(), FCrc::Strihash_DEPRECATED(), Strlen(), TCString< T >::Strlen(), Strncat(), Strtoi(), Strtoi64(), Strtok(), and Strtoui64().
Strncat() [1/3]
FORCEINLINE ANSICHAR * FAndroidPlatformString::Strncat (ANSICHAR * Dest, const ANSICHAR * Src, SIZE_T SrcLen) inline static
Definition at line 539 of file AndroidPlatformString.h.
References FORCEINLINE, and Src.
Strncat() [2/3]
PRAGMA_ENABLE_DEPRECATION_WARNINGS FORCEINLINE UTF8CHAR * FAndroidPlatformString::Strncat (UTF8CHAR * Dest, const UTF8CHAR * Src, SIZE_T SrcLen) inline static
Definition at line 661 of file AndroidPlatformString.h.
References FORCEINLINE, Src, and Strncat().
Strncat() [3/3]
FORCEINLINE WIDECHAR * FAndroidPlatformString::Strncat (WIDECHAR * Dest, const WIDECHAR * Src, SIZE_T SrcLen) inline static
Definition at line 136 of file AndroidPlatformString.h.
References FORCEINLINE, Src, and Strlen().
Referenced by Strncat().
Strncmp() [1/9]
FORCEINLINE int32 FAndroidPlatformString::Strncmp (const ANSICHAR * String1, const ANSICHAR * String2, SIZE_T Count) inline static
Definition at line 549 of file AndroidPlatformString.h.
References Count, and FORCEINLINE.
Referenced by TStringView< CharType >::Compare(), TStringView< CharType >::PrivateCompare(), TStringView< CharType >::PrivateEquals(), Strncmp(), and TCString< T >::Strncmp().
Strncmp() [2/9]
int32 FGenericPlatformString::Strncmp (const ANSICHAR * String1, const UTF8CHAR * String2, SIZE_T Count) static
Strncmp() [3/9]
int32 FGenericPlatformString::Strncmp (const ANSICHAR * String1, const WIDECHAR * String2, SIZE_T Count) static
Strncmp() [4/9]
int32 FGenericPlatformString::Strncmp (const UTF8CHAR * String1, const ANSICHAR * String2, SIZE_T Count) static
Strncmp() [5/9]
FORCEINLINE int32 FAndroidPlatformString::Strncmp (const UTF8CHAR * String1, const UTF8CHAR * String2, SIZE_T Count) inline static
Definition at line 671 of file AndroidPlatformString.h.
References Count, FORCEINLINE, and Strncmp().
Strncmp() [6/9]
int32 FGenericPlatformString::Strncmp (const UTF8CHAR * String1, const WIDECHAR * String2, SIZE_T Count) static
Strncmp() [7/9]
int32 FGenericPlatformString::Strncmp (const WIDECHAR * String1, const ANSICHAR * String2, SIZE_T Count) static
Strncmp() [8/9]
int32 FGenericPlatformString::Strncmp (const WIDECHAR * String1, const UTF8CHAR * String2, SIZE_T Count) static
Strncmp() [9/9]
int32 FGenericPlatformString::Strncmp (const WIDECHAR * String1, const WIDECHAR * String2, SIZE_T Count) static
Strncpy() [1/3]
FORCEINLINE ANSICHAR * FAndroidPlatformString::Strncpy (ANSICHAR * Dest, const ANSICHAR * Src, SIZE_T MaxLen) inline static
Definition at line 520 of file AndroidPlatformString.h.
References FORCEINLINE, and Src.
Strncpy() [2/3]
PRAGMA_ENABLE_DEPRECATION_WARNINGS FORCEINLINE UTF8CHAR * FAndroidPlatformString::Strncpy (UTF8CHAR * Dest, const UTF8CHAR * Src, SIZE_T MaxLen) inline static
Definition at line 642 of file AndroidPlatformString.h.
References FORCEINLINE, Src, and Strncpy().
Strncpy() [3/3]
FORCEINLINE WIDECHAR * FAndroidPlatformString::Strncpy (WIDECHAR * Dest, const WIDECHAR * Src, SIZE_T MaxLen) inline static
Definition at line 85 of file AndroidPlatformString.h.
References FORCEINLINE, and Src.
Referenced by Strncpy(), and TCString< T >::Strncpy().
Strnlen() [1/4]
FORCEINLINE int32 FAndroidPlatformString::Strnlen (const ANSICHAR * String, SIZE_T StringSize) inline static
Definition at line 559 of file AndroidPlatformString.h.
References FORCEINLINE, String, and StringSize().
Strnlen() [2/4]
FORCEINLINE int32 FAndroidPlatformString::Strnlen (const UCS2CHAR * String, SIZE_T StringSize) inline static
Definition at line 761 of file AndroidPlatformString.h.
References FORCEINLINE, String, and StringSize().
Strnlen() [3/4]
FORCEINLINE int32 FAndroidPlatformString::Strnlen (const UTF8CHAR * String, SIZE_T StringSize) inline static
Definition at line 681 of file AndroidPlatformString.h.
References FORCEINLINE, String, StringSize(), and Strnlen().
Strnlen() [4/4]
FORCEINLINE int32 FAndroidPlatformString::Strnlen (const WIDECHAR * String, SIZE_T StringSize) inline static
Definition at line 183 of file AndroidPlatformString.h.
References FORCEINLINE, String, and StringSize().
Referenced by Strnlen(), and TCString< T >::Strnlen().
Strrchr() [1/3]
FORCEINLINE const ANSICHAR * FAndroidPlatformString::Strrchr (const ANSICHAR * String, ANSICHAR C) inline static
Definition at line 574 of file AndroidPlatformString.h.
References FORCEINLINE, and String.
Strrchr() [2/3]
FORCEINLINE const UTF8CHAR * FAndroidPlatformString::Strrchr (const UTF8CHAR * String, UTF8CHAR C) inline static
Definition at line 696 of file AndroidPlatformString.h.
References FORCEINLINE, String, and Strrchr().
Strrchr() [3/3]
FORCEINLINE const WIDECHAR * FAndroidPlatformString::Strrchr (const WIDECHAR * String, WIDECHAR C) inline static
Definition at line 290 of file AndroidPlatformString.h.
References FORCEINLINE, Last, and String.
Referenced by Strrchr(), TCString< T >::Strrchr(), and TCString< T >::Strrchr().
Strstr() [1/3]
FORCEINLINE const ANSICHAR * FAndroidPlatformString::Strstr (const ANSICHAR * String, const ANSICHAR * Find) inline static
Definition at line 564 of file AndroidPlatformString.h.
References Find, FORCEINLINE, and String.
Strstr() [2/3]
FORCEINLINE const UTF8CHAR * FAndroidPlatformString::Strstr (const UTF8CHAR * String, const UTF8CHAR * Find) inline static
Definition at line 686 of file AndroidPlatformString.h.
References Find, FORCEINLINE, String, and Strstr().
Strstr() [3/3]
FORCEINLINE const WIDECHAR * FAndroidPlatformString::Strstr (const WIDECHAR * String, const WIDECHAR * Find) inline static
Definition at line 231 of file AndroidPlatformString.h.
References Find, FORCEINLINE, and String.
Referenced by Strstr(), TCString< T >::Strstr(), and TCString< T >::Strstr().
Strtoi() [1/3]
FORCEINLINE int32 FAndroidPlatformString::Strtoi (const ANSICHAR * Start, ANSICHAR ** End, int32 Base) inline static
Definition at line 599 of file AndroidPlatformString.h.
References End, and FORCEINLINE.
Strtoi() [2/3]
FORCEINLINE int32 FAndroidPlatformString::Strtoi (const UTF8CHAR * Start, UTF8CHAR ** End, int32 Base) inline static
Definition at line 721 of file AndroidPlatformString.h.
References End, FORCEINLINE, and Strtoi().
Strtoi() [3/3]
FORCEINLINE int32 FAndroidPlatformString::Strtoi (const WIDECHAR * Start, WIDECHAR ** End, int32 Base) inline static
Definition at line 352 of file AndroidPlatformString.h.
References CopyWideToAnsi(), End, FMemory_Alloca, FORCEINLINE, and Strlen().
Referenced by Strtoi(), and TCString< T >::Strtoi().
Strtoi64() [1/3]
FORCEINLINE int64 FAndroidPlatformString::Strtoi64 (const ANSICHAR * Start, ANSICHAR ** End, int32 Base) inline static
Definition at line 604 of file AndroidPlatformString.h.
References End, and FORCEINLINE.
Strtoi64() [2/3]
FORCEINLINE int64 FAndroidPlatformString::Strtoi64 (const UTF8CHAR * Start, UTF8CHAR ** End, int32 Base) inline static
Definition at line 726 of file AndroidPlatformString.h.
References End, FORCEINLINE, and Strtoi64().
Strtoi64() [3/3]
FORCEINLINE int64 FAndroidPlatformString::Strtoi64 (const WIDECHAR * Start, WIDECHAR ** End, int32 Base) inline static
Definition at line 377 of file AndroidPlatformString.h.
References CopyWideToAnsi(), End, FMemory_Alloca, FORCEINLINE, and Strlen().
Referenced by Strtoi64(), and TCString< T >::Strtoi64().
Strtok() [1/3]
FORCEINLINE ANSICHAR * FAndroidPlatformString::Strtok (ANSICHAR * StrToken, const ANSICHAR * Delim, ANSICHAR ** Context) inline static
Definition at line 614 of file AndroidPlatformString.h.
References FORCEINLINE.
Strtok() [2/3]
FORCEINLINE UTF8CHAR * FAndroidPlatformString::Strtok (UTF8CHAR * StrToken, const UTF8CHAR * Delim, UTF8CHAR ** Context) inline static
Definition at line 736 of file AndroidPlatformString.h.
References FORCEINLINE, and Strtok().
Strtok() [3/3]
FORCEINLINE WIDECHAR * FAndroidPlatformString::Strtok (WIDECHAR * StrToken, const WIDECHAR * Delim, WIDECHAR ** Context) inline static
Definition at line 427 of file AndroidPlatformString.h.
References CopyWideToAnsi(), FMemory_Alloca, FORCEINLINE, and Strlen().
Referenced by Strtok(), and TCString< T >::Strtok().
Strtoui64() [1/3]
FORCEINLINE uint64 FAndroidPlatformString::Strtoui64 (const ANSICHAR * Start, ANSICHAR ** End, int32 Base) inline static
Definition at line 609 of file AndroidPlatformString.h.
References End, and FORCEINLINE.
Strtoui64() [2/3]
FORCEINLINE uint64 FAndroidPlatformString::Strtoui64 (const UTF8CHAR * Start, UTF8CHAR ** End, int32 Base) inline static
Definition at line 731 of file AndroidPlatformString.h.
References End, FORCEINLINE, and Strtoui64().
Strtoui64() [3/3]
FORCEINLINE uint64 FAndroidPlatformString::Strtoui64 (const WIDECHAR * Start, WIDECHAR ** End, int32 Base) inline static
Definition at line 402 of file AndroidPlatformString.h.
References CopyWideToAnsi(), End, FMemory_Alloca, FORCEINLINE, and Strlen().
Referenced by Strtoui64(), and TCString< T >::Strtoui64().
Strupr()
template<typename CharType> CharType * FAndroidPlatformString::Strupr (CharType * Dest, SIZE_T DestCount) inline static
Definition at line 46 of file AndroidPlatformString.h.
References DestCount, and TChar< CharType >::ToUpper().
Referenced by TCString< T >::Strupr().
UE_DEPRECATED() [1/6]
FAndroidPlatformString::UE_DEPRECATED (5. 6, "Use Strncat instead. !!NOTE THAT STRNCAT takes SrcLen rather than DestCount. You must call Strncat(Dest, Src, DestCount - Strlen(Dest) - 1).")
References DestCount, FORCEINLINE, Src, and Strcat().
UE_DEPRECATED() [2/6]
FAndroidPlatformString::UE_DEPRECATED (5. 6, "Use Strncat instead. !!NOTE THAT STRNCAT takes SrcLen rather than DestCount. You must call Strncat(Dest, Src, DestCount - Strlen(Dest) - 1).")
References DestCount, FORCEINLINE, PRAGMA_DISABLE_DEPRECATION_WARNINGS, PRAGMA_ENABLE_DEPRECATION_WARNINGS, Src, and Strcat().
UE_DEPRECATED() [3/6]
FAndroidPlatformString::UE_DEPRECATED (5. 6, "Use Strncat instead. !!NOTE THAT STRNCAT takes SrcLen rather than DestCount. You must call Strncat(Dest, Src, DestCount - Strlen(Dest) - 1).")
References DestCount, FORCEINLINE, Src, and Strcat().
UE_DEPRECATED() [4/6]
FAndroidPlatformString::UE_DEPRECATED (5. 6, "Use Strncpy instead. Note that Strncpy has a behavior difference from Strcpy: it memzeroes the entire DestCount-sized buffer after the end of string.")
UE_DEPRECATED() [5/6]
FAndroidPlatformString::UE_DEPRECATED (5. 6, "Use Strncpy instead. Note that Strncpy has a behavior difference from Strcpy: it memzeroes the entire DestCount-sized buffer after the end of string.")
UE_DEPRECATED() [6/6]
FAndroidPlatformString::UE_DEPRECATED (5. 6, "Use Strncpy instead. Note that Strncpy has a behavior difference from Strcpy: it memzeroes the entire DestCount-sized buffer after the end of string.")
Field Documentation
DestCount
SIZE_T FAndroidPlatformString::DestCount
Definition at line 80 of file AndroidPlatformString.h.
Referenced by Strupr(), UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
Src [1/3]
SIZE_T const UTF8CHAR * FAndroidPlatformString::Src
Initial value:
{
        return Strcpy(Dest, Src)
Definition at line 80 of file AndroidPlatformString.h.
Referenced by CopyAnsiToWide(), CopyWideToAnsi(), Strcat(), Strcat(), Strcat(), Strcpy(), Strcpy(), Strcpy(), Strncat(), Strncat(), Strncat(), Strncpy(), Strncpy(), Strncpy(), UE_DEPRECATED(), UE_DEPRECATED(), and UE_DEPRECATED().
Src [2/3]
SIZE_T const ANSICHAR* FAndroidPlatformString::Src
Initial value:
{
        return Strcpy(Dest, Src)
Definition at line 515 of file AndroidPlatformString.h.
Src [3/3]
SIZE_T const UTF8CHAR* FAndroidPlatformString::Src
Initial value:
{
        PRAGMA_DISABLE_DEPRECATION_WARNINGS
        return (UTF8CHAR*)Strcpy((ANSICHAR*)Dest, DestCount, (const ANSICHAR*)Src)
Definition at line 635 of file AndroidPlatformString.h.
The documentation for this struct was generated from the following file:
Runtime/Core/Public/Android/AndroidPlatformString.h