Unreal Engine 5.6 C++ API: UE::Sequencer::FOutlinerSizing Struct Reference
UE::Sequencer::FOutlinerSizing Struct Reference
#include "IOutlinerExtension.h"
Public Member Functions
FOutlinerSizing ()=default
FOutlinerSizing (float InHeight)
FOutlinerSizing (float InHeight, float UniformPadding)
void Accumulate (const FOutlinerSizing &Other)
float GetSeparatorHeight () const
float GetTotalHeight () const
Data Fields
EOutlinerSizingFlags Flags = EOutlinerSizingFlags::IncludeSeparator
float Height = 0.f
float PaddingBottom = 0.f
float PaddingTop = 0.f
Friends
bool operator!= (const FOutlinerSizing &A, const FOutlinerSizing &B)
bool operator== (const FOutlinerSizing &A, const FOutlinerSizing &B)
Detailed Description
Definition at line 59 of file IOutlinerExtension.h.
Constructor & Destructor Documentation
FOutlinerSizing() [1/3]
UE::Sequencer::FOutlinerSizing::FOutlinerSizing () default
Referenced by Accumulate(), operator!=, and operator==.
FOutlinerSizing() [2/3]
UE::Sequencer::FOutlinerSizing::FOutlinerSizing (float InHeight) inline
Definition at line 63 of file IOutlinerExtension.h.
References Height.
FOutlinerSizing() [3/3]
UE::Sequencer::FOutlinerSizing::FOutlinerSizing (float InHeight, float UniformPadding) inline
Definition at line 67 of file IOutlinerExtension.h.
References Height, PaddingBottom, and PaddingTop.
Member Function Documentation
Accumulate()
void UE::Sequencer::FOutlinerSizing::Accumulate (const FOutlinerSizing & Other) inline
Definition at line 98 of file IOutlinerExtension.h.
References FOutlinerSizing(), Flags, GetSeparatorHeight(), Height, FMath::Max, Other, PaddingBottom, and PaddingTop.
GetSeparatorHeight()
float UE::Sequencer::FOutlinerSizing::GetSeparatorHeight () const inline
Definition at line 86 of file IOutlinerExtension.h.
References EnumHasAnyFlags(), Flags, and UE::Sequencer::IncludeSeparator.
Referenced by Accumulate(), and GetTotalHeight().
GetTotalHeight()
float UE::Sequencer::FOutlinerSizing::GetTotalHeight () const inline
Definition at line 93 of file IOutlinerExtension.h.
References GetSeparatorHeight(), Height, PaddingBottom, and PaddingTop.
Friends And Related Symbol Documentation
operator!=
bool operator!= (const FOutlinerSizing & A, const FOutlinerSizing & B) friend
Definition at line 81 of file IOutlinerExtension.h.
References FOutlinerSizing(), A, and B.
operator==
bool operator== (const FOutlinerSizing & A, const FOutlinerSizing & B) friend
Definition at line 73 of file IOutlinerExtension.h.
References FOutlinerSizing(), A, and B.
Field Documentation
Flags
EOutlinerSizingFlags UE::Sequencer::FOutlinerSizing::Flags = EOutlinerSizingFlags::IncludeSeparator
Definition at line 114 of file IOutlinerExtension.h.
Referenced by Accumulate(), and GetSeparatorHeight().
Height
float UE::Sequencer::FOutlinerSizing::Height = 0.f
Definition at line 111 of file IOutlinerExtension.h.
Referenced by FOutlinerSizing(), FOutlinerSizing(), Accumulate(), and GetTotalHeight().
PaddingBottom
float UE::Sequencer::FOutlinerSizing::PaddingBottom = 0.f
Definition at line 113 of file IOutlinerExtension.h.
Referenced by FOutlinerSizing(), Accumulate(), and GetTotalHeight().
PaddingTop
float UE::Sequencer::FOutlinerSizing::PaddingTop = 0.f
Definition at line 112 of file IOutlinerExtension.h.
Referenced by FOutlinerSizing(), Accumulate(), and GetTotalHeight().
The documentation for this struct was generated from the following file:
Editor/SequencerCore/Public/MVVM/Extensions/IOutlinerExtension.h