Unreal Engine 5.6 C++ API: Runtime/CoreUObject/Public/StructUtils/InstancedStructContainer.h File Reference
InstancedStructContainer.h File Reference
#include "StructUtils/StructView.h"
#include "InstancedStructContainer.generated.h"
Data Structures
struct TStructOpsTypeTraits< FInstancedStructContainer >
Macros
#define UE_API COREUOBJECT_API
Functions
USTRUCT () struct FInstancedStructContainer
Array of heterogeneous structs.
Macro Definition Documentation
UE_API
#define UE_API COREUOBJECT_API
Definition at line 8 of file InstancedStructContainer.h.
Function Documentation
USTRUCT()
USTRUCT ()
Array of heterogeneous structs.
Can be used as a property, supports serialization, but does not have type customizations (no editing in the UI).
If you need UI editable array of heterogeneous structs, use TArray<FInstancedStruct> instead.
The array item values and the index to an item are stored in one contiguous block of memory. The size required to specific layout of structs is larger than the sum of their sizes due to alignment, and because the index to the structs is stored along with the value memory. Each item takes extra 16 bytes for index. If your items are roughly same size, a TArray<TVariant<>> might be more performant.
Adding new items is more expensive than on regular TArray<>, layout of the structs needs to be updated, and initialization is done via UScriptStruct. Adding and removing items should be done in chunks if possible.
The allocation of new items does not allocate extra space as most array implementations do. Use Reserve() to reserve certain sized buffer in bytes if that is applicable to your use case.
Struct describing an item in the array.
How much memory is used to store info about each item.
Appends items to the array.
Insert new items at specified location.
Remove items at specific location. Does not change memory allocation.
Reserves at least 'NumBytes' for internal storage.
Sets the number of items in the array. Note: this can only shrink the array. Does not change memory allocation.
Returns number of bytes allocated for the array
Empties the array, destroys entities. Does not change memory allocation.
Empties the array, destroys entities. Frees memory.
Returns
true if the instance is correctly initialized.
Number of items in the instance data.
true of the index is in valid range to the array.
view to the struct at specified index.
view to the struct at specified index.
Iterators to enable range-based for loop support.
// Ranged for mutable container for (FStructView View : Container) {}
// Ranged for const container for (FConstStructView View : Container) {}
// Iterator based iteration, allows removing items. for (FInstancedStructContainer::FIterator It = Container.CreateIterator(); It; ++It) { It.RemoveCurrent(); }
Returns
struct view (or const structview) to the item.
true of two iterators point to the same item.
true of the interator points to valid item.
The index of the iterator.
Removes the item pointed by the iterator and adjust the iterator.
Creates iterator to iterate over the array.
Creates const iterator to iterate over the array.
For ranged for, do not use directly.
Type traits
Default minimum alignment for any allocation. Pointer sized to prevent trivial allocations due to alignment.
Each FItem struct is allocated at the end of the buffer (which is aligned to FItem alignment), and they are stride apart.
Returns
offset of the item in the allocated memory.
item based on index.
Memory holding all structs values and items. Values are stored front, and items back.
Number of bytes allocated for the array.
Number of items in the array.
Definition at line 31 of file InstancedStructContainer.h.
References Align, Append(), Ar, begin(), bool, Buffer, check, Container, Count, Empty, end(), GENERATED_BODY, Identical, InContainer, TIndexedContainerIterator< ContainerType, ElementType, SizeType >::Index, IsValid(), Item, Memory, Num, operator!=(), operator*(), operator++(), operator--(), operator=(), Other, Parent, Reset, ScriptStruct, UE_API, and TIsConst< T >::Value.