Unreal Engine 5.6 C++ API: TRelativePtr< T, OffsetType > Struct Template Reference
TRelativePtr< T, OffsetType > Struct Template Reference
#include "RelativePtr.h"
Public Member Functions
TRelativePtr ()
TRelativePtr (const void *BasePtr, const void *ThisPtr)
TRelativePtr (nullptr_t)
operator bool () const
void Reset (const void *BasePtr, const void *ThisPtr)
void Reset (nullptr_t)
T * Resolve (const void *BasePtr) const
template<typename U>
U * Resolve (const void *BasePtr) const
Static Public Attributes
static constexpr OffsetType NullValue = std::numeric_limits<OffsetType>::max()
Private Attributes
OffsetType Offset
Detailed Description
template<typename T, typename OffsetType = int16>
struct TRelativePtr< T, OffsetType >
Definition at line 10 of file RelativePtr.h.
Constructor & Destructor Documentation
TRelativePtr() [1/3]
template<typename T, typename OffsetType = int16> TRelativePtr< T, OffsetType >::TRelativePtr () inline explicit
Definition at line 16 of file RelativePtr.h.
TRelativePtr() [2/3]
template<typename T, typename OffsetType = int16> TRelativePtr< T, OffsetType >::TRelativePtr (nullptr_t) inline explicit
Definition at line 20 of file RelativePtr.h.
TRelativePtr() [3/3]
template<typename T, typename OffsetType = int16> TRelativePtr< T, OffsetType >::TRelativePtr (const void * BasePtr, const void * ThisPtr) inline explicit
Definition at line 24 of file RelativePtr.h.
Member Function Documentation
operator bool()
template<typename T, typename OffsetType = int16> TRelativePtr< T, OffsetType >::operator bool () const inline explicit
Definition at line 29 of file RelativePtr.h.
Reset() [1/2]
template<typename T, typename OffsetType = int16> void TRelativePtr< T, OffsetType >::Reset (const void * BasePtr, const void * ThisPtr) inline
Definition at line 50 of file RelativePtr.h.
Reset() [2/2]
template<typename T, typename OffsetType = int16> void TRelativePtr< T, OffsetType >::Reset (nullptr_t) inline
Definition at line 45 of file RelativePtr.h.
Referenced by UE::MovieScene::FPlaybackCapabilitiesImpl::AddCapability(), UE::MovieScene::FComponentAccess::PreLockComponentData(), UE::MovieScene::FEntityIDAccess::PreLockComponentData(), UE::MovieScene::FErasedOptionalReadAccess::PreLockComponentData(), UE::MovieScene::FErasedReadAccess::PreLockComponentData(), UE::MovieScene::FErasedWriteAccess::PreLockComponentData(), UE::MovieScene::FFilterMatchPassthrough::PreLockComponentData(), and UE::MovieScene::FOptionalComponentAccess::PreLockComponentData().
Resolve() [1/2]
template<typename T, typename OffsetType = int16> T * TRelativePtr< T, OffsetType >::Resolve (const void * BasePtr) const inline
Definition at line 34 of file RelativePtr.h.
Referenced by UE::MovieScene::FPlaybackCapabilitiesImpl::AddCapability(), UE::MovieScene::FEntityIDAccess::ResolvePreLockedComponentData(), UE::MovieScene::FErasedOptionalReadAccess::ResolvePreLockedComponentData(), UE::MovieScene::FErasedReadAccess::ResolvePreLockedComponentData(), UE::MovieScene::FErasedWriteAccess::ResolvePreLockedComponentData(), UE::MovieScene::FFilterMatchPassthrough::ResolvePreLockedComponentData(), UE::MovieScene::TOptionalReadAccess< T >::ResolvePreLockedComponentData(), UE::MovieScene::TOptionalWriteAccess< T >::ResolvePreLockedComponentData(), UE::MovieScene::TReadAccess< T >::ResolvePreLockedComponentData(), and UE::MovieScene::TWriteAccess< T >::ResolvePreLockedComponentData().
Resolve() [2/2]
template<typename T, typename OffsetType = int16> template<typename U> U * TRelativePtr< T, OffsetType >::Resolve (const void * BasePtr) const inline
Definition at line 40 of file RelativePtr.h.
Field Documentation
NullValue
template<typename T, typename OffsetType = int16> OffsetType TRelativePtr< T, OffsetType >::NullValue = std::numeric_limits<OffsetType>::max() static constexpr
Definition at line 12 of file RelativePtr.h.
Offset
template<typename T, typename OffsetType = int16> OffsetType TRelativePtr< T, OffsetType >::Offset private
Definition at line 75 of file RelativePtr.h.
The documentation for this struct was generated from the following file:
Runtime/MovieScene/Public/EntitySystem/RelativePtr.h