Unreal Engine 5.6 C++ API: FPropertyLocalizationDataGatherer::FObjectAndGatherFlags Struct Reference
FPropertyLocalizationDataGatherer::FObjectAndGatherFlags Struct Reference
Public Member Functions
FObjectAndGatherFlags (const UObject *InObject, const EPropertyLocalizationGathererTextFlags InGatherTextFlags)
FORCEINLINE bool operator!= (const FObjectAndGatherFlags &Other) const
FORCEINLINE bool operator== (const FObjectAndGatherFlags &Other) const
Data Fields
EPropertyLocalizationGathererTextFlags GatherTextFlags
uint32 KeyHash
const UObject * Object
Friends
uint32 GetTypeHash (const FObjectAndGatherFlags &Key)
Detailed Description
Definition at line 163 of file PropertyLocalizationDataGathering.h.
Constructor & Destructor Documentation
FObjectAndGatherFlags()
FPropertyLocalizationDataGatherer::FObjectAndGatherFlags::FObjectAndGatherFlags (const UObject * InObject, const EPropertyLocalizationGathererTextFlags InGatherTextFlags) inline
Definition at line 165 of file PropertyLocalizationDataGathering.h.
References GatherTextFlags, GetTypeHash, HashCombine(), KeyHash, and Object.
Referenced by GetTypeHash, operator!=(), and operator==().
Member Function Documentation
operator!=()
FORCEINLINE bool FPropertyLocalizationDataGatherer::FObjectAndGatherFlags::operator!= (const FObjectAndGatherFlags & Other) const inline
Definition at line 180 of file PropertyLocalizationDataGathering.h.
References FObjectAndGatherFlags(), FORCEINLINE, and Other.
operator==()
FORCEINLINE bool FPropertyLocalizationDataGatherer::FObjectAndGatherFlags::operator== (const FObjectAndGatherFlags & Other) const inline
Definition at line 174 of file PropertyLocalizationDataGathering.h.
References FObjectAndGatherFlags(), FORCEINLINE, GatherTextFlags, Object, and Other.
Friends And Related Symbol Documentation
GetTypeHash
uint32 GetTypeHash (const FObjectAndGatherFlags & Key) friend
Definition at line 185 of file PropertyLocalizationDataGathering.h.
References FObjectAndGatherFlags(), and Key.
Referenced by FObjectAndGatherFlags().
Field Documentation
GatherTextFlags
EPropertyLocalizationGathererTextFlags FPropertyLocalizationDataGatherer::FObjectAndGatherFlags::GatherTextFlags
Definition at line 191 of file PropertyLocalizationDataGathering.h.
Referenced by FObjectAndGatherFlags(), and operator==().
KeyHash
uint32 FPropertyLocalizationDataGatherer::FObjectAndGatherFlags::KeyHash
Definition at line 192 of file PropertyLocalizationDataGathering.h.
Referenced by FObjectAndGatherFlags().
Object
const UObject* FPropertyLocalizationDataGatherer::FObjectAndGatherFlags::Object
Definition at line 190 of file PropertyLocalizationDataGathering.h.
Referenced by FObjectAndGatherFlags(), and operator==().
The documentation for this struct was generated from the following file:
Runtime/CoreUObject/Public/Serialization/PropertyLocalizationDataGathering.h