Unreal Engine 5.6 C++ API: UE::MovieScene::FObjectPropertyTraits Struct Reference
UE::MovieScene::FObjectPropertyTraits Struct Reference
#include "MovieSceneTracksComponentTypes.h"
Data Structures
struct FObjectMetadata
Public Types
using MetaDataType = TPropertyMetaData<FObjectMetadata>
using ObjectTraitsImpl = TIndirectPropertyTraits<UObject*, FObjectComponent>
using ParamType = UObject*
using StorageType = FObjectComponent
using TraitsType = FObjectPropertyTraits
Static Public Member Functions
static bool CanAssignValue (const FObjectMetadata &ObjectMetadata, UObject *DesiredValue)
static void GetObjectPropertyValue (const UObject *InObject, FObjectMetadata ObjectMetadata, const FCustomPropertyAccessor &BaseCustomAccessor, FObjectComponent &OutValue)
static void GetObjectPropertyValue (const UObject *InObject, FObjectMetadata ObjectMetadata, const FName &PropertyPath, StorageType &OutValue)
static void GetObjectPropertyValue (const UObject *InObject, FObjectMetadata ObjectMetadata, FTrackInstancePropertyBindings *PropertyBindings, FObjectComponent &OutValue)
static void GetObjectPropertyValue (const UObject *InObject, FObjectMetadata ObjectMetadata, uint16 PropertyOffset, FObjectComponent &OutValue)
static void SetObjectPropertyValue (UObject *InObject, FObjectMetadata ObjectMetadata, const FCustomPropertyAccessor &BaseCustomAccessor, const FObjectComponent &InValue)
static void SetObjectPropertyValue (UObject *InObject, FObjectMetadata ObjectMetadata, FTrackInstancePropertyBindings *PropertyBindings, const FObjectComponent &InValue)
static void SetObjectPropertyValue (UObject *InObject, FObjectMetadata ObjectMetadata, uint16 PropertyOffset, const FObjectComponent &InValue)
Static Public Attributes
static constexpr bool bIsComposite = false
Detailed Description
Definition at line 577 of file MovieSceneTracksComponentTypes.h.
Member Typedef Documentation
MetaDataType
using UE::MovieScene::FObjectPropertyTraits::MetaDataType = TPropertyMetaData<FObjectMetadata>
Definition at line 589 of file MovieSceneTracksComponentTypes.h.
ObjectTraitsImpl
using UE::MovieScene::FObjectPropertyTraits::ObjectTraitsImpl = TIndirectPropertyTraits<UObject*, FObjectComponent>
Definition at line 593 of file MovieSceneTracksComponentTypes.h.
ParamType
using UE::MovieScene::FObjectPropertyTraits::ParamType = UObject*
Definition at line 591 of file MovieSceneTracksComponentTypes.h.
StorageType
using UE::MovieScene::FObjectPropertyTraits::StorageType = FObjectComponent
Definition at line 587 of file MovieSceneTracksComponentTypes.h.
TraitsType
using UE::MovieScene::FObjectPropertyTraits::TraitsType = FObjectPropertyTraits
Definition at line 590 of file MovieSceneTracksComponentTypes.h.
Member Function Documentation
CanAssignValue()
bool UE::MovieScene::FObjectPropertyTraits::CanAssignValue (const FObjectMetadata & ObjectMetadata, UObject * DesiredValue) inline static
Definition at line 613 of file MovieSceneTracksComponentTypes.h.
References UE::MovieScene::FObjectPropertyTraits::FObjectMetadata::bAllowsClear, UObjectBase::GetClass(), UStruct::IsChildOf(), and UE::MovieScene::FObjectPropertyTraits::FObjectMetadata::ObjectClass.
Referenced by SetObjectPropertyValue(), and SetObjectPropertyValue().
GetObjectPropertyValue() [1/4]
void UE::MovieScene::FObjectPropertyTraits::GetObjectPropertyValue (const UObject * InObject, FObjectMetadata ObjectMetadata, const FCustomPropertyAccessor & BaseCustomAccessor, FObjectComponent & OutValue) inline static
Definition at line 595 of file MovieSceneTracksComponentTypes.h.
References UE::MovieScene::TCustomPropertyAccessor< PropertyTraits >::Functions.
GetObjectPropertyValue() [2/4]
void UE::MovieScene::FObjectPropertyTraits::GetObjectPropertyValue (const UObject * InObject, FObjectMetadata ObjectMetadata, const FName & PropertyPath, StorageType & OutValue) inline static
Definition at line 608 of file MovieSceneTracksComponentTypes.h.
References UE::MovieScene::TIndirectPropertyTraits< UObject *, FObjectComponent >::GetObjectPropertyValue().
GetObjectPropertyValue() [3/4]
void UE::MovieScene::FObjectPropertyTraits::GetObjectPropertyValue (const UObject * InObject, FObjectMetadata ObjectMetadata, FTrackInstancePropertyBindings * PropertyBindings, FObjectComponent & OutValue) inline static
Definition at line 604 of file MovieSceneTracksComponentTypes.h.
References UE::MovieScene::TIndirectPropertyTraits< UObject *, FObjectComponent >::GetObjectPropertyValue().
GetObjectPropertyValue() [4/4]
void UE::MovieScene::FObjectPropertyTraits::GetObjectPropertyValue (const UObject * InObject, FObjectMetadata ObjectMetadata, uint16 PropertyOffset, FObjectComponent & OutValue) inline static
Definition at line 600 of file MovieSceneTracksComponentTypes.h.
References UE::MovieScene::TIndirectPropertyTraits< UObject *, FObjectComponent >::GetObjectPropertyValue().
SetObjectPropertyValue() [1/3]
void UE::MovieScene::FObjectPropertyTraits::SetObjectPropertyValue (UObject * InObject, FObjectMetadata ObjectMetadata, const FCustomPropertyAccessor & BaseCustomAccessor, const FObjectComponent & InValue) inline static
Definition at line 630 of file MovieSceneTracksComponentTypes.h.
References UE::MovieScene::TCustomPropertyAccessor< PropertyTraits >::Functions.
SetObjectPropertyValue() [2/3]
void UE::MovieScene::FObjectPropertyTraits::SetObjectPropertyValue (UObject * InObject, FObjectMetadata ObjectMetadata, FTrackInstancePropertyBindings * PropertyBindings, const FObjectComponent & InValue) inline static
Definition at line 642 of file MovieSceneTracksComponentTypes.h.
References CanAssignValue(), UE::MovieScene::FObjectComponent::GetObject(), and UE::MovieScene::TIndirectPropertyTraits< UObject *, FObjectComponent >::SetObjectPropertyValue().
SetObjectPropertyValue() [3/3]
void UE::MovieScene::FObjectPropertyTraits::SetObjectPropertyValue (UObject * InObject, FObjectMetadata ObjectMetadata, uint16 PropertyOffset, const FObjectComponent & InValue) inline static
Definition at line 635 of file MovieSceneTracksComponentTypes.h.
References CanAssignValue(), UE::MovieScene::FObjectComponent::GetObject(), and UE::MovieScene::TIndirectPropertyTraits< UObject *, FObjectComponent >::SetObjectPropertyValue().
Field Documentation
bIsComposite
bool UE::MovieScene::FObjectPropertyTraits::bIsComposite = false static constexpr
Definition at line 579 of file MovieSceneTracksComponentTypes.h.
The documentation for this struct was generated from the following file:
Runtime/MovieSceneTracks/Public/MovieSceneTracksComponentTypes.h