Unreal Engine 5.6 C++ API: UETypeName_Private::FSubstr Struct Reference
UETypeName_Private::FSubstr Struct Reference
#include "GeneratedTypeName.h"
Public Member Functions
constexpr uint32 Len () const
constexpr char operator[] (uint32 Index) const
constexpr FSubstr PopBack (int Num=1) const
constexpr FSubstr PopBackAll (char Ch) const
constexpr FSubstr PopBackAllNot (char Ch) const
constexpr FSubstr PopFront (int Num=1) const
constexpr FSubstr PopFrontAll (char Ch) const
constexpr FSubstr PopFrontAllNot (char Ch) const
Data Fields
uint32 Length
const char * Ptr
Detailed Description
Definition at line 26 of file GeneratedTypeName.h.
Member Function Documentation
Len()
uint32 UETypeName_Private::FSubstr::Len () const inline constexpr
Definition at line 36 of file GeneratedTypeName.h.
References Length.
Referenced by PopBack(), PopBackAll(), PopBackAllNot(), PopFront(), PopFrontAll(), and PopFrontAllNot().
operator[]()
char UETypeName_Private::FSubstr::operator[] (uint32 Index) const inline constexpr
Definition at line 31 of file GeneratedTypeName.h.
References Ptr.
PopBack()
FSubstr UETypeName_Private::FSubstr::PopBack (int Num = 1) const inline constexpr
Definition at line 46 of file GeneratedTypeName.h.
References Len(), Num, and Ptr.
Referenced by UETypeName_Private::GetTypeSubstr(), PopBackAll(), and PopBackAllNot().
PopBackAll()
FSubstr UETypeName_Private::FSubstr::PopBackAll (char Ch) const inline constexpr
Definition at line 61 of file GeneratedTypeName.h.
References Len(), PopBack(), PopBackAll(), and Ptr.
Referenced by UETypeName_Private::GetTypeSubstr(), and PopBackAll().
PopBackAllNot()
FSubstr UETypeName_Private::FSubstr::PopBackAllNot (char Ch) const inline constexpr
Definition at line 66 of file GeneratedTypeName.h.
References Len(), PopBack(), PopBackAllNot(), and Ptr.
Referenced by UETypeName_Private::GetTypeSubstr(), and PopBackAllNot().
PopFront()
FSubstr UETypeName_Private::FSubstr::PopFront (int Num = 1) const inline constexpr
Definition at line 41 of file GeneratedTypeName.h.
References Len(), Num, and Ptr.
Referenced by UETypeName_Private::GetTypeSubstr(), PopFrontAll(), and PopFrontAllNot().
PopFrontAll()
FSubstr UETypeName_Private::FSubstr::PopFrontAll (char Ch) const inline constexpr
Definition at line 51 of file GeneratedTypeName.h.
References Len(), PopFront(), PopFrontAll(), and Ptr.
Referenced by UETypeName_Private::GetTypeSubstr(), and PopFrontAll().
PopFrontAllNot()
FSubstr UETypeName_Private::FSubstr::PopFrontAllNot (char Ch) const inline constexpr
Definition at line 56 of file GeneratedTypeName.h.
References Len(), PopFront(), PopFrontAllNot(), and Ptr.
Referenced by UETypeName_Private::GetTypeSubstr(), and PopFrontAllNot().
Field Documentation
Length
uint32 UETypeName_Private::FSubstr::Length
Definition at line 29 of file GeneratedTypeName.h.
Referenced by Len().
Ptr
const char* UETypeName_Private::FSubstr::Ptr
Definition at line 28 of file GeneratedTypeName.h.
Referenced by operator[](), PopBack(), PopBackAll(), PopBackAllNot(), PopFront(), PopFrontAll(), and PopFrontAllNot().
The documentation for this struct was generated from the following file:
Runtime/Core/Public/Misc/GeneratedTypeName.h