Unreal Engine 5.6 C++ API: FWindowsPlatformAtomics Struct Reference
FWindowsPlatformAtomics Struct Reference
Windows implementation of the Atomics OS functions.
#include "WindowsPlatformAtomics.h"
Static Public Member Functions
static FORCEINLINE int16 AtomicRead (volatile const int16 *Src)
static FORCEINLINE int32 AtomicRead (volatile const int32 *Src)
static FORCEINLINE int64 AtomicRead (volatile const int64 *Src)
static FORCEINLINE int8 AtomicRead (volatile const int8 *Src)
static FORCEINLINE int16 AtomicRead_Relaxed (volatile const int16 *Src)
static FORCEINLINE int32 AtomicRead_Relaxed (volatile const int32 *Src)
static FORCEINLINE int64 AtomicRead_Relaxed (volatile const int64 *Src)
static FORCEINLINE int8 AtomicRead_Relaxed (volatile const int8 *Src)
static FORCEINLINE void AtomicStore (volatile int16 *Src, int16 Val)
static FORCEINLINE void AtomicStore (volatile int32 *Src, int32 Val)
static FORCEINLINE void AtomicStore (volatile int64 *Src, int64 Val)
static FORCEINLINE void AtomicStore (volatile int8 *Src, int8 Val)
static FORCEINLINE void AtomicStore_Relaxed (volatile int16 *Src, int16 Val)
static FORCEINLINE void AtomicStore_Relaxed (volatile int32 *Src, int32 Val)
static FORCEINLINE void AtomicStore_Relaxed (volatile int64 *Src, int64 Val)
static FORCEINLINE void AtomicStore_Relaxed (volatile int8 *Src, int8 Val)
static FORCEINLINE bool CanUseCompareExchange128 ()
static FORCEINLINE int16 InterlockedAdd (volatile int16 *Value, int16 Amount)
static FORCEINLINE int32 InterlockedAdd (volatile int32 *Value, int32 Amount)
static FORCEINLINE int64 InterlockedAdd (volatile int64 *Value, int64 Amount)
static FORCEINLINE int8 InterlockedAdd (volatile int8 *Value, int8 Amount)
static FORCEINLINE int16 InterlockedAnd (volatile int16 *Value, const int16 AndValue)
static FORCEINLINE int32 InterlockedAnd (volatile int32 *Value, const int32 AndValue)
static FORCEINLINE int64 InterlockedAnd (volatile int64 *Value, const int64 AndValue)
static FORCEINLINE int8 InterlockedAnd (volatile int8 *Value, const int8 AndValue)
static FORCEINLINE int16 InterlockedCompareExchange (volatile int16 *Dest, int16 Exchange, int16 Comparand)
static FORCEINLINE int32 InterlockedCompareExchange (volatile int32 *Dest, int32 Exchange, int32 Comparand)
static FORCEINLINE int64 InterlockedCompareExchange (volatile int64 *Dest, int64 Exchange, int64 Comparand)
static FORCEINLINE int8 InterlockedCompareExchange (volatile int8 *Dest, int8 Exchange, int8 Comparand)
static FORCEINLINE void * InterlockedCompareExchangePointer (void *volatile *Dest, void *Exchange, void *Comparand)
The function compares the Destination value with the Comparand value:
static FORCEINLINE int16 InterlockedDecrement (volatile int16 *Value)
static FORCEINLINE int32 InterlockedDecrement (volatile int32 *Value)
static FORCEINLINE int64 InterlockedDecrement (volatile int64 *Value)
static FORCEINLINE int8 InterlockedDecrement (volatile int8 *Value)
static FORCEINLINE int16 InterlockedExchange (volatile int16 *Value, int16 Exchange)
static FORCEINLINE int32 InterlockedExchange (volatile int32 *Value, int32 Exchange)
static FORCEINLINE int64 InterlockedExchange (volatile int64 *Value, int64 Exchange)
static FORCEINLINE int8 InterlockedExchange (volatile int8 *Value, int8 Exchange)
static FORCEINLINE void * InterlockedExchangePtr (void *volatile *Dest, void *Exchange)
static FORCEINLINE int16 InterlockedIncrement (volatile int16 *Value)
static FORCEINLINE int32 InterlockedIncrement (volatile int32 *Value)
static FORCEINLINE int64 InterlockedIncrement (volatile int64 *Value)
static FORCEINLINE int8 InterlockedIncrement (volatile int8 *Value)
static FORCEINLINE int16 InterlockedOr (volatile int16 *Value, const int16 OrValue)
static FORCEINLINE int32 InterlockedOr (volatile int32 *Value, const int32 OrValue)
static FORCEINLINE int64 InterlockedOr (volatile int64 *Value, const int64 OrValue)
static FORCEINLINE int8 InterlockedOr (volatile int8 *Value, const int8 OrValue)
static FORCEINLINE int16 InterlockedXor (volatile int16 *Value, const int16 XorValue)
static FORCEINLINE int32 InterlockedXor (volatile int32 *Value, const int32 XorValue)
static FORCEINLINE int64 InterlockedXor (volatile int64 *Value, const int64 XorValue)
static FORCEINLINE int8 InterlockedXor (volatile int8 *Value, const int8 XorValue)
Static Public Member Functions inherited from FGenericPlatformAtomics
static FORCEINLINE bool CanUseCompareExchange128 ()
Static Protected Member Functions
static void HandleAtomicsFailure (const TCHAR *InFormat,...)
Handles atomics function failure.
Static Protected Member Functions inherited from FGenericPlatformAtomics
static bool IsAligned (const volatile void *Ptr, const uint32 Alignment=sizeof(void *))
Checks if a pointer is aligned and can be used with atomic functions.
Detailed Description
Windows implementation of the Atomics OS functions.
Definition at line 26 of file WindowsPlatformAtomics.h.
Member Function Documentation
AtomicRead() [1/4]
FORCEINLINE int16 FWindowsPlatformAtomics::AtomicRead (volatile const int16 * Src) inline static
Definition at line 302 of file WindowsPlatformAtomics.h.
References FORCEINLINE.
AtomicRead() [2/4]
FORCEINLINE int32 FWindowsPlatformAtomics::AtomicRead (volatile const int32 * Src) inline static
Definition at line 307 of file WindowsPlatformAtomics.h.
References FORCEINLINE.
AtomicRead() [3/4]
FORCEINLINE int64 FWindowsPlatformAtomics::AtomicRead (volatile const int64 * Src) inline static
Definition at line 312 of file WindowsPlatformAtomics.h.
References FORCEINLINE.
AtomicRead() [4/4]
FORCEINLINE int8 FWindowsPlatformAtomics::AtomicRead (volatile const int8 * Src) inline static
Definition at line 297 of file WindowsPlatformAtomics.h.
References FORCEINLINE.
AtomicRead_Relaxed() [1/4]
FORCEINLINE int16 FWindowsPlatformAtomics::AtomicRead_Relaxed (volatile const int16 * Src) inline static
Definition at line 322 of file WindowsPlatformAtomics.h.
References FORCEINLINE.
AtomicRead_Relaxed() [2/4]
FORCEINLINE int32 FWindowsPlatformAtomics::AtomicRead_Relaxed (volatile const int32 * Src) inline static
Definition at line 327 of file WindowsPlatformAtomics.h.
References FORCEINLINE.
AtomicRead_Relaxed() [3/4]
FORCEINLINE int64 FWindowsPlatformAtomics::AtomicRead_Relaxed (volatile const int64 * Src) inline static
Definition at line 332 of file WindowsPlatformAtomics.h.
References FORCEINLINE, and InterlockedCompareExchange.
AtomicRead_Relaxed() [4/4]
FORCEINLINE int8 FWindowsPlatformAtomics::AtomicRead_Relaxed (volatile const int8 * Src) inline static
Definition at line 317 of file WindowsPlatformAtomics.h.
References FORCEINLINE.
AtomicStore() [1/4]
FORCEINLINE void FWindowsPlatformAtomics::AtomicStore (volatile int16 * Src, int16 Val) inline static
Definition at line 346 of file WindowsPlatformAtomics.h.
References FORCEINLINE.
AtomicStore() [2/4]
FORCEINLINE void FWindowsPlatformAtomics::AtomicStore (volatile int32 * Src, int32 Val) inline static
Definition at line 351 of file WindowsPlatformAtomics.h.
References FORCEINLINE.
AtomicStore() [3/4]
FORCEINLINE void FWindowsPlatformAtomics::AtomicStore (volatile int64 * Src, int64 Val) inline static
Definition at line 356 of file WindowsPlatformAtomics.h.
References FORCEINLINE.
AtomicStore() [4/4]
FORCEINLINE void FWindowsPlatformAtomics::AtomicStore (volatile int8 * Src, int8 Val) inline static
Definition at line 341 of file WindowsPlatformAtomics.h.
References FORCEINLINE.
AtomicStore_Relaxed() [1/4]
FORCEINLINE void FWindowsPlatformAtomics::AtomicStore_Relaxed (volatile int16 * Src, int16 Val) inline static
Definition at line 366 of file WindowsPlatformAtomics.h.
References FORCEINLINE.
AtomicStore_Relaxed() [2/4]
FORCEINLINE void FWindowsPlatformAtomics::AtomicStore_Relaxed (volatile int32 * Src, int32 Val) inline static
Definition at line 371 of file WindowsPlatformAtomics.h.
References FORCEINLINE.
AtomicStore_Relaxed() [3/4]
FORCEINLINE void FWindowsPlatformAtomics::AtomicStore_Relaxed (volatile int64 * Src, int64 Val) inline static
Definition at line 376 of file WindowsPlatformAtomics.h.
References FORCEINLINE, and InterlockedExchange.
AtomicStore_Relaxed() [4/4]
FORCEINLINE void FWindowsPlatformAtomics::AtomicStore_Relaxed (volatile int8 * Src, int8 Val) inline static
Definition at line 361 of file WindowsPlatformAtomics.h.
References FORCEINLINE.
CanUseCompareExchange128()
FORCEINLINE bool FWindowsPlatformAtomics::CanUseCompareExchange128 () inline static
Returns
true, if the processor we are running on can execute compare and exchange 128-bit operation.
See also
cmpxchg16b, early AMD64 processors don't support this operation.
Definition at line 441 of file WindowsPlatformAtomics.h.
References FORCEINLINE, and WINDOWS_PF_COMPARE_EXCHANGE128.
HandleAtomicsFailure()
void FWindowsPlatformAtomics::HandleAtomicsFailure (const TCHAR * InFormat, ...) static protected
Handles atomics function failure.
Since 'check' has not yet been declared here we need to call external function to use it.
Parameters
InFormat - The string format string.
Referenced by InterlockedCompareExchange(), InterlockedCompareExchangePointer(), and InterlockedExchangePtr().
InterlockedAdd() [1/4]
FORCEINLINE int16 FWindowsPlatformAtomics::InterlockedAdd (volatile int16 * Value, int16 Amount) inline static
Definition at line 103 of file WindowsPlatformAtomics.h.
References FORCEINLINE, and Value.
InterlockedAdd() [2/4]
FORCEINLINE int32 FWindowsPlatformAtomics::InterlockedAdd (volatile int32 * Value, int32 Amount) inline static
Definition at line 108 of file WindowsPlatformAtomics.h.
References FORCEINLINE, and Value.
InterlockedAdd() [3/4]
FORCEINLINE int64 FWindowsPlatformAtomics::InterlockedAdd (volatile int64 * Value, int64 Amount) inline static
Definition at line 113 of file WindowsPlatformAtomics.h.
References FORCEINLINE, and Value.
InterlockedAdd() [4/4]
FORCEINLINE int8 FWindowsPlatformAtomics::InterlockedAdd (volatile int8 * Value, int8 Amount) inline static
Definition at line 98 of file WindowsPlatformAtomics.h.
References FORCEINLINE, and Value.
InterlockedAnd() [1/4]
FORCEINLINE int16 FWindowsPlatformAtomics::InterlockedAnd (volatile int16 * Value, const int16 AndValue) inline static
Definition at line 206 of file WindowsPlatformAtomics.h.
References FORCEINLINE, and Value.
InterlockedAnd() [2/4]
FORCEINLINE int32 FWindowsPlatformAtomics::InterlockedAnd (volatile int32 * Value, const int32 AndValue) inline static
Definition at line 211 of file WindowsPlatformAtomics.h.
References FORCEINLINE, and Value.
InterlockedAnd() [3/4]
FORCEINLINE int64 FWindowsPlatformAtomics::InterlockedAnd (volatile int64 * Value, const int64 AndValue) inline static
Definition at line 216 of file WindowsPlatformAtomics.h.
References FORCEINLINE, and Value.
InterlockedAnd() [4/4]
FORCEINLINE int8 FWindowsPlatformAtomics::InterlockedAnd (volatile int8 * Value, const int8 AndValue) inline static
Definition at line 201 of file WindowsPlatformAtomics.h.
References FORCEINLINE, and Value.
InterlockedCompareExchange() [1/4]
FORCEINLINE int16 FWindowsPlatformAtomics::InterlockedCompareExchange (volatile int16 * Dest, int16 Exchange, int16 Comparand) inline static
Definition at line 179 of file WindowsPlatformAtomics.h.
References Exchange(), and FORCEINLINE.
InterlockedCompareExchange() [2/4]
FORCEINLINE int32 FWindowsPlatformAtomics::InterlockedCompareExchange (volatile int32 * Dest, int32 Exchange, int32 Comparand) inline static
Definition at line 184 of file WindowsPlatformAtomics.h.
References Exchange(), and FORCEINLINE.
InterlockedCompareExchange() [3/4]
FORCEINLINE int64 FWindowsPlatformAtomics::InterlockedCompareExchange (volatile int64 * Dest, int64 Exchange, int64 Comparand) inline static
Definition at line 189 of file WindowsPlatformAtomics.h.
References Exchange(), FORCEINLINE, HandleAtomicsFailure(), FGenericPlatformAtomics::IsAligned(), and TEXT.
InterlockedCompareExchange() [4/4]
FORCEINLINE int8 FWindowsPlatformAtomics::InterlockedCompareExchange (volatile int8 * Dest, int8 Exchange, int8 Comparand) inline static
Definition at line 174 of file WindowsPlatformAtomics.h.
References Exchange(), and FORCEINLINE.
InterlockedCompareExchangePointer()
FORCEINLINE void * FWindowsPlatformAtomics::InterlockedCompareExchangePointer (void *volatile * Dest, void * Exchange, void * Comparand) inline static
The function compares the Destination value with the Comparand value:
If the Destination value is equal to the Comparand value, the Exchange value is stored in the address specified by Destination,
Otherwise, the initial value of the Destination parameter is stored in the address specified specified by Comparand.
Returns
true if Comparand equals the original value of the Destination parameter, or false if Comparand does not equal the original value of the Destination parameter.
Early AMD64 processors lacked the CMPXCHG16B instruction. To determine whether the processor supports this operation, call the IsProcessorFeaturePresent function with PF_COMPARE64_EXCHANGE128.
Definition at line 425 of file WindowsPlatformAtomics.h.
References Exchange(), FORCEINLINE, HandleAtomicsFailure(), FGenericPlatformAtomics::IsAligned(), and TEXT.
InterlockedDecrement() [1/4]
FORCEINLINE int16 FWindowsPlatformAtomics::InterlockedDecrement (volatile int16 * Value) inline static
Definition at line 71 of file WindowsPlatformAtomics.h.
References FORCEINLINE, and Value.
InterlockedDecrement() [2/4]
FORCEINLINE int32 FWindowsPlatformAtomics::InterlockedDecrement (volatile int32 * Value) inline static
Definition at line 76 of file WindowsPlatformAtomics.h.
References FORCEINLINE, and Value.
InterlockedDecrement() [3/4]
FORCEINLINE int64 FWindowsPlatformAtomics::InterlockedDecrement (volatile int64 * Value) inline static
Definition at line 81 of file WindowsPlatformAtomics.h.
References FORCEINLINE, and Value.
InterlockedDecrement() [4/4]
FORCEINLINE int8 FWindowsPlatformAtomics::InterlockedDecrement (volatile int8 * Value) inline static
Definition at line 66 of file WindowsPlatformAtomics.h.
References FORCEINLINE, and Value.
InterlockedExchange() [1/4]
FORCEINLINE int16 FWindowsPlatformAtomics::InterlockedExchange (volatile int16 * Value, int16 Exchange) inline static
Definition at line 135 of file WindowsPlatformAtomics.h.
References Exchange(), FORCEINLINE, and Value.
InterlockedExchange() [2/4]
FORCEINLINE int32 FWindowsPlatformAtomics::InterlockedExchange (volatile int32 * Value, int32 Exchange) inline static
Definition at line 140 of file WindowsPlatformAtomics.h.
References Exchange(), FORCEINLINE, and Value.
InterlockedExchange() [3/4]
FORCEINLINE int64 FWindowsPlatformAtomics::InterlockedExchange (volatile int64 * Value, int64 Exchange) inline static
Definition at line 145 of file WindowsPlatformAtomics.h.
References Exchange(), FORCEINLINE, and Value.
InterlockedExchange() [4/4]
FORCEINLINE int8 FWindowsPlatformAtomics::InterlockedExchange (volatile int8 * Value, int8 Exchange) inline static
Definition at line 130 of file WindowsPlatformAtomics.h.
References Exchange(), FORCEINLINE, and Value.
InterlockedExchangePtr()
FORCEINLINE void * FWindowsPlatformAtomics::InterlockedExchangePtr (void *volatile * Dest, void * Exchange) inline static
Definition at line 162 of file WindowsPlatformAtomics.h.
References Exchange(), FORCEINLINE, HandleAtomicsFailure(), FGenericPlatformAtomics::IsAligned(), and TEXT.
InterlockedIncrement() [1/4]
FORCEINLINE int16 FWindowsPlatformAtomics::InterlockedIncrement (volatile int16 * Value) inline static
Definition at line 39 of file WindowsPlatformAtomics.h.
References FORCEINLINE, and Value.
InterlockedIncrement() [2/4]
FORCEINLINE int32 FWindowsPlatformAtomics::InterlockedIncrement (volatile int32 * Value) inline static
Definition at line 44 of file WindowsPlatformAtomics.h.
References FORCEINLINE, and Value.
InterlockedIncrement() [3/4]
FORCEINLINE int64 FWindowsPlatformAtomics::InterlockedIncrement (volatile int64 * Value) inline static
Definition at line 49 of file WindowsPlatformAtomics.h.
References FORCEINLINE, and Value.
InterlockedIncrement() [4/4]
FORCEINLINE int8 FWindowsPlatformAtomics::InterlockedIncrement (volatile int8 * Value) inline static
Definition at line 34 of file WindowsPlatformAtomics.h.
References FORCEINLINE, and Value.
InterlockedOr() [1/4]
FORCEINLINE int16 FWindowsPlatformAtomics::InterlockedOr (volatile int16 * Value, const int16 OrValue) inline static
Definition at line 238 of file WindowsPlatformAtomics.h.
References FORCEINLINE, and Value.
InterlockedOr() [2/4]
FORCEINLINE int32 FWindowsPlatformAtomics::InterlockedOr (volatile int32 * Value, const int32 OrValue) inline static
Definition at line 243 of file WindowsPlatformAtomics.h.
References FORCEINLINE, and Value.
InterlockedOr() [3/4]
FORCEINLINE int64 FWindowsPlatformAtomics::InterlockedOr (volatile int64 * Value, const int64 OrValue) inline static
Definition at line 248 of file WindowsPlatformAtomics.h.
References FORCEINLINE, and Value.
InterlockedOr() [4/4]
FORCEINLINE int8 FWindowsPlatformAtomics::InterlockedOr (volatile int8 * Value, const int8 OrValue) inline static
Definition at line 233 of file WindowsPlatformAtomics.h.
References FORCEINLINE, and Value.
InterlockedXor() [1/4]
FORCEINLINE int16 FWindowsPlatformAtomics::InterlockedXor (volatile int16 * Value, const int16 XorValue) inline static
Definition at line 270 of file WindowsPlatformAtomics.h.
References FORCEINLINE, and Value.
InterlockedXor() [2/4]
FORCEINLINE int32 FWindowsPlatformAtomics::InterlockedXor (volatile int32 * Value, const int32 XorValue) inline static
Definition at line 275 of file WindowsPlatformAtomics.h.
References FORCEINLINE, and Value.
InterlockedXor() [3/4]
FORCEINLINE int64 FWindowsPlatformAtomics::InterlockedXor (volatile int64 * Value, const int64 XorValue) inline static
Definition at line 280 of file WindowsPlatformAtomics.h.
References FORCEINLINE, and Value.
InterlockedXor() [4/4]
FORCEINLINE int8 FWindowsPlatformAtomics::InterlockedXor (volatile int8 * Value, const int8 XorValue) inline static
Definition at line 265 of file WindowsPlatformAtomics.h.
References FORCEINLINE, and Value.
The documentation for this struct was generated from the following file:
Runtime/Core/Public/Windows/WindowsPlatformAtomics.h